### ISSUE TITLE
Live progress output in NodeJS API

### ISSUE THREAD

**Issue by IngwiePhoenix** [webpack/webpack#1000]
I'd like to know if it was possible to get a live output (printing while things happen) when using the NodeJS API? As far as I am aware, the `webpack` cli does that but I couldn't figure out how it did it.

Kind regards, Ingwie

**Comment by sokra** [comment]
see `ProgressPlugin`

**Comment by IngwiePhoenix** [comment]
+2. Should be on the official documentation page also.

**Comment by DelvarWorld** [comment]
It would be nice to reopen this as a placeholder for updating the documentation.

**Comment by DelvarWorld** [comment]
FYI since it's not even documented here: http://webpack.github.io/docs/list-of-plugins.html

    var ProgressPlugin = require('webpack/lib/ProgressPlugin');

is how you require it

**Comment by DelvarWorld** [comment]
Mmm I lied, this plugin just takes a callback with a progress amount. There is currently no way to get the actual progress bar using node webpack.

Suggest reopening to add progress to the node api :)

**Comment by IngwiePhoenix** [comment]
Hm? I can use it just fine. O.o

Require: http://git.ingwie.me/ingwie/bird3/blob/master/util/webpack.config.js#L30
Use: http://git.ingwie.me/ingwie/bird3/blob/master/util/webpack.config.js#L128-132

**Comment by lexaurin** [comment]
1) @DelvarWorld Just added missing documentation to wiki https://github.com/webpack/docs/wiki/list-of-plugins#progressplugin

2) @DelvarWorld No need to require plugin itself, just use it from webpack module:
```
var webpack = require('webpack');

plugins: [
    new webpack.ProgressPlugin(function handler(percentage, msg) {/* ... */})
]
```
3) @DelvarWorld You're right there is now way to use it in node without specifying your own callback and using built in callback like in CLI  `--progress` so I made a pull request, hope @sokra will merge it.
After that it will be possible to use plugin with just default handler:
```
plugins: [
    new webpack.ProgressPlugin()
]
```

**Comment by TheLarkInn** [comment]
I'm using it currently like this: 

```
const webpack = require('webpack');
const webpackConfig = require('../tasks/webpack-build-config');
const webpackCompiler = webpack(webpackConfig);
const ProgressPlugin = require('webpack/lib/ProgressPlugin');

webpackCompiler.apply(new ProgressPlugin({
  profile: true
}));
```

**Comment by LucasIcarus** [comment]
@lexaurin Should the arg in new ProgressPlugin still be a handler function or the usage mentioned above is for webpack 2.0+?
