### ISSUE TITLE
Change the logic of MinChunkSizePlugin

### ISSUE THREAD

**Issue by Airkro** [webpack/webpack#10013]
## Feature request

**What is the expected behavior?**
Merge chunks what too small together. Don't merge async chunks to initial chunks.

**What is motivation or use case for adding/changing the behavior?**
Currently, webpack assigns small chunks to large chunks, whatever they are initial or async.

**How should this be implemented in your opinion?**
Add an option to avoid breaking change.

**Are you willing to work on this yourself?**
no

**Comment by Airkro** [comment]
Can anyone reopen this?

**Comment by evilebottnawi** [comment]
@Airkro You can setup it using `splitChunks` (there are a lot of options to do it)

**Comment by Airkro** [comment]
@evilebottnawi 

I‘m already using `splitChunks` and `MinChunkSizePlugin`. I have many small async chunks in my project, some pages just too small. But `MinChunkSizePlugin` didn't merge them together, it merges them into every initial chunk. I try many options, it didn't work.
