### ISSUE TITLE
Watch doesn't recompile on files added with more important multiple alias

### ISSUE THREAD

**Issue by minimit** [webpack/webpack#10015]
# Bug report

**What is the current behavior?**

When using multiple aliases on webpack 5, there's an issue when adding new files when having multiple aliases, webpack doesn't trigger recompile

**If the current behavior is a bug, please provide the steps to reproduce.**

Using multiple alias

```
  resolve: {
    unsafeCache: false,
    alias: {
      'customFolder': [
        path.resolve(__dirname, './dist/customFolder'),
        path.resolve(__dirname, './node_modules/customFolder')
      ],
    },
  },
```

When watch is running and you have only `node_modules/customFolder/test.css`, if you add `dist/customFolder/test.css` as a new file it sould recompile because the first alias has precedence to the second one.

**What is the expected behavior?**

Watch should recompile the files using `dist/customFolder/test.css`

**Other relevant information:**
webpack version:  webpack@5.0.0-beta.7
Node.js version: v10.16.3
Operating System: macos 10.13.6 (17G8037)
Additional tools:

**Comment by evilebottnawi** [comment]
@minimit Can you write about it here https://github.com/webpack/webpack/issues/9802, we keep feedback for webpack@5 in one issue to avoid a lot of issue and avoid house cleaning in future

**Comment by minimit** [comment]
Ok closing this so
