### ISSUE TITLE
Webpack bundling wrong file when using custom loader

### ISSUE THREAD

**Issue by felipellrocha** [webpack/webpack#10014]
# Bug report

**What is the current behavior?**
I have created a custom loader. It transforms `.proto` files into typescript that I can import and use.
I've verified that the typescript is generated correctly, although the problem now is that when I open my `bundle.js` I see multiple `index.ts` files. This is a express app, so it tries to bind to port 8000 multiple times, and the application never loads (is how I found out about the issue).
Typing seems to work just fine (although I haven't verified that).

**If the current behavior is a bug, please provide the steps to reproduce.**
Not sure how to reproduce except creating a new loader, and seeing if bundles the correct data, or some other file in the bundle.

**What is the expected behavior?**
I would see the compiled typescript file I have generated from my `.proto` file included in the final bundle.

**Other relevant information:**
webpack version:  4.41.2
Node.js version: v12.12.0
Operating System: Docker Container: node:12-slim
Additional tools:

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by felipellrocha** [comment]
Will put a gist together. In the meantime, it seems like if I emit a file on my loader, I get the correct data out of it. It's only during bundling that I don't get the appropriate data.

**Comment by felipellrocha** [comment]
https://gist.github.com/felipellrocha/4c57346f4bec5f0ea6ffc96ae15b2374

**Comment by felipellrocha** [comment]
Solved it, but not exactly sure how. I now know the issue was with `ts-loader`. If I replaced it with `happy-pack` then things started to work normally.

**Comment by sokra** [comment]
The ts-loader is not chain-able. This is a known limitation of the ts-loader, as far as I know the problem is in typescript itself.
