### ISSUE TITLE
How to make output JS file without dependency wrapper?

### ISSUE THREAD

**Issue by vaniljs** [webpack/webpack#10028]
Hi!
I've asked on several forums, Stackoverflow, Gitter, and a few wizards. 
But no one gives an answer.
You are my last hope. 

How can I make an output JS file without wrapping module dependencies? 
They're huge. 
I just need to output console.log, but unnecessary long paper is added.

https://ru.stackoverflow.com/questions/1046018/%D0%9A%D0%B0%D0%BA-%D1%83%D0%B1%D1%80%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B2%D0%B8%D1%81%D0%B8%D0%BC%D0%BE%D1%81%D1%82%D0%B8-%D0%B2-%D1%81%D0%BA%D0%BE%D0%BC%D0%BF%D0%B8%D0%BB%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%BD%D0%BE%D0%BC-%D1%84%D0%B0%D0%B9%D0%BB%D0%B5-js-%D1%83-webpack

**Comment by vaniljs** [comment]
А gulp прекрасно выведет только console.log() без лишнего кода

**Comment by sokra** [comment]
webpack 5 will only include runtime code neccessary.

**Comment by evilebottnawi** [comment]
Also if you don't need bundle your code you can use terser CLI
