### ISSUE TITLE
Errors should output to STDERR (bis)

### ISSUE THREAD

**Issue by hogmoru** [webpack/webpack#10022]
# Bug report

**What is the current behavior?**

Webpack prints everything to stdout, including errors.

It's a problem when webpack is used by another tool in a build process: that tool cannot extract the error messages, only detect that there was an error... or do some guesswork like "Upon non-zero exit code with empty stderr, let's use stdout", as I implemented for Rush, but the issue was reported by other tools, and it'd be better to fix it in Webpack itself.

See also #1278

**If the current behavior is a bug, please provide the steps to reproduce.**

See [this reproducible test repo](https://github.com/hogmoru/webpack-nostderr)

Clone it, `npm install`, `npm run build`.

**What is the expected behavior?**

The build tool expects Webpack to print errors to stderr.

**Other relevant information:**
webpack version:  4.41.2
Node.js version: 12.13.1
Operating System: macOS Catalina
Additional tools: tools known to have a problem with that: Rush, webpacker (Ruby on Rails)

**Comment by hogmoru** [comment]
One might argue that this would be a breaking behavior change.

In that case, please consider turning this bug report into a feature request, to have webpack support an option to print errors to stderr, that other build tools would have to use, e.g. `webpack --print-errors-to-stderr`.

**Comment by hogmoru** [comment]
Thanks for heads up @webpack-bot … Here's a bump.

This would be so nice in Webpack 5.

**Comment by andy1547** [comment]
Can this be reopened, thanks!

**Comment by pr0t4zy** [comment]
+1 for reopening.

**Comment by vankop** [comment]
basically you should use stats object

**Comment by vankop** [comment]
I think this is breaking change..

**Comment by alexander-akait** [comment]
@vankop errors are part of stats printing, so it is expected to get them in stdout, stats object is not error, we still print errors in stderr, but only errors inside webpack, don't think we should change it

**Comment by vankop** [comment]
>  we still print errors in stderr

we don't do this ( at least this what issue about )
