### ISSUE TITLE
No memory for yarn build

### ISSUE THREAD

**Issue by abhinavmandala** [webpack/webpack#10020]
Getting below issue when running yarn build in mac:

<--- Last few GCs --->

[22700:0x103001000]   194082 ms: Mark-sweep 1323.2 (1462.2) -> 1323.1 (1463.2) MB, 1325.4 / 0.0 ms  allocation failure GC in old space requested
[22700:0x103001000]   195424 ms: Mark-sweep 1323.1 (1463.2) -> 1323.0 (1426.7) MB, 1341.3 / 0.0 ms  last resort GC in old space requested
[22700:0x103001000]   196732 ms: Mark-sweep 1323.0 (1426.7) -> 1323.0 (1426.2) MB, 1308.2 / 0.0 ms  last resort GC in old space requested

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x90b638258b9 <JSObject>
    1: push(this=0x90b5b1b76c1 <JSArray[171718]>)
    2: /* anonymous */(aka /* anonymous */) [/Users/amandala/Documents/code/a/news-bits/node_modules/webpack-sources/lib/applySourceMap.js:~58] [pc=0x2dd689837877](this=0x90bbc9022d1 <undefined>,chunk=0x90b6d4c0289 <String[13]: configurable,>,middleMapping=0x90bca40a949 <Object map = 0x90b71908191>)
    3: walk(aka SourceNode_walk) [/Users/amandal...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/Users/amandala/.nvm/versions/node/v8.14.0/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/Users/amandala/.nvm/versions/node/v8.14.0/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/Users/amandala/.nvm/versions/node/v8.14.0/bin/node]
 4: v8::internal::Factory::NewUninitializedFixedArray(int) [/Users/amandala/.nvm/versions/node/v8.14.0/bin/node]
 5: v8::internal::(anonymous namespace)::ElementsAccessorBase<v8::internal::(anonymous namespace)::FastPackedObjectElementsAccessor, v8::internal::(anonymous namespace)::ElementsKindTraits<(v8::internal::ElementsKind)2> >::ConvertElementsWithCapacity(v8::internal::Handle<v8::internal::JSObject>, v8::internal::Handle<v8::internal::FixedArrayBase>, v8::internal::ElementsKind, unsigned int, unsigned int, unsigned int, int) [/Users/amandala/.nvm/versions/node/v8.14.0/bin/node]
 6: v8::internal::(anonymous namespace)::ElementsAccessorBase<v8::internal::(anonymous namespace)::FastPackedObjectElementsAccessor, v8::internal::(anonymous namespace)::ElementsKindTraits<(v8::internal::ElementsKind)2> >::GrowCapacityAndConvertImpl(v8::internal::Handle<v8::internal::JSObject>, unsigned int) [/Users/amandala/.nvm/versions/node/v8.14.0/bin/node]
 7: v8::internal::(anonymous namespace)::ElementsAccessorBase<v8::internal::(anonymous namespace)::FastPackedObjectElementsAccessor, v8::internal::(anonymous namespace)::ElementsKindTraits<(v8::internal::ElementsKind)2> >::Add(v8::internal::Handle<v8::internal::JSObject>, unsigned int, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, unsigned int) [/Users/amandala/.nvm/versions/node/v8.14.0/bin/node]
 8: v8::internal::JSObject::AddDataElement(v8::internal::Handle<v8::internal::JSObject>, unsigned int, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::Object::ShouldThrow) [/Users/amandala/.nvm/versions/node/v8.14.0/bin/node]
 9: v8::internal::Runtime_SetProperty(int, v8::internal::Object**, v8::internal::Isolate*) [/Users/amandala/.nvm/versions/node/v8.14.0/bin/node]
10: 0x2dd687c842fd
✨  Done in 199.09s.

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Maybe you project is very big so try to increase memory usage for node

**Comment by rajasekhar2** [comment]
I am also facing same issue. There are huge number of people who are posting this issue but not even one promising response from webpack team. It will be great if someone can look into this issue seriously that will be great. I have posted this https://github.com/webpack/webpack-dev-server/issues/2348 with al necessary details
