### ISSUE TITLE
How to prevent tree shaking on some files

### ISSUE THREAD

**Issue by ScriptedAlchemy** [webpack/webpack#10025]
I am developing this: https://github.com/ScriptedAlchemy/webpack-external-import

Which allows you to import chunks from another bundle. Im looking for a way to disable tree shaking of the exports when generating a chunk 

Lets say i have two exports

`export default` and `export const UnusedInApp` How can i prevent webpack from eliminating dead code for a specific file. Is it possible to apply sideEffects the way youd apply a loader, or is there a hook that i can take advantage of to skip tree shaking

**Comment by sokra** [comment]
Take a look at DllPlugin. It does the same and also disables tree shaking for some modules (it flags them as "used in unknown way")

**Comment by ScriptedAlchemy** [comment]
Perfect! Thanks @sokra 

I’ve got one more question I was hoping you can help me with.  How could one trace all dependencies a specific file needs? Beyond the direct imports, what about importing like a utils file which imports other dependencies. Any suggestions on tracing all dependencies a module might need

**Comment by i-like-robots** [comment]
We're also keen to disable tree shaking for some of the chunks we generate and are interested to know if it is currently possible without building a custom plugin.

We have multiple applications which don't share a fixed runtime but because we've set them up to deploy assets to the same location they can share code. As our users navigate between these apps we'd rather aid caching than minimise code size and risk downloading things twice. To aid this we have configured our builds to split out some well known libraries and a generic pattern to match packages from our component library.

**Comment by ScriptedAlchemy** [comment]
@i-like-robots this isn’t the way Tobias describes as I’ve still got to refactor some of my work - but this solution does work

I have a draft article about it. Search “tree shaking” and you’ll see the hook in a plugin you’d need https://medium.com/p/1132d8cb6051

**Comment by i-like-robots** [comment]
Interesting piece, thanks @ScriptedAlchemy. We had found our way to `FlagEntryExportAsUsedPlugin` and `.setUsedInUnknownWay()` but we're a little scared of using it... not because it might break something, but because somebody will see it in future and not know what it's about because it's an internal detail which is hard to find information about.

**Comment by ScriptedAlchemy** [comment]
I found that usedExports=true doesn’t work, you have to push an array or strings that are the export names. 

This might be only if you have providedExports:true. Not sure 

But I do think that you might be safer off pushing the array of used exports into the key, like I’m doing 

Does your example work for you?

**Comment by i-like-robots** [comment]
From a short mess around, yes it seems to do the trick. I'll put together some better examples to test it more thoroughly.

The code above is more or less a modified version of the `FlagInitialModulesAsUsedPlugin` for Webpack v4.

**Comment by i-like-robots** [comment]
I've uploaded my tests here: https://github.com/i-like-robots/disable-tree-shaking-for-chunk-plugin 

The test example is quite contrived and not yet tested on a real world codebase but it does appear to work.

**Comment by ScriptedAlchemy** [comment]
Ahh I believe this only prevents the module from being shaken entirely, does it preserve all exports? I was testing on a next js environment and observed that some destructured exports were discarded.

Ill follow along on your progress

**Comment by sokra** [comment]
There is a small difference between setting used exports to `true`/`usedInUnknownWay` and settings used exports to all provided exports.

when used in unknown way, export names are kept original. While when all provided exports are used, the export names might be mangled to shorter names.

when used in unknown way, a `__esModule: true` is added to the namespace object for commonjs interop.

**Comment by ScriptedAlchemy** [comment]
Yeah I saw this as well. The exports become a,b,c and so on. Not the originals, export default becomes exports.a

**Comment by i-like-robots** [comment]
Thank you for the extra detail @sokra, that makes sense. So to effectively disable tree shaking for modules is the following sufficient enough?:

``js
targetChunk.modulesIterable.forEach((m) => {
  m.usedExports = true
})
```

**Comment by sokra** [comment]
I think so. That's webpack 4 code. It changed a little bit in webpack 5 to `exportsInfo.setUsedInUnknownWay()`

**Comment by i-like-robots** [comment]
I've tested the little plugin I pasted together on 4 apps and it does produce the expected outcome. Thanks for your help ⭐️

**Comment by ScriptedAlchemy** [comment]
@sokra slightly off topic, but do you know if or what hook could be used to update a module.id *after* tree shaking. 

I’m doing a contenthash module by module, but after tree shakes the content hash would be different.

**Comment by i-like-robots** [comment]
> I found that usedExports=true doesn’t work, you have to push an array or strings that are the export names.

> This might be only if you have providedExports:true. Not sure

> But I do think that you might be safer off pushing the array of used exports into the key, like I’m doing

You were right @ScriptedAlchemy 😆 

We ended up in a situation where the export names were not being mangled consistently with the name expected by the consuming module.

This is the solution we ended up with (for Webpack v4):

```js
targetChunk.modulesIterable.forEach((m) => {
	if (m.type.startsWith('javascript/')) {
		m.used = true
		m.usedExports = true
		m.buildMeta.providedExports = true
	}
})
```



We ended up in a situation whereby the modules with tree shaking disabled were not having their exports mangled but the consumers of those modules were.

**Comment by ScriptedAlchemy** [comment]
https://github.com/webpack/webpack/issues/10352

This will solve our problems
