### ISSUE TITLE
webpack 4.41.2 Configuration Error

### ISSUE THREAD

**Issue by nuuiteam** [webpack/webpack#10021]
I am facing issue while upgrade the webpack to 4.4

webpack.config.js

var path = require('path');
var webpack = require('webpack');
var HtmlWebpackPlugin = require('html-webpack-plugin');
var ExtractTextPlugin = require('extract-text-webpack-plugin');

module.exports = {
  devtool: 'eval-source-map',
  resolve: {
    extensions: ['', '.js', '.jsx'],
    modules: [
      'node_modules'
  ]
  },
  entry: [
    'webpack-hot-middleware/client?reload=true',
    path.join(__dirname, 'app/index.js')
  ],
  output: {
    path: path.join(__dirname, '/dist/'),
    publicPath: '/',
    filename: '[name].js'
  },
  plugins: [
    new HtmlWebpackPlugin({
      template: 'app/index.tpl.html',
      inject: 'body',
      filename: 'index.html'
    }),
    new ExtractTextPlugin('components/css/[name]-[hash].min.css'),
    new webpack.optimize.OccurrenceOrderPlugin(),
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoEmitOnErrorsPlugin(),
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': JSON.stringify('development')
    })
  ],
  module: {
    rules: [
      {
        test: /\.css$/,
        exclude: /node_modules/,
        options: {
          presets: ['react', 'es2015', 'stage-0']
        },
        enforce: 'pre',
        use: [
          'style-loader',
          'css-loader'
        ]
      },
      
      {
        test: /\.(ico|jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|xlsx)(\?.*)?$/,
        use: {
          loader: 'file-loader',
          
          options: {
            name: 'images/[name].[ext]',
            vendor: [ 'xlsx'],
            
          }
        }
      }
    ],
    loaders: [{
      test: /\.jsx?$/,
      exclude: /node_modules/,
      loader: 'babel-loader'
    }, {
      test: /\.json?$/,
      loader: 'json-loader'
    }, {
      test: /\.css$/,
      loaders: [
        'style-loader',
        'css-loader'
      ]
    },
    {
      test: /\.(ico|jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|xlsx)$/,
      loader: 'file-loader'
    },
    ]
  }
};

webpack.config.production.js
var path = require('path');
var webpack = require('webpack');
var HtmlWebpackPlugin = require('html-webpack-plugin');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var StatsPlugin = require('stats-webpack-plugin');
var NODE_ENV = process.env.NODE_ENV || 'production';
var autoprefixer = require('autoprefixer');

module.exports = {
  entry: [
    path.join(__dirname, 'app/index.js')
  ],
  output: {
    path: path.join(__dirname, '/dist/'),
    publicPath: '/',
    filename: '[name]-[hash].min.js'
  },
  resolve: {
    extensions: ['', '.js', '.jsx']
  },
  plugins: [
    new webpack.optimize.OccurenceOrderPlugin(),
    new HtmlWebpackPlugin({
      template: 'app/index.tpl.html',
      inject: 'body',
      filename: 'index.html'
    }),
    new ExtractTextPlugin('components/css/[name]-[hash].min.css'),
    new webpack.optimize.UglifyJsPlugin({
      compressor: {
        warnings: false,
        screw_ie8: true
      }
    }),
    new StatsPlugin('webpack.stats.json', {
      source: false,
      modules: false
    }),
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': JSON.stringify(NODE_ENV)
    })
  ],
  module: {
    rules: [
      {
        test: /\.css$/,
        enforce: 'pre',
        use: [
          'style-loader',
          'css-loader'
        ]
      },
      {
        test: /\.(ico|jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|xlsx)(\?.*)?$/,
        use: {
          loader: 'file-loader',
          
          options: {
            name: 'images/[name].[ext]',
            vendor: [ 'xlsx'],
            
          }
        }
      }
    ],
    loaders: [{
      test: /\.jsx?$/,
      exclude: /node_modules/,
      loader: 'babel-loader'
    }, {
      test: /\.json?$/,
      loader: 'json-loader'
    }, {
      test: /\.css$/,
      loaders: [
        'style-loader',
        'css-loader'
      ]
    },
    {
      test: /\.(png|jpg|jpeg|svg)$/,
      loader: 'file-loader'
    },
    ]
  },
  postcss: function () {
    return [autoprefixer];
  }/Users/arul/Documents/cashbac workspace/localgit/20112019/cashbac/package/Users/arul/Documents/cashbac workspace/localgit/20112019/cashbac/webpack.config.production.js

[webpack.config.docx](https://github.com/webpack/webpack/files/3879376/webpack.config.docx)
[webpack.config.production.docx](https://github.com/webpack/webpack/files/3879377/webpack.config.production.docx)

.json
};/Users/arul/Documents/cashbac workspace/localgit/20112019/cashbac/webpack.config.js

package lock.json

{
  "name": "react-redux-boilerplate",
  "version": "1.0.0",
  "description": "",
  "main": "webpack.config.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "clean": "rimraf dist",
    "dev": "nodemon --delay 1.5 dev.js",
    "build": "npm run clean && cross-env NODE_ENV=production webpack --config ./webpack.config.production.js --progress --profile --colors",
    "lint": "eslint . --fix"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "babel-core": "^6.7.6",
    "babel-eslint": "^10.0.3",
    "babel-loader": "^8.0.6",
    "babel-plugin-add-module-exports": "^1.0.2",
    "babel-plugin-webpack-loaders": "^0.9.0",
    "babel-polyfill": "^6.7.4",
    "babel-preset-env": "^1.6.1",
    "babel-preset-react": "^6.5.0",
    "babel-preset-react-hmre": "^1.1.1",
    "babel-preset-stage-0": "^6.5.0",
    "babel-register": "^6.7.2",
    "cross-env": "^6.0.3",
    "css-loader": "^3.2.0",
    "eslint": "^6.6.0",
    "eslint-config-airbnb": "^18.0.1",
    "eslint-plugin-import": "^2.18.2",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-react": "^7.16.0",
    "extract-text-webpack-plugin": "^3.0.2",
    "html-webpack-plugin": "^3.2.0",
    "jsdom": "^15.2.1",
    "json-loader": "^0.5.7",
    "nodemon": "^2.0.0",
    "postcss-loader": "^3.0.0",
    "react-addons-test-utils": "^15.0.1",
    "redux-devtools": "^3.2.0",
    "redux-devtools-dock-monitor": "^1.1.1",
    "redux-devtools-log-monitor": "^1.0.11",
    "redux-logger": "^3.0.6",
    "rimraf": "^3.0.0",
    "stats-webpack-plugin": "^0.7.0",
    "style-loader": "^1.0.0",
    "webpack": "^4.41.2",
    "webpack-cli": "^3.3.10",
    "webpack-dev-middleware": "^3.7.2",
    "webpack-hot-middleware": "^2.10.0"
  },
  "dependencies": {
    "axios": "^0.19.0",
    "body-parser": "^1.15.1",
    "bootstrap": "^4.3.1",
    "express": "^4.13.4",
    "file-loader": "^4.3.0",
    "flickity": "^2.2.1",
    "font-awesome": "^4.6.1",
    "google-maps-react": "^2.0.2",
    "jquery": "^3.4.1",
    "moment": "^2.24.0",
    "popper.js": "^1.16.0",
    "postcss": "^7.0.23",
    "prop-types": "^15.6.0",
    "react": "^16.12.0",
    "react-bootstrap": "^1.0.0-beta.16",
    "react-dom": "^16.12.0",
    "react-redux": "^7.1.3",
    "react-router": "^5.1.2",
    "react-router-redux": "^4.0.2",
    "react-slick": "^0.25.2",
    "redux": "^4.0.4",
    "redux-thunk": "^2.0.1",
    "slick-carousel": "^1.8.1",
    "svg-transform-loader": "^2.0.8",
    "swiper": "^5.2.1",
    "url-loader": "^2.3.0"
  }
}
![Screenshot 2019-11-22 at 5 22 36 PM](https://user-images.githubusercontent.com/49484550/69423973-77b1b800-0d4d-11ea-89ea-c724ef001907.png)

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Please read error message you have invalid configuration
