### ISSUE TITLE
GSoC 2019 Project Title - ProgressPlugin Refactor

### ISSUE THREAD

**Issue by advaitranade** [webpack/webpack#10023]
Hello, This project is listed for GSoC 2019. I wanted to ask that is this project still open for contribution. I want to contribute to this project during GSoC 2020.

Project link - https://docs.google.com/document/d/19ZCaBt5UQJ45reIpCKQo_oeICpk9sPW5YjqO7ciAQh4/edit

**Comment by raxraj** [comment]
@advaitranade It would be really appreciated if you put this question somewhere else!!
It seems like creating an issue on Webpack core isn't exactly the greatest Idea!!
Though!
If you want to contribute to this Project listed above it is all about the Proposal you make! If WebPack Joins the GSOC 2020!!

**Comment by sokra** [comment]
If we participate in GSoC 2020 we will work out projects for you. We haven't decided on projects yet.
