### ISSUE TITLE
Version 4.6 ?

### ISSUE THREAD

**Issue by Legends** [webpack/webpack#10039]
[Section ](https://webpack.js.org/guides/code-splitting/#prefetchingpreloading-modules) mentions wp v4.6, but latest stable at the time of writing is [`v4.41.2`](https://github.com/webpack/webpack/releases).
Executing `yarn add webpack --dev` installs `4.41.2`, which should install latest stable version.

Shouldnt there be a tag 4.6 Release?
Or where can I find v4.6?

**Comment by sokra** [comment]
v4.41.2 > 4.6

**Comment by Legends** [comment]
I definitely need some sleep, sorry !
