### ISSUE TITLE
Tree shaking doesn't work as expected

### ISSUE THREAD

**Issue by helabenkhalfallah** [webpack/webpack#10034]
#Bug report
 
Hello, I tried to made a react component library.
I want to export library as ES Module.
I want that each application using this library will not import the whole bundle but only what needed.
I learned that with webpack Tree Shaking is possible.
https://webpack.js.org/guides/tree-shaking/

However when I use my library inside an application, I got the whole bundle loaded not only what I need.

**What is the current behavior?**
Tree Shaking not working in spite of doing like documentation recommandation :( 

**If the current behavior is a bug, please provide the steps to reproduce.**

Library link :
https://github.com/helabenkhalfallah/atomify

![Capture d’écran 2019-11-26 à 00 18 47](https://user-images.githubusercontent.com/1331451/69587535-15271900-0fe6-11ea-94af-e636098212e4.png)

Project link :
https://github.com/helabenkhalfallah/react-sortable-grid-pages/blob/master/src/pages/HomePage.jsx#L9

![Capture d’écran 2019-11-26 à 00 27 03](https://user-images.githubusercontent.com/1331451/69587545-1bb59080-0fe6-11ea-8567-69095b6dbb37.png)

**What is the expected behavior?**
I have a chuncked little import according what I had call and not the whole of bundle (like react router or ant design, modular loading).

Have I missed a settings ? is my configuration correct ?

Thanks.

**Comment by sokra** [comment]
Don't bundle your library. You can transpile your library instead with babel, or similar.

**Comment by helabenkhalfallah** [comment]
> Don't bundle your library. You can transpile your library instead with babel, or similar.

Hello @sokra I don't think this is not the best solution, If I want to share my lib between my team each one must exclude the lib, add required loaders and install required dependencies. These things are already done when using bundle (ready to use library without any config). 
Why we need webpack in this cas  :( :(

**Comment by helabenkhalfallah** [comment]
I tried libraryTarget umd & commonJS but the same : webpack import al the bundle not as es module.

**Comment by helabenkhalfallah** [comment]
Hello, I succeed to do es module for my library, if you are interested how :

Library :
https://github.com/helabenkhalfallah/atomify/blob/master/package.json#L24
https://github.com/helabenkhalfallah/atomify/blob/master/package.json#L25
https://github.com/helabenkhalfallah/atomify/blob/master/package.json#L29
https://github.com/helabenkhalfallah/atomify/blob/master/webpack.config.js#L11

Project importing :
https://github.com/helabenkhalfallah/react-sortable-grid-pages/blob/master/src/pages/HomePage.jsx#L7

And now webpack do tree shaking correctly, it import only what used : 

![Capture d’écran 2019-12-01 à 22 43 56](https://user-images.githubusercontent.com/1331451/69920871-50fe2a80-148d-11ea-852d-682f2a637688.png)

I do not import Button from library and it is not bundled :) 

Thanks for all your help :) :)
