### ISSUE TITLE
Uncaught ReferenceError: global is not defined

### ISSUE THREAD

**Issue by Praveer1981** [webpack/webpack#10035]
# Bug report

I have an `Electron` based application. we do `webpack ` in the render process. It throws error when I run the app
`Uncaught ReferenceError: global is not defined`

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
It should not throw this error when I run the application

**Other relevant information:**
here is the Error:
```
index.js?e792:25 Uncaught ReferenceError: global is not defined
    at eval (index.js?e792:25)
    at Object../node_modules/@babel/polyfill/lib/index.js (feb33beb921cb1f5a1b3.worker.js:97)
    at __webpack_require__ (feb33beb921cb1f5a1b3.worker.js:20)
    at eval (eval at ./node_modules/babel-loader/lib/index.js?{"babelrc":false,"presets":["@babel/preset-env", "@babel/preset-react"]}!./node_modules/ts-loader/index.js?{"transpileOnly":true,"configFile":"tsconfig.webpack.json"}!./node_modules/ts-loader/index.js?!./packages/myApp/modules/frameworks/file-provider/box-provider/webworker/box.worker.ts (feb33beb921cb1f5a1b3.worker.js:526), <anonymous>:2:73)
    at Module../node_modules/babel-loader/lib/index.js?{"babelrc":false,"presets":["@babel/preset-env", "@babel/preset-react"]}!./node_modules/ts-loader/index.js?{"transpileOnly":true,"configFile":"tsconfig.webpack.json"}!./node_modules/ts-loader/index.js?!./packages/myApp/modules/frameworks/file-provider/box-provider/webworker/box.worker.ts (feb33beb921cb1f5a1b3.worker.js:526)
    at __webpack_require__ (feb33beb921cb1f5a1b3.worker.js:20)
    at feb33beb921cb1f5a1b3.worker.js:84
    at feb33beb921cb1f5a1b3.worker.js:87
```

Note: Since it is an electron app: 
config.target = "electron-renderer";
{global:true};

webpack version:  ^4.41.2
Node.js version: 10.16.3
Operating System: windows 10
"@babel/core": "^7.6.4"
Additional tools: chrome 78
Electron version : 7.1.1

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by Praveer1981** [comment]
Its little bit hard to reproduce it in the separate application. I want to know under which scenario it is possible.
once I get the error in the console and write `global` It shows me the property of the global object which means the global object is available.
then what could be the reason of getting this error ?

**Comment by evilebottnawi** [comment]
@Praveer1981 Looks like you run `babel-loader` in worker, why you do it?

**Comment by Praveer1981** [comment]
we have `babel-loader` in the webpack config file

**Comment by Praveer1981** [comment]
`module.exports = {
....
module: {
	rules: [
		      {
        test: /\.ts(x?)$/,
        include: [packagesDir],
        use: [
          {
            loader: require.resolve("babel-loader"),
            options: {
              babelrc: false,
              presets: [
                [
                  "@babel/preset-env",
                  {
                    modules: false,
                    "useBuiltIns" : "entry"
                  }
                ],
                "@babel/preset-react"
              ],
              plugins: [require.resolve("babel-plugin-syntax-dynamic-import")]
            }
          },
          {
            loader: require.resolve("ts-loader"),
            options: {
              configFile: "tsconfig.webpack.json"
            }
          }
        ]
      }
	
	]
}
.....

}`

**Comment by Praveer1981** [comment]
Additional Information:
if (global._babelPolyfill && typeof console !== "undefined" && console.warn) {
  console.warn("@babel/polyfill is loaded more than once on this page. This is probably not desirable/intended " + "and may have consequences if different versions of the polyfills are applied sequentially. " + "If you do need to load the polyfill more than once, use @babel/polyfill/noConflict " + "instead to bypass the warning.");
}

**Comment by ohanar** [comment]
Here is an minimal example repository that runs into this issue: https://github.com/ohanar/webpack-issue-10035/

**Comment by amanharwara** [comment]
I was having the same issue, and I found a hacky fix.
If you can, change any reference of `global` which is causing the issue to `window.globalThis`. At least this worked for me.

**Comment by EdwinIwan** [comment]
We found easy solution for this bug. We had to only add this code to index.html before your bundle.

``` 
<body id="app">
    <script>
      global = globalThis //<- this should be enough
    </script>
    <script src="./electron-renderer.js"></script>
  </body>
```

**Comment by evilebottnawi** [comment]
Fixed in `worker-loader`, also webpack@5 supports workers out of box

**Comment by jbowa** [comment]
For me this worked: 

```javascript
app.on('ready', () => {
    mainWindow = new BrowserWindow({
        webPreferences: {
            nodeIntegration: true,
            contextIsolation: false,
        }
    });
});
```

**Comment by FrancescoBorzi** [comment]
> I'm having the same problem and the solution proposed by @EdwinIwan didn't work for me.
> 
> What **did "work"** was setting `contextIsolation: false` as suggested by @jbowa. Still, this isn't a real solution since I'm leaving my app more exposed given that the renderer process and Electron's internal processes are no longer isolated from one another. There should be something better, or an explanation as to why it "works" in order to find a better alternative.

Same here. In my case, the solution suggested by @EdwinIwan just changes the error to:

> polyfills.js:1 Uncaught ReferenceError: require is not defined

**Comment by eden-lane** [comment]
I'm also getting `require is not defined` error with this workaround. Is there any other way to solve this?

**Comment by emersonthis** [comment]
Same for me. `global = globalThis` causes `require is not defined`.  Does anyone understand this problem? The docs emphasize the importance of _not_ setting `contextIsolation` to false so this feels like a big deal.

**Comment by ExampleWasTaken** [comment]
Having the exact same issue. Would be great if anybody from the maintainers could take a look at this.

**Comment by vankop** [comment]
please create a new issue with reproducible repo.

**Comment by mx51damon** [comment]
> For me this worked:
> 
> ```js
> app.on('ready', () => {
>     mainWindow = new BrowserWindow({
>         webPreferences: {
>             nodeIntegration: true,
>             contextIsolation: false,
>         }
>     });
> });
> ```

Please read [the documentation](https://www.electronjs.org/docs/latest/breaking-changes#default-changed-contextisolation-defaults-to-true) before thumb down !! (This is a suggested solution from Electron documentation)

**Comment by geroale** [comment]
Same issue here

**Comment by ExampleWasTaken** [comment]
@vankop I've created a project with the exact same structure as the one that I initially encountered the issue with: https://github.com/ExampleWasTaken/webpack-issue-10035-demo

The `master` branch faces the issue that is described in the title.
The `attempted-fix` branch has a fix that I found on [StackOverflow](https://stackoverflow.com/a/67336441/13493994) and that has also been attempted by some in this conversation.

I hope this helps.

**Comment by vankop** [comment]
using `globalObject="globalThis"` should help.

**Comment by vankop** [comment]
> external node-commonjs "events"

it looks like you have some Node.js module in web..

**Comment by ExampleWasTaken** [comment]
> > external node-commonjs "events"
> 
> it looks like you have some Node.js module in web..

I'm using `target: electron-renderer` along with `nodeIntegration: true`

**Comment by patrickfatrick** [comment]
Another workaround is to simply not use `target: electron-renderer` for now, if you don't need it. `web` works.

**Comment by ExampleWasTaken** [comment]
> Another workaround is to simply not use `target: electron-renderer` for now, if you don't need it. `web` works.

that is exactly what I do. Yet I get the error

**Comment by ExampleWasTaken** [comment]
> Another workaround is to simply not use `target: electron-renderer` for now, if you don't need it. `web` works.

I have tried that, but I get the same error: 
```
Uncaught ReferenceError: global is not defined
    at jsonp chunk loading:41:1
    at jsonp chunk loading:509:1
    at startup:6:1
```

**Comment by vankop** [comment]
your global object should not be `global`, see https://github.com/webpack/webpack/issues/10035#issuecomment-1075074282

**Comment by ExampleWasTaken** [comment]
> your global object should not be `global`, see [#10035 (comment)](https://github.com/webpack/webpack/issues/10035#issuecomment-1075074282)

Yep that makes sense. My question is why it is global in the first place. My target is set to `electron-renderer`. And even if I change it, I get the `require is not defined`thing. Maybe I'm just lost here but I've been sitting on this for a good few weeks now.

**Comment by vankop** [comment]
it looks like `electron-renderer` should have `global` https://github.com/webpack/webpack/blob/main/lib/config/target.js#L211

**Comment by YasharSL** [comment]
I'm having the same issue while trying to open a new window in my app. None of the solutions worked.

**Comment by brunottonurb** [comment]
@marcibk I set `target: 'web'` in the webpack config for the react app. I do not set `nodeIntegration` (defaults to false AFAIK).

**Comment by CarlSaqui29** [comment]
on your createWindow(), add the 

webPreferences: {
  nodeIntegration: true,
  contextIsolation: false
}

this will work absolutely...

**Comment by Cedgud** [comment]
Hello,

does anone make this work? I've tried the global = globalThis fix. Now I have "require is not defined"

**Comment by thamizh-qwerty** [comment]
> We found easy solution for this bug. We had to only add this code to index.html before your bundle.
> 
> ```
> <body id="app">
>     <script>
>       global = globalThis //<- this should be enough
>     </script>
>     <script src="./electron-renderer.js"></script>
>   </body>
> ```

It does not works in angular + electronJS + contextIsolation = true

**Comment by resatDev** [comment]
I have already resolved this problem by changing the `node` options. According to official [doc of webpack](https://webpack.js.org/configuration/node/#node), **`global prop of node`** is **false** default. **Using suggested plugin** or making` global is true` will probably resolve your problem as well.

**Comment by travbid** [comment]
For my project I had to set `splitChunks: false` in the webpack config to fix this error:
```js
module.exports = {
  configureWebpack:{
    // ...
    target: "electron-renderer",
    optimization: {
      splitChunks: false,
    }
  }
}

```

**Comment by PhoenixTilea** [comment]
I'll join in here. Tried both combinations of `nodeIntegration` and `contextIsolation` and those solutions failed. Tried defining global in my index.html file, which failed. I have tried setups and configurations from at least 5 different "How to setup an electron project with react, webpack, and typescript" articles. I also tried setting node.global to true in all of my various webpack entry configs.

The only thing that works is setting `target: "web"` in the react webpack config, and this only works when building in development mode running two separate terminal processes for webpack-dev-server and the actual electron app.

Something is buggy with the electron-renderer target. Electron apps need global, and electron-renderer isn't providing it. The reference error being thrown isn't even in my own code, so I have no control over whether it's being called or not.

**Comment by codelegant** [comment]
When create brwoser window, use `nodeIntegrationInWorker: true` in `webPreferences`
https://www.electronjs.org/docs/latest/tutorial/multithreading
```
 new BrowserWindow({
      webPreferences: {
        nodeIntegrationInWorker: true,
        contextIsolation: false,
      },
    })
```

**Comment by witcsmartian** [comment]
> I'm also getting `require is not defined` error with this workaround. Is there any other way to solve this?

want help~

**Comment by mohan-reviewer1** [comment]
> > Another workaround is to simply not use `target: electron-renderer` for now, if you don't need it. `web` works.
> 
> I have tried that, but I get the same error:
> 
> ```
> Uncaught ReferenceError: global is not defined
>     at jsonp chunk loading:41:1
>     at jsonp chunk loading:509:1
>     at startup:6:1
> ```



> ExampleWasTaken
is there any workaround for this?

**Comment by kythanh** [comment]
Still got the same error here. 

```
Uncaught ReferenceError: global is not defined
    at jsonp chunk loading:84:1
    at jsonp chunk loading:86:1
    at index.tsx:10:67
```

<img width="522" alt="Image" src="https://github.com/user-attachments/assets/393cbb61-04f3-4214-af6d-1b52ff147831" />

**Comment by alexander-akait** [comment]
@kythanh Check your `target`? What is the value?

**Comment by hushuxian** [comment]
I have the same problem with my electron app,only set nodeIntegration:true and contextIsolation:false can fix it .

**Comment by alexander-akait** [comment]
@hushuxian Can you create reproducible test repo, thank you
