### ISSUE TITLE
Hot reloading webpack-dev-server by changing mock-data

### ISSUE THREAD

**Issue by Yegorich555** [webpack/webpack#10036]
## Feature request

**What is the expected behavior?**
Using wepback-dev-server as mock-api-server with hot-reloading. 

**What is motivation or use case for adding/changing the behavior?**
During the developing I have to provide a mock-data (when I have no real apiServer). So we can use 
```js 
{
  devServer: {
    after(app) {
      app.get("some url", function (req, res) {
        res.json('some object here')
      });
     ...
      app.post("some url", function (req, res) {
        res.json('some object here')
      });
    }
  }
};
```

And as mock-functions are set through wepback.config.js hot-replacement doesn't work. Right now I implemented proxy config for webpack and mockServer with nodemon. But it doesn't look perfect and nodemon doesn't resolve hmr (by watching imports). I would like to see hot-replacement directly into devServer that should reload dev-server by changing mock-files (that are imported in webpack.config.js and are used instead of ```app.get....```). Using the json files instead of functions doesn't work for me because I need to response based on request.

**How should this be implemented in your opinion?**
I guess we should run two webpack instances. The first one watch for mock data changes and reloads the dev-server, the second one works as is.

**Are you willing to work on this yourself?**
no, because I'm not good at in webpack architecture

**Comment by Yegorich555** [comment]
For everyone who looks for solution, I've developed [webpack-mock-server](https://www.npmjs.com/package/webpack-mock-server)

**Comment by evilebottnawi** [comment]
I think it is very rare case and your solution is good, maybe we revisit it in the future, anyway feel free to leave feedback

**Comment by flyyang** [comment]
It would be nice if officially support this feature.
