### ISSUE TITLE
Docs: "How to write a plugin"

### ISSUE THREAD

**Issue by IngwiePhoenix** [webpack/webpack#1003]
I just noticed, that the "How to write a plugin" page was not linked yet, having me guess it wasn't done just yet. So I thought I'd give in a few questions that I, as a user/developer, would have when asking about how this is done:

- Which phases of the compiler can we tap into?
- What can we manipulate and how?
- Can we inject loaders? This would be helpful, so that we only need to have the user add a plugin, and it will register a loader if a specific file is found.
- How to manipulate the source (adding scripts, injecting scripts into other chunks, actually adding stuff to the head or bottom) and at which compile steps?
- Which phases are recomended to tap into?
- What values are available in `this` and does it change during the compilation steps?

I am very much interested in source manipulation at the moment, so it would be nice to hear about how this works. :)

Kind regards, Ingwie

**Comment by mtscout6** [comment]
:+1:

**Comment by sokra** [comment]
There is a some information here: http://webpack.github.io/docs/plugins.html but propably a bit out-of date

**Comment by lemmy-** [comment]
:+1:

**Comment by IngwiePhoenix** [comment]
Bump o.o

**Comment by pksjce** [comment]
This issue was moved to webpack/webpack.io#99

**Comment by pksjce** [comment]
This issue was moved to webpack/webpack.io#128
