### ISSUE TITLE
Webpack 4 Upgrade,the bundleApp.js has been loaded but it didn't run

### ISSUE THREAD

**Issue by Aarthy217** [webpack/webpack#10045]
Webpack.config.js
var path = require('path');
var webpack = require('webpack');

// Webpack Plugins
var HTMLWebpackPlugin = require("html-webpack-plugin");
var autoprefixer = require('autoprefixer');
var MiniCssExtractPlugin = require('mini-css-extract-plugin');

var ENV = process.env.npm_lifecycle_event;
var isTestWatch = ENV === 'test-watch';
var isTest = ENV === 'test' || isTestWatch;
var isProd = ENV === 'build';

module.exports = function makeWebpackConfig() {
  
    var config = {};
    config.mode = 'development';
    config.entry = {
        'bundlePolyfill': './app/polyfills.ts',
        'bundleVendor': './app/vendor.ts',
        'bundleApp': './app/main.ts' // our angular app
    };
    config.output = {
        path: root('dist'),
        publicPath: '/dist/',
        filename: 'js/[name].[hash:10].js',
        chunkFilename: 'js/[name]-chunk.[hash:10].js'
    };
    config.resolve = {
        // only discover files that have those extensions
        extensions: ['.ts', '.js', '.json', '.css', '.html']
    };

    var atlOptions = '';
    if (isTest && !isTestWatch) {
        // awesome-typescript-loader needs to output inlineSourceMap for code coverage to work with source maps.
        atlOptions = 'inlineSourceMap=true&sourceMap=false';
    }
    config.module = {
        rules: [
         // Support for .ts files.
         {
              test: /\.ts$/,
              loaders: ['awesome-typescript-loader?' + atlOptions, 'angular2-template-loader', '@angularclass/hmr-loader', 'angular-router-loader'],
              exclude: [isTest ? /\.(e2e)\.ts$/ : /\.(spec|e2e)\.ts$/, /node_modules\/(?!(ng2-.+))/]
          },
         {
            test: /\.css$/,
            include: root('app'),
            loaders: ['css-to-string-loader', 'css-loader']
        },
          // all css required in src/app files will be merged in js files
         { test: /\.css$/, include: root('app'), loader: 'raw-loader!postcss-loader' },

                // support for .html as raw text
          // todo: change the loader to something that adds a hash to images
          { test: /\.html$/, loader: 'raw-loader', exclude: root('Public') }
        ]
    };
     
                
   if (isTest && !isTestWatch) {
        // instrument only testing sources with Istanbul, covers ts files
        config.module.rules.push({
            test: /\.ts$/,
            enforce: 'post',
            include: path.resolve('app'),
            loader: 'istanbul-instrumenter-loader',
            exclude: [/\.spec\.ts$/, /\.e2e\.ts$/, /node_modules/]
        });
    }
    config.plugins = [
      // Define env variables to help with builds
      // Reference: https://webpack.github.io/docs/list-of-plugins.html#defineplugin
      new webpack.DefinePlugin({
          // Environment helpers
          'process.env': {
              ENV: JSON.stringify(ENV)
          }
      }),

      // Workaround needed for angular 2 angular/angular#11580
      new webpack.ContextReplacementPlugin(
        // The (\\|\/) piece accounts for path separators in *nix and Windows
        /angular(\\|\/)core(\\|\/)@angular/,
        root('./app') // location of your src
      ),

      // Tslint configuration for webpack 2
      new webpack.LoaderOptionsPlugin({
          options: {
           
              tslint: {
                  emitErrors: false,
                  failOnHint: false
              },

             
              postcss: [
                autoprefixer({
                    browsers: ['last 2 version']
                })
              ]
          }
      })
    ];
    if (!isTest && !isTestWatch) {
      config.optimization= {
          runtimeChunk: false,
          minimize: true,
            splitChunks: {
            cacheGroups: {
                    commons: {
                    name: 'commons',
                        chunks: 'initial',
                       
                    },
                    
                // disables the default definition of these cache groups
                 
            }
        }
        
    }; 
     
                 
        config.plugins.push(
       new HTMLWebpackPlugin({
              template: './Views/Home/index.cshtml'//,
              //chunksSortMode: 'dependency'
          }),

         
         new MiniCssExtractPlugin({
           // Options similar to the same options in webpackOptions.output
           // both options are optional
           filename: 'css/[name].[hash].css',
           chunkFilename: 'css/[name]-chunk.[hash].css'
         }),

        );
    }
    
     config.devServer = {
        contentBase: './src/public',
        historyApiFallback: true,
        quiet: true,
        stats: 'minimal' // none (or false), errors-only, minimal, normal (or true) and verbose        
     };

    return config;
}();

// Helper functions
function root(args) {
    args = Array.prototype.slice.call(arguments, 0);
    return path.join.apply(path, [__dirname].concat(args));
}

package.json

{
  "name": "angular-quickstart",
  "version": "1.0.0",
  "description": "QuickStart package.json from the documentation, supplemented with testing support",
  "scripts": {
    "build:watch": "tsc -p src/ -w",
    "build:e2e": "tsc -p e2e/",
    "serve": "lite-server -c=bs-config.json",
    "serve:e2e": "lite-server -c=bs-config.e2e.json",
    "prestart": "npm run build",
    "build": "webpack --config webpack.config.js --display-error-details",
    "start": "webpack-dev-server --inline --progress --port 8080",
    "pree2e": "npm run build:e2e",
    "e2e": "concurrently \"npm run serve:e2e\" \"npm run protractor\" --kill-others --success first",
    "preprotractor": "webdriver-manager update",
    "protractor": "protractor protractor.config.js",
    "pretest": "npm run build",
    "test": "concurrently \"npm run build:watch\" \"karma start karma.conf.js\"",
    "pretest:once": "npm run build",
    "test:once": "karma start karma.conf.js --single-run",
    "lint": "tslint ./src/**/*.ts -t verbose",
    "webdriver-update": "webdriver-manager update",
    "webdriver-start": "webdriver-manager start",
    "clean": "rimraf node_modules doc dist && npm cache clean",
    "clean-install": "npm run clean && npm install",
    "clean-start": "npm run clean-install && npm start",
    "fix-memory-limit": "cross-env LIMIT=2048 increase-memory-limit"
  },
  "keywords": [],
  "author": "",
  "license": "MIT",
  "dependencies": {
    "@angular/common": "~4.2.6",
    "@angular/compiler": "~4.2.6",
    "@angular/compiler-cli": "~4.2.6",
    "@angular/core": "~4.2.6",
    "@angular/forms": "~4.2.6",
    "@angular/http": "~4.2.6",
    "@angular/platform-browser": "~4.2.6",
    "@angular/platform-browser-dynamic": "~4.2.6",
    "@angular/router": "~4.2.6",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0",
    "@types/d3": "^4.10.1",
    "@types/html2canvas": "0.0.35",
    "@types/jspdf": "^1.2.2",
    "ag-grid": "^18.1.2",
    "ag-grid-angular": "^18.1.0",
    "ag-grid-enterprise": "^18.1.1",
    "angular-2-dropdown-multiselect": "1.6.2",
    "angular2-draggable": "1.4.2",
    "angular2-ie9-shims": "0.0.2",
    "britecharts": "^2.0.1",
    "core-js": "^2.4.1",
    "d3": "^4.11.0",
    "dom-to-image": "^2.6.0",
   "express": "^4.16.4",
    "file-saver": "^1.3.3",
    "html2canvas": "^1.0.0-alpha.12",
    "https": "^1.0.0",
    "jquery": "^3.3.1",
    "jsdom": "^13.1.0",
    "jspdf": "1.4.1",
    "mydatepicker": "2.6.1",
    "ng-multiselect-dropdown": "0.2.3",
    "ng2-dragula": "1.3.1",
    "pptxgenjs": "2.5.0",
    "rxjs": "^5.4.2",
    "save-svg-as-png": "1.4.5",
    "systemjs": "0.19.40",
    "tslib": "^1.7.1",
    "xlsx": "^0.11.18",
    "xlsx-style": "^0.8.13",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "1.2.1",
    "@angular/compiler-cli": "2.4.x",
    "@angularclass/hmr": "^1.0.1",
    "@angularclass/hmr-loader": "^3.0.2",
    "@ng-idle/core": "^2.0.0-beta.15",
    "@types/d3-dsv": "1.0.31",
    "@types/jasmine": "2.5.41",
    "@types/node": "^6.0.46",
    "@types/selenium-webdriver": "2.53.39",
    "angular-router-loader": "0.6.0",
    "angular2-load-children-loader": "^0.2.1",
    "angular2-template-loader": "0.6.2",
    "autoprefixer": "^6.3.2",
    "awesome-typescript-loader": "3.2.1",
    "canonical-path": "0.0.2",
    "codelyzer": "2.0.0",
    "compression-webpack-plugin": "^1.0.1",
    "concurrently": "^3.2.0",
    "copy-webpack-plugin": "^4.0.0",
    "cross-env": "^5.0.5",
    "css-loader": "^0.28.4",
    "es6-shim": "^0.35.3",
    "file-loader": "^0.10.0",
    "html-loader": "^0.4.0",
    "html-webpack-plugin": "^4.0.0-alpha",
    "increase-memory-limit": "^1.0.3",
    "istanbul-instrumenter-loader": "^0.2.0",
    "jasmine-core": "^2.4.1",
    "jasmine-spec-reporter": "^3.2.0",
    "json-loader": "^0.5.3",
    "karma": "^1.7.1",
    "karma-chrome-launcher": "^2.2.0",
    "karma-cli": "^1.0.1",
    "karma-coverage": "^1.1.2",
    "karma-env-preprocessor": "^0.1.1",
    "karma-ie-launcher": "^1.0.0",
    "karma-jasmine": "^1.1.1",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-junit-reporter": "^1.2.0",
    "karma-remap-istanbul": "0.2.1",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-webpack": "2.0.2",
    "lite-server": "^2.2.2",
    "lodash": "^4.16.4",
    "mini-css-extract-plugin": "0.8.0",
    "node-sass": "^4.5.0",
    "null-loader": "0.1.1",
    "optimize-css-assets-webpack-plugin": "5.0.3",
    "postcss-loader": "^1.1.0",
    "protractor": "~4.0.14",
    "raw-loader": "0.5.1",
    "remap-istanbul": "^0.6.4",
    "rimraf": "^2.5.4",
    "sass-loader": "^6.0.1",
    "shelljs": "^0.7.0",
    "style-loader": "^0.13.0",
    "terser-webpack-plugin": "2.2.1",
    "to-string-loader": "1.1.5",
    "ts-helpers": "^1.1.1",
    "tslint": "^4.5.1",
    "tslint-loader": "^3.3.0",
    "typescript": "~2.1.0",
    "url-loader": "^0.5.6",
    "watchify": "^3.11.0",
    "webpack": "^4.41.2",
    "webpack-bundle-analyzer": "3.6.0",
    "webpack-cli": "^3.3.10",
    "webpack-dev-server": "3.9.0",
    "webpack-merge": "4.2.2"
  },
  "repository": {}
}

Index.cshtml
@{ 
    string path = Server.MapPath("~/dist/js/");
    string hashKey = string.Empty;
    string file = string.Empty;

    foreach (var fileNames in Directory.GetFiles(path, "bundlePolyfill.*"))
    {
        file = fileNames;
    }
    string fileName = Path.GetFileName(file);
    if (fileName.IndexOf("bundle") != -1 && !string.IsNullOrEmpty(fileName))
    {
        hashKey = fileName.Split('.')[1];
        string bundlePolyfill = "../dist/js/bundlePolyfill." + hashKey + ".js";
        string bundleVendor = "../dist/js/bundleVendor." + hashKey + ".js";
        string bundleApp = "../dist/js/bundleApp." + hashKey + ".js";
        <script src=@bundlePolyfill></script>
        <script src=@bundleVendor></script>
        <script src=@bundleApp></script>
    }
}

WebPack: 4.41
Node: 10.15.3
OS: 10

Is there any issue in my code?

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
