### ISSUE TITLE
Webpack 4 upgrade, bundleapp.js is loaded but it didnt run

### ISSUE THREAD

**Issue by Aarthy217** [webpack/webpack#10046]
[Webpack_config_js.txt](https://github.com/webpack/webpack/files/3901483/Webpack_config_js.txt)
[Package_Json.txt](https://github.com/webpack/webpack/files/3901484/Package_Json.txt)
[index_html.txt](https://github.com/webpack/webpack/files/3901504/index_html.txt)

**Comment by Aarthy217** [comment]
Wepack V4.41
Node V10.15
OS win10

**Comment by evilebottnawi** [comment]
Please use issue template

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/webpack/webpack/issues/10047
