### ISSUE TITLE
Webpack4 upgrade issue, main js is loaded but it is not running

### ISSUE THREAD

**Issue by Aarthy217** [webpack/webpack#10047]
Migrate to webpack4

Current behaviour:
main js is loaded but it is not running

Expected:
It should run and should load the page in the browser, with the webpack 3 it was loading fine

Node V10.15.3
Webpack V4.41.2

**Comment by sokra** [comment]
You didn't include the `commons` script generated by your splitChunks configuration

**Comment by Aarthy217** [comment]
> You didn't include the `commons` script generated by your splitChunks configuration

Where do I need to include it?

**Comment by sokra** [comment]
As script tag in your HTML

**Comment by Aarthy217** [comment]
Using webpack 3, the number and size of the chunks were minimal, after the webpack 4 upgrade the number of chunks generated was increased by 4 times and also the size.
Any specific config needs to be added to reduce the size and number of chunks.

**Comment by Aarthy217** [comment]
webpack3:

 new CommonsChunkPlugin({
              name: ['bundleApp', 'bundleVendor', 'bundlePolyfill'],
              minChunks: (module) => module.context && /node_modules/.test(module.context)
          }),
     new webpack.optimize.UglifyJsPlugin({
              minimize: true,
              warnings: true,
              sourceMap: true,
              mangle: true,
              compress: {
                  unused: true,
                  dead_code: true,
                  drop_debugger: true,
                  conditionals: true,
                  evaluate: true,
                  drop_console: true,
                  sequences: true,
                  booleans: true,
                  screw_ie8: true,
                  warnings: false
              },
              comments: false
          })
pls help me convert this to webpack4

**Comment by sokra** [comment]
Seems to be a separat issue. Please open a new one
