### ISSUE TITLE
XHR request not supported by stream-http getReader() of undefined

### ISSUE THREAD

**Issue by marinav** [webpack/webpack#10043]
# Bug report

**What is the current behavior?**

I need to send xhr requests to set up Cypress tests in my project, unfortunatly, even if the request succeed, i can't access data because of  dependencies used by webpack: (node-libs-browser and stream-http). It triggers this error :

> Cannot read property 'getReader' of undefined

because response.js file in stream-http package need a response.body and is empty.

I saw an [open PR](https://github.com/jhiesey/stream-http/pull/110 ) on stream-http package but I don't know if it will be merged one day. So I tried to desactivate node in webpack settings (https://webpack.js.org/configuration/node/) but I have another error : 

> 'crypto' is undefined

**If the current behavior is a bug, please provide the steps to reproduce.**

To simulate an xhr request I delete win.fetch in my Cypress file, but you can do it in the project directly. And I have whatwg-fetch polyfill installed.

**What is the expected behavior?**

I would like to send xhr request and get the answer.

**Other relevant information:**
webpack version:  4.41.2
Node.js version: 10.15.3
Operating System: Mac osx

**Comment by evilebottnawi** [comment]
@marinav sorry for delay, problem still exists?

**Comment by marinav** [comment]
@evilebottnawi I stop trying to use Cypress I had too much problems so it's not a problem no more.

**Comment by evilebottnawi** [comment]
@marinav thanks for feedback, I will close this problem if you have problems in the future feel free to open a problem, next time we will try to answer you as soon as possible, I apologize again for not being able to respond on time, thanks

**Comment by truelson** [comment]
I am seeing this on a 401 in an android webview and it's blocking use of the https://github.com/Yaffle/EventSource polyfill for us. Would greatly appreciate accepting the fix.

**Comment by truelson** [comment]
https://github.com/jhiesey/stream-http/pull/110
