### ISSUE TITLE
webpack Dev Server Invalid Options

### ISSUE THREAD

**Issue by fengxinming** [webpack/webpack#10056]
incorrect:
```js
devServer: {
  clientLogLevel: 'debug'
}
```
webpack Dev Server Invalid Options

options.clientLogLevel should be {String} and equal to one of the allowed values

 [ 'trace', 'debug', 'info', 'warn', 'error', 'silent' ]

(https://webpack.js.org/configuration/dev-server/#devserver-clientloglevel)

correct:
```js
devServer: {
  clientLogLevel: 'info'
}
```

**Comment by evilebottnawi** [comment]
Please open issue in https://github.com/webpack/webpack.js.org
