### ISSUE TITLE
[object Module] instead of image links after Webpack processing

### ISSUE THREAD

**Issue by nil4** [webpack/webpack#10053]
# Bug report

**What is the current behavior?**

`[object Module]` output instead of image links after processing through Webpack, e.g. 

 - `<link rel="shortcut icon" href="[object Module]" />` 
 - `<img src="[object Module]" alt=""/>`.

**If the current behavior is a bug, please provide the steps to reproduce.**

 1. Extract the attached [repro-webpack.zip](https://github.com/webpack/webpack/files/3902571/repro-webpack.zip).
 2. Run `npm install`
 3. Run `npm bundle` (this is a script for `webpack --mode development`)
 4. Examine the file `dist/index@hash.html` 

**What is the expected behavior?**

The `dist/index@hash.html` file should contain links to image URLs. 
Instead, wherever an image URL is expected, `[object Module]` is output instead.

Here is a diff between the actual and expected output:

```diff
<!doctype html>
<html>
<head>
    <meta charset="utf-8" />
-    <link rel="shortcut icon" href="[object Module]" />
+    <link rel="shortcut icon" href="/favicon@hash.ico" />
</head>
<body>
-    <img src="[object Module]" alt=""/>
+    <img src="/favicon@hash.ico" alt=""/>
<script type="text/javascript" src="/app@13359e76.js"></script></body>
</html>

```

**Other relevant information:**
webpack version:  4.41.2
Node.js version: 13.2.0
Operating System: Windows 10 1909 (x64)
Additional tools: NPM 6.13.1

I'm not sure whether this is a Webpack bug, or perhaps one of the plugins used. Happy to report it elsewhere if appropriate.

**Comment by evilebottnawi** [comment]
Already fixed, please update `style-loader` to latest version

**Comment by evilebottnawi** [comment]
My mistake, problem in `html-loader` or `HtmlWebpackPlugin`

**Comment by nil4** [comment]
@evilebottnawi thanks for reopening! I'm not sure what you meant &mdash; could you please expand a bit on where I should add `esModule: false`? Thank you in advance!

**Comment by evilebottnawi** [comment]
@nil4 https://github.com/webpack-contrib/file-loader#esmodule

**Comment by nil4** [comment]
Right, thank you. I confirm that setting `esModule: false` option for `file-loader` fixes this. 
Much appreciated!

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/webpack-contrib/html-loader/issues/203

**Comment by tsots** [comment]
evilebottnawi response worked perfectly for me
Many, many thanks.

@nil4 https://github.com/webpack-contrib/file-loader#esmodule

**Comment by Beefaz** [comment]
phpstorm, node, react
i saw some vulnerable packages so i did: 
'npm audit fix -f'
i saw some green inline message "thank you for installing jake"
had same problems as in topic until i uninstalled it: 'npm uninstall jake'
back to 1 high vulnerability though :(

**Comment by DragonFly378** [comment]
> Already fixed, please update `style-loader` to latest version

how to update style-loader

**Comment by NAkhilC** [comment]
We need to use default followed by require tag in react js.
src={ require('../images/'+image_name+'.png').default }

**Comment by Rafayalikhan** [comment]
> We need to use default followed by require tag in react js. src={ require('../images/'+image_name+'.png').default }
THANK YOU SOO MUCH I HIGHLY RESPECT
