### ISSUE TITLE
TypeError: Class constructor HookCodeFactory cannot be invoked without 'new'

### ISSUE THREAD

**Issue by akashishu777** [webpack/webpack#10051]
E:\BuildAgent\work\83d9728970ba3129\node_modules\tapable\lib\SyncWaterfallHook.js:24});
TypeError: Class constructor HookCodeFactory cannot be invoked without 'new'
at new SyncWaterfallHookCodeFactory

I am usign webapck version : "webpack": "~4.25.1"

[webpack.config.txt](https://github.com/webpack/webpack/files/3902537/webpack.config.txt)

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Without full information we can't help, sorry

**Comment by akashishu777** [comment]
@sokra can you please look into this?
