### ISSUE TITLE
Critical dependency: the request of a dependency is an expression 

### ISSUE THREAD

**Issue by lronelove** [webpack/webpack#10055]
when use my own package 'sg-calc',
`
const sg_calc = require('sg-calc')
`
then there will be an error like this. I don not know what wrong with my package 'sg-calc'.
(I use parcel to resolve my packge, does it influence)

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
