### ISSUE TITLE
IE 11 splitChunks + cacheGroups causes nothing to happen?

### ISSUE THREAD

**Issue by verbeeksteven** [webpack/webpack#10057]
Hello,

I have a setup which looks like

    splitChunks: {
        cacheGroups: {
            default: false,
            common: false,
            styles: {
                name: settings.vars.cssName,
                test: /\.(scss|css|vue)$/,
                chunks: 'all',
                enforce: true
            }
        }
    },

And this splits out an app.js and a styles.css file. My problem is the app.js is setup with dynamic code loading using the `webpackChunkName` which I can see in the file (I see each file that should be loaded in the Promise area).

My problem seems to be there is a function in the file called `checkDeferredModules` which is from webpack and looks like

 	function checkDeferredModules() {
 		var result;
 		for(var i = 0; i < deferredModules.length; i++) {
 			var deferredModule = deferredModules[i];
 			var fulfilled = true;
 			for(var j = 1; j < deferredModule.length; j++) {
 				var depId = deferredModule[j];
 				if(installedChunks[depId] !== 0) fulfilled = false;
 			}
 			if(fulfilled) {
 				deferredModules.splice(i--, 1);
 				result = __webpack_require__(__webpack_require__.s = deferredModule[0]);
 			}
 		}

and the problem is `if(installedChunks[depId] !== 0)` for some reason returns true which sets `fulfilled = false;` if I comment out this line IE 11 loads the JS files (fails elsewhere) but it at least loads them. If I don't it does absolutely nothing.

Now I don't really know webpack internals, but where should I start looking to solve this issue?

**Comment by sokra** [comment]
You also get a `styles.js` file which need to be included as `<script>` tag
