### ISSUE TITLE
Why does webpack-dev-server not execute compiler hook?

### ISSUE THREAD

**Issue by sp4rc** [webpack/webpack#10061]
Consider the following `webpack.config.js`. When running `npx webpack` my call to `console.log('Here goes my custom function')` gets executed. However when running `npx webpack-dev-server` it does not, although I can see it does the compilation. 

What I am basically trying to achieve is kick of a metalsmith build before the webpack compilation takes place. As said this works for manual builds but not when using `webpack-dev-server`

Why is that and how can I fix this?

    module.exports = {
          // ... 
        module: {
          // ...
        plugins: [  
            {
                apply: (compiler) =>{
                    compiler.hooks.beforeRun.tap('BeforeRunPlugin', (compilation) => {
                        console.log('Here goes my custom function')
                    })
                }
            },
            // ... 
        ],
        devServer: {  
            contentBase: join(__dirname, 'dist'),
            publicPath: './assets/',
            port: 7700,
            open: false,
            overlay: true, // show compiler errors as overlay
            writeToDisk: true,
        }
    };

**Comment by sokra** [comment]
There are two way to run webpack: `run` and `watch`. The dev-server uses `watch`.

The `beforeRun` hook is only called for `run` and not for `watch`.

You may want to use the `compile` hook instead.

**Comment by evilebottnawi** [comment]
You can use two hooks for running something on run and watch https://github.com/webpack/webpack-dev-middleware/blob/master/lib/utils/setupHooks.js#L66, thanks for question

**Comment by Jamiewarb** [comment]
Is there any documentation for which hooks run on dev and watch? I cannot find any here https://webpack.js.org/api/compiler-hooks/

**Comment by evilebottnawi** [comment]
There are no dev and watch hooks, only run and watchRun

**Comment by Jamiewarb** [comment]
Sure. So is there any documentation for hooks that run when using the `--watch` flag and ones that don't? E.G. `beforeRun`, as discussed above, isn't called when using `--watch`. Is this documented for this hook, and for other hooks?

**Comment by evilebottnawi** [comment]
No documented, you can look at source code and improve docs

**Comment by Jamiewarb** [comment]
Thank you
