### ISSUE TITLE
compatible output with "new Function()"

### ISSUE THREAD

**Issue by ThomasKientz** [webpack/webpack#10060]
Let's say we have this very simple script :

    // script.js
    
    return {foo : "bar"};

This script is meant to be executed within a `new Function()` like this :

    const res = new Function(`return {foo : "bar"};`) // res = {foo : "bar"}

But when I bundle this script with webpack, res becomes `undefined`. I guess its because webpack's output contains a self invoking function. 

## Idea

Have a configuration setting to make the output compatible with script that will be called inside javacript `new Function()`

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by ThomasKientz** [comment]
@sokra Thanks for having a look at https://github.com/ThomasKientz/webpack-issue-repro

**Comment by sokra** [comment]
hmm ok now I understand the issue.

One issue it that files processed by webpack are treated as modules, so either CommonJS, AMD or ESM. None of them allow to return a value. In CommonJS you assign the exports to `module.exports`, in AMD you wrap it in `define(...)` and in ESM you use `export`.

So you could use `module.exports = { foo: "bar" }`.

Which brings use to the next problem. The emitted file could be in multiple formats selectable via `output.libraryTarget`, but none of them allows to use `return`. I would be open to a PR adding `output.libraryTarget: "return"`, but you could also use your own plugin to enable this. Start by copying `SetVarTemplatePlugin` (webpack 5) resp. `SetVarMainTemplatePlugin` (webpack 4) and adjust that (=> `new ConcatSource("return ", source)` is the core result).

**Comment by ThomasKientz** [comment]
@sokra Thanks so muck, it makes sense. 

But I am having a hard time setting up the plugin, would you mind having a look to this [codesandbox](https://codesandbox.io/s/webpack-return-ugtkp) ? 

I have got the following error when building :
> Cannot read property 'hooks' of undefined

I don't understand how to properly set up the plugin in the webpack config:

```
module.exports = {
  entry: "./src/script.js",
  output: {
    filename: "script_webpack.js",
    path: path.resolve(__dirname, "dist")
  },
  mode: "production",
  plugins: [new SetVarMainTemplatePlugin()]
};
```

**Comment by sokra** [comment]
https://codesandbox.io/s/webpack-return-ifpy0

**Comment by ThomasKientz** [comment]
@sokra Awesome, thank you 🙏
