### ISSUE TITLE
Incorrect exit status when webpack-cli is not installed in non-interactive mode

### ISSUE THREAD

**Issue by aboks** [webpack/webpack#10076]
# Bug report

**What is the current behavior?**
When running webpack without webpack-cli installed, webpack helpfully asks "Do you want to install 'webpack-cli' (yes/no)" (great!). When the input stream is not interactive and there is no input provided (e.g. when running in CI or another automated process), webpack asks the question but never receives an answer. In this case webpack exits without installing webpack-cli and continuing, but still emits exit code 0. This leads to silent and hidden failures.

**If the current behavior is a bug, please provide the steps to reproduce.**
Install webpack without webpack-cli and run `webpack < /dev/null`.

**What is the expected behavior?**
I expect webpack to return a non-zero exit code in all cases where it was not able to build. In particular this includes all cases where webpack-cli is missing and wasn't installed automatically/on demand.

**Other relevant information:**
webpack version:  4.41.0
Node.js version: 12.13.1
Operating System: Ubuntu 18.04
Additional tools:

It seems that in cases like this, where there is no (interactive) input available on the input stream, `questionInterface.question()` never calls the answer callback.

**Comment by sokra** [comment]
Send a PR

**Comment by sunaku** [comment]
I'm currently working around this problem by forcing a "y" response via `yes` (thankfully the answer is read from stdin and not `/dev/tty` --- if that were the case, I'd have to use `expect` for automation):

```sh
yes | npm install webpack-cli
```

**Comment by aboks** [comment]
@sunaku Just to be sure and manage expectations: this issue (and the associated PR) is not about the need to confirm the installation of `webpack-cli`, just about having a proper exit status in all cases were `webpack-cli` was not installed. Even with the PR in place, you'd still need to pipe `yes` into the command if you want to auto-install `webpack-cli`. The only thing that changes is that if you don't use `yes |`, you get exit status 1 instead of 0.

**Comment by aboks** [comment]
Closing, as someone else made another PR for the same bug (#10351) that was merged earlier.
