### ISSUE TITLE
Type definitions use normal webpack plugin types for resolve.plugins

### ISSUE THREAD

**Issue by opl-** [webpack/webpack#10073]
# Bug report

**What is the current behavior?**

The [WebpackOptions.d.ts](https://github.com/webpack/webpack/blob/157c457241bf46b1cb31dbb17e806702eb4a0ec5/declarations/WebpackOptions.d.ts#L814) definitions use `(WebpackPluginInstance | WebpackPluginFunction)[]` for the prop's type. This is invalid as [per this test](https://github.com/webpack/webpack/blob/157c457241bf46b1cb31dbb17e806702eb4a0ec5/test/statsCases/resolve-plugin-context/ResolvePackageFromRootPlugin.js) resolve plugins are passed a `Resolver` instance.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Try to pass a resolver plugin that includes types (such as `tsconfig-paths-webpack-plugin`) in `resolve.plugins`.
2. TypeScript should error on compilation as the type doesn't match.

**What is the expected behavior?**

The types should correctly reflect the expected types.

**Other relevant information:**
webpack version: v4.41.2 and master
Node.js version: v12.13.1
TypeScript: v3.7.2
Operating System: N/A
Additional tools: N/A

**Comment by sokra** [comment]
Send a PR
