### ISSUE TITLE
Lazy loaded modules conflict (Micro Frontend )

### ISSUE THREAD

**Issue by devbikshu** [webpack/webpack#10079]
# Bug report

**What is the current behavior?**
I have three angular (version 7 and above) applications let's say:
1. shell application
2. sub application (client A)
3. sub application (client  B)

In my senario i wanted to load this sub applicaiton (A&B) into (shell) application.
so i have bundled my sub applications (A&B) with webpack configuration. 
(you can find my webpack configuration files below) 

STEP 1: I have bundled sub applications (A) with webpack configuration. Now following are the bundle.js files generated after building my angular sub application(A)
main.bundle.js 
1.main.bundle.js --> for lazyloaded modules (eg: angular login Module)

STEP 2: I have repeated same for sub application (B) also so it also produced following files
main.bundle.js 
1.main.bundle.js --> for lazyloaded modules (eg: angular signup Module)

STEP 3: Now i have created a navbar with nav links for app1 & app2 in shell angular application and i am appending the main.bundle.js file of each sub application on demand.
As a result i am able to load both the sub applications into shell application successfully. 

STEP 4: when it comes to serve the lazyload module form sub application (A) it is serving the content but fom sub application(B)   when i am loading lazyload module it't throwing following error as it referring already loaded 1.main.bundle.js of loginModule of sub application (A).

I could see this on network tab of chrome developer tool.

ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'call' of undefined
TypeError: Cannot read property 'call' of undefined

Reason behind error:

when i am loading lazyload module (login Module) form sub application(A) in angular shell  application 1.main.bundle.js file loading and it is serving the purpose.

when i am loading azyload module (signup Module) form sub application (B) in angular shell  application it is also referring previous 1.main.bundle.js so as a name conflict it is throwing following error. 

ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'call' of undefined
TypeError: Cannot read property 'call' of undefined

Webpack config file for sub application A: 
```
const AotPlugin = require('@ngtools/webpack').AngularCompilerPlugin;
const environment = 'http://localhost:4300/assets/';
const path = require('path');
const webpack = require('webpack');

const clientA = {
    entry: './src/main.ts',
    resolve: {
        mainFields: ['browser', 'module', 'main']
    },
    module: {
        rules: [
            { test: /\.ts$/, loaders: ['@ngtools/webpack'] },
            {
                test: /\.html$/,
                use: 'raw-loader'
                
            },
            {
                test: /\.js$/,
                loader: '@angular-devkit/build-optimizer/webpack-loader',
                options: {
                    sourceMap: true
                }
            }

        ]
    },
    plugins: [

        new AotPlugin({
            skipCodeGeneration: false,
            tsConfigPath: './tsconfig.app.json',
            hostReplacementPaths: {
                "./src/environments/environment.ts": "./src/environments/environment.prod.ts"
            },
            entryModule: path.resolve(__dirname, './src/app/app.module#AppModule')
        }),
        new webpack.DefinePlugin({
            ngDevMode: true,
            ngI18nClosureMode: false
        })
        

    ],
    output: {
        path: __dirname + '/src/assets',
        filename: 'main.bundle.js',
        publicPath: environment
    },
    mode: 'production'
};

module.exports = [clientA];
```
Webpack config file for sub application B: 
```
const AotPlugin = require('@ngtools/webpack').AngularCompilerPlugin;
const environment = 'http://localhost:4300/assets/';
const path = require('path');
const webpack = require('webpack');

const clientB = {
    entry: './src/main.ts',
    resolve: {
        mainFields: ['browser', 'module', 'main']
    },
    module: {
        rules: [
            { test: /\.ts$/, loaders: ['@ngtools/webpack'] },
            {
                test: /\.html$/,
                use: 'raw-loader'
                
            },
            {
                test: /\.js$/,
                loader: '@angular-devkit/build-optimizer/webpack-loader',
                options: {
                    sourceMap: true
                }
            }

        ]
    },
    plugins: [

        new AotPlugin({
            skipCodeGeneration: false,
            tsConfigPath: './tsconfig.app.json',
            hostReplacementPaths: {
                "./src/environments/environment.ts": "./src/environments/environment.prod.ts"
            },
            entryModule: path.resolve(__dirname, './src/app/app.module#AppModule')
        }),
        new webpack.DefinePlugin({
            ngDevMode: true,
            ngI18nClosureMode: false
        })
        

    ],
    output: {
        path: __dirname + '/src/assets',
        filename: 'main.bundle.js',
        publicPath: environment
    },
    mode: 'production'
};

module.exports = [clientB];
```
**If the current behavior is a bug, please provide the steps to reproduce.**

try to load webpack lazyload bundle js files of same naming convention 

**What is the expected behavior?**

**Other relevant information:**
webpack version:  3.3.10
Node.js version: 12.13.0
Operating System: windows 10
Additional tools: none

![img](https://user-images.githubusercontent.com/18551819/70145152-737a8880-16c5-11ea-9b6a-c5b25e13a932.png)

Any Help to fix this i am struggling from last one week to resolve.

Thanks in Advance.

**Comment by montogeek** [comment]
Have you tried changing the names of the chunks?

**Comment by devbikshu** [comment]
@montogeek No i have not tried. In fact i don't know how to do that as i am new to webpack.

It will be helpful if you guide me. I will try with it.

**Comment by sokra** [comment]
Try to use a unique `output.jsonpFunction` for each application.

**Comment by devbikshu** [comment]
Thank you! @sokra 

I have mentioned output.jsonpFunction in my webpack.config.js this solved my problem.

**Comment by humorHan** [comment]
Want to ask a question, is your micro front terminal application independently deployed? How to load sub applications? If not, how to ensure that components can be referenced asynchronously in a sub application
