### ISSUE TITLE
watchOptions.aggregateTimeout cannot be 0

### ISSUE THREAD

**Issue by simonhowey** [webpack/webpack#10071]
# Bug report

**What is the current behavior?**
Using a config with:
`
    watchOptions: {
      aggregateTimeout: 0
    },
`
Reverts to aggregateTimeout to 200 due to the || assignment here:

https://github.com/webpack/webpack/blob/c41bf0ed24ecba2a6406697481d699db8dbce379/lib/Watching.js#L46

happens here as well:

https://github.com/webpack/watchpack/blob/c0221fc3be199b34711909c6c1245fc1054c7a51/lib/watchpack.js#L67

**If the current behavior is a bug, please provide the steps to reproduce.**

Use a config with:
   ` watchOptions: {
      aggregateTimeout: 0
    },`

**What is the expected behavior?**

Not positive what expected behaviour is supposed to be. IMO either: 
- should change docs to note it should be > 0 and throw an error/warning if its 0
- change code to accept 0

Looking at watchpack it looks like 0 is fine it just ends up being a setTimeout value.

I can put in a PR for either.

**Other relevant information:**
webpack version:  4.41.0
Node.js version:  v10.17.0
Operating System: OSX
Additional tools:

**Comment by sokra** [comment]
> * change code to accept 0

Send a PR

**Comment by jeffin143** [comment]
@sokra , let's close this if fixed
