### ISSUE TITLE
Error with Vue lazy loading components

### ISSUE THREAD

**Issue by cuidaowang** [webpack/webpack#10075]
I am currently using vue to develop a layout framework, which is integrated into this framework after others develop applications. The specific way is to copy the resource path to an index.html after other applications are compiled. The vue components in each application are introduced through lazy loading. Each vue component is compiled into a separate .js file.
However, I found that conflicts will occur when different applications are integrated. As shown in the figure: 
![微信图片_20191204152728](https://user-images.githubusercontent.com/55750041/70121698-19b89500-16aa-11ea-841f-8d38133c0b01.jpg)
![微信图片_20191204152741](https://user-images.githubusercontent.com/55750041/70121702-1b825880-16aa-11ea-969b-ecf3d58e4bf7.jpg)
The above two pictures show building codes of different applications. Components with the same number are in conflict. If you open one and open the other, an error will be reported. For example, the FTKfwwyt in Figure 1 and the sjklgl in Figure 2 are numbered 1. Each component can only open one, and an error will be reported when opening the other. The error information is shown in the following figure:
![微信图片_20191204153544](https://user-images.githubusercontent.com/55750041/70122235-373a2e80-16ab-11ea-8eeb-f1746fd9662e.jpg)
I want to know what is the reason for this and how to solve it? What configuration can be used to make the component number unique？
Thanks very much！

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
