### ISSUE TITLE
Webpack generates script tags that will trigger warning for W3C HTML validator due to the extra type attribute

### ISSUE THREAD

**Issue by ye** [webpack/webpack#10074]
# Bug report

**What is the current behavior?**

Webpack generates the script tags with JavaScript resources that has an extra type attribute `type` that will trigger warning for W3C HTML validator.
![Screen Shot 2019-12-03 at 10 30 59 PM](https://user-images.githubusercontent.com/133924/70110445-f98ec480-161c-11ea-8e66-cd7f162e1ecc.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

Use webpack to build an react app, it add the bundled main.XXXXXX.js file in a script tag with the extra `type="text/javascript"` attribute.

The type attribute is unnecessary for JavaScript resources, e.g.

```html
<script type="text/javascript" src="/main.211a6080b1002980d663.js"></script>
```

**What is the expected behavior?**

It should NOT add `type="text/javascript"` attribute. Removing that attribute, it will pass W3C HTML validator clean.

e.g.

```html
<script src="/main.211a6080b1002980d663.js"></script>
```

**Other relevant information:**
webpack version:  `4.39.8`
Node.js version: `v12.8.0`
Operating System: `macOS Mojave 10.14.6`
Additional tools:

**Comment by evilebottnawi** [comment]
It is warning, also it is require for old browsers, solved for webpack@5 https://github.com/webpack/webpack/blob/master/lib/WebpackOptionsDefaulter.js#L284

**Comment by ye** [comment]
> It is warning, also it is require for old browsers

@evilebottnawi **No, type is NEVER required for HTML 5** because in HTML 5 spec, type is default to `text/javascript`. 
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script

It was only required in [HTML 4 spec](https://www.w3.org/TR/REC-html40/interact/scripts.html), but how many projects who use webpack to build single page apps do you expect to follow HTML 4 spec not HTML 5 spec??

Modern browsers are updating at least monthly, so I don't know what you are talking about by "old browsers". We are not living in pre-2014 days ([that's when HTML5 was first officially released](https://en.wikipedia.org/wiki/HTML5))

So no, I don't think your reasoning is valid - why does one of most popular JavaScript tools is insisting to generate standard non-compliant markup code????

We should backport that fix into webpack 4.x as well.

**Comment by evilebottnawi** [comment]
@ye it is breaking change for webpack@4, we can't do it, because some developers can use webpack for old browsers as i said before

**Comment by ye** [comment]
@evilebottnawi again as I said, what "older" browsers? The ones who only support HTML4 from 1999? It simply doesn't make sense. Yes it's a breaking change, in the sense that HTML5 is NOT compatible with HTML4. But webpack 4.x must support HTML 4 from 1999 ??? Do you even have a concrete example of that use case???
