### ISSUE TITLE
`SourceMapDevToolPlugin ... generate SourceMap` for vendors takes a very long time

### ISSUE THREAD

**Issue by igozali** [webpack/webpack#10087]
# Bug report

**What is the current behavior?**
I'm experiencing a massive performance regression between `webpack@4.28.4` and `webpack@4.41.2`, in particular during the `SourceMapDevToolPlugin ... generate SourceMap` for vendors.

When I use `webpack@4.28.4` to build my project in production mode, this step takes 3-4 seconds tops. However, after I upgrade to the latest `webpack@4.41.2` by using `npm i webpack@latest`, my build would be stuck at this step for a very long time (> 5 minutes):
```
93% after chunk asset optimization SourceMapDevToolPlugin 660c9e1426ee984771b2.vendors.bundle.js generate SourceMap
```

I'm using the following build command and the same config before and after the webpack update:
```
npx webpack --colors --display-modules --progress --config ./webpack.prod.config.js
```

I tried looking at the diff of `package-lock.json` before and after the update, but I couldn't find anything out of the ordinary.

**If the current behavior is a bug, please provide the steps to reproduce.**
All of the files that I think are relevant are here. 

 - [Initial `package.json`](https://gist.github.com/igozali/854ec0c7d6245f8513acf4b750f122b2#file-package-json)
 - [Initial `package-lock.json`](https://gist.github.com/igozali/854ec0c7d6245f8513acf4b750f122b2#file-package-lock-json)
 - [`webpack.base.config.js`](https://gist.github.com/igozali/854ec0c7d6245f8513acf4b750f122b2#file-webpack-base-config-js)
 - [`webpack.prod.config.js`](https://gist.github.com/igozali/854ec0c7d6245f8513acf4b750f122b2#file-webpack-prod-config-js)
 - [Diff for `package.json` after running `npm i webpack@latest`](https://gist.github.com/igozali/854ec0c7d6245f8513acf4b750f122b2#file-package-json-diff)
 - [Diff for `package-lock.json` after running `npm i webpack@latest`](https://gist.github.com/igozali/854ec0c7d6245f8513acf4b750f122b2#file-package-lock-json-diff)

Unfortunately, I don't have an example project for a MWE since this occurred on a work project. I was hoping some insights could be gained from the `package-lock.json` diffs, but if not, please let me know and I'll try to reproduce with a simple project.

**What is the expected behavior?**
The expected behavior is the one before the webpack update, where the generate SourceMap step on vendors takes 3-4 seconds.

**Other relevant information:**
webpack version:  4.41.2
Node.js version:  13.2.0
Operating System:  macOS Mojave 10.14.6
Additional tools:  npm@6.13.1

**Comment by evilebottnawi** [comment]
Because you have big vender, generating source map is very resource intensive operation, why it is increase because we fix bugs in generation source map, so previously you have broken source maps, now very are not broken, but require more time, unfortunately we can't do something on our side, in webpack@5 we cache source map so it should solve faster

**Comment by igozali** [comment]
Thanks very much for the explanation @evilebottnawi. Could you describe a bit more how (i.e. in what way) the previous source map generation was broken? And is there a config option (or some other way) in `webpack@4.41.2`  to keep the previous source map generation mechanism even though it's broken?

If what I care most is the time it takes to build my project, I suppose the easiest workaround is to stay at `webpack@4.28.4` then?

**Comment by sokra** [comment]
`devtool: "source-map"` create high quality source maps. If you prefer lower quality SourceMaps that are faster to generate check the table in the docs: https://webpack.js.org/configuration/devtool/

**Comment by shen-zhao** [comment]
I encountered the same problem. I import a non-default export of an npm package. My build would be stuck at `SourceMapDevToolPlugin ... generate SourceMap`. then I try to configure alias and it's working! but when I open a another terminal win to build. alias also has no effect. final Sometimes effective, sometimes invalid.

**Comment by evilebottnawi** [comment]
@shen-zhao Can you create reproducible test repo?

**Comment by shen-zhao** [comment]
Thank you for your reply @evilebottnawi , I create a repo for my problem; 
Here are some notes：
1.`@mc/phone-pc-sdk`is a private package, so I was submitted the `node_modules`, so you don't need run `npm i`
2.Error running script locally, But you do n’t need to worry, it does not affect the `build`
3.I wrote the reproduction process in readme, 
repo link: https://github.com/shen-zhao/webpack-test-repo

**Comment by evilebottnawi** [comment]
@shen-zhao weird, both variants are very slow, maybe something wrong with reproducible test repo, but it is expected, you have really big file, I'm afraid that there really is nothing to be done, maybe you should think about not to ship the whole vue with components

**Comment by shen-zhao** [comment]
> @shen-zhao weird, both variants are very slow, maybe something wrong with reproducible test repo, but it is expected, you have really big file, I'm afraid that there really is nothing to be done, maybe you should think about not to ship the whole vue with components

sorry, please delete the `alias` in the `vue.config.js` and try again

**Comment by shen-zhao** [comment]
@evilebottnawi 
Actually, we project have big vendors file around 7M!, but it has little effect on the speed of the build. Takes about 50 seconds

**Comment by shen-zhao** [comment]
I changed the file name to make the build speed normal. `esm.vue.js` => `esm.xxx.js`. `xxx` as long as it is not `vue`. I guess it may be that `vue-cli` did some special processing (I will continue to investigate), because I build both very slow by my own configuration. 
@evilebottnawi   It may be a waste of your time. Thank you very much
