### ISSUE TITLE
What is the recommend way to modify module result?

### ISSUE THREAD

**Issue by sunzongzheng** [webpack/webpack#10081]
I cannot find the recommend way to modify module result after reading the docs.
I tried to modify `module._source._value` to modify result. But I get some troubles.
When file has dependencies, it turns strange in the output file.

I made an smallest repo
https://github.com/sunzongzheng/webpack-plugin-to-modify-module-content-sample

**Comment by sokra** [comment]
If you want to do a larger transformation to a module, use a loader. You can add loaders from a plugin e. g. in normalModuleFactory.hooks.afterResolve

If you want to make small replacements or inject things that depend on other parts of the Compilation, use a custom dependency with a template.

**Comment by sunzongzheng** [comment]
@sokra I want to collect the files's dependencies and write then in output file.
For example,the dependencies are as follows
`a` depend `b`
`b` depend `c`
Then I get file `a`'s dependencies list `[b, c]`, and then write it to `a`'s module result.

I want to collect the files's dependencies through loaders. And the output file is a module which export dependencies.

So loader perhaps can not resolve my problem? I need loader's result to get dependencies.
Could you please explain more about the `use a custom dependency with a template`? Can it meet my needs?

**Comment by sunzongzheng** [comment]
In fact, I have two compiler. One of them output the normal module, and the other one output the dependencies.

**Comment by acupofspirt** [comment]
@sokra 
> If you want to do a larger transformation to a module, use a loader. You can add loaders from a plugin e. g. in normalModuleFactory.hooks.afterResolve
> 
> If you want to make small replacements or inject things that depend on other parts of the Compilation, use a custom dependency with a template.

Is there any documentation or example for custom dependencies? 
I need to rewrite file content with things like 
```
export default () => ({
  a: () => import('../foo/bar/file.js'),
  b: () => import('another/file/path.js')
})
```
I've tried a custom dependency with template inside _buildModule_ hook to modify a file content but that updated content remains untranspiled/unprocessed by other loaders/plugins. Using loaders is not a solution in my case.

**Comment by sokra** [comment]
For a custom dependency:

step 1: parsing:

Add some kind a placeholder to the file where your content should be added. e. g. `INSERT_CONTENT_HERE` (use a better name). This could also be added by a loader e. g. a loader appending: `import { register } from "registry"; register(module.id, INSERT_CONTENT_HERE);`.

Hook into the `(Javascript)Parser` to react on your placeholder: `parser.hooks.expression.for("INSERT_CONTENT_HERE").tap("...", expr => {...})`.

Add a Dependency to the module via `parser.state.module.addDependency(new MyDependency(expr.range))`.

step 2: create a Dependency class

Create your own dependency by extending e. g. webpacks `NullDependency`.

step 3. register a DependencyTemplate.

``` js
compilation.dependencyTemplates.set(MyDependency, new MyDependency.Template())
```

The teamplate is a class with an apply method. Check `DependencyTemplate` for the signature. You can also use it as base class.

In the apply method call `source.replace(dep.range[0], dep.range[1] - 1, "NEW CONTENT")`

**Comment by csr632** [comment]
Here is a SO answer that also talks about "custom dependency":
https://stackoverflow.com/a/52906440/8175856

**Comment by PeteSolid** [comment]
I also would like to modify a module after the loaders but after one specific Plugin. So is there a proper way to replace content in a plugin?

**Comment by KaiWinding** [comment]
After reading sokra's answer, I writed a plugin to implement this feature. Maybe you can try it: 
https://github.com/KaiWinding/modify-webpack-plugin

**Comment by PeteSolid** [comment]
@KaiWinding Thank you, I tried it but it does not work for me.
By now I have tried multiple ways to solve it.

Maybe some context will help:
So I am using the HtmlWebpackPlugin together with the prerender-loader from GoogleChromeLabs. I want to server-side render my page, but the render functions will still be in the TypeScript file. Even though I exclude the library in the webpack config. That is why I want to remove the function calls after the inline prerender-loader in the HtmlWebpackPlugin. 
Sadly, modifying the JS/TS will lead to Terser Error. Tried it with Closure Compiler and the same.

**Comment by artemirq** [comment]
Maybe someone will be interested. I've created webpack plugin for modifying modules source, which is based on sokra solution with loader and adding this loader by plugin.

Webpack 4 and 5 is supported.

```js
module.exports = {
  plugins: [
    new ModifyModuleSourcePlugin({
      test: /my-file\.js$/,
      modify: (src, filename) =>
        src +
        `\n// my new comment inside of ${filename} file`
    })
  ]
};
```

Link: https://github.com/artemirq/modify-source-webpack-plugin.
Any feedback appreciated.

**Comment by artemirq** [comment]
@sokra Is there any way to modify raw source files before they prepared to be processed with loaders?

For example with this configuration

```js
{
  module: {
    rules: [
      {
        test: /\.css$/i,
        use: ['style-loader', 'css-loader']
      }
    ]
  }
}
```

We will get these modules:

1) `/node_modules/css-loader/dist/cjs.js ! /path/to/css-file.css`
2) `/node_modules/style-loader/dist/cjs.js ! /node_modules/css-loader/dist/cjs.js ! /path/to/css-file.css`

But I want to get access to single raw source to avoid duplication in the case of modifying files.
