### ISSUE TITLE
Compilation progress is displayed to stderr instead of stdout

### ISSUE THREAD

**Issue by Kcchouette** [webpack/webpack#10086]
# Bug report

**What is the current behavior?**

Compilation progress is written to stderr, and so maven show it as Errors.

Eg: 
```
<execution>
            <id>webpackBuild</id>
            <phase>generate-resources</phase>
            <goals>
              <goal>npm</goal>
            </goals>
            <configuration>
              <arguments>run build:prod</arguments>
            </configuration>
          </execution>
```

And so running a command maven (eg `mvn compile`):

```
[ERROR] 62ms sealing
[ERROR] 4ms optimizing 
[ERROR] 0ms basic module optimization 
[ERROR] 12ms module optimization
[ERROR] 1ms advanced module optimization 
[ERROR] 0ms basic chunk optimization 
[ERROR] 0ms chunk optimization 
[ERROR] 0ms advanced chunk optimization 
[ERROR] 0ms module and chunk tree optimization 
[ERROR] 50ms module reviving
[ERROR] 4ms module order optimization 
[ERROR] 6ms module id optimization 
[ERROR] 6ms chunk reviving 
[ERROR] 0ms chunk order optimization 
[ERROR] 14ms chunk id optimization
[ERROR] 55ms hashing
[ERROR] 1ms module assets processing 
[ERROR] 104ms chunk assets processing
[ERROR] 2ms additional chunk assets processing 
[ERROR] 0ms recording
```

**What is the expected behavior?**

 Compilation progress is shown as info text (or warning, or debug).

**Other relevant information:**
webpack version:  4.41
Node.js version: 6.17.1
Operating System: Ubuntu 19.10
Additional tools: maven 3.6.1

Seems related to #3520

**Comment by sokra** [comment]
That's working as intended. stderr is for diagnostics information not only for errors. Maven incorrectly displays that as errors.

**Comment by Kcchouette** [comment]
Seems fixed on https://github.com/eirslett/frontend-maven-plugin/issues/733#issuecomment-553331792
