### ISSUE TITLE
__WEBPACK_EXTERNAL_MODULE__ is not defined with dynamic amd require

### ISSUE THREAD

**Issue by shaosh** [webpack/webpack#10088]
We trying to migrate from old requirejs build pipeline to webpack. In the legacy code, we imported the i18n related data with something like
    
    import i18n from '@webui/i18n-amd-loader!@webui-legacy/upgraded-url';

Requirejs can recognize it and use the i18n-amd-loader to get the resource of @webui-legacy/upgraded-url.

When moving to webpack, in case this requirejs-specific code can't be understood, I put it into externals: 

    function(context, request, callback) {
        if (/@webui\/i18n-amd-loader!/.test(request)){
            return callback(null, 'amd ' + request);
        }
        callback();
    }

We expect webpack to just skip this line, not do anything, just wait for require to run it and get the resource.

Build is fine, and the file is compiled into amd mode. However, when running, it shows error before it gets to the code:

    ReferenceError: __WEBPACK_EXTERNAL_MODULE__900y__ is not defined

__WEBPACK_EXTERNAL_MODULE__900y__ is the variable representing @webui/i18n-amd-loader!@webui-legacy/upgraded-url.

It seems webpack tried to find the resource of '@webui/i18n-amd-loader!@webui-legacy/upgraded-url' but failed. 

Is there work around to fix this issue? I tried ignorePlugin but it doesn't work.

**Comment by sokra** [comment]
Make sure to make your output file a AMD library with `output.libraryTarget: "amd"`. This way it's wrapped in `define` which is needed for AMD to work.

**Comment by shaosh** [comment]
@sokra Thanks for the quick response. The output.libraryTarget is amd. The file's name is campaign.js. If I build it separately, I can see @webui/i18n-amd-loader!@webui-legacy/upgraded-url in the dependency list of the define. However, when I built the entire large app, the campaign.js get chunked and then this error shows.

**Comment by shaosh** [comment]
If I build the entire app with libraryTarget: 'amd', it will fail without any error.

**Comment by shaosh** [comment]
I think I understand the reason of this issue. The entire app is not built into amd mode.
