### ISSUE TITLE
Webpack Dynamic Import ES6 Class shows incorrect mime type

### ISSUE THREAD

**Issue by pavrip** [webpack/webpack#10096]
# Bug report

**What is the current behavior?**
When dynamically importing a basic JavaScript Class I am getting the following error:
The script from “https://map-1:8890/public/assets/js/chunk.bundle.js” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type.

The caught webpack error:
ChunkLoadError: "Loading chunk chunk failed.
(error: https://map-1:8890/public/assets/js/chunk.bundle.js)"
    requireEnsure https://map-1:8890/assets/js/app.js:106
    <anonymous> webpack:///./app/index.js?:8
    js https://map-1:8890/assets/js/app.js:212
    __webpack_require__ https://map-1:8890/assets/js/app.js:64
    <anonymous> https://map-1:8890/assets/js/app.js:199
    <anonymous> https://map-1:8890/assets/js/app.js:202

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

**Comment by rishabh3112** [comment]
@pavrip thanks for filing issue. Send a minimal repository which simulates the issue.

**Comment by sokra** [comment]
The URL seem to be wrong `https://map-1:8890/public/assets/js/chunk.bundle.js` should be `https://map-1:8890/assets/js/chunk.bundle.js` instead. See `output.publicPath` option for solutions.
