### ISSUE TITLE
a nameless vendor chunk not triggers HMR updates

### ISSUE THREAD

**Issue by felixmosh** [webpack/webpack#10095]
# Bug report

**What is the current behavior?**
HMR not triggers an update when vendor chunk is nameless.

**Steps to reproduce:**
1. clone https://github.com/felixmosh/i18next-hmr/tree/master/examples/react-i18next
2. npm i
3. npm start
4. update some key in `public/locales/en/translation.json`.
   It will send to client something  like
   ```
   {"h":"7a2a05a02fe8fcfc2289","c":{"0":false}}
   ```
   but the `module.hot.accept` is **not triggered**.
5. change in `config/webpack.config.js` `splitChunks.name: true`
6. re-do steps 3-4, client side will get a proper update and `module.hot.accept` will be triggered.

**What is the expected behavior?**
It should trigger an HMR update for a nameless chunks.

**Other relevant information:**
webpack version:  4.x latest
Node.js version: 8
Operating System: macOS 
Additional tools:

**Comment by sokra** [comment]
I could imagine this is related to the way react-i18next handles translations. Please report it there.

If you think this is a webpack problem, please create a **minimal** repro repo to show it.

**Comment by felixmosh** [comment]
It is not related to i18next.
The repo that I’ve shared is based on CRA, and it reproduces all the time there.

**Comment by felixmosh** [comment]
Ping?

**Comment by felixmosh** [comment]
@sokra ?

**Comment by felixmosh** [comment]
ping

**Comment by evilebottnawi** [comment]
Please create reproducible test repo https://github.com/webpack/webpack/issues/10095#issuecomment-562996603

**Comment by felixmosh** [comment]
> Please create reproducible test repo [#10095 (comment)](https://github.com/webpack/webpack/issues/10095#issuecomment-562996603) or give steps to reproduce it

There are steps in the main post :\
![image](https://user-images.githubusercontent.com/9304194/76759632-c1a72980-6794-11ea-9f1f-29c8f82bbf77.png)

**Comment by felixmosh** [comment]
Ping

**Comment by felixmosh** [comment]
fix by https://github.com/webpack/webpack/pull/10773
