### ISSUE TITLE
JSON post loader

### ISSUE THREAD

**Issue by josias-r** [webpack/webpack#10098]
# Bug report

Currently, I can't create a post loader for JSON files.

[Related question](https://stackoverflow.com/questions/59012195/webpack-custom-loader-reuse-file-extension)

**What is the current behavior?**

I've created a custom loader, which reads JSON files and returns a react component. With my understanding, the "enforce" property for a rule should make the loader run after normal loaders are run, when set to "post". Therefore, it should be possible to return a react component instead of JSON.

But somehow this doesn't work and I get an invalid JSON error, because the integrated JSON loader still tries to load JSON even though this shouldn't happen after a post loader, or should it?

**What is the expected behavior?**

I'd like to "extend" the JSON loader with my own loader for specific files like `*.xyz.json`, but I can't see how this is currently possible, because it always runs as the last loader.

**Other relevant information:**
webpack version:  4.39.0

**Comment by Lyrkan** [comment]
Hey @josias-r,

You'll have to set the type of the rule using your loader to something else than `json` if you don't want its output to go through the default JSON parser: https://webpack.js.org/configuration/module/#ruletype

Currently a loader can't do it itself without using some internal properties (see https://github.com/webpack/webpack/issues/7057)

**Comment by evilebottnawi** [comment]
Answer above use https://webpack.js.org/configuration/module/#ruletype, you can setup loader too, like
```
module.exports = {
  //...
  module: {
    rules: [
      //...
      {
        test: /\.json$/,
        type: 'javascript/auto',
        loader: 'custom-json-loader'
      }
    ]
  }
};
```

**Comment by josias-r** [comment]
🤯thank you very much! I was searching for this for so long, I don't know why I couldn't find it.
