### ISSUE TITLE
Performant alternative to stats objects for getting preload/prefetch childAsset info

### ISSUE THREAD

**Issue by maclockard** [webpack/webpack#10094]
## Feature request

**What is the expected behavior?**

Currently, the only way to get whether a child asset of an entry point should be preloaded/prefetched in a plugin is to use the [`stats` object](https://webpack.js.org/api/node/#stats-object), however, for larger builds this can be too slow. Similarly to how there is an API for getting basic entry point info in a performant way avoiding the `stats` object, there should possibly be an API for getting this preload/prefetch information in a lightweight way.

**What is motivation or use case for adding/changing the behavior?**

If [html-webpack-plugin](https://github.com/jantimon/html-webpack-plugin) had access to a performant API for preload/prefetch info, it would be able to support preload/prefetch for the child assets of entry points in the initial HTML. This could significantly speed up initial load for larger bundles that make heavy use of async chunks.

**How should this be implemented in your opinion?**

Possibly extending the existing `compilation.entrypoints` API that html-webpack-plugin already uses?

**Are you willing to work on this yourself?**

No. I'm simply filing this on behalf of @jantimon since he expressed the need for this feature before being able to add support for preloading/prefetching chunks to [html-webpack-plugin](https://github.com/jantimon/html-webpack-plugin).

Relevant discussions with more information:
- https://github.com/jantimon/html-webpack-plugin/issues/934
- https://github.com/jantimon/html-webpack-plugin/pull/1014
- https://github.com/jantimon/html-webpack-plugin/issues/1150
- https://github.com/facebook/create-react-app/issues/3319

**Comment by maclockard** [comment]
Keep this open! Still needed

**Comment by evilebottnawi** [comment]
bump

**Comment by maclockard** [comment]
This issue should remain open. The inactivity bot should only close issues if it’s blocked on the original poster. This still needs comment from the maintainers.

**Comment by maclockard** [comment]
This issue should remain open. The inactivity bot should only close issues if it’s blocked on the original poster. This still needs comment from the maintainers.

**Comment by sokra** [comment]
The stats only extracts information from the compilation. All information is also available there.

**Comment by maclockard** [comment]
My understanding is that using stats is too slow for html-webpack-plugin, which is why they use `compilation.entrypoints`, however, I don't think `compilation.entrypoints` includes information on children that should be preloaded/prefetched.

See this comment here from @jantimon https://github.com/jantimon/html-webpack-plugin/issues/1150#issuecomment-460156688

It's just a shame that you can't preload any secondary chunks until after the initial chunk has fully loaded. If html-webpack-plugin was able to add `preload` script tags for those secondary chunks, it could result in pretty significant improvements of initial load for certain cases. My understanding is the only blocker on that is the fact the only way to get the required info (the stats object) is too slow.

**Comment by maclockard** [comment]
Also, more conversation on the problems here: https://github.com/jantimon/html-webpack-plugin/issues/1317

**Comment by evilebottnawi** [comment]
@maclockard It seems to me that it should be solved differently, there are two interesting cases:
- you don't have HTML output - here webpack generate runtime code and all works fine
- you have HTML output - you want to generate `link` and you can't do it right now

Note that both cases can exist at the same time in your app - one chunk can load other chunk which load other chunk and have preloads other chunks, injecting link inside HTML is not good idea, because you can't use it only on one/two pages in your app, not in the whole application, using `compilation.entrypoints` is not quite suitable in your case, I think `html-webpack-plugin` should have options for this
