### ISSUE TITLE
ModuleConcatenationPlugin cost much time

### ISSUE THREAD

**Issue by fodelf** [webpack/webpack#10103]
## Feature request

**What is the expected behavior?**
when we use webpack ModuleConcatenationPlugin  it cost us much time

**What is motivation or use case for adding/changing the behavior?**
I hope it work faster when we use the ModuleConcatenationPlugin 

**How should this be implemented in your opinion?**
reason ： i guess  in the ModuleConcatenationPlugin.js  , user the _tryToAdd function when our project it import many js ,it will cost much time. example [https://github.com/angular/angular-cli/issues/11327]
plan one :  cache all  problem , like this : const failureCache = require("./failureCache.js");it works;
plan two :  use nodejs worker_threads  to lifting speed

**Are you willing to work on this yourself?**
yes

**Comment by evilebottnawi** [comment]
In webpack@5 we implement cache on that level, it should be improve build time

**Comment by fodelf** [comment]
@evilebottnawi   I have read  ModuleConcatenationPlugin.js in @5.0.0-beta.9, the _tryToAdd function still not improve ; for example ，my project will run  the _tryToAdd   function  more then 10000 times, can you give me some  methods for the trouble,thanks

**Comment by evilebottnawi** [comment]
bump
