### ISSUE TITLE
import from node_modules breaks the code 

### ISSUE THREAD

**Issue by shhlkien** [webpack/webpack#10102]
# Bug report

**What is the current behavior?**
Edit:
Webpack cannot resolve import **outsite** source folder
e.g: I have folder structure like this:
```
webpack
  config.js
src
  js
    index.js
    test.js
public
  js
    somefile.js
```
I can import `test.js` since it in the same folder with `index.js` but not lucky with `somefile.js`
Webpack ouput done but code not working

**If the current behavior is a bug, please provide the steps to reproduce.**
**webpack.config.js**
```js
const path = require('path');

module.exports = {
  mode: 'development',
  entry: {
    index: './src/js/index.js',
  },
  output: {
    filename: 'bundle.js',
    publicPath: '/assets/',
    path: path.resolve('assets')
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader',
          options: {
            cacheDirectory: true,
            presets: ['@babel/preset-env']
          }
        }
      },
    ]
  },
  resolve: {
     extensions: ['.js']
  },
};
```
**src/js/index.js**
```js
import { VERSION } from "lodash";
import $ from "jquery";
console.log($('body'), VERSION); 
console.log('does this work?'); // didn't log anything
```

**What is the expected behavior?**
Code works as expected.

**Other relevant information:**
webpack version:  ^4.35.0
Node.js version: v10.17.0
Operating System: Ubuntu 18.04
Additional tools:

**Comment by evilebottnawi** [comment]
Please create reproducible test repo

**Comment by shhlkien** [comment]
> Please create reproducible test repo

I created a repo here: [https://github.com/shhlkien/webpack-test](https://github.com/shhlkien/webpack-test).

**Comment by sokra** [comment]
I think your manifest generation is incorrect and not all relevant script file are included. Check if your code is executed at all.

**Comment by shhlkien** [comment]
> I think your manifest generation is incorrect and not all relevant script file are included. Check if your code is executed at all.

My code works well if I don't import external library from node_modules

![image](https://user-images.githubusercontent.com/23404165/70909774-bda62700-2040-11ea-8116-8f87ac10fc1e.png)

![image](https://user-images.githubusercontent.com/23404165/70909687-92bbd300-2040-11ea-8847-794b96151edf.png)

**Comment by shhlkien** [comment]
Turn out I imported missing modules. Sorry for bothering.
