### ISSUE TITLE
extract-text-plugin: Rewrite CSS to require images first

### ISSUE THREAD

**Issue by IngwiePhoenix** [webpack/webpack#1011]
I just realized, that https://github.com/webpack/extract-text-webpack-plugin is actually taking the raw CSS it got from the `css-loader` and strips it from the original chunk to extract it somewhere else.

It would be very nice if I would still get the benefits of the re-written `import` and `url()` statements, as I want to use the `img-loader` for image optimization.

Is there a way to implement that?

**Comment by sokra** [comment]
> It would be very nice if I would still get the benefits of the re-written import and url() statements, as I want to use the img-loader for image optimization.

This does work. You get the same result as with `style!css`.

**Comment by IngwiePhoenix** [comment]
That’s odd. because my background image, for instance, is not being processed.

    #blurr-bg, #bg {
        background: url("/cdn/theme/images/bg.jpg");
    }

Is it because of the URL starting with a slash, maybe?

**Comment by sokra** [comment]
yep... see css-loader > readme > root-relative urls

**Comment by IngwiePhoenix** [comment]
That helped :) But I still can't seem to be able to replace this:

    @import url(//fonts.googleapis.com/css?family=Roboto:400,700);

It is from the Bootswatch Bootstrap theme I use. Is there a way to modify this one too?

**Comment by sokra** [comment]
nope. It's not on your server.

**Comment by IngwiePhoenix** [comment]
That sucks, then Ill have to carry this extra request along although I dont even use the font. Thanks anyway!

**Comment by sokra** [comment]
That's the CSSs fault...

You could write a custom loader that removes the line and apply it via config:

``` js
module.exports = function(source) {
  this.cacheable();
  return source.replace(/^.*fonts\.googleapis\.com.*$/, "");
}
```

**Comment by IngwiePhoenix** [comment]
I figured my way out of this - assigning a root path for root-relative resolves, and using a custom Bootstrap through Sassy CSS. No more extra font! :)
