### ISSUE TITLE
Sourcemap showing `null` for source path

### ISSUE THREAD

**Issue by TomasHubelbauer** [webpack/webpack#10110]
# Bug report

**What is the current behavior?**

I am using `devtool: 'source-map'` to generate source maps with my bundle and when reading the source map and attempting to find source file paths for various symbol locations, I'm getting `null` instead of the source file path.

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/TomasHubelbauer/webpack-sourcemap

**What is the expected behavior?**

Running `node repro` in the provided repro repo should print an entry for each string literal in the bundle and for the ones coming from files not in my `src` it should keep correctly displaying `webpack://…` paths, but for string literals that are generated from ones in my `src` folder, the file path of the original source file should be correctly resolved.

**Other relevant information:**
webpack version:  4.41.2 & CLI 3.3.10
Node.js version: 11.0.0
Operating System: Windows 10 Pro 10.0.18363.535
Additional tools: Nope

**Comment by sokra** [comment]
Your repro/index.js is incorrectly assuming that the output file has only a single line, which is not the case:

``` js
const map = sourceMap.originalPositionFor({ line: 1, column: node.pos });
```

Due to comments it has multiple lines

**Comment by TomasHubelbauer** [comment]
I've fixed that, thanks for pointing that out. However, the issue still persists.

**Comment by TomasHubelbauer** [comment]
Thanks, now I'm getting the correct `source` values and it helped me reproduce another issue for which I'll open a new ticket.
