### ISSUE TITLE
Using paths option from jsconfig.json / tsconfig.json instead of resolve.alias

### ISSUE THREAD

**Issue by Yegorich555** [webpack/webpack#10115]
## Feature request

Right now we can configure:
```js
// webpack.config.js
module.exports = {
  resolve: {
    alias: {
      "@": ".src/",
      images: ".src/assets/images",
      fonts: ".src/assets/fonts"
    }
  }
};

// jsconfig.json
{
  "compilerOptions": {
    "baseUrl": "./",
    "paths": {
      //for sync with aliases in webpack
      "@/*": ["src/*"],
      "images/*": ["src/assets/images/*"],
      "~images/*": ["src/assets/images/*"], //for using inside css-modules
      "fonts/*": ["src/assets/fonts/*"], 
      "~fonts/*": ["src/assets/fonts/*"] //for using inside css-modules
    },
  }
}
```
**What is the expected behavior?**
It would be fine if webpack could read **jsconfig.json/tsconfig.json** files and define default aliases according to one

**What is motivation or use case for adding/changing the behavior?**
Right now I need to configure 4 files for using alias: 
- webpack.config.js
- eslintrc.js
- jsconfig.json
- .vscode/settings.json (because ts-intellisense doesn't work with assets like images, css etc.)

I would like to avoid such overwhelmed configuration.

**How should this be implemented in your opinion?**

- Easiest way is implementation webpack-reading of js/ts-config.json files.
- The best way is figure out the single alias-configuration for eslint, vscode, webpack but I can't imagine how it possible to join these communities for working on this.

**Are you willing to work on this yourself?**
no, because I'm not familiar with wepback-inside-architecture

**Comment by evilebottnawi** [comment]
Out of scope webpack, you can create plugin for this

**Comment by evilebottnawi** [comment]
Or you can open issue about this in ts-loader/ts-plugin

**Comment by Yegorich555** [comment]
Ok. Thank you for your attention
