### ISSUE TITLE
Webpack3 to webpack4  issues

### ISSUE THREAD

**Issue by Aarthy217** [webpack/webpack#10112]
I have upgraded from webpack 3 to webpack4 and my config file are attached,
[Webpack3_Config_js.txt](https://github.com/webpack/webpack/files/3954323/Webpack3_Config_js.txt)
[Webpack4_config_js.txt](https://github.com/webpack/webpack/files/3954324/Webpack4_config_js.txt)

There were 25 chunks generated (10MB size ) using webpack 3,
but there are 111 chunks are generated(37 MB size) using webpack4.
Is there any config needs to added or remove to reduce the number and size of the config files.
Any help would be appreciated

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
