### ISSUE TITLE
Request: Adding my OJ loader to the list

### ISSUE THREAD

**Issue by IngwiePhoenix** [webpack/webpack#1012]
https://github.com/IngwiePhoenix/oj-loader

It works exactly how I want it, and it works great. Would be nice if it could be added to the listing! :)

**Comment by sokra** [comment]
If you think is stable good enough feel free to add it to the list. There is an edit button on the to top right corner.

**Comment by IngwiePhoenix** [comment]
Done! :) It's under Dialects. I have not encoutnered any issues thus far, so I suppose its considerable stable!
