### ISSUE TITLE
Sourcemap misreports the locations of string literals which are JSX children

### ISSUE THREAD

**Issue by TomasHubelbauer** [webpack/webpack#10125]
# Bug report

**What is the current behavior?**

When using the source map to resolve source locations of string literals found in the output files, the source map works correctly for normal string literals, and it works correctly for string literals which are JSX tag names, but it fails for string literals which are JSX children. Instead of resolving to a location of the string literal, it resolves to either the predecesor JSX element's tag name, if there is one, or it resolves to the parent element's tag name location.

https://github.com/TomasHubelbauer/webpack-sourcemap

Check out the result of `npm start` in this repo:

```
"div"
  source: src/App.js:5:5
  target: dist\main.js:30:4778
"App"
  source: src/App.js:5:20
  target: dist\main.js:30:4795
"h1"
  source: src/App.js:6:7
  target: dist\main.js:30:4820
"Welcome to my application!"
  source: src/App.js:6:7
  target: dist\main.js:30:4830
"This is my app!"
  source: src/App.js:5:5
  target: dist\main.js:30:4860
"strong"
  source: src/App.js:8:7
  target: dist\main.js:30:4896
"MINE."
  source: src/App.js:8:7
  target: dist\main.js:30:4910
```

- `div` is okay
- `App` is okay
- `h1` is okay
- `Welcome to my application!` points to `h1` :-(
- `This is my app.` points to `div` :-(((
- `strong` is okay
- `MINE` points to `strong` :-(

**What is the expected behavior?**

```jsx
<Element>
  String literal
  <Subelement />
  Another string literal
</Element>
```

`String literal` and `Another string literal` both resolve to their actual respective locations instead of `<Element`.

**Other relevant information:**

webpack version: 4.41.2 & CLI 3.3.10
Node.js version: 11.0.0
Operating System: Windows 10 Pro 10.0.18363.535
Additional tools: Nope

**Comment by sokra** [comment]
This seems indeed non-perfect. It also happens with raw babel so best report it there.

[SourceMap](https://sokra.github.io/source-map-visualization/#base64,InVzZSBzdHJpY3QiOwoKT2JqZWN0LmRlZmluZVByb3BlcnR5KGV4cG9ydHMsICJfX2VzTW9kdWxlIiwgewogIHZhbHVlOiB0cnVlCn0pOwpleHBvcnRzWyJkZWZhdWx0Il0gPSBBcHA7Cgp2YXIgX3JlYWN0ID0gX2ludGVyb3BSZXF1aXJlRGVmYXVsdChyZXF1aXJlKCJyZWFjdCIpKTsKCmZ1bmN0aW9uIF9pbnRlcm9wUmVxdWlyZURlZmF1bHQob2JqKSB7IHJldHVybiBvYmogJiYgb2JqLl9fZXNNb2R1bGUgPyBvYmogOiB7ICJkZWZhdWx0Ijogb2JqIH07IH0KCmZ1bmN0aW9uIEFwcCgpIHsKICByZXR1cm4gX3JlYWN0WyJkZWZhdWx0Il0uY3JlYXRlRWxlbWVudCgiZGl2IiwgewogICAgY2xhc3NOYW1lOiAiQXBwIgogIH0sIF9yZWFjdFsiZGVmYXVsdCJdLmNyZWF0ZUVsZW1lbnQoImgxIiwgbnVsbCwgIldlbGNvbWUgdG8gbXkgYXBwbGljYXRpb24hIiksICJUaGlzIGlzIG15IGFwcCEiLCBfcmVhY3RbImRlZmF1bHQiXS5jcmVhdGVFbGVtZW50KCJzdHJvbmciLCBudWxsLCAiTUlORS4iKSk7Cn0KCi8qIGJhc2U2NCBzb3VyY2UgbWFwIHJlbW92ZWQgKi8=,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIi4uL3NyYy9BcHAuanMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7OztBQUFBOzs7O0FBRWUsU0FBUyxHQUFULEdBQWU7QUFDNUIsU0FDRTtBQUFLLElBQUEsU0FBUyxFQUFDO0FBQWYsS0FDRSx5RUFERixxQkFHRSx3REFIRixDQURGO0FBT0QiLCJmaWxlIjoiQXBwLmpzIiwic291cmNlc0NvbnRlbnQiOlsiaW1wb3J0IFJlYWN0IGZyb20gJ3JlYWN0JztcclxuXHJcbmV4cG9ydCBkZWZhdWx0IGZ1bmN0aW9uIEFwcCgpIHtcclxuICByZXR1cm4gKFxyXG4gICAgPGRpdiBjbGFzc05hbWU9XCJBcHBcIj5cclxuICAgICAgPGgxPldlbGNvbWUgdG8gbXkgYXBwbGljYXRpb24hPC9oMT5cclxuICAgICAgVGhpcyBpcyBteSBhcHAhXHJcbiAgICAgIDxzdHJvbmc+TUlORS48L3N0cm9uZz5cclxuICAgIDwvZGl2PlxyXG4gIClcclxufVxyXG4iXX0=,aW1wb3J0IFJlYWN0IGZyb20gJ3JlYWN0JzsNCg0KZXhwb3J0IGRlZmF1bHQgZnVuY3Rpb24gQXBwKCkgew0KICByZXR1cm4gKA0KICAgIDxkaXYgY2xhc3NOYW1lPSJBcHAiPg0KICAgICAgPGgxPldlbGNvbWUgdG8gbXkgYXBwbGljYXRpb24hPC9oMT4NCiAgICAgIFRoaXMgaXMgbXkgYXBwIQ0KICAgICAgPHN0cm9uZz5NSU5FLjwvc3Ryb25nPg0KICAgIDwvZGl2Pg0KICApDQp9DQo=)

**Comment by TomasHubelbauer** [comment]
I attempted to reproduce this in pure Babel, but the `sourceMaps` option doesn't emit the `map` files. I checked out your source-map-visualization repo, but I don't see where it is configuring Babel's source maps, so I couldn't copy the config. I will file this with Babel, but if you could give me a pointer on how to fix my repro repo to actually reproduce the issue, I'd be very grateful, because as it stands I don't know enough about Babel to be able to reproduce this and report it:

https://github.com/TomasHubelbauer/babel-sourcemap

**Comment by sokra** [comment]
I did run `npm i @babel/cli && yarn babel src\App.js -s inline -o out\App.js` in your repo (https://github.com/TomasHubelbauer/webpack-sourcemap)

**Comment by TomasHubelbauer** [comment]
Thanks! That helped a lot. I passed the flag for generating sourcemaps through the CLI, not the config and then it worked. I opened babel/babel#10869.
