### ISSUE TITLE
[Suggestion / Feature request] webpack config composition

### ISSUE THREAD

**Issue by franleplant** [webpack/webpack#10142]
## Feature request

A way of composing several webpack configurations or chunks of configuration together 

**What is the expected behavior?**

Having a base webpack configuration that can be extended or be composed with others should be native in weback, or make this process easier by either adding config getters or finders and setters; or change the way the config is represented. 

The more problematic part is the `rules` array, if you want to customize a rule you basically need to traverse the array until you find an element that matches one search criteria (such as `loader.includes('file-loader')`). I've also seen in some boilerplates something like this `rules[someIndex].options.newOption = newValue` which is a rather brittle way of writing code.

I know there are things such as `webpack-merge` but they dont always work as expected (think when some deep config value is the result of running a function, and I've seen that lots of libraries (see below) just inspect the config object manually and tweak it to compose or modify it.

Also, different frameworks and libraries provide some sort of "plugin" interface. These plugins should not be confused with Webpack plugins, these libraries call plugins to hooks that they provide to customize the default webpack configuration that they abstract over.

**What is motivation or use case for adding/changing the behavior?**

Currently there are lots of libraries and frameworks that try to abstract over the webpack configuration but they require to provide some sort of escape hatch so that the users of said library or framework can customize the default abstracted configuration.
Examples of this are `razzle.js`, `next.js`, `create-react-app` and probably many others (note how these as pretty big names).

This should be proof that people are re-inventing this wheel over and over and that is something that is useful and needed.

I believe that webpack should recognize that it is a tool that should be abstracted other for most application developers and that abstractions with common configurations are desirable.

Think of an interface like this

```javascript
createWebpackConfig(
  useJSX(),
  useSASS(),
  useTypescript(),
  progressiveImages(), 
)
```

**How should this be implemented in your opinion?**

As I said before, lets analyse the most often operations that webpack config compositions might perform
- add new rules (loaders): usually done by `rules.push(newRule)`
- customize existing rules: this is the most problematic one because there is no easy or standard way of finding a rule by some id and tweaking it. It is further problematic when some value in that rule comes from running a function such as `nodeExternals`
- add new plugins: usually done by `rules.push(newRule)`

The potential solutions I can think of are
- providing a standard API for getters and setters of rules (we will probably need to add some sort of id to the rule for a more deterministic behavior)
- providing some sort of composition primitive like middlewares, inheritance. This will require further work to make composition a first class citizen.
- providing composition APIs such as `applyConfigChunk(configChunk)` and having official smart merging strategies (but im not sure how they will handle all of the problems described above). It will probably require that the underlying config object should be _flatter_ for easier composition.

EDIT: expanding on the first option since it looks like the least involved
if the config schema could be modified to allow rule ids then we might get to do something like this

```javascript
getRuleById(config, "javascript-rules") // => the entire rule object that you customize
```

and the original rule would look like this

```javascript
{
   module: {
    rules: [{
      id: "javascript-rules",
      test: /*\.jsx?/,
      loader: {loaders}
    }]
  }
}
```

I guess that something similar could be applied to loader arrays

**Are you willing to work on this yourself?**
Maybe, this might be above my capabilities but with the proper guidance I can definitively help

**Comment by sokra** [comment]
webpack itself intentionally does not provide an API for that, but leaves that to userland solutions. The config file is a JavaScript file and you can use any helper you like. e. g. webpack-merge is one, if you don't like it, fork it or write your own solution.

In general there are multiple ways how to compose configs. There are personal preferences and I don't think there is one right way. Here are some examples:

* Merging configs: Take multiple config object and merge them together in a smart way
* Modifying configs: Have base config and extending is done by executing modifying operations on this config
* Compositing configs: Have config snippets in sub-files and put them together for a final config
* Immutable updating: Extending happens in a way that copies the original config while updating values (`{ ...baseConfig, plugins: [ ...baseConfg.plugins, extraPlugin ]}`)
