### ISSUE TITLE
Logging API: as plugin developer i need to delete plugin name from every message  

### ISSUE THREAD

**Issue by Amaimersion** [webpack/webpack#10148]
## Allow plugin developers to control plugin name in messages

**What is the expected behavior?**

Using `compilation.getLogger('PluginName)` and `compiler.getInfrastructureLogger('PluginName')` i want to control how `PluginName` appears in log messages. In particaular, i don't want `PluginName` to appear in **every** message.

Current behavior is:
![1](https://user-images.githubusercontent.com/20613502/71123724-56c96f00-21f4-11ea-8f97-0ef9466f84a5.jpg)

As you can see, there is `[remove-files-plugin@1.1.4]` in every message, but i need this only in first message.
 
**What is motivation or use case for adding/changing the behavior?**

Pretty and clear logs.

**How should this be implemented in your opinion?**

As an object with options:
```javascript
compiler.getInfrastructureLogger('PluginName', {
    pluginNameInMessage: 'first' // or 'every'
});
```

**Are you willing to work on this yourself?**
no

**Comment by sokra** [comment]
You should not use the intrastructure logger for this plugin.

Use the normal logger with `compilation.getLogger('PluginName)`. It only displays your logger name once as header.

**Comment by Amaimersion** [comment]
>Use the normal logger
It is only available for `compilation`, not `compiler`. I need to use for both `compiler` and `compilation`.

**Comment by evilebottnawi** [comment]
игьз

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/webpack/webpack/issues/10148
