### ISSUE TITLE
RegExp in config not being parsed properly.

### ISSUE THREAD

**Issue by kirkcola** [webpack/webpack#10143]
# Bug report

**What is the current behavior?**
  
Hi, I was trying to handle all scss file named `*.global.scss` or `global.scss` by certain loaders,
so I write a regular expression like this:
```js
{
  test: /^(.*\.)?global\.scss$/,
  use: [
   //...
  ]
}
```
I didn't sense anything strange about this expression, but it failed when handling file `global.scss`, and throw an error:
```
You may need an appropriate loader to handle this file type ...
```
While:
- This expression was tested both on Chrome 79 DevTools and Node 10 (by calling `/..../.test("global.scss")`), and all returned `true`.
- If I simply change the test rule to `/global\.scss$/`, nothing goes wrong.

Finally I chose to split the expression into an array. 
```js
{
  test: [/\.global\.scss$/, /^global.scss$/],
  use: [
   //...
  ]
}
```
It works fine. I don't know if it's actually a bug, but since everything is drived by node (naturally), It's strange the same regular expression shows different behaviors on node and webpack.

**If the current behavior is a bug, please provide the steps to reproduce.**
See the code above.

**What is the expected behavior?**
The regular expression being parsed properly.

**Other relevant information:**
webpack version:  4.41
Node.js version:  10.17
Operating System:  macOS 10.15
Additional tools: Chrome 79

**Comment by evilebottnawi** [comment]
We don't touch your regexps, don't use `^`

**Comment by sokra** [comment]
It's matching with the absolute path of the file, so go with `/[.\\/]global\.scss$/`

**Comment by kirkcola** [comment]
@sokra It works, thank you! 😄
