### ISSUE TITLE
split-chunks-plugin: filename in cacheGroup param considered invalid during schema validation

### ISSUE THREAD

**Issue by asos-albinotonnina** [webpack/webpack#10159]
# Bug report

**What is the current behavior?**

[Docs](https://webpack.js.org/plugins/split-chunks-plugin/#splitchunkscachegroupscachegroupfilename) mention filename param can be a function, but I get schema validation error like this:

![image](https://user-images.githubusercontent.com/42975051/71278063-75437d80-234e-11ea-8a5c-351e7a281b00.png)

If I change [schemas/WebpackOptions.json](https://github.com/vankop/webpack/blob/27d7d0acedcbce3b8099f9c4e21dff93c177a35b/schemas/WebpackOptions.json#L615-L618) for the filename attr to accept a function it does actually work.
Is it just a matter of updating the json file? I'm certainly capable of opening a pr for this.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

configuration.optimization.splitChunks.cacheGroups['shared'].filename could be a function.

**Other relevant information:**
webpack version:  4.41.4
Node.js version: 10.15.3
Operating System: osx 10.15.1
Additional tools:

**Comment by shashwataggarwal** [comment]
How can I get started to contribute to webpack?

**Comment by asos-albinotonnina** [comment]
https://github.com/webpack/webpack/pull/10164#issuecomment-568181385

**Comment by asos-albinotonnina** [comment]
As a possible workaround, until you are on version 4 I guess you can do something like this:

```javascript
  plugins: [
    new webpack.optimize.SplitChunksPlugin({
      cacheGroups: {
        shared: {
          name: module => ...,
          filename: chunkData => yay!
        }
      }
    })
  ]
```
