### ISSUE TITLE
Asking for one module from a file containing multiple named amd modules

### ISSUE THREAD

**Issue by leandro95** [webpack/webpack#10150]
Hello,

I have a legacy file that contains **70 amd define** (yes i know 😆). I wanted to be able to request any modules in that file from another file. Currently only the last amd define in the file is considered as the module result, the previous ones are considered as local modules.

Supposed I have a file namedModule.js contained:
```javascript
define('named1', [], function() {
  return 'named1';
});

define('named2', [], function() {
  return 'named2';
});

define('named3', [], function() {
  return 'named3';
});

define('named4', ['named1', 'named2'], function(named1, named2) {
  return 'named4';
});
```
 And I asked for the module named 1 in my index.js:
```javascript
import named1 from 'namedModule.js';
console.log(named1); // suppose to return 'named1'
```
I'm expected 'named1' as result.
How can i achieve that ?

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
