### ISSUE TITLE
HMR not cleaning my DOM when injecting elements

### ISSUE THREAD

**Issue by bragjo** [webpack/webpack#10160]
Hi,

I have some troubles getting Hot Module Replacement to work properly. At the moment I'm just using vanilla javascript to practice and also using webpack-dev-server with the following settings in my config:

```
'use strict';

const path = require('path');
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const { CleanWebpackPlugin } = require('clean-webpack-plugin');

module.exports = {
    entry: {
        main: path.resolve('src/main.js')
    },
    mode: 'development',
    output: {
        filename: '[name]-bundle.js',
        path: path.resolve('dist'),
        publicPath: '/'
    },
    devServer: {
        contentBase: path.resolve('dist'),
        watchContentBase: true,
        overlay: true,
        hot: true
    },
    module: {
        rules: [
            {
                test: /\.js$/,
                use: ['babel-loader'],
                exclude: /node_modules/
            },
            {
                test: /\.html$/,
                use: ['html-loader']
            },
            {
                test: /\.css$/,
                use: ['style-loader', 'css-loader']
                }
            ]
    },
    plugins: [
        new HtmlWebpackPlugin({
            template: path.resolve('src/index.html')
        }),
        new webpack.HotModuleReplacementPlugin(),
        new CleanWebpackPlugin()
    ]
}
```

in my main.js file (which is my entry):

```
require(./style.css);
require(./app.js);

if (module.hot) {
    module.hot.accept();
}
```

in my app.js:

```
'use strict';

const body = document.body;
const div = document.createElement('div');
div.className = 'testing';

body.appendChild(div);
```

as you see nothing special, really simple..

How do I get HMR to also clean the DOM from elements created in my app.js automatically on save?
I have to manually reload the page to be able to clear the DOM. So with other words: removing the code in my app.js complete is not removing the elements from the DOM, only way for it to apply is to manually reload the browser.

Thanks.

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
