### ISSUE TITLE
Static properties on classes break tree shaking

### ISSUE THREAD

**Issue by maximilianMairinger** [webpack/webpack#10165]
# Bug report

**What is the current behavior?**

Static properties on classes break tree shaking (using ts)

`file: tree.ts`
```ts
export class BBB {
  public name = "BBB"
  public static staticProp = "BBB"
  constructor(public inner: any) {}
}


export class AAA {
  public name = "AAA"
  constructor(public inner: any) {}
}
```

`file test.ts`
```ts
import { AAA } from "./tree"

console.log(new AAA(""))
```

BBB gets ends up in the production bundle. I assume this is because ts resolves the static attribute to:

```js
export class BBB {
  constructor(inner) {
    this.name = "BBB"
    this.inner = inner
  }
}
BBB.staticProp = "BBB"
```

And the last line `BBB.staticProp = "BBB"` gets interpreted as side effect, thus disabeling the tree shakableness of BBB.

**If the current behavior is a bug, please provide the steps to reproduce.**

Clone example [repo](https://github.com/maximilianMairinger/test-tree-shaking) or:

Create a project with the files and content shown above.

Simple tsconfig with: `mode: "production"` and `ts-loader@^6.2.1`.

When deleting the line ´public static staticProp = "BBB"´ in `tree.ts`, BBB gets tree shaked as expected. 

**What is the expected behavior?**

BBB should be tree shakeable even with a static property.

**Other relevant information:**
webpack version: 4.41.4
Node.js version: v12.12.0
Operating System: Winows
Additional tools: "ts-loader": "^6.2.1"

**Comment by sokra** [comment]
Tree Shaking works, but Dead Code Elimination doesn't remove that code.
