### ISSUE TITLE
Working with django and react application with webpack-dev-server (Hot-reloading). I am getting this error in console. But my page is loading fine

### ISSUE THREAD

**Issue by kamalims62** [webpack/webpack#10167]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

https://stackoverflow.com/questions/59441494/working-with-django-and-react-application-with-webpack-dev-server-hot-reloading

Issue in the above link .

**Comment by evilebottnawi** [comment]
Please fill issue template, be patient wait answer
