### ISSUE TITLE
Safari will not paint the DOM untill all css chunks are loaded

### ISSUE THREAD

**Issue by hkhere** [webpack/webpack#10178]
# Bug report

**What is the current behavior?**
I assume webpack loads asynchronous chunks by adding  script and link tags in the head tag. 

It seems that safari will not paint the dom untill all the async css chunks are loaded. 

I have a simple web application that will show a simple loading component before the actual page is loaded. I use webpack dynamic import and lazy loading to achieve this . It works well on Chrome and Firefox. They all correctly show the loading component before the actual page is completely loaded. But on Safari it will show a blank page  until all async css chunks are loaded. 

I have done a test intentionally to verify this. I slowed down the requests of some async css chunks and inspected the elements on safari devtools. The dom of loading component was already loaded but the screen was blank.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
The content of the loading component should appear on safari when the actual page is loading.

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

**Comment by sokra** [comment]
Have you tried to wait until the `load` event before requesting more chunks?

**Comment by hkhere** [comment]
> Have you tried to wait until the `load` event before requesting more chunks

It is the task of webpack to request more async chunks at appropriate time. Currently I have no time to look into how webpack does this.  From my inspection on devtools, I think it loads async chunks by dynamically adding tags in the head tag, But I don’t know at what phase it will add the tags.

**Comment by hkhere** [comment]
> Have you tried to wait until the `load` event before requesting more chunks?

I did not request async chunks manually. I use code splitting and dynamic import feature of webpack.

**Comment by hkhere** [comment]
I think it is more a problem of Safari?  Because other browsers does this right.

**Comment by hkhere** [comment]
Other browsers like Chrome and Firefox do this right. I don’t know if this is more a problem of Safari. The problem is obvious when you have relative large async css chunks and your network is slow.

**Comment by evilebottnawi** [comment]
@hkhere can you provide Safari version and minimum reproducible test repo?

**Comment by sokra** [comment]
> I use webpack dynamic import and lazy loading to achieve this

> I did not request async chunks manually

That's a bit confusing. Yes, please 

> can you provide Safari version and minimum reproducible test repo?

**Comment by hkhere** [comment]
@sokra @evilebottnawi Here is the minimum reproducible test repo [webpack-issue-10178](https://github.com/hkhere/webpack-issue-10178)

**Comment by hkhere** [comment]
> > I use webpack dynamic import and lazy loading to achieve this
> 
> > I did not request async chunks manually
> 
> That's a bit confusing. Yes, please
> 
> > can you provide Safari version and minimum reproducible test repo?

I mean other than dynamic import. I did not manually request async chunks

**Comment by hkhere** [comment]
@sokra @evilebottnawi  Sorry for the confusion. I did not understand lazy loading and code splitting correctly. It is not the problem of webpack but my code.
