### ISSUE TITLE
webpack generates invalid token 'with' by requiring the core-js polyfill es.string.ends-with

### ISSUE THREAD

**Issue by fancy-rabbit** [webpack/webpack#10172]
# Bug report

**What is the current behavior?**
We use webpack (with babel-loader to transform all our modules in to CommonJS ones) to make our frontend bundles. the core-js(previously @babel/polyfill) library is treated as a webpack ``externals`` whose global name is __CoreJS.

if the ``mode`` of webpack is set to ``production`` or ``none``, the following code
```js
require('core-js/modules/es.string.ends-with');
```
is transformed to something like
```js
/* 237 */
/***/ (function(module, exports) {

module.exports = __CoreJS.modules.es.string.ends-with;

/***/ }),
```
which will be ``__webpack_require__()`` -ed. but this ``.ends-with`` breaks terser-webpack-plugin with

> Unexpected token: keyword (with)

moreover, when ``mode`` is set to ``development``, the generated code is like
```js
eval("module.exports = __CoreJS.modules.es.string.ends-with;\n//#sourceMappingURL=data:application/json;charset=utf-8;base64,*****\n//#sourceURL=webpack-internal:///core-js/modules/es.string.ends-with\n");
```
which doesn't breaks terser..(by wrapping it with ``eval``, but I'm wondering whether it will break something else)

**If the current behavior is a bug, please provide the steps to reproduce.**
If it is needed, I'll make one minimal reproducible repo when I have time^_^

**What is the expected behavior?**
it should not generate the invalid token 'with'.

**Other relevant information:**
webpack version:  4.41.4
Node.js version: 12.13.0
Operating System: CentOS 7
Additional tools: babel-loader 8.0.6, @babel/core 7.7.7, core-js 3.6.0
https://github.com/babel/babel/issues/10908

**Comment by nicolo-ribaudo** [comment]
I think that sharing your webpack config (at least `externals`) might help

**Comment by fancy-rabbit** [comment]
@nicolo-ribaudo oops, you mentioned me .... looking deeper into the module which generate the externals, I found the snippet
```js
        function (context, request, callback) {
            // external for submodules, 'module/*' => __module.xxx
            const libKeys = Object.keys(externalLibs);
            const key = libKeys.find(item => new RegExp(`^${item}(\\/.+)?$`).test(request));
            if (!key) {
                callback();
                return;
            }
            return callback(null, 'root ' + externalLibs[key] + request.slice(key.length).replace(/\//g, '.'));
        }
```

which made the conversion. so it looks like our fault.
thanks very much.

**Comment by nicolo-ribaudo** [comment]
The safest transformation is `a/b/c` -> `a["b"]["c"]`. You could then optimize it in case the path segment matches `/^[a-z$_]\w*$/i`.

**Comment by fancy-rabbit** [comment]
@nicolo-ribaudo thanks very much. I modified the code snippet to something like

```js
            let converted;
            if (/^(?:\/[a-z$_]\w*)+$/i.test(request.slice(key.length))) {
                converted = request.slice(key.length).replace(/\//g, '.');
            } else {
                const submodules = request.slice(key.length).split('/').slice(1);
                converted = '["' + submodules.join('"]["') + '"]';

            }
            return callback(null, 'root ' + externalLibs[key] + converted);
```
and it works well without any problems both with babel and webpack.
apologize for any misleading~
