### ISSUE TITLE
Export "to" directory

### ISSUE THREAD

**Issue by fenyagg** [webpack/webpack#10187]
## Feature request

**What is the expected behavior?**

I can do export to the current directory only without the possibility of global import.

**What is motivation or use case for adding/changing the behavior?**
Sometimes i need to create small modules which needed only in current directory. This will speed up the ide to find only the right modules. And we will be able to call modules with the same names in the current directory without confusion.

**How should this be implemented in your opinion?**

I suggest adding the specifically word "to".
E.g.:
- I export some var in path `/module/helpers.js`:
 ```
const helpres = {};
export helpres to "./";
```
- In `/module/module.js` i can import this one:

 ```
import helpres from "./helpers"; // got success
```

- in base directory ("/") i can't find this one:

```
import `helpres` from "./module/helpres"; // error someVar not found
```

**Are you willing to work on this yourself?**
unfortunately not

**Comment by evilebottnawi** [comment]
It is not standard js syntax so it it out of scope webpack

**Comment by sokra** [comment]
There is the `exports` field in package.json feature (experimental and not implemented in webpack yet) which can be used to restrict access to internal modules.

https://nodejs.org/docs/latest-v13.x/api/esm.html#esm_package_exports
