### ISSUE TITLE
chunkhash is unreliable

### ISSUE THREAD

**Issue by dimsmol** [webpack/webpack#1018]
I've got a number of cases when chunkhash suddenly gets changed even though output file stays the same and, what is worse, when chunkhash doesn't change when file contents changes dramatically.

Inconsistent "consistent hashing" is a nightmare when you're dealing with CDN, because once you got a problem, you got it on the huge number of servers and cannot fix it easily.

I'm sure we can hunt hashing bugs one by one and somewhen get them all fixed, but at any moment we cannot be sure there aren't some of them still waiting for a tricky combination of options to break everything down again. And of course we will get new bugs introduced by new options, loaders and so on.

So, in the meantime I'm forced to instrument deployment with tricky double-checking code (that can be buggy itself) just to prevent breaking things on CDN. This is very unpleasant and it looks like we need more reliable hashes.

Why cannot it be just hash of the final output content?

This approach prevents cyclic dependencies (but they are a bad practice anyway) and this will also force possible build order to be bottom-up through dependency tree.
But at least it will be much more robust and reliable, and this is what I (and I guess all the CDN users) really need badly.

What do you think?

**Comment by sokra** [comment]
Do you have an example for two files with the same hash but different content=

**Comment by dimsmol** [comment]
Yes, I have such examples at least for the following two cases:

* The files generated with and without `UglifyJsPlugin` have very different content, but are getting exactly same hashes
* When I'm changing `output.publicPath` the hash remains the same even for file containing urls that have been changed

Unfortunately they're a part of a big project, so it will take some time to extract a minimal example showing the problems.

Can you describe in short how this hash magic does currently work, please?
It would be nice to understand what else can probably introduce new hash-related problems.

PS According to problem when hashes are being changed on the same content.
I have an example when some files are getting new hashes but the only change in content is a source map url which contains the file name with a hash itself. It's a tricky case because for some files hash doesn't change (so file name doesn't change, source map url doesn't change and content doesn't change at all) but for some the problem exists and I didn't figure out yet what's the difference between the good and the bad cases.

**Comment by hankhsiao** [comment]
I encountered the same issue. Content is the same, but the chunk ids change. In this case, the file should be different, because the previous version with old chunk id is already in CDN.

Example config:
```js
output: {
    ...
    filename: '[name].[chunkhash].min.js',
    chunkFilename: '[name].[chunkhash].min.js'
},
plugins: [
    new webpack.optimize.DedupePlugin(),
    new webpack.optimize.CommonsChunkPlugin({
        name: 'common',
        filename: 'common.[hash].min.js',
        minChunks: 2
    }),
    new webpack.optimize.UglifyJsPlugin({
        compress: {
            warnings: false
        }
    })
]
```

The example that the same name but different chunk ids.
```
diff js1/tdv2-applet-video-modal.4f2b97c1cd8bbdcbe4be.min.js js2/tdv2-applet-video-modal.4f2b97c1cd8bbdcbe4be.min.js
2855c2855
< 780,
—
> 779,
2858c2858
< 781
—
> 780
```

**Comment by sokra** [comment]
Maybe 780 and 781 are identical modules and in the first case code of 780 is included and 781 references the code of 780 and in the second case code of 781 is included and 780 references that code. I would like to see more of the context of the diff.

If I'm right, the scripts are functional identical. This means the hash is correct, but the DedupePlugin is not deterministic with the order of deduplication.

**Comment by hankhsiao** [comment]
Correct, but that causes the problem, because main.js and common.js do change and upload to CDN, but that file is not due to the same filename. So JS will fail if main.js invokes 780 (was 781 in CDN).

Should chunkhash be generated after all process?

**Comment by hankhsiao** [comment]
@sokra don't you think that is a problem? What kind of evidence you want to see?

**Comment by sokra** [comment]
It would be great if you can create a repro case for the problem. I can only guess from the diff you gave me.

**Comment by hankhsiao** [comment]
OK, thank you for your quick response. I will try if I can get a solid example.

**Comment by XVincentX** [comment]
@sokra Has this change been *backported* to current webpack? As of now I see that part of 2.beta!
