### ISSUE TITLE
Webpack 4 Incorrectly Rendering `select` Element Options

### ISSUE THREAD

**Issue by philsinatra** [webpack/webpack#10195]
# Bug report

**What is the current behavior?**

Simple HTML `select` element is not being rendered properly. The `option` elements that are coded within the `select` are being rendered outside of the `select` element in the final output HTML file. 

**If the current behavior is a bug, please provide the steps to reproduce.**

```html
<select name="language" id="language">
  <optgroup label="Select Language">
    <option value="all" selected>All Languages</option>
    <option value="german" lang="de">Englisch Deutsch</option>
    <option value="french" lang="fr">Anglais français</option>
    <option value="italian" lang="it">Inglese e italiano</option>
    <option value="spanish" lang="es">Ingles Espa&#241;ol</option>
    <option value="english" lang="en">English Only</option>
  </optgroup>
</select>
```

![Screen Shot 2019-12-30 at 12 50 01 PM](https://user-images.githubusercontent.com/1465808/71594911-b7677e80-2b07-11ea-9bf1-d8dafee99750.png)

**What is the expected behavior?**

The `option` elements should remain as nested children to the `select`. I can not post my full repository.

**Other relevant information:**
webpack version:  

- `"webpack": "^4.41.3",`
- `"webpack-cli": "^3.3.10",`
- `"webpack-dev-server": "^3.10.0",`

Node.js version: 10.17.0  && 12.13.1
Operating System: macOS 10.15.2
Additional tools: 

- `"@babel/core": "^7.7.5",`
- `"@babel/plugin-transform-modules-commonjs": "^7.7.5",`
- `"@babel/preset-env": "^7.7.6",`

**Comment by sokra** [comment]
Not related to webpack.
