### ISSUE TITLE
Webpack 4, Output config, contenthash placeholder 

### ISSUE THREAD

**Issue by ameyzulkanthiwar** [webpack/webpack#10197]
### Placeholder config
I just started learning webpack and I come across one issue. I am using the [contenthash] placeholder and now I want to import the generated file in HTML script tag but because it contains the hash value I am confused how to mention that in the src tag of script element in HTML

```
module.exports = {

    mode: 'development',
    entry: {
        myfile :'./src/index.js'
    },
    output: {
      path: path.resolve(__dirname, 'dist'),
      filename:'js/[name].[contenthash].js',  //<<---
      publicPath: '/assets/',
   },
   devServer:{
       port: 1234,
       contentBase: path.join(__dirname, 'dist')
   }
}
```

# HTML file 
```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="X-UA-Compatible" content="ie=edge">
        <title>My firest Page</title>
    </head>
    <body>
        <h1>HTML Header</h1>       
        <script src='/assets/js/myfile.js'></script>
    </body>
</html>
```

I can make this thing work with the help of only [name] placeholder but I want to know how to use the [contenthash] placeholder.

File Name I want to use in src attribute "myfile.72573269809e6f221a8a.js"

```
<script src='/assets/js/myfile.72573269809e6f221a8a.js'></script>
```
### NOTE: I do not want to hard code the file name when ever I run buld command

Thank you for helping me.

**Comment by sokra** [comment]
Either use the webpack stats json data to generate the html yourself

or use one of the plugin to generate a HTML file, e. g. html-webpack-plugin
