### ISSUE TITLE
Module not found: Error: Can't resolve 'fs'

### ISSUE THREAD

**Issue by reZach** [webpack/webpack#10199]
# Bug report

**What is the current behavior?**
The current behavior is that webpack is not able to resolve the module `fs` and causes webpack to fail bundling. This webpack [target](https://webpack.js.org/configuration/target/) is set to **electron-renderer** due to this target being the only viable option in order to implement [Electron best security practices](https://electronjs.org/docs/tutorial/security). The usual solution to this problem is to set the webpack target to `node`, although attempting this still causes the error. 

_Note. I've tried countless SO posts and solutions and I am coming here as a last-resort, I've tried to do my research but do not know what may be the issue._

**If the current behavior is a bug, please provide the steps to reproduce.**
The easiest steps to reproduce is to run this boilerplate repo (I will include some related files of interest as well below). 
```
git clone https://github.com/reZach/electron-webpack-template.git
cd electron-webpack-template
npm i
npm run build-prod-webpack
```

The related-error when running the above commands is:
✖ ｢wdm｣:
ERROR in ./node_modules/electron/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/[me]/Projects/electron-w
ebpack-template/node_modules/electron'
 @ ./node_modules/electron/index.js 1:9-22
 @ ./app/main.js

If you, or cannot run the test git repo (which is preferable), you may look at my webpack configs and package.json (although again I would suggest running the git repo as it's easier to replicate).

**webpack.config**
```
const HtmlWebpackPlugin = require("html-webpack-plugin");
const CspHtmlWebpackPlugin = require("csp-html-webpack-plugin");

module.exports = (env, argv) => {

    return {
        target: "electron-renderer", // Allows us to use webpack without setting nodeIntegration to true in the BrowserWindow (Electron) object; https://webpack.js.org/configuration/target/
        module: {
            rules: [{
                test: /\.jsx?$/,
                include: /app/,
                resolve: {
                    extensions: [".js", ".jsx", ".json"]
                },
                use: {
                    loader: "babel-loader",
                    options: {
                        cacheDirectory: true
                    }
                }
            }]
        },
        plugins: [
            new HtmlWebpackPlugin({
                template: "./app/index.html",
                filename: "./index.html",
                excludeChunks: ["electron-main"]
            }),
            // https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy
            new CspHtmlWebpackPlugin({
                "base-uri": ["'self'"],
                "object-src": ["'none'"],
                "script-src": ["'self'"],
                "style-src": ["'self'"],
                "frame-src": ["'none'"],
                "worker-src": ["'none'"]
            })
        ]
    };
}
```

**webpack.production.config**
```
const merge = require("webpack-merge");
const base = require("./webpack.config");
const path = require("path");

module.exports = merge(base, {
    mode: "production",
    devtool: "nosources-source-map", //https://webpack.js.org/configuration/devtool/ && https://github.com/webpack/webpack/issues/5627#issuecomment-389492939
    entry: {
        "electron-main": "./app/main.js",
        "app": "./app/index.js"
    },
    output: {
        filename: "[name]-bundled.js", // Names the bundled files
        path: path.resolve(__dirname, "../../", "dist") // Path of the bundled files
    }
});
```

**package.json**
```
{
  "name": "electron-webpack-template",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "dev": "npm run build-dev-webpack && npm run start-dev-app",
    "build-dev-webpack": "webpack-dev-server --mode development --config ./app/configs/webpack/webpack.development.js",
    "start-dev-app": "cross-env HOT=1 NODE_ENV=development electron app/main.js",
    "prod": "npm run build-prod-webpack && npm run start-prod-app",
    "build-prod-webpack": "webpack --mode production --config ./app/configs/webpack/webpack.production.js",
    "start-prod-app": "cross-env NODE_ENV=production electron app/main.js"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/reZach/electron-webpack-template.git"
  },
  "keywords": [],
  "author": "",
  "license": "GPL-3.0-only",
  "bugs": {
    "url": "https://github.com/reZach/electron-webpack-template/issues"
  },
  "homepage": "https://github.com/reZach/electron-webpack-template#readme",
  "devDependencies": {
    "@babel/core": "^7.7.7",
    "@babel/plugin-proposal-json-strings": "^7.7.4",
    "@babel/plugin-transform-react-jsx": "^7.7.7",
    "@babel/preset-env": "^7.7.7",
    "@babel/preset-react": "^7.7.4",
    "@hot-loader/react-dom": "^16.11.0",
    "babel-loader": "^8.0.6",
    "babel-polyfill": "^6.26.0",
    "cross-env": "^6.0.3",
    "csp-html-webpack-plugin": "^3.0.4",
    "devtron": "^1.4.0",
    "electron": "^7.1.7",
    "html-webpack-plugin": "^3.2.0",
    "lockfile-lint": "^3.0.5",
    "react-hot-loader": "^4.12.18",
    "webpack": "^4.41.4",
    "webpack-cli": "^3.3.10",
    "webpack-dev-server": "^3.10.1",
    "webpack-merge": "^4.2.2"
  },
  "dependencies": {
    "@reduxjs/toolkit": "^1.2.1",
    "connected-react-router": "^6.6.1",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-redux": "^7.1.3",
    "react-router": "^5.1.2",
    "react-router-dom": "^5.1.2",
    "redux": "^4.0.5"
  }
}
```

**What is the expected behavior?**
The command to bundle all application files should succeed and not throw any error.

**Other relevant information:**
webpack version: 4.41.4
Node.js version: 8.11.1
Operating System: macOS High Sierra 10.13.6

**Comment by sokra** [comment]
Since you don't have access to `fs` in the renderer process without nodeIntegration (best practices), this is also not available in webpack.

Any scripts needing node integration should be done in a preload script using `electron-preload` target, with allows to use node integration.

Also in the electron main process (target `electron-main`) there is node integration available.

**Comment by reZach** [comment]
> 
> 
> Since you don't have access to `fs` in the renderer process without nodeIntegration (best practices), this is also not available in webpack.
> 
> Any scripts needing node integration should be done in a preload script using `electron-preload` target, with allows to use node integration.
> 
> Also in the electron main process (target `electron-main`) there is node integration available.

Thank you for your reply, and happy new years as well!

Is there not a way in webpack to have access to node modules (`fs`) following these best-practices? I was hoping there would be some way. I _am_ familiar with the preload script but do not know of an equivalent to put the modules necessary into webpack. 

If there isn't one, I will leave it as that and take this to the electron team. I don't want to continue to try if we know for certain this won't work/is supported.

Again - thank you for commenting!

**Comment by sokra** [comment]
> Is there not a way in webpack to have access to node modules (`fs`) following these best-practices?

The best practices don't allow to access `fs` in a renderer script.

You could configure webpack to allow to access `fs` with `externals: { fs: "commonjs fs" }` but if you are really following the best practices you have node integration disabled for renderer scripts and this won't work.

**Comment by reZach** [comment]
Thank you for your input @sokra, I've come to understand that to integrate webpack with Electron, you cannot bundle your application files in your renderer process as you've described above. The best approach may be as you describe (I could not get it to work), but to create a local application with webpack, and then have electron load the local webapp as described as [path 3 in this article](https://slack.engineering/interops-labyrinth-sharing-code-between-web-electron-apps-f9474d62eccc).
![image](https://user-images.githubusercontent.com/4740370/71866917-9c7ba800-30cd-11ea-831f-a72fdd2c55ea.png)

I've created [secure-electron-template](https://github.com/reZach/secure-electron-template) as a template following this idea and with the goal of securing apps built with webpack and electron. Thank you for pointing me in the right direction.

**Comment by ChenYCL** [comment]
same issues
 error  in ./node_modules/react-docgen-typescript/lib/parser.js

Module not found: Error: Can't resolve 'fs'

**Comment by Bosch-Eli-Black** [comment]
For anyone else who runs across this, check out https://github.com/electron/electron/issues/21437#issuecomment-573522360, which has an example of how to do this properly 🙂
