### ISSUE TITLE
Error `Uncaught TypeError: util.inherits is not a function`

### ISSUE THREAD

**Issue by matthewgertner** [webpack/webpack#1019]
I want to use `console.log` in my script, so I added `node: { console: true }` to my configuration. Now when I try to load the script, it reports `Uncaught TypeError: util.inherits is not a function`. The error is occuring in the Webpack version of `assert.js` at the line:

```util.inherits(assert.AssertionError, Error);```

I nosed around a bit, and it seems that that file is being parsed twice (if I put a log statement at the top of the file, it is written to the console twice). The first time, the `util` object is correct and has an `inherits` property that is a function. The second time, `util` is still an object but it has no properties.

Does anyone have an idea what might be going on here? If not, I will try to put together a simple reproducible use case.

**Comment by sokra** [comment]
Maybe a circular dependency between `util` and `asset`.

**Comment by matthewgertner** [comment]
Would be plausible although from what I can see, `util` doesn't require any other modules.

In any case it seems to be easy to reproduce this. Just require https://www.npmjs.com/package/request-promise and you'll get the error. The `node` section of my webpack config looks like this:

```
  node: {
    fs: 'empty',
    net: 'empty',
    tls: 'empty',
    console: true
  }
```

**Comment by jhnns** [comment]
Could you set up a simple gist that demonstrates the error?

**Comment by matthewgertner** [comment]
Literally just this one line does it for me:

```require('request-promise');```

Config as follows:

```
module.exports = {
  "output": {
    "filename": "test.js"
  },
  module: {
    loaders: [
      { test: /\.json$/, loader: 'json-loader' }
    ]
  },
  "node": {
    "fs": "empty",
    "net": "empty",
    "tls": "empty",
    "console": true
  }
}
```

I just webpacked that one line and tried to load it from an HTML page. This yields the error I reported.

**Comment by jhnns** [comment]
Yep, it's a circular dependency. `util` uses `console.log()` which triggers webpack to include `console-browserify` which requires `assert` which requires `util` → voilà :)

I currently don't know how to fix this, but a quickfix could be just to not use the `node: { console: true }`? The `console` object is present in all major browsers.

**Comment by matthewgertner** [comment]
The problem is with https://github.com/janl/node-jsonpointer. There is an explicit `require("console")` in their code that fails unless I include your `console` stub. As far as I can it isn't needed, so I filed an issue with them to see if they would be willing to remove it.

**Comment by matthewgertner** [comment]
For now I worked around the problem by creating an empty stub module called `console` and installing it using a `package.json` local path dependency. That way I don't have to use `node: { console: true }` and `node-jsonpointer` uses my stub package.

**Comment by benjie** [comment]
(Sorry to pollute the thread; in case anyone else hits this whilst suffering from similar issues, for me it turned out to be requiring `superagent` without using webpack workarounds; see [here](https://github.com/felixge/node-formidable/issues/337#issuecomment-264337905) and [here](https://github.com/visionmedia/superagent/wiki/SuperAgent-for-Webpack))

**Comment by crisys11** [comment]
npm i --save util@0.10.0 works for me

**Comment by langri-sha** [comment]
This is seriously annoying :hurtrealbad:. I did this in the end, because the `node-util` probably won't ever get updated again:

```
npm i browser-assert
```

Then in your config, monkeypatch `node-libs-browser`:

```
const nodeLibsBrowser = require('node-libs-browser')
nodeLibsBrowser.assert = require.resolve('browser-assert')
nodeLibsBrowser.util = require.resolve('util')
```

**Comment by Davidiusdadi** [comment]
i got this error becasue i had an ```util``` folder in my repository in which i created an ```index.ts``` / ```index.js``` which overshadowed the ```node_module/util``` module. Solved it by just renaming that index.ts thereby preventing my ./util to pass as a node module.

**Comment by sorenhoyer** [comment]
I got this error as well when trying to use ES modules in my Webpack powered application.

![image](https://user-images.githubusercontent.com/2083553/48537739-bac38a80-e8b2-11e8-9f7a-5745d346395f.png)

but only if I give preference to (ES) modules over main `mainFields: ['module', 'main']`. 

"main" seems to work just fine. 

I'm shipping my libraries in both dist/main (commonjs) and dist/module (esnext) with TypeScript compiler directly, no bundling.

Any idea how to fix this? :-)

**Comment by chaeron** [comment]
> npm i --save util@0.10.0 works for me temporally
> 
> I am also was to run
> 
> cd node_modules/node-libs-browser && npm i util@0.10.0

I had this problem with a Nativescript-Vue project, trying to require the jasonwebtoken module.  The above worked as a temporary fix, so thanks!

**Comment by JeroenBos** [comment]
For me the problem `util.inherits is not a function` disappeared by removing `{ console: true}` rather than adding it... not a clue as to why

**Comment by markpradhan** [comment]
module.exports = {
  resolve: {
    mainFields: ['browser', 'module', 'main']
  }
};

Adding this to the webpack config solved it for me.

**Comment by milahu** [comment]
i got `TypeError: util.inherits is not a function` when trying to run [octonode](https://github.com/pksunkara/octonode) in the browser ...
