### ISSUE TITLE
basdir=`dirname "$0"` error

### ISSUE THREAD

**Issue by yccteam** [webpack/webpack#1020]
Hi,
I'm trying to run webpack webserver.
Here's the code:

```
#!/bin/sh
basedir=`dirname "$0"`

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  "$basedir/node"  "$basedir/../webpack-dev-server/bin/webpack-dev-server.js" "$@"
  ret=$?
else 
  node  "$basedir/../webpack-dev-server/bin/webpack-dev-server.js" "$@"
  ret=$?
fi
exit $ret
```

Here's the script line:
```"start": "node node_modules/.bin/webpack-dev-server --content-base app"```

Any idea why it gives me this error when running ```npm start```?

Here's the error:
```
C:\Users\Yonk\Documents\gridApp\node_modules\.bin\webpack-dev-server:2
basedir=`dirname "$0"`
        ^
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by sokra** [comment]
`"start": "webpack-dev-server --content-base app"`

**Comment by yccteam** [comment]
Thanks!

**Comment by weijyewang** [comment]
@sokra Thanks for the solution, it works for me. But I still can't understand why the original answer posted in this issue does not works. I will be glad if you could provide some explanation.

**Comment by mzarnawski** [comment]
Sure, the start command was wrong: node node_modules/.bin/webpack-dev-server instead of just node_modules/.bin/webpack-dev-server.
This "node" at the beginning is unnecessary.
