### ISSUE TITLE
Cleaning bundle at the time of running dev server

### ISSUE THREAD

**Issue by ameyzulkanthiwar** [webpack/webpack#10208]
When I am trying to clean up at the time of the build process it works but when I am running the dev server it is continuously creating a new file because I am using the hash placeholder. 

How can I clean up the code at the time of running the dev server? in webpack which plugin will help.

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Please use stackoverflow or gitter for questions, thanks
