### ISSUE TITLE
Invalid syntax in output when using an Array in "externals"

### ISSUE THREAD

**Issue by cecilemuller** [webpack/webpack#10201]
# Bug report

**What is the current behavior?**

Using an array in `externals` produces invalid syntax.

**If the current behavior is a bug, please provide the steps to reproduce.**

In [webpack.config.js](https://github.com/wildpeaks/issue-webpack-externals-array/blob/master/webpack.config.js):
````js
// Same as https://webpack.js.org/configuration/externals/#array
externals: {
  subtract: ['./math', 'subtract']
}
````

It outputs in [dist/app.js](https://github.com/wildpeaks/issue-webpack-externals-array/blob/master/dist/app.js#L108):
````js
eval("if(typeof ./math === 'undefined') {var e = new Error(\"Cannot find module './math.subtract'\"); e.code = 'MODULE_NOT_FOUND'; throw e;}\nmodule.exports = ./math[\"subtract\"];\n\n//# sourceURL=webpack:///external_%5B%22./math%22,%22subtract%22%5D?");
````

This triggers an error at runtime for two reasons:
 - `if(typeof ./math === 'undefined')`
 - `module.exports = ./math[\"subtract\"];`

Here's the full test case:
https://github.com/wildpeaks/issue-webpack-externals-array/

**What is the expected behavior?**

It should use a variable instead of the path directly because `./math` cannot be used as variable name.

**Other relevant information:**
webpack version: 4.41.5
Node.js version: 12.14.0 LTS
Operating System: Windows 10
Additional tools:

**Comment by sokra** [comment]
You need to set `output.libraryTarget: "commonjs2"` to create a commonjs module

**Comment by cecilemuller** [comment]
Are you implying that array externals only work when generating CommonJS libraries, not for regular bundles ?

Because if so, then I'd recommend the documentation should mention it, the same way it mentions object externals are only for `libraryTarget: umd`.

**Comment by sokra** [comment]
array externals also work for other libraryTargets, e. g. `externals: { subtract: ["Math", "subtract"] }` would reference the property `subtract` on the global `Math`: `Math.subtract`, but you example uses `'./math'` which looks like some request string for `require()`, which implies that you probably don't want to generate a normal browser script but a commonjs module instead.

**Comment by cecilemuller** [comment]
So it sounds like it's not usable for regular node bundles, only libraries; ok, so it's an issue for the documentation repository instead then.

Also, it's not my example, this was the example from the documentation.
