### ISSUE TITLE
How to avoid giving junk names by webpack in angular production build

### ISSUE THREAD

**Issue by devbikshu** [webpack/webpack#10203]
How to avoid junk names given when angular application build in production mode (ng build --prod)

example when i build normally using ng build command my module request is going like this

http://localhost:8762/accsm/cp-create-cp-create-module.js

same when i run in production mode using ng build --prod my request name is giving some junk name as follows

http://localhost:8762/accsm/5.4038f5bfd96424556526.js

How do avoid this junk name issue in production mode also?

Regards,
Bikshapathi

**Comment by sokra** [comment]
It's not junk. It's a hash for "long term caching"

you can configure this in webpack with `output.filename` and `output.chunkFilename`.

For how to do this with `ng build` see `angular-cli` documentation or ask there
