### ISSUE TITLE
Hot reloading with webpack

### ISSUE THREAD

**Issue by ameyzulkanthiwar** [webpack/webpack#10209]
I am able to achieve the hot reloading but I got into one issue is the old content is not getting replaced. It is still on the screen.

For example on the screen I am displaying the text 'I love web pack' and then I am replacing the text to 'I love web pack as well as bable' it is showing both the text.

How can I remove the 1st text which is getting displayed on the screen?

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
