### ISSUE TITLE
require.cache doesn't do the cleaning

### ISSUE THREAD

**Issue by sneltyn** [webpack/webpack#10204]
# Bug report

**What is the current behavior?**

The documentation  for method **require.cache**  says the following

```
Removing values from this cache causes new module execution and a new export.
```

But if execute **require.cache** and changed module after dynamically loading it, there will be no changes

**If the current behavior is a bug, please provide the steps to reproduce.**

**main.js:**

```js
import fs from 'fs'

async function test(){
  await import(/* webpackChunkName: "main-core" */ './main-core')
  
  // console output: first version

  // replace file programmatically or manual and rename to main-core.js

  fs.unlinkSync(`__dirname/${main-core.js}`)
  fs.renameSync(`__dirname/${main-core_.js}`, `__dirname/${main-core.js}`)

  require delete require.cache['./src/main-core.js']

  await import(/* webpackChunkName: "main-core" */ './main-core')

  // console output: first version 
}

test()
```

**main-core.js:**

```js
console.log('first version')
```

**main-core_.js**

```js
console.log('second version')
```

> **NOTE!!!**
**It is important that the modules after packaging are separate files.**

**What is the expected behavior?**

It is expected that after replacing the file there will be an imported new version of the file. That is, after the second import, the console should display: `second version`.

Perhaps I misunderstood the documentation, then tell me how to implement this behavior with dynamic loading at runtime and changing the file with subsequent import.

**Other relevant information:**
webpack version:  4.41.5
Node.js version: 10.16.3
Operating System: Windows 10 Pro 1903
Additional tools: Electron, babel

**Comment by sokra** [comment]
> ```
> Removing values from this cache causes new module execution and a new export.
> ```
> 
> 
> But if execute **require.cache** and changed module after dynamically loading it, there will be no changes

It does what it the documentation says. The module is executed again. It does not say that the file is read again from disk. Bundles are considered as one pieces. It's not possible to replace a part of it without updating the other parts. That's not something that it supported.

With HMR it's possible to upgrade the whole application (all chunks) to a new version.

**Comment by sneltyn** [comment]
@sokra Can i use HRM without dev-server?

**Comment by sokra** [comment]
Yes

**Comment by sneltyn** [comment]
Ok, i try it. Thx)
