### ISSUE TITLE
HotModuleReplacementPlugin throws TypeError: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by Mensu** [webpack/webpack#10210]
# Bug report

**What is the current behavior?**
I set up a dev server for my private project and run it, and when I edit some file, I see the following error thrown by HotModuleReplacementPlugin and then the server exits.

```
<cwd>/node_modules/webpack/lib/HotModuleReplacementPlugin.js:275
                                                                const removedModules = records.chunkModuleIds[chunkId].filter(
                                                                                                                       ^

TypeError: Cannot read property 'filter' of undefined
    at compilation.hooks.additionalChunkAssets.tap (<cwd>/node_modules/webpack/lib/HotModuleReplacementPlugin.js:275:64)
    at SyncHook.eval [as call] (eval at create (<cwd>/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:12:1)
    at SyncHook.lazyCompileHook (<cwd>/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeTree.callAsync.err (<cwd>/node_modules/webpack/lib/Compilation.js:1399:37)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (<cwd>/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (<cwd>/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.seal (<cwd>/node_modules/webpack/lib/Compilation.js:1342:27)
    at compilation.finish.err (<cwd>/node_modules/webpack/lib/Compiler.js:675:18)
    at hooks.finishModules.callAsync.err (<cwd>/node_modules/webpack/lib/Compilation.js:1261:4)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (<cwd>/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:20:1)
    at AsyncSeriesHook.lazyCompileHook (<cwd>/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.finish (<cwd>/node_modules/webpack/lib/Compilation.js:1253:28)
    at hooks.make.callAsync.err (<cwd>/node_modules/webpack/lib/Compiler.js:672:17)
    at _done (eval at create (<cwd>/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at _err1 (eval at create (<cwd>/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:32:22)
    at _addModuleChain (<cwd>/node_modules/webpack/lib/Compilation.js:1185:12)
    at processModuleDependencies.err (<cwd>/node_modules/webpack/lib/Compilation.js:1097:9)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

I tried printing the variables and was surprised to find that `chunkId` was `Infinity`, and `key` was `'55124230e814'`. I believe it is because of the logic here

https://github.com/webpack/webpack/blob/v4.41.5/lib/HotModuleReplacementPlugin.js#L260
```js
const chunkId = isNaN(+key) ? key : +key;
```

When `key` is `'55124230e814'`, `+key` would be `Infinity`, which is not `NaN`, so `chunkId` is assigned `Infinify`. I believe in this case `chunkId` should still be `key`, that is `'55124230e814'`.

I also find that in webpack 5.0.0 this condition is already removed.

https://github.com/webpack/webpack/blob/v5.0.0-beta.11/lib/HotModuleReplacementPlugin.js#L311
```js
const chunkId = key;
```

**If the current behavior is a bug, please provide the steps to reproduce.**
I can only reproduce this bug in my private project and I can't share it.

**What is the expected behavior?**
No errors are thrown

**Other relevant information:**
webpack version:  4.41.5
Node.js version: 10.7.0/12.9.1
Operating System: Mac OS
Additional tools: None

**Comment by evilebottnawi** [comment]
Please create reproducible test repo, you can remove private code, we need example of your code and configuration

**Comment by Mensu** [comment]
> Please create reproducible test repo, you can remove private code, we need example of your code and configuration

@evilebottnawi Here is the reproducible test repo: https://github.com/Mensu/webpack-reproduce-issue-10210

After digging into the source code, I found the chunk id '55124230e814' was generated by this plugin: https://github.com/darshanlsagar/webpack-custom-chunk-id-plugin/blob/master/index.js#L38

There are three chunk group in my project: `FeedSpreadsheet`, `PCDocSheetBridge`, and `PCSpreadSheet`. `optimization.splitChunks.automaticNameDelimiter` is set to '-'. Because there are shared modules between the three chunk groups, `webpack` splits out a chunk whose name is `'FeedSpreadsheet-PCDocSheetBridge-PCSpreadSheet'` for the shared modules. `webpack-custom-chunk-id-plugin` creates an md5 hash for this name

```js
let hashVal = 'FeedSpreadsheet-PCDocSheetBridge-PCSpreadSheet';
crypto.createHash('md5').update(hashVal).digest('hex')  //  evaluates to '55124230e8140c5ebc0d808dbaa65245'
```

The hash value is '55124230e8140c5ebc0d808dbaa65245'. As `options.hashLength` of `webpack-custom-chunk-id-plugin` is set to `12`, the plugin takes the first 12 characters '55124230e814' and assign it to `chunk.id`.

**Comment by sokra** [comment]
hmm... seems like you hit a very unlikely case of a hash `55124230e814` being a valid number...

**Comment by Mensu** [comment]
> hmm... seems like you hit a very unlikely case of a hash `55124230e814` being a valid number...

@sokra Does webpack have any restrictions like a plugin should never set `chunk.id` to a string that can be converted to a valid `number`? In fact I don't see any point in converting the `key` to a number at https://github.com/webpack/webpack/blob/v4.41.5/lib/HotModuleReplacementPlugin.js#L260

I guess it was because in the past the logic below was `chunk.id === key`  instead of `${chunk.id}` `=== key`, which made it necessary to convert the string key to its original type in order to match the type of `chunk.id`

```js
const currentChunk = compilation.chunks.find(
  chunk => `${chunk.id}` === key,
);
```

**Comment by sokra** [comment]
> I guess it was because in the past the logic below was `chunk.id === key` instead of `${chunk.id}` `=== key`, which made it necessary to convert the string key to its original type in order to match the type of `chunk.id`

yep. If you want to you can send a PR to webpack 4 to backport this fix from webpack 5.

**Comment by sbeaney** [comment]
I may have been running into this issue when I reported it back in October of 2019 (https://github.com/webpack/webpack/issues/9871) but I didn't have the ability to dig as deep as you have. I had a hunch the issue is what you described here.

I was reminded of this because today I had to go back in and edit my local copy of HotModuleReplacementPlugin.js to implement the fix so HMR would work again.

**Comment by zhangmin173** [comment]
I have the same problem because I use a numeric string as the entry value

```
entry: {
  '1.0': 'src/1.0/index.js',
  '2.0': 'src/2.0/index.js
}
```
so in HotModuleReplacementPlugin.js
```
const chunkId = isNaN(+key) ? key : +key;
...
records.chunkModuleIds = {
  '1.0': [],
  '2.0': []
}
...
const removedModules = records.chunkModuleIds[chunkId].filter(
  id => !allModules.has(id)
);
```
so records.chunkModuleIds[chunkId] is non-existent

**Comment by evilebottnawi** [comment]
Bump
