### ISSUE TITLE
Not Working in IE11 with no console error

### ISSUE THREAD

**Issue by kumaresan-subramani** [webpack/webpack#10219]
# Bug report

This is my application `javascript` with webpack compilation.

Sample - https://github.com/kumaresan-subramani/IE11-not-working

My appplication not get loaing in `IE11` but working fine in `chrome` browser. I have tried so many workaround but no luck. is this webpack behavior or something?

**What is the current behavior?**
Application not loading in `IE11` without console error

**If the current behavior is a bug, please provide the steps to reproduce.**

1. clone my sample - https://github.com/kumaresan-subramani/IE11-not-working
2. give `npm i`
3. then run `gulp serve`
4. application will open in browser with `http://localhost:3000`

**What is the expected behavior?**

Appplication sholud work in `IE11`

**Other relevant information:**
webpack version:  4.41.5
Node.js version: 10.15.1 && 8.11.3 _[ both are not working]_
Operating System: windows 10
Additional tools:

**Comment by montogeek** [comment]
This is not related to webpack, you are not transpiling JS code to work on older browsers.

**Comment by kumaresan-subramani** [comment]
@montogeek , but it working fine in chrome and IE11 is not older browser 

> you are not transpiling JS code to work on older browser

what are you mentioning here, can you please describe little more detail

**Comment by kumaresan-subramani** [comment]
Error:

```
Uncaught (in promise) TypeError: Object doesn't support property or method 'forEach'
at t.prototype.setAttributes (http://localhost:3000/dist/ej2.min.js:1:1267231)
at t.prototype.createList (http://localhost:3000/dist/ej2.min.js:1:1267671)
```

Is this something relate to this issue? if yes, what is the reason

**Comment by montogeek** [comment]
Feel free to follow a guide like this one: https://www.thebasement.be/working-with-babel-7-and-webpack/

Reason is that IE11 doesn't support that method.
