### ISSUE TITLE
Typescript: Cannot find name 'RuleSetConditionsRecursive'

### ISSUE THREAD

**Issue by amoshydra** [webpack/webpack#10217]
> I didn't know recursive type was only supported in Typescript 3.7 (landed Nov 5, 2019)

# Bug report

**What is the current behavior?**
Typescript reports type definition errors for `webpack/declarations/WebpackOptions.d.ts` when using:
```ts
import { WebpackOptions } from 'webpack/declarations/WebpackOptions';
```

The following errors are generated when running type checking: `tsc --noEmit -p ./tsconfig.json`
```
../../../node_modules/webpack/declarations/WebpackOptions.d.ts:135:33 - error TS2304: Cannot find name 'RuleSetConditionsRecursive'.

135 export type RuleSetConditions = RuleSetConditionsRecursive;
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~

../../../node_modules/webpack/declarations/WebpackOptions.d.ts:184:41 - error TS2304: Cannot find name 'RuleSetConditionsAbsoluteRecursive'.

184 export type RuleSetConditionsAbsolute = RuleSetConditionsAbsoluteRecursive;
                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

This issues seem to be related to https://github.com/webpack/webpack/pull/8348. However, applying the fix mentioned in #8348 doesn't resolve this issue.

**If the current behavior is a bug, please provide the steps to reproduce.**

### Option 1
1. Clone webpack
2. `git checkout v4.41.5` (of any version between 4.20.0 and 4.41.5)
3. Open project in VSCode
4. Inspect the file `webpack/declarations/WebpackOptions` in VSCode
5. Both `RuleSetConditionsRecursive` and `RuleSetConditionsAbsoluteRecursive` are highlighted in red with errors:
    1. `Cannot find name 'RuleSetConditionsRecursive'.ts(2304)`
    1. `Cannot find name 'RuleSetConditionsAbsoluteRecursive'.ts(2304)`

### Option 2
1. `yarn add typescript`
2. `yarn tsc --init`
3. Create a typescript project that import the declaration file
    ```ts
    import { WebpackOptions } from 'webpack/declarations/WebpackOptions';
    ```
4. Run `yarn tsc --noEmit`
5. Typescript should reported the errors

[![Edit modern-architecture-78bo4](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/modern-architecture-78bo4?expanddevtools=1&fontsize=14&hidenavigation=1&moduleview=1&theme=dark)

**What is the expected behavior?**

There should be no types definition error.

##### Current Workaround
Right now it is possible to workaround this issue by adding a type definition shim matching the content in https://github.com/webpack/webpack/blob/c7681825f868cddff0a6aa840330354a588188ff/declarations.d.ts#L223-L230
```ts
import { RuleSetConditions, RuleSetConditionsAbsolute } from 'webpack/declarations/WebpackOptions';

declare module 'webpack/declarations/WebpackOptions' {
  type RuleSetConditionsRecursive = RuleSetConditions[]
  type RuleSetConditionsAbsoluteRecursive = RuleSetConditionAbsolute[]
}
```

**Other relevant information:**
webpack version: Between 4.20.0 to 4.41.5
Node.js version: v8.16.0
Operating System: Windows 10
Additional tools: typescript@3.7.4

**Comment by amoshydra** [comment]
This issue seems to be fixed in Webpack 5 with this commit 
https://github.com/webpack/webpack/commit/0ea81b542cf8eb948ae14d09a40af41b9b55982c#diff-8588527c440c140a86b57694ee7a97bcL135-R184

Perhaps the same fix can be applied to Webpack 4 too?

**Comment by sokra** [comment]
Send a PR
