### ISSUE TITLE
How to export a JavaScript Library to multiple formats

### ISSUE THREAD

**Issue by zerofront** [webpack/webpack#10212]
When publishing a JavaScript library, we usually want to make it available to as many people as possible to maximize the library’s usefulness and adoption. In that respect, it can be helpful to users to have the library available in their preferred module format - CommonJS, AMD, ES6, etc. 

![image](https://user-images.githubusercontent.com/19327366/71713522-07667e00-2e45-11ea-95df-b15bbb84cd4a.png)

how can I config in order to export multiple formats
eg:
dist/lib/libarary.umd.js
dist/umd/library.umd.js
dist/es/library.module.js

**Comment by MarkH817** [comment]
https://webpack.js.org/configuration/configuration-types/#exporting-multiple-configurations

**Comment by evilebottnawi** [comment]
Answer above

@MarkH817 thanks
