### ISSUE TITLE
官网文档的指南使用观察者模式移除错误应该是console.error('I get called from print.js!');

### ISSUE THREAD

**Issue by l695343920** [webpack/webpack#10218]
![image](https://user-images.githubusercontent.com/34496207/71801091-d2506a80-3094-11ea-8f5c-9e44c84915f3.png)

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
