### ISSUE TITLE
stats.preset config option not allowed

### ISSUE THREAD

**Issue by dougalg** [webpack/webpack#10221]
# Bug report

**What is the current behavior?**

When using the object option for `stats`, the `preset` is not an allowed sub-option.

While, it is well documented here: https://webpack.js.org/configuration/stats#preset it appears to be missing from the WebpackOptions.json schema.

**If the current behavior is a bug, please provide the steps to reproduce.**

Create a minimal webpack build and enable something like:

```
// Example from https://webpack.js.org/configuration/stats/#extending-stats-behaviours
module.exports = {
	// ...
    stats: {
        preset: 'minimal',
        moduleTrace: true,
        errorDetails: true
    },
};
```

**What is the expected behavior?**

It should be possible to extend stats preset settings without receiving an error, and with configurations being merged properly.

**Other relevant information:**
webpack version: 4.41.5
Node.js version: v12.10.0
Operating System: Mac OS 10.14.6
Additional tools: None

**Comment by sokra** [comment]
This option was introduced in webpack 5. It's not available in webpack 4:

https://v4.webpack.js.org/configuration/stats/#extending-stats-behaviours

**Comment by dougalg** [comment]
So the documentation on webpack.js.org which says "webpack v4.41.5" is actually for webpack 5? Is there are link somewhere to get to the v4 docs, other than just knowing? If not, maybe I should see if I can make an update to the docs website, because I found it very confusing and frustrating.

**Comment by arcataroger** [comment]
@dougalg I ran into this same issue and was confused by the documentation too. It really should be clearer that the default documentation is for the v5 beta :(

The v4 documentation is still available: https://v4.webpack.js.org/configuration/stats/ and properly doesn't list the "preset" option, but to get to the v4 docs you have to scroll to the bottom of the left sidebar.

It's strange to me that the default docs is for beta, and doesn't make that clear. Thanks for having raised this issue previously.
