### ISSUE TITLE
In browser debugger - no access to thrown error when in async context

### ISSUE THREAD

**Issue by lilotop** [webpack/webpack#10224]
# Bug report

**What is the current behavior?**
When an exception is caught inside an async function, the debugger does not display the value of the exception parameter given to the `catch` block.
It is accesible by the program itself, e.g. you can log it to the console, but not to the debugger (tried it with the latest Chrome, Firefox and Edge)

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Create a simple **async** function that throws and catches an exception.
2. In the browser's dev-tools, place a breakpoint inside the `catch` block.
3. The value of the caught exception is not shown on hover.
4. Also it is not available by typing the parameter's name in the console.

Example function:
```
        async created() {
            try {
                throw {a: 42, msg: 'hello lilo'};
            }
            catch (e) { // <-- can't inspect in dev-tools
                console.log(e); // <-- prints the value correctly (breakpoint here)
            }
        }
```
It is worth noting that I found the exception object inside `arguments[0].t0` (if you type this into the console you get the exception object passed to the `catch` block.

**What is the expected behavior?**
Caught exception should be available to the debugger.
Note that if you remove the `async` prefix from the function the exception is available.

**Other relevant information:**
webpack version:  4.41.2
Node.js version: v10.13.0
Operating System: Windows 10
Additional tools: Vue CLI (@vue/cli 4.0.5)

The webpack project was created by the Vue CLI tool.

**Comment by sokra** [comment]
Seems like you transpiled the async function. Consider disable transpilation for development, that makes debugging easier.

**Comment by lilotop** [comment]
I'm sorry but I couldn't find any documentation on this or anything useful on stackoverflow. How do I disable transpilation just for development?

**Comment by evilebottnawi** [comment]
Depends on your configuration
