### ISSUE TITLE
 warning yarn install

### ISSUE THREAD

**Issue by karlben** [webpack/webpack#10220]
# Bug report

I have  warning I don't know what is the problem
i use node v12.14.0
yarn install v1.21.1
[1/4] Resolving packages...
[2/4] Fetching packages...
warning mini-css-extract-plugin@0.4.2: Invalid bin field for "mini-css-extract-plugin".
warning sha.js@2.4.11: Invalid bin entry for "sha.js" (in "sha.js").
info fsevents@1.2.11: The platform "linux" is incompatible with this module.
info "fsevents@1.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...

**Comment by sokra** [comment]
There are no problems

**Comment by mguomanila** [comment]
i had the same experience...athough it's only a warning it would be greatly appreciated if someone would explain what's happening here?? thanks in advance

**Comment by sunpietro** [comment]
anyone can explain it, please?

**Comment by ciancu-gpsw** [comment]
I have encounted the same issue here.

**Comment by pujianto** [comment]
https://github.com/yarnpkg/yarn/issues/7803#issuecomment-574656273
