### ISSUE TITLE
os.platform get browser

### ISSUE THREAD

**Issue by wangfpp** [webpack/webpack#10229]
nodeJs document os.platform() return 'win32' | 'linux' ....
but webpack proify get browser 
how fix ???

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Please look at https://webpack.js.org/configuration/node/
