### ISSUE TITLE
Output CSS to different directory with ExtractTextPlugin

### ISSUE THREAD

**Issue by simonsmith** [webpack/webpack#1022]
I'm using the ExtractTextPlugin to build a separate CSS file. It works great but I'd really like to output the CSS into a different directory than the JS:

``` js
module.exports = {
  entry: {
    module: "./source/javascripts/app.js",
  },
  output: {
    path: './source/built/',
    filename: 'app.js'
  },
  module: {
    loaders:[
      {
        test: /\.js$/, exclude: /node_modules/, loader: 'babel-loader'
      },
      {
        test: /\.css$/,
        loader: ExtractTextPlugin.extract('style-loader', 'css-loader!postcss-loader')
      }
    ]
  },
  plugins: [
    new ExtractTextPlugin('app.css')
  ]
};
```
Currently both files go into `./source/built`, is there a way to change this?

**Comment by andreypopp** [comment]
Did you try:
```
new ExtractTextPlugin('css/app.css')
```

Not sure if it works, just a guess.

**Comment by andreypopp** [comment]
Also, issue probably belongs to extract-text-webpack-plugin repo than here.

**Comment by simonsmith** [comment]
It seems to feed off the `path` in `output` which is why I presumed it might be webpack related. Using `css/app.css` puts it in `./source/built/css/`

**Comment by nerdgrass** [comment]
This actually was a similar problem I was facing and andreypopp's answer solved it for me. Specifically, what worked for me was:
```
plugins: [
    new ExtractTextPlugin("./css/[name].css"),
  ],
```

**Comment by simonsmith** [comment]
Ah nice, in my example I was able to use `new ExtractTextPlugin("../css/[name].css")` to solve moving it to a different dir.

Thanks

**Comment by iDVB** [comment]
Sorry to raise this question up again but the documentation and my googling does not seem to cover what seems to me as a typical use case.
```
source/
    /componets/
       app.js
       app.scss
       image.png
     
dist/
   /css/
      all.bundle.css
   /images/
      image.png
   /js/
      all.bundle.js
   application.html
```

I've try a number of configs:
```javascript
webpack: { // grunt-webpack
  options: {
    module: {
      loaders: [
        { test: /\.jsx?$/, exclude: /(node_modules|bower_components)/, loader: 'babel' }, // REACTJS FILES
        { test: /\.json?$/, exclude: /(node_modules|bower_components)/, loader: 'json' }, // JSON FILES
        { test: /\.scss$/, loader: ExtractTextPlugin.extract('css!sass?includePaths[]=' + bourbon) }, // SASS & CSS FILES
        { test: /\.(jpe?g|png|gif|svg)$/i, exclude: /(node_modules|bower_components)/, loader: 'url?limit=1000&name=images/[hash].[ext]' } // IMAGES
      ]
    } 
  },
  dev: {
    entry: './<%= assets %>/js/component/app.js',
    output: {
      path: './<%= dist %>/',
      filename: 'js/all.bundle.js'
    },
    plugins: [
      new ExtractTextPlugin('css/all.bundle.css', {
        allChunks: true
      })
    ]
  },
}
```

I've also tried the following...
ExtractTextPlugin('./css/all.bundle.css',
ExtractTextPlugin('../css/all.bundle.css',
ExtractTextPlugin('./../css/all.bundle.css',

In most cases I'm able to get the css file to output to the proper folder, but then the image urls in the resulting css points to 'images/image.png' which of course should be '../images/image.png'

I think I'm missing something small that is leading to my frustration.

**Comment by vshjxyz** [comment]
@iDVB any news on this? I'm facing the same problem, it looks more of a `css-loader` issue anyway. 

Then problem is that css loader is applied BEFORE moving the css with the extracttextplugin to the desired folder...

**Comment by iDVB** [comment]
This worked for me..

```javascript
webpack: { // grunt-webpack
  options: {
    module: {
      loaders: [
        { test: /\.jsx?$/, exclude: /(node_modules|bower_components)/, loader: 'babel' }, // REACTJS FILES
        { test: /\.json?$/, exclude: /(node_modules|bower_components)/, loader: 'json' }, // JSON FILES
        { test: /\.scss$/, loader: ExtractTextPlugin.extract('css!sass?includePaths[]=' + bourbon, { publicPath: '../'}) }, // SASS & CSS FILES
        { test: /\.(jpe?g|png|gif|svg)$/i, exclude: /(node_modules|bower_components)/, loader: 'url?limit=1000&name=images/[hash].[ext]' } // IMAGES
      ]
    } 
  },
  dev: {
    entry: './<%= project.path.voter.assets %>/app/app.js',
    output: {
      path: './<%= project.path.voter.dist %>/',
      filename: 'js/voter.bundle.js'
    },
    plugins: [
      new ExtractTextPlugin('css/voter.bundle.css', {
        allChunks: true
      })
    ]
  }
}
```

**Comment by vshjxyz** [comment]
@iDVB maybe cause you're using `url loader` to extract images and as they are 'small' they are embedded in base64. 

If I use `file-loader` or if I have big images the css' `url(...)` are pointing to the wrong directory (I've got everything under `assets/` and the css is rewritten with `url(assets/example.png)` instead of `url(example.png)`

**Comment by iDVB** [comment]
Ya, not sure, I spent so much (too much) time trying to get something to work that once it did, I didn't really care "why" :P 

D

**Comment by jon301** [comment]
Had the same problem. The solution suggested by @iDVB worked for me too, though it's weird that publicPath contains a relative path value

**Comment by jununx** [comment]
@iDVB I have a common problems, with your solution, thank you.

**Comment by ulfryk** [comment]
@vshjxyz - have you found solution ?

**Comment by oodzchen** [comment]
@iDVB thank you so much, it really helped me a lot.

**Comment by crossingmay** [comment]
@nerdgrass thank you !~ It's useful for me !

**Comment by shri3k** [comment]
@ulfryk I don't know how @iDVB's solution solves this and also don't know how late it is for you but I was able to get this working by doing the following.

```js
module.exports = {
  entry: {
    './bundle.js': './index.js'
  },
  output: {
    filename: '[name]',
    publicPath: 'assets/'
  },
  module: {
    loaders: [{
      test: /\.scss$/,
      loader: ExtractTextPlugin.extract('style', 'css!sass'),
    }, {
      test: /\.png$/,
      loader: 'file',
      query: {
        name: 'assets/image/[hash].[ext]', // note this line still uses `assets` in path to create the right public directory
        publicPath: '/' // this overwrites the `publicPath` that's mentioned at the top or else you'd have `assets/assets/image/slkfdjskldf.png` in your css url(..)
      }
    }]
  },
  plugins: [new ExtractTextPlugin("./style/styleBundle.css")]
};
```

If the above is not as clear then basically you'd need to add `publicPath` in your `ExtractTextPlugin` query to override `publicPath` that's at the parent level while still putting the public path or in my case `assets` in the `name` query of ExtractTextPlugin so that it extracts to the right public directory while keeping the right url in the css.
Hope that clarifies a little and helps others as well cause it took me almost a day to figure this out.

**Comment by 1415926535** [comment]
I had this problem but just added subdirectory to the filename and it worked. 
Ubuntu webpack 2.4.1

```
const path = require('path');
const glob = require('glob');
const webpack = require('webpack');
const ExtractTextPlugin = require('extract-text-webpack-plugin');


module.exports = {
  entry: './src/main.js',
  output: {
    path: __dirname + '/public',
    filename: 'js/packpiled.js'
  },
  module: {
    loaders: [
        {
          test: /\.scss$/,
          loader: ExtractTextPlugin.extract('css-loader!sass-loader')
        }
    ]
  },
  plugins: [
    new ExtractTextPlugin('css/bootytwap4.css')
  ]
}
```

**Comment by dagoss** [comment]
@1415926535 I tried that and I got an `Error: Cannot readFile on directory` error. It seems that it could create the output directory, but not the directories when they were combined with the file names.

**Comment by jk171505** [comment]
I have the same issue as @dagoss. I tried different combinations and the css file is either not created at all (even if there is confirmation msg saying the file was emitted) or I get Cannot readFile on directory error...
Anyone knows what's wrong?

**Comment by dandigangi** [comment]
Randomly stumbled here. This plugin will make your life much easier.

https://github.com/webpack-contrib/copy-webpack-plugin

**Comment by gilomen2** [comment]
@dandigangi thank you! saved me so much frustration.
