### ISSUE TITLE
Can I split chunks based on modules' entry point?

### ISSUE THREAD

**Issue by aleen42** [webpack/webpack#10225]
Assume that I have two entries, `a` and `b`, and they both have many different chunks, and how can I split two chunks via the entry point?

I have tried this but not worked:

```js
// webpack.config.js
module.exports = {
    optimization : {
        runtimeChunk : false,
        splitChunks  : {
            cacheGroups : {
                vendors : false,
                entry   : {
                    name(module, chunks) { /* how to know corresponding entry point? */},
                    chunks : 'all',
                    test   : /^js$/,
                },
            },
        },
    },
};
```

It is significant because I need a workaround to extract styles into single files based on entries via [`mini-css-extract-pluigin`](https://github.com/webpack-contrib/mini-css-extract-plugin), where two entries have required depedencies from each.

**Comment by evilebottnawi** [comment]
Please use issue template otherwise issue will be closed
