### ISSUE TITLE
Webpack 5-beta.11 breaks some module imports

### ISSUE THREAD

**Issue by brettwillis** [webpack/webpack#10230]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

I don't fully understand the root cause, but with version 5.0.0-beta.11, some module imports seem to be broken due to import naming.

The issue doesn't exist with beta.10 or beta.9.

Here's what I see:

- The problem manifests for me in lit-html's [shady-render.ts#L75](https://github.com/Polymer/lit-html/blob/f69936e1b80d3ac0c34cd599f611846cdfc9d898/src/lib/shady-render.ts#L75)

      import {marker, Template} from './template.js';

      ...

      let template = templateCache.stringsArray.get(result.strings);
      if (template !== undefined) {
        return template;
      }

      const key = result.strings.join(marker); <--- HERE

- When compiled by Webpack `import {marker, Template} from './template.js';` becomes:

      // EXTERNAL MODULE: ./node_modules/lit-html/lib/template.js
      var template = __webpack_require__(6617);

      ...

       if (template !== undefined) {
         return template;
       }

       var key = result.strings.join(template/* marker */.Jw);

- Now you can see that the import is called `template` and this conflicts with the local variable, breaking the code.

**If the current behavior is a bug, please provide the steps to reproduce.**

Haven't tried this specifically but I expect you can reproduce it by running this lit-html starter kit with webpack@5.0.0-beta.11.

https://github.com/Polymer/pwa-starter-kit/tree/template-typescript-webpack

**What is the expected behavior?**

You are the experts, but the code should not break. :)

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

Webpack 5.0.0-beta.11 (#9802)
Node.js v12.14.0
macOS

**Comment by sokra** [comment]
I wasn't able to reproduce this bug. Could you provide a repro repo? The provided one doesn't lead to the problem.

**Comment by brettwillis** [comment]
In the process of trying to create a repo, I couldn't reproduce it. After upgrading to beta.12 in the original repo and back down to beta.11 it no longer happens.

Must have been some transient npm versioning? I can't figure out what it was, but it's no longer an issue.

Thanks.

**Comment by marksamman** [comment]
I'm seeing a similar issue in a large project since upgrading from beta 10 to 11, tried upgrading from 10 to 12 today but it's still broken so sticking with beta 10 for now. My import looks like this:
```
import Notifications from '@/models/notifications';
```
and the notifications.js module exports an object along these lines (actual file has 35 entries):
```
export default {
	FriendRequestAccepted: 0,
};
```
When trying to access Notifications.FriendRequestAccepted in the file that imports notifications.js I get:
```
Cannot read property 'FriendRequestAccepted' of undefined
```

The at-symbol is an alias in my webpack config, if that's relevant:
```
'@': path.resolve(__dirname, 'src/js/'),
```
