### ISSUE TITLE
Loading External File (AWS S3)

### ISSUE THREAD

**Issue by ryanburnett** [webpack/webpack#1024]
I'm using webpack 1.8.11 and trying to load an external file (on AWS S3).

Here is my code (following the [Getting Started Guide](http://webpack.github.io/docs/tutorials/getting-started/)):

*index.html*
```
<html>
<head>
	<meta charset="utf-8">
</head>
<body>
<script type="text/javascript" src="bundle.js" charset="utf-8"></script>
</body>
</html>
```

*webpack.config.js*
```
module.exports = {
	entry: "./entry.js",
	output: {
		path: __dirname,
		filename: "bundle.js"
	}
};
```

*entry.js*
`document.write(require("https://s3.amazonaws.com/fabricdev-webdata/home-decor/aws.js"));`

*https://s3.amazonaws.com/fabricdev-webdata/home-decor/aws.js*
`module.exports = "It works from aws. ";`

Here is the error:
`Module not found: Error: Cannot resolve module 'https://s3.amazonaws.com/fabricdev-webdata/home-decor/aws.js'`

Any idea what I'm doing wrong?

**Comment by IngwiePhoenix** [comment]
This sounds like something a Plugin could do. Sadly there is not a lot of docs for writing these yet, but they have a method to intercept or extend upon the module resolver…which is what you want. With a custom resolver, you could resolve the URL, bump the content to a local storage and then require it into the webpack…at least thats the idea from the top of my head o.o WebPack doesnt support URLs natively.

**Comment by sokra** [comment]
see #150
