### ISSUE TITLE
Webpack4 doesn't handle network paths

### ISSUE THREAD

**Issue by travikk** [webpack/webpack#10247]
# Bug report

**What is the current behavior?**

When `output.path` is a network path of the following format: `\\hostname\directory\deep\tree` webpack fails with the following message:

```
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.output.path: The provided value "\\\\hostname\\directory\\deep\\tree" is not an absolute path!
   -> The output directory as **absolute path** (required).
```

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Specify `output.path` as a network path. 
2. Try to compile the application

**What is the expected behavior?**

Network path is accepted and webpack outputs files to the specified path.

**Other relevant information:**
webpack version:  4.41.2
Node.js version: 10.15.1
Operating System: Windows

**Comment by sokra** [comment]
Send a PR to schema-utils

Here is the relevant line: https://github.com/webpack/schema-utils/blob/6caaa59cf40af948ea3d9658f4c32bd79b6c37a5/src/keywords/absolutePath.js#L54

**Comment by evilebottnawi** [comment]
https://github.com/webpack/schema-utils/pull/85, but for webpack@4 we need fix it here https://github.com/webpack/webpack/blob/v4.41.5/schemas/ajv.absolutePath.js#L29

**Comment by sokra** [comment]
yep. fix master first, then old versions...

**Comment by travikk** [comment]
@sokra @evilebottnawi Looks like this has been addressed no?

**Comment by evilebottnawi** [comment]
Yes, thanks
