### ISSUE TITLE
about splitChunk with dynamic import .

### ISSUE THREAD

**Issue by superchangme** [webpack/webpack#10246]
# Bug report

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
i use webpack4 with vue projects.I want split my dynamic import vue file and their dependencies  (use normal import syntax）into a chunk.
code is here
```javascript
splitChunks: {
cacheGroups: {
'vendor-async': {
          chunks: 'all',
          name: 'vendor-async',
          test(module,chunks){
            var libs = [path.join(__dirname, '..', 'src/components'),path.join(__dirname, '..', 'src/views/components'),path.join(__dirname, '..', 'src/vendor')]
            return module.context && libs.some(function (o) {
              return module.context.indexOf(o) >= 0
            }) 
          },
          minChunks: 3,
          priority: 5,
          reuseExistingChunk: true
        }
}
}
````
For example.I have three dynamic import vue files,they all import the file map.js.I want webpack can pack map.js into vendor-async.bundle.js.
But the result is webpack will pack map.js  file into app.bundle.js，even if the file is use more than 3 times in different dynamic vue files.
But when i change the config minChunks to 1.and rebuild map.js can be packed into wendor-async
I mean how webpack count minChunks,dynamic import only count once?\
Can you help me,how can i find the right way to split chunk into dynamic import...
I'm looking forward to your reply！

**Other relevant information:**
webpack version:  4.8.2
Node.js version: 10.16
Operating System: win7 64
Additional tools:

**Comment by sokra** [comment]
You must not import `map.js` from your not dynamic imported part of your application. Currently this is the case.

I would recommend to remove all splitChunks configuration expect `splitChunks: { chunks: "all" }`. The default config will automatically put modules into new shared chunks when the common part is > 30kb.

**Comment by pratheekhegde** [comment]
Can we have separate vendor bundles for async modules?

**Comment by rpivo** [comment]
@sokra Maybe I'm misunderstanding, but is there no way to dynamically import vendor files?
