### ISSUE TITLE
Dynamic import a UMD module that has been built externally

### ISSUE THREAD

**Issue by pastelsky** [webpack/webpack#10248]
Currently, webpack supports async importing of local files via either the dynamic import syntax or require. However, if you want to dynamically import a JS library that lives outside your current codebase, I didn't find a good way to do so.

If you do this –

```js
  const lib = import(/* webpackIgnore: true */ 'https://unpkg.com/some-umd-lib.js')
```

webpack does not make this a part of its resolution process at all. This makes it very tough to import a built UMD module which might depend on externals that are available in the environment where it is being `import()`ed.

It'd be great if webpack could detect external links, and replace `import()` with a `__webpack_require__` version that makes exports external scripts a part of its local list of available modules, and also fulfils `external` requirements of the script using the current list.

---

![image](https://user-images.githubusercontent.com/8946207/72353271-c5bdb900-3709-11ea-8e3a-e769c6955215.png)

**Comment by sokra** [comment]
> webpack does not make this a part of its resolution process at all.

The resolution process happens at build-time. native `import()` happens at runtime. Also native `import()` only supports ESM. You can't import a UMD file via native `import()`.

If you are looking for something which handles modules at runtime, you are looking for a "module loader".

**Comment by pastelsky** [comment]
So yes, I can use a module loader – but the loader be able to reconcile runtime dependencies needed by the external javascript file - even when they are present in webpackJsonP object (I think) ? 

Webpack doesn't have to know what imports / exports are present in the JS files at build time. I'm just looking for a way to execute the dynamically loaded module in the context of the existing webpack runtime environment.

**Comment by pastelsky** [comment]
There seems to have been some previous discussions here using systemjs-
https://github.com/webpack/webpack/issues/2810

But it's probably better to avoid interop between the webpack registry (client) and a system js dependency (child) – when we know that both modules have their own "webpack" module registries.

**Comment by Jokero** [comment]
@pastelsky take a look at this https://github.com/webpack/webpack/issues/7526

**Comment by pastelsky** [comment]
Closing this, as this discussion seems to be getting good traction at -

https://github.com/webpack/webpack/issues/10352
