### ISSUE TITLE
Tree shaking delete my code.

### ISSUE THREAD

**Issue by JeffWong16** [webpack/webpack#10254]
I config  `{ "sideEffects": false }` in my project.

index.js
```javascirpt
import { B } from './A'

B.foo()
B.bar()
```

A.js
```
import B from './B'

B.bar = function() {
  console.log('a')
}

export { B }
```
B.js
```
export default {
  foo () {
    console.log('b foo')
  }
}
```

The output is 
```
...
__webpack_require__.r(__webpack_exports__);

// CONCATENATED MODULE: ./src/B.js
/* harmony default export */ var B = ({
  foo () {
    console.log('b foo')
  }
});
// CONCATENATED MODULE: ./src/index.js


B.foo()
B.bar()
...
```

As you can see,  the below code is lost.
```
B.bar = function() {
  console.log('a')
}
```

But when I change index.js  A.js
index.js
```
import  B from './A'
B.foo()
B.bar()
```
 A.js
```
import B from './B'

B.bar = function() {
  console.log('a')
}

export default B 
```
bar function comes back.

Why does that work?

**Comment by sokra** [comment]
> ``` js
> B.bar = function() {
>   console.log('a')
> }
> ```

This is a side effect. You incorrectly marked the file as side-effect-free.

**Comment by JeffWong16** [comment]
> > ```js
> > B.bar = function() {
> >   console.log('a')
> > }
> > ```
> 
> This is a side effect. You incorrectly marked the file as side-effect-free.

Well, I get It.  But why when I use `export default B ` not  `export { B }`  that will not delete  
```
B.bar = function() {
  console.log('a')
}
```
