### ISSUE TITLE
IE8 HMR compatibility

### ISSUE THREAD

**Issue by jerrysu** [webpack/webpack#1025]
The HotModuleReplacement plugin fails to execute in IE8. The first line that results in an error is: https://github.com/webpack/webpack/blob/master/lib/HotModuleReplacement.runtime.js#L19

Apparently, `indexOf` doesn't exist in IE8: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/indexOf#Browser_compatibility

I haven't looked into whether there are any additional incompatibilities, but was wondering what the intended browser compatibility of webpack and/or HotModuleReplacement is?

If IE8 compatibility is intended, then it seems maybe the plugin can provide its own shim for `Array.prototype.indexOf`. Otherwise, if compatibility is not intended, then maybe the module can disable itself in browsers that aren't supported so that people can test in older browsers without having to change any configuration?

**Comment by sokra** [comment]
You should provide a polyfill on application level if you want compatibility.

> Otherwise, if compatibility is not intended, then maybe the module can disable itself in browsers that aren't supported so that people can test in older browsers without having to change any configuration?

yep, we should that.

**Comment by jerrysu** [comment]
I am requiring `es5-shim` in my application, but it seems it doesn't get pulled in until after the HMR runtime is run. I guess loading the polyfill as a separate script tag without webpack would work, but is there a better way to polyfill `es5-shim` that would ensure it is loaded before the HMR runtime? Is this what the `PrefetchPlugin` is?

I'll look into solutions for this in the next few days and see if I can come up with a reasonable PR.

**Comment by SimenB** [comment]
@jerrysu Did you find a solution for this?

**Comment by sokra** [comment]
After some discussion we decided for the following statement regarding IE8:

We don't support IE8 in webpack 2. IE8 is not supported by Microsoft and doesn't get security fixes. We think it's no responsible to allow web developers to build webapps which support IE8. They must break!
