### ISSUE TITLE
What is this file for in output dir?

### ISSUE THREAD

**Issue by Legends** [webpack/webpack#10264]
I've tweaked my webpack.config to spit out the desired output bundles, but one thing is unclear to me:

Using this webpack.config.prod.js (mode: production):

 ```
optimization: {
        minimize: true,
        // runtimeChunk: 'single',
        splitChunks: {
            chunks: 'initial',          
            cacheGroups: {
                defaultVendors: {                  
                    test: /\.js$/,
                    priority: -10
                },               
                styles: {
                    name: 'styles',
                    test: /\.css$/,
                    chunks: 'all',
                    enforce: true,
                },
            }
        }
    },
```

**I get this output:**

![image](https://user-images.githubusercontent.com/966368/72475713-c595ea00-37eb-11ea-912c-75a98bcbb047.png)

You can see the file and its content marked in green color.

Do I need it and what is it for?
If yes, should it be served first?

**Comment by sokra** [comment]
It contains the common modules from "about" and "index". Order is not relavant, but serve it with both entries.
