### ISSUE TITLE
Hot reload not working for samba shared folder

### ISSUE THREAD

**Issue by VirtumartOz** [webpack/webpack#10277]
# Bug report

**What is the current behavior?**
I have a win10 and a freebsd as a dev servers, i use win10 to edit code, it mounts the project root folder from freebsd12 via samba. I have to use freebsd because it performs much better for php + postgresql application, but i'm not suitable to edit php / vue files under freebsd terminal. I really can't leave win10 as daily use and editing code.  and kde or gnome are really not good enough. 
Now when i change some vue code in win10 editor and save, i see the change is reflected in freebsd server, and npm noticed there is change, i see it recompiled , but the page in my browser is not reflected of the change.
in chrome dev console, i see the "keep-alive" __webpack_hmr/client request has the output too, but it only has meaningful output for the first change made by win10, further files changes on win10 are not reflected in browser anymore, it has meaningless output for further changes like this: 
{"h":"28ac7a547ebf20ba2bb3","c":{}}

If i hadn't made changes via win10 editor after npm server started, every single change made by vi editor under freebsd are reflected in npm and browser.  But after i change the file in win10, then it only works for the first time change, further change dont work anymore, it dont work even if i go back to freebsd change the file there(npm failed to notice the change made by vi editor) . Refresh the page doesnt help. 

Only restart npm helps

**If the current behavior is a bug, please provide the steps to reproduce.**

create a nuxt app in freebsd , and install the samba server, configure the app root directory to be able for win10 to connect to . 
start npm in freebsd.
change the files in win10 after mounting the samba directory.  

**What is the expected behavior?**
every change to samba-mounted file made via win10 editor should be reflected in browser without page refresh, not producing meaningless ajax content by HMR

**Other relevant information:**
webpack version:  4.31.0
Node.js version: 6.12.1
Operating System: win10 + freebsd12
Additional tools:

**Comment by abrahamcuenca** [comment]
Are you running freebsd through a virtual machine (or vice versa) or are they two separate boxes? Or are you using WSL?

**Comment by VirtumartOz** [comment]
> Are you running freebsd through a virtual machine (or vice versa) or are they two separate boxes? Or are you using WSL?


they are two physical machine, in the local network

**Comment by VirtumartOz** [comment]
i already moved to debian, it works

**Comment by evilebottnawi** [comment]
Closing, I think it bug not related to webpack, anyway feel free to open new issue if you faced with the same problem
