### ISSUE TITLE
Re-write module requires, completely.

### ISSUE THREAD

**Issue by IngwiePhoenix** [webpack/webpack#1027]
So I am on a journey on finding a smaller alternative to jQuery that works with me. However, some commonJS modules that I package are still using `require("jquery")`. I want to **change** the module they require.

So if we had code like this:

    factory(require("jquery"), require("bootstrap"));

it should be made to actually be:

    factory(require("other-jquery"), require("bootstrap"));

...and then resolve, package, and the like.

Which plugin do I use to change which module is required instead of the original?

Thanks!

**Comment by SimenB** [comment]
http://webpack.github.io/docs/configuration.html#resolve-alias

**Comment by IngwiePhoenix** [comment]
#derp.
