### ISSUE TITLE
Warnings for isomorphic apps

### ISSUE THREAD

**Issue by tomekwi** [webpack/webpack#1028]
Hi, I’m developing the lib [isomorphic-ensure](https://github.com/tomekwi/isomorphic-ensure) to write webpack apps which also 100% work on node.

Everything works smoothly. I only get some warnings from webpack during compilation.

```
Critical dependencies:
15:5-12 require function is used in a way, in which dependencies cannot be statically extracted
15:21-28 require function is used in a way, in which dependencies cannot be statically extracted
26:4-11 require function is used in a way, in which dependencies cannot be statically extracted
```

Here’s the code it references (taken from the readme, marked with `^^^^^^^^`):

> **1) Wire things up.**
> 
> ```js
> if (!require.ensure) require.ensure =
>      ^^^^^^^         ^^^^^^^
>   require('isomorphic-ensure')({loaders: {
>     raw: require('raw-loader'),
>     json: require('json-loader'),
>   }})
> ;
> ```
> 
> 
> **2) Profit!**
> 
> ```js
> require.ensure(['json!babel/package.json', 'raw!./data.xml'], (require) => {
>   // Node modules are supported out of the box:
>   const babelManifest = require('json!babel/package.json');
> 
>   // Before referencing relative paths pass the current location:
>   require.dirname = __dirname;
>   ^^^^^^^
>   const data = require('raw!./data.xml');
> 
>   // Miracles! It works everywhere!
> });
> ```

@sokra I have two questions:

1. Is it a hack, what I’m doing?
2. If not, how to suppress the warnings?

**Comment by sokra** [comment]
``` js
if(typeof require.ensure !== "function")
```

You can take a look at https://github.com/webpack/enhanced-require
It's currently unmaintained because I don't have time to maintain it (webpack takes a lot of my time).

**Comment by tomekwi** [comment]
Thanks, I’ll check out the `typeof` variant as soon as I have the opportunity.

I stumbled upon *enhanced-require* while I was searching for a solution. But the first code example (`var myRequire = ...`) discouraged me. I already had some bad luck with wrapping `require`. Now I’ve dived right into the readme, I’ll give it a shot. Thanks!

**Comment by tomekwi** [comment]
> if(typeof require.ensure !== "function")

This worked like a charm for the first two warnings – thank you @sokra!

The warning for `require.dirname = __dirname;` didn’t go away though. Is it possible to make that “legal” as well somehow? My [previous idea](https://github.com/tomekwi/isomorphic-ensure/blob/0.0.1/Readme.md#usage) was to pass context as a third argument to `require.ensure` – but that tipped *webpack* completely off track.

Unfortunately I haven’t had much luch with *enhanced-require* – probably because I’m transpiling my code with *babel* and that itself wraps `require` calls with some logic.

**Comment by tomekwi** [comment]
> The warning for `require.dirname = __dirname;` didn’t go away though. Is it possible to make that “legal” as well somehow?

@sokra I can’t figure out the reason why *webpack* issues a warning there. I’ve been using this for some time now and I haven’t noticed any problems in spite of the warning.

Is there anything I can do to make sure *webpack* is OK with my code? [Here](https://github.com/tomekwi/isomorphic-ensure/blob/478677d165742cc527c2f5bb108336d87bc8921e/Readme.md#usage) are the usage instructions for reference.

**Comment by sokra** [comment]
Why not passing `dirname` in the init:

``` js
if (typeof require.ensure !== 'function') require.ensure =
  require('isomorphic-ensure')({
    dirname: __dirname,
    loaders: {
      raw: require('raw-loader'),
      json: require('json-loader'),
    }
  });
```

---

Alternativly you can write a webpack plugin to teach it about `require.dirname`.

**Comment by tomekwi** [comment]
> Why not passing dirname in the init:

I was sure `require` is a global function. Overwriting its `.ensure` property would then affect all modules, so it should only be done once per application. And within every file you could pass the context explicitly.

Now I’ve actually checked this in node and read up in the spec, I see it’s local. So I guess that’s the way to go. Thanks for pointing me in the right direction!
