### ISSUE TITLE
ConstPlugin invalidates asm.js code

### ISSUE THREAD

**Issue by ngg** [webpack/webpack#10283]
# Bug report

**What is the current behavior?**

ConstPlugin can change asm.js ("use asm") functions and invalidate them by inserting "false", "true", "undefined" values. In asm.js, using these identifiers are not allowed.

**If the current behavior is a bug, please provide the steps to reproduce.**

I'm currently trying to use https://www.npmjs.com/package/viz.js and compiling that with webpack causes it to no longer be valid asm.js code.
But this can be seen with much smaller codes as well, basically with any const conditional. (`0==0` becomes `true`, `truthy() ? 0 : 1` can become `truthy() ? 0 : undefined`, etc)

**What is the expected behavior?**

I think the best would be to simply disable ConstPlugin inside asm.js functions as it would be much harder to properly inject valid asm.js code there. The Parser's scope could be extended to check for "use asm" expressions just like it checks "use strict", and then ConstPlugin could use that info to skip those parts.

**Other relevant information:**
webpack version: 4.41.5

**Comment by sokra** [comment]
Yep makes sense. Send a PR
