### ISSUE TITLE
Unreachable imports correctly removed by Terser are still in output bundle

### ISSUE THREAD

**Issue by exogen** [webpack/webpack#10281]
# Bug report

**What is the current behavior?**

(FYI I tried searching for an existing issue but only found vaguely similar things, not this exact bug.)

When there is a static conditional containing a `require()` statement, Terser successfully removes it, and webpack does not include the module in its output (this is a good thing!):

```js
// normally this would happen due to DefinePlugin substitution, for example
if (false) {
  defaultAgent = require('https').Agent;
}
```

**However, if there is slight indirection** in the code which still results in it being removed, like so:

```js
function getDefaultAgent() {
  return require('https').Agent;
}

const agent = false ? undefined : getDefaultAgent();
```

Then `https` (and its dependencies) *will* be included in the output bundle, even though Terser correctly removes the entire function and thus the `require` reference. This is confirmed by looking at the output: the assignment becomes simply `agent = void 0`, the function is entirely removed, and nothing references the `https` module – it is only defined and never required. There is no more `require` reference at all in the output. Yet, webpack includes the module anyway.

I noticed this because it ends up pulling in several other dependencies like `stream-http`, `readable-stream`, `buffer`, etc.

**If the current behavior is a bug, please provide the steps to reproduce.**

Here's a repro using a Next.js webpack setup, although I've confirmed that the same thing happens with vanilla webpack@4, and webpack@5 beta.

https://github.com/exogen/test-next-terser-dce

**What is the expected behavior?**

I always thought that webpack's dependency analysis ran after Terser/Uglify's dead code elimination and that's why `if (false) { require(...) }` works correctly.

But evidently, that's not the case. I can't think of any other reason the module would be removed successfully for `if (false)` but not when a function containing a `require()` is removed. Does webpack handle the `if (false)` branches itself before Terser runs? Are there multiple DCE passes? It seems like in the final output, webpack should recognize that a module is now completely unreachable. (This should also have nothing to do with `sideEffects`, as the module is not even imported or referenced in the final output, so it's safe to remove no matter what.)

**Other relevant information:**
webpack version:  4.41.5, 5.0.0-beta.12
Node.js version: v10.13.0
Operating System: macOS

**Comment by sokra** [comment]
Inner-module references (`agent` -> `getDefaultAgent`) are not supported in webpack 4.
They are supported in webpack 5 but not yet for CommonJs require() calls. But this is planned.

**Comment by stof** [comment]
> Does webpack handle the `if (false)` branches itself before Terser runs?

that's indeed happening. webpack performs its own DCE pass (look for `tree shaking` in the issue tracker to find discussions about it). And Terser runs on the output bundle at the end of the process, performing its own DCE pass (but then, at this time, webpack cannot remove modules from the bundle anymore)
