### ISSUE TITLE
v5-beta.12: Many warns: Serializing big strings impacts deserialization performance (consider Buffer instead)

### ISSUE THREAD

**Issue by a-x-** [webpack/webpack#10298]
While webpack generates prod build I see many warnings like this.
<img width="1919" alt="Screenshot 2020-01-25 at 16 35 58" src="https://user-images.githubusercontent.com/6201068/73122023-d33c3400-3f90-11ea-862b-b554bd9bf37e.png">

**Comment by evilebottnawi** [comment]
Please use issue template in future, otherwise issue will be closed, also it is not easy to reproduce some problems, so test repo (with configuration and small examples) allow to use faster find a problem and fix it, thanks

**Comment by sokra** [comment]
Related to terser-webpack-plugin

**Comment by andersk** [comment]
Also happens with mini-css-extract-plugin: webpack-contrib/mini-css-extract-plugin#643.
