### ISSUE TITLE
Enable/Disable plugin for specific entry.

### ISSUE THREAD

**Issue by tommyZZM** [webpack/webpack#10292]
## Feature request

**What is the expected behavior?**

Enable/Disable plugin for specific entry.

**What is motivation or use case for adding/changing the behavior?**

I want to disable webpack.HotModuleReplacementPlugin for some specific entries

**How should this be implemented in your opinion?**

As described

**Are you willing to work on this yourself?**

Not yet.

**Comment by evilebottnawi** [comment]
You can use multi compiler mode, maybe we can implement `test`/`include`/`exclude` options for plugin, but what is use case?
