### ISSUE TITLE
Feature Request: Allow webpack be configured to provide externals in a non-library project

### ISSUE THREAD

**Issue by gerges** [webpack/webpack#1029]
I'm currently using webpack to build a front end application that includes an API and requires a provided SPI (inheriting from a base implementation). I can easily declare the provided SPI as an external with the following config

```
{
    externals : {
        "spi": "commonjs spi" //provided by container
    }
}
```

It would also be quite useful to provided a base SPI implementation, and the apps API as external components (to be used by my front end module loader).

example input
```
//spi_base.js
function SpiBase () {}
SpiBase.prototype.doFoo = function () {doBaseImpl();}

//main.js
var foo = require('spi_base');
```

desired output
```
//main.js
var foo = __webpack_require(1)__;
define("spi_base", __webpack_require(1)__);  // module definition to be consumed by a client-side module loader
```

**Comment by sokra** [comment]
I don't understand it.

**Comment by gerges** [comment]
Sorry @sokra, after some research I think the confusion came from me writing code that was trying to be both an application and library. It's better solved by just splitting up the application and building the whole thing as a library target with multiple entry points. I'll close this.
