### ISSUE TITLE
Change loader matching heuristic in 2.0?

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack#1030]
As far as I understand if you have a loader declaration like

```
loader: 'eslint',
```

this will match to `eslint-loader` unless `eslint` happens to be installed (same goes for `css-loader` and `css`). Interestingly on my system it would match to `eslint-loader` even in this case but on another system it matched to `eslint`.

It might be a good idea to set some stricter conventions here with 2.0. It would be sensible to perform loader lookup in order defined at `resolveLoader.moduleTemplates`.

Related to https://github.com/survivejs/webpack_react/issues/3.

**Comment by sokra** [comment]
I think it's a bug, because normally the order in `moduleTemplate` should be used. Wonder why this doesn't work...

**Comment by bebraw** [comment]
I think this was fixed at some point. The short variant (`eslint`) works reliably now.
