### ISSUE TITLE
webpack typescript definition cause can't extend stats behaviours

### ISSUE THREAD

**Issue by tjx666** [webpack/webpack#10300]
# Bug report

**What is the current behavior?**
Can't extend stats behaviours.

![screenshot_2020-01-26_11-39-00](https://user-images.githubusercontent.com/41773861/73130292-b35c4d00-4030-11ea-8b99-f85ec017508c.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

Just as the screenshot.

**What is the expected behavior?**

No type error

**Other relevant information:**
webpack version:  "@types/webpack": "^4.41.3",
Node.js version: 12.14.1
Operating System: win10pro
Additional tools:

**Comment by sokra** [comment]
Report an issue to `@types/webpack` -> https://github.com/DefinitelyTyped/DefinitelyTyped/
