### ISSUE TITLE
Passing a loader as a function rather than a string

### ISSUE THREAD

**Issue by drew-gross** [webpack/webpack#10302]
## Feature request

Currently, you specify a loader as a string that resolves to a module whose default export is a loader. This is an uncommon interface, and there are very few APIs where strings that represent the names of modules are passed around. Especially now that node supports ES6 modules, I propose adding the ability to `import` (or `require`) a loader directly in the webpack config, or even implement the loader directly in the webpack config.

**What is the expected behavior?**

These 4 ways of supplying a loader should be supported:

```js
const loader1 = require('loader1');
import loader2 from 'loader2');
loader3 = a => a.replace('s1', 's2');

module.exports = env => {
    return {
        entry: { /* ... */ },
        output: { /* ... */ },
        module: {
            rules: [
                {
                    exclude: /node_modules/,
                    test: /\.ext1$/,
                    use: loader1,
                },
                {
                    exclude: /node_modules/,
                    test: /\.ext2$/,
                    use: loader2,
                },
                {
                    exclude: /node_modules/,
                    test: /\.ext3$/,
                    use: loader3,
                },
                {
                    exclude: /node_modules/,
                    test: /\.ext-inline$/,
                    use: a => a.replace('s3', 's4'),
                },
            ],
        },
        resolve: {
            extensions: ['.ext1', '.ext2', '.ext3'],
        },
    };
};
```

**What is motivation or use case for adding/changing the behavior?**

My main motivation was that I was attempting to bundle a library using webpack, where the library I was trying to bundle was a webpack loader. I ran into issues attempting to bundle a library with a default export (as webpack requires it's loaders to have for the strings-as-modules-names API) and after thinking about it for awhile, this seemed like the best solution. Making it possible to bundle libraries with default exports would also work, of course.

This would also have the advantage of pushing the error earlier when the module can't be loaded for any reason, as it would error when the webpack config is evaluated, before any actual webpack code gets ahold of it.

**How should this be implemented in your opinion?**

When the `use` key of a rule is not a `string`, it may be a `function`. If it is, it is treated as though it were already loaded module. No parts of how the module is validate change, the semantics of the module API and requirements for a module to be a valid webpack loader do not change.

**Are you willing to work on this yourself?**
yes

**Comment by sokra** [comment]
There is a loader for that: https://www.npmjs.com/package/simple-functional-loader

But please don't use that.
Put your loader into separate files. You can also reference loaders relative: `use: "./loaders/my-loader.js"`.

**Comment by drew-gross** [comment]
Obviously I would import my loaders, and not actually write them inline inside the webpack config. `simple-functional-loader` looks fine for that, though I can't imagine it's implementation isn't full of hacks.

**Comment by sokra** [comment]
There are a few advantages when loaders are referenced as requests and not passed directly:

* They only have to be loaded when used
  * e. g. when using persistent caching loaders don't have to be loaded when modules are cached.
  * loaders do not have to be loaded when rules doesn't match any source file
* loader path is used a module identifier
  * Different rules may apply the same loader which lead to the same module
  * Persistent caching can cache modules based on this identifier
