### ISSUE TITLE
Dynamic import with variable + externals config not working

### ISSUE THREAD

**Issue by mrodal** [webpack/webpack#10309]
# Bug report

**What is the current behavior?**
I'm trying to use a dynamic import that uses a variable, and at the same time leave all these modules as external libraries, so I'm doing this:

```import(`library/${module}.js`);```

And my Webpack externals config is:

`externals : /library\/.*\.js/`

And right now, its not leaving those modules as external and its bundling them

If I do ```import(`library/specificModule.js`);``` it works even with the same regex on the externals config.

Looks like the externals config doesn't apply for the import() with variables, because I also tried using a function as the externals config and setting up a brakpoint inside it, and it doesn't hit for those files.

**If the current behavior is a bug, please provide the steps to reproduce.**
Take any library and import its modules with something like ```import(`library/${module}.js`);```
Add the regex to the externals webpack config
Run build
The modules are bundled

**What is the expected behavior?**
I think it should leave all those modules as external modules when using the variable on the import

**Other relevant information:**
webpack version:  4.23.1
Node.js version: 10.11.0
Operating System: Windows 10
Additional tools: -
Reopened close issue https://github.com/webpack/webpack/issues/8377

**Comment by miraage** [comment]
Dynamic expressions in `import()` have [a special treatment](https://webpack.js.org/api/module-methods/#dynamic-expressions-in-import).

> For example, import(`./locale/${language}.json`) will cause every .json file in the ./locale directory to be bundled into the new chunk.

I suggest you to write `externals` as a function and try to find out, what exactly is passed there. My assumption is that `externals` receives some part of the import statement, instead of the full path.

**Comment by sokra** [comment]
I think dynamic expressions are not supported together with externals. Dynamic expressions depend on reading the directory to figure out all possible files, which is not possible with exterals.

**Comment by sokra** [comment]
It's may possible to implement this and pass the dynamic part along. For this we would need something like `ExternalContextModule`, which probably only works for CommonJs and AMD externals.

**Comment by mrodal** [comment]
@sokra Nice! Do you think that this behaviour should be documented? Also, how likely do you think it is that this feature is implemented?

**Comment by shrinktofit** [comment]
Bump! I have same problem!

**Comment by evilebottnawi** [comment]
@shrinktofit What problem do you have?

**Comment by shrinktofit** [comment]
Dynamic import modules marked as `externals` not working:
```json
// webpack.config.js
{
    externals: "<files-as-externals>"
}
```

```js
let moduleName = "<files-as-externals>";
import(moduleName) // Runtime: module not found

import("<files-as-externals>") // This works
```

**Comment by ScriptedAlchemy** [comment]
Use a magic comment to have the webpack parser ignore it. I don't believe webpack can work with a fully variable based import. Webpack doesn't know why the variable will be. So it must account for all variances (the entire file systems)

**Comment by abdallaoui-dev** [comment]
the same problem
--v   webpack 5
in-this-file.js
function loadFile(filename) {
  import(/*webpackIgnore: true*/ `/js/${filename}`).then(...)
  throws Uncaught (in promise) Error: Cannot find module '/js/other-file.js'
  at webpackEmptyContext (...)
}
setTimeout(() => loadFile("other-file.js"), 1000)

**Comment by abdallaoui-dev** [comment]
the same problem
--v webpack 5
in-this-file.js
```
function loadFile(filename) {
   import(/*webpackIgnore: true*/ /js/${filename}).then(...)
   throws Uncaught (in promise) Error: Cannot find module '/js/other-file.js'
   at webpackEmptyContext (...)
}
setTimeout(() => loadFile("other-file.js"), 1000)
```

**Comment by abdallaoui-dev** [comment]
the same problem
--v webpack 5
in-this-file.js
```
function loadFile(filename) {
  import(/*webpackIgnore: true*/ `/js/${filename}`).then(...)
  throws Uncaught (in promise) Error: Cannot find module '/js/other-file.js'
  at webpackEmptyContext (...)
}
setTimeout(() => loadFile("other-file.js"), 1000)
```
