### ISSUE TITLE
webpack loader api sourceMap parameter  is undefined

### ISSUE THREAD

**Issue by Zuckjet** [webpack/webpack#10316]
# Bug report

**What is the current behavior?**
when I use webpack loader api to write a loader, the source map parameter is undefined.
I refer the [doc](https://webpack.js.org/api/loaders/) here.

my webpack loader is under `my-webpack-loader` folder , when I run `npm run build`, the terminate will show undefined whic refers to  sourceMap parameter

**If the current behavior is a bug, please provide the steps to reproduce.**
I have created a minimum [repo](https://github.com/Zuckjet/webpack-test) for reproducing this problem

**What is the expected behavior?**

**Other relevant information:**
webpack version:  4.41.5
Node.js version: v12.13.1
Operating System: macOS High Sierra
Additional tools:

```
module.exports = function(content, map, meta) {
  console.log(map) ;     --   sourcemap is undefined
  return someSyncOperation(content);
};
```

**Comment by evilebottnawi** [comment]
Because an other loader don't send a source map, please provide configuration

**Comment by Zuckjet** [comment]
@evilebottnawi  my webpack config file:
```
module.exports = {
    mode: 'development',
    devtool: 'source-map',
    entry: './src/index.js',
    output: {
        filename: './bundle.js'
    },
    devServer: {
        publicPath: '/dist',
    },
    module: {
        rules: [{
            test: /\.js$/,
            use: {
                loader: 'my-webpack-loader',
            }
        }]
    }
}
```

**Comment by Zuckjet** [comment]
Thanks, I understand what you mean. This issue should be closed.
