### ISSUE TITLE
Feature request: Show a listing of all compiled-in files, sorted by size.

### ISSUE THREAD

**Issue by IngwiePhoenix** [webpack/webpack#1032]
I dont know how you others feel about this, but have you been wondering what takes most of the size in your WebPack bundle? I myself have been trying to minimize the output of my file, by using just the components I need. So instead of using `require("bootstrap")`, I'd go about and write

```javascript
require("bootstrap/src/js/alert");
require("bootstrap/src/js/modal");
// and on and on...
```

Now, my next step is to figure out what takes up which space. For that purpose, it'd be awesome to obtain a listing of the compiled-in files, sorted by size.

**Comment by at0g** [comment]
Did you take a look at the stats option:
http://webpack.github.io/docs/node.js-api.html

**Comment by sokra** [comment]
with `--display-modules --sort-modules-by size` you can even to this on CLI.

**Comment by IngwiePhoenix** [comment]
I did look into the docs, but I must have overseen this option. Thank you, it now sorts just as I want. :)
