### ISSUE TITLE
ERR_CONNECTION / CORS Request did not succeed

### ISSUE THREAD

**Issue by marcoippolito** [webpack/webpack#10329]
"webpack": "^4.41.5"

# Bug report

I already asked questions in vue.js forum, in stackoverflow, and in other github reports.

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

      
    https://github.com/marcoippolito/testproject

Description of the problem:

I created a brand new tiny webapp with vue cli, so without adding anything, apart from what the empty vue-cli scaffolding brings:

    (base) marco@pc:~/vueMatters/testproject$ npm run serve

    > testproject@0.1.0 serve /home/marco/vueMatters/testproject
    > vue-cli-service serve

    INFO Starting development server...
    98% after emitting CopyPlugin

    DONE Compiled successfully in 1409ms 8:14:46 PM 

And get this error message : https://drive.google.com/open?id=10GcVFmqNVGRjox3wklJtcrAkIWM3kOp8

    "GET https://localhost/sockjs-node/info?t=1580228998416 net::ERR_CONNECTION_REFUSED" 

Using firefox as web browser, I get this error message: https://drive.google.com/open?id=1l6USIHrbHl6kBcQtormXplOgx0J653ko

    "Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at 
    https://localhost/sockjs-node/info?t=1580304400023. (Reason: CORS request did not succeed)."

Looking at Mozilla Developer explanation:
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSDidNotSucceed?utm_source=devtools&utm_medium=firefox-cors-errors&utm_campaign=default

    "What went wrong?

    The HTTP request which makes use of CORS failed because the HTTP connection failed at 
    either the network or protocol level. The error is not directly related to CORS, but is a fundamental
    network error of some kind.

    In many cases, it is caused by a browser plugin (e.g. an ad blocker or privacy protector) blocking 
    the request.

    Other possible causes include:

    Trying to access an https resource that has an invalid certificate will cause this error.
    Trying to access an http resource from a page with an https origin will also cause this error.
    As of Firefox 68, https pages are not permitted to access http://localhost, although this may be    
    changed by Bug 1488740.
    The server did not respond to the actual request (even if it responded to the Preflight request).
    One scenario might be an HTTP service being developed that panicked without returning any
    data.
"

In order to understand where the problem could lie, I checked various aspects:

- Checked the TLS Certificates with https://www.digicert.com/help/ : and the result is:
    " TLS Certificate has not been revoked.
    TLS Certificate expires soon. The primary TLS Certificate expires on February 28, 2020 (30 days
    remaining)
    Certificate Name matches ggc.world
    TLS Certificate is correctly installed " 

- curled the url both from within the PC-Server, and from a laptop:

  -From within the PC-Server:

    (base) marco@pc:~$ curl -Iki https://localhost/sockjs-node/info?t=1580397983088
    HTTP/2 405
    server: nginx/1.14.0 (Ubuntu)
    date: Fri, 31 Jan 2020 08:19:02 GMT
    allow: OPTIONS, GET

    (base) marco@pc:~/vueMatters/testproject$ curl -vk https://localhost/sockjs-
    node/info?t=1580397983088

        Trying ::1…
        TCP_NODELAY set
        connect to ::1 port 443 failed: Connection refused
        Trying 127.0.0.1…
        TCP_NODELAY set
        Connected to localhost (127.0.0.1) port 443 (#0)
        ALPN, offering h2
        ALPN, offering http/1.1
        successfully set certificate verify locations:
        CAfile: /etc/ssl/certs/ca-certificates.crt
        CApath: /etc/ssl/certs
        TLSv1.3 (OUT), TLS handshake, Client hello (1):
        TLSv1.3 (IN), TLS handshake, Server hello (2):
        TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
        TLSv1.3 (IN), TLS handshake, Unknown (8):
        TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
        TLSv1.3 (IN), TLS handshake, Certificate (11):
        TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
        TLSv1.3 (IN), TLS handshake, CERT verify (15):
        TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
        TLSv1.3 (IN), TLS handshake, Finished (20):
        TLSv1.3 (OUT), TLS change cipher, Client hello (1):
        TLSv1.3 (OUT), TLS Unknown, Certificate Status (22):
        TLSv1.3 (OUT), TLS handshake, Finished (20):
        SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
        ALPN, server accepted to use h2
        Server certificate:
        subject: CN=ggc.world
        start date: Nov 30 11:22:10 2019 GMT
        expire date: Feb 28 11:22:10 2020 GMT
        issuer: C=US; O=Let’s Encrypt; CN=Let’s Encrypt Authority X3
        SSL certificate verify ok.
        Using HTTP2, server supports multi-use
        Connection state changed (HTTP/2 confirmed)
        Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
        TLSv1.3 (OUT), TLS Unknown, Unknown (23):
        TLSv1.3 (OUT), TLS Unknown, Unknown (23):
        TLSv1.3 (OUT), TLS Unknown, Unknown (23):
        Using Stream ID: 1 (easy handle 0x559bc64c5580)
        TLSv1.3 (OUT), TLS Unknown, Unknown (23):

        GET /sockjs-node/info?t=1580397983088 HTTP/2
        Host: localhost
        User-Agent: curl/7.58.0
        Accept: /

        TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
        TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
        TLSv1.3 (IN), TLS Unknown, Certificate Status (22):
        TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
        TLSv1.3 (IN), TLS Unknown, Unknown (23):
        Connection state changed (MAX_CONCURRENT_STREAMS updated)!
        TLSv1.3 (OUT), TLS Unknown, Unknown (23):
        TLSv1.3 (IN), TLS Unknown, Unknown (23):
        < HTTP/2 200
        < server: nginx/1.14.0 (Ubuntu)
        < date: Fri, 31 Jan 2020 14:00:47 GMT
        < content-type: application/json; charset=UTF-8
        < access-control-allow-origin: *
        < vary: Origin
        < cache-control: no-store, no-cache, no-transform, must-revalidate, max-age=0
        < strict-transport-security: max-age=31536000
        <
        Connection #0 to host localhost left intact

  -From a laptop:

    (base) marco@marco-U36SG:~$ curl -Iki https://ggc.world/sockjs-node/info?t=1580397983088
    HTTP/1.1 405 Method Not Allowed
    Server: nginx/1.14.0 (Ubuntu)
    Date: Fri, 31 Jan 2020 09:34:59 GMT
    Connection: keep-alive
    Allow: OPTIONS, GET

    (base) marco@marco-U36SG:~$ curl -vk https://ggc.world/sockjs-node/info?t=1580397983088

        Trying 2.36.58.214:443…
        TCP_NODELAY set
        Connected to ggc.world (2.36.58.214) port 443 (#0)
        ALPN, offering http/1.1
        successfully set certificate verify locations:
        CAfile: /home/marco/anaconda3/ssl/cacert.pem
        CApath: none
       TLSv1.3 (OUT), TLS handshake, Client hello (1):
        TLSv1.3 (IN), TLS handshake, Server hello (2):
        TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
        TLSv1.3 (IN), TLS handshake, Certificate (11):
        TLSv1.3 (IN), TLS handshake, CERT verify (15):
        TLSv1.3 (IN), TLS handshake, Finished (20):
        TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
        TLSv1.3 (OUT), TLS handshake, Finished (20):
        SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
        ALPN, server accepted to use http/1.1
        Server certificate:
        subject: CN=ggc.world
        start date: Nov 30 11:22:10 2019 GMT
        expire date: Feb 28 11:22:10 2020 GMT
        issuer: C=US; O=Let’s Encrypt; CN=Let’s Encrypt Authority X3
        SSL certificate verify ok.

        GET /sockjs-node/info?t=1580397983088 HTTP/1.1
        Host: ggc.world
        User-Agent: curl/7.65.2
        Accept: /

        TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
        TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
        old SSL session ID is stale, removing
        Mark bundle as not supporting multiuse
        < HTTP/1.1 200 OK
        < Server: nginx/1.14.0 (Ubuntu)
        < Date: Fri, 31 Jan 2020 14:04:11 GMT
        < Content-Type: application/json; charset=UTF-8
        < Transfer-Encoding: chunked
        < Connection: keep-alive
        < Access-Control-Allow-Origin: *
        < Vary: Origin
        < Cache-Control: no-store, no-cache, no-transform, must-revalidate, max-age=0
        < Strict-Transport-Security: max-age=31536000
        <
        Connection #0 to host ggc.world left intact
        {“websocket”:true,“origins”:[":"],“cookie_needed”:false,“entropy”:1587194190}

- This is the output of the "Network" tab : 
    https://drive.google.com/open?id=1QJMe8FEBrEuWacHWeJ_TQegMkF0v68AY 

- This is the "view source" of the html page:

    <!DOCTYPE html>
    <html lang="en">
      <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width,initial-scale=1.0">
        <link rel="icon" href="favicon.ico">
        <title>testproject</title>
      <link href="js/app.js" rel="preload" as="script"><link href="js/chunk-vendors.js" rel="preload" 
    as="script"></head>
      <body>
        <noscript>
          <strong>We're sorry but testproject doesn't work properly without JavaScript enabled. Please 
    enable it to continue.</strong>
        </noscript>
        <div id="app"></div>
        
      <script type="text/javascript" src="js/chunk-vendors.js"></script><script type="text/javascript" src="js/app.js">  
    </script></body>
    </html>

- This is the result of the "localhost" word search in app.js:

    https://drive.google.com/open?id=11QpJKjd4PLKNMnO7m2utCJ9PrzO8Oyji  :

        /***/ }),

        /***/ 1:
/*!********************************************************************************************************************************************************************!*\
          !*** multi (webpack)-dev-server/client?http://localhost (webpack)/hot/dev-server.js (webpack)-
    dev-server/client?http://192.168.1.7:8080/sockjs-node ./src/main.js ***!
  \********************************************************************************************************************************************************************/
        /*! no static exports found */
        /***/ (function(module, exports, __webpack_require__) {

        __webpack_require__(/*! /home/marco/vueMatters/testproject/node_modules/webpack-dev-
    server/client   
        /index.js?http://localhost */"./node_modules/webpack-dev-server/client/index.js?http:
    //localhost");
        __webpack_require__(/*! /home/marco/vueMatters/testproject/node_modules/webpack
    /hot/dev-server.js  
        */"./node_modules/webpack/hot/dev-server.js");
        __webpack_require__(/*! /home/marco/vueMatters/testproject/node_modules/webpack-dev-
    server/client 
        /index.js?http://192.168.1.7:8080/sockjs-node */"./node_modules/webpack-dev-server/client
    /index.js?http:  
        //192.168.1.7:8080/sockjs-node");
        module.exports = __webpack_require__(/*! ./src/main.js */"./src/main.js");
        /***/ })
        /******/ });

- These are the results of the "localhost" word search in chunk-vendors.js :  

  - https://drive.google.com/open?id=13EPYKgb7Vv4DHOTxD0jxYk_CbDDrJkMy
  - https://drive.google.com/open?id=1UjWDsPyT-87GF4WJhVr-UhzOFGiBW8tH
  - https://drive.google.com/open?id=1eq5pWm51sjCYQkIaQn5GZ6uEmrmS36Od
  - https://drive.google.com/open?id=19QzxljB37HH5cvJ0jffdyX97u9hlBDsV

In this GitHub repository you can find all the related files: https://github.com/marcoippolito/testproject

The sudo nano /etc/nginx/conf.d/default.conf is the following: 

    server {
        listen 443 ssl http2 default_server;
        server_name ggc.world;

        ssl_certificate /etc/ssl/certs/chained.pem;
        ssl_certificate_key /etc/ssl/private/domain.key;
        ssl_session_timeout 5m;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
        ssl_ciphers EECDH+CHACHA20:EECDH+CHACHA20-
  draft:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:! 
        MD5;
          ssl_prefer_server_ciphers on;
          ssl_session_cache shared:SSL:50m;
          ssl_dhparam /etc/ssl/certs/dhparam.pem;
          #ssl_stapling on;
          #ssl_stapling_verify on;

        access_log /var/log/nginx/ggcworld-access.log combined;

        add_header Strict-Transport-Security "max-age=31536000";
        location = /favicon.ico { access_log off; log_not_found off; }
        location / {
            proxy_pass http://127.0.0.1:8080;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }

    server {
        listen 80 default_server;
        listen [::]:80 default_server;
        error_page 497 https://$host:$server_port$request_uri;
        server_name www.ggc.world;
        return 301 https://$server_name$request_uri;

        access_log /var/log/nginx/ggcworld-access.log combined;

        add_header Strict-Transport-Security "max-age=31536000";
        location = /favicon.ico { access_log off; log_not_found off; }
        location / {
            proxy_pass http://127.0.0.1:8080;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }

    # https://www.nginx.com/blog/nginx-nodejs-websockets-socketio/
    # https://gist.github.com/uorat/10b15a32f3ffa3f240662b9b0fefe706 
    # http://nginx.org/en/docs/stream/ngx_stream_core_module.html

    upstream websocket {
        ip_hash;
        server localhost:3000;
    }

    server {
        listen       81;
        server_name  ggc.world www.ggc.world;

        #location / {
        location ~ ^/(websocket|websocket\/socket-io) {
            proxy_pass http://127.0.0.1:4201;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header X-Forwared-For $remote_addr;
            proxy_set_header Host $host;

            proxy_redirect off;
            proxy_set_header X-Real-IP $remote_addr;
        }

    }
    # https://stackoverflow.com/questions/40516288/webpack-dev-server-with-nginx-proxy-pass

**What is the expected behavior?** : no ERR_CONNECTION

**Other relevant information:**
webpack version:  "webpack": "^4.41.5"
Node.js version: node -v v12.10.0
Operating System: Ubuntu 18.04.03 Server Edition
Additional tools:
  - npm -v 6.13.6 
  - webpack-cli@3.3.10
 - nginx -v nginx version: nginx/1.14.0 (Ubuntu)

Looking forward to your kind help.
Marco

**Comment by evilebottnawi** [comment]
Please open issue in `vue-cli`

**Comment by marcoippolito** [comment]
@evilebottnawi Are you 100% sure it's a problem of vue-cli? I'm going to open issue in vue-cli, but if they bounced me back here, I will definetely open it again

**Comment by marcoippolito** [comment]
@evilebottnawi I reported the problem in vue-cli GitHub page: https://github.com/vuejs/vue-cli/issues/5129  
Looking forward a joint effort and help

**Comment by appsparkler** [comment]
Hi @marcoippolito 


It works fine on Firefox on Ubuntu:

![image](https://user-images.githubusercontent.com/12084821/73602792-3c2e3800-459f-11ea-98ee-fe4f8692cd67.png)

**Comment by marcoippolito** [comment]
Hi @appsparkler 

 I stopped nginx server, and executed npm run serve:  

    (base) marco@pc:~/vueMatters/testproject$ sudo systemctl stop nginx
    [sudo] password for marco: 
    (base) marco@pc:~/vueMatters/testproject$ sudo systemctl status nginx
    ● nginx.service - A high performance web server and a reverse proxy server
       Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
       Active: inactive (dead) since Sun 2020-02-02 09:58:36 CET; 6s ago
         Docs: man:nginx(8)
      Process: 4359 ExecStop=/sbin/start-stop-daemon --quiet --stop --retry QUIT/5 --pidfile  
    /run/nginx.pid (code=exited, status=0/SUCCESS)
      Process: 983 ExecStart=/usr/sbin/nginx -g daemon on; master_process on; (code=exited,  
    status=0/SUCCESS)
      Process: 872 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, 
    status=0/SUCCESS)
     Main PID: 1001 (code=exited, status=0/SUCCESS)

    Feb 02 09:18:32 pc systemd[1]: Starting A high performance web server and a reverse proxy 
    server...
    Feb 02 09:18:33 pc systemd[1]: Started A high performance web server and a reverse proxy 
    server.
    Feb 02 09:58:36 pc systemd[1]: Stopping A high performance web server and a reverse proxy 
    server...
    Feb 02 09:58:36 pc systemd[1]: Stopped A high performance web server and a reverse proxy 
    server.
    (base) marco@pc:~/vueMatters/testproject$ npm run serve

    > testproject@0.1.0 serve /home/marco/vueMatters/testproject
    > vue-cli-service serve

     INFO  Starting development server...
    98% after emitting CopyPlugin

     DONE  Compiled successfully in 986ms                                                                                                                                                                         
    9:58:54 AM 

      App running at:
      - Local:   http://localhost:8080 
      - Network: http://192.168.1.7:8080

      Note that the development build is not optimized.
      To create a production build, run npm run build.

    But still get the error in Firefox: "Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8080/sockjs-node/info?t=1580634450627. (Reason: CORS request did not succeed)." 
![sockejsErrorWithoutNginx02](https://user-images.githubusercontent.com/3073209/73605898-8534bb00-45a4-11ea-824a-0b92810ad9ba.jpg)

![sockejsError-FireFoxVersion01](https://user-images.githubusercontent.com/3073209/73605947-29b6fd00-45a5-11ea-92d5-64509fc11507.jpg)


And in Google Chrome the error: "GET http://localhost:8080/sockjs-node/info?t=1580634002894 net::ERR_CONNECTION_REFUSED" : 
![sockejsErrorWithoutNginx01](https://user-images.githubusercontent.com/3073209/73605899-9382d700-45a4-11ea-865f-db0f34d024c1.jpg)

![sockejsError-GoogleChromeVersion01](https://user-images.githubusercontent.com/3073209/73605955-350a2880-45a5-11ea-92d3-270677ef343a.jpg)

**Comment by appsparkler** [comment]
Hi @marcoippolito 
Please see the screenshots from my Ubuntu.  Note that it is not Ubuntu server.  Maybe you are facing this issue due to Ubuntu Server OS.


# Firefox
![image](https://user-images.githubusercontent.com/12084821/73606107-cb9e1000-45cc-11ea-9d77-d8555935ac86.png)

# Chrome
![image](https://user-images.githubusercontent.com/12084821/73606139-030cbc80-45cd-11ea-86aa-2920cf90b246.png)

**Comment by marcoippolito** [comment]
@appsparkler I do not understand... might it be an issue related to the Ubuntu installed in the PC? 

    (base) marco@pc:~$ vue info

    Environment Info:

      System:
        OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
        CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
      Binaries:
        Node: 12.10.0 - ~/.nvm/versions/node/v12.10.0/bin/node
        Yarn: 2.0.0-rc.27 - ~/.nvm/versions/node/v12.10.0/bin/yarn
        npm: 6.13.6 - ~/.nvm/versions/node/v12.10.0/bin/npm
      Browsers:
        Chrome: Not Found
        Firefox: Not Found
      npmGlobalPackages:
        @vue/cli: 4.1.2
 
I checked also the add-on installed in Google Chrome: 
![sockejsError-GoogleChromeAddOn01](https://user-images.githubusercontent.com/3073209/73606421-5c172900-45aa-11ea-9817-a48fc01ef523.jpg)
and the installed add-on in FireFox:
![sockejsError-FireFoxAddOn01](https://user-images.githubusercontent.com/3073209/73606474-e8295080-45aa-11ea-810a-c39d4c135cdb.jpg)

So... what kind of issue might be related to the specific Ubuntu OS Server Edition installed in the PC?

**Comment by appsparkler** [comment]
Yes @marcoippolito 

In the information provided; your OS is  **Ubuntu 18.04.03 Server Edition**.  This may be the problem.  

You can install **Oracle VM Virtual Machine** and load an Ubuntu Desktop image.  Then clone your repository, install the node_modules and start the server (i.e npm serve or yarn serve).  If this works then the issue may be related to **Ubuntu 18.04.03 Server Edition** OS.

**Comment by marcoippolito** [comment]
@appsparkler 
I'm using Ubuntu Server Edition in my development machine because I need to use an environment as close as possible to the production environment.

To me it's not clear why a Server Edition should interfere with sockjs-node if, opening in the browser the files before the ERR_CONNECTION failures I read, when searcing for sockjs-node and use of localhost, references to webpack:

![sockejsError17](https://user-images.githubusercontent.com/3073209/73639498-cdb7ab80-466c-11ea-8fab-9462232652cf.jpg)

Anyway, I'm going to post an issue in Ubuntu Server Edition's platform, referring to this github's issue and your hypothesis about a bug/problem related to the Ubuntu 18.04.03 Server Edition.

And I will keep you informed about the results in other forums

**Comment by marcoippolito** [comment]
@appsparkler 

In the PC I installed ex-novo Ubuntu 18.04.3 Desktop and I verified that the problem disappeared.

I ran the same tiny webapp in both laptop and pc, and using localhost and the ip-address both from within the laptop/PC and from the other device (PC/laptop) gave no error. I reported everything here
https://askubuntu.com/questions/1207812/webapp-fails-with-neterr-connection-refused-with-ubuntu-18-04-4-server-edition

According to you, what kind of problems/missing parts/lacking features or whatever the Ubuntu 18.04.4 Server Edition could have compared to the Ubuntu 18.04.4 Desktop Edition? 
It would be great if we could give to the Ubuntu's people some hints/suggestions and help in solving this problem.

**Comment by appsparkler** [comment]
Hi @marcoippolito ,

> According to you, what kind of problems/missing parts/lacking features or whatever the Ubuntu 18.04.4 Server Edition could have compared to the Ubuntu 18.04.4 Desktop Edition?

Not sure about this.  Lets hope someone responds with a solution in the **askubuntu** forum.  Please update this discussion if you get any info.  

Good Luck...
