### ISSUE TITLE
Latest version 4.41.5 freezes on compile

### ISSUE THREAD

**Issue by danrostron** [webpack/webpack#10332]
# Bug report

**What is the current behavior?**

Just updated to the latest webpack, 4.41.5 and on compile my Typescript app now freezes. On displaying progress I see that it outputs this:

70% finish module graph FlagDependencyExportsPlugin

And gets stuck at this point. No errors. Any ideas why? How can I output errors?

**If the current behavior is a bug, please provide the steps to reproduce.**

Run a typescript compile task using a config file:
npx webpack --config webpack.config.js --entry ./source/ts/Main.ts --display-error-details --progress

**What is the expected behavior?**
I expect it should compile without issues as per previous release, 4.41.4.

**Other relevant information:**
webpack version:  4.41.5
Node.js version: v6.11.2
Operating System: MacOS High Sierra 10.13.6

**Comment by evilebottnawi** [comment]
Please create reproducible test repo

**Comment by legendcity** [comment]
Same problem, freezes on `70% finish module graph FlagDependencyExportsPlugin` - 100cpu.

Switched back,  4.41.4 work well.

**Comment by evilebottnawi** [comment]
Please create reproducible test repo
