### ISSUE TITLE
webpack can't find module vscode, 'vscode-debugadapter', and 'vscode-debugprotocol'

### ISSUE THREAD

**Issue by paulo-fernando-silva** [webpack/webpack#10338]
I also asked on stackoverflow:
https://stackoverflow.com/questions/60024640/

The issue is that web pack complains about not being able to find a module that is right there in the dependencies and therefore in node_modules.

Here's a patch that can be applied to the webpack-sample from vscode to reproduce the issue:
https://pastebin.com/peqvJ1Wt

Here's the sample:
https://github.com/microsoft/vscode-extension-samples/tree/master/webpack-sample

Any ideas on how to fix this?
Thanks

**Comment by evilebottnawi** [comment]
Please open issue in `vscode-extension-samples` repo

Please use the issue template in the future

**Comment by paulo-fernando-silva** [comment]
errm... They told me to ask it here: 
https://github.com/microsoft/vscode-extension-samples/issues/249

**Comment by evilebottnawi** [comment]
Can't reproduce problem, do you use yarn/npm? What is version? What is environment? Therefore, we ask you to use the issue template

**Comment by paulo-fernando-silva** [comment]
Sorry about that. I'm using npm 6.4.1, I'm on macOS, anything else I can add?

**Comment by evilebottnawi** [comment]
Can you provide reproducible test repo? I want to look at full structure and configuration

**Comment by paulo-fernando-silva** [comment]
[webpack-sample.zip](https://github.com/webpack/webpack/files/4154610/webpack-sample.zip)
I've attached the project that repros this for me.
It's basically the vscode webpack example, with one extra package added and code that uses that package.

The steps to reproduce it are
> npm i
> npm run webpack

It should install the packages, complain about a vulnerability (they need to update their samples), and the 2nd step complains about not being able to find the package.

Let me know if this is helpful. Thanks.

**Comment by evilebottnawi** [comment]
Thanks, I will look at that in near future and leave feedback

**Comment by evilebottnawi** [comment]
You can see what problem from `ts-loader` (from `ts`):

```
[tsl] ERROR in /home/evilebottnawi/IdeaProjects/webpack-sample/src/math.ts(10,31)
      TS2307: Cannot find module 'vscode-debugprotocol'.
```

You can comment:
```
compilerOptions: {
  "module": "es6" // override `tsconfig.json` so that TypeScript emits native JavaScript modules.
}
```

And all works fine, looks you need specify all options, you can open an issue in `ts-loader` repo or just create two configuration.

**Comment by paulo-fernando-silva** [comment]
Thank you for your help! That seems to work. I'll check with the ts-loader people next. 😅
