### ISSUE TITLE
Webpack v4.41.5 hangs on recursive re-export

### ISSUE THREAD

**Issue by asapach** [webpack/webpack#10349]
# Bug report

**What is the current behavior?**
When a module contains recursive re-export webpack silently hangs in what seems to be perpetual loop.

**If the current behavior is a bug, please provide the steps to reproduce.**
Add `src/index.js` and run `webpack`:
```js
export * from "./index.js";
export const foo = "bar";
```
Notice that the command hangs forever. Attaching a debugger points to `FlagDependencyExportsPlugin`.

**What is the expected behavior?**
Version 4.41.4 seems to work fine and produces a valid bundle.
This might be related to #10332

**Other relevant information:**
webpack version: 4.41.5
Node.js version: v12.14.1
Operating System: Windows 10
Additional tools:

**Comment by evilebottnawi** [comment]
Can you try master?

**Comment by asapach** [comment]
I've applied a patch from #10344 and it seems to address it.
