### ISSUE TITLE
Dynamic import not working as expected?

### ISSUE THREAD

**Issue by kumaresan-subramani** [webpack/webpack#10342]
# Bug report

I have import some of my modules dynamically based on button click, i have used like below"

```
import { Button } from '@syncfusion/ej2-buttons';

// Initialize Button component.
let button: Button = new Button({ content: 'Button' });

// Render initialized Button.
button.appendTo('#element');

document.getElementById('element').addEventListener("click", function(){
  check();
});

async function check() {
import("@syncfusion/ej2-grids").then((Grid) => {
  debugger
  console.log(Grid);
});
}
```

my webpack config file:

```
const path = require("path");
const UglifyJsPlugin = require("uglifyjs-webpack-plugin");

module.exports = {
  mode: "development",
  entry: {
    "src/app/bundle": "./src/app/index.ts"
  },
  output: {
    publicPath: "/js/",
    filename: "src/app/bundle.js"
  },
  devtool: "none",
  module: {
    rules: [
      {
        loader: "ts-loader",
        exclude: /node_modules/
      }
    ]
  },

  resolve: {
    extensions: [".ts", ".js"]
  }
};
```

when i compile and ru my application it throws below error

![image](https://user-images.githubusercontent.com/36756050/73812752-edcda300-4803-11ea-9feb-8b3dc07998c0.png)

**What is the current behavior?**
Throws error

**If the current behavior is a bug, please provide the steps to reproduce.**

- clone sample - https://github.com/kumaresan-subramani/dynamic-import/blob/master/webpack.config.js
- run `npm i`
- gulp compile
- gulp start

Then click button in browser, you will see reported error in my console.

**What is the expected behavior?**

Dynamic module should load properly

**Other relevant information:**
webpack version:  

>     "typescript": "3.7.5",
>     "uglifyjs-webpack-plugin": "^2.0.1",
>     "webpack": "^4.29.6",
>     "webpack-cli": "*",
>     "webpack-stream": "^5.2.1"

Node.js version:  10.15.1
Operating System:  windows 10
Additional tools:

**Comment by sokra** [comment]
Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md).

**Comment by kumaresan-subramani** [comment]
@sokra , this is not support request, i have followed your docs and guideline but it throws error so that i have raised query here

**Comment by aphillipo** [comment]
I have a feeling this happens because resolve.extensions is NOT correctly followed by dynamic imports. Very fruistrating as I've spent two days trying various incantations to make this work.

You can work around this with magic comments like so:
 
/* webpackInclude: /\.(ts|js)$/ */

Surely webpack should be resolving dynamic imports with resolve.extensions without the need to duplicate effort like this?
