### ISSUE TITLE
Some chunks doesnt get included in HTML when disabling name in splitChunks

### ISSUE THREAD

**Issue by finmavis** [webpack/webpack#10340]
# Bug report

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**
When using config like below:
```
optimization: {
  splitChunks: {
    chunks: 'all',
    name: false,
  },
}
```

Vendor chunk doesnt get included in the HTML.

For example, the generated file would look like below:

```
2.0eeefc2c.chunk.js -> This is the vendor chunks
3.e8d3cd1b.chunk.js 
index.html
main.7171a389.chunk.css
main.a1bf2ab0.chunk.js
runtime-main.e6fd4d77.bundle.js
```

The generated html would like below:

```
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Webpack Boilerplate</title>
    <link href="main.7171a389.chunk.css" rel="stylesheet">
</head>

<body>
    <h1>Webpack boilerplate</h1>
    <!-- why it doesnt get included in here? -->
    <script type="text/javascript" src="runtime-main.e6fd4d77.bundle.js"></script>
    <script type="text/javascript" src="main.a1bf2ab0.chunk.js"></script>
</body>
</html>
```

But, if I remove the name option like below:

```
optimization: {
  splitChunks: {
    chunks: 'all',
  },
}
```

Generated file would like below:

```
3.e8d3cd1b.chunk.js 
index.html
main.7171a389.chunk.css
main.a1bf2ab0.chunk.js
runtime-main.e6fd4d77.bundle.js
vendors~main.0eeefc2c.chunk.js
```

And the HTML would like below and it's the vendors get included:

```
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Webpack Boilerplate</title>
    <link href="main.7171a389.chunk.css" rel="stylesheet">
</head>

<body>
    <h1>Webpack boilerplate</h1>
    <script type="text/javascript" src="runtime-main.e6fd4d77.bundle.js"></script>
    <!-- it get included  here -->
    <script type="text/javascript" src="vendors~main.0eeefc2c.chunk.js"></script>
    <script type="text/javascript" src="main.a1bf2ab0.chunk.js"></script>
</body>
</html>
```

[Update]:
My webpack configuration here: [configs](https://github.com/finmavis/repo-example-bug/blob/master/config/webpack.prod.js)

**What is the expected behavior?**

The vendor chunks should get included just like when `name` options get enabled like the second example above.

**Other relevant information:**
webpack version:  4.41.5
Node.js version: 12.14.0
Operating System: windows 10 x64
Additional tools:

**Comment by evilebottnawi** [comment]
Please provide webpack configuration

**Comment by evilebottnawi** [comment]
Why do you use `name: false`? Do you read `splitChunks` documentation? I recommend use `mode: "production"` instead setup `splitChunks`. You should read how it works to understand how to configure https://webpack.js.org/plugins/split-chunks-plugin/

**Comment by finmavis** [comment]
I still trying to figure it out how to setup webpak, and read in (this article)[https://medium.com/webpack/webpack-4-code-splitting-chunk-graph-and-the-splitchunks-optimization-be739a861366] that i should disabling the name option for production for better caching? Sorry if i'm misundestanding it.

**Comment by evilebottnawi** [comment]
Why do you touch `splitChunks` default webpack configuration? It is works for most of projects? What is use case?

**Comment by finmavis** [comment]
My purpose only to learn how it works and understanding it, i still dont know the use case, because right now this is only playground to trial and error configuring webpack for me. Thank you for the answer, it is my bad not read the docs carefully.

Cheers! I will close this issue.
Once again thank you for fast response, and sorry for my bad english.

**Comment by evilebottnawi** [comment]
@finmavis If you don’t understand something, feel free to open the problem here https://github.com/webpack/webpack.js.org, we always want to improve our docs
