### ISSUE TITLE
Sourcemap from bundle is not utf-8 encoded

### ISSUE THREAD

**Issue by SimenB** [webpack/webpack#1035]
This can be seen in sourcemap

![image](https://cloud.githubusercontent.com/assets/1404810/7453048/6671ef18-f265-11e4-8ce0-d71e07e07a4a.png)

This is the actual bundle generated

![image](https://cloud.githubusercontent.com/assets/1404810/7453057/862a4878-f265-11e4-9e63-26c4c511dd51.png)

The letter `å` is wrong. Not sure if it's Webpack's fault or Sourcemap's?

Using Linux if that matters. Using `devtool: '#source-map'`

This is a letter only used in comments, not actual source, so shouldn't be a real problem.

**Comment by sokra** [comment]
https://github.com/webpack/webpack/blob/master/lib/SourceMapDevToolPlugin.js#L155

`"utf-8"` missing here. Would you like the write a PR?

**Comment by SimenB** [comment]
@sokra Sure, but I'm unsure where you mean I should put `utf-8`? Default encoding is utf-8 (https://nodejs.org/api/buffer.html#buffer_new_buffer_str_encoding & https://nodejs.org/api/buffer.html#buffer_buf_tostring_encoding_start_end)

**Comment by sirlancelot** [comment]
Looking at the [Buffer documentation](https://nodejs.org/api/buffer.html#buffer_new_buffer_str_encoding), I would guess that all you need to do is add `"utf-8"` as the second parameter. However, that appears to be the default, so there is likely some other place it needs to be added.

**Comment by disjukr** [comment]
i think same issue here: https://github.com/webpack/webpack/issues/859

**Comment by rjruizes** [comment]
I came across this issue because I had a Unicode code point in my javascript that was being scrambled as `â–¾`.
bundle.js: `console.log("▾")`; 
main.js: `console.log("\u25BE")`. 
My workaround: `console.log(String.fromCodePoint(0x25BE))` 
The workaround prevents webpack from unescaping the code point, and makes it to display correctly.

**Comment by sokra** [comment]
Did you send the correct UTF-8 HTTP Header from your server? Or did you add the utf-8 meta tag to the HTML page?

**Comment by rickihastings** [comment]
I'm still getting this issue. Specifically some files being produced are non-utf8 so they cannot be understood by Sentry when I'm uploading them as release artifacts.

That aside, from what I can gather the PR #1797 just seems to fix them when they're data-uri sourcemaps? How can I ensure that all files webpack outputs are utf-8 (using Windows)?

**Comment by bebraw** [comment]
Is this valid still? I can see the related PR was merged.

**Comment by SimenB** [comment]
Seeing as @rickihastings stil had the issue a couple of months later, probably not.

**Comment by jordanmkoncz** [comment]
I'm also having this issue, and like @rickihastings, I came upon this issue due to my source map not being readable by Sentry because the file is not utf8. I'm currently using Webpack 1.13.0 on macOS Sierra. I'm going to try updating to Webpack 1.14.0 and seeing if that resolves this issue - if it does then I'll report back here.

**Comment by yuri1992** [comment]
@jordanmkoncz did it worked for you ?

**Comment by katranci** [comment]
@bebraw I believe this issue is still valid. I'm using webpack@2.5.1 and I've got a multi-entry configuration. When I run `file -bi *.map` I can see that not all sourcemap files are in utf-8.

```
text/plain; charset=us-ascii
text/plain; charset=us-ascii
text/plain; charset=utf-8
text/plain; charset=us-ascii
text/plain; charset=utf-8
text/plain; charset=us-ascii
text/plain; charset=utf-8
```

What could cause a sourcemap file encoded in non-utf8 character set?

**Comment by mikeaustin** [comment]
Not sure if this is related, but I just fond I need to add charset="utf-8" to the bundle.js script tag:

<script src="bundle.js" type="text/javascript" charset="utf-8"></script>

Without the charset attribute, I get weird characters even with just &#9632;

**Comment by psachs21** [comment]
Also running into this. Doesn't seem to be any pattern, i have files either encoded as utf-8 or us-ascii.

```
0.e6063d8a791459c43093.chunk.js.map:                 text/plain; charset=us-ascii
1.e6063d8a791459c43093.chunk.js.map:                 text/plain; charset=utf-8
10.e6063d8a791459c43093.chunk.js.map:                text/plain; charset=utf-8
11.e6063d8a791459c43093.chunk.js.map:                text/plain; charset=utf-8
12.e6063d8a791459c43093.chunk.js.map:                text/plain; charset=utf-8
13.e6063d8a791459c43093.chunk.js.map:                text/plain; charset=utf-8
14.e6063d8a791459c43093.chunk.js.map:                text/plain; charset=utf-8
15.e6063d8a791459c43093.chunk.js.map:                text/plain; charset=utf-8
16.e6063d8a791459c43093.chunk.js.map:                text/plain; charset=us-ascii
```

In fact, this is not limited to source maps. My bundles are also scattered, some utf-8, some us-ascii. I'd like them to all be utf-8 encoded. Can this be forced?

**Comment by sokra** [comment]
They are always utf-8 encoded. If you only use characters from the ascii range, us-ascii and utf-8 encoding look equal.

``` js
> Buffer.from("abc", "utf-8")
<Buffer 61 62 63>
> Buffer.from("abc", "ascii")
<Buffer 61 62 63>

> Buffer.from("abcä", "ascii")
<Buffer 61 62 63 e4>
> Buffer.from("abcä", "utf-8")
<Buffer 61 62 63 c3 a4>
```

**Comment by psachs21** [comment]
hmm, interesting. I am trying to use a tool (sentry-cli) that uploads sourcemaps and it explodes saying "stream did not contain valid UTF-8". Might be something specific on their end in that case.

**Comment by newtonsheikh** [comment]
Thank you. Was facing the same problem  `text/plain; charset=utf-8` solved similar problem in our code. Cheers!
