### ISSUE TITLE
DOCS: output.ecmaVersion in Webpack 4 documentation

### ISSUE THREAD

**Issue by deftomat** [webpack/webpack#10353]
Looks like `output.ecmaVersion` feature is in `master` but it is not supported in 4.41.5.

Unfortunately, it is mentioned in v4 documentation which is quite confusing:
https://webpack.js.org/configuration/output/#outputecmaversion

**Comment by evilebottnawi** [comment]
Because it is for webpack@5, look at the version in package.json and will be available only for webpack@5, our master is webpack@5

**Comment by deftomat** [comment]
Yes, I got it. But as I said, Its mentioned in v4 documentation.

See the badge:

![Screenshot 2020-02-07 at 11 37 30](https://user-images.githubusercontent.com/5549148/74022636-3b7e1300-499e-11ea-9670-ecde63d2b131.png)

**Comment by montogeek** [comment]
Sorry, that badge is not for the documentation. We will change it later.
For v4 docs please use https://v4.webpack.js.org/, we are working in ways to show docs version.

**Comment by deftomat** [comment]
@montogeek AWESOME, thanks 👍

**Comment by davidgilbertson** [comment]
So are the docs at https://webpack.js.org/ currently for version 5? Is there an easy way to check if something I read in the docs will work in 4? I guess I need to add `v4` to the start of the URL to be certain?

I imagine this is a pain for anyone learning Webpack ATM.

I'm happy to help out, maybe adding a "Added in 5.0.0" to a bunch of things in the docs?

**Comment by jeffin143** [comment]
![IMG_20200327_145347](https://user-images.githubusercontent.com/21286134/77741381-d3ad8580-703a-11ea-82bb-24fd66e6dc28.jpg)


@davidgilbertson , you can click on the link and it will redirect to you. The migration guide would have bunch of things , which let's you know what is added.
