### ISSUE TITLE
JSON shaking should warn on bailout

### ISSUE THREAD

**Issue by laverdet** [webpack/webpack#10355]
# Bug report

**What is the current behavior?**
When you import a JSON-only module Webpack will shake it out only to the used properties. This works super well, but it bails out silently when an unknown key is encountered. This can create hard to track down issues where package size increases in size without a clear cause.

**If the current behavior is a bug, please provide the steps to reproduce.**
I've created a short gist that demonstrates the problem clearly:
https://gist.github.com/laverdet/c2da343e36669721f4541298348c347e

First run `npm install` obviously to pick up webpack. Then run `npx webpack` and examine `dist/main.js` to see: `console.log("main")` somewhere in the source. Webpack successfully pulled that from `config.js` and put it right into the log. The unused property in `config.js` has also been entirely omitted from the source (good).

Now uncomment line 3 of `main.js` and run `npx webpack` again. Now the source will be something like `var r={title:"main",aaaaaaaaaaaaaaaaaaaa:"bbbbbbbbbbbb"};console.log(r.title),console.log(r.undef)`. The property names of config.js now make it into the final source in addition to the unused properties.

**What is the expected behavior?**
I would expect some kind of warning here to let me know the JSON module routine has bailed out.

**Other relevant information:**
webpack version:  4.41.5
Node.js version: 13.x
Operating System: *

**Comment by sokra** [comment]
Interesting. Since webpack 4 doesn't tree-shake this case anyway (It's not JSON and not a namespace object), this is an optimization terser does for you.

It's probably unable to optimize this case because you may have `Object.prototype.undef` set to an value.
