### ISSUE TITLE
Allow pitch phase to efficiently rewrite the current loader chain

### ISSUE THREAD

**Issue by jquense** [webpack/webpack#10350]
## Feature request

This is maybe just a question as it may already be possible. I'm working on a loader that that inserts itself into an configured chain via `pitch()`

```js
export function pitch() {
  const cssIdx = this.loaders.findIndex(l => l.path.includes('css-loader/'));
  const cssLoader = this.loaders[cssIdx];

  const loaders = [...this.loaders];

  const [me] = loaders.splice(this.loaderIndex, 1);

  loaders.splice(cssIdx + 1, 0, me);
  const prefix = loaders.map(x => x.request).join('!');

  return `module.exports = require("-!${prefix}!${this.resourcePath}");`;
}
```

The *problem* is tho i need to add some options to css-loader here, but cannot b/c they aren't serializable, and the query string here is an ident. There doesn't seem to be any way of adding a new ident mapping either at this point.

My other approach was alter the loaders array, but the problem with this is it can create duplicate modules, when another loader does something like [css-loader does](https://github.com/webpack-contrib/css-loader/blob/master/src/utils.js#L186-L201) If you have 
`my-loader!foo.css` you can different modules that compile to the same thing if css-loader ses a dependency on foo.css it'll get required as `css-loader!my-loader!foo.css`

**What is the expected behavior?**

I'd like to be able to rewrite a loader chain in the pitch phase 
 - change options without mutating a configured rule's options object 
 - not create duplicate modules, which seems to happen based on the initial request, not the request after `pitch` is complete

**How should this be implemented in your opinion?**

Really unsure

**Are you willing to work on this yourself?**
yes

**Comment by jquense** [comment]
I guess i'd be nice if the api was simply something like 
```js
const query = `??${this.getIdentForOptions(newOptions)`
```

**Comment by sokra** [comment]
> My other approach was alter the loaders array

That's the way to go here.

Regarding identity: It's intended that modules that run different loaders, or the same loaders with different options create different module instances.

You may extend css-loaders `importLoaders` to include your loader to options are correctly adjusted.

To change the options clone them before modifying to not mutate the original config options object.

**Comment by jquense** [comment]
> To change the options clone them before modifying to not mutate the original config options object.

Awesome let me try that

> Regarding identity: It's intended that modules that run different loaders, or the same loaders with different options create different module instances.

that make total sense generally, since the output might be wildly different. It's problematic in this case tho because you end up with duplicate styles/broken cascade. I was hoping that identity could be determined after pitching (assuming no early returns). since the ultimately you can change the loaders that end up transforming the module. In this case, by the time pitching is done, the "real" request transforming the file would match another.

I could workaround that by returning `module.exports = require()` etc, where the next require is the "normal" one, but you end up with double the modules needed, and extra pass through code in the bundle (maybe the most practical downside).

**Comment by sokra** [comment]
> I could workaround that by returning `module.exports = require()` etc, where the next require is the "normal" one, but you end up with double the modules needed, and extra pass through code in the bundle (maybe the most practical downside).

You can `export * from "..."` and flag the module as side-effect-free with `sideEffects: false` in the rule in `module.rules`. This will skip the module during sideEffects optimization.

**Comment by jquense** [comment]
Interesting...that seems reasonable. A quick try didn't seem to get that result, but that may be due to the parent or child module importing/exporting commonJs? I'll dig in, but is it safe to assume that the optimization is only possible if the "passthrough" module is ESM imports on either side?

**Comment by sokra** [comment]
Yes, at least consumer need to be ESM too. Not sure about the target module.

Also note that the default export need to be reexported too if it exist. export * doesn't include default.

``` js
export { default } from "..."
```

**Comment by jquense** [comment]
This strategy worked great and I've I implemented some version of it in astroturf v1, thanks!
