### ISSUE TITLE
webpack cli progress option in configuration file

### ISSUE THREAD

**Issue by derMart** [webpack/webpack#10369]
Hi, the cli tool documentation lists the --progress option (https://webpack.js.org/api/cli/#debug-options), but I have not found this in the configuration documentation (https://webpack.js.org/configuration/#options)

Is it possible to setup webpack to output the progress using the json config and if yes, how?
If not, this would be a feature request.

kind regards
Martin

**Comment by evilebottnawi** [comment]
No, it is only for CLI, because only CLI create output and it is out of scope webpack

**Comment by derMart** [comment]
ok, but well there are other options in the configuration file which affect the cli output. E.g. the stats option...

**Comment by evilebottnawi** [comment]
Yes, because it is creating by webpack, webpack does not output nothing in a terminal without the CLI package

**Comment by derMart** [comment]
sorry I do not understand your argumentation.

What do you mean by "it is creating by webpack"
Ok webpack does not output anything, got that. But still there are configuration options in the json already which configure the CLI tools output. So not adding the progress option to the json because these options should not configure the CLI tools output is contradictory.

**Comment by evilebottnawi** [comment]
I can't understand you. Do you want setup progress using webpack configuration file? If yes you can use https://webpack.js.org/plugins/progress-plugin/, `--progress` option for webpack-cli do same

**Comment by evilebottnawi** [comment]
Also please use the issue template in the future

**Comment by derMart** [comment]
Thank you. Yes the progress-plugin is what I was asking for initially.
Is there any documentation about the mapping between the CLI tools options and the json configuration options / plugins? So, which CLI options correspond to which json configuration option respectively to which plugin ?

**Comment by evilebottnawi** [comment]
@derMart 

> Is there any documentation about the mapping between the CLI tools options and the json configuration options / plugins? So, which CLI options correspond to which json configuration option respectively to which plugin ?

Partial, you can open an issue here https://github.com/webpack/webpack.js.org to improve that
