### ISSUE TITLE
Feature - Export the manifest object from runtime chunk

### ISSUE THREAD

**Issue by xiaogdgenuine** [webpack/webpack#10364]
## Feature request

**What is the expected behavior?**
If the project generates a single runtime chunk file by option
`
optimization: {
  runtimeChunk: 'single'
}
` 
Pls expose the manifest content in that runtime chunk, I believe there is a function call jsonpScriptSrc contain such content, if u pass chunkId in, u will get the **public path** of that chunk as return value:

![image](https://user-images.githubusercontent.com/51731239/74124091-15f64100-4c0c-11ea-8b39-bc9da2095731.png)

**What is motivation or use case for adding/changing the behavior?**
I'm developing a plugin([webpack-prefetcher](https://www.npmjs.com/package/webpack-prefetcher)) to help people do better **prefetch/preload** in webpack

This plugin requires a manifest file to be downloaded before it can prefetch/preload anything, now I can get the manifest file by the [WebpackManifestPlugin](https://github.com/danethurber/webpack-manifest-plugin)

But if runtime chunk already has manifest data, the use of this manifest plugin is quite unnecessary in my opinion.

**How should this be implemented in your opinion?**
Modify the runtime chunk file's template, expose the `jsonpScriptSrc` function.

**Are you willing to work on this yourself?**
yes! but need some guidance...

**Comment by sokra** [comment]
webpack 5 exposes a `__webpack_get_script_filename__` function accessible inside of the bundle.

It also has a prefetch and preload function in the runtime, but this is not exposed as nice variable: `__webpack_require__.E` and `__webpack_require__.F`. It takes a `chunkId` and prefetches/preloads all resources like JS, CSS, WASM, etc. Plugins can add handlers to these functions for custom module types.

You could add them to the APIPlugin in a PR if you want them to be exposed.

**Comment by xiaogdgenuine** [comment]
@sokra I'm glad that webpack 5 exposes the `__webpack_get_script_filename__`, that should be enough for me, don't need to touch APIPlugin.

But since webpack 5 is still in beta, I was thinking to implement this in on webpack 4 first, anyway I found the `JsonpMainTemplatePlugin` in webpack 4 is generating the template for `jsonpScriptSrc`, I will try to modify this plugin first.

**Comment by evilebottnawi** [comment]
@xiaogdgenuine sorry webpack@4 doesn't accept new features, only bug fixes

**Comment by xiaogdgenuine** [comment]
@evilebottnawi I understand, and I found a way around this without changing the source code of webpack 4.

I wrote a webpack plugin to tap `mainTemplate.hooks.localVars` hook in the lower priority to achieve this:

```
compilation.mainTemplate.hooks.localVars.tap({
        name: pluginName,
        // lower priority compare to `JsonpMainTemplatePlugin`
        stage: 1,
      }, (source, chunk, hash) => {
        let newSource = source;

        // Expose get js path function
        newSource = newSource.replace(
                                   "function jsonpScriptSrc", 
                                   "window.jsonpScriptSrc = function jsonpScriptSrc");

        return newSource;
})
```

Really hacky but it works perfect for me. :P
