### ISSUE TITLE
Not splitting into chunks even with optimization.splitChunks.minSize=0

### ISSUE THREAD

**Issue by Aykelith** [webpack/webpack#10366]
# Bug report

**What is the current behavior?**

The webpack is not splitting by react components. I have a larger project that contains pretty big components and using the same config given in the project below it will not split anything and I don't know what I'm doing wrong.

**If the current behavior is a bug, please provide the steps to reproduce.**

I have created the project [https://github.com/Aykelith/webpack-corejs3-split-chunks-test](https://github.com/Aykelith/webpack-corejs3-split-chunks-test)

**What is the expected behavior?**

Should split my given components given in `src/MainPage.js` by using `React.lazy` and also adding `webpackChunkName` to the components. In the config of webpack I set `optimization.splitChunks.minSize=0` but still not creating my chunk

**Other relevant information:**
webpack version:  4.41.5
Node.js version: 12.13.1
Operating System: Windows 10 10.0.18362

**Comment by sokra** [comment]
Remove the dynamic-import-node Babel plugin

**Comment by Aykelith** [comment]
Thank you, thank you, thank you.
