### ISSUE TITLE
[Docs] i18n example is missing

### ISSUE THREAD

**Issue by berickson1** [webpack/webpack#10367]
# Bug report

**What is the current behavior?**
The localization example listed in https://github.com/webpack/webpack/tree/master/examples#i18n and at https://webpack.js.org/plugins/i18n-webpack-plugin/ is missing

**If the current behavior is a bug, please provide the steps to reproduce.**
N/A

**What is the expected behavior?**
Either the example should be restored or the links should be removed

**Other relevant information:**

**Comment by valentin9** [comment]
I assume the plugin is was not updated to the current plugin API (Tapable 2?), Might be the reason it's not in the master branch.

If the plugin should be updated, I would gladly try to do it and make a pull request, so it finally can land on the master branch. Let's wait for an official response.

**Comment by valentin9** [comment]
I see there is already a pull request but no response there:
https://github.com/webpack-contrib/i18n-webpack-plugin/pull/73

**Comment by berickson1** [comment]
@webpack-bot - This should be left active until #10376 is reviewed
