### ISSUE TITLE
Source map not working in production

### ISSUE THREAD

**Issue by geekyme** [webpack/webpack#1037]
Hi, 

I'm using the following sourcemap config: ```devtool: "source-map",```

On production, I see the following files downloaded: 
![image](https://cloud.githubusercontent.com/assets/977460/7466883/96e65f12-f31e-11e4-949c-53602f6d2f40.png)

So source maps are being generated. 

However, when an error occurs, I do not see the source map link: 

![image](https://cloud.githubusercontent.com/assets/977460/7466888/b4a12be0-f31e-11e4-9d3f-3f57f81676ad.png)

It only points to my compiled code which is obfuscated and hard to understand.

**Comment by mllocs** [comment]
https://github.com/mishoo/UglifyJS2/pull/738 may fix the issue

**Comment by bebraw** [comment]
@geekyme Can you try against the current version? I think uglify has received some nice fixes.

**Comment by bebraw** [comment]
No response, closing. Feel free to re-open with more details.
