### ISSUE TITLE
When a Yarn 2 installation uses virtual packages, the DllPlugin/DllReferencePlugin doesn't refer to the linked library.

### ISSUE THREAD

**Issue by edeustace** [webpack/webpack#10375]
When a Yarn 2 installation uses [virtual packages][lexicon], the DllPlugin/DllReferencePlugin don't pull in the linked library. This is because the [virtual package][lexicon] paths are unique even though the refer to the same package.

# Bug report

See this [repo][repo] for a demonstration. It contains 2 webpack builds: `dll-lib` and `lib-user`. 
* `dll-lib` bundles `react-dom` and creates a `library-manifest.json` using the `DllPlugin`.
* `lib-user` references `library-manifest.json` using `DllReferencePlugin`.

**What is the current behavior?**
`react-dom` is bundled into `lib-user/dist/index.js`.

**If the current behavior is a bug, please provide the steps to reproduce.**

[https://github.com/ahum/webpack-dll-yarn-two-virtual-paths-demo][repo]

**What is the expected behavior?**
The bundle in `lib-user` makes a reference to `react-dom` in it's bundle by using `library-manifest.json` in `dll-lib`.

**Other relevant information:**
webpack version:  5.0.0-beta.13
Node.js version: 11.10.0
Operating System: Pop_OS! 19.10
Additional tools: 
* yarn@2.0.0-rc.29

[repo]: https://github.com/ahum/webpack-dll-yarn-two-virtual-paths-demo

[ia]: https://yarnpkg.com/advanced/architecture#install-architecture
[lexicon]: https://yarnpkg.com/advanced/lexicon#virtual-package

**Comment by evilebottnawi** [comment]
bump

**Comment by richiejd** [comment]
Haven't firgured out the best way to handle, but to clarify what's happening:
package where dll is generated resolves to a given virtual namespace
package where dll is used resolves to a different virtual namespace, thus 

require('../4970a0b490...') and 
require('../76a393ef8c...') do not match as being the same underlying resolution

I haven't figured out how to have more control over the virtualized fs, more documentation on how this works would be great. Given I can have good control over my dependencies in my repo, ideally I'd be able to say something like "there is no virtual for react-dom; I will guarantee that only one module is installed for the whole repo and I do not want multiple instances instantiated"

Thus it would not be virtualized.

**Comment by vankop** [comment]
@sokra is it still an issue?
