### ISSUE TITLE
can't add @hapi/joi as externals

### ISSUE THREAD

**Issue by katlimruiz** [webpack/webpack#10379]
Can't add @hapi/joi as externals.

It tells me syntax error on @.

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by katlimruiz** [comment]
# Bug report
**What is the current behavior?**
set
`
"externals": ["@hapi/joi"]
`

and it gives error.
**What is the expected behavior?**
I define hapi/joi as an external, and it is excluded from the minified bundle.

**Other relevant information:**
webpack version:  4.41.6
Node.js version: 10
Operating System: Win10
Additional tools:
