### ISSUE TITLE
can't include @hapi/joi as external

### ISSUE THREAD

**Issue by katlimruiz** [webpack/webpack#10380]
What is the current behavior?
set
```
"externals": ["@hapi/joi"]
```
and it gives error.
What is the expected behavior?
I define hapi/joi as an external, and it is excluded from the minified bundle.

Other relevant information:
webpack version: 4.41.6
Node.js version: 10
Operating System: Win10
Additional tools:

**Comment by evilebottnawi** [comment]
Please answer on all questions in the issue template otherwise the issue was closed

**Comment by katlimruiz** [comment]
i ended up using rollup

**Comment by evilebottnawi** [comment]
Okay
