### ISSUE TITLE
Dead code still being compiled

### ISSUE THREAD

**Issue by johnsky95** [webpack/webpack#10386]
I am compiling **Typescript** to **JS** a demo app, just to see how the **Tree Shaking** works, but on compiled file, I see hundrets of methods I am not using them at all.

**webpack.config.js**
```
const path = require('path');
const TerserPlugin = require('terser-webpack-plugin');

module.exports = {
    entry: './index.ts',
    module: {
        rules: [
            {
                test: /\.tsx?$/,
                loader: 'babel-loader'
            }
        ]
    },
    output: {
        filename: 'bundle.js',
        path: path.resolve(__dirname, 'dist')
    },
    plugins: [
    ],
    optimization: {
        usedExports: true,
        minimize: true,
        minimizer: [new TerserPlugin()],
    },
};
```

**.babelrc**
```
{
  "presets": [
    "@babel/preset-env"
  ]
}
```

**tsconfig.json**
```
{
  "compilerOptions": {
    "target": "es5",
    "module": "es5",
    "lib": [
      "es5",
      "es6",
      "dom"
    ],
    "allowJs": true,
    "jsx": "react",
    "sourceMap": true,
    "outDir": "./dist",
    "rootDir": "./",
    "downlevelIteration": true,
    "esModuleInterop": true
  }
}
```

**index.ts**
```
import { HugeLibrary } from 'huge';

const huge = new HugeLibrary();
huge.sayHello();
```

So, the `sayHello()` only outputs on the console "Hello", and I expect only sayHello method to be compiled. But, that does not happen. What I see is, all the methods from the `Huge` Library as well as its dependencies. I compiled an Angular 8 production also, and they were also compiling the not reached code also. 

Why should sayGoodBye or greetings() be anyway compiled if from Index.ts I never used that?

**package.json**
```
{
  "name": "demo",
  "sideEffects": false,
  "main": "index.js",
  "author": "",
  "license": "ISC",
  "dependencies": {
   "huge": "^1.0.0",
  },
  "devDependencies": {
    "@babel/core": "^7.8.4",
    "@babel/preset-env": "^7.8.4",
    "@babel/preset-react": "^7.8.3",
    "@babel/preset-typescript": "^7.8.3",
    "babel-cli": "^6.26.0",
    "babel-loader": "^8.0.6",
    "babel-minify-webpack-plugin": "^0.3.1",
    "babel-plugin-minify-dead-code-elimination": "^0.5.1",
    "babili-webpack-plugin": "^0.1.2",
    "terser-webpack-plugin": "^2.3.4",
    "typescript": "^3.7.5",
    "webpack": "^4.41.5",
    "webpack-cli": "^3.3.11"
  }
}
```

webpack -p is the command I run

**Comment by montogeek** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by sokra** [comment]
Choose the correct `compilerOptions.module`

**Comment by evilebottnawi** [comment]
Answer above, please respect other developers and use the issue template in future

**Comment by johnsky95** [comment]
> Answer above, please respect other developers and use the issue template in future

I will, thank you.

**Comment by johnsky95** [comment]
> Choose the correct `compilerOptions.module` for ESM

Can you help me with the config?

**Comment by evilebottnawi** [comment]
Please use stackoverflow or gitter or other Q&A services for questions, it is bug tracker, thanks

**Comment by johnsky95** [comment]
> Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

https://github.com/johnsky95/webpack_dead_code

I created a demo app.


`export class ClassA {

    sayHello() {
        console.log('hello');
    }

    sayBye() {
        console.log('bye');
    }
}

new ClassA().sayHello();`

function sayBye() is still compiled, is this a bug or I am configuring something wrong, no idea :/
