### ISSUE TITLE
output.hotUpdateChunkFilename does not support functions

### ISSUE THREAD

**Issue by arseneyr** [webpack/webpack#10389]
# Bug report

**What is the current behavior?**
Setting `output.hotUpdateChunkFilename` to a function and enabling HMR in webpack-dev-server causes the following error: 
```
ERROR in chunk main [entry]
Cannot read property 'replace' of undefined

ERROR in chunk main [entry]
main.js
Cannot read property 'replace' of undefined
i ｢wdm｣: Failed to compile.
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Minimal example: https://github.com/arseneyr/broken-webpack-hotpath
Run using `yarn start` or `npm start`.

**What is the expected behavior?**
The compilation succeeds and the function supplied to `output.hotUpdateChunkFilename` is called to determine hot update filename.

**Other relevant information:**
webpack version:  4.41.6
Node.js version: 12.8.0
Operating System: Windows 10
Additional tools:

I believe this is a result of https://github.com/webpack/webpack/blob/71be3bfa45a55aa8ea1b954ab1302565bb073bbc/lib/web/JsonpMainTemplatePlugin.js#L569
without actually resolving the path using `compilation.getPathWithInfo`.

**Comment by sokra** [comment]
Why do you need that?

I think thats probably fixed in webpack 5

**Comment by arseneyr** [comment]
I was using it to conditionally unmangle hot update names for chrome extension chunks, where certain bundles may be running in the context of another page and need the hot update filename to be allow-listed. I can probably work around it in a plugin, but was just wondering if I was doing something wrong or the docs never meant to support a function.

**Comment by sokra** [comment]
The issue in webpack 4 is a technically one. `chunkFilename` and `hotUpdateChunkFilename` is not just called for each processed chunk, a runtime variant of the template is also embedded in the bundle. At runtime only chunkId is available and the filename template string (e. g. `[id].chunk.js`) is transformed to something like `chunkId => "" + chunkId + ".chunk.js"`. Supporting a function is not that easy.

webpack 5 does some more magic here and will generate a switch-case statement when using a function or using different filename templates for different chunks.

**Comment by evilebottnawi** [comment]
Fixed https://github.com/webpack/webpack/pull/10393 for webpack@5
