### ISSUE TITLE
Invalid webpack:///webpack/bootstrap mapping/content in source maps

### ISSUE THREAD

**Issue by bengourley** [webpack/webpack#10381]
# Bug report

**What is the current behavior?**

Webpack outputs a source map that includes the following mapping:

| Bundle line | Bundle column | Source file | Source line | Source column |
|---|---|---|---|---|
| 1 | 933 | `webpack:///webpack/bootstrap` | 83 | 54 |

The data included in the source map's `sourcesContent` array has this for `webpack:///webpack/bootstrap`, which is clearly already minified:

```
 \t// The module cache\n \tvar installedModules = {};\n\n \t// The require function\n \tfunction __webpack_require__(moduleId) {\n\n \t\t// Check if module is in cache\n \t\tif(installedModules[moduleId]) {\n \t\t\treturn installedModules[moduleId].exports;\n \t\t}\n \t\t// Create a new module (and put it into the cache)\n \t\tvar module = installedModules[moduleId] = {\n \t\t\ti: moduleId,\n \t\t\tl: false,\n \t\t\texports: {}\n \t\t};\n\n \t\t// Execute the module function\n \t\tmodules[moduleId].call(module.exports, module, module.exports, __webpack_require__);\n\n \t\t// Flag the module as loaded\n \t\tmodule.l = true;\n\n \t\t// Return the exports of the module\n \t\treturn module.exports;\n \t}\n\n\n \t// expose the modules object (__webpack_modules__)\n \t__webpack_require__.m = modules;\n\n \t// expose the module cache\n \t__webpack_require__.c = installedModules;\n\n \t// define getter function for harmony exports\n \t__webpack_require__.d = function(exports, name, getter) {\n \t\tif(!__webpack_require__.o(exports, name)) {\n \t\t\tObject.defineProperty(exports, name, { enumerable: true, get: getter });\n \t\t}\n \t};\n\n \t// define __esModule on exports\n \t__webpack_require__.r = function(exports) {\n \t\tif(typeof Symbol !== 'undefined' && Symbol.toStringTag) {\n \t\t\tObject.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });\n \t\t}\n \t\tObject.defineProperty(exports, '__esModule', { value: true });\n \t};\n\n \t// create a fake namespace object\n \t// mode & 1: value is a module id, require it\n \t// mode & 2: merge all properties of value into the ns\n \t// mode & 4: return value when already ns object\n \t// mode & 8|1: behave like require\n \t__webpack_require__.t = function(value, mode) {\n \t\tif(mode & 1) value = __webpack_require__(value);\n \t\tif(mode & 8) return value;\n \t\tif((mode & 4) && typeof value === 'object' && value && value.__esModule) return value;\n \t\tvar ns = Object.create(null);\n \t\t__webpack_require__.r(ns);\n \t\tObject.defineProperty(ns, 'default', { enumerable: true, value: value });\n \t\tif(mode & 2 && typeof value != 'string') for(var key in value) __webpack_require__.d(ns, key, function(key) { return value[key]; }.bind(null, key));\n \t\treturn ns;\n \t};\n\n \t// getDefaultExport function for compatibility with non-harmony modules\n \t__webpack_require__.n = function(module) {\n \t\tvar getter = module && module.__esModule ?\n \t\t\tfunction getDefault() { return module['default']; } :\n \t\t\tfunction getModuleExports() { return module; };\n \t\t__webpack_require__.d(getter, 'a', getter);\n \t\treturn getter;\n \t};\n\n \t// Object.prototype.hasOwnProperty.call\n \t__webpack_require__.o = function(object, property) { return Object.prototype.hasOwnProperty.call(object, property); };\n\n \t// __webpack_public_path__\n \t__webpack_require__.p = \"http://localhost:5000/\";\n\n\n \t// Load entry module and return exports\n \treturn __webpack_require__(__webpack_require__.s = 0);\n
```

This means that if you try to retrieve the code at line 83, column 54, you get nothing (since that source only has a single line).

**If the current behavior is a bug, please provide the steps to reproduce.**

The webpack config used to generate this bundle and map is as follows:

**webpack.config.js**
```js
const webpack = require('webpack')
const path = require('path')
module.exports = {
  mode: 'production',
  devtool: 'source-map',
  output: {
    path: path.resolve(__dirname, 'dist'),
    publicPath: 'http://localhost:5000/'
  },
}
```

**source/index.js**
```
try {
  throw new Error('hi')
} catch (e) {
  console.log(e.stack)
}
```

If you load this script in a browser you get something like the following stack trace:

```
@http://localhost:5000/dist/main.js:1:959
r@http://localhost:5000/dist/main.js:1:110
@http://localhost:5000/dist/main.js:1:924
@http://localhost:5000/dist/main.js:1:933
```

Using mozilla's source map tool you can verify whether the source maps are valid for each line of this stack trace:

```
npm i source-map
```

```sh
node -e "var sourceMap=require('source-map');new sourceMap.SourceMapConsumer(fs.readFileSync('dist/main.js.map','utf8')).then((sm) => {console.log(sm.originalPositionFor({ line: 1, column: 933 })) })"
```

Output:
```js
{ source: null, line: null, column: null, name: null }
```

The other frames map fine, e.g:
```sh
node -e "var sourceMap=require('source-map');new sourceMap.SourceMapConsumer(fs.readFileSync('dist/main.js.map','utf8')).then((sm) => {console.log(sm.originalPositionFor({ line: 1, column: 110 })) })"
```

```js
{
  source: 'webpack:///webpack/bootstrap',
  line: 19,
  column: 21,
  name: 'call'
}
```

**What is the expected behavior?**
I would expect either:
- the source for `webpack:///webpack/bootstrap` not to be minified in the source map
or
- the mappings should point to the correct place in the already minified `webpack:///webpack/bootstrap`

This is important for Bugsnag because we tell our users if their source maps are invalid and we can't retrieve the source it should map to:

![image](https://user-images.githubusercontent.com/609579/74454763-480dda00-4e7c-11ea-8908-b01bc368d986.png)

**Other relevant information:**
webpack version:  4.41.6
Node.js version: 12.4.0
Operating System: OSX
Additional tools:

**Comment by sokra** [comment]
> which is clearly already minified:
> 
> ```
>  \t// The module cache\n \tvar installedModules = {};\n\n \t// The require function\n
> ```

It's not. `\n` is a line break.

---

> Output:
> 
> ```js
> { source: null, line: null, column: null, name: null }
> ```

Some parts of the bundle are generated code and do not map to any source code. So this might be correct.

**Comment by bengourley** [comment]
> > which is clearly already minified:
> > ```
> >  \t// The module cache\n \tvar installedModules = {};\n\n \t// The require function\n
> > ```
> 
> It's not. `\n` is a line break.

🤦‍♂ good point, sorry! So it looks like the location `83:54` does exist in that source:

```
// Load entry module and return exports
return __webpack_require__(__webpack_require__.s = 0);
                                                    ^
```

I took at closer look at the mappings.

Using a [utility I wrote](https://www.npmjs.com/package/@bengourley/source-map-decoder) to print out a human-readable view of a source map, I get this, which seems correct:

```
"1": [
  "933 => webpack:///webpack/bootstrap 83:54 s"
]
```

But then when I log out all of the mappings using mozilla's `source-map` moduel,  it shows the following:

```
Mapping {
  generatedLine: 1,
  generatedColumn: 932,
  lastGeneratedColumn: null,
  source: null,
  originalLine: null,
  originalColumn: null,
  name: null
}
```

(note the column is zero-based)

```sh
node -e "var sourceMap=require('source-map');new sourceMap.SourceMapConsumer(fs.readFileSync('dist/main.js.map','utf8')).then((sm) => sm.eachMapping((s) => console.log(s)))"
```

It appears to be this explicit `null` mapping which is throwing the source map module off – I'm not sure why my module picks up a the seemingly-correct mapping for 1:933.

> Some parts of the bundle are generated code and do not map to any source code. So this might be correct.

I understand that this is often the case, and this is quite a normal occurrence, but with this specific example the code _is_ there because I can see it, the mapping just seems incorrect.

**Comment by sokra** [comment]
I don't know. Maybe you can provide a repro repo

**Comment by djskinner** [comment]
For any future travelers, this StackOverflow answer offers some explanation of why this entry appears: https://stackoverflow.com/a/45068039/120497
