### ISSUE TITLE
Error messages from loaders misreported when extra <> characters present

### ISSUE THREAD

**Issue by mcclure** [webpack/webpack#10384]
I am encountering a problem with Webpack with the Typescript ts-loader (I have also seen an identical bug with Webpack and awesome-typescript-loader). I [first filed this bug with ts-loader](https://github.com/TypeStrong/ts-loader/issues/1039#issuecomment-585354424). They told me it was a Webpack bug (citing its presence in multiple Webpack loaders) and closed my bug.

If this is not a Webpack bug, then I would like to request you help me figure out what to say to convince ts-loader that this is their bug that should be fixed at their end. I am an end user and do not know how Webpack loaders work.

# Bug report

**If the current behavior is a bug, please provide the steps to reproduce.**

[Check out this minimal example repo](https://github.com/mcclure/ts-hello-bug/commit/ad8f8cfbc4e7afcc0626fb6f98d723c59cded7ed). Run `npm install` and `npx webpack`. The example uses version 4.41.6 of Webpack with ts-loader (and copy-webpack-plugin).

**What is the current behavior?**

Upon running `npx webpack` with this example, the following confusing and misleading error occurs:

```
[./src/index.tsx] 294 bytes {main} [built] [failed] [11 errors]

ERROR in ./src/index.tsx 18:1
Module parse failed: Unexpected token (18:1)
File was processed with these loaders:
 * ./node_modules/ts-loader/index.js
You may need an additional loader to handle the result of these loaders.
| console.log("9");
| console.log("10");
>  > , label;
| string;
| {

ERROR in /Users/mcc/work/g/temp/ts-hello-bug/src/index.tsx
./src/index.tsx
[tsl] ERROR in /Users/mcc/work/g/temp/ts-hello-bug/src/index.tsx(25,58)
      TS1005: ';' expected.
```

9 more errors follow after these.

**What is the expected behavior?**

The **second** error shown in the error spew is correct. However the **first** error is fallacious, marks a line which is completely correct, misformats the code sample (it claims the error was on line 18 but prints a \> pointing at line 22; both lines 18 and 22 are correct) and is generally nonsensical. The expected behavior would be to show only the real error (line 25) and not the phantom error(s) on line 18 or 22.

Explanation: The example contains this line in "index.tsx" on line 25:

    function UsersBox(props: {list: State<OrderedSet<string>>>, label:string}) {

This is an invalid line of TypeScript. TypeScript uses \<angle brackets\> to denote parameterized types in generics, for example, a `Set<number>` is a Set of numbers. The \<brackets\> in this example are unbalanced, there is one \> too many.

You can tell that the phantom error is being inserted by **either** WebPack or ts-loader because normal TypeScript does not flag the line 18/22 bug. If you run `tsc` in the example repo the only errors you will see are

```
src/index.tsx(25,58): error TS1005: ';' expected.
src/index.tsx(25,59): error TS1109: Expression expected.
src/index.tsx(25,73): error TS1005: ',' expected.
```

The reason I consider the phantom error a significant problem is that usually in compiler errors, the first error in a group is the most significant. Coders effectively become trained to assume the first-reported error is "real" and further ones could be the result of a parser being lead off track by the first error. A user encountering this misreported-error bug (this happened to me) could lose a significant amount of time due to not realizing which error is the real one (the second out of eleven, but **not** the others). Furthermore the error is easy to encounter because \<\> is common in TypeScript.

**Other relevant information:**

Very many other simple typos involving stray \<angle brackets\> cause similar misreported errors to occur with Webpack+ts-loader. For example, if I remove index.tsx line 25 from the example repo and put this in instead:

```
return <div className="ErrorBox">
    <div className="Header">Errors</div>
    <div className="List">{errorFragment}<div>
  </div>
```

(The `<div>`s here are unbalanced; the second to last `<div>` should be a `</div>`). Similar to the `>>` bug, this code reports a nonsensical error about seven or eight lines before the place where the error actually occurred.

**Comment by sokra** [comment]
The error message shows the code generated by typescript. Typescript even generates some JS code when errors are found. That JS code is malformed, which causes the error.

**Comment by mcclure** [comment]
@sokra , is there a way to see what JS code ts-loader generated in this case, which caused the error, so I can check whether that is true?

is there anything ts-loader could be doing differently (for example, providing a source map) so that the line number in the error would be reported correctly?

If I run `tsc` (showing what output Typescript would normally emit— `tsc` will print errors but still emit a file), I get:
```
let verbose = false;
class OrderedSet {
    constructor() { }
}
class State {
    constructor() { }
}
console.log("1");
console.log("2");
console.log("3");
console.log("4");
console.log("5");
console.log("6");
console.log("7");
console.log("8");
console.log("9");
console.log("10");
// HERE IS THE LINE WITH THE CURSE
function UsersBox(props =  > , label) {
}
```
It looks like there *is* an error in the emitted code here on line 18, where typescript passes through a raw `>`. Line 18 is where the "phantom error" was reported. So Webpack might be reporting right in that there *is* an error on line 18 of the output it's been given, but it's not correct insofar as it's not line 18 of *index.tsc*, and also it truncates the displayed line to `>  > , label;` instead of printing `function UsersBox(props =  > , label) {` which would have been slightly more helpful.

**Comment by sokra** [comment]
> there _is_ an error on line 18 of the output it's been given, but it's not correct insofar as it's not line 18 of _index.tsc_, and also it truncates the displayed line to `> > , label;` instead of printing `function UsersBox(props = > , label) {` which would have been slightly more helpful.

That seem to be true, but I don't know why this is broken.

You might debug that. Here are the code which generates the error message:

https://github.com/webpack/webpack/blob/a87d290dd84aeb9190a836b79e1a9d91d9e4a680/lib/ModuleParseError.js#L47-L56

> is there anything ts-loader could be doing differently (for example, providing a source map) so that the line number in the error would be reported correctly?

Instead of reporting only soft errors with `this.emitError(error)` they could report a hard error with `this.callback(error)`. Not sure how this fits in the typescript philosophy and you probably only want this for parsing errors not for type errors.
