### ISSUE TITLE
JsonpTemplatePlugin should create script tag with 'module' attribute for lazy es2015 chunks

### ISSUE THREAD

**Issue by simeyla** [webpack/webpack#10385]
## Feature request

Note: I am using Angular 9 CLI with es2015 bundles and HTTP/2 server push.

**What is the expected behavior?**

When the script tags for **initial** chunks are written to `index.html` they use `module` and `nomodule` to allow the browser to determine the appropriate one. 

eg.

    <script src="/main-es2015.24ec32575701ca957fc1.js" type="module"></script>
    <script src="/main-es5.24ec32575701ca957fc1.js" nomodule defer>

When **deferred** chunks are loaded (eg. for an Angular feature module) the following script tag is added by [JsonpTemplatePlugin](https://github.com/webpack/webpack/blob/master/lib/web/JsonpTemplatePlugin.js):

    <script charset="utf-8" src="/3-es2015.8251cd5df78bdf8f7377.js"></script>

This does not contain the `type="module"` attribute. As a result the browser's ability to efficiently parse the file is not fully realized.

**What is motivation or use case for adding/changing the behavior?**

1) es2015 modules are [not just regular scripts](url) and they shouldn't be loaded with just a plain `script` tag.

> V8 (Chrome's JavaScript engine) parses and compiles modules differently from other JavaScript. <link rel="preload"> doesn't provide any way of indicating that the file being loaded is a module, so all the browser can do is load the file and put it in the cache. Once the script is loaded using a <script type="module"> tag (or it's loaded by another module), the browser parses and compiles the code as a JavaScript module.

Browsers are getting smarter - and in large applications there may be many chunks to download. If the browser knows in advance that a module is being requested it will process it differently and the lazy modules will be able to execute faster.

2) HTTP/2 Server push is made more complicated when mixing 'modules' and 'scripts'. For very advanced performance critical applications push can be used to send not only the initial required chunks, but also commonly used lower priority chunks.

When pushing a module you need to use `<link rel="modulepreload">` so that the [browser knows it's a module](https://developers.google.com/web/updates/2017/12/modulepreload) and can process it more efficiently. If you try to push a file with `modulepreload` but the corresponding `script` tag does not contain a `module` attributes then the file will be downloaded a second time. 

So for instance if using HTTP/2 push to push both `main.js` and `homepage.js` then you must use `rel=modulepreload` for `main.ts` and `rel=preload` to push the lazy chunk `homepage.js` .

3) CORS headers are sent for `main.js` but not for the deferred lazy chunks. This might lead to impossible to debug subtle issues.

eg. for `main` module this is the mode used:

> sec-fetch-dest: script
> sec-fetch-mode: cors

For lazy loaded modules this is the mode used:

> sec-fetch-dest: script
> sec-fetch-mode: no-cors

**How should this be implemented in your opinion?**
I am only a passive user of webpack, but I'm sure there is metadata for a particular deferred chunk available that knows it's a module and can simply add `type="module"`. It wouldn't be necessary to ever add `nomodule` though because for legacy browsers it wouldn't matter.

**Are you willing to work on this yourself?**
Not really knowledgeable enough in webpack.
Also sorry if this issue is actually a problem with the way Angular CLI uses webpack.

**Comment by sokra** [comment]
`output.jsonpScriptType: "module"`

see https://webpack.js.org/configuration/output/#outputjsonpscripttype

**Comment by simeyla** [comment]
@sokra thanks. this was an easy fix for me - I don't need to support IE11 :-)

Out of curiousity have you ever considered an optional lambda that would allow the chunk filename to determine the script type? eg.

    output.jsonpScriptType = (filename) => filename.includes('es2015') ? 'module' : 'text/javascript';

Angular CLI is set up by default to create both `'-es2015` and `'-es5` files so for anyone that needs to support IE11 I think setting `type="module"` won't work.
