### ISSUE TITLE
Using compilation.rebuildModule() on compiler.hooks.emit strange behaviour

### ISSUE THREAD

**Issue by ernestostifano** [webpack/webpack#10392]
Hi everyone!

I just wanted to check if the following is a normal behaviour or something else.

While writing a plugin, I've tapped into `compiler.hooks.emit` and managed to collect an object with information about emitted assets (essentially paths and sizes).

Then my intention was to load that object into an existing module.

I’ve managed to get the target module by looping through `compilation.modules` and to modify a specific loader option to create a reference to my collected object (to be inserted).

Finally I've tried to call `compilation.rebuildModule()`. Loader is successfully called, no errors, no warnings and I think the module is successfully rebuilt including the new data, but final asset (the chunk containing the module) is not updated.

I've read almost every file of Webpack's source code and it is still not clear for me how to correctly trigger a module rebuild. Is it even possible? Could be a feature request? Am I too late in the compilation process to do what I wanted?

I've temporarily solved this by storing the collected data in a json file and then starting again a new compilation that will load it, but it is obviously not an elegant solution.

I'm already working on some documentation improvements to contribute, based on what I've learned studying Webpack and I would not mind to add some information about this issue if resolved.

Thank you very much for your help.

**Comment by sokra** [comment]
> Am I too late in the compilation process to do what I wanted?

Yep that is too late. You can't change modules after chunks were generated and will be emitted. But you can't access emitted files before chunks were generated. That's circular and doesn't work. You could emit an additional file with the data you want to have and read that at runtime.

**Comment by ernestostifano** [comment]
@sokra thank you very much for your response. It is good to know that my guessing was not so inaccurate. I will surely close this issue very soon.

However, I'm still tempted to ask: **is there any way to restart the current compilation form "inside" Webpack?** I mean, currently I'm waiting for the whole process to end and then starting again Webpack from "cold" to be able to load the new data and this is complicated because it behaves differently if watching for development or building for production and both cases must be considered.

Additionally, I can't stop thinking that in watch mode, ulterior rebuilds are pretty fast (after first compilation), maybe because everything is kept in memory and because only changed files and their eventual consequences are considered. That makes me think that somehow a "two-step" single compilation could be possible and it would be faster than two "separated" compilations. Should I continue to elaborate on this or is it a dead-end path?

Thank you again!

**Comment by sokra** [comment]
There is an `needAdditionalSeal` hook, which does the sealing again.

You can use the node.js API and run `run` twice. In watch mode you can trigger a new compilation with `invalidate`.

**Comment by ernestostifano** [comment]
@sokra I've tried to replicate Watching.js by doing something like follows:

```
compiler.hooks.done.tap(
    "MyPlugin",
    () => {
        compiler.compile((err, compilation) => {
            compiler.emitAssets(compilation, () => {
                compiler.emitRecords(() => {});
            });
        });
    }
);
```

Webpack effectively starts compiling again, but final assets are not reflecting changes (I expect new data to be loaded via the native JSON loader).

My attempt was to make Webpack behave as if it was in watch mode, but re-compiling only one time.

**Comment by Krutsch** [comment]
@ernestostifano I was able to do it by using your done hook for restarting the compilation. However, that lead to no console output... Is there a fix for it?
Then, I check in the compilation and buildModule hook, whether we are in the second compilation. If it is the second compilation, then I add a module loader, which will change my files.

```
compiler.hooks.compilation.tap("compilation", (compilation) => {
  compilation.hooks.buildModule.tap("findJSFiles", (module) => {
    if (!isFirstRun && /\.json$/.test(module.resource)) {
      module.loaders.unshift({
        loader: path.resolve(__dirname, "yourloader.js"),
          options: options || {}
        });
      }
    }
  });
});
```

**Comment by ernestostifano** [comment]
@Krutsch what do you mean with ***"no console output"***?

By further analysing Webpack's source code, I've found that to make sure that changes in files are taken into account, you have to purge the internal filesystem by calling `compiler.purgeInputFileSystem()` or `compiler.inputFileSystem.purge(filePath)`, the latest accepts an argument which is the path of to file that you want to remove from the internal filesystem cache (otherwise, all files will be removed from the cache, thus impacting performance).

Additionally, to make sure that the intended module is rebuilt during successive compilations, you have to update the corresponding file change timestamp (as Watcher does when in watch mode) `compiler.fileTimestamps.set(filePath, Date.now())`. (Module last build timestamp will be compared with the file change timestamp to determine if the module needs to be rebuilt) (Maybe @sokra can confirm this).

At the end I was able to fully solve this "issue" by writing a plugin that triggers the second compilation by calling `compiler.compile()` and replicates normal Webpack behaviour in the passed callback. Additionally I discovered a way to ***"freeze"*** every plugin after `shouldEmit` hook while the second compilation completes and then resumes from where the process was left, so for other plugins it is like if nothing happened. Obviously stats are updated each time.

I will publish that plugin as `Webpack-recompile-plugin` once I finish testing and adjusting minor details for production. Then I will close this.

**Comment by Krutsch** [comment]
@ernestostifano Sorry, I meant that webpack does not display any stats (size of emitted assets, etc.) when I am using `compiler.compile()` in the done hook.

Cool, thanks for the update, looking forward for your plugin

**Comment by ernestostifano** [comment]
@Krutsch that is because at `done`, everything has been... ***"done"***, the only pending task at that point is to call the final callback. So, stats has already been created. That is why, in the `compiler.compile()` callback I had to repeat all the operations that Webpack normally does after that call. (Basically call some hooks, handle responses and update stats).

If you want to temporarily fix your issue, you have to to the following:

In the `done` hook, you will receive the generated stats instance object as argument. You can't return a different stat object, but you can leverage on references and modify the passed one.

Create the updated stats passing the latest compilation:

```js
const {Stats} = require('webpack');

function getNewStats(compilation) {
    const stats = compilation ? new Stats(compilation) : null;
    if (stats) {
        stats.startTime = this.startTime;
        stats.endTime = Date.now();
    }
    return (stats);
}
```

And the update existing stats using new one:

```js
function updateStats(existingStats, newStats) {
    for (const i in newStats) {
        if (!newStats.hasOwnProperty(i)) {
            continue;
        }
        existingStats[i] = newStats[i];
    }
}
```

That's it...

**Comment by flytam** [comment]
> @Krutsch what do you mean with _**"no console output"**_?
> 
> By further analysing Webpack's source code, I've found that to make sure that changes in files are taken into account, you have to purge the internal filesystem by calling `compiler.purgeInputFileSystem()` or `compiler.inputFileSystem.purge(filePath)`, the latest accepts an argument which is the path of to file that you want to remove from the internal filesystem cache (otherwise, all files will be removed from the cache, thus impacting performance).
> 
> Additionally, to make sure that the intended module is rebuilt during successive compilations, you have to update the corresponding file change timestamp (as Watcher does when in watch mode) `compiler.fileTimestamps.set(filePath, Date.now())`. (Module last build timestamp will be compared with the file change timestamp to determine if the module needs to be rebuilt) (Maybe @sokra can confirm this).
> 
> At the end I was able to fully solve this "issue" by writing a plugin that triggers the second compilation by calling `compiler.compile()` and replicates normal Webpack behaviour in the passed callback. Additionally I discovered a way to _**"freeze"**_ every plugin after `shouldEmit` hook while the second compilation completes and then resumes from where the process was left, so for other plugins it is like if nothing happened. Obviously stats are updated each time.
> 
> I will publish that plugin as `recompile-webpack-plugin` once I finish testing and adjusting minor details for production. Then I will close this.

Hi, I recently came across a similar requirement, can you please share the implementation related to this. Trigger the `compiler.compile` directly inside the `done`  hooks?
