### ISSUE TITLE
Webpack is compiling unused code

### ISSUE THREAD

**Issue by johnsky95** [webpack/webpack#10395]
# Bug report

**What is the current behavior?**
Unused functions are compiled on production

**If the current behavior is a bug, please provide the steps to reproduce.**
https://github.com/johnsky95/webpack_dead_code

I created a demo app where you can run "webpack -p" and check the "bundle.js" on "dist" folder. The unused method called "sayBye()" is still compiled, even tho is not used at all.

**What is the expected behavior?**
I expect "sayBye()" method which is not used at all, not to be included on production code.

**Other relevant information:**
webpack version:  4.41.5
Node.js version: 11.12.0
Operating System: Windows 10
Additional tools:

**Comment by sokra** [comment]
Methods on the prototype (class methods) can't not be analysed.

You can use direct functions for it to be able to remove them:

``` js
export function sayHello() {
        console.log('hello');
    }

export function sayBye() {
        console.log('bye');
    }
```

**Comment by johnsky95** [comment]
> Methods on the prototype (class methods) can't not be analysed.
> 
> You can use direct functions for it to be able to remove them:
> 
> ```js
> export function sayHello() {
>         console.log('hello');
>     }
> 
> export function sayBye() {
>         console.log('bye');
>     }
> ```

Hi Sokra. Thanks for your feedback.

**Comment by evilebottnawi** [comment]
Answered
