### ISSUE TITLE
Used to react - navtive

### ISSUE THREAD

**Issue by Holdor1** [webpack/webpack#10398]
I wanted to package the reaction-native project and use it directly on the web side, but kept reporting errors during bundle and startup，I also want to package the node_module。Here are my configurations
[webpack.config.dev.txt](https://github.com/webpack/webpack/files/4213665/webpack.config.dev.txt)

[package.json.txt](https://github.com/webpack/webpack/files/4213676/package.json.txt)
I am a novice and have used many other people's components, so I will report errors when starting and packaging. How can I solve this problem? Thank you
[erro.txt](https://github.com/webpack/webpack/files/4213697/erro.txt)

**Comment by montogeek** [comment]
I encourage you to ask your question on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

I’m closing for these reasons.
