### ISSUE TITLE
concatenateModules breaks circular dependency

### ISSUE THREAD

**Issue by SystemParadox** [webpack/webpack#10409]
# Bug report

**What is the current behavior?**

My app works fine normally, but setting `optimization: { concatenateModules: true }` causes it to break the resolution order of the circular dependency.

**If the current behavior is a bug, please provide the steps to reproduce.**

Consider the following example:

```
// lib/a.js
import cts from './cts';
export default cts.connectData(function () {});

// lib/b.js
import cts from './cts';
export function b() {
    setImmediate();
}

// lib/c.js
import cts from './cts';
import a from './a';
export function c() {}

// lib/cts.js
import * as cts from './cts';
export { cts as default };
export function connectData() {}
export { b } from './b';
export { c } from './c';

// lib/main.js
import cts from './cts';
import a from './a';
```

With `concatenateModules: true`, running the bundle (created from `lib/main.js`) results in `TypeError: Cannot read property 'connectData' of undefined`. Something has gone wrong with the concatenation, causing the cts default export to not be defined early enough.

I have reduced the example above to the bare minimum. Changing almost anything will cause it to work even with `concatenateModules`. It seems to be related to the concatenation bailout which is caused by the reference to setInterval.

**What is the expected behavior?**

`concatenateModules` should not cause working apps to break. Perhaps this is a particularly pathological example, but it's a bit concerning when it works in development and setting `mode: 'production'` causes it to break.

It took me a very long time to reduce this to a sensible example - hopefully this is useful!

On a side note, is there any better way to ensure that the default export gets set to the module namespace before processing any of the other imports/exports? It feels very fragile, and despite being such a common use case the spec appears to be lacking here.

**Other relevant information:**
webpack version: 4.41.6
Node.js version: 10.15.2
Operating System: Linux
Additional tools: None

**Comment by sokra** [comment]
> It took me a very long time to reduce this to a sensible example - hopefully this is useful!

very useful

> On a side note, is there any better way to ensure that the default export gets set to the module namespace before processing any of the other imports/exports? It feels very fragile, and despite being such a common use case the spec appears to be lacking here.

Seems fine. It's a good way.

**Comment by sokra** [comment]
This is more work then expected...

**Comment by SystemParadox** [comment]
Thanks so much for looking at this!

I was looking at testing but I'm a bit confused - master seems to be for webpack 5? Is there going to be a fix for webpack 4?
