### ISSUE TITLE
When I run the development environment, splitChunks seem to remove all the js code

### ISSUE THREAD

**Issue by xpromise** [webpack/webpack#10419]
# Bug report

When I run the development environment, splitChunks seem to remove all the js code。
My webpack.config.js is as follows:
```js
const HtmlWebpackPlugin = require('html-webpack-plugin');
const { CleanWebpackPlugin } = require('clean-webpack-plugin');
const webpack = require('webpack');
const { resolve } = require('path');

const NODE_ENV = process.env.NODE_ENV;

const isEnvDev = NODE_ENV === 'development';
const isEnvProd = NODE_ENV === 'production';

module.exports = {
  entry: './src/index.js',
  output: {
    path: isEnvProd ? resolve(__dirname, '../build') : undefined,
    filename: isEnvProd
      ? 'static/js/[name].[contenthash:10].js'
      : 'static/js/bundle.js',
    chunkFilename: isEnvProd
      ? 'static/js/[name].[contenthash:10].chunk.js'
      : 'static/js/[name].chunk.js',
    publicPath: '/'
  },
  plugins: [
    new HtmlWebpackPlugin({
      template: './public/index.html',
      minify: isEnvProd
        ? { collapseWhitespace: true, removeComments: true }
        : undefined
    }),
    isEnvProd && new CleanWebpackPlugin(),
    isEnvDev && new webpack.HotModuleReplacementPlugin()
  ].filter(Boolean),
  mode: NODE_ENV,
  devServer: {
    compress: true,
    contentBase: resolve(__dirname, '../public'),
    hot: true,
    host: 'localhost',
    port: 3000,
    open: true
  },
  optimization: {
    splitChunks: {
      chunks: 'all',
      name: false
    }
  }
};
```
When I run `cross-env NODE_ENV=development webpack-dev-server --config ./config/webpack.config.js`,  I opened the browser and found no console.

But in production, it's OK

code for details -->  https://github.com/xpromise/webpack-bug-report

**What is the expected behavior?**
In the development environment I run `npm start`, and the browser should have the console result

**Other relevant information:**
webpack version:  4.41.6
Node.js version: 12.13.0
Operating System: window10
Additional tools: VS Code

**Comment by evilebottnawi** [comment]
You have invalid configuration:
- You don't need `isEnvDev && new webpack.HotModuleReplacementPlugin()`, webpack-dev-server already enable that plugin when the `hot` is `true` (recommend)
- Move `public/index.html` to other location, for example `templates/index.html` (recommend)
- Change `contentBase: resolve(__dirname, '../public')` to `contentBase: resolve(__dirname, '../dist')`, by default webpack emit all assets to the `dist` directory 
- Comment `name: false` in the `splitChunks` option

Anyway, thanks for the issue, look bug in `HtmlWebpackPlugin`, that plugin don't include all chunks when the `name` is `false`

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/jantimon/html-webpack-plugin/issues/1347

**Comment by xpromise** [comment]
Thanks， It's OK now
