### ISSUE TITLE
Modifying filenames based on environment?

### ISSUE THREAD

**Issue by braco** [webpack/webpack#1041]
I see this used to be resolve.postprocess, but what is it now?

With
```
var foo = require('foo.js');
```

load
```
"foo.{ENV}.js"
```
if available, without having to modify the original require statement.

Don't see anything in the docs, sorry if I missed it.

**Comment by braco** [comment]
I guess this is the way to do it now:

```
var envifyPath, tryPath;

envifyPath = function(str) {
  return str.replace(/(\.\w+)$/, "." + process.env.NODE_ENV + "$&");
};

tryPath = function(req) {
  var tryEnv;
  if (!process.env.NODE_ENV) {
    return req;
  }
  tryEnv = envifyPath(req.userRequest);
  if (fs.existsSync(tryEnv)) {
    req.request = envifyPath(req.request);
  }
  return req;
};
```

in webpack config:

```
 plugins: [new webpack.NormalModuleReplacementPlugin(/\.js/, tryPath)]
```

**Comment by TN1ck** [comment]
To clarify this solution:

if you require foo without extension: `var foo = require('foo');`, webpack needs to resolve the extensions. The first element in the resolve-extensions-array that yields a match will be used.

So to serve to different files depending on the environment-variables, you could for example use:
`['.prod.js', '.js', '']` for a production system and `['staging.js', '.js', '']` for a staging system.
