### ISSUE TITLE
DefinePlugin doesn't handle arrays & undefined correctly

### ISSUE THREAD

**Issue by SassNinja** [webpack/webpack#10425]
# Bug report

**What is the current behavior?**

If providing a config with an array in it the DefinePlugin does not resolve it correctly.
If accessing an undefined key object the DefinePlugin does return the whole object.

**If the current behavior is a bug, please provide the steps to reproduce.**

```js
// webpack.config.js
module.exports = {
  plugins: [
    new webpack.DefinePlugin({
      FOO: {
        name: "'bar'",
        fruits: ["'apple'", "'lemon'", "'orange'"]
      }
	})
  ]
}

// main.js
console.log(FOO.name);
console.log(FOO.fruits);
console.log(FOO.xxxxx);
```

**What is the expected behavior?**

I expect the following

```
console.log('bar');
console.log(['apple', 'lemon', 'orange']);
console.log();
```
but I get
```
console.log('bar');
console.log(Object({"0":'apple',"1":'lemon',"2":'orange'}));
console.log(Object({"name":'bar',"fruits":Object({"0":'apple',"1":'lemon',"2":'orange'})}).xxxxx);
```

**Other relevant information:**
webpack version: 4.41.6 & 5.0.0-beta.13
Node.js version: v12.14.1
Operating System: Mac OS X
Additional tools:

**Comment by evilebottnawi** [comment]
webpack@5 supports array, how we should handle `undefined`?

**Comment by SassNinja** [comment]
> webpack@5 supports arrays
no, it doesn't because I define an array in `FOO.fruits` and get an object after compilation (see my example)

> how we should handle undefined?
I'd expect to not return anything if the key doesn't match (instead of returning the whole object as fallback)

I'm trying to use this plugin to use parts of the server config in my frontend code and really don't wanna see the whole config being included in case of a typo.

**Comment by evilebottnawi** [comment]
> no, it doesn't because I define an array in FOO.fruits and get an object after compilation (see my example)

https://github.com/webpack/webpack/pull/9942

just not released

> I'd expect to not return anything if the key doesn't match (instead of returning the whole object as fallback)

Make sense

**Comment by SassNinja** [comment]
> just not released

I've missed that one (did only check the issues) – cool!

> Make sense

Shall I submit a PR to fix this?

**Comment by evilebottnawi** [comment]
Yes, let's do it

**Comment by evilebottnawi** [comment]
@SassNinja for webpack@5 it is already solved, you can look at tests

**Comment by evilebottnawi** [comment]
@SassNinja now `DefinePlugin` works for all types except `Symbol`

**Comment by SassNinja** [comment]
Awesome!

Thank you @evilebottnawi
