### ISSUE TITLE
Webpack gives build error on private github repository

### ISSUE THREAD

**Issue by rvv-persistent** [webpack/webpack#10428]
Webpack gives build error while using github private repository as a package

```ERROR in ./node_modules/ibmcloud-appid/node_modules/streamroller/lib/RollingFileStream.js
Module not found: Error: Can't resolve 'child_process' in '/home/travis/build```

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
