### ISSUE TITLE
bower.json takes precedence over package.json when using DirectoryDescriptionFilePlugin

### ISSUE THREAD

**Issue by Morhaus** [webpack/webpack#1042]
Some of my modules installed from npm also define a bower.json file. When using the following plugin,  the `main` field from their `bower.json` will be used to resolve them, when I'd expect webpack to use `package.json`.

```
new webpack.ResolverPlugin(
  new webpack.ResolverPlugin.DirectoryDescriptionFilePlugin('bower.json', ['main'])
)
```

**Comment by yaru22** [comment]
I have the same issue (from requiring `rx` package). What's the proper way to solve this @sokra?

**Comment by fenivana** [comment]
Temporary approach:

```js
plugins: [
    new webpack.ResolverPlugin(
      new webpack.ResolverPlugin.DirectoryDescriptionFilePlugin('package.json', ['main'])
    ),

    new webpack.ResolverPlugin(
      new webpack.ResolverPlugin.DirectoryDescriptionFilePlugin('bower.json', ['main'])
    )
]
```

**Comment by jupl** [comment]
@fenivana Nice. I would add for the `browser` property as there are some NPM packages that use `main` for server-side and `browser` for client-side.

**Comment by lukescott** [comment]
I tried what @fenivana suggests, but it isn't working for me. It is now using package.json in bower_components. What I actually need is:

bower_components -> use bower.json only
node_modules -> use package.json only

**Comment by bebraw** [comment]
Can you try with webpack 2 beta?

**Comment by TheLarkInn** [comment]
I'm going to close this as this was from webpack 1. 

If this is still an issue, please update to webpack 3, resubmit a new issue with the information listed in our issue template (version, repro repo, etc.)
