### ISSUE TITLE
optimization proposal: append to body in batches

### ISSUE THREAD

**Issue by shishirarora3** [webpack/webpack#10436]
This is a proposal to optimize DOM access, make the bootstrap runtime webpack code, faster.

 When we  append invidual chunks to document head, in bootsrap part, [here](https://github.com/webpack/webpack/blob/master/lib/web/JsonpChunkLoadingRuntimeModule.js#L116), instead doing it one at a time, we should do it in batch, as DOM access is a slow process and should be limited. I am specifically looking at optimising the [prefetch](https://github.com/webpack/webpack/blob/master/lib/web/JsonpChunkLoadingRuntimeModule.js#L151) and the [preload](https://github.com/webpack/webpack/blob/master/lib/web/JsonpChunkLoadingRuntimeModule.js#L199) DOM appends.

So, instead of `document.head.appendChild(script);`, we can use 

````
fragment = document.createDocumentFragment();
fragment.appendChild(script); //do for all chunks/scripts
document.head.appendChild(fragment); //and then finally add that fragment to DOM

**Comment by sokra** [comment]
I'm pretty sure this is not a bottleneck, in worst case we are adding like 10 script tags.
