### ISSUE TITLE
Export flags for webpack-cli from webpack

### ISSUE THREAD

**Issue by rishabh3112** [webpack/webpack#10435]
## Feature request
We are looking to import the flags related to configuration from webpack.
https://github.com/webpack/webpack-cli/issues/1241 has more information on this feature.

**What is the expected behavior?**
Have flags managed at the webpack itself

**What is motivation or use case for adding/changing the behavior?**
This feature was suggested by @sokra and @evilebottnawi 

**How should this be implemented in your opinion?**
A real javascript object should be exported which will be utilized by the cli.
The flags should be in the form we have here https://github.com/webpack/webpack-cli/blob/next/packages/webpack-cli/lib/utils/cli-flags.js

**Are you willing to work on this yourself?**
yes. (@evilebottnawi is also willing to work on it)

**Comment by sokra** [comment]
done
