### ISSUE TITLE
Fact checking a Medium.com article

### ISSUE THREAD

**Issue by ORESoftware** [webpack/webpack#10437]
I just wrote this article on HMR in a React app:
https://medium.com/@the1mills/hot-module-replacement-for-a-react-app-d5e0a24c0bc6

could use fact checkers on it. One question I have.
When root.jsx changes - index.jsx is listening for those changes. *However*, it's possible that index.jsx also changes in Webpack, if the file on the fs changes. So what happens then? Are there then multiple references to index.jsx in the webpack build? Perhaps not (luckily), since the front-end is not accepting changes to index.jsx (the only change to index.jsx will happen on page refresh).

**Comment by sokra** [comment]
`index.jsx` is unaccepted and normally this would cause HMR to fail to update which usually triggers a full-reload. But you are using webpack-hot-middleware which explicitly ignores updates to unaccepted files:

https://github.com/webpack-contrib/webpack-hot-middleware/blob/cb29abb9dde435a1ac8e9b19f82d7d36b1093198/process-update.js#L18

In this case any update to the unaccepted module is ignored and it will keep running the old version until you manually reload the page.

There should be a warning in the console in this case:

https://github.com/webpack-contrib/webpack-hot-middleware/blob/cb29abb9dde435a1ac8e9b19f82d7d36b1093198/process-update.js#L22-L24

There shouldn't be two instances of `index.jsx`. 

---

You could use self accepting to accept updates of `index.jsx`:

``` js
import Root from './root.jsx'

ReactDOM.render(
  <Root/>,
  document.getElementById('app')
);

if(module.hot) module.hot.accept();
```

This will reevaluate the module on update.

---

Here a little simplification to your post: (make sure that you don't transpile ESM to CJS with babel)

``` diff
 import Root from './root.jsx'
 
 ReactDOM.render(
   <Root/>,
   document.getElementById('app')
 );
 
 if (module.hot) {
   // this is necessary for HMR, the only thing we need for the whole app which is nice
   module.hot.accept('./root.jsx', () => {
-    const NextRootContainer = require('./root.jsx').default;
-    ReactDOM.render(<NextRootContainer/>, document.getElementById('app'));
+    ReactDOM.render(<Root/>, document.getElementById('app'));
   })
 }
```

`import`s are live-bindings and will automatically point to the new module after `accept`.

**Comment by evilebottnawi** [comment]
Answer above
