### ISSUE TITLE
New entry.dependOn feature seems not supported in schema

### ISSUE THREAD

**Issue by shameleo** [webpack/webpack#10433]
# Bug report

**What is the current behavior?**
Error:
```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.entry should be one of these:
   function | object { <key>: non-empty string | [non-empty string] } | non-empty string | [non-empty string]
...
```

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Copy example directory (https://github.com/webpack/webpack/tree/22b6abdd4f6d70d27dc87d8d3b0eeb2216fd4bfc/examples/code-splitting-depend-on-simple)
2. `npm install webpack webpack-cli`
3. run webpack

**What is the expected behavior?**
According to docs entry can be
```
string [string] object = { <key> string | [string] | object = { import string | [string], dependOn string | [string], filename string }} (function() => string | [string] | object = { <key> string | [string] } | object = { import string | [string], dependOn string | [string], filename string })
```
so schema seems out of sync

**Other relevant information:**
webpack version:  4.41.6 (latest release)

**Comment by smelukov** [comment]
`dependOn`  will available since webpack@5.0.0-beta.14
webpack 4 does not support it

**Comment by shameleo** [comment]
I've mistaken because searching on webpack docs provides results for v5 (or both?) even if v4.webpack.js.org/ is opened at the moment. It can be misleading.

**Comment by smelukov** [comment]
There is an issue about it https://github.com/webpack/webpack.js.org/issues/3366

**Comment by kote-isaev** [comment]
This feature about dependOn etc is referenced at webpack.js.org at Dependency Management page without any mentioning of min beta version
