### ISSUE TITLE
share hash with 2 export configs

### ISSUE THREAD

**Issue by darul75** [webpack/webpack#1043]
Hi,

I am using 2 configurations with one for client side, other for server side into the same config file.

make.webpack.config.js
```
module.exports = [config1, config2] // functions exporting config...
```

When launching both at same time from my main production bundler:
```
module.exports = [require('./make.webpack.config)[1]({ 
     production: true
   }), 
   require('./make.webpack.config)[0]({ 
     production: true 
   }) 
 ];
```
As a result I can see 2 child process and would like computed [hash] to be the shared and not different, is it possible ?

My first bundle is a react client one
My second bundle is a react express server one rendering React components.. and this is to get same images resources hash names when rendering from client and server.

```
// { test: /\.(jpe?g|png|gif|svg|woff|eot|ttf)$/, loader: 'url?limit=10000&name=[sha512:hash:base64:7].[ext]' }
```
https://github.com/darul75/webye/blob/master/conf/webpack-config.js

Thx,

Julien

**Comment by sokra** [comment]
Why should they be shared? It doesn't make sense to generate to different bundles with the same hash...

**Comment by darul75** [comment]
Yes it has no sense but I can not find a way to get an express server rendering a react component with image id similar to client bundle and it was my only solution working until now ;) 

https://github.com/webpack/react-starter/issues/75

So I have used 2 webpack configs.

Is is better at the end to use only one config to bundle client and server with multi entry in case of production deployment:

 * One entry point to client app react file : app.jsx
 * Other entry to server file rendering react components : server.js

**Comment by sokra** [comment]
Not sure what you are trying to do, but in react-starter this works all fine. Just use the same loaders (file-loader or url-loader) for server and client build and it generates the same components.

multi-entry doesn't work with server and client, because you need different target settings.
mulit-config works. It's the same as starting webpack multiple times, but with watchers and fs cache shared.

**Comment by darul75** [comment]
well it looks tricky for me too and I am not sure to understand everything but I try... :-1: 

In dev mode I am using only clientApp with hot reload and dev-server it works like a charm and it is awesome.

In production mode I am using my own server code rendering react but I faced image rendering issue...html template rendered by express include client bundle.js and renders view on server side too. but Image id in not the same or missing if I skip it with a test on server side. It looks like it is mandatory that server renders exact same html than client side react js code => logical.

So I was exporting 2 configs, each returning configurations client or server one
module.exports = [clientApp, serverApp];

client
https://github.com/darul75/webye/blob/master/conf/webpack-config.js#L47

server
https://github.com/darul75/webye/blob/master/conf/webpack-config.js#L115

then my production target launch both of it with production options:

https://github.com/darul75/webye/blob/master/conf/webpack-prod.js

at the end it produces one app.js side and one server.js all bundle by webpack..but still just image hash issue

"if you have failed redefine success" :)

**Comment by darul75** [comment]
I was inspired by this multi configuration https://github.com/webpack/webpack/tree/master/examples/multi-compiler

One for client bundle : app.js
One for server bundle : server.js

Both rendering react component.

- Client send HTTP request
- Server express with server.js renders react component and send html remplate including app.js
- Client receive html generated on server side and include script app.js

React is API both client/server are rendering same content, except for images if images source id in bundle not the same.

**Comment by darul75** [comment]
ok fixed after several tries image have same generated hash
