### ISSUE TITLE
Webpack HMR almost works - but I am using `webpack` not `webpack-dev-server`

### ISSUE THREAD

**Issue by ORESoftware** [webpack/webpack#10434]
I am using `webpack --hot --watch` not `webpack-dev-server --hot`

I am having this issue:
https://stackoverflow.com/questions/60356923/hot-module-replacement-hmr-is-not-working-in-react-app

it looks like this:

```jsx
ReactDOM.render(
  <Root store={store} onEnterRedir={onEnterRedir}/>,
  document.getElementById('app')
);

if (module.hot) {
  console.log('the module IS hot');   // works - this gets logged
  module.hot.accept('./root.jsx', () => {
    console.log('the module was reloaded.'); // doesn't work - doesn't get logged
    const NextRootContainer = require('./root.jsx').default;
    ReactDOM.render(<NextRootContainer onEnterRedir={onEnterRedir} store={store}/>, document.getElementById('app'));
  })
}
```

I think I know what the problem is - the problem is likely that `webpack` as opposed to `webpack-dev-server` doesn't have a websocket server that can notify the browser when a module has changed.

Is that most likely the problem? Is there any way to replicate the websocket server of webpack-dev-server with `webpack`?

I was thinking something like this:

```bash
webpack --watch --hot |  notify_client
```

so I could notify the client manually when there are changes?  but that makes me wonder - what is the --hot flag for then? It seems to enable `module.hot` on the front-end, but doesn't provide a server to ping the client when files change?

**Comment by sokra** [comment]
`--hot` enables the API when using only webpack.

The dev server uses the API to trigger the process, but you also use the API to trigger hot update.

See `webpack/hot/...` for possible implementations. E.g. add `webpack/hot/poll?1000` to your entry point for a polling implementation that doesn't need a websocket

**Comment by evilebottnawi** [comment]
Answer above
