### ISSUE TITLE
Hash Module Identifier by full path instead of realtive path (unique in a monorepo)

### ISSUE THREAD

**Issue by KnisterPeter** [webpack/webpack#10438]
## Feature request

I would see the need to create a module identifier based on the full path of a file (or at least on the 'full' relative path inside a monorepo.
Currently we are building multiple webpack bundles out of our repository and while that works fine in the first place, there are collisions when code splitting is activated.
E.g. if there are two apps with an entrypoint of `src/index.js` they both will get the same module identifier when using `HashedModuleIdsPlugin` (other plugins don't work either).

**What is the expected behavior?**

There should be a way to create module identifiers uniquely per file in a monorepository (or maybe even on a absolute path).

**What is motivation or use case for adding/changing the behavior?**

As stated above we are building multiple apps from a repository and they may have the same entrypoint. If we are splitting the code and loading two app on one page, then the identifiers will conflict and create bugs.

**How should this be implemented in your opinion?**

There are different solutions which could be seen here.
* First (and perfered by me) would be to add a configurable parameter to `HashedModuleIdsPlugin` which could be added to the hash as well (during hash calculation). That could be seen as a seed for the hashing.
* A separate plugin could be created creating unique hashes.

**Are you willing to work on this yourself?**
yes sure, I'd be glad to create a pr for this

**Comment by sokra** [comment]
ids are only unique in a single compilation, which is fine this way. When multiple webpack builds are running on the same page you must make sure that their jsonp function name doesn't collide (set `output.jsonpFunction` to a unique name). That's the only global thing webpack uses. Module/Chunk ids do not need to be unique across builds.

Maybe also make sure that filenames doesn't collide.

**Comment by KnisterPeter** [comment]
Great. That will solve it too. I wasn't aware of setting the jsonp name.
Thank you
