### ISSUE TITLE
Angular 9 - Problem with paths defined in tsconfig

### ISSUE THREAD

**Issue by MDzyga** [webpack/webpack#10444]
# Bug report
Hi,
I have an application with Angular Universal 9 and try to deploy it on Azure. 

I think it can be related with this closed issue: https://github.com/symfony/webpack-encore/issues/663

**What is the current behavior?**
When I execute `ng run universal:build:dev && ng run universal:server:dev && webpack --progress --colors` I got an errors like:

```
Module not found: Error: Can't resolve 'environments/environment'
Module not found: Error: Can't resolve 'app/app.const'
Module not found: Error: Can't resolve '@trackShared/preloaded-section'
```
It looks like webpack doesn't import paths. 

**If the current behavior is a bug, please provide the steps to reproduce.**
I prepared repository with instructions how to get to the problem.
https://github.com/MDzyga/universal

**What is the expected behavior?**
I suppose after building app I will be able to deploy my solution on Azure and it will work. Currently it doesn't.

**Other relevant information:**
"typescript": "~3.7.5",
"webpack": "^4.41.6",
"webpack-bundle-analyzer": "3.6.0",
"webpack-cli": "^3.3.11",
"webpack-node-externals": "1.7.2"
"@nguniversal/common": "^9.0.1",
"@nguniversal/express-engine": "^9.0.1",
Angular 9

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by MDzyga** [comment]
@sokra I created a repo with steps to reprocude a problem (in readme file)
https://github.com/MDzyga/universal

**Comment by MDzyga** [comment]
@sokra Could you help me with this issue?

**Comment by MDzyga** [comment]
I closed this issue because I needn't to use webpack to create server.js.
I had to fix web.config and server.ts file
