### ISSUE TITLE
webpackIgnore prevents polyfilling of dynamic import

### ISSUE THREAD

**Issue by beckerei** [webpack/webpack#10446]
# Bug report

**What is the current behavior?**

```js
import( /* webpackIgnore: true */ 'https://external.site/script.js')
```

should not be interpreted by webpack (which works), but it also does not get transpiled correctly using babel-loader.

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/beckerei/webpack-babel-dynamic-import

There is noch much needed besides webpack, babel-loader and a correct browserlist (so that import should get polyfilled)

It seems that the line containing webpackIgnore is not run through the loaders as well.

It's kind of hard to find out what exactly webpackIgnore does, it is only ever found in context with import. What does it actually do?

You can find the output from webpack under https://github.com/beckerei/webpack-babel-dynamic-import/blob/master/dist/main.js it still contains import()

**What is the expected behavior?**

See how the code should be transformed in here https://babeljs.io/repl#?browsers=%3E%202%25&build=&builtIns=false&spec=false&loose=false&code_lz=FASwtgDg9gTgLgCgAQHoBUSDuBTARhAQwGMBrASQHMA7WbALiThgFdsk0UkByACzjggBnOihTYAHnGwwqBADYA6QSCkpBRGCAhwFAK0FcAlAG5gQA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Cenv&prettier=false&targets=&version=7.8.4&externalPlugins=

Babels preset-env can polyfill import now by default, but adding the import polfyfill plugin does not change the webpack output.

**Other relevant information:**
webpack version:  4.41.6
Node.js version: 13.8.0
Operating System: OSX
Additional tools: babel-loader@8.0.6, @babel/preset-env@7.8.4

**Comment by sokra** [comment]
> It's kind of hard to find out what exactly webpackIgnore does, it is only ever found in context with import. What does it actually do?

I instructs webpack to do nothing to this import() so it stay an `import()` at runtime. Which seem to work correct, but doesn't seem to be what you want to do?

Babel can transpile the `import()` to a `require` call, which doesn't make sense in context of webpack.

What are you trying to archive?

**Comment by beckerei** [comment]
Okay maybe require is not correct either,  but the setup for the babel rpl and the loader should be the same. So does webpackIgnore prevent babel-loader from reading/parsing that line in any way?

with babel 7.5. preset-env comes with dynamic import polyfills by default 
https://babeljs.io/blog/2019/07/03/7.5.0#dynamic-import-9552-https-githubcom-babel-babel-pull-9552-and-10109-https-githubcom-babel-babel-pull-10109

So this should be transformed in some way. Or am I completely wrong here? Trying to figure out if this is a webpack issues, a issue with babel(-loader) or myself :D

**Comment by sokra** [comment]
> with babel 7.5. preset-env comes with dynamic import polyfills by default
> https://babeljs.io/blog/2019/07/03/7.5.0#dynamic-import-9552-https-githubcom-babel-babel-pull-9552-and-10109-https-githubcom-babel-babel-pull-10109

> If you are using @babel/preset-env, dynamic import support will be enabled by default. You don't need to worry about webpack or rollup support, since both babel-loader and rollup-plugin-babel automatically disable the Babel transform to allow the bundler to handle it correctly.

babel-loader is different than raw babel

**Comment by beckerei** [comment]
Okay so webpack should handle the import correctly? This usually works fine for module imports, but breaks when importing from external url. The error there is fine as well:
```
Module not found: Error: Can't resolve 'https://external.site/script.js'
```

Should webpack handle this case? Or is there a way to work around this, using the import syntax.

importing from external urls works fine in the browser (Chrome, Firefox) supporting dynamic imports.

**Comment by sokra** [comment]
> Should webpack handle this case?

No, webpack is a static module bundler and not a (runtime) module loader. It only processes modules on your local disk, and does not allow loading modules from external sources by default.

You can indeed use `webpackIgnore: true` to keep the `import()` and let the browser handle the module loading. That would work and doesn't require any kind of polyfilling from babel. (But check the browser support)

There are also other runtime module loaders which can be used at runtime to load modules from external source, e. g. for ESM-like syntax you can use System.js.

**Comment by krosthw** [comment]
I have the same issue... Have you any update?

**Comment by beckerei** [comment]
Depends on what you mean by update, but yes we worked around it.
We do not want to add systemjs for such a minor use case.

We are using react, and creating a script tag on the fly like so:

```js
  useEffect(() => {
    const script = document.createElement('script');
    script.src = `https://external.site/script.js`;

    script.onload = () => {
      // put what you normally want to put in the then() block of a dynamic import
      });
    const scriptTag = document.body.appendChild(script);

    return () => {
      document.body.removeChild(scriptTag);
    };
  }, []);
```

It's not as smooth as dynamic import but works fine. Should be easy to adopt with any other framework.

**Comment by krosthw** [comment]
Thanks.
I have a React Component inside of the _script.js_. 
Actually, my code is:

       component = React.lazy(() => import(/* webpackIgnore: true */ `https://external.site/script.js`)); 
       ...

       render(){
       ...
               <component />

But the import doesn't work.
How can I load component with your solution?

**Comment by beckerei** [comment]
I'm not sure you can import react components with the method I described above. We don't import a component just a 3rd party script, which has nothing to do with react.

You might be interested in webpacks module federation plugin, read about it https://itnext.io/webpack-5-module-federation-a-game-changer-to-javascript-architecture-bcdd30e02669

As I'm unfamiliar with how exactly systemjs works you might want to give this a try.

**Comment by krosthw** [comment]
> You might be interested in webpacks module federation plugin, read about it https://itnext.io/webpack-5-module-federation-a-game-changer-to-javascript-architecture-bcdd30e02669

thanks for the help, this is exactly what i am looking for!

**Comment by beckerei** [comment]
I'll close this now. Seems only fair as it's not an webpack issue, it should not count towards the open issue count 👍
