### ISSUE TITLE
Make webpackJsonpCallback unique by default

### ISSUE THREAD

**Issue by wegry** [webpack/webpack#10441]
## Feature request

**What is the expected behavior?**

Multiple webpack bundles shouldn't stomp on each other when using chunking.

**What is motivation or use case for adding/changing the behavior?**

We're exploring the idea of multiple webpack bundles being pulled in by the same web app. My company uses quite a bit of Angular, which doesn't open up the ability to tweak https://webpack.js.org/configuration/output/#outputjsonpfunction without quite a bit of effort.

Related: #3791 

**How should this be implemented in your opinion?**

I'm not sure.

**Are you willing to work on this yourself?**

If there's a relatively straightforward way to implement it, yes.

**Comment by sokra** [comment]
It must be a global. That's the whole idea of this variable. Multiple scripts (chunks) need to access it to communicate with each other.

**Comment by evilebottnawi** [comment]
@sokra I think @wegry wants to do it unique by default, based on my experience most of configurations have the overridden option based on name of application from `package.json`

**Comment by wegry** [comment]
@sokra @evilebottnawi is correct. I've changed the title to reflect that.

**Comment by sokra** [comment]
Ah ok now I understand. That's a good idea.
