### ISSUE TITLE
WebPack fails to load ngTable due to previous minfication

### ISSUE THREAD

**Issue by BonsaiDen** [webpack/webpack#1044]
I'm trying to load `ng-table` via bower-webpack, this all works fine as the module is correctly found and included in the WebPack bundle, however once it is required the following error is thrown on the console:

```Uncaught ReferenceError: returntrue is not defined```

It seems like the source gets corrupted during compilation, as inspecting the bundle yields the following line of code:

```javascript
!function(a,b){"use strict";returntrue?void !(__WEBPACK_AMD_DEFINE_ARRAY__ = [__webpack_require__(/*! angular */ 13)], ..... 

```

The original source is already modified and adding a space in front of the `"function"` string gets rid of the above error.

```javascript
/*! ngTable v0.5.3 by Vitalii Savchuk(esvit666@gmail.com) - https://github.com/esvit/ng-table - New BSD License */

!function(a,b){"use strict";return"function"==typeof define&&define.amd?void define(["angular"], ....
```

**Comment by jsg2021** [comment]
@sokra I just hit this in webpack 4... With `babel-preset-minify` in the babel loader's config it produces this exact scenario with passed code from this [file](https://github.com/snd/url-pattern/blob/master/lib/url-pattern.js)

Here is my related bug on babel minify: https://github.com/babel/minify/issues/905

**Comment by evilebottnawi** [comment]
@jsg2021 you can try https://github.com/webpack-contrib/terser-webpack-plugin

**Comment by jsg2021** [comment]
@evilebottnawi yes, I'm only using babel-minify to make Uglify not crash :P (babel's minify runs on the loader with)

I tried using terser and it crashed with a maximum stack error...
