### ISSUE TITLE
Handle conditional require

### ISSUE THREAD

**Issue by IngwiePhoenix** [webpack/webpack#1045]
I just wanted to write a loader for jsph ... but then this one put it on a halt:

https://github.com/brentoboy/jsph/blob/master/src/jsph.js#L2-L6

How is that handled best? The intentions are clear: Only require, we are in NodeJS. However, we aren't really in NodeJS, but WebPack. So the require will pass through.

What is the better way to handle this?

I modified this line and prepended `typeof window == "undefined`, which pretty well proves a non-browser environment. However, this still didn't let me get rid of the error message.

```
Ingwie@Ingwies-Macbook-Pro.local ~/W/j/test $ webpack
Hash: 2bdae12f5ee09d3d6601
Version: webpack 1.8.9
Time: 71ms
    Asset     Size  Chunks             Chunk Names
bundle.js  6.31 kB       0  [emitted]  main
   [0] ./app.js 172 bytes {0} [built]
   [1] ./menu.jsph 949 bytes {0} [not cacheable] [built]
    + 1 hidden modules

ERROR in ../~/jsph/src/jsph.js
Module not found: Error: Cannot resolve module 'fs' in /Users/Ingwie/Work/jsph-loader/node_modules/jsph/src
 @ ../~/jsph/src/jsph.js 5:11-24
```

**Comment by sokra** [comment]
This need to be fixed on jsphs side. i. e. by adding an `browser` field to the package.json.

**Comment by IngwiePhoenix** [comment]
And in general speaking, how would I go about doing this? That a require() is only resolved when I really want it to be resolved.

I'll let the package maintainer know about it. :)
