### ISSUE TITLE
Output inject order issue

### ISSUE THREAD

**Issue by sergiombravo** [webpack/webpack#10458]
Hi, 

I have some structure like this

```
const FOO = 'bar';

require([some-file], function(baz) => {

}
```

in some-file I use FOO as I load before in terms of order. When I output the file on webpack it injects some-file code at the top, and as I have not loaded const FOO yet it throws an error.

How can I set to inject the used files at the end instead of the top? or how to solve this issue? Thanks!

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
