### ISSUE TITLE
Support new `export * as ns` syntax

### ISSUE THREAD

**Issue by OliverJAsh** [webpack/webpack#10460]
## Feature request

There is new export syntax: `export * as ns` (stage 4).

https://github.com/tc39/proposal-export-ns-from

```ts
export * as ns from './test';
```

Currently this will error:

```
ERROR in ./src/proxy.js 1:9
Module parse failed: Unexpected token (1:9)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> export * as ns from './test';
 @ ./src/index.js 1:0-29 2:12-14
```

FWIW, TypeScript recently added support for this: https://devblogs.microsoft.com/typescript/announcing-typescript-3-8/#export-star-as-namespace-syntax

**What is the expected behavior?**

**What is motivation or use case for adding/changing the behavior?**

**How should this be implemented in your opinion?**

**Are you willing to work on this yourself?**
yes

**Comment by sokra** [comment]
Does acorn already support it?

**Comment by OliverJAsh** [comment]
Sounds like it's implemented inside a plugin: https://github.com/acornjs/acorn/issues/742#issuecomment-432441171

https://github.com/acornjs/acorn-export-ns-from

**Comment by sokra** [comment]
acorn PR: https://github.com/acornjs/acorn/pull/889

**Comment by guillaume86** [comment]
I have this issue with typescript/ts-loader, is it a webpack issue or a ts-loader issue?

**Comment by evilebottnawi** [comment]
@guillaume86 ts-loader

**Comment by ooyyloo** [comment]
> @guillaume86 ts-loader

It's not a ts-loader issue. It happens because webpack 4 haven't used the newest acornjs version.

**Comment by guillaume86** [comment]
@ooyyloo thanks I'll just for a webpack update then

**Comment by appzuka** [comment]
Is this the same issue as https://github.com/TypeStrong/ts-loader/issues/1121?

If you use a module target lower than es2020 then typescript will transpile the new export * syntax down to a version webpack can understand.

**Comment by jun-sheaf** [comment]
A current workaround is to use Babel and its [@babel/plugin-proposal-export-namespace-from](https://babeljs.io/docs/en/babel-plugin-proposal-export-namespace-from) plugin. You can set is up like so for bare-minimal babel:

For dependencies,
```
npm i -D @babel/core babel-loader @babel/plugin-proposal-export-namespace-from
```

In your `webpack.config.js`,
```javascript
...
{
    test: /\.tsx?$/,
    use: [{
         loader: "babel-loader", // This should be the last loader of course
         options: {
              plugins: ["@babel/plugin-proposal-export-namespace-from"]
         }
    }, ...other loaders]
}
...
```

**Comment by OnurGvnc** [comment]
as a temporary solution;
https://github.com/OnurGvnc/acorn-with-stage3

`package.json`:

```json
{
  ...
  "resolutions": {
    "acorn": "npm:acorn-with-stage3"
  },
  "dependencies": {

```

**Comment by jun-sheaf** [comment]
> as a temporary solution;
> https://github.com/OnurGvnc/acorn-with-stage3
> 
> `package.json`:
> 
> ```json
> {
>   ...
>   "resolutions": {
>     "acorn": "npm:acorn-with-stage3"
>   },
>   "dependencies": {
> ```

A lot of packages rely on acorn. This can potentially break them. It is advisable to build on top rather than directly patch.

**Comment by noinkling** [comment]
> A lot of packages rely on acorn. This can potentially break them.

Scoping it to Webpack only would help:

```json
"resolutions": {
  "webpack/acorn": "npm:acorn-with-stage3"
},
```

**Comment by jun-sheaf** [comment]
> Scoping it to Webpack only would help

This only works on yarn.

**Comment by OnurGvnc** [comment]
> > Scoping it to Webpack only would help
> 
> This only works on yarn.

https://www.npmjs.com/package/npm-force-resolutions

**Comment by jun-sheaf** [comment]
> https://www.npmjs.com/package/npm-force-resolutions

`nom-force-resolutions` doesn't support that behavior.

**Comment by TheColorRed** [comment]
@appzuka I had to also change `module` to a version less than `es2020`

```json
{
  "compilerOptions": {
    "target": "es2015",
    "module": "es2015"
  }
}
```
