### ISSUE TITLE
Problem with 'text' require.js plugin

### ISSUE THREAD

**Issue by OpakAlex** [webpack/webpack#1046]
Hello!

I have a big problem when try migrate from require.js to webpack.
my config:

```
var path = require("path");
var webpack = require("webpack");
var appModulesPath = path.join(path.resolve('public/app/js'));
var libsPath = path.join(path.resolve('public/app/lib'));
module.exports = {
  cache: true,
  context: appModulesPath,
  entry: {
      entryMain: './main',
      // entryLogin: 'main-login'
  },
  output: {
    path: path.join(__dirname, "dist"),
    publicPath: "dist",
    filename: "[name].js",
    chunkFilename: "[chunkhash].js"
  },
  module: {
    loaders: [
      { test: /require\.js$/, loader: "exports?requirejs!script" },
      { test: /text!\.html$/, loader: "html" }
    ]
  },
  externals: {
    // require("jquery") is external and available
    //  on the global var jQuery
  },
  resolve: {
    root: [appModulesPath, libsPath],
    alias: {
        "text": 'text.js',
        "angular": 'angular/angular.js',
        "angularRoute": 'angular-route/angular-route.js',
        "angularCookies": 'angular-cookies/angular-cookies.js',
        "angularMocks": 'angular-mocks/angular-mocks.js',
        "jquery": 'jquery.js',
        "wysihtml5": 'wysihtml5.js',
        "gritter": 'jquery.gritter.js',
        "icheck": 'jquery.icheck.js',
        "placeholder": 'jquery.placeholder.js',
        "qtip": 'jquery.qtip.js',
        "tooltipster": 'jquery.tooltipster.min.js',
        "almond": 'almond/almond.js',
        "cryptojs": 'cryptojs/hmac-sha1.js',
        "datepicker": 'bootstrap-datepicker.js',
        "slider": 'jquery-ui-slider.js',
        "select2": 'select2.js',
        "toastr": 'toastr.js',
        "requirejs": 'requirejs/require.js'
    }
  },
  plugins: [
    new webpack.ProvidePlugin({
      // Automtically detect jQuery and $ as free var in modules
      // and inject the jquery library
      // This is required by many jquery plugins
      jQuery: "jquery",
      $: "jquery"
    })
  ]
};
```

Then, i use for require `html` => `require.js text` plugin.

when i run `webpack`:
```
ERROR in ./servers/partition-modal.js
Module not found: Error: Cannot resolve module 'text' in /private/var/www/webzilla/ssp/public/app/js/servers
 @ ./servers/partition-modal.js 3:0-173:2
```

example file:
```
'use strict';

define([
    'app',
    'text!servers/tpl/cart.html'
], function(
    app,
    tpl
) {
    app.controller('CartCtrl', [
        '$scope',
        '$location',
    function(
        $scope,
        $location
    ){
    }]);
});
```

What i do wrong?

**Comment by SimenB** [comment]
```js
define([
    'app',
    'html!servers/tpl/cart.html'
], function(
```

**Comment by OpakAlex** [comment]
@SimenB thanks, but if i want keep `text!`. how i can do it?

**Comment by SimenB** [comment]
Untested, but you can try

```js
resolve: {
    alias: {
        "text": 'html'
    }
  },
```

**Comment by OpakAlex** [comment]
no.....
Module not found: Error: Cannot resolve module 'text' in

**Comment by OpakAlex** [comment]
why it not load it? into module....this part i don't understand.

**Comment by OpakAlex** [comment]
@SimenB some ideas?

**Comment by OpakAlex** [comment]
@SimenB hi man, any news?)

**Comment by SimenB** [comment]
why do you insist on keeping `text` plugin? It's a requirejs plugin, it's not supposed to work for webpack

**Comment by sokra** [comment]
`resolveLoader.alias`

**Comment by sokra** [comment]
[contributing guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md)

> Please post a question to [StackOverflow with the webpack tag](http://stackoverflow.com/tags/webpack). Questions that include your webpack.config.js and relevant files are more likely to receive responses.

**Comment by michaelahlers** [comment]
@SimenB, one possible reason for preserving the `text` and other Require.js plugins (and syntax): ease legacy transitions to webpack. I'm currently migrating a large project, and I'm trying to be minimally invasive wherever possible.

**Comment by ecarding** [comment]
Hope you have solved it already. I had the same problem and my solution was to run this command:
npm install text-loader requirejs-text 
then put the alias text : 'npm_modules/requirejs-text/text' in the webpack-config 
in the require config put the same text : 'npm_modules.....' in the paths(I think)

**Comment by yeesunday** [comment]
What if the requirejs plugin is written by myself? Should  I write a webpack loader again?

**Comment by johnstew** [comment]
I know its been awhile on this thread but came across this problem when I was trying to integrate Webpack 2 as our new bundler. Anyways here is my solution following @sokra advice.

**webpack.config.js**
```
resolveLoader: {
  alias: {
      text: 'text-loader'
  }
}
```

Also going to need [text-loader](https://www.npmjs.com/package/text-loader).
