### ISSUE TITLE
ERROR: TS1149 in NodeTargetPlugins(11,10)

### ISSUE THREAD

**Issue by RouNNdeL** [webpack/webpack#10477]
# Bug report

I'm just staring to out with Webpack, trying to make a very simple React app written in TypeScript. And I cannot get the simplest examples to work properly.

**What is the current behavior?**
When using the `ts-loader` plugin to compile TypeScript an error is thrown: 
```
ERROR in <DEV_PATH>/node_modules/webpack/lib/node/NodeTargetPlugin.js
[tsl] ERROR in <DEV_PATH>/node_modules/webpack/lib/node/NodeTargetPlugin.js(11,10)
      TS1149: File name '<DEV_PATH>/node_modules/webpack/lib/module.js' differs 
from already included file name '<DEV_PATH>/node_modules/webpack/lib/Module.js' only in casing.
```

**If the current behavior is a bug, please provide the steps to reproduce.**
I'm using the following `webpack.config.js`:
```javascript
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const {CleanWebpackPlugin} = require('clean-webpack-plugin');

module.exports = {
  mode: 'development',
  entry: {
    app: './src/index.tsx',
  },
  devServer: {
    contentBase: './dist',
  },
  devtool: "source-map",
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        use: 'ts-loader',
        exclude: /node_modules/,
      },
      {
        test: /\.s[ac]ss$/i,
        use: [
          'style-loader',
          'css-loader',
          'sass-loader',
        ],
      },
    ],
  },
  resolve: {
    extensions: [ '.tsx', '.ts', '.js' ],
  },
  plugins: [
    new CleanWebpackPlugin(),
    new HtmlWebpackPlugin({
      title: 'Development',
    }),
  ],
  output: {
    filename: '[name].bundle.js',
    path: path.resolve(__dirname, 'dist'),
  },
};
```

I've tried to set `forceConsistentCasingInFileNames` to `false` in the `tsconfig.json` file, but that does not resolve the issue.

**What is the expected behavior?**
The files should be compiled. I opened the issue here, since the error references the file in the `webpack/lib` folder.

**Other relevant information:**
webpack version:  4.41.6
Node.js version: v12.13.1
Operating System: Windows 10
Additional tools: JetBrains PHPStorm IDE

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by RouNNdeL** [comment]
@sokra Here you go https://github.com/RouNNdeL/webpack-issue-10477. I've cloned the repo into a new directory and the issue still persists.

**Comment by RouNNdeL** [comment]
I've managed to get the `ts-loader` to load the `tsconfig.json` which allows me to suppress the error, but I think this should be looked at regardless.

**Comment by sokra** [comment]
@johnnyreilly

**Comment by johnnyreilly** [comment]
It could be worth comparing your repo with say this one: https://github.com/TypeStrong/ts-loader/tree/master/examples/vanilla

Worth comparing `tsconfig.json` / `webpack.config.js` / `package.json` in particular

**Comment by MrIrick** [comment]
same problem, any patch way?

**Comment by MrIrick** [comment]
ok , i know why , and solved;
i set my tsonfig.json.module = es6
change it to other, the error gone.

and if webpack thinking about fix it, even if its a invalid module in tsconfig.

**Comment by RouNNdeL** [comment]
Nope, the issue can be closed
