### ISSUE TITLE
Missing required LICENSE file in mamacro@0.0.3 dep

### ISSUE THREAD

**Issue by opichals** [webpack/webpack#10479]
The current tree contains the mamacro@v0.0.3 which doesn't contain the license file. The issue has been fixed upstream in the  @webassembly/*v1.9.0 versions.

Therefore it is sufficient to backport the https://github.com/webpack/webpack/commit/d226474c9fa5c787aa32dfe9cd954e303da199b4 to webpack-4 branch.

**Comment by sokra** [comment]
Do it: https://github.com/webpack/webpack/issues/10489

**Comment by jeffin143** [comment]
Done :), Let's close this

**Comment by opichals** [comment]
It would be nice to get that released (From what I see https://github.com/webpack/webpack/commits/webpack-4 this isn't the case yet).

**Comment by evilebottnawi** [comment]
It was release in near future
