### ISSUE TITLE
Webpack watch + livereload

### ISSUE THREAD

**Issue by eriknyk** [webpack/webpack#1047]
Hi, I have a question,
I'm using webpack with grunt,
there is some way to configure webpack with watch enabled,
and that watch mode, enabling livereload?, since I'm thinking, that watch mode is related to
grunt-watch.

Regards.

**Comment by sokra** [comment]
[contributing guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md)

> Please post a question to [StackOverflow with the webpack tag](http://stackoverflow.com/tags/webpack). Questions that include your webpack.config.js and relevant files are more likely to receive responses.
