### ISSUE TITLE
CommonsChunkPlugin for vendor chunk in conjunction with other chunks loaded via jsonp

### ISSUE THREAD

**Issue by gcorne** [webpack/webpack#1048]
There seems to be a couple issues when using `CommonsChunkPlugin` to create a vendor chunk and via jsonp/require.ensure additional chunks are created.

``` js
var webpackConfig = {
  output: {
    chunkFilename: '[name].[chunkhash].js'
  },
  plugins: [
    new webpack.optimize.CommonsChunkPlugin( 'vendor', '[name].[chunkhash].js' )
  ]
```
1. If the above configuration is used, the hash for `vendor.[chunkhash].js` won't vary when the hashes of the other chunks change. This is needed because the hashes are part of the bootstrap and the vendor chunk includes the bootstrap.
2. The workaround is to use `[name].[hash].js` as a template but then the hash varies on every build which leads to the file changing more frequently than is desired.

**Comment by sokra** [comment]
Use the workaround. The expected result would be a error that `[chunkhash]` is not allowed for an entry point when `chunkFilename` contains `[chunkhash]`.

**Comment by sokra** [comment]
Also see https://github.com/diurnalist/chunk-manifest-webpack-plugin

**Comment by vamsiampolu** [comment]
@sokra ,

I get the issue when generating the `manifest` both with and without using the `chunkFilename`, this is my config: https://gist.github.com/vamsiampolu/de0daaaffb4c662220a4dd32907d42e6

The `[hash]` would change on every build, would it not?

**Comment by bebraw** [comment]
Can you see this with webpack 2?
