### ISSUE TITLE
Two different universal definitions for same request

### ISSUE THREAD

**Issue by RyanBanner** [webpack/webpack#10494]
# Bug report

**What is the current behavior?**
When I include the script from a separate domain one of two things happen. Either `b` is logged which results in `TFRSDK` not being defined. Or `d` is logged meaning that everything works. If I set the condition checked which returns the `b` log to `false` then `d` is logged and everything works.

![image](https://user-images.githubusercontent.com/61511457/75698920-76c2e780-5ca7-11ea-8686-1f4a6c77dba6.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
My setup for this is strange. I have two sites, one a staging server and one local. They're both loading the js file in question from a separate domain which is public via ngrok routing to a local docker container. The staging server causes issues whereas the local site works.

Then export a default class and things should break.

**What is the expected behavior?**
Both the staging server and local server can access the variable holding the class.

**Other relevant information:**
webpack version:  4.41.6
Node.js version: 10.16.0
Operating System: Local - Ubuntu 16.04 Staging - Unknown Docker - php:7.3.11-apache
Additional tools:

**Comment by sokra** [comment]
If `b` is logged you seem to have a AMD loader on the page which handles this module.

If you always want to define a global you should consider a different `output.libraryTarget`.
