### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by marcoippolito** [webpack/webpack#10496]
# Bug report

**What is the current behavior?**

My testing-app is compiling fine, except that I get this warning:
" Critical dependency: the request of a dependency is an expression"

    (base) marco@pc01:~/webMatters/vueMatters/PeerJS-VueJS-Test$ npm run serve

    > testproject@0.1.0 serve /home/marco/webMatters/vueMatters/PeerJS-VueJS-Test
    > vue-cli-service serve

     INFO  Starting development server...
    98% after emitting CopyPlugin

    WARNING  Compiled with 1 warnings                                                                                                             
    7:22:25 PM

    warning  in ./node_modules/peerjs/dist/peerjs.min.js

    Critical dependency: the request of a dependency is an expression

      App running at:
      - Local:   http://localhost:8080 
      - Network: http://ggc.world/

      Note that the development build is not optimized.
      To create a production build, run npm run build.

I read around that it might depend of webpack, but didn't find how to put it right.

This is webpack.config.js  :  

    {
        "mode": "development",
        "output": {
            "path": __dirname+'/static',
            "filename": "[name].[chunkhash:8].js"
        },
        "module": {
            "rules": [
                {
                    "test": /\.vue$/,
                    "exclude": /node_modules/,
                    "use": "vue-loader"
                },
                {
                    "test": /\.pem$/,
                    "use": "file-loader"
                }
            ]
        },
        node: {
            __dirname: false,
            __filename: false
        },
        resolve: {
            extension: ['*', '.pem'],
        },
        devServer: {
            watchOptions: {
                aggregateTimeout: 300,
                poll: 1000
            },
            https: true,
            compress: true,
            public: 'ggc.world:8080'
        }
    }

Any ideas about how to solve it?

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
    webpack version:  npm view webpack version 4.42.0
    Node.js version: v12.15.0
    Operating System: Ubuntu 18.04.4 Desktop
    Additional tools:

    (base) marco@pc01:~/webMatters/vueMatters/PeerJS-VueJS-Test$ vue info

    Environment Info:

      System:
        OS: Linux 5.3 Ubuntu 18.04.4 LTS (Bionic Beaver)
        CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
      Binaries:
       Node: 12.15.0 - ~/.nvm/versions/node/v12.15.0/bin/node
       Yarn: Not Found
        npm: 6.13.4 - ~/.nvm/versions/node/v12.15.0/bin/npm
      Browsers:
        Chrome: 80.0.3987.122
        Firefox: 73.0.1
      npmPackages:
        @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
        @vue/babel-plugin-transform-vue-jsx:  1.1.2 
        @vue/babel-preset-app:  4.2.3 
        @vue/babel-preset-jsx:  1.1.2 
        @vue/babel-sugar-functional-vue:  1.1.2 
        @vue/babel-sugar-inject-h:  1.1.2 
        @vue/babel-sugar-v-model:  1.1.2 
        @vue/babel-sugar-v-on:  1.1.2 
        @vue/cli-overlay:  4.2.3 
        @vue/cli-plugin-babel: ^4.1.2 => 4.2.3 
        @vue/cli-plugin-eslint: ^4.1.2 => 4.2.3 
        @vue/cli-plugin-router:  4.2.3 
        @vue/cli-plugin-vuex:  4.2.3 
        @vue/cli-service: ^4.1.0 => 4.2.3 
        @vue/cli-shared-utils:  4.2.3 
        @vue/component-compiler-utils:  3.1.1 
        @vue/preload-webpack-plugin:  1.1.1 
        @vue/web-component-wrapper:  1.2.0 
        eslint-plugin-vue: ^5.0.0 => 5.2.3 
        vue: ^2.6.10 => 2.6.11 
        vue-eslint-parser:  5.0.0 
        vue-hot-reload-api:  2.3.4 
        vue-loader:  15.9.0 
        vue-style-loader:  4.1.2 
        vue-template-compiler: ^2.6.10 => 2.6.11 
        vue-template-es2015-compiler:  1.9.1 
      npmGlobalPackages:
            @vue/cli: 4.1.2

**Comment by pagnkelly** [comment]
same question

**Comment by evilebottnawi** [comment]
Please create reproducible test repo

**Comment by pagnkelly** [comment]
function requireLocalPkg(pkgName: string): any {
    try {
        const a = require(pkgName)
        return a 
    } catch (e) {
        console.log(e)
    }
  }
  export { requireLocalPkg };

It's like using this method at run time

**Comment by GonyMaster** [comment]
me too

**Comment by evilebottnawi** [comment]
It is warning and it is expected because it is `Critical dependency: the request of a dependency is an expression`, fix your code, you don't provide code so we can't help, sorry

**Comment by ShortRoundDev** [comment]
Here is an example of valid javascript that webpack is giving a critical warning on:

```js
    async test(): Promise<void> {
        const script = 'export function Foo(){ return "hello"; }';
        const blob = new Blob([script], { type: 'text/javascript' });
        const module = URL.createObjectURL(blob);

        const m = await import(module);
        console.log(m.Foo());
    }
```

results in:

```
WARNING in [my file name here].ts 114:80-90
Critical dependency: the request of a dependency is an expression
```

If you are doing what I'm doing (i.e: trying to use the browser's native dynamic import and not webpack's), then you need to use import like this:

```js
await import(/* webpackIgnore: true */ module)
```

if you are using typescript, you need to add

```json
"module": "ESNext"
```

to your tsconfig.json file:

https://github.com/webpack/webpack/issues/7644
