### ISSUE TITLE
Define deps & loaders in package.json

### ISSUE THREAD

**Issue by JonDum** [webpack/webpack#1050]
As a package developer it'd be freaking awesome to define deps in the package.json, so that a `require("foo")` loads it's `main` as well as any additional stuff it may need.

```
{
  name: "foo",
  main: "src/foo.js", // for non-webpackers
  webpack: ["src/foo.js", "src/css/styles.css", "src/html/template.html"],
}
```

But a lot of the time the deps require a loader...

{
  name: "foo",
  main: "src/foo.js",
  webpack: ["6to5!src/foo.js", "styl!css!src/css/styles.styl", "handlebars!src/html/template.hbs"],
}

Is there any way of making that work?

**Comment by sokra** [comment]
There is a plan for that, but I don't have enough time currently...

**Comment by mtscout6** [comment]
Is there a link to this plan you have?

**Comment by JonDum** [comment]
> Is there a link to this plan you have?

@mtscout6 it's in his head :)

@sokra I'm going to take a stab at this your response as a go ahead for a PR. Absolutely zero promises that I can make it work though!

**Comment by IngwiePhoenix** [comment]
Ohmy! That does look very promising. :)

But, a question. Will the developer be notified in any way when a loader is missing? For instance, I use the Babel loader, so I dont have 6to5-loader on my project.

**Comment by sokra** [comment]
Actually it's here: https://github.com/webpack/concord (WIP)

**Comment by princed** [comment]
@sokra Does it mean concord is no longer planned?

**Comment by princed** [comment]
Still invaluable thing for components library maintainers.

**Comment by evilebottnawi** [comment]
Let's move this on `webpack@5` with low priority

**Comment by princed** [comment]
😐

**Comment by evilebottnawi** [comment]
Not sure we really want to have it, I think in 2020 JS configurations are preferable
