### ISSUE TITLE
typescript export type error

### ISSUE THREAD

**Issue by tjx666** [webpack/webpack#10519]
# Bug report

**What is the current behavior?**

syntax eroor

![screenshot_2020-03-07_19-29-17](https://user-images.githubusercontent.com/41773861/76142685-e885a180-60aa-11ea-89a2-1d6c73d750d9.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

add following code:

```typescript
type TestType = 666;
export type { TestType };
```

repository: [coo](https://github.com/tjx666/coo)

**What is the expected behavior?**

no error

**Other relevant information:**
webpack version:  4.42.0
Node.js version: v12.16.1
Operating System:  win10pro1909
Additional tools:

**Comment by sokra** [comment]
This is not webpack-related by typescript-related.

Maybe even looks like a babel error, but you didn't paste the full error message.
