### ISSUE TITLE
enforceExtension in resolve doesn't work!!!

### ISSUE THREAD

**Issue by Mistyyyy** [webpack/webpack#10511]
# Bug report

**What is the current behavior?**

webpack.config.js
```
const path = require('path');
const { CleanWebpackPlugin } = require('clean-webpack-plugin');

module.exports = {
  mode: 'development',

  entry: './src/index.js',

  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'a.bundle.js',
  },

  resolve: {
    enforceExtension: true,
  },

  plugins: [
    new CleanWebpackPlugin()
  ]
}
```
Directory tree
```
├── src
│   ├── a.js
│   └── index.js
└── webpack.config.js
```

index.js

```
import { a } from './a';

console.log(a)
```

a.js

```
export const a = 1
```

errors
`Module not found: Error: Can't resolve './src/index.js' in '/Users/teishunrai/main/demo/webpack-enforceExtension-repo`

**If the current behavior is a bug, please provide the steps to reproduce.**

this is [test repo](https://github.com/Mistyyyy/webpack-enforceExtension-repo)

**What is the expected behavior?**

`import { a } from './a'` doesn't work

**Other relevant information:**
webpack version:  4.42.0 / 5.0.0-beta.13 all failed
Node.js version: v12.0.0
Operating System: macOS 10.14.6
Additional tools: webpack-cli: 3.3.11/4.0.0-beta.8

**Comment by sokra** [comment]
You probably want:

``` js
  resolve: {
    extensions: [],
  },
```

**Comment by Mistyyyy** [comment]
Thanks for responding to my question

what I want to convey is if I config the resolve as below

```javascript
resolve: {
    extensions: [],
 },
```
The result is right 

![image](https://user-images.githubusercontent.com/37856353/76082448-66cc4000-5fe6-11ea-8c9a-216d748c7b51.png)

but if I set `enforceExtensions: true` and follow the webpack document description

> If true, it will not allow extension-less files. So by default require('./foo') works if ./foo has a .js extension, but with this enabled only require('./foo.js') will work.

The result should be the same as `extensions: []`, but I got

![image](https://user-images.githubusercontent.com/37856353/76082991-8879f700-5fe7-11ea-9103-172d4fbfea57.png)

Webpack can't find entry Module rather Can't resolve './a'. the result is not right.
It should be an **enhanced-resolve** issue

**Comment by sokra** [comment]
The webpack documentation is incorrect here.

enhanced-resolve has the correct documentation here:

https://github.com/webpack/enhanced-resolve/#resolver-options

> Enforce that a extension from extensions must be used

Now that I read it, it is also pretty hard to understand correctly.

`enforceExtensions: false`: During resolving any extension from `extensions` **can optionally** be added to the request.

`enforceExtensions: true`: During resolving any extension from `extensions` **must** be added to the request.

**Comment by Mistyyyy** [comment]
@sokra Thanks for your explanation. 

However, if I set the `enforceExtensions: true`. The project build failed, even extension all added to the request. It can't find the entry file, If I comment out the `enforceExtensions: true`, the project build to succeed.

`Error: Can't resolve '/Users/s/main/demo/webpack-external-demo/src/index.js' in '/Users/s/main/demo/webpack-external-demo'`

I debug it locally, I found It is an `enhanced-resolve ` bug.

**Comment by sokra** [comment]
> Error: Can't resolve '/Users/s/main/demo/webpack-external-demo/src/index.js' in '/Users/s/main/demo/webpack-external-demo'

That's working as expected. `index.js` already has an extension, so if you enforce adding one extension from `extensions` with the flag it fails to resolve.

**Comment by evilebottnawi** [comment]
Answer above, feel free to leave feedback

**Comment by KaseiHaku** [comment]
oh my god, explanation of official documents waste eight hours of me, Why isn't there a case to explain this
