### ISSUE TITLE
NPM repo is not sync with the Github repo

### ISSUE THREAD

**Issue by TechieForFun** [webpack/webpack#10517]
At the time I'm writing this issue, in the [`package.json` at line 12](https://github.com/webpack/webpack/blob/777bc8aff1ce39e6355e45f491296fc7c6acee94/package.json#L12) we have `acorn` version `^7.0.0`, but in the [npm package](https://registry.npmjs.org/webpack/-/webpack-4.42.0.tgz) we have `acorn` with version of `^6.2.1` which makes a [security warning](https://www.npmjs.com/advisories/1488).

**Comment by dacevedoatfluid** [comment]
Hi @TechieForFun, I just had this problem aswell. I figured that it's only updated in master which is webpack 5 beta. webpack 4 is using the outdated and vulnerable 6.2.1

I opened an issue about it https://github.com/webpack/webpack/issues/10516

**Comment by TechieForFun** [comment]
Hi @dacevedoatfluid, you're right, thanks for pointing. I'm gonna make a PR for it.
