### ISSUE TITLE
externals function is called repeatedly for the same request, instead of being cached.

### ISSUE THREAD

**Issue by trusktr** [webpack/webpack#10521]
# Bug report

**What is the current behavior?**

For a given request, like "foo", an externals function is called every time the "foo" import is encountered.

Shouldn't it be cached, to save on performance cost?

**If the current behavior is a bug, please provide the steps to reproduce.**

Add an externals function, like

```js
externals: [function (ctx, request, callback) {
  if (request === 'foo') console.log('foo')
  callback()
}]
```

and notice that it is called multiple times for the same request (change the code to match an actual request that you have, where it is imported many times throughout your project).

I don't see any reason why the same request would need to be handled differently every time.

**What is the expected behavior?**

The function should only be called once, the first time a given request is encountered.

**Other relevant information:**
webpack version:  4.27.1

**Comment by trusktr** [comment]
As a workaround, I do the following. The following is not representative of my more complicated actual code):

```js
externals: [(function() {
  const cache = new Set

  return function skipFoo(ctx, request, callback) {
    if (cache.has(request)) { callback(); return }
    if (request === 'foo') {
      console.log('foo')
    }
    callback()
  }
}())]
```

**Comment by sokra** [comment]
> I don't see any reason why the same request would need to be handled differently every time.

There is also `ctx` which could also be different.

Anyway there could be reason why it should be handled differently. e. g. you only want to make `foo` in one package external.

That's how the resolving works. It context-dependent. non-external `import "foo"` can also resolve to different modules in your application depending on where it's placed and what's the nearest node_modules contains.
