### ISSUE TITLE
Bug: webpack-dev-server   --config=config/webpack.dev.js

### ISSUE THREAD

**Issue by ComahonQQComahon** [webpack/webpack#10528]
# Bug report

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
If I use command
 webpack-dev-server --config=config/webpack.dev.js
Webpack working good.
But If I changing file package.json 
from this:
`{
  "name": "webpack-course",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test cpecified\" && exit 1"
    },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "css-loader": "^3.4.2",
    "style-loader": "^1.1.3",
    "webpack": "^4.42.0",
    "webpack-cli": "^3.3.11",
    "webpack-dev-server": "^3.10.3"
  }
}
`
to this:
`{
  "name": "webpack-course",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "webpack-dev-server
     --config=config/webpack.dev.js",
     "build": "webpack --config=config/webpack.dev.js"
    },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "css-loader": "^3.4.2",
    "style-loader": "^1.1.3",
    "webpack": "^4.42.0",
    "webpack-cli": "^3.3.11",
    "webpack-dev-server": "^3.10.3"
  }
}
`
and run 

npm run start

It gives an error

> npm ERR! code EJSONPARSE
npm ERR! file C:\Users\Sergey\webpack-course\package.json
npm ERR! JSON.parse Failed to parse json
npm ERR! JSON.parse Unexpected token
npm ERR! JSON.parse  in JSON at position 142 while parsing '{
npm ERR! JSON.parse   "name": "webpack-course",
npm ERR! JSON.parse   "version'
npm ERR! JSON.parse Failed to parse package.json data.
npm ERR! JSON.parse package.json must be actual JSON, not just JavaScript.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Sergey\AppData\Roaming\npm-cache\_logs\2020-03-10T08_30_27_520Z-debug.log

**Other relevant information:**
webpack version:  4.42.0
Node.js version: 12.14.1
Operating System:  win 7 sp1 x86
Additional tools: git Bash

**Comment by evilebottnawi** [comment]
You have invalid format for `package.json`. Please read the error message:
```
npm ERR! JSON.parse Failed to parse package.json data.
npm ERR! JSON.parse package.json must be actual JSON, not just JavaScript.
```
