### ISSUE TITLE
docs(readme): broken link Architects.io

### ISSUE THREAD

**Issue by snitin315** [webpack/webpack#10523]
# Bug report
the link [https://architects.io](https://architects.io) in readme is broken.

![Screenshot from 2020-03-09 15-11-35](https://user-images.githubusercontent.com/46647141/76200849-4a174e80-6218-11ea-830f-66f33360a7fd.png)

![Screenshot from 2020-03-09 15-11-57](https://user-images.githubusercontent.com/46647141/76200876-54d1e380-6218-11ea-9e7c-64b5a1ea5415.png)

**What is the current behavior?**
Either it should be removed or updated with the correct one.

**If the current behavior is a bug, please provide the steps to reproduce.**
Go TO [https://architects.io](https://architects.io)

**What is the expected behavior?**
Should not be broken.

Additional Info--

I will work on thisi issue.

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

**Comment by snitin315** [comment]
@sokra what should be done?

**Comment by himanshu010** [comment]
I think that this is a duplicate of #10513

**Comment by evilebottnawi** [comment]
Remove it

**Comment by evilebottnawi** [comment]
send a PR
