### ISSUE TITLE
Code splitting using importScripts in web workers

### ISSUE THREAD

**Issue by SebastiaanYN** [webpack/webpack#10520]
## Feature request

**What is the expected behavior?**

I've been looking for a way to synchronously import files in a web worker, but files imported with `importScripts` don't get bundled. 

Dynamic imports properly handle code splitting, but wrap `importScripts` calls in a promise, which means it can't be used outside async functions.

```js
__webpack_require__.e = function requireEnsure(chunkId) {
	var promises = [];
	promises.push(Promise.resolve().then(function() {
		// "1" is the signal for "already loaded"
		if(!installedChunks[chunkId]) {
			importScripts(__webpack_require__.p + "" + ({}[chunkId]||chunkId) + "." + {"0":"6394943a04beaad66432"}[chunkId] + ".js");
		}
	}));
	return Promise.all(promises);
};
```

Given this, the following code should output `worker.js` and `external.js` as separate files. `worker.js` would then load `external.js` dynamically once it's executed.

```js
// worker.js
importScripts('./external.js');
```

```js
// external.js
console.log('Hello');
```

**What is motivation or use case for adding/changing the behavior?**

It allows `importScripts` to be used to synchronously import files with code splitting support.

**How should this be implemented in your opinion?**

There could be another function on `__webpack_require__` that is implemented as following:

```js
function(chunkId) {
	importScripts(__webpack_require__.p + "" + ({}[chunkId]||chunkId) + "." + {"0":"6394943a04beaad66432"}[chunkId] + ".js");
};
```

Then calls to `importScripts` would be transpiled similar to dynamic imports, but referencing this function instead of `__webpack_require__.e`.

**Are you willing to work on this yourself?**

I have no knowledge of the internals of webpack, but I'd be willing to work on it if I got directions.

**Comment by sokra** [comment]
It's a hack, but this should work:

``` js
import('./external.js'); // ignore the promise
require.weak('./external.js');
```

**Comment by SebastiaanYN** [comment]
When I try that I get the following warning from the compiler:
```
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
```

And the following error at runtime:
```
TypeError: __webpack_require__(...).weak is not a function
```

The compiler output is:
```js
  __webpack_require__.e(/*! import() */ 0).then(__webpack_require__.t.bind(null, /*! ./external.js */ "./src/external.js", 7));
  __webpack_require__("./src sync recursive").weak('./external.js');
```

**Comment by sokra** [comment]
hmm yes my mistake, `require.weak` doesn't exist. Try this:

``` js
import('./external.js'); // ignore the promise
__webpack_require__(require.resolveWeak('./external.js'));
```

**Comment by SebastiaanYN** [comment]
This doesn't work either. Because `import` is async it's queued until after the `__webpack_require__` call. Because the webpack require doesn't import the file it errors:
```
TypeError: Cannot read property 'call' of undefined
```
on
```js
// Execute the module function
modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
```

This does work when the `import` call is executed first, but because it's not awaited there's no guarantee.

For reference, this is the compiled code:
```js
__webpack_require__.e(/*! import() */ 0).then(__webpack_require__.bind(null, /*! ./external.js */ "./src/external.js"));
__webpack_require__(/*require.resolve*/(/*! ./external.js */ "./src/external.js"));
```

**Comment by sokra** [comment]
Hmm ok. If this doesn't work I don't have a solution. You need to write a custom plugin.

I think the hack would work in webpack 5, because it doesn't delay the importScripts call by a microtick, only the module execution. I check if I can add sync version of `import()`, at least for node.js and webworker targets.

**Comment by evilebottnawi** [comment]
Will be great to add tests for webpack@5
