### ISSUE TITLE
Code splitting with compressed bundle files

### ISSUE THREAD

**Issue by mustik22** [webpack/webpack#10535]
# Bug report

**What is the current behavior?**
I have been successfully using code splitting and react lazy loading for some time.  Recently I implemented the CompressionWebpackPlugin to try to make the resulting bundles smaller .  All compressed files are successfully created including for those chunks that that are extracted through the magic comment features in the react code. However only the primary compressed bundles are actually utilized in the resulting package (e.g. bundle.js.gz, vendors~bundle.js.gz).  LazyLoad linkages are still pointing to the original chunk names, not the new compressed ones.

Example 'Magic comment' to create the react chunk ...
const {default: module} = await import(/* webpackChunkName: "ConfigDialogs" */ './settingsModal')

As all of the compressed bundles are created it does not appear to be an issue with CompressionWebpackPlugin, but rather an issue with the import. webpack.config.js included in this submit.

Any thoughts would be greatly appreciated.

**If the current behavior is a bug, please provide the steps to reproduce.**
[webpack.config.js.zip](https://github.com/webpack/webpack/files/4318207/webpack.config.js.zip)

**What is the expected behavior?**
The react lazy loader would load the compressed chunks instead of the uncompressed ones.

**Other relevant information:**
webpack version:  4.41.6
Node.js version: n/a
Operating System: MacOS
Additional tools: C#, React 16.12

**Comment by sokra** [comment]
The .gz file should never be requested. It up to the server to respond with the .gz file when the .js file is requested and the client accepts gzip compression.

**Comment by mustik22** [comment]
Thank you for the response.

As the chunk JS files are completely created with WebPack, the our server has little or no idea which files will be requested. That being said, the root script (bundle.js.gz/vendor~bundle.js.gz) is served as part of the view but there is no other knowledge of the react (JS?) file structure. Everything else is lazy-loaded as the user uses the product.

I believe what you are suggesting is that we somehow 'know' about the react chunks and trap for them them in the request pipeline. We would then return the .gz version of the file instead of the .js version of the file. That could be accomplished ... but I have found that one of the many advantages of WebPack has been the idea that the chunks are very dynamic and created as the react code evolves.

I believe doing as you suggest ties the back end too close to the front end code structure.

I would kindly ask you to either point me to some documentation that would describe a method of dealing with this, without loading the file names into the backend, or maybe someone knows of a method to indicate to the run-time that it should request the .gz version instead of the .js version of the file. I believe it is the compiled lazy-load code that decides the file name that is being requested from the server.

**Comment by mustik22** [comment]
Thanks, updated the C# middleware as you suggested.

All good!
