### ISSUE TITLE
Source map causes the source map file to appear in CSS

### ISSUE THREAD

**Issue by bosens-China** [webpack/webpack#10532]
Now I just want to generate the sourcemap file for JavaScript files, but I don't want to move the CSS file
What should I do, thank you

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
