### ISSUE TITLE
If devtool is source map, the source map will be generated for the CSS file

### ISSUE THREAD

**Issue by bosens-China** [webpack/webpack#10539]
## Feature request
Devtool for source-map will only generate a JavaScript sourceMap file, the sourceMap of the css is selected by the css-loader

**What is the expected behavior?**
In production mode, and devtool for source-map will only generate sourceMap for JavaScript files

**What is motivation or use case for adding/changing the behavior?**
``` js
// ...
  config
    .mode('production')
    .devtool( 'source-map' );
```

**How should this be implemented in your opinion?**

As above
**Are you willing to work on this yourself?**
yes

**Comment by evilebottnawi** [comment]
Yes, some loader still not respect devtool value, it can't be fixed on webpack side, it should be fixed on loader side, for css - css-loader (+ postcss-loader + sass-loader/less-loader)

**Comment by bosens-China** [comment]
> Yes, some loader still not respect devtool value, it can't be fixed on webpack side, it should be fixed on loader side, for css - css-loader (+ postcss-loader + sass-loader/less-loader)

Hi, is my expression not clear enough? I now want to manually control the display and hiding of JavaScript and css sourceMap.
``` js
     // ...
           {
             loader: 'css-loader',
             options: {
               sourceMap: true,
             },
           },
           {
             loader: 'less-loader',
             options: {
               sourceMap: true,
             },
           },
```
Now in source-map mode, I manually set `sourceMap: false` for css-loader, and the sourceMap file still appears.
what should I do

**Comment by evilebottnawi** [comment]
Please provide full reproducible test repo

**Comment by bosens-China** [comment]
## webpack.config.js
``` js
const MiniCssExtractPlugin = require("mini-css-extract-plugin");
const path = require("path");
const { CleanWebpackPlugin } = require("clean-webpack-plugin");
const HtmlWebpackPlugin = require("html-webpack-plugin");
module.exports = {
  entry: {
    app: "./src/main.js"
  },
  plugins: [
    new MiniCssExtractPlugin({
      filename: "[name].css",
      chunkFilename: "[id].css"
    }),
    new CleanWebpackPlugin(),
    new HtmlWebpackPlugin({
      title: "Production",
      template: "./src/index.html"
    })
  ],
  output: {
    filename: "[name].bundle.js",
    path: path.resolve(__dirname, "dist")
  },
  mode: "production",
  devtool: "source-map",
  module: {
    rules: [
      {
        test: /\.css$/,
        use: [
          {
            loader: MiniCssExtractPlugin.loader
          },
          {
            loader: "css-loader",
            options: {
              sourceMap: false
            }
          }
        ]
      }
    ]
  }
};
```

## package.json
``` json
{
  "name": "demo.js",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "css-loader": "^3.4.2",
    "mini-css-extract-plugin": "^0.9.0",
    "webpack": "^4.42.0",
    "webpack-cli": "^3.3.11"
  },
  "devDependencies": {
    "clean-webpack-plugin": "^3.0.0",
    "html-webpack-plugin": "^3.2.0"
  },
  "scripts": {
    "build": "webpack --config webpack.config.js"
  }
}
```

## build
``` sh
dist
├─ app.bundle.js
├─ app.bundle.js.map
├─ app.css
├─ app.css.map
└─ index.html
```

## Expected results
``` sh
dist
├─ app.bundle.js
├─ app.bundle.js.map
├─ app.css
└─ index.html
```

**Comment by evilebottnawi** [comment]
Bug in `mini-css-extract-plugin` https://github.com/webpack-contrib/mini-css-extract-plugin/issues/223, description bit confusing, but it is current bug
