### ISSUE TITLE
node-loader does not behave similar to original require function

### ISSUE THREAD

**Issue by cloppy** [webpack/webpack#1053]
I'm writing an application that uses nwjs as the browser and webpack as the packaging manager. The app will use mongoose to communicate with a mongoDB directly in the browser.

So I tried to require `mongoose`, but it always throws an error. After digging a little bit into the problem I narrowed it down to the `node-loader` of webpack.

At a deep level, the module `bson` tries to require a node file from the `bson_ext` module. This can be found in `bson/lib/bson/index.js`:

```javascript
// Catch error and return no classes found
  try {
    classes['BSON'] = require('bson-ext')
  } catch(err) {
    return exports.pure();
  }
```

The `bson-ext` module requires relative `./ext` and accesses the property `BSON`:

```javascript
var BSON = require('./ext').BSON;

// ....

module.exports = BSON;
```

And in this ext file it tries to require a `.node` file:

```javascript
// Attempt to load the release bson version
	try {
		bson = require('../build/Release/bson');
	} catch (err) {
		console.dir(err)
		console.error("js-bson: Failed to load c++ bson extension, using pure JS version");
		throw new Error("js-bson: Failed to load c++ bson extension, using pure JS version");
	}
```

I tried the node-loader but it just returned an empty object instead of a native function. Using the `raw-loader` just gave me the plain compiled stuff, that I obviously cannot use.

Could somebody please dig into this? I think it's pretty vital that the node-loader acts as the original require function when passing in a node file.

**Comment by sokra** [comment]
Seems like the signature of `process.dlopen` changes since I created the node-loader. see https://github.com/joyent/node/commit/15508589a163b0c9f09ac608281f9ebb015d4deb
It should be easy to adapt the [node-loader](https://github.com/webpack/node-loader]. You can send a PR.

**Comment by cloppy** [comment]
I'm not quite sure how to fix this (I don't get alle the magic things that happen in webpack).

Can you give me some explanation what to do?

**Comment by grabbou** [comment]
Well, I've submitted the updated signature but this does not resolve the original issue as the `process.dlopen` is not a function anyway.

**Comment by kevzettler** [comment]
@sokra what version of node is node-loader compatiblie with?

**Comment by kevzettler** [comment]
@grabbou not seeing your PR actually against the webpack/node-loader repo

https://github.com/webpack/node-loader/pulls

**Comment by jwaldrip** [comment]
Can we get this merged in?
