### ISSUE TITLE
Using @angular-devkit and webpack for builds, webpack complains especially with angular i18n builds

### ISSUE THREAD

**Issue by bwsimiyu** [webpack/webpack#10530]
## Feature request

**What is the expected behavior?**
Writable should be set to true at _webpack/lib/Stats.js_
`Object.defineProperty(obj, "_showWarnings", {
        value: showWarnings,
        enumerable: false
});
Object.defineProperty(obj, "_showErrors", {
        value: showErrors,
        enumerable: false,
});`

**What is motivation or use case for adding/changing the behavior?**
Object.defineProperties, by default writable is set to false

**How should this be implemented in your opinion?**
`Object.defineProperty(obj, "_showWarnings", {
	value: showWarnings,
        enumerable: false,
        writable: true
});
Object.defineProperty(obj, "_showErrors", {
	value: showErrors,
        enumerable: false,
        writable: true
});`

**Are you willing to work on this yourself?**
yes

**Comment by evilebottnawi** [comment]
What is use case?

**Comment by bwsimiyu** [comment]
The @angular-devkit builds

**Comment by evilebottnawi** [comment]
Please provide real use case, thanks
