### ISSUE TITLE
Feedback on the webpack 5 stats output

### ISSUE THREAD

**Issue by sokra** [webpack/webpack#10534]
In this issue I want to collect feedback on the state output for webpack. For webpack 5 we have the change the improve the default output. For webpack 5 the Stats internally has been refactored to extensibility, but the output has kept as it was in webpack 4 (expect for some minor changes).

Please leave any feedback you like. Here are some question to inspire you:

* What information is important for you?
  * Regarding the default output: What pieces of the output did you enable with the `stats` option?
* What information distracts you and is unneeded?
  * Regarding the default output: What pieces of the output did you disable with the `stats` option?
* How can information shown in a better way?
  * Readablility?
  * More useful format?
  * Missing aspects?
  * Color and highlighting?
* Maybe paste a screenshot of your output
* Do you use a custom tool for displaying webpack results?

---

Here are some examples of stats output:

Small build:

![image](https://user-images.githubusercontent.com/1365881/76401108-acd82980-6381-11ea-8353-6dbe40d47339.png)

Small build with many node_modules:

![image](https://user-images.githubusercontent.com/1365881/76401316-f7f23c80-6381-11ea-88ea-ab76b50bb1be.png)

Large build:

![image](https://user-images.githubusercontent.com/1365881/76401635-7fd84680-6382-11ea-8276-662e8165faae.png)

![image](https://user-images.githubusercontent.com/1365881/76401675-9383ad00-6382-11ea-91ca-245559af04fb.png)

Incremental build in watch mode:

![image](https://user-images.githubusercontent.com/1365881/76404466-ccbe1c00-6386-11ea-9050-65b73dbd478a.png)

---

Here is my own feedback:

* node_modules in the stats is not as useful.
* The assets table doesn't scale well for many assets or long asset names
* Hash seem to be useless
* Version, Time and Build at could be displayed in a more condensed way, in a single line, headers can be omitted
* There is no success/failure summary. Best this would be at the end of the output.
* Sizes of modules are not as useful as it doesn't include sizes of dependencies.
* KiB vs MiB is not really obvious, large assets are easy to miss
* hidden modules/assets may confuse
* In small builds:
  * `[emitted]` is useless
  * Entrypoint is useless when there is only one with a single file
  * Asset meta info like `[name: main]` is useless
  * Time is useless
  * Module meta info like `[built]` and size is useless
* In large builds:
  * Long list of files for an Entrypoint is useless
  * List of 15 (random?) modules is useless in first build, but useful in incremental build
  * Assets list is useless in first build, but useful in incremental build
  * All `[dev]` assets are useless

Here are some ideas:

* Hide `[dev]` assets by default
* When assets > 15, group them by extension and flags:
  * 14 *.js [emitted] [immutable], 4 *.js [emitted], 13 *.css [emitted] [immutable]
  * always show assets which are too large
* Hide Entrypoints by default when 1 entrypoint with 1 file
* Show total size of files in entrypoint
* Summarize entrypoint files when > 5: `Entrypoint main = 7 asset 3.45 MiB (14 auxilary assets 3.45 MiB)`
* Hide module size by default
* Hide `[built]` flag when only build assets are shown
* Hide `[emitted]` flag when only emitted assets are shown
* Show summary of hidden asset/modules
  * `+ 9 hidden asset (3 not emitted assets, 6 dev assets)`
  * `+ 541 hidden modules (500 not built modules, 32 not included modules, 9 runtime modules)
* Display assets in list instead of table, like modules
* remove color from folders in asset name, highlight the extension.
* Instead of hiding modules that doesn't fit in the limit, group them by folders
  * This should automatically group node_modules in a useful way
* Show modules in a tree groups by folder
  * show only folder summary when module limit has been reached
  * excluded modules will always by show as summary
  * Can we do the same for the assets list?
  * Should this be done in the JSON too?

``` text
./js/
  index.js 7.85 KiB [built]
  indexedDB.js 1.04 KiB [built]
  butterchurnOptions.ts 2.92 KiB [built]
  dropboxFilePicker.ts 923 bytes [built]
../node_modules/
  raven-js/ 5 modules 838 bytes [built]
  react/ 4 modules 190 bytes [built]
  react-dom/ 6 modules 1.33 KiB [built]
  raven-for-redux/built/ 10 modules 2.22 KiB [built]
  butterchurn/lib/isSupported.min.js 1.4 KiB [built]
../skins/base-2.91-png.wsz 104 bytes [built]
../js/
  constants.ts 1.33 KiB [built]
  selectors.ts 18.4 KiB [built]
  actionTypes.ts 4.48 KiB [built]
  webampLazy.tsx 9.58 KiB [built]
  actionCreators/index.ts 4.15 KiB [built]
```

**Comment by Munter** [comment]
The alphabetically sorted final file names are not very useful at all. Especially because they can get so long that relevant information is quite hard to spot.

Suggestions:
- Move the file name from the first column to the last column and left align.
- Add a file extension column somewhere early in the column order
- Group rows by file extension, then sort by size maybe? Could also be sorted by breadth first dependency graph order
- Don't show files marked as `[dev]` by default
- If the point of the size is to be able to compare, output the number in kilobytes formatted with thousands seperators. If the point is to see that something is big, make it have more digits. Possibly do this as an addition to the current size column. The current one is good to use in conversation, but hard to skim and spot patterns from

**Comment by StringEpsilon** [comment]
Our project is medium to big. On default settings, I get the following info I'd consider unhelpful for my day to day building needs:

* Asset size warnings for image assets (.jpg). Can't do anything about those. - 33 lines
* Module details for the entries we have - 32 lines (30 modules listed + "n hidden assets"
* Emit info for static assets that only get copied over (fonts, images, svgs, ...): 132 lines
* Hash - I don't actually know what that hash means.
* Time - My build pipeline makes that available for me anyway.
* Built at - My build pipeline makes that available for me anyway.

I use these settings normally:

```js
stats: {
  all: false,
  assets: true,
  excludeAssets: !assetName.endsWith(".js")),
  assetsSort: "!size",
  errors: true,
}
```

Which gives me 45 lines of output vs. over 300.

**Comment by donaldpipowitch** [comment]
I look at watch logs most of the time. Here I want very few information. Time stamp of the build, warnings, error - respecting error/warning filtering (which afaik currently doesn't work). Maybe how long the build took. Maybe some progress indicator. Errors and warnings should be "as uniform as possible" across loaders and plugins.

I have no big opinion on the log of production builds however. 🙂

**Comment by vankop** [comment]
It is very hard to decide what is better for default, but it will be great to make most of output optional, especially:
- node_modules in stats.
- customize assets table/list
- hash in files
- size 
- `[built]`, `[emitted]` and other flags

`ls` tool has awesome flags for filesystem info =)
- format (presets for formatting)
- size (kilobytes are optional)
- sort
- columns settings (like width of the column, tabsize)

**Comment by getsnoopy** [comment]
There should be a space between the measurement quantities and their unit symbols, as outlined in the referenced issue above. E.g., "100 ms" instead of "100ms". I have the code ready for this. Should I just open a PR tagged with this issue?

**Comment by garygreen** [comment]
I think it should be fairly minimal by default and just list entry => chunk file outputs.

From the perspective of developers, we just deal with entry points, webpack then handles the dependency graph and outputs the chunks. Personally I'm not interested in what happens in between. If I wanted to dig further and understand *why* certain things are in the output chunks then I would enable a option to have more verbose stats, but in typical day to day operations I'm only interested in seeing when entry points change and what the end output was.

I use:

```js
   stats: {
    all: false,
    entrypoints: true,
    chunkGroups: true,
    timings: true,
    errors: true,
   },
```

Would be nice if you could add filesizes to this.

**Comment by khader69** [comment]
articles.html

**Comment by khader69** [comment]
> articles.html

**Comment by khader69** [comment]
#

**Comment by chenxsan** [comment]
@sokra 

> For webpack 5 the Stats internally has been refactored to extensibility, but the output has kept as it was in webpack 4 (expect for some minor changes).

I found that webpack 5 stats output quite different from webpack 4 in some cases which kind of break webpack-hot-middleware's function https://github.com/webpack-contrib/webpack-hot-middleware/blob/master/middleware.js#L118 because it relies on the output [`module.id`](https://github.com/webpack-contrib/webpack-hot-middleware/blob/master/middleware.js#L172) which unfortunately is missing from webpack 5's output.

I set up a repository here https://github.com/chenxsan/test-webpack-stats-json/commit/81a9f590b582506e0a0e94eb82cd7c719cf7dfdd just in case you might want to check.

**Comment by raulchedrese** [comment]
Our project has 60+ entry points and the default output was extremely overwhelming. We landed on a minimal output config.

```js
stats: {
    assetsSort: '!size',
    children: false,
    usedExports: false,
    modules: false,
    entrypoints: false,
    // Hide source maps from output
    excludeAssets: [/\.*\.map/]
}
```

The most important information for us is the bundle size or more specifically the change in bundle size.

**Comment by khader69** [comment]
Sorry for the miracle??? +
It is so much fun to have a great time

**Comment by ScriptedAlchemy** [comment]
Easier ways to infer Federation data. Where is a remote consumed, what requirements does an exposed module have, who uses a shared remote. It’s complex to do now.  It I’ll send you my repo and you can see

**Comment by erykpiast** [comment]
What happened to the `source` field of module object? In the general issue [I can see somebody complaining](https://github.com/webpack/webpack/issues/9802#issuecomment-624428356) but without response.

I'm trying to add support for Webpack 5 to [webpack-stats-explorer](https://github.com/erykpiast/webpack-stats-explorer/issues/335) and it's the last piece missing. Unfortunately having the module source is crucial for this tool, as it's all about showing the difference of bundle contents between subsequent builds.

**Comment by evilebottnawi** [comment]
@erykpiast ?

```js
const { modules } = stats.toJson({ source: true });
```

**Comment by erykpiast** [comment]
@evilebottnawi thank you for the answer! I use rather CLI than the programmatic approach. Is there any chance to have this in stats outputted from `webpack --json` command? [I experimented with specifing options in `stats` section of the config](https://codesandbox.io/s/webpack-stats-explorer-playground-article-g-9g0uz?file=/webpack.config.js:50-96), but unfortunatelly without results ([see stats.json file](https://codesandbox.io/s/webpack-stats-explorer-playground-article-g-9g0uz?file=/stats.json); call `yarn build` from terminal to regenerate).

**Comment by evilebottnawi** [comment]
@erykpiast yep, not implement yep, WIP

**Comment by wojtekmaj** [comment]
> display assets in stats in a list instead of a table

Can I get the old behavior somehow via config? I find the new output a little too hard to read.

**Comment by evilebottnawi** [comment]
@wojtekmaj Can you provide screen show? We remove table view and switch on previously, but I would like to make sure that we are talking about the same

**Comment by wojtekmaj** [comment]
Yes, I'm talking about this...

<img width="1122" alt="obraz" src="https://user-images.githubusercontent.com/5426427/89899835-23a07980-dbe3-11ea-9238-6e62b888c05c.png">

**Comment by evilebottnawi** [comment]
https://github.com/webpack/webpack/issues/8811 - Always print `errors` and `warnings` at bottom

**Comment by sokra** [comment]
First steps for improvements in beta.30:

> Small build:
> 
> ![image](https://user-images.githubusercontent.com/1365881/76401108-acd82980-6381-11ea-8353-6dbe40d47339.png)

![image](https://user-images.githubusercontent.com/1365881/92974634-f74c7700-f486-11ea-8a53-53b8fc1b17ce.png)


> Small build with many node_modules:
> 
> ![image](https://user-images.githubusercontent.com/1365881/76401316-f7f23c80-6381-11ea-88ea-ab76b50bb1be.png)

![image](https://user-images.githubusercontent.com/1365881/92973882-51e4d380-f485-11ea-8671-42fd3253f3c8.png)

> Large build:
> 
> ![image](https://user-images.githubusercontent.com/1365881/76401635-7fd84680-6382-11ea-8276-662e8165faae.png)
> 
> ![image](https://user-images.githubusercontent.com/1365881/76401675-9383ad00-6382-11ea-91ca-245559af04fb.png)

![image](https://user-images.githubusercontent.com/1365881/92974305-30381c00-f486-11ea-9b48-c78ecd9d31be.png)

> Incremental build in watch mode:
> 
> ![image](https://user-images.githubusercontent.com/1365881/76404466-ccbe1c00-6386-11ea-9050-65b73dbd478a.png)

![image](https://user-images.githubusercontent.com/1365881/92974407-66759b80-f486-11ea-92e6-b3a5f14b07e5.png)

**Comment by sokra** [comment]
Thanks for all the feedback. I tried to improve the output. Sorry if not all feedback have been implemented, we try to cover all use cases, so you might configure the stats a little bit for your use case.

**Comment by evilebottnawi** [comment]
Anyway if you want to something improve or found some very annoying or misleading feel free to open a new issue :star:

**Comment by alexander-akait** [comment]
What do you need to improve in stats output?

**Comment by erykpiast** [comment]
@alexander-akait see my first comment from months ago :) The `source` field from the `module` object is missing. I use it in the tool to display what was the code processed by Webpack (after Babel/TypeScript transpilation if you use one). I cannot do it when it's not available in stats.

**Comment by alexander-akait** [comment]
hm, feel free to send a PR
