### ISSUE TITLE
Using module.hot from an npm module, currently impossible

### ISSUE THREAD

**Issue by Pixelatex** [webpack/webpack#10559]
So what I have is a SSR framework similar to next.js. 

However, in order to get the server-side hot reloading I need to have the module.hot code inside the website itself. It's impossible to extend this code from an npm package due to the fact that `module.hot.accept` requires a direct path. 

```
if (module.hot) {
  console.log('✅  Server-side HMR Enabled!');

  module.hot.accept('./server', () => {
    console.log('🔁  HMR Reloading `./server`...');

    try {
      app = require('./server.js');
      server.removeListener('request', currentApp);
      server.on('request', app);
      currentApp = app;
    } catch (error) {
      console.error(error);
    }
  });
}
```
In an ideal scenario we should be able to pass a reference to a file or a directory to the accept function.

e.g.

```
module.hot.accept(server, () => {
```

or

```
module.hot.accept('./server', process.cwd() , () => {
```

This is something that is almost impossible to find documentation on and I do feel this is a feature that should be possible or documented how it can be done.

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
