### ISSUE TITLE
Support node Conditional Exports 

### ISSUE THREAD

**Issue by xiaoxiangmoe** [webpack/webpack#10555]
## Feature request

**What is the expected behavior?**

[resolve.mainFields](https://webpack.js.org/configuration/resolve/#resolvemainfields) should support [Conditional Exports](https://nodejs.org/api/esm.html#esm_conditional_exports) in nodejs

```json
  "exports": {
    ".": {
      "require": "./dist/my-lib.cjs",
      "import": "./dist/my-lib.mjs"
    }
  }
```

**Comment by sokra** [comment]
Yep, we will add support for this in webpack 5.

**Comment by evilebottnawi** [comment]
Duplicate of #9509
