### ISSUE TITLE
expose multiple libraries in one file

### ISSUE THREAD

**Issue by camsong** [webpack/webpack#1055]
How to expose multiple libraries in one file. With browserify before, we can expose `jquery`, `react`, `lodash` at once like in our `op-vendor` npm package, we declare all of our dependencies:
```
browserify()
  .require('react/addons', {expose:'react/addons'})
  .require('jquery', {expose:'jquery'})
  .require('lodash', {expose:'lodash'})
```
In the our reals project, it only require `op-vendor` package, and can require all the libraries.

After google for a while, I still can not find how to use webpack to do this. any help is appreciated. thanks.

**Comment by ernestorocha** [comment]
Any luck with that ?

**Comment by camsong** [comment]
Yes for sure.

### `op-vendor` settings
First, mount `jquery`,`react`,`lodash` in `index.js` file of `op-vendor` project and make it global by setting output to `umd`:

```js
# webpack.config.js
    output: {
      path: destDir,
      filename: '[name].js',
      library: 'op-vendor',
      libraryTarget: 'umd'
    },
```

```js
# index.js
exports.react    = require('react');
exports.jquery  = require('jquery');
exports.lodash = require('lodash');
```

### Real Project Settings

By now, you should be able to access `react` like this:
```
const react = window['op-vendor'].react;
```

Not looking good, right? what we need is doing like this:

```
import react from 'react';
```

So you also need to set alias of `react` to `window['op-vendor'].react`, so `externals` came in to help.

```js
# webpack.config.js
    externals: [
      'op-vendor', 
      { react: { window: [ 'op-vendor', 'react' ] },
      { jquery: { window: [ 'op-vendor', 'jquery' ] },
      { lodash: { window: [ 'op-vendor', 'lodash' ] }
    ],

```

That's it, notify me if not helps

**Comment by ernestorocha** [comment]
Yeah. In the end that was kinda what I did. But initially my plan was other. Like export to the global scope as a `React` or `Lodash` variable.

Anyway, I got it working, for every bundle defined I can do this `bundle('my-component')`.

Thanks!

**Comment by seajean** [comment]
@ernestorocha  Hi, I came across the same problem, how you manager to do that?

**Comment by camsong** [comment]
@seajean You may try [webpack DLL](https://github.com/webpack/webpack/tree/master/examples/dll). It can build multiple packages into one bundle, also no need to using `externals` alias.

**Comment by seajean** [comment]
webpack DLL is not what I want, just wonder why webpack didn't add this feature, and @bebraw  just closed this issue without saying a word..
