### ISSUE TITLE
HasOwnProperty

### ISSUE THREAD

**Issue by bartoszgolebiowski** [webpack/webpack#10565]
Hello, I am using single-spa framework.
I have some shared dependencies like 'react' in my app shell.
While loading micro frontend with 'react-table' dependency I received this:

![image](https://user-images.githubusercontent.com/39523638/76617878-7cca8b00-6527-11ea-8a94-b7b9efe6df51.png)

```js
(function (global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports, require('react')) :
  typeof define === 'function' && define.amd ? define(['exports', 'react'], factory) :
  (global = global || self, factory(global.ReactQuery = {}, global.React));
}(this, (function (exports, React) { 'use strict';

  React = React && React.hasOwnProperty('default') ? React['default'] : React
```

![image](https://user-images.githubusercontent.com/39523638/76617978-bac7af00-6527-11ea-9754-4fd9b46ba615.png)

React variable is Module and does not have hasOwnProperty function.

Is this any workaround for this problem?

![image](https://user-images.githubusercontent.com/39523638/76618199-42152280-6528-11ea-8350-a9d02f9be079.png)

This is from the localhost application.

The solution is:
```js
  React && React['default'] ? React['default'] : React 
```
Webpack output is:
```js
  React = React && React.hasOwnProperty('default') ? React['default'] : React
```

BR
Bartosz Gołębiowski

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
