### ISSUE TITLE
Node Optimist being Deprecated

### ISSUE THREAD

**Issue by sadiqevani** [webpack/webpack#1056]
So, i noticed that Optimist is being deprecated and won't be supported in the future.

It might be a good idea to use some other plugin: 

https://github.com/substack/node-optimist

**Comment by IngwiePhoenix** [comment]
On Optimist’s page, it recommends yargs. Just swap the module, no code change required. :)

**Comment by luqin** [comment]
[minimist](https://www.npmjs.com/package/minimist)
