### ISSUE TITLE
Question Mark Character (`?`) in File Name

### ISSUE THREAD

**Issue by Husterknupp** [webpack/webpack#10568]
# Bug report

**What is the current behavior?**

```
$ npx webpack --mode=production src/index\?.js
...
ERROR in Entry module not found: Error: Can't resolve '<personal path>/webpack-demo/src/index?.js' in '<personal path>/webpack-demo'
```

```
$ tree -I "node_modules"
.
├── README.md
├── dist
│   └── main.js
├── index.html
├── package-lock.json
├── package.json
└── src
    ├── index.bak.js
    └── index?.js

2 directories, 7 files
```

I am trying to use an entry point that has a question mark character (`?`) in its file name. webpack apparently has problems loading this even though MacOS seems to be treating it as a legal file name.

**If the current behavior is a bug, please provide the steps to reproduce.**

This [GitHub repo](https://github.com/Husterknupp/webpack-issue-10568) has my 'config' and instructions on how to reproduce.

I don't think this is related to a plugin since I've tried to keep my config as minimal as possible. It's basically the first three steps from the webpack getting-started, no additional plugin / file type loader.

**What is the expected behavior?**

As long as MacOS can handle file names with question mark characters (`?`) I'd expect webpack to treat such files not special and bundle them just fine. But maybe I'm missing something on special characters here (please point me to it!). I didn't find anything when I searched for special characters/filenames in the docs on webpack.js.org.

Exactly: `npx webpack --mode=production src/index\?.js` should output the same bundle as `npx webpack --mode=production src/index.bak.js` does. I'm using index.bak.js as example here because the src/ directory must not contain the default entry point (index.js). Otherwise my broken case would fall back to using index.js and I could not make it fail.

**Other relevant information:**
webpack version:  4.42.0
Node.js version: v10.14.2
Operating System: macOS 10.15.3 (19D76)
Additional tools: *none*

EDIT: add GitHub link (how to reproduce)

**Comment by Mistyyyy** [comment]
Webpack treats the module path as an `identifier` in [enhanced-resolve](https://github.com/webpack/enhanced-resolve) including entry file
and webpack support query params in module path used to apply loader like `url-loader`.
```javascript
 import style from './css?inline'

// loader config
{
   test: /\.css$/,
   resourceQuery: /inline/,
   use: 'url-loader'
}
```
so, before webpack resolve the module's path, it would parse and find the query params.
the code logic shows below
```javascript
if (identifier === "") return null;
    const part = {
      request: "",
      query: "",
      module: false,
      directory: false,
      file: false
    };
    const idxQuery = identifier.indexOf("?");
    if (idxQuery === 0) {
      part.query = identifier;
    } else if (idxQuery > 0) {
      part.request = identifier.slice(0, idxQuery);
      part.query = identifier.slice(idxQuery);
    } else {
      part.request = identifier;
    }
    if (part.request) {
      part.module = this.isModule(part.request);
      part.directory = this.isDirectory(part.request);
      if (part.directory) {
        part.request = part.request.substr(0, part.request.length - 1);
      }
    }
    return part;
```
so webpack mistake the `?` and view it as a query params, it may be a bug or intended.

**Comment by Husterknupp** [comment]
Thanks, that tells me that the issue doesn't seem to be about special characters in general but about the fact that there seems to be semantics encoded in the file name which I was not aware of.

However, in my particular use case we're using dynamic imports on files with arbitrary file names (including ? characters). 

```js
const file = userSelects(); // e.g., 'to be or not to be?.png' - nothing loader-related
await import(`./assets/${file}`) // we need `file.default`'s export
// ..
```

Those files are loaded during run time, and we don't need to configure loaders dynamically for them by passing url parameters (or I don't see where it would make sense).

Is there a particular use case for dynamic module loading with additional dynamic loader config, ie, is this a bug or intended (repeating your question, @Mistyyyy )?

**Comment by sokra** [comment]
These module requests are in fact URLs. In URLs some chars have special meaning (e. g. `?` or `#`). You must not use them in filenames. webpack also adds `!` as special char, which must also not used.

Yes this is a limitation, but we don't intend to change this. Some OSes doesn't even allow `?` as filename.

**Comment by igorpupkinable** [comment]
TS throws the following exception with query parameters.
```
TS2307: Cannot find module './logo.png?inline' or its corresponding type declarations.
```
