### ISSUE TITLE
'code of conduct' routes to openjsf.org

### ISSUE THREAD

**Issue by Parikshit-Hooda** [webpack/webpack#10564]
# Bug report

**What is the current behavior?**

'Code of conduct' link in CODE_OF_CONDUCT.md routes of openjsf.org . check it out here : https://github.com/webpack/webpack/blob/master/CODE_OF_CONDUCT.md

**If the current behavior is a bug, please provide the steps to reproduce.**
1. go to https://github.com/webpack/webpack/blob/master/CODE_OF_CONDUCT.md
2. click on the link in the file.
3. the link routes to https://openjsf.org/ 

**What is the expected behavior?**
It should route to a file similar to this(or this only)https://github.com/mochajs/mocha/blob/master/.github/CODE_OF_CONDUCT.md . 
The reason of choosing this file is that mocha is also under jsfoundation. Simply linking to https://openjsf.org doesn't link the seeker to a code_of_conduct file(which is expected).

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

**Comment by Parikshit-Hooda** [comment]
Would like to fix this, after a discussion on this issue.

**Comment by evilebottnawi** [comment]
Feel free to send a PR with fixed link https://github.com/openjs-foundation/code-and-learn/blob/master/CODE_OF_CONDUCT.md

**Comment by Parikshit-Hooda** [comment]
Looks like ryanclark has already raised a PR. will move on to the next one. Thanks @ryanclark

**Comment by Parikshit-Hooda** [comment]
@evilebottnawi I am gonna raise a PR as well to cover this task and some typo fixes as well.

**Comment by evilebottnawi** [comment]
Do not mix difference problems in the one PR

**Comment by Parikshit-Hooda** [comment]
I didn't want to raise an issue for typo fixes, as brought under my notice by you recently.
