### ISSUE TITLE
Prototype Pollution for minimist

### ISSUE THREAD

**Issue by vmatchenko** [webpack/webpack#10574]
Hi, could you update this dependency on the new version?

  Moderate        Prototype Pollution                                           
  Package         minimist                                   
  Patched in      >=1.2.3                        
  Dependency of   webpack-dev-server [dev]
  Path               webpack-dev-server > chokidar > fsevents > node-pre-gyp > tar > mkdirp > minimist                                                                                               
  More info       https://npmjs.com/advisories/1179                             
                                                                                
                                                                                
  Moderate        Prototype Pollution               
  Package         minimist                                        
  Patched in      >=1.2.3                                             
  Dependency of   webpack [dev]                      
  Path            webpack > watchpack > chokidar > fsevents > node-pre-gyp > rc > minimist                               
  More info       https://npmjs.com/advisories/1179

**Comment by millerthegorilla** [comment]
This is a duplicate of #10561
mkdirp needs to be updated to >1.0.0.   Mkdirp has had a major version change, as the API has changed to use promises.
I tried using the resolutions field with https://www.npmjs.com/package/npm-force-resolutions
but the change to the api is too much.

**Comment by millerthegorilla** [comment]
Doh.  Reading the rest of that issue #10561, I see that a request for a backport fix was made to the mkdirp team.
So I added the following line to the resolutions section of my package.json:
    "mkdirp": "^0.5.3"
and then ran npm install, keeping in mind that I have https://www.npmjs.com/package/npm-force-resolutions with a pre-install script installed.
This then updated mkdirp and no vulnerabilities were reported.
