### ISSUE TITLE
[performance] seal is slow with a lot of import()

### ISSUE THREAD

**Issue by sibelius** [webpack/webpack#10579]
# Bug report

**What is the current behavior?**
webpack is taking too much time to rebuild

**If the current behavior is a bug, please provide the steps to reproduce.**
not a bug, but a performance issue

here are some prints

![image](https://user-images.githubusercontent.com/2005841/76999891-32d21280-6936-11ea-960b-c817fad768c1.png)

## incremental build 2
rebuild takes 6s for us
![image](https://user-images.githubusercontent.com/2005841/76999949-47160f80-6936-11ea-8bec-efc9d994cddb.png)

most time is on `seal` and `lazyCompileHook`

this profile was taken using this plugin https://github.com/jantimon/cpuprofile-webpack-plugin

you can access the profile info here
[webpack-cpu.zip](https://github.com/webpack/webpack/files/4351022/webpack-cpu.zip)

webpack config gist: https://gist.github.com/sibelius/8356d3e9c10dce76b35b36c9e38260ae

related to https://github.com/webpack/webpack/issues/9460

our code has many `loadable(() => import('')` (lazy chunks), more than 600

**What is the expected behavior?**
it should be fast on seal and webpack parts

**Other relevant information:**
webpack version:  4.42.0
Node.js version: v12.16.1
Operating System: macOsX
Additional tools: most webpack plugins are using the latest versions

**Comment by evilebottnawi** [comment]
We are working on webpack@5, please test code using webpack@5, webpack@4 takes only fixes (no features/improvements)

**Comment by evilebottnawi** [comment]
Let's bump, i think we can optimize it in future

**Comment by sibelius** [comment]
we moved from react-hot-loader to react refresh and the rebuild improved a lot

I can reopen when I profile it again

thanks
