### ISSUE TITLE
Failed resolve dependencies for sails framework build

### ISSUE THREAD

**Issue by p-g-krish** [webpack/webpack#10581]
Hi,
      When i bundle the sails application with below webpack config file. 

```
module.exports = {
    // You need to list out every file you want to bundle in `entry`
    entry: {
      express: `${process.cwd()}/server.js`
    },
    output: {
      // Write to the '/dist' directory relative to the directory
      // where `webpack` is running
      path: `${process.cwd()}/dist`,
      // Webpack will bundle `src/foo.js` into `dist/foo.min.js`
      // because of `[name]`.
      filename: '[name].min.js'
    },
    target: 'node'
  };
```

i facing the following error

_

> Hash: 6edb23275685f0c8a0d0
> Version: webpack 4.42.0
> Time: 6556ms
> Built at: 03/19/2020 10:37:54 AM
>  1 asset
> Entrypoint express = express.min.js
>   [0] external "util" 42 bytes {0} [built]
>   [2] external "path" 42 bytes {0} [built]
>   [5] external "fs" 42 bytes {0} [built]
>   [8] external "stream" 42 bytes {0} [built]
>  [10] (webpack)/buildin/module.js 497 bytes {0} [built]
>  [19] external "assert" 42 bytes {0} [built]
>  [21] external "events" 42 bytes {0} [built]
>  [27] external "crypto" 42 bytes {0} [built]
>  [32] external "http" 42 bytes {0} [built]
>  [41] external "os" 42 bytes {0} [built]
>  [49] external "querystring" 42 bytes {0} [built]
>  [69] external "url" 42 bytes {0} [built]
> [284] ./server.js 1.86 KiB {0} [built]
> [308] ./node_modules/sails/lib/hooks sync ^\.\/.*$ 4.71 KiB {0} [built]
> [621] ./node_modules/sails/lib/app/configuration sync 160 bytes {0} [optional] [built]
>     + 646 hidden modules
> 
> WARNING in ./node_modules/sails/lib/hooks/session/index.js 365:33-118
> Critical dependency: the request of a dependency is an expression
>  @ ./node_modules/sails/lib/hooks sync ^\.\/.*$
>  @ ./node_modules/sails/lib/app/configuration/index.js
>  @ ./node_modules/sails/lib/app/load.js
>  @ ./node_modules/sails/lib/app/Sails.js
>  @ ./node_modules/sails/lib/app/index.js
>  @ ./node_modules/sails/lib/index.js
>  @ ./server.js
> 
> WARNING in ./node_modules/machine/lib/pack.js 212:16-38
> Critical dependency: the request of a dependency is an expression
>  @ ./node_modules/machine/index.js
>  @ ./node_modules/sails/lib/hooks/helpers/index.js
>  @ ./node_modules/sails/lib/hooks sync ^\.\/.*$
>  @ ./node_modules/sails/lib/app/configuration/index.js
>  @ ./node_modules/sails/lib/app/load.js
>  @ ./node_modules/sails/lib/app/Sails.js
>  @ ./node_modules/sails/lib/app/index.js
>  @ ./node_modules/sails/lib/index.js
>  @ ./server.js
> 
> WARNING in ./node_modules/sails-stringfile/gettext.js 42:15-38
> Critical dependency: the request of a dependency is an expression
>  @ ./node_modules/sails-stringfile/index.js
>  @ ./node_modules/sails/lib/hooks/blueprints/index.js
>  @ ./node_modules/sails/lib/hooks sync ^\.\/.*$
>  @ ./node_modules/sails/lib/app/configuration/index.js
>  @ ./node_modules/sails/lib/app/load.js
>  @ ./node_modules/sails/lib/app/Sails.js
>  @ ./node_modules/sails/lib/app/index.js
>  @ ./node_modules/sails/lib/index.js
>  @ ./server.js
> 
> WARNING in ./node_modules/express/lib/view.js 81:13-25
> Critical dependency: the request of a dependency is an expression
>  @ ./node_modules/sails/lib/hooks/http/view.js
>  @ ./node_modules/sails/lib/hooks sync ^\.\/.*$
>  @ ./node_modules/sails/lib/app/configuration/index.js
>  @ ./node_modules/sails/lib/app/load.js
>  @ ./node_modules/sails/lib/app/Sails.js
>  @ ./node_modules/sails/lib/app/index.js
>  @ ./node_modules/sails/lib/index.js
>  @ ./server.js
> 
> WARNING in ./node_modules/include-all/lib/help-include-all-sync.js 293:32-49
> Critical dependency: the request of a dependency is an expression
>  @ ./node_modules/include-all/index.js
>  @ ./node_modules/sails/lib/app/private/controller/load-action-modules.js
>  @ ./node_modules/sails/lib/app/reload-actions.js
>  @ ./node_modules/sails/lib/app/Sails.js
>  @ ./node_modules/sails/lib/app/index.js
>  @ ./node_modules/sails/lib/index.js
>  @ ./server.js
> 
> WARNING in ./node_modules/include-all/lib/help-include-all-sync.js 269:27-52
> Critical dependency: the request of a dependency is an expression
>  @ ./node_modules/include-all/index.js
>  @ ./node_modules/sails/lib/app/private/controller/load-action-modules.js
>  @ ./node_modules/sails/lib/app/reload-actions.js
>  @ ./node_modules/sails/lib/app/Sails.js
>  @ ./node_modules/sails/lib/app/index.js
>  @ ./node_modules/sails/lib/index.js
>  @ ./server.js
> 
> WARNING in ./node_modules/sails-stringfile/gettext.js 49:15-38
> Critical dependency: the request of a dependency is an expression
>  @ ./node_modules/sails-stringfile/index.js
>  @ ./node_modules/sails/lib/hooks/blueprints/index.js
>  @ ./node_modules/sails/lib/hooks sync ^\.\/.*$
>  @ ./node_modules/sails/lib/app/configuration/index.js
>  @ ./node_modules/sails/lib/app/load.js
>  @ ./node_modules/sails/lib/app/Sails.js
>  @ ./node_modules/sails/lib/app/index.js
>  @ ./node_modules/sails/lib/index.js
>  @ ./server.js
> 
> WARNING in ./node_modules/sails/lib/hooks/moduleloader/index.js 556:23-92
> Critical dependency: the request of a dependency is an expression
>  @ ./node_modules/sails/lib/hooks sync ^\.\/.*$
>  @ ./node_modules/sails/lib/app/configuration/index.js
>  @ ./node_modules/sails/lib/app/load.js
>  @ ./node_modules/sails/lib/app/Sails.js
>  @ ./node_modules/sails/lib/app/index.js
>  @ ./node_modules/sails/lib/index.js
>  @ ./server.js
> 
> WARNING in ./node_modules/sails/lib/hooks/moduleloader/index.js 452:38-55
> Critical dependency: the request of a dependency is an expression
>  @ ./node_modules/sails/lib/hooks sync ^\.\/.*$
>  @ ./node_modules/sails/lib/app/configuration/index.js
>  @ ./node_modules/sails/lib/app/load.js
>  @ ./node_modules/sails/lib/app/Sails.js
>  @ ./node_modules/sails/lib/app/index.js
>  @ ./node_modules/sails/lib/index.js
>  @ ./server.js
> 
> WARNING in ./node_modules/sails/lib/hooks/moduleloader/index.js 396:25-84
> Critical dependency: the request of a dependency is an expression
>  @ ./node_modules/sails/lib/hooks sync ^\.\/.*$
>  @ ./node_modules/sails/lib/app/configuration/index.js
>  @ ./node_modules/sails/lib/app/load.js
>  @ ./node_modules/sails/lib/app/Sails.js
>  @ ./node_modules/sails/lib/app/index.js
>  @ ./node_modules/sails/lib/index.js
>  @ ./server.js
> 
> WARNING in ./node_modules/sails/lib/hooks/moduleloader/index.js 279:31-47
> Critical dependency: the request of a dependency is an expression
>  @ ./node_modules/sails/lib/hooks sync ^\.\/.*$
>  @ ./node_modules/sails/lib/app/configuration/index.js
>  @ ./node_modules/sails/lib/app/load.js
>  @ ./node_modules/sails/lib/app/Sails.js
>  @ ./node_modules/sails/lib/app/index.js
>  @ ./node_modules/sails/lib/index.js
>  @ ./server.js
> 
> WARNING in ./node_modules/sails/lib/app/configuration/index.js 65:21-41
> Critical dependency: the request of a dependency is an expression
>  @ ./node_modules/sails/lib/app/load.js
>  @ ./node_modules/sails/lib/app/Sails.js
>  @ ./node_modules/sails/lib/app/index.js
>  @ ./node_modules/sails/lib/index.js
>  @ ./server.js
> 
> WARNING in ./node_modules/sails/lib/hooks/policies/README.md 1:0
> Module parse failed: Unexpected character '#' (1:0)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> > # Policies (Core Hook)
> | 
> | ## Status
>  @ ./node_modules/sails/lib/hooks sync ^\.\/.*$ ./policies/README.md
>  @ ./node_modules/sails/lib/app/configuration/index.js
>  @ ./node_modules/sails/lib/app/load.js
>  @ ./node_modules/sails/lib/app/Sails.js
>  @ ./node_modules/sails/lib/app/index.js
>  @ ./node_modules/sails/lib/index.js
>  @ ./server.js
> 
> WARNING in ./node_modules/sails/lib/hooks/pubsub/README.md 1:0
> Module parse failed: Unexpected character '#' (1:0)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> > # Pubsub (core hook)
> | 
> | See http://sailsjs.com/documentation/reference/web-sockets/resourceful-pub-sub for more info.
>  @ ./node_modules/sails/lib/hooks sync ^\.\/.*$ ./pubsub/README.md
>  @ ./node_modules/sails/lib/app/configuration/index.js
>  @ ./node_modules/sails/lib/app/load.js
>  @ ./node_modules/sails/lib/app/Sails.js
>  @ ./node_modules/sails/lib/app/index.js
>  @ ./node_modules/sails/lib/index.js
>  @ ./server.js
> 
> WARNING in ./node_modules/sails/lib/hooks/moduleloader/README.md 1:0
> Module parse failed: Unexpected character '#' (1:0)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> > # `moduleloader` (Core Hook)
> | 
> | This hook exposes `sails.modules`, a set of functions which other core hooks call to load modules from an app's configured directories in `sails.config.paths`.
>  @ ./node_modules/sails/lib/hooks sync ^\.\/.*$ ./moduleloader/README.md
>  @ ./node_modules/sails/lib/app/configuration/index.js
>  @ ./node_modules/sails/lib/app/load.js
>  @ ./node_modules/sails/lib/app/Sails.js
>  @ ./node_modules/sails/lib/app/index.js
>  @ ./node_modules/sails/lib/index.js
>  @ ./server.js
> 
> WARNING in ./node_modules/sails/lib/hooks/http/README.md 1:0
> Module parse failed: Unexpected character '#' (1:0)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> > # http (Core Hook)
> | 
> | ## Status
>  @ ./node_modules/sails/lib/hooks sync ^\.\/.*$ ./http/README.md
>  @ ./node_modules/sails/lib/app/configuration/index.js
>  @ ./node_modules/sails/lib/app/load.js
>  @ ./node_modules/sails/lib/app/Sails.js
>  @ ./node_modules/sails/lib/app/index.js
>  @ ./node_modules/sails/lib/index.js
>  @ ./server.js
> 
> WARNING in ./node_modules/sails/lib/hooks/logger/README.md 1:0
> Module parse failed: Unexpected character '#' (1:0)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> > # logger (Core Hook)
> | 
> | 
>  @ ./node_modules/sails/lib/hooks sync ^\.\/.*$ ./logger/README.md
>  @ ./node_modules/sails/lib/app/configuration/index.js
>  @ ./node_modules/sails/lib/app/load.js
>  @ ./node_modules/sails/lib/app/Sails.js
>  @ ./node_modules/sails/lib/app/index.js
>  @ ./node_modules/sails/lib/index.js
>  @ ./server.js
> 
> WARNING in ./node_modules/sails/lib/hooks/request/README.md 1:0
> Module parse failed: Unexpected character '#' (1:0)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> > # request (Core Hook)
> | 
> | > In future releases, the various responsibilities of this hook will likely be farmed out to other hooks and/or pulled into core.
>  @ ./node_modules/sails/lib/hooks sync ^\.\/.*$ ./request/README.md
>  @ ./node_modules/sails/lib/app/configuration/index.js
>  @ ./node_modules/sails/lib/app/load.js
>  @ ./node_modules/sails/lib/app/Sails.js
>  @ ./node_modules/sails/lib/app/index.js
>  @ ./node_modules/sails/lib/index.js
>  @ ./server.js
> 
> WARNING in ./node_modules/sails/lib/hooks/responses/README.md 1:0
> Module parse failed: Unexpected character '#' (1:0)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> > # responses (Core Hook)
> | 
> | ## Status
>  @ ./node_modules/sails/lib/hooks sync ^\.\/.*$ ./responses/README.md
>  @ ./node_modules/sails/lib/app/configuration/index.js
>  @ ./node_modules/sails/lib/app/load.js
>  @ ./node_modules/sails/lib/app/Sails.js
>  @ ./node_modules/sails/lib/app/index.js
>  @ ./node_modules/sails/lib/index.js
>  @ ./server.js
> 
> WARNING in ./node_modules/sails/lib/hooks/blueprints/README.md 1:0
> Module parse failed: Unexpected character '#' (1:0)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> > # sails-hook-blueprints
> | 
> | Implements support for the blueprint API in Sails.
>  @ ./node_modules/sails/lib/hooks sync ^\.\/.*$ ./blueprints/README.md
>  @ ./node_modules/sails/lib/app/configuration/index.js
>  @ ./node_modules/sails/lib/app/load.js
>  @ ./node_modules/sails/lib/app/Sails.js
>  @ ./node_modules/sails/lib/app/index.js
>  @ ./node_modules/sails/lib/index.js
>  @ ./server.js
> 
> WARNING in ./node_modules/sails/lib/hooks/security/README.md 1:0
> Module parse failed: Unexpected character '#' (1:0)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> > # security (Core Hook)
> | 
> | 
>  @ ./node_modules/sails/lib/hooks sync ^\.\/.*$ ./security/README.md
>  @ ./node_modules/sails/lib/app/configuration/index.js
>  @ ./node_modules/sails/lib/app/load.js
>  @ ./node_modules/sails/lib/app/Sails.js
>  @ ./node_modules/sails/lib/app/index.js
>  @ ./node_modules/sails/lib/index.js
>  @ ./server.js
> 
> WARNING in ./node_modules/sails/lib/hooks/session/README.md 1:0
> Module parse failed: Unexpected character '#' (1:0)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> > ## Session Hook
> | 
> | At configuration-time, this hook loads verifies valid configuration of the connect session store (configurable in `sails.config.session`),
>  @ ./node_modules/sails/lib/hooks sync ^\.\/.*$ ./session/README.md
>  @ ./node_modules/sails/lib/app/configuration/index.js
>  @ ./node_modules/sails/lib/app/load.js
>  @ ./node_modules/sails/lib/app/Sails.js
>  @ ./node_modules/sails/lib/app/index.js
>  @ ./node_modules/sails/lib/index.js
>  @ ./server.js
> 
> WARNING in ./node_modules/sails/lib/hooks/userconfig/README.md 1:0
> Module parse failed: Unexpected character '#' (1:0)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> > ## Userconfig Hook
> | 
> | This hook loads app-level user configuration using the moduleloader hook (from the config directory located at `sails.config.paths.config`) It is always loaded first.
>  @ ./node_modules/sails/lib/hooks sync ^\.\/.*$ ./userconfig/README.md
>  @ ./node_modules/sails/lib/app/configuration/index.js
>  @ ./node_modules/sails/lib/app/load.js
>  @ ./node_modules/sails/lib/app/Sails.js
>  @ ./node_modules/sails/lib/app/index.js
>  @ ./node_modules/sails/lib/index.js
>  @ ./server.js
> 
> WARNING in ./node_modules/sails/lib/hooks/userhooks/README.md 1:0
> Module parse failed: Unexpected character '#' (1:0)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> > ## Userhooks Hook
> | 
> | This hook loads hooks from the user hooks directory, configurable in `sails.config.paths.hooks` (defaults to `api/hooks`) of a sails app.  If the directory doesn't exist, this hook is a no-op.
>  @ ./node_modules/sails/lib/hooks sync ^\.\/.*$ ./userhooks/README.md
>  @ ./node_modules/sails/lib/app/configuration/index.js
>  @ ./node_modules/sails/lib/app/load.js
>  @ ./node_modules/sails/lib/app/Sails.js
>  @ ./node_modules/sails/lib/app/index.js
>  @ ./node_modules/sails/lib/index.js
>  @ ./server.js
> 
> WARNING in ./node_modules/sails/lib/hooks/README.md 1:0
> Module parse failed: Unexpected character '#' (1:0)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> > #Hooks
> | 
> | ## Status
>  @ ./node_modules/sails/lib/hooks sync ^\.\/.*$ ./README.md
>  @ ./node_modules/sails/lib/app/configuration/index.js
>  @ ./node_modules/sails/lib/app/load.js
>  @ ./node_modules/sails/lib/app/Sails.js
>  @ ./node_modules/sails/lib/app/index.js
>  @ ./node_modules/sails/lib/index.js
>  @ ./server.js
> 
> WARNING in ./node_modules/sails/lib/hooks/http/default-favicon.ico 1:0
> Module parse failed: Unexpected character '�' (1:0)
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> (Source code omitted for this binary file)
>  @ ./node_modules/sails/lib/hooks sync ^\.\/.*$ ./http/default-favicon.ico
>  @ ./node_modules/sails/lib/app/configuration/index.js
>  @ ./node_modules/sails/lib/app/load.js
>  @ ./node_modules/sails/lib/app/Sails.js
>  @ ./node_modules/sails/lib/app/index.js
>  @ ./node_modules/sails/lib/index.js
>  @ ./server.js
> 
> WARNING in configuration
> The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
> You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/
> 
> WARNING in ./node_modules/ejs/lib/ejs.js 831:2-20
> require.extensions is not supported by webpack. Use a loader instead.
>  @ ./node_modules/sails/lib/hooks/views/default-view-rendering-fn.js 8:10-24
>  @ ./node_modules/sails/lib/hooks sync ^\.\/.*$
>  @ ./node_modules/sails/lib/app/configuration/index.js
>  @ ./node_modules/sails/lib/app/load.js
>  @ ./node_modules/sails/lib/app/Sails.js
>  @ ./node_modules/sails/lib/app/index.js
>  @ ./node_modules/sails/lib/index.js
>  @ ./server.js
> 
> WARNING in ./node_modules/ejs/lib/ejs.js 830:4-22
> require.extensions is not supported by webpack. Use a loader instead.
>  @ ./node_modules/sails/lib/hooks/views/default-view-rendering-fn.js 8:10-24
>  @ ./node_modules/sails/lib/hooks sync ^\.\/.*$
>  @ ./node_modules/sails/lib/app/configuration/index.js
>  @ ./node_modules/sails/lib/app/load.js
>  @ ./node_modules/sails/lib/app/Sails.js
>  @ ./node_modules/sails/lib/app/index.js
>  @ ./node_modules/sails/lib/index.js
>  @ ./server.js
> 
> ERROR in ./node_modules/redis-parser/lib/hiredis.js
> Module not found: Error: Can't resolve 'hiredis' in 'D:\david\node_modules\redis-parser\lib'
>  @ ./node_modules/redis-parser/lib/hiredis.js 3:14-32
>  @ ./node_modules/redis-parser/lib/parser.js
>  @ ./node_modules/redis-parser/index.js
>  @ ./node_modules/redis/index.js
>  @ ./node_modules/machinepack-redis/index.js
>  @ ./node_modules/sails/lib/hooks/session/index.js
>  @ ./node_modules/sails/lib/hooks sync ^\.\/.*$
>  @ ./node_modules/sails/lib/app/configuration/index.js
>  @ ./node_modules/sails/lib/app/load.js
>  @ ./node_modules/sails/lib/app/Sails.js
>  @ ./node_modules/sails/lib/app/index.js
>  @ ./node_modules/sails/lib/index.js
>  @ ./server.js
> 
> ERROR in express.min.js from Terser
> Invalid assignment [express.min.js:190498,21]

_

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
