### ISSUE TITLE
webpack how to ignore folder for watch

### ISSUE THREAD

**Issue by novaknole** [webpack/webpack#10582]
# Bug report

I also posted the question on stackoverflow, but with no luck for answers. I'd really appreciate if you don't close it and take a look at this.

**What is the current behavior?**

Somewhere in my app, I have a function which uses dynamic require.

```
export default function(path, urlKey = 'static') {

    if (urlKey === 'static') {
        path = require(`~/static${path}`).default;
    }

    urlKey = Object.keys(config.app.urls).includes(urlKey) ? urlKey : 'static';

    return (config.app.urls[urlKey] + '/' + path).replace(/([^:]\/)\/+/g, "$1");

};
```

As you can see, I am using `dynamic require` . It's something like `require.context`. What happens is, while webpack bundling it, it builds all the files in the static folder. As you can see I have ~ which is an alias for the root directory in which i have a static folder.

Now, when using watch mode of webpack, what happens is it never stops building, when it builds the project, it starts it again and again as a loop. Unfortunatelly, I couldn't ignore static folder at all by using watchOptions.ignored or WatchIgnorePlugin.

Here is what I tried:

```
watchOptions: {
  ignored: /static/
}
```

And also

```
plugins:[
        new WatchIgnorePlugin([
            path.resolve(__dirname, '..', 'static')
        ]),
    ]
```

but with no luck. It still rebuilds infinitely when in watch mode.

The way this starts working(I mean it doesn't compile over and over again is) is by changing require statement 

from : `path = require(`~/static${path}`).default;`

to : `path = require(`~/static/${path}`).default;` (look at one slash addition before ${path})

This solves it, but in my whole app, I use this function in too many places where I pass path that start with / so, I had to also change it to `path = require(`~/static/${path.substring(1)}`).default;`

**What is the expected behavior?**

It  shouldn't rebuild the project infinitelly. 

**Other relevant information:**
webpack version:  4.41.5
Node.js version:  12.14.1
Operating System:  MacOS
Additional tools:

**Comment by evilebottnawi** [comment]
Please use `stackoverflow` or `gitter` for questions, it is bug tracker, thanks
