### ISSUE TITLE
Multiple build support

### ISSUE THREAD

**Issue by divmain** [webpack/webpack#1059]
Thought I'd move the discussion here.  I had a couple of unanswered questions wrt how to move forward with this.  Copied from my last comment [here](https://github.com/webpack/webpack/pull/1017).

------------------------

The workflow you describe is _exactly_ what I had in mind.  My first attempt, in fact, was a plugin along these lines - emitting manifest with generated JS, ingesting dependency manifests and re-using generated chunks where available, using `[chunkhash].js` for library output filename, relying on require-dependency resolution to identify chunks made available by `npm install`ed modules, etc.

It is good to know you think this is a reasonable direction, also.

[...]

Two questions that come to mind:

1. How do you suggest sharing module instances between components?  Each entry point will retain its own `installedModules`.  However, with something like jQuery for example, you'd expect a config change to be made globally and shared across the browser context.

2. By default, chunk hashmaps are generated by `asset-path` plugins and inlined in the entry points.  The lookup itself occurs if the `installedChunks[chunkId]` is `undefined`.  How do you suggest overriding this behavior such that, if a chunk has been loaded in a `script` tag by a separate entry point it won't be loaded again?  It seems that altering this behavior would require significant changes to `require-ensure` template.

**Comment by baer** [comment]
I'm super interested in this as well.

**Comment by sokra** [comment]
see PR
