### ISSUE TITLE
Source maps namespace does not replace output library [name] with the entrypoint name

### ISSUE THREAD

**Issue by FinestV** [webpack/webpack#10595]
# Bug report

**What is the current behavior?**
When using `devtool: source-map` with `library: [name]` all generated source maps will generate sources paths with the namespace [name] eg. `webpack://[name]/./src/components/button.tsx`. This means all source maps have the same namespace - [name]

**If the current behavior is a bug, please provide the steps to reproduce.**
Set `devtool: source-map` and output `library: [name]`

See minimal reproduction here
https://github.com/FinestV/WebpackSourceMapNamespaceRepro

**What is the expected behavior?**
Expect that source map namespaces containing [name] will be replaced by the entry point name.

**Other relevant information:**
webpack version:  4.42.0
Node.js version: 12.13.1
Operating System: Windows 10
Additional tools:

**Comment by evilebottnawi** [comment]
@FinestV sorry for delay, why do you expected this? `[name]` is `file` (chunk) name, not an entry point name, but in some cases it can be same
