### ISSUE TITLE
Webpack guides

### ISSUE THREAD

**Issue by dibate48** [webpack/webpack#10590]
Hi  to all 
I am requesting anyone that has followed the guides more specifically "getting started", and got Webpack to work following their procedure to send me a template, i literally installed and reinstalled packages and their procedure keeps failing.

regards
Dibate

**Comment by snitin315** [comment]
@dibate48 , I have followed the guide and everything works perfectly. His guide is the best source to learn webpack.

**Comment by dibate48** [comment]
Thanks for your response, i will keep trying, may i should remove the lodash functionality from the index.js as it seems to me i likely to unsupported in the versions i am in.
The suggested npx wepack works fine:
![image](https://user-images.githubusercontent.com/45804214/77228401-d8cc8980-6b8f-11ea-97e4-d68f845fa8bb.png 
but npx webpack --config webpack.config.js fails, my understanding is that the config file remains supported. i will send the output in a jiffy

**Comment by dibate48** [comment]
![Uploading image.png…]()
