### ISSUE TITLE
splitChunks causes .wasm imports in symlinked node_modules dependencies to fail

### ISSUE THREAD

**Issue by adroitwhiz** [webpack/webpack#10593]
# Bug report

**What is the current behavior?**

When the following conditions are met:
- `splitChunks` is enabled
- A symlinked dependency *in `node_modules`* imports a .wasm file with async/dynamic `import()`
- `resolve.symlinks` is `false`
- The .js file that imports the .wasm file is large enough that Webpack considers splitting it (I think)

`.wasm` files are not output as chunks, and the `// Fetch + compile chunk loading for webassembly` section of the code is not generated.

**If the current behavior is a bug, please provide the steps to reproduce.**

See [this repository](https://github.com/adroitwhiz/webpack-wasm-bug). `demo.sh` will set up the symlinked dependency and build using Webpack. This was only tested on Linux.

**What is the expected behavior?**

WebAssembly chunks should be present in the output and loaded.

**Other relevant information:**
webpack version:  4.42.0
Node.js version: v10.17.0 and v13.3.0
Operating System: Fedora Linux
Additional tools: N/A

**Comment by adroitwhiz** [comment]
AFAIK this is still an issue

**Comment by alexander-akait** [comment]
Fixed in webpack@5, just note you need to change `name` for `splitChunks` and `runtimeChunk` because it is conflict, look at the error message
