### ISSUE TITLE
Allow hashDigestLength to be used by other loaders

### ISSUE THREAD

**Issue by rightaway** [webpack/webpack#10603]
## Feature request

**What is the expected behavior?**
Every loader that uses `[hash]` needs to use `[hash:10]` to be consistent if webpack's options were set as `output: { hashDigestLength: 10 } }`. It would be better if loaders were able to use the same value by default if they choose to.

**What is motivation or use case for adding/changing the behavior?**
`hashDigestLength` should be able to be used by `[hash]` in file-loader and other loaders if they choose to, so that `[hash]` would by default have a length of `10`.

**How should this be implemented in your opinion?**
In https://github.com/webpack/loader-utils/issues/121#issuecomment-602487372 it says that the issue should be solved on the webpack side. There was also an issue in `file-loader` project which said it can't be solved there.

**Are you willing to work on this yourself?**

**Comment by evilebottnawi** [comment]
@rightaway Please read my answer in the issue, we already have an issue for providing some output options for loaders

**Comment by rightaway** [comment]
> we already have an issue for providing some output options for loaders

Sorry I didn't see that issue you're referring to. It's not linked from https://github.com/webpack/loader-utils/issues/121. Could you please link that issue here so I can follow the correct one?
