### ISSUE TITLE
Environment variable interpreted as floating point number

### ISSUE THREAD

**Issue by Gearshxft** [webpack/webpack#10609]
# Bug report

**What is the current behavior?**

There seems to be no way of forcing environment variables to be treated as a string. For example, our build pipeline automatically passes the git commit hash as an environment variable:

`yarn webpack --env.hash="838132e2"`

The webpack.config file would interpret this as a floating point number: 83813200

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

We need a way to always treat this as a string, so the webpack config file should receive "838132e2".

**Other relevant information:**
webpack version:  4.42.1
Node.js version: 12.13.0
Operating System: macOS Catalina
Additional tools:

**Comment by evilebottnawi** [comment]
Not related to webpack, using `webpack` you use `webpack-cli`, also `webpack-cli` doesn't support `env` arguments, you can you environments variables for that, for example `GIT_HAS=1231231 webpack` and use Define plugin to pass that value to your code

**Comment by Gearshxft** [comment]
@evilebottnawi https://webpack.js.org/api/cli/#environment-options
