### ISSUE TITLE
disable minification for child compilers

### ISSUE THREAD

**Issue by jantimon** [webpack/webpack#10604]
In order to optimize the compilation time for the html-webpack-plugin I would like to opt out from terser during the template compilation.

The minification would not help here as the generated code will not be saved to disked but is run directly.  However it takes time for terser to minify and this time can be saved.

So basically I am looking for something like the following which can be set when create a child compiler:

```js
module.exports = {
  //...
  optimization: {
    minimize: false
  }
};
```

**Comment by sokra** [comment]
I think it makes sense to add this kind of info to the asset info data as flag. The terser plugin could skip asset flagged this way.

**Comment by evilebottnawi** [comment]
@sokra I think terser plugin should migrate on `thisCompilation`

**Comment by sokra** [comment]
Hmm maybe not. What's about worker-loader or other plugins that create webworkers. They want their worker code, which is build in a child compilation, to be optimized. Less relevant if they emit a worker as file, but at least worker-loader can also create a worker as data URL.

I would go with a `skipOptimization` flag...

**Comment by evilebottnawi** [comment]
@sokra But files from childCompilers copied to `assets`, so we don't need to run minification on child compilers

**Comment by sokra** [comment]
If they are copied yes, but e. g. worker-loader can also inline the worker code as data uri or blob. That code would be not optimized in this case.

**Comment by sokra** [comment]
And we should set `skipOptimization` on assets from children so they are not mininized twice...

**Comment by evilebottnawi** [comment]
@sokra 

> If they are copied yes, but e. g. worker-loader can also inline the worker code as data uri or blob. That code would be not optimized in this case.

Good catch, I will think about it

**Comment by evilebottnawi** [comment]
Fixed on `terser-webpack-plugin`, we skip already optimized assets from child compilation, without any new options

**Comment by evilebottnawi** [comment]
@jantimon Do you search this?

**Comment by mbrevda** [comment]
> Fixed on `terser-webpack-plugin`, we skip already optimized assets from child compilation, without any new options

In which version?

**Comment by evilebottnawi** [comment]
@mbrevda https://github.com/webpack-contrib/terser-webpack-plugin/releases/tag/v3.1.0

**Comment by jantimon** [comment]
Wow that's cool 👍

Does that mean child compiler compilation will never be optimised?

**Comment by evilebottnawi** [comment]
@jantimon `terser` minimize child assets, but skip them in main compilation (no double minimizing)

**Comment by jantimon** [comment]
I don't need any minification at all as I will not output the asset.  
Is there any way how I can tell terser to ignore a child compiler entirely for faster builds?

**Comment by evilebottnawi** [comment]
@jantimon Why you need it, I can't understand, if you don't have `js` files, terser will now work, minimizers should always work on child compilations, otherwise a lot of assets will no be optimized

**Comment by jantimon** [comment]
If you use a webpack loader together with a template file this will generate a `js` under the hood.  
Before the emit is happening we remove it from the output and instead execute it directly to generate the html.

It's similar for the favicon generation.

Terser would here minify a file which will only be used internally and therefore slow down the html generation and make it harder to read the stack traces.

**Comment by evilebottnawi** [comment]
You should not use `delete`, we have `deleteAsset` for webpack@5, otherwise it does not delete assets by other plugins, for example - `compression-webpack-plugin`, but I understand what do you mean, as workaround you can add `minimized: true` to asset info and terser skip minification for this assets

**Comment by jantimon** [comment]
Thanks for the heads up on `deleteAsset` 👍

Can you give an example where I would need to place `minimized: true` in https://github.com/jantimon/html-webpack-plugin/blob/17653730164688703ad46ce25ed356c52e79c43f/lib/child-compiler.js ?

**Comment by evilebottnawi** [comment]
@jantimon I will send a PR in near future, bit busy right now

**Comment by jantimon** [comment]
Cool thanks 👍  
Let me know if I can help you there.

**Comment by PratishShrivastava** [comment]
Can I work on this issue.

**Comment by LukasBombach** [comment]
@jantimon @alexander-akait is it possible to turn on optimization / minification for child compilers now? I can't find anything related in the source of `html-webpack-plugin` nor in other projects using a `childCompiler`

**Comment by alexander-akait** [comment]
No, it is impossible, but it runs only for production
