### ISSUE TITLE
How to generate or inject source code during webpack processing / bundling?

### ISSUE THREAD

**Issue by watery** [webpack/webpack#10600]
I've already tried [asking on StackOverflow](https://stackoverflow.com/q/60721730/3127111) and [on Gitter too](https://gitter.im/webpack/webpack?at=5e7619d11d73bb22eb966e47) with no luck, so I hope here I'll gather some info.

I want to generate a whole new module within my project, based on some other modules (the specific use case is generating a menu (React) component based on modules within a directory): is that possible and how can I do it?

I'm reading through the plugins docs, but before I do any attempt with that I'd like to at least know if what I want to do is feasible at all; then, some pointers or example code would be of great help :upside_down_face:

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Please wait answer on stackoverflow

Also please clarify what do you want, the question is not clear

**Comment by watery** [comment]
@evilebottnawi, I'd like to point out that following [New Issue] -> [Other] there's no issue template that I deleted, except a series of comments:

```
<!-- Bug reports and Feature requests must use other templates, or will be closed -->
<!-- Please ask questions on StackOverflow or the webpack Gitter (https://gitter.im/webpack/webpack). -->
<!-- Issues which contain questions or support requests will be closed. -->
```

Beside that, here's a quick example.

Given a project only made of the following two source files (almost pseudocode):

* `index.js`
  > ```
  > import greeting from "./greeting";
  >
  > console.log(greeting("World"));
  > ```
* `message.js`
  > ```
  > export default message = "Hello";
  > ```

At some step (i.e. after `message.js` has been compiled) I want to generate a module named `greeting` with the following code:

```
import message from "./message";

export default greeting = function(name) { return message + " " + name }
```

so that the static `import` in `index.js` is satisfied when the latter is compiled.

**Comment by evilebottnawi** [comment]
@watery Please read https://webpack.js.org/guides/author-libraries/

**Comment by watery** [comment]
@evilebottnawi Thanks.

I'm read that page but I'm not sure to understand why you pointed me there: I don't need to consume any third-party library or package nor I am trying to put together a library or package for others to use.

I'm talking about generating a whole new source file on-the-fly during webpack processing, all within the same project.
