### ISSUE TITLE
bug(config): can't use optimization.moduleId = 'deterministic'

### ISSUE THREAD

**Issue by snitin315** [webpack/webpack#10614]
# Bug report

**What is the current behavior?**

```
module.exports = {
  //...
  optimization: {
    moduleIds: 'deterministic'
  }
};
```

The above config throws the following error -

![Screenshot from 2020-03-26 20-17-43](https://user-images.githubusercontent.com/46647141/77661242-61886280-6fa0-11ea-8c55-46e4aadcd3fa.png)

### **But according to [WebpackOptions.json#L1162](https://github.com/webpack/webpack/blob/bdd5ec85a9058391fb1f5960f80a4878f90b79ed/schemas/WebpackOptions.json#L1162) it is still supported.**

**If the current behavior is a bug, please provide the steps to reproduce.**

Run webpack with the above configuration.

**What is the expected behavior?**

If this value has been removed it should be removed from [WebpackOptions.json#L1162](https://github.com/webpack/webpack/blob/bdd5ec85a9058391fb1f5960f80a4878f90b79ed/schemas/WebpackOptions.json#L1162) as well.

**Other relevant information:**
webpack version:  4.42.0
Node.js version: 12.14.1
Operating System: Kali Linux
Additional tools:

**Addition Info**

I would like to help with this issue.

**Comment by evilebottnawi** [comment]
Because it is implemented only for webpack@5

**Comment by snitin315** [comment]
So we have to mention in docs it's for webpack@5.
