### ISSUE TITLE
./src/index.js Cannot find file: 'Hello.js' does not match the corresponding name on disk: '.\src\hello.js'.

### ISSUE THREAD

**Issue by harshrocker** [webpack/webpack#10617]
# Bug report

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

**Comment by harshrocker** [comment]
what can i do plz guide me to solve it...

**Comment by harshrocker** [comment]
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import Hello from './Hello';
import * as serviceWorker from './serviceWorker';

ReactDOM.render(
  <React.StrictMode>
    <Hello />
  </React.StrictMode>,
  document.getElementById('root')
);

// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: https://bit.ly/CRA-PWA
serviceWorker.unregister();

**Comment by harshrocker** [comment]
import React from 'React';
import ReactDom from 'react-dom';

class extends Hello React.component{
	render(){
		return(
			<div>
			<h1>Welcome Coderworld!</h1>
			</div>
			)
	}
}

export default Hello;

**Comment by shreyashpandey** [comment]
Have you created hello.js file in your React app src folder

**Comment by Mistyyyy** [comment]
You should keep the `import hello from './Hello'` reference and `Hello.js` filename consistent.

**Comment by sokra** [comment]
Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md).
