### ISSUE TITLE
How can I put assets url inside production build

### ISSUE THREAD

**Issue by krishnaTORQUE** [webpack/webpack#10625]
How can I put assets url inside production build ?

Like bundle.js >> assets.com/bundle.js

**Comment by sokra** [comment]
Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md).
