### ISSUE TITLE
Webpack resolve modules not following precedence 

### ISSUE THREAD

**Issue by orpheus** [webpack/webpack#10626]
I am using the webpack resolve pattern

` modules: [path.resolve('node_modules'), 'node_modules'].concat(/* ... */)`

for use w symlinked modules as found in this issue https://github.com/facebook/create-react-app/issues/6027

and it works except that I have a dependency `ol` in my `node_modules` which also has a nested node_modules with a few dependencies.. it comes out looking like:

```
┬ ol@5.3.3
│ ├─┬ pbf@3.1.0
│ │ ├── ieee754@1.1.13
│ │ └─┬ resolve-protobuf-schema@2.1.0
│ │   └── protocol-buffers-schema@3.4.0
│ ├── pixelworks@1.1.0
│ └─┬ rbush@2.0.2
│   └── quickselect@1.1.1
```
With `rbush` and `quickselect` being the culprits.

Resolving to my local node modules with the absolute path allows my symlinked module to use the same react, react-redux, etc, but then when the app loads, it eventually tries to use the `rbush` module, it doesn't resolve properly and tries to call a function of undefined.

I can fix the issue by adding an alias: (if I just do it for rbush, an error throws from quickselect, and when both are added, the app works)
```
alias: {
  rbush: path.resolve('node_modules/ol/node_modules/rbush'),
  quickselect: path.resolve('node_modules/ol/node_modules/quickselect')
},
```

I'd rather not have to alias each nested node_module.

webpack docs say to add a path to your `resolve.modules`:

> If you want to add a directory to search in that takes precedence over node_modules/:

And so I want my local node modules to take precedence: `(path.resolve('node_modules')`

But when the app cannot find `rbush` or `quickselect` at the top level, it should then search the next entry which is the `node_modules` relative path (as it does for default), which is the lower precedence, but it seems to stop searching after it didn't find it at the top level

**Comment by sokra** [comment]
This works as expected. `node_modules/rbush` takes precedence over `node_modules/ol/node_mdoules/rbush` as you specified it in `resolve.modules`.

``` js
modules: [path.resolve('node_modules'), 'node_modules']
```

This is a bad config regarding correctly resolving modules correctly in your own node_modules.

Try this instead:

``` js
resolve: {
  modules: ["node_modules"], // or the default
  alias: {
    react: require.resolve("react"),
    "react-dom": require.resolve("react-dom")
  }
}
```

to only change the resolving of the singleton modules.

---

Alternatively you can also only change the resolve config for external modules:

``` js
module.rules: [
  {
    exclude: path.resolve("node_modules"),
    resolve: { modules: [path.resolve('node_modules'), 'node_modules'] }
  }
]
```

**Comment by orpheus** [comment]
Ah ok, I see what I did. Not completely sure what the later code does (tried and didn't work), but I'll opt for resolving singleton modules, thank you.
