### ISSUE TITLE
Got "TypeError: Cannot read property 'call' of undefined" while using TerserPlugin and set mangle.properties to true.

### ISSUE THREAD

**Issue by LvChengbin** [webpack/webpack#10633]
# Bug report

**What is the current behavior?**

Got error message "TypeError: Cannot read property 'call' of undefined" if I set the `mangle.properties` to `true` in `terser-webpack-plugin`'s options.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  4.42.1
Node.js version: v13.5.0
Operating System: MacOS
Additional tools: terser-webpack-plugin@2.3.5

**Comment by sokra** [comment]
This is not related to webpack, but terser instead. Probably a problem in your codebase. Nobody can help you with this without a minimal reproduction case.
