### ISSUE TITLE
Every second build throws `Error: ENOENT`

### ISSUE THREAD

**Issue by alexfedoseev** [webpack/webpack#1063]
I have an issue with every second build in a row.

First build runs fine, but next build falls with error:

```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: ENOENT, lstat '/path/to/app/public/assets/app-3028cce106c7de81a595.js'
    at Error (native)
```

Next build is ok. And so on.

Running it with gulp.
Here is [my webpack config](https://github.com/alexfedoseev/generator-react-on-rails/blob/master/app/templates/app/build/webpack.config.js).
And [gulpfile](https://github.com/alexfedoseev/generator-react-on-rails/blob/master/app/templates/app/gulpfile.js).

```
webpack v1.9.5
node    v0.12.2
npm     v2.9.1
```

**Comment by sokra** [comment]
Chould you vertify if it relate to webpack or to the gulp stuff? Try to run only the build with webpack CLI.

**Comment by alexfedoseev** [comment]
With CLI it runs fine.

**Comment by alexfedoseev** [comment]
Fixed here: https://github.com/adametry/gulp-eslint/issues/36
