### ISSUE TITLE
Webpack is escaping `?` inside the filename

### ISSUE THREAD

**Issue by jantimon** [webpack/webpack#10638]
# Bug report

**What is the current behavior?**

I got multiple error reports (#1367, #1346, #1355, #1374) that the `html-webpack-plugin` 4.x does not support querystrings in filename although `html-webpack-plugin` 3.2 did.

People use the filename to append a querystring to a file:

```
output: {
  filename: 'assets/name.js?whatever'
},
plugins: [
  new MiniCssExtractPlugin({
    filename: 'assets/name.css?whatever'
  }),
]
```

webpack is correctly removing the querystring before it writes files to disk however it is also encaping `?` to `%3F`.

would it be possible to not do this replacement for `compilation.entrypoints.get(entryName).getFiles()`?

**Other relevant information:**
webpack version:  4.42.1
Additional tools: html-webpack-plugin: 4.0.3

**Comment by sokra** [comment]
Is this only related to the mini-css-extract-plugin?

cc @evilebottnawi

**Comment by jantimon** [comment]
I created a code sandbox to fiddle with the problem here:

https://codesandbox.io/s/html-webpack-plugin--querystring-dgl7k

**Comment by jantimon** [comment]
According to @gracexiong who tried to integrate https://github.com/jantimon/html-webpack-plugin/issues/1355#issuecomment-596566980 it was based of the escaping but I can't reproduce that issue - I'll need to take a further look.

It seems like webpack is doing the correct thing here:

```
compilation.entrypoints.get("main").getFiles() 
// ['assets/name.css?whatever', 'assets/name.js?whatever']
```

**Comment by jantimon** [comment]
Hey @sokra after further looking into it it looks like webpack is working absolutely correct here - sorry for the mess :(
