### ISSUE TITLE
Using webpack to build neo.mjs (a webworkers driven ui framework)

### ISSUE THREAD

**Issue by tobiu** [webpack/webpack#10630]
## Feature request

**What is the expected behavior?**
it would be appreaciated if webpack was able to build in a worker based env.

**What is motivation or use case for adding/changing the behavior?**
right now, setting target to web will break terribly, since there are hard coded uses of window (has to be _self in the worker context). now, when switching to target: node it does work as long as you don't use dynamic imports. as soon as you do webpack will add require() calls which break inside a browser env for obvious reasons.

**How should this be implemented in your opinion?**
replacing window with _self might already help

**Are you willing to work on this yourself?**
no, my area of expertise is strongly ui related

the neo.mjs framework is using the MIT license and slowly gaining traction. you can see the setup i am trying to use for webpack inside the buildScripts folder:

https://github.com/neomjs/neo

**Comment by sokra** [comment]
Have you tried `target: "webworker"`?

**Comment by tobiu** [comment]
Hi Tobias,

thanks for the heads up, I was not aware that this target exists.

Right now my build combines the main thread & workers, will need to separate the logic to give it a shot.

Might take 1-2 days (still in those cvid hackathons). Will let you know how it works.

Best regards
Tobias

**Comment by tobiu** [comment]
Hi again,

finally found time to get started and it feels non-trivial for sure.

https://github.com/neomjs/neo/projects/11

I was able to isolate the main thread build for dev & prod and switched this one to target web.

Using dynamic imports, Webpack does create the new chunks, but by default was not able to import them => wrong references.

Tried this one at first:
```
if (window.__webpack_public_path__) {
    __webpack_public_path__ = '../../';
}
```
Note: there has to be a window. check or it will break when running the file without webpack directly. The public path only(!!) worked in the development env and completely got ignored for production.

Switched to something like:
```
    output: {
        chunkFilename: '[name].js', // would default to '[id].js': src/main/lib/AmCharts => 1.js

        filename: (chunkData) => {
            if (chunkData.chunk.name === 'main') {
                return config.mainOutput;
            }
        },

        path      : path.resolve(processRoot, config.buildFolder),
        publicPath: '../../'
    }
```

Note2: 
> import(/* webpackChunkName: 'src/main/lib/AmCharts' */ './main/lib/AmCharts.mjs');
This one will use the given chunk name in mode: 'development', not in prod. Using chunkFilename in prod does fix it.

Note3:
publicPath seems to work fine for now, webpack is looking for files to import on the index file level instead of using the main imported chunk as the base line. I am not sure if this will work for the app thread env where the relative file / folder depth can vary.

Minor issue with HtmlWebpackPlugin:
Main chunk unknown: https://github.com/neomjs/neo/issues/523

The real deal will be to get split chunk optimisations in there. We might need to separate the data & vdom workers into own scripts too, since those imports live in different realms. Not sure yet how this will work out with import references (publicPath) or multiple apps to lazy load like how it works inside the docs app UI without webpack.

Will keep you posted, we can create sub-tickets.

**Comment by evilebottnawi** [comment]
@tobiu sorry for delay problem still exists?

**Comment by tobiu** [comment]
I was not able yet to figure out a solution. To be fair, I had no time to dive into it.

Still on my todo list.

**Comment by evilebottnawi** [comment]
@tobiu maybe you can create simple example and I will help you?

**Comment by tobiu** [comment]
ha, i got confused with ticket numbers :)

The one where I do need help is that one:
https://github.com/webpack/webpack/issues/11049

For this ticket, my overrides do work fine. Would be nice to see them as webpack configs, but low prio. Feel free to close it.

**Comment by evilebottnawi** [comment]
> For this ticket, my overrides do work fine. Would be nice to see them as webpack configs, but low prio. Feel free to close it.

Do you mean `__webpack_public_path__` overrides? 

So problems with publicPath only? Maybe it helps https://github.com/webpack/webpack/issues/11127?
