### ISSUE TITLE
Wrap imported function calls in inlinable identity function

### ISSUE THREAD

**Issue by fabiosantoscode** [webpack/webpack#10635]
## Feature request

In #5600 @sokra talks about why Webpack generates `Object()` wrappers around calls of imported functions (it's to remove the `this` binding), and why `(0, module.fn)()` is not used instead. It does make sense, however in general I'm concerned about how small JavaScript code is, and https://github.com/terser/terser/issues/620 was opened in Terser which brought this to my attention.

**What is the expected behavior?**
I'm proposing that webpack wraps these calls in an identity function call (the function itself might need to be marked with `/*#__INLINE__*/`, but not all call sites), so that Terser can inline it and turn it into `(0, module.fn)()` form. Terser currently can't pull this off, but after an issue is fixed it should work.

**What is motivation or use case for adding/changing the behavior?**
To make output JavaScript smaller. Terser doesn't know that `Object` is an unchanged global, and it doesn't know that the imported function is a function (it looks like a regular property access).

**How should this be implemented in your opinion?**
An identity function should be created at the top of the bundle (or at the top of every module) with an `/*#__INLINE__*/` comment. Then, functions imported from modules can be wrapped in a call of this identity function, instead of Object.

**Are you willing to work on this yourself?**
yes

**Comment by sokra** [comment]
webpack 5 uses `(0, module.fn)()` instead, so this shouldn't be an issue any longer.

**Comment by fabiosantoscode** [comment]
My bad. Thanks!
