### ISSUE TITLE
I need a feature, look like this

### ISSUE THREAD

**Issue by spiritfox358** [webpack/webpack#10644]
## Feature request

**What is the expected behavior?**
i hope have feature that script tag add attribute

**What is motivation or use case for adding/changing the behavior?**

Loss of function

**How should this be implemented in your opinion?**

<script 
  type=”text/javascript” 
  src=”/build/bundle.js” 
  charset=”utf-8">
</script>

should add this code   `charset=”utf-8"`

**Are you willing to work on this yourself?**
I can't do that

**Comment by chenxsan** [comment]
webpack does not generate `script` tags, you are on your own to add `charset` attribute when you need. If you are using html-webpack-plugin or create-react-app, etc. to generate html files, then better ask on their repositories for feature request.

**Comment by sokra** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script

> ## Deprecated attributes
> ### charset 
> If present, its value must be an ASCII case-insensitive match for "utf-8". It’s unnecessary to specify the charset attribute, because documents must use UTF-8, and the script element inherits its character encoding from the document.

For dynamically inject script tags webpack already sets `utf-8`, even if not needed.

If you want to affect the generated HTML see html generation plugin
