### ISSUE TITLE
'invalid' event triggered shortly after first 'done'

### ISSUE THREAD

**Issue by markfinger** [webpack/webpack#1064]
Hi,

I'm hooking in to the plugin system as part of a wrapper and I've noticed that when first watching the following cascade of events occurs

- **start**
- `done`
- `invalid`
- `done`

When a file change occurs, it is as expected

- **file change occurs**
- `invalid`
- `done`

Once it's up and running, everything seems to be fine. But the initial `done` always seems to be be followed by an `invalid` event which, I assume, triggers the bundle to be rebuilt again.

The whole thing's started with something like the following

```javascript
// Create a compiler
var compiler = webpack({...});

// hook in to the compiler
compiler.plugin('done', function(){...});
compiler.plugin('invalid', function(){...});
compiler.plugin('failed', function(){...});

// start the watcher
compiler.watch(200, function() {/* no-op */});
```

I've been keeping pace with webpack's releases for the last ~6 months and all have exhibited this. Should this be considered expected behaviour?

**Comment by markfinger** [comment]
Seems to only happen in unit tests. For context, the dependencies are being generated milliseconds before the compilation starts, so I assume this probably has to do with watchpack having an offset when reading mtimes

**Comment by sokra** [comment]
Caused by the watcher, because of filesystem accurency...

**Comment by markfinger** [comment]
Ah yeah, of course. I hit that accuracy issue the other day.

Thanks for the heads up, @sokra
