### ISSUE TITLE
Add a dry mode to webpack to simulate a build without producing the output

### ISSUE THREAD

**Issue by paztis** [webpack/webpack#10651]
## Feature request

**What is the expected behavior?**
If I dont pass `output` in the config or no `filename`, a default one is created (dist/[name].js)
At the end a file is always created

**What is motivation or use case for adding/changing the behavior?**
I need to simulate a webpack build on my modules to verify build well completes
But I can't found a way to disable the output.

**How should this be implemented in your opinion?**
I'd like to have a **dry mode** option to do this, or to found the good configuration / plugin for it.
Webpack-dev-server well create in memory build. A way yo do this may exist.

**Are you willing to work on this yourself?**
yes

**Comment by evilebottnawi** [comment]
You can create a plugin for it, here an example of code https://github.com/webpack/webpack-dev-middleware/blob/master/src/utils/setupOutputFileSystem.js, I don’t think we need this in cory, anyway thanks for the issue
