### ISSUE TITLE
Async External with AMD

### ISSUE THREAD

**Issue by gingur** [webpack/webpack#10650]
# Bug report

**What is the current behavior?**
Using AMD libraryTarget, when the source specifies an async external, the external is referenced as a dependency in the `define` statement.

```js
// source
import('lodash').then(lodash => console.log(lodash));

// output
define(['lodash'], lodash => {
  Promise.resolve().then(__webpack_require__.t.bind(null, 1, 7)).then(lodash => console.log(lodash));
});
```

**If the current behavior is a bug, please provide the steps to reproduce.**
https://repl.it/@gingur/webpack-amd-async-external

**What is the expected behavior?**
Modeled on how rollup handles this, it adds "require" as a dependency to load the external asynchronously. This could also use the global "require" if preferred, so long as "lodash" is not in the initial dependency array since that would *always* load the dependency instead of it getting fetched *optionally* when needed.
```js
// source
import('lodash').then(lodash => console.log(lodash));

// output
define(['require'], require => {
 new Promise((resolve, reject) => require(['lodash'], resolve, reject)).then(lodash => console.log(lodash));
});
```

**Other relevant information:**
webpack version: 4.42.1 && 5.0.0-beta.13
Node.js version: 10 && 12 tested
Operating System: any

**Comment by evilebottnawi** [comment]
bump
