### ISSUE TITLE
Displayed units should have a space between the quantity and the unit symbol

### ISSUE THREAD

**Issue by getsnoopy** [webpack/webpack#10656]
# Bug report

**What is the current behavior?**
When webpack compilation is done, it prints (or returns) a string with the time it took to run in the format `Time: <x>ms`, where `<x>` is the number of milliseconds.

**If the current behavior is a bug, please provide the steps to reproduce.**
Just run any webpack-cli command or a webpack API compilation, and examine the stats output.

**What is the expected behavior?**
The output should be `Time: <x> ms`, with a space between `<x>`, the number of milliseconds, and the unit symbol `ms` as per [SI rules](https://www.bipm.org/utils/common/pdf/si-brochure/SI-Brochure-9-EN.pdf#page=35).

**Other relevant information:**
webpack version:  4.42.1, 5.0.0-beta.14
Node.js version: 13.5.0
Operating System: Linux (elementary OS 5.1.2 Hera)
Additional tools:

**Comment by evilebottnawi** [comment]
Please put feedback on current output here https://github.com/webpack/webpack/issues/10534, we want improve it in the future, thanks
