### ISSUE TITLE
Flood-require

### ISSUE THREAD

**Issue by IngwiePhoenix** [webpack/webpack#1065]
I have a little loader for my project that processes `*.soundpack.json` files. They look like this:

```json
{
    "name": "My theme",
    "msg_recv": "msg_recv.wav",
    "msg_send": "msg_send.wav",
    "msg_notice": "msg_notice.wav",
    "msg_bot": "msg_bot.wav"
}
```

My loader resolves the files in this listing to files in the folder and converts all `.wav` files to MP3 and OGG as well. This is intended for HTML5's audio API in JavaScript. I use a library ontop of this to support multi-track playback. So far, this works out as I want.

But. I have a variety of soundpacks. Currently, I have to manually edit my sound bootstrapper with each and every soundpack added. I wondered if this could be made simpler... So I wondered if one could require many things at once in a dynamic manner - aka. flood-require.

```javascript
var soundpacks = require.flood("./soundpacks/**/*.soundpack");
// loads soundpacks/8bit/8bit.soundpack.json and such with the proper loader.
// the soundpacks object contains an object, with each name associated to the exports of the module.
// In my case, this would be: { 8bit: {...} }
```

I know that `require.flood()` is not implemented. But how exactly would I get the behaviour described above working at all? As you can see, glob patterns are used in order to pick out the folders in the `soundpacks` folder, relative to the current script.

Would be great to have a solution for this. :)

Kind regards, Ingwie

**Comment by bebraw** [comment]
Wouldn't it be possible to implement this on top of [require.context](https://webpack.github.io/docs/context.html)? Here's what it would look like:

```javascript
var req = require.context('./soundpacks', true, /^\.\/.*\.soundpack$/);

// 1. use req.keys() to get soundpack files
// 2. req(file) per each
```

I think you'll get pretty close to what you are after this way. You can hide that `req.keys` bit behind some function. `require.context` is a bit iffy in that it won't work with dynamic values but that probably doesn't matter here.

**Comment by IngwiePhoenix** [comment]
That sounds like it could be what I am looking for. I'll give it a try for sure. :)

**Comment by shama** [comment]
@sokra This issue seems like it could be closed, right? `require.context` is exactly for the OP's purpose (thanks @bebraw!).
