### ISSUE TITLE
Installing webpack ^4.42.1 gives me deprecated warnings

### ISSUE THREAD

**Issue by thatguyjono94** [webpack/webpack#10662]
I get the following two warnings on a npm install:

`npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated`
`npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated`

Do we have a issue for this already? My apologies if we do, but not sure if we should just ignore this warning or address it.

**Comment by thatguyjono94** [comment]
Can I get a follow up on this please? Is this warning happening for anyone else?

**Comment by evilebottnawi** [comment]
Deprecations from `resolve-url` and `urix` packages, webpack doesn't use these packages, maybe contributors of these projects doesn't have time to update dependencies, sometimes it happens, you can open issues in their repo, thanks

**Comment by BGodefroid** [comment]
I get the same warning when I try to install grunt-cli using this command: npm install -g grunt-cli
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
