### ISSUE TITLE
__webpack_exports_info__ incorrect for default

### ISSUE THREAD

**Issue by vankop** [webpack/webpack#10663]
# Bug report

**What is the current behavior?**

incorrect info, default is used

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/vankop/webpack/commit/03c85918b4084b0d241cc7804c290eec1dc8d533

**What is the expected behavior?**

test should pass

**Aditional information**

If change `__webpack_exports_info__.mod` to `__webpack_exports_info__.default` all works as expected

**Other relevant information:**
webpack version:  master 3b700e710ddac77677fffbf4991ac123560eac73
Node.js version: 
Operating System: 
Additional tools:

**Comment by sokra** [comment]
The test is wrong:

`__webpack_exports_info__.maxCount.used` -> `__webpack_exports_info__.default.used
