### ISSUE TITLE
resourceQuery and babel-plugin-module-resolver root module not found

### ISSUE THREAD

**Issue by DamSenViet** [webpack/webpack#10672]
# Bug report

**What is the current behavior?**
Using babel-plugin-module-resolver with the root alias to my project's `src` directory in tandem with a `resourceQuery` fails to compile. The module is not found when using an import that is project relative with a `resourceQuery` applied.

e.g. Suppose the root path for imports inside the build are aliased to my project's `src` folder. `import FooSVG from "/assets/icons/foo.svg?inline"` will lead to a similar error message and the module will not be found.

**If the current behavior is a bug, please provide the steps to reproduce.**
https://github.com/Thulinma/ACNLPatternTool/tree/webpack-issue

1. Clone the above repository

2. Setup project **according to that branch's README.**

3. Execute `npm run dev` in the main repository.

Please do note that this project uses a build script rather than relying on the webpack cli. The config files will be used slightly differently compared to regular projects.

The result should be an error within `/src/pages/Home.vue`  where the resource with resourceQuery is not having its path resolved by babel-plugin-module-resolver despite having set a root alias (and therefore fails to compile). I've also switched around the `svgRule` settings in  `/config/webpack.config.js` where the `resourceQuery` is applied to the file-loader rather than the vue-svg-loader and the same problem occurred with the file-loader as a test (not included in the HEAD of that branch). The aforementioned test demonstrated that the issue does not discriminate between loaders. The issue now lies with webpack or the babel plugin.

**What is the expected behavior?**
The project's home page should compile and load without issue and the the module should be found when using babel-plugin-module-resolver with an alias set to the project's `src` folder with a resourceQuery applied to the import statement.

**Other relevant information:**
webpack version:  4.41.6
Node.js version: 13.7.0
Operating System: macOS
Additional tools:

**Comment by sokra** [comment]
Sounds like `babel-plugin-module-resolver` is not able to handle querystrings in requests

**Comment by DamSenViet** [comment]
I accidentally filed this issue here thinking I was on my tab with the babel-plugin repo 😅. I'm a little bit more certain it's the plugin now. I was able to resolve the issue by using an alias rather than a root alias in both webpack and babel-plugin-module-resolver.
