### ISSUE TITLE
How to ignore require with expression replacement?

### ISSUE THREAD

**Issue by ivansky** [webpack/webpack#10673]
I'm trying to bundle `node_modules` for `nodejs` application to decrease size of application image and save some essential space. 

There is an issue with tricky library that is needed for application.
It has a few require with expression like:
```js
const manifest = require(path.join(this.distDir, constants.PRERENDER_MANIFEST));
```
and I got
```js
const manifest = __webpack_require__(1)(path_1.join(this.distDir, constants_1.PRERENDER_MANIFEST));
```
This doesn't work at all because `__webpack_require__(1)` function doesn't lead to original require.

How to tell webpack that expression requires should be touched?
How to manage it? Could you please help me?

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Please respect time other developers, thanks
