### ISSUE TITLE
Files added to compilation.compilationDependencies don't trigger a rebuild via --watch

### ISSUE THREAD

**Issue by garygreen** [webpack/webpack#10674]
# Bug report

When adding dependencies to webpack manually using `compilation.compilationDependencies` and then using  `--watch` when you change the file you added a dependency for Webpack does not trigger a rebuild.

**What is the expected behavior?**

For all the dependencies you've added it should trigger a rebuild whenever you change those files.

**Example code**

```js
const path = require('path');

/**
 * Manually list dependencies here to automatically rebuild if any of these files change.
 * This is useful for files in the chain that webpack isn't aware of.
 */
const addDepPaths = [
	'some_external_dep_webpack_doesnt_know_about_due_to_external_tooling.js'
];

module.exports = {
	entry: {
		site: './test.js'
	},

	output: {
		path: __dirname + '/test',
		filename: 'js/[name]-[contenthash].js'
	},

	mode: 'development',

	plugins: [{
		apply: function(compiler) {
			compiler.hooks.compilation.tap('add-deps', function(compilation) {
				addDepPaths.forEach(function(depPath) {
					compilation.compilationDependencies.add(path.join(compiler.context, depPath));

					// This is maybe the new way to do it in Webpack 5?
					// https://github.com/webpack/webpack.js.org/issues/2755
					// compilation.fileDependencies.add(path.join(compiler.context, depPath));
				});
			});
		}
	}]

};
```

Note: this is example code, please don't comment about how you should be using `import some_external...` in `test.js` because we have a need to add a dependency in our plugin/workflow that Webpack simply doesn't see due to external tooling.

**Other relevant information:**
webpack version:  4.41.5

**Comment by evilebottnawi** [comment]
You should use `contextDependencies` for directories and `fileDependencies` for files

**Comment by garygreen** [comment]
@evilebottnawi that is the bug. It doesn't work.
