### ISSUE TITLE
"production" mode is causing an exception in IE11

### ISSUE THREAD

**Issue by NicHaley** [webpack/webpack#10675]
# Bug report

**What is the current behavior?**
I am bundling my TypeScript application with Webpack 4, and compiling with Babel. When using `mode: "production"` in `"webpack": "^4.42.1",` I get the error `Unhandled promise rejection Typeerror: Object doesn’t support this action` in IE11. The error doesn't occur in any other browsers, and it doesn't occur when using "developement" or "none" mode. Because the other modes are working, I assume that the error is due to a "production" mode configuration, and not (directly) related to my babel config. My guess is that some "production" config is not playing nice with Babel.

I have been trying to reverse-engineer the issue by using the same `production` config found [here](https://webpack.js.org/configuration/mode/#mode-production) with `mode: "none"` to try and produce the same error. Once the issue can be re-produced without `mode: "production"`, it should be straightforward to deduce the culprit option. So far I have not had any success. The snippet provided does not contain the `TerserPlugin` config, and for all I know might not actually be a 1:1 match of "production" mode. 

**If the current behavior is a bug, please provide the steps to reproduce.**
Not sure this is possible because I cannot reproduce outside my codebase, which is private. 

**What is the expected behavior?**
If `mode: "development"` bundle output is IE11 compatible, I would expect `mode: "production"` to be as well.

**Other relevant information:**
webpack version:  4.42.1
Node.js version: v13.8.0
Operating System: macOS Catalina 10.15.4
Additional tools: IE11

**Comment by evilebottnawi** [comment]
> If the current behavior is a bug, please provide the steps to reproduce.
> Not sure this is possible because I cannot reproduce outside my codebase, which is private.

Sorry we can't help, it is impossible to fix something somewhere

**Comment by NicHaley** [comment]
@evilebottnawi Would you be able to provide me with the full configuration object produced `mode: "production"`? If I could have that I would be able to further debug on my end.

**Comment by evilebottnawi** [comment]
Maybe bug with tree shaking, maybe bug in minificator - terser, maybe in external plugins/loaders, 
we don’t need all the code, just a small example that broken in IE11

**Comment by NicHaley** [comment]
That's fair - I'll need to spend some time to understand where the error is happening. Unfortuantely, the IE11 exception does not provide a line number so makes debugging extremely hard. Once I do that I can try to send over some code.

If possible I would still love to get the full config under "Mode: production" on this page: https://webpack.js.org/configuration/mode/#mode-production. That would help me determine if it's happening in the terser or elsewhere

**Comment by evilebottnawi** [comment]
@NicHaley try to disable minimizer firstly - https://webpack.js.org/configuration/optimization/#optimizationminimize

**Comment by NicHaley** [comment]
Okay, after some serious digging I have managed to find the problematic code. The error `Unhandled promise rejection Typeerror: Object doesn’t support this action` is coming from 

```
import "custom-event-polyfill";
....
new CustomEvent(...);
```
Using `CustomEvent` in IE11 and lower is a known issue. As per this [stackoverflow thread](https://stackoverflow.com/a/31783177/4282290), I added the polyfill:

```
  if (typeof window.CustomEvent === "function") {
    return; // If not IE
  }

  // tslint:disable-next-line:function-name
  function CustomEvent<T>(event: string, params: EventParams): CustomEvent<T> {
    const newParams = params || { bubbles: false, cancelable: false, detail: undefined };
    const evt = document.createEvent("CustomEvent");
    evt.initCustomEvent(event, newParams.bubbles, newParams.cancelable, newParams.detail);

    return evt;
  }

  CustomEvent.prototype = window.Event.prototype;

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  window.CustomEvent = (CustomEvent as any);
```
And as I mentioned, this works in `mode: "development"`.

**Comment by evilebottnawi** [comment]
Please provide your configuration

**Comment by NicHaley** [comment]
Webpack:
```
  {
    entry: { client: './src/client/index.tsx' },
    module: {
      rules: [
        {
          test: /\.(ts|js)x?$/,
          exclude: /node_modules/,
          loader: "babel-loader"
        }
      ]
    },
    resolve: {
      extensions: [".ts", ".js", ".tsx", ".jsx"],
      alias: {
        ...
      }
    },
    plugins: [
      new webpack.EnvironmentPlugin({
        ...
      })
    ],
    externals: {
      preact: "preact"
    },
    output: {
      filename: 'index.js',
      path: '/Users/x/data/y/z/dist/client',
      publicPath: '',
      crossOriginLoading: 'anonymous'
    },
    mode: 'production'
  }
```

Package.json (shortened to show webpack, TS, babel):
```
  "devDependencies": {
    "@babel/cli": "^7.7.7",
    "@babel/core": "^7.7.7",
    "@babel/plugin-proposal-class-properties": "^7.7.4",
    "@babel/plugin-proposal-numeric-separator": "^7.7.4",
    "@babel/plugin-proposal-object-rest-spread": "^7.7.7",
    "@babel/plugin-transform-react-jsx": "^7.8.3",
    "@babel/plugin-transform-runtime": "^7.7.6",
    "@babel/preset-env": "^7.7.7",
    "@babel/preset-typescript": "^7.7.7",
    "babel-loader": "^8.0.6",
    "babel-preset-preact": "^2.0.0",
    "typescript": "^3.7.4",
    "webpack": "^4.42.1",
    "webpack-bundle-analyzer": "^3.5.0",
    "webpack-cli": "^3.3.6",
    "webpack-dev-server": "^3.7.2",
    "webpack-merge": "^4.2.2",
    "webpack-subresource-integrity": "^1.3.4"
  },
  "dependencies": {
    "@babel/runtime": "^7.7.7",
    "@sentry/browser": "^5.15.3",
    "@types/json-stable-stringify": "^1.0.32",
    "@types/uniqid": "^4.1.3",
    "dotenv": "^8.2.0",
    "json-stable-stringify": "^1.0.1",
    "preact": "10.3.3",
    "uniqid": "^5.0.3",
    "webpack-s3-plugin": "^1.0.3"
  }
```

Babel:
```
const presets = [
  "preact",
  [
    "@babel/preset-typescript",
    {
      jsxPragma: "h"
    }
  ],
  [
    "@babel/preset-env",
    {
      corejs: 3,
      useBuiltIns: "usage"
    }
  ]
];

const plugins = [
  "@babel/plugin-proposal-class-properties",
  "@babel/plugin-proposal-object-rest-spread",
  "@babel/plugin-proposal-numeric-separator",
  [
    "@babel/plugin-transform-react-jsx", {
      "pragma": "h",
      "pragmaFrag": "Fragment"
    }
  ],
  [
    "@babel/plugin-transform-runtime",
    {
      regenerator: true
    }
  ]
];

module.exports = { presets, plugins };
```

**Comment by evilebottnawi** [comment]
Can you run `npm ls terser`?

**Comment by NicHaley** [comment]
```
embed-frames@1.0.0 /Users/x/data/y/z
└─┬ webpack@4.42.1
  └─┬ terser-webpack-plugin@1.4.3
    └── terser@4.6.3
```

**Comment by evilebottnawi** [comment]
Update terser to latest version - `4.6.10`

**Comment by NicHaley** [comment]
Upgraded, but same error.

```
embed-frames@1.0.0 /Users/x/data/y/z
└─┬ webpack@4.42.1
  └─┬ terser-webpack-plugin@1.4.3
    └── terser@4.6.10
```

**Comment by evilebottnawi** [comment]
Looks problem in terser, we need minimum reproducible test repo to report terser repo, can you help?

**Comment by NicHaley** [comment]
I can try and set one up

**Comment by NicHaley** [comment]
@evilebottnawi I have set one up [here](https://github.com/NicHaley/WebpackTerser). I am trying to mirror my issue as closely as possible, but so far have not been able to reproduce. I will try to get a reproducable error when I have some more time

**Comment by koriner** [comment]
@NicHaley I'm running into this same issue with CRA/TS/IE11 and struggling to get things to work. Have you had any luck fixing this?

**Comment by evilebottnawi** [comment]
Cam't reproduce on IE11 and Edge, all works fine, maybe you use old version of IE11?

**Comment by NicHaley** [comment]
Hey! Unfortunately I haven't been able to make it reproducible yet in my sample project. In my own project I got around the issue with a different polyfill. Rather than define a new `CustomEvent` on the window, I just use `document.createEvent("CustomEvent");` for all events. Unfortuantely it doesn't get to the root of the issue though.

**Comment by evilebottnawi** [comment]
Maybe an another package inject something in globals for IE11

**Comment by koriner** [comment]
@NicHaley I actually discovered that just including the `custom-event-polyfill` solved this in my case!

**Comment by evilebottnawi** [comment]
@NicHaley You can try to recreate the problem again?

**Comment by NicHaley** [comment]
@evilebottnawi Still working on it...Still unclear what is causing the problem, but I think your guess may be correct. Seems likely another module that is causing a conflict in production mode.

**Comment by NicHaley** [comment]
@evilebottnawi Apologies for taking so long with a reply. I believe the issue can be safely closed, as the issue appears to be related to tree-shaking `import './custom-event-polyfill';`, and not including it as a sideEffect.

**Comment by NicHaley** [comment]
@koriner Perhaps this will help you as well if you are using [side effects](https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free).
