### ISSUE TITLE
[RFC] IgnorePlugin filter function should receive more arguments

### ISSUE THREAD

**Issue by wood1986** [webpack/webpack#10671]
## Feature request

**What is the expected behavior?**

Currently `checkResource (resource, context)` is the filter function for IgnorePlugin. I would suggest the filter function should change to `checkResource({resource, context, issuer, type})`.

**What is motivation or use case for adding/changing the behavior?**

I have a scenario that if the request is issued from non node_modules and the request is asynchronous (`import("./lazy"), require.ensure(["./lazy"]), require(["./lazy"])`), I want to ignore it.

**How should this be implemented in your opinion?**

Change this line from

https://github.com/webpack/webpack/blob/0fa27b62441b8dd36097cd1ddc3e39f83e65aa37/lib/IgnorePlugin.js#L41

to

```
this.options.checkResource({
  request: resolveData.request,
  context: resolveData.context,
  issuer: resolveData.contextInfo.issuer,
  type: resolveData.dependencies[0].type
})
```

**Are you willing to work on this yourself?**
yes

**Comment by wood1986** [comment]
any updates?

**Comment by sokra** [comment]
`type` won't work as multiple types are resolved in a single request.

**Comment by wood1986** [comment]
@sokra Could you give some example? Or are you talking about this scenario?

```js
import _ from "lodash";

import("lodash")
```

**Comment by wood1986** [comment]
How can I ignore all the lazy loading import statement from my app only? I am trying to build a bundle for server side rendering. there is no need to split the lazy chunk because they will not get called or executed in the initial state. So it is safe to ignore them.

I do not want to put the magic comment `/* webpackIgnore: true */` because when I build the client side rendering bundle and I have to remove this magic comment.
