### ISSUE TITLE
Files added to compilation.compilationDependencies don't trigger a rebuild via --watch

### ISSUE THREAD

**Issue by garygreen** [webpack/webpack#10678]
**reopening closed issue: #10674 with more info**

# Bug report

When adding dependencies to webpack manually using `compilation.compilationDependencies` and then using  `--watch` when you change the file you added a dependency for Webpack does not trigger a rebuild.

This is also an issue with `contextDependencies` and using `fileDependencies`

According to @evilebottnawi it should be supported.

**What is the expected behavior?**

For all the dependencies you've added it should trigger a rebuild whenever you change those files.

**Example code**

```js
const path = require('path');

/**
 * Manually list dependencies here to automatically rebuild if any of these files change.
 * This is useful for files in the chain that webpack isn't aware of.
 */
const addDepPaths = [
	'some_external_dep_webpack_doesnt_know_about_due_to_external_tooling.js'
];

module.exports = {
	entry: {
		site: './test.js'
	},

	output: {
		path: __dirname + '/test',
		filename: 'js/[name]-[contenthash].js'
	},

	mode: 'development',

	plugins: [{
		apply: function(compiler) {
			compiler.hooks.compilation.tap('add-deps:compilation', function(compilation) {
				addDepPaths.forEach(function(depPath) {
					compilation.compilationDependencies.add(path.join(compiler.context, depPath));
				});
			});

			compiler.hooks.afterEmit.tap('add-deps:afterEmit', function(compilation) {
				addDepPaths.forEach(function(depPath) {
					compilation.fileDependencies.add(path.join(compiler.context, depPath));
				});
			});

			compiler.hooks.afterEmit.tap('add-deps-using-contextDependencies:afterEmit', function(compilation) {
				addDepPaths.forEach(function(depPath) {
					compilation.contextDependencies.add(path.join(compiler.context));
				});
			});
		}
	}]

};

https://github.com/garygreen/webpack-dep-problem
```

Note: this is example code, please don't comment about how you should be using `import some_external...` in `test.js` because we have a need to add a dependency in our plugin/workflow that Webpack simply doesn't see due to external tooling.

**Other relevant information:**
webpack version:  4.41.5

**Comment by evilebottnawi** [comment]
You example still use `compilationDependencies`, do you check `contextDependencies` and `fileDependencies`?

**Comment by evilebottnawi** [comment]
Copy webpack plugin uses this code for adding deps - https://github.com/webpack-contrib/copy-webpack-plugin/blob/master/src/index.js#L99

**Comment by garygreen** [comment]
I've added some more examples including the one you linked to which `copy-webpack-plugin` uses - it doesn't seem to work.

Can you clarify, if you add those depdencies should the `--watch` command rebuild when you make any changes to those depdencies? That is my understanding, though I could be mistaken.

Here's a reproducable repository with everything you need: https://github.com/garygreen/webpack-dep-problem

**Comment by sokra** [comment]
It works with your repro.

Note that you won't see anything in the console as the build produced exact the same result and the cli doesn't print stats output again if it's identical.

The file should have influence on the build to see updated stats output.

**Comment by garygreen** [comment]
> Note that you won't see anything in the console as the build produced exact the same result and the cli doesn't print stats output again if it's identical.

When updating `some_external..` js file in our app that SHOULD result in a different build output but as you can see from that example repo it doesn't even re-create the bundle.

Try:

1. Deleting the `test` folder
2. npm run watch
3. Edit `some_external...` file and notice how nothing happens in Webpack. Test folder is empty, the bundle isn't even created.

We even use `[contenthash]` as our output filenames so if the contents changed as a result of changing the external dependency file (that is tracked with `fileDependencies`) then webpack SHOULD rebuild, show stats and create a new file. Unfortunately it currently doesn't seem to do anything - could be due to internal mechanisms in webpack for caching?

It's almost like webpack needs a new API `externalFileDependencies` and whenver those files are changed webpack will ALWAYS rebuild, as it can't possibly know if the bundle have changed or not by that third party tool.

**Comment by sokra** [comment]
> When updating `some_external..` js file in our app that SHOULD result in a different build output

Why should it? The file not not used in any way in your plugin.

> We even use `[contenthash]` as our output filenames so if the contents changed as a result of changing the external dependency file

the `some_external..` js file is not part of the content of the output file, so contenthash is unaffected.

> It's almost like webpack needs a new API `externalFileDependencies` and whenver those files are changed webpack will ALWAYS rebuild, as it can't possibly know if the bundle have changed or not by that third party tool.

By adding it to file/compilationDependencies it will rebuild, but as nothing has changed to the bundle it won't print stats.

You can verify this by adding a console.log to the `compilation` hook.

> PS: I'm on Windows. Not sure if that makes a difference to the watcher...

Me to, but this doesn't make a difference.

**Comment by garygreen** [comment]
> the some_external.. js file is not part of the content of the output file, so contenthash is unaffected.

In our application it is. I have simplified the example repo but basically this is our use case:

**postcss.config.js**
```js
// This is the "external" file that webpack doesn't know about.
// So we want to track it with ".file/.compilationDependencies"
import siteTheme from './site-theme.js';

module.exports = {
   plugins: [
       siteTheme.postcssPlugin()
   ]
}
```

**site-theme.js**
```js
// This file is responsible for helpers and utilities in building our site theme.
// It exports a postcss plugin.
// Any changes to this file SHOULD be tracked, but currently it doesn't seem easily possible with webpack.
var variables = {
   'text-blue': '#0000ff',
   // ....
};

function postcssPlugin() {
   // .... reads the variables, performs various mutations to css for our theme, etc.
}

export default postcssPlugin;
```

Because Webpack doesn't know about our imported `site-theme.js` file it won't re-build anything. What we're looking to achieve is a way to tell webpack that dependency and any changes to that file (such as adding new variables, etc) for it to rebuild our bundle.

We could possibly achieve this by creating our own loader, but I don't see why that is nesscary when all we want to do is track a file and have it rebuild when it's changed....

Hopefully you can see our problem and use case more clearly now. If you need more information let me know

**Comment by sokra** [comment]
Now it's something different. Your problem is not that it's not rebuilding. Your problem is that the modules processed with postcss are cached, because webpack doesn't know to invalidate the cache for them when the file changes.

You need to add the file as fileDependency to the module. A loader can do that.

Here is a loader that would do it:

``` js
const path = require("path");
module.exports = function(source) {
  this.addDependency(path.resolve("site-theme.js"));
  return source;
}
```

Chain it with the postcss-loader:

``` js
module.rules: [
  {
    test: /\.css$/,
    use: ["postcss-loader", "./my-postcss-dependencies-loader.js"]
  }
]
```

---

A postcss-plugin could also do it like this:

``` js
module.exports = postcss.plugin("postcss-dependencies-plugin", function () {
    return function (root, result) {
      result.messages.push({
        type: "dependency",
        file: path.resolve(site-theme.js")
      });
    };
});
```

---

I would recommend to use the loader, otherwise a syntax error in `site-theme.js` would break watching as the config file can't be read at all.

**Comment by garygreen** [comment]
@sokra thank you so much for you help on this, it's much appreciated 💑

The examples you provided are of great help. In addition I've discovered that Node caches any `require` statements so that meant any changes to those files that were required/imported were only being processed once even though Webpack was trying to rebuild as it was added as dependency.

So for anyone else stumbling across this issue the below helper should come in handy:

**dep-plugin.js**
```js
// It's possible to tell Node to remove a module from it's cache.
// This function allows you to require without using the cache.
function requireUncached(module) {
    delete require.cache[require.resolve(module)];
    return require(module);
}

module.exports = postcss.plugin("postcss-dep-plugin", function (configPath) {
    return function (root, result) {
      var theme = requireUncached(configPath);

      // do whatever you want with the theme

      result.messages.push({
        type: "dependency",
        file: configPath // this needs to be a exact path, including `.js` I believe.
      });
    };
});
```

**site-theme.js**
```js
function theme() {
   return {
       'text-blue': 'blue',
   }
}

module.exports = theme;
```

**postcss.config.js usage:**
```js
const path = require('path');

module.exports = {
    plugins: [
       require('./dep-plugin')(path.resolve(__dirname, './site-theme.js')) // make sure to provide exact path.
   ]
}
```
