### ISSUE TITLE
define a new configuration for adding async attributes to script element when loading chunks

### ISSUE THREAD

**Issue by qianghuang94** [webpack/webpack#10681]
## Feature request

**What is the expected behavior?**
A new configuration for adding `async` attribute to script element that used for loading chunks.

**What is motivation or use case for adding/changing the behavior?**
Improve performance.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script
Based on the documentation of async attr
> This attribute allows the elimination of parser-blocking JavaScript where the browser would have to load and evaluate scripts before continuing to parse. defer has a similar effect in this case.

It can unblock parser to work.

**How should this be implemented in your opinion?**
Define a configuration in the outputOptions, and modify the file: https://github.com/webpack/webpack/blob/6f413ae2e63897aef5e1956cb1c351ab33f6dbfe/lib/web/JsonpTemplatePlugin.js#L134
Similar to crossOrigin.

**Are you willing to work on this yourself?**
yes

**Comment by evilebottnawi** [comment]
It is unnecessary because all scripts created via `var script = document.createElement('script');` always async. 

Just run in browser:
```js
var script = document.createElement('script');
console.log(script.async);
```

**Comment by qianghuang94** [comment]
> It is unnecessary because all scripts created via `var script = document.createElement('script');` always async.
> 
> Just run in browser:
> 
> ```js
> var script = document.createElement('script');
> console.log(script.async);
> ```

Thank you!
