### ISSUE TITLE
[Feature request] configurable dynamic import

### ISSUE THREAD

**Issue by NE-SmallTown** [webpack/webpack#10682]
## Feature request

**What is the expected behavior?**

At now, it seems that we will bundle all dependencies into the output(i.g dist) when it's a **3rd party** package. **But** for the **app** code, it will not. For example:

```
// src/main.js

import ('packageFoo');
import localBar from './bar';

...
```

```
// node_modules/packageFoo

import 'react-dom';

...
```

```
// src/bar.js

import 'react-dom';

...
```

```
// webpack.config.js

splitChunks: {
  cacheGroups: {
    vendors: {
      test: /[\\/]node_modules[\\/](react|react-dom)[\\/]/,
      name: 'vendors',
      chunks: 'all',
    }
  }
}
```

After run build, there will be 3 bundled files, `main.hash.js`, `vendor.hash.js`, `packageFoo.hash.js`.

But I find that in `packageFoo.hash.js`, the dependency `react-dom` will be packed into it, but for `localBar`, you can't find `react-dom` in `main.hash.js`(that's where `localBar` code are), instead, the `react-dom` will be in `vendor.hash.js`, this is right IMO. The problem here is why `react-dom`(i.g the dependencies) be packed into 3rd party package rather than use/keep the `require` statement, in other words, why dynamic import syntax chose the dist/application pack strategy rather than 'lib'(just keep all dependencies require. BTW, this is not about `transform-runtime`).

From my personal perspective, maybe that's because we can't promise the dependencies of that package has been loaded whenever/wherever request the 'packageFoo', but I think this is an edge case. So, depend on the most cases, maybe make the dynamic import strategy from 'dist' to `lib` is a good choice. And for those edge cases, we can provide a configurable way like `import (/* webpackDynamicStrategy "dist" */ 'packageFoo');`?

**What is motivation or use case for adding/changing the behavior?**
As described above.

**How should this be implemented in your opinion?**
As described above.

**Are you willing to work on this yourself?**
no, I'm afraid it's not my skill.

**Comment by sokra** [comment]
webpack should not bundle react-dom into packageFoo.hash.js as it's already in vendors.hash.js which has been loaded at this case.

It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by NE-SmallTown** [comment]
Ah, sorry, my mistake, it's(actually is`react-dom-sever`, instead `react-dom`) caused by hot-loader rather than webpack
