### ISSUE TITLE
webpack -w does not output subsequent errors

### ISSUE THREAD

**Issue by k88hudson** [webpack/webpack#1069]
STR:

0. run `webback -w`
1. Add a syntax error at line 5 in a file
2. Webpack outputs `Module build failed: Error: Parse Error: Line 5: ....` to console
3. Add another syntax error at line 15
4. Fix the error at line 5

I would expect a new error message to be output referring to line 15, but it seems that there is no new console output. Is this intended behaviour?

**Comment by bebraw** [comment]
@k88hudson Can you try again with a fresh version?
