### ISSUE TITLE
DllReferencePlugin scheme lost the sourceType "system"

### ISSUE THREAD

**Issue by strayiker** [webpack/webpack#10699]
# Bug report

**What is the current behavior?**
```javascript
new webpack.DllReferencePlugin({
      ...
      sourceType: 'system',
    })
```
Using this config results in a build failure with a schema validation message.

https://github.com/webpack/webpack/blob/110033897cf4187bfa5430aa82c2d1dde5dab73f/schemas/plugins/DllReferencePlugin.json#L82-L94

**What is the expected behavior?**
Expects that this config will not break the build.

**Other relevant information:**
webpack version:  4.42.0
Node.js version: 13.10.1
Operating System: MacOS

**Comment by sokra** [comment]
Send a PR
