### ISSUE TITLE
Webstie not reloaded on updating state.js files in the store

### ISSUE THREAD

**Issue by DarkLite1** [webpack/webpack#10697]
# Bug report

**Describe the bug**
When I change something in the file ‘/store/navigation/state.js’, say I change ‘label: “About”’ to ‘label: “About2222”’, the webpage is not reloaded automatically after saving the file.

Quasar detects the change as I see it re-running in the terminal when the file is saved but the browser needs a manual refresh by clicking the refresh button or hitting F5. Don’t know if this is me, Quasar or a plugin that is failing.

**Codesandbox**
Check out the [header file on codesandbox](https://codesandbox.io/s/falling-sea-s33z7?file=/src/components/Header.vue) and the [state.js file](https://codesandbox.io/s/falling-sea-s33z7?file=/src/store/navigation/state.js). If you change something in state.js a manual refresh is needed.

**To Reproduce**
1. Start the server, see the page correctly loaded
2. Change the the label of the header from 'About' to 'SomethinngElse' in the file src/store/navigation/state.js
3. Notice the browser didn't reload itself

**Expected behavior**
A reload of the browser window

**Other relevant information:**
webpack version:  4.42.1
Node.js version:  v13.9.0
Operating System:  codesandbox and Win Srv 2016
Additional tools: Quasar framwerok 1.6.1

My [original bug report](https://github.com/quasarframework/quasar/issues/6780) at Quasar framework brought me here. Thank you for your help.

**Comment by evilebottnawi** [comment]
Please create reproducible test repo, look like a bug in `quasar`, no problems with pure setup webpack-dev-server

**Comment by DarkLite1** [comment]
Thannks for the feebback. There is a section in my report saying 'To reproduce' these steps need to be followed within the codesandbox. The codesandbox contains all the files and starts the server so you can see it straight away without effort. Just click on [the link](https://codesandbox.io/s/falling-sea-s33z7?file=/src/components/Header.vue).

**Comment by DarkLite1** [comment]
The problem was fixed thanks to [Scott from the Quasar team](https://github.com/quasarframework/quasar/issues/6780#event-3223684297)::

_Remove this code in the store's index.js file. That fixed it on codesandbox._
```
if (process.env.DEV && module.hot) {
    module.hot.accept(['./tickets', './navigation'], () => {
      Store.hotUpdate({
        modules: {
          tickets: require('./tickets').default,
          navigation: require('./navigation').default
        }
      })
    })
  }
```
