### ISSUE TITLE
TS error when importing Stats class from Webpack package.

### ISSUE THREAD

**Issue by ernestostifano** [webpack/webpack#10711]
# Bug report

**What is the current behavior?**

```js
import {Stats} from 'webpack';

/* [...] */

const stats = new Stats(compilation);
```

TypeScript throws: ***"TS2511: Cannot create an instance of an abstract class."***

Could it be a problem with Webpack's `index.d.ts` file? Stats class is marked as abstract.

***NOTE:*** I only use TypeScript for type checking and declaration files generation for JS files with JSDoc annotations. So I am really not very familiar with TypeScript syntax. Maybe there is something that I'm missing.

**Other relevant information:**
webpack version: 4.42.1
Node.js version: 13.12.0
Operating System: macOS Catalina 10.15.3
Additional tools: N/A

**Comment by sokra** [comment]
webpack 4 doesn't publish typescript types. These usually come from https://github.com/DefinitelyTyped/DefinitelyTyped
Report issue there.

webpack 5 will ship with types.
