### ISSUE TITLE
webpack4.42.0

### ISSUE THREAD

**Issue by Yangxiucheng1002** [webpack/webpack#10712]
When I open the build file locally, it can be accessed normally, but the static resource 404 is reported as an error when deployed to the server and accessed by address

**Comment by Yangxiucheng1002** [comment]
I configured it according to the official documentation   "homepage": "./",

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
