### ISSUE TITLE
Uglify Webpack globals

### ISSUE THREAD

**Issue by gitcatrat** [webpack/webpack#10713]
Is there a way to mangle/uglify Webpack globals? Option for it? Even hacky way?

Few examples: `__webpack_exports__`, `moduleName__WEBPACK_IMPORTED_MODULE_0__`

My bundle is extremely size-sensitive and these are **10-15% of my bundle**.
https://stackoverflow.com/questions/61216115/uglify-webpack-globals

Really sorry about question here but I've adventured like a week in SO, gitter, etc - no answers.

**Comment by gitcatrat** [comment]
Mode is set to `production`, so is `process.env.NODE_ENV`, TerserPlugin is not defined.

**Comment by evilebottnawi** [comment]
Please create reproducible test repo

**Comment by sokra** [comment]
The default webpack config mangles these identifiers. Seems like you provided a custom terser config which opts out of these optimization.

**Comment by gitcatrat** [comment]
@sokra That's not the case, no Terser configuration is provided.

**Comment by gitcatrat** [comment]
```js
  return {
    mode: options.mode || 'production',
    target: 'web',
    // can cache bite us in the ass?
    cache: {type: 'memory'},
    entry: {
      adtag: [path.resolve(__dirname, '../src/index.js')]
    },
    output: {
      path: path.resolve(__dirname, 'dist'),
      publicPath: options.publicPath || '',
      filename: '[name].js',
      chunkFilename: '[name].js',
      jsonpFunction: 'loader_' + Date.now() + '_' + randomInt
    },
    resolve: {
      alias: {
        // 5 aliases to directories
      }
    },
    // only DefinePlugin with big object (about 20-25 properties)
    plugins: plugins
  };
```

**Comment by evilebottnawi** [comment]
Provide plugins

**Comment by gitcatrat** [comment]
@evilebottnawi 

```js
const plugins = [
  new webpack.DefinePlugin(globals)
];

```

`globals` is dynamic depending on settings, it's returned from a function call, example:
```js
{
    FULL_API: JSON.stringify(options.fullApi || false),
    SYSTEM_ENV: JSON.stringify(options.systemEnv || 'prod'),
    ROOT_PATH: JSON.stringify(options.rootPath || false),
    LEGACY: JSON.stringify(options.legacy || false),
    FEATURES: {
      VIDEO: JSON.stringify(true),
      // etc
    },
    SETTINGS: JSON.stringify(options.settings || []),
}
```

**Comment by evilebottnawi** [comment]
Please use issue template in future, because we start to answer questions from the issue template, I don't know your version of webpack, don't know configuration, don't know other information

Please create minimum reproducible test repo

**Comment by gitcatrat** [comment]
@evilebottnawi Yeah sure, I used question format because I had no idea if Webpack acutally does it by default, asked several times in gitter, stackoverflow, etc and nobody told me.

I'll try to make a test repo, my only concern is if I manage to reproduce it. I can't just make company's code public for obvious reasons. Was hoping that it was a case of configuration.

```
"webpack": "^4.41.6",
"webpack-cli": "^3.3.11"
```

**Comment by gitcatrat** [comment]
@evilebottnawi  Thank you!

**Comment by bartlomiejzuber** [comment]
> @evilebottnawi
> 
> ```js
> const plugins = [
>   new webpack.DefinePlugin(globals)
> ];
> ```
> 
> `globals` is dynamic depending on settings, it's returned from a function call, example:
> 
> ```js
> {
>     FULL_API: JSON.stringify(options.fullApi || false),
>     SYSTEM_ENV: JSON.stringify(options.systemEnv || 'prod'),
>     ROOT_PATH: JSON.stringify(options.rootPath || false),
>     LEGACY: JSON.stringify(options.legacy || false),
>     FEATURES: {
>       VIDEO: JSON.stringify(true),
>       // etc
>     },
>     SETTINGS: JSON.stringify(options.settings || []),
> }
> ```

I see you've used `webpack.DefinePlugin` this effectively means that each occurrence of `SETTINGS` will be replaced with output of `JSON.stringify`. For example if the JSON.stringify(options.settings || []) returns huge amount of data, all this data will be put and duplicated inside final bundle each time you use 'SETTINGS' somewhere in your code. (works exactly like find & replace)

ex. 
```js
...
{
   SETTINGS: JSON.stringify(['a', 'b', 'c', 'd', 'e', 'f', 'g']),
}
...

// then webpack replaces all occurrence of `SETTINGS` in each module to `"['a', 'b', 'c', 'd', 'e', 'f', 'g']"`.
