### ISSUE TITLE
Output IIFE not working

### ISSUE THREAD

**Issue by Richacinas** [webpack/webpack#10716]
# Bug report

**What is the current behavior?**

Setting output mode to IIFE doesn't work. It creates a compilation error.

![image](https://user-images.githubusercontent.com/7046504/79361134-319c0180-7f45-11ea-95bd-422eae756c29.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

```
module.exports = {
  entry: 'index.js',
  output: {
    path: '/dist',
    filename: '[name].bundle.js',
    publicPath: '/',
    iife: true
  }
};
```

**What is the expected behavior?**

I expect Webpack to put my bundle inside my `dist` folder and have this bundle wrapped in a self called function.

**Other relevant information:**
webpack version:  **4.39.3**
Node.js version: **12.14.0**
Operating System: **Ubuntu 18.04 LTS**
Additional tools:

**Comment by evilebottnawi** [comment]
Please create reproducible test repo, can't reproduce

**Comment by evilebottnawi** [comment]
Please provide reproducible test repo, can't reproduce

**Comment by Richacinas** [comment]
Of course!

Here it is, using the mentioned versions.

On the lower bottom, open a new tab of console and run `npm start`.

https://codesandbox.io/s/determined-williams-63kxm

**Comment by evilebottnawi** [comment]
@Richacinas it is supported only for webpack@5

**Comment by Richacinas** [comment]
Ok thanks! would be good to have any mention to that in the docs.

https://webpack.js.org/configuration/output/#outputiife

**Comment by evilebottnawi** [comment]
@Richacinas feel free to open a new issue in webpack docs

**Comment by Micka33** [comment]
Hopefully, I found this issue after only 10min of google search.
