### ISSUE TITLE
Can't not resolve exported class after build

### ISSUE THREAD

**Issue by TranNgocKhoa** [webpack/webpack#10721]
# Bug report

**What is the current behavior?**
- I create a React Component which exported 2 classes are `Tabs` and `TabPane`.
- After I build, I use the bundle file to import to my example code.
- My code editor show an warning that Can not resolve symbol `TabPane`.
![Screen Shot 2020-04-16 at 19 29 38](https://user-images.githubusercontent.com/30297271/79456676-1bf80c00-8019-11ea-8b53-c08657f65f75.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
- Download code here: https://github.com/TranNgocKhoa/react-components/tree/master/tabs
- Import project by Webstorm.
- Build with production by command: `npm install && npm run build:pro`
- Open file `/example/app.js` And change `import {Tabs, TabPane} from '../src'` to `import {Tabs, TabPane} from '../dist'`
- Hover TabPane in line `import {Tabs, TabPane} from '../dist'`

**What is the expected behavior?**

`TabPane` should inported properly like `Tabs`

**Other relevant information:**
webpack version:  4.42.1
Node.js version: v12.16.2
Operating System: MacOS 10.15.4
Additional tools: WebStorm 2019.3

**Comment by evilebottnawi** [comment]
It is the error from IDE, not webpack
