### ISSUE TITLE
webpack + react + packery:  disaster

### ISSUE THREAD

**Issue by yonatanmn** [webpack/webpack#1072]
Hi,
I've just downloaded [Packery](https://github.com/metafizzy/packery) with npm for experimenting with that.
I'm using react + webpack, and when I try to build the project it fails because in some of the npm modules there is this code : 
```
 if ( typeof define == 'function' && define.amd ) {
    // AMD
    define( [
        'classie/classie'  // ...
```

the solutions provided [here](https://github.com/arasatasaygin/is.js/issues/100) doesn't help, since I'm doing `require('packery');` from my code, and when I add this to webpack.config : 
```
module: {
  loaders: [
    { test: /packery/, loader: "imports?define=>undefined" }
  ]
}
```
The require itself stops working.
The only solution I have is changing the npm's module code (forcing `if` to be always `false`).
Any better approach?

(Posted also in [Packery's github](https://github.com/metafizzy/packery/issues/270) )

**Comment by bebraw** [comment]
Just checked that issue you linked to and I saw you managed to resolve the issue. Can you close this one as well?
