### ISSUE TITLE
Can't use [chunkhash] or [contenthash] in filename if chunkFilename uses [hash]

### ISSUE THREAD

**Issue by Rheeseyb** [webpack/webpack#10724]
# Bug report

**What is the current behavior?**
In `output`, if I attempt to use the `[chunkhash]` or `[contenthash]` placeholder in `filename`, but use `[hash]` in `chunkFilename`, the build will fail with the error:
```
ERROR in chunk main [entry]
main.[contenthash].js
Cannot use [chunkhash] or [contenthash] for chunk in 'main.[contenthash].js' (use [hash] instead)
```

**If the current behavior is a bug, please provide the steps to reproduce.**
The following minimal webpack config will trigger this:
```
module.exports = {
  entry: './src/index.js',
  output: {
    filename: 'main.[contenthash].js',
    chunkFilename: '[id].[hash].js',
  },
};
```

**What is the expected behavior?**
Either of those placeholders should work, or if this is by design the error should inform me that it failed because I am using `[hash]` elsewhere (I don't believe this is by design).

**Other relevant information:**
webpack version:  4.42.1
Node.js version: 12.5.0
Operating System: macOS, Linux
Additional tools: None

**Comment by Rheeseyb** [comment]
This isn't reproducible on webpack version 5.0.0-beta.14 (I opted to submit because the guidance mentions only opening bugs against the latest version, and 4.42.1 is the latest non-beta version).

Also of note, this appears to be a similar issue to #8251

**Comment by evilebottnawi** [comment]
It is by design in webpack@4

**Comment by evilebottnawi** [comment]
For code:
```
if (
		data.noChunkHash &&
		(REGEXP_CHUNKHASH_FOR_TEST.test(path) ||
			REGEXP_CONTENTHASH_FOR_TEST.test(path))
	) {
		throw new Error(
			`Cannot use [chunkhash] or [contenthash] for chunk in '${path}' (use [hash] instead)`
		);
	}
```

We do some changes with templates in wepback@5

**Comment by evilebottnawi** [comment]
https://github.com/webpack/webpack/blob/v4.42.1/lib/TemplatedPathPlugin.js#L87

**Comment by Rheeseyb** [comment]
Ok thanks for answering. Can you elaborate on why this is the case? I only ask because I want to propose a change to the v4 docs [here](https://v4.webpack.js.org/configuration/output/#outputfilename) but to do that I'd like to be able to state roughly why the restriction is there
