### ISSUE TITLE
dynamic import for chunk in node_modules is not working as expected

### ISSUE THREAD

**Issue by gaurav5430** [webpack/webpack#10722]
# Bug report

**What is the current behavior?**
When _Project B_ imports _Project A_ from `node_modules`, and _Project A_ uses dynamic import/lazy loading to load some part of itself as required, the resolution fails on _Project B_ (webpack in _Project B_ can't find the chunk file at the expected place).

**If the current behavior is a bug, please provide the steps to reproduce.**
Project A
- Create a webpack project. - _Project A_
- Add dynamic imports in _Project A_ to get some chunks dynamically.
- Observe that the chunks are created in the output folder (build) and lazy loading works fine when running this project.

Project B
- Create a webpack project - _Project B_
- include _Project A_ as a dependency.
- in some file in _Project B_, import the main module from _Project A_ (which would lazy load other parts of _Project A_ as required)
- The lazy loaded chunks as specified in _Project A_ , do not get resolved now.

This seems to happen because once _Project A_ main chunk has been created in _Project B_ (because of the import), all the relative paths inside the main file in _Project A_ are now resolved relative to _Project B_. So previously the chunk that was resolved from "Project A/build" is now trying to get resolved from "Project B/build"
But _Project B_ does not have the chunks required by _Project A_ in its build folder (they are only in the build folder of _Project A_), so the call fails.

**What is the expected behavior?**
The expected behaviour is to get the chunk resolution working. 
I can partly understand why it is not working, because it is trying to resolve those urls relative to the current _Project B_, but _Project B_ does not have those chunk files in the build directory (although the files are available in Project B/node_modules/Project A/build)

Currently I can make it work by copying **Project A/build/*** to **Project B/build/*** , which lets webpack find the required chunks at the current url.

Would it make sense for webpack to copy the dynamically imported chunks from _Project A_ to _Project B_, if during import it encounters an import from _Project A_, and that import further dynamically imports other modules. If i am not wrong, this is how it works for static imports.

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

**Comment by Akany** [comment]
Is there any suggestions how to solve it ?

**Comment by gaurav5430** [comment]
We have currently solved it using[ webpack-copy-plugin](https://webpack.js.org/plugins/copy-webpack-plugin/) to copy the generated chunks from `node_modules` entry for Project A to our build folder of Project B. This requires the consumer to have an understanding of how and where the chunks for the dependent project are created, and is not a general solution, which means we would have to add an entry for any other such dependencies in our consumer webpack config, if we have in future.

Just to give you more context, this is a similar/the same problem as discussed here:

https://github.com/webpack/webpack/issues/7843
https://github.com/webpack/webpack/issues/8934
https://levelup.gitconnected.com/micro-frontend-architecture-dynamic-import-chunks-from-another-webpack-bundle-at-runtime-1132d8cb6051

**Comment by lmaddio** [comment]
I have the same issue but can't use **webpack-copy-plugin** because I depend on multiple dependencies and cannot predict which ones are or not using dynamic imports.
Any other idea to that dynamic file to (as in your example) **Project B/build** without having the file name?

**Comment by gaurav5430** [comment]
i don't have the file names either, but I do have the build folder name for Project A, that's what i use.

So, in my case, it would be:
'../node_modules/ProjectA/build'

**Comment by lmaddio** [comment]
In my case ProjectA comes from a lerna repo, so I have there a lot of packages and I don't know which of those are or not implementing dynamic imports.
ProjectB could be using ProjectX being X any package inside lerna

**Comment by gaurav5430** [comment]
yeah, I mean, there needs to be a specific solution for different use cases, so in your case, you would have to know all of the Projects that create chunks, and just add an entry for all of them in your copy plugin config

https://levelup.gitconnected.com/micro-frontend-architecture-dynamic-import-chunks-from-another-webpack-bundle-at-runtime-1132d8cb6051  would possibly help you once this is in webpack

**Comment by Akany** [comment]
@gaurav5430 as i see, it wont solve the issue - it goes to micro front end.
In my case, i want main bundle to include all child bundle assets.

It might be possible with some kind of manifest - so child should create manifest of his assets.
Main bundle should load all child assets by his manifest.

Couldn't find such plugin, maybe there is one you know guys ?

**Comment by zd819** [comment]
Has this been fixed yet? It keeps saying ChunkLoadError: Loading chunk 'X' failed, in my consuming app (_Project B_). 

I have used **CopyPlugin** so that the Project A chunk files are present in Project B build folder, but it sill says:
```
ChunkLoadError: Loading chunk vendors-node_modules_crypto-js_sha256_js failed.
```

**Comment by alexander-akait** [comment]
@zd819 Hello, please provide reproducible test repo?

**Comment by shashank-brightness** [comment]
Any idea why this was closed? I am facing similar problem and posted [here](https://github.com/webpack/webpack/discussions/18318).

The main issue is that it tries to do another request. We need something same as inline import works by taking chunk from within same file but only difference is that it should work by considering relative paths and not dependent or using Project A/Project B url's. I am not sure if it is even possible or not. 

Copy plugin in Project B (which in my case was with laravel-mix) is there but not viable solution. Why consumer has to first copy every chunk just to get the package working?

Also, as @vankop highlights, if we use source files then it works as webpack first publishes to project B's publicPath but one does not want to use source file as he/she needs to compile package on their own and not using bundler of project B. Not to mention that Project B could have even different bundler as well and not webpack.

If needed i can provide simple test repo to reproduce this behavior.

**Comment by Shashank-Bhatt1** [comment]
Any idea why this was closed? I am facing similar problem.

The main issue is that it tries to do another request. We need something same as how inline import works by taking chunk from within same file but only difference is that it should work by considering relative paths and not dependent or using Project A/Project B url's. Chunk should be of course in different file as it is now. I am not sure if it is even possible or not.

Copy plugin in Project B (which in my case was with laravel-mix) is there but not viable solution. Why consumer has to first copy every chunk just to get the package working?

Also, as @vankop highlights, if we use source files then it works as webpack first publishes to project B's publicPath but one does not want to use source file as he/she needs to compile package on their own and not using bundler of project B. Not to mention that Project B could have even different bundler as well and not webpack.

If needed, i can provide simple test repo to reproduce this behavior.

**Comment by alexander-akait** [comment]
@Shashank-Bhatt1 

> If needed, i can provide simple test repo to reproduce this behavior.

Please do it
