### ISSUE TITLE
custom dev server question

### ISSUE THREAD

**Issue by darul75** [webpack/webpack#1073]
hi @sokra and others,

* In dev mode with just a client need, a webpack client config and a webpack-dev-server fits my need.
* In production mode, a webpack config for both client and server fits my need.

But in dev mode with a need for a custom server, it starts to be tricky. I want to be able to debug my server side with custom api routes...get hot loading on client side and why not hot loading on server side too (NodeJS)

I have done the following:

- based on this documentation and "existing server" section http://webpack.github.io/docs/webpack-dev-server.html
- my client side is packed with webpack and template generated by my express server targeting my client bundle. ok for this part.
- but using react my express server is rendering react and not aware of changes in hot mode ?

Do I need to webpack my server also ?

I mean when changes are made, my client side is aware of it and reload everything, but on server side nothing is rebundle and node not restarted too.. (normal). One common case is when I change something on a react component, when rerendering I got normal warning about 'you client/server are not rendering same component..." as my server is not changing anything in in logic to render react "previous" component.

Not sure I am clear but it is to open the discussion ;)

https://github.com/darul75/web-react

**Comment by sokra** [comment]
> why not hot loading on server side too

You can do that with `target: "node"` and `webpack/hot/signal`. A bit of tooling is missing here, but it's doable.

**Comment by darul75** [comment]
Thanks for replying and giving me hope. Is it something line enhance my server bundle with a signal patch, any examples ?

**Comment by sokra** [comment]
The HMR works because of the HotModuleReplacementPlugin. `webpack/hot/signal` is just a little helper which checks for updates on process signal like `SIGUSR2`. You can see the source [here](https://github.com/webpack/webpack/blob/master/hot/signal.js). There is also `webpack/hot/poll?1000` which polls for updates. That's a good start.

**Comment by darul75** [comment]
ok nice I will check and come back to you then, it is so dense webpack, amazing stuff inside

**Comment by darul75** [comment]
I have updated the server config to handle signal, I know I need to figure out more about how all this is working but could you confirm this workflow:

- first script start both client and server webpack config with a webpack-dev-server running on port 8081.

```
webpack --config conf/webpack-dev-server.js | webpack-dev-server --port 8081 --config conf/webpack-dev-server.js --hot --history-api-fallback --progress --colors --inline --content-base ./build
```

it produces an app.js client file  and server.js for server.

- second simply run following command

```
node server.js
```

When changes occured, client and server are re-bundled, but I do not know how to self patch nodejs  process.

Do I need to use nodemon and that kind of glue ?

Thx

**Comment by sokra** [comment]
* compile the server bundle with `target: "node"`
* enable records by providing a [`recordsPath`](http://webpack.github.io/docs/configuration.html#recordspath-recordsinputpath-recordsoutputpath).
* add `webpack/hot/poll?1000` to the server entry point, this checks for updates every second.
* The server process prints to stdout when it updates itself.
* No need to nodemon. Just native node.js process.

**Comment by sokra** [comment]
After the second compilation there should be hot update files in the output directory.

The process logs something similar to this:

```
[HMR] Updated modules:
[HMR]  - ...
[HMR] Update applied.
```

**Comment by darul75** [comment]
I keep you in touch, it looks great, your documentation is pretty good but sometimes very low level

**Comment by darul75** [comment]
server config extract is :

```
    // plugins.push(new webpack.HotModuleReplacementPlugin());


    {
      entry: [
        './server/server'
        'webpack/hot/poll?1000'
      ],
       output: {
        path: './build/',
        filename: 'server.js',
        libraryTarget: 'commonjs2',
        publicPath: '/'
      },
      recordsPath = path.resolve(__dirname, ''build/webpack.records.json');
      target: 'node',
      externals: /^[a-z][a-z\.\-0-9]*$/,
      node: {
        console: false,
        global: false,
        process: false,
        Buffer: false,
        __filename: true,
        __dirname: true
      },
      module : {
        loaders: [
          { test: /\.js$/, exclude: /node_modules/, loader: 'babel-loader'},
          { test: /\.jsx?$/, loaders: ['babel'], exclude: /node_modules/ },
          { test: /\.(jpe?g|png|gif|svg|woff|eot|ttf)$/, loader: 'url?limit=10000&name=[sha512:hash:base64:7].[ext]' },
          { test: /\.sass$/, loader: sassLoaders },
          { test: /\.css$/, loader: cssLoaders },
          { test: /\.scss$/, loader: cssLoaders }
        ]
      },
      plugins: plugins
    }
```

in server.js generated I see something like 'hot-update.json'

do I need to rename my recordsPath file according to this name ?

**Comment by darul75** [comment]
here is a sample output from client webpack-dev-server listening too:

```
    Time: 2391ms
                                   Asset      Size  Chunks             Chunk Nam
es
                               server.js   87.7 kB       0  [emitted]  main
    0.30bce14756866dc22941.hot-update.js   4.54 kB    0, 0  [emitted]  main, mai
n
    30bce14756866dc22941.hot-update.json  36 bytes          [emitted]
    chunk    {0} server.js, 0.30bce14756866dc22941.hot-update.js, 0.30bce1475686
6dc22941.hot-update.js (main) 54.4 kB [rendered]
        [1] ./app/components/HomeSection/HomeSection.jsx 4.1 kB {0} [built]
         + 42 hidden modules`

```

**Comment by darul75** [comment]
Hot files are not dumped into mu build folder, just the recordPaths json file

**Comment by darul75** [comment]
Now hot files are *dumped* into build folder, output path was not absolute my mistake, but it is still not live patching node process.

webpack is in a sub 'conf' folder

```
var publicPath = 'http://127.0.0.1:8081/';
var server = path.resolve(__dirname, '..', 'server', 'server-dev'); // my express server code server-dev.js
var out = path.resolve(__dirname, '..', 'build'; // build output folder
var plugins = [];

var entry = [server];
config.recordsPath = path.resolve(__dirname, '..', 'build/webpack.records.json');
    
plugins.push(new webpack.HotModuleReplacementPlugin());
// above 2 entries I have tried
//entry.push('webpack/hot/signal.js');
entry.push('webpack/hot/poll?1000');

and my config:
{
      entry: entry,
       output: {
        path: out,
        filename: 'server.js',
        libraryTarget: 'commonjs2',
        publicPath: publicPath
      },
      target: 'node',
      externals: /^[a-z][a-z\.\-0-9]*$/,
      node: {
        console: false,
        global: false,
        process: false,
        Buffer: false,
        __filename: true,
        __dirname: true
      },
      module : {
        loaders: [
          { test: /\.js$/, exclude: /node_modules/, loader: 'babel-loader'},
          { test: /\.jsx?$/, loaders: ['react-hot', 'babel'], exclude: /node_modules/ },
          { test: /\.(jpe?g|png|gif|svg|woff|eot|ttf)$/, loader: 'url?limit=10000&name=[sha512:hash:base64:7].[ext]' },
          { test: /\.sass$/, loader: sassLoaders },
          { test: /\.css$/, loader: cssLoaders },
          { test: /\.scss$/, loader: cssLoaders }
        ]
      },
      plugins: plugins
    });
  }
```

I have simplified it : https://github.com/darul75/web-react/blob/master/conf/webpack-config.js

**Comment by darul75** [comment]
What I see is some hot-update files written on fist webpack run command.

```
Child
    Hash: 802cb6fd391d9de1eaab
    Version: webpack 1.9.7
    Time: 7879ms
             Asset       Size  Chunks             Chunk Names
       favicon.ico    1.15 kB          [emitted]  
       V2d-uc_.png      49 kB          [emitted]  
        vendors.js     1.1 MB       0  [emitted]  vendors
            app.js     115 kB       1  [emitted]  app
    index-dev.html  424 bytes          [emitted]  
    chunk    {0} vendors.js (vendors) 962 kB [rendered]
...
Child
    Hash: b4896b8f7de71b3b50a7
    Version: webpack 1.9.7
    Time: 6110ms
                                   Asset      Size  Chunks             Chunk Names
                             favicon.ico   1.15 kB          [emitted]  
                             V2d-uc_.png     49 kB          [emitted]  
                               server.js    387 kB       0  [emitted]  main
    0.4820893926fcd8b8f5e0.hot-update.js   14.3 kB    0, 0  [emitted]  main, main
    4820893926fcd8b8f5e0.hot-update.json  36 bytes          [emitted]  
    chunk    {0} server.js, 0.4820893926fcd8b8f5e0.hot-update.js, 0.4820893926fcd8b8f5e0.hot-update.js (main) 329 kB [rendered]
```

Here both files     0.4820893926fcd8b8f5e0.hot-update.js and     4820893926fcd8b8f5e0.hot-update.json are dumped.

Then if I change a source file, console outputs:

```
Child
    Hash: d4565675eb56dfd86839
    Version: webpack 1.9.7
    Time: 1707ms
                                   Asset       Size  Chunks             Chunk Names
                              vendors.js     1.1 MB       0  [emitted]  vendors
                                  app.js     115 kB       1  [emitted]  app
    1.802cb6fd391d9de1eaab.hot-update.js    5.66 kB       1  [emitted]  app
    802cb6fd391d9de1eaab.hot-update.json   36 bytes          [emitted]  
                          index-dev.html  424 bytes          [emitted]  
    chunk    {0} vendors.js (vendors) 962 kB [rendered]
         + 280 hidden modules
    chunk    {1} app.js, 1.802cb6fd391d9de1eaab.hot-update.js (app) 104 kB {0} [rendered]
      [159] ./app/components/HomeSection/HomeSection.jsx 5.34 kB {1} [built]
         + 31 hidden modules
Child
    Hash: 4b683c54158896c50d89
    Version: webpack 1.9.7
    Time: 409ms
                                   Asset      Size  Chunks             Chunk Names
                               server.js    387 kB       0  [emitted]  main
    0.b4896b8f7de71b3b50a7.hot-update.js   5.62 kB    0, 0  [emitted]  main, main
    b4896b8f7de71b3b50a7.hot-update.json  36 bytes          [emitted]  
    chunk    {0} server.js, 0.b4896b8f7de71b3b50a7.hot-update.js, 0.b4896b8f7de71b3b50a7.hot-update.js (main) 329 kB [rendered]
       [47] ./app/components/HomeSection/HomeSection.jsx 5.34 kB {0} [built]
         + 109 hidden modules
webpack: bundle is now VALID.
```

But no hot-update files an dumped.

**Comment by sokra** [comment]
https://github.com/webpack/hot-node-example

**Comment by darul75** [comment]
Ok i will look at it thank you for providing it so fast.

**Comment by darul75** [comment]
it is working as expected, I was not using webpack while running my node process...so it was not patching anything. I still have some warning and need to finish some work but it is another story. maybe other questions will be coming.
