### ISSUE TITLE
ConcurrentCompilationError if calls `.watch` several times

### ISSUE THREAD

**Issue by srghma** [webpack/webpack#10730]
# Bug report

**What is the current behavior?**

it doesnt throw error if I call register watch once

```js
  var webpack = require('webpack');
  var webpackConfig = require('./webpack.config');
  var compiler = webpack(
    {
      target: 'node',
      mode: 'production',

      output: {
        filename: "output.js",
      },

      entry: './entry.js'
    }
  );

  compiler.watch({
    aggregateTimeout: 300,
    poll: undefined
  }, (err, stats) => {
    if (err) return console.error(err)
    if (!stats.hasErrors()) {
      console.log('1')
    } else {
      console.log('2')
    }
  })
```

```js
# entry.js
console.log('hello from entry.js')
```

it throws error

```
 ✘  ~/projects/webpack-hot-middleware/example   ConcurrentCompilationError ●  node server.js
[20:56:23.785] [ERROR]  ConcurrentCompilationError: You ran Webpack twice. Each instance only supports a single concurrent compilation at a time.
    at Compiler.watch (/home/srghma/projects/webpack-hot-middleware/example/node_modules/webpack/lib/Compiler.js:319:19)
    at /home/srghma/projects/webpack-hot-middleware/example/server.js:54:12
    at Object.<anonymous> (/home/srghma/projects/webpack-hot-middleware/example/server.js:65:3)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
[20:56:23.790] [LOG]    Listening on {"address":"::","family":"IPv6","port":1616}
[20:56:24.205] [LOG]    2

```

if I call `.watch` twice

```js
  var webpack = require('webpack');
  var webpackConfig = require('./webpack.config');
  var compiler = webpack(
    {
      target: 'node',
      mode: 'production',

      output: {
        filename: "output.js",
      },

      entry: './entry.js'
    }
  );

  compiler.watch({
    aggregateTimeout: 300,
    poll: undefined
  }, (err, stats) => {
    if (err) return console.error(err)
    if (!stats.hasErrors()) {
      console.log('1')
    } else {
      console.log('2')
    }
  })

  compiler.watch({
    aggregateTimeout: 300,
    poll: undefined
  }, (err, stats) => {
    if (err) return console.error(err)
    if (!stats.hasErrors()) {
      console.log('3')
    } else {
      console.log('4')
    }
  })
```

**What is the expected behavior?**

I can register `.watch` as much as I want

this is especially annoying when using `webpack-dev-middleware`, I cannot register new watch because there is already watch registered

https://github.com/webpack/webpack-dev-middleware/blob/e400f57a0c577fa543a7b716ed2bed7c1d5adceb/src/index.js#L60 

**Other relevant information:**
webpack version:  5.0.0-beta.13 and 4
Node.js version: v13.8.0
Operating System: linux
Additional tools: none

**Comment by evilebottnawi** [comment]
Because you can run webpack twice, you should use:
```js
compiler.watch(options, (err, stats) => {
  compiler.watch(options, (err, stats) => {});
})
```

**Comment by evilebottnawi** [comment]
> this is especially annoying when using webpack-dev-middleware, I cannot register new watch because there is already watch registered

Please provide full configuration

**Comment by srghma** [comment]
@evilebottnawi updated

**Comment by sokra** [comment]
The error says: You can't call `watch` twice. Don't do that. After the first watch it's already watching, why do you want to call it twice...

**Comment by srghma** [comment]
Because I think this example https://github.com/alexmingoia/pux-starter-app/blob/f29ac097dbfca9ac36805e1b50ce4568afc2fb0e/webpack.config.client.js#L117 was working with old versions of webpack-dev-middleware

(Now I have to use https://github.com/webpack/webpack-dev-middleware#waituntilvalidcallback )

But why shouldn't I be able to register several watchers

**Comment by sokra** [comment]
`watch` doesn't register a watcher callback. It starts watching of the Compiler. It was never working correctly only the error message is new. You can attach additional listeners when the build is done with `compiler.hooks.done.tap("YourPlugin", stats => {})`

**Comment by srghma** [comment]
This is ok for me too, thx )
