### ISSUE TITLE
Safari 7.1 throws error: Unexpected token '='. Expected a ')' or a ',' after a parameter declaration

### ISSUE THREAD

**Issue by digitalcortex** [webpack/webpack#10733]
# Bug report

**What is the current behavior?**
OS X Mavericks Safari 7.1 throws `Unexpected token '='. Expected a ')' or a ',' after a parameter declaration` pointing at line `window["webpackJsonp"] = window["webpackJsonp"] || []` after loading the JS bundle packaged by Webpack.

**If the current behavior is a bug, please provide the steps to reproduce.**
`window["webpackJsonp"] = window["webpackJsonp"] || []` line is
included in every build made with default Vue CLI setup. Reproducible.

**What is the expected behavior?**
Application bundle is correctly executed by Safari browser.

**Other relevant information:**
webpack version: 4.42.1
Node.js version: 13.12.0
Operating System: macOS Mojave 10.14.6
Additional tools: Vue CLI

Screenshots attached below (Safari 7.1):
![2020-04-18 12 55 58](https://user-images.githubusercontent.com/62620810/79633031-f59ab380-8173-11ea-8292-da8e186a4bfd.jpg)
![2020-04-18 12 56 08](https://user-images.githubusercontent.com/62620810/79633034-fcc1c180-8173-11ea-85bb-94f828b68104.jpg)

If it is expected behaviour, how can we solve the issue?

**Comment by evilebottnawi** [comment]
Safari 7.1 is outdated and doesn't supported

**Comment by digitalcortex** [comment]
> Safari 7.1 is outdated and doesn't supported
Is there no way for a workaround? Some of my user base is facing blank screen because of that.

**Comment by evilebottnawi** [comment]
No workarounds, it is old browser, you can show message about updating browser
