### ISSUE TITLE
Hot Reloading when manually triggering multiple builds with compiler.run

### ISSUE THREAD

**Issue by romeovs** [webpack/webpack#10745]
## Feature request

I'm putting together a tool that uses Webpack as part of a build system. I've got the static builds to work and am working on dev builds with hot module reloading now.

Because the Webpack build relies on previous build steps, I cannot simple uses `compiler.watch` to watch for changed files. Instead, I'm relying on sequential calls to `compiler.run`.
This seems to work and the builds feel incremental (rebuilds are speedy). The HMR plugin seems to even pick up that a rebuild is taking place and logs this in the browser console.

There's one issue however: `HotModuleReplacementPlugin` is not emitting `hot-update.json` files because it thinks every build is the "first" build.

Is there a way to make `HotModuleReplacementPlugin` to realise that subsequent calls to `compiler.run` should be emitting `hot-update.json` files?

**What is motivation or use case for adding/changing the behavior?**
I'm building a tool that needs `webpack --watch`-like behaviour, but also needs to coordinate the Webpack build with other build steps.

**How should this be implemented in your opinion?**
Not entirely sure what the right way to do this is. AFAICT, `HotModuleReplacementPlugin` uses some heuristics to determine wether or not to output the `hot-update.json` files. An extra option to override that heuristic might be nice.

OTOH, I'm not even sure if sequentially calling `compiler.run` is the right way to go with this. Any other tips on how to coordinate `compiler.watch` builds with build steps that happen outside of Webpack are welcome too!

**Are you willing to work on this yourself?**
yes

**Comment by romeovs** [comment]
Any news on this?

**Comment by sokra** [comment]
Sounds like a bug in the HMR plugin. I think it should better check if there is info about the last build in records to determine if a HMR update should be emitted.
