### ISSUE TITLE
Changelog missing for 1.9 releases

### ISSUE THREAD

**Issue by kpdecker** [webpack/webpack#1074]
http://webpack.github.io/docs/changelog.html is missing changes for 1.9 releases.

**Comment by bebraw** [comment]
See https://github.com/webpack/docs/wiki/changelog .

I tried http at incognito mode (no cache) and it gave me the same result as the wiki (1.9 included). https yields older pages, though.

**Comment by kpdecker** [comment]
Looks like this has been updated.
