### ISSUE TITLE
how can i setting omit the window object

### ISSUE THREAD

**Issue by wjhcc2018** [webpack/webpack#10743]
error code:
```js
let num = Number(1.2)
```
when build,it's report an error "r is not a  function"

right code:
```js
let num = window.Number(1.2)
```

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
