### ISSUE TITLE
module.hot.decline fails to parse module name

### ISSUE THREAD

**Issue by kpdecker** [webpack/webpack#1075]
https://github.com/webpack/webpack/blob/master/lib/HotModuleReplacementPlugin.js#L199 is looking for two arguments and otherwise it leaves the module id unaltered. This causes the module to be not be declined as the moduleId check is expecting an internal module id:
https://github.com/webpack/webpack/blob/master/lib/HotModuleReplacement.runtime.js#L253

From the [docs](http://webpack.github.io/docs/hot-module-replacement.html#decline) it also looks like this function fails in the same way for array entry types.

**Comment by kpdecker** [comment]
Is there test coverage for this or desire to have it? I actually found this when writing tests for the circus plugin to support hot update (code to be pushed to public location soon). Glad to submit a PR for that if there's desire and the cost (usually about 1s a test case due to phantom spin up, etc) is acceptable.

**Comment by sokra** [comment]
Actually I would like to have tests for HMR, but it's a bit work to write them. You don't need phantom for this, as HMR also works in node.js. It's propably the best to setup the HMR test infrastructure by my own. Than you can submit PRs for test cases.

If you are looking for some other places to write tests: https://coveralls.io/r/webpack/webpack has a good list...
