### ISSUE TITLE
webpack 4 -> 5 : several typescript issues

### ISSUE THREAD

**Issue by rvion** [webpack/webpack#10757]
# Bug report

webpack version:  beta 15
Node.js version: 10.xxx
Operating System: windows

### 2. ResolveOptions is not exported

![image](https://user-images.githubusercontent.com/2150990/79935141-713a8000-8454-11ea-9954-38e12b577995.png)
fix: 
export them at the end of the file ![image](https://user-images.githubusercontent.com/2150990/79935707-df337700-8455-11ea-9ec9-f3c5bd9ed06a.png)

### 3. EntryObject is wrong

```
type Entry =
	| string
	| (() => string | EntryObject | [string, string] | Promise<EntryStatic>)
	| EntryObject
	| [string, string];
declare interface EntryObject {
	[index: string]: string | [string, string] | EntryDescription;
}
```
but doc says here :  https://webpack.js.org/configuration/entry-context/#dependencies
```
module.exports = {
  //...
  entry: {
    app: { import: './app.js', dependOn: 'react-vendors' },
    'react-vendors': ['react', 'react-dom', 'prop-types']
  }
};
```
which triggers a typescript error
there should be some `| string[]` somewhere

### 4. no migration Guide 

(bug found in some code I maintain)
    - `... extends CompilationHooks` -> `... extends CompilationHooksJavascriptModulesPlugin`
    - `compilation.Chunk`->`Chunk`
    - `compilation.Compilation`->`Compilation`
    - `Module` -> `ModuleOptions`
    - `Resolve` -> `ResolveOptions`

**Comment by ryanelian** [comment]
I'm happy that webpack 5 has its own generated types. 

However I used these types from webpack (back when using `@types/webpack` 4), how to make this work with webpack 5 beta 15? All these types are now missing when installing the new package:

```ts
import webpack = require('webpack');

webpack.RuleSetRule

webpack.RuleSetLoader

webpack.Plugin

webpack.Output

webpack.Resolve

webpack.Options.Optimization

webpack.Stats.ToJsonOutput

webpack.loader.LoaderContext
```

**Comment by evilebottnawi** [comment]
@rvion Do you use `@types/webpack`? Because yes, webpack now provide own types

**Comment by ryanelian** [comment]
While we're at it, can we have a new publish of webpack-dev-server which accepts the webpack 5 generated types?

Let's say a version 4 beta of webpack-dev-server which depends on webpack 5 instead of `@types/webpack`, because this is also happening in my project:

![image](https://user-images.githubusercontent.com/8892187/80125071-59c9d700-85bb-11ea-9e4b-a3b4de685686.png)

**Comment by rvion** [comment]
@evilebottnawi I was using webpack own types when I opened the issue
@ryanelian some types have been renamed (e.g. Resolve  => ResolveOptions)
some types are not exported in beta15 (e.g. ResolveOptions). With beta 15, you need to manually edit they libdef file and add missing exports at the bottom

**Comment by evilebottnawi** [comment]
@rvion What is missign?

**Comment by rvion** [comment]
@evilebottnawi  Sorry, my response was a bit late.
I didn't notive sokra alrady pushed some changes when I replied 3 hours ago.
I was responding to your initial question here: https://github.com/webpack/webpack/issues/10757#issuecomment-618500848

I don't know what is now missing on master after his recent commits, I switched back to using webpack 4 because of https://github.com/webpack/webpack/issues/9802#issuecomment-601911417 and don't have the time to check right now.

thanks anyway for the quick support !

**Comment by evilebottnawi** [comment]
@rvion Thanks for the link, WIP on this

**Comment by artem-malko** [comment]
@evilebottnawi 
> What is missing in master?

I've not found Loader type and LoaderContext. So, it's quite difficult to write own loader with typescript using webpack beta 15 right now.

**Comment by chenxsan** [comment]
@artem-malko Can you `import type {TheOneYouWant} from 'webpack/declarations/WebpackOptions'`?

**Comment by artem-malko** [comment]
@chenxsan 
Loader from `webpack/declarations/WebpackOptions`
```typescript
export interface Loader {
	[k: string]: any;
}
```

Loader from `@types/webpack`
```typescript
interface Loader extends Function {
            (this: LoaderContext, source: string | Buffer, sourceMap?: RawSourceMap): string | Buffer | void | undefined;

            /**
             * The order of chained loaders are always called from right to left.
             * But, in some cases, loaders do not care about the results of the previous loader or the resource.
             * They only care for metadata. The pitch method on the loaders is called from left to right before the loaders are called (from right to left).
             * If a loader delivers a result in the pitch method the process turns around and skips the remaining loaders,
             * continuing with the calls to the more left loaders. data can be passed between pitch and normal call.
             */
            pitch?(remainingRequest: string, precedingRequest: string, data: any): any;

            /**
             * By default, the resource file is treated as utf-8 string and passed as String to the loader.
             * By setting raw to true the loader is passed the raw Buffer.
             * Every loader is allowed to deliver its result as String or as Buffer.
             * The compiler converts them between loaders.
             */
            raw?: boolean;
        }
```

Quite big difference)

**Comment by evilebottnawi** [comment]
@artem-malko Let's open a new issue about improving types

**Comment by artem-malko** [comment]
@evilebottnawi ok)

**Comment by Izhaki** [comment]
In 5, what replaces:

```
import { Plugin } from 'webpack';
```

Because for the code above I get:

```
/webpack-5-ts/node_modules/webpack/types"' declares 'Plugin' locally, but it is not exported.
```

There are additional 30 errors, 29 of which are:

```
node_modules/schema-utils/declarations/validate.d.ts:2:34 - error TS2307: Cannot find module 'json-schema'.

2 export type JSONSchema4 = import('json-schema').JSONSchema4;
```

And the other one is:

```
node_modules/webpack/types.d.ts:62:8 - error TS2307: Cannot find module 'estree'.

62 } from "estree";
```

# To reproduce

package.json:
```json
{
  "license": "MIT",
  "scripts": {
    "build": "tsc example.ts"
  },
  "devDependencies": {
    "@types/node": "^13.13.5",
    "nodemon-webpack-plugin": "^4.3.1",
    "typescript": "^3.8.3",
    "webpack": "5.0.0-beta.16"
  }
}
```

example.ts:
```js
import NodemonPlugin from "nodemon-webpack-plugin";
```

Then:
```
yarn build
```

No errors if I remove [this line](https://github.com/Izhaki/nodemon-webpack-plugin/blob/master/src/index.d.ts#L3):

```
import { Plugin } from 'webpack';
```

**Comment by artem-malko** [comment]
There is a temp solutions, who want use webpack beta 15 and higher and rich typings from @types/webpack:
tsconfig.json
```json
"compilerOptions": {
    "paths": {
      "webpack": ["./node_modules/@types/webpack/index.d.ts"],
    },
}
```

**Comment by evilebottnawi** [comment]
@artem-malko What types are missing?

**Comment by evilebottnawi** [comment]
@Izhaki `schema-utils` will be fixed today

**Comment by evilebottnawi** [comment]
@sokra look like same problem with `estree`

**Comment by artem-malko** [comment]
@evilebottnawi https://github.com/webpack/webpack/issues/10828 for example)

**Comment by Izhaki** [comment]
Sorry to revive the discussion here, but the question remains:

In 5, what replaces:

```
import { Plugin } from 'webpack';
```

?

Latests [types.d.ts](https://github.com/webpack/webpack/blob/v5.13.0/types.d.ts) does not export a `Plugin` definition. So not quite sure how to support both webpack 4 and 5 in my [plugin's type definition](https://github.com/Izhaki/nodemon-webpack-plugin/issues/118)

**Comment by Izhaki** [comment]
More of a note to self: html-webpack-plugin does not import the type from webpack, rather it [declares its own](https://github.com/jantimon/html-webpack-plugin/blob/3768bbabb7bfc19487f94841f0e7d4900bca7110/typings.d.ts).

**Comment by alexander-akait** [comment]
https://github.com/webpack/webpack/blob/v5.13.0/types.d.ts#L10473, not sure you can have types for webpack@4 and webpack@5 without problems, because it is breaking change
