### ISSUE TITLE
feature idea: format output bundle's internal modules as ES Modules inside data URLs?

### ISSUE THREAD

**Issue by trusktr** [webpack/webpack#10777]
## Feature request (idea)

**What is the expected behavior?**

Similar to the `eval` format where modules inside an output bundle are executed with `eval` (they are strings), this would format the internal modules as actual ES Modules, and save them as `data:` URLs inside the bundle. Each module would import other modules by data URL, therefore loading each other using native ES Modules in the browser.

The bundle itself would also be an ES Module. It would import the first module by data URL, and so on down the dependency tree.

**What is motivation or use case for adding/changing the behavior?**

I thought it would be neat. It would exercise the native ES Module machinery, making sure code is compatible with it.

Is it better than regular bundling though? I'm not sure.

But at least it would work the native module way without any possible deviances, guaranteeing code is compatible with native ES Modules.

It could also then be possible (if Webpack ever changed some of its design goals) for Webpack to output each file separately as individual ES Modules.

I don't really know if this is ultimately better (other than modules working exactly as designed in browsers). Many people would gauge "better" as being faster.

**How should this be implemented in your opinion?**

^

**Are you willing to work on this yourself?**
No time for it. I wish!

**Comment by evilebottnawi** [comment]
@trusktr What is real use case?
