### ISSUE TITLE
Issue with a WebWorker in a Blob()

### ISSUE THREAD

**Issue by kalwalt** [webpack/webpack#10778]
# Bug report

**What is the current behavior?**

I am developing a little lib for AR: [**ARnft**](https://github.com/kalwalt/ARnft) all goes well in development mode but when i run in production with `webpack --mode production --optimize-minimize` the code fails with this error: 
`05ff8846-4121-4380-86c3-9612f404732a:1 Uncaught SyntaxError: Function statements require a function name`
that error point to the Blob worker at this line https://github.com/kalwalt/ARnft/blob/159673892584d3ccb396bebb6410ddb700bb55ca/src/utils/Utils.js#L272 it seems that webpack remove the name of the function   **`workerRunner`** and this cause to hang and not procede.
I defined my workerRunner in this way:

```javascript
const workerRunner = () => {
// code of the worker
}
```

and is injected in a Blob:

```javascript
// create a Worker to handle loading of NFT marker and tracking of it
const workerBlob = new Blob(
    [workerRunner.toString().replace(/^function .+\{?|\}$/g, '')],
     { type: 'text/js-worker' }
  )
  const workerBlobUrl = URL.createObjectURL(workerBlob)

  worker = new Worker(workerBlobUrl)
```

Instead if i run `webpack --mode production --optimize-minimize -d` the code works, and it enter in the WebWorker.

**If the current behavior is a bug, please provide the steps to reproduce.**

run in production mode my repository with `webpack --mode production --optimize-minimize`

**What is the expected behavior?**
It is expected that the code minified, may enter in the Worker function.

**Other relevant information:**
webpack version:  4.42.1
Node.js version: v13.8.0
Operating System:  Ubuntu 18.04 LTS
Additional tools: Babel 7.9.0

i have also submitted a question in [stackoverflow](https://stackoverflow.com/questions/61411261/issue-with-webpack-in-production-mode-minification-issue), suggested to post an issue here, because maybe is a bug.

Thanks for the attention,
Walter

**Comment by sokra** [comment]
That's a usual optimization that happens during minimizing. You should not rely on function names.

You could disable this behavior by passing custom options to terser with the `optimization.minimizer` option, but it makes more sense to write your code in a way that it doesn't rely on function names.

**Comment by kalwalt** [comment]
Thank you @sokra i tried the optimization.minimizer with keep_fnames:

```js
optimization: {
    minimizer: [
      new TerserPlugin({
        terserOptions: {
          keep_fnames: true
        }
      })
    ]
  },
```

and `webpack --mode production` but now the app hang not entering in the WebWorker and in the console the webWorker is empty. I think i need to change my code.

**Comment by kalwalt** [comment]
I discovered there is a module [worker-loader](https://github.com/webpack-contrib/worker-loader) that maybe can simplify and avoid this issue. I will let you know. Thanks in advance. :slightly_smiling_face:

**Comment by kalwalt** [comment]
I solved using the **worker-loader**, it worked perfectly! See my commit https://github.com/kalwalt/ARnft/commit/6f95c6476f7e0cdcd41220dbb1c83cab813e0205 
This issue is not a bug. My fault because my limited knowledge on webpack.
