### ISSUE TITLE
webpack build error in travis

### ISSUE THREAD

**Issue by chnliquan** [webpack/webpack#10787]
# Bug report

**What is the current behavior?**
I use storybook in react-create-app, it works fine when run `build-storybook -s public` in local envirment, but it not works in travis, the error is 

```
<s> [webpack.Progress] 70% building 1549/1549 modules 0 active 
<s> [webpack.Progress] 70% building 1549/1550 modules 1 active /home/travis/build/chnliquan/iron/node_modules/xtend/immutable.js
<s> [webpack.Progress] 70% building 1550/1550 modules 0 active 
```

it stoped here, i can not figure out

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  cra 4.7.2 storybook 4.33, i add SKIP_PREFLIGHT_CHECK=true in .env
Node.js version: 12.0.0
Operating System: OS
Additional tools:

**Comment by evilebottnawi** [comment]
Please open an issue in `storybook` repo
