### ISSUE TITLE
webpack 5: '.wasm' is missing loader

### ISSUE THREAD

**Issue by eisenhaus335** [webpack/webpack#10788]
# Bug report
webpack 5 is missing '.wasm' loader shown in this console report
![image](https://user-images.githubusercontent.com/25275731/80351400-75273180-889c-11ea-983f-b209a3928db7.png)

**What is the current behavior?**
webpack 4 do just fine parse the wasm but somehow webpack 5 unable to parse '.wasm' because missing loader

**If the current behavior is a bug, please provide the steps to reproduce.**
run the `yarn start` and press the "click me" its will show the error in inspector. i using the webpack 5 

**What is the expected behavior?**

https://github.com/eisenhaus335/wasm-showcase
**Other relevant information:**
webpack version: 5.0.0-beta.13 
Node.js version: v12.6.1
Operating System: Ubuntu 19.10
Additional tools: yarn

**Comment by evilebottnawi** [comment]
Can you create reproducible test rero, seems wasm code is broken

**Comment by eisenhaus335** [comment]
https://github.com/eisenhaus335/wasm-showcase
sorry forgot to add the code

**Comment by evilebottnawi** [comment]
Try:
```
experiments: {
        asyncWebAssembly: true,
        syncWebAssembly: true
    },
```

`wasm` is experimental by default, this will allow us to fix more errors without major releases

**Comment by Pauan** [comment]
@evilebottnawi Webpack 5 completely breaks all uses of `.wasm` (which worked fine with Webpack 4). Where is this breaking change mentioned?

**Comment by evilebottnawi** [comment]
@Pauan 

> Webpack 5 completely breaks all uses of .wasm

Where? You just need to change configuration 

https://github.com/webpack/changelog-v5

**Comment by Pauan** [comment]
@evilebottnawi Got it, thanks!

**Comment by evilebottnawi** [comment]
Yes, i think we should improve an error message

/cc @sokra

**Comment by eisenhaus335** [comment]
enabling the experiments syncwasm is working thanks :D 

sadly new issue popping up. this happend when i only use "asyncWasm" and both enabling "asyncWasm" and "syncWasm". this might issue for wasm-bindgen side. the "syncWasm" working great but for "asyncWasm is not"

![image](https://user-images.githubusercontent.com/25275731/80440116-3e035f80-8932-11ea-9269-6b1319ce010c.png)

**Comment by sokra** [comment]
Sounds like a circular dependency thing. As far as I remember the new spec changes behavior for circular dependencies. It could be that the format wasm-bindgen generates is not compatible with the new spec. I'll check that...

**Comment by sokra** [comment]
Ok two changes were needed to make it work.

1. You need to enable `experiments.importAsync: true`, to allow importing wasm as they are async modules. We should add an error when missing out this flag. Or maybe remove the flag at all and enable this by default.

2. `pkg/index.js` and `pkg/index_bg.wasm` form a circular dependency. The new spec snapshots all imports on execution. `pkg/index_bg.wasm` executes first. `pkg/index.js` defines a `export const __wbg_alert_e4f89deb17f7e8ca = function(...)`. So `__wbg_alert_e4f89deb17f7e8ca` is in TDZ during execution of the wasm resulting in this error. Manually changing it to `export function __wbg_alert_e4f89deb17f7e8ca(...)` fixes the TDZ problem. This requires a fix in wasm-bindgen. (Note the old spec used to use live-bindings instead). 

Not sure who is responsible for wasm-bindgen maybe @alexcrichton

**Comment by Pauan** [comment]
@sokra The fix is here: https://github.com/rustwasm/wasm-bindgen/pull/2110

**Comment by evilebottnawi** [comment]
@Pauan Can we close?

**Comment by Pauan** [comment]
@evilebottnawi Yes, sorry, this has been fixed on wasm-bindgen's side, so `asyncWebAssembly` works now.
