### ISSUE TITLE
Module building fails with using node-interface for building web-project

### ISSUE THREAD

**Issue by ararati** [webpack/webpack#10780]
# Bug report

I use the electron-app for building web project with using [node-interface](https://webpack.js.org/api/node/) for webpack.
Errors appear after include the babel-loader to [webpack.config](https://github.com/ararati/webpack-api-node-issue/blob/master/project1/webpack.buildExternal.js#L13)

**What is the current behavior?**
```
Uncaught (in promise) TypeError: Cannot read property 'default' of undefined
    at eval (loadLoader.js:6)

./src/main.js↵Module build failed (from ./node_modules/babel-loader/lib/index.js)
  Error: Cannot find module 'D:\WebpackTest\project2\node_modules\babel-loader\lib\index.js'
```

**If the current behavior is a bug, please provide the steps to reproduce.**
I created the repository to reproduce an error: [repository](https://github.com/ararati/webpack-api-node-issue)

**Other relevant information:**
webpack version:  4.43.0
Node.js version: 12.16.2
Operating System: Windows 10 x64
Additional tools: npm 6.14.4

Thanks for your help.

**Comment by evilebottnawi** [comment]
Looks problem in `babel-loader`, you can read it your error mssage

**Comment by ararati** [comment]
@evilebottnawi, Thanks for the answer, but I get the same error for the url-loader

**Comment by sokra** [comment]
You bundled webpack with webpack, but the bundle doesn't include the loaders.

**Comment by ararati** [comment]
@sokra, Thanks for answer, do you mean that [project1 ](https://github.com/ararati/webpack-api-node-issue/tree/master/project1)should include the `babel-loader`? 
If so, I installed the `babel-loader` to `project1` but I get the same error.
Can you give more information about it?
