### ISSUE TITLE
ModuleConcatenation bailout: Module is referenced from these modules with unsupported syntax

### ISSUE THREAD

**Issue by isekaimaou1109** [webpack/webpack#10791]
I just edit output config as below: 
```javascript
module.exports = {
   output: {
       pathinfo: false
   }
}
```
it will disappear the messege. and it work correctly

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
