### ISSUE TITLE
How to handle new version deployement for Docker webpack application that use code splitting?

### ISSUE THREAD

**Issue by kopax** [webpack/webpack#10792]
# Bug report

**What is the current behavior?**

After deploying a new version of my application **in Docker**, 

I see my `console` having the following error that **break my application**:

    Uncaught SyntaxError: Unexpected token '<'

[![error when webpack chunk is missing][1]][1]

  [1]: https://i.stack.imgur.com/0Mzis.png

In this screenshot, the source that is missing is called: `10.bbfbcd9d.chunk.js`, the content of this file looks like:

```js
(this.webpackJsonp=this.webpackJsonp||[]).push([[10],{1062:function(e,t,n){"use strict";var r=n(182);n.d(t,"a",(function(){return r.a}))},1063:function(e,t,n){var ...{source:Z[De],resizeMode:"cover",style:[Y.fixed,{zIndex:-1}]})))}))}}]);
//# sourceMappingURL=10.859374a0.chunk.js.map
```

This error happens because :

1. On every release, we build a new `Docker` image that **only** include **chunks from the latest version**
2. Some clients are running an **outdated** version and the server **won't have** a resolution for an **old chunk** because of *(1)*

> Chunks are `.js` file that are produced by `webpack`, see code splitting for [more information](https://webpack.js.org/guides/code-splitting/)

Reloading the application will update the version to latest, but it still breaks the app for all users that use an outdated version.

A possible fix I have tried consisted of refreshing the application. If the requested chunk was missing on the server, I was sending a reload signal if the request for a `.js` file ended up in the wildcard route.
 
> Wild card is serving the `index.html` of the web application, this for delegating routing to client-side routing in case of an user refreshing it's page

```js
// Handles any requests that don't match the ones above
app.get('*', (req, res) => {
  // prevent old version to download a missing old chunk and force application reload
  if (req.url.slice(-3) === '.js') {
    return res.send(`window.location.reload(true)`);
  }
  return res.sendFile(join(__dirname, '../web-build/index.html'));
});
```

This appeared to be a bad fix especially on Google Chrome for Android, I have seen my app being refreshed in an infinite loop. (And yes, that is also an ugly fix!)

Since it's not a reliable solution for my end users, I am looking for another way to reload the application if the user client is outdated.

My web application is build using `webpack`, it's exactly as if it was a `create-react-app` application, the distributed build directory is containing many `.js` chunks files.

These are some possible fix [I got offered on webpack issue tracker](https://github.com/webpack/webpack/issues/10792), some were offered by the webpack creator itself:

 * **Don't remove old builds.** *<= I am building a Docker image so this is a bit challenging*
 * **catch `import()` errors and reload. You can also do it globally by patching `__webpack_load_chunk__` somewhere.** *<= I don't get that patch or where to use `import()`, I am not myself producing those chunks and it's just a production feature*
 * **let the server send `window.location.reload(true)` for not existing js files, but this is a really weird hack.** *<= it makes my application reload in loop on chrome android*
 * **Do not send HTML for `.js` requests, even if they don't exist, this only leads to weird errors** *<= that is not fixing my problem*

How can I implement a solution that would prevent this error?

**If the current behavior is a bug, please provide the steps to reproduce.**

- Just deploy within docker a new version in production and try to access the application using an outdated version. (also, do not keep old chunks when building a new app, as in a CI process deployement)

**What is the expected behavior?**

- User should get the latest version

**Possible fix**

Identify and fix an official workaround and add an explanation within webpack documentation.

**Related issue**

- https://github.com/webpack/webpack/issues/7502

**Other relevant information:**

webpack version:  ^4.43.0
Node.js version: 14
Operating System: alpine

**Comment by evilebottnawi** [comment]
No one knows, please provide reproducible test repo

**Comment by kopax** [comment]
It's hard to give a reproduction for this.

I believe this is due to express serving the `index.html` because the old chunk that is being tried to download is not existing server side.

Probably an express question.

**Comment by kopax** [comment]
It's hard to give a reproduction, as I said, this happens after a new release is happening but this is what I think:

- The application loaded is not the latest version, it is the cached version on the client
  - Is it possible for my express server to force the new version to be sent and refresh the client
- The chunk downloaded is a Webpack chunk, but it does not exist anymore on the server, since the version is different, the chunk is different
  - This result in express returning the default `*` route which is HTML, causing the chunk to be HTML syntax while expecting a JS files, and crashing the application for the end users

How can I tell express to prevent that, and to compare the version used by the client and force the refresh of the web app on the client?

I believe this is common issue with application served by webpack. How can I prevent that?

**Comment by evilebottnawi** [comment]
@kopax Doesn't remove old builds, webpack doesn't do it to avoid this problem, sorry it is webpack bug tracker, not stackoverflow

**Comment by sokra** [comment]
* Don't remove old builds.
* catch `import()` errors and reload. You can also do it globally by patching `__webpack_load_chunk__` somewhere.
* let the server send `window.location.reload()` for not existing js files, but this is a really weird hack.
* Do not send HTML for `.js` requests, even if they don't exist, this only leads to weird errors

**Comment by kopax** [comment]
@evilebottnawi I am aware of that, I just can't find any qualified people while this is somehow really bad for an app that goes to production. Feel free to close my issue if this is not the right place to ask.

I am building a `docker` image upon release, not deleting the old files would be a challenge.

@sokra:

- where should I add that `catch`?
- I am not aware of `_webpack_load_chunk__`, would you mind giving me some resources to understand what you are saying by `patching`
- `window.location.reload` seems to be the easiest solution.
- I agree for not sending html for `.js`, but so far I had no idea on what to do.

**Comment by sokra** [comment]
> * where should I add that `catch`?

``` js
import("./some-module").catch(err => {
  // handle error
});
```

> * I am not aware of `_webpack_load_chunk__`, would you mind giving me some resources to understand what you are saying by `patching`

``` js
const load = __webpack_chunk_load__;
__webpack_chunk_load__ = async chunkId => {
  try {
    return await load(chunkId);
  } catch(err) {
    // handle error globally
  }
}
```

**Comment by kopax** [comment]
> > * where should I add that `catch`?
> 
> ```js
> import("./some-module").catch(err => {
>   // handle error
> });
> ```
> 
> > * I am not aware of `_webpack_load_chunk__`, would you mind giving me some resources to understand what you are saying by `patching`
> 
> ```js
> const load = __webpack_chunk_load__;
> __webpack_chunk_load__ = async chunkId => {
>   try {
>     return await load(chunkId);
>   } catch(err) {
>     // handle error globally
>   }
> }
> ```

Usually, webpack inject the main is file in the index.html , I do not import those file myself in my source code. This lead me to the same question, how can I solve it (for example with expo or create react app)

**Comment by kopax** [comment]
I have tried to do : 

```js
  // Handles any requests that don't match the ones above
  app.get('*', (req, res) => {
    // prevent old version to download a missing old chunk and force application reload
    if (req.url.slice(-3) === '.js') {
      return res.send(`window.reload()`);
    }
    return res.sendFile(join(__dirname, '../web-build/index.html'));
  });
```

How does webpack expect the file to be run afterward ? Will this work ? I am able to test it on next deployment but it would be nice to get some more advices in order for this to work.

**Comment by kopax** [comment]
It's deployed and the reload work like a charm, thank you so much !

**Comment by kopax** [comment]
I am having now an infinite loop when accessing the website from google chrome on android. I have been trying to refresh but that doesn't help. It seems that this bring more side effect than I expected.

I did not understand how I could get behind that issue with the other offered solution.

**Comment by kopax** [comment]
Got many answer on so: https://stackoverflow.com/questions/61479698/after-releasing-a-new-production-version-i-always-get-uncaught-syntaxerror-u

Closing this.
