### ISSUE TITLE
Webpack 5 - Memory Leak

### ISSUE THREAD

**Issue by smparsons** [webpack/webpack#10796]
# Bug report

**What is the current behavior?**

When I make a change in my web app and Webpack compiles, memory usage seems to increase. If I keep making changes and Webpack keeps re-compiling, memory usage will continue to climb. In a large project I work in, it takes about 10 compilations until Webpack crashes with a "Allocation failed - JavaScript heap out of memory" exception.

**If the current behavior is a bug, please provide the steps to reproduce.**

Please see the minimal repo I created to reproduce the issue: https://github.com/smparsons/webpack-memory-leak-issue. The instructions to reproduce are on the README.

**What is the expected behavior?**

I would expect some kind of garbage collection to happen in between compilations.

**Other relevant information:**
webpack version: 5.0.0-beta.15
Node.js version: 11.10.1
Operating System: macOS Catalina Version 10.15
Additional tools:

**Comment by sokra** [comment]
Do not use any kind of hash in the filename during development when using webpack-dev-middleware. Each compilation will create a new file as filename changes. Just like files will pile up on disk, they will pile up in memory as the webpack-dev-middleware stores output files in memory.

**Comment by smparsons** [comment]
Got it. That makes my problem go away during development.

However, I noticed that in my project when I build in production mode (where I am using hash in the filenames), I also get a Javascript heap out of memory error.

I updated my repo with new instructions and some changes so you can reproduce the issue: https://github.com/smparsons/webpack-memory-leak-issue

What I did to sort of "simulate" a large amount of code is created a few files with tons of console log statements. You'll see that "npm run start" works fine but "npm run build" doesn't work.

Let me know if I need to make a new issue and I can do that.

**Comment by sokra** [comment]
It works for me, but it's near the memory limit.

But that it needs a lot of memory is not related to having a memory leak.

For larger builds you need to increase the node memory limit, which is pretty low by default.

**Comment by smparsons** [comment]
Got it. I'll open up another issue if I see anything else. Thanks for the help.

**Comment by joshxyzhimself** [comment]
This one does the trick, right?

```js
{
    output: {
      filename: mode === 'production' ? '[chunkhash].js' : '[name].js',
      chunkFilename: mode === 'production' ? '[chunkhash].js' : '[name].js',
    },
}
```
