### ISSUE TITLE
Production build rise an error in runtime

### ISSUE THREAD

**Issue by inoyakaigor** [webpack/webpack#10806]
# Bug report

**What is the current behavior?**
Minification and concatenating modify code in that way which rise an error in runtime.
Minimal reproduce [repo](https://github.com/inoyakaigor/webpack-dynamic-properties) and it can be seen here https://inoyakaigor.github.io/

**If the current behavior is a bug, please provide the steps to reproduce.**
Open https://inoyakaigor.github.io/, open devtools, reload.

**What is the expected behavior?**
I expect webpack to modify the code so that it will work. I realize that when webpack builds code, it doesn't know what happens at runtime, and I'm not sure that it can be fixed in principle.

**Other relevant information:**
I think this issue relevant to #8902 because the error can be fixed if set to `false` the `optimization.minimize` and `optimization.concatenateModules`

If you after look in code start thinking about circular dependicies or something you also should to know that way to connecting store via the root store described in [Mobx best practices](https://mobx.js.org/best/store.html#combining-multiple-stores)

webpack version:  4.43.0
Node.js version: 14
Operating System: macos 10.14
Additional tools: 
React: 16.13.1
Mobx: 5.15.4
Typescript: 3.8.3

**Comment by sokra** [comment]
Minimizing changes function names due to mangling. Do not rely on function names.

**Comment by inoyakaigor** [comment]
So there is no way to fix it from the webpack?

**Comment by evilebottnawi** [comment]
@inoyakaigor `minimize: { mangle: false }` but it is increase bundle size what is not recommended

**Comment by inoyakaigor** [comment]
I found the solution and described it in [my blog](https://inoyakaigor.ru/blog/97) (in Russian)
