### ISSUE TITLE
output.ecmaVersion should have a smart default based on the browserslist config

### ISSUE THREAD

**Issue by stof** [webpack/webpack#10803]
## Feature request

webpack 5 currently makes `output.ecmaVersion` default to `6`. This can create issues for projects needing to support older browsers like IE 11.
Many projects (including Babel's preset-env) have moved in the direction of relying on a shared browserslist config to avoid duplicating the browser support info. It would be great if webpack could rely this info as well, to select the `output.ecmaVersion` automatically by default

Initially suggested in the beta feedback at https://github.com/webpack/webpack/issues/9802#issuecomment-588896560

**What is the expected behavior?**

**What is motivation or use case for adding/changing the behavior?**

Devs will get a working build by default without even having to know that the `output.ecmaVersion` config setting exists. This goes in the direction of 0-config.

**How should this be implemented in your opinion?**

@vankop and @evilebottnawi have discussed some implementation suggestions in comments following the one I linked above.

**Are you willing to work on this yourself?**
I don't really have time right now, so no guarantee.

**Comment by vankop** [comment]
There is issue on that already https://github.com/webpack/webpack/issues/10507

**Comment by evilebottnawi** [comment]
Yep, let's close it is duplicate and in our roadmap :+1: Don't worry

**Comment by stof** [comment]
Sorry for the duplicate. I missed this issue.
