### ISSUE TITLE
Can't exclude built-in node modules

### ISSUE THREAD

**Issue by yyny** [webpack/webpack#10814]
# Bug report

Built-in node modules will always be preferred over hand-written alternatives, with seemingly no way to change this behavior.

```js
// ./webpack.config.js
const path = require('path');
const webpack = require('webpack');

module.exports = {
  mode: 'production',
  resolve: {
    modules: [path.resolve(__dirname, 'src')],
    // Notice no `node_modules` entry.
    // This will ensure imports will never resolve to `node_modules` in our own codebase.
    // However, it won't prevent webpack from resolving to modules visible to webpack (such as built-in modules and seemingly also modules in ./node_modules/webpack/node_modules).
  }
}
```

```js
// ./src/index.js
import EventEmitter from 'events';

// Do whatever with EventEmitter
```

```js
// ./src/events.js
export class EventEmitter {
  /* Your Web-Safe high-performance EventEmitter implementation here... */
};
```

**What is the expected behavior?**

`import EventEmitter from 'events';` resolves to `./src/events.js`, since it's the only resolvable path specified in the config file.

**What is the actual behaviour?**

The expression resolves to the nodejs built-in `events` module, with seemingly no way to change this behaviour (`modules.Rule.exclude` and `plugins: [require("webpack-node-externals")]` have no effect).

**System info**
webpack version:  4.43.0
Node.js version:  v8.10.0
Operating System: Ubuntu 18.04.4 LTS x86_64

**Comment by sokra** [comment]
See https://webpack.js.org/configuration/node/#node

`node: false`
