### ISSUE TITLE
 TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by Buccerati** [webpack/webpack#10818]
const {RichEmbed} = require("discord.js");
const randomPuppy = require("random-puppy");

module.exports = {
    name:"meme",
    category: "fun",
    discription:"Отправляет ржомбу",
    run: async (client, message, args) => {
        const subReddits = ["dankmeme", "meme", "me_irl"];
        const random = subReddits[Math.floor(Match.random() * subReddits.lenght)];

        const img = await randomPuppy(random);
        const embed = new RichEmbed()
              .setColor("RANDOM")
              .setImag(img)
              .setTitl(`From /r/${random}`)
              .setURL(`https://reddit.com/r/${random}`);

        message.channel.send(embed);
        }
}

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
