### ISSUE TITLE
Firefox complains about "unreachable code after return statement"

### ISSUE THREAD

**Issue by markjaquith** [webpack/webpack#10812]
Firefox adds warnings to my console because of this code:

https://github.com/webpack/webpack/blob/44bcc43fdd3f55a7146558cf3609ec7d381e5400/lib/hmr/HotModuleReplacement.runtime.js#L190-L193

Could be rewritten as:

```javascript
 status: function (l) { 
 	if (l) {
 	 	registeredStatusHandlers.push(l); 
	} else {
		return currentStatus;
 	}
 }, 
```

**Comment by markjaquith** [comment]
Yeah, the code is certainly valid. Firefox is just [issuing a warning](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Stmt_after_return) because of the early return, because in some cases, that could indicate a coding mistake like leaving in an early return for debugging purposes (even though it isn't a mistake, in this situation).

It's just annoying to have "noise" in your Console.

Found another instance:

<img width="755" alt="Screen Shot 2020-04-30 at 2 26 54 PM" src="https://user-images.githubusercontent.com/353790/80745970-1f969300-8aef-11ea-98ac-d8505a23f74a.png">

**Comment by sokra** [comment]
I think it's a Firefox bug. According the the documention no warning should happen in this case: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Stmt_after_return

**Comment by oles** [comment]
I'm also getting this on Firefox 76.0.1, though differently:

![Screenshot from 2020-05-13 13-52-47](https://user-images.githubusercontent.com/7634050/81809337-7fdef900-9521-11ea-9c3d-5bb04218eade.png)
![Screenshot from 2020-05-13 13-52-56](https://user-images.githubusercontent.com/7634050/81809341-82415300-9521-11ea-968b-43ad16dc7e9e.png)

Don't have the time to test rolling back webpack and/or Firefox now to narrow it down, but next week, unless someone figured it out by then :+1:

**Comment by oles** [comment]
Narrowed it down! I was actually having some unreachable code after a return statement.

The warning went away once I fixed it.

Perhaps it is the same for you, @markjaquith?

I just manually commented out various bits in my code 'til it went away, narrowing it down as I went.

**Comment by DanielRuf** [comment]
Is there a reproducible testcase as repository?

I can not resolve this in Firefox 76.

Related and old bug reports:
https://bugzilla.mozilla.org/show_bug.cgi?id=1151931
https://bugzilla.mozilla.org/show_bug.cgi?id=1177941

**Comment by evilebottnawi** [comment]
Fixed on Firefox side
