### ISSUE TITLE
Module not found: Error: Cannot resolve module 'babel-loader'

### ISSUE THREAD

**Issue by camsong** [webpack/webpack#1083]
I'm using `webpack` in directory `/users/path/a/`(it holds the `webpack.config.js`) and compile files in directlry `/another/path/b/`. I run gulp webpack task in path a, and it will compile all the files in path b using absolute path.

Then I got `Cannot resolve module 'babel-loader' ` error.

After looking at https://github.com/webpack/webpack/issues/784, I tried `resolve.fallback`, `resolve.root`, but neither works. Thanks for all kinds of help.

**Comment by camsong** [comment]
Finally I tried `resolveLoader` and it works.
My configuration is as follows:

```
resolveLoader: {
      modulesDirectories: [
          '/users/path/a/node_modules'
      ]
},
```

**Comment by sokra** [comment]
better use `resolveLoader.root` for absolute paths. see documentation hint.

**Comment by camsong** [comment]
Changed to `resolveLoader.root` 
BTW, it's hard to find `resolveLoader.root` in the documentation. the *IMPORTANT* is not so outstanding 

![image](https://cloud.githubusercontent.com/assets/948896/7745800/6a051802-ffe0-11e4-9177-d1807d792d6b.png)

**Comment by mikalai-silivonik** [comment]
Thanks for the thread guys! Agree with @camsong it's better to highlight the `IMPORTANT` section there.

**Comment by Duan112358** [comment]
Thks @camsong , I also packed as webpack config in a node cli package

**Comment by kevireilly** [comment]
For those looking to have some copy pasta:
```
resolveLoader: {
  root: path.join(__dirname, 'node_modules')
}
```
From the [image](https://cloud.githubusercontent.com/assets/948896/7745800/6a051802-ffe0-11e4-9177-d1807d792d6b.png) posted by @camsong as pulled from the [docs](https://webpack.github.io/docs/configuration.html#module-loaders)

**Comment by kevireilly** [comment]
For those looking to have some copy pasta:
```
resolveLoader: {
  root: path.join(__dirname, 'node_modules')
}
```
Pulled from the [docs](https://webpack.github.io/docs/configuration.html#module-loaders) and the [image](https://cloud.githubusercontent.com/assets/948896/7745800/6a051802-ffe0-11e4-9177-d1807d792d6b.png) as posted by @camsong. Thanks for figuring it out.

**Comment by sk22** [comment]
And, why do I need to add `resolveLoader`? Shouldn't it work without? Why doesn't it?

**Comment by mrchimp** [comment]
I am having this same problem but it seems like resolveLoader.root is now deprecated. Can anyone point me in the right direction? There's a lot of conflicting information around!

**Comment by MincePie** [comment]
Kevinreilly - I tried the suggestion you gave. I can see where you found it in the docs, but it produces this error for me:  Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.resolveLoader has an unknown property 'root'. These properties are valid:
   object { alias?, aliasFields?, cachePredicate?, descriptionFiles?, enforceExtension?, enforceModuleExtension?, extensions?, fileSystem?, mainFields?, mainFiles?, moduleExtensions?, modules?, plugins?, resolver?, symlinks?, unsafeCache?, useSyncFileSystemCalls? }

**Comment by kevireilly** [comment]
@MincePie after researching your error it seems like the solution above is for Webpack v1 and that it may have changed for v2. I've not used v2 so this is just a guess from the migration guide:
```
  resolve: {
   modules: [
     path.join(__dirname, "src"),
     "node_modules"
   ]
  }
```
For more information, see [Migrating from v1 to v2](https://webpack.js.org/guides/migrating/)

**Comment by djuretic** [comment]
In my case my `node_modules` folder is in a different location, and only modifying `resolve.modules` didn't work well with `webpack-dev-server`.

This worked for me:

```
resolveLoader: {
    modules: ['/path/to/node_modules'],
},
resolve: {
    modules: ['/path/to/node_modules'],
}
```

**Comment by SauravDas90** [comment]
@djuretic `var debug = process.env.NODE_ENV !== "production";
var webpack = require('webpack');
var path = require('path');

module.exports = {
  context: path.join(__dirname, "src"),
  devtool: debug ? "inline-sourcemap" : false,
  entry: "./js/client.js",
  module: {
    loaders: [
      {
        test: /\.jsx?$/,
        exclude: /(node_modules|bower_components)/,
        loader: 'babel-loader',
        query: {
          presets: ['react', 'es2015', 'stage-0'],
          plugins: ['react-html-attrs', 'transform-decorators-legacy', 'transform-class-properties'],
        }
      }
    ]
  },
 resolveLoader: {
    modules: [
     "node_modules"
   ]
},
  resolve: {
   modules: [
     path.join(__dirname, "src"),
     "node_modules"
   ]},
   output: {
    path: __dirname + "/src/",
    filename: "client.min.js"
  },

  plugins: debug ? [] : [
    new webpack.optimize.DedupePlugin(),
    new webpack.optimize.OccurrenceOrderPlugin(),
    new webpack.optimize.UglifyJsPlugin({ mangle: false, sourcemap: false }),
  ],
};

`

and the pathe of my node-modules for global is

/usr/lib/node_modules

and local is 

/home/saurav/workspaces/javascript/react_exer/react-js-tutorials/1-basic-react.... its also where **package.json is there, **
can you please help , the resolve issue is not working

**Comment by SauravDas90** [comment]
Added    "babel-preset-es2015": "^6.3.13"  dependency in package.json

**Comment by lynk** [comment]
I am using webpack 4.
I solved my "module not found" error finally! by using the loader option "includePaths":

`    module: { 
    rules: [   {
                test: /\.(scss)$/,
                use: [
                    {
                        loader: 'sass-loader',
                        options: {
                            includePaths: ['./node_modules']
}
                    }
                ]
            }
        ]
    },`

All "resolve" and "resolveLoader" and other solutions offered in this thread did not work.
Hope this helps anyone :)

My folder structure:

--node_modules
--src
webpack.config.js
package.json

**Comment by TheEhsanSarshar** [comment]
FTW:
```
yarn add --dev babel-loader
npm i --save-dev babel-loader
```
