### ISSUE TITLE
webpack 5: Module concatenation should not rewrite import-referencing declaration following `delete`

### ISSUE THREAD

**Issue by thecrypticace** [webpack/webpack#10831]
# Bug report

**What is the current behavior?**
Deleting a property on an object imported from an external file results in errors during build because the reference is converted to a local variable which cannot be deleted in strict mode.

**If the current behavior is a bug, please provide the steps to reproduce.**

Reproduction repo: https://github.com/thecrypticace/webpack-module-concat-delete-prop-bug

Reproduction steps (these are also demonstrated in above repo with a few more examples):
1. Export object from file:
```js
export default {
  foo: null,
}
```

2. Import object from said file
```js
import def from "./other.js"
```

3. Delete property in object
```js
delete def.foo
```

4. Build with module concatenation
```
npx webpack -p
```

5. See error about deleting local variable
```
ERROR in ./src/index.js + 1 modules
Deleting local variable in strict mode (3:0)
|
|
| delete __WEBPACK_MODULE_REFERENCE__0_5b2264656661756c74222c22666f6f225d_asiSafe__
|
```

**What is the expected behavior?**
Module concatenation should not rewrite whole reference following a `delete` directive into a local variable as this is an error in strict mode.

**Other relevant information:**
webpack version:  v5.0.0-beta.15
Node.js version: v14.1.0
Operating System: macOS 10.15.3
Additional tools: Yarn v1.22.4

**Comment by web-padawan** [comment]
Confirmed with `highcharts` library, see https://unpkg.com/highcharts@8.1.2/modules/exporting.src.js?module

```
ERROR in ./node_modules/highcharts/es-modules/masters/modules/exporting.src.js + 3 modules
Deleting local variable in strict mode (1340:8)
|         }
|         delete chart.printReverseInfo;
|         delete __WEBPACK_MODULE_REFERENCE__1_5b2264656661756c74222c227072696e74696e674368617274225d_asiSafe__;
|         fireEvent(chart, 'afterPrint');
|     },
```

The problematic line is this one:

```
delete H.printingChart;
```

**Comment by evilebottnawi** [comment]
@web-padawan thanks for information, it will be fixed in the near future
