### ISSUE TITLE
dependsOn - Support for multiple files per entry

### ISSUE THREAD

**Issue by aparna-tavisca** [webpack/webpack#10833]
## Feature request

webpack version: v5.0.0-beta.15

I can see new feature `dependOn` is added. I can see examples of dependOn only with `objects` i:e 

> entry: {
>     app: { import: './app.js', dependOn: 'react-vendors' },
>     'react-vendors': ['react', 'react-dom', 'prop-types']
>   }

**What is the expected behavior?**
What if two different modules have common dependency and I want to combine this two files into one `js` file. I cannot see examples of multiple files per entry using array.

**Example:** 
> entry: {
>     app: [{ import: './app.js', dependOn: 'react-vendors' }, { import: 'somejsfilepath', dependOn: 'react-vendors' }],
>     'react-vendors': ['react', 'react-dom', 'prop-types']
>   }

**Comment by sokra** [comment]
``` js
entry: {
  app: { import: ['./app.js', 'somejsfilepath'], dependOn: 'react-vendors' },
  'react-vendors': ['react', 'react-dom', 'prop-types']
}

**Comment by aparna-tavisca** [comment]
@sokra - Thank you so much :)
