### ISSUE TITLE
Add `root` as an alias of `global` 

### ISSUE THREAD

**Issue by jdalton** [webpack/webpack#1084]
The recent version of lodash (v3.9.0) left some `root` vars in place in their node package. This works in node/io.js because `root === global`. Would you all be against adding `root` as an alias of `global`?

Related to https://github.com/lodash/lodash/issues/1218.

**Comment by cesarandreu** [comment]
I think this issue is expired and can be closed @bebraw. It looks like [`global`](https://github.com/tc39/proposal-global) won, considering it's up to stage 3.

**Comment by bebraw** [comment]
Cool. Thanks.
