### ISSUE TITLE
How to apply source map to paths reported by "ERROR in" or "WARNING in" messages?

### ISSUE THREAD

**Issue by dko-slapdash** [webpack/webpack#10842]
Hi.

Is it possible to tell webpack to translate references in **error/warning messages** using source maps of the input files?

E.g. source-map-loader allows to bundle the pre-built JS content from dist/ (imagine we have tsc which builds dist/ content from src/), it works fine. Then, dist/ folder looks like this:

```
$ ls dist/
Some.js  # e.g. generated from src/Some.myesotericlanguage
Some.js.map
```

And, say, in transpiled Some.js I have a dummy `require("aaa")` where aaa doesn't exist. Then, when bundling Some.js, webpack generates the following error message to console:

```
ERROR in ../dist/Some.js
Module not found: Error: Can't resolve 'aaa' in '../dist'
```

I.e. it doesn't respect source map file for dist/Some.js path and just prints it as is (as well as examples from the code if there is some JS syntax error after transpilation; source map is not respected there too). Although it exists.

**Comment by sokra** [comment]
Currently this is not possible

**Comment by dko-slapdash** [comment]
Could you please provide some code pointers/hints on how to make it possible? Like, is there some hooks on these error/warning messages? (The closest I could google for is loader's emitError/emitWarning, but it may be irrelevant.)

Because from theoretical point of view, it's reading of .map file corresponding to the "Error in xyz" path and then translating location (source location would do 90% of the value; examples from the code which webpack shows in error message are less valuable.)

Also, at which abstraction level can it be implemented? It's not a loader and not a plugin, right?

**Comment by sokra** [comment]
You can write a plugin that hooks into `Compilation.hooks.succeedModule` and update the `module.errors/warnings`.

**Comment by evilebottnawi** [comment]
Answer above
