### ISSUE TITLE
How grab dependencies of import

### ISSUE THREAD

**Issue by aquaductape** [webpack/webpack#10858]
I'm trying grab a typescript file `theme.ts`, compile it to javascript, then use nodejs to read the JS output and inject it inside an inline script tag which belongs to the file `_document.tsx`.

`theme.ts` purpose is to change color mode of the webpage, so by toggling the mode, I'm using some logic from that file.

Also inside `theme.ts` I have an exported function `setInitialTheme` that initially sets up the color mode(aka dark mode) . To make sure that it does run before the main content is rendered, I would have to place it inside a script tag in `_document.tsx`

```js
import { setInitialTheme } from "../lib/theme.ts";

const script = `( function(){ var run =${String(setInitialTheme)}; run() } )()`;
class MyDocument extends Document {
  render() {
    return (
      <Html>
        <Head>
          <script dangerouslySetInnerHTML={{ __html: script, }} />
        </Head>
...
```
This wouldn't work. The issue is `setInitialTheme` calls other functions, therefore during runtime the script will break. 
```js
// setInitialTheme uses setThemeConfig
// setThemeConfig uses setCssVar 
// setCssVar uses ect...

export const setInitialTheme = () => {
  try {
    const theme = localStorage.getItem("theme") || "light";

    setThemeConfig(theme);
  } catch (err) {
    console.log(err);
  }
};
```

I know could just make move those other functions inside `setInitialTheme`, but I'm wondering if there's a way for either NodeJS or webpack to grab all "dependencies" of `setInitialTheme`

Therefore the end result of string script would look like this
```js
const script  = `(function() {
const setCSSVar = (property, color) => { ... }
const setThemeConfig = (inputTheme) => { ... }
const setInitialTheme = () => { ... }
setInitialTheme()
})()`
```

Rather than importing the `setInitialTheme` directly into `_document.tsx`, I'm importing it to a different directory `.theme` where it will be read by webpack which will output a file that is then read by nodejs, which will modify `_document.tsx`

Here's the [setup of the source code](https://github.com/aquaductape/nextjs-inject-script), where my webpack config file is `webpack.theme.js` and the logic to read `theme.ts` and inject it inside `_document.tsx` is inside `.theme` directory.

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Please use stackoverflow or gitter for questions
