### ISSUE TITLE
add option to polyfill node's root variable on bundling

### ISSUE THREAD

**Issue by goldensunliu** [webpack/webpack#1085]
when requiring the v3.9 lodash's npm package's sub module matches:

require('lodash/utility/matches')

the result bundle throws an error on the browser:
"root is undefined" on https://github.com/lodash/lodash-node/blob/master/modern/internal/bufferClone.js#L5.

We should include an extra option of root in http://webpack.github.io/docs/configuration.html#node, so the variable root can also be polyfilled and allow these npm bundles to load happily thereafter.

**Comment by SimenB** [comment]
Related: #1084

**Comment by bebraw** [comment]
@goldensunliu Is this still relevant? If you are using Babel, please see [babel-plugin-lodash](https://github.com/megawac/babel-plugin-lodash).

**Comment by bebraw** [comment]
Closed in favor of #1084.
