### ISSUE TITLE
Webpack production mode can't display images on other pages besides the main page

### ISSUE THREAD

**Issue by Sophia-98** [webpack/webpack#10857]
# Bug report

**What is the current behavior?**

- Production mode when built doesn't display images and other non js, html and css files such as shaders (development mode is fine). The images are definitely within the dist folder so it's not an issue of modules.
- It would only display in production mode when I put all the image files not as an import but as a direct src link not relative to the js file. e.g `<img src = "../src/etc."/>` instead of `import img as "../../js/etc"` `<img src = {img}/>`. (using this way of sourcing doesn't allow me to use shaders.)
- However, If I were to deploy this onto a server the same issue would arise again despite it working in live server in production mode.  

**If the current behavior is a bug, please provide the steps to reproduce.**

The app must have react-router dom with many routes as the first page that loads is the only one that seems to work properly

Here is my repository simplifying what is going on in my web application
https://github.com/Sophia-98/issue

**What is the expected behavior?**

- The expected behavior is for it to work exactly as it does in dev server and for the images and other files such as shaders to be displayed correctly. 

**Other relevant information:**
-  When using making a quick react app with 'create-react-app' I was able to use static server and would work on my local port. But if I were to do it with this file it would give a 404 error not found.

webpack version:  4.42.0
Node.js version: 6.14.2
Operating System: Windows 10
Additional tools: Visual Studio Code

**Comment by evilebottnawi** [comment]
Please create reproducible test repo

**Comment by evilebottnawi** [comment]
We don't have `useLoader` API

**Comment by Sophia-98** [comment]
> We don't have `useLoader` API

useLoader is part of react-three-fiber.

**Comment by Sophia-98** [comment]
> We don't have `useLoader` API



> Please create reproducible test repo

@evilebottnawi Sorry if this seems obvious but you want me to post my files to github correct?

**Comment by snitin315** [comment]
Yes @Sophia-98

**Comment by Sophia-98** [comment]
@snitin315 @evilebottnawi  So Ive been trying to upload my folder on git for quite a while and the file is too big so it keeps cutting the connection. I don't really know what to do. On my build it says that my files including my main.js and my image files are too big. do you think this is the reason as to why they are not showing?
