### ISSUE TITLE
modules[moduleId].call is undefined running locally Angular Universal project with Lazy loading

### ISSUE THREAD

**Issue by ilprima** [webpack/webpack#10850]
# Bug report

**What is the current behavior?**
Hi, I'm trying to run my project with Angular Universa locally but webpack gives an error. It is not able to load my modules. I'm using lazy loading and the module name uses hash. I think webpack is not able to find the modules. The error is:
```

/Users/-/WebstormProjects/-app/dist/server.js:47289
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
         		                  ^

TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (/Users/-/WebstormProjects/-app/dist/server.js:47289:30)
    at Object.<anonymous> (/Users/-/WebstormProjects/-app/dist/server.js:148749:12)
    at Object.a12C (/Users/-/WebstormProjects/-app/dist/server.js:161547:30)
    at __webpack_require__ (/Users/-/WebstormProjects/-app/dist/server.js:47289:30)
    at module.exports.O9CF.extendStatics (/Users/andreaprimaverili/WebstormProjects/-app/dist/server.js:124094:117)
    at Object.O9CF (/Users/-/WebstormProjects/-app/dist/server.js:124096:2)
    at __webpack_require__ (/Users/-/WebstormProjects/-app/dist/server.js:47289:30)
    at Object.V7fC (/Users/-/WebstormProjects/-app/dist/server.js:134032:32)
    at __webpack_require__ (/Users/-/WebstormProjects/-app/dist/server.js:47289:30)
    at Object.K011 (/Users/-/WebstormProjects/-app/dist/server.js:118559:37)
```

**If the current behavior is a bug, please provide the steps to reproduce.**
I ran the following commands:
 "build:ssr": "npm run build:client-and-server-bundles && npm run compile:server"
 "serve:ssr": "node local.js",

Using Lazy loaded modules with hash names, eg my names are "56.65e412bc6525fe8d22a2.js"

**What is the expected behavior?**

Run with no error

**Other relevant information:**
```
ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/
    

Angular CLI: 8.1.3
Node: 10.16.3
OS: darwin x64
Angular: 8.2.4
... common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.803.2
@angular-devkit/build-angular              0.803.2
@angular-devkit/build-optimizer            0.803.2
@angular-devkit/build-webpack              0.13.8
@angular-devkit/core                       8.3.2
@angular-devkit/schematics                 8.3.2
@angular/animations                        8.2.10
@angular/cli                               8.1.3
@angular/http                              7.2.2
@angular/platform-server                   8.2.14
@ngtools/webpack                           8.3.2
@nguniversal/common                        8.1.0
@nguniversal/express-engine                8.2.6
@nguniversal/module-map-ngfactory-loader   8.2.6
@schematics/angular                        8.1.3
@schematics/update                         0.801.3
rxjs                                       6.5.3
typescript                                 3.5.3
webpack                                    4.39.2
```

**Comment by evilebottnawi** [comment]
Please create reproducible test repo, your issue is not readable

**Comment by sokra** [comment]
This happens when you use remote modules, but didn't not have a `import()` somewhere in the path. We need to add a compile-time error for that.

**Comment by ilprima** [comment]
I commented these lines:

```
externals: {
      './dist/server/main': 'require("./server/main")'
},
```

in webpack.server.config.js file but now I have another error when running the app:

> node local.js

internal/modules/cjs/loader.js:638
    throw err;
    ^

```
Error: Cannot find module 'require("./server/main")'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users//WebstormProjects/-app/dist/server.js:47270:18)
    at __webpack_require__ (/Users//WebstormProjects/-app/dist/server.js:21:30)
    at Object.<anonymous> (/Users//WebstormProjects/-app/dist/server.js:129:10)
    at __webpack_require__ (/Users//WebstormProjects/-app/dist/server.js:21:30)
    at module.exports.Object.defineProperty.value (/Users//WebstormProjects/-app/dist/server.js:85:18)
    at Object.<anonymous> (/Users//WebstormProjects/-app/dist/server.js:88:10)
```

**Comment by sokra** [comment]
It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by ilprima** [comment]
> It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

I would like to do it but it is a big project is is not easy. 
By the way checking online (https://github.com/maciejtreder/ng-toolkit/issues/729#issuecomment-568938643) I found that the problem is:
`module.exports = require("require(\"./server/main\")");`
instead of 
` module.exports = require('./server/main');`
in the server.js file produced. The problem is that I don't know how to fix it without editing manually that file.

My server.ts file is:

`/**
 * *** NOTE ON IMPORTING FROM ANGULAR AND NGUNIVERSAL IN THIS FILE ***
 *
 * If your application uses third-party dependencies, you'll need to
 * either use Webpack or the Angular CLI's `bundleDependencies` feature
 * in order to adequately package them for use on the server without a
 * node_modules directory.
 *
 * However, due to the nature of the CLI's `bundleDependencies`, importing
 * Angular in this file will create a different instance of Angular than
 * the version in the compiled application code. This leads to unavoidable
 * conflicts. Therefore, please do not explicitly import from @angular or
 * @nguniversal in this file. You can export any needed resources
 * from your application's main.server.ts file, as seen below with the
 * import for `ngExpressEngine`.
 */

import 'zone.js/dist/zone-node';
import { createWindow } from 'domino';

import express from "express"
//import * as express from 'express';
import {join} from 'path';
import {readFileSync} from 'fs';

// Express server
export const app: any = express();

const PORT = process.env.PORT || 4000;
const DIST_FOLDER = join(process.cwd(), 'dist/browser');


//Try to fix ionic  document is not defined errors
const template = readFileSync(
    join('.', 'dist', 'browser', 'index.html')
).toString();
const win = createWindow(template);
global['window'] = win;
global['document'] = win.document;
global['navigator'] = win.navigator;

// * NOTE :: leave this as require() since this file is built Dynamically from webpack
const {AppServerModuleNgFactory, LAZY_MODULE_MAP, ngExpressEngine, provideModuleMap} = require('./dist/server/main');

// Our Universal express-engine (found @ https://github.com/angular/universal/tree/master/modules/express-engine)
app.engine('html', ngExpressEngine({
  bootstrap: AppServerModuleNgFactory,
  providers: [
    provideModuleMap(LAZY_MODULE_MAP)
  ]
}));

app.set('view engine', 'html');
app.set('views', DIST_FOLDER);

// Example Express Rest API endpoints
// app.get('/api/**', (req, res) => { });
// Serve static files from /browser
app.get('*.*', express.static(DIST_FOLDER, {
  maxAge: '1y'
}));

// All regular routes use the Universal engine
app.get('*', (req, res) => {
  res.render('index', { req });
});


// Start up the Node server
app.listen(PORT, () => {
    console.log(`Node server in ascolto su http://localhost:${PORT}`);
});
`

**Comment by sokra** [comment]
>   externals: {
>       fsevents: "require('fsevents')",
>       './dist/server/main': 'require("./server/main")'
> 	},

```
  externals: {
      fsevents: "fsevents",
      './dist/server/main': './server/main'
	},
```

**Comment by ilprima** [comment]
> > externals: {
> > fsevents: "require('fsevents')",
> > './dist/server/main': 'require("./server/main")'
> > },
> 
> ```
>   externals: {
>       fsevents: "fsevents",
>       './dist/server/main': './server/main'
> 	},
> ```

Yes I already resolved with this. Seems like the official Ionic guide is wrong
