### ISSUE TITLE
Module federation should declare the remote entries with its location

### ISSUE THREAD

**Issue by Falci** [webpack/webpack#10859]
## Feature request

Let's start from [this example](https://github.com/module-federation/module-federation-examples/tree/master/typescript).

The app1 (shell/main/host) depends on app2. 
This dependency is declared in the [webpack.config.js](https://github.com/module-federation/module-federation-examples/blob/master/typescript/app1/webpack.config.js#L36), but the location of app2 is declared in the [/public/index.html](https://github.com/module-federation/module-federation-examples/blob/master/typescript/app1/public/index.html#L3)

**What is the expected behavior?**
I'd like to see them togheter, in the plugin options
```js
    new ModuleFederationPlugin({
      name: "app1",
      library: { type: "var", name: "app1" },
      remotes: {
        app2: {alias: "app2", remoteEntry: "http://localhost:3002/remoteEntry.js"}
      },
      shared: ["react", "react-dom"],
    }),
```

**What is motivation or use case for adding/changing the behavior?**
Easier to maintain

**How should this be implemented in your opinion?**
It should not change the core behaviour. It's like a syntax sugar: just copy the `remotes.{key}.remoteEntry` to the `index.html` as `<script>`

**Are you willing to work on this yourself?**
I'd love to. Not sure if I know enough about webpack's implementation.

**Comment by Falci** [comment]
"I'd like to see them togheter" is not a good sentence.
It would be better to say: "I doesn't feel right to put this kind of metadata in the `index.html`".

It's true that the `index.html` is the place where it should end up, but doesn't mean it should be declared there.

A second option would be to declare it in the `package.json` since it's the place to declare the dependencies:

```json
{
    "name": "app1",
    "version": "0.0.0",
    "dependencies": {...},
    "devDependencies": {...},
    "remoteEntries": {
        "app2": "http://localhost:3002/remoteEntry.js"
    }
}
```

**Comment by kenkozheng** [comment]
I partly agree with u.  Declare in the `index.html` is not a good idea.
But if declaring in the config file, the url of app2 will just be static.
For example, we want to get the url of app2 from an admin backend.  
Actually, I want webpack do the favor for me to finish the last step, not fetching `remoteEntry.js` by my code.

**Comment by zhangwilling** [comment]
u can define remoteEntry in your js files.

**Comment by sokra** [comment]
This was been added via the `script` external

**Comment by whu12yz** [comment]
> remoteEntry

how? could u please give  an example
