### ISSUE TITLE
IgnorePlugin: Cannot Found Module Error

### ISSUE THREAD

**Issue by aparna-tavisca** [webpack/webpack#10866]
# Bug report
**What is the current behavior?**
I'am trying to use `IgnorePlugin` to ignore certain module imports. However, the modules which are added in the ignore list is throwing error `module not found`.

`webpack.config.js`

> module.exports = {
>    entry: {
>     shared: ['./utils/src/index.ts'],
>     entry1: { import: './button/src/index.ts', dependOn: 'shared' },
>     entry2: { import: './input/src/index.ts', dependOn: 'shared' }
>   },
>   plugins: [
>     new webpack.IgnorePlugin({
>       checkResource(resource) {
>         if (resource.includes('@bit/utils')) {
>           return true;
>         } else {
>           return false;
>         }
>       }
>     })
>   ]
> }

`button/src/index.ts`

> import '@bit/utils';

> ...

`input/src/index.ts`
> import '@bit/utils';

> ...

**What is the expected behavior?**
The `entry1` and `entry2` should not include the import of `import '@bit/utils'`. In order to avoid redundancy, I made it as separate entry and mentioned it as `dependOn`.

Note - I cannot use `externals` option, as it will exclude all the import and it is upto the end user to add the ignored module. Also `splitsChunkPlugin` cannot be used, because this are independent folders (Used lerna tool). I mean button and input are two different folders and they have own respective node_modules. So the absolute import path is different and the splitsChunkPlugin only makes chunks when the import paths are same.

**Other relevant information:**
webpack version:  ^5.0.0-beta.16
Node.js version: 12.16.1
Operating System: windows

Note - Already looked in to the issue - https://github.com/webpack/webpack/issues/2858, but the solution does not seems to work for me. Can some one please help me to solve this issue?

**Comment by sokra** [comment]
IgnorePlugin is the wrong tool here. Try to alias all usage of `@bit/utils` to the same absolute path with`resolve.alias`. Then use dependOn or splitChunks.

Even better would be to make your package manager only install it once. E.g. use yarn workspaces to move your `node_modules` higher in the tree

**Comment by aparna-tavisca** [comment]
@sokra - Thank you so much :). `resolve.alias` works like charm :)
