### ISSUE TITLE
I write a loader and want pass some options to it but I get ‘{}’ when pass not json data

### ISSUE THREAD

**Issue by lastnigtic** [webpack/webpack#10865]
I am using my own loader like:
```
 {
            loader: 'my-loader',
            options: {
                  xxx: /regex/
            }
 }
```
Then i use `import { getOptions } from 'loader-utils';` to get options. 
I will get `xxx: {}` but not the regex I am passing.
When I rewrite the RegExp.proptotype.toJSON by 
```
Object.defineProperty(RegExp.prototype, 'toJSON', {
    value: RegExp.prototype.toString,
});
```
I will get `xxx: /regex/`.

It that a bug or something wrong with me?

**Other relevant information:**
webpack version:  4.41.2
Node.js version: 
Operating System: 
Additional tools:

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by lastnigtic** [comment]
I find a way to reproduce this behavior.

It is relative with `thread-loader`.

Using the configs below, I will get "{}"
```
// get `{}`
[
    'thread-loader',
   {
            loader: 'my-loader',
            options: {
                  xxx: /regex/
            }
   }
]
```

However, when I switch their position, it works as expected.

```
// expect
[
   {
            loader: 'my-loader',
            options: {
                  xxx: /regex/
            }
   },
    'thread-loader',
]
```

What is the best pratice to use 'thread-loader'? Thanks

**Comment by sokra** [comment]
Thread loader doesn't support non-json options as it has to move these options to another thread.

**Comment by lastnigtic** [comment]
Got it!
Are there any documents explain how thread-loader works?
