### ISSUE TITLE
Need a grammar check in README file

### ISSUE THREAD

**Issue by Deeksha2501** [webpack/webpack#10877]
There are some grammar issues in README file. 
Can I work on this issue.

**Comment by snitin315** [comment]
Yes Go ahead.

**Comment by Deeksha2501** [comment]
Ok.

**Comment by evilebottnawi** [comment]
We already use cspell for this https://github.com/webpack/webpack/blob/master/package.json#L138, if you found a grammar error just send a PR, no need to create an issue, thanks
