### ISSUE TITLE
When using optimization.splitchunks library is not available in import

### ISSUE THREAD

**Issue by shubhamkes** [webpack/webpack#10878]
# Bug report ?
Not sure if its a bug, but I am stuck here and want help from the community...

**What is the current behavior?**
I am creating a library to be used in react web and react-native. Since library size is too heavy, am trying to split it into chunks and trying splitChunks but library doesn't seem to be available for import.

Importing a simple module from this library isn't available when splitChunks is enabled. However when not using splitChunks, it works like charm.

Here is my webpack.config 

```
module.exports = {
    entry:
    {
        'index': './src/index.ts',
        'utils': './src/index.utils.ts',
    },
    output: {
        path: path.join(__dirname, "dist"),
        filename: "[name].ts",
        library: ["frontend-business", "[name]"],
        libraryTarget: "commonjs2"
    },
    devtool: 'inline-source-map',
    resolve: {
        extensions: ['.tsx', '.ts', '.js'],
    },
    module: {
        rules: [
            {
                test: /\.js$/,
                include: path.resolve(__dirname, 'src'),
                exclude: /(node_modules|build|dist)/,
                use: {
                    loader: 'babel-loader',
                }
            },
            {
                test: /\.ts?$/,
                include: path.resolve(__dirname, 'src'),
                use: 'ts-loader',
                exclude: /(node_modules|build|dist)/,
            },
        ]
    },
    externals: {
        'react': 'commonjs react', // this line is just to use the React dependency of our parent-platform-project instead of using our own React.
        '@types/react': 'commonjs @types/react'
    },
    optimization: {
        splitChunks: {
            chunks: 'all',
        }
    }
};


```

**What is the expected behavior?**
With splitChunks it should have work as without it because I dont see any extra work associated with splitChunks to make it work. 

**Other relevant information:**
webpack version:  4.41.2
Node.js version: 10.16.3
Operating System: Darwin

**Comment by sokra** [comment]
This config will probably split your library into multiple files. You need to include all files for the library to work. So maybe something like `require("./your-lib/vendors-index.js") || require("./your-lib/index.js")`. That's pretty unusual for a library.

**Comment by shubhamkes** [comment]
I am publishing as npm package, and consumer imports module like 
```
import {someMethod } from 'frontend-business' 
```
What am i missing here? is there any extra include to be done on package side when using splitChunks?

**Comment by sokra** [comment]
Note it's very unusually to use splitChunks with `chunks: "all"` for a library. I'm not very sure if this works...
If you create a repo to reproduce this I might be able to help you to get this working.

**Comment by shubhamkes** [comment]
Have uploaded minimal version of my repo
[(https://github.com/shubhamkes/webpack-splitChunks)]
in this repo dist-with-split folder has bundle with splitChunks enabled code 
where as dist is without splitChunks and dist works perfectly

And its not like I have just tried only ```chunks: "all" ```
so far I have tried so many variants available on the various posts but none worked. 

Thank you for your time

**Comment by shubhamkes** [comment]
Hey @sokra can you please look into it?

**Comment by wcldyx** [comment]
I also encountered the same problem, creating multiple modules with mutual reference relationship between them, and opening the library released by "Optimization.splitchunks" becomes "undefind" when it is imported.

**Comment by wcldyx** [comment]
@sokra @shubhamkes 
Is there any new progress on this issue

**Comment by shubhamkes** [comment]
I have uploaded the repository to reproduce the issue and waiting for the help from someone in the community

**Comment by sokra** [comment]
There are a few thing unclear in the repro. How do you consume the lib? In node.js, from webpack, or via script tags?

I noticed some weird things in your config:

* `output.libraryTarget: "umd"` + `externals: "commonjs ..."`: externals would only work in commonjs. Do you want to use `output.libraryTarget: "commonjs2"`?
* `output.globalObject: "this"`: This will not work for commonjs libraries as `this` is `exports` in commonjs
* `output.filename: "[name].ts"`: `.ts` as extension doesn't make sense. use `.js`.
* `output.jsonpFunction` should be changed to something unique to not conflict this other webpack libraries or applications

When consuming the lib you **must load both** output files: `vendor` and one of `index` or `util`:

e. g.

``` js
import 'frontend-business/vendor.js'
import { someMethod } from 'frontend-business'
```

But this would be ugly for the consumer so create your own wrapper files for that:

``` js
// index.js
import './dist/vendor.js'
export * from './dist/index.js'

// util.js
import './dist/vendor.js'
export * from './dist/util.js'
```

But remember that after all, it's not recommended to bundle libraries for consumption by bundlers. Only bundle them for consumption via script-tags.

**Comment by evilebottnawi** [comment]
@sokra Maybe we can improve error reporting for this? I encounter a lot of similar problems and most often this is a configuration problem

**Comment by sokra** [comment]
> Maybe we can improve error reporting for this? I encounter a lot of similar problems and most often this is a configuration problem

The default values of all these options are actually correct. `externals` will default to `output.libraryTarget` as type when external type is not explicitly overwriten. `output.globalObject` defaults to `window`. `output.filename` defaults to `[name].js`. `output.jsonpFunction` will use a unique name in webpack 5 by default.

**Comment by shubhamkes** [comment]
> There are a few thing unclear in the repro. How do you consume the lib? In node.js, from webpack, or via script tags?
> 
> I noticed some weird things in your config:
> 
> * `output.libraryTarget: "umd"` + `externals: "commonjs ..."`: externals would only work in commonjs. Do you want to use `output.libraryTarget: "commonjs2"`?
> * `output.globalObject: "this"`: This will not work for commonjs libraries as `this` is `exports` in commonjs
> * `output.filename: "[name].ts"`: `.ts` as extension doesn't make sense. use `.js`.
> * `output.jsonpFunction` should be changed to something unique to not conflict this other webpack libraries or applications
> 
> When consuming the lib you **must load both** output files: `vendor` and one of `index` or `util`:
> 
> e. g.
> 
> ```js
> import 'frontend-business/vendor.js'
> import { someMethod } from 'frontend-business'
> ```
> 
> But this would be ugly for the consumer so create your own wrapper files for that:
> 
> ```js
> // index.js
> import './dist/vendor.js'
> export * from './dist/index.js'
> 
> // util.js
> import './dist/vendor.js'
> export * from './dist/util.js'
> ```
> 
> But remember that after all, it's not recommended to bundle libraries for consumption by bundlers. Only bundle them for consumption via script-tags.

This lib is meant for react projects which will be bundled up with webpack supposedly.

I agree few things here doesn't make sense
like output.libraryTarget: "umd" and output.globalObject: "this"
but these were not my initial setup. Since i was struggling to make it work with splitchunks, and while doing hit and trial, ended up with these configurations.

**Comment by dkamyshov** [comment]
Hi, @sokra!

> That's pretty unusual for a library.

It is sometimes useful (especially in reactlandia) to have a library with multiple entrypoints, with each entrypoint re-exporting a common module (think of a singleton). We need all entrypoints to `require` the shared module. It is trivial to achieve with rollup, see this demo: https://github.com/dkamyshov/rollup-split-library-reproduction/tree/master/dist

With webpack, it is somewhat achievable with `libraryTarget: 'module'`, though it uses some weird dynamic requires and I'm not sure whether webpack would consume such a library. Those dynamic requires look like this:

```js
/******/ 	(() => {
/******/ 		var next = __webpack_require__.x;
/******/ 		__webpack_require__.x = () => {
/******/ 			__webpack_require__.e("src_a_js-src_b_js");
/******/ 			return next();
/******/ 		};
/******/ 	})();
```

**Comment by alexander-akait** [comment]
Close due asnwered https://github.com/webpack/webpack/issues/10878#issuecomment-633951230, feel free to feedback if you have questions

**Comment by GouJieShinee** [comment]
@shubhamkes  how you fix this problem? I meet the same problem

**Comment by madruga8** [comment]
no one was able to fix this... only dynamic imports works when code splitting are enabled.

**Comment by shashank-brightness** [comment]
> But remember that after all, it's not recommended to bundle libraries for consumption by bundlers. Only bundle them for consumption via script-tags.

If anyhow needs to be consumed via script tag then what's the point of developing as a separate node package? One needs to do both access bundled script even imported by bundler and with SplitChunks in place.
