### ISSUE TITLE
Webpack inserts line break after semicolon in quoted string, breaks Google Font import with multiple font weights

### ISSUE THREAD

**Issue by c-tanner** [webpack/webpack#10873]
# Bug report

**What is the current behavior?**
Webpack inserts a line break after semi-colon in quoted string

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Select multiple font weights for a Google font and copy the supplied `@import` snippet
2. Paste that code into a SCSS file, ex:

```
@import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600&display=swap');
```

3. Check Webpack's compiled CSS, ex:

```
@import url(https://fonts.googleapis.com/css2?family=Montserrat:wght@400;

600&display=swap);
```

**What is the expected behavior?**
Webpack should ignore semicolons in quoted strings

**Other relevant information:**
webpack version:  4.42.0
Node.js version: 10.16.0
Operating System: MacOS 10.15.4
Additional tools:

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by sokra** [comment]
Could you try to isolate the issue to figure out if this is related to `sass-loader` or `css-loader` or `mini-css-extract-plugin`?

**Comment by drummsb4** [comment]
@c-tanner You should be able to get around this by doing something like:

`@import url('https://fonts.googleapis.com/css?family=Montserrat:400,600&display=swap');`

**Comment by evilebottnawi** [comment]
No problems on `css-loader`/`sass-loader` side, maybe bug in a plugin for `postcss-loader`

**Comment by partyvaper** [comment]
Using latest laravel mix and plugin versions and stumbled upon same issue, would like to als oadd that changing syntax from:
`@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&family=Roboto:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap');`
to:
`@import url('https://fonts.googleapis.com/css?family=Poppins:300,400,500,700|Roboto:300,400,500,700,300i,400i,500i,700i&display=swap');`
compiles css correctly and fonts are loaded correctly.

**Comment by evilebottnawi** [comment]
Answer here https://github.com/webpack/webpack/issues/10873#issuecomment-632024988, you you still have a problem, please open a new issue in css-loader with reproducible test repo, I will show where the error is
