### ISSUE TITLE
How to bundle vendor scripts separately and require them as needed with Webpack?

### ISSUE THREAD

**Issue by bensampaio** [webpack/webpack#1087]
Maybe this is not the right place to ask this, but I'm really in need of help here. I posted [this question](http://stackoverflow.com/questions/30329337/how-to-bundle-vendor-scripts-separately-and-require-them-as-needed-with-webpack) on stackoverflow yesterday, could you please have a look at it?

Thank you!

**Comment by margielm** [comment]
I don't consider myself webpack-expert. but I tried to do my best to  help you.

**Comment by bebraw** [comment]
@bensampaio Did you figure this out?

**Comment by bensampaio** [comment]
@bebraw In the end I decided to keep doing it as before... I use webpack for my own scripts, and I merge all vendor scripts into one even if some of them are not used. I don't like it, but it works... I tried to create a loader to just grab all required vendor scripts and merge them in a file by keeping global variables, but it had some problems with the order files were being loaded and written. I ended up giving up because it was consuming too much time. If you want to have a look you can find it here: https://github.com/bensampaio/webpack-globals-loader.

**Comment by Freezystem** [comment]
In case you're interested in bundling automatically your scripts separately from vendors ones: 

```js
var webpack = require('webpack'),
    pkg     = require('./package.json'),  //loads npm config file
    html    = require('html-webpack-plugin');

module.exports = {
  context : __dirname + '/app',
  entry   : {
    app     : __dirname + '/app/index.js',
    vendor  : Object.keys(pkg.dependencies) //get npm vendors deps from config
  },
  output  : {
    path      : __dirname + '/dist',
    filename  : 'app.min-[hash:6].js'
  },
  plugins: [
    new webpack.optimize.CommonsChunkPlugin('vendor', 'vendor.min-[hash:6].js'),
    new html()
  ]
};
```
You can read more about this feature in [official documentation](https://webpack.github.io/docs/code-splitting.html#split-app-and-vendor-code).

**Comment by KongMac** [comment]
put the vendor scripts into the other folder,not in the entry folders.just you just need use "require (XX)"in the entry file,and then you make it.
