### ISSUE TITLE
enable node builtin modules polyfills when target is `node`

### ISSUE THREAD

**Issue by Huanghuiying0624** [webpack/webpack#10874]
# Bug report

**What is the current behavior?**
when I set `node` attribute to `true` in the webpack config file, the bundled file still contains `require(xxx)` for nodejs builtin modules

**If the current behavior is a bug, please provide the steps to reproduce.**
Here is the related configuration in my webpack.config.js:

target: 'node';
node: true;

**What is the expected behavior?**
When we set `node: true`, the nodejs builtin modules will be bundled into the output file, instead of containing `require('stream')` or other node builtins

Here is the use case:
We are bundling a React project for server-side rendering by webpack, and running the bundled files inside vm2 in the node environment. Since vm2 is a sandbox, just like the browser environment, so we cannot contain any `require(xxx)` statements in the bundled files

**Other relevant information:**
webpack version:  4.28.4
Node.js version: 
Operating System: 
Additional tools:

**Comment by evilebottnawi** [comment]
Apparently you are compiling something for `node` target, so I strongly recommend do not mock Node.js modules, this makes no sense, just set `node: false`

> We are bundling a React project for server-side rendering by webpack, and running the bundled files inside vm2 in the node environment. Since vm2 is a sandbox, just like the browser environment, so we cannot contain any require(xxx) statements in the bundled files

https://github.com/patriksimek/vm2#quick-example

You need use this

For webpack@5 we don't mock built-in global and modules by default for `target: node` https://github.com/webpack/webpack/blob/master/lib/config/defaults.js#L479
