### ISSUE TITLE
webpack.ProvidePlugin cannot provide multiple modules as nested global object

### ISSUE THREAD

**Issue by Thor-x86** [webpack/webpack#10872]
# Bug report

**What is the current behavior?**
The `console.log(mycontainer);` throws "mycontainer is not defined"

**If the current behavior is a bug, please provide the steps to reproduce.**

Inside webpack.config.js:

    module.exports = {
        ...
        plugins : [
            new ProvidePlugin({
                'mycontainer.mymodule' : './src/mymodule.js'
            })
        ],
        ...
    }

Inside index.js:

    console.log(mycontainer); // Error here

**What is the expected behavior?**
The `console.log(mycontainer);` supposed to output `{mymodule : ...}`

**Other relevant information:**
webpack version:  4.43.0
Node.js version: 3.5.2
Operating System: Ubuntu 18.04.4 LTS
Additional tools: webpack-dev-server, webpack-cli

**Comment by sokra** [comment]
You provided only `mycontainer.mymodule` and not `mycontainer`. If you want this too add another property to the ProvidePlugin. You might need to create a new file of the full object.
