### ISSUE TITLE
Runtime error in case of circular dependency between ES Modules with a re-export

### ISSUE THREAD

**Issue by bregenspan** [webpack/webpack#10870]
# Bug report

I'm seeing a runtime error in a cyclic dependency case where:

 * module A imports and re-exports a reference to a function from module C and also imports module B
 * module B depends on the function from module C via module A's re-export of it

In the minimal reproduction in https://github.com/bregenspan/webpack-circular-import-issue, this manifests as the runtime error: "Uncaught TypeError: n is not a function".

This issue seems different from https://github.com/webpack/webpack/issues/9060, as it involves an exported function declaration and so as I understand it shouldn't involve the temporal dead zone in the same way; also Rollup and native ES module support in Chrome and Node.js execute the code as expected, unlike in that case.
  

### **What is the current behavior?**

In the example in https://github.com/bregenspan/webpack-circular-import-issue, there is a runtime error with the message: `Uncaught TypeError: n is not a function` when the bundled code is run in a browser. This is because the definition of the default export of the "shared.js" module used in this example is bundled following the first reference to it.

### **If the current behavior is a bug, please provide the steps to reproduce.**

Clone the minimal reproduction in https://github.com/bregenspan/webpack-circular-import-issue, run `npm install && npm run start`. You should now see a browser window and can click "webpack.html" and open your browser's developer console to see the noted behavior.

### **What is the expected behavior?**

There should be no runtime error, and the console output in the browser should match that shown in the other examples (rollup.html and native.html):

```
shared import
"shared import" should be logged twice, once above this log line, once below
shared import
```

While Rollup operates differently from Webpack, I would expect the outputted code in the bundle here to be functionally similar, such that the function declaration imported from the shared import is hoisted and accessible in both of the modules that reference it. (See example of Rollup's output in dist/rollup/bundle.js in the repo linked above after running `npm run build`).

### **Other relevant information:**
webpack version:  4.43.0 / 5.0.0-beta.16
Node.js version: v12.16.3
Operating System: MacOS 10.15.4
Additional tools: Chrome 81.0.4044.138

Other notes:

 * Reordering imports like this: https://github.com/bregenspan/webpack-circular-import-issue/commit/c4a9f00e1e2b5a9aefa84f3bf526d2f88429f305 works around the issue, but I did not expect this to be necessary.
 * This is a somewhat strange pathological case, but I did encounter it in the wild in a production application (after upgrading Babel, which had apparently been masking the issue in this particular code). I definitely intend to rewrite the relevant code to not have this cyclic dependency for readability and maintainability reasons, but it seems like a case where the code as written should work as expected and not produce a runtime error.
 * If this behavior is to spec and is a wontfix, it could be nice if there was a warning in this case, possibly by including something like [circular-dependency-plugin](https://github.com/aackerman/circular-dependency-plugin) by default.

**Comment by sokra** [comment]
hmm... seems like you hit a limitation here. In certain edge cases the way webpack generates code doesn't allow hoisting function correctly in circular dependencies. In your case you are executing a function of a module before runtime sees the import to that module (before evaluation of the module has started). The ESM spec allows that.

I guess this code would work in production due to module concatenation, which handles hoisting of function better.

As workaround you should be able to switch the order of imports to fix that.

In practice this edge case is pretty rare and in all the years since ESM integration in webpack exists it has not be reported before. It's rare because most code like this would break anyway since you would not be able to access any variable of the scope of the shared module, since they are all still in TDZ or undefined.

**Comment by bregenspan** [comment]
> I guess this code would work in production due to module concatenation, which handles hoisting of function better.

In this case there's also a runtime error in production mode (`Uncaught ReferenceError: Cannot access 't' before initialization` under 5.0.0-beta.16, using default `--mode production` behavior with no config file). But agreed that this case seems very rare and rewriting to avoid it is a workable solution.

Has there been thought to including something like circular-dependency-plugin by default? I think it could help head off these kinds of issues by catching circular dependencies early and strongly recommending against them / encouraging a pattern of whitelisting exceptions for the few cases they're needed. I like that Rollup warns on this circular dependency case. But maybe that's too opinionated to include in the core?

**Comment by sokra** [comment]
> Has there been thought to including something like circular-dependency-plugin by default? I think it could help head off these kinds of issues by catching circular dependencies early and strongly recommending against them / encouraging a pattern of whitelisting exceptions for the few cases they're needed. I like that Rollup warns on this circular dependency case. But maybe that's too opinionated to include in the core?

I had some ideas to detect circular dependencies and improve optimization based on them. But that got a bit stuck as there are dirty ways to hide them so detection would not be relieable enough:

```
// index.js
require("./a");

export function innocentFunction() {
  // lazy imported
  require("./a");
}

// a.js
const b = require("./b");

// b.js
const { innocentFunction } = require("./index.js");
innocentFunction();
```

The module graph is non-circular, but execution is circular at runtime.

So this gets pretty tricky. Probably only possible for ESM. Still tricky when interacting with CJS or other dynamic things.

**Comment by sokra** [comment]
> In this case there's also a runtime error in production mode (`Uncaught ReferenceError: Cannot access 't' before initialization` under 5.0.0-beta.16, using default `--mode production` behavior with no config file). But agreed that this case seems very rare and rewriting to avoid it is a workable solution.

That's actually a bug.

There seem to be wrong behavior for function declarations without name. This works-around the problem:

``` diff
-export default function () {
+export default function name() {
   console.log('shared import');
 }
```

function declarations without name in export default is a little bit of an edge case.

**Comment by bregenspan** [comment]
Thanks for looking into this @sokra! So it seems like there are a lot of good reasons to close this out as "wontfix" for now. It's trivial to rewrite any code affected by this, sounds like it's very rare for the issue to come up, and it only blew up in a production app for me in an unexpected way (following a Babel upgrade) because an older Babel configuration was somehow masking the preexisting issue.

I can close this out and open a new separate issue for the bug with unnamed function declaration in default export with clearer repro for that.

**Comment by jedwards1211** [comment]
@sokra I just ran into this issue in an unreleased version of `openai` I'm working on for Stainless API.  I made [this repo](https://github.com/jedwards1211/webpack-circular-import-bug) to demonstrate the issue.

I think I have a pretty clear idea how to solve this issue, though it would be a somewhat significant change...

The crux of the problem is that
```ts
export { Chat } from "./chat.js";
export { ChatCompletion, Completions } from "./completions.js";
```
gets webpacked into
```js
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   Chat: () => (/* reexport safe */ _chat_js__WEBPACK_IMPORTED_MODULE_0__.Chat),
/* harmony export */   Completions: () => (/* reexport safe */ _completions_js__WEBPACK_IMPORTED_MODULE_1__.Completions)
/* harmony export */ });
/* harmony import */ var _chat_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./chat.js */ "./src/chat.ts");
/* harmony import */ var _completions_js__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ./completions.js */ "./src/completions.ts");
```
`_completions_js__WEBPACK_IMPORTED_MODULE_1__` doesn't even get initialized until `"./chat.js"` finishes initializing, but code in `chat.js` tries to read `Completions`.

The solution would be to create empty module objects and get references to them before evaluating imported modules:
```js
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   Chat: () => (/* reexport safe */ _chat_js__WEBPACK_IMPORTED_MODULE_0__.Chat),
/* harmony export */   Completions: () => (/* reexport safe */ _completions_js__WEBPACK_IMPORTED_MODULE_1__.Completions)
/* harmony export */ });

// Get references to the empty modules before evaluating imports.
// `_completions_js__WEBPACK_IMPORTED_MODULE_1__` will be empty at first,
// but it will get populated when `chat.js` imports `completions.js`.

/* harmony import */ var _chat_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__.initModule(/*! ./chat.js */ "./src/chat.ts");
/* harmony import */ var _completions_js__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__.initModule(/*! ./completions.js */ "./src/completions.ts");

// Actually evaluate the imports
/* harmony import */ __webpack_require__(/*! ./chat.js */ "./src/chat.ts");
/* harmony import */ __webpack_require__(/*! ./completions.js */ "./src/completions.ts");
```

What do you think?  If you're open to this I'd love to work on a PR.

**Comment by alexander-akait** [comment]
@jedwards1211 Sorry for delay, is the problem still valid? Also feel free to send a PR in any cases

**Comment by jedwards1211** [comment]
Yeah still valid, okay I'll try to work on a PR
