### ISSUE TITLE
Empty Module Exports Dramatically Affect Bundle Output

### ISSUE THREAD

**Issue by JasonGore** [webpack/webpack#10889]
# Bug report

While integrating TypeScript 3.9 I noticed significant bundle size regressions and confirmed it was triggered by the [`export *` is always retained](https://github.com/microsoft/TypeScript/wiki/Breaking-Changes#export--is-always-retained) change by using TS nightlies.

I've created a more minimal repro showing that exporting an empty module with no executable code with contents such the one below has significant impact on bundle output.

```
//# sourceMappingURL=DockPanel.Props.js.map
```

**What is the current behavior?**

Adding exports to modules that contain no executable code cause a significant change in bundle output. These images show the effects of adding an export of an empty module with the contents shown above (shown on the left in the images) on bundle output (shown on the right):

**Webpack 4:**

![webpack4](https://user-images.githubusercontent.com/26070760/81861733-8ff4d980-951d-11ea-9992-768bff9b5251.gif)

**Webpack 5:**

![webpack5](https://user-images.githubusercontent.com/26070760/81861745-93886080-951d-11ea-8fe0-d9886b470b9d.gif)

This also has dramatic effects on split chunk behavior, causing wide swaths of code to move between chunks. I'm hoping this minimal repro is the cause of that behavior, but I'm not sure how to confirm that hypothesis at this point.

**If the current behavior is a bug, please provide the steps to reproduce.**

Repros
* [Branch based off `webpack-4`](https://github.com/JasonGore/webpack/tree/webpack-4-empty-module/examples/side-effects-empty-module)
* [Branch based off `webpack-5`](https://github.com/JasonGore/webpack/tree/webpack-5-empty-module/examples/side-effects-empty-module)
* [webpack4-repro patch file](https://github.com/webpack/webpack/files/4624504/webpack4-repro.zip)
* [webpack5-repro patch file](https://github.com/webpack/webpack/files/4624506/webpack5-repro.zip)

All of these contain a new example called `side-effects-empty-module` which can be run using the standard example steps. The key line is in `module-with-export/index.js` which shows dramatic changes to bundle output when commented in and out (effects shown above.)

**What is the expected behavior?**

I've been chatting with @TheLarkInn about this for the past couple of days and agreed we should enter this issue. I don't think empty module exports should affect the bundle output. (Or at least I would like to understand the reason and mitigate the behavior.) 

**Other relevant information:**
webpack version: 4.43.0, 5.0.0-beta.16
Node.js version: 12.16.3
Operating System: Windows 10
Additional tools:

Terms: bundle size regression, ts3.9, typescript 3.9, 3.9.2

**Comment by JasonGore** [comment]
@sokra @evilebottnawi Sean thought your input would be really good on this, so I'd like to hear what you think. 😄

**Comment by sokra** [comment]
Interesting issue. Empty modules seem to cause an problem here because they are no longer considered as ESM, but as CJS module (there is no import or export). Exports are unknown in such a dynamic module and export * is tricky here. But it should not affect direct exports as they have priority over star exports.
Adding `export {}` to empty modules should force them to ESM.
Why is the module empty? Is this transpiled from a type-only typescript module?

**Comment by JasonGore** [comment]
That is correct, this is an example of what type-only TypeScript modules look like.

**Comment by JasonGore** [comment]
One thing I wanted to call out here is that my repro has multiple `export *`'s from the empty module. It seems that all of them are needed to repro this issue and that having just one export will not affect the bundle. I just wanted to point this fact out in case this could be a bug rather than a module specification issue.

**Comment by JasonGore** [comment]
Out of curiosity I also did a [small sample project](https://github.com/JasonGore/babel-empty-module) with Babel to see how it generates ESM with type-only modules. It seems to take the same approach of generating an `export *` of an empty module, which would seem to affect webpack in a similar way. This makes me think Babel users would have previously encountered output similar to what I've provided in my repro. (Although again with the requisite multiple layered `export *`'s of said empty module causing bundling regression.)

**Comment by TheLarkInn** [comment]
@sokra with TS 3.9 people are going to run into this a lot more I fear. How hard is a fix from our side vs. TSC dropping empty modules. (Maybe not even possible given the ts loader scenario?)

**Comment by sokra** [comment]
Already working on that...

Still we could generate even better code with less interop logic if TS would add an `export {}` if it removes all imports and exports.

**Comment by JasonGore** [comment]
I'm not sure this is TS-specific. The babel repro I provided above also generates the same types of modules. I think the use case here is more about layers of libs exporting empty modules rather than TS's output.

**Comment by DanielRosenwasser** [comment]
Yeah, it also likely affects anyone using ts-loader with `transpileOnly` on. If this was optimized away, we might see a nice dip in bundle sizes for similarly structured projects using `transpileOnly` or Babel.

**Comment by sokra** [comment]
Here is the status of this problem from webpack side:

Only investigated in the webpack 5 problem so far. I'll check the webpack 4 thing afterwards (Likely the some problems).

There are two problems:

1. Using `module` inside of a ESM opts out of used exports optimization (Tree Shaking). In the repro this was caused by this module:

``` js
export * from "module-with-export";

module.exports = function(msg) {
	console.log(msg);
};
```

Note that this module is invalid (`module.exports` must not be used when using `export` or `import`) and would throw an exception at runtime. But there are other cases where it would make sense to allow using `module` without opt-out. Like `const m = module; console.log(m.id);`. In CJS using `module` really need to cause an opt-out, as you can access `module.exports` with the `module` object, but in ESM this is not needed.

2. Side-effects optimization doesn't work when there are unknown exports reexported somewhere in the chain. We only implemented the pure-ESM case, where exports are statically known. An empty module has unknown exports (see earlier comment). We can improve the algorithm to handle unknown exports and I'll do so.

Fixing problem 1 would already fix the large bundle size due to the large export in the repro. Fixing problem 2 will cause modules like `./log` to be excluded from bundle, so reduces sized even further.

**Comment by JasonGore** [comment]
Case 1 is not really a valid case in our scenario... this is just a side effect of me trying to repro behavior in a minimal scenario. I should have taken `module.exports` out. Does taking this out fix case 2 as well? Should I work on the repro a bit more?

Just wanted to clarify that in case 2 you aren't changing side effect behavior, only removing unused exports. In our case we don't want other modules with valid side effects to be removed (like log statements) where they previously weren't, either.

Put most simply, I don't think adding an export of a module with no executable code (which would be types modules here) should have any effect on the bundle, regardless of what other non-empty modules are or aren't doing. If the repro isn't showing that clearly enough, I can try and tweak it more.

**Comment by sokra** [comment]
Let me fix these problems before you put more time into the repro

**Comment by sokra** [comment]
I also look into detecting these empty modules, but I still think this is worth fixing in typescript and Babel.

**Comment by sokra** [comment]
@hzoo what do you think about type exports e.g. `export type ...` making a module a ESM and should leave an `export {}` resp. `"use strict";` + `__esModule` when removed? In Babel and typescript.

**Comment by nicolo-ribaudo** [comment]
Is it needed because currently TypeScript uses `import`/`export` to disambiguate ESM and CJS, and doesn't support ESM without any "module syntax"?

**Comment by sokra** [comment]
> Is it needed because currently webpack uses `import`/`export` to disambiguate ESM and CJS, and doesn't support ESM without any "module syntax"?

Yes

> If this is the problem, we could inject `export {}` in the TS Babel plugin when removing an `export type`/`import type` doesn't leave any module syntax, and the file's `sourceType` is `"module"`.

That would be great :)

**Comment by sokra** [comment]
For webpack 5 I managed to fully optimize the case in your repro. Even with the offending `export * from "empty"` the result is now: `(()=>{"use strict";console.log("a","smallVar")})();`

For completeness I add problem 3:

3. Modules with unknown / dynamic provided exports are not considered for module concatenating. I fixed that by using the used exports as replacement for these information. This works as long the used exports are not dynamic or point to dynamic exports. So reexporting a CommonJs module is fine as long you don't reference (possible) exports from it. Together with the side-effect optimization reexported empty modules can be omitted from the bundle.

---

btw with 

```
output: {
	module: true
},
experiments: {
	outputModule: true
}
```

your repro will lead to this output: `console.log("a","smallVar");`

**Comment by robpalme** [comment]
@sokra From your comments in this issue it sounds like webpack has solved the problem of re-exported empty modules leading to bundle bloat.

Given that, does webpack still need TypeScript to [add `export {}` into ambiguous files?](https://github.com/microsoft/TypeScript/issues/38696)

**Comment by sokra** [comment]
Yes.

It would allow to concatenate them with other esm.

If there is some code in the file, removing all imports and exports would make it run in non-strict mode.

If the re-export chain leaves the compilation boundary, this would require weird dynamic exporting. Note you can attach exports to a commonjs module from outside, since it's not frozen like a esm namespace object.

Some improvements where only made for webpack 5 and not for webpack 4 to not risk stability.

**Comment by JasonGore** [comment]
TypeScript created [an emit export issue](https://github.com/microsoft/TypeScript/issues/38696) and merged [a PR](https://github.com/microsoft/TypeScript/issues/38696) that I've tested via the `4.0.0-dev.20200522` nightly and the results look very good. It seems to have negated most if not all of the regressions I saw on bundle output.

**Comment by JasonGore** [comment]
As pointed out earlier that this doesn't appear to be a TypeScript-only issue, as well. The Babel repro I posted earlier also doesn't emit exports.

**Comment by robpalme** [comment]
webpack is in a position to solve this problem (disambiguation of `.js` files) without relying on other projects. The `"type": "module"` declaration in `package.json` was introduced specifically to solve this problem.  See #10958

**Comment by amalitsky** [comment]
Folks, is fix in question available or planned for webpack 4.x? Looks like in 4.x we can't use `experiments: { outputModule: true }` option.

And being angular app we can't go for typescript 4.x version just yet.

Any course of action you could recommend? Thanks

Also huge thanks to topic starter @JasonGore, it was quite a relief to find this issue after spending many hours on debugging. 🎉

**Comment by evilebottnawi** [comment]
> And being angular app we can't go for typescript 4.x version just yet.

What do you mean?

**Comment by amalitsky** [comment]
@evilebottnawi, as far as I know angular version is tightly bound with particular TS version, i.e. the most recent angular version 10 is supposed to be used with TS 3.9.7. Hence we can't simply update TS to 4.x.

I.e [ngtools/webpack package.json file](https://github.com/angular/angular-cli/blob/master/packages/ngtools/webpack/package.json#L31).

**Comment by sokra** [comment]
@amalitsky Are you using the latest webpack version?

**Comment by amalitsky** [comment]
@sokra, we are on 4.42 right now and bumping it to 4.44 didn't change much.

**Comment by evilebottnawi** [comment]
@amalitsky Do you use mini-css-extract-plugin? Can you try master branch?

**Comment by amalitsky** [comment]
@evilebottnawi, we do indeed use _mini-css-extract-plugin_. We will try to use webpack 5.x but that might take some time.

What I've noticed with _index.ts_ files affected is handling of _xxx.types.ts_ imports has changed. In the past if _xxx.types.ts_ was exporting nothing but TS types _index.ts_ importing that types file would get `import * from './xxx.types.ts';` line dropped on some point. Not after upgrade to TS 9.7.

And since _xxx.types.ts_ is empty and not exporting anything (no _declaredExports_), whole module (_index.ts_) exports are used and kind of copy pasted in _xxx.types.ts_.

**Comment by evilebottnawi** [comment]
> And since xxx.types.ts is empty and not exporting anything (no declaredExports)

Can you try to add `export {}`?

**Comment by amalitsky** [comment]
@evilebottnawi, I tried exporting random `const` and it fixed the issue with particular _index.ts_ file. I'll try `export {}` and update this comment.

**Comment by evilebottnawi** [comment]
@amalitsky friendly ping, problems still exists with latest webpack version?

**Comment by amalitsky** [comment]
@evilebottnawi, looks like problem is resolved for us:

![wpba-ts-402](https://user-images.githubusercontent.com/1457274/98150151-1104ac00-1e83-11eb-869a-07e41f1383f5.png)

We are on Webpack 4.44.1 and TS 4.0.2.

Thanks for the follow up

**Comment by evilebottnawi** [comment]
Great, will be great if you try `webpack@5` (most of critical regressions are fixed, so it should be safe), anyway if you faced with the problems again feel free to open new issue(s)
