### ISSUE TITLE
UMD entry point not automatically executed in AMD-enabled cases

### ISSUE THREAD

**Issue by tri170391** [webpack/webpack#10886]
## Feature request

I have a use case where we want our library to be in `umd`  format but want the `amd` part of it to works like `amd-require` format. Basically we expect a global endpoint even if there is an alternative module system in place.

Here is a use case that is very similar to what I have: https://www.haykranen.nl/2013/05/10/the-problem-with-combining-umd-require-js-modules-and-non-umd-modules/

**What is the expected behavior?**

When our `umd` library is used in a `require.js`-active environnement we still want the entry point to be executed and a global entry available.

**What is motivation or use case for adding/changing the behavior?**

We have reports our library when used in `require.js` enabled use case does not execute its entry, which is required for some "environmental" preparation of our library and to coordinate with other loosely-dependent modules that may or may not be required to be bundled with client code.

**How should this be implemented in your opinion?**

Allow a `amd-require`-like variant of `umd` library target.

**Are you willing to work on this yourself?**
no

**Comment by evilebottnawi** [comment]
@tri170391 Sorry fr delay, problem still exists?

**Comment by tri170391** [comment]
Is there an option similar to `amd-require` mode but for UMD instead in latest version og `webpack`?
