### ISSUE TITLE
how to exclude the `browser` field when target is `electron-renderer`

### ISSUE THREAD

**Issue by yinjun1991** [webpack/webpack#10885]
# Bug report

```
webpack: v4.43.0
nodejs: v12.16.3
```

According to the [7953](https://github.com/webpack/webpack/issues/7953), webpack keep the module resolve action the same on targets `electron-renderer` with `web`.

I use the package `nedb` in my electron app project, which support two different versions, node and browser.
I mean to load the nedb node version, so I set webpack config `resolve.mainFields: ['module', 'main']` to exclude the browser field.

But in the out bundle, I found two browser version files of nedb are bundled but not the node version.

The nedb package.json like below:
```
  "main": "index",
  "browser": {
    "./lib/customUtils.js": "./browser-version/browser-specific/lib/customUtils.js",
    "./lib/storage.js": "./browser-version/browser-specific/lib/storage.js"
  },
```

`index.js` requires the two files `./lib/storage` and `./lib/customUtils` indirectly.

I think webpack load the two files according to the path declared in the browser field, but not the correct file `./lib/customUtils.js` and `./lib/storage.js`.

I want to know how to resolve this problem, thank you.

**Comment by sokra** [comment]
`resolve.aliasFields: []`

**Comment by yinjun1991** [comment]
> `resolve.aliasFields: []`

It works! Thank you.

**Comment by finom** [comment]
Doesn't work for me for some reason. I always get

> Uncaught Error: ws does not work in the browser. Browser clients must use the native WebSocket object

But the error disappears if I manually remove "browser": "browser.js" from generated package.json from node_modules

**Comment by panuhorsmalahti** [comment]
I can fix this with:
```
    resolve: {
      // ...
      aliasFields: []
    },
```

in webpack configuration.
