### ISSUE TITLE
a error with DllPlugin

### ISSUE THREAD

**Issue by wangzl1163** [webpack/webpack#10892]
# Bug report
The dll package generated using DllPlugin does not support the module value of the type attribute of script?

**What is the current behavior?**
When the js  introduced in this way， a "vue_library is not defined" error occurs。
`<script type="module" src="/dll/vue.cd23a218.dll.js"></script>`
or
`<script src="/dll/vue.cd23a218.dll.js" nomodule></script>`

**If the current behavior is a bug, please provide the steps to reproduce.**
When the js  introduced in this way， a "dll_library is not defined" error occurs。
`<script type="module" src="/dll/vue.cd23a218.dll.js"></script>`
or
`<script src="/dll/vue.cd23a218.dll.js" nomodule></script>`

**What is the expected behavior?**
no error

**Other relevant information:**
webpack version:  4.43.0
Node.js version: 12.16.2
Operating System: win10
Additional tools:

**Comment by sokra** [comment]
The `var` libraryTarget doesn't work in modules. Try `output.libraryTarget: "global"`

**Comment by wangzl1163** [comment]
> The `var` libraryTarget doesn't work in modules. Try `output.libraryTarget: "global"`
The problem is solved. It works.
