### ISSUE TITLE
Webpack performance per asset

### ISSUE THREAD

**Issue by AdamRubinIL** [webpack/webpack#10891]
## Feature request

**What is the expected behavior?**
I would like to control the weight of each file created by webpack. 
for now, we can only decide maxAssetSize for all output files. 

**What is motivation or use case for adding/changing the behavior?**
I want to be sure that some files on my project won't cross one size and other files another size.

**How should this be implemented in your opinion?**
current status:
```
performance: {
			hints: "error",
			maxAssetSize: 160000
		}
```
expected: 
```
performance: {
			hints: "error",
			defaultMaxAssetSize: 160000,
                         maxAssetSize: [{filename: REGEX, size: 50000}]
		}
```
 
**Are you willing to work on this yourself?**
yes

**Comment by yuripramos** [comment]
What version of Webpack are you using? I guess I the Latest release of webpack@5 you can manage that.

**Comment by AdamRubinIL** [comment]
I see in the documentation https://webpack.js.org/configuration/performance that there is a performance.assetFilter however it's just filter files to checks. How can I manage each asset and it's the weight of it? It would be wonderful if you can point on something that I'm missing.

> What version of Webpack are you using? I guess I the Latest release of webpack@5 you can manage that.

**Comment by evilebottnawi** [comment]
Bump
