### ISSUE TITLE
Relative source file in sourcemap from output files

### ISSUE THREAD

**Issue by TimVosch** [webpack/webpack#10896]
https://github.com/TypeStrong/ts-loader/issues/1105
https://stackoverflow.com/questions/61442109/change-webpack-sourcemap-relative-path-context

Not sure if this is a bug or would be a feature request. It could also be classified as support, I am confused as well.

### Expected Behaviour
When TSC outputs sourcemaps it references the original file from the context of the output directory. (starts with two dots)
This allows Visual Studio Code to automatically detect the original files, since the relative path - as seen from the output file - is correct.

**dist/main.js.map**
```
source: ["../src/main.ts"]
```

### Actual Behaviour
Webpack + TS-Loader references the original files from the directory of the webpack.config.js. (Notice a single dot)

**dist/main.js.map**
```
source: ["./src/main.ts"]
```

### Steps to Reproduce the Problem
Create a project using webpack and ts-loader with the following configuration:

```js
{
  mode: "development",
  target: "node",
  entry: "./src/main.ts",
  output: {
    filename: "main.js",
    path: path.resolve(__dirname, "dist"),
  },
  externals: [nodeExternals()],
  module: {
    rules: [
      {
        test: /\.ts$/,
        exclude: /node_modules/,
        loader: "ts-loader",
      },
    ],
  },
  resolve: {
    extensions: [".js", ".ts"],
    plugins: [new TsconfigPathsPlugin()],
  },
  devtool: false,
  plugins: [
    new webpack.SourceMapDevToolPlugin({
      filename: "[name].js.map",
      moduleFilenameTemplate: "[resource-path]",
      noSources: true,
      module: true,
    }),
  ],
}
```

### Location of a Minimal Repository that Demonstrates the Issue.
`git clone https://github.com/TimVosch/webpack-tsloader`
`cd webpack-tsloader`
`npm run build`

**Comment by evilebottnawi** [comment]
Why do not use `moduleFilenameTemplate: "../[resource-path]"`?
