### ISSUE TITLE
Load of an emscripten runtime

### ISSUE THREAD

**Issue by polx** [webpack/webpack#10890]
## Feature request

It seems that emscripten has become a very widespread system to compile and package C and C++ files to the web-world, web-assembly or JS. It does so by generating JavaScript that loads other elements of varying size.

I have started to fork the [emscripten loader](https://github.com/wasm-tool/emscripten) to my repo [webpack-emscripten](https://github.com/polx/webpack-emscripten) and write the two classical phases of C++ compilations as two separate loaders: cpp-loader (the compilation) and cpp-packager (the linker).

Currently, the Emscripten javascript generation only delivers an asynchronous way to obtain the functions after the wasm modules are loaded: At best it is an es6-promise.

_Would it be possible for an exported promise to be resolved when it is imported?_

**What is the expected behavior?**

This way, I could do:
`import {MyCppClass1, MyCppClass2} from 'EmscriptenModule.emsc.js'`

**What is motivation or use case for adding/changing the behavior?**

What I have found thus far either is too simple (wasm-tool/emscripten's example is a simple C class with a single function) or  still requires to call `then` or simply ignore the imports.

Incorporating the emscripten runtime seems to be a good practice as the exposed JavaScript takes care of quite some integration, in particular of a set of readable glue elements between C++ and JavaScript.

**How should this be implemented in your opinion?**

Here, I am afraid that I don't know yet.

**Are you willing to work on this yourself?**
yes

**Comment by sokra** [comment]
> Would it be possible for an exported promise to be resolved when it is imported?

I think you are looking for `top level await`, which comes with webpack 5

**Comment by polx** [comment]
That's an excellent suggestion @sokra. I've been following the inspiration in [this gist](https://gist.github.com/sokra/33f3db1b2714e9a6720f890842c47ae6).

Indeed, it has helped me revise the loader and create an example that applies the top level await. My [app.js](https://github.com/polx/webpack-emscripten/blob/master/example/src/app.js#L5) uses `import await` but then still needs to await the result within an async function. Is there an optimization possible here or is this part of the nature of asyncs?

thanks much

Paul

**Comment by sokra** [comment]
This gist was a proposal, but has not become part of the spec.
Check the original proposal for the correct syntax.

You need:

```js
experiments: {
  topLevelAwait: true,
  importAsync: true
}
```

in webpack 5, but this will no longer be needed once it's in stage 4.

**Comment by polx** [comment]
Did I understand properly the beta release-notes that top-level-await is not supported anymore?

At least the two experiments' settings are not valid anymore, importAsync seems now standard but a line such as `import await emscriptenRuntime from './cpp-classes.emsc.js';` breaks in the current beta (beta-29) if the experiments are away.

**Comment by evilebottnawi** [comment]
@polx it is not broken, you should use `experiments`

**Comment by polx** [comment]
I wish you were right @evilebottnawi but that's not what it tells me:


		git clone 'https://github.com/polx/webpack-emscripten.git'
		cd webpack-emscripten
		cd example
		npm install
		node node_modules/webpack/bin/webpack.js --mode development

		[….]

		  postFormatter: [Function: postFormatter],
		  message: 'Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.\n' +
		    " - configuration.experiments has an unknown property 'importAsync'. These properties are valid:\n" +
		    '   object { asset?, asyncWebAssembly?, mjs?, outputModule?, syncWebAssembly?, topLevelAwait? }\n' +
		    '   -> Enables/Disables experiments (experimental features with relax SemVer compatibility).'
		}

(I also try removing importAsync or importAwait from experiments but it did not help)

Maybe the experiments' names have changed?

paul

**Comment by evilebottnawi** [comment]
`importAwait` and `importAsync` was removed, it is `true` by default right now

**Comment by polx** [comment]
Ok. emptied the `experiments` object. Now I get:

        ERROR in ./src/app.js 1:7
        Module parse failed: Cannot use keyword 'await' outside an async function (1:7)

The line is just `import await emscriptenRuntime from './cpp-classes.emsc.js';` .

**Comment by evilebottnawi** [comment]
Set `topLevelAwait: true` :smile:

**Comment by polx** [comment]
* In experiments? (same "cannot use keyword" error as above).
* outside? (property of module.exports): inappropriate config

Thanks for your help.

**Comment by evilebottnawi** [comment]
> In experiments

hm, I will look at this in near future

**Comment by evilebottnawi** [comment]
@polx code is not valid :confused: 
```
import await emscriptenRuntime from './cpp-classes.emsc.js';
```

**Comment by polx** [comment]
You mean it's not valid-JS?  `import await` has never been valid-JS or?
So what would otherwise be an example for `import await` ?

**Comment by evilebottnawi** [comment]
@polx 
```js
const myModule = await import('file.js');
```

**Comment by polx** [comment]
Hello @evilebottnawi, I did try quite a few things around your suggestion but I couldn't get it to work: At the end, the object I obtain is not usable or resolvable... This is examplified in [line 5 of my example's app.js](https://github.com/polx/webpack-emscripten/blob/master/example/src/app.js#L5).

However, the `import`, as well as the `await` of the imported object a few lines later does have the useful side effect that the exported object, which is also set as a property defined on the `window` object ([here](https://github.com/polx/webpack-emscripten/blob/master/cpp-packager.js#L117)), is usable and its resolution gives the appropriately loaded emscripten object (often called "Module"). Definitely a convoluted hack but the only method I found to upgrade out of the beta and, as a cherry on the cake, to debug-browse the C/C++ code in Firefox and Chromium.

If you have hints on making this `import` smoother and thus get rid on the window property, that would be great.

**Comment by evilebottnawi** [comment]
It is how JS works, I don't see webpack problems here

**Comment by polx** [comment]
It would be cool if you have a working example of an `import await`.

**Comment by evilebottnawi** [comment]
Can you look at your code and configuration?

**Comment by polx** [comment]
I don't understand your question. Are you trying to ask me to look my code and see something in particular?
I believe that I have some knowledge of my code, indeed. But I also believe that I do not see the answer to my question in my code right now.

**Comment by evilebottnawi** [comment]
@polx I mean create simple example:
- what you have
- what you actually have
- what you expect
- your configuration

Because what you want to do I think should work without problems webpack@5
