### ISSUE TITLE
ModuleNotFoundError: Module not found

### ISSUE THREAD

**Issue by matyaspeto** [webpack/webpack#10899]
I don't think this is an issue with webpack itself, but I have no better idea, where to ask.

I had zero changes in my code in past few days, also there was zero change in my dev environment, except a windows update (this is the only thing I can think, that possibly caused this)

Windows version: 1903
Build number: 18362.836
NodeJS: 10.15.1
@symfony/webpack-encore: ^0.22.0

After the update I can't execute my webpack project properly, because it's complaining about "ModuleNotFoundError: Module not found" for several files. 

The files location did not change recently, neither the references to them, so I have no idea how to fix this. 2 days ago it was just fine, Webpack was able to pack all my resources as expected.

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
