### ISSUE TITLE
Alias behaving as relative

### ISSUE THREAD

**Issue by pherrymason** [webpack/webpack#109]
I think I've found a bug regarding `resolve.alias`.
I got the following in `webpack.config.js`:

``` javascript
resolve : {
        alias: {
            jquery      : "../vendor/jquery/jquery-1.10.2.js",
            underscore  : "../vendor/backbone/underscore.js",
            backbone    : "../vendor/backbone/backbone.js"
                }
         }
```

When executing webpack it complains not being able to found `underscore`:

```
ERROR in ../vendor/backbone/backbone.js
Module not found: Error: Cannot resolve file or directory ../vendor/backbone/underscore.js in /Users/raulferras/dev/htdocs/pumbao/desktop/src/js/vendor/backbone.
 @ ../vendor/backbone/backbone.js 41:50-71
```

However, if I change `webpack.config.js` to this:

``` javascript
resolve : {
        alias: {
            jquery      : "../vendor/jquery/jquery-1.10.2.js",
            underscore  : "./underscore.js",
            backbone    : "../vendor/backbone/backbone.js"
                }
         }
```

It works ok.
Underscore is being required inside `backbone.js` and it seems like there the path is being used as a relative path from `backbone.js`'s path and not from the entry file. Is this intended behaviour? Should I stick with an absolute path to be able to require `underscore` from different modules located in different paths?

**Comment by hackfaq** [comment]
Hello, issue not resolved, I have experienced same problem till found this issue.
