### ISSUE TITLE
minsize doesn't work as expected

### ISSUE THREAD

**Issue by novaknole** [webpack/webpack#10908]
# Bug report

**What is the current behavior?**

I am using this `splitChunksPlugin` settings.

```js

output: {
        path:  path.resolve(__dirname, 'dist'),
        filename: '[name].js',
        chunkFilename: '[name].js'
    },


optimization: {
        splitChunks: {
            chunks: 'all',
            minSize:50000,
            minChunks: 1,
            cacheGroups: {
                vendor: {
                    minChunks: 1,
                    test: /[\\/]node_modules[\\/]/,
                    name (module) {
                        const packageName = module.context.match(/[\\/]node_modules[\\/](.*?)([\\/]|$)/)[1];
                        return `npm.${packageName.replace('@', '')}`;
                    }
                },
                default: false,
                vendors: false
            }
        }
    },
```

```js

// app.js
import(/* webpackChunkName: "test1" */ "./test1")
import(/* webpackChunkName: "test2" */ "./test2")

// test1.js
import HammerJS from 'hammerjs'

// test2.js
import HammerJS from 'hammerjs'
```

Running `npm run production` causes these files to be generated...

```
  main.js   2.16 KiB       1  [emitted]  main
npm.hammerjs.js   19.9 KiB       0  [emitted]  npm.hammerjs
       test1.js  103 bytes       2  [emitted]  test1
       test2.js  104 bytes       3  [emitted]  test2
```

Even though I am using `minSize:50000` (which is 50kb), it still creates `npm.hammer.js` as a separate file.

**What is the expected behavior?**

expected behaviour is that by using `minSize:50000` , it shouldn't be creating `npm.hammerjs` as a separate chunk.

**Other relevant information:**
webpack version:  4.43.0
Node.js version: 10.11.0
Operating System:  MacOS latest
Additional tools:

**Comment by sokra** [comment]
minSize is calculated from the unminimized source code size. Try `optimization.minimize: false` to get a better size for testing

There are technical reasons for that. Chunk splitting is done before minimizing, so we don't know the mininized size.

**Comment by novaknole** [comment]
@sokra 

I set `minimize:false` . Now it turns out this is what bundle information looks like:
```
       main.js   8.41 KiB       1  [emitted]  main
npm.hammerjs.js   72.3 KiB       0  [emitted]  npm.hammerjs
       test1.js  464 bytes       2  [emitted]  test1
       test2.js  458 bytes       3  [emitted]  test2
```

As you can see, it's 72.3 KiB. I am setting minSize: 220000,  but still, new file(npm.hammerjs.js) gets generated.  Any clue ?  The least `minSize` that causes the new file NOT to be generated is `230000` which seems so large. 230kb is so bigger than 72.3KIB . still correct behaviour ?

**Comment by novaknole** [comment]
Looks like,  my `vendor` cacheGroup causes this..

```js
 vendor: {
                    minChunks: 1,
                    test: /[\\/]node_modules[\\/]/,
                    name (module) {
                        const packageName = module.context.match(/[\\/]node_modules[\\/](.*?)([\\/]|$)/)[1];
                        return `npm.${packageName.replace('@', '')}`;
                    }
                },
```,

but why? I set `minSize` in the `splitChunks` settings which is the parent of cacheGroup, so `minSize` should be applied to my `vendor` group too. But still it's not.

Could it be that when I set `minChunks:1`, it overrides whatever `minSize` I have ?

**Comment by novaknole** [comment]
@sokra 

**UPDATE** : which one is more prioritized: `minChunks` or `minSize`. I am seeing a very strange behaviour. 

```js
splitChunks: {
            chunks: 'all',
            minSize: X,
            minChunks: Y,
            cacheGroups: {
                vendor: {
                    test: /[\\/]node_modules[\\/]/,
                    name (module) {
                        const packageName = module.context.match(/[\\/]node_modules[\\/](.*?)([\\/]|$)/)[1];
                        return `npm.${packageName.replace('@', '')}`;
                    }
                },
                default: false,
                vendors: false
            }
        }
```

Let's change `minSize` and `minChunks` accordingly.

 1) `minSize: 220000`, `minChunks` : 1 - This  causes `npm.hammer.js` to get created.
 2) `minSize: 230000`, `minChunks` : 1 - This  DOESN'T cause `npm.hammer.js` to get created.

 1) `minSize: 72000`, `minChunks` : 2 - This  causes `npm.hammer.js` to get created.

 1) `minSize: 75000`, `minChunks` : 2 - This  DOESN'T `npm.hammer.js` to get created.


if `npm.hammer.js` appears as the build output, it shows the the size : 19.9 KIB.  and I import `hammerjs` library in two `async` modules. So I am not sure why changing these settings above behave very strange.

**Comment by sokra** [comment]
I think I randomly found the bug that caused this weird behavior. Cache groups with minSize unset or 0 caused some NaNs in the splitChunks plugin which makes sorting behave really weird. I hope this is fixed now and behave as configured.

**Comment by evilebottnawi** [comment]
@novaknole Can you test it with webpack@5?
