### ISSUE TITLE
webpack sometimes just aborts without any feedback or error message

### ISSUE THREAD

**Issue by doberkofler** [webpack/webpack#10903]
# Bug report

I'm fully aware that this is not enough information to track down a possible problem, but I would hope to eventually gain some information on how to better understand what's going wrong.

Over the last few weeks I noticed an increasing number of occurrences when webpack build to just aborts without any feedback or error message:

I'm running with the `--progress` progress option and the last message I see is some like this:
```bash
> webpack --progress
...
67% building 2376/2476 modules 100 active ...modules/stylus-loader/index.js??ref--5-3!/Users/doberkofler/MyDev/ljs_app/trunk/periscope/src/modules/las_mod_communication/module.styl%
~ $
````

If I run webpack once again it works like expected and finishes like this:

```bash
...
Version: webpack 4.43.0
Time: 38136ms
Built at: 05/16/2020 2:20:44 PM
                         Asset       Size                       Chunks             Chunk Names
  dmo_dlg_createdemoaccount.js    232 KiB    dmo_dlg_createdemoaccount  [emitted]  dmo_dlg_createdemoaccount
~ $
````

Is there anything I can do to debug this problem ?

**Other relevant information:**
webpack version:  4.43.0
Node.js version: 14.2.0
Operating System: macOS 10.15.4
Additional tools:

**Comment by evilebottnawi** [comment]
Without full information we can't help, maybe problem in `stylus-loader`

**Comment by sokra** [comment]
This might happen when a loader doesn't call the callback. Try `paralellism: 1` and `--progress` and you might see the offending module.

**Comment by doberkofler** [comment]
Thank you. It seems to have been fixed by updating all webpack dependencies.
