### ISSUE TITLE
Externalized dependencies to be imported by chunk

### ISSUE THREAD

**Issue by privatenumber** [webpack/webpack#10909]
## Feature request
For chunks to request its own externalized modules

**What is the expected behavior?**
If an application depends on `lodash` but is only being used by one chunk, the request to load `lodash` should come from the chunk rather than the entry point.

**What is motivation or use case for adding/changing the behavior?**
In a large application, using Dll or externalizing dependencies can help reduce the build time/size. However, externalized dependencies currently get requested by the entry-points before the chunks that need them are even loaded.

Depending on how many dependencies the application has, this could load a ton of modules that are yet to be useful on page-load, and that kind of defeats the point of code-splitting.

Demo of this behavior [here](https://github.com/privatenumber/webpack-playground/blob/master/externals/dist/amd/main.js)

**How should this be implemented in your opinion?**
Library wrappers in chunks. For example, if AMD, each chunk can be wrapped in AMD to load its dependencies.

**Are you willing to work on this yourself?**
might not be qualified for it but with enough time and guidance, perhaps

**Comment by artola** [comment]
@privatenumber   is it similar to: https://github.com/webpack/webpack/issues/5489. ?

**Comment by privatenumber** [comment]
@artola It is, thanks!
