### ISSUE TITLE
Production mode won't display any shaders or images

### ISSUE THREAD

**Issue by Sophia-98** [webpack/webpack#10911]
# Bug report

**What is the current behavior?**

- Production mode when built doesn't display images and other non js, html and css files such as shaders (development mode is fine). The images are definitely within the dist folder so it's not an issue of modules.
- It would only display in production mode when I put all the image files not as an import but as a direct src link not relative to the js file. e.g `<img src = "../src/etc."/>` instead of `import img as "../../js/etc"` `<img src = {img}/>`. (using this way of sourcing doesn't allow me to use shaders.)
- However, If I were to deploy this onto a server the same issue would arise again despite it working in live server in production mode.  

**If the current behavior is a bug, please provide the steps to reproduce.**

The app must have react-router dom with many routes as the first page that loads is the only one that seems to work properly

Here is my repository simplifying what is going on in my web application
https://github.com/Sophia-98/issue

**What is the expected behavior?**

- The expected behavior is for it to work exactly as it does in dev server and for the images and other files such as shaders to be displayed correctly. 

**Other relevant information:**
-  When using making a quick react app with 'create-react-app' I was able to use static server and would work on my local port. But if I were to do it with this file it would give a 404 error not found.

webpack version:  4.42.0
Node.js version: 6.14.2
Operating System: Windows 10
Additional tools: Visual Studio Code

**Comment by evilebottnawi** [comment]
All works fine, if you open `dist/index.html` you will see images, works fine with static server too, feel free to feedback, if you still have problems, please provide more information, sorry for delay
