### ISSUE TITLE
Imported modules are wrapped in a "default" namespace when passed to a function.

### ISSUE THREAD

**Issue by iclanton** [webpack/webpack#10928]
# Bug report

**What is the current behavior?**

Importing a JSON module with the `import * as x from './path.json';` syntax, and then passing the module object to a function causes the module to be wrapped in a `"default"` namespace.

**If the current behavior is a bug, please provide the steps to reproduce.**

There's a pretty simple repro here: https://github.com/iclanton/webpack-import-repro

After installing dependencies, run `npm run build`, and then run `node dist/test.js`. The `package.json` file's "name" property will be printed to the console, and then `undefined` will be printed to the console.

**What is the expected behavior?**

The module should not be wrapped in a `"default"` namespace. In the repro repo, the `package.json`'s "name" property should be printed to the console twice.

**Other relevant information:**
webpack version: 4.43.0
Node.js version: v10.19.0
Operating System: Windows 10
Additional tools:

**Comment by sokra** [comment]
This is fixed in webpack 5. It will also print this warning:

```
WARNING in ./src/index.js 7:12-28
Should not import the named export 'name' (imported as 'packageJson') from default-exporting module (only default export is available soon)
```

It's telling you that you are using JSON modules incorrectly. The official spec says that only a `default` export is available for JSON. So you better change your import to `import x from './path.json'`, since this is the spec'ed way.

**Comment by iclanton** [comment]
@sokra - Using `import packageJson from '../package.json';` syntax, the object isn't tree-shaken and the property names aren't minified in `production` mode. I see that this is fixed in Webpack 5, but this is currently broken in Webpack 4.

Can you point me to the spec? I'm having trouble finding it.

**Comment by sokra** [comment]
See link in this issue https://github.com/webpack/webpack/issues/9246
