### ISSUE TITLE
Upgrade watchpack for node 14 compatibility

### ISSUE THREAD

**Issue by ErinCall** [webpack/webpack#10924]
With [node v13's EOL looming](https://nodejs.org/en/about/releases/), I'm trying to get a repo upgraded to v14, but webpack is currently incompatible:

* webpack 4.43.0 requires watchpack^1.6.1
* watchpack <1.7 requires chokidar^2.1.8
* chokidar <3 requires fsevents^1.2.7
* fsevents <2 does not support node v14

webpack/watchpack#153 added support for chokidar3, so I imagine the fix is as simple as updating the watchpack dependency in `package.json`, but I don't know what the knock-on effects might be. If that's sufficient, I'll happily submit a PR 🙂

**What is the current behavior?**

Installing webpack on node 14.x causes `deprecated`/`notsup` warnings.

**If the current behavior is a bug, please provide the steps to reproduce.**

```
$ node -v
v14.1.0
$ npm -v
6.14.4
$ npm init -y
[snip (full output below)]
$ npm install webpack
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
[snip]
npm WARN notsup Unsupported engine for watchpack-chokidar2@2.0.0: wanted: {"node":"<8.10.0"} (current: {"node":"14.1.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: watchpack-chokidar2@2.0.0
[snip]
```

**What is the expected behavior?**

`npm install watchpack` succeeds without warnings

**Other relevant information:**
webpack version:  4.43.0
Node.js version: 14.1.0 (I've also seen it on 14.2.0)
Operating System: OSX (I've also seen it on Alpine)
Additional tools: npm 6.14.4

<details>
<summary><b>Full shell output:</b></summary>

```
$ node -v
v14.1.0
$ npm -v
6.14.4
$ npm init -y
Wrote to /Users/erincalling/code/futzing/package.json:

{
  "name": "futzing",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}

$ npm install webpack
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.

> fsevents@1.2.13 install /Users/erincalling/code/futzing/node_modules/watchpack-chokidar2/node_modules/fsevents
> node install.js

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN notsup Unsupported engine for watchpack-chokidar2@2.0.0: wanted: {"node":"<8.10.0"} (current: {"node":"14.1.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: watchpack-chokidar2@2.0.0
npm WARN futzing@1.0.0 No description
npm WARN futzing@1.0.0 No repository field.

+ webpack@4.43.0
added 348 packages from 210 contributors and audited 348 packages in 11.57s

5 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

$
```
</details>

**Comment by nolimitdev** [comment]
The same warnings are not only for node v14 but almost any other. On latest LTE node v12.6.3:

```
$ npm install webpack
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN notsup Unsupported engine for watchpack-chokidar2@2.0.0: wanted: {"node":"<8.10.0"} (current: {"node":"12.16.3","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: watchpack-chokidar2@2.0.0
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\watchpack-chokidar2\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
```

I think it is annoying and should be fixed. Installing new latest webpack version should not produce so many warnings.

**Comment by evilebottnawi** [comment]
@ErinCall you need install `chokidar@3` manually, just run `npm i -D chokidar`, we can't update it because it is a breaking change, so we provide ability to install latest version manually. Fixed for webpack@5.

@nolimitdev 
It is just a warning, ignore it. It was done for supporting watch on macos and node@14.

**Comment by ErinCall** [comment]
Oh, I see what's happening—the warnings still appear since watchpack ensures chokidar v2 is _available_, but as long as I ensure I'm getting an updated watchpack¹, the chokidar it actually _uses_ is v3. Thanks for helping to clarify!

¹ it doesn't need to be specified in a newly-created codebase, but the existing one needed a `--save-dev watchpack`

**Comment by uchuugaka** [comment]
Warnings should NEVER be ignored but it _would_ help if they were more clear or did not occur.
Thankfully, this issue existed so I could find this information.
Warnings are great!

**Comment by lfender6445** [comment]
I had this issue on node 12 after a few upgrades and I was able to resolve the issue with:

```
npm install --save-dev watchpack-chokidar2
```
