### ISSUE TITLE
webpack can incorrectly remove transitive side effects

### ISSUE THREAD

**Issue by sgomes** [webpack/webpack#10939]
# Bug report

It appears that there are situations in which declared side effects are not preserved, if they're coming through a module which has had its exports tree-shaken.

This is best explained with an example.

I [prepared a project](https://github.com/sgomes/webpack-transitive-side-effects-bug) with a single file containing a side effect, creatively named `src/side-effect.js`:

```js
// This console.log is a side effect, which runs on module load.
console.log( 'side effect' );

export function somethingElse() {
}
```

This file is declared as containing side effects in a `src/package.json` file:

```json
{
  "sideEffects": [
    "./side-effect.js"
  ]
}
```

`src/side-effect.js` is imported in `src/middle.js` through a naked import. This `src/middle.js` module exports a single function, `removeMe`:

```js
// Naked import.
// The file is marked as having side effects in package.json, so its side
// effects should be preserved.
import "./side-effect";

export function removeMe() {
  console.log( 'removeMe' );
}
```

The entry point for the project is `src/index.js`, which imports `removeMe` from `src/middle.js`, without actually using it:

```js
// Unused import.
// It should get tree-shaken away.
// However, the 'middle' module also contains transitive side effects, which
// should be preserved.
import { removeMe } from "./middle";

function main() {
}

main();
```

So, to summarise: `index.js` asks for `removeMe` from `middle.js` and doesn't use it, making the function a candidate for tree-shaking (cleverly illustrated by its ingenious name). But `middle.js` doesn't just export that function; it also imports `side-effect.js`, which contains a side effect.

**What is the current behavior?**

The side effect is not preserved, with the final output being (cleaned up to the relevant portion):

```js
"use strict";
__webpack_require__.r(__webpack_exports__);
// Unused import.
// It should get tree-shaken away.
// However, the 'middle' module also contains transitive side effects, which
// should be preserved.


function main() {}

main();
```

If we analyse the `webpack` verbose output, `middle.js` is never even loaded:

```
Hash: bb18082f22d189219cdc
Version: webpack 4.43.0
Time: 247ms
Built at: 05/21/2020 5:20:48 PM
    Asset      Size  Chunks             Chunk Names
bundle.js  3.84 KiB       0  [emitted]  main
Entrypoint main = bundle.js
chunk    {0} bundle.js (main) 219 bytes [entry] [rendered]
    > /path/test/src main
 [0] ./src/index.js 219 bytes {0} [depth 0] [built]
     [no exports]
     single entry /path/test/src  main

LOG from webpack.buildChunkGraph.visitModules
<t> prepare: 0.421189ms
<t> visiting: 0.081341ms
```

**If the current behavior is a bug, please provide the steps to reproduce.**

- Clone [the test repo I prepared](https://github.com/sgomes/webpack-transitive-side-effects-bug)
- `npm ci`
- `npm run build`
- Analyse `dist/bundle.js`

**What is the expected behavior?**

Declared side effects should be preserved, regardless of whether they're directly or transitively imported.

In the example, the expected behaviour is that `dist/bundle.js` would include the `console.log( 'side effect' );` side effect that is imported from `src/side-effect.js`.

In order to get the example to work, both `side-effect.js` and `middle.js` have to be declared in `sideEffects`. However, this should not be necessary, as `middle.js` does not include any side effects of its own, and it results in the unnecessary `removeMe` function being included as well.

**Other relevant information:**
webpack version:  4.43.0
Node.js version: v12.16.0
Operating System: macOS 10.15.4 (19E287)
Additional tools:
```
"@babel/core": "^7.9.6",
"@babel/preset-env": "^7.9.6",
"babel-loader": "^8.1.0",
"webpack-cli": "^3.3.11"
```

**Comment by vankop** [comment]
I am not sure that this intended to work this way. It works only for direct import from `node_modules`, see https://github.com/vankop/webpack-transitive-side-effects-bug

**Comment by sokra** [comment]
Yep this behavior is by design. It allows to kind of "override" side effects of dependencies.

The most prominent example is a Component which imports some stylesheet. The stylesheet itself has side effects (apply style to the Dom), but the component is side effect free. It basically says: "while my dependencies have side effects, these are not relevant when not using me". So if the component is not used the styles are also excluded.

**Comment by sokra** [comment]
In your example if you expect that `middle.js` triggers the side effect of their dependency, you can say it's side effect free.

**Comment by sgomes** [comment]
Thank you for getting back to me so quickly, @vankop, @sokra! 

> In your example if you expect that `middle.js` triggers the side effect of their dependency, you can say it's side effect free.

I understand your point, but wouldn't that extend all the way to the root, by the transitive property? That is to say, if we follow that logic, we wouldn't be able to say that `index.js` in the example is side effect free either, and thus we'd need to declare it in `sideEffects` as well.

My expectation was that if I were to declare the file with the actual side effect, I could have the bundler automatically determine the side effect propagation through the dependency graph. Having to declare the transitive set importers of that file seems like something that would require a large amount of maintenance as a codebase evolves and the dependency graph changes 😕 

Is there any other way of preserving the side effect?

**Comment by sgomes** [comment]
Here's another way of looking at the situation that illustrates the mismatch between my expectation and my understanding of the implementation, as you describe it.

- Preserving the side effect should work at level 0; that is, when the file being declared is the entry point.
- It also should work at level 1; that is, when the file being declared is imported by the entry point.
- However, at levels 2 and beyond, it won't necessarily work, and you'll need to declare the intermediate levels.

I realise I may be looking at this incorrectly, but I hope it helps to illustrate my point of view.

**Comment by vankop** [comment]
> Here's another way of looking at the situation that illustrates the mismatch between my expectation and my new understanding of the implementation, as you describe it.
> 
> * Preserving the side effect should work at level 0; that is, when the file being declared is the entry point.
> * It also should work at level 1; that is, when the file being declared is imported by the entry point.
> * However, at levels 2 and beyond, it won't necessarily work, and you'll need to declare the intermediate levels.

[exports entrypoint](https://nodejs.org/api/esm.html#esm_package_entry_points) will solve this problem.

> Is there any other way of preserving the side effect?

Unfortunately, I don't know..

**Comment by sgomes** [comment]
Thanks, @vankop! Any chance you or @sokra could add some clarity to the points I raised in https://github.com/webpack/webpack/issues/10939#issuecomment-632305810 ? At which point can we stop declaring side effects?

From @sokra's comments, my understanding is that `webpack` was designed so that we need to specify both the file with the side effects and any direct importer of that file. Is that sufficient, or do we also need to declare any importers of those importers?

Also, is it somehow possible to still tree-shake unused exports from a file that's marked as having side effects, while leaving the side effects in place? In my example, if I mark `middle.js` as having side effects, then `removeMe` is no longer tree-shaken, even though it's unused.

**Comment by sokra** [comment]
Yes if your side effect is something globally visible you need to declare all importers and importers of importers as having side effects. All these files have a side effect when imported.

Tree shaking will side work. It will keep all code that has side effects according to terser (which is properly more than you intend, you may help with a pure annotation).

Best avoid side effects during importing at all.

**Comment by sgomes** [comment]
Thank you again, @sokra and @vankop! 

I'm closing this issue, as I walked away with a much better understanding of how `webpack` handles side effects. My assumptions about how they get preserved were wrong, and if things had been implemented they way I expected, it would ultimately make it very difficult to ever tree-shake any side effects away!

My take-away from all this is that side-effectful modules should be imported as closely as possible to the code actually making use of them, so that they're always closely coupled and one is never present without the other. Relying on a parent or child module to import side effects for you may result in inconsistencies as things get tree-shaken away.

In fact, it's best to err on the side of caution and import them in multiple places, if need be, taking advantage of the fact that modules only run once.

Hope this helps anyone stumbling across this issue in the future!
