### ISSUE TITLE
compile twice

### ISSUE THREAD

**Issue by PT-github** [webpack/webpack#10937]
hello, I don't know why. The same webpack config it compile twice when in hot update in window. In mac,it's OK! Please help me. 
I'm sorry my English is very poor. I don't know if you know what I mean

my webpack.config.js

module.exports = {
  mode: 'development',
  entry: {
    app: path.resolve(__dirname, '../example/index.js')
  },
  output:  {
    path: path.resolve(__dirname, '../dist'), // 必须是绝对路径
    filename: 'app.js'
  },
  module: {
    noParse: /^(vue|vue-router|vuex|vuex-router-sync)$/,
    rules: [
      {
        test: /\.md$/,
        use: [
          {
            loader: 'vue-loader',
            options: {
              compilerOptions: {
                preserveWhitespace: false
              }
            }
          },
          {
            loader: path.resolve(__dirname, './md-loader/index.js')
          }
        ]
      },
      {
        test: /\.tsx?$/,
        use: {
          loader: 'ts-loader',
          options: {
            appendTsSuffixTo: [/\.vue$/]
          }
        },
        exclude: /node_modules/ // 排除 node_modules 目录
      },
      {
        test: /\.jsx?$/,
        use: {
          loader: 'babel-loader',
          options: {
            cacheDirectory: true,
          }
        },
        exclude: /node_modules/ // 排除 node_modules 目录
      },
      {
        test: /\.(le|c)ss$/,
        use: [
          // 'vue-style-loader',
          {
            loader: MiniCssExtractPlugin.loader,
            options: {
              hmr: true,
              esModule: true
            }
          },
          'css-loader',
          'postcss-loader',
          'less-loader'
        ],
      },
      {
        test: /\.(sa|sc)ss$/,
        use: [
          {
            loader: MiniCssExtractPlugin.loader,
            options: {
              hmr: true,
              esModule: true
            }
          },
          'css-loader',
          'postcss-loader',
          'sass-loader'
        ]
      },
      {
        test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/i,
        use: [
          {
            loader: 'url-loader',
            options: {
              limit: 10240,
              fallback: {
                loader: 'file-loader',
                options: {
                  publicPath: "./",
                  outputPath: 'styles',
                  name: 'fonts/[name].[hash:6].[ext]'
                }
              }
            }
          }
        ]
      },
      {
        test: /\.(png|jpg|gif|jpeg|webp|svg)$/,
        use: [
          {
            loader: 'url-loader',
            options: {
              limit: 10240, // 10K
              esModule: false,
              fallback: {
                loader: 'file-loader',
                options: {
                  // publicPath: '/public/path/to/',
                  name: 'img/[name]_[hash:6].[ext]'
                }
              }
            }
          }
        ],
        // exclude: /node_modules/
      },
      {
        test: /\.(mp4|webm|ogg|mp3|wav|flac|aac)$/,
        loader: 'file-loader',
        options: {
          esModule: false,
          name: 'media/[name].[hash:6].[ext]'
        }
      },
      {
        test: /\.vue$/,
        loader: 'vue-loader'
      }
    ]
  },
  devtool: 'cheap-module-eval-source-map', // 开发模式下使用
  devServer: {
    host: '0.0.0.0',
    hot: true,
    port: '3000', // 默认是8080
    quiet: false, // 默认不启用
    inline: true, // 默认开启 inline 模式，如果设置为false,开启 iframe 模式
    stats: 'errors-only', // 终端仅打印 error
    overlay: false, // 默认不启用
    clientLogLevel: 'silent', // 日志等级
    compress: true // 是否启用 gzip 压缩
  },
  resolve: {
    alias: {
      vue$: 'vue/dist/vue.esm.js',
      '@': path.resolve(__dirname, '../src'),
      packages: path.resolve(__dirname, '../packages')
    },
    extensions: [
      '.js',
      '.jsx',
      '.vue',
      '.ts',
      '.json'
    ]
  }, // 解析
  externals: {},
  optimization: {
    minimize: true
  },
  performance: {
    hints: false
  },
  stats: {
    children: false
  },
  plugins: [
    new MiniCssExtractPlugin({
      // Options similar to the same options in webpackOptions.output
      // both options are optional
      filename: 'styles/[name].css',
      chunkFilename: 'styles/[id].css'
    }),
    new HtmlWebpackPlugin({
      template: './example/index.html',
      filename: 'index.html', // 打包后的文件名
      // dllName: manifest.name,
      minify: {
        removeAttributeQuotes: false, // 是否删除属性的双引号
        collapseWhitespace: false // 是否折叠空白
      }
      // hash: true //是否加上hash，默认是 false
    }),
    new VueLoaderPlugin()
  ]
}

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
