### ISSUE TITLE
[Feature Request] provide (dynamic) query params when loading bundles

### ISSUE THREAD

**Issue by KBOE2** [webpack/webpack#10938]
## Feature request

**What is the expected behavior?**
Loading bundles created by code splitting (`import('myModule')`) should be possible with dynamic query parameters.
Example: In my file `dashboard.vue`, I'm loading the component `./components/vehicle-types.vue` via component `VehicleTypes: () => import(/* webpackChunkName: "dashboard/vehicle-types" */ './components/vehicle-types.vue')`. I can set a public path that is prepended to the bundle path in generated `jsonpScriptSrc` function:
```js
function jsonpScriptSrc(chunkId) {
    return __webpack_require__.p + "" + ({"dashboard/vehicle-types":"dashboard/vehicle-types"}[chunkId]||chunkId) + ".bundle.js"
}
```

I suggest the possibility to provide dynamic query parameters for the loading. Which would – in my current case – produce a `jsonpScriptSrc` function like that:
```js
function jsonpScriptSrc(chunkId) {
    return __webpack_require__.p + "" + ({"dashboard/vehicle-types":"dashboard/vehicle-types"}[chunkId]||chunkId) + ".bundle.js?uid=" + window.user_id
}
```

**What is motivation or use case for adding/changing the behavior?**
I am creating an Add-On for a browser game based on vue. To provide dynamic loading of functionalities, I want to implement code splitting. But I need to pass the User-ID as the server checks wether it needs to send the file in Beta-Version or the Public Version. (I know, that anyone could change the provided user-ID to receive beta files but that is no Problem as beta-Version is OpenSource and accessible anyways for advanced ones).
Providing a dynamic Query could solve this issue for me.

**How should this be implemented in your opinion?**
Webpack configuration could be extended by an Object `output.publicQuery` which provides the query parameters.
Just as an Idea:
```js
module.exports = {
    output: {
        publicQuery: {
            staticKey: {
                value: 'This is a static key'
            },
            dynamicKey: {
                value: 'window.user_id', // must be valid JS Code stringified
                isDynamicKey: true, // false by default
            }
        }
    }
};
```
Which would produce in the build the following function (or similar):
```js
function jsonpScriptSrc(chunkId) {
    return __webpack_require__.p + "" + ({"dashboard/vehicle-types":"dashboard/vehicle-types"}[chunkId]||chunkId) + ".bundle.js?staticKey=This%20is%20a%20static%20key&dynamicKey=" + window.user_id
}
```

**Are you willing to work on this yourself?**
I can try to do so but I may need some guidance as I am not familiar with the file structure yet.

**Comment by sokra** [comment]
That's not something that fits into the core. You can write a custom plugin for that.

**Comment by KBOE2** [comment]
Thank you for your answer!
I didn't think of a plugin yet but that's a good idea! :+1:
