### ISSUE TITLE
multi-second intermittent pauses when loading components

### ISSUE THREAD

**Issue by mx2323** [webpack/webpack#10942]
# Bug report

**What is the current behavior?**
my app uses webpack and uses a component called react-ace. im running my app in debug mode, but i get multi-second random pauses when i am clicking around. when i profile and try to understand whats going on, it appears to be spending time in webpack sourcemap code. 

i have NO idea what _parseMappings_ or _quickSort_ or _originalPositionFor_, but it appears related to sourcemaps maybe? 
![image](https://user-images.githubusercontent.com/528124/82601182-64e93600-9b6c-11ea-946d-b34baa4f82cb.png)

**What is the expected behavior?**
not have sudden intermittent multi-second stuttering - or at least provide a warning about why this is happening

**Other relevant information:**
webpack version:  4.29.6
Node.js version: v12.4
Operating System: ubuntu 18.04
Additional tools:

**Comment by sokra** [comment]
The methods you mentioned are from the `source-map` package. We also use it, but not at runtime. This doesn't origin from webpack.
