### ISSUE TITLE
Inconsistent chunk paths when using dynamic imports

### ISSUE THREAD

**Issue by tobiu** [webpack/webpack#10949]
# Bug report
I just finished the new neo.mjs build scripts and run into webpack issues.

Inside the neo main thread i am doing this:
```
if (window.webpackJsonp) {
    __webpack_require__.p = Neo.config.basePath.substring(6);
}

Neo.config.mainThreadAddons.forEach(addon => {
    imports.push(import(/* webpackChunkName: 'src/main/addon/[request]' */ `./main/addon/${addon}.mjs`));
});

// intended for the online examples where we need an easy way to add GA to every generated app
if (!Neo.config.mainThreadAddons.GoogleAnalytics && Neo.config.useGoogleAnalytics) {
    // for this use case webpack creates a chunk called "[request]" if not named manually.
    imports.push(import(/* webpackChunkName: 'src/main/addon/GoogleAnalytics-mjs.js' */ './main/addon/GoogleAnalytics.mjs'));
}
```

side issues:
1. you can not change `__webpack_public_path__` inside the output without the hack to override `__webpack_require__.p` (this var should get exposed)
2. in case i remove the last if statement, GA will get included fine. in case i change the webpackChunkName to 'src/main/addon/[request]' there, it will literally name the GA chunk "[request]".

the side issues are not high prio items, since the hacks work.

When building the main thread for the development environment:

https://github.com/neomjs/neo/blob/dev/buildScripts/webpack/development/webpack.config.main.js

The output result is this one (perfectly fine):

<img width="305" alt="Screenshot 2020-05-23 at 21 40 41" src="https://user-images.githubusercontent.com/1177434/82739210-1390a080-9d3e-11ea-8498-cad0ca59ad2f.png">

I tried to deploy this version to the online examples (gh pages). The only difference is that neo.mjs itself is a node_module here. I am calling the same script inside the neo.mjs module.

The output result is this one:

<img width="361" alt="Screenshot 2020-05-23 at 21 43 03" src="https://user-images.githubusercontent.com/1177434/82739251-771ace00-9d3e-11ea-81dc-6f42cfbc1298.png">

Now I am confused!

Why are 6 addons saved at the correct spot, while 2 others get a vendors prefix for the source folder resulting in a wrong spot?

The result inside the node_module env does not work inside the browser. Let me know in case you need more input.

Any pointers would be appreciated!

Thx & best regards,
Tobias

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  v4.43.0
Node.js version: v12.12.0
Operating System: Mac OS
Additional tools:

**Comment by tobiu** [comment]
seems to be related to SplitChunksPlugin => cacheGroups => defaultVendors

**Comment by tobiu** [comment]
since i am going to change it, let us keep a reference of the old webpack.config.main.js here.
```
const path        = require('path'),
      buildTarget = require('./buildTarget.json'),
      processRoot = process.cwd(),
      packageJson = require(path.resolve(processRoot, 'package.json')),
      neoPath     = packageJson.name === 'neo.mjs' ? './' : './node_modules/neo.mjs/',
      config      = require(path.resolve(neoPath, 'buildScripts/webpack/json/build.json')),
      entry       = {main: path.resolve(neoPath, config.mainInput)};

module.exports = {
    mode   : 'development',
    devtool: 'inline-source-map',
    entry,
    target : 'web',

    output: {
        filename: (chunkData) => {
            if (chunkData.chunk.name === 'main') {
                return config.mainOutput;
            }
        },

        path: path.resolve(processRoot, buildTarget.folder)
    }
};
```

**Comment by tobiu** [comment]
as a first test, i added:
```
optimization: {
    splitChunks: {
        cacheGroups: {
            default: false
        }
    }
}
```

this change has no effect when using neo.mjs as a node_module.

2nd try (replacing node_modules with ignore_node_modules):
```
optimization: {
    splitChunks: {
        cacheGroups: {
            vendors: {
                test: /[\\/]ignore_node_modules[\\/]/,
            }
        }
    }
}
```

This change worked and no vendor prefix got added to the src folder for addons (all 8 ended up at the right spot). Testing the build result next.

**Comment by tobiu** [comment]
ok, it looks like the number "6" is related to
```
optimization: {
    splitChunks: {
        maxAsyncRequests: 6 // default value
    }
}
```

changed the number to 25, but this had no effect.

i did look into:

https://github.com/webpack/webpack/blob/master/lib/optimize/SplitChunksPlugin.js

and did not see the 6 there.

**Comment by sokra** [comment]
The difference is related to the size of the chunks. By default vendors select chunks > 30kb.

**Comment by tobiu** [comment]
this one is no longer an issue for the neo.mjs use case. closing it.
