### ISSUE TITLE
Webpack does not load config file

### ISSUE THREAD

**Issue by yanxyz** [webpack/webpack#1094]
Well, I start with webpack and meet a problem, webpack does not load config file:

```js
module.exports = {
  entry: './main.js',
  output: {
    fileName: './bundle.js' // fileName should be filename
  }
}; 
```
I don't notice the spelling mistake( forgive me), so I look into the code to find out the reason. Then I find out that I have made a foolish mistake. However the code does not give the tip, it just prints out help instead. I think it could be improved:

bin/convert-argv.js line  463:

```js
} else if (options) {
	console.log("Config did not have output.filename or output.");
	process.exit(-1);
} else {
	optimist.showHelp();
	process.exit(-1);
}
```

**Comment by troutowicz** [comment]
fileName -> filename :)

**Comment by yanxyz** [comment]
Yes, but I can't find this spelling mistake until I debug in "convert-argv.js" .

**Comment by troutowicz** [comment]
Your shared snippet in your first comment has the spelling mistake.

**Comment by yanxyz** [comment]
@troutowicz  Apologize for my bad English. I followed the document, however, spelling mistake sometimes is hard to find out. Actually I looked at my config several times and always thought it had no problem, at end I was forced to dig out the reason. If CLI gave some useful tips then I could quickly find out this foolish mistake, but It only gave help in this case as if it could not load the config file. This is why I think the improvement above is helpful.

**Comment by troutowicz** [comment]
Yeah, I can see why that might be useful now. I think the below changes would make sense.

Change line 463
```js
} else {
  optimist.showHelp();
  process.exit(-1);
}
```
to
```js
} else {
  console.log('Config object is missing output properties.');
  process.exit(-1);
}
```

**Comment by yanxyz** [comment]
if there is no webpack.config.js, then `webpack` will not print help but print this error. so should check options first. The document says that `webpack` will print help if there is no options.

**Comment by troutowicz** [comment]
Ah, right... your change makes more sense now. But in the error message, we only need to mention the undefined property that is required. If the output object is undefined, that would be fixed when resolving the error message.

```js
} else if (options) {
    console.log("Config is missing output.filename property.");
    process.exit(-1);
} else {
    optimist.showHelp();
    process.exit(-1);
}
```

**Comment by yanxyz** [comment]
Oh, I'm not clear about the error message, that's why I open this issue but not make a pr directly:-) . If there is no other problem then this issue could be closed.

**Comment by troutowicz** [comment]
I'd say submit a PR and let @sokra decide if he wants the change. If you aren't able, I can make one.

**Comment by yanxyz** [comment]
Thanks, I made a pr.

**Comment by shadowii** [comment]
I second more verbose error messages (or rather, any error message at all would be nice). I pulled down someone's NPM project with an existing webpack.config.js file. Running the webpack in CLI just printed the help with no indication that there was an error or that it had even read the config file.  

In my case, the original author had specified output.library but not output.filename, and apparently it won't work without the latter.

**Comment by bebraw** [comment]
@yanxyz Safe to close?

**Comment by sokra** [comment]
There is a warning now.

**Comment by yanxyz** [comment]
:+1: though the warning is not very obvious.

**Comment by ManikandanMagi** [comment]
Error: webpack.optimize.CommonsChunkPlugin has been removed, please use config.optimization.splitChunks instead.what i do i faced this error for run webpack4 please any one helps to resolve this error

**Comment by bebraw** [comment]
@ManikandanMagi Please see https://webpack.js.org/plugins/split-chunks-plugin/#optimizationsplitchunks.
