### ISSUE TITLE
Feature request: "type": "module" in package.json

### ISSUE THREAD

**Issue by robpalme** [webpack/webpack#10958]
## Feature request

**What is the expected behavior?**

`.js` files inside a package with `"type": "module"` in `package.json` should be treated as ES modules.  

See [the Node docs](https://nodejs.org/docs/latest-v12.x/api/esm.html#esm_package_json_type_field) for more information.

**What is motivation or use case for adding/changing the behavior?**

As of yesterday, [Node LTS](https://nodejs.org/en/blog/release/v12.17.0/) now offers this feature unflagged so it would be good for webpack to support it too.

Additionally this would help alleviate bundle bloat in cases similar to #10889

Officially ES Modules support in Node is still classified as experimental, but there is a strong expectation the key mechanisms will remain stable.  Mostly it's things like error message wording that may change.

**How should this be implemented in your opinion?**

However Tobias sees fit.  If it could land in webpack 4 that would be amazingly useful, but I would understand if it were webpack 5 only.

**Are you willing to work on this yourself?**

Guy tells me Tobias has already begun implementation.  But I could not find any related issue or thread.  Therefore I'm mostly raising this as a tracking issue so that everyone can see the status.

**Comment by guybedford** [comment]
I've posted https://github.com/webpack/webpack/issues/10971 which is also related to Node.js interop here.

**Comment by evilebottnawi** [comment]
Node for webpack@5, babel has bugs https://github.com/webpack/webpack/issues/11467
