### ISSUE TITLE
Feature request: Lazy load only required exports from module

### ISSUE THREAD

**Issue by pushkardk** [webpack/webpack#10959]
## Feature request

- Allow lazy loading of only a part of a module (say, a named export). 
- When a part of a module is lazy loaded, it must not contain the default and other named exports. 

**What is the expected behavior?**

- The ability to request only a particular export (or a set of it) from a module while lazy loading it.
- When a single export or a collection of such exports are lazy loaded, webpack should deliver only the what is required with the rest of the module's code tree shaken

**What is motivation or use case for adding/changing the behavior?**

- Dynamic import as of now only allows importing of the whole module that includes all the exports
- With this new feature, when code splitting for the requested chunks happens at build time, we will have a chunk with a reduced size which will save us bandwidth while requesting the resource from a server

**How should this be implemented in your opinion?**

- Expand the `import(specifier)` argument list to include a second parameter to mention required named exports
- A single named export: 
```javascript
import(specifier, { named }).then(module => { /* Only module.named is available */ })
```
  - Multiple named exports:
```javascript
import(specifier, { named1, named2 }).then(module => { /* Only module.named1 and module.named2 are available */ })
```
- Creating chunks during build time containing only the specific exports of the module (with the rest tree shaken) can decrease the chunk size and reduce latency when it is requested inside the application

**Are you willing to work on this yourself?**
Unsure

**Comment by sokra** [comment]
> * Expand the `import(specifier)` argument list to include a second parameter to mention required named exports

`import()` is spec'ed, we can't add arguments.

But something like 
```js
import(/* webpackExports: ["named1", "named2"] */ "module")
```
would be possible.

As workaround you can create a wrapper file which reexports only a part of the module.

``` js
// partial-module.js
export { named1, named2 } from "module";
```

``` js
import("./partial-module")
```

**Comment by pushkardk** [comment]
Thank you for addressing my feature request @sokra 

Yes, I do agree that populating information as a magic comment is a better and more elegant approach without fiddling with the spec. As for the workaround, the onus is on the developer's code without webpack actively helping out.

I would like to help if this is something that will be useful to implement (However, I will need time and help as I haven't contributed before)

**Comment by evilebottnawi** [comment]
It is good feature, after it we can deprecate https://github.com/webpack-contrib/exports-loader in favor built-in solution

**Comment by pushkar100** [comment]
I want to work on this. I think the starting point is `ImportParserPlugin`. I request some time to present a code solution if I can do so, @sokra

**Comment by sokra** [comment]
Sure go ahead

**Comment by pushkar100** [comment]
I have opened a draft PR (https://github.com/webpack/webpack/pull/10964/files?diff=unified&w=1)

- Added `getReferencedExports` method to `ImportDependency` class to be able to return the named exports
- Added the initial test cases

Do I need to do a similar change for `ImportEagerDependency` and `ImportWeakDependency`? How do we proceed?

@sokra @evilebottnawi

**Comment by sokra** [comment]
Yep, they need similar changes. Check if they inherit from each other

**Comment by pushkar100** [comment]
Added similar support for:
- `ImportEagerDependency`
- `ImportWeakDependency`
(These did not inherit from each other but they all inherited from the common 'ModuleDepenency` class)

Considering the following next:
- For params that are not strings (Dynamic expressions) are built using `ContextDependencyHelper` and `ImportContextDependency`. Working on introducing named exports here too.
- "default" should handle resolving module with only the default export

My tests pass in`test:build` but fail in `test:integration` (`test/TestCasesCachePack.test.js`). I need some help in understanding why and eventually resolving this.
