### ISSUE TITLE
Potential Webpack 5 regression with `mode: development` and shared imports

### ISSUE THREAD

**Issue by ahwitz** [webpack/webpack#10966]
# Bug report

**What is the current behavior?**

When using `mode: development` with the current Webpack 5 version (`^5.0.0-beta.16` in package.json from `npm install webpack@next`), changes to a single file imported into two separate entrypoints do not get recognized.

**If the current behavior is a bug, please provide the steps to reproduce.**

I've reduced this to what I think is the absolute base case (without digging into specifics about `mode: development` vs `mode: production`) at https://github.com/ahwitz/webpack-issue-example . There may be some issues if you're running on Windows due to filepaths, but the following steps work out of the box for me with a fresh clone on Mac OS 10.14.

To reproduce:
- Clone above repo, run `npm install`
- Run `gulp`
=> Console will print out "success: [hash]"
- Open `src/entry-b.js` in a text editor and make a change
=> `compile` task will run and console will print out "success: [hash2]"
- Make another change to `src/entry-b.js`
=> `compile` task will run and console will print out "success: [hash2]"

**What is the expected behavior?**

The third printout above should be a third, different hash, as `src/entry-b.js` (and thus the compiled files) have changed again. Both `dist/` files should also change to include the updates.

If `mode: production` is set, this correctly prints out a third, different hash and the files update. If you run this same code using Webpack 4.x, this correctly prints out a third, different hash and the files update.

Because of those two, I'm _fairly certain_ this is a regression and have skipped reporting on StackOverflow first. I also haven't tested this with using one of the Webpack native CLI tools because I was trying to reduce the base case from my organization's production use. My apologies if this isn't a regression or if this isn't reproducible with `webpack-dev-server`. 

**Other relevant information:**
webpack version: 5.x
Node.js version: 10.x
Operating System: Mac OS 10.14.x
Additional tools: Gulp 4.x

-------

Edit a few hours later: I realized I accidentally misnamed the files, and if I switch the filenames to make it more realistic, things work again. More confused now and will leave things the way they are; if more debugging information is needed let me know.

**Comment by ahwitz** [comment]
Ran `git bisect` and traced it to https://github.com/webpack/webpack/commit/352ecd0c3add237448ae307679afe23c4f364e48. Changing https://github.com/webpack/webpack/blob/master/lib/FileSystemInfo.js#L894 to `commonMap.size < 1` fixes the issue and made sense from an outsider's perspective, unless a "snapshot" is specifically intended to be n > 2 files.

I have a PR ready for that fix (from https://github.com/ahwitz/webpack/commit/74fdde8888078ea01dd48aa4073a1ae84e2dda4f), but because a) I'm not so sure about that "unless" and b) I couldn't find any tests that broke because of this/correspond to this, I'm hesitant to submit it. Let me know if you want me to put that in and I can.

**Comment by sokra** [comment]
Thanks great find. I need to look into that  in detail, not sure if this is the correct fix, but that you figured out that the snapshot deduplicate logic is the problem is a good find and makes it easier to fix that.

**Comment by sokra** [comment]
Could you try the changes on my PR on your codebase:

You can add this to your package.json to install that version

``` json
"dependencies": {
  "webpack": "webpack/webpack#bugfix/snapshot-dedupe"
}
```

**Comment by ahwitz** [comment]
Can confirm it does on the production code we found the issue in. `_from` in `node_modules/webpack/package.json` lines up with the bugfix tag, and none of my temporary changes were still in place. Thanks a ton!

**Comment by sokra** [comment]
🎉
