### ISSUE TITLE
How webpack dev sever implement the live reload?

### ISSUE THREAD

**Issue by Victor716** [webpack/webpack#10963]
Recently, I've been reading the source codes of webpack dev-server. I was wondering how webpack dev sever implement the live reload? I tried setting the path in contentBase, it seemed like it wouldn't watch the static files under that path.

I also tried the dev-server config without watchContentBase, which would not trigger         **this.setupWatchStaticFeature();** at line 513 in **node_modules\webpack-dev-server\lib\Server.js**. And the live reload still works?

Could u pls tell the code where it implements the live reload?

Thx a lot

Victor

**Comment by evilebottnawi** [comment]
Using websockets/sockjs:
- Server: https://github.com/webpack/webpack-dev-server/blob/master/lib/servers/SockJSServer.js
- Client: https://github.com/webpack/webpack-dev-server/blob/master/client-src/default/index.js#L37

Please use stackoverflow/gitter for questions. Thanks.
