### ISSUE TITLE
Components with multiple themes

### ISSUE THREAD

**Issue by jonasbjorkberg** [webpack/webpack#1096]
I am building a web app (React) in which I need to support multiple themes. The file structure is as follows. Each component has it's own directory containing all files that belong to the component.
Example:

ui-Avatar
  |-- index.jsx
  |-- theme-a.css
  |-- theme-b.css
  |-- ....

When using webpack-dev-server I can quite easily use a conditional require and pull in either theme-a or theme-b.

onComponentWillMount() {
   if (this.context.theme === 'theme-a') {
      require('./theme-a.css');
   else (this.context.theme === 'theme-b') {
      require('./theme-b.css');
   }
}

BUT when I use web pack to package for the production server both theme-a.css and theme-b.css get pulled in and packaged into the same resulting css file. With the result that the style rules in the themes overwrite each other.

What I would like is to be able to produce separate files for the two themes with the collected theme snippets from all the components in the application.

Does anyone know how to set up webpack to solve my problem?

**Comment by sokra** [comment]
You can use Local scoped CSS or "CSS Modules" (experimental) for that.

Just give your component a `theme` property and use the styles from this.

Example using CSS Modules:

``` jsx
import baseStyle from "./baseStyle.css"
class Component {
  render() {
    var { theme } = this.props;
    return <div className={theme.main + " " + baseStyle.main}>
      <div className={theme.inner + " " + baseStyle.main}></div>
    </div>;
  }
  // ...
}
```

``` css
/* themeA.css */
.main {
  background: black;
}
.inner {
  color: white;
}
```

``` css
/* themeB.css */
.main {
  background: white;
}
.inner {
  color: blue;
}
```

Useage:

``` js
import themeA from "component/themeA.css";
import themeB from "component/themeB.css";
import customTheme from "./customThemeForComponent.css";
import Component from "component";

<Component theme={themeA} />
<Component theme={themeB} />
<Component theme={customTheme} />
```

CSS Module mode: https://github.com/webpack/css-loader#module-mode

**Comment by jonasbjorkberg** [comment]
Thank you Tobias
What a brilliant solution! CSS Modules are an amazing concept.

**Comment by lanocturne** [comment]
@jonasbjorkberg Thanks man, that example is GREAT! Any suggestion I can apply it on site theme change?

**Comment by jure** [comment]
Aren't all three CSS files included in the final CSS in this case? Is there a way to include only the selected CSS? My use case would be build-time theme configuration, and then conditional requires, which I think might be the more common use case?

**Comment by andywer** [comment]
Hey @jure. Just saw your comment.

Have a look at my new plugin https://github.com/andywer/postcss-theme Maybe that's what you need :)

**Comment by akre54** [comment]
I'm dealing with this currently. I'd love for style-loader to be able to return some kind of string template / dynamicaly aware format, because while @sokra's way is the one we're heading towards, I'd really hate to duplicate that many files / declarations.

What I'm proposing would look something like

```js
import styleFn from 'styles/component.css'

class MyComponent extends React.Component {
  render() {
    const { theme } = this.props
    const styles = styleFn(theme)

    return (
      <div className={styles.component}>
      </div>
    )
  }
}
```

Is there a way to enable this? Theme could either be an object (with colors and size variables, e.g.) or a string, and let some css processor handle the conditionals. Any thoughts?

**Comment by bojandragojevic** [comment]
what if you want to build 2 versions of app, So one version with theme A will be deployed to one domain  and theme b to another domain. So I do not want to have both css on domain A if do not need it, just theme A.

Someone tried that?

**Comment by andywer** [comment]
@bojandragojevic 
I might have a solution if you are using CSS modules: Use `postcss-theme` and set the theme path based on an environment variable in the webpack config (`{ themePath: process.env.THEME || defaultThemePath }`).

You can then create a webpack build for each theme.

**Comment by mnzaki** [comment]
If you do not want to use CSS Modules, you can use the [DefinePlugin](https://github.com/webpack/docs/wiki/list-of-plugins#defineplugin) to define a `THEME_PATH` constant, then simply `require(THEME_PATH)`. These constants are replaced as-is in the code.

I use themes extensively in my project, and I require more flexibility with generated code, so I have resorted to using a custom loader based on [ejs-render-loader](https://www.npmjs.com/package/ejs-render-loader) and I inject a config object into the EJS render context, then I setup the loader such that I can include `*.ejs.js` files and they would be run through the EJS compiler first before being `require()`ed

**Comment by pleunv** [comment]
I've been thinking about this a bit recently. My use case is a large enterprise product that has dozens of customer instances. Each of these have at least some basic theming requirements (simple prop mapping would do), however, some of these go a lot further and require implementation of house styles and so on. Most css (in js) solutions these days can deal with the basic requirements, but if you want to take this one step further you usually get stuck. 

Ideally what I would like to achieve is to split off different themes into separate css files at build time that can be loaded and activated on the fly at runtime. I would also combine this with modular and reusable base components and themes, housed in separate repos, so some decoupling (and explicit mapping of classes/styles) will be necessary.

So far I've also been unable to achieve this result with webpack and css-modules. However, this sounds kind of similar to what `require.ensure` does today. What if a mechanism like `require.ensure` could be used to asynchronously load css files into the DOM?

Image an approach like this:

```js
function onThemeLoaded(id, theme) {
  themeCollection.registerTheme(id, theme);
  themeCollection.activateTheme(id);
}

function loadTheme(id) {
  switch (id.toLowerCase()) {
    case 'mdl':
      require.ensure([], (require) => onThemeLoaded('mdl', {
        Card: require('@org/mdl-theme/Card.css'),
        List: require('@org/mdl-theme/List.css'),
        Nav: require('@org/mdl-theme/Nav.css')
      }), 'mdl-theme');
      break;
    case 'ios':
      require.ensure([], (require) => onThemeLoaded('ios', {
        Card: require('@org/ios-theme/Card.css'),
        List: require('@org/ios-theme/List.css'),
        Nav: require('@org/ios-theme/Nav.css')
      }), 'ios-theme');
      break;
    default:
      break;
  }
}

loadTheme('mdl');
```

The above snippet currently creates 2 separate theme chunks `mdl-theme.js' and 'ios-theme.js' containing the class maps. The require callback gets passed a dictionary of class maps that can in turn be passed to a global theme service. Combine with some theme context magic to pass the classnames to the corresponding themeable components that can combine them with the default styles and this would be a fairly transparent and easy approach.

However, 2 parts are missing:

- In addition to the `mdl-theme.js` and `ios-theme.js` chunks we also need the css extracted into separate chunks (`mdl-theme.css` and `ios-theme.css`). Right now ExtractTextPlugin does not appear to do this.
- The css chunks need to be fetched and loaded into the DOM.

How feasible would an approach like this be?

**Comment by calvinwyoung** [comment]
I realize that this thread is fairly old, but it has the most information about this problem so I'm hoping someone here might be able to help.

I'm working with a whitelabeled website that has multiple customer domains pointing to the same set of servers. The backend returns a different CSS bundle based on the domain with custom branding. I'd like to be able to do the following:

- Define a different set of `brand_1_theme.css`, `brand_2_theme.css`, files with custom colors, etc.
- Require a theme file in my CSS code. Seems like postcss-theme might be the best option here, but I'm open to anything.
- Have `ExtractTextPlugin` output a different set of CSS files for each theme, and have `ManifestPlugin` output a manifest file with mappings for *all* themes.

Has anyone done anything similar to this? What has been there approach?

**Comment by deemstone** [comment]
Also，we are trying to define a grammer like this, to generate multi "theme-xxx.css" by machine.

```scss
//define variables contains values for all theme
$fontColor: {
    dark: white;
    light: #CCC;
}
p {
    //reference theme variable
    color: @theme($fontColor);
    //inline theme variable
    opacity: @theme( 0.5,  1 );
}
```

That's just an idea , the grammar has not yet been finalized. We are trying.

**Comment by luotaoyeah** [comment]
[import()](https://github.com/tc39/proposal-dynamic-import) works:
```javascript
if (this.context.theme === 'theme-a') {
    import('./theme-a.css').then(() => {
        /* ... */
    });
else (this.context.theme === 'theme-b') {
    import('./theme-b.css').then(() => {
    /* ... */
    });
}
```

OR

```javascript
import(`./${this.context.theme}.css`).then(() => {
/* ... */
});
```

**Comment by terence55** [comment]
I'm dealing with the same problem currently, I try to figure it out without any invasive of codes. Then I write a webpack plugin [themes-switch](https://github.com/terence55/themes-switch) to do that. Maybe it can help you.
Now I just use variables to define different colors and dimensions, then webpack would generate themes for me, and the style formats can be less, postcss and sass. Then I can make a realtime-switch in my app.

theme-a.less
```
@color-main: #0A6EFA;
@color-text: #000;
```

theme-b.less
```
@color-main: #222A42;
@color-text: #FFF;
```

default.less
```
@import 'theme-a.less';
```

main.less
```
@import 'default.less';
.main {
  background: @color-main;
}
```

In use
```js
changeTheme('theme-b', 'theme-b-123456.css')
```

**Comment by veeral-patel** [comment]
@sokra Hi Tobias, thank you very much for your solution! I noticed someone mentioned all 3 CSS files will be loaded. I don't have a problem with the performance impact of that, but I do want to make sure the CSS files don't collide with each other.

If I understand correctly, they won't, because we're using CSS Modules, correct?

Thank you again!
