### ISSUE TITLE
Corrupt source map paths for context module that uses negative lookahead

### ISSUE THREAD

**Issue by rjgotten** [webpack/webpack#10969]
# Bug report

**What is the current behavior?**

Given a context module that uses a negative lookahead, e.g.

```js
// registers all files other than `./index.js`
const context = require.context( ".", true, /^(?!.*[\\/]index\.js$).*$/i, "lazy" );
```

Webpack generates a corrupted source map filenames for this context module.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Create a context module as per the above example, on some deeply rooted path within your project structure, e.g. `/foo/bar/index.js`
2. Compile with source maps enabled.
3. Look at output in browser dev tools or open up the generated sourcemap.
3. Note the sourcemap has the context module at `webpack:///.*[\\/]index\.js$).*$`, instead of where it should go: `webpack:///foo/bar/index.js lazy ^(?!.*[\\/]index\.js$).*$`

**What is the expected behavior?**

For Webpack to generate the correct source map path:
`webpack:///foo/bar/index.js lazy ^(?!.*[\\/]index\.js$).*$`

**Other relevant information:**
webpack version:  4.43
Node.js version: 12.16.3
Operating System: Win 10 Pro 1909
Additional tools: -

**Comment by rjgotten** [comment]
Some analysis I've already done regarding this problem:

The root problem is Webpack assumes that any `!` in a module identifier signals a split between loaders and resource path, which breaks for context modules as they have regexes in their generated `identifier` and `readableIdentifier` where `!` is an extremely valid control character.

For reference, the relevant parts of the code base:

https://github.com/webpack/webpack/blob/c9d4ff7b054fc581c96ce0e53432d44f9dd8ca72/lib/ModuleFilenameHelpers.js#L71-L97

https://github.com/webpack/webpack/blob/c9d4ff7b054fc581c96ce0e53432d44f9dd8ca72/lib/ContextModule.js#L84-L185

A potential solution to the problem would be to update all identifier generators to apply percent/URI encoding of the `!` character to the regular expressions inserted into the module identifier - i.e. `regExp`, `include` and `exclude`.


**NOTE**:
Potentially this can break in a _lot_ more places than just source maps, as the regular expressions are part of the core `module.id` as well and there might be more places where Webpack attempts a naive `.split("!")` to separate resource path from loaders.

Source maps are just the first spot where I noticed it.

**Comment by sokra** [comment]
Yep, fixing `prettyRegExp` would also be my idea. Send a PR

**Comment by sokra** [comment]
Send a PR

**Comment by Adityaperiwal** [comment]
Hii @sokra, is there a way to get the `sourcemap` or `identifier` out of `require.context()`?
