### ISSUE TITLE
Wrapping imported function in Object causes naming conflicts

### ISSUE THREAD

**Issue by dennis-c** [webpack/webpack#10968]
# Bug report

**What is the current behavior?**
When compiling the code below webpack creates an endless loop
```
import { logger } from "./export";

const obj = {
	Object: function() {
		logger();
	}
};

obj.Object();
```
Compiles into
```
var obj = {
	Object: function Object() {
		Object(_export__WEBPACK_IMPORTED_MODULE_0__["logger"])();
	}
};

obj.Object();
```

There should probably be a reference to the global `Object`, maybe this could be achieved with `globalThis`? (Babel is prefixes the function with a name according to the ES6 spec, which I believe to be correct, however the Object wrapping cannot handle being in a function named Object (See example two in source code).

**If the current behavior is a bug, please provide the steps to reproduce.**
You can check out the full source code here: https://github.com/dennis-c/webpack-import-wrap-bug
You can see the error in your console here: https://dennis-c.github.io/webpack-import-wrap-bug/public/

**What is the expected behavior?**
Each example alerts the "Logger called" text once.

**Other relevant information:**
webpack version:  4.43.0
Node.js version: 13.10.1
Operating System: OSX (But also fails under windows)
Additional tools: -

**Comment by sokra** [comment]
Unfortunate...

**Comment by sokra** [comment]
We are trying to get rid of this `Object` anyway. webpack 5 only uses it in rare cases. Hopefully we get rid of that totally.

**Comment by maximgavrilov** [comment]
Is it any way to force `Object` back? We have a crash reports from iOS 10.3 with troubles connected with `(0,module).func()` execution.

```
TypeError

(0,_pixi_utils__WEBPACK_IMPORTED_MODULE_1__.isPow2) is not a function. 
(In '(0,_pixi_utils__WEBPACK_IMPORTED_MODULE_1__.isPow2)(this.realHeight)',
'(0,_pixi_utils__WEBPACK_IMPORTED_MODULE_1__.isPow2)' is -2.4171740473974053e+176)
```
