### ISSUE TITLE
Tree-shaking delete  un-side-effect code

### ISSUE THREAD

**Issue by underfin** [webpack/webpack#10978]
# Bug report
Webpack will delete all code when use npm module (package.json has `"sideEffects": false`) .But it's ok when use relative path import.
``` js
 // a.js (a module)
function a(){}
```
``` js
// b.js (b module)
import {a} from 'a'
function b () {}
a(b) // shouldn't delete
export { b as bb}
```
```js
// index.js  (it's entry)
import {bb} from 'b'
```

**What is the current behavior?**
delete code.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. run webpack wtach output.

**What is the expected behavior?**
Shouldn't delete code.

**Other relevant information:**
webpack version:  5.0.0-beta.16 and 4.433 (the issues all happend with two version)
Node.js version: 12.14.0
Operating System: mac
Additional tools:xx

**Comment by sokra** [comment]
That's not unexpected. When using `"sideEffects": false` it's assumed your module evaluation has no (visible) side-effects and initialization code doesn't need to be evaluated, when exports are not used.

Since in your case non of the exports of `b.js` are used, it's not evaluated.
