### ISSUE TITLE
Component not loading under sources in Chrome webpack 4 angular 8

### ISSUE THREAD

**Issue by Shubham819** [webpack/webpack#10975]
Hi i am using webpack 4.3.0
And webpack dev server 3.11.0
I am not able to get any components in the sources folder when I check in developer tools in Chrome. 
Also property of call undefined in my pollyfills.ts, global, ts and main.ts filea

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
