### ISSUE TITLE
Building fails when `output.path` on Windows is with forward slashes e. g. `C:/my/dir`

### ISSUE THREAD

**Issue by nolimitdev** [webpack/webpack#10980]
# Bug report
When `output.path` on Windows is set with forward slashes e. g. `C:/my/dir` bulding fails. Changing forward slashes to backward seems to be workaround now.
```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.output.path: The provided value "C:/my/dir" is not an absolute path!
   -> The output directory as **absolute path** (required).
```

**What is the current behavior?**
Build failed because of error mentioned above.

**If the current behavior is a bug, please provide the steps to reproduce.**
Set `output.path` on Windows with forward slashes e. g. `C:/my/dir`

**What is the expected behavior?**
Build must process successfully because ofcourse `C:/my/dir` is valid absolute path on Windows. So error message is laying/misleading.

**Other relevant information:**
webpack version:  4.43.0
Node.js version: 12.16.3
Operating System: Windows

**Solution:**
Regex
`/^(?:[A-Za-z]:\\|\\\\|\/)/`
in `webpack/schemas/ajv.absolutePath.js` shoud be changed to
`/^(?:[A-Za-z]:(\\|\/)|\\\\|\/)/`

**Comment by evilebottnawi** [comment]
Fixed for webpack@5, but we recommend do not use `/` on windows
