### ISSUE TITLE
Es6 import commonjs export seems to work

### ISSUE THREAD

**Issue by OSG-Proj** [webpack/webpack#10997]
Hello, I have found an hidden feature that many sites say this is not possible but, webpack will work with es6 imports on commonjs modules, even visual studio code will have support for them.

**Comment by sokra** [comment]
I wouldn't say it's a hidden feature. How said it's not possible?

**Comment by OSG-Proj** [comment]
It's not a problem, it's just a lot of client side js libraries are made in commonjs and I dont know if it is recommended to use this feature

**Comment by evilebottnawi** [comment]
Expected for compatibility reasons, you can use it
