### ISSUE TITLE
vendors chunk hash changed when only changing index.js

### ISSUE THREAD

**Issue by tomwang1013** [webpack/webpack#11000]
# Bug report

**What is the current behavior?**
https://v4.webpack.js.org/guides/caching/#module-identifiers
I followed the above doc to add `moduleIds: 'hashed',` and change the `index.js` to add or remove the import to `print.js`:
```javascript
// import Print from './print'
...
  ...
  // element.onclick = Print.bind(null, 'hello, webpack!')
```
But the `vendors` chunkHash changed:
`vendors.d1c9ad51eaae38dd8083.js`
`vendors.eef4dd919ffa3214a349.js`

**If the current behavior is a bug, please provide the steps to reproduce.**
```bash
git clone https://github.com/tomwang1013/webpack-demo.git
npm install

edit index.js, comment above 2 lines
npm run build
check venders chunkHash

edit index.js, uncomment above 2 lines
npm run build
check venders chunkHash
```

**What is the expected behavior?**
The vendors' chucnkHash should be same whether or not we change `index.js`

**Other relevant information:**
webpack version:  4.43.0
Node.js version: v12.13.1
Operating System: window10
Additional tools: vscode

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/webpack/webpack/issues/9520, it is same problem
