### ISSUE TITLE
Interface `Configuration` missing property `devServer`

### ISSUE THREAD

**Issue by mightyiam** [webpack/webpack#11006]
# Bug report

**What is the current behavior?**

Using webpack@5.0.0-beta.17, the property `devServer` is missing from the TypeScript interface `Configuration`. But it is a documented property and it works in v4.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

The property should be present in the interface.

**Other relevant information:**
webpack version: 5.0.0-beta.17
Node.js version: v14.3.0
Operating System: Ubuntu
Additional tools: TypeScript

**Comment by sokra** [comment]
It's in the webpack-dev-server typings. Install and add them.

**Comment by evilebottnawi** [comment]
@mightyiam You can open an issue about improve typings in webpack-dev-server

**Comment by mightyiam** [comment]
Thank you. It is indeed an issue in @types/webpack-dev-server but only for webpack v5.
