### ISSUE TITLE
Process will exit if run Compiler.Watching.close twice.

### ISSUE THREAD

**Issue by DiamondYuan** [webpack/webpack#11007]
# Bug report

**What is the current behavior?**
process will exit if run close twice.

**If the current behavior is a bug, please provide the steps to reproduce.**

```
const webpack = require('webpack')
const config = {
  entry: {
    main: "any.js"
  },
  mode: "development",
  output: {
    path: __dirname,
    filename: "any.js",
  },
};
const compiler = webpack(config)
const watcher = compiler.watch({
  poll: 300
})
function close(a) {
  return new Promise(r => {
    a.close(r)
  })
}

(async () => {
  console.log(1)
  await close(watcher)
  console.log(2)
  await close(watcher)
  console.log(3)
})()
```
![image](https://user-images.githubusercontent.com/9692408/83873275-1b047080-a766-11ea-8bf0-9ddc40d285f3.png)

**What is the expected behavior?**

throw error or do nothing.

**Other relevant information:**
webpack version:  4.43.0
Node.js version: v10.17.0
Operating System: macos
Additional tools:

**Comment by sokra** [comment]
Looks like the callback in close is never called when the compiler is already closed. Send a PR

**Comment by evilebottnawi** [comment]
Fixed https://github.com/webpack/webpack/pull/11093 for webpack@5
