### ISSUE TITLE
module.resource is not available for css files

### ISSUE THREAD

**Issue by AnmSaiful** [webpack/webpack#11004]
# Bug report

**What is the current behavior?**

`module.resource` is `undefined`

**If the current behavior is a bug, please provide the steps to reproduce.**

``` js
module.exports = {

    optimization: {

        splitChunks: {

            cacheGroups: {

                vendor: {

                    name    : 'vendor',
                    chunks  : 'all',
                    enforce : true,
                    test    : module => { console.log( module.resource ); return false }

                }
            }
        }
    }
}
```

Using:
- MiniCssExtractPlugin.loader
- postcss-loader
- css-loader
- sass-loader

**What is the expected behavior?**
`module.resource` should be the path of the css file.

**Other relevant information:**
webpack version:  4.43.0
Node.js version: 12.17.0
Operating System: Running on Docker `node`

**Comment by evilebottnawi** [comment]
@webpack-bot move to webpack-contrib/mini-css-extract-plugin
