### ISSUE TITLE
Inline loader from dependency not being resolved correctly

### ISSUE THREAD

**Issue by bensampaio** [webpack/webpack#1101]
On my project I have the following folder structure:
- app
  - gulpfile.js
  - node_modules
    - my-dependency
      - src
        - main.js
      - webpack.config.js
      - node_modules
        - my-loader

On `app/node_modules/my-dependency/main.js` (which is the entry point of my app) I have a line with the following: `require('my!jquery')`. Here `my` referes to `my-loader` under `my-dependency` dependencies.

When I am working under `my-dependency` repo and I execute `webpack` the require mentioned above is resolved correctly and I get the expected output.

On my app I am using gulp, which is using `gulp-webpack-build` to execute `webpack` with the config file in `app/node_modules/my-dependency/webpack.config.js`. Each time I run gulp when it tries to run webpack it gives me the folllowing error on the line I mentioned above: "Unexpected reserved word
You may need an appropriate loader to handle this file type.".

On my `webpack.config.js` file I have the following: `resolveLoader: {root: __dirname + '/node_modules/'}`. Shouldn't this allow webpack to resolve the `my` keyword? Any ideas on what I'm doing wrong? I would really appreciate some help here... I'm trying to solve this problem for quite a while already... Thank you very much!

**Comment by wmertens** [comment]
I don't understand why you need the resolveLoader statement, node should already be looking under node_modules?

On what text does the reserved word error happen?

**Comment by bensampaio** [comment]
I think the problem exists because gulp (which is in `app/`) is running webpack from `app/node_modules/my-dependency/node_modules/webpack` and webpack seems to be looking for `my-loader` in `app/node_modules` but it should look in `app/node_modules/my-dependency/node_modules/`. That is why I tried to use the `resolveLoader` statement but it didn't change anything so I'm not really sure if that is the correct solution.

The reserver word error happens in `require('my!jquery')`.

**Comment by toddself** [comment]
The issue here seems to be that webpack does not work properly when it lives in a directory that has a parent directory named `node_modules`. 

```10:07:45 ~/src/.../node_modules/onshowrunner
↳ pwd
/Users/todd/src/node_modules/onshowrunner
10:13:35 ~/src/.../node_modules/onshowrunner
↳ node_modules/.bin/webpack-dev-server
 http://localhost:8080/webpack-dev-server/
webpack result is served from /
content is served from /Users/todd/src/node_modules/onshowrunner
Hash: e8cd7ed26c3d8b3c0bb4
Version: webpack 1.13.2
Time: 52ms
    Asset    Size  Chunks             Chunk Names
bundle.js  1.5 kB       0  [emitted]  main
chunk    {0} bundle.js (main) 28 bytes [rendered]
    [0] multi main 28 bytes {0} [built] [1 error]

ERROR in ./index.js
Module parse failed: /Users/todd/src/node_modules/onshowrunner/index.js Unexpected token (53:4)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (53:4)
    at Parser.pp$4.raise (/Users/todd/src/node_modules/onshowrunner/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)
    at Parser.pp.unexpected (/Users/todd/src/node_modules/onshowrunner/node_modules/webpack/node_modules/acorn/dist/acorn.js:603:10)
    at Parser.pp$3.parseExprAtom (/Users/todd/src/node_modules/onshowrunner/node_modules/webpack/node_modules/acorn/dist/acorn.js:1822:12)
    at Parser.pp$3.parseExprSubscripts (/Users/todd/src/node_modules/onshowrunner/node_modules/webpack/node_modules/acorn/dist/acorn.js:1715:21)
    at Parser.pp$3.parseMaybeUnary (/Users/todd/src/node_modules/onshowrunner/node_modules/webpack/node_modules/acorn/dist/acorn.js:1692:19)
    at Parser.pp$3.parseExprOps (/Users/todd/src/node_modules/onshowrunner/node_modules/webpack/node_modules/acorn/dist/acorn.js:1637:21)
    at Parser.pp$3.parseMaybeConditional (/Users/todd/src/node_modules/onshowrunner/node_modules/webpack/node_modules/acorn/dist/acorn.js:1620:21)
    at Parser.pp$3.parseMaybeAssign (/Users/todd/src/node_modules/onshowrunner/node_modules/webpack/node_modules/acorn/dist/acorn.js:1597:21)
    at Parser.pp$3.parseParenAndDistinguishExpression (/Users/todd/src/node_modules/onshowrunner/node_modules/webpack/node_modules/acorn/dist/acorn.js:1861:32)
    at Parser.pp$3.parseExprAtom (/Users/todd/src/node_modules/onshowrunner/node_modules/webpack/node_modules/acorn/dist/acorn.js:1796:19)
 @ multi main
webpack: bundle is now VALID.
^C
10:13:51 ~/src/.../node_modules/onshowrunner
↳ cd ..
10:14:05 ~/src/.../src/node_modules
↳ mv onshowrunner ../.
10:14:10 ~/src/.../src/node_modules
↳ cd ..
10:14:12 ~/src
↳ cd onshowrunner/
10:14:13 ~/src/.../src/onshowrunner
↳ pwd
/Users/todd/src/onshowrunner
10:14:15 ~/src/.../src/onshowrunner
↳ npm start

> showrunner@1.0.0 start /Users/todd/src/onshowrunner
> webpack-dev-server --inline --content-base . --history-api-fallback

 http://localhost:8080/
webpack result is served from /
content is served from /Users/todd/src/onshowrunner
404s will fallback to /index.html
Hash: cc90896f4b525df842cb
Version: webpack 1.13.2
Time: 3369ms
                  Asset     Size  Chunks             Chunk Names
              bundle.js  1.34 MB       0  [emitted]  main
static/styles/style.css  21.9 kB       0  [emitted]  main
[ a ton of output clipped]
webpack: bundle is now VALID.
```

**Comment by toddself** [comment]
So why does webpack care about what a parent directory has been named?

**Comment by wmertens** [comment]
@toddself can you provide a gist with your webpack config and .babelrc?

**Comment by toddself** [comment]
Here's what our developer created as a webpack config.  There is no `.babelrc` for this project.

<details>
```js
const autoprefixer = require('autoprefixer')
const ExtractTextPlugin = require('extract-text-webpack-plugin')
const path = require('path')

const sassLoaders = [
  'css-loader',
  'postcss-loader',
  'sass-loader?indentedSyntax=sass&includePaths[]=' + path.resolve(__dirname, './src')
]

const config = {
    entry: [
        "./index.js"
    ],
    module: {
        loaders: [
            {
                test: /\.js$/,
                exclude: /node_modules/,
                loader: 'babel-loader?presets[]=es2015&presets[]=react'
            },
            {
                test: /\.scss$/,
                loader: ExtractTextPlugin.extract('css!sass')
            }
        ]
    },
    output: {
        filename: 'bundle.js',
        publicPath: ''
    },
    plugins: [
        new ExtractTextPlugin('static/styles/style.css', {
            allChunks: true
        })
    ],
    postcss: [
        autoprefixer({
            browsers: ['last 2 versions']
        })
    ],
    resolve: {
        extensions: ['', '.js', '.scss'],
        root: [path.join(__dirname, './src')]
    }
}

module.exports = config;
```
</details>

**Comment by wmertens** [comment]
Exclude: /node_modules/ ignores all paths with node_modules somewhere in
them. So if you have a parent node_modules dir, you ignore everything.

That rule should be `include: __dirname, exclude: path.join(__dirname,
'node_modules')`

**Comment by TheLarkInn** [comment]
I'm going to close this as this was from webpack 1. If this is still an issue, please resubmit a new issue with the information listed in our issue template (version, repro repo, etc.)
