### ISSUE TITLE
Question: webpackPrefetch

### ISSUE THREAD

**Issue by Legends** [webpack/webpack#11013]
My static app is using `html-webpack-plugin`.

I have an entry-chunk which imports a module `app.js`.
`App.js` does the following:

`import(/* webpackPrefetch: true */ "gsap");`

> Sidenote: Here we need another plugin to inject `<link rel='prefetch'.../>` into the document, as  the `html-webpack-plugin` does not do that.

But during page load I can see, that `webpack` attaches a script tag for `gsap` into the head tag, 
which means: `gsap` will be loaded and executed immediately, which is against prefetch.

Prefetch should only pre-cache the file and not execute it.

Why does webpack add a `<script src='...gsap.js'...</script>` instead of only adding a `<link rel='prefetch' src='gsap.js' .../>`

Is another plugin needed in order to remove the `gsap` chunk from the compilation?

**Comment by Legends** [comment]
Or should I also add `/* webpackIgnore: true */` and do the `link` injection in a separate plugin?

**Comment by sokra** [comment]
You need to use `import()` as usual (somewhat lazy) and add the prefetch there. Webpack will figure out when to prefetch.

Once you call `import()` it will load the chunk.

**Comment by Legends** [comment]
[Webpack docs for prefetch-preload](https://webpack.js.org/guides/code-splitting/#prefetchingpreloading-modules)

`import(/* webpackPrefetch: true */ 'LoginModal'); // this is how I call it`

> This will result in <link rel="prefetch" href="login-modal-chunk.js"> being appended in the head of the page, which will instruct the browser to prefetch in idle time the login-modal-chunk.js file.

Neither `webpack `nor the `html-webpack-plugin` are adding `<link rel="prefetch"...` to the head tag. `Prefetching` is a browser thing. 
That's why I have a plugin which adds the prefetch/preload links to the head tag during `compilation`.
Preload works fine with webpack. Webpack adds the script tags for `preload `resources to the `head ` tag. But adding a `script `tag for `prefetch `is not desired, because it gets executed on the current page.

Just following the docs... perhaps someone can update them to make it more clear.

Conclusion:

Preload works fine in conjunction with my plugin, but adding a `<script src='gsap'` to the `head `is not prefetching, it's a normal `fetch`.

**Comment by sokra** [comment]
If it's adding a script tag you are calling `import()`. If you like it to prefetch you must not call `import()` but have it in a click handler or a timeout or whatever. Prefetching is done when the `import()` becomes visible, not when it's called.

**Comment by Legends** [comment]
Hm, if you do a [prefetch](https://developer.mozilla.org/en-US/docs/Web/HTML/Link_types/prefetch) in the click-handler, then it's already too late.
In the click-handler it should already be in the `cache` and load whatever component instantly.

> The prefetch keyword for the rel attribute of the <link> element is a hint to browsers that the user is likely to need the target resource for future navigations, and therefore the browser can likely improve the user experience by preemptively fetching and caching the resource.

**Comment by Legends** [comment]
Ah ok. Perhaps this could be added to the docs as an example. Thanks Tobias!
Closing this, question answered.

**Comment by Legends** [comment]
@sokra 

One thing:
I have a plugin which adds` preload/prefetch `statements during `compile time`.
Now the `prefetch `statements will get doubled because `webpack `adds the same `prefetch` statements again during `runtime`.

Is it possible to tell webpack not to add these `<link rel='prefetch' href="some.js"/>` to the head tag, as this is handled by my plugin (for `html-webpack-plugin`) ?

```
<head>
<link rel='prefetch' src='some.js' />  // added during compile time by plugin
<link rel='prefetch' src='some.js' />  // added during runtime by webpack
</head>
```

Perhaps someone could live with doubled `prefetch `statements, but if feels very dirty and I don't know if this has any side effects on prefetching resources.

**Comment by lexmes** [comment]
@Legends did you find a solution for your last comment? I'm facing the same issue.

**Comment by vadim-ch** [comment]
I have the same issue. Can someone help me?
