### ISSUE TITLE
Loader changes watched in watch mode

### ISSUE THREAD

**Issue by vankop** [webpack/webpack#11017]
# Bug report

**What is the current behavior?**

Loader changes watched in watch mode 

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/vankop/watch-loader-bug

**What is the expected behavior?**

webpack should not watch loaders

**Other relevant information:**
webpack version:  5.0.0-beta.17
Node.js version: 10 LTS
Operating System: OS X
Additional tools:

**Comment by evilebottnawi** [comment]
bump
