### ISSUE TITLE
Why have a gitter if no one ever answers? Shut it down, delink it.

### ISSUE THREAD

**Issue by working-name** [webpack/webpack#11018]
It's beyond frustrating to see this happening. Back in the IRC days (which thankfully is still alive and kicking) you'd join a channel, ask a question, and get an answer. Now it's all about the fancy eye candy but zero answers. Your gitter feed is filled to the brim with questions but that's all. Was the point of it to avoid clogging issues with questions you were never going to tackle? :) If that's it, carry on.

**Comment by evilebottnawi** [comment]
Be patient and you will get an answer, no one can answer you 24 hours 7 days a week without delay

**Comment by working-name** [comment]
It's not about patience, there are no answers to questions for weeks if you check. I attempted to post a question 2x times, waited 1 week the first time, 13 days the second time. No answer. Deleted my questions since I reached a conclusion on my own. 

My recommendation stands: shut it down, delink it from the main page. It's useless and it only creates frustration on the user side.
