### ISSUE TITLE
HMR not propagating correctly with circular imports and re-exports

### ISSUE THREAD

**Issue by pmmmwh** [webpack/webpack#11016]
# Bug report

**What is the current behavior?**

At import time, the dependency will be `undefined`, and the update cannot be called correctly after the first HMR cycle.

**If the current behavior is a bug, please provide the steps to reproduce.**

Reproducible Repo:
https://github.com/pmmmwh/refresh-cycle-repro

Run `yarn start` and then try to edit `SurveyOverview.js`, like returning `101` instead of `100` in the function.

The `module.hot.accept()` calls are intentionally placed for only those files - they are recognized as "boundaries" for HMR to happen in React Fast Refresh world.

**What is the expected behavior?**

The dependency should be the exact exports and thus calls to it should work correctly, even after HMR.

To be honest, I'm not sure if this is too extreme/specific of an edge case which is hitting the boundaries of Webpack's CJS/ESM module system. It involves re-exports and circular dependencies (both need to be related to an unaccepted dependency for this issue to rise) which, in practice, are both very difficult to deal with properly in CJS. To my understanding, Webpack's module system aligns closer to CJS - so I'm also not sure if this can be solved at all.

This might be related to #10870.
Related issue for FR: pmmmwh/react-refresh-webpack-plugin#81

**Other relevant information:**

Webpack version: 4.43.0
Node.js version: 14.4.0
Operating System: macOS 10.15.5
Additional tools: None

**Comment by sokra** [comment]
I didn't run the code yet (on mobile), but from reading the code this seem to be a circular depenency issue.

In a circular depenency behavior often depends on the module you execute first. This one will see all it's dependencies completely, but the child modules may see the parent module incompletely. Here routes execute first and can see Dashboard.

But with a module.accept handler re-execution will start at the accepted module, so we enter the cycle at a different module, which causes a behavior change.

I guess we could detect these circular depenendencies in the HMR runtime and try to enter the cycle at the correct module on re-execution. But this could be a bit tricky to implement.

**Comment by evilebottnawi** [comment]
bump

**Comment by alexander-akait** [comment]
I think still valid

**Comment by dontsave** [comment]
we are running into this as well. some modules become undefined after a fast refresh in a monorepo with re-exports and some circular imports

**Comment by sokra** [comment]
I think this is a "won't fix". If you accept a module it will start executing there. If you don't want that behavior place your accept somewhere else.

**Comment by gaearon** [comment]
I’m probably missing something — a module originally having exports but later starting to have undefined as exports, seems like a bug either way? Regardless of how accept works I wouldn’t expect exports to “get lost”. Even stale exports would be better imo.

**Comment by alexander-akait** [comment]
@gaearon Can you open a new issue and describe why do you think it?
