### ISSUE TITLE
Allow global config for webpackMode

### ISSUE THREAD

**Issue by marian-c** [webpack/webpack#11012]
## Feature request

**What is the expected behavior?**

I expect to globally change the webpackMode of `import()` statements

**What is motivation or use case for adding/changing the behavior?**

I am in a situation in which I need `webpackMode: "lazy"` for client rendering and `webpackMode : "eager"` for server rendering. To have this dual behaviour currently I need to test some global env variable (e.g: `process.env.IS_SERVER`) for every `import()` statement.

```javascript
// written on the spot, don't expect to actually work
function loadAndUseACertainModule() {
  let mod;
  if (process.env.IS_SERVER === 'true') {
    mod = import(/*webpackMode: "eager"*/ './mod') 
  } else {
    mod = import(/*webpackMode: "lazy"*/ './mod') 
  }
  mod.then(...)
}
``` 

Hope you can see that doing this for every lazily loaded module is not ideal

**How should this be implemented in your opinion?**

A config in `webpack.config.js` could sit in between the default and the magic comment.
No idea about the config name and position.
This new config value will be used instead of the default if the magic comment is not present.

**Are you willing to work on this yourself?**
yes

---
Edit: apologies in advance if there's already a way of changing the webpackMode of import() statements without the magic comment already; Searching "eager" on the docs only revealed the magic comment bit

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/webpack/webpack/issues/5029

**Comment by vankop** [comment]
hm.. this is not done yet.

**Comment by vankop** [comment]
I think we can add parser option for this
