### ISSUE TITLE
Is it possible to get a compiled component from a remote cdn and use in another project ? 

### ISSUE THREAD

**Issue by TRUEND** [webpack/webpack#11028]
I wanted to get a react component compiled from a cdn and use in another part of my project, is it possible to do this? 

something like dinamic import. 
`import("./mycomponent.js").then(...)`
but insteed of use a component from the same project I wanted to get from a remote url .
`import("https://cdn.whatever/mycomponent.js")`

is this possible? I know I cannot do this with that sintax, but is it possible to get a component from a remote origin and use in my project ?

**Comment by evilebottnawi** [comment]
`webpackIngore` https://webpack.js.org/api/module-methods/#magic-comments, do not remove issues template in the future, fro questions please use gitter or stackoverflow
