### ISSUE TITLE
Webworker target + Wasm-pack-plugin = importScripts on imaginary files?

### ISSUE THREAD

**Issue by khoover** [webpack/webpack#11023]
# Bug report

**What is the current behavior?**
I get
`DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The URL '0.js' is invalid.
    at http://localhost:8080/worker.js:76:14
    at async Promise.all (index 0)`

**If the current behavior is a bug, please provide the steps to reproduce.**
Clone the repo from https://github.com/khoover/Webworker-webpack-wasmpack-test, run `yarn start`.

**What is the expected behavior?**
No error, should log, in some order, "In index.", "Made worker.", "In worker." twice, "Loaded wasm.", and "Hello world!" to the console.

**Other relevant information:**
webpack version:  4.43.0
Node.js version: 12.8.0
Operating System: WSL
Additional tools: wasm-pack 0.9.1, wasm-pack-plugin 1.3.1, rustc/cargo 1.44.0, webpack-dev-server 3.11.0.

**Comment by khoover** [comment]
Setting `output.publicPath` to be the path the worker's being served from fixed the issue, but it seems strange that that would be necessary?

**Comment by khoover** [comment]
Correction, it only worked for the index2 variant I added, available via `yarn serve` then manually import()-ing index2 from the command line.

**Comment by evilebottnawi** [comment]
Bump

**Comment by evilebottnawi** [comment]
Can't reproduce, all works fine, my output:
```
In index.
index.js?ee1c:5 Made worker.
client?81da:52 [WDS] Live Reloading enabled.
worker.js?301f:1 In worker.
worker.js?301f:2 Loaded wasm
cbbdb489-a4b9-4836-acb7-f6f407e566e9:1 In worker.
index_bg.js?6119:61 Hello world!
client?81da:52 [WDS] Live Reloading enabled.
```

Feel free to feedback

**Comment by evilebottnawi** [comment]
Try to update deps
