### ISSUE TITLE
SplitChunks generates same file names for chunks, with different casing

### ISSUE THREAD

**Issue by pavsaund** [webpack/webpack#11026]
# Bug report

**What is the current behavior?**
On adding a new feature to an application, webpack build split two of the chunks with the same name and capitalisation difference. This broke the output.filename in dev with `[name].[hash].chunk.js`. Ref [twitter thread](https://twitter.com/pavsaund/status/1270674506881908736)

The overlapping chunks reported in build log were:
```sh
app~._Features_customers_A.189e07408f4aa1d4b39f.chunk.js   184 KiB
app~._Features_customers_a.189e07408f4aa1d4b39f.chunk.js   163 KiB
```

The file output was:
```sh
app~._Features_customers_A.189e07408f4aa1d4b39f.chunk.js   184 KiB
```
**If the current behavior is a bug, please provide the steps to reproduce.**
I've been struggling to reproduce this in a standalone repository. It's never been an issue before, and based on a [comment by on twitter](https://twitter.com/wSokra/status/1270774860466323462?s=20), it seems like an edge case.

**What is the expected behavior?**
Should not overlap the same chunk names with different casing.

**Other relevant information:**
webpack version:  4.43.0
Node.js version: v12.14.0
Operating System: macOS Catalina 10.15.5
Additional tools:

**Comment by Shubham819** [comment]
https://github.com/webpack/webpack/issues/7230#issuecomment-643174712

Can Any1 help with this

**Comment by rahullli** [comment]
Hello , I am new in open source but want to work on this issue .
Can you please provide me some more details about this issue .

**Comment by sokra** [comment]
Problem is in webpack/lib/util/deterministicGrouping.js `getName` it should compare chars without casing instead.

**Comment by sokra** [comment]
I'll fix it
