### ISSUE TITLE
Proxy: Change port but keep original url

### ISSUE THREAD

**Issue by simkessy** [webpack/webpack#11027]
I have webpack dev server running in docker and proxying `/api` requests to a different port. 

    devServer: {
      // 0.0.0.0 binds to all interfaces. The public port is 8080 which is served
      // by nginx and proxied to the internal webpack port of 10001.
      host: '0.0.0.0',
      public: '0.0.0.0:0',
      port: 10001,
      sockPort: 80,
      hotOnly: true,
      publicPath: '/',
      headers: { 'Access-Control-Allow-Origin': '*' },

      proxy: [
        {
          context: ['/login', '/api'],
          target: 'https://myusername.companydomain.com:8080'
        }
      ]
    }

The issue I have is that `myusername` is dynamic based on the user machine. I just need to proxy the requests to a different port. Is there a way to do this?

**Comment by zcfan** [comment]
Different port in the same host? try `https://localhost:8080`

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Please use stackoverflow or gitter for questions
