### ISSUE TITLE
Modifying options

### ISSUE THREAD

**Issue by artola** [webpack/webpack#11036]
# Bug report

**What is the current behavior?**
Some config's options modified with an ad-hoc plugin do not work on v5 while it works on v4.

**If the current behavior is a bug, please provide the steps to reproduce.**

For example, the `ConfigStuff` sets the `libraryTarget` to `amd` but without success.

```js
class ConfigStuff {
  apply(compiler) {
    compiler.options.output.libraryTarget = 'amd';
  }
}

module.exports = {
  entry: path.resolve('src/index.js'),
  output: {
    path: path.resolve('dist'),
  },
  plugins: [
    new ConfigStuff(),
  ],
};
```

**What is the expected behavior?**

If a plugin applies changes to the config, they should have taken during the compilation as it happens with v4.

**Other relevant information:**
webpack version:  5.0.0-beta.17
Node.js version: v12.16.2
Operating System: macOS
Additional tools:

**Comment by sokra** [comment]
Yep this is allowed. Options are normalized before plugins are applied so you have to modify the normalized options. Here `output.libraryTarget` doesn't exist as it's old and normalized to the now form `output.library.type`

**Comment by artola** [comment]
@sokra Thanks a lot!
