### ISSUE TITLE
Loaders written in Coffeescript/other compile-to-js languages don't work

### ISSUE THREAD

**Issue by KyleAMathews** [webpack/webpack#1103]
I have a loader I'm writing that's unique to my project. I want to write it in coffeescript but if I do, webpack won't require it for some reason despite everything else being written in coffeescript.

**Comment by shama** [comment]
In your webpack config file, are you calling `require('coffee-script/register')` to register coffee-script first?

**Comment by KyleAMathews** [comment]
I invoke the file which is requiring the config and other files with the
coffee executable so essentially yes.

**Comment by shama** [comment]
Here are the examples that work for me:

I have a loader named `./my-loader.coffee`:
```coffeescript
module.exports = ->
  return 'module.exports = "I work"'
```

Then with `webpack.config.coffee`:
```coffeescript
module.exports =
  entry: './src/index.js'
  output:
    path: 'build/'
    filename: 'index.js'
  module:
    loaders: [
      { test: /\.js$/, loader: require('path').resolve('./my-loader.coffee') }
    ]
```

My loader is read properly. If I use a `webpack.config.js` file instead, I need to do:

```js
require('coffee-script/register')
module.exports = {
  entry: './src/index.js',
  output: {
    path: 'build/',
    filename: 'index.js'
  },
  module: {
      loaders: [
          { test: /\.js$/, loader: require('path').resolve('./my-loader.coffee') },
      ],
  }
}
```

**Comment by IngwiePhoenix** [comment]
WebPack uses standard `require()` within laoders to open the files. So you have to modify `require` yourself - WebPack won't pick it up.

A solution would be to use the fact that laoders exist and try to load the loader (lol) and then executing the resulting code. But, tbh, that sounds a bit overweight.

Compile your loaders to plain JS and provide the flat source in a `src/` folder. That is what you typically want anyway.

```
myapp/
    - src/
    - lib/
    - package.json
```

Define a "build" section within the `scripts` section and name it correctly. This allows you to "build" your module on install time. That, at least, is what I would do. :)

Kind regards, Ingwie.

PS: See https://docs.npmjs.com/misc/scripts to learn more about the "scripts" section.

**Comment by bebraw** [comment]
Safe to close?
