### ISSUE TITLE
After each code change, the copy operation of the "copy-webpack-plugin" plug-in is executed at the same time as the recompilation operation.

### ISSUE THREAD

**Issue by LP1994** [webpack/webpack#11032]
webpack: v4.43.0
webpack-dev-server: v3.11.0
copy-webpack-plugin: v6.0.2
html-webpack-plugin v4.3.0
Windows 10 professional edition 1902 18363.900
node.js: v14.4.0
npm: v6.14.5

Describe the bug:
1、
After each code change, the copy operation of the "copy-webpack-plugin" plug-in is executed at the same time as the recompilation operation.
![image](https://user-images.githubusercontent.com/12012671/84560498-6bd42480-ad77-11ea-99e3-3c619292c512.png)

To Reproduce:
1、The configuration of "copy-webpack-plugin" is:
![image](https://user-images.githubusercontent.com/12012671/84560514-adfd6600-ad77-11ea-91f1-48aaac850431.png)
2、The configuration of "html-webpack-plugin" is:
![image](https://user-images.githubusercontent.com/12012671/84560600-3c71e780-ad78-11ea-9726-5bc75928e36a.png)
3、The configuration of "webpack" is:
![image](https://user-images.githubusercontent.com/12012671/84560630-704d0d00-ad78-11ea-9e39-fb5b5c54d55f.png)

Expected behavior：
1、
After each code change, the recompile operation will not be executed at the same time as the "copy-webpack-plugin" plugin's copy operation.
2、
The "copy-webpack-plugin" plug-in will be re copied only when the copied file changes.

**Comment by LP1994** [comment]
At the same time, I asked this question in the feedback of these three plug-ins(webpack、html-webpack-plugin、copy-webpack-plugin).

**Comment by sokra** [comment]
> At the same time, I asked this question in the feedback of these three plug-ins(webpack、html-webpack-plugin、copy-webpack-plugin).

So we don't need it here

**Comment by LP1994** [comment]
OK!
I just want to ask everybody if everybody have the same problem, because the developers of "copy-webback-plugin" say it is the problem of "html-webback-plugin", but neither of them has put forward corresponding solutions. I don't know when to solve this problem. After all, "weback 5" is about to be officially released. I hope this bug won't make too many people think it's a "weback 5" problem.

**Comment by sokra** [comment]
I don't understand your problem excatly, but if you expect that the copy-webpack-plugin only emits file when they have changed, I agree with that and this could be improved in the copy-webpack-plugin. But I don't see how this would cause any problems with the html-webpack-plugin.

**Comment by evilebottnawi** [comment]
No problem here, we should always emit all files, otherwise plugins like `clean-webpack-plugin` and other will not work. I don’t even see a bug here, everything works fine, just big stats output

**Comment by sokra** [comment]
True, but you should emit the same Source instance again. This way webpack will not write them again.

**Comment by evilebottnawi** [comment]
@sokra It is not easy, there are a lot of transformations and etc, but i think how we can improve it

**Comment by evilebottnawi** [comment]
@webpack-bot move to webpack-contrib/copy-webpack-plugin
