### ISSUE TITLE
at webpack.config.ts , How should I configure webpack-dev-server

### ISSUE THREAD

**Issue by wuming123** [webpack/webpack#11031]
At webpack.config.ts How should I configure webpack-dev-server

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Please use stackoverflow or gitter for questions
