### ISSUE TITLE
[BUG] LogLevel not mute all log output

### ISSUE THREAD

**Issue by MaxmaxmaximusGitHub** [webpack/webpack#11044]
![image](https://user-images.githubusercontent.com/60403187/84706739-2b86c900-af66-11ea-9f43-fd16d874982c.png)

webpack.config.js
```javascript
module.exports = {
  stats: 'errors-only',

  devServer: {
    hot: true,
    clientLogLevel: 'none'
  },
}
```

When I edit my site and click save, the log messages ([HMR] and [WDS]) do not get to my console. But the first time the page loads, or if I press F5 (refresh the page), then I see this line in the console: ```[HMR] Waiting for update signal from WDS...```. It should not appear, cuz I turned off the log level.

however, if I directly edit the file `node_modules/webpack/hot/log.js` and write there `var logLevel = "none";` then the log level works as it should, and there is nothing in the console.

The bug is that when you first load the page, HMR has time to write one line exactly

**Comment by MaxmaxmaximusGitHub** [comment]
UPD
===

i inistall some npm packages, and my webpack  package will repare, and loging is back(

![image](https://user-images.githubusercontent.com/60403187/84718432-3d299a00-af81-11ea-88cc-918be8beddc7.png)

**Comment by evilebottnawi** [comment]
Not related to webpack, it is bug on `webpack-dev-server` side and will be fixed in `v4`
