### ISSUE TITLE
Hash Difference of bundle files built in the same env

### ISSUE THREAD

**Issue by wkk5194** [webpack/webpack#11041]
# Bug report

**What is the current behavior?**

build the same project two times in the same environment(in fact, I build in two dockers of completely same env), but the hash tags of some bundle files are different.

![image](https://user-images.githubusercontent.com/42814736/84643247-2a3aa980-af30-11ea-9b98-0d3316f6d301.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

1. use this demo project to test [demo](https://github.com/wkk5194/umi-dva-antd-mobile)
2. run `npm i && npm build`

**What is the expected behavior?**

same hash tag of bundle files no matter how many times i build

**Other relevant information:**
webpack version:  4
Node.js version: 14.4
Operating System: docker/linux redhat
Additional tools:

**Comment by evilebottnawi** [comment]
Problem on `css-loader` side - https://github.com/webpack-contrib/css-loader/issues/886

**Comment by evilebottnawi** [comment]
Please create **minimum** reproducible test repo in future, I it very hard to catch problem using boilerplates and big projects
