### ISSUE TITLE
if (types.has(key)) i++; ^  TypeError: Cannot read property 'has' of undefined  at getNumberOfMatchingSizeTypes

### ISSUE THREAD

**Issue by jackIsZlg** [webpack/webpack#11048]
when  I run  webpack --mode development , with Basic react project。
Then  I got wrong
![image](https://cdn.weipaitang.com/static/20200616510b8c0d-faeb-8c0dfaeb-a83a-3f63c4446ce8-W1092H762)

in this file:  webpack/webpack5/node_modules/webpack/lib/util/deterministicGrouping.js:122
I commented out this code, replace:
   // if (types.has(key)) i++;
   if (types && types.has(key)) i++;

it worked;

**Comment by sokra** [comment]
Interesting problem. There really seem to be a bug here.

https://github.com/webpack/webpack/blob/930860dd8948a4db554b8e8e240a18b0541d03d5/lib/util/deterministicGrouping.js#L285-L286

`getNumberOfMatchingSizeTypes` is called here without second argument. I think it should receive `problemTypes` too, but need to look into that in detail...

**Comment by sokra** [comment]
Still valid

**Comment by snitin315** [comment]
I will send a PR.
