### ISSUE TITLE
#__PURE__ not honored in tree-shaking

### ISSUE THREAD

**Issue by jeantil** [webpack/webpack#11042]
# Bug report

I intially formulated this as a [stackoverflow question](https://stackoverflow.com/questions/62168548/why-does-webpack-4-include-the-whole-file-for-single-named-import) but failed to get an answer there. I'm submitting this here as I have now become convinced this is a bug.

**What is the current behavior?**

When importing a named export marked with `#__PURE__` webpack fails to tree-shake the remainder of the file.

Given the following files: 
```js
//a.js
export const X = /*#__PURE__*/ "X";

const a = function () {
  return "About a!";
};
a.foo = function () {
  return "foo";
};
export default a;
```
and 
```js 
//main.js
import { X } from "./a";
import { Y } from "./b";

console.log(X, Y)
```

Webpack 4.43 in production mode inlines the whole `a.js` file in the resulting bundle. 

Rollup only includes X from a.js ([demo](https://rollupjs.org/repl/?version=2.12.1&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QnglN0QlMjBmcm9tJTIwJy4lMkZhJyU1Q24lNUNuY29uc29sZS5sb2coeCklMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJhLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMGNvbnN0JTIweCUzRDElNUNuJTVDbmNvbnN0JTIwYSUyMCUzRCUyMGZ1bmN0aW9uKCklN0IlMjByZXR1cm4lMjAlNUMlMjJhJTVDJTIyJTIwJTdEJTVDbmEuZm9vJTNEZnVuY3Rpb24oKSU3QiUyMHJldHVybiUyMGZvbyUyMCU3RCU1Q24lNUNuZXhwb3J0JTIwZGVmYXVsdCUyMGElM0IlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyY2pzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)) which is what I expected.

The following didn't help :
* Adding `"sideEffect": false` to `package.json`
* Adding `optimization.usedExports: true` to `webpack.config.js`

The bailout debugging of the [concatenation plugin](https://webpack.js.org/plugins/module-concatenation-plugin/#debugging-optimization-bailouts) doesn't yield additional insight.

I have a [sandbox repository](https://github.com/jeantil/next-bugs/tree/bug/incorrect_tree_shaking) which exhibits the problem.
Clone the project, then run `yarn` to install the dependencies. 
* you can run `webpack` to build `dist/purejs.bundle.js` in dev mode and confirm that the default export is flagged `/* unused harmony default export */` 
* you can run `webpack -p` to build `dist/purejs.bundle.js` in prod mode and confirm that the bundle still contains `return"About a!"` and `foo=function(){return"foo"}` 
* you can run ` webpack --display-optimization-bailout  -p  ` to see that the concatenation plugin doesn't warn of bailout on `a.js` or `b.js`

**Other relevant information:**
webpack version: 4.43  
Node.js version: 12.16.3
Operating System:  Linux
Additional tools: n/a

**Comment by sokra** [comment]
You can fix that with this configuration:

``` js
const TerserWebpackPlugin = require("terser-webpack-plugin");

/** @type {import("webpack").Configuration} */
module.exports = {
    optimization: {
        minimizer: [
            new TerserWebpackPlugin({
                terserOptions: {
                    compress: {
                        passes: 3
                    }
                }
            })
        ]
    }
}
```

Seems like a single compression pass in terser is not enough to compress this code.

cc @evilebottnawi maybe we should increase the default?

**Comment by evilebottnawi** [comment]
@sokra I’m afraid that this could have a very negative effect on build speed. I will look deeply today

**Comment by jeantil** [comment]
@sokra thanks a lot for the pointer I had looked at terser options but I was at a loss which to enable. Your configuration indeed helps with the sample I provided. 
Unfortunately for me it seems my reproduction was too simple, once I reinject the proposed change in the next.js build (even upping the passes to 30) the inlining comes back. I'll try digging in next.js now.

**Comment by sokra** [comment]
Ok. Please create a new repro case if you want more help.

Little note: `/*#__PURE__*/` has only an effect if it is in front of a function call. `/*#__PURE__*/ "X"` is not valid. `/*#__PURE__*/ f()` is valid.

**Comment by jeantil** [comment]
> /*#__PURE__*/ has only an effect if it is in front of a function call. 

I was unaware of this specificity, thanks again.
