### ISSUE TITLE
DefinePlugin bug

### ISSUE THREAD

**Issue by kaniak274** [webpack/webpack#11050]
# Bug report

Today I tried to use `DotenvPlugin` but it didn't work. I've looked up the issue and from my research the problem is within `DefinePlugin` initialization. 

**What is the current behavior?**

First I tried to follow the documentation and create some env variables:
```
new webpack.DefinePlugin({
  'process.env.TEST': '"TEST"'
});
```
but it didn't work i.e. process.env was empty.
Instead I did:
```
new webpack.DefinePlugin({
  'process.env': {
    NODE_ENV: '"TEST"',
  }
});
```
and it did work. Unlucky for me dotenv-webpack is using the first style of initializing the plugin with variables.

**If the current behavior is a bug, please provide the steps to reproduce.**
Just use plugin `DefinePlugin` as follows:
```
new webpack.DefinePlugin({
  'process.env.TEST': '"TEST"'
});
```

**What is the expected behavior?**
It does work as expected as this point says
https://webpack.js.org/plugins/environment-plugin/#usage in documentation.

**Other relevant information:**
webpack version:  4.43.0
Node.js version: v10.21.0
Operating System: Ubuntu 20.04
Additional tools: Docker / docker-compose

**Comment by sokra** [comment]
You should not write `process.env` in your code but directly `process.env.TEST` instead.

**Comment by kaniak274** [comment]
As I said, I tried following the docs and do:
```
new webpack.DefinePlugin({
  'process.env.TEST': '"TEST"'
});
```
but it didn't work, and the plugin `dotenv-webpack` does not work as well at least for me.

**Comment by evilebottnawi** [comment]
Please report the issue to `dotenv-webpack` plugin

**Comment by sokra** [comment]
It's expected that `process.env` doesn't work. Only `process.env.TEST` works.
