### ISSUE TITLE
need help about splitChunk

### ISSUE THREAD

**Issue by Taoja** [webpack/webpack#11058]
how can I extract sync chunk from some async chunks with splitChunk?

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
