### ISSUE TITLE
Vagrant HMR problem

### ISSUE THREAD

**Issue by zeravcic** [webpack/webpack#11052]
Hi to all,
I don't know if it's related to a Webpack, but please take a look at the Hot Module Replacement problem described on:

- Create-nuxt-app issue "[Laravel Homestead and Nuxt HMR problem](https://github.com/nuxt/create-nuxt-app/issues/550)" or

- Laracast forum discussion "[Laravel homestead and nuxt](https://laracasts.com/discuss/channels/vue/laravel-homestead-and-nuxt#reply-617075)".

Any heeelp?

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Wait answer from maintainers of `creat-nuxt-app`, no need spam, thanks
