### ISSUE TITLE
Using `vue-loader` with rules that use `oneOf` and/or a function for `use` doesn't work

### ISSUE THREAD

**Issue by dietergeerts** [webpack/webpack#11055]
While searching for a solution, I found the following existing, but closed, tickets, which where never resolved:
- https://github.com/webpack/webpack/issues/8406
- https://github.com/webpack/webpack/pull/8940

# Bug report

**What is the current behavior?**

see linked tickets

**If the current behavior is a bug, please provide the steps to reproduce.**

see linked tickets

**What is the expected behavior?**

see linked tickets

**Other relevant information:**
webpack version:  4.43.0
Node.js version: 10
Operating System: Windows 10
Additional tools:

**Comment by sokra** [comment]
> see linked tickets

They have been resolved. Provide your own repro case if you have a different problem

**Comment by dietergeerts** [comment]
They haven't been resolved, please read their content. The PR was never merged, and thus the problem was never solved.

**Comment by evilebottnawi** [comment]
@dietergeerts resolved in `webpack@5`
