### ISSUE TITLE
Support for "node" config object to include keys like "fs", "module"

### ISSUE THREAD

**Issue by saravanan10393** [webpack/webpack#11064]
# Bug report
I am using Antlr4 which was working fine with webpack-4, but after upgrading to webpack-5, it throwed the following error
```
Module not found: Error: Can't resolve 'fs' in '/Users/Saravanan/projects/frontend/widgets/web/node_modules/antlr4'
```
As specified here in [stackoverflow](https://stackoverflow.com/questions/54754585/how-to-use-antlr-if-an-error-with-fs-occursl) adding the following in the webpack config will work.
```
node: {
  fs: "empty",
  module: "empty"
}
```
But in webpack-5 there is no support to specify those keys in node object, it was specified [here in the doc](https://webpack.js.org/configuration/node/)

That implies that i could able to use the libraries that i were using with webpack-4.
I am kind of struck because it blocks my development

**What is the current behavior?**
Not allowing to specify the node object with keys that was working well in webpack-4

**If the current behavior is a bug, please provide the steps to reproduce.**
N/A

**What is the expected behavior?**
Webpack-5 should allow pollyfill the nodeJs options

**Other relevant information:**
webpack version:  webpack-5-beta-16
Node.js version: node 12
Operating System: Mac Os
Additional tools: [Antlr4](https://www.npmjs.com/package/antlr4)

**Comment by evilebottnawi** [comment]
```js
resolve: {
    alias: {
      // path to polyfill
      'fs': false
    },
  },
```

**Comment by evilebottnawi** [comment]
Answer above, feel free to feedback
