### ISSUE TITLE
Resolving custom file from another folder with invalid package.json causes webpack not to find module

### ISSUE THREAD

**Issue by pieczorx** [webpack/webpack#11062]
# Bug report

**What is the current behavior?**
Error: Cannot find module 'alligator/file.js'

**If the current behavior is a bug, please provide the steps to reproduce.**
Let's assume we have 4 folders and 4 files like below:

MAIN FOLDER
|- A
|-|- webpack.config.js
|-|- entry.js
|- B
|-|- package.json
--|- C
----|- file.js

webpack.config.js **in folder A**:
```javascript
module.exports = {
	context: "Absolute path to folder A",
	resolve: {
		alias: {
			alligator: "Absolute path to folder C"
		}
	},
	target: 'node',
	mode: 'development'
}
```

entry.js **in folder A**:
```javascript
import something from 'alligator/file.js'
console.log(something)
```

file.js **in folder C**:
```javascript
export default {
	hello: 'Im alligator'
}
```

and finally **broken** package.json **inside folder B**:
```
{I'm broken json file: """""123}
```

**What is the expected behavior?**
Include that file and don't check package.json which is not associated with this file in any way

**Other relevant information:**
webpack version: 4.42.1
Node.js version: 14.2.0
Operating System: Windows 10
Additional tools: none, cmd + notepad

**Comment by sokra** [comment]
The package.json could contain aliasing information like the `browser` field, which allows to redirect path. It's needed and it must be valid.

**Comment by pieczorx** [comment]
I don't think anyone would like to put `browser` field into `package.json` if it's invalid. I've spent a few days on figuring out what's wrong (doing everything the right way) and in this context `package.json` should be just omitted like it doesn't exist at all.

Is there any reason behind why it should be required?

**Comment by pieczorx** [comment]
Anyway I think it's a really, really rare usage like mine, because 99% of the developers will have valid package.json. However it's a big problem for me, because I can't know if users of my package will have valid package.json. (It can be installed globally, and it just runs webpack in a directory and it has everything installed inside its own package.json).

Of course I can check on my own if package.json syntax is valid, however it won't allow people to run their package if this single file is broken.

I don't see any reason to tell them: "Hi, please fix package.json" 🧛

**Comment by sokra** [comment]
You could put a package.json in folder C. Maybe even a virtual one.

Or you can disable package.json resolving, but this would also break other features of a package.json.

**Comment by evilebottnawi** [comment]
Answers above.

> I don't see any reason to tell them: "Hi, please fix package.json" vampire

You should tell your users that they have broken `package.json`.

`package.json` contains a lot of information, for example without this information, we can get code for `node`, not for `browser`, so you will have a problems
