### ISSUE TITLE
TS type for Entry error

### ISSUE THREAD

**Issue by ebuchmann** [webpack/webpack#11063]
# Bug report

**What is the current behavior?**

Typing error with the following:

```
import { Configuration } from 'webpack';

const configuration = (): Configuration => {
  const webpackConfig = {
    mode: 'development' as const,
    entry: ['webpack-hot-middleware/client', path.join(__dirname, '..', 'client', 'index.jsx')],
    plugins: [
      new HtmlWebPackPlugin({
        title: config.pageTitle,
        template: path.join(__dirname, '..', 'client', 'index.html'),
        filename: path.join(__dirname, '..', 'client', 'index.html'),
      }),
      new webpack.HotModuleReplacementPlugin(),
    ],
    output: {
      filename: '[name].bundle.js',
      path: path.resolve(__dirname, '..', 'client'),
      publicPath: config.basePath,
    },
  };

  return webpackConfig;
};
```

```
  Types of property 'entry' are incompatible.
    Type 'string[]' is not assignable to type 'string | (() => string | EntryObject | [string, ...string[]] | Promise<EntryStatic>) | EntryObject | [string, ...string[]] | undefined'.
      Property '0' is missing in type 'string[]' but required in type '[string, ...string[]]'.ts(2345)
```

The typing for Entry:

```
type Entry =
	| string
	| (() => string | EntryObject | [string, ...string[]] | Promise<EntryStatic>)
	| EntryObject
	| [string, ...string[]];
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

The code works fine, the typing shouldn't be throwing an error for something that is valid. It seems the last part of the typing should just be `string[]`, which works fine if I adjust it manually.

**Other relevant information:**
webpack version:  webpack 5 beta 18
Node.js version: 12
Operating System: macos
Additional tools: vscode

**Comment by sokra** [comment]
You could try that:

``` diff
-entry: ['webpack-hot-middleware/client', path.join(__dirname, '..', 'client', 'index.jsx')],
+entry: ['webpack-hot-middleware/client', path.join(__dirname, '..', 'client', 'index.jsx')] as const,
```

**Comment by evilebottnawi** [comment]
Answer above

**Comment by ebuchmann** [comment]
I did try that, didn't work. For now I just have to @ts-ignore the line because it doesn't like the typing of [string, ...string[]].

**Comment by mitchell-frost** [comment]
Can I work on this issue?

**Comment by evilebottnawi** [comment]
Yes, PR welcome

**Comment by mitchell-frost** [comment]
How do I reproduce the bug and where are the changes supposed to be made?

**Comment by evilebottnawi** [comment]
Example above

**Comment by sokra** [comment]
We can workaround that problem omitting `minLength` from the Schema for generating type declarations

See webpack/tooling repo

**Comment by mitchell-frost** [comment]
I created a simple webpack project with the documentation here [https://webpack.js.org/guides/getting-started/](url) and copied and pasted the code above. I don't understand where the code for the type entry is supposed to be. i could not reproduce the bug with `npx webpack` or `npm run build` . Is there some other process involved in reproducing it?

**Comment by moltar** [comment]
Also having a similar issue.

I'm defining an entry in a variable:

```ts
const entry: Record<string, string[]> = {
  foo: ['bar', 'baz']
}
```

But when I supply this to configuration, get the following:

```
Type 'Record<string, string[]>' is not assignable to type 'Entry'.
  Type 'Record<string, string[]>' is not assignable to type 'string'.ts(2322)

types.d.ts(1790, 2): The expected type comes from property 'entry' which is declared here on type 'Configuration'
```

**Comment by evilebottnawi** [comment]
Fixed https://github.com/webpack/webpack/releases/tag/v5.3.1
