### ISSUE TITLE
bug: option stats is not compiling value true correctly

### ISSUE THREAD

**Issue by snitin315** [webpack/webpack#11072]
# Bug report
`stats: true` is actually doing nothing 

**What is the current behavior?**
for `stats: true` in webpack config, `compiler.options.stats = {}`. where as for `stats: false` it's correct `compiter.options.stats = { preset: 'none'}`

### for `stats: true` - 
![Screenshot at 2020-06-22 18-09-37](https://user-images.githubusercontent.com/46647141/85288583-96c72280-b4b3-11ea-9089-ba2878aca50a.png)

### for `stats: false`
![Screenshot at 2020-06-22 18-09-09](https://user-images.githubusercontent.com/46647141/85288597-9dee3080-b4b3-11ea-9f25-cd316f1736a6.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
set `stats: true` in webpack config and then check the value of `stats` in the `compiler.options`

**What is the expected behavior?**
`stats: true` should set `compiler.options.stats : {preset : 'normal'}`.

**Other relevant information:**
webpack version: 5
Node.js version: 12.16.2

**Comment by snitin315** [comment]
I see preset `normal` is also missing here, https://github.com/webpack/webpack/blob/8aaff95a1bc7320914b26ac1cead96b18f59f9e2/lib/stats/DefaultStatsPresetPlugin.js#L21-L91

**Comment by evilebottnawi** [comment]
Good catch, let's fix it, should be easy

**Comment by sokra** [comment]
Seems correct to me.

An empty object `{}` results in all properties using the default value. So is uses the "normal" stats. There is no "normal" preset.

**Comment by snitin315** [comment]
> An empty object {} results in all properties using the default value. So is uses the "normal" stats

@sokra This makes sense, I was confused because it is showing preset `normal` for `stats: 'normal'`
 
![Screenshot at 2020-06-24 13-15-16](https://user-images.githubusercontent.com/46647141/85517668-1a505300-b61d-11ea-95cc-6c39451dab7c.png)

**Comment by evilebottnawi** [comment]
@sokra it is hard for plugins/external tools, to detect alias, why do not create alias `stats: true` === `stats: 'normal', `stats: false` - `stats: 'none'`?

**Comment by sokra** [comment]
> @sokra it is hard for plugins/external tools, to detect alias, why do not create alias `stats: true` === `stats: 'normal', `stats: false`-`stats: 'none'`?

I'm fine with that, send a PR.

So there is no bug here...

**Comment by snitin315** [comment]
yep, not a bug we are returning `{}` for `stats === true`, we can `return { preset: 'normal'}` instead to avoid confusion and make it clear like done for `stats === false`. 

https://github.com/webpack/webpack/blob/80b76711f97b7a474a38ce6d7a643eb1e5398273/lib/config/normalization.js#L282-L298
