### ISSUE TITLE
Module sharing supporting semver ranges including prereleases

### ISSUE THREAD

**Issue by jasongrout** [webpack/webpack#11073]
## Feature request

**What is the expected behavior?**

Currently, constraints on consuming shared modules lets you specify a range of required versions you can accept. The webpack custom parsing of semver ranges does not handle many forms of semver range syntax, such as `1.2.*` or `1.x`, and does not correctly handle versions with first component 0, like `^0.2.3`, even though the underlying capability of the sharing system can handle these range concepts.

Also, the representation of version ranges does not allow for the semver range `||` operator.

Finally, the sharing system does not handle prerelease versions (it can't parse them, and doesn't have a good way to represent prereleases).

**What is motivation or use case for adding/changing the behavior?**

For flexibility, webpack should be able to handle semver range syntax for the supported features of semver ranges.

In order to support a wider range of common scenarios, the required version ranges should support `||`. For example, this comes up if a consumed shared library has a breaking change somewhere in it's API, necessitating a major version bump from `1.2.3` to `2.0.0` across the entire package, but if a consumer does not use that part of the api, it can (and should) happily consume `^1.2.3 || ^2.0.0` for maximum flexibility.

As for prerelases, when a system is built on top of sharing modules, it is useful to be able to publish prerelease versions of shared packages for consumers to test. In order to do that, consumers need to be able to specify prerelease versions of shared modules.

In practice, I think the two relevant scenarios to cover with prereleases is locking to a specific prerelease, and including all prereleases up through some version bump, e.g., `>=1.2.3-alpha.0 <1.2.4-0` or `>=1.2.3-alpha.0 <1.3.0-0`. Locking to a specific prerelease is more 'correct', in that there could be breaking changes between prereleases, though in practice it's often more convenient, especially when you get to rc prereleases, to do something like `>=1.2.3-rc.1 <=1.2.3` or `~1.2.3-rc.1` (which includes 1.2.4, 1.2.5, etc.) to cover all release candidates.

**How should this be implemented in your opinion?**

*Note: these ideas are still work-in-progress as I explore the sharing system more deeply. I'm happy to have a discussion here, or elsewhere if it's more appropriate, before pushing forward with things.*

To better parse semver range syntax, we can use the npm semver library when bundling js (note: not when running the bundle). Some explorations with this are at https://github.com/jupyterlab/jupyterlab/pull/8385#issuecomment-646995548.

To support `||`, there are also some thoughts at https://github.com/jupyterlab/jupyterlab/pull/8385#issuecomment-647653196 and other places in that discussion.

To support prerelease versions, I think the way of representing required versions should change. Some more background is at https://github.com/jupyterlab/jupyterlab/pull/8385#issuecomment-647711412, but in short, I think it might be sufficient to represent a required version range as a list of version components preceded by the number of components that are fixed. 

For example, the existing `['1', '2', 3]` would be instead `[2, 1, 2, 3]`, indicating that the 1, and 2 are fixed, and the range is `1.2.*`, i.e., `>=1.2.3 <1.3.0-0`. This then extends to prerelease versions, so `[5, 1, 2, 3, 'alpha', 0]` means `1.2.3-alpha.0`, but `[3, 1, 2, 3, 'alpha', 0]` means `>=1.2.3-alpha.0 <=1.2.3` (i.e., up to and including the release) and `[2, 1, 2, 3, 'alpha', 0]` means `~1.2.3-alpha.0`.

Note that `[4, 1, 2, 3, 'alpha', 0]` indicates the range of all alphas, which is not so easy to express in semver, since semver doesn't have notation like `1.2.3-alpha.*`.

Also note that we would need to have logic around matching prereleases (see https://docs.npmjs.com/misc/semver#prerelease-tags). For example, `['1', '2', 3]` should *not* include version `1.2.4-alpha.0`. In order to have a prerelease satisfy a range, the first three components *must* match. Also we need to be careful about how prerelease sorting works: see section 11 of https://semver.org/

**Are you willing to work on this yourself?**
yes

**Comment by sokra** [comment]
Yeah, version parsing and handling is something that need improvement. I only handled the "common" cases for now.

**Comment by jasongrout** [comment]
Thanks. Can we work with you to get it in better shape for 5.0 to handle our usecases?

**Comment by jasongrout** [comment]
> Thanks. Can we work with you to get it in better shape for 5.0 to handle our usecases?

In other words, are you open to reviewing and merging PRs that add these things?

**Comment by evilebottnawi** [comment]
@jasongrout Yep

**Comment by sokra** [comment]
@jasongrout I'll implement it for you...

**Comment by jasongrout** [comment]
> @jasongrout I'll implement it for you...

Thanks!

I've been experimenting a lot with how webpack might accommodate these needs, so I'd love to talk over the technical details if you want. For example, I think slight modifications to how versions are stored in the store can accommodate the usecases of pinning to a specific prerelease version, but supporting a prerelease range (i.e., all prereleases up through the release) would be much more difficult.

I've also tracked down a few bugs in the current implementation.

**Comment by evilebottnawi** [comment]
@jasongrout 

> I've also tracked down a few bugs in the current implementation.

Can you provide, for future tests?

**Comment by jasongrout** [comment]
> Can you provide, for future tests?

Sure, of course.

For example, one I saw this morning was in https://github.com/webpack/webpack/blob/ffcae03680ae174ade4b325637cb5edf7b6e1603/lib/sharing/ShareRuntimeModule.js#L77 - it uses the variable `v` which is not in scope for this function.

**Comment by sokra** [comment]
So it was a bit more involved but I'm done: https://github.com/webpack/webpack/pull/11105

This adds full SemVer support for any kind of range and complex versions like `1.2.3-beta.42+123.456`. Afaik it should behave equal to the semver specification including edge cases like prereleases doesn't match normal ranges, prereleases are smaller than the final release, etc.

**Comment by jasongrout** [comment]
Thanks. You beat me to it (#11103). I've learned a lot doing my PR, though, so I can give better comments on yours!

**Comment by sokra** [comment]
Fixed
