### ISSUE TITLE
v5 module dep invalidation not working in cases that do in v4

### ISSUE THREAD

**Issue by jquense** [webpack/webpack#11074]
👋  I wasn't sure the right format for this observation/bug report/question so gonna drop it here.

I'm the maintainer of [`astroturf`](https://github.com/4Catalyzer/astroturf) a library that extracts inline css strings into separate files during compilation. Current (v4 and previous) we do this with a hacky but useful approach of not actually writing files to disk, instead tweaking the webpack FS object in a mixed in memory/real-fs approach. The plugin is here: https://github.com/4Catalyzer/astroturf/blob/master/src/VirtualModulePlugin.js 

Please 🙏  excuse the terrible cache busting, which allows the sibling loader to bootstrap the plugin mid compilation. I know that's terrible and can confirm that this issue still persists when the plugin is added manually via config before compilation starts.

The paired loader adds extracted files as dependencies of the processed file, so: 

**button.js**
```
const styles = css`
  color: blue;
`
```

Produces `button-styles.css` and `addDependency` is called with the new file (added to the in memory fs). NOW in v4, when `button.js` changes it also invalidates `button.css` and both rebuild (which is desired). HOWEVER in v5 `button.css` never invalidates when `button.js` changes.

I know that this probably isn't going to work smoothly as is, given that that one must process `button.js` _before_ knowing if `button.css` has changed, but the v4 behavior of just always invalidating the dependent CSS files works fine for that, even if it's a bit inefficient. 

I'm wondering if this difference in behavior is expected, or even known, and if there is any place I should start looking to try and make this work in v5? I've already seen `fileTimestamps` have changed in v5 and have attempted to migrate to something similar, but it seems to work _too_ well given the CSS files aren't being rebuilt. Maybe i need to manually invalidate these style files when a parent changes?

(If it helps this is the unfinished and non functional spike i've been working on for v5 support https://github.com/4Catalyzer/astroturf/blob/webpack5/src/VirtualModulePlugin.ts)

**Comment by sokra** [comment]
In general virtual modules is not the way to go in webpack. If you need to transform a file in any way use a loader. Extracting a snippet from a file is also a way for transforming a file. You can also use a loader without an input file if you like to generate files out of the void (maybe from passed options).

So your loader workflow could be as following:

``` js
// button.js
const styles = css`
  color: blue;
`
```

Loader transformation to:

``` js
// button.js
const styles = require("./button.js.css!=!your-base64-unpack-loader?Y29sb3I6IGJsdWU7!");
```

`./button.js.css!=!` gives the resulting module a name and allows to apply `test: /\.css$/` rules to them.

---

In webpack 5 you could even use data urls directly:

``` js
// button.js
const styles = require("data:text/css;base64,Y29sb3I6IGJsdWU7!");
```

and match rules to them:

``` js
module.rules: [
{
  mimetype: "text/css",
  use: ["style-loader", "css-loader"]
}
]
```

But note that relative urls in data uris are relative to the `this.rootContext` in the loader, so you might have to change references.

---

Otherwise the "old" approach above allows to let relative stuff works as expected by adding a resource file:

``` js
// button.js
const styles = require("./button.js.css!=!your-base64-unpack-loader?Y29sb3I6IGJsdWU7!./button.js");
```

**Comment by jquense** [comment]
> You can also use a loader without an input file if you like to generate files out of the void (maybe from passed options).

O wow, That was my first attempt at this but couldn't figure out a way to do it. is the `!=!` notation here special or an extension of the other inline loader syntax?

**follow up question**: would this approach suffer from the same invalidation waterfall issue? Changing `button.js` would trigger a new b64 hash on the require which would have to trigger another compilation?

**Comment by sokra** [comment]
It's a special inline syntax (that should only be used by loaders).

No this would build in a single compilation

**Comment by jquense** [comment]
Made a quick attempt to use this method and rean into a bad interaction with another hacky loader pattern specifically: https://github.com/webpack/webpack/issues/10350

`button.css!=!some-loader!b64-decode?content=asfsa!`

where `some-loader` pitches and returns `export { default } from '-!css-loader!some-loader!b64-decode?content=asfsa!'`

I may just be doing it wrong, but i get CSS syntax errors on the content of this passthrough loader, as if webpack passed the new content to the existing `.css` loader chain. Will investigate more.

**Comment by sokra** [comment]
> `button.css!=!some-loader!b64-decode?content=asfsa!`

This should be interpreted like
The result of `some-loader!b64-decode?content=asfsa!` is processed like it it was written in a file named `button.css`.
So the result should be CSS as you would write CSS in a .css file. All loaders and other rules from the config that would match a button.css file are used on the result.

**Comment by jquense** [comment]
> So the result should be CSS as you would write CSS in a .css file.

That makes sense tho the same case with an actual css file you can return JS from `.pitch` and it works fine, which is different than this case. where the the result of `pitch` doesn't short-circuit the current chain

**Comment by jquense** [comment]
> the result of pitch doesn't short-circuit the current chain

@sokra any chance you get, can you confirm if the difference in pitch behavior is intended here and if it can be worked around?

This approach won't work if the inline `!=!` if the pitch phase doesn't behave the same way as a loader specified the normal way

**Comment by sokra** [comment]
I would say that's intended. You can short-circur the chain, but you still have to return CSS.

It looks like you just want to replace your loader with `css-loader!some-loader`. In the pitch phase you can modify the loader chain and insert/remove loaders. So for the above case you may want to insert `css-loader` and `some-loader` after your loader.
Not sure exactly what you want to do. Usually loaders should be independent and the user should be able to combine them as wished...

**Comment by jquense** [comment]
> I would say that's intended. You can short-circur the chain, but you still have to return CSS.

Just to be clear, that is very different from how pitching works normally it seems. It means that you can't short circuit meaningfully because you cannot change or skip configured loaders in the pitch phase.

Example:
```js
// "css-loader!my-loader!button.css"
...
my-loader.pitch = (src) => {
 return 'module.exports = 'skip everything'
}
```
This works fine, it's expected you have to return JS here because the early return means no more loaders are run right?

```js
//button.css!=!css-loader!my-loader!?content="css"! 
...
my-loader.pitch = (src) => {
 return 'module.exports = 'skip everything'
}
```
This does not compile ☝️  because `'module.exports = 'skip everything'` is passed to css-loader

**Comment by evilebottnawi** [comment]
@jquense problem still exists? I can help with this

**Comment by jquense** [comment]
@evilebottnawi ya my last question is the latest and still pending if you get a chance to look at it. Thanks!

**Comment by jquense** [comment]
@evilebottnawi if you have a chance would love some help. Let me know if I can share more.

**Comment by evilebottnawi** [comment]
@jquense Can you link on place where you have a problem(s)?

**Comment by jquense** [comment]
@evilebottnawi ya definitely. Here is a running isolated reproduction of the behavior i'm seeing. 

https://github.com/jquense/webpack-pitch-repro/blob/master/src/index.js

`string-loader`: returns `module.exports = 'string'` during pitch.
`log-loader`: confirms the new source is JS

the first import in `index.js` works, the result in the bundle is `module.exports = "hi"`, the second import using the `!=!` syntax does not work. It doesn't work because `css-loader` tries to process the new JS. 

Note that the docs for Pitching loaders say:
> Second, if a loader delivers a result in the pitch method, the process turns around and skips the remaining loaders. In our example above, if the b-loaders pitch method returned something:

That is true for the first example, and false for the second

**Comment by evilebottnawi** [comment]
@jquense As I understand you want to disable `css-loader, right?

/cc @sokra need you attention,

**Comment by jquense** [comment]
Technically it should disable any remaining loader. Maybe I can do it manually

**Comment by evilebottnawi** [comment]
@jquense Yes, I think it is bug with `!=!` syntax

**Comment by evilebottnawi** [comment]
Let's fix it in webpack@5

**Comment by jquense** [comment]
happy to contribute if someone could point me in the right direction :)

**Comment by evilebottnawi** [comment]
https://github.com/webpack/webpack/blob/master/lib/NormalModuleFactory.js#L66
https://github.com/webpack/webpack/blob/master/lib/NormalModuleFactory.js#L396

Feel free to feedback

**Comment by jquense** [comment]
Ok @evilebottnawi here is the logic that forks the behavior: https://github.com/webpack/webpack/blob/master/lib/NormalModuleFactory.js#L452 

What's happening is that `!=!` modules add inline loaders **after** configured loaders, which is the opposite from normal files, where inline loaders run first. So the pitching behavior is working but the loader order is different. 

I don't know why this works this way but i assume there is a good reason. I don't know what the right "fix" is aside from adding more syntax like `!=!!` or something. thoughts?

**Comment by jquense** [comment]
(also i wonder if the matchResource should added to the loader context somewhere?)

**Comment by jquense** [comment]
taking a step back there are maybe a larger reason this isn't a great alternative to virtual modules. In the context of a loader there is no resourcePath using this syntax and most loaders tend to assume resource path exists.

**Comment by jquense** [comment]
ok I feel pretty stuck here.

The core issue is this problem: 

> [...loader] Produces button-styles.css and addDependency is called with the new file (added to the in memory fs). In v4, when button.js changes it also invalidates button.css and both rebuild (which is desired). HOWEVER in v5 button.css never invalidates when button.js changes.

Regardless of matchResource, or virtual files. I think the problem is the same, **how do I invalidate a file dependency from a loader such that it is rebuilt**?

It does seems like the matchResource approach avoids the invalidation problem but I don't think it's viable because `resourcePath` is empty for those modules, and almost every loader requires `resourcePath`, e.g. css-loader will error out on one of these. Adding resourcePath manually seems to trigger resolver action somewhere which fails

**Comment by evilebottnawi** [comment]
> how do I invalidate a file dependency from a loader such that it is rebuilt?

just add it to file dependencies, or do you need invalidate it from loader? How you know when it should be invalided?

**Comment by jquense** [comment]
> , or do you need invalidate it from loader

yes, a loader produces and updates the file. the example is a loader removes as string JS file and saves it to a file that is required by the JS file. So `Foo.js` runs it loaders and produces `Bar.js` but Bar.js isn't rebuilding when updated.

> How you know when it should be invalided

I can hash it or just always rebuild it

**Comment by evilebottnawi** [comment]
@jquense Can you provide link on this?

**Comment by jquense** [comment]
yeah sorry, working to try and make it as minimal as possible. 

here is my attempt: https://github.com/4Catalyzer/astroturf/blob/webpack5/src/VirtualModulePlugin.ts
here is a similar project: https://github.com/sysgears/webpack-virtual-modules

and here is an example of the behavior:  https://github.com/jquense/webpack-pitch-repro/tree/virtual-modules

I can confirm now that this is **just** an issue with the way virtual modules are implemented via both of us. I would love to switch off of it but the `!=!` is not viable right now. In the meantime the ask is to help figure out why these files aren't triggering rebuilds 🙏

**Comment by evilebottnawi** [comment]
@jquense yep, webpack was not designed for invalidation virtual modules, why do not use original paths for invalidation? In theory you can create temp files and write to them when you need to invalidate somehting, but it is very hacky

**Comment by jquense** [comment]
bug report in the plugin: https://github.com/sysgears/webpack-virtual-modules/issues/68

yeah I know it's not ideal, but this _was_ working in v4 albeit with hacks. Happy to do something else but I don't see another approach that works here

- writing to temp directories isn't viable, these files need to be able to contain relative imports to other things in the project. e.g. Scss files importing other scss files
- Writing files locally is bad since it adds generated files to source directories and the point is to not have these be separate files from the devs perspective

**Comment by evilebottnawi** [comment]
@jquense Do you want to use this plugin or achieve this without the plugin? I don't think it is possible on loader side, because the webpack doesn't even run loaders when you use cache

**Comment by jquense** [comment]
> Do you want to use this plugin or achieve this without the plugin

Open to all possibilities, i just want it to be low/no config for a user

> because the webpack doesn't even run loaders when you use cache

It must re-run loaders if the file source changes no?

**Comment by evilebottnawi** [comment]
> It must re-run loaders if the file source changes no?

yes, only when it was tracker in deps and changed

**Comment by jquense** [comment]
o i see, I forgot to add it as a dependency in the example. let me see if that helps

**Comment by non25** [comment]
@sokra Thanks for the example: https://github.com/webpack/webpack/issues/11074#issuecomment-648658214

I tried two approaches, passing a base64'd css string from Svelte SFCs, and passing a key to a Map css storage for the second loader run, removing that pair on reading and passing it further to the `.css` pipeline.
Personally, I like passing a key to a Map much better, it doesn't pollute webpack's console with base64s in queries and invalidates css the same way when component changes.

https://github.com/sveltejs/svelte-loader/compare/master...non25:emitcss-inline
https://github.com/sveltejs/svelte-loader/compare/master...non25:emitcss-to-map

Is there any other way to pass the data through custom loader string aside from this two ?

@jquense Do any approach listed above work for you ?

**Comment by jquense** [comment]
@non25 i've not gotten other approach to work for passing data, the problem with the `Map` approach is that it may not play nicely with thread-loader, and both run into issues with `cache-loader` where the it expects files to exist somewhere.

I eventually gafve up on this approach because of: 

> [...] I don't think it's viable because resourcePath is empty for those modules, and almost every loader requires resourcePath, e.g. css-loader will error out on one of these. Adding resourcePath manually seems to trigger resolver action somewhere which fails

**Comment by alexander-akait** [comment]
@jquense `cache-loader` was deprecated in favor built-in cache

**Comment by jquense** [comment]
@alexander-akait 👋  I am back trying to make this work. I am 90% of the way there with the `!=!` syntax but there are problems that seem unsolvable without changes to webpack or css-loader. 

To recap, `resourcePath` is empty naturally unless you add one like @non25 did in svelte loader to the end. the **big** problem with that approach tho is you **must** use a resource that exists and is resolvable. Svelte loader is using the "parent" resource, and due that works for them due to how svelte handles preprocessing. It *does not* work if you need to pair the virtual CSS file with css-loader's CSS module support. 

Assuming this request:

    Button.module.css!=!my-loader?css=[b4data]!./Button.js

Problems/Concerns: 
 - css-loader module `'auto'` behavior doesn't work, the file extension of `resourcePath` is `.js`
 - There are a few bugs in css-loader that concat `!=!` incorrectly (easily fixable)

I'm not sure how to address the first one

**Comment by alexander-akait** [comment]
@jquense 

> There are a few bugs in css-loader that concat !=! incorrectly (easily fixable)

Let's start to fix it? Can you send a PR or open an issue to investigate it?

**Comment by jquense** [comment]
already working on it! Do you have an idea for dealing with the first problem?

**Comment by alexander-akait** [comment]
> css-loader module 'auto' behavior doesn't work, the file extension of resourcePath is .js

hm, it should work, I need to look at this, maybe bug

**Comment by alexander-akait** [comment]
@jquense All problems are solved, something else?

**Comment by jquense** [comment]
it should be solved, I'm running into some issue with `matchResource` being `undefined` when it shouldn't be. Seems like at some point webpack creates a new NormalModule with the fully resolved request (which doesn't include the matchResource) I'm trying to figure out why that's happening and why the behavior is different than in your tests

**Comment by alexander-akait** [comment]
`matchResource` can be empty when it is not defined in `request`, so you need check `if (matchResource) { // You logic }`

**Comment by jquense** [comment]
the problem is requests like `./button.module.css!=!my-loader!./Button.js?foo` are getting to `css-loader` with `matchResource` undefined, when it should be defined. trying to simplify the case to figure out why

**Comment by alexander-akait** [comment]
Yes, please provide simple example and I will look

**Comment by sokra** [comment]
Why and where are you reading `matchResource`? You shouldn't not read that in a loader.

**Comment by alexander-akait** [comment]
@sokra Example:
```
import styles2 from "./button.module.css!=!./base64-loader?LmZvbyB7IGNvbG9yOiByZWQ7IH0=!./other.js";
```

in `css-loader` we have logic to apply CSS modules if the `resourcePath` option have `/\.module\./`, but in this case we can't detect it because `other.js` doesn't have `/\.modules\./`, we can't control file names because developers name them and it is bad for DX ask to set `modules: true` in `webpack.config.js`

**Comment by jquense** [comment]
I think more of an issue than `modules: true`, without looking at matchResource you can't actually hash the class names correctly and get collisions

**Comment by jquense** [comment]
still unsolved thanks!

**Comment by sokra** [comment]
Maybe you could quickly summarize whats the remaining issue? Too many comments in the issue...

**Comment by wesleybl** [comment]
> it should be solved, I'm running into some issue with matchResource being undefined when it shouldn't be. Seems like at some point webpack creates a new NormalModule with the fully resolved request (which doesn't include the matchResource) I'm trying to figure out why that's happening and why the behavior is different than in your tests

@jquense @alexander-akait we have an app where pages are generated both on the server and on the client:

https://github.com/plone/volto

We are having a problem, when using CSS modules with webpack 5. The css-loader is generating a hash for the CSS class name when it compiles the client and another one when it compiles the client. This difference is precisely due to the filling or not of the `matchResource` variable. See comment:

https://github.com/plone/volto/issues/5019#issuecomment-1653679324

I don't know what could be causing this variable to be filled or not. Do you know what could be causing this?
