### ISSUE TITLE
Webpack 5: Empty JS chunks are emitted for CSS entries

### ISSUE THREAD

**Issue by slightlyfaulty** [webpack/webpack#11088]
# Bug report

**What is the current behavior?**

Empty JS files are emitted for CSS entries in Webpack 5 even when `optimization.removeEmptyChunks` is `true`.

**If the current behavior is a bug, please provide the steps to reproduce.**

```js
const MiniCssExtractPlugin = require('mini-css-extract-plugin')

module.exports = {
	entry: './style.css',
	optimization: {
		removeEmptyChunks: true,
	},
	plugins: [
		new MiniCssExtractPlugin(),
	],
	module: {
		rules: [
			{
				test: /\.css$/,
				use: [MiniCssExtractPlugin.loader, 'css-loader'],
			},
		],
	},
}
```
Output:
```sh
   Asset      Size
main.css  25 bytes  [emitted]  [name: main]
 main.js   0 bytes  [emitted]  [name: main]
```

**What is the expected behavior?**

Since the `main.js` file is empty, it should be removed when `optimization.removeEmptyChunks` is `true`.

**Other relevant information:**
webpack version:  5.0.0-beta.18
Node.js version: 14.3.0
Operating System: Manjaro Linux
Additional tools: N/A

**Comment by evilebottnawi** [comment]
It is not supported yep

**Comment by slightlyfaulty** [comment]
If this needs to be implemented in every plugin like `mini-css-extract-plugin` then we can close this. It just seems like one could expect `optimization.removeEmptyChunks` to, well, remove empty chunks...

**Comment by evilebottnawi** [comment]
@slightlyfaulty it should be fixed on webpack side

**Comment by sokra** [comment]
Webpack 5 would not emit chunks without modules. I think in this case there is a js module in the chunk which is empty and the output file gets empty after minimizing.

Once we upgrade the mini css extract plugin to webpack 5 we can do a lot improvements, like getting rid of these empty js modules.

**Comment by slightlyfaulty** [comment]
> I think in this case there is a js module in the chunk which is empty and the output file gets empty after minimizing.

I imagine the js module that Webpack sees is the CSS file. But even in `development` mode and `devtool` false, the resulting JS file looks like this:

```js
/******/ (() => { // webpackBootstrap
/******/ 	/************************************************************************/
/*!*******************!*\
  !*** ./style.css ***!
  \*******************/
/*! unknown exports (runtime-defined) */
/*! exports [maybe provided (runtime-defined)] [unused] */
/*! runtime requirements:  */
// extracted by mini-css-extract-plugin
/******/ })()
;
```

It's all good and well to let the plugin handle this, but it would make things a lot simpler for everyone if `optimization.removeEmptyChunks` could be extended to never output "empty" JS files like this, in any case. That way all other plugins can automatically benefit by not needing to handle this separately in their own ways.

Not having this has resulted in several plugins all just attempting to do this one thing. And none of them seem to work with Webpack 5.

- [webpack-fix-style-only-entries](https://www.npmjs.com/package/webpack-fix-style-only-entries)
- [webpack-extraneous-file-cleanup-plugin](https://www.npmjs.com/package/webpack-extraneous-file-cleanup-plugin)
- [webpack-remove-empty-js-chunks-plugin](https://www.npmjs.com/package/webpack-remove-empty-js-chunks-plugin)
- [webpack-delete-no-js-entries-plugin](https://www.npmjs.com/package/webpack-delete-no-js-entries-plugin)

But this doesn't just affect mini-css-extract-plugin. It also affects [extract-css-chunks-webpack-plugin](https://www.npmjs.com/package/extract-css-chunks-webpack-plugin) for example, and I imagine at least a few more plugins that extract different types of assets or do anything else that results in an empty JS file.

**Comment by vankop** [comment]
@slightlyfaulty 

Could you try
webpack.config.js
```
const MiniCssExtractPlugin = require('mini-css-extract-plugin')

module.exports = {
	entry: './style.css',
	optimization: {
		removeEmptyChunks: true,
	},
	plugins: [
		new MiniCssExtractPlugin(),
    ],
    module: {
        rules: [
            {
                test: /\.css$/,
                use: [{loader: MiniCssExtractPlugin.loader, options: {esModule: true}}, 'css-loader'],
            },
        ],
    },
}
```
package.json
```
{
    "dependencies": {
           "mini-css-extract-plugin": "webpack-contrib/mini-css-extract-plugin"
    }
}
```
I think master fixes your problem

**Comment by vankop** [comment]
@evilebottnawi @sokra I think we should make `options.esModule = true` to improve DX

**Comment by slightlyfaulty** [comment]
Hmm doesn't seem to make a difference on my end @vankop. I cloned/built `mini-css-extract-plugin` master and added the `esModule` option. Using the latest webpack 5.0.0-beta.20. But an empty `main.js` is still emitted.

**Comment by vankop** [comment]
@slightlyfaulty Ah I see what you trying to achieve.. This is not possible right now..

**Comment by evilebottnawi** [comment]
@vankop yep, It will be true when we prepare css-loader@4, already WIP

**Comment by evilebottnawi** [comment]
Let's close in favor https://github.com/webpack/webpack/issues/7300, already reported, should work with webpack@5 and latest version of `mcep`, but need tests, I will do it in the near future

**Comment by marcofugaro** [comment]
Still happening for me today, what's the fix?

**Comment by patrickkahl** [comment]
I managed to get it to work with this plugin: https://github.com/webdiscus/webpack-remove-empty-scripts

**Comment by ShaneMuir** [comment]
@kahl-dev I can't get that to work, it only gives examples in html webpack plugin and pub? Could you share your setup if you aren't using them setups

**Comment by kahl-dev** [comment]
I became some messages how the solution would look like, so here it is: https://github.com/kahl-dev/demo-webpack
