### ISSUE TITLE
Webpack 4 + bootstrap [TypeError: Cannot read property 'jquery' of undefined]

### ISSUE THREAD

**Issue by ASharma-5562** [webpack/webpack#11082]
I have recently started working with webpack ,while running my app with webpack I am getting below mentioned error:

var version = $.fn.jquery.split(' ')[0].split('.');                       ^

TypeError: Cannot read property 'jquery' of undefined
    at Object.jQueryDetection 

I am using expose-loader for the same.

My webpack File:

const path = require('path');
const nodeExternals = require('webpack-node-externals');
var webpack = require('webpack');

module.exports = {
  entry: './server/index.js',

  target: 'node',

  externals: [nodeExternals()],

  output: {
    path: path.resolve('server-build'),
    filename: 'index.js'
  },
  resolve: {
    extensions: ['.js', '.json', '.ts', '.tsx']
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        use: 'babel-loader'
      },
      {
        test: /\.tsx?$/,
        use: 'ts-loader',
        exclude: /node_modules/,
      },
      {
        test: /\.css$/,
        use: [
          {
            loader: 'css-loader'
          }
        ]
      },
      {
        test: /\.(png|jpe?g|gif)$/i,
        use: [
          {
            loader: 'file-loader',
          },
        ],
      },
      {
        test: require.resolve('jquery'),
        loader: 'expose-loader',
        options: {
          exposes: ['$', 'jQuery'],
        },
      },
    ]
  },
  plugins: [
    new webpack.ProvidePlugin({
      $: 'jquery',
      jQuery: 'jquery'
    })
  ]
};

Please assist with this particular scenario,

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
