### ISSUE TITLE
Wrong relative path when using `externals`

### ISSUE THREAD

**Issue by malash** [webpack/webpack#11083]
# Bug report

**What is the current behavior?**

There are two source files:

`src/index.js`:
```js
require("./the/deep/path");
```

`src/the/deep/path/index.js`:
```js
const _add = require("../../../../node_modules/lodash/add");
console.log("1+2 is", _add(1, 2));
```

And the `webpack.config.js` is:

```js
module.exports = {
	mode: "development",
	target: "node",
	devtool: false,
	output: {
		filename: "index.js",
	},
	externals: [
		(context, request, callback) => {
			if (request.includes("node_modules")) {
				callback(null, `commonjs ${request}`);
				return;
			}
			callback();
		},
	],
};
```

I expect `"../../../../node_modules/lodash/add"` was reguard as an external dependency and the output `dist/index.js` should be:

```js
const _add = require("../node_modules/lodash/add");
console.log("1+2 is", _add(1, 2));
```

But in fact, the path is still `require("../../../../node_modules/lodash/add")` and it's wrong.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Clone https://github.com/malash/webpack-issue-11083
2. Checkout `webpack-4` or `webpack-5` branch for different versions of Webpack.

3. Run `npm install`

4. Run `npm start`

5. Run `node src` and it works

6. Run `node dist` and you will see `node dist` failed.

![image](https://user-images.githubusercontent.com/1812118/85563786-47722500-b660-11ea-876c-4504d87522c8.png)

**What is the expected behavior?**

In the above case, I expect the `node dist` should work as well as `node src`.

There are several ways to reproduce this issue in production code.

1. Use relative path in `externals`

2. Use Node global variables in the web target. For example, the `process` is compiled to `./../path/to/node_modules/process` and cause this bug.

**Other relevant information:**
webpack version:  4.43.0 and 5.0.0-beta.18
Node.js version: 12.18.1
Operating System: macOS 10.15.5
Additional tools: None

**Comment by sokra** [comment]
That's outside of the scope of the externals feature. You would have to handle this in the function you provided for `externals`.

Why not using `const _add = require("lodash/add");`?

**Comment by malash** [comment]
@sokra Good question. But there are still several situations that result in this issue.

1. All relative paths go wrong not only `node_modules`.

2. If set `target` to `web`, `process` is transformed to `../../path/to/node_modules/process/browser.js` and it also trigger this bug.

I have no idea how to handle this issue in `externals` because there is no way to know the dist path, the `dist/index.js`, in the `externals` callback. 

Also if `splitChunks` was enabled, the code would be bundled in either main chunk or common chunk and it is harder to detect the dist path in `externals` callback.

**Comment by evilebottnawi** [comment]
> All relative paths go wrong not only node_modules.

It is expected for externals.

> If set target to web, process is transformed to ../../path/to/node_modules/process/browser.js and it also trigger this bug.

Shimming, webpack@5 doesn't do it.

What do you want to archive?
