### ISSUE TITLE
webpack 打包react 遇到jsx语法报错

### ISSUE THREAD

**Issue by TreeZhou** [webpack/webpack#11092]
![image](https://user-images.githubusercontent.com/32838069/85695702-e05d7a80-b70a-11ea-8527-164c3f71313f.png)

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
