### ISSUE TITLE
Webpack analyses dependencies tree before applying webpack.DefinePlugin variables and minimizing code

### ISSUE THREAD

**Issue by budarin** [webpack/webpack#11099]
# Bug report

**What is the current behavior?**
I have define a constant in my config 
```json
        new webpack.DefinePlugin({
            "__PROD__": true,
        }),
``` 
and use it in my code 

```js
if (!__PROD__) {
       const myObject = require('my-package');
       ....
}
```
when I run webpack - it tries to add `my-package` to resulting code while the code in the result is not included
If I use 

```js
if (false) {
       const myObject = require('my-package');
       ....
}
```
webpack doesn't include `my-package` in dependency

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

expected webpack to apply variable definition and code optimization and only than try to analyze dependencies 

**Other relevant information:**
webpack version:  4.43.0
Node.js version: 14.4.0
Operating System: any
Additional tools:

**Comment by evilebottnawi** [comment]
It is limitation, we don't know your runtime value, it can be any and changed in code

**Comment by evilebottnawi** [comment]
Prod build remove this module anyway

**Comment by sokra** [comment]
Actually that should work... Could you provide a repro?

**Comment by budarin** [comment]
I could not provide a repo but I see it on result file - it bigger in case of using __PROD__ and smolle when I use just false constant
it's real code:

```js
if (!__PROD__) {
    const serve = require('koa-static');
    app.use(serve('./dist'));
}
```
![image](https://user-images.githubusercontent.com/8055157/86108845-5a578000-bacc-11ea-86db-70b049289462.png)

```js
if (false) {
    const serve = require('koa-static');
    app.use(serve('./dist'));
}
```

![image](https://user-images.githubusercontent.com/8055157/86109108-af939180-bacc-11ea-9114-39f2d86c7730.png)

**Comment by evilebottnawi** [comment]
@budarin hm, maybe you can create minimum reproducible test repo? It is possible when `__PROD__` is `undefined`?

**Comment by budarin** [comment]
I'll try )14:28, 30 июня 2020 г., Evilebot Tnawi <notifications@github.com>:
@budarin hm, maybe you can create minimum reproducible test repo? It is possible when __PROD__ is undefined?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
С уважением Бударин Вадим

**Comment by budarin** [comment]
@evilebottnawi 
here is my cut [project](https://github.com/budarin/webpack-problem-demo) - please try to build it with `!__PROD__` and just `false`

**Comment by evilebottnawi** [comment]
No reproduced with pure JS, bug on `babel-loader` to `ts` side:
```
if (appHelpers_initApp(app),!false){
    const a=__webpack_require__("KNelC2SJ");
    
    app.use(a("./dist"))
}
```

code from bundle, so webpack can't drop module evalation

**Comment by evilebottnawi** [comment]
Sorry it is not minimum reproducible test repo, I have to spend a lot of time to find who exactly break it, you have a lot of plugins for webpack and babel and other stuff, it is not easy to detect how break it, but with pure webpack configuration without addoinal vendor plugins all works fine, if you want to find a problem, just disable plugins step by step

**Comment by budarin** [comment]
@evilebottnawi thanks!
I'll try to exclude plugins

**Comment by sokra** [comment]
Babel minify preset is the problem

**Comment by budarin** [comment]
@sokra thanks a lot!!!
I'll try to play with its  parameters

**Comment by evilebottnawi** [comment]
Please do not use `babel-minify`, it is very unstable and broken in many places, migrate on `terser`, I will close issue, we cannot fix anything here

**Comment by budarin** [comment]
@evilebottnawi  Thanks a lot!
