### ISSUE TITLE
how to code splitting and dynamic require

### ISSUE THREAD

**Issue by PaquitoSoft** [webpack/webpack#1109]
Hi there!

I'm really interested in using webpack for one of my projects where I'm working with require.js right now.

Currently I have this Single Page Application where I render the first page in the server and then there is client side navigation. I have a commons.js bundle where I put vendor code and all the common custom components written in-house, and I have a bundle for every page in my application.
When I move from one page to another (client-side navigation), I request this new page to the server. The info of this new page holds the name of the JS bundle I need to load for it. So my router component requires that bundle.

I've been reading the [code splitting](http://webpack.github.io/docs/code-splitting.html) docs this weekend and also checking the [demo app](https://github.com/webpack/example-app/) but I can't figure out the way I need to set this up.

This was my best shot:
```javascript
var path = require('path'),
	webpack = require('webpack'),
	CommonsChunkPlugin = require('webpack/lib/optimize/CommonsChunkPlugin');

module.exports = {
	context: process.cwd() + '/public',
	entry: {
		shared: ['jquery', 'dustjs', 'dustjs-helpers', 'pagejs', 'handlebars',
			'./js/main.js',
			'./js/controllers/mini-cart-controller.js',
			'./js/controllers/main-navigation-controller.js'],
		home: './js/controllers/home-controller',
		category: './js/controllers/category-controller',
		product: './js/controllers/product-detail-controller',
		shopCart: './js/controllers/shop-cart-controller'
	},
	
	output: {
		path: './public/js/dist',
		filename: "[name].entry.chunk.js"
	},

	resolve: {
		root: [
			path.resolve('public'),
			path.resolve('public/js'),
			path.resolve('public/vendor'),
		],
		modulesDirectories: [
			'vendor'
		],
		alias: {
			jquery: process.cwd() + '/public/vendor/jquery/dist/jquery.js',
			'dustjs-linkedin': process.cwd() + '/public/vendor/dustjs-linkedin/lib/dust.js',
			'dustjs-helpers': process.cwd() + '/public/vendor/dustjs-linkedin-helpers/lib/dust-helpers.js',
			pagejs: process.cwd() + '/public/vendor/page.js/page.js'
		}
	},

	module: {
		loaders: [
			{ test: /\.css$/, loader: 'style!css' }
		]
	},

	plugins: [
		new CommonsChunkPlugin({
			name: 'shared',
			filename: 'shared.js',
			minChunks: Infinity
		})
	]
};
```

I don't get how to use the require.ensure thing and how webpack can create the different bundles.

Could anybody help?
Thanks.

**Comment by shama** [comment]
What does the code where you're using `require.ensure` look like?

In your app's code, if you:

```js
require(['./a-script-loaded-async.js'], function (myAsyncScript) {
  console.log(myAsyncScript)
})
```

It will generate a separate chunk for the file `./a-script-loaded-async.js` and any of it's dependent modules.
