### ISSUE TITLE
Webpack splitchunksplugin different url.

### ISSUE THREAD

**Issue by novaknole** [webpack/webpack#11097]
I am using `splitChunksPlugin` In my **Project B**. After using it, I got 2 files..

`test1.js` and `test2.js`. It also seems like that `test2.js` is loaded in `test1.js` as lazy-loaded.

In my **Project A,** I use `axios` to fetch `test1.js`.  After clicking the button `test1.js` gets executed which should lazy-load `test2.js`. But `test1.js` seems to be loading the `test2.js` from Project A instead of Project B. 

Is there any way to make it load from Project B ?

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
