### ISSUE TITLE
Requiring CSS files

### ISSUE THREAD

**Issue by pherrymason** [webpack/webpack#111]
I'm doing something wrong when trying to require a css file in my app.

I've defined an alias in my `webpack.config.js` for that CSS file (select2.css):

``` javascript
module.exports = {
    // ...
    module :{
        loaders: [
            { test: /\.css$/, loader: "style!css" },
            { test: /\.png$/, loader: "file-loader" },
            { test: /\.gif$/, loader: "file-loader" },
            { test: /\.jpg$/, loader: "file-loader" }
        ]
    },
    resolve : {
        alias: {
            jquery      : __dirname + "/../../../js/vendor/jquery/jquery-1.10.2.js",
            underscore  : __dirname + "/../../../js/vendor/backbone/underscore.1.4.4.js",
           gmaps        : __dirname + "/../../../js/vendor/gmaps/gmaps.js",
           bootstrap    : __dirname + "/../../../js/vendor/bootstrap/bootstrap.3.js",
           select2      : __dirname + "/../../../js/vendor/select2-3.4.3/select2.js",
          'select2.css': __dirname + "/../../../js/vendor/select2-3.4.3/select2.css"
        }
    }
};
```

In my app, I'm requiring `'select2.css` like this:

``` javascript
    require('select2.css');
```

Then, I've installed `css-loader` and `style-loader` in my app folder with:
`npm install css-loader style-loader`

So now I have a `node_modules` folder with both modules installed in it next to my `app.js`.

When trying to build, node complains cannot resolve `file-loader` module, which I've installed but gave me these warnings:

```
npm WARN package.json css-loader@0.6.2 No repository field.
npm WARN package.json file-loader@0.5.0 No repository field.
npm WARN package.json style-loader@0.6.0 No repository field.
```

This is the complain about not being able to resolve `file-loader` module:

```
ERROR in ./~/css-loader!/Users/raulferras/dev/htdocs/eimagen/src/js/vendor/select2-3.4.3/select2.css
Module not found: Error: Cannot resolve module file-loader in /Users/raulferras/dev/htdocs/eimagen/src/js/vendor/select2-3.4.3.
 @ ./~/css-loader!/Users/raulferras/dev/htdocs/eimagen/src/js/vendor/select2-3.4.3/select2.css 2:2823-2847 2:5351-5375 2:5997-6021 2:6070-6094 2:6240-6264 2:6373-6397 2:6503-6527 2:16223-16247
```

**Comment by WaylonSong** [comment]
@sokra Whether require.resolve("file-loader") can carry parameters like this require.resolve("file-loader?name=[path][name].[ext]")
but it doesnt work, the erro message "Error: Cannot find module 'file-loader?name=[path][name].[ext]'
"
thx~

**Comment by jhnns** [comment]
@WaylonSong what would you expect to be returned by `require.resolve("file-loader?name=[path][name].[ext]")`?

Imo `require.resolve()` with loaders does not make sense

**Comment by WaylonSong** [comment]
@jhnns I didn't have a module env in the deploy directory, so I prefer to use require.resolve('file-loader'). But I also want the loader: "file?name=[path][name].[ext]"} taking such parameters, so I try  
{ test: /\.jpe?g$|\.gif$|\.png$|\.svg$|\.woff$|\.ttf$|\.wav$|\.mp3$/, require.resolve("file-loader?name=[path][name].[ext]"}
but doesn't work.
And I also try this
{ test: /\.jpe?g$|\.gif$|\.png$|\.svg$|\.woff$|\.ttf$|\.wav$|\.mp3$/, loader: "file-loader?name=[path][name].[ext]"}
resolveLoader: { 
        alias: { 
            "file-loader": require.resolve("file-loader") 
        } 
    }
doesn't work either.
Finally, I have to npm install the file loader in the deploy directory.

**Comment by jhnns** [comment]
Have you tried

```javascript
{ test: /.jpe?g$|.gif$|.png$|.svg$|.woff$|.ttf$|.wav$|.mp3$/,
loader: require.resolve("file-loader") + "?name=[path][name].[ext]"}
```

?

**Comment by WaylonSong** [comment]
@jhnns  yes， have tried, and id doesn't work.

npm install everywhere is ok, but I donnt know whether it is best practice.

**Comment by jhnns** [comment]
@WaylonSong Please, if you want help:

- Don't just throw in some code, use the code formatter feature of GitHub (using three backticks)
- Don't just answer "it doesn't work". Is there an error? Did it return an unexpected value?

Otherwise people won't take time to answer your questions

**Comment by WaylonSong** [comment]
@jhnns Ok，thank your for ur patience and instruction. I am just a rookie in Github, and I'll pay attention and summarize my answer.

Thank you so so much again~

**Comment by jhnns** [comment]
You're welcome :wink:
