### ISSUE TITLE
webpack splitchunksplugin lazy load 

### ISSUE THREAD

**Issue by novaknole** [webpack/webpack#11100]
**What is the current behavior?**

I am using `splitChunksPlugin` In my **Project B**. After using it, I got 2 files..

`test1.js` and `test2.js`. It also seems like that `test2.js` is loaded in `test1.js` as lazy-loaded.

In my **Project A,** I use `axios` to fetch `test1.js`.  After clicking the button `test1.js` gets executed which should lazy-load `test2.js`. But `test1.js` seems to be loading the `test2.js` from Project A instead of Project B. 

**What is the expected behavior?**

IT should still be loading `test2.js` from project B instead of project A, since it was built on Project B.

**Other relevant information:**
webpack version:  4.41.5
Node.js version: 12.14.1
Operating System:  Macos
Additional tools:

**Comment by evilebottnawi** [comment]
Without configuration(s) and an example of code no one can help you

**Comment by novaknole** [comment]
I don't think code example would do much, but here it is.

```
splitChunks: {
      chunks: 'all',
      maxInitialRequests: Infinity,
      minSize: 300000, 
      cacheGroups: {
        vendors:false,
        vendor: {
          filename: `[name].[contenthash:${utils.assetHashLength}].js`,
          test: /[\\/]node_modules[\\/]((?!(phaser)).*)[\\/]/,
          name: 'vendors',
          chunks: 'all'       
        },

        common: {
          name: 'common.js',
          minChunks: 2,
          chunks: 'async',
          priority: 10,
          reuseExistingChunk: true,
          // enforce: true
        }
      }
```


in `main.js` , I have 

```
  let scene = await require.ensure([], async function(resolve, reject) {
                this.gameType = await require('./HideGame/hideGameScene').default;
})
```

This is what makes it `test1.js` and `test2.js` lazy loaded in `test1.js`. Because I have 2 projects, and I ask `test1.js` which resides on Project B(different domain) from Project A , after executing `test1.js`, it lazy-loads `test2.js` from Project A instead of still loading it from Project B.

**Comment by evilebottnawi** [comment]
It is expected, because you can't share `cacheGroups` between difference builds (different domain), we have https://webpack.js.org/concepts/module-federation/ for webpack@5 to solve this problem, but it is still under development

**Comment by catherinejanson** [comment]
I have a client website [https://www.logoforwork.com/](https://www.logoforwork.com)/.  I am doing page speed optimization.it has Recaptcha. I have tried many ways to fix it when I applied lazy load on it then contact [form](url) is not working properly

**Comment by evilebottnawi** [comment]
@catherinejanson You problems is not related to this issue

Close the original issue
