### ISSUE TITLE
Bundle file encoding

### ISSUE THREAD

**Issue by ldsenow** [webpack/webpack#11109]
Hi,

I have encountered an issue which the one of the output files' encoding varies from machines (my dev vs CI). It only happens when i use a third party lib (xlsx) in my page (BTW, it is a Vue project) and has non-English translation. It turns out the bundle file contains random chars and the file encoding becomes ANSI not UTF-8 anymore. I tried a webpack encoding plugin and it didnt solve the problem. 

Anyone has solution for this kind of issue?

PS: html head already set to charset utf-8

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

You need convert your file to using `UTF-8`
