### ISSUE TITLE
Initial chunks that fail to load stop entire app from booting

### ISSUE THREAD

**Issue by gpoitch** [webpack/webpack#11108]
# Bug report

**What is the current behavior?**
If an initial chunk does not load (e.g. is content blocked/ad blocked) then the rest of the application code never runs.

For example, if I explicitly create a chunk called `advertising.js` to contain all the advertising code for my app, that chunk may be ad blocked by the browser (that's ok), but then the code in the main chunk never runs.

**If the current behavior is a bug, please provide the steps to reproduce.**
Minimal repro/example app: https://github.com/gpoitch/webpack-chunk-block

**What is the expected behavior?**
Allow the rest of the code to execute.

**Other relevant information:**
webpack version:  4.43.0
Node.js version: 14.4.0
Operating System:  macOS 10.15.5

**Comment by sokra** [comment]
That's working as expected and specced.
If you want to have control over loading failure of a part of you application use `import()`.

splitChunks doesn't change the behavior of the code.

**Comment by evilebottnawi** [comment]
Answer above
