### ISSUE TITLE
Webpack 5 Beta 19: Invalid postinstall

### ISSUE THREAD

**Issue by arcanis** [webpack/webpack#11102]
# Bug report

The postinstall script applied on #10929 causes Webpack 5 to fail installs (technically because `is-ci` and `yarn-deduplicate` are dev deps, but the real problem is that this script shouldn't exist in the first place).

**If the current behavior is a bug, please provide the steps to reproduce.**

Just install Webpack 5. The problem got detected by our automated tests a few minutes ago:

https://github.com/yarnpkg/berry/runs/819104587

**Other relevant information:**

I suggest just removing the postinstall script, since its value is fairly low. If you really need this feature, perhaps we can look into upgrading your repository to Yarn 2 and implement the deduplication as a plugin? Babel recently did it, and Jest is almost done as well, so it probably won't be much more difficult.

**Comment by evilebottnawi** [comment]
Yes, we should remove it, and run it only for CI as lint step, our mistake

**Comment by sokra** [comment]
fixed in https://github.com/webpack/webpack/releases/tag/v5.0.0-beta.20

**Comment by sokra** [comment]
The intention of this script was only for local development. It was never intended to run that on user-side.
