### ISSUE TITLE
The documentation of webpack website is rigorous

### ISSUE THREAD

**Issue by Joker-rose** [webpack/webpack#11111]
I looked at the documentation，and Writed the code according to the documentation. It didn't work out。
For example,create a JS's Library with webpack. Following the documentation and it didn't work.

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Please open an issue in webpack docs (https://github.com/webpack/webpack.js.org) repo where provide example(s) with problems, thanks
