### ISSUE TITLE
Webpack includes jstree/dist/jstree when I include jstree/src/jstree

### ISSUE THREAD

**Issue by Herz3h** [webpack/webpack#11112]
# Bug report

**What is the current behavior?**

I'm including jstree like this:

```js
import 'jstree/src/jstree.js'
import 'jstree/src/jstree.dnd.js'
```

I have checked jstree.js and jstree.dnd.js and none of them have any imports.

**If the current behavior is a bug, please provide the steps to reproduce.**

I have set up a test repository here (project generated with `vue create test-jstree` : https://github.com/Herz3h/test-jstree-webpack

Just run:

```bash
$ yarn install
$ yarn serve 
```

**What is the expected behavior?**

It should only includes the files in jstree/src not the jstree/dist ones....

**Other relevant information:**
webpack version:  4.43.0
Node.js version: 10.21.0
Operating System: MacOS Mojave
Additional tools: -
<img width="674" alt="Capture d’écran 2020-07-01 à 10 36 58" src="https://user-images.githubusercontent.com/1900696/86244190-de326a80-bba7-11ea-8eba-df2a61300b56.png">

**Comment by evilebottnawi** [comment]
Not related to webpack, look here https://github.com/vakata/jstree/blob/master/src/jstree.dnd.js#L13, `jstree.dnd.js` require `jstree` package and wepback resolve it from `dist`, you can use `alias` https://webpack.js.org/configuration/resolve/#resolvealias to avoid it

**Comment by evilebottnawi** [comment]
Ideally you should not use files from `src`

**Comment by Herz3h** [comment]
I somehow skipped that top part... Okay I'll close this. thank you.
