### ISSUE TITLE
Jpeg-2000 image loader support

### ISSUE THREAD

**Issue by AmberWilliams** [webpack/webpack#11118]
## Feature request

**What is the expected behavior?**
Be able to use `.jp2`(Jpeg-2000) images in bundled source code

**What is motivation or use case for adding/changing the behavior?**
Image optimization for Safari users

**How should this be implemented in your opinion?**
Creating a loader that will help use this

**Are you willing to work on this yourself?**
Not sure

**Comment by evilebottnawi** [comment]
Please ise `file-loader`, not related to webpack
