### ISSUE TITLE
API for plugins to inject async resources

### ISSUE THREAD

**Issue by jussi-kalliokoski** [webpack/webpack#1111]
I'd like to make a webpack plugin to collect the polyfills the code requires using [autopolyfiller](https://github.com/azproduction/autopolyfiller) and then use the callback API of [Polyfill service](https://cdn.polyfill.io/v1/docs/) to inject the polyfills before any non-webpack-internals code executes.

I managed to collect the needed polyfills, but there doesn't seem to be a way to delay the execution of the modules until the callback of the polyfill service has fired. Am I missing something or if this is not possible (without depending on undocumented behavior), is this something that could be considered to be added to the plugins API?

**Comment by jussi-kalliokoski** [comment]
On second thought, given how webpack works, this might not be the best approach after all since it would block `require.ensure()` call from fetching additional bundles, e.g. my current approach with webpack is that each view has the initializing JS of that view inlined in the HTML, for example:

```javascript
require.ensure([], function () {
    var initializeApp = require("./initializeApp");
    var View = require("./View");
    initializeApp(View);
});
```

So what I'd actually want is that the polyfills would load in parallel to the chunk triggered by the `require.ensure`, but the chunk would be executed only after the polyfills have loaded. Not sure what would be the best way to go about this.

**Comment by jussi-kalliokoski** [comment]
After trying it out a bit, I think it would actually more sense to leave the developer in control of when to load what. So for example if you wanted to load the polyfills in parallel with the other modules (but not execute the modules before the polyfills have loaded), you'd do this:

```javascript
var loadPolyfills = require("loadPolyfills");
var polyfillsLoaded = loadPolyfills();

require.ensure([], function () {
    polyfillsLoaded.then(function () {
        var initializeApp = require("./initializeApp");
        var View = require("./View");
        initializeApp(View);
    });
});
```

Now I just have to figure out how to inject a named module with generated content into the build after the required polyfills have been collected.

**Comment by SimenB** [comment]
https://github.com/deepsweet/autopolyfiller-loader

**Comment by jussi-kalliokoski** [comment]
> https://github.com/deepsweet/autopolyfiller-loader

Not quite the same - polyfill.io loads only the needed polyfills based on your UA string.

Anyway, I made a plugin for this: https://github.com/jussi-kalliokoski/polyfill-service-webpack . Probably not quite the following the webpack plugin best practices, but it's my first webpack plugin so I'd be happy to get feedback. :)
