### ISSUE TITLE
apply,plugin这2个api在webpack5中被移除了，请问有对应的替换api吗

### ISSUE THREAD

**Issue by xinqilela** [webpack/webpack#11110]
apply,plugin这2个api在webpack5中被移除了，请问有对应的替换api吗

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
