### ISSUE TITLE
Invalid Host header when setting up a new domain

### ISSUE THREAD

**Issue by ErezShahaf** [webpack/webpack#11114]
The website works fine when I am accessing it through the ip, but when I am going to my domain it returns : Invalid Host header I have tried many solution online and none worked, mainly because some of them ask to edit the webpack config and suggested the following solution:

```
devServer: {
  compress: true,
  public: 'mywebsitehere.com' // That solved it for many
}
```
unfortunately, I cannot find the devServer object inside the config file, I tried to add it at the end of the document but it causes the react server to crash.

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Not related to webpack, it is webpack-dev-server repo
