### ISSUE TITLE
import的 webpackChunkName

### ISSUE THREAD

**Issue by 13588936722** [webpack/webpack#11128]
webpack 的懒加载需要我们写/* webpackChunkName: "pageName" */，打包的时候才可以打包出包名。
那么webpack为什么直接解析路径去生成包名呢？

理想效果：
以下代码效果一致
`component: () => import( /* webpackChunkName: "wisdom-pharmacy-entry" */ 'views/wisdom-pharmacy/entry.vue'),`
`component: () => import( 'views/wisdom-pharmacy/entry.vue'),`

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
