### ISSUE TITLE
allow `__webpack_public_path__` customize as a function.

### ISSUE THREAD

**Issue by septs** [webpack/webpack#11120]
in chrome extension development, dynamic import file
need via `chrome.runtime.getURL` method authorize.

i hope allow `__webpack_public_path__` customize as a **function**.

```js
__webpack_public_path__ = (fileName) => chrome.runtime.getURL(fileName);
```

--------------

Reference:
- https://webpack.js.org/guides/public-path/#on-the-fly

**Comment by evilebottnawi** [comment]
Please use the issue template, otherwise it will be closed

**Comment by septs** [comment]
I hope `___webpack_public_path___` can be a `function`, so he is programmable.

**Comment by sokra** [comment]
Have you tried this:

``` js
__webpack_public_path__ = chrome.runtime.getURL(".") + "/";
```

**Comment by evilebottnawi** [comment]
Answer above
