### ISSUE TITLE
Correctly resolve dynamic chunk paths relative to the current file at run time

### ISSUE THREAD

**Issue by gkjohnson** [webpack/webpack#11127]
## Feature request

Correctly load a bundled dynamic javascript import file relative to the current script file.

**What is the expected behavior?**

When dynamic imports (`import()`) the bundle should correctly load bundle chunks relative to the loading javascript file rather than the loaded root HTML file as the `import()` natively behaves.

Without this behavior package dependencies aren't able to rely on dynamic import behavior.

If this isn't currently clear I can provide a minimal build of the problematic behavior.

**What is motivation or use case for adding/changing the behavior?**

Dynamic imports are valuable part of modern javascript for enabling more performant initial download times and support from bundlers is important for enabling their adoption. Right now `publicPath` must be set with the root html file that will load it in mind which is confusing and not necessarily clear without digging deep into webpacks behavior. It also prevents the same package from being loaded by html files located in different directory tiers relative to the bundled javascript. However it should be possible for this functionality to "just work".

**How should this be implemented in your opinion?**

[document.currentScript](https://developer.mozilla.org/en-US/docs/Web/API/Document/currentScript) could be used to derive the current script path in supported browsers. Some [polyfills](https://github.com/JamesMGreene/document.currentScript) claim that `document._currentScript()` is available in older versions of IE. Other polyfills and Parcel.js (which supports this behavior correctly out of the box) rely on [looking at the latest script available in an Errors stacktrace](https://github.com/parcel-bundler/parcel/blob/769c1fcfd98ec4a25270ad5cdbed5f4e9b01d12c/packages/runtimes/js/src/bundle-url.js#L12-L30) to get the current script path and load a chunk relative to the current script.

**Are you willing to work on this yourself?**

This is not typically my expertise but if no one else is available to address this and someone can point me in the right direction for where to make the change I can try to contribute this feature.

**Comment by evilebottnawi** [comment]
> If this isn't currently clear I can provide a minimal build of the problematic behavior.

Yes, please, need to investigate

**Comment by gkjohnson** [comment]
@evilebottnawi 

I've put together a small repro case which I've attached here. Let me know if you have any questions. Here are the instructions that are in the README as well:

```
- Run `npm install`.
- Run `npm run build-config`.
- Run `npm start`.
- Navigate to `localhost:9080/index.html`.
- Dynamic chunk fails to load.

- Uncomment line 7 in `webpack.config.js`.
- Run `npm run build-config`.
- Run `npm start`.
- Navigate to `localhost:9080/index.html`.
- Dynamic chunk loads correctly. There is no way to get this working behavior without a
manually configured `webpack.config.js` file. Even so it will not load if index.html is moved to
another folder.
```

[example.zip](https://github.com/webpack/webpack/files/4886054/example.zip)

Thank you!

**Comment by gkjohnson** [comment]
Hey @evilebottnawi I just wanted to check back in to see if you had any further thoughts on this and needed anything more from me. Thanks!

**Comment by vankop** [comment]
You need explicitly specify `publicPath` to webpack, thats how it works. So if you output without it (in your case `index.js` and `1.index.js`) webpack assumes that scripts served from `/`.

**Comment by gkjohnson** [comment]
> You need explicitly specify publicPath to webpack, thats how it works. So if you output without it (in your case index.js and 1.index.js) webpack assumes that scripts served from /.

This part I understand. I didn't mean to imply this is a bug but I see the title may have made it sound that way.

> adding this functionality will add extra functionality at runtime (increase bundle size).

The other solution I posted that uses an error stacktrace seems to be universal and feels like it would have a small code footprint. I understand the desire to keep the bundle size small but perhaps there's some compromise here? The path resolution code would not be needed if `publicPath` is set, for example, and could be removed in that case.

> `publicPath` option works well for that

I'm suggesting the current behavior be improved. I'm interested in more intuitive out of the box behavior as both a user and a library developer.

Right now when running valid javascript through webpack cli in the simple case it can output code that will not work depending on the path it's imported from because of the behavior I mentioned above. And it fails in a way that's not clear how to fix. It just looks like webpack broke or the code is incorrect.

From the perspective of developing a library I'd like to be able to use dynamic imports to make my packages more streamlined and ultimately make their bundled size smaller without extra effort on the part of the user. With the behavior as it is right now, though, the user code could break for no apparent reason if `publicPath` is not set correctly which it likely could not be if they're not using code splitting otherwise. In the worst case the user thinks the library code they imported is bad and choose to use something else that doesn't use code splitting and gets them a larger initial bundle to load than it would have been with dynamic resolution anyway.

Due to these issues it doesn't seem feasible to distribute a package that uses dynamic imports at the moment even though ultimately it would mean slimmer bundles and better initial download times for users. Wepback is without a doubt the most popular bundling system out there right now and I think handling this more gracefully is good step towards enabling library developers to take advantage of dynamic imports and enabling them to be more common.

**Comment by sokra** [comment]
Yes this is a good idea.

I would suggest the following steps:

* Change `PublicPathRuntimeModule.js` to inject automatic publicPath detection when `publicPath` is set to `"auto"`.
  * `document.currentScript` is preferred. error.stack is non-standard.
* Default `publicPath: "auto"` for improved DX.

**Comment by evilebottnawi** [comment]
Sounds very good

**Comment by gkjohnson** [comment]
Awesome!

A few thoughts on the implementation, then -- this is my first time looking through the webpack code so any advice or correction is appreciated.

Looking at the built code in my test case it looks like the `publicPath` field is set inside of the require callback which can be called asynchronously. However `document.currentScript` is `null` when called in an asynchronous function:

```js
console.log( document.currentScript );
setTimeout( () => {
  
    console.log( document.currentScript );

} );

// <script src="..."></script>
// null
```

Which means I don't think we can just change [this line](https://github.com/webpack/webpack/blob/0d4607c68e04a659fa58499e1332c97d5376368a/lib/runtime/PublicPathRuntimeModule.js#L21-L28) to use `currentScript` unless I'm misunderstanding. It would need to be saved in a parent scope in the initial synchronous run of the script.

Regarding browser support after looking around it seems that `document.currentScript` is not supported in [any IE version](https://caniuse.com/#feat=document-currentscript). Reading around a bit it sounds like for IE < 11 we could use _getCurrentScript() but that's not available in IE11. Scraping the error stack would work in all these cases, though, I would think. If the asynchronous issue is simply addressed then using a fallback approach may be appropriate?

1. use `document.currentScript`
1. use `document._getCurrentScript()`
1. use error stacktrace

**Comment by sokra** [comment]
> Looking at the built code in my test case it looks like the `publicPath` field is set inside of the require callback which can be called asynchronously. However `document.currentScript` is `null` when called in an asynchronous function:

The runtime module should run synchronously, so this should not be a problem.

> Regarding browser support after looking around it seems that `document.currentScript` is not supported in [any IE version](https://caniuse.com/#feat=document-currentscript). Reading around a bit it sounds like for IE < 11 we could use _getCurrentScript() but that's not available in IE11. Scraping the error stack would work in all these cases, though, I would think. If the asynchronous issue is simply addressed then using a fallback approach may be appropriate?
> 
> 1. use `document.currentScript`
> 2. use `document._getCurrentScript()`
> 3. use error stacktrace

For `type="module"` scripts `import.meta.url` is recommended. Can we use that too?

Before adding a super hacky solution I would better flag this feature as "modern browsers only" and omit support for IE11. I mean you can still specific `publicPath` manually if you need support for these browsers...

**Comment by gkjohnson** [comment]
> The runtime module should run synchronously, so this should not be a problem.

You're right! Looks like I misread the braces.

> For `type="module"` scripts `import.meta.url` is recommended. Can we use that too?

I tried this and unfortunately it's not so simple. If `import.meta` is used _anywhere_ in a script file not imported as a module an error is logged and it can't be caught so this can't happen conditionally. The stack trace approach does work here, too, though

`document.currentScript` works well in the non module case but I'm trying to figure out how to test `_getCurrentScript()`. Do you have any suggestions on how to test and IE versions <= 10?

**Comment by evilebottnawi** [comment]
@gkjohnson I think we can provide how to polyfill it (if it is possible)

**Comment by gkjohnson** [comment]
I've created PR #11258 to help address this.

> @gkjohnson I think we can provide how to polyfill it (if it is possible)

Unfortunately I don't believe it's possible to polyfill this so simply such that it matches the spec. It may be possible considering webpack is getting `currentScript` immediately, though, and doesn't rely on it being `null` in async calls. Here are a couple possible polyfills for IE but I haven't tested the robustness of them:

https://github.com/amiller-gh/currentScript-polyfill
https://github.com/JamesMGreene/document.currentScript

I'm not sure how well these would work when using modules, though. Is that a common webpack use case?

**Comment by evilebottnawi** [comment]
Done in https://github.com/webpack/webpack/pull/11258, I think we can close the issue, feel free to feedback

**Comment by blackrabbit99** [comment]
Can not resolve publicPath for `libraryTarget = 'umd'`
webpack version = 5.68.0

Looks like logic that detects publicPath is called in async manner so it does not detect currentScript.

**Comment by desbrowne** [comment]
In case anyone else runs into this, we had inline script tags that caused this to fail.
```html
<script>
/// e.g. this is inline with no src attribute
</script>
```
To fix this we replaced `document.getElementsByTagName("script")` with `document.querySelectorAll('script[src]')`
