### ISSUE TITLE
webpack --watch do not detect changes in files that only export TS interfaces/types etc.

### ISSUE THREAD

**Issue by kenilam** [webpack/webpack#11121]
# Bug report

**What is the current behavior?**
I believe this issue has been reported in a closed issue (https://github.com/webpack/webpack/issues/8734)
therefore, report again for visibility:
_When the only thing a Typescript file exports is an interface, changes to the interface are not seen by watch_

I believe files only contain interfaces contain no real Javascript and that is the issue that webpack is not able to detect any changes while transpilation.

Tried the workaround with comments that didn't fix the issue, the only way I were able to get the `type only` file trigger the build is to have a `export { a: 'a' }` then `import { a } from './typeOnly.ts'` - which is not ideal and not practical. 

**If the current behavior is a bug, please provide the steps to reproduce.**
Create a file that only export interface/types:
`props.ts`
```ts
interface Props {
  name: string
}

export default Props
```

Then create anther file that import `props.ts`:
`component.ts`
```tsx
import React, { FunctionComponent } from 'react';
import Props from './props';

const MyComponent: FunctionComponent<Props> = ({ name }) => (
  <div>{ name }</div>
);
```

Modify `props.ts`, either add/change/delete properties in `Props` then apply those changes to `component.ts`

Webpack not able to detect the changes in `props.ts` and the `type errors` report error on the UI.

See screenshot attached below for example:
![Screen Shot 2020-07-05 at 2 40 45 AM](https://user-images.githubusercontent.com/657845/86529852-f84ea000-be68-11ea-83d8-fcbb03e14982.png)

https://github.com/kenilam/Ki.CL is my repos where you can reproduce.

**What is the expected behavior?**
Webpack watch should be able to pick up file changes that only contain `type` values

**Other relevant information:**
webpack version:  4.43.0 
Node.js version: 14.4.0

**Comment by sokra** [comment]
@webpack-bot move to TypeStrong/ts-loader

**Comment by kenilam** [comment]
> @webpack-bot move to TypeStrong/ts-loader

@sokra i actually deprecated `to-loader` and migrated to `es-loader` few weeks ago

**Comment by johnnyreilly** [comment]
That's so cool!
