### ISSUE TITLE
Webpack 5 - module reexport tree shaking issue not resolved

### ISSUE THREAD

**Issue by net-bet** [webpack/webpack#11125]
# Bug report

**What is the current behavior?**

When reexporting nodule in index.js file, and import few of them, all modules are bundled.

**If the current behavior is a bug, please provide the steps to reproduce.**

index.js (being packed in a package called @lib but **not** bundled which the main entry is index.js):
import a from './...';
import b from './...';
import c from './...';
export { a, b, c };

app.js
import { a } from '@lib' 

webpack.config:
      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules\/(?!(@lib|ANOTHER-ONE)\/).*/,
        loader: "babel-loader",
        options: { presets: ["@babel/env", "@babel/preset-react"] }
     },

b and c bundled

**What is the expected behavior?**

b and c should be tree shaken.
If I import directly from the module (@tle/ui/dist/lib/....), there is no issue.

**Other relevant information:**
webpack version:  5.0.0-beta.20
Additional tools:

**Comment by evilebottnawi** [comment]
Please `modules: false` for https://babeljs.io/docs/en/babel-preset-env#modules

**Comment by net-bet** [comment]
1. modules:false (auto) is the default in babel>=7
2. I tried it now and it doesn't work
3. I think if it was the issue it wouldn't happen only in case of reexport

Am I missing something?

**Comment by evilebottnawi** [comment]
> modules:false (auto) is the default in babel>=7

Set it to `false`, `auto` is not `false`

**Comment by net-bet** [comment]
as said I tried, anyway what I missed was the sideEffects:false. and it also works in version 4. I didn't know about this behavior!
