### ISSUE TITLE
scss files loading differ between dev and prod.

### ISSUE THREAD

**Issue by helabenkhalfallah** [webpack/webpack#11124]
# Bug report
I have an issue with scss files loading : 
- in dev mode (local) if I not import scss files, I have my page styled (**strange**).
- in prod mode, if not imported, isn't loaded (**the correct**).
I have this issue in three internal projects.
It seems like in dev mode webpack loads everything.
So when locally testing (dev), everything works, when deploying (prod) no style was loaded, astonished.

**What is the current behavior?**
scss file loading differ between dev and prod.

**If the current behavior is a bug, please provide the steps to reproduce.**
Normal steps : 
- webpack-dev-server (local)
- webpack build prod (deployment)

**What is the expected behavior?**
scss loading should be the same in dev and prod to correctly validate dev before deploying.

**Other relevant information:**
webpack version:  4.32.2 and 4.41.5.
Node.js version: 10.13.0
Operating System: Windows 10
Additional tools: none

Thank.

**Comment by helabenkhalfallah** [comment]
Base config : 

```
const merge = require('webpack-merge');

const Dev = require('./webpack.dev');
const Prod = require('./webpack.prod');

const baseConfig = {
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        use: ['babel-loader'],
      },
      {
        test: /\.scss$/,
        loaders: [
          'style-loader',
          'css-loader',
          'resolve-url-loader',
          {loader: 'sass-loader', options: {sourceMap: true}},
        ],
        exclude: /node_modules\/(?!XXX)/,
      },
      {
        test: /\.css$/,
        use: [
          { loader: 'style-loader' },
          { loader: 'css-loader' },
        ],
        exclude: /node_modules\/(?!XXX)/,
      },
      {
        test: /\.less$/,
        use: [
          { loader: 'style-loader' },
          { loader: 'css-loader' },
          {
            loader: 'less-loader',
            options: {
              javascriptEnabled: true,
            },
          },
        ],
        exclude: /node_modules\/(?!XXX)/,
      },
      {
        test: /\.(jpe?g|png|gif|svg)$/,
        loader: 'url-loader',
        options: {
          limit: 8192,
          name: 'assets/img/[name].[ext]',
        },
      },
      {
        test: /\.(ttf|eot|otf|woff2?)$/,
        loader: 'url-loader',
        options: {
          limit: 8192,
          name: 'assets/fonts/[name].[ext]',
        },
      },
    ],
  },
  resolve: {
    extensions: ['*', '.js', '.jsx'],
  }
};

const devConfig = merge(baseConfig, Dev);
const prodConfig = merge(baseConfig, Prod);

module.exports.devConfig = devConfig;
module.exports.prodConfig = prodConfig;
```

Webpack dev : 

```
const path = require('path');

module.exports = {
  mode: 'development',
  entry: path.resolve(__dirname, '../src/main/webapp/index.js'),
  output: {
    path: path.resolve(__dirname, '../src/main/webapp/dist'),
    publicPath: '/',
    filename: 'bundle.js',
  },
  devServer: {
    contentBase: '../dist',
    historyApiFallback: true,
    hot: true,
    port: 9000,
  }
};

```

Webpack prod : 

```
const path = require('path');
const TerserPlugin = require('terser-webpack-plugin');

module.exports = {
  mode: 'production',
  entry: path.resolve(__dirname, '../src/main/webapp/index.js'),
  output: {
    path: path.resolve(__dirname, '../src/main/webapp/dist'),
    publicPath: '/',
    filename: 'bundle.js',
  },
  optimization: {
    minimizer: [
      new TerserPlugin({
        parallel: true,
        sourceMap: true,
        terserOptions: {
          mangle: true,
          output: {
            comments: false,
          },
        },
      })
    ]
  }
};
```

**Comment by vankop** [comment]
@helabenkhalfallah Unfortunately, it is very hard to help you without reproducible repo..

**Comment by helabenkhalfallah** [comment]
Hello @vankop I added my webpack configuration, I think this what you need not ?

**Comment by evilebottnawi** [comment]
I think it is the `sideEffects` problem (https://webpack.js.org/guides/tree-shaking/)? How you import styles?

**Comment by helabenkhalfallah** [comment]
Exemple Home Page : 

```
import React, { Component } from 'react';
import '../scss/_reset.scss';
import '../scss/_grid.scss';
import '../scss/_layoutHome.scss';


class HomePage extends Component {
  componentDidMount() {}

  initPage = () => {};

  render() {
    return (
      <div className="homeContainer">
          <span className="titleClassname"> HomePage </span>
      </div>
    );
  }
}

export default HomePage;
```

Package json : 
```
  "sideEffects": [
    "*.scss"
  ],
```

**Comment by evilebottnawi** [comment]
@helabenkhalfallah Do you read [this](https://webpack.js.org/guides/tree-shaking/#clarifying-tree-shaking-and-sideeffects)? After adding `sideEffects`, it is working?

**Comment by helabenkhalfallah** [comment]
@evilebottnawi yes :) 

I have many stranges behaviors in my internals projects  : 

"webpack": "=4.28.4" => side effects = false => **I have styles loaded both in dev and prod (like if treeshaking not working), why ?**
"webpack": "=4.32.2" => side effects = false => **styles are loaded only in local dev, why ?**.
"webpack": "=4.32.2" => side effects = 'scss' => **styles are loaded in dev and prod**.

Why scss file are loaded in local even if side effects is false and I don't import the scss files ? Here is my central issue.
 This make not intuitive to find that we must add side effects attributes (because local dev work).
And why using 4.28.4, I have styles loaded in dev and prod ?

Thank you for your help :)

**Comment by evilebottnawi** [comment]
@helabenkhalfallah I think it was bugs, try to use only latest versions

**Comment by helabenkhalfallah** [comment]
Okay, I will try to update. Thanks.

**Comment by evilebottnawi** [comment]
@helabenkhalfallah Can we close? Do you have more questions?

**Comment by helabenkhalfallah** [comment]
Yes yes, I wil try to update to the latest version, thank you for your help :)

**Comment by evilebottnawi** [comment]
@helabenkhalfallah feel free to feedback if you will have problems
