### ISSUE TITLE
Merge is not a function

### ISSUE THREAD

**Issue by makuzaverite** [webpack/webpack#11139]
####  Doc might be updated about how  merge package is used on production section under guides

> I had an issue to day i was looking into webpack's doc and the face an error like this 

This didn't work for me

![more](https://user-images.githubusercontent.com/53856673/86914606-e4cd5e80-c120-11ea-956c-bca81642ccf6.PNG)

![image](https://user-images.githubusercontent.com/53856673/86914434-a33cb380-c120-11ea-879a-67b0846092dc.PNG)

I came a cross an found that webpack-merge package now is destructured during it's import

![solution](https://user-images.githubusercontent.com/53856673/86914746-16dec080-c121-11ea-9473-87e124f32747.PNG)

Here is link to the page https://webpack.js.org/guides/production/#setup
may be documentation might be updated to remove that kind of confusion

**Comment by snitin315** [comment]
> webpack-merge package now is destructured during it's import

yes, I will update the docs.

**Comment by makuzaverite** [comment]
May you allow me to update it

**Comment by makuzaverite** [comment]
i want to contribute

**Comment by snitin315** [comment]
Yes sure.

**Comment by snitin315** [comment]
you need to update here https://github.com/webpack/webpack.js.org/edit/master/src/content/guides/production.md

**Comment by evilebottnawi** [comment]
Not related to webpack
