### ISSUE TITLE
Prevent certain directories from being scanned by `require.context` 

### ISSUE THREAD

**Issue by remorses** [webpack/webpack#11149]
## Feature request

**What is the expected behavior?**
When using `require.context` there should be a way to prevent certain directories children to be checked against the regex

**What is motivation or use case for adding/changing the behavior?**
I would like to exclude all the `node_modules` directories from the search, preventing its children to be tested against the regex, this would greatly improve the build time

**How should this be implemented in your opinion?**
The recurse argument could accept a regex in addition to the boolean type:
- true would mean "recurse inside every directory", 
- false "don't recurse" 
- a regex "check if folder satisfies the regex"

**Are you willing to work on this yourself?**
yes but i don't know the code base and i need guidelines on where this logic should be implemented

**Comment by remorses** [comment]
Maybe this is the only part that needs to be changed
https://github.com/webpack/webpack/blob/00226ff3de02078c641ef0426a5425c184510b8a/lib/ContextModuleFactory.js#L268-L270

I will open a pull request

If you have advices or suggestion on other ways to implement this please tell me

**Comment by evilebottnawi** [comment]
Please use regexp to include/exclude necessary files, you can read this here https://webpack.js.org/guides/dependency-management/#requirecontext

**Comment by remorses** [comment]
The regex is not tested against folders, all the files will be scanned recursively no matter what the regex is

Look at the line I posted above, every time the addDir function finds a directory it calls itself scanning all children

**Comment by evilebottnawi** [comment]
@remorses There are a lot of ways to achieve this:
- You can set `useSubdirectories: false` and do multiple requests
- You can refactor structure
- You can filter in runtime (bad idea)


It is specific webpack API and we recommend avoid this in favor ES module syntax

**Comment by remorses** [comment]
This api is used for storybook and really slows it down because searches every file inside node modules

I can work on this, the recurse argument could be a regex or Boolean type, it is not even a breaking change, can I open a pull request?

**Comment by evilebottnawi** [comment]
> This api is used for storybook and really slows it down because searches every file inside node modules

Can you provide where?

**Comment by remorses** [comment]
https://github.com/storybookjs/storybook/blob/54a1c0c5f6e6cb9ca078c884c45447b95fada29f/lib/core/src/server/preview/to-require-context.js#L26

**Comment by remorses** [comment]
In the next release it is still used

https://github.com/storybookjs/storybook/blob/57e5092dd5d46da5f5c5e3dbe76d26e62587c724/lib/core/src/server/preview/to-require-context.ts#L61

**Comment by evilebottnawi** [comment]
How you fix it in storybook?

**Comment by remorses** [comment]
I was thinking to add a regex to exclude directories like `node_modules` from being scanned

But maybe it's better to not use `context.require`,  instead generate a file at build time with an object that maps from filenames to `import` , this way the glob search behaviour can be more flexible

```js
{
  './dir/story.js': () => import('./dir/story.js'),
  // for every file found by the glob
}
```
Is this the best approach?

PS: i am not a contributor of storybook but i am building another similar project that uses the same approach

**Comment by remorses** [comment]
I will just remove `context.require`

**Comment by evilebottnawi** [comment]
Yes, don't use `context.require`, migrate on other approaches, `context.require` is webpack specific, and should be avoided in real code as much as possible
