### ISSUE TITLE
How to write loader width HMR?

### ISSUE THREAD

**Issue by linlinyang** [webpack/webpack#11147]
`

  resolveLoader: {
    alias: {
        'my-loader': resolvePath('./lib/index.js')
      }
  },
`
and 
`
devServer: {
        open: true,
        compress: true,
        hot: true,
        historyApiFallback: true,
        contentBase: resolvePath('dist'),
        disableHostCheck: true
    },
`

and my loader change, about demos do not update

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Here docs https://webpack.js.org/concepts/hot-module-replacement/ and https://webpack.js.org/guides/hot-module-replacement/
