### ISSUE TITLE
v4 `contenthash` changes when file content does not (seems to be fixed in v5)

### ISSUE THREAD

**Issue by OliverJAsh** [webpack/webpack#11146]
# Bug report

**What is the current behavior?**

An asset's `contenthash` changes even though the file content does not change. This is problematic because it reduces the efficiency of our cache.

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/OliverJAsh/webpack-hash-bug-test

1. Clone the repository
1. Run `yarn`
1. Copy the steps in `README.md` and paste them into the terminal

**What is the expected behavior?**

There should be no difference to the `internal-error-route~not-found-route` chunk file name, because the contents have not changed.

Actual behaviour: the `internal-error-route~not-found-route` chunk file name changes, even though the contents have not changed.

Note I also tested this using the webpack v5 beta and it seems to be fixed. Is there any chance we could retrofit that fix to v4?

**Other relevant information:**
webpack version: 4.43.0
Node.js version: 12.8.1
Operating System: macOS latest
Additional tools:

**Comment by OliverJAsh** [comment]
@sokra What do you think the chances are of getting a fix retrofitted to v4 for this?

**Comment by sokra** [comment]
Considering the risk and the work involved to fix this non-critical problem I don't think we will fix that for webpack 4. You can start using the webpack 5 beta, or wait a bit

**Comment by evilebottnawi** [comment]
Unfortunately, this will not be very easy to fix and can potentially create new problems, yes, fixed in webpack@5, also we improve generation of `contenthash` https://github.com/webpack/webpack/pull/11339 (`true` by default in `production` mode), now it is always hash of content. webpack@5 release will be `10-10-2020`, so I would like to close this issue, webpack@4 accept only critical fixes, sorry

**Comment by dazjean** [comment]
Is there a necessary condition for the occurrence of this problem? In my project, the same configuration is valid when Vue is built, but in the react project, only the content hash of JS file is invalid, and the amazing discovery of the content hash used by the CSS file extracted by react is normal.
