### ISSUE TITLE
chunk names are numeric instead of regular ones

### ISSUE THREAD

**Issue by budarin** [webpack/webpack#11159]
# Bug report
Try to use code splitting with import and "magic" comments for giving chunks meaningful names and use them in SSR, but I get numeric names instead

**What is the current behavior?**
chunks have numeric identifiers

**If the current behavior is a bug, please provide the steps to reproduce.**
1. add to webpack.confi.js to output section `chunkFilename: '[name].js',`
2. set in code "magic comment" `() => import(/* webpackChunkName: "Page1" */ '../pages/Page1')`
3. try to to bundle and get `0.js` instead of 'Page1.js' as a chunk name

[here is the config](https://gist.github.com/budarin/5d9bea96239143dbca51556c9a4a0ebe)

**What is the expected behavior?**
expected chunk to have the name given in "magic" comment

**Other relevant information:**
webpack version:  4.43.0
Node.js version: v14.4.0
Operating System: any
Additional tools:

**Comment by evilebottnawi** [comment]
Can't reproduce:
```
       Asset       Size  Chunks                   Chunk Names
    Page1.js  376 bytes   Page1  [emitted]        Page1
Page1.js.map  252 bytes   Page1  [emitted] [dev]  Page1
    index.js   8.49 KiB   index  [emitted]        index
index.js.map   8.37 KiB   index  [emitted] [dev]  index

```

Can you create reproducible test repo?

**Comment by ScriptedAlchemy** [comment]
Check your Babel configurations. Something might be messing with it in the repo. Saw a similar issue closed due to babelrc

**Comment by budarin** [comment]
Thank you for your patience
Here is the peece of real [project](https://github.com/budarin/wp-chunk-names-problem-demo)

here is no criminal in my babel config

**Comment by evilebottnawi** [comment]
`comments: true,` in `config/babel/client.babel.configs.js`

**Comment by budarin** [comment]
I'm sorry!
Coud yuo add this to webpack code splitting docs?
I am aware that I am not the first and I am not the last to face this
Thank you a lot!

**Comment by ScriptedAlchemy** [comment]
Not sure if it really belongs in the docs, but can try making troubleshooting section the bottom. Generally, we do not document implementation details.

**Comment by budarin** [comment]
@evilebottnawi 
just remove string 'comments: true, from babel config in demo project and try to build config - the result is the same - chunks are numerical :(

**Comment by evilebottnawi** [comment]
@budarin 
```
Hash: 6291b796eee6a4d31f64
Version: webpack 4.43.0
Time: 5362ms
Built at: 07/15/2020 2:52:41 PM
      Asset       Size    Chunks             Chunk Names
NotFound.js   3.09 KiB  NotFound  [emitted]  NotFound
  Page1.css   39 bytes     Page1  [emitted]  Page1
   Page1.js   10.2 KiB     Page1  [emitted]  Page1
  Page2.css   37 bytes     Page2  [emitted]  Page2
   Page2.js   10.2 KiB     Page2  [emitted]  Page2
   Page3.js   9.33 KiB     Page3  [emitted]  Page3
 client.css  279 bytes    client  [emitted]  client
  client.js   2.83 MiB    client  [emitted]  client
```

Maybe you have `removeComments: true` in `tsconfig.json`?

I urge you not to touch the default options. Their values were set for a reason. Most of the problems arise precisely when developers begin to touch them without understanding.

**Comment by budarin** [comment]
I have removed them both: babel & tsconfig

```bash
Hash: 91699a666ed455f39b78
Version: webpack 4.43.0
Time: 2417ms
Built at: 07/15/2020 7:39:28 PM
     Asset       Size  Chunks             Chunk Names
     0.css   39 bytes       0  [emitted]  
      0.js   10.2 KiB       0  [emitted]  
     1.css   37 bytes       1  [emitted]  
      1.js   10.2 KiB       1  [emitted]  
      2.js   9.06 KiB       2  [emitted]  
      3.js   3.07 KiB       3  [emitted]  
client.css  279 bytes  client  [emitted]  client
 client.js   2.83 MiB  client  [emitted]  client
Entrypoint client = client.css client.js
```

**Comment by evilebottnawi** [comment]
Try to update deps, something wrong on your side, code passed to webpack without comments, there is not problems on webpack side, you can see my local output above

**Comment by budarin** [comment]
@evilebottnawi 

Thank you very much for your help !

the problem turned out to be that Babel was connecting a config that is at the root of the project and which also had the `comments: false ' code, although the configuration for babel-loader specified a file that was correct
