### ISSUE TITLE
For interoperability, what's the best practice for exposing webpack's require function or a large set of modules outside of the bootstrap scope (ie. window, etc.)?

### ISSUE THREAD

**Issue by Alpheus** [webpack/webpack#1115]
Assuming I'm building everything with webpack and have several chunked entry points. What would be the recommended approach to exposing the either require, require.ensure or specific modules (in commonjs or AMD format) into the browser?

**Comment by shama** [comment]
Set the [output.libraryTarget](http://webpack.github.io/docs/configuration.html#output-librarytarget) to `'umd'` then the bundle can be consumed via commonjs, amd or a script tag.

**Comment by bebraw** [comment]
@Alpheus Safe to close?

**Comment by Alpheus** [comment]
Yes.
