### ISSUE TITLE
v4 devtoolModuleFilenameTemplate adds additional symbol on incremental builds

### ISSUE THREAD

**Issue by SPWizard01** [webpack/webpack#11157]
# Bug report

**What is the current behavior?**

on each incremental build webpack adds additional `/` to unaffected modules while running webpack-dev-server,
which results in a bad expirience in dev tool because folders get nested deeper and deeper with each build.

 i am not sure if its webpack-dev-server issue or webpack itself however looking into the source it seems like its webpack

i.e. here i have done 2 incremental builds, this module is imported by a module which was not modified
```
{
  identifier: '//./node_modules/uncontrollable/esm/index.js',
  shortIdentifier: '//./node_modules/uncontrollable/esm/index.js',
  resource: '//./node_modules/uncontrollable/esm/index.js',
  resourcePath: '//./node_modules/uncontrollable/esm/index.js',
  absoluteResourcePath: '//./node_modules/uncontrollable/esm/index.js',
  allLoaders: '',
  query: '',
  moduleId: '',
  hash: 'be67',
  namespace: ''
}
```
you can see that identifier/shortIdentifier etc start with `//`

**If the current behavior is a bug, please provide the steps to reproduce.**

single entry (A) with dynamic import (B)

``` 
devtool: "source-map",
output: {
    devtoolModuleFilenameTemplate: info => {
      console.log(info);
      return `webpack:///${info.resourcePath}`;
    },
}
```
modify entry (A) and observe that (A) has correct paths in console log while B and its dependencies had additional `/` added to the beginning of the path
modify (B) and observer that (B) now has a correct path

**What is the expected behavior?**

resourcePath should not change?
i.e. on each incremental build it should still start with `./node_modules` and not `///////./node_modules`

**Other relevant information:**
webpack version:  4.43.0
Node.js version: v12.18.0
Operating System: Windows 10
Additional tools: N/A?

**Comment by evilebottnawi** [comment]
Please create reproducible test repo

**Comment by SPWizard01** [comment]
@evilebottnawi https://github.com/SPWizard01/webpackdevtoolbug here you go :)

**Comment by evilebottnawi** [comment]
bump

**Comment by SPWizard01** [comment]
bump :)

**Comment by sokra** [comment]
Is this still an issue with webpack 5?

**Comment by alexander-akait** [comment]
@sokra Yep, I can create reproducible test repo

**Comment by sokra** [comment]
Try to change this line:

https://github.com/webpack/webpack/blob/b14ecc1be015dbcf1b9b1e075cc125320ed00030/lib/SourceMapDevToolPlugin.js#L386

to `const sourceMap = { ...task.sourceMap };` and check if this fixes it.

**Comment by alexander-akait** [comment]
Check it on webpack the latest v5 (i.e. `5.26.0`)

> ~~Bug1 - Webpack~~ (fixed)
> ~~Bug 2 - Webpack-Dev-Server~~ (fixed)

I was wrong, all bugs are fixed, feel free to feedback, anyway if you faced with bugs again please open new issue(s)
