### ISSUE TITLE
When while watching file removed try to resolve it again

### ISSUE THREAD

**Issue by whitecolor** [webpack/webpack#11158]
## Feature request

Thogh this could be refered as bug, but I cound find a like issues.

**What is the expected behavior?**

1) user tranferes code from `src/helpers.ts` to `src/helpers/index.ts`
2) removes `src/helpers.ts`
3) webpack/wds watches and can not find removed files should try to resolve it again it would find `src/helpers/index.ts`

Currently it gives an error:

```
Module build failed (from ./.../loader/index.js):
Error: ENOENT: no such file or directory,
```
User needs to restart the process.

**What is motivation or use case for adding/changing the behavior?**

This would make workflow more flawless.

**How should this be implemented in your opinion?**

only gods know

**Are you willing to work on this yourself?**
no

**Comment by sokra** [comment]
fixed in webpack 5
