### ISSUE TITLE
Export more types from types.d.ts

### ISSUE THREAD

**Issue by otakustay** [webpack/webpack#11154]
## Feature request

`webpack@5`'s bult-in types have less types exported than `@types/webpack`, some of them are quite useful to implement a custom build too.

Some types can be inferred from existing ones but requires a lot of work like this:

```typescript
import {RuleSetRule} from 'webpack';

type RuleSetUse = Exclude<RuleSetRule['use'], undefined>;

type LoaderFactory = (context: OurCustomBuildContext) => RuleSetUse | null;
```

**What is the expected behavior?**

I'm currently missing these types:

- RuleSetCondition
- RuleSetConditionAbsolute
- RuleSetUse
- RuleSetUseItem
- RuleSetLoader (the object structure of `module.rules.use`)

**What is motivation or use case for adding/changing the behavior?**

By exporting more types, developers can create more robust build tools with typescript.

**How should this be implemented in your opinion?**

Yes

**Are you willing to work on this yourself?**

I can try to create a PR to export types above.

**Comment by KevinGruber** [comment]
I can only second that.
We have a custom build pipeline / CLI and use webpack types everywhere.
But since webpack 5 doesn't export the same types we can't really use it.

We are missing the ones mentioned above.
Plus MultiStats for example and all connected Types there. 

What does the future plan look like?

**Comment by sokra** [comment]
Send a PR. Types can be exposed by adding `@typedef`s to `lib/index.js`. Run `yarn special-lint-fix` to update the typings.
