### ISSUE TITLE
Library Modules undefined when using splitChunks

### ISSUE THREAD

**Issue by rpg-verodin** [webpack/webpack#11152]
# Bug report

**What is the current behavior?**

Without `splitChunks` enabled entries have module objects in library as expected, but when `splitChunks` is enabled all keys in the library object are `undefined`.

**If the current behavior is a bug, please provide the steps to reproduce.**

Attached repository has both the broken state (`master` branch) and the working state (`working` branch). The only difference between the two branches is the addition of the `optimization` object in `webpack.common.js`.

https://github.com/rpg-verodin/splitchunks_issue_demo

To set up the repo:
* Check out repo locally with git clone.
* Run `npm i`
* Run `npm start`
* Load http://localhost:8080/ in browser

The application I work on at my job has a multi-page architecture. Most Webpack entries have a variety of vendor bundles (including React, lodash, moment, etc), and they are all repeated over and over across the product.

In our product I had a branch from about 6 months ago where `splitChunks` was working as configured, but it never made it into our mainline codebase. When I tried to pull it in recently I came across this issue.

Both the working and broken builds include the following identical chunk of code that includes the simplification of a JSX component that should be available at `components.tester.Tester`, but in the broken build `components.tester` is `undefined`:

`eval("__webpack_require__.r(__webpack_exports__);\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, \"Tester\", function() { return Tester; });\n/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! react */ \"./node_modules/react/index.js\");\n/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(react__WEBPACK_IMPORTED_MODULE_0__);\n\nvar Tester = function Tester() {\n  return /*#__PURE__*/react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement(\"div\", null, /*#__PURE__*/react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement(\"h1\", null, \"This is a test\"), /*#__PURE__*/react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement(\"p\", null, \"This is only a test.\"));\n};\n\n//# sourceURL=webpack://components.%5Bname%5D/./components/Tester.js?");`

**What is the expected behavior?**

When `splitChunks` is enabled the modules in the library object should not be undefined, but should contain exports the same as when `splitChunks` is not enabled.

**Other relevant information:**
webpack version:  4.43.0
Node.js version: v14.1.0 (same issue occurs with 10.17.0  in our production environment)
Operating System: Mac OS 10.15.5 and Centos 7
Additional tools: Not sure what this is asking for, but the repo has a package.json, .bashrc  and webpack config with all the info about the conditions that result in this.

**Comment by evilebottnawi** [comment]
You split chunks and don't include `react` chunk in your html, you should use this:
```
<script src='/react.js'></script>
<script src='/tester.js'></script>
<script src='/app.js'></script>
``` 

All works fine. You can use HtmlWebpackPlugin to avoid this problem.

**Comment by rpg-verodin** [comment]
@evilebottnawi That would certainly do it. Thanks for the help. Sorry for my stupid mistakes.

**Comment by cymptom** [comment]
@evilebottnawi and anyone else -- 

Mine might be a separate issue or a different manner of oversight, but I thought I'd ask anyway: 

In my case, I'm using webpack to create a library module and wanted to chunk out the vendor portion of it. I'm not using `<script/>` includes -- my webpack output is being consumed via ES `import`. 

It works fine as a single bundle, but as soon as I introduce the `splitChunks: { chunks: "all" }` optimization, my module import comes back as `undefined`.

Any immediate thoughts as to why that might be? If not, I'll consider creating a separate issue...

**Comment by evilebottnawi** [comment]
@cymptom do you use webpack-dev-server or simple webpack compilation?

**Comment by cymptom** [comment]
@evilebottnawi I'm using simple webpack compilation. The config is something like this:

```
module.exports = {
	entry: {
		"image-editor": "./lib/image-editor/src/index.ts"
	},
	devtool: false,
	plugins: [
		new webpack.SourceMapDevToolPlugin({
			exclude: /vendor/,
		})
	],
	optimization: {
		splitChunks: {
			chunks: "all"
		}
	},
	module: {
		rules: [
			{
				test: /\.tsx?$/,
				exclude: /node_modules/,
				use: {
					loader: "ts-loader"
				}
			}
		]
	},
	resolve: {
		extensions: [".tsx", ".ts"]
	},
	output: {
		filename: "[name]/index.js",
		libraryTarget: "umd",
		path: "dist/lib"
	}
};
```

It's being consumed in my code like this:
```
import { ImageEditor } from "lib/image-editor";
```

This works perfectly without the `splitChunks` setting. With `splitChunks` on, however, I'll get an error in the console: `Cannot read property 'ImageEditor' of undefined`.

**Comment by evilebottnawi** [comment]
@cymptom Can you create reproducible test repo, I think we fixed it in master, want to check

**Comment by cymptom** [comment]
> @cymptom Can you create reproducible test repo, I think we fixed it in master, want to check

I'll do that and get back to you. Thanks :)

**Comment by cymptom** [comment]
> @cymptom Can you create reproducible test repo, I think we fixed it in master, want to check

Alrighty, repo is here:
https://github.com/cymptom/webpack-chunk-demo

Steps to reproduce:

1. `npm install` in `\lib\guid-generator` and `\site`
2. `npm start` in `\site`.
3. Navigate to `localhost:3000` and observe guid printed to page using bundled uuid dependency.
4. Uncomment the `optimization` section of `\site\webpack.config.js`.
5. `npm run build:libs` in `\site` to re-run webpack.
6. Refresh `localhost:3000` and observe console error.

In putting together this repo I wondered whether the issue could be related to the use of `require.js`, but I don't know -- let me know what you think.

Thanks!

**Comment by evilebottnawi** [comment]
Sorry for delay, look at this tomorrow

**Comment by evilebottnawi** [comment]
@cymptom Sorry for delay, bug can't start:
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/api-extractor - Not found
npm ERR! 404 
npm ERR! 404  'api-extractor@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by evilebottnawi** [comment]
Anyway reproduced:
```
index.js:15 Uncaught TypeError: Cannot read property 'guidGenerator' of undefined
```

**Comment by evilebottnawi** [comment]
@cymptom the same problem, when you use `splitChunks` you need to inject them in `HTML` template:
- fix in code:
```html
<script>
        require(
            [
                "dist/index.js",
                "dist/vendor-lib_guid-generator_node_modules_uuid_dist_esm-browser_v4_js/index.js",
            ], 
            (module) => {
                module.run();
            }
        );
</script>
```
- you can use `html-webpack-plugin` to automate it 
- you can use `enforce: true` on `vendor` chunk to always have chunk(s), but I do not recommend, but may valid cases in some situations

**Comment by cymptom** [comment]
@evilebottnawi Thanks for looking into that. Sorry for whatever configuration hiccup caused that `api-extractor` error 🙏 

So just to confirm, vendor chunks _always_ need to be manually included on the page? I think I had expected, perhaps incorrectly, that the vendor chunk would be imported automatically when the main module is loaded. It's a bit surprising that there isn't at least an option to enable this behavior, given that webpack knows of the main module's dependency on the vendor chunk and could easily do that wire-up in an elegant way. 

For the average scenario, your suggestion of including the vendor script on the HTML page is probably ideal. However, the problem for me stems from the fact that I'm using webpack to bundle a **library**. The library isn't meant to be included on the page directly, and it's safe to say that I don't want the page to need to know anything about the library or its dependencies. The library module should be easily consumed by developers via simple `import` -- they shouldn't need to worry about manually loading that module's dependencies or including the vendor script at the page level. Perhaps this is an unusual usage of webpack?

About `enforce: true` -- at a glance, the docs don't seem to suggest that this would help achieve the effect I'm looking for. Would `enforce: true` cause the main module to automatically import the vendor script when it is loaded? It looks like `enforce` is only relevant in determining whether the chunk is _created_, though I could be reading it wrong. 

In any case, I really appreciate your help. If you have any other suggestions, I'd love to hear them. I'll probably play around with adding a top level `import` for the vendor bundle in the entry file. I wouldn't be thrilled about this solution, however -- Given that the vendor bundle is created by webpack, it seems to me that our source files used by that same webpack process shouldn't know anything about it 🤔

**Comment by evilebottnawi** [comment]
Don't split library, you will potentially lose tree shaking and many other optimizations

If you don't want to add this to HTML, use JS to load this.

**Comment by cymptom** [comment]
This is probably a bit of a hack, but I think I've more or less managed to accomplish what I wanted by including the vendor bundle as an `entry` and excluding it from bundling by defining it in `externals`. Feels dirty, but it seems to work as intended:
```
entry: {
	"guid-generator": [
		"dist/vendor/index.js",
		"../lib/guid-generator/src/index.ts"
	]
},
externals: {
	"dist/vendor/index.js": "dist/vendor/index.js"
}
```

> Don't split library, you will potentially lose tree shaking and many other optimizations

Yeah, I realize that doing it this way isn't ideal. But, I'm working in a legacy application with sprawling front-end code that just isn't in a state where I could easily begin bundling the site code directly. 

My goal at the moment is to avoid pulling in the entirety of vendor scripts (what I'm doing currently), and instead author libraries that consume vendor scripts and expose a vendor-agnostic interface for the application to use. When bundled with webpack, tree shaking _should_ strip away the parts of the vendor scripts that aren't used by the library, correct?

In the `guid-generator` project, for example -- the vendor chunk generated by webpack includes `v4` from the `uuid` node module, since it is used by the library, but excludes `v1`, `v2`, `v3`, etc.

To your point, though, this method leaves me with no way of excluding (tree shaking) the parts of my library that aren't used by the app. I'm fine with that compromise, for now, given the limitations of the legacy code I'm working in, and the fact that the libraries will already be tailored for use in my product and shouldn't contain much code that isn't used by my applications, anyway.

**Comment by GouJieShinee** [comment]
@cymptom hi,how you fixed the problem? I use splitChunks to split library meet the same problem.

**Comment by GouJieShinee** [comment]
@cymptom manually you fixed this problem by add vender files to entry ? do you has a greater way to fixed it ?
