### ISSUE TITLE
Upgrade to fsevents 2

### ISSUE THREAD

**Issue by long76** [webpack/webpack#11162]
# Bug report

**What is the current behavior?**
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.

**If the current behavior is a bug, please provide the steps to reproduce.**
`npm install --save-dev webpack`

**What is the expected behavior?**
no warn

**Other relevant information:**
webpack version:  4.43.0
Node.js version: 12.18.2
Operating System: Windows 8.1 x64
Additional tools:

**Comment by evilebottnawi** [comment]
You need so install latest `chokidar` manually, just run `npm i -D chokidar`
