### ISSUE TITLE
ES6 support?

### ISSUE THREAD

**Issue by remimarenco** [webpack/webpack#1116]
Hi guys!

I had this error when I tried to use some ES6 code:

`ERROR in ./src/scripts/components/report.js
Module parse failed: /home/remi/_Dev/JsCoverageQC/node_modules/react-hot-loader/index.js!/home/remi/_Dev/JsCoverageQC/node_modules/jsx-loader/index.js?harmony!/home/remi/_Dev/JsCoverageQC/node_modules/jsxhint-loader/index.js!/home/remi/_Dev/JsCoverageQC/src/scripts/components/report.js Line 134: Unexpected token [
You may need an appropriate loader to handle this file type.
| 			// Used to change immutable data : https://facebook.github.io/react/docs/update.html
| 			var objVariantChecked_ToAdd = {
| 				[key]: {
| 					$set: variant
| 				}
 @ ./src/scripts/components/JsCoverageQcApp.js 15:13-32`

I guess this is related to ES6 and I have found an [opened issue](https://github.com/webpack/webpack/issues/532) who seems to address this problem.

Could you guys confirm this? Or is it related to another problem?

If this is the problem, how do you think I can resolve this?

**Comment by Sinewyk** [comment]
Confirmed, you have to wait for webpack 2 or fork it and switch from esprima to esprima-fb in the package.json. Did it to test, and works quite well.

You can close this ^^.

**Comment by remimarenco** [comment]
By the time, I looked deep further into this and found [babel-loader](https://github.com/babel/babel-loader) [supports Computed Property Names](http://kangax.github.io/compat-table/es6/).

I replaced it by the js-loader I used before and it works well!

Thanks @Sinewyk ;)
