### ISSUE TITLE
Build time degradation in webpack@5.0.0-beta.22

### ISSUE THREAD

**Issue by shivam-kantival-mt** [webpack/webpack#11163]
# Bug report

**What is the current behavior?**
I have seen a huge increase in production build times after moving to Webpack-beta:22
`Webpack-beta:22 | 960sec
`
instead of

`Webpack 4.43.0 | 180sec`

I can figure out the issue being related to TerserPlugin taking too much time.

**If the current behavior is a bug, please provide the steps to reproduce.**
I recorded build process profiles using `cpuprofile-webpack-plugin` for both Webpack versions with/without source maps enabled.

https://drive.google.com/drive/folders/1JTh-HgNZ2YI1m4ayVEAjygjQ9h8CkNYb?usp=sharing

**What is the expected behavior?**
Build times should not rise too much beyond that of v4.

**Other relevant information:**
webpack version:  5.0.0-beta.22
Node.js version: 10.15.0
Operating System: MacOS 10.14.6

Terser config 

> new TerserPlugin({

          terserOptions: {
            parse: {
              // We want terser to parse ecma 8 code. However, we don't want it
              // to apply any minification steps that turns valid ecma 5 code
              // into invalid ecma 5 code. This is why the 'compress' and 'output'
              // sections only apply transformations that are ecma 5 safe
              // https://github.com/facebook/create-react-app/pull/4234
              ecma: 8,
            },
            compress: {
              ecma: 5,
              warnings: false,
              // Disabled because of an issue with Uglify breaking seemingly valid code:
              // https://github.com/facebook/create-react-app/issues/2376
              // Pending further investigation:
              // https://github.com/mishoo/UglifyJS2/issues/2011
              comparisons: false,
              // Disabled because of an issue with Terser breaking valid code:
              // https://github.com/facebook/create-react-app/issues/5250
              // Pending further investigation:
              // https://github.com/terser-js/terser/issues/120
              inline: 2,
            },
            mangle: {
              safari10: true,
            },
            // Added for profiling in devtools
            keep_classnames: isEnvProductionProfile,
            keep_fnames: isEnvProductionProfile,
            output: {
              ecma: 5,
              comments: false,
              // Turned on because emoji and regex is not minified properly using default
              // https://github.com/facebook/create-react-app/issues/2488
              ascii_only: true,
            },
          },
          sourceMap: envConfigManager.getConfigByKey(ENV_CONFIG_KEYS.SOURCE_MAPS),
        })

**Comment by ScriptedAlchemy** [comment]
Can you provide you’re build configuration and/or an minimum reproducible repo?

**Comment by shivam-kantival-mt** [comment]
Hi we use a dynamic config generator, have uploaded the same to the mentioned [drive folder](https://drive.google.com/drive/folders/1JTh-HgNZ2YI1m4ayVEAjygjQ9h8CkNYb?usp=sharing)

**Comment by evilebottnawi** [comment]
@shivam-kantival-mt What is version of `terser-webpack-plugin`, if it is the problem of terser plugin, let's move it to terser repo

**Comment by evilebottnawi** [comment]
@webpack-bot move to webpack-contrib/terser-webpack-plugin
