### ISSUE TITLE
npm run build webpack error

### ISSUE THREAD

**Issue by AndreyRRiazantsev** [webpack/webpack#11173]
Error while trying to build project for prod

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Imobilko\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.14.6
3 info using node@v12.18.2
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle webpack-config@1.4.0~prebuild: webpack-config@1.4.0
6 info lifecycle webpack-config@1.4.0~build: webpack-config@1.4.0
7 verbose lifecycle webpack-config@1.4.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle webpack-config@1.4.0~build: PATH: C:\Users\Imobilko\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\Imobilko\Desktop\WorkProjects\lawfirm\node_modules\.bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\Imobilko\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files\Git\cmd;C:\xampp\php;C:\composer;C:\Program Files\PuTTY;C:\Program Files\nodejs;C:\Users\Imobilko\AppData\Local\Microsoft\WindowsApps;C:\Users\Imobilko\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Imobilko\AppData\Roaming\Composer\vendor\bin;C:\Users\Imobilko\bin;C:\Users\Imobilko\AppData\Roaming\npm
9 verbose lifecycle webpack-config@1.4.0~build: CWD: C:\Users\Imobilko\Desktop\WorkProjects\lawfirm
10 silly lifecycle webpack-config@1.4.0~build: Args: [ '/d /s /c', 'webpack --progress --hide-modules --mode production' ]
11 silly lifecycle webpack-config@1.4.0~build: Returned: code: 2  signal: null
12 info lifecycle webpack-config@1.4.0~build: Failed to exec build script
13 verbose stack Error: webpack-config@1.4.0 build: `webpack --progress --hide-modules --mode production`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Imobilko\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Imobilko\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid webpack-config@1.4.0
15 verbose cwd C:\Users\Imobilko\Desktop\WorkProjects\lawfirm
16 verbose Windows_NT 10.0.18363
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Imobilko\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v12.18.2
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 2
22 error webpack-config@1.4.0 build: `webpack --progress --hide-modules --mode production`
22 error Exit status 2
23 error Failed at the webpack-config@1.4.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

const path = require('path')
const minJSON = require('jsonminify')
const TerserPlugin = require('terser-webpack-plugin');

const plugins = {
  progress: require('webpackbar'),
  clean: (() => {
    const { CleanWebpackPlugin } = require('clean-webpack-plugin')
    return CleanWebpackPlugin
  })(),
  extractCSS: require('mini-css-extract-plugin'),
  sync: require('browser-sync-webpack-plugin'),
  html: require('html-webpack-plugin'),
  copy: require('copy-webpack-plugin'),
  sri: require('webpack-subresource-integrity')
}

module.exports = (env = {}, argv) => {
  const isProduction = argv.mode === 'production'

  let config = {
    context: path.resolve(__dirname, 'src'),

    entry: [
      './scripts/home.js'
    ],

    output: { path: __dirname + '/build' },

    module: {
      rules: [
        {
          test: /\.scss$/,
          use: [
            {
              loader: 'file-loader',
              options: {
                name: 'css/[name].blocks.css',
              }
            },
            {
              loader: 'extract-loader'
            },
            {
              loader: 'css-loader?-url'
            },
            {
              loader: 'sass-loader'
            }
          ]
        },
        {
          test: /\.js$/,
          exclude: /node_modules/,
          use: {
            loader: 'babel-loader',
            options: {
              presets: [
                '@babel/preset-env'
              ]
            }
          }
        },
        {
          test: /\.(gif|png|jpe?g|svg)$/i,
          exclude: /fonts/,
          use: [
            {
              loader: 'file-loader',
              options: {
                name: '[path][name].[ext]',
                // publicPath: '..' // use relative path
              }
            },
            {
              loader: 'image-webpack-loader',
              options: {
                disable: !isProduction,
                mozjpeg: {
                  progressive: true,
                  quality: 65
                },
                optipng: {
                  enabled: false
                },
                pngquant: {
                  quality: [0.65, 0.90],
                  speed: 4
                },
                gifsicle: {
                  interlaced: false
                },
                webp: {
                  quality: 75
                }
              }
            }
          ]
        },
        {
          test: /.(ttf|otf|eot|svg|woff(2)?)(\?[a-z0-9]+)?$/,
          exclude: /images/,
          use: [{
            loader: 'file-loader',
            options: {
              name: '[name].[ext]',
              outputPath: 'fonts/',
              // publicPath: '../fonts/' // use relative path
            }
          }]
        },
        {
          test: /\.html$/,
          use: {
            loader: 'html-loader'
          }
        }
      ]
    },

    devServer: {
      contentBase: path.join(__dirname, 'src'),
      port: 8080,
      overlay: {
        warnings: true,
        errors: true
      },
      quiet: true
    },

    plugins: (() => {
      let common = [
        new plugins.extractCSS({
          filename: 'styles/[name].css'
        }),
        new plugins.html({
          template: 'index.html',
          filename: 'index.html',
          minify: false
        }),
        new plugins.html({
          template: 'team.html',
          filename: 'team.html',
          minify: {
            removeEmptyAttributes: true,
            removeStyleLinkTypeAttributes: true
          }
        }),
        new plugins.html({
          template: 'about.html',
          filename: 'about.html',
          minify: {
            removeEmptyAttributes: true,
            removeStyleLinkTypeAttributes: true
          }
        }),
        new plugins.html({
          template: 'team_member.html',
          filename: 'team_member.html',
          minify: {
            removeEmptyAttributes: true,
            removeStyleLinkTypeAttributes: true
          }
        }),
        new plugins.html({
          template: 'contact.html',
          filename: 'contact.html',
          minify: {
            removeEmptyAttributes: true,
            removeStyleLinkTypeAttributes: true
          }
        }),
        new plugins.html({
          template: 'departments.html',
          filename: 'departments.html',
          minify: {
            removeEmptyAttributes: true,
            removeStyleLinkTypeAttributes: true,
          }
        }),
        new plugins.html({
          template: 'terms.html',
          filename: 'terms.html',
          minify: {
            removeEmptyAttributes: true,
            removeStyleLinkTypeAttributes: true,
          }
        }),
        new plugins.progress({
          color: '#5C95EE'
        })
      ]

      const production = [
        new plugins.clean(),
        new plugins.copy({
          patterns: [
            {
              from: 'data/**/*.json',
              transform: content => minJSON(content.toString())
            }
          ]
        }),
        new plugins.sri({
          hashFuncNames: ['sha384'],
          enabled: true
        })
      ]

      const development = [
        new plugins.sync(
          {
            host: 'localhost',
            port: 9090,
            proxy: 'http://localhost:8080/'
          },
          {
            reload: false
          }
        )
      ]

      return isProduction
        ? common.concat(production)
        : common.concat(development)
    })(),

    devtool: (() => {
      return isProduction
        ? '' // 'hidden-source-map'
        : 'source-map'
    })(),

    resolve: {
      modules: [path.resolve(__dirname, 'src'), 'node_modules'],
      alias: {
        '~': path.resolve(__dirname, 'src/scripts/')
      }
    },

    stats: 'errors-only'
  }

  return config
}

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
