### ISSUE TITLE
idea: See what ESBuild is doing right

### ISSUE THREAD

**Issue by mysticaltech** [webpack/webpack#11181]
Hello, first of all, thank you for this amazing project, the world's best. I will admit that I am mostly ignorant on the inner workings of Webpack but this is just an idea I wanted to share. 

I know that WP 5 has made huge improvements when it comes to build times, but there is a specific project written in Golang, https://github.com/evanw/esbuild that is out-of-this-world fast, obviously they are doing something right.

Snowpack, and Vite your latest competitors are using it and hence are extremely fast too. I was wondering if the next iterations of WP could inspire itself from ESBuild to make build times even faster.

That's all, thanks and keep up the wonderful work.

**Comment by evilebottnawi** [comment]
Interesting project, maybe we have something to see there, especially in parallelism

**Comment by egoist** [comment]
Snowpack and Vite are fast but that's mainly because they do no bundling during development.

**Comment by evilebottnawi** [comment]
@egoist i think we can use it to traspile typescript and ES next syntax (babel)

**Comment by egoist** [comment]
@evilebottnawi yeah I actually made a loader: https://github.com/egoist/esbuild-loader

But I guess what makes webpack slow is the bundling process.

**Comment by evilebottnawi** [comment]
@egois, interesting, need investigate, maybe problem in parallel?

**Comment by ZuBB** [comment]
Any chance Webpack team will look into this? especially after v5 is out

**Comment by sokra** [comment]
We are always watching what other tools are doing...

**Comment by natew** [comment]
@sokra thoughts on esmodule mode that avoids bundling but still supports HMR? I believe there should be some big wins for HMR speed by doing that.
