### ISSUE TITLE
BannerPlugin does not work correctly with AngularCompilerPlugin 

### ISSUE THREAD

**Issue by ewaDev** [webpack/webpack#11187]
# Bug report

**What is the current behavior?**
When ngToolsWebpack AngularCompilerPlugin is used with webpack BannerPlugin, BannerPlugin adds text to minified components and they appear in the ui. They are interpreted as normal text in the html template and therefore are displayed. 

Interestingly, even when the exclude option is selected and all entry points are excluded, the comments are still added to the components.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Add banner plugin into webpack js file
2. Add banner text ( for example Banner : "hello world") 
3. Set up AngularCompilerPlugin
4. Run webpack
5. You will see text when components are added.

webpack config here: https://gist.github.com/ewaDev/d5f8ae7e4153eacbc524ce4bec5d8f8e

**What is the expected behavior?**
The banner should only be inserted on top of files.

**Other relevant information:**
webpack version:  4.43.0
Node.js version:  12.13.0
Operating System: Windows
Additional tools:

**Comment by evilebottnawi** [comment]
I think you should open an issue `AngularCompilerPlugin` repo, looks like it is used hook before `BannerPlugin`

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/angular/angular-cli/issues/18282, feel free to feedback if problem(s) will be with webpack itself (I will reopen the issue), but I can't reproduce too
