### ISSUE TITLE
[webpack 5] Identifier of ?. is not correctly parsed

### ISSUE THREAD

**Issue by SunriseFox** [webpack/webpack#11186]
# Bug report

**What is the current behavior?**

acorn's ChainExpression is not correctly parsed. Variables are not correctly resolved to imports when optional chaining is used.

```javascript
import test from './test';

console.log(test.a)
console.log(test?.a)
```

compiles to

```javascript
/* harmony import */ var _test__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./test */ "./src/test.js");


console.log(_test__WEBPACK_IMPORTED_MODULE_0__.default.a)
console.log(test?.a)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/SunriseFox/webpack-bug-optional-chaining

`yarn && yarn start`

**What is the expected behavior?**

should be 

```
/* harmony import */ var _test__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./test */ "./src/test.js");


console.log(_test__WEBPACK_IMPORTED_MODULE_0__.default.a)
console.log(_test__WEBPACK_IMPORTED_MODULE_0__.default?.a)
```

**Other relevant information:**
webpack version:  5.0.0-beta.22
Node.js version: v12.16.3
Operating System: MacOS 10.15.5
Additional tools: none

**Comment by evilebottnawi** [comment]
On board https://github.com/webpack/webpack/projects/5#card-37921062

**Comment by vankop** [comment]
@sokra FYI working on this..
