### ISSUE TITLE
in a package.json having a jam.main entry takes precidents over a main

### ISSUE THREAD

**Issue by calvinmetcalf** [webpack/webpack#1118]
If a dependency has an entry for [jam](https://github.com/caolan/jam) in a package.json which has a main entry that differs from the parent main entry webpack inexplicably uses the jam one, e.g.

``` json
"main": "lib/index.js",
  "jam": {
    "main": "dist/build.js"
  },
```

`dist/build.js` is chosen as the entry point instead of `lib/index.js` 

Since jam was meant to be for AMD modules not commonjs this leads to warning from webpack (see calvinmetcalf/lie#22) as those tend to be prebuilt files.  I'm not sure this is the behavior  you want espetially as I don't think jam really in active development anymore (cc @caolan) though it does lead to the work around of just removing jam support.

**Comment by shama** [comment]
A workaround is to set the `resolve.packageMains` in your config to exclude jam: `["webpack", "browser", "web", "browserify", "main"]`. See: http://webpack.github.io/docs/configuration.html#resolve-packagemains

But +1 for removing `jam.main` as a default.

**Comment by SpaceK33z** [comment]
Closing this since remove `jam.main` has been removed in webpack v2.
