### ISSUE TITLE
[Webpack 5] Dynamic import is not working with promise externals

### ISSUE THREAD

**Issue by roblan** [webpack/webpack#11197]
# Bug report

**What is the current behavior?**

~~`__webpack_require__` is called with result of promise external when it's is loaded as dynamic import, which results with error~~
webpack it threating resolved value as module id with dynamic imports witch results with
```
Uncaught (in promise) TypeError: __webpack_modules__[moduleId] is not a function
```

webpack generated code (added line breaks for clarity):
```
Promise.resolve(/*! import() */)
.then(__webpack_require__.bind(__webpack_require__, /*! promise-external */ "promise-external"))
.then((m) => __webpack_require__.t(m, 7))
.then(console.log);
```

~~part `.then((m) => __webpack_require__.t(m, 7))` seems to be unnecessary.~~

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/roblan/webpack-external-promise-import

webpack config:
```
module.exports = {
	externals: {
		"promise-external": "promise Promise.resolve(42)",
	},
	experiments: {
		importAsync: true
	}
};
```
src/index.js
```
import('promise-external').then(console.log);
```

**What is the expected behavior?**

~~`__webpack_require__` should not be called on promise external result~~

~~webpack should generate code without second `__webpack_require__ ` call:~~
```
Promise.resolve(/*! import() */)
.then(__webpack_require__.bind(__webpack_require__, /*! promise-external */ "promise-external"))
.then(console.log);
```

webpack should resolve dynamic import with `{ default: 42 }`

**Other relevant information:**
webpack version:  5.0.0-beta.22
Node.js version: v14.4.0
Operating System: MacOS 10.15.6
Additional tools: -

**Comment by sokra** [comment]
That part wraps the result in a namespace object as `import()` always returns a namespace object. Here it would return `{ default: 42 }`

**Comment by roblan** [comment]
You are right - my expected behavior part is wrong, but either way it does not work as expected.

**Comment by sokra** [comment]
Yeah there really seems something wrong here. The generated code should be `__webpack_require__.t(m, 6)` instead of 7

**Comment by sokra** [comment]
If someone wants to send a PR the problem is somewhere in `RuntimeTemplate.js` probably in `namespacePromise`

**Comment by chenxsan** [comment]
Unfortunately I found it's more complex than I expected to fix it, I'm going to close my pull request so anyone interested in it can continue.
