### ISSUE TITLE
How to send file from node.js to frontend reactjs, by using __dirname?

### ISSUE THREAD

**Issue by murtazahassani69** [webpack/webpack#11204]
Hey, dear friends, I'm trying to create a contact form in reactJs, send email & receive from it, fore backend I use node.js, and I need to send a file from node.js to react.js, for that I've created a ContactScree.js in front-end/src/screens/folder in react.js, the point is this can I send file to a .js file?

**Comment by sokra** [comment]
Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md).

**Comment by murtazahassani69** [comment]
I tried but I can't post a question because asked a lot of question
