### ISSUE TITLE
[Webpack 5] Error: EMFILE, too many open files in watch mode

### ISSUE THREAD

**Issue by rramaa** [webpack/webpack#11203]
# Bug report

**What is the current behavior?**
When I run webpack 5 in watch mode(or webpack-dev-server), webpack compiles my project successfully, but then I start getting the error `Error: EMFILE, too many open files in watch mode`. The terminal tab gets stuck and I am not able to close the process by using (`ctrl`+`c`). I have to close the terminal tab

**If the current behavior is a bug, please provide the steps to reproduce.**
I investigated and found that the bug is due to this plugin [WatchMissingNodeModulesPlugin](https://github.com/facebook/create-react-app/blob/4784997f0682e75eb32a897b4ffe34d735912e6c/packages/react-dev-utils/WatchMissingNodeModulesPlugin.js). It used to work correctly with Webpack 4. On removing this plugin, everything works correctly. 
I think the issue is when webpack tries to watch large number of files

**What is the expected behavior?**
Webpack's watch should not fail with the above mentioned error.

**Other relevant information:**
webpack version:  5.0.0-beta.22
Node.js version: v12.17.0
Operating System: MacOS 10.15.6

**Comment by sokra** [comment]
I don't think you need that plugin with webpack 5. It should watch missing node_modules by default

**Comment by rramaa** [comment]
Thanks @sokra !
Webpack rebuild's the project on changes to `node_modules`, but it logs that no changes were found.

I was able to fix this behavior, by setting `cache.managedPaths = []`.

However, I was not able to find this in the migration guide. It was more of a hit and trial. It would be helpful if this was included in the guide

**Comment by evilebottnawi** [comment]
> Webpack rebuilds the project on changes to node_modules, but it logs that no changes were found.

What do you mean?

**Comment by rramaa** [comment]
<img width="314" alt="Screenshot 2020-08-03 at 5 16 05 PM" src="https://user-images.githubusercontent.com/16651792/89179367-31d01380-d5ad-11ea-89bc-3385a6dcc205.png">

This is the exact log which I am getting on updating a `node_module`.

On adding `cache.managedPaths = []`, everything works and updates as expected.

I am using `webpack-dev-server@3.11.0`

**Comment by evilebottnawi** [comment]
Because nothing to change?

**Comment by rramaa** [comment]
Nope

The change I made was not something that would not affect the final output of the code(It was a logical change).
Webpack gave the above mentioned log and did not update the code(even after reloading the browser)

However, after adding this line(`cache.managedPaths = []`) and making the same change, webpack detected the change and the hot update worked as well

**Comment by rramaa** [comment]
This issue is reproducible. I have created a minimum reproducible example [here](https://github.com/rramaa/minimal-webpack-issue-reproduction).

Steps to setup:
1. `yarn`
2. `yarn start`
3. Navigate to  [http://localhost:8080/](http://localhost:8080/)

Expected output => `["extract","parse","stringify","parseUrl","stringifyUrl"]`

Steps to reproduce:
1. Make changes to `node_modules/query-string/index.js` file
2. Add `exports.abcd = "test"` (or anything else).
3. Observe the console in the browser.
4. The output in the browser does not change.

Add this line(`cache.managedPaths = []`) in `webpack.config.js`(or just uncomment the cache block), and repeat the above steps. The output in the browser changes

**Comment by sokra** [comment]
> 1. Make changes to `node_modules/query-string/index.js` file

webpack assumes you don't make any manual changes to any file in `cache.managedPaths` (`node_modules` by default).
This is a performance optimization and works in pratice where you use `npm` or `yarn` to install packages in node_modules.

There is a note in the changelog: https://github.com/webpack/changelog-v5#persistent-caching

So this is working as expected.

**Comment by rramaa** [comment]
Got it
Must have missed it...I was actually having the original issue when symlinking packages.

Thanks!

**Comment by sokra** [comment]
Symlinked packages are excluded from this as their resolved path is outside of node_modules (except when you disable symlink handling with `resolve.symlinks: false`, which shouldn't be done).

So there shouldn't be a caching issue with these.

**Comment by evilebottnawi** [comment]
@rramaa Can you try latest watchpack@beta with latest webpack@beta?

**Comment by rramaa** [comment]
@evilebottnawi will do

**Comment by evilebottnawi** [comment]
@rramaa we are fix even more problems in latest beta release, I would like to know if the problem was solved?

**Comment by rramaa** [comment]
yes @evilebottnawi the problem was resolved
thanks!

**Comment by evilebottnawi** [comment]
Let's close, if somebody will faced with the same issue feel free to open the new issue with reproducible test repo/configurations/screenshots/videos/etc, sometimes it is hard to fix these problems
