### ISSUE TITLE
webpack@4 watch recompiles many times after fs.writeFileSync

### ISSUE THREAD

**Issue by Loonride** [webpack/webpack#11219]
# Bug report

**What is the current behavior?**

For webpack@4, running watch on a file that was just written to with fs.writeFileSync will cause many repeated compilations, even though the file remains the same between those compilations.

This does not happen with webpack@5. It is difficult behavior to work with for e2e testing in webpack-dev-server, because it makes it hard to simulate a user editing a file and waiting for a reload.

**If the current behavior is a bug, please provide the steps to reproduce.**

See: https://github.com/Loonride/webpack-write-done-hook

run `npm install`, then `node index.js`. You will see many compilations happen, even though the file was written before the compilation even started.

If you install webpack@next, it will work without problems

**What is the expected behavior?**

If a file was written before a compilation is started, it should not impact the compilation.

**Other relevant information:**
webpack version:  v4
Node.js version: 13.12.0
Operating System: Ubuntu 20.04
Additional tools:

**Comment by sokra** [comment]
Filesystem accuracy of timestamps on disk make it difficult to see if the file has changed again without a watcher attached.
When we are unsure we better compile again. You can check if the build has the same hash compared to the previous build.

**Comment by evilebottnawi** [comment]
bump, I think we can improve this in webpack@5

**Comment by bertho-zero** [comment]
I have this problem since I updated to webpack 5, sometimes `(repeated 0 times)`, sometimes `(repeated 1 times)`.

**Comment by evilebottnawi** [comment]
@bertho-zero Can you provide reproducible test repo?

**Comment by bertho-zero** [comment]
I'm in a huge monorepo, it's complicated for me to reduce it to a minimal repro.

**Comment by evilebottnawi** [comment]
@bertho-zero without reproducible test repo we can't help, sorry, maybe bug in plugins
