### ISSUE TITLE
Webpack doesn't recognize package.json main attribute

### ISSUE THREAD

**Issue by Luke-zhang-04** [webpack/webpack#11217]
# Bug report

**What is the current behavior?**
WebPack does not resolve modules from the `main` attribute in the `package.json` files in `node_modules`

**If the current behavior is a bug, please provide the steps to reproduce.**
Import or require a module from `node_modules` that has an `src` or `lib` folder (or equivalent) and a `main` attribute, and the modules won't resolve properly. That's how I get errors such as:
`Uncaught TypeError: [library].default is not a constructor` which only is fixed when I use `require` like so: `require("[lib-name]/src")`.

**What is the expected behavior?**
Modules are imported directly from the directory specified by the `main` attribute in the `pacakge.json` files such that the usage of `require` can be done without specifying `src` or `lib`.

You can find a test repo [here](https://github.com/Luke-zhang-04/temporary-webpack-test-repo)

Demo of bugs here [here](https://luke-zhang-04.github.io/temporary-webpack-test-repo/). Open dev tools and open console.

As you can see, scripts 2 and 4 both work, because they specify the `lib` directory, while script and script3 don't work, even though "lib" is specified as "main".

[here](https://github.com/Luke-zhang-04/DeStagnate/blob/master/package.json) is the package.json of the library library that is causing the error.

**Other relevant information:**
webpack version: 4.43.0 
Node.js version: 12.13.1
Operating System: darwin19
Additional tools: TypeScript

**Comment by evilebottnawi** [comment]
Please provide reproducible test repo, we have tests for `main` property of `package.json`

**Comment by Luke-zhang-04** [comment]
I was just thinking, could it be that the main attribute needs to specify a file and not a directory?

**Comment by Luke-zhang-04** [comment]
> Please provide reproducible test repo, we have tests for `main` property of `package.json`

I've added those in my issue above

**Comment by vankop** [comment]
main field works, in your example for bare specifier `destagnate` browser field is taken, you can check this in resulted bundle

**Comment by evilebottnawi** [comment]
Answer above, you can change behavior using this option https://webpack.js.org/configuration/resolve/#resolvealias
