### ISSUE TITLE
Imports are routed to different builds of the same package.

### ISSUE THREAD

**Issue by SukantPal** [webpack/webpack#11213]
# Bug report

**What is the current behavior?**

I have an app that imports both `pixi.js` and `pixi-batch-renderer`. `pixi-batch-renderer` imports classes from `pixi.js` as well.

The resulting bundle has two pixi.js instances - one from the ESM build (required from the app itself), and one from the CJS build (required from pixi-batch-renderer). (required means `require()` inside the bundle).

This should not be the case - webpack should only bundle the ESM version.

**If the current behavior is a bug, please provide the steps to reproduce.**

The full reproduction is here: https://github.com/SukantPal/webpack-duplicate-bundle

I've given more details there.

**What is the expected behavior?**

Only one version of pixi.js should be bundled.

**Other relevant information:**
webpack version:  4.42.0
Node.js version: 12.7.0
Operating System: macOS Catalina
Additional tools: N/A

**Comment by evilebottnawi** [comment]
Here problem https://github.com/webpack/webpack/issues/5756#issuecomment-335093480, workaround https://github.com/webpack/webpack/issues/5756#issuecomment-405468106

**Comment by SukantPal** [comment]
@evilebottnawi The problem isn't that `module` gets prioritized over `main`. It is that `main` is being prioritized over `module`.

**Comment by sokra** [comment]
In .mjs files only `main` is used. Node.js defined .mjs so we are keeping strictly with the node.js behavior.

**Comment by SukantPal** [comment]
Should I should change it to .es.js I think? Thanks!
