### ISSUE TITLE
Ability to force bundling of a module

### ISSUE THREAD

**Issue by younabobo** [webpack/webpack#11223]
## Feature request

**What is the expected behavior?**
Ability to force bundling of a module

**What is motivation or use case for adding/changing the behavior?**
It is impossible to dynamically import a module using import(moduleName) with moduleName being a variable

**How should this be implemented in your opinion?**
In settings, there should be an array of bundled modules, the modules within it will be bundled even if they're not required in the project itself

**Are you willing to work on this yourself?**
no

**Comment by evilebottnawi** [comment]
What do you mean? Please clarify

**Comment by younabobo** [comment]
https://github.com/younabobo/webpack-dynamic-import-test
Details are in README.md

**Comment by evilebottnawi** [comment]
Do not duplicate issue https://github.com/webpack/webpack/issues/8934#issuecomment-663237983
