### ISSUE TITLE
Building React with Antd  project in production causing error using webpack v4.44.0

### ISSUE THREAD

**Issue by liho98** [webpack/webpack#11238]
# Bug report

**What is the current behavior?**
`"build": "NODE_ENV=production webpack -p --config webpack.config.prod.js"`
```
vendors~app.1119d1fb9353e3bd9353.js:77 Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at xu (vendors~app.1119d1fb9353e3bd9353.js:77)
    at d (vendors~app.1119d1fb9353e3bd9353.js:77)
    at v (vendors~app.1119d1fb9353e3bd9353.js:77)
    at vendors~app.1119d1fb9353e3bd9353.js:77
    at ji (vendors~app.1119d1fb9353e3bd9353.js:77)
    at mc (vendors~app.1119d1fb9353e3bd9353.js:77)
    at lu (vendors~app.1119d1fb9353e3bd9353.js:77)
    at cu (vendors~app.1119d1fb9353e3bd9353.js:77)
    at Zc (vendors~app.1119d1fb9353e3bd9353.js:77)
    at vendors~app.1119d1fb9353e3bd9353.js:77
```
![image](https://user-images.githubusercontent.com/44250267/88613214-90822280-d0bf-11ea-88dd-461a505b919d.png)

Trying with -d option its working fine.
"build": "NODE_ENV=development webpack -d --config webpack.config.prod.js"

**If the current behavior is a bug, please provide the steps to reproduce.**
- Create a react project with antd v4.0.0 and use the form components with the syntax getFieldDecorator().
```
            <FormItem label="Type" labelCol={{ span: 7 }} wrapperCol={{ span: 17 }}>
              {getFieldDecorator('type', {
                initialValue: 'DYNAMIC',
                rules: [
                  {
                    required: true,
                    message: 'Please select type!',
                  },
                ],ﬁ
              })(
                <RadioGroup>
                  <RadioButton value="DYNAMIC">Dynamic</RadioButton>
                  <RadioButton value="STATIC">Static</RadioButton>
                </RadioGroup>,
              )}
            </FormItem>
```
- Adding -p option to build the react project. 

**What is the expected behavior?**
 It should be working fine as webpack version v4.43.0.

**Other relevant information:**
webpack version:  v4.44.0
Node.js version: v12.16.1
Operating System: macOS Catalina 10.15.4
Additional tools: Antd v4.0.0

**Comment by evilebottnawi** [comment]
Duplicate https://github.com/webpack/webpack/issues/11234, please use search before post the issue

**Comment by liho98** [comment]
> Duplicate #11234, please use search before post the issue

Because that post https://github.com/webpack/webpack/issues/11234 did not mention the steps to reproduce the error and how to get the error and the tools were using, at least my post is clearly stated.

**Comment by liho98** [comment]
Since the post #11234 did not mention the steps to reproduce the error, how to obtain the error and the tool being used, but at least my post clearly stated.
In addition, the title is different, my post clearly states that building React with Antd project in production causing error using webpack v4.44.0, and I don’t know anything in that post...
here is the reproduce test repo - https://github.com/liho98/webpack-4.44.0-bug
Its ok, if you did not follow up this post, Thank you 🙃
