### ISSUE TITLE
SyntaxError: Unexpected token :     at Module._compile (internal/modules/cjs/loader.js:723:23) Eventhough webpack is set correctly

### ISSUE THREAD

**Issue by SS88** [webpack/webpack#11239]
I have installed webpack using npm and configured the config like follows : 
```
module.exports = {
  module: {
    rules: [
      { test: /\.css$/, use: 'css-loader' },
      { test: /\.css$/, use: 'style-loader' }
    ]
  }
};

but when i import my bootstrap.css into my jsx file i get this error : 

`SyntaxError: Unexpected token :     at Module._compile (internal/modules/cjs/loader.js:723:23) 

Why ?
Thanks !
````

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by evilebottnawi** [comment]
Here simple example https://github.com/webpack-contrib/css-loader#assets
