### ISSUE TITLE
Regression in 4.44.0: minified code error

### ISSUE THREAD

**Issue by pdeva** [webpack/webpack#11234]
# Bug report

**What is the current behavior?**
seeing this error in minified version of code:

```
console error: Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

code works fine in:
- non-minified version
-  when compiled with 4.43.0 of webpack 

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

no exceptions

**Other relevant information:**
webpack version:  4.44.0
Node.js version: 
Operating System: 
Additional tools:

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by evilebottnawi** [comment]
I think here problem with something new with react and terser, without reproducible test repo, we can't help

**Comment by cfaherty** [comment]
FWIW I've just had an upgrade to 4.44.0 (from 4.43.0) begin causing failed production builds.. in my project complaints about the aws-amplify module. Sorry for the anecdotal response.

**Comment by evilebottnawi** [comment]
**Please** create reproducible test repo, otherwise issue will be closed

**Comment by sokra** [comment]
Duplicate of #11243
