### ISSUE TITLE
Support graaljs target

### ISSUE THREAD

**Issue by abnud1** [webpack/webpack#11233]
## Feature request

**What is the expected behavior?**
I expect to set `target: "graaljs"` or similar and the bundled code will work on GraalVM without any issues

**What is motivation or use case for adding/changing the behavior?**
Right Now We have a react app bundled using webpack and We're doing server-side rendering using GraalVM polyglot api in which we call javascript code from JVM language(in our case kotlin but could be java) because that's the language our Backend is built in and we don't want to invest in nodejs.

**How should this be implemented in your opinion?**
Currently we're using `target: "web"` and some polyfills for some node modules but not all node modules are polyfillable and `target: "web"` breaks on Graaljs when using dynamic import because the `window` object is used.

So maybe we could apply the same plugins applied to web target with some modifications, libraries will probably work because they already target the web, even react ssr works except ofcourse `renderToStream` but we don't need to support such cases.

**Are you willing to work on this yourself?**
No

**Comment by evilebottnawi** [comment]
> Currently we're using target: "web" and some polyfills for some node modules but not all node modules are polyfillable and target: "web" breaks on Graaljs when using dynamic import because the window object is used.

We avoid polyfills for webpack@5

What is global object for `Graaljs`?

**Comment by sokra** [comment]
Graaljs has a node.js compatible mode. Try to use that with `target: "node"`

**Comment by abnud1** [comment]
@sokra that mode can't be used from java with the "Context API" right ?

**Comment by evilebottnawi** [comment]
bump

**Comment by nicobrinkkemper** [comment]
@[abnud1](https://github.com/abnud1) could you share an example configuration of webpack to use with graal polyglot context?
