### ISSUE TITLE
Problem with first load app.js

### ISSUE THREAD

**Issue by xaru123** [webpack/webpack#11241]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
Is there an instruction to optimize app.js size? the first download of a 5.5 MB file takes 10 seconds. which is very long. can someone tell me what to look for?

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Maybe it is ok. but i think it is not fast at all.

It is my  webpack.mix.js

```
const mix = require('laravel-mix');
mix.autoload({
    jquery: ['$', 'window.jQuery', "jQuery", "window.$", "jquery", "window.jquery"]
});

mix.webpackConfig({
    output: {
        chunkFilename: 'js/chunk/[name].js'
    }
    
});

mix.options({ processCssUrls: true })
    .js('resources/js/app.js', 'public/js')
    .sass('resources/sass/app.scss', 'public/css')
    .copyDirectory('resources/layout', 'public/layout')//шаблон
    .copyDirectory('resources/images', 'public/img')
    .copyDirectory('resources/css/template', 'public/css/template')
    .copyDirectory('resources/css/dashboard', 'public/css/dashboard')
    .copyDirectory('resources/css/report', 'public/css/report')
    .copyDirectory('resources/css/arm', 'public/css/arm')
    .copyDirectory('resources/js/dashboard', 'public/js/dashboard')
    .copyDirectory('resources/js/common', 'public/js/common')
    .copyDirectory('resources/js/report', 'public/js/report')
    .copyDirectory('resources/js/arm', 'public/js/arm')
    .copyDirectory('resources/js/module', 'public/js/module')
    .copyDirectory('resources/media', 'public/media')
    .copyDirectory('resources/vendors', 'public/vendors')
    .copyDirectory('resources/instruction', 'public/instruction')
```

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
webpack version: last
Laravel, vue
Operating System: Whatever

**Comment by evilebottnawi** [comment]
Please open an issue in `laravel-mix` repo
