### ISSUE TITLE
webpack appears to be missing the stats.preset option in the config schema

### ISSUE THREAD

**Issue by avinoamsn** [webpack/webpack#11242]
# Bug report

**What is the current behavior?**

Webpack errors out during compilation when the `stats.preset` option is set. This is the error returned:

```console
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.stats has an unknown property 'preset'. These properties are valid:
   object { all?, assets?, assetsSort?, builtAt?, cached?, cachedAssets?, children?, chunkGroups?, chunkModules?, chunkOrigins?, chunks?, chunksSort?, colors?, context?, depth?, entrypoints?, env?, errorDetails?, errors?, exclude?, excludeAssets?, excludeModules?, hash?, logging?, loggingDebug?, loggingTrace?, maxModules?, moduleAssets?, moduleTrace?, modules?, modulesSort?, nestedModules?, optimizationBailout?, outputPath?, performance?, providedExports?, publicPath?, reasons?, source?, timings?, usedExports?, version?, warnings?, warningsFilter? }
````

Notably, `preset` is missing from this list.

**If the current behavior is a bug, please provide the steps to reproduce.**

Webpack config in question:

```javascript
module.exports = {
	stats: {
		preset: `minimal`,
	}
	...
}
```

**What is the expected behavior?**

Webpack should compile successfully and print the correct output based on the `stat` config options.

**Other relevant information:**
webpack version:  4.44.0
Node.js version: v14.5.0
Operating System: Windows Subsystem for Linux

**Comment by evilebottnawi** [comment]
It is only for webpack@5

**Comment by avinoamsn** [comment]
@evilebottnawi thank you for the clarification. It would be nice if this information were featured more prominently on the site (e.g. not only in small, cutoff font at top and bottom of the sidebar). Alas.
