### ISSUE TITLE
[Webpack 5] Module Federation loading remote module several places overrides load event callback causing 2 minute delay

### ISSUE THREAD

**Issue by jandvik** [webpack/webpack#11247]
# Bug report

**What is the current behavior?**
Loading the same federated remote module twice causes a 2 minute delay in app.

**If the current behavior is a bug, please provide the steps to reproduce.**
Git repo to reproduce issue: https://github.com/jandvik/webpack-module-federation-issue

App configuration:
- app-container (host app)
- home (page app)
- search (page app)
- nav (library/component app)

Federated Module usage:
```
app-container
  - home
    - nav
  - search
    - nav
```

To make the error go away, comment out lines 10-12 in packages/search/src/App.tsx
OR comment out line 31 in packages/app-container/src/App.tsx in https://github.com/jandvik/webpack-module-federation-issue

**What is the expected behavior?**
There should be no delay in loading from two federated modules using the same shared library remote module.

**Other relevant information:**
webpack version:  5.0.0-beta.22
Node.js version: 10.16.3
Operating System: Windows 10
Additional tools:

**Comment by jandvik** [comment]
Pulling over quote from https://github.com/webpack/webpack/issues/10352#issuecomment-665914841 for reference

> @jandvik It's a webpack bug.
> 
> The script loading attaches a load event but overrides the load event callback from the other remote.
> 
> If you want to send a PR see load script runtime module and make sure to keep the old callbacks.

**Comment by jandvik** [comment]
@sokra @evilebottnawi  - I hope I did this right ... here's the PR https://github.com/webpack/webpack/pull/11248

Maybe not the prettiest solution, and I'm open to suggestions. The core of the issue is that each loader has the "inProgress" scoped within its own execution, so when another federated module loads the same - the script exists, but there's no reference to the other callbacks for execution.

I'm honestly not too familiar with the inner workings of Webpack, or if theres another way to globally share information within webpack.

**Comment by davidtranjs** [comment]
This issue still happen 😢
