### ISSUE TITLE
Tapable applyPluginsAsync vs applyPluginsParallel?

### ISSUE THREAD

**Issue by anyong** [webpack/webpack#1124]
So I was having some major issues getting webpack to watch multiple option objects in gulp. I was digging through the code for a few hours and ended up with a working solution, which is to change the applyPluginsParallel to applyPluginsAsync on [this line](https://github.com/webpack/webpack/blob/18f3595cdefd9682ca5dff55a6d3a9712985ec39/lib/Compiler.js#L392)

Can anyone explain why this works and if it is a bug or not? I'm pretty clueless here but I've got my gulp file working again (it worked before recent updates), so I'll stick with changing it manually for now...

**Comment by sokra** [comment]
Can you post your gulpfile?

**Comment by anyong** [comment]
Will do from computer later (on mobile) but basically its:

```
gulp.task('client', function(){
    webpack(config).watch(100, callback);
});
```

And then another one the same with a different config object, finally:

```
gulp.task('watch', ['client', 'server']);
```

Config objects just have some normal options set and Babel loader, nothing
fancy.

**Comment by sokra** [comment]
where does `config` come from? do client and server share (a part of) the config?
Where does `callback` come from?

**Comment by anyong** [comment]
Ok the config objects are just plain JavaScript objects coming from a
function like this:

```
var base = {/* common options */}
function configMaker (opts) {
  return _.assign({}, base, opts);
}
```

Where opts are just the entry points options specific to the build. I think
its basically just setting the real __dirname in the server build vs.
mocked in the client build, and different entry points.

callback looks like

```
function callback(err, stats) {
  if (err) console.log(err);
  console.log(stats.toString());
}
```

That's what I remember off the top of my head but I'll paste the whole
thing later if you still need.

**Comment by bebraw** [comment]
Any update on this? Did you manage to resolve the problem?
