### ISSUE TITLE
Fails when inculding regular json ~ Unexpected token ":" is just JSON

### ISSUE THREAD

**Issue by govpack** [webpack/webpack#1125]
i did add  [C:\Z\N\node_modules\webpack] "C:/Z/N/iojs.exe" "C:/Z/N/node_modules/npm/bin/npm-cli.js"   install json-loader --save 

why shouldn't that json-loader be included by default?
but still webpack can't even include json without errors

Hash: 28db93eab2d21d255194
Version: webpack 1.9.10
Time: 117ms
   Asset     Size  Chunks             Chunk Names
upack.js  88.3 kB       0  [emitted]  main
   [0] ./lib/entry.js 37 bytes {0} [built]
   [1] ./ucum.js 1.71 kB {0} [built] [1 error]
   [2] ./generated/ucum-parser.js 81.8 kB {0} [built] [2 errors]
   [3] ./lib/helpers.js 1.09 kB {0} [built]
   [4] ./generated/prefixes.json 0 bytes [built] [failed]
   [5] ./generated/metrics.json 0 bytes [built] [failed]
   [6] ./generated/equivalents.json 0 bytes [built] [failed]

ERROR in ./generated/equivalents.json
Module parse failed: C:\_______________\generated\equivalents.json Line 2: Unexpected token :
You may need an appropriate loader to handle this file type.
| {
|   "10*": {
|     "value": 10,
|     "ucum": "1"
 @ ./ucum.js 2:14-53

ERROR in ./generated/prefixes.json
Module parse failed: C:\______________\generated\prefixes.json Line 2: Unexpected token :
You may need an appropriate loader to handle this file type.
| {
|   "Y": 1e+24,
|   "Z": 1e+21,
|   "E": 1000000000000000000,
 @ ./generated/ucum-parser.js 1490:17-43

ERROR in ./generated/metrics.json
Module parse failed: C:\_____________\generated\metrics.json Line 1: Unexpected token :
You may need an appropriate loader to handle this file type.
| {"mol":true,"sr":true,"Hz":true,"N":true,"Pa":true,"J":true,"W":true,"A":true,"V":true,"F":true,"Ohm":true,"S":true,"Wb":true,"Cel":true,"T":true,"H":true,"lm":true,"lx":true,"Bq":true,"Gy":true,"Sv":true,"l":true,"L":true,"ar":true,"t":true,"bar":true,"u":true,"eV":true,"pc":true,"[c]":true,"[h]":true,"[k]":true,"[eps_0]":true,"[mu_0]":true,"[e]":true,"[m_e]":true,"[m_p]":true,"[G]":true,"[g]":true,"[ly]":true,"gf":true,"Ky":true,"Gal":true,"dyn":true,"erg":true,"P":true,"Bi":true,"St":true,"Mx":true,"G":true,"Oe":true,"Gb":true,"sb":true,"Lmb":true,"ph":true,"Ci":true,"R":true,"RAD":true,"REM":true,"cal_[15]":true,"cal_[20]":true,"cal_m":true,"cal_IT":true,"cal_th":true,"cal":true,"tex":true,"m[H2O]":true,"m[Hg]":true,"eq":true,"osm":true,"g%":true,"kat":true,"U":true,"[iU]":true,"[IU]":true,"Np":true,"B":true,"B[SPL]":true,"B[V]":true,"B[mV]":true,"B[uV]":true,"B[10.nV]":true,"B[W]":true,"B[kW]":true,"st":true,"mho":true,"bit":true,"By":true,"Bd":true,"m":true,"s":true,"g":true,"rad":true,"K":true,"C":true,"cd":true}
| 
 @ ./generated/ucum-parser.js 1491:16-41

**Comment by karlnp** [comment]
Did you add the "json!" prefix to those files' requires, or to the [modules.loaders](http://webpack.github.io/docs/configuration.html#module-loaders) config entry, so that the program knows to apply "json-loader" to `/\.json$/` extensions? It's not enough to just install the loader - webpack doesn't recognize it automatically so you have to invoke it. I ran into this too when I began using Webpack.

**Comment by govpack** [comment]
@karlnp  no, i'd probably need an example, i  searched for "json!" and "json$" on that link
http://webpack.github.io/docs/configuration.html#module-loaders
and that wasn't mentioned. Even from your kind reply i wouldn't know how.
next time i want a bit of configuration hell, i'll give it another try

....

i see it now in 

https://github.com/webpack/webpack/blob/master/examples/loader/webpack.config.js

```
module.exports = {
	module: {
		loaders: [
			{ test: /\.json$/, loader: "json" }
		]
	}
}
```


but the initial experience was too off putting to care anymore


and here in

node_modules\webpack\node_modules\json-loader\README.md

``` javascript
var json = require("json!./file.json");
// => returns file.json content as json parsed object
```

but doesn't require("file.json") also return file.json content as a json parsed object?
it would be weird, to me, if that  !json prefix wouldn't break people's code (ie some other annotation that doesn't break things would be preferred)

where is the global webpack.config.js? (nowhere i could see in node_modules/webpack)
so i wouldn't know where to add such

```
module.exports = {
	module: {
		loaders: [
			{ test: /\.json$/, loader: "json" }
		]
	}
}
```

except (i'm guessing) on a project-folder, by folder basis -- all this to say including json in a build shouldn't require any extra installations or config [json is a build in part of javascript in node and the browser]

**Comment by karlnp** [comment]
Oh, it's per-project, @govpack . For example, I have a few different config files in the project root: `webpack.config.dev.json`, `webpack.config.staging.json`, and `webpack.config.production.json` (which for us is empty.) That's where you define your entry points, include modules and plugins, loader pipelines, etc, etc.

When I next have some time I'll make some documentation PRs making that clearer.

**Comment by pksjce** [comment]
This issue was moved to webpack/webpack.io#146
