### ISSUE TITLE
Share Scopes doesnt create new cases in switch statements

### ISSUE THREAD

**Issue by ScriptedAlchemy** [webpack/webpack#11256]
# Bug report

**What is the current behavior?**
I don't think share scopes are working outside the default case. 
What I am trying to do is import a newer component inside an older react host. 
The idea is ill have an adapter which react to mount a div, then use share scope to take advantage of reactNew.render()

My idea was to create two share scopes so that legacy apps importing modern code would be able to render and mount the modern components on its own using a new version of react via share scope. 

```js
   new ModuleFederationPlugin({
      name: "app2",
      library: {type: "var", name: "app2"},
      filename: "remoteEntry.js",
      exposes: {
        "./Button": "./src/Button",
        "./ModernComponent": "./src/ModernReactComponent",
      },
      shared: ["react-dom", {
        react: {
          import: "react", // the "react" package will be used a provided and fallback module
          shareKey: "react", // under this name the shared module will be placed in the share scope
          shareScope: "default", // share scope with this name will be used
          singleton: true, // only a single version of the shared module is allowed
        },
        reactNew: {
          import: "react", // the "react" package will be used a provided and fallback module
          shareKey: "reactNew", // under this name the shared module will be placed in the share scope
          shareScope: "modern", // share scope with this name will be used
          singleton: true, // only a single version of the shared module is allowed
        },
      }],
    }),
``

Which generates the following

```js
/******/ 		__webpack_require__.I = (name) => {
/******/ 			// only runs once
/******/ 			if(initPromises[name]) return initPromises[name];
/******/ 			// handling circular init calls
/******/ 			initPromises[name] = 1;
/******/ 			// creates a new share scope if needed
/******/ 			if(!__webpack_require__.o(__webpack_require__.S, name)) __webpack_require__.S[name] = {};
/******/ 			// runs all init snippets from all modules reachable
/******/ 			var scope = __webpack_require__.S[name];
/******/ 			var warn = (msg) => typeof console !== "undefined" && console.warn && console.warn(msg);;
/******/ 			var uniqueName = "@different-react-versions/app2";
/******/ 			var register = (name, version, factory) => {
/******/ 				var versions = scope[name] = scope[name] || {};
/******/ 				var activeVersion = versions[version];
/******/ 				if(!activeVersion || !activeVersion.loaded && uniqueName > activeVersion.from) versions[version] = { get: factory, from: uniqueName };
/******/ 			};
/******/ 			var initExternal = (id) => {
/******/ 				var handleError = (err) => warn("Initialization of sharing external failed: " + err);
/******/ 				try {
/******/ 					var module = __webpack_require__(id);
/******/ 					if(!module) return;
/******/ 					var initFn = (module) => module && module.init && module.init(__webpack_require__.S[name])
/******/ 					if(module.then) return promises.push(module.then(initFn, handleError));
/******/ 					var initResult = initFn(module);
/******/ 					if(initResult && initResult.then) return promises.push(initResult.catch(handleError));
/******/ 				} catch(err) { handleError(err); }
/******/ 			}
/******/ 			var promises = [];
/******/ 			switch(name) {
/******/ 				case "default": {
/******/ 					register("react-dom", "16.13.1", () => Promise.all([__webpack_require__.e("vendors-node_modules_react-dom_index_js"), __webpack_require__.e("webpack_sharing_consume_default_react_react")]).then(() => () => __webpack_require__(/*! ../../node_modules/react-dom/index.js */ "../../node_modules/react-dom/index.js")));
/******/ 					register("reactNew", "16.13.1", () => __webpack_require__.e("vendors-node_modules_react_index_js").then(() => () => __webpack_require__(/*! ../../node_modules/react/index.js */ "../../node_modules/react/index.js")));
/******/ 				}
/******/ 				break;
/******/ 			}
/******/ 			return promises.length && (initPromises[name] = Promise.all(promises).then(() => initPromises[name] = 1));
/******/ 		};
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

Id expect to see `default` and `modern` in the switch statement

**Other relevant information:**
webpack version:  beta 22
Node.js version: 12
Operating System:  osx

**Comment by ScriptedAlchemy** [comment]
![image](https://user-images.githubusercontent.com/25274700/89110269-f17e6300-d3fd-11ea-8666-906c4ceb0cc3.png)

from 
```
  await __webpack_init_sharing__("modern");

  const container = window['app2']; // or get the container somewhere else
  // Initialize the container, it may provide shared modules
  console.log(__webpack_share_scopes__)
  await container.init(__webpack_share_scopes__.modern);
```

**Comment by sokra** [comment]
The host is not sharing `reactNew` here, because it never uses it. It would need to `import "reactNew"` to actually use this version and share it.

As sharing is optional and independent for each build, it's only done when really using the package.

That the host doesn't share `reactNew` doesn't prevent the containers to share it. Actually there would be no benefit when the host shares it except when container use `import: false` which is not recommended.

So if you want to isolate shared modules in some remotes, just omit the `reactNew` shared entry and the container would work as expected. They would share react with each other

**Comment by AsaRory** [comment]
> The host is not sharing `reactNew` here, because it never uses it. It would need to `import "reactNew"` to actually use this version and share it.
> 
> As sharing is optional and independent for each build, it's only done when really using the package.
> 
> That the host doesn't share `reactNew` doesn't prevent the containers to share it. Actually there would be no benefit when the host shares it except when container use `import: false` which is not recommended.
> 
> So if you want to isolate shared modules in some remotes, just omit the `reactNew` shared entry and the container would work as expected. They would share react with each other

I have three items: a,b,c,d.
a provides modules for b and c to use. a and b want to share react. a and c don't want to share react.
d also provides modules for c to use. d and c want to share react.
At this time, how to configure shared
