### ISSUE TITLE
compilation.rebuildModule broken in webpack 5

### ISSUE THREAD

**Issue by mattcompiles** [webpack/webpack#11269]
# Bug report

**What is the current behaviour?**

`compilation.rebuildModule` is broken since the breaking changes introduced in webpack 5 alpha. The source of the issue is the `removeReasonsOfDependencyBlock` function called inside `_rebuildModule`. 

`removeReasonsOfDependencyBlock` calls the removed Module API `Module.removeReason` to clean up the old dependencies of the rebuilt module. This causes any compilation using `compilation.rebuildModule` to fail. 

**If the current behaviour is a bug, please provide the steps to reproduce.**

I have created a basic test case in my fork. I'm happy to PR this in if it would help. 
https://github.com/mattcompiles/webpack/commit/541d049e458d14a1d45322c1fca8faca224080d2

I'd like to help fix the issue, however I'm not familiar with what modifications I need to make to the ModuleGraph and ChunkGraph to correctly clean up the module post rebuild.

**Comment by evilebottnawi** [comment]
Yep, let's fix it

**Comment by ruoqianfengshao** [comment]
Any good news about this issue? Callback which is passed to rebuildModule haven't run in webpack@5.12.0

**Comment by alexander-akait** [comment]
@ruoqianfengshao yep, we are working on it https://github.com/webpack/webpack/pull/11433 (latest update today), I think it was fixed in the next release, sorry for delay

**Comment by alexander-akait** [comment]
Fixed by https://github.com/webpack/webpack/pull/11433

**Comment by ruoqianfengshao** [comment]
Thanks，let me try this feature.
