### ISSUE TITLE
[Webpack 5] Why remove the id of runtime chunk from the entriesPart in JsonpTemplatePlugin

### ISSUE THREAD

**Issue by l5oo00** [webpack/webpack#11279]
# Bug report

Why remove the id of runtime chunk from the entriesPart in [JsonpTemplatePlugin](https://github.com/webpack/webpack/commit/8ca593e71828f36e582c38b3c6e83234907a003c#diff-ffb5b0d25c4855ca48e315d496203852R95)

**What is the current behavior?**

- `./dist/runtime.js`

```javascript
// ...

/******/ 		var installedChunks = {
/******/ 			666: 0
/******/ 		};

// ...

```

- `./dist/main.js`

```javascript
(window["webpackJsonpw5"] = window["webpackJsonpw5"] || []).push([[179],{

/***/ 138:
/***/ (() => {


console.log(1);


/***/ })

},[[138]]]);
```

**If the current behavior is a bug, please provide the steps to reproduce.**

- `./src/index.js`

```javascript
console.log(1);
```

- `./webpack.config.js`

```javascript
module.exports = {
    entry: {
        main: './src/index.js'
    },
    optimization: {
        minimize: false,
        runtimeChunk: 'single'
    }
};
```

- `./package.json`

```json
{
  "devDependencies": {
        "webpack": "5.0.0-beta.23",
        "webpack-cli": "^4.0.0-beta.2"
    },
    "scripts": {
        "build": "webpack --config webpack.config.js",
    }
}
```

**What is the expected behavior?**

- `./dist/runtime.js`

```javascript
// ...

/******/ 		var installedChunks = {
/******/ 			666: 0
/******/ 		};

// ...

```

- `./dist/main.js`

```javascript
(window["webpackJsonpw5"] = window["webpackJsonpw5"] || []).push([[179],{

/***/ 138:
/***/ (() => {


console.log(1);


/***/ })

},[[138, 666]]]);
```

When I use webpack@5.0.0-beta.18 and below versions, the behavior is expected.

**Other relevant information:**
webpack version:  
Node.js version:  v13.14.0
Operating System:  macOS Catalina 10.15.2

**Comment by sokra** [comment]
That was not intended, it's a bug. Do you want to send a PR?

**Comment by l5oo00** [comment]
ok, let me have a try.
