### ISSUE TITLE
Uncaught (in promise) Error: Cannot find module './dev'

### ISSUE THREAD

**Issue by ckken** [webpack/webpack#11272]
# Bug report

```javascript
const env = process.env.EMP_ENV || 'dev'
console.log('env project antd ===>', env)
const config = require(`./${env}`)
// const config = require(`src/config/${process.env.EMP_ENV}`) is worked!
config.env = env
export {env}
export default config

```
throw error `Uncaught (in promise) Error: Cannot find module './dev'`

and webpack 5.0.0-beta 22 is worked!

**Other relevant information:**
webpack version:  5.0.0-beta 23
Node.js version: v12.13
Operating System: 
Additional tools:

**Comment by evilebottnawi** [comment]
It is expected and described https://webpack.js.org/api/module-methods/#dynamic-expressions-in-import, it is limitation

**Comment by ckken** [comment]
but webpack 5.0.0-beta 22 is worked!

**Comment by evilebottnawi** [comment]
I think it was bug with side effect, we can't analyze runtime variable

**Comment by sokra** [comment]
It's a bug. It's already fixed but not yet released.
