### ISSUE TITLE
Conditional require seems not work

### ISSUE THREAD

**Issue by supnate** [webpack/webpack#1128]
Hi,

Say that I have below code in app.js which is the only entry in the entry point:
```javascript
var $ = false && require('jquery');
```
But the generated bundle still contains jquery code. Does this work as designed?

Actually I use a free variable defined by DefinePlugin to define if it needs jquery.

UPDATE:

I just found it works if I write:
```javascript
var $ = false ? require('jquery') : null;
```

or:

```javascript
var $ = null;
if (false) {
  $ = require('jquery')
}
```

So this seems only a minimal issue.

**Comment by Dashed** [comment]
This is short-circuit require; not conditional require. I don't think short-circuit expressions are supported.

**Comment by bebraw** [comment]
Not supported.
