### ISSUE TITLE
[Webpack 5] Automatic Node.js Polyfills Removed

### ISSUE THREAD

**Issue by hanford** [webpack/webpack#11282]
Hello Webpack team!

First of all, **huge** thank you to everything that Webpack has become. I've been happily using webpack for 5 or 6 years now and it's critical software for me.

I'm super excited about Webpack 5 (Especially Filesystem cache & Module Federation). I noticed that the nodejs polyfills are removed which a few my projects rely on, that's totally cool ... but I'm not sure what the best way to migrate that code is. 

Seems like most instances are in dependencies of dependencies, and after searching through the docs I wasn't able to find a migration for this specific change.

Is there a Webpack 5 compatible way of achieving the same thing? Do I polyfill these libraries in my application code?

Thanks again!

**Comment by evilebottnawi** [comment]
Here docs https://github.com/webpack/changelog-v5#automatic-nodejs-polyfills-removed

Plus you can use `alias` for this https://webpack.js.org/configuration/resolve/#resolvealias

**Comment by hanford** [comment]
Thanks!

**Comment by hanford** [comment]
Also came across this!

https://medium.com/@sanchit3b/how-to-polyfill-node-core-modules-in-webpack-5-905c1f5504a0

**Comment by hanford** [comment]
@evilebottnawi So I'm able to load my own Node polyfills and that's working great

I ran into another situation that's pretty interesting, I'm depending on [this library](https://github.com/vfile/vfile/blob/main/core.js#L55) which is using `process.cwd()` as a global (not importing process) ... and so my process mocks aren't loaded

Any ideas on how to solve or mock this use case?

**Comment by evilebottnawi** [comment]
You need to open an issue in library for browsing supporting or you can use https://www.npmjs.com/package/process (just put `import 'porcess';`), some libraries can be incompatibility with browsers env, we can't fix it

**Comment by hanford** [comment]
Thanks @evilebottnawi I'll move my issue to the other repo

**Comment by roman-hordiichuk** [comment]
Found solution for Angular and particularly sockJS nested dev-dependency of eventsource lib. Perhaps not the prettiest solution, though but it still works.

So you need the following steps: 
1) Install [](https://www.npmjs.com/package/event-source-polyfill)
2) Override required dependencies in package.json, in my case it was:
```
"overrides": {
    "sockjs-client": {
      "eventsource": "npm:event-source-polyfill"
    } 
```
So it changes your nested dependency by entirely different lib.
