### ISSUE TITLE
Consultation about chunkId and contenthash

### ISSUE THREAD

**Issue by LysKing** [webpack/webpack#11286]
Hello, I want to ask a question, if the output filename is configured and Contenthash is added, when is the hash value generated during the compilation and build of WebPack? Will the hash values be recalculated from the contents of module and Chunk during the build process? If I extract the common module in the mode of 'initial' with splitchunks, when is the common chunkId generated? Looking forward to your reply

**Comment by evilebottnawi** [comment]
Please use stackoverflow for questions, you can safely use `contenthash`, don't understand you
