### ISSUE TITLE
Reference to variable declared in switch case is incorrectly replaced with module reference when it shadows the import

### ISSUE THREAD

**Issue by dasa** [webpack/webpack#11283]
# Bug report

**What is the current behavior?**

This bug is similar to #9055, but happens for variables declared inside switch cases when the case isn't a single block.

**If the current behavior is a bug, please provide the steps to reproduce.**

`a.js`: `export default 1;`

index.js`:

```js
import A from "./a.js";

function go(test) {
  switch (test) {
    case 1:
      const A = "A";
      console.log(A); // should be "A", but is 1
      break;
    case 2: {
      const A = "A";
      console.log(A); // is "A"
      break;
    }
  }
}

go(1);
go(2);
```

Bundled code snippet in `none` mode:

```
function go(test) {
  switch (test) {
    case 1:
      const A = "A";
      console.log(_a_js__WEBPACK_IMPORTED_MODULE_0__["default"]);
      break;
    case 2: {
      const A = "A";
      console.log(A);
      break;
    }
  }
}
```

**What is the expected behavior?**

case 1 log should be same as case 2.

**Other relevant information:**
webpack version:  4.44.1
Node.js version: 
Operating System: 
Additional tools:

**Comment by evilebottnawi** [comment]
Thanks
