### ISSUE TITLE
./src/index.js overrides entry points specified in config

### ISSUE THREAD

**Issue by rjb3977** [webpack/webpack#11296]
# Bug report

**What is the current behavior?**
If `./src/index.js` is present, no other entry points are processed.

**If the current behavior is a bug, please provide the steps to reproduce.**

Use the following `webpack.config.js`:
```js
module.exports = {
    mode: 'development',
    output: {
        filename: '[name].js'
    },
    entry: {
        asdf: './src/asdf.js'
    }
}
```

Make two (potentially empty) files, `./src/index.js`, and `./src/asdf.js`. Run `npx webpack`, and observe that only one entry point is processed, named `main`, and including only `./src/index.js`.

Alternatively, run `npm i` and `npx webpack` after cloning [this repo](https://github.com/rjb3977/webpack-5.0.0-beta24-bug).

**What is the expected behavior?**
If `entry` is present in the config, only the entry points specified there are processed. In the case above, there should be one processed entry point, named `asdf`, and including only `./src/asdf.js`

**Other relevant information:**
webpack version: 5.0.0-beta24
Node.js version: 14.2.0
Operating System: Ubuntu 20.04

**Comment by anshumanv** [comment]
This seems to be a bug in CLI, I've added a test for it here - https://github.com/webpack/webpack-cli/pull/1718

Should be fine in next release, /cc @evilebottnawi
