### ISSUE TITLE
Cache failed with Yarn 2 PNP

### ISSUE THREAD

**Issue by kirill-konshin** [webpack/webpack#11293]
# Bug report

**What is the current behavior?**

```
<w> [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Managed item /Users/xxx/.yarn/unplugged/typescript-patch-ba0dbfd217 isn't a directory or doesn't contain a package.json
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Unable to snapshot resolve dependencies
```

The contents of the folder are as follows:

![image](https://user-images.githubusercontent.com/1530410/89591188-6a1a6080-d7fe-11ea-8d95-a2e0613b2cd7.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

Have `typescript` unplugged in repository with Yarn 2 with PNP enabled, then just build.

**What is the expected behavior?**

No errors should appear.

**Other relevant information:**
webpack version: 5.0.0-beta.24
Node.js version: 14
Operating System: Mac

**Comment by evilebottnawi** [comment]
How you create `typescript-patch-ba0dbfd217`? Structure it strange

**Comment by kirill-konshin** [comment]
This is how Yarn 2 handles packages in PNP mode.

**Comment by evilebottnawi** [comment]
Let's mark as bug

**Comment by Wheeeeeeeeels** [comment]
Same to me

**Comment by evilebottnawi** [comment]
Maybe related https://github.com/webpack/watchpack/issues/142?

Can you try to update yarn to latest version?

**Comment by kirill-konshin** [comment]
@evilebottnawi it does not look related...

**Comment by irudoy** [comment]
Have the same issue with the latest yarn (from sources). It's definitely not related to https://github.com/webpack/watchpack/issues/142.

**Comment by evilebottnawi** [comment]
Somebody can provide steps to reproduce?

**Comment by kirill-konshin** [comment]
Just use Webpack 5 and Yarn 2 with PNP mode, make sure to use ts loader and/or SASS loader, you'll see the following error:

```
<w> [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Managed item /xxx/.yarn/unplugged/node-sass-npm-4.14.1-edc7772b3a isn't a directory or doesn't contain a package.json
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Unable to snapshot resolve dependencies
```

**Comment by evilebottnawi** [comment]
@kirill-konshin unplugged package?

**Comment by kirill-konshin** [comment]
@evilebottnawi you can either unplug it manually, but Yarn 2 automatically unplugs packages that require `postinstall`. Both `typescript` and `node-sass` seems to do it.

**Comment by evilebottnawi** [comment]
@ kirill-konshin Only warnings? Is everything working fine?

**Comment by kirill-konshin** [comment]
@evilebottnawi *some* cache files are being created, but I'm not sure that cache is consistent and works well. And as you see the message is ERROR, not WARNING.

**Comment by sokra** [comment]
It's only a warning. The caching system will reresolve the build dependencies on restore and the caching should actually work. It might take a small performance hit on restore.

We should still fix that problem. Seems like we are expecting some different file structure here. I guess the format changed since this was implemented.

**Comment by kirill-konshin** [comment]
@sokra Yarn 2 has indeed some weird format of their directories unplugged directories...

![image](https://user-images.githubusercontent.com/1530410/91895792-a9e13600-ec4c-11ea-92ac-49236f215c47.png)
