### ISSUE TITLE
[rules.issuer]: unknown property 'test' 

### ISSUE THREAD

**Issue by ROME12345** [webpack/webpack#11300]
Hi,

i get the error "configuration.module.rules[0].issuer.not[0] has an unknown property 'test'. These properties are valid: object { and?, not?, or? }"

`module: 
		rules: [
			{
				test: /\.css$/i,
				issuer: {
					not: [{						
							test: /\.html$/i
						}]
				},
				use: [{
					loader: MiniCssExtractPlugin.loader
				},
					'css-loader'
				]
			}]}`

I cannot find any place in the documentation that this syntax is no longer valid from version 5. How can I solve the problem?

Regards, 
Roxane Mester

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted issue template. It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

It was removed from webpack@5, please open an issue in https://github.com/webpack/changelog-v5 repo, we will update changelog, thanks

**Comment by sokra** [comment]
`not: /\.html$/i`

**Comment by evilebottnawi** [comment]
Answer above, feel free to feedback
