### ISSUE TITLE
Security advisory for serialize-javascript package

### ISSUE THREAD

**Issue by samelliottdlt** [webpack/webpack#11309]
Hey folks 👋🏽

A security advisory was raised by npm for this serialize-javascript package. More info here: https://www.npmjs.com/advisories/1548

Looks like this package is brought in to our dependency trees by way of terser-webpack-plugin. A fix could be to update and publish to the latest version of terser-webpack-plugin which doesn't depend on a vulnerable version of serialize-javascript.

**Comment by webmaster128** [comment]
terser-webpack-plugin version ^4, ^3 and ^2 use a sufficiently version range of serialize-javascript (^4.0.0 and ^3.1.0). So webpack 5 is not affected.

For webpack 4 there is a semver-matching terser-webpack-plugin version 1.4.4 that bumps serialize-javascript from "^2.1.2" to "^3.1.0".

**Comment by evilebottnawi** [comment]
Please update deps to latest, fixed, all versions of `terser-webpacj-plugin` using `serialize-javascript@4`

**Comment by trivikr** [comment]
Is the dependency on vulnerable version of `serialize-javascript` going to be removed in `webpack@4`?

Latest version of webpack@4, i.e. v4.44.1 depends on `serialize-javascript@2.1.3`
https://github.com/webpack/webpack/blob/cd4af164784f3938353102179adfcbcf8f53949d/yarn.lock#L5789-L5792

To fix, it needs to be updated to `>3.1.0`

**Comment by trivikr** [comment]
`webpack@4` just need to update it's `terser-webpack-plugin` dependency to `v1.4.5` which updates `serialize-javascript` package version to `4.0.0`
* Code: https://github.com/webpack-contrib/terser-webpack-plugin/blob/v1.4.5/package-lock.json#L10713-L10720
* PR: https://github.com/webpack-contrib/terser-webpack-plugin/pull/259 

Question: Is this fix going to be released in `webpack@4.44.2` or `webpack@4.45.0`?

**Comment by trivikr** [comment]
For those who're visiting this issue from Dependabot security alerts, here is an example PR where dependency is updated https://github.com/aws-samples/aws-sdk-js-tests/pull/47
I just deleted `yarn.lock` entry for `terser-webpack-plugin@^1.4.3` and re-run yarn command. You can do the same for `package-lock.json` file if you're using npm.

Dependabot cannot automatically create a pull request to fix this as "one or more other dependencies require a version that is incompatible with this update."
As of now, the webpack team is not planning to release a patch version `webpack@4` with explicit dependency on `terser-webpack-plugin@v1.4.5`
