### ISSUE TITLE
webpackIgnore: true is ignored, dynamic import/require still processed

### ISSUE THREAD

**Issue by petermetz** [webpack/webpack#11311]
# Bug report

**What is the current behavior?**

Dynamic require gets parsed that isn't supposed to because I marked it with the `webpackIgnore: true` comment based on what I see here: https://github.com/webpack/webpack/pull/7034/files

**If the current behavior is a bug, please provide the steps to reproduce.**

webpack.config.js

```javascript

module.exports = {
  entry: {
    "x.bundle.js": `./x.js`,
  },
  target: "node",
  mode: "development",
  devtool: "inline-source-map",
  resolve: {
    extensions: [".js"],
  },
  output: {
    filename: "[name]",
  },
};

```

x.js

```javascript
const packageName = "net"
const x = require(/* webpackIgnore: true */ packageName);
```

x.bundle.js

```javascript
/***/ "./x.js":
/*!**************!*\
  !*** ./x.js ***!
  \**************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

const packageName = "net"
const x = __webpack_require__("./ sync recursive")(packageName);

/***/ })
```

**What is the expected behavior?**

x.bundle.js should look like this (e.g. no dynamic require parsing due to the ignore comment) so that it doesn't crash when the module is available to be loaded by NodeJS.
 
```javascript
/***/ "./x.js":
/*!**************!*\
  !*** ./x.js ***!
  \**************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

const packageName = "net"
const x = require(packageName);

/***/ })
```

**Other relevant information:**
webpack version:  4.44.1
Node.js version: v12.16.3
Operating System: Ubuntu 20.04
Additional tools:

**Comment by evilebottnawi** [comment]
Please create reproducible test repo, maybe babel/typescript remove comments

**Comment by petermetz** [comment]
> Please create reproducible test repo, maybe babel/typescript remove comments

@evilebottnawi Thank you for the response!

Repo: https://github.com/petermetz/webpack-11311

**Comment by evilebottnawi** [comment]
@petermetz 404

**Comment by petermetz** [comment]
> @petermetz 404

Oops, try now please. Set the visibility to public just now.

**Comment by sokra** [comment]
webpackIgnore is only for `import()` not for `require`

**Comment by petermetz** [comment]
> webpackIgnore is only for `import()` not for `require`

@sokra Ohh, maybe turn this into a feature request then? I need the webpackIgnore to work for require because ts-loader compiles the import down to require (need the commonjs module resolution because it's a NodeJS project).

**Comment by sokra** [comment]
Send a PR to add magic comments for `require()`. There are more possible comments that could apply here:
`webpackExports`, `webpackInclude`, `webpackExclude`, `webpackIgnore`

**Comment by petermetz** [comment]
> Send a PR to add magic comments for `require()`. There are more possible comments that could apply here:
> `webpackExports`, `webpackInclude`, `webpackExclude`, `webpackIgnore`

@sokra Here's the PR https://github.com/webpack/webpack/pull/11316
Only added `webpackIgnore` because that's the one I need and fully understand, never needed or used the other ones.

**Comment by evilebottnawi** [comment]
bump

**Comment by petermetz** [comment]
@kolserdav Do you mean the `webpackIgnore` magic comment or something else? If yes, can you please create a simplified test repo where the issue can be observed?

**Comment by kolserdav** [comment]
Hi, @petermetz. Thank you for your reply! Actually I see now that it works fine. My issue were connected with my code delivery. I use the bundle in my `Next.js` application and it make bundle with `webpack` but the bundle in production mode have no comments and so it's producing a wrong result.

**Comment by petermetz** [comment]
@kolserdav You are most welcome! Glad it all worked out in the end!
