### ISSUE TITLE
shim nodejs 'http' and 'https' for duktape

### ISSUE THREAD

**Issue by clarkbynum** [webpack/webpack#11318]
Hi everyone, I'm curious if it's possible to return a custom implementation of http/https whenever bundled code requires these built-in node packages. The use case being I'd like to redirect http method calls to a custom http implementation provided via go-duktape. Ideally, the custom implementation would be used when requiring statically and when requiring with expressions.  

e.g., static: `const http = require('http');` and with expression: `require(url.split(':')[0])`

I'm currently using a npm package that contains a require with an expression like in the example above, however, this results in an error being thrown - `Cannot find module 'http'`

My first thought was to monkey patch the require function to intercept calls for 'http' but looking at the bundled code, I see that calls with `require(url.split(':')[0])` are replaced with `__webpack_require__(3)` which points to a `webpackEmptyContext` module.

I've searched plenty for this kind of thing but haven't had any luck. Any help is appreciated

**Comment by sokra** [comment]
> require(url.split(':')[0])

You have to use the `ContextReplacementPlugin` to fix that. It's too dynamic for webpack.

**Comment by evilebottnawi** [comment]
Answer above, please use the issue template in future
