### ISSUE TITLE
[Webpack 5] Uncaught TypeError: entry.get is not a function

### ISSUE THREAD

**Issue by udayrajMT** [webpack/webpack#11319]
# Bug report

**What is the current behavior?**
Getting this error
```javascript
Uncaught TypeError: entry.get is not a function
    at get (main.e23b686eeb1e8d58814b.js:20685)
    at main.e23b686eeb1e8d58814b.js:20698
    at main.e23b686eeb1e8d58814b.js:20690
    at Object.webpack/sharing/consume/default/react/react (main.e23b686eeb1e8d58814b.js:20734)
    at Object.__webpack_modules__.<computed> [as webpack/sharing/consume/default/react/react] (main.e23b686eeb1e8d58814b.js:20745)
    at __webpack_require__ (main.e23b686eeb1e8d58814b.js:20104)
    at Object../src/index.js (main.e23b686eeb1e8d58814b.js:15)
    at __webpack_require__ (main.e23b686eeb1e8d58814b.js:20104)
    at main.e23b686eeb1e8d58814b.js:20842
    at main.e23b686eeb1e8d58814b.js:20844
```
**If the current behavior is a bug, please provide the steps to reproduce.**
Actually at this point I'm not sure how to reproduce it in a new repository(a lot of configuration may affect this). But perhaps someone can guide me with it. 

Something relevant I can share is the module federation plugin config. 
```javascript
new ModuleFederationPlugin({
  name: "<project-1>",
  library: { type: "var", name: "<project-1>" },
  filename: `${FEDERATION_REMOTE_ENTRY}.js`,
  exposes: {
    "./App": "./src/App",
  },
  remotes: {
    "<project-0>": "<project-0>",
  },
  shared: {
    react: {
      eager: true,
      singleton: true,
      requiredVersion: false,
    },
    "react-dom": {
      eager: true,
      singleton: true,
      requiredVersion: false,      
    },
    "react-router-dom": {
      eager: true,
      singleton: true,
      requiredVersion: false,      
    },
    "prop-types": {
      eager: true,
      singleton: true,
      requiredVersion: false,
    },
    // ... and others
  },
});

```

On applying a pause on exception, it stops near these line (breaks inside get) - 
```javascript
/******/ 		var loadFallback = /*#__PURE__*/ init(function(scopeName, scope, key, fallback) {
/******/ 			return scope && __webpack_require__.o(scope, key) ? get(findVersion(scope, key)) : fallback();
/******/ 		});
```

I see scope.react has the following value in console:
```javascript
// > scope.react
16.13.1: {from: "<project-name>", get: ƒ}
get: ƒ ()
version: (3) [16, 13, 1, loaded: 1]
__proto__: Object
```
I can see `findVersion(scope, key)` is returning `scope.react.version` which is not having a `get()` in it.

**What is the expected behavior?**
`findVersion(scope, key)` should return `scope.react.16.13.1`, or `scope.react.version` should have a get()

**Other relevant information:**
webpack version:  5.0.0-beta.24
Node.js version:  v12.13.1
Operating System: MacOS
Additional tools: module federation plugin is used

**Comment by sokra** [comment]
> ```js
> // > scope.react
> 16.13.1: {from: "<project-name>", get: ƒ}
> get: ƒ ()
> version: (3) [16, 13, 1, loaded: 1]
> __proto__: Object
> ```

Looks like you mixed in an old webpack version. There was a breaking change in the sharing system, get all containers up-to-date.

**Comment by evilebottnawi** [comment]
Answer above

**Comment by udayrajMT** [comment]
@sokra all projects that use moduleFederation are at the same webpack version. 
There is a webpack 4 project whose dist output is used in them. But I don't think it should be a problem. 

Also interestingly I do not get this error when using webpack-dev-server. 
Can you please give me further insight?

**Comment by evilebottnawi** [comment]
`webpack-dev-server` doesn't work with `ModuleFederationPlugin` yet, it is weird

**Comment by udayrajMT** [comment]
Well, it works practically

**Comment by udayrajMT** [comment]
@sokra would you mind giving more insights?

**Comment by evilebottnawi** [comment]
@udayrajMT Can you create reproducible test repo?

**Comment by sokra** [comment]
> There is a webpack 4 project whose dist output is used in them. But I don't think it should be a problem.

Could be.

It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by udayrajMT** [comment]
@vankop Thanks for reopening. 
@evilebottnawi @sokra I'll try to give a reproducible repository right when I find the time. Just that my further diagnosis was pointing towards an OS related issue, as it is not giving the error when served locally from the dist folders. The error is occurring in a linux pod only(I wasn't sure earlier, so had not mentioned).

**Comment by udayrajMT** [comment]
The error was gone for me a while ago, can't find a way to reproduce it just now. So I guess I shall close it until I encounter it again.
