### ISSUE TITLE
[Webpack 5] Module Federation - Shared exposed modules from host to remote do not work

### ISSUE THREAD

**Issue by mihaisavezi** [webpack/webpack#11313]
# Bug report

**What is the current behavior?**

application-a **exposes** SharedFromA to application-b  and **imports** AppAgendaChild from application-b
application-b **exposes** AppAgendaChild to application-a but it **imports** {SharedFromA} from 'application_a/SharedFromA';

**If the current behavior is a bug, please provide the steps to reproduce.**

- clone repo https://github.com/mihaisavezi/federated-libraries-get-started/tree/issue/use-case-host-remote
- run yarn dev to start the applications
- Uncomment ``` import {SharedFromA} from 'application_a/SharedFromA';``` in application-b/src/app.jsx
- notice the error 
```javascript
VM284 remoteEntry.js:2 Uncaught (in promise) TypeError: r is not a function
while loading "./SharedFromA" from webpack/container/reference/application_a
    at s (VM284 remoteEntry.js:2)
    at p (VM284 remoteEntry.js:2)
    at s (VM284 remoteEntry.js:2)
    at VM284 remoteEntry.js:2
    at s (VM284 remoteEntry.js:2)
    at VM284 remoteEntry.js:2
    at Array.forEach (<anonymous>)
    at Object.i.f.remotes (VM284 remoteEntry.js:2)
    at VM284 remoteEntry.js:2
    at Array.reduce (<anonymous>)
```

**What is the expected behavior?**

- application-a can load module exposed by application-b that itself loads something exposed from application-a

**Other relevant information:**
webpack version:  5.0.0-beta.24
Node.js version: 10.15.3
Operating System: MacOS Mojave 10.14.6
Additional tools:

**Comment by sokra** [comment]
https://github.com/mihaisavezi/federated-libraries-get-started/blob/05a1d1ed0e75a626afef432ae18f8190fa2d8a8a/packages/application-a/public/index.html#L6

This should be `<script src="http://localhost:3001/remoteEntry.js"></script>`
