### ISSUE TITLE
[Webpack 5] "new.target" is replaced by "Object()"

### ISSUE THREAD

**Issue by Hookyns** [webpack/webpack#11310]
# Bug report

**What is the current behavior?**
Webpack replace "new.target" by "Object()" which cause error.

**If the current behavior is a bug, please provide the steps to reproduce.**

> index.ts
```typescript
class A {
	static get instance() {
		return Reflect.construct(A, [], B);
	}
	
	constructor() {
		if (new.target != B) {
			throw new Error();
		}
	}
}

class B extends A {}

console.log(A.instance);
```

> tsconfig.json
```json
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "commonjs",
    "strict": true
  }
}
```

```
> npx webpack index.ts --output dist.js
```

------------------------------

TypeScript is transpiled right:
```javascript
"use strict";
class A {
    static get instance() {
        return Reflect.construct(A, [], B);
    }
    constructor() {
        if (new.target != B) {
            throw new Error();
        }
    }
}
class B extends A {
}
console.log(A.instance);
```

But output of dist.js is:
```javascript
(() => {
    class t {
        static get instance() {
            return Reflect.construct(t, [], c)
        }

        constructor() {
            if (Object() != c) throw new Error // THIS IS THE BUG!
        }
    }

    class c extends t {
    }

    console.log(t.instance)
})();
```

**What is the expected behavior?**
"new.target" should be leaved as is. 

**Other relevant information:**
Node.js version: 14.4
Operating System: Win 10
```json
  "dependencies": {
    "typescript": "^3.9.7",
    "webpack": "^5.0.0-beta.25"
  },
  "devDependencies": {
    "webpack-cli": "^3.3.12"
  }
```

**Comment by evilebottnawi** [comment]
Thanks for the issue

**Comment by sokra** [comment]
Yep, it's a bug

**Comment by seawatts** [comment]
Also seeing this bug here https://github.com/slackapi/node-slack-sdk/pull/1042

https://github.com/slackapi/node-slack-sdk/blob/078256bb59b5d7d7439ba5fb89b2a6e35bcf1ff5/packages/web-api/src/methods.ts#L36

**Comment by roni-frantchi** [comment]
Hey.  
I think this issue (or a variation of it) still exists on Webpack 5.11.1.  
Bundling [RobinBuschmann/sequelize-typescript](https://github.com/RobinBuschmann/sequelize-typescript) produces the following - 

Source: 
```javascript
if (!new.target.isInitialized) {
            throw new model_not_initialized_error_1.ModelNotInitializedError(new.target, `${new.target.name} cannot be instantiated.`);
```

Webpack 5.11.1 output:
```javascript
if (true) {
            throw new model_not_initialized_error_1.ModelNotInitializedError(new.target, `${new.target.name} cannot be instantiated.`);
```

Reported originally in https://github.com/RobinBuschmann/sequelize-typescript/issues/850

**Comment by alexander-akait** [comment]
@roni-frantchi please open new issue with reproducible test repo, thanks

**Comment by roni-frantchi** [comment]
@alexander-akait opened https://github.com/webpack/webpack/issues/12339 .  
A very simple reproducible repo is in there.
