### ISSUE TITLE
Try to resolve file after it is deleted (cache issue)

### ISSUE THREAD

**Issue by alfredsgenkins** [webpack/webpack#11328]
## Feature request

**What is the expected behavior?**

We are using custom Fallback plugin, which allows to resolve any file in the project from multiple roots, i.e. your theme, parent theme, core theme. They fallback sequentially, and we are only watching changes in main theme directory (only accessible to user, other are installed as node_modules). Fall-backing from custom theme to parent theme, from parent theme to core. The main reason to fallback - is if the file exist in higher level theme (custom) prefer it over lower level (parent, core).

The issue is - at the moment we are forced to restart webpack-dev-server as the newly created file is not recognized by webpack, the reuses some cache. Same goes for deleting - if a file / folder gets deleted the expected behavior is to fallback the file to parent theme. At the moment webpack just fails compiling. We are forced to restart it forcefully.

**What is motivation or use case for adding/changing the behavior?**

In case there are custom resolvers modules for files, after file deletion they have no way to fire, the request simply does not pass to resolved plugins. Allowing to retry file resolution can allow for our use-case to function properly.

**How should this be implemented in your opinion?**

There are two options:
- Exposure of API to clear file cache from memory, then we could watch ourself and clear on demand
- Allow resolver to resolve the file one more time, even if it was deleted. Fail only afterwards.

**Are you willing to work on this yourself?**

Yes, I would like to contribute. Unfortunately, after inspecting sources, I was unable to find a place to start from.

**Comment by sokra** [comment]
That's something that is addressed with webpack 5. It tracks all unsuccessful paths during resolving and watches them.

**Comment by alfredsgenkins** [comment]
Nice! Will take a look on beta. While waiting for stable release, will it be correct to say, that caching is implemented here:
- https://github.com/webpack/enhanced-resolve/blob/master/lib/UnsafeCachePlugin.js

Maybe replacing it with custom solution would be enough to implement cache purge.

**Comment by alfredsgenkins** [comment]
And sorry for playing with issue closing button, an "incedent" happened!
