### ISSUE TITLE
[Webpack 5] Can not use web-assembly rust impl

### ISSUE THREAD

**Issue by kaczor6418** [webpack/webpack#11347]
# Bug report

**Context**
If I create a simple rust function like this one:
```rust
#[wasm_bindgen]
pub fn return_char() -> char {
    return 'a';
}
```
And then I use this method inside constructor of web-component:
```typescript
constructor() {
    super();
    this.attachShadow({ mode: 'open' });
    this.shadowRoot.innerHTML = template;
    console.log(return_char());
}
```
This worked as expected I can see `'a'` in the console:

<center><img src="https://i.stack.imgur.com/g6Fm1.png"></center>

If I create rust struct with implementation like this one:
```rust
#[wasm_bindgen]
pub struct Test {
    value: char
}

#[wasm_bindgen]
impl Test {
    pub fn new() -> Test {
        let value: char = 'a';
        Test {
            value
        }
    }

    pub fn value(&self) -> char {
        self.value
    }

    pub fn change_value(&mut self) {
        self.value = 'b';
    }
}
```
And then create `Test` instance inside constructor of web-component and run `value` and `change_value` methods: 
```typescript
constructor() {
    super();
    this.attachShadow({ mode: 'open' });
    this.shadowRoot.innerHTML = template;
    const test: Test = Test.new();
    console.log(test.value());
    test.change_value();
    console.log(test.value());
}
```
I should see `'a'` and `'b'` in the console. But there is only this error:
> Uncaught (in promise) ReferenceError: Cannot access '__wbindgen_throw' before initialization
    at Module.__wbindgen_throw (calculator_engine_bg.js:5)
    at bundle.js:47
    at async eval (calculator_engine_bg.js:9)
    at async eval (App.ts:7)
    at async eval (index.ts:7)

**What is the current behavior?**
Application throws an error:
> Uncaught (in promise) ReferenceError: Cannot access '__wbindgen_throw' before initialization
    at Module.__wbindgen_throw (calculator_engine_bg.js:5)
    at bundle.js:47
    at async eval (calculator_engine_bg.js:9)
    at async eval (App.ts:7)
    at async eval (index.ts:7)

**What is the expected behavior?**
Application should print `'a'` and `'b'` to the console

**If the current behavior is a bug, please provide the steps to reproduce.**
 - Go to this GitHub repository [webpack-web-assembly-rust-impl-bug](https://github.com/kaczor6418/webpack-web-assembly-rust-impl-bug)
 - run following commends in your terminal
```bash
git clone https://github.com/kaczor6418/webpack-web-assembly-rust-impl-bug.git
cd webpack-web-assembly-rust-impl-bug
npm install
npm run serve
```
- go under this url: http://localhost:8080/
- press f12 (you should see error in console)

To check if this works only for simple method like `return_char` from my example follow this steps:
 - Go to this GitHub repository [webpack-web-assembly-rust-impl-bug](https://github.com/kaczor6418/webpack-web-assembly-rust-impl-bug)
 - run following commends in your terminal
```bash
git clone https://github.com/kaczor6418/webpack-web-assembly-rust-impl-bug.git
cd webpack-web-assembly-rust-impl-bug
git checkout example-without-error
npm install
npm run serve
```
- go under this url: http://localhost:8080/
- press f12 (you should see `'a'` in console)

**GitHub repository with minimal code needed to reproduce  [webpack-web-assembly-rust-impl-bug](https://github.com/kaczor6418/webpack-web-assembly-rust-impl-bug)**

**[webpcak-config](https://github.com/kaczor6418/webpack-web-assembly-rust-impl-bug/blob/master/webpack.config.js)**

**Other relevant information:**
webpack version:  5.0.0-beta.26
Node.js version: v12.12.0
Operating System: Linux Mint 19 Cinnamon / 4.15.0-47-generic

**Comment by sokra** [comment]
Try `experiments.syncWebAssembly` instead of `experiments.asyncWebAssembly`. If this works, the rust infrastructure need to be updated for the new spec.

**Comment by kaczor6418** [comment]
@sokra  this will work but I have to add additional `bootstrap.ts` file which will asynchronously load `index.ts`

>Without this additional file this will not work.

I created a branch with example: [sync-web-assebmly-and-bootstrap-file](https://github.com/kaczor6418/webpack-web-assembly-rust-impl-bug/tree/sync-web-assebmly-and-bootstrap-file).

But I think that `experiments.asyncWebAssembly` should work out of the box, or I am wrong ?

>Anyways this solution helped me a lot

**Comment by evilebottnawi** [comment]
> But I think that experiments.asyncWebAssembly should work out of the box, or I am wrong ?

No, please read https://webpack.js.org/configuration/experiments/

Do you still have a problem without this option?

**Comment by stephenmartindale** [comment]
> 
> 
> > But I think that experiments.asyncWebAssembly should work out of the box, or I am wrong ?
> 
> No, please read https://webpack.js.org/configuration/experiments/
> 
> Do you still have a problem without this option?

I've read the link and can't see, there, why `experiments.asyncWebAssembly` should *NOT* work, today. Is it a Rust issue or just because the experimental feature still needs more time in the oven?

It's a feature that I'm waiting for. Can you point me to any issues, either on the Rust side or the webpack side, which are tracking the status of `asyncWebAssembly` support? (I appear to be having a complete failure-to-search-the-web on this topic. I can't find anything and the only two links I did find, pointing to examples of `asyncWebAssembly`'s use, were long dead.)

**Comment by alexander-akait** [comment]
> But I think that experiments.asyncWebAssembly should work out of the box, or I am wrong ?

> I've read the link and can't see, there, why experiments.asyncWebAssembly should NOT work, today. Is it a Rust issue or just because the experimental feature still needs more time in the oven?

Yes, in future it will be `true` by default, right now developers have code for sync (previously standard) and async (new standard) versions, but async is new (was new) + many repos have old sync style, so to avoid problems, we set them to `false` by default.

We can improve docs if something needed here

> It's a feature that I'm waiting for. Can you point me to any issues, either on the Rust side or the webpack side, which are tracking the status of asyncWebAssembly support? (I appear to be having a complete failure-to-search-the-web on this topic. I can't find anything and the only two links I did find, pointing to examples of asyncWebAssembly's use, were long dead.)

It is already work, just set `experiments.asyncWebAssembly: true`, what is the problem?

**Comment by alexander-akait** [comment]
If you have a problem, just provide simple reproducible test repo and I will help

**Comment by alexander-akait** [comment]
Example for `syncWebAssembly`:

```js
Promise.resolve().then(() => {
    return import ("../calculator-engine/pkg/calculator_engine");
}).then(({ Test }) => {
    const test: any = Test.new();
    console.log(test.value());
    test.change_value();
    console.log(test.value());
});
```

**Comment by alexander-akait** [comment]
Here example of `asyncWebAssembly` - https://github.com/webpack/webpack/blob/master/test/configCases/wasm/identical/webpack.config.js, we use `wast-loader` to generate wasm file (`wabt` module used for it),

**Comment by xtuc** [comment]
@stephenmartindale  did you try https://github.com/wasm-tool/wasm-pack-plugin?

**Comment by stephenmartindale** [comment]
@xtuc: I did use it in the past. I no longer see the need for it. I'm even toying with the idea of removing `wasm-pack`, itself, from my projects and just invoking `wasm-bindgen` (and `wasm-opt`) as part of my build scripts. (And I wouldn't be the first: https://github.com/ruffle-rs/ruffle/pull/2482)
