### ISSUE TITLE
[💡DeprecationWarning] webpack 5 externals-function should be defined like ({context, request}, cb) => { ... }

### ISSUE THREAD

**Issue by thisVioletHydra** [webpack/webpack#11344]
terminal warning
```
webpack is watching the files…

(node:4516) [DEP_WEBPACK_EXTERNALS_FUNCTION_PARAMETERS] DeprecationWarning: The externals-function should be defined like ({context, request}, cb) => { ... }
(Use `node --trace-deprecation ...` to show where the warning was created)
```

![image](https://user-images.githubusercontent.com/11839238/90647484-0736b980-e241-11ea-8af9-5ed5022d54a3.png)

What I should do?

**Comment by evilebottnawi** [comment]
Please open an issue in `node-externals` packages, it is deprecation and they should fix it for webpack@5 compatibility, but I think you don't need this package anymore, we don't mock node globals by default in webpack@5

**Comment by thisVioletHydra** [comment]
> Please open an issue in `node-externals` packages, it is deprecation and they should fix it for webpack@5 compatibility, but I think you don't need this package anymore, we don't mock node globals by default in webpack@5

when i disable this prop:
```jsonc
 target: 'async-node',
      // externals: [
      //   ({ request }, callback) => {
      //     if (/^[a-z\-0-9]+$/.test(request)) {
      //       return callback(null, `commonjs ${request}`);
      //     }

      //     return callback();
      //   },
      // ],
      // externals: [{ nodeExternals: [nodeExternals()] }],
      // watch: false,
      // watch: nodeEnv !== 'production',
      mode: String(nodeEnv),
```

![image](https://user-images.githubusercontent.com/11839238/90683003-88f10c00-e26e-11ea-8065-8fd8ae46c2a5.png)

------
When i turn on

![image](https://user-images.githubusercontent.com/11839238/90683182-ce153e00-e26e-11ea-82cd-612b9ea5ae34.png)

What does it mean? `you don't need this package anymore`

**Comment by evilebottnawi** [comment]
https://github.com/webpack/changelog-v5#automatic-nodejs-polyfills-removed, please read migrate section

**Comment by evilebottnawi** [comment]
If you need to help, please create reproducible test repo
