### ISSUE TITLE
[Webpack 5] Module Federation - Re-exports imported in remote crash application with no error message.

### ISSUE THREAD

**Issue by mihaisavezi** [webpack/webpack#11341]
# Bug report

**What is the current behavior?**
Bi-directional hosts. Exposed file is a re-export. Compilation does not throw an error. But application won't load.

**Context** 
- `app1` exposes `indexExternal.js` as `./hostExports` which re-exports some modules from `exports.js` which exports everything from `deps.js` and `effects.js`
- `app2` exposes `demo-exports.js` as `./remoteExports` which is just a constant
- Search for `(1)` and `(2)` in the code.
  - (1) - here we import from `app2/remoteExports` and it crashes the app with no error. The import is made in a file that is later re-exported. `effects.js` is re-exported in `exports.js` to indexExternal, where we only pick-up some of the exports. This is the file that is exposed from `app1`
  - (2) - here we import from `app2/remoteExports` in `app1`. This works, the file is not re-exported or anything similar.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Clone [this repo](https://github.com/mihaisavezi/module-federation-examples/tree/feat/module-federation-bug)
2. Start bi-directional hosts example. (For detailed explanations see [Readme that explains the bug](https://github.com/mihaisavezi/module-federation-examples/tree/feat/module-federation-bug/bi-directional))
3. Search for `(1)` and un-comment the code underneath it. App no longer loads, no compilation error thrown.
4. Search for `(2)` and un-comment the code underneath it. App loads normally.

**What is the expected behavior?**
Regardless of where the import from the `remote module` to `host` is made, it should not crash the app or it should have some informative message.

**Other relevant information:**
webpack version:  webpack@5.0.0-beta.26 
Node.js version: v10.15.3
Operating System: Mac OS 10.14.6 Mojave
Additional tools:

**Comment by sokra** [comment]
Yes, this seem to be a bug. The container awaiting each other initialization during initialization. This creates a circular promise which never completes...

**Comment by mihaisavezi** [comment]
Since an image is worth a 1000 words, used the federation-dashboard to illustrate the dependencies in this issue.

![image](https://user-images.githubusercontent.com/6965490/90647032-8c6d9e80-e240-11ea-9756-727c474d5514.png)

**Comment by mihaisavezi** [comment]
I'd like to give this a go. But really no clue where to start with this? Any hypotheses for starting points on this ?

Not really familiar with the API or anything. Some hints would help. 

I'll start diving into this myself in the meantime.

**Comment by sokra** [comment]
should be fixed

**Comment by evilebottnawi** [comment]
@mihaisavezi feel free to feedback
