### ISSUE TITLE
[BETA] beta.27 build error when `mode: production` is set

### ISSUE THREAD

**Issue by jungleBadger** [webpack/webpack#11348]
# Bug report

**What is the current behavior?**

1. Webpack builds emits an error when using `"mode": "production"`
2. The exact same webpack and project files work fine if I set `"mode": "development"`
3. It works if I hardcode `"mode": "development"` and set `NODE_ENV=production`

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Here is the webpack config example: https://pastebin.com/gC6eVdDk
2. The `main.js` minimal content, which already triggers the error
```js
"use strict"
export default {};
```
3. The index.ejs is also very simple traditional HTML5 template
4. The error log:

```
TypeError: asset.source.buffer is not a function
    at F:\projects\ibm_projects\platform\node_modules\webpack\lib\optimize\RealContentHashPlugin.js:214:25
```

![Anotação 2020-08-20 010614](https://user-images.githubusercontent.com/12788435/90715677-61f00580-e281-11ea-95a6-68c663266b1b.jpg)

5. I added a `console.log(asset)` instruction at `RealContentHashPlugin.js line 210`:

![Anotação 2020-08-20 011310](https://user-images.githubusercontent.com/12788435/90716072-6b2da200-e282-11ea-96cd-e38b3f7c8c72.jpg)

Extra info:

1. I couldn't share the repo, because it is from an enterprise git.
2. I spent a few hours trying to find a reason for this on my side before opening the issue.
3. I researched the error messages and couldn't find any related info on StackOverflow/etc.
4. Right before opening the issue, I found this reference here: https://github.com/webpack/webpack/issues/9802#issuecomment-676826884, which I think can be related 
5. This is the command I'm using to execute the production build:
```
webpack --env.production --env.NODE_ENV=production
```
6. I tried to remove the `optimization` option and the result remains the same.
7. I couldn't find any update to the plugins I'm using

**What is the expected behavior?**

Build successfully when setting the `mode` as `production`

**Other relevant information:**
webpack version:  `^5.0.0-beta.27`
Node.js version: `12.18.3`
Operating System: `Win 10 pro`
Additional tools: N/A

**Comment by sokra** [comment]
fixed in https://github.com/webpack/webpack/releases/tag/v5.0.0-beta.28
