### ISSUE TITLE
Code splitting with ES6 Modules?

### ISSUE THREAD

**Issue by trusktr** [webpack/webpack#1135]
The [Code Splitting](http://webpack.github.io/docs/code-splitting.html) page says:

> To clarify a common misunderstanding: Code Splitting is not just about extracting common code into a shared chunk. The more notable feature is that Code Splitting can be used to split code into an on demand loaded chunk.

I specifically want to do code splitting for the first reason: `extracting common code [from all bundles] into a shared chunk`. I'm not using AMD or CJS, just ES6 Modules. The page doesn't say anything about code splitting with ES6.

Is it possible?

**Comment by trusktr** [comment]
Hmmmmm... Okay, I think I got this. I think `CommonsChunkPlugin` will be my friend.

**Comment by SimenB** [comment]
Seems like you found it, but for reference: http://webpack.github.io/docs/code-splitting.html#split-app-and-vendor-code
