### ISSUE TITLE
[DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues.

### ISSUE THREAD

**Issue by Dam998** [webpack/webpack#11350]
# Bug report

**What is the current behavior?**
I created a script in node js, it works fine, but when I create a bundle with webpack and run it I receive this error:
`[DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.`

But I'm not using Buffer
The strange thing is that when I execute it normally don't get any warning but if I execute the bundle, I get this error

**If the current behavior is a bug, please provide the steps to reproduce.**
I'm using an exeternal package called [Simple Terminal Menu](https://www.npmjs.com/package/simple-terminal-menu), if I remove it, I don't receive this error

**What is the expected behavior?**
Do not reiceve this warning, I don't know how to fix it, all my packages are up to date
only after using webpack do i get this error

**Other relevant information:**
webpack version:  4.44.1
Node.js version: 12.18.3
Operating System: Win 10 Pro
Additional tools:

**Comment by goto-bus-stop** [comment]
`Buffer()` only emits a deprecation warning if the call to it is _not_ inside `node_modules`. So, if simple-terminal-menu or one of its dependencies is using the deprecated `Buffer()` constructor, you will not get a deprecation warning.

But, when you bundle it with webpack, the code using `Buffer()` is no longer inside `node_modules`: it's now in the bundled file, which to Node.js looks like it's part of your own code. Then it emits the warning.

There is nothing webpack can do to address that. You can ignore the deprecation, or figure out which dependency exactly is using the deprecated `Buffer()` constructor and send them a PR.

**Comment by Dam998** [comment]
Oh okay, I understand
Thank you for your support

I'm looking for the package

Another question @goto-bus-stop, Do you know a way to not show this warning? just not print it in the console

**Comment by goto-bus-stop** [comment]
The [`node --no-deprecation` flag](https://nodejs.org/api/cli.html#cli_no_deprecation) hides deprecation warnings.

**Comment by Dam998** [comment]
Thank you for your support @goto-bus-stop 
I appreciate it

Last question, if you know the response, I want to create an exe with pkg or nexe
Do you know a way to use --no-deprecation with nexe or pkg? because I didn't find documentation in their github

Thank you!

**Comment by goto-bus-stop** [comment]
Sorry, I'm not familiar with those.

**Comment by sokra** [comment]
Also see `--trace-deprecation` to get a Stack Trace of the deprecation to find the origin.

**Comment by anilverma087** [comment]
**Created node API with HTTPS Server**

working fine on local host getting   [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues.
while hosting  on IIS server
