### ISSUE TITLE
2 bundles with bootstrap leads into problems.

### ISSUE THREAD

**Issue by bitterdev** [webpack/webpack#11357]
Hello,

i have a question.

We are using 2 webpack bundles in our project.

Each bundle imports bootstrap.

Therefore we have issues like that the dropdown require 2 clicks (which is an issue when bootstrap is loaded 2+ times)
https://stackoverflow.com/questions/24218663/avoid-having-to-double-click-to-toggle-bootstrap-dropdown

What is the best practice to use bootstrap js in both bundles without any issues?

Thank you

Fabian

**Comment by sokra** [comment]
Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md).
