### ISSUE TITLE
ERROR in Entry module not found: 

### ISSUE THREAD

**Issue by IamANM** [webpack/webpack#1136]
Error: Cannot resolve module 'client/react' in /Users/z013mrq/react-back
```
/**
 * Created by z013mrq on 6/1/15.
 */
var path = require('path');
var webpack = require('webpack');

module.exports = {
    cache : true,
    entry:{
        react:"./client/react"
    },
    output:{
        path: path.join(__dirname,"client/build"),
        publicPath : "build/",
        filename:"[name].js",
        chunkFilename : "[chunkhash].js"
    },
    modules:{
        loader:[
            // required for react jsx
            { test: /\.js$/,    loader: "jsx-loader" },
            { test: /\.jsx$/,   loader: "jsx-loader?insertPragma=React.DOM" },
        ]
    },
    resolve:{
        alias:{

        }
    }
}
```

**Comment by IamANM** [comment]
webpack --display-error-details

ERROR in Entry module not found: Error: Cannot resolve 'file' or 'directory' ./client/react in /Users/z013mrq/react-back
resolve file
  /Users/z013mrq/react-back/client/react is not a file
  /Users/z013mrq/react-back/client/react.webpack.js doesn't exist
  /Users/z013mrq/react-back/client/react.web.js doesn't exist
  /Users/z013mrq/react-back/client/react.js doesn't exist
  /Users/z013mrq/react-back/client/react.json doesn't exist
resolve directory
  /Users/z013mrq/react-back/client/react/package.json doesn't exist (directory description file)
  directory default file index
    resolve file index in /Users/z013mrq/react-back/client/react
      /Users/z013mrq/react-back/client/react/index doesn't exist
      /Users/z013mrq/react-back/client/react/index.web.js doesn't exist
      /Users/z013mrq/react-back/client/react/index.webpack.js doesn't exist
      /Users/z013mrq/react-back/client/react/index.js doesn't exist
      /Users/z013mrq/react-back/client/react/index.json doesn't exist

**Comment by IamANM** [comment]
i found that, .jsx file format is not supported for modules. So i renamed my files to .js and it started working. Any idea when requiring .jsx file will work

**Comment by 1j01** [comment]
I think you might have a typo `loader` instead of `loaders`
