### ISSUE TITLE
trouble parsing module

### ISSUE THREAD

**Issue by GhanPatel** [webpack/webpack#1138]
I've read this:
https://github.com/webpack/webpack/issues/303
but I believe my issue is different (not about json).

I'm using webpack (with babel-loader), and get this error when I import react-geocoder:

    ERROR in ./~/react-geocoder/index.js
    Module parse failed: /Users/me/project/node_modules/react-geocoder/index.js Line 9:
    Unexpected token (
    You may need an appropriate loader to handle this file type.
    |  */
    | var Geocoder = React.createClass({
    |   getDefaultProps() {
    |     return {
    |       endpoint: 'https://api.tiles.mapbox.com',
    @ ./static/app/scripts/components/ListProperty/ListPropertyLocationField.jsx 25:21-46

This is most likely a webpack config problem, and I'm hoping someone here knows how to help. My webpack config:

    var config = {
        entry: './static/app/scripts/main.js',
        output: {
          path: __dirname,
          filename: 'main.js'
        },
        debug : isDev,
        module: {
          loaders: [{
              test: /\.jsx?$/,
              exclude: /node_modules/,
              loader: 'babel'
          }]
        }
      };

**Comment by karlnp** [comment]
Try to add another loader for `/\.js$/` specifically - it's probably just that you've defined JSX but not JS files for Babel loading.

**Comment by GhanPatel** [comment]
thanks @karlnp, adding this doesn't help:

      loaders: [{
          test: /\.jsx?$/,
          exclude: /node_modules/,
          loader: 'babel'
      },
      {
          test: /\.js?$/,
          exclude: /node_modules/,
          loader: 'babel'
      }]

I wonder if it's the loader... version of babel-loade is up to date.

**Comment by karlnp** [comment]
wait, that's odd - geocoder is a node_module - it shouldn't be being compiled by babel.

**Comment by SimenB** [comment]
@GhanPatel You exclude `node_modules` in the loader. You could create a new loader entry with include only on `react-geocoder`

**Comment by GhanPatel** [comment]
looks like adding this works:

    {
        test: /\.js?$/,
        include: /react-geocoder/,
        loader: 'babel'
      }

Thanks!

**Comment by gitnik** [comment]
I don't really understand this. (why) does webpack not work with es6 modules?

**Comment by karlnp** [comment]
It doesn't know how to read them unless you include babel as a loading step. why would we expect it to work differently? This error was a problem with the configuration, not with language levels.

**Comment by niftylettuce** [comment]
I get the same error, webpack doesn't exclude `/node_modules/` and the only way it seems to work is with `include`
