### ISSUE TITLE
hide relative path on bundle files

### ISSUE THREAD

**Issue by sutineeangs** [webpack/webpack#11380]
Hi,
1. I build react project using webpack. 
This is my config.
`
var config = {
  mode: NODE_ENV,
  node: {
    __filename: true,
    __dirname: true
  },
  entry: entry,
  optimization: {
    splitChunks: {
      chunks: 'all',
      maxInitialRequests: 2, // default to 2, adjust as needed
    },
    runtimeChunk: 'single', // optional, recommended
  },
  output: {
    publicPath: "",
    path: OUTPUT_PATH,
    filename: '[name].[hash].js',
  },
  resolve: {
    extensions: ['.js', '.coffee', '.jsx', '.css', '.scss', '.sass'],
    alias: {
      '@Components': path.resolve(__dirname, 'src/components/'),
      '@Assets': path.resolve(__dirname, 'src/assets/'),
      '@Ducks': path.resolve(__dirname, 'src/ducks/'),
      '@Gql': path.resolve(__dirname, 'src/gql/'),
    }
  },
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        use: ["babel-loader"],
        include: [
          path.resolve(__dirname, "src"),
        ]
      },
      {
        test: /\.coffee$/,
        loaders: ['babel-loader',
          'coffeescript-loader']
      },
      {
        test: /\.css$/,
        loaders: ['style-loader',
          'css-loader?importLoaders=1',
          'font-loader?format[]=truetype&format[]=woff&format[]=embedded-opentype']
      },
      {
        test: /\.(jpe?g|png|gif|svg)$/i,
        loaders: ['url-loader?limit=10000',
          'img-loader']
      },
      {
        test: /\.less$/,
        loaders: ["style-loader",
          "css-loader",
          "less-loader"]
      },
      {
        test: /\.(sass|scss)$/,
        loaders: ["style-loader",
          "css-loader",
          "sass-loader"]
      },
      {
        test: /\.(eot|svg|ttf|woff|woff2)$/,
        loader: 'url-loader'
      }
    ]
  },
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new HtmlWebpackPlugin({
      title: 'Caching',
      inject: true,
      filename: path.resolve(OUTPUT_PATH, INDEX_FILENAME),
      template: './src/index.html'
    }),
    new webpack.DefinePlugin(_.extend({
      ENV: JSON.stringify(process.env)
    }, ENV_VARS_VALUES)),
    new WebpackObfuscator({
      rotateStringArray: true
    })
  ],
  devServer: {
    historyApiFallback: true,
    port: WEBPACK_DEV_PORT,
    host: "0.0.0.0",
    disableHostCheck: false,
    publicPath: "/",
    quiet: false,
    noInfo: false,
    inline: true,
    hot: true,
    watchOptions: {
      aggregateTimeout: 300,
      poll: 500
    },
    // watchContentBase: true,
  }
};

module.exports = config;
`
2. I found relative path on bundle files.
C:/Users/xxxxxxx/Works/abc/src/components/AlertModal.js in main.xxxxxxxxx.js file

How to relative path on bundle files?

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

We can't help you without infromation.
