### ISSUE TITLE
Function configs are not used (webpack 5)

### ISSUE THREAD

**Issue by ntucker** [webpack/webpack#11398]
# Bug report

**What is the current behavior?**
Function configs are not used

**If the current behavior is a bug, please provide the steps to reproduce.**
See https://github.com/ntucker/webpack-example

**What is the expected behavior?**
- `running webpack` is printed to console
- output file is named `out.js`
- entrypoint 'first' points to non-existant directory `src2` and thus cannot compile

**Other relevant information:**
webpack version:  5.0.0-beta.19
Node.js version: 14.9.0
Operating System: ubuntu wsl2 on windows 10
Additional tools: yarn 1

**Comment by sokra** [comment]
Seem to be a webpack cli issue

**Comment by snitin315** [comment]
Yes, this issue is fixed in https://github.com/webpack/webpack-cli/pull/1721
