### ISSUE TITLE
disableHostCheck is no work in beta 29

### ISSUE THREAD

**Issue by ckken** [webpack/webpack#11407]
webpack 5 beta 24 work well!

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

Not related to webpack and it was not changed
