### ISSUE TITLE
npm [ERR] code EMAXREDIRECT     during    npm install webpack --save-dev

### ISSUE THREAD

**Issue by cellurl3** [webpack/webpack#11400]
newbie. Sorry for intrusion.

I am behind proxy .company.com

I was able to find an .msi for npm, nodejs, but is there one for webpack??

Otherwise, I have to yank my work computer to home, install webpack and then get fired... ;-)

-----------------------------------------------------
C:\Users\857723\OneDrive - MyFedEx\Desktop\translate_onhover-master>npm install webpack --save-dev
npm ERR! code EMAXREDIRECT
npm ERR! maximum redirect reached at: http://199.82.243.100:4711/files/proxy.pac

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\857723\AppData\Roaming\npm-cache\_logs\2020-08-31T18_42_14_945Z-debug.log

C:\Users\857723\OneDrive - MyFedEx\Desktop\translate_onhover-master>

**Comment by sokra** [comment]
not a webpack issue, probably company it problem

**Comment by cellurl3** [comment]
i know, but the work around is an msi. Of course you hate it, but your number one user (me), needs it ;-)

**Comment by evilebottnawi** [comment]
@cellurl3 what do you expect from us to do here?
