### ISSUE TITLE
Why are modules called with `module.exports` context?

### ISSUE THREAD

**Issue by pgilad** [webpack/webpack#1141]
I notice the following line when calling a newly loaded module:
```js
modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
```

Evaluated at runtime, `module.exports` is an empty object, and this breaks plugins that are built with UMD and need access to the global this, which they assume is `window`.
For example:
Using [jquery-visibility](https://github.com/mathiasbynens/jquery-visibility) you notice that in this line: https://github.com/mathiasbynens/jquery-visibility/blob/master/jquery-visibility.js#L25 they expect this to be the global window.

Using Webpack - it evaluates to a blank object, forcing you to use `imports?this=>window` as a loader, which is redundant (and wasteful) IMO.

Any explanations as to why modules are loaded this way?
What is the correct solution in this case? I feel that calling modules with a specific context should be an opt-in and not default behavior.

**Comment by sokra** [comment]
CommonJs spec say so.

**Comment by pgilad** [comment]
So every jQuery plugin that uses reference to this (and assumes it will be window) will need to be wrapped with an `import` loader?

**Comment by sokra** [comment]
yep... `imports?this=>window` you need to put this into the config.

But it's actually the modules fault, because they modifed the UMD wrapper in a wrong way: [passing `root` as `window`](https://github.com/mathiasbynens/jquery-visibility/blob/master/jquery-visibility.js#L20)

**Comment by pgilad** [comment]
So in `jquery.visibility` case - what should have been the correct implementation? Directly referencing `window` instead of `this` ?

**Comment by shama** [comment]
A better UMD pattern for `jquery.visibility` would be to just check if the global `window` exist (by just not bothering to pass it to the factory):

```js
;(function (factory) {
    if (typeof define === 'function' && define.amd) {
        // AMD. Register as an anonymous module.
        define(['jquery'], function ($) {
        	return factory($);
        });
    } else if (typeof exports === 'object') {
        // Node/CommonJS
        module.exports = factory(require('jquery'));
    } else {
        // Browser globals
        factory(jQuery);
    }
}(function($, undefined) {
  // Does window exist?
  if (!window) throw new Error('We need a window');
}));
```

It's better to check for global dependencies as need instead of assuming `this` equals `window` because in many cases, even outside of webpack, `this !== window`.

**Comment by bebraw** [comment]
@pgilad Safe to close?

**Comment by pgilad** [comment]
Yes, thank you
