### ISSUE TITLE
webpack@5.0.0-beta.29 loader should be a non-empty string.

### ISSUE THREAD

**Issue by Linkontoask** [webpack/webpack#11418]
**What is the current behavior?**

```
ValidationError: Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.module.rules[0] should be one of these:
   ["..." | object { compiler?, descriptionData?, enforce?, exclude?, generator?, include?, issuer?, loader?, mimetype?, oneOf?, options?, parser?, realResource?, resolve?, resource?, resourceFragment?, resourceQuery?, rules?, sideEffects?, test?, type?, use? }, ...]
   -> A rule.
   Details:
    * configuration.module.rules[0].loader should be a non-empty string.
      -> A loader request.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Recurring link: [https://github.com/Linkontoask/webpack-5-bug](https://github.com/Linkontoask/webpack-5-bug)

`"babel-loader": "^8.1.0",`
`"eslint-loader": "^4.0.2",`
```
  {
    test: /\.js$/,
    loader: ['babel-loader', 'eslint-loader']
  }
```

**What is the expected behavior?**

`Compiled successfully.`

**Other relevant information:**
webpack version:  5.0.0-beta.29
Node.js version: 12.16.1
Operating System: 
Additional tools:

**Comment by chenxsan** [comment]
You're supposed to use [`Rule.use`](https://webpack.js.org/configuration/module/#ruleuse) for multiple loaders instead of `Rule.loader` which only accepts a non-empty string as the error message showed.

**Comment by Linkontoask** [comment]
4.x can use `loader: ['','']`, it can run normally.
This is true, but the error prompts given are not friendly enough. When there are multiple rules and they all use `loader: ['','']`, only the last error will be prompted, which will mislead the direction to a certain extent.

4.x can compile normally
```
module: {
     rules: [
       {
         test: /\.js$/,
         loader: ['babel-loader','eslint-loader']
       }
     ]
}
```

5.x prompts are not friendly enough, only the last configuration error will be prompted, and it is expected to show all
```
{
     test: /\.tsx?$/,
     loader: ['ts-loader','eslint-loader']
},
{
     test: /\.js$/,
     loader: ['babel-loader','eslint-loader']
}
```

**Comment by evilebottnawi** [comment]
yes, it is breaking change, you should use:
```
module: {
     rules: [
       {
         test: /\.js$/,
         use: ['babel-loader','eslint-loader']
       }
     ]
}
```

Please open an issue in https://github.com/webpack/schema-utils repo, this module generate error messages

From https://github.com/webpack/changelog-v5 

> module.rules query and loader(s) were removed (since alpha.13)

**Comment by derekschinke** [comment]
Wow, was this listed as a migration step on [this page](https://webpack.js.org/migrate/5/)? I've been wrestling with upgrading to 5.0, checked the migration steps, but it didn't appear that `loader -> use` was breaking change.
