### ISSUE TITLE
ModuleFederationPlugin shared undefined cause error when init

### ISSUE THREAD

**Issue by shaodahong** [webpack/webpack#11419]
# Bug report

**What is the current behavior?**

Webpack

```js
     new ModuleFederationPlugin({
        name: 'app1',
        library: { type: 'var', name: 'app1' },
        filename: 'remoteEntry.js',
        exposes: {
          Routes: './src/routes',
        },
      }),
```

Project
```js
  await __webpack_init_sharing__('default')
  const container = window['app1']

  // cause error
  await container.init(__webpack_share_scopes__.default)
```

cause `TypeError: Cannot read property 'default' of undefined`

and if set 'shared: {}', it's normal

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  5.0.0-beta.29
Node.js version: v12.16.1
Operating System: OSX
Additional tools:

**Comment by shaodahong** [comment]
@sokra 

In my see 

https://github.com/webpack/webpack/blob/edf03440bac7f0027eb477a006231af759bb6ae9/lib/container/ContainerEntryModule.js#L211

`RuntimeGlobals.shareScopeMap` maybe have not initialization, `RuntimeGlobals.shareScopeMap` value is `undefined`

**Comment by evilebottnawi** [comment]
@shaodahong feel free to send a PR

**Comment by mannymu** [comment]
I have the same problem, did you solve it
