### ISSUE TITLE
eval source-map devtool options cause syntax error on output from inline worker-loader

### ISSUE THREAD

**Issue by wavebeem** [webpack/webpack#11417]
# Bug report

When using any of the following devtool options:

- `eval-source-map`
- `eval-cheap-source-map`
- `eval-nosources-source-map`
- `eval-cheap-module-source-map`
- `eval-nosources-cheap-source-map`
- `eval-nosources-cheap-module-source-map`

Any worker loaded via `worker-loader` will contain a malformed `sourceURL`
comment, causing a syntax error and making the inline worker fail to load.

**What is the current behavior?**

```
SyntaxError: unexpected token: ":"
```

The web worker can be instantiated (i.e. `new MyWorker()`), but its code has a
syntax error, so it doesn't work.

**If the current behavior is a bug, please provide the steps to reproduce.**

See my [minimal reproduction example][1]
repository on GitHub for a full repo with source code and instructions.

[1]: https://github.com/wavebeem/bug-report-webpack-worker-devtool

The gist of it is `npm install`, `npm start`, open the browser, open the JS
console, observe the syntax error.

> If your issue is caused by a plugin or loader, please create an issue on the
> loader/plugin repository instead

While I am using `worker-loader`, it seems the error here is actually with
webpack's `devtool` option, since everything works with that turned off or set
to certain values. If you disagree, I'm happy to open the bug against
https://github.com/webpack-contrib/worker-loader instead.

**What is the expected behavior?**

It should be possible to use any of the `eval*source-map` devtool options with
the output from an inline `worker-loader`.

**Other relevant information:**

| name               | version                  |
| ------------------ | ------------------------ |
| Operating System   | macOS Catalina (10.15.6) |
| Node.js            | `12.18.2`                |
| webpack            | `4.44.1`                 |
| webpack-cli        | `3.3.12`                 |
| webpack-dev-server | `3.11.0`                 |
| worker-loader      | `3.0.2`                  |

**Comment by sokra** [comment]
@evilebottnawi seem to be related to the piece of code in worker-loader that removes the SourceMap comment when no-fallback is set.

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/webpack-contrib/worker-loader/issues/285
