### ISSUE TITLE
Hot Module Reload fails for web worker (document API doesn't exist)

### ISSUE THREAD

**Issue by ncoder** [webpack/webpack#11416]
# Bug report

**What is the current behavior?**

Hot Module Reloading fails with

```
log.js:26 [HMR] Update failed: ReferenceError: document is not defined
    at hotDownloadUpdateChunk (http://localhost:8080/meshworker.bundle.js:14:25)
    at hotEnsureUpdateChunk (http://localhost:8080/meshworker.bundle.js:322:13)
    at http://localhost:8080/meshworker.bundle.js:288:14
```

In the webworker when one of it's dependencies needs to be refreshed.

this injected function: 
```
/******/ 	function hotDownloadUpdateChunk(chunkId) {
/******/ 		var script = document.createElement("script");
/******/ 		script.charset = "utf-8";
/******/ 		script.src = __webpack_require__.p + "" + chunkId + "." + hotCurrentHash + ".hot-update.js";
/******/ 		if (null) script.crossOrigin = null;
/******/ 		document.head.appendChild(script);
/******/ 	}
```

fails because there is no "document" api inside a web worker.

**If the current behavior is a bug, please provide the steps to reproduce.**

I've got a simple config with two entrypoints, one for my main module, one for the worker.

```
module.exports = {
    entry: {
        main: './src/index.ts',
        meshworker: './src/meshworker/index.ts'
    },

```
I use the temp workaround for the "window" crash issue in web workers
```
    output: {
        filename: '[name].bundle.js',
        path: path.resolve(__dirname, 'dist'),
        globalObject: 'this'
    },
```

I start my webworker with a direct manual load. (not using the worker loader)
`var meshWorker = new Worker('meshworker.bundle.js');`

start the thing with
`webpack-dev-server --dev --hot`

then touch one of the worker's bundle's depdencies.

**What is the expected behavior?**

At a minium, a full reload.

That piece of code that uses script tags on the document to load a script looks important. I'm not sure it's possible to simply "fix" this. 
Some suggestions:
Inside dev-server, i see the error response code:

```
	.catch(function(err) {
				var status = module.hot.status();
				if (["abort", "fail"].indexOf(status) >= 0) {
					log(
						"warning",
						"[HMR] Cannot apply update. Need to do a full reload!"
					);
					log("warning", "[HMR] " + log.formatError(err));
					window.location.reload();
				} else {
					log("warning", "[HMR] Update failed: " + log.formatError(err));
				}
			});
```

It fails to even fallback to the full reload, as the status is "prepare", instead of abort or fail. If the whole page reloaded, we'd be at least in a bit better shape.

Another useful thing is if I could somehow know in the main thread that my web worker needs reloading. This may be possible, I just don't know how. Even better if I could know which submodule dependency failed to load. I know you can do this under normal circumstances in the main thread; Unsure if you can do this cross-thread like this.

**Other relevant information:**
webpack version:  
4.44.1

**Comment by ncoder** [comment]
Looks like you can't just dumbly add "prepare" to the list of failure code; "window.location.reload();" won't work either in the webworker. needs to bubble up somehow.

**Comment by evilebottnawi** [comment]
@ncoder You need to use `worker-loader` or multi compiler mode with `target: 'webworker'` (https://webpack.js.org/configuration/target/), you can't use multiple entry points for different targets
