### ISSUE TITLE
config __dirname: false not working

### ISSUE THREAD

**Issue by lukywong** [webpack/webpack#11422]
# Bug report

**What is the current behavior?**
webpack.config.js

```javascript
{
    target: 'electron-main',
    node: {
      __dirname: false
    },
    entry: {
      main: './src/main.ts'
    },
}
```
main.ts
``` javascript
console.log(__dirname)
```

``` shell
$ node main.js
```
ouput '/'

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

it should output the absolute path 

**Other relevant information:**
webpack version:  4.44.1
Node.js version: 12.18.3
Operating System: macOS 10.15.6
Additional tools:

**Comment by evilebottnawi** [comment]
Duplicate, please read https://github.com/webpack/webpack/issues/1599, also please read https://github.com/electron/electron/issues/3204

**Comment by lukywong** [comment]
@evilebottnawi thanks, it is a walk-around indeed on electron, but when i target to node, the output makes no different whether config `__dirname` true or false, that's really wired when i tried to compile typescript for a server running app

**Comment by evilebottnawi** [comment]
@lukywong change target on node

**Comment by lukywong** [comment]
> @lukywong change target on node

Yes, i did, but it makes no different
