### ISSUE TITLE
LimitChunkCountPlugin max chunks not working for dynamic import

### ISSUE THREAD

**Issue by LLGZONE** [webpack/webpack#11431]
# Bug report

**What is the current behavior?**
When use LimitChunkCountPlugin with dynamic import for multi entry, webpack will generate chunks even set maxChunks = 1.

**If the current behavior is a bug, please provide the steps to reproduce.**
The [repo](https://github.com/LLGZONE/limitchunkplugin-demo) can show the current behavior, just as the image shown below.
![image](https://user-images.githubusercontent.com/22257849/92246239-12077480-eef8-11ea-965a-98128916bb08.png)

**What is the expected behavior?**
I think webpack should only generate the entry chunk with LimitChunkCountPlugin for each entry and prevent any additional chunks.

**Other relevant information:**
webpack version:  4.44.1
Node.js version:  v12.18.2
Operating System: MacBook-Pro

**Comment by quanglam2807** [comment]
Same problem

**Comment by alexander-akait** [comment]
bump

**Comment by firouzyar** [comment]
i have same problem even tho i have one entry and i want to have one bundle.js instead of 1,2 and main chunk.

**Comment by cartok** [comment]
same here

**Comment by cartok** [comment]
For now the only workaround I found is this:

https://v4.webpack.js.org/plugins/limit-chunk-count-plugin/

```
plugins: [
      // Also add lazy loaded chunks to the bundle
      new webpack.optimize.LimitChunkCountPlugin({
        maxChunks: 1,
      }),
    ],
```

**Comment by alexander-akait** [comment]
Still valid

**Comment by vankop** [comment]
Can not reproduce with `webpack@5`. Feel free to create a repro with webpack@5

**Comment by carlovenus** [comment]
Hi, I have the same issue using webpack 5.68.0

`new webpack.optimize.LimitChunkCountPlugin({
                        maxChunks: 1,
                    })`

and i still get chunks

**Comment by vankop** [comment]
@carlovenus Could you create a repro?

**Comment by carlovenus** [comment]
> @carlovenus Could you create a repro?

It is a Vue/Quasar application, and I have a  quasar.conf.js file where I can configure/extend Webpack: 

`extendWebpack (cfg) {

                cfg.plugins.push(
                    new webpack.optimize.LimitChunkCountPlugin({
                        maxChunks: 1
                    })
                )

}`

The build is successful, not getting errors, but js and css files are chunked.
As a ref: [https://quasar.dev/quasar-cli/quasar-conf-js#property-build](url)

**Comment by vankop** [comment]
what webpack version you are using?

**Comment by carlovenus** [comment]
@vankop 5.68.0

**Comment by mohsinulhaq** [comment]
@carlovenus what was the solution?

**Comment by mehmetcozdemir** [comment]
@mohsinulhaq you can set [this option](https://webpack.js.org/configuration/module/#moduleparserjavascriptdynamicimportmode) to `eager` if you just want to get rid of dynamic import chunks.

**Comment by mohsinulhaq** [comment]
@mehmetcozdemir thanks for the help! This didn't work, probably because my chunks are being created by Web Workers and not any dynamic imports. Is there any way to control the chunks created via `new Worker`?

**Comment by alexander-akait** [comment]
@mohsinulhaq You can use multi compiler mode and compiler webworker before compiler compilation (also good for perfomance if you don't change worker a lot)

**Comment by hoang-dao** [comment]
@vankop the issue can still be reproducible following the posted repo (https://github.com/LLGZONE/limitchunkplugin-demo) even with updated dependencies
```json
"dependencies": {
    "webpack": "^5.74.0",
    "webpack-cli": "^4.10.0"
}
```
* webpack: 5.74.0
* webpack-cli: 4.10.0
* node: v16.13.1
* OS: MacOS Monterey

In my case, my project is a monorepo which contains many typescript serverless functions, I follow the entry descriptor as a workaround to build a single bundle for every entry point https://webpack.js.org/configuration/entry-context/#entry-descriptor.

Refer from the posted repo, this is my updated config:
// webpack.config.js
```
const path = require('path')
const webpack = require('webpack')

module.exports = {
  target: 'node',
  entry: {
    a: {
      import: './a.js',
      filename: '[name].js'
    },
    b: {
      import: './b.js',
      filename: '[name].js'
    }
  },
  output: {
    path: path.resolve(__dirname, './build'),
    chunkLoading: false,
  },
}
```

Hope it can help!

**Comment by alexander-akait** [comment]
So all dynamic imports now is not lazy and you will get one chunk

**Comment by icy0307** [comment]
@alexander-akait  
I am little confused about the relationship between `LimitChunkCountPlugin`, `SplitChunkPlugin` and  `module.parser.javascript.dynamicImportMode`.
What is the relationship between minChunks, maxAsyncRequest, maxInitialRequests in splitchunk and maxChunks in SplitChunkPlugin?
If I set module.parser.javascript.dynamicImportMode something other than 'eager', who has the highest priority?

**Comment by alexander-akait** [comment]
`LimitChunkCountPlugin` just merge chunks, `SplitChunkPlugin` merge them, `LimitChunkCountPlugin` has more priority over `SplitChunkPlugin` (if you added it), `module.parser.javascript.dynamicImportMode` is just a directive how webpack handles dynamic import - i.e. create a new chunk or consider it as part of intiail code (`eager`) and etc (for example - `SplitChunkPlugin` can split dynamic chunks on multiple chunks and create more chunks)

**Comment by icy0307** [comment]
Sorry, I'm still a little bit confused about  "SplitChunkPlugin merge them". What are they?
`SplitChunkPlugin ` already has `minRemainingSize`, and `minSize`, to set the limit on size. And `maxAsyncRequest`, `maxInitialRequests` limit chunk's count. Should one use LimitChunkCountPlugin and SplitChunkPlugin?

**Comment by alexander-akait** [comment]
> Should one use LimitChunkCountPlugin and SplitChunkPlugin?

Depends on what you want to get, but most often - No. 

`LimitChunkCountPlugin` most often used when you set `target: "node"` to create one executable file.
