### ISSUE TITLE
Long time to load asset-manifest.json.  

### ISSUE THREAD

**Issue by ROBOTIS-David** [webpack/webpack#11434]
# Bug report

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: Linux Ubuntu 16.04
Additional tools: atom

Hi, I am running one git page and I received one feedback from China user. When my git page is loaded from China, there is significant requesting time when loading. 

25 | http://emanual.robot.../asset-manifest.json | text/html; charset=utf-8 | 66.851 s | - | 125 ms | - | 408 ms | 3815 ms | 11.6 KB | - | 404 | -
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

Is there way to improve the speed for the asset-manifest.json? 

Or just delete? I am not sure what the asset-manifest.json is, and I can't find .json file from my reposi or any folder too. 

Thank you for reading ! 

Have a good day :)

For your reference, below is the information on the asset-manifest.json file when loaded. 

- Request 25: http://emanual.robotis.com/asset-manifest.json
URL: http://emanual.robotis.com/asset-manifest.json
Host: emanual.robotis.com
Error/Status Code: 404
Request Start: 66.851 s
Initial Connection: 125 ms
Time to First Byte: 408 ms
Content Download: 3815 ms
Bytes In (downloaded): 11.6 KB
Bytes Out (uploaded): 0.0 KB
Request Headers:

GET /asset-manifest.json HTTP/1.1
Host: emanual.robotis.com
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0 PTST/19.04
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: http://emanual.robotis.com/
origin: http://emanual.robotis.com
Connection: keep-alive
Response Headers:

HTTP/1.1 404 Not Found
Content-Type: text/html; charset=utf-8
Server: GitHub.com
ETag: W/"5ecdc066-23eb5"
Access-Control-Allow-Origin: *
Content-Encoding: gzip
X-Proxy-Cache: MISS
X-GitHub-Request-Id: CDDE:601A:588FF:5FBAC:5ECF5663
Content-Length: 11854
Accept-Ranges: bytes
Date: Thu, 28 May 2020 06:12:52 GMT
Via: 1.1 varnish
Age: 0
Connection: keep-alive
X-Served-By: cache-tyo19939-TYO
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1590646372.298839,VS0,VE172
Vary: Accept-Encoding

**Comment by sokra** [comment]
I can't help you here. This isn't webpack-related.

**Comment by ROBOTIS-David** [comment]
Ops 

Sorry about that, but thank you for quick reply
