### ISSUE TITLE
Webpack5: how to get module parents/dependants (or deps graph) from loader

### ISSUE THREAD

**Issue by whitecolor** [webpack/webpack#11432]
In one of my loaders, I need to know parents/dependants that the current module (handled by loader) was requested by. For this in webpack4 I used a hacky way to do this with access to `this._module.reasons`, but in webpack 5 `reasons` prop does not exist on `_module` object (which is a too deprecated prop). So how the actual task of getting requested parents from within loader may be accomplished in Webpack 5?

**Comment by evilebottnawi** [comment]
I think you need to rewrite the loader to the plugin, it is not safe using `this._module.reasons` in the loader in webpack@4, the loader should not do this stuff, please provide link on loader or more information if you need help, I close issue because the issue template was removed, anyway if you will provide more information I will help you here

**Comment by whitecolor** [comment]
This is the code of loader https://github.com/whitecolor/lp-loader/blob/master/src/lp-loader.ts it produces language bundles by combining language for files from different dicts based on where those dicts are required.

Didn't write the plugins, so advice would be appreciated.

**Comment by evilebottnawi** [comment]
You really need plugin for this case, using loader is bad idea, just use hook, I think you can use this hook https://github.com/webpack/webpack/blob/master/lib/Compilation.js#L406

**Comment by whitecolor** [comment]
@evilebottnawi 
Hope you don't mind me asking some questions here. This is not an easy thing to get the right way (API) for doing things in webpack internals.

You proposed to use `afterOptimizeTree` hook, where I believe I should add new modules and chunks which currently my loader creates using `require.ensure` API. 

A couple of questions:

1) How to add/load new modules from known filePath in this hook?
2) How to change the code of an already loaded module?
