### ISSUE TITLE
Bugged as hell

### ISSUE THREAD

**Issue by Yuri6037** [webpack/webpack#11430]
# Bug report
Whenever application assets are outside the source folder webpack bugs completeley throwing all kinds of errors and warnings:
- Tries to load .txt LICENSE non sense
- Tries to load .ts files even more non sense
- Tries to load .tsx files also non sense
- Tries to load .html files also non sense

And also by changing:

```require("../assets/" + name + ".css");```

with

```require("../" + name);```

Webpack will now try to include Linux root file system "/"!!!!! Amazing non sense.
When it does that be sure to quickly run a SIGKILL to avoid crashing HDD!!

**What is the current behavior?**
Webpack will attempt to load non-sense files including linux root file system.

**If the current behavior is a bug, please provide the steps to reproduce.**
And also by changing:

```require("../assets/" + name + ".css");```

with

```require("../" + name);```

**What is the expected behavior?**
I think Webpack isn't supposed to be acting like a virus indexing the entire HDD...

**Other relevant information:**
webpack version:  4.44.1
Node.js version: 10.19.0
Operating System: Pop!_OS 20.04
Additional tools: Electron JS

**Comment by evilebottnawi** [comment]
Please provide configuration, webpack never do it

**Comment by Yuri6037** [comment]
main.config.js (only for electron bootstrap no react):
https://github.com/ERPMod/electron-react-ts/blob/master/webpack/main.config.js

react.config.js (where things are getting bad, ran exclusively by webpack-dev-server):
https://github.com/ERPMod/electron-react-ts/blob/master/webpack/react.config.js

**Comment by evilebottnawi** [comment]
No problems, all works fine

**Comment by Yuri6037** [comment]
Here look, not all works fine as you can see:

```
[./src/App.tsx] 699 bytes {main} [built]
    [./src/Assets.ts] 370 bytes {main} [built]
    [./src/Screens/LoadScreen.tsx] 1.63 KiB {main} [built]
        + 75 hidden modules
    
    WARNING in ./assets/html/index.html 1:0
    Module parse failed: Unexpected token (1:0)
    You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
    > <!doctype html>
    | <html lang="en">
    |   <head>
     @ ./assets sync ^\.\/.*$ ./html/index.html
     @ ./src/Assets.ts
     @ ./src/App.tsx
    Child HtmlWebpackCompiler:
         1 asset
        Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
        [./node_modules/html-webpack-plugin/lib/loader.js!./assets/html/index.html] 560 bytes {HtmlWebpackPlugin_0} [built]
```

**Comment by evilebottnawi** [comment]
Invalid configuration, but how it related to?

> Webpack will now try to include Linux root file system "/"!!!!! Amazing non sense.
> When it does that be sure to quickly run a SIGKILL to avoid crashing HDD!!

**Comment by evilebottnawi** [comment]
You try to import `html` file without `html-loader`

**Comment by Yuri6037** [comment]
When I put ../ sometimes it tries indexing the entire HDD it's just totally random. The best way to get it to bug is to try variants of `require("../" + name)`.
It's just totally random.

But i'm not importing HTML

**Comment by evilebottnawi** [comment]
> When I put ../ sometimes it tries indexing the entire HDD it's just totally random.

Why do you think it?, where you store project? Using `../` means include all files from up directory

**Comment by evilebottnawi** [comment]
I don't understand you

**Comment by Yuri6037** [comment]
Do you mean that Webpack ignores the variable and just uploads everything that is referenced by the prefix?

**Comment by evilebottnawi** [comment]
> Do you mean that Webpack ignores the variable and just uploads everything that is referenced by the prefix?

webpack is static analyzer, we don't know value of variable, so we include all modules in bundle and when you try to load `../assets/${something}` we just return one module from all modules

**Comment by Yuri6037** [comment]
That's terrible! What if I include 10 ttf files but only use the first 3 in code well it's going to load the 10 files and take more time. Why is that? Is there any way to disable this?

**Comment by evilebottnawi** [comment]
> That's terrible! 

Change your tone

> What if I include 10 ttf files but only use the first 3 in code well it's going to load the 10 files and take more time.

Do not use context `require`/`import`

>  Why is that?

webpack is static analyzer

> Is there any way to disable this?

Do not use extra context request, it is described in docs https://webpack.js.org/api/module-methods/#dynamic-expressions-in-import

**Comment by evilebottnawi** [comment]
You yourself say that you want to include the entire folder(s) in the bundle, the webpack does this

**Comment by Yuri6037** [comment]
Well I did not want that, I did not tell to do this, it just converts my string into a * recursive one. That's the only problem. I'm not referencing every files. I thought Webpack was smart enough to understand that what is inside of assets should not be packed as one big blob but I guess not...

**Comment by evilebottnawi** [comment]
@Yuri6037 

>  I thought Webpack was smart enough to understand that what is inside of assets should not be packed as one big blob but I guess not...

You can do it, using non standard method https://webpack.js.org/api/module-methods/#requirecontext and use `filter` to achieve this, but I do not recommend do it, it deoptimization your bundle, use `import`

**Comment by Yuri6037** [comment]
At least thanks for the info, now that I know what webpack really does, I can find ways to optimize differently
