### ISSUE TITLE
handle sass import in webpack loader

### ISSUE THREAD

**Issue by wenyanqi** [webpack/webpack#11448]
## Feature request

**What is the expected behavior?**
I want to handle sass import file in the webpack loader.
Just like this:
```
// style.scss
@import './theme.scss';
p {
   color: white;
}
```
I want webpack loader can handle 'theme.scss'

**What is motivation or use case for adding/changing the behavior?**
I want to handle sass file before sass-loader compiled.

**Comment by evilebottnawi** [comment]
Just write loader and put it after `sass-loader`:
```
{
  loader: 'sass-loader'
},
{
  loader: 'my-loader'
}
```

Please read https://webpack.js.org/concepts/loaders/

**Comment by wenyanqi** [comment]
> Just write loader and put it after `sass-loader`:
> 
> ```
> {
>   loader: 'sass-loader'
> },
> {
>   loader: 'my-loader'
> }
> ```
> 
> Please read https://webpack.js.org/concepts/loaders/

I have try in this way. But loader can only handle "style.scss", can't get "./theme.scss".
