### ISSUE TITLE
 Added this error code when testing the document code       use: 'imports-loader?this=>window' 

### ISSUE THREAD

**Issue by uljdcwy** [webpack/webpack#11441]
> shimming@1.0.0 build E:\shimming
> webpack --config webpack.config.js

Insufficient number of arguments or no entry found.
Alternatively, run 'webpack(-cli) --help' for usage info.

Hash: e6ffcc5de24c02225d00
Version: webpack 4.44.1
Time: 39ms
Built at: 2020-09-08 4:50:53 ├F10: PM┤

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'de
velopment' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mo
de/

ERROR in Entry module not found: Error: Can't resolve 'imports-loader' in 'E:\shimming'
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! shimming@1.0.0 build: `webpack --config webpack.config.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the shimming@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\zhengxiya\AppData\Roaming\npm-cache\_logs\2020-09-08T08_50_53_963Z-debug.log

**Comment by evilebottnawi** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
