### ISSUE TITLE
[Webpack 5] Long time for rebuilds

### ISSUE THREAD

**Issue by WaveString** [webpack/webpack#11443]
# Bug report

**What is the current behavior?**

I get very long rebuilds on Webpack 5, about 1 minutes.

<img width="643" alt="webpack-5-rebuild" src="https://user-images.githubusercontent.com/7781512/92485353-075d2000-f215-11ea-928a-0f51f9c7c1e2.png">

But on weback 4 I get much less rebuild time, about 4 seconds.
<img width="594" alt="webpack-4-rebuild" src="https://user-images.githubusercontent.com/7781512/92485567-50ad6f80-f215-11ea-89d5-380e50544684.png">

Also when I reduce the number of imports (from 8000 to 2400 watchers), rebuild takes 7 seconds
<img width="596" alt="webpack-5-rebuild-2400-only-direct" src="https://user-images.githubusercontent.com/7781512/92490645-79d0fe80-f21b-11ea-82a3-ff33240b948c.png">

I prepared the results of the number of watchers for the rebuild time
| Number of watchers   | Seconds |
| ------------- | ------------- |
| 8000  | 60 |
| 7300  | 55 |
| 6800  | 30 |
| 5400  | 14 |
| 2400  | 7 |

I tried to remove all plugins and partially removed loaders (except `"babel-loader": "8.1.0"`, `style-loader`). But there was no critical reduction in time.

**If the current behavior is a bug, please provide the steps to reproduce.**
Project must have many files to reproduce.

**What is the expected behavior?**
Rebuild time comparable to webpack 4

**Other relevant information:**
webpack version:  5.0.0-beta.29
Node.js version: 14.0.0
Operating System: macOS Catalina 10.15.6
Additional tools: yarn 1.22.4

**Comment by evilebottnawi** [comment]
@WaveString pelase provide configuration file

**Comment by evilebottnawi** [comment]
Also can you provide examples of removed `import`s?

**Comment by WaveString** [comment]
> Also can you provide examples of removed imports?

It's just usual packages from node_modules

**Comment by evilebottnawi** [comment]
@WaveString Sorry, without reproducible test repo/configurations hard to say what decrease perf, maybe some plugins or loaders (use old API or some hacks), maybe some options in the configuration, nobody knows

**Comment by sokra** [comment]
At least the configuration would be helpful.
Any custom watching config/plugins?

**Comment by WaveString** [comment]
I think I found the reason, it's `MiniCssExtractPlugin.loader`. When I replace it to a `style-loader`, rebuild time is acceptable.

![style-loader](https://user-images.githubusercontent.com/7781512/92598395-f1ae3000-f2d2-11ea-8fa3-b5a020f075df.png)

Config for css
```
test: /\.css$/,
use: [
  {
  MiniCssExtractPlugin.loader,
  'css-loader'
]
```

versions:
`"mini-css-extract-plugin": "0.11.1"`
 `"css-loader": "4.3.0"`

**Comment by chenxsan** [comment]
It's advised to use `MiniCssExtractPlugin.loader` only for production.

**Comment by evilebottnawi** [comment]
@WaveString What is version are you use?

**Comment by WaveString** [comment]
@evilebottnawi 
```
"webpack": "5.0.0-beta.29"
"mini-css-extract-plugin": "0.11.1" // also I tried with "mini-css-extract-plugin": "0.10.0"
"css-loader": "4.3.0" // also I tried with "css-loader": "3.5.3"
"babel-loader": "8.1.0"
```

**Comment by evilebottnawi** [comment]
@WaveString we need reproducible test repo (you can create minimum) to investigate places with poor performance, please do not ignore requests on providing configuration, otherwise nobody will help you and issue will be closed

**Comment by sokra** [comment]
Seem to be a caching issue in mini-css with webpack 5

**Comment by WaveString** [comment]
I prepared [repository](https://github.com/WaveString/webpack-5-example), rebuilding on webpack 5 takes 9 seconds. You can change to webpack 4, rebuilding takes much less time.

<img width="667" alt="webpack5" src="https://user-images.githubusercontent.com/7781512/92724268-8167e300-f394-11ea-80ef-4583af08bb46.png">

**Comment by evilebottnawi** [comment]
@WaveString Can you try https://github.com/webpack-contrib/mini-css-extract-plugin/releases/tag/v0.11.2?

**Comment by evilebottnawi** [comment]
@WaveString hm, strange, I tested it locally:

webpack@4
```
css-loader - 13s - 14s
mini-css-extract-plugin - 26s-30s
```

webpack@5
```
css-loader - 14s-15s
mini-css-extract-plugin - 28-32s
```

almost no regressions

**Comment by WaveString** [comment]
@evilebottnawi

Tried `"mini-css-extract-plugin": "0.11.2"`, didn't help.

> @WaveString hm, strange, I tested it locally:

What time is it, is it rebuild time?
When I use `"webpack": "4.44.1"` and change `src/index.jsx`, rebuild time was instant.
<img width="498" alt="webpack4" src="https://user-images.githubusercontent.com/7781512/93003339-0ce59d80-f568-11ea-8580-5c7502228b60.png">

**Comment by sokra** [comment]
> What time is it, is it rebuild time?

That does look like initial build time, not incremental build time @evilebottnawi

**Comment by evilebottnawi** [comment]
@WaveString Please provide full `stats` output with time and other information, I can't reproduce locally or provide steps

**Comment by WaveString** [comment]
@evilebottnawi 
Steps for reproduce:

For Webpack 5:

1. yarn install
2. yarn start
3. change file `src/index.jsx` (e.g. `Hello Webpack!` -> `Hello Webpack!!!`)
4. get rebuild stat in terminal

For Webpack 4:

1. yarn add -D webpack@4.44.1
2. yarn install
3. yarn start
4. change file `src/index.jsx` (e.g. `Hello Webpack!` -> `Hello Webpack!!!`)
5. get rebuild stat in terminal


`stats`:

- [webpack4.json](https://drive.google.com/file/d/1C0oUqwb4IcAAYlae66VmGuGoIWtb19AP/view?usp=sharing)
- [webpack5.json](https://drive.google.com/file/d/1AFIg9aR4ldWfwlk_JRonO5WEemDYdoOV/view?usp=sharing)

but its only first build

**Comment by sokra** [comment]
Ok I've found the issue. The time is spend in a deprecated method that emulates the old behavior by copying all timestamps. This is called very often. We can cache it to improve the performance. And CssModule should implement `needBuild` insteadof `needRebuild`. The method is also missing a deprecation warning, which probably would have catched this earlier.

![image](https://user-images.githubusercontent.com/1365881/93188615-7b318800-f741-11ea-8ef3-3c0c405513df.png)

See also `Module.needBuild` implementation.

**Comment by evilebottnawi** [comment]
@sokra It is possible have two methods `needRebuild` and `needBuild` for backward compatibility?

**Comment by sokra** [comment]
> @sokra It is possible have two methods `needRebuild` and `needBuild` for backward compatibility?

Yes you can have both.
