### ISSUE TITLE
require.context() and export default runtime error

### ISSUE THREAD

**Issue by agustinCaire** [webpack/webpack#11444]
# Bug report

**What is the current behavior?**
if you use require.context(...) to load some modules and then you use "export default ..." then the generated code fails on runtime with the following message: `Cannot access '__WEBPACK_DEFAULT_EXPORT__' before initialization`

**If the current behavior is a bug, please provide the steps to reproduce.**
To reproduce simply create some files with default export and then require them somewhere using require.context(). See next examples:

### Example 1: 

In this case code will **fail**:

Source code:
```javascript
const modulesImport = require.context('./', false, /\.js$/);

modulesImport.keys().forEach(x => {
	
    modulesImport(x).default;
		
})

export default {}
```

runtime code:
```javascript
((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "default": () => __WEBPACK_DEFAULT_EXPORT__ /* ERROR HERE BECAUSE __WEBPACK_DEFAULT_EXPORT__ IS NOT INITIALIZED*/
/* harmony export */ });
var modulesImport = __webpack_require__("./src/store sync \\.js$");

modulesImport.keys().forEach(function (x) {
  modulesImport(x)["default"];
});
/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = ({});

/***/ }),

```
### Example 2:
If we move `export default` line before module imports it's **works fine**
source code:

```javascript
const modulesImport = require.context('./', false, /\.js$/);

export default {}

modulesImport.keys().forEach(x => {
	
    modulesImport(x).default;
		
})
```

runtime code:

```javascript
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "default": () => __WEBPACK_DEFAULT_EXPORT__
/* harmony export */ });
var modulesImport = __webpack_require__("./src/store sync \\.js$");

/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = ({});
modulesImport.keys().forEach(function (x) {
  modulesImport(x)["default"];
});

/***/ }),
```

**What is the expected behavior?**
it's expected that require.context() works well independent of the position of `export default` sentence.

**Other relevant information:**
webpack version:  5.0.0-beta.29
Node.js version: v12.16.1
Operating System: Arch linux
Additional tools:

**Comment by sokra** [comment]
Working as expected. It's a circular dependency and you must not access the default export before it's declaration.

**Comment by evilebottnawi** [comment]
@sokra maybe we can improve error reporting here?

**Comment by sokra** [comment]
The error is from the javascript engine we can't change it. But I think it's already pretty clear: "Cannot access ... before initialization"

**Comment by wangmeijian** [comment]
This is Babel's fault, right?

**Comment by Edge00** [comment]
Same problem. any idea yet？

**Comment by VictorGaiva** [comment]
I was able to find out what the issue was. I had the following files:

```
src/
├─ a.jsx // Imports c-1 with "import { C1 } from 'src/c'"
├─ b.jsx // Imports c-1 with "import C1 from 'src/c/c-1/index.jsx'"
├─ c/
│  ├─ index.jsx // Re-exports the default export component from "./c-1/index.jsx" as a named export 'C1'
│  ├─ c-1/
│  │  ├─ index.jsx // Has a component that is exported by default
```

This caused a circular dependency. To resolve the issue I changed the default importal at `src/b.jsx` to be the same as `src/a.jsx` and the issue was fixed.

**Comment by whatwg6** [comment]
Folder structure

```code
src/
|-- a.js  
|-- b/b.js  
|-- index.js
```

Original code
```code
// index.js
const modulesImport = require.context('./', true, /\.js$/);

modulesImport.keys().forEach(x => {
    modulesImport(x).default;
})

export default {}
```

Solution 1 Just remove export default {}
Solution 2 Exclude itself
```code 
modulesImport.keys().forEach(x => {
  if (x !== 'src/index.js') {
    modulesImport(x).default
  }
})
```
