### ISSUE TITLE
[webpack 4] externals, load local json file on runtime

### ISSUE THREAD

**Issue by shubhamdeodia** [webpack/webpack#11459]
I have a file uiConfig.json, it has some server URL, and the DevOps team changes the files based on the environment. I am trying to load this file on runtime using webpack.

So far I have tried the following.

```
//webpack.config.js
  
externals: {
   'uiConfig': JSON.stringify(require('./uiConfig.json'))
},
```
copied uiConfig at root path of build directory

```
//app.js

import uiConfig from 'uiConfig'
```
**What is the current behavior?**

url inside uiConfig is part of prod chunks

**What is the expected behavior?**

app should load the uiConfig at runtime to get the server url

What am I doing wrong? is this not how we are supposed to use externals?

**Comment by evilebottnawi** [comment]
- https://webpack.js.org/plugins/define-plugin/
- externals
- webpackIgnore
- fetch/Ajax on runtime

**Comment by evilebottnawi** [comment]
I cannot answer more precisely because you did not say the purpose of the file

**Comment by shubhamdeodia** [comment]
@evilebottnawi : I did mention, the purpose of file is to get some server URL, which will be used for authorization.

Also, many people have a similar issue, official documentation did mention that webpack will use external to load module on runtime, but never gave an example of how it can be used with a local file.

DefinePlugin will not useful, as what I am looking for is config, which can still be changed after the bundling is done.

**Comment by evilebottnawi** [comment]
@shubhamdeodia https://webpack.js.org/api/module-methods/#magic-comments

**Comment by shubhamdeodia** [comment]
@evilebottnawi 

 I did try it with fetch.

```
<script type="application/javascript"> 
        window.uiConfig = {}
          fetch('./uiConfig.json').then((response) => {
            return response.json();
          }).then((data) => {
            window.uiConfig = data
        })
    </script> 
```

But the behaviour is not consistent, what I mean, it doesn't always load the data before it start executing another scripts.

**Comment by evilebottnawi** [comment]
change your logic so that it works, we don't touch your `script` tag and `uiConfig.json`

**Comment by shubhamdeodia** [comment]
@evilebottnawi 

I understand what you are trying to say, but this should have been achievable throw webpack itself.

I want to tell webpack don't include and transform a particular JSON file because I will do it manually.

I did it so with the help of IgnorePlugin.

But after this point, I expect webpack to not touch my imports and keep as it is, instead I see, 

`{var e=new Error("Cannot find module '../uiConfig.json'")` in the bundle.

What are other ways, to tell webpack, that 
> hey webpack, I want to place json mannualy at a particular path, just reference that JSON and load it when requested. And please ignore the JSON from bundling.

**Comment by evilebottnawi** [comment]
@shubhamdeodia you can use `copy-webpack-plugin`

**Comment by shubhamdeodia** [comment]
@evilebottnawi 

I did, but what about the import.

So far webpack is helping me ignoring the JSON and letting me copy it.

But, How do tell webpack, not to evaluate the import statement, since I am ignoring the file, the import statement is evaluated to an error.

But the file is actually present (thanks to copy plugin)

```
new CopyPlugin(
                    [
                        {
                            from: path.resolve(__dirname, './', 'uiConfig.json'),
                            to: path.resolve(__dirname, './dist')
                        }
                    ]
                )
```

**Comment by evilebottnawi** [comment]
> So far webpack is helping me ignoring the JSON and letting me copy it.

webpack is bundle, if you don't need handle this file, use `copy-webpack-plugin` plugin, you should avoid non bundled files in bundle, anyway you can achieve this using:

```js
async function loadJson() {
return import(/* webpackIgnore */ './file.json').then((modules) => {})
}
```

**Comment by sokra** [comment]
externals is the best way to go.

e. g. If you have the config in a global var use `externals: { uiConfig: "var UICONFIG" }`
This allows `import config from "uiConfig"`
