### ISSUE TITLE
webpack 4.44.1 alias bug within webpack.config.ts file only

### ISSUE THREAD

**Issue by cainrus** [webpack/webpack#11452]
# Bug report

**What is the current behavior?**
Alias `{ "@/": path.join(__dirname, 'src') + '/'}` won't work within webpack.config.ts file, but works fine within webpack.config.js

**If the current behavior is a bug, please provide the steps to reproduce.**
set alias `{ "@/": path.join(__dirname, 'src') + '/'}`, add import like `@/config`

Alias can be fixed if we drop last slash: `{ "@": path.join(__dirname, 'src')}`, but is it right? Alias will match external module imports like `@babel/core`.

**What is the expected behavior?**

Should work same as webpack.config.js

**Other relevant information:**
webpack version:  4.44.1
Node.js version:  12.15.0
Operating System: mac os 10.15.6
Additional tools: "typescript@3.8.3"

**Comment by evilebottnawi** [comment]
Please report issue to `typescript`, if it works in `webpack.config.js`  then it works and there is nothing we can do on our side

**Comment by cainrus** [comment]
It also wont work when I call webpack.config.ts via ts-node api:
```
require('ts-node/register/transpileonly');
require('./webpack.config.ts');
```
I believe that, it's not totally typescript issue. But some incompatibility between both or shared packages like `glob` or some other packages.

When I call webpack with `--display-error-details` arg, then I see, that alias ```{"@/": `${path.join(__dirname, 'src')}/`}``` was not applied during module search. But next alias `{"@": path.join(__dirname, 'src')}` works fine.

**Comment by evilebottnawi** [comment]
@cainrus we don't use `glob`
