### ISSUE TITLE
handle sass import file in webpack loader (reopen #11448)

### ISSUE THREAD

**Issue by wenyanqi** [webpack/webpack#11451]
[see this](https://github.com/webpack/webpack/issues/11448)

@evilebottnawi please read again.

I have try in this way. But loader can only handle "style.scss", can't get "./theme.scss".

**Comment by evilebottnawi** [comment]
Please use stackoverflow for questions, it is bug tracker

**Comment by evilebottnawi** [comment]
Maybe you need https://github.com/sass/node-sass#importer--v200---experimental
