### ISSUE TITLE
Is there a way to split code more convenient?

### ISSUE THREAD

**Issue by dexbol** [webpack/webpack#1145]
Recently I make a single page application aka SPA by React.js. I need render page according the url by `pushstate` event. And I want to split code for every url. So one url accord a javascript file. For example:
```
if (url == 'index') {
    require.ensure([], function() {
        var Page = require('./page/index.js');
        React.render(<Page />, document.body);
    }
}

if (url == 'detial') {

...
```

I have dozens url and it seems too tedious. So I want encapsulate it. like something:

```
require.ensure([], function() {
    var Page = require('./page/' + pageid + '.js');
    React.render(<Page />, document.body);
}
```

But webpack will include all page module to one chunk. Could you have any idea to improve this ? Context ? That seems not for this case.

**Comment by amarant** [comment]
Look at [context](http://webpack.github.io/docs/context.html) and [bundle-loader](https://github.com/webpack/bundle-loader).
And don't forget to ask in the [gitter webpack](https://github.com/webpack/bundle-loader) or the [webpack channel in the react slack](https://reactiflux.slack.com/messages/webpack/)
I would try something like that :
(I didn't test it)
```javascript
function(pageid) {
  var context = require.context("bundle?lazy!./page/", false, /\.js$/);
  var Page = context('./' + pageid + '.js');
  React.render(<Page />, document.body);
}
````

**Comment by dexbol** [comment]
@amarant Thank you. It works. The code blew can be running.

```
function(pageid) {
    var context = require.context("bundle?lazy!./page/", false, /\.js$/);
    var waitTheChunk = context('./' + pageid + '.js');
    waitTheChunk(function(Page) {
            React.render(<Page />, document.body);
    });
}
```
