### ISSUE TITLE
Eval sourcemaps truncates [] characters and everything in-between

### ISSUE THREAD

**Issue by jasonwilliams** [webpack/webpack#11456]
Raised from https://github.com/vercel/next.js/issues/15823

## bug
Eval sourcemap doesn’t seem to support [] characters in the sources property. These characters get truncated and this causes nextjs to break.

## To Reproduce
1. Clone next.js and go to https://github.com/vercel/next.js/tree/master/examples/dynamic-routing (master branch or 9.5)
2. install dependencies, then run `yarn|npm run dev`
3. go to localhost and click "first post"
4. Now go into the `.next` folder, server -> pages -> post -> [id].js
5. Search for `/***/ "./pages/post/[id]/index.js":`
6. Select the base64 content and run `pbpaste | base64 -D` on the command line
6. inspect the JSON output.

```json
{"version":3,"sources":["webpack:///./pages/post//index.js?a773"]}
```
notice `id` has been truncated in the url.
This has broken debugging.

Now, still in the same folder (dynamic routing), change the next.js version in the package.json to 9.3.6
1. yarn install
2. yarn dev
3. same as before navigate to the first post
4. inspect `static/development/pages/post/[id].js.map`

```json
{"version":3,"file":"static/development/pages/post/[id].js","sources":["webpack:///webpack/bootstrap","webpack:///external \"next/dist/next-server/lib/router-context.js\""]}
```

You can see `file` is set.

The breakage happened because next.js switched from inline-source-map to eval-source-map

**Comment by evilebottnawi** [comment]
@jasonwilliams webpack@4 or webpack@5?

**Comment by jasonwilliams** [comment]
@evilebottnawi webpack 4

**Comment by jasonwilliams** [comment]
@evilebottnawi did you need any more info?

**Comment by evilebottnawi** [comment]
@jasonwilliams can you test it using webpack@5?

**Comment by jasonwilliams** [comment]
> @jasonwilliams can you test it using webpack@5?

Sadly not, it won't even build when i try webpack@5. I have a lot of errors some i've fixed but some dependencies faily completely.

**Comment by evilebottnawi** [comment]
@jasonwilliams maybe you can create isolated reproducible test repo?

**Comment by jasonwilliams** [comment]
Hi @evilebottnawi 

I've managed to create a test case:
https://github.com/jasonwilliams/webpack-sourcemap-testcase (I've added the output in the readme)

Interestingly it doesn't truncate the `[]` in the output. However i do get `.js.js` twice which is odd.

I now wonder if this bug lies somewhere in Next's codebase or im missing something that they're doing in my testcase

**Comment by evilebottnawi** [comment]
I will look at this in near future

**Comment by evilebottnawi** [comment]
Sorry for delay, it is bug, you are right

**Comment by evilebottnawi** [comment]
Try to fix it for webpack@5 tomorrow, we have a problems for all files contains `[id]`/`[hash]`/`[query]`/etc

**Comment by jasonwilliams** [comment]
@evilebottnawi that's great news thanks!
Do you know if this fix will be backported to v4? Quite a lot of us can't upgrade to v5 just yet for various reasons (also the fact its still in beta)

**Comment by evilebottnawi** [comment]
@jasonwilliams I'm afraid not, only security fixes for webpack@4, webpack@5 is rc and will be release `2020-10-10`, migration is not a hard

**Comment by jasonwilliams** [comment]
@evilebottnawi ok no problem, is this issue linked to a PR anywhere? No worries if not was just wondering.

**Comment by evilebottnawi** [comment]
@jasonwilliams unfortunately I did not start work, too many issues after webpack@5

**Comment by jasonwilliams** [comment]
This issue also affects webpack5, so I don’t know if it needs the label also? I hope it doesn’t get left behind now that activity is focused on v5 😔
