### ISSUE TITLE
When using `minimize: true`, the `sources` in the resulting sourcemap only lists one file

### ISSUE THREAD

**Issue by abettadapur** [webpack/webpack#11461]
# Bug report

I am having trouble creating accurate source-maps, using `ts-loader` and the built in `terser` plugin.

**What is the current behavior?**
The sourcemap generated with `minimize: false` has the correct number of sources
```
"sources":["webpack:///webpack/bootstrap","webpack:///./node_modules/tslib/tslib.es6.js","webpack:///external \"assert\"","webpack:///./node_modules/rxjs/_esm5/index.js".............]
```

Simply flipping the `minimize: true` option on, produces a sourcemap with `sources` that point to a file that does not and has never existed

```
"sources":["webpack:///<path_to_entry>/extension.js"]
```

**If the current behavior is a bug, please provide the steps to reproduce.**
* Have a project with `ts-loader`
* Enable production mode
* Use the `SourceMapDevTool` plugin
* With `{minimize: false}`, sourcemaps are correct
* With `{minimize: true`}, sourcemaps are incorrect

**What is the expected behavior?**
The `minimize` option should have no impact on the resulting sourcemap sources.

**Other relevant information:**
webpack version:  4.44.1
Node.js version: 12
Operating System: Any
Additional tools: `ts-loader`

**Comment by evilebottnawi** [comment]
@webpack-bot move to webpack-contrib/terser-webpack-plugin
