### ISSUE TITLE
[Feature Request] Add `init` phase for initializing loader when webpack process starts

### ISSUE THREAD

**Issue by billykwok** [webpack/webpack#11460]
## Feature request

Currently, a typical loader is written with the following structure.

```javascript
import foo from 'foo';
import { getOptions } from 'loader-utils';
import validateOptions from 'schema-utils';
import schema from './schema';

export function pitch(remainingRequest, precedingRequest, data) {
  data.value = foo.bar(remainingRequest, precedingRequest);
};

export default function loader(source) {
  // Initialization
  const options = getOptions(this);
  validateOptions(schema, options, 'Example Loader');
  const transform = foo.init(options);
  // Transformation
  const transformed = transform(source, this.data.value);
  return `export default ${JSON.stringify(transformed)}`;
}
```

The loader function is executed statelessly each time an asset needs to be compiled. This looks nice and clean.

However, there are occasions when initialization is expensive. And the fact that they are run every time an asset is compiled (assuming no caching) would slow down the build significantly. When there are `n` assets to be compiled, the same code runs `n` times.

While some option-independent initialization can be done simply by executing in the module scope, some of them require reading the options object in order to be set up properly. Currently, there is no way to avoid repeatedly executing the same initialization code every time the loader runs.

This feature request proposes a new phase in the loader lifecycle called `init` (feel free to propose better name).

Like the `pitch` phase, `init` is defined by exporting a named function.

Unlike `pitch` and `loader`, `init` has no access to any source - only the `options` object. It only re-runs when the `options` itself changes or upon startup, regardless of the changes in `source`. As a result, repeated runs happen very rarely because Webpack usually requires a restart when config changes (may not be the case in the future but you get the point). This minimizes the unnecessary re-computation for initializing the loader code.

The object returned by `init()` is passed to `pitch()` and `loader()` as an argument (or as a property in `this`, welcome suggestions). Also, all `init()`, `pitch()`, and `loader()` are still required to be stateless (same input, same output).

The above loader can now be rewritten as below.

```javascript
import foo from 'foo';
import { getOptions } from 'loader-utils';
import validateOptions from 'schema-utils';
import schema from './schema';

export function init() {
  const options = getOptions(this);
  validateOptions(schema, options, 'Example Loader');
  const transform = foo.init(options);
  return transform;
}

export function pitch(remainingRequest, precedingRequest, data, transform) {
  data.value = foo.bar(remainingRequest, precedingRequest);
};

export default function loader(source, transform) {
  const transformed = transform(source, this.data.value);
  return `export default ${JSON.stringify(transformed)}`;
}
```

I'm willing to help with the implementation if no big change is required.

**Comment by evilebottnawi** [comment]
It is impossible due each request is handled separably, you still need validate and other actions in loader for each request (`import`/`require`), you can use caches if you need speedup somethings, for example when you write `import('!!my-loader!./file.json')` we will need run init again, so feature is makes no sense
