### ISSUE TITLE
Need the ability for "issuer" Rule to apply to all dependencies of a top-level issuer recursively

### ISSUE THREAD

**Issue by jmikrut** [webpack/webpack#11466]
## Feature request

I am a big fan of the potential that the `issuer` Rule offers. 

But, I need it to work recursively. As-is, I can use the `issuer` rule properly to automatically apply a loader to any files that are required by a certain module. But, I need to continue to apply the loader _**recursively**_ to any additional modules that are require'd from modules that are required from the `issuer`.

More information about my use-case can be found here:

https://stackoverflow.com/questions/63799399/need-to-apply-a-loader-to-all-dependencies-of-a-certain-file-recursively

**What is the expected behavior?**

Loaders are applied recursively to all dependencies that are required from the top-level

**What is motivation or use case for adding/changing the behavior?**

See above StackOverflow link.

**How should this be implemented in your opinion?**

I'd like to either see the `issuer` field either be extended to apply recursively to all modules required by the `issuer` via an additional property or option, OR, alternatively, I could envision this as being added through a new rule altogether.

**Are you willing to work on this yourself?**

Possibly, if someone can point me in the right direction. I imagine I would need to retrieve the dependency graph of all files require'd by my `issuer` and then extend loader application to any dependencies that fall within the dependency graph. This could be a bit out of my wheelhouse, to be honest. But I'd give it a shot with some help.

**Comment by sokra** [comment]
That won't work this way, but technically something like a `scope` could be set to modules and matched on that. Probably not worth the effort... Need to know the use case for that.
