### ISSUE TITLE
stats.maxModules is missing in the types declaration for webpack 5

### ISSUE THREAD

**Issue by thasmo** [webpack/webpack#11477]
# Bug report

**What is the current behavior?**
> ValidationError: Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
> - configuration.stats has an unknown property 'maxModules'.

**If the current behavior is a bug, please provide the steps to reproduce.**
Install the latest `next` version of webpack and set `stats.maxModules` in the `webpack.config.js` file.

**What is the expected behavior?**
`stats.maxModules` should be a valid [stats option](https://github.com/webpack/webpack/blob/master/types.d.ts#L8613).

**Other relevant information:**
webpack version: `5.0.0-beta.30`
Node.js version: `12.16.1`
Operating System: Linux/Ubuntu

**Comment by evilebottnawi** [comment]
It was removed https://github.com/webpack/webpack/blob/master/lib/validateSchema.js#L31

**Comment by evilebottnawi** [comment]
https://github.com/webpack/webpack/pull/11409

**Comment by thasmo** [comment]
@evilebottnawi, thank you!

**Comment by rogerprz** [comment]
How do we get rid of the error if maxModules is not present within our codebase? 

Posting for search reference:
```
Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.stats has an unknown property 'maxModules'
```

**Comment by rossPatton** [comment]
Same issue for me. Not using this property, but on migration to webpack 5 I am also getting this error

**Comment by alexander-akait** [comment]
@rogerprz Some old plugins can modify output options, try to check it
