### ISSUE TITLE
bug: Webpack wrongly converts require() to __webpack_require__()

### ISSUE THREAD

**Issue by mroczek123** [webpack/webpack#11473]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Webpack during bundling converts imports from this function:
node_modules/axios/lib/defaults.js line 16-26
```
function getDefaultAdapter() {
  var adapter;
  if (typeof XMLHttpRequest !== 'undefined') {
    // For browsers use XHR adapter
    adapter = require('./adapters/xhr');
  } else if (typeof process !== 'undefined' && Object.prototype.toString.call(process) === '[object process]') {
    // For node use HTTP adapter
    adapter = require('./adapters/http');
  }
  return adapter;
}
```
from:
```
// For node use HTTP adapter
    adapter = require('./adapters/http');
```
to:
fragment of dist/main.js line 288
```
// For node use HTTP adapter\n    adapter = __webpack_require__(/*! ./adapters/http */
\"./node_modules/axios/lib/adapters/xhr.js\");\n
```

which later leads to exception caused by mistaken import.

**If the current behavior is a bug, please provide the steps to reproduce.**
minimal reproducible repo with webpack output: https://github.com/mroczek123/debugrepo
webpack.config.js
```
const path = require('path');

module.exports = {
  entry: './index.js',
  mode: 'development',
  output: {
    filename: 'main.js',
    path: path.resolve(__dirname, 'dist')
  },
  resolve: {
    extensions: ['.js']
  }
}
```
package.json
```
{
  "name": "debugrepo",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "webpack": "^4.44.1",
    "webpack-cli": "^3.3.12"
  },
  "dependencies": {
    "axios": "^0.20.0"
  }
}
```
index.js
```
import axios from 'axios';
axios.get('google.pl')
```

**What is the expected behavior?**
I think there should be `__webpack_require__(/*! ./adapters/http */ \"./node_modules/axios/lib/adapters/http.js\");`
instead of `__webpack_require__(/*! ./adapters/http */ \"./node_modules/axios/lib/adapters/xhr.js\");`
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
"webpack": "^4.44.1",
node version 14.10.0
"webpack-cli": "^3.3.12"
"axios": "^0.20.0"
OS: win10

**Comment by evilebottnawi** [comment]
No, you target is `web` by default, so we use the `browser` field https://github.com/axios/axios/blob/master/package.json#L71

**Comment by mroczek123** [comment]
Hi, thanks for response. I wasn't aware of "target" setting. Setting this to target: node fixed all my issues. Thanks for help
