### ISSUE TITLE
Get current Watching's instance from compiler object

### ISSUE THREAD

**Issue by rishabh3112** [webpack/webpack#11481]
## Feature request
Access instance of current [`Watching`](https://webpack.js.org/api/node/#watching) from [`Compiler`](https://webpack.js.org/api/node/#compiler-instance) object itself.

**What is the expected behavior?**
```
const compiler = webpack({...})
const watching = compiler.watch(...);
const watchingFromCompiler = compiler.watching;
// expect(watching === watchingFromCompiler).toBe(true)
```

**What is motivation or use case for adding/changing the behavior?**
I am developing Interactive mode for `watch` for `webpack-cli` using Plugin API.
I want to implement a feature to stop current compiling round (where `watching.invalidate()` would help) as well as a feature to start new watching (where `watching.close` would help).

**How should this be implemented in your opinion?**
Whenever `compiler.watch` is called, update `compiler.watching`with current watching.

**Are you willing to work on this yourself?**
yes (need pointers on where to implement it)

**Comment by evilebottnawi** [comment]
We need this for `iterative` mode for webpack-cli, for pause/start/restart/etc, we can't use `const watching = compiler.watch()`, because other tools (for example `webpack-dev-middleware`) can run `compiler.watch()`

**Comment by sokra** [comment]
Yep makes sense.

**Comment by evilebottnawi** [comment]
@rishabh3112 Feel free to send a PR

https://github.com/webpack/webpack/blob/master/lib/Compiler.js#L336
```js
this.watching = new Watching(this, watchOptions, handler);

return this.watching;
```
