### ISSUE TITLE
Warning received while installing webpack in windows to global

### ISSUE THREAD

**Issue by vairam-svs** [webpack/webpack#1148]
Restarted the machine;
running cmd prompt as administrator
Windows 7 professional
npm installed and other packages installed
Warning received while installing webpack in windows to global: 

npm WARN optional dep failed, continuing fsevents@0.3.6
C:\Users\username\AppData\Roaming\npm\webpack -> C:\Users\username\AppData\Roa
ming\npm\node_modules\webpack\bin\webpack.js
npm WARN package.json commandjs@0.0.7 No repository field.
webpack@1.9.10 C:\Users\username\AppData\Roaming\npm\node_modules\webpack
├── supports-color@1.3.1
├── tapable@0.1.9
├── interpret@0.5.2
├── clone@1.0.2
├── memory-fs@0.2.0
├── async@0.9.2
├── enhanced-resolve@0.8.6 (graceful-fs@3.0.8)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── optimist@0.6.1 (wordwrap@0.0.3, minimist@0.0.10)
├── esprima@1.2.5
├── webpack-core@0.6.5 (source-list-map@0.1.5, source-map@0.4.2)
├── uglify-js@2.4.23 (uglify-to-browserify@1.0.2, async@0.2.10, source-map@0.1.3
4, yargs@3.5.4)
└── watchpack@0.2.8 (graceful-fs@3.0.8, chokidar@1.0.3)

**Comment by sokra** [comment]
`npm WARN optional dep failed, continuing fsevents@0.3.6` fine, it's an OSX only module.

`npm WARN package.json commandjs@0.0.7 No repository field.` Send a PR to commandjs and add an repo field to fix it. But it doesn't hurt.
