### ISSUE TITLE
Dynamic imports: Support for different path roots

### ISSUE THREAD

**Issue by tobiu** [webpack/webpack#11483]
## Feature request

**What is the expected behavior?**
Following the definition inside the docs:
https://webpack.js.org/api/module-methods/#import-1

We can use static paths inside dynamic imports, to search matching files inside a specific folder / files tree.

Example:
```
    importApp(path) {
        return import(
            /* webpackInclude: /\/app.mjs$/ */
            /* webpackExclude: /\/node_modules/ */
            /* webpackChunkName: "chunks/[request]" */
            /* webpackMode: "lazy" */
            `../../${path}`
        );
    }
```

**What is motivation or use case for adding/changing the behavior?**
There are use cases (especially for the neo.mjs context), where the base path can be in different spots.

In case I want to build the framework repo itself to get split chunks for all apps & examples, I need to path specified above ("../../").

We have the structure:

neo
- apps
- examples
- src
- - worker 
- - - App.mjs

Since the AppWorker is the main entry point for all apps, we need to walk 2 folders upwards.

Now, when we use npx neo-app to generate a new app (workspace), the folder structure is different:

workspace
- apps
- node_modules
- - neo.mjs
- - - src
- - - - worker 
- - - - - App.mjs

In this case, we want to parse all apps inside the apps top level folder, while ignoring the apps & examples folder inside the neo.mjs repo itself. Ignoring the repo works fine with the webpackExclude here.

To make it work, I needed to create a copy of the AppWorker class, just to change the webpack based imports:
https://github.com/neomjs/neo/blob/dev/buildScripts/webpack/entrypoints/AppWorker.mjs

Extending the real AppWorker class can not work, since in this case, webpack would parse the overridden imports as well.

```
    importApp(path) {
        if (!Neo.config.isExperimental) { // dist/dev & dist/prod
            return import(
                /* webpackInclude: /\/app.mjs$/ */
                /* webpackExclude: /\/node_modules/ */
                /* webpackChunkName: "chunks/[request]" */
                /* webpackMode: "lazy" */
                `../../../../../${path}`
                );
        } else {
            return import( // dev mode
                /* webpackIgnore: true */
                `../../../${path}`
                );
        }
    }
```

It actually needs 2 different versions for this one directly (running inside the browser VS using webpack based builds).

It does work fine with the duplicated app worker file, but I think it should be easier to achieve this.

**How should this be implemented in your opinion?**
I am not 100% sure, what the best approach could be.

We could add a specific variable name, which would need to get resolved inside the webpack based builds.

E.g.: `${basePath}../../${path}`

To keep it reasonable, the variable has to get defined inside the same scope.

```
    importApp(path) {
        let basePath = '';

        if (myCustomEnv === true) { // this is the tricky part => figuring out which version to use
            basePath = '../../../';
        }

        return import(
            /* webpackInclude: /\/app.mjs$/ */
            /* webpackExclude: /\/node_modules/ */
            /* webpackChunkName: "chunks/[request]" */
            /* webpackMode: "lazy" */
            `${basePath}../../${path}`
        );
    }
```

**Are you willing to work on this yourself?**
Ugh, if I just had more time. Willing to provide feedback for sure.

**Comment by evilebottnawi** [comment]
You should solve it on application side, it is out of scope webpack

**Comment by sokra** [comment]
A basePath prefix would only work if it is compile-time-constant, which doesn't seem to be.

You could also change the base path of a "context" (webpack name for dynamic request, like import() with expression), via configuration with the `ContextReplacementPlugin`. Maybe this helps here?

**Comment by tobiu** [comment]
Hi Tobias,

interesting one. Missed it so far.

In case I add the plugin into the build processes for the app worker using a wildcard regex, it will only get one match (actually 2, but they are almost the same).

It does not really matter though, since it matches the main dynamic imports entry point to lazy load apps.

```
            new webpack.ContextReplacementPlugin(/.*/, context => {
                if (!insideNeo && context.context.includes('/src/worker')) {
                    context.request = '../../' + context.request;
                }
            })
```
https://github.com/neomjs/neo/commit/34babc001cc8c545211aac48a87c1e2d753f7318

Thx, it is definitely good enough to remove the app worker build entry point copy.

The results are pretty cool btw., so kudos to the webpack team!

With the central app worker entry point, the neo project now has cross apps split chunks in place. So, we can easily add multiple apps on one page with close to zero overhead and it becomes even more powerful inside the SharedWorkers context => multi browser window apps.

Feel free to take a look at the split chunks output inside the online examples (they are inside the app worker scope): https://neomjs.github.io/pages/node_modules/neo.mjs/dist/production/apps/website/index.html#mainview=examples

Closing this ticket, thanks again!

Best regards, Tobi
