### ISSUE TITLE
import statement results in root of relative path name being resolved as filename

### ISSUE THREAD

**Issue by infoeon** [webpack/webpack#11480]
# Bug report

**What is the current behavior?**

An `import` statement with a relative filename of `some/long/path.css` will instead import `some.js` if the file exists.

**If the current behavior is a bug, please provide the steps to reproduce.**

See gist: https://gist.github.com/infoeon/f4c81ac060e67458e220c2f55903cecf

**What is the expected behavior?**

Webpack should abort the build since the imported file is non-existent. This is the current (and correct) behaviour in Webpack 4.

**Other relevant information:**
webpack version:  5.0.0-beta.30
Node.js version: 14.9.0
Operating System: Windows 10
Additional tools:

**Comment by vankop** [comment]
this should be fixed with latest master.. could you try with `webpack@github:webpack/webpack` ?

**Comment by infoeon** [comment]
Confirmed, latest master has resolved the bug.
