### ISSUE TITLE
improve URL supporting

### ISSUE THREAD

**Issue by evilebottnawi** [webpack/webpack#11491]
Amazing feature, thank you! This allows us to use Wasm in npm packages that can be used in Web, Node and Webpack projects.

Did you consider not requiring `./` at the beginning of the relative path? Both

```js
let a = new URL("./wasm/drand.wasm", "file:///Users/me/projects/drand-client/verifying.js");
let b = new URL("wasm/drand.wasm", "file:///Users/me/projects/drand-client/verifying.js");
```

are the same URL but the second one fails with

> Module not found: Error: Can't resolve 'wasm/drand.wasm' in '/Users/simon/opensource/drand/drand-client'

_Originally posted by @webmaster128 in https://github.com/webpack/webpack/pull/11276#issuecomment-694070263_

**Comment by webmaster128** [comment]
Thank you for creating this ticket. Ping @vankop

**Comment by sokra** [comment]
I would like to fix this together with `url(path/to/file)` in css etc.

There could be a resolve option in enhanced-resolve which tries to resolve module request relative first and fallback to module resolving afterwards. You could set this for `url` type resolvers.

So `wasm/drand.wasm` in `/path/to/project` would resolve to:

* `/path/to/project/wasm/drand.wasm`
* `/path/to/project/node_modules/wasm/drand.wasm`
* `/path/to/node_modules/wasm/drand.wasm`
* `/path/node_modules/wasm/drand.wasm`
* `/node_modules/wasm/drand.wasm`

in that order.

This would make `url("~module/thing")` obsolete and simpler for the user.

**Comment by sokra** [comment]
I think it would be pretty easy to implement by moving this line

https://github.com/webpack/enhanced-resolve/blob/adfbc74e4122d0b736d47b13ad3a824e0ce0a913/lib/ResolverFactory.js#L362

before this:

https://github.com/webpack/enhanced-resolve/blob/adfbc74e4122d0b736d47b13ad3a824e0ce0a913/lib/ResolverFactory.js#L341-L349

when the flag is set.

**Comment by evilebottnawi** [comment]
> This would make url("~module/thing") obsolete and simpler for the user.

Still not obsolete, in theory you can have relative file and module (`bootstrap` :smile: ), so you need to use `~` if you want to load module instead file, but edge case

**Comment by sokra** [comment]
yes, in practice the developer probably works around that by renaming the local file.

Technically node_modules resolving isn't allowed in native web anyway in places where urls are expected. This is kind of kind by webpack to support this anyway^^

**Comment by vankop** [comment]
@webpack-bot move to webpack/enhanced-resolve

**Comment by vankop** [comment]
Need some improvement on webpack side to
