### ISSUE TITLE
chunk with dependOn results in invalid Js

### ISSUE THREAD

**Issue by ryanburnette** [webpack/webpack#11505]
# Bug report

**What is the current behavior?**

Relevant parts of my config.

```js
module.exports = {
  entry: {
    vendor: ['vue'],
    main: {
      import: './js/main.js',
      dependOn: 'vendor'
    }
  },
  // ...
  module: {
      {
        test: /\.(js|jsx)$/,
        exclude: /(node_modules|bower_components)/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['@babel/preset-env']
          }
        }
      }
  }
};
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Error in browser console...

```
vendor.js:12033 Uncaught TypeError: {(intermediate value)} is not a function
    at vendor.js:12033
    at startup:2
```

Offending code in vendor.js...

```js
/******/ 	// object to store loaded CSS chunks
/******/ 	var installedCssChunks = {
/******/ 		"vendor": 0
/******/ 	}/* webpack/runtime/jsonp chunk loading */
/******/ 	(() => {
/******/ 		// no baseURI
/******/ 	
```

Not sure if it would help (of it it's related), but how can I run Babel on the Js that webpack generates? I understand that it will run on the imports, but I want the generated part to be es2015 as well.

**What is the expected behavior?**

- expected vendor.js to be valid js
- wish vendor.js could be transpiled to es2015

**Other relevant information:**
webpack version:  5.0.0-beta.32
Node.js version: 12.18.4 (current lts)
Operating System: Mac OS X 10.15.5
Additional tools:

**Comment by ryanburnette** [comment]
Also relevant to add...

```js
module.exports = {
  // ...
  entry: {
    // vendor: ['vue'],
    main: {
      import: './js/main.js'
      // dependOn: 'vendor'
    }
  },
  // ...
}
```

Compiling it all to one file works.

**Comment by vankop** [comment]
fixed https://github.com/webpack-contrib/mini-css-extract-plugin/pull/561

please try to use latest `mini-css-extract-plugin`
