### ISSUE TITLE
Dynamic Import not working with variable path

### ISSUE THREAD

**Issue by AmaanKulshreshtha** [webpack/webpack#11508]
# Bug report

**What is the current behavior?**
When using a variable path inside of dynamic import, it throws a `Error: Cannot find module` error.

**If the current behavior is a bug, please provide the steps to reproduce.**
```javascript
const componentPath = `${process.cwd().replace('/', '')}/${context.componentPath}`;
const component = await import(`/${componentPath}.js`);
console.log(component);
```
Tried from #6680 

## Also Tried

```javascript
const componentPath = `${process.cwd()}/${context.componentPath}.js`;
const component = await import(/* webpackIgnore: true */ componentPath);
console.log(component);
```
Tried from #8341 

**What is the expected behavior?**
It should load the module, when the module already exists and should provide the module object with the default property inside.

**Other relevant information:**
webpack version: 4.44.1  
Node.js version: 14.3.0 
Operating System: MacOS Catalina (10.15.6)

**PS:** I need `process.cwd()` because I'm working on a library, and I want to avoid path discrepancies.

**Comment by vankop** [comment]
Hack with `webpackIgnore` should work.

Please provide minimum reproducible repo, otherwise it is hard to help.

**Comment by AmaanKulshreshtha** [comment]
Sure thing, just need some time for that...will post it within a few days.

**Comment by adjenks** [comment]
I'm curious why you're pulling all the slashes out like this:
`process.cwd().replace('/', '')`
You'd take a directory like  `/some/cool/directory/path/` and change it to `somecooldirectorypath`

Also, in the second example, you don't do this. Is there a reason for that?

Another question, do both tests return the same error message? Or are they different at all?

You should try `console.log(componentPath)` to verify the path in both tests.

**Comment by AmaanKulshreshtha** [comment]
I did verify the path in both, and it's the same...and if you do `cmd` + click, it actually opens the file too.

**Comment by adjenks** [comment]
You need some chunk of static path.
Please see:
https://webpack.js.org/api/module-methods/#dynamic-expressions-in-import
Also this might help:
https://webpack.js.org/configuration/entry-context/#context
Maybe try something like this:
```js
const componentPath = `/${context.componentPath}`;
const component = await import(process.cwd()+'/'+context.componentPath');
console.log(component);
```
Hopefully `process.cwd()` will become inlined and webpack can interpret it as a static path. It will cause everything in the `process.cwd()` folder to get processed by webpack and put into the dist folder. Ideally you'd just use a relative path like "./components/" or something instead of using `process.whatever`

**Comment by AmaanKulshreshtha** [comment]
I read the docs for this. The thing is I want to avoid path discrepancies for a library I am working on and my sole objective of using `process.cwd()` is to solve that issue.
It'll really help me a lot if you can provide an alternative for that issue.

**Comment by AmaanKulshreshtha** [comment]
@vankop I have created the [repo](https://github.com/AmaanKulshreshtha/webpack-module-error) to reproduce the error.

**Comment by sokra** [comment]
What I think you want is this:

``` js
const { default: App } = await import(COMPONENT_PATH);
```

and in webpack.config.js

``` js
plugins: [
  new DefinePlugin({
    COMPONENT_PATH: path.resolve(__dirname, "..", process.env.component_path)
  })
]
```

**Comment by AmaanKulshreshtha** [comment]
My bad, I forgot to mention that I used `process.env` as an example. 

My use case requires me to read the value from a `yaml` config file. And so the user has to input the file name there. I don't know if using the `DefinePlugin` will work there.

Really sorry to not have informed earlier ✌️

**Comment by evilebottnawi** [comment]
> My use case requires me to read the value from a yaml config file.

Read value and pass it to `DefinePlugin`, please use stackloverflow for future questions

Solved, feel free to feedback
