### ISSUE TITLE
Multiple assets emit different content to the same filename css/common.css

### ISSUE THREAD

**Issue by hubcarl** [webpack/webpack#11503]
# Bug report

**What is the current behavior?**

development mode , only modify css file trigger webpack hot reload, will follow error:

```
<e> [webpack-dev-middleware] assets by status 40.6 KiB [cached] 1 asset
<e> assets by info 4.22 KiB [hmr]
<e>   assets by chunk 3.3 KiB (name: common)
<e>     asset css/common.css 1.8 KiB [emitted] [hmr] (name: common) (id hint: styles, vendors)
<e>     asset common.3dda70a80101f291712e.hot-update.js 1.5 KiB [emitted] [immutable] [hmr] (name: common) (id hint: styles, vendors)
<e>   asset runtime.3dda70a80101f291712e.hot-update.js 902 bytes [emitted] [immutable] [hmr] (name: runtime)
<e>   asset 3dda70a80101f291712e.hot-update.json 40 bytes [emitted] [immutable] [hmr]
<e> assets by path js/ 3.64 MiB
<e>   asset js/common.js 3.6 MiB [emitted] (name: common) (id hint: styles, vendors)
<e>   asset js/runtime.js 42.3 KiB [emitted] (name: runtime)
<e>
<e> ERROR in Conflict: Multiple assets emit different content to the same filename css/common.css
<e>
<e> webpack 5.0.0-beta.32 compiled with 1 error in 303 ms
```

**If the current behavior is a bug, please provide the steps to reproduce.**

```
- git clone git@github.com:easy-team/awesome.git
- git checkout webpack5
- cd boilerplate/react
- yarn
- npm run dev
```

- The demo can run depends on another issue([https://github.com/webpack-contrib/mini-css-extract-plugin/pull/590](https://github.com/webpack-contrib/mini-css-extract-plugin/pull/590) ) to be resolved and merged for release.
- Modify `src/router/component/home.css`  file, trigger webpack hot reload, will above error.   If only modify javascript file , can works.

**What is the expected behavior?**

**Other relevant information:**
webpack version:  webpack 5.0.0-beta.32
Node.js version:  v12.14.0
Operating System:  Mac
Additional tools:

**Comment by evilebottnawi** [comment]
Please do not duplicate issues, it is traced in `mini-css-extract-plugin` repo https://github.com/webpack-contrib/mini-css-extract-plugin/issues/487
