### ISSUE TITLE
Class isn't tree-shaken if it's instantiated in an unused variable

### ISSUE THREAD

**Issue by marcofugaro** [webpack/webpack#11509]
# Bug report

**What is the current behavior?**

Tree-shaking doesn't work if the class is instantiated somewhere but its instance is not actually used.

Here is a minimal example:

```js
class UsedClass {}

class UnusedClass {
  constructor() {
    this.name = 'UnusedClass'
  }
}

// this class is instantiated but the variable is not actually used 
const unusedVariable = new UnusedClass();

// this class is actually used
console.log(UsedClass)
```

This, after being compiled and minified by terser, is outputted as:
```js
(() => {
    "use strict";
    new class {
        constructor() {
            this.name = "UnusedClass";
        }
    };
    console.log(class {});
})();
```

As you can see, the unused class is still in the bundle.

Using `/*#__PURE__*/` in the class instance variable, correctly makes terser remove the class. However this sould not be necessary.

Rollup, for example, [correctly removes the unused class](https://rollupjs.org/repl/?version=2.28.1&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNsYXNzJTIwVXNlZENsYXNzJTIwJTdCJTdEJTVDbiU1Q25jbGFzcyUyMFVudXNlZENsYXNzJTIwJTdCJTVDbiUyMCUyMGNvbnN0cnVjdG9yKCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwdGhpcy5uYW1lJTIwJTNEJTIwJ1VudXNlZENsYXNzJyU1Q24lMjAlMjAlN0QlNUNuJTdEJTVDbiU1Q25jb25zdCUyMHVudXNlZFZhcmlhYmxlJTIwJTNEJTIwbmV3JTIwVW51c2VkQ2xhc3MoKSUzQiU1Q24lNUNuJTVDbmNvbnNvbGUubG9nKFVzZWRDbGFzcyklM0IlNUNuJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==)

**If the current behavior is a bug, please provide the steps to reproduce.**

Repro: https://github.com/marcofugaro/webpack-treeshake-test

- `npm i`
- `npm run build`

**What is the expected behavior?**

The unused class should not appear in the final bundle.

```js
(() => {
    "use strict";
    console.log(class {});
})();
```

**Other relevant information:**
webpack version:  `5.0.0-rc.0`
Node.js version: `v14.5.0`
Operating System: macOS Catalina

**Comment by vankop** [comment]
It is possible to have a side effect in constructor, e.g. 
```
class UnusedClass {
  constructor() {
    this.name = 'UnusedClass'
   window.count++;
  }
}
```
as I understand terser does not track this, so `/*#__PURE__*/` notation is important here. 
Anyway related to terser, please reopen issue there https://github.com/terser/terser
