### ISSUE TITLE
erro in validation throw `new WebpackOptionsValidationError`

### ISSUE THREAD

**Issue by andersonbosa** [webpack/webpack#11512]
# Bug report

**What is the current behavior?**
It claims that a configuration is wrong. The configuration that was passed does not use the configuration that is giving an error (see log below), so BUILD should result in success.

**If the current behavior is a bug, please provide the steps to reproduce.**
I can't do a "step by step" because I don't know the reason for the error, which comes from the webpack library. After all, my configuration is apparently correct ([according to the documentation](https://webpack.js.org/configuration/optimization/#optimizationsplitchunks)). 

**Here the files:**
[webpack.config.js](https://gist.github.com/andersonbosa/f42d2a0d81d502cf5df60b7b22c80ede)
[webpack.common.js](https://gist.github.com/andersonbosa/1f722b84ef6cdfb8fdea3d9a0736802c)
[webpack.prd.js](https://gist.github.com/andersonbosa/e64dee7ae06c450fd8f6a13d8f22c40d).
[webpack.dev.js](https://gist.github.com/andersonbosa/180cf51599de97d3b42b4b1860e339c9)
[how i build: `frontend-app-cli`](https://gist.github.com/andersonbosa/17393a18225d9a3fcf8212388e287f3f)
[**The bug, when running. npm log output**](https://gist.github.com/andersonbosa/bc5ef72c2805f0c65f05a7c6913db8d2) - breaks in `frontent-app-cli/node_modules/webpack/lib/webpack.js:31`

**What is the expected behavior?**
The expected behavior is to accept the configuration (I tried the suggested one, `configuration.optimization.splitChunks: false`, and it keeps breaking in the webpack lib)

**Other relevant information:**
webpack version: ^4.42.2
Node.js version: v10.20.1
Operating System: `Linux kali 5.8.0-kali1-amd64 #1 SMP Debian 5.8.7-1kali1 (2020-09-14) x86_64 GNU/Linux`

**Comment by evilebottnawi** [comment]
Please read the validation error message and fix it

**Comment by andersonbosa** [comment]
wow! how i couldn't think it! oh, wait...
`- configuration.optimization.splitChunks should be one of these: false | object`
[so it should be the same as it is ... AMAZING!](https://gist.github.com/andersonbosa/e64dee7ae06c450fd8f6a13d8f22c40d#file-webpack-issue-js-L6)

**For those with a similar problem: users on StackOverFlow suggest trying change the version used.**

**Comment by evilebottnawi** [comment]
You use docs for v5, but point on v4 in the issue template
