### ISSUE TITLE
v5.0.0-rc.0 duplicated module in chunks

### ISSUE THREAD

**Issue by mustafawm** [webpack/webpack#11513]
In reference to [this](https://github.com/webpack/webpack/issues/9802#issuecomment-696014390)

## Current behavior
Same module found in multiple chunks

<img width="1792" alt="Screen Shot 2020-09-22 at 3 24 44 pm" src="https://user-images.githubusercontent.com/13101565/93846566-c0c4f680-fce7-11ea-9a11-1f3ac87af119.png">

## Steps to reproduce:

[This repo](https://github.com/mustafawm/wp-splitchunks-issue)
```
npm i
npm run build
```

`<Map />` is used in different places (lazy-loaded in some). 

```jsx
// App.tsx
const AuthenticatedApp = lazyLoad(() => import('./Authenticated'));
const UnAuthenticatedApp = lazyLoad(() => import('./UnAuthenticated'));

export default function AppRoutes() {
  const random = Math.random() * 10;

  // if authed
  if (random < 6) {
    return <AuthenticatedApp />;
  }
  return <UnAuthenticatedApp />;
}
```
```jsx
// Authenticated.tsx
const MapUsed1 = lazyLoad(() => import('app/MapUsed1'));
const MapUsed2 = lazyLoad(() => import('app/MapUsed2'));

export default function AuthenticatedRoutes() {
  return (
    <Routes>
      <Route path="profile" element={<MapUsed1 />} />
      <Route path="send" element={<MapUsed2 />} />
    </Routes>
  );
}
```

```jsx
// UnAuthed.tsx
export default function UnauthenticatedRoutes() {
  return (
      <Routes>
        <Route path="signup" element={<MapUsed3 />} />
      </Routes>
  );
}
```

## Expected behavior
one chunk containing `leaflet`

webpack version:  5.0.0-rc.0
Node.js version: 14.7.0
Operating System:  MacOS

_Sorry if the repo is not very well-organized. I stripped out the codebase I'm working on to get a reproduceable repo._

**Comment by sokra** [comment]
Thanks for the report. It was an interesting bug in SplitChunks when chunks have more than one source type (here: javascript and css). Fix coming soon.

**Comment by mustafawm** [comment]
Glad it was helpful 🙂
