### ISSUE TITLE
http://webpack.github.io/ cannot open

### ISSUE THREAD

**Issue by Aries-Sushi** [webpack/webpack#11519]
![image](https://user-images.githubusercontent.com/17898871/94098854-2803b780-fe5c-11ea-94c4-6f72eac1e618.png)

**Comment by anshumanv** [comment]
Please use https://webpack.js.org/

**Comment by Aries-Sushi** [comment]
> Please use https://webpack.js.org/

I want to analyze the output through the website http://webpack.github.io/analyse/, but i have found another tool bundle-stats-webpack-plugin. Thank u all the same.
