### ISSUE TITLE
Module is incorrectly disposed if it is required in another chunk during hot-update

### ISSUE THREAD

**Issue by tranvansang** [webpack/webpack#11527]
# Bug report

**What is the current behavior?**

Chunk `2` includes module `./src/client/components/shared/flex/FixedFlexSpacer.tsx` (call it module `Boy`).

Chunk `8` includes module `./src/client/components/pages/auth/signup/SignUpSuccessWithConfirm.tsx` (call it module `Father`).

Initially, `Father` does not import `Boy`, then I started webpack in watch mode.

After that, `Father` is edited to import `Boy`. The 3 following files are generated.

- `2.537fa46d90ccbabf66a2.hot-update.js`

```
exports.id = 2;
exports.modules = {

/***/ "./src/client/components/shared/flex/FixedFlexSpacer.tsx":
false

};
//# sourceMappingURL=2.537fa46d90ccbabf66a2.hot-update.js.map
```

- `8.537fa46d90ccbabf66a2.hot-update.js`

```
exports.id = 8;
exports.modules = {

/***/ "./src/client/components/pages/auth/signup/SignUpSuccessWithConfirm.tsx":
/*!******************************************************************************!*\
  !*** ./src/client/components/pages/auth/signup/SignUpSuccessWithConfirm.tsx ***!
  \******************************************************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);

[[content pruned]]
```

- `537fa46d90ccbabf66a2.hot-update.json`

```
{"h":"ef1541474da5ab0559b2","c":{"2":true,"8":true}}
```

Because in `2.[hash].hot-update.js`, the value associated with the `Boy` module is `false`, in [this line](https://github.com/webpack/webpack/blob/8295202bc86b45b791c28215703f7ce4e2eac370/lib/hmr/JavascriptHotModuleReplacement.runtime.js#L124), the module `Boy` is disposed, and the compiler generates a warning

```
[HMR] unexpected require(./src/client/components/shared/flex/FixedFlexSpacer.tsx) to disposed module
```

(Actually, there is a bug in the warning function, and I already fixed it in https://github.com/webpack/webpack/pull/11526 )

# My questions are

- What does the `false` value mean in `2.[hash].hot-update.js`? Does it mean the module `Boy` is going to be disposed or any other meaning?
- If yes, could anyone who can tell me where this `false` is defined before it is printed to `2.[hash].hot-update.js`, so I can continue debugging.

Thank you very much!

**Further background information**
I am using component splitting where `Boy` and `Father` belong to different dynamic imports. In my server code, whenever HMR happens, I immediately refetch (and await) all the dynamic imports.

I am talking about the bug in nodejs (actually, it happens also in the browser) where I use `webpack/hot/poll?1000` to poll the updates.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

The module `Boy` should not be disposed, and should be required in module `Father` during the hot update.

**Other relevant information:**
webpack version:  4.44.2
Node.js version: v14.9.0
Operating System: Ubuntu 20.04 5.4.0-48-generic
Additional tools:

**Comment by sokra** [comment]
yes that's a bug. It was fixed by: https://github.com/webpack/webpack/pull/11440 in webpack 5.

**Comment by evilebottnawi** [comment]
Fixed in webpack@5, ETA is `2020-10-10`
