### ISSUE TITLE
weird issue with mixing require.ensure and dynamic require

### ISSUE THREAD

**Issue by KidkArolis** [webpack/webpack#1152]
Hi @sokra,

Thanks for all your hard work on webpack! I feel bad continuously asking for help with my issues without contributing otherwise. I've been trying to convert a large app to use webpack since January and every time I revisit that branch I run into some new issues.

I have this fairly tricky dynamic loading setup that I'm trying to get going, the code looks something like

```js
function loadRouteHandler(name, cb) {
  // this is the async bit
  require.ensure([], function (require) {
   // this is the dynamic bit
    cb(require("app/routes/page1/" + name));
  });
};
```

This compiles to something like

```js
function loadRouteHandler(name, cb) {
  __webpack_require__.e/* nsure */(5, function (require) {
    cb(__webpack_require__(64)("./" + name));
  });
}
```

Now the weird thing is this works when I'm running the app locally. But for some reason, in my tests, this breaks because moduleId 64 is not in the bundle and so this line throws:

```js
// Execute the module function
modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
```

Any idea why this could be happening? Is there any other info I could provide?

**Comment by ctrlplusb** [comment]
I think the require.ensure function is provided by Webpack.  Your tests probably aren't getting executed through Webpack therefore the function will not exist. :)

You can look at using something like 'webpack-require' to wrap your tests with a webpack context.

https://github.com/petehunt/webpack-require

**Comment by bebraw** [comment]
@KidkArolis Did you figure it out?
