### ISSUE TITLE
ModuleFederation rc config file

### ISSUE THREAD

**Issue by lomocc** [webpack/webpack#11520]
## Feature request

**What is the expected behavior?**
I think we can use **.modulerc.js** to configure ModuleFederation.   
So we don’t need to configure **webpack.config.js**

```js
// .modulerc.js
module.exports = {
  name: 'shared',
  filename: 'remoteEntry.js',
  exposes: {},
  remotes: {},
  shared: [
    {
      react: {
        singleton: true,
      },
      'react-dom': {
        singleton: true,
      },
    },
  ],
};
```

**What is motivation or use case for adding/changing the behavior?**
Easier to use
**How should this be implemented in your opinion?**
```js
fs.existsSync(`${pwd}.modulerc.js`) &&
        new ModuleFederationPlugin(require(`${pwd}.modulerc.js`)),
```

**Are you willing to work on this yourself?**
no

**Comment by evilebottnawi** [comment]
Sorry, no, you have `webpack.config.js` and can use `require`/`import`
