### ISSUE TITLE
Webpack dynamic import

### ISSUE THREAD

**Issue by Noeldeveloper** [webpack/webpack#11523]
## Feature request

We need dynamic imports to resolve variables. It's very important because future microfrontends could be served from a server. 

**What is the expected behavior?**

Expected behaviour is to make that work:

`const path = await http.get(''https://myserver/mylib/fesm2015Bundle');`
`// path = 'https://myrepo.com/assets/fesm2015Bundle.js'`
`import(path).then((content) => content.fn())`

**What is motivation or use case for adding/changing the behavior?**

Let bundles be served from server, to avoid dependencies, and make projects very light weight

**How should this be implemented in your opinion?**

It needs to go one step far from static analysis of import path

**Are you willing to work on this yourself?**
yes

**Comment by evilebottnawi** [comment]
use `import(/* webpackIgnore: true */).then()`
