### ISSUE TITLE
support for arbitrary custom import handlers in addition to custom loaders

### ISSUE THREAD

**Issue by godmar** [webpack/webpack#11538]
## Feature request

I would like to be able to say something akin to:
```
import Content from 'dynamiccontentmaker:../src/preparesomecontent.js';
```

**What is the expected behavior?**

The expected behavior would be to execute `../src/preparesomecontent.js` at build time, save whatever it produces and include it in the bundle, similar to how custom file loaders work.

**What is motivation or use case for adding/changing the behavior?**

It is sometimes useful to record the results of JS code that is run at build time in the bundle produced by webpack, but independent of loading and transforming files.

**How should this be implemented in your opinion?**

Perhaps similar to loaders.  I was, in fact, able to implement the following work-around in webpack `4.44.0` (run under `next.js`):
```
import Content from '../path/to/some/dummy-file.dummyext'
```
and then I wrote a loader for `.dummyext` and added it to the webpack rules to refer to `src/preparesomecontent.js`

However, the drawback of this approach is that `../path/to/some/dummy-file.dummyext` needs to exist since custom loaders are designed to load files and transform their content, not to execute arbitrary JS code.

**Are you willing to work on this yourself?**

yes, definitely

**Comment by evilebottnawi** [comment]
Sorry, it is out of scope webpack, you can achieve this using loaders or plugins, also it is not part of ES spec, we try to avoid adding non-standard items, also this will create a problem with https://github.com/webpack/webpack/issues/8896

**Comment by sokra** [comment]
`import "../src/preparesomecontent.js!"` would do that if you want to go non standard.
