### ISSUE TITLE
Entry with DependOn array not loading

### ISSUE THREAD

**Issue by neoGeneva** [webpack/webpack#11539]
# Bug report

**What is the current behavior?**

If there are multiple items in the DependOn the module never runs.

**If the current behavior is a bug, please provide the steps to reproduce.**

I have an example repository here: https://github.com/neoGeneva/webpack-dependon-bug

I have a config with three entry points, and four modules.
* Entry1 loads module1.js, which in turn loads module2.js
* Entry2 loads module3.js, which in turn loads module2.js and module4.js. Entry2 has DependsOn: [Entry1, Entry3]
* Entry3 loads module4.js

In my example each module logs its name, and the name of the modules its loaded. At the moment Entry2 never runs and its output is never logged to the console, and the output is the following

```
loaded module2
loaded module1
module1 loaded module2
loaded module4
```

**What is the expected behavior?**

The module should load, in my example I'd expect the output to be:

```
loaded module2
loaded module1
module1 loaded module2
loaded module4
loaded module3
module3 loaded module2
module3 loaded module4
```

**Other relevant information:**
webpack version: 5.0.0-rc.0
Node.js version: v12.18.3
Operating System: Windows 10 Version 20H2 (OS Build 19042.541)
Additional tools:

**Comment by sokra** [comment]
It's not allowed to have more then one runtime on a single html page. You have to use `optimization.runtimeChunk: "single"` for this case. That should also fix this issue.

**Comment by neoGeneva** [comment]
Hey @sokra, that solved my problem, thanks!
