### ISSUE TITLE
[HMR] on server side and module reloads

### ISSUE THREAD

**Issue by darul75** [webpack/webpack#1153]
Hi,

In my server side I face some modules updates errors with some express routing updates by instance. I guess it is a question of module dependencies or build version and ids...

Can you help with this scenario:

- code is like

```
// Register API middleware
// -----------------------------------------------------------------------------
require('./api')(app);
```

if I update api.js I got :

```bash
Express server listening on port 3000
[HMR] Cannot apply update.
[HMR] Error: Aborted because 115 is not accepted
```

Then if I put something like (from https://github.com/webpack/docs/wiki/hot-module-replacement)

```
require('./api')(app);

// check if HMR is enabled
if(module.hot) {
  // accept update of dependency
  module.hot.accept('./api', function() {
    require('./api')(app);
  });
}
```

here it is fine

```
Expresssss server listening on port 3000

[HMR] Updated modules:
[HMR]  - 115
[HMR] Update applied.
```

Can you help about this common use cases and how to manage server side code to be hot loading enabled ?

**Comment by darul75** [comment]
Now that I have read "carefully" the documentation it looks like it is normal way of doing hot patching but it still do not want to work correctly, I mean patching process is ok.

```
[HMR] Updated modules:
[HMR]  - 116
[HMR] Update applied.
[HMR] Updated modules:
[HMR]  - 71
[HMR] Update applied.
```

But code of patch is not called even if I try to reinject it with caution.

Small example, my express use a small api middleware module let's call it ./api.js

./main.js (bundle by webpack)
```
var app... my app express server instance
var apiRoutes = require('./api');`

// activation
apiRoutes(app);
```

./a.js
```
function query(server) {
  server.get('/test', (req, res, next) => {
      res.status(200).send({test: 'test'});
}

export default query;
```

if I change ./api.js to send different json {test: 'test webpack'}

I can see patch contain good code, I have printed method body but it still not work

// check if HMR is enabled
if(module.hot) {
  // accept update of dependency
  module.hot.accept(['./api'], () => {
    apiRoutes = require('./api'); // fresh new one with good body

    apiRoutes(app);
  });
}

**Comment by darul75** [comment]
I have made test with simple require it looks ok but when into some express routes...more tricky

**Comment by sokra** [comment]
You need to remove the old routes from the express app. Another registration doesn't overwrite the handlers it just adds more.

**Comment by darul75** [comment]
It confims my thought and what I have seen, just need to checkout how express routing works, it is fine.

Another question, do you have any advices on how to handle "accept" patching ?

If module B, depends on module A, B depends on module C, that I update C, do I need to apply hot accept dependency only on B or both A,B... it is descendant to sub requires for a specific module.

Sorry to bother you :)
