### ISSUE TITLE
Module federation with css generate repeat file

### ISSUE THREAD

**Issue by shaodahong** [webpack/webpack#11546]
# Bug report

**What is the current behavior?**

generate repeat file

**If the current behavior is a bug, please provide the steps to reproduce.**

[git repository report](https://github.com/shaodahong/module-federation-css-report)

exposes file import css file

### Repeat file
- [x] Module federation with css and without `splitChunks` to extract single file
- [x] Module federation with sass(whether `splitChunks` to extract single file)

**What is the expected behavior?**
reuse the same file

**Other relevant information:**
webpack version:  `5.0.0-rc.1`
Node.js version: `v12.16.1`
Operating System: `OSX`
Additional tools:

**Comment by shaodahong** [comment]
@sokra it's normal when add

```js
optimization: {
    splitChunks: {
      cacheGroups: {
        styles: {
          name: 'styles',
          test: /\.css$/,
          chunks: 'all',
          enforce: true,
        },
      },
    },
  }
```

but if I use sass and `splitChunks` config, it's still

**Comment by ScriptedAlchemy** [comment]
Don’t enforce it
