### ISSUE TITLE
Module resolve issue with RxJS as nested dependency and a specific config

### ISSUE THREAD

**Issue by yamalight** [webpack/webpack#1154]
Having an issue using package that depends on RxJS from webpack - for some reason webpack does not correctly resolves `require('rx');` in a nested package when using `main` field from package.json.

Error log can be found here: https://gist.github.com/yamalight/4532b7f6c358f0a05962
Minimal test case can be found here: https://gist.github.com/yamalight/dcefec96f2dd61c4f619

Executing test case in node.js (e.g. `node index.js`) works perfectly fine. 
Same with using the given module using AMD and browserify. 
Only webpack fails.

**Comment by yamalight** [comment]
Looks like after reading "index.js" from main, webpack finds it in folder and then instead of including the file, it takes `browser["index.js"]` field for some reason.
removing `browser` from package.json in Rx forces webpack to start requiring `index.js` properly, but then it goes crazy because of the AMD and CommonJS being present in the code together (or at least that how it looks to me).

**Comment by yamalight** [comment]
Adding the following alias seems to fix the issue: `rx: 'rx/dist/rx.all.js'`, but that shouldn't be necessary under normal circumstances IMO.

**Comment by sokra** [comment]
Here is the spec for the `browser` field: https://gist.github.com/defunctzombie/4339901

It should be `"index.js": "./dist/rx.all.js"`. The package.json is wrong.

**Comment by yamalight** [comment]
@sokra it's still broken if you ignore `browser` field at all (see the test case provided)

**Comment by sokra** [comment]
`packageMains: ['main'],` doesn't ignore the browser field... the browser field still acts as aliasing field...

**Comment by yamalight** [comment]
@sokra I thought providing `packageMains` overrides the way wepback looks for entry points in `package.json` - am I misunderstanding how it's supposed to work?

**Comment by bebraw** [comment]
@yamalight Any luck with the current version of rx?

**Comment by yamalight** [comment]
@bebraw ah, yes, 4.x works perfectly fine! 
totally forgot about this issue, will close it now :)
