### ISSUE TITLE
 webpack 5.0.0-rc.3 hashes in chunk output filename  leads to broken bundle

### ISSUE THREAD

**Issue by FabianHippmann** [webpack/webpack#11567]
# Bug report

**What is the current behavior?**
Using for example `[name].[contenthash].js`as the filename in output.filename leads to a compiled bundle where the `contenthash` gets compiled as a variable instead of a string. 

```js
/******/ 				var href = "" + ({}[chunkId]||chunkId) + "." + __webpack_require__.h ? __webpack_require__.h() : 33a77d7a305d7b86ce61 + ".css";

```

the using a different separator works - `[name]-[contenthash].js`

**If the current behavior is a bug, please provide the steps to reproduce.**
This occurs randomly - we had this error on different machines - with the same node/yarn etc. versions. 

Webpack config here -> https://gist.github.com/FabianHippmann/b122bc99ed10059325720796f0259bad

Bc this also affects the mini-css-plugin i opened an issue there -> https://github.com/webpack-contrib/mini-css-extract-plugin/issues/596

**What is the expected behavior?**
`contenthash`should be compiled as a string. 

for example: 
```js
/******/ 				var href = "" + ({}[chunkId]||chunkId) + "." + __webpack_require__.h ? __webpack_require__.h() : "33a77d7a305d7b86ce61" + ".css";

```

**Other relevant information:**
webpack version:  webpack 5.0.0-rc.3
Node.js version: v12.18.4
Operating System: Ubuntu 20.04
Additional tools:

**Comment by evilebottnawi** [comment]
Please do not duplicate issues, close in favor https://github.com/webpack-contrib/mini-css-extract-plugin/issues/596
