### ISSUE TITLE
typeof process check inlining

### ISSUE THREAD

**Issue by guybedford** [webpack/webpack#11569]
## Feature request

**What is the expected behavior?**

It should be possible to inline `typeof process !== 'undefined' && process.env.NODE_ENV === 'production'` checks used in ES modules.

**What is motivation or use case for adding/changing the behavior?**

It is important that it is possible to write ES modules that do not assume that the `process` global must exist if we are to move to a truly native ecosystem.

But Webpack is actively inhibiting this pattern in that `typeof process !== 'undefined' && process.env.NODE_ENV === 'production'` checks with inlining will cause process to be pulled in.

The solution here would be to have the `process.env.NODE_ENV` inlined definition also cause `typeof process !== 'undefined'` to be inlined when it is combined into the same expression check in this way (specifically that the condition is the intersection of these respective conditions, it is fine for a lone `typeof process !== 'undefined'` to remain equivalent).

**How should this be implemented in your opinion?**

As a specific pattern match on the expression case of this intersection of conditions and extended inlining of the whole expression. It may be worthwhile to include some minor variations but even if it's just this pattern specifically that is hugely beneficial.

**Comment by evilebottnawi** [comment]
We don't use `process` and `process.env`, what do you mean?

**Comment by guybedford** [comment]
Ah, yes there was some confusion in the original PR over whether `process` in an ES module would be built in by Webpack. AFAICT it is not currently, but correct me if I am wrong.

**Comment by evilebottnawi** [comment]
No `process` in webpack@5, and polyfilling process on webpack@4, if you use target `web` and using `process`
