### ISSUE TITLE
[Bug/Feature Request] `__dirname` resolves to unexpected values

### ISSUE THREAD

**Issue by manuth** [webpack/webpack#11579]
## Feature request
I have no option to set for `node.__dirname` that suites my needs.
This issue is related to #4303 and #1599 .

**What is the expected behavior?**
***src/main.ts***
```ts
require("./Properties/Settings");
```

***src/Properties/Settings.ts***
```ts
console.log(__dirname);
```

When running the bundle, I'd expect the absolute path to `[bundle-root]/[relative path from bundle-root to context]/src/Properties` to be logged.

**What is motivation or use case for adding/changing the behavior?**
The current behavior of `__dirname` is unexpected.
When working with `__dirname` you'd expect that the path either resolves to the **absolute** path to `src/Properties` or `out/Properties` but neither is the case.

* When setting `node.__dirname` to `true`, `src/Properties` is logged
  * The path is not absolute and depends on the current working directory which might cause huge issues (especially when the bundle is installed as a dependency)
* When setting `node.__dirname` to `false`, `[bundle-root]` (`lib`) is logged
  * For the `src/main.ts`-file this might look correct, but for `src/Properties/Settings.ts` you would expect `lib/Properties`
* When ommitting `node.__dirname` or setting `node.__dirname` to `"mock"`, `/` is logged
  * This behavior might break every case where you might want to use `__dirname`

**How should this be implemented in your opinion?**
A new option similar to `node.__dirname = "mock"`

**Are you willing to work on this yourself?**
Probably

**Comment by manuth** [comment]
What I've noticed is that, cause of this behavior, modules such as `puppeteer` and every other module depending on `__dirname` don't work correctly.

**Comment by evilebottnawi** [comment]
It is expected, and described in https://github.com/webpack/webpack/issues/4303 and https://github.com/webpack/webpack/issues/1599

**Comment by manuth** [comment]
@evilebottnawi please keep in mind that this is a feature request and therefore logically is not expected by me and causes huge trouble in my projects.

And as described in this issue, `mock` neither suits my needs nor solves my issue. Could you please reopen my issue and help me to provide a new feature as described in this issue?

**Comment by evilebottnawi** [comment]
@manuth It works as expected as I written above, please provide example where it "broken"

**Comment by manuth** [comment]
@evilebottnawi thanks for hearing me out
The most common use-case for the `__dirname`-variable is to load or store resources at a known location.

`puppeteer`, for instance, usually downloads chromium to its package-directory using `__dirname`.
Cause of the `__dirname` not resolving to the source-directory, the `.local-chromium`-directory is being created at the wrong place. This behavior doesn't break the functionality of `puppeteer`, though

What's more frustrating is, that my package loads resources from yml-files and reads them using `__dirname`. In this case, the behavior of webpack breaks my module.

I'm currently using a handmade module as a workaround.

**Comment by evilebottnawi** [comment]
Why do not use `__dirname: false`?

**Comment by manuth** [comment]
Though I had to fiddle with the paths to make them match to the bundle-root, this did the trick
Thanks for taking time
