### ISSUE TITLE
[Module Federation] If shared scope is not specified, federation fails completely

### ISSUE THREAD

**Issue by rramaa** [webpack/webpack#11587]
# Bug report

**What is the current behavior?**
While using Module Federation Plugin, if `shared` field is not specified, an error is thrown(Cannot read property default of undefined)

<img width="615" alt="Screenshot 2020-10-06 at 4 11 23 PM" src="https://user-images.githubusercontent.com/16651792/95191607-98142500-07ee-11eb-9eec-dbc73e7ca375.png">.

<img width="1133" alt="Screenshot 2020-10-06 at 4 36 16 PM" src="https://user-images.githubusercontent.com/16651792/95193883-2938cb00-07f2-11eb-933c-aee71d1ac621.png">
Line number 16 is the problem

The whole application stops working and nothing is displayed on the screen.

**If the current behavior is a bug, please provide the steps to reproduce.**
I have forked the `module-federation-examples` repo and modified the `basic-host-remote` example. I have removed the `shared` field from both `app1` and `app2`. Upon running the application with `yarn start`, this error can be seen on the browser(on the host application).

Links:
[basic-host-remote](https://github.com/rramaa/module-federation-examples/tree/share_scope_issue/basic-host-remote)
[host-config](https://github.com/rramaa/module-federation-examples/blob/share_scope_issue/basic-host-remote/app1/webpack.config.js#L41)
[remote-config](https://github.com/rramaa/module-federation-examples/blob/share_scope_issue/basic-host-remote/app2/webpack.config.js#L35)

my guess is that `__webpack_require__.S` directly depends on the `shared` key.

**What is the expected behavior?**
If `shared` key is a required property, then the webpack build should fail with the appropriate message(as it happens for other keys)
If `shared` key is not a required property, then the application should run

**Other relevant information:**
webpack version:  `5.0.0-rc.3`

Node.js version: `12.18.3`

Operating System: MacOS Catalina

Additional tools: `lerna` and `yarn workspaces`

**Comment by sokra** [comment]
fixed by #11421

update your remote to the latest RC

**Comment by rramaa** [comment]
Worked!
Thanks!
