### ISSUE TITLE
allow to use loader functions that are defined not only in `module.exports = func...`, but allow custom fields also

### ISSUE THREAD

**Issue by srghma** [webpack/webpack#11581]
## Feature request

**What is motivation or use case for adding/changing the behavior?**

what if a loader file exports loader function NOT from `module.exports = `

e.g.

```
module.exports = function(source) {
  var callback = this.async();
  callback(null, 'RESULT')
};
```

to use it as

```
....
resolveLoader: {
  alias: { "my-loader": './filepath.js' }
}
```

BUT from  `module.exports.foo = `

```
module.exports.foo = function(source) {
  var callback = this.async();
  callback(null, 'RESULT')
};
```

and use it as

```
....
resolveLoader: {
  alias: { "my-loader": { path: './filepath.js', field: 'foo' }
}
```

**How should this be implemented in your opinion?**

as above

**Are you willing to work on this yourself?**
no

**Comment by evilebottnawi** [comment]
Why do you need this?

**Comment by srghma** [comment]
hi @evilebottnawi 

I want to write loaders in purescript

but purescript cannot export loader as `module.exports = ...`

it can only export it as `module.exports.loader = ...`

https://github.com/srghma/purescript-halogen-nextjs/blob/74e1165512d94cd7424ec4d70af73e3915ab8832/webpack/NextjsWebpack/IsomorphicClientPagesLoader.purs#L1

![2020-10-06-13:10:58-screenshot](https://user-images.githubusercontent.com/7573215/95188685-735f8380-07d5-11eb-8f36-ce19fbcca814.png)

https://github.com/srghma/purescript-halogen-nextjs/blob/74e1165512d94cd7424ec4d70af73e3915ab8832/webpack/NextjsWebpack/WebpackConfig/Config.purs#L161-L165

https://github.com/srghma/purescript-halogen-nextjs/blob/74e1165512d94cd7424ec4d70af73e3915ab8832/webpack/NextjsWebpack/WebpackConfig/Config.purs#L77

then, I want to use this loader either as

```
resolveLoaders: {
  alias: { 'isomorphic-client-pages-loader': '/home/srghma/projects/purescript-halogen-nextjs/output/NextjsWebpack.IsomorphicClientPagesLoader/index.js` }
}
....
entry: { myPage1: 'isomorphic-client-pages-loader?pageData=somePageData!' }
```

or right away as 

```
entry: { myPage1: '/home/srghma/projects/purescript-halogen-nextjs/output/NextjsWebpack.IsomorphicClientPagesLoader/index.js?pageData=somePageData!' }
```

______

P.S. the thing is the spago output path `/home/srghma/projects/purescript-halogen-nextjs/output` cannot be known beforehand and is passed by user as cli argument

it means I cannot do

```
resolveLoaders: {
  alias: { 'isomorphic-client-pages-loader': '/home/srghma/projects/purescript-halogen-nextjs/wrapper.js` }
}
....
entry: { myPage1: 'isomorphic-client-pages-loader?pageData=somePageData!' }
```

and in `wrapper.js`

```
module.exports = require('/home/srghma/projects/purescript-halogen-nextjs/output/NextjsWebpack.IsomorphicClientPagesLoader/index.js').loader
```

_______________


**I have tried also the fragment thing** I have found in https://github.com/webpack/enhanced-resolve/blob/d2a56e227d228d4fad6451e5e489473c72e63171/test/exportsField.js#L1459-L1477

though I don't know what the fragment means - cant find documentation

no results

![2020-10-06-11:32:18-screenshot](https://user-images.githubusercontent.com/7573215/95189728-e87f8880-07d6-11eb-9518-82a9678169cd.png)
![2020-10-06-11:32:32-screenshot](https://user-images.githubusercontent.com/7573215/95189738-e9b0b580-07d6-11eb-96cd-24d05fba0917.png)
![2020-10-06-11:32:42-screenshot](https://user-images.githubusercontent.com/7573215/95189739-ea494c00-07d6-11eb-8445-b8621b6f9949.png)

**Comment by evilebottnawi** [comment]
Yep, let's improve this

**Comment by srghma** [comment]
@evilebottnawi maybe you know if it's possible to write a plugin to use it like

```js
resolveLoader: { 
  plugins: [ 
     new MyLoaderImportFromFieldPlugin()
  ],
  alias: {
    'isomorphic-client-pages-loader': 'MyLoaderImportFromFieldPlugin?path=/home/srghma/projects/purescript-halogen-nextjs/output/NextjsWebpack.IsomorphicClientPagesLoader/index.js&field=loader'
  }  
},
....
entry: { myPage1: 'isomorphic-client-pages-loader?pageData=somePageData!' }
```

and write plugin (similar to https://github.com/shaketbaby/directory-named-webpack-plugin/blob/master/index.js )


```
module.exports = function() {
  return {
    apply: function(options, resolver) {
      // file type taken from: https://github.com/webpack/enhanced-resolve/blob/v4.0.0/test/plugins.js
      var target = resolver.ensureHook("undescribed-raw-file");

      resolver.getHook("before-existing-directory")
        .tapAsync("MyLoaderImportFromFieldPlugin", (request, resolveContext, callback) => {
          // how to return function from module.exports.loader ???
          resolver.doResolve(????file, ???obj, "using path: " + filePath, resolveContext, innerCallback);
        }
    }
  }
}
```

**Comment by evilebottnawi** [comment]
Hm, https://github.com/webpack/loader-runner/blob/master/lib/loadLoader.js#L48, I think you can use `default` :smile: to achieve this right now, we should send a PR to https://github.com/webpack/loader-runner

**Comment by sokra** [comment]
Use `default` as property. That should be enough. I don't think we need another one or the ability to customize that

**Comment by srghma** [comment]
Tnx a lot!!, it worked https://github.com/srghma/purescript-halogen-nextjs/commit/40f8aa2b03eb5524310f7db8be9e1d2b67b78c9c

this is not needed anymore)
