### ISSUE TITLE
Webpack 5.0.0-beta.31 broke operations on arrays imported from JSON files

### ISSUE THREAD

**Issue by wojtekmaj** [webpack/webpack#11588]
# Bug report

I have the following code in my project (simplified):

```js
import types from '../../../../../../config/types.json';

function getLabel(data) {
  return types.find(
    el => el.type === data.type,
  ).label;
}

function validate({
  response,
  data,
}) {
  const { type } = response;

  if (type !== formData.type) {
    console.warn(`Type mismatch: '${formData.type}' provided, expected '${type}'.`);

    const typeLabel = getLabel(data);

    return `It looks like ${typeLabel} type is wrong.`;
  }
}
```

where imported `types.json` is something like

```
[
  {
    "label": "Label",
    "type": 1
  }
  {
    "label": "Another label",
    "type": 2
  }
]
```

and obviously, `validate()` function is ran at some point.

After upgrading from Webpack `5.0.0-beta.29` to `5.0.0-rc.3`, I've noticed that this function started crashing.

I investigated by updating it step by step and here's my outcome:

| Version | Works? |
| -- | -- |
| 5.0.0-beta.29 | Yes ✅  |
| 5.0.0-beta.30 | Yes ✅  |
| 5.0.0-beta.31 | No ❌  |
| 5.0.0-rc.0 | No ❌  |
| 5.0.0-rc.3 | No ❌  |

**What is the current behavior?**

In `5.0.0-beta.31`, `5.0.0-rc.0`, `5.0.0-rc.3` it's compiled to (whitespace added for readability):

```js
if(o!==s.type)
  return console.warn("Type mismatch: '"+s.type+"' provided, expected '"+o+"'."), 
  "It looks like "+function(e){return(void 0)((function(t){return t.type===e.type})).label}(s)+" type is wrong.";
```

which causes the following error:

```
TypeError: (void 0) is not a function
```

**What is the expected behavior?**

In `5.0.0-beta.29`, `5.0.0-beta.30`, `if` statement is compiled to (whitespace added for readability):

```js
if(o!==s.type)
  return console.warn("Type mismatch: '"+s.type+"' provided, expected '"+o+"'."), 
  "It looks like "+function(e){return _.find((function(t){return t.type===e.type})).label}(s)+" type is wrong.";
```

which correctly prints

```
Type mismatch: <type> provided, expected <expectedType>.
```

and correctly returns

```
It looks like <type.label> type is wrong.
```

**Other relevant information:**

Changing types.json from to `js` (`export default [{…}, {…}]`) makes it all working again.

Similarly, changing the code slightly not to do direct operations on array imported from JSON:

```diff
-import rawTypes from '../../../../../../config/types.json';
+import rawTypes from '../../../../../../config/types.json';
+
+const types = [...rawTypes];

function getLabel(data) {
  const { label } = types.find(
    el => el.type === data.type,
  );

  return label;
}
```

also fixes the issue.

So my diagnosis is: tree-shaking / or minifying / or module concatenating functionality, starting with 5.0.0-beta.31, stopped correctly recognizing Array.find on arrays imported from JSON files, causing them be "resolved" to `void 0`, and consequently, to no longer work.

webpack version: 5.0.0-rc.3
Node.js version: 14.5.0
Operating System: macOS Big Sur

**Comment by vankop** [comment]
Thanks for report!
Closing in favor of https://github.com/webpack/webpack/issues/11580
