### ISSUE TITLE
Extract CSS on JS file

### ISSUE THREAD

**Issue by borisdamevin** [webpack/webpack#11593]
Hi,

I'm looking to do the following thing for work with **Web Components** and **LitElement**: extract the CSS (via Sass) into a JS file, into a variable and if I have multiple CSS files, this based on a JS file template and only change one variable inside .

I can't find a solution, is this possible with Webpack?

**Example:**

**Source**

The Sass file:

 ```scss
body { 
    background: red;
}
```

**Output**

The JS file generated, not the CSS file _(from template file ``sass-template.tpl`` if multiple CSS sources)_:

```js
import { css } from 'lit-element';

export const style = css`body { background: red; }`;
```

**Comment by evilebottnawi** [comment]
No, it is out of scope webpack, but you can write a plugin/loader for this, better open an issue in `lit-element`, but you can use:
```
import styles from './style.css';
import { css } from 'lit-element';

export const style = css`${styles}`;
```

**Comment by borisdamevin** [comment]
@evilebottnawi I already try that, but ``import styles from './style.css';`` is an empty object.

**Comment by evilebottnawi** [comment]
@borisdamevin hm, yep, I was wrong, you need loader for this, we can implement this using `style-loader` + some extra loader/plugin, let's close in favor https://github.com/webpack-contrib/style-loader/issues/328#issuecomment-516437065
