### ISSUE TITLE
I am trying to upgrade from webpack 4 to 5 and got deprecation error in angular 10

### ISSUE THREAD

**Issue by AntonyRavelA** [webpack/webpack#11598]
Promise rejection: Error: NormalModuleFactory.beforeResolve is no longer a waterfall hook, but a bailing hook instead. Do not return the passed object, but modify it instead. Returning false will ignore the request and results in no module created.
[webpack-cli] Error: NormalModuleFactory.beforeResolve is no longer a waterfall hook, but a bailing hook instead. Do not return the passed object, but modify it instead. Returning false will ignore the request and results in no module created.
    at E:\Pocs\angular-webpack\node_modules\webpack\lib\NormalModuleFactory.js:644:11
    at eval (eval at create (E:\Pocs\angular-webpack\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:14:1)
    at runNextTicks (internal/process/task_queues.js:58:5)
    at processImmediate (internal/timers.js:412:9)

**Comment by evilebottnawi** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Please use rc release of `webpack-cli`
