### ISSUE TITLE
[Module Federation] Webpack build fails if shared is a non empty array in Module Federation Plugin

### ISSUE THREAD

**Issue by rramaa** [webpack/webpack#11596]
# Bug report

**What is the current behavior?**
On running webpack build(I am using `webpack-dev-server`), the build fails with the following stack trace
```
TypeError: b.isAsync is not a function
    at processBlock (<project-path>/node_modules/webpack/lib/buildChunkGraph.js:412:10)
    at processQueue (<project-path>/node_modules/webpack/lib/buildChunkGraph.js:467:6)
    at visitModules (<project-path>/node_modules/webpack/lib/buildChunkGraph.js:761:3)
    at buildChunkGraph (<project-path>/node_modules/webpack/lib/buildChunkGraph.js:925:2)
    at Compilation.seal (<project-path>/webpack/lib/Compilation.js:1874:3)
    at <project-path>/webpack/lib/Compiler.js:972:20
    at <project-path>/node_modules/webpack/lib/Compilation.js:1709:4
    at eval (eval at create (<project-path>/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:45:1)
    at <project-path>/node_modules/webpack/lib/FlagDependencyExportsPlugin.js:284:11
    at <project-path>/node_modules/neo-async/async.js:2830:7
    at Object.each (<project-path>/node_modules/neo-async/async.js:2850:39)
    at <project-path>/node_modules/webpack/lib/FlagDependencyExportsPlugin.js:263:18
    at <project-path>/node_modules/neo-async/async.js:2830:7
    at Object.each (<project-path>/node_modules/neo-async/async.js:2850:39)
    at <project-path>/node_modules/webpack/lib/FlagDependencyExportsPlugin.js:41:16
    at Hook.eval [as callAsync] (eval at create (<project-path>/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:41:1)
```

This only happens when the `shared` option of the `ModuleFederation` plugin is a non empty array and the webpack version is at least `5.0.0-rc.0`. This is also happening on the latest `rc.4`
The build runs successfully on version `5.0.0-beta.29`.

If the `shared` option is an empty array, then also the build runs successfully.

Configuration for ModuleFederationPlugin:
```
{
    name: "shell",
    filename: "remoteEntry.js",

    remotes: {
      shell2: "shell2@http://localhost:3002/remoteEntry.js"
    },
    shared: ["react", "react-dom"]
  }
```
Rest of the configuration is same as the module federation examples repo

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Upgrade the webpack version to `5.0.0-rc.4`
2. Use the above given configuration.
3. Run `webpack-dev-server`
4. Build should fail

**What is the expected behavior?**
Build should not fail. The behavior should be the same as in previous beta versions.

**Other relevant information:**
webpack version:  `5.0.0-rc.4`

Node.js version:  12.18.3

Operating System: MacOS Catalina

Additional tools: `yarn` and `lerna`

**Comment by evilebottnawi** [comment]
`webpack-dev-server` is not supported module federation, but it should not failed with `b.isAsync is not a function`, please create reproducible test repo

**Comment by rramaa** [comment]
Will do...I missed mentioning that webpack build fails even when it is started without the dev server

**Comment by sokra** [comment]
Could you validated that you are really the latest RC? Also check if there are not multiple webpack version installed: `yarn why webpack`

I'm asking because the `b.isAsync` line has been removed in this commit: https://github.com/webpack/webpack/commit/ed06a7f83a7cb7542ff7d9df9fa9755154679258#diff-fb5505dfa4e1d04d2eed8f03d4834740L427 since beta.30

**Comment by rramaa** [comment]
Thanks it worked! 🎉 
Was due to a version mismatch due to monorepo(multiple webpack versions were installed)
