### ISSUE TITLE
Option 'bail' causes failed build

### ISSUE THREAD

**Issue by meskill** [webpack/webpack#11594]
# Bug report

**What is the current behavior?**

Setting option [bail](https://webpack.js.org/configuration/other-options/#bail) to true will break the build for unresolved modules wrapped in try...catch
After setting bail to false bundle builds successfully

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Set bail: true in config
1. Add require to unresolved module wrapped in try...catch
	```
	let packageJson = {};
	
	try {
	  packageJson = require('../../../../package.json');
	} catch (e) {
	}
	```
1. Start build as always

**What is the expected behavior?**

There is should be only a warning about the unresolved module, bundle should be built successfully.

**Other relevant information:**
webpack version: 5.0.0-rc.3 
Node.js version: 12.18.4

**Comment by evilebottnawi** [comment]
Unresolved module is the error

**Comment by meskill** [comment]
@evilebottnawi, please, look carefully
require is wrapped in try..catch so error for an unresolved module is handled, and it works fine without the option

![image](https://user-images.githubusercontent.com/8974488/95340383-c14fb680-08bd-11eb-95b6-f39800767dd7.png)

**Comment by evilebottnawi** [comment]
It is default behavior for webpack@4 and webpack@5 we are static analyzer

**Comment by evilebottnawi** [comment]
Oh, I was wrong here, it is bug on `webpack-cli`, please use latest `rc` release

**Comment by evilebottnawi** [comment]
From my test:
```js
WARNING in ./test.js 4:18-53
Module not found: Error: Can't resolve '../../../../package.json' in '/home/user/path/to/package'
```

```bash
# echo $?
0
```

**Comment by meskill** [comment]
@evilebottnawi I've created a test repo to show this issue and the difference between webpack4 and webpack5 
https://github.com/meskill/webpack5-bail-option-repro

**Comment by code1x1** [comment]
is it a bug for sure? 

shouldn't webpack only care if the required source is not found while the bundler is running even though the require is inside a try catch.

and not if a require is resolving in runtime because of the try catch. 

I think those cases should be handled by setting the externals property in config?!?
https://webpack.js.org/configuration/externals/

**Comment by meskill** [comment]
> is it a bug for sure?
> 
> shouldn't webpack only care if the required source is not found while the bundler is running even though the require is inside a try catch.
> 
> and not if a require is resolving in runtime because of the try catch.
> 
> I think those cases should be handled by setting the externals property in config?!?
> https://webpack.js.org/configuration/externals/

this bug describes only bundle-time case.
we have a tool to wrap a webpack execution from our users and thats why we may face case when user app doesn't have some dependencies in their modules tree.
And it works as expected, except for this bug, when option `bail: true` leads to unsuccessful build

**Comment by alexander-akait** [comment]
bump
