### ISSUE TITLE
Unable to build because of error with export from v. 5 beta 30

### ISSUE THREAD

**Issue by mariusrak** [webpack/webpack#11597]
# Bug report
I'm unable to compile [fluent](https://github.com/projectfluent/fluent.js) with new versions of webpack.

**What is the current behavior?**
After an update to webpack 5.0.0-beta.30 or higher, I get an error during compilation:
```
ERROR in ./node_modules/@fluent/bundle/esm/index.js 9:0
Module parse failed: 'import' and 'export' may appear only with 'sourceType: module' (9:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|  *
|  */
> export { FluentBundle } from "./bundle.js";
| export { FluentResource } from "./resource.js";
| export { FluentType, FluentNumber, FluentDateTime } from "./types.js";
 @ ./index.js 1:0-62 2:12-24 2:26-40
 ```

**If the current behavior is a bug, please provide the steps to reproduce.**
https://github.com/mariusrak/Webpack5FluentError

**What is the expected behavior?**
It should be built without an error same as with webpack 5.0.0-beta.29 or lower

**Other relevant information:**
webpack version:  5.0.0-beta.30
Node.js version: 12.16.3
Operating System: Windows 10 Pro 1909
Additional tools: babel-loader, fluent

**Comment by evilebottnawi** [comment]
Interesting problem - `@fluent` has `"type": "commonjs",` and have `"module": "./esm/index.js",`, webpack thinks it is commonjs module

**Comment by mariusrak** [comment]
So it is an issue of webpack or fluent? I've reported issue also at fluent https://github.com/projectfluent/fluent.js/issues/517

**Comment by sokra** [comment]
`"module": "./esm/index.js",` doesn't flag files as ESM. It's only an entrypoint.

You can put a `{ "type": "module" }` package.json into the `@fluent/bundle/esm` folder to fix that.

**Comment by evilebottnawi** [comment]
You can use https://github.com/ai/dual-publish to achieve supporting commonjs/mjs

**Comment by mariusrak** [comment]
So there is mistake in the fluent package? Can I as a user do something about it?

**Comment by evilebottnawi** [comment]
> So there is mistake in the fluent package?

Yep

> Can I as a user do something about it?

Use `resolve.alias` and point to right file

**Comment by sokra** [comment]
> > Can I as a user do something about it?
> 
> Use `resolve.alias` and point to right file

I don't think this will help here. You need to flag the files as ESM:

```js
module.rules: [{
  test: /\.js/,
  include: /@fluent[\\/]bundle[\\/]esm/,
  type: "javascript/auto"
}]
```

**Comment by mariusrak** [comment]
Both solutions helped.
But why it worked till 5 beta 29?

**Comment by evilebottnawi** [comment]
@mariusrak because we start to support `"type": "commonjs"`/`"type": "module"` since beta.29

**Comment by brettz9** [comment]
IMV, I don't think this behavior of Fluent should actually be treated as a bug. Some browsers might not recognize ".mjs" (or "maybe .cjs") to handle it properly as JavaScript, so it should be possible to use the ".js" extension for "browser" for say ESM browser, and possibly say "default" for UMD. (IMO, Webpack should, create a distinct "umd" type if wishing to support importing of non-ESM browser files and always expect ESM in both `browser` and `default`.)

The `type` field relates to how *Node* processes modules. The whole idea of the other conditionals is to let them use what works for their environments and requirements.
