### ISSUE TITLE
resolve.fallback fails for linked packages

### ISSUE THREAD

**Issue by Hornwitser** [webpack/webpack#11600]
# Bug report

**What is the current behavior?**

Configuring `resolve.fallaback` does not work for modules linked from outside the package directory that webpack is being used from.  For example with the following file structure

```
root/
  +- pkg-a/
  |  +- package.json
  |  +- index.js (containing require("path"))
  +- pkg-b/
     +- package.json (containing dependency "pkg-a": "file:../pkg-a", webpack, webplack-cli and path-browserify)
     +- src/
     |  +- index.js (containg require("pkg-a"))
     +- webpack.config.js (containing resolve.fallback.path: "path-browserify")
```
Webpack fails to build with the error
```
assets by status 252 bytes [cached] 1 asset
./src/index.js 59 bytes [built] [code generated]
../pkg-a/index.js 30 bytes [built] [code generated]

ERROR in ../pkg-a/index.js 1:13-28
Module not found: Error: Can't resolve 'path' in 'webpack-bug/pkg-a'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add an fallback 'resolve.fallback: { "path": "path-browserify" }'
        - install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "path": false }
 @ ./src/index.js 2:10-26

webpack 5.0.0-rc.4 compiled with 1 error in 203 ms
```

This file structure is similar to how monorepos with tools like lerna are set up.

**If the current behavior is a bug, please provide the steps to reproduce.**

See [this repository](https://github.com/Hornwitser/webpack-bug) for a minimal reproduction example.  Note that if pkg-a is moved into pkg-b/node_modules the build succeed.

**What is the expected behavior?**

Module fallback should work irrespective of whether the package is linked from outside or installed into node_modules.

**Other relevant information:**
webpack version:  5.0.0-rc.4
Node.js version: v14.9.0
Operating System: Arch Linux
Additional tools: None.

**Comment by evilebottnawi** [comment]
I think it is expected, try to change:
```
{
  resolve: {
        fallback: { "path": false }
  }
}
```

wepback try to resolve `path-browserify` in root and can't find it, you need to specify full path to fallback:
```
module.exports = {
    mode: "production",
    resolve: {
        fallback: { "path": require.resolve("path-browserify") }
    }
}
```

**Comment by evilebottnawi** [comment]
Maybe we should improve the error message here

**Comment by evilebottnawi** [comment]
Pseudo code:
```
const path = require("path"); -> const path = require("path-browserify");
```

But here no `path-browserify` module

**Comment by Hornwitser** [comment]
I can confirm that
```
fallback: { "path": require.resolve("path-browserify") }
```
does work here.  Thought I can't really comment on whether or not that is the right behaviour.

**Comment by sokra** [comment]
The behavior is correct, but we should improve our breaking change message to include the `require.resolve`. Do you want to send a PR?

**Comment by Hornwitser** [comment]
Do you mean change https://github.com/webpack/webpack/blob/96383923c81935c9d7a4766933af0a067ec7e3b7/lib/ModuleNotFoundError.js#L69
to read `\t- add an fallback 'resolve.fallback: { "${request}": require.resolve("${alias}") }'\n`?

**Comment by sokra** [comment]
Yep perfect. Maybe you can also fix the `an fallback` typo to `a fallback`.

**Comment by Hornwitser** [comment]
There's an issue with this suggestion.  It does not work for replacement packages that are shadowed by the builtin ones.  e.g., for `require("events")` it suggest installing `events`, but doing `require.resolve("events")` returns the string `"events"` instead of the path to the events package that's installed into node_modules.

**Comment by sokra** [comment]
I think you can use `require.resolve("events/")`. Does that work?

**Comment by Hornwitser** [comment]
Yes.  That works.
