### ISSUE TITLE
[DllPlugin] manifest has relative paths to dependency files within node_modules

### ISSUE THREAD

**Issue by jedwards1211** [webpack/webpack#11604]
# Bug report

**What is the current behavior?**

If the `context` in my webpack is a subfolder of my project folder like `src`, then the Dll manifest will contain entries like `"content":{"../node_modules/react/index.js":{"id":1,`

In this case I'm not sure a third-party bundle built with DllReferencePlugin on this manifest can even resolve `react` to the dll bundle.  Unless that third-party bundle is built with `context` as a subfolder of its project folder as well.

So it seems like I have to use my root project folder as context, but the draw back is third-party bundles referencing my own project's source files in the dll bundle have to use paths like `myScope/src/file.js`.  I wanted that to just be `myScope/file.js` without breaking dependency imports like `react`.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

Regardless of where `node_modules` is relative to the webpack context, `node_modules/react/index.js` is entered in the manifest as
`"content":{"react/index.js":{"id":1,`

**Other relevant information:**
webpack version:  4.28.0
Node.js version: N/A
Operating System: N/A
Additional tools: N/A

**Comment by jedwards1211** [comment]
I guess I can work around this by building two separate dlls... But I'd really like to keep the number of separate webpack steps down

**Comment by evilebottnawi** [comment]
Please read https://github.com/webpack/webpack/issues/3800#issuecomment-383905446, feel free to feedback

**Comment by jedwards1211** [comment]
@evilebottnawi I know that the context parameter affects the relative paths to node_modules...

I think this is unhelpful behavior...I'm asking for paths to note modules to **not be relative**.

**Comment by jedwards1211** [comment]
In other words, if in project A I have

* node_modules/react
* src/client

And I webpack DLL with context: src/client

And in project B I have

* node_modules/react
* src

And I webpack with context: src and all reference, I want the bundle for project B to use react from project A's Dll.  A and B have different relative paths from the context dir to their node_modules but I don't want that to prevent B from being able to use A Dll's node_modules in any case.

**Comment by jedwards1211** [comment]
Can we reopen with title:

### [Feature Request] Use non relative paths in Dll manifest for modules inside node_modules

**Comment by evilebottnawi** [comment]
I don't think it is valid, you can have different version of react, it will be break your app, I think you search module federation,

**Comment by jedwards1211** [comment]
Yes that's what I'm trying to accomplish, I need the thing using Dll reference to get the same exact instance of react as the rest of the app.  This is inherently tedious to explain, seems I'm not making it clear.  I'm requesting a way to reference dll modules by absolute npm package, not by path on disk

**Comment by evilebottnawi** [comment]
make sense

**Comment by jedwards1211** [comment]
Seems like module federation might work but them I'm not sure what's the point of DllPlugin vs. module federation

**Comment by jedwards1211** [comment]
Oh so `ContainerPlugin`, `ContainerReferencePlugin` etc. aren't implemented in Webpack 4 I guess?

**Comment by evilebottnawi** [comment]
Yes, not implemented, only webpack@5

**Comment by jedwards1211** [comment]
reading more about the module federation stuff, it definitely solves these issues in a way DllPlugin doesn't, so I'll just close this issue
