### ISSUE TITLE
React DND(Drag N Drop) is facing a compatibility issue with webpack5 as one of the changes introduced as part of WP5 is setting the 'process' node to false, which is used by react DND.

### ISSUE THREAD

**Issue by liebenjoy** [webpack/webpack#11611]
# Bug report
Webpack 5 removes process, effectively making it impossible to use the [react-dnd](https://github.com/react-dnd/react-dnd) library since it has code like:

function asap(task) {
  var rawTask;

  if (freeTasks.length) {
    rawTask = freeTasks.pop();
  } else {
    rawTask = new RawTask();
  }

  rawTask.task = task;
  rawTask.domain = process.domain;
  (0, _raw.rawAsap)(rawTask);
}

**What is the current behavior?**
React DND(Drag N Drop) is facing a compatibility issue with webpack5 as one of the changes introduced as part of WP5 is setting the 'process' node to false, which is used by react DND.

**If the current behavior is a bug, please provide the steps to reproduce.**
Use react-dnd 11.x and Webpack 4. Add the following to your Webpack config:

    node: {
      Buffer: false, // WEBPACK 5: Remove
      process: false, // WEBPACK 5: Remove
    },

**What is the expected behavior?**
react-dnd should work in Webpack 5 builds

**Other relevant information:**
webpack version:  5
Node.js version: 12.6.1
Operating System: Windows
Additional tools:

**Comment by evilebottnawi** [comment]
You need to polyfill this, please read https://webpack.js.org/migrate/5/

**Comment by sokra** [comment]
> rawTask.domain = process.domain;

`process` is not available in a browser. Assuming so it not correct.

webpack 5 no longer polyfill `process` to point out these issues.
