### ISSUE TITLE
Fix semantic of target property

### ISSUE THREAD

**Issue by smelukov** [webpack/webpack#11610]
In the target-property, we have different semantic for the different platforms:
`node-webkit[X[.Y]]`
`electron[X[.Y]]-main`

**What is the expected behavior?**

It should be `node[X[.Y]]-webkit` or `<product>[<version>][/<subtype>]`

**What is motivation or use case for adding/changing the behavior?**

Semantic

**How should this be implemented in your opinion?**

Support `<product>[<version>][/<subtype>]`

We should support both versions (for not making a breaking change) with a warning for old semantic

**Are you willing to work on this yourself?**

yes

**Comment by evilebottnawi** [comment]
@smelukov I think we can close it
