### ISSUE TITLE
TypeError: Cannot read property 'range' of null at /node_modules/webpack/lib/optimize/SideEffectsFlagPlugin.js:132:56

### ISSUE THREAD

**Issue by Akkuma** [webpack/webpack#11615]
# Bug report
SideEffectsFlagPlugin appears to not handle certain cases preventing webpack from successfully completing
`TypeError: Cannot read property 'range' of null at /node_modules/webpack/lib/optimize/SideEffectsFlagPlugin.js:132:56`

**What is the current behavior?**
```
Module parse failed: Cannot read property 'range' of null
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
TypeError: Cannot read property 'range' of null
    at /app/client/node_modules/webpack/lib/optimize/SideEffectsFlagPlugin.js:132:56
```

**If the current behavior is a bug, please provide the steps to reproduce.**
```js
import uuid from '@lukeed/uuid'

const test = 1;
console.log(uuid());
```

Ran webpack against this file using:
```js
const webpack = require('webpack');
const path = require('path');

const config = {
  context: __dirname,
  entry: { 
    test: './app/test.js',
  },
  output: {
    filename: '[name]-bundle.js',
    path: path.resolve(__dirname, '../app/assets/javascripts/generated'),
  },
  plugins: [
    new webpack.ContextReplacementPlugin(/moment[\/\\]locale$/, /en/),
  ], 
};

module.exports = config;
```

**What is the expected behavior?**
SideEffectsFlagPlugin doesn't prevent webpack from completing by either bailing from the optimization or handling these cases.

**Other relevant information:**
webpack version:  5.0.0-rc.4
Node.js version: 14.11.0
Operating System: Dockerfile node:14.11.0
Additional tools:

**Comment by evilebottnawi** [comment]
Yep, bug
