### ISSUE TITLE
Requiring library with multiline strings adds tabs

### ISSUE THREAD

**Issue by ckoster22** [webpack/webpack#1161]
In my project I am requiring in a library from node_modules which contains a block of code similar to the following:

``` javascript
var someVariable = 'line1\
line2\
line3\
line4';
```

This is a valid, though not recommended, way to use multiline strings in Javascript. The issue occurs after I bundle my project with WebPack. The output looks something like this:

``` javascript
.. function(module,exports,__webpack_require__){ /* other code */ var someVariable='line1   line2   line3   line4'; ...
```

Tabs are added into the multiline string. I get the same result even when I don't minify/uglify the output. The block of code is indented in the output and the multiline string now has the same tabs prepended to each line:

``` javascript
    var someVariable = 'line1\
    line2\
    line3\
    line4';
```

Is there something I'm doing wrong that multiline strings get their values changed, or is this a bug in WebPack?

**Comment by sokra** [comment]
It's a bug, which is not easy to fix (in a performant way), but you can use the [output.sourcePrefix](http://webpack.github.io/docs/configuration.html#output-sourceprefix) option to disable the tabs...

**Comment by ckoster22** [comment]
Thanks. That did the trick.

**Comment by 4vanger** [comment]
Just run into the same issue. Thanks for the tip with sourcePrefix because I was going to write a plugin to collapse multiline strings into single lined

**Comment by romadenysyuk** [comment]
Hi. Can you please tell exactly how to fix it using output.sourcePrefix?

**Comment by ckoster22** [comment]
The documentation is linked above but basically you'll have an `output` section in your configuration and I set sourcePrefix to an empty string to fix the issue for my project.

```
output: {
        ...
        sourcePrefix: ''
    }
```

**Comment by romadenysyuk** [comment]
Thank you. I tried that. Yes, it fixes the issue with tabs in multiline strings. But there is another issue that I'm trying to solve at the first place. Source maps are not working correctly for minified files that have multiline strings. Chrome shows the console.log as being called from bundled file, not from original js file. Without multiline strings source maps work ok.

**Comment by donaldpipowitch** [comment]
Could `output.sourcePrefix` default to `''`? I was bitten by this recent bitten by this recently. Tabs seem to be to dangerous for ES6 multiline strings.

**Comment by bebraw** [comment]
Can you check this against webpack 2? Note that the ES6 syntax for multiline strings should be supported now.
