### ISSUE TITLE
Hot reloading new file not added to context module

### ISSUE THREAD

**Issue by KyleAMathews** [webpack/webpack#1162]
I'm not entirely sure what I need to do to get this working. When I make a change to files already in a module context, these are hot reloaded just fine, but when I add a new module, Webpack shows in the browser console that a new module id was "modified" and if I look at the webpack cli logging output, I see something like:

`[596] ./pages/2015-05-20---tools-administer-facebook-groups/index.md 1.64 kB {0} [optional] [built]`

But despite accepting the module update successfully and calling require again, this new (optional?) file isn't included in the context module.

What do I need to do?

**Comment by zenlambda** [comment]
I have a similar issue and confusion about what 'optional' means. I can't seem to even manage to hot reload an existing-but-modified file that was loaded in a context module.

**Comment by hakunamatatawang** [comment]
Hello, I am using Gatsby a demo, but i want to deploy to https://*******.github.io/helloworld/, but when i click on the link, directly after the https://********.github.io/ modified URL,this should be https://*******.github.io/helloworld/ later modified, what am i going to do ?

**Comment by KyleAMathews** [comment]
Hi this is the wrong place to ask questions about Gatsby. Please go to
https://github.com/gatsbyjs/gatsby and create an issue there.

**Comment by sokra** [comment]
fixed
