### ISSUE TITLE
webpack5 wepback-cli4.0 internal/modules/cjs/loader.js:883  Error: Cannot find module 'webpack-cli/bin/config-yargs'

### ISSUE THREAD

**Issue by chenjiajing23** [webpack/webpack#11633]
# Bug report

**What is the current behavior?**

```ts
webpack5.0 webapck4.0
internal/modules/cjs/loader.js:883
  throw err;
  ^
Error: Cannot find module 'webpack-cli/bin/config-yargs'
Require stack:

[webpack-cli] 
Error: Universal Chunk Loading is not implemented yet
```
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  5.0.0
Node.js version: 14.13.1
Operating System: mac os 10.15.7
Additional tools: vscode

**Comment by martinoppitz** [comment]
Yes, that does not work anymore.

I think, that webpack-dev-server must do something.

**Comment by chenjiajing23** [comment]
> 是的，这不再起作用。
> 
> 我认为，webpack-dev-server必须做一些事情。

So, what's the solution？

**Comment by AviVahl** [comment]
`webpack-dev-server` has a `next` branch not released yet: https://github.com/webpack/webpack-dev-server/tree/next

**Comment by evilebottnawi** [comment]
Please update webpack-cli to latest stable version and use wbpack serve to run webpack dev server, and we have the same issue in webpack-dev-server repo, release new version will be in near future, please also remove node from browserslist you don’t need universal chunks or change the target option

**Comment by ww028** [comment]
Please tell me how can I solve this problem

**Comment by renjinhui** [comment]
> Please tell me how can I solve this problem

install the webpack-cli@3.x.x

**Comment by chencheng666** [comment]
install the webpack-cli@3.x.x is a good methods,i' ok

**Comment by alexander-akait** [comment]
Please read docs

**Comment by wangshicheng123** [comment]
> Please tell me how can I solve this problem

package.json---> scripts----> "start": "webpack serve"
