### ISSUE TITLE
Troubles using multiple CommonsChunkPlugins

### ISSUE THREAD

**Issue by dfoverdx** [webpack/webpack#1163]
I have a project that contains a module named `Table`.  Until now, it was just another module, but now I need `Table` and its three dependencies to run in a WebWorker, and thus need those four modules in their own file, while still allowing my main bundle.js to load like any other module.

I've tried multiple things, such as adding `table.js` in the array of entries next to `app.js`, adding it as its own entry point, both as a string and as an array, and adding `table.js` and its dependencies to their own entry point.

None of those methods have worked.  The common chunk generates a `table.js` file, but it doesn't have anything in it; `Table` ends up either in bundle.js or vendors.js (the common chunk I've had previously with a bunch of required node modules in it) depending on which CommonChunkPlugin I list first in my `plugins` array.

Could you write an example snippet of a webpack.config.js and also how to import my `Table` module in my other code?

Thanks!

**Comment by bebraw** [comment]
Here is how I would do it:

```javascript
{
  entry: {
    ...
    table: ['dep1', 'dep2', ...]
  },
  plugins: {
    new webpack.optimize.CommonsChunkPlugin(
      'table',
      '[name].[chunkhash].js'
    )
  }
}
```

This is just the basic setup I use for splitting my vendor dependencies. I might be missing something that's needed for your case specifically.

An interesting alternative would be to write a separate configuration altogether (return an array of configurations) that would bundle your `Table` related bits. In that case you could skip `CommonsChunkPlugin` altogether.
