### ISSUE TITLE
Expose 'entryOption' hooks logic in EntryOptionPlugin 

### ISSUE THREAD

**Issue by wood1986** [webpack/webpack#11634]
Is it possbile to expose these logic in

https://github.com/webpack/webpack/blob/37a676810c70f87bb282103ef3e05e2160040e02/lib/EntryOptionPlugin.js#L19-L35

Currently, I have to repeat the exact same logic for my childCompiler because the following code does not perform any compilation.

```js
new EntryOptionPlugin().apply(childCompiler);
childCompiler.hooks.entryOption.call(options.context, options.entry);
```

The reason of not having a compilation is the following
https://github.com/webpack/webpack/blob/37a676810c70f87bb282103ef3e05e2160040e02/lib/Compiler.js#L872-L888

Also see https://github.com/webpack/webpack/issues/9240#issuecomment-507092856

**Comment by evilebottnawi** [comment]
I don’t think it is good idea to expose this, because it can be changed in future, otherwise we need do breaking changes on new features with entry logic, what is the problem?

**Comment by wood1986** [comment]
I do not think there is a difference when dealing with breaking changes. In v4, I was using `MultiEntryPlugin` and it breaks me in v5 without a console message. I know the blog has.

The problem is my plugin will build another bundles for different target from a different entry in the childCompiler. Because of that, I have to `new EntryPlugin` for this entry

**Comment by evilebottnawi** [comment]
In this case my recommendation is to copy/paste code

**Comment by wood1986** [comment]
My point is you can have 2 methods co-exist. One is for v4 and another one is for v5. For example when v4 will be deprecated, you can proxy a deprecated message in v5. I mean it will be good when people want to make their own plugin backward compatible at least for one major version

**Comment by evilebottnawi** [comment]
@wood1986 we already are doing it, but you case is very rare, so we have missed it

**Comment by wood1986** [comment]
Is it worth to do it? I do not mind I do it and I do not mind you reject it or -1.

**Comment by evilebottnawi** [comment]
How would you like to use it? It is part of plugin logic, so `utils` is not best place to put it, maybe static method?

**Comment by wood1986** [comment]
It can be anywhere and I do not have preference. All I need is this method. And yes it can be in the same place with a static method. If so, here is my expectation.

```js
class EntryOptionPlugin {
  ...

  apply(compiler) {
    compiler.hooks.entryOption.tap("EntryOptionPlugin", (context, entry) => INeedAGoodNamePlugin(compiler)
  }
  
  static INeedAGoodNamePlugin(compiler) { return (context, entry) => {
    if (typeof entry === "function") {
        const DynamicEntryPlugin = require("./DynamicEntryPlugin");
        new DynamicEntryPlugin(context, entry).apply(compiler);
      } else {
        const EntryPlugin = require("./EntryPlugin");
        for (const name of Object.keys(entry)) {
          const desc = entry[name];
          const options = EntryOptionPlugin.entryDescriptionToOptions(
            compiler,
            name,
            desc
          );
          for (const entry of desc.import) {
            new EntryPlugin(context, entry, options).apply(compiler);
          }
        }
      }
      return true;
    }
  }

  ...
}

```

In my plugin, I will call it like this
```js
EntryOptionPlugin.INeedAGoodNamePlugin(myChildCompiler)(myContext, myNormalizedEntry)
```

**Comment by evilebottnawi** [comment]
Make sense

/cc @sokra What do you think

**Comment by wood1986** [comment]
#11644 is for v4
#11645 is for v5

Anyway, I created a PR. Feel free to do anything you want
