### ISSUE TITLE
[5.0.0] Persistent cache fails when using the "--config" attribute

### ISSUE THREAD

**Issue by SoerenSilkjaer** [webpack/webpack#11643]
# Bug report

**What is the current behavior?**
When using the --config attribute in the webpack command, while persistent cache is enabled then the following error is thrown: ```[webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Can't resolve '${config.filename}' in '${path.to.dir}'
<w> while resolving '${config.filename}' in ${path.to.dir} as file ```

**If the current behavior is a bug, please provide the steps to reproduce.**
Create a webpack config file with persistent cache enabled and run: `webpack --config ${config.filename}`

**What is the expected behavior?**
That persistent cache finds the config file and stores the cache files to disk.

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

**Comment by evilebottnawi** [comment]
Please read the error message, `webpack --config ${config.filename}` never work, you need to provide path to config, we don't know what is `config.filename`

**Comment by SoerenSilkjaer** [comment]
@evilebottnawi 
I was trying to express that the config filename can be anything. For example the default name: webpack.config.js

**Comment by snitin315** [comment]
@SoerenSilkjaer can you provide a reproducible repo?

**Comment by SoerenSilkjaer** [comment]
@snitin315 

Here is a repo that reproduces the error.

https://github.com/SoerenSilkjaer/webpack5-persistent-cache-bug

To reproduce run: ```npm run webpack```

**Comment by SoerenSilkjaer** [comment]
I believe I have found the issue. The path needs to be relative. 

This does not work: ```webpack --config webpack.config.js```

This works: ```webpack --config ./webpack.config.js```

The reason for the confusion is that it was not needed in webpack 4.

**Comment by snitin315** [comment]
`webpack.config.js` is default so you dont need to pass `--config ./webpack.config.js`. CLI will automatically cosider it for your webpack config.

**Comment by SoerenSilkjaer** [comment]
I know, but that was not the point. I could have named the config file something else. The issue was the way I passed the path into the --config parameter.
