### ISSUE TITLE
Webpack 5: When using a custom configuration, replace name with idHint.

### ISSUE THREAD

**Issue by tomaszs** [webpack/webpack#11648]
According to migration docs: https://webpack.js.org/migrate/5/

"Reconsider optimization.splitChunks:"
"When using a custom configuration, replace name with idHint."

Does it mean that I should change:

```
optimization: {
    splitChunks: {
      chunks: chunk => {
        return chunk.name !== 'specialname';
      },
      name: false,
    },
    runtimeChunk: false,
  },
```

to:

```
optimization: {
    splitChunks: {
      chunks: chunk => {
        return chunk.idHint !== 'specialname';
      },
      idHint: false,
    },
    runtimeChunk: false,
  },
```

?

**Comment by sokra** [comment]
You can just remove that option.

**Comment by tomaszs** [comment]
Thanks for answer @sokra . Does it mean that in this case, the whole "optimization" property can be removed? The code above is all what is there.

**Comment by evilebottnawi** [comment]
> Does it mean that in this case, the whole "optimization" property can be removed?

No

We are updating docs https://github.com/webpack/webpack.js.org/pull/4064

**Comment by tomaszs** [comment]
@evilebottnawi  Thanks for answer. If not, how the config mentioned above should change?

**Comment by evilebottnawi** [comment]
> You can just remove that option.

**Comment by tomaszs** [comment]
@evilebottnawi thanks for answer,

what does **that** mean? 

```
optimization: {
    splitChunks: {
      chunks: chunk => {
        return chunk.name !== 'specialname';
      },
      name: false,
    },
    runtimeChunk: false,
  },

```

```
    runtimeChunk: false, ?
```

or 

```
 splitChunks: {
      chunks: chunk => {
        return chunk.name !== 'specialname';
      },
      name: false,
    },
```

or both? or something else?

**Comment by evilebottnawi** [comment]
I don't know what you want, you don't provide more information, just remove `name: false`

**Comment by tomaszs** [comment]
@evilebottnawi  thanks for answer,

According to the documentation:

"Reconsider optimization.splitChunks:"
"When using a custom configuration, replace name with idHint."

I want to adjust my configuration to follow the recommendation. 
So i have to remove ```      name: false,````,

so this is good?

optimization: {
    splitChunks: {
      chunks: chunk => {
        return chunk.idHint !== 'specialname';
      },
    },
    runtimeChunk: false,
  },

?

**Comment by evilebottnawi** [comment]
@tomaszs I think yes

**Comment by tomaszs** [comment]
@evilebottnawi  thanks
