### ISSUE TITLE
Upgraded to 5 : TypeError: Cannot read property 'tap' of undefined

### ISSUE THREAD

**Issue by joshchernoff** [webpack/webpack#11641]
Versions:
nodejs   14.13.1
npm.      6.14.8
packages: https://github.com/MorphicPro/morphic.pro/blob/upgrade-webpack/assets/package.json

# Bug report

**What is the current behavior?**

Running from zsh on OSX 10.15.6 (19G2021)
```
% node --trace-deprecation node_modules/webpack/bin/webpack.js -v
webpack-cli 4.0.0
webpack 5.0.0

% node --trace-deprecation node_modules/webpack/bin/webpack.js --config webpack.dev.config.js
[webpack-cli]
TypeError: Cannot read property 'tap' of undefined
```
here is the config in question. 
https://github.com/MorphicPro/morphic.pro/blob/upgrade-webpack/assets/webpack.dev.config.js

**If the current behavior is a bug, please provide the steps to reproduce.**
It looks to be falling hard and fast with just the stdout shown above. 

**What is the expected behavior?**
I'd like to discover what is calling tap on undefined

**Comment by evilebottnawi** [comment]
Bug on `HardSourceWebpackPlugin` side, please report them, but I think you don't need `HardSourceWebpackPlugin` anymore, webpack has `cache` out of box https://webpack.js.org/configuration/other-options/#cache
