### ISSUE TITLE
Error: NormalModuleFactory.afterResolve is no longer a waterfall hook, but a bailing hook instead.

### ISSUE THREAD

**Issue by creage** [webpack/webpack#11647]
# Bug report

**What is the current behavior?**
Webpack build crashes with error 
`Error: NormalModuleFactory.afterResolve is no longer a waterfall hook, but a bailing hook instead. Do not return the passed object, but modify it instead. Returning false will ignore the request and results in no module created.`

**If the current behavior is a bug, please provide the steps to reproduce.**
Follow `NormalModuleReplacementPlugin` [usage guide](https://webpack.js.org/plugins/normal-module-replacement-plugin/)
```js
module.exports = function(env) {
  var appTarget = env.APP_TARGET || 'VERSION_A';
  return {
    plugins: [
      new webpack.NormalModuleReplacementPlugin(/(.*)-APP_TARGET(\.*)/, function(resource) {
        resource.request = resource.request.replace(/-APP_TARGET/, `-${appTarget}`);
      })
    ]
  };
};
```

**What is the expected behavior?**
It should build as before

**Other relevant information:**
webpack version:  5.0.0
Node.js version: v14.9.0
Operating System: Windows 10
Additional tools: -

**Comment by sokra** [comment]
Could you check if you have mulitple webpack versions installed? `yarn why webpack` `npm ls webpack`

**Comment by creage** [comment]
No, I don't. I've removed previous `node_modules` completely before doing upgrade. But I'm running `lerna` if this might help. So, all of my deps are hoisted to the root folder.

**Comment by evilebottnawi** [comment]
@creage Sorry without additional information we can't help

**Comment by creage** [comment]
@evilebottnawi I'm ready to provide with whatever info you need. If you really need the output of `npm ls webpack` - here you go:

```
npm ls webpack
-- UNMET PEER DEPENDENCY webpack@5.0.0

npm ERR! peer dep missing: webpack@^2.0.0 || ^3.0.0 || ^4.0.0, required by lodash-webpack-plugin@0.11.5
npm ERR! peer dep missing: webpack@^1.0.0 || ^2.0.0 || ^3.0.0 || ^4.0.0, required by script-ext-html-webpack-plugin@2.1.4
```

**Comment by evilebottnawi** [comment]
You need to open issue in `lodash-webpack-plugin` and `script-ext-html-webpack-plugin` repos

> Could these plugins cause the error I receive?

yes

https://github.com/lodash/lodash-webpack-plugin/blob/master/src/index.js#L41

Sorry, we can't fix it on our side, my recommendation is avoid using `lodash-webpack-plugin`, just rewrite your code on `import { something } from 'lodash';`
