### ISSUE TITLE
Webpack not able to handle runtime require emitted from wasm-bindgen

### ISSUE THREAD

**Issue by b-m-f** [webpack/webpack#11640]
# Bug report

**What is the current behavior?**
For my project I am using [wasm-bindgen](https://github.com/rustwasm/wasm-bindgen) to compile Rust to wasm.

My Rust crate depends on [rand](https://github.com/rust-random/rand) which will call different RNG backends depending on which plattform it is running on.

In the browser everything works fine. 

Using the the same setup but with `target: node` fails with ` Error: Cannot find module 'crypto'`.

Someone else is affected by the same problem -> https://github.com/rustwasm/wasm-bindgen/issues/2323

# Trace

The error happens here:

__Unminified chunk from the bundle__
```
const __wbg_require_604837428532a733 = function(arg0, arg1) {
>>> var ret = __webpack_require__(6867)(getStringFromWasm0(arg0, arg1));
    return addHeapObject(ret);
};

```

Here is the original code before bundling:

```
export const __wbg_require_604837428532a733 = function(arg0, arg1) {
    var ret = require(getStringFromWasm0(arg0, arg1));
    return addHeapObject(ret);
};

```

Here is 6867:

```


/***/ 6867:
/***/ ((module) => {

function webpackEmptyContext(req) {
        var e = new Error("Cannot find module '" + req + "'");
        e.code = 'MODULE_NOT_FOUND';
        throw e;
}
webpackEmptyContext.keys = () => [];
webpackEmptyContext.resolve = webpackEmptyContext;
webpackEmptyContext.id = 6867;
module.exports = webpackEmptyContext;

/*** /})

```

`getStringFromWasm0(arg0, arg1)` only resolves to `crypto` during runtime when the **WASM** needs to use an RNG backend.

 Webpack should somehow be aware to stay away from this, or add an option to keep original syntax in place if no module could be found during bundletime.
 
 

**What is the expected behavior?**

The bundle should be able to work without error, `require`ing `crypto` when needed.

**Other relevant information:**
webpack version:  5.0.0
Node.js version: 14
Operating System:  Arch
Additional tools: wasm-bindgen@0.2.68, rand@0.7.3

I am happy to provide more information or test ideas.

**Comment by b-m-f** [comment]
Thats rude @webpack-bot

**Comment by b-m-f** [comment]
Still relevant

**Comment by b-m-f** [comment]
Dont know if this is fixed. Can restest next week

**Comment by vankop** [comment]
hm... not sure what you expect.. there is `require(getStringFromWasm0(arg0, arg1))` that webpack can't statically analyze

**Comment by vankop** [comment]
maybe you want to ignore this require so you need  comments like `/* webpackIgnore: true */`
