### ISSUE TITLE
Webpack 5 dynamic imports with webpackChunkName specified do not load in browser

### ISSUE THREAD

**Issue by tarponjargon** [webpack/webpack#11658]
# Bug report

**What is the current behavior?**

Just upgraded from 4 to 5 and am having a problem getting named chunks to load in the browser (both development and production).  Example.

```
import(
	/* webpackPrefetch: true */
	/* webpackChunkName: "detail" */
	"./js/views/DetailView"
).then(DetailView => {
	viewInit = new DetailView.default();
	viewInit.init(view).then(() => resolve(view));
});
```

The chunks themselves get created with the specified (correct) name:

```/assets/detail.e91defe850779a8dd88f.js```

But they just don't load in the browser.  No error in the console.  However, if I remove:

```/* webpackChunkName: "detail" */```

Then the chunks do load in the browser as they should.

I am giving the chunks specific names because I have a custom plugin that is handling assignment of resource hints for my platform, based on the filenames in compilation.chunks[] ... chunk.files array (or set)

**If the current behavior is a bug, please provide the steps to reproduce.**

not sure how to, but here's my config optimization hash:

```
optimization: {
	minimize: true,
},
```

I don't have a babelrc that 's stripping comments or anything.  The chunks were named and loaded fine in wp4.  Though there may be something important I'm not understanding about webpackChunkName in web5.

**What is the expected behavior?**

dynamic imports named with webpackChunkName retain their specified name and load dynamically in the browser.

**Other relevant information:**
webpack version:  5.0.0
Node.js version: v14.8.0
Operating System: OS X
Additional tools:

**Comment by tarponjargon** [comment]
Nevermind - the issue is with my custom plugin, not webpack.

**Comment by m4wjw** [comment]
Have you resolved it? I meet it too with wp5
