### ISSUE TITLE
Webpack loads 2 versions of backbone instead of 1

### ISSUE THREAD

**Issue by Woutvdvegt** [webpack/webpack#1165]
When I have a structure like this:
```
├─┬ node_modules
│ ├── backbone@1.2.1
│ ├─┬ backbone.marionette@2.4.1  
│ │ └─┬ node_modules
│ │   ├── backbone@1.1.2
│ │   └── backbone.babysitter@0.1.7
│ └── backbone.babysitter@0.1.7
└── app.js
```

And load these modules in my app.js like this:
```javascript
import Backbone from "backbone";
import Marionette from "backbone.marionette";
import "backbone.babysitter";
```

Now when I watch in dev tools at the sources tab, it show that the page has loaded 2 backbones and 2 backbone.babysitters. First the self defined versions, and secondly the dependencies of Marionette:

![webpack-sources](http://s13.postimg.org/d1yavbzyv/webpack_sources.png)

How can I ensure that webpack provides the self defined packages to Marionette?

**Comment by SimenB** [comment]
Did you try `npm dedupe`? Doesn't help with webpack directly, but it might remove some duplicated deps

**Comment by taurose** [comment]
[This workaround](https://github.com/webpack/webpack/issues/777#issuecomment-73615754) seems to work well. You probably have to careful about version conflicts though.

```js
module.exports = {
  resolve: {
    alias: {
      'backbone': require.resolve('backbone')
    }
  }
}
```

**Comment by akre54** [comment]
Try running `npm dedupe` and [DedupePlugin](http://webpack.github.io/docs/list-of-plugins.html#dedupeplugin).

**Comment by Woutvdvegt** [comment]
@taurose thank you, thats what I needed

**Comment by shama** [comment]
This issue can be closed now right @sokra?
