### ISSUE TITLE
Type defs CssMinimizerPlugin and TerserWebpackPlugin with webpack 5

### ISSUE THREAD

**Issue by blephy** [webpack/webpack#11656]
I'm getting this error with webpack 5 when trying to override minimizer config property : 

```ts
/** Webpack config */
...
minimize: true,
minimizer: [
      new TerserPlugin({
        cache: true,
        parallel: true,
        sourceMap: false,
        extractComments: false,
        terserOptions: {
          output: {
            comments: false
          }
        }
      }),
      new CssMinimizerPlugin({
        sourceMap: false,
        minimizerOptions: {
          preset: [
            'default',
            {
              discardComments: { removeAll: true }
            }
          ]
        }
      })
    ],
...
```

> Type 'TerserPlugin' is not assignable to type '((this: Compiler, compiler: Compiler) => void) | WebpackPluginInstance | "..."'. Type 'TerserPlugin' is not assignable to type '"..."'.

> Type 'CssMinimizerPlugin' is not assignable to type '((this: Compiler, compiler: Compiler) => void) | WebpackPluginInstance | "..."'. Type 'CssMinimizerPlugin' is not assignable to type '"..."'.

When i try to use spread operator as showed in the migration guide, i'm getting this error : 

> Type 'TerserPlugin' must have a '[Symbol.iterator]()' method that returns an iterator.

> Type 'CssMinimizerPlugin' must have a '[Symbol.iterator]()' method that returns an iterator

**Other relevant information:**
webpack version: 5
Node.js version: 12.19.0
Operating System: MacOS Catalina 10.15.5
TypeScript: 4.0.3

**Comment by evilebottnawi** [comment]
Not related to webpack

**Comment by evilebottnawi** [comment]
`TerserPlugin` and `CssMinimizerPlugin` doesn't have types right now

**Comment by evilebottnawi** [comment]
Use `ts-ignore`

**Comment by blephy** [comment]
Ok sorry
