### ISSUE TITLE
[webpack 5]Switch to on/off ESM usage info log in chunks.

### ISSUE THREAD

**Issue by ZKHelloworld** [webpack/webpack#11667]
## Feature request
Seems like webpack 5 generate ESM usage info in chunks for the sake of tree-shaking and that's awesome!
But it may takes up too much bytes in dev mode.

We are actively working on a long-term monorepo(over 1 million lines of code). After switch to webpack 5, the prod mode chunks are slightly smaller than webpack 4. But the dev mode chunks are almost **40M** bigger.

Size built on webpack 4:
![image](https://user-images.githubusercontent.com/6254209/95845318-9ad9c180-0d7c-11eb-8347-935cf82feb08.png)
Size built on webpack 5:
![image](https://user-images.githubusercontent.com/6254209/95845361-a4fbc000-0d7c-11eb-819f-1266feffd66c.png)

And most of the incremental bytes are these logs:
![image](https://user-images.githubusercontent.com/6254209/95845668-0d4aa180-0d7d-11eb-874a-98aea9eddbf5.png)

Is it necessary to add a config that can manually switch on/off the tree-shaking feature or ESM usage info in dev mode? Or am i missing something that will do the same?

**What is the expected behavior?**
It's available to switch off ESM usage info in dev mode.

**What is motivation or use case for adding/changing the behavior?**
Smaller chunks means faster load time and greater development experience.

**How should this be implemented in your opinion?**
A switch to on/off the tree-shaking feature or ESM usage info in dev mode.

**Are you willing to work on this yourself?**
yes

**Comment by evilebottnawi** [comment]
Please use `terser-webpack-plugin` to remove comments or you can disable all `optimization` https://github.com/webpack/webpack/blob/master/lib/config/defaults.js#L833

**Comment by sokra** [comment]
> A switch to on/off the tree-shaking feature or ESM usage info in dev mode.

`output.pathinfo: false` disables the info comments.
