### ISSUE TITLE
terminal errors when using webpack with sequelize

### ISSUE THREAD

**Issue by Pomax** [webpack/webpack#1166]
I was working on a project where I needed a quick DB interface, so I hit up `npm install sequelize --save` and `npm install mysql --save` and then reran my webpack build, only for webpack to rather spectacularly die on this new library:

![screenshot 28](https://cloud.githubusercontent.com/assets/177243/8150406/e6b7b426-129c-11e5-944b-4479862f505e.png)

Simply having `var Sequelize = require('sequelize');` in my code triggers this rather weird error, and prevents webpack from actually building all the files.

**Comment by sokra** [comment]
The problem is [a dynamic require](https://github.com/sequelize/sequelize/blob/master/lib/dialects/mysql/connection-manager.js#L15) (`this.lib = require(sequelize.config.dialectModulePath || 'mysql');`) which cannot be statically analysed. You could address it with the `ContextReplacementPlugin`.

**Comment by Pomax** [comment]
That explanation is exceedingly worth putting in the error reporting, so that it's obvious why everything is going wrong

**Comment by Boelensman1** [comment]
Can you give me an example how I should use the ContextReplacementPlugin in this case? I am having the same problem.

**Comment by Pomax** [comment]
@Boelensman1 worth asking in a new issue, since that's a new problem you're having, not a problem directly related to the dynamic require in relation to sequelize

**Comment by Boelensman1** [comment]
I don't really get what you mean. I have the same errors as you have with, probably, the same cause. I am also trying to use sequelize in combination with webpack.

**Comment by Pomax** [comment]
oops, sorry, misread your question, comment deleted.

**Comment by arunasSlenderis** [comment]
I have the same issue too. I don't know how to remove sequelize from bundling with webpack. Maybe You can give some advice? thank you
