### ISSUE TITLE
Webpack 5 typescript tslib is not resolved when importHelpers set to true

### ISSUE THREAD

**Issue by SPWizard01** [webpack/webpack#11666]
# Bug report

**What is the current behavior?**
tsconfig.json:
```
{
	"compilerOptions": {
		"module": "esnext",
		"sourceMap": true,
		"target": "es5",
		"esModuleInterop": true,
		"moduleResolution": "node",
		"importHelpers": true,
		"jsx": "react",
		"allowJs": false
	},
	"compileOnSave": false,
	"exclude": [
		"node_modules"
	]
}
```

results in:
`Uncaught (in promise) TypeError: Cannot destructure property '__extends' of '_tslib_js__WEBPACK_IMPORTED_MODULE_0___default(...)' as it is undefined.`

also this is a problem if you have a library that depends on tslib i.e. `pnpjs` and just import that library

workaround:
```
    alias: {
      tslib: resolve(__dirname, "./node_modules/tslib/tslib.es6.js"),
    },
```

i am not sure if this is a bug or works as intended

**If the current behavior is a bug, please provide the steps to reproduce.**

general configuration of typescript + ts-node + webpack will produce this error if having importHelpers set to true

**What is the expected behavior?**
it should resolve? at least in Webpack 4 it does

**Other relevant information:**
webpack version:  5.0.0
Node.js version: v12.18.0
Operating System: Window 10
Additional tools:
typescript@latest
ts-node@latest

**Comment by evilebottnawi** [comment]
Update tslib to latest version

**Comment by Delagen** [comment]
2.0.3 the same problem caused exports field in package.json. Latest working version 2.0.1

**Comment by evilebottnawi** [comment]
@Delagen why do you use `alias`? Please create reproducible repo

**Comment by evilebottnawi** [comment]
https://github.com/microsoft/tslib/pull/129
