### ISSUE TITLE
Tree-shaking not work

### ISSUE THREAD

**Issue by NE-SmallTown** [webpack/webpack#11665]
# Bug report

**What is the current behavior?**
The Tree-shaking not work

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/NE-SmallTown/webpack-tree-shaking-bug-repro

**What is the expected behavior?**

You can do following steps to reproduce this problem:

1. clone the repo above
2. go to `node_modules` and find `@hyext/hy-ui` and then add `"sideEffects": false,` in `@hyext/hy-ui/package.json`
3. run `npm run build` in the project root path

The output will be in `/dist`, you will find that the Tree-shaking not works. As specific:

1. The `/dist/index_web.chunk.js` has **both** `funcA` and `funcB` code(It should only have `funcB` because I don't use `funcA` anywhere)

2. The `/dist/index_web.chunk.js` has `src/app.hycss` code which is **not** correct too, because in the project package.json I have set `"sideEffects": false` **rather than** `"sideEffects": ['**/*.hycss']`

3. The `/dist/vendors.chunk.js` has **all** `@hyext/hy-ui` code, and there are many images in `/dist` related about  `@hyext/hy-ui`. **But** I just `import { UI } from '@hyext/hy-ui'` and just use `const { View, Text } = UI`, it should only have the related code about `View` and `Text`

4. The `/dist/vendors.chunk.js`  has **all** `react-native-web` code(import `react-native` will finally be import `react-native-web` due to `babel-plugin-react-native-web`), but the only module which import `react-native` is `@hyext/hy-ui`, and it always use the `import { xxx } from 'react-native'` format, so it's not correct too(it should only have the related code about `react-native-web`)

## Other information maybe helpful

1. Althouh I have add `--display-used-exports` when run webpack, but there is no output about that when you do `npm run build`, I find that the `module.usedExports` https://github.com/webpack/webpack/blob/2efeb4b5787e868e69233aa9dec469c200fa3b2c/lib/Stats.js#L1202 is always `true` rather than an `Array` or `false`(I dont know why), so it would output nothing

2. The [`dep`](https://github.com/webpack/webpack/blob/2efeb4b5787e868e69233aa9dec469c200fa3b2c/lib/optimize/SideEffectsFlagPlugin.js#L144) will always be neither `HarmonyImportSideEffectDependency` nor `HarmonyExportImportedSpecifierDependency`(actully, it's `CommonJsRequireDependency` (I dont know why too)), so we cant reach the `sideEffectFree` branch 

**Other relevant information:**
webpack version:  4.44.2
Node.js version: 10.19.0
Operating System: Windows10 WSL2
Additional tools: no

**Comment by evilebottnawi** [comment]
Problems with the `sideEffects` options, it is wrong...

**Comment by NE-SmallTown** [comment]
Sorry, I figure it out, the problem is all modules be transformed to commonjs so they cant be tree-shaken, https://github.com/facebook/metro/pull/203

The problem 2 described above is because `babel-plugin-transform-jsx-to-hy-stylesheet` will use the default `export` of `./app.hycss`, so it will not be tree-shaken

**Comment by NE-SmallTown** [comment]
> Problems with the sideEffects options, it is wrong... 

I dont know what you means, could you share more details?

**Comment by NE-SmallTown** [comment]
The problem 3 is still not ok, but that's fine, it's related to https://github.com/webpack/webpack/issues/8057
