### ISSUE TITLE
v5: [webpack-cli] TypeError: compiler.plugin is not a function

### ISSUE THREAD

**Issue by budarin** [webpack/webpack#11672]
# Bug report

**What is the current behavior?**
Made all suggestions for v4->v5
try to run dev configuration with `webpack serve` and got the error

**If the current behavior is a bug, please provide the steps to reproduce.**
yes

**What is the expected behavior?**
successful build 

**Other relevant information:**
webpack version:  5.1.0
Node.js version: 14.4.0
Operating System: any
Additional tools: 

Where to look and what to watch?
[webpack config](https://gist.github.com/budarin/4a13ff560f286875d729f1648a7dd44b)

**Comment by evilebottnawi** [comment]
Not related to webpack, report it to the plugin repo

**Comment by evilebottnawi** [comment]
Use path.resolve, you are on windows

**Comment by budarin** [comment]
@evilebottnawi 

Thanks!

**Comment by Rabbitzzc** [comment]
> Not related to webpack, report it to the plugin repo, `compiler.plugin` api was removed in webpack@5

What property should I use instead？

**Comment by Sir-hennihau** [comment]
I'm also looking for the correct replacement for `compiler.plugin`, anybody has some hints?

**Comment by ericatallah** [comment]
> I'm also looking for the correct replacement for `compiler.plugin`, anybody has some hints?

Maybe try: `compiler.hooks.done.tap`

**Comment by nrd26** [comment]
Hi,
Weirdly enough, I'm getting this error even though I haven't configured compiler.plugin anywhere in my project. Any clue as to what the source of the error could be?

**Comment by dakur** [comment]
@nrd26 It's not about `compiler.plugin` in your project, but in source code of webpack plugin. Investigate which plugin causes it, you should see it on the very next line below the `compiler.plugin is not a function`.

**Comment by klm-lab** [comment]
> > I'm also looking for the correct replacement for `compiler.plugin`, anybody has some hints?
> 
> Maybe try: `compiler.hooks.done.tap`

HI, we never know. So i end up with @ericatallah solution with some adjustements when using **"dts-bundle"** plugin. I go from

```js
DtsBundlePlugin.prototype.apply = function (compiler) {
// TypeError here: compiler.plugin is not a function
  compiler.plugin('done', function(){
    .......
  });
};
```
to 

```js
DtsBundlePlugin.prototype.apply = function (compiler) {
// Applying @ericatallah solution
  compiler.hooks.done.tap({name: "dts-bundle"}, function(){
    .......
  });
};
```

**Comment by klm-lab** [comment]
> > > I'm also looking for the correct replacement for `compiler.plugin`, anybody has some hints?
> > 
> > 
> > Maybe try: `compiler.hooks.done.tap`
> 
> HI, we never know. So i end up with @ericatallah solution with some adjustements when using **"dts-bundle"** plugin. I go from
> 
> ```js
> DtsBundlePlugin.prototype.apply = function (compiler) {
> // TypeError here: compiler.plugin is not a function
>   compiler.plugin('done', function(){
>     .......
>   });
> };
> ```
> 
> to
> 
> ```js
> DtsBundlePlugin.prototype.apply = function (compiler) {
> // Applying @ericatallah solution
>   compiler.hooks.done.tap({name: "dts-bundle"}, function(){
>     .......
>   });
> };
> ```

@Rabbitzzc @Sir-hennihau
