### ISSUE TITLE
Webpack 5 prod build performance?

### ISSUE THREAD

**Issue by pavelloz** [webpack/webpack#11674]
What are benchmarks saying about perf vs v4 in prod mode?

I just tried to migrate and failed because app stopped working, but building time got me worried.
On cold cache was 4x higher than v4 on cold,
On hot cache it was 2.5x-3x higher than v4 on hot.

Maybe prod mode isnt priority, but i just liked having builds done quickly.

**Comment by TheLarkInn** [comment]
Thanks for the report. Do you think you can provide some more actionable details/examples that we could work with or profile. Examples of profiles might look like [this article](https://daniellockyer.com/profiling-nodejs/). We definitely focus on dev mode for faster builds however we're still interested in regressions from 4=>5.

**Comment by pavelloz** [comment]
Sure thing, I will look into proper benchmarking it soon, as the migration is pretty easy.

Meanwhile I wanted to ask if anybody else observed it - I remember having issues with my env and not being able to reproduce the issue on any other machine, I dont rule that out. Just trying to be careful :)

**Comment by jrnail23** [comment]
@pavelloz, you're not crazy.  I'm also experiencing slow initial build times.  Rebuilds (using persistent cache) are ridiculously fast though!

**Comment by pavelloz** [comment]
Thats a good news. :)
At the end of the day, production builds are done less than dev builds, so this is probably where priority should lie. Im just pedantic that way to try to optimize even prod builds :)

Ok, i tried to use article advice, but couldnt force 0x to measure webpack-cli command.
So i tried to use SMP plugin, but v5 is not compatible with it.
But just by spamming build in my console it is at around 2x slower.

v4 with SMP (even though the measuring plugin can add its own overhead, which is a pretty common issue with benchmarking) warm cache:
<details>
nearme-documentation|master⚡ ⇒ MEASURE=true NODE_ENV=production webpack-cli
(node:16047) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
(Use `node --trace-deprecation ...` to show where the warning was created)


 SMP  ⏱  
General output time took 5.38 secs

 SMP  ⏱  Plugins
TerserPlugin took 0.167 secs
MiniCssExtractPlugin took 0.001 secs
WebpackRequireFrom took 0.001 secs

 SMP  ⏱  Loaders
mini-css-extract-plugin, and 
css-loader, and 
postcss-loader took 4.63 secs
  module count = 3
css-loader, and 
postcss-loader took 4.58 secs
  module count = 3
babel-loader took 2.18 secs
  module count = 103



Version: webpack 4.44.1
Time: 5384ms
Built at: 10/13/2020 11:25:02 PM
                    Asset      Size  Chunks                         Chunk Names
            search.726.js   114 KiB       2  [emitted] [immutable]  search
syntaxHighlighting.d66.js  44.7 KiB       3  [emitted] [immutable]  syntaxHighlighting
                  app.css  24.4 KiB       0  [emitted]              app
               search.css  18.4 KiB       2  [emitted]              search
                   app.js  6.59 KiB       0  [emitted]              app
               graphql.js  2.98 KiB       1  [emitted]              graphql
              graphql.css  2.49 KiB       1  [emitted]              graphql
Entrypoint app = app.css app.js (prefetch: search.css search.726.js)
Entrypoint graphql = graphql.css graphql.js
</details>

v5 hot cache
<details>
nearme-documentation|after⚡ ⇒ MEASURE=true NODE_ENV=production webpack-cli
(node:16435) [DEP_WEBPACK_MAIN_TEMPLATE_GET_PUBLIC_PATH] DeprecationWarning: MainTemplate.getPublicPath is deprecated (use Compilation.getAssetPath(compilation.outputOptions.publicPath, options) instead)
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:16435) [DEP_WEBPACK_MAIN_TEMPLATE_REQUIRE_FN] DeprecationWarning: MainTemplate.requireFn is deprecated (use "__webpack_require__")
assets by status 158 KiB [cached] 4 assets
assets by path . 55.3 KiB
  assets by path *.css 45.3 KiB
    asset app.css 24.4 KiB [compared for emit] (name: app)
    asset search.css 18.4 KiB [compared for emit] (name: search)
    asset graphql.css 2.49 KiB [compared for emit] (name: graphql)
  assets by path *.js 10 KiB
    asset app.js 7.56 KiB [compared for emit] [minimized] (name: app)
    asset graphql.js 2.47 KiB [compared for emit] [minimized] (name: graphql)
Entrypoint app 32 KiB = app.css 24.4 KiB app.js 7.56 KiB
Entrypoint graphql 4.96 KiB = graphql.css 2.49 KiB graphql.js 2.47 KiB
webpack 5.1.0 compiled successfully in 9633 ms
</details>

**Comment by pavelloz** [comment]
PS. I guess esbuild author already did some comparisons with less dramatic numbers: https://github.com/evanw/esbuild#javascript-benchmark

**Comment by sokra** [comment]
An easy way to get a simple performance profile is `--progress --profile`. There are more hints in the migration guide.

**Comment by sokra** [comment]
> TerserPlugin took 0.167 secs

I guess you have minimizing cached in this build...

**Comment by evilebottnawi** [comment]
@pavelloz Can you create reproducible test repo, esbuild created pretty focused tests, likely it is not your performance problem

> (node:16047) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

You have old plugin, maybe problem with it

**Comment by pavelloz** [comment]
@evilebottnawi https://github.com/mdyd-dev/platformos-documentation/tree/after

A little bit more than JUST webpack has been upgraded, but its the most realistic upgrade I could do :)

Comparison to v4 version: https://github.com/mdyd-dev/platformos-documentation/compare/after?expand=1


@sokra Thank you, ill prepare some more systematic benchmark with proper cleans :)

**Comment by evilebottnawi** [comment]
@pavelloz What is you version of `postcss-loader` and PostCSS?

**Comment by evilebottnawi** [comment]
Most of the time was spent on postcss, so I think we need to see what's wrong

**Comment by pavelloz** [comment]
Well, yes, because there is very little JS in the project, and tailwindcss is a postcss plugin, so thats where the time goes.

Versions are: PostCSS 8.1.2, postcss-loader 4.0.4

I think i need to wait for the same performance tracking plugin to work on both versions to compare and detect more. Right now i jus see that its around 2x slower but dont know if thats webpack or not, because a lot of loaders/plugins had to be upgraded to work with 5.x. And as you said, maybe postcss development will fix this issue.

**Comment by evilebottnawi** [comment]
@pavelloz Can you create reproducible example and I will help, otherwise we will close issue, because we can't solve something somewhere

**Comment by pavelloz** [comment]
https://github.com/webpack/webpack/issues/11674#issuecomment-708332516

I wont prepare more.

**Comment by evilebottnawi** [comment]
@pavelloz Can you try to update `TerserPlugin` to latest? We fix some perf issues
