### ISSUE TITLE
Watcher issue on Window's short paths like C:\PROGRA~1\

### ISSUE THREAD

**Issue by piotr-oles** [webpack/webpack#11679]
# Bug report

**What is the current behavior?**
I'm an author of the fork-ts-checker-webpack-plugin and I noticed that behavior in my recent PR: https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/pull/516/files.

When I navigate to a path using MS-DOS compatible path (for example temp directory on GitHub Actions on Windows image - `C:\Users\RUNNER~1\AppData\Local\Temp\`), and I add a directory to the `compilation.contextDependencies` (for example `C:\Users\RUNNER~1\AppData\Local\Temp\my-app\src`), webpack will trigger unnecessary rebuilds. I checked `compiler.modifiedFiles` and `compiler.removedFiles` and they randomly contain `C:\Users\RUNNER~1\AppData\Local\Temp\my-app\src` directory (which shouldn't be the case - there should be only files). 

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Copy webpack project to `C:\Program Files\my-app`
2. Add a hook that will add `path.join(process.cwd, 'src')` to `compilation.contextDependencies`
3. Run webpack in a watch mode with CWD = `C:\PROGRA~1\my-app`
4. Add/update/delete some files in `C:\Program Files\my-app\src` and debug `compiler.modifiedFiles` and `compiler.removedFiles` Set

**What is the expected behavior?**
As in webpack 4, the watcher should not trigger unnecessary rebuild and report directory as changed or removed file.

**Other relevant information:**
webpack version:  5.1.0
Node.js version: 10
Operating System: Windows 10
Additional tools:

**Comment by sokra** [comment]
I don't understand the problem. If you add `src` as `contextDependency` it will report `src` as changed once anything in `src` changes. And this also triggers a rebuild.
`modifiedFiles` will only list entries of `fileDependencies` or `contextDependencies`. It will not list the file changed if this is not a direct dependency.

**Comment by piotr-oles** [comment]
I would expect that `modifiedFiles` and `removedFiles` contains a list of files - not directories. And that's the case on Linux, Mac, and Windows with normal paths, but not on Windows with MS-DOS compatible paths.

**Comment by evilebottnawi** [comment]
@piotr-oles how it is related to chokidar?

**Comment by piotr-oles** [comment]
@evilebottnawi I didn't notice such an issue with webpack 4 which AFAIK uses chokidar as a low-level watching library. But I don't know if that's the source of the issue.

**Comment by evilebottnawi** [comment]
@piotr-oles 

> modifiedFiles will only list entries of fileDependencies or contextDependencies.

Expected, what do you want?

**Comment by piotr-oles** [comment]
As I said above, it works differently on Linux and Mac OS. If it's expected, then the name ’modifiedFiles’ is misleading :)

**Comment by evilebottnawi** [comment]
@piotr-oles What is work differently? Yes, it is some misleading

**Comment by sokra** [comment]
But I really noticied a small difference when using 6+3 names. It reports `C:\PROGRA~1` as removed as it wasn't able to find the folder with readdir...

**Comment by piotr-oles** [comment]
Yes, there is something off with 8.3 names. I resolved an 8.3 path using `fs.resolveSync.native` in my tests as a CWD for the spawned webpack process and now they pass :)

**Comment by evilebottnawi** [comment]
@piotr-oles so we can close it?

**Comment by piotr-oles** [comment]
It's up to you. The problem still exists, but I was able to do a workaround :)

**Comment by evilebottnawi** [comment]
@piotr-oles please describe what you expected, because 

> As I said above, it works differently on Linux and Mac OS

It should not do that.

**Comment by sokra** [comment]
> I resolved an 8.3 path using `fs.resolveSync.native` in my tests

How did you do that exactly? I wasn't able to find `fs.resolveSync.native`?

**Comment by sokra** [comment]
ah it's `fs.realpathSync.native`

**Comment by piotr-oles** [comment]
Yep, sorry for the wrong function :)

**Comment by alexander-akait** [comment]
still valid

**Comment by alexander-akait** [comment]
bump
