### ISSUE TITLE
terminal errors when using webpack with mysql

### ISSUE THREAD

**Issue by Pomax** [webpack/webpack#1167]
Trying to use Webpack with the `mysql` package results in webpack doing very curious things that cause it to terminate:

![screenshot 29](https://cloud.githubusercontent.com/assets/177243/8150434/bce6f4d4-129e-11e5-895d-1dfdd9d74442.png)

**Comment by sokra** [comment]
`require-all` is not supported by webpack, because it's not statically analysable.

This could be addressed by the `mysql` package author, but I think the `mysql` package would still not be browser-compatible.

**Comment by Pomax** [comment]
If possible, seeing that reason reflected in the error/warns would be quite welcome, so that users understand why things are going wrong and have agency to figure out ways around it, rather than not understanding what's really going wrong.

**Comment by shama** [comment]
@Pomax There is going to be a good deal of modules that will not run in a browser, `mysql` is one of them. As certain operations don't have a functional equivalent in the browser, `net`, `tls` and `fs` which are typically provided by Node.js on the server and which the error above indicates: Cannot resolve module.

**Comment by Pomax** [comment]
right, so: it would be a great idea to make sure that webpack generates a useful error in these cases, instead of saying "critical dependencies" and "unknown token". Those are not the kinds of error that let users figure out what's wrong so they can fix the problem themselves.

**Comment by shama** [comment]
@Pomax What error messages would you suggest? Keeping in mind, webpack only knows it cannot resolve the module or the module you're trying to load isn't valid JS.

It doesn't know that the module you're trying to load isn't web compatible. I think it is a fairly safe assumption that a developer using `mysql` should know that MySQL does not run in a web browser and it's not webpack's responsibility to inform users of that.

**Comment by Pomax** [comment]
Hm, those are two different errors.

1. "cannot resolve module" error when the module doesn't resolve makes sense,
2."invalid JS encountered for bundling: [module name] - server-side/binary modules are not supported" when it hits JS that relies on binaries or non-browsers APIs?

**Comment by shama** [comment]
> "invalid JS encountered for bundling: [module name] - server-side/binary modules are not supported" when it hits JS that relies on binaries or non-browsers APIs?

Currently when it hits invalid JS the error says: "You may need an appropriate loader to handle this file type". As it is possible to load non-JS files, you just need an appropriate loader that can convert the file to valid JS. Such as one could `readmeContents = require('md-loader!./readme.md')`.

So we can't assume any invalid JS the user is trying to load is a server-side/binary module that isn't supported.

**Comment by Pomax** [comment]
We actually totally can: those loaders need to kick in for require calls with an extension that is not `.js`, as requires without extensions and requires ending in `.js` are plain module imports. So it should be entirely possible to throw one kind of error when the js branch (implicit or not) goes wrong, and the "you need a loader" error for when the "with-extenion" branch goes wrong.

**Comment by shama** [comment]
Loaders are not based upon the file extension. I can do `require('md-loader!./readme.js')` or `require('md-loader!./readme')`.

In addition, there are shorthands [omitting the file extension](http://webpack.github.io/docs/configuration.html#resolve-extensions) and third party modules do not use file extensions `require('some-package')`.

As well as the user can also set a loader based upon their own regex (not the file extension):

```js
module: {
  loaders: [
    { test: /matchThisRegex/, loader: 'md-loader' }
  ]
}
```

So all webpack can do is try and load the module then throw when it fails to parse.

**Comment by Pomax** [comment]
right, but this error is cropping up for regular requires, so it doesn't make a lot of sense to use loaders as a reason *not* to add a more specific error during parse runs where this *can* be detected. Full solution? No. Better solution than now? Most definitely.

**Comment by shama** [comment]
I'm totally with you on better error reporting, I think that would be great. I'm just failing to help you understand that what you're asking for is not technically possible.

Just for fun, I opened up Firefox and tried to do: `<script src="node_modules/mysql/index.js"></script>`. It gave me the error `"ReferenceError: exports is not defined"`. Not a very helpful error. Should it be Firefox's responsibility to let me know the script I'm trying to load isn't compatible with the browser? Or is that error message technically impossible and as a developer, I should just know better?

Maybe I'm totally wrong though. Feel free to send a PR that can check if a module is web compatible and delivers a better error message indicating so. Cheers!

**Comment by Pomax** [comment]
I'm confused, why are you firing up Firefox? This is about errors in the terminal, during the webpack compile step...? We never even get to a point where we can even look at something in the browser.

**Comment by bebraw** [comment]
Is this issue relevant still?

**Comment by Pomax** [comment]
Hm, no idea. Although I've clearly not run into it for almost two years so my guess is "no".

**Comment by bebraw** [comment]
Ok, let's close then.
