### ISSUE TITLE
can't find module 'fs' when target is set to 'web'

### ISSUE THREAD

**Issue by bibeksh9** [webpack/webpack#11683]
# Bug report

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**
I have a package @mapbox-gl while bundleing if I set target to 'web' . I getting the error

**What is the expected behavior?**

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

**Comment by sokra** [comment]
`fs` only exists in Node.js. It's not available in the web.
