### ISSUE TITLE
Cannot find module 'webpack-cli/bin/config-yargs'

### ISSUE THREAD

**Issue by zhangshimingde** [webpack/webpack#11682]
# Bug report

where I update the webpack to 5.1.0, webpack-cli 4.0.0 ,it throw    throw err;
    ^

Error: Cannot find module 'webpack-cli/bin/config-yargs'

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

**Comment by evilebottnawi** [comment]
Please read https://github.com/webpack/webpack-dev-server/issues/2759

**Comment by Imprasna** [comment]
![Screenshot from 2020-12-02 15-18-38](https://user-images.githubusercontent.com/31104095/100858681-4f0de380-34b4-11eb-9e1a-63895f118a5b.png)
I encounter this err when I run npm run start
