### ISSUE TITLE
webpack adds not license comments to license.txt 

### ISSUE THREAD

**Issue by mathmakgakpak** [webpack/webpack#11687]
# Bug report

**What is the current behavior?**
adds babel+itself comments to license.txt file
![image](https://user-images.githubusercontent.com/44949126/95978032-eb532c80-0e19-11eb-910c-52d2294c1d73.png)
![image](https://user-images.githubusercontent.com/44949126/95978069-f6a65800-0e19-11eb-8f34-b76cfb864e2c.png)
![image](https://user-images.githubusercontent.com/44949126/95978088-fd34cf80-0e19-11eb-89b2-69993548bfc4.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
use pathinfo option and production build

**What is the expected behavior?**
it should add only license fields like the buffer one or license of package
![image](https://user-images.githubusercontent.com/44949126/95978955-33268380-0e1b-11eb-84e8-372a257260f2.png)

**Other relevant information:**
webpack version:  5.1.0
Node.js version: v12.18.3
Operating System: Windows 10
Additional tools:

**Comment by evilebottnawi** [comment]
Because you have `ouptut.pathinfo: true`

**Comment by mathmakgakpak** [comment]
i know that i have it but i thought that it should not add these comments to license file

**Comment by evilebottnawi** [comment]
It is expected
