### ISSUE TITLE
HashedModuleIdsPlugin not found in webpack/lib

### ISSUE THREAD

**Issue by zhangshimingde** [webpack/webpack#11681]
# Bug report

HashedModuleIdsPlugin not found in webpack/lib,so when I set the HashedModuleIdsPlugin,it threw  plugins: [new _webpack["default"].HashedModuleIdsPlugin(), new _happypack["default"]({   
            ^

TypeError: _webpack.default.HashedModuleIdsPlugin is not a constructor
**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

**Comment by sokra** [comment]
It has been moved to `webpack.ids.HashedModuleIdsPlugin`
