### ISSUE TITLE
The Chinese official website had a router problem.

### ISSUE THREAD

**Issue by bvanjoi** [webpack/webpack#11684]
In the page of https://www.webpackjs.com/, when you click the button '英文官网', it had redirect a wrong router: https://www.webpackjs.com/https:/webpack.js.org/.... 

Em, I think the right router path in the tag a should delete the char code '/'..

**Comment by evilebottnawi** [comment]
Please open an issue in `webpackjs.com` docs repo, we don't create this site, sorry
