### ISSUE TITLE
Caching is not working

### ISSUE THREAD

**Issue by csomakk** [webpack/webpack#11689]
# Bug report

In the attached image, red square should be like blue square. (cached)

**What is the current behavior?**
GIVEN my webpack config is set up for caching with
```
output: {
        filename: '[name].[contenthash].js',
        path: path.resolve(__dirname, 'dist'),
    },
```

WHEN i load the build on Chrome
THEN it is not loading from the cache name.a34f.js according to devtools

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
THEN it is loading from the cache name.a34f.js according to dev tools `(disk cache)` or `(memory cache)` is listed under size column on dev tools network tab.

**Other relevant information:**
webpack version:  4.39.3
Node.js version: 13.11.0
Operating System: Mac OS 10.15.6
Additional tools: -

![Screenshot 2020-10-14 at 19 34 31](https://user-images.githubusercontent.com/629462/96024829-9385e700-0e54-11eb-8d9d-22daeb2dd3ec.png)

**Comment by csomakk** [comment]
the server has no cache control set up, neither http header

**Comment by evilebottnawi** [comment]
Not related to cache, please read how cache works

**Comment by evilebottnawi** [comment]
Also cache doesn't work on wepback@4

**Comment by evilebottnawi** [comment]
Browsers cache is not our scope

**Comment by csomakk** [comment]
2nd comment is helpful, thanks.
browser cache -- yeah, its not your scope i get that but half the internet is full with recommending this way.. Google's https://web.dev/codelab-http-cache/ literally mentions webpack for this...

**Comment by csomakk** [comment]
and it also is literally in your guide https://webpack.js.org/guides/caching/

**Comment by csomakk** [comment]
@evilebottnawi and it works if i add a new script tag for html as well.

**Comment by evilebottnawi** [comment]
Yes, you need add script, please use stackoverflow for questions

**Comment by csomakk** [comment]
I MEANT 
<body>
<script type="text/javascript" src="bbbb.a21b968dd4a8cbe36e6c.js"></script>
<script type="text/javascript" src="/static-assets/ccccc.js"></script>

the webpack generated bbbb is not cached, the cccc is.
