### ISSUE TITLE
webpack5: UnhandledPromiseRejectionWarning: TypeError: compiler.apply is not a function

### ISSUE THREAD

**Issue by jackIsZlg** [webpack/webpack#11697]
when I use
 const webpack = require('webpack');
const compiler = webpack(CONFIG);
compiler.apply(new WebpackBar());

it can not work，has errors：
  UnhandledPromiseRejectionWarning: TypeError: compiler.apply is not a function。。。at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5372) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

 **but it worked in webpack4**

[https://cdn.weipaitang.com/static/2020101557454143-a57c-4143a57c-fbfe-8ea6f5166dc0-W1062H416](url)

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by evilebottnawi** [comment]
Please open new issue in `WebpackBar` repo
