### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module

### ISSUE THREAD

**Issue by l09a** [webpack/webpack#11696]
# Bug report

**What is the current behavior?**

When I try to import `react-redux` from my client code the server throws this error:

```
$ node dist/ssr-server.js 
internal/modules/cjs/loader.js:1153
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/dev/testssr/node_modules/@babel/runtime/helpers/esm/extends.js
require() of ES modules is not supported.
require() of /home/dev/testssr/node_modules/@babel/runtime/helpers/esm/extends.js from /home/dev/testssr/dist/ssr-server.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename extends.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/dev/testssr/node_modules/@babel/runtime/helpers/esm/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:13)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at eval (webpack:///external_%22@babel/runtime/helpers/esm/extends%22?:1:18)
    at Object.@babel/runtime/helpers/esm/extends (/home/dev/testssr/dist/ssr-server.js:456:1)
    at __webpack_require__ (/home/dev/testssr/dist/ssr-server.js:21:30)
    at eval (webpack:///./client/node_modules/react-redux/es/components/connectAdvanced.js?:3:92)
    at Module../client/node_modules/react-redux/es/components/connectAdvanced.js (/home/dev/testssr/dist/ssr-server.js:134:1) {
  code: 'ERR_REQUIRE_ESM'
}
```

**If the current behavior is a bug, please provide the steps to reproduce.**

I've uploaded a simple reproduction of the error: https://github.com/l09a/webpack-babel-bug

To reproduce:

```
$ git clone https://github.com/l09a/webpack-babel-bug
$ cd webpack-babel-bug/client
$ npm i
$ cd ..
$ npm i
$ npm start
$ node dist/ssr-server.js
```

**What is the expected behavior?**

The code runs without error.

**Other relevant information:**
webpack version:  5.1.0
Node.js version: v12.18.4
Operating System: Ubuntu 20.04.1 LTS
Additional tools:

**Comment by sokra** [comment]
You defined `@babel/runtime/helpers/esm/extends` as (commonjs) external, but it's a ESM file. We do not support `module` externals, but `import` externals.

* Try to add `externalsType: "import"` to your config as workaround.
* Maybe this should be solved in `webpack-node-externals`
* Maybe there is an babel option to use commonjs runtime helpers instead.

**Comment by evilebottnawi** [comment]
Answer above

**Comment by shanshanzhu** [comment]
i ended up using `webpack-node-externals` in webpack config to sort of bypass this issue
```
const nodeExternals = import 'webpack-node-externals';

// add these to the webpack config.
    externals: [
          nodeExternals({
            whitelist: [/^@babel\/runtime/],
          }),
     ],
```

This solution creates duplicated babel/runtime file injections and can also be mitigated by https://webpack.js.org/loaders/babel-loader/#babel-is-injecting-helpers-into-each-file-and-bloating-my-code



            whitelist: [/^@babel\/runtime/],
          }),

**Comment by bendman** [comment]
> I ended up using `webpack-node-externals` in webpack config to sort of bypass this issue
> 
> ```
> const nodeExternals = require('webpack-node-externals');
> 
> // add these to the webpack config.
>     externals: [
>           nodeExternals({
>             whitelist: [/^@babel\/runtime/],
>           }),
>      ],
> ```
> 
> This solution creates duplicated babel/runtime file injections and can also be mitigated by https://webpack.js.org/loaders/babel-loader/#babel-is-injecting-helpers-into-each-file-and-bloating-my-code

This worked perfectly for me, except the key in our version of nodeExternals is `allowList`, not `whitelist`.
