### ISSUE TITLE
Webpack configuration no longer supports mocking Node.js modules

### ISSUE THREAD

**Issue by adarshbhat** [webpack/webpack#11699]
# Bug report

**What is the current behavior?**
Webpack configuration no longer supports mocking Node.js modules. Currently, an error is thrown:

```
Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.node should be one of these:
   false | object { __dirname?, __filename?, global? }
```

It looks like the schema used to validate webpack.config.js is too restrictive.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Sample `webpack.config.js` : https://gist.github.com/adarshbhat/3ec5950b66b78102da0cf46e51a3d633
1. Use a module that does a `require('fs')`

**What is the expected behavior?**
If `webpack.config.js` has specified `node: { fs: 'empty' }`, then an empty object should be returned when `require('fs')` is called. 

Currently, running `webpack` throws a validation error. It looks like the schema used to validate webpack.config.js is too restrictive.

Relevant documentation is here: https://webpack.js.org/configuration/node/#node

**Other relevant information:**
webpack version:  5.1.0
Node.js version: 14.5.0
Operating System: Windows 10
Additional tools: NA

**Comment by chenxsan** [comment]
As you might find in the document https://webpack.js.org/configuration/node/#node only support three properties including `global`, `__filename` and `__dirname`.

What you need here could be https://webpack.js.org/configuration/resolve/#resolvefallback:

```json
{
  resolve: {
    fallback: {
      fs: false
    }
  }
}
```
But I haven't tested it yet.

**Comment by adarshbhat** [comment]
Thank you for your response. I will try out your recommendation.

**Comment by adarshbhat** [comment]
@chenxsan Your recommendation worked! Thank you so much.
