### ISSUE TITLE
Ensure runtimeChunk: single doesnt empty out federated container runtimes

### ISSUE THREAD

**Issue by ScriptedAlchemy** [webpack/webpack#11691]
## Feature request

When using runtimeChunk: single -  it appears the federated container.js file does not have the rest of the webpack runtime. This is harder to pull both runtime and container across on other apps

**What is the expected behavior?**
the remote container should be able to boot without depending on another runtime module. 
All runtime requirements should be preserved on the module federation entry point 

**What is motivation or use case for adding/changing the behavior?**
Next.js and general caching strategies split out the runtime from main. 

**How should this be implemented in your opinion?**
keep a copy of the runtime requirements from the runtime chunk and re-add them / concatenate it into the consiner.js file

**Are you willing to work on this yourself?**
yes

**Comment by Cronus1007** [comment]
@ScriptedAlchemy  Sir shall I take over this issue.

**Comment by ScriptedAlchemy** [comment]
@Cronus1007 yes please. I've gotten this to work previously but it involved some hacks like pushing runtime requirements into an array, then writing those strings back to remoteContainer.

**Comment by Cronus1007** [comment]
Sir I was also going for the similiar appoach.

**Comment by Cronus1007** [comment]
@ScriptedAlchemy  Sir rather we can have a copy of the array and export it so that our changes would be reflected in that array.
By this we are not changing our orignal runtime array and malfunctioning won't occur.

**Comment by ScriptedAlchemy** [comment]
Okay

**Comment by ScriptedAlchemy** [comment]
```

const shell = require("shelljs");
const path = require("path");

module.exports = class MergeRemoteChunksPlugin {
  // Define `apply` as its prototype method which is supplied with compiler as its argument
  apply(compiler) {
    // Specify the event hook to attach to
    compiler.hooks.afterEmit.tap("MergeRemoteChunksPlugin", (output) => {
      const emittedAssets = Array.from(output.emittedAssets);
      const files = [
        "static/chunks/webpack",
        "static/runtime/remoteEntry",
      ]
        .filter((neededChunk) =>
          emittedAssets.some((emmitedAsset) =>
            emmitedAsset.includes(neededChunk),
          ),
        )
        .map((neededChunk) =>
          emittedAssets.find((emittedAsset) =>
            emittedAsset.includes(neededChunk),
          ),
        )
        .map((file) => path.resolve(__dirname, ".next", file));
      if (files.length > 0) {
        shell
          .cat(files)
          .to(
            path.resolve(
              __dirname,
              ".next/static/runtime/remoteEntryMerged.js",
            ),
          );
      }
    });
  }
};

```

**Comment by Cronus1007** [comment]
Sir I am looking into shelljs and will soon send a PR to close this issue with all the test Cases, snapshots and typing updated.
For understanding the concept of module federation referring to this video of yours 
https://www.youtube.com/watch?v=HDRIvks0yyk

**Comment by ScriptedAlchemy** [comment]
I published it here (use MergeRuntime) 
https://github.com/module-federation/nextjs-mf

**Comment by ScriptedAlchemy** [comment]
dont use shelljs, not if this is going to be a webpack PR, this plugin is a hack, but it works for now

**Comment by Cronus1007** [comment]
> @ScriptedAlchemy Sir rather we can have a copy of the array and export it so that our changes would be reflected in that array.
> By this we are not changing our orignal runtime array and malfunctioning won't occur.

I think we can approach like this we can have a copy of the runtime requirements from the RuntimeRequirementsDependency.js and then expose the runtime requirements via the container.json file.

**Comment by ScriptedAlchemy** [comment]
Yeah agreed. That's the best approach I can think of

**Comment by Cronus1007** [comment]
I have just updated the schema and declarations so that you will have a look at how I have exposed the runtimerequirements to the ModuleFederationPlugin

**Comment by Cronus1007** [comment]
@sokra  @ScriptedAlchemy  Sir ModuleFederationPlugin.js lacks the runtimeRequirements (including both the chunkRuntime and  the present runtime ) So first of all we have to enable the chunkRuntime and then we have to merge the chunkRuntime and the runtimeRequirements 
![Screenshot (100)](https://user-images.githubusercontent.com/56436023/97336883-8bdb2f00-18a5-11eb-83ce-2ffe8f1bb443.png)

**Comment by ScriptedAlchemy** [comment]
I'm not sure if that would be don't in the MF plugin directly but I think we need to add runtime requirements to the container specifically.

**Comment by Cronus1007** [comment]
Sir as per my observations We need to handle  runtime dependent code in the ModuleFederationPlugin,js.Have a look at #11843

**Comment by ScriptedAlchemy** [comment]
Nice work, definitely will take a closer look

**Comment by Cronus1007** [comment]
#11843 Sir can we merge this pr to main?
