### ISSUE TITLE
From 1.9.10 to 1.9.11: CLI does not read entry point from command line

### ISSUE THREAD

**Issue by dhlavaty** [webpack/webpack#1169]
After upgrading from 1.9.10 to 1.9.11 the following script does not work anymore:

Script from package.json:

    ...
    "test": "webpack ./test/tests.js --output-file tmpTestBundle.js --target node"
    ...

Webpack is still using entrypoint from `webpack.config.js` and not one from command line as in previous version (1.9.10).

**Comment by Geril** [comment]
+1

**Comment by kuka-radovan** [comment]
+1

**Comment by patrik-piskay** [comment]
+1

**Comment by soson** [comment]
+1

**Comment by sokra** [comment]
`./test/tests.js` is appended to the entry point.

**Comment by bebraw** [comment]
@dhlavaty Any luck with the current version? Did you see the tip?
