### ISSUE TITLE
Webpack 5 hashed module ids are different for the same modules, compared to webpack 4

### ISSUE THREAD

**Issue by weareoutman** [webpack/webpack#11700]
# Bug report

**What is the current behavior?**

I followed the migration guide and changed the `HashedModuleIdsPlugin` to `optimization: { moduleIds: "hashed" }`. However, the generated manifest are different than the past when using Webpack 4.

We use `DllPlugin` to generate manifest.json in the main app, and use `DllReferencePlugin` in other independently-deployed plugins. Since the main app and plugins are deployed independently, the different manifest caused our main app using webpack 5 can't work with existed plugins which built by webpack 4.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

I hope there is a workaround to make the module ids generated keep the same as webpack 4.

**Other relevant information:**
webpack version:  5.1.0
Node.js version: 12.19.0
Operating System: MacOS 10.15.5
Additional tools:

**Comment by sokra** [comment]
Sorry we don't support compatibility of DLLs between webpack 4 and 5. Update all to webpack 5.
