### ISSUE TITLE
Build assets aren't included in the build output in production mode (regression from 5.1.0 to 5.1.1)

### ISSUE THREAD

**Issue by JessevanAssen** [webpack/webpack#11707]
# Bug report

**What is the current behavior?**
I have project which uses the mini-css-extract-plugin to extract the styles to a CSS file. However, the resulting css file seems to be marked as an orphan, and not included in the final build output during a production build. This is a regression from Webpack 5.1.0 to 5.1.1, in the former, the css file is present in the dist/ folder.

**If the current behavior is a bug, please provide the steps to reproduce.**
This is the same project setup as listed on https://webpack.js.org/plugins/mini-css-extract-plugin/

src/index.js:
```js
import './style.css';
```

src/index.css:
```css
body {
	background: green;
}
```

webpack.config.js:
```js
const CssExtractPlugin = require('mini-css-extract-plugin');

module.exports = {
	plugins: [new CssExtractPlugin()],
	module: {
		rules: [
			{
				test: /\.css$/i,
				use: [CssExtractPlugin.loader, 'css-loader'],
			},
		],
	},
};
```

If I run Webpack with `npx webpack --mode=production`, no "main.css" file is present in the output folder.
If I run Webpack with `npx webpack --mode=development`, the file is properly created.

**What is the expected behavior?**
I expect the css file to be present in the output folder, so it's consistent with Webpack 5.1.0 and older.

**Other relevant information:**
Webpack version:  5.1.1
Node.js version: v14.13.1
NPM version: v6.14.8
Operating System: Ubuntu 20.04.1
Additional tools:

**Comment by JessevanAssen** [comment]
I've bisected it to this commit: https://github.com/webpack/webpack/commit/50c3a83340605694c90ff6973e3bd103763b88d9

**Comment by evilebottnawi** [comment]
Thanks for issue, keep using webpack@5.1.0, fix will be soon

**Comment by sokra** [comment]
Seems like this case slipped through the process. I think our test suite still runs against an older version of mini-css.

I revert the change until I find a better fix tomorrow.

**Comment by evilebottnawi** [comment]
@JessevanAssen can you test?

**Comment by JessevanAssen** [comment]
Thanks for the quick response! The issue is not present any more in 5.1.2.
Also, I've tested @sokra's assumption, and indeed the tests are running against an older version of mini-css. If I bump it to the latest version, [the tests that cover the mini-css-extract-plugin](https://github.com/webpack/webpack/tree/master/test/watchCases/plugins/mini-css-extract-plugin) indeed start to fail.

**Comment by sokra** [comment]
Could you try again with 5.1.3?

**Comment by JessevanAssen** [comment]
Yep, my use case works with 5.1.3 as well :). Thanks for the quick response!
