### ISSUE TITLE
[5.1.2] Progress message shows separate percentages when exporting multiple configurations

### ISSUE THREAD

**Issue by doberkofler** [webpack/webpack#11717]
# Bug report

**What is the current behavior?**

When exporting multiple configurations the percentage of the progress message does not show a combined value but rather switches between the individual sub projects.

**If the current behavior is a bug, please provide the steps to reproduce.**

```js
module.exports = [{
  output: {
    filename: './dist-amd.js',
    libraryTarget: 'amd'
  },
  name: 'amd',
  entry: './app.js',
  mode: 'production',
}, {
  output: {
    filename: './dist-commonjs.js',
    libraryTarget: 'commonjs'
  },
  name: 'commonjs',
  entry: './app.js',
  mode: 'production',
}];
```

**What is the expected behavior?**

It would be great, if a combined (based on on the totals or the minimum) percentage could be shown.

**Other relevant information:**

webpack version:  5.1.2
Node.js version: 14.13.0
Operating System: 10.15.7
Additional tools:

**Comment by evilebottnawi** [comment]
Please provide more information what you expected

**Comment by evilebottnawi** [comment]
You ignore `**If the current behavior is a bug, please provide the steps to reproduce.**` section, I will reopen this after you fix it

**Comment by doberkofler** [comment]
I do absolutely respect the time of others developers and actually filled out the `If the current behavior is a bug, please provide the steps to reproduce.` with the example from the webpack documentation to explain that this is a generic problem and not specific to a unique configuration.

I'm not sure on how to better describe the expected behavior:
- imagine a configuration with several (quite different) configurations
- currently the progress message shows a percentage that flips between each individual configuration (10%, 11%, 2%, 15%, 3%, ...) because it seems (just an educated guess) to flip between the different configurations
- it would be more useful, if the percentage wold be either calculated based on the total numbers from all configurations or (if this is not possible) at least always only show the minimum of the the individual configurations

**Comment by evilebottnawi** [comment]
@doberkofler expected, different configurations === different builds

**Comment by doberkofler** [comment]
If this is really expected I will just have to accept it, but I really don't understand why someone would expect a percentage that just flips between builds?

**Comment by evilebottnawi** [comment]
@doberkofler because each bundling knows nothing about the other bundling, and combining them is a difficult task, also it reduces readability

**Comment by doberkofler** [comment]
I understand! Thank you!
