### ISSUE TITLE
Can't use an npm module (webpack 5)

### ISSUE THREAD

**Issue by devinrhode2** [webpack/webpack#11710]
I guess webpack 5 will not allow me to just npm install some package if it requires some node api's. I understand the intent is to reduce bundle size, but I think that's achieved very well by the vscode extension [Import Cost](https://marketplace.visualstudio.com/items?itemName=wix.vscode-import-cost)
If an import is sufficiently large, Import Cost will give you a nice red "68.1k gzipped"
Perhaps webpack could print out an "Import Cost Report" on the command line. Or even write some bundle-analyzer report to a file that's in the repo, so developers can see in PR's that there's a new package added to the package.json, and the bundle-size report shows it costs 50k. This more generally tackles the problem of bundle sizes.

**Comment by sokra** [comment]
> I guess webpack 5 will not allow me to just npm install some package if it requires some node api's.

It's doesn't allow it out of the box, but you can install and add the required polyfills to support that. Please read the error messages, they tell you what you need to do.

> I understand the intent is to reduce bundle size

That's not the only reason. Not even the biggest one.

We want to align with what browsers do and what's spec'ed on the web platform. Node.js API is not part of any browser, and it shouldn't be that way. I think the frontend ecosystem incorrectly accepted this dependency from the frontend ecosystem to the Node.js ecosystem and we should move away from that.

These node.js API are not listed within the dependencies of a package, so there is no semantic versioning with them. A package that works now might break in a few years when Node.js APIs have changed and we ship different polyfills.

It's just wrong that frontend packages use Node.js APIs. These packages should have **at least** listed these Node.js APIs as `dependencies` and use the `browser` field to apply them for in browser usage.

> Or even write some bundle-analyzer report to a file that's in the repo, so developers can see in PR's that there's a new package added to the package.json, and the bundle-size report shows it costs 50k.

You can use `webpack --analyse`

**Comment by evilebottnawi** [comment]
Feel free to feedback
