### ISSUE TITLE
Analysis web page crashes on Hints

### ISSUE THREAD

**Issue by perqa** [webpack/webpack#11711]
# Bug report
Regarding http://webpack.github.io/analyse/#hints

**What is the current behavior?**
If you go to "Hints" tab in the analysis page, it crashes, and must be reloaded in order to work again.
http://webpack.github.io/analyse/#hints

**If the current behavior is a bug, please provide the steps to reproduce.**
Upload a stats.json file on http://webpack.github.io/analyse/ and click the tab _Hints_. After that the page becomes unresponsive. Not sure if this happens for **any** stats.json, but I can not currently attach the offending one to this ticket. This error can be seen in developer console at the moment you click _Hints_:

```contentscript.js:54 <body class=​"modal-open">​…​</body>​
15f6448ec2a08f35395d.js:1 [Violation] 'load' handler took 463ms
f82681492bc705423f7a.js:1 Uncaught (in promise) TypeError: Cannot read property 'join' of undefined
    at f82681492bc705423f7a.js:1
    at f82681492bc705423f7a.js:1
    at e.exports (f82681492bc705423f7a.js:1)
    at e.exports (f82681492bc705423f7a.js:1)
    at HTMLDocument.<anonymous> (web.js:1)
    at j (jquery-2.1.0.min.js:2)
    at Object.add [as done] (jquery-2.1.0.min.js:2)
    at o.fn.init.o.fn.ready (jquery-2.1.0.min.js:2)
    at new o.fn.init (jquery-2.1.0.min.js:2)
    at o (jquery-2.1.0.min.js:2)
(anonymous) @ f82681492bc705423f7a.js:1
(anonymous) @ f82681492bc705423f7a.js:1
e.exports @ f82681492bc705423f7a.js:1
e.exports @ f82681492bc705423f7a.js:1
(anonymous) @ web.js:1
j @ jquery-2.1.0.min.js:2
add @ jquery-2.1.0.min.js:2
o.fn.ready @ jquery-2.1.0.min.js:2
o.fn.init @ jquery-2.1.0.min.js:2
o @ jquery-2.1.0.min.js:2
i @ web.js:1
Promise.then (async)
i @ web.js:1
a @ web.js:1
(anonymous) @ web.js:1
```

**What is the expected behavior?**
To get some hints or a message saying there are no hints. No uncaught errors in console.

**Other relevant information:**
webpack version:  "webpack": "^4.44.1",
Node.js version: v14.8.0
Operating System: Mac OS 10.12.6
Additional tools: "stats-webpack-plugin": "^0.7.0",

**Comment by evilebottnawi** [comment]
@webpack-bot move to webpack/analyse
