### ISSUE TITLE
Support disabling disk cache for certain modules

### ISSUE THREAD

**Issue by liximomo** [webpack/webpack#11715]
## Feature request
Disable disk cache for certain modules.

**What is the expected behavior?**
One should be able to disable disk cache for certain modules.

**What is motivation or use case for adding/changing the behavior?**
Some plugins would replace the module loader conditionally by plugin which made the content of the module dynamic. In such situation, the module should not be cached on disk.

**How should this be implemented in your opinion?**
Checking the `diskCacheable` property of a module before save it to disk.

**Are you willing to work on this yourself?**
yes

**Comment by evilebottnawi** [comment]
Sorry no, if you have problems with caching please open a new issue with example of problem(s)

**Comment by evilebottnawi** [comment]
> One should be able to disable disk cache for certain modules.

this makes the cache extremely ineffective, and others may start to abuse it, we want to avoid it

> Some plugins would replace the module loader conditionally by plugin which made the content of the module dynamic. In such situation, the module should not be cached on disk.

What is condition?

**Comment by liximomo** [comment]
![image](https://user-images.githubusercontent.com/9816225/96272495-bd7c0c80-1000-11eb-8f8d-e26e042ed8e1.png)

The module is always non-cacheable at the first build, after that, it's would be cacheable in memory. The behavior would be break if it's be cached in disk.


And talking about effective, it would be extremely ineffective if I have to disable the whole disk cache because of just such one non-disk-cacheable module.

**Comment by evilebottnawi** [comment]
It is bad idea, you can't change it to `true`, this modules are uncachable always

**Comment by liximomo** [comment]
But it did works and get cached id disk, it works well without disk cache.

**Comment by evilebottnawi** [comment]
@liximomo hm, maybe you can create reproducible test repo?

**Comment by liximomo** [comment]
Ok, I will create one.

**Comment by liximomo** [comment]
Here is reproducible repo. https://github.com/liximomo/wepback-disk-cache-bug

**Comment by liximomo** [comment]
@evilebottnawi any feedback?

**Comment by evilebottnawi** [comment]
@liximomo marked as `enhancement`, but i think it will never be implemented

**Comment by liximomo** [comment]
@evilebottnawi  Would you like me to implement this?

**Comment by evilebottnawi** [comment]
@liximomo feel free to send a PR, but I will be not easy

**Comment by alexander-akait** [comment]
bump

**Comment by sokra** [comment]
I think disk vs memory caching should be transparent for the loaders. They should not differ between them.

You better solve your use case by adding the loader during resolving so it's part of the module identifier and two cache entries are created, with and without loader.

**Comment by sokra** [comment]
btw. we might add the behavior of your plugin as native core feature soonish... (experimental)
