### ISSUE TITLE
Watch option is ignored

### ISSUE THREAD

**Issue by fabiospampinato** [webpack/webpack#11723]
**What is the current behavior?**

Webpack 5 ignores the `watch: true` configuration option.

**If the current behavior is a bug, please provide the steps to reproduce.**

I can't easily extract a minimal repo that reproduces the issue, but literally having "watch: true" in the configuration just didn't make Webpack watch files as it should, and it instead just exited with exit code 0. Passing `--watch` to `webpack-cli` worked instead.

**What is the expected behavior?**

No options should be ignored.

**Other relevant information:**

webpack version:  5.1.3
Node.js version: 12.12
Operating System: macOS 10.14
Additional tools: Like what? I don't think other tools are relevant to this issue.

**Comment by evilebottnawi** [comment]
Fixed in webpack-cli in master, release will be today/tomorrow

**Comment by evilebottnawi** [comment]
Sorry for regressions
