### ISSUE TITLE
ModuleFederationPlugin Babel IE11 support

### ISSUE THREAD

**Issue by StevenMatchett** [webpack/webpack#11722]
# Bug report

**What is the current behavior?**
When using federated modules babel is not transpiling the remoteEntry file. This causes IE11 to throw a syntax error as it doesn't understand arrow function

**If the current behavior is a bug, please provide the steps to reproduce.**

I created a new repo to show the issue. Run yarn && yarn build. You will see in the build folder remoteEntry file will contain arrow functions

https://github.com/StevenMatchett/webpack5-ie11-issue

**What is the expected behavior?**

When babel transform arrow functions is used it transform output

**Other relevant information:**
webpack version:  5.1.3
Node.js version: 10.x.x
Operating System: OSX

**Comment by evilebottnawi** [comment]
Please read changelog, `target: ['web', 'es5']`

**Comment by ScriptedAlchemy** [comment]
Lol yes agree. Down with IE
