### ISSUE TITLE
duplicate module when use async import

### ISSUE THREAD

**Issue by zWingz** [webpack/webpack#11720]
# Bug report

**Files**

```js
// components/common.js
export function test() {
  console.log('commonjs')
}

// src/main1.js
import { test } from './components/common'
test()

// src/main2.js
import { test } from './components/common'
test()

// src/main.js
const a = () => import('./main2')
const b = () => import('./main3')
console.log(a);
console.log(b);

```

**What is the current behavior?**

`main1.js` bundled to `1.js`, `main2.js` bundled to `2.js`,
but `commonn.js` bundled to both `1.js` and `2.js`

**What is the expected behavior?**

`commons.js` should be bundled to `component.js`

**Other relevant information:**

```js
// webpack.config.js
const path = require('path')
module.exports = {
  entry: './src/main.js',
  output: {
    path: path.join(__dirname, 'dist')
  },
  optimization: {
    minimize: false,
    splitChunks: {
      cacheGroups: {
        components: {
          name: 'components',
          priority: 30,
          minChunks: 1,
          reuseExistingChunk: false,
          test: 'components'
        },
      },
    },
  },
}

```

**Comment by vankop** [comment]
this is by design (note: modules executed once), @sokra please help with opt-out

**Comment by zWingz** [comment]
@vankop it is a bug in webpack-4 or feature in webpack-5 ?

**Comment by sokra** [comment]
webpack 4 and 5 work nearly identical here.

The source code of small common modules is duplicated in each chunk. To deduplicate the modules an additional request would be needed and that's not worth it. You can take a look at the `optimization.splitChunks` configuration to change this behavior. Look at `minSize`.

**Comment by evilebottnawi** [comment]
Answer above, feel free to feedback
