### ISSUE TITLE
Node mocking not working: configuration[0].node has an unknown property

### ISSUE THREAD

**Issue by lcrosetto** [webpack/webpack#11727]
# Bug report

**What is the current behavior?**

Node module mocking in the configuration does not work as of v5.1.3, and will produce a schema error such as:

```
'Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.\n' +
    " - configuration[0].node has an unknown property 'fs'. These properties are valid:\n" +
    '   object { __dirname?, __filename?, global? }\n' +
    '   -> Options object for node compatibility features.\n' +
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Add any key to the the node section in the config such as:

```
node: {
  fs: 'empty'
}
```

**What is the expected behavior?**

Schema should allow module names. It looks like additionalProperties in the NodeOptions schema is missing:

`"additionalProperties": false,
`
 I have tested with the the version from v4 and it works (WebpackOptions.json):

```
    "additionalProperties": {
        "description": "Include a polyfill for the node.js module",
        "enum": [false, true, "mock", "empty"]
      },
```

**Other relevant information:**
webpack version:  5.1.3
Node.js version: 13.12.0
Operating System: macOS 10.15.7
Additional tools:

**Comment by chenxsan** [comment]
Check https://github.com/webpack/webpack/issues/11699 to see if it can help.

**Comment by evilebottnawi** [comment]
No `node.fs` anymore

**Comment by lcrosetto** [comment]
Do the docs need to be updated?

https://webpack.js.org/configuration/node/#node

> boolean = false object
> 
> This is an object where each property is the name of a Node global or module and each value may be one of the following...
> 
> true: Provide a polyfill.
> 'mock': Provide a mock that implements the expected interface but has little or no functionality.
> 'empty': Provide an empty object.
> false: Provide nothing. Code that expects this object may crash with a ReferenceError. Code that attempts to import the module using require('modulename') may trigger a Cannot find module "modulename" error.

This matches with the schema from v4.

**Comment by chenxsan** [comment]
@lcrosetto Yes, the `mock` value was removed and a new `eval-only` was added https://github.com/webpack/webpack/blob/master/schemas/WebpackOptions.json#L1213, I'll updated the documentation.

**Comment by jhenriquevissotto** [comment]
Same problem here!
