### ISSUE TITLE
Modules can exist in more than one chunk

### ISSUE THREAD

**Issue by pornel** [webpack/webpack#1172]
I'd like to move rarely used/optional features of my application to separate chunks, so they can be loaded lazily.

I'm using `require.ensure` with a chunk name:

```js
require.ensure([], function(){
    require("feature-foo"); 
}, "feature-foo");
```

In the above example `feature-foo.js` requires other modules from all over the place, but tries to use `require.ensure` consistently when requiring other features from other chunks.

This works as expected only if I have one "feature" chunk. As soon as I add more chunks, many modules end up being in multiple chunks at the same time, massively increasing total size of the application. Example webpack stats have the same issue:

http://webpack.github.io/analyse/#module/119

How can I ensure that every module lives only in one chunk and that is never ever ever ever in more than one chunk?

Unfortunately, the dependency graph of my app is a ball of mud, so I can't guarantee that I don't have any circular dependencies or cross dependencies between chunks.

I'd be OK if need for a module to be in more than one chunk was a compilation error, or if the module was moved to the entry chunk, or triggered load of more chunks. Just never duplicate any code.

**Comment by sirlancelot** [comment]
Have a look at the rules of [Chunk Optimization](http://webpack.github.io/docs/code-splitting.html#chunk-optimization). Webpack is only duplicating modules for which it can't guarantee will be included at every code split.

**Comment by pornel** [comment]
So I think my problem is that when module is not guaranteed to be available, instead of duplicating it, I'd like webpack to load the chunk that has the module (i.e I'd rather trigger load of 2 chunks than load one chunk, but with duplicate modules).

I guess that's not possible?

**Comment by sirlancelot** [comment]
I can think of two options at the moment: 1) You can sprinkle `require.include` statements around your code base to help Webpack determine how to bundle certain modules; 2) You can fiddle around with [AggressiveMergingPlugin](http://webpack.github.io/docs/list-of-plugins.html#aggressivemergingplugin).

Either way, your post is more of a question than an issue. You may get better answers by asking on Gitter or StackOverflow perhaps.

**Comment by pornel** [comment]
Thanks. 

In the meantime I've added code to my build to analyze webpack's stats and throw error when a module is in more than one chunk, and I'm trying to move dependencies around to avoid these cases :)

**Comment by abergs** [comment]
@pornel Could you share that code that you wrote? :)

**Comment by pornel** [comment]
I can't, as it was for my previous employer. However, they're open-source friendly, so maybe @ rowanbeentje can share it.

**Comment by pornel** [comment]
I can't, as it was for my previous employer. However, they're open-source friendly, so maybe @rowanbeentje can share it.
