### ISSUE TITLE
Buffer is not defined - NeutrinoJs

### ISSUE THREAD

**Issue by Khatib-Abbas** [webpack/webpack#11742]
If you have this error [Buffer is not defined]
you have to use
(neutrino) => {
      neutrino.config.node.set('Buffer', true)
},
in your .neutrinorc.js config file
https://neutrinojs.org/migration-guide/

**Comment by silviuburceadev** [comment]
https://webpack.js.org/migrate/5/#test-webpack-5-compatibility explicitly documents the node's Buffer/process behaviour.

**Comment by evilebottnawi** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

**Comment by evilebottnawi** [comment]
Answer above
