### ISSUE TITLE
Common Style modules not added to all entry points

### ISSUE THREAD

**Issue by omarjov** [webpack/webpack#11744]
# Bug report

**What is the current behavior?**
We have multiple multiple entry points, and some shared components, trying to separate css according to this docs https://webpack.js.org/plugins/mini-css-extract-plugin/#extracting-css-based-on-entry, the issue is that styles of common components is bundled in only one entry point css file.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Styles of the component should be added to all entry points where it's included

**Other relevant information:**
webpack version:  4.44.2
Node.js version: v10.16.0
Operating System: All
Additional tools:

**Comment by evilebottnawi** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Do not ignore fields from the issue template, docs for v5, not for v4
