### ISSUE TITLE
SplitChunk.cacheGroup Exception

### ISSUE THREAD

**Issue by heart-er** [webpack/webpack#11746]
# Bug report

**What is the current behavior?**
add chunks: 'all' in cacheGroups.libs

![image](https://user-images.githubusercontent.com/24717511/96538224-a2dcb880-12ca-11eb-9047-fdfeb22c8618.png)

if remove chunks: 'all', webpack can be packaged normally

**If the current behavior is a bug, please provide the steps to reproduce.**
![image](https://user-images.githubusercontent.com/24717511/96535061-9d2fa480-12c3-11eb-8371-55616f572ad7.png)

**What is the expected behavior?**
webpack can be packaged normally

**Other relevant information:**
webpack version:  5.1.3
Node.js version: v10.19.0
Operating System: MacOS 10.14.6
Additional tools: Iterm2 and VSCode

**Comment by heart-er** [comment]
> _For maintainers only:_
> 
> * [ ]  webpack-4
> * [ ]  webpack-5
> * [ ]  bug
> * [ ]  critical-bug
> * [ ]  enhancement
> * [ ]  documentation
> * [ ]  performance
> * [ ]  dependencies
> * [ ]  question

**Comment by evilebottnawi** [comment]
Problem in terser, please open new issue in terser-webpack-plugin with reproducible test repo, thanks
