### ISSUE TITLE
Dual mode (ESM + CJS) regerssion between webpack 4 and webpack 5

### ISSUE THREAD

**Issue by dubzzz** [webpack/webpack#11750]
Hello 👋 

# Bug report

**What is the current behavior?**

Starting at webpack 5, I am not able anymore to import the package fast-check to my projects.
Up to know, it worked fine in webpack 4.x versions.

Something important to note is that this package handles both ESM and CJS builds together.
It applies dual mode patterns to expose the two versions to node (node is still happy with it... for the moment).

**If the current behavior is a bug, please provide the steps to reproduce.**

In order to reproduce locally you can either use the repo: https://github.com/dubzzz/webpack5-dual-mode-test
You can check that the script is compatible with node (in ESM build) by running `yarn node:fc` but not anymore with webpack 5 by running `yarn build:fc`. It worked fine with webpack 4.44.2.

Or the following configuration:

Here is a simple config for webpack:
```js
const path = require("path");
module.exports = {
  mode: "production",
  entry: { app: `./src/fc.mjs` },
  plugins: [],
  output: {
    filename: "fc.js",
    path: path.resolve(__dirname, "dist"),
  },
};
```

And the script file I am trying to build:
```js
import fc from "fast-check";
console.log(fc.__type);
```

**What is the expected behavior?**

The expected behaviour would be that the module can be imported and bundled by webpack.
Meanwhile the bug might be in the module itself (not really confident about dual modes configurations).

**Other relevant information:**
webpack version:  5.1.3
Node.js version: 12.18.2
Operating System: Windows 10
Additional tools:

**Comment by dubzzz** [comment]
Whaou thanks a lot @sokra, you are too quick

**Comment by bmeck** [comment]
We noticed this diverges from node since it adds back the searching behavior. Is there a way to turn off the searching (either we can PR a config or some path towards convergence)?

**Comment by evilebottnawi** [comment]
@bmeck I think we need support both scenarios right now, because it can potential break some packages, but we should implement this https://github.com/webpack/webpack/issues/11616

**Comment by bmeck** [comment]
@evilebottnawi that seems fine as long as we have some eventual convergence, I'm not asking to remove searching just to have a flag or something (even just a warning when searching would be fine) to make sure it matches node.

**Comment by evilebottnawi** [comment]
@bmeck yes, but before flag/option/warning we should implement recommended solution, so let' continue discussion https://github.com/webpack/webpack/issues/11616

**Comment by sokra** [comment]
The issue was about a package.json was not read for the `type: module` flag. How does it relate to searching?
