### ISSUE TITLE
arrow functions in webpackBootstrap with browserslist: "IE >= 11"

### ISSUE THREAD

**Issue by micopiira** [webpack/webpack#11753]
# Bug report

**What is the current behavior?**

With `browserslist: "IE >= 11"` in my package.json there are arrow functions in generated webpackBootstrap code. It works correctly if I use IE >= 10 in my package.json.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Add "browserslist": "IE >= 11" to package.json
2. npx webpack

**What is the expected behavior?**

I would expect the generated code to not have arrow functions for IE >= 11 since IE11 does not support arrow functions.

**Other relevant information:**
webpack version:  5.1.3
Node.js version: v14.6.0
Operating System: Ubuntu 20.04 LTS (WSL2)
Additional tools:

**Comment by evilebottnawi** [comment]
Sorry, can't reproduce, please do not ignore sections in the issue template

**Comment by anton6** [comment]
I could be wrong, but have you tried adding this to the webpack config:

```
output : {
  environment: {
    arrowFunction: false
 }
}...
```

Originally came across this here: https://medium.com/@JayKariesch/webpack-5-beta-babel-loader-why-do-i-still-have-arrow-functions-6a22980dcae4

**Comment by evilebottnawi** [comment]
Fix https://github.com/webpack/webpack/pull/11754

**Comment by anton6** [comment]
Which version of webpack is going to have this fix?

**Comment by sethomas** [comment]
@evilebottnawi can we re-open this? I am running into the same problem on `webpack@5.5.0`, if I change `browserslist` to `not ie < 10`, it works, but if it's at `not ie < 11` I still get arrow functions in my bundle.

**Comment by evilebottnawi** [comment]
@sethomas fixed, double check you webpack version, I can't reopen issue without reproducible steps, sorry

**Comment by evilebottnawi** [comment]
https://github.com/webpack/webpack/blob/master/lib/config/browserslistTargetHandler.js#L161

**Comment by sethomas** [comment]
@evilebottnawi Odd, I'll chalk it up to me having to deal with IE 11 that threw me off, all is well, sorry for wrong information and thanks for the response.

**Comment by amok** [comment]
@sethomas setting `target: 'web'` to `target: ['web', 'es5']` helped me

**Comment by Eschon** [comment]
I'm still running into this problem, but only with our production build in a docker image. My local development build works fine.
I'm not sure how to properly reproduce it.

My webpack version is 5.21.2
The docker image is node:14.15-alpine with very little added and the exact node version is 14.15.4
I have a .browserslistrc file with "defaults"

**Comment by Eschon** [comment]
Also happens with the latest webpack version (5.24.2) but at least the workaround suggested by @amok fixes it for me

**Comment by MoonE** [comment]
With OpenLayers there were also arrow functions in the generated code. webpack version 5.30.0
The affected jobs are `build-legacy` and `build-examples`, see: https://github.com/openlayers/openlayers/blob/9d773c8f19a157f98391e985f2146747bc4da77e/package.json#L20-L24
The affected output file for `build-legacy` is `build/legacy/ol.js`
For `build-examples` it is `build/examples/common.js`

Using @amok's suggestion fixed the transpilation of arrow functions. 
The change that fixes it is in https://github.com/openlayers/openlayers/pull/12181/files

Hope this information will help you to reproduce, @alexander-akait.
