### ISSUE TITLE
scss file is not loading while using webpack

### ISSUE THREAD

**Issue by VuppalaMahesh** [webpack/webpack#11757]
**Do you want to request a *feature* or report a *bug*?**
I am not sure if it is a bug or error from my end. But facing issues.

**What is the current behavior?**
My external file is in LESS(using Semantic UI LESS), for custom styles I am using SCSS. But if I am using LESS for my project custom css it is working fine, When I am using SCSS it is giving a bunch of different errors!

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Both Less and SCSS should be compiled and bundled by webpack.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
Browser version: Version 86.0.4240.80,
 Node.js version: v12.16.1,
 webpack version: 4.41.2,
Operating System: Mac OS Catalina 10.15.6

I have raised a question in stackoverflow but that solution doesn't work. I have explained my issue clearly in below link, please help me with it. 
[Stackover flow](https://stackoverflow.com/questions/64358522/scss-file-is-not-loading-while-using-webpack)

**Comment by evilebottnawi** [comment]
You have invalid configuration, sorry without reproducible example I can't help, do no ignore questions in the issue, no problems with webpack here, if you want to help please open an issue in sass-loader with reproducible test repo and I will help, answer on stackoverflow is right
