### ISSUE TITLE
Cannot extract CSS into a single file anymore after migration

### ISSUE THREAD

**Issue by wintercounter** [webpack/webpack#11752]
# Bug report

**What is the current behavior?**

After migrating to Webpack 5 my CSS doesn't get extracted into a single file. It is chunked across multiple files. I do feel all my issues are caused by the same source.

![image](https://user-images.githubusercontent.com/963776/96571192-8a20d280-12cb-11eb-9e63-1e043da11b0a.png)

![image](https://user-images.githubusercontent.com/963776/96571294-aae92800-12cb-11eb-9314-8194c936ec96.png)

Another issue is if I give `name: 'styles'` for `cacheGroup.styles` I'll get an error. This happens with any cacheGroup if I give `name` (which I had previously for WP4).

![image](https://user-images.githubusercontent.com/963776/96570281-745edd80-12ca-11eb-84c8-7349090cf028.png)

I have a third problem. It seems like `css-minimizer-webpack-plugin` is being ignored. If you take a look on the second picture, the plugin supposed to remove the duplicates. One note to add here that I migrated from `optimize-css-assets-webpack-plugin`.

**If the current behavior is a bug, please provide the steps to reproduce.**

Here are my CSS related configs.

```
{
    plugins: [
         new MiniCssExtractPlugin({
            filename: '[contenthash].css',
            ignoreOrder: true
        })
    ],
    optimization: {
        runtimeChunk: 'single',
        splitChunks: {
            maxAsyncRequests: 25,
            maxInitialRequests: 25,
            automaticNameDelimiter: '~',
            maxSize: 800000,
            cacheGroups: {
                commons: {
                    chunks: 'all',
                    test: /node_modules/,
                    priority: -10,
                    minSize: 100000
                },
                styles: {
                    test: /\.s?css$/,
                    chunks: 'all',
                    enforce: true,
                    reuseExistingChunk: true,
                    priority: 10
                }
            }
        },
        minimize: true,
        minimizer: [
            new CSSMinimizerWebpackPlugin({
                 sourceMap: true,
                 test: /\.css$/g,
                 minify: data => {
                     const [[filename, input]] = Object.entries(data)
                     // cssnano will remove duplicates
                     return (
                         require('cssnano')
                             .process(input, {
                                 preset: ['default', { discardComments: { removeAll: true } }],
                                 from: filename
                             })
                             // mqpacker will merge media queries and moves to the end
                             .then(function (cssnanoResult) {
                                 return require('mqpacker').process(cssnanoResult, {
                                     sort: true,
                                     from: filename
                                 })
                             })
                             .then(result => {
                                 return {
                                     css: result.css,
                                     map: result.map,
                                     warnings: result.warnings()
                                 }
                             })
                     )
                 }
            })
        ]
    }
}
```

**What is the expected behavior?**

All CSS is extracted into a single file and `css-minimizer-webpack-plugin` is running through fine.

**Other relevant information:**
webpack version:  5.1.3

**Comment by evilebottnawi** [comment]
Please open an issue in `mini-css-extract-plugin` with reproducible test repo, thanks

**Comment by evilebottnawi** [comment]
Already reported, https://github.com/webpack-contrib/mini-css-extract-plugin/issues/610, just create reproducible test repo and put it here https://github.com/webpack-contrib/mini-css-extract-plugin/issues/610, thanks!

**Comment by wintercounter** [comment]
Thanks, I thought this will be a problem with `splitChunks`.
