### ISSUE TITLE
scss file is not compiling to css using Webpack

### ISSUE THREAD

**Issue by VuppalaMahesh** [webpack/webpack#11756]
Hi all,

I am facing an issue with SCSS loader.  I have raised a question in stackoverflow but that solution doesn't work. I have explained my issue clearly in below link, please help me with it. 

[Stackover flow](https://stackoverflow.com/questions/64358522/scss-file-is-not-loading-while-using-webpack)

In simple words, my issue is, My external file is in LESS(using Semantic UI LESS), for custom styles using SCSS. But if I am using LESS for my project custom css it is working fine, When I am using SCSS it is giving a bunch of different errors! I am expecting help from you. Thanks in advance.

**Comment by evilebottnawi** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Please wait the asnwer.
