### ISSUE TITLE
[Documentation]Print Section in Documentation doesn't working

### ISSUE THREAD

**Issue by jvmazagao** [webpack/webpack#11766]
# Bug report

**What is the current behavior?**

![The print section in the documentation is unavailable](https://user-images.githubusercontent.com/22477816/96656568-7fd7f600-1316-11eb-998f-ffbfc2042fcb.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
1. WHEN CLICK THE link Print section shows me the image above

**What is the expected behavior?**
Should appear a window with the printable area or open the dialog to print everything.

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: MacOS
Additional tools: Chrome

**Comment by chenxsan** [comment]
Which page? I've tested some pages with Chrome on macOS but couldn't reproduce the problem you have.

BTW, it's an issue belonging to https://github.com/webpack/webpack.js.org instead of here.

**Comment by jvmazagao** [comment]
Ok, I'm moving this issue to there, sorry by the incovinent
