### ISSUE TITLE
An unhandled exception occurred: Cannot find module 'webpack/lib/WebpackError'

### ISSUE THREAD

**Issue by Bazhan4ik** [webpack/webpack#11769]
I just updated my webpack and now I have this error

`PS C:\All\randombulshit\cossac-app> ng serve
An unhandled exception occurred: Cannot find module 'webpack/lib/WebpackError'
Require stack:
- C:\All\randombulshit\cossac-app\node_modules\@ngtools\webpack\src\webpack-diagnostics.js
- C:\All\randombulshit\cossac-app\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js
- C:\All\randombulshit\cossac-app\node_modules\@ngtools\webpack\src\index.js
- C:\All\randombulshit\cossac-app\node_modules\@angular-devkit\build-angular\src\webpack\configs\typescript.js
- C:\All\randombulshit\cossac-app\node_modules\@angular-devkit\build-angular\src\webpack\configs\index.js
- C:\All\randombulshit\cossac-app\node_modules\@angular-devkit\build-angular\src\utils\package-chunk-sort.js
- C:\All\randombulshit\cossac-app\node_modules\@angular-devkit\build-angular\src\utils\index-file\write-index-html.js
- C:\All\randombulshit\cossac-app\node_modules\@angular-devkit\build-angular\src\browser\index.js
- C:\All\randombulshit\cossac-app\node_modules\@angular-devkit\build-angular\src\dev-server\index.js
- C:\All\randombulshit\cossac-app\node_modules\@angular-devkit\architect\node\node-modules-architect-host.js
- C:\All\randombulshit\cossac-app\node_modules\@angular-devkit\architect\node\index.js
- C:\All\randombulshit\cossac-app\node_modules\@angular\cli\models\architect-command.js
- C:\All\randombulshit\cossac-app\node_modules\@angular\cli\commands\serve-impl.js
- C:\All\randombulshit\cossac-app\node_modules\@angular-devkit\schematics\tools\export-ref.js
- C:\All\randombulshit\cossac-app\node_modules\@angular-devkit\schematics\tools\index.js
- C:\All\randombulshit\cossac-app\node_modules\@angular\cli\utilities\json-schema.js
- C:\All\randombulshit\cossac-app\node_modules\@angular\cli\models\command-runner.js
- C:\All\randombulshit\cossac-app\node_modules\@angular\cli\lib\cli\index.js
- C:\Users\bazha\AppData\Roaming\npm\node_modules\@angular\cli\lib\init.js
- C:\Users\bazha\AppData\Roaming\npm\node_modules\@angular\cli\bin\ng
See "C:\Users\bazha\AppData\Local\Temp\ng-U7tlBY\angular-errors.log" for further details.`

**Comment by evilebottnawi** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

**Comment by evilebottnawi** [comment]
Open an issue in `ngtools` repo
