### ISSUE TITLE
[webpack5] Interactive mode breaks `--json` flag

### ISSUE THREAD

**Issue by Domiii** [webpack/webpack#11761]
# Bug report

**What is the current behavior?**

If I input an invalid option or otherwise make `webpack` have doubts, it will go into interactive mode and ask me for feedback.

E.g.:
`npx webpack --no-color --json --verbose > stats.json  # invalid verbose option`

writes something like this to `stats.json`:

> [?25l[36m?[39m [1mWhich flags do you want to use?[22m [2m…[22m 
>[2m[90m✔[39m[22m [36m[4m--entry: The entry point(s) of your application e.g. ./src/main.js[24m[39m
> [2m[90m✔[39m[22m --config: Provide path to a webpack configuration file e.g. ./webpack.config.js
> [2m[90m✔[39m[22m --color: Enable/Disable colors on console

(Note that it even has colors, which I explicitely disabled.)

**What is the expected behavior?**

`--json` should always have JSON-structured output, nothing else.

**Possible Workarounds**

If in interactive mode, you might want to use error-out instead, or just entirely disable interactive mode, or allow a config option to disable it.

**Other relevant information:**

webpack version:  5.1.3
Node.js version: 12.*
Operating System: MacOS
Additional tools: -

**Comment by evilebottnawi** [comment]
Please update `webpack-cli` to the latest version

**Comment by evilebottnawi** [comment]
Also you need to fix flags, please look at the error message

**Comment by Domiii** [comment]
@evilebottnawi Your swift reply is greatly appreciated!

However, the problem is that I DON'T KNOW about the invalid flags, because the interactive error resolver pushed a colored output into my `stats.json` file, instead of at least sending it to `stderr`.

I'm following best practices of [`webpack-bundle-analyzer`](https://github.com/webpack-contrib/webpack-bundle-analyzer#usage-as-a-cli-utility) here.

**Comment by Domiii** [comment]
However, now testing it one more time, and it appears that webpack-cli at least shows the first line on `stderr`, however Lerna gobbled that up.

I guess, that should be sufficient here.

Again, thanks for the fast reaction time!
