### ISSUE TITLE
Webpack 5 doesn't support extended globs in the sideEffects field

### ISSUE THREAD

**Issue by jsnajdr** [webpack/webpack#11779]
# Bug report

**What is the current behavior?**
When a `package.json` specifies `sideEffects` field with filename-matching globs that use the [extended glob syntax](https://www.linuxjournal.com/content/bash-extended-globbing):
```
"sideEffects": [
  "dist/(esm|cjs)/init.js"
]
```
or
```
"sideEffects": [
  "!(dist/api/**)"
]
```
then webpack doesn't match the files that should the globs: it interprets the `!` and `()` characters as regular characters, not as a special syntax.

**What is the expected behavior?**
In webpack 4, the extended glob syntax used to be supported.

The change was introduced in #9141, when switching from `micromatch` to `glob-to-regexp`, a smaller but much less powerful library. The PR describes the breaking change as "probably some weird patterns are different" which I think is not a good description of removing a whole class of glob patterns.

The `(esm|cjs)` syntax can be replaced by `{esm,cjs}`, there is no replacement for `!` except converting to a list of "positive" globs.

I think it's OK to say that the extended glob syntax is no longer supported and document it. But a `package.json` field like `sideEffects` that should be in theory bundler-agnostic would deserve some precise specification of what is allowed or not.

**Other relevant information:**
webpack version: 5.1.3

**Comment by evilebottnawi** [comment]
I think `glob-to-regexp` should supports this patterns

**Comment by jonschlinkert** [comment]
try `"!**/dist/api/**"` or `"!dist/api/**"`

**Comment by sokra** [comment]
Negative patterns are not supported. Be positive...

I feel ok that only simple patterns are supported. Supporting a too wide range of patterns was a mistake. That only lead to inconsistencies between tooling. Restricting to simple patterns is good.

But we should improve the documentation about what's supported.

**Comment by samal-rasmussen** [comment]
Not sure if I should file a new bug for this as it is also an issue caused by glob-to-regexp.

But adding a regex to the config.devServer.watchOptions.ignored list also trips glob-to-regexp with `throw new TypeError('Expected a string');`.

I now see that `config.devServer.watchOptions` is deprecated and I should use `config.watchOptions` instead. It has a type of `string | RegExp | string[]`, so the previous list of regexes does not pass the type checker any more when using this instead. I think some info on this could be to the migration documentation.

**Comment by evilebottnawi** [comment]
@samal-rasmussen update webpack to latest version, and this problem is different

**Comment by samal-rasmussen** [comment]
> update webpack to latest version, and this problem is different

I updated webpack to the latest this morning. That's when I got this issue.

**Comment by evilebottnawi** [comment]
@samal-rasmussen please do not spam in the not related issue, you still use old version, `yarn upgrade --latest` is not upgrade major release

> The upgrade --latest command upgrades packages the same as the upgrade command, but ignores the version range specified in package.json . 

https://classic.yarnpkg.com/en/docs/cli/upgrade/

**Comment by samal-rasmussen** [comment]
> @samal-rasmussen please do not spam in the not related issue, you still use old version, `yarn upgrade --latest` is not upgrade major releases

`yarn upgrade --latest` did upgrade webpack from 4 to 5.

I'd love to move this discussion to a new issue if you want. I wouldn't want to do a DenverCoder9: [https://xkcd.com/979/](https://xkcd.com/979/)

**Comment by evilebottnawi** [comment]
@samal-rasmussen no need to new issue, webpack@5 provide own types, so you don't need `@types/webpack`, please read how typescript work before using it

**Comment by samal-rasmussen** [comment]
> webpack@5 provide own type

The migration guide doesn't say that you need to remove @types/webpack when you upgrade in order to get the new v.5 types. If I saw the right types then I would have been able to figure out why I was getting errors with glob-to-regexp, and I wouldn't have come here.

**Comment by evilebottnawi** [comment]
@samal-rasmussen https://webpack.js.org/migrate/5/#changes-to-internals, feel free to send a PR with improvements
