### ISSUE TITLE
DeprecationWarning: SingleEntryPlugin was renamed to EntryPlugin - ReactJS start/build

### ISSUE THREAD

**Issue by advanceddev** [webpack/webpack#11776]
Hi there! After update to **webpack v5.1.3** I have a deprecation warning when i run **start** or **build** ReactJS script.

ReactJS has been ejected and i didn't find any **SingleEntryPlugin** import in webpack configuration file.

**Comment by evilebottnawi** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Please read changelog
