### ISSUE TITLE
DeprecationWarning: SingleEntryPlugin was renamed to EntryPlugin - ReactJS start/build

### ISSUE THREAD

**Issue by advanceddev** [webpack/webpack#11777]
# Bug report

**What is the current behavior?**

When i run **start** or **build** reactjs script i have: 
DeprecationWarning: SingleEntryPlugin was renamed to EntryPlugin

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Eject create-react-app 
2. Update webpack from **v.4.42.0** to **v.5.1.3**
3. Run **npm start** or **npm run build**

**What is the expected behavior?**

The launch of the ReactJS dev server was expected.

**Other relevant information:**
webpack version:  5.1.3
Node.js version: 13.13.0
Operating System: OS X El Captain v.10.11.6
Additional tools: -

**Comment by evilebottnawi** [comment]
Fix the deprecation, answer in the deprecation message:
```
DeprecationWarning: SingleEntryPlugin was renamed to EntryPlugin
```

**Comment by evilebottnawi** [comment]
You need to report about this to `create-react-app`, sorry, we can't fix it on our side
