### ISSUE TITLE
From 1.9.10 to 1.9.11: Webpack dev server does not load main js

### ISSUE THREAD

**Issue by alansouzati** [webpack/webpack#1177]
Hi,

  Great job on webpack, our tool has webpack as the backbone of the developer environment and it is being extremely helpful. 

  I've just updated from 1.9.10 to 1.9.11 and, after that, I cannot get my webpack-dev-server to work. There is no issue in the logs and the main entry point is not invoked anymore.

  If I fallback to 1.9.10 everything is working fine again. 

  I'm trying to investigate what's going on, if you can give me any pointers I can try to send a PR myself.

Alan

**Comment by alansouzati** [comment]
Ok, I can't give up on this.

I was evaluating the webpack bundles and I saw that most of the modules are now gone for 1.9.11.

I see that you've changed from an array to object keys. Everything goes well from 0, 1, 2 and then suddenly jumps to 203.

Any extra pointers would be much appreciated.

**Comment by alansouzati** [comment]
Ok, my again. 

I was able to find a fix for this, not sure if it is the final solution.

For webpack 1.9.10 my entry config was something like this:

```javascript
var webpackConfig = {
  ...
  entry: {
    app: ['webpack/hot/dev-server', './main.js'],
    styles: ['webpack/hot/dev-server', './main.scss']
  },
  ...
}
```
Without `styles` key in the entry, changes in `./main.scss` would **not** trigger the hot reloading.

It seems that 1.9.11 is not happy about this extra key. Removing this key works for me and changes in `./main.scss` does trigger the hot reloading for this new version. So, now my config is somehow like this:

```javascript
var webpackConfig = {
  ...
  entry: {
    app: ['webpack/hot/dev-server', './main.js']
  },
  ...
}
```

I'm not sure why this is happening though. And took me quite a while to figure this out (no debugging messages of any kind). I had to manually evaluate the generated webpack bundle. Are we not supposed to have multiple entries?

**Comment by sokra** [comment]
You can use multiple entries, if you have `[name]` or similar in `output.filename`.

But it makes more sense to add the styles to the first entry point:

``` js
  entry: {
    app: ['webpack/hot/dev-server', './main.js', './main.scss']
  },
```

In 1.9.11 there was a change in how CLI arguments were handled. Maybe there is something weird in your webpack command line call.

**Comment by alansouzati** [comment]
I'm using webpack with gulp. The gulp plugin that I use is [webpack](https://www.npmjs.com/package/webpack). So, I'm not invoking the CLI directly. 

If I move the scss declaration to be inside `app` entry, everything works fine. So, I'm fine closing the issue. But the question which remains unanswered is: Why it worked in 1.9.10 and it is not working with 1.9.11? Also, if there was a breaking change in the API, does it make sense to be 1.10.0 instead ?

All the best..

**Comment by bebraw** [comment]
@alansouzati Can you try against the current version?
