### ISSUE TITLE
StringDecoder.write method doesn't accept TypedArray argument

### ISSUE THREAD

**Issue by xiaohong14** [webpack/webpack#11783]
# Bug report
StringDecoder.write function accepts Buffer or TypedArray argument in Node.js according to [their docs](https://nodejs.org/api/string_decoder.html). And it really works when I pass a Uint16Array object.
But the string_decoder.js bundled by webpack doesn't accept TypedArray argument, it seems only accept Buffer argument.

**What is the current behavior?**
If we pass a Uint16Array argument to StringDecoder.write function, I get following error:
```
TypeError: buf.copy is not a function
    at StringDecoder.push../node_modules/string_decoder/lib/string_decoder.js.StringDecoder.fillLast (string_decoder.js:165)
    at StringDecoder.push../node_modules/string_decoder/lib/string_decoder.js.StringDecoder.write (string_decoder.js:147)
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Just run the following code to reproduce:
```
const {StringDecoder} = require("string_decoder");
const utf16ledecoder = new StringDecoder("utf-16le");
utf16ledecoder.write(new Uint16Array([1, 2, 3]));
utf16ledecoder.write(new Uint16Array([1, 2, 3, 4]));
```

**What is the expected behavior?**
string_decoder.js bundled by webpack should also support TypedArray arguments.

**Other relevant information:**
webpack version:  4.44.1
Node.js version: 10.18.0
Operating System: Ubuntu 18.04
Additional tools:

**Comment by sokra** [comment]
webpack 5 drops these default polyfills.

Report the problem to the string_decoder package: https://github.com/nodejs/string_decoder
