### ISSUE TITLE
Can not import css file not exported from package.json 

### ISSUE THREAD

**Issue by 3DGISKing** [webpack/webpack#11787]
I am working on https://github.com/CesiumGS/cesium-webpack-example.
This is very simple web pack configured web app.

It works well with webpack 4(original version).
But after I update web pack version, it shows following error.

Module not found: Error: Package path ./Build/Cesium/Widgets/widgets.css is not exported from package E:\MyResearch\CesiumJsGIS\node_modules\cesium (see exports fiel
d in E:\MyResearch\CesiumJsGIS\node_modules\cesium\package.json)

In a short I could not import css file from node_module.

This is original webpack version.
![image](https://user-images.githubusercontent.com/26606704/96893508-5907f400-14bd-11eb-9712-8acf142c1267.png)

This is the updated part of the config file.
![image](https://user-images.githubusercontent.com/26606704/96893311-26f69200-14bd-11eb-9cd8-319287d2eb18.png)

**Comment by evilebottnawi** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

**Comment by evilebottnawi** [comment]
Expected, because https://github.com/CesiumGS/cesium/blob/master/package.json#L35, css is not exported for other packages

**Comment by evilebottnawi** [comment]
https://github.com/webpack/webpack/issues/11467#issuecomment-708871353, but I **strongly don't recommend** to do this

**Comment by 3DGISKing** [comment]
so what is the solution?

**Comment by evilebottnawi** [comment]
Solutions:
- open an issue in repo and ask to export CSS files
- avoid using not exported CSS files and use `copy-webpack-plugin`
- Use workaround above, right now and search alternatives

**Comment by 3DGISKing** [comment]
I see. Thanks.

**Comment by trusktr** [comment]
I have this same problem with cesium. but the fullySpecified trick doesn't work:

```js
			{
				test: /\.css$/i,
				use: ['style-loader', 'css-loader'],
				exclude: /node_modules\/(?!cesium)/,
				resolve: {fullySpecified: false}, // https://github.com/webpack/webpack/issues/11787
			},
```

I still get

```
Module not found: Error: Package path ./Source/Widgets/widgets.css is not exported from package /home/trusktr/app/node_modules/cesium (see exports field in /home/trusktr/app/node_modules/cesium/package.json)
```
