### ISSUE TITLE
Missing type definition on @types/webpack package

### ISSUE THREAD

**Issue by linbudu599** [webpack/webpack#11791]
## Feature request

**What is the expected behavior?**
`@types/webpack` is missing some type definitions which are required on some plugins work, like `ModuleFileNameHelper` and `Compilation.updateAsset`, I got this problem in a [plugin file](https://github.com/sorrycc/esbuild-webpack-plugin/blob/master/src/index.ts), which is declared in webpack source type.d.ts: [ModuleFileNameHelper](https://github.com/webpack/webpack/blob/4d0db65e6409bbac90378c8104f0846c9c4e73a6/types.d.ts#L10034), [updateAsset](https://github.com/webpack/webpack/blob/4d0db65e6409bbac90378c8104f0846c9c4e73a6/types.d.ts#L1460). It seems like a common problem.

**What is motivation or use case for adding/changing the behavior?**

**type safety on plugin work**

**How should this be implemented in your opinion?**

please consider on supplementing the missing and more type definition

**Are you willing to work on this yourself?**
yes(if u give the where and how the type should be added, it's a really huge file)

**Comment by snitin315** [comment]
I think you can send a PR for exporting more types as per your need. 
Types can be exposed by adding `@typedefs` to `lib/index.js`. Run `yarn special-lint-fix` to update the typings.

**Comment by linbudu599** [comment]
Thanks a lot~
