### ISSUE TITLE
The getting-started tutorial doesn't work on windows

### ISSUE THREAD

**Issue by dotnetCarpenter** [webpack/webpack#1179]
I'm new to webpack 1.9.11 and are following the [getting-started tutorial](http://webpack.github.io/docs/tutorials/getting-started/). Unfortunately I can only get to *Binding loaders*, where I get the following error:
```
C:\Users\dotnet\Projects\playground\webpack_tut (master)
λ webpack ./entry.js bundle.js --module-bind 'css=style!css'
Hash: 3fd1ef8aa00068f12535
Version: webpack 1.9.11
Time: 52ms
    Asset     Size  Chunks             Chunk Names
bundle.js  1.72 kB       0  [emitted]  main
   [0] ./entry.js 65 bytes {0} [built] [1 error]
   [1] ./style.css 0 bytes [built] [failed]
   [2] ./content.js 47 bytes {0} [built]

ERROR in ./style.css
Module parse failed: C:\Users\dotnet\Projects\playground\webpack_tut\style.css Line 1: Unexpected token {
You may need an appropriate loader to handle this file type.
| body {
|     background: yellow;
| }
 @ ./entry.js 1:0-22
```

My entry.js:
```js
require("./style.css");
document.write(require("./content.js"));
```
My style.css:
```css
body {
    background: yellow;
}
```
`npm list --depth=0`:
```
C:\Users\dotnet\Projects\playground\webpack_tut
├── css-loader@0.14.5
├── node-libs-browser@0.5.2
└── style-loader@0.12.3
```

**Comment by dotnetCarpenter** [comment]
node -v && npm -v
v0.12.4
2.10.1

**Comment by sairion** [comment]
You need to provide which loader to use unless is widely known type, such as `.js`

like: `require("!style!css!./style.css");`

**Comment by dotnetCarpenter** [comment]
From the tutorial:
> We don’t want to write such long requires require("!style!css!./style.css");.
>We can bind file extensions to loaders so we just need to write: require("./style.css")
>update entry.js
>- require("!style!css!./style.css");
>+ require("./style.css");
>  document.write(require("./content.js"));

> Run the compilation with:
> `webpack ./entry.js bundle.js --module-bind 'css=style!css'`

But when I do `webpack ./entry.js bundle.js --module-bind 'css=style!css'` it fails.

**Comment by sairion** [comment]
@dotnetCarpenter Have you installed `style-loader` and `css-loader` as well?

**Comment by dotnetCarpenter** [comment]
@sairion yes. See the bottom of my original post.
```
C:\Users\dotnet\Projects\playground\webpack_tut
├── css-loader@0.14.5
├── node-libs-browser@0.5.2
└── style-loader@0.12.3
```

**Comment by taurose** [comment]
Try double quotes

`webpack ./entry.js bundle.js --module-bind "css=style!css"`

**Comment by Anahkiasen** [comment]
Getting exactly the same issue on Mac with node 0.12 and NPM 3, and I do have the loader defined:

```
ERROR in ./css/styles.css
Module parse failed: /Users/anahkiasen/Sites/webpack/css/styles.css Line 1: Unexpected token {
You may need an appropriate loader to handle this file type.
| body {
|   background: red;
| }
 @ ./js/app.js 1:0-30
```

```js
module.exports = {
  entry: './js/app.js',
  output: {
    path: __dirname,
    filename: 'bundle.js',
    module: {
      loaders: [
        {
          test: /\.css$/,
          loader: 'style!css',
        },
      ]
    }
  }
};
```

```js
require('./../css/styles.css');
```

**Comment by taurose** [comment]
`module.loaders` shouldn't be inside `output`

```js
module.exports = {
  entry: './js/app.js',
  output: {
    path: __dirname,
    filename: 'bundle.js',
  },
  module: {
    loaders: [
      {
        test: /\.css$/,
        loader: 'style!css',
      }
    ]
  }
};
```

**Comment by mr-cjk** [comment]
Just to chime in that I have had the same problem with `--module-bind 'css=style!css'` on Linux. If I try using double-quotes I just get a different flavour of error from bash:

`-bash: !css: event not found`

After a bit of trying I figure it is not a major problem to me right now as for my projects I am going to be loading via webpack.config.js.

**Comment by vitoyan** [comment]
same issue in ubuntu 3.16.0-14
/home/will/webpackTest
├── css-loader@0.16.0
└── style-loader@0.12.3

**Comment by Tumne** [comment]
Using single quotes worked for me. Try:

```
webpack ./entry.js bundle.js --module-bind 'css=style!css'
```

**Comment by btargac** [comment]
'css=style!css' single quotes are fine with me too

**Comment by biirus** [comment]
yep, single quotes have helped

**Comment by xdliuyong** [comment]
add webpack.config.js

```
module.exports = {
    entry: "./entry.js",
    output: {
        path: __dirname,
        filename: "bundle.js"
    },
    module: {
        loaders: [
            { test: /\.css$/, loader: "style!css" }
        ]
    }
};
```
using:  ```webpack```  or  ```webpack ./entry.js bundle.js --module-bind 'css=style!css'````    is ok

**Comment by dbashford** [comment]
+1 on single quotes.  May be worth updating the docs?

![image](https://cloud.githubusercontent.com/assets/581127/9745640/2947426a-5641-11e5-8654-ac7ec8de8b66.png)

**Comment by rakeshok** [comment]
+1

**Comment by KarlPurk** [comment]
+1 for single quotes - worked for me using Git Bash on Windows 8.

**Comment by Tumne** [comment]
Changed the Docs! Change the Docs! #ProgrammersLivesMatter

**Comment by DoneBySimon** [comment]
On OS X (10.11) using iTerm or Terminal:

Fails:

    webpack ./entry.js bundle.js --module-bind "css=style!css"
    -bash: !css": event not found

Builds:

    webpack ./entry.js bundle.js --module-bind "css=style\!css"
or

    webpack ./entry.js bundle.js --module-bind 'css=style!css'

I was about to create a PR for this, but I don't know the preferred solution.

**Comment by sirlero** [comment]
Use single quotes like this:
webpack ./entry.js bundle.js --module-bind 'css=style!css'

**Comment by mailtoharshit** [comment]
Single Quote Work but what needs be updated in webpack.config.js ? 

I run this command : webpack 

Only I renamed entry.js to index.js 

    Asset     Size  Chunks             Chunk Names
bundle.js  10.9 kB       0  [emitted]  main
chunk    {0} bundle.js (main) 8.88 kB [rendered]
    [0] ./index.js 151 bytes {0} [built] [1 error]
    [1] ./~/style-loader!./~/css-loader!./style.css 895 bytes {0} [built]
    [2] ./~/css-loader!./style.css 187 bytes {0} [built]
    [3] ./~/css-loader/lib/css-base.js 1.51 kB {0} [built]
    [4] ./~/style-loader/addStyles.js 6.09 kB {0} [built]
    [6] ./content.js 45 bytes {0} [built]

ERROR in ./style.css
Module parse failed: /Users/harshitp/Desktop/WebPack/style.css Line 1: Unexpected token {
You may need an appropriate loader to handle this file type.
| body {
|     background: yellow;
| }
 @ ./index.js 4:0-22

**Comment by mailtoharshit** [comment]
My config looks like this 


module.exports = {
	entry: "./index.js",
    output: {
        path: __dirname,
        filename: "bundle.js"
    },

	module: {
		loaders: [
			{ test: /\.css$/, loader: 'style!css'}
		]
	},
	node: {
		fs: "empty"
	}

}

**Comment by mailtoharshit** [comment]
I tried single quote as well as double in config files as well but I see this error when i run 'webpack' command - -> Output filename not configured.

**Comment by btargac** [comment]
Are those loaders installed via npm ? Style loader and css loader ?

I tried single quote as well as double in config files as well but I see
this error when i run 'webpack' command - -> Output filename not configured.

—
Reply to this email directly or view it on GitHub
<https://github.com/webpack/webpack/issues/1179#issuecomment-149092952>.

**Comment by mailtoharshit** [comment]
yes those were installed via NPM

**Comment by caser789** [comment]
+1 single quote works!

**Comment by FrankFan** [comment]
> +1 single quote works!

**Comment by amfarrell** [comment]
Single quote works for me, but I note that the docs hosted at https://webpack.github.io/docs/tutorials/getting-started/ don't show single quotes.

**Comment by bebraw** [comment]
@sokra Any idea why the online version hasn't been synced?

**Comment by villeneuve-michael** [comment]
+1 for the single quote

**Comment by JohnnyZhao** [comment]
+1 single quotes have helped on Mac

**Comment by richa3350** [comment]
Single quotes haven't worked yet for me. Running on on MAC OS X (10.10.5) 
Still getting a parse error on style.css. 

Run command - 
webpack src/entry.js bundle.js --module.bind 'css=style!css'

Result:  
Hash: 7b48b7155d8f821da49e
Version: webpack 1.12.9
Time: 53ms
    Asset     Size  Chunks             Chunk Names
bundle.js  1.79 kB       0  [emitted]  main
   [0] ./src/entry.js 131 bytes {0} [built] [1 error]
   [1] ./src/style.css 0 bytes [built] [failed]
   [2] ./src/content.js 49 bytes {0} [built]

ERROR in ./src/style.css
Module parse failed: /Users/rverma2/git/rbansal/ESS/HelloWebPack/src/style.css Line 1: Unexpected token {
You may need an appropriate loader to handle this file type.
body {
     background: yellow;
 }
 @ ./src/entry.js 3:0-22

**Comment by PoacherBro** [comment]
Single quote is not worked to me with webpack version 1.12.14, and node v4.2.2 in Windows 7.
Error message as below
```
λ webpack entry.js bundle.js --module-bind 'css=css!style'
Hash: 36de1388af70066e460d
Version: webpack 1.12.14
Time: 43ms
    Asset     Size  Chunks             Chunk Names
bundle.js  1.72 kB       0  [emitted]  main
   [0] ./entry.js 67 bytes {0} [built] [1 error]
   [1] ./style.css 0 bytes [built] [failed]
   [2] ./content.js 46 bytes {0} [built]

ERROR in ./style.css
Module parse failed: D:\Leo\Project\nodejs\webpack-test\style.css Line 1: Unexpected token {
You may need an appropriate loader to handle this file type.
| body {
|     background: yellow;
| }
 @ ./entry.js 1:0-22
```

**Comment by OnlyRefat** [comment]
i am having similar issue. can not solve it. anyone who faced and fixed it???

http://stackoverflow.com/questions/38669804/you-may-need-an-appropriate-loader-to-load-this-file-on-windows-with-webpack-not
