### ISSUE TITLE
[Webpack5]|code splitting] installChunk: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by Guymestef** [webpack/webpack#11799]
# Bug report

**What is the current behavior?**
When using @loadable/component library, with SSR, I get the error: 
installChunk: Cannot read property 'length' of undefined
In debug, I can see that chunk object only contains __LOADABLE_LOADED_CHUNKS__, no object modules, ids or runtime.
So it crashes on chunkIds.length

```javascript
var installChunk = (chunk) => {
	var moreModules = chunk.modules, chunkIds = chunk.ids, runtime = chunk.runtime;
	for(var moduleId in moreModules) {
		if(__webpack_require__.o(moreModules, moduleId)) {
			__webpack_require__.m[moduleId] = moreModules[moduleId];
		}
	}
	if(runtime) runtime(__webpack_require__);
	for(var i = 0; i < chunkIds.length; i++)
		installedChunks[chunkIds[i]] = 1;
};
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Using @loadable/component library in SSR mode, with a loadable component and a named import:
```javascript
const About = loadable(() => import('components/Pages/About'), {
    resolveComponent: components => components.About,
    fallback: <Spinner loading={true} size="big" className="my-2 d-flex justify-content-center" />,
});
```

**What is the expected behavior?**
importAsync component should not crash, chunk object should be filled with expected properties or installChunk should check if properties are defined if  the chunk object is well populated

**Other relevant information:**
webpack version:  5
Node.js version: 14
Operating System: Windows 10
Additional tools: @loadable/components / @loadable/server

[@loadable/component](https://github.com/gregberge/loadable-components)

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by evilebottnawi** [comment]
Please update https://github.com/gregberge/loadable-components/releases/tag/v5.14.0

**Comment by evilebottnawi** [comment]
Feel free to feedback if it doesn't help, also please provide reproducible test repo

**Comment by ereztaiar** [comment]
I'm also facing this issue
webpack version 4.43.0

`
const path = require('path');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const nodeExternals = require('webpack-node-externals');
const LoadablePlugin = require('@loadable/webpack-plugin')

const common = {
    module: {
        rules: [
            {
                test: /\.jsx?$/,
                exclude: /node_modules/,
                loader: 'babel-loader',
                options: {
                    presets: [
                        ['@babel/preset-env', {modules: false}],
                        '@babel/preset-react',
                    ],
                    plugins: [
                        '@loadable/babel-plugin',
                        '@babel/plugin-transform-modules-commonjs',
                        '@babel/plugin-proposal-class-properties',
                        [
                            '@babel/transform-runtime',
                            {
                                regenerator: true,
                            },
                        ],

                    ],
                },
            },
            {
                test: /\.png|jpg$/,
                exclude: [/^logo(?:192|512)\.png/, /^maskable_wof\.png$/],
                use: ['file-loader'],
            },
            {
                test: /\.css$/,
                use: ["style-loader", "css-loader"]
            },
            {
                test: /\.svg$/,
                use: [
                    {
                        loader: '@svgr/webpack',
                        options: {
                            icon: true,
                        },
                    },
                ],
            },
        ],
    },

    resolve: {
        extensions: ['.js', '.jsx', '.json', '.css'],
    },
    optimization:{
        chunkIds: 'named',
        // splitChunks: {
        //     cacheGroups: {
        //         vendor: {
        //             chunks: 'initial',
        //             name: 'vendor',
        //             test: module => /node_modules/.test(module.resource),
        //             enforce: true,
        //         },
        //     },
        // },
    },
};

const client = {
    ...common,
    target: 'web',
    mode: 'development',
    entry: {
        main: './src/index.js',
        'service-worker': './src/service-workers/index.js',
    },
    output: {
        publicPath: '/',
        globalObject: 'this',
    },
    plugins: [
        new CopyWebpackPlugin({
            patterns: [
                path.resolve(__dirname, 'src/assets', 'og_image.jpg'),
                path.resolve(__dirname, 'src/assets', 'wof-background-spots@2.png'),
                path.resolve(__dirname, 'src', 'fonts.css'),
                path.resolve(__dirname, 'src', 'style.css'),
            ],
        }),
        new LoadablePlugin({
            filename: 'client-stats.json'
        })
    ],
    devtool: 'cheap-module-source-map',
    node: {
        fs: 'empty',
        net: 'empty',
        tls: 'empty'
    }
};

const server = {
    ...common,
    target: 'node',
    mode: 'development',
    externals: [nodeExternals()],
    entry: {
        server: './src/server.js'
    },
    output: {
        publicPath: '/',
        globalObject: 'this',
    },
    plugins: [
        new LoadablePlugin({
            filename: 'server-stats.json'
        })
    ],

    devtool: 'cheap-module-source-map',
    node: {
        console: false,
        global: false,
        process: false,
        Buffer: false,
        __filename: false,
        __dirname: false

    }
};


module.exports = [  server];
`

If i add the client to the module.exports array
`module.exports = [ client, server];`
this bug happens 
i think thats happens because the target in the client is web and the one in server is node but the files should be the same
or am i wrong here somehow
