### ISSUE TITLE
Empty bundle prohibition is inconvenient for TypeScript users

### ISSUE THREAD

**Issue by andersk** [webpack/webpack#11801]
## Feature request

**What is the expected behavior?**
The `EntryItem` type should be `string[] | string`, not `[string, ...string[]] | string`.

**What is motivation or use case for adding/changing the behavior?**
The `[string, ...string[]]` type is annoying to work with in TypeScript, because it’s incompatible with almost every nontrivial way you might compute the `entry` parameter other than writing it out literally. For example, using `filter` or `map` or importing from a `.json` file all give you a `string[]`, which cannot be assigned to `[string, ...string[]]` without an unchecked cast, even if the programmer “knows” the result will be nonempty.

**How should this be implemented in your opinion?**
Either remove the relevant `"minItems": 1` from `schemas/WebpackOptions.json`, or configure `json-schema-to-typescript` with `ignoreMinAndMaxItems`.

**Are you willing to work on this yourself?**
yes

**Comment by evilebottnawi** [comment]
Yes, PR welcome
