### ISSUE TITLE
Naming web worker chunks

### ISSUE THREAD

**Issue by dfoverdx** [webpack/webpack#1180]
Forgive me if this issue should be in the `worker-loader` repository.  Poking through the code, I saw `webpack/lib/webworker` so I wasn't sure.

Is it possible to name web worker chunks like you can name chunks using a third parameter in `require.ensure()`?

I have two web workers to load and when I don't include `[hash]` in the output filename, only one gets created, or more accurately, they both get created with the same name, so only one exists at the end of compilation.  Even including `[id]`, doesn't work--they both, apparently, have an id of 0.

However, when I do include `[hash]`, every time I make a change to the code a new file is created, leaving my output folder full of old versions of the worker file.  Periodically deleting all the output is quite annoying.

Thanks!

**Comment by sirlancelot** [comment]
It doesn't appear to be documented at [code splitting](https://webpack.github.io/docs/code-splitting.html#require-ensure), but I've been doing this for a while. Just pass a string as the third parameter to `require.ensure` like so:

    require.ensure([], function() { var tmp = require("some-module"); }, "page/some-module");

You can put slashes in the string and it will create subfolders. You have to make sure that your `output.chunkFilename` contains `"[name]"` somewhere in it and that will get replaced with the name that you pass in.

**Comment by dfoverdx** [comment]
I think I mispoke.  For loading workers, I'm not using `require.ensure()`.  I don't want to get into an async mess, so I'm doing a simple 

    import myWorker from 'worker!./myWorker.js';

**Comment by iMoses** [comment]
+1

**Comment by bebraw** [comment]
@dfoverdx Safe to close?

**Comment by hawkrives** [comment]
https://github.com/webpack/worker-loader/issues/5
> […] It is now possible to specify the name in the loader query.
