### ISSUE TITLE
Hooks to implement chunk retry on failed downloads

### ISSUE THREAD

**Issue by salzhrani** [webpack/webpack#11816]
## Feature request

**What is the expected behavior?**
Be able to intercept async load failures and retry by recreating the script tag with cache busted url

**What is motivation or use case for adding/changing the behavior?**
We found that retrying the download with the use of cache busting params is very effective, and we could not find a way to utilize it correctly. existing plugins replace the jsonp loading code which is not possible with version 5, causing the need to duplicate the logic and patch it to use the duplicated code instead of the original

**How should this be implemented in your opinion?**
Either expose a way to be able to add search params for the purpose of cache busing in user land. or add a hook to augment the `loadingEnded` function in jsonp runtime

**Are you willing to work on this yourself?**
yes, with guidance from a contributer

**Comment by sokra** [comment]
Try something like this:

``` js
const old = __webpack_get_script_filename__;
const hasFailed = new Set();
__webpack_get_script_filename__ = (chunkId) => {
  const filename = old(chunkId);
  if (hasFailed.has(chunkId))
    return filename + "?" + Math.random();
  return filename;
};

const old2 = __webpack_chunk_load__;
__webpack_chunk_load__ = (chunkId) => {
  const result = old2(chunkId);
  return result.catch(err => {
    hasFailed.add(chunkId);
    // you may add automatic retry here
    throw err;
  });
}
```

Note that this would break prefetching as urls are not identical, but this might not apply in your case.

**Comment by salzhrani** [comment]
Thank you for your assistance

**Comment by 2heal1** [comment]
> Try something like this:
> 
> ```js
> const old = __webpack_get_script_filename__;
> const queryMap = new Map();
> __webpack_get_script_filename__ = (chunkId) => {
>   const filename = old(chunkId);
>   return filename + (queryMap.get(chunkId) || "");
> };
> 
> const old2 = __webpack_chunk_load__;
> __webpack_chunk_load__ = (chunkId) => {
>   const result = old2(chunkId);
>   return result.catch(err => {
>     queryMap.set(chunkId, "?" + Math.random());
>     // you may add automatic retry here
>     throw err;
>   });
> }
> ```
> 
> Note that query should be constant when no error occurs to not break prefetching, etc. which also use the filename

Is available for webpack@4 ?

**Comment by 2heal1** [comment]
> Try something like this:
> 
> ```js
> const old = __webpack_get_script_filename__;
> const queryMap = new Map();
> __webpack_get_script_filename__ = (chunkId) => {
>   const filename = old(chunkId);
>   return filename + (queryMap.get(chunkId) || "");
> };
> 
> const old2 = __webpack_chunk_load__;
> __webpack_chunk_load__ = (chunkId) => {
>   const result = old2(chunkId);
>   return result.catch(err => {
>     queryMap.set(chunkId, "?" + Math.random());
>     // you may add automatic retry here
>     throw err;
>   });
> }
> ```
> 
> Note that query should be constant when no error occurs to not break prefetching, etc. which also use the filename

@sokra  hi , I wonder it's available for webpack@4 ?
