### ISSUE TITLE
browserslist  ie 11 show a problem 

### ISSUE THREAD

**Issue by scdmn** [webpack/webpack#11814]
**What is the current behavior?**

       var chunkLoadingGlobal = this["webpackChunknews_app"] = this["webpackChunknews_app"] || [];
        /******/
        var parentChunkLoadingFunction = chunkLoadingGlobal.push.bind(chunkLoadingGlobal);
        /******/
        chunkLoadingGlobal.push = webpackJsonpCallback;

    The code above reports an error ， TypeError: Cannot read property 'webpackChunknews_app' of undefined

**If the current behavior is a bug, please provide the steps to reproduce.**

When I use the ModuleFederationPlugin to package, if the browserslist of package.json was set to ie 11, the compiled file changes from an arrow function to an ordinary function. the "this" in the compiled file mean to pointed the window, but it is undefined in the ordinary function.

**What is the expected behavior?**

“this” point to the window object,when browserslist set to ie11.

**Other relevant information:**
webpack version:  5.2.0
Node.js version: 12.17.0
Operating System:  mac os 10.15.4
Additional tools:

**Comment by sokra** [comment]
should be fixed by #11886 
released in 5.4.0
