### ISSUE TITLE
[Webpack 5] Modules from internal library cannot be loaded when using mode: development (work in production)

### ISSUE THREAD

**Issue by JonWallsten** [webpack/webpack#11827]
# Bug report

**What is the current behavior?**
Modules from internal library (also built with Webpack) is missing all exports and is missing from `__webpack_modules__` when building with `mode: development`. 
The same code works and the page is loading fine when building with `mode: production` and serving dist.

It seems like the dist bundle file is never "expanded" in `__webpack_modules__`.
If you look at the image you'll see that the bundle is an entry in `__webpack_modules__`, but the exported modules from said file is not appearing in the list when checking. The list consists om a bunch of modules from node_modules and the modules from the application using the library.
![image](https://user-images.githubusercontent.com/5993909/97200424-7edd1380-17b1-11eb-9847-e0d8daae7cdd.png)

So when it looks for the module in `__webpack_modules__` it will end up with `undefined`.
```javascript
__webpack_modules__[moduleId].call(module.exports, module, module.exports, __webpack_require__);
```
That will cause the following error:
```
Uncaught TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (main.js:2793)
    at eval (index.ts:30)
    at Object../src/index.ts (index.js:2168)
    at __nested_webpack_require_8364606__ (index.js:5397)
    at eval (index.js:5436)
    at eval (index.js:5437)
    at webpackUniversalModuleDefinition (index.js:11)
    at eval (index.js:18)
    at Object.../web-lib-core/dist/index.js (lib.js:87)
    at __webpack_require__ (main.js:2793)
```
The module is also missing all exports:
![image](https://user-images.githubusercontent.com/5993909/97201046-42f67e00-17b2-11eb-9b1d-f06b1302d33e.png)

The code is present in the dist file (i have removed the contents):
```javascript
/***/ "./src/metadata/oasbasicmetadataextensions.class.ts":
/*!**********************************************************!*\
  !*** ./src/metadata/oasbasicmetadataextensions.class.ts ***!
  \**********************************************************/
/*! flagged exports */
/*! export OasBasicMetadataTypeExtensionBase [provided] [no usage info] [missing usage info prevents renaming] */
/*! export __esModule [provided] [no usage info] [missing usage info prevents renaming] */
/*! other exports [not provided] [no usage info] */
/*! runtime requirements: __webpack_exports__, __webpack_require__ */
/***/ ((__unused_webpack_module, exports, __webpack_require__) => {

"use strict";
eval("\r\nObject.defineProperty(exports, \"__esModule\", ({ value: true }));\r\nexports.OasBasicMetadataTypeExtensionBase = void 0;\r\nvar tslib_1 = __webpack_require__(/*! tslib */ \"../../node_modules/tslib/tslib.es6.js\");\r\nvar utils_1 = __webpack_require__(/*! ../utils */ \"./src/utils/index.ts\"); var OasBasicMetadataTypeExtensionBase = /** @class */ (function () {\r\n    function OasBasicMetadataTypeExtensionBase(type, typeRef) {...}\r\nexports.OasBasicMetadataTypeExtensionBase = OasBasicMetadataTypeExtensionBase;//# sourceURL=webpack-internal:///./src/metadata/oasbasicmetadataextensions.class.ts\n");

/***/ })
```

**Config files:**
https://gist.github.com/JonWallsten/69c82a3eb7688cae285f9034a8699f5b

**If the current behavior is a bug, please provide the steps to reproduce.**

I will work on a repro, but we have a large complex monorepo with a lot of sensitive information. Will update issue when I have created a similar repo with minimal code.

**What is the expected behavior?**
Modules from our internal library, also built with Webpack, should be found in `__webpack_modules__` and the site should load just fine like it does with `mode: production`.

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

**Comment by evilebottnawi** [comment]
How you run webpack?

**Comment by evilebottnawi** [comment]
webpack-dev-server don't support libraries yet

**Comment by JonWallsten** [comment]
> How you run webpack?

I use `webpack serve` as per this issue: https://github.com/webpack/webpack-dev-server/issues/2759
But the same issue occur if I build a development build with Webpack and then use a third party package for serving the dist.
``` 
"build:dev": "node --max_old_space_size=8192 ../../node_modules/webpack/bin/webpack --config config/webpack.dev.ts --color"
```

> webpack-dev-server doesn't support libraries yet

So I can't import modules from another bundle built with Webpack? Or is library something else in this context?

I'll work on a repro.

**Comment by evilebottnawi** [comment]
> So I can't import modules from another bundle built with Webpack? Or is library something else in this context?

No, you can, we should fix it, but maybe it is not related to your problem, yep, will be great to look at repo

**Comment by JonWallsten** [comment]
> No, you can, we should fix it, but maybe it is not related to your problem, yep, will be great to look at repo
Yeah, it's a guessing game without a repro. Was hoping someone had had the same issue and could point in the right direction. But I'll continue with the repro. It might be done tonight or tomorrow morning.

**Comment by JonWallsten** [comment]
I've created a repo now by removing most of our code but leaving the structure. One thing that differ though is that in my repro the web-lib-core library is completely missing `__webpack_require__` for some reason. That is not happening in our app right now. So to get to the real problem I need help with understandning why this is happening.
Close this repo: 
https://github.com/JonWallsten/monorepo-new/tree/angular%2Bwebpack-upgrade
I sent you an invite since it's private. Create an issue with any questions about installing/running. I'll answer as fast as I can.

**Comment by Birch-san** [comment]
@JonWallsten I think you're running into the same issue we encountered. Another minimal repro and findings here: https://github.com/webpack/webpack/issues/11277.

**Comment by evilebottnawi** [comment]
Sorry for delay, look at this tomorrow

**Comment by JonWallsten** [comment]
> Sorry for delay, look at this tomorrow

No stress at all man!

**Comment by evilebottnawi** [comment]
Yes, duplicate #11277, let's close, we are working on fixing
