### ISSUE TITLE
Webpack-5 filesystem cache not detects changed files

### ISSUE THREAD

**Issue by vbartusevicius** [webpack/webpack#11820]
# Bug report

**What is the current behavior?**
The changes in the project's source-tree are not detected with the following config:
```js
config.cache = {
    type: 'filesystem',
    cacheDirectory: `${cacheDirectory}/webpack`,
    buildDependencies: {
        config: [__filename],
    },
};
```

**If the current behavior is a bug, please provide the steps to reproduce.**
https://github.com/vbartusevicius/webpack-5-persistent-cache

**What is the expected behavior?**
Webpack should see the changed files in source-tree and recompile what's needed.

**Other relevant information:**
webpack version:  5.1.2
Node.js version: v12.18.3
Operating System: Linux valentas 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Additional tools: n/a

**Comment by sokra** [comment]
`__filename` is a node.js variable that gives the filename of the current file. If you place this code in a nested file only this file will be added to the buildDependencies and not the top-level file.

`__filename` must be placed in the top-level webpack config.

In your case it probably make sense to pass it from the top-level config:

``` diff
 // webpack.config.js
 const fullPath = "\/home\/valentas\/Projects\/webpack-5-persistent-cache";
 
 module.exports = require(`${fullPath}\/app\/config\/webpack.config.js`)({
+    "config": __filename,
     "entry": {
         "style-97d6614bde722784c18a56c668d3e0090ddd8302": `${fullPath}\/src\/index.js`,
     },
```

``` diff
 // app/config/webpack.config.js
        config.cache = {
            type: 'filesystem',
            cacheDirectory: `${cacheDirectory}/webpack`,
            buildDependencies: {
                config: [
-                   __filename,
+                   options.config,
                ],
            },
        };
```

**Comment by vbartusevicius** [comment]
@sokra - did what you recommended, still, the issue remains. If I understand correctly, the guide (https://github.com/webpack/changelog-v5/blob/master/guides/persistent-caching.md) tells that it should compare the snapshots, and other fancy stuff to find the changed tree.

**Comment by evilebottnawi** [comment]
You have to put all build files to `buildDependencies` and `webpack.config.js` and `app/config/webpack.config.js` in your case

**Comment by evilebottnawi** [comment]
Try to set `cache: false` and you will have the same problem, I think something wrong on babel side :confounded:

**Comment by vbartusevicius** [comment]
The problem is here:
```js
// app/config/webpack.config.js

filename: BUILD ? '[name].js?[contenthash]' : '[name].bundle.js',`
```

with `[name].js?[contenthash]` it does not work, but with `[name].bundle.js` - everything is fine.

**Comment by evilebottnawi** [comment]
Yep, looking at this

**Comment by evilebottnawi** [comment]
Yes, it is interesting case/bug, we do not look at source code if it is `immutable` file (i.e filename `contenthash`), but you have  `contenthash` in query and no query on filesystem

**Comment by vbartusevicius** [comment]
Having `?[contenthash]` helps us to temporary keep the old files between releases for users, who have not refreshed the page yet.

**Comment by evilebottnawi** [comment]
Honestly, using `[contenthash]` for query is real not good idea, but it, anyway we should fix it

**Comment by sokra** [comment]
ah I see... that's a problem

**Comment by vbartusevicius** [comment]
Do you have any idea when it could be in a release?

**Comment by evilebottnawi** [comment]
@vbartusevicius Already released https://github.com/webpack/webpack/releases/tag/v5.2.1
