### ISSUE TITLE
Watch mode rebuilds due to "missing" invalid files

### ISSUE THREAD

**Issue by Knagis** [webpack/webpack#11823]
# Bug report

This might be issue for [source-map-loader](https://github.com/webpack-contrib/source-map-loader/issues) instead, please let me know if it must be moved. But for me it seems that there could be generic solutions possible at webpack/watchpack level that would work around the source-map-loader problem as well.

Running webpack in watch mode results in immediate rebuild once due to files that the watchpack report as initial-missing due to them being present in source maps.

Examples:
* URLs like `webpack://videojs/./node_modules/classnames/index.js`
* From react-draggable@4.2.0 source maps where the source maps do not match actual files in the package
  * `proj\node_modules\react-draggable\build\lib\DraggableCore.js`
  * `proj\node_modules\react-draggable\build\external {"commonjs":"react-dom","commonjs2":"react-dom","amd":"react-dom","root":"ReactDOM"}`
  * `proj\node_modules\react-draggable\build\external {"commonjs":"react","commonjs2":"react","amd":"react","root":"React"}`

**What is the current behavior?**

Watch rebuilds once

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/Knagis/webpack-11823

```
yarn
yarn webpack --watch
```

**What is the expected behavior?**

No rebuild unless files change.

**Other relevant information:**
webpack version:  5.2.0
Node.js version: 12.13.1
Operating System: 
Additional tools: source-map-loader@1.1.1

**Comment by evilebottnawi** [comment]
You miss `If the current behavior is a bug, please provide the steps to reproduce.`, please fix it and I will reopen

**Comment by Knagis** [comment]
@evilebottnawi added

**Comment by evilebottnawi** [comment]
Yes, it is bug on source-map-loader, we should not add broken utils for wathing

**Comment by evilebottnawi** [comment]
@webpack-bot move to webpack-contrib/source-map-loader
