### ISSUE TITLE
webpack-5 Nested tree-shaking is not working

### ISSUE THREAD

**Issue by sunginHwang** [webpack/webpack#11821]
# Bug report

**What is the current behavior?**
* example code 
```js
// inner.js
export const a = 1;
export const b = 2;

// module.js
export * as inner from './inner';

// index.js
import * as module from './module';

console.log(module.inner.a);
```

* webpack.config.js
```js
const path = require('path');

module.exports = {
  entry: './src/index.js',
  output: {
    filename: 'main.js',
    path: path.resolve(__dirname, 'dist'),
  },
  mode: 'production',
  optimization:{
    minimize: false, 
  }
};

```

* webpack output file
![image](https://user-images.githubusercontent.com/13899553/97155090-2b21f880-17b8-11eb-9bd2-d01c5fc29503.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
i expected remove b. like this document
![스크린샷 2020-10-26 오후 6 23 22](https://user-images.githubusercontent.com/13899553/97155263-6fad9400-17b8-11eb-91f9-87e069f38f48.png)

but the b was not removed from my outputFile. why b is not removed..? help.. plz

**Other relevant information:**
webpack version:  5.2.0
Node.js version: v12.16.3
Operating System: macOS Mojave(10.14.6)
Additional tools:

**Comment by vankop** [comment]
with `optimization.minimize = true` dead code will be eliminated.

**Comment by evilebottnawi** [comment]
Yes, minimizer remove dead code, you should not disable this for production mode, Answer above

**Comment by sunginHwang** [comment]
@vankop , @evilebottnawi  thank you ~!!!!

**Comment by dmnsgn** [comment]
Does nested tree shaking also works for CommonJS? From my initial testing, a CJS node module `require`d inside a `require`d file will include all exports from said node module.

**Comment by nyngwang** [comment]
@dmnsgn: No. But it's still possible to be done in that case :) There are tricks.
