### ISSUE TITLE
Accept PayPal Donations on webpack.js.org

### ISSUE THREAD

**Issue by Lonniebiz** [webpack/webpack#11834]
Why doesn't webpack.js.org also accept donations via PayPal?:
https://opencollective.com/webpack/donate

Donation pages should conform to the convenience the donator. There's no telling how many people have not followed through with their intention of donating simply because they didn't immediately see a PayPal option.

Having to setup an account with another 3rd party (while one already has a relationship with paypal) certainly hinders some donations. Since providing a PayPal donation link is [easy](https://paypal.me/LonnieBest ); it seem like you'd provide a PayPal option alongside the preferred option that is currently showcased.

**Comment by sokra** [comment]
There is an paypal option on opencollecti ve

**Comment by Lonniebiz** [comment]
@sokra That's good; they should showcase that prominently, because I don't see a paypal logo [here](https://opencollective.com/webpack/donate) among the other logos showcased.

Even still, every additional step required to make a donation will reduce the number of donations completed. Online marketers are familiar with this concept. If someone has a paypal account, they are accustom to making donations in 2 steps and do not enjoy going through yet another 3rd party to accomplish that.

I say continue making OpenCollective the default option, but you'll be surprised on how many additional donations a [direct paypal link](https://paypal.me/LonnieBest ) (that circumvents 3rd party sign up) will bring.

**Comment by evilebottnawi** [comment]
@Lonniebiz These are our sponsors, not a donation methods, sorry we cannot just accept money because it is taxed, so we use open collective https://opencollective.com/webpack, we made it as simple as possible

**Comment by Lonniebiz** [comment]
@evilebottnawi Oh, I see. I thought that was some list of payment methods accepted by OpenCollective.

However, this misconception is beside my point that "less steps equal more donations". I think you're losing some donations without a direct paypal button. Maybe it is worth it. Not my call.

**Comment by evilebottnawi** [comment]
> In my opinion, the best way to do it is to have a bullet list of accepted donation methods. This way, the donator is one click away from doing the method they prefer (without creating an account somewhere else first).

But there we can get a tax problem :disappointed: I think open collective repo it is the best places for asking UX improvements, but yes, maybe we should improve this on our site too

**Comment by Lonniebiz** [comment]
Interesting. For some reason I thought webpack was a non-profit organization and didn't realize there were any taxes on charitable donations. Maybe, I think know things, but I don't :)
