### ISSUE TITLE
installed webpack-cli will output a error while process exit

### ISSUE THREAD

**Issue by yinsang** [webpack/webpack#11836]
# Bug report
When webpack is installed but webpack-cli is not . After put yes to shell, at last it will install webpack-cli ,but still output an error to shell .

**What is the current behavior?**
➜  react-babel-study npm run test

> react-babel-study@1.0.0 test /Users/weiyinpeng/Documents/study-code/react-babel-study
> npm uninstall webpack-cli && npm run webp

npm WARN react-babel-study@1.0.0 No description
npm WARN react-babel-study@1.0.0 No repository field.

audited 263 packages in 2.183s

23 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> react-babel-study@1.0.0 webp /Users/weiyinpeng/Documents/study-code/react-babel-study
> webpack

{
  name: 'webpack-cli',
  package: 'webpack-cli',
  binName: 'webpack-cli',
  installed: false,
  url: 'https://github.com/webpack/webpack-cli'
}
CLI for webpack must be installed.
  webpack-cli (https://github.com/webpack/webpack-cli)

We will use "npm" to install the CLI via "npm install -D".
Do you want to install 'webpack-cli' (yes/no): y
Installing 'webpack-cli' (running 'npm install -D webpack-cli')...
npm WARN react-babel-study@1.0.0 No description
npm WARN react-babel-study@1.0.0 No repository field.

+ webpack-cli@4.1.0
added 43 packages from 26 contributors and audited 306 packages in 17.752s

28 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

Error: Cannot find module 'webpack-cli'
Require stack:
- /Users/weiyinpeng/Documents/study-code/react-babel-study/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at /Users/weiyinpeng/Documents/study-code/react-babel-study/node_modules/webpack/bin/webpack.js:120:5
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/weiyinpeng/Documents/study-code/react-babel-study/node_modules/webpack/bin/webpack.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-babel-study@1.0.0 webp: `webpack`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-babel-study@1.0.0 webp script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/weiyinpeng/.npm/_logs/2020-10-27T11_34_52_522Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-babel-study@1.0.0 test: `npm uninstall webpack-cli && npm run webp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-babel-study@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/weiyinpeng/.npm/_logs/2020-10-27T11_34_52_548Z-debug.log

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

expect no error while exit

I will pull a request about to resolve  this problem .
https://github.com/webpack/webpack/pull/11838
It's because of require('webpack-cli') push an error to stack and it output after process exit.
**Other relevant information:**
webpack version:  5.2.0
Node.js version: v14.13.1
Operating System: mac
Additional tools:

**Comment by evilebottnawi** [comment]
You problem is not readable, sorry

**Comment by evilebottnawi** [comment]
If you want to run webpack using CLI, you **need** to install webpack-cli

**Comment by yinsang** [comment]
> If you want to run webpack using CLI, you **need** to install webpack-cli

when I have not a webpack-cli ,webpack bin notice me I need install webpack,
after I put 'yes' ,webpack-cli is installed successfully, but still output a error about `require('webpack-cli')`
I just want to fix the output error.

**Comment by yinsang** [comment]
![image](https://user-images.githubusercontent.com/12373328/97299362-d18cfd00-188f-11eb-9833-b589e5b4ae4a.png)

**Comment by evilebottnawi** [comment]
Because you need to put `webpack-cli` in your package.json, no `npm`/`yarn`/etc list, you decrease performance for all developers, no body have problems with it, so something wrong with your env, please provide steps to reproduce

**Comment by yinsang** [comment]
{
  "name": "react-babel-study",
  "version": "1.0.0",
  "description": "",
  "main": "webpack.config.js",
  "scripts": {
    "w": "webpack"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@babel/core": "^7.12.3",
    "@babel/preset-env": "^7.12.1",
    "react": "^17.0.1",
    "react-dom": "^17.0.1"
  },
  "devDependencies": {
    "@babel/plugin-syntax-jsx": "^7.12.1",
    "@babel/preset-react": "^7.12.1",
    "babel-loader": "^8.1.0",
    "webpack": "^5.2.0",
    "webpack-dev-server": "^3.11.0",
    "webpack-merge": "^5.2.0"
  }
}

**Comment by evilebottnawi** [comment]
@yinsang Put `webpack-cli` in your package.json

**Comment by yinsang** [comment]
> @yinsang Put `webpack-cli` in your package.json
I know how to fix my problem.
I mean while `questionInterface.question` has put **yes**, an error is output  after 'webpack-cli' is installed.
```
Error: Cannot find module 'webpack-cli'
```

**Comment by evilebottnawi** [comment]
Please provide **all** steps to reproduce, all works fine

**Comment by yinsang** [comment]
src/index.js
```
import react from 'react'
const dom = <div></div>
```
webpack.config.js
```
{
  "name": "react-babel-study",
  "version": "1.0.0",
  "description": "",
  "main": "webpack.config.js",
  "scripts": {
    "w": "webpack -c webpack.config.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@babel/core": "^7.12.3",
    "@babel/preset-env": "^7.12.1",
    "react": "^17.0.1",
    "react-dom": "^17.0.1"
  },
  "devDependencies": {
    "@babel/plugin-syntax-jsx": "^7.12.1",
    "@babel/preset-react": "^7.12.1",
    "babel-loader": "^8.1.0",
    "webpack": "^5.2.0",
    "webpack-dev-server": "^3.11.0",
    "webpack-merge": "^5.2.0"
  }
}

```
webpack.config.js
```
module.exports = {
  module:{
    rules:[
      {
        test:/\.jsx?$/,
        exclude:/node_modules/,
        use:{
          loader:'babel-loader',
          options:{
            presets:['@babel/preset-env','@babel/preset-react'],
            plugins:['@babel/plugin-syntax-jsx']
          }
        }

      }
    ]
  }
}
```

shell:
```
npm i 
```
```
npm run w
```
you will see the error:
![image](https://user-images.githubusercontent.com/12373328/97302338-e1a6db80-1893-11eb-8223-e898800a2adb.png)

**Comment by evilebottnawi** [comment]
Weird, can't reproduce

**Comment by evilebottnawi** [comment]
Reproduced

**Comment by evilebottnawi** [comment]
Second execution is successful

**Comment by yinsang** [comment]
> Second execution is successful, only on first

Yes, it is. Because of the 'require' error in error stack. Thinking of  fix it by a way like Error.captureStackTrace.
Thanks

**Comment by evilebottnawi** [comment]
Sent PR with fix

**Comment by yinsang** [comment]
Thanks so much!
