### ISSUE TITLE
Porting assets modification plugin to V5

### ISSUE THREAD

**Issue by kubijo** [webpack/webpack#11835]
Hey.

I'm giving another shot to V5 upgrade in a more incremental way and one thing
I strugle with is porting of my plugin for assets modification.

The idea is that we are running multiple compilations of the project (one per color theme)
and I'm removing all non-css assets from all compilations except the first one.

The whole rather simple code that is working for us on V4 is here:
```javascript
function PluginOnlyCss() {
    this.hooks.shouldEmit.tap('PreventEmit', compilation => {
        Object.keys(compilation.assets).forEach(assetFileName => {
            if (/\.css$/i.test(assetFileName)) return;

            // eslint-disable-next-line no-param-reassign
            delete compilation.assets[assetFileName];
        });
    });
}
```

This however causes the deprecation warning:
```
[DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
```

I wasn't able to find good pointers that would aid me with the migration

**Comment by evilebottnawi** [comment]
Because you use invalid hook, no modification for assets on emit/beforeEmit hooks, please use this hook https://github.com/webpack/webpack/blob/master/lib/Compilation.js#L551:
```js
compiler.hooks.thisCompilation.tap(name, (compilation) => {
  const Compilation = compier.webpack.Compilation;
  
  compilation.hooks.processAssets({ name: name, stage: Compilation.PROCESS_ASSETS_STAGE_PRE_PROCESS }, (assets) => {
   // Your logic...
  })
})
```
