### ISSUE TITLE
Rewriting module paths

### ISSUE THREAD

**Issue by kastermester** [webpack/webpack#1184]
Hello,

I'm trying to setup webpack for my company's web application. So far this looks great!

One major problem I'm facing however, is that our solution requires some preprocessing of the module paths. Sometimes a given import url may resolve to one path, sometimes another, depending on what is present on the filesystem. I need this resolve process to apply in both less and js files.

I have tried writing a plugin using the `normal-module-factory`, combined with `before-resolve` plugin endpoints. However when loading less-files using the less-loader this doesn't seem to get called (the `less-loader` loader seems to be calling `resolve` on the loader itself to resolve a module to a path as far as I can tell.

For some context: Our web app is split in two parts, the `app` part and `core` part. We employ a shared core between many applications. In order to support customisation of the apps we have then, under require.js written a custom module that knows if the application has overriden the given file or not, and requires the correct implementation in.

Any pointers on how to write such a plugin? I would of course like to register the correct dependencies such that when, let's say, adding a new file in the app that should override the core implementation, webpack-dev-server will recompile the bundle. I have tried quite a few options by now I feel, however the documentation doesn't seem that clear on which endpoints to hook into IMO.

Any help would be greatly appreciated!

**Comment by mathieumg** [comment]
What about the `alias` configuration?

**Comment by kastermester** [comment]
That works for static resolutions, where `myawesomemodule` always resolves to `somepath/myawesomemodule`. My problem is that, say `myawesomemodule` exists in a folder called `app` it needs to resolve to `app/myawesomemodule` and otherwise to `core/myawesomemodule` (it is slightly more complicated than this obviously, ie. i have `group` name embedded inside the module path that also needs to be taken into account. But this example illustrates the main issue).

**Comment by kastermester** [comment]
As an example, here is the existing RequireJS module we have atm.

https://gist.github.com/kastermester/4dff3a76c4ab25c5049b

**Comment by mathieumg** [comment]
Oh, then perhaps leveraging `moduleDirectories` would be more suited?

**Comment by sokra** [comment]
``` js
resolve.root: [
  path.resolve(__dirname, "./app"),
  path.resolve(__dirname, "./core")
]
```

`require("myawesomemodule")` tries `./app/myawesomemodule` first and `./core/myawesomemodule` after that.

**Comment by bebraw** [comment]
@kastermester Did you figure it out?
