### ISSUE TITLE
Linking local npm modules

### ISSUE THREAD

**Issue by eimfach** [webpack/webpack#1185]
Since npm 2.0 you can link local npm modules in package.json:

    dependencies: {
      "core.module": "./modules/core"
    }

If you run *npm install* these modules get installed into the *node_modules* folder.
I ask myself if webpack could manage to resolve these paths and include them into the build? So one would not need to *npm install* every time changes were made on this modules ?

**Comment by sokra** [comment]
Try to add `"modules"` to `resolve`resolve.modulesDirectories`.

**Comment by eimfach** [comment]
Okay thanks, did work
