### ISSUE TITLE
Unable to produce large library bundle that can be consumed by other projects.

### ISSUE THREAD

**Issue by triforcely** [webpack/webpack#11859]
# Bug report

**What is the current behavior?**
Webpack is unable to consume library that was created from other webpack project and is built for commonjs target. It fails with "FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out 
of memory"

**If the current behavior is a bug, please provide the steps to reproduce.**
This happens with large projects, my "library bundle" is around ~7mbs which is build for SPA application with multiple Vue components.

**What is the expected behavior?**
Webpack should be able to load and use large commonjs library produced or allow the library to be split into chunks (https://github.com/webpack/webpack/issues/10878).

**Other relevant information:**
webpack version:  4.44.2
Node.js version: 10.13.0
Operating System: Windows 10
Additional tools: vue-cli-service

**Comment by evilebottnawi** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Sorry without provide this information we can help you, I will reopen when you fix it

**Comment by triforcely** [comment]
@evilebottnawi I used "other" type which doesn't provide any specific fields to fill.

**Comment by evilebottnawi** [comment]
You haven't even shown in your webpack version, problems with memory is bug, so please use the issue template for bugs

**Comment by triforcely** [comment]
> You haven't even shown in your webpack version, problems with memory is bug, so please use the issue template for bugs

Thanks, I will use bug template then.

**Comment by evilebottnawi** [comment]
@triforcely Can you try webpack@5?

**Comment by triforcely** [comment]
> @triforcely Can you try webpack@5? We are fixed a lot of memory issues, so I don't think we will fix it for webpack@4

My solution is deeply coupled with vue-cli-service which uses webpack 4. I won't be able to use webpack 5 unless they add support for it.

**Comment by evilebottnawi** [comment]
@triforcely maybe you need to open an issue in `vue-cli`, because I don't think we can fix something here

**Comment by triforcely** [comment]
@evilebottnawi Alright, thanks for you help.
