### ISSUE TITLE
Add CDN for static files

### ISSUE THREAD

**Issue by AntonGordei** [webpack/webpack#11853]
How can we add CDN to images, etc. But the scripts are loaded as before. 
How it was possible for example in webpack 4 and url-loader. 
![image](https://user-images.githubusercontent.com/49307594/97420688-b2887c80-191c-11eb-92cb-9e5000bb1015.png)

How to do it using the assets module in the webpack 5.

**Comment by evilebottnawi** [comment]
Answered, stop spamming

**Comment by AntonGordei** [comment]
@evilebottnawi Where i can check answer?
