### ISSUE TITLE
 TypeError: compiler.plugin is not a function

### ISSUE THREAD

**Issue by dubovik02** [webpack/webpack#11855]
# Bug report

**What is the current behavior?**
"build": "webpack --mode production",
"dev": "webpack serve --mode development --open --watch"
Unsuccessful builds with error: TypeError: compiler.plugin is not a function
It happened after install webpack-md5-hash.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Successful build

**Other relevant information:**
webpack version:  5.3.0
Node.js version: 12.18.3
Operating System: Win10
Additional tools: 

Files with configs: <https://github.com/dubovik02/config>

**Comment by evilebottnawi** [comment]
Please open an issue in `webpack-md5-hash` (no compatibility with webpack@5), anyway you don't need this plugin for v5, webpack do it for `mode: 'production'`
