### ISSUE TITLE
Module Federation Dynamic Import

### ISSUE THREAD

**Issue by BriceChaponneau** [webpack/webpack#11869]
# Bug report

**What is the current behavior?**
Page no rendering
`main.js` return error : `Uncaught SyntaxError: Unexpected token '!=='`

**If the current behavior is a bug, please provide the steps to reproduce.**
I have 2 apps : 
- shell : manager, head of app
- fragment: one of the multiple apps. Will be duplicated to have n apps in MFE.

**SHELL**
index.html
```
<!DOCTYPE html>
<html lang="en">
<head>
  <script src="http://localhost:3001/remoteEntry.js"></script>
</head>
<body>
  <div id="app"></div>
</body>
</html>
```

App.vue
```
<template>
  <div id="app">
    SHELL
    <compo>COME FROM FRAGMENT</compo>
  </div>
</template>

<script>
export default {
  name: "ShellApp",
  components: {
    Compo: () => import('fragment1/Compo').catch((err) => ({
        render: h => h('div', [
              h('pre', err.name),
              h('pre', err.stack)
        ])
    }))
  },
}
</script>
```

webpack.js
```
const paths = require('./paths')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const VueLoaderPlugin = require('vue-loader/lib/plugin')
const { ModuleFederationPlugin } = require("webpack").container

module.exports = {
  entry: [paths.src + '/main.js'],
  plugins: [
    new HtmlWebpackPlugin({
      title: 'Constellation',
      favicon: paths.public + '/favicon.png',
      template: paths.public + '/index.html',
      filename: 'index.html',
    }),

    new VueLoaderPlugin(),

    new ModuleFederationPlugin({
      name: "shell",
      filename: "remoteEntry.js",
      remotes: {
        // fragment1: "fragment1@http://localhost:3001/remoteEntry.js",  // WORK
        fragment1: "fragment1",                                          // DOESN'T WORK
      },
    }),
  ]
}
```

**FRAGMENT**

webpack.js
```
const paths = require('./paths')
const HtmlWebpackPlugin = require('html-webpack-plugin')
const VueLoaderPlugin = require('vue-loader/lib/plugin')
const { ModuleFederationPlugin } = require("webpack").container;

module.exports = {
  entry: [paths.src + '/main.js'],

  plugins: [
    new HtmlWebpackPlugin({
      title: 'Constellation-Fragment',
      favicon: paths.public + '/favicon.png',
      template: paths.public + '/index.html',
      filename: 'index.html',
    }),

    new VueLoaderPlugin(),

    new ModuleFederationPlugin({
      name: "fragment1",
      filename: "remoteEntry.js",
      remotes: {},
      exposes: {
        "./Compo": "@c/Compo"
      },
    })
  ]
}
```

Compo.vue
```
<template>
  <div class="compo"><slot></slot></div>
</template>

<script>
export default {
  name:"Content"
}
</script>
```

**Explanation**
When i use this line in `shell` (webpack config) and nothing import in index.html, all work fine :
`fragment1: "fragment1@http://localhost:3001/remoteEntry.js"`

I do not know in advance the url of the fragments / apps. I need to make a configuration file or write the urls directly in the `index.html`. So I change shell with 
- add script in `index.html`  : `<script src="http://localhost:3001/remoteEntry.js"></script>`
- change `webpack ` config remote : `fragment1: "fragment1"`

When I run everything I get the following error in the browser (`main.js`) : `Uncaught SyntaxError: Unexpected token '!=='`

```
/*!****************************!*\
  !*** external "fragment1" ***!
  \****************************/
/*! dynamic exports */
/*! exports [maybe provided (runtime-defined)] [no usage info] */
/*! runtime requirements: module, __webpack_require__.l, __webpack_require__.* */
/***/ ((module, __unused_webpack_exports, __webpack_require__) => {

"use strict";
var error = new Error();
module.exports = new Promise((resolve, reject) => {
	if(typeof  !== "undefined") return resolve();                               // THIS LINE
	__webpack_require__.l("fragment1", (event) => {
		if(typeof  !== "undefined") return resolve();
		var errorType = event && (event.type === 'load' ? 'missing' : event.type);
		var realSrc = event && event.target && event.target.src;
		error.message = 'Loading script failed.\n(' + errorType + ': ' + realSrc + ')';
		error.name = 'ScriptExternalLoadError';
		error.type = errorType;
		error.request = realSrc;
		reject(error);
	}, "");
}).then(() => );
```

I looked in all the examples and found nothing. Even when adapting to Vue.
https://github.com/module-federation/module-federation-examples
https://github.com/module-federation/module-federation-examples/tree/master/dynamic-system-host
https://indepth.dev/webpack-5-module-federation-a-game-changer-in-javascript-architecture/

**What is the expected behavior?**
No error and page rendering

**Other relevant information:**
webpack version:  5.1.3
Node.js version: 12.19.0
Operating System: Windows
Additional tools: Vue.js 2.6.12

**Comment by Coolpix** [comment]
Inside your webpack config, if you dont set the url into your remote name with @ you need to set library type

new ModuleFederationPlugin({
      name: "shell",
       library: { type: "var", name: "shell" }, --> THIS ONE
      filename: "remoteEntry.js",
      remotes: {
        // fragment1: "fragment1@http://localhost:3001/remoteEntry.js",  // WORK
        fragment1: "fragment1",                                          // DOESN'T WORK
      },
    }),

**Comment by BriceChaponneau** [comment]
Ok, i try immedialty.
But without set url, how shell know where is the fragment ?

**Comment by Coolpix** [comment]
> Ok, i try immedialty.
> But without set url, how shell know where is the fragment ?

Because you´re loading the remote directly from your index.html

**Comment by BriceChaponneau** [comment]
Ok but it's not dynamic so. I have to retrieve the urls of the fragments in a configuration file.

If i add dynamically a <script src... /> that does not work. Do you hnow how do that ?

**Comment by evilebottnawi** [comment]
@BriceChaponneau better ask this vue team

**Comment by Coolpix** [comment]
> Ok but it's not dynamic so. I have to retrieve the urls of the fragments in a configuration file but at runtime or in browser. Not in compilation time
> 
> If i add dynamically a <script src... /> that does not work. Do you hnow how do that ?
> 
> Does this exemple is portable to Vue 2 ? https://github.com/module-federation/module-federation-examples/tree/master/advanced-api/dynamic-remotes

Of course that way its not dynamic. Ir order to implement dynamic import you must use webpack´s api in runtime and load the remote dynamically, you can follow that example, its not framework´s related, its pure JS.

**Comment by BriceChaponneau** [comment]
I've try with library. That do not work. I have same error

**Comment by ScriptedAlchemy** [comment]
Dynamic remote can be ported to vue. Webpack doesn't care what framework is calling it. Just use the vue equivalent lifecycle hooks.

**Comment by ScriptedAlchemy** [comment]
fragment1: "fragment1"

Probably doesn't work because you're setting library manually. Which can change how the remote is referred to

**Comment by BriceChaponneau** [comment]
**Setting library**
The fragment output is : 

```
  output: {
    library: 'fragment1',
    libraryTarget: 'umd',
    umdNamedDefine: true
  },
```

What's wrong ?

**Comment by ScriptedAlchemy** [comment]
Looks right to me. I'll need to see console errors or a repo to inspect. It's something small

**Comment by BriceChaponneau** [comment]
https://github.com/BriceChaponneau/module-federation

**Comment by ScriptedAlchemy** [comment]
Try adding the library option like you have on the shell. One config has library var. one does not.

**Comment by sokra** [comment]
You can also add `remoteType: "var"`. The default is `remoteType: "script"` which requires `global@URL`.

**Comment by ScriptedAlchemy** [comment]
Yeah I've done this as well when dealing with server-side next. RemoteType likely will resolve

**Comment by BriceChaponneau** [comment]
I've update and that works. Thanks.

@ScriptedAlchemy do not understand with server-side, for dynamic ? Do you have source ?

Another thing, where can we found documentation about full config please ?
share router, share store, optimisation (export module for tree shaking...) ?

**Comment by evilebottnawi** [comment]
@sokra @ScriptedAlchemy maybe we can open an issue with module federations questions to avoid multiple issues with many questions, we even create FAQ in the top post with popular questions

**Comment by ScriptedAlchemy** [comment]
Yeah something because I've got lots of docs and code to basically anything. In some form or another. With @sokra overseeing some of this and contributing to responses, we might be able to improve samples I've had. 

I'm also getting huge traffic with similar questions on all comms platforms

**Comment by BriceChaponneau** [comment]
If you want help, let me know. You can close this issue. I put my dev on hold...

**Comment by GSingh01** [comment]
@ScriptedAlchemy awesome work on Webpack federation. 
I had question based on above, is it possible to load a remote module during runtime and then make it part of webpack module cache, so that down the stream, component can simply be accessed by using `import myComp from 'remoteLib/myComp'`;

My case is I have library project which is consumed by app1 and app2. app1 consumes app2 as well. Want to use library as a shared federated module. Given the need to deploy the solution to test and then production environment there are different URLs for each federated module per environment deployed as static site, thus leaving us only with runtime module loading as a solution.

Any help will greatly be appreciated.

Thanks again for wonderful work

**Comment by alexander-akait** [comment]
Please use `Discussion` for questions, closed due https://github.com/webpack/webpack/issues/11869#issuecomment-727178109
