### ISSUE TITLE
Incorrect conditional require `tslib` for forced common chunk

### ISSUE THREAD

**Issue by Knagis** [webpack/webpack#11863]
# Bug report

The conditional require inside a common chunk (enforced, shared by multiple entries) incorrectly skips loading of `tslib` (not sure if it is specific to just it or more generic issue).

**What is the current behavior?**

``` js
// when it fails, __webpack_require__.j == 9554

if (!/^([29]705|1743|2509|5639|5911|9554)$/.test(__webpack_require__.j)) {
var tslib_es6 = __webpack_require__(333940);
}
// EXTERNAL MODULE: ./node_modules/react/index.js
var react = __webpack_require__(989526);
// [...]
// CONCATENATED MODULE: ./packages/.../SomeReactComponent.tsx

var SomeReactComponent = /** @class */ (function (_super) {
    tslib_es6/* __extends */.ZT(SomeReactComponent , _super);
    function SomeReactComponent () {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    SomeReactComponent .prototype.render = function () {
        // [....]
    };
    return SomeReactComponent ;
}(react.PureComponent));

var SomeWrappedComponent = Wrapper/* Wrapper */.i(SomeReactComponent );

// CONCATENATED MODULE: ./packages/anothermodule.tsx
// [...]
```

**If the current behavior is a bug, please provide the steps to reproduce.**

No reproduction repository, happens in our large monorepo. All optimizations enabled (apart from minimize).

**What is the expected behavior?**

tslib is loaded for all runtimes/entries using the common chunk since it is required in module scope.

**Other relevant information:**
webpack version:  5.3.1
Node.js version: 12.13.1
Operating System:
Additional tools: tslib@1.13.0

**Comment by Knagis** [comment]
using `usedExports: "global"` "fixes" this issue.

no luck in making small reproduction...

**Comment by sokra** [comment]
Could you try some other flags too?

* `optimization.innerGraph: false`
* `optimization.concatenateModules: false`

**Comment by sokra** [comment]
Maybe you can share your repo privately with me? Seems like a good repo to find more issue related to this...

**Comment by Knagis** [comment]
I am asking my management about it. I hope it will be possible under NDA.

**Comment by evilebottnawi** [comment]
@Knagis Maybe you can found part of code what is broken?

**Comment by Knagis** [comment]
@evilebottnawi unfortunately, not yet. I am finally releasing 5.3.1 with `usedExports: "global"` to my org, fingers crossed everything will work and I will get time to research this issue in more detail. Last night I could not get the module concatenation to concat a class together with something else at all - which seems to be the key since otherwise tslib will never be made conditional require.

@sokra I got approval, should I contact you using the e-mail on your git commits?

**Comment by sokra** [comment]
> @sokra I got approval, should I contact you using the e-mail on your git commits?

yep

**Comment by sokra** [comment]
I think I found the problem. At least I found one that is very similar.

It happens when the execution order in a concatenated module is different between runtimes

**Comment by sokra** [comment]
could you try: https://github.com/webpack/webpack/pull/11873

**Comment by Knagis** [comment]
Looks like the fix is working.
