### ISSUE TITLE
Trouble using output.importFunctionName

### ISSUE THREAD

**Issue by criles25** [webpack/webpack#11860]
# Bug report

**What is the current behavior?**
I'm trying to do `output.importFunctionName: 'shimport'`, but it's not replacing the `import()` expression with `shimport()`.

**If the current behavior is a bug, please provide the steps to reproduce.**
```
// webpack.config.js
{
  entry: '/src/index',

  module: {
    rules: [
      {
        test: /\.(js|json|jsx|ts|tsx)$/,
        use: 'babel-loader',
        exclude: /node_modules/,
      }
    ]
  },

  resolve: {
    extensions: ['*', '.js', '.json', '.jsx', '.tsx', '.ts'],
  },

  devtool: 'source-map',

  externals: {
    react: 'React',
    'react-dom': 'ReactDOM',
  },

  output: {
    importFunctionName: 'shimport'
  }
};
```

```
// js
import React from "react";
import ReactDOM from "react-dom";
import {css} from "@emotion/react";

setTimeout(() => {
  // @ts-ignore
  import(/* webpackIgnore: true */ "https://cdn.skypack.dev/canvas-confetti")
    .then(module => console.log(module))
}, 1000)

ReactDOM.render(
  <h1 css={
    css`color: #1A5ADE;`
  }>Hello, world!h1>,
  document.getElementById("main")
);
```

**What is the expected behavior?**

**Other relevant information:**
webpack version:  5.3.0
Node.js version: 
Operating System: 
Additional tools:

I would love to be able to configure webpack to do this. In addition to using my shimport, I also do not want to bundle these dynamically imported modules.

**Comment by evilebottnawi** [comment]
`importFunctionName` for external(s), `webpackIgnore` ignores whole constructions (does nothing with it)

**Comment by evilebottnawi** [comment]
es modules are not supported yet right now, this option for future improvements

**Comment by criles25** [comment]
that makes sense, i will close this issue then. thank you.
