### ISSUE TITLE
 Polyfilling node core modules in webpack 5

### ISSUE THREAD

**Issue by sabeurios** [webpack/webpack#11868]
Webpack 5 no longer do auto-polyfilling for node core modules.

# Bug report
<img width="756" alt="Screenshot 2020-10-27 at 16 23 55" src="https://user-images.githubusercontent.com/57177536/97535594-29c11d80-19bc-11eb-9177-b30ea780db19.png">

**Other relevant information:**
webpack version:  5.2.0M
Node.js version: 12.18.4
Operating System: macOS Mojave
Additional tools: Jhipster 6.10.4

#  PS
I'm a beginner in development so solution must be well described fo me.

**Comment by sokra** [comment]
You'll find the solution in the error message. What exactly is unclear to you about that?

**Comment by sabeurios** [comment]
I have already tried the solution but always the same error
<img width="353" alt="Screenshot 2020-10-29 at 08 51 09" src="https://user-images.githubusercontent.com/57177536/97540619-2af64880-19c4-11eb-8596-0ee4b1bc5c22.png">
<img width="465" alt="Screenshot 2020-10-29 at 08 52 03" src="https://user-images.githubusercontent.com/57177536/97540624-2c277580-19c4-11eb-9830-dabb2d3fb8c5.png">

**Comment by gexiaolin** [comment]
Maybe you need to configure `target: ['node']`

**Comment by sabeurios** [comment]
@gexiaolin not working
<img width="743" alt="Screenshot 2020-10-29 at 09 19 28" src="https://user-images.githubusercontent.com/57177536/97543038-f97f7c00-19c7-11eb-822e-f631e870859b.png">

**Comment by 435352980** [comment]
https://github.com/duplotech/create-react-app/commit/d0be703d40cd4bc32cd91128ba407a138c608243

**Comment by evilebottnawi** [comment]
It was answered a lot of time, please use search, use this:
```js
module.exports = {
  //...
  resolve: {
    fallback: {
      path: require.resolve('path-browserify/')
    }
  }
};
```

**Comment by sabeurios** [comment]
@evilebottnawi 
I tried it and I have already posted screens
![Uploading Screenshot 2020-10-29 at 09.19.28.png…]()

**Comment by sabeurios** [comment]
<img width="233" alt="Screenshot 2020-10-29 at 09 19 12" src="https://user-images.githubusercontent.com/57177536/97558949-1c685b00-19dd-11eb-9fb1-9162c2349ca0.png">

**Comment by evilebottnawi** [comment]
@sabeurios Please provide reproducible test repo

**Comment by sabeurios** [comment]
@evilebottnawi I think I don't have a reproducible test repo or else don't know what exactly you want ... don't forget please I still beginner. Thanks

**Comment by evilebottnawi** [comment]
> I think I don't have a reproducible test repo or else don't know what exactly you want.

I think better ask this question in your boilerplate repo, sorry, without reproducible test repo and more information I can't help

**Comment by sokra** [comment]
It looks like you are compiling your webpack config instead of using your config as config. How are you calling webpack?

**Comment by sabeurios** [comment]
@sokra 
I have an existing project generated with jhipster 5.7 so I upgraded to 6.10 and I transferred the existing files to the new directory and suddenly I had this polyfilling problem

**Comment by evilebottnawi** [comment]
@sabeurios please open an issue `jhipster` or ask them to explain the problem to you

**Comment by gsagar230** [comment]
@sabeurios I am also facing the same issue which you have faced with jhispter project. Can you please tell me what you have did to fix the issue?

**Comment by SURAJ-R-P** [comment]
I am also facing the same issue can you tell me that how did you fixed that error

**Comment by satinder1624** [comment]
Anyone has a solution?

**Comment by Magin-CC** [comment]
Easy way to resolve this problem is use `"alias"` configuration.Like this:

```
alias: {
    "os": "YOUR PLOYFILL MODULE"
}
```

**Comment by Magin-CC** [comment]
`fallback` is the fallback for module resolution failed. But if the core module can find the module in module resolution, we don't use `fallback` configuration anymore.

**Comment by satinder1624** [comment]
alias: {
    "os": "YOUR PLOYFILL MODULE"
}

Here what is YOUR PLOYFILL MODULE

**Comment by Magin-CC** [comment]
> alias: { "os": "YOUR PLOYFILL MODULE" }
> 
> Here what is YOUR PLOYFILL MODULE

Like `"os-browserify/browser"` as in the example above.

**Comment by satinder1624** [comment]
Hello Magin-CC, I try that but it not doing anything. Could you able to look at the code if I send you the repo link? I am trying to solve the issue from last 3 days. I will really appreciate your help.

**Comment by Magin-CC** [comment]
> Hello Magin-CC, I try that but it not doing anything. Could you able to look at the code if I send you the repo link? I am trying to solve the issue from last 3 days. I will really appreciate your help.

I create a demo project: https://github.com/Magin-CC/webpack-core-alias-demo .
It works well. Maybe you can check your webpack config with this.

**Comment by satinder1624** [comment]
Hi, I really appreciate your effort. I wanna confirm where should I change them as I dont have a web config in the root folder should I create one?
Also I have on webpack.config.js file in client/node_modules/react-script

**Comment by Magin-CC** [comment]
learn about this: https://create-react-app.dev/docs/available-scripts#npm-run-eject

**Comment by satinder1624** [comment]
Hey, could you please help me -> https://snipboard.io/6b13KT.jpg
I am not able to solve my problem. As long as I import the 2nd line I get a list of errors

**Comment by Nourfaress** [comment]
check your import ? 
It’s not right , i don’t know what is right in your case but it’s all about import 
i was have the same issue
 import { Router } from 'express';
the right in my case is 
import { Router } from '@angular/router';

**Comment by Brosinski** [comment]
In my case it was using 
import { Router } from 'express';

instead of 

import { Router } from '@angular/router';

Damn quickfix... @Nourfaress thank you
