### ISSUE TITLE
Order of imported (or exported) values is not respected between dev and prod env

### ISSUE THREAD

**Issue by joelwurtz** [webpack/webpack#11871]
# Bug report

**What is the current behavior?**

Order of imported values (when using `import * as values`) is not respected between dev and prod environment

**If the current behavior is a bug, please provide the steps to reproduce.**

foo.js:

```
export const W = 'w';
export const A = 'a';
```

bar.js:

```
import * as values from './foo.js':

console.log(Object.keys(values));
```

webpack 4 dev + prod will output ['W', 'A'];
webpack 5 dev will output ['W', 'A'];
webpack 5 prod will output ['A', 'W']

**What is the expected behavior?**

It should, at least, be the same between dev and production environment for webpack 5, and would be best to keep the same ordrer as declared (like webpack 4 or dev in webpack 5)

**Other relevant information:**

webpack version: 5.3.1
Node.js version: 14.13.1
Operating System: linux
Additional tools: webpack-dev-server

**Comment by evilebottnawi** [comment]
What is use case?

**Comment by joelwurtz** [comment]
It's not really a use case but in our app we have some wrapper in front of react router where we get our routes like this:

```
import * as Routes from './routes.js`
```

then later we do a switch

```
<Switch>
    {Object.keys(Routes).map(route => {
         ...
    })}
</Switch>
```

It broke our application on webpack 5 prod, because `Switch` rely on order to match: first matching = first display. Since we have a NOT_FOUND route to handle bad routes, every route named after it (in alphabetical order) was no longer working. It's easy to understand once you know it, but pretty hard to debug this.

**Comment by sokra** [comment]
The spec requires alphabetical order, but for technical reasons we can't ensure that when commonjs interop is involved. But in a pure ESM we should make sure it's in that order.

**Comment by Tofandel** [comment]
You really shouldn't rely on this order though, even if it's alphabetical, it's pure code smell when you start renaming your routes.. Better use an index.js and export an array with the list of routes imported in the correct order
