### ISSUE TITLE
Named exports for CJS

### ISSUE THREAD

**Issue by WebReflection** [webpack/webpack#11878]
# Bug report

**What is the current behavior?**

Named exports for CJS are part of NodeJS LTS 14 and current version 15, and are being [backported to LTS 12](https://github.com/nodejs/node/pull/35757), but standard code that runs without issues in NodeJS cannot currently be bundled with webpack due error:

```
Can't import the named export 'XXX' (imported as 'XXX') from default-exporting module (only default export is available)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

create an `esm.js` file with this content:
```js
import {log, info} from './cjs/cjs.js';

log('This works');
info('And so does this');
```

put into `package.json` the following content:
```js
{"type": "module"}
```

now create a `./cjs` folder with a `./cjs/cjs.js` file with the following content:
```js
exports.log = console.log;
exports.info = console.info;
```

put into `./cjs/package.json` the following content:
```js
{"type": "commonjs"}
```

Run `node esm.js` and see this outcome:
```
This works
And so does this
```

Now try to configure *webpack* any way to use `./esm.js` as entry point and see this outcome:
```
[webpack-cli] Compilation finished
assets by status 254 bytes [cached] 1 asset
./esm.js 86 bytes [built] [code generated]
./cjs/cjs.js 56 bytes [built] [code generated]

ERROR in ./esm.js 3:0-3
Can't import the named export 'log' (imported as 'log') from default-exporting module (only default export is available)

ERROR in ./esm.js 4:0-4
Can't import the named export 'info' (imported as 'info') from default-exporting module (only default export is available)

webpack 5.3.2 compiled with 2 errors in 155 ms
```

**What is the expected behavior?**

CommonJS named exports have been available for quite some time, and alternative bundlers seem to be compatible with the current NodeJS standard behavior, but *webpack* is making partial migrations from CJS to ESM a bit harder than it should.

Please consider supporting named exports to make migrations smoother, thank you!

**Other relevant information:**
webpack version:  5.3.2 / CLI 4.1.0
Node.js version: 12, 14, 15
Operating System: Linux / macOS
Additional tools: none

**Comment by evilebottnawi** [comment]
Yep, we should improve it
