### ISSUE TITLE
[Webpack 5 bug, works in 4] exported library in an empty object

### ISSUE THREAD

**Issue by dperetti** [webpack/webpack#11887]
# Bug report

**What is the current behavior?**

Exported library is an empty object.

**If the current behavior is a bug, please provide the steps to reproduce.**
```js
// src/Main.tsx
export default { foo: 1 }
```

```js
// webpack.config.js
const path = require('path')

module.exports = {
  devtool: 'inline-source-map',
  entry: {
    Main: './src/Main.tsx',
  },
  output: {
    filename: '[name]-[hash].js',
    path: path.resolve(__dirname, 'dist'),
    publicPath: 'http://0.0.0.0:8080/', 
    library: '[name]',
    libraryExport: 'default',
  },
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        use: 'ts-loader',
        exclude: /node_modules/,
      },
    ],
  },
  resolve: {
    extensions: ['.tsx', '.ts'],
  }
}
```

```js
// in the web page
console.log('Main'); // --> {}
```

**What is the expected behavior?**

```js
// in the web page, using Webpack 4.44.2 we get the expected:
console.log('Main'); // --> {foo: 1}
```

**Other relevant information:**
webpack version:  5.3.2
Node.js version: 12.4.0
Operating System: OSX 10.15.7
Additional tools:

**Comment by evilebottnawi** [comment]
Please do not ignore `If the current behavior is a bug, please provide the steps to reproduce.`, for webpack-dev-server it is known issues

**Comment by sapolio** [comment]
The same problem
webpack 5.14.0
My object is fine when i expose it manually as `window.library`. When i set `library: 'library'`, the export object becomes empty.

**Comment by alexander-akait** [comment]
@sapolio Please provide demo of the problem

**Comment by sapolio** [comment]
What certain parts of setup do i need to expose?
This is how it works on webpack@4 via DevServer.
```
  entry: path.resolve(__dirname, 'src/main.js'),
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'filename.js',
    library: 'libraryName',
    libraryExport: 'default',
  },
```
The default export of **main.js** is an object literal.
```
export default {
  ...ClapprCore,
  ClickToPause,
  andSoOn
}
```
And i see it in browsers window object as **libraryName**

Now i will reinstall webpack to version 5 and start it... 

> \+ webpack@5.15.0
> webpack 5.15.0 compiled successfully in 5144 ms
ℹ ｢wdm｣: Compiled successfully.

Now my **libraryName** is undefined.
Then i comment out `libraryExport: 'default',` line. After that my **libraryName** becomes an empty object.

**Comment by alexander-akait** [comment]
Without `webpack-dev-server` all works fine? Maybe you can provide minimum reproducible test repo?

**Comment by sapolio** [comment]
Didn't try bundle file alone yet.
OK I'll make a repo a bit later.

**Comment by sapolio** [comment]
@alexander-akait , welcome!
https://github.com/sapolio/webpack_5_test
I minimized the project.
Change the webpack version to 4, and everything will work.
So far, we are only talking about devserver.

**Comment by sapolio** [comment]
@alexander-akait 
Bundle works fine without devserver...

**Comment by alexander-akait** [comment]
@sapolio Can you try `webpack-dev-server@4-beta.0`?

**Comment by sapolio** [comment]
@alexander-akait 
How does one install this version?

**Comment by alexander-akait** [comment]
@sapolio put this in `package.json` (i.e. `{ devDependencies: { "webpack-dev-server": "^4.0.0-beta.0" } }`)

**Comment by sapolio** [comment]
@alexander-akait 
The problem is gone with that beta version.
However, it could not start until I removed the "contentbase" and "disablehostcheck"options from the config.

> - configuration has an unknown property 'contentBase'.

**Comment by alexander-akait** [comment]
`contentbase` was renamed to `static: './public'`
`disablehostcheck` was renamed to `firewall: false`

**Comment by ivictbor** [comment]
Works when updating to `"webpack-dev-server": "^4.0.0-beta.0"` 

Don't forget to replace `publicPath` with `static`
```
devServer: {
        static: path.join(__dirname, 'build'),
},
```

**Comment by 1950195** [comment]
But also have to change lots of props in `devServer`(when updating to "webpack-dev-server": "^4.0.0-beta.0")  😧  , likes `before`:

```
before: async (app) => {
```

==>

```
onBeforeSetupMiddleware: async ({ app }) => {
```

❤️  It works!

**Comment by challet** [comment]
> `contentbase` was renamed to `static: './public'`
> `disablehostcheck` was renamed to `firewall: false`

Where one can find the list of changes from webpack-dev-server 3.x to 4.x ?

**Comment by yansenlei** [comment]
the same issue, Is there any solution?

**Comment by ivictbor** [comment]
> the same issue, Is there any solution?

https://hinty.io/devforth/fix-webpack-imported-module-is-not-a-function-for-webpack5/

**Comment by yansenlei** [comment]
@ivictbor , Thank you for your help. My problems are still there.
My export configuration doesn't have a `library`

```js
{
  ...
  output: {
    path: env.production ? path.resolve(__dirname, '../dist') : path.join(pluginHomeDir, 'dist'),
    libraryTarget: 'umd',
    umdNamedDefine: true,
    filename: 'testPlugin.min.js',
    publicPath: '/dist/'
  },
  devServer: {
    hot: true,
    historyApiFallback: true,
    noInfo: true,
    overlay: true,
    contentBase: path.join(__dirname, 'dist'),
    compress: true,
    host: 'localhost',
    port: 9000,
    injectClient: true,
    writeToDisk: (filePath) => {
      return writeIndex++ <= 1
    },
    headers: {
      "Access-Control-Allow-Origin": "*",
      https: true
    }
  }
}
```
I expect to work normally in DevServer, and WebPack4 can work

```
    "webpack": "^4.29.4",
    "webpack-cli": "^3.0.8",
    "webpack-dev-server": "^3.1.4",
```
in browser
```js
Module{object}
```
After upgraded webpack
```
    "webpack": "^5.38.1",
    "webpack-cli": "^3.0.8",
    "webpack-dev-server": "^3.11.2",
```
in browser
```
{}
```

![image](https://user-images.githubusercontent.com/23315895/120523112-1f5e7a80-c408-11eb-9268-33333be56e2f.png)

**Comment by ivictbor** [comment]
> @ivictbor , Thank you for your help. My problems are still there.
> My export configuration doesn't have a `library`
> 
> ```js
> {
>   ...
>   output: {
>     path: env.production ? path.resolve(__dirname, '../dist') : path.join(pluginHomeDir, 'dist'),
>     libraryTarget: 'umd',
>     umdNamedDefine: true,
>     filename: 'testPlugin.min.js',
>     publicPath: '/dist/'
>   },
>   devServer: {
>     hot: true,
>     historyApiFallback: true,
>     noInfo: true,
>     overlay: true,
>     contentBase: path.join(__dirname, 'dist'),
>     compress: true,
>     host: 'localhost',
>     port: 9000,
>     injectClient: true,
>     writeToDisk: (filePath) => {
>       return writeIndex++ <= 1
>     },
>     headers: {
>       "Access-Control-Allow-Origin": "*",
>       https: true
>     }
>   }
> }
> ```
> 
> I expect to work normally in DevServer, and WebPack4 can work
> 
> ```
>     "webpack": "^4.29.4",
>     "webpack-cli": "^3.0.8",
>     "webpack-dev-server": "^3.1.4",
> ```
> 
> in browser
> 
> ```js
> Module{object}
> ```
> 
> After upgraded webpack
> 
> ```
>     "webpack": "^5.38.1",
>     "webpack-cli": "^3.0.8",
>     "webpack-dev-server": "^3.11.2",
> ```
> 
> in browser
> 
> ```
> {}
> ```
> 
> ![image](https://user-images.githubusercontent.com/23315895/120523112-1f5e7a80-c408-11eb-9268-33333be56e2f.png)

What is your entry point? What do you export from source code, and also your package.json please. I would also recommend to create minimal reproducible project like I did. Then it will be easier for you to understand the difference and for us to find an issue

**Comment by yansenlei** [comment]
@ivictbor I added some [information](https://github.com/webpack/webpack/issues/11887#issuecomment-853236108) 🥰

**Comment by ivictbor** [comment]
> @ivictbor I added some [information](https://github.com/webpack/webpack/issues/11887#issuecomment-853236108) 🥰

As I see from your info you did not install 4.x.x weback-dev-server like here https://github.com/webpack/webpack/issues/11887#issuecomment-773253134

**Comment by yansenlei** [comment]
It's working fine now
```
    "webpack": "^5.38.1",
    "webpack-cli": "^4.7.0",
    "webpack-dev-server": "4.0.0-beta.0",
```

**Comment by dgaenko** [comment]
I test it on 
    "webpack": "^5.38.1",
    "webpack-cli": "^4.7.0",
    "webpack-dev-server": "4.0.0-beta.x" (0-3)
it's not works :(

**Comment by vquigley** [comment]
This fix worked for me but I worry that I am now moving to a more unstable version in general. Does anyone know if 4 will be released as stable? Should we log a bug against 3 for a fix against that version?
