### ISSUE TITLE
Question: How to avoid duplication of module?

### ISSUE THREAD

**Issue by rocetspace** [webpack/webpack#11884]
Hey there! I have a question.

I have two npm-packages: `sub` and `common`. I'm writing my app using this packages.

**`sub`** includes `common` as dependency.
```javascript
import common from 'common';

// some code here
```

**my app**
```javascript
import sub from 'sub';
import common from 'common';

// some code here
```

The final bundle contains two copies of `common` package. The first copy is for my app, and the second one - for package `sub`.
**final bundle**
```javascript
...
// my app
({ /* some deps */ }) => {
    var sub = __webpack_require__(1);
    var common = __webpack_require__(2);
}
// end of my app

...
// sub
({ /* some deps */ }) => {
    var common = __webpack_require__(3);
    //                               ^ not the same line in app (in app uses 2)
}
// end of sub
...

// module 2
({ /* some deps */ }) => {
    // code of common 
}
// end module 2
...

// module 3
({ /* some deps */ }) => {
    // code of common
}
// end module 3
```

Could I combine `common` in one module to avoid duplication? Thanks!

**Comment by montogeek** [comment]
I encourage you to ask your question on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question.

I’m closing for these reasons.
