### ISSUE TITLE
Watching.close does not really close watching

### ISSUE THREAD

**Issue by HKalbasi** [webpack/webpack#11899]
# Bug report

**What is the current behavior?**
When I remove the webpack entry file after watching.close callback called, webpack generate an error like this:
```
ERROR in app
Module not found: Error: Can't resolve './client-sdjsafjkhdsf-gitignore.js'
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Remove entry file with a code like this:
```
    console.log('Stop watching...');
    await new Promise((res) => watching.close(()=>res()));
    await new Promise(res=>setTimeout(res, 2000)); // just for testing
    console.log('Removing files...');
    await rmdir(tempDir, { recursive: true });
    await removeFile(wiPath); // removing index file
    console.log('Exited successfully');
    await new Promise(res=>setTimeout(res, 2000)); // here webpack print error
```

**What is the expected behavior?**
`Watching.close` should close the watching and webpack don't run again after I delete files. There should be no error.

**Other relevant information:**
webpack version:  5.3.2
Node.js version: 14.6.0
Operating System: Ubuntu 20.04

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by HKalbasi** [comment]
I made a small sample but it was right in it, when I went back to my code I saw it right there too! Without changing a single line of code.
Very strange! If it happens again and I understand in what condition it happens, I will reopen this issue.
