### ISSUE TITLE
Error referencing asset module with multiple different query strings

### ISSUE THREAD

**Issue by andersk** [webpack/webpack#11894]
# Bug report

**What is the current behavior?**

When handling `.eot` files as asset modules, loading [`font-awesome/css/font-awesome.css`](https://github.com/FortAwesome/Font-Awesome/blob/v4.7.0/css/font-awesome.css) with `css-loader` causes “Error: Prevent writing to file that only differs in casing or query string from already written file. This will lead to a race-condition and corrupted files on case-insensitive file systems.”

This seems to be because `font-awesome.css` references the same file with two different query strings: `url('../fonts/fontawesome-webfont.eot?v=4.7.0')` and `url('../fonts/fontawesome-webfont.eot?#iefix&v=4.7.0')`.

**If the current behavior is a bug, please provide the steps to reproduce.**

```console
$ cat > webpack.config.js <<EOF
// webpack.config.js
module.exports = {
  entry: "font-awesome/css/font-awesome.css",
  output: { publicPath: "" },
  module: {
    rules: [
      { test: /\.css$/, use: ["style-loader", "css-loader"] },
      { test: /\.(eot|svg|ttf|woff2?)$/, type: "asset/resource" },
    ],
  },
};
EOF
$ npm i css-loader font-awesome style-loader webpack webpack-cli
…
+ style-loader@2.0.0
+ font-awesome@4.7.0
+ webpack-cli@4.1.0
+ css-loader@5.0.0
+ webpack@5.3.2
added 163 packages from 175 contributors and audited 163 packages in 4.752s
…
$ npx webpack
[webpack-cli] Error: Prevent writing to file that only differs in casing or query string from already written file.
This will lead to a race-condition and corrupted files on case-insensitive file systems.
/tmp/test/dist/cf88812dc8f4d812c0ef.eot
/tmp/test/dist/cf88812dc8f4d812c0ef.eot
    at writeOut (/tmp/test/node_modules/webpack/lib/Compiler.js:565:20)
    at /tmp/test/node_modules/webpack/lib/Compiler.js:748:7
    at arrayIterator (/tmp/test/node_modules/neo-async/async.js:3467:9)
    at timesSync (/tmp/test/node_modules/neo-async/async.js:2297:7)
    at Object.eachLimit (/tmp/test/node_modules/neo-async/async.js:3463:5)
    at emitFiles (/tmp/test/node_modules/webpack/lib/Compiler.js:534:13)
    at /tmp/test/node_modules/webpack/lib/util/fs.js:178:5
    at FSReqCallback.oncomplete (fs.js:171:23)
```

This can also be reproduced without css-loader, using a JS entry point like

```js
require("font-awesome/fonts/fontawesome-webfont.eot?v=1");
require("font-awesome/fonts/fontawesome-webfont.eot?v=2");
```

**What is the expected behavior?**

Referencing a file with different query strings should not cause it to be written twice—it’s the same file, not a collision between two files.

**Other relevant information:**
webpack version: 5.3.2
Node.js version: 14.14.0
Operating System: Linux (NixOS 21.03)
Additional tools: css-loader 5.0.0, font-awesome 4.7.0

**Comment by Bhavik-Ardeshna** [comment]
Hey ! I need to work on this issue
But I m new to this can you plz guide me how to start go through this webpack repo.

Means from which file I would start ?

**Comment by evilebottnawi** [comment]
WIP on this, task is not easy

**Comment by evilebottnawi** [comment]
Workaround:
```js
{
  test: /\.(png|jpg|gif|svg|eot|ttf|woff|woff2)$/i,
  type: 'asset/resource',
  generator: {
    filename: 'static/[hash][ext]'
  }
},
