### ISSUE TITLE
Loader Function

### ISSUE THREAD

**Issue by nick-thompson** [webpack/webpack#119]
In the case of custom loaders which are extremely short (like https://github.com/petehunt/jsx-loader/blob/master/index.js), it'd be nice to be able to define the loader inline:

```
function jsxLoader(source) {
  this.cacheable()
  return React.transform(source);
}

module.exports = {
  module: {
    loaders: [
      { test: /\.js$/, loader: jsxLoader }
    ]
  }
};
```

Is this possible in any way? If not, is it an idea that you'd be willing to entertain?

**Comment by trusktr** [comment]
@sokra Functional loaders would be great because the function could close on the scope being used to configure Webpack, and that scope can have useful variables that aren't accessible in a file-based loader.

**Comment by trusktr** [comment]
An alternative solution is to use inline transforms with the transform-loader.

**Comment by sokra** [comment]
> @sokra Functional loaders would be great because the function could close on the scope being used to configure Webpack, and that scope can have useful variables that aren't accessible in a file-based loader.

You can write a loader that allows to use inline/function loaders.

**Comment by cameron** [comment]
FWIW, I also like the idea of an inline function loader, and it seems like you could just borrow the function name for the identifier.

**Comment by matthewmueller** [comment]
@lovetingyuan, woah that's really clever using `__filename` & `module.exports`. Thanks for sharing!
