### ISSUE TITLE
output file is empty if a plugin opens it at 'done'

### ISSUE THREAD

**Issue by heebtob** [webpack/webpack#1190]
I wrote a small plugin to automatically set chunk hashes in my output file.

It does the following:
* Read Output file (Server.js)
* Get all chunk names
* extract the chunk hash
* make a regex replace to replace all ##chunkhash_...## with the actual hash
* write it to the Output file (Server.js)

The Problem ist that it sometimes works and sometimes not.

If it's not working then I saw that the regex returns null.
But the regex should never return null. 
I wrote the Content of the Output file (Server.js) to the console and saw that at the second call of the plugin the Output file (Server.js) is empty. 
But the second call is the important one.

**Why is the output file sometimes empty at the second call of the plugin?**

**HTML**
``` html
<script src="/client.##chunkhash_app##.js"></script>
```

**plugin code**
``` JavaScript
'use strict';

var fs = require('fs');
var path = require('path');

function Plugin(options) {
    this.options = options || {};
}

Plugin.prototype.apply = function(outerCompiler) {
    var self = this;

    outerCompiler.plugin('done', function(stats) {
        var outputDir = self.options.path || '.';
        var htmlFile = self.options.htmlFile;

        var htmlPath = path.join(outputDir, htmlFile);
        console.log('path:' + htmlPath);

        try {
            var serverjs = fs.readFileSync(htmlPath, 'utf8');
            //console.log('content:' + serverjs);
            var webpackStatsJson = stats.toJson();

            for (var chunkName in webpackStatsJson.assetsByChunkName) {
                // always take the first entry. it doesn't depend because every entry of the chunk has the same hash
                var chunkValue = webpackStatsJson.assetsByChunkName[chunkName][0];

                var indexOfFirstPoint = chunkValue.indexOf('.');
                var indexOfSecondPoint = chunkValue.indexOf('.', indexOfFirstPoint + 1);

                // extract hash which is between the first and the second point
                var chunkHash = chunkValue.substring(indexOfFirstPoint + 1, indexOfSecondPoint);
                console.log('chunkname:' + chunkName + ' chunkvalue:' + chunkValue + ' chunkhash:' + chunkHash);

                // prepare regex to replace all ##chunkhash_chunkname## with the chunk hash
                var regex = RegExp('##chunkhash_' + chunkName + '##', 'gi');
                console.log('regex:' + '##chunkhash_' + chunkName + '##');
                console.log('matches:' + serverjs.match(regex));

                serverjs = serverjs.replace(regex, chunkHash);
                fs.writeFile(htmlPath, serverjs);
            }
        } catch (e) {
            console.log(e);
            compiler.errors.push(new Error('CacheBustingPlugin: File not found ' + htmlPath));
        }
    });
};

module.exports = Plugin;
```

**Console Output**

path:C:\WebstormProjects\build\server.js
chunkname:main chunkvalue:server.js chunkhash:server.
regex:##chunkhash_main##
matches:null

path:C:\WebstormProjects\build\server.js
chunkname:app chunkvalue:client.40b9f1e0c1cc9d223afe.js chunkhash:40b9f1e0c1cc9d223afe
regex:##chunkhash_app##
matches:null
chunkname:vendors chunkvalue:vendors.207f2b7b49e660a0c6a2.js chunkhash:207f2b7b49e660a0c6a2
regex:##chunkhash_vendors##
matches:null

**Comment by sokra** [comment]
Do you want to override the orginal file (`C:\WebstormProjects\build\server.js`)? This would remove the placeholders. Maybe you want to write the result to a new file and don't modify the orginal file.

`fs.writeFile(htmlPath, serverjs);` should either be Sync or use a callback.

**Comment by heebtob** [comment]
Yes I want to override the original file because it's the output file of the build. 
I changed writeFile to writeFileSync. Could this be the Problem? 
I made a few builds and it worked everytime.

**Comment by heebtob** [comment]
I think the writeFile was the Problem. 
Since I changed it to writeFileSync it worked everytime.

Thanks very much for the help.
