### ISSUE TITLE
Caching failed for pack: Error: Unable to snapshot build dependencies

### ISSUE THREAD

**Issue by kelunik** [webpack/webpack#11908]
# Bug report

**Reproduction Steps**

See https://github.com/kelunik/webpack-5-testing/commit/a800896c6c10df3572d50b573ef03c9e2a8607f6 for a simple reproduction. The README includes two scenarios, both for the large file and generic tracking of the project root as build dependency.

**What is the current behavior?**

```
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Unable to snapshot build dependencies
```

I did some debugging in `FileSystemInfo.js` and found the following error here: 

```
this._getContextTimestampAndHash(path, (err, entry) => {
	if (err) {
		if (this.logger) {
			this.logger.debug(
				`Error snapshotting context timestamp hash combination of ${path}: ${err}`
			);
		}
		jobError();
	} else {
		contextTshs.set(path, entry);
		jobDone();
	}
});
```

```
RangeError [ERR_FS_FILE_TOO_LARGE]: File size (3458767214) is greater than possible Buffer: 2147483647 bytes
    at FSReqCallback.readFileAfterStat [as oncomplete] (fs.js:278:11) {
  code: 'ERR_FS_FILE_TOO_LARGE'
}
```

**What is the expected behavior?**

I'm not sure, but the current error message neither says what the actual error is nor how to work around such a problem. I'm not sure whether the problem itself can be avoided. Maybe users running into this need to apply filters to the context?

**Other relevant information:**
webpack version:  5.3.2
Node.js version: 12.16.3
Operating System: Ubuntu / Linux

**Comment by sokra** [comment]
Were you able to determine the file which caused the error?

Note that you can enable debug logging with `infrastructureLogging.debug: /FileSystemInfo/`. Maybe that yields something useful...

**Comment by kelunik** [comment]
`path` was the root of the project. Do I need to set `infrastructureLogging.debug: /FileSystemInfo/` inside `stats`?

**Comment by kelunik** [comment]
I see: https://webpack.js.org/configuration/other-options/#infrastructurelogging

**Comment by kelunik** [comment]
Only yields that exact error, but would have prevented me editing the files manually to get the error.

```
99% done plugins watchInfo[webpack-cli] Compilation finished
    [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Error snapshotting context timestamp hash combination of /home/kelunik/Git/project-xy: RangeError [ERR_FS_FILE_TOO_LARGE]: File size (3458767214) is greater than possible Buffer: 2147483647 bytes
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Unable to snapshot build dependencies
```

I found the file using `ncdu` and deleted it, the message is gone then. But there might be other large files in the project directory that aren't related to my webpack build at all.

**Comment by sokra** [comment]
> Only yields that exact error

hmm, we should add stack traces to the logging...

**Comment by sokra** [comment]
> But there might be other large files in the project directory that aren't related to my webpack build at all.

Yeah, weird that `/home/kelunik/Git/project-xy` is in your build dependencies. This shouldn't be that way. It actually makes the cache useless as it's always invalidated when anything changes. This might be caused by some kind of fallback behavior, because the usually way doesn't work...

**Comment by sokra** [comment]
> This might be caused by some kind of fallback behavior, because the usually way doesn't work...

Is your webpack.config.js an node.js ESM?

**Comment by kelunik** [comment]
No, code in the project is ESM, but the webpack config is CJS.

> This might be caused by some kind of fallback behavior, because the usually way doesn't work...

Do you have anything specific in mind I should check?

**Comment by evilebottnawi** [comment]
> Do you have anything specific in mind I should check?

Do you have big project? Maybe you can show webpack config?

**Comment by sokra** [comment]
> Do you have anything specific in mind I should check?

I think this is related to ESM in build dependencies which is not fully supported and falls back to including whole directories... Working on that

**Comment by kelunik** [comment]
Ok, I've debugged this today. I followed the advice of the new [cache configuration](https://github.com/webpack/changelog-v5/blob/master/guides/persistent-caching.md#build-dependencies) and added `tsconfig.json` as additional file to `buildDependencies.config`. However [this](https://github.com/webpack/webpack/blob/7415a618460795874fdf95c8f03363ea96709d52/lib/FileSystemInfo.js#L1212-L1215) fails for `tsconfig.json` and runs into the [`else` branch](https://github.com/webpack/webpack/blob/7415a618460795874fdf95c8f03363ea96709d52/lib/FileSystemInfo.js#L1250-L1257). `tsconfig.json` is in the project root, so it adds the entire project directory.

**Comment by evilebottnawi** [comment]
Can you provide simple reproducible test repo?

**Comment by kelunik** [comment]
I'll try to do that now, yes.

**Comment by kelunik** [comment]
See https://github.com/kelunik/webpack-5-testing/commit/a800896c6c10df3572d50b573ef03c9e2a8607f6 for a simple reproduction. The README includes two scenarios, both for the large file and generic tracking of the project root as build dependency.

**Comment by sokra** [comment]
> `tsconfig.json` is in the project root, so it adds the entire project directory.

Ah I see. So you are adding a non code file. We should handle this better.

Anyway you probably don't need to add this file. I strongly assume that your typescript loader add this as dependency. At least it should do so. cc @johnnyreilly ?

Nonetheless we should support non-code files as buildDependencies too.

**Comment by ASDFGerte** [comment]
As a mention, i also naively added `tsconfig.json` and `package.json` as `buildDependencies` in my project. Adding `package.json` is probably unnecessary, but `tsconfig.json` isn't. When changing something in `tsconfig.json`, and nothing else, webpack would just take the cache, bypassing `ts-loader`. The new build would not reflect the potentially vast differences produced by changing a compiler flag. This was, why i searched for `buildDependencies` in the first place. Imho `buildDependencies` is for 'atypical and not easy to predict reasons to invalidate the cache', where non-js files should be allowed.

Sadly, i didn't get OP's error message, but just a generic note, that the root folder hash now differs. I wouldn't be surprised, if `package.json` has some special case, which further added to my confusion about the cause (because that worked, unlike any other `.json` file). Stackoverflow didn't help either, and i've been searching for quite a while, until just crawling through any 'cache'-related issues one by one, finally finding this.

**Comment by johnnyreilly** [comment]
Hi,

I've read this but I'm not sure if there's any way in which I can help?

**Comment by alexander-akait** [comment]
@johnnyreilly Do we add `tsconfig.json` to `buildDependencies`?

**Comment by johnnyreilly** [comment]
So `tsconfig.json` will likely change rarely. But it can change build output / build behaviour. Having skimmed the docs, I think that probably means it should be in buildDependencies for reasons of persistent caching.

**Comment by alexander-akait** [comment]
@johnnyreilly loader has API for this, you can do it automatically to reduce complex of the configuration

**Comment by johnnyreilly** [comment]
> you can do it automatically to reduce complex of the configuration

Are there docs around that?

**Comment by sokra** [comment]
`this.addDependency` can be used for the tsconfig too.

**Comment by Mahdi-Soultana** [comment]
i think this issu has relation with node version that you have install with it your project and the upgardated version that you use later , so you have to remove your node_module and upgrade your npm and try to install everything fresh !
