### ISSUE TITLE
Should WatchOptions.ignored really exclude changes from the compilation process or just from triggering a new build?

### ISSUE THREAD

**Issue by JonWallsten** [webpack/webpack#11907]
This is kind of an open question to the maintainers, and if it's already addressed in Webpack 5 you can just close this.
While creating a plugin for our monorepo where I wanted to exclude our dist files from triggering a new build in upstream packages, I noticed that these files was also excluded in the compilation process for the next rebuild. Isn't this really two different things? 
Ignoring files to not trigger new build might be useful in some cases, and ignoring changed files from the compilation process might be useful in other cases. Would it be possible to separate these two thing?
In the end I ignored the files and then manually called called fileWatcher to trigger a change to include them in the process.

I understand that I maybe should have used middleware or child compilers e.t.c. But it would have been so much easier just excluding files from triggering a new build.

**Comment by evilebottnawi** [comment]
You just disable watching for these files or directories
