### ISSUE TITLE
webpack execute and replace my umd module code during compile

### ISSUE THREAD

**Issue by littleprincewdk** [webpack/webpack#11906]
# Bug report

**What is the current behavior?**
webpack execute and replace code like `typeof define === "function"` and `typeof module === "object"` during compile.

**If the current behavior is a bug, please provide the steps to reproduce.**
suppose we have two file:
`src/index.js`:
```javascript
import umdModule from "./umdModule";

console.log(umdModule);
```
`src/umdModule.js`(usually a library in node_modules):
```javascript
(function (root, factory) {
  if (typeof define === "function" && define.amd) {
    define([], factory); // this will reserved, but i don`t want amd
  } else if (typeof module === "object" && module.exports) {
    module.exports = factory(require("lodash")); // this will disappear after compile
  } else {
    root.returnExports = factory(require("lodash")); // this will disappear after compile
  }
})(typeof self !== "undefined" ? self : this, function (lodash) {
  console.log(lodash.VERSION); // so lodash is undefined, this will throw an error: "TypeError: Cannot read property 'VERSION' of undefined";

  return "a umd module";
});

console.log(typeof define === "object"); // => console.log("function" === "object");
console.log(typeof module === "object"); // => console.log("object" === "object");
```
`webpack.config.js`:
```javascript
const path = require("path");

module.exports = {
  mode: "development",
  entry: path.resolve("src/index.js"),
  output: {
    path: path.resolve("dist"),
    filename: "index.js",
  },
  devtool: "source-map",
};
```
the reproduction repository: https://github.com/littleprincewdk/webpack-umd-test

**What is the expected behavior?**
then i compile and run like this:
```bash
$ npm run build
$ node dist/index.js
```
i expect it output `lodash.VERSION`, but i got a error `TypeError: Cannot read property 'VERSION' of undefined`, then i checked `dist/index.js`, it looked like this:
```javascript

/***/ "./src/umdModule.js":
/*!**************************!*\
  !*** ./src/umdModule.js ***!
  \**************************/
/*! unknown exports (runtime-defined) */
/*! runtime requirements: top-level-this-exports, __webpack_exports__, module */
/*! CommonJS bailout: this is used directly at 9:40-44 */
/***/ (function(module, exports) {

var __WEBPACK_AMD_DEFINE_FACTORY__, __WEBPACK_AMD_DEFINE_ARRAY__, __WEBPACK_AMD_DEFINE_RESULT__;(function (root, factory) {
  if (true) {
    !(__WEBPACK_AMD_DEFINE_ARRAY__ = [], __WEBPACK_AMD_DEFINE_FACTORY__ = (factory),
		__WEBPACK_AMD_DEFINE_RESULT__ = (typeof __WEBPACK_AMD_DEFINE_FACTORY__ === 'function' ?
		(__WEBPACK_AMD_DEFINE_FACTORY__.apply(exports, __WEBPACK_AMD_DEFINE_ARRAY__)) : __WEBPACK_AMD_DEFINE_FACTORY__),
		__WEBPACK_AMD_DEFINE_RESULT__ !== undefined && (module.exports = __WEBPACK_AMD_DEFINE_RESULT__)); // this will reserved, but i don`t want amd
  } else {}
})(typeof self !== "undefined" ? self : this, function (lodash) {
  console.log(lodash.VERSION); // so lodash is undefined, this will throw an error: "TypeError: Cannot read property 'VERSION' of undefined";

  return "a umd module";
});

console.log("function" === "object"); // => console.log("function" === "object");
console.log("object" === "object"); // => console.log("object" === "object");


/***/ })
```
`typeof define === "function" && define.amd` become `true`, `commonjs` and `global` definition gone, so the dependency `lodash` is `undefined`

**Other relevant information:**
webpack version:  5.3.2
Node.js version: 14.0.0
Operating System: Mac OS 10.15.2
Additional tools: vscode 1.50.1

**Comment by sokra** [comment]
webpack supports AMD and CommonJS. If AMD comes first in the `if` UMD block, it's used. The CommonJs is removed since it's dead code and will never be entered.

Note that your UMD module is wrong of AMD:

``` diff
-define([], factory);
+define(["lodash"], factory);

**Comment by littleprincewdk** [comment]
> webpack supports AMD and CommonJS. If AMD comes first in the `if` UMD block, it's used. The CommonJs is removed since it's dead code and will never be entered.
> 
> Note that your UMD module is wrong of AMD:
> 
> ```diff
> -define([], factory);
> +define(["lodash"], factory);
> ```

Thank you. Indeed i dont want AMD, i use it in nodejs, i want CommonJS。The actual scenario is that I use a library called [X2JS](https://github.com/x2js/x2js/blob/09934740124896582ce208b23c3f2295feceab75/x2js.js#L41), its source code:
```javascript
(function (root, factory) {
	"use strict";

	/* global define */
	if (typeof define === 'function' && define.amd) {
		// AMD. Register as an anonymous module.
		define([], factory);
	} else if (typeof module === 'object' && module.exports) {
		// Node. Does not work with strict CommonJS, but only CommonJS-like
		// environments that support module.exports, like Node.
		module.exports = factory(require("xmldom").DOMParser);
	} else {
		// Browser globals (root is window)
		root.X2JS = factory();
	}
})(this, function (CustomDOMParser) {
	"use strict";
```

when i compile and run it in nodejs, it broken, because nodejs doesn't support AMD. `module.exports = factory(require("xmldom").DOMParser);` gone. output is:
```javascript
(function (root, factory) {
	"use strict";

	/* global define */
	if (true) {
		// AMD. Register as an anonymous module.
		!(__WEBPACK_AMD_DEFINE_ARRAY__ = [], __WEBPACK_AMD_DEFINE_FACTORY__ = (factory),
				__WEBPACK_AMD_DEFINE_RESULT__ = (typeof __WEBPACK_AMD_DEFINE_FACTORY__ === 'function' ?
				(__WEBPACK_AMD_DEFINE_FACTORY__.apply(exports, __WEBPACK_AMD_DEFINE_ARRAY__)) : __WEBPACK_AMD_DEFINE_FACTORY__),
				__WEBPACK_AMD_DEFINE_RESULT__ !== undefined && (module.exports = __WEBPACK_AMD_DEFINE_RESULT__));
	} else {}
})(this, function (CustomDOMParser) {
	"use strict";
```
`CustomDOMParser` is `undefined`

**Comment by evilebottnawi** [comment]
You can disable AMD if you don't want it

**Comment by evilebottnawi** [comment]
https://webpack.js.org/configuration/other-options/#amd

**Comment by littleprincewdk** [comment]
> You can disable AMD if you don't want it

This can solve my problem temporarily. But if webpack can retain the code, what exactly is determined by the runtime，will it be better? Then my code can support AMD and CommonJs. When i set `libraryTarget: 'umd'`, The code generated by webpack itself is reserved and not replaced，then the user's should be kept。
<img width="582" alt="截屏2020-11-03上午11 27 28" src="https://user-images.githubusercontent.com/20736912/97947216-91fe6d80-1dc7-11eb-9dfb-88bb3fde6e4e.png">

**Comment by sokra** [comment]
> he actual scenario is that I use a library called [X2JS](https://github.com/x2js/x2js/blob/09934740124896582ce208b23c3f2295feceab75/x2js.js#L41), its source code

This lib behaves different depending on the module system use. This is not recommended. But as there is nothing you can do there try to add this to your config:

``` js
module.rules: [{
  test: require.resolve("x2js/x2js.js"),
  parser: {
    amd: false
  }
}]
```

**Comment by littleprincewdk** [comment]
OK，thank all of you。It is really a problem with X2JS, I should raise the issue to it

**Comment by watsonnnnn** [comment]
Is this a webpack bug? Why amd comes first in nodejs runtime when bundling?

**Comment by alexander-akait** [comment]
@watsonnnnn Can you clarify? thank you
