### ISSUE TITLE
Type information for WatchOptions.ignored seems to be wrong

### ISSUE THREAD

**Issue by JonWallsten** [webpack/webpack#11903]
# Bug report

**What is the current behavior?**
Type information for Webpack states `WatchOptions.ignored` can take `string | RegExp | string[];` but the documentation states it can take `anymatch`. 

From anymatch:

> matchers: (Array|String|RegExp|Function) String to be directly matched, string with glob patterns, regular expression test, function that takes the testString as an argument and returns a truthy value if it should be matched, or an **array of any number and mix of these types**.

**If the current behavior is a bug, please provide the steps to reproduce.**
Add the following to the config:
```
{
    watchOptions: {
        ignored: [
            /node_modules/,
            '**/*.d.ts'
        ]
    }
}
```

This causes the following error:
![image](https://user-images.githubusercontent.com/5993909/97873200-8f443f80-1d17-11eb-8ab8-a916a94187d1.png)

**What is the expected behavior?**
It should allow mixing RegExp and string in the array without showing an error.

**Other relevant information:**
webpack version:  5.3.2
Node.js version: 12.19.0
Operating System: Windows 10

**Comment by evilebottnawi** [comment]
Feel free to send a fix

**Comment by sokra** [comment]
The documentation is not up-to-date here, but it probably also makes sense to add RegExp support for watchpack.

**Comment by JonWallsten** [comment]
> The documentation is not up-to-date here, but it probably also makes sense to add RegExp support for watchpack.

@sokra I'm already using RegExp and can confirm that matching files does not trigger a new build or end up in the compilation process the next rebuild. At least for Webpack 4. Isn't Watchpack just passing the option on to chokidar?

Using the following code:
`` `
const distFilesFilter = /[\\\/]packages[\\\/]web-(?:lib|app)-.*[\\\/]dist[\\\/]/;

watchOptions: {
    aggregateTimeout: 300,
    ignored: [
        /node_modules/,
        distFilesFilter,
        '**/*.d.ts'
    ]
},
```

**Comment by evilebottnawi** [comment]
> Isn't Watchpack just passing the option on to chokidar?

we don't use `chokidar` for webpack@5

**Comment by JonWallsten** [comment]
> > Isn't Watchpack just passing the option on to chokidar?
> 
> we don't use `chokidar` for webpack@5

Then everything makes sense! Thanks!

**Comment by alexander-akait** [comment]
Fixed in docs
