### ISSUE TITLE
Implement import assertions

### ISSUE THREAD

**Issue by xtuc** [webpack/webpack#11917]
## Feature request

**What is the expected behavior?**
webpack can use https://github.com/tc39/proposal-import-assertions to enforce JavaScript module type at runtime or build time (like with JSON modules, presumably based on file extension).

**What is motivation or use case for adding/changing the behavior?**
For security reasons browser will use the syntax for some non JavaScript Module types. Even if webpack doesn't necessarily suffers from that concern, we should make it consistent with browsers.

It could help webpack's runtime when loading/parsing resource into JavaScript modules if the file extension isn't available on a file system or expose to loaders to run on a certain module types only.

**How should this be implemented in your opinion?**
Acorn needs to support the syntax

**Are you willing to work on this yourself?**
yes

**Comment by PratishShrivastava** [comment]
@xtuc  can I work on this issue

**Comment by xtuc** [comment]
I implemented the parser plugin in acorn for import assertions: https://github.com/xtuc/acorn-import-assertions

**Comment by alexander-akait** [comment]
bump

**Comment by alexander-akait** [comment]
Done https://github.com/webpack/webpack/pull/12278
