### ISSUE TITLE
Libraries loaded twice using ModuleFederation plugin

### ISSUE THREAD

**Issue by alex-vukov** [webpack/webpack#11914]
# Bug report

**What is the current behavior?**
I have a shell React application which must display a component from another application using the ModuleFederation plugin. I run them both on localhost. Shell app is on port 8080, BillingMFE app is on port 8082. When running the entire setup I can see that a bundle containing React is loaded once from the MFE app (by remoteEntry.js) and once by the Shell app. This causes the following error [https://reactjs.org/docs/error-decoder.html/?invariant=321](url)

This is the webpack config in Shell app:
```
new ModuleFederationPlugin({
      name: "ShellUI",
      library: { type: "var", name: "ShellUI" },
      remotes: {
        BillingMFE: "BillingMFE",
      },
      shared: [
        "react",
        "react-dom",
        "react-router-dom",
        "redux",
        "react-redux",
        "react-bootstrap",
        "@dds2/alpha",
      ],
    }),
```
This is in the config of the BillingMFE app:
```
new ModuleFederationPlugin({
      name: "BillingMFE",
      library: { type: "var", name: "BillingMFE" },
      filename: "remoteEntry.js",
      exposes: {
        "./App": "./src/App",
      },
      shared: [
        "react",
        "react-dom",
        "react-router-dom",
        "redux",
        "react-redux",
        "react-bootstrap",
        "react-loading-skeleton",
        "ag-grid-community",
        "ag-grid-react",
        "@dds2/alpha",
      ],
    }),
```

I load the remoteEntry.js in the head of index.html of the shell like this:
``` <script src="http://localhost:8082/remoteEntry.js"></script>```

And finally I import the remote component from the Shell app like this:
```
import React from "react";
import App from "BillingMFE/App";

const Billing = props => {
  return (
    <>
      <h1>Billing</h1>
      <App />
    </>
  );
};

export default Billing;
```

**What is the expected behavior?**
I expect that only a single copy of React be loaded as it is present in both "shared" arrays.

**Other relevant information:**
webpack version:  5.3.2
Node.js version: 14.15.0
Operating System: Windows 10

**Comment by evilebottnawi** [comment]
Please do not ignore fields in the issue template

> **If the current behavior is a bug, please provide the steps to reproduce.**

Do not ignore this, respect time of other, thanks
