### ISSUE TITLE
feature request: silence output using config

### ISSUE THREAD

**Issue by kentcdodds** [webpack/webpack#1191]
I originally asked this as a question on [StackOverflow](http://stackoverflow.com/q/30756804/971592) but the lack of response and some digging has lead me to believe that this is not possible. Here's the original question (copy/paste):

> I would like to know if there's a configuration option to tell webpack to only log the "important information" to the terminal. Pretty much just errors and warnings, not all of this:
> 
> ![output of terminal with webpack](http://i.stack.imgur.com/abVg5.jpg)
> 
> There's just so much output! Would love to suppress the common stuff and only have webpack output the warnings/errors. Would like a solution for `webpack`, `webpack-dev-server`, and `karma-webpack`.
> 
> *Note*: I tried `noInfo: true` and `quiet: true` but that didn't seem to do the trick.

I've dug around the code a bit and I don't think that there's anything in `webpack` or `webpack-core` to silence the output based on the config I give it (though it looks like `webpack-dev-server` does support this). I would really like to silence output for my tests so I can keep noise to a minimum.

Note: Keeping `webpack: bundle is now VALID` or `INVALID` I think would still be valuable. It's just the info about everything that was built is noisy.

**Comment by lukas-zech-software** [comment]
:+1: 
I would also like that very much as I use webpack to build my integration tests.
Having a watcher compile and run the tests on every file change comes with a lot of unnecessary console output, making the test results harder to read

This might also be solved by LogLevel:NONE as proposed in this issue #476

**Comment by burabure** [comment]
+1, having nodemon, post-css and other build drowned in 200lines of webpack verbosity is not nice =(

**Comment by hekar** [comment]
:+1: This is essential. Certain output is not relevant to all users. There should be an option to change the verbosity level.

**Comment by yanivtal** [comment]
+1

**Comment by SimenB** [comment]
#1323 might help?

**Comment by rtsao** [comment]
https://github.com/webpack/webpack-dev-server/issues/68

**Comment by johnnyreilly** [comment]
I'd love to see this as well.

**Comment by hsinha** [comment]
Passing chunks:false and chuckModules:false in the stats object solves this. https://webpack.github.io/docs/node.js-api.html

**Comment by lukas-zech-software** [comment]
```
stats.toString({chunks:false})
```

hsinha's solution reduced my build output to 1 line! :+1:

**Comment by bebraw** [comment]
@kentcdodds Is `stats.toString({chunks:false})` enough for you?

**Comment by johnnyreilly** [comment]
Works for me!

**Comment by kentcdodds** [comment]
Looks like it's working for me. Thanks for the help!

**Comment by kentcdodds** [comment]
For others looking at this, I actually prefer configuring it in my webpack config and I also prefer the `'errors-only'` option. So my webpack config has this:

```javascript
{
  devServer: {
    stats: 'errors-only',
  },
}
```

Thanks!

**Comment by burakhanalkan** [comment]
+1 for stats.toString({chunks:false}) solution.

**Comment by nightire** [comment]
@kentcdodds what else options can we have on `devServer.stats`?

**Comment by kentcdodds** [comment]
[Here's the relevent code](https://github.com/webpack/webpack/blob/5b5775f9e2fc73fea46629f2d6a3ed7a1f8424d3/lib/Stats.js#L696-L730). Looks like the acceptable preset values are: `none, errors-only, minimal, normal, verbose` and otherwise you can specify your own object:

```javascript
{
	hash: false,
	version: false,
	timings: false,
	assets: false,
	chunks: false,
	modules: false,
	reasons: false,
	children: false,
	source: false,
	errors: false,
	errorDetails: false,
	warnings: false,
	publicPath: false
}
```

**Comment by nightire** [comment]
@kentcdodds Thanks very much, very informative.

**Comment by TangHao1987** [comment]
`stats: 'errors-only'` works for me when using WebPackDevServer:
`new WebpackDevServer(webpack(webpackConfig), {
    publicPath: webpackConfig.output.publicPath,
    stats: 'errors-only',
    hot: true
  })`

**Comment by greypants** [comment]
@TangHao1987's solution also works with `webpack-dev-middleware`, which I'm using with BrowserSync.

**Comment by mgleason** [comment]
For anyone looking to silence the verbose output in the Relay examples (like relay-treasurehunt), this worked for me:

1. open "server.js"
2. search for "stats: {colors: true}"
3. change it to "stats: {chunks:false}"

**Comment by mik01aj** [comment]
Is there a way to supress all these messages also for `webpack` (and not just for `webpack-dev-server`)?

**Comment by mik01aj** [comment]
@IAMtheIAM I tried it, but it helps only for the dev server, not the build.

**Comment by ebenoist** [comment]
@mik01aj would you mind posting how to pass that option when running through karma?

**Comment by mccarter** [comment]
+1

**Comment by tomkel** [comment]
All of the possible options should really be in the documentation

**Comment by kentcdodds** [comment]
> All of the possible options should really be in the documentation

Agreed. Would you like to do that? It's really easy to update the documentation :+1:

<img width="343" alt="screen shot 2016-06-22 at 10 13 17 pm" src="https://cloud.githubusercontent.com/assets/1500684/16290868/8ca4be74-38c6-11e6-86eb-369053471638.png">

**Comment by mik01aj** [comment]
@ebenoist I don't use Karma... You can always file an issue in your karma webpack plugin (or webpack karma plugin, whatever)

**Comment by ebenoist** [comment]
@mik01aj sorry I bumped here from the karma thread and must have gotten lost on the way. If there is a way to silence chunks in the webpack config without using a cli flag and/or the webpack devserver I'd be happy to document the solution.

**Comment by mjw56** [comment]
@ebenoist in your entry `karma.config.js` try this:

```js
files: [ ... ],
plugins: [ ... ],
...
webpackMiddleware: {
  stats: {
    chunks: false,
  },
},
```

Note that you can use all the options @IAMtheIAM mentioned above. Hope this helps.

**Comment by ebenoist** [comment]
@mjw56 thanks this is exactly what I needed. I didn't realized I'd have to configure the middleware in this case. I appreciate your help!

**Comment by johnnyreilly** [comment]
I've slightly tweaked the documentation to draw attention to `chunks: false` here: https://webpack.github.io/docs/node.js-api.html

**Comment by andy-pro** [comment]
the best options:
`  stats: {
    colors: true,
    cached: false
  }`
only show changes

**Comment by bjunix** [comment]
Just for reference, here is the documentation for the `stats` option: https://webpack.js.org/configuration/stats/

**Comment by abdennour** [comment]
And if you tried all solutions above and it does not work. Check `devServer` again , it might you FORGET to delete the previous `stats` object .. and this is what happen for me  : 

```js
	devServer: {
           stats: {
		    errors: false,
		    errorDetails: false,
		    warnings: false,
		    publicPath: false
		},
		contentBase: 'build',
		historyApiFallback: true,
		progress: true,
		stats: 'errors-only', // <-- ⚠️ I forgot to remove this which override the first stats which whant i want
		host: HOST,
		port: PORT,
	}
```

**Comment by cchamberlain** [comment]
The above options didn't work for me on latest, I needed to add `maxModules: 0`

This is nearly silencing output for me:
```js
stats: {
            assets: false,
            cached: false,
            cachedAssets: false,
            children: false,
            chunks: false,
            chunkModules: false,
            chunkOrigins: false,
            colors: false,
            depth: false,
            entrypoints: false,
            errors: true,
            errorDetails: true,
            hash: false,
            maxModules: 0,
            modules: false,
            performance: false,
            providedExports: false,
            publicPath: false,
            reasons: false,
            source: false,
            timings: false,
            usedExports: false,
            version: false,
            warnings: false 
}
```

**Comment by jonathanconway** [comment]
This isn't fully working for me.

Even after setting `stats: 'none'`, I'm still getting the following outputted:
```
Project is running at http://0.0.0.0:8080/
webpack output is served from /
```

I really really want to suppress this, because I'm hosting webpack-dev-server in a docker container, which maps the port to a different port, and I don't want to confuse the user by printing two different port numbers to the output.

Is this worthy of an issue?

**Comment by tom10271** [comment]
I have set `stats: false`

But....


```
 46% building modules 301/332 modules 31 active ...e_modules/rxjs/operators/skipWhile.js[0m[91m 46% building modules 302/332 modules 30 active ...e_modules/rxjs/operators/skipWhile.js[0m[91m 46% building modules 302/333 modules 31 active ...e_modules/rxjs/operators/skipUntil.js[0m[91m 46% building modules 302/334 modules 32 active ...odules/core-js/modules/_to-integer.js[0m[91m 46% building modules 302/335 modules 33 active ...de_modules/rxjs/operators/skipLast.js[0m[91m 46% building modules 302/336 modules 34 active ...dules/urijs/src/SecondLevelDomains.js[0m[91m 46% building modules 302/337 modules 35 active ...ww/app/node_modules/urijs/src/IPv6.js[0m[91m 46% building modules 303/337 modules 34 active ...ww/app/node_modules/urijs/src/IPv6.js[0m[91m 46% building modules 304/337 modules 33 active ...ww/app/node_modules/urijs/src/IPv6.js[0m[91m 46% building modules 305/337 modules 32 active ...ww/app/node_modules/urijs/src/IPv6.js[0m[91m 46% building modules 305/338 modules 33 active ...www/app/node_modules/sifter/sifter.js[0m[91m 46% building modules 306/338 modules 32 active ...www/app/node_modules/sifter/sifter.js[0m[91m 46% building modules 307/338 modules 31 active ...www/app/node_modules/sifter/sifter.js[0m[91m 46% building modules 308/338 modules 30 active ...www/app/node_modules/sifter/sifter.js[0m[91m 46% building modules 308/339 modules 31 active ...pp/node_modules/urijs/src/punycode.js[0m[91m 46% building modules 308/340 modules 32 active ...p/node_modules/rxjs/operators/skip.js[0m[91m 46% building modules 308/341 modules 33 active ...node_modules/rxjs/operators/single.js[0m[91m 46% building modules 308/342 modules 34 active ...modules/rxjs/operators/shareReplay.js[0m[91m 46% building modules 308/343 modules 35 active .../node_modules/rxjs/operators/share.js[0m[91m 46% building modules 308/344 modules 36 active ...dules/rxjs/operators/sequenceEqual.js[0m[91m 46% building modules 308/345 modules 37 active ...de_modules/core-js/modules/_shared.js[0m[91m 46% building modules 308/346 modules 38 active ...p/node_modules
```

It is just part of the output, what can I do?

**Comment by ahmadawais** [comment]
Actually, these two work great.

```js
	// stats: 'minimal',
	stats: 'errors-only',
```

**Comment by ilyazub** [comment]
@tom10271, are you using [`ProgressPlugin`](https://github.com/webpack/docs/wiki/internal-webpack-plugins#progresspluginhandler)?

**Comment by mrcgrhrdt** [comment]
I finally found a way to (nearly) silence the output in `webpack-dev-server@4.7.3` in 2022! I leave it here to anyone who is interested.

Add this to your `webpackConfig`:
```js
devServer: {
  devMiddleware: {
    stats: {
      assets: false,
      chunks: false,
      hash: false,
      modules: false,
      source: false
    }
  }
}
```

This should do the deal

**Comment by suanmei** [comment]
> I finally found a way to (nearly) silence the output in `webpack-dev-server@4.7.3` in 2022! I leave it here to anyone who is interested.

not work

**Comment by alexander-akait** [comment]
@suanmei You can use it https://webpack.js.org/configuration/other-options/#level
