### ISSUE TITLE
feat: expose sibling compilers from compiler object in MultiCompiler mode

### ISSUE THREAD

**Issue by rishabh3112** [webpack/webpack#11911]
## Feature request
A `compiler.siblings` property so that we can access all compilers available in MultiCompiler mode through Compiler as well.

**What is the expected behavior?**
`compiler.siblings` to contain all child compilers of multi compiler.

**What is motivation or use case for adding/changing the behavior?**
While implementing interactive output mode in webpack-cli, I need the ability to access all compilers in multicompiler mode so that I can synchronize the output correctly.

**How should this be implemented in your opinion?**
1. Create `siblings` property in `Compiler.js`
2. Set siblings property in each childCompiler in the loop here https://github.com/webpack/webpack/blob/83a1def18015e05186d0f1e4ed9b5ae8cb61e807/lib/webpack.js#L43

**Are you willing to work on this yourself?**
Yes, I am willing to work on this.

**Comment by evilebottnawi** [comment]
@rishabh3112 we can have child compilation in child compilation (very deep), maybe you can describe deeply what do you want achieve

**Comment by rishabh3112** [comment]
Ability to access all compliers in case of mulitiple compilers.

**Comment by evilebottnawi** [comment]
Why we need access for child compilators? They are already in printed stats

**Comment by rishabh3112** [comment]
Each child compiler has it's own interactive plugin, I need to know when all of them have completed their compilation, this would be possible when I can access siblings of compiler.

**Comment by evilebottnawi** [comment]
hm, I think we should avoid adding interactive plugin for child compilations, at least it should disabled by default, for example, mini-css-extract-plugin creates many child compilations, it will be like spam in interactive mode

**Comment by rishabh3112** [comment]
I think we are not on same page. I am talking about child compilers i.e. `MultiCompiler.compilers` not about the compilation processes itself.

**Comment by evilebottnawi** [comment]
I'm a little confused :smile: But we can get `compiler.compilers`

**Comment by rishabh3112** [comment]
One can't register plugin on a `MultiCompiler` which has this `compilers` prop that you are mentioning as far as I know. It doesn't have `options` prop:
https://github.com/webpack/webpack/blob/83a1def18015e05186d0f1e4ed9b5ae8cb61e807/lib/MultiCompiler.js#L49

**Comment by rishabh3112** [comment]
So, should I go ahead with PR for the same?

**Comment by evilebottnawi** [comment]
@sokra Can you look?

**Comment by sokra** [comment]
Technically you can add plugins to the MultiCompiler too. This is only possible from the Node.js API and not from config, but that should be possible to do in the CLI.

Unrelated from that, we should allow to add plugins to the MultiCompiler from config too.

**Comment by rishabh3112** [comment]
> Technically you can add plugins to the MultiCompiler too

Can you point to me on how to do it?

**Comment by sokra** [comment]
> > Technically you can add plugins to the MultiCompiler too
> 
> Can you point to me on how to do it?

``` js
plugin.apply(multiCompiler);
```

Just like with normal compilers. It as similar hooks like the `Compiler` but not all of them.

**Comment by evilebottnawi** [comment]
@rishabh3112 it helps to solve a problem?

**Comment by rishabh3112** [comment]
Yeah it helps. Will try this out and see if this works 😅

**Comment by rishabh3112** [comment]
Yes it worked. Thanks everyone 😄
