### ISSUE TITLE
chunkhash's length wrong.

### ISSUE THREAD

**Issue by hufeng** [webpack/webpack#1192]
assetsChunk===========> {
 'mobile-bind': '/static/dist/0.bundle-mobile-bind-52ed7e504cb51b99a1c1b8e16bddf832.js',
 'email-bind': '/static/dist/1.bundle-email-bind-a7c26f0611608b24ceb9778f3e74b292.js',

but chunkfile only contains "52ed7e504cb51b99a1c1"

**Comment by luqin** [comment]
error on webpack@1.9.12.  you can use 1.9.11

**Comment by hufeng** [comment]
3ks @luqin 你碰到过类似的问题嘛？

**Comment by luqin** [comment]
@hufeng 今天升级遇到的，现在固定版本开发了，不然耽误别人工作

**Comment by hufeng** [comment]
@luqin 非常感谢 我们也是这样 升级到最新碰到了这个问题。现在是通过
filename: 'bundle-[name]-[chunkhash:20].js'这样绕过去的，我们也固定版本吧。

**Comment by gfranko** [comment]
I'm seeing this as well

**Comment by DekusDenial** [comment]
Yeah, i have the same issue around this. 3ks

**Comment by jhnns** [comment]
Yep, seems like a regression in 1.9.12

**Comment by jonaswindey** [comment]
A quick fix can be to change
```      filename: '[name]-[chunkhash].js',
      chunkFilename: '[name]-[chunkhash].js',
```
to
``` 
      filename: '[name]-[chunkhash:12].js',
      chunkFilename: '[name]-[chunkhash:12].js',
```
