### ISSUE TITLE
How to run examples?

### ISSUE THREAD

**Issue by 23cicada** [webpack/webpack#11929]
I executed the following steps
```
Run yarn in the root of the project.
Run yarn setup in the root of the project.
Run yarn add --dev webpack-cli in the root of the project.
Run node build.js in the specific example directory. (Ex: cd examples/commonjs && node build.js)
```
then report error
![image](https://user-images.githubusercontent.com/52289446/98211385-ed259100-1f7c-11eb-894c-3d94e1999689.png)

**Comment by sokra** [comment]
The examples still use the old webpack-cli. So you need to run `Run yarn add --dev webpack-cli@3` instead.

**Comment by evilebottnawi** [comment]
@sokra I sent a PR with updating

**Comment by alexander-akait** [comment]
Fixed
