### ISSUE TITLE
[Webpack 5] Reference error: __webpack_require__ is not defined

### ISSUE THREAD

**Issue by janlent1** [webpack/webpack#11924]
# Bug report

**What is the current behavior?**
I would like to upgrade our repo to webpack5. We have custom requires and custom dependency and templates. In webpack4, the dependency could be added without issues. Now though, the compiled code doesnt inlcude the __webpack_require__ inside the function argument, so the __webpack_require__ which we replaced doesnt work anymore. 
`/***/ 9126:
/***/ ((module) => {`
This is how the module is described, this is how it should be:
`/***/ 9125:
/***/ ((module, __unused_webpack_exports, __webpack_require__) => {`
How should we adapt the code of the dependency template so that this __webpack_require__ is added to the module arguments?  

**If the current behavior is a bug, please provide the steps to reproduce.**

This is company code, but maybe one could help that knows how these dependencies work and advice me how to adapt it manually :) 

**What is the expected behavior?**
Modules with custom requires should have the __webpack_require__ working, so that the code can access the __webpack_require__'s like below. 
`/***/ 9125:
/***/ ((module, __unused_webpack_exports, __webpack_require__) => {`
` 

**Other relevant information:**
webpack version:  5.3.2
Node.js version: 12.17.10
Operating System: MacOS
Additional tools:

**Comment by evilebottnawi** [comment]
It is breaking change, you need fix compatibility with webpack@5

> How should we adapt the code of the dependency template so that this webpack_require is added to the module arguments?

Please provide code how you do it

**Comment by janlent1** [comment]
@evilebottnawi thanks for the swift reply!
It is company code I cannot show it. But could i orientate myself at lib/dependencies/AMDRequireDependency.js at the AMDRequireDependencyTemplate where
`if (dep.functionRange && !dep.arrayRange) {
			const startBlock = ``${promise}.then((``;
			const endBlock = ``).bind(exports, __webpack_require__, exports, module)).catch(${RuntimeGlobals.uncaughtErrorHandler})``;
			runtimeRequirements.add(RuntimeGlobals.uncaughtErrorHandler);
` 
this has been added? Here they bind __webpack_require__ to the module? Or is that not the right place to find that? Or is there some simple require dependency that I could orientate myself after?
The template is something like this:
`
apply(dep, source, outputOptions, requestShortener) {
        if (!dep.range) {
            return
        }

        var actualContent
        var moduleDependency = outputOptions.moduleGraph.getModule(dep)
        actualContent = '__webpack_require__(' + JSON.stringify(moduleDependency.id)
        var lineDifference = dep.loc.end.line - dep.loc.start.line
        if (lineDifference > 0) {
            for (var i = 0; i < lineDifference; i++) {
                actualContent += '\n'
            }
        }
        actualContent += ')'
        source.replace(dep.range[0], dep.range[1] - 1, actualContent)
    }
`

**Comment by evilebottnawi** [comment]
Can you refactor the issue, it is not readable 

> It is company code I cannot show it. 

Unfortunately, most likely you will unanswered in this case, I do not ask to show all the code, I ask to show an example

You can look at code in https://github.com/webpack/webpack/tree/master/lib/dependencies

**Comment by janlent1** [comment]
@evilebottnawi sorry for the inconveniences. What else do you need to see? 
We hook into the custom require call inside the compilation when this call is executed. Then we add the dependency to the parser.state.current.addDependency.
Additionally we hook into the compilation and then execute this here:
```
compiler.hooks.compilation.tap(
        'CustomPlugin',
        function(compilation, params) {
            var normalModuleFactory = params.normalModuleFactory
            compilation.dependencyFactories.set(CustomRequireItemDependency, normalModuleFactory)
            compilation.dependencyTemplates.set(
                CustomRequireItemDependency,
                new CustomRequireItemDependency.Template()
            )
            compilation.dependencyFactories.set(ConstDependency, new NullFactory())
            compilation.dependencyTemplates.set(ConstDependency, new ConstDependency.Template())
        }
    )
``` 
Is this helpful?
The dependency itself is a simple dependency nothing crazy...

**Comment by sokra** [comment]
You need to declare the correct `runtimeRequirements` in your custom dependency. Choose one from `RuntimeGlobals`.

**Comment by janlent1** [comment]
Hi @sokra,
thanks as well for the answer! 
So you mean just adding runtimeRequirements from the outputOptions and call on it runtimeReqiurements.add(RuntimeGlobals.require)? I only need the __webpack_require__...
Or do we have to do more like creating this promise like in the template of lib/dependencies/AMDRequireDependency.js?

**Comment by sokra** [comment]
> runtimeReqiurements.add(RuntimeGlobals.require)

Yes that should be it.

**Comment by janlent1** [comment]
@sokra this seemed to work. 
Thanks so much! You saved me hours of work!!! :)) 

I am now having a problem regarding **require.context**, it throws errors that it cannot **resolve module** abc/def/ghiTest.js in blablablatoabc/ even though the path is blablablatoabc/abc/def/ghiTest.js.. do you know how to solve that or should i open up a new ticket? The require context is called with the path-alias,true, /[tT]est$/  that should find the ghiTest.js... When calling then the module not found warnings are thrown but when calling the specific test it seems to work, but the devtools cannot open up the test file... Very odd... In webpack 4 it worked though...

**Comment by evilebottnawi** [comment]
Please provide example

**Comment by janlent1** [comment]
@evilebottnawi 
Okay the above description is really all i can give you, this is more central coding. And as of now, it just gives out the warnings but the code actually works... I also don't know what exactly i could show you that could help here... Maybe I'll get back to it later.

What I would like to know though, is that I have a custom HtmlPlugin, and this used to be able to get the CSS as an asset for the html page during the **emit** phase. Now this moved to the **thisCompilation**(it adds assets) **processAssets** phase and there i tap at the **PROCESS_ASSETS_STAGE_ADDITIONS** phase. There it seems though, that the **css is not available as an asset yet though**. I am using the style-loader and css-loader for loading assets. Do you know which stage these css assets are available now?  I know the css processing is slightly different know but i don't understand why it is not emitted during this phase.
```
This is the sequence of the array for use when testing against test: /\.css$/,
use: ["style-loader?esModule=false",
{
        loader: 'css-loader',
        options: {
            modules: true, 
            esModule: false,
            url: false
        }
    }]
```

I am sorry for all these vague questions, but your help is so greatly appreciated, I fought with webpack 4 already so much and this is really saving me...

**Comment by evilebottnawi** [comment]
Because `style-loader` do not create new assets, only mini-css-extract-plugin

**Comment by janlent1** [comment]
@evilebottnawi you are right im sorry, we used the extracttextplugin and that still seemed to work in v4. I will try to upgrade to the mini-css-extract-plugin, and will come back to you in a bit. Let you know soon.
Thank you for your help!

**Comment by janlent1** [comment]
Hi @evilebottnawi TypeError: The 'compilation' argument must be an instance of Compilation is the error im getting when using mini-css-extract-plugin@1.2.1...

**Comment by evilebottnawi** [comment]
I want to close, because original problems was solved 

> TypeError: The 'compilation' argument must be an instance of Compilation is the error im getting when using mini-css-extract-plugin@1.2.1...


Double check what you don't have two webpack versions

**Comment by evilebottnawi** [comment]
Anyway feel free to feedback

**Comment by janlent1** [comment]
@evilebottnawi I figured it out and thanks for the info there! 
I have one more thing and it is the ParserHelpers.addParsedVariableToModule replacement.
[Here](https://github.com/GoogleChromeLabs/worker-plugin/issues/88#issuecomment-688568600) they talk about the replacement for this parser helper function. In the old way, you could set addParsedVariableToModule(parser,name,expression). How can i do that with the new way mentioned above?
I have to give a special expression to the expression argument, which sets a custom method there which extends __webpack_require__...

Thank you!

**Comment by janlent1** [comment]
@evilebottnawi  what i basically want to translate into webpack5 is this coding:
```
ParserHelpers.addParsedVariableToModule(
    parser,
    'CustomPluginFor' + Name.replace(/[.]/g, '_'),
    `__webpack_require__.map.set('${Name}', require.resolve(` +
    JSON.stringify(resPath + '.specialending') +
    '))'
)
```

**Comment by janlent1** [comment]
Seems like the only way for me to do it now is to transform this coding into a custom dependency?
