### ISSUE TITLE
ModuleFederation App Not Working as Described in Documentation

### ISSUE THREAD

**Issue by alex-vukov** [webpack/webpack#11921]
# Bug report

**What is the current behavior?**
According to ModuleFederation plugin documentation the loading of both the host and the component provider application must be moved to a bootstrap file which should then be imported dynamically in index.js. However in one of the webpack examples at [https://github.com/module-federation/module-federation-examples](url) this setup doesn't work and nothing is rendered on the screen.

**If the current behavior is a bug, please provide the steps to reproduce.**
To reproduce this issue get this repo [https://github.com/module-federation/module-federation-examples/tree/master/basic-host-remote](url) and in ```app1/src/index.js``` change:
```
import bootstrap from "./bootstrap";
bootstrap();
```
to
```
import("./bootstrap");
```
Then start app1 and app2 and when you navigate to http://localhost:3001 nothing is rendered on the screen. 

What's strange is that this bootstrap import works correctly in other examples like [https://github.com/module-federation/module-federation-examples/tree/master/bi-directional](url)

**What is the expected behavior?**
Expected behavior is for the dynamic bootstrap import to load the application or there to be some sort of documentation on why it can't be used in this exact scenario.

**Other relevant information:**
webpack: 5.4.0  
Node.js version:  14.15.0
Operating System: Windows 10
Additional tools:

**Comment by evilebottnawi** [comment]
Please open an issue in https://github.com/module-federation/module-federation-examples, it require more fixes
