### ISSUE TITLE
ModuleFederationPlugin's name may not include dashes

### ISSUE THREAD

**Issue by jpzwarte** [webpack/webpack#11923]
# Bug report

**What is the current behavior?**
`ReferenceError: ical is not defined`

**If the current behavior is a bug, please provide the steps to reproduce.**
`new ModuleFederationPlugin({ name: 'share-ical-link' })`

**What is the expected behavior?**
No error. Workaround is to use underscores: `share_ical_link`.

**Other relevant information:**
webpack version:  5.4.0
Node.js version: 
Operating System: 
Additional tools:

This is due to the generated code being eval'ed and name is used as a variable name: if(typeof share-ical-link !== \"undefined\")

**Comment by evilebottnawi** [comment]
Anyway feel free to send a fix, it should be easy

**Comment by kshitij86** [comment]
I'll fix this. @evilebottnawi can I get assigned?

**Comment by evilebottnawi** [comment]
Done

**Comment by kshitij86** [comment]
@jpzwarte @evilebottnawi  So if I understand the issue corectly, when defining a new `ModuleFederationPlugin`, we want to enforce that the name in the options object cannot have dashes and throw an error if it does? Is that correct? Or should it automatically convert dashes to underscores, or do both of the above tasks?

**Comment by jpzwarte** [comment]
@kshitij86 Since name is a string in `webpack.config.js`, it should accept any value and convert the text to a valid variable name imo.

**Comment by sokra** [comment]
It depends on the library type used. The default type is `var` which have problem with dashes.

If you want to add a validation, add it here:

https://github.com/webpack/webpack/blob/a01988f55a38a82fe66b1101fb10f8ffb0da6622/lib/library/AssignLibraryPlugin.js#L142

Check if `base` is an valid identifier.

**Comment by kshitij86** [comment]
@sokra After we check if `base` is a valid identifier, and find that it does include illegal dashes, should we modify the `base` property to replace dashes with underscores?
Or should we do something like `throw "In ModuleFederationPlugin, 'name' cannot include dashes";`

**Comment by evilebottnawi** [comment]
Throw an error

**Comment by evilebottnawi** [comment]
or maybe we can use `JSON.stringify` and maybe it will work

**Comment by kshitij86** [comment]
@evilebottnawi I tried implementing the error throwing part and it works perfectly when searching `base` for dashes. Submitting a PR for this issue now. 

![hyphen](https://user-images.githubusercontent.com/26821140/98275147-52e43e00-1fba-11eb-9683-821f36a87bcc.png)

**Comment by sokra** [comment]
> should we modify the `base` property to replace dashes with underscores?

no

> or maybe we can use `JSON.stringify` and maybe it will work

that won't work in this context. Other library types allow that and it's already implemented that way. e. g. `library.type: "global"` uses `self["name-with-dashes"] = `

**Comment by ChrisAckerman** [comment]
Related to https://github.com/webpack/webpack/issues/11949. A namespace would allow for the solution mentioned by @sokra

**Comment by ChrisAckerman** [comment]
My feeling is that while validation might be a good interim step. It's not correct longterm. The name that seems most logical to me is the name of the package itself. And `package.json` names can contain hyphens.

**Comment by kshitij86** [comment]
@ChrisAckerman What would be the most optimal solution then? I'm already working on a [fix using validation](https://github.com/webpack/webpack/pull/11934). Could you point me in a direction for the **namespace**?

**Comment by ChrisAckerman** [comment]
@kshitij86 See this issue https://github.com/webpack/webpack/issues/11949

**Comment by shaodahong** [comment]
also crash when name like `<%= path %>`

**Comment by martinkadlec0** [comment]
> It depends on the library type used. The default type is `var` which have problem with dashes.

What about the host? I see the default `remoteType` is `script` which seems to assume the `var` type on the remote, but if I change the library type on the remote to e.g. "window" (to support dashes etc.) then I have a problem on the host since changing the remoteType to anything other than `script` will mean I will lose the external script logic. :(

**Comment by sokra** [comment]
> then I have a problem on the host since changing the remoteType to anything other than `script` will mean I will lose the [external script logic](https://github.com/webpack/webpack/blob/master/lib/ExternalModule.js#L120).

add `remoteType: "script"`

**Comment by martinkadlec0** [comment]
> add `remoteType: "script"`

What do you mean? I was explaining that the `script` type is assuming `var` type on the remote, and so I can't easily use any other type without losing the script loading logic. Or am I missing something?

**Comment by alexander-akait** [comment]
Fixed by https://github.com/webpack/webpack/pull/11934/

**Comment by papagei-ma** [comment]
@shaodahong did find out more about the error. I keep getting it through multiple projects. Those were in angular 11, and then through ng update to angular 12. Is it a problem in Terser itself, Webpack or the libraries which terser is trying to  mangle/compress ?

**Comment by shaodahong** [comment]
> @shaodahong did you find out more about the error. I keep getting it through multiple projects. Those were in angular 11, and then through ng update to angular 12. Is it a problem in Terser itself, Webpack or the libraries which terser is trying to mangle/compress ?

Yep, incorrect name cause fail compress.

**Comment by papagei-ma** [comment]
> > @shaodahong did you find out more about the error. I keep getting it through multiple projects. Those were in angular 11, and then through ng update to angular 12. Is it a problem in Terser itself, Webpack or the libraries which terser is trying to mangle/compress ?
> 
> Yep, incorrect name cause fail compress.

Thanks. You mean incorrect names use in Libraries?, so how did you fix it?.

**Comment by monolithed** [comment]
> My feeling is that while validation might be a good interim step. It's not correct long term. The name that seems most logical to me is the name of the package itself. And `package.json` names can contain hyphens.

I believe you. `window['@foo/bar']` - is a correct variable and an obvious rule. 

```
enum Streams {
     FOO = '__foo_bar' // You need to look at the source code of the project to find out its name
}
```

```
enum Streams {
     FOO = '@foo/bar' // it's an obvious rule to have unique and readable names
}
```

**Comment by alexanderkhivrych** [comment]
https://okhivrych.io/module-federation-lifehack-custom-container-name
