### ISSUE TITLE
ModuleFederationPlugin's name may not include dashes

### ISSUE THREAD

**Issue by jpzwarte** [webpack/webpack#11922]
With webpack 5.4.0, if I use the `ModuleFederationPlugin` with `name: 'share-ical-link'`, I will get a `ReferenceError: ical is not defined` error at runtime. If I change the name to `share_ical_link`, the error goes away.

This is due to the generated code being eval'ed and `name` is used as a variable name: `if(typeof share-ical-link !== \"undefined\")`

Please fix this so `name` may include dashes.

**Comment by evilebottnawi** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

**Comment by evilebottnawi** [comment]
I will reopen it after you fix the issue template, please respect time of other developers, thanks
