### ISSUE TITLE
WARNING in asset size limit: The following asset(s) exceed the recommended size limit (977 KiB). This can impact web performance.

### ISSUE THREAD

**Issue by grknsolak** [webpack/webpack#11926]
WARNING in asset size limit: The following asset(s) exceed the recommended size limit (977 KiB).
This can impact web performance.
Assets: 
  5.js (1.91 MiB)
  6.js (1.14 MiB)
  8.js (1.02 MiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (391 KiB). This can impact web performance.
Entrypoints:
  truRequire (1.2 MiB)
      vendor.js
      truRequire.js

**Comment by evilebottnawi** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

You can disable it `performance: false`

**Comment by lmxyjy** [comment]
what? I want get more info...

**Comment by alexander-akait** [comment]
You don't ask something
