### ISSUE TITLE
Webpack load all files in node_module directory in development mode and dynamic import name

### ISSUE THREAD

**Issue by jcubic** [webpack/webpack#11936]
# Bug report

The issue reported to Codemirror codemirror/CodeMirror#5297 but in fact it's bug in Webpack development mode module loading. Webpack load everything that is in node_module, if module have invalid files (like html file) it give warnings in <5 and errors in version 5.

**What is the current behavior?**

Can't load Codemirror in development mode.

Webpack 5 throw error:

```
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <!doctype html>
| 
| <title>CodeMirror: RPM changes mode</title>
 @ ./node_modules/codemirror/mode/ sync ^\.\/.*\/.*$ ./rpm/changes/__
 @ ./src/a.js 10:4-46

ERROR in ./node_modules/codemirror/mode/rpm/xxx/zzz 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <XXXXXX
| 
 @ ./node_modules/codemirror/mode/ sync ^\.\/.*\/.*$ ./rpm/xxx/zzz
 @ ./src/a.js 10:4-46
```

Webpack 4 show warning.

I've create directory xxx and dummy file zzz with "<XXXXXX" content and Webpack try to load the file.

**If the current behavior is a bug, please provide the steps to reproduce.**

Here is simple example:
```
require('expose-loader?CodeMirror!codemirror/lib/codemirror');
require('expose-loader?debounce!debounce');
//require('expose-loader?LightningFS!../../lightning-fs');
require('expose-loader?LightningFS!../lightning-fs.min.js');
require("codemirror/lib/codemirror.css");
require('codemirror/addon/scroll/simplescrollbars');
require('codemirror/addon/scroll/simplescrollbars.css');
require("codemirror/addon/edit/matchbrackets");
['css', 'xml', 'javascript', 'htmlmixed', 'scheme'].forEach(function(mode) {
    require(`codemirror/mode/${mode}/${mode}`);
});
require("codemirror/theme/twilight.css");
```

the code is simple because I only use webpack to bundle dependencies no code is used.

here is my weback config, just basics:
```javascript
const path = require('path');
const webpack = require('webpack');
module.exports = {
    mode: "development", // "production",//
    entry: {
        'a': "./src/a.js",
        'b': "./src/b.js"
    },
    output: {
        filename: 'bundle-[name].js',
        path: path.resolve(__dirname)
    },
    module: {
        rules: [
            {
                test: () => true,
                sideEffects: true   // this so webpack don't remove code that is not used in dependency only files
            },
            {
                test: /\.css$/,
                use: ['style-loader', 'css-loader']
            }
        ]
    }
};
```

I use manual code splitting in my setup other file have different imports similar to this one.

**What is the expected behavior?**

It should load Codemirror without errors even if there are html files. In fact it should only load the files that I have in my imports.

**Other relevant information:**
webpack version:  5.4.0
Node.js version: v14.3.0
Operating System: Fedora GNU/Linux
Additional tools:

**Comment by jcubic** [comment]
This is something to do with import when using variables:

```javascript
['css', 'xml', 'javascript', 'htmlmixed', 'scheme'].forEach(function(mode) {
    require(`codemirror/mode/${mode}/${mode}`);
});
```
I think that the actual require that is called is not the one I have in code. The same probably happen for other case in Codemirror issue:

```javascript
import(`codemirror/mode/${this.options.mode}/${this.options.mode}`)
```

**Comment by jcubic** [comment]
Here is simplify example:
```
npm init -y
npm install --save webpack webpack-cli sysend
```

Same webpack file (without b.js) and a.js is:

```javascript
var mode = 'sysend.js';
require(`sysend/${mode}`);
```

running `npx webpack` give error:
```
ERROR in ./node_modules/sysend/LICENSE 1:4
Module parse failed: Unexpected token (1:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> MIT License
| 
| Copyright (c) 2018 Jakub T. Jankiewicz
 @ ./node_modules/sysend/ sync ^\.\/.*$ ./LICENSE
 @ ./a.js 2:0-25
```

**Comment by evilebottnawi** [comment]
Expected, please read https://webpack.js.org/guides/dependency-management/#require-with-expression

**Comment by evilebottnawi** [comment]
We are static analyzer, so it cannot know what is variable value, so we include all files, you can `ignore` some extensions, look at docs or setup loader for them

**Comment by evilebottnawi** [comment]
You should not use:
```
{
  test: () => true,
  sideEffects: true   // this so webpack don't remove code that is not used in dependency only files
},
```

it is unsafe

**Comment by jcubic** [comment]
@evilebottnawi what is the alternative to disable tree shaking for node_modules?

Also if webpack is static analizer then why it throw warnings like this:
```
Critical dependency: the request of a dependency is an expression
```
for require.resolve and no way to disable it, even I have mangle the code like this:
```javascript
       global_env.set('require.resolve', doc('require.resolve', function(path) {
            typecheck('require.resolve', path, 'string');
            var name = path.valueOf();
            var x = require;
            return x['resolve'](name);
        }, `(require.resolve path)

           Return path relative the current module.`));
```

it keep showing this line `x['resolve'](name);` as problematic. I just want to define function that call `require.resolve`.

**Comment by jcubic** [comment]
This was discussed in #8826 and the fix was provider, the eval seems to the only way to work with webpack.
