### ISSUE TITLE
Webpack devtool validation fails on 'eval-source-map'

### ISSUE THREAD

**Issue by actuallymentor** [webpack/webpack#11938]
# Bug report

**What is the current behavior?**

When running webpack with the below config object I receive the following error: `configuration.devtool should match pattern "^(inline-|hidden-|eval-)?(nosources-)?(cheap-(module-)?)?source-map$".`

```js
{
  entry: '/Users/mentor/dev/webpack-frontend-only/src/js/main.js',
  output: {
    filename: 'app-1604657698388.js',
    path: '/Users/mentor/dev/webpack-frontend-only/public/assets/js/'
  },
  module: { rules: [ [Object] ] },
  devtool: 'eval-source-map',
  plugins: [
    BrowserSyncPlugin {
      browserSyncOptions: [Object],
      options: [Object],
      browserSync: [Object],
      isWebpackWatching: false,
      isBrowserSyncRunning: false
    }
  ]
}
```

**If the current behavior is a bug, please provide the steps to reproduce.**

See configuration object above, see [regex101 preview](https://regex101.com/r/40d3vC/1) showing that the regex should match.

**What is the expected behavior?**

Webpack should compile as it did in `v4`.

**Other relevant information:**
webpack version:  `5.4.0`
Node.js version: `14.2`
Operating System: `OSX`
Additional tools: `zsh shell`

**Comment by actuallymentor** [comment]
When running without flag `-d` there seems to be no error and I have no idea why.

**Comment by evilebottnawi** [comment]
Why it is hard do not ignore, proving link on regexp and steps to reproduce is different `If the current behavior is a bug, please provide the steps to reproduce.`?

Sorry I can't give your answer because I don't know how you run webpack, what is full configuration and other information, for me `devtool: 'eval-source-map',` for fine, without problems.

I will reopen and give you answer when if you the issue template, try to respect time on other developers, thanks

**Comment by evilebottnawi** [comment]
Flag `-p` was removed, you need to use `--mode production`, flag `-d` require value, i.e. `-d eval-source-map`

**Comment by actuallymentor** [comment]
> Why it is hard do not ignore, proving link on regexp and steps to reproduce is different If the current behavior is a bug, please provide the steps to reproduce.? Sorry I can't give your answer because I don't know how you run webpack, what is configuration and/or other information, for me devtool: 'eval-source-map', for fine, without problems.

You seem needlessly frustrated. I thought a configuration object would be clear.

> Flag -p was removed, you need to use --mode production, flag -d require value, i.e. -d eval-source-map

As I commented I came to that conclusion, there is no mention of it in the migration guide though. `-d` used to mean 'development mode' not 'devtool mode'.

This is the recycling of a cli argument while changing it's usage but not documenting it in the warnings.

The issue was resolved, I hope you have a nice day.

**Comment by acao** [comment]
if anyone else runs into this issue even with perfectly valid `devtool` configuration options, it's 100% caused by accidentally passing `-d`. I will make a PR soon to fix this documentation issue, by telling the user to use --mode instead of -d
