### ISSUE TITLE
Webpack TypeScript types don't export 'Mode'

### ISSUE THREAD

**Issue by anaisbetts** [webpack/webpack#11930]
# Bug report

**What is the current behavior?**

Writing Webpack v5 configuration methods cannot be typed correctly:

```ts
function vendors({ mode }: { mode: string }): Configuration {
  return {
    mode,    // Type 'string' is not assignable to type 'Mode'.ts(2322)
    entry: {
      vendor: [npmExportsFile],
    },
    output: {
      filename: '[name].[contenthash:8].packages.js',
      library: '[name]_packages',
      path: OUTPUT_DIR,
      publicPath: PUBLIC_PATH,
    },
    plugins: [
      new webpack.DllPlugin({
        name: '[name]',
        path: path.join(OUTPUT_DIR, '[name].json'),
      }),
    ],
  }
}
```

**What is the expected behavior?**

Because `Mode` is not exported, it can't be used as the type in the above type signature instead of `string` here

**Other relevant information:**

webpack version:  5.4.0
Node.js version: 15.1.0
Operating System: Linux x86_64
Additional tools: Typescript v4.0.5

**Comment by sokra** [comment]
You don't need the type. Pass `"development"` or `"production"`. If you want to declare a type for it use: `{ mode: "development" | "production" }`

**Comment by anaisbetts** [comment]
@sokra oof, duplicating the type seems really Gross

**Comment by evilebottnawi** [comment]
You can get the `Mode` type using `Configuration["mode"]`
