### ISSUE TITLE
Why doesn't changing RawSource at renderModuleContent work?

### ISSUE THREAD

**Issue by zengpl** [webpack/webpack#11932]
# Bug report

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

before webpack5.0.0@alpha.17, it can work
```
plugins: [
  compiler.hooks.compilation.tap("ncc", compilation => {
    compilation.moduleTemplates.javascript.hooks.render.tap('xxx', (moduleSource, module, options) => {
      if (moduleSource._value) {
         // do something with moduleSource._value, it can work
      }
    })
  })
]
```

at webpack5.0.0+, it doesn't work
```
plugins: [
  compiler.hooks.compilation.tap("ncc", compilation => {
    webpack.javascreipt.JavascriptModulesPlugin.getCompilationHooks(compilation).renderModuleContent.tap('xxx', (moduleSource, module, options) => {
      if (moduleSource._value) {
         // do something with moduleSource._value, it doesn't work
      }
    })
  })
]
```

**Other relevant information:**
webpack version:  5.0.0
Node.js version: 12.18.3
Operating System: windows
Additional tools:

**Comment by evilebottnawi** [comment]
Because it was changed, you don't provide context - what is the problem, why you change it and etc, so we can't help, sorry
