### ISSUE TITLE
webpack 5.4 + react 17.0: Uncaught TypeError: superCtor is undefined

### ISSUE THREAD

**Issue by dmitryweiner** [webpack/webpack#11940]
# Bug report

**What is the current behavior?**
When I'm trying to build bundle, I get error in browser:
Uncaught TypeError: superCtor is undefined
    inherits inherits_browser.js:5
    js parser_stream.js:27

**If the current behavior is a bug, please provide the steps to reproduce.**
Install latest Webpack and React.
Here is package.json https://github.com/jyabka/Chat_Name/blob/54136bd46ad76b43934bc0b47258136501d7f89b/package.json
![Снимок экрана от 2020-11-06 21-44-33](https://user-images.githubusercontent.com/6175334/98379121-83d77800-2079-11eb-9e90-c436d670afa7.png)

**What is the expected behavior?**
When I downgrade webpack to 4.44, it works normally.

**Other relevant information:**
webpack version: 5.4 
Node.js version: 10.23
Operating System: Ubuntu 20.04
Additional tools:

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by dmitryweiner** [comment]
> Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

Here is the example:
```
git clone https://github.com/dmitryweiner/webpack-bug
cd webpack-bug
npm i
npm run dev
```

**Comment by vankop** [comment]
you need to provide correct pollyfill for stream `require('stream').Writable === undefined`

**Comment by dmitryweiner** [comment]
Thank you very much!

Now I get:
Uncaught ReferenceError: Buffer is not defined
    js util.js:103
    Webpack 45
![Снимок экрана от 2020-11-06 23-17-28](https://user-images.githubusercontent.com/6175334/98389234-5a711900-2086-11eb-8b65-f9b7f3e892bb.png)

**Comment by vankop** [comment]
this worked for me https://github.com/vankop/webpack-bug/commit/271f437af6fce5b29faa8ba0b0960ebb08a194cd

**Comment by dmitryweiner** [comment]
This error was caused by stream.js. I should read [the doc](https://webpack.js.org/blog/2020-10-10-webpack-5-release/#automatic-nodejs-polyfills-removed) more careful:
> webpack 5 stops automatically polyfilling these core modules and focus on frontend-compatible modules.

The issue can be closed.
