### ISSUE TITLE
webpack5.0 webpack-dev-server cannot  live reloading Webpage

### ISSUE THREAD

**Issue by tothethousand** [webpack/webpack#11943]
Start command：
![image](https://user-images.githubusercontent.com/50653328/98384143-5f36cc80-2088-11eb-9899-78b6f1004bf2.png)
congif：
![image](https://user-images.githubusercontent.com/50653328/98384237-7b3a6e00-2088-11eb-807f-b3a0fc314299.png)
version：
![image](https://user-images.githubusercontent.com/50653328/98384416-b50b7480-2088-11eb-9ada-5507956a986d.png)
detail：When I modify the JS file, I can trigger automatic packaging, but I can't automatically refresh the web page

**Comment by tothethousand** [comment]
webpack-5

**Comment by tothethousand** [comment]
> _仅针对维护者：_
> 
> * [ ]  webpack-4
> * [ ]  webpack-5
> * [ ]  虫子
> * [ ]  严重错误
> * [ ]  增强
> * [ ]  文件资料
> * [ ]  性能
> * [ ]  依存关系
> * [ ]  题

webpack-5

**Comment by evilebottnawi** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please respect time of other developers. It was known bug and tracker in webpack-dev-server, set `target: 'web'`
