### ISSUE TITLE
Attach ModuleFederationPlugin containers to a namespace

### ISSUE THREAD

**Issue by ChrisAckerman** [webpack/webpack#11949]
## Feature request

**What is the expected behavior?**

ModuleFederationPlugin should attach exposed containers to a namespace (e.g. `window.__webpack_module_federation_containers__.app1`)

**What is motivation or use case for adding/changing the behavior?**

- The current behavior of just attaching federated module containers to the window, is prone to collisions with window apis and globally attached libraries
- It breaks typescript typing when wiring in dynamic remotes.
- Container names cannot contain hyphens (current implementation uses `var containerName`).

**How should this be implemented in your opinion?**

The currently generated container script global assignment should be changed from

```
var containerName; containerName = ...
```

to

```
var __webpack_module_federation_containers__ = __webpack_module_federation_containers__ || {}; __webpack_module_federation_containers__['containerName'] = ...
```

For backwards compatibility, if the container name is var compatible, it would generate the following.

```
var containerName, __webpack_module_federation_containers__ = __webpack_module_federation_containers__ || {}; containerName = __webpack_module_federation_containers__['containerName'] = ...
```

**Are you willing to work on this yourself?**

yes

**Comment by sokra** [comment]
That's already possible via with config in the ModuleFederationPlugin:

``` js
library: {
  type: "var",
  name: ["containers", "containerName"]
}
```

**Comment by ChrisAckerman** [comment]
@sokra Ah, interesting. I did not know that.

**Comment by evilebottnawi** [comment]
Answered, feel free to feedback

**Comment by monolithed** [comment]
> That's already possible via with config in the ModuleFederationPlugin:
> 
> ```js
> library: {
>   type: "var",
>   name: ["containers", "containerName"]
> }
> ```

@sokra could you provide an example how to use it?

```diff
{
        new ModuleFederationPlugin({
            name: 'foo',
            filename: '[contenthash].js',
+            library: {
+                type: "var",
+                name: ["containers", "containerName"]
+            }
        })
}
```

**Before**:

```ts
window.foo // {}
```

**After**:

```js
window.foo // undefined
window.containers // undefined
window.containerName // undefined
````
