### ISSUE TITLE
types.d.ts: Plugin interface is incompatible to all Webpack Plugins

### ISSUE THREAD

**Issue by jantimon** [webpack/webpack#11947]
# Bug report

Type Error: `Type '(compiler: Compiler) => void' is not assignable to type '() => void'.ts(2322)`

**What is the current behavior?**

A plugin is a class with an `apply` function **without** a `Compiler` instance:

https://github.com/webpack/webpack/blob/7415a618460795874fdf95c8f03363ea96709d52/types.d.ts#L6638-L6640

All webpack plugins have an `apply` function **with** a `Compiler` instance:

https://github.com/webpack/webpack/blob/7415a618460795874fdf95c8f03363ea96709d52/types.d.ts#L134-L142

This is a problem as for example `createChildCompiler` is allowing only `Plugin[]`.  
That means that **all webpack plugins are incompatible** with `createChildCompiler`.

https://github.com/webpack/webpack/blob/7415a618460795874fdf95c8f03363ea96709d52/types.d.ts#L1502-L1506

**If the current behavior is a bug, please provide the steps to reproduce.**

```ts
import webpack from 'webpack';

const compilation = new webpack.Compilation(
/* 
    Please ignore this line
    its a shortcut to reduce the amount of code */null as any
);

compilation.createChildCompiler('demo', {}, [
  
  new webpack.AutomaticPrefetchPlugin()

])
```

<img width="401" alt="import_webpack_from__webpack___•_Untitled-1_—_html-webpack-plugin" src="https://user-images.githubusercontent.com/4113649/98438385-14e63780-20ea-11eb-9227-112f017a255a.png">

Therefore all webpack plugins produce the following type error:

```
Type 'AutomaticPrefetchPlugin' is not assignable to type 'Plugin'.
  Types of property 'apply' are incompatible.
    Type '(compiler: Compiler) => void' is not assignable to type '() => void'.ts(2322)
```

**What is the expected behavior?**

We should have either

```ts
declare interface Plugin {
	apply: (compiler: Compiler) => void;
}
```

or

```ts
declare interface WebpackPlugin extends  Plugin{
	apply: (compiler: Compiler) => void;
}

createChildCompiler(
		name: string,
		outputOptions: OutputNormalized,
		plugins: WebpackPluginPlugin[]
	): Compiler;
```

**Other relevant information:**
webpack version:  5.1.2
Node.js version: 10.13.0
Operating System: OS-X
Additional tools: typescript 4.0.3

**Comment by evilebottnawi** [comment]
PR welcome

**Comment by jantimon** [comment]
Will do 👍

**Comment by jantimon** [comment]
@evilebottnawi can you please take a look at #11948 ?

**Comment by bboydflo** [comment]
@jantimon I came to the same conclusion. Thanks for your PR

**Comment by evilebottnawi** [comment]
@jantimon fixed, can we close?

**Comment by jantimon** [comment]
Thanks for merging 👍
