### ISSUE TITLE
Remote can crash host app when using ModuleFederationPlugin

### ISSUE THREAD

**Issue by Rinaldo** [webpack/webpack#11944]
# Bug report

**What is the current behavior?**

An incorrectly configured remote can crash its host app

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/module-federation/module-federation-examples/blob/master/basic-host-remote
On [this line](https://github.com/module-federation/module-federation-examples/blob/master/basic-host-remote/app2/webpack.config.js#L13) change the value of `publicPath` to `"/"`

app2 still runs fine by itself
app1 throws a `ChunkLoadError`
Not only can the error not be caught in App.js, App.js and bootstrap.js don't even run

**What is the expected behavior?**

Remotes should never be able to crash their host apps. The dynamic import should return a promise that can be caught if needed, not throw strange errors that take down the whole app. If a team can deploy a broken remote that takes down every live app that consumes it, it means the whole federated network is unacceptably fragile.

**Other relevant information:**
webpack version:  5.4.0
Node.js version:  12
Operating System:  Mac

**Comment by evilebottnawi** [comment]
And what do you want? public path is wrong so you get the error

**Comment by Rinaldo** [comment]
what I want is to be able to protect app1 from errors in its remotes. There doesn't seem to be any way to catch the ChunkLoadError and display some sort of fallback.

**Comment by evilebottnawi** [comment]
Where you place `try`/`catch`, we don't have magic for errors

**Comment by ChrisAckerman** [comment]
Also ran into this. The dynamic import promise should be rejected, since the chunk error should happen within the bounds of that promise.

**Comment by csvan** [comment]
ping @ScriptedAlchemy

**Comment by ScriptedAlchemy** [comment]
This is a webpack level problem of requiring wrong chunks. You'd need to wrap that in try catch to see if it can even get there. Or use the low level api in an attempt to find it ahead of time and call it.

**Comment by jeffbmartinez** [comment]
I was trying to solve a similar issue where I wanted my container app to run even if a dependency was down.

I ended up using the `import()` function to import my dependency. My host app's `index.js` looks something like this:

```
import('./bootstrap').catch(error => console.log('The dependency is down'));
```
With that your host should survive any issues with loading up the dependent service.

**Comment by ScriptedAlchemy** [comment]
If you use the low level api - you can dynamically try and require the module and allow it to fail gracefully, checking ahead of time if the get request is successful. 

You can also use a promise / async external or other fallback pattern in remote modules I believe.

**Comment by ramesh-murugan-at-philips** [comment]
@Rinaldo , do you have a workaround for this issue? I am facing the same.

**Comment by ramesh-murugan-at-philips** [comment]
@ScriptedAlchemy , could you provide some sample code to overcome this issue?

**Comment by Rinaldo** [comment]
@ramesh-murugan-at-philips 

As @ScriptedAlchemy said, you can use the advanced api for dynamic remotes to have more control over script loading.

I adapted / simplified the following  from the [dynamic-remotes example](https://github.com/module-federation/module-federation-examples/blob/master/advanced-api/dynamic-remotes/app1/src/App.js)
```js
const loadScope = (url, scope) => {
  const element = document.createElement('script');
  const promise = new Promise((resolve, reject) => {
    element.src = url
    element.type = 'text/javascript'
    element.async = true
    element.onload = () => resolve(window[scope])
    element.onerror = reject
  })
  document.head.appendChild(element)
  promise.finally(() => document.head.removeChild(element))
  return promise
}

const loadModule = async (url, scope, module) => {
  try {
    const container = await loadScope(url, scope)
    await __webpack_init_sharing__('default')
    await container.init(__webpack_share_scopes__.default)
    const factory = await container.get(module)
    return factory()
  } catch (error) {
    console.error('Error loading module:', error)
    throw error
  }
}

const RemoteButton = React.lazy(() => loadModule(
  'http://localhost:3002/remoteEntry.js',
  'app2',
  './Button'
))
```
Try using it in the basic-host-remote example (app1/src/App.js). It catches the ChunkLoadError I was having issues with.

_I still don't think we should have to drop down to the low level api to get proper error handling though._

**Comment by kevinschaffter** [comment]
@Rinaldo, The above works with lazily loading React components.  How would you deal with importing a utility functions to use in a react component from a federated module?

**Comment by Rinaldo** [comment]
@kevinschaffter, the loadModule function returns a promise for a module, and a module is just an object with keys corresponding to the defined exports.

If you have a utils file in a remote like this:
```js
export const sayHello = () => console.log("hello")

export default () => console.log("I'm the default")
```
Then you can load and run those functions like so:
```js
loadModule(
    'http://localhost:3002/remoteEntry.js',
    'app2',
    './utils'
)
.then(module => {
    module.sayHello() // "hello"
    module.default() // "I'm the default"
})
```
For using the utils in a React component you could stick the above in an `onClick` but you probably want to use useState + useEffect to fetch the module once when the component mounts and then be able to use the functions synchronously

**Comment by PallavNav** [comment]
So what is the final outcome of this problem?

**Comment by felixmokross** [comment]
@Rinaldo  Thanks a lot for your workaround suggestion. I tried it for our case and it works great.

I agree this should be built into the core API of the Module Federation plugin. Not having discoverability and custom error handling is a huge disadvantage for enterprise apps. Our product should still be usable even if a remote is completely down or fails to load correctly. One of our remotes is also in an earlier development stage and therefore the remoteEntry.js doesn't even exist on some environments.

One slight addition: I modified the `loadScope` method to return the promise returned by `finally`. Otherwise any errors in the script loading lead to an uncaught promise rejection (leading to the CRA error overlay). However we want to handle this error gracefully and just log it to the console.

```js
const loadScope = (url, scope) => {
  …
  document.head.appendChild(element)
  return promise.finally(() => document.head.removeChild(element))
}
```

**Comment by dassum03-BH** [comment]
> @ramesh-murugan-at-philips
> 
> As @ScriptedAlchemy said, you can use the advanced api for dynamic remotes to have more control over script loading.
> 
> I adapted / simplified the following from the [dynamic-remotes example](https://github.com/module-federation/module-federation-examples/blob/master/advanced-api/dynamic-remotes/app1/src/App.js)
> 
> ```js
> const loadScope = (url, scope) => {
>   const element = document.createElement('script');
>   const promise = new Promise((resolve, reject) => {
>     element.src = url
>     element.type = 'text/javascript'
>     element.async = true
>     element.onload = () => resolve(window[scope])
>     element.onerror = reject
>   })
>   document.head.appendChild(element)
>   promise.finally(() => document.head.removeChild(element))
>   return promise
> }
> 
> const loadModule = async (url, scope, module) => {
>   try {
>     const container = await loadScope(url, scope)
>     await __webpack_init_sharing__('default')
>     await container.init(__webpack_share_scopes__.default)
>     const factory = await container.get(module)
>     return factory()
>   } catch (error) {
>     console.error('Error loading module:', error)
>     throw error
>   }
> }
> 
> const RemoteButton = React.lazy(() => loadModule(
>   'http://localhost:3002/remoteEntry.js',
>   'app2',
>   './Button'
> ))
> ```
> 
> Try using it in the basic-host-remote example (app1/src/App.js). It catches the ChunkLoadError I was having issues with.
> 
> _I still don't think we should have to drop down to the low level api to get proper error handling though._

How would this be used in angular?

**Comment by luistak** [comment]
> If you use the low level api - you can dynamically try and require the module and allow it to fail gracefully, checking ahead of time if the get request is successful.
> 
> You can also use a promise / async external or other fallback pattern in remote modules I believe.

Do you have an example of how to approach fallbacks on remote module failures without that [hacky loadRemote](https://github.com/webpack/webpack/issues/11944#issuecomment-747082733)?

What i ended doing was:

```tsx
export const loadRemoteModule: LoadModule = async (baseURL, scope, module) => {
  const url = `${baseURL}/remoteEntry.js`;

  try {
    const container = await loadScope(url, scope);
    await __webpack_init_sharing__('default');

    await container.init(__webpack_share_scopes__.default);
    const factory = await container.get(`./${module}`);

    return factory();
  } catch (error) {
    console.error('Error loading module:', error);

    return {
      default: () => <AppSetupError error={error} />,
    };
  }
};
```

It seems a bit hacky but kinda works 🤷, my problem is that my shell app kinda breaks when a specific team uploads a malformed remoteEntry path, so my objective is to have a fallback for those cases but it does not seem right this solution

**Comment by ScriptedAlchemy** [comment]
Module-federation.io we have runtime apis now in v2
