### ISSUE TITLE
Uncaught TypeError: Cannot read property 'call' of undefined when import from node_modules

### ISSUE THREAD

**Issue by Scorpovi4** [webpack/webpack#11950]
# Bug report

Error message: **Uncaught TypeError: Cannot read property 'call' of undefined**

compiled line with error:

`/* harmony import */ var lightgallery_dist_js_lightgallery_all_min__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__("./node_modules/lightgallery/dist/js/lightgallery-all.min.js");`

```
// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
```

webpack config:
```
{
         mode: λ.isDevelopment ? 'development' : 'production',
              output: {
                pathinfo: false,
              },
              plugins: [],
              module: {
                rules: [
                  {
                    test: /\.js$/,
                    exclude: /(node_modules)/,
                    use: {
                      loader: 'babel-loader',
                      options: {
                        presets: ['@babel/preset-env'],
                      },
                    },
                  },
                ],
              },
              optimization: {
                namedModules: true,
                namedChunks: true,
                splitChunks: {
                  cacheGroups: {
                    default: false,
                    vendors: false,
                    vendor: {
                      chunks: 'all',
                      test: /node_modules/,
                    },
                  },
                },
              },
            }
```

module code:

```
import 'lightgallery/dist/js/lightgallery-all.min';
export default (() => {
  console.log($('#light-gallery'));
  //$('#light-gallery').lightGallery();

  $('.js-product-gallery').on('click', () => {
    console.log('click');
    //$('#light-gallery').trigger('click');
  });
})();
```

**What is the expected behavior?**

Providing correct import from node_modules folder without errors. 

Import from the rest paths works well.

**Other relevant information:**
webpack version:  latest
Node.js version: **v10.13.0**
Operating System: Windows 10

**Comment by evilebottnawi** [comment]
Can't reproduce, please provide minimum reproducible test repo

**Comment by Scorpovi4** [comment]
> Can't reproduce, please provide minimum reproducible test repo

Test repo is ready here https://github.com/Scorpovi4/test . Local deployment in Readme file.

The case already simulated with adding import from node_modules to the `_HTML/src/assets/js/_pages/page-index.js`

The config of webpack for pages is on path: `_HTML/components/js-pages.js`

**Comment by evilebottnawi** [comment]
Just note - `webpack-stream` uses `webpack@4`, please consider to update (open an issue in `webpack-stream` repo), something wrong with `webpack-stream` or your gulp setup, you invalid order of webpack output in your HTML file, it should be:
```
<script defer src="assets/js/page-index.js"></script>
<script defer src="assets/js/libraries.js"></script>
```

nothing to do in webpack, I would say even more, you have a completely wrong setting, avoid using `splitChunks` if you concat output, it doesn't make sense and even unsafe
