### ISSUE TITLE
ReferenceError: __WEBPACK_DEFAULT_EXPORT__ is not defined when running a bundle with circular dependencies

### ISSUE THREAD

**Issue by ezze** [webpack/webpack#11958]
# Bug report

**What is the current behavior?**

With Webpack 5.4.0 when using circular dependencies I get an error at runtime for my Node.js project (transpilation is done without any errors and warnings):

```
ReferenceError: __WEBPACK_DEFAULT_EXPORT__ is not defined
```

**If the current behavior is a bug, please provide the steps to reproduce.**

I narrowed down the problem in my real project. Here is a repo to reproduce: https://github.com/ezze/webpack-5-circular

A minimal code snippet:

*Job.js*

```javascript
import JobProductOutput from './JobProductOutput';

import { defineModel } from './helpers.js';

const Job = defineModel({
  id: {
    type: 'integer',
    primaryKey: true,
    autoIncrement: true
  }
});

export default Job;
```

*JobProductOutput.js*

```javascript
import Job from './Job';

import { defineModel } from './helpers';

const JobProductOutput = defineModel({
  id: {
    type: 'integer',
    primaryKey: true,
    autoIncrement: true
  },
  jobId: {
    field: 'job_id',
    type: 'integer',
    allowNull: false,
    references: {
      model: Job,
      key: 'id'
    },
    onUpdate: 'cascade',
    onDelete: 'cascade'
  }
})

export default JobProductOutput;
```

*helpers.js*

```javascript
export function defineModel(options) {
  // TODO: implement
  console.log(options);
  return {};
}
```

**What is the expected behavior?**

Expected to work without any errors at runtime as it was with Webpack 4.

**Other relevant information:**
webpack version: 5.4.0
Node.js version: 10.22.0
Operating System: Kubuntu 20.04.1 LTS

**Comment by sokra** [comment]
This is working as expected. You are using `Job` before it's defined. In webpack 4 this incorrectly returned `undefined` when it should cause an error instead.

**Comment by ezze** [comment]
@sokra, thanks for clarification and sorry for this. I thought it was working but you're right about `undefined` value of the import in Webpack 4. I should reorganize my source code somehow then.
