### ISSUE TITLE
HMR does not pick up changes from dependency packages inside "node_modules"

### ISSUE THREAD

**Issue by birdofpreyru** [webpack/webpack#11952]
# Bug report

**What is the current behavior?**

HMR does not pick up changes from dependency packages inside `node_modules`, and it looks like `package.json` of dependency packages acts as a barrier (explanation below).

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Clone [https://github.com/birdofpreyru/webpack5-bug1.git](https://github.com/birdofpreyru/webpack5-bug1.git)
2. Go into `host` folder.
3. `npm install`
4. Manually create a file at path `./node_modules/test/index.js`, with simple content `console.log('Check Point')`.
5. Run the code with `npm start`, then browse to `localhost:8080`. In the browser console you will see the message from the file you created at step (4), and also from the `./index.js` file.
6. HMR is enabled, if you edit the message inside `./index.js` or `./node_modules/test/index.js` you will see the page is automatically re-loaded and the new message is printed in the browser console.
7. Now manually create the file `./node_modules/test/package.json`, with empty object `{}` as the content, restart the server, and reload the page in browser. Try to edit the message inside `./node_modules/test/index.js`. You will see HMR does not see that change now, prining `Nothing changed` in the browser console.

**What is the expected behavior?**

HMR should pick-up changes from dependencies. It definitely worked in Webpack@4.

**Other relevant information:**
webpack version:  5.4.0
Node.js version: 14.15.0
Operating System: Ubuntu 20.04.1
Additional tools:

**Comment by evilebottnawi** [comment]
You **should not** tocuh files in node_modules, you can disable use using https://webpack.js.org/configuration/other-options/#cachemanagedpaths

**Comment by birdofpreyru** [comment]
Thanks @evilebottnawi ! I agree to you regarding the normal workflow, but for debugging/developing libraries it is super-useful to watch selected libraries in `node_modules`, to edit their code and immediately see the effect on a host codebase. I guess, with the config option you pointed out I'll be able to achieve that again in my development setup.

My suggestion is to mention that in Webpack configuration documentation. Before creating this ticket, I was trying to figure out why it does not work anymore with Webpack@5, and the furthest I arrived in the docs was [`watchOptions.ignored` documentation](https://webpack.js.org/configuration/watch/#watchoptionsignored), and thinking that `node_modules` is ignored by default. I think, you should mention there that caching-related config options also affect the watching of `node_modules`, and should be checked out first.

**Comment by evilebottnawi** [comment]
@birdofpreyru Can you open an issue in webpack docs repo?

**Comment by ezze** [comment]
@alexander-akait Is it possbile to ignore everything in `node_modules` excepting single subdirectory. I tried the following to exclude scoped packages from being ignored but seems that globs don't work here.

```javascript
snapshot: {
  managedPaths: [
   nodeModulesPath,
   `!${path.resolve(nodeModulesPath, '@geoapps')}`
  ]
}
```

```
[webpack-cli] Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.snapshot.managedPaths[1]: The provided value "!/home/ezze/Development/geomonitor/node_modules/@geoapps" is not an absolute path!
   -> A path to a managed directory (usually a node_modules directory).
```

**Comment by alexander-akait** [comment]
I think you want to have this https://github.com/webpack/webpack/issues/12112

**Comment by MaximBalaganskiy** [comment]
We hacked around this by monkey patching `FileSystemInfo`
```js
const FileSystemInfo = require('webpack/lib/FileSystemInfo');
const FileSystemInfoFix = require('./FileSystemInfo');
FileSystemInfo.prototype.createSnapshot = FileSystemInfoFix.prototype.createSnapshot;
```

The local `FileSystemInfo.js` is basically a copy of existing file with a single edit
```js
		const checkManaged = (path, managedSet) => {
			// patch begin
			if(path.includes('your-package-name')){
				return false;
			}
			// patch end
			for (const immutablePath of this.immutablePathsWithSlash) {

```

**Comment by djErock** [comment]
> You **should not** touch files in node_modules, you can disable use using https://webpack.js.org/configuration/other-options/#cachemanagedpaths. In a normal workflow, developers usually don't change `node_modules` files, so we optimize working with this to improve performance. Feel free to feedback

WIth more and more wide spread adoption of micro front end applications in the industry and the cumbersome nature of mono-repos, it may be time to rethink this...

**Comment by djErock** [comment]
I have a suite of packages that are deployed to multiple projects in an enterprise environment. I have the dev config set as such:

`devServer: {
    historyApiFallback: true,
    open: true,
    compress: true,
    port: 3000,
    // watchFiles: [
    //   '../src/**',
    //   '../public/**',
    //   '../node_modules/vcrm*/**',
    // ],
  },
  watchOptions: {
    ignored: [
      '../node_modules/!(vcrm*)/**', // Do not ignore any updates to vcrm project folders
    ],
  },`
  
  I update my package in the separate workspace and webpack pushes the build files into the node_module folder correctly.
  
  I even see webpack pick up on the change printing this in the terminal.
  
  `assets by status 90.1 MiB [cached] 42 assets
asset index.html 3.53 KiB [emitted] 1 related asset
cached modules 34.2 MiB (javascript) 26.7 KiB (runtime) [cached] 2419 modules
webpack 5.70.0 compiled successfully in 3195 ms
assets by status 90.1 MiB [cached] 42 assets
asset index.html 3.53 KiB [emitted] 1 related asset
cached modules 34.2 MiB (javascript) 26.7 KiB (runtime) [cached] 2419 modules
webpack 5.70.0 compiled successfully in 1780 ms
assets by status 90.1 MiB [cached] 42 assets
asset index.html 3.53 KiB [emitted] 1 related asset
cached modules 34.2 MiB (javascript) 26.7 KiB (runtime) [cached] 2419 modules
webpack 5.70.0 compiled successfully in 1286 ms`

However, when the browser goes to reload/recompile:

`[webpack-dev-server] App updated. Recompiling...
index.js?e2a7:551 [webpack-dev-server] App updated. Recompiling...
index.js?e2a7:551 [webpack-dev-server] Nothing changed.
index.js?e2a7:551 [webpack-dev-server] Nothing changed.
index.js?e2a7:551 [webpack-dev-server] App updated. Recompiling...
index.js?e2a7:551 [webpack-dev-server] App updated. Recompiling...
index.js?e2a7:551 [webpack-dev-server] Nothing changed.
index.js?e2a7:551 [webpack-dev-server] Nothing changed.`

**Comment by vithano** [comment]
> I have a suite of packages that are deployed to multiple projects in an enterprise environment. I have the dev config set as such:
> 
> `{
>   devServer: {
>     historyApiFallback: true,
>     open: true,
>     compress: true,
>     port: 3000,
>     watchFiles: [
>       '../src/**',
>       '../public/**',
>       '../node_modules/vcrm*/**',
>     ],
>   },
>   watchOptions: {
>     ignored: [
>       '../node_modules/!(vcrm*)/**', // Do not ignore any updates to vcrm project folders
>     ],
>   },
>  }`
> 
>   
>   I update my package in the separate workspace and webpack pushes the build files into the node_module folder correctly.
>   
>   I even see webpack pick up on the change printing this in the terminal.
> 
> - assets by status 90.1 MiB [cached] 42 assets
> - asset index.html 3.53 KiB [emitted] 1 related asset
> - cached modules 34.2 MiB (javascript) 26.7 KiB (runtime) [cached] 2419 modules
> - webpack 5.70.0 compiled successfully in 3195 ms
> - assets by status 90.1 MiB [cached] 42 assets
> - asset index.html 3.53 KiB [emitted] 1 related asset
> - cached modules 34.2 MiB (javascript) 26.7 KiB (runtime) [cached] 2419 modules
> - webpack 5.70.0 compiled successfully in 1780 ms
> - assets by status 90.1 MiB [cached] 42 assets
> - asset index.html 3.53 KiB [emitted] 1 related asset 
> - cached modules 34.2 MiB (javascript) 26.7 KiB (runtime) [cached] 2419 modules
> -  webpack 5.70.0 compiled successfully in 1286 ms
> 
> 
> However, when the browser goes to reload/recompile:
> 
> - [webpack-dev-server] App updated. Recompiling...
> - index.js?e2a7:551 [webpack-dev-server] App updated. Recompiling...
> - index.js?e2a7:551 [webpack-dev-server] Nothing changed.
> - index.js?e2a7:551 [webpack-dev-server] Nothing changed.
> - index.js?e2a7:551 [webpack-dev-server] App updated. Recompiling...
> - index.js?e2a7:551 [webpack-dev-server] App updated. Recompiling...
> - index.js?e2a7:551 [webpack-dev-server] Nothing changed.
> - index.js?e2a7:551 [webpack-dev-server] Nothing changed.
> 
> 

Hi im having the same issue using relative-deps to load my local package, did you manage to solve it?

**Comment by birdofpreyru** [comment]
Setting [snapshot.managedPaths](https://webpack.js.org/configuration/other-options/#snapshot) to empty array will sickle the problem disabling the cashing, probably other snapshot options allow to fine-tune it in a more optimal way.

**Comment by faceyspacey** [comment]
@vithano I'm also using relative-deps -- the `managedPaths` option with the regex to exclude your package "works", but there's another issue:

webpack seems to reload too quickly 75% of the time, missing some of the files transferred via `relative-deps`. Have you seen this issue? Any ideas for workarounds?
