### ISSUE TITLE
Missing onResourceLoad hook from RequireJS for purposes of decorating module with file path

### ISSUE THREAD

**Issue by mbixby** [webpack/webpack#1196]
> [[onResourceLoad](https://github.com/jrburke/requirejs/wiki/Internal-API:-onResourceLoad) is] an internal hook that can be used to get notifications of when a module is created/has an exports value, so that it is possible to trace the modules and their dependencies.

I was using it to assign file path to certain exported modules for their identification (in runtime). This feature has been requested many times in this issue tracker, I haven't found any definitive answers. `__filepath` constant is not enough.

I know I need to rewrite `__webpack_require__` to extend `module-obj` with the file path but it would save me some time if somebody could point me in the right direction as to where / how to build the moduleId–>filePath map and how to pass the map over to lib/MainTemplate.

Also please tell me if this feature would be accepted as a PR so I don't waste time on integration / config flag / docs / tests.

**Comment by mbixby** [comment]
Something like this?
```js
    this.plugin("local-vars", function(source/*, chunk, hash*/) {
        var modulesWithExposedPath = chunk.modules.filter(function(module){
            return module.rawRequest.match(/^\.viewmodels/);
        })
        return this.asString([
            source,
            "// The module cache",
            "var installedModules = {};",
            this.requireFn() + ".moduleRequestPaths = {",
                modulesWithExposedPath.map(function(module, idx){
                    return idx + ": " + module.rawRequest + ",";
                }),
            "}"
        ]);
    });
```
Then modulePaths exposed

**Comment by sokra** [comment]
https://github.com/webpack/webpack/commit/a04ffb928365b19feb75087c63f13cadfc08e1eb

Add `new webpack.NamedModulesPlugin()` and your module ids are full names.

This way you will see the name when HMR updates some modules.

**Comment by mbixby** [comment]
Do you know what was the original reason behind numbers as module IDs? Was it just perf or did somebody want to hide path information?

**Comment by sokra** [comment]
Smaller bundles and hiding path infos
