### ISSUE TITLE
npm WARN ajv-keywords@3.5.2 requires a peer of ajv@^6.9.1 but none is installed

### ISSUE THREAD

**Issue by hassaans** [webpack/webpack#11969]
# Bug report

**What is the current behavior?**
npm WARN ajv-keywords@3.5.2 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
inclusion of ajv in package.json

**Other relevant information:**
webpack version:  4.44.2
Node.js version: 14.15.0
Operating System: OSX 10.15.7
Additional tools:

**Comment by evilebottnawi** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please fill out all fields.
