### ISSUE TITLE
assets modules won't work for inline html <img>

### ISSUE THREAD

**Issue by tr1s** [webpack/webpack#11968]
# Bug report

**What is the current behavior?**

I know I can import using js, but how can I import in an HTML file or CSS file in Webpack 5?

doing this in css/sass:

`background: url("../../images/image.png");`

or this in html template:

`<img class="logo-img" src="images/favicon.svg" alt="website logo" />`

doesn't work. I just get broken links. What am I missing for these asset modules? I've tried them all in all combos with all file extensions. I've been adding and deleting stuff but here's what I have latest:

<img width="83" alt="CleanShot 2020-11-10 at 22 21 35@2x" src="https://user-images.githubusercontent.com/19172250/98761761-29edef80-23a4-11eb-8842-ca4545b858ae.png">

**If the current behavior is a bug, please provide the steps to reproduce.**

```
  module: {
    rules: [
      {
        test: /\.txt$/,
        type: 'asset/source'
      },
      {
        test: /\.(?:ico|gif|png|jpg|jpeg)$/i,
        type: 'asset/resource'
      },
      {
        test: /\.(woff(2)?|eot|ttf|otf|svg|)$/,
        type: 'asset/inline'
      },
      {
        test: /\.js$/, exclude: /node_modules/,
        use: ['babel-loader']
      },
      {
        test: /\.(scss|css)$/,
        use: [
          'style-loader',
          {
            loader: 'css-loader',
            options: {
              sourceMap: true,
              importLoaders: 1
            }
          },
          {
            loader: 'postcss-loader',
            options: {
              sourceMap: true
            }
          },
          {
            loader: 'sass-loader',
            options: {
              sourceMap: true
            }
          },
        ],
      },
    ],
  },
```

**What is the expected behavior?**

The image shows up on the page.

**Other relevant information:**
webpack version: `5.4.0`
Node.js version: `14.4.0`
Operating System: macOS latest version

**Comment by evilebottnawi** [comment]
Sorry, can't reproduce, please provide reproducible test repo and I will reopen it, part of configuration is not enough to help you

**Comment by evilebottnawi** [comment]
For HTML you need `html-loader`, for CSS you need `css-loader`

**Comment by tr1s** [comment]
@evilebottnawi [here's a test repo](https://github.com/tr1s/webpack-5) of my setup. Just `npm i` then `npm-start` and as you can see the logo in the header doesn't work (using inline html), but now the `background: url` (my mistake).

**Comment by evilebottnawi** [comment]
bug in html-webpack-plugin, please open an issue

**Comment by jantimon** [comment]
I just tried and everything seems to work:

https://codesandbox.io/s/html-webpack-plugin-5x-alpha-html-loader-q5cg3?file=/src/template.ejs

**Comment by evilebottnawi** [comment]
@jantimon fixed in v5?

**Comment by jantimon** [comment]
the asset integration has not been changed since html-webpack-plugin 2

**Comment by evilebottnawi** [comment]
Please look at
```
 {
        test: /\.txt$/,
        type: 'asset/source'
      },
      {
        test: /\.(?:ico|gif|png|jpg|jpeg)$/i,
        type: 'asset/resource'
      },
      {
        test: /\.(woff(2)?|eot|ttf|otf|svg|)$/,
        type: 'asset/inline'
      },
```

**Comment by jantimon** [comment]
oh you are right I used the url loader for the png

**Comment by jantimon** [comment]
if I use `asset/source` webpack@5 crashes and says that `publicPath: 'auto'` is not supported

if I use `asset/source` and `publicPath: ''` it works:

https://codesandbox.io/s/html-webpack-plugin-5x-alpha-html-loader-assetressource-rr0hu?file=/package.json

**Comment by evilebottnawi** [comment]
It is very bad what `html-webpack-plugin` doesn't support `publicPath: 'auto'`

**Comment by evilebottnawi** [comment]
Big blocker for great feature

**Comment by jantimon** [comment]
`html-webpack-plugin` supports `publicPath: 'auto'` 

it works perfectly with the `url-loader` and `publicPath: 'auto'` however if you switch from `url-loader` to `asset/source` it fails

**Comment by jantimon** [comment]
Just try it out in this codesandbox:

https://codesandbox.io/s/html-webpack-plugin-5x-alpha-html-loader-q5cg3?file=/webpack.config.js

**Comment by evilebottnawi** [comment]
@jantimon hm, should work, I have 502 on codesandbox, maybe you can create reproducible test repo using `github`?

**Comment by jantimon** [comment]
Sorry I don't know why webpack-cli is no longer supporting codesandbox - I'll create an issue..

You can download a codesandbox here: ![export-zip](https://user-images.githubusercontent.com/4113649/98946841-b5769600-24f4-11eb-9b9e-634f83d851ee.png)

**Comment by sokra** [comment]
`publicPath: "auto"` doesn't work in node.js and html-webpack-plugin runs the child compiler bundle in node.js.
Within node.js webpack can't figure out the public path.
I think it should be fixable by using a relative public path in the child compiler `publicPath: publicPath === "auto" ? "" : publicPath`

**Comment by jantimon** [comment]
Good idea @sokra 👍

**Comment by tr1s** [comment]
hi @jantimon , @alexander-akait I'm getting around to checking this again. Was there any progress made on using `asset/modules` yet?

also, even with just using `url-loader` I can't get this to work on [my repo](https://github.com/tr1s/webpack-5).

In `src/template.html` on line 55, the image will resolve (no errors), but I still can't see the image. Any idea what I'm doing wrong here since I just want to go back to the old way and use `url-loader`?

**Comment by jantimon** [comment]
The latest alpha of the html-webpack-plugin has partial support for asset/resource:

https://github.com/jantimon/html-webpack-plugin/blob/next/examples/javascript/webpack.config.js

**Comment by alexander-akait** [comment]
@tr1s What do you mean?
