### ISSUE TITLE
Tree shaking not working as expected

### ISSUE THREAD

**Issue by tmeyer2115** [webpack/webpack#11961]
I've got a relatively simple library that I'm using Webpack to bundle. The library is made available on the `window`. I can't get tree shaking to work as I would expect. Roughly, my code is structured something like this:

entry.js
```
import Formatters from './formatters/formatters';

export { Formatters };
```

formatters/formatters.js
```
import { formatAttribute, prettyPrint } from './formatters-internal';

const Formatters = {
  formatAttribute,
  prettyPrint,
};

export { Formatters as default };

```

and formatters/formatters-internal.js
```
import prettyFormat from 'pretty-format';

export function prettyPrint(val) {
  return prettyFormat(val);
}

export function formatAttribute(object, key='test') {
  if (!object[key]) {
    return '';
  }
  return `${object[key]}`;
}
```

In `formatters.js`, I would expect that if I delete `prettyPrint` from the `import` statement and the `Formatters` object, the `pretty-format` dependency is not included in my bundle. This isn't the case. It's still part of the bundle. I have to go into `formatters-internal` and actually delete the `prettyPrint` function for it to be shaken out. Because of how this application will be used, simply deleting things from `formatters-internal` is not an option. Here's what my Webpack config looks like: 
```
module.exports = function () {
  return {
    mode: 'production',
    entry: {
      'bundle': './src/entry.js'
    },
    output: {
      filename: '[name].js',
      library: 'SomeLibrary',
      libraryTarget: 'window'
    }
  }
};

```

I'm not sure what I'm doing wrong here. Babel is not being used to convert things to CommonJS. I also made sure that my package.json (and the package.json of `pretty-format`) has `"sideEffects: false"`. I'm using v4.44.2 of Webpack.

**Comment by evilebottnawi** [comment]
Please format the issue using the issue template, I will reopen it after you fix it, respect time of other developers, thanks

**Comment by evilebottnawi** [comment]
And, we fix a lot of bugs with tree shaking in v5, please try v5

**Comment by sokra** [comment]
Yes this case only works in webpack 5
