### ISSUE TITLE
Multi Entries Format is not working

### ISSUE THREAD

**Issue by AlexandrSokolov** [webpack/webpack#11977]
# Bug report

**What is the current behavior?**
As soon as I switch the webpack configuration from single entry to multiple entries format, the project stop working.

**If the current behavior is a bug, please provide the steps to reproduce.**
I've created an issue on [stackoverflow.com](https://stackoverflow.com/questions/64786054/ejected-react-app-stuck-on-starting-the-development-server-after-changing-entr)

To reproduce it:

```
$ npx create-react-app react-hello
$ cd react-hello
$ npm run eject
```

Then add into `App.js`:

`import React from "react";`

And start application to make sure it works with default configuration:

`$ npm start`

To support multiple entries, I have to convert entry into the associative array/hash table. In the example I use `index` as a key for the default index page:

```
entry: {
  index: [
    isEnvDevelopment && require.resolve('react-dev-utils/webpackHotDevClient'),
    paths.appIndexJs
   ].filter(Boolean)
},
```

And as soon as I change the format, the `npm start` stucks and `Starting the development server...` lasts forever. I try to build it and get an error:

> $ npm run build
> 
> ...
> > node scripts/build.js
> 
> Creating an optimized production build...
> 
> Failed to compile.
> 
> Cannot read property 'filter' of undefined
> 

**What is the expected behavior?**

Application is built successfully, in the browser I can see the index page.

**Other relevant information:**
```
webpack version:  
$ npm list webpack
...
└── webpack@4.44.2
```
Node.js version: 
```
node --version
v10.15.3
```
Operating System: 
```
$ uname -a
Linux alex-latitude-5480 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linu
```
Additional tools: nothing special.

**Comment by evilebottnawi** [comment]
Please open an issue in `create-react-app` repo
