### ISSUE TITLE
Expose a function for apply all optimization-related plugin

### ISSUE THREAD

**Issue by wood1986** [webpack/webpack#11976]
## Feature request

**What is the expected behavior?**
I have a plugin which creates a child compiler. And I want to apply the same optimization plugins that https://github.com/webpack/webpack/blob/a16909c5fdb9efe9f1dd20226a1e7fc216160d1a/lib/WebpackOptionsApply.js#L293-L456 is doing into my child compiler. Otherwise, I have to duplicate the whole block and then paste it into my plugin.

**What is motivation or use case for adding/changing the behavior?**
Same as previous.

**How should this be implemented in your opinion?**
Just put the whole block in a function and then expose it.

**Are you willing to work on this yourself?**
yes

**Comment by evilebottnawi** [comment]
Sorry, it is internal plugins, but you can use it using `const SideEffectsFlagPlugin = require('webpack/lib/optimize/RemoveParentModulesPlugin');`

**Comment by wood1986** [comment]
But I am not talking about a particular internal plugin. I am talking about the all optimization plugin***s***. If it is just one, then I won't suggest. I have already highlighted a hundred line of code that need to be wrapped and then exposed as a helper function.

**Comment by evilebottnawi** [comment]
Why you need all optimization plugins? What is real use case? Looks some weird

**Comment by wood1986** [comment]
I have a plugin which uses the child compiler to output node target chunks. My use case is I want to have the same optimizations for those chunks. For example, there is no split chunk optimization for the node target chunks unless I explicitly add 'SplitChunksPlugin' to my plugin. What if I want to let the consumers do the same optimization that parent is doing such as 'LimitChunkCountPlugin' and so on? Then I have to copy and paste the whole block I mentioned above into my plugin. I want to reuse your implementation.

**Comment by wood1986** [comment]
Any updates? Is it worth to do it?

**Comment by evilebottnawi** [comment]
They already work for child compilationы

**Comment by wood1986** [comment]
I do not think it is true. As I have put a `console.log` statement inside the `apply` function for each `optimize/*Plugin.js`. If they already apply to each child compilation, I should see twice. The actual behavior output once.

**Comment by evilebottnawi** [comment]
Just apply them in child compiler, you don't provide context what you want to achieve so I cant help sorry
