### ISSUE TITLE
Incorrect paths in compilation.fileDependencies

### ISSUE THREAD

**Issue by MikeDevice** [webpack/webpack#11971]
# Bug report

**What is the current behavior?**
The `compilation.fileDependencies` (at a webpack plugin) contains incorrect paths, such as `/`, `/home`, etc. There is no such problem with `webpack@4`.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Create an empty project.
2. Install `webpack` and `webpack-cli`:

```
$ npm install --save-dev webpack webpack-cli
```

3. Create `webpack.config.js` with the follow content:

```js
class Plugin {
  apply(compiler) {
    compiler.hooks.emit.tapAsync('Plugin', (compilation, callback) => {
      console.log(Array.from(compilation.fileDependencies));
      callback();
    });
  }
}

module.exports = {
  plugins: [new Plugin()]
};
```

4. Run build:

```
$ webpack
```

5. See the console output. It will be like so:

```
[
  '<path-to-repo>/package.json',
  '<path-to-repo>/src',
  '<path-to-repo>/src/index.js',
  '<path-to-repo>',
  '/home/<username>',
  '/home',
  '/'
]
```

Here is a repo that reproduces this issue: https://github.com/MikeDevice/webpack-file-dependencies-issue.

**What is the expected behavior?**
The expected behavior is what `webpack@4` has:

```
[
  '<path-to-repo>/src/index.js'
]
```

**Other relevant information:**
webpack version:  5.4.0
Node.js version: 12.14.0
Operating System: Ubuntu 18.04.5 LTS
Additional tools: webpack-cli: 4.2.0

**Comment by sokra** [comment]
`/home/<username>` could be a symlink which would affect resolving.

**Comment by evilebottnawi** [comment]
Answer above

**Comment by MikeDevice** [comment]
I'm not sure, I understand you. Okay. Let's see another example. I created a new branch at the example repo ([link](https://github.com/MikeDevice/webpack-file-dependencies-issue/tree/babel-runtime-example)), where I added `@babel/runtime` as a dependency.

Now at the build a get follow logs:

```
[
  '<path-to-repo>/node_modules/@babel/runtime',
  '<path-to-repo>/node_modules/@babel/runtime/package.json',
  '<path-to-repo>/node_modules/@babel/runtime/helpers/decorate.js',
  '<path-to-repo>/node_modules/@babel/runtime/helpers',
  '<path-to-repo>/node_modules/@babel',
  '<path-to-repo>/node_modules',
  // ...
  // other @babel/runtime paths
  // ...
]
```

When I use `webpack@4` I don't get such paths as

```
  '<path-to-repo>/node_modules/@babel/runtime',
  '<path-to-repo>/node_modules/@babel/runtime/package.json',
  '<path-to-repo>/node_modules/@babel/runtime/helpers',
  '<path-to-repo>/node_modules/@babel',
  '<path-to-repo>/node_modules',
```

and It seems good, because these paths are not real dependencies.

**Comment by evilebottnawi** [comment]
@MikeDevice what is the problem? It is features, right now webpack can follow for symlinks

**Comment by MikeDevice** [comment]
The problem is [license-checker-webpack-plugin](https://github.com/microsoft/license-checker-webpack-plugin) doesn't work sometimes with `webpack@5` and I thought It's been caused because of webpack's "bug", but as you said it's a feature, so now I realise it's a plugin's bug, not webpack.

**Comment by evilebottnawi** [comment]
Yes, please open an issue in `license-checker-webpack-plugin`, it is feature, also it give more abilities for watching and tracking
