### ISSUE TITLE
[Webpack 5 Question] Info for upgrading Wepback Plugins

### ISSUE THREAD

**Issue by janlent1** [webpack/webpack#11973]
@evilebottnawi  what i basically want to translate into webpack5 is this coding:
```
ParserHelpers.addParsedVariableToModule(
    parser,
    'CustomPluginFor' + Name.replace(/[.]/g, '_'),
    `__webpack_require__.map.set('${Name}', require.resolve(` +
    JSON.stringify(resPath + '.specialending') +
    '))'
)
```

_Originally posted by @janlent1 in https://github.com/webpack/webpack/issues/11924#issuecomment-725431300_

**Comment by evilebottnawi** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

I don't know your context and I can't answer you
