### ISSUE TITLE
In packages we publish with conditional exports, should .mjs files still be ES5 except for import/export statements?

### ISSUE THREAD

**Issue by jedwards1211** [webpack/webpack#11975]
Since `import` and `export` statements are not ES5, it seems tempting to use other non-ES5 features in published `.mjs` files.

But all hell will break loose once Webpack is resolving `.mjs` files by default in packages with conditional exports, if packages that used to resolve to code that was compatible with legacy browsers now resolve to `.mjs` that isn't compatible with legacy browsers (aside from the `import`/`export` statements, which get converted by webpack).

Is there any official guidance for package authors?  I assume this means we should still transpile everything but `import`/`export` statements to ES5 in the `.mjs` files we publish.  Or are all Webpack users expected to add a transpiler rule for all `.mjs` files?

(For that matter if I recall correctly, packages can conditionally export `.js` files that use ES Module syntax, so a transpiler rule for `.mjs` files wouldn't even cut it)

I'm used to packages dropping support for old versions of node, but I don't think I've ever seen a package mention dropping support for old browsers (except I did this in some of mine when the `module` field was introduced, then backtracked), so it seems like the community expectations are more vague than ever and discussion is needed.

I would like to publish modern code (say, ES11) in my `.mjs` files so that I can make slimmer bundles for modern browsers, but I don't want to cause problems for everyone else using my packages.

Frankly, I wish the community had already settled on some kind of pragma comment for all files to declare what version of ES they're supposed to be, so that we could avoid transpiling code that's already compatible with our target environment.  Although it's easy to transpile all JS files of any kind to play it safe, it's really slow too (though I guess we would rarely need to transpile everything while developing).

**Comment by evilebottnawi** [comment]
Please use stackoverflow for questions, we use Node.js logic, so what is working on Node.js, will work with webpack, if you found a bug/problem, please open an issue with description and step to reproduce, sorry, unfortunately we do not have time to answer questions related to work with ES modules

**Comment by evilebottnawi** [comment]
Anyway my recommendation to use https://github.com/ai/dual-publish

**Comment by jedwards1211** [comment]
@evilebottnawi there was a similar question on StackOverflow that never got any answers, so I was discouraged from asking there...

I figured it would be worth pointing this out since the change to resolve `.mjs` files and conditional exports by default may cause a lot of surprises.

It seems to me like the only safe route these days is to transpile **everything** on a production build, whereas in the early days of Webpack I'm pretty sure everyone advised to ignore `node_modules`.  So it seems to me that we should address this in Webpack 5 documentation?

**Comment by evilebottnawi** [comment]
@jedwards1211 Yep, I agree, let's open an issue in webpack docs

**Comment by sokra** [comment]
There is no perfect answer to this.

I would say publish stage 4 javascript, user should transpile everything.

Note that you must only increase the javascript level on major version. Changing javascript level is a breaking change.

**Comment by jedwards1211** [comment]
Yes, you often see breaking changes when packages drop support for old versions of node, but I don't think anyone's doing this for code destined for the browser yet.  For example, I looked at `apollo-client`'s `"module": "bundle.esm.js"`, and it appears to be ES5 + `import` and `export` statements as far as I can tell.  So I think publishing modern JS is far from the norm right now for browser packages.

Is the ecosystem really in a position to handle a smooth transition to everyone publishing stage 4 JS yet?  It would be smoother if there's some system for packages or pragma comments to specify what version of JS they export so that bundler rules could transpile when necessary, or (when there's no rule to transpile a given package) Webpack can warn that the output isn't pure ES5.  Seems like there really needs to be more discussion of how this phase of evolution will work.  This would go for later versions of ES too, since there will come a day when everyone drops support for pure ES6 environments as well.

**Comment by evilebottnawi** [comment]
> Webpack can warn that the output isn't pure ES5.

You can do it on own side, just run `acorn` with different `ecmaVersion` values https://github.com/acornjs/acorn/tree/master/acorn#interface, so if it is failed with `5` you can output warning(s) places where it happens (same for `6`/`7`/`8`/`9`/`10`/`11`/`12`), anyway it will be implement and it is not hard, what we need:
- `acorn` should have API to get `ecmaVersion` based on parsed code, we use the `latest` value https://github.com/webpack/webpack/blob/master/lib/javascript/JavascriptParser.js#L128
- in `webpack@5` we have the `target` option

So we can compare them and if parsed code contains es6 but you have `target: ['web', 'es5']` we can log warning. 

But this does not guarantee that you will not get problems. Why? Different browsers have different support ES features, some features can work, some features cannot.

**Comment by jedwards1211** [comment]
Can `acorn` tell us if the parsed code is es5 except for `import`/`export` statements though?

> But this does not guarantee that you will not get problems.

That's true, I haven't implemented separate legacy and modern browser builds yet, and I'm not sure how most people do that, but I guess even for the modern browser build they might just specify the target browser versions and let `@babel/preset-env` decide what to transpile instead of specifying a target ES version...

We definitely need a doc issue though since the [Build Performance](https://webpack.js.org/guides/build-performance/) documentation advises applying loaders to the minimum number of modules necessary.  I'll create one

**Comment by evilebottnawi** [comment]
> The tricky thing is a lot of packages out there have ES5 + import/export statements, but you have to parse that as ES6 so it would be hard to know that the output code is going to be ES5 once Webpack has processed the import and export statements.

Yep, we need more smart tool here, ideally acorn should provide list of used ES features, so we can exclude `import`/`export` and output supported browsers/es version

**Comment by jedwards1211** [comment]
I thought about this some more...

The trickiest thing is say you're publishing ES2019 and everything works in some versions of major browsers and node.  Then suppose you make a code change that uses `Object.fromEntries` (still valid ES2019) when your code wasn't previously using it, and your code stops working in a version of Chrome that it did before, even though all of the other ES2019 features weren't working.  (Not sure if this is the case, but just an example).

So if we're going to publish code that isn't pure ES5, the only responsible thing to do is test in selected versions of all major browsers as well as node.  (Which is a biiiiiig overhead...)

So I think any official guidance on publishing >ES5 code we add to official documentation should advise picking target browser versions and testing in them if that's the case.

Also, I'm not sure if stage 4 proposals are guaranteed to be supported by current browsers?  I would say no one should publish code that doesn't work in current browsers, so that dev builds don't have to transpile everything.  Because transpiling everything any time you need to do development would really suck in large projects.  (I guess module federation makes it possible to split up large projects into pieces, but how many of us are going to reach that point any time soon?)

**Comment by jedwards1211** [comment]
I'm beginning to think it would be better for everyone if there were yet another `package.json` entrypoint key that's *opt-in* unlike `module` and `exports`, and the convention with this key is that you should expect to need to transpile the code.  Publishing ES2015+ is just not catching on [like people have hoped](https://babeljs.io/blog/2018/06/26/on-consuming-and-publishing-es2015+-packages) when it comes to packages for the browser.
