### ISSUE TITLE
DefinePlugin hard to inject class/object that includes function

### ISSUE THREAD

**Issue by thakerng** [webpack/webpack#1198]
I'm writing program that run webpack on NodeJs with their configuration (without grunt, gulp) . and there are some dynamic parameters I would like to share between bundled script and NodeJs. So the thing I have to do is injecting dynamic parameters as a global variable to bundled script.

 I've found the solution that use definePlugin

```javascript
plugins:[
    new webpack.DefinePlugin({
          "share":JSON.stringify("parameters")
   })
]
```

that works well in flat parameter but I'm facing the problem that when parameter is an object includes type of function. JSON.stringify cannot serialize a function, some libraries such as JSONfn , serialize a function type to be a string webpack did not eval that. 

the way I purpose to be is 

```javascript

var shareParam = {foo:function(){ return true; },bar:"Hello World"};
webpack({
   plugins:[
        new webpack.DefinePlugin({
           "share":serialize(shareParam)
       })
   ]
})
```  

```javascript

console.log(window.share.foo())
```

Is there any solution to do easier?  I think that practical using of definePlugin is hard. Why does not allow injecting parameter directly without stringify

**Comment by IngwiePhoenix** [comment]
Use the output of this[1] module’s function. Its literal javascript, so it should work just fine.

[1]: https://www.npmjs.com/package/serialize-javascript

**Comment by sokra** [comment]
> Is there any solution to do easier? I think that practical using of definePlugin is hard. Why does not allow injecting parameter directly without stringify

Because you may want to inject code: 

``` js
new DefinePlugin({
  TWO: "(1 + 1)"
});
```
