### ISSUE TITLE
[Webpack 5.4] ontput.library unable to work properly

### ISSUE THREAD

**Issue by EickeOe** [webpack/webpack#11986]
# Bug report

**What is the current behavior?**

Unable to export normally

**If the current behavior is a bug, please provide the steps to reproduce.**
```javascript
// webpack.config

entry:{
        mian:'/src/index.ts'
    },
    output: {
        path: path.join(__dirname, '../dist'),
        publicPath: './',
        filename: isDevServer
            ? '[name].[fullhash].js'
            : '[name].[contenthash].js',
        library: 'test',
        libraryTarget: 'umd',
        jsonpFunction: `webpackJsonp_test`,
    }
```

```javascript
// index.ts

export function mount() {}
export function bootstrap() {}
export function unmount() {}

```

```javascript
// in Browser
console.log(window.test)
// {}
```

**What is the expected behavior?**

```javascript
// in Browser
console.log(window.test)
// {mount(){},bootstrap(){},unmount(){}}
```

**Other relevant information:**
webpack version:  5.4.0

**Comment by code1x1** [comment]
here is a working example
https://github.com/code1x1/webpack-library-example-11986

the test property definitely exists

**Comment by evilebottnawi** [comment]
Works fine, I think you use webpack-dev-server, webpack-dev-server doesn't support libraries :disappointed: , we have the issue about this, hope we will fix it in near future

**Comment by EickeOe** [comment]
> Works fine, I think you use webpack-dev-server, webpack-dev-server doesn't support libraries 😞 , we have the issue about this, hope we will fix it in near future

Yeah, I use webpack-dev-server 
thank you
