### ISSUE TITLE
Cannot find the hash of the main bundle from runtime

### ISSUE THREAD

**Issue by zendra1994** [webpack/webpack#11988]
# Bug report

**What is the current behavior?**
Deploying to production breaks the script as the runtime cannot find the chunk tagged by the particular hash.

**If the current behavior is a bug, please provide the steps to reproduce.**
![image](https://user-images.githubusercontent.com/18490172/99088101-dd84f880-25cb-11eb-9cd8-f122cff5ec08.png)

<img width="629" alt="Pasted Graphic 1 copy" src="https://user-images.githubusercontent.com/18490172/99088733-b4189c80-25cc-11eb-9271-ecd28d49252f.png">

**What is the expected behavior?**

Building this application locally works as expected, all chunks are resolved properly and the script starts the app.
It is difficult to reproduce as it is happening only on the production environment, and there are no specific environment details which change how the build runs and how it loads in the scripts.

The output files are hashed using `contenthash`.

```
    filename: 'js/[name].[contenthash:4].js',
    chunkFilename: 'js/[name].[contenthash:4].chunk.js',
```

**Other relevant information:**
webpack version:  5.2.0
Node.js version: 12.19.0
Operating System: 
Additional tools:

**Comment by evilebottnawi** [comment]
Update webpack to `5.4.0`

**Comment by evilebottnawi** [comment]
Sorry without reproducible example or more information about environments where it happens we can't help

**Comment by zendra1994** [comment]
I'll try updating. Didn't see there's a new release that happened lately. Thanks.

**Comment by evilebottnawi** [comment]
@zendra1994 Feel free to feedback, if you faced with this issue, we will continue investigate it

**Comment by zendra1994** [comment]
Updating to the newest version at the time `5.4.0` fixes the issue!

**Comment by zendra1994** [comment]
Update:

![image](https://user-images.githubusercontent.com/18490172/101367330-519e7d80-38a6-11eb-8816-328dfbe3faf0.png)

I found where the issue is, it is a dev mistake, the vendor url contains the ./ (`static/./js/vendor.a274.js`), which is a misconfiguration from `splitChunks.cacheGroups.common.filename`. Although the browser correctly downloads the asset, the path is resolved correctly, an error is thrown from webpack's runtime bundle.

![image](https://user-images.githubusercontent.com/18490172/101368033-f456fc00-38a6-11eb-9b68-1b898458d670.png)
