### ISSUE TITLE
Webpack 5 incorrectly marking a reexport as unused

### ISSUE THREAD

**Issue by christiango** [webpack/webpack#11990]
# Bug report

**What is the current behavior?**
When upgrading our app (a large Microsoft Office web application) from webpack 4 to webpack 5 we are getting an error like this:

boot.js:3914 Uncaught TypeError: (0 , lib.createTheme) is not a function
    at Object.844 (boot.js:3914)
    at __webpack_require__ (boot.js:3966)
    at boot.js:4207
    at boot.js:4208 

This issue only happens in production mode. More specifically, it happens when concatenateModules and unusedExports are set to true. 

To debug, I turned off minification and export mangling (the issue still repros) and I found that the 'createTheme' module is incorrectly being marked as 'unused'. One interesting thing to note about createTheme is that it is being imported from the `office-ui-fabric-react` npm package, which internally reexports that module from the `@uifabric/

Here is the chain of the re-exports from office-ui-fabric-react (which is in the middle of a rename to fluent-ui)
https://github.com/microsoft/fluentui/blob/master/packages/react/src/Theme.ts
https://github.com/microsoft/fluentui/blob/master/packages/react-internal/src/Theme.ts
https://github.com/microsoft/fluentui/blob/master/packages/theme/src/index.ts#L8

Here is the interesting code from the bundle, with comments saying it is an unused re-export
```javascript
  "createTheme": () => /* reexport */ /* unused export */ undefined,
```

**If the current behavior is a bug, please provide the steps to reproduce.**
I was able to strip down our app into a minimal repro of the issue, it is in this github repo: https://github.com/christiango/webpack5-unused-export-bug

The readme there contains some notes from the investigation. One of the most interesting bits is that if we change any of these things, the issue no longer reproduces:

1. Making it only a single entry point (remove the logout entrypoint)
2. Switch the webpack mode to development
3. Set optimization.concatenateModules to false in the webpack config
4. Set optimization.usedExports to false in the webpack config
5. Switch the dynamic import in ErrorDialog.js to a static import

**What is the expected behavior?**
The "createTheme" function in the repro should not crash

**Other relevant information:**
webpack version:  5.4.0
Node.js version:  12.14.0
Operating System: Windows 10
Additional tools:

**Comment by christiango** [comment]
Another interesting tidbit: The issue repros in webpack: 5.0.0-beta.31 and after, but not 5.0.0-beta.30 and before.

**Comment by christiango** [comment]
Doing npm installs of the commits that were new to beta.31, will report back soon with the commit that breaks this scenario

**Comment by christiango** [comment]
Does not repro with commit 23e91dbbac9d8fc98b9a87e8822b711be5634fc6
Does repro with commit 9af1d7526b180cab69ea175175eb56a2cde9df75

Looks like it was introduced in this commit: https://github.com/webpack/webpack/commit/9af1d7526b180cab69ea175175eb56a2cde9df75

**Comment by sokra** [comment]
On it...

**Comment by sokra** [comment]
Ok, I found the problem and have a bugfix. Still need to construct a smaller test case to add it to our test suite...

**Comment by christiango** [comment]
Thank you for taking the time to fix this so quickly. I've made a donation to webpack as a small thank you for the bug fix and all the other awesome work the team has done on the project.

**Comment by dzearing** [comment]
I am seeing something very similar. We have a library `keyboard-key`, which exports a constant like so:

```ts
export const GraveAccentKey = keyboardKey['`'];
```

We have a test-bundle package which tries to bundle (production build) keyboard-key starting at the index.

In webpack 4, I see output like this in the minified bundle:


```js
  function (n, e, r) {
    "use strict";
    r.r(e),
      r.d(e, "getCode", function () {
        return o;
      }),
      r.d(e, "GraveAccentKey", function () {
        return m;
      }),
      r.d(e, "ExclamationPointKey", function () {
        return h;
      }),
```
In webpack 5, I see no mention of `GraveAccentKey` anywhere. It was stripped.

The unminified bundle shows this:

```js
var GraveAccentKey = keyboardKey['`'];

/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "getCode": () => /* binding */ getCode,
/* harmony export */   "GraveAccentKey": () => /* binding */ GraveAccentKey,
/* harmony export */   "ExclamationPointKey": () => /* binding */ ExclamationPointKey,
...
};
```

And in the minified build, this whole block is nuked. Did not expect top level exports in a bundle to be removed.

**Comment by dzearing** [comment]
@sokra or @TheLarkInn Should I open a separate issue for this? If you want me to isolate a repro I can; or if there's a newer build with this addressed I can try it out.

**Comment by dzearing** [comment]
(note: deleted my comments, I think perhaps output.libraryTarget default might have changed, but explicitly setting to UMD preserved the exports.)
