### ISSUE TITLE
Ability to catch ChunkLoadError in a project level

### ISSUE THREAD

**Issue by MatanYadaev** [webpack/webpack#11998]
I would like to catch the whole `ChunkLoadError` errors in my project in order to tell the browser to refresh the page when that happens.
This should fix some cache invalidation issues in my project.

Is that a functionality that exists in Webpack? Is that an option to catch the whole `ChunkLoadError` in the project?

Thanks.

**Comment by sokra** [comment]
``` js
const old = __webpack_chunk_load__;
__webpack_chunk_load__ = (id) => {
  return old(id).catch(err => { ... });
}
