### ISSUE TITLE
DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.

### ISSUE THREAD

**Issue by livelyPeng** [webpack/webpack#11993]
webpack5.0 

[DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
	Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
	Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
(Use `node --trace-deprecation ...` to show where the warning was created)

**Comment by livelyPeng** [comment]
webpack-5

**Comment by trev-dev** [comment]
What if your plugin is adding a comment to the top of a production bundle? I've played with all of the stages of the processAssets stage, my comment gets wiped out.
