### ISSUE TITLE
util doesn't work in IE8 and lower

### ISSUE THREAD

**Issue by jhnns** [webpack/webpack#12]
The node module `util` uses `Object.create` in the `inherit`-function. But in IE8 and lower `Object.create` is not defined. Thus `util` requires a shim to work properly in these browsers.

Not all JavaScript 1.8.5 features available in `Object.create` can be emulated but for the purpose of `inherit` I think [this one provided by the MDN](https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects/Object/create#Cross-browser_compatibility) will do it.

**Comment by KidkArolis** [comment]
Whats your recommendation for running webpacked scripts on third party sites where we cant execute any polyfils.
