### ISSUE TITLE
optimization.splitChunks.chunks = initial will catch error but not throw an Error out !

### ISSUE THREAD

**Issue by yinsang** [webpack/webpack#12000]
# Bug report

**What is the current behavior?**
Both webpack4 and webpack 5 had this issue.
While my program has an error ,this config will make javascript runtime block ,but none of Error had thrown.
// src/index.js
```
const a = c;
```
// html
```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <script src="./main.js"></script>
</body>
</html>
```
// webpack.config.js
```
const path = require('path')
const devConfig = {
  output: {
    // 用于build后输入的文件夹
    path: path.resolve(__dirname, 'dist'),
    publicPath: '',
    filename: "[name].js",
  },
  optimization: {
    splitChunks: {
        chunks: 'initial'
    }
  },
  mode: 'development',
  devtool: 'inline-source-map',
  devServer: {
    index: 'index.html',
    publicPath: '',
    contentBase: path.resolve(__dirname),
    compress: true,
    port: 8080
  }
}
module.exports = devConfig
```
// package.json
```
{
  "name": "webpack-bug",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "dev": "webpack serve"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "webpack": "^5.4.0",
    "webpack-cli": "^4.2.0",
    "webpack-dev-server": "^3.11.0"
  }
}

```
console: without  error
![image](https://user-images.githubusercontent.com/12373328/99248531-930db100-2843-11eb-88db-a0d7d4a057f0.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

expect throw an error like:
```
chunks: 'all'
```
![image](https://user-images.githubusercontent.com/12373328/99248257-20043a80-2843-11eb-8812-50eedb190c98.png)

**Other relevant information:**
webpack version:  5.4.0
Node.js version: v14.13.1
Operating System:  macOS
Additional tools: vscode

**Comment by evilebottnawi** [comment]
Please full out all fields in the issue template, I think you forget to add chunks in your html

**Comment by yinsang** [comment]
[webpack-bug.zip](https://github.com/webpack/webpack/files/5545984/webpack-bug.zip)

**Comment by yinsang** [comment]
> Please full out all fields in the issue template, I think you forget to add chunks in your html

I had put ./main.js to index.html.
You didn't read my question seriously.
I put zip just now ,please check again.

**Comment by evilebottnawi** [comment]
All works fine, I don't understand you problem, please provide steps to reproduce

**Comment by yinsang** [comment]
> All works fine, I don't understand you problem, please provide steps to reproduce

download webpack-bug.zip , 
```
npm i 
```
```
npm run dev
```
can't see any error in console.log,
expect throw an error in javascript runtime.

**Comment by evilebottnawi** [comment]
@yinsang Because you code is not executed, you forget to include `vendors-node_modules_webpack-dev-server_client_index_js_http_localhost_8080-node_modules_webp-ef8580`

**Comment by evilebottnawi** [comment]
For debug you can use:
```
devServer: {
    index: 'index.html',
    publicPath: '',
    contentBase: path.resolve(__dirname),
    compress: true,
    port: 8080,
    // Look here
    writeToDisk: true,
  }
```

And look in the `dist` directory

**Comment by yinsang** [comment]
Thanks so much.
 I forget to import all chunks, but import some of them. 
It's wrong on my HtmlWebpackPlugin 's options.

```
return new HtmlWebpackPlugin({
    filename: `${name}.html`,
    template: './src/layouts/index.html'
     //  wrong before, need delete underline
    // chunks: ['common', name]
  });
```
Acturally ,  **vendors\~common\~detail.8fe56.js**  is forgot.
