### ISSUE TITLE
imported functions don't work on a single line if statement in development mode

### ISSUE THREAD

**Issue by sebovzeoueb** [webpack/webpack#12006]
# Bug report

**What is the current behavior?**

If a function is imported using an import statement and called on a single line if statement the function gets called even though the statement evaluates to false. This only occurs in development mode. A semicolon is being inserted before the imported function where it shouldn't:

```
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var _importedFunction__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./importedFunction */ "./src/importedFunction.js");
;

const testValue = 'whatup'
if (testValue != 'whatup') ;(0,_importedFunction__WEBPACK_IMPORTED_MODULE_0__.default)()
console.log('Test Ended')
```

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/sebovzeoueb/webpack-5-import-bug
- clone this repository and run `npx webpack`
- open up `dist/index.html` and notice that the console logs "Imported Function" even though the if statement on line 4 of `src/index.js` should prevent that.

**What is the expected behavior?**

A semicolon is not inserted before the imported function in development mode. This used to be the case in previous versions of webpack.

**Other relevant information:**
webpack version:  5.4.0
Node.js version: 12.18.3
Operating System: Windows 10 Professional

**Comment by sokra** [comment]
fixed in #12007
