### ISSUE TITLE
ionic pwa angular gulp babel

### ISSUE THREAD

**Issue by luismendes070** [webpack/webpack#12009]
## Feature request

**What is the expected behavior?**

**What is motivation or use case for adding/changing the behavior?**

**How should this be implemented in your opinion?**

**Are you willing to work on this yourself?**
yes

**Comment by luismendes070** [comment]
webpack-4
documentation
performance

**Comment by evilebottnawi** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
