### ISSUE TITLE
Chunk outputting with incorrect file name

### ISSUE THREAD

**Issue by jcreamer898** [webpack/webpack#1200]
I'm seeing an odd issue and it's happening randomly where WebPack is generating a chunk file with a different name than it's reference in the `common.js` output where I'm using the `CommonsChunk`.

Here's the name of the chunk it's generating...

![](http://d.pr/i/1cCpL+)

And here's what `common.js` is referencing...

![](http://d.pr/i/1dB0H+)

Here's my [webpack.config.js](https://gist.github.com/jcreamer898/c6992fd12f5a7de76a02) file too. 

Thanks!

**Comment by Antariano** [comment]
same here

**Comment by jcreamer898** [comment]
I did figure out that you can do this in your chunk filename template...

```js
chunkFilename: "[name]_[chunkhash:20].js",
```

So, that helps, but seems like more of a bandaid?

Also, docs need to be updated to even show that open is available. :)

**Comment by sokra** [comment]
fixed

**Comment by jcreamer898** [comment]
Where did it get fixed? My second response was just a temporary solution I think.

**Comment by sokra** [comment]
https://github.com/webpack/webpack/commit/02522f11c3a5883bf55f27a412727b98404720c9

**Comment by jcreamer898** [comment]
Awesome. 





On Sat, Jun 27, 2015 at 5:59 AM -0700, "Tobias Koppers" <notifications@github.com> wrote:












02522f1
