### ISSUE TITLE
MinChunkSizePlugin breaks federated modules loading

### ISSUE THREAD

**Issue by gautierrollin** [webpack/webpack#12003]
# Bug report

**What is the current behavior?**

When an application tries to load a remote module with a minimal chunk size defined via the Webpack `MinChunkSizePlugin`, I get this error:

```
Uncaught TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (bootstrap:18)
    at Function.__webpack_require__.t (create fake namespace object:7)
__webpack_require__ @ bootstrap:18
__webpack_require__.t @ create fake namespace object:7

```

**If the current behavior is a bug, please provide the steps to reproduce.**

Just add this to a Webpack config that uses remote modules via `ModuleFederationPlugin`:

```js
new MinChunkSizePlugin({
  minChunkSize : 10000
})
```

It seems that code who is in charge of loading the remote modules is missing in the bundle that uses `MinChunkSizePlugin`.
To see the difference, you can just compare the two following files:
- [main-ok.js](https://github.com/gautierrollin/mf-min-chunk-size-plugin/blob/master/diff/main-ok.js) (without `MinChunkSizePlugin`)
- [main-not-ok.js](https://github.com/gautierrollin/mf-min-chunk-size-plugin/blob/master/diff/main-not-ok.js) (with `MinChunkSizePlugin`)

Reproducible repos: 
- Root application: https://github.com/gautierrollin/mf-min-chunk-size-plugin
- Remote application: https://github.com/gautierrollin/mf-remote-application

**What is the expected behavior?**

`MinChunkSizePlugin` should just impact the chunk size of internal application chunk and the way of loading remotes modules should not be removed from the bundle.

**Other relevant information:**
webpack version:  5.4.0
Node.js version: 12.18.3
Operating System: Mac OS v10.15.6

---

**PS**: I've already encountered issues with the `MinChunkSizePlugin` and the first version of [module federation plugin](https://github.com/ScriptedAlchemy/webpack-external-import).
Well, that's an old issue but it could be related: https://github.com/ScriptedAlchemy/webpack-external-import/issues/128 CC @ScriptedAlchemy 😄

**Comment by Gautierrr** [comment]
Like in my old issue, this bug appears if Webpack doesn't have to create several chunks (because of a large `minChunkSize` value relative to the project).

**Comment by evilebottnawi** [comment]
> Uncaught TypeError: Cannot read property 'call' of undefined
>    at __webpack_require__ (bootstrap:18)
>    at Function.__webpack_require__.t (create fake namespace object:7)
> __webpack_require__ @ bootstrap:18
> __webpack_require__.t @ create fake namespace object:7

can't reproducible (with and without plugin), can your improve reproducible test repo

**Comment by Gautierrr** [comment]
I don't think you have the same error with and without `MinChunkSizePlugin`.

Without the plugin, you get an error because the remote application does not exist:

```
Uncaught ReferenceError: app2 is not defined
```

I've been lazy but you can now clone [this repo](https://github.com/Gautierrr/mf-remote-application), start the remote application (in addition to the root application) and it'll be fixed 😉

**Comment by evilebottnawi** [comment]
> I've been lazy but you can now clone this repo, start the remote application (in addition to the root application) and it'll be fixed wink

Please avoid this, the time it took was worth unanswered problem(s) to somebody

@sokra Limitation?

**Comment by alexander-akait** [comment]
bump

**Comment by csvan** [comment]
@gautierrollin is this still an issue for you?

**Comment by gautierrollin** [comment]
No because I don't use `MinChunkSizePlugin` anymore in my project. But I think the problem still exists.

**Comment by ScriptedAlchemy** [comment]
Messing around with chunking is problematic. If you want to force federated modules into fewer chunks then do it through splitChunks cache groups and a regex

**Comment by juanger** [comment]
I got this problem when using `{splitChunks : {maxSize: 300000} }`. I'll give the `cacheGroups` a try. My UI loads several federated modules and keeping the remote entries small is very important.
