### ISSUE TITLE
HMR doesn't work if 'target' property has any value

### ISSUE THREAD

**Issue by mazurevich** [webpack/webpack#12001]
# Bug report

**What is the current behavior?**
HRM doesn't work neither using webpack-dev-server CLI either node app. 

**If the current behavior is a bug, please provide the steps to reproduce.**
1) Create simple webpack config with hot: true and webpack.HotModuleReplacementPlugin or just clone this repo https://github.com/mazurevich/webpack-hmr-issue
2) run 'npm start' or 'npm run dev' 
3) HMR doesn't work
4) comment target property in webpack.config.js
5) HMR works fine in any mode

**What is the expected behavior?**
HRM should work regardless target property. Probably the issue in tree-shaking because I don't see the ./node_modules/webpack-dev-server/client/index.js code in bundle.

**Other relevant information:**
webpack version:  5.4.0
Node.js version: latest
Operating System: Windows/MacOS
Additional tools:

**Comment by evilebottnawi** [comment]
Please use search before posting the issue, it was reported in webpack-dev-server and we are working on it
