### ISSUE TITLE
Problem with clean-webpack-plugin

### ISSUE THREAD

**Issue by matthias1999** [webpack/webpack#12013]
# Bug report

**What is the current behavior?**
Some thing strange is happening :) . when I installed clean webpack plugin i get an strange error 90 times :-1: 
[error-log.txt](https://github.com/webpack/webpack/files/5555019/error-log.txt)

`ERROR in [at-loader] ./node_modules/@types/webpack/index.d.ts:1375:26 
    TS2707: Generic type 'SyncHook<T, R, AdditionalOptions>' requires between 1 and 3 type arguments.` 

**If the current behavior is a bug, please provide the steps to reproduce.**
Just install the clean webpack plugin !

**What is the expected behavior?**
Its simple . run with out error and you know what is the plugins work.

**Other relevant information:**
webpack version:  5.4.0
Node.js version: 12.18.3
Operating System: debian 9 
Additional tools: Typescript

**Comment by evilebottnawi** [comment]
Problem in `at-loader`, 

> If the current behavior is a bug, please provide the steps to reproduce.
Just install the clean webpack plugin !

No

**Comment by matthias1999** [comment]
> Problem in `at-loader`,
> 
> > If the current behavior is a bug, please provide the steps to reproduce.
> > Just install the clean webpack plugin !
> 
> No, no problems with installation
Yeah sorry there was conflict with my ts loader and this plugin
tnq

**Comment by matthias1999** [comment]
@evilebottnawi Yeah sorry there was conflict with my ts loader and this plugin.
awesome-typescript-plugin
