### ISSUE TITLE
"Modules" reserved keyword in cacheGroup test option

### ISSUE THREAD

**Issue by BregtDeLange** [webpack/webpack#12012]
# Bug report

**What is the current behavior?**
I work on an existing project with a long history. I have multiple entries and want to extract common and vendor modules in two separate bundles. I'm using two cachegroups, one for both. Modules that I want to extract to common bundle, are located in the folder `Modules/Projects/_Shared` and its subfolders (I cannot change this).

```
optimization: {
        splitChunks: {
            cacheGroups: {
                commons: {
                    test: /[\\/]Modules[\\/]Projects[\\/]_Shared[\\/]/,
                    chunks: 'initial',
                    name: 'common',
                    enforce: true
                },
                vendor: {
                    test: /[\\/]node_modules[\\/]/,
                    chunks: "initial",
                    name: "vendor",
                    priority: 10,
                    enforce: true
                }
            }
        }
    }
```

**If the current behavior is a bug, please provide the steps to reproduce.**
The output doesn't generate a common.js bundle. I tried removing `_Shared` from the path, and all sorts of combinations. 

However, when I move the modules outside `Modules` in a new folder `Test` in the root, it works fine and a correct common.js bundle is created.

Is 'Modules' a reserved keyword?

**What is the expected behavior?**
Have a common.js file that groups all modules located in `Modules/Projects/_Shared`.

**Other relevant information:**
webpack version:  5.4
Node.js version:  10+
Operating System: Windows
Additional tools: /

Related, with CommonChunksplugin it was easier to create a common.js bundle from all entrypoints you passed. This doesn't seem possible anymore, and makes this complexer.

**Comment by evilebottnawi** [comment]
> Is 'Modules' a reserved keyword?

No

You should avoid using `Modules`, please use `modules`, some file systems are case insensitivity 

> (I cannot change this).

You need to open an issue in project(s) where used `Modules`

> If the current behavior is a bug, please provide the steps to reproduce.

Sorry I can't reproduce it, please provide reproducible test repo and I will reopen the issue

**Comment by BregtDeLange** [comment]
I'm working in an large MVC application. `Modules `in this case is a set of projects and their components. Scripts are located next to their Models. I'm not follwoing why I should create an issue in the project where used in `Modules`?


Folder structure
`
- node_modules
- Modules
-- Projects
--- ProjectOne
--- ProjectTwo
--- _Shared
---- Library (folder containing modules that are used by several other modules in each project)
`

This does not work
```
optimization: {
        splitChunks: {
            cacheGroups: {
                commons: {
                    test: **/[\\/]Modules[\\/]Projects[\\/]_Shared[\\/]/,**
                    chunks: 'initial',
                    name: 'common',
                    enforce: true
                },
                vendor: {
                    test: /[\\/]node_modules[\\/]/,
                    chunks: "initial",
                    name: "vendor",
                    priority: 10,
                    enforce: true
                }
            }
        }
    }
```

This does not create a common.js file
```
optimization: {
        splitChunks: {
            cacheGroups: {
                commons: {
                    test: **/[\\/]modules[\\/]projects[\\/]_shared[\\/]/,**
                    chunks: 'initial',
                    name: 'common',
                    enforce: true
                },
                vendor: {
                    test: /[\\/]node_modules[\\/]/,
                    chunks: "initial",
                    name: "vendor",
                    priority: 10,
                    enforce: true
                }
            }
        }
    }
```

This **does** create a common.js file
```
optimization: {
        splitChunks: {
            cacheGroups: {
                commons: {
                    test: **/[\\/]test[\\/]/,**
                    chunks: 'initial',
                    name: 'common',
                    enforce: true
                },
                vendor: {
                    test: /[\\/]node_modules[\\/]/,
                    chunks: "initial",
                    name: "vendor",
                    priority: 10,
                    enforce: true
                }
            }
        }
    }
```

**Comment by evilebottnawi** [comment]
> Sorry I can't reproduce it, please provide reproducible test repo and I will reopen the issue

@BregtDeLange Please create reproducible test repo

**Comment by evilebottnawi** [comment]
we ask this not because we are so demanding, because it helps to reduce the time for help or finding a problem

**Comment by BregtDeLange** [comment]
I will try later, for now I just included the common modules in a folder different from Modules.

**Comment by evilebottnawi** [comment]
@BregtDeLange Feel free to ping me
