### ISSUE TITLE
Removed Polyfills handling

### ISSUE THREAD

**Issue by JhonnyJason** [webpack/webpack#12011]
Hallo Webpack Team!

## Emo Stuff
First  - your are super awesome - thank you for all your work on Webpack!

Secondly - I think the decision to remove the polyfills is a very good idea. Though we have a lot of problems now xD
The real issue is due to the diversity how people build/use their packages and packaging system.

And yes, we want to have small bundles - so unncessesary polyfills - be gone!

## The Problem
But now how to handle the bundling issues?
```coffeescript
if typeof window == "object" then specificCode = require("./specificBrowserOptimizedCode")
else specificCode = require("./specificNodeOptimizedCode")
```

- So of course the `specificNodeOptimizedCode` will have many requires of node modules.
- Now it would not bundle because of errors like `Module not found: Error: Can't resolve 'url' in ...`

It seems - to make the bundle work I have to do this: `resolve.fallback.url = false`
I would have to do this for every module for every project where I upgrade webpack :sweat_smile: 

- I want to use the most modern version of webpack
- I want it to just bundle it without manual adjusting every `webpack.config.js` after I did the package upgrade
- I agree I donot need the polyfills xD

## Idea
By default have `resolve.fallback.moduleX = false` for every module.

And/or have something like this:
```json
 {
    "resolve": {
        "fallback": {
            "*": false
        }
    }
}
```

**Comment by JhonnyJason** [comment]
Btw. bleeding edge FTW :sunglasses:

**Comment by evilebottnawi** [comment]
In theory it is possible, but I think tracking each module in the configuration is better, fallback can be used not only for node.js modules

**Comment by JhonnyJason** [comment]
@evilebottnawi 
I'm not sure what you mean - I can see that it makes sense to consider and track modules I need. 
But it's quite a hassle to consider and track every module I don't need but still occurs in the code.

I somehow don't see a situation where I would want to have implicitly available fallbacks - such that it makes sense it would error out on me when they are not available. 
In face of a situation like this, when the value of variables determine if  a module is needed or not,  a warning that a module was not found is better IMO.

**Comment by sokra** [comment]
I recommend that packages use the `browser` package.json field to implemented switches between browser and node.js code:

e. g.

``` js
const specificCode = require("./specificNodeOptimizedCode");
```

```
// package.json
"browser": {
  "./specificNodeOptimizedCode": "./specificBrowserOptimizedCode"
}
```

---

> I would have to do this for every module for every project where I upgrade webpack 😅

`require("module").builtinModules` gives you a list of all node.js builtin modules...

**Comment by evilebottnawi** [comment]
Answer above, feel free to feedback

**Comment by JhonnyJason** [comment]
@sokra Yhea this is a good idea. Did not know about such an option and what it would do - will look into it. :sunglasses: 
I could see that from webpack perspective this could be a solution.

@sokra Also good to know about the .buildinModules - thank you! I assume this hints towards automatizing the process of adjusting all configs there.

Still would strongly favour any solution which does not involve changing neither the configs nor the package.json of those relevant packages^^... Cheers!

**Comment by JhonnyJason** [comment]
Hello - back on the same track... Keeping my off my critical development path^^

So small bump again.

What is the solution now?
For the immediate case I could again change the package.json of the package or the config. Still there will be a next one. And a next one and so on... If I automate the process then, it helps yhea. Still does require at least one session of reasearch for everyone else to also find that solution.
Probably I answered in a too agreeable manner I guess. 

- What is the reason why it is not the solution to simply have the fallback option to be `false` by default?
- What is the reason why the error could not be turned into a warning - that the bundling would still just succeed?

I hope it is understood that the reason why this is an issue here is because the expectation is that this problem is resolved by Webpack.
It is not optimal to demand every user and package maintainers to adjust their configs and package.json 
The only real solution is graceful default behaviour.

If you solve it that way - it is solved for everyone.

**Comment by alexander-akait** [comment]
> What is the reason why it is not the solution to simply have the fallback option to be false by default?
> What is the reason why the error could not be turned into a warning - that the bundling would still just succeed?

Because it is unsafe

**Comment by JhonnyJason** [comment]
@alexander-akait Can you elaborate?
How could this make anything unsafe?

**Comment by alexander-akait** [comment]
Because some packages require Node.js packages and package can be broken

**Comment by JhonnyJason** [comment]
> Because some packages require Node.js packages and package can be broken with Node.js modules

I'm sorry, I think I don't get the idea there

Some packages require nodejs packages - yhea
A package can be broken with nodejs modules - ? hmm 

Now the bundling process is broken exactly because of that error - I could not see how to avoid this error in this case would break something else

You mean like, when a packages requires the nodejs polyfill actually? 
Then it is broken either way because now xD
In the case where the polyfill is not required it would not be broken at all just the error breaks the bundling process.

Probably you meant something different I did not get I suppose
