### ISSUE TITLE
Watch mode not always emmitting files in v5

### ISSUE THREAD

**Issue by GeoMarkou** [webpack/webpack#12010]
# Bug report

**What is the current behavior?**
Using --watch mode in Webpack doesn't emit files that have changed after the 2nd time you change them. This has only been an issue after upgrading to Webpack 5. I was able to get this to work temporarily by specifying `cache: false` in my webpack.config.js but this causes the build times to increase significantly.

**If the current behavior is a bug, please provide the steps to reproduce.**
I ran `webpack --progress --env development --watch` as per normal but was very confused when my changes stopped appearing in my browser after hitting refresh. I've included my webpack.config.js below.

```
const path = require('path');
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;
const CleanWebpackPlugin = require('clean-webpack-plugin').CleanWebpackPlugin;

module.exports = (env) => {
    var mode = 'development';
    var devtool = 'inline-source-map';
    if (env.production) {
        mode = 'production';
        devtool = false;
    }
    
    return {
        plugins: [
            new CleanWebpackPlugin({
                // needed because index.html is 1 level above the project folder
                dangerouslyAllowCleanPatternsOutsideProject: true,
                dry: false
            }),

            new webpack.DefinePlugin ({
                'process.browser': 'true'
            }),
            
            new HtmlWebpackPlugin({
                template: 'JavaScript/index.html',
                scriptLoading: 'defer',
                cache: false,
                hash: true,
                filename: path.resolve(__dirname, 'wwwroot/index.html')
            }),

            new BundleAnalyzerPlugin({
                analyzerMode: env.analyzebundle ? 'server' : 'disabled'
            })
        ],

        resolve: {
            extensions: ['.tsx', '.ts', '.jsx', '.js'],
            alias: {
              '@APPLICATION1': path.resolve(__dirname, 'JavaScript/'),
              '@APPLICATION2': path.resolve(__dirname, '../APPLICATION2/JavaScript/')
            }
        },

        entry: {
            'site': path.join(__dirname, 'JavaScript/Site.tsx')
        },

        output: {
            filename: '[name].[contenthash].bundle.js',
            path: path.join(__dirname, 'wwwroot/js/'),
            publicPath: '/js/'
        },

        optimization: {
            moduleIds: 'deterministic',
            runtimeChunk: 'single',
            splitChunks: {
                cacheGroups: {
                    vendor: {
                        test: /[\\/]node_modules[\\/]/,
                        name: 'vendors',
                        chunks: 'all'
                    }
                }
            }
        },

        module: {
            rules: [
                {
                    // TODO remove this case once more dependancies upgrade to babel 7.12.0
                    test: /\.m?js$/,
                    resolve: {
                        fullySpecified: false
                    }
                },
                {
                    test: /\.jsx$|\.tsx$|\.js$|\.ts$/,
                    use: [{
                        loader: 'babel-loader',
                        options: {
                            envName: mode
                        }
                    }]
                },
                {
                    test: /\.jpe?g$|\.gif$|\.png$|\.svg$|\.woff$|\.woff2$|\.ttf$|\.eot$|\.mp3$|\.ogg$/,
                    use: [{
                        loader: 'file-loader'
                    }]
                }
            ]
        },

        target: 'web',
        devtool: devtool,
        mode: mode,
        // disabled because it currently has a bug in --watch mode where files are not emmitted even when changed
        cache: false
    };
};
```

**What is the expected behavior?**
Files which are changed are always emitted.

**Other relevant information:**
webpack version:  5.4.0
Node.js version: v10.16.3
Operating System: Windows 10
Additional tools: Visual Studio Code terminal

**Comment by evilebottnawi** [comment]
`target: 'web'`, it is bug on `webpack-dev-server` and we are working on it

**Comment by GeoMarkou** [comment]
I'm not using `webpack-dev-server` though - unless it is being used internally when I pass the `--watch` parameter?

**Comment by evilebottnawi** [comment]
webpack@5 do not write assets if they not changed, expected behavior, you should not touch `dist` directory (write there)

**Comment by GeoMarkou** [comment]
Ok sure. If they haven't changed, it makes sense to not emit them. However my bug report is:

> Using --watch mode in Webpack doesn't emit files that have changed after the 2nd time you change them.

Meaning that I make multiple changes to the same file, but after a few times, it stops working. In my case this lead to a wasted 2 hours while I tried to figure out why my code changes wasn't being reflected in the browser.

I feel like this is worth fixing. Disabling cache entirely results in 40 second build times every time I hit ctrl+s. And I refuse to believe that watch mode only working twice per file is intended.

**Comment by evilebottnawi** [comment]
Please create reproducible test repo, I think something wrong with your env, we have very many tests on this

**Comment by GeoMarkou** [comment]
I noticed there was an update (5.4.0 => 5.6.0) and I'm not able to reproduce this in the latest version, so I'm guessing this was a temporary bug with that specific version.

**Comment by evilebottnawi** [comment]
@GeoMarkou Great, anyway feel free to open an issue if you faced with bug again
