### ISSUE TITLE
[BUG] Webpack 5 Broken Bundle

### ISSUE THREAD

**Issue by BlackYuzia** [webpack/webpack#12014]
# Bug report

I would build bundle by command `npm run build`.
After that I get complete bundle.
But when I change some value I get error in to console.

I would get this error when I didn't setup any loader for some types of files (like `.css`, `.js`, `.vue` etc)

I use **Vue + Vuetify** build.
I can share a full code base with you if you want.

**What is the current behavior?**

Sounds a little weird. But it really is.
Editing files that are not related to the main (bundle), it somehow breaks. Then it gives an error as if there are no loaders (loaders) that upload the necessary files.

> by google translate

**If the current behavior is a bug, please provide the steps to reproduce.**

I'm not sure. However, I think it is possible to repeat something like this:

1. Install **Webpack 5.4.0**
2. Install **Vue 2.6.12**
3. Install **Vuetify 2.3.16**
4. Install loaders (css, vue, sass and etc by vuetify docs)
5. Setup code for load Vue, Vuetify and etc.
6. Run build bundle.
7. Change code.
8. Get broken bundle.

**What is the expected behavior?**

I didn't get broken bundle by edit one of js files.

**Other relevant information:**
webpack version:  5.4.0
Node.js version:  12.18.3
Operating System: Windows
Additional tools:

### Screenshots

There I have fully work page without any changes:
![image](https://user-images.githubusercontent.com/25010528/99424969-f7477800-290a-11eb-8b54-b7f9c462c80d.png)
Then I change by adding comment line:
![image](https://user-images.githubusercontent.com/25010528/99424993-fd3d5900-290a-11eb-8721-be43b3076607.png)
Then I was restart page:
![image](https://user-images.githubusercontent.com/25010528/99425058-0cbca200-290b-11eb-8596-def7828a7b25.png)
Profit! Get error.
The same error but when I load min.css file (vuetify) 
![image](https://user-images.githubusercontent.com/25010528/99425139-20680880-290b-11eb-8913-cd898ad10bf0.png)

The same troubles I have without this css files.
for example when I remove this css file. I get second error:
![image](https://user-images.githubusercontent.com/25010528/99425854-185c9880-290c-11eb-88de-89a9e89fc2f7.png)

For fix this error I should rebuild bandle:
![image](https://user-images.githubusercontent.com/25010528/99425351-64f3a400-290b-11eb-9dbe-4b9ec8b2aab3.png)

After that all is work. IDK how that work.

Loaders:
![image](https://user-images.githubusercontent.com/25010528/99425449-85236300-290b-11eb-89b0-08a80a196145.png)

Sorry if I forget add something important.
Call me and I will try add this fast how I can.

**Comment by BlackYuzia** [comment]
Hi all who saw this issue.
Today, after awake, I see what this trouble has been disapear manualy.
Idk why. I didn't change anything. 

So, I should close this issue?

**Comment by evilebottnawi** [comment]
Yes, looks problem in `Vuetify`, nothing to do on webpack side
