### ISSUE TITLE
Third part file name will be added hash if file name is duplicated local file.

### ISSUE THREAD

**Issue by shenghou** [webpack/webpack#12017]
# Bug report

**What is the current behavior?**
 
 I use facebook sdk for live video and import fb sdk,  i also have a file named sdk.js, when building with webpack,  the fb sdk file will be add hash.

* Before 
![image](https://user-images.githubusercontent.com/24260845/99479373-03761880-2991-11eb-968c-7f6b46110550.png)

* After 
![image](https://user-images.githubusercontent.com/24260845/99479812-de35da00-2991-11eb-8530-b43e4ec6b5ef.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:    v4.41.0
Node.js version:      v12.18.2
Operating System:   mac os
Additional tools:

**Comment by evilebottnawi** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Please fill out all fields in the issue template
