### ISSUE TITLE
Polling option not picked up by watchpack

### ISSUE THREAD

**Issue by gilbox** [webpack/webpack#1201]
I wasn't sure if I should post this in `karma-webpack` issue tracker instead, but this seems like a webpack error to me. Using webpack v1.9.11, I am trying to enable poll-based watching, in my karma configuration I have

```
    webpack: {
        watchOptions: {
          poll: true
        },
        devtool: 'inline-source-map',
        resolve: webpackConfig.resolve,
        module: {
          loaders: [buildConfig.loaders.babel]
        }
    }
```

It seems as if the `watchOptions` options are not being propagated to watchpack. My other options work. I can add a single line to `node_modules/webpack/node_modules/watchpack/lib/DirectoryWatcher.js`:

         options.poll = true;

in the `DirectoryWatcher` function and then polling works.

Any ideas?

**Comment by sokra** [comment]
Propably a karma-webpack issue... `watchOptions` was added recently and karma-webpack wasn't updated.

**Comment by gilbox** [comment]
Thanks, I cross-posted in karma-webpack. However, afaict karma-webpack just [passes the options on to webpack](https://github.com/webpack/karma-webpack/blob/master/index.js#L51)

**Comment by evandegr** [comment]
I'm doing something like this:

```watchOptions: {
    aggregateTimeout: 500,
    poll: 500
}```

Does that fix it?

**Comment by gilbox** [comment]
@evandegr that doesn't fix it. You're doing that with `karma-webpack` ?

**Comment by gilbox** [comment]
I have a PR to fix this [here](https://github.com/webpack/karma-webpack/pull/59)
