### ISSUE TITLE
optimization.splitChunks.maxAsyncRequests does not affect how module federation shared modules are bundled

### ISSUE THREAD

**Issue by jasongrout** [webpack/webpack#12018]
## Feature request

I'm not sure if this is considered a bug, is expected behavior and I just need to research it more (I've read a lot of documentation...), or if it should be a feature request.

**What is the expected behavior?**

I expected that setting `optimization.splitChunks.maxAsyncRequests` would affect how module federation shared modules are bundled together. However it seems that each shared module is bundled into its own js file, no matter what the global splitChunks configuration is.

**What is motivation or use case for adding/changing the behavior?**

See https://github.com/jasongrout/webpack-testcase for a simplified repo reproducing this issue.

We have a use case with webpack module federation where we are sharing around 100 modules. This is leading us to having around 100 js files loaded on our initial page load.

I thought we would be able to control the number/size of bundles using the `optimization.splitChunks` configuration, in particular the `maxAsyncRequests` or `maxInitialRequests`, however setting those to small numbers does not seem to be helping (in the repo above we set them to 5, but we still end up with dozens of shared modules in separate js files).

Is there a better way to combine shared modules into larger bundles other than using cacheGroups like below? Or is this the recommended approach to combining shared modules? It seems like a bit of a sledgehammer to combine everything.

```js
      cacheGroups: {
        vendor: {
          test: /[\\/]node_modules[\\/]/,
          name: 'vendors',
          chunks: 'all'
        }
      }
```

**How should this be implemented in your opinion?**

I'm not sure.

**Are you willing to work on this yourself?**
I'm happy to assist, especially if it seems like a relatively light lift.

**Comment by evilebottnawi** [comment]
> Is there a better way to combine shared modules into larger bundles other than using cacheGroups like below?

Why? This kills the idea of module federation

> Or is this the recommended approach to combining shared modules?

You decide what will be included

**Comment by jasongrout** [comment]
Thanks. That sounds like it answers my question, i.e., it is expected behavior, and if I want the auto-splitting logic applied to a huge shared bundle, I first need to force everything (or whatever I want to group) into the same cache group.
