### ISSUE TITLE
When 'react-dom' is used in shared the remote app itself breaks and no error is logged

### ISSUE THREAD

**Issue by ajayjaggi** [webpack/webpack#12021]
# Bug report

 

**What is the current behavior?**
In shared if 'react-dom' is added the remote app itself breaks and no errors are logged 

the module federation plugin config is:
![Screen Shot 2020-11-17 at 4 09 11 PM](https://user-images.githubusercontent.com/46561425/99541792-44911b80-29d7-11eb-98bf-56257aac0383.png)

exposed component is :
![Screen Shot 2020-11-16 at 11 18 08 PM](https://user-images.githubusercontent.com/46561425/99541720-2deac480-29d7-11eb-812b-986dcd5e74f2.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
The remote app should not break.

**Other relevant information:**
webpack version:  5.4.0
Node.js version: 10.15.0
Operating System: mac os
Additional tools:

**Comment by evilebottnawi** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

> If the current behavior is a bug, please provide the steps to reproduce.

Do not ignore this

**Comment by ajayjaggi** [comment]
But i wrote that on adding 'react-dom' in shared breaks the app.that is the only step to reproduce it

**Comment by evilebottnawi** [comment]
Sorry reading code from snapshot is very hard, I will have to spend a lot of time to understand what and how you are using, which means that someone will not get help, respect time other developers and please use the issue template with all fields filled, thanks
