### ISSUE TITLE
Laravel 8 Wepback API configuration problem

### ISSUE THREAD

**Issue by VCollins** [webpack/webpack#12028]
# Bug report
Laravel 8 Wepback API configuration problem

**What is the current behavior?**
using "npm run dev" results in the error "Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema. configuration.module.rules[10] has an unknown property 'loaders' "

**If the current behavior is a bug, please provide the steps to reproduce.**
Environment: Vagrant VM with Linux 20.04, accessed through an elevated command prompt in Windows 10.
Navigate to directory hosting Laravel 8 project
Run command "rm -rf node_modules" and wait for the command to complete
Run command "rm package-lock.json"
Run command "npm cache clear --force"
Run command "sudo npm install --global npm"
Run command "sudo yarnpkg install"
Run command "sudo yarnpkg add babel@latest"
Run command "sudo yarnpkg add webpack@latest"
Run command "sudo yarnpkg add webpack-cli@latest"
Run command "sudo yarnpkg add vue-template-compiler --save-dev --production=false"
Run command "sudo yarnpkg add sass-loader@8.* sass --save-dev --production=false"
Run command "sudo npm install --global cross-env"
Run command "yarnpkg run dev"

**What is the expected behavior?**
Npm compiles the necessary files and assets, based on dependencies and provides a success message.

**Other relevant information:**
webpack version:  5.6.0
Node.js version: 10.19.0
Operating System: Windows 10, but VM is Vagrant build on Virtualbox manager
Additional tools:

**Comment by evilebottnawi** [comment]
> using "npm run dev" results in the error "Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema. configuration.module.rules[10] has an unknown property 'loaders' "

Fix, it, nothing to fix on webpack side or please open an issue in your boilerplate repo
