### ISSUE TITLE
When 'react-dom' is used in shared the remote app itself breaks and no error is logged

### ISSUE THREAD

**Issue by ajayjaggi** [webpack/webpack#12022]
# Bug report
In shared if 'react-dom' is added the remote app itself breaks and no errors are logged

the module federation plugin config is:
![Screen Shot 2020-11-17 at 4 09 11 PM](https://user-images.githubusercontent.com/46561425/99543256-ff6de900-29d8-11eb-8e11-e39842b180fe.png)

exposed component is :
![Screen Shot 2020-11-16 at 11 18 08 PM](https://user-images.githubusercontent.com/46561425/99543454-317f4b00-29d9-11eb-8298-3c936773f979.png)

**What is the current behavior?**
On using ExposedRoutes component and adding 'react-dom' to shared the app breaks.

**If the current behavior is a bug, please provide the steps to reproduce.**
add exposedRoutes component in exposes and add 'react-dom' to shared.The remote app will break on client without any error on console.

**What is the expected behavior?**
Why only 'react-dom' is breaking the app and not any other dependency

**Other relevant information:**
webpack version:  5.4.0
Node.js version: 10.15.0
Operating System: mac os
Additional tools:

**Comment by evilebottnawi** [comment]
No reproducible steps - no answer

> If the current behavior is a bug, please provide the steps to reproduce.
> add exposedRoutes component in exposes and add 'react-dom' to shared.The remote app will break on client without any error on console.

We don't know your config, we don't know your code, we don't know your plugins, we nothing know

**Comment by ajayjaggi** [comment]
ok i will also shared the whole config
