### ISSUE TITLE
Minimizer not preserving quoted reserved word property names

### ISSUE THREAD

**Issue by owenpearson** [webpack/webpack#12029]
# Bug report

**What is the current behavior?**

The webpack built-in 'minimizer' unquotes my reserved word property names meaning that my code will throw an error in environments that don't support ES5 and up.

**If the current behavior is a bug, please provide the steps to reproduce.**
`npm i webpack webpack-cli`

```js
// webpack.config.js
module.exports = {
  target: 'web',
  entry: './index.js',
}
```

```js
// index.js
console.log({ 'delete': '' });
```
`npx webpack`

Following these steps gives a bundle which looks like `console.log({delete:""});` which contains an unquoted reserved word property name despite the property name being quoted in the source.

**What is the expected behavior?**

Ideally webpack shouldn't affect the ECMA version of my output, or if it does, it should at least provide an `output.environment` configuration option to prevent this behaviour.

**Other relevant information:**
webpack version:  5.6.0
Node.js version: 14.14.0
Operating System: macOS Catalina 10.15
Additional tools:

**Comment by csvan** [comment]
This probably belongs in https://github.com/webpack-contrib/terser-webpack-plugin

**Comment by sokra** [comment]
@webpack-bot move to webpack-contrib/terser-webpack-plugin
