### ISSUE TITLE
Initial file change stuck at compiling need to save again

### ISSUE THREAD

**Issue by Koen028** [webpack/webpack#12026]
# Bug report

**What is the current behavior?**
When using `webpack-dev-server` with the following command:
```
webpack serve --hot --mode development --config-name <name>
```
Everything works fine except for the **first** change to any file it starts compiling an both the console inform me that it's compiling. In the console I see `i ｢wdm｣: Compiling...` and the browser console shows `[WDS] App updated. Recompiling...` good to note is that it gets printed out twice in the browser console.

After I change the file again it actually compiles and the change is being shown in the browser. It now works as normal.

**What is the expected behavior?**
I expect the first change to compile and show the change in the browser without having to change or save the file again.

**Other relevant information:**
webpack version:  **4.44.2**
Node.js version: **v14.15.0**
Operating System: **Windows 10**
Additional tools: 
- `webpack-dev-server`
- `mini-css-extract-plugin`
- `html-webpack-plugin`
- `clean-webpack-plugin`
- `css-minimizer-webpack-plugin`
- `terser-webpack-plugin`
- `html-webpack-harddisk-plugin`
- `@pmmmwh/react-refresh-webpack-plugin`

**Comment by evilebottnawi** [comment]
Sorry, please provide more information, your information is not helpful

**Comment by evilebottnawi** [comment]
> **If the current behavior is a bug, please provide the steps to reproduce.**

Do not ignore it, please fix the issue template and I will reopen it
