### ISSUE TITLE
When will modules in ensure() be loaded to page? 

### ISSUE THREAD

**Issue by littlee** [webpack/webpack#1202]
After reading the docs and examples of Code Split,
I don't really understand it.
```js
var a = require("a");
var b = require("b");
require.ensure(["c"], function(require) {
    require("b").xyz();
    var d = require("d");
});
```
My question is when will "c" be loaded?
When should I use require.ensure()?

**Comment by IngwiePhoenix** [comment]
A module that is targeted using require.ensure is loaded asynchronously. That means, it is loaded /after/ the page itself. Imagine you had a jQuery plugin, that you only wanted to load in certain situations, then you would use this. Here is a bit of code that I use to autoload Highlight.JS only when code blocks are there. This allows me to keep the main script’s filesize low, but load additional code on-demand.

    if($("body").find("pre code").length > 0) {
        require.ensure([
            // Should only load the hljs stuff we need...
            "highlight.js",
            // Stylesheet.
            "highlight.js/styles/hybrid.css"
        ], function(hljs){
            hljs.configure({
                tabReplace: Array(5).join(" ")
            });
            $("body").find("pre code").each(function(i,v){
                if($(v).prop("class").match(/language-.+/ig) != null) {
                    // The current block has a language- class.
                    $(v).addClass("hascode");
                    $(v).parent().addClass("hascode");
                    hljs.highlightBlock(v);
                }
            });
        });
    }

whenever you use require.ensure, that module is put into a separate chunk (aka. another file) which is added to the page once the call occurs. That is also why you have to supply a callback. It will only then be called when the async loading is done and the module is ready to be used.

**Comment by littlee** [comment]
:smile: :+1:

**Comment by bebraw** [comment]
@littlee Did you understand the explanation?

**Comment by littlee** [comment]
yes, if what @IngwiePhoenix said is true.
