### ISSUE TITLE
Make managedPaths support globs/anymatch

### ISSUE THREAD

**Issue by martpie** [webpack/webpack#12036]
## Feature request

With some setups (especially the ones making use of Yarn Workspaces), it is fairly common to use Webpack to apply some loaders to files located in `node_modules` (like a local package, or a module that needs to go through Babel, etc), and also watch changes happening in those files.

The problem with Webpack 5 is `snapshot.managedPaths`/`cache.managedPaths` only accepts an array of string representing a list of folders that "are not supposed to change" (that's my understanding of the feature).

So now, a solution is to just disable them:

```js
{
  snapshot: { 
    managedPaths: []
}
```

...which I would not recommend at all, as I assume it would introduce some severe performances hits for the cache.

So, it would be great if we could have the following:

```js
{
  snapshot: { 
    managedPaths: ['**node_modules/{!some-module,or-another}/**/*']
  }
}
```

**What is the expected behavior?**

Nothing is expected, this is a proposal/requet.

**What is motivation or use case for adding/changing the behavior?**

cf. above.

**How should this be implemented in your opinion?**

It looks to me that using `anymatch` on `managedPaths` would not break anything. I have absolutely no knowledge of Webpack's internals, I may say something really stupid here.

**Are you willing to work on this yourself?**

If it receives the blessing of an official Webpack member, yes!

**Comment by evilebottnawi** [comment]
Sorry out of scope webpack, we avoid using `glob` syntax in the config (expect edge cases), you can achieve this on own side, just write own logic in the config file

**Comment by evilebottnawi** [comment]
Logic for this options can be very complex, so we try to keep it simple as possible and complex solutions we leave it to the developers

**Comment by sokra** [comment]
Wrap the glob within `glob.sync` in the config
