### ISSUE TITLE
Plugin that process content before loaders

### ISSUE THREAD

**Issue by DatenMetzgerX** [webpack/webpack#1203]
I have a question to how plugins work. It's hard to figure out the correct extension point to use by reading the documentation. So I hope someone can help me which extension point I have to use. 

I want to create a plugin that extracts information from all used html files and write the result into a single json file. First I tried to use a (pre) loader, but with a loader I couldn't figure out how to postpone the emitting of the file until compilation is complete. That's the reason why I tried to create my own plugin. 
So I'm looking for an extension point where I get the source of the file (like a pre-loaders). 

Thanks for your help, 
Micha

**Comment by sokra** [comment]
Try a combination of loader and plugin. There is a hook to extend the loader context to establish a communication channel between plugin and loader.
