### ISSUE TITLE
Bug when processing handlebars templates.

### ISSUE THREAD

**Issue by pherman** [webpack/webpack#12039]
# Bug report

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

The minimal working example can be found here: [https://gist.github.com/pherman/30763567e1c5245c752be9ac693d5b3f](https://gist.github.com/pherman/30763567e1c5245c752be9ac693d5b3f
)

Run `npm install` to install the dev dependencies and then `npm run build && npm start` to test.

You should see something like this in the console:

`<link href="71660f764fdd7f9399f45b22b5c50f83.css" rel="stylesheet">My name is Bourne.`

When you open the css file, you will see:

`
:root {
     content: '{{ color }}';
}
`

Thus far, everything works as expected.

Now to reproduce the bug, go into webpack.config.js and comment out VERSION 0 and remove the comments from VERSION 1.

Rebuild and rerun and you will again see html similar to the above in the console but if you open the css file, you will find this:

`<link href="./some.css" rel="stylesheet" type="text/css">My name is .`

This is the more.html file except that the variable is replaced with the empty string.  Here I would expect:

`
:root {
     content: 'red';
}
`

Interestingly, if you then uncomment the first line in index.js that require some.css directly, rebuild, and rerun, the output is correct.  This implies that this can't be a bug in handlebars-loader.  Perhaps there is a caching issue here?

**Other relevant information:**
webpack version:  5.6.0
Node.js version: 6.14.8
Operating System: Ubuntu
Additional tools:

**Comment by sokra** [comment]
This doesn't seem to be a webpack issue. It looks like there is some global state in the output of handlebars-loader. Probably it's also using `module.exports` which overrides your loader code. Avoid using direct `eval`. Replace it with `(0,eval)(...)` and you probably get better errors. Also inspect the output of handlebars-loader (`source`).
