### ISSUE TITLE
cheap-module-source-map & inline-source-map is failing build in Webpack 5

### ISSUE THREAD

**Issue by GorvGoyl** [webpack/webpack#12041]
# Bug report

**What is the current behavior?**
I get the below error when I use `cheap-module-source-map` or `inline-source-map` in webpack config. 
Please note that build works fine if I use eval based source map like `eval-cheap-module-source-map`.

You can see that webpack config file: https://github.com/GorvGoyl/Notion-Boost-browser-extension/blob/72c0da7202b2cbcd6006d553fe59035abdb8d9e4/webpack.config.js#L217

```
[ Starting the Hot Extension Reload Server... ]
[webpack-cli] Compilation starting...
(node:5728) [DEP_WEBPACK_COMPILATION_AFTER_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: afterOptimizeChunkAssets is deprecated (use Compilation.hook.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)
(node:5728) [DEP_WEBPACK_DEPRECATION_ARRAY_TO_SET] DeprecationWarning: Compilation.chunks was changed from Array to Set (using Array method 'reduce' is deprecated)
(node:5728) UnhandledPromiseRejectionWarning: TypeError: item.listMap is not a function
    at ConcatSource.listMap (C:\Users\1gour\OneDrive\Documents\old\Github\Notion-Boost-browser-extension\node_modules\webpack-sources\lib\ConcatSource.js:72:18)  
    at ConcatSource.proto.sourceAndMap (C:\Users\1gour\OneDrive\Documents\old\Github\Notion-Boost-browser-extension\node_modules\webpack-sources\lib\SourceAndMapMixin.js:24:16)
    at getTaskForFile (C:\Users\1gour\OneDrive\Documents\old\Github\Notion-Boost-browser-extension\node_modules\webpack\lib\SourceMapDevToolPlugin.js:78:30)      
    at C:\Users\1gour\OneDrive\Documents\old\Github\Notion-Boost-browser-extension\node_modules\webpack\lib\SourceMapDevToolPlugin.js:265:22
    at C:\Users\1gour\OneDrive\Documents\old\Github\Notion-Boost-browser-extension\node_modules\webpack\lib\Cache.js:91:34
    at Array.<anonymous> (C:\Users\1gour\OneDrive\Documents\old\Github\Notion-Boost-browser-extension\node_modules\webpack\lib\cache\MemoryCachePlugin.js:45:13)  
    at C:\Users\1gour\OneDrive\Documents\old\Github\Notion-Boost-browser-extension\node_modules\webpack\lib\Cache.js:91:19
    at Hook.eval [as callAsync] (eval at create (C:\Users\1gour\OneDrive\Documents\old\Github\Notion-Boost-browser-extension\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:19:1)
    at Cache.get (C:\Users\1gour\OneDrive\Documents\old\Github\Notion-Boost-browser-extension\node_modules\webpack\lib\Cache.js:75:18)
    at ItemCacheFacade.get (C:\Users\1gour\OneDrive\Documents\old\Github\Notion-Boost-browser-extension\node_modules\webpack\lib\CacheFacade.js:116:15)
(node:5728) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5728) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
**If the current behavior is a bug, please provide the steps to reproduce.**

- Clone `https://github.com/GorvGoyl/Notion-Boost-browser-extension/tree/webpack5_devtool_bug`
- `npm install`
- run webpack in development mode `npm run start:ch`
- build would fail with above error.

**What is the expected behavior?**

**Other relevant information:**
webpack version:  5.6.0
Node.js version: 12.15.0
Operating System: Win10
Additional tools: Powershell Core, VSCode

**Comment by evilebottnawi** [comment]
You use incompatible plugin with webpack@5, you can see warning in your console, not sure what we can do here

**Comment by GorvGoyl** [comment]
Are you talking about the internal SourceMapDevToolPlugin used by webpack? If so, I don't see in docs which values are incompatible with v5 https://webpack.js.org/configuration/devtool/#root

**Comment by evilebottnawi** [comment]
> [webpack-cli] Compilation starting...
(node:5728) [DEP_WEBPACK_COMPILATION_AFTER_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: afterOptimizeChunkAssets is deprecated (use Compilation.hook.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)
(node:5728) [DEP_WEBPACK_DEPRECATION_ARRAY_TO_SET] DeprecationWarning: Compilation.chunks was changed from Array to Set (using Array method 'reduce' is deprecated)
(node:5728) UnhandledPromiseRejectionWarning: TypeError: item.listMap is not a function

Please read how to debug deprecation in node  https://nodejs.org/api/cli.html#cli_trace_deprecation

And you will found these plugins

**Comment by GorvGoyl** [comment]
Got it. Cluprit is `merge-jsons-webpack-plugin`.  To be fair webpack should provide proper details about the plugin causing issues.

**Comment by evilebottnawi** [comment]
We already do it, you can see a lot of deprecation warnings + some of them can't be detailed due breaking change, please open an issue in `merge-jsons-webpack-plugin`, nothing to fix here
