### ISSUE TITLE
webpack 5.6.0 fails to compile

### ISSUE THREAD

**Issue by zengbiaozengbiao** [webpack/webpack#12048]
I encountered a problem when trying webpack 5.6.0 again，The error content is as follows： 

ERROR  Error: Rule can only have one resource source (provided resource and test + include + exclude) in {
  "exclude": [
    null
  ],
  "use": [
    {
      "loader": "C:\\Users\\MyObject\\etc-manage\\node_modules\\cache-loader\\dist\\cjs.js",
      "options": {
        "cacheDirectory": "C:\\Users\\MyObject\\etc-manage\\node_modules\\.cache\\babel-loader",
        "cacheIdentifier": "ba8d0e54"
      },
      "ident": "clonedRuleSet-38[0].rules[0].use[0]"
    },
    {
      "loader": "C:\\Users\\MyObject\\etc-manage\\node_modules\\babel-loader\\lib\\index.js",
      "options": "undefined",
      "ident": "undefined"
    }
  ]
}

**Comment by zengbiaozengbiao** [comment]
![webpack](https://user-images.githubusercontent.com/45677823/100048730-7b8c8480-2e50-11eb-8d4c-f4d9faa6159c.png)

**Comment by evilebottnawi** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Fix your configuration, you have wrong options for loaders
