### ISSUE TITLE
Awesomness should be promoted on StackShare

### ISSUE THREAD

**Issue by zharikovpro** [webpack/webpack#1204]
WebPack is so great, that it definitely should be promoted on http://stackshare.io/vendors

**Comment by sokra** [comment]
Yeah, how to add it?

**Comment by zharikovpro** [comment]
Just follow up sign up instructions on mentioned page: http://take.ms/MGj1N

**Comment by zharikovpro** [comment]
Oh well, found direct link: http://stackshare.io/submit

**Comment by sokra** [comment]
Ok it's already submitted...

**Comment by sokra** [comment]
http://stackshare.io/webpack
