### ISSUE TITLE
`npm link` doesn't work between webpack 5 and webpack 4 builds

### ISSUE THREAD

**Issue by testacode** [webpack/webpack#12050]
# Bug report

Gitter seems dead, I've placed questions there and nobody answers. It's just a posting questions place with no answers.

**What is the current behavior?**
When trying to link a library built with webpack 4 in development mode into a project that consumes that library and it's built with webpack 5, also in development mode, I get the following error.

![image](https://user-images.githubusercontent.com/1852080/100140522-d386b380-2e6f-11eb-90b5-ddb284924a34.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
Just link a package built with webpack 4 in development mode into an app that's built with webpack 5 in development mode and that's pretty much it.

[The gist with the configs example](https://gist.github.com/testacode/0013e690490dd5fa049d3f52e4ecca72)

**What is the expected behavior?**
The expected behavior would be to be able to link the library into the app so that I can develop in a more dynamic way without having to deploy the library package.

**Other relevant information:**
webpack version:  5.6.0 vs 4.43.0
Node.js version: 12 lts
Operating System: OSX Mojave
Additional tools:

**Comment by testacode** [comment]
If I remove the `modules: commonjs` from the webpack config I get another error now (more friendly I guess):
![Uploading image.png…]()

**Comment by ScriptedAlchemy** [comment]
Depending on what your linking. Resolutions will not work correctly since the linked package likely has dev dependencies causing code inside that package to resolve to its own modules folder. 

This isn’t uncommon. Yarn pack or npm pack the file / just cp it works pretty well

**Comment by evilebottnawi** [comment]
Answer above

**Comment by testacode** [comment]
Sorry, I must reopen it. I've removed all of the modules resolution and now I get the following issue.
The dependency I need to link has a peer dependency of `react`. And removed all module resolves from the "shell" app that loads this linked dependency.

![image](https://user-images.githubusercontent.com/1852080/100236303-3fb6f500-2f0c-11eb-828d-a5d2614f5265.png)

**Comment by evilebottnawi** [comment]
@testacode What your expected from webpack here? Answer is right

**Comment by testacode** [comment]
Finally it was the sourcemaps generations.
