### ISSUE TITLE
Webpack not preloading assets when using compression-webpack-plugin

### ISSUE THREAD

**Issue by PiotrSkrzynski88** [webpack/webpack#12054]
# Bug report

**What is the current behavior?**
When using plugin **compression-webpack-plugin** and import `/ * webpackPreload: true * /` webpack tries to preload a non-existent, uncompressed file

**If the current behavior is a bug, please provide the steps to reproduce.**
Minimal reproduction repo: https://github.com/PiotrSkrzynski88/webpack-compression-preload.git
Checkout README.md for reproduction steps
Checkout console to see 404 

**What is the expected behavior?**
Webpack should preload file compressed by compression-webpack-plugin

**Other relevant information:**
webpack version:  5.6.0
Node.js version: 14.15.0
Operating System: macOS Catalina 10.15.5
Additional tools:

**Comment by evilebottnawi** [comment]
Expected, compression-webpack-plugin only for servers (nginx/apache/etc), browser ask server to load assets and server return compressed source and avoid extra compression on server side
