### ISSUE TITLE
Webpack not setting NODE_ENV="production" for mode:"production"

### ISSUE THREAD

**Issue by cbdeveloper** [webpack/webpack#12055]
# Bug report

**What is the current behavior?**

Webpack doesn't seem to be setting the `NODE_ENV=production` when called with `mode: "production"`

**If the current behavior is a bug, please provide the steps to reproduce.**

I have a build script on `build.sh`

**package.json**

```
"build-sh": "./scripts/build/build.sh",
```

**build.sh**

I have isolated just the webpack call of the build process. Everything else is currently disabled.

```
webpack  \
--config webpack.prod.js
```

**webpack.prod.js**

My webpack config will log the `NODE_ENV`.

```
console.log("======================================");
console.log("FROM WEBPACK.PROD.JS...");
console.log(`NODE_ENV: ${JSON.stringify(process.env.NODE_ENV)}`);
console.log("======================================");
console.log("");

const config = {
  
  ...sharedConfig,

  mode: "production",       // <==== PRODUCTION MODE
  devtool: "none",

  // OTHER CONFIGS...
}
```

My `js, ts, tsx` files are handled by `babel-loader`. And here is my `babel.config.js` file:

**babel.config.js**

My babel config (which I guess is being called by webpack => babel-loader) will also log the `NODE_ENV`.

```
module.exports = function (api) {

  const NODE_ENV = JSON.stringify(api.env());

  console.log("");
  console.log("=================================");
  console.log("FROM BABEL.CONFIG.JS (ON ROOT)...");
  console.log(`NODE_ENV: ${NODE_ENV}`);
  console.log("=================================");
  console.log("");

  // OTHER CONFIGS
}
```

**What is the expected behavior?**

I would expect `webpack.prod.config` to log `NODE_ENV` as `undefined`, given the fact that it's not being set on the `webpack` call made by `build.sh`.

But I would expect `babel.config.js` to log `NODE_ENV` as `production`, given the fact that `webpack.prod.js` is initiating the bundle process with `mode: "production"`, which is supposed to set a `NODE_ENV="production"` variable. As per the [docs](https://webpack.js.org/configuration/mode/)

But here is what I'm getting as logs:

![image](https://user-images.githubusercontent.com/43407798/100232368-320b6a80-2f20-11eb-8953-f2fd6bfcfcb3.png)

If I change `build.sh` to add the `NODE_ENV=production` for the `webpack` call. Here is what happens:

```
# PRODUCTION BUILD WITH WEBPACK
cross-env NODE_ENV=production webpack  \
--config webpack.prod.js
```

Resulting logs:

![image](https://user-images.githubusercontent.com/43407798/100232585-726ae880-2f20-11eb-896a-6e4a336daca9.png)

Now both configs log `"production"`. Which makes sense, since the `NODE_ENV` was set before the `webpack` call.

**QUESTION**

Shouldn't `babel.config.js` be logging `"production"` without me having to add the `NODE_ENV`? Just by the fact that `webpack.config.js` is returning `mode: "production"` ?

Sorry if I missed something, but I was expecting something different from what I've read on the docs. Am I doing something wrong or is this some kind of bug?

**Other relevant information:**
webpack version:  
```
    "webpack": "^4.44.2",
    "webpack-cli": "^3.3.12",
    "webpack-dev-server": "^3.11.0"
```
Node.js version: `v10.19.0`
Operating System: `Windows 10 Home`
Additional tools: Babel

```
    "@babel/cli": "^7.11.6",
    "@babel/core": "^7.11.6",
    "@babel/node": "^7.10.5",
    "@babel/preset-env": "^7.11.5",
    "@babel/preset-react": "^7.10.4",
    "@babel/preset-typescript": "^7.10.4",
    "babel-eslint": "^10.1.0",
    "babel-loader": "^8.1.0",
    "babel-plugin-module-resolver": "^4.0.0",
    "babel-plugin-styled-components": "^1.11.1",
    "babel-plugin-transform-react-remove-prop-types": "^0.4.24",
```

**Comment by evilebottnawi** [comment]
`--mode=production` set `process.env.NODE_ENV` only for compiled code (`entry` and `import`/`require` inside `entry` files), it is not modified `process.env.NODE_ENV` in your config files, so it expected, feel free to feedback

**Comment by cbdeveloper** [comment]
@evilebottnawi thank you for the explanation. Sorry about the confusion.

I re-read the docs on [config mode](https://webpack.js.org/configuration/mode/) and I think there is room for improvement.

I guess most people use `webpack` to run bundles on browsers, which, by default, don't have a `process.env`, so I think it could be more explicit what `webpack` is doing by setting that variable and why it does that.

Also, this part:

> Please remember that setting `NODE_ENV` doesn't automatically set mode.

What `NODE_ENV` is this quote referring to? Isn't it the Node's `NODE_ENV` ? Or is it a `NODE_ENV` that could be inserted at the resulting compiled code by using `DefinePlugin` ?


![image](https://user-images.githubusercontent.com/43407798/100242771-165a9100-2f2d-11eb-97e3-339635812b70.png)

**Comment by evilebottnawi** [comment]
@cbdeveloper Please opan an issue in webpack docs repo, we can improve this
