### ISSUE TITLE
 I encountered a problem when trying webpack 5.6.0 again，The error content is as follows：

### ISSUE THREAD

**Issue by zengbiaozengbiao** [webpack/webpack#12051]
ERROR Error: Rule can only have one resource source (provided resource and test + include + exclude) in {
"exclude": [
null
],
"use": [
{
"loader": "C:\Users\MyObject\etc-manage\node_modules\cache-loader\dist\cjs.js",
"options": {
"cacheDirectory": "C:\Users\MyObject\etc-manage\node_modules\.cache\babel-loader",
"cacheIdentifier": "ba8d0e54"
},
"ident": "clonedRuleSet-38[0].rules[0].use[0]"
},
{
"loader": "C:\Users\MyObject\etc-manage\node_modules\babel-loader\lib\index.js",
"options": "undefined",
"ident": "undefined"
}
]
}

**Other relevant information:**
webpack version:  5.6.0
Node.js version: 14.15.0
Operating System: windows10
Additional tools:webstorm 2020

**Comment by evilebottnawi** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
