### ISSUE TITLE
Question about remove package.json information in bundle.js file.

### ISSUE THREAD

**Issue by madist** [webpack/webpack#12059]
Is there any way to remove package.json information in `main.bundle.js` file
cause, when i deployed on website. someone read main.bundle.js and get package.json info. after that, he create library my private module which upload on my private npm repo.

that guys upload same named module on `public npm repo`...

so, when i using `^x.x.x` than, that guy's module is downloaded. which is dummy. totally different. so, when i build my webpack. it appears error.

so, i wanna remove package.json information in my `main.bundle.js` file. 
is there any option?

cause, i build with production level. but it exists.

I'm using cra(eject) + webpack.

my webpack is below
```

"webpack": "3.8.1",
    "webpack-dev-server": "2.9.4",
    "webpack-manifest-plugin": "1.3.2",
```

**Comment by sokra** [comment]
Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md).
