### ISSUE TITLE
Strip comments

### ISSUE THREAD

**Issue by IngwiePhoenix** [webpack/webpack#1205]
Although I am using the UglifyJS plugin and have options turned on, I still get some comments in the code like `/*! ... */`. I want to strip my **entire** output of any comment. How can I do that?

Kind regards, Ingwie.

**Comment by sokra** [comment]
See uglifyjs options. Use the uglifyjsplugin.

**Comment by IngwiePhoenix** [comment]
But I am already using it. O.o

```javascript
var uglify = new webpack.optimize.UglifyJsPlugin({
    compress: {
        warnings: false,
        properties: true,
	sequences: true,
	dead_code: true,
	conditionals: true,
        comparisons: true,
        evaluate: true,
	booleans: true,
	unused: true,
        loops: true,
        hoist_funs: true,
        cascade: true,
	if_return: true,
	join_vars: true,
	//drop_console: true,
        drop_debugger: true,
        negate_iife: true,
        unsafe: true,
        hoist_vars: true,
        //side_effects: true
    },
    //sourceMap: true,
});
```

What is the option to suppress comments?

**Comment by taurose** [comment]
```js
new webpack.optimize.UglifyJsPlugin({
    output: {
        comments: false
    }
})
```

**Comment by frg** [comment]
I'm still getting comments in my bundle. Can anyone help me out?

uglifyjs options:
'''
plugins: [
    new Webpack.optimize.UglifyJsPlugin({
      compress: {
        sequences: true,
        dead_code: true,
        conditionals: true,
        booleans: true,
        unused: true,
        if_return: true,
        join_vars: true,
        drop_console: true
      },
      mangle: {
        except: ['$super', '$', 'exports', 'require']
      },
      output: {
        comments: false
      } 
    })
  ]
'''

Command I'm running:
'''
set NODE_ENV=production & webpack -p --optimize-minimize --optimize-dedupe --config webpack.production.config.js
'''

**Comment by rkovacevic** [comment]
+1

Any news on this?

**Comment by IngwiePhoenix** [comment]
I get them stripped now. This is my config for Uglifyjs. The only place where comments are left, is CSS.

```javascript
module.exports = {
    compress: {
        warnings: false,
        properties: true,
        sequences: true,
        dead_code: true,
        conditionals: true,
        comparisons: true,
        evaluate: true,
        booleans: true,
        unused: true,
        loops: true,
        hoist_funs: true,
        cascade: true,
        if_return: true,
        join_vars: true,
        //drop_console: true,
        drop_debugger: true,
        unsafe: true,
        hoist_vars: true,
        negate_iife: true,
        //side_effects: true
    },
    //sourceMap: true,
    mangle: {
        toplevel: true,
        sort: true,
        eval: true,
        properties: true
    },
    output: {
        space_colon: false,
        comments: function(node, comment) {
            var text = comment.value;
            var type = comment.type;
            if (type == "comment2") {
                // multiline comment
                return /@copyright/i.test(text);
            }
        }
    }
}
```

Notice the function there - that does the trick. It only leaves comments with `@copyright` in. All others are goners.

**Comment by frg** [comment]
I ended up using this config. Seems to get me the smallest build file.

```
{
  debug: false,
  sourceMap: false,
  entry: ...,
  output: {...},
  resolve: {...},
  module: {...},
  plugins: [
    new Webpack.optimize.DedupePlugin(),
    new Webpack.optimize.AggressiveMergingPlugin(),
    new Webpack.optimize.UglifyJsPlugin({
      sourceMap: false,
      compress: {
        sequences: true,
        dead_code: true,
        conditionals: true,
        booleans: true,
        unused: true,
        if_return: true,
        join_vars: true,
        drop_console: true
      },
      mangle: {
        except: ['$super', '$', 'exports', 'require']
      },
      output: {
        comments: false
      } 
    })
  ]
}
```

Where "..." are irrelevant settings.

@IngwiePhoenix 's solution seems good but I haven't tried it yet so I can't vouch for it :)

**Comment by rkovacevic** [comment]
Thanks. Still playing with it. 

btw @IngwiePhoenix what happened to this:
https://www.npmjs.com/package/stripcomment-loader

github page is 404

**Comment by Zorgatone** [comment]
[**@IngwiePhoenix**](https://github.com/IngwiePhoenix) commented on [8 nov 2015, 17:54 CET](https://github.com/webpack/webpack/issues/1205#issuecomment-154840823 "2015-11-08T16:54:48Z - Replied by Github Comment Enhancer"):
> I get them stripped now. This is my config for Uglifyjs. The only place where comments are left, is CSS.
> 
> <div class="highlight highlight-source-js"><pre><span class="pl-c1">module</span>.exports <span class="pl-k">=</span> {
>     compress<span class="pl-k">:</span> {
>         warnings<span class="pl-k">:</span> <span class="pl-c1">false</span>,
>         properties<span class="pl-k">:</span> <span class="pl-c1">true</span>,
>         sequences<span class="pl-k">:</span> <span class="pl-c1">true</span>,
>         dead_code<span class="pl-k">:</span> <span class="pl-c1">true</span>,
>         conditionals<span class="pl-k">:</span> <span class="pl-c1">true</span>,
>         comparisons<span class="pl-k">:</span> <span class="pl-c1">true</span>,
>         evaluate<span class="pl-k">:</span> <span class="pl-c1">true</span>,
>         booleans<span class="pl-k">:</span> <span class="pl-c1">true</span>,
>         unused<span class="pl-k">:</span> <span class="pl-c1">true</span>,
>         loops<span class="pl-k">:</span> <span class="pl-c1">true</span>,
>         hoist_funs<span class="pl-k">:</span> <span class="pl-c1">true</span>,
>         cascade<span class="pl-k">:</span> <span class="pl-c1">true</span>,
>         if_return<span class="pl-k">:</span> <span class="pl-c1">true</span>,
>         join_vars<span class="pl-k">:</span> <span class="pl-c1">true</span>,
>         <span class="pl-c">//drop_console: true,</span>
>         drop_debugger<span class="pl-k">:</span> <span class="pl-c1">true</span>,
>         unsafe<span class="pl-k">:</span> <span class="pl-c1">true</span>,
>         hoist_vars<span class="pl-k">:</span> <span class="pl-c1">true</span>,
>         negate_iife<span class="pl-k">:</span> <span class="pl-c1">true</span>,
>         <span class="pl-c">//side_effects: true</span>
>     },
>     <span class="pl-c">//sourceMap: true,</span>
>     mangle<span class="pl-k">:</span> {
>         toplevel<span class="pl-k">:</span> <span class="pl-c1">true</span>,
>         sort<span class="pl-k">:</span> <span class="pl-c1">true</span>,
>         eval<span class="pl-k">:</span> <span class="pl-c1">true</span>,
>         properties<span class="pl-k">:</span> <span class="pl-c1">true</span>
>     },
>     output<span class="pl-k">:</span> {
>         space_colon<span class="pl-k">:</span> <span class="pl-c1">false</span>,
>         <span class="pl-en">comments</span><span class="pl-k">:</span> <span class="pl-k">function</span>(<span class="pl-smi">node</span>, <span class="pl-smi">comment</span>) {
>             <span class="pl-k">var</span> text <span class="pl-k">=</span> comment.<span class="pl-c1">value</span>;
>             <span class="pl-k">var</span> type <span class="pl-k">=</span> comment.<span class="pl-c1">type</span>;
>             <span class="pl-k">if</span> (type <span class="pl-k">==</span> <span class="pl-s"><span class="pl-pds">"</span>comment2<span class="pl-pds">"</span></span>) {
>                 <span class="pl-c">// multiline comment</span>
>                 <span class="pl-k">return</span><span class="pl-sr"> <span class="pl-pds">/</span>@copyright<span class="pl-pds">/</span>i</span>.<span class="pl-c1">test</span>(text);
>             }
>         }
>     }
> }</pre></div>
> 
> Notice the function there - that does the trick. It only leaves comments with `@copyright` in. All others are goners.

In which file did you put that `module.exports`?

Also I don't get why you have to declare the plugin. Doesn't `webpack -p` already uses `UglifyJS`?
Does the plugin work everytime or just in production mode when using `webpack -p`?

**Comment by ianwith** [comment]
+1

@sokra 
I am using the following uglifyjs options:
```
new webpack.optimize.UglifyJsPlugin({
    compress: { warnings: false },
    comments: false,
    sourceMap: false
})
```

I get no comments in JS bundle, BUT still ```/*! xxxx */``` in CSS.
How can I strip these comments in CSS files? Is there any workaround?

**Comment by frg** [comment]
@ianwith Correct me if I'm wrong, but I don't believe "UglifyJsPlugin" works with css.

**Comment by barroudjo** [comment]
Just to let you know, using UglifyJsPlugin sets the minimize option to true for all loaders. I had to dive in webpack's code to find out about this, it's bad design and it's already changed in version 2 (beta as of now) but I guess we'll have to live with it as it is in version 1.x.x.

**Comment by viko16** [comment]
@ianwith 
You can try this `css-loader` option:
```
loaders: [{
  test: /\.css$/,
  loader: ExtractTextPlugin.extract('style-loader', 'css-loader?' + JSON.stringify({discardComments: {removeAll: true}}))
}]
```

Document: 
- http://cssnano.co/options/
- https://github.com/ben-eb/postcss-discard-comments#removeall

**Comment by bebraw** [comment]
To summarize, both JS (uglify) and CSS (`css-loader`) need to be configured separately for this to work. Closing.

**Comment by LoicMahieu** [comment]
Update snippet from @viko16  :

```js
loaders: [{
  test: /\.css$/,
  loader: ExtractTextPlugin.extract('style-loader', 'css-loader?' + JSON.stringify({ minimize: { discardComments: { removeAll: true } } })
}]
```

**Comment by ccorcos** [comment]
This worked for me:

```
				new webpack.optimize.UglifyJsPlugin({
					comments: (astNode: any, comment: any) => false,
				}),
```

Saved me 250KB!

**Comment by ReeganExE** [comment]
I use this for CSS:
```js
{
  test: /\.s?css$/,
  use: ExtractTextPlugin.extract({
    fallback: 'style-loader',
    use: [
      {
        loader: 'css-loader',
        options: {
          minimize: { discardComments: { removeAll: true } }
        }
      },
      'sass-loader'
    ]
  })
}
```
And this for JS:
```js
plugins: [
  // ...
  new webpack.optimize.UglifyJsPlugin({
    beautify: false,
    mangle: {
      screw_ie8: true,
      keep_fnames: false
    },
    compress: {
      screw_ie8: true
    },
    comments: false
  }),
  // ...
]
```

**Comment by xgqfrms-gildata** [comment]
# webpack2 & create-react-app

**Comment by EvanBurbidge** [comment]
If anyones using typescript you can set removeComments in the tsconfig.json to true and that'll remove all the comments from your produced code. Hope this helps someone as a quick workaround.

**Comment by xeptore** [comment]
im using Webpack 4 and the problem with `.js` files was fixed by adding [UglifyjsWebpackPlugin](https://www.npmjs.com/package/uglifyjs-webpack-plugin), but the problem with `.css` (`.scss`) file was not fixed even after i tried **all** of the solutions above.
After 2 hours of struggling with configuration and different plugins,  i realized that my problem was about [Webpack build caching](https://webpack.js.org/guides/caching/). the `css` generated files were cached and the output `css` was not affected by changes to Webpack configuration and plugins.
So i first disabled the cache and then after following the official docs about [minimizing css for production](https://webpack.js.org/plugins/mini-css-extract-plugin/#minimizing-for-production), and installing [Optimize CSS Assets Plugin](https://github.com/NMFR/optimize-css-assets-webpack-plugin) and also **adding** it to Webpack plugins array (which was not covered in Webpack official doc, but was described in the plugin documentation [example](https://github.com/NMFR/optimize-css-assets-webpack-plugin#example)), my problem was fixed and there were not comments both in `css` and `js`.

Here is my Webpack configuration (some parts removed, for the sake of brevity):
```js
const UglifyJsPlugin = require('uglifyjs-webpack-plugin');
const OptimizeCSSAssetsPlugin = require('optimize-css-assets-webpack-plugin');


module.exports = {
  /*
  * other configurations
  */,

  optimization: {
    minimizer: [
      new TerserJSPlugin({}), // do not forget to add this. it's Webpack's default.
      new OptimizeCSSAssetsPlugin({
        cssProcessorPluginOptions: {
          preset: ['default', { discardComments: { removeAll: true } }],
        },
      })
    ],
  },

  /*
  * other configurations
  */,

  plugins: [

  /* other plugins */,

  new OptimizeCSSAssetsPlugin({
    cssProcessorPluginOptions: {
      preset: ['default', { discardComments: { removeAll: true } }],
    },
  }),

  /* other plugins */,

  ]
}
```

Sorry for my bad English, i hope it helps :)
