### ISSUE TITLE
How can I get the build's hash externally? 

### ISSUE THREAD

**Issue by dragonDScript** [webpack/webpack#12056]
I want to get the build hash externally. The use case is; I'm using nodemon together with webpack parallel and I need the hash to run this app. Nodemon-Webpack-Plugin doesn't meet my requirements, so I can't use it either.
These are my NPM Scripts:
```json
    "dev": "cross-env NODE_ENV=development npm run pack:webpack:preload:dev && run-p watch:webpack:main:dev watch:webpack:renderer:dev",
    "pack": "cross-env NODE_ENV=production webpack --config webpack.config.js",
```
*I use Webpack 5.*

**Comment by bebraw** [comment]
You have it in build stats and you can get it through the CLI as well. I wrote [a small reference](https://survivejs.com/webpack/optimizing/build-analysis/) on the feature. I hope that helps.

**Comment by dragonDScript** [comment]
OK, thanks.

**Comment by dragonDScript** [comment]
I fixed this by following this reference, and making a node.js script. Thank you.
