### ISSUE TITLE
Module not found: Error: Can't resolve 'server' in 'E:\Downloads\folder'

### ISSUE THREAD

**Issue by Devinora** [webpack/webpack#12064]
- Operating System: Windows 10 Pro 20H2 19042.630
- Node Version: v14.15.1
- NPM Version: v6.14.9
- webpack Version:  v^5.7.0
- webpack-dev-server Version: v^3.11.0
- Browser: Google Chrome 86.0.4240.198

- [x ] This is a **bug**
- [ ] This is a **modification** request

### Code

![Files](http://dl3.joxi.net/drive/2020/11/26/0018/1236/1221844/44/e835b4e7b9.png)

```js
// webpack.config.js

const webpack = require('webpack');
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
  entry: {
    index: './src/js/index.js',
  },
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: './js/[name].js',
  },
  devServer: {
    overlay: true,
    host: '0.0.0.0',
    public: 'my ip',
    port: '3000',
  },
  plugins: [
    new HtmlWebpackPlugin({
      filename: 'index.html',
      template: './src/index.html',
      chunks: ['index'],
    }),
  ],
};
```

```js
// package.json

{
  "name": "webpack-test",
  "version": "1.0.0",
  "description": "",
  "private": true,
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Devinora",
  "license": "ISC",
  "devDependencies": {
    "html-webpack-plugin": "^4.5.0",
    "webpack": "^5.7.0",
    "webpack-cli": "^4.2.0",
    "webpack-dev-server": "^3.11.0"
  }
}
```

### Expected Behavior

this is a test build to check for an error. **js file is empty**. the build happens fine, but when I turn on **dev-server**, then this error occurs. even installed the dependency:  [**Options that are compatible with webpack-dev-middleware have 🔑 next to them.**](https://webpack.js.org/configuration/dev-server/)

I don't understand where the **main.js** file comes from and the **server** module is declared in it.

### Actual Behavior

```js
//console
PS E:\Downloads\asd> npx webpack server
[webpack-cli] Compilation finished
assets by status 0 bytes [cached] 1 asset

ERROR in main
Module not found: Error: Can't resolve 'server' in 'E:\Downloads\asd'

webpack 5.6.0 compiled with 1 error in 575 ms
```

### For Bugs; How can we reproduce the behavior?

**npx webpack server**

**Comment by alexander-akait** [comment]
first warning for spam

**Comment by Devinora** [comment]
> first warning for spam

wrote that the index.js file is empty. nowhere is a module declaration used.

**Comment by 79059038** [comment]
how to solve this problem？

**Comment by Devinora** [comment]
> how to solve this problem？

https://github.com/webpack/webpack-dev-server/issues/2865#issuecomment-734350749
