### ISSUE TITLE
Build fails with "Maximum call stack size exceeded" when "concatenateModules" is enabled

### ISSUE THREAD

**Issue by kuworking** [webpack/webpack#12066]
# Bug report

**What is the current behavior?**

In webpack optimization, with `concatenateModules: true` compilation fails with a `Maximum call stack size exceeded` error

If disabled, it builds as expected

**If the current behavior is a bug, please provide the steps to reproduce.**

The repo https://github.com/kuworking/webpack_concatenateModules_issue uses `11ty`, and reproduces the problem in my computer

Please note than under Windows environment it does NOT work due to (presumably) a bug in 11ty

In my case (W10 user) I can run it successfully under WSL
 
```
git clone <<repo>>
yarn
npm run build
>>> edit `concatenateModules: false`
npm run build
```

**What is the expected behavior?**

With `concatenateModules` disabled the repo builds ok, but not when it is enabled

Perhaps there is a legitimate reason why the build fails (?)

**Other relevant information:**
webpack version:  5.4.0
Node.js version: v14.15.0
Operating System: W10 (WSL Ubuntu 20.04)
Additional tools:

**Comment by vankop** [comment]
`webpack-remove-empty-js-chunks-plugin` is unneeded with `webpack@5`, looks like without it build works.

**Comment by kuworking** [comment]
Just to note that without the plugin activated (`"webpack-remove-empty-scripts": "0.6.3"`) I do see empty js files, but this is likely an issue with webpack then

**Comment by vankop** [comment]
please create a separate issue
