### ISSUE TITLE
Build fails with "Maximum call stack size exceeded" when "concatenateModules" and "webpack-remove-empty-scripts" is enabled

### ISSUE THREAD

**Issue by kuworking** [webpack/webpack#12068]
!-- Please don't delete this template because we'll close your issue -->

# Bug report

**What is the current behavior?**

In webpack optimization, with `concatenateModules: true` compilation fails with a `Maximum call stack size exceeded` error when one uses `webpack-remove-empty-scripts`

If any of the two is disabled, it builds as expected

As noted in the https://github.com/webdiscus/webpack-remove-empty-scripts plugin page

> The plugin support only Webpack 5 using new ChunkGraph and ModuleGraph APIs. For Webpack 4 use original plugin.

Maybe in webpack one would expect this plugin to be unnecessary with `optimization.removeEmptyChunks` https://webpack.js.org/configuration/optimization/#optimizationremoveemptychunks

Or maybe this refers to "chunks" but not entire files

Anyway, in my setup empty files are present if I don't use `webpack-remove-empty-scripts`, something I happily sacrifice in order to have `concatenateModules: true` (but still, shouldn't happen I assume)

**If the current behavior is a bug, please provide the steps to reproduce.**

The repo https://github.com/kuworking/webpack_concatenateModules_issue uses `11ty`, and reproduces the problem in my computer

Please note than under Windows environment it does NOT work due to (presumably) a bug in 11ty

In my case (W10 user) I can run it successfully under WSL
 
```
git clone <<repo>>
yarn
npm run build
>>> edit `concatenateModules: false`
>>> or comment the part `new RemoveEmptyScriptsPlugin(),`
npm run build
```

**What is the expected behavior?**

With `concatenateModules` OR `new RemoveEmptyScriptsPlugin()` disabled the repo builds ok, but not when it is enabled

**Other relevant information:**
webpack version:  5.4.0
Node.js version: v14.15.0
Operating System: W10 (WSL Ubuntu 20.04)
Additional tools:

**Comment by alexander-akait** [comment]
Please open an issue in webpack-remove-empty-js-chunks-plugin (no compatibility with webpack@5), sorry we can't help here

**Comment by webdiscus** [comment]
@kuworking The issue `Maximum call stack size exceeded` I have fixed.
Please update to new version of package 0.6.4.
https://www.npmjs.com/package/webpack-remove-empty-scripts/v/0.6.4

P.S. can you please test this fix by your react project and tell me a result.
The issue site: https://github.com/webdiscus/webpack-remove-empty-scripts/issues/1
