### ISSUE TITLE
How can i use summernote with webpack

### ISSUE THREAD

**Issue by cswleocsw** [webpack/webpack#1207]
I want to use summernote as my simple online html editor. But when i use webpack to buildle it and webpack  alway report somw warring & error, although summernote support AMD!

`CodeMirror`  causes those error and warring. But I do not know how to adjust webpck config for it!

**Comment by mathieumg** [comment]
See https://github.com/summernote/summernote/issues/1171

**Comment by cswleocsw** [comment]
Thanks!

**Comment by itsazzad** [comment]
@cswleocsw what was the solution? please

**Comment by cswleocsw** [comment]
webpack.config.js

```
plugins: [
        // summernote: require 
        new webpack.DefinePlugin({
            'require.specified': 'require.resolve'
        })
    ],

    resolve: {
        alias: {
            // summernote: codemirror 
            'CodeMirror': 'codemirror',
        }
    },
```

**Comment by hackerwins** [comment]
I hope below link is helpful.
https://github.com/hackerwins/summernote-webpack-example

**Comment by mnpenner** [comment]
I finally got it to compile after adding these loaders,

```js
{
    test: /\.(jpe?g|png|gif|svg)$/i,
    loaders: [
        'url?limit=2048&name=[name]-[sha1:hash:hex:10].[ext]', // Inline images if they're less than 2 KiB
        //'image-webpack?bypassOnDebug&optimizationLevel=7&interlaced=false'
    ]
},
{
    test: /\.(eot|svg|ttf|woff2?)(\?\w+)?$/i,
    loaders: [
        'file?name=[name]-[sha1:hash:hex:10].[ext]',
    ]
},
```

And installing `codemirror` explicitly. However, I still get a JS error:

/quote TypeError: $node.attr(...).tooltip is not a function

I don't know what jQuery library is supposed to add `tooltip` but clearly I don't have it.
