### ISSUE TITLE
Webpack fails to properly pack a wasm-bindgen helper function

### ISSUE THREAD

**Issue by Systool** [webpack/webpack#12078]
# Bug report
**What is the current behavior?**
If I try to import a wasm module that I generated with wasm-pack, Webpack fails to pack helper functions like `__wbindgen_string_new`

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Clone https://github.com/Systool/webpack-error-example
2. Follow https://rustwasm.github.io/wasm-pack/installer/
3. `yarn install`
4. `yarn dev`

**What is the expected behavior?**
Webpack should properly handle functions like `__wbindgen_string_new`, all of which can found in `/module/pkg/index_bg.js` after wasm building

**Other relevant information:**
webpack version:  5.9.0
Node.js version: 15.3.0
Operating System: Arch Linux
Additional tools: cargo, wasm-pack, yarn

**Comment by sokra** [comment]
Have you tried `experiements.syncWebAssembly: true` instead of `experiements.asyncWebAssembly: true`?

**Comment by Systool** [comment]
It didn't seem to load with Webpack 4.44.1 (dependency of next) at first, but after trying again it seems to work both with the "old" version and with `syncWebAssembly: true`, however in another project I get `__webpack_require__.w is undefined` with Webpack 4.44.1, while it works under Webpack 5.9.0 and `syncWebAssembly: true`. Sorry for wasting your time

**Comment by sokra** [comment]
As far I remember wasm-bindgen is using some circular dependencies between wasm and js part, which are illegal in the new spec. So you are stuck with the old spec for now. But I think they are aware of that and this will probably be fixed eventually.
