### ISSUE TITLE
AMD module built with `webpack serve` returns `undefined` (Webpack 5 only)

### ISSUE THREAD

**Issue by yvele** [webpack/webpack#12085]
# Bug report

**What is the current behavior?**

When using `webpack serve` the defaut AMD module returns `undefined`.

**If the current behavior is a bug, please provide the steps to reproduce.**

Webpack config is very simple:

```js
const path = require("path");

module.exports = {
  entry : path.join(__dirname, "src/index.js"),
  output : {
    path : path.join(__dirname, "dist"),
    filename : "main.js",
    libraryTarget : "amd",
    libraryExport : "default"
  }
};
```

And `main.js` also:

```js
export default {
  foo : "bar"
};
```

Clone https://github.com/yvele/webpack-5-amd-devserver

Then

```sh
npm install
npm run build
npm run start
```

The AMD module built with `webpack` works as expected.
The AMD module built with `webpack serve` return `undefined`.

![image](https://user-images.githubusercontent.com/4225430/100622602-56e94e80-3321-11eb-9450-a4c7865a3f37.png)

I also tried to set `inline` to false and deactivate hot.. But still lots of code if injected and the AMD module returns `undefined` with `webpack serve`.

Note that I don't have the bug with Webpack 4.

**What is the expected behavior?**

`webpack serve` should build a valid AMD module.

**Other relevant information:**
webpack version:  5.8.0
webpack-cli version:  4.2.0
webpack-dev-server: 3.11.0
Node.js version: 12.19.0
Operating System: macOS 10.15.7
Additional tools:

```
  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Memory: 1.84 GB / 16.00 GB
  Binaries:
    Node: 12.19.0 - ~/.nvm/versions/node/v12.19.0/bin/node
    npm: 6.14.8 - ~/.nvm/versions/node/v12.19.0/bin/npm
  Browsers:
    Chrome: 87.0.4280.67
    Firefox: 81.0.2
    Safari: 14.0
```

**Comment by alexander-akait** [comment]
Fixed, please try `webpack-dev-server@4`

**Comment by yvele** [comment]
Thanks!

But hum.. is there any workaround or any related `webpack-dev-server` issue where I can maybe find a workaround by myself?

The problem is that `webpack-dev-server@4-beta.0` is so breaking.. and lacks of documentation.. It's nearly impossible to switch to  `webpack-dev-server@4-beta.0` 🤔

**Comment by alexander-akait** [comment]
No workarounds, only migrate on `webpack-dev-server@4-beta.0` (what is so breaking?)

**Comment by yvele** [comment]
Ok everything works fine with `webpack-dev-server@4-beta.0`! 👌 

(lots of options has changed and there is no documentation.. but I figured out, thanks!)
