### ISSUE TITLE
question about context

### ISSUE THREAD

**Issue by darul75** [webpack/webpack#1208]
hi @sokra ,

you know it already but I say it again, your solution is amazing.

but difficult to take in hand I mean in your code :) so much dense now.

can you give me some detailsspecialy how you enhance default require function and by instance give to me code files for require.context(directory, useSubdirectories = false, regExp = /^\.\//) function.

from
http://webpack.github.io/docs/context.html

I would like take a look in it.

thx

**Comment by sokra** [comment]
Start here: https://github.com/webpack/webpack/blob/master/lib/dependencies/RequireContextPlugin.jshttps://github.com/webpack/webpack/blob/master/lib/dependencies/RequireContextPlugin.js

**Comment by darul75** [comment]
thx ok, I will try debug it first

**Comment by bySabi** [comment]
Here trying to replace:
```tests.webpack.js
const context = require.context('./test', true, /^.+\.(js|jsx)+$/g);
context.keys().forEach(context);
```

with

```webpack.conf.js
var RequireContextPlugin = require('webpack/lib/dependencies/RequireContextPlugin');
...
  plugins: [
    //new RequireContextPlugin(['./test'], [/^.+\.(js|jsx)+$/g])
    new RequireContextPlugin(['./test'], ['.js'])
 ]
```

Is this suitable?
