### ISSUE TITLE
[webpack v5] libraryTarget=var doesn't expose the entry module

### ISSUE THREAD

**Issue by LexSwed** [webpack/webpack#12082]
After upgrading to `webpack@5` builds no longer expose modules when `output.libraryTarget = 'var'`, for some reason global variable always points to an empty object.

So with config set as:
```js
 // config
  output: {
    library: {
      name: 'app2',
      type: 'var',
    },
  }
```

I expect the build to expose entry point module via `window.app2` when injected on the page. Instead, the value is an empty object `{}`

Reproduced: https://github.com/LexSwed/webpack-5-issue

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

**Comment by alexander-akait** [comment]
Please fix it and I will reopen the issue
