### ISSUE TITLE
`require.context()` duplicates file names in `context.keys()` list

### ISSUE THREAD

**Issue by uditalias** [webpack/webpack#12087]
# Bug report

**What is the current behavior?**

When using `require.context(__dirname, true, /\.mdl\.ts$/)` the context `keys()` are duplicated.
I tested the same code with webpack@4.44.2 and it works as expected (see expected behavior).

**If the current behavior is a bug, please provide the steps to reproduce.**

Using webpack@5.5.1, I created 3 files in my `./src` folder.

1. index.ts
2. bootstrap.mdl.ts
3. api.mdl.ts

Inside `index.ts` I'm using `require.context()` as follow:

```typescript
const context = require.context(__dirname, true, /\.mdl\.ts$/);
```

When observing the `context.keys()` I get the following list of files:

```typescript
["./bootstrap.mdl.ts", "./api.mdl.ts", "bootstrap.mdl.ts", "api.mdl.ts"]
```

**What is the expected behavior?**

The `context.keys()` should return the following list with no file duplications:

```typescript
["./bootstrap.mdl.ts", "./api.mdl.ts"]
```

**Other relevant information:**
webpack version:  5.5.1
Node.js version: 14.13.0
Operating System: macOS 11.0.1 (20B29)
Additional tools:

**Comment by akgupta0777** [comment]
@uditalias can you tell me the steps to reproduce the bug with javascript.

**Comment by uditalias** [comment]
Hey @akgupta0777 
I created this repo to reproduce the issue with JavaScript
https://github.com/uditalias/webpack-context-dup-keys

Thanks

**Comment by sokra** [comment]
Your `resolve.modules` config allows you to write `require("boostrap.mdl.ts")`. That's reflected by `require.context`. `keys()` lists all possible requests that you can write. If you only want requests with `./` add that to the regexp.

**Comment by uditalias** [comment]
Thank you @sokra 
What you've suggested is not consistent with webpack 4
Is it changed in purpose?

**Comment by alexander-akait** [comment]
@uditalias Yep, it is breaking change
