### ISSUE TITLE
Allow dynamic imports to be GC'd

### ISSUE THREAD

**Issue by jnields** [webpack/webpack#12089]
## Feature request

One of the main motivations for code-splitting is to limit the amount of JS that a user needs to use in order to render an app.

In the context of a SPA, this means downloading only the code necessary to render the current page, and to then dynamically import additional chunks to render other pages to which the user navigates.

Currently, references to resolved dynamic imports seem to be preserved in a global variable, `webpackChunkapp`, preventing them from being GC'd.

**What is the expected behavior?**
When dynamically importing a module, do not save references to it in any global variables. Alternatively, if this is not possible, you could allow a method to "unregister" a module.

**What is motivation or use case for adding/changing the behavior?**
To allow the user's device to GC unused imports, releasing occupied JS heap space on large, code-split apps.

Properly configured, hashed filenames and cache-control directives for assets can prevent unnecessarily re-downloading assets, but still allow devices to GC dynamic imports that aren't in use.

**How should this be implemented in your opinion?**
Global references to dynamically imported modules should be destroyed once the import is complete and subscribers to the success / error events have been called.

If this is a breaking change or off-spec for dynamic imports (I haven't looked into the spec in detail), I imagine this being an opt-in feature could potentially work.

**Are you willing to work on this yourself?**
This feels like a very core change that I currently lack the context to complete, but if required I might be able.

**Comment by rjgotten** [comment]
> Global references to dynamically imported modules should be destroyed once the import is complete

Hard disagree. That violates the semantics of both a CJS require _and_ a dynamic ES import, which both have import-once semantics. I.e. no matter when the module is requested, it will only be actually loaded _once_ and all resolves get handed the same module instance.
