### ISSUE TITLE
Webpack allows unhandled promise rejection to fail silently

### ISSUE THREAD

**Issue by ebbishop** [webpack/webpack#12086]
# Bug report

**What is the current behavior?**
We recently had a bad build deploy successfully and found that an outdated plugin was causing an unhandled promise rejection that didn't cause the build to fail.

**If the current behavior is a bug, please provide the steps to reproduce.**

This repo contains a minimal package list & webpack config to reproduce the problem:

https://github.com/ebbishop/webpack-silent-fail

The `webpack.config.js` in this repo forces webpack to fail. While fixing/updating/removing the offending plugin is important, webpack exit the process with a non-zero code.

**What is the expected behavior?**

* When webpack runs into an `UnhandledPromiseRejectionWarning`, it should exit the node process with a non-zero code
* This will allow automated ci/cd scripts to fail once the webpack process fails.

**Other relevant information:**
webpack version:  5.9.0
Node.js version: 10.16.3
Operating System: macOS 10.14.5

**Comment by alexander-akait** [comment]
Please use `tapPromise`, for `tapAsync` you need to run `cb`, your code is not executed

**Comment by ebbishop** [comment]
@alexander-akait The change you suggest does not solve the problem I'm reporting. I know the plugin causes the build to fail - that's the point. What I and others need is a way to have webpack exit the node process with a non-zero when there's an unhandled promise rejection. 

This is problem that sometimes comes up in automated deployments: a plugin is updated and suddenly breaks the webpack build, but the node process doesn't exit.  So then, our builds continue on without the build files we expect webpack tor produce.

The expected result is not that webpack build files when a plugin is broken, but that it fail in such a way that the node process exits.

**Comment by alexander-akait** [comment]
You just do not call `cb`. what is you expected?

**Comment by ebbishop** [comment]
The `FailingPlugin` is meant to simulate any possible plugin with an unhandled promise rejection.

Expected: when there's an unhandled promise rejection, webpack exits the node process with a non-zero exit code.

Why: this will allow us to kill a deployment if a webpack build is broken.

**Comment by ebbishop** [comment]
@alexander-akait 

The logs for `npm run build` in my test repo are this:

```
npm WARN prepare removing existing node_modules/ before installation

> node-sass@5.0.0 install /webpack-silent-fail/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v5.0.0/darwin-x64-72_binding.node
Download complete ░⸩ ⠋ :
Binary saved to /webpack-silent-fail/node_modules/node-sass/vendor/darwin-x64-72/binding.node
Caching binary to /.npm/_cacache/node-sass/5.0.0/darwin-x64-72_binding.node

> node-sass@5.0.0 postinstall /webpack-silent-fail/node_modules/node-sass
> node scripts/build.js

Binary found at /webpack-silent-fail/node_modules/node-sass/vendor/darwin-x64-72/binding.node
Testing binary
Binary is fine
added 467 packages in 5.692s

> webpack-test@1.0.0 build /webpack-silent-fail
> webpack

rejecting promise
(node:66709) UnhandledPromiseRejectionWarning: undefined
(node:66709) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:66709) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

> webpack-test@1.0.0 postbuild /webpack-silent-fail
> npm run clean


> webpack-test@1.0.0 clean /webpack-silent-fail
> rm -f css/*.js
```

What I'd like to see is something more like this:
```
1 ERROR in child compilations
webpack 5.9.0 compiled with 1 error in 493 ms
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webpack-test@1.0.0 build: `webpack`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the webpack-test@1.0.0 build script.
```

**Comment by alexander-akait** [comment]
Sorry, handling `Unhandled promise rejection` on your code side, you can add to this any own logic

**Comment by ebbishop** [comment]
@alexander-akait What happens when we don't control the plugin? That's the use-case I'm most concerned about. Currently, **webpack fails to build**, but lets the node process continue. That seems like a bug to me.

**Comment by alexander-akait** [comment]
Please read again:
```
(node:66709) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
so wepback doesn't exit with non zero exit code

**Comment by technocookie** [comment]
@ebbishop  did you ever figure out this issue? For me this most certainly should qualify as a bug. Webpack needs to support a --unhandled-rejections flag or an uncaught error should cause the node process to fail.

**Comment by alexander-akait** [comment]
@technocookie webpack should not generate `Unhandled promise rejections are deprecated`, maybe problem in not official loaders/plugins, can you trace it?
