### ISSUE TITLE
Support customizing infrastructure logging

### ISSUE THREAD

**Issue by akphi** [webpack/webpack#12091]
## Feature request

Hi in Webpack 5, logging API has been reworked and logging has been divided into `infrastructureLogging` and `stats.logging`. The display of the latter can be customized by setting `stats.logging=false` and create a plugin to print from the `stats` object; however, the former, as mentioned [here](https://github.com/webpack/webpack.js.org/issues/3205) cannot be customized as this info is not exposed. Can you confirm this is still the case? If so, would it be possible if we can customize the formatting of these infra log messages? 

**What is the expected behavior?**
Webpack should expose these log event somehow so downstream we can have a plugin to print it.

**What is the motivation or use case for adding/changing the behavior?**
I'm using `webpack-dev-server` and I don't quite like the new look that the logging messages show in the terminal for example: `<i>`, and I also like to customize the coloring using `chalk`
```
<i> [webpack-dev-server] Project is running at http://127.0.0.1:3000/
<i> [webpack-dev-server] webpack output is served from /
```
so I would like to be able to customize this part, without the need to create my own dev server like what `create-react-app` does

**How should this be implemented in your opinion?**
I'm not too sure of the inner working of this, but I believe we can't really achieve the same as what we did with the `stats` object as the infrastructure log here is called and expected to print immediately. So we might need to allow specifying a function that will do the formatting on the spot.

I have narrowed down to 2 places: `createConsoleLogger.js` and `nodeConsole.js`. For the first one, we can pass in a function that takes `name` and `arg` and output a string, here if the user wants to customize, they can use `chalk`. The latter worries me a bit more, the file seems pretty self-contained and hard to poke in to customize, so maybe it's just better to let people create their own console they want, or have an option like `disableConsoleFormatting` to not print the `prefix <i> <e>` and to not print the ANSI escape sequence (note here we want to keep other things like indentation though)

In shorts, we would need at least 2 options for `infrastructureLogging`:
1. `formatter: (type: LogType, name: string, arg: any[]) => any[]` a function to customize the log content.
2. `disableConsoleFormatting: boolean` a flag indicating if we're to disable coloring and prefix for the default node console

**Are you willing to work on this yourself?**
yes, I would need some guidance and your advice on how to architect this though, but if it is what I imagine on the previous question, I don't think it's a big change.

**Comment by alexander-akait** [comment]
You can create own plugin for this - https://github.com/webpack/webpack/blob/master/lib/Compilation.js#L997 and https://github.com/webpack/webpack/blob/master/lib/Compiler.js#L288, sorry we don't want to change current output without reasons, it is very subjective - like it or not, if you have any suggestions for improvement, let them know, feel free to feedback

**Comment by alexander-akait** [comment]
> disableConsoleFormatting: boolean a flag indicating if we're to disable coloring and prefix for the default node console

**Comment by alexander-akait** [comment]
``

**Comment by akphi** [comment]
@alexander-akait Thank you, it makes so much sense now that I can tap to `compiler.hooks.infrastructureLog`

**Comment by boxfoot** [comment]
@akphi thanks for raising this.  Did you end up building an alternate logging plugin?  Would you be willing to share or collaborate on your work?

**Comment by akphi** [comment]
@boxfoot hey I haven't had time to work on this. I plan to do it when we start using `webpack-dev-server@4`
