### ISSUE TITLE
Code splitting and chunkhash problem hasn't been totally resolved.

### ISSUE THREAD

**Issue by fenivana** [webpack/webpack#1209]
The issue #1181 hasn't been totally resolved. When a.js require b.js, modifying b.js won't change the chunkhash of app.js.

**Comment by redonkulus** [comment]
@fenivana can you provide a simple example or is it the same one from #1181?

**Comment by fenivana** [comment]
Yes, the same. I've updated the git.
https://github.com/fenivana/webpack-chunkhash-issue

**Comment by fenivana** [comment]
Another related issue is that compile.watch() doesn't re-compile the entry js if split code changed.

**Comment by oliviertassinari** [comment]
I confirm, I'm using 1.10.1. If a depend on b and if the content of b change. Then the chunkHast of b change but no the chunkHash of a.

**Comment by p0wl** [comment]
does this only occur when using `require.ensure`?

**Comment by sokra** [comment]
You are correct. I'll try again... https://github.com/webpack/webpack/commit/ea7fd67ec1673116607c56b39b8ab3d5c2d24f96

:cry:

**Comment by bebraw** [comment]
@fenivana Can you try now? There was a related commit that might have fixed this.

**Comment by fenivana** [comment]
@bebraw I confirmed the issue has been fixed. Thanks!
