### ISSUE TITLE
Dependency resolution of 3rd-party imports fails

### ISSUE THREAD

**Issue by johnrichardrinehart** [webpack/webpack#12093]
# Bug report

**What is the current behavior?**

`yarn run build` in my [MWE (note the commit hash in the URL](https://github.com/johnrichardrinehart/wouter/commit/7d6938c83a311f3e35db55f271e4724822f5e6dc) fails with a bunch of resolver errors.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. `git clone https://github.com/johnrichardrinehart/wouter`
1. `git checkout 7d6938c83a311f3e35db55f271e4724822f5e6dc`
1. `yarn run build`

**What is the expected behavior?**

`yarn run build` should bundle all my assets and stick them in `./dist/`.

**Other relevant information:**
webpack version:  `5.9.0`
Node.js version: `node v15.3.0`
Operating System:  `Ubuntu 20.10`
Additional tools: `yarn v2.40.0` (`berry`, so `yarn set version berry`)

**Comment by alexander-akait** [comment]
> If the current behavior is a bug, please provide the steps to reproduce.

Please do not ignore this

**Comment by johnrichardrinehart** [comment]
@alexander-akait Didn't mean to ignore. I've added clear instructions, now.

**Comment by alexander-akait** [comment]
Don't have problem

**Comment by johnrichardrinehart** [comment]
I just checked. If you check out that commit then you'll have errors. See below:

```
➜  wouter git:(7d6938c) ✗ yarn run build        
(node:60440) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
	Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
	Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
(Use `node --trace-deprecation ...` to show where the warning was created)
[webpack-cli] Compilation finished
asset bundle.js 108 KiB [compared for emit] (name: index)
asset ./index.html 211 bytes [compared for emit]
runtime modules 668 bytes 3 modules
modules by path ./.yarn/ 81.8 KiB
  modules by path ./.yarn/$$virtual/wouter-virtual-21dacc859c/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/*.js 9.13 KiB
    ./.yarn/$$virtual/wouter-virtual-21dacc859c/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 4.33 KiB [built] [code generated]
    ./.yarn/$$virtual/wouter-virtual-21dacc859c/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/use-location.js 2.6 KiB [built] [code generated]
    ./.yarn/$$virtual/wouter-virtual-21dacc859c/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/react-deps.js 176 bytes [built] [code generated]
    ./.yarn/$$virtual/wouter-virtual-21dacc859c/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/matcher.js 2.03 KiB [built] [code generated]
  modules by path ./.yarn/cache/ 72.7 KiB
    ./.yarn/cache/react-npm-17.0.1-98658812fc-a76d86ec97.zip/node_modules/react/index.js 190 bytes [built] [code generated]
    ./.yarn/cache/react-npm-17.0.1-98658812fc-a76d86ec97.zip/node_modules/react/cjs/react.development.js 70.5 KiB [built] [code generated]
    ./.yarn/cache/object-assign-npm-4.1.1-1004ad6dec-66cf021898.zip/node_modules/object-assign/index.js 2.06 KiB [built] [code generated]
./src/index.js 361 bytes [built] [code generated]

ERROR in ./.yarn/$$virtual/wouter-virtual-21dacc859c/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 23:18-31
export 'createContext' (imported as 'createContext') was not found in './react-deps.js' (possible exports: )
 @ ./src/index.js 4:0-31 7:42-47

ERROR in ./.yarn/$$virtual/wouter-virtual-21dacc859c/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 32:20-30
export 'useContext' (imported as 'useContext') was not found in './react-deps.js' (possible exports: )
 @ ./src/index.js 4:0-31 7:42-47

ERROR in ./.yarn/$$virtual/wouter-virtual-21dacc859c/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 51:17-23
export 'useRef' (imported as 'useRef') was not found in './react-deps.js' (possible exports: )
 @ ./src/index.js 4:0-31 7:42-47

ERROR in ./.yarn/$$virtual/wouter-virtual-21dacc859c/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 63:14-20
export 'useRef' (imported as 'useRef') was not found in './react-deps.js' (possible exports: )
 @ ./src/index.js 4:0-31 7:42-47

ERROR in ./.yarn/$$virtual/wouter-virtual-21dacc859c/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 70:9-10
export 'createElement' (imported as 'h') was not found in './react-deps.js' (possible exports: )
 @ ./src/index.js 4:0-31 7:42-47

ERROR in ./.yarn/$$virtual/wouter-virtual-21dacc859c/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 85:24-25
export 'createElement' (imported as 'h') was not found in './react-deps.js' (possible exports: )
 @ ./src/index.js 4:0-31 7:42-47

ERROR in ./.yarn/$$virtual/wouter-virtual-21dacc859c/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 97:22-33
export 'useCallback' (imported as 'useCallback') was not found in './react-deps.js' (possible exports: )
 @ ./src/index.js 4:0-31 7:42-47

ERROR in ./.yarn/$$virtual/wouter-virtual-21dacc859c/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 121:14-28
export 'isValidElement' (imported as 'isValidElement') was not found in './react-deps.js' (possible exports: )
 @ ./src/index.js 4:0-31 7:42-47

ERROR in ./.yarn/$$virtual/wouter-virtual-21dacc859c/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 121:52-53
export 'createElement' (imported as 'h') was not found in './react-deps.js' (possible exports: )
 @ ./src/index.js 4:0-31 7:42-47

ERROR in ./.yarn/$$virtual/wouter-virtual-21dacc859c/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 123:9-21
export 'cloneElement' (imported as 'cloneElement') was not found in './react-deps.js' (possible exports: )
 @ ./src/index.js 4:0-31 7:42-47

ERROR in ./.yarn/$$virtual/wouter-virtual-21dacc859c/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 136:6-20
export 'isValidElement' (imported as 'isValidElement') was not found in './react-deps.js' (possible exports: )
 @ ./src/index.js 4:0-31 7:42-47

ERROR in ./.yarn/$$virtual/wouter-virtual-21dacc859c/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 145:13-25
export 'cloneElement' (imported as 'cloneElement') was not found in './react-deps.js' (possible exports: )
 @ ./src/index.js 4:0-31 7:42-47

ERROR in ./.yarn/$$virtual/wouter-virtual-21dacc859c/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 155:2-17
export 'useLayoutEffect' (imported as 'useLayoutEffect') was not found in './react-deps.js' (possible exports: )
 @ ./src/index.js 4:0-31 7:42-47

ERROR in ./.yarn/$$virtual/wouter-virtual-21dacc859c/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/react-deps.js 1:0-12:15
Module not found: Error: Can't resolve 'react' in '/home/john/wouter/.yarn/$$virtual/wouter-virtual-21dacc859c/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter'
Did you mean 'index.js'?
BREAKING CHANGE: The request 'react' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '*.mjs' file or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
 @ ./.yarn/$$virtual/wouter-virtual-21dacc859c/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 4:0-13:25 23:18-31 32:20-30 51:17-23 63:14-20 70:9-10 85:24-25 97:22-33 121:14-28 121:52-53 123:9-21 136:6-20 145:13-25 155:2-17
 @ ./src/index.js 4:0-31 7:42-47

ERROR in ./.yarn/$$virtual/wouter-virtual-21dacc859c/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/use-location.js 12:25-33
export 'useState' (imported as 'useState') was not found in './react-deps.js' (possible exports: )
 @ ./.yarn/$$virtual/wouter-virtual-21dacc859c/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 1:0-45 26:9-21
 @ ./src/index.js 4:0-31 7:42-47

ERROR in ./.yarn/$$virtual/wouter-virtual-21dacc859c/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/use-location.js 13:19-25
export 'useRef' (imported as 'useRef') was not found in './react-deps.js' (possible exports: )
 @ ./.yarn/$$virtual/wouter-virtual-21dacc859c/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 1:0-45 26:9-21
 @ ./src/index.js 4:0-31 7:42-47

ERROR in ./.yarn/$$virtual/wouter-virtual-21dacc859c/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/use-location.js 15:2-11
export 'useEffect' (imported as 'useEffect') was not found in './react-deps.js' (possible exports: )
 @ ./.yarn/$$virtual/wouter-virtual-21dacc859c/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 1:0-45 26:9-21
 @ ./src/index.js 4:0-31 7:42-47

ERROR in ./.yarn/$$virtual/wouter-virtual-21dacc859c/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/use-location.js 40:19-30
export 'useCallback' (imported as 'useCallback') was not found in './react-deps.js' (possible exports: )
 @ ./.yarn/$$virtual/wouter-virtual-21dacc859c/0/cache/wouter-npm-2.6.0-237130b851-d80392b074.zip/node_modules/wouter/index.js 1:0-45 26:9-21
 @ ./src/index.js 4:0-31 7:42-47

webpack 5.9.0 compiled with 18 errors in 675 ms
```

**Comment by alexander-akait** [comment]
```
BREAKING CHANGE: The request 'react' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '*.mjs' file or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
```

**Comment by alexander-akait** [comment]
Do you read the message?

**Comment by johnrichardrinehart** [comment]
Yeah, I read the message.

**Comment by alexander-akait** [comment]
Try to run this package without webpack, in browsers or Node.js (if supported), and you will see the same problem

**Comment by johnrichardrinehart** [comment]
The author of `wouter` said that this seems to be a `webpack` resolution issue.

https://github.com/molefrog/wouter/issues/150#issuecomment-735925196

**Comment by johnrichardrinehart** [comment]
@alexander-akait Is it the author of `wouter` or the author of `react` that needs to fix their package?

**Comment by alexander-akait** [comment]
https://github.com/molefrog/wouter/blob/master/package.json#L20, but code use `import something from './package/file';` without `extension`, it will not work in browser or Node.js and webpack have the same behavior to catch problems with libraries, you can disable this behavior https://github.com/webpack/webpack/issues/11467#issuecomment-691873586, but I don't recommend to do it, please report the problem in library repo

**Comment by johnrichardrinehart** [comment]
@alexander-akait All his local imports have extensions. His non-local imports (dependency imports) don't have extensions, per [ESM specification](https://github.com/webpack/webpack/issues/11467#issuecomment-691702706).

**Comment by alexander-akait** [comment]
Try to build it without `yarn` PnP, `wouter` is not PnP compatibility (no `peerDependenciesMeta`, yarn can't understand what `wouter` need to use `react` like peer dep, so webpack can't resolve)

**Comment by johnrichardrinehart** [comment]
Are you saying that `wouter` needs a `peerDependenciesMeta` field in `package.json` in order to be PnP compatible?

**Comment by alexander-akait** [comment]
Yep, for example `webpack-dev-server` can be run via CLI and Node.js API, for running it via CLI you need to install `webpack-cli`, so we have https://github.com/webpack/webpack-dev-server/blob/master/package.json#L115 for PnP support, otherwise yarn don't know relationship between webpack-cli and webpack-dev-server and `require`/`import` will not work

**Comment by johnrichardrinehart** [comment]
Ahhh, okay, let me fork `molefrog/wouter` and try to modify that `package.json`. If that works then I'll notify `wouter`'s author that I'd like to implement a change. Thanks @alexander-akait !

**Comment by johnrichardrinehart** [comment]
I've added the [appropriate field](https://github.com/johnrichardrinehart/wouter/blob/fix/peerDepedenciesMeta/package.json#L57-L61) to [my fork](johnrichardrinehart/wouter). It's still broken.

To reproduce:

1. `git clone https://github.com/johnrichardrinehart/wouter_issue`
1. `git checkout wouter_still_broken`
1. `yarn run build`

You can see in the `package.json` and the `yarn.lock` that I'm using my fork at the [right commit](https://github.com/johnrichardrinehart/wouter/tree/fix/peerDepedenciesMeta).

**Comment by alexander-akait** [comment]
Still something wrong in deps, we are using yarn PnP resolver (https://github.com/webpack/enhanced-resolve/blob/master/lib/PnpPlugin.js#L23), if it is not working, it means PnP can't resolve it, nothing to do here in webpack

**Comment by johnrichardrinehart** [comment]
I managed to fix the compilation, but I had to modify my resolution settings for `webpack`. I had to remove `exclude: /node_modules/` and I had to add `resolve: {fullySpecified: false}`.

So, it works if I change something in `webpack`. It breaks if I don't. It seems like the issue is with `webpack`. If `wouter` is doing something wrong then can you please identify exactly what they are doing wrong?

**Comment by alexander-akait** [comment]
> It seems like the issue is with webpack.

No problems with webpack here, yarn can't resolve it, run it in Node.js and you will get the same problem

**src/index.js**

```
//import ReactDOM from "react-dom"; // Needed to attach to #root`
import React from "react"; // needed for rendering <App />, which is sugar for React.createElement
import {Route} from 'wouter';

function App() {
  return 'test';
}
```

```
$ node src/index.js
```

output:

```
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'react' imported from /home/evilebottnawi/IdeaProjects/wouter/src/index.js
    at packageResolve (internal/modules/esm/resolve.js:650:9)
    at moduleResolve (internal/modules/esm/resolve.js:691:18)
    at Loader.defaultResolve [as _resolve] (internal/modules/esm/resolve.js:784:11)
    at Loader.resolve (internal/modules/esm/loader.js:100:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:246:28)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:47:40)
    at link (internal/modules/esm/module_job.js:46:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
```

**Comment by alexander-akait** [comment]
Unfortunately, I have no time to investigate deeply, you can ask it on `stackoverflow` or may even in `yarn` repo

**Comment by johnrichardrinehart** [comment]
Fair enough. Let's close for now.

**Comment by alexander-akait** [comment]
@johnrichardrinehart anyway feel free to feedback or post the solution, it may help other developers in future, if you get stuck with this for a long time, you can ping me again, maybe I will have time and help you

**Comment by johnrichardrinehart** [comment]
@alexander-akait I think there's an issue with the test that you ran [here](https://github.com/webpack/webpack/issues/12093#issuecomment-736615573). `node` isn't going to find it because `yarn` puts all the dependencies in a compressed `yarn/cache/*.zip` instead of `node_modules. `node` looks in `node_modules` so I wouldn't expect your test to work. `webpack` is designed to resolve using `yarn` (like you said). `node` isn't.

How does your test confirm that the issue isn't with `webpack`?

**Comment by alexander-akait** [comment]
yarn is patching node resolution algorithm

**Comment by johnrichardrinehart** [comment]
Apprently PnP resolution isn't being used, so it's not Yarn. Yarn sent me back to you:

https://github.com/yarnpkg/berry/issues/2199#issuecomment-736681587

**Comment by arcanis** [comment]
One extra tidbit:

> No problems with webpack here, yarn can't resolve it, run it in Node.js and you will get the same problem

The Node resolver doesn't support ESM yet (tracked [here](https://github.com/yarnpkg/berry/issues/638)), so the test you made crashes in Node because of that, but in the case of Webpack it shouldn't matter because you only use [requireToUnqualified](https://github.com/webpack/enhanced-resolve/blob/master/lib/PnpPlugin.js#L45), which only resolves bare identifiers (`wouter`) to the package location on the disk. The rest of the resolution (indexes, modules, etc) should be handled by Webpack, and thus work 🤔

**Comment by johnrichardrinehart** [comment]
@alexander-akait Ping just so I don't forget about this.

**Comment by alexander-akait** [comment]
@johnrichardrinehart should we reopen this, I can investigate

**Comment by johnrichardrinehart** [comment]
Please. I'm not in a position to diagnose the cause. I barely understand how all these parts fit together.

**Comment by johnrichardrinehart** [comment]
@sokra Could you help me debug this? We have a couple good pieces of information.

1. Adding `resolve: {fullySpecified: false}` to my `webpack.config.js` [fixes the broken build](https://github.com/webpack/webpack/issues/12093#issuecomment-736610502).
2. Removing `type: "module"` from the dependency's `package.json` (`yarn unplug`) [fixes the broken build](https://github.com/yarnpkg/berry/issues/2199#issuecomment-736729588).

The [author](https://github.com/molefrog/wouter/issues/150) of this package is [apparently](https://github.com/webpack/webpack/issues/12093#issuecomment-736732047) doing nothing wrong, putting this issue in the `webpack/webpack` court.

Please let me know how I can help debug.

**Comment by sokra** [comment]
So far I think it's a webpack (enhanced-resolve) bug regarding removing fullySpecified when resolving module request with PnP, but I have to investigate further...

* wouter looks fine
  * peerDependenciesMeta is not needed, peerDependencies is enough. Without that you would get another error telling that it is missing.
  * `import "react"` is valid when using `type: "module"`

**Comment by johnrichardrinehart** [comment]
> bug regarding removing fullySpecified when resolving module request

Just to be clear: **Adding** `fullySpecified: false` **fixes** the resolution problem. So, it doesn't seem to me that `enhanced-resolve` is removing `fullySpecified` when resolving a module request with PnP. Actually, it's taking `fullySpecified` into consideration and changing resolution behavior based on the presence/absence of this resolver option.

**Comment by johnrichardrinehart** [comment]
@sokra Your [PR](https://github.com/webpack/enhanced-resolve/pull/266) fixed it.

@alexander-akait Any idea how long until `webpack`'s minor version will be promoted to include this change?

Until then I have 
```json
  "resolutions": {
    "enhanced-resolve": "5.4.0"
  },
```
added to my `package.json`.


@arcanis @molefrog We're all good! :)

**Comment by sokra** [comment]
> Any idea how long until `webpack`'s minor version will be promoted to include this change?

webpacks enhanced-resolve range includes that version. You just need to update you lockfile.

**Comment by johnrichardrinehart** [comment]
Oh, okay. I `yarn up`ed but that didn't touch my dependences. That's smart. I'll delete my lock file and `yarn install`.

Thanks again, @sokra .
