### ISSUE TITLE
provide for cli agruments useful error from schema-utils

### ISSUE THREAD

**Issue by alexander-akait** [webpack/webpack#12113]
## Feature request

```js
const problems = require('webpack').cli.processArguments(coreFlag, options, coreConfig);

if (problems) {
  problems.forEach((problem) => {
    console.log(proble.type); // Fine
    console.log(proble.argument); // Fine
    console.log(proble.argument); // Fine, but why?
    console.log(proble.hint); // I think here we can have helpful message for better DX like from `schema-utils`
 });

  process.exit(2);
}
```

**What is the expected behavior?**

Have helpful message like from `schema-utils`

**What is motivation or use case for adding/changing the behavior?**

Provide better DX

**How should this be implemented in your opinion?**

**Are you willing to work on this yourself?**

Don't have time rihgt now

**Comment by akgupta0777** [comment]
I am willing to work on this.
Can you please tell me How should this be implemented?

**Comment by alexander-akait** [comment]
https://github.com/webpack/webpack/blob/master/lib/cli.js#L484

**Comment by akgupta0777** [comment]
Thanks

**Comment by sokra** [comment]
Do you want a `message` property in the `Problem` info, which is a formatted version of the data.

**Comment by alexander-akait** [comment]
Yep, helpful message for better DX - i.e. possible values

**Comment by akgupta0777** [comment]
is DX stands for Debugging Experience ?

**Comment by sokra** [comment]
> Yep, helpful message for better DX - i.e. possible values

Possible values is already provided via `expected`. I think all information is already there. I can add an additional property which provides a readable text version of the data. I didn't do that initially because I thought the cli might want to be in control of messages, so I provided a type and the data instead.

**Comment by alexander-akait** [comment]
Fixed in `webpack-cli`, `expected` is enough for us
