### ISSUE TITLE
[webpack 5] production build failes for specific mix of require, imports and sideEffects: false

### ISSUE THREAD

**Issue by meskill** [webpack/webpack#12114]
# Bug report

**What is the current behavior?**
Running production build for a specific mix of modules with requires, imports, and modules with the flag `sideEffects: false` will fail build with error:

```
RuntimeTemplate.importStatement(): Module /workspaces/open-source/webpack5-require-bug/src/node_modules/@test/reexport/index.js has no id assigned.
    This should not happen.
    It's in these chunks: none (If module is in no chunk this indicates a bug in some chunk/module optimization logic)
    Module has these incoming connections:
    - /workspaces/open-source/webpack5-require-bug/src/a.js harmony side effect evaluation
    - /workspaces/open-source/webpack5-require-bug/src/a.js harmony import specifier
```

**If the current behavior is a bug, please provide the steps to reproduce.**
I've created a test repo with the simple file structure to show the difference in build for webpack4 and webpack5
https://github.com/meskill/webpack5-require-bug

**What is the expected behavior?**
Build should happen without errors as it was for webpack4.

**Other relevant information:**
webpack version: 5.9.0 
Node.js version: 14.15.1

**Comment by alexander-akait** [comment]
Can you try to update to `1.14.1`?

**Comment by meskill** [comment]
> Can you try to update to `1.14.1`?

what package do you suggest to upgrade?

**Comment by alexander-akait** [comment]
`tslib`, but it is not help

**Comment by sokra** [comment]
bugfix is on the way: https://github.com/webpack/webpack/pull/12123
