### ISSUE TITLE
external promise: syntaxError

### ISSUE THREAD

**Issue by DoctorChenGuang** [webpack/webpack#12111]
**Webpack config**:
    externals: [
      function({ context, request, }, callback){
        return callback(null, result, "**promise**")
      }
    ]

**Compiled Code**:
"use strict";
module.exports = (async () => {...});

Problom:
The **browser version** is so low that some syntax parsing failed, example, arrow function or async/await.
I do some test and found that the webpack internal-code is not included in **babel-loader ** scoped.
Is there any configuration to solve above situation?
 Or i need to encapsulate a plugin to solve this.

**Comment by DoctorChenGuang** [comment]
> _For maintainers only:_
> 
> * [ ]  webpack-4
> * [X]  webpack-5
> * [ ]  bug
> * [ ]  critical-bug
> * [ ]  enhancement
> * [ ]  documentation
> * [ ]  performance
> * [ ]  dependencies
> * [ ]  question

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
