### ISSUE TITLE
Eagerly shared modules should take precedence in shared module registration

### ISSUE THREAD

**Issue by jakenorthey** [webpack/webpack#12124]
## Feature request

**What is the expected behavior?**
If two containers provide the same version of the same module, currently the runtime of the SharePlugin resolves the registration conflict by comparing the names of the containers registering the modules.  If one of the containers provides the module eagerly, it is expected that the eagerly bundled module should take precedence.

**What is motivation or use case for adding/changing the behavior?**
Modules that are already available eagerly should be loaded synchronously versus asynchronous chunk loading of modules that are not made available eagerly.

**How should this be implemented in your opinion?**
Update the ProvideSharedModule to indicate whether a module is provided eagerly.  Update the ShareRuntimeModule to check whether a module is provided eagerly and prioritize modules that are eager.

**Are you willing to work on this yourself?**
yes

**Comment by alexander-akait** [comment]
I don't think it is possible

especial due

> Modules that are already available eagerly should be loaded synchronously versus asynchronous chunk loading of modules that are not made available eagerly.

**Comment by jakenorthey** [comment]
I do have an implementation in a fork.  The shared module registration code below will override a shared module entry that is not already loaded if the container name is greater.  The implementation simply adds an extra step to check if the module was provided eagerly so that the shared module registration does not have to simply resort to container name comparisons as a tiebreaker.
```"if(!activeVersion || !activeVersion.loaded && uniqueName > activeVersion.from) versions[version] = { get: factory, from: uniqueName };"```

**Comment by jakenorthey** [comment]
https://github.com/webpack/webpack/blob/88ed4fe03fea19ed9396fdaba05e8f2003c22161/lib/sharing/ShareRuntimeModule.js#L90

**Comment by alexander-akait** [comment]
But how you can guarantee who was first, it depends on very different approaches

**Comment by jakenorthey** [comment]
In this case when there is a conflict, we only want to prioritize eager modules.  In the case that we have a conflict between two containers providing two copies of the same version of the module and bother are eager, we shouldn't care which one wins out.  However in the case where we have two containers providing two copies of the same version of the module and one is eager and one is not, we would prefer the eager module.

**Comment by sokra** [comment]
Yep that makes sense

**Comment by alexander-akait** [comment]
@jakenorthey PR welcome, don't forget about tests

**Comment by jakenorthey** [comment]
PR submitted:
https://github.com/webpack/webpack/pull/12132

**Comment by alexander-akait** [comment]
Implemented by https://github.com/webpack/webpack/pull/12132
