### ISSUE TITLE
[webpack 5] Dynamic chunk loading error

### ISSUE THREAD

**Issue by budarin** [webpack/webpack#12130]
# Bug report
After migrating from v4 to v5 webpack fails while serving dynamic chunk loading

**What is the current behavior?**
Dynamic chunk import hangs and throws timeout error

```js
import(/* webpackChunkName: "Home" */ './home')
```

```bash
Error loading Home.js ChunkLoadError: Loading chunk Home failed.
(timeout: http://localhost:3000/assets/Home.js)
    at Object.__webpack_require__.f.j (http://localhost:3000/assets/client.js:10365:29)
    at http://localhost:3000/assets/client.js:9849:40
    at Array.reduce (<anonymous>)
    at Function.__webpack_require__.e (http://localhost:3000/assets/client.js:9848:67)
    at Function.fn.e (http://localhost:3000/assets/client.js:10048:50)
    at HTMLDocument.<anonymous> (http://localhost:3000/assets/client.js:9751:25)
```

Note: if remove preloading Home.js from html or remove magic comment from import - everything works but its strange

```html
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Simple app</title>
    </head>
    <body>
        <div id="app">
        <script src="/assets/Home.js"></script>
        <script src="/assets/client.js"></script>
    </body>
    </html>
```

**If the current behavior is a bug, please provide the steps to reproduce.**
[Demo repository](https://github.com/budarin/wp5-dev-server)

**What is the expected behavior?**
proper chunk loading 

**Other relevant information:**
webpack version:  5.10.0
Node.js version:  v15.0.1
Operating System: any

**Comment by csvan** [comment]
@budarin you probably should move this to https://github.com/webpack/webpack-dev-server

Also, webpack-dev-server v3 is not compatible with Webpack 5. You can try the beta version of v4 which is: https://github.com/webpack/webpack-dev-server/releases/tag/v4.0.0-beta.0

**Comment by budarin** [comment]
@csvan 

I'm not sure whose webpack or dev-server problem this is.
I'll try with dev-server beta

**Comment by budarin** [comment]
@csvan

the problem remained with the new dev-server's version - so the bug is in webpack

**Comment by sokra** [comment]
I can't open your repro repo. Is it private?

**Comment by budarin** [comment]
> I can't open your repro repo. Is it private?

sorry, my falls 
made public

**Comment by jeyashree-n** [comment]
I am also facing the same issue continuously.

Webpack: 4.46.0 
Webpack-dev-server: 3.1.14

**Comment by csvan** [comment]
Webpack 4 is not supported anymore

**Comment by hansiemithun** [comment]
why is this closed without a solution, similar problem and blocked with webpack 5. 

Ref: https://github.com/webpack/webpack/issues/17608
