### ISSUE TITLE
Webpack externals throw error on `prod builds` how to resolve this?

### ISSUE THREAD

**Issue by 3gwebtrain** [webpack/webpack#12139]
In my `index.html` i am loading `jquery` and works well with local. when i do product build I am getting an error as :

`Uncaught ReferenceError: jQuery is not defined`  in the console. But still the `jquery` downloaded in `prod` build. how can i configure web pack to look the `jquery` in `windows` space alwasy?

here is my index.html ( i am using `systemjs` to download the script )

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Container</title>
    <base href="/" />
    <meta name="importmap-type" content="systemjs-importmap" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" type="image/x-icon" href="favicon.ico" />
    <script type="systemjs-importmap" src="/assets/import-map.json"></script>
    <script type="systemjs-importmap">
      {
        "imports": {
          "jquery": "https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js"
        }
      }
    </script>
    <script src="https://cdn.jsdelivr.net/npm/systemjs/dist/system.min.js"></script>
    <script>
      function multiImport(modules) {
        return Promise.all(
          modules.map(function (m) {
            return System.import(m);
          })
        );
      }
      multiImport(["jquery"]);
    </script>
  </head>
  <body>
    <app-root></app-root>
  </body>
</html>
```
my webpack config:

```
const webpack = require("webpack");

module.exports = {
  externals: {
    jquery: ["jQuery"],
  },
  plugins: [
    new webpack.ProvidePlugin({
      "window.jQuery": "jquery",
      $: "jquery",
      jquery: "jQuery",
    }),
  ],
};
```

after prod build getting an error as:

`Uncaught ReferenceError: jQuery is not defined
    at Object.xeH2 (main-es2015.18b4452e55ad689e0880.js:1)`

how can i fix this? what is the correct way to export and use it `prod` build as well?

**Comment by sokra** [comment]
I don't see the bundle in the HTML. I guess it's injected as script tag, which would create a race condition. Sometimes jquery loaded first, sometimes the bundle is loaded first.

You need to make sure to load the script in the correct order.

If you are using System.js you probably want to create your bundle as System.js library via

``` js
output: {
  library: "app",
  libraryTarget: "system",
},
externals: ["jquery"]
```

``` js
System.import("app"); // dependencies like jquery are automatically loaded by System.js
```

**Comment by 3gwebtrain** [comment]
@sokra , I am not able to get you clearly. can you please help me further? I created a js file in the root folder as "System.js" the it's added to `index.html` file. but still not getting any valid result. getting an error as `ERROR Error: Uncaught (in promise): Error: Parcel parcel-0 must have a valid bootstrap function1` I am quite new, please help me further.

**Comment by alexander-akait** [comment]
> ERROR Error: Uncaught (in promise): Error: Parcel parcel-0 must have a valid bootstrap function1

Why you run parcel?

**Comment by 3gwebtrain** [comment]
I am not run parcel, but my angular downloads once of the external angular app as parcel

**Comment by alexander-akait** [comment]
Sorry, this error not related to webpack, it is error from parcel runtime, we can't fix it

**Comment by 3gwebtrain** [comment]
Actually my question is different. I am loading external `jquery` in to angular. it works fine. I use the webpack external to do that. it works fine in local. But not after production build. the above said error reverted. can you please have look on my first question so  you can able to understand easly.

**Comment by alexander-akait** [comment]
Because you need to add scripts tags with webpack generated files

**Comment by 3gwebtrain** [comment]
so, ok. how can i use webpack instead systemjs then? any sample code or repo to load script outside to angular?

**Comment by alexander-akait** [comment]
Just add scripts tags, please use stackoverflow or gitter for questions, it is bug tracker

**Comment by sokra** [comment]
You can also run webpack with System.js, but you need to compile it for System.js



> ```js
> output: {
>   // webpack 4 or 5:
>   library: "app",
>   libraryTarget: "system", // <- for System.js
>   // webpack 5:
>   library: { type: "system", name: "app" }
> },
> externals: ["jquery"]
> ```

**Comment by alexander-akait** [comment]
Answer above
