### ISSUE TITLE
Module loading/bundling failure

### ISSUE THREAD

**Issue by siilike** [webpack/webpack#12138]
# Bug report

I am having an issue with @toast-ui/react-image-editor (a React wrapper for tui-image-editor) that was bundled fine with Webpack 4, but does not work any more with Webpack 5.

There is an issue related to module paths of tui-image-editor. Possibly related to the fact that tui-image-editor is still built with Webpack 4, but I would expect it to work regardless.

**What is the current behavior?**
Module is not loaded:

```
Uncaught TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (bundle.js:41685)
    at eval (index.js:3)
    at Object../src/index.js (bundle.js:40596)
    at __nested_webpack_require_1152__ (bundle.js:39425)
    at bundle.js:39489
    at bundle.js:39492
    at webpackUniversalModuleDefinition (bundle.js:39403)
    at Object.733 (bundle.js:39405)
    at __webpack_require__ (bundle.js:41685)
    at Object.<anonymous> (bundle.js:7)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/siilike/webpack12138

**What is the expected behavior?**

Module is loaded fine.

**Other relevant information:**
webpack version:  5.10.0
Node.js version: 14.15.1

**Comment by emilsedgh** [comment]
I made a pull request for tui, which is build using webpack5 and works fine.
Until that is released you can use my branch:

`npm i github:emilsedgh/tui.image-editor#62807f5a6015f4b62e453eb09672fc1ea7952a15`

**Comment by alexander-akait** [comment]
@emilsedgh Can't reproduce using the `latest` version of `webpack`

**Comment by siilike** [comment]
Confirmed to work in 5.17.0.
