### ISSUE TITLE
problem with node module

### ISSUE THREAD

**Issue by ximet** [webpack/webpack#1214]
Problem with standart module NodeJS: url module, http, https, zlib,stream

my setting file:
```javascript
          webpack: {
            custom: {
                entry: './src/index.js',
                output: {
                    path: 'build/',
                    filename: 'index.js'
                },
                target: 'node',
                resolve: {
                    extensions: [
                        '.js',
                    ],
                    root: '.'
                },
                module: {
                    loaders: [
                        { test: /\.js$/, loader: 'jsx-loader' },
                    ],

                }
            }
        }
```

After run build index.html, and see error: Uncaught ReferenceError: require is not defined
Opened details, and see:

```javascript
function(module, exports) {

	module.exports = require("url");

/***/ },
```
require not spun. How it fixed?

**Comment by shama** [comment]
It might be because your target is `target: 'node',` which is set for node and expects your bundle to be loaded in a node-like environment (where `require` exists).

If you leave that configuration out, it will default to `'web'` which is likely what you want if you're loading in `index.html`.

**Comment by ximet** [comment]
thnx

**Comment by mkotsollaris** [comment]
Adding `target: 'web'` in my `webpack.config.js` fixed the issue indeed.
