### ISSUE TITLE
Chunk's sourcemap cache is not work on dev mode because of runtime getFullHash changes every time

### ISSUE THREAD

**Issue by feix760** [webpack/webpack#12145]
# Bug report

**What is the current behavior?**

In a big project dev mode build very slow after single file changes，because chunk's sourcemap cache is not work

chunk's built in content `runtime/getFullHash` changes every time, so chould not match per cache

```js
/******/ 	/* webpack/runtime/getFullHash */
/******/ 	(() => {
/******/ 		__webpack_require__.h = () => "8b762c66508e598f9870"
/******/ 	})();
```

**If the current behavior is a bug, please provide the steps to reproduce.**

- Watch mode start a project
- Modify a file to rebuild project

See if this cache code works

https://github.com/webpack/webpack/blob/25b9f4e7311104b79b32b8129477cbe19879005c/lib/SourceMapDevToolPlugin.js#L212

**What is the expected behavior?**

Use chunk's sourcemap cache to eeduce most of the rebuild time

**Other relevant information:**
webpack version:  5.10.0
Node.js version: 12.18.0
Operating System:  mac
Additional tools:

**Comment by alexander-akait** [comment]
@feix760 Please provide your configuration

**Comment by sokra** [comment]
That's actually true, but the full hash really changes every build. (It's added because HMR needs it)

Best put the runtime modules into a separate chunk with `optimization.runtimeChunk: true`.

**Comment by sokra** [comment]
You could also go with

``` js
output: {
  hotUpdateChunkFilename: "[id].hot-update.js",
  hotUpdateMainFilename: "[runtime].hot-update.json"
}
```

so removing the `[fullhash]` from the defaults. Then `getFullHash` won't be added anymore.

But this might cause some issues when updates happen faster then the browser can handle them...

**Comment by feix760** [comment]
Set this works fine

```javascript
  optimization: {
    runtimeChunk: {
      name: 'runtime',
    } ,
  },
```

Thx, I will close this issue.
