### ISSUE TITLE
browser get wrong warnings

### ISSUE THREAD

**Issue by dsaco** [webpack/webpack#12157]
# Bug report

**What is the current behavior?**
this is some eslint warnings
![image](https://user-images.githubusercontent.com/12523637/101596481-1c259b80-3a30-11eb-981b-c9ded540dfed.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
webpack4 and webpack-dev-server3 work good, when upgrade webpack5.10.0 webpack-dev-server4.0.0-beta.0

**What is the expected behavior?**
![image](https://user-images.githubusercontent.com/12523637/101596728-96562000-3a30-11eb-9d0f-8180e9ee6be4.png)

**Other relevant information:**
webpack version:  v5.10.0
Node.js version: v10.19.0
Operating System: chrome 87.0.4280.88
Additional tools:

**Comment by dsaco** [comment]
this is current behavior
![image](https://user-images.githubusercontent.com/12523637/101597850-3d878700-3a32-11eb-9310-21235bd0345c.png)
if add .message /webpack-dev-server/client/default/index.js
![image](https://user-images.githubusercontent.com/12523637/101598026-7d4e6e80-3a32-11eb-9308-82c2a5473659.png)
it's work but the style is not ok

![image](https://user-images.githubusercontent.com/12523637/101598223-ce5e6280-3a32-11eb-899d-f59ea67afb8f.png)

**Comment by alexander-akait** [comment]
Fixed in `webpack-dev-server@4-beta.0`

**Comment by dsaco** [comment]
my webpack-dev-server is 4.0.0-beta.0
it's doesn't fixed @alexander-akait

**Comment by alexander-akait** [comment]
Double check, anyway it is not related to webpack, please create reproducible test repo in webpack-dev-server repo
