### ISSUE TITLE
how to replace file

### ISSUE THREAD

**Issue by Yixi** [webpack/webpack#1215]
I use webpack for help me build a isomorphic javascript app.

I have a problem , I have two module :

<pre>
'./api/client/api.js'
'./api/server/api.js'
</pre>

because the server and client have different get data method, so I use 

<pre>
var api  = require('./api/server/api.js')
</pre>

but when webpack use same file build the client js I want use './api/client/api.js' for replace, is there have any setting like

<pre>
{
"./api/server/api.js":"./api/client/api.js"
}
</pre>

to solve my problem? 
thanks

**Comment by wyvernnot** [comment]
Will `alias` solve your problem?

http://webpack.github.io/docs/configuration.html#resolve-alias

**Comment by pwang2** [comment]
In coding phase, I am not sure we could use ../xxx/ path as alias name. 
 
Sokra suggest using NormalModuleReplacementPlugin
see https://github.com/webpack/webpack/issues/1090

**Comment by Yixi** [comment]
@pwang2  Yes, I think NormalModuleReplacementPlugin can solve my problem,thanks
