### ISSUE TITLE
Incorrect handling of imported identifier "require"

### ISSUE THREAD

**Issue by ef4** [webpack/webpack#12154]
# Bug report

**What is the current behavior?**

If an ES module exports a function named `require`, when you import and invoke it webpack 5 incorrectly treats it as a CJS require:

```js
import { require } from './my-lib';
function whatever() {
  require('something'); // <-- Module not found: Error: Can't resolve 'something'
}
```

This worked correctly in webpack 4. This is a regression in webpack 5.

**If the current behavior is a bug, please provide the steps to reproduce.**

In any webpack 5 project, add the file `my-lib.js` containing:

```js
export function require(thing) {
  return `I see you required ${thing}`;
}
```

And then in a second file try to import and invoke the function:

```js
import { require } from './my-lib';
function whatever() {
  console.log(require('something'));
}
```

You will see a build error in webpack 5, whereas it will work correctly in webpack 4.

**What is the expected behavior?**

Webpack should only handle `require` when it's a free upvar. Webpack v4 got this correct, and Webpack v5 gets it correct for cases like `function require(){}` in scope, but gets it wrong for `import { require } from '...'`.

**Other relevant information:**
webpack version:  5.10.0
Node.js version: 12.16.0
Operating System: OSX
Additional tools: N/A

**Comment by alexander-akait** [comment]
You need to use `externals`

**Comment by ef4** [comment]
This is not about externals. In my example, the string passed to `require` is *not* the name of a module. This is just an arbitrary function that happens to be named `require`.

**Comment by ef4** [comment]
What's more, if I move the arbitrary function *inside* the module that calls it, webpack handles it fine, because webpack *knows* that not all `require` calls are truly CJS require calls. Only unbound ones:

```js
function require(thing) {
  return `I see you required ${thing}`;
}
require('something'); // <- no error, as it should be
```

**Comment by alexander-akait** [comment]
Sorry, I was confused, here interesting case, you can do it using:
```
{
  test: /\.js$/,
  type: "javascript/esm",
},
```

Other solution is rename `js` files to `mjs` (both).

Why it is not by default? 

Webpack has 3 types for parsing javascript files: `javascript/dynamic` (i.e. `sourceType: script`, no `import`/`export`), `javascript/esm` (i.e. `sourceType: module`, ECMA modules) and `javascript/auto` (allow to use `require` and `import`) https://github.com/acornjs/acorn/tree/master/acorn, unfortunately most of developers use babel and other tools which allow you to create files with `require` and `import`/`export` in one file. We found it too hard for migration for developers when webpack v5 was development and keep `javascript/auto` by default. Perhaps we will consider in future (for v6).

Feel free to feedback, and sorry again

**Comment by alexander-akait** [comment]
Do not forget `import { require } from './my-lib';` is wrong, because ECMA modules requires extension at the end `import { require } from './my-lib.js';` (or `mjs`)

**Comment by alexander-akait** [comment]
Why it worked in v4? Simple - because tree shaking is not working for many cases, but in v5 we improve tree shaking, so now we you faced with the error

**Comment by ef4** [comment]
But anyway, yes, thank you for the explanation about the parsing mode. That probably solves my problem.

**Comment by alexander-akait** [comment]
> FWIW, switching the mode to javascript/esm is a workaround for this bug but this is still a real bug in javascript/auto mode. There's nothing ambiguous in the example -- require is a local binding that has nothing to do with CJS require.

> My example code is fine in javascript/esm mode, but this issue can occur within a larger codebase that really needs auto mode, so as long as you think auto mode needs to exist, IMO it's worth making auto mode properly understand how binding scope works in this case.

Yes, you are right here, we tried to do it, but found it hard for many cases, it request deep analyze, for example

```js
import { require } from './my-lib';
import { createRequire } from 'module';

require = createRequire('string');

function whatever() {
  require('something'); // <-- Module not found: Error: Can't resolve 'something'
}
```

So now `require` is `require`, there are more cases...

Ideally, we shouldn't have `javascript/auto`... Look here https://github.com/webpack/webpack/projects/5#card-10425786, I think we revisit it for webpack v6

**Comment by ef4** [comment]
Makes sense. I agree, we should all be pulling the ecosystem toward clear standards and not a mishmash like auto mode. Thanks.
