### ISSUE TITLE
webpack 5.10.0 compiled with 3 warnings in 9251 ms

### ISSUE THREAD

**Issue by mdrahiem** [webpack/webpack#12162]
I've a simple webpack5 configuration with react but its taking too much time to compile in development. Below is my webpack configuration file. If you would like to look at the repo, please check this [url](https://github.com/mdrahiem/simple-react-redux-saga-app).

webpack.config.js
```
const path = require('path'); 
const HtmlWebPackPlugin = require('html-webpack-plugin'); 
const baseURL = path.resolve(__dirname, ''); 
module.exports = { 
  entry: path.resolve(baseURL, 'src', 'index.js'),
  output: { 
    path: path.resolve(__dirname, 'dist'), 
    filename: 'main.js', 
    publicPath: '/' 
  }, 
  devServer: { 
    // this is for whenever the inner url reloads (or 404s) they should redirect to '/'
    historyApiFallback: true 
  },
  module: { 
    rules: [ 
      { 
        test: /\.js$/, 
        exclude: /node_modules/, 
        loader: "babel-loader", 
      } 
    ] 
  }, 
  plugins: [ 
    new HtmlWebPackPlugin({ 
      template: `${baseURL}/src/index.html`, 
      filename: './index.html', 
      inject: 'body', 
    }) 
  ] 
};
```

![image](https://user-images.githubusercontent.com/12086760/101735851-826df500-3ae8-11eb-800f-bfd83fbdaff7.png)

**Comment by sokra** [comment]
You probably want to run in `mode: "development"`, but it actually there should be a warning about that. It seem to be a bug that this is not displayed. cc @alexander-akait

**Comment by mdrahiem** [comment]
Thanks @sokra for your tip 👍 

For the people who will visit this to find a solution, I've updated the git repo in this [url](https://github.com/mdrahiem/simple-react-redux-saga-app).

![image](https://user-images.githubusercontent.com/12086760/101760328-b9e89b80-3b00-11eb-8e81-d0d45d325537.png)

**Comment by alexander-akait** [comment]
@sokra yep, already fixed
