### ISSUE TITLE
The property 'nestedModulesSpace' of Stats does not exist

### ISSUE THREAD

**Issue by akasuv** [webpack/webpack#12163]
# Bug report
It seems that `Stats` doesn't have a `nestedModulesSpace` property like it [introduced](https://webpack.js.org/configuration/stats/#statsnestedmodulesspace) in the doc.

**What is the current behavior?**

> Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
>  - configuration.stats has an unknown property 'nestedModulesSpace'. These properties are valid:
>    object { all?, assets?, assetsSort?, assetsSpace?, builtAt?, cached?, cachedAssets?, cachedModules?, children?, chunkGroupAuxiliary?, chunkGroupChildren?, chunkGroupMaxAssets?, chunkGroups?, chunkModules?, chunkOrigins?, chunkRelations?, chunks?, chunksSort?, colors?, context?, dependentModules?, depth?, entrypoints?, env?, errorDetails?, errorStack?, errors?, errorsCount?, exclude?, excludeAssets?, excludeModules?, groupAssetsByChunk?, groupAssetsByEmitStatus?, groupAssetsByExtension?, groupAssetsByInfo?, groupAssetsByPath?, groupModulesByAttributes?, groupModulesByCacheStatus?, groupModulesByExtension?, groupModulesByPath?, hash?, ids?, logging?, loggingDebug?, loggingTrace?, moduleAssets?, moduleTrace?, modules?, modulesSort?, modulesSpace?, nestedModules?, optimizationBailout?, orphanModules?, outputPath?, performance?, preset?, providedExports?, publicPath?, reasons?, relatedAssets?, runtimeModules?, source?, timings?, usedExports?, version?, warnings?, warningsCount?, warningsFilter? }
>    -> Stats options object.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Assign any integer to `stats` property `nestedModulesSpace` in webpack config
```
  stats: {
    nestedModulesSpace: 15,
  }
```
2. Run webpack.

**What is the expected behavior?**
At least it should have this property.

**Other relevant information:**
webpack version:  v5.10.0
Node.js version: v12.18.2
Operating System: macOS Big Sur v11.0.1
Additional tools:

**Comment by sokra** [comment]
Yep, good find, it's missing in the schema. Do you want to send a PR? (Make sure to also run `yarn special-lint-fix` to update the typings)

**Comment by akasuv** [comment]
Sure, I'll try it when I get some time.

**Comment by jaiwanth-v** [comment]
Hi @akasuv, are you working on this? If not, I'll send a PR.

**Comment by akasuv** [comment]
Go ahead

**Comment by akgupta0777** [comment]
I also tried to fix this and added schema but because of lack of guidance and knowledge I can't fix the issue.
I am closing my Pull request.

@jaiwanth-v  can you explain me how did you tackle this issue and how do you come to know about how this problem can be solved.

I feel much happy to learn from you.

**Comment by jaiwanth-v** [comment]
Have a look at my PR, I think you'll understand it.
