### ISSUE TITLE
Dynamic import with variable + module-federation-plugin error

### ISSUE THREAD

**Issue by XingtianLiu** [webpack/webpack#12167]
# Bug report

I'm trying to use a dynamic import that uses a variable in module federation plugin. Then report error.My Code:

```javascript
  const separator = '/'
  import("childApp"+separator+"module").then(res=>{
      console.log(res)
  })
```

error:

```shell
  Uncaught (in promise) Error: Cannot find module 'childApp/module'
```

**What is the current behavior?**

I attempt to change my code:

```javascript
  // works 
  const separator = '/'
  import("."+separator+"child").then(res=>{
      console.log(res)
  })
  // works 
  import("childApp/module").then(res=>{
      console.log(res)
  })
 // error
  import("childApp"+separator+"module").then(res=>{
      console.log(res)
  })
```

**If the current behavior is a bug, please provide the steps to reproduce.**

This is my example: <https://github.com/XingtianLiu/module-federation-import.git>

steps:

- git clone https://github.com/XingtianLiu/module-federation-import.git
- yarn
- yarn start

**What is the expected behavior?**

**Other relevant information:**
webpack version:  ^5.10.0
Node.js version:  v15.3.0
Operating System: windows10
Additional tools:

**Comment by alexander-akait** [comment]
What is real use case?

**Comment by sokra** [comment]
`"childApp"+separator+"module"` that's not supported.

`"childApp/"+expression` that is technically possible, but not implemented.

**Comment by XingtianLiu** [comment]
> What is real use case?

In my application , frontend split into many parts and they deployed on different web server. Main part don't know where they are,  it must load all routers from backend api.In other words, it must work:

```javascript
  const app = "childApp"
  const routers = ["app1","app2","app3"]
  routers.forEach(router=>{
  	import(app + "/" + router)
  })
```
But  that's not supported.

**Comment by alexander-akait** [comment]
You can have map of routes

**Comment by XingtianLiu** [comment]
> You can have map of routes

 Could you please give me a demo?

**Comment by alexander-akait** [comment]
@XingtianLiu Just store paths in Object or Map

**Comment by XingtianLiu** [comment]
The Final Solution:
```jsx
// child
 new ModuleFederationPlugin({
      name: "childApp",
      library: { type: "var", name: "childApp" },
      filename: "remoteEntry.js",
      exposes: {
        "./ChildAppHome": "./src/components/ChildHome.vue",
        "./ChildAppPage1": "./src/components/Page1.vue",
        "./ChildAppPage2": "./src/components/Page2.vue"
      },
      shared: ["vue", "vue-router"],
    }),
```
```jsx
// main app vue-router
async function $gm(child,router){
  const module = await window[child].get('./'+router)
  return module().default
}
const arr = [
  { url: '/child', container: 'childApp', name: "childApp", component: 'ChildAppHome' },
  { url: '/child/page1', container: 'childApp', name: "page1", component: 'ChildAppPage1' },
  { url: '/child/page2', container: 'childApp', name: "page2", component: 'ChildAppPage2' },
]
function formatRouters(arr) {
  return arr.map(({ url, container, component,name }) => (
     {
      path: url,
      name,
      component: $gm(container, component)
    }
  ))
}
const routers = [
  {
    path: '/',
    name: 'Home',
    component: Home,
  },
  ...formatRouters(arr)
]
```

**Comment by T0miii** [comment]
it seems like this still doesnt working is this solution from @XingtianLiu best pactice and the way to go?
