### ISSUE TITLE
Create a new Boiler Plate

### ISSUE THREAD

**Issue by daniele-zurico** [webpack/webpack#1216]
Hello guys, 
I've just completed my Angular ES6 boiler plate project to get you started. Write Directives/Controllers and Services using classes. Test your code using Jasmine, generate documentation using ES6 Docs view test coverage and more. 

The project using a modular architecture where you build re-usable modules and glue them together in a container 

If you're interested clone the project and if you've same good idea how to improve it please create an issue or a branch and we will improve it. 

https://github.com/daniele-zurico/es6-webpack-angular

**Comment by bebraw** [comment]
Thanks for heads up. I'm closing the issue as I'm trying to clean up the tracker a bit. ;)
