### ISSUE TITLE
Webpack 5 cache storing should reset the idle timeout when a rebuild is triggered or building

### ISSUE THREAD

**Issue by zlk89** [webpack/webpack#12179]
# Bug report

**What is the current behavior?**
The cache storing happens even webpack is rebuilding.

**If the current behavior is a bug, please provide the steps to reproduce.**
- Set idle time to 10 second
- Right after initial build, make change to any file which triggers a rebuild
- You will see the cache storing happens even if the second build has not completed, and it stuck at
`94% sealing after seal` until the cache is stored.

**What is the expected behavior?**
The `idleTimeoutForInitialStore` or `idleTimeout` should be reset when a new build is triggered, and starts to count after the build is completed

**Other relevant information:**
webpack version:   5.10.0
Node.js version: 12.16.1
Operating System: Mac
Additional tools:

**Comment by Bosch-Eli-Black** [comment]
I think this is still an issue.

**Comment by alexander-akait** [comment]
What is the problem?

**Comment by Bosch-Eli-Black** [comment]
Thanks for the response, @alexander-akait  🙂

Making a change in a watched file that's currently being compiled doesn't stop the current compilation.

For example:

1. Run webpack in watch mode
2. Make a change in hello.jsx
3. Webpack starts compiling
4. Make another change in hello.jsx
5. Webpack waits for the first compilation to finish and then queues another compilation.

On projects that take several seconds to compile, this can be time consuming.

**Comment by sokra** [comment]
@Bosch-Eli-Black this doesn't sound related to the issue.

According to the code, idle timeout is reset when the next compilation starts. I wasn't able to reproduce the problem.

If this is still a problem, please open a new issue with a reproduction.

**Comment by Bosch-Eli-Black** [comment]
After updating to the newest webpack version, I no longer have this issue. Sorry for the spam, and thanks, sokra 🙂
