### ISSUE TITLE
Really cannot figure out why __webpack_amd_options__ is not defined

### ISSUE THREAD

**Issue by ZombieHippie** [webpack/webpack#1217]
I've been tweaking my config process, and cannot figure out where or how this variable `__webpack_amd_options__` is supposed to be populated.

**Comment by sokra** [comment]
It's populated from `options.amd`.

http://webpack.github.io/docs/configuration.html#amd

**Comment by ZombieHippie** [comment]
Thank you, I had some crazy things happening with my first attempt at configuration, so I believe this is a non-issue.
