### ISSUE TITLE
Use different config/loader options for different entrypoints?

### ISSUE THREAD

**Issue by evandegr** [webpack/webpack#1218]
Let's say I have one entrypoint called ```app.ie.js``` and one entrypoint called ```app.js```. I would like two bundles to be created, but with one of them having a different ```includePaths[]``` option for the ```scss``` loader i.e. one is

```{
    test: /\.scss$/,
    loader: 'style!css!autoprefixer-loader?{browsers:["last 2 versions","ie >= 9"]}!sass?includePaths[]=app/src'
}```

and the other is:

```{
    test: /\.scss$/,
    loader: 'style!css!autoprefixer-loader?{browsers:["last 2 versions","ie >= 9"]}!sass?includePaths[]=app/src/ie9styles'
}```

Is something like this possible?

**Comment by kirill-konshin** [comment]
+1 use case

I need to build a library in 2 variations: with and without external dependencies, so it would be great if I could set externals individually per entry point.

**Comment by evandegr** [comment]
You can pass an array as config to webpack apparently:

```[
    {entrypoints: sauce},
    {entrypoints: wut}
]```

**Comment by kirill-konshin** [comment]
Got a question about passing an array as webpack config... Does it use loaders for each file only once no matter how many array items there are?

For my case I have 2 variations, and 99% of the files are the same, the only difference is whether to include externals or not...

**Comment by kirill-konshin** [comment]
Bump. The question is only about optimization... I've got plenty of TypeScript files and it would be great if even with multiple array items in webpack config each file would still be compiled only once. Can anyone confirm that?
