### ISSUE TITLE
Question:  How to keep both formatted and minized versions of budnle with the V5?

### ISSUE THREAD

**Issue by ievgennaida** [webpack/webpack#12187]
I have a project configured to generate minimized and formatted file versions:
https://github.com/ievgennaida/animation-timeline-control/blob/master/webpack.config.js
when migrated to v 5.1.0 both file are minimized.
Any way to keep two versions?

**Comment by alexander-akait** [comment]
You can use multi compiler mode https://github.com/webpack/webpack/tree/master/examples/multi-compiler and disable minification for the formatted version https://webpack.js.org/configuration/optimization/#optimizationminimize
