### ISSUE TITLE
Accessing a circular dependency early with re-export, an error occurs

### ISSUE THREAD

**Issue by HealGaren** [webpack/webpack#12193]
# Bug report

**What is the current behavior?**

This is a simplified example:
```js
// src/barrel/a.js
export function a() {}

// src/barrel/b.js
import {a} from "./index";
console.log(a); // expected undefined
export function b() {}

// src/barrel/index.js
export * from "./b";
export * from "./a";

// src/index.js (entry point)
import {b} from "./barrel";
b();
```

When I run this example, I get an `Cannot read property 'a' of undefined` error in `console.log(a);` line of `b.js`.

**What is the expected behavior?**

I expect undefined to be printed to log without error.

I know that if I change the export order of `index.js` or import `a.js` directly from `b.js` it works fine.
But I expect modules with unresolved circular imports to evaluate to undefined.

If I run the same code with Webpack 4(`4.44.2`), it prints undefined without error.

**Other relevant information:**
webpack version:  5.10.1
Node.js version: 14.15.1
Operating System: Ubuntu 20.04.1 LTS (WSL)
Additional tools: None

**Comment by alexander-akait** [comment]
I can't reproduce:
```
asset main.js 51 bytes [compared for emit] [minimized] (name: main)
orphan modules 150 bytes [orphan] 3 modules
./index.js + 3 modules 182 bytes [built] [code generated]

webpack 5.10.0 compiled with 1 warning in 151 ms
```

**Comment by alexander-akait** [comment]
Try to run this code without webpack, you will get runtime error, why you nees this, what is real use case?

**Comment by sokra** [comment]
Actually it should log `function`, but this is a limitation in webpack ESM emulation. In some cases it will work in production mode or with `optomization.concatenateModules: true`. Try to reorder the reexports or import the leaf modules directly.

We can't fix that.

**Comment by HealGaren** [comment]
@alexander-akait 
Since it is a webpack environment, it seems that an error occurs by omitting the `index.js` and `.js` extensions.
If you add the omitted file name, it will be successfully executed in ES module format directly in Chrome.
(I created github [repo](https://github.com/HealGaren/esm-reexport-order-test) & [page](https://healgaren.github.io/esm-reexport-order-test/))

@sokra
The reason I expected undefined is that it followed the output of the old webpack version.
I understood that the actual browser behavior is loggin `function` and Webpack doesn't support it. Thank you.

**Comment by HealGaren** [comment]
Here are some use cases that came to ask for this issue:

- I use typescript and legacy decorator, and use [typescript metadata](https://www.typescriptlang.org/docs/handbook/decorators.html#metadata) in some code.
(Summary of metadata: compiled to insert type data at class declaration time)
- There is a legacy class that uses a circularly imported class as a member, and this class uses decorator and does not use metadata.
- In version 4 of the webpack that I was using, the type data of the circularly imported class was inserted as undefined. Therefore, there was no problem unless you use type data.
- After updating to Webpack 5, an error similar to this issue occurs when the imported class is evaluated to insert type information.

I wanted to keep the old behavior because there was a risk to refactoring the legacy code.

---
I know that this use case is a problem with other libraries, not webpack, and is just an example.

Even if the behavior is not supported, I think it is possible to implement a change to safely evaluate to undefined without throwing an error. (If necessary, I will try to send a PR.)

Is it wrong to try to change it so that it doesn't make an error?

**Comment by alexander-akait** [comment]
Maybe better to stick on webpack@4 in this case 

> Even if the behavior is not supported, I think it is possible to implement a change to safely evaluate to undefined without throwing an error. (If necessary, I will try to send a PR.)

I think it is very hard/impossible to fix without breaking something other

**Comment by alexander-akait** [comment]
In the latest release (i.e. `5.26.2`), it is `undefined`, fixed :smile:

**Comment by ElvisWang27** [comment]
> In the latest release (i.e. `5.26.2`), it is `undefined`, fixed 😄

I meet the same issue like @HealGaren said when update to webpack@5.68 from webapck@4.46, Is this problem fixed?There was a risk to refactoring the legacy code.
<img width="540" alt="image" src="https://user-images.githubusercontent.com/12270447/154810237-00d939ec-4a50-4487-9168-fb3c99b9a7d0.png">
