### ISSUE TITLE
Why do I report errors when I run the examples?

### ISSUE THREAD

**Issue by SJanJan** [webpack/webpack#12199]
I installed the following steps to run the example, 
```
1.Run yarn in the root of the project.
2.Run yarn setup in the root of the project.
3.Run yarn add --dev webpack-cli in the root of the project.
4.Run cd examples/commonjs && node build.js
```
**but got the following error：**
$ cd examples/commonjs && node build.js
[webpack-cli] Unknown argument: --display-reasons
[webpack-cli] Unknown argument: --display-used-exports    
[webpack-cli] Unknown argument: --display-provided-exports
[webpack-cli] Unknown argument: --display-chunks
[webpack-cli] Unknown argument: --display-max-modules     
[webpack-cli] Unknown argument: --display-origins

Error: Command failed: node C:\Users\zhanglj3\Desktop\xx\webpack\bin\webpack.js --mode production --env production --display-reasons --display-used-exports --display-provided-exports --no-color --display-chunks  --display-max-modules 99999 --display-origins --output-public-path "dist/"  ./example.js -o dist/output.js 
[webpack-cli] Unknown argument: --display-reasons
[webpack-cli] Unknown argument: --display-used-exports
[webpack-cli] Unknown argument: --display-provided-exports
[webpack-cli] Unknown argument: --display-chunks
[webpack-cli] Unknown argument: --display-max-modules
[webpack-cli] Unknown argument: --display-origins

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
  killed: false,
  code: 2,
  signal: null,
  cmd: 'node C:\\Users\\zhanglj3\\Desktop\\xx\\webpack\\bin\\webpack.js --mode production --env production --display-reasons --display-used-exports --display-provided-exports --no-color --display-chunks  --display-max-modules 99999 --display-origins --output-public-path "dist/"  ./example.js -o dist/output.js '
}
**Why? I tried all kinds of methods, but still can't run. Can you help me? Thanks.**

**Comment by SJanJan** [comment]
> _For maintainers only:_
> 
> * [ ]  webpack-4
> * [ ]  webpack-5
> * [ ]  bug
> * [ ]  critical-bug
> * [ ]  enhancement
> * [ ]  documentation
> * [ ]  performance
> * [ ]  dependencies
> * [ ]  question
webpack-5,question

**Comment by SJanJan** [comment]
> _For maintainers only:_
> 
> * [ ]  webpack-4
> * [ ]  webpack-5
> * [ ]  bug
> * [ ]  critical-bug
> * [ ]  enhancement
> * [ ]  documentation
> * [ ]  performance
> * [ ]  dependencies
> * [ ]  question

**Comment by sokra** [comment]
the examples still use the old webpack-cli

this is addressed by https://github.com/webpack/webpack/pull/12125
