### ISSUE TITLE
react-bootstrap-table2-toolkit Import Error in Webpack 5

### ISSUE THREAD

**Issue by enosisbd-anonta** [webpack/webpack#12197]
# Bug report

**What is the current behavior?**
`react-bootstrap-table2-toolkit` package causes error when bundled using webpack 5 (`5.10.1` to be exact). Simply adding `import { Search } from 'react-bootstrap-table2-toolkit';` to any js file produces the following error.

```
SearchBar.js:9 Uncaught ReferenceError: arguments is not defined
    at eval (SearchBar.js:9)
    at Object../node_modules/react-bootstrap-table2-toolkit/lib/src/search/SearchBar.js (bundle.js:459)
    at __webpack_require__ (bundle.js:1141)
    at fn (bundle.js:1335)
    at eval (index.js:7)
    at Object../node_modules/react-bootstrap-table2-toolkit/lib/src/search/index.js (bundle.js:507)
    at __webpack_require__ (bundle.js:1141)
    at fn (bundle.js:1335)
    at eval (index.js:8)
    at Object../node_modules/react-bootstrap-table2-toolkit/lib/index.js (bundle.js:313)
```

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Clone this [sample repository](https://github.com/enosisbd-anonta/minimal-react-webpack-babel-setup). It's a minimal react project that uses webpack 5.
2. Checkout `master` branch
3. Start the app using `npm start` and look for the error in console.
4. Changes made in [this commit ](https://github.com/enosisbd-anonta/minimal-react-webpack-babel-setup/commit/75e81d1005ff58113418896f59487100dfb7ae10) are causing the error

**What is the expected behavior?**
We should be able to import the 'react-bootstrap-table2-toolkit' package without any error.

**Other relevant information:**
webpack version: 5.10.1
Node.js version: 12.16.2
Operating System: Windows
Additional tools: None

**Comment by enosisbd-anonta** [comment]
At the moment I am using the package by directly importing the UMD module provided in their `dist` directory.
```
import ToolkitProvider, { Search } from 'react-bootstrap-table2-toolkit/dist/react-bootstrap-table2-toolkit';
```

**Comment by sokra** [comment]
I don't think that's an webpack problem.

[The module uses `arguments` in an arrow function, which is incorrect](https://github.com/react-bootstrap-table/react-bootstrap-table2/blob/ef22dc47ebeb985b28980001f806eeb01a687973/packages/react-bootstrap-table2-toolkit/src/search/SearchBar.js#L14)

Nobody noticed in webpack 4 because it wrapped modules in normal functions. Webpack 5 also uses arrow function leaving no normal function to fallback.

**Comment by sokra** [comment]
Here is a fix: https://github.com/react-bootstrap-table/react-bootstrap-table2/pull/1506

**Comment by alexander-akait** [comment]
Let's close in favor https://github.com/react-bootstrap-table/react-bootstrap-table2/pull/1506

**Comment by juniorkibirige** [comment]
Error is back
Mix: Laravel Mix v6.0.13

**Comment by alexander-akait** [comment]
Fix was not merged

**Comment by juniorkibirige** [comment]
So then how do I go about solving this, cause on every deploy the files in node_modules are reinstalled on my server

**Comment by alexander-akait** [comment]
@juniorkibirige Can you provide stack of error?
