### ISSUE TITLE
App with Module federation doesn't load all scripts

### ISSUE THREAD

**Issue by siarhei-zharnasek** [webpack/webpack#12194]
# Bug report

**What is the current behavior?**
There are a few apps configured with ModuleFederationPlugin:
- main (loads one component from i_service and one component from b_service)
- i_service that exposes one component to main app
- b_service that exposes one component to main app

When I start main app I see only the first loaded component.
i_service and b_service expose components with the same hierarchy and naming (./src/common/components/Router/Router) and I guess this is the issue (name collision)

**If the current behavior is a bug, please provide the steps to reproduce.**

Repos:
- main app (https://github.com/siarhei-zharnasek/main-app)
- b_service (https://github.com/siarhei-zharnasek/b_service)
- i_service (https://github.com/siarhei-zharnasek/i_service)

`npm install` and `npm start` in every repo will start 3 apps (localhost:8080, localhost:8081, localhost:8082)
- open localhost:8080
- click to `Billing` in navigation, this will load Billing page
- click to `Identity` in navigation and page stays the same (should load component from another service)

Also this reproducible when you load Billing and Identity later.

**What is the expected behavior?**

Main app should load both components and resolve chunk even with the same name

**Other relevant information:**
webpack version:  5.4.0
Node.js version: 14.15.1
Operating System: Windows
Additional tools:

**Comment by alexander-akait** [comment]
webpack-dev-server doesn't support module federation, we have the issue about supporting it, but it is not implemented yet

**Comment by siarhei-zharnasek** [comment]
@alexander-akait does it mean that module federation will not work in production as well?

**Comment by alexander-akait** [comment]
Nope, it should work in production without webpack-dev-server

**Comment by siarhei-zharnasek** [comment]
@alexander-akait for my case it doesn't work (name collision)

**Comment by alexander-akait** [comment]
I don't see here name collisions, I think here problem with `HtmlWebpackPlugin`

**Comment by siarhei-zharnasek** [comment]
@alexander-akait why `HtmlWebpackPlugin` ? I saw that webpack resolves file's key as path to file (in exposes for `ModuleFederationPlugin`) for example `./src/common/components/Router/Router` path will become `src_common_components_Router_Router_tsx.[hash].js` name
but since I have the same structure for 2 projects I'll see the content of the firstly loaded script

**Comment by alexander-akait** [comment]
It means you have problems with configurations

**Comment by siarhei-zharnasek** [comment]
@alexander-akait any thoughts what's wrong with configs?

**Comment by alexander-akait** [comment]
@siarhei-zharnasek something wrong with your code, try to press `ctrl+F5` on http://0.0.0.0:8080/billing and http://0.0.0.0:8080/identity (all is fine)

**Comment by alexander-akait** [comment]
Try to remove `lazy` import and debug the problem

**Comment by sokra** [comment]
> i_service and b_service expose components with the same hierarchy and naming (./src/common/components/Router/Router) and I guess this is the issue (name collision)

you must have different `output.uniqueName`s in each app. This defaults the to `"name"` in `package.json`. 
**Make sure the each repo has a different `"name"` in the `package.json`.**

**Comment by siarhei-zharnasek** [comment]
@sokra applications had the same name (copypasted) and making them unique fixed the issue, thanks!
