### ISSUE TITLE
with newest webpack 1.10.0 page reload stops work

### ISSUE THREAD

**Issue by istarkov** [webpack/webpack#1219]
`webpack: 1.10.0`
`webpack-dev-server: 1.10.1`

full reload not work

```javascript
//app.js
console.log('XXX');
```
if change 'XXX' on 'YYY' page reload doesn't occurs.

with 
`webpack: 1.9.13`
`webpack-dev-server: 1.10.1`
all works as expected, page reloaded.

**Comment by jonmanzo** [comment]
Update to 1.10.1...  Fixed it for me....

**Comment by istarkov** [comment]
Thank you, all work with 1.10.1
