### ISSUE TITLE
code splitting doesn't work in child compilations

### ISSUE THREAD

**Issue by gusvargas** [webpack/webpack#12198]
## Feature request

**What is the expected behavior?**

Code splitting should work in child compilations without the need for additional configuration.

**What is motivation or use case for adding/changing the behavior?**

Without an intimate understanding of all of webpack's internal plugins and the hooks they use, it's unclear what functionality you get and don't get when when creating a child compiler. I found it surprising that a child compiler cannot, at minimum, build an app that uses code splitting given that code splitting is not a feature that you usually have to enable otherwise.

In my use case, I'd like to have a 2nd compilation that's _almost identical_ to the parent compilation with the exception that a different `optimization` option is set. Since the input to both compilations are identical I'd like to reuse as much work as possible across compilations so that webpack doesn't perform 2x the work.

This appears to be the minimal amount of code required to create a compilation similar to the parent:

```js
module.exports = class CopyCatCompilerPlugin {
  apply(mainCompiler) {
    mainCompiler.hooks.make.tapAsync(
      'ChildCompilerPlugin',
      (compilation, callback) => {
        const childCompiler = compilation.createChildCompiler(
          'child',
          mainCompiler.options.output,
          [
            new JsonpTemplatePlugin(), // required since `thisCompilation` taps are not copied
          ]
        );

        // required since `compile` taps are not copied by default
        childCompiler.hooks.compile.taps = mainCompiler.hooks.compile.taps.slice();

        // prevent errors like "Conflict: Multiple assets emit to the same filename 0.js"
        // since the child compilation will result is identically named split chunks
        childCompiler.options.output.chunkFilename = `child-${mainCompiler.options.output.chunkFilename}`;

        // filter out unwanted optimization plugins here

        // add identical entry with a different bundle name
        new SingleEntryPlugin(
          mainCompiler.context,
          './src/index.js',
          'main-2'
        ).apply(childCompiler);

        childCompiler.runAsChild(callback);
      }
    );
  }
};
```

In general, it seems like the pattern of running multiple almost-identical compilations is useful in cases where you want to compile to different targets while not duplicating work across compilation. Or when you want webpack to bundle a test runner bundle but not have the test bundle entry affect your code splits.

Is there a better approach to this problem so that it's easy to replicate the parent compilation with slightly different options while maintaining performance?

For context, I'm on webpack 4.27.1 but cannot migrate to webpack 5 since I have many custom plugins and loaders that will require work to make compatible with webpack 5.

**How should this be implemented in your opinion?**

Have `Compiler.createChildCompiler` ensure that the `JsonpTempaltePlugin` is applied.

**Are you willing to work on this yourself?**

yes

**Comment by alexander-akait** [comment]
> For context, I'm on webpack 4.27.1 but cannot migrate to webpack 5 since I have many custom plugins and loaders that will require work to make compatible with webpack 5.

Which?

You can apply plugin(s) on `childCompiler`, there is no bugs, like here https://github.com/webpack/webpack/blob/master/lib/WebpackOptionsApply.js#L351

**Comment by gusvargas** [comment]
Thanks for the reply.

> Which?

Which loaders/plugins? They're not open source.

> You can apply plugin(s) on childCompiler, there is no bugs, not all plugins enabled by default for child compilations, like here https://github.com/webpack/webpack/blob/master/lib/WebpackOptionsApply.js#L351

Yeah, I understand that after I create a child compiler I can do anything I want with it. But it's not obvious which plugins are enabled by default and which are not. For example, you have to know that `createChildCompiler` does not copy `thisCompilation` and you have to know that the `SplitChunksPlugin` uses `thisCompilation`. It just seemed surprisingly manual to create a child compiler that can replicate the parent compilation.

The docs say:

> It copies _**all**_ hooks and plugins from the parent (or top-level compiler) and creates a child Compiler instance.
> https://webpack.js.org/api/compilation-object/#createchildcompiler

But that's not true since many hooks, including hooks for important features like code splitting, are not copied over default. It seems like what gets copied over by default is mostly coincidental. Maybe this is just a documentation issue.

I can close this issue if this is considered working as designed but I do have a couple of related questions if you don't mind answering:

- Does a child compiler seem like the right solution to this problem? That is, creating a duplicate compilation of the same input but with different `optimization` options.
- What are the benefits of using a child compiler instead of configuring a `MultiCompiler` for this use case?

I'm happy to submit a PR with better `createChildCompiler` documentation once I have a better understanding.

Thanks again.

**Comment by sokra** [comment]
Not all plugins are copied to the child compiler. e. g. target and environment specific plugins are not copied, as the child compilation bundle usually run in a different target/environment.

I'm not aware of any limitation that comes with code splitting and child compilers. They should be able to use code splitting as usual. Without example is different to see what kind of problem you are running into?

**Comment by sokra** [comment]
btw. for independent builds for client and tests you are better using multiple configurations instead of a child compiler. The child compiler is intended to be used when the child compiler output should be referenced in the main compilation.

**Comment by gusvargas** [comment]
> Not all plugins are copied to the child compiler. e. g. target and environment specific plugins are not copied, as the child compilation bundle usually run in a different target/environment.

I'll submit a PR so that's more clear in the docs.

> I'm not aware of any limitation that comes with code splitting and child compilers. They should be able to use code splitting as usual.

It's not a limitation with the child compiler. It was just a surprising design decision in the `createChildCompiler` API. Code splitting only works if you configure the child compiler with the `JsonpTemplatePlugin`.

Here is an example: https://github.com/gusvargas/webpack-child-compiler-code-splitting

I ran the build with `yarn webpack --mode development --plugin ./ChildCompilerPlugin.js`

The resulting split chunk looks like this: https://github.com/gusvargas/webpack-child-compiler-code-splitting/blob/master/dist/child-0.js
But I expect: https://github.com/gusvargas/webpack-child-compiler-code-splitting/blob/master/dist/0.js#L1
This line needs to be uncommented: https://github.com/gusvargas/webpack-child-compiler-code-splitting/blob/master/ChildCompilerPlugin.js#L13

@prateekbh Also wrote about this detail in his article

> Step 4: Discover that the chunks are not being fetched.
https://medium.com/@prateekbh/my-experience-writing-a-webpacks-child-compiler-plugin-a1237c175947

Anyway, it's easy to work around by simply applying the `JsonpTemplatePlugin` plugin and the default behavior makes more sense now that you're saying that target and environment specific plugins are not copied as an explicit decision – since code splitting is a browser concern I understand why it doesn't work by default.

> btw. for independent builds for client and tests you are better using multiple configurations instead of a child compiler.

Thank you for the suggestion. My concern with using multiple configurations is that it would dramatically increase by build time – my build time is currently several minutes long. Adding a separate build configuration for a test bundle, where a lot of the input source is the same as the client build, seems  wasteful since it would make webpack repeat a lot of work. With the child compiler, it looks like at minimum the [`inputFilesystem` and `resolveFactory` are shared across compilers](https://github.com/webpack/webpack/blob/v4.27.1/lib/Compiler.js#L455-L457). Is there a recommended way of using multiple configurations while also sharing work/cache between them?

**Comment by alexander-akait** [comment]
Do you try https://webpack.js.org/configuration/other-options/#cachetype? (filesystem)?

**Comment by gusvargas** [comment]
That's interesting but it doesn't look like it's supported in webpack 4: https://v4.webpack.js.org/configuration/other-options/#cache

**Comment by alexander-akait** [comment]
Maybe it is worth to consider to migrate on webpack@5 (there are a lot of other improvements)...

**Comment by gusvargas** [comment]
That's something that we would love to do soon but I was curious what the best solution today would look like.

It sounds like our best bet might just be to run these builds in parallel so that build times don't suffer too much. I'll close this issue but I'm happy to hear any other thoughts if you have them.

I'll open a documentation PR soon to add more details about the `createChildCompiler` API.

**Comment by alexander-akait** [comment]
@gusvargas for the future, maybe you can provide your profile file and we will look how we can improve perf

**Comment by gusvargas** [comment]
Thanks, @alexander-akait .
