### ISSUE TITLE
buildDependencies not working as expected.

### ISSUE THREAD

**Issue by chenxsan** [webpack/webpack#12195]
# Bug report

**What is the current behavior?**

See pull request here https://github.com/webpack/webpack.js.org/pull/4311

I'm `require`ing a file in webpack configuration, but change to `require`ed file doesn't invalidate the cache as per https://github.com/webpack/changelog-v5/blob/master/guides/persistent-caching.md#build-dependencies.

Here's the related configuration for `cache`:

```
  cache: {
    type: 'filesystem',
    buildDependencies: {
      config: [__filename],
    },
    cacheDirectory: path.resolve(__dirname, '.cache/webpack')
  },
```

**If the current behavior is a bug, please provide the steps to reproduce.**

1. clone code from `https://github.com/webpack/webpack.js.org/pull/4311`
2. run `yarn` then `yarn fetch:supporters` and `yarn start`
3. open http://localhost:3000/api/cli/#configuration-options
4. change `-` to `*` here https://github.com/webpack/webpack.js.org/pull/4311/files#diff-53da17d70729ef08abbe0bc80f4cf2a701f0447084bf69be87873f5a064512e4R13
5. `ctrl-c` twice to stop dev server and run `yarn start` again
6. refresh `http://localhost:3000/api/cli/#configuration-options`, you can find `-` still there while i was expecting `*`.

**What is the expected behavior?**

Right now I have to run `rm -rf .cache/webpack` to clean up the cache.

**Other relevant information:**
webpack version:  5.10.1
Node.js version: 14.15.0
Operating System: macOS Big Sur
Additional tools:

**Comment by alexander-akait** [comment]
You need to add `webpack.common.js ` to `buildDependencies` too

**Comment by alexander-akait** [comment]
Also I think you need to add `babel.config.js` and other config files (involved in bundle)

**Comment by sokra** [comment]
There seem to be something wrong here...

**Comment by sokra** [comment]
There are two bugs here. One in webpack and one in webpack-cli.

The webpack-cli bug is hit first. It adds `"webpack.dev.js"` to `cache.buildDependencies.config` because it's passed as `--config`. The problem is that this can't be resolved for multiple reasons, it's not prefixed with `./` and it's not relative to `options.context`. Anyway, webpack-cli should pass an absolute path.

Side note: It would also be better if webpack-cli applies a default and not force-add the config file. 
``` js
if(options.cache.buildDependencies.defaultConfig === undefined) options.cache.buildDependencies.defaultConfig = [absPathToConfig];
```

instead of

``` js
if(options.cache.buildDependencies.config === undefined) options.cache.buildDependencies.config = []; options.cache.buildDependencies.config.push(config);
```

---

So the resolving fails and with it fails the caching. A warning it printed to the output.

But the second build ignores the failing buildDependencies from the first run and just stores the cache without buildDependencies. This shoud not happen in webpack.

**Comment by alexander-akait** [comment]
@sokra 
> The webpack-cli bug is hit first. It adds "webpack.dev.js" to cache.buildDependencies.config because it's passed as --config. The problem is that this can't be resolved for multiple reasons, it's not prefixed with ./ and it's not relative to options.context. Anyway, webpack-cli should pass an absolute path.

Fixed, I hope I will do release today/tomorrow

**Comment by alexander-akait** [comment]
> Side note: It would also be better if webpack-cli applies a default and not force-add the config file.

in todo

**Comment by chenxsan** [comment]
Guess that explains why I saw this error when running the documentation site locally:

> <w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Can't resolve 'webpack.dev.js' in '/Users/sam/Documents/githubRepos/webpack.js.org/src'
<w> while resolving 'webpack.dev.js' in /Users/sam/Documents/githubRepos/webpack.js.org/src as file

**Comment by alexander-akait** [comment]
Yep, fixed

**Comment by chenxsan** [comment]
I've tested the code with the latest webpack and it works as expected now, I think the warning regarding `Can't resolve 'webpack.dev.js'` could be fixed in another `webpack-cli` release, hence I'm closing this issue.
