### ISSUE TITLE
Compute `ModuleFederationPlugin`s remotes' URLs in the runtime

### ISSUE THREAD

**Issue by jazzfog** [webpack/webpack#12217]
With the `remotes` property we define where to pull remotes from:
```js
remotes: {
  widget: `widget@http://localhost:3001/remoteEntry.js`,
},
```

It is possible to alternate the URL during the build
```js
remotes: {
  widget: `widget@${isDev ? 'http://localhost:3001' : '/apps/widgets'}/remoteEntry.js`,
},
```
Though it seems like there is no way to define the remote's URL dynamically in runtime.
 
I would imagine it like this:
```js
remotes: {
  widget: () => {
    const prefix = location.host.startsWith('eu.') ? 'europe' : 'us';
    return `widget@${prefix}/apps/widgets/remoteEntry.js`
  },
},
```

It would be really useful to have such an option.

_Originally posted by @jazzfog in https://github.com/webpack/webpack/discussions/12213_

**Comment by Rinaldo** [comment]
@jazzfog There is a dynamic remote api which allows you to set the url at runtime. [Example](https://github.com/webpack/webpack/issues/11944#issuecomment-747082733)

**Comment by jazzfog** [comment]
@Rinaldo, thanks for the example!
It does seem like this solution can solve the problem of inclusion of a component. 

Though it looks like this way we include in the async manner, unlike default way of doing it which for developer feels like synchronous.

It is not a big deal for a component that we can place on the app once it is ready but If I want to include some constants/functions and use them in my code immediately - it looks like I can't do that because I need to wait for the promise to resolve.

Please, let me know If I misunderstood it.

**Comment by Rinaldo** [comment]
@jazzfog
Dynamic imports always return promises, so the module will be loaded asynchronously whether you use the `import('module')` syntax or the example I linked above

**Comment by jazzfog** [comment]
@Rinaldo, I am not 100% sure how it works under the hood but Module Federation can provide experience that looks and feels like synchronous imports. See [router imports example](https://github.com/module-federation/module-federation-examples/blob/master/shared-routes2/app1/src/App.js).

```
import remoteRoutes from "app2/routes";

const routes = [...localRoutes, ...remoteRoutes];

...

{routes.map((route) => (
  <Route
    key={route.path}
    path={route.path}
    component={route.component}
    exact={route.exact}
  />
))}
```

It would be great to be able to write code like this and at the same time be able to define the remote URL for the `app2` in runtime. To be honest I do not see any fundamental obstacles for that, hole the webpack team can implement it.

**Comment by jazzfog** [comment]
Still think it'd be a useful feature.

**Comment by rere252** [comment]
+1

**Comment by Pavanbn03** [comment]
> +1

**Comment by Pavanbn03** [comment]
> With the `remotes` property we define where to pull remotes from:
> 
> ```js
> remotes: {
>   widget: `widget@http://localhost:3001/remoteEntry.js`,
> },
> ```
> 
> It is possible to alternate the URL during the build
> 
> ```js
> remotes: {
>   widget: `widget@${isDev ? 'http://localhost:3001' : '/apps/widgets'}/remoteEntry.js`,
> },
> ```
> 
> Though it seems like there is no way to define the remote's URL dynamically in runtime.
> 
> I would imagine it like this:
> 
> ```js
> remotes: {
>   widget: () => {
>     const prefix = location.host.startsWith('eu.') ? 'europe' : 'us';
>     return `widget@${prefix}/apps/widgets/remoteEntry.js`
>   },
> },
> ```
> 
> It would be really useful to have such an option.
> 
> _Originally posted by @jazzfog in #12213_

**Comment by vankop** [comment]
remotes basically are external modules, you can use `promise` external see webpack test case for that https://github.com/webpack/webpack/blob/main/test/configCases/container/circular/webpack.config.js
