### ISSUE TITLE
Node API: Watching: A 'callback' argument need to be provided 

### ISSUE THREAD

**Issue by mattkrick** [webpack/webpack#12218]
# Bug report

**What is the current behavior?**
```
(node:32284) [DEP_WEBPACK_WATCH_WITHOUT_CALLBACK] DeprecationWarning: A 'callback' argument need to be provided to the 'webpack(options, callback)' function when the 'watch' option is set. There is no way to handle the 'watch' option without a callback.
```

**If the current behavior is a bug, please provide the steps to reproduce.**
```js
const compileServers = () => {
  return new Promise((resolve) => {
    const config = require('./webpack/dev.servers.config')
    const compiler = webpack(config)
    compiler.watch(true, () => {
      resolve()
    })
  })
}
```

**What is the expected behavior?**
The code above worked in v4 & looking at the docs (https://webpack.js.org/api/node/#watching), it seems it should work in v5, too.

**Other relevant information:**
webpack version:  5.10.3
Node.js version: 15
Operating System: macos
Additional tools:

**Comment by sokra** [comment]
Your config contains `watch: true` and that is deprecated as it has no effect for `webpack(config)`. Instead watching or not is indicated by you calling `watch()` or `run()`. You are correctly calling `watch()` after that and there is no behavior change with that from v4 to v5.

We added a deprecating warning as is might be confusing for people using `webpack({ ..., watch: true })` and expecting that this would watch something (which is don't do).

**Comment by mattkrick** [comment]
that makes perfect sense. thank you!
would be happy to PR that error message or the docs, just let me know which.

**Comment by sokra** [comment]
Documentation contributions are always very welcome
