### ISSUE TITLE
tsconfig-paths-webpack-plugin doesn't work with webpack5

### ISSUE THREAD

**Issue by gespiton** [webpack/webpack#12219]
# Bug report
I'm not sure if this is a breaking change or a bug. But I can't find related info so I will submit this issue here and hope someone could look into this.

The problem I encounter is when using tsconfig-paths-webpack-plugin with webpack version 5.10.0.
when this plugin try to resolve a dependency according to tsconfig.paths, the required file path will become the file that exist in the main src folder. 
```
/***/ "../packages/fullscreen/src/entry.ts":
/*!*******************************************!*
  !*** ../packages/fullscreen/src/entry.ts ***!
  \*******************************************/
/***/ ((__unused_webpack_module, exports, __webpack_require__) => {

"use strict";

function __export(m) {
    for (var p in m) if (!exports.hasOwnProperty(p)) exports[p] = m[p];
}
Object.defineProperty(exports, "__esModule", ({ value: true }));
console.log('packages/fullscreen/src/entry.ts loaded');
__export(__webpack_require__(/*! ./test */ "./src/test.ts"));
```

noted that on the last line, the file path is ./src/test.ts, which resolves to the file application/src/test.ts. While the correct resolve path should be like ../packages/fullscreen/src/test.ts (which it is in webpack 4). View the full repo [here](https://github.com/gespiton/tsconfigplugin-issue-with-webpack-5) 

 Here is a related StackOverflow question https://stackoverflow.com/questions/60907111/using-tsconfig-paths-webpack-plugin-gives-module-not-found-error-for-fs-and. 

**What is the current behavior?**
resolve packages path to main app path

**If the current behavior is a bug, please provide the steps to reproduce.**
1. download the code in https://github.com/gespiton/tsconfigplugin-issue-with-webpack-5
2. follow the readme to run the demo
3. open browser and check the console.

**What is the expected behavior?**
resolve to correct path when import from packages/**

**Other relevant information:**
webpack version:  5.10.0
Node.js version: 12.0.0
Operating System: macos
Additional tools: tsconfig-paths-webpack-plugin version: 3.3.0

**Comment by sokra** [comment]
Please report that to tsconfig-paths-webpack-plugin

**Comment by gespiton** [comment]
I've submitted an issue on tsconfig-paths-webpack-plugin as well. But that repo seems not as active and I'm afraid this is a problem inside webpack.

Anyway. For now, I will use webpack's resolve.alias instead of the plugin.
