### ISSUE TITLE
clean-webpack-plugin should be an internal webpack plugin

### ISSUE THREAD

**Issue by yoavain** [webpack/webpack#12221]
## Feature request

**What is the expected behavior?**
1. `clean-webpack-plugin` should work with TypeScript configuration
2. `clean-webpack-plugin` should be maintained since it is recommended in the documentation:
https://webpack.js.org/guides/output-management/#cleaning-up-the-dist-folder

**What is motivation or use case for adding/changing the behavior?**
1. Last version of `clean-webpack-plugin` was published in May 2019
2. There's a typing bug in that repo from October 2019 that is not addressed and prevent using TypeScript configuration:
https://github.com/johnagan/clean-webpack-plugin/issues/188

**How should this be implemented in your opinion?**
Repo should be forked and published as an internal webpack plugin.
Alternatively, recommend a different plugin that can work with TypeScript

**Are you willing to work on this yourself?**
maybe

**Comment by sokra** [comment]
Yes, we are actually planning to make this an integrated feature with `output.clean: true`, but we are not there yet.

see #11561

**Comment by alexander-akait** [comment]
Improved https://github.com/webpack/webpack/pull/11561
