### ISSUE TITLE
Question: ~ instead of node_modules

### ISSUE THREAD

**Issue by thaiat** [webpack/webpack#1222]
Is there any good reason for webpack to replace the node_modules folder by ~?
this is a bit annoying when displaying stats or using source maps...

Example of stats:
```bash
Version: webpack 1.10.1
Time: 1829ms
              Asset     Size  Chunks             Chunk Names
    ./src/bundle.js  1.07 MB       0  [emitted]  main
./src/bundle.js.map  1.24 MB       0  [emitted]  main
   [3] ./src/controllers/home.js 1.32 kB {0} [built]
   [0] ./src/main.js 139 bytes {0} [built]
   [2] ./~/angular/angular.js 1.04 MB {0} [built]
   [1] ./~/angular/index.js 48 bytes {0} [built]
```

**Comment by sokra** [comment]
It's shorter.

**Comment by thaiat** [comment]
shorter sure, but it's also not a existing folder. 
is there a way to deactivate the shortening especially in sourcemaps ;) ?

**Comment by thaiat** [comment]
@sokra i think i have a potential solution for this:
in `ModuleFilenameHelpers.js` in the function `createFileName` i check if moduleFilenameTemplate is a function and call it with the module and the resolved infos.

Then in the webpack.config.js i can define a function for output.devtoolModuleFilenameTemplate and return whatever i want.

in addition all the templates could accept function(devtoolFallbackModuleFilenameTemplate, there may be other...)

I can make a PR, let me know

**Comment by sokra** [comment]
You can use this:

``` js
output.devtoolModuleFilenameTemplate: "file:///[absolute-resource-path]",
output.devtoolFallbackModuleFilenameTemplate: "file:///[absolute-resource-path]?[hash]",
```

http://webpack.github.io/docs/configuration.html#output-devtoolmodulefilenametemplate

**Comment by thaiat** [comment]
yep tried it already but that's not enough.
I need the source map to be in their exact location, so it is easy to locate the sources when i'm debugging.
the real need is to be able to transform the filename instead of just a static template.

there is an different issue referencing the exact same need here : #782

My PR has been submited here : #1224

**Comment by bebraw** [comment]
Closing given #1224 was merged.
