### ISSUE TITLE
The default values of code and document are inconsistent

### ISSUE THREAD

**Issue by YuFy1314** [webpack/webpack#12222]
https://github.com/webpack/webpack/blob/10ad4e95b850bbe20019275fd1d364666c4b69ea/lib/optimize/SplitChunksPlugin.js#L594

![](https://user-images.githubusercontent.com/24446694/102455399-82d33680-407a-11eb-9665-76779273e92d.png)

**Comment by YuFy1314** [comment]
webpack-5 and documentation

**Comment by sokra** [comment]
The defaults come from here:

https://github.com/webpack/webpack/blob/41db807b9cb20d0be77c0c3b1b5e5b1fd1d20b8e/lib/config/defaults.js#L894-L895

**Comment by YuFy1314** [comment]
> The defaults come from here:
> 
> https://github.com/webpack/webpack/blob/41db807b9cb20d0be77c0c3b1b5e5b1fd1d20b8e/lib/config/defaults.js#L894-L895

Thank you for your answer
