### ISSUE TITLE
FileSystemInfo can not createSnapshot with symbol link

### ISSUE THREAD

**Issue by killagu** [webpack/webpack#12246]
# Bug report

**What is the current behavior?**
I install deps with [npminstall](https://github.com/cnpm/npminstall)(it can install faster), but the file tree in `node_modules` is special bacause npminstall install pkgs with symbol link to download and write less files.

The file tree looks like this
```
app
├── index.js
└── node_modules
    ├── _a@1.0@a(real dir)
    |   ├── index.js
    |   └── node_modules
    |       └── b(symbol link to app/node_modules/_b@1.0@b)
    ├── _b@1.0@b(real dir)
    |   ├── index.js
    |   └── node_modules
    |       └── a(symbol link to app/node_modules/_a@1.0@a)
    ├── a(symbol link to app/node_modules/_a@1.0@a)
    └── b(symbol link to app/node_modules/_b@1.0@b)
```

Because of a,b is reference by each other, `contextTimestampQueue` and `contextHashQueue` in `FileSystemInfo` will never reach the end.

**If the current behavior is a bug, please provide the steps to reproduce.**

The minimal reproduction repo is [here](https://github.com/killagu/npminstall_webpack).
The reproduce step is 
```shell
git clone git@github.com:killagu/npminstall_webpack.git
cd npminstall_webpack
npm i -g cnpm
# must use cnpm install
cnpm i
npm run build
```

Build snapshow will fail.

**What is the expected behavior?**
- Use `fs.lstat` to get file info, and use target path to process.
- Skip files if has been processed

**Other relevant information:**

webpack version:  5.11.0
Node.js version: 12.16.3
Operating System: macOS Big Sur 11.0.1 (20B29) 

If it is ok, I'm happy to make a pr to fix it.

**Comment by alexander-akait** [comment]
Yep bug

**Comment by killagu** [comment]
@alexander-akait Thanks for confirm, I can have a try to fix it.

**Comment by alexander-akait** [comment]
Other example with symlinks https://github.com/webpack/webpack/issues/12503#issue-793467072

**Comment by alexander-akait** [comment]
Another example https://github.com/webpack/webpack/issues/12810

**Comment by alexander-akait** [comment]
bump

**Comment by iperzic** [comment]
Do we have an ETA on when this might be fixed?

**Comment by alexander-akait** [comment]
https://github.com/webpack/webpack/pull/14019

**Comment by qiqiboy** [comment]
Hi @sokra, I found that some specific libs will still cause the snapshot to fail in `v5.52.0`, such as `video.js`. Install `video.js` in the above reproduction repo, and it can be reproduced after running.

```bash
git clone git@github.com:killagu/npminstall_webpack.git
cd npminstall_webpack
npm i -g cnpm
# must use cnpm install
cnpm i
# NEW: install the video.js library
cnpm install video.js -S
npm run build

<--- JS stacktrace --->

FATAL ERROR: invalid array length Allocation failed - JavaScript heap out of memory
```

**Comment by alexander-akait** [comment]
@qiqiboy update wepback to the latest stable version

**Comment by qiqiboy** [comment]
> @qiqiboy update wepback to the latest stable version

Yes, I have tried, but still fail.
```bash
cnpm install video.js webpack@latest -S
npm run build
```

The problam is still

**Comment by alexander-akait** [comment]
Can't reproduce the problem

**Comment by qiqiboy** [comment]
@alexander-akait my env info: 
```bash
$ cnpm -v                                
cnpm@7.0.0 (/usr/local/lib/node_modules/cnpm/lib/parse_argv.js)
npm@6.14.15 (/usr/local/lib/node_modules/cnpm/node_modules/npm/lib/npm.js)
node@14.17.5 (/usr/local/bin/node)
npminstall@5.0.2 (/usr/local/lib/node_modules/cnpm/node_modules/npminstall/lib/index.js)
prefix=/usr/local 
darwin x64 20.3.0 
registry=https://registry.nlark.com
```
<img width="738" alt="截屏2021-09-09 20 33 42" src="https://user-images.githubusercontent.com/3774036/132686910-a4a36fa1-5a08-4849-b46a-fadb3ac474bf.png">

**Comment by alexander-akait** [comment]
Increase your memory usage, file is so bug, not related to this problem
