### ISSUE TITLE
v5.x.x buid error

### ISSUE THREAD

**Issue by zehavibarak** [webpack/webpack#12243]
# Bug report

Build fails in all 5.x, works in 4.44.2.

Yield:

> Error: ./node_modules/my-package/assets/themes/default.min.css
> Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
> TypeError: Cannot read property 'tapAsync' of undefined
>     at ExternalModuleFactoryPlugin.apply (\node_modules\webpack\lib\ExternalModuleFactoryPlugin.js:41:39)
>     at \node_modules\webpack\lib\ExternalsPlugin.js:30:63
>     at SyncHook.eval [as call] (eval at create (\node_modules\@angular-devkit\build-angular\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:1)
>     at SyncHook.lazyCompileHook (\node_modules\@angular-devkit\build-angular\node_modules\tapable\lib\Hook.js:154:20)
>     at \node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compiler.js:665:23
>     at AsyncSeriesHook.eval [as callAsync] (eval at create (\node_modules\@angular-devkit\build-angular\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
>     at AsyncSeriesHook.lazyCompileHook (\node_modules\@angular-devkit\build-angular\node_modules\tapable\lib\Hook.js:154:20)
>     at Compiler.compile (\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compiler.js:662:28)
>     at Compiler.runAsChild (\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compiler.js:328:8)
>     at Object.pitch (\node_modules\mini-css-extract-plugin\dist\loader.js:121:17)
>  @ multi ./src/styles.scss ./node_modules/my-package/assets/themes/default.min.css styles[1]
> 
> Error: ./src/styles.scss
> Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
> TypeError: Cannot read property 'tapAsync' of undefined
>     at ExternalModuleFactoryPlugin.apply (\node_modules\webpack\lib\ExternalModuleFactoryPlugin.js:41:39)
>     at \node_modules\webpack\lib\ExternalsPlugin.js:30:63
>     at SyncHook.eval [as call] (eval at create (\node_modules\@angular-devkit\build-angular\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:7:1)
>     at SyncHook.lazyCompileHook (\node_modules\@angular-devkit\build-angular\node_modules\tapable\lib\Hook.js:154:20)
>     at \node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compiler.js:665:23
>     at AsyncSeriesHook.eval [as callAsync] (eval at create (\node_modules\@angular-devkit\build-angular\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
>     at AsyncSeriesHook.lazyCompileHook (\node_modules\@angular-devkit\build-angular\node_modules\tapable\lib\Hook.js:154:20)
>     at Compiler.compile (\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compiler.js:662:28)
>     at Compiler.runAsChild (\node_modules\@angular-devkit\build-angular\node_modules\webpack\lib\Compiler.js:328:8)
>     at Object.pitch (\node_modules\mini-css-extract-plugin\dist\loader.js:121:17)
>  @ multi ./src/styles.scss ./node_modules/my-package/assets/themes/default.min.css styles[0]
> 

**Other relevant information:**
webpack version:  5.11.0
Node.js version: 15.3.0
Operating System: Win64
Additional tools: ng cli

**Comment by csvan** [comment]
This is almost certainly a problem with your CSS loader. Are you using a version which is compatible with webpack 5?

**Comment by zehavibarak** [comment]
> This is almost certainly a problem with your CSS loader. Are you using a version which is compatible with webpack 5?

Which are?

**Comment by alexander-akait** [comment]
Please update mini-css-extract-plugin to the latest version, nothing to fix on webpack side
