### ISSUE TITLE
Production mode build fails with experiments.outputModule: true together with optimization.runtimeChunk: 'single'

### ISSUE THREAD

**Issue by ludofischer** [webpack/webpack#12244]
# Bug report

**What is the current behavior?**
Running webpack-cli prints the following error:
```
ERROR in runtime.js from Terser
'return' outside of function [runtime.js:130,9]
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Reproduction repository: https://github.com/ludofischer/webpack-outputmodule-bug
1. Create this `webpack.config.js`:

```javascript
module.exports = {
    experiments: {outputModule: true},
    mode: 'production',
    optimization: {
      runtimeChunk: 'single'
    }
}
```
2. Install webpack and webpack-cli
3. Place your source in `src/index.js` 
4. run `npx webpack`

**What is the expected behavior?**
I think either:
1. output just the minified application code in `dist/`
2. output the minified application code and a minified webpack runtime
3. give an error message saying  `runtimeChunk: 'single'` is useless with `outputModule: true` 

I am not sure about the expected behaviour because I don't know whether the webpack runtime is ever needed with `outputModule: true`. 

**Other relevant information:**
The code builds if we change `mode: production` to `mode: 'development'` in `webpack.config.js`. 
I see that without `runtimeChunk: 'single'`, the runtime is not included in the bundle .

webpack version:  5.11
Node.js version: v14.15.1
Operating System: Fedora 33
Additional tools: none

**Comment by leepowelldev** [comment]
Also seeing this - also, when using this experiment, I'm not seeing any difference in output. I've gotten around the reported bug by disabling minification to inspect the final output. It looks just the same as not using the setting. Maybe I'm missing something?

**Comment by alexander-akait** [comment]
Yes, it is bug, we need to fix it
