### ISSUE TITLE
compileBooleanMatcher fails when prefix and suffix overlap

### ISSUE THREAD

**Issue by izaera** [webpack/webpack#12255]
# Bug report

**What is the current behavior?**

Currently, the [compileBooleanMatcher](https://github.com/webpack/webpack/blob/master/lib/util/compileBooleanMatcher.js#L23) function is being fooled when the common prefix and suffix of two expressions overlap. This, in turn, leads to incorrect code being generated by [JsonpChunkLoadingRuntimeModule](https://github.com/webpack/webpack/blob/af52c8f0457b1055098d6b7b545b257404d06c93/lib/web/JsonpChunkLoadingRuntimeModule.js#L144) which, in my case, tries to load a consumed module as if it had been bundled locally, thus making the web server return a `Not found` error and failing the page load.

**If the current behavior is a bug, please provide the steps to reproduce.**

I cannot send a small test project to reproduce it because:

1. [My project](https://github.com/liferay/liferay-portal) setup is huge and I'm working in a current development locally.
2. I'm not quite sure how it could be reproduced in a small project because it depends on the dependency graph and federation config.

Anyway, I'm going to fix this in a following PR with a test, where it is easy to see why the production code was wrong and, looking at the test, what I was expecting to work correctly.

**What is the expected behavior?**

The expected behavior is that the computed regexp matches the setup correctly (see the unit test in the associated PR).

**Other relevant information:**
webpack version:  5.11.0
Node.js version: 12.16.3
Operating System: ArchLinux
Additional tools: yarn 1.22.4

**Comment by alexander-akait** [comment]
Thanks for the issue and the PR :star:

**Comment by izaera** [comment]
Hi webpack team:

May I ask what is the release policy of the project? We are having some discussions around using a temporary patched webpack version for our project until the new release fixing this issue happens, but we are unsure it is worth the hassle, as it looks you release very often :-). 

However, I would like to know if you have a fixed cadence, or do it on demand, or simply when you have time to do it.

Thanks in advance and also thanks for the great work you do.

**Comment by alexander-akait** [comment]
Release will be after holidays

**Comment by izaera** [comment]
Perfect, then. Thanks :+1:
