### ISSUE TITLE
Wasm loading should fallback to `instantiate` if `instantiateStreaming` fails due to incorrect MIME type

### ISSUE THREAD

**Issue by Herschel** [webpack/webpack#12259]
## Feature request

**What is the expected behavior?**
When using a Wasm file with `experiments.(a)syncWebAssembly: true`, the Wasm module will fail to load if the server does not serve the file with the application/wasm MIME type:
`TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'`

Source that instantiates the Wasm:
https://github.com/webpack/webpack/blob/af52c8f0457b1055098d6b7b545b257404d06c93/lib/wasm-sync/WasmChunkLoadingRuntimeModule.js#L304-L311

The loader could detect this and attempt to fallback to `WebAssembly.instantiate` in this case so that the app can continue to function.

Compare the behavior of the loading code in `wasm-bindgen`:
https://github.com/rustwasm/wasm-bindgen/blob/b584407a46a1b9f517d0f606fff954aaa079fa6b/crates/cli-support/src/js/mod.rs#L684-L710

**What is motivation or use case for adding/changing the behavior?**
This would allow the app to continue to work in cases where the server is not configured for the proper MIME type and is not easily configurable.

**How should this be implemented in your opinion?**
Catch the error thrown when trying to `instantiateStreaming`, possibly inspect `response.headers`, and fall back to `WebAssembly.instantiate`.

**Are you willing to work on this yourself?**
No

**Comment by xtuc** [comment]
it means that your webserver doesn't set the proper mime type when serving wasm. You should consider upgrading to the latest version

**Comment by Herschel** [comment]
The issue is my application is hosted by end-users on their own server; often their server is not configurable (hosted by a third party) or they lack the knowledge to do so. As serving with the proper MIME type still seems to be the exception, not the norm this is [https://github.com/ruffle-rs/ruffle/issues/506](the number one support request) for my app [despite significant effort in documentation](https://github.com/ruffle-rs/ruffle/wiki/Using-Ruffle#configure-webassembly-mime-type). So it seems like it'd be useful to fall back to in this case, possibly logging a warning to the console.

**Comment by alexander-akait** [comment]
bump
