### ISSUE TITLE
Webpack 4.44 FATAL ERROR: JavaScript heap out of memory

### ISSUE THREAD

**Issue by kevzettler** [webpack/webpack#12252]
# Bug report

**What is the current behavior?**
I have a project in which I run webpack dev server and a webpack watch command

```
    "dev-client": "npx webpack-dev-server --mode development --config config/webpack.config.js",
    "dev-server": "npx webpack --watch --progress --config ./config/webpack.server.config.js"
```
Both of these webpack instances will quickly and correctly build on the first initial run. However subsequent runs will take a long time and then usually crash with a heap out of memory fatal error.

`FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory `

This seems exacerbated when I rapidly edit and save a file triggering further re-compiles as if they almost queue up and run out of memory.

**If the current behavior is a bug, please provide the steps to reproduce.**
I have created a repo that reproduces the issue at: https://github.com/kevzettler/webpack-memory-leak/tree/master

I have limited the repo just to the `dev-client` `webpack-dev-server` case. You can install dependencies and run. then go and edit white space in any the files multiple times and it should crash. 

I am using a bunch of exotic loaders in this project and suspect it might be related to one of them. Any guidance on further investigation would be much appreciated.

I'm using the following dependency versions

```
Node: v12.18.1 *
NPM: 6.14.8
```

```
hypeworks@0.0.1 /Users/kevzettler/code/webpack-memory-leak
├─┬ threads@1.6.3 -> /Users/kevzettler/code/threads.js
│ └── webpack@4.41.4  extraneous
└── webpack@4.44.2
```

The 2 versions of `webpack` one within the `threads` loader is suspicious...

**What is the expected behavior?**

Webpack should not crash after re-compiling updates. This seems to be aggravated when i'm rapidly editing and saving files. 

**Other relevant information:**
webpack version:  
```hypeworks@0.0.1 /Users/kevzettler/code/webpack-memory-leak
├─┬ threads@1.6.3 -> /Users/kevzettler/code/threads.js
│ └── webpack@4.41.4  extraneous
└── webpack@4.44.2
```
Node.js version:  v12.18.1
Operating System: macOS Mojave: `Darwin kevs-mbp.lan 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64`
Additional tools: Typescript 4.0.3

**Comment by alexander-akait** [comment]
Bug in `ThreadsPlugin`, please report them

**Comment by kevzettler** [comment]
Thank you @alexander-akait any further detail I can give `threads-plugin` ? they are suggesting it is not an issue

**Comment by alexander-akait** [comment]
Something is not flushed, maybe you can provider profile file?

**Comment by kevzettler** [comment]
@alexander-akait I'm not sure what you mean when you say 'profile' file are you talking about like chrome-dev tools stack trace profile?

**Comment by alexander-akait** [comment]
> chrome-dev tools stack trace profile

Yep

**Comment by kevzettler** [comment]
@alexander-akait how did you decide that it was an issue with the `threads-plugin` what evidence led you to that conclusion?

**Comment by alexander-akait** [comment]
try to do not use this plugin
