### ISSUE TITLE
Invalid arguments: 'delay' error

### ISSUE THREAD

**Issue by amilcar-infante** [webpack/webpack#1225]
The current version (1.8.11) is throwing an error in NodeWatchFileSystem,js file (line 29) in the NodeWatchFileSystem.prototype.watch method

if(typeof delay !== "number")
    throw new Error("Invalid arguments: 'delay'");

According our research the delay parameter, which is expected as a number, is in fact an object as you can see below: 
{ aggregateTimeout: 200 }

We used the same version in a previous project and this issues wasn't throwed there so it's posible that some change in the way delay is built introduced this error. 

Thanks

**Comment by gihrig** [comment]
> The current version (1.8.11) is throwing an error in NodeWatchFileSystem,js file (line 29) in the NodeWatchFileSystem.prototype.watch method

Latest as of July-8-2015, is 1.10.1 - solved that error for me :-)

    "webpack": "1.10.1", "
     "webpack-dev-server": "1.10.1"

**Comment by amilcar-infante** [comment]
Excellent, thanks gihrig!!!
