### ISSUE TITLE
Federated Modules: Dynamic Remotes with synchronous imports

### ISSUE THREAD

**Issue by ksrb** [webpack/webpack#12258]
### Feature request

**What is the current behavior?**
Using code from https://github.com/webpack/webpack/issues/11033 it is possible to load code in with dynamic urls asynchronously, however the given solution does not work with 'synchronous' imports for example:

```js
import urls from "remoteModule/constants";

async function getSomething(params) {
  // ...Other processing
  return fetch(urls.aThing);
}
```

The code above would have to be converted to:
```js
async function getSomething(params) {
  const { aThing } = await someKindOfDynamicLoading("remoteModule/constants");
    // ...Other processing
  return fetch(urls.aThing);
}
```

This doesn't seem ideal especially for non-jsx code or 'middleware-like' code.

**What is the expected behavior?**
See above?

**What is motivation or use case for adding/changing the behavior?**
Not all code needs/wants the async loading of code to be 'apparent' like the example above but another example might be a set of constants that builds off another set of constants.

**How should this be implemented in your opinion?**
I'm not sure to be honest, I would imagine something would 'hook' into the webpack internals before the async boundary for example:
```js
(async () => {
  await loadModules();
  import("./index");
})();
```

**Are you willing to work on this yourself?**
Maybe, but I would require quite a bit of assistance as I'm unfamiliar with webpack internals.

**Comment by alexander-akait** [comment]
I think it is impossible, because loading is async

> I'm not sure to be honest, I would imagine something would 'hook' into the webpack internals before the async boundary for example:

We can't violate ES modules spec and change logic for `import`

**Comment by sokra** [comment]
You should be able to do it with the following:

``` js
new ModuleFederationPlugin({
  remotes: {
    remoteModule: "internal ./module-to-load-remote.js"
  }
})
```

``` js
// module-to-load-remote.js
module.exports = (async () => {
  const container = await someKindOfDynamicLoading();
  return container;
})();
```

``` js
// usage as usual
import urls from "remoteModule/constants";
```

This delegates the loading of the container to some internal logic.

**Comment by alexander-akait** [comment]
Answer above, feel free to feedback

**Comment by alexander-akait** [comment]
@ksrb @mendenhallmagic Should we doc it?

**Comment by ksrb** [comment]
Haven't had a chance to try what sokra mentioned but that would be great, I had no idea that there was `internal` keyword(?) that could be used to delegate the module loading.

**Comment by alexander-akait** [comment]
@sokra friendly ping

**Comment by ksrb** [comment]
So I gave what sokra mentioned a shot but am having trouble getting it to work any chance someone could take a look:

https://github.com/ksrb/module-federation-examples/tree/dynamic-remotes-synchronous-imports/advanced-api/dynamic-remotes-synchronous-imports

The end result is supposed to be:
![image](https://user-images.githubusercontent.com/3750409/103819714-d0124a80-501f-11eb-8aa2-ecbf0affd4a8.png)

Which you can see if you check out the previous commit at sha [bccfd95e68](https://github.com/ksrb/module-federation-examples/commit/bccfd95e68)

However the current commit fails with the following error:
![image](https://user-images.githubusercontent.com/3750409/103820158-ab6aa280-5020-11eb-89f8-4ae436045559.png)

**Comment by ksrb** [comment]
@alexander-akait any chance you or another webpack team member could take a look at this. I wouldn't mind cleaning it up and adding documentation to webpack if I can get the example I posted working https://github.com/module-federation/module-federation-examples/pull/557.

Thanks 😄!

**Comment by Guriqbal-Singh-Alida** [comment]
@sokra i also tried your solution but got this:
![image](https://user-images.githubusercontent.com/71792252/104251299-477f1a00-5424-11eb-9423-a228e28cb3e2.png)

webpack config:
![image](https://user-images.githubusercontent.com/71792252/104251420-890fc500-5424-11eb-8b18-2d0b13c522bc.png)

Any help is appreciated

**Comment by Guriqbal-Singh-Alida** [comment]
test

**Comment by Guriqbal-Singh-Alida** [comment]
@sokra i encountered the above same issue and upon debugging looks like externals.get method is undefined. Any help is appreciated.
Thanks

**Comment by Guriqbal-Singh-Alida** [comment]
@sokra @ScriptedAlchemy @ksrb @alexander-akait  upon further debugging, the issue happens on:
![image](https://user-images.githubusercontent.com/71792252/104380316-abb2e400-54df-11eb-8a8d-096c817a80c3.png)

Upon checking there is no such menthod call external.get on js-dom external
https://html.spec.whatwg.org/multipage/obsolete.html#dom-external

Any help is much appreciated

**Comment by Guriqbal-Singh-Alida** [comment]
> You should be able to do it with the following:
> 
> ```js
> new ModuleFederationPlugin({
>   remotes: {
>     remoteModule: "internal ./module-to-load-remote.js"
>   }
> })
> ```
> 
> ```js
> // module-to-load-remote.js
> module.exports = (async () => {
>   const container = await someKindOfDynamicLoading();
>   return container;
> })();
> ```
> 
> ```js
> // usage as usual
> import urls from "remoteModule/constants";
> ```
> 
> This delegates the loading of the container to some internal logic.

doesnot work

**Comment by jacob-ebey** [comment]
If you export an object with "get, init", then in the "init" load the remote entry it works. This feels strange though and it would be nice to have a combination of "internal" and "promise" to allow either exporting a promise from the "module-to-load-remote", or an async function instead of a resolved module.

**Comment by Guriqbal-Singh-Alida** [comment]
@jacob-ebey nop still error says fn is returned undefined at exact same line

**Comment by jacob-ebey** [comment]
@Guriqbal-Singh-Alida It most definitely does work: https://github.com/jacob-ebey/fed-internal-remote

**Comment by Guriqbal-Singh-Alida** [comment]
@jacob-ebey Thanks for quick replies, only diff i can see is that in your case target is set to node,
Also when i set my target to node i get 
![image](https://user-images.githubusercontent.com/71792252/104385213-abb6e200-54e7-11eb-8c8b-ed20bca64e6a.png)

Further I intend to create static build in the end

**Comment by jacob-ebey** [comment]
Ah, browser land...

**Comment by Guriqbal-Singh-Alida** [comment]
@jacob-ebey yup

**Comment by Guriqbal-Singh-Alida** [comment]
@jacob-ebey surprising thing is in my case the file break point is not even hit, so looks like internal doesnot have any effect, or otherwise external api differs between browser vs node

**Comment by jacob-ebey** [comment]
@Guriqbal-Singh-Alida it seems to work without issue: https://github.com/jacob-ebey/fed-internal-remote-browser

**Comment by Guriqbal-Singh-Alida** [comment]
@jacob-ebey I will give it a try from scratch, may be i am missing something.
Thanks again for your quick comments

**Comment by jacob-ebey** [comment]
@Guriqbal-Singh-Alida I just made some quick updates that simplify the "internal-load.js" and turns it into a promise as mentioned by @sokra and it works fine as well both on the node and browser examples I have above.

**Comment by Guriqbal-Singh-Alida** [comment]
@jacob-ebey so i was missing the piece where we need to copy file in build directory.  It work for straight forward case but
we cannot use import or even require syntax since the file is added to externals it will not be transpiled by webpack for browser use.
Any ideas

**Comment by jacob-ebey** [comment]
@Guriqbal-Singh-Alida Another webpack build with the "internal-load" as an entry with libraryTarget set to var?

**Comment by Guriqbal-Singh-Alida** [comment]
@jacob-ebey did not get you sorry

**Comment by jacob-ebey** [comment]
@Guriqbal-Singh-Alida I've once again update the example to run the internal-load.js file through the loaders, thus they also have access to the rest of the webpack graph for importing whatever they need to load the remote entry.

**Comment by Guriqbal-Singh-Alida** [comment]
@jacob-ebey Thanks buddy, now its working. Your responsive replies are much appreciated and thank you so much for your quick help.
This should serve as gold for other people looking to have module federation dynamic loading but not sacrificing the es6  import syntax.
This case is specially helpful if one is exporting hooks as federated module.

**Comment by jacob-ebey** [comment]
@Guriqbal-Singh-Alida NP, this was something I've been doing on the side thus figured I'd share. I'm sure there is a better way to get the entry registered in the webpack modules graph to not have to do the externals stuff, but 🤷‍♀️

**Comment by Guriqbal-Singh-Alida** [comment]
@jacob-ebey yup agree that this should be handled natively in ModuleFederationPlugin's remote config (@ScriptedAlchemy and WMF team)
But this will do it in the mean time.
Thanks :slightly_smiling_face:

**Comment by Guriqbal-Singh-Alida** [comment]
@jacob-ebey i just noticed that with above HMR is broken and if I set hot: true for webpack dev server then code stops working. did you by anychance encountered the same?

**Comment by jacob-ebey** [comment]
@Guriqbal-Singh-Alida I'd personally argue this is outside the scope of the ModuleFederationPlugin core.

HMR does not work with cross-container HMR in general at the moment. No one has spent time making this work.

**Comment by Guriqbal-Singh-Alida** [comment]
@jacob-ebey ah ok so looks like we have to sacrifice HMR in that case.
Cool will regard it as manageable tradeoff given the MF benefits at the moment but it would be nice if it can work with HMR too but all good
Thanks for the awesome work on module federation

**Comment by Guriqbal-Singh-Alida** [comment]
@jacob-ebey  so the above approach works fine when import simple object but when we try to import react components it blows up as follow:
![image](https://user-images.githubusercontent.com/71792252/104519874-06ffd780-55af-11eb-89a9-bbb26371b645.png)

in our webpack react is set as singleton also.

**Comment by Guriqbal-Singh-Alida** [comment]
@jacob-ebey further confirming the modules are returned fine but looks like something else in the path not liking, since it only happens in code that uses react as dependency

**Comment by Guriqbal-Singh-Alida** [comment]
@jacob-ebey @maraisr @ScriptedAlchemy any thoughts or help is appreciated?
Or else is there way to specify remote urls at runtime?

**Comment by Guriqbal-Singh-Alida** [comment]
@jacob-ebey @ScriptedAlchemy issue solved. To explain when we provide multiple entry points, the each entry gets its own runtime by default(https://webpack.js.org/configuration/optimization/#optimizationruntimechunk). Since hooks and react components must share runtime we had to split react and vendor as separate common chunks and configure runtimeChunk as single
```
entry: {
      main: './src/index',
      'library-loader': {
        import: `${path.resolve(__dirname, 'src', 'startup.js')}`,
        library: {
          type: 'var',
          name: 'LIBRARY_LOAD',
        },
      },
    },
    externals: [
      {
        'library-loader': `promise new Promise((res, rej) => {
        const mod = LIBRARY_LOAD;
        mod.library.then(res, rej);
      })`,
      },
    ],
  optimization: {
    splitChunks: {
        chunks: 'all',
      },
    runtimeChunk: 'single',
  }
```

Thanks for all the support you guys provided

**Comment by 17biubiu** [comment]
i met the same issue, in the developement mode, it can work fine, but when i run npm run build. on the web server, it not work
![image](https://user-images.githubusercontent.com/13295895/105443131-faae0580-5ca5-11eb-92c3-c38adbcfba5e.png)
tools is tools.js
`import tools from 'remote/tools'`

**Comment by jacob-ebey** [comment]
@17biubiu That seems to be related to `runtimeChunk: "single"`.

**Comment by Guriqbal-Singh-Alida** [comment]
@17biubiu to add on to @jacob-ebey reply, if you are talking about exposed components not working then may be you are facing  https://github.com/module-federation/module-federation-examples/issues/646

**Comment by 17biubiu** [comment]
@jacob-ebey @Guriqbal-Singh-Alida  yeah,  it looks strange.

**Comment by Guriqbal-Singh-Alida** [comment]
@17biubiu Temp fix found, please take a look at latest comment in previous mentioned issue

**Comment by 17biubiu** [comment]
@Guriqbal-Singh-Alida  thanks, i found it,I will try it later

**Comment by Guriqbal-Singh-Alida** [comment]
@jacob-ebey  @17biubiu  just fyi: This is simpler approach https://github.com/module-federation/module-federation-examples/issues/566 and has much less integration issues

**Comment by ksrb** [comment]
Thanks everyone who helped figure out this issue, I've update the PR https://github.com/module-federation/module-federation-examples/pull/557 to utilize the plugin created by matthewma7.

**Comment by nkalinov** [comment]
Hey guys, thank you all your work here! 
Is there a way to provide remote URL fallback? 
Ie: try to load module "foo" from URL-1, if it fails (404 for example), fallback to loading the from URL-2 ?
Trying to make local development easier by loading some modules from a CDN env if it is not running on localhost...

**Comment by Guriqbal-Singh-Alida** [comment]
@nkalinov There might be other solutions but 1 quick approach is to load federated modules dynamically at runtime using https://webpack.js.org/concepts/module-federation/#dynamic-remote-containers

**Comment by ScriptedAlchemy** [comment]
promise new promise syntax or pass remote an array or valid options, like remote1: [global@url,global@otherUrl]

**Comment by cyrusssssschen** [comment]
> 

@ScriptedAlchemy 
Specifying multiple URLs for single remote id able to be supported now?

**Comment by ScriptedAlchemy** [comment]
Always has been. Remotes take an array

**Comment by ialpert** [comment]
I know it's been a while, but maybe you can provide an example in NextJS context? 

I tried to implement it and got: `originalExternals is not a function`

**Comment by Albert-Stepanyan777** [comment]
Hey guys), does anyone know is there a way to achieve cross-micro frontend communication, namely the synchronization of dynamic state, such as feature flags, across micro frontends, especially when they are hosted on different domains, is it possible with a combination of Webpack Module Federation and a runtime plugin that facilitates dynamic sharing of feature flags across micro frontends?

**Comment by ScriptedAlchemy** [comment]
> Hey guys), does anyone know is there a way to achieve cross-micro frontend communication, namely the synchronization of dynamic state, such as feature flags, across micro frontends, especially when they are hosted on different domains, is it possible with a combination of Webpack Module Federation and a runtime plugin that facilitates dynamic sharing of feature flags across micro frontends?

Yeah that works. I don't have a example of this however.
