### ISSUE TITLE
[Feature Request] Persistent cache for webpack ---watch, after initial build use memory

### ISSUE THREAD

**Issue by matzeeable** [webpack/webpack#12251]
## Feature request

**What is the expected behavior?**

Is it somehow possible, to use the persistent disk cache for the initial build, and the memory for the rebuilds?

**What is motivation or use case for adding/changing the behavior?**

Speed up initial `--watch` compilation.

**How should this be implemented in your opinion?**

> [...] I think this behavior can be default [...]

#12250

**Are you willing to work on this yourself?**
can't say atm

**Comment by sokra** [comment]
Yes, that's already how it works by default (when persistent cache is enabled)

**Comment by sokra** [comment]
Additionally persistent cache will persist the memory cache after 1 minute of idle in watch mode.
