### ISSUE TITLE
Crash at the end of compilation

### ISSUE THREAD

**Issue by CYB3RL1F3** [webpack/webpack#12263]
Hello,

I meet a crash with this error at the end of the compilation: 

```
ERROR in [initial] main.e4e732f00dfe0da35af2.js
Maximum call stack size exceeded

webpack 5.11.0 compiled with 1 error in 38480 ms
```

Any clue?

I splitted lots of modules into small chunks.

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Please fix the problem and I will reopen
