### ISSUE TITLE
Randomly dropping CSS modules from entrypoint on watch recompilation

### ISSUE THREAD

**Issue by Bilge** [webpack/webpack#12267]
# Bug report

**What is the current behavior?**
First compilation always works. However, during development in *watch* mode, subsequent recompilations drop other included modules from the final output.

When modifying `app.less` in development, only the contents of `app.less` and `chart.css` are included on recompilation in *watch* mode. That is, `3col.less` and `compact ranking.less` are excluded. I investigated why `chart.css` survives but the other two are discarded, and it is due to the file extension. If I rename `chart.css` -> `chart.less`, it is also dropped on recompilation in watch mode.

It should be noted the behaviour is not always reproducible on first recompilation. Sometimes it takes 2-3 changes to `app.less` before the bug shows itself. The modifications can be in quick succession, so time is not a factor, just the number of recompiles.

**If the current behavior is a bug, please provide the steps to reproduce.**
```js
const path = require('path');

const MiniCssExtractPlugin = require('mini-css-extract-plugin');

module.exports = {
    mode: 'development',
    // Absolute base directory for entry points and resource paths.
    context: path.resolve(__dirname, 'static'),
    entry: {
        app: [
            './css/3col.less',
            './css/app.less',
            './css/chart.css',
            './css/compact ranking.less',
        ],
    },

    output: {
        path: path.resolve(__dirname, 'static/c'),
        publicPath: '',
    },

    plugins: [
        new MiniCssExtractPlugin(),
    ],

    module: {
        rules: [
            {
                test: /\.(less|css)$/,
                use: [
                    {
                        loader: MiniCssExtractPlugin.loader,
                    },
                    {
                        loader: 'css-loader',

                        options: {
                            url: false,
                            sourceMap: true,
                        },
                    },
                    {
                        loader: 'less-loader',

                        options: {
                            sourceMap: true,
                        },
                    },
                ],
            },
        ],
    },
};

```

**What is the expected behavior?**
When `app.css` is recompiled, all included assets (`3col.less`, ` app.less`, `chart.css` and `compact ranking.less` ) should still be present in the output.

**Other relevant information:**
webpack version:  5.11.0
Node.js version: v14.15.3
Operating System:  Windows 10
Additional tools: 
* less-loader@7.1.0
* less@4.0.0
* mini-css-extract-plugin@1.3.3

**Program output**

Below is the output from a full recompile plus two additional watch recompiles. The first *watch* recompile is successful. The second *watch* recompile drops modules, leaving the output file in a bad state.

```
$ webpack --watch
[webpack-cli] Compilation starting...
[webpack-cli] Compilation finished
assets by path *.css 18.4 KiB
  asset app.css 13.4 KiB [emitted] (name: app)
  asset search.css 3.18 KiB [compared for emit] (name: search)
  asset club250.css 1.81 KiB [compared for emit] (name: club250)
assets by path *.js 9.99 KiB
  asset app.js 3.88 KiB [compared for emit] (name: app)
  asset search.js 3.06 KiB [compared for emit] (name: search)
  asset club250.js 3.05 KiB [compared for emit] (name: club250)
Entrypoint club250 4.86 KiB = club250.css 1.81 KiB club250.js 3.05 KiB
Entrypoint app 17.2 KiB = app.css 13.4 KiB app.js 3.88 KiB
Entrypoint search 6.25 KiB = search.css 3.18 KiB search.js 3.06 KiB
runtime modules 822 bytes 3 modules
code generated modules 400 bytes (javascript) 18.3 KiB (css/mini-extract) [code generated]
  cacheable modules 400 bytes
    modules by path ./css/*.css 200 bytes 4 modules
    modules by path ./css/*.less 200 bytes 4 modules
  css modules 18.3 KiB
    modules by path ./css/*.css 4.99 KiB 4 modules
    modules by path ./css/*.less 13.4 KiB
      css ../node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[0].use[1]!../node_modules/less-loader/dist/cjs.js??ruleSet[1].rules[0].use[2]!./css/3col.less 1.37 KiB [code generated]
      css ../node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[0].use[1]!../node_modules/less-loader/dist/cjs.js??ruleSet[1].rules[0].use[2]!./css/app.less 9.96 KiB [code generated]
      css ../node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[0].use[1]!../node_modules/less-loader/dist/cjs.js??ruleSet[1].rules[0].use[2]!./css/chart.less 1.73 KiB [code generated]
      css ../node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[0].use[1]!../node_modules/less-loader/dist/cjs.js??ruleSet[1].rules[0].use[2]!./css/compact ranking.less 300 bytes [code generated]
webpack 5.11.0 compiled successfully in 455 ms
[webpack-cli] watching files for updates...
[webpack-cli] Compilation starting...
[webpack-cli] Compilation finished
assets by status 28.3 KiB [cached] 6 assets
Entrypoint club250 4.86 KiB = club250.css 1.81 KiB club250.js 3.05 KiB
Entrypoint app 17.2 KiB = app.css 13.4 KiB app.js 3.88 KiB
Entrypoint search 6.25 KiB = search.css 3.18 KiB search.js 3.06 KiB
cached modules 350 bytes (javascript) 18.3 KiB (css/mini-extract) 822 bytes (runtime) [cached] 18 modules
./css/app.less 50 bytes [built]
webpack 5.11.0 compiled successfully in 97 ms
[webpack-cli] watching files for updates...
[webpack-cli] Compilation starting...
[webpack-cli] Compilation finished
assets by status 15 KiB [cached] 5 assets
asset app.css 13.4 KiB [emitted] (name: app)
Entrypoint club250 4.86 KiB = club250.css 1.81 KiB club250.js 3.05 KiB
Entrypoint app 17.2 KiB = app.css 13.4 KiB app.js 3.88 KiB
Entrypoint search 6.25 KiB = search.css 3.18 KiB search.js 3.06 KiB
cached modules 350 bytes (javascript) 8.38 KiB (css/mini-extract) 822 bytes (runtime) [cached] 17 modules
modules by path ./css/*.less 50 bytes (javascript) 9.96 KiB (css/mini-extract)
  ./css/app.less 50 bytes [built]
  css ../node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[0].use[1]!../node_modules/less-loader/dist/cjs.js??ruleSet[1].rules[0].use[2]!./css/app.less 9.96 KiB [code generated]
webpack 5.11.0 compiled successfully in 79 ms
[webpack-cli] watching files for updates...
```

**Comment by alexander-akait** [comment]
>When app.css is recompiled, all included assets (3col.less, app.less, chart.css and compact ranking.less ) should still be present in the output.

By default webpack uses `memory` cache in development mode, so on second and more compilations unchanged files not rebuilded and so not output in terminal, anyway all necessary data available in stats

**Comment by alexander-akait** [comment]
Look here:
```
cached modules 350 bytes (javascript) 18.3 KiB (css/mini-extract) 822 bytes (runtime) [cached] 18 modules
```

```
cached modules 350 bytes (javascript) 8.38 KiB (css/mini-extract) 822 bytes (runtime) [cached] 17 modules
```

**Comment by Bilge** [comment]
What are you talking about? Whether or not the assets are cached, when webpack regenerates the `app` entrypoint, only half the files are present in the output `app.css`. That is, only the contents of `app.less` and `chart.css` are present in the output. The other files (`3col.less` and `compact ranking.less`) are ***EXCLUDED*** from the GENERATED FILE so the page appear corrupted because CSS is ***MISSING***. Please reopen this issue.

**Comment by alexander-akait** [comment]
Сhange your tone of communication, don't be toxic, I try to reproduce the problem using `If the current behavior is a bug, please provide the steps to reproduce.` and all works fine, please create reproducible test repo, thanks

Also your configuratoin is invalid:
```
module: {
        rules: [
            {
                test: /\.(less|css)$/,
                use: [
                    {
                        loader: MiniCssExtractPlugin.loader,
                    },
                    {
                        loader: 'css-loader',

                        options: {
                            url: false,
                            sourceMap: true,
                        },
                    },
                    {
                        loader: 'less-loader',

                        options: {
                            sourceMap: true,
                        },
                    },
                ],
            },
        ],
    },
```

You apply less-loader to `CSS` files, so it some bug on less side, but I can't say it 100%, because I don't have a code

**Comment by alexander-akait** [comment]
Try to use `less@3` too

**Comment by Bilge** [comment]
I am not trying to be toxic but you closed my issue as invalid with no resolution when it is very valid very problematic.

As mentioned, reproduction is not consistent:

1. You must run webpack in *watch mode*
2. One of the dependent files must be regenerated at least 2/3, maybe even 4/5 times before the bug exhibits itself.

Regarding the *invalid configuration*, this invalid configuration was generated by the config generator of webpack-cli, so if it truly is invalid that's another bug in webpack code.

In any case, I seriously doubt this has anything to do with *less* or any of loaders because it is webpack that is instructed to include four files in the entrypoint and it seems to me that it is webpack that is dropping them.

**Comment by alexander-akait** [comment]
> Regarding the invalid configuration, this invalid configuration was generated by the config generator of webpack-cli, so if it truly is invalid that's another bug in webpack code.

It is not webpack core bug, it is bug on webpack-cli, and feel free to open an issue

> In any case, I seriously doubt this has anything to do with less or any of loaders because it is webpack that is instructed to include four files in the entrypoint and it seems to me that it is webpack that is dropping them.

We cannot guess, I already answered earlier that I cannot reproduce, so it seems to me that this is due to loaders/plugins, especial less-loader

> I am not trying to be toxic but you closed my issue as invalid with no resolution when it is very valid very problematic.

Understand me too, I cannot try to fix something and somewhere without being able to even reproduce the problem, I am not a predictor

**Comment by Bilge** [comment]
Downgrading to less@3 made no difference.

**Comment by alexander-akait** [comment]
Still can't reproduce

**Comment by Bilge** [comment]
If I update the config to be *valid*, the problem still persists.

```js
{
    test: /\.css$/,
    use: [
        {
            loader: MiniCssExtractPlugin.loader,
        },
        {
            loader: 'css-loader',

            options: {
                url: false,
                sourceMap: true,
            },
        },
    ],
},
{
    test: /\.less$/,
    use: [
        {
            loader: MiniCssExtractPlugin.loader,
        },
        {
            loader: 'css-loader',

            options: {
                url: false,
                sourceMap: true,
            },
        },
        {
            loader: 'less-loader',

            options: {
                sourceMap: true,
            },
        },
    ],
}
```

**Comment by alexander-akait** [comment]
I will reopen the issue when I reproduce it, maybe move to mini-css-extract-loader or other repo, plese create minimum reproducible test repo

**Comment by Bilge** [comment]
@alexander-akait I tried to reproduce it with a separate repo but I could not. Not even using the exact sample files could I reproduce it. Yet at the same time, the exact same files in my original project were *consistently* exhibiting this behaviour. So I restarted my IDE and now I cannot reproduce the problem even in the original repo. So it seems there was some sort of problem running `watch` via PhpStorm. Or, somehow, Node running via PhpStorm had become irredeemably corrupted, but even that explanation makes no sense to me, because every time I restarted webpack to generate the correct output, it spawns a new Node process.

I don't know if I'm ever going to be able to reproduce it at this point (hopefully not), but it still bothers me that I have no explanation for why it occurred to begin with.

**Comment by alexander-akait** [comment]
These are the things I'm talking about. We have a lot of old issues with the same problems, and now we cannot close them, because we cannot answer (so it is why we closed not reproducible problems, excluding explicit), yep, it looks like file system and cache issues in your IDE, if you run into it again recommended looking at stats (especial birthtime and changed time) and content of files.
