### ISSUE TITLE
Webpack Mode for externally loaded chunks - don't reject if not loaded yet

### ISSUE THREAD

**Issue by daewigma** [webpack/webpack#12260]
## Feature request
Webpack mode that's a mix of lazy/weak, bundle generated to be loaded like lazy mode, but loaded externally like weak mode (and waits for the file to load if not loaded, like lazy)

**What is the expected behavior?**
If doing a dynamic import, allow the chunk to be loaded with external code, but don't reject if it isn't loaded by the time the dynamic import happens. Keep waiting until it loads.

**What is motivation or use case for adding/changing the behavior?**
I'm trying to use my script on a site that has anti-malware code blocking scripts from adding new scripts to the page. Scripts can only be added by the site owner.
My script is large and I would like to break it into smaller pieces, only loading the code needed for the entry UI first. I can set it up to load a second script after the first is loaded, but there isn't a webpack mode that supports this (weak mode is close, but rejects if the script hasn't loaded)

**How should this be implemented in your opinion?**
the importing side should behave almost like weak mode, but if the script is missing, it should set up a listener, and resolve once that's called
the imported side should be generated the same way lazy mode is, but with a bit of added code that triggers the listener on the importing side if it exists

**Are you willing to work on this yourself?**
no

**Comment by alexander-akait** [comment]
Out of scope webpack, you can implement this in your application code
