### ISSUE TITLE
“Parsing error: invalid character” when bundling images with Webpack's loaders

### ISSUE THREAD

**Issue by morteify** [webpack/webpack#12276]
# Bug report

**What is the current behavior?**
When I'm trying to bundle my React project, I get the following error regarding an image I'm about to load:
![image](https://user-images.githubusercontent.com/37783495/103174401-1c140100-4862-11eb-9141-70715ab72284.png)

Oddly enough, when I hide the error overlay, I can see in a browser that my picture has been loaded correctly, despite Webpack's complaints. I've already been carefully following other working config examples, where that problem doesn't occur, but I can't easily identify the source of the issue, what leaves me here with no idea how to approach it or where to look for a hint. I've also tried using different loaders: `url-loader`, `file-loader` and `image-webpack-loader`, but to no avail.

**If the current behavior is a bug, please provide the steps to reproduce.**
This happens every time I have an image in the `src/assets/images` directory and run one of these scripts: 
```
  "scripts": {
    "start": "webpack serve --config config/webpack.config.ts --env env=dev",
    "build": "webpack --config config/webpack.config.ts --env env=prod"
  },
```

Source code and every config file is available here:
```
git clone https://github.com/morteify/react-ts-webpack-babel-starter.git
```

**What is the expected behavior?**
I'd like to get rid of the compilation error followed by the overlay.

**Other relevant information:**
Webpack version:  5.11.0
Node.js version: 15.2.0
Operating System: Windows 10
Additional tools: 
 - Babel 7
 - React 17
 - ESlint 7
 - Typescript 4
 - Fast Refresh

**Comment by alexander-akait** [comment]
Please open an issue in `ForkTsCheckerWebpackPlugin`, I think you need fix :
```
files: './src/**/*.{ts,tsx,js,jsx}' // required - same as command `eslint ./src/**/*.{ts,tsx,js,jsx} --ext .ts,.tsx,.js,.jsx`
```
