### ISSUE TITLE
logger looks strange in terminal

### ISSUE THREAD

**Issue by odddemid** [webpack/webpack#12277]
# Bug report
The logs in the terminal look strange. Terminal logs after webpack serve look weird Each new line of the log begins with <i>.

**What is the current behavior?**
The result of the webpack serve command is the following log:
```
<i> [webpack-dev-server] Project is running at http://[::]:8082/
<i> [webpack-dev-server] Content not from webpack is served from
<i> [webpack-dev-middleware] asset main.js 257 KiB [emitted] (name: main)
<i> [runtime / cacheable / webpack] logs] which are irrelevant for this error
<i> webpack 5.11.0 compiled successfully in 368 ms
<i> [webpack-dev-middleware] Compiled successfully.
```
**If the current behavior is a bug, please provide the steps to reproduce.**
Execute command in terminal `webpack serve`

**What is the expected behavior?**
There is no `<i>` at the beginning of the line. To make sure this is an error of the logger and not of my shell, I checked this command in bash/shell/zsh and got the same result. 

Then i modify source code in node_modules/webpack-dev-server/lib/utils/status.js and this code inside status where logger available in scope.

```javascript
logger.info('Hello! i\'m a buggy logger' );
console.log('Nice to meet you, i\'m native console in Node.js')
```

```
<i> [webpack-dev-server] Hello! i'm a buggy logger
Nice to meet you, i'm native console in Node.js
```
Since the logger is part of the webpack project, I open this ish here. 

I hope I did everything right, this is my first one)

```
 System:
    OS: macOS 11.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 305.98 MB / 16.00 GB
  Binaries:
    Node: 14.15.0 - /usr/local/opt/node@14/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/opt/node@14/bin/npm
  Browsers:
    Chrome: 87.0.4280.88
    Safari: 14.0.2
  Packages:
    webpack: ^5.11.0 => 5.11.0 
    webpack-cli: ^4.3.0 => 4.3.0 
    webpack-dev-server: ^4.0.0-beta.0 => 4.0.0-beta.0 
```

**Comment by alexander-akait** [comment]
It is expected, you can disable logging, <i> means - log (like `console.log`) or create own logger, it was discussed many time, sorry we don't want to change it

**Comment by alexander-akait** [comment]
Also not related to webpack
