### ISSUE TITLE
Stats: Option to have a flat list of assets

### ISSUE THREAD

**Issue by silverwind** [webpack/webpack#12270]
## Feature request

Webpack 5's stat output seems a bit on the verbose side with the nested asset stats, I'd like an option to just have a flat list of assets.

**What is the expected behavior?**

Before:
````
assets by path . 13 MiB
  assets by path js/ 11.6 MiB
    asset js/file.js 10.3 KiB [emitted] [minimized] (name: file) (id hint: vendors)
    asset js/file2.js 44.7 KiB [emitted] [minimized] (name: file2) (id hint: vendors)
````

After:
````
asset js/file.js 10.3 KiB [emitted] [minimized] (name: file) (id hint: vendors)
asset js/file2.js 44.7 KiB [emitted] [minimized] (name: file2) (id hint: vendors)
````

**What is motivation or use case for adding/changing the behavior?**

Having more terse output for easier visual parsing.

**How should this be implemented in your opinion?**

A boolean option like `stats.nestAssets`.

**Are you willing to work on this yourself?**
no

**Comment by alexander-akait** [comment]
No options, you have hooks and can change this if you need, sorry, we don't want to change current output, look at example https://github.com/webpack/webpack/blob/master/lib/stats/DefaultStatsPrinterPlugin.js
