### ISSUE TITLE
Migration docs issue

### ISSUE THREAD

**Issue by dbuck** [webpack/webpack#12287]
# Bug report

**What is the current behavior?**
If a user follows the [migration guide](https://webpack.js.org/migrate/5/#upgrade-webpack-version) directly, they will install an old version of webpack.  ` yarn add webpack@next --dev` installs version `"webpack": "^5.0.0-rc.6",` where the user most likely intended to install the latest version `"webpack": "^5.11.1",`

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Remove @next or have @next point to a version that works

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

**Comment by chenxsan** [comment]
@dbuck Thanks for heads-up, I've filed a pull request to fix it.

**Comment by alexander-akait** [comment]
Fixed
