### ISSUE TITLE
It can't be imported by the original path when I set an alias.

### ISSUE THREAD

**Issue by iam-frankqiu** [webpack/webpack#12282]
# Bug report

**What is the current behavior?**

When I set an index. file to export a component and set the Alias on config. It can't be imported by the original path.

**If the current behavior is a bug, please provide the steps to reproduce.**

https://codesandbox.io/s/busy-swirles-mj3j9?file=/src/index.tsx

**What is the expected behavior?**

It also can be imported by the original path.

**Other relevant information:**
webpack version:  4.44.2
Node.js version: v14.15.1
Operating System: MacOS 10.15.6

**Comment by alexander-akait** [comment]
`import { Drawer } from "./Drawer.tsx";`, please don't use webpack@5 with CRA https://github.com/facebook/create-react-app/issues/9510, it is not compatibility

**Comment by raix** [comment]
Webpack 5 in CRA is not yet supported, there is a pinned issue/overview of progress.

But webpack-dev-server doesn't support federated modules yet afaik?

**Comment by alexander-akait** [comment]
federated modules is not supported webpack-dev-server right now
