### ISSUE TITLE
Uncaught SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by wangcherry** [webpack/webpack#12281]
![image](https://user-images.githubusercontent.com/11580793/103267065-f0248700-49eb-11eb-998d-13db4bc4cae9.png)

my webpack config 

```
new ModuleFederationPlugin({
      name: "ahas_sentinel",
      library: { type: "var", name: "ahas_sentinel" },
      filename: "remoteEntry.js",
      remotes: {
        ahas_switch: `ahas_switch@${config.output.publicPath}remoteEntry.js`,
      },
      exposes: {
        "./routes": "./routes.tsx",
      },
      shared: {
        ...deps,
      },
 })
```

* [x] webpack-5

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

**Comment by alexander-akait** [comment]
don't use invalid identifier for `ahas_switch: `ahas_switch@${config.output.publicPath}remoteEntry.js`,`

**Comment by yzStrive** [comment]
@wangcherry  Have you solved it ? I have the same problem
![image](https://user-images.githubusercontent.com/32640035/103335116-f3cd1200-4aae-11eb-9dfd-f269614c5c05.png)
![image](https://user-images.githubusercontent.com/32640035/103335131-01829780-4aaf-11eb-8d62-7e030df42440.png)
 build files has error

**Comment by yzStrive** [comment]
> don't use invalid identifier for `ahas_switch@${config.output.publicPath}remoteEntry.js`

 I have the same problem 
 webpack  "version": "5.11.1"

**Comment by hypeJunction** [comment]
I am seeing the same issue with webpack 5.17. Can't figure it out what's causing it.

**Comment by hypeJunction** [comment]
This seems to only happen with `{ library: { type: 'var', name: 'name' } }`. Not sure what the underlying reason is.

**Comment by netics** [comment]
Any news about this one? I am having the same issue with vue-cli and webpack5

**Comment by caiquelsousa** [comment]
Same here i'm not sure how to solve this.. can someone help please?

**Comment by alexander-akait** [comment]
JSON.stringify('app2@http://example.com/')

**Comment by amitpatil321** [comment]
Does anyone found any solution to this ? I even tried @alexander-akait workaround but that throws other error.

**Comment by kbcolsy** [comment]
I've got the same issue @amitpatil321

**Comment by Perseman** [comment]
> amitpatil321
I have the same problem，do you resolve it?

**Comment by amitpatil321** [comment]
> > amitpatil321
> 
> I have the same problem，do you resolve it?

I don't remember how i resolved it, But i have a working code that you can compare with your code. 

https://github.com/amitpatil321/Redux-micro-frontend
