### ISSUE TITLE
coffee 2 js Module not found

### ISSUE THREAD

**Issue by timnity** [webpack/webpack#1228]
When I  `$ webpack --display-error-details`
I got some error log: `Module not found: Error: Cannot resolve module 'fs' ...`
I search the solution, add node to config file like:
```
...
node: {
  console: false,
  fs: 'empty',
  net: 'empty',
  pg-hstore: 'empty'
}
```
But the pg-hstore still throw error log, all of the middle line name will ignored, thanks any help.

**Comment by timnity** [comment]
my webpack.config.js
```
module.exports = {
  entry: {
    mobile: './api/server.coffee'
  },
  output: {
    filename: './apibuild/[name].js'
  },
  devtool: 'inline-source-map',
  module: {
    loaders: [
      { test: /\.json$/, loader: 'json-loader',  },
      { test: /\.coffee$/, loader: 'coffee-loader', exclude: /node_modules/ }
    ]
  },
  resolve: {
    extensions: ['', '.coffee', '.json', '.js', '.web.coffee', '.web.js']
  },
  node: {
    console: false,
    fs: 'empty',
    net: 'empty'
  }
};
```

**Comment by shama** [comment]
If a module is relying on `fs` you're likely going to have a hard time using the module on the client side. `fs` is for interfacing with the file system which a web browser doesn't have. There are potential `fs` shims out there but it's a big guess whether they'll satisfy the requirements of specific modules.

**Comment by timnity** [comment]
Before I use gulp to transform, uglify, test ... I try to use webpack instead gulp work, but it's hard. thank you

**Comment by bebraw** [comment]
@timnity Safe to close?
