### ISSUE TITLE
after upgrade, webpack 5 imports module as `undefined`.

### ISSUE THREAD

**Issue by kevzettler** [webpack/webpack#12293]
# Bug report

I am in the middle of upgrading a webpack 4 project to webpack 5 . One of my imported modules is coming in as `undefined` in the runtime browser bundle. I can manually require this module from `node_modules` in the `node` command line interface. This module also imports fine with previous webpack 4 version.

**What is the current behavior?**

The when imported the module is `undefined` at runtime in the browser.

**If the current behavior is a bug, please provide the steps to reproduce.**
I have created a minimal reproduction library at: https://github.com/kevzettler/webpack5-missing-module

**What is the expected behavior?**

```
import * as kiwi from 'kiwi-schema';

console.log('kiwi.compileSchema should defined...', kiwi.compileSchema);
```

The `kiwi.compileSchema` should be a `Function` and it is `undefined`

**Other relevant information:**
webpack version:  
```
    "webpack": "^5.11.1",
    "webpack-cli": "^4.3.0",
    "webpack-dev-server": "^4.0.0-beta.0"
 ```

Node.js version: `v12.18.1`
Operating System:  
`Darwin kevs-mbp.lan 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64`
macOS Mojave 10.14.6

Additional tools:
`"kiwi-schema": "git://github.com/bvandenbos/kiwi.git#maps",`

**Comment by sokra** [comment]
The module has a `var exports` at top. That's really weird, and seems to confuse webpack, because `exports` is no longer a free var. It thinks the free `exports` is unused.

You could add `module.noParse: /kiwi-schema.kiwi\.js/` to the config as workaround. Or upgrade to the latest version of kiwi-schema...

I don't think this has high enough priority to fix it...

**Comment by alexander-akait** [comment]
bump
