### ISSUE TITLE
Worker is not defined for target Node.js

### ISSUE THREAD

**Issue by kevzettler** [webpack/webpack#12299]
# Bug report

I am trying to use the new Webpack 5 native worker features. per @alexander-akait 's comment at https://github.com/webpack-contrib/worker-loader/issues/301#issuecomment-741898222

I was under the impression the worker support would work for both web workers and node.js worker-threads.
I understand the documentation is not yet ready and hope i'm missing something obvious. 

**What is the current behavior?**
`ReferenceError: Worker is not defined`

in a `target:node` build

**If the current behavior is a bug, please provide the steps to reproduce.**

I have created a minimal reproduction repository at: https://github.com/kevzettler/webpack5-worker-test

**What is the expected behavior?**
Per comment at: https://github.com/webpack-contrib/worker-loader/issues/301#issuecomment-741898222
and discussion at:
https://github.com/webpack/webpack/issues/6472#issuecomment-693549090

I assumed `new Worker(new URL("./worker", import.meta.url))` would work in a Node.js target

**Other relevant information:**
webpack version:  
```
webpack 5.11.1
webpack-cli 4.3.1
```

Node.js version: 
`v12.18.1`
Operating System: 
`macOs Mojave 10.14.6`
Additional tools:

**Comment by alexander-akait** [comment]
Because `Worker` doesn't exists in Node.js you need to use, supported syntaxes https://github.com/webpack/webpack/blob/923be31fba88468b70499428e1f2b83aad49af84/lib/dependencies/WorkerPlugin.js#L37 (but you can add own too), please look at `Worker from worker_threads`

**Comment by kevzettler** [comment]
@alexander-akait I need help. How do I use this syntax? 

```
 worker = new Worker from worker_threads(new URL('./server.worker', import.meta.url));
 ```
 Is not valid and breaks typescript
 
 > (but you can add own too), 
 
 How would I do this?

**Comment by sokra** [comment]
Please also read the node.js documentation about how to use workers in node. It's a bit different compared to the browser.

``` js
import { Worker } from "worker_threads";

new Worker(new URL(...))
```

**Comment by alexander-akait** [comment]
@kevzettler answer above

**Comment by kevzettler** [comment]
thanks yall. got it.
