### ISSUE TITLE
use  resolve.fallback  to polyfill nodejs  modules  still not  work

### ISSUE THREAD

**Issue by duanbaosheng** [webpack/webpack#12298]
**Other relevant information:**
webpack version:  5.11.1
Node.js version: 10.15.3
Operating System: mac os 10.14.5
Additional tools:

i  upgrade webpack4  to webpack5

but i  got a lot of  nodejs polyfill error

![image](https://user-images.githubusercontent.com/17683694/103412636-1fd0bc00-4bb1-11eb-85cc-3e03d0bfbcf5.png)

   "dependencies": {
        "@tencent/AUI-cli": "^0.0.24",
        "@tencent/beaconapi": "^1.2.3",
        "@tencent/exeditor-basic": "^0.4.0-alpha.3",
        "@tencent/exeditor-common-plugin": "^0.4.0",
        "@tencent/exeditor-server-plugin": "^0.4.0",
        "@tencent/luna-upload": "^0.1.5",
        "@tencent/oms_ui": "^1.1.26",
        "@tencent/oms_ui_reactEcharts": "^0.0.11",
        "@tencent/omscomp": "0.0.1-7.7",
        "acorn": "^6.0.0",
        "acorn-jsx": "^5.0.1",
        "antd": "^3.3.2",
        "axios": "^0.16.2",
        "babel-polyfill": "^6.23.0",
        "browserslist": "^2.11.3",
        "classnames": "^2.2.5",
        "commander": "^2.15.1",
        "dva": "^2.4.1",
        "dva-loading": "^3.0.21",
        "ejs-loader": "^0.3.0",
        "history": "^4.7.2",
        "js-beautify": "^1.6.14",
        "jsonp": "^0.2.1",
        "moment": "^2.22.2",
        "nan": "^2.12.1",
        "nprogress": "^0.2.0",
        "numeral": "^2.0.6",
        "path-to-regexp": "^1.7.0",
        "prop-types": "^15.5.10",
        "qs": "^6.5.0",
        "query-string": "^5.0.0",
        "react": "16.6.0",
        "react-countup": "^2.1.1",
        "react-dom": "16.6.0",
        "react-helmet": "^5.1.3",
        "url-loader": "^4.1.1",
        "viewerjs": "^1.0.0",
        "xlsx": "^0.14.1"
    },
    "devDependencies": {
        "@babel/core": "^7.9.0",
        "@babel/plugin-proposal-class-properties": "^7.8.3",
        "@babel/plugin-proposal-decorators": "^7.8.3",
        "@babel/plugin-proposal-object-rest-spread": "^7.9.0",
        "@babel/plugin-syntax-dynamic-import": "^7.8.3",
        "@babel/plugin-transform-modules-commonjs": "^7.9.0",
        "@babel/plugin-transform-runtime": "^7.9.0",
        "@babel/plugin-transform-spread": "^7.8.3",
        "@babel/preset-env": "^7.9.0",
        "@babel/preset-react": "^7.9.1",
        "@babel/runtime": "^7.12.5",
        "@tencent/dwt": "^3.0.3",
        "@tencent/dwt-reporter": "^3.0.1",
        "awesome-typescript-loader": "^5.2.1",
        "babel-eslint": "^10.0.1",
        "babel-jest": "^26.3.0",
        "babel-loader": "^8.1.0",
        "babel-plugin-add-module-exports": "^1.0.2",
        "babel-plugin-dev-expression": "^0.2.1",
        "babel-plugin-dva-hmr": "^0.4.2",
        "babel-plugin-import": "^1.1.1",
        "babel-plugin-transform-remove-console": "^6.9.4",
        "babel-plugin-transform-runtime": "^6.9.0",
        "babel-runtime": "^6.9.2",
        "case-sensitive-paths-webpack-plugin": "^2.3.0",
        "chalk": "^3.0.0",
        "clean-webpack-plugin": "^3.0.0",
        "constants-browserify": "^1.0.0",
        "copy-webpack-plugin": "^7.0.0",
        "core-js": "^3.6.4",
        "cross-env": "^5.0.5",
        "cross-spawn": "^6.0.5",
        "css-loader": "^3.4.2",
        "detect-port": "^1.3.0",
        "dva-model-extend": "^0.1.2",
        "enzyme": "^3.11.0",
        "enzyme-adapter-react-16": "^1.15.5",
        "eslint": "^5.9.0",
        "eslint-config-alloy": "^1.4.2",
        "eslint-import-resolver-node": "^0.3.2",
        "eslint-loader": "^2.1.1",
        "eslint-plugin-import": "^2.14.0",
        "eslint-plugin-jsx-a11y": "^6.1.2",
        "eslint-plugin-react": "^7.11.1",
        "fbjs": "^0.8.16",
        "gulp": "^3.9.1",
        "gulp-clean": "^0.3.2",
        "gulp-rename": "^1.2.2",
        "gulp-replace": "^0.6.1",
        "gulp-uglify": "^3.0.0",
        "hard-source-webpack-plugin": "^0.13.1",
        "hoist-non-react-statics": "^2.3.1",
        "html-webpack-plugin": "^5.0.0-alpha.17",
        "identity-obj-proxy": "^3.0.0",
        "inquirer": "^5.1.0",
        "jest": "^25.1.0",
        "jest-canvas-mock": "^2.2.0",
        "jest-html-reporter": "^3.2.0",
        "jsdom": "^16.4.0",
        "less-loader": "^5.0.0",
        "less-vars-to-js": "^1.1.2",
        "mini-css-extract-plugin": "^1.3.3",
        "mockjs": "^1.0.1-beta3",
        "node-fetch": "^2.6.1",
        "optimize-css-assets-webpack-plugin": "^5.0.3",
        "os-browserify": "^0.3.0",
        "path-browserify": "^1.0.1",
        "postcss-loader": "^3.0.0",
        "postcss-plugin": "^1.0.0",
        "react-dev-utils": "^10.2.1",
        "redbox-react": "^1.2.10",
        "redux-mock-store": "^1.5.4",
        "run-sequence": "^2.2.1",
        "script-ext-html-webpack-plugin": "^2.1.4",
        "stream-browserify": "^3.0.0",
        "style-loader": "^1.1.3",
        "sugarss": "^1.0.1",
        "terser-webpack-plugin": "^2.3.5",
        "thread-loader": "^2.1.3",
        "webpack": "^5.11.1",
        "webpack-dev-server": "^4.0.0-beta.0",
        "webpack-manifest-plugin": "^3.0.0",
        "webpack-merge": "^4.2.2"
    },

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

please fill out all fields, otherwise we can't help
