### ISSUE TITLE
Type misalign between webpack and webpack-sources

### ISSUE THREAD

**Issue by Austaras** [webpack/webpack#12294]
# Bug report

In webpack's declarations.d.ts, `Source` is 
```ts
export abstract class Source {
		size(): number;

		map(options?: MapOptions): Object;
```
while in `@types/webpack-sources`, it is
```
    map(options?: MapOptions): RawSourceMap | null;
```

**What is the expected behavior?**
typing of webpack and webpack-sources should be compatible. 

In this case I believe the latter is more detailed, so it should be used. BTW, why doesn't webpack use this declaration but instead write its own?

**Other relevant information:**
webpack version:  5.11.1

**Comment by alexander-akait** [comment]
Please respect time of other developers and use the issue template

**Comment by Austaras** [comment]
updated

**Comment by alexander-akait** [comment]
Update we can improve types here, PR welcome

**Comment by alexander-akait** [comment]
bump

**Comment by alexander-akait** [comment]
@TheLarkInn Should be easy, very annoing to lose types here

**Comment by TheLarkInn** [comment]
@Austaras would you be willing to submit a fix here?

**Comment by alexander-akait** [comment]
@TheLarkInn We already have fix https://github.com/webpack/webpack/pull/16805 :smile:
