### ISSUE TITLE
Problem with windows `\\` paths

### ISSUE THREAD

**Issue by J-Brk** [webpack/webpack#12305]
# Bug report

**What is the current behavior?**
When using webpack with the hot command it throws a directory exception on processing the font files. The issue only occurs when using the hot command.

Currently I'm using Laravel Mix as webpack wrapper and I believe the issue is caused by webpack and not by the Laravel Mix package (unconfirmed).

The following error occurs when running the hot command:
```
C:\wamp64\www\project\node_modules\webpack\lib\util\fs.js:141
                throw new Error(
                ^

Error: \fonts\vendor\@fortawesome\fontawesome-pro\webfa-brands-400.eot is neither a posix nor a windows path, and there is no 'dirname' method defined in the file system
    at dirname (C:\wamp64\www\project\node_modules\webpack\lib\util\fs.js:141:9)
    at C:\wamp64\www\project\node_modules\webpack\lib\Compiler.js:790:19
    at arrayIterator (C:\wamp64\www\project\node_modules\neo-async\async.js:3467:9)
    at timesSync (C:\wamp64\www\project\node_modules\neo-async\async.js:2297:7)
    at Object.eachLimit (C:\wamp64\www\project\node_modules\neo-async\async.js:3463:5)
    at emitFiles (C:\wamp64\www\project\node_modules\webpack\lib\Compiler.js:536:13)
    at C:\wamp64\www\project\node_modules\webpack\lib\util\fs.js:182:5
    at Immediate.<anonymous> (C:\wamp64\www\project\node_modules\memfs\lib\volume.js:684:17)
    at processImmediate (internal/timers.js:461:21)
```

### Steps To Reproduce:
1. Using Laravel Mix Version: 6.0.0-beta.17
2. Installing the `@fortawesome/fontawesome-pro` package
2. Running `mix watch --hot`

**What is the expected behavior?**
I expect webpack to complete the build process and serve the result.

### Additional information:

The exception occurs when it tries to process the following input:
` absPath = \fonts\brlnsr-webfont.eot `
https://github.com/webpack/webpack/blob/a62ddbd0e72ba3684e9fa25e30cd40324381feeb/lib/util/fs.js#L133-L145

I was able to solve the problem by changing line 138 from
https://github.com/webpack/webpack/blob/a62ddbd0e72ba3684e9fa25e30cd40324381feeb/lib/util/fs.js#L138
to 
```js
} else if (absPath.startsWith("\\") || absPath.length > 1 && absPath[1] === ":") { 
```

However I'm not sure if this is the correct solution for the problem / if there is a root cause.

**Other relevant information:**
webpack version:  5.11.1
Node.js version: v14.15.3
Operating System: Windows 10 19041.685
Additional tools: Laravel Mix

**Comment by alexander-akait** [comment]
Please create reproducible test repo, maybe bug on laravel mix side, can't reproduce using pure webpack without extra boilerplates

**Comment by jasongrout** [comment]
We have a report of a very similar problem at https://github.com/jupyterlab/jupyterlab/issues/9819 (but in our case, with the `join` method). It does seem like using UNC paths (which are windows paths that start with `\\`, not with `<drive>:`) falls through to the error case instead of being caught in https://github.com/webpack/webpack/blob/a62ddbd0e72ba3684e9fa25e30cd40324381feeb/lib/util/fs.js#L138

**Comment by alexander-akait** [comment]
@jasongrout yep, bug :disappointed: Feel free to send a fix

**Comment by jasongrout** [comment]
> @jasongrout yep, bug 😞 Feel free to send a fix

See https://github.com/webpack/webpack/pull/12714. Thanks!
