### ISSUE TITLE
Segmentation fault (core dumped) Error 139 (Webpack 5.11.1)

### ISSUE THREAD

**Issue by Ray-Garraty** [webpack/webpack#12308]
Hi! I've started creating a [small educational project](https://github.com/Ray-Garraty/frontend-project-lvl3) using Webpack. When I try to make an initial build, I get the following error message:
```
Segmentation fault (core dumped)
npm ERR! code 139
npm ERR! path /home/ray-garraty/Documents/frontend-project-lvl3
npm ERR! command failed
npm ERR! command sh -c webpack
```
Here's the complete error log: [2020-12-31T16_11_52_774Z-debug.log](https://github.com/webpack/webpack/files/5759860/2020-12-31T16_11_52_774Z-debug.log)
Is there a problem with my Webpack config, or maybe smth else?
P.S.: I've tried reinstalling nvm, deleting and reinstalling the 'node_modules' folder and rebuilding dependencies, but it didn't work.

**Comment by alexander-akait** [comment]
You have ` "type": "module",` in package.json, but `webpack.config.js` in common JS format, rename `webpack.config.js` to `webpack.config.cjs` (supporting ES modules configuration syntax is in progress, we have the issue in webpack-cli repo)

**Comment by swayamSixt** [comment]
> You have ` "type": "module",` in package.json, but `webpack.config.js` in common JS format, rename `webpack.config.js` to `webpack.config.cjs` (supporting ES modules configuration syntax is in progress, we have the issue in webpack-cli repo)

Changing the configuration back to `webpack.config.cjs` and using `require()` and `module.exports` still throws this Segmentation Fault issue!!
<img width="1403" alt="Screen Shot 2021-11-28 at 6 07 12 PM" src="https://user-images.githubusercontent.com/77677017/143768264-e4fdda79-5a45-4f4f-8136-7a5e44ab3957.png">

**Comment by alexander-akait** [comment]
Yarn has problems with ESM, please open an issue in their repo, we can't fix it here, also Node.js has bugs with `import()` too
