### ISSUE TITLE
ReferenceError: __webpack_require__ is not defined

### ISSUE THREAD

**Issue by ljwagerfield** [webpack/webpack#12300]
# Bug report

**What is the current behaviour?**

Importing a third-party module that also happened to be distributed w/ Webpack fails with the following:

```
ReferenceError: __webpack_require__ is not defined
```

**Steps to reproduce.**

1. Create a dist of a module such that the dist code looks something like:

    ```javascript
    !function(e,t){"object"==typeof exports&&"object"==typeof module?module.exports=t():"function"==typeof define&&define.amd?define([],t):"object"==typeof exports?exports.HSHeader=t():e.HSHeader=t()}(window,function(){return d={"./src/js/hs-header.js":function(module,__webpack_exports__,__webpack_require__){"use strict";eval("__webpack_require__.r(__webpack_exports__); ...
    ```

2. Import this dist'd module into another application.

3. The re-webpacked code of the above module becomes as follows. (Notice `__webpack_require__` -> `__nested_webpack_require_285__`, but it misses one, hence "not defined" error at runtime.)

    ```javascript
    !function(e,t){ true?module.exports=t():0}(window,function(){return d={"./src/js/hs-header.js":function(module,__webpack_exports__,__nested_webpack_require_285__){"use strict";eval("__webpack_require__.r(__webpack_exports__); ...
    ```

4. The `__webpack_require__` within the dist'd module causes a runtime error of `ReferenceError: __webpack_require__ is not defined`

5. This is because `__webpack_require__` is replaced with `__nested_webpack_require_285__`, yet the code inside the `eval` keeps the existing (now broken) reference to `__webpack_require__`.

**What is the expected behaviour?**

- No error.

- Possibly the `__webpack_require__` inside the `eval` should also be replaced with `__nested_webpack_require_285__`, but it isn't for some reason?

(Note: the third-party library that I'm importing (that webpack breaks) is not under my control.)

**Other relevant information:**

webpack version (my app):  `5.5.1`
webpack version (third-party module):  `?.?.?`
Node.js version: `v12.19.0`
Operating System: macOS Big Sur

**Comment by alexander-akait** [comment]
Yep, limitation, but we can improve this

**Comment by 1215904405a** [comment]
chrome56 version  equally
