### ISSUE TITLE
Initial vendor chunks not respecting minSize

### ISSUE THREAD

**Issue by airasyaqub** [webpack/webpack#12307]
# Bug report

**What is the current behavior?**

Changing minSIze to 520KB generates synchronous ( initial ) vendor chunk of size 517KB. 

**If the current behavior is a bug, please provide the steps to reproduce.**

I have two entry points with async/sync modules.

```
// a.js
import { run } from "./app/app";
import ("lodash");
import "bootstrap";
import "./main.scss";
import { AlertService } from "./app/alert.service";
import { ComponentService } from "./app/component.service";
const alertService = new AlertService();
const componentService = new ComponentService();
run(alertService, componentService);
```

```
// b.js
import { run } from "./app/app";
import ("lodash");
import ("bootstrap");
import "./main.scss";
import { AlertService } from "./app/alert.service";
import { ComponentService } from "./app/component.service";
const alertService = new AlertService();
const componentService = new ComponentService();
run(alertService, componentService);
```
The optimization plugin config **without custom minSize** is as follows where everything generated as expected

```
  optimization: {
    minimize: false,
    splitChunks: {
      chunks: "initial",
      // minSize: 520000,
    }
  }
```
generated chunks with above config
```
4.0430a28c67c95515623d.bundle.js   509 KiB       4  [emitted] [immutable]  [big]  
5.177897857c70dc7eaa96.bundle.js   531 KiB    5, 6  [emitted] [immutable]  [big]  
6.507730afe61b6ceecf70.bundle.js   531 KiB       6  [emitted] [immutable]  [big]  
a.ac0e9c622ffd0aace615.bundle.js  10.2 KiB       1  [emitted] [immutable]         a
a~b.1fafc50267cf2e753b51.bundle.js   148 KiB       0  [emitted] [immutable]         a~b
b.b9218b218e06859b7b0d.bundle.js  18.5 KiB       2  [emitted] [immutable]         b
imgs/webpack.523e1b932381f19b26060571ccfc7a31.svg  2.29 KiB          [emitted] [immutable]         
index.html  1.77 KiB          [emitted]                     
vendors~a.50adedf6af3fbeb56ed3.bundle.js   517 KiB    3, 4  [emitted] [immutable]  [big]  vendors~a
```

If uncommented minSize from above config following is the generated output

```
3.4fe397947d6a74a38870.bundle.js   509 KiB       3  [emitted] [immutable]  [big]  
4.5289e4657b1f86d851f1.bundle.js   531 KiB    4, 5  [emitted] [immutable]  [big]  
5.ad452c25e6aa46a1cdff.bundle.js   531 KiB       5  [emitted] [immutable]  [big]  
a.974925a2f0898c477b9e.bundle.js   158 KiB       0  [emitted] [immutable]         a
b.2cd9e2bdb8245dd78851.bundle.js   165 KiB       1  [emitted] [immutable]         b
imgs/webpack.523e1b932381f19b26060571ccfc7a31.svg  2.29 KiB          [emitted] [immutable]         
index.html  1.72 KiB          [emitted]                     
vendors~a.e51176a01049374bf6f1.bundle.js   517 KiB    2, 3  [emitted] [immutable]  [big]  vendors~a
```
Note that a.bundle.js and b.bundle.js is increased as main.scss is not spitted out to separate chunk due to minSIze restriction. But its still creating vendor~a chunk even tho its size is 517kb.

If we set minSize to significantly increased number i.e 999999999
we get the expected output with no initial chunks

```
2.4d4ab8a0eebe11a6149c.bundle.js   509 KiB       2  [emitted] [immutable]  [big]  
3.434ee8f39d57e8f7dee7.bundle.js   531 KiB    3, 4  [emitted] [immutable]  [big]  
4.d890b35757aa13206d0e.bundle.js   531 KiB       4  [emitted] [immutable]  [big]  
a.16d5f9d877a088513a7d.bundle.js   674 KiB    0, 2  [emitted] [immutable]  [big]  a
b.062bc745c5f2e5e55948.bundle.js   165 KiB       1  [emitted] [immutable]         b
imgs/webpack.523e1b932381f19b26060571ccfc7a31.svg  2.29 KiB          [emitted] [immutable]         
index.html  1.66 KiB          [emitted]           
```

**What is the expected behavior?**
When setting minSize to 520kb vendor~a chunk should not be generated as happening  with main.scss, respecting minSize.

**Other relevant information:**
webpack version:  4.44.2
Node.js version: 12.19.0
Operating System: ubuntu budgie
Additional tools:

**Comment by sokra** [comment]
minSize is an estimation of the size before minimizing. For technical reasons we don't have the final size when we need to decide which module to put in which chunk

**Comment by airasyaqub** [comment]
@sokra thanks a lot for replying. Yeah I am aware of the fact that minSize is before minimizing, which is the reason I have used **minimize: false** option to get better idea of chunks size. I still don't get your second statement completely though.  So we don't have the final size to decide thus not have size to compare with minSize. Does that mean webpack will always create initial vendor chunks ?  

According to my understanding on that statement of yours webpack will check if we have disabled vendor cache group or not. If yes, it will not create any initial vendor chunk. If not, vendor chunk will be generated no matter what minSize restriction. In case of large minSize let say 9Mb webpack is not generating any initial vendor chunks so it must have some kind of max limit range in code too where if exceeded webpack will evidently not create any vendor chunk.

**Comment by sokra** [comment]
Maybe I have to note that 517kiB > 520000 bytes

**Comment by airasyaqub** [comment]
My bad. So yeah 517kib is approx 529408 bytes. But still even if I change minSize to 600000 bytes splitchunkplugin still generating vendor~a chunk !

**Comment by airasyaqub** [comment]
Here is the graph with new minSize value.

```
  optimization: {
    minimize: false,
    splitChunks: {
      chunks: "initial",
      minSize: 600000
    }
  }
```

![Screenshot from 2021-01-03 21-54-53](https://user-images.githubusercontent.com/30695220/103484195-9fa79200-4e0e-11eb-8b9b-cadd5ba0703a.png)

**Comment by airasyaqub** [comment]
@alexander-akait can you help me out in here please. I will be glad of it !

**Comment by sokra** [comment]
I don't know what's causing that, could you provide a repro so we can test this locally too.

Maybe also check if this is already fixed in webpack 5.

**Comment by airasyaqub** [comment]
@sokra  https://github.com/airasyaqub/webpack_tutorial 
above repo contains the code !

**Comment by sokra** [comment]
Thanks. I found the problem. It's a bug in webpack.

**Comment by airasyaqub** [comment]
Kudos to you @sokra . So should I test it now reinstalling same version of webpack ?

**Comment by sokra** [comment]
I'll also backport this to webpack 4

**Comment by airasyaqub** [comment]
@sokra  is it merged to main branch now ? I have reinstalled my webpack dependencies but still getting the issue. If not, kindly can I know approx when will it be pushed to production

**Comment by sokra** [comment]
Probably today

**Comment by airasyaqub** [comment]
@sokra the same bug is being produced now.  I just tested it with same above configiration and files. Why is that happening now !
