### ISSUE TITLE
the  file in  the   compilation.assets  object  does not  have  existsAt  property  

### ISSUE THREAD

**Issue by duanbaosheng** [webpack/webpack#12313]
i  write  a  webpack  plugin,  use  compiler.hooks.afterEmit.tapAsync  function.
in the  callback,  i can got compilation object, and  then  compilation.assets[fileName], it got the file object,
in  the  webpack4, i can  get   the filePath through file.existsAt ,  
but in the webpack5,  file.existsAt   is undefined.

i  wonder  the API  is removed in the  webpack5? 
there  has a  replace  method or property ?

node 10.15
webpack 5.11.1

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
