### ISSUE TITLE
Unexpected behaviour during error handling

### ISSUE THREAD

**Issue by s-panferov** [webpack/webpack#1232]
I am the author of https://github.com/s-panferov/awesome-typescript-loader and I have a problem with my async loader:

Pseudo-code:

```
let callback = this.async();

/* inside promise handler */
try {
    callback(null, result.text, sourceMap);
} catch(e) {
    console.error('Caught', e)
    // I'm here! What I need to do in that case?  
}
```

Console output:
```
Caught { [ModuleParseError: Module parse failed: /Users/panferov-s/Workspace/arui/node_modules/react-hot-loader/index.js!/Users/panferov-s/Workspace/awesome-typescript-loader/dist/index.js?compiler=ntypescript&rewriteImports=arui&module=commonjs!/Users/panferov-s/Workspace/arui/src/popup/common/popup.ts Line 112: Unexpected token ,
You may need an appropriate loader to handle this file type.
|             || nextAttachment !== attachment) {
|             this.setState({
|                 attachment: ,
|                 targetAttachment: ,
]             });

/** stripped */
```

Versions:

```
    "webpack": "^1.10.1",
    "webpack-dev-server": "^1.10.1"
```

The big problem here is that compilation freezes in webpack-dev-server

**Comment by shama** [comment]
It is because you're informing the loader that it is async. Which means it will wait for you to call `callback()` to continue. Upon an error, you're not calling the `callback()` so it hangs waiting for it.

The 1st argument of the callback is for errors: `callback(err)` instead of `null`. Although it is likely you can just remove that `try catch` and let webpack deal with the error though.

**Comment by s-panferov** [comment]
@shama 	you don't understand the problem. I **call** the callback, but the call throws an exception that takes place in some other loader or inside webpack core (e.g. if syntax error is in the file) and the error returns to my loader. But I can't call the callback another one time, because it throws an exception in that case!

**Comment by shama** [comment]
Ah you're right sorry. Could you post a full stack trace or even better an example repo that duplicates the issue so I can take a look? Thanks!

**Comment by s-panferov** [comment]
@shama, ok, I'll try to provide some example.

**Comment by s-panferov** [comment]
I was because of `bail: true` was enabled in my config file. 

So I have to write https://github.com/s-panferov/awesome-typescript-loader/blob/master/src/index.ts#L357-L362. The problem is solved, but I thing that the behaviour of the `callback` function in bail mode must be documented somewhere.

**Comment by shama** [comment]
@s-panferov Oh nice find! The documentation is openly editable to anyone. Would you mind adding a note about it here http://webpack.github.io/docs/configuration.html#bail? Thanks!

**Comment by bebraw** [comment]
@s-panferov Can you look at that documentation bit so we can get this closed?

**Comment by pksjce** [comment]
This issue was moved to webpack/webpack.io#148
