### ISSUE TITLE
watching in webpack 5 does not generate new code

### ISSUE THREAD

**Issue by rod24574575** [webpack/webpack#12328]
# Bug report

**What is the current behavior?**
When using watching mode in webpack 5 with yarn workspace and import all, the initial building is fine, while the following changes do not trigger code regeneration.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Clone this [repo](https://github.com/rod24574575/webpack5-watch-broken).
2. Run `yarn run webpack --mode development -w`
```
asset test.js 4.24 KiB [compared for emit] (name: main)
runtime modules 668 bytes 3 modules
cacheable modules 88 bytes
./packages/test-entry/index.js 67 bytes [built] [code generated]
./node_modules/test-dep1/index.js 21 bytes [built] [code generated]
webpack 5.11.1 compiled successfully in 112 ms
```
3. After the initial building, check the result of generated code.
```shell
$ node dist/test.js;
# [ 'aa' ]
```
4. Modify the exported variable `aa` to `bb` in `packages/test-dep1/index.js`, and we could find that webpack wrongly uses cache and does not generate new code.
```
assets by status 4.24 KiB [cached] 1 asset
cached modules 88 bytes (javascript) 668 bytes (runtime) [cached] 5 modules
webpack 5.11.1 compiled successfully in 18 ms
```
```shell
$ node dist/test.js;
# [ 'aa' ]
```

**What is the expected behavior?**
In the step 4, webpack should generate new code and the execution result should be like following.
```shell
$ node dist/test.js;
# [ 'bb' ]
```

**Other relevant information:**
webpack version:  5.11.1
Node.js version: 12.19.0
Operating System: Ubuntu 18.04.4 LTS
Additional tools: yarn version 1.21.1

**Comment by sokra** [comment]
Seems like you accidentally disabled symlink handling (`resolve.symlinks: false` is set), but you are actually using symlinks due to the use of yarn workspaces. Enable `resolve.symlinks: true` or better just omit the option to use the default.

**Comment by rod24574575** [comment]
Oh... it seems to work fine after removing `resolve.symlinks: false`. I think adding this is to workaround for ts-loader/ts-jest, which is currently replaced with babel-typescript/jest-with-babel in my project. However, webpack 4 just works fine even if I add this config. Is this behavior change intended? If not, will it be fixed in future?

**Comment by alexander-akait** [comment]
> Is this behavior change intended?

Yes

> If not, will it be fixed in future?

No, there is nothing to fix

> webpack 4 just works fine even

we have some bugs in webpack@4, so it is fix


Feel free to feedback
