### ISSUE TITLE
Export WebpackError

### ISSUE THREAD

**Issue by jantimon** [webpack/webpack#12323]
## Feature request

**What is the expected behavior?**

I am trying to notify webpack about an error which occurred in my plugin:

```js
compilation.errors.push( new Error( "Something went very very wrong  😢 ") );
```

Is this the correct way to add an error?

If not you can close this issue right away.

Otherwise please read on  😉 

`compilation.errors` will accept only Errors of type `WebpackError`:

![webpack-error](https://user-images.githubusercontent.com/4113649/103557718-e7ccc000-4eb3-11eb-9a26-8663c447154e.png)

Would it be  possible to export `WebpackError` as `compiler.webpack.WebpackError`?

**What is motivation or use case for adding/changing the behavior?**

Adding errors of the correct type to the webpack compilation.

**How should this be implemented in your opinion?**

Export `compiler.webpack.WebpackError` or allow `Error` to be added to `compilation.errors`

**Are you willing to work on this yourself?**
yes

**Comment by alexander-akait** [comment]
No need to export this, `compilation.errors` should accept `Error`

**Comment by jantimon** [comment]
Thanks @alexander-akait for your quick response 👍

So in that case it is just a small bug in the current typings?

**Comment by sokra** [comment]
`WebpackError` is exported since 5.11.0: https://github.com/webpack/webpack/commit/745a5830403a9f1a2e1d0d81833aa38a5b5ca1e5

Nothing will break if you push a normal `Error` instance, but using `WebpackError` will allow to attach more information to the error, which will improve the way it's displayed in the Stats.

**Comment by sokra** [comment]
> Is this the correct way to add an error?

yes

**Comment by jantimon** [comment]
Cool thanks 👍

Adding a normal `Error` is causing only a type error (not a real runtime error).
