### ISSUE TITLE
webpack will compile twice in watch mode after addDependency in a compilation. 

### ISSUE THREAD

**Issue by JayFate** [webpack/webpack#12336]
# Bug report

**What is the current behavior?**

In watch mode, webpack will compile twice  after addDependency in a compilation

**If the current behavior is a bug, please provide the steps to reproduce.**

1. git clone git@github.com:JayFate/joyful-webpack5-demo.git
2. cd joyful-webpack5-demo && npm install
3. cd joyful-webpack5-demo/packages/joyful && npm install
4. cd joyful-webpack5-demo/demo
5. node ../packages/joyful/bin/joy.js build

webpack will compile twice in watch mode after addDependency in a compilation. Errors in compilation will be printed twice.
![image](https://user-images.githubusercontent.com/48240828/103603330-56a82880-4f49-11eb-86d8-15b615af21f8.png)

please look into this [demo](https://github.com/JayFate/joyful-webpack5-demo)

**What is the expected behavior?**

webpack should not compile again  after addDependency in a compilation. Errors in compilation should be printed once only.
![image](https://user-images.githubusercontent.com/48240828/103603709-3462da80-4f4a-11eb-80fb-550777db4a73.png)

**Other relevant information:**
webpack version:  5.11.1
Node.js version: 12.0.0
Operating System: macOs big sur
Additional tools:

**Comment by JayFate** [comment]
I fixed it in https://github.com/webpack/webpack/pull/12337.

this is my first commit and I‘m grateful for any help.

**Comment by alexander-akait** [comment]
Answer here https://github.com/webpack/webpack/pull/12337#issuecomment-754855753, feel free to feedback

> What if my compilation depends on a file which I'm not sure whether it exists before my compilation? Users of my tool will not ensure all files needed in compilation exists.

You can do it on tool side, in loader you can use `this.fs` to do it (calls will be cached), if you provide more context I will help you
