### ISSUE TITLE
If you specify the PascalCase directory name in the Entry key, it will be converted to CamelCase.

### ISSUE THREAD

**Issue by fagai** [webpack/webpack#12346]
# Bug report

**What is the current behavior?**

If you specify the PascalCase directory name in the Entry key, it will be converted to CamelCase.

**If the current behavior is a bug, please provide the steps to reproduce.**

```js
entry : {
    'Foo/FooBar/name': 'src/name.js'
}
```

When it is actually output, the directory will be camelCase.
`{path}/foo/fooBar/name.js`

**What is the expected behavior?**

output
`{path}/Foo/FooBar/name.js`

**Other relevant information:**
webpack version:  5.11.0
Node.js version: 12
Operating System: Intel CPU macOS
Additional tools: nodebrew
Suppose you specify the following Entry.

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Respect time of other developers.

I will reopen this after you fix it

**Comment by fagai** [comment]
I didn't know if it was a bug or normal behavior, so I chose the other one.
to correct.

**Comment by alexander-akait** [comment]
What is use case for using `Foo/FooBar/name` as entry name?

**Comment by fagai** [comment]
On my system, multiple applications are contained in one repository.
The reason I wanted to cut the directory with the Entry key is because I wanted to output it as a directory for each application.

My system is legacy and I had to put out js for each page first.
At that time, when the directory name (Controller name) was set to PascalCase, the output was CamelCase, so I asked a question.
If it's a webpack spec, we'll follow it.

**Comment by sokra** [comment]
We don't convert the casing in webpack. Maybe these lower cased directories already exist before running webpack. Try to remove all of them and run webpack again

**Comment by fagai** [comment]
Cleared the cache and removed the output directory. The problem did not go away.

**Comment by fagai** [comment]
Oh, I'm sorry.
When I deleted the actual directory, it worked as expected.

Thank you.
