### ISSUE TITLE
Bound function expression callbacks not handled correctly when using AMD require()

### ISSUE THREAD

**Issue by bregenspan** [webpack/webpack#1234]
When using Webpack to package a file containing an AMD-style `require()` with a bound expression callback like:

```
require(['dependency'], function (dependency) {
   ...
}.bind(this));
```

The `this` context within the callback fails to match the expected because the call is wrapped in an outer function expression:

```
__webpack_require__.e/* require */(1, function(__webpack_require__) { var __WEBPACK_AMD_REQUIRE_ARRAY__ = [__webpack_require__(1)]; (function (dependency) {
 ...
}.bind(this).apply(null, __WEBPACK_AMD_REQUIRE_ARRAY__));});
```

Example of the issue:

https://github.com/bregenspan/webpack-amd-require-issue
https://rawgit.com/bregenspan/webpack-amd-require-issue/master/index.html

One quick remedy that solves this particular case (but needs further testing) is the following patch:
https://gist.github.com/bregenspan/6cb090011fafe428fc97 .  But I wanted to make sure this is indeed an issue and there isn't already a configuration option I'm missing somewhere that would solve this, before submitting any PR.

-Ben

PS: thank you for releasing + maintaining this great tool!

**Comment by sokra** [comment]
It is an issue. Do you wan to send your patch as PR including an test?

**Comment by bregenspan** [comment]
@sokra sorry for the delay -- I haven't had a solid block of free time to familiarize myself with the test suite yet. Do you have any thoughts about the best way to approach testing for this one? Looking at past changes that touched similar functionality, I could see tests working for it both in the "parsing" and "runtime" phases but need to investigate further.
