### ISSUE TITLE
Node.js version doesn't generate snapshot/cache in webpack 5

### ISSUE THREAD

**Issue by zlk89** [webpack/webpack#12342]
# Bug report

**What is the current behavior?**
When using Node.js version's webpack command, it doesn't generate snapshot/cache, while using webpack-cli, it works fine.

**If the current behavior is a bug, please provide the steps to reproduce.**

- Go to https://github.com/zlk89/webpack-reprods/tree/nodejs-no-snapshot
- `yarn` to install dependencies
- `yarn compile-nodejs` - compile using Node.js interface, which doesn't generate cache (see ./.webpack_cache folder)
- `yarn compile-cli` - compile using cli, which generates cache correctly

**What is the expected behavior?**
`yarn compile-nodejs` should generate snapshot/cache

**Other relevant information:**
webpack version:  5.11.1
Node.js version: v12.16.1
Operating System: MacOS Catalina
Additional tools:

**Comment by sokra** [comment]
A compiler created with `webpack(config)` need to be closed with `compiler.close(callback)`.

Best just use the shortcut form like that:

``` js
webpack(config, (err, stats) => {
```

It automatically closes the compiler.
