### ISSUE TITLE
Customize filename for ModuleFederationPlugin shared dependencies

### ISSUE THREAD

**Issue by artchenamazon** [webpack/webpack#12351]
## Feature request

**What is the expected behavior?**

Shared dependencies are bundled into files such as `vendors-node_modules_react_index_js_bundle.js`. I didn't find a way to customize the filename via webpack configuration, or ModuleFederationPlugin options.

**What is motivation or use case for adding/changing the behavior?**

I have concern about cache busting with the default naming convention. When a shared dependency version updates, doesn't the filename stays the same? In my current application, we append contenthash to the filename as a way to invalidate cache when the bundle content changes.

**How should this be implemented in your opinion?**

Add a `filename` property under each `shared` option object of ModuleFederationPlugin that supports interpolation like [contenthash].

Would like opinion on feasibility or better options.

**Are you willing to work on this yourself?**
yes

**Comment by sokra** [comment]
The usually webpack options apply here:

``` js
// in the normal config:
output: {
  filename: "[contenthash].js"
}
```

https://webpack.js.org/configuration/output/#outputfilename

**Comment by artchenamazon** [comment]
Thanks!
