### ISSUE TITLE
 __webpack_require_ is not defined

### ISSUE THREAD

**Issue by 17biubiu** [webpack/webpack#12354]
# Bug report

**What is the current behavior?**
when i use quill@1.x, it work. but 2.0 is not work. it report error is __webpack_require_ is not defined

**If the current behavior is a bug, please provide the steps to reproduce.**
compare the version of quill. webpack5 seems not support module:"es6"
the quill@1.x config is
`{
        test: /\.ts$/,
        use: [{
          loader: 'ts-loader',
          options: {
            compilerOptions: {
              declaration: false,
              target: 'es5',
              module: 'commonjs'
            },
            transpileOnly: true
          }
        }]
      }`
the quill@2 config
`test: /\.ts$/,
  use: [
    {
      loader: 'ts-loader',
      options: {
        compilerOptions: {
          declaration: false,
          module: 'es6',
          sourceMap: true,
          target: 'es6',
        },
        transpileOnly: true,
      },
    },
  ],`

**What is the expected behavior?**
it can work well

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by 17biubiu** [comment]
@sokra duplicate [#11277,](https://github.com/webpack/webpack/issues/11277).

**Comment by alexander-akait** [comment]
@17biubiu Please create reproducible est repo, because it was fixed

**Comment by 17biubiu** [comment]
@alexander-akait i upgrade webpack@latest, it work fine.
