### ISSUE TITLE
WP5 Module Federation refresh remoteEntry and/or external modules

### ISSUE THREAD

**Issue by raix** [webpack/webpack#12350]
## Feature request

**What is the expected behavior?**
An external component should be able to invalidate the remoteEntry and cause a refresh of the external module - currently we would have to do a full page reload.

**What is motivation or use case for adding/changing the behavior?**
* If the app is able to detect a new release of the external component a reload might be required - instead of a full page reload we could refresh the module. _(it would likely be the module it self knowing if a refresh is needed)_
* If there was an issue in the loaded module eg. a UI Component having an issue - it would be nice to provide a pr. module refresh eg. letting the user trigger a "retry"
* If the external service is down for some reason the fallback module/component could likely detect when the service is up again and trigger a refresh of modules from that service

**How should this be implemented in your opinion?**
Client code could import a magical `import {refresh} from "webpack/module/federation/refresh"`
If used as an external module it would communication with the remoteEntry refresh mechanism updating module loader and resetting module cache. *(If used in the main application it could either be ignored or trigger a full page reload?)*

**Are you willing to work on this yourself?**
yes, despite being low on time and domain knowledge regarding the webpack code base - although the initial work would likely be figuring out if feasible / practical or if a full page reload is better.

**Comment by alexander-akait** [comment]
You can do it on application side... Don't know what you expected from webpack here

**Comment by raix** [comment]
@alexander-akait the module `remoteEntry` files containing the module loading with hashed urls etc. is afaik loaded as part of the main bundle. Unless we create our own custom loading of remote modules I don't quite see how it would be possible to reload the remoteEntry files and resetting the remote modules for that entry.
*(By custom I mean our own module loader eg.: [Example of manually loading modules from container](https://github.com/webpack/webpack/issues/11033#issuecomment-644349386))*

I might be missing out on some documentation of the internal webpack api's?

**Comment by rojasjandro89** [comment]
I have the same problem. I'm loading remotes that can be updated. A full refresh is required.

@alexander-akait can you elaborate a bit on how to do this from application side?

**Comment by alexander-akait** [comment]
Just reload browser browser, do you know when it happens?

**Comment by rojasjandro89** [comment]
@alexander-akait well that's what I'm doing now but it feels like we are in the 2000s forcing a full refresh like that for something that happens in the background. 

Ideally, unloading and/or refreshing a lazily loaded bundle should be as easy as loading it for the first time... a full browser reload feels like a slap in the face at that point.

**Comment by alexander-akait** [comment]
@rojasjandro89 I undestand your feelings, but bidirectional hmr for module federation is not an easy thing, it is in our roadmap, you can always send a PR

It was closed because we already have an issue about it, it is just duplicate...
