### ISSUE TITLE
Code Splitting issues after migration to Webpack 5 

### ISSUE THREAD

**Issue by holitics** [webpack/webpack#12365]
# Bug report

**What is the current behavior?**

Trying to use code splitting and chunks. If the entry "dependOn" option is used, and/or the optimization.runtimeChunk: 'single' option is used, the build succeeds and bundles are created correctly, but application always fails in either scenario during runtime launch with the following error:

```
Uncaught TypeError: (intermediate value)(intermediate value)(intermediate value).push is not a function
    at launch.bundle.js:1
(anonymous) @ launch.bundle.js:1

```

The cause is the first line of the bundle:

```
(typeof self !== 'undefined' ? self : this["webpackChunkdtr"] = typeof self !== 'undefined' ? self : this["webpackChunkdtr"] || []).push([[882],{
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Two scenarios trigger this behavior:

```
entry: {
    launch: {
      import: path.resolve(__dirname, "src/launch.js"),
      dependOn: 'shared'
    },
    shared: path.resolve(__dirname, "src/shared.js"),
}
```

or:

```
  optimization: {
    runtimeChunk: 'single'
  }

```
**What is the expected behavior?**

The application should load and execute correctly when the browser loads the page instead of empty white screen and the above error.

**Other relevant information:**

webpack version:  5.0.0-rc.6
Node.js version: v12.14.0
Operating System: OSX 10.14.6
Additional tools:

**Comment by sokra** [comment]
Looks like a incorrect `output.globalObject` config. Put brackets around the expression.

**Comment by holitics** [comment]
Hi @sokra, thanks for your response. I have tried that, various combinations of brackets or quote characters get me either the same error or nothing happens / loads at all. 

Here is what I currently have defined for globalObject:

```
output: {
    filename: "[name].bundle.js",
    path: path.resolve(__dirname, "public"),
    publicPath: "/",
    globalObject: ('typeof self !== "undefined" ? self : this')
}
```

I noticed some people talking about weird similar behavior in  https://github.com/webpack/webpack/issues/6522, figured I would mention it.

**Comment by AviVahl** [comment]
Try: '(typeof self !== "undefined" ? self : this)'

**Comment by holitics** [comment]
Hi @AviVahl, so I tried that. With that I get the nothing loading result (I get blank page).

If I debug in the browser, the first line is:

`((typeof self !== "undefined" ? self : this)["webpackChunkdtr"] = (typeof self !== "undefined" ? self : this)["webpackChunkdtr"] || []).push([[826],{`

Looking at the "self" object (which is window), expanded, I see that the "**webpackChunkdtr**" object is an empty array.

Could there be a setting that I am missing in my **webpack.config.js** file that tells webpack to populate these arrays with the bundles? Please bear in mind WITHOUT any code splitting (i.e one huge bundle), it all works just fine.

Thanks.

**Comment by AviVahl** [comment]
Create a small repo that shows the splitting issue. Link to it here. There are other factors that affect loading of bundles, like how the html using them is created.

**Comment by holitics** [comment]
@AviVahl Great, I've put together a tiny repo example of what is going on. There is a README that will describe how to reproduce the issue.

[Repo With Splitting Issue](https://github.com/holitics/testwebpack5issue)

Thank you, please let me know if you have any questions.

**Comment by AviVahl** [comment]
If I uncomment the `dependOn` line and add `<script src="./fhirclient.bundle.js"></script>` to the `index.html` (right before the script that loads `index.bundle.js`), the app loads successfully.

I'm unsure whether this is intended behaviour, though.

@sokra, when using the `dependOn` field of an entry (`A`) to depend on another chunk (`B`), is it my responsibility (as the developer) to ensure chunk `B` loads in the HTML before `A`?

Regarding the `runtimeChunk` and/or `splitChunks` not working... I'll leave that to the core webpack team to assist. Out of my webpack knowledge depth in those parts.

**Comment by holitics** [comment]
@AviVahl - interesting, thanks for that! for some reason I assumed the `index.bundle` would have an automatic reference put into it for the generated **fhirclient** bundle. I enabled `runtimeChunk` and it seems the same applies, it works as long as `<script src="./runtime.bundle.js"></script>` is loaded first. Not sure if that's the way it's supposed to work, but that does do the trick!

As far as `splitChunks`, that generates chunks with numbers, not sure how to address that.

**Comment by alexander-akait** [comment]
What about https://webpack.js.org/guides/code-splitting/#entry-dependencies?

**Comment by holitics** [comment]
Hi @alexander-akait, that documentation is very helpful and that is what I used initially to get this far, but was not clear with respect to explicitly having to include the generated chunks in the source script. Also I haven't even explored the `SplitChunks` optimization that much (looks very powerful and useful in terms of space saving), but at an early stage it was clear that it was not loading the newly generated chunks. Maybe the solution is to use the `SplitChunks` "names" feature, and then explicitly include loading those chunks in the source...

**Comment by alexander-akait** [comment]
@holitics So, do you need help more?

**Comment by holitics** [comment]
@alexander-akait, I have not had a chance to experiment with `SplitChunks` again. At this point I have the application working with WP5 as long as I explicitly reference the chunks at the top of the file depending on it. I'll close this issue right now and will re-open if I find there is a problem with `SplitChunks`. Thanks to everyone that helped to figure this out!
