### ISSUE TITLE
Server-side rendering does not work with Module Federation

### ISSUE THREAD

**Issue by suhanw** [webpack/webpack#12378]
# Bug report

**What is the current behavior?**

I am able to build and start the host and remote servers successfully, but I get this server error when loading the page in the browser. The browser remains spinning until I stop the server. 
```
(node:66910) UnhandledPromiseRejectionWarning: Error: Cannot find module 'webpack/container/reference/remote'
Require stack:
- /Users/suhanwijaya/Desktop/wp5-ssr/host/build/server/bundle.js
while loading "./top-nav" from webpack/container/reference/remote
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.webpack/container/reference/remote (/Users/suhanwijaya/Desktop/wp5-ssr/host/build/server/bundle.js:171:18)
    at __webpack_require__ (/Users/suhanwijaya/Desktop/wp5-ssr/host/build/server/bundle.js:194:41)
    at handleFunction (/Users/suhanwijaya/Desktop/wp5-ssr/host/build/server/bundle.js:300:31)
    at /Users/suhanwijaya/Desktop/wp5-ssr/host/build/server/bundle.js:319:15
    at Array.forEach (<anonymous>)
    at Object.__webpack_require__.f.remotes (/Users/suhanwijaya/Desktop/wp5-ssr/host/build/server/bundle.js:282:36)
(node:66910) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:66910) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Minimal reproducible repo: https://github.com/suhanw/wp5-ssr

I included a README for the instructions to run locally. 

`host` server webpack config: https://github.com/suhanw/wp5-ssr/blob/main/host/webpack.server.config.js
`remote` server webpack config: https://github.com/suhanw/wp5-ssr/blob/main/remote/webpack.server.config.js

`remote` exposes the component `TopNav`, and `host` consumes and imports `TopNav` in the `App` component, here: 
https://github.com/suhanw/wp5-ssr/blob/main/host/client/components/App/index.js#L3

If you comment out the line above, SSR works (i.e., the `App` component is rendered on server-side correctly). 

PS: I was following this [example](https://github.com/module-federation/module-federation-examples/tree/408ced256b23206aac3b9c117ac63af73a504e2d/server-side-render-only) by @ScriptedAlchemy.  

**What is the expected behavior?**

`host` should be able to consume shared components exposed by `remote` for server-side rendering.

**Other relevant information:**
webpack version:  5.12.1
Node.js version: 14.15.3
Operating System: MacOS Catalina 10.15.6
Additional tools: None

**Comment by alexander-akait** [comment]
Please look at 

```
(node:66910) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:66910) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Something should be async, but not used in right way

**Comment by suhanw** [comment]
Thanks for pointing that out. 
```
UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
```
... was indeed causing the issue of browser spinning forever. 

This [commit](https://github.com/suhanw/wp5-ssr/commit/5f1d4e8e1dd9a991eb5e853c994bef6d3d6289d9) fixed it, so now it will catch and log the error and respond to the browser with "Error caught."

However, the error logged is still the same as `UnhandledPromiseRejectionWarning: Error: Cannot find module 'webpack/container/reference/remote'` in my original issue.

**Comment by alexander-akait** [comment]
Something wrong with loading runtime core, `webpack/container/reference/remote` should exists, can you check stats file and check all scripts tags in HTML?

**Comment by suhanw** [comment]
@alexander-akait thanks for helping me out. So I exported the stats files with `--json=webpack-stats.json` CLI flag, but I'm not really sure what to look for. 

[Server-side stats for HOST](https://gist.github.com/suhanw/20286d6a76c592d308b514ba299aa07c)
[Server-side stats for REMOTE](https://gist.github.com/suhanw/7b0e31bf03df834e1e145ff2d8fd5306)

The [HTML has the `remoteEntry` script tag](https://github.com/suhanw/wp5-ssr/blob/main/host/server/renderer.js#L10), but not sure if it has any bearing on server side rendering. 

Not sure if helpful, but here are also the stats for client-side builds: 
[Client-side stats for HOST](https://gist.github.com/suhanw/3bf3d07fd99cf34fa1faea1a7575c919)
[Client-side stats for REMOTE](https://gist.github.com/suhanw/8b40fdbb9613f06c8b72a721019df7ed)

**Comment by alexander-akait** [comment]
I recommend to ask this in https://github.com/module-federation/module-federation-examples, it is not place for personal helping, it is bug tracker, I can't even run you reproducible test repo - `cd ./remove && npm run dev` run infinity loop

**Comment by suhanw** [comment]
Sorry about that, I just pushed a fix for the infinite loop. 

But sure, I can open an issue there too. Thanks for your help in any case!

**Comment by jacob-ebey** [comment]
This is a simple case of a misconfigured externals: https://github.com/suhanw/wp5-ssr/pull/1

No bug here, this issue can be closed.

**Comment by suhanw** [comment]
amazing, thanks @jacob-ebey

**Comment by alexander-akait** [comment]
@jacob-ebey thanks
