### ISSUE TITLE
Webpack 5 cannot reuse filesystem cache in different file directory

### ISSUE THREAD

**Issue by worlddai** [webpack/webpack#12379]
# Bug report
I have submitted this question in stackoverflow, but I haven't received any reply。

https://stackoverflow.com/questions/65642712/webpack-5-cannot-reuse-caches-in-different-file-structures

**What is the current behavior?**
1. I use the file cache of Webpack5 through the following configuration, and set the cache files in a public folder

2. In the case of the file directory structure unchanged, build again. At this time, caching can be applied successfully, greatly reducing the build time

3. I copied the entire project code to the same directory as testbuild

4. Under the new directory testBuild, execute the build and find that the previously generated cache is not applied. It generates new ones

5. Supplementary Note: This test is to simulate the real CI construction process, and my goal is to significantly reduce the build time on CI construction

`cache: {
            type: 'filesystem',
            cacheDirectory: path.resolve(paths.cachePath,'prod-cache'),
  }`

**If the current behavior is a bug, please provide the steps to reproduce.**

Because of the problem of office environment, I can't code to GitHub warehouse. All I can offer is a few configuration fragments

**What is the expected behavior?**

In the case of the same code, different file directories can reuse the file cache

**Other relevant information:**

webpack version: 5.11.0
Node.js version: v10.15.3
Operating System: window 10
Additional tools:

**Comment by alexander-akait** [comment]
Duplicate https://github.com/webpack/webpack/issues/10400
