### ISSUE TITLE
callMemberChain doesn't trigger callback when tap for user defined function

### ISSUE THREAD

**Issue by McDaddy** [webpack/webpack#12385]
# Bug report

**What is the current behavior?**
In my custom plugin, I'm expecting `parser.hooks.callMemberChain` can trigger callback no matter its predefined object function or user defined function. But actually it only triggers when callExpression callee is an Identifier like `console`. So I'm suspecting it should be a bug

**If the current behavior is a bug, please provide the steps to reproduce.**
I have created a minimal reproduction library at: [link](https://github.com/McDaddy/webpack5-callMemberChain-issue)

**What is the expected behavior?**
`callMemberChain` should trigger any callExpression

**Other relevant information:**
webpack version:  5.12.3
Node.js version: 12.15
Operating System: macOS Big Sur 11.1
Additional tools:

**Comment by sokra** [comment]
It's intentionally only triggered for free variables. That's not a bug.

e. g. `require("abc")` vs `function(require) { require("abc") }`
only the first snippet is the require function. in the second snipped `require` could be anything and we don't want this to be parsed as require function.

---

If you want defined identifiers to be parsed too, there is a mechnism in the parser to allow that. Variables can be "tagged" with your own tags and all hooks allow to hook into tags too:

``` js
// define your own tag
const MY_TAG = Symbol("my tag");

// somewhere, when the someVariable has just been defined. e. g. hooks.declarator, hooks.pattern
parser.tagVariable("someVariable", MY_TAG, { custom: "data" });

// hook into the tag
parser.hooks.callMemberChain.for(MY_TAG).tap(...)

// you may want to handle hooks.assign for your tag too, otherwise it may get weird when someone assigns to your variable.
```

Note that any nested redeclaration will require tagging again as it's a separate variable. The tag is only valid for the lifetime of the variable.

**Comment by McDaddy** [comment]
Thank u! @sokra , you're right, your solution works for me. One more question, is the ast in parser readonly? can we change the ast output while compilation？
