### ISSUE TITLE
webpack 5 - hmr check api no longer returns updated modules

### ISSUE THREAD

**Issue by lukeapage** [webpack/webpack#12408]
# Bug report

https://github.com/webpack-contrib/webpack-hot-middleware/issues/390

I've been investigating the cause.

as per the documentation https://webpack.js.org/api/hot-module-replacement/#check
it expects check to yield an array of updated modules. It uses this to compare to the updated modules in order to decide whether to reload.

when I debug I see:

https://github.com/webpack/webpack/blob/master/lib/hmr/HotModuleReplacement.runtime.js#L257
check doesn't add any modules, it passes the array to the runtime to update.

https://github.com/webpack/webpack/blob/master/lib/hmr/JavascriptHotModuleReplacement.runtime.js#L413
The runtime doesn't add any modules, but it passes the array on to the loader

https://github.com/webpack/webpack/blob/80c5041fe1f909d34975abd33e03bdb069876ea9/lib/web/JsonpChunkLoadingRuntimeModule.js#L280
The loader doesn't accept the second argument so it doesn't add any modules to the array

It looks like a bug because the documentation wasn't changed and the code still references the updatedModules array.

Seems it was introduced in webpack 5 alpha. 0 here:
https://github.com/webpack/webpack/commit/9d918615922f8e7fb8ab1c9712135908cf1cadd7#diff-99b22d1932803b7795bbe843d01cdf63d32e52a247610bfd9cffb95170227cc6

it seems that the node/ version had the updated module id's, but the web version does not.

**Other relevant information:**
webpack version:  5.3.1
Node.js version: 12
Operating System: windows 10
Additional tools:

**Comment by samhuk** [comment]
I created an issue with webpack-hot-middleware that details an eventual side-effect of this: https://github.com/webpack-contrib/webpack-hot-middleware/issues/398. I believe that it's the exact same thing going on as in your linked issue (https://github.com/webpack-contrib/webpack-hot-middleware/issues/390)

**Comment by alexander-akait** [comment]
bump

**Comment by rocalvo-meli** [comment]
Hi! I'm facing the same problem, there is any update ?

**Comment by otakustay** [comment]
Facing the same issue, by stepping into it a little further, I find this code in `node_modules/webpack/lib/hmr/JavascriptHotModuleReplacement.runtime.js` at around line 439：

``js
chunkIds.forEach(function (chunkId) {
	if (
		$hasOwnProperty$($installedChunks$, chunkId) &&
		$installedChunks$[chunkId] !== undefined
	) {
		// HERE
		promises.push($loadUpdateChunk$(chunkId, updatedModulesList));
		currentUpdateChunks[chunkId] = true;
	}
});
```

This calls `loadUpdateChunk` with 2 arguments, however inside `node_modules/webpack/lib/web/JsonpChunkLoadingRuntimeModule.js` around line 273, `loadUpdateChunk` is defined as:

```js
? Template.asString([
		"var currentUpdatedModulesList;",
		"var waitingUpdateResolves = {};",
		// HERE
		"function loadUpdateChunk(chunkId) {",
		Template.indent([
			`return new Promise(${runtimeTemplate.basicFunction(
				"resolve, reject",
				[
```

It only defines one parameter, it never pushes any entry into `updatedModulesList` array, causing `hot.check` fails to report updated modules.

**Comment by TrejGun** [comment]
bump

**Comment by Herz3h** [comment]
any news on this ?

**Comment by tangtangtangtangtang** [comment]
is there any progress?

**Comment by sokra** [comment]
Send a PR

**Comment by vankop** [comment]
fixed

**Comment by Herz3h** [comment]
I don't know if this is related, but unless I use runtimeChunk: 'single' (can't use this because multi entrypoints app and if I do use it, code evaluated only once, which is problematic with js code embedded in modals), hmr doesn't work in dev ever since moving to webpack 5

Relevant part where error occurs:

```js
self["webpackHotUpdatedevmyproject"] = function(chunkId, moreModules, runtime) {
	for(var moduleId in moreModules) {
		if(__webpack_require__.o(moreModules, moduleId)) {
			currentUpdate[moduleId] = moreModules[moduleId]; // Fails here with: Cannot set properties of undefined (setting '45461')
			if(currentUpdatedModulesList) currentUpdatedModulesList.push(moduleId);
		}
	}
	if(runtime) currentUpdateRuntime.push(runtime);
	if(waitingUpdateResolves[chunkId]) {
		waitingUpdateResolves[chunkId]();
		waitingUpdateResolves[chunkId] = undefined;
	}
};
```

**Comment by alexander-akait** [comment]
Because you have several runtimes and only the first one processes, but the module is in another, I recommed to use `single` only for dev in such cases

**Comment by Herz3h** [comment]
I understand, however In webpack 4, I didn't have `runtimeChunk: 'single'` and HMR was working fine

**Comment by alexander-akait** [comment]
> can't use 'single' because then modals's js code is only evaluated first time


Sorry, but this shouldn't be related

**Comment by Herz3h** [comment]
So my only solution is to go back to webpack 4 where it was working I guess...rip http2

Thanks for replies

**Comment by alexander-akait** [comment]
@Herz3h Sorry I don't understand you, if you show me a reproducible repository I'll show you how to solve it, multiple entries and HMR works without any  problems

**Comment by Herz3h** [comment]
Here is a repro: https://github.com/Herz3h/webpack-runtime-single-reproduction

When you click in fetch code, alert is shown first time, but not anymore if you click on the button multiple times

**Comment by alexander-akait** [comment]
Because you are using the wrong configuration.

```js

module.exports = {
  entry: {
    index: './public/js/index.js',
    homepage: {
      dependOn: 'index',
      import: './public/js/homepage.js',
    },
  },
};
```

Each un `dependOn` entry is a separate page and can not be used on one page because multiple runtimes are generated to make it work properly.

> When you click on fetch code button, alert is shown first time, but not anymore if you click on the button multiple times

your code being executed (or not being executed) does not change in any way when changing the configuration, if this does not happen, there is probably a bug somewhere in the global application settings, not in webpack

**Comment by Herz3h** [comment]
Wasn't aware of the `dependOn` option. It seems to solve my issue. Thank you !! @alexander-akait
