### ISSUE TITLE
when importing react to the demo, the multi part library output becomes undefined

### ISSUE THREAD

**Issue by lancety** [webpack/webpack#12403]
Hi there, I made a sample repo to reproduce the issue here https://github.com/lancety/webpack-multi-part-lib-sample 
The expected result is no matter I include react import or not, the multi part library output should always show the exports as library props from these alpha and beta file, which is not. 

Wondering if anyone have similar issue since both webpack and react are very popular :) 
Thanks

version - detail listed in package.json of above repo
    "webpack": "5.12.3",
    "webpack-cli": "4.3.1",

    "react": "16.13.1",
    "react-dom": "16.13.1",

**Comment by lancety** [comment]
looks like the "vendor" causing the undefined issue. It is added when adding "react" import,  not sure if there is any webpack config setting can fix it. looking for someone's help~ ;D

**Comment by alexander-akait** [comment]
```
<html>
	<head></head>
	<body>
		<script src="dist/MyLibrary.Vendor.js" charset="utf-8"></script>
		<script src="dist/MyLibrary.alpha.js" charset="utf-8"></script>
		<script src="dist/MyLibrary.beta.js" charset="utf-8"></script>
	</body>
</html>
```

You use splitting but doesn't include splitted part in HTML file

**Comment by lancety** [comment]
get it, so in my real project, I included the bundles linke vendor, but they are not in right order so some of them are undefined. 
Thanks for your help @alexander-akait
