### ISSUE TITLE
parser.tagVariable in importSpecifier Error

### ISSUE THREAD

**Issue by McDaddy** [webpack/webpack#12409]
# Bug report

**What is the current behavior?**
my purpose is to catch all custom function call by AST traversal. since its not a free variable, so I tagVariable in hooks.importSpecifier, if I don't return anything after tagVariable, the callMemberChain callback would never be triggered, but once I return true, I'll get ReferenceError. something like the import is not taking effect.

![image](https://user-images.githubusercontent.com/5175455/104308484-b5ead780-550b-11eb-88fc-388784a919da.png)

```
// source code
import { i18n } from './i18n'

i18n.s('中文', 'ns');

// my plugin
const MY_TAG = Symbol("i18n-tag");
class MyPlugin {
  apply(compiler) {
    compiler.hooks.compilation.tap(
      "MyPlugin",
      (compilation, { normalModuleFactory }) => {
        normalModuleFactory.hooks.parser
          .for("javascript/auto")
          .tap("MyPlugin", (parser) => {
            parser.hooks.importSpecifier.tap("MyPlugin",
              (statement, source, exportName, identifierName) => {
                parser.tagVariable("i18n", MY_TAG, {});
                return true  // if not comment this line Error happens: Uncaught ReferenceError: i18n is not defined
              }
            );

            parser.hooks.callMemberChain
              .for(MY_TAG)
              .tap("MyPlugin", (expression, properties) => {
                console.log(expression); // works well if line 14 not be commented
              });
          });
      }
    );
  }
}
```

**If the current behavior is a bug, please provide the steps to reproduce.**
I have created a minimal reproduction library at: [link](https://github.com/McDaddy/webpack5-callMemberChain-issue)

**What is the expected behavior?**
importSpecifier is a SyncBailHook, once return true, it'll stop exec the hook chain，I'm wondering whether the return true is required?

**Other relevant information:**
webpack version: 5.12.3
Node.js version: 12.15
Operating System: macOS Big Sur 11.1
Additional tools:

**Comment by alexander-akait** [comment]
Please avoid creating multiple issues, you already get support here https://github.com/webpack/webpack/issues/12385, please use discussions https://github.com/webpack/webpack/discussions before creating issues
