### ISSUE TITLE
Module not found: Error: Can't resolve './src'

### ISSUE THREAD

**Issue by thisVioletHydra** [webpack/webpack#12412]
# Bug report

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

## "webpack": "5.11.0" work fine config folder 
![image](https://user-images.githubusercontent.com/11839238/104350986-db7cde80-5515-11eb-95ea-28b471da6627.png)

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

**Comment by alexander-akait** [comment]
You need to create `src/index.js`

**Comment by thisVioletHydra** [comment]
> You need to create `src/index.js`
I tested the old project and the new one, the error is still in the 'webpack-cli', with the old version of the 'webpack-cli': '4.2.0' everything works

**Comment by alexander-akait** [comment]
This behavior was broken and was removed, it was not removed from docs because we missed it, not rely on this, please use the `--config` option

**Comment by thisVioletHydra** [comment]
> This behavior was broken and was removed, it was not removed from docs because we missed it, not rely on this, please use the `--config` option

Is it not the correct config? And I can't use the .webpack folder anymore
![image](https://user-images.githubusercontent.com/11839238/104352365-a4a7c800-5517-11eb-96aa-f5d32afdbd7f.png)

**Comment by alexander-akait** [comment]
It is correct, but you files is `webpack.config.dev` and `webpack.config.prod`, but these files are not listed here
