### ISSUE TITLE
chunkModulesSpace stats option shows error

### ISSUE THREAD

**Issue by jmrossy** [webpack/webpack#12411]
# Bug report

**What is the current behavior?**

Using the new `chunkModulesSpace` stats option shows this error:
```
Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema. - configuration.stats has an unknown property 'chunkModulesSpace'.
```

The new option was added by @sokra in https://github.com/webpack/webpack/pull/11409

**If the current behavior is a bug, please provide the steps to reproduce.**

Configure webpack stats option to use the chunkModulesSpace, for examples:
```
  stats: {
    assets: true,
    assetsSort: 'size',
    nestedModules: true,
    chunks: true,
    chunkGroups: true,
    chunkModules: true,
    chunkOrigins: true,
    modules: true,
    modulesSort: 'size',
    assetsSpace: 200,
    modulesSpace: 200,
    nestedModulesSpace: 200,
    chunkModulesSpace: 200
  },
  ```

**What is the expected behavior?**

Ability to configure chunk modules space.

**Other relevant information:**
webpack version:  5.12.3
Node.js version: 10.21.0
Operating System: MacOs 10.15.7
Additional tools: -

**Comment by alexander-akait** [comment]
Feel free to send a PR to schema, it should be easy

**Comment by jaiwanth-v** [comment]
Hi @jmrossy, can I go ahead if you're not working on this?

**Comment by jmrossy** [comment]
@jaiwanth-v Sure, yeah I won't be able to get to it for a few days so go ahead if you like :)
