### ISSUE TITLE
Webpack 5 - The `asset` module type does not emit font files referenced in a scss file to the output directory

### ISSUE THREAD

**Issue by kelly-tock** [webpack/webpack#12413]
# Bug report

**What is the current behavior?**
with this asset setting:
```
{
      test: /\.(eot|svg|ttf|woff|woff2)$/,
      include: path.join(cwd, 'src/client/fonts'),
      type: 'asset/resource',
    },
```

and this scss:
```
@font-face {
  font-display: swap;
  font-family: 'tock';
  font-style: normal;
  font-weight: normal;
  src:
    url('../../fonts/icon.woff2?i1m5jz') format('woff2'),
    url('../../fonts/icon.woff?i1m5jz') format('woff'),
    url('../../fonts/icon.ttf?i1m5jz') format('truetype'),
    url('../../fonts/icon.svg?i1m5jz#tock') format('svg');
```

The file was not being emitted into the output directory. 

it was transforming the path to the correct output path and hashed the filename as well. 

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
The file should be emitted if larger than 8kb with the `asset` type. 

I changed it to `asset/resource` and then it emitted the font files to the output directory. 

**Other relevant information:**
webpack version:  5.11.0
Node.js version: v14.12.0
Operating System: OS X 10.15.7
Additional tools

**Comment by alexander-akait** [comment]
> If the current behavior is a bug, please provide the steps to reproduce.

Don't ignore this, I will reopen when you fixed it

**Comment by notflip** [comment]
@kelly-tock Did you ever find a solution to this?
