### ISSUE TITLE
how to reload the browser?

### ISSUE THREAD

**Issue by fridaymeng** [webpack/webpack#1241]
when the code changes,how to refresh the browser?use a plugin?

**Comment by jauco** [comment]
Webpack won't do that for you. You might achieve the same effect using Hot Module Replacement, but that's not something that will work out of the box.

[1]: http://webpack.github.io/docs/hot-module-replacement-with-webpack.html

**Comment by shama** [comment]
@fridaymeng Are you asking how to enable live reload? http://webpack.github.io/docs/webpack-dev-server.html#hot-mode

Or asking to literally `document.location.reload()` when changes occur? If that is the case, you'll need to create a plugin for that as I haven't seen that done anywhere else. Usually most just use live reload.

**Comment by fridaymeng** [comment]
<a href="https://github.com/shama" class="user-mention">@shama</a>
that's right ,thanks a lot.

**Comment by shama** [comment]
@sokra This issue can be closed now, thanks!
