### ISSUE TITLE
After upgrading webpack 5, some JS files are lost after packaging, and 404 appears when the browser loads

### ISSUE THREAD

**Issue by pubdreamcc** [webpack/webpack#12416]
# Bug report

**What is the current behavior?**

After upgrading webpack5, npm run build, some js files are missing, and 404 appears when the browser loads. Webpack4 will not appear before (the same configuration file.)
![image](https://user-images.githubusercontent.com/46315263/104445582-396ffb80-55d4-11eb-9595-36c5ccde7efd.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
I don’t know if webpack5 has improved tree-shaking, which caused some js files to be removed from packaging, or if I generated an environment configuration file and added:
,,
cache: {
type:'filesystem'
}
. . . .

Only part of the package is not packaged in. When I remove it:

output.filename:'admin/static/js/[name].[chunkhash:8].js' =>'output.filename:'admin/static/js/[name].js';

chunkFilename:'admin/static/js/[name].[chunkhash:8].chunk.js => "chunkFilename:'admin/static/js/[name].chunk.js'

The problem has not been fixed.

**What is the expected behavior?**

fix the problem;

**Other relevant information:**
webpack version:  5.12.3
Node.js version: 14.15.4
Operating System: Mac OS big sur 11.1
Additional tools:vscode

**Comment by pubdreamcc** [comment]
Can anyone help me look at this problem, thank you very much ！

**Comment by alexander-akait** [comment]
> If the current behavior is a bug, please provide the steps to reproduce.

You will get help when you stop ignoring my request about reproducible test repo, I will reopen the issue when you fixed it

**Comment by alexander-akait** [comment]
And

```
output.filename:'admin/static/js/[name].[chunkhash:8].js' =>'output.filename:'admin/static/js/[name].js';

chunkFilename:'admin/static/js/[name].[chunkhash:8].chunk.js => "chunkFilename:'admin/static/js/[name].chunk.js'
```

Invalid configuratoin
