### ISSUE TITLE
'fallback' does not exist in type 'Resolve'

### ISSUE THREAD

**Issue by jcrosetto** [webpack/webpack#12422]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Building a typescript project fails with a type error when using fallback within resolve.

**If the current behavior is a bug, please provide the steps to reproduce.**

Building a Typescript project and trying to use

```
resolve: {
      fallback: {
        path: require.resolve('path-browserify'),
      },
    }
```

results in 

```
[webpack-cli] webpack.config.ts(144,7): error TS2322: Type '{ fallback: { path: string; }; }' is not assignable to type 'Resolve'.
  Object literal may only specify known properties, and 'fallback' does not exist in type 'Resolve'.
```

**What is the expected behavior?**

No errors

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

webpack: 5.14.0
webpack-cli: 4.3.1

**Comment by alexander-akait** [comment]
You have `@types/webpack`, please use built-in types, we don't have `Resolve` type, it is now `ResolveOptionsWebpackOptions`

**Comment by jcrosetto** [comment]
Thanks. It turned out clean-webpack-plugin was pulling in the types

**Comment by patricknwanah** [comment]
how did you fix this?
