### ISSUE TITLE
parser "evaluate CallExpresion not called for all call expressions

### ISSUE THREAD

**Issue by DatenMetzgerX** [webpack/webpack#1242]
Hy

I'm trying to figure out how the parser works. The documentation mentions, that 'evaluate <expression>' evaluates an expression from type `<expression>`. So I would have expected that a registered plugin for `evaluate CallExpression` is invoked for every `CallExpression` in the code, but that is not the case. 

I think the problem lies in the `walkCallExpression` method. This method never calls `this.applyPluginsBailResult("evaluate CallExpression", expression)`.

Why do I need this? I want to find the four calls to $translate in the following example code:

```js
$translate('y'); // 1
var Test = (function () {
    function Test($translate, $http) {
        var _this = this;
        this.$translate = $translate;
        this.$http = $http;
        this.$translate('instance-translate-id'); // 2
        $http.get('xy').then(function () { return _this.$translate("success"); }); //3
    }
    Test.prototype.onClick = function () {
        this.$translate('hello'); // 4
    };
    return Test;
})();
```

Expected plugin code: 

```js
compiler.parser.plugin('call $translate', jsTranslateCall);
compiler.parser.plugin('evaluate CallExpression .$translate', jsTranslateCall);
```

My proposal is to adjust `walkCallExpression` and add a call to `this.applyPluginsBailResult("evaluate CallExpression", expression)`. But I don't know what I should do with the result. Return it? 

If someone can give me some advices, then I can create a pull request that adjusts the behavior. 

Micha

**Comment by sokra** [comment]
The `evaluate ...` stuff is only called when calling `Parser.evaluate`, i. e. for expressions in `if(...)`. `evaluate` tries to figure out if the expression is a compile-time constant, i. e. always true of false. It's also called for the content of `require(...)`.

**Comment by DatenMetzgerX** [comment]
That surprises me. So except walking the ast myself (hook into 'program'), there is no way to visit all CallExpressions? The point is, it works quite well if a global function is used like `require`, then `call require` is always triggered (even renaming is supported). But as soon as the variable is not global but a local function declaration, the CallExpression is not invoked anymore. 

I think from the naming of the plugin hook (evaluate CallExpression) it is expected that it is called for all CallExpression. It might be that I have my super logic that is capable to evaluate certain CallExpressions to compile time constants. But to be able to do so, the hook needs to be triggered for all CallExpressions and not only for some.

**Comment by sokra** [comment]
The Parser is build for parsing "free vars". Your use case should better solved within a loader by using your own parser or with a RegExp.

There is no way to ensure that `this.$translate` is assosiated with the `$translate` free var.

**Comment by DatenMetzgerX** [comment]
Ok, good to understand. I have solved it by using (esprima-walk)[https://www.npmjs.com/package/esprima-walk] in the program extension point. I know, this will break when you change your parser implementation. But for the moment this is sufficent... 

Thanks anyway!
