### ISSUE TITLE
we remove plugin for i18n, and it's document, so how do we support i18n?

### ISSUE THREAD

**Issue by lornally** [webpack/webpack#12433]
i have report another issue, that i18n document link is 404, then we remove the link. but my requirement is using i18n. so how  can we use webpack for i18n?

**Comment by alexander-akait** [comment]
`i18n` is out of scope webpack, we recommend to use `i18n` libraries to achieve this, pick libraries for your framework
- react: https://github.com/i18next/react-i18next
- vue: https://kazupon.github.io/vue-i18n/introduction.html
- pure js: https://github.com/fnando/i18n-js

You can found more using google

**Comment by lornally** [comment]
thank you:)
