### ISSUE TITLE
can't find library export 

### ISSUE THREAD

**Issue by clark-cui** [webpack/webpack#12430]
I use <script> to import index.bundle.js in a HTML.
```
//webpack.config.js
   entry: {
        index: '/src/index.ts'
    },
 output: {
        path: path.join(__dirname, 'dist'),
        library: 'test',
        libraryTarget: 'umd',
    }

```
```
//index.ts
export function mount() {
    console.log("mount")
}
```
```
//html
 <script src="dist/index.js"></script>
    <script>
        console.log(window.mount());
    </script>
```
then error.
```
Uncaught TypeError: window.mount is not a function
```
I have checked the official documentation.But I can't find answer.
my code is [here](https://github.com/clark-cui/webpack-library-example-11986)

```
yarn 
npm run build 
```
then open the index.html,you can find the error.

**Comment by alexander-akait** [comment]
Because you compile library, `mount`, `bootstrap` and `unmount` are just exports from library, it is not exposed to `window`, and please use dicussion or stackoverflow for questions

**Comment by alexander-akait** [comment]
Use this `window.test.mount()`, if you need access to your library

**Comment by clark-cui** [comment]
thanks bro! It help me a lot.have a nice day.
