### ISSUE TITLE
Type 'HotModuleReplacementPlugin' is not assignable to type '((this: Compiler, compiler: Compiler) => void) | WebpackPluginInstance'.

### ISSUE THREAD

**Issue by HomyeeKing** [webpack/webpack#12447]
I saw this error after make `checkJs` in jsconfig enabled,
this is the code:
```js
plugins: [
        new webpack.HotModuleReplacementPlugin()
    ]
```

webpack version : ^5.1.3

**Comment by sokra** [comment]
I guess you mixed `@types/webpack` (webpack 4) and the types of `webpack` (webpack 5)

**Comment by HomyeeKing** [comment]
maybe you are right , I don't trust the jsconfig's checkjs, it's  a js project , so the type is not that accurate
