### ISSUE TITLE
Expose variable doesn't work in watch mode

### ISSUE THREAD

**Issue by ingun37** [webpack/webpack#12445]
# Bug report

**What is the current behavior?**
When I expose a variable using  [*var* libraryTarget](https://webpack.js.org/configuration/output/#expose-a-variable)

the exposed variable is empty object in watch mode dev server.

It works fine when I open the html file directly from filesystem.

**If the current behavior is a bug, please provide the steps to reproduce.**

Here's minimal reproducable project https://github.com/ingun37/webpack-bug-reproduce

Write entry file like this
```javascript
var aaa = "aafufufa"
export {aaa}
```

Configure webpack like this

```javascript
const path = require("path");
module.exports = {
    output: {
        library: 'yourLibName',
        libraryTarget: 'var',
    },
    devServer: {
        hot: true,
        contentBase: path.resolve(__dirname, "dist"),
        publicPath: "/",
    },
}
```

Write HTML like this

```html
<script src="./main.js"></script>
<script>console.log(yourLibName)</script>
```

Run webpack dev server in watch mode
```shell
npx webpack serve --open
```

You can see the console outputs

```
{}
```

While it outputs correctly when you just directly open the html file.

```
[Log] Object (index.html, line 9)
__esModule: true
aaa: 
Symbol(Symbol.toStringTag): "Module"
Object Prototype
```

**What is the expected behavior?**

Expose the variable correctly.

**Other relevant information:**
webpack version:  5.15.0
Node.js version: 12
Operating System: MacOS
Additional tools:

## Side note

I remember I had the same problem when I was using Webpack 4.
Also  I found an article addressing the same problem https://stackoverflow.com/a/51924958/3769433

**Comment by ingun37** [comment]
I shouldn't src `./main.js`

**Comment by ingun37** [comment]
I thought the problem could be the script element's src attribute is written in relative filesytem format so I tried 
```html
<script src="/main.js"></script>
```
But didn't work.

**Comment by sokra** [comment]
cc @alexander-akait this seem to be related to webpack-dev-server isn't it?

**Comment by alexander-akait** [comment]
Yes, it is fixed in `webpack-dev-server@4-beta.0`

**Comment by skfreddo** [comment]
Is there a workaround for this in `webpack-dev-server@3`?

**Comment by alexander-akait** [comment]
webpack-dev-server@beta-0
