### ISSUE TITLE
passing variables to imported js module

### ISSUE THREAD

**Issue by Ibrahimrahhal** [webpack/webpack#12449]
## Feature request

**What is the expected behavior?**
It would be great if we can pass variables to the files that we import so we can do stuff before importing for example
`import './modules1?color=blue';`

**What is the motivation or use case for adding/changing the behavior?**
I'm trying to import jquery UI widgets dynamically and as you may know, each widget could have its dependencies on other widgets so I should control this manually I was thinking of something like this.
`import './jquery-ui/widgets=menu+tabs+autocomplete;`
and in the jquery file, I'd have something like this
`if(widgets.includes('autocomplete') || widgets.includes('menu'))`
`import './widgets/menu';`

**How should this be implemented in your opinion?**

**Are you willing to work on this yourself?**
yes

**Comment by sokra** [comment]
> import './modules1?color=blue';

yes you can do that this way.

```js
const query = import.meta.url.replace(/^.(\?|$)/, "");
```
