### ISSUE TITLE
Consider using PrettyError for error messages

### ISSUE THREAD

**Issue by AriaMinaei** [webpack/webpack#1245]
Webpack's error messages are a bit hard to read and could use some formatting:

![image](https://cloud.githubusercontent.com/assets/593118/8645398/678c656c-295c-11e5-91fa-267c5530e436.png)

Have you guys considered using a package like [PrettyError](https://github.com/AriaMinaei/pretty-error) for formatting webpack's error messages? PrettyError helps make stack traces more readable, and it's very easy to integrate into other packages.

![screenshot](https://github.com/AriaMinaei/pretty-error/raw/master/docs/images/pretty-error-screenshot.png)

You could also use [RenderKid](https://github.com/AriaMinaei/renderkid) for formatting the rest of webpack's logs. RenderKid has features like text-wrapping, so that lines of a paragraph wrap inside the paragraph's margins, unlike this:

![image](https://cloud.githubusercontent.com/assets/593118/8645566/c23ebe50-295d-11e5-81d5-616fcbe4ce7c.png)

Both PrettyError and RenderKid can be customized with css-like rules, so that webpack can define a common theme for its console output, regardless of which plugin those messages come from.

ps. I'm the author of both packages, and I can help with the integration process.

**Comment by krasnoperov** [comment]
+1

**Comment by bebraw** [comment]
@sokra Maybe this would be good for webpack 2?

**Comment by jhabdas** [comment]
+2 it's good instantly

**Comment by TheLarkInn** [comment]
+3 Would we want to instead make it a flag for `--prety-error` or let them set it all the time. Similar to `--colors.`

**Comment by prabirshrestha** [comment]
Would be good to also have a custom formatter like tslint. https://github.com/palantir/tslint/pull/947

**Comment by jhabdas** [comment]
@TheLarkInn Makes sense to have flags or some other configurable way to otherwise leverage pretty's black box capabilities. FWIW Chrome Dev Tools has woeful support for hiding React internals.

**Comment by mxstbr** [comment]
Could somebody point me to the file to add this at? Is there a general "throw an error" method? (maybe [`lib/Stats.js`](https://github.com/webpack/webpack/blob/b0fffd50d35dd0eef734d189928c1ac4c5c9fb97/lib/Stats.js)? I'd love to have this. /cc @TheLarkInn @bebraw

**Comment by bebraw** [comment]
@mxstbr If I read right, `Stats.jsonToString` would be a good place to poke. Perhaps a good way to prototype it would be to figure out good formatting against Node and `stats` you get through it. Once you have `stats` JSON with an error, you can iterate on the formatting fast.

**Comment by sokra** [comment]
these "pretty" errors are pretty noisy.

**Comment by jhabdas** [comment]
@sokra check out the blackboxing feature. it allows one to hide the frames of the stacktrace which are not interesting/applicable, such as vendored code

**Comment by TheLarkInn** [comment]
@jhabdas so we would love to see a PR on this. And like @sokra said it may not be for _everyone_ so a flag would be very ideal. We can discuss further through the PR process as well.

**Comment by TheLarkInn** [comment]
Or maybe instead to empower better plugins for this, I have always been interested in the investigation into creating a new [Tapable](github.com/webpack/tapable) instance for webpacks output system. This could allow features like this to be created through plugins, in addition could solidify and standardize across the board how plugins, maybe loaders hook up into a standard console output "template" or "instance".

**Comment by bebraw** [comment]
Yeah, I would rather expose a logging protocol that would allow overrides than stick to some particular solution over others.

**Comment by jhabdas** [comment]
@TheLarkInn @bebraw The idea of a tapable instance sounds great (the link's broken by the way). I'd personally lean towards a _code for today_ mentality, though, and put this under a flag. Though I understand the webpack codebase is probably getting a bit gnarly. IMO the underlying need for this issue is simply more dev-friendly error outputting, however it's done.

If there are any other ideas on how blackboxing could be done with the current installment, I'd love to hear about it. FWIW, since React became a thing step debugging in the browser has become quite a bit more complex and I've seen many developers backpedaling to `console.log` and generally wasting their time. Perhaps the best approach is to make step debugging easier.

**Comment by dmitriid** [comment]
A more relevant question would be: if I'm not a webpack/plugin developer, there's really no value in these errors. As a devloper I want to see one single error: what happened:

- A loader failed to parse file X at line Y expecting Z.
- webpack failed to find module M referenced from module N even though it looked at directories O, P and Q
- etc.

This entire stacktrace, and loaders' stacktraces and any other stacktraces should be hidden by default and enabled through a `-enable-verbose-logging` switch.

(I'm currently looking at easily 100 lines of a stacktrace including tens of lines of `Parser.pp.<> at webpack/node_modules/acorn/dist/acorn.js` and `Storage.finished at node_modules/enhanced-resolve/node_modules/graceful-fs/graceful-fs.js` where I need only one single line: `ERROR in [default] xxx.js:3:15 Expression expected.`)

**Comment by jhabdas** [comment]
I'm leaving a comment because a bot just sent me a notification on GitHub causing me to lose 2 minutes of my life.

**Comment by sokra** [comment]
We did implemted what @dmitriid suggested. By default no stack trace is shown and only the relevant message. `--display-error-details` show the complete stack.

In addition to this everybody is free to use PrettyError in the webpack.config.js. Just add `require('pretty-error').start();` on top.
