### ISSUE TITLE
[request] Improve errors relating to ESM module not found errors.

### ISSUE THREAD

**Issue by trusktr** [webpack/webpack#12456]
## Feature request

At the moment, Webpack 5 tells me something like

```js
Module not found: Error: Can't resolve '@lume/variable/dist/dom.js'
```

**What is the expected behavior?**

It should say 

```js
Module not found: Error: Can't resolve '@lume/variable/dist/dist/dom.js'
```

**What is motivation or use case for adding/changing the behavior?**

The difference is subtle, but this error message change privdes useful and helpful clues to the problem.

The `@lume/variable` package has this in `package.json`:

```json
	"exports": {
		".": "./dist/index.js",
		"./": "./dist/"
	},
```

so the project doing the import should have tried

```js
import {} from '@lume/variable/dom.js'
```

instead of

```js
import {} from '@lume/variable/dist/dom.js'
```

and the updated error message would provide a stronger hint that this is the problem.

In fact, if you try `import {} from '@lume/variable/dist/dom.js'` in Node.js in an ESM file, Node.js gives this error message:

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/home/trusktr/src/my-project/node_modules/@lume/variable/dist/dist/dom.js'
```

and the double `/dist/dist` was a better hint to finding the issue.

**How should this be implemented in your opinion?**

No opinion.

**Comment by alexander-akait** [comment]
@trusktr yep, maybe useful, you can send a PR :smile:

**Comment by sokra** [comment]
We have very useful details for the resolving errors, but it need to be enabled with `stats.errorDetails: true`.

I would like to point users to this by adding a message to the stats when error details are available:

```
These error(s) can provide more details. Use `stats.errorsDetails: true` resp. `--stats-error-details` to show them.
```

And/or it would be cool to automatically show error details when only a single error is reported. For that `stats.errorDetails` should default to `stats.errorDetails: "auto"`, which shows details only when a single error is shown.

**Comment by snitin315** [comment]
I will be working on this one.
