### ISSUE TITLE
 An unhandled error has occurred inside Forge: Cannot read property 'tapAsync' of undefined

### ISSUE THREAD

**Issue by raphael10-collab** [webpack/webpack#12461]
# Bug report

I described the issue in gitter.im/webpack/webpack : 

![image](https://user-images.githubusercontent.com/70313067/105163959-d373fe80-5b14-11eb-87ed-70078f3bafda.png)

![image](https://user-images.githubusercontent.com/70313067/105164116-09b17e00-5b15-11eb-80e9-770959220cc1.png)

![image](https://user-images.githubusercontent.com/70313067/105164260-36fe2c00-5b15-11eb-87ee-544358fd665d.png)

And in StackOverflow:

https://stackoverflow.com/questions/65796745/copy-webpack-plugin-configuration-issue

But didn't solve the issue.

So... I ask here, because I do not know if it's problem I can solve, but I need to know how, or it's a bug

**What is the current behavior?**

    yarn start
    yarn run v1.22.5
    $ cross-env NODE_ENV=development electron-forge start
    ✔ Checking your system
    ✔ Locating Application
    ✔ Preparing native dependencies
    ✔ Compiling Main Process Code
    ✖ Launch Dev Servers

    An unhandled error has occurred inside Forge:
    Cannot read property 'tapAsync' of undefined
    TypeError: Cannot read property 'tapAsync' of undefined
        at ExternalModuleFactoryPlugin.apply (/home/marco/webMatters/electronMatters/PythonConnection/node_modules
    /webpack/lib/ExternalModuleFactoryPlugin.js:59:39)
        at /home/marco/webMatters/electronMatters/PythonConnection/node_modules/webpack/lib/ExternalsPlugin.js:30:63
        at SyncHook.eval (eval at create (/home/marco/webMatters/electronMatters/PythonConnection/node_modules/tapable
    /lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
        at SyncHook.lazyCompileHook (/home/marco/webMatters/electronMatters/PythonConnection/node_modules/tapable
    /lib/Hook.js:154:20)
        at /home/marco/webMatters/electronMatters/PythonConnection/node_modules/@electron-forge/plugin-webpack
    /node_modules/webpack/lib/Compiler.js:665:23
        at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/marco/webMatters/electronMatters/PythonConnection
    /node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
        at AsyncSeriesHook.lazyCompileHook (/home/marco/webMatters/electronMatters/PythonConnection/node_modules/tapable
    /lib/Hook.js:154:20)
        at Compiler.compile (/home/marco/webMatters/electronMatters/PythonConnection/node_modules/@electron-forge/plugin-
    webpack/node_modules/webpack/lib/Compiler.js:662:28)
        at /home/marco/webMatters/electronMatters/PythonConnection/node_modules/@electron-forge/plugin-webpack
    /node_modules/webpack/lib/Watching.js:77:18
        at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/marco/webMatters/electronMatters/PythonConnection
    /node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:33:1)
        at AsyncSeriesHook.lazyCompileHook (/home/marco/webMatters/electronMatters/PythonConnection/node_modules/tapable
    /lib/Hook.js:154:20)
        at Watching._go (/home/marco/webMatters/electronMatters/PythonConnection/node_modules/@electron-forge/plugin-
    webpack/node_modules/webpack/lib/Watching.js:41:32)
        at /home/marco/webMatters/electronMatters/PythonConnection/node_modules/@electron-forge/plugin-webpack
    /node_modules/webpack/lib/Watching.js:33:9
        at Compiler.readRecords (/home/marco/webMatters/electronMatters/PythonConnection/node_modules/@electron-
    forge/plugin-webpack/node_modules/webpack/lib/Compiler.js:529:11)
        at new Watching (/home/marco/webMatters/electronMatters/PythonConnection/node_modules/@electron-forge/plugin-
    webpack/node_modules/webpack/lib/Watching.js:30:17)
        at Compiler.watch (/home/marco/webMatters/electronMatters/PythonConnection/node_modules/@electron-forge/plugin-
    webpack/node_modules/webpack/lib/Compiler.js:244:10)

**If the current behavior is a bug, please provide the steps to reproduce.**

  in in /tools/webpack/webpack.plugins.js :

    const path = require('path');
    const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin');
    const webpack = require('webpack');
    const CopyPlugin = require("copy-webpack-plugin");

    module.exports = [
      new ForkTsCheckerWebpackPlugin(),
      new webpack.ExternalsPlugin('commonjs', [
        'electron'
      ]),

      new CopyPlugin({
        patterns: [
          { from: path.resolve(__dirname, "../../src/scripts/*"),
            to: path.resolve(__dirname, "../../.webpack/main/scripts") },
        ],
      })
    ];

You can find the complete git repo here: https://github.com/raphael10-collab/PythonConnection

Steps to reproduce the problem:

- git clone https://github.com/raphael10-collab/PythonConnection.git
- yarn
- yarn start

I also asked for help in electron-discord forum : 
![image](https://user-images.githubusercontent.com/70313067/105165240-56e21f80-5b16-11eb-8f1e-4b4c6c60a3da.png)

And reported the issue also in github's electron page:  https://github.com/electron/electron/issues/27390

**What is the expected behavior?**

No errors and the files correctly copied in the specified folder

**Other relevant information:**
webpack version:  webpack : 5.16.0
Node.js version: node : v14.5.0
Operating System:  Ubuntu 18.04.4 Desktop
Additional tools: 
    copy-webpack-plugin : 7.0.0
    @electron-forge/plugin-webpack: 6.0.0-beta.53

![image](https://user-images.githubusercontent.com/70313067/105167457-08825000-5b19-11eb-9f00-42c0ab6e8549.png)

Looking forward to hearing from you

**Comment by alexander-akait** [comment]
You need webpack@5 to use latest version of plugin, you still on webpack@4, please read CHANGELOG before updating

**Comment by alexander-akait** [comment]
Open an issue in `@electron-forge/plugin-webpack` repo, they need update webpack

**Comment by alexander-akait** [comment]
https://github.com/electron-userland/electron-forge/blob/master/packages/plugin/webpack/package.json#L31

**Comment by raphael10-collab** [comment]
@alexander-akait I opened also an issue here: https://github.com/electron-userland/electron-forge/issues/2135

**Comment by raphael10-collab** [comment]
@alexander-akait As you can see here: https://github.com/electron-userland/electron-forge/issues/2135#issuecomment-763755177
electron-forge people think it's a problem of webpack: "This appears to be a webpack version problem per webpack/webpack#12461 (comment), use a version of the plugin compatible with Webpack 4 for now."

**Comment by raphael10-collab** [comment]
> You need webpack@5 to use latest version of plugin, you still on webpack@4, please read CHANGELOG before updating


The webpack version used is alread version 5: https://github.com/raphael10-collab/PythonConnection/blob/master/package.json#L56   : "webpack": "^5.16.0"

**Comment by raphael10-collab** [comment]
@alexander-akait so... electron-forge people think it's a problem of webpack, specifically of webpack version used, while you think that electron-forge should upgrade the version of webpack they use.

I ask you then: which version of webpack and which version of electron-forge should I use in order to have everything working fine?

**Comment by raphael10-collab** [comment]
With the combination : 

    "copy-webpack-plugin": "6",
    "webpack": "4"

I do not get those errors anymore.

**Comment by alexander-akait** [comment]
Because latest version of `copy-webpacj-plugin` require `webpack@5`, please read changelog before updating and do not ignore warnings/errors from package manager, it say you about this
