### ISSUE TITLE
`var _arguments = arguments` does work at webpack v4 but throw error at v5

### ISSUE THREAD

**Issue by vanpipy** [webpack/webpack#12466]
Hi, 

the code like `var _arguments = arguments` which converted by babel from the arrow function `() => { console.log(arguments) }`. It can be used with webpack v4, but after migrate to v5. An error is coming cause the `the argumens is undefined`. I try to debug 
at v4 and v5, then I figure out that the `arguments` is an object at v4 and undefined at v5.

And after digging out the document - [output.environment](https://webpack.js.org/configuration/output/#outputenvironment), the problem existed still. 

So I come here to ask for some help cause the `ecmaVersion` removed at the latest version. And I think the problem will be solved via a way like the webpack v4 handle the module. 

Thanks.

**Comment by vanpipy** [comment]
The `arguments` is undefined because an exception `Exception: TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them at Function.o (<anonymous>:1:83) at __webpack_require__`, is there a way to avoid it?

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by sokra** [comment]
> `() => { console.log(arguments) }`

The code looks suspicious. `arguments` can't be used in arrow functions.

**Comment by vanpipy** [comment]
Hi, @sokra ,

Yes, it is useless and wrong for an ES Module, but it happened in a legacy code...

Pretend the code exist as follow:

```
export const sum = ({ x: 1, y: 2 }) => {
  const args = arguments[0];
  const result = args.x + args.y + x + y;
  return result;
}
```

and babel it with `babel --presets=@babel/preset-env filename`

```
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.sum = void 0;
var _arguments = arguments; //<--- here

var sum = function sum(_ref) {
  var _ref$x = _ref.x,
      x = _ref$x === void 0 ? 1 : _ref$x,
      _ref$y = _ref.y,
      y = _ref$y === void 0 ? 2 : _ref$y;
  var args = _arguments[0];
  var result = args.x + args.y + x + y;
  return result;
};

exports.sum = sum;
```

And the line `var _arguments = arguments;` throw an error and block the webpack build under v5, but passed under v5.

The description is not simple and hard to reproduce the exception, I will give a repo to display the process.

Thanks @sokra

**Comment by vanpipy** [comment]
Resolve by `output.environment.arrowFunction: fales`.
