### ISSUE TITLE
Deprecation warning with Vue

### ISSUE THREAD

**Issue by jockehewh** [webpack/webpack#12468]
after building my bundle i receive this warning
`
(node:3292) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
`
how can i disable it?
i tried using stats: (no-errors, {warnings:false}, none) but none of these can solve my issue. does someone know how i can prevent the warning apprearing in the console?

**Comment by alexander-akait** [comment]
We use `util.deprecate` (`util` is Node.js package), so you can pass `--no-deprecation` to Node.js, if you use `webpack-cli` you can use https://webpack.js.org/api/cli/#pass-cli-arguments-to-nodejs (`NODE_OPTIONS="--no-deprecation" webpack`), for other CLI it should work too, but nothing to fix on webpack side

**Comment by jockehewh** [comment]
> We use `util.deprecate` (`util` is Node.js package), so you can pass `--no-deprecation` to Node.js, if you use `webpack-cli` you can use https://webpack.js.org/api/cli/#pass-cli-arguments-to-nodejs (`NODE_OPTIONS="--no-deprecation" webpack`), for other CLI it should work too, but nothing to fix on webpack side

Thank you Alexander
