### ISSUE TITLE
Is there a way to config Asset Modules so that there's no files emitted

### ISSUE THREAD

**Issue by Diablohu** [webpack/webpack#12474]
## Feature request

**What is the expected behavior?**
Need an option for Asset Modules (`type: 'asset/resource'`) to not emit files

**What is motivation or use case for adding/changing the behavior?**
`file-loader` has this option which is useful for server side packages

**How should this be implemented in your opinion?**
Add a new option to Asset Modules, such like

```javascript
module.exports = {
  // ...
  module: {
    rules: [
      {
        test: /\.png/,
        type: 'asset/resource',
        emitFile: false
      }
    ]
  },
};
```

**Are you willing to work on this yourself?**
no

**Comment by alexander-akait** [comment]
What is use case? SSR?

**Comment by Diablohu** [comment]
> What is use case? SSR?

As I mentioned, it is useful for server side packages. So yes, SSR

**Comment by alexander-akait** [comment]
My mistake :smile: Yes, we need improve this, should be easy

**Comment by alexcyfong** [comment]
Is this solved? can we use this now?
        test: /\.png/,
        type: 'asset/resource',
        emitFile: false

**Comment by ketanhdoshi** [comment]
Hi, any news on when we can expect this enhancement?

**Comment by mendoncanorma** [comment]
What would the configuration look like with emit file? This what I have currently

        {
          test: /\.(eot|gif|otf|png|svg|ttf|woff)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
          type: 'asset/resource',
          generator: {
            filename: '[path][name][ext]',
          },
        },

**Comment by alexander-akait** [comment]
You can remove `(\?v=[0-9]\.[0-9]\.[0-9])?` you don't need this

**Comment by mendoncanorma** [comment]
Thank you @alexander-akait.

Sorry if my question was unclear. How do I emit file with asset modules? With file-loader we had `emitFile: false`

**Comment by chenxsan** [comment]
@mendoncanorma See https://webpack.js.org/configuration/module/#rulegeneratoremit.

**Comment by mendoncanorma** [comment]
Thank you @chenxsan

**Comment by mendoncanorma** [comment]
@alexander-akait , @chenxsan ,

A minor query,  I was on webpack 4.x.x and css-loader 3.x.x.  I upgraded to webpack 5 and css-loader 5.2.1. 

My css files had `background-image: url(/dev/image/file.svg)` in some classes.

After the upgrade I get **Module parse failed: Unexpected character '�'** for the image files in my CSS. Hence I have used **file-loader** as mentioned above. I had not used file-loader until then. Am I missing anything here?

**Comment by alexander-akait** [comment]
You need migrate on `asset/resource` https://webpack.js.org/guides/asset-modules/, just replace `file-loader` on this

**Comment by mendoncanorma** [comment]
Let me reformat my question.

I was on webpack 4.x.x and css-loader 3.x.x. I upgraded to webpack 5 and css-loader 5.2.1.

My css files had `background-image: url(/dev/image/file.svg)` in some classes.

After the upgrade I get Module parse failed: Unexpected character '�' for the image files in my CSS.

It was working fine earlier even without **file-loader**. Should I use asset modules here?

**Comment by alexander-akait** [comment]
webpack starts support `/path/to/image.png` urls, you need fix path to your image or ignore them or use `/** webpackIgnore: true */`, i.e.

```css
a {
  /** webpackIgnore: true */
  background-image: url(/dev/image/file.svg)
}
```

Ideally you should avoid using unresolved URLs

**Comment by mendoncanorma** [comment]
Thank you @alexander-akait . It helped.

**Comment by vavra7** [comment]
Back to original question. There is actually an option 'emit'.
```
{
  test: /\.jpg/,
  type: 'asset/resource',
  generator: {
    emit: false
  }
}
```
I really don't know why it is not documented [here](https://webpack.js.org/guides/asset-modules/).

**Comment by alexander-akait** [comment]
@vavra7 Feel free to open an issue in webpack docs repo, thank you https://github.com/webpack/webpack.js.org
