### ISSUE TITLE
webpack will keep recompiling in watch mode when calling this.addContextDependency(this.projectRoot) in loader

### ISSUE THREAD

**Issue by JayFate** [webpack/webpack#12473]
# Bug report

**What is the current behavior?**

In watch mode, calling this.addContextDependency(this.projectRoot) in loader will trigger recompilation continuously.

***If this is a bug, please leave it to me and I will fix it.***

**If the current behavior is a bug, please provide the steps to reproduce.**

1. git clone git@github.com:JayFate/webpack5-demo.git
2. cd webpack5-demo && npm install
3. cd webpack5-demo/qa && npm install
4. cd webpack5-demo/demo
5. node ../qa/bin/index.js build

webpack will keep recompiling in watch mode when calling this.addContextDependency(this.projectRoot) in loader

![image](https://user-images.githubusercontent.com/48240828/105461243-eb3fb400-5cc7-11eb-9de0-b3fd63a783d6.png)

please look into this [demo](https://github.com/JayFate/webpack5-demo)

**What is the expected behavior?**

webpack should not compile again  when calling this.addContextDependency(this.projectRoot) in loader. Errors in compilation should be printed only once.

**Other relevant information:**
webpack version:  5.11.1
Node.js version: 12.0.0
Operating System: macOs big sur
Additional tools:

**Comment by alexander-akait** [comment]
Expected, you added `demo` directory (i.e. `this.projectRoot`) using `addContextDependency`, when compilation finished and webpack creates `build/app.js.js` then webpack sees file was created/changed and run compilation again. No problem from webpack here, exclude `build/app.js.js`.Want to debug? Open `node_modules/watchpack/lib/watchpack.js`, go to `_onChange` and put `console.log` and you see it.
