### ISSUE TITLE
Loader: implement middlewares

### ISSUE THREAD

**Issue by IngwiePhoenix** [webpack/webpack#1247]
I want to extend my `oj-loader` with middlewares - to implement a preprocessor, for instance. It currently has the very basic structure of just an exported function via `module.exports` like loaders should. However, in my case, I would probably change that slightly and export the actual loader function itself as `module.exports.loader` or similar.

Is it allowed to pass a function to the loader parameter of a definition or what can I do to make this work?

**Comment by sokra** [comment]
I don't understand your issue...

**Comment by IngwiePhoenix** [comment]
Imagine module X (`x-mod`). X is capable of using middlewares. There are the middlewares `a` and `b`. So typically:

```javascript
var x = require("x-mod"),
    a = require("a"),
    b = require("b");

x.use( a() );
x.use( b() );
```

Now, I want to create a loader for WebPack that is able to use middlewares. Would this be valid WebPack configuration?

```javascript
var x = require("x-loader"),
    a = require("a"),
    b = require("b");

x.use(a());
x.use(b());

module.exports = {
    module: {
        loader: [
            { test: /\.x$/, loader: x.loader  }
        ]
    }
};
```

**Comment by sokra** [comment]
``` js
var a = require("a"),
    b = require("b");

module.exports = {
    module: {
        loader: [
            { test: /\.x$/, loader: "x-loader"  }
        ]
    },
    x: [
      a(),
      b()
    ]
};
```

In the loader `this.options.x`.

**Comment by IngwiePhoenix** [comment]
alright. ill go that way then. thank you (:
