### ISSUE TITLE
multiple entry points with splitChunks "all" - not working

### ISSUE THREAD

**Issue by havarez** [webpack/webpack#12471]
# Bug report

**What is the current behavior?**
When using multiple entry points and enabling 
`optimization: { splitChunks: { chunks: "all"  } }`
bundles generated by webpack are empty and can't be imported.
If you comment out  chunks: "all" or make single entry point - import works properly.
Used HtmlWebpackPlugin - but no luck.
Tried webpack4 and webpack3 - same behaviour.

**If the current behavior is a bug, please provide the steps to reproduce.**

Tiny project where you can reproduce the bug.
All packages updated to latest versions.
https://github.com/havarez/webpack-import-with-chunks-bug

1) npm install > npm run dist > npm start
2) You will see "COMP LOADED" on a page
3) Uncomment webpack.config.lib.js > chunks: "all"
4) npm run dist
5) Component not loaded. Page is empty.

**What is the expected behavior?**

Load bundles generated from multiple entry points even if they have shared chunks. 

**Other relevant information:**
webpack version:  v5.16.0
Node.js version: v12.16.3
Operating System: mac os

**Comment by alexander-akait** [comment]
Because you forget to include `dist/src-lib_comp_js.js`, in most cases you should not `splitChunks` libraries, anyway if you want to do it, please use:

Berfore:

**src-page/index.js**

```js
import "../dist/index";

class App extends HTMLElement {
  constructor() {
    super();

    const comp = document.createElement("app-comp");
    this.attachShadow({ mode: "open" }).appendChild(comp);
  }
}

customElements.define("app-index", App);
```

Fixed:

**src-page/index.js**

```js
// Splitted part
import "../dist/src-lib_comp_js.js";
import "../dist/index";

class App extends HTMLElement {
  constructor() {
    super();

    const comp = document.createElement("app-comp");
    this.attachShadow({ mode: "open" }).appendChild(comp);
  }
}

customElements.define("app-index", App);
```

When you use splitting you need manually load `JS` file, you can do it using `import` in JS files or `<script src="./file.js"></script>` in HTML, it descried in docs. Why? Because you can split scripts in very different ways.

**Comment by havarez** [comment]
Thank you.
