### ISSUE TITLE
Webpack requiring plugin when using filesystem cache refused by yarn with pnp

### ISSUE THREAD

**Issue by ASDFGerte** [webpack/webpack#12489]
**Bug report**

**What is the current behavior?**
When enabling filesystem caching, and having `mini-css-extract-plugin` as plugin (probably not restricted to this plugin), webpack tries to access the plugin package while checking the cache. As the plugin isn't seen as a dependency, yarn2 "berry" with strict pnp enabled refuses the access, resulting in many warnings:
```
[webpack.cache.PackFileCacheStrategy] Restoring failed for SourceMapDevToolPlugin|style.css from pack: Error: webpack tried to access mini-css-extract-plugin, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: mini-css-extract-plugin (via "mini-css-extract-plugin\dist\CssDependency")
Required by: webpack@virtual:78843900345fbf1fadc3dc7c92ad84ed83e5a2cb05414092627e16f511b55ab52daa2376892e4e5e594a0db7dc481170f358fe0d41dc53641a70588c02b551f2#npm:5.17.0 (via C:\my\nice\folder\.yarn\$$virtual\webpack-virtual-aec5acf597\0\cache\webpack-npm-5.17.0-e594321923-2840d6291d.zip\node_modules\webpack\lib\serialization\)

Require stack:
- C:\my\nice\folder\.yarn\$$virtual\webpack-virtual-aec5acf597\0\cache\webpack-npm-5.17.0-e594321923-2840d6291d.zip\node_modules\webpack\lib\serialization\ObjectMiddleware.js
- C:\my\nice\folder\.yarn\$$virtual\webpack-virtual-aec5acf597\0\cache\webpack-npm-5.17.0-e594321923-2840d6291d.zip\node_modules\webpack\lib\util\serialization.js
- C:\my\nice\folder\.yarn\$$virtual\webpack-virtual-aec5acf597\0\cache\webpack-npm-5.17.0-e594321923-2840d6291d.zip\node_modules\webpack\lib\util\makeSerializable.js
- C:\my\nice\folder\.yarn\$$virtual\webpack-virtual-aec5acf597\0\cache\webpack-npm-5.17.0-e594321923-2840d6291d.zip\node_modules\webpack\lib\DependenciesBlock.js
- C:\my\nice\folder\.yarn\$$virtual\webpack-virtual-aec5acf597\0\cache\webpack-npm-5.17.0-e594321923-2840d6291d.zip\node_modules\webpack\lib\Module.js
- C:\my\nice\folder\.yarn\$$virtual\webpack-virtual-aec5acf597\0\cache\webpack-npm-5.17.0-e594321923-2840d6291d.zip\node_modules\webpack\lib\index.js
- C:\my\nice\folder\.yarn\$$virtual\webpack-cli-virtual-b2846ce664\0\cache\webpack-cli-npm-4.4.0-2000105866-0d1328369a.zip\node_modules\webpack-cli\lib\webpack-cli.js
- C:\my\nice\folder\.yarn\$$virtual\webpack-cli-virtual-b2846ce664\0\cache\webpack-cli-npm-4.4.0-2000105866-0d1328369a.zip\node_modules\webpack-cli\lib\bootstrap.js
- C:\my\nice\folder\.yarn\$$virtual\webpack-cli-virtual-b2846ce664\0\cache\webpack-cli-npm-4.4.0-2000105866-0d1328369a.zip\node_modules\webpack-cli\bin\cli.js
- C:\my\nice\folder\.yarn\$$virtual\webpack-virtual-aec5acf597\0\cache\webpack-npm-5.17.0-e594321923-2840d6291d.zip\node_modules\webpack\bin\webpack.js
(during deserialization of Array)
(during deserialization of webpack/lib/NormalModule)
(during deserialization of Map)
(during deserialization of webpack/lib/cache/PackFileCacheStrategy PackContentItems)
```
This warning is produced so often, my terminal's backlog isn't enough to keep them all. It seems to always be the same over and over (which also makes sense), but i didn't scan the entirety of the output, whether there is anything else in between all these.

The build as such completes successfully. From what i can observe, the warnings only appear, when the cache isn't invalidated early on for other reasons (e.g. config changed).

A temporary fix is adding a package extension to `.yarnrc.yml`:
```
packageExtensions:
  "webpack@*":
    dependencies:
      "mini-css-extract-plugin": "^1.3.3"
```

**If the current behavior is a bug, please provide the steps to reproduce.**
While i could probably make a minimal repo, it's hopefully not necessary. Here are the imho relevant excerpts from my webpack config (other parts changed to `// [...]`):
```
const path = require('path');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
module.exports = {
  infrastructureLogging: {
    debug: /webpack\.cache/,
  },
  // [...]
  plugins: [
    new MiniCssExtractPlugin({
      filename: 'style.css',
    }),
  ],
  optimization: {
    runtimeChunk: {
      name: 'webpackruntime',
    },
    splitChunks: {
      cacheGroups: {
        styles: {
          name: 'styles',
          test: /\.css$/,
          chunks: 'all',
          enforce: true,
        },
        vendors: {
          name: 'vendors',
          test: /[\\/]node_modules[\\/]/,
          chunks: 'all',
          enforce: true,
        },
      },
    },
  },
  cache: {
    type: 'filesystem',
    cacheDirectory: path.resolve(__dirname, '.webpackcache'),
  },
  // [...]
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        loader: 'ts-loader',
        exclude: /node_modules/,
      },
      {
        test: /\.s[ac]ss$/i,
        use: [
          {
            loader: MiniCssExtractPlugin.loader,
            options: {
              modules: {
                namedExport: true,
              },
            },
          },
          {
            loader: 'css-loader',
            options: {
              modules: {
                namedExport: true,
              },
            },
          },
          'sass-loader',
        ],
      },
    ],
  },
};
```

**What is the expected behavior?**
Optimally, the source of the problem would be fixed, either by removing the require, or by making yarn accept it. In case a full fix isn't possible or feasible, a single proper warning, with details on the problem, would be good.

Sadly, i don't even know for sure, where the root of the problem lies: yarn, webpack, mini-css-extract-plugin, or in my configs. My best guess is webpack, that's why i am creating this issue. While having suspicions about the cause, those are not founded enough to justify much speculation from my side.

**Other relevant information:**
webpack version: 5.17.0
Node.js version: 15.6.0
Operating System: Windows 7
Additional tools: Yarn

**Comment by alexander-akait** [comment]
Can you try to use `loader: require.resolve('mini-css-extract-plugin').loader`?

**Comment by alexander-akait** [comment]
I think problem here https://github.com/webpack/webpack/blob/master/lib/serialization/ObjectMiddleware.js#L591...

/cc @sokra Any ideas? We can't `require` deps which is not list of `peerDependenciesMeta`

**Comment by sokra** [comment]
yeah, this is tricky.

One way to fix this would be to place this code in mini-css-extract-plugin:

``` js
const registerLoader = require("webpack").serialization.registerLoader;

registerLoader(/^mini-css-extract-plugin\//, request => {
  require(`.${request.slice("mini-css-extract-plugin".length)}`);
  return true;
});
```

This overrides how the serialization loads requests starting with `mini-css-extract-plugin/` to use this local require. (Path may need to be changed a bit depending on where this code is placed)

**Comment by alexander-akait** [comment]
@ASDFGerte I will fix the problem tomorrow, should be easy

**Comment by alexander-akait** [comment]
@ASDFGerte to be honestly I can't reproduce :confused:

**Comment by alexander-akait** [comment]
Maybe you can provide example of something else? I use your configuration and yarn v2.4.0

**Comment by ASDFGerte** [comment]
Trying to reproduce this, i noticed, that it only happens, when the project is in a contained workspace. This makes it seem less like a webpack problem, but i can't tell.

Here is a repo of the issue: https://github.com/ASDFGerte/webpackissue

Run `yarn install` in the root (i didn't include the cache to make it small), then run `yarn run build` inside the `workspace-a` folder twice (first to create the cache, second to produce the issue).

**Comment by merceyz** [comment]
>  i noticed, that it only happens, when the project is in a contained workspace. This makes it seem less like a webpack problem, but i can't tell.

Sounds like https://yarnpkg.com/features/pnp/#different-behaviours-based-on-workspace--not-a-workspace

**Comment by alexander-akait** [comment]
Found solution, WIP

**Comment by alexander-akait** [comment]
Release will be today
