### ISSUE TITLE
ProcessAssets hook showing warning of deprication

### ISSUE THREAD

**Issue by janiskopsisko** [webpack/webpack#12480]
# Bug report

**What is the current behavior?**

I was porting an older plugin to the latest version of Webpack (5.16.0) In previous versions of webpack I was using `optimizeChunkAssets` method to alter chunks, but now, as documentation suggest, I am using `processAssets` method, and still get the warning: 

DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.

**If the current behavior is a bug, please provide the steps to reproduce.**

This is my code, which created the warning:

```
const { sources } = require('webpack');
...
apply(compiler) {
    compiler.hooks.thisCompilation.tap('myPlugin', (compilation)=>{
        const Compilation = compiler.webpack.Compilation;
        compilation.hooks.processAssets.tap(
        {
	    name: 'myPlugin',
	    stage: Compilation.PROCESS_ASSETS_STAGE_DERIVED // value is -200
        },
        assets => {
	    for(const filename in assets) {
		if(/\.js$/.test(filename)) {
			const source = assets[filename].source()
			compilation.assets[filename] = sources.ConcatSource( methodReturningString(source) )
		}
	    }
       })
    })
}


```

**What is the expected behavior?**

I should not see the warning. Either the documentation or warning is missleading

**Other relevant information:**
webpack version:  5.16.0
Node.js version: 14.15.1
Operating System: MacOS 11.1
Additional tools:

**Comment by alexander-akait** [comment]
`processAssets` is not deprecated, it is new abilities to work with assets, see here https://github.com/webpack/webpack/blob/master/lib/Compilation.js#L695, you need to use `emitAsset` or `updateAsset` or `deleteAsset` and don't touch assets inside `compilation` directly, look here https://webpack.js.org/api/compilation-object/#emitasset on API, feel free to open issue in docs repo to improve it if something misleading

**Comment by janiskopsisko** [comment]
I do understand this a new feature. But, even if I dont do anything within the `processAssets` just the basic bolierplate, I get the same error. This is the code directly from webpack documentation [https://webpack.js.org/api/compilation-hooks/#processassets](https://webpack.js.org/api/compilation-hooks/#processassets)

```
compilation.hooks.processAssets.tap(
  {
    name: 'MyPlugin',
    stage: Compilation.PROCESS_ASSETS_STAGE_ADDITIONS, // see below for more stages
  },
  (assets) => {
   console.log('anything')
  }
);

```

![Screenshot 2021-01-22 at 17 43 43](https://user-images.githubusercontent.com/7488012/105519268-7ffedd80-5cd9-11eb-993a-54fd2ae3741c.png)

![Screenshot 2021-01-22 at 17 44 01](https://user-images.githubusercontent.com/7488012/105519404-ab81c800-5cd9-11eb-8d79-a107305e1ed3.png)

if I'm not doing anything within the processAssets, why the warning?

**Comment by alexander-akait** [comment]
It means other plugin do it, can you run using https://nodejs.org/api/cli.html#cli_trace_deprecation

**Comment by janiskopsisko** [comment]
🤦‍♂️  can I delete this embarassing post? thank you

**Comment by alexander-akait** [comment]
Don't worry, we all make mistakes sometimes
