### ISSUE TITLE
Behavior change in compiler initiation.

### ISSUE THREAD

**Issue by serkanyersen** [webpack/webpack#12481]
sorry to put comments on an old PR. just wanted to point out something. this change altered the behavior of the compiler. and it's not mentioned as a breaking change in the docs.

Previously you could do this.

```javascript
const compiler = webpack(config);

// ... do other things, or pass the compiler to other functions

compiler.run(); // compiler starts here.
```

but now, compiler starts as soon as `webpack` is called. which is not a huge deal, but a significant change in behavior.

Similar change happened for `.watch` it would have started the compiler in watch mode before. now it doesn't work that way.

_Originally posted by @serkanyersen in https://github.com/webpack/webpack/pull/11252#r562877999_

**Comment by sokra** [comment]
> ```js
> const compiler = webpack(config);
> 
> // ... do other things, or pass the compiler to other functions
> 
> compiler.run(); // compiler starts here.
> ```

As far as I know it will still start only when calling `run` resp `watch`. How should it start with `webpack(config)`, it doesn't even know if it should run or watch?

**Comment by alexander-akait** [comment]
@sokra HEre case when you pass `{ watch: true }` in `webpack(optins)`, webpack starts to watch automatically with deprecation message about missing `callback`

@serkanyersen Am i right here?

**Comment by aadisriram** [comment]
I think there is a bug in how progress is being reported

Example config:

```
const config: webpack.Configuration = {
  entry: "./src/index.ts",
  mode: "development",
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        use: "ts-loader",
        exclude: /node_modules/,
      },
    ],
  },
  watch: false,
  resolve: {
    extensions: [".tsx", ".ts", ".js"],
  },
  output: {
    filename: "[name].[contenthash].js",
    path: path.resolve(__dirname, "../dist"),
  },
  plugins: [
    new webpack.ProgressPlugin((percentage) => console.log(percentage)),
  ],
};
```

and this is my code to run the compiler, in this case i'm not calling run



```
console.log("start");
const compiler = webpack([config, config2]);
console.log("end");
```


The output is

```
start
0
0.01
0.01
0.01
mid
end
Done in 2.46s.
```


If I update the code to also execute run,

```
  console.log("start");
  const compiler = webpack(config);
  console.log("mid");
  console.log("end");

  compiler.run(() => {});
```

The output is now

```
start
0
0.01
0.01
0.01
mid
end
0.02
0.02
0.02
0.03
...
```

Either webpack compilation is starting or the '0.01' is a bug! This becomes apparent when you use WebpackBar, the 0.01 triggers the bar to be displayed immediately. This behavior is only showing up in Webpack 5.

**Comment by aadisriram** [comment]
I don't think my comment was off topic, it adds clues as to why it looks like calling webpack() immediately starts the build.

From the original post:
> but now, compiler starts as soon as webpack is called

**Comment by serkanyersen** [comment]
comment from @aadisriram was not off-topic. we were trying to repro this issue on an isolated case. this is what we found. progress is being reported right away which breaks the flow on custom scripts.

**Comment by alexander-akait** [comment]
Please then keep the conversation consistent, the problem described above has nothing to do with `ProgressPlugin`. Even if it has anything to do with it, this is a transitive effect of the problem, so let's find out what you want to get and what is happens now. What is the problem?

**Comment by alexander-akait** [comment]
If you remove `watch: false` something changed?

**Comment by alexander-akait** [comment]
webpack automatically starts compilation only in one moment, when you have `watch: true` or `watch: false` inside config, it is for some edge cases

**Comment by aadisriram** [comment]
removing `watch:false` yielded no changes.

"What is the problem?" -> calling webpack(config) immediately starts compilation as per the progress output (I agree it is a transitive effect) which seems wrong, the compiler shouldn't start until run is called. Even if I never call 'compiler.run()' I have webpack reporting 0.01 progress.

**Comment by alexander-akait** [comment]
@aadisriram Can you provide example/script how you run?

**Comment by aadisriram** [comment]
Sure!

This is what I run:
https://github.com/aadisriram/webpack-tests/blob/testing-progress-bug/webpack-demo/scripts/node-api-adventures.ts

This is how I run:
`yarn run build` which is mapped to `cross-env TS_NODE_PROJECT=\"tsconfig-for-webpack-config.json\" ts-node scripts/node-api-adventures.ts`

**Comment by serkanyersen** [comment]
> Please then keep the conversation consistent, the problem described above has nothing to do with `ProgressPlugin`. Even if it has anything to do with it, this is a transitive effect of the problem, so let's find out what you want to get and what happens now. What is the problem?

@alexander-akait ProgressPlugin starts printing output before we call `run` or `watch` this caused confusion into thinking compilation has started early. 

we also have suspicions that "occasionally" it does indeed start and continue without calling `.run/watch` but no proof on that yet, we will try to rule it out.

**Comment by alexander-akait** [comment]
> @alexander-akait ProgressPlugin starts printing output before we call run or watch this caused confusion into thinking compilation has started early.

It is bug, and yes we need fix it

> we also have suspicions that "occasionally" it does indeed start and continue without calling .run/watch but no proof on that yet, we will try to rule it out.

no magic here, webpack doesn't start `run`/`watch` by default (otherwise webpack-cli was broken), only one exception `{ watch: true }` in this case webpack start `watch` automatically, but it is trick for some edge cases (where developer can change commands which run webpack), in ideals world you need use `const compiler =  webpack();` and `compiler.run(callback)`/`compiler.watch(callback)`

**Comment by serkanyersen** [comment]
@alexander-akait Thanks. 

> so in future we can implement runAsync/watchAsync (Promise API, don't know why nobody requested it)

we actually created a wrapper around this to achieve that. would be awesome to have this built-in.

> we also have suspicions that "occasionally" it does indeed start and continue without calling .run/watch but no proof on that yet, we will try to rule it out.

@aadisriram just gave this a try by running his repro back to back with a script (for around 10000 times lol). looks like we ruled out this issue. only the progress one remains.

**Comment by alexander-akait** [comment]
Bump, we need fix logging https://github.com/webpack/webpack/issues/12481#issuecomment-767095046

**Comment by vankop** [comment]
created an issue with ProgressPlugin
