### ISSUE TITLE
webpack compiles twice on startup in watch mode with yarn berry

### ISSUE THREAD

**Issue by artembatura** [webpack/webpack#12483]
# Bug report

**What is the current behavior?**

webpack emits extra message about compilation on startup with yarn berry:

<details>
  <summary>Screenshot</summary>

  ![Screenshot_621](https://user-images.githubusercontent.com/17342159/105569272-72853a00-5d51-11eb-8ad4-703cc136a113.png)

</details>

**If the current behavior is a bug, please provide the steps to reproduce.**

Reproduction examples: [w/ file-loader](https://github.com/artemirq/webpack-issue-12483-file-loader), [w/ style-loader](https://github.com/artemirq/webpack-12483-style-loader).

We have: webpack in basic configuration, yarn berry and some webpack loader.

1) Loader should be resolved by `require.resolve`
2) You should import file which should be handled by this loader
3) Then you can see that webpack emits extra message about compilation

Note that if you remove `require.resolve` for loader issue will disappear.

*webpack.config.js*

```js
module.exports = {
  module: {
    rules: [
      {
        loader: require.resolve('file-loader'),
        exclude: /\.js$/
      }
    ]
  }
};
```

*src/index.js*
```
const svg = require('./icon.svg');

console.log('svg url', svg);
```

*src/icon.svg* 
```
```

**What is the expected behavior?**

The compilation should only trigger once.

**Other relevant information:**

`node -v` - v14.15.4
`yarn -v` - 2.4.0

"file-loader": "6.2.0",
"webpack": "5.17.0",
"webpack-cli": "4.4.0"

**Comment by jantimon** [comment]
maybe this caused by the same bug like #12498

**Comment by alexander-akait** [comment]
hm, I think no, `removedFiles` is like on the second compilation, webpack thinks something files were removed:
```
Set {
  '/home/evilebottnawi/IdeaProjects/webpack-issue-12483-file-loader/.yarn/$$virtual/file-loader-virtual-dc9b9074ac/0',
  '/home/evilebottnawi/IdeaProjects/webpack-issue-12483-file-loader/.yarn/$$virtual/file-loader-virtual-dc9b9074ac',
  '/home/evilebottnawi/IdeaProjects/webpack-issue-12483-file-loader/.yarn/$$virtual'
}
```

**Comment by sokra** [comment]
Since this is a virtual filesystem, we should also check how it behaves when requesting `fs.stat` for this (fake) folders.

**Comment by arcanis** [comment]
The stat calls for `.yarn/$$virtual` and `.yarn/$$virtual/<hash>` are meant to return the same result as for a stat call on `.yarn`. The stat calls in individual file/folders inside that should return the same stat as the original entry. How does Webpack knows which files have been removed?

Note that the virtual entries won't be returned as part of a `readdir` call though, since there's virtually an infinite number of them.

**Comment by sokra** [comment]
> Note that the virtual entries won't be returned as part of a `readdir` call though

That's probably the problem. When starting watching we will do an initial scan of the folders. If readdir doesn't return the files it will be marked as removed.

**Comment by sokra** [comment]
For webpack that's only a filesystem. We don't know it's special/virtual. If it behaves inconsistent that will lead to problems.

**Comment by arcanis** [comment]
Yep I understand, but unfortunately I don't have a good answer; I don't think we could change that easily 🤔

Note that even on typical file systems you may be able to read a child entry without being able to access its parent's directory listing, so it's not entirely foolproof either. Perhaps once you've made a first pass on the `readdir` it would make sense to run a stat call to validate the removal?

**Comment by artemirq** [comment]
Bump!

**Comment by donileo** [comment]
Any workarounds or update on this?

**Comment by alexander-akait** [comment]
No, due https://github.com/webpack/webpack/issues/12483#issuecomment-767034297

**Comment by decademoon** [comment]
Webpack 4 + pnp-webpack-plugin did not have this issue. What changed?

**Comment by arcanis** [comment]
> No, due [#12483 (comment)](https://github.com/webpack/webpack/issues/12483#issuecomment-767034297)

@alexander-akai Note that what I mentioned should still be a valid workaround. I understand you'd prefer to do as little IO as possible, but in this case file removals should be a fairly rare occurence (especially under PnP, which doesn't have hoisting), so I don't think it would have much impact on Webpack's speed (unlike these double-installs). And at worst you can even enable this check only if `process.versions.pnp` is set.

> Perhaps once you've detected a removal via `readdir` it would make sense to confirm it via a `stat` call?

**Comment by alexander-akait** [comment]
We need check it, maybe solved, but let's keep

**Comment by fengerzh** [comment]
Has this issue been solved?

**Comment by alexander-akait** [comment]
I think no, let's reopen

**Comment by decademoon** [comment]
I "fixed" this problem by ignoring files in the `.yarn` directory:

```
watchOptions.ignored = /\/\.yarn\//
```

I think it's a good compromise until the issue is fixed.

**Comment by Bosch-Eli-Black** [comment]
@alexander-akait Has this been fixed?

**Comment by alexander-akait** [comment]
I think no... let's open, but I am afraid it can be unfixable, because it is API of yarn...

**Comment by artemirq** [comment]
@alexander-akait Looks like still not fixed, let's reopen?

<details>
  <summary>Screenshot</summary>
  
  ![image](https://user-images.githubusercontent.com/17342159/198857465-b80aa5e3-8076-487a-b631-3b9580a05063.png)
</details>

**Comment by artemirq** [comment]
@alexander-akait Looks like problem still can be reproduced with any loader. Originally it was reproduced with `file-loader` (example in the issue) but now this loader is deprecated so I have tried other loaders and created simple example using style loader: https://github.com/artemirq/webpack-12483-style-loader.

As mentioned there and as I understand https://github.com/webpack/webpack/issues/12483#issuecomment-767034297 as one of the solution webpack need to use special workaround for yarn pnp to additionally check if file was actually removed.

Also related issues: webpack#13813 (possible solution?), yarnpkg/berry#3311.

**Comment by alexander-akait** [comment]
@artemirq Yeah, thank you, Yarn PnP is buggy (though enough time has passed), I put your repo in my todo (will look at this in near future), sometimes I am thinking using `npm`/`pnpm` is better than wait fixes (before when I looked, bugs were in yarn PnP implementation, that is why it is still not fixed)

**Comment by arcanis** [comment]
I'm not aware of any bug in the PnP implementation. Last time I checked this thread the problem seemed to be related to how Webpack crawl the filesystem for changes, which had an adverse interaction with virtual filesystems.

Cf my last post: https://github.com/webpack/webpack/issues/12483#issuecomment-900924347

**Comment by artemirq** [comment]
@alexander-akait No problem, thank you too for investing your time in this. As from my (small) experience I think yarn one of the most stable package managers. I also used pnpm and there was problems too. But anyway this is all great modern package managers that are actively developing.

I think this issue is related to compatibility with yarn berry PnP. It's not a yarn bug just implementation specificity. Virtual filesystem has their trade-offs. Problem with double compilation isn't so critical and for me it's just additional message in terminal. But we have more important issues such as [increased bundle size](https://github.com/webpack/webpack/issues/13813) and [slow recompilation](https://github.com/yarnpkg/berry/issues/3311) using yarn PnP. Actually I didn't check last two issues for myself. Possible we can have one solution from webpack perspective for all this problems including current one.

As per me probably I will switch to node modules in potentially problematic projects so it's not a blocking issue for me. Thanks.

**Comment by alexander-akait** [comment]
@arcanis 

> That's probably the problem. When starting watching we will do an initial scan of the folders. If readdir doesn't return the files it will be marked as removed.

And here bottleneck, it works with any other package manager, and it is hard to implement good watching without it, we can avoid/hide double compilation message, but under the hood it will create problems with perf and tracking changes after initial compilation. I think that such tools should be transparent and do not affect the logic (or provide official "workaround" for such limitations). If each package manager introduces their own limitations, then maintaining them will become a huge headache for developers. 

> And at worst you can even enable this check only if process.versions.pnp is set.

We already do it, but we can't get list of files, so we can't track them

**Comment by Bosch-Eli-Black** [comment]
@alexander-akait Should this be reopened? I think `webpack-bot` closed it due to lack of activity, but it doesn't look like the core issue has been solved.

**Comment by jackw** [comment]
Looking at the webpack logs in the yarn PNP project I'm working in it hasn't been solved. `.yarn/__virtual__` has files deleted causing multiple builds.

```
webpack 5.88.1 compiled successfully in 14195 ms
    [IdleFileCachePlugin] Initial cache was generated and cache will be persisted in 5s.
    [webpack-cli] Compiler finished
    [webpack-cli] Compiler is watching files for updates...
No errors found.
    [webpack.cache.PackFileCacheStrategy] Pack got invalid because of write to: HtmlWebpackCompiler|0|Compilation/modules|javascript/esm|data:text/javascript,__webpack_public_path__ = __webpack_base_uri__ = htmlWebpackPluginPublicPath;
    [webpack-cli] Compiler starting...
    [webpack-cli] Compiler is using config: '/Users/jackwestbrook/dev/grafana/grafana/scripts/webpack/webpack.dev.js'
    [ForkTsCheckerWebpackPlugin] Calling reporter service for incremental check.
      Changed files: []
      Deleted files: ["/Users/jackwestbrook/dev/grafana/grafana/.yarn/__virtual__","/Users/jackwestbrook/dev/grafana/grafana/.yarn/__virtual__/html-webpack-plugin-virtual-c9af7f7789","/Users/jackwestbrook/dev/grafana/grafana/.yarn/__virtual__/css-loader-virtual-c45ab14dec","/Users/jackwestbrook/dev/grafana/grafana/.yarn/__virtual__/postcss-loader-virtual-1d673f9e90","/Users/jackwestbrook/dev/grafana/grafana/.yarn/__virtual__/sass-loader-virtual-0efb83f2a1","/Users/jackwestbrook/dev/grafana/grafana/.yarn/__virtual__/mini-css-extract-plugin-virtual-bc1740f587","/Users/jackwestbrook/dev/grafana/grafana/.yarn/__virtual__/html-webpack-plugin-virtual-c9af7f7789/0","/Users/jackwestbrook/dev/grafana/grafana/.yarn/__virtual__/css-loader-virtual-c45ab14dec/0"]
assets by status 202 MiB [cached] 354 assets
assets by path . 13.5 KiB
  asset ../views/index.html 11.5 KiB [emitted]
  asset ../views/error.html 2.02 KiB [emitted]
Entrypoint app 67.4 MiB = runtime~app.797ecd5d509df5cbe044.js 33.4 KiB app.75437bb7d5af65049483.js 67.4 MiB
Entrypoint dark 270 KiB = runtime~dark.71c9ab3adda9375bbfbd.js 5.92 KiB grafana.dark.5200fa7e966a3fefd795.css 263 KiB dark.c4c3327207a0a58f8b9e.js 1.6 KiB
Entrypoint light 270 KiB = runtime~light.30ec9b624ea7fdff6498.js 5.92 KiB grafana.light.676957064d3021635f66.css 262 KiB light.c8c51a8ceca753030880.js 1.61 KiB
cached modules 46.9 MiB (javascript) 514 KiB (css/mini-extract) 70.8 KiB (asset) 35.6 KiB (runtime) [cached] 9860 modules
javascript modules 2.64 KiB
  ./public/app/ sync extensions\/index.ts 160 bytes [built]
  ./public/app/ sync \.html$ 2.49 KiB [built]
webpack 5.88.1 compiled successfully in 5183 ms
    [IdleFileCachePlugin] Initial cache was generated and cache will be persisted in 5s.
    [webpack-cli] Compiler finished
    [MemoryWithGcCachePlugin] 47464 active entries, 3478 recently unused cached entries
    [webpack-cli] Compiler is watching files for updates...
No errors found.
    [webpack-cli] Compiler starting...
    [webpack-cli] Compiler is using config: '/Users/jackwestbrook/dev/grafana/grafana/scripts/webpack/webpack.dev.js'
    [ForkTsCheckerWebpackPlugin] Calling reporter service for incremental check.
      Changed files: []
      Deleted files: ["/Users/jackwestbrook/dev/grafana/grafana/.yarn/__virtual__/mini-css-extract-plugin-virtual-bc1740f587/0"]
assets by status 202 MiB [cached] 354 assets
assets by path . 13.5 KiB
  asset ../views/index.html 11.5 KiB [emitted]
  asset ../views/error.html 2.02 KiB [emitted]
Entrypoint app 67.4 MiB = runtime~app.797ecd5d509df5cbe044.js 33.4 KiB app.75437bb7d5af65049483.js 67.4 MiB
Entrypoint dark 270 KiB = runtime~dark.71c9ab3adda9375bbfbd.js 5.92 KiB grafana.dark.5200fa7e966a3fefd795.css 263 KiB dark.c4c3327207a0a58f8b9e.js 1.6 KiB
Entrypoint light 270 KiB = runtime~light.30ec9b624ea7fdff6498.js 5.92 KiB grafana.light.676957064d3021635f66.css 262 KiB light.c8c51a8ceca753030880.js 1.61 KiB
cached modules 46.9 MiB (javascript) 514 KiB (css/mini-extract) 70.8 KiB (asset) 35.6 KiB (runtime) [cached] 9862 modules
webpack 5.88.1 compiled successfully in 1201 ms
    [IdleFileCachePlugin] Initial cache was generated and cache will be persisted in 5s.
    [webpack-cli] Compiler finished
    [MemoryWithGcCachePlugin] 44126 active entries, 6816 recently unused cached entries
    [webpack-cli] Compiler is watching files for updates...
No errors found.
    [webpack.cache.PackFileCacheStrategy] Storing pack...
<t> [webpack.cache.PackFileCacheStrategy] resolve build dependencies: 597.471875 ms
<t> [webpack.cache.PackFileCacheStrategy] snapshot build dependencies: 121.786833 ms
    [webpack.cache.PackFileCacheStrategy] 50526 fresh items in cache put into pack 0 (25264 items), 1 (25262 items)
<t> [webpack.cache.PackFileCacheStrategy] store pack: 3644.1055420000002 ms
    [webpack.cache.PackFileCacheStrategy] Stored pack (50526 items, 2 files, 493 MiB)
```
