### ISSUE TITLE
SplitChunksPlugin crash when optimization.splitChunks.maxSize is set

### ISSUE THREAD

**Issue by smitty3268** [webpack/webpack#12487]
**Bug Report**

**What is the current behavior?**
Webpack crashes when splitting my project in 5.17.0 when a maxSize is set. 

This behavior varies depending on the packages being splits, as well as the maxSize and minSize that are set. I'm able to consistently avoid problems by setting minSize to 0. The larger I set it, the more likely it is for a problem to occur.

I get the following stack trace when it fails:

```
SplitChunksPlugin(node:22720) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'size' of undefined
    at module.exports (C:\_code\Intranet\trunk\Web\node_modules\webpack\lib\util\deterministicGrouping.js:339:44)
    at C:\_code\Intranet\trunk\Web\node_modules\webpack\lib\optimize\SplitChunksPlugin.js:1589:23
    at Hook.eval [as call] (eval at create (C:\_code\Intranet\trunk\Web\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:19:10), <anonymous>:39:16)
    at Hook.CALL_DELEGATE [as _call] (C:\_code\Intranet\trunk\Web\node_modules\webpack\node_modules\tapable\lib\Hook.js:14:14)
    at Compilation.seal (C:\_code\Intranet\trunk\Web\node_modules\webpack\lib\Compilation.js:2101:36)
    at C:\_code\Intranet\trunk\Web\node_modules\webpack\lib\Compiler.js:1056:20
    at C:\_code\Intranet\trunk\Web\node_modules\webpack\lib\Compilation.js:1925:4
    at _next2 (eval at create (C:\_code\Intranet\trunk\Web\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:35:1)
    at eval (eval at create (C:\_code\Intranet\trunk\Web\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:71:1)
    at C:\_code\Intranet\trunk\Web\node_modules\webpack\lib\FlagDependencyExportsPlugin.js:332:11
(node:22720) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:22720) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Looking at the code where it crashes, I see this:

```
let left = 1;
let leftSize = Object.create(null);
addSizeTo(leftSize, group.nodes[0].size);
while (isTooSmall(leftSize, minSize)) {
    addSizeTo(leftSize, group.nodes[left].size); //this is the crash, left has exceeded the length of the nodes list.
    left++;
}
```

I don't see how exactly this is supposed to work, as there doesn't appear to be anything stopping left from incrementing up past the length of the available nodes. This code is what made me realize setting minSize lower would workaround the issue, though, as setting it small enough simply ensures the while loop is never entered.

**If the current behavior is a bug, please provide the steps to reproduce.**
On my codebase, setting maxSize smaller and minSize larger seems to be more likely to cause the bug.

```
optimization: {
    chunks: 'all', 
    maxAsyncRequests: Infinity,
    maxInitialRequests: Infinity,
    maxSize: 100000,
    //minSize: 1,
    cacheGroups: {
        sharedcomponents: {
            test: /[\\/]_shared[\\/]src/,
            name: 'sharedcomponents',
            reuseExistingChunk: true
        },
	vendors: {
            test: /[\\/]node_modules[\\/]/,
            name: 'vendors',
	    reuseExistingChunk: true
        }
    }
}
```

**What is the expected behavior?**
Webpack should generate chunks with an appropriate maxSize if possible, and anything smaller is acceptable as well. Having a chunk smaller than the minSize shouldn't crash.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
Webpack 5.17.0. Also had the same issue on 5.14.0. Haven't tested any older versions.
Node 12.13.0

**Comment by smitty3268** [comment]
Some debugging of values before it crashes:

```
leftSize:{"javascript":166867,"css/mini-extract":6848}
minSize:{"javascript":20000,"unknown":20000,"css/mini-extract":20000}
isTooSmall:true
group.size:{"javascript":166867,"css/mini-extract":6848}
maxSize:{"javascript":100000,"unknown":100000,"css/mini-extract":100000}
isTooBig:true
```

Maybe this has to do with multiple types of code in the bundle?

**Comment by sokra** [comment]
Yeah seems a but that happens when a group is too big and too small at the same time.

**Comment by mupic** [comment]
Same problem.

**Comment by wojtekmaj** [comment]
So I looked at the loop that's crashing:

https://github.com/webpack/webpack/blob/8c8f4c93bb2114606bd20978bf2f0ab961bd391e/lib/util/deterministicGrouping.js#L345-L348

and changed it a little bit to see what's causing the error:

```js
while (isTooSmall(rightSize, minSize)) {
	if (group.nodes[right]) {
		addSizeTo(rightSize, group.nodes[right].size);
	} else {
		throw new Error({ node:group.nodes[right], right });
	}
	right--;
}
```

and sure enough, this is what I got: in logs:

```js
{
  "node" undefined,
  "right": -1
}
```

A fix as simple as

```diff
-				while (isTooSmall(rightSize, minSize)) {
+ 				while (right && isTooSmall(rightSize, minSize)) {
```

fixed the issue.
