### ISSUE TITLE
devServer can not show html but dir, with module.exports=array

### ISSUE THREAD

**Issue by lornally** [webpack/webpack#12499]
# Bug report

**What is the current behavior?**
when i use  "webpack serve", http://localhost:8080/  only show: '~/' (the blank directory)

**If the current behavior is a bug, please provide the steps to reproduce.**
this is my webpack.config.coffee
```coffeescript
cmd = # here is another config

html = # here is config for html
	entry: d1: './src/d1.js'
	output:
		path: path.resolve __dirname, 'dist/html'
		filename: '[name].[contenthash].js'
	plugins: [
		new HtmlWebpackPlugin	title: 'Development'
	]
	devServer: contentBase: './dist/html'

module.exports=[html,cmd] # if i use this line, http://localhost:8080/ is ~/
module.exports=[html] # if i use this line, http://localhost:8080/ is right
```

**What is the expected behavior?**
http://localhost:8080/ show '~/', it should show the index.html of the website.

**Other relevant information:**
webpack version:  5.4.0
Node.js version:  15.5.0
Operating System:  macos bigsur 11.1
Additional tools: vscode, coffeescript

**Comment by alexander-akait** [comment]
Doesn't related to webpack, please open an issue in `webpack-dev-server` with **normal** reproducible test repo, thanks
