### ISSUE TITLE
webpack compiles twice if compilation.fileDependencies.add is used

### ISSUE THREAD

**Issue by jantimon** [webpack/webpack#12498]
# Bug report

**What is the current behavior?**

If a plugin adds fileDependencies during the `make` phase the initial webpack compilation runs twice:

<img width="658" alt="webpack_logger_demo__forked__-_CodeSandbox" src="https://user-images.githubusercontent.com/4113649/105640092-68138f00-5e7c-11eb-8203-43b0efcff7b9.png">

**If the current behavior is a bug, please provide the steps to reproduce.**

codesandbox:

https://codesandbox.io/s/webpack-recompilation-58sx6?file=/webpack.config.js

minimal reproduction example:

webpack.config.js
```js
class MyDemoPlugin {
  apply(compiler) {
    compiler.hooks.make.tapPromise("MyDemoPlugin", async (compilation) => {
      compilation.fileDependencies.add("./package.json");
    });
  }
}

module.exports = {
  mode: "development",
  plugins: [new MyDemoPlugin()]
};
```

```
webpack serve
```

**What is the expected behavior?**

The initial compilation should only run once

**Other relevant information:**
webpack version:  5.17.0

**Comment by sokra** [comment]
You must use absolute paths in `fileDependencies`. Otherwise this is like passing a non-existing file, webpack will think this file was removed during compilation and will recompile because of that.

**Comment by jantimon** [comment]
Thanks for your late sunday evening support 👍

It works now perfectly - maybe an error or a jsdoc comment might help plugin devs here.
