### ISSUE TITLE
[ Q ] How can I make multiple class names in localIdentName

### ISSUE THREAD

**Issue by rendstack** [webpack/webpack#12491]
```js
     localIdentName: '[hash:base64:8]'
// ... 
   test: /\.css$/,
                use: [
                    {
                        loader: 'style-loader'
                    },
                    {
                        loader: 'css-loader',
                        options: {
                            importLoaders: 1,

                        }
                    }
```

There is such a construction. In general I'm trying to do

```jsx
import classnames from 'classnames/bind'
import styles from './main.module.css'

const cx = classnames.bind(styles)

const multiClassNames = (c) => cx(`${c}`.split(" "))

<div className={ multiClassNames("foo bar baz ....")}>
```
This works, but it gets tricky to do this for all classes every time. Is there any easier way to do this

**Comment by alexander-akait** [comment]
Not related to webpack, please use `css-loader` repo in future, you can't do it, you can use https://github.com/webpack-contrib/css-loader#exportlocalsconvention, for example `camelCase`, you will have `camelCase` and `original` classes, anyway having multiple cases will increase your bundled JS and CSS files, I strongly do not recommend to do it, anyway if you have real use case where you really need this, please open an issue in `css-loader` and provide example
