### ISSUE TITLE
webpack.log and webpack.debug are not outputting messages

### ISSUE THREAD

**Issue by jantimon** [webpack/webpack#12492]
# Bug report

**What is the current behavior?**

I haven't look deep into `compiler.getInfrastructureLogger` so maybe I am misusing it somehow.

From [the logging docs](https://webpack.js.org/api/logging/):

> `logger.log(...)`: for unimportant information messages. These messages are displayed only when user had opted-in to see them

> logger.log. Displayed expanded when logging level is set to 'verbose' or 'debug'.

From the [stats logging docs](https://webpack.js.org/configuration/stats/#statslogging):

>  - 'log', true - errors, warnings, info messages, log messages, groups, clears. Collapsed groups are displayed in a collapsed state.
> - 'verbose' - log everything except debug and trace. Collapsed groups are displayed in expanded state.

From that docs I expected that

```js
const logger = compilation.compiler.getInfrastructureLogger(
  "my-demo-plugin"
);
logger.info("info");
logger.log("log");
logger.warn("warn");
logger.debug("debug");
```

I would have expected to see the following 4 messages:

- info
- log
- warn
- debug

But instead I only see:

- info
- warn

**If the current behavior is a bug, please provide the steps to reproduce.**

Full webpack.config.js

webpack.config.js
```js
class MyDemoPlugin {
  apply(compiler) {
    compiler.hooks.make.tapPromise("MyDemoPlugin", async (compilation) => {
      const logger = compilation.compiler.getInfrastructureLogger(
        "my-demo-plugin"
      );
      logger.info("info");
      logger.log("log");
      logger.warn("warn");
      logger.debug("debug");
    });
  }
}

module.exports = {
  plugins: [new MyDemoPlugin()],
  stats: {
    logging: true,
    loggingDebug: [(name) => name.contains("my-demo-plugin")]
  }
};
```

same for 

```js
stats: {
    logging: 'verbose'
  }
```

codesandbox:  https://codesandbox.io/s/webpack-logger-demo-8l7yl?file=/webpack.config.js

**What is the expected behavior?**

The following infrastructure logger command should send "myMessage" to the visible console output

```js
compiler
  .getInfrastructureLogger( "my-demo-plugin")
  .log("myMessage")
```

**Other relevant information:**
webpack version:  5.17.0
Node.js version: 10.13.0

**Comment by sokra** [comment]
For infrastructure logging there is a different configuration option:

``` js
infrastructureLogging: {
  level: "verbose",
  debug: /my-demo-plugin/
}
```

**Comment by jantimon** [comment]
Oh that makes sense - is there a guide which logger should be used?

**Comment by sokra** [comment]
If the plugin/logging is related to the compilation, use the normal logger. This is most often the case.

For logging that happens outside of the compilation cycle, there is the infrastructure logger.

Prefer the normal logger.

Normal logging is stored within the stats.

**Comment by jantimon** [comment]
Thanks a lot I'll close this for now - should I add this information to the docs?

**Comment by eps1lon** [comment]
> If the plugin/logging is related to the compilation, use the normal logger. This is most often the case.

@sokra Shouldn't the documentation reflect that? Right now the documentation explicitly states to use `getInfrastructureLogger` for plugins:

> Examples of how to get and use webpack logger in loaders and plugins
```js
const PLUGIN_NAME = 'my-webpack-plugin';
export class MyWebpackPlugin {
  apply(compiler) {
    // you can access Logger from compiler
    const logger = compiler.getInfrastructureLogger(PLUGIN_NAME);
    logger.log('log from compiler');

    compiler.hooks.compilation.tap(PLUGIN_NAME, (compilation) => {
      // you can also access Logger from compilation
      const logger = compilation.getLogger(PLUGIN_NAME);
      logger.info('log from compilation');
    });
  }
}
```
