### ISSUE TITLE
New watching solution

### ISSUE THREAD

**Issue by sokra** [webpack/webpack#125]
(see #122)

The watching implementation is far from perfect. Implement a new watching module and use it in webpack.

The new watching module should have to following properties:

* Watcher should be applied backdated. Solve this by reading filestamps and compare them with the wished start time.
* It should watch files and directories. For files changing content is relevant. For directories changing the contained files is relevant (renaming counts too).
* Emit events for changed stuff.
* Emit a delayed event, which is emitted when for a specified time no additional change occures.
* `pause`: Don't emit event anymore, but keep the watchers alive. When starting again less timestamps need to be read and less watchers need to be attached. This should make the whole stuff more stable.
* `close`: Really close everything.
* There is a limit for file watchers, so don't watch every file, but only watch the parent directory. This reduces the watcher count. It must be the direct parent directory. A directory watcher may result in many attached watchers for each child directory. After a change in a directory the timestamps of the files are checked (no every os tells you the filename, but if it do then use it).
* `persistant` option (because it is easy)
* Don't crash on file delete
* Multiple watchers can share fs watchers
* Cope with decreasing timestamps (branch switch, etc.)
* It should have a cool name (wootcher, watchtress, witcher?)

**UPDATE: Try it with:**

``` js
plugins: [
  new webpack.NewWatchingPlugin()
]
```

**Comment by gaearon** [comment]
New watching plugin seems to fail on Node 0.10 with `undefined is not a function` after file is saved.
Is it just me?

**Comment by sokra** [comment]
new watching is now default...

All the watching logic is in this module: https://github.com/webpack/watchpack
Feel free to use it...

**Comment by ColCh** [comment]
Any migration needed?

**Comment by sokra** [comment]
If you have used the NewWatchingPlugin you should now omit it.

If for some reason the new watching doesn't work, you can use the OldWatchingPlugin. 😉

**Comment by jhnns** [comment]
> Symlinks are not followed, instead the symlink is watched.

I need to test if watchers are still working when I'm using [link-package](https://github.com/peerigon/link-package) then.

**Comment by ericprieto** [comment]
Does this work on a shared folder under a VirtualBox VM? Or do I have to use rsync sharing?

**Comment by madebyherzblut** [comment]
We had a few problems with shared folders a while ago. Because of that we now use rsync with [vagrant-gatling-sync](https://github.com/smerrill/vagrant-gatling-rsync) and it works great. Of course, for one way syncing only.

**Comment by ericprieto** [comment]
Yeah, I tried that, but I need two way syncing.... Luckly, I found **unison**, a sync tool via ssh. It works very fast, faster than rsync I guess.... Well, I'm using it and it's working :dancer: 

Thanks for your answer!

**Comment by ColCh** [comment]
@ericprieto If you're looking for perfect Vagrant dir sharing, try to share "current work dir" with 2 mount point - one for rsync and one for usual vboxsf. That gives just perfect workflow with file sharing...

**Comment by fresheneesz** [comment]
@ericprieto Could you elaborate a bit on that? I'm pretty unhappy with way's I've found to do a shared folder in vagrant. Is there somewhere you could link to that describes that in more detail? I'll also have to look at unison - i built my own ad hoc watcher that's actually working pretty well at this point, but could be faster.

**Comment by rarkins** [comment]
@fresheneesz I documented how we install/use unison with vagrant manually: https://keylocation.sg/blog/vagrant-and-unison-without-a-plugin/

**Comment by ericprieto** [comment]
After a few weeks trying unison and every other solution, I just gave up.

Install Linux. Be Happy.

**Comment by SpaceK33z** [comment]
@ericprieto As of webpack 1.9.10 you can use `webpack --watch --watch-polling` (see 297707d42debc8cff41d7d24d709034228149bd8). This works perfectly fine over NFS and in combination with Vagrant.

**Comment by ericprieto** [comment]
Awesome!

**Comment by stas-webwork** [comment]
SpaceK33z, thanks.
--watch-polling

**Comment by alanbacon** [comment]
I found "--watch-polling" doesn't work. Instead I had to use "--watch-poll".... it's a small thing but nevertheless a source of confusion. I'm running webpack 1.11.0 and webpack-dev-server 1.10.1

**Comment by 3oheme** [comment]
@alanbacon `--watch-poll` also works great for me, thanks!

Macbook pro late 2011
Iterm2 Build 2.1.1 
Vagrant 1.7.2
NPM 1.4.28

**Comment by piecyk** [comment]
Hi i'm getting some strange behavior and don't know what is wrong, using webpack 2.0 and NewWatchingPlugin on VM with Arch Linux, running `webpack --watch --watch-poll`
everything is good till (lint works on every file change) i got some `Module build failed` error. For example `f ( {}` and save this. 
Will throw an error from babel-loader and after fixing it it will not reload the file. Watch is stuck! need to change dir to diffident component (modifies something there, and hoping that it will work)
I added the `fs.inotify.max_user_watches=524288` but didn't help...

Has some seen something similar? this is my config ( tried so many configuration but nothing helped ) and don't know if it's webpack or babel-loader problem ?

```
var path    = require('path');
var webpack = require('webpack');

//
var gulpUtil = require('gulp-util');
var env = gulpUtil.env;
var isProduction = env.env === 'production';

module.exports = {
  debug: !isProduction,
  resolve: {
    modules: [
      path.resolve(__dirname, 'src')
    ],
    alias: {
      lib: path.resolve(__dirname, 'src/lib')
    },
    extensions: ['', '.js', '.jsx', '.json'],
    unsafeCache: true
  },
  entry: {
    global: './src/a/global.js',
    pub: './src/a/site/js/pub.js',
    app: './src/a/app.js'
  },
  output: {
    path: path.join(__dirname, 'build/js'),
    filename: '[name].js',
    publicPath: '/build/js/'
  },
  plugins: [
    new webpack.optimize.CommonsChunkPlugin({
      name: 'commons',
      chunks: ['pub', 'global', 'app'],
      minChunks: 2 // How many times a dependency must come up before being extracted
    }),
    new webpack.DefinePlugin({
      "process.env": {
        "NODE_ENV": JSON.stringify(env.env)
      }
    }),
    new webpack.ProgressPlugin()
  ].concat(isProduction ? [
    // This plugin looks for similar chunks and files
    // and merges them for better caching by the user
    new webpack.optimize.DedupePlugin(),
    // This plugin prevents Webpack from creating chunks
    // that would be too small to be worth loading separately
    new webpack.optimize.MinChunkSizePlugin({
      minChunkSize: 51200 // ~50kb
    }),
    // This plugin minifies all the Javascript code of the final bundle
    new webpack.optimize.UglifyJsPlugin({
      mangle: true,
      showStack: true,
      compress: {
        drop_console: true
      }
    })
  ] : [
    new webpack.NewWatchingPlugin(),
    // new webpack.WatchIgnorePlugin(),
    new webpack.SourceMapDevToolPlugin({
      filename: '[file].map',
      exclude: ['global', 'pub'],
      columns: false
    })
  ]),
  module: {
function(errors) { gulpUtil.log("\n" + errors); }] : null))
    preLoaders: [
      {
        test: /\.(js|jsx)$/,
        loader: 'eslint-loader',
        include: path.resolve(__dirname, 'src'),
        exclude: [
          path.resolve(__dirname, 'src/lib/vendor'),
          path.resolve(__dirname, 'src/lib/router.js'),
        ]
      }
    ],
    loaders: [
      {
        test: /.(js|jsx)?$/,
        loader: 'babel-loader?cacheDirectory',
        include: path.resolve(__dirname, 'src')
      },
      {
        test: /\.json$/,
        loader: 'json-loader'
      }
    ]
  }
};
```

**Comment by ColCh** [comment]
@piecyk you should ask this on SO, probably.

Try to set larger watch timeouts:
```
watchOptions: {
    aggregateTimeout: 800,
    poll: 1500
}
```
It's in webpack-dev-server's config, [please see more in docs](https://webpack.github.io/docs/webpack-dev-server.html#additional-configuration-options)

**Comment by piecyk** [comment]
@ColCh it's not a problem of timeouts, watch is working good till i hit the first `Parsing error` 
then it is stuck... hmm i think something is wrong around `babel-loader`

**Comment by ColCh** [comment]
@piecyk Try then inlude [NoErrorsPlugin](https://github.com/webpack/docs/wiki/list-of-plugins#noerrorsplugin) and specify __babel-loader__ presets in webpack config also (I had problems with __.babelrc__ and latest loader version)

**Comment by piecyk** [comment]
From quick debug it looks like when file has error it's removed form the list of files to be watched, 

https://github.com/webpack/webpack/blob/9f440e30ecac00bfc27b91d372a969d3414d194c/lib/node/NodeWatchFileSystem.js#L17 

here `files` don't have this file, event if we fix it and re run it by changing another file it will not reload it... i think cache is taking over here...

**Comment by StephanBijzitter** [comment]
Old watching plugin or new, they both do not pick up on change events.
Running OS X Yosemite, with a Ubuntu 14.04 VM.

When I run the watcher on OS X, all is fine. However, the reason we use a VM is to streamline the process. Bit of a bummer. Polling does not seem to work, either.

**Comment by jhnns** [comment]
[VirtualBox's shared folder does not trigger change events](https://www.virtualbox.org/ticket/10660), so this is not an issue of webpack (further discussion #425). I'm using `rsync` to update the changed files in the VM which works great.

**Comment by ColCh** [comment]
@jhnns it's only with _vboxfs_ of with _NFS_ too?

**Comment by jhnns** [comment]
@ColCh Don't know

**Comment by StephanBijzitter** [comment]
@jhnns When the polling support in webpack also fails, it does make it a webpack problem

**Comment by NickStefan** [comment]
Just moved to using a vagrant + NFS.

- regular build uses the webpack CLI to watch. it wasnt watching changes correctly with vagrant. I turned on polling and it now works flawlessly.

- testing framework wraps webpack's node API and mocha. I turned on polling. it now triggers the watch event correctly (and re-runs our tests). __however, the actual output file is not being rebuilt__.

What could be the difference between the node API and the cli? its the only difference I can think of.

**Comment by StephanBijzitter** [comment]
Just read through all of this, and I must say that it would be great to remove the watcher from webpack entirely. Indeed, we could rely on external packages to watch for us if we get the incremental compilation right! It would reduce maintenance for the webpack team too, it's a win-win!

**Comment by sap9433** [comment]
I think having a plugin to watch external files is a better approach . How does this look ? https://www.npmjs.com/package/filewatcher-webpack-plugin .

**Comment by felipenmoura** [comment]
This is all very interesting.
Is there a way I can/could identify when a watch event was triggered due to a new file, or to a "file changed"?
