### ISSUE TITLE
How to remove LICENSE.txt file using Webpack 5

### ISSUE THREAD

**Issue by yangjocy** [webpack/webpack#12506]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Upon building, LICENSE.txt is generated by default.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. set devtool to false on webpack.config file
2. build a project and check the output
3. a LICENSE.txt file is generated.

**What is the expected behavior?**
a webpack configuration is provided to avoid LICENSE.txt file generation.
I understand "extractComments: false" of terser-webpack-plugin could be used to realize it, but since terser is built in on Webpack 5, I cannot set this attribute directly.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
Node.js version: 14.15.1
webpack version: 5
OS: win dows 10

**Comment by alexander-akait** [comment]
https://github.com/webpack-contrib/terser-webpack-plugin#remove-comments

**Comment by alexander-akait** [comment]
Please prefer to use discussion before creating an issue

**Comment by alexander-akait** [comment]
In this case you need manually setup `TerserPlugin`, keep license comments is a good practice

**Comment by yangjocy** [comment]
> https://github.com/webpack-contrib/terser-webpack-plugin#remove-comments

Have read that, but I think it's for Webpack v4 or lower according to Getting Started block:
`If you are using webpack v5 or above you do not need to install this plugin`
And also I worry that by newing a Terser plugin I would accidentally erase the default config/behavior of the build-in Terser plugin.

**Comment by waruyama** [comment]
If you have trouble with `extractComments` option, make sure that you place it **outside** the `TerserOptions` object. It will not work and there is no error message if you place it inside the  `TerserOptions` object.

**Comment by ChrissiQ** [comment]
@waruyama @alexander-akait There is no information in the docs on how I can configure the settings for the terser plugin with Webpack 5.  It just says it's included in Webpack 5, then shows Webpack 4 instructions on how to configure it, which don't work for Webpack 5 because we didn't install terser separately and don't have an exposed TerserPlugin object to configure.

For Webpack 5, do I need to install `terser-webpack-plugin` separately, require it, and set it up as per Webpack 4, just so I can disable the license output?  Does this clobber anything?

The docs do not have an answer relating to Webpack 5, only 4.

**Comment by alexander-akait** [comment]
@ChrissiQ You setup should work, can you provide minimum example?

**Comment by alexander-akait** [comment]
We have test on this case https://github.com/webpack-contrib/terser-webpack-plugin/blob/master/test/extractComments-option.test.js#L573

**Comment by mcha-dev** [comment]
In my case (using webpack 5 with its default terser) I'm already using [clean-webpack-plugin](https://github.com/johnagan/clean-webpack-plugin) so I configured its after build option **cleanAfterEveryBuildPatterns** as follows:

```js
plugins: [
    new CleanWebpackPlugin({
      cleanAfterEveryBuildPatterns: ['*.LICENSE.txt'],
    }),
```

**Comment by Jun711** [comment]
> In my case (using webpack 5 with its default terser) I'm already using [clean-webpack-plugin](https://github.com/johnagan/clean-webpack-plugin) so I configured its after build option **cleanAfterEveryBuildPatterns** as follows:
> 
> ```js
> plugins: [
>     new CleanWebpackPlugin({
>       cleanAfterEveryBuildPatterns: ['*.LICENSE.txt'],
>     }),
> ```

@mcha-dev Is my configuration correct? It doesn't seem to work for me. 
A minimal repo: https://github.com/Jun711/clean-webpack-test

```
const path = require('path');
const { CleanWebpackPlugin } = require('clean-webpack-plugin');

module.exports = {
  mode: 'production',
  entry: [
    './src/test.js',
  ],
  module: {
    rules: [
      {
        test: /\.m?js/,
        resolve: {
            fullySpecified: false
        }
      },
      {
        test: /\.(js)$/,
        exclude: /node_modules/,
        use: ['babel-loader']
      }
    ]
  },
  resolve: {
    extensions: ['*', '.js']
  },
  plugins: [
    new CleanWebpackPlugin({
      cleanAfterEveryBuildPatterns: ['*.LICENSE.txt'],
    })
  ],
  output: {
    filename: '[name].js',
    path: path.resolve(__dirname, 'dist'),
  }
}
```

**Comment by Piero87** [comment]
@Jun711 You have to do this:

```
          new CleanWebpackPlugin({
            protectWebpackAssets: false,
            cleanAfterEveryBuildPatterns: ['*.LICENSE.txt'],
          })
```

**Comment by ajimae** [comment]
> @Jun711 You have to do this:
> 
> ```
>           new CleanWebpackPlugin({
>             protectWebpackAssets: false,
>             cleanAfterEveryBuildPatterns: ['*.LICENSE.txt'],
>           })
> ```

This works for me

**Comment by noscripter** [comment]
It should be merged into source file all removed by default.

**Comment by ouweiya** [comment]
If you don't want to change the default configuration, adding a simple custom plugin can help.

```js
npm i rimraf

const rimraf = require('rimraf');

plugins: [
  new (class {
    apply(compiler) {
      compiler.hooks.done.tap('Remove LICENSE', () => {
        console.log('Remove LICENSE.txt');
        rimraf.sync('./dist/*.LICENSE.txt');
      });
    }
  })(),
]
```

**Comment by JeViCo** [comment]
Keep in mind that path is relative
> console.log('Remove LICENSE.txt');
> rimraf.sync('./dist/*.LICENSE.txt');

Also rimraf supports glob-like patterns so you probably want this
```javascript
rimraf.sync('dist/**/*.LICENSE.txt');
```

**Comment by Program-Monkey** [comment]
> If you have trouble with `extractComments` option, make sure that you place it **outside** the `TerserOptions` object. It will not work and there is no error message if you place it inside the `TerserOptions` object.

it works for me

**Comment by Constaline** [comment]
This custom plugin will delete the LICENSE.txt file from assets.


```javascript
// remove-license-file-plugin.js

class RemoveLicenseFilePlugin {
    apply(compiler) {
        compiler.hooks.emit.tap("RemoveLicenseFilePlugin", (compilation) => {
            // compliation has assets to output
            // console.log(compilation.assets);
            for (let name in compilation.assets) {
                if (name.endsWith("LICENSE.txt")) {
                    delete compilation.assets[name];
                }
            }
        });
    }
}

module.exports = RemoveLicenseFilePlugin;
```


```javascript
//  webpack.config.js

const RemoveLicenseFilePlugin= require("./remove-license-file-plugin");

module.exports =  {

    plugins: [new RemoveLicenseFilePlugin()],

};
```
