### ISSUE TITLE
Entry with chunkloading import-scripts public path wrong

### ISSUE THREAD

**Issue by janlent1** [webpack/webpack#12502]
# Bug report

**What is the current behavior?**
For my test build, when I am importing another script in my entry with chunkloading set to import-scripts, it requires from the non-test build chunks path/directory which doesn't exist in the non-test build directory. Upon breaking at the importscripts call in webpacks require call, the `__webpack_public_path__` is undefined. But `__webpack_require__.p` is defined, and correct, but it doesn't load from there.

**What is the expected behavior?**
It should load from the configured public path and not from some other path. I don't even know where this path is found.
I added a hack which should set the `__webpack_public_path__ `global var with a entry point entry, but that is also not working. Maybe this variable is not used any more but since the p is set above, I wonder why this doesn't load importscripts from there.

**Other relevant information:**
webpack version:  5.16.0
Node.js version: 12.17.0
Operating System: macOS
Additional tools:

**Comment by janlent1** [comment]
I guess the lib/webworker/ImportScriptsChunkLoadingRuntimeModule.js outputName is wrong? There is no `__webpack_require__.b`

**Comment by janlent1** [comment]
Okay, will debug there and will update whether I see any obvious errors there.

**Comment by alexander-akait** [comment]
Please fill out how we can reproducible it and I will reopen it, please do not ignore it

**Comment by janlent1** [comment]
[https://github.com/webpack/webpack/issues/12577](url)

**Comment by janlent1** [comment]
#12577

**Comment by alexander-akait** [comment]
Feel free to send a PR, it should be easy

**Comment by janlent1** [comment]
@alexander-akait will you merge it? There is someone that didnt report this issue and wants to merge, will you use his pull request or may I push to the repo?

**Comment by alexander-akait** [comment]
https://github.com/webpack/webpack/pull/12610
