### ISSUE TITLE
webpack5 compiler.watchFileSystem.watcher.mtimes attributes display undefined but webpack4 has data why ?

### ISSUE THREAD

**Issue by xiasha1** [webpack/webpack#12507]
webpack5: console undefined

webpac4 4:console object

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Because it was changed use `getFileTimeInfoEntries()` and `getContextTimeInfoEntries()` to get information for files and directories

**Comment by xyoscer** [comment]
> Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.
> 
> Please help us help you by recreating the issue using one of our templates.
> 
> Because it was changed use `getFileTimeInfoEntries()` and `getContextTimeInfoEntries()` to get information for files and directories


Excuse me, through watchFileSystem
 How can I get the current changed files? There are too many files as a result of watcher.getTimeInfoEntries()

**Comment by xyoscer** [comment]
> webpack5: console undefined
> 
> webpac4 4:console object
Encountered the same problem, how is this problem solved?

**Comment by xyoscer** [comment]
> Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.
> 
> Please help us help you by recreating the issue using one of our templates.
> 
> Because it was changed use `getFileTimeInfoEntries()` and `getContextTimeInfoEntries()` to get information for files and directories
can use `compiler.modifiedFiles ` instead of webapck4's `mtimes` to get a list of changed files
