### ISSUE TITLE
Numbered chunks not loading correctly per config

### ISSUE THREAD

**Issue by evandegr** [webpack/webpack#1250]
So I have two different webpack configs I'm passing in an array that looks something like this:

```
[
    {
        entry: entrypointsIE,
        output: outputIE,
        module: {
            loaders: [
                  // set of loaders that has one difference to load SCSS variables from a different location
            ]
        },
        resolveLoader: resolveLoader,
        resolve: resolve,
        plugins: plugins,
        devServer: devServer
    },
    {
        entry: entrypoints,
        output: output,
        module: {
            loaders: [
                 // loaders all the same as the IE9 except one difference in sass loader    
            ]
        },
        resolveLoader: resolveLoader,
        resolve: resolve,
        plugins: plugins,
        devServer: devServer
    }
]
```

```
output = {
    path: '/web/dist',
    filename: '[name].bundle.js',
    chunkFilename: '[id].bundle.js'
};

outputIE = {
    path: '/web/dist',
    filename: '[name].ie.bundle.js',
    chunkFilename: '[id].ie.bundle.js'
};
```

and

```
apps.forEach(function(appName, index) {
    entrypoints[appName] = [ 'webpack/hot/dev-server', appName + '/app' ];
});

appsIE = apps;

appsIE.forEach(function(appName, index) {
    entrypointsIE[appName] = [ 'webpack/hot/dev-server', appName + '/app.ie' ];
});
```

The entrypoints are the exact same files (and this is where I think my problem is coming from). I have a conditional in my index.html which loads `framework.ie.js` if it detects IE, and `framework.js` if it does not. This works as expected. The problem is that it does not load the numbered chunks consistently. Sometimes I see `0.bundle.js` getting loaded, and sometimes I see `0.bundle.ie.js` getting loaded (regardless of whether `framework.ie.js` or `framework.js` got loaded).

Is there some way to make it consistently load the correct chunk or is there a way to just make sure that everything I need just gets loaded into the framework bundles without any chunks getting loaded by webpack?

**Comment by evandegr** [comment]
Any input here? Need help with this.

**Comment by sokra** [comment]
I don't know... Sounds pretty weird. If I should take a looks please prepare a minimal test repo.

**Comment by bebraw** [comment]
@evandegr Could you set up a minimal repository showcasing the issue?
