### ISSUE TITLE
Watch doesn't work correctly with links

### ISSUE THREAD

**Issue by TomSssM** [webpack/webpack#12503]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Webpack file watcher ignores changes in symlinked files if `resolve > symlinks` options is set to `false`.

**If the current behavior is a bug, please provide the steps to reproduce.**

I have created [a minimal reproducible repo](https://github.com/TomSssM/webpack-test) to test the issue:
- go to `./project`
- do `npm ci`
- then start local server by running `npm run server`
- start Webpack file watcher by running `npm run watch`
- change the file in `./package/Logger` (you could try changing the message getter for example, this way the changes are easy to see)

**What is the expected behavior?**

The changes made in `Logger` module should appear on the page (e.g. `Logger` should append a different message). Instead Webpack doesn't re-build the `Logger` module.

I found a similar issue [here](https://github.com/webpack/watchpack/issues/60).

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

__Node.js version__ 12.19.0

__Webpack version__ 5.10.3

**Comment by alexander-akait** [comment]
Can't reproduce, watch works as expected

**Comment by alexander-akait** [comment]
You need `webpack-dev-server` if you want to see changes on the page, please update `webpack-cli` to the latest version, install `webpack-dev-server` and use `webpack serve` command to run `webpack-dev-server`, `--watch` only watch files, it is not include client code for reloading and hot module replacement

**Comment by TomSssM** [comment]
`watch` doesn't re-build `../package/Logger.js` is it really expected behavior?

**Comment by alexander-akait** [comment]
It re-build files, look at console

**Comment by alexander-akait** [comment]
> The changes made in Logger module should appear on the page (e.g. Logger should append a different message).

No, changes will not be appeared, because nobody reload the page

**Comment by alexander-akait** [comment]
```
[webpack-cli] Compilation starting...
(node:2506126) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
[webpack-cli] Compilation finished
asset runtime.3257a4a1eff8ce2ecff1.js 6.69 KiB [emitted] [immutable] (name: runtime)
asset package.c441a94aec26a6bc73e0.js 1.5 KiB [emitted] [immutable] (name: package) (id hint: defaultVendors)
asset main.0f930fc8ca28029879b1.js 1.49 KiB [emitted] [immutable] (name: main)
asset index.html 357 bytes [emitted]
Entrypoint main 9.68 KiB = runtime.3257a4a1eff8ce2ecff1.js 6.69 KiB package.c441a94aec26a6bc73e0.js 1.5 KiB main.0f930fc8ca28029879b1.js 1.49 KiB
runtime modules 3.17 KiB 4 modules
cacheable modules 591 bytes
  ./src/index.js 315 bytes [built] [code generated]
  ./node_modules/package/Logger.js 276 bytes [built] [code generated]
webpack 5.10.3 compiled successfully in 91 ms
[webpack-cli] watching files for updates...
[webpack-cli] Compilation starting...
[webpack-cli] Compilation finished
assets by status 9.68 KiB [cached] 3 assets
Entrypoint main 9.68 KiB = runtime.3257a4a1eff8ce2ecff1.js 6.69 KiB package.c441a94aec26a6bc73e0.js 1.5 KiB main.0f930fc8ca28029879b1.js 1.49 KiB
cached modules 591 bytes (javascript) 3.17 KiB (runtime) [cached] 6 modules
webpack 5.10.3 compiled successfully in 16 ms
[webpack-cli] watching files for updates...
[webpack-cli] Compilation starting...
[webpack-cli] Compilation finished
assets by status 9.68 KiB [cached] 3 assets
Entrypoint main 9.68 KiB = runtime.3257a4a1eff8ce2ecff1.js 6.69 KiB package.c441a94aec26a6bc73e0.js 1.5 KiB main.0f930fc8ca28029879b1.js 1.49 KiB
cached modules 591 bytes (javascript) 3.17 KiB (runtime) [cached] 6 modules
webpack 5.10.3 compiled successfully in 11 ms
[webpack-cli] watching files for updates...
```

**Comment by TomSssM** [comment]
Changes are still missing after full page reload, bundle containing the code from `package` likewise doesn't update though Webpack writes logs

**Comment by alexander-akait** [comment]
Because you need dev server to reload page as I described above

**Comment by alexander-akait** [comment]
Oh, I see the problem

**Comment by TomSssM** [comment]
The problem that I am experiencing is that the `dist/package.[hash].js` does not include changes made in watch mode, it is only possible if i change `symlinks` to `true`

**Comment by TomSssM** [comment]
I wonder if it is a good idea to add something like `followSymlinks` to `watchOptions` so that the file watcher will resolve symlinks in watch mode

**Comment by alexander-akait** [comment]
Why you disable `symlinks`? It is unsafe in some cases

**Comment by alexander-akait** [comment]
`followSymlinks` already in `watchOptions`

**Comment by TomSssM** [comment]
I can't find it here https://webpack.js.org/configuration/watch/ Is it somewhere else?

**Comment by TomSssM** [comment]
Let's just say in the project I am working on it is necessary to disable symlinks =)

**Comment by alexander-akait** [comment]
https://github.com/webpack/webpack.js.org/issues/4483

**Comment by TomSssM** [comment]
I added it blindly to my config but everything got even worse:
```
/Users/ilyakortasov/Documents/sandbox/webpack-aliases/project/node_modules/watchpack/lib/LinkResolver.js:94
                                throw e;
                                ^

Error: ENOENT: no such file or directory, readlink '/Users/ilyakortasov/Documents/sandbox/webpack-aliases/project/Users'
    at Object.readlinkSync (fs.js:1035:3)
    at LinkResolver.resolve (/Users/ilyakortasov/Documents/sandbox/webpack-aliases/project/node_modules/watchpack/lib/LinkResolver.js:47:27)
    at LinkResolver.resolve (/Users/ilyakortasov/Documents/sandbox/webpack-aliases/project/node_modules/watchpack/lib/LinkResolver.js:36:31)
    at LinkResolver.resolve (/Users/ilyakortasov/Documents/sandbox/webpack-aliases/project/node_modules/watchpack/lib/LinkResolver.js:36:31)
    at LinkResolver.resolve (/Users/ilyakortasov/Documents/sandbox/webpack-aliases/project/node_modules/watchpack/lib/LinkResolver.js:36:31)
    at LinkResolver.resolve (/Users/ilyakortasov/Documents/sandbox/webpack-aliases/project/node_modules/watchpack/lib/LinkResolver.js:36:31)
    at LinkResolver.resolve (/Users/ilyakortasov/Documents/sandbox/webpack-aliases/project/node_modules/watchpack/lib/LinkResolver.js:36:31)
    at LinkResolver.resolve (/Users/ilyakortasov/Documents/sandbox/webpack-aliases/project/node_modules/watchpack/lib/LinkResolver.js:36:31)
    at LinkResolver.resolve (/Users/ilyakortasov/Documents/sandbox/webpack-aliases/project/node_modules/watchpack/lib/LinkResolver.js:36:31)
    at LinkResolver.resolve (/Users/ilyakortasov/Documents/sandbox/webpack-aliases/project/node_modules/watchpack/lib/LinkResolver.js:36:31) {
  errno: -2,
  syscall: 'readlink',
  code: 'ENOENT',
  path: '/Users/ilyakortasov/Documents/sandbox/webpack-aliases/project/Users'
}
```

**Comment by alexander-akait** [comment]
But you can't do it, you need resolve `symlinks`, because `./node_modules/package` is link

**Comment by TomSssM** [comment]
You see we use Webpack aliases in our project, these aliases need to work not only in the project directory but also in the symlinked package directories. If we resolve symlinks, then Webpack aliases don't work inside symlinked packages and everything crashes. Is there any other workaround?

**Comment by alexander-akait** [comment]
> You see we use Webpack aliases in our project

I don't see

> Webpack aliases don't work inside symlinked packages and everything crashes

Please clarify, aliases work everywhere 

> Is there any other workaround?

No workarounds, you disable symlinks, but wait they will work :confused:

**Comment by TomSssM** [comment]
The best way to explain is with code: go to the minimal reproducible repo and switch to `aliases` branch, then run `npm run watch`, Webpack will not be able to resolve `generated` because of `symlinks: true` option. If you set `symlinks` to `false`, then everything works.
__Note:__ I just updated my repo, make sure to pull it first

**Comment by alexander-akait** [comment]
Bug in cache, set `cache: false,` and all works fine

**Comment by alexander-akait** [comment]
Original issue - https://github.com/webpack/webpack/issues/12246
PR - https://github.com/webpack/webpack/issues/12246

**Comment by TomSssM** [comment]
Horray! Everything works now, thanks 🎉

**Comment by alexander-akait** [comment]
Some things were a little unclear, I thought you were expecting an automatic reload and want fully disable symlinks, let's close because duplicate

**Comment by TomSssM** [comment]
Oh I see now why you thought this way, gotta be clearer next time =)
