### ISSUE TITLE
Chunks in splitChunks.cacheGroups named by output.filename, not output.chunkFilename

### ISSUE THREAD

**Issue by marcusds** [webpack/webpack#12505]
# Bug report

I would expect that chunks generated by `SplitChunksPlugin` would be named by `output.chunkFilename`, not `output.filename` (which I would expect to be used for naming entries), however this is not the case.

**What is the current behavior?**

When using the config below, anything coming out of `splitchunks.cacheGroup.defaultVendors` is named `[name]-[hash?].js` and is placed in the same folder as the entry file is.

**If the current behavior is a bug, please provide the steps to reproduce.**

Use the following config:

``` 
output: {
    filename: '[name].js',
    path: __dirname, 
    publicPath: '/resources/',
    chunkFilename: '[chunkhash].chunk.js'
},
splitChunks: {
        chunks: 'async',
        minSize: 20000,
        minRemainingSize: 0,
        maxSize: 0,
        minChunks: 1,
        maxAsyncRequests: 30,
        maxInitialRequests: 30,
        enforceSizeThreshold: 50000,
        cacheGroups: {
            defaultVendors: {
                test: /[\\/]node_modules[\\/]/,
                priority: -10,
                reuseExistingChunk: true
            },
            default: {
                minChunks: 2,
                priority: -20,
                reuseExistingChunk: true
            }
        }
    }
```

**What is the expected behavior?**

The expected behaviour is that the chunks are named in accordance with `output.chunkFilename`. So in my example code: something like: `[chunkhash].chunk.js`

**Other relevant information:**
webpack version:  5.17.0
Node.js version: 12.19.0
Operating System: Windows 10
Additional tools:

**Comment by alexander-akait** [comment]
You can do using https://webpack.js.org/plugins/split-chunks-plugin/#splitchunkscachegroupscachegroupfilename, changing `output.filename` to `output.chunkFilename` will be big breaking change, we can't do it, also when you split something it create initial chunks (i.e. you need to `import`/`require`/`<script>` them in right order), the `chunkFilename` option used for async chunks
