### ISSUE TITLE
Webpack 4 - how to resolve different URLs

### ISSUE THREAD

**Issue by elisabetperez** [webpack/webpack#12512]
Hi,
I'm using Webpack 4 in my project and I'm having trouble with the URLs of my images. I have 2 images placed: 1 in my html, and 1 in my scss entry. Only one of the images is being rendered and I can't resolve the URL of the images coming from the CSS.

This is my /src  folder structure:

```
|   index.html
+--js
+--scss
| +----scss/entries
           |  index.scss
+---img
    |  imgA.png
    |  imgB.png
|  webpack.common.js
|  webpack.dev.js
|  webpack.prod.js
```

This is my rule for images in webpack.common.js
```
 {
                test: /\.(png|svg|gif|jpg)$/,
                use: [
                    {
                        loader: 'file-loader',
                        options: {
                            name: "[name].[hash].[ext]",
                            outputPath: "img", 
                            publicPath: './img/',
                        }
                    }
                ],
            },
```

This is part of my code in index.html
```
<div class="image-background"></div> //image from CSS
<img src="./img/shutter.png" alt="">
```

The .scss for the .image-background is this:
```
.image-background{
  background:url('./../../css-img/nat.png');
  min-height: 300px;;
}
```

And, finally, these are the pugins I'm using:
```
"devDependencies": {
    "@babel/cli": "^7.12.10",
    "@babel/core": "^7.12.10",
    "@babel/preset-env": "^7.12.11",
    "babel-loader": "^8.2.2",
    "clean-webpack-plugin": "^3.0.0",
    "css-loader": "^5.0.1",
    "file-loader": "^6.2.0",
    "html-loader": "^1.3.2",
    "html-webpack-plugin": "^4.5.1",
    "mini-css-extract-plugin": "^1.3.4",
    "node-sass": "^5.0.0",
    "postcss": "^8.2.4",
    "postcss-loader": "^4.1.0",
    "postcss-preset-env": "^6.7.0",
    "sass": "^1.32.5",
    "sass-loader": "^10.1.1",
    "style-loader": "^2.0.0",
    "url-loader": "^4.1.1",
    "vue-loader": "^15.9.6",
    "vue-style-loader": "^4.1.2",
    "vue-template-compiler": "^2.6.12",
    "webpack": "^4.45.0",
    "webpack-bundle-analyzer": "^4.4.0",
    "webpack-cli": "^4.4.0",
    "webpack-dev-server": "^3.11.2",
    "webpack-merge": "^5.7.3"
  },
  "dependencies": {
    "vue": "^2.6.12"
  }
```

Output for the image from index.html is correct, but output for the '.image-background' div is (./img/imgA.png) instead of (./../img/imgA.png);

My question is the following: what needs to be done to render and resolve the URL of the images coming from the .scss entries? What is the best approach when we have images coming from different folders and different structure depths? 
What if instead of entries I've got modules and components inside some other folders? How do I solve all the URLS?

Thanks in advance 🚀

**Comment by alexander-akait** [comment]
It is problem from `sass-loader` https://github.com/webpack-contrib/sass-loader#problems-with-url, Unfortunately `sass` doesn't give ability to rewrite `url()`

**Comment by alexander-akait** [comment]
webpack@5 has `resolver.roots` feature and you can use put `assets/images/image.png` and use `url('/assets/images/image.png')` and `<img src="/assets/images/image.png">`

**Comment by andresclua** [comment]
`alias: {
            'jsPath':path.resolve(__dirname,'src/js'),
            'imgPath':path.resolve(__dirname,'src/img')
        },
        `
        `.image-background{
  background:url('~imgPath/shutter.png');
  min-height: 300px;;
}`
        
        
        that should solve the problem.

**Comment by alexander-akait** [comment]
Answers above, feel free to feedback and please prefer to use discussions for questions
