### ISSUE TITLE
How to find out which own dependencies Webpack uses at runtime?

### ISSUE THREAD

**Issue by mike-lischke** [webpack/webpack#12517]
This is a pretty special question I have which [Stackoverflow](https://stackoverflow.com/questions/65920043/how-to-find-the-dependencies-of-the-webpack-runtime) is not able to answer.

What I need to know is what parts of Webpack are actually shipped in generated code and which 3rd party code it relies on. For legal approval I need to list all 3rd/4th party libraries that are shipped to customers.

I looked at the package.json file of the project, but to me it looks as if that contains many build/dev dependencies. I installed webpack@4.44.2 explicitly (this is the version used by current react-scripts) leaves me with a 600 lines long dependency tree. This cannot all be runtime dependencies. Much of that is certainly for build/dev time only, right?

So, how can I tell which dep is shipped?

**Comment by alexander-akait** [comment]
Using `stats` or https://github.com/webpack-contrib/webpack-bundle-analyzer (visual)

**Comment by alexander-akait** [comment]
Please prefer to use https://github.com/webpack/webpack/discussions for questions in future, you can use `npm-remote-ls` (you can write own tool and get logic from this), for yarn it can be different

**Comment by alexander-akait** [comment]
Feel free to feedback
