### ISSUE TITLE
Uncaught SyntaxError: Unexpected token '(' after minifying js file

### ISSUE THREAD

**Issue by khanakia** [webpack/webpack#12513]
# Bug report
**What is the current behavior?**
I am simply importing a library `import "bootstrap/dist/js/bootstrap.bundle.min.js"` and when i compile with webpack it works fine but when i **minify the js file** manually or using some wordpress plugin it gives the error `Uncaught SyntaxError: Unexpected token '(' after minifying js file`

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Clone the repo https://github.com/khanakia/webpack-semicolon-issue/
2. Run yarn and yarn install
3. Check this LINE 63 in https://github.com/khanakia/webpack-semicolon-issue/blob/0c6da3e15ed60e04225d0c4766810d00560ae92b/dist/app.js#L63
4. It did not added any **semicolon**

**What is the expected behavior?**
`__webpack_require__.x = x => {}` should be `__webpack_require__.x = x => {};` with semicolon

**Other relevant information:**
webpack version:  ^5.18.0
Node.js version:  15.0
Operating System: OXS
Additional tools: yarn

**Comment by alexander-akait** [comment]
Why do you duplicate the problem?

**Comment by khanakia** [comment]
Where did i duplicate ? i created only one issue and one community discussion.

**Comment by alexander-akait** [comment]
No need to do it, only one - issue or discussion, prefer to use discussion before issue
