### ISSUE TITLE
webpack cache -- immediate cache created

### ISSUE THREAD

**Issue by gita-v** [webpack/webpack#12520]
## Feature request

Webpack cache to force create a cache if cache state is empty and with no changes to the code base.

**What is the expected behavior?**

For webpack cache to save cache state on the initial build even with no changes to the code base.

**What is motivation or use case for adding/changing the behavior?**

This used to be the functionality in hard-source-webpack-plugin; and since webpack cache replaced hard-source-webpack-plugin I think this would be useful to have. If someone runs development webpack and does not make any changes, and then kills the process, and then re-ups webpack again it would be nice to have a warm cache from the initial state. 

**How should this be implemented in your opinion?**

I think if webpack cache sees that the cache directory is empty, it should create a cache based on the current build state.

**Are you willing to work on this yourself?**
yes -- with guidance on which files I should look at, I would love to work on it :)

**Comment by alexander-akait** [comment]
> For webpack cache to save cache state on the initial build even with no changes to the code base.

What do you mean? I did not understand at all what you expect

**Comment by gita-v** [comment]
Yes, I am referring to setting the cache to `filesystem`.
When I set the cache to `filesystem` during the initial run, none of the cache files are saved for the bundles until I edit one of the files, then it triggers a cache save. Maybe this is a bug then? I thought it was expected behavior.

**Comment by alexander-akait** [comment]
You can use https://webpack.js.org/configuration/other-options/#cacheidletimeout and https://webpack.js.org/configuration/other-options/#cacheidletimeoutforinitialstore

**Comment by gita-v** [comment]
Oh so sorry I missed that -- Thank you so much.
