### ISSUE TITLE
Webpack 5 persistent cache + EnvironmentPlugin: environment variables changing doesn't affect cache.

### ISSUE THREAD

**Issue by dangreen** [webpack/webpack#12528]
# Bug report

**What is the current behavior?**

Webpack 5 persistent cache + EnvironmentPlugin: environment variables changing doesn't affect cache.

**If the current behavior is a bug, please provide the steps to reproduce.**

- make webpack config with persistent cache and EnvironmentPlugin
- build code, for example, with env variable `TEST_VAR=1`, output code will contain value `1`
- next build with `TEST_VAR=2`, output code will still contain value `1`

**What is the expected behavior?**

Environment variable change will affect output code.

**Other relevant information:**
webpack version:  5
Node.js version: 12
Operating System:  macOS

**Comment by alexander-akait** [comment]
changing something in `webpack.config.js` should invalid cache, you if do right setup, please provide example how you use it

**Comment by dangreen** [comment]
@alexander-akait webpack.config.js doesn't changing, only values of environment variables which should passed to code.

**Comment by alexander-akait** [comment]
How you pass variables to `EnvironmentPlugin`

**Comment by dangreen** [comment]
@alexander-akait yes, only names with default values

**Comment by alexander-akait** [comment]
We can't invalidate cache based on `process.env`, your cache will then become useless, in this case you need to use https://webpack.js.org/configuration/other-options/#cacheversion - `version: JSON.stringify(envVariables)`

**Comment by dangreen** [comment]
@alexander-akait so that will invalidate whole cache, it's sad....

**Comment by alexander-akait** [comment]
Maybe you want this https://github.com/webpack/webpack/issues/10249?

**Comment by alexander-akait** [comment]
`EnvironmentPlugin` uses `DefinePlugin` under the hood https://github.com/webpack/webpack/blob/master/lib/EnvironmentPlugin.js#L59

**Comment by dangreen** [comment]
@alexander-akait 

so if i have

```
new webpack.EnvironmentPlugin({
  NODE_ENV: 'development',
  TENANT: null,
})
```

i should replace it with

```
new webpack.DefinePlugin({
  'process.env.NODE_ENV': JSON.stringify('development'),
  'process.env.TENANT': webpack.DefinePlugin.runtimeValue(() => process.env.TENANT),
})
```

or what?

**Comment by alexander-akait** [comment]
No, you can still use `EnvironmentPlugin`, in the provided issue, changing something in options should invalidate modules where values used

**Comment by dangreen** [comment]
@alexander-akait Sorry, doesn't see what you talking about. Can you please provide example?

**Comment by alexander-akait** [comment]
When value (for example `process.env.TENANT`) changed, we should invalidate only modules where you use `process.env.TENANT`, not whole cache when you using `cache.version`, so we should track previously value of `process.env.TENANT` as described here https://github.com/webpack/webpack/issues/10249, I don't know how even easier to explain it

**Comment by dangreen** [comment]
> so we should track previously value of

how we should track it?

**Comment by alexander-akait** [comment]
It is not implemented yet, so https://github.com/webpack/webpack/issues/10249 has `bug` and `enhancement`, because for some developers it is bug, but in fact it is just limitation right now, but we can improve this

**Comment by dangreen** [comment]
@alexander-akait I thought I can turn it on somehow right now 🙂

Ok, thanks. Will wait this enhancement.

**Comment by alexander-akait** [comment]
Let's close in favor https://github.com/webpack/webpack/issues/10249 because duplicate, right now only one solution - `cache.version`
