### ISSUE TITLE
JavascriptParser expose comment options

### ISSUE THREAD

**Issue by xiaoxiaojx** [webpack/webpack#12526]
## Feature request
lib/javascript/JavascriptParser.js
Add commentOptions hook

**What is the expected behavior?**
commentOptions: new SyncWaterfallHook(["options", "expression"])

**What is motivation or use case for adding/changing the behavior?**
We have a cli tool that wants to automatically ignore all dynamic imports during SSR compilation, so we want to have hooks that expose commentOptions

**How should this be implemented in your opinion?**
This is a version of my implementation also added test cases, I hope to be adopted
https://github.com/webpack/webpack/commit/77fece3a01b2f78bd4052017af3cae7ae7ea3578

**Are you willing to work on this yourself?**
yes

**Comment by xiaoxiaojx** [comment]
🤔 Is this change necessary ？ now my temporary solution is to copy most of the code of ImportParserPlugin to write a plugin, and then force the dynamic import to return to the ImportEagerDependency

**Comment by alexander-akait** [comment]
Do you want this https://github.com/webpack/webpack/issues/5029?

**Comment by xiaoxiaojx** [comment]
I think it's a very similar requirement, and if can expose comentOptions, it will all be easy to implement this requirement. And comentOptions would allow developers to do more than just modify the webpackMode.

**Comment by alexander-akait** [comment]
bump

**Comment by vankop** [comment]
you can use hook like `finish` ( second argument are comments ). btw there is method `parser.getComments(range)` that will return you array of comments in some range.
