### ISSUE TITLE
Runtime performance gets 3 times worse when I use Webpack 5

### ISSUE THREAD

**Issue by ingun37** [webpack/webpack#12521]
# Bug report

**What is the current behavior?**

I make Web app that renders some 3D models using WebGL.
It used to take about 50s to load some test models, but after I updated Webpack to 5, it has been taking about 160s which is more than 3x.

**If the current behavior is a bug, please provide the steps to reproduce.**

I'm sorry that I can't provide sample app. It's too complicated to concentrate the problem.
But I'm certain that Webpack 5 is the problem because the only difference between the two different measurement was whether the version of Webpack was 5.15.0 or 4.44.2.

**What is the expected behavior?**

I expected Webpack, being just a bundler, not to affect runtime performance.

**Other relevant information:**
webpack version:  5.15.0
Node.js version: 12
Operating System: MacOS, Ubuntu 20
Additional tools:

Are there any known issuses about the runtime performance like mine that I can see?

**Comment by alexander-akait** [comment]
> I'm sorry that I can't provide sample app. It's too complicated to concentrate the problem.

I am sorry, we can't help, you don't provide anything to track the problem - no screenshots, no videos, no examples, no performance from dev tools. Won't fix.

Anyway if you provide more information we will reopen issue. Sorry.

No issues about performance runtime so I assume that you missed something during the update. 

Anyway again, we can continue discussion here.
