### ISSUE TITLE
Follow naming convention

### ISSUE THREAD

**Issue by cntgfy90** [webpack/webpack#12536]
## Feature request

**What is the expected behavior?**
This proposed change concerns only the naming convention and its standardization.
https://github.com/webpack/webpack/blob/master/lib/util/memoize.js#L24
It is proposed to shorten the comment and make it more clear

**What is motivation or use case for adding/changing the behavior?**
Follow standardized naming conventions

**How should this be implemented in your opinion?**
Something like `avoid loitering` would suffice

**Are you willing to work on this yourself?**
yes

**Comment by alexander-akait** [comment]
No need issues for this, if you want change comment on something other just send a PR, no bugs/features here, thanks
