### ISSUE TITLE
dependOn with dynamically loaded modules still creates separate chunks

### ISSUE THREAD

**Issue by thomasledoux1** [webpack/webpack#12530]
# Bug report

**What is the current behavior?**
Currently, I have a separate entry point for jquery defined.
I have another entry point (e.g. ModuleA with a dependOn pointing to the jquery entry point.

jquery entrypoint: 
```jquery: 'jquery'``` 

ModuleA entrypoint:
```
ModuleA: {
      import: path.resolve(
        './../../../Features/Retail/code/assets/js/apps/cartOverview.js'
      ),
      dependOn: 'jquery',
    },
```
In ModuleA, I load jQuery dynamically:
```
init: async () => {
      if (document.querySelector('.zoomProduct')) {
        const $ = await import('jquery');
      }
}
```
Because of this, jquery is not in the chunk, but it will be dynamically loaded when needed from a separate chunk which is generated. 
I would think this separate chunk should not be created anymore, and should instead be coming from the jquery chunk I created.

**If the current behavior is a bug, please provide the steps to reproduce.**
See code above

**What is the expected behavior?**
I expected the dynamic loading of the module to point to the separate jquery chunk I created.

**Other relevant information:**
webpack version:  5.16.0
Node.js version: 10.15.3
Operating System: Windows 10
Additional tools:

**Comment by alexander-akait** [comment]
In this case you should not use `dependOn` 

> If the current behavior is a bug, please provide the steps to reproduce.
> See code above

This does not quite help to understand what you want to get, especially without an example code, at least minimal

**Comment by thomasledoux1** [comment]
Hi @alexander-akait thanks for the fast reply.
If I shouldn't use dependOn in this case, what should I do instead?
Not create a separate chunk for the jquery dependency and just let webpack dynamically load it (from a different chunk every time)? The code I'm working on is under NDA so I can't share it here..

**Comment by alexander-akait** [comment]
@thomasledoux1 you can use `externals`, you don't need provide full core, just provide small example, I need to understand what do you want achieve
