### ISSUE TITLE
LimitChunkCountPlugin - ERROR in chunk runtime [entry] Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by AllanOricil** [webpack/webpack#12535]
# Bug report

**What is the current behavior?**
I need to set the max chunck to only 1 and I can't currently do that. This error has been reported before but nothing was done.

**If the current behavior is a bug, please provide the steps to reproduce.**

1 - Create a Nuxt App using `npx create-nuxt-app <project-name>` (Choose bootstrap, axios and eslint when asked)
2 - Change your "nuxt.config.js" to match the one below. 
3 - `npm run build`
4 - Verify that is a Webpack Bug

![image](https://user-images.githubusercontent.com/55927613/106352939-cdcda400-62de-11eb-808d-d0eda77abe6f.png)

5 - Change `maxCount:4`
6 - `npm run build`
7 - Verify that it now worked

![image](https://user-images.githubusercontent.com/55927613/106353072-d4a8e680-62df-11eb-865b-f394e04b9142.png)

obs: The file is located in the root of the project. 
nuxt.config.js
````js
import webpack from 'webpack';

export default {
  // Target: https://go.nuxtjs.dev/config-target
  target: 'static',
  ssr: false,

  // Global page headers: https://go.nuxtjs.dev/config-head
  head: {
    title: 'salesforce-query-editor',
    htmlAttrs: {
      lang: 'en',
    },
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: '' },
    ],
    link: [],
    script: [],
  },

  // Global CSS: https://go.nuxtjs.dev/config-css
  css: [],

  // Plugins to run before rendering page: https://go.nuxtjs.dev/config-plugins
  plugins: [],

  // Auto import components: https://go.nuxtjs.dev/config-components
  components: true,

  // Modules for dev and build (recommended): https://go.nuxtjs.dev/config-modules
  buildModules: [
    // https://go.nuxtjs.dev/eslint
    ['@nuxtjs/eslint-module', { fix: true, quiet: true }],
  ],

  // Modules: https://go.nuxtjs.dev/config-modules
  modules: [
    'bootstrap-vue/nuxt',
    '@nuxtjs/axios',
  ],

  // Axios module configuration: https://go.nuxtjs.dev/config-axios
  axios: {},

  // Build Configuration: https://go.nuxtjs.dev/config-build
  build: {
    extend(config, ctx) {
      if (ctx.isDev) {
        config.devtool = ctx.isClient ? 'source-map' : 'inline-source-map';
      }
    },

    plugins: [
      new webpack.optimize.LimitChunkCountPlugin({
        maxChunks: 1
      })
    ],
  },

  router: {
    mode: 'hash',
  },
}

````

**What is the expected behavior?**
It should output one js file as I specified maxChunk = 1 on the LimitChunkCountPlugin

**Other relevant information:**
webpack version:  4
Node.js version: v12.13.0
Operating System:  Windows
Additional tools:

**Comment by alexander-akait** [comment]
Duplicate https://github.com/webpack/webpack/issues/9964, sorry, no fixes for webpack@4, because it can create regressions, please consider to update webpack@5

**Comment by AllanOricil** [comment]
I fixed my issue. For those who have this problem, just change the chunck name like shown below:

````js
config.output.filename = 'app.js',
config.output.chunkFilename = '[id].js';
config.optimization.splitChunks.cacheGroups.default = false;
config.optimization.runtimeChunk = false;


plugins: [
  new webpack.optimize.LimitChunkCountPlugin({
    maxChunks: 1
  })
],
````

The problem is caused because of the `[contenthash:7].js`. For some reason it does not work when using the `maxChuncks:1`. So just change to be like in the example above and it should work :)

````js

output: {
    filename: '[contenthash:7].js',
    chunkFilename: '[contenthash:7].js',
},
````

**Comment by alexander-akait** [comment]
@AllanOricil Can you provide simple reproducible test repo, I want to add this to tests to ensure we will not break it again

**Comment by AllanOricil** [comment]
> @AllanOricil Can you provide simple reproducible test repo, I want to add this to tests to ensure we will not break it again

@alexander-akait  Follow these steps to have a project that you can base your tests on

1 - `npx create-nuxt-app ANY_NAME`
2 - Inside the project root folder there is a file called `nuxt.config.js`. Nuxt uses Webpack 4 to pack the app, and it comes with pre configure Webpack. And it is in this file  that any webpack config can be overwritten. On the `build` section of the `nuxt.config.js` is the place where we can do our changes to webpack. So change your `build` section to match this one below and don't do anything else

````js
build: {
    extend(config, ctx) {
      if (ctx.isDev) {
        config.devtool = ctx.isClient ? 'source-map' : 'inline-source-map';
      }
    },

    plugins: [
      new webpack.optimize.LimitChunkCountPlugin({
        maxChunks: 1
      })
    ],
  },
````
3 - run `npm run build` and check the error from this issue
4 - Now change your build again to match the following:

````js
build: {
    extend(config, ctx) {
      if (ctx.isDev) {
        config.devtool = ctx.isClient ? 'source-map' : 'inline-source-map';
      }

      if (ctx.isClient) {
        config.output.filename = 'app.js',
        config.output.chunkFilename = '[id].js';
        config.optimization.splitChunks.cacheGroups.default = false;
        config.optimization.runtimeChunk = false;
      }
    },

    plugins: [
      new webpack.optimize.LimitChunkCountPlugin({
        maxChunks: 1
      })
    ],
  },
````
5 - Verify it does not throw any error

**Comment by ben8p** [comment]
> ```js
> config.output.chunkFilename = '[id].js';
> ```

you saved my day!
Thanks

**Comment by samslater** [comment]
@alexander-akait OMG thank you so much!!  Was banging my head on this all day and this was it!
```
config.output.chunkFilename = '[id].js';
```
