### ISSUE TITLE
Loaders used with the inline syntax can't fully override module types

### ISSUE THREAD

**Issue by Lyrkan** [webpack/webpack#12531]
# Bug report

**What is the current behavior?**

Hi,

Let's say that I create a webpack config with a rule that handles all `.txt` files using the `asset/resource` type:

```js
{
  test: /\.txt$/i,
  type: 'asset/resource'
}
```

I then wish to create a loader that will be **used with the inline notation** to handle some other `.txt` files, but using the `javascript/auto` type.

Since (unless I'm missing something) that type can't be set directly in the inline syntax, I use the following snippet in the loader (which is something that works to override the default behavior with `.json` files):

```js
const requiredType = 'javascript/auto';
if (this._module.type !== requiredType) {
    const factory = this._compilation.dependencyFactories.get(LoaderDependency);
    this._module.type = requiredType;
    this._module.generator = factory.getGenerator(requiredType);
    this._module.parser = factory.getParser(requiredType);
}
```

And import the `.txt` file in my JS modules using the following syntax:

```js
import '!!./loader.js!./foo.txt';
```

The compilation then fails with the following message:

```
str must be a string, but is a object: module.exports = "";
```

If I remove the rule from the `webpack.config.js` file that error disappears.

**If the current behavior is a bug, please provide the steps to reproduce.**

Here is a gist  with a minimal repro: https://gist.github.com/Lyrkan/bdff6c43ed3edbed3f9a166e0b68799c

**What is the expected behavior?**

The module type declared in the rule should be ignored for that import and the compilation should be successful.

**Other relevant information:**
webpack version: 5.18.0
Node.js version: 14.15.1
Operating System: Linux
Additional tools: None

**Comment by alexander-akait** [comment]
You should **never change** `this._module.type` and better nothing from `_`. Please prefer to use discussion for questions. You can use this syntax to achieve this https://github.com/webpack/webpack/issues/11074#issuecomment-648658214

**Comment by alexander-akait** [comment]
Also I recommend to use `asset/source` and for inline + additional loader if you need something non standard

**Comment by Lyrkan** [comment]
Hi @alexander-akait, thanks for the answer.

> You should never change this._module.type and better nothing from _.

I am aware of that but as I said it seems to be the only way to change the type from the loader itself... which doesn't seem right since a loader is probably able to tell what kind of data it's going to return.

> Please prefer to use discussion for questions.

Yeah sorry about that, I was a bit hesitant about opening that one but it really feels like a bug, or at least a missing feature.

> You can use this syntax to achieve this #11074 (comment)

I fail to see how it applies to the example I gave above... could you expand a little bit?

Note that the use case behind that issue is also a bit more complex and involves being able to handle any type of file no matter what rules are set in the config and that those files are not known in advance (imported through `require.context(...)` calls coming from user input).

**Comment by alexander-akait** [comment]
`!=!` syntax avoid using `type`, so you can working with any file as any type, I can't say how to solve it in right way, but if you right more examples or example of loader or example what you have and what you need I will help you

**Comment by Lyrkan** [comment]
> but if you right more examples or example of loader or example what you have and what you need I will help you

What I have is basically the loader I put in my first example with some additonal code that processes the imported file (what it does is not really important there I think).

It is called using `require.context()` to go over all files from a given folder (and eventually) subfolders, something along the lines of:

```js
const context = require.context(
	'!!my-loader!./my-directory',
	true,
	/.*/
);

context.keys().forEach(context);
```

I can't control which kind of files are processed since this is generated by a tool that can be configured by end-users, and it can collide with some default rules that have the `asset/resource` type (such as the one from my first example), hence the `!!` prefix.

In previous versions of Webpack (< 4) I didn't use the `this._module.type` hack, but it was required after the introduction of the native `.json` files handling (since it would be triggered and break that loader).

I thought about excluding files from the default rule using a resource query (that I'd add on files processed by that loader) but it seems that it is not possible to entirely negate `resourceQuery`.

**Comment by rb-mwindh** [comment]
Thank you for the quick reply :)

I've just tested it and I get the following error:
```
ModuleNotFoundError: Module not found: Error: Can't resolve '=' in 'C:\workspaces\igpm\central_fe\.storybook'
   --- cut stacktrace ---

resolve '=' in 'C:\workspaces\igpm\central_fe\.storybook'
  Parsed request is a module
  using description file: C:\workspaces\igpm\central_fe\package.json (relative path: ./.storybook)
    resolve as module
      C:\workspaces\igpm\central_fe\.storybook\node_modules doesn't exist or is not a directory
      looking for modules in C:\workspaces\igpm\central_fe\node_modules
        single file module
          using description file: C:\workspaces\igpm\central_fe\package.json (relative path: ./node_modules/=)
            no extension
              C:\workspaces\igpm\central_fe\node_modules\= doesn't exist
            .js
              C:\workspaces\igpm\central_fe\node_modules\=.js doesn't exist
        C:\workspaces\igpm\central_fe\node_modules\= doesn't exist
      C:\workspaces\igpm\node_modules doesn't exist or is not a directory
      looking for modules in C:\workspaces\node_modules
        single file module
          using description file: C:\workspaces\package.json (relative path: ./node_modules/=)
            no extension
              C:\workspaces\node_modules\= doesn't exist
            .js
              C:\workspaces\node_modules\=.js doesn't exist
        C:\workspaces\node_modules\= doesn't exist
      C:\node_modules doesn't exist or is not a directory
      looking for modules in C:\workspaces\igpm\central_fe\node_modules\@angular-devkit\build-angular\node_modules
        single file module
          using description file: C:\workspaces\igpm\central_fe\node_modules\@angular-devkit\build-angular\package.json (relative path: ./node_modules/=)
            no extension
              C:\workspaces\igpm\central_fe\node_modules\@angular-devkit\build-angular\node_modules\= doesn't exist
            .js
              C:\workspaces\igpm\central_fe\node_modules\@angular-devkit\build-angular\node_modules\=.js doesn't exist
        C:\workspaces\igpm\central_fe\node_modules\@angular-devkit\build-angular\node_modules\= doesn't exist
      looking for modules in C:\workspaces\igpm\central_fe\node_modules
        single file module
          using description file: C:\workspaces\igpm\central_fe\package.json (relative path: ./node_modules/=)
            no extension
              C:\workspaces\igpm\central_fe\node_modules\= doesn't exist
            .js
              C:\workspaces\igpm\central_fe\node_modules\=.js doesn't exist
        C:\workspaces\igpm\central_fe\node_modules\= doesn't exist
      looking for modules in C:\workspaces\node_modules
        single file module
          using description file: C:\workspaces\package.json (relative path: ./node_modules/=)
            no extension
              C:\workspaces\node_modules\= doesn't exist
            .js
              C:\workspaces\node_modules\=.js doesn't exist
        C:\workspaces\node_modules\= doesn't exist
```

I'm using the following versions:
```
Webpack@5.50.0
Angular@12.2.10
Storybook@6.3.12
css-loader@5.2.7
style-loader@2.0.0
```

**Comment by rb-mwindh** [comment]
More or less... The whole issue seems to be somehow related to the webpack config generated by Angular12.
This problems has kept me busy for 8 days now 😭 

I already posted a question on stackoverflow (it's my first, ever! 😆 )
You can find it here: https://stackoverflow.com/questions/69614700/import-css-file-into-es6-returns-string-instead-of-object

I was able to reproduce the issue with a blank Angular12 app and the mentioned import statement.
I've pushed the workspace to https://github.com/rb-mwindh/angular12-webpack5-inline-loader-repro

However, I don't know how to access the webpack config generated by angular. In older releases you could 'eject' it, but nowadays this seems to be more complex...

The import statement is located at `src/app.component.ts`
You can reproduce the issue by running `npm i && npm run start` and navigating to http://localhost:4200
The browser console will show the sourcecode generated by css-loader (or style-loader, doesn't matter) as a plain string.

**Comment by rb-mwindh** [comment]
Thanks for spending so much time on my issue 😄 

I know about the lazyStyleTag syntax, I learned about it from the @etchteam/storybook-addon-css-theme-variables plugin 😆 
Actually I just wanted to use that plugin to switch between the themes from my library in storybook...

I also don't know how to set up such an exclusion as I don't know how to change the angular-generated webpack config...

8 days ago Webpack was just some tool that was used "under the hood" by Angular. I didn't even know what it's used for 🤣  Now I know (a little) about modules, loaders, inline syntax...

**Comment by alexander-akait** [comment]
I think you can ask angular team team, I think it is possible

**Comment by liorwohl** [comment]
I also came across a very similar problem while trying to build a webcomponent under two angular apps, one with angular 14 and the other with angular 13. I just need to load CSS files as string in the webcomponent so I'm using raw-loader.
For the angular 13 it was enough to do: 
import themeLight from '../themes/light.css';
But for the angular 14 I had to do
import themeLight from '!!raw-loader!../themes/light.css';
but this didnt work in the angular 13 app..
so eventually using this issue and some modification, this works for both angular 13 and 14:
import themeLight from '[javascript/auto]!=!!!raw-loader!../themes/light.css';
