### ISSUE TITLE
splitchunks with multiple entry points is broken in v5.12.0+

### ISSUE THREAD

**Issue by rmuchall** [webpack/webpack#12533]
# Bug report

**What is the current behavior?**
When using the splitchunks.cacheGroups option with multiple entry points one of the vendor bundle files is not created.
This only occurs in Webpack v5.12.0 and later. Webpack v5.11.1 and earlier works correctly.

**If the current behavior is a bug, please provide the steps to reproduce.**
This issue is reproducible using my open source Chrome extension project located here:
https://github.com/peardropsoftware/torrent2box

Instructions to reproduce:
1) Clone repo, npm install
2) **Install a Webpack version that is v5.12.0 or above**
3) Run the npm script "build" which calls Webpack
4) A build directory is created with the webpacked assets
5) The 3 entry points should be created each with their corresponding vendor bundles but the content-vendor.js bundle is missing.
```
background.js
background-vendor.js
content.js
content-vendor.js // THIS FILE IS NOT CREATED - IT IS MISSING
options.js
options-vendor.js
```

**What is the expected behavior?**
All files listed above should be created.

**Other relevant information:**
webpack version:  Works in v5.11.1 - is broken in v5.12.0 - 5.19.0
Node.js version:  v14.15.3
Operating System:  Windows 10
Additional tools: N/A

Here is the relevant splitChunks configuration:
```
    optimization: {
        minimize: false,
        splitChunks: {
            cacheGroups: {
                backgroundVendor: {
                    test: /[\\/]node_modules[\\/]/,
                    name: "background-vendor",
                    chunks: (chunk) => {
                        return chunk.name === "background";
                    }
                },
                contentVendor: {
                    test: /[\\/]node_modules[\\/]/,
                    name: "content-vendor",
                    chunks: (chunk) => {
                        return chunk.name === "content";
                    }
                },
                optionsVendor: {
                    test: /[\\/]node_modules[\\/]/,
                    name: "options-vendor",
                    chunks: (chunk) => {
                        return chunk.name === "options";
                    }
                }
            }
        }
    },
```

**Comment by alexander-akait** [comment]
hm, regression after `experiments.layers`

**Comment by sokra** [comment]
It will only create a vendors-content chunk if the vendors in the content chunk are > 20kb. Is this the case?

**Comment by alexander-akait** [comment]
@sokra hm, before 5.12.0 it created, but now no

**Comment by rmuchall** [comment]
> It will only create a vendors-content chunk if the vendors in the content chunk are > 20kb. Is this the case?

Thanks for the suggestion :)
I thought of that too during my testing but size on disk is 32k. I assume this is the size the limit is checking against?

![size-on-disk](https://user-images.githubusercontent.com/9222511/106360431-49941480-6310-11eb-8114-942d1eb3b0ea.png)

**Comment by rmuchall** [comment]
I just set minsize to 5000 and this has fixed my issue. Minsize was indeed the problem.
My apologies, I should have double checked this before posting the issue.
Many thanks for all your hard work :)

```
optimization: {
        minimize: false,
        splitChunks: {
            minSize: 5000,
... etc
```

**Comment by sokra** [comment]
The problem was not that `content-vendors` would be too small. The problem was that `content` would be too small when the vendors are splitted into a separate chunk.

If you really want to make sure that a cacheGroup is created add `enforce: true`. This disables the thresholds.

You can also configure the size that need to remain separately from the `minSize` via `minRemainingSize`. By default it uses `minSize` for both.

**Comment by rmuchall** [comment]
Understood. Many thanks for the clarification. I will modify my webpack config accordingly.
