### ISSUE TITLE
Error: ES Modules may not assign module.exports or exports.*, Use ESM export syntax, instead: 581

### ISSUE THREAD

**Issue by takhello** [webpack/webpack#12549]
# Bug report
Error: ES Modules may not assign module.exports or exports.*, Use ESM export syntax, instead: 581

**What is the current behavior?**
Error: ES Modules may not assign module.exports or exports.*, Use ESM export syntax, instead: 581

**What is the expected behavior?**
There is no abnormal

**Other relevant information:**
webpack version:  "webpack": "^5.13.0",
Node.js version: v10.15.3
Operating System: mac
Additional tools:vscode

**Comment by sokra** [comment]
You need to fix the code of module 581.
`module.exports` must not be assigned within an ESM.
Try development mode for the readable module name.
Sometimes this is also caused by incorrect Babel config, which inserts imports which converts the module to an ESM.

**Comment by alexander-akait** [comment]
Answer above, feel free to feedback

**Comment by WhereJuly** [comment]
@sokra @alexander-akait 

Hello colleagues, 

for me this happens on a CommonJS module only when I use `typeof` operator in the prototype method.

E.g. 

``` javascript
ItemQuantityController.prototype.isTypeOrNullable = function(type, value) {
    // return true;
    return typeof value === type || value === null;
};
```

This may have something to do with Babel but I was not successful googling any clue to this with regard to Babel.

**Comment by alexander-akait** [comment]
@WhereJuly Please create reproducible test repo, I will open an issue if it will be bug

**Comment by sokra** [comment]
See https://babeljs.io/docs/en/options#sourcetype
unambiguous

**Comment by WhereJuly** [comment]
@alexander-akait Yes, thanks. I will in several days.
@sokra Thanks for the hint. Will investigate this.

**Comment by scil** [comment]
I had same issure but `"sourceType": "unambiguous",` not work. 

Because I tentatively edited a node-style module, i copied a line with es-style require:
```
import { app } from "electron";  // the ruin

var fs = require('fs')
var path = require('path')
var os = require('os')

```

**Comment by ef4** [comment]
> This may have something to do with how Babel transforms `typeof` but I was not successful googling any clue to the culprit so I just keep the solution here.

Yeah, this can happen if you're using [babel-plugin-transform-runtime](https://babeljs.io/docs/en/babel-plugin-transform-runtime) along with babel's [`sourceType: 'module'`](https://babeljs.io/docs/en/options#sourcetype).

babel-plugin-transform runtime is inserting an import statement into the file, which causes webpack to treat the file as an ES module, which causes it to be an error to try to assign to `module.exports`.

**Comment by flyskywhy** [comment]
None of webpack config change above can fix it, only source code change can [fix: react-native-web with react-app-rewired and react-scripts@5 and webpack@5 cause `Uncaught Error: ES Modules may not assign module.exports or exports.*, Use ESM export syntax, instead: ./node_modules/@flyskywhy/react-native-gcanvas/index.js`](https://github.com/flyskywhy/react-native-gcanvas/commit/077dd6f321a1224d4ad7e07038258b0730bfb682), ref to https://github.com/webpack/webpack/issues/4039#issuecomment-419284940
