### ISSUE TITLE
Incorrect output.path leads to compiler not finishing

### ISSUE THREAD

**Issue by leoselig** [webpack/webpack#1254]
I could not really figure out how this happens but it bugged me for days

I accidentally set the output.path to a string "./C:\some\path" which is obviously wrong
Unfortunately, the compiler instance did not finish (neither calling the callback function nor exiting nor crashing).

This should really be reported as an error by the compiler

**Comment by andreicek** [comment]
@TheLarkInn I'd like to tackle this one! :shipit:

**Comment by TheLarkInn** [comment]
Output now should validate via schema.
