### ISSUE TITLE
Attempted import error: 'LowPriority' is not exported from 'scheduler' (imported as 'LowPriority')

### ISSUE THREAD

**Issue by sunnyn0891** [webpack/webpack#12543]
# Bug report

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

**Comment by sunnyn0891** [comment]
# Bug report






**
Trying to upgrade from webpack v4 to v5.
getting attempted import error: 'LowPriority' is not exported from 'scheduler' (imported as 'LowPriority') error and build fails**







**Expected behaviour is successful update**





**Other relevant information:**
webpack version:  v5
Node.js version: v12.12.0
Operating System: Mac 
Additional tools:

**Comment by regy42** [comment]
This seems to be caused by https://github.com/formium/formik/pull/2438. Try update your Formik dependency. I upgraded from 2.1.4 to 2.2.6 and it works now.
