### ISSUE TITLE
export 'default' (imported as 'styles') was not found in '../styles.less'

### ISSUE THREAD

**Issue by NexxLuo** [webpack/webpack#12558]
# Bug report
Get a warning when i use `import styles from "./styles.less"` .
The warning message like this  `export 'default' (imported as 'styles') was not found in '../styles.less'`

```javascript
{
      test: /\.(less)(\?.*)?$/,
      oneOf: [
        /* config.module.rule('less').oneOf('css') */
        {
          use: [
            /* config.module.rule('less').oneOf('css').use('extract-css-loader') */
            {
              loader: require.resolve("mini-css-extract-plugin/dist/loader"),
              options: {
                esModule: true,
                modules: {
                  namedExport: true
                },
                publicPath: "./"
              }
            },
            /* config.module.rule('less').oneOf('css').use('css-loader') */
            {
              loader: require.resolve("css-loader"),
              options: {
                esModule: true,
                modules: {
                  namedExport: true,
                  localIdentName: "[local]___[hash:base64:5]"
                },
                importLoaders: 1
              }
            },
            /* config.module.rule('less').oneOf('css').use('postcss-loader') */
            {
              loader: require.resolve("postcss-loader"),
              options: {
                postcssOptions: {
                  ident: "postcss",
                  plugins: [["postcss-preset-env", { stage: 3, autoprefixer: true }]]
                }
              }
          },
            /* config.module.rule('less').oneOf('css').use('less-loader') */
            {
              loader: require.resolve("less-loader"),
              options: {
                lessOptions: {
                  modules: true,
                  modifyVars: undefined,
                  javascriptEnabled: true
                }
              }
            }
          ]
        }
      ]
    }
```

![QQ图片20210202161849](https://user-images.githubusercontent.com/18549980/106571854-a3941480-6572-11eb-8752-06230eb53596.png)

![QQ图片20210202161900](https://user-images.githubusercontent.com/18549980/106571857-a42cab00-6572-11eb-8547-f7d45c5a45ea.png)
 
**Other relevant information:**
webpack version:  5.18.0
Node.js version: 12.19.0
Operating System:  windows 10
Additional tools: visual studio code

**Comment by alexander-akait** [comment]
Not related to webpack, please read `mini-css-extract-plugin` CHANGELOG, `mini-css-extract-plugin` returns nothing (only named locals if you use CSS modules), so export doesn't exists, please use `import * as locals from './style.css'; console.log(locals.myClass)`

**Comment by NexxLuo** [comment]
> Not related to webpack, please read `mini-css-extract-plugin` CHANGELOG, `mini-css-extract-plugin` returns nothing (only named locals if you use CSS modules), so export doesn't exists, please use `import * as locals from './style.css'; console.log(locals.myClass)`

Thanks . I just set the `esModule` to false also hidden this error.

**Comment by efojs** [comment]
Thanks to the @NexxLuo's hint, solved same error,:  
> I just set the esModule to false also hidden this error  

But I wanted to name styles by template `foo__[name]__[local]`
And (rtfm) turned out it has nothing to do with `mini-css-extract-plugin` and named exports.  
It is a `css-loader` feature — [localidentname](https://github.com/webpack-contrib/css-loader#localidentname)  

So if you don't need named exports, don't use it:
```javascript
// just add
{
    loader: 'css-loader',
    options: {
        modules: {
            localIdentName: "[path][name]__[local]--[hash:base64:5]",
        },
    },
},

// and use
import styles from './app.css';

let element = `
    <div class="${styles.element}">
    ...
`
```

**Comment by leonpatry** [comment]
what about support for both? named and default exports?
