### ISSUE TITLE
No source maps in production mode

### ISSUE THREAD

**Issue by blarsern** [webpack/webpack#12563]
# Bug report

**What is the current behavior?**
Unable to create sourcemaps in production mode.

**If the current behavior is a bug, please provide the steps to reproduce.**
So we have 3 environments:
development  (dev build with source maps)
staging           (prod build with source maps)
production     (prod build without source maps)

This was working fine with webpack 4.41.0, but something changed after 4.42.0 -> 4.46.0.

It kinda works, it generates source map for stuff in the node_modules, but not our src folder.
webpack --progress --env.staging --mode production --env.extractCss --optimize-minimize --devtool source-map

But if i change mode to development, like:
webpack --progress --env.staging --mode development --env.extractCss --optimize-minimize --devtool source-map

Then it generates sourcemap for both node_modules and our src folder.
But then we get development source code. Not minified etc. Not a production build.

**What is the expected behavior?**
Generate source map when i tell it to generate source maps.
Even if i build a production build.

What am i missing ? :)

**Other relevant information:**
webpack version:   4.46.0
Node.js version:  14.15.4
Operating System: Windows 10
Additional tools:

**Comment by alexander-akait** [comment]
> If the current behavior is a bug, please provide the steps to reproduce.

Sorry command line arguments without configuration can't help to help you, nobody know, won't fix

**Comment by blarsern** [comment]
Humm this kinda fixed it self when upgrading:
ts-loader, @types/node or sass-loader i think..

Some strange dependencies here..
