### ISSUE TITLE
Redundant file reads in Webpack 4 and ts-loader?

### ISSUE THREAD

**Issue by JasonKleban** [webpack/webpack#12566]
# Bug report

**What is the current behavior?**

I'm first trying to figure out which piece of software this behavior most relates to.  Here's the ts-loader issue perspective:  https://github.com/TypeStrong/ts-loader/issues/1245

This is for webpack 4.  There are compatibility issues I have yet to work through to get as far in Webpack 5.

With Process Monitor on Windows, I'm comparing `tsc --build` to webpack & ts-loader with and without typechecking.  tsc (with typechecking) is a very clear winner.  ts-loader without typechecking or sourcemaps is about 3x duration.  ts-loader WITH typechecking (`transpileOnly: false`) is extremely slow.

The reason that I'm asking about webpack specifically is that file accesses to .less, .css, .js, and package.json files, for example, are also read hundreds of times and I don't know if that's expected and unavoidable, or if it perhaps represents a bug in webpack 4. 
 Is webpack responsible for reading package.json files normally?  Or is that 100% a loader problem, such as ... Is the ts-loader repeat reads of some files causing the repeat reads by the loaders of imported non-ts files?

![image](https://user-images.githubusercontent.com/17498172/106665699-a1cb5080-6574-11eb-980d-629f6d80328f.png)

Example sequential repeated reads:

![image](https://user-images.githubusercontent.com/17498172/106665764-b871a780-6574-11eb-8c75-97d1a878a482.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

Use Sysinternals Process Monitor on Windows to compare ReadFile events between `tsc` and `webpack` builds of the same code with similar configurations.

**What is the expected behavior?**

Totals and durations should be similar.

**Other relevant information:**
webpack version:  4.46.0
Node.js version: 14
Operating System: Windows 10
Additional tools: typescript, ts-loader, [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon)

**Comment by alexander-akait** [comment]
Please do not duplicate issue(s), we already have https://github.com/TypeStrong/ts-loader/issues/1245, be patients, unfortunately the information provided is not enough to tell what the problem is, and yes, it is related to `ts-loader`, please provide example of repo or how we can reproduce it here https://github.com/TypeStrong/ts-loader/issues/1245 and we investigate, if we found the problem in webpack, I will reopen issue and send a PR, wait feedback here https://github.com/TypeStrong/ts-loader/issues/1245
