### ISSUE TITLE
[bug]: concatenated modules are labelled as orphan modules.

### ISSUE THREAD

**Issue by Spence-S** [webpack/webpack#12568]
# Bug report

**What is the current behavior?**
If a module gets concatenated, it will be in the stats as an orphan module, even if they are included in the bundles.

**If the current behavior is a bug, please provide the steps to reproduce.**
Not sure if this is a bug, but if you bundle underscore in production mode, you'll notice all the underscore modules get concatenated and they will all be considered orphan. This happens with all the concatenated modules in my build, underscore is just one of several.

**What is the expected behavior?**
I would expect that concatenated modules are not orphan by default.

**Other relevant information:**
webpack version:  5.19
Node.js version: 12
Operating System: MacOS Big Sur

**Comment by alexander-akait** [comment]
> If a module gets concatenated, it will be in the stats as an orphan module, even if they are included in the bundles.

It for stats, so analyze tools can report about it to you

**Comment by polaroidkidd** [comment]
how can we differentiate between truly orphaned modules and ones which have been included in the bundle?

**Comment by sokra** [comment]
When concatenating it will create a new concatenated module which will contain all the nested modules. You can look into the nested modules from stats too 
The original modules are orphaned as they are really not in the bundle in that version. Instead a different version is in the bundle as nested module.
