### ISSUE TITLE
Relative node modules produce invalid source map path

### ISSUE THREAD

**Issue by Bilge** [webpack/webpack#12569]
# Bug report

**What is the current behavior?**
When the `context` path is below the `node_modules` directory level, the source map path will backtrack with `..` relative path components, which the browser cannot resolve.

**If the current behavior is a bug, please provide the steps to reproduce.**

```js
module.exports = {
    mode: 'development',
    context: path.resolve(__dirname, 'static'),
    entry: {
    foo: [
            './js/foo.ts',
            './css/foo.less',
        ],
    },

    output: {
        path: path.resolve(__dirname, 'static/c'),
        publicPath: '',
    },

    resolve: {
        extensions: ['.ts'],
    },

    plugins: [
        new MiniCssExtractPlugin(),
        new CleanWebpackPlugin(),
    ],

    module: {
        rules: [
            {
                test: /\.(less|css)$/,
                use: [
                    {
                        loader: MiniCssExtractPlugin.loader,
                    },
                    {
                        loader: 'css-loader',
                        options: {
                            url: false,
                            sourceMap: true,
                        },
                    },
                    {
                        loader: 'less-loader',
                        options: {
                            sourceMap: true,
                            lessOptions: {
                                strictUnits: true,
                            },
                        },
                    },
                ],
            },
            {
                test: /\.tsx?$/,
                loader: 'ts-loader',
            },
        ],
    },

    optimization: {
        minimizer: [
            new TerserPlugin(),
            new CssMinimizerPlugin(),
        ],
    },
};
```

It seems the source maps *are* loaded into Firefox.

![image](https://user-images.githubusercontent.com/470626/106674816-dc041480-65ab-11eb-8be4-73d6e7c66251.png)

Nevertheless, it cannot find them. I *assume* this is because the paths are relative, but it may be for some other reason.

![image](https://user-images.githubusercontent.com/470626/106674983-1c639280-65ac-11eb-90f5-0efb1b61cbb6.png)

I have tried amending this configuration to get the output paths to be absolute, but none of the following settings change the output in any way. I don't know what else to try.

```js
module.exports = {
    resolve: {
        modules: [path.resolve(__dirname, 'node_modules')],
        roots: [__dirname],
        preferAbsolute: true,
    }
}
```

**What is the expected behavior?**

webpack should output source maps that the browser can find and use. Note that source maps for all my first-party source files work correctly; only third party modules are affected with this configuration, which I believe is because they sit outside the context directory.

**Other relevant information:**
webpack version:  5.19.0
Node.js version: v14.15.3
Operating System: Windows 10
Additional tools: Firefox 84

**Comment by alexander-akait** [comment]
You need `source-map-loader` to load external source map https://github.com/webpack-contrib/source-map-loader, we want to built-in this in webpack in near future https://github.com/webpack/webpack/issues/10265
