### ISSUE TITLE
Dependency context from `require_optional` needs more information

### ISSUE THREAD

**Issue by rendall** [webpack/webpack#12560]
### Summary

The context generated by the `ContextModuleFactory` from a [`require_optional`](https://www.npmjs.com/package/require_optional) call is not adequate to handle the dependency expression that generates it.

### Details

Is this a bug report?  Is this a feature request? It's ambiguous.

Wherever `require_optional` appears in the code *(e.g. in [MongoDB node driver](https://github.com/mongodb/node-mongodb-native/blob/8082c89f8ef3624d22f4bdd6066b6f72c44f763d/lib/core/index.js#L4))*, Webpack prints a warning `Critical dependency: the request of a dependency is an expression` and bundles all of its possible dependencies.

<details>
<summary>An example of the full warning</summary>
<code>
WARNING in ../node_modules/require_optional/index.js 84:18-42

Critical dependency: the request of a dependency is an expression

 @ ../node_modules/mongodb/lib/core/utils.js

 @ ../node_modules/mongodb/lib/bulk/common.js

 @ ../node_modules/mongodb/index.js

 @ ../lib/MongodbService.js

 @ ./gauth.js
</code>
</details>

Common advice for this warning is to use the [`ContextReplacementPlugin`](https://webpack.js.org/plugins/context-replacement-plugin/) to indicate which dependency is correct (or even just suppress the warning)

The context objects passed to `ContextReplacementPlugin` by the [ContextModuleFactory](https://github.com/webpack/webpack/blob/master/lib/ContextModuleFactory.js) at this stage does not have enough information to respond. The `request` field value is always only `'.'` and every other field value is likewise identical, because the `Context` instance here [refers to dependency requests in `require_optional`](https://github.com/christkv/require_optional/blob/c11c4ec54c29d9f5b8a335db379a4670ceeb6cfb/index.js#L87) and not the underlying dependency that uses it. 

<details>
<summary>e.g. The identical context object passed by every <code>require_optional</code> call</summary>
<code>
{
  "addon": "",
  "resource": "/absolute/path/node_modules/require_optional",
  "context": "/absolute/path/node_modules/require_optional",
  "dependencies": [
    {
      "module": null,
      "weak": false,
      "optional": true,
      "loc": {
        "start": {
          "line": 84,
          "column": 18
        },
        "end": {
          "line": 84,
          "column": 42
        }
      },
      "options": {
        "request": ".",
        "recursive": true,
        "regExp": false,
        "mode": "sync"
      },
      "userRequest": ".",
      "critical": "the request of a dependency is an expression",
      "hadGlobalOrStickyRegExp": false,
      "range": [
        2560,
        2584
      ],
      "valueRange": [
        2568,
        2583
      ]
    },
    {
      "module": null,
      "weak": false,
      "optional": true,
      "loc": {
        "start": {
          "line": 92,
          "column": 20
        },
        "end": {
          "line": 92,
          "column": 44
        }
      },
      "options": {
        "request": ".",
        "recursive": true,
        "regExp": false,
        "mode": "sync"
      },
      "userRequest": ".",
      "critical": "the request of a dependency is an expression",
      "hadGlobalOrStickyRegExp": false,
      "range": [
        2864,
        2888
      ],
      "valueRange": [
        2872,
        2887
      ]
    },
    {
      "module": null,
      "weak": false,
      "optional": false,
      "loc": {
        "start": {
          "line": 99,
          "column": 35
        },
        "end": {
          "line": 99,
          "column": 67
        }
      },
      "options": {
        "request": ".",
        "recursive": true,
        "regExp": false,
        "mode": "sync"
      },
      "userRequest": ".",
      "critical": "the request of a dependency is an expression",
      "hadGlobalOrStickyRegExp": false,
      "range": [
        3091,
        3106
      ],
      "valueRange": [
        3091,
        3106
      ]
    }
  ],
  "resolveOptions": {},
  "request": ".",
  "recursive": true,
  "regExp": false,
  "mode": "sync"
}
</code>
</details>

If there is a single `require_optional` in all of the dependencies, then `ContextReplacementPlugin` can properly handle that single call (or [`resolve.alias`](https://github.com/huksley/require-optional-mongodb)). If there are many, it's not clear which dependency is needed: e.g. one call is [ambivalent between `bson` and `bson-ext`](https://github.com/mongodb/node-mongodb-native/blob/8082c89f8ef3624d22f4bdd6066b6f72c44f763d/lib/core/index.js#L9), and another wants to throw an error if [`mongodb-extjson` is unavailable](https://github.com/mongodb/node-mongodb-native/blob/8082c89f8ef3624d22f4bdd6066b6f72c44f763d/lib/core/utils.js#L51), and yet another wants to halt if [`kerberos` is not installed](https://github.com/mongodb/node-mongodb-native/blob/8082c89f8ef3624d22f4bdd6066b6f72c44f763d/lib/core/utils.js#L30).

**What is the expected behavior?**

The context object that `ContextModuleFactory` creates as a result of `require_optional` should be detailed enough to properly resolve the ambiguity in dependency, perhaps by including the warning's stack trace of the warning that includes the files that call `require_optional`.

**What is motivation or use case for adding/changing the behavior?**

I think it's probably answered under the *Details* heading, above, but I'm happy to clarify if anything is unclear.

**How should this be implemented in your opinion?**

Some naive possibilities (given that I'm naive about Webpack internals):

* Enhance the Context instance passed from ContextModuleFactory, perhaps to include the stack trace if possible, or otherwise enable Context related plugins to distinguish among identical contexts
* If this ambiguity-about-dependencies is passed to plugins via some other ... ModuleFactory?... mechanism, maybe it would be better to create a plugin that uses that

**Are you willing to work on this yourself?**

Definitely. I'd like some feedback or insight, but I am willing to do the heavy lifting. 

First, is this write-up clear? Do you, reading this, understand what the issue is?

Second, if so, is *enhancing* the `Context` instance even possible? Is there a better way? I don't know if the stack trace is even available to the `ContextModuleFactory`.

Edits: nervously clarifying with links and examples

**Comment by alexander-akait** [comment]
bump
