### ISSUE TITLE
Modules fail to load inside user-scoped modules `require` statements

### ISSUE THREAD

**Issue by andrevinsky** [webpack/webpack#1256]
If I depend on a a user-scoped module (i.e. named `@username/user-scoped-module-name`), the modules it depends on fail to load with the error:

```
Error: Cannot find module 'underscore'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> ([..]\webpack:\external "underscore":1:1)
    at __webpack_require__ ([..]\webpack:\webpack\bootstrap 50dd70b4bf3911f26d28:19:1)
    at Object.<anonymous> ([..]\webpack:\~\@eventuateinc\eventuate-nodejs-client\modules\es.js:5:1)
    at __webpack_require__ ([..]\webpack:\webpack\bootstrap 50dd70b4bf3911f26d28:19:1)
    at Object.module.exports.exports.entityTypeName ([..]\webpack:\[..]\src\modules\EsClient.js:1:28)
    at __webpack_require__ ([..]\webpack:\webpack\bootstrap 50dd70b4bf3911f26d28:19:1)
```

This does not apply neither to nodejs internal modules (e.g. 'utils', etc.) nor to locally available files. So if the mentioned user-scoped module has code like this..:

```
/* app.js inside the '@username/user-scoped-module-name' package */
var util = require('util');
var stomp = require('./stomp/stomp');
var _ = require('underscore');
```

.. the exception will get thrown only for the 'underscore' reference (third `require` statement).

I believe the cause of this issue lies in a way the user-scoped modules are loaded into a file system. They reside not in the folder that's an immediate child to `node_modlues` folder but within an extra folder named `@username`:

```
/node_modules
^---/@username
    ^----/user-scoped-module-name
        .package.json
^---/plain-module-name
```

A simple hack to solve this (NOTE, not a proposed solution!) would be to:
1. (after npm install) copy or move the `user-scoped-module-name` folder (in the illustration above) one level up,
2. reference it in the `package.json` as `user-scoped-module-name` instead of `@username/user-scoped-module-name`
3. `require`/`import` it based on its new name (`user-scoped-module-name`).

But this really is a hack in the place where it should work without these atrocities.

Please consider assigning it a high priority, as it fails to support basic npm mechanisms, not something advanced.

**Comment by rascada** [comment]
+1

**Comment by DullReferenceException** [comment]
+1. This really should be a _bug_, not an _enhancement_.

**Comment by IngwiePhoenix** [comment]
Agreed. Sounds like the package resolver is not completely NPM compliant. +1 for this as well, although I haven't run across any scoped modules yet.

**Comment by fleex** [comment]
+1. Clearly a bug, making it impossible to use webpack with scoped modules...

**Comment by adamkdean** [comment]
I'm having an issue here with this as well. Pretty big issue if you ask me!

**Comment by lukebennett** [comment]
I'm amazed there hasn't been more noise about this, it does seem a significant bug and is causing pain here too.

**Comment by sokra** [comment]
It looks like `underscore` is configurated as `external`, which means webpack doesn't resolve it but instead put a `require("underscore")` into the bundle (see stacktrace above where it leaves webpack and enters node.js require). This means `underscore` is resolve by node.js relative to the output path, the bundle.js.

Where do you place your bundle.js? Where is underscore installed? Are you using any other tooling for enhancing the node.js runtime (looks like something special for source map support)?

**Comment by adamkdean** [comment]
@sokra in my case, the issue is that I have a scoped module and it doesn't get picked up by webpack, it's sat in a subdirectory like so: node_modules/@namespace/module_name/

**Comment by sokra** [comment]
@adamkdean That looks like a different problem. Here this issue is that require from inside a user-scoped module is not resolves...

**Comment by adamkdean** [comment]
Ah apologies. It looks like these two issues are related though. Will open up a new issue for that and link it.

**Comment by therippa** [comment]
Any updates on this? It's a big issue for me as well.

**Comment by franleplant** [comment]
Hi! Any updates?

**Comment by danscrima** [comment]
Any update oh this?? I've been trying to use resolve.alias to find scoped packages during a webpack compile but it can never find them. Any updates would be great. Thanks.

**Comment by mderoche** [comment]
+1 on this, would love a fix.  Any updates?

**Comment by MatissJanis** [comment]
This issue still persists. It took me a few hours to find this thread, so that could be the reason why there's not a bigger noise being made - people cannot find this thread.

Any updates or workarounds?

**Comment by rts-rob** [comment]
Hate to "me too" this, but I'm having the same problem and like @MatissJanis it took me hours to find this thread.

I haven't (yet) been able to find a workaround. Extremely frustrating.

**Comment by MatissJanis** [comment]
Not exactly sure this will solve OPs issue.

The fix (workaround) was to create an empty `index.js` file in the root directory of my private NPM module. For some reason that made the issue go away.

**Comment by jonestg** [comment]
I'm having the same problem but creating the empty `index.js` at the root of my module isn't working for me.

**Comment by vanesyan** [comment]
Any updates on the thread?

**Comment by TheLarkInn** [comment]
Can anyone reproduce this in an isolated and simplified repo? Neither @sokra or myself have been able to reproduce this. We ideally would want it as vanilla as possible to rule out any side effects from other configuration settings as encountered earlier in the issue.

**Comment by damianobarbati** [comment]
Same here:
```
//SimpleForm.js
import Input from '../src/Input';
```
//../src/Input.js
import update from '@damianobarbati/react-update';

ERROR in ../src/Input.js
Module not found: Error: Can't resolve '@damianobarbati/react-effect' in '/Users/damz/Desktop/react-redux-form/src'
 @ ../src/Input.js 56:0-50
 @ ../index.js
 @ ./SimpleForm.js
 @ ./router.js
 @ ./index.js
 @ multi babel-polyfill ./index.js
```

**Comment by joachimvdnab** [comment]
Hi, I think I have the same problem as well. I could however solve it by adding an alias for each scoped package mapping the name to the correct directory. But I don't think that this is a good solution. I will try to provide a stripped down project as soon as possible.

**Comment by joachimvdnab** [comment]
@TheLarkInn I have created a simple project with two packages. One package exports a function and the second package just imports the function from the first one. I used lerna to handle the project as a mono repo. You can find the code here [example repo](https://github.com/joachimvdnab/webpack). Hopefully this can help you to solve the problem. I also added an alias to the webpack config of the second package. For now it's commented out, but if you would add that piece then it works.

**Comment by bellcliff** [comment]
Does anyone has a walk around on this problem?

**Comment by e2tox** [comment]
If you are using nodejs. you can use external properties to make it work.

```json
{
  "externals": {
    "@google/maps":"commonjs @google/maps"
  }
}
```

**Comment by evilebottnawi** [comment]
Looks problem solve for `webpack@3` and `webpack@4`. Right?

**Comment by code-matt** [comment]
Hi I am running into this as well, are there any workarounds? A bunch of our internal packages are now scoped but:

```
var _packageName = require('package-name');
```
gets spit out in the compiled versions when it should really be ```require('@scopename/package-name')``` by looking at the package.json name field?

**Comment by jshaw22** [comment]
Has this been solved? On Webpack 4.17 and am getting this error.

**Comment by evilebottnawi** [comment]
@jshaw22 Please update webpack version to latest

**Comment by evilebottnawi** [comment]
Solved. If somebody faced with the issue please open a new issue with reproducible test repo, thanks
