### ISSUE TITLE
Angular 11 with webpack 5 breaks with webpackMissingModule on recompilation

### ISSUE THREAD

**Issue by jawadsh123** [webpack/webpack#12561]
# Bug report

**What is the current behavior?**
An Angular 11 app with webpack 5 breaks after recompilation (for changes on certain files)
```
Cannot find module '@angular/core'
at webpackMissingModule ...
```

**If the current behavior is a bug, please provide the steps to reproduce.**
- git clone https://github.com/difference-engine/ng-webpack5-missing-module.git
- cd ng-webpack5-missing-module
- yarn
- yarn start
- (go to http://localhost:4200/)
- (edit app.module.ts and save)
- refresh browser window, and you should see the error
![image](https://user-images.githubusercontent.com/15520960/106600998-2328e000-6581-11eb-9333-1321086fc25c.png)
- (interestingly, doing the same with app.component.html or app.component.ts doesn't break things)

**What is the expected behavior?**
After recompilation, modules shouldn't go missing :sweat_smile: 

PS: Honestly, I'm not entirely sure if this is a problem with webpack or how angular-cli uses webpack
Although, I noticed recently some changes were made to `rebuildModule` -> https://github.com/webpack/webpack/pull/11433
and `AngularWebpackPlugin` seems to rely on it
https://github.com/angular/angular-cli/blob/master/packages/ngtools/webpack/src/ivy/plugin.ts#L260
hence posting this here

**Other relevant information:**
webpack version:  5.19.0
Node.js version: 14.15.1
Operating System: Ubuntu
Additional tools: @angular-devkit/build-angular: ~0.1101.2

**Comment by alexander-akait** [comment]
`@ngtools/webpack@11.1.2` and `@angular-devkit/build-webpack` still require and use `webpack@4` API, don't use `resolutions` in this case, it is unsafe, sorry we can't help, this tools should migrate on webpack@5 and change their API

**Comment by alexander-akait** [comment]
I recommend to open issue(s) in them repos

**Comment by jawadsh123** [comment]
Thanks for the quick response @alexander-akait, have opened an issue angular-cli :+1:
