### ISSUE TITLE
importScripts used for wasm loading misses publicPath

### ISSUE THREAD

**Issue by maksnester** [webpack/webpack#12577]
# Bug report

After upgrade from webpack 4 to webpack 5 my build of webworker (that in turn uses wasm) got broken, because importScripts do not have publicPath prefix anymore.

**What is the current behavior?**

publicPath is missing in importScripts 

```
/******/ 		__webpack_require__.f.i = (chunkId, promises) => {
/******/ 			// "1" is the signal for "already loaded"
/******/ 			if(!installedChunks[chunkId]) {
/******/ 				importScripts("" + __webpack_require__.u(chunkId));
/******/ 			}
/******/ 		};

// ...

/******/ 	/* webpack/runtime/get javascript chunk filename */
/******/ 	(() => {
/******/ 		// This function allow to reference async chunks
/******/ 		__webpack_require__.u = (chunkId) => {
/******/ 			// return url for filenames based on template
/******/ 			return "" + chunkId + ".js";
/******/ 		};
/******/ 	})();
```

That causes the build to be broken when files are uploaded to CDN.

**If the current behavior is a bug, please provide the steps to reproduce.**

That's not distilled, but [the actual repo](https://github.com/cognitedata/reveal/tree/master/parser-worker) where you can reproduce it.

The latest version uses webpack 4 and works fine. To see things broken you need to upgrade it to webpack 5. The exact steps can be found [here](https://github.com/cognitedata/reveal/pull/1368/files). Literally just 3 steps:
* install webpack5, webpack-cli4
* change syntax for passing env variable in package.json
* update webpack config with `experiments: { syncWebAssembly: true },`

And to actually build things please follow the [readme](https://github.com/cognitedata/reveal/blob/master/parser-worker/README.md). Nothing too hard, you just need to install rust, wasm-pack, and then you'll be able to build it by running `yarn build`.  

Build output is available at `parser-worker/dist/cdn`

**What is the expected behavior?**

`__webpack_require__.p` (aka publicPath) is used. That's example from `"webpack": "4.44.1"` output that works fine

```
/******/ 	__webpack_require__.e = function requireEnsure(chunkId) {
/******/ 		var promises = [];
/******/ 		promises.push(Promise.resolve().then(function() {
/******/ 			// "1" is the signal for "already loaded"
/******/ 			if(!installedChunks[chunkId]) {
/******/ 				importScripts(__webpack_require__.p + "" + ({}[chunkId]||chunkId) + ".js");
/******/ 			}
/******/ 		}));
```

**Other relevant information:**
webpack version:  `5.20.0`

**Comment by sokra** [comment]
Yes it's a bug. I incorrectly assumed that `importScripts` will resolve the url relative to the location of the Worker, but instead it resolves it relative to the HTML document.

**Comment by sokra** [comment]
You can send a PR.

The code is here: https://github.com/webpack/webpack/blob/fdae092cee72426a23c73fa90d4c297ad0100cb2/lib/webworker/ImportScriptsChunkLoadingRuntimeModule.js#L135
https://github.com/webpack/webpack/blob/fdae092cee72426a23c73fa90d4c297ad0100cb2/lib/webworker/ImportScriptsChunkLoadingRuntimeModule.js#L100

This need to be changed to `` `importScripts(${RuntimeGlobals.publicPath} + ${``

And this:

https://github.com/webpack/webpack/blob/fdae092cee72426a23c73fa90d4c297ad0100cb2/test/ConfigTestCases.template.js#L325-L327

need to be changed to check if the path starts with `"https://test.cases/path/"` and `path.dirname(p)` should be replaced with the output directory.

**Comment by anshumanv** [comment]
will PR 👍
