### ISSUE TITLE
Can't use string ref in ModuleFederationPlugin exposes ?

### ISSUE THREAD

**Issue by NexxLuo** [webpack/webpack#12586]
# Bug report

I try to modify an old project code with using `ModuleFederationPlugin` , but get an error in the browser . Because i use `string ref` in the exposes module. Although i can use `React.crateRef`  to fix this issue, but will take a lot of time. Any else way to solve this?
 

**What is the current behavior?**

Set the `exposes` module called Home  in `ModuleFederationPlugin`  :

![1B97J0B@A 6{}$0M7M(@TOP](https://user-images.githubusercontent.com/18549980/106872202-02da5c00-670e-11eb-909a-76df7bbc4a15.png)

In the home module , has a string ref :

![N@LO`7M_ER4RTIZ98@10AX2](https://user-images.githubusercontent.com/18549980/106872225-0968d380-670e-11eb-82b3-96c55b13493c.png)

Error in the browser :

![HLQ7XM XQ5X(`BLYB604 K9](https://user-images.githubusercontent.com/18549980/106872241-0cfc5a80-670e-11eb-8647-6c59d2819482.png)

 

**Other relevant information:**
webpack version:  5.18.0
Node.js version: 12.19.0
Operating System: windows 10
Additional tools: visual studio code

**Comment by alexander-akait** [comment]
Not related to webpack, please read the error message, also you ignore `How we can reproduce it`, so won't fix, sorry

**Comment by NexxLuo** [comment]
> Not related to webpack, please read the error message, also you ignore `How we can reproduce it`, so won't fix, sorry

Thanks for your reply . I make the react shared in `singleton` , it solve this issue.
