### ISSUE TITLE
`esmodule` packaging failure

### ISSUE THREAD

**Issue by ttttttssssss** [webpack/webpack#12585]
# Bug report

**What is the current behavior?**

Compile the results`dist/main.js`

`foo` is undefined
```js
(()=>{"use strict";foo()})();
```

**If the current behavior is a bug, please provide the steps to reproduce.**
`file path`
```shell
.
├── dist
│   ├── index.html
│   └── main.js
├── package-lock.json
├── package.json
├── src
│   ├── index.js
│   └── tool.js
└── webpack.config.js
```
`webpack.config.js`
```js
const path = require('path')
const src = path.join(__dirname, 'src');
const { CleanWebpackPlugin } = require('clean-webpack-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin')
module.exports = {
    mode: "production",
    // mode: 'development',
    context: src,
    entry: path.join(src, 'index.js'),
    output: {
        path: path.resolve(src, '../dist'),
    },
    plugins: [
        new CleanWebpackPlugin(),
        new HtmlWebpackPlugin({
            minify: false
        })
    ]
}
```
`package.json`
```json
{
  "name": "c",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "webpack"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "clean-webpack-plugin": "^3.0.0",
    "html-webpack-plugin": "^5.0.0",
    "webpack": "^5.20.1",
    "webpack-cli": "^4.5.0"
  }
}

```
`src/index.js`
```js
export { foo } from './tool';
foo();
```

`src/tool.js`
```js
export function foo() {
    console.log('foo')
}

export const bar = function () {
    console.log('bar')
}
```
---
`dist/main.js`
```js
(()=>{"use strict";foo()})();
```
`dist/index.html`
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Webpack App</title>
  <meta name="viewport" content="width=device-width, initial-scale=1"><script defer src="main.js"></script></head>
  <body>
  </body>
</html>
```
**What is the expected behavior?**

`dist/index.js`  Be able to find `declare` about `foo function`
And `bar` shouldn't be there,because it is `Tree Shaking`

**Other relevant information:**
webpack version:  5.20.1
Node.js version: v12.19.0
Operating System: mac os
Additional tools: none

**Comment by ttttttssssss** [comment]
> _For maintainers only:_
> 
> * [ ]  webpack-4
> * [x]  webpack-5
> * [ ]  bug
> * [ ]  critical-bug
> * [ ]  enhancement
> * [ ]  documentation
> * [ ]  performance
> * [ ]  dependencies
> * [x]  question

**Comment by alexander-akait** [comment]
No problems, please read how reexport work, if you need debug the problem, rename

`index.js` to `index.mjs`
`tool.js` to `tool.mjs`

Change: `export { foo } from './tool.mjs';`

and run `node src/index.js`

output:

```
file:///home/evilebottnawi/IdeaProjects/webpack-cli/src/index.mjs:3
foo();
^

ReferenceError: foo is not defined
    at file:///home/evilebottnawi/IdeaProjects/webpack-cli/src/index.mjs:3:1
    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
    at async Loader.import (internal/modules/esm/loader.js:166:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
```

**Comment by alexander-akait** [comment]
You need `import`, `export ... from ...` doesn't create something in module what can be used

**Comment by ttttttssssss** [comment]
> You need `import`, `export ... from ...` doesn't create something in module what can be used

Ohhh! I checked again. `export { foo } from './tool';` => `import { foo } from './tool';` 🤣🤣 **typo**
