### ISSUE TITLE
new URL() won't work as I expected upon server side rendering

### ISSUE THREAD

**Issue by chenxsan** [webpack/webpack#12589]
# Bug report

I'm not sure it's a bug or it is how it works, but let me show it first.

**What is the current behavior?**

Generally, I want to server-side rendering a page:

1. Bundle `page.js` to `page.bundle.js` with webpack for server side render (I'm setting `target` to `node` and `output.libraryTarget` to `commonjs2`)
2. Call `renderToStaticMarkup`  from `react-dom/server` to render the`page.bundle.js` of step 1 into html

However, the `page.js` contains code like `const logo = new URL('./logo.svg', import.meta.url)`, now when I require the built `page.bundle.js` and render it with `renderToStaticMarkup`, here's the result of that image:

```html
<img src="file:///Users/sam/Documents/githubRepos/webpack-web-commonjs/dist/c43188443804f1b1f534.svg"/>
```
Which obviously won't work in browser.

**If the current behavior is a bug, please provide the steps to reproduce.**

Here's a repository I've setup https://github.com/chenxsan/issue-webpack-web-commonjs2, you can see the readme for how to reproduce.

**What is the expected behavior?**

`new URL()` works alongside server side rendering.

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

**Comment by alexander-akait** [comment]
I think you want to have https://github.com/webpack/webpack/issues/12474

**Comment by chenxsan** [comment]
From what I can tell in https://webpack.js.org/loaders/file-loader/#emitfile:

> If false, the loader will return a public URI but will not emit the file. It is often useful to disable this option for server-side packages.

It would still output the same public URL with a `emitFile` option for Asset Modules. Actually I don't care about files emitted or not, I just care about the output public URL for those assets introduced by `new URL()`.

**Comment by alexander-akait** [comment]
`clean` broken with multi compiler mode too

**Comment by alexander-akait** [comment]
I think we need an option for this, I don't think it is bug, because you try to create code for node, so this code works in Node.js env, but in your case you need using logic as for web

**Comment by chenxsan** [comment]
Seems like `next` has the same problem when I use the [`new URL()` syntax](https://webpack.js.org/guides/asset-modules/#url-assets):

![image](https://user-images.githubusercontent.com/1091472/106988329-82b60400-67aa-11eb-93dc-ae6eb9c05c72.png)

![image](https://user-images.githubusercontent.com/1091472/106988378-9eb9a580-67aa-11eb-9abe-d4805d50db0b.png)

Just FYI @timneutkens

**Comment by vankop** [comment]
you need to provide your own baseURI for SSR

**Comment by vankop** [comment]
ah, it is not possible right now.. @sokra maybe we need to add an option for baseURI?

**Comment by alexander-akait** [comment]
@vankop Yep, I think we need option here

**Comment by chenxsan** [comment]
Or maybe we can have something like one SSR mode to handle all those SSR related cases like this one or https://github.com/webpack/webpack/issues/12474? And it can be used by plugins/loaders as well if they have server side rendering cases to support.

**Comment by sokra** [comment]
Yeah that's a bit tricky. One problem might be that `new URL` can also be used for paths to assets used by the server. So server code might use `readFile(new URL("./file", import.meta.url))` to read a file. For this use case the url is correct. For SSR instead you need a URL that is valid from browser side.

Note that URLs are always absolute.

There are multiple options available here:

1. Use an absolute `publicPath`. When doing so, this will be returned by `new URL`.
2. Use a helper e. g. `getClientPath` everywhere where `new URL` is used (or in `Image` components or similar), which converts a path on the server/client to a relative client path.
3. I added `__webpack_base_uri__` which allows to change the base URI for `new URL` to something else. You can set this during SSR to the base uri on client, to generate URLs for the client.
