### ISSUE TITLE
Code Splitting with different DefinePlugin definitions?

### ISSUE THREAD

**Issue by ericclemmons** [webpack/webpack#1258]
I'm leveraging [webpack-split-by-path][1] to bundle my `node_modules` into a `vendor.js` (yay!).

However, my client-side code is dependent on `process.env.NODE_ENV` in `development`, `staging`, & `production`.

However, on `staging`, I want to shim `process.env.NODE_ENV = "production"` for only `vendor.js`.  _(That way dead code elimination will let us see exactly how much production-minified code weighs & performs, but allow `client.js` to correctly know the true `process.env.NODE_ENV`).

Unfortunately, when code-splitting, there doesn't seem to be a way to pivot `DefinePlugin` based on the split code.

Thoughts or ideas?

[1]: https://github.com/BohdanTkachenko/webpack-split-by-path#split-by-path-webpack-plugin

**Comment by sokra** [comment]
This doesn't work. In one compilation all modules must compile the same way (with the same options).

You would need multiple compilation (one for the vendors and one for the app) to apply different options. But this would require a complex setup with `DllPlugin` and is propably not worth it.

---

Maybe webpack 2 can use different parsers per module, this would allow to apply some plugins only to a part of the codebase.

**Comment by bebraw** [comment]
Closing given there's an answer. Feel free to bring this up later or set up a feature request.

**Comment by ericclemmons** [comment]
Sorry for not staying on top of this.  This was solved internally over a year ago by simply having an `APP_ENV` (for our logic) and a `NODE_ENV` (for vendors).
