### ISSUE TITLE
`type: "commonjs"` and browser ESM exports with ".js"

### ISSUE THREAD

**Issue by brettz9** [webpack/webpack#12598]
# Bug report

 
**What is the current behavior?**

Hi,

Per https://github.com/webpack/webpack/issues/11597#issuecomment-705114717 and https://github.com/JSONPath-Plus/JSONPath/issues/145 , a couple of projects have run into issues where `type: 'commonjs'` is used and webpack is using this fact to insist that *all* `.js` exports must therefore be CommonJS and complaining when an ES module is encountered.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Add a `package.json` with `"type": "commonjs"`.
2. Add `exports` with a `browser` pointing to `.js`, e.g.:

```json
    ".": {
      "browser": "./dist/index-browser-esm.js",
      "umd": "./dist/index-browser-umd.js",
      "import": "./dist/index-node-esm.mjs",
      "require": "./dist/index-node-cjs.js",
      "default": "./dist/index-browser-esm.js"
    }
```
....where `./dist/index-browser-esm.js` uses an ESM import and/or export.

3. See the message:

> ERROR in ./node_modules/jsonpath-plus/dist/index-browser-esm.js 1061:0
> Module parse failed: 'import' and 'export' may appear only with 'sourceType: module' (1061:0)

**What is the expected behavior?**

In my understanding of the `type` property per the Node docs, that property is specified for the sake of Node. A `browser` or other build should not need to be similarly constrained, and indeed:
 
1. I would expect more browser builds using `package.json` (esp. within `exports` since it has been around) are exposing standard ESM.
2. I understand some browser versions which support modules nevertheless do not automatically treat ".mjs" as JavaScript when a content-type header is absent, causing problems for downstream users. Besides the possible inconvenience of a project being forced to switch to "type: 'module'" to work around this, it seems some testing frameworks like mocha do not support *native* ESM testing, so this would force such projects to write their tests without using ESM.
 
In my humble opinion (and as someone who is not a regular user but is impacted by such users), Webpack should either allow its users configuration to choose the `exports` one desires, expect a specific `umd` type if wishing to allow users to specify other non-ESM browser builds, or just assume ESM for the browser by default.

Thank you.

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

**Comment by alexander-akait** [comment]
"type": "commonjs" and `exports` are completely unrelated properties, you can use and commonjs and esm and node and deno and etc exports

**Comment by alexander-akait** [comment]
> In my humble opinion (and as someone who is not a regular user but is impacted by such users), Webpack should either allow its users configuration to choose the exports one desires, expect a specific umd type if wishing to allow users to specify other non-ESM browser builds, or just assume ESM for the browser by default.

You can use `conditionNames` for setup it https://github.com/webpack/webpack/blob/master/lib/config/defaults.js#L978

**Comment by alexander-akait** [comment]
And adding `exports` (i.e. https://github.com/JSONPath-Plus/JSONPath/pull/146) is breaking change and should use major release

**Comment by brettz9** [comment]
Yes, thank you for the reference to `conditionNames`, and I would think that should allow proper selection (if it is not the default behavior and webpack is somehow otherwise informed it is a browser app). (We've already released with `exports`, so I don't think it is a breaking change, even if we change the file names to which we point since to Node, I believe `exports` causes the resolution to be opaque. It was breaking when we added `exports` because that prevents access to other files, but this shouldn't do that since we are not restricting file access.

However, the issue seems to be that although webpack is finding the right browser-based file through `exports`, the user is being informed (when adding the `type: commonjs`), that the use of ESM within the pointed-to browser file was problematic. Why would the user be getting such an error if not for `type: commonjs`?

**Comment by sokra** [comment]
I think this is working as expected. If you are using `type: "commonjs"` you are basically opting in into `.js` and `.cjs` being CommonJS and `.mjs` being ESM. This is unrelated from the conditions used for `exports` and I don't think there should be explict exceptions here.

Note that you don't have to opt-in into `type: "commonjs"`. You can just omit the property and webpack will auto-detect which file-format it should use for `.js`.

Note that you can also choose the `type` per directory by placing e. g. a package.json with `{ type: "module" }` in `dist/browser`.

**Comment by brettz9** [comment]
But this was all meant for *Node*. Node is just making space for `exports` to be leveraged for other purposes, none of which are obliged to abide by conventions meant for it (browsers of course don't even understand CommonJS in a native way).

I can work around by avoiding opting in with `type: commonjs` for the sake of our users, but if you are going by Node conventions, having it present is supposed to [have the same meaning](https://nodejs.org/api/packages.html#packages_type) as not having it at all. And it is called for not only as a best practice to be more explicit, but Node even raises the possibility that the default behavior could be [switched](https://nodejs.org/api/packages.html#packages_determining_module_system) in the future, meaning you are possibly encouraging projects to do something which causes future Node breakage.

I think others are going to keep discovering and being dismayed by this problem as module use increases, especially since it is tool-specific rather than something Node spelled out. You all admittedly are the ones making the tools, so I guess it is also whatever you want it to mean too. :-) However, I'm not so sure that is very good for the ecosystem. (The nested `browser` folder is at least a standard workaround, albeit a bit clumsy and perhaps prone to some confusion.)

Anyways, you guys are doing the hard work of maintaining this, so I'll leave it at that. Appreciate the investigation of the issue, and suggestions. Take care!

**Comment by alexander-akait** [comment]
> I can work around by avoiding opting in with type: commonjs for the sake of our users, but if you are going by Node conventions, having it present is supposed to have the same meaning as not having it at all. And it is called for not only as a best practice to be more explicit, but Node even raises the possibility that the default behavior could be switched in the future, meaning you are possibly encouraging projects to do something which causes future Node breakage.

I don't think it will ever change, it's huge breaking change and breaks many things, but anything can happen someday...

**Comment by brettz9** [comment]
Ok, will close then if that's the plan. Thanks!
