### ISSUE TITLE
Cannot resolve 'main.js' in /dir

### ISSUE THREAD

**Issue by marco74** [webpack/webpack#12592]
# Bug report

**What is the current behavior?**

Webpack reported it cannot resolve 'main.js' in folder /x/y although the file was present. After changing

  entry:'main.js'

  to 

  entry:'./main.js'

everthing worked fine.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

Do not print out such missleading error message. main.js was present in the directory printed on the console. The message was kind of:

  Module not found: Error: Can't resolve 'main.js' in '/home/marco/projects/<project>/webpage'

But main.js was present in the directory /home/marco/projects/<project>/webpage

Please do not print that the file is not there, when it is present there.

**Other relevant information:**
webpack version: 5.20.2 
Node.js version: 10.23
Operating System: Debian 10
Additional tools:

**Comment by anshumanv** [comment]
This looks like CLI problem, please provide your CLI version

@alexander-akait we fixed something like this right?

**Comment by marco74** [comment]
"webpack-cli": "^4.5.0",

**Comment by marco74** [comment]
I just freshly installed that a couple of minutes ago.

**Comment by anshumanv** [comment]
Thanks, was able to repro, yes the problem is not with CLI my bad, @sokra is this intentional that we enforce the user to provide a relative path prefixed with `./`?

**Comment by sokra** [comment]
yeah, it's like the request you write in `import`s. `import "main.js"` vs `import "./main.js"`.

`main.js` would resolve to `node_modules/main.js`.

**Comment by anshumanv** [comment]
> But I guess we could provide a better error message by trying to resolve it as resolve request too and if this works we can add a Did you mean "./main.js"? to the error message.

Yes that makes sense, will take a look 👍

**Comment by marco74** [comment]
Thanks for the hint that `main.js` could also mean `node_modules/main.js`. The suggestions with "Did you mean" will be really helpful.

Please also keep in mind, that most people outside there do not know a lot about webpack. They only use it because the need to, maybe because of some tool like vue-cli set that up. Of course it's always good to know your tools but sometimes its simply not possible to know all of them.

So writing, that the error occurred while a resolve request, may not be understood by everybody. Instead the user reads a path, webpack says it looked into, but didn't really do so. Could the message contain the path, webpack did really look into, while the resolve request? Otherwise it may be better to not mention a path either but printing the hint with "Did you mean `./main.js`.

**Comment by sokra** [comment]
> Could the message contain the path, webpack did really look into, while the resolve request?

yes -> https://github.com/webpack/webpack/pull/12601

**Comment by marco74** [comment]
> > Could the message contain the path, webpack did really look into, while the resolve request?
> 
> yes -> #12601

Does the detailed information show the real path?

**Comment by alexander-akait** [comment]
Fixed https://github.com/webpack/webpack/pull/12601

@marco74 it shows possible imports which you maybe mean

**Comment by sokra** [comment]
It could be further improved with `Did you mean ./main.js.`

**Comment by anshumanv** [comment]
yep, will PR in a while
