### ISSUE TITLE
Support sharing relative modules from a package in ModuleFederation

### ISSUE THREAD

**Issue by menosprezzi** [webpack/webpack#12594]
## Feature request

Hello guys! Awesome work here!

Here at my company we have our own package of utils, `@neogrid/react`. Utils are grouped by folders so if I want to import the i18n utils, for instance, I will `import { I18nLocaleProvider } from '@neogrid/react/core/i18n';`
The point is that we cant share '@neogrid/react' and its declared contexts because it don't have an index.js importing all the declarations. Only the `./core/i18n` and the other internal modules has.

**What is the expected behavior?**

It will be nice if somehow we declare something like:
```js
      new ModuleFederationPlugin({
        // some config here
        shared: {
          '@neogrid/react/core/i18n': { // Or support a wildcard such as '@neogrid/react/core/*' to match all the folders inside.
            import: '@neogrid/react/core/i18n',
            packageName: '@neogrid/react', // the key used to check the version, according the API.
            shareKey: '', // ? I don't know if the key needs to match each file to work.
            singleton: true
          }
        }
      })
```

**What is motivation or use case for adding/changing the behavior?**

It will support share code in packages that have this type of structure (none comes to my mind when I was writing this, sorry!).
I'd know that our package should need a properly index.js or maybe be splitted in a set of packages...

**How should this be implemented in your opinion?**

In the next major maybe.

**Are you willing to work on this yourself?**
No. I don't have time and I don't know if this is possible to achieve.
Please, tell me if this kind of feature makes sense :)

[]s!

**Comment by menosprezzi** [comment]
@alexander-akait Nice!
What did you mean with use a glob in webpack.config.js? How?

**Comment by alexander-akait** [comment]
> What did you mean with use a glob in webpack.config.js? How?

Using any glob package

**Comment by sokra** [comment]
You can use `"@neogrid/react/core/i18n/"` with a leading /. This will share all sub exports.
