### ISSUE TITLE
compiler.intermediateFileSystem need add sync method on typings

### ISSUE THREAD

**Issue by WanderWang** [webpack/webpack#12599]
## Feature request

compiler.intermediateFileSystem need add sync method ( such as readFileSync ) on types.d.ts

**What is the expected behavior?**

compiler.intermediateFileSystem need add sync method ( such as readFileSync ) on types.d.ts

**What is motivation or use case for adding/changing the behavior?**

I want to use compiler.intermediateFileSystem.readFileSync

**How should this be implemented in your opinion?**

just add some typings on types.d.ts

**Are you willing to work on this yourself?**
yes

**Comment by sokra** [comment]
> I want to use compiler.intermediateFileSystem.readFileSync

Use `readFile` instead.

We could add them only as optional methods, otherwise it would be a breaking change.

**Comment by WanderWang** [comment]
so, may I contribute a PR for it ?

such as

```
interface IntermediateFileSystem {

   readFileSync?:(filepath:string,encoding?:string):Buffer|string
   // others
}
```

**Comment by sokra** [comment]
Yes feel free to do that, but there won't be a guarantee that some other plugin omit this method as it's optional. The default fs has this method.

**Comment by alexander-akait** [comment]
bump

**Comment by alexander-akait** [comment]
Still male sense
