### ISSUE TITLE
stats: 'verbose' is broken with webpack 5.21.0

### ISSUE THREAD

**Issue by snitin315** [webpack/webpack#12608]
# Bug report

`stats: 'verbose'` is broken.

**What is the current behavior?**

using stats: 'verbose' throws an error.

https://github.com/webpack/webpack/blob/01c48f9b8bd5759674c8baa878414362089b2820/lib/stats/DefaultStatsPrinterPlugin.js#L1189

![Screenshot at 2021-02-06 06-45-14](https://user-images.githubusercontent.com/46647141/107104289-f4439000-6846-11eb-9829-dae08eb7bf1d.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

`webpack --stats=verbose`

**What is the expected behavior?**

It should log verbose output like before.

**Other relevant information:**
webpack version:  5.21.0
Node.js version: 12.16.2
Operating System: Debian
Additional tools: None

**Comment by sokra** [comment]
Yes, we need to handle non string values here...

**Comment by sokra** [comment]
Should be fixed in 5.21.1. Could you verify it?

**Comment by snitin315** [comment]
Yes, fixed in 5.21.1 👍🏻
