### ISSUE TITLE
unable to install webpack

### ISSUE THREAD

**Issue by harcop** [webpack/webpack#12609]
# Bug report

**What is the current behavior?**
bug

**If the current behavior is a bug, please provide the steps to reproduce.**
npm install webpack
received error: npm ERR! Unexpected end of JSON input while parsing near '...},"dist":{"shasum":"3'

**What is the expected behavior?**

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

**Comment by harcop** [comment]
npm i --save-dev webpack
receiving error: Unexpected end of JSON input while parsing near '...},"dist":{"shasum":"3'

**Comment by alexander-akait** [comment]
> received error: npm ERR! Unexpected end of JSON input while parsing near '...},"dist":{"shasum":"3'

Something with your register (broken JSON), impossible to fix on our side
