### ISSUE TITLE
Webpack5 failed to cache with some special names like constructor

### ISSUE THREAD

**Issue by liuliangsir** [webpack/webpack#12615]
# Bug report

**What is the current behavior?**
initial cache process will stuck after enabling cache strategy

**If the current behavior is a bug, please provide the steps to reproduce.**
1. add cache option to webpack configuration file
2. import [globals.json](https://github.com/sindresorhus/globals/blob/main/globals.json) in application code

**What is the expected behavior?**
initial cache process will work after enabling cache strategy

**Other relevant information:**
webpack version:  5.21.0
Node.js version: 10.15.3
Operating System: 10.0.19041 N/A Build 19041
Additional tools: N/A

**Comment by sokra** [comment]
Fix is on the way.

It was a one-line fix, but I found 3 other incorrect edge cases related to JSON importing.
