### ISSUE TITLE
Webpack 5 Native Workers generates an unusable chunk for node targets

### ISSUE THREAD

**Issue by Khauri** [webpack/webpack#12614]
# Bug report

**What is the current behavior?**

Using native workers with the `async-node` target generates a chunk that can't be used since it doesn't transform any of the require statements, generate any common chunks, or include the webpack runtime. This makes the chunk impossible to run as it references relative modules that don't exist.

**If the current behavior is a bug, please provide the steps to reproduce.**

I have created a repo to demonstrate the issue here: https://github.com/Khauri/vigilant-pancake
I've included the `dist` folder. `dist/worker.js` is generated from `worker.js` and imports an arbitrary file that's also imported in the main `index.js`. If you look at `dist/worker.js` you'll see it calls `require('./isWorker.js')` which is not available in the `dist` folder. 

**What is the expected behavior?**

I would expect that the generated chunk have some kind of runtime code and interoperability with the main chunk.

**Other relevant information:**
webpack version:  5.21.1
Node.js version:  10.16.3 and 12.6.3 tested
Operating System: 
Additional tools:

**Comment by sokra** [comment]
Worker integration only works with `import { Worker } from "worker_threads"` and not with require

**Comment by Khauri** [comment]
Interesting? Are there any plans to support cjs? Or at the very least show a warning if you use a cjs require? It still seems odd to me that a new bundle is created.

Also it seems like using a `URL` object inside of `new Worker()` is not supported on versions of node <=12.16.
That may be worth mentioning in the docs if it's not already mentioned.

**Comment by sokra** [comment]
I added this info to the documentation.

We might add support for CommonJS eventually (depends on progress in commonjs tree shaking, as this need to be analysed), but note that Node.js neither supports CommonJS as it's using `import.meta.url`.

**Comment by Khauri** [comment]
Is/would it be possible to enable this feature in a different way? Possibly some kind of magic comment?

Currently I'm using babel with `@babel/preset-env`'s modules field set to "cjs" in order to force convert all modules to commonjs, but because this transpilation happens before webpack does any of its static analysis, it gets rid of the `import {Worker} from 'worker_threads'` too soon.

If I disable this option in babel and fully convert the one file it's used in to esm then it'll correctly generate the chunk, but at runtime I get an error:
 
```js
ES Modules may not assign module.exports or exports.*, Use ESM export syntax instead: ./some-dependency-of-worker.js
```

The file it's pointing to is a cjs dependency and is not the file I converted to an esm and none of its dependencies are esm and neither the file nor its dependencies mix `import` and `module.exports`.

**Comment by sokra** [comment]
The error probably happens because some Babel plugin injects imports. This might happen because sourceType is not set to ambiguous

**Comment by alexander-akait** [comment]
@Khauri Can we close?
