### ISSUE TITLE
Multiple URLs for publicPath to allow multiple CDN subdomains

### ISSUE THREAD

**Issue by wordofchristian** [webpack/webpack#1261]
Does webpack have the ability to use multiple URL aliases for the publicPath?

I would like to use [the common trick of having 4 CDN urls to improve  load performance](http://cloudinary.com/blog/reduce_site_load_time_with_multiple_cdn_sub_domains)

**Comment by sokra** [comment]
No, but with a little hack this may be possible:

``` js
var idx = 0;
Object.defineProperty(__webpack_require__, "p", {
  get: function() {
    idx = (idx + 1) % 4;
    return "cdn" + idx + ".server.com/";
  }
});
```

With HTTP2 you don't need this anymore.

**Comment by neekychan** [comment]
@sokra and how about now?

**Comment by bebraw** [comment]
I don't think the situation has changed. As mentioned by Tobias, you can work around this with a `__webpack_require__` specific tweak. Maybe `publicPath` could accept a function where similar customization could be performed so you get entirely static output. If someone is interested, please open a separate issue and propose an API.
