### ISSUE TITLE
I asked in StackOverflow, in Gitter Webpack and in Discord Electron but got no answer

### ISSUE THREAD

**Issue by raphael10-collab** [webpack/webpack#12611]
I asked an helping request 
  in StackOverflow: https://stackoverflow.com/questions/66075114/get-is-not-a-function-at-getpubsubrouter-how-to-fix-my-webpack-configuration

  in webpack Gitter : 

![image](https://user-images.githubusercontent.com/70313067/107121112-f7636e00-6890-11eb-91b2-e7b8b262b370.png)

![image](https://user-images.githubusercontent.com/70313067/107121135-1f52d180-6891-11eb-8045-dd2f709ae833.png)

And also in Discord Electron Forum:

![image](https://user-images.githubusercontent.com/70313067/107121277-d2bbc600-6891-11eb-918c-11f942060aa7.png)

but got no answer, no hints, no help at all.
So, being conscious that this is not the right place, I ask here if there is someone who can give me an hand.

I'm having this error:

    TypeError: get is not a function
        at getPubsubRouter (/home/marco/webMatters/electronMatters/IPFS-
    Forge/.webpack/main/index.js:103184:20)
        at getLibp2pOptions (/home/marco/webMatters/electronMatters/IPFS-
    Forge/.webpack/main/index.js:103201:15)
        at module.exports../node_modules/ipfs-core/src/components
    /libp2p.js.module.exports (/home/marco/webMatters/electronMatters
    /IPFS-Forge/.webpack/main/index.js:103152:25)
        at configureRepo (/home/marco/webMatters/electronMatters/IPFS-
    Forge/.webpack/main/index.js:107078:18)
        at async loadRepo (/home/marco/webMatters/electronMatters/IPFS-
    Forge/.webpack/main/index.js:106927:17)
        at async Function.start (/home/marco/webMatters/electronMatters
    /IPFS-Forge/.webpack/main/index.js:106908:41)
        at async Object.create (/home/marco/webMatters/electronMatters
    /IPFS-Forge/.webpack/main/index.js:102376:21)

Running the node debugging tool I get this error:

    (base) marco@pc01:~/webMatters/electronMatters/IPFS-Forge$ node-
    nightly --inspect ./node_modules/webpack/bin/webpack.js
     New nightly available. To upgrade: `node-nightly --upgrade` 
    Debugger listening on ws://127.0.0.1:9229/fdab8bb4-cd2c-415d-8154-
    ac4b554a0c0f
    For help, see: https://nodejs.org/en/docs/inspector
    Hash: a1c0ce406046af77594b
    Version: webpack 4.46.0
    Time: 24ms
    Built at: 02/06/2021 1:41:03 PM

    WARNING in configuration
    The 'mode' option has not been set, webpack will fallback to 
    'production' for this value. Set 'mode' option to 'development' or 
    'production' to enable defaults for each environment.
    You can also set it to 'none' to disable any default behavior. Learn 
    more: https://webpack.js.org/configuration/mode/

    ERROR in Entry module not found: Error: Can't resolve './src' in 
    '/home/marco/webMatters/electronMatters/IPFS-Forge'

Error, which I do not understand, because this is the path to main.ts : 

    (base) marco@pc01:~/webMatters/electronMatters/IPFS-Forge/src$ ls -lah 
     | grep main.ts 
    -rwxr-xr-x 1 marco marco 1,6K feb  6 09:22 main.ts

that I defined in /tools/webpack/webpack.main.js :   

     entry: ['./src/main.ts'],

And according to IPFS people the problems I'm having are due to the webpack configuration: https://github.com/ipfs/js-ipfs/issues/3531#issuecomment-773989083
But I do not understand where the problem is. 

Would you be so kind in helping me to solve the problem?

**Comment by alexander-akait** [comment]
Bug in code, nothing to fix on webpack side, please read the stack, something try to use `get` method, but `get is not a function` in `.webpack/main/index.js` file

**Comment by alexander-akait** [comment]
Open `.webpack/main/index.js` file and fix the problem

**Comment by alexander-akait** [comment]
And never ignore the issue template, respect the time of other developers

**Comment by alexander-akait** [comment]
https://github.com/jprichardson/node-jsonfile/issues/140

**Comment by raphael10-collab** [comment]
Sorry @alexander-akait . 
What code are you talking about?
The only ipfs-related code I wrote is the following in /src/main.ts : 

const IPFS = require('ipfs');

app.on('ready', async () => {
  createWindow()

  try {
    const node = await IPFS.create()
    const id = await node.id()
    console.log(id)
  } catch (err) {
    console.error(err)
  }
})

IPFS people tell me that it's my webpack configuration which is broken.
And you say that in my code, something is trying to use `get` method.

As I wrote above, I know that this is not the right place to ask for help.
But as I explained, I already asked for help in Gitter Webpack in StackOverflow and in Discord Electron Forum. No hints, no responses, no help

**Comment by alexander-akait** [comment]
Because developers can't answer immediately, you need wait answer, also you ignore the issue template and I can't help you because I can't reproduce, screenshots is not help here, if you need help ASAP - create reproducible test repo and be patient

**Comment by raphael10-collab** [comment]
@alexander-akait I've beein trying to solve this problem, asking for help and getting no response, for the last three days.
That's why I'm here now

This is the reproducible test repo: https://github.com/raphael10-collab/IPFS-Forge
git clone it -> yarn -> yarn start

**Comment by alexander-akait** [comment]
@raphael10-collab Firstly you use `webpack` v4 and webpack v5 in the one project, it is bad, you shouldn't do this (try to use `npm` v7 and you will see the problem)

Also `npm run build` command doesn't exist.

**Comment by alexander-akait** [comment]
Using `npm run package` throw an error `TypeError: Cannot read property 'tapAsync' of undefined` due usage webpack v4 and v5

**Comment by raphael10-collab** [comment]
I didn't realized that I was using webpack v5.
In package.json I have `"webpack": "4"`

**Comment by alexander-akait** [comment]
because https://github.com/electron-userland/electron-forge/blob/master/packages/plugin/webpack/package.json#L31, you need to use v4 or open an issue in `electron-forge` repo to support webpack@5

**Comment by raphael10-collab** [comment]
I already opened an issue more than one month ago in electron-forge to support webpack@5 and I've been told that since upgrading is a complex task, it will take a lot of time. 
Sorry for my ignorance.. how to detect the package using webpack@5?

    (base) marco@pc01:~/webMatters/electronMatters/IPFS-Forge$ npm ls | grep "webpack"
    ├── @electron-forge/plugin-webpack@6.0.0-beta.54
    ├── @types/webpack-env@1.16.0
    ├── copy-webpack-plugin@7.0.0
    ├── fork-ts-checker-webpack-plugin@6.1.0
    ├── node-polyfill-webpack-plugin@1.0.2
    └── webpack@4.46.0

**Comment by alexander-akait** [comment]
Just run `npm ls webpack` and you will see all `webpack` versions

**Comment by raphael10-collab** [comment]
(base) marco@pc01:~/webMatters/electronMatters/IPFS-Forge$ npm ls webpack

    IPFS-Forge@1.0.0 /home/marco/webMatters/electronMatters/IPFS-Forge
    ├─┬ @electron-forge/plugin-webpack@6.0.0-beta.54
    │ ├─┬ html-webpack-plugin@4.5.1
    │ │ └── webpack@4.46.0 deduped // <---------------------
    │ ├─┬ webpack-dev-middleware@3.7.3
    │ │ └── webpack@4.46.0 deduped // <--------------------
    │ └── webpack@4.46.0 deduped // <--------------------
    ├─┬ copy-webpack-plugin@7.0.0
    │ └── webpack@4.46.0 deduped invalid // <-------------------
    ├─┬ node-loader@1.0.2
    │ └── webpack@4.46.0 deduped // <----------------
    ├─┬ node-polyfill-webpack-plugin@1.0.2
    │ └── webpack@4.46.0 deduped invalid // <------------------
    ├─┬ ts-loader@8.0.14
    │ └── webpack@4.46.0 deduped
    └─┬ webpack@4.46.0  // <-------------------
      └─┬ terser-webpack-plugin@1.4.5
        └── webpack@4.46.0 deduped   // <-------------------

npm ERR! code ELSPROBLEMS
npm ERR! invalid: webpack@4.46.0 /home/marco/webMatters/electronMatters/IPFS-Forge/node_modules/webpack

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/marco/.npm/_logs/2021-02-06T16_03_25_817Z-debug.log


They are all webpack@4.46.0 some of which are invalid

**Comment by alexander-akait** [comment]
Yep, because `@electron-forge/plugin-webpack` requires v4

**Comment by raphael10-collab** [comment]
Based on this upgraded template: https://github.com/codesbiome/electron-react-webpack-typescript-2021 
I created a brand new repo : https://github.com/raphael10-collab/Ipfs-Webpack with webpack v5, except for electron-forge which keeps its version v4 : 

    (base) marco@pc01:~/webMatters/electronMatters/Ipfs-Webpack$ npm ls webpack
    Ipfs-Webpack@2.1.0 /home/marco/webMatters/electronMatters/Ipfs-Webpack
    ├─┬ @electron-forge/plugin-webpack@6.0.0-beta.54
    │ ├─┬ html-webpack-plugin@4.5.1
    │ │ └── webpack@4.46.0 deduped
    │ ├─┬ webpack-dev-middleware@3.7.3
    │ │ └── webpack@4.46.0 deduped
    │ └─┬ webpack@4.46.0
    │   └─┬ terser-webpack-plugin@1.4.5
    │     └── webpack@4.46.0 deduped
    ├─┬ css-loader@5.0.1
    │ └── webpack@5.13.0 deduped
    ├─┬ file-loader@6.2.0
    │ └── webpack@5.13.0 deduped
    ├─┬ less-loader@7.2.1
    │ └── webpack@5.13.0 deduped
    ├─┬ node-loader@1.0.2
    │ └── webpack@5.13.0 deduped
    ├─┬ style-loader@2.0.0
    │ └── webpack@5.13.0 deduped
    ├─┬ ts-loader@8.0.14
    │ └── webpack@5.13.0 deduped
    └─┬ webpack@5.13.0
      └─┬ terser-webpack-plugin@5.1.1
        └── webpack@5.13.0 deduped

I installed the latest version of ipfs package and  in main.ts I added only this single line:  

     const IPFS = require('ipfs');

And I get this error:

    A JavaScript error occurred in the main process
    Uncaught Exception:
    Error: Cannot find module 'ipfs'
        at webpackMissingModule (/home/marco/webMatters/electronMatters/Ipfs-Webpack/.webpack/main/index.js:102:78)
        at Module../src/main.ts (/home/marco/webMatters/electronMatters/Ipfs-Webpack/.webpack/main/index.js:102:157)
        at __webpack_require__ (/home/marco/webMatters/electronMatters/Ipfs-Webpack/.webpack/main/index.js:21:30)
        at Object.0 (/home/marco/webMatters/electronMatters/Ipfs-Webpack/.webpack/main/index.js:161:18)
        at __webpack_require__ (/home/marco/webMatters/electronMatters/Ipfs-Webpack/.webpack/main/index.js:21:30)
        at /home/marco/webMatters/electronMatters/Ipfs-Webpack/.webpack/main/index.js:85:18
        at Object.<anonymous> (/home/marco/webMatters/electronMatters/Ipfs-Webpack/.webpack/main/index.js:88:10)
        at Module._compile (internal/modules/cjs/loader.js:1152:30)
        at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
        at Module.load (internal/modules/cjs/loader.js:992:32)

I also added in webpack.main.js : 

    resolve: {
      extensions: ['.js', '.ts', '.jsx', '.tsx', '.css', '.json'],
      //alias: require('./webpack.aliases'),
      modules: ['node_modules', 'src']
    },
    resolveLoader: {
      modules: ['node_modules'],
      mainFields: ['loader', 'main'],
    },

but still :  `Cannot find module 'ipfs'`

**Comment by alexander-akait** [comment]
Because you don't have `ipfs` module, run `npm i ipfs`

**Comment by raphael10-collab** [comment]
(base) marco@pc01:~/webMatters/electronMatters/Ipfs-Webpack$ npm i ipfs

    changed 11 packages, and audited 1804 packages in 4s

    138 packages are looking for funding
      run `npm fund` for details

    3 low severity vulnerabilities

    To address all issues, run:
      npm audit fix

    Run `npm audit` for details.

    (base) marco@pc01:~/webMatters/electronMatters/Ipfs-Webpack$ npm ls ipfs
    Ipfs-Webpack@2.1.0 /home/marco/webMatters/electronMatters/Ipfs-Webpack
    └── ipfs@0.54.1

**Comment by alexander-akait** [comment]
And try to build again

**Comment by raphael10-collab** [comment]
Sorry for the question.... which command you suggest me to add to the scripts in package.json to build?

**Comment by alexander-akait** [comment]
I don't know, run command which run webpack to bundle

**Comment by raphael10-collab** [comment]
Following the indications found here: https://webpack.js.org/guides/getting-started/#creating-a-bundle
I first added in package.json the script: `"build": "webpack"`

when executing `yarn build` I got this error: `Module not found: Error: Can't resolve './src' in '/home/marco/webMatters/electronMatters/Ipfs-Webpack'`

    (base) marco@pc01:~/webMatters/electronMatters/Ipfs-Webpack$ yarn build
    yarn run v1.22.5
    $ webpack
    CLI for webpack must be installed.
      webpack-cli (https://github.com/webpack/webpack-cli)

    We will use "yarn" to install the CLI via "yarn add -D webpack-cli".
    Do you want to install 'webpack-cli' (yes/no): yes
    Installing 'webpack-cli' (running 'yarn add -D webpack-cli')...
    warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix 
    package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning,    
    remove package-lock.json.
    [1/4] Resolving packages...
    warning @electron-forge/plugin-webpack > webpack > watchpack > watchpack-chokidar2 > chokidar > fsevents@1.2.13: 
    fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
    [2/4] Fetching packages...
    info fsevents@2.3.2: The platform "linux" is incompatible with this module.
    info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
    info fsevents@1.2.13: The platform "linux" is incompatible with this module.
    info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
    [3/4] Linking dependencies...
    warning "ipfs > ipfs-cli > ipfs-daemon@0.5.1" has unmet peer dependency "electron-webrtc@^0.3.0".
    warning "ipfs > ipfs-cli > ipfs-daemon@0.5.1" has unmet peer dependency "wrtc@^0.4.6".
    warning "ipfs > ipfs-core > native-abort-controller@0.0.3" has unmet peer dependency "abort-controller@*".
    [4/4] Building fresh packages...
    success Saved lockfile.
    success Saved 11 new dependencies.
    info Direct dependencies
    └─ webpack-cli@4.5.0
    info All dependencies
    ├─ @discoveryjs/json-ext@0.5.2
    ├─ @webpack-cli/configtest@1.0.1
    ├─ @webpack-cli/info@1.2.2
    ├─ @webpack-cli/serve@1.3.0
    ├─ envinfo@7.7.4
    ├─ fastest-levenshtein@1.0.12
    ├─ import-local@3.0.2
    ├─ interpret@2.2.0
    ├─ rechoir@0.7.0
    ├─ resolve-cwd@3.0.0
    └─ webpack-cli@4.5.0
    assets by status 0 bytes [cached] 1 asset

    WARNING in configuration
    The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or   
    'production' to enable defaults for each environment.
    You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/

    ERROR in main
    Module not found: Error: Can't resolve './src' in '/home/marco/webMatters/electronMatters/Ipfs-Webpack'
 
    webpack 5.13.0 compiled with 1 error and 1 warning in 108 ms
    error Command failed with exit code 1.
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by raphael10-collab** [comment]
@alexander-akait A IPFS Developer made a thoughrough analysis which I report here:

https://github.com/ipfs/js-ipfs/issues/3531#issuecomment-774649075   

"

Starting a new project with npx create-electron-app my-new-app --template=typescript-webpack and added IPFS to it. In main.ts I start an IPFS node, I'm greeted with:

Error: Module build failed (from ./node_modules/@marshallofsound/webpack-asset-relocator-loader/dist/index.js):
SyntaxError: Unexpected token (85:14)
    at Object.module.exports.pp$4.raise (/Users/alex/Documents/Workspaces/achingbrain/ipfs-electron-forge/node_modules/@marshallofsound/webpack-asset-relocator-loader/dist/index.js:20834:13)
// some lines omitted
    at Object.parseExprAtom (/Users/alex/Documents/Workspaces/achingbrain/ipfs-electron-forge/node_modules/@marshallofsound/webpack-asset-relocator-loader/dist/index.js:4551:117)
    at Object../node_modules/fs-extra/lib/mkdirs/make-dir.js (/Users/alex/Documents/Workspaces/achingbrain/ipfs-electron-forge/.webpack/main/index.js:76966:7)
    at __webpack_require__ (/Users/alex/Documents/Workspaces/achingbrain/ipfs-electron-forge/.webpack/main/index.js:21:30)
    at Object../node_modules/fs-extra/lib/mkdirs/index.js (/Users/alex/Documents/Workspaces/achingbrain/ipfs-electron-forge/.webpack/main/index.js:76943:44)
    at __webpack_require__ (/Users/alex/Documents/Workspaces/achingbrain/ipfs-electron-forge/.webpack/main/index.js:21:30)
    at Object../node_modules/fs-extra/lib/copy-sync/copy-sync.js (/Users/alex/Documents/Workspaces/achingbrain/ipfs-electron-forge/.webpack/main/index.js:75881:20)
    at __webpack_require__ (/Users/alex/Documents/Workspaces/achingbrain/ipfs-electron-forge/.webpack/main/index.js:21:30)
    at Object../node_modules/fs-extra/lib/copy-sync/index.js (/Users/alex/Documents/Workspaces/achingbrain/ipfs-electron-forge/.webpack/main/index.js:76058:13)
    at __webpack_require__ (/Users/alex/Documents/Workspaces/achingbrain/ipfs-electron-forge/.webpack/main/index.js:21:30)
    at Object../node_modules/fs-extra/lib/index.js (/Users/alex/Documents/Workspaces/achingbrain/ipfs-electron-forge/.webpack/main/index.js:76809:6)
    at __webpack_require__ (/Users/alex/Documents/Workspaces/achingbrain/ipfs-electron-forge/.webpack/main/index.js:21:30)

If I click through the stack trace, eventually in /Users/alex/Documents/Workspaces/achingbrain/ipfs-electron-forge/.webpack/main/index.js on line 76966 I find:

/***/ "./node_modules/fs-extra/lib/mkdirs/make-dir.js":
/*!******************************************************!*\
  !*** ./node_modules/fs-extra/lib/mkdirs/make-dir.js ***!
  \******************************************************/
/*! no static exports found */
/***/ (function(module, exports) {

throw new Error("Module build failed (from ./node_modules/@marshallofsound/webpack-asset-relocator-loader/dist/index.js):\nSyntaxError: Unexpected token (85:14)\n    at Object.module.exports.pp$4.raise (/Users/alex/Documents/Workspaces/achingbrain/ipfs-electron-forge/node_modules/@marshallofsound/webpack-asset-relocator-loader/dist/index.js:20834:13)\n    at Object.module.exports.pp.unexpected (/Users/alex/Documents/Workspaces/achingbrain/ipfs-electron-forge/node_modules/@marshallofsound/webpack-asset-relocator-loader/dist/index.js:18680:8)\n    at Object.module.exports.pp$1.parseTryStatement (/Users/alex/Documents/Workspaces/achingbrain/ipfs-electron-forge/node_modules/@marshallofsound/webpack-asset-relocator-loader/dist/index.js:19069:49)\n    at Object.module.exports.pp$1.parseStatement *snip*");

The error being thrown contains the stack trace that's printed out when I npm start the project.

So ./node_modules/fs-extra/lib/mkdirs/make-dir.js has a syntax error on line 85. Looking at line 85 of make-dir.js at v9.10, it's using Optional Catch Binding, which appears in ECMAScript2019. ECMAScript2019 is otherwise known as ES10

@marshallofsound/webpack-asset-relocator-loader contains an JavaScript AST parser and is a fork of @vercel/webpack-asset-relocator-loader - the fork is now very out of date. It looks like the fork should be able to support ES10 but it defaults to ES9 and doesn't seem to expose an option to change that. If I change the default in the generated source it crashes somewhere else so it's ES10 support may not be fully implemented, I don't know.

The upstream version supports ES2020 so likely would understand the Optional Catch Binding syntax.

So your options are:

    Stop using webpack
    Convince the maintainer of @marshallofsound/webpack-asset-relocator-loader to update their fork and re-apply their patch if it's still necessary

"

**Comment by MarvinXu** [comment]
Passing through... Much love for @alexander-akait 😀
