### ISSUE TITLE
Async externals are not awaited in commonjs modules

### ISSUE THREAD

**Issue by goloveychuk** [webpack/webpack#12629]
# Bug report

**What is the current behavior?**
Currently, if I configure `externals: {someExternal: 'promise window.getDep...'}`, they are awaited only in es modules. 
In commonjs modules they are promises. 
Which is not a big deal, if it's local file. 
But, if some library (umd) you're bundling expected "someExternal" as external, and you have it as async in main bundle - it is a bug, because it's not awaited inside umd factory.

I've experimented a bit, if I change this
https://github.com/webpack/webpack/blob/f75fb35679b1c7fa18f4e698100aaebdf4d65d4a/lib/async-modules/InferAsyncModulesPlugin.js#L38:L38
to 
`(dep instanceof HarmonyImportDependency || dep instanceof CommonJsRequireDependency) &&`
and add `__WEBPACK_EXTERNAL_MODULE_someModule = await __WEBPACK_EXTERNAL_MODULE_someModule` in commonjs module factory - this works great.
Will it work nice with other webpack code? I can submit a pr if it should work.

**If the current behavior is a bug, please provide the steps to reproduce.**
webpack config:
```
externals: {
    someExternal: 'promise Promise.resolve({default: "mod"})'
  },

```
index.js
```
import React from "someExternal";
import React2 from "./mod";
console.log(React, React2)
```
mod.js
```
const React = require("someExternal");

module.exports = React
```
it logs to console - first module, second is promise.

**What is the expected behavior?**
It should be awaited in commonjs modules, I guess

**Other relevant information:**
webpack version:  5.16.0
Node.js version: 
Operating System: 
Additional tools:

**Comment by alexander-akait** [comment]
Why you ignore? 

> If the current behavior is a bug, please provide the steps to reproduce.

> What is the expected behavior?

Please respect time of other developers

**Comment by goloveychuk** [comment]
added more info

**Comment by alexander-akait** [comment]
You can't use `promise Promise.resolve({default: "mod"})` with `import ... from ...`

**Comment by goloveychuk** [comment]
ok, if I change it to 
```
externalsType: 'script',
  externals: {
    someExternal: ["https://cdn.jsdelivr.net/npm/lodash@4.17.19/lodash.min.js", '_'],
  },
```
which (looks like) is the same as promise under the hood,
I have same result - first console.log is module, second is promise.
And according to docs, It's allowed to `import from` for async external (at least script)
https://webpack.js.org/configuration/externals/#example

**Comment by goloveychuk** [comment]
adding 
```js
(dep instanceof HarmonyImportDependency || dep instanceof CommonJsRequireDependency) &&
```
is enough to fix local commonjs modules.

**Comment by sokra** [comment]
When you require an async module you get a promise. This is working as intended.

**Comment by alexander-akait** [comment]
Answer above
