### ISSUE TITLE
Asset modules & fixing bugs on webpack-manifest-plugin: associate sourceFilename with output filename

### ISSUE THREAD

**Issue by weaverryan** [webpack/webpack#12637]
Hi!

I'm the maintainer of https://github.com/symfony/webpack-encore and I've been spending the last few days trying to fix a few bugs in https://github.com/shellscape/webpack-manifest-plugin - specifically related to "asset modules" (e.g. `asset/resource` types) and other auxiliary files (e.g. sourcemap files).

What we need to do "seems" simple. Take this setup:

```js
// webpack.config.js
const path = require('path');

module.exports = {
  entry: './src/index.js',
  output: {
    filename: '[name].[contenthash:8].js',
    assetModuleFilename: 'assets/[name].[hash:8][ext]',
    path: path.resolve(__dirname, 'dist'),
  },
  devtool: 'source-map',
  module: {
    rules: [
      {
        test: /\.(png)$/i,
        type: 'asset/resource',
      },
    ],
  },
};
```

```js
// src/index.js
import './images/logo.png';
```

That's it! We would want a `manifest.json` that looks like this:

```
{
  "main.js": "main.dc10ed89.js",
  "assets/logo.png": "assets/logo.91beba37.png",
  "main.js.map": "main.dc10ed89.js.map"
}
```

It's very simply to get a list of all the files being emitted, but it seems difficult to associate those final filenames with their *original* filename. `webpack-manifest-plugin` has found various ways to do this for various files (and I *almost* made it work for "asset modules").

Am I missing something? Is there a way to reliably get a map from the source filename to the output filename for all files emitted?

Thanks!

**P.S.**  I have a simplified example of how `webpack-manifest-plugin` works here: https://github.com/weaverryan/webpack-manifest-example - the https://github.com/weaverryan/webpack-manifest-example/blob/main/inlined-test-manifest-plugin.js file is a simplified version of `webpack-manifest-plugin`. It *almost* works, except that the sourcemap key is versioned in `manifest.json` and my "asset modules" fix works here, but we have found one setup on Windows where it does not because `asset.info.sourceFilename` is missing for images... I don't know why).

**Comment by alexander-akait** [comment]
> Am I missing something? Is there a way to reliably get a map from the source filename to the output filename for all files emitted?

No way right now, you need plugin for this, but we will improve it in future

Official way is `asset.info.sourceFilename`. I prefer to continue discussion here https://github.com/webpack/webpack/issues/11562

>  but we have found one setup on Windows where it does not because asset.info.sourceFilename

Please provide reproducible test repo, just note `sourceFilename` always use `/`

**Comment by weaverryan** [comment]
Hi @alexander-akait!

You just saved my life! THANK YOU. The key thing was this:

> Official way is `asset.info.sourceFilename`. 

I was not sure if that was correct, but it motivated me to dig into why this was missing in some cases. It turns out it was some sort of Windows + npm bug + mixture of dependencies that list Webpack 4 and 5 as their peer dependency. We had to work around that in the test suite to get things properly installed, but then Webpack behaves perfectly.

Thank you again - your small hint made my week!
