### ISSUE TITLE
Resolving 'acorn/dist/acorn' for build dependencies doesn't lead to expected result

### ISSUE THREAD

**Issue by liuliangsir** [webpack/webpack#12633]
# Bug report

**What is the current behavior?**
initial cache process will stuck after enabling cache strategy

**If the current behavior is a bug, please provide the steps to reproduce.**
1. add cache option to webpack configuration file
2. run [the small reproducible project](https://github.com/liuliangsir/react-webpack-starter-kit)

**What is the expected behavior?**
initial cache process will work after enabling cache strategy

**Other relevant information:**
webpack version:  5.21.2
Node.js version: 14.15.4
Operating System: Linux ws-c164f1d1-8ac0-4f00-8cf1-4c286bfe627f 5.4.0-1024-gcp #24~18.04.1-Ubuntu SMP Sun Sep 6 03:37:03 UTC 2020 x86_64 x86_64 x86_
64 GNU/Linux
Additional tools: N/A

**Comment by alexander-akait** [comment]
Please prefer to use github for repos, we can reproduce due:
```
operation not permitted: missing get permission on workspace
```

**Comment by liuliangsir** [comment]
@alexander-akait Okay, [Here](https://github.com/liuliangsir/react-webpack-starter-kit) is the github repo. In addition, The bug report has already been edited with the new github repos

**Comment by alexander-akait** [comment]
Why do you touch this https://github.com/liuliangsir/react-webpack-starter-kit/blob/master/webpack.config.js#L55?

**Comment by liuliangsir** [comment]
@alexander-akait I would like to control cache path, Therefore add snapshot option to webpack.config.js

**Comment by alexander-akait** [comment]
@liuliangsir Why you need to control it? If you need to cache path you don't need to change `snapshot` options, changing something in the `snapshot` options is not safe and can break caching

**Comment by liuliangsir** [comment]
Okay, I use the above snapshot option, which is displayed on [the official documentation website](https://webpack.js.org/configuration/other-options/#snapshot).

**Comment by alexander-akait** [comment]
@liuliangsir why you change them? What is case, just remove them, all works fine?

**Comment by sokra** [comment]
I tried your repo, but both `yarn start` and `yarn build` work fine and also persistent cache the build.

> initial cache process will stuck after enabling cache strategy

Could you give more details what your are experiencing?

**Comment by alexander-akait** [comment]
> I tried your repo, but both yarn start and yarn build work fine and also persistent cache the build.

Same here

**Comment by liuliangsir** [comment]
I am so sorry to response slowly. I will create a new reproducible example.

**Comment by alexander-akait** [comment]
@liuliangsir friendly ping

**Comment by liuliangsir** [comment]
It seems to be working on windows, So I am going to close the issue above.
