### ISSUE TITLE
[Feature Request] Only build if source files have changed

### ISSUE THREAD

**Issue by lonix1** [webpack/webpack#12643]
## Feature request

**What is the expected behavior?**
As in related tools, it would be nice if webpack would compile "only if source files have changed".

**What is motivation or use case for adding/changing the behavior?**
This is something many are used to from other tools like grunt/gulp. (*Yes those are task runners, but even webpack docs say there is overlap - many use webpack as a task runner AND bundler.*)

It's not just a matter of saving time, though that is very nice.

The real benefit is that on a modern SSD hard drive, recompiling hundreds (thousands depending on project) of files on every build thrashes the drive with lots of small files writes. This is guaranteed to lower its lifespan and ultimately lead to data loss if you aren't careful - that kind of heavy small-file writing is cancer for SSDs.

**How should this be implemented in your opinion?**
There are a few webpack plugins that address this ([e.g.](https://github.com/jsdf/only-if-changed-webpack-plugin/)), but they are all unmaintained and obsolete. I think they keep hashes of files in a temp directory between runs. Maybe that temp directory is in `node_modules/webpack/tmp` or maybe somewhere else. Although not the most elegant solution, it works. They are proof that this can be done, but it would be better for the logic to be in webpack itself.

A more elegant approach is the grunt/gulp/etc way of checking timestamps, but that may not be possible in all cases after source files are transformed. Maybe a comparison can be made to the output bundle's timestamp.

**Are you willing to work on this yourself?**
Wouldn't know where to begin. I'm new to webpack. :)

Thanks for making this great tool, and hope you will consider this! :smile:

**Comment by alexander-akait** [comment]
> As in related tools, it would be nice if webpack would compile "only if source files have changed".

Please use `type: filesystem` https://webpack.js.org/configuration/other-options/#cachetype 

Note - not all things can be cached, but most of places already have cache

**Comment by lonix1** [comment]
**Thanks** for that Alexander! I didn't know it is built in.

So if I'm using it as a bundler then I use `memory`, but if I use it as a task runner then I use `filesystem`?

**Comment by alexander-akait** [comment]
It doesn't matter, it is layered cache, so when you using `filesystem` cache `memory` will be used too

**Comment by lonix1** [comment]
No what I mean is if I use webpack as task runner (not watch mode), then the only way for it to know "don't do this because the sources haven't changed", is to save cache to `filesystem`

Not sure if I'm explaining myself properly. :smile:

**Comment by alexander-akait** [comment]
> No what I mean is if I use webpack as task runner (not watch mode), then the only way for it to know "don't do this because the sources haven't changed", is to save cache to filesystem

Yes

**Comment by lonix1** [comment]
Last thing:

I notice my output says either `[compared for emit] ... [code generated]` or `[compared for emit] ... [nothing/cached]` - which means "did not use cache" and "did use cache".

BUT, some say `[copied]` **every** time - for the copy plugin. Is that a bug in that plugin? Should I open issue in that repo?

**Comment by alexander-akait** [comment]
@lonix1 No bugs, all works as expected, it is just flags, they can be many

**Comment by lonix1** [comment]
Ok thanks!

**Comment by lonix1** [comment]
For anyone else who arrives here:

Although I usually use webpack as a task runner, sometimes I use it in watch mode - so I want caching in memory.

So I did this:
````js
module.exports = (env, argv) {

  // ...

  cache: function () {
    return argv.watch ? { type: 'memory' } : { type: 'filesystem' };
  }(),

}
````

So in watch mode it will use memory, and when used as a pure task runner (not watching) it will cache to disk.

And in both cases webpack will avoid rebuilding if source files haven't changed.
