### ISSUE TITLE
Is there official sass-loader for webpack?

### ISSUE THREAD

**Issue by jeyraof** [webpack/webpack#1264]
I found [sass-loader](https://github.com/jtangelder/sass-loader) in another place.
But I have not trust completely that in operating with `webpack`.
Is there any reason for not owning `webpack/sass-loader`?

many thanks.

**Comment by shama** [comment]
https://github.com/jtangelder/sass-loader is :+1:

With so many possible loaders and limited team resources on the webpack organization, it would be difficult to officially support some loaders. The contributors to `sass-loader` are active in the webpack community and have done a great job maintaining a sass loader for webpack though. Thanks!

**Comment by jeyraof** [comment]
@shama I'm persuaded enough.
And sorry to @jtangelder and others on `jtangelder/sass-loader`.
All, thanks a lot!

**Comment by SimenB** [comment]
Have you thought intoaboutmoving the ones you feel are good and dependable into the organization, and just give the authors access to that repo? Sort of an official stamp of approval?

**Comment by shama** [comment]
@SimenB It is ultimately up to @sokra.

My personal opinion is that moving projects into organizations or making some projects "official" isn't great for an ecosystem. We did that with Grunt and the original contributors moved on. This made the organization volunteers responsible for projects in which they may not have been personally invested in (for example, I don't use sass and would be an awful maintainer for projects related to it).

Also it seemed to discourage individuals from working more freely on projects thinking they needed approval from an organization. We'd missed out on a lot of good ideas in my opinion. If for whatever reason the current `sass-loader` gets stalled or the volunteers there are unable to maintain, anyone else is freely able to fork or create their own at any time without fear of competing with a "approved" project.

**Comment by SimenB** [comment]
I don't have an opinion either way, it was just a thought that struck me when I saw this. But the points you bring up indicates that the current way is the best one. Thanks for the response!
