### ISSUE TITLE
"ERROR in child compilations" not helpful

### ISSUE THREAD

**Issue by einfallstoll** [webpack/webpack#12653]
# "Bug" report

When compiling the message `1 ERROR in child compilations` appears. However, no additional information is printed. When debugging into this I noticed that `compilation.errorsCount` is set to `1`, however `compilation.errors` is an empty array. 

Relevant function:
https://github.com/webpack/webpack/blob/7f3f7805b9325f3da05540a37a027823719007ab/lib/stats/DefaultStatsPrinterPlugin.js#L200

My wild uneducated guess is that the "child" throws an error without a message.

**What is the current behavior?**

This is the output I'm facing. However, `1 ERROR in child compilations` is not helpful without saying _which_ child is causing trouble.

````
$ webpack --mode=production
assets by status 20.6 MiB [cached] 144 assets
orphan modules 46.2 KiB [orphan] 34 modules
runtime modules 3.76 KiB 8 modules
modules by path ../node_modules/core-js/ 381 KiB 382 modules
modules by path ../node_modules/moment/ 672 KiB 137 modules
modules by path ./ 101 KiB (javascript) 358 KiB (css/mini-extract) 20 modules
modules by path ../node_modules/bootstrap-table/dist/ 204 KiB (javascript) 9.4 KiB (css/mini-extract) 6 modules
modules by path ../node_modules/i18n/ 44 KiB 3 modules
modules by path ../node_modules/bootstrap-datepicker/dist/ 57 KiB (javascript) 22.2 KiB (css/mini-extract) 3 modules
modules by path ../node_modules/url/ 37.4 KiB 3 modules
modules by path ../node_modules/querystring/*.js 4.51 KiB 3 modules
modules by path ../node_modules/quill/dist/ 429 KiB (javascript) 24.7 KiB (css/mini-extract) 2 modules
modules by path ../node_modules/debug/src/*.js 11.8 KiB 2 modules
modules by path ../node_modules/@stripe/stripe-js/ 4.35 KiB 2 modules
23 modules
1 ERROR in child compilations
webpack 5.21.2 compiled with 1 error in 101752 ms
````

**If the current behavior is a bug, please provide the steps to reproduce.**

_It's not really a bug, rather missing information_

**What is the expected behavior?**

I expect to _at least_ know what is causing trouble, even if it's something like this:

````
1 ERROR in child compilations:
- MyBrokenPlugin returned exit code 1337 without an error message.
````

**Other relevant information:**
webpack version:  5.21.2
Node.js version: 14.5.5 (LTS)
Operating System: macOS Big Sur 11.2
Additional tools: N/A

**Comment by sokra** [comment]
Try `stats.children: true` to get more info

**Comment by einfallstoll** [comment]
That. Was. Fast. _... and it did the trick._

I think "stats" is a poorly chosen name for this. I would expect _statistics_ not errors when being enabled.

**Comment by sokra** [comment]
We should add a hint to the message pointing to this option

**Comment by einfallstoll** [comment]
Yes, that's a really good suggestion and a time saver!

**Comment by highviewstudios** [comment]
Can somebody tell me where I need to put the ;stats.children: true' bit in my react project please?

**Comment by Pawper** [comment]
> Can somebody tell me where I need to put the ;stats.children: true' bit in my react project please?

```
module.exports = {
  ...
  stats: { children: true }
};
```

I have no idea why my project started getting the child compilations error, but adding the line resolved it for me.

**Comment by manuelmanx** [comment]
> # "Bug" report
> When compiling the message `1 ERROR in child compilations` appears. However, no additional information is printed. When debugging into this I noticed that `compilation.errorsCount` is set to `1`, however `compilation.errors` is an empty array.
> 
> Relevant function:
> 
> https://github.com/webpack/webpack/blob/7f3f7805b9325f3da05540a37a027823719007ab/lib/stats/DefaultStatsPrinterPlugin.js#L200
> 
> My wild uneducated guess is that the "child" throws an error without a message.
> 
> **What is the current behavior?**
> 
> This is the output I'm facing. However, `1 ERROR in child compilations` is not helpful without saying _which_ child is causing trouble.
> 
> ```
> $ webpack --mode=production
> assets by status 20.6 MiB [cached] 144 assets
> orphan modules 46.2 KiB [orphan] 34 modules
> runtime modules 3.76 KiB 8 modules
> modules by path ../node_modules/core-js/ 381 KiB 382 modules
> modules by path ../node_modules/moment/ 672 KiB 137 modules
> modules by path ./ 101 KiB (javascript) 358 KiB (css/mini-extract) 20 modules
> modules by path ../node_modules/bootstrap-table/dist/ 204 KiB (javascript) 9.4 KiB (css/mini-extract) 6 modules
> modules by path ../node_modules/i18n/ 44 KiB 3 modules
> modules by path ../node_modules/bootstrap-datepicker/dist/ 57 KiB (javascript) 22.2 KiB (css/mini-extract) 3 modules
> modules by path ../node_modules/url/ 37.4 KiB 3 modules
> modules by path ../node_modules/querystring/*.js 4.51 KiB 3 modules
> modules by path ../node_modules/quill/dist/ 429 KiB (javascript) 24.7 KiB (css/mini-extract) 2 modules
> modules by path ../node_modules/debug/src/*.js 11.8 KiB 2 modules
> modules by path ../node_modules/@stripe/stripe-js/ 4.35 KiB 2 modules
> 23 modules
> 1 ERROR in child compilations
> webpack 5.21.2 compiled with 1 error in 101752 ms
> ```
> 
> **If the current behavior is a bug, please provide the steps to reproduce.**
> 
> _It's not really a bug, rather missing information_
> 
> **What is the expected behavior?**
> 
> I expect to _at least_ know what is causing trouble, even if it's something like this:
> 
> ```
> 1 ERROR in child compilations:
> - MyBrokenPlugin returned exit code 1337 without an error message.
> ```
> 
> **Other relevant information:** webpack version: 5.21.2 Node.js version: 14.5.5 (LTS) Operating System: macOS Big Sur 11.2 Additional tools: N/A

I have the same problem.... on Macbook 14''  M1 Pro, node:16.13.0

**Comment by Ken-Sarowiwa** [comment]
> 

where in the project directories are we adding this line please??

 module.exports = {
  ...
  stats: { children: true }
};

**Comment by einfallstoll** [comment]
@Ken-Sarowiwa In your webpack config file

**Comment by crisnunez1** [comment]
The color-adjust shorthand is currently deprecated and it depends on the autoprefixer@10.4.6. 
[autoprefixer: Replace color-adjust to print-color-adjust. #36259](https://github.com/twbs/bootstrap/issues/36259)

I was able to fix this by reverting the autoprefixer package to version 10.4.5, run this:

`npm install autoprefixer@10.4.5 --save-exact`

**Comment by ibakirov** [comment]
@crisnunez1 Annoying thing, thanks for shorthand solution 👍

**Comment by GetRekt69420** [comment]
in my case.. it throwing this error because i didn't have a file that i prefaced in webpack.config.js first.. after i created the file.. all is good.. maybe this tip will help someone :)
