### ISSUE TITLE
Worker chunking makes main app bundle to no-op

### ISSUE THREAD

**Issue by RReverser** [webpack/webpack#12652]
# Bug report

In #12646, I've used this demo with `sideEffects:false` https://glitch.com/edit/#!/grass-northern-xenon.

The original issue was solved, but on the same thread @sokra suggested:

> btw.
>
> ``` js
>     splitChunks: {
>       chunks: 'all',
>       minSize: 0,
>       usedExports: false
>     }
> ```
> 
> will put `utils.js` into it's own chunk

as a way to force code-splitting between main JS and the worker.

This seems to trigger another bug: when I use those settings, the main JS no longer calls `initWorker`, a new thread is not created, and the console on https://grass-northern-xenon.glitch.me/ stays empty.

If I comment out e.g. `minSize: 0`, then everything works and `42` is printed in the console as expected.

Note that this time I don't even use `sideEffects: false`, so the issues are likely not related to each other.

**Other relevant information:**
webpack version: 5.21.2
Node.js version: 14.15.2

**Comment by sokra** [comment]
You are splitting the entrypoint so you need to include script tags for both chunks

**Comment by RReverser** [comment]
Oh... I thought Webpack takes care of loading the split-out chunks?

**Comment by sokra** [comment]
Only for node and worker targets. For the webpack loading them in parallel with script tags is more efficient. It's also better for long term caching since they are all independent and don't invalidate each other.

**Comment by RReverser** [comment]
To be fair, I don't deal with Webpack very extensively, so if this is something most Webpack users are already aware of and know how to solve, I'm happy to close the issue.

It just felt counter-intuitive to me personally, especially 1) when it works with one value of `minSize` but not with another and 2) because filenames are autogenerated as numbers by default (288.js, 409.js, 442.js) and not something I could include by hand as script tags without [I'm guessing] tweaking the config somehow further to make filenames stable and human-readable.

**Comment by alexander-akait** [comment]
> To be fair, I don't deal with Webpack very extensively, so if this is something most Webpack users are already aware of and know how to solve, I'm happy to close the issue.

This is how webpack works a long time

> It just felt counter-intuitive to me personally, especially 1) when it works with one value of minSize but not with another and 2) because filenames are autogenerated as numbers by default (288.js, 409.js, 442.js) and not something I could include by hand as script tags without [I'm guessing] tweaking the config somehow further to make filenames stable and human-readable.

You can use `html-webpacj-plugin` to generate HTML files, anyway supporting HTML entrypoint on our roadmap, so in future it will be more intuitive

**Comment by RReverser** [comment]
Fair enough, thanks. I think at least some kind of warning could be helpful, as otherwise for a newcomer it feels like it's hard to tell why the page is blank, but since it's expected behaviour, I'll close the issue.

**Comment by alexander-akait** [comment]
@RReverser Yep, we have the issue for this, but this will increase in runtime...
