### ISSUE TITLE
Standalone bundle, no need for package.json?

### ISSUE THREAD

**Issue by tamis-laan** [webpack/webpack#12651]
I'm trying to bundle my code using webpack to run standalone, such that I don't need `node_modules` and the `package.json`. However after compiling my bundle, when I change `package.json` with a syntax error, my bundled code will no longer run!? For some reason my bundled code still revers to `package.json`, why is this?

**Comment by 368573607** [comment]
Can you describe it in more detail?

**Comment by alexander-akait** [comment]
Please use discussions for questions, it is bug tracker, thanks
