### ISSUE TITLE
Unable to pass custom arguments to config

### ISSUE THREAD

**Issue by bedrich-schindler** [webpack/webpack#12659]
# Bug report

**What is the current behavior?**

Before update from webpack 4.44, webpack-cli 3.3 and webpack-dev-server 3.11.0 to webpack 5.21, webpack-cli 4.5 and webpack-dev-server 3.11.2, we had been able to pass custom attributes to webpack configuration. Since update, I have not been able to make it working again, so we are not able to pass custom attributes in to webpack config now.

Webpack config:

```
module.exports = (env, argv) => {
  const deviceArgument = argv.device;
  const modeArgument = argv.mode;
  const productionServerArgument = argv.productionServer;
  
  // Before update, I was able to read mode and productionServer. It is not working after update.
};
```

NPM scripts before update (package.json):
`"start": "webpack-dev-server --mode=development",`

NPM scripts before update (package.json):
`"start": "webpack serve --mode=development",`

If I execute `npm start -- --device=12.23.45.78 --productionServer` before update, I was able to read those custom arguments in webpack configuration and modify configuration according to it. If I execute the same command now, following error is thrown:

```
[webpack-cli] Error: Unknown option '--device'
[webpack-cli] Run 'webpack --help' to see available commands and options
```

I checked documentation and StackOverflow and it seems that it should be executed as `npm start -- --env device=12.34.56.78 --env productionServer` or something like this. But If I let console.log to print it, neither this variables are passed into the config

**What is the expected behavior?**

I would expect to be able to read custom arguments in webpack config when they are passed.

**Other relevant information:**

node: v14.15.1
npm: 6.14.8
webpack: 5.21.2
webpack-cli: 4.5.0
webpack-dev-server: 3.11.2

**Comment by alexander-akait** [comment]
Not related to webpack, it is breaking change for webpack-cli, you need to use `--env` flags to pass additional options, please report to valid repo if you have questions

`npm start -- --env device=12.34.56.78 --env productionServer` should work but you ignore `How we can reproduce`, so won't fix
