### ISSUE TITLE
The script generated by webpack is not formatted with babel.

### ISSUE THREAD

**Issue by 368573607** [webpack/webpack#12656]
# Bug report

**What is the current behavior?**
Babel-loader is used, but the scripts generated by webpack are not compatible.

![image](https://user-images.githubusercontent.com/60562136/107598100-cd76c680-6c57-11eb-8f3b-2b035aa9dfd4.png)

![image](https://user-images.githubusercontent.com/60562136/107598134-e0899680-6c57-11eb-9c8e-394ae9a5048f.png)

My code is processed, but webpack code is not processed.

**What is the expected behavior?**

The closure function wrapped in the outermost layer and the code used to process the module can be processed by babel.

**Other relevant information:**
* webpack version:  5.21.2
* Node.js version: v14.4.0
* Operating System: Windows 10
* Additional tools: 
    * @Babel/core: 7.12.13
    * @Babel/cli: 7.12.13

**Comment by sokra** [comment]
You are looking for https://webpack.js.org/configuration/target/#browserslist

``` js
target: "browserslist: ie >= 8"
```

**Comment by alexander-akait** [comment]
Answer above, time to drop IE, feel free to feedback
