### ISSUE TITLE
createChildCompiler: taps into hooks by additional plugins get "lost" by design

### ISSUE THREAD

**Issue by danschDE** [webpack/webpack#12668]
# Bug report

This may well be not a bug but a design choice, but some plugins (such as the html-webpack-plugin) may add additional plugins when creating a child compiler. The html-webpack-plugin for instance adds webpack's own LoaderTargetPlugin to set the target to "node". The LoaderTargetPlugin in return taps into the compilation hook to prepare the environment.

**What is the current behavior?**

In the current design, a child compiler "inherits" its compilation taps from the parent compiler by getting its respective taps-array reassigned. As such any previously defined taps into the child compiler's compilation hook get "lost" and are apparently never called.
As a consequence - using html-webpack-plugin as an example again - the childCompiler runs as well using the "web" target since the LoaderTargetPlugin never had a chance to get its tap called.

**If the current behavior is a bug, please provide the steps to reproduce.**

None.

**What is the expected behavior?**

Since adding additional plugins to a child compiler is a valid option when calling "createChildCompiler", one would expect that any taps required by those plugins will be called throughout the compiler/compilation process.
As a temporary fix, I helped myself by merging parent and child compiler taps and it works as expected in my case.
Apparently this may have consequences that I cannot think of right now.
Please let me know if there is anything else I can/need to provide in case I wasn't clear enough.

**Other relevant information:**
webpack version:  5.21.0
Node.js version: v14.15.4
Operating System: Windows 10
Additional tools:

**Comment by alexander-akait** [comment]
> In the current design, a child compiler "inherits" its compilation taps from the parent compiler by getting its respective taps-array reassigned.

No. You can use ` compiler.hooks.thisCompilation` to attach hooks only for main compilation or `compiler.hooks.compilation` to attach hooks for all compilations (including child). Each plugin decides for itself how to do it correctly. 

`html-webpack-plugin` uses `compiler.hooks.thisCompilation` so `compilation.hooks.processAssets` will be executed only for main compilation.

I think `html-webpack-plugin` should not use `LoaderTargetPlugin`. `NodeTemplatePlugin` and `NodeTargetPlugin` are enough for this. Feel free to open an issue in `html-webpack-plugin`. Also feel free to feedback
