### ISSUE TITLE
[webpack-cli] Error: Prevent writing to file that only differs in casing or query string from already written file.

### ISSUE THREAD

**Issue by Varinders0hal** [webpack/webpack#12664]
I am working on a laravel reactjs project and when I run the command npm run dev the compilation stuck at 95% and give the following error. I checked in the whole project there is no file calling with the case-sensitive names all images are calling with the lower case letters.

Error: Prevent writing to file that only differs in casing or query string from already written file.
This will lead to a race-condition and corrupted files on case-insensitive file systems.
/media/public/images/user-4.jpg
/media/public/images/user-4.jpg

React: 17.0.1

Webpack: 5.21.2

Node: 14.15.2

**Comment by alexander-akait** [comment]
No need to like it, because the problem on your side, you emit two files (as you can see in error), it can lead to the problems, but you ignore our issue template so I can't help you
