### ISSUE TITLE
innerGraph incorrectly marking function as unused resulting in broken build

### ISSUE THREAD

**Issue by wesselvdv** [webpack/webpack#12669]
# Bug report

**What is the current behavior?**

Using the default optimizations for production is causing used functions to be marked as unused. I have pinned it down to the option `innerGraph`, setting this option to false seems to fix it.

**If the current behavior is a bug, please provide the steps to reproduce.**

See the reproduction repository: https://github.com/wesselvdv/inner-graph-bug

Reproduction steps:

1. yarn build
2. yarn run

**What is the expected behavior?**

Expected behaviour is that the `O.if` is working in the production build, currently it isn't because the underlying export is marked as unused.

**Other relevant information:**
webpack version:  5.21.2
Node.js version: 14.10.1
Operating System: Arch Linux
Additional tools: N/A

**Comment by vankop** [comment]
Since `@effect-ts/core` does not have side effects ( in package.json `sideEffects: false`, [more info](https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free) ) function expression
```
pipe(
    undefined,
    O.fromNullable,
    O.isNone,
    O.if(() => O.none, () => O.some('test')),
    O.toUndefined,
);
```
has no side effect (so this call is eliminated)

**Comment by mikearnaldi** [comment]
@vankop the library doesn't have side-effects but the linked project has side effects, namely the example is simulating a main file. So the case is a none side effect function is used in a side effect file that should lead to the function not being removed.

**Comment by sokra** [comment]
It's a bug in webpack. The order of `export { branch as if }` and `const branch = /*@__PURE__*/ ...` seem to matter, but it shouldn't

**Comment by sokra** [comment]
I wonder why this hasn't happened before, since it's a pretty obvious bug
