### ISSUE TITLE
Ability to provide a global "use strict;"

### ISSUE THREAD

**Issue by malyw** [webpack/webpack#1267]
Current: So far we can provide "use strict;" for each JS module.
Expected: Config field or something which will add "use strict;" globally for the output JS file.

Workarounds: https://www.npmjs.com/package/strict-loader (loader adds "use strict;" for each loaded module)

**Comment by SpaceK33z** [comment]
Do you use [babel-loader](https://github.com/babel/babel-loader)? It converts your ES6 javascript to ES5 and inserts the 'use strict' for you :).

**Comment by malyw** [comment]
Yep, after moving all JS files to babel it works this way.
