### ISSUE TITLE
some thoughts

### ISSUE THREAD

**Issue by mofengfs** [webpack/webpack#12670]
For those who focus on business development, configuring webpack is a headache. Is it possible to throw any front-end project into a basket, and the basket can automatically generate configuration files?

**Comment by alexander-akait** [comment]
You can get `CRA`, `nextjs`, `vue-cli`, `angular-cli` a d etc where webpack already configured, also there are a lot of boilerplates, please prefer to use `Discussions` for this questions, also we have `webpack init`
