### ISSUE TITLE
When using more than one worker, the main thread bundle references them with an undefined hash

### ISSUE THREAD

**Issue by rubenlg** [webpack/webpack#12676]
# Bug report

**What is the current behavior?**

When declaring two bundles (entry points) each one with its own web worker, and using `[contenthash]`, workers are incorrectly referenced with an `undefined` hash, which the browser can't load.

**If the current behavior is a bug, please provide the steps to reproduce.**

I created a github repo with the minimal repro case. Follow the README.md in that repo:
https://github.com/rubenlg/webpack-undefined-repro

**What is the expected behavior?**

Same as when using `[fullhash]`, both workers should be possible to reference from their respective bundles, i.e. the generated URL should have the correct hash instead of `undefined`.

**Other relevant information:**
webpack version:  5.21.2
Node.js version: v14.15.5
Operating System: Ubuntu Linux 20.04.2 LTS
Additional tools: N/A

Related conversations:
*  https://github.com/webpack/webpack/pull/11686
* https://github.com/webpack/webpack/issues/11677

**Comment by alexander-akait** [comment]
Thanks

**Comment by rubenlg** [comment]
Wow, thanks for the super speedy fix!!
