### ISSUE TITLE
warning webpack-dev-server > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies

### ISSUE THREAD

**Issue by raphael10-collab** [webpack/webpack#12674]
Installing webpack-dev-server I encountered this warning:

`warning webpack-dev-server > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies`

O.S.: Ubuntu 18.04.4 Desktop
node: v14.5.0

**Comment by joealden** [comment]
@raphael10-collab:

1. This is an issue that should be filed in the [`webpack-dev-server`](https://github.com/webpack/webpack-dev-server) repo.
2. In the future, please add more relevant info to the issue, such as your version of `webpack` and `webpack-dev-server`.
3. This warning has already been resolved on the `master` branch of `webpack-dev-server` and will be included in the upcoming v4 release of `webpack-dev-server` (see [`webpack-dev-server@4.0.0-beta.0`](https://github.com/webpack/webpack-dev-server/releases/tag/v4.0.0-beta.0))

**Comment by raphael10-collab** [comment]
Ok . Thank you @joealden for telling me that this warning has already been resolved and will be included in the upcoming v4 release of webpack-dev-server
