### ISSUE TITLE
There are multiple modules with names that only differ in casing.

### ISSUE THREAD

**Issue by code-god-team** [webpack/webpack#12673]
# Bug report
Hi Team 

I am trying to learn node js with webpack 5 and react with some page implemention. But badly i got below warning.

How to fix below error ?
```
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
```

**webpack.config.js**
```
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const { CleanWebpackPlugin } = require('clean-webpack-plugin');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');

module.exports = {
  mode: 'development',
  devtool: 'source-map',
  devServer: {
    contentBase: './build',
    historyApiFallback: true,
    stats: {
      chunks: false,
    },
  },
  entry: {
    index: path.resolve(__dirname, 'docs', 'app.js'),
  },
  output: {
    path: path.resolve(__dirname, './build'),
    filename: '[name].bundle.js',
    libraryTarget: 'umd',
  },
  module: {
    rules: [
      {
        test: /\.(scss|css)$/,
        use: [MiniCssExtractPlugin.loader, 'css-loader', 'sass-loader'],
      },
      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        use: 'babel-loader?cacheDirectory',
      },
    ],
  },
  plugins: [
    new CleanWebpackPlugin(),
    new HtmlWebpackPlugin({
      template: path.resolve(__dirname, 'docs', 'index.html'),
    }),
    new MiniCssExtractPlugin({
      filename: 'assets/[name].css',
      chunkFilename: 'assets/[id].css',
    }),
  ],
};

```

**package.json**
```
{
  "name": "webpack-react-learning",
  "version": "0.0.1",
  "description": "",
  "main": "index.js",
  "scripts": {
    "build": "webpack --mode production",    
    "dev": "webpack --mode development",
    "start": "webpack serve --open"
  },
  "devDependencies": {
    "@babel/core": "^7.12.13",
    "@babel/preset-env": "^7.12.13",
    "@babel/preset-react": "^7.12.13",
    "babel-loader": "^8.2.2",
    "clean-css-cli": "^4.3.0",
    "clean-webpack-plugin": "^3.0.0",
    "css-loader": "^5.0.1",
    "html-webpack-plugin": "^5.0.0",
    "mini-css-extract-plugin": "^1.3.6",
    "npm-run-all": "^4.1.5",
    "prismjs": "^1.23.0",
    "react-router-dom": "^5.2.0",
    "sass": "^1.32.6",
    "sass-loader": "^11.0.0",
    "style-loader": "^2.0.0",
    "webpack": "^5.21.1",
    "webpack-cli": "^4.5.0",
    "webpack-dev-server": "^3.11.2"
  },
  "dependencies": {
    "react": "^17.0.1",
    "react-dom": "^17.0.1"
  },
  "keywords": [],
  "author": "Rajesh",
  "license": "MIT"
}

```

**babel.config.json**

```
{
  "presets": ["@babel/preset-env", "@babel/preset-react"]
}

```
Folder Structure
![image](https://user-images.githubusercontent.com/60088266/107868961-fe9d0400-6eae-11eb-8096-1143e6143322.png)

**Home.js**
![image](https://user-images.githubusercontent.com/60088266/107869060-1628bc80-6eb0-11eb-8466-ddb7c781e4f9.png)

**Display.js**
![image](https://user-images.githubusercontent.com/60088266/107869075-41131080-6eb0-11eb-9b29-87d64c749850.png)

**Code.js**
```
import React, { useEffect } from 'react';
import Prism from 'prismjs';

export default function Code({ code, language = 'markup' }) {
  useEffect(() => {
    Prism.highlightAll();
  }, []);
  return (
    <pre>
      <code className={`language-${language}`}>{code}</code>
    </pre>
  );
}

```

When i import the Code.js or Other common files i am getting below warning
![image](https://user-images.githubusercontent.com/60088266/107869009-7e2ad300-6eaf-11eb-8c5e-173754459cb5.png)

**What is the expected behavior?**
How to fix the warning ?

As a developer I would like to use reusable components instead of writing more codes.

**Other relevant information:**
webpack version:  ^5.21.1
Node.js version: v14.15.4
Operating System: Windows 10
Additional tools: ```
 "react": "^17.0.1",
 "react-dom": "^17.0.1"
```

**Thanks in advance**

**Comment by joealden** [comment]
@code-god-team from the following (taken from https://github.com/webpack/webpack/issues/12673#issue-807890811):

![screenshot](https://user-images.githubusercontent.com/60088266/107869009-7e2ad300-6eaf-11eb-8c5e-173754459cb5.png)

I can see references to both `docs/Components` and `docs/components`, so that would indicate that you have both a `components` and a `Components` directory, or if that isn't the case, that maybe you have mistyped some imports (as from the folder structure you posted, I can only see a `Components` directory, but it looks like that screenshot doesn't show if a `components` directory on the same level could exist).

If that doesn't help, it's be great to get a [minimal reproduction case](https://stackoverflow.com/help/minimal-reproducible-example) (for example, via [CodeSandbox](https://codesandbox.io/s/)).

**Comment by code-god-team** [comment]
@joealden you are right the importing component is issue.

**Comment by alexander-akait** [comment]
Answer, feel free to feedback
