### ISSUE TITLE
Webpack doesn't remove `type: 'module'` from Worker construction

### ISSUE THREAD

**Issue by RReverser** [webpack/webpack#12686]
# Bug report

When using native module workers in browser, one needs to write `new Worker(...path..., { type: 'module' })`.

Webpack's addition of support for `new Worker(new URL('path', import.meta.url))` helps bridge the gap and write code that is less reliant on bundling, but currently it doesn't remove the `type: 'module'` property, and this leads to issues.

**What is the current behavior?**

When using `new Worker(new URL('path', import.meta.url), { type: 'module' })` in order to have code that works in both browser and outside it, Webpack currently transforms the worker JS into a non-ESM version, and uses `importScripts` in the output for any external chunks, but it keeps the `{ type: 'module' }` in the constructor.

As a result, browser creates a module worker, loads the non-ESM bundle, and fails on `importScripts` - which is not allowed in module workers.

**If the current behavior is a bug, please provide the steps to reproduce.**

Check out the sample at https://grass-northern-xenon.glitch.me for code, and https://grass-northern-xenon.glitch.me/out/ for the output (see the runtime error in the console).

**What is the expected behavior?**

Webpack should remove the `type` property after bundling. Probably the easiest to do so by wrapping the options argument in a function that does `delete options.type; return options`, or Webpack might want to be smarter when options is a static object literal and delete the options statically. Either one should work fine, and size difference is minimal.

**Other relevant information:**
webpack version: 5.22.0

**Comment by alexander-akait** [comment]
I think it is more `enhancement` then `bug`, I think we should improve this :smile: Ideally when you use `new Worker(new URL('path', import.meta.url), { type: 'module' })` we should bundle entry in es module format and don't remove `{ type: 'module' }`, but es modules is still under develop, so yep, it is bug

**Comment by RReverser** [comment]
@alexander-akait Yeah it's kinda tricky to categorize, because on one hand it's enhancement to support one more variant, but on another Webpack says that `new Worker(new URL(...))` allows to write code not dependant on bundlers, and then it's rather a bug.

> we should bundle entry in es module format

I really don't think this would be expected behaviour. `new Worker(new URL('somePath', import.meta.url), { type: 'module' })` is essentially same as `import('somePath')` but in a separate thread, and they should be treated in a similar way - that is, both transparently transformed into a working non-ESM version.

**Comment by sokra** [comment]
Yes that's a problem.
