### ISSUE TITLE
`v5.22.0` breaks HtmlWebpackLoader

### ISSUE THREAD

**Issue by trullock** [webpack/webpack#12689]
# Bug report

Updating from 5.21.2 to 5.22.0 makes my build spit out the following errors for all my `HtmlWebpackPlugins`:

`message:  Error: The loader "<path>\\node_modules\\html-webpack-plugin\\li  b\\loader.js!<path>\\src\\app\\app.html" didn't return html.\n+`

Relevant webpack config 

```
new HtmlWebpackPlugin({
			template: path.resolve(__dirname, "src", "app", "app.html"),
			templateParameters: {
				pages
			},
			filename: 'app.html',
			scriptLoading: "defer",
			chunks: ['app']
		})
```

rest of stack trace:

```
      '  - index.js:336 HtmlWebpackPlugin.evaluateCompilationResult\n' +
      '    [Useroo]/[html-webpack-plugin]/index.js:336:24\n' +        
      '  \n' +
      '  - index.js:243 \n' +
      '    [Useroo]/[html-webpack-plugin]/index.js:243:22\n' +        
      '  \n' +
      '  - runMicrotasks\n' +
      '  \n' +
      '  - task_queues.js:93 processTicksAndRejections\n' +
      '    internal/process/task_queues.js:93:5\n' +
      '  \n' +
      '  - async Promise.all\n' +
      '  \n' +
      '  - async Promise.all\n' +
      '  \n'
  },
```

**What is the expected behavior?**

Not to explode, it doesn't in 5.21.2 but does in 5.22.0

**Other relevant information:**
webpack version:  5.22.0 (not 5.21.2)
Node.js version:  12, 14
Operating System: Windows, Linux

**Comment by alexander-akait** [comment]
Problem from `html-webpack-plugin`, nothing to fix here

**Comment by trullock** [comment]
So you don't care about making breaking changes via minor revisions to plugins your own documentation promotes the use of?

**Comment by alexander-akait** [comment]
> So you don't care about making breaking changes via minor revisions to plugins your own documentation promotes the use of?

What? Where is nothing was changed in `webpack`. This problem happens because your update `html-loader` to v2 and `html-webpack-plugin` doesn't support new webpack features. Major updates always potentially have regressions. No one is to blame for this.

**Comment by trullock** [comment]
Here's my package.json:

```
  "devDependencies": {
    "@babel/core": "^7.12.16",
    "@babel/plugin-proposal-class-properties": "^7.12.13",
    "@babel/preset-env": "^7.12.16",
    "babel-loader": "^8.2.2",
    "babel-preset-es2015": "^6.24.1",
    "babel-register": "^6.26.0",
    "bootstrap": "^4.6.0",
    "chokidar": "^3.5.1",
    "css-loader": "^5.0.2",
    "file-loader": "^6.2.0",
    "html-loader": "^1.3.2",
    "html-webpack-plugin": "^4.5.1",
    "mini-css-extract-plugin": "^1.3.6",
    "nsfw": "^2.1.1",
    "purgecss-from-html": "^3.1.3",
    "purgecss-webpack-plugin": "^3.1.3",
    "sass": "^1.32.7",
    "sass-loader": "^10.1.1",
    "style-loader": "^2.0.0",
    "webpack": "^5.21.1",
    "webpack-cli": "^4.5.0"
  }
```

If I do an npm update:

webpack goes to 5.22.0
mini-css-extract-plugin goes to 1.3.7

html-loader doesn't update to 2.0.

updating html-loader to 2.0 with webpack 5.21.1 does yield the same issue, however

**Comment by alexander-akait** [comment]
You need to update `html-webpack-plugin` to v5

**Comment by trullock** [comment]
Thanks, I'll look into that

**Comment by takhello** [comment]
Really a dangerous update, sorry

**Comment by hhd5206** [comment]
You can try to do it like this
module: {
    rules: [
      {
        test: /\.css$/,
        use: ["style-loader", "css-loader"],
      },
      {
        exclude: /\.(css)$/, **//  this is the important**
        loader: "file-loader",
        options: {
          name: "[hash:10].[ext]",
        },
      },
    ],
  },
plugins: [
    new HTMLWebpackPlugin({
      template: "./src/index.html",
    }),
  ],
