### ISSUE TITLE
Dynamic import doesn't work from worker spawned from electron-renderer.

### ISSUE THREAD

**Issue by soerenbf** [webpack/webpack#12683]
# Bug report

A little context: I'm working on a project where we need to load a wasm module through a worker. Recently tried migrating the project to webpack 5. We use [https://github.com/nolanlawson/promise-worker](url) to handle worker communication and registration, but I've tried both with and without this and both fail to load dynamically imported modules.

**What is the current behavior?**
Webpack correctly splits dynamic imports into separate files.

Worker dynamically loading module fires error `ReferenceError: require is not defined
    at Object.__webpack_require__.f.require`.

**If the current behavior is a bug, please provide the steps to reproduce.**
I've created a repo with minimal configuration showcasing the issue:
https://github.com/soerenbf/electron-wasm-worker

The repo is set up with the following branches:

- **webpack-4** (working configuration with webpack 4, loads wasm module)
- **webpack-5** (not working, webpack 5)
- **webpack-5-no-worker** (loads wasm from UI thread instead of worker, this works)
- **webpack-5-web** (loads wasm from worker, but with web as target instead of electron-renderer, this works)
- **webpack-5-native-worker** (loads worker as a native worker, this also fails).
- **webpack-5-native-worker-no-wasm** (same as above, but without WASM to remove this from the equation).

I've tried with both `experiments.syncWebAssembly` and `experiments.asyncWebAssembly`. Both seem to fail.

**What is the expected behavior?**
Dynamic module loads without errors.

**Other relevant information:**
webpack version:  5.21.2
Node.js version: 12.18.3
Operating System: macOS Big Sur
Additional tools: Typescript (4.1.5), Electron (11.2.3)

**Comment by alexander-akait** [comment]
Yep, bug, thanks for the issue

**Comment by sokra** [comment]
* there is a bug in webpack. It thinks that in electron there is no `importScripts` in worker, but it exist. Without this info it doesn't know which chunk loading to use.
* worker-loader lacks wasm support, so you need to migrate to our own Worker support

``` diff
 // index.ts
 import PromiseWorker from 'promise-worker';
-// @ts-expect-error : has no default export.
-import Worker from './worker/test.worker';
 
-const worker = new PromiseWorker(new Worker());
+const worker = new PromiseWorker(new Worker(new URL('./worker/test.worker', import.meta.url)));
 
 worker.postMessage("").then(console.log);
```

and remove the worker-loader rule from webpack.config.js.

* You need to enable nodeIntegrationInWorker or change the globalObject

``` diff
 // electron.ts
    webPreferences: {
+     nodeIntegrationInWorker: true,
      nodeIntegration: true
    }
```

`nodeIntegrationInWorker: true` is needed enable the same electron-mixed node.js and web environment for WebWorkers. Alternatively you can also use `output.globalObject: "self"`, because your repro is only using `global` from the nodeIntegration anyway.

**Comment by soerenbf** [comment]
Thanks for the clarification.

@sokra Just wanted to let you know your latest merge fixes the issue 🙂 
Thanks a ton for the swift resolution! Version hasn't been bumped though and hasn't been released to npm. Any reason for that?

**Comment by sokra** [comment]
Will do soon
