### ISSUE TITLE
Setting dynamic publicPath with commons module

### ISSUE THREAD

**Issue by matthisk** [webpack/webpack#1268]
For my deployment of Webpack I have to dynamically set the publicPath through `__webpack_public_path__`. I make use of the CommonsChunkPlugin, where some modules in the commons module depend on the public path to be set to be able to load (font) files. The problem is that settings the `__webpack_public_path__` at the start of my entry file(s) result in it being set after the commons module is loaded, thus the public path not being present for the file loads. What is the best way to solve this issue, is there a way to inject some code into the commons module?

**Comment by matthisk** [comment]
I found the solution to this problem with the help of the following line from the documentation:

`Advanced hint: You can run code inside the commons chunk`

If anybody is ever wondering how to do this, just create an additional entry point (named commons in this example) and initialize the plugin as follows:

`new CommonsChunkPlugin("commons", "commons.js")`

**Comment by epsitec** [comment]
@matthisk I am struggling with the same kind of issue, trying to set `__webpack_public_path__` in one chunk only to find that the change is not visible in the other chunks, especially in the hot loader. Can you share your complete `webpack.config.js` file? It might be helpful...

**Comment by epsitec** [comment]
Oh, I've just run into [this thread](https://github.com/webpack/webpack/issues/1650) which explains that the behaviour I am seeing is by design. When using hot module reload, every module gets its own instance of `__webpack_require__`.
