### ISSUE TITLE
Specify chunk for dynamic import

### ISSUE THREAD

**Issue by marcusds** [webpack/webpack#12681]
## Feature request

**What is the expected behavior?**
When one has multiple dynamic imports in one entry, the ability do make sure they are not merged into one chunk.

If there are many dynamic imports in an entry, but only one of them might be called a session, it may make sense to only have one import per chunk rather than always putting all dynamic imports in an entry in a chunk.

**What is motivation or use case for adding/changing the behavior?**
Minimizing downloading of unused code.

**How should this be implemented in your opinion?**
Perhaps through a magic comment, something like webpackOwnChunk: true?

**Are you willing to work on this yourself?**
no, tried to look at the source to see if I could figure out how to do it but had no idea where to even get started.

**Comment by sokra** [comment]
> the ability do make sure they are not merged into one chunk.

That's the default. You need to do something to get them merged into the same chunk. e. g.
* Giving them the same name
* Using splitChunks with an constant name
* Some chunk merging plugins like MinChunkSize or LimitChunkCount

**Comment by marcusds** [comment]
@sokra Thank you for your response.

I'm not sure what I am doing wrong then, my splitChunks is mostly default, simply:
`splitChunks: {
	cacheGroups: {
		vue: {
			test: /[\\/]node_modules[\\/]vue[\\/]dist/,
			name: 'vendor/vue',
		}
	}
}`

My imports at different points in my entry look something like:
`import(/* webpackExports: ["SomeModule"] */ 'packageA')`
`import(/* webpackExports: ["SomethingElse"] */ 'packageB')`
`import(/* webpackExports: ["SomethingElseFurther"] */ 'packageC')`

But if I were to run just one of those imports, and out put a console.log of the promise's return I get an object containing, SomeModule, SomethingElse, and SomethingElseFurther.

**Comment by alexander-akait** [comment]
Just use `LimitChunkCount` with `maxChunks: 1` and all your chunks will be union in the one chunk. You disable `splitChunks` in your case (or use the same name for entry and splitting chunks, but I recommend to use `LimitChunkCount`)

 `webpackExports` is used for drop unused exports and it doesn't affect of count of chunks, from docs:
> webpackExports: tells webpack to only bundle the specified exports of a dynamically import()ed module. It can decrease the output size of a chunk.

> But if I were to run just one of those imports, and out put a console.log of the promise's return I get an object containing: SomeModule, SomethingElse, and SomethingElseFurther.

Yes, because it is different imports,

Fully answer above (https://github.com/webpack/webpack/issues/12681#issuecomment-779049500), unfortunately you did not provide examples of your code, so we cannot clearly indicate how you can achieve this for your case. Anyway feel free to feedback, if you provide example I will show you how to achieve it.

**Comment by marcusds** [comment]
Hi @alexander-akait,

I am actually having the opposite problem., My imports are already be combined into 1 chunk, when I want them to be separate chunks. Currently one import loads all the imports in the entry even when using webpackExports to only load 1 of the exports.

I created a small sample repo here to show my problem: https://github.com/marcusds/webpack-imports-sample

**Comment by alexander-akait** [comment]
Unfortunately splitting modules between dynamic imports is not supported, other bundlers doesn't support it too https://bundlers.tooling.report/code-splitting/splitting-modules/dynamic-import/, there are some difficult things here to implement this

**Comment by marcusds** [comment]
Interesting, so even though they are unrelated modules they have to be included with other unrelated dynamic imports?

**Comment by alexander-akait** [comment]
https://github.com/marcusds/webpack-imports-sample/blob/main/src/index.js#L7 and https://github.com/marcusds/webpack-imports-sample/blob/main/src/index.js#L24 is the same import

**Comment by marcusds** [comment]
Ah yes that is true for my reproducation. In my real use case they are coming from separately installed NPM packages. I will attempt to update my example with a proper reproduction.

**Comment by marcusds** [comment]
If I was importing several external packages, which shared another external package as a dependency would that result in the same use scenario as importing two modules from the same file?

**Comment by marcusds** [comment]
To anyone else who encounters this issue, to get around this problem I am doing a simple "proxy" script just `export { something } from 'something';` and that seems to be solving my problem. Haven't found a reason not to try it this way yet at least.
