### ISSUE TITLE
 Error: The loader html-webpack-plugin didn't return html.

### ISSUE THREAD

**Issue by BarrMan** [webpack/webpack#12687]
# Bug report
Since v5.22, build are failing with this error:
```
ERROR in   Error: The loader "/Users/my-user/project/node_modules/html-webpack-plugin/lib/loader.js!//Users/my-user/project/src/app/index.html" didn't return html.

  - index.js:336 HtmlWebpackPlugin.evaluateCompilationResult
    [ni-xbox2]/[html-webpack-plugin]/index.js:336:24

  - index.js:243 Promise.resolve.then
    [ni-xbox2]/[html-webpack-plugin]/index.js:243:22

  - next_tick.js:68 process._tickCallback
    internal/process/next_tick.js:68:7



webpack 5.22.0 compiled with 1 error and 1 warning in 73981 ms
ℹ ｢wdm｣: Failed to compile.
```

**What is the current behavior?**
The build are failing, saying that the html file did not return an HTML output.

**If the current behavior is a bug, please provide the steps to reproduce.**
Upgrade webpack from v5.21 to v5.22, reinstall node_modules and webpack will fail to build the project.

**What is the expected behavior?**
Webpack should build the project.

**Other relevant information:**
webpack version:  v5.22
Node.js version: v15.8.0
Operating System: MacOs Catalina v10.15.7
Additional tools:

**Comment by alexander-akait** [comment]
Not related to webpack, please open a issue in `html-webpack-plugin`, maybe related https://github.com/jantimon/html-webpack-plugin/issues/1602, new `html-loader` uses `new URL` syntax, but not all plugins ready for this, nothing to fix here

**Comment by alexander-akait** [comment]
Will be great if you provide reproducible test repo in your issue for `html-webpack-plugin`, and I will look how to fix it ASAP

**Comment by BarrMan** [comment]
Actually when duplicated the repo twice, once with webpack v5.22 and once with v5.21, I also tested the versions of html-webpack-plugin. They were both the same (v4.5.1).

I'll try to create a sample test repo for this case. Are there any flags I could use to narrow the issue down?

**Comment by alexander-akait** [comment]
Just less loaders and plugins :smile: The simpler the repository, the easier it is to identify the problem.

**Comment by BarrMan** [comment]
I'll try the best I can.. This repo is quite large. Will let you know soon

**Comment by matthewrobb** [comment]
I just started having this issue myself, looking into it more to see if I can help provide context

**Comment by brriann** [comment]
I am also experiencing this issue.  webpack 5.20.0 and html-webpack-plugin 4.3.0.  will follow this/related issues and update with more relevant information as possible

**Comment by chenxsan** [comment]
As far as I know, the latest `html-webpack-plugin` is v5.1.0, and it's webpack 5 compatible. So try to upgrade `html-webpack-plugin` first.

**Comment by brriann** [comment]
Thank you Sam, I forgot to update this thread - upgrading to latest did indeed fix the issue.

**Comment by fathimashba** [comment]
npm i -D html-webpack-plugin@latest this command should work. U just have to update the html webpack here and it will work.
