### ISSUE TITLE
Watching error with ContextModule

### ISSUE THREAD

**Issue by cdoublev** [webpack/webpack#12701]
# Bug report

**What is the current behavior?**

When saving changes to a file bundled in a multi-compiler mode (not sure this is relevant though), of a server side rendered React application, hydrated client side after synchronous loading of the dynamically splitted chunks (meaning the use of `require.resolveWeak`), compiler watching crashes with the following error:

```
/var/www/app/node_modules/watchpack/lib/watchpack.js:106
                        ? path => !ignored.test(path.replace(/\\/g, "/"))
                                ^
TypeError: path.replace is not a function
    at filter (/var/www/app/node_modules/watchpack/lib/watchpack.js:106:33)
    at Watchpack.watch (/var/www/app/node_modules/watchpack/lib/watchpack.js:122:9)
    at NodeWatchFileSystem.watch (/var/www/app/node_modules/webpack/lib/node/NodeWatchFileSystem.js:84:16)
    at Watching.watch (/var/www/app/node_modules/webpack/lib/Watching.js:254:48)
    at /var/www/app/node_modules/webpack/lib/Watching.js:231:13
    at processTicksAndRejections (node:internal/process/task_queues:76:11)
```

`path` has the following value (isolated with `!path.replace && console.log(path) || !ignored.test(...)`:

```js
LazySet {
  _set: Set(2) {
    '/var/www/app/package.json',
    '/var/www/app/src/universal'
  },
  _toMerge: Set(0) {},
  _toDeepMerge: [],
  _needMerge: false,
  _deopt: true
}
```

I also figured out that **all** other watched paths are `String`s, and that `NormalModule` uses `LazySet` for its dependencies since [this change](https://github.com/webpack/webpack/commit/c21fb4bd582cde908d397917bd3a90fa16891f32), but it has not been applied to `ContextModule`. Replacing the "normal" `Set`s used for its dependencies by `LazySet`s, prevents the watcher from crashing, and the re-compilation completes successfully.

**If the current behavior is a bug, please provide the steps to reproduce.**

I will do my best to produce a minimum reproduction repository before the week end. For some reason that I haven't figured out yet, this error does not occur when removing the universal loading setup. The application has repositories as dependencies, which are related to this `universal` setup but are not published on the Internet.

In the meantime, if a webpack maintainer already thinks this change (`Set` -> `LazySet`) is really missing, I would be happy to avoid spending more time on this issue!

Update:

- Clone [this repository](https://github.com/cdoublev/webpack-issue)
- Run `npm start`
- Open and save `./src/pages/hello.js`

**What is the expected behavior?**

`watchpack` should not crash.

**Other relevant information:**
webpack version:  5.22.0
Node.js version: 15.8.0
Operating System: Debian Buster

**Comment by cdoublev** [comment]
Here is a [minimum reproduction repository](https://github.com/cdoublev/webpack-issue) (also updated in my initial comment with the steps to reproduce the bug).

I figured that the bug might come from a conflicting import of `core-js/modules/esnext.set.add-all.js` in `./src/universal.js`, which is injected by `babel` when its configuration has `corejs` option with `proposals: true`.

The thing I can't understand yet, is that I can't reproduce the watching error when running a single compiler (client or server).

**Comment by alexander-akait** [comment]
Problem from `webpack-hot-server-middleware`, if you comment `app.use(webpackHotServerMiddleware(compiler))` code all works fine, here interesting case when you use `requireFromString` https://github.com/60frames/webpack-hot-server-middleware/blob/master/src/index.js#L65, code from webpack evaluated so some globals (from evaluated code) was modified (that is why `Set` polyfill break code) https://github.com/zloirock/core-js/blob/master/packages/core-js/modules/esnext.set.add-all.js

Problem here https://github.com/webpack/webpack/blob/master/lib/cache/ResolverCachePlugin.js#L44 (new `Set` has `addAll` method), if you add `cache: false` for both compilers all will work fine.

**Comment by alexander-akait** [comment]
> Edit: @babel/preset-env adds the Set polyfill when useBuitIns is entry|usage, even when corejs has proposals: false.

Here bug in babel (I think), because it is just `proposals`, so using them is very dangerous, they potential break code

**Comment by cdoublev** [comment]
My apologies: I don't know how I came to observe that `babel` injects `add-all` when `proposals` is `false`, but it is wrong. Thanks for the helpful insights from above. I was aware of some other issues related to the code eval by `requireFromString`. I'm afraid I'm not competent enough to find a workaround, but I'll try!

**Comment by alexander-akait** [comment]
Let's keep open, in theory we can add additional check https://github.com/webpack/webpack/blob/master/lib/cache/ResolverCachePlugin.js#L44 to ensure is it `Set` or our `LazySet`, I think we can fix it using:
```
const addAllToSet = (set, otherSet) => {
	if ("addAll" in set && !(set instanceof Set)) {
	       set.addAll(otherSet);
	} else {
		for (const item of otherSet) {
			set.add(item);
		}
	}
};
```

**Comment by cdoublev** [comment]
Oh sorry.

I also found this "dumb" workaround for `webpack-hot-server-middleware`:

```js
  // Delay read from string by wrapping its execution in a function
  serverRenderer = () => getServerRenderer(filename, buffer, serverRendererOptions);
  // ... executed in the middleware
  try {
    serverRenderer(/* requireFromString */)(req, res, next);
  } 
  // ... catch server render error (better late than never...)
}
```

**Comment by alexander-akait** [comment]
Yep, should also works fine
