### ISSUE TITLE
Sentry support in Module Federation

### ISSUE THREAD

**Issue by rramaa** [webpack/webpack#12706]
## Feature request

**What is the expected behavior?**
Sentry intercepts errors at a global level. That error is tagged with a release version and the sourcemaps related to that release is used for displaying the real source.

But now since an error source can be any part of the code and that part can have different release versions(since they are deployed separately), how I can communicate the release version to sentry so that my error can get successfully decoded by the source map. Basically, the core problem is, I want to get the source of the error so that I can successfully identify the name of the federated app from where the error was thrown.

**How should this be implemented in your opinion?**
In my opinion, if somehow webpack can tag the error with the federated app somehow, it might be possible to get more details about that error

**Are you willing to work on this yourself?**
I am willing to contribute if there are any changes required here.

Issue in sentry's repository https://github.com/getsentry/sentry-javascript/issues/3268

**Comment by sokra** [comment]
Afaik it's not technically possible to tag errors thrown by the source. You need to get that from the stack trace.

**Comment by rramaa** [comment]
That's what I thought. Traces are mangled in production mode. Is there any federation plugin configuration through which I can get the source application from where the error originated(through stack traces itself or any other way)?

**Comment by ScriptedAlchemy** [comment]
You'd need to tag it somehow or wrap some kind of boundary which labels the remote and labels the current host

**Comment by ScriptedAlchemy** [comment]
DefinePlugin(CURRENT_HOST) would work in defining "who am i"

**Comment by rramaa** [comment]
@ScriptedAlchemy that would work for synchronous errors, but async errors would get lost

**Comment by ScriptedAlchemy** [comment]
I've published a post detailing how to handle distributed logging. We have implemented it with sentry hub and custom use of the low level apis
