### ISSUE TITLE
Facing undefined error for json import while running jest enzyme test cases

### ISSUE THREAD

**Issue by ddbhagat** [webpack/webpack#12705]
# Bug report

**What is the current behavior?**

To fix the below warning
```
  WARNING in ./src/modules/components/xxx/ABC.tsx 68:17-40
  Should not import the named export 'xyz' (imported as 'CDF') from default-exporting module (only default export is available soon)
```
As suggested in Webpack 5, https://webpack.js.org/migrate/5/#using-named-exports-from-json-modules I am changing JSON imports from import * as data from './data.json'; to import data from './data.json';

This is working perfectly fine for react application. But jest + enzyme test cases started failing with undefined error wherever this json data is been accessed.

I dont want to enable esModuleInterop as this could increase bundle sizes.

**If the current behavior is a bug, please provide the steps to reproduce.**
- Upgrade to Webpack 5
- Update the json imports as suggested in migration guide
- Run the test cases

**What is the expected behavior?**
Json import should be accessible.

**Other relevant information:**
webpack version:  5.21.2
Node.js version: 12.18.3
Operating System: Ubuntu 20
Additional tools:CircleCi

**Comment by alexander-akait** [comment]
We just follow the spec, also it is works without `ts`, so you need additional options for jest + enzume + ts, you can open an issue/ask in discussions in these repos, sorry, nothing to fix on webpack side
