### ISSUE TITLE
Foo.prototype.isFoo = true breaks tree-shaking

### ISSUE THREAD

**Issue by mrdoob** [webpack/webpack#12716]
# Bug report

**What is the current behavior?**

Seems like [Webpack tree-shaking breaks when adding a property to a class prototype](https://github.com/mrdoob/three.js/pull/21285#issuecomment-780519616).
Rollup however, [seems to be able to tree-shake it](https://rollupjs.org/repl/?version=2.39.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMEZvbyUyMCU3RCUyMGZyb20lMjAnLiUyRkZvby5qcyclM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJGb28uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyY2xhc3MlMjBGb28lMjAlN0IlN0QlNUNuRm9vLnByb3RvdHlwZS5pc0ZvbyUyMCUzRCUyMHRydWUlM0IlNUNuZXhwb3J0JTIwJTdCJTIwRm9vJTIwJTdEJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyYW1kJTIyJTNBJTdCJTIyaWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=).

**If the current behavior is a bug, please provide the steps to reproduce.**

Unsure if this is a bug or a feature request.

**What is the expected behavior?**

Webpack should be able to tree-shake that code. In Three.js we rely on `prototype.isFoo` so this means we'd have to recommend people to use Rollup if they want to produce small bundles.

**Other relevant information:**
webpack version:  5.23.0

**Comment by mrdoob** [comment]
Rollup maintainer had this to say:
https://twitter.com/lukastaegert/status/1363084395960221703

**Comment by sokra** [comment]
There are many edge cases which makes this unsafe. [Rollup is a little more aggressive in optimization](https://rollupjs.org/repl/?version=2.39.0&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMEZvbyUyMCU3RCUyMGZyb20lMjAnLiUyRkZvby5qcyclM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJGb28uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZnVuY3Rpb24lMjBCYXIoKSUyMCU3QiU3RCU1Q25CYXIucHJvdG90eXBlJTIwJTNEJTIwJTdCJTIwc2V0JTIwaXNGb28odiklMjAlN0IlMjBjb25zb2xlLmxvZyglNUMlMjJoZWxsbyU1QyUyMiklMjAlN0QlMjAlN0QlM0IlNUNuJTVDbmNsYXNzJTIwRm9vJTIwZXh0ZW5kcyUyMEJhciUyMCU3QiU3RCU1Q25Gb28ucHJvdG90eXBlLmlzRm9vJTIwJTNEJTIwdHJ1ZSUzQiU1Q25leHBvcnQlMjAlN0IlMjBGb28lMjAlN0QlNUNuJTVDbiU1Q25jbGFzcyUyMEZvbzIlMjAlN0IlN0QlNUNuRm9vMi5wcm90b3R5cGUlMjAlM0QlMjBleHRlcm5hbCUzQiU1Q25Gb28yLnByb3RvdHlwZS5pc0ZvbzIlMjAlM0QlMjB0cnVlJTNCJTVDbmFzc2V0KGV4dGVybmFsLmlzRm9vMiUyMCUzRCUzRCUzRCUyMHRydWUpJTNCJTVDbmV4cG9ydCUyMCU3QiUyMEZvbzIlMjAlN0QlNUNuJTVDbiU1Q25PYmplY3QuZGVmaW5lUHJvcGVydHkoT2JqZWN0LnByb3RvdHlwZSUyQyUyMCU1QyUyMmlzRm9vMyU1QyUyMiUyQyUyMCU3QiUyMHNldCUzQSUyMCgpJTIwJTNEJTNFJTIwJTdCJTIwY29uc29sZS5sb2coJTVDJTIyaGVsbG8lNUMlMjIpJTNCJTIwJTdEJTIwJTdEKSUzQiU1Q24lNUNuY2xhc3MlMjBGb28zJTIwJTdCJTdEJTVDbkZvbzMucHJvdG90eXBlLmlzRm9vMyUyMCUzRCUyMHRydWUlM0IlNUNuZXhwb3J0JTIwJTdCJTIwRm9vMyUyMCU3RCUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE), but webpack usually tries to avoid unsafe optimization.

You can wrap it in a PURE flag instead:

``` js
export const Foo = /*#__PURE__*/ (() => {
  class Foo {}
  Foo.prototype.isFoo = true;
  return Foo;
})();
```

**Comment by sokra** [comment]
class properties work a bit different (they define a property instead of calling a setter) and allow a lot more optimizations:

``` js
class Foo {
  isFoo = true;
}
```
