### ISSUE TITLE
Module concatenation bug in destructuring assignment with default value

### ISSUE THREAD

**Issue by PAkerstrand** [webpack/webpack#12712]
# Bug report

**What is the current behavior?**

When using destructuring assignment in a module, in combination with a default assignment, it can cause the property looked up in the generated code to be different than the one in the source code _(it uses `newName`)_ if there's a identifier collision.

```js
// index.js
import modA from "./module-a";
import modB from "./config";

const { testProp = "defaultValue" } = modB;

modA();
console.log(testProp);
```
```js
// module-a.js

// In the real code, `stats` is read from another Webpack build
// for the client bundle, generated by `@loadable/webpack-plugin`
const stats = { testProp: 'valueFromSomeFile' };

const { testProp } = stats;

export default function printModuleAProp() {
  console.log(testProp);
}
```
```js
// config.js
export default {
  testProp: "configuredValue",
};
```

Generated code:

```js

/******/ (() => { // webpackBootstrap
/******/ 	"use strict";
var __webpack_exports__ = {};

;// CONCATENATED MODULE: ./src/module-a.js
// In the real code, `stats` is read from another Webpack build
// for the client bundle, generated by `@loadable/webpack-plugin`
const stats = { testProp: 'valueFromSomeFile' };

const { testProp } = stats;

function printModuleAProp() {
  console.log(testProp);
}

;// CONCATENATED MODULE: ./src/config.js
/* harmony default export */ const config = ({
	testProp: "configuredValue",
});

;// CONCATENATED MODULE: ./src/index.js



const { src_testProp = "defaultValue" } = config;

printModuleAProp();
console.log(src_testProp);

/******/ })()
;
```

The incorrect part is this line:

```js
const { src_testProp = "defaultValue" } = config;
```

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/PAkerstrand/webpack-concatenation-bug

**What is the expected behavior?**

The generated line should be along the lines of 

```js
const { testProp: src_testProp = "defaultValue" } = config;
```

We think we've narrowed down the bug to this part in `lib/optimize/ConcatenatedModule.js`:

```js
for (const identifier of allIdentifiers) {
	const r = identifier.range;
	const path = getPathInAst(info.ast, identifier);
	if (
		path &&
		path.length > 1 &&
		path[1].type === "Property" &&
		path[1].shorthand
	) {
		source.insert(r[1], `: ${newName}`);
	} else {
		source.replace(r[0], r[1] - 1, newName);
	}
}
```

For the code in our example, the path taken is the `else`-branch, which replaces the name with a new
one, rather than aliasing the variable name

**Other relevant information:**
webpack version:  `^5.22.0`
Node.js version: `v14.15.4`
Operating System: 
```
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H114
```
Additional tools: –

**Comment by alexander-akait** [comment]
Thanks

**Comment by sokra** [comment]
Send a PR.

The AST is a bit different in this case because of the default value. There is a AssignmentPattern in between that need to be handled.

**Comment by PAkerstrand** [comment]
Yeah, I saw that... I’ll try to create a PR
