### ISSUE TITLE
Dynamic import not working with data uri from asset/inline

### ISSUE THREAD

**Issue by Ron-lab** [webpack/webpack#12731]
# Bug report

**What is the current behavior?**
I'm using asset/inline ([Asset modules](https://webpack.js.org/guides/asset-modules/)) to load a javascript file (myfile.js):
webpack.config:
```
      {
        test: /myfile\.js$/,
        type: 'asset/inline',
      }
```
and some other javascript file that imports 'myfile.js':
```
import myFileUri from './myfile';  //This is working as expected 

async init()  {
  const myModule = await import(myFileUri); //This results in "can't find module" error
}
```
It seems the Webpack can't resolve dynamic import from variable even when the variable contains data uri that Webpack generated.
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
I'm aware of the Webpack dynamic import limitations. 
If I set the generated data URI inside the import('data:application/javascript.......') everything works fine!
I would expect Webpack to resolve successfully a data URI that was generated by Webpack when using dynamic import

**Other relevant information:**
webpack version:  5.23.0
Node.js version: 12.18.3
Operating System: Mac OS Catalina
Additional tools:

**Comment by sokra** [comment]
Yes, expressions in `import()` are not supported. What are you trying to do?

Something like this would work:

``` js
const myModule = await import('./myfile');
```

but it this case `asset/inline` doesn't make sense.

If you really want to load a JS as DataURL with native import, this would work: (but I really question why you would want to do that)

``` js
const myModule = await import(/* webpackIgnore: true */ myFileUri);
```

**Comment by Ron-lab** [comment]
@sokra 
I want to do that because I'm working on a Wasm based javascript SDK that should be published as a library on npm.
If it wasn't a library that should be installed by other application, so there is not problem.
The library has few Emscripten generated dependency files: 
`myFile.wasm, myFile.js and myFile.worker.js + SDK main.js.`
So when packing the library and install it by an application, the application `node_modules/my-library` contains these 4 files.
The problem is that when building application with webpack, only SDK main.js is imported by Webpack but the other 3 files are not bundled. Why there are not bundled? because they are assets that are expected to be at the root url address.
So I'm trying to solve this by building my library with a single main.js output, where the 3 dependencies are bundled into the main.js using asset/inline +dataURI.
I'll be happy you hear your feedback. Thanks

**Comment by alexander-akait** [comment]
Can you provide example?

**Comment by alexander-akait** [comment]
I recommend to avoid using `import file from './file.[ext]'` for non JS files, it is not supported by browsers or node, instead please use `new URL('./image.png', import.meta.url)`.

Yes, expression is not supported, if you still need `import`, please use `/* webpackIgnore: true */`

> The problem is that when building application with webpack, only SDK main.js is imported by Webpack but the other 3 files are not bundled. Why there are not bundled? because they are assets that are expected to be at the root url address.

Don't think it is good idea... You can `import` files directly sand avoid this.

Feel free to feedback
