### ISSUE TITLE
Performance improvement of using cache

### ISSUE THREAD

**Issue by cjblomqvist** [webpack/webpack#12738]
I just wanted to say great work with persistent caching. My compile times went from 80s to 10s, which makes a huuuuge difference for me and my team development wise. 

Really looking forward to lazy loading! (I don't dare to try experimental features, but it sounds truly promising!) 

PS. Sorry for bloating the issue tracker.  😊

**Comment by sokra** [comment]
Thanks for your positive feedback.

> I don't dare to try experimental features

You should try it.
