### ISSUE TITLE
How to force watchpack to watch all changes in a subtree?

### ISSUE THREAD

**Issue by gajus** [webpack/webpack#1273]
I have spent a good hour trying to figure out why `webpack --watch` is not picking up changes in certain files.

I have ended up looking at `/lib/node/NodeWatchFileSystem.js`:

``` js
// [..]
NodeWatchFileSystem.prototype.watch = function watch(files, dirs, missing, startTime, options, callback, callbackUndelayed) {
    console.log(files, dirs);
// [..]
```

It showed me that the files that are not being picked up are not in the list of the files that are being watched.

Regardless of the reason why these files are not picked up (I am assuming some sort of dependency resolution logic is not able to detect a dependency or a link is not created at all). How do I configure `watchpack` from `webpack.config.js` to watch all files under a certain path?

**Comment by sokra** [comment]
Propably a loader is not adding the files as dependencies. Which files are not watched? Which loader should load them?

**Comment by gajus** [comment]
There are several loaders that are supposed to load it (based on the extension):

```js
{
    test: /\.js$/,
    exclude: [
        /node_modules/
    ],
    loader: 'babel',
    query: {
        stage: 0
    }
},
{
    test: /\.js$/,
    exclude: [
        /node_modules/
    ],
    loader: 'eslint'
}
```

It loads a whole bunch of `*.js* files, but it does not load certain files.

```
curiosity:actions gajus$ ls -lah
total 16
drwxr-xr-x  4 gajus  staff   136B 21 Jul 19:14 .
drwxr-xr-x  9 gajus  staff   306B 21 Jul 20:22 ..
-rw-r--r--  1 gajus  staff   358B 21 Jul 19:20 TaskTypeActions.js  [not loaded]
-rw-r--r--  1 gajus  staff   464B 21 Jul 19:20 TodoActions.js          [loaded]
```

No obvious reason.
