### ISSUE TITLE
Simplify outputModule:true format

### ISSUE THREAD

**Issue by trusktr** [webpack/webpack#12741]
## Feature request

**What is the expected behavior?**

The output re-creates ES Module bindings inside of ES Modules. There's no point.

**What is motivation or use case for adding/changing the behavior?**

It should just `export` things and it is done.

**How should this be implemented in your opinion?**

For example, instead of having this code in the bundle (with concatenated modules turned on):

```js
// ESM COMPAT FLAG
__webpack_require__.r(__webpack_exports__);

// EXPORTS
__webpack_require__.d(__webpack_exports__, {
  "theThingBeingExported": () => (/* binding */ theThingBeingExported)
});

// ........ concatenated modules at the top level ...........

var __webpack_exports__runGlas = __webpack_exports__.theThingBeingExported;
export { __webpack_exports__theThingBeingExported as theThingBeingExported };
```

it should just be this:

```js
export { theThingBeingExported }
```

Or better yet, if `theThingBeingExported` already has an `export`, just leave it alone:

```js
export function theThingBeingExported() {...}
```

**Comment by trusktr** [comment]
Is this format intentional? Or is it just a matter of time before someone has the time to improve it?

**Comment by sokra** [comment]
> Is this format intentional? Or is it just a matter of time before someone has the time to improve it?

It's an intermediate work in progress state. Eventually this will be change to a direct export.

**Comment by sokra** [comment]
see #2933
