### ISSUE TITLE
Destructured assignment/default value sometimes inverted

### ISSUE THREAD

**Issue by jsg2021** [webpack/webpack#12757]
# Bug report

**What is the current behavior?**
Some destructured assignments are getting rewritten with invalid syntax... the = and : to rename are in the wrong order.

**If the current behavior is a bug, please provide the steps to reproduce.**
I'm not sure how to get this to happen outside of my app, but I have a component that does something like:

```js
import { DataURIs } from '../constants';

const { BLANK_IMAGE } = DataURIs;

function test (data = {}) {
	const {
		src = BLANK_IMAGE,
	} = data;
}
```

and `src` becomes something like `{src = constants_BLANK_IMAGE : src_constants_BLANK_IMAGE}`... which is backwards.

**What is the expected behavior?**
no syntax error.

**Other relevant information:**
webpack version:  5.24.0
Node.js version: 15.8.0
Operating System: 
Additional tools:

**Comment by alexander-akait** [comment]
Duplicate https://github.com/webpack/webpack/issues/12769
