### ISSUE TITLE
Target files on different drive than the output path cause invalid path and error is thrown

### ISSUE THREAD

**Issue by JonWallsten** [webpack/webpack#12759]
# Bug report

**What is the current behavior?**
When providing assets from a different drive than then output path on Windows Compiler.js throws an error and the build fails.
https://github.com/webpack/webpack/blob/972b7f9bd1c608a0ce8794b4bed236cfffe72b2e/lib/Compiler.js#L796

```
// Running this code generates the output below
if (targetFile.match(/\/|\\/)) {
	const fs = this.outputFileSystem;
	console.error('[Compiler.js] Output path: ', outputPath);
	console.error('[Compiler.js] Target file: ', targetFile);
	const dir = dirname(fs, join(fs, outputPath, targetFile));
	console.error('[Compiler.js] Dir: ', dir);
	mkdirp(fs, dir, writeOut);
}
// Output:
[Compiler.js] Output path:  C:\Users\RUNNER~1\AppData\Local\Temp\_karma_webpack_191749
[Compiler.js] Target file:  D:\a\ts-loader\ts-loader\test\execution-tests\3.0.1_projectReferences\lib\tsconfig.tsbuildinfo
[Compiler.js] Dir:  C:\Users\RUNNER~1\AppData\Local\Temp\_karma_webpack_191749\D:\a\ts-loader\ts-loader\test\execution-tests\3.0.1_projectReferences\lib
{ [Error: EINVAL: invalid argument, mkdir 'C:\Users\RUNNER~1\AppData\Local\Temp\_karma_webpack_191749\D:\a\ts-loader\ts-loader\test\execution-tests\3.0.1_projectReferences\lib']
  errno: -4071,
  code: 'EINVAL',
  syscall: 'mkdir',
  path:
   'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\_karma_webpack_191749\\D:\\a\\ts-loader\\ts-loader\\test\\execution-tests\\3.0.1_projectReferences\\lib' } ```
```
A path with multiple drives doesn't seem to be valid on Windows. So just joining the two paths doesn't work.

**If the current behavior is a bug, please provide the steps to reproduce.** 
This only happens when testing `ts-loader` with Github Workflow (seems to be running Microsoft Windows Server 2019), I've been unable to reproduce on two local Windows 10 machines. So it's hard to give steps to reproduce. But happens every time we run the test suite on Github:
https://github.com/TypeStrong/ts-loader/runs/1958905766?check_suite_focus=true

I do have a `webpack` fork as dependency for a `ts-loader` fork where I can reproduce this. That's how I got the log statements and the stack trace leading to `Compiler.js`.

**What is the expected behavior?**
When providing an asset located on another drive than the output path it should not crash.

**Other relevant information:**
webpack version:  5.20.0
Node.js version: 10.x.x/12.x.x/14.x.x
Operating System: Microsoft Windows Server 2019
Additional tools:

**Comment by alexander-akait** [comment]
PR welcome

**Comment by JonWallsten** [comment]
@alexander-akait: I'll fix. I just need to figure out what the best practices is! 😬

**Comment by JonWallsten** [comment]
@alexander-akait: This is more complex than i though:
```
START:
Webpack bundling...
[Compiler.js] Dir:  C:\Users\RUNNER~1\AppData\Local\Temp\_karma_webpack_529363\D\a\ts-loader\ts-loader\test\execution-tests\3.0.1_projectReferences\lib
Target file:  D:\a\ts-loader\ts-loader\test\execution-tests\3.0.1_projectReferences\lib\tsconfig.tsbuildinfo
Target file after replace:  D\a\ts-loader\ts-loader\test\execution-tests\3.0.1_projectReferences\lib\tsconfig.tsbuildinfo
1. C:\Users\RUNNER~1\AppData\Local\Temp\_karma_webpack_529363
2. D:\a\ts-loader\ts-loader\test\execution-tests\3.0.1_projectReferences\lib\tsconfig.tsbuildinfo
{ Error: ENOENT: no such file or directory, open 'C:\Users\RUNNER~1\AppData\Local\Temp\_karma_webpack_529363/D:\a\ts-loader\ts-loader\test\execution-tests\3.0.1_projectReferences\lib\tsconfig.tsbuildinfo'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at stats.toJson.assets.forEach (D:\a\ts-loader\ts-loader\node_modules\karma-webpack\lib\webpack\plugin.js:21:66)
    at Array.forEach (<anonymous>)
    at compiler.hooks.done.tap (D:\a\ts-loader\ts-loader\node_modules\karma-webpack\lib\webpack\plugin.js:16:29)
    at Hook.eval [as callAsync] (eval at create (D:\a\ts-loader\ts-loader\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (D:\a\ts-loader\ts-loader\node_modules\tapable\lib\Hook.js:18:14)
    at emitRecords.err (D:\a\ts-loader\ts-loader\node_modules\webpack\lib\Compiler.js:447:23)
    at Compiler.emitRecords (D:\a\ts-loader\ts-loader\node_modules\webpack\lib\Compiler.js:836:39)
    at emitAssets.err (D:\a\ts-loader\ts-loader\node_modules\webpack\lib\Compiler.js:439:11)
    at hooks.afterEmit.callAsync.err (D:\a\ts-loader\ts-loader\node_modules\webpack\lib\Compiler.js:818:14)
    at Hook.eval [as callAsync] (eval at create (D:\a\ts-loader\ts-loader\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (D:\a\ts-loader\ts-loader\node_modules\tapable\lib\Hook.js:18:14)
    at asyncLib.forEachLimit.err (D:\a\ts-loader\ts-loader\node_modules\webpack\lib\Compiler.js:815:27)
    at D:\a\ts-loader\ts-loader\node_modules\neo-async\async.js:2818:7
    at done (D:\a\ts-loader\ts-loader\node_modules\neo-async\async.js:3522:9)
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path:
   'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\_karma_webpack_529363/D:\\a\\ts-loader\\ts-loader\\test\\execution-tests\\3.0.1_projectReferences\\lib\\tsconfig.tsbuildinfo' }
```

The reason for the error is that `karma-webpack` is trying to read the file after it's written, but with the wrong path since I changed it to not contain `:`
So instead of just fixing the path when the asset is emitted, I need to change the path's source so when stats are returned the path is changed there as well:
```
apply(compiler) {
    this.compiler = compiler;

    // webpack bundles are finished
    compiler.hooks.done.tap('KW_WebpackPlugin', (stats) => {
      // read generated file content and store for karma preprocessor
      this.controller.bundlesContent = {};
      stats.toJson().assets.forEach((webpackFileObj) => {
        // If webpackFileObj.name has an absolute path on Windows we need to clean up the drive letter to avoid getting an error when a dir is created for this path
        console.error('1.', compiler.options.output.path);
        console.error('2.', webpackFileObj.name);
        const filePath = `${compiler.options.output.path}/${webpackFileObj.name.replace(/(a-z):/gi, '$1')}`;
        this.controller.bundlesContent[webpackFileObj.name] = fs.readFileSync(
          filePath,
          'utf-8'
        );
      });

      // karma refresh
      this.karmaEmitter.refreshFiles();
    });
  }
```

**Comment by alexander-akait** [comment]
So nothing to fix on webpack side, bug in `karma-webpack`

**Comment by JonWallsten** [comment]
> So nothing to fix on webpack side, bug in `karma-webpack`

That depends. Are you allowed to emit assets with a different drive than the output? 
If the answers in yes: Then it's a bug in Webpack since `mkdirp` throws an error. It should then be fixed with some solution.
If the anwer is no: Then it should not be possible to emit a file on a different drive and `emitAssets` and an error should be throws when you do it.

The solution for 'yes' could be that as soon as you emit a file on a different drive then the output path the path is corrected and whenever someone asks for the assets/stats/etc the path would be without the colon.

In the example above everything would work if stats contained the corrected path. I did a quick fix where I just fixed the path when writing the file, I will obviously need to fix that as soon as I have time.

The easy solution is of course to not allow this and throw a real error explaining why. But since it can be fixed pretty easily, why not?

**Comment by alexander-akait** [comment]
Yep, but, let's fix it

**Comment by JonWallsten** [comment]
> Yep, but, let's fix it

I'll try to do it this weekend.

**Comment by JonWallsten** [comment]
@alexander-akait: I was trying to find the root-cause of the issue, but since it's only reproducible on GitHub Workflow (Windows 2019 server) it takes forever to debug. Had to take a pause from it. I don't know why we're sending additional assets in just this case. Also it would be hard to set up an easy repro since you need Windows and multiple hard drives/partitions. 

Something for you and maybe @sokra to think about is: 
What should happen when the dist is on another drive than the target file?
As long as the file is part of a bundle it's fine since the code gets extracted anyways, but we do have additional resources as well.

Some examples:
```
dist: c:\dist
source: c:\project
```
In this case additional assets in `c:\project` would be located in `c:\dist\project` since `c:\` is the common base. All good.
But in this scenario:  
```
dist: c:\dist
source: d:\project
```
There is no common base. So the path ends up `c:\dist\d:\project` which is an invalid path on Windows.
The easiest solution is of course to replace `d:` with `d` when you add the asset, so that it's treated with it's new path in Webpack. I tried to do this at the time of the writing of the file, but that doesn't work since the real path (with `d:`) is sent back with the stats. So an idea would be to fix this in the emitAsset function maybe. That would however not fix the issue if someone decides to add the assets the old way by just adding it to the array of assets, like `ts-loader` does before my PR. So there might be a better place to do this?

**Comment by alexander-akait** [comment]
I don't know there is the problem, please provide reproducible test repo and step to reproduce, otherwise won't fix, sorry

**Comment by JonWallsten** [comment]
@alexander-akait: I will take a look at the Node side of the problem. Joining two paths on different drives and get a valid url. What I'm unsure about is if this should be done by the user or fixed in Webpack. I'll get back to you shortly.

**Comment by alexander-akait** [comment]
I tested right now on windows, my program on `D:\`, my config
```js
module.exports = {
    mode: 'development',
    devtool: false,
    entry: './entry.js',
    output: {
        path: 'C:\\test',
        filename: '[name].js',
    },
    module: {
        rules: [
            {
                test: /\.txt$/,
                type: 'asset/resource',
            },
        ],
    },
};
```

And all works fine. 

Here problem what the `targetFile` should not be absolute. You output files relative to `output.path`, so using `targetFile` as absolute is not safe

**Comment by JonWallsten** [comment]
Yeah, preferably one should not add assets with an absolute path. But we can't fix it with path.relative either since it doesn't work with two separate drives. So I guess we need to find where does assets are emitter and fake a valid path then?

**Comment by alexander-akait** [comment]
> Yeah, preferably one should not add assets with an absolute path

You **should not** pass absolute paths, it is unsafe, it is bad for cache, it is bad for compatibility.

> But we can't fix it with path.relative either since it doesn't work with two separate drives.

Not related to webpack.

> So I guess we need to find where does assets are emitter and fake a valid path then?

No. I don't think we should do it and it is unsafe, because you should not use `absolute` paths, there is no problems, please open an issue in plugin/loader there used absolute paths, it is wrong.

**Comment by JonWallsten** [comment]
> > Yeah, preferably one should not add assets with an absolute path
> 
> You **should not** pass absolute paths, it is unsafe, it is bad for cache, it is bad for compatibility, it it bad for different os.
> 
> > But we can't fix it with path.relative either since it doesn't work with two separate drives.
> 
> Not related to webpack.
> 
> > So I guess we need to find where does assets are emitter and fake a valid path then?
> 
> No. I don't think we should do it and it is unsafe, because you should not use `absolute` paths for emitting assets, please open an issue in plugin/loader there used absolute paths, it is wrong.

I meant in ts-loader. Since the issue is only apparent when using project references it might be the doing of TypeScript. So I guess we need to make sure that the paths are relative to the working directory so they can be joined with the output folder. I'll start digging. But your are fine with the fact that Webpack crashes without a relevant error message when you provide assets with an absolut path?

**Comment by alexander-akait** [comment]
Let's wait answer from @sokra I send a simple fix and tested manually

**Comment by JonWallsten** [comment]
That's an interesting approach. It's weird that the assets will be written back in the source folder, but since that's the path emitted, it's correct. And it will not crash. Besides, when you see the compiled assets in your source folder you will definitely know something is wrong in your setup, which is good. Then the user can investigate why they emit absolute paths.

**Comment by alexander-akait** [comment]
bump

**Comment by Josmithr** [comment]
Bump :)

**Comment by sschmidTU** [comment]
This is still a problem, and it wasn't in webpack 4 (using karma-webpack 4).
Isn't a possible solution adding a regex replacement in Compiler.js (see top post) to always just take the second occurence of a drive lettered file path (`[A-Z]:\\.*$` or something)?

This problem should be reproducible with this PR (on a Windows machine with the project installed on a secondary drive letter):
https://github.com/opensheetmusicdisplay/opensheetmusicdisplay/pull/1119

Run `npm install; npm test`

**Comment by adanski** [comment]
Is there any straightforward workaround? Can I somehow set my TMP variable exclusively for Nodejs?

**Comment by buchatsky** [comment]
Workaround that worked for me:
karma.conf.js
```
    webpack: {
      // webpack configuration
      output: {
        path: path.join(__dirname, 'temp'),
      }
    ...
    }

```
