### ISSUE TITLE
Corner-case with method shorthand syntax

### ISSUE THREAD

**Issue by char0n** [webpack/webpack#12767]
# Bug report

**What is the current behavior?**

The behavior is documented here and affects webpack@4 only: https://github.com/babel/babel/discussions/12874. I thought originally that it was babel bug, but seems like a webpack@4 one. webpack@5 doesn't use `Object` call so it doesn't manifest with this issue. I'm reporting this on webpack@4 as CRA is still using it.

**If the current behavior is a bug, please provide the steps to reproduce.**

**module.js**
```js
export const symbol = () => {};
```

**index.js**
```js
import { symbol } from './module';

var a = {
    Object: function Object() {
        symbol('test');
        return {};
    }
}

export default a;
```

Bundled code fragment
```js
// some code before
var a = {
    Object: function Object() {
        Object(_module__WEBPACK_IMPORTED_MODULE_0__["symbol"])('test');
        return {};
    }
}
// some code after
```

As you can see this causes obvious recursion of resulting code and `Maximum call stack size exceeded error`.

**What is the expected behavior?**

Proper transpilation as in webpack@5 and no recursion.

```js
// some code before
var a = {
    Object: function Object() {
        (0,_module__WEBPACK_IMPORTED_MODULE_0__.symbol)('test');
        return {};
    }
}
// some code after
```

**Other relevant information:**
webpack version:  4.46.0
Node.js version: 14.1.0
Operating System: Linux Mint 20.1
Additional tools:

**Comment by alexander-akait** [comment]
Sorry, webpack v4 is deprecated, we strong recommend to update to v5, unfortunately this cannot be fixed in v4, this fix is likely to create a lot of regressions, so we try not to touch at all v4, sorry again
