### ISSUE TITLE
Ws does not work in the browser. Browser clients must use the native WebSocket object

### ISSUE THREAD

**Issue by dmitrysurkin** [webpack/webpack#12763]
My node js application uses a library 'ws'. I'm trying to make a build. An error is thrown in the bundle.

Webpack.config.js
`const path = require('path');

module.exports = {
    entry: path.resolve(__dirname, 'index.js'),
    output: {
        filename: 'index.js',
        path: path.resolve(__dirname, 'build')
    },
    module: {
        rules: [
          {
            test: /\.(js)$/,
            exclude: /node_modules/,
            use: ['babel-loader']
          }
        ]
      },
    resolve: {
        modules: ['node_modules'],
        fallback: {
            zlib: false
        },
        alias: {
            'huobi': path.join(__dirname, 'src', 'huobi'),
        },
    },
};`

![Screenshot_9](https://user-images.githubusercontent.com/57535916/108860908-7cc87b80-7610-11eb-8b44-2490f0817f2e.jpg)

Error: ws does not work in the browser. Browser clients must use the native WebSocket object

**Comment by dmitrysurkin** [comment]
The problem is solved by changing the environment in webpack.config.js

target: 'node',

**Comment by xternet** [comment]
If it didn't completely solve the problem, then:
```
  target: "node",
  externals: {
    ws: "commonjs ws",
  },
```
