### ISSUE TITLE
Module concatenation produces invalid syntax when using object destructuring with a default

### ISSUE THREAD

**Issue by Hypnosphi** [webpack/webpack#12769]
# Bug report

**What is the current behavior?**
**If the current behavior is a bug, please provide the steps to reproduce.**

See reproduction: https://github.com/Hypnosphi/webpack-5-repro

Here’s the output with invalid syntax:

```js
// CONCATENATED MODULE: ./src/b.js
function b_noop() {}

function B({foo = noop: b_noop}) {}
```

**What is the expected behavior?**

```js
// CONCATENATED MODULE: ./src/b.js
function b_noop() {}

function B({foo = b_noop}) {}
```

**Other relevant information:**
webpack version:  5.24.0
Node.js version: 12.20.2
Operating System: Linux, macOS
Additional tools: no

**Comment by bpowers** [comment]
I'm also seeing this, but don't have a reproduction (downgrading to 5.23 is my current workaround)

**Comment by alexander-akait** [comment]
Other example https://github.com/webpack/webpack/issues/12757
