### ISSUE TITLE
How to specify @babel/register for webpack 5

### ISSUE THREAD

**Issue by huiyifyj** [webpack/webpack#12772]
For webpack 4, I can use es6 to edit configuration file by using `--config-register` / `-r @babel/register` flag.
Migrate to webpack 5, it doesn't work. It looks the flag be not supported.

**Comment by alexander-akait** [comment]
You don't need it, webpack-cli automatically apply `@babel/register` on `.babel.js` files, anyway if you still have problems with migration please open an issue in `webpack-cli` repo

**Comment by huiyifyj** [comment]
> You don't need it, webpack-cli automatically apply `@babel/register` on `.babel.js` files, anyway if you still have problems with migration please open an issue in `webpack-cli` repo

Thanks for your reply. 👍
