### ISSUE TITLE
When can i get the cache file while i start filessystem

### ISSUE THREAD

**Issue by Idletalk** [webpack/webpack#12786]
hi, i have a question about: i want to get the cache file when start filesystem. i try to use the hook about "done" like this  
compiler.hooks.done.tap('', () => {
  // get the cache filesystem
})
but i field. 
which hook in compiler or compiler.cache can i use to get the filesystem cache?

**Comment by alexander-akait** [comment]
You **should not touch** cache file, please use `Discussions` for questions
