### ISSUE TITLE
Package name with slashes (e.g. scoped) influencing source map path

### ISSUE THREAD

**Issue by ASDFGerte** [webpack/webpack#12783]
**Bug report**
**What is the current behavior?**
If the package name contains slashes, e.g. by having a scope `@scope/name`, the part after the slash bleeds into the source map path, as in, the path where a debugger searches for the file. This causes all breakpoints in the original source files to be unbound. Maybe i am making a silly mistake, and i also can't be sure, that it's not the fault of vscode, or chrome, but webpack seems to be right in the middle of things.

**If the current behavior is a bug, please provide the steps to reproduce.**
As far as i can see, just run webpack with `devtool: 'inline-source-map'`, have slashes in the name of `package.json` (for testing, it can even be an invalid name that just contains one or more slashes), and try to debug with vscode and chrome.

Here is a repo with the issue, that uses yarn, in a minimal monorepo, that includes a minimal expressjs webserver. What happens in visual studio code is, that all breakpoints in the source file will be unbound when running. However, removing all slashes from the package name (removing the scope), breakpoints work fine. Yarn cache isn't included, so run `yarn install` first.

https://github.com/ASDFGerte/webpacksourcemapissue

I've found, that a sign of the issue is chrome displaying a subfolder with the part after the first slash, in sources. It is possible to open chrome devtools, view the source there, set a breakpoint, and hit it. A file will open in visual studio code, with the source, and the hit breakpoint. Hovering over that tab will display a path, where everything from the package name after the first slash is inserted after the root folder.

Here is a screenshot of this, coming from a different project, with an invalid package name as test, but the same applies for scoped ones. It's just in case you know what this is immediately, so you don't even need the repo above:

https://i.imgur.com/Hzb1aot.png

While the repo uses yarn, and multiple workspaces, i could also see the behavior of chrome putting the package name as a subfolder name in sources on an extremely basic npm setup, that just built the bundle, and didn't serve. I simply opened the html manually with chrome, and checked the devtools.

**What is the expected behavior?**
scope from `package.json` should be irrelevant. An invalid package name with multiple slashes may potentially cause an error, but not silently break debugging.

**Other relevant information:**
webpack version:  5.24.2
Node.js version: v15.6.0
Operating System: windows 7

**Comment by alexander-akait** [comment]
Do you expect have `web` in the sources URL? Can you try `output.devtoolNamespace: 'web'`?

**Comment by ASDFGerte** [comment]
Yes, `output.devtoolNamespace: 'no_slashes_here'` fixes the issue, by just using something other than package name, thanks. Sorry for bothering, i should probably read the entire webpack docs from start to finish one day. Stackoverflow couldn't help for days.

I am still a bit confused, why a default of package name including slashes was chosen, but i guess I can wonder about that after some more research on the topic.

Thanks again :)
