### ISSUE TITLE
Module Federation remotes do not load when using webworker target

### ISSUE THREAD

**Issue by joeblynch** [webpack/webpack#12780]
**Do you want to request a *feature* or report a *bug*?**

This appears to be a bug.

**What is the current behavior?**

When using `target: 'webworker'`, for a webworker script which uses `ModuleFederationPlugin` to load a remote module, the error `Uncaught (in promise) DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'XXX' failed to load.` occurs when attempting to import from the remote.

It appears that both the `importScripts` chunk loader and the `remotes loading` chunk loader attempt to load the remote module, with the `importScripts` chunk loader erroneously attempting to load the remote from a nonexistent local file.

Specifically, the [ensure chunk](https://github.com/joeblynch/module-federation-webworker-test/blob/master/packages/main/dist/main.js#L115-L126) portion of the runtime iterates through each registered chunk loader:
```javascript
/* webpack/runtime/ensure chunk */
(() => {
	__webpack_require__.f = {};
	// This file contains only the entry chunk.
	// The chunk loading function for additional chunks
	__webpack_require__.e = (chunkId) => {
		return Promise.all(Object.keys(__webpack_require__.f).reduce((promises, key) => {
			__webpack_require__.f[key](chunkId, promises);
			return promises;
		}, []));
	};
})();
```

The `remotes loading` [here](https://github.com/joeblynch/module-federation-webworker-test/blob/master/packages/main/dist/main.js#L213-L255) requests the remote module, but `importScripts` chunk loader [here](https://github.com/joeblynch/module-federation-webworker-test/blob/master/packages/main/dist/main.js#L334-L339) throws an exception while also trying to load the chunk.

Configuring the main webworker script to [not use target: 'webworker'](https://github.com/joeblynch/module-federation-webworker-test/blob/master/packages/main/webpack.config.js#L6-L7) prevents this issue. However, this replaces the `importScripts` chunk loader with a `JSONP` loader, which I'd expect would prevent chunk splitting from working.

**If the current behavior is a bug, please provide the steps to reproduce.**

Minimal reproduction repo [is available here](https://github.com/joeblynch/module-federation-webworker-test).

**NOTE:** This repo uses `patch-package` to include the fix from https://github.com/webpack/webpack/pull/12612/, to resolve https://github.com/webpack/webpack/issues/12577, which appears to impact webworker module federation remotes in addition to WASM modules.

1. Run `yarn` to install dependencies.
2. Run `yarn serve` to serve prebuilt dist (or `yarn start` to serve from source).
3. Load http://localhost:3001, the console should show the error `Uncaught (in promise) DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http://localhost:3001/webpack_container_remote_remote_remote-logger.js' failed to load.`

**What is the expected behavior?**

Remote module is loaded without an error. In the above minimal reproduction repo, the message `Hello from the remote logger` should appear on the page.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

webpack: v5.24.2

**Comment by alexander-akait** [comment]
bump

**Comment by joeblynch** [comment]
Closing as I see this has been resolve as of `v5.48.0`.
