### ISSUE TITLE
Many typescript definitions not exported.

### ISSUE THREAD

**Issue by ktalebian** [webpack/webpack#12796]
## Feature request

**What is the expected behavior?**
I'm upgrading from webpack 4 and by far the most difficult bit has been the numerous missing type definitions that were previously exported in https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/webpack/index.d.ts. For example,

* `CallbackWebhook`
* `StatsError` (and other stats compilation results)
* Different sub configurations of `Configuration` 

Can we export these as well and make them consistent with webpack 4?

**What is motivation or use case for adding/changing the behavior?**

To export more of the definition to keep them the same as webpack 4.

**How should this be implemented in your opinion?**
Type definition to be updated to allow for missing types to be exported.

**Are you willing to work on this yourself?**
yes

**Comment by alexander-akait** [comment]
Please report them here https://github.com/webpack/webpack/issues/11630
> CallbackWebhook

CallbackWebhook doesn't exists in types, neither `DefinitelyTyped` nor `webpack` v5 types, something internal on your side  

> StatsError (and other stats compilation results)

Why do you need this type?

> - Different sub configurations of Configuration

Please describe them in provided issues
