### ISSUE TITLE
can not success

### ISSUE THREAD

**Issue by zfxj** [webpack/webpack#12798]
# Bug report
ERROR in ./node_modules/@babel/runtime/helpers/esm/createSuper.js 1:0-46
Module not found: Error: Can't resolve './getPrototypeOf' in '/Users/xujun/Documents/workSpace/founder/yjzh/YJSHWeb/node_modules/@babel/runtime/helpers/esm'
Did you mean 'getPrototypeOf.js'?
BREAKING CHANGE: The request './getPrototypeOf' failed to resolve only because it was resolved as fully specified
(probably because the origin is a '*.mjs' file or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
 @ ./node_modules/rc-trigger/es/index.js 6:0-66 38:17-29
 @ ./node_modules/rc-cascader/es/Cascader.js 40:0-33 386:35-42
 @ ./node_modules/rc-cascader/es/index.js 1:0-34 2:15-23
 @ ./node_modules/antd/es/cascader/index.js 23:0-37 371:48-58
 @ ./src/container/handle/leftMenu/report/templateManage/addEditTemplateManage/addEditTemplateManage.js 17:0-41 374:38-47
 @ ./src/router/router.js 105:11-114
 @ ./src/router/index.js 33:0-30 46:52-58
 @ ./src/main.js 28:0-40 87:40-50

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  5.24.2
Node.js version: v14.15.1
Operating System:  mac
Additional tools:

**Comment by sokra** [comment]
update your babel version, this has been fixed a while ago
