### ISSUE TITLE
Typescript: How to add a new compilation hook on a readonly hook?

### ISSUE THREAD

**Issue by ktalebian** [webpack/webpack#12795]
How do I go about adding a new hook to webpack compiler? In webpack 4 I could do something like

```ts
interface CustomHooks extends CompilerHooks {
  tsCompiled: SyncHook<string[], string[]>;
}

interface CustomCompiler extends Compiler {
  hooks: CustomHooks;
}

const compiler = webpack(config) as CustomCompiler;
compiler.hooks.tsCompiled = new SyncHook(['warnings', 'errors']);
```

The guide [here](https://webpack.js.org/api/plugins/#custom-hooks ) says you can add a custom hook by doing `compiler.hooks.custom = ...` but looking at the code, hooks is frozen https://github.com/webpack/webpack/blob/master/lib/Compiler.js#L120. Indeed, if I try to add extend this anyway by using `// @ts-ignore`, I get

> Failed to create a webpack compiler: Cannot add property tsCompiled, object is not extensible

So how do you go about extending hooks?

**Comment by sokra** [comment]
This is intentional: https://webpack.js.org/blog/2020-10-10-webpack-5-release/#hook-object-frozen

To offer a custom hook you need to do the following:

Create a module-scope weak map for compilation hooks:

```
const compilationHooks = new WeakMap<Compilation, MyHooks>();

interface MyHooks {
  custom: SyncHook<[number, string]>
}
```

Create a static method on your plugin:

```
static getCompilationHooks(compilation: Compilation) : MyHooks {
  let hooks = compilationHooks.get(compilation);
  if(hooks === undefined) {
    compilationHooks.set(compilation, hooks = {
      custom: new SyncHook()
    });
  }
  return hooks;
}
```

Call hooks like this in your plugin:

```
const hooks = MyPlugin.getCompilationHooks(compilation);

hooks.custom.call(1, "hello");
```

Other plugins could access your custom hooks too:

```
import MyPlugin from "my-plugin";

const hooks = MyPlugin.getCompilationHooks(compilation);

hooks.custom.tap("OtherPlugin", (n, s) => {
  // magic
});
```

**Comment by sokra** [comment]
see https://github.com/jantimon/html-webpack-plugin#events for an example

**Comment by alexander-akait** [comment]
Answer above, feel free to feedback

**Comment by EECOLOR** [comment]
It might be a good idea to change the documentation to reflect this: https://webpack.js.org/api/plugins/#custom-hooks

**Comment by alexander-akait** [comment]
@EECOLOR Yep, can you open an issue?
