### ISSUE TITLE
AssertionError: path must be a string after upgrade from <=1.10.1 to 1.10.3

### ISSUE THREAD

**Issue by warbrett** [webpack/webpack#1280]
Nothing has changed in webpack config and versions 1.9.12 and 1.10.1 Work fine. 
```
assert.js:93
  throw new assert.AssertionError({
        ^
AssertionError: path must be a string
    at Module.require (module.js:362:3)
    at require (module.js:380:17)
    at module.exports (/Users/brett/Documents/projects/myproject/node_modules/webpack/bin/convert-argv.js:61:19)
    at Object.<anonymous> (/Users/brett/Documents/projects/myproject/node_modules/webpack/bin/webpack.js:54:40)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
```

**Comment by taion** [comment]
I'm seeing this as well. The last working version was v1.10.1. The first broken version was v1.10.2.

**Comment by taion** [comment]
It looks like this might be specifically an issue with files of the form `webpack.config.babel.js`, or others that use extensions. If I define a `webpack.config.js` per:

```js
require('babel/register');
module.exports = require('./webpack.config.babel');
```

then everything works again.

**Comment by warbrett** [comment]
Using webpack.cofig.babel as well. So that must be it

**Comment by taion** [comment]
It looks like the failure is a consequence of updating `interpret` from 0.5.x to 0.6.x in https://github.com/webpack/webpack/commit/bf3ea10f3cc988c78627498f81a188f796329e82.

**Comment by phated** [comment]
Blindly updating to interpret 0.6 was not a good idea, as we changed the structure of the object exported to handle fallbacks and other things.  This was handled by the main consumer (liftoff) changing the way it used the file.

**Comment by taion** [comment]
Would it be possible to roll back to 0.5.x for the time being?

**Comment by mtscout6** [comment]
Looks like there may be a possible fix in #1283

**Comment by taion** [comment]
That fixes the issue I see.

@sokra How long until the next release with this fix comes out?

**Comment by bebraw** [comment]
Closing given #1283 was merged.

@warbrett Please open again if you still see the issue.
