### ISSUE TITLE
Single runtime chunk incompatible with library output in Webpack 5

### ISSUE THREAD

**Issue by keeganstreet** [webpack/webpack#12801]
# Bug report

**What is the current behavior?**

Using the following config works in Webpack 4 but not Webpack 5:

```js
module.exports = {
  output: {
    library: "A",
  },
  optimization: {
    runtimeChunk: "single"
  },
};
```

I would expect the module to be assigned to a variable `A`, but in Webpack 5 `A` is undefined.

**Webpack 4 output:**

```js
var A =
(window["webpackJsonpA"] = window["webpackJsonpA"] || []).push([["main"],{
  ...
},[["./src/index.js","runtime"]]]);
```

**Webpack 5 output:**

```js
var A;
(self["webpackChunkA"] = self["webpackChunkA"] || []).push([["main"],{
  ...
},
0,[["./src/index.js","runtime"]]]);
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Smallest reproducible bug demo: https://github.com/keeganstreet/webpack-5-library

**What is the expected behavior?**

The module should be assigned to `A`.

**Other relevant information:**
webpack version:  5.24.2
Node.js version: v14.4.0
Operating System: Mac OS
Additional tools: N/A

**Comment by keeganstreet** [comment]
Closing as this seems to be a duplicate of https://github.com/webpack/webpack/issues/12742

**Comment by keeganstreet** [comment]
I will re-open and let you decide if this is a dupe. The steps to reproduce are slightly different so I don't know for sure whether its the one bug causing both issues.

**Comment by alexander-akait** [comment]
It is the same problem, duplicate, yes steps are different but the problem is the same

**Comment by alexander-akait** [comment]
Just downgrade webpack to v5.21.2

**Comment by keeganstreet** [comment]
OK thanks
