### ISSUE TITLE
Unable to provide NodeJS APIs as externals in Webpack 5

### ISSUE THREAD

**Issue by keeganstreet** [webpack/webpack#12802]
# Bug report

**What is the current behavior?**

Targeting NodeJS, and marking a NodeJS API such as `http` as an external does not work in Webpack 5.

For example, given the following config:

```js
module.exports = {
  mode: "development",
  target: "node",
  externals: {
    http: "external_http"
  }
};
```

I would expect output to contain something like this (and this is what Webpack 4 provides):

```js
"http":
  (function(module, exports) {
    module.exports = external_http;
  })
```

But Webpack 5 does not apply the external at all, resulting in output like:

```js
"http":
  ((module) => {
    module.exports = require("http");
  })
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Smallest reproducible bug demo: https://github.com/keeganstreet/webpack-5-library/tree/broken-externals

**What is the expected behavior?**

If `http` is marked as an external of `external_http`, then `require("http")` should be replaced with `external_http`.

**Other relevant information:**
webpack version:  5.24.2
Node.js version: 14.4
Operating System: Mac OS
Additional tools:

**Comment by alexander-akait** [comment]
Fix https://github.com/webpack/webpack/pull/12803

**Comment by keeganstreet** [comment]
Thank-you @alexander-akait !

**Comment by alexander-akait** [comment]
Fixed https://github.com/webpack/webpack/pull/12803
