### ISSUE TITLE
Lack of feedback or errors thrown when Webpack fails on "export from" babel style

### ISSUE THREAD

**Issue by shamilovtim** [webpack/webpack#12809]
# Bug report

**What is the current behavior?**
There is a style of exporting which some applications have adopted and is supported by babel:
https://github.com/tc39/proposal-export-ns-from

When Webpack encounters this style of exporting, it breaks opaquely, does not throw any error messages and continues onward without notifying the user that it's broken.

**If the current behavior is a bug, please provide the steps to reproduce.**
- Inside of an index.js file use the `export * as someIdentifier from "someModule"` supported by babel
- Webpack will neither compile the file nor tell the user that there's an error

**What is the expected behavior?**
If Webpack cannot handle the export style `export _ from _`  then it should throw an error message telling the user that there's an error 

**Other relevant information:**
webpack version: ^4.x latest
Node.js version: 14.4.0
Operating System: macOS Big Sur
Additional tools: Storybook

**Comment by alexander-akait** [comment]
Fixed in v5, you need update webpack version, sorry, we can't back port it
