### ISSUE TITLE
Exif data stripping in asset modules

### ISSUE THREAD

**Issue by dakotaewigman** [webpack/webpack#12806]
Add a param to delete exif data from images using asset modules

**What is the expected behavior?**
Add a parameter to asset modules that will strip metadata (iptc, exif, etc) from images 

**What is motivation or use case for adding/changing the behavior?**
While it's normally preferable to avoid checking in files with metadata into the codebase altogether. If forgotten, it would be good to have a way to automatically prevent photos with metadata from being deployed publicly.

**How should this be implemented in your opinion?**
param for asset modules

**Are you willing to work on this yourself?**
No

**Comment by alexander-akait** [comment]
You need to implement loader/plugin to achieve this, sorry parsing images out of scope webpack, anyway you can look at https://github.com/webpack-contrib/image-minimizer-webpack-plugin/, most of imagemin plugins do it
