### ISSUE TITLE
webpack --watch fails silently when fs.inotify.max_user_watches is exceeded

### ISSUE THREAD

**Issue by brotchie** [webpack/webpack#1281]
### Docker container configuration
- Webpack 1.10.3
- Node v0.10.25
- Ubuntu 15.04
### Host configuration
- Docker 1.0.1
- Ubuntu 14.04
### Issue

Running `webpack --watch` in docker container successfully performs one build and then exits with exit code 0 (success).
### Expectation

Some kind of error code and a return code != 0 if max_user_watches is exceeded.
### Workaround

Increasing `/proc/sys/fs/inotify/max_user_watches` on the host system fixes the problem.

**Comment by muka** [comment]
:+1:  thank you. An error message would be helpful

**Comment by prograhammer** [comment]
I had this exact same problem. I do some frontend local dev work on my Linux Mint (Ubuntu 16.04) machine and webpack dev-server hot reloading would just silently stop. I can also confirm that updating the `/etc/sysctl.conf` file to have the line `fs.inotify.max_user_watches=1048576` has fixed the problem so far.

**Comment by SpaceK33z** [comment]
Moved to https://github.com/webpack/watchpack/issues/46
