### ISSUE TITLE
How to use ModuleGraph Api in Webpack5 ?

### ISSUE THREAD

**Issue by Edge00** [webpack/webpack#12811]
I'm trying to visit `this._module.issuer.resource` in my own loader

```js
module.exports = function (content) {
  const requester = this._module.issuer.resource
  // other stuffs
}
```

However i got `[DEP_WEBPACK_MODULE_ISSUER] DeprecationWarning: Module.issuer: Use new ModuleGraph API
`

But how should i use ModuleGraph API to visit issuer?

**Comment by alexander-akait** [comment]
Please use Discussions for questions, answer:
```js
const issuer = this._compilation.moduleGraph.getIssuer(this._module);

// Don't forget issuer can be empty when no issuers (i.e. entrypoint)
if (issuer) {
  console.log(issuer.resource);
}
 ```

**Comment by Edge00** [comment]
Sorry. Thank you!
