### ISSUE TITLE
Node modules source maps specifying location without providing source are incorrectly mapped

### ISSUE THREAD

**Issue by olee** [webpack/webpack#12814]
# Bug report

**What is the current behavior?**
I have an issue with source map locations of node modules in my monorepo project (it does not seem that the monorepo is the cause here - just FYI).

I am using the npm package `serializr`, which is shipped with source maps.
[Those source maps](https://pastebin.com/BSj9hjUM) specify file locations which do not exist, because the sourceContent is not included in the npm package.

Some basic information
| Information | |
|-|-|
| Monorepo root | E:/dev/myProject/web |
| Project root | /packages/@myproject/frontend/
| Imported file location | /node_modules/serializr/lib/serializr.es.js |
| Source map location | /node_modules/serializr/lib/serializr.es.js.map |

When this `serializr` package is now included in a chunk, webpack seems to include the source locations as-is, resulting in the following output:
```json
{
  "file": "static/js/698.chunk.js",
  "sources": [
    "E:/dev/myProject/web/packages/@myProject/src/api/createSimpleSchema.ts",
    "E:/dev/myProject/web/packages/@myScope/src/utils/invariant.ts",
    "...snip..."
  ],
  "sourcesContent": [
     null,
     null,
     "...snip..."
  ],
  "mappings": "..snip...",
  "sourceRoot": ""
}
```

This prevents proper debugging of the library.

However, even after copying the sources to the correct location, it still does not work.
For a test I logged the source map info passed to `devtoolModuleFilenameTemplate` function in the output config and received this output:
```json
{
  "identifier": "../src/api/createSimpleSchema.ts",
  "shortIdentifier": "../src/api/createSimpleSchema.ts",
  "resource": "../src/api/createSimpleSchema.ts",
  "resourcePath": "../src/api/createSimpleSchema.ts",
  "absoluteResourcePath": "E:\\dev\\myProject\\web\\packages\\@myProject\\src\\api\\createSimpleSchema.ts",
  "allLoaders": "",
  "query": "",
  "moduleId": "",
  "hash": "bac7",
  "namespace": "@dirico/frontend"
}
```

So the bug that webpack seems to produce here is the incorrect `absoluteResourcePath`, which should be `E:\\dev\\myProject\\web\\node_modules\\serializr\\src\\api\\createSimpleSchema.ts`.

Also, is there any way to tell webpack to ignore maps which have missing sources, so that the browser debugger does not try to pick them up?

**If the current behavior is a bug, please provide the steps to reproduce.**
I will try to provide a minimal reproduction case soon

**What is the expected behavior?**
The source map location should be handled relative to the node module location, so that `absoluteResourcePath` points to the src directory within the node module.

**Other relevant information:**
webpack version:  5.24.2
Node.js version: v12.16.1
Operating System: Win10

**Comment by alexander-akait** [comment]
> Also, is there any way to tell webpack to ignore maps which have missing sources, so that the browser debugger does not try to pick them up?

How you pass source maps to webpack? No because we don't check `sources`. Do you use `source-map-loader`?

Yes please create minimum reproducible test repo, I don't see problems here...

**Comment by olee** [comment]
I'm using cheap-module-source-map and I can understand that webpack might not check the sources specified in the package's source map file.
Ideally, I would like to just completely disable loading of source maps for my node modules and rather step the unmapped javascript instead of having to deal with missing source maps and this path issue.

The main issue I have here is the source map location of the npm package not being handled relative to the npm package, but instead to the generated bundle files as it seems
`"absoluteResourcePath": "E:\\dev\\myProject\\web\\packages\\@myProject\\src\\api\\createSimpleSchema.ts",`
If this path was not incorrect, I would be able to provide the proper sources to debug this code at least.

As for a minimal reproducible test repo, I will try to create one soon, so that this can be verified properly.

**Comment by alexander-akait** [comment]
> Ideally, I would like to just completely disable loading of source maps for my node modules and rather step the unmapped javascript instead of having to deal with missing source maps and this path issue.

webpack by default do not load external source maps, so I want to check which plugin/loader do it and how we can handle it

**Comment by olee** [comment]
So webpack itself does not pass those around?

The interesting thing is that this only breaks when a npm package provides sourcemaps itself.

I used this debug function to log files where the sourcemap was not found and got quite some results.
```ts
const resolveDevtoolModuleFilename = (info: DevtoolModuleFilenameTemplateInfo) => {
    const absolutePath = path.resolve(info.absoluteResourcePath).replace(/\\/g, '/');
    if (!fs.existsSync(absolutePath)) {
        console.log(JSON.stringify(info, undefined, 2));
        console.log(absolutePath);
        return null;
    }
    return absolutePath;
};
```

Please give me a little while to provide a reproduction repo.

**Comment by alexander-akait** [comment]
> So webpack itself does not pass those around?

We do not pass external source maps

> Please give me a little while to provide a reproduction repo.

yes, feel free to ping me

**Comment by olee** [comment]
@alexander-akait while preparing the repo, I started from scratch and noticed that there were no issues with source maps, until I added babel-loader.
The difference of both source maps can be seen [here](https://gist.github.com/olee/41a138a5b7d0afbd3eb67bd5ba22d3c4)
It seems that babel loader tries to embed the source maps encountered when loading modules.

**Comment by alexander-akait** [comment]
Yes, maybe `babel` (I think it is `babel` bug, not `babel-loader`) try to rewrite sources and have a bug, will be great to look at this, maybe it is already reported

**Comment by olee** [comment]
I tried looking into the babel-loader repository but could not find an issue describing this issue - only some other source-map related stuff.

Here is my reproduction repo: https://github.com/olee/webpack-issue-12814

The code has a debugger; statement and if you try stepping into the following function call, the debugger will show an error that it cannot find the source for the file.

If babel-loader rule is commented out in webpack-config however, this works without any issues.

**Comment by alexander-akait** [comment]
@olee Found other problem with `serializr`, look at source map (i.e. `serializr.es.js.map` or other)
```
"sources":["../src/api/createSimpleSchema.ts","../src/utils/invariant.ts","../src/utils/utils.ts","../src/api/getDefaultModelSchema.ts","../src/api/setDefaultModelSchema.ts","../src/api/createModelSchema.ts","../node_modules/tslib/tslib.es6.js","../src/types/primitive.ts","../src/constants.ts","../src/api/serializable.ts","../src/core/serialize.ts","../src/core/Context.ts","../src/core/deserialize.ts","../src/types/object.ts","../src/core/serializeAll.ts","../src/core/cancelDeserialize.ts","../src/core/update.ts","../src/types/identifier.ts","../src/types/date.ts","../src/types/alias.ts","../src/types/custom.ts","../src/types/optional.ts","../src/types/reference.ts","../src/types/list.ts","../src/types/map.ts","../src/types/mapAsArray.ts","../src/types/raw.ts"]
```

But `serializr` don't have `src` directory (and files), so source maps doesn't have sense here

**Comment by alexander-akait** [comment]
If you want to add support of external source maps, i.e. `sourceMapURL`, you need to use `source-map-loader`:
```
{
  test: /\.js$/,
  enforce: "pre",
  use: ["source-map-loader"],
},
```

After this no problems with babel, only problem with non exists source files

**Comment by olee** [comment]
> But serializr don't have src directory (and files), so source maps doesn't have sense here

Yes, that is what I mentioned already in the beginning. Serializr does not provide the src directory in its package, however even if I copy the sources to the correct location, it does not fix the problem.

> If you want to add support of external source maps, i.e. sourceMapURL, you need to use source-map-loader:

Adding source-map-loader and also copying the sources to the correct location did not fix the issue.

**Comment by alexander-akait** [comment]
> Yes, that is what I mentioned already in the beginning. Serializr does not provide the src directory in its package, however even if I copy the sources to the correct location, it does not fix the problem.

> Adding source-map-loader and also copying the sources to the correct location did not fix the issue.

Should solve, can you provide example? It works on my side without any problems, anyway I think nothing to fix on webpack side here...

**Comment by sokra** [comment]
This seem to be a bug somewhere. The relative paths in the source map are not resolved relative to the source map, but relative to the compiler context.

I guess webpack/lib/NormalModule should do this when it sees relative urls as sources.

**Comment by alexander-akait** [comment]
@sokra I think here problem on babel side, because without `babel` source maps are good, only `serializr` doesn't provide sources

**Comment by sokra** [comment]
> I think here problem on babel side, because without `babel` source maps are good, only `serializr` doesn't provide sources

That's interesting. Maybe babel-loader processes the input source map incorrectly...

**Comment by alexander-akait** [comment]
Yep, I think the same, so I asked for a simple example, hard to say why it was broken

**Comment by alexander-akait** [comment]
@olee friendly ping

**Comment by olee** [comment]
Sorry for the wait.
What exactly would you need from me?

**Comment by alexander-akait** [comment]
@olee Can you create simple example? I can't find here problems on webpack side, only broken source maps in `serializr` due lack of source

**Comment by fatawesome** [comment]
Hello! I encountered the same issue: my project uses packages, which provide source maps but no sources. I agree this is a problem on package side, but still would like to have some way of "ignoring" package maps as they were never there. Does anyone know such a way?
