### ISSUE TITLE
output.clean not recognised by Webpack 5.24.3

### ISSUE THREAD

**Issue by alfonsomunozpomer** [webpack/webpack#12815]
# Bug report

**What is the current behavior?**
Using `output.clean` in `webpack.config.js` makes Webpack throw the following error:
```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.output has an unknown property 'clean'. These properties are valid:
 ...
``` 

**If the current behavior is a bug, please provide the steps to reproduce.**
Add `output: { clean: true }`  to `webpack.config.js` and run `npx webpack`.

**What is the expected behavior?**
According to [the documentation](https://webpack.js.org/configuration/output/#outputclean) Webpack should remove the previously emitted bundles and re-generate them without displaying an error.

**Other relevant information:**
webpack version:  5.24.3
Node.js version: 14.15.3
Operating System: Pop!_OS 20.10
Additional tools:

**Comment by alexander-akait** [comment]
You still use old webpack v4, we have test on it, please run `npm ls webpack`, feel free to feedback

**Comment by alfonsomunozpomer** [comment]
You’re totally right, I think `package-lock.json` was playing tricks on me. Sorry for the noise.
