### ISSUE TITLE
Webpack with forge electron 

### ISSUE THREAD

**Issue by Petrik626** [webpack/webpack#12820]
# Bug report

**What is the current behavior?**
I using webpack with forge electron. Forge electron has two default scripts 
1) electron forge start
2) electron forge make
Also I using React library for creating web application and using electron for building it on desktop. Also on my Router component I using react-loadable package for lazy loading and code splitting and I have the following issues:
1) When I run forge make script I getting the ChunkLoadingError. For fix this error I updated my webpack.renderer.config, I added publicPath url on output object and ChunkLoadingError has been fixed, but when I run electron forge start script I getting Failed loaded local resources error. Browser cannot download index.js script. Could you please help me understood how I can fix these issues? 
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Please fill out all fields, won't fix, sorry
