### ISSUE TITLE
Multi-var assign no longer works for me.

### ISSUE THREAD

**Issue by retorquere** [webpack/webpack#12821]
# Bug report

**What is the current behavior?**

With 5.21.2, I used to be able to do multi-var assign using

```
  output: {
    library: 'var {f1, f2}',
    libraryTarget: 'assign',
  }
```

to get `f1` and `f2` at the top level (a requirement for the environment in which my code runs). With 5.24.3, this no longer seems to work.

I have put together an MWE at https://github.com/retorquere/webpack-mwe which is a stripped-down version of my [own repo](https://github.com/retorquere/zotero-better-bibtex/) which is far from minimal. After running `npm run webpack`, the assignment ends up like

```
var {Translator, detectImport, doImport, doExport} = __webpack_exports__;
```

inside the `webpackBootstrap` IIFE. 

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

That the multi-assign ends up in the outer scope like it used to.

**Other relevant information:**
webpack version:  5.24.2
Node.js version: v15.5.0
Operating System: MacOS big sur
Additional tools: none that are not installed by `npm i`.

**Comment by alexander-akait** [comment]
Because you can't using ` library: 'var {f1, f2}',`, you need specify name here, yes it is work before because we just put you value inside code, but we refactor code and you faced with it, but using this is wrong, you can solve it on own side

**Comment by retorquere** [comment]
How would I go about solving it on my own side? BTW it turns out multivar assignment does still work, just not with the typescript to javascript code. If I do just javascript, it does work as before.
