### ISSUE TITLE
webpack 4/5 compatibility issue

### ISSUE THREAD

**Issue by mihkeleidast** [webpack/webpack#12844]
# Bug report

**What is the current behavior?**

If an app that is bundled with webpack@4 tries to consume library that has been bundled with webpack@5 AND TerserPlugin with `keep_fnames: true` option AND the library exports something that has an async/dynamic module loaded, the app has a runtime error in console.

It _does_ work when both app and library are bundled with the same webpack version (both 4/5 are fine).

**If the current behavior is a bug, please provide the steps to reproduce.**

See README in https://github.com/mihkeleidast/webpack-5-module-library.

**What is the expected behavior?**

I would expect the webpack version differences in bundling library/app not to matter. The runtime error should be `Uncaught (in promise) ChunkLoadError: Loading chunk 443 failed.` or something like that.

**Other relevant information:**
webpack version:  4.46.0 / 5.24.4
Node.js version: 12.x
Operating System: Windows 10

**Comment by mihkeleidast** [comment]
Ignore for now, there seems to be a typo in my repro.

**Comment by mihkeleidast** [comment]
Reopening - managed to reproduce this by adding another variable into the game - the error happens if the library exports something that is loading a dynamic module.

**Comment by alexander-akait** [comment]
Expected, do not mix webpack v4 and webpack v5, it was answered a lot of time

**Comment by mihkeleidast** [comment]
So you're saying the entire industry should upgrade to webpack 5 at the same time? It's rather difficult even in my own small ecosystem. `app` has some dependency that does not support webpack@5 yet, so I shouldn't upgrade anything else either?

**Comment by alexander-akait** [comment]
You need updating consistently, i.e update `app` to v5, then libraries and etc to v5, you can't use webpack v5 features and improvements using v4, they just don't supported

**Comment by mihkeleidast** [comment]
Got it. Thank you for your answer.
