### ISSUE TITLE
Webpack v5 missing compilation hook

### ISSUE THREAD

**Issue by mikecarenzo** [webpack/webpack#12847]
# Bug report

**What is the current behavior?**

I'm attempting to migrate my webpack plugin over to webpack 5, but I'm running into an issue:

_The original (Webpack 4) plugin:_
```
apply(compiler) {
    compiler.hooks.emit.tap("DtsBundlerPlugin", (compilation) => {
        // Get assets whose name ends in ".d.ts", 
        // bundle them, emit single ".d.ts" file.
    });
}
```
_The Warning:_
```
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
```

_The Problem_:
I understand, I can't modify assets this late in the compilation and it has to be done earlier. So I did that:
```
apply(compiler) {
    compiler.hooks.thisCompilation.tap("DtsBundlerPlugin", (compilation) => {
        compilation.hooks.processAssets.tap({
            name: "DtsBundlerPlugin",
            state: Compilation.PROCESS_ASSETS_STAGE_OPTIMIZE_INLINE,
        }, (assets) => {
            // Get assets whose name ends in ".d.ts", 
            // bundle them, emit single ".d.ts" file.
        })
    });
}
```

But the ".d.ts" assets (being generated by `ts-loader`) don't appear at the:

* `processAssets` hook
* `afterOptimizeAssets` hook
* `afterProcessAssets` hook

They don't show up until `record` which is too late to modify assets. There appears to be a missing hook in the compilation process which can't be tapped into.

**If the current behavior is a bug, please provide the steps to reproduce.**

Clone and run the following repo to reproduce the problem: https://github.com/mikecarenzo/webpack-plugin-missing-hook

**What is the expected behavior?**

There should be a hook where _all_ assets can be modified before the compilation is sealed.

**Other relevant information:**
webpack version: 5.24.2
Node.js version: 12.21.0
Operating System: Windows 10
Additional tools: [ts-loader: 8.0.17], [typescript: 4.2.3], [webpack-cli: 4.5.0]

**Comment by alexander-akait** [comment]
You need open an issue in `ts-loader` loader repo, nothing to fix on webpack side, also here work on it https://github.com/TypeStrong/ts-loader/pull/1251
