### ISSUE TITLE
Assign variable no longer hoisted to global level for typescript

### ISSUE THREAD

**Issue by retorquere** [webpack/webpack#12843]
# Bug report

**What is the current behavior?**

When compiling typescript using ts-loader with webpack, the `library` variable is not hoisted to the global level, thereby not exposing it at all.

**If the current behavior is a bug, please provide the steps to reproduce.**

MWE at https://github.com/retorquere/webpack-mwe

With webpack 5.21.2, `var MyModule =` is declared at the top of the webpacked output; with 5.24.4, it is declared inside the IIFE and thus not available at the global level.

**What is the expected behavior?**

that the variable in `output.library` is declared in a way that it is available at the global level

**Other relevant information:**
webpack version: 5.21.2 vs 5.24.4
Node.js version: v15.5.0
Operating System: MacOS big sur
Additional tools: none

**Comment by alexander-akait** [comment]
Duplicate https://github.com/webpack/webpack/issues/12742, also https://github.com/retorquere/webpack-mwe/blob/main/webpack.config.ts#L37 should be `var` and https://github.com/retorquere/webpack-mwe/blob/main/webpack.config.ts#L36 should be just `MyModule`
