### ISSUE TITLE
Chunksplitting leads to Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by janlent1** [webpack/webpack#12855]
# Bug report

**What is the current behavior?**
When chunksplitting with the default setup as described here https://webpack.js.org/plugins/split-chunks-plugin/#optimizationsplitchunks, splitting chunks leads to the original chunk to only include one module and that modules moduleId is the path instead of the number that is used in the runtime code to require this module. The right chunk is loaded but the __webpack_modules__ only includes the path instead of the module id(eg 1880) and leads to Cannot read property 'call' of undefined. The mode is set to none.

**If the current behavior is a bug, please provide the steps to reproduce.**
It is tough to reproduce since this is  a chunksplitting done with the standard chunksplitting settings. Maybe due to the knowledge of @sokra this could be fixed, because maybe this is a very specific issue and he knows where to look exactly?

**What is the expected behavior?**
That the module id is included in the chunk instead of the path to the module. Then the __webpack_require__ should also work correctly. This seems to be a very specific issue and maybe this can be fixed swiftly by one who knows the code around this area.

**Other relevant information:**
webpack version: 5.16.0
Node.js version: 12.17.0
Operating System: macOS
Additional tools:

**Comment by alexander-akait** [comment]
> It is tough to reproduce since this is a chunksplitting done with the standard chunksplitting settings. Maybe due to the knowledge of @sokra this could be fixed, because maybe this is a very specific issue and he knows where to look exactly?

Sorry, no

Please provide stack of an error, as minimum

**Comment by janlent1** [comment]
```
Uncaught (in promise) TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (app.main.js:54693)
    at eval (353:42)
__webpack_require__ @ app.main.js:54693
eval @ 353:42
Promise.catch (async)
eval @ 353:49
loadRuntime @ 353:5
init @ 5218:75
eval @ 9404:31
initXXX @ 9404:28
execute @ 9404:163
loadFramework @ 5367:1028
_do @ 9386:157
run @ 9386:70
_startLoad @ 5367:340
main @ 5367:997
loadMainApplication @ 5367:1561
load @ 5367:1359
eval @ 1119:29
Promise.then (async)
eval @ 1119:7
Promise.then (async)
eval @ 1119:6
(anonymous) @ app.main.js:13032
__webpack_require__ @ app.main.js:54693
eval @ 1117:86

```
After adapting the moduleIds in optimization to natural, the path changed into a id 1872, but still the wrong id is in the requiring chunk 1880... I need to further investigate

**Comment by janlent1** [comment]
I explicitly excluded the app.main.js from optimization, because if I include it, it doesnt load all the necessary chunks for the application to start.

**Comment by alexander-akait** [comment]
Can you disable https://webpack.js.org/configuration/optimization/#optimizationmoduleids? and `devtool` and provide stack again

**Comment by janlent1** [comment]
Hi @alexander-akait , unfortunately after doing these steps, after 5 hours now the build failed with a oom dump.

**Comment by janlent1** [comment]
What I can do is to disable the moduleids and maybe enable a lighter devtool? Currently I have EvalSourceMapDevToolPlugin enabled. Also you could point me in the code direction where these moduleids are set, so I can have a look myself and --inspect-brk into the webpack build. I will update you once I have built with a lighter sourcemap and disabled moduleids.

**Comment by sokra** [comment]
Please upgrade to the latest webpack version first. We fixed some of these problems already.

**Comment by janlent1** [comment]
Hi @sokra I already updated to 5.24.4. when additionally minifying so during emit phase I dont run into OOM again, I get an OOM in lib/stats/DefaultStatsPrinterPlugin.js. I could increase the memory footprint, but to make it work it needs at least 10 more gb of ram, then what it did in webpack3. Im trying to increase the memory until it will work, i will keep updating you 
guys. If that wont help i need to debug to find where the module id for this chunk is created. Is there a place you could recommend me to look into for debugging webpack? 
Thanks,
Jan

**Comment by alexander-akait** [comment]
> Is there a place you could recommend me to look into for debugging webpack?

No, please provide configuration, maybe some plugins have leaking, can you disable `stats: 'none'`? How big is the project?

**Comment by janlent1** [comment]
I could show it to you in a call or something but I cannot upload it now, if I should upload it i need to anonymize some properties and this is a big configuration. Let me know whether I could show it to you in a call, in the meantime I will try with the stats none flag.

**Comment by janlent1** [comment]
@alexander-akait also when I set the moduleIds: false, I get possible oom node js errors/breakpoints in the nodejs devtools in the RuntimeTemplate within the function noModuleIdErrorMessage. If this build doesn't work again, I will reset it to 'natural'or just leave it out of the config as previously done.

**Comment by janlent1** [comment]
Without the stats and without the EvalSourceMapDevToolPlugin it worked now with minification. Now some other chunks are not laoded. But the moduleid errors are gone.

**Comment by alexander-akait** [comment]
> This missing modules can be also from my custom plugin side though.

I think problem here

**Comment by janlent1** [comment]
But before the issue with the moduleids was fixed by disabling the evalsourcemapdevtoolplugin. But what i mean now is the problem is the missing chunks not modules which are our issue... False moduleids is reallly not soemthing that we adapt./.

**Comment by janlent1** [comment]
okay i have the issue of false moduleids again after not setting the moduleids in the config. will set it to false again.

**Comment by alexander-akait** [comment]
Can you provide stack or something more, playing guessing is bad practice

**Comment by sokra** [comment]
> moduleIds: false

That disables module ids and you are expected to provide a plugin for module ids. I don't think you want to configure it this way.

> without the EvalSourceMapDevToolPlugin it worked now with minification

EvalSourceMapDevToolPlugin + minification doesn't make a lot of sense anyway.

**Comment by janlent1** [comment]
it seems like since updating to 24.4 from 16, the emit takes much longer. Also much more ram is used. Is this DefaultStatsPrinterPlugin new since >16?

**Comment by alexander-akait** [comment]
> it seems like since updating to 24.4 from 16

We don't have these versions

**Comment by janlent1** [comment]
you are right i meant 5.24.4 and 5.16.0

**Comment by alexander-akait** [comment]
We fixed some leak issue in master, maybe you can test?

**Comment by janlent1** [comment]
Was there some stuff downported? I see this now also in the 5.16.0 build:
Uncaught RangeError: Invalid string length
    at Array.join (<anonymous>)
    at itemsJoinMoreSpacing (name/webpack/node_modules/webpack/lib/stats/DefaultStatsPrinterPlugin.js:759:61)
    at Hook.eval [as call] (eval at create (name/webpack/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:5:16)
    at Hook.CALL_DELEGATE [as _call] (/name/webpack/node_modules/webpack/node_modules/tapable/lib/Hook.js:14:14)
    at /Applications/Develop/name/webpack/node_modules/webpack/lib/stats/StatsPrinter.js:203:8
    at StatsPrinter._forEachLevel (name/webpack/node_modules/webpack/lib/stats/StatsPrinter.js:120:19)
    at StatsPrinter._print (/name/webpack/node_modules/webpack/lib/stats/StatsPrinter.js:202:24)
    at StatsPrinter.print (/name/webpack/node_modules/webpack/lib/stats/StatsPrinter.js:150:16)
    at name/webpack/node_modules/webpack/lib/stats/StatsPrinter.js:217:27
    at Array.map (<anonymous>)

**Comment by alexander-akait** [comment]
Does it happen with the latest version?

**Comment by janlent1** [comment]
![DefaultStatsPrinterPlugin](https://user-images.githubusercontent.com/22960683/110838687-0d56bb00-82a3-11eb-8426-6811af8e9b29.png)

Seems to be also in the master that i just installed and also in another configuration that just uses this webpack because its in the subfolder.
Will debug

**Comment by alexander-akait** [comment]
Yes, please debug it, it is easy, just print `items` in `itemsJoinMoreSpacing`, I still think bug in custom plugin

**Comment by janlent1** [comment]
Okay I made it work again with the master and could get the build to build. But the error persists and the only usabble callstack is this here 
```
Uncaught (in promise) TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (app.main.js:54693)
    at Function.__webpack_require__.t (app.main.js:54744)
```
The __webpack_modules__ is an array but some entries are no numbers but are actual module ids(paths|loader prefixes) as name.
These modules with the name for the file or the name plus loaders are everything from ts(x) js less css files... They are from few areas but they seem to be required as the id instead of the name that they are stored as in.
 
And those modules that are not optimized by the splitchunksplugin but processed by it(maybe other modules have been cut from the chunk away but those remaining) have  the path as the module id; those chunks that are created by the splitchunksplugin have modules with  moduleids as a number as they should have it. If you explicitly excluded speicifc chunks from optimization they dont have a path anymore.
 
It seems to me that optimized but not changed chunks(modules have been cut away from chunk, but the leftover chunk is like the original one) have a path as the module id and those that were created or optimized (modules have been put into new chunk) or explicitly excluded from optimization have an id as the moduleid.

**Comment by janlent1** [comment]
So after also disabling the devtool:false, and not having other EvalSourceMapDevToolPlugin enabled the split chunks split by the splitchunksplugin have a eval-source-map, but those original have no source map.
This is now only working in the master for me before that the build never finished.

**Comment by janlent1** [comment]
If I enable eval-source-map in the devtool, the optimized and non-optimized but going through splitchunks chunks look simialr except the module id still being faulty in the non-optimized chunk.

**Comment by alexander-akait** [comment]
Sorry I can't help you, won't fix for me, I can’t guess and unfortunately I don’t have time for that, if you need help try to reduce your app and provide example of the problem

**Comment by janlent1** [comment]
@alexander-akait i could also debug some more if you could give me a point where module ids are transformed into the numbers as they should be. The setmoduleid is not the right call because that happens with the path but i didnt see it with numbers yet.
Maybe I can then go up the stack and take a look at where this processing is started and try to figure out why they are not transformed. 
I also figured out that these weird modules are coming from one entrypoint that is added. That is why in one configuration of mine the app is working, since it doesnt have the entrypoint that is necessary for the other config/build type. Is it possible that there is still some issue with the entrypoints? I saw a new release but that didnt fix any issues for me....

**Comment by alexander-akait** [comment]
@janlent1 sorry, your problem is not fixable, please provide an example of how we can reproduce the error, otherwise I will have to close it and mark it as `won't fix`

**Comment by primozs** [comment]
Upgrading from "webpack": "^5.22.0", to "webpack": "^5.23.0" and all versions above I get 
```
Cannot read property 'call' of undefined
    at __webpack_require__ ( ...build/dist/server/main.js:2:8428129)
...
```
not using anything "special"
<img width="1669" alt="Screenshot 2021-03-21 at 10 25 57" src="https://user-images.githubusercontent.com/1006789/111899929-eb420300-8a2f-11eb-865f-9a76673a3682.png">

**Comment by primozs** [comment]
my issue was resolved for version 5.23.0 and all above that by removing
new webpack.optimize.ModuleConcatenationPlugin(),
https://webpack.js.org/plugins/module-concatenation-plugin/

**Comment by alexander-akait** [comment]
Should be fixed for `5.28.0`, but we still have some problems in some cases https://github.com/webpack/webpack/issues/12964

**Comment by csvan** [comment]
@janlent1 did you find a solution? I am seeing the same issue when using Module Federation, not sure which version it started on.

**Comment by ydmitry** [comment]
https://github.com/webpack/webpack/issues/12964 similar issue raised here
