### ISSUE TITLE
Webpack React Module parsers fail in webpack-5

### ISSUE THREAD

**Issue by SatishChandraPalakoti** [webpack/webpack#12853]
I have my webpack config as follow:

 ```
module:{
        rules: [
            {
                test: /\.js$/,
                exclude: /node_modules/,
                include: APP_DIR,
                use: ['babel-loader']
            },
            {
                test: /\.(scss|css)$/,
                use: ["style-loader","css-loader","sass-loader"]
            }
        ]
    },
```
Surprisingly nothing changed in my code. And things seem to fail suddenly with the following error. It's just a simple react button click in a component bound to render function.

```
ERROR in ./src/index.js 16:15
Module parse failed: Unexpected token (16:15)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     }
|     render(){
>         return(<div>
|             <button onClick={()=>this.clicked()}>Click Me</button>
|             </div>
```

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Please use `test: /\.jsx$/,` (`x` for JSX)

**Comment by SatishChandraPalakoti** [comment]
@alexander-akait I am using the exact samme notation for test clause in the webpack file.  But the issue still seems to appear. I am trying to figure out if this is webpack related or not.

**Comment by alexander-akait** [comment]
@SatishChandraPalakoti Remove ` exclude: /node_modules/,`, because `node_modules` can contain react components
