### ISSUE TITLE
Optimising "Initial" chunks breaks library scripts.

### ISSUE THREAD

**Issue by jcampbell05** [webpack/webpack#12863]
Webpack 5
Mac OS Catalina 10.15.7

If you optimise only initial or all chunks then library targets which use Webpack will break. This is because some of these new shared chunks will end up as additional entry points with the expectation they will be loaded from the HTML in the correct order.

The HTML plugin would normally handle this for you but since this is a library we do not have control over this. Instead we would ideally love webpack to generate a script to fetch these shared modules in the order they should be loaded like the original HTML plugin would have done. 

You can see an example of a plugin I have written where I do exactly this but Ideally would be part of Webpack itself.
https://github.com/PSPDFKit-labs/webpack-optimise-chunks-workaround/blob/main/bootstrap.plugin.js

**Comment by KevinPan** [comment]
I have the same problem.

**Comment by vankop** [comment]
@alexander-akait I did not get what we should do from webpack side..

**Comment by alexander-akait** [comment]
Yes, it is weird to use splitting chunks for library, if you don't want to split code, just disable it, also maybe file to file output library will help here (i.e. keeping file structure and rewrite online `require`/`define`/etc)

**Comment by vankop** [comment]
feel free to feedback

**Comment by jcampbell05** [comment]
We wanted the splitting of chunks for our library but we wanted a way of webpack to spit out a file which would resolve these chunks for us.

**Comment by heyheyhello** [comment]
Sorry for cross posting but I got it working with a on-the-fly code mod to get webpack to produce an auto-loaded chunk :) https://github.com/webpack/webpack/issues/11025#issuecomment-1034793716
