### ISSUE TITLE
Please export Resolver and ResolvePluginInstance from types.d.ts

### ISSUE THREAD

**Issue by Brian-McBride** [webpack/webpack#12869]
Similar to how `Compiler` and the various plugin interfaces are exported, please add `Resolver` and `ResolvePluginInstance` to the exports.

```typescript
export {
		AutomaticPrefetchPlugin,
		 // ... 
		Compiler,
		//  ...
		Resolver,
		ResolvePluginInstance,
                //  ...
}
```

I am updating some plugins to work with Webpack 5, and in a typescript environment, I'm missing those types when trying to create a resolve plugin.

**Comment by alexander-akait** [comment]
Feel free to send PR, just add them here https://github.com/webpack/webpack/blob/master/lib/index.js#L31 in js docs and they will be in types, don't forget to run https://github.com/webpack/webpack/blob/master/package.json#L156 before adding

**Comment by Brian-McBride** [comment]
PR up at #12875 

Thanks for the pointer.

**Comment by alexander-akait** [comment]
bump
