### ISSUE TITLE
Vendor common file + entrypoints common file

### ISSUE THREAD

**Issue by evandegr** [webpack/webpack#1286]
I have 3 application bundles (3 entrypoints) and also a bunch of vendor files. I'd like to create a bundle that has all the common code from the 3 entrypoints as well as the bundle of vendor files (or put the common code also in the vendor bundle).

```
plugins = [
    new webpack.optimize.CommonsChunkPlugin("vendor", "vendor.bundle.js"),
    new webpack.NormalModuleReplacementPlugin(appModuleRegex, function(result) {
        result.request = result.request.replace(appModuleRegex, "/web/app/$1/src/$2");
    }),
    new webpack.HotModuleReplacementPlugin(),
    new webpack.optimize.LimitChunkCountPlugin({maxChunks: 1}),
    new webpack.optimize.OccurenceOrderPlugin(true)
];
```

```
entrypoints = {
    framework: 'framework/app',
    operations: 'operations/app',
    platform: 'platform/app',
    vendor: 
        ['babel-core',
         'crypto-js',
         'classnames',
         'd3',
         'fetch',
         'lodash',
         'moment',
         'moment-timezone',
         'react',
         'react-router',
         'react-select',
         'zxcvbn2']
};
```

Currently I'm seeing a lot of code duplicated across the app bundles. I also need to keep maxChunks at 1.

**Comment by sokra** [comment]
> Currently I'm seeing a lot of code duplicated across the app bundles.

This is working as intended. Code is only moved to the commons chunk if it is shared by all 3 entry chunks. The idea is to keep initial download time minimal. The client shouldn't download unneeded code.
