### ISSUE TITLE
When two different remotes exposes a component each with the same file name, host application assumes they are the same components

### ISSUE THREAD

**Issue by hasanayan** [webpack/webpack#12862]
# Bug report

**What is the current behavior?**

# my module federation setup

I use react and react-router;

**app2**
exposes `./src/Route` and `./src/App` as `app2/Route` and `app2/App`
App is a button with a text: "App 2 button"

**app3**
exposes `./src/Route3` and `./src/App` as `app3/Route` and `app3/App`
App is a button with a text: "App 3 button"

Notice that Route and Route3 have different file names but both remotes expose module named App.

**app1**
imports `app2/Route`, `app2/App`,  `app3/Route` `app3/App`

renders the routes and passes the respective App components as their children.

# The problem

I noticed webpack checks the js file name and if they match, uses the first downloaded module for all the future modules that has the same file name. I think this is designed for the shared dependencies but it is forcing me to use different file names for the exposed modules in different remotes.

**If the current behavior is a bug, please provide the steps to reproduce.**

when I;
- run app1
- click a link that routes to app2, I will see there is a button that has "App 2 button" as text (this is expected)
- click a link that routes to app3, I will see the same button with the same text "App 2 button" 

for live example; go to [https://tmf-app1.hasanayan.me](https://tmf-app1.hasanayan.me)
click on "go to app 2" you will see a button with text "App 2 button"
click on "go to app1" (do not refresh the page)
click on "go to app 3" you will see the same button from App2

here is the repo to the project [https://github.com/hasanayan/typed-module-federation](https://github.com/hasanayan/typed-module-federation)

**What is the expected behavior?**

when you click on "go to app 3" you should see a button with text "App 3 button".

If the modules are from the source (not from node_modules) of the remotes and have the same name, webpack should not assume they are the same modules and should download and load them separately.

**Other relevant information:**
webpack version:  5.18.0
Node.js version: v12.18.4
Operating System: Mac OS
Additional tools:

**Comment by sokra** [comment]
Make sure that each package.json has a different `"name"`. In your example: fix app3/package.json
