### ISSUE TITLE
Promise is undefined with target: ['web', 'es5'] using webworker

### ISSUE THREAD

**Issue by plohoj** [webpack/webpack#12877]
# Bug report

**What is the current behavior?**

IE 11 throws a "'Promise' is undefined" exception if there is a promise or async in the code, even with `babel-loader`.
This error occurs in a piece of code generated by webpack:
![image](https://user-images.githubusercontent.com/10156573/110858932-bd401e80-82cb-11eb-9e83-4a630c8f793f.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

This error is thrown if webpack.config.js contains:
```ts
{ target: ['web', 'es5'] }
```
Also a new way of declaring webworker is used
```ts
new Worker(new URL('./worker', import.meta.url));
```
And any piece of code will contain a `Promise` or an `async`. If a `Promise` or `async` is not contained in the code, then there will be no error.

https://github.com/plohoj/webpack-web-es5-webworker-promise-issue

**What is the expected behavior?**

It is assumed that if webpack targets `['web', 'es5']` then it will not use Promise in generated code

**Other relevant information:**
webpack version:  5.24.4
Node.js version: v14.0.0
Operating System: Windows 10

**Comment by sokra** [comment]
es5 is the syntax level. It's not about the runtime api. You need to provide polyfills for the stuff you are using.

**Comment by plohoj** [comment]
In my example, I am using babel-loader and @ babel/preset-env. And it provides polyfill for my code, but babel-loader cannot provide polyfills for import code generated by webpack.

My input code:
```ts
export class Library {
    public async log(): Promise<void> {
        console.log('Some log');
    }
}
```
My output code:
```js
var Library =
/** @class */
function () {
  function Library() {}

  Library.prototype.log = function () {
    return __awaiter(this, void 0, void 0, function () {
      return __generator(this, function (_a) {
        console.log('Some log');
        return [2
        /*return*/
        ];
      });
    });
  };

  return Library;
}();
```
And the same file contains the following code generated by webpack
```js
/******/ 	/* webpack/runtime/ensure chunk */
/******/ 	!function() {
/******/ 		__webpack_require__.f = {};
/******/ 		// This file contains only the entry chunk.
/******/ 		// The chunk loading function for additional chunks
/******/ 		__webpack_require__.e = function(chunkId) {
/******/ 			return Promise.all(Object.keys(__webpack_require__.f).reduce(function(promises, key) {
/******/ 				__webpack_require__.f[key](chunkId, promises);
/******/ 				return promises;
/******/ 			}, []));
/******/ 		};
/******/ 	}();
```

I suppose this is happening because babel-loader does its job before webpack replaces the import functions.

**Comment by alexander-akait** [comment]
Answer above, webpack doesn't do polyfilling for you, you need do it manually, here you can found  how you can do it https://stackoverflow.com/questions/38960490/how-can-i-polyfill-promise-with-webpack. Yes, babel may don't add polyfills, because you use `useBuiltIns: 'usage'`, so if you don't have Promise in your code babel doesn't add them, you need manually add them.

I strongly recommend do not use polyfill for libraries, you don't know env where it will be used

**Comment by alexander-akait** [comment]
For library you can improve readme and add description like:

"You need `Promise` for using this library". 

Here good library https://github.com/stefanpenner/es6-promise

For application I recommend just put 
```
<script src="https://cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.auto.min.js"></script> 
```

In your HTML file

**Comment by alexander-akait** [comment]
I think we need doc it

**Comment by plohoj** [comment]
I've tried all the suggested ways, but it doesn't help. I added to my webpack.config.js:
```js
entry: [
    'core-js/es/promise',
    './src/scripts/main.ts'
],
```
`src_scripts_worker_ts.js` file contains polyfill import:  
![image](https://user-images.githubusercontent.com/10156573/111031465-bc68d300-8418-11eb-82be-570e35e5a94c.png)  

And the `vendors-node_modules_core-js_modules_es_object_to-string_js-node_modules_core-js_modules_es_p-2bb844.js` file contains the declaration promise:
![image](https://user-images.githubusercontent.com/10156573/111031662-ba534400-8419-11eb-9fee-479099361fae.png)  

But the error is still present. IE still indicates a bug in the webpack imports:  
![image](https://user-images.githubusercontent.com/10156573/110858932-bd401e80-82cb-11eb-9e83-4a630c8f793f.png)  
Because the polyfill will be added after installing the webpack import dependencies.
I am pointing out a bug that **webpack replaces imports with its own template imports**, which uses a Promise before it is polyfilled.

I believe webpack should not use `Promise` in its imports. Since I cannot guarantee that the `Promise` polyfill will be added before webpack starts initializing.

**Comment by alexander-akait** [comment]
> I believe webpack should not use Promise in its imports. Since I cannot guarantee that the Promise polyfill will be added before webpack starts initializing.

Sorry, it is impossible, again, just add `<script src="https://cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.auto.min.js"></script> ` in HTML file, without promise async loading are impossible

**Comment by plohoj** [comment]
> just add `<script src="https://cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.auto.min.js"></script> ` in HTML file before webpack code

It also doesn't work. Because the error is happening in the `src_scripts_worker_ts.js file`, which is executed in the **webwerker area**

**Comment by alexander-akait** [comment]
Please provide example

**Comment by plohoj** [comment]
Exemple pinned in main message:
https://github.com/plohoj/webpack-web-es5-webworker-promise-issue

**Comment by alexander-akait** [comment]
workaround:
```js
new webpack.BannerPlugin({
  raw: true,
  banner: 'if (typeof WorkerGlobalScope !== "undefined" && self instanceof WorkerGlobalScope && typeof self.Promise === "undefined") { importScripts("https://cdn.jsdelivr.net/npm/es6-promise@4/dist/es6-promise.a.."); self.Promise = ES6Promise; }'
})
```

close in favor https://github.com/webpack/webpack/issues/3531, we should allow to setup `Promise`, also pulling `__webpack_promise__` in worker scope
