### ISSUE TITLE
ie 11 silently failing feature after build

### ISSUE THREAD

**Issue by rgeerts** [webpack/webpack#12879]
# Bug report

**What is the current behavior?**
I am using a vue, vue cli, and bootsrap-vue in a project.  When I run a project in development mode, it is working fine.  When I go to build the project a particular feature doesn't work.  I have a table filtering feature where you can type in a text field and the table is searched for the contents.
If i put in a .vue.config.js with "mimize":false...I have no problems.

I have added an issue to bootstrap-vue for reference there in case someone else runs up against the same issue:

https://github.com/bootstrap-vue/bootstrap-vue/issues/6493

**If the current behavior is a bug, please provide the steps to reproduce.**

You can checkout https://github.com/rgeerts/ei11_optimization_vue_issue (I have a webpack 5 branch that uses the latest webpack)
steps:
  1. check out dir
  2. npm install
  3. npm run serve
  4. use browser (http://localhost:8080)
  5. fill in text box with "11" see the table filter
  6. npm run build
  7. npm install -g serve
  8. serve -s dist
  9.  notice the filter doesn't do anything by going to http://localhost:5000
  10.  change ./vue.config.js.bak to ./vue.config.js
  11. npm run build
  12. serve -s dist
  13. see the filter work again

**What is the expected behavior?**
I would expect the same behavior from javascript whether a project is minified or not

**Other relevant information:**
webpack version:  5.24.4
Node.js version: I am using 15.2.0
Operating System: osx
Additional tools:

**Comment by alexander-akait** [comment]
oh, again IE 11, 2021 year...

**Comment by rgeerts** [comment]
I know...Edge <= 44 too. That probably doesn't make it too much more enticing.

**Comment by alexander-akait** [comment]
I will look at the problem, I'm pretty sure the problem isn't in webpack, problem in babel/terser/package, in most places we don't touch your code, just rewrite `import`/`export`/`require`/etc on own function + some runtime

**Comment by rgeerts** [comment]
yeah...I wasn't exactly sure webpack's relation with terser.  Saw some other terser related issues issued here. I can add an issue with terser directly too.

**Comment by rgeerts** [comment]
I see submitting a bug to terser may be more complicated that I originally estimated.  They don't want webpack included.  I spent a fair amount of time already organizing this code example.  not sure I can get this issue condensed down to a terser issue very quickly.

**Comment by alexander-akait** [comment]
You don't use `webpack version: 5.24.4`, run `npm ls webpack` and look at output, maybe bug in `terser`, but v5 only available in `webpack` v5 (or in `terser-webpack-plugin` v5, but it require `webpack` v5 too), you need to open issue in `vue-cli`, unfortunately we can't fix it on our side also I try to debug it using IE 11/10 and even 9, all works fine

**Comment by rgeerts** [comment]
I experience the issue with webpack 4 and 5(I thought).  I used vue cli alpha version to get the webpack 5.  Not sure it is worth you looking at anymore if you couldn't replicate it with 4 even.  but my npm ls webpack does show 5.24.4. Did you use the webpack5 branch?

npm ls webpack
test_app@0.1.0 /Users/rgeerts/code/test_app
├─┬ @vue/cli-plugin-babel@5.0.0-alpha.7
│ ├─┬ babel-loader@8.2.2
│ │ └── webpack@5.24.4 deduped
│ ├─┬ thread-loader@3.0.1
│ │ └── webpack@5.24.4 deduped
│ └── webpack@5.24.4
├─┬ @vue/cli-plugin-eslint@5.0.0-alpha.7
│ ├─┬ eslint-webpack-plugin@2.4.3
│ │ └── webpack@5.24.4 deduped
│ └── webpack@5.24.4 deduped
├─┬ @vue/cli-service@5.0.0-alpha.7
│ ├─┬ @soda/friendly-errors-webpack-plugin@1.8.0
│ │ └── webpack@5.24.4 deduped
│ ├─┬ @vue/preload-webpack-plugin@1.1.2
│ │ └── webpack@5.24.4 deduped
│ ├─┬ cache-loader@4.1.0
│ │ └── webpack@5.24.4 deduped invalid
│ ├─┬ copy-webpack-plugin@7.0.0
│ │ └── webpack@5.24.4 deduped
│ ├─┬ css-loader@5.1.2
│ │ └── webpack@5.24.4 deduped
│ ├─┬ css-minimizer-webpack-plugin@1.2.0
│ │ └── webpack@5.24.4 deduped
│ ├─┬ file-loader@6.2.0
│ │ └── webpack@5.24.4 deduped
│ ├─┬ html-webpack-plugin@5.3.1
│ │ └── webpack@5.24.4 deduped
│ ├─┬ mini-css-extract-plugin@1.3.9
│ │ └── webpack@5.24.4 deduped
│ ├─┬ postcss-loader@5.2.0
│ │ └── webpack@5.24.4 deduped
│ ├─┬ terser-webpack-plugin@5.1.1
│ │ └── webpack@5.24.4 deduped
│ ├─┬ url-loader@4.1.1
│ │ └── webpack@5.24.4 deduped
│ ├─┬ vue-loader-v15@npm:vue-loader@15.9.6
│ │ └── webpack@5.24.4 deduped
│ ├─┬ webpack-dev-server@3.11.2
│ │ ├─┬ webpack-dev-middleware@3.7.3
│ │ │ └── webpack@5.24.4 deduped
│ │ └── webpack@5.24.4 deduped
│ └── webpack@5.24.4 deduped
└─┬ sass-loader@10.1.1
  └── webpack@5.24.4 deduped

npm ERR! code ELSPROBLEMS
npm ERR! invalid: webpack@5.24.4 /Users/rgeerts/code/test_app/node_modules/webpack

**Comment by alexander-akait** [comment]
I can't reproduce the problem with IE 11 using webpack v4 and webpack v5 in your branch, all works fine

**Comment by alexander-akait** [comment]
Also if is working with `minimize: false`, nothing to fix on our side, sorry

**Comment by rgeerts** [comment]
thanks for your effort, any chance I could get your package-lock.json that was generated

**Comment by alexander-akait** [comment]
For v4 or v5?

**Comment by rgeerts** [comment]
lets go with v5

**Comment by alexander-akait** [comment]
I am using `yarn` (just note your package doesn't install using npm v7)
[yarn.lock.txt](https://github.com/webpack/webpack/files/6131054/yarn.lock.txt)

**Comment by alexander-akait** [comment]
Reproduced, give me time to investigate

**Comment by alexander-akait** [comment]
Yep, bug in `terser`. I can't say what is wrong, but if you set `terserOptions.compress.unused = false;` https://github.com/terser/terser#compress-options all works fine

**Comment by alexander-akait** [comment]
Looks something was removed by terser as unused, but it still need for IE 11, i think it is polyfill

**Comment by alexander-akait** [comment]
Unfortunately, I can't help much, I spent 3~4 hours on debug and no luck, feel free to report it in `terser` repo and provide information about `compress.unused: false` is fix the problem. Nothing to fix on our side, sorry, I helped as much as I could

My **BIG** recommendation is drop IE 11, I know that some clients still require it, but it's time to tell them no, it is not possible and it is very slow.

As workaround you can setup `terser-webpack-plugin` manually using `vue.config.js` and setup `compress.unused: false`.

Feel free to feedback
