### ISSUE TITLE
Asset modules custom publicPath

### ISSUE THREAD

**Issue by gpoitch** [webpack/webpack#12884]
## Feature request

**What is the expected behavior?**
Need a way to set a different publicPath per asset.
`assetModuleFilename` and `generator.filename` allow file name customization but not public path.

**What is motivation or use case for adding/changing the behavior?**
file-loader has this option: https://github.com/webpack-contrib/file-loader#publicpath
My use-case is that I host font assets at a different cdn than other assets.

**How should this be implemented in your opinion?**
Similar to file-loader.  A string|function  exposed either via `generator.publicPath` or `assetModulePublicPath`

**Are you willing to work on this yourself?**
maybe, if some direction provided.

**Comment by sokra** [comment]
Send a PR. AssetModulesPlugin is a good place to start. Tests can go into test/configCases/asset-modules.
You also need to change the schema in schemas/WebpackOptions.json to add the new option.

**Comment by xiaoxiaojx** [comment]
cool, I also need this feature, I'll mention a mr, thanks
https://github.com/webpack/webpack/pull/12902
