### ISSUE TITLE
Unable to migrate to webpack@5 without stable dev server

### ISSUE THREAD

**Issue by fmagaldea** [webpack/webpack#12889]
Hi,

All community see you are doing great efforts in webpack package.
But for now is sad to say that is for nothing, because there is no decent way to use in local in development mode (= served locally, with hot, all in memory...).

Why?
Because the package you recommend for dev environment [webpack-dev-server](https://www.npmjs.com/package/webpack-dev-server) has so many issues (hot broken, incompatible with IE...) that makes it unusable, for I guess a very large majority of projects.

Any possibility to balance resources in your team, so you could give some help and finish at least a first stable version of the dev environment handling?

**Comment by sokra** [comment]
cc @alexander-akait

**Comment by alexander-akait** [comment]
We are working on new release, hope we will finish it on this week. @fmagaldea You can try `webpack-dev-server@beta-0` and if you faced with the issue, feel free to open a new issue in `webpack-dev-server` repo, sorry for this
