### ISSUE TITLE
Webpack drops aggregated changes when using Watching.resume()

### ISSUE THREAD

**Issue by vladar** [webpack/webpack#12882]
# Bug report

**What is the current behavior?**

This is an issue with `resume`/`suspend` flow of webpack Watching. In an edge case (described below) webpack drops some of the aggregated changes and they are not included in the compilation result.

**If the current behavior is a bug, please provide the steps to reproduce.**

All of the following conditions must be met to reproduce it:

1. `resume` is called between `changed` (`invalid`) and `aggregated` watchpack events
2. empty compilation caused by `resume` is finished before `aggregated` event fires

I've opened a PR with a failing test to demonstrate it: #12881

It is easier to reproduce this with higher aggregation timeout but we've seen this in Gatsby in the real-world projects with default timeout as well (just harder to reproduce).

**What is the expected behavior?**

Resumed compilation should include all aggregated changes.

**Other relevant information:**
webpack version:  latest
Node.js version: 12.20.0
Operating System: Windows
Additional tools: Jest? 😄

**Comment by alexander-akait** [comment]
Fixed by https://github.com/webpack/webpack/pull/13399
