### ISSUE TITLE
ENAMETOOLONG when emitting HMR chunk

### ISSUE THREAD

**Issue by rigor789** [webpack/webpack#12883]
# Bug report

**What is the current behavior?**

In a complex project we are applying multiple loaders - everything works as expected, however when a HMR build triggers the emitted `hot-update.json` file has a too long name.

```
[webpack-cli] [Error: ENAMETOOLONG: name too long, open '/Users/rigor789/Code/_tmp/myVueApp/platforms/ios/myVueApp/app/_node_modules_nativescript_webpack_dist_loaders_nativescript-hot-loader_index_js_ruleSet_1_rules_8_use_0_node_modules_babel-loader_lib_index_js_clonedRuleSet-3_0_rules_0_use_0_node_modules_nativescript_webpack_dist_loaders_nativescript-worker-loader_index_js_app_app_js_10_17-67.hot-update.json'] {
  errno: -63,
  code: 'ENAMETOOLONG',
  syscall: 'open',
  path: '/Users/rigor789/Code/_tmp/myVueApp/platforms/ios/myVueApp/app/_node_modules_nativescript_webpack_dist_loaders_nativescript-hot-loader_index_js_ruleSet_1_rules_8_use_0_node_modules_babel-loader_lib_index_js_clonedRuleSet-3_0_rules_0_use_0_node_modules_nativescript_webpack_dist_loaders_nativescript-worker-loader_index_js_app_app_js_10_17-67.hot-update.json'
}
```

I have tried changing `config.output.otUpdateMainFilename` & `config.output.hotUpdateChunkFilename` however if I remove the `[runtime]` placeholder - the filenames are no longer unique (and webpack warns about this correctly).

**If the current behavior is a bug, please provide the steps to reproduce.**

Tried to reproduce in a simple scenario but that has proven difficult - as it's a combination of multiple plugins & loaders.

**What is the expected behavior?**

The [HotModuleReplacementPlugin](https://github.com/webpack/webpack/blob/master/lib/HotModuleReplacementPlugin.js) (or anywhere, if there's a better place) should handle too long filenames, and shorten them.

Adding some logging, the `runtime` is the long part that causes trouble:
https://github.com/webpack/webpack/blob/e643b85a6accde7e4c7f19c8770816e5aaf6a945/lib/HotModuleReplacementPlugin.js#L454-L463

This seems to be handled for imported chunks already: https://github.com/webpack/webpack/issues/6426

**Other relevant information:**
webpack version:  5.25.0
Node.js version: 14.9.0
Operating System: macOS
Additional tools: N/A

**Comment by alexander-akait** [comment]
Feel free to send a PR, low priority

**Comment by rigor789** [comment]
@alexander-akait to avoid going down the wrong path, do you have pointers where should we check the filename length? Happy to work on a PR!

**Comment by alexander-akait** [comment]
How you get this long path?

**Comment by rigor789** [comment]
The config is from an upcoming webpack5 rewrite of the NativeScript build setup - we're building the config dynamically using webpack-chain, and here's a rough output of the config that causes the ENAMETOOLONG issue when doing hmr:

https://gist.github.com/rigor789/838c5ae02139c3e26aeb638493021611

In this particular case - disabling the "bundle" loader stack: https://gist.github.com/rigor789/838c5ae02139c3e26aeb638493021611#file-webpack-config-js-L55-L70 works fine - however that just masks the underlying issue (and we do need that loader in place to inject our hmr runtime code).

The `ruleSet_1_rules_8_use_0` etc parts in the filename - I'm not sure if these are added by webpack of perhaps vue-loader (it does some rule cloning internally & adds resourceQueries, it could be related to that maybe)?

**Comment by rigor789** [comment]
Update: I managed to reproduce it in an isolated projects, and it seems to be related to worker chunks.

Included steps to reproduce in the README:

https://github.com/rigor789/webpack-hmr-enametoolong

**Comment by alexander-akait** [comment]
I am afraid it is not easy to fix, even more I think it is not fixable

**Comment by rigor789** [comment]
@alexander-akait Thanks for looking into it - got me worried for a second there! 😆 If you can point me in the right direction, I'm happy to work on the fix!

**Comment by alexander-akait** [comment]
https://github.com/webpack/webpack/blob/master/lib/HotModuleReplacementPlugin.js, but looks it require more code

**Comment by rigor789** [comment]
I traced back where the `runtime` name is generated: 
https://github.com/webpack/webpack/blob/e643b85a6accde7e4c7f19c8770816e5aaf6a945/lib/dependencies/WorkerPlugin.js#L266-L270

Would it be safe to do a length check & truncate very long names (with a hash) like this: https://github.com/webpack/webpack/blob/e643b85a6accde7e4c7f19c8770816e5aaf6a945/lib/optimize/SplitChunksPlugin.js#L1634-L1639

**Comment by sokra** [comment]
As workaround you can manually give the worker chunk a name with `/* webpackChunkName: "name" */` in the `new Worker(..)` call.

**Comment by rigor789** [comment]
Thanks @sokra, I have found your comment about that in https://github.com/webpack/webpack/pull/11439#issuecomment-688693800 and have tried naming the chunk. It is renamed, however a HMR chunk/update still crashes. Patching the WorkerPlugin & truncating the `entryOptions.runtime` seemed to solve the crash (and everything else appears to be fine), but I don't feel confident it's the right fix.

**Comment by alexander-akait** [comment]
@rigor789 Yep, it is just workaround

**Comment by olegshilov** [comment]
Got the same issue. Is there any news about a fix?
