### ISSUE TITLE
Support force tty of nodeConsole

### ISSUE THREAD

**Issue by KENNYSOFT** [webpack/webpack#12899]
## Feature request

**What is the expected behavior?**

Provide some environment variable or someway to support force set `tty` of `nodeConsole`.

**What is motivation or use case for adding/changing the behavior?**

To use with Jenkins.

I make builds using Jenkins, and it supports colors by AnsiColor plugin.
Since Jenkins shows 'Console Output' as non-TTY environment, I need to set force color options many place.
So I want something like https://github.com/webpack/webpack-cli supporting force color via .npmrc `color=always`.

**How should this be implemented in your opinion?**

https://github.com/webpack/webpack/blob/263c950952ca6aad298f2b7651c06e072fbf3e62/lib/node/nodeConsole.js#L11

Change above to below:

```js
const tty = (process.stderr.isTTY && process.env.TERM !== "dumb") || process.env.TERM === "tty";
```

**Are you willing to work on this yourself?**
Yes

**Comment by alexander-akait** [comment]
> const tty = (process.stderr.isTTY && process.env.TERM !== "dumb") || process.env.TERM === "tty";

it is breaking change and potential break terminal for other developers

**Comment by KENNYSOFT** [comment]
I see, then how about using a new environment variable, something like `process.env.WEBPACK_FORCE_TTY` ?

**Comment by alexander-akait** [comment]
I think we need logic here:
```js
const tty =
  !("NO_TTY" in process.env) &&
  ("FORCE_TTY" in process.env ||
    (process.stderr != null &&
      process.stderr.isTTY &&
      process.env.TERM &&
      process.env.TERM !== "dumb"))
```

**Comment by alexander-akait** [comment]
So you can force enable and disable it

**Comment by KENNYSOFT** [comment]
Yeah but not `process​.​env​.​TERM​ ​&&​` since the property may not exists.

**Comment by KENNYSOFT** [comment]
So could I make a PR?

**Comment by alexander-akait** [comment]
Yes, let's send a PR

**Comment by KENNYSOFT** [comment]
Cool, let me study awhile for write js test code.

**Comment by sokra** [comment]
Is using env vars the best idea for that?

What do you think about using config options for that `infrastructureLogging.colors: false/true` and `infrastructureLogging.appendOnly: false/true`?

**Comment by KENNYSOFT** [comment]
Ooh that's cool also.

**Comment by KENNYSOFT** [comment]
BTW if we use something like `infrastructureLogging.colors` we should also provide `force` value to address this issue.

**Comment by alexander-akait** [comment]
@KENNYSOFT Byt with this option, you can do it in `webpack.config.js`

**Comment by KENNYSOFT** [comment]
@alexander-akait Do you mean it's already implemented? I cannot find :(

**Comment by alexander-akait** [comment]
@KENNYSOFT No, it is not implemented

> we should also provide force value to address this issue.

Why you need force here?

**Comment by KENNYSOFT** [comment]
Ah, may not. I've seen some programs ignore color flags even manually set when using in non-TTY environment. So if I implement without ignoring when TTY then it's not needed.

**Comment by alexander-akait** [comment]
We can provide option to disable/enable colors for `infrastructureLogging` and you can implement any logic on own side

**Comment by KENNYSOFT** [comment]
Yup it's great. So someone will want:

```js
infrastructureLogging: {
  colors: process.stderr.isTTY && process.env.TERM !== "dumb",
  ...
}
```

just like now, or I will want:

```js
infrastructureLogging: {
  colors: true,
  ...
}
```

to force set colors everywhere!
