### ISSUE TITLE
Webpack skips changes to files when compilation is suspended

### ISSUE THREAD

**Issue by vladar** [webpack/webpack#12898]
# Bug report

**What is the current behavior?**

This is an issue with `suspend` and `resume` flow of `Watching`. The second and subsequent aggregated changes that occur after `suspend` are dismissed by webpack.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Call [`suspend`](https://github.com/webpack/webpack/blob/58dfda2796edc57c9d18526053d6bcde6f06b8b7/lib/Watching.js#L320).
2. Edit file1 
3. Wait when aggregation timeout passes (and `aggregated` watchpack event fires)
4. Edit file2
5. Call [`resume`](https://github.com/webpack/webpack/blob/58dfda2796edc57c9d18526053d6bcde6f06b8b7/lib/Watching.js#L324).

**What is the expected behavior?**

The compilation contains changes from both `file1` and `file2`

**Actual result**: only changes from `file1` are applied. Changes to `file2` are skipped by webpack.

I've opened a PR with a failing test that demonstrates the problem (and suggested fix): #12897

**Other relevant information:**
webpack version:  latest (but also exists in v4 latest)
Node.js version: 12
Operating System: Windows
Additional tools: no

**Comment by alexander-akait** [comment]
Please prefer to use the one issue to track all problems with `suspend` and `resume`, looks it is side effects of the one problem

**Comment by vladar** [comment]
No, those are actually different bugs (they hit different codepaths). Fixing one won't fix the other. That's why I've opened two issues.

**Comment by alexander-akait** [comment]
Fixed by https://github.com/webpack/webpack/pull/13399
