### ISSUE TITLE
Do you have more detailed documentation for plugins ？

### ISSUE THREAD

**Issue by mayu888** [webpack/webpack#12895]
I'm going to write a plugin to modify the code in the JS file, but I have too many doubts by looking at the official documents. The plugin has too many hooks. What should the hooks in each stage do? Is there a detailed tutorial?

**Comment by mayu888** [comment]
我的目的是编译前在js/jsx文件以及css文件中修改我的部分代码，但是我不知道在哪个钩子内做这些事，有比较详细的文档吗？

**Comment by mayu888** [comment]
My goal is to modify some of my code in js/jsx and CSS files before compiling, but I don't know which hook to do these things. Do you have a more detailed document?

**Comment by alexander-akait** [comment]
You need to implement own `loader` in this case, but you can apply loader inside plugin, example https://github.com/webpack-contrib/image-minimizer-webpack-plugin/blob/master/src/index.js#L255, please use `Discussions` for questions, thanks

If you need add something after bundling you can use `processAssets` hook, example here https://github.com/webpack-contrib/image-minimizer-webpack-plugin/blob/master/src/index.js#L287

**Comment by alexander-akait** [comment]
Also if you need better docs about it, feel free to open issue in docs repo https://github.com/webpack/webpack.js.org
