### ISSUE TITLE
Query to aliased resource with loader

### ISSUE THREAD

**Issue by kisenka** [webpack/webpack#1289]
How can I pass [query](http://webpack.github.io/docs/loaders.html#resourcequery) to aliased resource which is processed by custom loader?
Following setup doesn't work:

**webpack.config.js**
```js
resolve: {
  alias: {
    'super-alias': path.join(__dirname, 'lib', 'my-module.js')
  }
},
module: {
  loaders: [
    {
      test: /my-module/,
      loader: path.resolve(__dirname, 'lib', 'loaders', 'my-custom-loader.js')
    }
  ]
}
```

Entry point
```js
require('super-alias?qwe=123');
```

**my-custom-loader**
```js
module.exports = function (content, sourceMap) {
  console.log(this.resourceQuery); // null
};
```

**Comment by jbrantly** [comment]
If I'm not mistaken a similar issue exists with resolveLoader aliases.
```
resolveLoader: {
  alias: { 'myLoader': require('path').join(__dirname, "../../index.js") }
},
 module: {
  loaders: [
    { test: /\.js$/, loader: 'myLoader?someOption=true' }
  ]
}
```

`this.query` is blank in the loader.

But doing `{ test: /\.js$/, loader: '../../index.js?someOption=true' }` works fine, `this.query` is populated correctly.

**Comment by rpora** [comment]
Hi! 

I also encounter this bug, and I found that this is related to
[enhanced-resolve/ModuleAliasPlugin](https://github.com/webpack/enhanced-resolve/blob/master/lib/ModuleAliasPlugin.js#L26) that does not take into account the original query to create the newRequest.

So, obj.query is inevitably null.

```
var obj = {
	path: request.path,
	request: newRequest.path,
	query: newRequest.query,
	directory: newRequest.directory
};
```

I  [fixed it and added a test case](https://github.com/rpora/enhanced-resolve/commit/1be777baccebf81ccc9bba059fd831b344509c94) .  

With this commit, I can do

```
resolveLoader: {
  alias: { 'myLoader': require('path').join(__dirname, "./my-loader.js") }
},
 module: {
  loaders: [
    { test: /\.js$/, loader: 'myLoader?someOption=true' }
  ]
}
```
and still access the query.

All tests are green, but I'm not sure this is the right place to fix this bug.  

@sokra :  Hi!  What do you think about it? Should I PR or am I wrong??

**Comment by AlbertoElias** [comment]
It would be amazing to have this fixed. Thanks @rpora for it. Hopefully you'll be given the good to go soon :)

**Comment by kisenka** [comment]
@sokra could you kindly check @rpora's fix?

**Comment by Kreozot** [comment]
@rpora, did you do pull request for this commit?

**Comment by rpora** [comment]
Hi! 
Yes, it's done! :)

**Comment by bebraw** [comment]
Looks like this was resolved in https://github.com/webpack/enhanced-resolve/pull/22 .
