### ISSUE TITLE
css module `import * as` not work after upgrade to webpack5

### ISSUE THREAD

**Issue by monic-shixi** [webpack/webpack#12904]
# Bug report

I had update webpack4 to webpack5, but some css module not work.

For example:
   
```js
// ...
{
  test: /\.module\.css$/,
  use: [
    isEnvDevelopment && require.resolve('style-loader'), 
    isEnvProduction && require("mini-css-extract-plugin").loader, 
    {
      loader: 'css-loader',
      options: {
        importLoaders: 1,
        modules: {
          compileType: 'module',
          exportLocalsConvention: 'camelCase',
          localIdentName: '[name]_[local]_[hash:8]'
        },
        esModule: false
      }
    },
    // ... postcssLoader, 
    // ... lessLoader
  ].filter(Boolean)
}
// ...
```

```css
/* xxx.module.css */
.root {
	color: #fff;
}
```

### not work

- env
   - **webpack@5.16.0**
   - css-loader@5.0.1

```js
// a.jsx
import * as styles from './xxx.module.css'
import ss from './xxx.module.css'

console.log(styles) //  Module {__esModule: true, Symbol(Symbol.toStringTag): "Module"}
console.log(ss) // {root: "[name]_root_[hash]"}
```

### work

- env
   - **webpack@4.35.0**
   - css-loader@5.0.1  

```js
// a.jsx
import * as styles from './xxx.module.css'
import ss from './xxx.module.css'

console.log(styles) //  {root: "[name]_root_[hash]"}
console.log(ss) // {root: "[name]_root_[hash]"}
```

I had read change log, so, it's because of `tree-shaking`? But i had set `sideEffects: true`, that not work.

**What is the current behavior?**
If css imported by `import * as xxx from '*.css'`, the style not work.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
`import * as xxx from '*.css'` work, likes webpack5

**Other relevant information:**
webpack version:  5.16.0
Node.js version: 12.13.1
Operating System: macOS Mojave
Additional tools:

**Comment by alexander-akait** [comment]
You should not disable `esModule` (i.e. remove this option), not related to webpack

**Comment by monic-shixi** [comment]
> You should not disable `esModule` (i.e. remove this option or set `esModule: true`), not related to webpack

No. If `esModule: true` in option:

- env
   - webpack@4.35.0
   - css-loader@5.0.1


```js
// a.jsx
import * as styles from './xxx.module.css'
import ss from './xxx.module.css'

console.log(styles) //  {}
console.log(ss) // {}
```
So, i think it's because of webpack.

**Comment by alexander-akait** [comment]
No problems on webpack side, if you need help please open an issue in `css-loader` and provide simple reproducible test repo

**Comment by monic-shixi** [comment]
> No problems on webpack side, if you need help please open an issue in `css-loader` and provide simple reproducible test repo

Ok, thanks for you response.
