### ISSUE TITLE
Export source asset module to default 

### ISSUE THREAD

**Issue by rashkov** [webpack/webpack#12903]
https://github.com/webpack/webpack/blob/2abcede6cd044d3424b072ccf06ab076ae1cdb19/lib/asset/AssetSourceGenerator.js#L42

can we modify this to support exporting to the “default” keyword? I’m unable to use this loader in my code base because it only uses require().

**Comment by sokra** [comment]
> I’m unable to use this loader in my code base because it only uses require().

This is not a loader. This is webpacks internal format of defining modules.

I don't understand why you are unable to use it. You can `import` or `require` it.

**Comment by rashkov** [comment]
@sokra thanks for your super quick response. You were right, I can require() it just fine. I'm using Rescript lang, and my module binding was incorrect on the Rescript side, so it was transpiling to require("asset").default instead of just require("asset").

Thanks again. Closing this issue.

**Comment by AviVahl** [comment]
@sokra existing code that used `file-loader` or `raw-loader` got an es module in the last stable releases.
so if someone imported a file directly using commonjs, they usually added `.default` lookup to the request.
it makes it a bit trickier to migrate existing code when moving from the loaders to the new built in functionality.
would u consider making it esm by default (with esModuleInterop) or making it configurable?

**Comment by barak007** [comment]
We have such case in a large codebase that prevent us from move forward to webpack5 `AssetModules`. In my opinion making it configurable will do the trick

**Comment by alexander-akait** [comment]
@AviVahl @barak007 It is internal webpack format and it is always use exports as `default`. Example:

**webpack.config.js**

```js
module.exports = {
    mode: 'development',
    devtool: false,
    entry: './entry.js',
    output: {
        filename: '[name].js',
    },
    module: {
        rules: [
            {
                test: /\.txt$/,
                type: 'asset/source',
            },
        ],
    },
};
```

**entry.js**

```js
import one from './test.txt';

const two = require('./test.txt');

console.log(one);
console.log(two);
```

**test.txt**

```
RAW
```

Output:
```
RAW
RAW
```

Same for `asset/resource` and `asset/inline`

You don't need to use `default`, it is always `default` for ES modules and for commonjs.

**Comment by alexander-akait** [comment]
Yes, it is breaking change between `file-loader`/`url-loader`/`raw-loader` and `assets` modules, I don't think we really need to create a new option here, you can use `file-loader`/etc right now and start to migrate using `test`/`include`/`exclude` step by step
