### ISSUE TITLE
SUGGESTION: Please allow if(require) { require(...); } 

### ISSUE THREAD

**Issue by jlchereau** [webpack/webpack#1290]
At the present time, the following works (1):

```
require(...);
require(...);
require(...);

// more code
```

But the following does not work (2):

```
if (require) {
    require(...);
    require(...);
    require(...);
}

// more code
```

It would be nice if (2) could work so as to allow the use of scripts built for webpack in a non-webpack way, especially for unit tests where you do not want a full build.

**Comment by sokra** [comment]
`if(typeof require === "function")`

**Comment by IngwiePhoenix** [comment]
DefinePlugin can also define expressions as far as i know, never tested.


new DefinePlugin({ "if(require)“:"if(true)" });
