### ISSUE TITLE
__webpack_modules__[moduleId] is not a function with webpack >= 5.24.0

### ISSUE THREAD

**Issue by vladimir-tikhonov** [webpack/webpack#12914]
# Bug report

**What is the current behavior?**

Starting from webpack@5.24.0 webpack generates bundles with a `__webpack_require__(null)` inside, leading to a runtime error.

**If the current behavior is a bug, please provide the steps to reproduce.**

Here's the minimal example - https://github.com/vladimir-tikhonov/webpack-bug. It works without webpack and with webpack@5.23. There is a circular reference inside, which, however, is not a problem as referenced class is used only in runtime.

**What is the expected behavior?**

No exceptions in runtime, as it's a perfectly valid set of ES6 modules.

**Other relevant information:**
webpack version: any  >= 5.24.0
Node.js version: 12.14.1
Operating System:  MacOS
Additional tools: none

**Comment by alexander-akait** [comment]
You should not use `concatenateModules: true` and `new webpack.optimize.ModuleConcatenationPlugin()`, just only one, otherwise you will have two plugins and it is unsafe, it is limitation

**Comment by vladimir-tikhonov** [comment]
@alexander-akait huh, my bad, for some reason I thought that those are related. Thanks for the help!

**Comment by alexander-akait** [comment]
In future you can look here https://github.com/webpack/webpack/blob/master/lib/WebpackOptionsApply.js to check it, for the `concatenateModules` option our logic is  https://github.com/webpack/webpack/blob/master/lib/WebpackOptionsApply.js#L376
