### ISSUE TITLE
Invalid configuration object

### ISSUE THREAD

**Issue by hugoebarboza** [webpack/webpack#12910]
# Bug report

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

{
"name": "mf-demo",
"version": "0.0.0",
"scripts": {
"ng": "ng",
"start": "npm run start:shell",
"start:shell": "ng serve shell -o --port 5000",
"start:mfe1": "ng serve mfe1 -o --port 3000",
"start:all": "concurrently "npm run start:shell" "npm run start:mfe1" ",
"build:shell": "ng build shell --prod",
"build:mfe1": "ng build mfe1 --prod",
"serve:dist": "concurrently "serve dist/shell -l 5000 -s" "serve dist/mfe1 -l 3000 -s" ",
"build": "npm run build:shell && npm run build:mfe1",
"test": "ng test",
"lint": "ng lint",
"e2e": "ng e2e"
},
"private": true,
"resolutions": {
"webpack": "^5.0.0"
},
"dependencies": {
"@angular-architects/module-federation": "^1.2.3",
"@angular/animations": "11.2.4",
"@angular/common": "11.2.4",
"@angular/compiler": "^11.2.4",
"@angular/core": "^11.2.4",
"@angular/forms": "11.2.4",
"@angular/platform-browser": "11.2.4",
"@angular/platform-browser-dynamic": "11.2.4",
"@angular/router": "11.2.4",
"@nrwl/workspace": "^11.4.0",
"concurrently": "^6.0.0",
"rxjs": "^6.6.6",
"tslib": "^2.1.0",
"zone.js": "~0.11.4"
},
"devDependencies": {
"@angular-devkit/build-angular": "^0.1102.3",
"@angular/cli": "11.2.3",
"@angular/compiler-cli": "^11.2.4",
"@types/jasmine": "~3.6.6",
"@types/jasminewd2": "~2.0.8",
"@types/node": "^14.14.33",
"codelyzer": "^6.0.1",
"jasmine-core": "~3.6.0",
"jasmine-spec-reporter": "~6.0.0",
"karma": "~6.1.2",
"karma-chrome-launcher": "~3.1.0",
"karma-coverage": "~2.0.3",
"karma-jasmine": "~4.0.1",
"karma-jasmine-html-reporter": "^1.5.4",
"ngx-build-plus": "^11.0.0",
"protractor": "~7.0.0",
"serve": "^11.3.2",
"ts-node": "~9.1.1",
"tslint": "~6.1.0",
"typescript": "^4.1.5"
}
}

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Please respect time of other developers, won't fix
