### ISSUE TITLE
Async chunk loading breaks complex expressions in globalObject option

### ISSUE THREAD

**Issue by noppa** [webpack/webpack#12924]
# Bug report

**What is the current behavior?**

```javascript
// webpack.config.js
  output: {
    library: 'myLib',
    libraryTarget: 'umd',
    globalObject: 'typeof self !== \'undefined\' ? self : this',
  },
  optimization: {
    splitChunks: {
      chunks: 'all',
      minSize: 1,
    }
  }

// index.js
  await import('./chunk')
```
generates code
```javascript
var chunkLoadingGlobal = typeof self !== 'undefined' ? self : this["webpackChunkmyLib"] = typeof self !== 'undefined' ? self : this["webpackChunkmyLib"] || [];
/******/ 		chunkLoadingGlobal.forEach(webpackJsonpCallback.bind(null, 0));
```
The ternary expression for `globalObject` isn't protected as an expression, but gets mixed with the surrounding code.
In case the condition is true (`typeof self !== 'undefined'`) and consequent path is taken, the result of this expression ends up being the equivalent of
```javascript
var chunkLoadingGlobal = self
```
which then throws in the next line
```
Uncaught TypeError: chunkLoadingGlobal.forEach is not a function
```

Similar code also gets generated to the async chunk
```javascript
typeof self !== 'undefined' ? self : this["webpackChunkmyLib"] = 
```
which would also fail if the execution ever got that far.

**If the current behavior is a bug, please provide the steps to reproduce.**
Full minimal reproducible example in [noppa/webpack-global-object-issue-repro](https://github.com/noppa/webpack-global-object-issue-repro).

**What is the expected behavior?**
The code in `globalObject` option should be treated as an arbitrary expression and either lifted to a variable or wrapped in parenthesis
```javascript
var root = typeof self !== 'undefined' ? self : this
var chunkLoadingGlobal = root["webpackChunkmyLib"] = root["webpackChunkmyLib"] || [];
```

The problem is easily enough fixed on the user's side:
```diff
-     globalObject: 'typeof self !== \'undefined\' ? self : this',
+     globalObject: '(typeof self !== \'undefined\' ? self : this)',
```
and I get that this issue could end up closed as "working as intended". However, I think that this limitation should then at least be mentioned in the docs and/or some kind of warning should be given. The nasty thing about the current behavior is that the code only breaks under very specific conditions:
  1. The app must contain async chunks. Without them, `globalObject` is only used in expression
    ```  
         })(typeof self !== 'undefined' ? self : this, function() {
    ```
    which doesn't break the way the `chunkLoadingGlobal` code does. Simply adding `/* webpackMode: "eager" */ ` to the import will "fix" the issue.
  2. The condition in ternary must be true, as the RHS of the ternary actually works fine. In practice this means that the app crashes in browser (where `self` is defined) but not in Node. 

Thus, the broken `globalObject` code is already widely used in the wild: [grep.app search for unparenthesized ternaries in globalObject option](https://grep.app/search?q=globalObject%5B%22%27%60%5D%3F%3A%20%5B%22%27%60%5D%5B%5E%28%5D.%2A%5C%3F.%2A%3A.%2A%5B%22%27%60%5D&regexp=true).

I believe that at least these issues could be caused by this:
* [StackOverflow jsonpArray.push is undefined when the output library code splits](https://stackoverflow.com/questions/50896811/vue-cli-3-0-jsonparray-push-is-undefined-when-the-output-library-code-splits)
* [Related issue in vue-cli](https://github.com/vuejs/vue-cli/issues/1607)
* #9766 not for the OP of that issue but maybe for the commenters saying that setting `jsonpFunction` didn't fix the issue for them

**Other relevant information:**
webpack version:  5.26.3 and 4.46.0
Node.js version: 15.6.0
Operating System:
Additional tools:

**Comment by alexander-akait** [comment]
To be honestly using `()` is always good, because it is always protect your code, but yes we can fix it

**Comment by alexander-akait** [comment]
Still valid
