### ISSUE TITLE
New Asset Modules type: asset/null, to properly replace null-loader

### ISSUE THREAD

**Issue by ferdinando-ferreira** [webpack/webpack#12920]
## Feature request
New asset module type: `asset/null`, to properly replace the now deprecated `null-loader`

**What is the expected behavior?**
```javascript
    rules: [
      ...
      {
        test: /\.css$/,
        type: 'asset/null'
      }
    ]
```

To replace the use of the now deprecated `null-loader` in situations analogous to the following

```javascript
    rules: [
      ...
      {
        test: /\.css$/,
        use: [
          { loader: "null-loader" }
        ]
      }
    ]
```
That is: to tell webpack to ignore a module but, instead of based on a name, to ignore a module based on a rule.

**What is motivation or use case for adding/changing the behavior?**

The [documented way to replace the use of `null-loader`](https://webpack.js.org/configuration/resolve/#resolvealias)

> Setting resolve.alias.package to false will tell webpack@5 to ignore a module.

 does not correctly replace the deprecated loader.

In particular, it does not allow webpack to prevent modules from being imported based on a rule, which was one the uses for `null-loader`.

Using resolve.alias also implies that the name of the modules to be ignored are known when creating the webpack config, which is not always true or even possible.

**How should this be implemented in your opinion?**

With the creation of a new type for asset modules: `asset/null`. 

The change is also consistent with how the other deprecated modules were dealt with

 * `asset/resource` replaced `file-loader`
 * `asset/inline` replaced `url-loader`
 * `asset/source` replaced `raw-loader`

With this proposal `asset/null` would replace `null-loader`

**Are you willing to work on this yourself?**

Yes, if directed to the appropriate parts of the code

**Comment by alexander-akait** [comment]
`asset` modules for assets, there is no `null`, you can use to ignore any `require`/`import`, also it is unsafe and will be broken with CSS modules, because you lose all locals

**Comment by alexander-akait** [comment]
For real assets, you can use `emit: false` https://github.com/webpack/webpack/pull/12871

**Comment by alexander-akait** [comment]
Also you can use `asset/inline` and `generator.dataUrl: () => 'data:,0'` also

**Comment by ferdinando-ferreira** [comment]
> Also you can use `asset/inline` and `generator.dataUrl: () => 'data:,'` also

@alexander-akait : OK, that works for me, except `() => ''`. Thanks!

**Comment by alexander-akait** [comment]
@ferdinando-ferreira anyway, let's reopen original issue, I think we need this option

**Comment by ferdinando-ferreira** [comment]
> I think we need this option

Thanks! I can submit a PR for it if you guys want.

**Comment by alexander-akait** [comment]
Yep, let's do it

**Comment by ferdinando-ferreira** [comment]
> Yep, let's do it

@alexander-akait: when you say `original issue` you mean 12920, right?

**Comment by alexander-akait** [comment]
Mean this https://github.com/webpack-contrib/mini-css-extract-plugin/issues/713

**Comment by ferdinando-ferreira** [comment]
Right. The original PR had a technical issue. Should I redo it but on the loader side instead of on the plugin?

**Comment by alexander-akait** [comment]
Ideally we should not run plugin, just create locals and return them
