### ISSUE TITLE
Production mode compilation throws socket.io 404 error

### ISSUE THREAD

**Issue by madhavan020985** [webpack/webpack#1292]
I compiled my app.jsx file using the command, webpack -p (webpack versioned 1.8.9). And i tried to load my index.html page using a node-static server. Webpack now bombards my shell terminal with warning messages as, 
````javascript
20:28:48 [404]: /socket.io/?EIO=3&transport=polling&t=1437749928591-2656
..............................................................................(repetitively prints same stuff)
````
My webpack.config.js looks like,
````javascript
var webpack = require('webpack');
var path = require('path');

module.exports = {
  entry: {
    'app.js': './client/app.jsx'
  },
  output: {
    filename: path.join('dist', 'app.js')
  },
  resolve : {
    extensions: ['', '.js', '.jsx']
  },
  module: {
    loaders: [
      {test: /\.jsx$/, loaders: ['babel']},
    ],
  }
};
````

**Comment by bebraw** [comment]
@madhavan020985 Are you still seeing the same issue?

**Comment by ghyonimor** [comment]
I'm having the same issue.

**Comment by madhavan020985** [comment]
@Bartekus ebraw, i can't confirm, since i moved out from this work...... but i will keep it open, to address on @ghyonimor
