### ISSUE TITLE
"imports" field support

### ISSUE THREAD

**Issue by guybedford** [webpack/webpack#12928]
## Feature request

In addition to the `"exports"` field, Node.js also defines the [`"imports"` field](https://nodejs.org/dist/latest-v15.x/docs/api/packages.html#packages_imports) to permit private internal resolutions to simplify backtracking and local conditional resolution cases. As far as I can tell this field isn't yet supported in Webpack.

**What is the expected behavior?**

When writing a package.json with an `"imports"` field, the `#private` specifier resolutions should resolve through these rules analogously to the exports field.

**What is motivation or use case for adding/changing the behavior?**

Node.js resolver support parity.

**How should this be implemented in your opinion?**

It's a similar extension to the exports field and exports package "own name" resolution.

**Are you willing to work on this yourself?**

Possibly!

**Comment by alexander-akait** [comment]
We already support it

**Comment by alexander-akait** [comment]
https://github.com/webpack/enhanced-resolve/blob/master/lib/ImportsFieldPlugin.js

**Comment by guybedford** [comment]
I've posted a failing test here in https://github.com/webpack/webpack/pull/12929.

**Comment by zdm** [comment]
How to make it works?
I got error
```
Module not found: Error: Can't resolve '#internal'
```
