### ISSUE TITLE
Cannot read property 'updateHash' of undefined

### ISSUE THREAD

**Issue by zhangchao828** [webpack/webpack#12934]
# Bug report

**What is the current behavior?**
Cannot read property 'updateHash' of undefined with experiments.lazyCompilation=true

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
experiments.lazyCompilation work well

**Other relevant information:**
webpack version:  5.26.3
Node.js version: 14.15.0
Operating System: window
Additional tools:

**Comment by sokra** [comment]
Looks like a bug. Could you provide further information?

**Comment by alexander-akait** [comment]
@zhangchao828 Never ignore `If the current behavior is a bug, please provide the steps to reproduce.`, otherwise issue will be closed

**Comment by zhangchao828** [comment]
> @zhangchao828 Never ignore `If the current behavior is a bug, please provide the steps to reproduce.`, otherwise issue will be closed

I'll give you an example later

**Comment by zhangchao828** [comment]
[https://github.com/zhangchao828/webpack-demo](url)
@sokra @alexander-akait 
1. clone the repository
2. install dependencies
3. yarn start
4. click link in the browser
5. then you'll see the error: Cannot read property 'updateHash' of undefined

**Comment by alexander-akait** [comment]
@zhangchao828 Thanks

**Comment by alexander-akait** [comment]
Fixed in `5.27.2`, please update
