### ISSUE TITLE
Regression: rule not accepted anymore by schema in v5

### ISSUE THREAD

**Issue by EECOLOR** [webpack/webpack#12940]
# Bug report

**What is the current behavior?**

Rule in the `module` section is not accepted anymore by the the schema. The error is:

`configuration.module.rules[0].oneOf[6].resource.or[0] has an unknown property 'exclude'. These properties are valid:
   object { and?, not?, or? }`

**If the current behavior is a bug, please provide the steps to reproduce.**

```js
{
  rules: [{ oneOf: [
    ...,
    {
      resource: {
        test: /(\.html\.js|\.js|\.mjs)$/,
        or: [{ exclude: /node_modules/ }, ...compileWithBabel],
      },
      loaders: [babelLoader]
    },
    ...
  ] }]
}
```

**What is the expected behavior?**

That it would be accepted by the [schema](https://github.com/webpack/webpack/blob/master/schemas/WebpackOptions.json). I am not very fluent in reading the schema, but it seems that it is not possible anymore to use any object other than one containing `or`, `not` and `and` withing an `or`, `not` or `and`.

This is the description of `rule.test`: `"Shortcut for resource.test."`. The `resource` rule however looks like this:

```
        "resource": {
          "description": "Match the resource path of the module.",
          "oneOf": [
            {
              "$ref": "#/definitions/RuleSetConditionOrConditionsAbsolute"
            }
          ]
        },
```

And as far as I can tell, the `RuleSetConditionOrConditionsAbsolute` does not contain a `test` property.

Alternatively, if this was a conscious change I expected it to be mentioned in https://webpack.js.org/migrate/5/ or https://github.com/webpack/changelog-v5#minor-changes

**Other relevant information:**
webpack version:  5

If there is another way to formulate this rule I am happy to change it.

**Comment by EECOLOR** [comment]
If I change the rule to this:

```
        {
          resource: {
            test: /(\.html\.js|\.js|\.mjs)$/,
            or: [{ not: /node_modules/ }, ...compileWithBabel],
          },
          loaders: [babelLoader]
        },
```

I get this error:

```
- configuration.module.rules[0] should be one of these:
   ["..." | object { compiler?, dependency?, descriptionData?, enforce?, exclude?, generator?, include?, issuer?, issuerLayer?, layer?, loader?, mimetype?, oneOf?, options?, parser?, realResource?, resolve?, resource?, resourceFragment?, resourceQuery?, rules?, sideEffects?, test?, type?, use? }, ...]
   -> A rule.
   Details:
    * configuration.module.rules[0].oneOf[6].resource.or[0].not should be an array:
      [RegExp | string | object { and?, not?, or? } | function | [(recursive), ...], ...]
      -> A list of rule conditions matching an absolute path.
    * configuration.module.rules[0].oneOf[6].resource.or[0].not should be one of these:
      [RegExp | string | object { and?, not?, or? } | function | [(recursive), ...], ...]
      -> Logical NOT.
```
---
And if I change it to this:

```
        {
          resource: {
            test: /(\.html\.js|\.js|\.mjs)$/,
            or: [{ not: [/node_modules/] }, ...compileWithBabel],
          },
          loaders: [babelLoader]
        },
```

I get this error:

```
 - configuration.module.rules[0].oneOf[6].resource has an unknown property 'test'. These properties are valid:
   object { and?, not?, or? }
```

And that one feels kinda weird considering the following comments in the documentation:

> `Rule.test` is a shortcut to `Rule.resource.test`. If you supply a `Rule.test` option, you cannot also supply a `Rule.resource`. See `Rule.resource` and `Condition.test` for details.

**Comment by sokra** [comment]
There is no test within resource. You can only use `and`, `or` and `not` since webpack 5.

**Comment by EECOLOR** [comment]
From the documentation:

> Include all modules that pass test assertion. If you supply a `Rule.test` option, you cannot also supply a `Rule.resource`. See `Rule.resource` and `Condition.test` for details.

There is also no `Condition.test` I think

---

Just to understand the new structure better, is this:

```js
{
  test: 'a',
  exclude: 'b',
}
```

The same as?

```js
{
  resource: {
    and: ['a', { not: 'b' }]
  }
}
```

**Comment by EECOLOR** [comment]
Maybe resource is an `and` by it self, and it could be simplified to:

```js
{
  resource: ['a', { not: 'b' }]
}
```

**Comment by EECOLOR** [comment]
I don't think time should be spend on this issue. I naively thought I could quickly switch to v5, but after reading some of the motivation I realized this is not going to be that kind of upgrade.

We will re-evaluatate our configuration and plugins, quite a few things have become obsolete by new features in v5. It is gonna be quite some work to get things implemented a backwards compatible fashion, but that is fine. I understand the motivation and I think the steps taken by the webpack team are in the right direction.
