### ISSUE TITLE
Undetermined shared module version in federated module for specific dependency

### ISSUE THREAD

**Issue by itsjoesullivan** [webpack/webpack#12942]
# Bug report

**What is the current behavior?**

When using the @apollo/client dependency in a webpack build in which react is a module that is shared through the federated modules plugin, the version of react that @apollo/client requires is not determined, resulting in the following error:

```
WARNING in shared module react
No required version specified and unable to automatically determine one. Unable to find required version for "react" in description file (.../module-federation-examples/basic-host-remote/app2/node_modules/@apollo/client/react/hooks/package.json). It need to be in dependencies, devDependencies or peerDependencies.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Install basic-host-remote federated modules example (https://github.com/module-federation/module-federation-examples/tree/master/basic-host-remote)
2. Add @apollo/client and graphql libraries to app2, resulting in a package.json for app2 like:
```
{
  "dependencies": {
    "@apollo/client": "^3.3.12",
    "graphql": "^15.5.0",
    "react": "^16.13.0",
    "react-dom": "^16.13.0"
}
```

3. Start app2

You will see the following warning:

```
WARNING in shared module react
No required version specified and unable to automatically determine one. Unable to find required version for "react" in description file (.../module-federation-examples/basic-host-remote/app2/node_modules/@apollo/client/react/hooks/package.json). It need to be in dependencies, devDependencies or peerDependencies.
```

This results from the existence of a package.json file at `/react/hooks/package.json` that does not reflect the dependencies required by the files contained in that directory. These package.json files are created at publish time inside the @apollo/client repo, [here](https://github.com/apollographql/apollo-client/blob/main/config/prepareDist.js#L62).

[`getDescriptionFile`](https://github.com/webpack/webpack/blob/911ec1aa67011e25aa1449610f5b0b557edd5459/lib/sharing/utils.js#L27) is accepting this package.json file as the source of truth for the required versions of react, and of course there is no value there. In practice, the package's root-level package.json is the source of truth for the required version of react.

**What is the expected behavior?**

Because the @apollo/client package is certainly defining a react version, you might expect the version to be identified and for this warning not to appear. It would be nice in this case for `getDescriptionFile` to keep searching all the way to the root package.json file. However, I also understand that this case, where there are supplementary package.json files intended directly to throw dependency-checking off, is rather unique.

I'm reporting this here first to see if it's a case federated modules / webpack would like to handle.

**Other relevant information:**
webpack version:  5.27.1
Node.js version: v12.21.0
Operating System: OSX 11.2.1
Additional tools:

**Comment by alexander-akait** [comment]
> It would be nice in this case for getDescriptionFile to keep searching all the way to the root package.json file. However, I also understand that this case, where there are supplementary package.json files intended directly to throw dependency-checking off, is rather unique.

Sorry out of scope webpack, you can implement this logic on your side

**Comment by tmkasun** [comment]
I also get the same kind of error in a different context, when using `lerna` to manage mono repos.

```
react_module_federation_app1: No required version specified and unable to automatically determine one. Unable to find required version for "react" in description file (/Users/user/testing/modulefederation/host/package.json). It need to be in dependencies, devDependencies or peerDependencies.
```

I have moved `react` and `react-dom` to root level `package.json` and it seems that `ModuleFederationPlugin` is cross-validating the `shared` dependencies in the `package.json` file ?

Can we ignore this warning or is there an alternative way to provide the version of shared dependency?
