### ISSUE TITLE
Incorrect source URL in source maps when sources not under context hierarchy

### ISSUE THREAD

**Issue by ilgonmic** [webpack/webpack#12951]
# Bug report

**What is the current behavior?**
There is project layout
|- js
|-- packages
|--- lib
|---- `package.json`
|---- `webpack.config.js`
|---- compiled
|----- `my.js`
|----- `my.js.map`
|- lib
|-- `My.kt`

Imagine that `my.js` was produced from `My.kt` and `my.js.map` is appropriate source map, `sources` field in source map is something like `["../../../../lib/My.kt"]`.
NPM project (`package.json` and `node_modules`) is not in the same directory hierarchy as original `My.kt` file.
I use `devtoolModuleFilenameTemplate: "[absolute-resource-path]"` setting to get only absolute paths of files in output source map.

In output source map I get `sources` field:
`["webpack/universalModuleDefinition","/Users/ilya.goncharov/reproducers/webpack5-devtool/js/packages/lib/My.kt"]`
The second file is not correct location of original file.

**If the current behavior is a bug, please provide the steps to reproduce.**

Link to the repro: https://github.com/ilgonmic/webpack5-devtool

**What is the expected behavior?**

In output source map I want to get correct `sources` field with original locations.
`["webpack/universalModuleDefinition","/Users/ilya.goncharov/reproducers/webpack5-devtool/lib/My.kt"]`

**Other relevant information:**
webpack version:  5.27.1
Node.js version: v15.4.0
Operating System: macOS Big Sur (version 11.2.2)

**Some investigations:**
There was no such problem with `webpack-4`.
Now in `NormalModule.js` on creating `SourceMapSource` `contextifySourceMap` is used
- https://github.com/webpack/webpack/blob/master/lib/NormalModule.js#L406
- https://github.com/webpack/webpack/blob/master/lib/NormalModule.js#L635

It leads to polluting of source maps with additional `webpack://` protocol.
When it is passed to `source-map` through [SourceMapConsumer](https://github.com/webpack/webpack-sources/blob/master/lib/helpers.js#L60), it is [normalized](https://github.com/mozilla/source-map/blob/83b8bbd5837d8c3f66095f7834b24ed7fbc1ed24/lib/source-map-consumer.js#L178) and then "redundant" `..` [is removed](https://github.com/mozilla/source-map/blob/83b8bbd5837d8c3f66095f7834b24ed7fbc1ed24/lib/util.js#L117) because it is detected not as absolute path but as URL.

So without `contextify` we get correct result in this case, but with `contextify` generated path is incorrect.

Is there reason why `contextify` necessary?
And is there some workaround in my particular case?

I of course can prepare Pull Request, but I am wondering is it ok to just remove contextifies or could you please give some other advice to fix this behaviour?

**Comment by sokra** [comment]
yeah
