### ISSUE TITLE
export AsyncDependenciesBlock

### ISSUE THREAD

**Issue by jantimon** [webpack/webpack#12967]
## Feature request

**What is the expected behavior?**

most APIs are available in `compiler.webpack` unfortunately `AsyncDependenciesBlock` is not..  

would it make sense to add it?

**Are you willing to work on this yourself?**
yes

**Comment by barak007** [comment]
Same is true for `ModuleDependency`  can we take care of this in the same PR?

**Comment by sokra** [comment]
yeah send a PR

**Comment by jantimon** [comment]
Cool I'll try to create a pr during the day :)

**Comment by barak007** [comment]
@jantimon I opened a PR if you want to take a look. #12975
