### ISSUE TITLE
terser-webpack-plugin not importable with Yarn 2 + strict pnpMode

### ISSUE THREAD

**Issue by rdicroce** [webpack/webpack#12966]
# Bug report

The docs for terser-webpack-plugin state: `If you are using webpack v5 or above you do not need to install this plugin. Webpack v5 comes with the latest terser-webpack-plugin out of the box.` This is not quite true if you are using Yarn 2 with pnpMode = strict, and you want to provide a custom terser configuration.

**What is the current behavior?**

Adding `require('terser-webpack-plugin')` in webpack.config.js causes an error. The problem can be worked around by adding terser-webpack-plugin to the project's package.json alongside webpack. 

**If the current behavior is a bug, please provide the steps to reproduce.**

Should be able to reproduce with any project that uses Yarn 2, has webpack (but not terser-webpack-plugin) as a devDependency, and tries to require terser-webpack-plugin.

**What is the expected behavior?**

Adding `require('terser-webpack-plugin')` without explicitly installing terser-webpack-plugin should not cause an error.

With pnpMode = strict, Yarn 2 prevents access to packages not explicitly listed as a dependency. You can change this behavior by setting pnpMode = loose, but Yarn discourages that because it is [unsafe](https://yarnpkg.com/configuration/yarnrc#pnpMode). Yarn's [recommended solution](https://yarnpkg.com/advanced/rulebook#packages-should-only-ever-require-what-they-formally-list-in-their-dependencies) for meta-package situations like this is for the meta-package (webpack, in this case) to declare the dependency (terser-webpack-plugin) as both a dependency and a peerDependency.

**Other relevant information:**
webpack version: 5.26.3
Node.js version: 14.16.0
Operating System: Windows 10 Pro 20H2
Additional tools:

**Comment by alexander-akait** [comment]
When you add `require('terser-webpack-plugin')` in your code **you need to install package manually**

> Adding require('terser-webpack-plugin') without explicitly installing terser-webpack-plugin should not cause an error.

It is impossible, please read how package managers works

**Comment by rdicroce** [comment]
It is very much possible. In fact, it was the default behavior in Yarn 1. And it can be accomplished in Yarn 2, as explained by the docs I linked to.

**Comment by alexander-akait** [comment]
Yep, but it is wrong way
