### ISSUE TITLE
Support AMD when loading splitChunks 

### ISSUE THREAD

**Issue by Soombra** [webpack/webpack#12962]
## Feature request

**What is the expected behavior?**
Webpack use JsonP to load other chunks. wondering whether we can load chunks by requireJs?

**What is motivation or use case for adding/changing the behavior?**
in my case, i want to share common chunks among different compilations, and assets from different compilations maybe used in the same page. since we use JsonP to load chunks, the output.chunkLoadingGlobal  from certain compilation will be set in common chunk files. so between different compilations , we wont get common chunks  exactly the same, and common share is failed.

**How should this be implemented in your opinion?**
maybe supply a option that splitChunks can be loaded by AMD, so the splitChunks  dont have to set some logic related to the main chunk. so we can share among compilations

**Are you willing to work on this yourself?**
sorry，i would like to but maybe not qualified.

**Comment by alexander-akait** [comment]
Duplicate https://github.com/webpack/webpack/issues/5489
