### ISSUE TITLE
callAnyMember hook does not work (regarding a previous ticket)

### ISSUE THREAD

**Issue by fabis94** [webpack/webpack#12974]
# Bug report

**What is the current behavior?**

`callAnyMember` doesn't get invoked unless the callee of the CallExpression being looked at is an "identifier". 

See original ticket that was closed due to inactivity for more info: https://github.com/webpack/webpack/issues/9480

**If the current behavior is a bug, please provide the steps to reproduce.**

No reproduction, but here's the offending part from webpack's source code:
![image](https://user-images.githubusercontent.com/938316/112368976-574c9180-8ce4-11eb-95ef-ae4393f241f4.png)

The `BasicEvaluatedExpression` instance returned by `this.evaluateExpression()` has to have `isIdentifier` evaluate to `true`, otherwise it skips the entire branch that calls hooks like `callAnyMember` and `call`. 

I don't know what an "identifier" is in this context, I couldn't find anything about this topic in Google, but to me it seems arbitrary to have some function calls be reported on and not others based on this flag.

**What is the expected behavior?**

Well `callAnyMember` should do what the documentation says it does - it should be "triggered when parsing a call to a member function of an object." Currently if the callee of the CallExpression isn't an "identifier" (whatever that means) it just skips those hooks entirely, and this decision seems arbitrary.

This requires plugin devs to do hacks where the `evaluate` hook of the Parser is used to build custom `BasicEvaluatedExpression` instances that evaluate `isIdentifier` to `true`. Here's one such solution that I was able to find on GitHub, I'm going to do something similar: https://github.com/aurelia/webpack-plugin/blob/9f6f7983312c66f857e79b744e4ec257cc287b8b/dist/InlineViewDependenciesPlugin.js

**Other relevant information:**
webpack version:  4.46.0
Node.js version: 14.15.4
Operating System: macOS Catalina v10.15.7

**Comment by alexander-akait** [comment]
Sorry, you use outdated webpack version, only security fixes, please consider migration to v5, sorry again

**Comment by fabis94** [comment]
@alexander-akait is this at least fixed in v5 or does it have the same issue?

**Comment by alexander-akait** [comment]
We don't have `callAnyMember` in webpack v5 https://github.com/webpack/webpack/blob/master/lib/javascript/JavascriptParser.js#L2693, can you provide example of your code and what do you want achieve
