### ISSUE TITLE
configuration[1].module.generator.asset has an unknown property 'publicPath'

### ISSUE THREAD

**Issue by ppbl** [webpack/webpack#12982]
# Bug report

**What is the current behavior?**

Use module.generator.asset.publicPath error

```
configuration[1].module.generator.asset has an unknown property 'publicPath'
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Use module.generator.asset.publicPath

**What is the expected behavior?**

No error

**Other relevant information:**
webpack version:  5.28.0
Node.js version: 
Operating System: 
Additional tools:

**Comment by alexander-akait** [comment]
Here example of usage https://github.com/webpack/webpack/blob/master/test/configCases/asset-modules/generator-asset-publicPath/webpack.config.js, maybe you forget to update webpack to latest version, please run `npm ls webpack` and check the venison
