### ISSUE TITLE
Feature Request: Expose ModuleFederationPluginOptions in type definitions

### ISSUE THREAD

**Issue by adamtay** [webpack/webpack#12984]
## Feature request

Expose `ModuleFederationPluginOptions` in type definitions.

https://github.com/webpack/webpack/blob/master/types.d.ts#L5927

**What is the expected behavior?**

Be able to import the interface `ModuleFederationPluginOptions` in a typescript project.

**What is motivation or use case for adding/changing the behavior?**

`ModuleFederationPlugin` is already exposed on the webpack/container namespace. Wanting to import `ModuleFederationPluginOptions` for enforcing strict type safety for our module federation configurations.

**How should this be implemented in your opinion?**

Expose `ModuleFederationPluginOptions` on webpack/container namespace.

https://github.com/webpack/webpack/blob/master/types.d.ts#L11495

**Are you willing to work on this yourself?**
No

**Comment by adamtay** [comment]
Bumping this as it would still be highly desirable.

**Comment by alexander-akait** [comment]
You can do it without adding types...

**Comment by alexander-akait** [comment]
```ts
import type { container } from "webpack";

type ModuleFederationPluginOptions = ConstructorParameters<typeof container.ModuleFederationPlugin>[0];

const options: ModuleFederationPluginOptions = {
    filename: 'test',
    // Unknown option
    foo: 'bar'
};
```
