### ISSUE TITLE
Can't specify an object for library for differing names per targets

### ISSUE THREAD

**Issue by jqrun** [webpack/webpack#12992]
As per the documentation: 

https://webpack.js.org/configuration/output/#outputlibrary

```javascript
// Since webpack 3.1.0, you may specify an object for library for differing names per targets:
module.exports = {
  //...
  output: {
    library: {
      root: 'MyLibrary',
      amd: 'my-library',
      commonjs: 'my-common-library',
    },
    libraryTarget: 'umd',
  },
};
libraryTarget: 'system'
```

However, using 

```javascript
    library: {
      root: 'MyLibrary',
      amd: 'my-library',
      commonjs: 'my-common-library',
    },
```

Throws an error with AssignLibraryPlugin: https://github.com/webpack/webpack/blob/master/lib/library/AssignLibraryPlugin.js#L126

```Library name must be a string, string array or unset```

It looks like the normalized library options passed into parseOptions is merging everything under name:

```
{
   type: 'this',
   auxiliaryComment: undefined,
   export: undefined,
   name: {
     amd: 'my-library',
     commonjs: 'my-common-library',
     root: 'MyLibrary'
   },
   umdNamedDefine: undefined
 }

```

Note that it's a bit strange that the type is `this`, even though I pass `libraryTarget: 'umd'`

As a result it ends up going to AssignLibraryPlugin:

https://github.com/webpack/webpack/blob/547b4d8deb75355bf5695349fdcc3830ec22d68f/lib/library/EnableLibraryPlugin.js#L115

**Other relevant information:**
webpack version:  
Node.js version: v12.16.1
Operating System: Linux

**Comment by jqrun** [comment]
Okay it looks like it depends on the librarytarget:

https://github.com/webpack/webpack/blob/547b4d8deb75355bf5695349fdcc3830ec22d68f/lib/library/EnableLibraryPlugin.js#L115,

Where the EnableLibraryPlugin will either copy/assign/error for unnamed. How do we go about achieving the documentation example?

**Comment by jqrun** [comment]
Okay I think I found the issue, you can't use librarytarget anymore when you set library as the {amd, commonjs, root}, it seems to work if you instead fo library: {amd, commonjs, root, type}.

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by alexander-akait** [comment]
Please fill out all fields in the issue template, including how we can reproducible it and webpack version, I will reopen it after you fix it. Right now we can't help you, sorry

**Comment by chenxsan** [comment]
You might want to check https://webpack.js.org/configuration/output/#type-umd, and there's an example:

```js
module.exports = {
  //...
  output: {
    library: {
      name: {
        root: 'MyLibrary',
        amd: 'my-library',
        commonjs: 'my-common-library',
      },
      type: 'umd',
    },
  },
};
```

**Comment by jqrun** [comment]
Looks like I wasn't able to create a minimal reproducer, so there may be other configuration issues I have to figure out first, sorry about that! Will re-open if I'm able to distill the right context

**Comment by jqrun** [comment]
Just updating, it was 100% an issue in our repo, we had been mutating somewhere where we shouldn't have, and a stray config ended up with type: 'this' instead of type: 'umd', which branched to the wrong plugin (in this case, AssignLibraryPlugin). 

Will be better about following the template and reproducer guidelines next time!
