### ISSUE TITLE
Devtool breaks UMD exports with webpack-dev-server

### ISSUE THREAD

**Issue by redallen** [webpack/webpack#12991]
# Bug report

**What is the current behavior?**

After loading my bundle `window.quickstarts = {}`.

**If the current behavior is a bug, please provide the steps to reproduce.**

webpack.config.js:
```js
module.exports = {
  mode: 'development',
  devtool: 'inline-cheap-source-map',
  entry: {
    quickstarts: {
      import: __dirname + '/entry.js',
      filename: 'quickstarts.js',
      library: {
        name: 'quickstarts',
        type: 'umd'
      }
    }
  }
}
```

entry.js:
```js
export function myExport() { console.log('some data'); }
```

The output at http://localhost:8080/quickstarts.js erroneously contains:
```js
var __webpack_exports__ = {};
// This entry need to be wrapped in an IIFE because it need to be in strict mode.
(() => {
"use strict";
var __webpack_exports__ = {}; // THIS SHOULDN'T BE HERE?!
/*!******************!*\
  !*** ./entry.js ***!
  \******************/
__webpack_require__.r(__webpack_exports__);
/* harmony export */ __webpack_require__.d(__webpack_exports__, {
/* harmony export */   "myExport": () => (/* binding */ myExport)
/* harmony export */ });
function myExport() { console.log('some data'); }

})();
```

Minimal Github repo: https://github.com/redallen/webpack-umd-bug

**What is the expected behavior?**

I expect `__webpack_exports__` to not be defined in the IIFE scope so that it contains `myExport` and then `window.quickstarts` will contain it as well.

**Other relevant information:**
webpack version: 
```json
    "webpack": "^5.28.0",
    "webpack-cli": "^4.5.0",
    "webpack-dev-server": "^3.11.2"
```
Node.js version: v14.16.0
Operating System: linux

**Comment by redallen** [comment]
Upon further tinkering it seems that any `devtool` other than `false` causes this issue.

**Comment by alexander-akait** [comment]
You need `webpack-dev-server@beta-1`, webpack-dev-server v3 is not fully compatibility with webpack v5

**Comment by alexander-akait** [comment]
Stable release will in near future

**Comment by redallen** [comment]
The beta release fixes it.

The release cycle surrounding webpack@5 and webpack-cli/webpack-dev-server has been rather confusing -- I hope to see some version incompatibility notices in the future!

**Comment by ianks** [comment]
@alexander-akait this does not fix the issue for me

**Comment by alexander-akait** [comment]
@ianks sorry, this message is not helpful, provide example
