### ISSUE TITLE
webpackPrefetch: true breaks library output

### ISSUE THREAD

**Issue by Hypnosphi** [webpack/webpack#12993]
# Bug report

**What is the current behavior?**
If I use `/* webpackPrefetch: true */` for dynamic imports, it makes my library output `undefined`

**If the current behavior is a bug, please provide the steps to reproduce.**
https://github.com/Hypnosphi/webpack-5-library

**What is the expected behavior?**
![image](https://user-images.githubusercontent.com/6651625/112528783-d7d2c700-8da4-11eb-82a4-340f37ad4cb2.png)

**Other relevant information:**
webpack version:  5.28.0
Node.js version: 12.21.0
Operating System: macOS
Additional tools:

**Comment by brunolemos** [comment]
any workaround? facing the same thing.

I noticed this line gets added in the js output, causing the issue:

```diff
/******/ 	__webpack_require__("./prelude/index.js");
/******/ 	var __webpack_exports__ = __webpack_require__("./app/index.tsx");
+/******/ 	__webpack_exports__ = __webpack_require__.O(__webpack_exports__);
/******/ 	myglobalvariable = __webpack_exports__;
```

**Comment by brunolemos** [comment]
Ok I just looked at the implementation of `__webpack_require__.O` and found a workaround: 
setting `chunkIds` to `false` fixes the issue:

```diff
  optimization: {
+   chunkIds: false,
    splitChunks: {
      cacheGroups: {
        defaultVendors: false,
      },
    },
  },
```

<details>

<summary>See __webpack_require__.O implementation</summary>

```js
/************************************************************************/
/******/ 	/* webpack/runtime/chunk loaded */
/******/ 	(() => {
/******/ 		var deferred = [];
/******/ 		__webpack_require__.O = (result, chunkIds, fn, priority) => {
/******/ 			if(chunkIds) {
/******/ 				priority = priority || 0;
/******/ 				for(var i = deferred.length; i > 0 && deferred[i - 1][2] > priority; i--) deferred[i] = deferred[i - 1];
/******/ 				deferred[i] = [chunkIds, fn, priority];
/******/ 				return;
/******/ 			}
/******/ 			var notFulfilled = Infinity;
/******/ 			for (var i = 0; i < deferred.length; i++) {
/******/ 				var [chunkIds, fn, priority] = deferred[i];
/******/ 				var fulfilled = true;
/******/ 				for (var j = 0; j < chunkIds.length; j++) {
/******/ 					if ((priority & 1 === 0 || notFulfilled >= priority) && Object.keys(__webpack_require__.O).every((key) => (__webpack_require__.O[key](chunkIds[j])))) {
/******/ 						chunkIds.splice(j--, 1);
/******/ 					} else {
/******/ 						fulfilled = false;
/******/ 						if(priority < notFulfilled) notFulfilled = priority;
/******/ 					}
/******/ 				}
/******/ 				if(fulfilled) {
/******/ 					deferred.splice(i--, 1)
/******/ 					result = fn();
/******/ 				}
/******/ 			}
/******/ 			return result;
/******/ 		};
/******/ 	})();
```

</details>

**Comment by brunolemos** [comment]
I'm not very experienced in webpack but it seems like it's treating the main output file (`output.filename`) as a chunk

**Comment by brunolemos** [comment]
Downgrading webpack to `5.24.4` seems to be the best workaround for now.

**Comment by Shinyaigeek** [comment]
I investigated this issue and webpack code, and I found anothor workaround, which is to configure `devtool` as false (in development mode, `devtool` is configured as eval as a default behavior).

I may ask webpack developers some questions about codebase, but if you do not mind, I would like to pick this issue.

**Comment by agawley** [comment]
Hi webpack folks. Any guidance on when this fix might make it into a release? Or if there is anything I can do to help it along. Thanks!
