### ISSUE TITLE
[experimental] output.library.type: module generates commonjs syntax for externals and node.js builtins

### ISSUE THREAD

**Issue by dnalborczyk** [webpack/webpack#12994]
not sure if it's too early to file bugs regarding experimental features?

# Bug report

**What is the current behavior?**
webpack library.type "module" generates commonjs syntax (module.exports/require) for node.js builtins (when target is node) and for any module specified as external(s).

**If the current behavior is a bug, please provide the steps to reproduce.**

```index.js
export { version } from "process";
```

```webpack.config.js
export default {
  entry: {
    index: "./index.js",
  },
  experiments: {
    outputModule: true,
  },
  // externals: ...
  output: {
    filename: "[name].js",
    library: {
      type: "module",
    },
  },
  target: "node",
};
```

```js
/***/ "process":
/*!**************************!*\
  !*** external "process" ***!
  \**************************/
/***/ ((module) => {

module.exports = require("process");;

/***/ })
```

**What is the expected behavior?**
I'd imagine that node builtins have to be either required on top of the file (outer module scope) or possibly dynamically **import()** ed.

**Other relevant information:**
webpack version:  v5.22.0
Node.js version: v15.12.0
Operating System: macOS Big Sur
Additional tools: n/a

**Comment by alexander-akait** [comment]
Yep, in roadmap, duplicate https://github.com/webpack/webpack/issues/2933
