### ISSUE TITLE
Common modules in main entry

### ISSUE THREAD

**Issue by NekR** [webpack/webpack#1300]
I have following structure, components mostly are pages and they use "shared" modules, e.g. those which ``main.js`` module uses already. Is there a way to not include those module in chunks, but just keep them in ``main.js`` module?

```
        main.js     150 kB       0  [emitted]  main
components/1.js  315 bytes       1  [emitted]
components/2.js    8.06 kB       2  [emitted]
components/3.js    17.3 kB       3  [emitted]
components/4.js    6.32 kB       4  [emitted]
components/5.js  337 bytes       5  [emitted]
components/6.js    9.26 kB       6  [emitted]
components/7.js  462 bytes       7  [emitted]
components/8.js    8.67 kB       8  [emitted]
```

P.S. I know there is ``CommonsChunkPlugin`` but as I understand, it puts common module in separate file, but I need them in main module.

**Comment by NekR** [comment]
Okay, I see this now:
> ``require.include`` can be useful if a module is in multiple child chunks. A require.include in the parent would include the module and the instances of the modules in the chunk chunks would disappear.

Seems like this won't work with ``bundle-loader``, will need to handle loading myself.

**Comment by sokra** [comment]
You can do this with the CommonChunkPlugin.

``` js
new CommonsChunkPlugin({
  name: "main",
  minChunks: 4,
  children: true
})
```

Also try `async: true` this creates an async extra chunk which is loaded in parallel with the on-demand loaded chunks.

**Comment by NekR** [comment]
@sokra I understand how to load files :-) Let me explain in more details what I am trying to achieve, sorry if this is exactly that you are proposing here and I do not understand.

Let's say I have one main module ``main``, two pages ``page1`` and ``page2`` and a utils module ``utils``.
* ``main`` is the only entry of the app and is loaded always and first.
* ``page1`` and ``page2`` are chunks generated by the ``bundle-loader``. They are loaded when specific page is navigated.
* ``utils`` is the shared module which is referenced by all the other modules (``main``, ``page1``, ``page2``).

The goal is to include ``utils`` module it to the main entry alongside with ``main`` module and do not include it in ``page1`` and ``page2``. And not having an separate file for common modules like ``CommonsChunkPlugin`` does (if I correctly understand it).

**Comment by NekR** [comment]
Hmmm.. it seems that this line ``new webpack.optimize.CommonsChunkPlugin('main', null, false)`` does exactly what I wanted. Sorry for misunderstanding..

**Comment by NekR** [comment]
Forget to close. Thanks for answers here, I did not get that your initial response here worked as I wanted until I found some articles about ``CommonsChunkPlugin`` over internet.

**Comment by NekR** [comment]
@sokra now no one solution works, only adding `require.include('module')` in the main entry does the trick. Any ideas why?
