### ISSUE TITLE
ESM re-exports to umd

### ISSUE THREAD

**Issue by fireridlle** [webpack/webpack#13007]
**What is the current behavior?**
ESM re-exports to umd transpiler produce big bundle size.
When i used to have the same functions in 1 single file, a bundle was significantly less. however, when i migrate to esm and put each function into a separate file and create index.js with re-export, bundle size has been blown. per my bundle analuze i realize that the biggest file is index.js.

**If the current behavior is a bug, please provide the steps to reproduce.**
create a few files per with single function (in my case 207).
crearte index.js with re-exports like
```
export { default as a1 } from './a1'
export { default as a2 } from './a2'
export { default as a3 } from './a3'
.....
export { default as aN } from './aN'
```

**What is the expected behavior?**
I would expect that bundle size with re-exports would be the same as having all functions in one file. or at least some steps for pre-build to concatenate all files into one before transpile to umd.

webpack version:  5.23.0
Node.js version: 12.18.0
Operating System: mac os

**Comment by alexander-akait** [comment]
Now you have more modules, so size is more

**Comment by sokra** [comment]
In production mode webpack concatenates modules when they use ESM exports and imports.

It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.
