### ISSUE TITLE
Strange build behaviour - webpack generate incorrect id for module

### ISSUE THREAD

**Issue by khmilevoi** [webpack/webpack#13010]
# Bug report

**What is the current behavior?**

After building webpack generates this code.

```js
        }, 2
    c88e: (t, r, a) => {
        "use strict";
        var o, i = a(82109), u = a(31236).f, s = a(17466), v = a(3929), m = a(84488), _ = a(84964), R = a(31913),
            j = "".startsWith, M = Math.min, W = _("startsWith");
        i({

```

Webpack generate id as `2c88e` but in other places of code it is number.
And after launching browser throw syntax error.

**If the current behavior is a bug, please provide the steps to reproduce.**

[webpack.config.js](https://codesandbox.io/s/weathered-pond-heurp?file=/src/index.js)

**What is the expected behavior?**

**Other relevant information:**
webpack version:  
v5.28.0 
Node.js version: 
v14.16.0
Operating System: 
```
      Operating System: Ubuntu 20.04.2 LTS
      Kernel: Linux 5.4.0-66-generic
      Architecture: x86-64

```
Additional tools:

**Comment by alexander-akait** [comment]
Can't reproducible, please provide minimum reproducible test repo, also link above uses parcel

**Comment by khmilevoi** [comment]
https://webpack.js.org/plugins/terser-webpack-plugin/

It's fix my problem.)

**Comment by goblin-pitcher** [comment]
> https://webpack.js.org/plugins/terser-webpack-plugin/
> 
> It's fix my problem.)

Hi, dude, I have met the same problem, could you tell me how you solved it? 
I even tried to turn off the `optimization.minimize`, but the problem still exists 😢
