### ISSUE TITLE
Production mode in Angular

### ISSUE THREAD

**Issue by floflojaja** [webpack/webpack#13011]
Hi,

I am currently setting up webpack 5 Federation Module under Angular 11.

Everything is ok in development mode but at the time of producing my project. I have an error : Error loading ScriptExternalLoadError: Loading script failed.

Indeed, the build in development and production mode does not produce the same "entryPoint":
Production Mode : 
`var library;(self.webpackChunklibrary=self.webpackChunklibrary||[]).push([[297],{795:function(e,n,r){"use strict";var i={"./web-components":function(){return Promise.all([r.e(547),r.e(382),r.e(155),r.e(807),r.e(676),r.e(110),r.e(821),r.e(533),r.e(215),r.e(592),r.e(144)]).then(function(){return function(){return r(9144)}})}},t=function(e,n){return r.R=n,n=r.o(i,e)?i[e]():Promise.resolve().then(function(){throw new Error('Module "'+e+'" does not exist in container.')}),r.R=void 0,n},o=function(e,n){if(r.S){var i=r.S.default,t="default";if(i&&i!==e)throw new Error("Container initialization failed as it has already been initialized with a different share scope");return r.S[t]=e,r.I(t,n)}};r.d(n,{get:function(){return t},init:function(){return o}})}},function(e){"use strict";var n=e(e.s=795);library=n}]);`

We can see that there are several js files that have been minified and anonymized and this produces an error.

Have you already started producing Angular projects under Webpack 5 Module Federation?

Thanks !!

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Please ask it in angular repo
