### ISSUE TITLE
webpack-dev-server/clicnt/index.js 

### ISSUE THREAD

**Issue by ws18250840411** [webpack/webpack#13013]
# Bug report
On line 135 the strippedWarnings[i] is object, In webpack4 the value is string. There is a problem with the console output

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

**Comment by alexander-akait** [comment]
Fixed in `beta-1`

**Comment by alexander-akait** [comment]
Never ignore the issue template, respect time of other developers
