### ISSUE TITLE
Export StatsAsset in the types

### ISSUE THREAD

**Issue by 43081j** [webpack/webpack#13014]
The `StatsAsset` type is currently not exported, so we have to get it via something like this:

```ts
type StatsAsset = NonNullable<StatsCompilation['assets']>[0];
```

It would be good if it was instead exported and we could simply import `{StatsAsset}`.

**Comment by alexander-akait** [comment]
Please use `StatsCompilation['assets']`, it is right usage

**Comment by alexander-akait** [comment]
It is internal object and can be changed

**Comment by 43081j** [comment]
That makes sense, it leaves us in an awkward situation though.

Bundlephobia currently does something along the lines of:

```ts
function mapper(asset: StatsAsset): foo {
  // ...
}

stats.assets.map(mapper);
```

Which means we're reliant on that model to interact with the assets anyway. Seeing as you expose it indirectly, it isn't really internal anymore I would say.

Maybe webpack could expose a subset of the interface? For example, we only need the `name`, `size` and `chunkNames`. These 3 sound like fairly common properties you're unlikely to remove in a non-breaking change anyway.

**Comment by alexander-akait** [comment]
Low priority, PR welcome
