### ISSUE TITLE
Webpack fails to bundle node_redis

### ISSUE THREAD

**Issue by Dindaleon** [webpack/webpack#1302]
Whenever I require redis inside a file other than the one where I start the server, I get the following error while webpack is bundling:

    ERROR in ./~/redis/index.js
    Module not found: Error: Cannot resolve module 'net' in     C:\NodeServer\AppInTheWild\node_modules\redis
     @ ./~/redis/index.js 3:10-24

    ERROR in ./~/redis/lib/parser/hiredis.js
    Module not found: Error: Cannot resolve module 'hiredis' in C:\NodeServer\AppInTheWild\node_modules\redis\lib\parser
     @ ./~/redis/lib/parser/hiredis.js 3:14-32

**EDIT:** being solved at: https://github.com/webpack/webpack-dev-server/issues/227

**Comment by shama** [comment]
https://github.com/webpack/webpack-dev-server/issues/227#issuecomment-125803858
