### ISSUE TITLE
CSS files being treeshaken even when sideEffects=true

### ISSUE THREAD

**Issue by k2snowman69** [webpack/webpack#13027]
# Bug report

**What is the current behavior?**
Css files that are imported without named imports is currently removed even though css files have sideEffects=true defined in the webpack config.

**If the current behavior is a bug, please provide the steps to reproduce.**
I've created a repo to help reproduce it:
https://github.com/k2snowman69/bug-css-tree-shaking

Basic textual intepretation:
1. In a js file, add `import "somecss.css"` so that javascript file is importing the css file without named modules
2. Make sure your webpack config specifies that css files have sideEffects
```
{
  sideEffects: true,
  test: /\.css$/,
  use: [
    // MiniCssExtractPlugin is not necessary to replicate this issue.
    // I added it as it is easier to view the order of the generated CSS.
    // However, you can still see the issue by searching for the generated
    // class names in the .js bundle. They're still out of order.
    MiniCssExtractPlugin.loader,
    "css-loader",
  ],
},
```

**What is the expected behavior?**
That the css file is included in the final build output. In my sample repository there should be two classes available:
```
.component--import-modules {
  color: black;
}

.component--import-no-modules {
  color: lightblue;
}
```
However currently only one is compiled:
```
.component--import-modules {
  color: black;
}
```

**Other relevant information:**
webpack version:  5.28.0
Node.js version: 14.15.4
Operating System: OSX
Additional tools: babel@7.x.x

**Comment by sokra** [comment]
This is working as expected: 

`src/ui/component--import-no-modules/index.js` has no side effects so it's not included (since no direct export is used). The import to the CSS in that file is not considered, neither are the side effects of the CSS file.

**Comment by alexander-akait** [comment]
Answered, feel free to feedback

**Comment by k2snowman69** [comment]
`src/ui/component--import-no-modules/index.js` imports a file that has side-effects (./ComponentB.css) so why is the import of the index.js skipping the css file.

Am I thinking of this backwards maybe? My thinking is that I say "css files have sideEffects, therefore always include them". In this situation, any time along an import chain a css file is imported, it should always be included. Is the reality that "these particular files have sideEffects, always include all their imports? More of a top down vs bottom up approach?

If that's the case, when calculating if sideEffects should be true or not for a single file, I'd need to know the imports and to know if it's importing a css file correct? Is that possible?

**Comment by k2snowman69** [comment]
Okay so to express my frustration further I've updated my repository to contain

 - component--import-no-modules--index - has `import "./Component.css";` from the index.js
 - component--import-no-modules--component - has `import "./Component.css";` from the component.js

However only `component--import-no-modules--component` shows up in my build.

In my webpack config all css files are listed as having side effects.

IMO if file A imports B where B has sideEffects, then A should be calculated to have sideEffects as well to be on the safer side.

**Comment by alexander-akait** [comment]
> IMO if file A imports B where B has sideEffects, then A should be calculated to have sideEffects as well to be on the safer side.

No

**Comment by k2snowman69** [comment]
I understand you get a lot of questions regarding this, I'm sorry if this is frustrating however I'm also trying to understand this system in either hopes of improving documentation or determining if this is a bug or not.

I think by your "No", it implies that even though in a webpack config you define a file as "sideEffects: true" that's affecting the imports within that file, not the files that import that file. So more a parent to child relationship instead of a child to parent relationship.

So declaring css files as having side effects means nothing. What's really needed is any files that include css files should be declared as having side effects?

**Comment by NullPainter2** [comment]
@alexander-akait Why not?

**Comment by paztis** [comment]
facing the same issue: all the css imported in the index.js files are removed, while not the others.
I've found a workaround by adding this in my package.json


    "sideEffects": [
        "index.js",
        "*.css",
        "*.scss"
    ],

I hope index.js in the sideEffects will not keep too much code...
