### ISSUE TITLE
Module Federation deps strictVersion mismatch source in error message

### ISSUE THREAD

**Issue by glebmachine** [webpack/webpack#13020]
## Feature request

**What is the expected behavior?**
`getStrictSingletonVersion` throws more detailed error.
Also will be great get all errors at once (not one per step)

This dramatically decrease spent time on module federation integration process.

**What is motivation or use case for adding/changing the behavior?**
Adding module federation to huge porject i'm facing following problem:
I'm unable do determine package, which declare mismatched strict version dependency, because only clue i've get is 
```
Unsatisfied version 11.0.3 of shared singleton module @angular/core (required ^10.0.0)
```

Digging deeper i've found this (but it still don't help me):
![image](https://user-images.githubusercontent.com/1610882/112955615-4a96c600-9148-11eb-8d8d-7aa08ed995ac.png)
There are is a lot of older angular dependencies version, but - i can't determine which package bring them there.

**How should this be implemented in your opinion?**

This:
```
Unsatisfied version 11.0.3 of shared singleton module @angular/core (required ^10.0.0)
```

Will be good to expanded to this:
```
Unsatisfied versions detected:
@angular/core (current 11.0.3)
   10.0.0 (by @ngrx/core)
   6.0.3 (by ngx-quicklinks)
```
**Are you willing to work on this yourself?**
I'm not sure i can handle it, but i can try, if you give me few design clues.

**Comment by glebmachine** [comment]
That too baaaaad(
Digging into all packages to find exact package which add own peerDependencies and mess the bundle

**Comment by sokra** [comment]
Try `yarn why @angular/core`. I guess that will print the information you are looking for. Otherwise you can use the stack trace of the error.

**Comment by glebmachine** [comment]
Ofcourse i tried, it was in peerDependency of installed packages and not displayed by `yarn why` (because of peerDependencies).

Stack trace also doesn't work, because it is `eager` module, and eager dependency list defined right in previous line of code (it don't traced up to parent call)

I found all mismatched peerDependencies by:
```bash
grep -nri '@angular' --include="package.json" node_modules > deps
```

But it looks not about good DX. So that's why i file that issue

**Comment by alexander-akait** [comment]
@glebmachine Maybe you can provide example?

**Comment by glebmachine** [comment]
@alexander-akait Sure!
https://github.com/glebmachine/module-federation-version-mismatch-repro

Steps to reproduce:
1. `git clone git@github.com:glebmachine/module-federation-version-mismatch-repro.git` 
2. `cd module-federation-version-mismatch-repro`
3. `yarn`
4. `./node_modules/.bin/ng run shell:serve`

Also, you can find broken stats output:
![image](https://user-images.githubusercontent.com/1610882/113194513-e5d38c80-9269-11eb-83e2-d8e36abf3c71.png)

**Comment by glebmachine** [comment]
Kindly reminder

**Comment by alexander-akait** [comment]
```
warning " > ngx-sub-form@5.1.2" has incorrect peer dependency "@angular/common@^9.0.0".
warning " > ngx-sub-form@5.1.2" has incorrect peer dependency "@angular/core@^9.0.0".
warning " > ngx-sub-form@5.1.2" has incorrect peer dependency "tslib@^1.10.0".
```

You have mixed version of `@angular/core`, only one `@angular/core` package allowed to use. It is configured by `@angular/cli`

Nothing to fix here, sorry

**Comment by alexander-akait** [comment]
You can comment and change code:
```
// import { Controls, NgxAutomaticRootFormComponent } from 'ngx-sub-form';
```

and all works fine

**Comment by glebmachine** [comment]
@alexander-akait Ваш комментарий выглядит как издевательство, честно

Это репро, я наглядно здесь иллюстрирую скупые сообщения об ошибках
Вот скриншот ошибки:
![image](https://user-images.githubusercontent.com/1610882/114544836-d9850180-9c63-11eb-8eae-65b93c33a0c3.png)

В сообщении не сказано, какой модуль принес зависимость с несовместимой версией
И `ngx-sub-form` это как раз та самая зависимость, не надо ее комментировать. Это вопроc DX, который дает webpack.

Единственный способ ее найти, это грепать по зависимостям
Если нужны комментарии, мы можем вживую с вами пообщаться: t.me/glebmikheev

**Comment by alexander-akait** [comment]
@glebmachine

> Ваш комментарий выглядит как издевательство, честно
> Это вопроc DX, который дает webpack.

Пожалуйста не будьте токсичны, это настройка лежит внутри `@angular/cli` и именно там `angular-cli` должен вам сообщить о не совместимости, мы это описываем достаточно хорошо в документации. Что вы здесь ожидаете? Мы сообщили о несовместимой версии и в какой модуле проблема. Некоторые пакеты можно использовать много раз, некоторые нет, мы не можем проанализировать код каждого пакеты на совместимость, все что мы можем вывести ошибку на основании используемых модулей и их настроект при фенедарции модулей.

К слову говоря даже пакетный менедреж вам об этом сообщает. Даже более при использовании yarn PnP или pnpm вы не сможете установить ваши завимисоисти из-за этой проблемы без хаков. И даже более использовать разных версий angular скорее всего сломает ваш проект.

**Comment by glebmachine** [comment]
@alexander-akait сейчас принесу чистое репро, где только js

**Comment by alexander-akait** [comment]
Я понимаю ваш вопрос и желание, я помечу это как улучшение, но это может быт не так легко решить как кажется, так как сборка может происходить независимо и имена могут в production может быть сжаты, хотя это имеет смысл для development режима

**Comment by glebmachine** [comment]
Вот, пожалуйста, репро:

https://github.com/glebmachine/module-federation-pure-demo/tree/error-message

Тут чистый пример, где нет angular-специфики
Как запустить репро:

1. `git clone git@github.com:glebmachine/module-federation-pure-demo.git`
2. `git checkout error-message`
3. `npm i`
4. `npm run serve:shell`

И при запуске приложения мы получаем вот такую ошибку:
![image](https://user-images.githubusercontent.com/1610882/114548541-95483000-9c68-11eb-9309-516ce67da9bb.png)

### Подробности:
В общих зависимостях стоит `has-value: 2.0.2` (`package.json`)
В шереном модуле стоит зависимость `has-value: 0.0.1` (`app\package.json`)

В итоге генерится вот такой код:
![image](https://user-images.githubusercontent.com/1610882/114548858-ff60d500-9c68-11eb-9980-732ddeb8ff17.png)
Тут регистрируются фабрики для зависимостей, где указаны версии.

В случае если strictVersion зависимость, то генериться ошибка:
![image](https://user-images.githubusercontent.com/1610882/114549078-3fc05300-9c69-11eb-80be-15f9d92610a6.png)

И вот в этом контексте не хватает информации в _каком_ модуле, была определена версия зависимости.
Что в свою очередь не позволяет разработчику проанализировать проблему. Только понять и признать сам факт.

Мы можем дать более качественный DX, если подскажем _какой_ файл ему принес эту зависимость.
Может хотя-бы alias отсюда протащить до этого исключения, взяв название из этого конфига:
![image](https://user-images.githubusercontent.com/1610882/114549383-9c237280-9c69-11eb-8aed-1609d3fd9253.png)

**Comment by alexander-akait** [comment]
Можешь послать PR если у тебя есть желание быстрее это улучшить :+1:

**Comment by glebmachine** [comment]
> Можешь послать PR если у тебя есть желание быстрее это улучшить 👍
Я за, я готов

Но мне нужно помочь с дизайном, от того, кто шарит за архитектуру.
Пару подсказок, типа "посмотри сюда" "видишь вот тут"

Это и сократит вход в кодовую базу, и даст мне правильный дизайн, что уменьшит суету на ревью =)

Можешь дать подобные подсказочки, пожалуйста ?)

**Comment by snitin315** [comment]
Пожалуйста, используйте английский в будущем

**Comment by alexander-akait** [comment]
You can improve it here https://github.com/webpack/webpack/blob/master/lib/sharing/ConsumeSharedRuntimeModule.js, we have helpers like `findVersion`/`findSingletonVersionKey` https://github.com/webpack/webpack/blob/master/lib/sharing/ConsumeSharedRuntimeModule.js#L98, I think we need return not only versions, but also packages where this versions were used so it allows to improve error message

**Comment by glebmachine** [comment]
@snitin315 sure, thank you!
@alexander-akait thanks for some clues, will back soon)
