### ISSUE TITLE
Unused code is not removed from dynamic imports

### ISSUE THREAD

**Issue by gkjohnson** [webpack/webpack#13028]
## Feature request

**What is the expected behavior?**

Dynamic imports should have unused code removed the way regular imports do. Currently if you export two functions from a dynamically imported file and only ever use 1 of them the unused function will not be removed. Consider the following example:

```js
// dynamic.js
export function usedFunction() { console.log( 'USED' ); };

export function unusedFunction() { console.log( 'UNUSED' ); };
```

```js
// index.js
import( './dynamic.js' ).then( ( { usedFunction } ) => {

    usedFunction();

} );
```

After bundling the above files "unusedFunction" will still be included in the built `dynamic.js` chunk. However "unusedFunction" is removed when using `import { usedFunction } from './dynamic.js';`.

_(tested with the latest webpack, webpack-cli)_

**What is motivation or use case for adding/changing the behavior?**

I would like to remove as much code as possible even from the dynamically imported files to reduce the download and parse time overhead.

**How should this be implemented in your opinion?**

Dynamic imports should have unused code removed the way regular imports do by inspecting the fields used after running the import.

**Are you willing to work on this yourself?**

Unfortunately I don't think I'll be able to.

**Comment by sokra** [comment]
This is too complex to statically analyse, so webpack doesn't know which exports are used.

You can tell it manually like that:

``` js
// index.js
import(/* webpackExports: "usedFunction" */ './dynamic.js' ).then( ( { usedFunction } ) => {

    usedFunction();

} );
```

**Comment by gkjohnson** [comment]
I did expect that handling every scenario would be too complicated but what about supporting a limited syntax for this? Limited syntax support works pretty well for WebWorkers. The magic comments you suggest are nearly like the immediate destructuring case:

```js
const { usedFunction } = await import( './dynamic.js' );

// or

import( './dynamic.js' ).then( ( { usedFunction } ) => { /* ... */ } );
```

Either way I appreciate your response!

**Comment by sokra** [comment]
Yes we probably want to implement the await syntax eventually

**Comment by alexander-akait** [comment]
bump

**Comment by vankop** [comment]
bump

**Comment by vankop** [comment]
closing in favor of https://github.com/webpack/webpack/issues/14800
