### ISSUE TITLE
[PackFileCacheStrategy error because of 'fsevents' on windows

### ISSUE THREAD

**Issue by vincaslt** [webpack/webpack#13026]
# Bug report

**What is the current behavior?**

```
[webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Can't resolve 'fsevents' in '<path>\node_modules\chokidar'
 while resolving 'fsevents' in <path>\node_modules\chokidar to a directory
```

I tried installing fsevents as a dev dependency, but it says: 

```
Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
```

It's also skipped when chokidar is installed, I assume that fsevents is not available on windows.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

caching works and no error

**Other relevant information:**
webpack version:  5
Node.js version: v14.15.1
Operating System: Windows 7
Additional tools: Webpack is used in NextJS

**Comment by alexander-akait** [comment]
hm, we don't use `chokidar` directly (https://github.com/webpack/webpack/blob/master/yarn.lock), can you share how we can reproduce it? Do you use `fork-ts-checker-webpack-plugin`?

**Comment by vincaslt** [comment]
Ah indeed, webpack doesn't use it directly. It's a required dependency of nextjs:

```
"next": {
      "version": "10.1.2",
      "resolved": "https://registry.npmjs.org/next/-/next-10.1.2.tgz",
      "integrity": "sha512-S2KYS8NXeFmaJd8EyoC/kWi3uIlNz3PghnpDWYwy5dxhbtyaozK7fVpXmDcOTQEyYq3BZG5ph0B+hOsAwMdYfQ==",
      "requires": {
        ...
        "chokidar": "3.5.1",
```

**Comment by alexander-akait** [comment]
I think you need to open an issue in nextjs repo

**Comment by sokra** [comment]
This is a webpack bug. We need to make optional dependencies optional

**Comment by alexander-akait** [comment]
Fixed https://github.com/webpack/webpack/pull/13062

**Comment by vincaslt** [comment]
Wow, nice job, thank you!
