### ISSUE TITLE
Module Federation emits zero-sized files

### ISSUE THREAD

**Issue by glebmachine** [webpack/webpack#13035]
# Bug report

When internal library added as `shared` dependency, webpack emits zero-sized files
![image](https://user-images.githubusercontent.com/1610882/113196020-a86ffe80-926b-11eb-9f9e-05c51aae3808.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

Repro:
1. `git clone git@github.com:glebmachine/module-federation-zero-sized-bundle.git `
2. `yarn`
2. `./node_modules/.bin/ng run shell:serve`

Step to `repair build`:
1. Open `projects\shell\webpack.config.js`
2. Comment 8 line:
![image](https://user-images.githubusercontent.com/1610882/113196190-e0774180-926b-11eb-830b-9bce17ec0bfc.png)

Expect that everything goes normal (emit normal project, with separated chunk for my auth library)

**Other relevant information:**
webpack version:  5.28.0
Node.js version: 12.14.1
Operating System: win10
Additional tools:

**Comment by alexander-akait** [comment]
It is custom output, so you need open an issue in angular repo, we can't fix it on our side

**Comment by glebmachine** [comment]
Ok i will, thank you!

But, it also doesn't server anything, looks like empty files - reponsibility of webpack, not output itself

**Comment by alexander-akait** [comment]
webpack doesn't generate empty files

**Comment by glebmachine** [comment]
webpack doesn't serve anything as well

**Comment by alexander-akait** [comment]
Please ask this in `angular` repo

**Comment by glebmachine** [comment]
@alexander-akait done
https://github.com/angular/angular-cli/issues/20428
