### ISSUE TITLE
How to compile vue2 file and vue3 file

### ISSUE THREAD

**Issue by BlackCubeNo99** [webpack/webpack#13032]
**What is the current behavior?**
Cannot compile Vue2 and Vue3 at the same time

**If the current behavior is a bug, please provide the steps to reproduce.**
I installed `vue-loader`、`vue-template-compiler`、`@vue/compiler-sfc`、`vue2`、`vue3`

```json
// package.json
"devDependencies": {
  "vue-loader": "16.1.2",
  "vue-template-compiler": "2.6.12",
  "@vue/compiler-sfc": "3.0.7"
},
"dependencies": {
  "vue": "2.6.12",
  "vue3": "npm:vue@3.0.7"
}
```

How to set vue2 and vue3 config ?

```javascript
// webpack.config.js
module.exports = {
  entry: ['a.js', 'b.ts'],
  resolve: {
    alias: {}
  }
}
```

a.js use vue2
```javascript
// a.js
import Vue from 'vue'
import App from './App.vue'

new Vue({
  el: '#app',
  render: h => h(App)
})
```

b.ts use vue3
```typescript
// b.ts
import { createApp } from 'vue3'
import App from './App.vue'

createApp(App).mount('#app')
```

**What is the expected behavior?**
compile Vue2 and Vue3 at the same time

**Other relevant information:**
webpack version:  5.24.4
Node.js version: 12.16.2
Operating System: macOS Catalina 10.15.7
Additional tools:

**Comment by alexander-akait** [comment]
Please ask this questions in `vue`/`vue-loader` repo, in theory you can use multi compiler mode and compiler vue2 code to js when include compiled code in app where you use vue3, but I am not sure, here answer https://stackoverflow.com/questions/64122089/how-can-i-use-vue2-old-component-vue-file-with-a-new-vue3-project
