### ISSUE TITLE
WorkerPlugin doesn't correctly handle `new URL().toString()`

### ISSUE THREAD

**Issue by jtbandes** [webpack/webpack#13043]
# Bug report

The [documentation for `Worker`](https://developer.mozilla.org/en-US/docs/Web/API/Worker/Worker) and `SharedWorker` say that their constructors accept **strings**, not `URL`s (and the TypeScript standard library types enforce this for SharedWorker, although not for Worker).

In practice, it seems like passing a URL is fine (at least in Chrome), but for projects using TypeScript, it will be most natural to pass a string, which means that `String()`, `.toString()`, `.href`, or similar must be used. However the new WorkerPlugin (#11439) assumes that the import must look like `new Worker(new URL(..., import.meta.url))`: https://github.com/webpack/webpack/blob/f3dce69e9df5f778fb4850662b0f16f9fd9951d2/lib/dependencies/WorkerPlugin.js#L84-L85

**What is the current behavior?**
`new Worker(new URL(...).toString())` does not properly bundle the worker code in the same way as `new Worker(new URL(...))`.

**What is the expected behavior?**

`.toString()` or other similar constructs should be allowed since they are technically more correct according to the documentation.

**Other relevant information:**
webpack version:  5.26.3
Node.js version: v15.9.0
Operating System: macOS 11.2.3

**Comment by alexander-akait** [comment]
> .toString() or other similar constructs should be allowed since they are technically more correct according to the documentation.

Where?

> The documentation for Worker and SharedWorker say that their constructors accept strings, not URLs (and the TypeScript standard library types enforce this for SharedWorker, although not for Worker).

```js
declare var Worker: {
    prototype: Worker;
    new(stringUrl: string | URL, options?: WorkerOptions): Worker;
};
```

But yes, we can improve this

**Comment by alexander-akait** [comment]
Feel free to send PR, should be not hard

**Comment by jtbandes** [comment]
https://github.com/microsoft/TypeScript/blob/f9b35cd302a6746fd281de1d39cdf7f8c8860cee/lib/lib.dom.d.ts#L15089

**Comment by alexander-akait** [comment]
It is old, please look at master https://github.com/microsoft/TypeScript/blob/master/lib/lib.dom.d.ts

**Comment by jtbandes** [comment]
It's not old– this file has not been updated since Jan 10 :) https://github.com/microsoft/TypeScript/blob/master/lib/lib.dom.d.ts#L15089-L15092

**Comment by vankop** [comment]
@alexander-akait what we should do on our side? from ts lib.dom 
```ts
declare var Worker: {
    prototype: Worker;
    new(stringUrl: string | URL, options?: WorkerOptions): Worker;
};
```
url is ok

**Comment by alexander-akait** [comment]
@vankop I think we should improve this, why not?

**Comment by vankop** [comment]
this will require additional static analyze, `.toString()` is not enough.. if we will support string we need support all "stringify" methods

**Comment by alexander-akait** [comment]
hm, you are right, handling all `stringify` methods maybe be difficult, and even unsafe in edge cases, maybe we can docs it as limitation, I don't see any big reasons to use `toString()`, also ts update their types and now it works fine with `new URL()`

**Comment by vankop** [comment]
created an issue ☝️
