### ISSUE TITLE
HotModuleReplacement suddenly requiring `sudo` to work properly

### ISSUE THREAD

**Issue by timbur** [webpack/webpack#1304]
I think I began having this problem last week when I had to run `npm cache clean` for some other `webpack` related issue (don't remember what exactly).

I went on a short vacation and didn't realize until today during some testing that HMR wasn't detecting changes made to files.  After a bit of confusion and profanity, I finally figured out that running `npm start` as `sudo` allows everything to function as it did before.  I've tried `chown`ing a few directories (`~/.npm`, `/usr/local`, my projects that use webpack, etc.) but to no avail.

Any idea what to do to make HMR work again without `sudo`?

**Comment by sokra** [comment]
@es128 any idea?

**Comment by es128** [comment]
Not really. You could try switching the watch mode to see if it makes a difference (toggle chokidar's `usePolling` setting)
