### ISSUE TITLE
`webpack serve --profile` does not respect `logging: "verbose"`, causing profile results to be hidden

### ISSUE THREAD

**Issue by Ruin0x11** [webpack/webpack#13055]
# Bug report

**What is the current behavior?**

When running `webpack serve --profile`, the profiler results will always be hidden even if `logging: "verbose"` is specified. I was trying to use `--profile` to understand why adding a binary asset to the public folder caused the build/rebuild times to balloon from 3 seconds to 40 seconds, but I can't understand what part of the build is the slowest because of this.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Create the webpack demo as described at https://webpack.js.org/guides/getting-started/. The webpack config is:
```js
module.exports = {
  entry: [
    './src/index.js'
  ],
  output: {
    path: __dirname + '/dist',
    filename: "index.bundle.js"
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/
      }
    ]
  },
  stats: {
    logging: 'verbose',
  },
  // plugins: []
};
```

And `package.json`:

```json
{
  "name": "webpack-demo",
  "version": "1.0.0",
  "description": "",
  "main": "src/index.js",
  "private": true,
  "scripts": {
    "start": "webpack serve --config webpack.config.js --profile"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "webpack": "^5.30.0",
    "webpack-cli": "^4.6.0",
    "webpack-dev-server": "^3.11.2"
  }
}
```

2. Run `webpack serve --config webpack.config.js --profile`. This is the output:

<details><summary>Output</summary>

> webpack-demo@1.0.0 start
> webpack serve --config webpack.config.js --profile

[34mℹ[39m [90m｢wds｣[39m: Project is running at http://localhost:8080/
[34mℹ[39m [90m｢wds｣[39m: webpack output is served from /
[34mℹ[39m [90m｢wds｣[39m: Content not from webpack is served from /home/hiro/build/work/webpack-demo
[34mℹ[39m [90m｢wdm｣[39m: asset index.bundle.js 366 KiB [emitted] (name: main)
runtime modules 432 bytes 3 modules
cacheable modules 336 KiB
  modules by path ./node_modules/webpack-dev-server/client/ 20.9 KiB 10 modules
  modules by path ./node_modules/html-entities/lib/*.js 61 KiB 5 modules
  modules by path ./node_modules/url/ 37.4 KiB 3 modules
  modules by path ./node_modules/querystring/*.js 4.51 KiB
    ./node_modules/querystring/index.js 127 bytes [built] [code generated]
      75 ms -> 0 ms -> 105 ms ->
      338 ms (resolving: 327 ms, restoring: 0 ms, integration: 0 ms, building: 11 ms, storing: 0 ms)
    ./node_modules/querystring/decode.js 2.34 KiB [built] [code generated]
      75 ms -> 0 ms -> 105 ms -> 338 ms ->
      0 ms (resolving: 0 ms, restoring: 0 ms, integration: 0 ms, building: 0 ms, storing: 0 ms)
    ./node_modules/querystring/encode.js 2.04 KiB [built] [code generated]
      75 ms -> 0 ms -> 105 ms -> 338 ms ->
      0 ms (resolving: 0 ms, restoring: 0 ms, integration: 0 ms, building: 0 ms, storing: 0 ms)
  modules by path ./node_modules/webpack/hot/*.js 1.42 KiB
    ./node_modules/webpack/hot/emitter.js 75 bytes [built] [code generated]
      75 ms -> 0 ms ->
      0 ms (resolving: 0 ms, restoring: 0 ms, integration: 0 ms, building: 0 ms, storing: 0 ms)
    ./node_modules/webpack/hot/log.js 1.34 KiB [built] [code generated]
      75 ms -> 58 ms ->
      0 ms (resolving: 0 ms, restoring: 0 ms, integration: 0 ms, building: 0 ms, storing: 0 ms)
./node_modules/webpack/hot/ sync nonrecursive ^\.\/log$ 170 bytes [built] [code generated]
  75 ms ->
  58 ms (resolving: 53 ms, restoring: 0 ms, integration: 0 ms, building: 5 ms, storing: 0 ms)

LOG from webpack.Compiler
<t> make hook: 605.020253 ms
<t> finish make hook: 0.146329 ms
<t> finish compilation: 8.03662 ms
<t> seal compilation: 51.091821 ms
<t> afterCompile hook: 0.089044 ms
<t> emitAssets: 8.149458 ms
<t> emitRecords: 0.138002 ms

LOG from webpack.Compilation.ModuleProfile
     | 33 ms (parallelism 1.6) resolve to new modules > ./node_modules/webpack/hot/ sync nonrecursive ^\.\/log$
     | 31 ms (parallelism 2.2) resolve to new modules > ./node_modules/html-entities/lib/index.js
     | 96 ms (parallelism 3.4) resolve to new modules > ./node_modules/querystring/index.js
    262 ms resolve to new modules
     |  | 52 ms (parallelism 4) build modules > ./node_modules/html-entities/lib/xml-entities.js
     |  | 56 ms (parallelism 3.9) build modules > ./node_modules/html-entities/lib/html4-entities.js
     |  | 79 ms (parallelism 3.5) build modules > ./node_modules/html-entities/lib/html5-entities.js
     | 262 ms build modules > 30 x javascript/auto
    264 ms build modules
**+ 11 hidden lines**

LOG from webpack.Compilation
<t> finish module profiles: 3.261562 ms
<t> finish modules: 4.005907 ms
<t> report dependency errors and warnings: 0.313237 ms
<t> optimize dependencies: 0.478636 ms
<t> create chunks: 4.726329 ms
<t> optimize: 8.033269 ms
    31 modules hashed (1 variants per module in average)
<t> module hashing: 6.089001 ms
    100% code generated (31 generated, 0 from cache)
<t> code generation: 8.265651 ms
<t> runtime requirements: 3.978663 ms
<t> hashing: initialize hash: 0.008002 ms
<t> hashing: sort chunks: 0.119712 ms
<t> hashing: hash runtime modules: 1.003699 ms
<t> hashing: hash chunks: 3.156388 ms
<t> hashing: hash digest: 0.107199 ms
<t> hashing: process full hash modules: 0.002971 ms
<t> hashing: 5.175099 ms
    100% code generated (3 generated, 0 from cache)
<t> record hash: 0.058027 ms
<t> module assets: 0.176339 ms
<t> create chunk assets: 11.191404 ms
<t> process assets: 0.333835 ms

LOG from webpack.ResolverCachePlugin
    100% really resolved (34 real resolves with 0 cached but invalid, 0 cached valid, 0 concurrent)

LOG from webpack.FlagDependencyExportsPlugin
<t> restore cached provided exports: 0.736224 ms
<t> figure out provided exports: 1.967799 ms
    100% of exports of modules have been determined (30 not cached, 1 flagged uncacheable, 0 from cache, 1 additional calculations due to dependencies)
<t> store provided exports into cache: 0.453885 ms

LOG from webpack.SideEffectsFlagPlugin
<t> update dependencies: 0.142505 ms

LOG from webpack.buildChunkGraph
<t> visitModules: prepare: 0.629772 ms
<t> visitModules: visiting: 1.394456 ms
    63 queue items processed (31 blocks)
    0 chunk groups connected
    0 chunk groups processed for merging (0 module sets, 0 forked, 0 + 0 modules forked, 0 + 0 modules merged into fork, 0 resulting modules)
    0 chunk group info updated (0 already connected chunk groups reconnected)
<t> visitModules: 2.924442 ms
<t> connectChunkGroups: 0.121117 ms
<t> cleanup: 0.060591 ms

LOG from webpack.SplitChunksPlugin
<t> prepare: 0.04144 ms
<t> modules: 2.452829 ms
<t> queue: 0.00952 ms
<t> maxSize: 0.067257 ms

LOG from webpack.FileSystemInfo
    65 new snapshots created
    0% root snapshot uncached (0 / 0)
    0% children snapshot uncached (0 / 0)
    0 entries tested
    File info in cache: 28 timestamps 0 hashes 0 timestamp hash combinations
    File timestamp snapshot optimization: 86% (209/244) entries shared via 2 shared snapshots (32 times referenced)
    Directory info in cache: 0 timestamps 0 hashes 0 timestamp hash combinations
    Missing items snapshot optimization: 62% (16/26) entries shared via 1 shared snapshots (1 times referenced)
    Managed items info in cache: 72 items
    Managed items snapshot optimization: 18% (28/158) entries shared via 2 shared snapshots (5 times referenced)
    Managed files snapshot optimization: 37% (65/174) entries shared via 4 shared snapshots (18 times referenced)
    Managed contexts snapshot optimization: 0% (0/1) entries shared via 0 shared snapshots (0 times referenced)
    Managed missing snapshot optimization: 22% (38/173) entries shared via 4 shared snapshots (9 times referenced)

LOG from webpack.Watching
<t> done hook: 6.69074 ms
<t> storeBuildDependencies: 0.185076 ms
<t> beginIdle: 0.049954 ms

webpack 5.30.0 compiled successfully in 694 ms
[34mℹ[39m [90m｢wdm｣[39m: Compiled successfully.
</details>

**What is the expected behavior?**

The full output of the profiler should be displayed in the log, with no hidden lines.

**Other relevant information:**
webpack version:  5.30.0
Node.js version: v15.13.0
Operating System: Linux 5.11.11
Additional tools:

**Comment by sokra** [comment]
Verbose seem to work. What's hidden here is some debug logging that you can control with `stats.loggingDebug`, but that won't help you here, as it will only include timings from 10ms to 50ms

**Comment by alexander-akait** [comment]
@Ruin0x11 Please provide more information

**Comment by alexander-akait** [comment]
Answered
