### ISSUE TITLE
2 loaders applied on same images resource

### ISSUE THREAD

**Issue by darul75** [webpack/webpack#1305]
hi @sokra 

I would like to apply 2 different process for my images, first one use url loader, other one use file loader ( I use it to copy my files into my destination build folder)

previously I was using only url loader, and it is great

```javascript
{ test: /\.(jpe?g|png|gif|svg|woff|eot|ttf)$/, loader: 'url?limit=10000&name=[sha512:hash:base64:7].[ext]' },
```

now I would like also apply file loader for some images that are in another folder but can not figure out how to play with exclude or extra params to achieve it.

```javascript
{ test: /\.(jpe?g|png|gif|svg|woff|eot|ttf)$/, loader: 'url?limit=10000&name=[sha512:hash:base64:7].[ext]' },
{ test: /\.(jpe?g|png|gif|svg|woff|eot|ttf)$/, loader: 'file?name=[path][name].[ext]' },
```

These 2 loaders combined to not work well and all my images processed by url loader have in result a weird base 64 result...not displaying then.

```html
<img src="data:image/svg+xml;base64,bW9kdWxlLmV4cG9ydHMgPSBfX3dlYnBhY2tfcHVibGljX3BhdGhfXyArICJpbWFnZXMvYnJhbmRpbmcvY3NzLTMuc3ZnIg==" width="40" height="40" data-reactid=".0.1.2.0.$6">
```

Somewhere in my code I do 

```javascript
require.context('../../images/posts', true, /\.jpg$/);
```

and I want all images contained in that folder to be processed by 'file' loader and not 'url' one ?

is it possible

**Comment by sokra** [comment]
You can use thehttps://github.com/webpack/multi-loader

But if you use webpack to copy files you are probably doing something wrong...

**Comment by darul75** [comment]
I do everything with webpack ;) I take a look

**Comment by darul75** [comment]
it works perfectly fine, and it just amazing...

my images are in a specifi folder, but I use mardown to write my post and inside this mardown are some image markup pointing to relative path inside this folder, so I can not require image dynamicaly in code, I just render mardown.

what do you think ?
