### ISSUE TITLE
Wrong documentation: webpack-dev-server

### ISSUE THREAD

**Issue by estani** [webpack/webpack#13052]
webpack-dev-server is not started with `
webpack-dev-server --open` anymore but with `webpack serve`.
(https://webpack.js.org/guides/development/)

**Comment by anshumanv** [comment]
The command does indeed say webpack serve

![image](https://user-images.githubusercontent.com/21009455/113506911-27fc1700-9565-11eb-9945-5701ce41bf35.png)

**Comment by anshumanv** [comment]
Maybe you have an older version of site, for any other issues related to docs open issue at https://github.com/webpack/webpack.js.org

**Comment by estani** [comment]
I think this just got changed, I doubt I had some cached version.
In anycase it is correct now, so I'm closing the ticket. Thanks.
