### ISSUE TITLE
NodeJS app with http-auth crashes after Webpack5

### ISSUE THREAD

**Issue by MorganLindqvist** [webpack/webpack#13053]
# Bug report

**What is the current behavior?**
A 5 row NodeJS application, [https://github.com/MorganLindqvist/webpack5-http-auth-failure](https://github.com/MorganLindqvist/webpack5-http-auth-failure), works as it should without Webpack-5. But when running after webpack the application crashes.

**If the current behavior is a bug, please provide the steps to reproduce.**
`git clone https://github.com/MorganLindqvist/webpack5-http-auth-failure.git`
`cd webpack5-http-auth-failure`
`npm install`
`npm run build_dev`
`node dist/main.js`

The 5-row application that crashes is as follows:
```
const auth = require("http-auth");
const basic = auth.basic({
  realm: "Realm",
  file: __dirname + "/../htpasswd"
});
```

**What is the expected behavior?**
This small snippit is a part of a larger NodeJS application and the same error/crash (see below) is triggered in that one when the usage of http-auth module was added. The error message I receive s as follows:

`TypeError: Can not find node binding files from @node-rs/bcrypt-linux-x64-gnu, @node-rs/bcrypt-linux-x64-gnux32, @node-rs/bcrypt-linux-x64-musl and /home/user/webpack5-http-auth-failure/dist/bcrypt.linux-x64-gnu.node, /home/user/webpack5-http-auth-failure/dist/bcrypt.linux-x64-gnux32.node, /home/user/webpack5-http-auth-failure/dist/bcrypt.linux-x64-musl.node
`
Until it is fixed, can I bypass it in some way?

**Other relevant information:**
webpack version:  5.30.0
Node.js version: v14.16
Operating System: Ubuntu 20.04
Additional tools: npm: 6.14.11

**Comment by alexander-akait** [comment]
`@node-rs` has very weird logic for loading
```js
function loadBinding(dirname, filename = 'index', packageName) {
    const triples = triples_1.platformArchTriples[PlatformName][ArchName];
    for (const triple of triples) {
        if (packageName) {
            try {
                return require(require.resolve(`${packageName}-${triple.platformArchABI}`, { paths: [dirname] }));
            }
            catch (e) { }
        }
        const localFilePath = path_1.join(dirname, `${filename}.${triple.platformArchABI}.node`);
        if (fs_1.existsSync(localFilePath)) {
            return require(localFilePath);
        }
    }
    const errorMsg = `Can not find node binding files from ${packageName ? triples.map((triple) => `${packageName}-${triple.platformArchABI}`).join(', ') : ''} ${packageName ? 'and ' : ''}${triples
        .map((triple) => path_1.join(dirname, `${filename}.${triple.platformArchABI}.node`))
        .join(', ')}`;
    throw new TypeError(errorMsg);
}
```

I don't think it is possible to fix in right way, even more it will not work with yarn pnp.

You can try to use https://github.com/webpack-contrib/node-loader for `.node` files

**Comment by alexander-akait** [comment]
Duplicate https://github.com/webpack-contrib/node-loader/issues/34...

**Comment by alexander-akait** [comment]
Close in favor https://github.com/webpack-contrib/node-loader/issues/34, you need `node-loader` to working with `.node` files, anyway some package have hardcored logic for loading and there is not good idea how to solve it universally, maybe make sense to open an issue in package and ask to somehow relax the logic
