### ISSUE TITLE
How does Hot Module Reload swap in changed files?

### ISSUE THREAD

**Issue by marialovesbeans** [webpack/webpack#13060]
Hey guys, does anyone understand how Webpacks HMR is it able to swap out a modified module at runtime? 

For example, you add a new function to a JS file. Browser fetches the new changed file. But then, how does it replace the old module, so the new code take into effect?

**Comment by alexander-akait** [comment]
No need to create multiple questions/issues, you already ask question https://github.com/webpack/webpack/discussions/13059
