### ISSUE TITLE
[BUG] Module not found (but it's there in node_modules).

### ISSUE THREAD

**Issue by trusktr** [webpack/webpack#1306]
I have some code that does `require('glslify')`, and node_modules contains glslify, yet after Webpack has made a bundle, that bundle contains the familiar `webpackMissingModule` function for where glslify is required. I'll see if I can link a reproduction.

**Comment by shama** [comment]
A workaround is `require('glslify/browser.js')` but it looks like the `browser` key in their package.json isn't being respected: https://github.com/stackgl/glslify/blob/master/package.json#L54

**Comment by trusktr** [comment]
Hi @shama I tried that:

```js
var glslify = require('glslify/browser.js');

var shaders = {
    vertex: glslify('./VertexShader.glsl'),
    fragment: glslify('./FragmentShader.glsl')
};

module.exports = shaders;
```

I've got glslify-loader all set up in Webpack, but that throws the error (the one hard coded in browser.js):

```
Uncaught Error: It appears that you're using glslify in browserify without its transform applied. Make sure that you've set up glslify as a source transform: https://github.com/substack/node-browserify#browserifytransform
```

So, at least now it actually imports something.

Question: should glslify-loader for Webpack automatically transform that error message into whatever it needs to be? <-- cc: @mattdesl @hughsk, and also @shama mentioned above that you can set the `browser` key in package.json (and I guess Webpack will use that as the entrypoint for `require('glslify')` calls).

**Comment by bebraw** [comment]
Any update on this? Can you try against webpack 2?

**Comment by TheLarkInn** [comment]
No response and this is reported from webpack 1 so closing. If still an issue please test in webpack @latest and submit a new issue if still a problem
