### ISSUE TITLE
`exclude` rule crashes webpack!

### ISSUE THREAD

**Issue by NullPainter2** [webpack/webpack#13075]
Hi,

I am trying to distinguish between two kinds of scss files. What would help me would be for example `exclude` in rules or `insert` having some option other that element.

My use case is pretty much this https://v4.webpack.js.org/loaders/style-loader/#lazystyletag , but `exclude` does not work at all, even when I just add it to rule.

I have webpack 4.43.0 .

This works
```
{
    test: /\.scss$/,
    use: [
        {
            loader: "style-loader",
        },
        {
            loader: "css-loader",
        },
        {
            loader: "sass-loader",
        },
    ],
},
```

but when adding `exclude` it crashes webpack:

```
{
    test: /\.scss$/,
    exclude: /\.print\.css$/,
    use: [
        {
            loader: "style-loader",
        },
        {
            loader: "css-loader",
        },
        {
            loader: "sass-loader",
        },
    ],
}
```
with this message:
```
ERROR in ./content/Styles/main.scss (../node_modules/css-loader/dist/cjs.js!../node_modules/sass-loader/dist/cjs.js!../node_modules/css-loader/dist/cjs.js??ref--17-0!./content/Styles/main.scss)
Module build failed (from ../node_modules/css-loader/dist/cjs.js):
CssSyntaxError

(4:1) C:\PathToMyProjectRedacted\content\Styles\main.scss Unknown word

2 |    -------------------------------------------------------------------------------- */
3 |
> 4 | // Cross-browser consistency in the default styling of HTML elements
| ^
5 | @import "base/normalize";
6 |

@ ./content/Styles/main.scss 2:26-197 22:4-35:5 25:25-196
@ ./content/index.ts
i ｢wdm｣: Failed to compile.
```

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

You apply `css-loader` then `sass-loader` and then `css-loader` again, so you get this error, but you ignore the issue template to I can't say what is wrong, fix it and I will.

**Comment by NullPainter2** [comment]
> Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.
> 
> Please help us help you by recreating the issue using one of our templates.
> 
> You apply `css-loader` then `sass-loader` and then `css-loader` again, so you get this error, but you ignore the issue template and I can't say what is wrong, fix it and I will help.

What templates? Where are they?

I double checked, and I did not find any mention of template in neither default text of bug report nor webpack readme.md. Please add these link to default text :)

**Comment by alexander-akait** [comment]
https://github.com/webpack/webpack/issues/new/choose

**Comment by alexander-akait** [comment]
Also not related to webpack itself, `css-loader` is better place for ask this
