### ISSUE TITLE
Load fonts from public folder

### ISSUE THREAD

**Issue by eduardfossas** [webpack/webpack#13078]
Hello, hope you are having a nice day!

It is possible to declare a @font-face inside the source folder and this is loading a font from the public folder. Like this:

@font-face {
  font-family: 'Inter';
  src: url('./assets/fonts/Inter.ttf');
}

Thanks in advance

**Comment by alexander-akait** [comment]
Yep, you can use `/public/path/to/font.ext`, please use https://github.com/webpack/webpack/discussions for questions
