### ISSUE TITLE
Broken since v5.25.0

### ISSUE THREAD

**Issue by RettentoRectangle** [webpack/webpack#13076]
# Bug report

**What is the current behavior?**

After upgrading from v5.24.x I got runtime error.

**If the current behavior is a bug, please provide the steps to reproduce.**

Simple npm-upgrade and npm i from v5.24 then starting npm run dev which is:
webpack serve --mode development --progress --config *my-config-path*

Nothing special.

- webpack-cli says: There are no validation errors in the given webpack configuration.

- Attached webpack config JSON stringified.
[webpack-config-output.log](https://github.com/webpack/webpack/files/6272312/webpack-config-output.log)

- Attached runtime error screenshot
![webpack-bug](https://user-images.githubusercontent.com/42135870/113884021-f1213d80-97be-11eb-9e07-ec2d585991e2.jpg)

**What is the expected behavior?**

Should work without any changes.

**Other relevant information:**
webpack version:  5.25.0
webpack cli: 4.6.0
webpack-dev-server: 3.11.2

Node.js version: 4.15.3
Operating System: Windows 10
Additional tools: nothing special

**Comment by alexander-akait** [comment]
> If the current behavior is a bug, please provide the steps to reproduce.

Steps to reproduce, without code nobody can't help

**Comment by alexander-akait** [comment]
And please update webpack to 5.30.0 and check again

**Comment by RettentoRectangle** [comment]
I tried every version since Feb 22. When a new wp version comes I try to upgrade it asap.

The thing is we got some dynamic json imports using to our translating system.
__LANGS__, __LOCALES__ and __APP_LOCALES__ can be found in the attached webpack config

```ts
__LANGS__.forEach(async (lang) => {
  const fileName = `${ lang }-${ lang }.json`

  const commonJson = await import(
    /* webpackChunkName: "locales/[request]" */
    __LOCALES__ + fileName
  )

  const appJson = await import(
    /* webpackChunkName: "locales/[request]" */
    __APP_LOCALES__ + fileName
  )

  addTranslation(lang, { ...commonJson.default, ...appJson.default })
})
```ts

It runs without error below 5.25.
When I cut this code out, no runtime error, but our translations are gone. :)

**Comment by alexander-akait** [comment]
You try to load something what is not exists, `forEach` can't be `async`

**Comment by RettentoRectangle** [comment]
I know about forEach and async and it's not the best code but it works until 5.25.0.

The files are there since months the code is the same since months.

If I pass wrong path the error will be: Uncaught (in promise) Error: Cannot find module PATH
But the error is webpack-require.t is not a function as you can see on the attached printscreen.

Btw, thanks for trying to help. 👍

**Comment by alexander-akait** [comment]
> I know about forEach and async and it's not the best code but it works until 5.25.0.

just luck, this does not guarantee chunk will be loaded, 

> But the error is webpack-require.t is not a function as you can see on the attached printscreen.

so you try to use code from non loaded chunk

Nothing to fix

**Comment by sokra** [comment]
hmm, weird error. the `forEach` async thing shouldn't affect that problem, so that's fine.

Not sure what's causing that...

Does it happen only on development or also in a full build?
Any custom plugins? (seems like not)

Are you able to reduce this down to a smaller repro you could share?

`__webpack_require__.t` is a helper method that should be included in the runtime chunk. You could look there if it's included there.

**Comment by RettentoRectangle** [comment]
I try to reduce it as small as possible, just give me some time.

**Comment by alexander-akait** [comment]
Friendly ping

**Comment by RettentoRectangle** [comment]
Busy pong but not forgotten.

**Comment by RettentoRectangle** [comment]
All right, I have no time to reduce the core things from our gigantic monorepo (100+ apps, dozens of websites are using the same configurable webpack with custom, own made jsx renderer, etc.) to figure out what's wrong since 5.25.0.

Last time we tried to upgrade 5.51.0 but got the same error as mentioned above.

We are stuck on 5.24.0.

Thanks for your help, I hope I will have time to find what's the problem.

Close this one. :)

**Comment by alexander-akait** [comment]
Maybe you can invite me?

**Comment by vankop** [comment]
Feel free to report new issue with `webpack@latest` with reproducible repo.

**Comment by RettentoRectangle** [comment]
I tried the latest one (5.75.0), but still not working, maybe one day. :)
The good old 5.24.x works very well.

**Comment by alexander-akait** [comment]
@RettentoRectangle can you create reproducible test repo?
