### ISSUE TITLE
DefinePlugin crashes in version 5.26.0 and up

### ISSUE THREAD

**Issue by sjoqvist** [webpack/webpack#13073]
# Bug report
**What is the current behavior?**
Code that was working with Webpack 4 up until Webpack 5.25.1 causes a crash with the following trace on Webpack 5.26 to 5.30.0 (which is the latest version at the time of writing).
```
ERR! TypeError: Cannot read property 'get' of undefined
ERR!     at /node_modules/webpack/lib/DefinePlugin.js:549:57
ERR!     at Array.forEach (<anonymous>)
ERR!     at walkDefinitionsForValues (/node_modules/webpack/lib/DefinePlugin.js:545:31)
ERR!     at /node_modules/webpack/lib/DefinePlugin.js:571:5
ERR!     at SyncHook.eval [as call] (eval at create (/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:15:1)
ERR!     at SyncHook.lazyCompileHook (/node_modules/tapable/lib/Hook.js:154:20)
ERR!     at Compiler.newCompilation (/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/Compiler.js:631:26)
ERR!     at /node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/Compiler.js:667:29
ERR!     at AsyncSeriesHook.eval [as callAsync] (eval at create (/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
ERR!     at AsyncSeriesHook.lazyCompileHook (/node_modules/tapable/lib/Hook.js:154:20)
ERR!     at Compiler.compile (/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/Compiler.js:662:28)
ERR!     at /node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/Watching.js:77:18
ERR!     at _next0 (eval at create (/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
ERR!     at eval (eval at create (/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:34:1)
ERR!     at watchRunHook (/node_modules/webpack-virtual-modules/index.js:173:5)
ERR!     at AsyncSeriesHook.eval [as callAsync] (eval at create (/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:30:1)
ERR!  TypeError: Cannot read property 'get' of undefined
ERR!     at /node_modules/webpack/lib/DefinePlugin.js:549:57
ERR!     at Array.forEach (<anonymous>)
ERR!     at walkDefinitionsForValues (/node_modules/webpack/lib/DefinePlugin.js:545:31)
ERR!     at /node_modules/webpack/lib/DefinePlugin.js:571:5
ERR!     at SyncHook.eval [as call] (eval at create (/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:15:1)
ERR!     at SyncHook.lazyCompileHook (/node_modules/tapable/lib/Hook.js:154:20)
ERR!     at Compiler.newCompilation (/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/Compiler.js:631:26)
ERR!     at /node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/Compiler.js:667:29
ERR!     at AsyncSeriesHook.eval [as callAsync] (eval at create (/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
ERR!     at AsyncSeriesHook.lazyCompileHook (/node_modules/tapable/lib/Hook.js:154:20)
ERR!     at Compiler.compile (/node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/Compiler.js:662:28)
ERR!     at /node_modules/@storybook/builder-webpack4/node_modules/webpack/lib/Watching.js:77:18
ERR!     at _next0 (eval at create (/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
ERR!     at eval (eval at create (/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:34:1)
ERR!     at watchRunHook (/node_modules/webpack-virtual-modules/index.js:173:5)
ERR!     at AsyncSeriesHook.eval [as callAsync] (eval at create (/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:30:1)
```

**If the current behavior is a bug, please provide the steps to reproduce.**
https://gist.github.com/sjoqvist/e7eeb73dfe66c4834cb2d1a190553687

Create a directory with the gist files and run
```sh
docker build -t webpack-error .
docker run -it --rm webpack-error
```

**What is the expected behavior?**
Storybook should start, instead of crashing with an error. Changing `5.26.0` to e.g. `~5.25.0` in `package.json` and then rebuilding the Docker image gets rid of the error and Storybook starts like it should.

Alternatively, if the feature I was using is deprecated I would have expected a warning prior to its removal. [The changelog](https://github.com/webpack/webpack/releases/tag/v5.26.0) mentions changes to `DefinePlugin`, but not what action I need to perform to adjust my code.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
* Arch Linux 5.10.27-1-lts
* Docker version 20.10.5, build 55c4c88966
* Node 15.13.0 (as specified in `Dockerfile`)

**Comment by alexander-akait** [comment]
`@storybook/builder-webpack4` you are on webpack v4, you mix webpack v4 and webpack v5, so you get this error

**Comment by sjoqvist** [comment]
@alexander-akait You're probably correct that it's a mixed environment, but it's not something that I've consciously selected. I've only chosen to install Webpack 5, as you can tell from the linked gist, and I can't see any dependency warnings related to this. Not sure what to make of this, though. If everything is working correctly without warnings on Webpack 5.25, then it looks like a breaking change to me.

**Comment by alexander-akait** [comment]
> If everything is working correctly without warnings on Webpack 5.25, then it looks like a breaking change to me.

Nothing to fix on webpack side, you should not use mixed webpack versions, please read https://storybook.js.org/blog/storybook-for-webpack-5/.

You need setup `storybook` on webpack v5 if you use webpack v5 for building app, otherwise please use webpack v4.

Why we can't fix it? Because it is Node.js `require` behavior

**Comment by sokra** [comment]
yeah, you were lucky that the webpack 5 DefinePlugin worked with webpack 4 until 5.25.1, but this is not something you can rely on. 
Make sure to use the right versions.
