### ISSUE TITLE
Node commonjs2 library target exports are broken when using dynamic chunks with prefetch hint

### ISSUE THREAD

**Issue by dbanisimov** [webpack/webpack#13084]
# Bug report

**What is the current behavior?**
Bundling `node` library target with `commonjs2` output type produces incorrect exports statements when dynamic import chunks are generated with prefetch hints.

**If the current behavior is a bug, please provide the steps to reproduce.**
Full repro case is available in this repo: https://github.com/dbanisimov/webpack-commonjs-exports-repro

1. Create a library with dynamic imports and prefetch hints:
```js
// dep.js
export default () => console.log("dep");

// src.js
export default async () => {
    import(/* webpackPrefetch: true */ './dep').then((res) => {
        res.default();
        console.log('lib');
    })
}
```

2. Bundle for node commonjs2
```js
module.exports = {
  target: "node",
  output: {
    library: {
      type: "commonjs2",
    },
  },
};
```

3. Import the bundled library and inspect the library exports
```js
const lib = require('./dist/lib');
console.log(lib);

// => actual `undefined`
// => expected Object [Module] { default: [Getter] }
```

**What is the expected behavior?**
The expected behavior is preserving the entrypoint exports, including the default one.

**Other**
After digging around I've found that this extra webpack runtime code line is responsible for corrupting the exports
```js
// webpack bundle mode: 'development'
// `__webpack_exports__` becomes `undefined` after the `__webpack_require__.O` function call
var __webpack_exports__ = __webpack_require__("./lib/lib.js");
__webpack_exports__ = __webpack_require__.O(__webpack_exports__);
module.exports = __webpack_exports__;
```

This line comes from the `onChunksLoaded` runtime call introduced in [this change](https://github.com/webpack/webpack/commit/c7f93af138cc56fb825c256b7972bcaf1bb2e137). I can confirm that downgrading to `webpack@5.24` mitigates the issue.

**Other relevant information:**
webpack version:  5.25+
Node.js version: 14.16
Operating System: Ubuntu 20.04
Additional tools: -

**Comment by alexander-akait** [comment]
Duplicate https://github.com/webpack/webpack/issues/12993, thanks for the issue
