### ISSUE TITLE
The code compiles, but the browser does not refresh automatically，when set target: ['web', 'es5']

### ISSUE THREAD

**Issue by anneyangyue** [webpack/webpack#13093]
The code compiles, but the browser does not refresh automatically，when set target: ['web', 'es5']
If set target: 'web', it works, but build.js is es6

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

You need `webpack-dev-server@4.beta-2` (stable release will be soon)
