### ISSUE TITLE
core plugin LimitChunkCountPlugin generates deprecation warning

### ISSUE THREAD

**Issue by meskill** [webpack/webpack#13099]
# Bug report

**What is the current behavior?**

In webpack 5 (v5.31.0) adding [webpack.optimize.LimitChunkCountPlugin](https://webpack.js.org/plugins/limit-chunk-count-plugin/#root) to config will lead to deprecation warning in console:
```
(node:24852) [DEP_WEBPACK_CHUNK_INTEGRATE] DeprecationWarning: Chunk.integrate: Use new ChunkGraph API
(Use `node --trace-deprecation ...` to show where the warning was created)
(node:24852) [DEP_WEBPACK_CHUNK_INTEGRATED_SIZE] DeprecationWarning: Chunk.integratedSize: Use new ChunkGraph API
```

**If the current behavior is a bug, please provide the steps to reproduce.**

1. add webpack.optimize.LimitChunkCountPlugin to config:
```
  plugins: [
    new webpack.optimize.LimitChunkCountPlugin({
      maxChunks: 1,
    }),
  ],
};
```
2. Run build

**What is the expected behavior?**
No deprecation warnings should be showed

**Other relevant information:**
webpack version:  5.31.0

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

You have webpack v4 and webpack v5 in your project.

**Comment by meskill** [comment]
> Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.
> 
> Please help us help you by recreating the issue using one of our templates.
> 
> You have webpack v4 and webpack v5 in your project.

Thanks for the suggestion about webpack version mix, but I can even point to source code in webpack5 where deprecations are arising:

Here is the code in LimitCountChunkPlugin that using deprecated api:
https://github.com/webpack/webpack/blob/master/lib/optimize/LimitChunkCountPlugin.js#L178
https://github.com/webpack/webpack/blob/master/lib/optimize/LimitChunkCountPlugin.js#L207
https://github.com/webpack/webpack/blob/master/lib/optimize/LimitChunkCountPlugin.js#L225

that api has deprecation tag in Chunk.js:
https://github.com/webpack/webpack/blob/master/lib/Chunk.js#L260
https://github.com/webpack/webpack/blob/master/lib/Chunk.js#L329

that eventually will raise deprecation warning in ChunkGroup.js:
https://github.com/webpack/webpack/blob/1f48895e5309f32173e7b1252b1e269b25da0656/lib/ChunkGraph.js#L1521

Speaking about template for the issue - it is neither bug (as it works fine, just generates warnings that I cant fix on the user side) or a feature request.

**Comment by alexander-akait** [comment]
Yep, feel free send a PR

**Comment by alexander-akait** [comment]
Bug it is more bug

**Comment by alexander-akait** [comment]
Fixed https://github.com/webpack/webpack/pull/13169
