### ISSUE TITLE
`webpack`'s named exports not available with Node's ESM resolution

### ISSUE THREAD

**Issue by silverwind** [webpack/webpack#13098]
[These exports](https://github.com/webpack/webpack/blob/48b7cce9ce7a1ceab12ea4955570b975b89d3613/lib/index.js#L94) can not be destructured when importing webpack as from an ESM module because Node's [static analysis](https://nodejs.org/api/esm.html#esm_commonjs_namespaces) does not detect the named exports. I would suggest assigning to `module.exports.<property>` directly so Node has an easier time detecting it, or even better convert webpack to ESM (which will work in all supported node versions in 20 days).

```js
// fails with no named export present
import {SourceMapDevToolPlugin} from 'webpack';

// using default export works
import webpack from 'webpack';
const {SourceMapDevToolPlugin} = webpack;
```

Quotes from link above:

> For better compatibility with existing usage in the JS ecosystem, Node.js in addition attempts to determine the CommonJS named exports of every imported CommonJS module to provide them as separate ES module exports using a static analysis process.

> The detection of named exports is based on common syntax patterns but does not always correctly detect named exports

**Comment by alexander-akait** [comment]
Answer in the error:
```
import pkg from 'webpack';
const {SourceMapDevToolPlugin} = pkg;
```

We avoid it to improve perf

**Comment by silverwind** [comment]
Node's detection code is at https://github.com/guybedford/cjs-module-lexer. I guess it could be solved on their end too but webpack is making it extra hard on them with that `mergeExports` function. cc: @guybedford.

**Comment by alexander-akait** [comment]
I don't think it will be solved `cjs-module-lexer.`, we use `getter` to avoid extra `require`

**Comment by silverwind** [comment]
getter is [supported](https://github.com/guybedford/cjs-module-lexer#getter-exports-parsing) but the [`mergeExports`](https://github.com/webpack/webpack/blob/48b7cce9ce7a1ceab12ea4955570b975b89d3613/lib/index.js#L66) wrapper is not. I guess it would be possible to un-wrap that but the file would probably double in size after that.

**Comment by guybedford** [comment]
There is a hack that esbuild uses here to emit a hint, see https://github.com/guybedford/cjs-module-lexer/pull/46.

I don't personally recommend this approach as it is sensitive to minification, but if that is the final output being executed in Node.js via npm or otherwise it can solve the problem.

**Comment by sokra** [comment]
I think I can live with only default export being available.
