### ISSUE TITLE
Allow loaders to be functions

### ISSUE THREAD

**Issue by nick-thompson** [webpack/webpack#131]
I'd really like to be able to pass functions to loaders in my webpack config:

``` js
function jsLoader(source) {
  // do whatever...
}

module.exports = {
  ...,
  module: {
    loaders: [
      {test: /\.js$/, loader: jsLoader}
    ]
  },
  ...
};
```

The reason is that I have some global configuration state in my webpack.config.js, example:

``` js
var STATIC_ROOT = 'path/to/static/root';
```

And my js_loader needs access to that static root for the transformation that it performs on the source code. My options are either to duplicate the configuration in each files, which is annoying to maintain and error-prone, or to throw all of the configuration variables into process.env, and from my js_loader, read them back from process.env, which just feels hacky.

**Comment by ericmorand** [comment]
@sokra, where is the `closures` option documented? And why is the TypeScript definition missing for this property?

**Comment by EmptyOa** [comment]
Not working in webpack 4, throws `Invalid configuration object` with `closures` property, why the hell??
