### ISSUE TITLE
How dynamically create a module

### ISSUE THREAD

**Issue by kisenka** [webpack/webpack#1310]
I am writing a plugin which creates SVG sprite. It globs over the directories, merge svg files in one image and return the result. Idea is to dynamically create a module (which contains merged images) so that other modules can require it as an usual module. Is it possible in webpack? Or maybe you can suggest more easy solution.

**Config**
```js
{
  plugins: [
    new SvgSpritePlugin({
      sprites: {
        icons: 'images/svg/icons/*.svg',
        logos: 'images/svg/logos/*.svg',
        socials: 'images/svg/logos/{twitter,youtube,facebook}.svg',
      }
    })
  ]
}
```

**Somewhere in the application**
```js
var logosSprite = require('sprite/logos'); // require dynamically created module
document.body.appendChild(logoSprite);
```

**Comment by sokra** [comment]
Possible, but this is not the webpack-style of doing it.

Write a loader which takes a image and returns a CSS fragment (best a CSS Module).

If this works fine: Write a plugin which takes all modules with your loader, merges the images to a sprite and changes the CSS fragment (or CSS Module).

This is a lot of work which is probable obsolete once you switch your server to HTTP2. Major browsers already support it...

**Comment by kisenka** [comment]
Unfortunately I don't have access to the server config, and CSS modules aren't exactly what I need.

As for now I am looking at these two options:

1. A loader that loads an empty module, then does all the work `require('sprite-loader?pattern=images/svg/icons/*.svg&id=icons!dummy-module')` and returns a sprite as a string which is then just inserted into a page. This is going to work, but isn't exaclty a webpack-way of doing things :)

2. Get the images separately via `require.context('images/svg/icons', false, /\.svg$/)`, and assemble a sprite during runtime. This one is more webpack-y, but will surely have a toll on browser when it will have to process it all.

I am working on a site comprised of hundreds of pages, and have the following requirements:

1. Each of the page may have its own entry-point and may use multiple sprites.
2. At the template decorator level one more entry-point is added that initializes the core functions common to all pages based on this template.
3. CommonChunksPlugin is used to keep the frequently reused code in separate chunks.

It would be ideal to have several commonly used sprites (like icons or logos) stored in a common-chunk, and page-specific sprites that are only used in a page's entry-point.

**Comment by adjavaherian** [comment]
I'm trying to do a similar thing with sass.  I want to follow the dependency graph of the entry module and compile all the sass files I find and place the whole string into the entry chunk.  Perhaps a dynamically created module and webpack require would be better?  

Not sure, but I took @sokra 's advice above and created a loader that starts its own webpack instance on the entry file.  The loader's configuration has a plugin which recursively collects those dependencies, but I have no idea how to output them back to the loader.  (https://github.com/adjavaherian/sass-lifter-loader)[https://github.com/adjavaherian/sass-lifter-loader]

**Comment by bgannonPL** [comment]
+1. I'm attempting to do something similar, collect data via a loader, and then modify a module (rather than create a new one) with the results, so that it will be included in the same build. Trying to avoid having to make an extra http request for a generated file.
