### ISSUE TITLE
React and Angular not working together in  Module Federation 

### ISSUE THREAD

**Issue by m-korkut** [webpack/webpack#13103]
I cannot import Angular project in React when using module federation.
I couldn't run React and Angular together.

I would be glad if you could help.

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Please use stackoverflow for these questions
