### ISSUE TITLE
Unable to load federated modules based on condition using Webpack 5  module federation

### ISSUE THREAD

**Issue by isachinraj** [webpack/webpack#13100]
Hi @sokra 

I have an application that is acting as a container application.
I want to consume Application 1, Application 2, and Application 3 in the container application.

Application 1, Application 2 and Application 3 are exposed to container application using Webpack 5 module federation plug-in.

Now in container application I have the following codes to consume the individual application.

let App1, App2, App3;

if(user has access to app1){
   App1= React.lazy(() => import('app1/App'));
}

if(user has access to app2){
   App2= React.lazy(() => import('app2/App'));
}

if(user has access to app3){
   App3= React.lazy(() => import('app3/App'));
}

<Switch>
   <Route exact path="/app1" render={ () => <App1 /> } />
   <Route exact path="/app2" render={ () => <App2 /> } />
   <Route exact path="/app3" render={ () => <App3 /> } />
</Switch>

Even if the user can only access app1, the container application will load the remoteEntry.js file of all applications (App1, App2, and App3).
If the user has access to App2 and App3, I don't want to load the remoteEntry.js files from App2 and App3.
Is it possible to conditionally render the federated modules? If so, how can I achieve this in this scenario?

Any information will be very helpful.

Thanks and Regards,
Raj

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

If you can't fill out our issue template, please prefer to use https://github.com/webpack/webpack/discussions
