### ISSUE TITLE
Webpack 5 app load time slowdown

### ISSUE THREAD

**Issue by atfzl** [webpack/webpack#13125]
# Bug report

**What is the current behavior?**
Our app's load time increased significantly when we upgraded to Webpack 5.
Target for our app is `ES2015`.

The JavaScript execution time increased from 1.2s to 1.6s which is pretty significant.
We narrowed it down to usage of arrow functions in Webpack 5 internal runtime code.

On using arrow functions in webpack's internal code, the self time of functions like `__webpack_require__` increased significantly. Ideally the self time for functions like this should be close to `0`, which it is when it uses vanilla functions.

Webpack 5 by default uses es2015 in its internal code instead of es5 in Webpack 4.
So, now the internal code uses `() => {}` instead of `function() {}`.

A solution for this would be to change the default value of `arrowFunction` to `false` instead of `true` in 
https://webpack.js.org/configuration/output/#outputenvironment.

**If the current behavior is a bug, please provide the steps to reproduce.**
I have created a small repo to reproduce this. This repo was generated with [gatsby](https://www.gatsbyjs.com).

Repo: https://github.com/atfzl/webpack5-arrow-function-slowdown

Start the dev server:
* `npm install`
* `npm run start`

## Vanilla function

This will start the dev server at http://localhost:8000 with `target: es5`. This is our good build.
**Time to run the JavaScript: 83ms**
Get the timeline data from Chrome timeline for the app load.
[Chrome timeline vanilla function.json.zip](https://github.com/webpack/webpack/files/6303901/vanilla.function.json.zip)
![Screen 2021-04-13 at 18 32 41@2x](https://user-images.githubusercontent.com/14862437/114557019-e109d200-9c86-11eb-9952-8b23c89ccf2a.png)

Stop the dev server.

## Arrow function
Now change the line ``config.target = [`web`, `es5`]`` to ``config.target = [`web`, `es2015`]`` in `node_modules/gatsby/dist/utils/webpack.config.js`.
Start the dev server again with `npm run start`.

Go to http://localhost:8000

Now the build served will have arrow functions in the internal code.
**Time to run the JavaScript: 117ms**
Get the timeline data from Chrome timeline for the app load.
[Chrome timeline arrow function.json.zip](https://github.com/webpack/webpack/files/6303917/arrow.function.json.zip)
![Screen 2021-04-13 at 18 36 46@2x](https://user-images.githubusercontent.com/14862437/114557667-84f37d80-9c87-11eb-897f-f192eabc6354.png)

The build with arrowFunction is taking 30-40% more time when running JavaScript.
I've highlighted only one place where `options.factory` is taking more self time but there are other places as well.
Same behavior with the production build as well.

You can also try experimenting with arrow functions and vanilla functions in the browser using [local overrides](https://developer.chrome.com/blog/new-in-devtools-65/#overrides) in Chrome.

Changing the vanilla function to fat arrow in `framework.js` at this place increases the self time of `options.factory` at the place specified in the above screenshots of timeline.
<img width="843" alt="Screen 2021-04-13 at 19 18 57@2x" src="https://user-images.githubusercontent.com/14862437/114563671-3e088680-9c8d-11eb-861a-f4c75b4e4865.png">

**What is the expected behavior?**
So, this is not actually a bug with Webpack but the default config provided degrades the performance.
I couldn't find a reason why arrow function is taking much more time. I'll be opening an issue in V8 to find out the cause.

**Other relevant information:**
webpack version:  5.30.0
Node.js version: 12.18.3
Operating System: macOS Big Sur 11.2.3
Additional tools:

**Comment by sokra** [comment]
That's interesting. Looks like it's eager parsing in the `function` case, but lazy parsing in the `arrow-function` case.

But you should look into that too deeply since it's in development mode. Please profile the production mode code, since this is what the user gets.

**Comment by atfzl** [comment]
Steps to run prod and serve build in the repo https://github.com/atfzl/webpack5-arrow-function-slowdown:

* npm run install
* npm run build
* npm run serve

Starts the server on http://localhost:9000/

### Vanilla function
![prod vanilla function](https://user-images.githubusercontent.com/14862437/114682661-ed486a80-9d2c-11eb-823c-d9e7e8cfa0bb.png)
[prod vanilla function.json.zip](https://github.com/webpack/webpack/files/6309574/prod.vanilla.function.json.zip)

### Arrow function
![prod arrow function](https://user-images.githubusercontent.com/14862437/114682790-0b15cf80-9d2d-11eb-9655-0b23787e36ec.png)
[prod arrow function.json.zip](https://github.com/webpack/webpack/files/6309578/prod.arrow.function.json.zip)

I have used the function `53` as a baseline taking ~0.25ms.

From the screenshot you can see the difference between time taken to execute the main function of the script.
8.55ms for vanilla function
13.98ms for arrow function
The difference is 5.43ms.

I have added the difference in self times in arrow function case, at some places there is increase in self time and at some places there is new self time which was 0 in vanilla function case.
The sum of the increase in self time is 5.65ms which is close to the total difference of 5.43ms.

**Comment by sokra** [comment]
hmm that's really interesting.

I think this is something for @mathiasbynens

**Comment by atfzl** [comment]
@sokra @mathiasbynens Could you take a look at this?

**Comment by alexander-akait** [comment]
@atfzl it is v8 problem, we can't fix it here, you can disable arrow function or use `es5`

**Comment by sokra** [comment]
We are not even sure what's the problem here. I would guess different behavior of eager vs lazy compilation of functions. I would like to have more insight into the differences in v8 here...

**Comment by atfzl** [comment]
I agree that the issue is not with Webpack, but this ultimately affects all Webpack 5 users who are using `ES6` and above. 

Can we change the default value of `arrowFunction` to `false` in https://webpack.js.org/configuration/output/#outputenvironment till this is fixed.

**Comment by alexander-akait** [comment]
You can do it manually, the problems is not for all webpack users, it is also for all js users, and ideally should be fixed in v8, please open a bug in their bug tracker, if we even fit it, other scripts on your package can use it and you will have the same problem
