### ISSUE TITLE
export is undefined use webpack 5 bundle commonjs

### ISSUE THREAD

**Issue by diem98** [webpack/webpack#13135]
# Bug report

**What is the current behavior?**
here is my webpack config to bundle a commonjs  utils:
```
const path = require('path');
module.exports = {
  mode: process.env.NODE_ENV || 'development',
  entry: {
    app: path.resolve('./index.js'),
  },
  devServer: {
    hot: true,
    writeToDisk: true,
  },
  output: {
    libraryTarget: 'commonjs2',
    globalObject: 'this'
  },
  target: 'node',
  devtool: false,
}
```
package.json as below
```
  "scripts": {
    "dev": "webpack-cli serve",
    "build": "webpack --mode production",
    "clean": "rm -rf dist"
  },
  "dependencies": {
    "webpack": "^5",
    "webpack-cli": "^4.6.0",
    "webpack-dev-server": "^3"
  }
```
`index.js` just export a simple function:
```
export function customUtil() {
  console.log(`custom util=========`)
}
```

after run `yarn dev`, You will find  that the `dist/app.js` module.exports is undefined:
![image](https://user-images.githubusercontent.com/41503212/114721049-20a9ea00-9d6b-11eb-89b4-486aef377409.png)

I know dev-sever will add some js like `webpack/hot/dev-server.js` to the entry array。

The same code in webpack 4 results in the following, I can import customUtil from index.js as expected: 
![image](https://user-images.githubusercontent.com/41503212/114722292-42f03780-9d6c-11eb-9f1c-4724ef1d18f8.png)

I don't know if this is the expected result in webpack 5. The same goes for umd.

This prevents me from using the webpack 5 commonjs or umd bundle with hot updates in browser.😭

**If the current behavior is a bug, please provide the steps to reproduce.**

As mentioned above, the current problem can be reproduced。

**What is the expected behavior?**

I'm not sure if it will behave the same way as webpack 4, but if so, it would be great~

**Other relevant information:**
webpack version:  5.32.0
webpack-cli version: 4.6.0
webpack-dev-server version: 3.11.2
Node.js version: 14.15.4
Operating System:  macos

**Comment by alexander-akait** [comment]
`webpack-dev-server@3` is not supported libraries, please use `webpack-dev-server@4-beta.2`, stable release will be soon

**Comment by diem98** [comment]
> `webpack-dev-server@3` is not supported libraries, please use `webpack-dev-server@4-beta.2`, stable release will be soon

webpack-dev-server v4 works fine. But how do I clear the output information.
I've read the changelog:
![image](https://user-images.githubusercontent.com/41503212/114838845-b2ffcb80-9e07-11eb-93aa-7022678b6f2d.png)
But still logging as below:
![image](https://user-images.githubusercontent.com/41503212/114838935-c874f580-9e07-11eb-9fd5-942bc70b2d76.png)

my webpack config is:

```
 stats: {
    logging: false,
  },
  infrastructureLogging : {
    level: 'none',
  }
```

**Comment by alexander-akait** [comment]
`stats: 'errors-warnings'`
