### ISSUE TITLE
Babel throws on JSX files when preset-react is not added

### ISSUE THREAD

**Issue by AbdelhayA0100** [webpack/webpack#13136]
"babel-loader": "^8.1.0",
"babel-preset-es2015": "^6.24.1",
"babel-preset-react": "^6.24.1",
"babel-preset-stage-2": "^6.24.1",
"webpack": "^4.44.2",
"webpack-cli": "^4.6.0",
"webpack-dev-server": "^3.11.1"

const path = require("path");
var SRC_DIR = path.resolve(__dirname, "src");

///////////////////////////file web webpack.config /////////////////////////////
const path = require("path");

var DIST_DIR = path.resolve(__dirname, "dist");
var SRC_DIR = path.resolve(__dirname, "src");

module.exports = {
	mode: "development",
	entry: SRC_DIR + "/index.js",
	output: {
		path: DIST_DIR + "/src",
		filename: "bundle.js",
		publicPath: "/src/",
	},
	resolve: {
		extensions: [".js", ".jsx"],
		alias: {
			assets: path.resolve(__dirname, "src/assets/"),
		},
	},
	module: {
		rules: [
			{
				test: /\.jsx?$/,
				loader: "babel-loader",
				include: __dirname + "/src/",
				exclude: "/node_modules/",
				query: {
					presets: [
						"babel-preset-myPreset",
						"@babel/preset-env",
						"@babel/preset-react",
						"es2015",
						"react",
						"stage-2",
					],
				},
			},
		],
	},
};
//////////////////////////////////////////////////////

ERROR in ./src/index.js 7:2
Module parse failed: Unexpected token (7:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| ReactDOM.render(

<React.StrictMode>
|
| </React.StrictMode>,

file index
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';

ReactDOM.render(
<React.StrictMode>

</React.StrictMode>,
document.getElementById('root')
);

**Comment by AbdelhayA0100** [comment]
webpack-4

**Comment by alexander-akait** [comment]
Please use https://github.com/webpack/webpack/discussions for supporting, also please provide more information - versions/code/how you run webpack, better to create simple example. 

Problem here `include: __dirname + "/src/",`, remove it
