### ISSUE TITLE
[Webpack 5]: Error during require when runtimeChunk: single and split chunks are used (node)

### ISSUE THREAD

**Issue by iPherian** [webpack/webpack#13130]
# Bug report

**What is the current behavior?**

When using a single runtimeChunk and forcing certain files into a seperate chunk, throws errors during require "Cannot find module './undefined". (target is node)

(minimal example)

webpack config:

```javascript
const cfg = {
  mode: "production",
  target: "node",
  output: {
    libraryTarget: "commonjs2",
  },
  entry: "./src/entry.js",
  optimization: {
    runtimeChunk: "single",
    splitChunks: {
      cacheGroups: {
        other: {
          name: "source-mapped",
          enforce: true,
          chunks: "initial",
          test: /source-mapped\.js/,
        },
      },
    },
  },
};

module.exports = cfg;
```

Works if one removes `runtimeChunk: "single"`

Basically I was hoping that I would be able to be in production, but have some of the source source-mapped and the rest not. So I was trying to have a separate chunk for certain files and later would enable source mapping on that file. Also would be nice to have a single common runtime between all entry points.

**If the current behavior is a bug, please provide the steps to reproduce.**

[example repo](https://github.com/iPherian/webpack-v5-node-split-chunks-bug)

- `git clone https://github.com/iPherian/webpack-v5-node-split-chunks-bug.git`
- `cd webpack-v5-node-split-chunks-bug`
- `npm init`
- `npm install webpack webpack-cli`
- `./node_modules/.bin/webpack`
- `node ./test-dist.js # just require's dist/main.js`

**What is the expected behavior?**

Should be able to require dist/main.js without error.

**Other relevant information:**
webpack version: v5.32.0
Node.js version: v14.16.1
Operating System: Win 10 x64 1909 18363.1316
Additional tools: n/a

Error trace:
```
Error: Cannot find module './undefined'
Require stack:
- C:\src\webpack-v5-node-split-chunks-bug\dist\runtime.js
- C:\src\webpack-v5-node-split-chunks-bug\dist\main.js
- C:\src\webpack-v5-node-split-chunks-bug\test-dist.js
           at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
           at Function.Module._load (internal/modules/cjs/loader.js:725:27)
           at Module.require (internal/modules/cjs/loader.js:952:19)
           at require (internal/modules/cjs/helpers.js:88:18)
    at Object.s.f.require (C:\src\webpack-v5-node-split-chunks-bug\dist\runtime.js:1:569)
    at C:\src\webpack-v5-node-split-chunks-bug\dist\runtime.js:1:226
    at Array.reduce (<anonymous>)
    at Function.s.e (C:\src\webpack-v5-node-split-chunks-bug\dist\runtime.js:1:204)
    at Array.map (<anonymous>)
    at Function.s.X (C:\src\webpack-v5-node-split-chunks-bug\dist\runtime.js:1:352) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\src\\webpack-v5-node-split-chunks-bug\\dist\\runtime.js',
    'C:\\src\\webpack-v5-node-split-chunks-bug\\dist\\main.js',
    'C:\\src\\webpack-v5-node-split-chunks-bug\\test-dist.js'
  ]
}

```

webpack bundle output:

```
asset runtime.js 626 bytes [compared for emit] [minimized] (name: runtime)
asset main.js 237 bytes [compared for emit] [minimized] (name: main)
asset source-mapped.js 118 bytes [compared for emit] [minimized] (name: source-mapped) (id hint: other)
Entrypoint main 981 bytes = runtime.js 626 bytes source-mapped.js 118 bytes main.js 237 bytes
runtime modules 1.86 KiB 5 modules
cacheable modules 219 bytes
  ./src/entry.js 124 bytes [built] [code generated]
  ./src/source-mapped.js 95 bytes [built] [code generated]
webpack 5.32.0 compiled successfully in 204 ms
```

**Comment by alexander-akait** [comment]
Bug

**Comment by iPherian** [comment]
@sokra wow thanks for the quick fix! Works in my actual project too. 😄🙏

**Comment by mahidhar4** [comment]
@sokra still seeing this issue in recent version
