### ISSUE TITLE
Persistent caching uses absolute paths for node_modules

### ISSUE THREAD

**Issue by 7rulnik** [webpack/webpack#13139]
# Bug report

**What is the current behavior?**

Webpack stores absolute paths for node_modules (not only for node_modules I believe). So when the base path changes it leads to error like that: 

```
[webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo]
/Users/v7rulnik/projects/project/node_modules/emojis-list invalidated because hashes differ
(missing != emojis-list@3.0.0)
```

The main problem that there are environments where users can't control the base directory. For example Jenkins CI. Base directory in Jenkins looks like this: `/home/jenkins/agent/workspace/$PROJECT_NAME_$GIT_BRANCH/`. So it's impossible to share cache between branches.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Run webpack with cache enabled in the project directory, for example: `~/project/`
2. Rename project directory: `~/project/ → ~/project_renamed/`
3. Run webpack in `~/project_renamed/`

**What is the expected behavior?**

The base directory shouldn't affect persistent caching. Maybe we can store relative paths in pack files and concatenate them with current [context](https://webpack.js.org/configuration/entry-context/#context)?

**Other relevant information:**
webpack version: 5.32.0
Node.js version: 14.15.4
Operating System: MacOS

**Comment by alexander-akait** [comment]
Duplicate https://github.com/webpack/webpack/issues/10400, on our roadmap, there is some difficult problems, but they are solvable, please use search in future

**Comment by 7rulnik** [comment]
Ooops sorry, missed it somehow

**Comment by alexander-akait** [comment]
Don't worry :smile:
