### ISSUE TITLE
How to decide which output file to use when using i18n plugin?

### ISSUE THREAD

**Issue by littlee** [webpack/webpack#1313]
I use i18n plugin to generate multi-language output files,
e.g.
en_US.output.js
zh_CN.output.js

What's the best practice to decide whick file should be include?
writing judgement inside my backend template
or
writing another webpack.config.js file?

**Comment by sokra** [comment]
That's backend logic. The `Accept-Language` header can be used for this purpose.

**Comment by littlee** [comment]
Thanks any way.
Our back-end guy use cookie to set language.
I use JavaScript to get the cookie value.
