### ISSUE TITLE
Uncaught TypeError: __webpack_require__.n is not a function

### ISSUE THREAD

**Issue by jens-duttke** [webpack/webpack#13152]
# Bug report

**What is the current behavior?**

After updating from Webpack `5.24.4` to Webpack `5.25.0` and **any** newer version, I get the following error in the browsers dev tools:
```
runtime-bootstrap.js:39 Uncaught TypeError: __webpack_require__.n is not a function
    at eval (VM49083 errorReporting.ts:3)
    at Module../errorReporting.ts (error-reporting.js:40)
    at __webpack_require__ (runtime-bootstrap.js:36)
    at __webpack_exec__ (error-reporting.js:842)
    at error-reporting.js:843
    at webpackJsonpCallback (runtime-bootstrap.js:1199)
    at Array.forEach (<anonymous>)
    at runtime-bootstrap.js:1212
    at runtime-bootstrap.js:1214
    at runtime-bootstrap.js:1220
```

**If the current behavior is a bug, please provide the steps to reproduce.**

I've reduced the size of my app to an absolutely minimum and created a repo, which is available here:
https://github.com/jens-duttke/webpack-bug-demo

**What is the expected behavior?**

Since I did no code changes with the Webpack update, I expect that the code works as it did in `5.24.4`.
I can't see any breaking changes in the release notes of `5.25.0`, which could cause this.

**Other relevant information:**
webpack version:  `5.25.0` up to `5.33.2`
Node.js version: `15.8.0`
Operating System: Windows 10 Pro
Additional tools:
- Babel `7` / babel-loader `8.2.2`
- TypeScript `4.2`
- React `17`
- Core-js `3.1`
- css-loader `5.2.1`
- mini-css-extract-plugin `1.4.1`
- html-webpack-plugin `5.3.1`

**Comment by alexander-akait** [comment]
hm, multiple runtime chunks, you don't need `runtime-bootstrap.js` chunk, I think it is bug

**Comment by jens-duttke** [comment]
> hm, multiple runtime chunks, you don't need `runtime-bootstrap.js` chunk, I think it is bug

In my full app, I have different HTML pages and they use different runtimes. The runtime bundle `runtime-bootstrap` is loaded on all pages. The reason for this is to keep the runtimes as small as possible and only include what is really necessary on the respective pages.

**Comment by sokra** [comment]
Using multiple runtimes from a single compilation on the same page is not supported.

You might use multiple configuration instead to do that, but make sure to choose a different `output.uniqueName` for each of them if you want to load the on the same page.

**Comment by jens-duttke** [comment]
> Using multiple runtimes from a single compilation on the same page is not supported.

But that would mean that shared code would be also separately bundled for each configuration, right?
And how can multiple configurations share the same devServer?

Do you know a more in-depth example where multiple configurations are used for app development?
All I can find are 5 line-of-code examples for library-development without devServer etc.

**Comment by alexander-akait** [comment]
> And how can multiple configurations share the same devServer?

Using multiple dev server is limited right now, in future it will be possible
