### ISSUE TITLE
5.25+, Webpack AMD bundle exports changed behavior when used with runtimeChunk

### ISSUE THREAD

**Issue by SimmeNilsson** [webpack/webpack#13165]
# Bug report

**What is the current behavior?**
Starting with 5.25, webpack bundles output as AMDs, in combination with _runtimeChunk_, no longer provides the exports of the main file of the bundle when imported, using for example RequireJS.

**If the current behavior is a bug, please provide the steps to reproduce.**
Repository with minimal code to reproduce:
https://github.com/SimmeNilsson/webpack_amd
Steps:
_yarn
yarn build_
Run _index.html_, watch what main.js receives from bundle (undefined).
Downgrade to Webpack 5.24 or older
_yarn add -D webpack@5.24.4_
Run _index.html_ again, watch what main.js receives from bundle (exported object).

**What is the expected behavior?**
Exported object received in main.js

**Other relevant information:**
webpack version:  5.33.2
Node.js version: 15.12
Operating System: Windows 10
Additional tools: yarn, RequireJS

Happens when _runtimeChunk_ is set ("single").

**Comment by alexander-akait** [comment]
Yep, regression
