### ISSUE TITLE
Bug using Webpack

### ISSUE THREAD

**Issue by manav95** [webpack/webpack#13168]
# Bug report

**What is the current behavior?**
I am currently having an issue with using webpack to compile and bundle my web app. The issue is this:

ERROR in /Users/mavd/TIN/src/App.test.tsx
6:19-22
[tsl] ERROR in /Users/mavd/TIN/src/App.test.tsx(6,20)
      TS2786: 'App' cannot be used as a JSX component.
  Its instance type 'App' is not a valid JSX element.
    Type 'App' is missing the following properties from type 'ElementClass': context, setState, forceUpdate, props, and 2 more.

ERROR in /Users/mavd/TIN/src/App.tsx
34:9-15
[tsl] ERROR in /Users/mavd/TIN/src/App.tsx(34,10)
      TS2786: 'Navbar' cannot be used as a JSX component.
  Its instance type 'Navbar' is not a valid JSX element.
    Type 'Navbar' is missing the following properties from type 'ElementClass': context, setState, forceUpdate, props, and 2 more.

ERROR in /Users/mavd/TIN/src/App.tsx
35:8-39:10
[tsl] ERROR in /Users/mavd/TIN/src/App.tsx(35,9)
      TS2607: JSX element class does not support attributes because it does not have a 'props' property.

ERROR in /Users/mavd/TIN/src/App.tsx
35:9-16
[tsl] ERROR in /Users/mavd/TIN/src/App.tsx(35,10)
      TS2786: 'AboutUs' cannot be used as a JSX component.
  Its instance type 'AboutUs' is not a valid JSX element.
    Type 'AboutUs' is missing the following properties from type 'ElementClass': context, setState, forceUpdate, props, and 2 more.

Here is a snippet from App.tsx:

```
import { Component } from 'react';
import "./App.css";
import Navbar from "./components/Navbar";
import ContactForm from "./components/ContactForm";
import Calendar from "./components/Calendar";
import Gallery from "./components/Gallery"
import AboutUs from "./components/AboutUs"
import Message from "./components/Message"

import message from './message';
import { animateScroll as scroll } from "react-scroll";
import { hot } from "react-hot-loader";

interface AppState {
  onboardEnabled: boolean;
}

class App extends Component<any, AppState> {
  state = {onboardEnabled: true};
  
  constructor(props: any) {
    super(props);
    this.onboard = this.onboard.bind(this)
  }

  onboard() { 
    this.setState({onboardEnabled: false});
    scroll.scrollTo(20000)
  }

  render() {
    return (
      <div className="App">
        <Navbar />
        <AboutUs
          title="About Us"
          id="section1"
          onboard={this.onboard}
        />
```

**If the current behavior is a bug, please provide the steps to reproduce.**
It happens when I run webpack on my React app that also uses Typescript.

**What is the expected behavior?**
As the webpack.config.js file is this:

```
const path = require("path");
const webpack = require('webpack');
var HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
    entry: "./src/index.js",
    mode: "development",
    devtool: "source-map",
    module: {
        rules: [
            {
                test: /\.(js|jsx)$/,
                exclude: /node_modules/,
                use: "babel-loader"
            },
            {
                test: /\.tsx?$/,
                use: "ts-loader",
                exclude: /node_modules/
            },
            {
                test: /\.(css|scss)$/,
                use: ["style-loader", "css-loader"],
            },
          {
            test: /\.(png|svg|jpg|gif)$/,
            use: ['file-loader']
          }
        ]
    },
    resolve: {
        extensions: ['.ts', '.js', '.json', ".tsx", ".jsx"]
    },
    output: {
        path: path.resolve(__dirname, "dist"),
        filename: "bundle.js"
    },
    plugins: [new HtmlWebpackPlugin({
        template: "public/index.html",
        hash: true, // This is useful for cache busting
        filename: 'index.html'
    }), new webpack.HotModuleReplacementPlugin()],
    devServer: {
      contentBase: path.resolve(__dirname, './dist'),
      hot: true,
    }
}

```
It should compile everything into a file called bundle.js and put it under the dist directory. But it is instead giving a weird error that doesn't make sense as the App and Navbar and all other components extend Component. I do not know what to do as I updated @types/react and am using the right imports.

**Other relevant information:**
webpack version:  5.33.2
Node.js version:  15.11.0
Operating System: 10.14.6
Additional tools: Babel, Typescript 4.1.3

**Comment by alexander-akait** [comment]
Not related to webpack, it is `typescript` problems
```
TS2786: 'AboutUs' cannot be used as a JSX component.
Its instance type 'AboutUs' is not a valid JSX element.
Type 'AboutUs' is missing the following properties from type 'ElementClass': context, setState, forceUpdate, props, and 2 more.
```

You need fix on your application side. Sorry can't be fixed on webpack side
