### ISSUE TITLE
Extra code found in the production build

### ISSUE THREAD

**Issue by dgeibi** [webpack/webpack#13177]
# Bug report

**What is the current behavior?**

input:  https://github.com/dgeibi/webpack-tree-shaking-bug/blob/master/src/App.js
![image](https://user-images.githubusercontent.com/2224764/115249108-e1a8d980-a15a-11eb-9928-0e94c5571f66.png)

extra `useRef()`  found in the production build

![image](https://user-images.githubusercontent.com/2224764/115245518-97722900-a157-11eb-8b16-fb463edd47d1.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

clone https://github.com/dgeibi/webpack-tree-shaking-bug

```
npm run build
```

output: `dist/main.js`

**What is the expected behavior?**

no extra `useRef()` in the `useEffect`'s callback

**Other relevant information:**
webpack version:  4.46.0 and 5.33.2
Node.js version:  14.16.0
Operating System:  macOS 11.2.3
Additional tools:

**Comment by alexander-akait** [comment]
Why do you think it was dropped? Tree shaking only for `import`/`export`

**Comment by alexander-akait** [comment]
You don't mark this as `pure`, i.e.
```
const x = /*@__PURE__*/ useRef();
```

So we don't know side effects.

**Comment by dgeibi** [comment]
I only add one `useRef()` but produce 2 in the production build
![image](https://user-images.githubusercontent.com/2224764/115248950-bcb46680-a15a-11eb-9c8b-b46938337320.png)

**Comment by alexander-akait** [comment]
Bug on terser side https://github.com/terser/terser

**Comment by dgeibi** [comment]
Thank you

**Comment by dgeibi** [comment]
reported https://github.com/terser/terser/issues/979

**Comment by alexander-akait** [comment]
Thanks, as you can see, `terser` add extra call (https://try.terser.org/)

**Comment by csvan** [comment]
Seems to be closed in Terser, but not sure if released

https://github.com/terser/terser/commit/84c1a314ed43fa3f367159c140175791b5d06b9c

**Comment by alexander-akait** [comment]
Fixed in `5.7.0`, please update deps (https://github.com/terser/terser/commits/master), let's close, for webpack we have PR from dependabot

@csvan thanks for point on this
