### ISSUE TITLE
MainFields shouldn't be used for resolution when resolving dependancies.

### ISSUE THREAD

**Issue by denis-migdal** [webpack/webpack#13170]
# Bug report

**What is the current behavior?**

When using `MainFields: ['main.js', 'index.js']`, dependencies resolution might fail when :

- dependency's main field in package.json points to a directory.
- the directory contains a main.js and an index.js, expecting index.js to be used by default.

See: https://github.com/stdlib-js/stdlib/issues/391

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Use a dependency s.a. @stdlib/stdlib that has main.js and index.js in the same directory
2. import/require this dependency.
3. use this dependency.

**What is the expected behavior?**

When requiring a directory,

1. find the first package.json encountered in the parent folders of the required/imported directory.
2. if there is no webpack.config.js in the package.json folder (i.e. is a node dependency).
    - ignore mainFields for the resolution of the required/imported file as it changes the expected behavior of node ;
    - ignore mainFields for the resolution of all files directly or indirectly imported by the previous required/imported file.

OR

1. find the first package.json encountered in the parent folders of the required/imported directory.
2. if there is no webpack.config.js in the package.json folder (i.e. is a node dependency).
    - add index.js as the first element of mainFields for the resolution of the required/imported file to match node's expected behavior
    - add index.js as the first element of mainFields for the resolution of all files directly or indirectly imported by the previous required/imported file.

**Other relevant information:**
webpack version:  4.41.4
Node.js version: v15.12.0
Additional tools: @stdlib/stdlib 0.0.93

**Comment by sokra** [comment]
You probably mean `mainFiles: ['main.js', 'index.js']`.

Anyway I think webpack is behaving as expected. If you reconfigure it to prefer `main.js` over `index.js` it will do that, and that might break some packages that have a `main.js`.

You can swap the order to `mainFiles: ['index.js', 'main.js']` or best don't change that at all and use the usual renaming conventions...

**Comment by denis-migdal** [comment]
> You probably mean `mainFiles: ['main.js', 'index.js']`.

Indeed, my bad.

> You can swap the order to `mainFiles: ['index.js', 'main.js']` or best don't change that at all and use the usual renaming conventions...

I already swapped them and it solved the bug I was encountering. However, I think this is a problematic behavior.

> Anyway I think webpack is behaving as expected. If you reconfigure it to prefer `main.js` over `index.js` it will do that, and that might break some packages that have a `main.js`.

I think it shouldn't for several reasons :

- to respect encapsulation principles, developpers should be agnostic of the packages content ;
- there is no reasons to prefer main.js over index.js inside a node package as it will break it ;
- finding the origin of such errors can be time consuming, I think it should be great to prevent it.

After, other solutions may be possible :

- add a warning when index.js is not the first value of mainFiles ;
- add an option to exclude paths (e.g. by default node_modules) on which mainFiles is used/applied.

Note that `resolve.extensions` may lead to similar issues.

**Comment by denis-migdal** [comment]
Maybe I should provide an hypothetical use cases to why such behavior is an issue.

1) A developer is asked to rewrite an application from JavaScript to TypeScript. To do so, he modifies files one by one, adding an `index.ts` next to `index.js`. Then he ask webpack to prefer `.ts` over `.js` files in order to test the `.ts` files he wrote.
He keep the `index.js` file when testing the newly written `.ts` file in order to check it if there is any issue.

That seems to be a reasonable use case.

But if any of the dependencies he uses has, for whatever reason, `index.ts` files next to `index.js` files, but is expecting the `index.js` file to be choosen, it will break.

2) A project has several webpack configuration, e.g. one to build html files, and one to build js files. A directory might contains `index.html` files that will be used for the first configuration, and `index.js` files for the second configuration. Therefore, the developer modified the `mainFiles` in order to fetch `index.html` over `index.js` when requiring a directory for the first configuration.

However, if, for any reason a dependency he uses as an `index.html` file next to a `index.js` file, it might break.
