### ISSUE TITLE
Different behaviour when requiring in webpack and directly in node

### ISSUE THREAD

**Issue by schovi** [webpack/webpack#1317]
I am having problem with momentjs library https://github.com/moment/moment/
When installing npm package and require it `require('moment')` it requires all locales (lot of modules). But in node it requires only main library.
In webpack log it appears 

    [239] ./~/moment/moment.js 104 kB {0} {1} [built]
    [240] ./~/moment/locale ^\.\/.*$ 2.06 kB {0} {1} [optional] [built]
    [241] ./~/moment/locale/af.js 2.58 kB {0} {1} [optional] [built]
    [242] ./~/moment/locale/ar.js 4.52 kB {0} {1} [optional] [built]
    .... a lot more :)

I tried to ask in momentjs issues: https://github.com/moment/moment/issues/2517
I was thinking that [optional] modules will be skipped when build production javascript, but they are included. Any suggestions?

**Comment by sokra** [comment]
it doesn't require all locales. it just include all locales in the bundle. The runtime behaviour is equal to node.js.

moment.js has a function that allows to load a local by string parameter. This means you can potentially load all locals and they need to be included into the bundle to be available.

With a bit configuration you can change this behaviour to your needs. search on stackoverflow.

**Comment by schovi** [comment]
@sokra thanks for answer. But I am not sure if I understand "it just include all locales in the bundle".
For me it means that all locale files was required and will be in my application build. Right?

**Comment by SimenB** [comment]
They will be in the bundle yes, but not executed. To be able to set language moment's way (just a string in runtime), every language has to be bundled.
Top google result: http://stackoverflow.com/a/25426019/1850276
