### ISSUE TITLE
Webpack 5 ModeFederation error when shared package version is not in semver

### ISSUE THREAD

**Issue by vovkvlad** [webpack/webpack#13176]
# Bug report

**What is the current behavior?**
One of our packages has version 'dev' set in package.json as it is internal not released yet package.
```json
....
"dependencies": {
    "{PACKAGE_NAME}": "dev",
}
....
```
When I try to configure ModeFederationPlugin for our main app I configure shared modules as follows:
```js
const packageJson = require('../package.json');

const packageName = packageJson.name;
const packageDeps = packageJson.dependencies;

new ModuleFederationPlugin({
   ....
    shared: {
      ...packageDeps,
      react: {
        singleton: true,
        eager: true,
        requiredVersion: packageDeps.react,
      },
      'react-dom': {
        singleton: true,
        eager: true,
        requiredVersion: packageDeps['react-dom'],
      },
    },
    ....
  }),
```

When I run webpack it gives me next error:
```
ERROR in resolving fallback for shared module ($PACKAGE_NAME}
Module not found: Error: Can't resolve 'dev' in '{PATH_TO_FILE_USING_PACKAGE}'
```

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Add package with version different from semantic versioning standard to dependencies of the project
2. Try to add `ModuleFederationPlugin` to the webpack config of the app with the following config:
```js
const packageJson = require('../package.json');

const packageName = packageJson.name;
const packageDeps = packageJson.dependencies;

new ModuleFederationPlugin({
    name: packageName,
    remotes: {},
    shared: {
      ...packageDeps,
      angular: {
        singleton: true,
        eager: true,
        requiredVersion: packageDeps.angular,
      },
      react: {
        singleton: true,
        eager: true,
        requiredVersion: packageDeps.react,
      },
      'react-dom': {
        singleton: true,
        eager: true,
        requiredVersion: packageDeps['react-dom'],
      },
    },
  }),
```
3. Run webpack and see the errors in the console

**What is the expected behavior?**
I assume that if webpack can resolve node_modules with non-semantic versioning then `ConsumeSharedPlugin` should also be able to

If any additional info is needed for me, please let me know

**Other relevant information:**
webpack version:  5.24.4
Node.js version: v14.15.0
Operating System: macOS Catalina Version 10.15.7
Additional tools:

**Comment by alexander-akait** [comment]
You need using `file` protocol in this case https://stackoverflow.com/questions/14381898/local-dependency-in-package-json

**Comment by vovkvlad** [comment]
but it's not local, the package itself is stored in our npm registry and can be downloaded from there. 
It's just version that's specified as `dev` for some reason...
If I change the version in `package.json` to `0.0.1` or even `0.0.1-alpha` the build will succeed even though there is no such version neither in `node_modules` nor in npm regstry

**Comment by alexander-akait** [comment]
But `dev` is not valid... So we don't handle it, why do not use valid semantic version?

**Comment by vovkvlad** [comment]
We will work on fixing the version.  But it works fine with standard webpack build, as long as you don't configure ModuleFederation. I wonder where this constraint comes from in module federation?

**Comment by alexander-akait** [comment]
We have logic  to detect `singleton` problems with multiple versions, so each package should have valid (parsable by semver) version

**Comment by vovkvlad** [comment]
Small update:
I wasn't aware of it, as I don't own the mentioned package. But it turns out that `dev`  is not the version but an npm-dist tag, which points to a specific publish version. It seems to be valid version for npm:
https://docs.npmjs.com/cli/v7/configuring-npm/package-json#dependencies

**Comment by alexander-akait** [comment]
Yep, unfortunately we do not support this, limitation

**Comment by tgelu** [comment]
A note that I have a similar issue with not-so-common semantic versions. I have a package depending on react `">=16.8.0 < 18"` but when things are resolved at runtime I get a warning that the react singleton version isn't satisfied: `>=16.8.0 * ^18` - notice the `*` and `^` which seem to be added when the warning shows up. It seems to me like npm's parsing of these versions isn't the same as webpack/module federation plugin which appears to change it or parse it wrongly somehow.

According to [the semantic version parser used by npm](https://npm.runkit.com/semver) it seems like  `">=16.8.0 < 18"` is a valid version range.

I would venture to guess that the package linked above and this [semver util in webpack](https://github.com/webpack/webpack/blob/main/lib/util/semver.js) differ, but I do not know enough about it to be sure.

**Comment by tgelu** [comment]
I think you're right that it was fixed - I just added a failing test in `5.68.0` and seems to not fail in `5.69.0` :) will try it out in our real app and get back

**Comment by tgelu** [comment]
Seems to be working well, thanks for pointing it out! 👍

**Comment by alexander-akait** [comment]
Yeah, thank you for investigation, I want to close this issue, because fixed, anyway if somebody face with this - feedback welcome
