### ISSUE TITLE
libraryTarget:umd cause "__webpack_exports__ is not defined"

### ISSUE THREAD

**Issue by buhichan** [webpack/webpack#13185]
# Bug report

**What is the current behavior?**

library target: umd cause "__webpack_exports__ is not defined" error

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/buhichan/webpack_exports-is-undefined/tree/master

**What is the expected behavior?**

it should not generate main.js with reference error. This error does not happen with webpack 5.22.

In https://github.com/webpack/webpack/blob/master/lib/javascript/JavascriptModulesPlugin.js, the code is like

```
renderMain(...){
     ...
     if(inlineModule){
          ...
          generate var __webpack_exports__ = {};
          ...
     }else{
          ...
     }
     if(someConfig){
          generate return __webpack_exports__;
     }
     ...
}

```

Maybe `generate return __webpack_exports__` should be put into if(inlineModule){ ... }

**Other relevant information:**
webpack version:  5.34
Node.js version: 14
Operating System: Macos
Additional tools: webpack-dev-server: 4.0.0-beta.2

**Comment by alexander-akait** [comment]
Duplicate https://github.com/webpack/webpack/issues/13165 and here fix https://github.com/webpack/webpack/pull/13175

**Comment by buhichan** [comment]
thanks for reply, that commit fix my problem
