### ISSUE TITLE
webpack.definePlugin definitions and garbage collection leak

### ISSUE THREAD

**Issue by tugayilik** [webpack/webpack#13182]
# Bug report

**What is the current behavior?**
When the definitions by `webpack.definePlugin` are being used in any module, It's not accessing the definitions from the reference but importing and duplicating them for each module.  Also, increasing garbage collection load cumulatively according to definition size. (Assume that, a big json file used for global definition)

**If the current behavior is a bug, please provide the steps to reproduce.**
I created a minimum reproducible repo. You can check the output -`main.js`- and it's content. Clearly visible that, the settings object is duplicated.

https://github.com/tugayilik/webpack-defineplugin

**What is the expected behavior?**
Not to duplicate values for each module and decreasing the garbage collection load.

**Other relevant information:**
webpack version:  5.31.2
Node.js version: 15.13.0
Operating System: macOS
Additional tools: -

**Comment by sokra** [comment]
That's working as intended. The DefinePlugin inlines source code into modules. If you want to have a shared settings object, use a module and import it everywhere (or use the ProvidePlugin).

**Comment by tugayilik** [comment]
I see. But what is the plus of this intend, why it inlines instead of referencing it like other modules?
