### ISSUE TITLE
Is there a way to get a list of files that weren't compiled into an entrypoint's bundle?

### ISSUE THREAD

**Issue by trusktr** [webpack/webpack#1318]
For example, if I tell webpack to compile an entry point, that entry point will require other files, etc. Is there a way for Webpack to give me a list of unused files, files that weren't require/imported into the bundle?

**Comment by sokra** [comment]
Nope, but feel free to write a plugin.

**Comment by trusktr** [comment]
I found a solution: the compiler `stats.toJson()` object contains a list of modules that were compiled. I have the list of all the files, so I can just see which files aren't listed in the `modules` array, and those are the files that weren't used.
