### ISSUE TITLE
Progress is logged to STDErr which is causing lots of inconvenience

### ISSUE THREAD

**Issue by ThaDaVos** [webpack/webpack#13190]
This is a new issue referring to an older closed one - that one was closed for missing the template and since then has never been opened so probably lost from the issue radar: https://github.com/webpack/webpack/issues/3520

# Bug report

**What is the current behavior?**
Progress is considered unconventional output so it's logged to stdErr - which is inconvenient to say the least when the progress has to be parsed by other programs, for example dotNet core

**If the current behavior is a bug, please provide the steps to reproduce.**
Steps are simple -> get any project which contains Webpack and use it to build with `--progress` enabled
and directing the output of StdOut and StdErr to a separate file each. You will notice the progress ending up in the StdErr file while you would expect it in the StdOut file...

**What is the expected behavior?**
The progress being logged into the StdOut file or at least through the StdOut pipe...

**Other relevant information:**
webpack version:  N/A
Node.js version: N/A
Operating System: N/a
Additional tools:
See: https://github.com/webpack/webpack/issues/3520

**Comment by sokra** [comment]
You can configure that: https://webpack.js.org/configuration/other-options/#stream

**Comment by alexander-akait** [comment]
Answered
