### ISSUE TITLE
How to prevent Webpack from changing "this" to "undefined"?

### ISSUE THREAD

**Issue by trusktr** [webpack/webpack#1319]
I need to compile Webpack bundles, but I need to run them in such a way that the code needs to be able to access `this` from outside the scope where the code runs. 

The problem is that Webpack adds `"use strict";` to the module wrapper, and changes `this` to `undefined`.

I want to run code like the following inside the module:

```js
someThing = "someThing";
```

or 

```js
this.someThing = "someThing";
```

without the use of `var` or `let` so that the variable `someThing` gets added onto the `this` from the outer scope where the bundle is placed. Webpack changes the previous example to

```js
undefined.someThing = "someThing";
```

**Comment by sokra** [comment]
webpack doesn't add `use strict`. Propably a loader is doing this (babel-loader?).

**Comment by trusktr** [comment]
@sokra Aah, that's probably it.

**Comment by skip405** [comment]
@trusktr, did you eventually find a workaround? Besides not using `babel-loader` :)

**Comment by SimenB** [comment]
https://babeljs.io/docs/advanced/transformers/other/strict/#blacklisting

**Comment by trusktr** [comment]
@skip405 I just embraced it and did something else. I manually inserted some symbols into the script in my case, after webpack was done compiling.
