### ISSUE TITLE
stats.children = true not showing warnings

### ISSUE THREAD

**Issue by JonathanLorimer** [webpack/webpack#13197]
I have this in my webpack config
```js
    stats: {
      children: true,
    }
```
but continue to see this warning:
```
$ webpack serve --hot

ℹ ｢wdm｣: Compiling...
⚠ ｢wdm｣: 397 assets
3912 modules
1 WARNING in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)
webpack 5.35.0 compiled with 1 warning in 3018 ms
ℹ ｢wdm｣: Compiled with warnings.
No issues found.
```

versions:
```
    "webpack": "^5.35.0",
    "webpack-cli": "^4.6.0",
    "webpack-dev-server": "^3.11.2",
```

**Comment by alexander-akait** [comment]
Please provide example and how you run webpack?

**Comment by JonathanLorimer** [comment]
I use `yarn` to run webpack, but tried with `npx` and got the same result. Unfortunately it is difficult to provide an example since the warnings are sporadic (occur when saving some ts, js, css files, but not all) and I can't get the warnings to print out, so I can't identify what in the codebase is causing the warning.

**Comment by alexander-akait** [comment]
Unfortunately, then I can hardly help you and probably nobody can, sorry. Do you try `--stats-children`?

**Comment by JonathanLorimer** [comment]
I see, I don't expect you (or any of the maintainers of webpack) to resolve the warnings. I was just wondering if there might be a reason that `children: true` or `npx webpack server --stats-children` isn't actually printing out the warnings.

it is a bit frustrating to see this in webpacks output:
```
1 WARNING in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)
```
when both are enabled.

**Comment by alexander-akait** [comment]
Can you run `webpack serve --hot -stats-children`?

**Comment by JonathanLorimer** [comment]
same result unfortunately
```
 npx webpack serve --hot --stats-children
ℹ ｢wds｣: Project is running at http://localhost:3001/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /home/jonathanl/Mercury/mercury-web/public
ℹ ｢wds｣: 404s will fallback to /index.html
Warning: The 'no-floating-promises' rule requires type information.
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
ℹ ｢wdm｣: 395 assets
3912 modules
webpack 5.35.0 compiled successfully in 34088 ms
ℹ ｢wdm｣: Compiled successfully.
Issues checking in progress...
No issues found.
ℹ ｢wdm｣: Compiling...
⚠ ｢wdm｣: 397 assets
3912 modules
1 WARNING in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)
webpack 5.35.0 compiled with 1 warning in 3061 ms
ℹ ｢wdm｣: Compiled with warnings.
No issues found.
```

**Comment by alexander-akait** [comment]
> Warning: The 'no-floating-promises' rule requires type information.

Here warning

**Comment by alexander-akait** [comment]
What is `stats` value in `webpack.config.js`?

**Comment by JonathanLorimer** [comment]
```
    stats: {
      children: true,
      warningsFilter: [
        /\-\-underline\-color/,
      ]
    },
```

Are you sure these warnings are the same? They don't seem to be coming from a child process, and there are 2 of them, so I would expect it to show 2 child warnings, not 1.

**Comment by alexander-akait** [comment]
`warningsFilter` is deprecated in favor https://webpack.js.org/configuration/other-options/#ignorewarnings

> 1 WARNING in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)

You have only one warning and we show this warning

**Comment by JonathanLorimer** [comment]
That fixed it! It was the `warningsFilter`. I suppose that, because there was an issue with `stats` it wasn't being configured properly and therefore wasn't displaying the child warnings.

**Comment by alexander-akait** [comment]
So the problem is solved?

**Comment by JonathanLorimer** [comment]
Yes, thank you for your help!

**Comment by alexander-akait** [comment]
:star: Feel free to feedback, you can always ask questions here https://github.com/webpack/webpack/discussions
