### ISSUE TITLE
WARNING in DefinePlugin related to #12896

### ISSUE THREAD

**Issue by syuta-sugawara** [webpack/webpack#13194]
# Bug report

**What is the current behavior?**

when build process is executed with [mode](https://webpack.js.org/configuration/mode/) and DefinePlugin, mode's value  conflict with DefinePlugin's value, even though the same value is used.

**If the current behavior is a bug, please provide the steps to reproduce.**
ex
set mode and  webpack.DefinePlugin
```js
module.exports = {
  //...
  mode: 'development',
  plugins: [
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': 'development', 
    }),
  ],
};
```

**What is the expected behavior?**

Conflicting warning doesn't occur.
Maybe modify system to detect changing values in DefinePlugin is good.
related to these
https://github.com/webpack/webpack/blob/e05935f8969d873a20762767d348256e5ad8fb46/lib/DefinePlugin.js#L559-L584

**Other relevant information:**
webpack version:  5.34.0
Node.js version: v14.15.3
Operating System: macOS Catalina
Additional tools:

**Comment by sokra** [comment]
You have indeed conflicting values.

`"development"` (the default, development as string) and `development` (your value, development as identifier, incorrect)

**Comment by alexander-akait** [comment]
Here example in docs https://webpack.js.org/plugins/define-plugin/#usage, you need use `JSON.stringify('development')`
