### ISSUE TITLE
Package ES6 only works on first load

### ISSUE THREAD

**Issue by gameloch** [webpack/webpack#13192]
I built a package based on CSS3 / CSS4, HTML5 and its APIs, the package contains 101 files and uses promises to differentiate the files and measure their priority, at the end of a promise, you may or may not start another one as needed, in the following format:

```
import(/* webpackMode: "lazy-once" */ /* webpackChunkName: "exemple1" */ /* webpackPrefetch: true */ /* webpackPreload: true */ "../module1").then(exemple1 => {
import(/* webpackMode: "lazy-once" */ /* webpackChunkName: "exemple2" */ /* webpackPrefetch: true */ /* webpackPreload: true */ "../module2").then(exemple2 => {
//code execution or do another import
});
});
```
The modules look like this:
```
export default function Exemple1() {	
//code
};
new Exemple1()
```
The package works perfectly without the Webpack, with the Webpack, it only works in the first access, in the later accesses it works partially, it was verified that all the modules appear in the source map, but only some are executed, although all of them are really necessary, the Total non-minimized packet size is 411 kb or 652 KB on disk, no errors have been logged on the console. See the configuration files: (no dependencies required)

Package.json - Name, description, version, main file and test file have been omitted for security reasons.
```
{
   "private": true,
   "mode": "production",
   "main": "....",
   "name": "....",
   "description": "...",
    "version": "...",
    "scripts": {
        "test": "....",
        "dev": "npm run development",
        "development": "npx webpack",
        "watch": "npm watch",
        "prod": "npm run production",
        "production": "npx webpack"
    },
    "devDependencies": {
        "webpack": "^5.35.0",
        "webpack-cli": "^4.6.0"
    },
    "dependencies": {
        "es6-promise": "^4.2.8"
    }
}
```
Webpack.config.js

```
const path = require('path');
var webpack = require('webpack');

module.exports = {
mode: 'production',
cache: false,
devtool: 'source-map'
}
```

A reduction in the number of pieces (files generated) was attempted with the code below, but it did not solve the problem:

```
module.exports = {
[...]
entry: './main.js',
output: {
    path: path.resolve(__dirname, './dist'),
    publicPath: 'js/',
    filename: 'main.js',  library: 'packgeexemple',
    sourceMapFilename: '[name].[contenthash].map',
    chunkFilename: '[name].[contenthash].js',	
    libraryTarget: 'window',
    libraryExport: 'default',
    clean: true,  
},
optimization: {
     splitChunks: {
       cacheGroups: {
         vendor: {
           test: /[\\/]node_modules[\\/]/,
           name: 'vendors',
           chunks: 'all',
         },
       },
     },
	 },
  plugins: [
    new webpack.optimize.LimitChunkCountPlugin({
      maxChunks: 5,
    }),
  ]
}
```
How can this be resolved?

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

I will reopen then you fix it, respect time of other developers, thanks

**Comment by alexander-akait** [comment]
Please go to https://github.com/webpack/webpack/issues/new/choose and chose `Bug report` and use the issue template

**Comment by gameloch** [comment]
@alexander-akait alexander-akait
It's right now? https://github.com/webpack/webpack/issues/13198
