### ISSUE TITLE
Partial package loading | Problem with dynamic imports / promises ES6 

### ISSUE THREAD

**Issue by gameloch** [webpack/webpack#13198]
# Bug report

**What is the current behavior?**
The modules are executed only once, in the first access to the web application, apart from the second access, only a portion of the modules are actually executed, they appear in the source-map, apparently they were loaded, but the code is not executed.

**If the current behavior is a bug, please provide the steps to reproduce.**
The bug can be reproduced using nested promises (one inside the other) ES6, with import (), as indicated in the documentation. 

```
import(/* webpackMode: "lazy-once" */ /* webpackChunkName: "exemple1" */ /* webpackPrefetch: true */ /* webpackPreload: true */ "../module1").then(exemple1 => {
import(/* webpackMode: "lazy-once" */ /* webpackChunkName: "exemple2" */ /* webpackPrefetch: true */ /* webpackPreload: true */ "../module2").then(exemple2 => {
//code execution or do another import
});
});
```

Other codes here: https://github.com/webpack/webpack/issues/13192 

**What is the expected behavior?**
The webpack must load and execute all the requested modules, all are necessary, if 100 modules are requested it must load all 100 modules and not 50, 75, 80 and etc., as it does, the webpack partially executes the package, being that must execute the entire package, at all times, as the package builds pages based on html tags, if the module is not executed, the user will see a blank page, the webpack must not interfere or act as a service worker.

**Other relevant information:**
webpack version:  5.35.0
Node.js version: 6.14.11
Operating System: Windows 10 x64
Additional tools: No dependencies

**Comment by alexander-akait** [comment]
> If the current behavior is a bug, please provide the steps to reproduce.

Please provide steps - configurations/files/code (no need provide full code, just example for error)/how you run it/is it dev server?

**Comment by gameloch** [comment]
@alexander-akait 

But the code is on that other ticket...

1. Create a package https://webpack.js.org/guides/getting-started/ 
2. Install and import the polyfill in the main file: ` npm i es6-promise` import like this:` import 'es6-promise';`
3. In an html file, place these example tags:
```
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

<div class="row">
<div class="col"><a1> </a1></div>
<div class="col"><a2> </a2></div>
<div class="col"><a3> </a3></div>
<div class="col"><a4> </a4></div>
<div class="col"><a5> </a5></div>
</div>
```
4. Now in the package, create 5 js files, 
5. Call them in the main file, like this
```
import(/* webpackMode: "lazy-once" */ /* webpackChunkName: "exemple1" */ /* webpackPrefetch: true */ /* webpackPreload: true */ "../module1").then(exemple1 => {
import(/* webpackMode: "lazy-once" */ /* webpackChunkName: "exemple2" */ /* webpackPrefetch: true */ /* webpackPreload: true */ "../module2").then(exemple2 => {
import(/* webpackMode: "lazy-once" */ /* webpackChunkName: "exemple3" */ /* webpackPrefetch: true */ /* webpackPreload: true */ "../module3").then(exemple3 => {
import(/* webpackMode: "lazy-once" */ /* webpackChunkName: "exemple4" */ /* webpackPrefetch: true */ /* webpackPreload: true */ "../module4").then(exemple4 => {
import(/* webpackMode: "lazy-once" */ /* webpackChunkName: "exemple55" */ /* webpackPrefetch: true */ /* webpackPreload: true */ "../module5").then(exemple5 => {
//code or null
});
});
});
});
});
```

6. in each one you will use something to make insertions in the page, try this in each one modifying the querySelector as necessary:
```
export default function Module1() {

document.querySelector('a1').innerHTML = ' <div class="card text-white bg-primary mb-3" style="max-width: 18rem;"> <div class="card-header">Header</div> <div class="card-body"> <h5 class="card-title">Primary card title</h5> <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> </div> </div> <div class="card text-white bg-secondary mb-3" style="max-width: 18rem;"> <div class="card-header">Header</div> <div class="card-body"> <h5 class="card-title">Secondary card title</h5> <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> </div> </div> <div class="card text-white bg-success mb-3" style="max-width: 18rem;"> <div class="card-header">Header</div> <div class="card-body"> <h5 class="card-title">Success card title</h5> <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> </div> </div> <div class="card text-white bg-danger mb-3" style="max-width: 18rem;"> <div class="card-header">Header</div> <div class="card-body"> <h5 class="card-title">Danger card title</h5> <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> </div> </div> <div class="card text-dark bg-warning mb-3" style="max-width: 18rem;"> <div class="card-header">Header</div> <div class="card-body"> <h5 class="card-title">Warning card title</h5> <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> </div> </div> <div class="card text-dark bg-info mb-3" style="max-width: 18rem;"> <div class="card-header">Header</div> <div class="card-body"> <h5 class="card-title">Info card title</h5> <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> </div> </div> <div class="card text-dark bg-light mb-3" style="max-width: 18rem;"> <div class="card-header">Header</div> <div class="card-body"> <h5 class="card-title">Light card title</h5> <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> </div> </div> <div class="card text-white bg-dark mb-3" style="max-width: 18rem;"> <div class="card-header">Header</div> <div class="card-body"> <h5 class="card-title">Dark card title</h5> <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> </div> </div>';
};
new Module1()
```
7. run the command: `npx webpack`
8.  Call the package in your html file and open it in the browser, the server is unnecessary, in this case.

Watch it live: https://www.gpgic.com/ 
just open your devtool and click on sources, expand "Mylochi".

**Comment by alexander-akait** [comment]
> `webpackMode` expected 'lazy', 'eager' or 'weak', but received: lazy-once.

Don't use `lazy-once` with non context `import`.

No problems, all works fine as you setup.

Please read again:

> 'lazy-once': Generates a single lazy-loadable chunk that can satisfy all calls to import(). The chunk will be fetched on the first call to import(), and subsequent calls to import() will use the same network response. Note that this only makes sense in the case of a partially dynamic statement, e.g. import(`./locales/${language}.json`), where multiple module paths that can potentially be requested.


> document.querySelector('a1').innerHTML

You are using `a1`, you need set different selector if you want to use `a2`/`a3`/`a4`/`a5`
