### ISSUE TITLE
Uncaught Error: [HMR] Hot Module Replacement is disabled & [WDS] Hot Module Replacement enabled

### ISSUE THREAD

**Issue by tobeyouth** [webpack/webpack#1320]
I use the `react-hot-loader`

There is my config:

    var accountDevConfig = {
      plugins: [
        new ExtractTextPlugin("[name].css"),
           new webpack.DefinePlugin({
           DEV: true
        }),
         new webpack.HotModuleReplacementPlugin(),
         new webpack.NoErrorsPlugin()
       ],
      devtool: 'eval',
      entry: {
      'account_login': [
        'webpack-dev-server/client?http://localhost:3000',
        'webpack/hot/only-dev-server',
        './static_resource/account/login.jsx'
     ],
    output: {
      path: path.join(__dirname,'dest'),
      filename: '[name].js',
      publicPath: '/dest/',
      chunkFilename: '[id].bundel.js'
    },
    module: {
      loaders: [
        { test: /\.css$/, loader: ExtractTextPlugin.extract("style", cssLoader.join('!')) },
        { test: /\.scss$/, loader: ExtractTextPlugin.extract("style", cssLoader.concat('sass').join('!')) },
        {
          test: /\.(woff|woff2|ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
          loader: 'file?name=assets/fonts/[name].[ext]'
        },
        {
          test: /\.js$/,
          exclude: /node_modules/,
          loader: ['react-hot','babel?stage=0']
        },
        {
           test: /\.jsx$/,
           exclude: /node_modules/,
           loaders: ['react-hot','babel?stage=0']
         }
        ]
      }
      }
    }
    
    var accountDevCompiler = webpack(accountDevConfig)
    var accountDevServer = new webpackDevServer(accountDevCompiler, {
      contentBase: path.resolve(__dirname),
      publicPath: accountDevConfig.output.publicPath,
      hot: true,
      historyApiFallback: true,
      stats: { colors: true },
      inline: false,
      headers: { 'Access-Control-Allow-Origin': '*' }
    });

  accountDevServer.listen(3000, 'localhost', function (err, result) {
    if (err) {
      console.log(err);
    }
      console.log('Listening at localhost:3000');
    });

On the page,there console.log is that:

    Uncaught Error: [HMR] Hot Module Replacement is disabled
    [WDS] Hot Module Replacement enabled.

The module don't work

what is wrong with my config?
thx :)

**Comment by sokra** [comment]
`HotModuleReplacementPlugin` is missing.

**Comment by leecade** [comment]
+1

**Comment by rogovdm** [comment]
@sokra  

As far as I can see @tobeyouth has `HotModuleReplacementPlugin` in his code. I have it too and still have the same error.

Do you have any clues?

**Comment by bebraw** [comment]
@tobeyouth Any luck? I go through a [basic setup](http://survivejs.com/webpack_react/developing_with_webpack/) at a chapter of mine.
