### ISSUE TITLE
Loader written in TypeScript not working when in node_modules

### ISSUE THREAD

**Issue by inad9300** [webpack/webpack#13218]
# Bug report

**What is the current behavior?**
Referencing a loader written in TypeScript works just as expected, except when the loader's TypeScript file is inside `node_modules`.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Write a simple loader using TypeScript.
2. Reference that loader from a webpack configuration file and see it working.
3. Move that loader to the `node_modules` directory and change the path in the webpack file to point to the new location.
4. See it fail with `SyntaxError: Cannot use import statement outside a module`, as webpack fails to interpret the file as TypeScript.

**What is the expected behavior?**
TypeScript webpack loaders should work even when placed in a directory named "node_modules", just the same as they work from any other directory.

**Other relevant information:**
webpack version:  5.35.1 / 4.6.0 (CLI)
Node.js version: 14.16.0
Operating System: macOS
Additional tools: ts-loader 9.1.1, ts-node 9.1.1, TypeScript 4.2.4

**Comment by alexander-akait** [comment]
> See it fail with SyntaxError: Cannot use import statement outside a module, as webpack fails to interpret the file as TypeScript.

No related to webpack
