### ISSUE TITLE
webpack whether to support modification before build

### ISSUE THREAD

**Issue by nextdoorUncleLiu** [webpack/webpack#13212]
## Feature request

**What is the expected behavior?**

i want to function，file before build content modification, then output

**What is motivation or use case for adding/changing the behavior?**

because i want to building update jsx or function content, but compilation.hooks.buildModule can get resource, can't get file content update, fs.readFileSync can get content, but not output, hope to provide a function, can build before update, return value is updated content

**How should this be implemented in your opinion?**

only need to add a hook:

```js
// entry example.js
console.log('this init content')

// plugin
compilation.hooks.updateModule.tap('update-plugin', module => {
    const file = fs.readFileSync(module.resource, 'utf-8')
    return `console.log('new module') \n ${file}`
})

// output main.js
console.log('new module')
console.log('this init content')
```

**Are you willing to work on this yourself?**
yes

**Comment by alexander-akait** [comment]
You can create loader for this, it is way how you can modify module code, please read https://webpack.js.org/contribute/writing-a-loader/

**Comment by nextdoorUncleLiu** [comment]
@alexander-akait 
loader it can be realized,but loader is all file build, I want only need file parse ,loader parse need long time

**Comment by alexander-akait** [comment]
> I want only need file parse

What do you mean?

**Comment by nextdoorUncleLiu** [comment]
Suppose I have ten file,but I want two of them to translate
Loader will take ten file content translate, if ast translate it takes a long time; regex not accurate enough
Through hooks it can be accurate get every file, I not need break; I need translate
Sorry I form China, english not good, please

**Comment by alexander-akait** [comment]
You can implement implement plugin using these hooks https://github.com/webpack/webpack/blob/master/lib/javascript/JavascriptParser.js#L149 and change what you need

**Comment by nextdoorUncleLiu** [comment]
ok, thanks

**Comment by nextdoorUncleLiu** [comment]
sorry, i see JavascriptParser word, for example:
**index.js**
```js
const a = new String('123');
```
**plugin.js**
```js
compiler.hooks.compilation.tap('MyPlugin', (compilation, {normalModuleFactory}) => {
      normalModuleFactory.hooks.parser
      .for('javascript/auto')
      .tap(
        'MyPlugin',
        (parser, options) => {
          parser.hooks.evaluate.for('NewExpression').tap('MyPlugin', (expression) => {
            console.log(expression)
            return new BasicEvaluatedExpression()
            .setString('345')
            .setRange(expression.range)
          });
        }
      )
    })
```
why output still `123` not `345`
