### ISSUE TITLE
Question: Name of chunkFiles

### ISSUE THREAD

**Issue by Tylopilus** [webpack/webpack#13231]
Hi,

after I have upgraded from v4 to v5 I can see that my chunfiles have been renamed and now containing their relative path.

e.g. Vendor-chunk-Name
* on v4: vendors~site.js
* on v5: vendors-node_modules_jquery_dist_jquery_js.js

Since I did not make any other configuration my assumption is that this is due to the upgrade of webpack. My build-tools actually rely on the ~ in the name, so is there a way to revert to the old naming?

**Comment by aileak** [comment]
I have a similar problem with name of chunkFiles. In webpack 4, my chunk filenames starting in order from 2, 2.hash.chunk.js etc. In webpack 5 it has random numbers 474.hash.chunk.js, 660.hash.chunk.js. Is it ok?

Webpack config:
`
optimization: {
	splitChunks: {
		chunks: 'all'
	},
}
`
