### ISSUE TITLE
Path tests don't use a normalized path separator causing errors on Windows

### ISSUE THREAD

**Issue by doctorpangloss** [webpack/webpack#13234]
# Bug report

**What is the current behavior?**

Using a test of the form

```
rules: [{
  test: /\/filename.ext$/
}]
```

will fail on node users in the MINGW64 / msys2 / msysgit environment because the path separator is `\`.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Run webpack in a native Windows environment.
2. Observe path separators are \ and not /.
3. Observe this interacts poorly with path testing in Webpack.

**What is the expected behavior?**

Paths might have to be tested twice, once with forward slashes and once with backslashes.

**Other relevant information:**
webpack version:  5.32.0
Node.js version: v16.0.0
Operating System: Windows 10
Additional tools: MSYS2 (i.e. the native bash provided by the Git client for Windows)

**Comment by alexander-akait** [comment]
Duplicate https://github.com/webpack/webpack/issues/2553, you can use `/(?:\/|\\)filename.ext$/`
