### ISSUE TITLE
Support for ECMAScript loader (with "type": "module")

### ISSUE THREAD

**Issue by tschaub** [webpack/webpack#13233]
## Feature request

**What is the expected behavior?**

If a loader is authored as an ECMAScript module (or if the nearest `package.json` has `"type": "module"`), it would be nice if webpack provided the necessary info to `loader-runner` so that the loader could be loaded.

**What is motivation or use case for adding/changing the behavior?**

It looks like `loader-runner` supports loaders authored with ESM (see webpack/loader-runner#40).  I'm assuming that means that webpack will eventually support ESM loaders.  I'm opening this issue to get confirmation on that or to hear if anybody has looked into it.

**How should this be implemented in your opinion?**

If a loader's `package.json` has `"type": "module"`, webpack should set the `loader.type` to `module` for `loader-runner`.

**Are you willing to work on this yourself?**

Sure (with guidance).

**Comment by sokra** [comment]
Yep good idea to continue on that. You need to look into the NormalModuleFactory in webpack. It resolves an array of loaders in some method and creates the argument that is later passed to loader-runner. The resolver will provide you the information from package.json and you need to include that as type for the loader-runner argument.

**Comment by alexander-akait** [comment]
Bump

**Comment by stefanprobst** [comment]
hi, in your comment in https://github.com/webpack/webpack/issues/13233#issuecomment-827459873 did you mean this:

https://github.com/webpack/webpack/compare/main...stefanprobst:fix/pass-package-type-to-loader-runner

**Comment by otakustay** [comment]
@stefanprobst I tested your patch in some of my projects and everything works fine, maybe you are interested in creating a PR for this, desperately waiting for that

**Comment by stefanprobst** [comment]
@otakustay cool, thanks for testing! i opened https://github.com/webpack/webpack/issues/13233#issuecomment-827459873 to get some maintainer feedback!

**Comment by alexander-akait** [comment]
Yeah, we will fix it soon, just need some time
