### ISSUE TITLE
Live Reloading stop working if main file throws exception

### ISSUE THREAD

**Issue by maksimr** [webpack/webpack#13232]
STR:

- install `webpack`, `webpack-cli`, `webpack-dev-server`
- create `src/index.js` with content `foo;`
- run `webpack serve --mode development`

ER: Live reload should work even if main entry point has an error
AR: Exception, stop execution and don't reach code which setup live reload connection

Sample project:
[project.zip](https://github.com/webpack/webpack/files/6378733/project.zip)

https://user-images.githubusercontent.com/616193/116120952-c8f37300-a6c8-11eb-9c6d-6e102021380d.mov

**Comment by alexander-akait** [comment]
Sorry we can't reload page when JS is broken (i.e. runtime code is broken), JS can't be executed, so we don't have ability to reload page in this case, sorry.

**Comment by alexander-akait** [comment]
Anyway some cases was fixed, try `webpack-dev-server@beta-2`

**Comment by alexander-akait** [comment]
Yep, works fine with `"webpack-dev-server": "^4.0.0-beta.2"`, stable release will be soon

**Comment by alexander-akait** [comment]
Let’s close, rc out, stable will be on the next week
