### ISSUE TITLE
[Cache] Variable dependency & loader options

### ISSUE THREAD

**Issue by Tofandel** [webpack/webpack#13249]
## Feature request | Bug

**What is the expected behavior?**
```js
module.exports = {
  mode: 'development',
  entry: './src/index.js',
  cache:  {
    type: 'filesystem',
    buildDependencies: {
      // This makes all dependencies of this file - build dependencies
      config: [__filename],
    },
    variableDependencies: [
      process.env.TEST
    ]
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        use: [
          {
            loader: 'webpack-preprocessor-loader',
            options: {
              params: { a: process.env.TEST },
              debug: false,
            },
          },
        ],
      },
    ],
  },
};
```

Run
```
TEST=1 webpack
TEST=2 webpack
```

The file should have been compiled with TEST=2, instead it is cached with TEST=1 and the cache is not invalidated in the second build resulting in an incorrect result

**What is motivation or use case for adding/changing the behavior?**
~~It is currently not possible to invalidate the cache with value of variables leading to unexpected caching issues when using env variables~~
It is currently possible to write
```js
const hash = require('object-hash');
const options =  {
  params: { a: parseInt(process.env.TEST) },
  debug: false,
};
module.exports = {
  mode: 'development',
  entry: './src/index.js',
  cache:  {
    type: 'filesystem',
    version: hash(options),
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        use: [
          {
            loader: 'webpack-preprocessor-loader',
            options,
          },
        ],
      },
    ],
  },
};
```
But a direct api for it would make things cleaner and smoother

**How should this be implemented in your opinion?**
Just adding an array of variables in `variablesDependencies` to add to calculate the cache hash

I believe the loader api is also in need of a fix here as well, this would avoid the need for this in the first place as the loader could invalidate the cache on it's own.
Currently the loader doesn't invalidate its own cache based on it's options, only based on its file deps: https://webpack.js.org/api/loaders/#thisadddependency
Adding a cache hash based on the options of the loader would solve the initial issue because a loader could then use it's options to create a cache hash and we wouldn't have to cache bust manually

### This should be made a default, changing loader options should always invalidate the cache, I can't think of a use case where changing an option doesn't modify the result, there is even a [warning about it, lost in the doc](https://webpack.js.org/configuration/other-options/#cacheversion)

**Are you willing to work on this yourself?**
yes

**Comment by alexander-akait** [comment]
Using `version` is good solution. Don't forget you need serialize `variableDependencies`, it is not easy as you can think, for example - circular structures, functions, external thins (for example function can loader configuration based on stricture of project). This is why we recommend explicitly specifying dependencies, because only you can know them.

**Comment by alexander-akait** [comment]
But I think better will be allow to use `version: { foo: 'bar' /* etc */ }` as object
