### ISSUE TITLE
Error in all components and layouts: (Module parse failed: Unexpected token (23:62) You may need an appropriate loader to handle this file type) 

### ISSUE THREAD

**Issue by kartikaaekap** [webpack/webpack#13248]
# Bug report

Hello, I've tried to make a PWA using NuxtJs. When I tried to build them, I got many error, for example like my following picture :
![image](https://user-images.githubusercontent.com/51069408/116341367-ffd1a200-a80a-11eb-8d6c-03656b8a7455.png)

**What is the current behavior?**
This is my babel plugins configuration :
![image](https://user-images.githubusercontent.com/51069408/116341459-2a235f80-a80b-11eb-831f-dae8f9dbb0ab.png)

I've realized that the error was occured in all components and layouts I made. This is the structure of my project :
![image](https://user-images.githubusercontent.com/51069408/116341715-98682200-a80b-11eb-9e42-16dcb87f2baf.png)

I really need your help, and if you need additional information please kindly to ask me. Thank you :D

**Other relevant information:**
"@nuxt/webpack": "2.15.2"
"nuxt": "^2.14.12",
"@nuxtjs/pwa": "^3.3.5",
Node.js version:  v14.15.5
Operating System: Windows

**Comment by alexander-akait** [comment]
Please open an issue in `NuxtJs` repo, loader in Nuxt generate broken es code, sorry, can't be fixed here
