### ISSUE TITLE
Cannot use keyword 'await' outside an async function

### ISSUE THREAD

**Issue by pbadenski** [webpack/webpack#13240]
# Bug report

**What is the current behavior?**

```
ERROR in ./app/src/ui/charts/export/png.ts 190:11
Module parse failed: Cannot use keyword 'await' outside an async function (190:11)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   });
|   toBlob = async () => {
>     return await this.toCanvas().then(canvasToBlob);
|   };
| }
```

**If the current behavior is a bug, please provide the steps to reproduce.**

I believe it's an issue with a class property which is an async function. Webpack is not able to handle the case below:
```
class A {
  m = async () => {
    return await Promise.resolve();
  };
}
```

**What is the expected behavior?**

I believe webpack should be able to handle this use case.

**Other relevant information:**
webpack version:  5.36.0
Node.js version: 15.11.0
Operating System:  MacOS 10.15.7

**Comment by sokra** [comment]
Sounds like an acorn bug related to class fields...

**Comment by pbadenski** [comment]
Slightly unrelated, and maybe it's another ticket - it would be helpful if these type of errors mentioned acorn. I don't deal with these type of problems very often and each time it takes me a few hours to rediscover the information. This IMHO would be very helpful improvement for example:
```
[acorn@8.2.1] Module parse failed: Cannot use keyword 'await' outside an async function (190:11)
````

**Comment by alexander-akait** [comment]
Yep acorn bug, reported https://github.com/acornjs/acorn/issues/1030, I think we can close here, we can't fix it here

**Comment by alexander-akait** [comment]
Fixed https://github.com/acornjs/acorn/issues/1030, please update deps

**Comment by pbadenski** [comment]
Awesome turnaround time - thank you!
