### ISSUE TITLE
Inconsistency with TypeScript in Module Resolution with Fully-Specified ESM Imports

### ISSUE THREAD

**Issue by Josehower** [webpack/webpack#13252]
# Bug report

**What is the current behavior?**

When using extention .js as part of an import (fully-specified ESM import), webpack fails to create a bundle if the file imported have extention .tsx

This shouldnt be like this based on the comment of [RyanCavanaugh](https://github.com/RyanCavanaugh)
in this issue https://github.com/microsoft/TypeScript/issues/41887#issuecomment-741968855

> "TypeScript doesn't modify JavaScript code you write, the import path you write should be the one you want to appear in the output .js file"

**If the current behavior is a bug, please provide the steps to reproduce.**

I created a repo showing this unexpected behavior
this repo was tested with both `ts-loader` and `babel-loader`

https://github.com/Josehower/webpack-babel-test

1. clone the repo and install dependencies
2. use command `$yarn start`

![image](https://user-images.githubusercontent.com/61600906/116395964-0f5de480-a825-11eb-8915-8fcfbf05d1f6.png)
```js
import { test } from './test.js';

console.log('Hello Webpack Project.');
test();
```

```sh
jose fernando hower@DESKTOP-FHTIMFT MINGW64 /D/upleveled-softwork/webpack-test (main)
$ yarn start
yarn run v1.22.5
$ webpack serve --config ./webpack.config.js --mode development
i ｢wds｣: Project is running at http://localhost:8080/
i ｢wds｣: webpack output is served from /
i ｢wds｣: Content not from webpack is served from D:\upleveled-softwork\webpack-test\dist
× ｢wdm｣: asset bundle.js 367 KiB [emitted] (name: main)
runtime modules 706 bytes 4 modules
cacheable modules 336 KiB
  modules by path ./node_modules/webpack-dev-server/ 21.2 KiB
    modules by path ./node_modules/webpack-dev-server/client/ 20.9 KiB 10 modules
    modules by path ./node_modules/webpack-dev-server/node_modules/ 296 bytes 2 modules
  modules by path ./node_modules/html-entities/lib/*.js 61 KiB 5 modules
  modules by path ./node_modules/querystring/*.js 4.51 KiB 3 modules
  modules by path ./node_modules/webpack/hot/ 1.42 KiB
    ./node_modules/webpack/hot/emitter.js 75 bytes [built] [code generated]
    ./node_modules/webpack/hot/log.js 1.34 KiB [built] [code generated]
  modules by path ./node_modules/url/*.js 23.1 KiB
    ./node_modules/url/url.js 22.8 KiB [built] [code generated]
    ./node_modules/url/util.js 314 bytes [built] [code generated]
./node_modules/webpack/hot/ sync nonrecursive ^\.\/log$ 170 bytes [built] [code generated]

ERROR in ./src/index.tsx 1:0-33
Module not found: Error: Can't resolve './test.js' in 'D:\upleveled-softwork\webpack-test\src'
resolve './test.js' in 'D:\upleveled-softwork\webpack-test\src'
  using description file: D:\upleveled-softwork\webpack-test\package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: D:\upleveled-softwork\webpack-test\package.json (relative path: ./src/test.js)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        D:\upleveled-softwork\webpack-test\src\test.js doesn't exist
      *
        Field 'browser' doesn't contain a valid alias configuration
        D:\upleveled-softwork\webpack-test\src\test.js* doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        D:\upleveled-softwork\webpack-test\src\test.js.js doesn't exist
      .ts
        Field 'browser' doesn't contain a valid alias configuration
        D:\upleveled-softwork\webpack-test\src\test.js.ts doesn't exist
      .tsx
        Field 'browser' doesn't contain a valid alias configuration
        D:\upleveled-softwork\webpack-test\src\test.js.tsx doesn't exist
      as directory
        D:\upleveled-softwork\webpack-test\src\test.js doesn't exist

webpack 5.36.0 compiled with 1 error in 2410 ms
i ｢wdm｣: Failed to compile.
```

3. use command `$yarn tsc --noEmit`
```sh
jose fernando hower@DESKTOP-FHTIMFT MINGW64 /D/upleveled-softwork/webpack-test (main)
$ yarn tsc --noEmit
yarn run v1.22.5
$ D:\upleveled-softwork\webpack-test\node_modules\.bin\tsc --noEmit
✨  Done in 1.49s.
```
4. 
![image](https://user-images.githubusercontent.com/61600906/116396321-872c0f00-a825-11eb-9755-8eaae9688d32.png)

**What is the expected behavior?**

- In the example repo `yarn start` should succesfully create a bundle.

- Webpack should be able to recognize the files imported and create a bundle even if the import statements with the extention .js point files that have the extention .tsx

**Other relevant information:**

```sh
OS: Windows 10 10.0.19041
CPU: (4) x64 Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
Binaries:
Node: 16.0.0 - ~\AppData\Local\Temp\yarn--1619542324765-0.4257021548777624\node.CMD
Yarn: 1.22.5 - ~\AppData\Local\Temp\yarn--1619542324765-0.4257021548777624\yarn.CMD
npm: 7.10.0 - C:\Program Files\nodejs\npm.CMD
Browsers:
Chrome: 90.0.4430.93
Edge: Spartan (44.19041.906.0), Chromium (90.0.818.46)
```

**Comment by karlhorky** [comment]
Alternately, in case @sokra or others decide that parity with TypeScript's module resolution algorithm with fully-specified ES Modules imports is not a goal of webpack, this bug / feature request may actually be better placed in the two loaders that were used to consume TypeScript:

- [`babel-loader`](https://github.com/babel/babel-loader) (cc @JLHwung)
- [`ts-loader`](https://github.com/TypeStrong/ts-node) (cc @cspotcode @blakeembrey)

**Comment by karlhorky** [comment]
Hmm... as a workaround in the meantime, would it be possible to create a map of `./file.js` to `./file` module file paths using something like [the `NormalModuleReplacementPlugin`](https://webpack.js.org/plugins/normal-module-replacement-plugin/)? 🤔

**Comment by alexander-akait** [comment]
What is problem with webpack here? If you use `import` you need to write extension, or disable `fully-specified ESM import`, don't know what we should fix here...

**Comment by karlhorky** [comment]
The problem is that using the fully-specified `.js` extension fails when using TypeScript `.ts` files (they are not resolved like TypeScript and `tsc` do)

With TypeScript and `tsc`, the following works:

```
// index.ts
import {abc} from './abc.js';
```

```
// abc.ts
export const abc = 1;
```

See @RyanCavanaugh's comment here: https://github.com/microsoft/TypeScript/issues/41887#issuecomment-741968855

**Comment by alexander-akait** [comment]
I think related https://github.com/TypeStrong/ts-loader/issues/1198

**Comment by karlhorky** [comment]
Maybe somewhat related, although it seems this person is describing the opposite: they want to write node-style specifiers (without the extension) and have them resolved to the `.js` files (ignoring the `.ts` file).

What we're looking for is to be able to write standard imports using ES Modules fully-specified import paths (with `.js` extension) and that they be resolved to the `.ts` files (as TypeScript + `tsc` do today)

**Comment by alexander-akait** [comment]
Give me time to look at this. I think problem somewhere here https://github.com/TypeStrong/ts-loader/blob/main/src/resolver.ts

**Comment by alexander-akait** [comment]
Anyway why do you want to use `import { test } from './test.js';` instead `import { test } from './test.ts';`? I think in ts better to have `ts` extension at the end, it is fully-specified import

**Comment by karlhorky** [comment]
> I think in ts better to have `ts` extension at the end, it is fully-specified import

The TypeScript team doesn't agree, check out the issue I linked above: https://github.com/microsoft/TypeScript/issues/41887#issuecomment-741968855

**Comment by alexander-akait** [comment]
Yep, I see...:
```
[tsl] ERROR in /home/evilebottnawi/IdeaProjects/webpack-babel-test/src/index.tsx(1,22)
      TS2691: An import path cannot end with a '.tsx' extension. Consider importing './test.js' instead.
```

**Comment by karlhorky** [comment]
Thanks for the confirmation, I've opened an issue in `babel-loader` over here: https://github.com/babel/babel-loader/issues/904

**Comment by alexander-akait** [comment]
Simple workaround for your simple case:
```
resolve: {
    alias: {
      './test.js': './test'
    },
    extensions: ['.tsx', '.ts', '...'],
},
```

Ideally `ts-loader` should respect `resolve.extensions` (better `resolve.byDependency.typescript`) and when you using `import something from './foo.js'` try to resolve `./foo.js` as `./foo.tsx`/`./foo.ts`  and then other variants (i.e. `./foo.js` and etc).

To avoid collisions between `ts-loader` resolving and Node.js resolbing we should support https://webpack.js.org/configuration/resolve/#resolvebydependency, so you will use:
```
resolve: {
  byDependency: {
    typescript: {
      extensions: ['.tsx', '.ts', '...'],
    },
}    
```

It will be implement using https://webpack.js.org/api/loaders/#thisgetresolve, we use the same logic for `sass`/`less`/etc so `@import` with CSS and SASS works good. 

Honestly it's not hard to do.

**Comment by alexander-akait** [comment]
Simple we should not do this https://github.com/TypeStrong/ts-loader/blob/main/src/resolver.ts, instead we should use `this.getResolve` (simple example https://github.com/webpack-contrib/less-loader/blob/master/src/utils.js#L35), by default you can set `extensions: [".ts", "..."],`, so in future developers don't need to set `resolve.extension` with `.ts` extensions, it will work out of box

**Comment by Josehower** [comment]
another workaround i found was using `NormalModuleReplacementPlugin` to replace the problematic extention


```js
 module.exports = function (env) {
  return {
    plugins: [
      new webpack.NormalModuleReplacementPlugin(new RegExp(/\.js$/), function (resource) {
        resource.request = resource.request.replace('.js', '');
      }),
        }
      ),
    ],
  };
};
```

in our case this did the trick

**Comment by alexander-akait** [comment]
Yep, should works too, anyway will be better to solve it in `ts-loader`, because we have more profit here like better DX, resolvgin by dependency, no need `enhanced-resolve` in deps

**Comment by johnnyreilly** [comment]
Yeah I think `ts-loader` would be open to a PR that tackles this.

**Comment by sokra** [comment]
Something like that could be solved in a custom resolver plugin. I think think this typescript-specific problem fits into the webpack core.

The resolver plugin could take an `extensions` argument which is a list of typescript extensions that should be tried when the request ends with `.js`.

**Comment by johnnyreilly** [comment]
Cool - perhaps that's a better place for it to go!

**Comment by karlhorky** [comment]
not stale

**Comment by alexander-akait** [comment]
@johnnyreilly I think we need this in `ts-loader` after https://devblogs.microsoft.com/typescript/announcing-typescript-4-5-beta/#type-in-packagejson-and-new-extensions

**Comment by vankop** [comment]
feel free to use https://github.com/softwareventures/resolve-typescript-plugin

**Comment by alexander-akait** [comment]
And more information you can found here https://github.com/TypeStrong/ts-loader/issues/1383

**Comment by karlhorky** [comment]
Ok so @alexander-akait can I assume by closing this, it means that it will be implemented over in `ts-loader` in that issue https://github.com/TypeStrong/ts-loader/issues/1383 ?

That means that it will no longer be a part of webpack core like @sokra [suggested above](https://github.com/webpack/webpack/issues/13252#issuecomment-828714153)?

**Comment by alexander-akait** [comment]
hm, we can put it in core

@sokra What do you think?

**Comment by karlhorky** [comment]
@sokra did you have a chance to make a decision here? Should this be in webpack core as you [suggested above](https://github.com/webpack/webpack/issues/13252#issuecomment-828714153)? 

Or should this be done in `ts-loader`, potentially as part of https://github.com/TypeStrong/ts-loader/issues/1383 ?

**Comment by alexander-akait** [comment]
@karlhorky I think we need a plugin in https://github.com/webpack/enhanced-resolve/ (I already implemented it in thread) and allow customize resolver, allow ts-loader can create custom resolver using loader API and supports it out of box

**Comment by karlhorky** [comment]
Oh great, good news, thanks for the update!

So am I understanding correctly: this is already implemented in `enhanced-resolve` and now just needs to be implemented in `ts-loader`?

**Comment by alexander-akait** [comment]
@karlhorky It is not implemented in `enhanced-resolve`, but it is easy https://github.com/TypeStrong/ts-loader/issues/1383#issuecomment-968075478, just want to verify @sokra and @vankop support my idea

**Comment by vankop** [comment]
I we want parity with `tsc` we can make a resolver plugin.

**Comment by alexander-akait** [comment]
@vankop I think it will be good, because ESM is popular, will be great to do it as part of core

**Comment by vankop** [comment]
should be fixed by https://github.com/webpack/enhanced-resolve/pull/351

**Comment by alexander-akait** [comment]
@karlhorky I think you still need to setup it for ts,like you use `extensions` for ts before, but now you don't need many code, just one line, we need to update docs

**Comment by karlhorky** [comment]
> just one line

Ok, so what is the configuration that would be required? I'm sure that this will be a common question for those looking to take advantage of this.

What I can see from the PR is something like this:

```js
{
  "extensionAlias": {
    ".js": [".ts", ".js"],
    ".mjs": ".mts"
  }
}
```

Is `extensionAlias` a valid top-level key in webpack config? Or does `enhanced-resolve` need to be added via a plugin or something in the config as well?

**Comment by karlhorky** [comment]
Would also be good to document in this thread here what version of `webpack` will have this change, if possible.

**Comment by alexander-akait** [comment]
Accidentally close, yes, you can specify `extensionAlias` in the `resolve` option (https://webpack.js.org/configuration/resolve/), like you do it for `alias`/etc

**Comment by vankop** [comment]
technically we can add this to default rules but webpack doesn't support ts out of the box.. so probably you will need specify extension alias

**Comment by karlhorky** [comment]
Alright, so the configuration is going to be something like this I assume:

```js
module.exports = {
  resolve: {
    extensionAlias: {
      '.js': ['.ts', '.js'],
      '.mjs': '.mts',
      '.cjs': '.cts',
    },
  },
}
```

Or should the `.mjs` and `.cjs` values also be arrays with fallbacks to the non-transformed extensions? Eg. like this:

```js
module.exports = {
  resolve: {
    extensionAlias: {
      '.js': ['.ts', '.js'],
      '.mjs': ['.mts', '.mjs'],
      '.cjs': ['.cts', '.cjs'],
    },
  },
}
```

I guess ideally, the non-transformed extension would be a default in all configurations, so that this would work:

```js
module.exports = {
  resolve: {
    extensionAlias: {
      '.js': '.ts',
      '.mjs': '.mts',
      '.cjs': '.cts',
    },
  },
}
```

**Comment by laverdet** [comment]
> another workaround i found was using `NormalModuleReplacementPlugin` to replace the problematic extention
> 
> ```js
>  module.exports = function (env) {
>   return {
>     plugins: [
>       new webpack.NormalModuleReplacementPlugin(new RegExp(/\.js$/), function (resource) {
>         resource.request = resource.request.replace('.js', '');
>       }),
>         }
>       ),
>     ],
>   };
> };
> ```
> 
> in our case this did the trick

I tweaked the RegExp here because otherwise imports to modules like [sha.js](https://www.npmjs.com/package/sha.js/v/2.4.9) will fail. Thanks!

```ts
            new NormalModuleReplacementPlugin(/^\..+\.js$/, resource => {
                resource.request = resource.request.replace(".js", "");
            }),
```

**Comment by alexander-akait** [comment]
Yeah, sometimes I think npm should not allow to use `.` in a package name, because it is pain to write regexp and code looks misleading:

```
var shajs = require('sha.js')
```

Do we load `./sha.js` or `./sha.js/index.js`? weird

**Comment by karlhorky** [comment]
> Would also be good to document in this thread here what version of `webpack` will have this change, if possible.

Looks like this is in version `5.74.0`: https://github.com/webpack/webpack/releases/tag/v5.74.0

**Comment by iamWing** [comment]
> > another workaround i found was using `NormalModuleReplacementPlugin` to replace the problematic extention
> > ```js
> >  module.exports = function (env) {
> >   return {
> >     plugins: [
> >       new webpack.NormalModuleReplacementPlugin(new RegExp(/\.js$/), function (resource) {
> >         resource.request = resource.request.replace('.js', '');
> >       }),
> >         }
> >       ),
> >     ],
> >   };
> > };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > in our case this did the trick
> 
> I tweaked the RegExp here because otherwise imports to modules like [sha.js](https://www.npmjs.com/package/sha.js/v/2.4.9) will fail. Thanks!
> 
> ```ts
>             new NormalModuleReplacementPlugin(/^\..+\.js$/, resource => {
>                 resource.request = resource.request.replace(/\.js$/, "");
>             }),
> ```

The regex on the tweaked version doesn't seem right to me. Neither `./app.js` or `sha.js` matches the expression.

My suggestion would be use `/.*\/+.+\.js$/` instead. Matching a `/` character in the middle of the path can help identifying if we're importing a local module or not, because if we're importing a dependency installed we usually just write `import something from 'something';`, but if we're importing a local module, we write `import something from './path/something.js'`.

A better way to cover all cases would be tweaking the function in `NormalModuleReplacementPlugin` to exclude some patterns for the edge cases.

e.g.
```ts
new NormalModuleReplacementPlugin(/.*\/+.+\.js$/, (resource) => {
  if (/^sha\.js$/.test(resource.request) return; // - Exclude the edge cases using if statement
  resource.request = resource.request.replace(/\.js$/, '');
}),
```

Maybe we can also develop a plugin to do what we're doing with `NormalModuleReplacementPlugin` here but also check the dependency list from `package.json` so that all packages listed there can be excluded automatically? I'll do some research on this later.
```

**Comment by karlhorky** [comment]
@iamWing the `/^\..+\.js$/` regex seems to work for `./app.js`, and it is supposed to filter out `sha.js`:

```js
> /^\..+\.js$/.test('./app.js')
> true
```

**Comment by iamWing** [comment]
> 



> @iamWing the `/^\..+\.js$/` regex seems to work for `./app.js`, and it is intended to filter out `sha.js`:
> 
> ```js
> > /^\..+\.js$/.test('./app.js')
> > true
> ```

My bad for the typo, I actually mean `_/app.js` instead of `./app.js` there.

The reason I'm using `_/app.js` rather then `./app.js` there is because I have path alias configured in `tsconfig` and I think a lot of people do rather than just typing long paths for relative imports, hence I proposed to check for the `/` in the import path to check if it's a realative import instead of `./`.

**Comment by karlhorky** [comment]
I've also opened a corresponding issue in Next.js, since it seems that they have their own flavor of the problem:

- https://github.com/vercel/next.js/issues/41961

**Comment by karlhorky** [comment]
Seems like the `ResolveOptionsWebpackOptions` type is missing the `extensionAlias` type too:

<img width="699" alt="Screenshot 2022-11-03 at 14 59 13" src="https://user-images.githubusercontent.com/1935696/199740732-eeaff03a-8021-411d-bcfc-8f50e1e9c34b.png">

**Comment by alexander-akait** [comment]
@karlhorky Can you look at the latest version?

**Comment by karlhorky** [comment]
Oh sorry - deleted my comment! Indeed the type is there in `5.74.0`, somehow one of my webpack versions was locked to `5.73.0` 😬

**Comment by alexander-akait** [comment]
I think we can close it, now we have `extensionAlias` - https://webpack.js.org/configuration/resolve/#resolveextensionalias

**Comment by karlhorky** [comment]
Use `extensionAlias` in Next.js via `experimental.extensionAlias` config introduced in https://github.com/vercel/next.js/pull/45423:

 `next.config.js`

```js
/** @type {import("next").NextConfig} */
const nextConfig = {
  experimental: {
    // Remove .js from import specifiers, because
    // webpack does not yet support TypeScript-style
    // module resolution out of the box
    // https://github.com/webpack/webpack/issues/13252#issuecomment-1171080020
    // https://github.com/vercel/next.js/pull/45423
    extensionAlias: {
      '.js': ['.ts', '.tsx', '.js', '.jsx'],
      '.jsx': ['.tsx', '.jsx'],
      '.mjs': ['.mts', '.mjs'],
      '.cjs': ['.cts', '.cjs'],
    },
  },
}

module.exports = nextConfig
```

**Comment by sibelius** [comment]
is there an extensionAlias for jest as well ?

**Comment by sibelius** [comment]
related jest issue https://github.com/jestjs/jest/issues/15354
