### ISSUE TITLE
Include "[acorn]" tag in parsing errors

### ISSUE THREAD

**Issue by pbadenski** [webpack/webpack#13258]
## Feature request

**What is the expected behavior?**

Add acorn tag (optionally with acorn version) to "Module parse failed" errors.

Change this:

```Module parse failed: Cannot use keyword 'await' outside an async function (190:11)```

to that:

```[acorn@8.2.1] Module parse failed: Cannot use keyword 'await' outside an async function (190:11)```

For extra points - and if possible - it would be helpful to include an output from acorn with a code fragment that's being problematic (helpful for debugging).

**What is motivation or use case for adding/changing the behavior?**

This type of webpack parsing issues do not happen very often to me. Each time it does happen though, I tend to spend up to a few hours digging into babel, just to discover that this is actually a webpack builtin parser being a problem here. It feels like it's really a minor point, but surprisingly this gets me over and over again.

**How should this be implemented in your opinion?**
-

**Are you willing to work on this yourself?**
yes

**Comment by alexander-akait** [comment]
But I think this did not solve the problem at the root, almost no one knows what is supported in current acorn version...

**Comment by pbadenski** [comment]
Version is secondary - I'm ok if it's not there. It's that `[acorn]` tag bit that is super valuable to me as webpack user.

From where I sit - at least points me some direction. This type of issues pop up for me every few months and each time I find "Module parse failed" message very cryptic. I often assume (incorrectly) it's a babel problem and spend hours digging into that. Honestly - this error is just to give user something slightly more tangible (and potentially less confusing) to tackle.
