### ISSUE TITLE
Ids of chunkFiles

### ISSUE THREAD

**Issue by aileak** [webpack/webpack#13256]
Hi, I have problem with filenames of chunkFiles. In webpack 4, my chunk filenames starting in order from 2, 2.hash.chunk.js etc. In webpack 5 it has random numbers 474.hash.chunk.js, 660.hash.chunk.js. Is it ok?

Webpack config:
`
optimization: { splitChunks: { chunks: 'all' }, }
`

**Comment by alexander-akait** [comment]
Yes, it is ok and better for caching
