### ISSUE TITLE
Unstable require context

### ISSUE THREAD

**Issue by ghost** [webpack/webpack#1326]
Hi,

I am migrating a rather large project and I have a strange issue with the require.context. It would take me a while to try and simplify the repro so just asking beforehand in case someone can help me explain the behavior.

Imagine the following file structure
folder 1
--- module 1.1
--- module 1.2
folder 2
--- module 2
folder 3
--- module 3
app.js

In app.js I need to dynamically load all modules from folder 1 and folder 2, so I write:

``` javascript
var req = require.context("folder1/", true);
req.keys().forEach(function(key){ req(key); });

req = require.context("folder2/", true);
req.keys().forEach(function(key){ req(key); });
```

So far so good, I get 2 dynamic modules for both folders and all files are loaded.
Now, somewhere in the bottom of app.js I write

``` javascript
var module3 = require("folder3/module3");
```

And now suddenly instead of folder2 I get a webpackMissingModule() and it complains at runtime that module folder2/ could not be found.
The interesting thing is that module3 is in no way related to folder1 or folder2. It's just a module without any dependencies...

Am I doing something what webpack is not designed for? Or does it seem like a bug with dependency management?

**Comment by bebraw** [comment]
Can you check with webpack 2?
