### ISSUE TITLE
Types/Doc mismatch for resourceQuery: { not: /regex/ }

### ISSUE THREAD

**Issue by slorber** [webpack/webpack#13284]
# Bug report

**What is the current behavior?**

This is documented:

![image](https://user-images.githubusercontent.com/749374/116703425-900a1580-a9ca-11eb-9e74-a4ae33a3ddd0.png)

https://webpack.js.org/guides/asset-modules/#replacing-inline-loader-syntax

But using `not` only allows an array in TS:

https://github.com/webpack/webpack/blob/master/types.d.ts#L9336

![image](https://user-images.githubusercontent.com/749374/116703723-e0817300-a9ca-11eb-8f70-a4f5f5725d23.png)

And this is rejected in practice

![image](https://user-images.githubusercontent.com/749374/116703956-24747800-a9cb-11eb-9c68-39c5b873f531.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

See above

**What is the expected behavior?**

TS and doc are in sync, not sure which is wrong

**Other relevant information:**
webpack version:  5/master
Node.js version:
Operating System:
Additional tools:

**Comment by alexander-akait** [comment]
Bug in types
