### ISSUE TITLE
`5.34.0` ➞ `5.36.1` breaks compatibility with `@types/webpack`

### ISSUE THREAD

**Issue by yoav-lavi** [webpack/webpack#13280]
# Bug report
See also: https://github.com/webpack/webpack/issues/13278

Between `5.34.0` and `5.36.1` a typing change was released which typed `SyncBailHook`, `SyncHook`, `SyncWaterfallHook`, `AsyncSeriesHook`, `AsyncSeriesWaterfallHook` and `HookMap` as generic. `Tapable` was also unexported. As with the linked issue this should have been fine due to `@types/webpack` not being used anymore, but this breaks builds using third party libraries that use `@types/webpack` as a dependency.

This can currently be mitigated by setting `skipLibCheck` to `true`

Error excerpt: 

```
node_modules/@types/webpack/index.d.ts:32:3 - error TS2305: Module '"tapable"' has no exported member 'Tapable'.

32   Tapable,
     ~~~~~~~

node_modules/@types/webpack/index.d.ts:1062:23 - error TS2707: Generic type 'SyncWaterfallHook<T, AdditionalOptions>' requires between 1 and 2 type arguments.

1062             resolver: SyncWaterfallHook;
                           ~~~~~~~~~~~~~~~~~

node_modules/@types/webpack/index.d.ts:1063:22 - error TS2707: Generic type 'SyncWaterfallHook<T, AdditionalOptions>' requires between 1 and 2 type arguments.

1063             factory: SyncWaterfallHook;
                          ~~~~~~~~~~~~~~~~~

node_modules/@types/webpack/index.d.ts:1064:28 - error TS2707: Generic type 'AsyncSeriesWaterfallHook<T, AdditionalOptions>' requires between 1 and 2 type arguments.

1064             beforeResolve: AsyncSeriesWaterfallHook;
```

**What is the current behavior?**

Building a project using this version fails on type checking

**If the current behavior is a bug, please provide the steps to reproduce.**

Update Webpack to `5.36.1`, have a dependency still using `@types/webpack`

**What is the expected behavior?**

Type checking the plugins should not throw errors introduced by a non breaking upgrade

**Other relevant information:**
webpack version:  5.36.1
Node.js version: v15.14.0
Operating System: macOS 11.3

**Comment by sokra** [comment]
There has been no change in the webpack typings about anything tapable related.

The tapable typings always had generic arguments.

> Update Webpack to `5.36.1`, have a dependency still using `@types/webpack`

webpack 5 ships it's own types. Try to get rid of `@types/webpack`...

Maybe `@types/webpack` need to have a dependency on `@types/tapable` so it consumes the correct tapable types...

**Comment by yoav-lavi** [comment]
@sokra I'm aware that Webpack now ships it's own types, the issue is that some third party plugins still use `@types/webpack` which causes builds to break unexpectedly from the user perspective between these versions. For some reason this doesn't show up when using `5.34.0`.

**Comment by sokra** [comment]
> For some reason this doesn't show up when using `5.34.0`.

I guess it's not the version, but instead the layout of your node_modules folder has changed in a way that hoisting of dependencies is different. And this causes `@types/webpack` to use `tapable@2` as typings when it should better use `@types/tapable` types...

**Comment by yoav-lavi** [comment]
The only upgrade was the Webpack version, but I think you're right since forcing the newest `@types/webpack` using `resolutions` also seems to fix this issue (but not the linked one). 
I'll close this, thanks!
