### ISSUE TITLE
Support async evaluation for compiler hooks

### ISSUE THREAD

**Issue by aminpaks** [webpack/webpack#13289]
## Feature request
Add a new async compiler hook at the beginning of compiler initialization, or turn most of sync hooks like `entryOption` to async.

**What is the expected behavior?**
A plugin should be able to perform asynchronous tasks at any hooks specially at compiler initialization and configuration.

**What is motivation or use case for adding/changing the behavior?**
There is some cases that plugin needs to evaluate for example new entries and this must be asynchronous, today this cannot be done as per all the hooks before, including `entryOption`, are synchronous.

**How should this be implemented in your opinion?**
Refactor related sync process to async.

**Are you willing to work on this yourself?**
Yes.

**Comment by alexander-akait** [comment]
bump

**Comment by sokra** [comment]
Compiler initialization need to stay sync. You can add async logic to determine entries. This is even supported without plugins:

``` js
// webpack.config.js
module.exports = {
  entry: async () => {
    await doSomething();
    return { main: "./main.js" };
  }
}
```

**Comment by aminpaks** [comment]
>Compiler initialization need to stay sync
@sokra this means there is no way for a plugin to initialize itself async and manipulate the entries. I was working on a plugin to dynamically update the entries. I might being it the wrong way.
How would you suggest to build a plugin building an entry-map for system.js?

**Comment by alexander-akait** [comment]
You can use `https://github.com/webpack/webpack/blob/main/lib/index.js`, i.e. 
```js
const DynamicEntryPlugin = require("./DynamicEntryPlugin");
new DynamicEntryPlugin(compiler.context, async () => {}).apply(compiler);
```

in your plugin and add entry dynamically
