### ISSUE TITLE
I can confirm that there might be a bug with the `splitChunks` feature:

### ISSUE THREAD

**Issue by acarlstein** [webpack/webpack#13288]
I can confirm that there might be a bug with the `splitChunks` feature:

I have this webpack configuration:
```javascript
module.exports = {
  entry: {
    index: './src/js/index.js',
    about: './src/js/about.js'
  },
  output: {
    filename: 'js/[name]/[name].js',
    chunkFilename: 'js/[name].js'
  },
  optimization: {
    splitChunks: {
      chunks: 'all',
      name: 'vendor'
    }
  }
}
```

I was expecting that the Vue code will be saved inside the file `vendor.js` inside `/dist/js` directory as shown in the image below:
![image](https://user-images.githubusercontent.com/5709926/113320954-57462600-92d0-11eb-8d17-850f15ac67c5.png)

Instead, the Vue code is inside the file `vendor.js`, which is saved in the directory `/dist/js/vendor` as shown below:
![image](https://user-images.githubusercontent.com/5709926/113321167-8f4d6900-92d0-11eb-927f-22d41a5f8148.png)

It like the output property `chunkFilename` is being ignored.

_Originally posted by @acarlstein in https://github.com/webpack/webpack/issues/9297#issuecomment-812005782_

**Comment by alexander-akait** [comment]
No bugs, you use `filename: 'js/[name]/[name].js',`, please use the issue template

**Comment by alexander-akait** [comment]
Here the same answer https://github.com/webpack/webpack/issues/9297#issuecomment-503061903

**Comment by alexander-akait** [comment]
Answered, feel free to feedback
