### ISSUE TITLE
reuseExistingChunk option does not respect webpackChunkName

### ISSUE THREAD

**Issue by chrissantamaria** [webpack/webpack#13299]
# Bug report

**What is the current behavior?**

Webpack 5 does not seem to respect the `splitChunks.cacheGroups.{cacheGroup}.reuseExistingChunk` option when handling chunks named with `webpackChunkName`, resulting in the custom name being overridden by the cache group name.

**If the current behavior is a bug, please provide the steps to reproduce.**

See my minimal reproduction repo [here](https://github.com/chrissantamaria/webpack-splitchunks-name-bug) showcasing example builds in v4 and v5. v4 behaves as expected while v5 (from what I can tell) incorrectly names one of the async chunks.

The configs in `webpack-4` and `webpack-5` should be identical besides a few version-specific changes around cleaning and disabling default cache groups. `@formatjs/intl-datetimeformat` is used as an arbitrary example to illustrate dynamically importing two modules, one of which meets the cache group size threshold.

**What is the expected behavior?**

Webpack v5 matches the previous behavior from v4 where `reuseExistingChunk: true` results in named chunks not being affected by split chunk cache groups (even if they satisfy a group's `test`). In the case of the specific example above, both async chunks should be named with their custom `webpackChunkName`s rather than one using the `lib` cache group hash.

I may be misinterpreting the expected behavior here, though it does seem like there is a change between v4 and v5. Perhaps I missed something in the [migration guide](https://webpack.js.org/migrate/5/)?

**Other relevant information:**
webpack version: 5.36.2 (4.46.0 when comparing with webpack 4 behavior)
Node.js version: 14.16.0
Operating System: macOS 10.15.7

**Comment by chrissantamaria** [comment]
@alexander-akait apologize for the ping, just wondering if there's anything else I can do to help resolve this

As an alternative, in my use case a reasonable workaround could be creating a new chunk group like `intlPolyfills` (for example, matching `/node_modules\/@formatjs/`) to give custom filenames + prevent those chunks from being assigned to other groups. Functionally it would be similar to `webpackChunkName` but it may help get around the issue here. Tried exploring that a bit but couldn't get anything working - is that something `splitChunks` can handle?

**Comment by alexander-akait** [comment]
It is breaking change, do not use `name` if you want `reuseExistingChunk`, it is misleading which name you want to use

**Comment by chrissantamaria** [comment]
@alexander-akait maybe I'm misunderstanding the purpose of these settings - my end goal is for `webpackChunkName` to take precedence over any chunk groups. What's the best way to implement that besides `reuseExistingChunk`?

**Comment by alexander-akait** [comment]
`webpackChunkName` to take precedence over any chunk groups, `reuseExistingChunk` just say to put some modules to exiting chunk, just use:
```
 lib: {
          test(module) {
            return (
              module.size() > 160000 &&
              /node_modules[/\\]/.test(module.nameForCondition() || '')
            );
          },
          reuseExistingChunk: true,
        },
```

And behavior will be same

**Comment by chrissantamaria** [comment]
@alexander-akait that works, but then I lose out on custom `lib` naming which is also necessary for my use case. Just to clarify, are you saying it's not possible to accomplish both of these?

Thanks for helping debug this :)

**Comment by alexander-akait** [comment]
When you use `reuseExistingChunk`, it means you want to split modules from `exiting` chunks in your case you specify them using `webpackChunkName`, you don't need naming here because you already have `name`, `name` make sense when your chunk doesn't have `name`.

You can change name in `webpackChunkName` comment.

Also you can choose chunk using https://webpack.js.org/plugins/split-chunks-plugin/#splitchunkschunks.

**Comment by chrissantamaria** [comment]
@alexander-akait sorry, should have clarified the example repo a bit more. In my use case there will be other chunks (not named with `webpackChunkName`) that should match the `lib` group and be named with that custom function. For example, here's a build with an additional async import added (not named with `webpackChunkName`):

```
dist
├── 93.js
├── 93.js.LICENSE.txt
├── main.js
├── polyfill-intl-datetimeformat-add-all-tz.js
├── polyfill-intl-datetimeformat.js
└── polyfill-intl-datetimeformat.js.LICENSE.txt
```

The `93.js` chunk should be prefixed by `lib-`.

 Happy to update the repo if that would be helpful

**Comment by alexander-akait** [comment]
I think in this case you need two groups with `reuseExistingChunk: true`, but if you update repo and show what you expected, I will help you

**Comment by chrissantamaria** [comment]
@alexander-akait sure, just updated the repo with an additional `three` async chunk (arbitrary example, just wanted something big).

Are you suggesting something like what I was describing [here](https://github.com/webpack/webpack/issues/13299#issuecomment-842491543) with a group specifically for these types of async chunks?

**Comment by alexander-akait** [comment]
You can use:
```js
{
  reuse: {
          test(module) {
            return (
              module.size() > 160000 &&
              /node_modules[/\\]/.test(module.nameForCondition() || '')
            );
          },
          reuseExistingChunk: true,
  },
  three: {
          chunks: (chunk) => {
            if (chunk.name === 'polyfill-intl-datetimeformat-add-all-tz') {
              return false;
            }
            
            return true;
          },
          test(module) {
            return (
                module.size() > 160000 &&
                /node_modules[/\\]/.test(module.nameForCondition() || '')
            );
          },
          name(module) {
            const hash = crypto.createHash('sha1');
            
            if (!module.libIdent) {
              throw new Error(
                  `Encountered unknown module type: ${module.type}. Please open an issue.`
              );
            }
            
            hash.update(module.libIdent({ context: path.resolve('.') }));
            
            return hash.digest('hex').substring(0, 8) + '-three';
          },
  },
}
```

First say what you want to move some modules to exiting chunks (but I strongly recommend specify more specific modules, i.e. better regexp/check in test)
Second split three in own chunks, you can tweak this more complicated. 

Just remember -  `reuseExistingChunk` get exiting chunk(s) and you can specify name, because you already have name.

Also you can use `filename` to specify filename.

**Comment by chrissantamaria** [comment]
@alexander-akait sounds good! Ended up finding a workaround for my specific use case but this example helps show some of the differences in Webpack 5. This doesn't look like a bug so I'm okay closing this issue if you'd like.

**Comment by alexander-akait** [comment]
Yep, there is no bugs, `reuseExistingChunk` means you already have name for chunk(s), so naming will not work here
