### ISSUE TITLE
Webpack 5: "Module parse failed: Unexpected token" when importing JSON file

### ISSUE THREAD

**Issue by GiancarlosIO** [webpack/webpack#13292]
# Bug report
I think I have found a bug in webpack 5. 
I'm getting the error `Module parse failed: Unexpected token (1:13)` from webpack. It points to a `node_modules/emoji-mart/data/all.json`. `emoji-mart` is a react library that we are using https://github.com/missive/emoji-mart.

**What is the current behavior?**
When I try to compile my application webpack throws an error saying that it can't parse the json file.
![image](https://user-images.githubusercontent.com/17274950/116835567-b1b0fb80-ab88-11eb-91b4-11e3e3a6c4af.png)
````js
 @ ../../../node_modules/emoji-mart/dist-es/utils/emoji-index/emoji-index.js 1:0-42 3:38-42
 @ ../../../node_modules/emoji-mart/dist-es/index.js 1:0-72 1:0-72
 @ ../jsx/MyApp/screens/screen-inner/sections/Tab/Chat/components/Emojis.tsx
 @ ../jsx/MyApp/screens/screen-inner/sections/Tab/Chat/components/TextFieldForm.tsx
 @ ../jsx/MyApp/screens/screen-inner/sections/Tab/Chat/Chat.tsx 34:0-55 199:18-31
 @ ../jsx/MyApp/screens/screen-inner/sections/Tab/Chat/index.tsx 1:0-33 1:0-33
 @ ../jsx/MyApp/screens/screen-inner/sections/Tab/LiveTabs.tsx 36:0-26 250:80-84
 @ ../jsx/MyApp/screens/screen-inner/sections/Tab/index.tsx 1:0-37 1:0-37
 @ ../jsx/MyApp/screens/screen-inner/Detail.tsx 50:0-43 289:18-26 336:18-26
 @ ../jsx/MyApp/screens/screen-inner/index.tsx 32:0-38 131:43-49
 @ ../jsx/MyApp/App.tsx 40:0-44 66:16-25
 @ ../jsx/MyApp/index.tsx 14:0-24 24:67-70
````
It points to the first line of `node_modules/emoji-mart/dist-es/emoji-index/emoji-index.js`:
````js
import data from '../../../data/all.json'; // <= THIS ONEEEE
import NimbleEmojiIndex from './nimble-emoji-index';
var emojiIndex = new NimbleEmojiIndex(data);
var emojis = emojiIndex.emojis,
    emoticons = emojiIndex.emoticons;

function search() {
  return emojiIndex.search.apply(emojiIndex, arguments);
}

export default {
  search: search,
  emojis: emojis,
  emoticons: emoticons
};
````

Maybe it's related to this? 
(image from emoji-mart github docs)
![image](https://user-images.githubusercontent.com/17274950/116835653-03f21c80-ab89-11eb-89a7-815464ceee6e.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

- Install `"emoji-mart": "3.0.0"` package
- Configure babel loader with react
- Build files with webpack in production mode

Webpack config:
````js
{
 ....
 module: {
   rules: {
     {
  test: /\.(js|tsx|ts)$/,
  include: pathFolder,
  use: [
    {
      loader: 'babel-loader',
      options: {
        cacheDirectory: true,
      },
    },
  ],
},
 {
  test: /\.(graphql|gql)$/,
  include: [
    pathFolder,
    path.join(__dirname, '../../../../node_modules/@xxx'),
  ],
  loader: 'graphql-tag/loader',
},
{
  test: TEST,
  use: [
    'style-loader',
    'css-loader',
   'postcss-loader',
    'sass-loader',
  ],
},
{
  test: /\.svg$/,
  include: pathFolder,
  loader: 'svg-react-loader',
},
   }
 }
 ...
}
````

**What is the expected behavior?**
It should compile without errors since webpack5 supports json files.

**Other relevant information:**
My solution was to use the json-loader. With json-loader it builds without any errors 🤔
webpack version:  5.36.2
Node.js version: v12.18.2
Operating System: Window 10
Additional tools:
- "webpack-cli": "4.6.0"
- "terser-webpack-plugin": "5.1.1"
- "css-minimizer-webpack-plugin": "^2.0.0"
- "circular-dependency-plugin": "5.2.2"
- "html-webpack-harddisk-plugin": "2.0.0"
- "html-webpack-plugin": "5.3.1"

**Comment by sokra** [comment]
> * "html-webpack-harddisk-plugin": "2.0.0"

Could you try removing that plugin?

**Comment by GiancarlosIO** [comment]
@sokra same error without that plugin 😢

**Comment by alexander-akait** [comment]
@GiancarlosIO Can you provide reproducible example?

**Comment by GiancarlosIO** [comment]
@alexander-akait of course! I'll try to isolate the problem this week. I'll come back once I have the reproducible
🏃🏼

**Comment by alexander-akait** [comment]
@GiancarlosIO friendly ping

**Comment by Pulkit3234** [comment]
@alexander-akait  Can I work on this issue, I am new here so can you please guide me on how to move ahead with this issue, if its not taken?

**Comment by GiancarlosIO** [comment]
@alexander-akait @Pulkit3234 sorry for the delay. Here is the reproducible example:
https://github.com/GiancarlosIO/weebpack-5-parse-json-error

The repository has the same behavior and error that I have in my original project. It takes a long time to show the error (like 5 minutes) with dev or prod commands. If I enable the json-loader it only takes seconds or just 1 min to compile without errors.

Let me know if you need something more from my side.
Thanks!

**Comment by sokra** [comment]
Change `test: /\.m?js/` to `test: /\.m?js$/` in your webpack config.

**Comment by alexander-akait** [comment]
Answered (above), you have `/\.m?js/`, `test.json` is matching this regexp

**Comment by GiancarlosIO** [comment]
@sokra @alexander-akait thanks!

**Comment by reacterpro** [comment]
> Answered (above), you have `/\.m?js/`, `test.json` is matching this regexp

https://github.com/webpack/webpack/issues/13292#issuecomment-852974844
