### ISSUE TITLE
'__WEBPACK_DEFAULT_EXPORT__' before initialization during nodemon

### ISSUE THREAD

**Issue by shikhars371** [webpack/webpack#13293]
I am getting this error:

(node:8319) UnhandledPromiseRejectionWarning: ReferenceError: Cannot access 'WEBPACK_DEFAULT_EXPORT' before initialization

please help me its been a week nothing is found on google how to resolve it? node - v14.16.0

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

No one can help you without additional information. Please use the issue template and I will reopen and help you.
