### ISSUE TITLE
duplicated dependencies in the output bundle

### ISSUE THREAD

**Issue by Zane-XY** [webpack/webpack#1329]
I have `require('moment')` in my own module, also I use `bootstrap-daterangepicker` which also depends on `moment`, then I saw this in my build log:

```
 ./~/moment/moment.js 104 kB {0} [built]
 ...
[10] ./~/bootstrap-daterangepicker/~/moment/moment.js 104 kB {0} [built]
```

it seems `moment.js` has been bundled two times by webpack, and I have enabled `DedupePlugin` 

```javascript
	plugins: [
		new webpack.optimize.DedupePlugin(),
		new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/), 
...
	],
```
How to get rid of the duplication?

**Comment by sokra** [comment]
`npm dedupe`

**Comment by gsklee** [comment]
@sokra what's the purpose of the dedupe plugin then?

**Comment by bebraw** [comment]
@Zane-XY Any luck? Have you tried it with npm 3?

**Comment by Zane-XY** [comment]
@bebraw I didn't. I solved the problem by externalize the dependencies, and include them outside of webpack.
