### ISSUE TITLE
Need of more user friendly info about chunking

### ISSUE THREAD

**Issue by budarin** [webpack/webpack#1330]
There are lot of samples without usefull info fo novices in WebPack.
The information is short and not understandable for novices
There are plenty of questions out of the board...(

Please do not use abstract modules for samples - use real cases fo review

**Comment by shama** [comment]
Just want to point out the documentation is freely editable here https://github.com/webpack/docs/wiki/contents if you wanted to help out with this effort. Thanks!

**Comment by pksjce** [comment]
This issue was moved to webpack/webpack.io#98

**Comment by pksjce** [comment]
This issue was moved to webpack/webpack.io#127
