### ISSUE TITLE
How to load precompiled sourcemaps from node_modules

### ISSUE THREAD

**Issue by zerkalica** [webpack/webpack#1331]
I have a published library, transpiled from babel-code with precompiled sourcemaps:

```
node_modules/mylib:
index.js
index.js.map
mapTokens.js
mapTokens.js.map
plainObject.js
plainObject.js.map
Translator.js
Translator.js.map
```

How to teach webpack parse this maps, when i use this lib in my projet? Currently webpack builds sourcemap only for main project and not loads existing from node_modules.

**Comment by andreypopp** [comment]
See https://github.com/webpack/source-map-loader 

It's better to use GitHub Issues for issues with webpack only. Questions should be addressed to [StackOverflow Webpack](http://stackoverflow.com/tags/webpack) instead.

**Comment by zerkalica** [comment]
Thanks, i ask question on stackoverflow: https://stackoverflow.com/questions/31874944/how-to-load-precompiled-sourcemaps-from-node-modules

**Comment by yugandhar-pathi** [comment]
If you are trying this for react-app and you are using `create-react-app` please refer [this](https://stackoverflow.com/a/58964565/1773256) link.
