### ISSUE TITLE
Module Federation Plugin: force single runtime chunk to concatenate with container

### ISSUE THREAD

**Issue by ScriptedAlchemy** [webpack/webpack#13312]
When using next.js 10.2, im unable to successfully re-join the container code with the single runtime chunk. 

I was previously able to re-merge them with a simple plugin

```
    compiler.hooks.emit.tap(PLUGIN_NAME, (compilation) => {
      const { assets } = compilation;
      const assetArray = Object.keys(assets);

      let runtimePath = assetArray.find((asset) => {
        return asset.includes(this._options.runtime);
      });
      const runtime = assets[runtimePath];
      let remoteEntryPath = assetArray.find((asset) => {
        return asset.includes(this._options.fileName);
      });
      const remoteEntry = assets[remoteEntryPath];
      const mergedSource = new ConcatSource(runtime, remoteEntry);
      assets[remoteEntryPath] = mergedSource;
    });
```

However, this no longer works and I get a "container does not exist" error, even when typing directly into the browser console `window.remoteName` will return undefined. 

My idea is to try and get the runtime requirements added to the normal webpack runtime, then duplicate the asset and strip the hashed name off of it. This should give me a "normal" functioning container capable of booting and running without having to track down and load both the webpack runtime and the container.js file of the remote

@sokra, do you have any ideas around how I can force the usually code split runtime requirement back into the standard webpack runtime?

**Comment by sokra** [comment]
It might be easier to opt-out from creating a runtime chunk for this entry at all.

``` js
		compiler.hooks.thisCompilation.tap("...", compilation => {
			compilation.hooks.addEntry.tap(
				"...",
				(_, { name: entryName }) => {
					if (entryName !== "name-of-mf-entry") return;
					const data = compilation.entries.get(entryName);
					data.options.runtime = undefined;
				}
			);
		});
```

**Comment by sokra** [comment]
But you can use MF with runtime chunk too. Just make sure to load both, the runtime chunk and the remote entry, into the target page.

**Comment by ScriptedAlchemy** [comment]
Thanks Tobias, ill give this a try - I was able to get the ConcatSource to work again - it looks like when I try to make react an external in next, remote seems to stop attaching to scope so its always retuning undefined. 

I changed to resolve.alias for react 
`Object.assign(config.resolve.alias,{ react: require.resolve("./react.js")})`

and here's my react file
```
if (global.React) {
  module.exports = global.React;
} else if (process.browser && window.React) {
  module.exports = window.React;
} else if (process.browser) {
  window.React = require("react");
  module.exports = window.React;
} else {
  global.React = require("react");
  module.exports = global.React;
}
```

This gets singleton sharing of react to work in the nextjs world (next is missing the async bootstrap)
