### ISSUE TITLE
__webpack_require__.d is not a function

### ISSUE THREAD

**Issue by code1x1** [webpack/webpack#13316]
# Bug report

**What is the current behavior?**

I have a big/medium sized project using webpack 5.36.2. just migrated from webpack 4.44.2. which worked fine for my team but the speed improvement between those two versions is just insane. Thank you for that.
I noticed that optimization.runtimeChunk = true gave an extra performance boost, but the resulting bundle shows an error "__webpack_require__.d is not a function" which seams to happen just in that project. i tried to isolate the error in a small test repo. if i set optimization.runtimeChunk = false then the error disappears, but the build time is significantly higher.
sometimes its "__webpack_require__.r is not a function".

**If the current behavior is a bug, please provide the steps to reproduce.**

1. clone this repo https://github.com/code1x1/webpack-require-d-is-not-a-function
2. run `npm run start`
3. open http://localhost:3000 in your browser
4. open developer console in your browser
 

**What is the expected behavior?**

optimization.runtimeChunk = true should build the bundle and the runtime.~chunk.js should contain __webpack_require__.d definition which is missing.
 

**Other relevant information:**
webpack version:  5.36.2
Node.js version: v12.16.3
Operating System: Debian GNU/Linux 10 (buster)
Additional tools: npm 6.14.12

**Comment by alexander-akait** [comment]
```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@keen%2feditorconfig - Not found
npm ERR! 404 
npm ERR! 404  '@keen/editorconfig@^1.0.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/evilebottnawi/.npm/_logs/2021-05-06T12_26_03_163Z-debug.log
```

Can't run your example. 

> if i set optimization.runtimeChunk = false then the error disappears, but the build time is significantly higher.

It seems you forgot to include `runtime` chunk in your `index.html`.

Also you need webpack-dev-server@4-beta.2 to use multiple chunks, we are working on stable release, sorry for this

**Comment by code1x1** [comment]
oh sorry that was private npm package i removed it.

> It seems you forgot to include runtime chunk in your index.html.
the chunks are loaded correctly by the html-webpack-plugin all chunks exist but the runtime chunk doesnt contain the webpack_require.d function.

> Also you need webpack-dev-server@4-beta.2 to use multiple chunks, we are working on stable release, sorry for this
Ok i didnt know that

**Comment by sokra** [comment]
error An unexpected error occurred: "https://registry.yarnpkg.com/md-progress-circular: Not found".

I'm also unable to install the repo

**Comment by manasb-uoe** [comment]
Noticing the exact same issue. In webpack v4 we used to have:

```
runtimeChunk: { 
   name: (entrypoint: { name: string }) => `runtime-${entrypoint.name}`
}
```

Having the same config in webpack v5 results in `Uncaught TypeError: __webpack_require__.r is not a function` error being logged in the console, although app functionality remains unaffected. 

As @code1x1 mentioned, setting `runttimeChunk=false` resolves this.

**Comment by manasb-uoe** [comment]
@alexander-akait I can confirm that I am loading the runtime chunk. Here are the different scripts being included in `index.html`:

```html
  <script defer src="/s/runtime~polyfills.js"></script>
  <script defer src="/s/polyfills.js"></script>
  <script defer src="/s/runtime~index.js"></script>
  <script defer src="/s/vendors-common.js"></script>
  <script defer src="/s/index.js"></script>
```

Will try to create a repro later today.

**Comment by code1x1** [comment]
i updated the repo https://github.com/code1x1/webpack-require-d-is-not-a-function

**Comment by code1x1** [comment]
i found out that entrypoints with no imports are causing the error.
i created a fixed branch for demonstration purpose.
if i add lodash import to the preApp.js the error message disappears
https://github.com/code1x1/webpack-require-d-is-not-a-function/pull/1/files#diff-55df9f1608f148b01fbe0ac729345fbb89a369222cb296909779df2d6a5c5bc3

**Comment by alexander-akait** [comment]
@code1x1 You have multiple runtimes `runtime~platform.bundle.js` and `runtime~preApp.bundle.js` on the same page with the same `self.webpackChunkwebpack_example` global method, so after second runtime loaded, it will replace first runtime, so some methods are not available anymore

> if i add lodash import to the preApp.js the error message disappears

It is fixed, because both runtimes have `__webpack_require__.d` method, but it is bad fix

**Comment by alexander-akait** [comment]
in webpack v4 we don't have many optimizations, you can have three variants
- one entrypoint, here you can use `runtimeChunk` with any values for better long term cache
- multiple entrypoints on the same page, here you need set `runtimeChunk: 'true'`, otherwise you will have multiple runtime code
- multiple entrypoints on different pages, here you can use `runtimeChunk` with any values for better long term cache too

Don't forget you can use https://webpack.js.org/configuration/entry-context/#entry-descriptor, in most cases when you want to use multiple entry points and need runtimeChunk: 'true'` you want to use `dependOn`

**Comment by code1x1** [comment]
thanks

**Comment by code1x1** [comment]
thanks
