### ISSUE TITLE
Bundled code uses wrong version of a dependency

### ISSUE THREAD

**Issue by mbelsky** [webpack/webpack#13320]
# Bug report

Hey,

I found an issue with nested dependencies in my project. Lets imagine we have a structure like this:

```
├── README.md
├── node_modules
│   ├── awesome-complex-dependency
│   │   ├── node_modules
│   │   │   └── awesome-dependency # (v0.1.0)
│   │   │       ├── package.json
│   │   │       └── src
│   │   │           └── main.js
│   │   ├── package.json
│   │   └── src
│   │       └── main.js
│   ├── awesome-dependency # (v2.0.0)
│   │   ├── package.json
│   │   └── src
│   │       └── main.js
├── package-lock.json
├── package.json
├── src
│   └── index.js
└── webpack.config.js
```

And the `src/index.js` contains:

```
const awesomeDependency = require('awesome-dependency')
const awesomeComplexDependency = require('awesome-complex-dependency')
const awesomeComplexDependencyAlternativeRequire = require('awesome-complex-dependency/src/main.js')

console.log(`awesome-dependency output:`, awesomeDependency());
console.log(`awesome-complex-dependency output: `, awesomeComplexDependency());
console.log(`awesome-complex-dependency alternative require output: `, awesomeComplexDependencyAlternativeRequire());

```

**What is the current behavior?**

```
awesome-dependency output: awesome-dependency/v2.0.0
awesome-complex-dependency output:  I use awesome-dependency/v0.1.0
awesome-complex-dependency alternative require output:  I use awesome-dependency/v2.0.0
```

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Clone this repo: https://github.com/mbelsky/triage/tree/webpack-dependencies
1. Switch to `webpack-dependencies` branch
1. Run following commands:
```
npm install \
  && npm run copy-deps \
  && npm run build \
  && npm run test-bundle
```

**What is the expected behavior?**

```
awesome-dependency output: awesome-dependency/v2.0.0
awesome-complex-dependency output:  I use awesome-dependency/v0.1.0
awesome-complex-dependency alternative require output:  I use awesome-dependency/v0.1.0
```

**Other relevant information:**
webpack version:  5.36.2
Node.js version: v14.15.0
Operating System: MacOS 10.15.7
Additional tools: -

**Comment by alexander-akait** [comment]
No problems, you mark `awesome-complex-dependency` as external, but load `awesome-complex-dependency/src/main.js`, you can fix it using:
```
externals: {
    'awesome-dependency': 'commonjs awesome-dependency',
    'awesome-complex-dependency': 'commonjs awesome-complex-dependency',
    'awesome-complex-dependency/src/main.js': 'commonjs awesome-complex-dependency/src/main.js',
},
```

Alternative you can use `Function` https://webpack.js.org/configuration/externals/#function, this can be a little misleading, but you should set the each request in external, this allows flexible customization for any request

**Comment by mbelsky** [comment]
Alexander thanks for sharing this solution. This fixes the example's issue well. However how to be with real bundled nodejs apps? A typical nodejs app has hundreds dependencies and it will be a hard task to detect all wrong bundled dependencies and setup and actualise externals list for them.

**Comment by alexander-akait** [comment]
If you don't want write regexp (it is easy) and easy to find in your code, you can use https://github.com/liady/webpack-node-externals, after this all modules from `node_modules` will be external

**Comment by mbelsky** [comment]
Woops, I've missed webpack-node-externals handles this well. Thanks!
