### ISSUE TITLE
Migrating to Webpack 5 with Next.js 10.2 yields `Module not found: Can't resolve X` for custom env variables, and `Module not found: Can't resolve 'fs'`

### ISSUE THREAD

**Issue by Vadorequest** [webpack/webpack#13328]
# Bug report

I'm migrating my Next.js app from 10.1.x to 10.2.x and enabled Webpack 5.

But, I'm encountering a variety of Wbepack-related errors that make no sense to me and I'm stuck.

Next.js webpack migration is simple if we haven't customised the Webpack behavior, but we did and we're having issues migrating by hand.

> Our work is open source so we'll provide a full reproduction.

**What is the current behavior?**

> From https://github.com/vercel/next.js/discussions/23498#discussioncomment-705606

```
error - ./src/app/components/BrowserPageBootstrap.tsx:157:21
Module not found: Can't resolve '"v5.1.x-rc-next-v10.2"'
  155 |           app: {
  156 |             name: process.env.NEXT_PUBLIC_APP_NAME,
> 157 |             release: process.env.NEXT_PUBLIC_APP_VERSION_RELEASE,
      |                     ^
  158 |             stage: process.env.NEXT_PUBLIC_APP_STAGE,
  159 |             preset: process.env.NEXT_PUBLIC_NRN_PRESET,
  160 |           },

```

#### Here's how it works with Webpack 4:
- 1) We define `NEXT_PUBLIC_APP_VERSION_RELEASE` and `NEXT_PUBLIC_APP_BUILD_ID` through [custom webpack definitions](https://github.com/UnlyEd/next-right-now/blob/3ed6e669c0f8264678bdf6bbc26e8d014a4cba9f/next.config.js#L215-L222):

```js
    config.plugins.map((plugin, i) => {
      if (plugin.definitions) { // If it has a "definitions" key, then we consider it's the DefinePlugin where ENV vars are stored
        // Dynamically add some "public env" variables that will be replaced during the build through "DefinePlugin"
        // Those variables are considered public because they are available at build time and at run time (they'll be replaced during initial build, by their value)
        plugin.definitions['process.env.NEXT_PUBLIC_APP_BUILD_ID'] = JSON.stringify(buildId);
        plugin.definitions['process.env.NEXT_PUBLIC_APP_VERSION_RELEASE'] = JSON.stringify(APP_VERSION_RELEASE);
      }
    });
```

- 2) Then, we use those environment variables in the code: `const release = process.env.NEXT_PUBLIC_APP_VERSION_RELEASE;`

##### Using Webpack 5
When doing the same thing with Webpack 5, webpack seems to try to resolve a module based on the value of the environment variable. I don't know why it does that, maybe the way environment variables are defined is not valid anymore?

Regardless, the error message is really confusing.

Also, when disabling all environment variable generated through webpack, I get another error about `Module not found: Can't resolve 'fs'` and I'm still stuck there.

**If the current behavior is a bug, please provide the steps to reproduce.**

**Reproduction**:
1. `git clone https://github.com/UnlyEd/next-right-now.git`
1. `cd next-right-now && git checkout next-v10.2`
1. `cp .env.local.example .env.local` - Uses the default ENV variables when running locally
1. `yarn`
1. `yarn start` ==> **It will fail here**
1. Open `http://localhost:8888`

**`next.config.js:webpack`**:  https://github.com/UnlyEd/next-right-now/blob/3ed6e669c0f8264678bdf6bbc26e8d014a4cba9f/next.config.js#L208

**PR**: https://github.com/UnlyEd/next-right-now/pull/313

**What is the expected behavior?**

It should behave the same as webpack 4, by starting the local server.

**Other relevant information:**
webpack version:  5
Node.js version: v14.16.0/v15.x
Operating System: MacOS
Additional tools:

**Comment by Vadorequest** [comment]
I identified one of the issue is because I'm adding the environment variables in both the `DefinePlugin` and `ProvidePlugin`. They should only be added to `DefinePlugin`.

**Comment by Vadorequest** [comment]
https://github.com/UnlyEd/next-right-now/commit/e9a1f4d256f928ee9fc212a79ceb7844d7489dd7 fixed the `Module not found: Can't resolve '"v5.1.x-rc-next-v10.2"'` error.

But I'm still getting the `Module not found: Can't resolve 'fs'` error.

**Comment by Vadorequest** [comment]
I tried using the `fallback` too, but the result is the same. See https://github.com/UnlyEd/next-right-now/pull/313/files#diff-882b2c04b01b2e8b2cdcf1817c30ea503a8005f1c0d54cfff37053b6801fea85R189-R193

I don't think I can remove all modules using fs, it's not even an option, there are too many of them. And we need it, as part of our code runs on the server.

**Comment by ludofischer** [comment]
> I don't think I can remove all modules using fs, it's not even an option, there are too many of them. And we need it, as part of our code runs on the server.

Some modules have a separate browser entry point. Maybe wepack is not detecting it for some reason? I think that if code running in the browser ended up calling the `fs` module, it would not work even with a fallback.

**Comment by Vadorequest** [comment]
You're right. But that's not the case, the project was working fine using Webpack 4 and now it doesn't compile using webpack 5. So, I rather assume it's a misconfiguration rather than a code error.

Basically, the old way of disabling `fs` doesn't work anymore and I don't know how I'm supposed to configure it now. Using `fallback` didn't work out.

**Comment by Vadorequest** [comment]
The `fs` error was related to the `winston` module. By removing it from the project (used by 2 dependencies) it fixed the Webpack issue. Thanks for the feedback, it helped me figuring it out.

Now, I only need to find a proper replacement for this module. 😅 

```
error - ./node_modules/winston/dist/winston/tail-file.js:9:0
Module not found: Can't resolve 'fs'

```

I wish the webpack error message could have been a bit more obvious and had told me the `winston` package is not properly configured or something like this. It did tell me about winston, but I assumed it was webpack-related and not winston-related.

**Comment by Vadorequest** [comment]
I eventually managed to drop winston by using https://github.com/UnlyEd/simple-logger.

**Comment by AbdullahG** [comment]
I have the same issue 

I am using "fs" module in some files in the project and I cannot build the project with nextjs v11 and webpack-5

`"resolve.fallback.fs": "false"` didnt work for me too
