### ISSUE TITLE
Setting node.__dirname to false doesn't work with ffi-napi, ref-napi libraries with electron js

### ISSUE THREAD

**Issue by raviSussol** [webpack/webpack#13329]
# Bug report

**What is the current behavior?**
Using webpack in the electron js app I can't import native module libraries like `ffi-napi`, `ref-napi`, etc in my application. Libraries like those generally expects node's `__dirname` to set as global. Thus, setting `node: {__dirname: true}` would work in my app but in the `production` built it throws a runtime error:

```
Error: No native build was found for platform=darwin arch=x64 runtime=electron abi=87 uv=1 libc=glibc node=14.16.0 electron=12.0.6 webpack=true
```

The same above error would throws if I change/remove `node:{__dirname: false}` or `node` property itself from the webpack config.

**If the current behavior is a bug, please provide the steps to reproduce.**
I'm not sure on this whether its a bug or not. But to reproduce the scenario here's my example [repo](https://github.com/raviSussol/electron-webpack-native-module-example) which can show the issue in more details. Basically,
##### to reproduce an error
- start the app by `npm start`
- then an error would shown up

##### to get working
- change the `__dirname` to `true` in the `webpack.config.js` and again
- start the app by `npm start`
- now it runs OK. To confirm if native module `ffi-napi`, `ref-napi` are working properly - goto View > Toggle Developer Tools and in the console tab = `Add: 8`

**What is the expected behavior?**
If I need to set `node:{__dirname: true}` in this case (which works in the `development` mode) then the same behavior is expected to be working in the `production` mode (in the installer). Otherwise, if there is/are other work around to fix then still the expectation is same as to the `development` mode at the moment.

**Other relevant information:**
webpack version:  ^5.37.0
Node.js version: 14.16.0
Operating System: macOS 10.14.6
Additional tools: ffi-napi ver. ^4.0.3, ref-napi ver. ^3.0.2, webpack-cli ver. ^4.7.0, electron ver. ^12.0.7

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by formatting your issue and we will reopen.

Don't use this:
```
 node: {
    __dirname: false,
    __filename: false
  }
```

`target` understand how to work with this.

**Comment by alexander-akait** [comment]
You can format this issue as bug report or create a new and ping me

**Comment by raviSussol** [comment]
Thanks @alexander-akait I have now updated this issue with an appropriate bug template. Please have a look now.

**Comment by alexander-akait** [comment]
Why you set `node: { __dirname: false }`? Don't do it, the `target` option already set right values for `node`. `production` enable optimizations, so some part of code can be removed and simplified, so it can work

**Comment by raviSussol** [comment]
@alexander-akait setting `target: 'node'` would not work in the electron app. It throws an error:
```
Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
```

And I've tried several times deleting and re-installing the node_modules in the app but not working at all.
I've attached my example repo above. Here: https://github.com/raviSussol/electron-webpack-native-module-example
Maybe you can try setting `target: 'node'` and then run the app?

**Comment by alexander-akait** [comment]
hm, yes, you are right `target: 'node'` is not working and it is expected, we set `__dirname: mock` for all cases except `node` https://github.com/webpack/webpack/blob/master/lib/config/defaults.js#L884

The problem here is that `node-gyp-build` try to search file and don't found it, because it is bundled code and be in `dist` directory, not in `node_modules` (in my case it is `/home/akait/projects/electron-webpack-native-module-example/dist`). No webpack problem here, you need copy file to `dist`. Open `node_modules/node-gyp-build/index.js` and debug `load.path`.

We have the same limitation for Node.js add-ons, you need to use https://github.com/webpack-contrib/node-loader to working with them.

**Comment by raviSussol** [comment]
@alexander-akait Yeah its to do with node addon path that node gyp build is expecting for building. But the `__dirname` varies based on the webpack config and so does the electron as well. One definitely needed to settle by providing consistent path to the directory and I fixed by using electron's `getAppPath` function which always returns runtime app execution path. Node loader may not work in this case I think as libraries like `ffi-napi`, `ref-napi` themselves provide javascript apis to interact with their node addon files. However, did have to customized a bit of those libraries for me to get working. Thanks for the heads up though. I think this issue can be closed now.
