### ISSUE TITLE
Security Vulnerability pick up by Fortify Scan

### ISSUE THREAD

**Issue by nekyouto** [webpack/webpack#13321]
# Bug report

**What is the current behavior?**
Good Afternoon webpack team,

We were performing a scan on the webpack Javascript library and the Fortify application has picked up the following items that are discovered as vulnerabilities. 
(Reason being our project has imported this library as a dependency and part of our deliverable would requires the scanning of the full source code and identify/remove the vulnerable.)

(**Low**) Cross-Site Request Forgery
No of items picked by the Fortify Scan: **1**
Kindly refer to the following image, scanImage1
![scanImage1](https://user-images.githubusercontent.com/6581645/117429045-3620c700-af59-11eb-8d80-2f881737602b.png)

(**Low**) JavaScript Hijacking
No of items picked by the Fortify Scan: **1**
Kindly refer to the following image, scanImage1
![scanImage2](https://user-images.githubusercontent.com/6581645/117429232-6b2d1980-af59-11eb-8490-06057a990f8a.png)

(**Low**) Key Management: Null Encryption Key
No of items picked by the Fortify Scan: **1**
Kindly refer to the following image, scanImage3
![scanImage3](https://user-images.githubusercontent.com/6581645/117429503-b2b3a580-af59-11eb-9c1c-5800f35c15f1.png)

(**Low**) Poor Logging Practice: Use of a System Output Stream
No of items picked by the Fortify Scan: **Less than 10**
Kindly refer to the following image, scanImage4
![scanImage4](https://user-images.githubusercontent.com/6581645/117429789-f7d7d780-af59-11eb-821e-9b11288a4b8c.png)

(**Low**) Key Management: Null Encryption Key (Plugin: terser-webpack-plugin)
No of items picked by the Fortify Scan: **1**
Kindly refer to the following image, scanImage5
![scanImage5](https://user-images.githubusercontent.com/6581645/117434661-8a2eaa00-af5f-11eb-8bf1-d4aa07aa0902.png)

(**Low**) Poor Logging Practice: Use of a System Output Stream (Plugin: terser-webpack-plugin)
No of items picked by the Fortify Scan: **Less than 10**
Kindly refer to the following image, scanImage6
![scanImage6](https://user-images.githubusercontent.com/6581645/117436053-1f7e6e00-af61-11eb-9d9b-0ea87339d5a7.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
(Reason being our project has imported this library as a dependency and part of our deliverable would requires the scanning of the full source code and identify/remove the vulnerable.)

**Other relevant information:**
webpack version: 4.46.0
terser-webpack-plugin version: 4.2.3

**Comment by sokra** [comment]
These are no security problems
