### ISSUE TITLE
Webpack not actually bundling commonjs

### ISSUE THREAD

**Issue by wpitallo** [webpack/webpack#13327]
So when using this config webpack is not actually bundling any node modules and also some of the project files.

```javascript
import * as path from 'path'
import FilterWarningsPlugin from "webpack-filter-warnings-plugin"

export default {
  entry: './main.js', // or './src/index.ts' if TypeScript
  target: 'node',
  mode: 'production',
  output: {
    path: path.join(process.cwd(), '/dist'),
    filename: './main.min.js',
    libraryTarget: "commonjs-module"
  },
  experiments: { outputModule: true },
  optimization: {
    minimize: false
  },
  externalsType: "commonjs",
  externals: {
    path: 'path',
    stream: 'stream',
    http: 'http',
    crypto: 'crypto',
    module: 'module',
    fs: 'fs',
    zlib: 'zlib',
    net: 'net'
  },
  plugins: [
    new FilterWarningsPlugin({
      exclude: /Critical dependency: the request of a dependency is an expressio/
    })
  ]
}

```

Looking in the bundle you can see that its still trying to require node modules and project files:

```javascript
;// CONCATENATED MODULE: ./core/helpers/src/sql.js

const sql_require = (0,external_module_namespaceObject.createRequire)("file:///home/ubuntu/environment/server/_globalServer/core/helpers/src/sql.js")

const sql = sql_require("mssql")

class Sql {
    static newTransaction() {
        return new sql.Transaction( /* [pool] */ )
    }
}

;// CONCATENATED MODULE: ./core/helpers/index.js
```
And the bundle works, when reference it but if I delete my node modules or mssql node module it fails. Why is is not properly bundling these dependencies? 

**Other relevant information:**
webpack version:  5.36.2
Node.js version:  v14.16.1
Operating System:  Ubuntu 18

**Comment by ludofischer** [comment]
I imagine `outputModule: true` contradicts `libraryTarget: commonjs-module` since the first asks webpack to output an ES module. Compare https://webpack.js.org/configuration/output/#outputmodule and  https://webpack.js.org/configuration/output/#librarytarget-module

**Comment by alexander-akait** [comment]
If you want to mark all modules from `node_modules` as external you can use this package https://github.com/liady/webpack-node-externals. Please do not ignore questions in our issue template. I can't understand do you want bundle **all** packages or do you want to always use them using `require`, or do you want generate ES modules syntax

**Comment by sokra** [comment]
I think you are trying to use `import { createRequire } from "module"`, which is not supported.

But only guessing since you did not provide any source code.

**Comment by wpitallo** [comment]
@sokra 

Yes, that is exactly what is was.

import { createRequire } from 'module'
const require = createRequire(import.meta.url)
