### ISSUE TITLE
Failure to load loader from a scoped package when using pnpm

### ISSUE THREAD

**Issue by Kiskae** [webpack/webpack#13339]
# Bug report

**What is the current behavior?**

When using a loader from a scoped package (`@<scope>/<package>`)  through `pnpm`, the system will resolve the correct path, but then fail to find the module for usage as a loader:

```
Error: Cannot find module '<root>/node_modules/.pnpm/@next#react-refresh-utils@10.2.0_377debd9c60f944826ee39c3e9eaa238/node_modules/@next/react-refresh-utils/loader.js'
Require stack:
- <root>/node_modules/.pnpm/loader-runner@4.2.0/node_modules/loader-runner/lib/loadLoader.js
- <root>/node_modules/.pnpm/loader-runner@4.2.0/node_modules/loader-runner/lib/LoaderRunner.js
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Download these files into an empty directory:

`package.json` and `webpack.config.js`: https://gist.github.com/Kiskae/966f4a24e61cc6acc99b0155dea125cd

Run the following commands within that directory:

```bash
# enable default webpack behavior
touch src.js
# install node_modules through pnpm
npx pnpm@6.3.0 install
npx pnpm@6.3.0 run w
```

This should then produce a build error even though the source file is empty, since it cannot find the loader even though it resolved the path successfully.

**What is the expected behavior?**

Given that the loader is correctly resolved to a regular file on the filesystem, the loader loader should be able to find and execute it. The reason why it only affects scoped loaders is because of a change made in [`pnpm 6.0.0`](https://github.com/pnpm/pnpm/releases/tag/v6.0.0):

> The layout of the virtual store directory has changed (node_modules/.pnpm) to allow keeping cache in it:
>      All packages inside the virtual store directory are on the same depth. Instead of subdirectories, one directory is used with # instead of slashes.

This appears to then trigger an issue similar to #12156 since the package directory is remapped to `@<scope>#<package>`.

**Other relevant information:**
webpack version:  `webpack 5.36.2`
Node.js version: `v14.16.0`
Operating System: `Linux 5.11.0-7614-generic #15~1618626693~20.10~ecb25cd-Ubuntu SMP  x86_64 GNU/Linux`
Additional tools: `pnpm 6.3.0`

**Comment by Kiskae** [comment]
Spent some additional time looking into it and the problem seems to occur because `loader-runner` handles loader input differently based on the object type:

* If the loader is supplied as a `string`, split into path, query and fragment unless `?`/`#` are escaped by a nul byte. Then remove the nul bytes.
* If the loader is an `object`, the path is set to the `loader` value of the object as-is

`loader-runner` src: https://github.com/webpack/loader-runner/blob/6221befd031563e130f59d171e732950ee4402c6/lib/LoaderRunner.js#L65

What webpack appears to be doing is escaping the `loader` string but then providing it to `loader-runner` as an object which then gets passed directly to `require`. 
The fact that the `\x00` does not appears when printing strings normally makes the error misleading, since it is actually trying to find the path with the nul bytes included, but does not show them.

**Comment by alexander-akait** [comment]
Sorry, I can't reproduce the problem

**Comment by alexander-akait** [comment]
We need fix it here https://github.com/webpack/loader-runner/blob/master/lib/loadLoader.js#L19
```
// And same for `url.pathToFileURL(loader.path)`
var module = require(loader.path.replace(/\u0000/, ''));
```

**Comment by todortotev** [comment]
@alexander-akait Can I take this one?

**Comment by alexander-akait** [comment]
Yes, PR welcome

**Comment by sidverma32** [comment]
@alexander-akait Hi, If this is still pending ,then can i pick this and raise a PR?

**Comment by snitin315** [comment]
@sidverma32 Yes, feel free to send a PR.

**Comment by sidverma32** [comment]
Based on the above discussion and suggestion, updated the `loadLoader.js` file, 
@snitin315   Please review [57](https://github.com/webpack/loader-runner/pull/57) and let me know incase if any modification required.

**Comment by alexander-akait** [comment]
Still valid, I think, but need to test

**Comment by vankop** [comment]
I think this was fixed.. please check with latest webpack.
