### ISSUE TITLE
configured `resolve.alias` got errors

### ISSUE THREAD

**Issue by lonfger** [webpack/webpack#13365]
# Bug report

**What is the current behavior?**
![image](https://user-images.githubusercontent.com/13881250/117908940-ea30a200-b30b-11eb-95de-16a29004576f.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
1.  my webpack.config.js 
![image](https://user-images.githubusercontent.com/13881250/117909653-34665300-b30d-11eb-84e6-c7e96455feff.png)
2. in order for typescript to recognize ,I configured the `tsconfig.json` as following picture:
![image](https://user-images.githubusercontent.com/13881250/117909813-87400a80-b30d-11eb-94d5-22e0ea37c9c1.png)
3. Usage example with the alias path
 ![image](https://user-images.githubusercontent.com/13881250/117909961-b0f93180-b30d-11eb-813a-c803ca8fe495.png)
4. when start my project, got some errors 
![image](https://user-images.githubusercontent.com/13881250/117910124-f3bb0980-b30d-11eb-8909-0add60899498.png)
5. But when I replaced the alias path `import halo from '@/assets/1.jpg';` with `import halo from './assets/1.jpg';`, it compiled successfully.
![image](https://user-images.githubusercontent.com/13881250/117910238-29f88900-b30e-11eb-9717-4549695302ec.png)

**What is the expected behavior?**
I don’t know if I configured it wrong. Can someone tell me how to solve this problem or  configure  it in a right way.

**Other relevant information:**
webpack version:  5.36.2
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
    Memory: 4.91 GB / 15.71 GB
  Binaries:
    Node: 12.18.3 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - D:\Program Files\nodejs\yarn.CMD
    npm: 6.14.6 - D:\Program Files\nodejs\npm.CMD
  Managers:
    pip3: 20.2.3 - D:\Program Files\Python\Scripts\pip3.EXE
  Utilities:
    Git: 2.28.0. - D:\Program Files\Git\cmd\git.EXE
  IDEs:
    VSCode: 1.56.0 - D:\Program Files\Microsoft VS Code\bin\code.CMD
  Languages:
    Bash: 4.4.23 - D:\Program Files\Git\bin\bash.EXE
    Go: 1.15.8 - D:\Program Files\Go\bin\go.EXE
    Java: 1.8.0_281 - D:\Program Files\java\bin\javac.EXE
    Python: 3.9.2 - D:\Program Files\Python\python.EXE
  Databases:
    MongoDB: 4.4.5 - D:\Program Files\MongoDB4.4\bin\mongo.EXE      
  Browsers:
    Edge: Spartan (44.19041.906.0), Chromium (90.0.818.56)
    Internet Explorer: 11.0.19041.1
typescript: 4.2.4,
ts-loader: 9.1.2
bable-loader: 8.2.2

**Comment by alexander-akait** [comment]
`*` will never work, please read docs how alias works https://webpack.js.org/configuration/resolve/#resolvealias
