### ISSUE TITLE
Error: Cannot find module 'webpack-cli/bin/config-yargs'[webpack-cli] Error: Cannot find module 'webpack/lib/BasicEvaluatedExpression'

### ISSUE THREAD

**Issue by masx200** [webpack/webpack#13367]
# Bug report

**What is the current behavior?**
1.
[webpack-cli] Error: Cannot find module 'webpack/lib/BasicEvaluatedExpression'

2.
Error: Cannot find module 'webpack-cli/bin/config-yargs'

**What is the expected behavior?**

No errors should occur when using "webpack-cli" and "webpack-dev-server"

**Other relevant information:**
webpack version:  5.37.0
Node.js version: 14.15.4
Operating System:
 Linux localhost 4.19.113-perf-g8fa0212 #1 SMP PREEMPT Fri Apr 23 02:52:00 CST 2021 aarch64 Android
Additional tools:
https://github.com/masx200/webpack-react-vue-spa-awesome-config

**If the current behavior is a bug, please provide the steps to reproduce.**

~ $ cd webpack-react-vue-spa-awesome-config             ~/webpack-react-vue-spa-awesome-config 

$ cat package.json
{
    "types": "./release/config/webpack.config.d.ts",
    "type": "commonjs",
    "version": "2.8.2",
    "publishConfig": {
        "registry": "https://registry.npmjs.org/"
    },
    "bin": "./bin/index.js",
    "main": "./release/config/webpack.config.js",
    "scripts": {
        "start": "webpack-dev-server  --config ./release/config/webpack.config.js  --mode=development",
        "build": "webpack  --config ./release/config/webpack.config.js     --mode=production",
        "rollup": "rollup -c rollup.config.js",
        "prettier": "prettier --write **/*.ts *.md *.json **/*.js   *.js *.ts ./cli/src/*.js ./release/config/*.js **/*.css **/*.html",
        "test1": "node ./bin/index.js start",
        "test2": "node ./bin/index.js --mode=development",
        "test3": "node ./bin/index.js build"
    },
    "name": "@masx200/webpack-react-vue-spa-awesome-config",
    "license": "MIT",
    "browserslist": {
        "production": [
            ">0.2%",
            "not dead",
            "not op_mini all"
        ],
        "development": [
            "last 1 chrome version",
            "last 1 firefox version",
            "last 1 safari version"
        ]
    },
    "dependencies": {
        "@babel/core": "^7.14.0",
        "@babel/plugin-proposal-class-properties": "^7.13.0",
        "@babel/plugin-proposal-decorators": "^7.13.15",
        "@babel/plugin-syntax-dynamic-import": "^7.8.3",
        "@babel/preset-env": "^7.14.1",
        "@babel/preset-react": "^7.13.13",
        "@babel/runtime": "^7.14.0",
        "@types/html-webpack-plugin": "^3.2.5",
        "@types/mini-css-extract-plugin": "^1.4.3",
        "@types/node": "^15.0.2",
        "@types/optimize-css-assets-webpack-plugin": "^5.0.3",
        "@types/react": "^17.0.5",
        "@types/terser-webpack-plugin": "^5.0.3",
        "@types/webpack": "^5.28.0",
        "@types/workbox-webpack-plugin": "^5.1.6",
        "babel-loader": "^8.2.2",
        "babel-plugin-htm": "^3.0.0",
        "babel-plugin-named-asset-import": "^0.3.7",
        "babel-plugin-transform-runtime": "^6.23.0",
        "babel-preset-react-app": "^10.0.0",
        "banner-content-loader": "^0.1.1",
        "clean-webpack-plugin": "^4.0.0-alpha.0",
        "css-loader": "^5.2.4",
        "fast-sass-loader": "^2.0.0",
        "file-loader": "^6.2.0",
        "html-webpack-plugin": "^5.3.1",
        "json-loader": "^0.5.7",
        "less": "^4.1.1",
        "less-loader": "^8.1.1",
        "mini-css-extract-plugin": "^1.6.0",
        "node-sass": "^6.0.0",
        "optimize-css-assets-webpack-plugin": "^5.0.4",
        "postcss": "8.2.15",
        "postcss-flexbugs-fixes": "^5.0.2",
        "postcss-loader": "^5.2.0",
        "postcss-normalize": "^10.0.0",
        "postcss-preset-env": "^6.7.0",
        "postcss-safe-parser": "^5.0.2",
        "purgecss-webpack-plugin": "4.0.3",
        "purify-css": "^1.2.5",
        "purifycss-webpack": "^0.7.0",
        "react-app-polyfill": "^2.0.0",
        "react-hot-loader": "^4.13.0",
        "regenerator-runtime": "^0.13.7",
        "sass": "1.32.12",
        "style-loader": "^2.0.0",
        "terser": "^5.7.0",
        "terser-webpack-plugin": "^5.1.1",
        "to-string-loader": "^1.1.6",
        "uglifyjs-webpack-plugin": "^2.2.0",
        "unicode-loader": "^1.0.7",
        "url-loader": "^4.1.1",
        "vue-loader": "^15.9.7",
        "vue-style-loader": "^4.1.3",
        "vue-template-compiler": "^2.6.12",
        "webpack": "^5.37.0",
        "webpack-cli": "^4.7.0",
        "webpack-copyfiles-plugin": "^1.0.9",
        "webpack-deep-scope-plugin": "^1.6.2",
        "webpack-dev-server": "^3.11.2",
        "workbox-webpack-plugin": "^6.1.5",
        "worker-loader": "3.0.8"
    },
    "devDependencies": {
        "@rollup/plugin-babel": "5.3.0",
        "@rollup/plugin-commonjs": "^19.0.0",
        "@rollup/plugin-json": "^4.1.0",
        "@rollup/plugin-node-resolve": "^13.0.0",
        "acorn": "^8.2.4",
        "core-js-pure": "^3.12.1",
        "event-target-shim": "^6.0.2",
        "lodash": "^4.17.21",
        "minimist": "^1.2.5",
        "prettier": "^2.3.0",
        "react": "^16.13.1",
        "rollup": "^2.47.0",
        "rollup-plugin-babel": "^4.4.0",
        "rollup-plugin-terser": "^7.0.2",
        "serialize-javascript": "^5.0.1",
        "tslib": "2.2.0",
        "typescript": "^4.2.4",
        "vue": "^2.6.11",
        "yargs-parser": "20.2.7"
    },
    "repository": "https://github.com/masx200/webpack-react-vue-spa-awesome-config.git",
    "author": "masx200 <34191203+masx200@users.noreply.github.com>",
    "description": "极速、零配置的 web 应用打包工具, 同 时支持 react 和 vue 的单页面应用,提供开箱即用支持  Fast, zero-configuration web application packaging tool that supports both single-page applications for react and vue, out-of-the-box support， 基于 webpack4.x,同时支持 react 和 vue 的单页面应用 通用的 webpack 配置文件,提供开箱即用支持 ，您无需学习和配置许多构建工具。即时重新加载可帮 助您专注于开发。在部署时，您的捆绑包会自动优化",
    "peerDependencies": {
        "react": "16.13.1",
        "vue": "2.6.12"
    },
    "optionalDependencies": {
        "react": "17.0.2",
        "vue": "2.6.12"
    }
}
~/webpack-react-vue-spa-awesome-config 

$ yarn start
yarn run v1.22.10
warning package.json: "optionalDependencies" has dependency "react" with range "17.0.2" that collides with a dependency in "devDependencies" of the same name with version "^16.13.1"
warning package.json: "optionalDependencies" has dependency "vue" with range "2.6.12" that collides with a dependency in "devDependencies" of the same name with version "^2.6.11"
$ webpack-dev-server  --config ./release/config/webpack.config.js  --mode=development
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'webpack-cli/bin/config-yargs'
Require stack:
- /data/data/com.termux/files/home/webpack-react-vue-spa-awesome-config/node_modules/webpack-dev-server/bin/webpack-dev-server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/data/data/com.termux/files/home/webpack-react-vue-spa-awesome-config/node_modules/webpack-dev-server/bin/webpack-dev-server.js:65:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/data/data/com.termux/files/home/webpack-react-vue-spa-awesome-config/node_modules/webpack-dev-server/bin/webpack-dev-server.js'
  ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
~/webpack-react-vue-spa-awesome-config 

$ yarn build
yarn run v1.22.10
warning package.json: "optionalDependencies" has dependency "react" with range "17.0.2" that collides with a dependency in "devDependencies" of the same name with version "^16.13.1"
warning package.json: "optionalDependencies" has dependency "vue" with range "2.6.12" that collides with a dependency in "devDependencies" of the same name with version "^2.6.11"
$ webpack  --config ./release/config/webpack.config.js     --mode=production
输入的参数:
[
    "/data/data/com.termux/files/usr/bin/node",
    "/data/data/com.termux/files/home/webpack-react-vue-spa-awesome-config/node_modules/.bin/webpack",
    "--config",
    "./release/config/webpack.config.js",
    "--mode=production"
]
解析的参数:
{
    "mode": "production"
}

webpack config filename : /data/data/com.termux/files/home/webpack-react-vue-spa-awesome-config/release/config/webpack.config.js

working directory : /data/data/com.termux/files/home/webpack-react-vue-spa-awesome-config

webpack mode : production

[webpack-cli] Failed to load '/data/data/com.termux/files/home/webpack-react-vue-spa-awesome-config/release/config/webpack.config.js' config
[webpack-cli] Error: Cannot find module 'webpack/lib/BasicEvaluatedExpression'
Require stack:
- /data/data/com.termux/files/home/webpack-react-vue-spa-awesome-config/node_modules/webpack-copyfiles-plugin/index.js
- /data/data/com.termux/files/home/webpack-react-vue-spa-awesome-config/release/config/webpack.config.js
- /data/data/com.termux/files/home/webpack-react-vue-spa-awesome-config/node_modules/webpack-cli/lib/webpack-cli.js
- /data/data/com.termux/files/home/webpack-react-vue-spa-awesome-config/node_modules/webpack-cli/lib/bootstrap.js
- /data/data/com.termux/files/home/webpack-react-vue-spa-awesome-config/node_modules/webpack-cli/bin/cli.js
- /data/data/com.termux/files/home/webpack-react-vue-spa-awesome-config/node_modules/webpack/bin/webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (/data/data/com.termux/files/home/webpack-react-vue-spa-awesome-config/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/data/data/com.termux/files/home/webpack-react-vue-spa-awesome-config/node_modules/webpack-copyfiles-plugin/index.js:26:34)
    at Module._compile (/data/data/com.termux/files/home/webpack-react-vue-spa-awesome-config/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/data/data/com.termux/files/home/webpack-react-vue-spa-awesome-config/node_modules/webpack-copyfiles-plugin/index.js',
    '/data/data/com.termux/files/home/webpack-react-vue-spa-awesome-config/release/config/webpack.config.js',
    '/data/data/com.termux/files/home/webpack-react-vue-spa-awesome-config/node_modules/webpack-cli/lib/webpack-cli.js',
    '/data/data/com.termux/files/home/webpack-react-vue-spa-awesome-config/node_modules/webpack-cli/lib/bootstrap.js',
    '/data/data/com.termux/files/home/webpack-react-vue-spa-awesome-config/node_modules/webpack-cli/bin/cli.js',
    '/data/data/com.termux/files/home/webpack-react-vue-spa-awesome-config/node_modules/webpack/bin/webpack.js'
  ]
}
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
~/webpack-react-vue-spa-awesome-config $

**Comment by masx200** [comment]
> _For maintainers only:_
> 
> * [ ]  webpack-4
> * [x]  webpack-5
> * [x]  bug
> * [x]  critical-bug
> * [ ]  enhancement
> * [ ]  documentation
> * [ ]  performance
> * [ ]  dependencies
> * [ ]  question

**Comment by alexander-akait** [comment]
Update webpack-cli to the latest version and change `"start": "webpack-dev-server --config ./release/config/webpack.config.js --mode=development",` to `"start": "webpack serve --config ./release/config/webpack.config.js --mode=development",`

In future please use github repos, your problem is not readable

**Comment by alexander-akait** [comment]
Also please report problem in `webpack-copyfiles-plugin` for webpack v5 compatibility, but I recommend to use https://github.com/webpack-contrib/copy-webpack-plugin
