### ISSUE TITLE
Module dependencies set in buildModule hook are getting reset during the build 

### ISSUE THREAD

**Issue by 7rulnik** [webpack/webpack#13361]
# Bug report

**What is the current behavior?**

I'm trying to modify the source of the module based on [this comment](https://github.com/storybookjs/storybook/issues/14118#issuecomment-802711917)

So my code looks like this:
```js
compilation.hooks.buildModule.tap('MyPlugin', (module) => {
	module.addDependency(new MyDependency())
})
```

But it's doesn't work because in the build method webpack resets dependencies of module https://github.com/webpack/webpack/blob/2151f56ae73b35722c56432c9b34820626d72e53/lib/NormalModule.js#L879

**If the current behavior is a bug, please provide the steps to reproduce.**

Clone https://github.com/7rulnik/webpack-repro-13361 and run `yarn && yarn webpack`

**What is the expected behavior?**

I don't quite follow the logic of `clearDependenciesAndBlocks`, but I thing that it should contain check for `dependencies.length`

**Other relevant information:**
webpack version: 5.36.2
Node.js version: v14.15.4
Operating System: MacOS 11.3 M1

**Comment by alexander-akait** [comment]
Please prefer to use `Discussions` in future for questions, otherwise we will not be able to fix real problems in a timely manner. What do you want achieve, can you provide more information? You can use `parser.hooks` to handle something and add dependencies

**Comment by 7rulnik** [comment]
@alexander-akait the only reason why I decided to create an issue, not a question in discussions, because that implementation based on Tobias's own comment. Also, it works in webpack 4 and I didn't find anything related to this change in changelog. So this is why I raised this issue.

I also understand that this can be worked around by adding a dependency to `parser.hooks`, for example,` ConstDependency`.

**Comment by sokra** [comment]
I think I was wrong. `buildModule` doesn't work. You need to use parser hooks to add dependencies...

**Comment by 7rulnik** [comment]
@sokra so if it's intended behaviour let's close this issue?

**Comment by alexander-akait** [comment]
@7rulnik I think yes, `parser.hooks` is good place for dependencies

**Comment by michenly** [comment]
For anyone who ran into similar problem and wondering how `parser.hooks` can be use to modify module.
The trick is accessing module using `parser.state.module` inside a `parser.hooks.program.tap(...)`
