### ISSUE TITLE
TypeError: this.generator.getConcatenationBailoutReason is not a function

### ISSUE THREAD

**Issue by nuragic** [webpack/webpack#13370]
# Bug report

**What is the current behavior?**

When I run my build I get the following exception:

```
TypeError: this.generator.getConcatenationBailoutReason is not a function
    at NormalModule.getConcatenationBailoutReason (webpack/lib/NormalModule.js:1018:25)
    at webpack/lib/optimize/ModuleConcatenationPlugin.js:132:36
    at Hook.eval [as callAsync] (eval at create (tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (tapable/lib/Hook.js:18:14)
    at webpack/lib/Compilation.js:2408:36
    at Hook.eval [as callAsync] (eval at create (tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (tapable/lib/Hook.js:18:14)
    at Compilation.seal (webpack/lib/Compilation.js:2399:27)
    at webpack/lib/Compiler.js:1094:20
    at webpack/lib/Compilation.js:2216:4

```

**If the current behavior is a bug, please provide the steps to reproduce.**

I'm in the process of (trying to) migrate from v4 to v5; I have a custom config, similar to the one from create-react-app (in fact the project was created with it, but later ejected); I don't think it would be very useful to share my config _right now_ because I still probably have things to change; however, this is like a blocker, because it's a Webpack internal TypeError. 

**What is the expected behavior?**

I guess that it should print  the result of "getConcatenationBailoutReason" to the console... 

**Other relevant information:**
webpack version:  5.37.0
Node.js version:  16.1.0
Operating System: iOS 11.3.1

Thanks for your patience. 
Cheers!

**Comment by alexander-akait** [comment]
> If the current behavior is a bug, please provide the steps to reproduce.

> I'm in the process of (trying to) migrate from v4 to v5; I have a custom config, similar to the one from create-react-app (in fact the project was created with it, but later ejected); I don't think it would be very useful to share my config right now because I still probably have things to change; however, this is like a blocker, because it's a Webpack internal TypeError.

Please provide configuration, nobody can't help

**Comment by alexander-akait** [comment]
You have incompatibility plugin with invalid API

**Comment by nuragic** [comment]
Ok many thanks for the hint. I'll try to fix all the deprecation warnings about the plugins first. However, I think you should consider to convert those warning to just errors, because if v5 breaks plugins then it's pointless to follow with any migration... there're lot of plugins which are not compatible with v5 and for many of them there's no response from authors about supporting the new API. Just a suggestion... thanks again!

**Comment by alexander-akait** [comment]
We are trying to avoid many breaking change between 4 and 5, but in some cases it is impossible

**Comment by nuragic** [comment]
@alexander-akait FYI I just managed to remove all the DeprecationWarning, but the error still persist... the stack trace is different tho; the error is originated from `html-webpack-plugin/lib/cached-child-compiler.js:237:53`. I'll try to investigate more on that… it's weird because I'm using the latest version of this plugin (5.3.1). In the meantime I try to invoke @jantimon hoping to get some more hint. 😄

**Comment by nuragic** [comment]
Another update: if I remove html-webpack-plugin from my build config the error is still there, the stack trace is the one I posted above... so this is not something related to this plugin (or any plugin)... I guess it's something that Webpack doesn't like about my config? ¯\_(ツ)_/¯ If I can set up a repo to enable reproduce it I'll reopen. Thanks!

**Comment by HughG-50** [comment]
@nuragic were you able to solve this issue? I currently experiencing the same problem.

**Comment by nuragic** [comment]
Hey! Nope sorry, I gave up on doing the migration for now... if you finally sort it out please let it know! Thanks!

**Comment by nuragic** [comment]
If you use create react app, I think they were already done doing the switch, check their repo.
