### ISSUE TITLE
html-loader with Webpack v5 is unable to load html template

### ISSUE THREAD

**Issue by ManoharChennuru** [webpack/webpack#13386]
# Bug report

**What is the current behavior?**
I'm trying to replace my old templateCache way of loading templates favoring html-loader, which is unable to load them, on build webpack is saying "currently no loaders are configured to process this file"

ERROR in ./src/app/views/templates/dataGrid.html 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, 

```
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
  > <div class="gridPanel">
  |     <div class="gridContainer">
  |         <div class="dataGridHeader">
```

**If the current behavior is a bug, please provide the steps to reproduce.**

I'm trying to load AngularJs app templates(html) using **html-loader + webpack 5**. Many people junked templateCache favoring html-loader. But in my case I can't really get it work. 

I even tried raw-loader, angularjs-template-loader and ngtemplate-loader too. But webpack always complaining about the loader.

**Error**:
"Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders"
```
  > <div class="panel">
  |     <div class="panelContent gridContainer">
  |         <div class="dataGridHeader">

```
**Here is is my weback.config.js:**
```
module:{
  rules: [
           {
                test: /\.html$i/,
                use: 'html-loader'
         },
  ]
}
```

**Directive**:

```
const directive = {
        restrict: "E",
        template: require("ROOT/app/views/templates/dataGrid.html"),
        controller: dataGridController,
        controllerAs: "vm",
        bindToController: true
  }
 return directive;
``` 

**package.json:**

```
Portion of devDependencies:

"devDependencies": {
    "@babel/cli": "^7.0.0",
    "@babel/core": "^7.11.1",
    "@babel/plugin-syntax-dynamic-import": "^7.8.3",
    "@babel/preset-env": "^7.11.0",
    "angularjs-template-loader": "^0.1.2",
    "babel-loader": "^8.0.0",
    "html-loader": "^2.1.2",
    "ngtemplate-loader": "^2.1.0",
    "raw-loader": "^4.0.2",
    "speed-measure-webpack-plugin": "^1.5.0",
    "webpack": "^5.36.2",
    "webpack-cli": "^4.7.0",
    "webpack-dev-server": "^3.11.2",
    "webpack-merge": "^5.7.3"
  }

```

Anybody facing this issue?

**What is the expected behavior?**
Should e able to import templates dynamically

**Other relevant information:**
webpack version:  v5.7.0
Node.js version: v10.18.0
Operating System: windows 10
Additional tools:

**Comment by alexander-akait** [comment]
@webpack-bot move to webpack-contrib/html-loader
