### ISSUE TITLE
Add callbacks before and after webpack built files in watch mode

### ISSUE THREAD

**Issue by Omnivoreye** [webpack/webpack#13390]
## Feature request

**What is the expected behavior?**
It is possible to configure webpack in such a way, that callbacks are executed before rebuild and after rebuild in watch mode.

**What is motivation or use case for adding/changing the behavior?**
It is not clear if webpack has already built, or it is still building and the terminal output is from the previous build. Adding a callback that prints for example 'Build started' could resolve this.

**How should this be implemented in your opinion?**
Add new possible values to watchOptions:
```
    watchOptions: {
      beforeRebuild: () => console.log('Build started')
      afterRebuild: () => console.log('Build finished')
    },
```

**Are you willing to work on this yourself?**
 maybe, when i find time

**Comment by ellenmartin22** [comment]
> 
> 
> *For maintainers only:*
> 
> * [x] webpack-4
> * [x] webpack-5
> * [x] bug
> * [x] critical-bug
> * [x] enhancement
> * [x] documentation
> * [y] performance
> * [x] dependencies
> * [x] question

**Comment by ellenmartin22** [comment]
> 
> 
> *For maintainers only:*
> 
> * [x] webpack-4
> * [x] webpack-5
> * [x] bug
> * [x] critical-bug
> * [x] enhancement
> * [x] documentation
> * [x] performance
> * [x] dependencies
> * [x] question

**Comment by ellenmartin22** [comment]
> 
> 
> *For maintainers only:*
> 
> * [x] webpack-4
> * [x] webpack-5
> * [x] bug
> * [x] critical-bug
> * [x] enhancement
> * [x] documentation
> * [x] performance
> * [x] dependencies
> * [x] question

**Comment by ellenmartin22** [comment]
> 
> 
> *For maintainers only:*
> 
> * [ ] webpack-4
> * [ ] webpack-5
> * [ ] bug
> * [ ] critical-bug
> * [ ] enhancement
> * [ ] documentation
> * [ ] performance
> * [ ] dependencies
> * [ ] question

**Comment by ellenmartin22** [comment]
> 
> 
> *For maintainers only:*
> 
> * [x] webpack-4
> * [x] webpack-5
> * [x] bug
> * [x] critical-bug
> * [x] enhancement
> * [x] documentation
> * [x] performance
> * [x] dependencies
> * [x] question

**Comment by ellenmartin22** [comment]
ellenmartin22 ***@***.***> schrieb am So. 16. Mai 2021 um
14:04:

**Comment by ellenmartin22** [comment]
#13388

**Comment by ellenmartin22** [comment]
> _For maintainers only:_
> 
> * [x]  webpack-4
> * [ ]  webpack-5
> * [ ]  bug
> * [ ]  critical-bug
> * [ ]  enhancement
> * [ ]  documentation
> * [ ]  performance
> * [x]  dependencies
> * [x]  question

**Comment by ellenmartin22** [comment]
?

**Comment by alexander-akait** [comment]
Before - https://github.com/webpack/webpack/blob/master/lib/Compiler.js#L166
After - https://github.com/webpack/webpack/blob/master/lib/Compiler.js#L131

Small example for simple build/watch/changed files you can find here https://github.com/webpack/webpack-cli/blob/master/packages/webpack-cli/lib/plugins/CLIPlugin.js#L48
