### ISSUE TITLE
Tree shaking of unused dependencies not working

### ISSUE THREAD

**Issue by BakoviDagi** [webpack/webpack#13396]
# Bug report

**What is the current behavior?**
When a file is marked as `sideEffects: false`, an unused dependency that isn't marked side-effect-free is still included in the bundle. I can kind of see why this would be the case, but presumably somebody who's gone through their project to find what files have side-effects also looked at the imports it has to see if those affect things as well.

**If the current behavior is a bug, please provide the steps to reproduce.**
I have an NPM package with `sideEffects: false` that has a lot of shared utils for our various micro-frontends that we're creating. One of these utils imports `lodash` and uses it in some exported functions but not others:
`my-util.js`
```js
import { someLodashFunc } from 'lodash';
export function unused () {
  return someLodashFunc();
}
export function noLodash () {
  return 'something';
}
```

I also have a micro-frontend that's importing this util and only using a lodash-free function:
`app.js`
```js
import { noLodash } from '@company/uikit/src/my-util';

noLodash();
```

When I build this, I have `lodash` included in my bundle. After a bunch of debugging, I figured out that if I update `lodash`'s `package.json` to include `sideEffects: false`, then `lodash` is dropped from my bundle.

**What is the expected behavior?**
A file that is marked as side-effect free should be treated as such, even when it comes to its imports that may not explicitly be so.

I'm aware that switching to `lodash-es` would fix the problem in this specific case, but a couple of my other dependencies still use `lodash`, so I end up with both `lodash` and `lodash-es` included in the bundle

**Other relevant information:**
webpack version:  5.28.0
Node.js version: v14.16.0
Operating System: Windows 10
Additional tools:

**Comment by alexander-akait** [comment]
Please create reproducible test repo

**Comment by BakoviDagi** [comment]
Nevermind, I was able to fix this by splitting `my-util.js` into mutliple files and exporting them all in an index.js:
`my-util/_unused.js`:
```js
import { someLodashFunc } from 'lodash';
export function unused () {
  return someLodashFunc();
}
```
`my-util/_noLodash.js`:
```js
export function noLodash () {
  return 'something';
}
```
`my-util/index.js`:
```js
export { unused } from './_unused';
export { noLodash } from './_noLodash';
```

And then in my project the import would be the same:
`app.js`:
```js
import { noLodash } from '@company/uikit/src/my-util';

noLodash();
```
