### ISSUE TITLE
Webpack 5 : Invalid chunkIds/moduleIds are generated.

### ISSUE THREAD

**Issue by m301** [webpack/webpack#13398]
# Bug report

**What is the current behavior?**

When using Webpack `5.37.0` (this might exist in previous versions), moduleIds which should be numerical are contain character, these incident occur randomly, So far I haven't seen any pattern or identifier which causes this issue, 
```
var chart_Ring_20_js = __webpack_require__(1309);
var chart_Ring_16_js = __webpack_require__(1310);
var chart_River_32_js = __webpack_require__(2ff4);  // This is invalid identifier 
var chart_River_24_js = __webpack_require__(1312);
var chart_River_20_js = __webpack_require__(1313);
```

**If the current behavior is a bug, please provide the steps to reproduce.**

In development everything works fine, in production following config is used. initially, I left with the default ids config but it produced the same issue. 

I would have created a reproducible test repo, but it is hard to reproduce in my project as well, it is just random.  I can help in debugging if the direction is provided. 

```
  optimization: {
    // https://github.com/webpack/webpack-dev-server/issues/2792
    runtimeChunk: 'single',
    removeEmptyChunks: true,
    mergeDuplicateChunks: true,
    chunkIds: 'natural',
    moduleIds: 'natural',

    // runtimeChunk: 'single', // enable "runtime" chunk
    // Uncomment below in production mode
    splitChunks:  {
      chunks: 'initial',
      maxInitialRequests: 1,
      maxAsyncRequests: 6,
      minSize: 10 * 10000,
      cacheGroups: {
        styles: {
          name: 'styles',
          test: (m, c, entry = 'index') => {
            return m.constructor.name === 'CssModule';
          },
          chunks: 'all',
          minChunks: 1,
          reuseExistingChunk: true,
          enforce: true,
        },
      
        commons: {
          name: "commons",
          chunks: "initial",
          minChunks: 1,
          minSize: 0
        },
      }
    },
    usedExports: true,
    minimize: true, // there is no other minimizer
}

```

**What is the expected behavior?**

The Id's should be valid or if they are string they should be quoted.

**Other relevant information:**
webpack version:  5.37.0
Node.js version: 
Operating System: 
Additional tools:

**Edit**

I logged generated module ids https://github.com/webpack/webpack/blob/master/lib/ids/DeterministicModuleIdsPlugin.js#L57 by adding `console.log(`${module} ${id}`)`

For one of the case 
```
Module[11133: /mnt/micro/...../src/vue/AddRoute.vue|408156b2ee344bc8e49390c2b00667e6] 95264 
Module[11134: /mnt/micro/...../src/vue/AddVendor.vue|4f71055da1eb41653bf7a0a85fb31627] 58829
```

which generated below code,  the `AddVendor` method has valid import and chunk id, probably it has something to do with post processing of ID's

```
var AddRoute = function AddRoute() {
  return __webpack_require__.e(/* import() */ 1086).then(__webpack_require__.bind(__webpack_require__, 75f54));
};
var AddVendor = function AddVendor() {
  return __webpack_require__.e(/* import() */ 5858).then(__webpack_require__.bind(__webpack_require__, 58829));
};
```

**Comment by sokra** [comment]
Not sure. I would guess your `output.hashDigestLength` is 5 and it conflicts with your module ids. Increase the hash length to make it unique enough.

**Comment by m301** [comment]
I haven't enforced hash digest length explicitly. The doc says it is set to 20 by default https://webpack.js.org/configuration/output/#outputhashdigestlength.


```
 cache: true,
  stats: isDevelopment ? 'normal' : 'errors-warnings',
  mode: isDevelopment ? 'development' : 'production',
  target: 'web',
  entry: entry,
  output: {
    chunkFilename: '[name].[contenthash:6].js', //: '[id].[chunkhash].chunk.js',
    filename: '[name].[contenthash:6].js',
    path: buildPath,
    publicPath,
  },
  ```

**Comment by alexander-akait** [comment]
Change `[contenthash:4]` on `[contenthash]`

**Comment by m301** [comment]
Yes, I changed that, infact you can see in my previous post history. 

```
output: {
    chunkFilename: '[name].[contenthash:6].js', //: '[id].[chunkhash].chunk.js',
    filename: '[name].[contenthash:6].js',
    path: buildPath,
    publicPath,
    hashDigestLength: 20,
  },
```

the builds are working fine, I will monitor to see if this issue comes up again. 

Output file name shouldn't impact the chunk id generated right ?

**Comment by alexander-akait** [comment]
> Output file name shouldn't impact the chunk id generated right ?

Doesn't impact on chunk id generated.

Avoid using very less `contenthash`, default value is `20` and it is good by default

**Comment by m301** [comment]
@alexander-akait on reducing content hash length, it due to hash collision it creates circular dependency  producing something like this. 
```
[webpack-cli] HookWebpackError: Circular hash dependency ab (views.ab.js) -> 51 (scss.51.js) -> 65 (3969.65.js) -> 69 (945.69.js) -> 94 (9785.94.js) -> 87 (preact.87.js) -> 71 (6048.71.js) -> 04 (2762.04.js) -> 62 (5479.62.js) -> 79 (350.79.js) -> ec (9891.ec.js,5209.ec.js) -> 29 (9954.29.js) -> 95 (6581.95.js,7398.95.js) -> 65 (3969.65.js)
```


I tested previous config with `[contenthash:4]` with `hashDigestLength: 20,` as suggested by @sokra , The builds are working fine. I will confirm it next few days if this is the appropriate solution.

**Comment by m301** [comment]
As suggested by @alexander-akait Avoid using very less `contenthash`. It will create problems.

**Comment by sokra** [comment]
> Output file name shouldn't impact the chunk id generated right ?

In theory not, but there are rare cases when the hash of the file is contained in code of the file this will cause problems with the hash replacing. With the default hash length this is super unlikely, but with short hashes you will run into that. You can either choose a longer hash or disable `optimization.realContentHash`.

**Comment by m301** [comment]
@sokra I think we should add that in documentation, if you would like I can submit a PR for that.

https://webpack.js.org/configuration/output/

May be in here or in table we should add comment to avoid smaller hash, as sometimes just to make things fancy people will use small hashes
```
The length of hashes ([hash], [contenthash] or [chunkhash]) can be specified using
```

Or may we should show a warning in hash, as this error in minified JS is really hard to narrow down. 
Initially, I disabled few libraries to solve the problem, I thought it's problem with terser or babel.
