### ISSUE TITLE
Webpack resolve.alias cannot support react/addons

### ISSUE THREAD

**Issue by yujiangshui** [webpack/webpack#1339]
If I don't want to parse a library, I setup resolve.alias and module.noParse in webpack.config.js.

When I use both react and react/addons in it I ran in to a problem.

Webpack just generates a url for 'react' like this:

`.../react/react.js`

This url is correct and set by me. But when I need to use react/addons, it generates a url like this `.../react/react.js/addons`, which is supposed to be `..../react/addons.js`.  

This demo show the issue: https://github.com/yujiangshui/webpack-vendor-bug-demo

**Comment by brabadu** [comment]
On one of my projects I ended up using alias
```
      alias: {
            "react": "react/addons",
        }
```

And making sure anything that wants react with addons still requires 'react', not 'react/addons'. 

This doesn't work with some third-party packages like (e.g. react-routing). So in other project, where I have react-routing, I left react to be parsed by webpack.

**Comment by ctumolosus** [comment]
Have you tried using `$` in the `alias` key?

> Expected is a object with keys being module names. The value is the new path. It’s similar to a replace but a bit more clever. If the the key ends with $ only the exact match (without the $) will be replaced.
http://webpack.github.io/docs/configuration.html#resolve-alias

```js
{
    resolve: {
        alias: {
            'react$': path.resolve(__dirname, './node_modules/react/dist/react.min.js')
        }
    }
    loaders: {
        noParse: [
            path.resolve(__dirname, './node_modules/react/dist/react.min.js')
        ]
    }
}
```

**Comment by rottmann** [comment]
@brabadu Funny solution(?):

```
    module: {
        ...
        noParse: [
            path.resolve(baseDir, 'node_modules/react/dist/react-with-addons.js')
        ]
    },
    resolve: {
        ...
        alias: {
            'react$'      : path.resolve(baseDir, 'node_modules/react/dist/react-with-addons.js'),
            'react/addons': path.resolve(baseDir, 'node_modules/react/dist/react-with-addons.js'),
            'react/lib'   : 'react',
            'react/dist'  : 'react'
        }
```

Worked with react-router 1.0.0-rc1.
I use the non minified versions because i use the UglifyJsPlugin.

**Comment by brabadu** [comment]
That might actually work. Thanks @rottmann, I'll try that.

**Comment by vyorkin** [comment]
@brabadu @yujiangshui have you figured it out? does @rottmann's solution it work for you?

**Comment by yujiangshui** [comment]
React 0.14 put addons out, and recommend require special addon to use. So this problem will not be a problem.

@vyorkin you can update your React to figure out.

Thanks for your comment @brabadu @ctumolosus @rottmann .

**Comment by szarouski** [comment]
@vyorkin , I run into the same issue with require. How did you resolve it?

**Comment by szarouski** [comment]
It looks like there is almost [no benefit](https://github.com/survivejs/webpack/issues/35#issuecomment-150988500) to add react-dom to noParse. So nevermind.
