### ISSUE TITLE
Relative `alias` resolution for monorepos

### ISSUE THREAD

**Issue by Domiii** [webpack/webpack#13391]
## Feature request

In monorepos, use of "common packages" is widespread. Files of these common packages can be referenced directly from other packages, and be put together into one `webpack.config.js`, with a single output.

However, different packages might have common aliases, which should resolve differently per package. Example: the `src` alias should point to the package's `src` folder.

## What is motivation or use case for adding/changing the behavior?

Example:

* 2 packages: `App` and `common-lib`.
* There is only one `webpack.config.js` in the project. It is to build `App`.
  * `common-lib` does not need to be built independently. It is only to be used in conjunction with other modules.
* Files in `App` can directly import files from `common-lib` (usually by configuring `resolve.modules` and `resolve.alias`).

**Problem**: some aliases are package-relative. Most commonly: the `src` alias. (It is so common in fact, that VSCode automatically resolves to `src`, if it is shorter than a relative import, even though, if `baseUrl` is configured, and `src` is in `baseUrl`.)

## How should this be implemented in your opinion?

The `alias` configuration option can take a function which (or provide some other way where it) resolves the same alias differently, depending on where it is used.

This enables the following scenario:

* `import from 'src/X';`
  * should resolve to `App/src/X`, if used in `App`
  * should resolve to `common-lib/src/X`, if used in `common-lib`

## Are you willing to work on this yourself?

Maybe, depends on feedback.

**Comment by alexander-akait** [comment]
You can write `plugin` https://webpack.js.org/configuration/resolve/#resolveplugins and implement this

**Comment by Domiii** [comment]
@alexander-akait I am guessing there is no hook to override `alias` directly, which means we have to... look for `src` paths manually and change them afterwards...? Or... how would you suggest going about this?

**Comment by alexander-akait** [comment]
You can achieve this using:
- different alias for `import from 'src/X';`, i.e. in app `import something from 'app/src/x'`, in `common` using `import something from 'common/src/x'` and write for them alises
- using `imports` https://nodejs.org/api/packages.html#packages_imports (preferable due it will work without webpack too)
- implement a plugin https://github.com/webpack/enhanced-resolve
- write a loader and rewrite `import` on necessary file
- refactor code and using different imports modules

Also it is not good for ESM, because in real world the same URL in import should resolve the same file (don't forget `import` is cached), so because it is non standard, please use any custom solution from above, thanks

**Comment by Domiii** [comment]
The last point is the best one: module paths should indeed be unique.

Tbh, the main issue is that VSCode does the rewrite automatically. Will have to file an issue with them, to see what can be done on their end.

**Comment by Domiii** [comment]
@alexander-akait Thank you for the elaborate answer.

I understand that this functionality should not need to be integrated into the webpack core.

But I guess I have question related to your comment on "the same URL should resolve the same file":

The Node commonJS module resolution page says that its perfectly fine for the same name to resolve to different files. Note that, while there is theoretically the potential for dependency conflicts, it still is a common requirement to have the same dependency resolve to different files (at different versions) in the same application.

I quote from https://nodejs.org/api/modules.html#modules_caching:

> **Module caching caveats**  
> > Modules are cached based on their resolved filename. Since modules may resolve to a different filename based on the location of the calling module (loading from node_modules folders), it is not a guarantee that require('foo') will always return the exact same object, if it would resolve to different files.

This means that having the same name resolve to different files for different parts of the application does make sense, no?

**Comment by alexander-akait** [comment]
You can achieve this using a custom plugin https://webpack.js.org/configuration/resolve/#resolveplugins, yes, it is possible in Node.js context (but not for browser), anyway I strongly recommend do not use it, because your target is `web` and will be better to be align with web (for example you are trying to avoid using Node.js package for `web` target). Feel free to feedback

**Comment by Domiii** [comment]
I am actually working on a hybrid app, it is mostly targeting `electron` and `node`, and then there is some UMDs (actually I split it into `node` and `web` after running into several problems when trying to target `umd`).

I'm not sure what you mean by "not [possible] for browser"? Are you saying that `webpack` forces a single version for all dependencies when targeting `web`?

To my mind, when targeting `web`, the problem remains: you might have `a` requiring `d`, and `b` also requiring `d` but at a different version. Not sure how webpack module resolution deals with such a dependency conflict, but default `commonjs` resolution would make sure that `a` and `b` each get their own version of `d`.

I know that if you use `shared` libraries in `webpack-module-federation`, it will warn you in case of such dependency conflicts (because you basically told it to enforce a single version in the config). I can't recall ever seeing webpack (without module-fedration) warning me about that?

**Comment by alexander-akait** [comment]
When you bundle multiple multiple version of package, each modules have identifier (it is path to module i.e. for example if you have `require("package")` and some package also have `require("package")` you will have `node_modules/package/index.js` and `node_modules/another-package/node_modules/package/index.js`), so you will have two versions of packages.

As I written above you can create a custom plugin for resolver and implement any logic. module federation is some other technology, it allow to share modules in runtime and reuse them, so you can create micro architecture.
