### ISSUE TITLE
Inverse match pattern in rules not working

### ISSUE THREAD

**Issue by nvmkpk** [webpack/webpack#13402]
# Bug report
Unable to use inverse match pattern in rules

```
{
    test: /\.(ttf|woff2|woff|eot|otf)$/,
    use: {
        loader: "file-loader",
        options: {
            name: "[name].[ext]",
            outputPath: "fonts/",
            publicPath: "../fonts/"
        }
    }
},
{
    test: /.*webfont.*\.svg$/,
    use: {
        loader: "file-loader",
        options: {
            name: "[name].[ext]",
            outputPath: "fonts/",
            publicPath: "../fonts/"
        }
    }
},
{
    test: /\.(jpg|png|gif)$/,
    use: {
        loader: "file-loader",
        options: {
            name: "[name].[ext]",
            outputPath: "images/",
            publicPath: "../images/"
        }
    }
},
{
    test: /(?!.*webfont).*\.svg$/,
    use: {
        loader: "file-loader",
        options: {
            name: "[name].[ext]",
            outputPath: "images/",
            publicPath: "../images/"
        }
    }
}
```
**What is the current behavior?**
file `fontawesome-webfont.svg` is copied to `images` folder and `fonts` folder contains the same file with content:
```
export default "../images/fontawesome-webfont.svg";
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
`fontawesome-webfont.svg` should not match the last rule and should not be copied to `images` folder and complete file should be in `fonts` folder.

**Other relevant information:**
webpack version:  5.37.0
webpack-cli version: 4.7.0
Node.js version: v14.16.0
Operating System: Windows 10
Additional tools: yarn version 2.4.1

**Comment by alexander-akait** [comment]
> If the current behavior is a bug, please provide the steps to reproduce.

Please use `Discussions` if you can't create reproducible test repo, `file-loader` and `url-loader` are deprecated, please use https://webpack.js.org/guides/asset-modules/

**Comment by nvmkpk** [comment]
I updated to remove file-loader and still the inverse match pattern isn't working. This is my new rules part of config:
```
{
    test: /\.(ttf|woff2|woff|eot|otf)$/,
    type: "asset/resource",
    generator: {
        filename: "fonts/[name].[ext][query]",
        publicPath: "../"
    }
},
{
    test: /.*webfont.*\.svg$/,
    type: "asset/resource",
    generator: {
        filename: "fonts/[name].[ext][query]",
        publicPath: "../"
    }
},
{
    test: /\.(jpg|png|gif)$/,
    type: "asset/resource",
    generator: {
        filename: "images/[name].[ext][query]",
        publicPath: "../"
    }
},
{
    test: /(?!.*webfont).*\.svg$/,
    type: "asset/resource",
    generator: {
        filename: "images/[name].[ext][query]",
        publicPath: "../"
    }
},

```

This time however, the svg file is not in `fonts` folder but still being copied to `iamges` folder.

**Comment by alexander-akait** [comment]
Please `If the current behavior is a bug, please provide the steps to reproduce.`

You have a mistake in configuration

**Comment by nvmkpk** [comment]
I attached the zip file to reproduce this issue. You may need to install yarn 2 to reproduce the issue.

[issue.zip](https://github.com/webpack/webpack/files/6504192/issue.zip)

**Comment by alexander-akait** [comment]
Firstly remove `.` (dot) from `filename`, second use `exclude`, example:
```
{
                test: /\.(ttf|woff2|woff|eot|otf|svg)$/,
                type: "asset/resource",
                generator: {
                    filename: "fonts/[name][ext][query]",
                    publicPath: "../"
                }
            },
            {
                test: /\.(jpg|png|gif|svg)$/,
                exclude: /webfont/,
                type: "asset/resource",
                generator: {
                    filename: "images/[name][ext][query]",
                    publicPath: "../"
                }
            },
```

Also you don't need `CleanWebpackPlugin`, because `webpack` has `output.clean` https://webpack.js.org/guides/output-management/#cleaning-up-the-dist-folder

**Comment by nvmkpk** [comment]
I tried `exclude` when using file-loader and it did not work. I will try that now but doesn't the third rule copy all svg files to `fonts` folder? I did not include any svg files in the repro project but I have some that I want them in the `images` folder.

But why doesn't the inversion match work?

**Comment by alexander-akait** [comment]
`exclude` always works, don't know why it was not work for you

**Comment by nvmkpk** [comment]
It is now working with this change. I don't understand why other svg files do not get copied to `fonts` folder. But still the inverse match pattern should have worked and I think it still is a bug.

**Comment by alexander-akait** [comment]
No bugs here double check your regexps

**Comment by nvmkpk** [comment]
The zip file I uploaded here for repro has the regex that is not working. I tried the regex in https://regexr.com/ and it works there exactly as expected.

**Comment by alexander-akait** [comment]
I provide solution above, why do not use it?

**Comment by nvmkpk** [comment]
Of course I am using it. But the bug should be fixed to make the product better regardless of whether someone needs it. It might just be a lower priority.

**Comment by alexander-akait** [comment]
No bugs here again, you have overlapping in rules, so it works as expected

**Comment by nvmkpk** [comment]
My original config has mutually exclusive rules, your suggestion has overlapping rules (for other svg files). It definitely seems like a bug, whether you agree or not (I just wanted to help make this better). In the end, it works for me and that is what I care about. If it doesn't then I would just switch to another bundler.

**Comment by alexander-akait** [comment]
> If it doesn't then I would just switch to another bundler.

I have no right to forbid you something

> It definitely seems like a bug, whether you agree or not (I just wanted to help make this better). 

1. Solution and fix was provided.
2. Open https://regex101.com/, choose `ECMAScript`, write **your** regexp `(?!.*webfont).*\.svg$` and put `fontawesome-webfont.svg` as test string and you will see matches (i.e. `true` for in `test` and for the rule), because `/(?!.*webfont).*\.svg$/` is not ignore `webfont`.

I don't know why you think this is a webpack problem, when you have just wrong regexp. And I deeply do not understand why you are trying to threaten me with a change of bundler.

Do I need to show you how to write right regexp to ignore word between?

**Comment by nvmkpk** [comment]
I apologize, I am not trying to threaten you (or anyone). It was just frustration for the lack of explanation for why it was not working. This explanation was all I needed. If you just say "no bug here" it does not help anyone.
