### ISSUE TITLE
[Question] Is there any way to update entry in watch mode?

### ISSUE THREAD

**Issue by nilennoct** [webpack/webpack#1340]
We have a project which has more than 100 pages, and each page has a javascript file in webpack's entry. When start webpack, it takes 36 seconds to compile all files. So if there any way to update entry in watch mode? For example, add and compile only a little entries in the beginning, when pages visited or files changed, add the related file into entry and compile them. Is this possible at the moment? Or if we should change the way to compile the files? Thank you!

**Comment by adjavaherian** [comment]
Have you tried require.ensure() ? http://webpack.github.io/docs/code-splitting.html  It would be interesting to see if there are performance benefits to ensure, vs. multiple entry points in config.

**Comment by shama** [comment]
I recommend refactoring to use `require.ensure` as @adjavaherian proposed. It's just a guess but incremental builds would likely work way more efficiently instead of an entry point for each page.
