### ISSUE TITLE
env variables defined via EnviromentPlugin not included in bundle

### ISSUE THREAD

**Issue by Joozty** [webpack/webpack#13418]
# Bug report

Related SO question:
https://stackoverflow.com/questions/38013104/webpacks-define-plugin-variable-is-not-defined/48472655

**What is the current behavior?**
When I try to define env variable with [EnvironmentPlugin](https://webpack.js.org/plugins/environment-plugin/) the variable is not added to bundle. 

**If the current behavior is a bug, please provide the steps to reproduce.**
webpack.config.js

```js
const path = require('path')

const { EnvironmentPlugin } = require('webpack')

module.exports = (env) => {
	return {
		entry: {
			main: path.resolve(__dirname, 'index.js'),
		},
		resolve: {
			extensions: ['.js'],
		},
		output: {
			filename: '[name].bundle.js',
			path: path.resolve(__dirname, 'dist'),
		},
		plugins: [
			new EnvironmentPlugin({
				CONTEXT: 'tests',
			}),
		],
	}
}
```

index.js
```js
console.log(CONTEXT);
```

dist/main.bundle.js
```
console.log(CONTEXT)
```

**What is the expected behavior?**
I would expect that bundled file should look like this:

```
console.log('tests');
```

or 

```
var CONTEXT = 'tests';
console.log(CONTEXT);
```

**Other relevant information:**
webpack:  5.37.1
webpack-cli: 4.7.0
Node.js version: 16.0.0
Operating System: macos
Additional tools: -

**Comment by alexander-akait** [comment]
Yes, please use `DefinePlugin`, `EnvironmentPlugin` for `process.env.${key}`
