### ISSUE TITLE
'ReferenceError: BigInt is not defined' due to the BigInt in v5.35.1 or newer version

### ISSUE THREAD

**Issue by lukewang2018** [webpack/webpack#13419]
# Bug report

**What is the current behavior?**

After we upgrade the version of webpack to be v5.35.1 or newer, we will get below errors. If the version is older than v5.35.0, it would be OK. 
In fact, I already find the cause in the commit history. This issue is caused by this PR https://github.com/webpack/webpack/pull/13213 with this commit https://github.com/webpack/webpack/commit/acfea9dae42fb1182b4e162b7f0d752129a3bd34 by @sokra . In this commit, it's using **BigInt** which brings this issue. 

```
Resolve error: ReferenceError: BigInt is not defined
    at Object.<anonymous> (xxx/node_modules/webpack/lib/ChunkGraph.js:42:22)
    at Object.<anonymous> (xxx/node_modules/webpack/lib/ChunkGraph.js:1672:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (xxx/node_modules/webpack/lib/Chunk.js:8:20)

``` 

**If the current behavior is a bug, please provide the steps to reproduce.**
Just need to update the version and check build log. 

**What is the expected behavior?**
There should no such errors "Resolve error: ReferenceError: BigInt is not defined"

**Other relevant information:**
webpack version:  v5.35.1 or newer
Node.js version: v12.15.0
Operating System: Mac v11.3.1
Additional tools: VS Code v1.33.1

**Comment by alexander-akait** [comment]
> Node.js version: v12.15.0

No, it means you have Node.js lower than `10.4.0`, double check it `node -v`, minimum supported Node.js version is `10.13.0` https://github.com/webpack/webpack/blob/master/package.json#L108

**Comment by lukewang2018** [comment]
@alexander-akait no, I'm using node v12.15. I provided in the issue description.

```
$ node -v
v14.16.1
```

**Comment by alexander-akait** [comment]
create `file.js` put here `const bigNumber = BigInt(0)` and run `node file.js`

**Comment by alexander-akait** [comment]
Something wrong with Node.js in your dev env

**Comment by lukewang2018** [comment]
@alexander-akait thanks for your help. `node file.js`  works with node v14.16.1.

 I finally got the cause. it's due to the editor VSCode version. I just upgraded it from v1.33.1 to be v1.56.2 and it's ok now. 

<img width="254" alt="Screen Shot 2021-05-20 at 11 22 10 PM" src="https://user-images.githubusercontent.com/40848250/119006562-1363c900-b9c3-11eb-9849-e54040b25e25.png">

thanks again!
