### ISSUE TITLE
It seems no way to alias ESM and reuse the aliased module on webpack 5

### ISSUE THREAD

**Issue by JounQin** [webpack/webpack#13413]
The following works just fine on webpack 4, but fails on webpack 5 due to native ESM support.

```js
// webpack.config.js
module.exports = {
  resolve: {
    alias: {
      'js-yaml$': require.resolve('./js-yaml.shim.js'),
    },
  },
}

// js-yaml.shim.js
import { DEFAULT_SCHEMA } from 'js-yaml/dist/js-yaml.mjs'

export * from 'js-yaml/dist/js-yaml.mjs'

export const Schema = {
  create(...args) {
    let [schemas, customTags] = args
    if (args.length < 2) {
      customTags = schemas
    }
    return DEFAULT_SCHEMA.extend({
      implicit: schemas == null ? undefined : [],
      explicit: customTags == null ? undefined : [],
    })
  },
}
```

But `js-yaml` module uses `exports` field in `package.json` now: https://github.com/nodeca/js-yaml/blob/master/package.json#L29-L35, this makes subfolder files being invisible what means `js-yaml/dist/js-yaml.mjs` cannot be resolved anymore.

**Comment by alexander-akait** [comment]
https://webpack.js.org/configuration/resolve/#resolvebydependency

**Comment by alexander-akait** [comment]
How you import `js-yaml`?

**Comment by JounQin** [comment]
> How you import `js-yaml`?

`import {load} from 'js-yaml'`

**Comment by sokra** [comment]
You can create an alias `real-js-yaml` to the original package and import that from the shim

**Comment by JounQin** [comment]
> You can create an alias `original-js-yaml` to the original package and import that from the shim

Thanks @sokra ! It works as expected by aliasing `'original-js-yaml$': path.resolve('node_modules/js-yaml')`.

Does it worth to document? That would be very helpful.

**Comment by alexander-akait** [comment]
Feel free to send a PR to our docs :star:
