### ISSUE TITLE
output.path equivalent for assetModule

### ISSUE THREAD

**Issue by DylanPiercey** [webpack/webpack#13414]
## Feature request

Currently we have `assetModuleFilename` option which can use used to modify the output asset name (similar to `output.filename`) however there is not a way to override the path that assets get written to (without augmenting the filename that ultimately makes it into the asset url).

I propose that an `output.assetModulePath` be added which (for asset modules) is preferred over `output.path`.

**What is the expected behavior?**

Ideally we'd be able to have asset module files be written to a different directory than the regular chunk assets.

**What is motivation or use case for adding/changing the behavior?**

With `file-loader` I was able to leverage the `outputPath` option (https://v4.webpack.js.org/loaders/file-loader/#outputpath) to achieve what I needed.

The main purpose I have for this is that I've got two webpack compilers (one for a `target: "node"` and one `target: "web"`). When an asset is imported in the node compiler I'd like for it to place that asset in a common directory where the web compiler would also be outputting it.

Here is an example webpack config where this is being done (https://github.com/marko-js/examples/blob/master/examples/webpack-express/webpack.config.js#L173-L174).

**How should this be implemented in your opinion?**
I believe it could be implemented as I described, basically when resolving the full filesystem path for asset modules it would prefer the `output.assetModulePath` option if configured and fallback to `output.path` as it does now.

**Are you willing to work on this yourself?**
yes

**Comment by alexander-akait** [comment]
Second example https://webpack.js.org/guides/asset-modules/#custom-output-filename

**Comment by DylanPiercey** [comment]
@alexander-akait that's not exactly the same. The issue is whatever you put into the `assetModuleFilename` as a prefix ultimately makes it in as part of the final asset url, which is it the goal here. The goal is to just move where the asset is written, not change what the url would be.

**Comment by alexander-akait** [comment]
You will have problems with URL in this case, you can found a lot of issues about `outputPath` in `file-loader`, so this behavior is unwanted

**Comment by alexander-akait** [comment]
It sounds like to have multiple `output.path`, but it was discussed a lot of time, only one `output.path` can be

**Comment by DylanPiercey** [comment]
It's possible I'm limiting my thinking to my existing solution but ultimately I'm looking for a solution to this particular problem:

Isomorphic compilers (one for server and one for browser) where both import the same asset.

One issue I have is that I need to separate the ssr js code from the asset module output, since one will need to be served/uploaded to a cdn and the other should not.

The second issue is that if I do as you suggested and use something like `assetModuleFilename` with `../` or similar, then the server would be sending different urls than the browser would see.

**Comment by DylanPiercey** [comment]
One option is to go the `emit: false` route, and not have the server emit any assets. But I would like to support the case where an asset is imported (to get the url) on the server alone.

**Comment by alexander-akait** [comment]
You can use multi compiler mode and use different options, it is recommend

**Comment by DylanPiercey** [comment]
I am using multiple compilers, that's part of the problem. I wan't both of these compilers to output client assets to the same location, and also want to make sure that any asset urls the server compiler generates is inline with what the browser compiler does (Which is why having different `assetModuleFilename` options for each compiler does not work).

**Comment by alexander-akait** [comment]
Your original request was

> Ideally we'd be able to have asset module files be written to a different directory than the regular chunk assets.

And you can use `assetModulePath` to achieve this

> I propose that an output.assetModulePath be added which (for asset modules) is preferred over output.path.

No again, it means you will have multiple `path.output` (one for js, other for assets), it is unwanted, `output.path` should be one
