### ISSUE TITLE
use group matched in resourceQuery

### ISSUE THREAD

**Issue by MHA15** [webpack/webpack#13420]
## Feature request

In rule definition when using resourceQuery it's a good idea to have ability to use matched group and queryParams

**What is the expected behavior?**
```
  resourceQuery: /(color-.*)/
  generator: {
    dataUrl: (content, meta) => {
         // somehow access matched query and use given color in creating dataUrl
    } 
  }
```

**What is motivation or use case for adding/changing the behavior?**
when using mini-svg-data-uri to creating dataURI for svgs you can use queryParam to give color and set it in dataURI and having mulltiple colors of a same svg icon  

```
                    generator: {
                        dataUrl: (content, meta) => {
                            content = content.toString().replace(/currentColor/g, meta.matchedQuery /* example red or #fc2*/);
                            return svgToMiniDataURI(content);
                        },
                    },

```

**How should this be implemented in your opinion?**

**Are you willing to work on this yourself?**
no

**Comment by alexander-akait** [comment]
You can setup this on rules level using `matchedQuery`

**Comment by sokra** [comment]
Best use a custom loader for that. Inside of the loader you can access `this.resourceQuery`

**Comment by alexander-akait** [comment]
Answered, feel free to feedback
