### ISSUE TITLE
webpack5 considerably slower than webpack4

### ISSUE THREAD

**Issue by StreetStrider** [webpack/webpack#13427]
Hello. My team is trying to migrate to webpack5 and we've faced `5-30%` build time increasing.
I've tried to track down particular subsystem (like loader or plugin) which can be the source of this issue, but no success. I've ended up creating repro case and measuring setup which would allow you to reproduce my results and confirm or disprove it.

I've used [repro](https://github.com/meskill/webpack5-performance-issue) from #12102 as a base and I'm using some simple statistic approach.
Setup: [webpack-perf.zip](https://github.com/webpack/webpack/files/6522182/webpack-perf.zip)

My result is that on this simple public setup I have webpack5 `5%` slower (with stddev about `1.5%`) on my machine. In our private app we have around `30%` slowness in my local tests and in our CI system runs. Right now I'm trying to adapt this basic setup to our private setup to display even more slowness. I'm on 10-11% mark in my private setup now. If this is relevant, I can try to share that with you in the future without disclosing our private code.

I can share some additional info on perf which I gained through my research, if you become interested. For instance, activating devtool = source-map (full mode) leads to instant `30-40%` slowness in webpack5 in comparison to the same mode in webpack4. However, we use `cheap-module-source-map` in general.

**Comment by alexander-akait** [comment]
Please put your feedback/problems here https://github.com/webpack/webpack/issues/12102 and example, we are trying to track perf problems in one issue, big thanks and sorry for closing

**Comment by StreetStrider** [comment]
@alexander-akait okay, will do. Btw, I would never post there initially, because OP's issue is related to rebuilds and I'm still perfing cold builds at the moment. But ok.

**Comment by alexander-akait** [comment]
@StreetStrider In most of cases problems with rebuild appear for cold builds too :+1:
