### ISSUE TITLE
ERROR in ./webapp/manifest.webapp 2:8

### ISSUE THREAD

**Issue by Prasanth-FrontEnd** [webpack/webpack#13432]
While the building the Angular 9 version application I'm getting this error by using this command - ng build. But it was working fine using yarn start.

Please get back to me ASAP.

ERROR in ./webapp/manifest.webapp 2:8
Module parse failed: Unexpected token (2:8)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| {
>   "name": "sampleproject",
|   "short_name": "sampleproject",
|   "icons": [
 @ ./webapp/app/polyfills.ts 52:0-29

**Comment by alexander-akait** [comment]
You need to setup loader for `manifest.webapp`, you can use `asset/resource` https://webpack.js.org/guides/asset-modules/ for `webapp` extension

**Comment by Prasanth-FrontEnd** [comment]
Shall I use like this?

            {
                test: /manifest.webapp$/,
                loader: 'file-loader?name=manifest.webapp',
                type: 'asset/resource',
            },

**Comment by alexander-akait** [comment]
Remove `loader`, you don't need `file-loader`/`raw-loader`/`url-loader` for webpack v5, better to use
```
{
  test: /\.webapp$/,
  type: 'asset/resource',
},
```

**Comment by Prasanth-FrontEnd** [comment]
No, but I'm using the webpack version of 4.29.5.

**Comment by alexander-akait** [comment]
In this case you need `file-loader`, i.e.:
```
{
  test: /\.webapp$/,
  loader: 'file-loader',
  options: { name: '[path][name].[ext]' }
},
```

**Comment by Prasanth-FrontEnd** [comment]
Not working
           {
                test: /\.webapp$/,
                loader: 'file-loader',
                options: { name: 'manifest.webapp' }
            },

**Comment by alexander-akait** [comment]
`ng build` uses webpack under the hood, I think better ask them how better setup loader for the `webapp` extension
