### ISSUE TITLE
Webpack5 doesn't have compatibility with non-harmony modules.

### ISSUE THREAD

**Issue by LinFeng1997** [webpack/webpack#13438]
# Bug report

**What is the current behavior?**
![image](https://user-images.githubusercontent.com/16188742/119476445-a5cbea00-bd80-11eb-878b-0a2a5493ebd6.png)
when I import `file-saver` package(a non-harmony module). it's all of the property is on `defalut`

**If the current behavior is a bug, please provide the steps to reproduce.**
1. get the [code](https://github.com/LinFeng1997/non-harmony-module)
2. `yarn install`
3. `yarn run build`
4. open index.html

**What is the expected behavior?**
![image](https://user-images.githubusercontent.com/16188742/119476224-71f0c480-bd80-11eb-8cbc-0d44c31211ac.png)

`modules.saveAs` is exists.

I think because webpack5 doesn't have compatibility with non-harmony modules but webpack4 does.

And I found that webpack4 can generate those codes:
```
/******/ 	// getDefaultExport function for compatibility with non-harmony modules
/******/ 	__webpack_require__.n = function(module) {
/******/ 		var getter = module && module.__esModule ?
/******/ 			function getDefault() { return module['default']; } :
/******/ 			function getModuleExports() { return module; };
/******/ 		__webpack_require__.d(getter, 'a', getter);
/******/ 		return getter;
/******/ 	};
```

**Other relevant information:**
webpack version:  5.37.1
Node.js version: 14.16.0
Operating System: windows 10

**Comment by alexander-akait** [comment]
Async import always use `.default` property by spec, please run `node src/index.js`

**Comment by LinFeng1997** [comment]
@alexander-akait Why webpack4 support it?

**Comment by LinFeng1997** [comment]
And I read up on [ecma spec](https://tc39.es/ecma262/#sec-hostimportmoduledynamically), but I didn't find any information about `default` property, can you give me the correct spec URL?

**Comment by sodatea** [comment]
Not the ECMAScript spec. The ESM-CommonJS interop spec by Node.js https://nodejs.org/api/esm.html#esm_interoperability_with_commonjs

> When importing CommonJS modules, the `module.exports` object is provided as the default export. Named exports may be available, provided by static analysis as a convenience for better ecosystem compatibility.

Note that dynamic imports are typically not statically analyzable, so named exports are not available.

**Comment by alexander-akait** [comment]
@LinFeng1997 Answer above, please prefer to use `default` with webpack v5, feel free to feedback
