### ISSUE TITLE
Webpack 5 Node Interface - can't resolve loader from node_modules

### ISSUE THREAD

**Issue by royibernthal** [webpack/webpack#13430]
# Bug report

**What is the current behavior?**

I'm trying to compile custom TypeScript code in Node at runtime using Webpack 5.

It says it can't resolve ts-loader from node_modules because node_modules doesn't exist, except it definitely does exist.

Here's the error from the log:

    [   {
        loc: 'main',
        message: "Module not found: Error: Can't resolve 'ts-loader' in 'D:\\Projects\\projectCode\\projectcode-server-test'",
        details: "resolve 'ts-loader' in 'D:\\Projects\\projectCode\\projectcode-server-test'\n" +
          '  Parsed request is a module\n' +
          '  No description file found in D:\\Projects\\projectCode\\projectcode-server-test or above\n' +
          '  resolve as module\n' +
          "    D:\\Projects\\projectCode\\projectcode-server-test\\node_modules doesn't exist or is not a directory\n" +
          "    D:\\Projects\\projectCode\\node_modules doesn't exist or is not a directory\n" +
          "    D:\\Projects\\node_modules doesn't exist or is not a directory\n" +
          "    D:\\node_modules doesn't exist or is not a directory",
        stack: "ModuleNotFoundError: Module not found: Error: Can't resolve 'ts-loader' in 'D:\\Projects\\projectCode\\projectcode-server-test'\n" +
          '    at D:\\Projects\\projectCode\\projectcode-server-test\\node_modules\\webpack\\lib\\Compilation.js:1762:28\n'
    +
          '    at D:\\Projects\\projectCode\\projectcode-server-test\\node_modules\\webpack\\lib\\NormalModuleFactory.js:730:13\n'
    +
          '    at eval (eval at create (D:\\Projects\\projectCode\\projectcode-server-test\\node_modules\\tapable\\lib\\HookCodeFactory.js:33:10), <anonymous>:8:1)\n' +
          '    at D:\\Projects\\projectCode\\projectcode-server-test\\node_modules\\webpack\\lib\\NormalModuleFactory.js:273:22\n'
    +
          '    at eval (eval at create (D:\\Projects\\projectCode\\projectcode-server-test\\node_modules\\tapable\\lib\\HookCodeFactory.js:33:10), <anonymous>:7:1)\n' +
          '    at D:\\Projects\\projectCode\\projectcode-server-test\\node_modules\\webpack\\lib\\NormalModuleFactory.js:488:15\n'
    +
          '    at D:\\Projects\\projectCode\\projectcode-server-test\\node_modules\\webpack\\lib\\NormalModuleFactory.js:117:11\n'
    +
          '    at D:\\Projects\\projectCode\\projectcode-server-test\\node_modules\\webpack\\lib\\NormalModuleFactory.js:571:8\n'
    +
          '    at D:\\Projects\\projectCode\\projectcode-server-test\\node_modules\\neo-async\\async.js:2830:7\n'
    +
          '    at done (D:\\Projects\\projectCode\\projectcode-server-test\\node_modules\\neo-async\\async.js:2925:13)' } ]

**If the current behavior is a bug, please provide the steps to reproduce.**

Create a new project with the following files and run it:

### index.js

    const webpack = require('webpack');
    const { createFsFromVolume, Volume } = require('memfs');
    
    const vol = Volume.fromJSON({
        './src/index.tsx': `
            console.log('index test');
        `
    });
    
    const inputFS = createFsFromVolume(vol);
    const outputFS = createFsFromVolume( new Volume() );

    const compiler = webpack(
        {
            entry: './src/index.tsx',
            mode: 'production',
            module: {
                rules: [
                    {
                        test: /\.tsx?$/,
                        use: 'ts-loader'
                    }
                ]
            },
            resolve: {
              extensions: ['.tsx', '.ts', '.jsx', '.js'],
            },
            output: {
                filename: 'bundle.js'
            }
        }
    );
    
    compiler.inputFileSystem = inputFS;
    compiler.outputFileSystem = outputFS;
    
    compiler.run((err, stats) => {
        if (err) {
            console.error(err.stack || err);
    
            if (err.details) console.error(err.details);
    
            return;
        }
    
        const info = stats.toJson();
    
        if (stats.hasErrors()) console.error(info.errors);
    
        if (stats.hasWarnings()) console.warn(info.warnings);
    });

### package.json

    {
      "name": "projectcode-server-test",
      "version": "1.0.0",
      "description": "",
      "main": "index.js",
      "scripts": {
        "start": "node index.js"
      },
      "author": "",
      "license": "ISC",
      "dependencies": {
        "memfs": "^3.2.2",
        "ts-loader": "^9.2.2",
        "webpack": "^5.37.1"
      }
    }

**What is the expected behavior?**

node_modules should be found since it exists in the expected path, and ts-loader should be resolved.

**Other relevant information:**
webpack version:  5.37.1
Node.js version: 12.16.2
Operating System: Windows 10 Pro
Additional tools: None

**Comment by alexander-akait** [comment]
Do not override `inputFileSystem`, i.e. `compiler.inputFileSystem = inputFS;`, webpack can not find `ts-loader` in this case, or you can create flaky fs, i.e. try to read from memory, if not found in memory try to read from real fs or you can use https://github.com/streamich/fs-monkey so `require` will work, `compiler.outputFileSystem = outputFS;` is enough, in dev server we will do the same, only change `outputFileSystem`

**Comment by royibernthal** [comment]
Makes sense, it didn't occur to me that inputFileSystem would affect that too.

Due to my project's needs, I need to input files from memory rather than from the file system, doesn't that mean I have to override inputFileSystem?

I tried unionfs to create a combination of memory fs and real fs. It's now able to find ts-loader but for some reason can't find other modules within the memory file system (e.g. App). Any idea what I'm missing this time?

### index.js

```
const webpack = require('webpack');
const { createFsFromVolume, Volume } = require('memfs');
const fs = require('fs');
const { ufs } = require('unionfs');

const sandboxCode = Volume.fromJSON({
    './src/App.tsx': `
        export default function App() {
            console.log('App');
        }
    `,
    './src/index.tsx': `
        import App from "./App";
        
        console.log('index');
    `
});

const sandboxFS = createFsFromVolume(sandboxCode);
const inputFS = ufs.use(fs).use(sandboxFS);
const outputFS = createFsFromVolume( new Volume() );

const compiler = webpack(
    {
        entry: './src/index.tsx',
        mode: 'production',
        module: {
            rules: [
                {
                    test: /\.tsx?$/,
                    use: 'ts-loader'
                }
            ]
        },
        resolve: {
          extensions: ['.tsx', '.ts', '.jsx', '.js'],
        },
        output: {
            filename: 'bundle.js'
        }
    }
);

compiler.inputFileSystem = inputFS;
compiler.outputFileSystem = outputFS;

compiler.run((err, stats) => {
    if (err) {
        console.error(err.stack || err);

        if (err.details) console.error(err.details);

        return;
    }

    const info = stats.toJson();

    if (stats.hasErrors()) console.error(info.errors);

    if (stats.hasWarnings()) console.warn(info.warnings);
});
```

### package.json

```
{
  "name": "projectcode-server-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "nodemon index.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "memfs": "^3.2.2",
    "ts-loader": "^9.2.2",
    "typescript": "^4.2.4",
    "unionfs": "^4.4.0",
    "webpack": "^5.37.1"
  }
}
```

### Error

```
[
  {
    file: 'D:\\Projects\\projectCode\\projectcode-server-test\\src\\index.tsx',
    moduleIdentifier: 'D:\\Projects\\projectCode\\projectcode-server-test\\node_modules\\ts-loader\\index.js!D:\\Projects\\projectCode\\projectcode-server-test\\src\\index.tsx',
    moduleName: './src/index.tsx',
    loc: '2:24-31',
    message: '\u001b[90m[tsl] \u001b[39m\u001b[1m\u001b[31mERROR\u001b[39m\u001b[22m\u001b[1m\u001b[31m in \u001b[39m\u001b[22m\u001b[1m\u001b[36mD:\\Projects\\projectCode\\projectcode-server-test\\src\\index.tsx(2,25)\u001b[39m\u001b[22m\r\n' +
      "\u001b[1m\u001b[31m      TS2307: Cannot find module './App' or its corresponding type declarations.\u001b[39m\u001b[22m",
    moduleId: 629,
    moduleTrace: [],
    details: 'ts-loader-default_e3b0c44298fc1c14',
    stack: 'Error: \u001b[90m[tsl] \u001b[39m\u001b[1m\u001b[31mERROR\u001b[39m\u001b[22m\u001b[1m\u001b[31m in \u001b[39m\u001b[22m\u001b[1m\u001b[36mD:\\Projects\\projectCode\\projectcode-server-test\\src\\index.tsx(2,25)\u001b[39m\u001b[22m\r\n' +
      "\u001b[1m\u001b[31m      TS2307: Cannot find module './App' or its corresponding type declarations.\u001b[39m\u001b[22m\n" +
      '    at makeError (D:\\Projects\\projectCode\\projectcode-server-test\\node_modules\\ts-loader\\dist\\utils.js:93:19)\n' +
      '    at D:\\Projects\\projectCode\\projectcode-server-test\\node_modules\\ts-loader\\dist\\utils.js:63:27\n' +
      '    at Array.map (<anonymous>)\n' +
      '    at Object.formatErrors (D:\\Projects\\projectCode\\projectcode-server-test\\node_modules\\ts-loader\\dist\\utils.js:46:14)\n' +
      '    at D:\\Projects\\projectCode\\projectcode-server-test\\node_modules\\ts-loader\\dist\\after-compile.js:153:49\n' +
      '    at Array.forEach (<anonymous>)\n' +
      '    at provideErrorsToWebpack (D:\\Projects\\projectCode\\projectcode-server-test\\node_modules\\ts-loader\\dist\\after-compile.js:150:31)\n' +
      '    at D:\\Projects\\projectCode\\projectcode-server-test\\node_modules\\ts-loader\\dist\\after-compile.js:36:9\n' +
      '    at D:\\Projects\\projectCode\\projectcode-server-test\\node_modules\\ts-loader\\dist\\instances.js:203:13\n' +
      '    at fn (D:\\Projects\\projectCode\\projectcode-server-test\\node_modules\\webpack\\lib\\Compilation.js:425:10)'
  }
]
```

**Comment by alexander-akait** [comment]
> TS2307: Cannot find module './App' or its corresponding type declarations.

Looks you need set custom fs (i.e. memory) for `ts` too, maybe related https://github.com/ionic-team/stencil/issues/567

**Comment by royibernthal** [comment]
It seems passing the transpileOnly: true option to ts-loader solved the issue. Thanks for the help :)

**Comment by alexander-akait** [comment]
@royibernthal Can we close?

**Comment by royibernthal** [comment]
Yup. Thanks again.
