### ISSUE TITLE
WP5: Unexpected lazy element in stream

### ISSUE THREAD

**Issue by garfileds** [webpack/webpack#13440]
# Bug report

**What is the current behavior?**

1. enable persistent cache in webpack config
2. use webpack in custom dev server

when calling webpack(config), throw error `Unexpected lazy element in stream`.

i found the same issue but closed.
[issue#11661](https://github.com/webpack/webpack/issues/11661)

**If the current behavior is a bug, please provide the steps to reproduce.**

The error can be reproduced with the following example.

```javascript
    const config = {
        name: 'cache_test',
        entry: {},
        cache: {
            type: 'filesystem'
        }
    };
    const webpackCompiler = webpack(config);
```

```
Error: Unexpected lazy element in stream
    at readU8 (E:\JavaScript\wwmngnjlogic_2\vue_dev\webpack\node_modules\webpack\lib\serialization\BinaryMiddleware.js:589:11)
    at BinaryMiddleware._deserialize (E:\JavaScript\wwmngnjlogic_2\vue_dev\webpack\node_modules\webpack\lib\serialization\BinaryMiddleware.js:882:20)
    at BinaryMiddleware.deserialize (E:\JavaScript\wwmngnjlogic_2\vue_dev\webpack\node_modules\webpack\lib\serialization\BinaryMiddleware.js:494:15)
    at Serializer.deserialize (E:\JavaScript\wwmngnjlogic_2\vue_dev\webpack\node_modules\webpack\lib\serialization\Serializer.js:41:26)
    at PackFileCacheStrategy._openPack (E:\JavaScript\wwmngnjlogic_2\vue_dev\webpack\node_modules\webpack\lib\cache\PackFileCacheStrategy.js:915:5)
    at new PackFileCacheStrategy (E:\JavaScript\wwmngnjlogic_2\vue_dev\webpack\node_modules\webpack\lib\cache\PackFileCacheStrategy.js:887:27)
    at WebpackOptionsApply.process (E:\JavaScript\wwmngnjlogic_2\vue_dev\webpack\node_modules\webpack\lib\WebpackOptionsApply.js:561:9)
    at createCompiler (E:\JavaScript\wwmngnjlogic_2\vue_dev\webpack\node_modules\webpack\lib\webpack.js:81:28)
    at E:\JavaScript\wwmngnjlogic_2\vue_dev\webpack\node_modules\webpack\lib\webpack.js:44:48
    at Array.map (<anonymous>)
    at createMultiCompiler (E:\JavaScript\wwmngnjlogic_2\vue_dev\webpack\node_modules\webpack\lib\webpack.js:44:33)
    at create (E:\JavaScript\wwmngnjlogic_2\vue_dev\webpack\node_modules\webpack\lib\webpack.js:118:16)
    at webpack (E:\JavaScript\wwmngnjlogic_2\vue_dev\webpack\node_modules\webpack\lib\webpack.js:151:32)
    at f (E:\JavaScript\wwmngnjlogic_2\vue_dev\webpack\node_modules\webpack\lib\index.js:55:16)
```

**What is the expected behavior?**
the build should execute without error

**Other relevant information:**
webpack version:  5.30.0
Node.js version:  14.16.1
Operating System:  Windows
Additional tools:

**Comment by alexander-akait** [comment]
Run `npm ls webpack` and do you have extra plugins/loaders?

**Comment by garfileds** [comment]
> Run `npm ls webpack` and do you have extra plugins/loaders?

```
I removed all extra loaders/plugins except cache and entry options in webpack.config, and still get the same error.

**Comment by alexander-akait** [comment]
Please run `npm ls webpack`, we need to check your webpack version

**Comment by garfileds** [comment]
> Please run `npm ls webpack`, we need to check your webpack version

```
> npm ls webpack
vue_dev_webpack@1.0.0 E:\JavaScript\wwmngnjlogic_2\vue_dev\webpack
+-- @tencent/ww.webpack_i18n_loader@0.4.1
| `-- webpack-inject-plugin@1.5.5
|   `-- webpack@5.37.1 deduped
+-- babel-loader@8.2.2
| `-- webpack@5.37.1 deduped
+-- cache-loader@4.1.0
| `-- webpack@5.37.1 deduped invalid
+-- css-loader@5.2.6
| `-- webpack@5.37.1 deduped
+-- friendly-errors-webpack-plugin@1.7.0
| `-- webpack@5.37.1 deduped invalid
+-- less-loader@7.3.0
| `-- webpack@5.37.1 deduped
+-- lodash-webpack-plugin@0.11.6
| `-- webpack@5.37.1 deduped
+-- parallel-webpack@2.6.0
| `-- webpack@5.37.1 deduped invalid
+-- speed-measure-webpack-plugin@1.5.0
| `-- webpack@5.37.1 deduped
+-- stylelint-webpack-plugin@2.1.1
| `-- webpack@5.37.1 deduped
+-- thread-loader@3.0.4
| `-- webpack@5.37.1 deduped
+-- vue-loader@15.9.7
| `-- webpack@5.37.1 deduped
+-- webpack-cli@4.7.0
| +-- @webpack-cli/configtest@1.0.3
| | `-- webpack@5.37.1 deduped
| `-- webpack@5.37.1 deduped
+-- webpack-dev-middleware@4.3.0
| `-- webpack@5.37.1 deduped
`-- webpack@5.37.1
  `-- terser-webpack-plugin@5.1.2
    `-- webpack@5.37.1 deduped
```

**Comment by alexander-akait** [comment]
If you remove `entry: {}`, all works fine?

**Comment by alexander-akait** [comment]
Note: Also you don't need `cache-loader` for webpack v5, also `parallel-webpack` is not compatibility with webpack v5

**Comment by garfileds** [comment]
> If you remove `entry: {}`, all works fine?

It doesn't work to remove `entry`, but it works to remove `cache`.

**Comment by alexander-akait** [comment]
Can you provide code of `src/index.js`? I can't reproduce it

**Comment by garfileds** [comment]
> Can you provide code of `src/index.js`? I can't reproduce it

It's just some test code. 

src/index.js
```javascript
import App from './test.vue';

new Vue({
    render: h => h(App)
}).$mount('#js_single_page_container');

```

src/test.vue

```
<template>
    <div>test</div>
</template>
<script>
export default {
    name: 'Test',
    data() {
        return {
            title: ''
        };
    }
};
</script>
```

**Comment by alexander-akait** [comment]
But you don't have loader(s) for `.vue`...

**Comment by garfileds** [comment]
@alexander-akait 
I found the reason. The following condition doesn't include the object looks like a promises-a+ promise, such as `bluebird`.
Maybe it's better to use the library `is-promise`？

webpack/lib/serialization/Serializer.js
```javascript
    deserialize(value, context) {
		const ctx = { ...context, ...this.context };
		/** @type {any} */
		let current = value;
		for (const middleware of this.deserializeMiddlewares) {
			**if (current instanceof Promise)** {
				current = current.then(data => middleware.deserialize(data, context));
			} else {
				current = middleware.deserialize(current, ctx);
			}
		}
		return current;
	}
```

BTW, I found out that the error can be only reproduced in our express application, which is missed in the submitted issue. Sorry about this. And in the application, we use `bluebird`.

**Comment by alexander-akait** [comment]
Yes, we can improve this check, no need to use extra package for this simple check https://github.com/then/is-promise/blob/master/index.js#L5

But I want to warn you other tools/packages/libraries/etc can use the same approach to check on `Promise`, so you may run into problems somewhere else (not only with webpack)

**Comment by alexander-akait** [comment]
Feel free to send PR and improve checks https://github.com/webpack/webpack/search?q=%22instanceof+Promise%22

**Comment by myNameIsDu** [comment]
> Feel free to send PR and improve checks https://github.com/webpack/webpack/search?q=%22instanceof+Promise%22

Can I fix this? Recently I've been reading the Webpack source code and I'm looking for some confidence :worried:

**Comment by alexander-akait** [comment]
Yes, you can send a PR
