### ISSUE TITLE
Cannot resolve module, when it is included as a different name

### ISSUE THREAD

**Issue by netsgnut** [webpack/webpack#1344]
Hi,

Not sure if this is a bug or simply my own misunderstandings of things, but I do have got some trouble in integrating `HubSpot/vex` into the webpack pipeline.

I have tried the following:
```js
export var vex = require('vex-js/js/vex.js');
require('vex-js/js/vex.dialog.js');
```

However the second statement would give out an error of `Module not found: Error: Cannot resolve module 'vex'`. The offending line is `144:4-47` [(see here)](https://github.com/HubSpot/vex/blob/v2.3.2/js/vex.dialog.js#L144), which I think may refer to the fact that `webpack` treats the imported library as `vex-js`, but it in fact is finding `vex`.

Frankly speaking I am not sure if this issue belongs here or at the issue tracker of `HubSpot/vex` instead. However I really would like to see how to deal with it. Thanks.

**Comment by netsgnut** [comment]
Never mind, got mine resolved by
```js
resolve: {
  alias: {
    vex: 'vex-js'
  }
}
```

Silly me.

**Comment by shama** [comment]
:+1:

**Comment by ConAntonakos** [comment]
@netsgnut, thanks for submitting this issue. This helped me as well since it's not really explained well in their docs. How did you resolve the issue with the CSS?

**Comment by netsgnut** [comment]
@ConAntonakos Sorry that I saw your reply just now. Are you referring to the CSS supplied by vex itself? For them I have to import them myself, just like for the JS.

One of my stylesheet files have the following lines:

```less
@import (less) "~vex-js/css/vex.css";
@import (less) "~vex-js/css/vex-theme-default.css";
```

I use LESS in this project, but it would apply to different post-processing engines like SASS too. How it helps and sorry for the late reply.

**Comment by satb** [comment]
Ran into this issue. Sorry new to webpack and trying to understand what is going on here. Could someone please explain why @ConAntonakos solution works? What the alias is actually achieving and what the ~ in the @import for style sheets means?

**Comment by Kovensky** [comment]
I'm not sure why the alias is needed; is there some kind of self-reference but with the wrong name? You should be able to just `require('vex')`. The only thing you should need to explicitly `require` other than the default entry point is the css.

As for the `~`, that seems to be LESS syntax for "look in node_modules". You can also just do the `require` from JS, like `require('vex/css/vex.css')` and `require('vex/css/vex-theme-default.css')`, as long as you do those `require`s before you require your own CSS.

**Comment by andreypopp** [comment]
`~` is a css-loader's thing: basically when you import from CSS all references are treated as relative but those are prefixed with `~` resolved in packages (e.g. in `node_modules/`).

**Comment by satb** [comment]
@andreypopp - Thanks. ~ as a mnemonic makes sense now.
