### ISSUE TITLE
`DefinePlugin` does not work if `loader` modifies the code

### ISSUE THREAD

**Issue by Domiii** [webpack/webpack#13458]
Pre-determined plugin/loader order causes bugs in my application:

1. I have a custom `babel` plugin which modifies code.
2. This causes `DefinePlugin` to fail because it seems to operate on `babel` output, not input, code. It thus cannot recognize what to replace in the code.

How can I tell `DefinePlugin` to run before `babel-loader`?

I don't see any configuration option for that. Not sure, if that is an oversight, or if there is a way to fix this at all?

I setup a repository that illustrates the issue: https://github.com/Domiii/webpack-plugin-order-test

PS: I am not sure if this a bug or a feature request or something else.

**Comment by alexander-akait** [comment]
No ability and no problems with `DefinePlugin`, all works as expected, if you don't know what is this please use `Discussions`, it is for questions, if a bug was found we will convert it to the issue.

> This causes DefinePlugin to fail because it seems to operate on babel output, not input, code. It thus cannot recognize what to replace in the code.

In this case you need a custom babel plugin

**Comment by alexander-akait** [comment]
> Should I open a post on Discussions to pursue this question?

This makes no sense, `DefinePlugin` plugin works only after loaders, it is impossible to run it before in most of cases, because we need parse your code (it can be ts/modern ES/coffee script/etc), which means we need to supply all these parsers and write logic, it's just incredible work and most likely it's just impossible.

> What do you mean "custom babel plugin"? I already have one. And I want it to work with arbitrary webpack configurations. I.e. DefinePlugin should work as usual. Do you mean that DefinePlugin cannot operate on input and only on output? (If so, maybe the documentation can reflect that?)

You need something like this https://github.com/wssgcg1213/babel-plugin-inline-replace-variables, other solution is implement own loader before babel-loader and replace `A.B.C` on own мфдгу - you can use RegExp or parsers.

**Comment by alexander-akait** [comment]
Answered. My recommendation - create simple loader and replace values using `RegExp`, as I said earlier, unfortunately this is not possible to `DefinePlugin` before loaders (I'll correct myself, this is theoretically possible if you only use `stage 4`), but in your case you are using `babel` so your code can be in any stage, even more you can use experimental syntax that may never be part of ECMA and here is the main problem, we can't parse this syntax.

Other solution - https://github.com/jean-smaug/babel-plugin-search-and-replace

Feel free to feedback

**Comment by Domiii** [comment]
@alexander-akait, thank you for your feedback!

I guess the [string-replace-loader](https://www.npmjs.com/package/string-replace-loader) would be preferrable, seeing how it is a lot more widely used :)
