### ISSUE TITLE
Should not import the named export 'version' bug after upgrade to webpack5

### ISSUE THREAD

**Issue by lemiesz** [webpack/webpack#13469]
# Bug report

**What is the current behavior?**
After upgrading to webpack5 I am getting the following error  

```
   {
      moduleIdentifier: '/local/home/{redacted}/Projects/{redacted}/src/{}/node_modules/babel-loader/lib/index.js??ruleSet[1].rules[0].oneOf[2]!/local/home/{redacted}/Projects/{redacted}/src/{redacted}/node_modules/{redacted}/node_modules/@aws-sdk/client-pinpoint/dist/es/runtimeConfig.browser.js',
      moduleName: './node_modules/{redacted}/node_modules/@aws-sdk/client-pinpoint/dist/es/runtimeConfig.browser.js',
      loc: '19:43-50',
      message: "Should not import the named export 'version' (imported as 'version') from default-exporting module (only default export is available soon)"
    }
``` 

The rules referenced there is adopted form the CRA config.  

```
         {
                            test: /\.(js|mjs)$/,
                            exclude: /@babel(?:\/|\\{1,2})runtime/,
                            loader: require.resolve('babel-loader'),
                            options: {
                                babelrc: false,
                                configFile: false,
                                compact: false,
                                presets: [[require.resolve('babel-preset-react-app/dependencies'), { helpers: true }]],
                                cacheDirectory: true,
                                // See #6846 for context on why cacheCompression is disabled
                                cacheCompression: false,

                                // Babel sourcemaps are needed for debugging into node_modules
                                // code.  Without the options below, debuggers like VSCode
                                // show incorrect code and set breakpoints on the wrong lines.
                                sourceMaps: shouldUseSourceMap,
                                inputSourceMap: shouldUseSourceMap,
                            },
                        },
```

I cant change the actually behavior of those exports since they are coming from a library i don't control. 

**What is the expected behavior?**

I expect this to work the same way it worked in webpack4... meaning it compiles my app without errors. 
Or if I am misunderstanding something about why this error is happening please let me know. 

**Other relevant information:**
webpack version:  5.0
Node.js version: 12.x
Operating System:  Linux

**Comment by alexander-akait** [comment]
It means you use bad library or maybe babel break it without code nobody can help, example of the problem https://github.com/system-ui/theme-ui/issues/1097, as you can see you need open an issue in your library, json files always exports by `default` property

**Comment by alexander-akait** [comment]
You can't do it:
```js
import { version as __EMOTION_VERSION__ } from 'package/package.json'
```

It should be written:
```js
import packageInfo from 'package/package.json'
```

**Comment by lemiesz** [comment]
I understand but that is not a solution. 

Because this issue is in a library, and the issue compiles correctly in Webpack4. 

I cant edit this library.

**Comment by lemiesz** [comment]
Is there anyway to have babel ignore these files?

**Comment by lemiesz** [comment]
Actually it looks like this issue was already solved in the AWS-SDK https://github.com/aws/aws-sdk-js-v3/commit/797ba7dc7743eb65e8f81536bcf70e5c225ef861. 

I was just had an old transitive dependency. Which is what was confusing me. Resolving the issue now thanks oyu.
