### ISSUE TITLE
Incorrect processing of cyclic dependencies of ES modules in development

### ISSUE THREAD

**Issue by ilgonmic** [webpack/webpack#13461]
# Bug report
<img width="691" alt="image" src="https://user-images.githubusercontent.com/36933116/119845433-eb6bec80-bf11-11eb-8d7a-15d83344ee32.png">

**What is the current behavior?**
There is dependencies structure,
`Baz1` class in `baz1.js`
`Bar1` - in `bar1.js`
`Foo1` - in `foo1.js`

`foo2.js` reexport all of these classes from their original place.
`foo1.js` imports `Bar1` from `foo2.js`

Entry point - `foo3.js` import all of these classes from `foo2.js`
In development mode, there is error in browser
```
Uncaught TypeError: _baz1_js__WEBPACK_IMPORTED_MODULE_2__ is undefined
```

In production mode, everything works fine.

**If the current behavior is a bug, please provide the steps to reproduce.**

Webpack config:
```
const config = {
    mode: 'development',
    resolve: {
      modules: [
        "node_modules"
      ]
    },
    plugins: [],
    module: {
      rules: []
    }
  };
  
  // entry
  config.entry = {
      main: ["./foo3.js"]
  };

  const path = require("path")
  
  config.output = {
      path: path.resolve("dist"),
      filename: (chunkData) => {
          return chunkData.chunk.name === 'main'
              ? "hello.js"
              : "hello-[name].js";
      },
      library: "foo",
      libraryTarget: "umd",
      globalObject: "this"
  };
  
  module.exports = config
  
  ```

`bar1.js`
```
import {Baz1} from "./foo2.js"
console.log("from bar1 Baz1", Baz1)
export function Bar1() {}
```
`baz1.js`
```
export function Baz1() {}
```
`foo1.js`
```
import {Baz1, Bar1} from "./foo2.js"
console.log("from foo1 Baz1", Baz1)
console.log("from foo1 Bar1", Bar1)
export function Foo1() {}
```
`foo2.js`
```
export * from "./foo1.js"
export * from "./bar1.js"
export * from "./baz1.js"
```
`foo3.js`
```
import {Foo1, Bar1, Baz1} from "./foo2.js"

console.log("from foo3 Foo1", Foo1)
console.log("from foo3 Bar1", Bar1)
console.log("from foo3 Baz1", Baz1)
```

**What is the expected behavior?**
No errors in browser in development mode.
Cyclic dependencies works fine either in production or development like in Node.JS.

**Other relevant information:**
webpack version:  5.38.0
Node.js version: 16.0.0
Operating System: MacOS Big Sur 11.2.3
Additional tools:

**Comment by myNameIsDu** [comment]
If you change the function to a let declaration and run it in a browser, it will also report an error

**Comment by sokra** [comment]
@ilgonmic that's a known limitation on how we are wrapping modules in functions.
In some cases with
* Circular dependencies
* Reexports
* Exporting hoised bindings like function declarations
you will see some exports being undefined during the circular evaluation

In production mode scope hoisting will get rid of most wrapping so that won't happen here.

I think it also won't happen for side effect free flagged modules since optimization will get rid of reexports here
