### ISSUE TITLE
Support custom service ip:port when runtime.

### ISSUE THREAD

**Issue by yansenlei** [webpack/webpack#13479]
## Feature request

**What is the expected behavior?**

Support custom service ip:port when *Template.runtime.js

```
"webpack": "^4.29.4",
```
WebWorkerMainTemplate.runtime.js
```diff
function hotDownloadUpdateChunk(chunkId) {
  importScripts('http://localhost:9000' + $require$.p + $hotChunkFilename$);
}

// eslint-disable-next-line no-unused-vars
function hotDownloadManifest(requestTimeout) {
  requestTimeout = requestTimeout || 10000;
  return new Promise(function(resolve, reject) {
    if (typeof XMLHttpRequest === "undefined") {
      return reject(new Error("No browser support"));
    }
    try {
      var request = new XMLHttpRequest();
-     var requestPath = $require$.p + $hotMainFilename$;
+     // Custom service IP
+     var requestPath = 'http://localhost:9000' + $require$.p + $hotMainFilename$;
      request.open("GET", requestPath, true);
      request.timeout = requestTimeout;
      request.send(null);
    } catch (err) {
      return reject(err);
    }
...
```

**What is motivation or use case for adding/changing the behavior?**

**How should this be implemented in your opinion?**

**Are you willing to work on this yourself?**
If webpack provide custom hooks

**Comment by alexander-akait** [comment]
Sorry no, also webpack v4 is deprecated and accept only security fixes, in webpack v5 we done big refactor you can do it by creating custom plugin, here example how you can add more https://github.com/webpack/webpack/blob/master/lib/javascript/EnableChunkLoadingPlugin.js
