### ISSUE TITLE
Missing exports in shared split chunks

### ISSUE THREAD

**Issue by roblan** [webpack/webpack#13489]
# Bug report

**What is the current behavior?**

Async entries loading can lead to errors caused by missing exports in shared tree shaked dependencies, as they use the same module id, but can have different module content.

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/roblan/webpack-splitChunks
```
npm install
npm start
# everything ok (but also fails sometimes)
open ./a-b.html
# missing named export
open ./a-later.html
# missing default export
open ./b-later.html
```

**What is the expected behavior?**

Webpack should either create one shared chunk with all used exports for shared module or treat every export in shared module as separate module (with unique module id).
Or chunkLoadingGlobal should not be shared across different entries (but this would probably introduce some bugs as shared content could be expected to be only loaded once).

**Other relevant information:**
webpack version:  5.38.1
Node.js version: 14.17.0
Operating System: MacOS 11.4
Additional tools: none

**Comment by alexander-akait** [comment]
I don't see any problems, you have multiple runtime at the same time on page, you need to use `runtimeChunk: single` for using multiple entries on the same page https://github.com/webpack/webpack-dev-server/issues/2792#issuecomment-808328432, feel free to feedback
