### ISSUE TITLE
IE11: syntax error in vendor bundle although target: ["web", "es5"] is used

### ISSUE THREAD

**Issue by vertic4l** [webpack/webpack#13486]
# Bug report

**What is the current behavior?**

After bundling and testing in IE11 i've encountered this syntax error:

<img width="775" alt="Bildschirmfoto 2021-06-01 um 15 20 55" src="https://user-images.githubusercontent.com/1771763/120331227-d914f880-c2ed-11eb-8415-1d10cb055778.png">

**If the current behavior is a bug, please provide the steps to reproduce.**

 - having a webpack config with target: ["web", "es5"]
 - using webpack 5

**What is the expected behavior?**

Bundling should produce a clean / stable bundle which works in IE11, when "es5" is mentioned as target.

**Other relevant information:**
webpack version: "^5.38.1"
Node.js version: 14.4.0
Operating System: Mac OSX / Paralles Desktop (Windows 10)
Additional tools: none

**Comment by alexander-akait** [comment]
You need babel-loader for supporting IE 11, no problems in your screenshot

> If the current behavior is a bug, please provide the steps to reproduce.

Can't reproduce

Please provide all steps to reproduce the problem, I will reopen and ask what is wrong when you fill out all steps.

**Comment by vertic4l** [comment]
@alexander-akait I've switched from babel to swc. so maybe it is related to it, are there any config examples ?

**Comment by alexander-akait** [comment]
@vertic4l Can you provide small reproducible test repo, we have tests with IE11 in many loaders/plugins/dev server/etc and no problems, even more we have test with IE10/IE9, so I think it is related to transpiler, can you provide full bundled file (it allows to look at compiled code)?

**Comment by vertic4l** [comment]
like the produced vendor bunde ?

**Comment by alexander-akait** [comment]
Yes, code of `vendor` bundle

**Comment by vertic4l** [comment]
Here you have it.
[vendor.06eecc7758d3b7756e3e.js.zip](https://github.com/webpack/webpack/files/6576820/vendor.06eecc7758d3b7756e3e.js.zip)

**Comment by vertic4l** [comment]
And as i said, i'm trying to use swc-loader due to it's speed instead of babel-loader:

```
{
            test: /\.m?js$/,
            exclude: /core-js/,
            use: {
                loader: "swc-loader",
            }
        },
        // thread-loader,
        // ts-loader,
```

**Comment by alexander-akait** [comment]
For better debug you can set `devtool: false` (we will have code without eval and source map stuff)

**Comment by vertic4l** [comment]
yes, here with `devtool: false`
[vendor.d1ee8faff3b2a8b26156.js.zip](https://github.com/webpack/webpack/files/6576924/vendor.d1ee8faff3b2a8b26156.js.zip)

**Comment by vertic4l** [comment]
maybe nothing, but just saw this line inside of it:
`function(){return!!i[e]()||"​᠎"!="​᠎"`

which looks like some strange encoding although watched with UTF-8.
<img width="296" alt="Bildschirmfoto 2021-06-01 um 16 29 21" src="https://user-images.githubusercontent.com/1771763/120340744-9572bc80-c2f6-11eb-91e5-de75db4e0e89.png">

**Comment by alexander-akait** [comment]
yep, something weird in code, can you try to set `ascii_only: true` for terser plugin https://github.com/terser/terser#format-options (most likely it won't help due swc return broken code, just want to check it is not terser problem), looks `swc` doesn't handle `unicode` bug report https://github.com/swc-project/swc/issues/1227

**Comment by alexander-akait** [comment]
Also other problem with unicode https://github.com/swc-project/swc/search?q=Unicode&type=issues, swc is so young, maybe you shouldn't use it for production right now, babel is more mature and stable, especial if you want do not break something in production for your clients

**Comment by vertic4l** [comment]
Ya, i think i'll skip it for now. Thank you very much for your time. swc seems to be nice, but as you said not mature / stable enough for now.

**Comment by vertic4l** [comment]
Works with babel flawlessly. But build time is no back to 42 secs. instead of 23 sec. with swc.

**Comment by alexander-akait** [comment]
Yes, `swc` needs time to be mature, I think by the end of the year we will see much better results. Maybe we should inform them about this error and they will prioritize it. 

> Thank you very much once again!

:+1:
