### ISSUE TITLE
Container generated as a SystemJS library loads its exposed modules from host url

### ISSUE THREAD

**Issue by fbessou** [webpack/webpack#13480]
# Bug report

**What is the current behavior?**
A container library generated using the `ContainerPlugin` with `library: {type: "systemjs"}` and served on any URL different from the host application's root can't have its exposed module loaded.

**If the current behavior is a bug, please provide the steps to reproduce.**

A host app served on `http://localhost:9000` loads the 'http://localhost:9001/remoteEntry.js' file using SystemJS : 
```js
SystemJS.import('http://localhost:9001').then(container => {
[...]
})
```
When trying to call `container.get('./someModule')`, the corresponding request is sent to `http://localhost:9000/some_module_js.js` instead of `http://localhost:9001/some_module_js.js`

Here is a repository to reproduce the problem : https://github.com/fbessou/webpack-systemjs-container
See `README.md` for instructions on how to reproduce.

**What is the expected behavior?**

The exposed modules should be loaded from a path relative to the remoteEntry.js file and on the same origin.

**Other relevant information:**
webpack version:  5.38.1
Node.js version: 14.17.0
Operating System: Debian 10 (buster)
Additional tools:

**Comment by alexander-akait** [comment]
Why you use `ContainerPlugin`? You should not use it if you don't understand what you do. And you need other plugin on other side other it will not work.
