### ISSUE TITLE
When there are more than 7 entry points, webpack is strucking

### ISSUE THREAD

**Issue by pavankumarkatakam** [webpack/webpack#1349]
AS mentioned i have an app that has 13 entry points but it is failing to build when i use `webpack` command ,when i reduce some entry points to 6 then it is working fine.

can anybody explain why this is happening.

**Comment by shama** [comment]
Could you provide an example or more steps to reproduce?

It's likely not the exact number of entry points but rather the operations that will occur with a certain set of entry points.

**Comment by pavankumarkatakam** [comment]
if it is due to number of operations, what is the solution for that.

for now , im reduced entry points and building the project for entire project im building with 3 different times with 3 different entry points each, but then chunks are misalliged or not in order.


please tell me any temporary solution for that.

**Comment by shama** [comment]
I can't provide a solution because I cannot reproduce the issue. Could you provide an example or more steps to reproduce?

**Comment by pavankumarkatakam** [comment]
I tried with sample project to reproduce the issue but in that case it is working fine.

**Comment by pavankumarkatakam** [comment]
yes i have big dependency tree, with large no of requires.

**Comment by pavankumarkatakam** [comment]
Additional details i run this command

`webpack --progress`

every time it is strucking at progrerss 

`53% 63/87 build modules`

**Comment by pavankumarkatakam** [comment]
for now im using named chunks rather than id's.

**Comment by bebraw** [comment]
@pavankumarkatakam Any luck with the issue? Could you try setting up a reproducible test case again?

**Comment by pavankumarkatakam** [comment]
No its still appears, but i noticed that if it has more number of require's then it is strucking....

**Comment by bebraw** [comment]
@pavankumarkatakam Ok. It would be great if you could set up a standalone case to study. There is no other way to debug the problem properly.

**Comment by pavankumarkatakam** [comment]
Sure, i will make one.

**Comment by bebraw** [comment]
@pavankumarkatakam Could you please have a look? That standalone example would help.

**Comment by pavankumarkatakam** [comment]
Hi @bebraw , after updating the sass loader its working fine. At that time i has a couple of css (sass-loader) mistake which caused webpack to struck with out intimating the error. Now its working fine and sorry to close this issue. can i close it now.

**Comment by bebraw** [comment]
Thanks!
