### ISSUE TITLE
Cannot build project with webpack v4

### ISSUE THREAD

**Issue by korya** [webpack/webpack#13498]
# Bug report

Cannot build a webpack project with the latest SDK installed, `@aws-sdk/lib-storage@3.17.0`. I get the following error: `Module not found: Error: Can't resolve 'fs' in ...`

### Setup

Below is the minimal setup for reproducing this problem.

```sh
$ tree
.
├── package-lock.json
├── package.json
└── src
    └── index.js

1 directory, 3 files
```

Contents of `package.json`:

```json
{
  "name": "ttt",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "build": "webpack --mode development"
  },
  "devDependencies": {
    "webpack": "^4.46.0",
    "webpack-cli": "^3.3.12",
    "webpack-dev-server": "^3.11.2"
  },
  "dependencies": {
    "@aws-sdk/client-s3": "^3.17.0",
    "@aws-sdk/lib-storage": "^3.17.0"
  }
}
```

Contents of `src/index.js`:

```js
import { S3Client } from '@aws-sdk/client-s3';
import { Upload } from '@aws-sdk/lib-storage';

console.log('+=+ S3Client', S3Client);
console.log('+=+ Upload', Upload);
```

**What is the current behavior?**

I get the following error:

```sh

ERROR in ./node_modules/@aws-sdk/lib-storage/dist/es/runtimeConfig.js
Module not found: Error: Can't resolve 'fs' in '/Users/korya/dev/ttt/node_modules/@aws-sdk/lib-storage/dist/es'
 @ ./node_modules/@aws-sdk/lib-storage/dist/es/runtimeConfig.js 3:0-31 7:106-115
 @ ./node_modules/@aws-sdk/lib-storage/dist/es/bytelength.js
 @ ./node_modules/@aws-sdk/lib-storage/dist/es/Upload.js
 @ ./node_modules/@aws-sdk/lib-storage/dist/es/index.js
 @ ./src/index.js
```

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Create the project
2. Install deps: `npm install`
2. Try to build it using `npm run build` (or just by running `npx webpack`)

**What is the expected behavior?**

The project should be successfully built and `Upload` imported `@aws-sdk/lib-storage` should be configured to work in browser's environment (as expected).

**Other relevant information:**
webpack version:  4.46.0
Node.js version: 15.14.0
npm version: 7.12.1
Operating System: MacOS Catalina
Additional tools:

**Comment by korya** [comment]
Cross-posted in https://github.com/aws/aws-sdk-js-v3/issues/2459

**Comment by alexander-akait** [comment]
Please do not duplicate issues and avoid cross-posting because it is like spam, you need polyfill `fs` for `target: 'web'`, close in favor https://github.com/aws/aws-sdk-js-v3/issues/2459 and https://github.com/aws/aws-sdk-js-v3/issues/2136, we can't fix it on our side, sorry

**Comment by alexander-akait** [comment]
For webpack v5 you can set `resolve: { fallback: { fs: false } }`, but if library needs `fs` module for correct work, it will not work, not all libraries can work in browser

**Comment by korya** [comment]
The catch is the library does not need `fs`. `@aws-sdk/lib-storage` has 3 implementations:
- one for browser: `runtimeConfig.browser.ts`, https://github.com/aws/aws-sdk-js-v3/blob/main/lib/lib-storage/src/runtimeConfig.browser.ts)
- one for react-native: `runtimeConfig.native.ts`, https://github.com/aws/aws-sdk-js-v3/blob/main/lib/lib-storage/src/runtimeConfig.native.ts
- one (the default) for NodeJS: `runtimeConfig.ts`, https://github.com/aws/aws-sdk-js-v3/blob/main/lib/lib-storage/src/runtimeConfig.ts

The library code imports `runtimeConfig` file at: https://github.com/aws/aws-sdk-js-v3/blob/5d9bc5f32980f43a9b581b1f5101cdc7f2258173/lib/lib-storage/src/bytelength.ts#L1-L2

The build tool is supposed to choose the right implementation at the build time. `package.json`, https://github.com/aws/aws-sdk-js-v3/blob/5d9bc5f32980f43a9b581b1f5101cdc7f2258173/lib/lib-storage/package.json,  of the library contains instructions (hints?):

```json
  "browser": {
    "stream": "stream-browserify",
    "./runtimeConfig": "./src/runtimeConfig.browser"
  },
  "react-native": {
    "./runtimeConfig": "./src/runtimeConfig.native"
  },
```

I expect `webpack` to use `./src/runtimeConfig.browser` when `./runtimeConfig` is imported at https://github.com/aws/aws-sdk-js-v3/blob/5d9bc5f32980f43a9b581b1f5101cdc7f2258173/lib/lib-storage/src/bytelength.ts#L1-L2. Because the target in my webpack config is `web`.

The main reason I've opened this issue here is because it seems to be a `webpack` bug. I've decided to cross-post it in SDK's repository as well because the old issues you've referenced were not properly resolved.

**Comment by alexander-akait** [comment]
Due the `module` field https://github.com/aws/aws-sdk-js-v3/blob/5d9bc5f32980f43a9b581b1f5101cdc7f2258173/lib/lib-storage/package.json#L6, please read here https://github.com/webpack/webpack/issues/5756 about this problem.

Shortly: `module` can be for browser and for node and it is hard to say what is right (some libraries using this for browser, some for Node.js, some for both and more), but here solution - implement `exports` and provide `browser` and `node` targets https://webpack.js.org/guides/package-exports/#target-environment.

**Comment by korya** [comment]
I briefly read the thread and I could undestand why `module` would matter in this case. But my knowledge of "package.json" conventions is very limited. As far as I understand, `main` is the legacy (pre-ES6) way to define an entry point and `module` is the ES6 way to define an entry point. This is good, `webpack` properly chooses the entry point of the ES6 distribution -- `./node_modules/@aws-sdk/lib-storage/dist/es/index.js`.

Stuff breaks later when `index.js` transitively imports `./runtimeConfig.js`, as can be seen from:

```
Module not found: Error: Can't resolve 'fs' in '/Users/korya/dev/ttt/node_modules/@aws-sdk/lib-storage/dist/es'
 @ ./node_modules/@aws-sdk/lib-storage/dist/es/runtimeConfig.js 3:0-31 7:106-115
 @ ./node_modules/@aws-sdk/lib-storage/dist/es/bytelength.js
 @ ./node_modules/@aws-sdk/lib-storage/dist/es/Upload.js
 @ ./node_modules/@aws-sdk/lib-storage/dist/es/index.js
 @ ./src/index.js
```

I still have some questions:
1. Is it a bug in `webpack`?
2. Is it a bug in `@aws-sdk/lib-storage`?
3. What would be the proper way to fix it in the original library? using `exports` field?
4. Is there a workaround for me as a user of this application? How could I let webpack know that `./runtimeConfig.js` should be "mapped" to `./runtimeConfig.browser.js` inside `@aws-sdk/lib-storage`?

**Comment by alexander-akait** [comment]
> Is it a bug in webpack?
> Is it a bug in @aws-sdk/lib-storage?

I would not call it a bug, this is limitation, which cannot be fixed correctly for all packages without workarounds, but we have `exports` in `Node.js` so now there is no problems

> What would be the proper way to fix it in the original library? using exports field?

Yes and webpack will get the right file

> Is there a workaround for me as a user of this application? How could I let webpack know that ./runtimeConfig.js should be "mapped" to ./runtimeConfig.browser.js inside @aws-sdk/lib-storage?

In theory you can change https://webpack.js.org/configuration/resolve/#resolvemainfields, but it will change it for other packageю Other workaround to create extra rile for this package and change `mainFields`, here simple example https://webpack.js.org/configuration/module/#ruleresolve

**Comment by korya** [comment]
Thanks a lot for your help!

In regards to `export`. It seems that it is designed to provide aliases to internal paths for outside users of a package. That is, it has no effect on imports inside the package itself.

I tried to define exports as follows (directly in `node_modules/` dir):

```diff
--- node_modules/@aws-sdk/lib-storage/package.json~orig	2021-06-04 09:29:02.040115270 -0400
+++ node_modules/@aws-sdk/lib-storage/package.json	2021-06-04 11:54:44.719345898 -0400
@@ -48,12 +48,14 @@
       ]
     }
   },
-  "browser": {
-    "stream": "stream-browserify",
-    "./runtimeConfig": "./src/runtimeConfig.browser"
-  },
-  "react-native": {
-    "./runtimeConfig": "./src/runtimeConfig.native"
+  "exports": {
+    "./runtimeConfig": {
+      "browser": "./runtimeConfig.browser",
+      "react-native": "./runtimeConfig.native"
+    },
+    "stream": {
+      "browser": "stream-browserify"
+    }
   },
   "homepage": "https://github.com/trivikr/aws-sdk-js-v3/tree/main/lib/lib-storage",
   "repository": {
```

This one did not work either:

```diff
--- node_modules/@aws-sdk/lib-storage/package.json~orig	2021-06-04 09:29:02.040115270 -0400
+++ node_modules/@aws-sdk/lib-storage/package.json	2021-06-04 09:29:06.252200902 -0400
@@ -48,12 +48,14 @@
       ]
     }
   },
-  "browser": {
-    "stream": "stream-browserify",
-    "./runtimeConfig": "./src/runtimeConfig.browser"
-  },
-  "react-native": {
-    "./runtimeConfig": "./src/runtimeConfig.native"
+  "exports": {
+    "browser": {
+      "stream": "stream-browserify",
+      "./runtimeConfig": "./runtimeConfig.browser"
+    },
+    "react-native": {
+      "./runtimeConfig": "./runtimeConfig.native"
+    }
   },
   "homepage": "https://github.com/trivikr/aws-sdk-js-v3/tree/main/lib/lib-storage",
   "repository": {
```

but it did no work. I get the same error:

```sh

ERROR in ./node_modules/@aws-sdk/lib-storage/dist/es/runtimeConfig.js
Module not found: Error: Can't resolve 'fs' in '/Users/korya/dev/ttt/node_modules/@aws-sdk/lib-storage/dist/es'
 @ ./node_modules/@aws-sdk/lib-storage/dist/es/runtimeConfig.js 3:0-31 8:106-115
 @ ./node_modules/@aws-sdk/lib-storage/dist/es/bytelength.js
 @ ./node_modules/@aws-sdk/lib-storage/dist/es/Upload.js
 @ ./node_modules/@aws-sdk/lib-storage/dist/es/index.js
 @ ./src/index.js
```

**Comment by alexander-akait** [comment]
@korya oh, I forgot you are using webpack v4, sorry, in this case only help:

> In theory you can change https://webpack.js.org/configuration/resolve/#resolvemainfields, but it will change it for other packageю Other workaround to create extra rile for this package and change mainFields, here simple example https://webpack.js.org/configuration/module/#ruleresolve

**Comment by korya** [comment]
Thanks. I will give it a try.

**Comment by korya** [comment]
Thanks again!

Just an update. The following config worked for `webpack@4.46.0`:

```js
const path = require('path');

module.exports = {
  entry: './src/index.js',

  module: {
    rules: [
      {
        test: /@aws-sdk\/lib-storage\//,
        resolve: {
          alias: {
            './runtimeConfig': './runtimeConfig.browser',
          },
        },
      },
    ],
  },
};
```

**Comment by alexander-akait** [comment]
Great!
