### ISSUE TITLE
Inconsistent sourcemap dot path behavior

### ISSUE THREAD

**Issue by danielgindi** [webpack/webpack#13495]
# Bug report

**What is the current behavior?**

When configuring an entry point like this:
```
module.exports = {
  entry: './path/to/my/entry/file.js',
};
```

The source map in dev mode will have urls like this:
```webpack://project-server/./resources/js/MyPage.js```

But `vue` files in the same project have urls like this:
```webpack://project-server/resources/js/AnotherPage.vue```

Notice that the `vue` paths are not prefixed with `./`.

This splits the sources in the dev tool to two separate folder, which makes it hard to find while debugging.

I have tried multiple `entry` combinations, but could not get this to behave.

For those interested in a workaround, here it is:
```js
  output.devtoolModuleFilenameTemplate = opts => {
      return `webpack://${opts.namespace}/${opts.resourcePath.startsWith('./') ? opts.resourcePath.substr(2) : opts.resourcePath}`;
  };
  output.devtoolFallbackModuleFilenameTemplate = opts => {
      return `webpack://${opts.namespace}/${opts.resourcePath.startsWith('./') ? opts.resourcePath.substr(2) : opts.resourcePath}?${hash}`;
  };
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Any simple project with both js and vue will demonstrate the issue.
Although just a simple js project will also demonstrate it, as the paths should not contain `./` in them anyway.

**What is the expected behavior?**

Paths should be normalized (no `./` or `../` in the path), or at least behave in a consistent way across all modules.

I am not entirely sure if paths are not normalized, or if they are actually normalized and this line ```options.moduleFilenameTemplate || "webpack://[namespace]/[resourcePath]";``` in `SourceMapDevToolPlugin.js` is just too simple.

Even though there is a workaround, I think that this should be fixed for everyone from the ground up.

**Other relevant information:**
webpack version:  `5.38.1`
Node.js version: `14.5.4`
Operating System: `Windows 10`
Additional tools: `webpack-dev-server v4.0.0-beta.3`, `webpack-cli v4.6.0`

**Comment by alexander-akait** [comment]
Path can be outside of `namespace` so we keep `./`, `../` and `../../` and more, so it is expected and we can't normalize `../../../../` when it above of `namespace`, but you still setup `filesystem` in dev tools, feel free to feedback

**Comment by danielgindi** [comment]
@alexander-akait But `./` can always be normalized, and should be stripped. As I demonstrated, this creates weird duplicate file system.

**Comment by alexander-akait** [comment]
in this context `project-server` is not directory, it is just namespace (i.e. name of the project), you can have multiple of them, I don't see duplication, maybe you can demonstrate (using small github repo)?

**Comment by danielgindi** [comment]
> in this context `project-server` is not directory, it is just namespace (i.e. name of the project), you can have multiple of them, I don't see duplication, maybe you can demonstrate (using small github repo)?

The problem is in the sourcemap diff between `webpack://project-server/./` and `webpack://project-server/`.
In the Chrome devtools, you see your files in different folders although they are in the same folder.
That's because some paths are stripped of the ./ by the vue-loader, and some don't.
Now the ./ is redundant. It means "current folder, no change"... so why not strip it?

**Comment by alexander-akait** [comment]
> In the Chrome devtools, you see your files in different folders although they are in the same folder.

it should be same... look like chrome bug, what is chrome version? Can you provide screenshot(s)?

**Comment by danielgindi** [comment]
It's not from Chrome, the paths are like that in the sourcemap itself. 
The Chrome version is latest, documented in the issue details. Although it happens for a year now, through many Chrome versions.

**Comment by alexander-akait** [comment]
@danielgindi Can you provide small repo with vue-loader/etc, I want to look at this and ensure the problem

**Comment by danielgindi** [comment]
Yes I'll create something

**Comment by alexander-akait** [comment]
@danielgindi thanks

**Comment by danielgindi** [comment]
@alexander-akait here's a sample: https://github.com/danielgindi/webpack-bug-sample
1. `git clone https://github.com/danielgindi/webpack-bug-sample && cd webpack-bug-sample && npm start`
2. `http://localhost:8080/`
3. F12 -> Sources tab
4. Look for `webpack-bug-sample/./app/sample.js`
5. Look for `webpack-bug-sample/app/other.vue`
6. Look for `webpack-bug-sample/./app/other.vue?artifacts`

In full projects, you'll see the split in `node_modules` too, and other directory trees.

**Comment by alexander-akait** [comment]
And no problem here:
- app/other.vue is source of file
- ./app/other.vue is transpiled file from vue to js

If they have the same name, you will lose some of the information.

**Comment by danielgindi** [comment]
Nope, you are missing the problem. The transpiled pieces are suffixed with a hash, using the fallback template.
In any case, the sourcemaps are meant to show the *sources*.
So if you look for the sources for the vue file, and for the source of the js file- you'll see them in a different folder although they are physically in the same folder.
If you'll uncomment the template functions in the `webpack.config.js` you'll observe the correct behavior, and without losing anythingx

**Comment by alexander-akait** [comment]
oh, I see, feel free to send PR, honestly I would call it more an improvement than a bug

**Comment by sokra** [comment]
> * app/other.vue is source of file

That really shouldn't be this way.

All files should be prefixed with `./` (or `../` if they are outside the project directory). The names used here usually are the names webpack also displays in stats.

**Comment by danielgindi** [comment]
> > * app/other.vue is source of file
> 
> That really shouldn't be this way.
> 
> All files should be prefixed with `./` (or `../` if they are outside the project directory). The names used here usually are the names webpack also displays in stats.

Why `./`? `./` is redundant, and also apparently 3rd party plugins (aka vue-loader...) do cleanup the paths...

**Comment by alexander-akait** [comment]
@danielgindi it means vue-loader has bug here, because `namespace` is like `root`, you can set `namespace` to empty string, it is not part of path as I am saying before

**Comment by danielgindi** [comment]
> @danielgindi it means vue-loader has bug here, because `namespace` is like `root`, you can set `namespace` to empty string, it is not part of path as I am saying before

I think you are wrong. The `./` is still redundant. Even in root. Look at any other path systems. Whether windows, linux, unix, or devtools sourcemaps. Only webpack generates those `./`. That's just a drawback of using a fixed template without any normalization.

I'll create a simple PR to fix that.

**Comment by alexander-akait** [comment]
Note - css-loader and some other loaders and plugins also use `./` always, note `file.ext` and `./file.ext` is different URLs, you can have `sourceRoot: /path/to/static/assets`, so when you have `file.ext`, you will get `/path/to/static/assetsfile.ext`, but with `./file.ext` you will get `/path/to/static/assets./file.ext`, we cannot know how it server will worj with trailing urls (i.e. ending with `/`) and we can't apply it by default

**Comment by sokra** [comment]
sourceRoot and source is concatenated with a `/` when sourceRoot doesn't end with `/`.

**Comment by sokra** [comment]
We use `./` to indicate that these paths are relative to your project and that's not absolute paths.

**Comment by danielgindi** [comment]
> We use `./` to indicate that these paths are relative to your project and that's not absolute paths.

Still not convinced. The `[namespace]` is the project's root. Everything is relative to that.
Anything below that - will have `../../` etc. in it.

**Comment by alexander-akait** [comment]
> The [namespace] is the project's root.

you can set `namespace` to `''` (empty string) and if you change `./` on nothing you will get absolute paths 

> Still not convinced.

ok then if there is no difference and both are valid we prefer to use `./` and it is our default behaviour

**Comment by danielgindi** [comment]
> ok then if there is no difference and both are valid we prefer to use `./` and it is our default behaviour 

So I understand that you want to preserve this weird behaviour- that's fine, thank you. I do have a local workaround.
