### ISSUE TITLE
Extend templating capabilities for asset module output routing

### ISSUE THREAD

**Issue by mbalc** [webpack/webpack#13492]
## Feature request

**What is the expected behavior?**
either `output.assetModuleFilename` or `output.path` should expose "chunkName"/"entryName" via some template-like way

**What is motivation or use case for adding/changing the behavior?**
I want my webpack v5 config to use those fancy features like Asset Modules and Multiple Entries support

However, I need my chunks to be grouped by Entry Name

So far, the only way I could manage my idea (without spawning lots of webpack workers that were really spammy) to come true was to use the following config idea:

```webpack.config.babel.ts
const someDefaultConfigWithPluginsAndModuleLoaderRulesSpec = {
    REDACTED: true,
};

  const makeOutputCfg = (folderName) => ({
    path: `${__dirname}/dist/${folderName}`,
    publicPath: `/dist/${folderName}`,
    filename: '[name]/bundle.js',
  });


  const outputs = [
    {
      target: 'web',
      entry: {
        MyAwesomeInterface: './src/someEntryPoint.tsx',
        MyWonderfulDemoComponent: './src/anotherReactTing.tsx',
      },
      output: makeOutputCfg('browser'),
      devServer: {
        contentBase: path.join(__dirname, 'dist', 'browser'),
        port: 8080,

        historyApiFallback: {
          index: 'index.html', // if route doesn't exist, serve our SPA
        },
      },
    },
    {
      target: 'node',
      entry: {
        OneShadyBackend: './src/crypticExpressFile.ts',
        TheMostImportantMainBackend: './src/myMicroServer.ts',
      },
      output: makeOutputCfg('node'),
    },
  ];  
  
  const myExports =  outputs.map((outputSpec) =>
    Object.assign({}, someDefaultConfigWithPluginsAndModuleLoaderRulesSpec, outputSpec));
    
  export default myExports
```

Please note necessary use of `[name]` template string in `output.filename` to specify a folder name - according to the docs, `output.path` doesn't support any templating to achieve the same effect

now, to extend this config so it outputs Asset Modules to the same path as `bundle.js` files, I have to either use `output.assetModuleFilename` or extend the asset module loader rule with `generator.filename` option - but none of this give me a way to use the `[name]` template string like in `output.filename`

I could not find any clean way of achieving this neither in docs, nor on stackOverflow or Google - other than exporting not two-element array, but n-element array from the `webpack.config.babel.ts` file, where `n` corresponds to the number of entries - but that defeats the purpose of having a support for multiple entries in webpack and results in a really spammy webpack output

**How should this be implemented in your opinion?**
I'm not familiar enough with the codebase to be able to make any suggestions here

**Are you willing to work on this yourself?**
won't be able to find time at least in the nearest ~2 months for that; later - who knows, maybe?

**Comment by alexander-akait** [comment]
You can setup `publicPath` and `filename` by entries https://github.com/webpack/webpack/blob/master/schemas/WebpackOptions.json#L473, also `filename` and `publicPath` can be `Function` https://github.com/webpack/webpack/blob/master/schemas/WebpackOptions.json#L3006, so you can do any complex logic
