### ISSUE TITLE
Resolve alias fails - "Module not found: Error: Can't resolve"

### ISSUE THREAD

**Issue by dennemark** [webpack/webpack#13504]
# Bug report

**What is the current behavior?**

Hi,
I am using webpack 5 via nextjs and need to resolve an import with an alias. However it fails. Here is the config, with two different options. Both resulting in different errors. It seems Option 2 is the right direction, but it still fails.
I upgraded to latest nextjs (10.2.3) and babel version (7.14.3).

```
webpack: (config, { buildId, dev, isServer, defaultLoaders, webpack }) => {      
      // Option 1 fails with Cannot find module. It seems this one does still compile with mapbox-gl
      // config.resolve.alias['mapbox-gl'] = 'maplibre-gl'
      config.module.rules.push({
        resolve:{
          alias: {
            ...config.resolve.alias,
            // Option 2 via rules fails with Module not found: Error: Can't resolve 'mapbox-gl'
            'mapbox-gl': 'maplibre-gl'
          }
        }
      })
      return config
    }
```

**If the current behavior is a bug, please provide the steps to reproduce.**

I am using nextjs with react-mapbox-gl and maplibre-gl. Since react-mapbox-gl normally works with mapbox-gl the usage of the maplibre-gl **fork** is possible via aliases as mentioned here: https://github.com/alex3165/react-mapbox-gl/issues/924#issuecomment-755377958

Since this issue seems to be mainly related to webpack and not nextjs, I am asking the question here.

**What is the expected behavior?**

Within the node_module "react-mapbox-gl" all instances of mapbox-gl imports should be replaced with maplibre-gl.
Is there maybe a better resolve condition than "mapbox-gl": "maplibre-gl" to replace a module import within a node_module?

**Other relevant information:**
webpack version:  5.? (unfortunately I do not know, which version nextjs uses, I assume one of the latest)
Node.js version: 14.15.5
Operating System: Windows
Additional tools: Babel 7.14.3, typescript 4.1.3

**Comment by alexander-akait** [comment]
Please use `Discussions` for questions, you can use `require.resolve('name-of-module')`

**Comment by dennemark** [comment]
Thanks for the fast reply! I categorized it as a bug, sorry for the inconvenience...

I assume you mean to use require.resolve within the alias to have a direct path to the module. This however, still leads to the same result.

```
  alias: {
    ...config.resolve.alias,
    'mapbox-gl': require.resolve('maplibre-gl')
  }
```

**Comment by alexander-akait** [comment]
I can't reproduce it using pure webpack configuration (try it), please create example of the problem

**Comment by dennemark** [comment]
I will try.
One thing came to my mind. When using `next dev` instead of compilation through build or export, the "Cannot find module" error appears on the screen. After reloading the page, the error disappears. Could there be a delay in resolving the alias that is not considered by compilation?

**Comment by alexander-akait** [comment]
> Could there be a delay in resolving the alias that is not considered by compilation?

I think no, this of course may be due to a bug in not official plugin

**Comment by alexander-akait** [comment]
Can you run `npm ls maplibre-gl`? Do you use workspaces?

**Comment by dennemark** [comment]
I have created a repository. I hope this one works for you: https://github.com/dennemark/next-resolve-alias-issue
Running `yarn dev` and `yarn export` lead to cannot find module error. However `yarn build` seems to work, but I did not check the result. Interestingly yarn dev does not resolve after reload of page, as it does in my other project. However the issue should be the same.

The error happens with or without workspace. `npm ls maplibre-gl` returns: `-- maplibre-gl@1.14.0

**Comment by dennemark** [comment]
Even though the issue happens in above repository, it is probably good to mention my other config settings, concerning the delay.
```
      config.resolve.alias.process = 'process/browser'
      config.resolve.alias.stream = "stream-browserify"
      config.resolve.alias.zlib = "browserify-zlib"
      config.resolve.alias['mapbox-gl'] = require.resolve('maplibre-gl')
      config.plugins.push( new webpack.ProvidePlugin({
        process: 'process/browser',
        Buffer: ['buffer', 'Buffer'],
      }), )
      config.module.rules.push({
        test: /\.(woff|woff2|eot|ttf|otf)$/,
        use:{
          loader: 'url-loader',
        }
     })
    return config;
```

**Comment by alexander-akait** [comment]
We don't have any delay...

**Comment by alexander-akait** [comment]
Something in nestjs just use `require('mapbox-gl')` without webpack (so no aliases), if you look at stack trace - no webpack, I think SSR doesn't use webpack https://github.com/vercel/next.js/issues/877

**Comment by alexander-akait** [comment]
No problem with pure webpack, also we have a lot of test for resolving, so something wrong/bug/undocumented on nextjs side, sorry we can't fix it here

**Comment by alexander-akait** [comment]
I tried to use `jsconfig.json` with `paths` (found that this is done through him), but no luck too

**Comment by alexander-akait** [comment]
I think `Next.js` uses `externals` for packages inside `node_modules` for SSR, so `react-mapbox-gl` is loading from `node_modules` directly, you can check this in stack trace:
```
- /home/evilebottnawi/IdeaProjects/next-resolve-alias-issue/node_modules/react-mapbox-gl/lib/map.js
```

and aliases doesn't work here, because webpack doesn't touch this file (otherwise you will get an error on bundled file in `.next` directory).

**Comment by dennemark** [comment]
Thanks a lot for looking into this issue in such great length! The yarn dependencies solution might be the best option! I will have a look at it and let you know, how it worked out!

**Comment by dennemark** [comment]
The solution via dependencies seems to work! I tried it with yarn within a yarn workspace environment and I did not experience any issues yet. So I see this issue as resolved.
Thanks a lot again @alexander-akait , your explanation was very helpful!
