### ISSUE TITLE
TypeError: Cannot read property 'tap' of undefined

### ISSUE THREAD

**Issue by bucibucii** [webpack/webpack#13506]
# Bug report

**What is the current behavior?**
node_modules/webpack-deep-scope-plugin/index.js:16
        compilation.hooks.dependencyReference.tap(
                                              ^

TypeError: Cannot read property 'tap' of undefined

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
"webpack": "^5.38.1",
    "webpack-cli": "^4.7.0",
    "webpack-deep-scope-plugin": "^1.6.2",
    "webpack-dev-server": "^3.11.2",
node :v14.17.0
ubuntu 20.04

**Comment by alexander-akait** [comment]
You don't need `webpack-deep-scope-plugin` with webpack v5, please remove it
