### ISSUE TITLE
文档错误

### ISSUE THREAD

**Issue by clinfc** [webpack/webpack#13507]
在 `webpack5` 文档中，`css-loader` 可以使用 `to-string-loader` 或 `const css = require("./test.css").toString()`  将 `css-loader` 的结果转换为字符串，然而通过实际应用中以上两种方式均无法达到预期效果，故指出。

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

**Comment by alexander-akait** [comment]
Please use English
