### ISSUE TITLE
Webpack 5 production build takes ~20% more time than in webpack 4

### ISSUE THREAD

**Issue by SkReD** [webpack/webpack#13514]
# Bug report

**What is the current behavior?**

Production build in webpack 5 takes approximatly 20% more time to complete than in webpack 4. Turn minimization off via optimization.minimize makes webpack 5 actually faster then webpack 4.

Providing result of [10 build runs](https://github.com/SkReD/webpack5-performance-issue/blob/master/bench.json) by webpack 4 and by webpack 5:
```
webpack 4: 6.135080679988861 seconds
webpack 5: 7.854557122190793 seconds
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Repo for reproducing https://github.com/SkReD/webpack5-performance-issue

**What is the expected behavior?**
Build time is bigger about 0 - 5% maximum. Should be possible to configure optimization for reducing build time to webpack 4 values.

**Other relevant information:**
webpack version:  5.38.1
Node.js version: 16.3.0 (--cpu-profile fails on current LTS)
Operating System: windows 10 x64
Additional tools:

Providing logs of last runs from bench run

**webpack 4 profile logs**
[main-process.cpuprofile](https://github.com/SkReD/webpack5-performance-issue/blob/master/webpack4/main-process.cpuprofile)
![main-process](https://user-images.githubusercontent.com/938036/120779902-3d26ff00-c530-11eb-8179-86dd3c6d6671.png)

[child-process.cpuprofile](https://github.com/SkReD/webpack5-performance-issue/blob/master/webpack4/child-process.cpuprofile)
![child-process](https://user-images.githubusercontent.com/938036/120779912-3dbf9580-c530-11eb-967f-61344a7cb6ca.png)

**webpack 5 profile logs**
[main-process.cpuprofile](https://github.com/SkReD/webpack5-performance-issue/blob/master/webpack5/main-process.cpuprofile)
![main-process](https://user-images.githubusercontent.com/938036/120779954-49ab5780-c530-11eb-9328-f682b21b25b3.png)

[child-process.cpuprofile](https://github.com/SkReD/webpack5-performance-issue/blob/master/webpack5/child-process.cpuprofile)
![child-process](https://user-images.githubusercontent.com/938036/120779956-4adc8480-c530-11eb-86e9-d6a22877afab.png)

**Comment by alexander-akait** [comment]
Yes, because webpack have more abilities and more checks to prevent problems in code, also it is output more optimized code, please use this issue https://github.com/webpack/webpack/issues/12102 to report about perf problems, no need duplicate, otherwise we will have a lot of same issues and it will be more difficult to help. 

You can use `{ cache: { type: 'fllesystem' } }` to create persistent cache.

**Comment by alexander-akait** [comment]
> Turn minimization off via optimization.minimize makes webpack 5 actually faster then webpack 4.

Because you have new version of terser and supports more features, like classes, fields, nullish coalescing, big int and etc and they require more time.

Feel free to repost your information here https://github.com/webpack/webpack/issues/12102, maybe @fabiosantoscode can help here and look on perf regression in terser v5

**Comment by SkReD** [comment]
Made a repost but think that thread there is too bloat with different situations and we can use performance tag to track those issues.

Cache is not an option for fresh CI builds and cross branch building particulary (or at least its too hard to setup properly). 

Old terser gives relatively the same results @alexander-akait. It can be easilly checked with provided repo, so problem is in webpack i think.

**Comment by alexander-akait** [comment]
@SkReD if you disable `minimize` only `terser` plugin will be disable (but plugins API is simple), also please try different Node.js version, maybe regression on Node.js side

> Old terser gives relatively the same results @alexander-akait.

How you check it?

**Comment by alexander-akait** [comment]
webpack v4 uses `terser-webpack-plugin` v1, not v4 https://github.com/webpack/webpack/blob/v4.46.0/package.json#L28

**Comment by SkReD** [comment]
> try different Node.js version, maybe regression on Node.js side
Initially problem rised at 14.13.1 also stays at 12.8.2, 14.17.0 and 16.3.0. 16.3.0 used just for perf logs.

> How you check it?
Change version here and run bench https://github.com/SkReD/webpack5-performance-issue/blob/master/webpack5/package.json#L6

> webpack v4 uses terser-webpack-plugin v1, not v4 https://github.com/webpack/webpack/blob/v4.46.0/package.json#L28
`terser-webpack-plugin` installed directly in repo and included in webpack.config.js https://github.com/SkReD/webpack5-performance-issue/blob/master/webpack4/package.json#L6

**Comment by alexander-akait** [comment]
@SkReD You should use terser-webpack-plugin v1, because webpack v4 uses v1

**Comment by SkReD** [comment]
I dont understand why? terser-webpack-plugin v4 is modern and supports webpack 4. Why should i use so old version? Whats the point?

**Comment by alexander-akait** [comment]
> I dont understand why. terser-webpack-plugin v4 is modern and supports webpack 4. Why should i use so old version? What's the point?

You check webpack v4 and webpack v5 perf, but webpack v4 uses terser-weback-plugin v1 by default

Also try to disable `parallels` (i.e. `parallels`)

**Comment by SkReD** [comment]
`terser-webpack-plugin` is manually installed in `optimization.minimizer` section of config
```
  optimization: {
    minimizer: [new TerserPlugin()],
    ...
  }
```
is it not enough to fully replace `terser-webpack-plugin@^1` in webpack?

**Comment by alexander-akait** [comment]
Based on how your import `terser-webpack-plugin`

**Comment by SkReD** [comment]
https://github.com/SkReD/webpack5-performance-issue/blob/master/webpack.config.js#L39
```
const TerserPlugin = require(`${process.cwd()}/node_modules/terser-webpack-plugin`);
```

**Comment by SkReD** [comment]
> Also try to disable parallels (i.e. parallels)
Disabling `parallel` didn't help

**Comment by alexander-akait** [comment]
@SkReD I will look at repos in near future
