### ISSUE TITLE
Invalid chunkfile extensions with Webpack Module Federation and Webpack Compression plugin

### ISSUE THREAD

**Issue by raspy8766** [webpack/webpack#13518]
# Bug report

**What is the current behavior?**
When I build an application using the Webpack Module Federation plugin and [Webpack Compression plugin](https://github.com/webpack-contrib/compression-webpack-plugin), the `webpack/runtime/get` function does not return the proper chunk file extension. I am not sure if this is an issue with Webpack Module Federation or the Webpack Compression plugin, but since it seems to be a function defined in the `remoteEntry.js` file, I figured I'd start here.

The files are correctly compressed as seen here:
![image](https://user-images.githubusercontent.com/8533429/120865436-e8d94a80-c542-11eb-90cc-d4895b199cfc.png)

When you decompress the `remoteEntry.js.gz` file, you'll see that the `webpack/runtime/get` function is returning the wrong extension:
![image](https://user-images.githubusercontent.com/8533429/120866437-cba57b80-c544-11eb-9aad-f25db3618e47.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
Include both the Webpack Module Federation plugin and Webpack Compression plugin in your webpack config as shown below to create a compressed module federation remote:
```javascript
plugins: [
  new ModuleFederationPlugin({
    name: 'test',
    library: { type: 'var', name: 'test' },
    filename: 'remoteEntry.js',
    exposes: {
      '.': resolve(process.cwd(), entry),
    },
  }),
  new CompressionPlugin({
    exclude: /.map|.txt$/,
    deleteOriginalAssets: 'keep-source-map',
  }),
]
```

**What is the expected behavior?**
Should use the proper chunkfile extension (`.js.gz`) in the `webpack/runtime/get` function so that the chunk will load properly at runtime.

**Potential Workaround**
* Include the `.gz` extension in the webpack Module Federation plugin `filename` option (`filename: remoteEntry.js.gz`).
* Exclude the `.gz` extension in the Compression plugin `filename` option (`filename: '[path][base]'`).
* Set the `output.filename` field to `'index.js.gz'`
* Set the `output.chunkFilename` field to `'[id].[chunkhash].js.gz'`

This works, but it seems like a hack, and does not build source-maps into the build output despite using the `source-map-loader` (works properly in the previous config).

**Other relevant information:**
webpack version:
`v5.38.1`
Node.js version:
`v15.1.0`
Operating System: 
`macOS: 10.15.7`
Additional tools:

**Comment by alexander-akait** [comment]
@webpack-bot move to webpack-contrib/compression-webpack-plugin
