### ISSUE TITLE
API discussion: Deprecate use of loader!loader?config and require syntax?

### ISSUE THREAD

**Issue by AndrewRayCode** [webpack/webpack#1351]
[This documentation page](https://webpack.github.io/docs/loaders.html) is difficult to approach as a webpack newcomer. It starts off explaining a brand new, unique-to-webpack mini language that's only in string format: `require("my-loader!./my-awesome-module");` There are also sections like [this](https://webpack.github.io/docs/loaders.html#loader-context) where I have absolutely no idea what's going on.

This first comment is from a place of admitted ignorance: I haven't seen the odd `require()` syntax (mentioned above) used in any production webpack builds. It's unclear when and why you would use that specific require syntax inline in a file. What **appears to be much more common** is using `{ ... loaders: ... }` in your config file. I've asked a few times in chat rooms and haven't gotten a satisfactory answer for when to use which. This indicates to me that the API is confusing and avoided by developers.

When using config file loaders, another confusing point is `loader: 'loader1!loader2'` vs `{ loaders: [ 'loader1', 'loader2' ] }`. The second one seems a lot more intuitive and doesn't require a new language to understand. I also suspect those are semantically equivalent, but the docs don't give any clues and no one I've asked seems to know. If they are equivalent, I'm not sure why the first syntax would be preferred.

As a newcomer to webpack (and now a moderately experienced user), the require syntax is confusing and never clearly explained when or why to use it. In a cursory glance of my peers, the only use case of loaders is used in config files (not inline requires). And to me, something like

```
{ test: ...,  loaders: [{ loader: 'a', config: { limit: 2048 }] } 
```

is easier for a newcomer to approach than a new mini string language.

**Some thoughts and possible courses of action:**

**1.** Discussion of deprecating the `require()` loader syntax (I again admit my own ignorance of not knowing when to use it / having seen it used in real world projects)
**2.** Rewrite of the [loaders](https://webpack.github.io/docs/loaders.html) documentation page. Specifically, the `require()` case seems to be rarely used, yet it's the first section of that page, with the most common case a few paragraphs down.
**3.** Possibly allowing a non-webpack-string-language loader syntax vanilla javascript object in the config file (related to but not dependent on point 1)
**4.** Clearly documenting the difference between `[ 'a', 'b' ]` and `a!b` with an emphasis on the most common cases.
**5.** Maybe better separation of "writing a loader" and "loaders" into two different doc pages?

I'm aware that all of the documentation pages have edit buttons on them, and I could try to implement some of this myself. However, I don't feel confident enough in my webpack config knowledge to make any of these changes. The docs rarely mention _why_ certain APIs are the way they are, which would likely result in my edits removing something critical that I didn't realize was critical.

**Comment by SimenB** [comment]
> `loader: 'loader1!loader2'` vs `{ loaders: [ 'loader1', 'loader2' ] }`

In my opinion, the first is a lot less writing, but if you find it confusing you can pass an array. I think that's the meaning behind it.
Otherwise no comment :grin:

**Comment by taurose** [comment]
One reason I see for using `require('loader!./file')` is if you're using a non-standard or "magic" loader which you want to make explicit in order to avoid confusion, e.g. `var Worker = require('worker!./file.js');`.

**Comment by jquense** [comment]
another reason for the request loader syntax is that some loaders simply output another require() with additional loaders specified in the request.

Additionally webpack loaders specified in requests run a different time than the config ones. Its a helpful syntax for doing a bunch of stuff that you can't do by specifying loaders in a config, like overriding the default loader for a file, just once. for a practical example we use inline loaders to tell webpack to [fetch metadata for a file instead of the file content](https://github.com/react-bootstrap/react-overlays/blob/master/examples/App.js#L8)

**Comment by bebraw** [comment]
@sokra Webpack 2 might be a good chance to visit this topic.

**Comment by jquense** [comment]
I can't see this behavior going away anytime soon a large amount of loaders are built on this syntax internally.

**Comment by mbtts** [comment]
One (obvious) approach might be to offer both versions of the syntax - using tabs - so the reader can pick which they find most comfortable:

```
   ------------------------------
   | Object Config | URL Config |
------------------------------------
```

As a newcomer to webpack (first week) I relate immediately to the comments by @DelvarWorld. It was also a stumbling block to comprehension.
