### ISSUE TITLE
Weboack 5 Module Federation error in shared

### ISSUE THREAD

**Issue by MaxusAdmin** [webpack/webpack#13517]
# Bug report

**What is the current behavior?**

**webpack version: 5.37.0
react version: 17.0.2
react-dom version: 17.0.2**

i created project for demostation my problem -> [module_federation_test](https://github.com/MaxusAdmin/module_federation_test)

I have two apps:

1. **host_app** is app which render remote app on different port. **_it works on localhost:8080_**
2. **remote_app** is app which rende only - hello world, good luck. **_it works on localhost:8081_**

And my projec didn't work.

when i didn't use shared i had error:
```diff
- Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
-   1. You might have mismatching versions of React and the renderer (such as React DOM)
-   2. You might be breaking the Rules of Hooks
-   3. You might have more than one copy of React in the same app
- ....... etc
```

when i used shared i had error:
```diff
- Uncaught Error: Shared module is not available for eager consumption: webpack/sharing/consume/default/react/react
-    at Object.__webpack_require__.m.<computed> (consumes:132)
-    at __webpack_require__ (bootstrap:24)
- ....... etc
```
in second option i used this config
#### for host_app
```js script
new ModuleFederationPlugin({
      name: "host",
      filename: 'static/js/remoteEntry.js',
      remotes: {
        remote_app: "remote_app@http://localhost:8081/static/js/remoteEntry.js",
      },
      shared: [
        {
          react: {
            singleton: true,
            eager: true,
            requiredVersion: deps.react
          },
          "react-dom": {
            singleton: true,
            eager: true,
            requiredVersion: deps["react-dom"]
          }
        }
      ]
    })
```
#### for remote_app
```js script
new  ModuleFederationPlugin({
      name: 'remote_app',
      library: { type: "var", name: 'remote_app' },
      filename: 'static/js/remoteEntry.js',
      exposes: {
        "./RootApp": "./src/apps/RemoteApp",
      },
      shared: [
        {
          react: {
            singleton: true,
            eager: true,
            requiredVersion: deps.react
          },
          "react-dom": {
            singleton: true,
            eager: true,
            requiredVersion: deps["react-dom"]
          }
        }
      ]
    })
```

I found infomation about eager react on [react_eager](https://webpack.js.org/concepts/module-federation/), but it isn't work
![image](https://user-images.githubusercontent.com/22521593/120852802-602ece80-c583-11eb-9ed3-50cacd886abf.png)

I need help. Maybe i don't understand philosophy or other things which are important for solve my problem.

p.s
I tried lots of option, but it didn't work.
I made test project on GitHub (link above in the problem description) when anyone can test their theory of the truthful version code.

Please don't tell me that it is problem in react =)

**Comment by XiaofengXie16** [comment]
When you import the bootstrap, you need use dynamic import not your regular module import.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#dynamic_imports

Do this in your index file 
```js
import('./bootstrap');
```

**Comment by MaxusAdmin** [comment]
> When you import the bootstrap, you need use dynamic import not your regular module import.
> 
> https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#dynamic_imports
> 
> Do this in your index file
> 
> ```js
> import('./bootstrap');
> ```
> 
> Code: https://github.com/XiaofengXie16/module_federation_test
> 
> With the use of dynamic import, it allows webpack to interface with the remote's remoteEntry file.
> 
> With that change above, also remove the `eager` option from both of your config.

ok, i did that you said, 
i changed my bootstrap file on this
```js script

import("./bootstrap").then(() => {});

```
but i hav new error
```diff
- Uncaught ScriptExternalLoadError: Loading script failed.
- (missing: http://localhost:8081/static/js/remoteEntry.js)
- while loading "./RootApp" from webpack/container/reference/remote_app
-    at Object.webpack/container/reference/remote_app (remoteEntry.js":1)
-    at __webpack_require__ (bootstrap:24)
-    at handleFunction (remotes loading:33)
-    at remotes loading:52
-    at Array.forEach (<anonymous>)
-    at Object.__webpack_require__.f.remotes (remotes loading:15)
-    at ensure chunk:6
-    at Array.reduce (<anonymous>)
-    at Function.__webpack_require__.e (ensure chunk:5)
-    at Function.fn.e (hot module replacement:81)
```

and if i remove all shared option i will hav eager error
```diff
- Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
- 1. You might have mismatching versions of React and the renderer (such as React DOM)
- 2. You might be breaking the Rules of Hooks
- 3. You might have more than one copy of React in the same app
- See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
-    at resolveDispatcher (react.development.js:1476)
-    at useEffect (react.development.js:1519)
-    at __WEBPACK_DEFAULT_EXPORT__ (RemoteApp.tsx:5)
-    at renderWithHooks (react-dom.development.js:14985)
-    at updateFunctionComponent (react-dom.development.js:17356)
-    at mountLazyComponent (react-dom.development.js:17677)
-    at beginWork (react-dom.development.js:19055)
-    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
-    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
-    at invokeGuardedCallback (react-dom.development.js:4056)
```

**Comment by XiaofengXie16** [comment]
Could you try remove the then statement? Also , if I run the code below does it work for you (it is modified based on the code you provided)? https://github.com/XiaofengXie16/module_federation_test

**Comment by MaxusAdmin** [comment]
> Could you try remove the then statement? Also , if I run the code below does it work for you (it is modified based on the code you provided)? https://github.com/XiaofengXie16/module_federation_test @MaxusAdmin

It's works )))))))))))
i understood.
If i imported another file in bootstrap i will hev lots of problems
I changed my bootstrap file on this
```ts script
import React from 'react';
import ReactDOM from 'react-dom';
import Wrapper from './apps/MainPage';

// https://github.com/basscss/basscss
import 'basscss-margin/css/margin.css';
import 'basscss-padding/css/padding.css';

import 'box-shadows-css/box-shadows.css';

import 'rsuite/lib/styles/themes/default/index.less';
import './static/styles/default.less';

const SPA = () => (
    <Wrapper />
);

ReactDOM.render(
    <React.StrictMode>
        <SPA />
    </React.StrictMode>,
    document.getElementById('root'),
);

```
it was my first problem) 

and next i changed my module federation config as you said)
Thank you!!!

**Comment by XiaofengXie16** [comment]
@MaxusAdmin  No problem, I am glad I can help.

**Comment by alexander-akait** [comment]
@XiaofengXie16 Please do not open again issue, it was moved in `Discussions` because here was bug in your code, you will be in my todo on help today, we have a lot issues and sometimes we simply do not have enough time to help everyone, but this does not mean that we will not help you, just be patient
