### ISSUE TITLE
No need in asterisks in source map

### ISSUE THREAD

**Issue by ivn-cote** [webpack/webpack#1352]
I have to set my sources publicly accessible (for Senty). So all paths in source map should be relative urls. I've set configuration as so

```
    output: {
      path: __dirname + '/nstatic/public/compiled/',
      filename: '[name].js',
      devtoolModuleFilenameTemplate: getSourceMapPublicPath,
      devtoolFallbackModuleFilenameTemplate: getSourceMapPublicPath,
      sourceMapFilename: './[file].map',
      publicPath: '/nstatic/public/compiled/'
    },
    devtool: 'source-map',
.....
function getSourceMapPublicPath(info) {
  return '/ololo/' + info.resourcePath;
}
```

Debugging in the browser is working, thanks! But in source map I find many of cases, when asterisks are concatenated to the path, e.g. `/ololo/./~/react/lib/ReactPropTransferer.js***`

**Comment by bebraw** [comment]
Can you check with webpack 2?

**Comment by garaboncias** [comment]
Webpack 2 do the same. What those asterisks means? Sometimes has many of them. ex.:
importwizard.ts***********
