### ISSUE TITLE
Asset Modules with source mode to load SVG, result as string instead of element

### ISSUE THREAD

**Issue by SevlaMare** [webpack/webpack#13534]
# Bug report

**What is the current behavior?**
SVG is loaded embed as string into HTML instead of a SVG element, so is not render, using the new Asset Modules.

**If the current behavior is a bug, please provide the steps to reproduce.**
drop this config into your webpack.config.js:
```
      {
        test: /\.svg/,
        type: 'asset/source',
      },
```
import a SVG into your React component, and insert it:

```
      import menu from './icon/menu.svg';
      <span>{menu}</span>
```
      
now after build, it will be as a string in your HTML, and it will not render. eg.:

      "<svg>...</svg>" 

      

---
If it helps, the setup I'm using on webpack.config.js is here:
https://gist.github.com/SevlaMare/449bb0b1a3ff8af7ff17b32d09fc59c2

And package.json:
https://gist.github.com/SevlaMare/ff4dd5954097b8d82ea54f7f9eee1eec
![screenshot](https://user-images.githubusercontent.com/40220867/121091552-8c835e80-c7c0-11eb-8cad-6e44a893b039.png)

**What is the expected behavior?**
To load the SVG as element.

The SVG should be load as HTML element, instead of a string with the content inside, so it can render properly.

**Other relevant information:**
webpack version:  5.24.4
Node.js version: v14.16.1
Operating System:  Windows 10 build 19042
Additional tools:

**Comment by alexander-akait** [comment]
You should fix it in your app, sorry won't fix, there is no HTML in JS, only strings
