### ISSUE TITLE
webpackPrefetch failed with webpack version >= 5.25.0

### ISSUE THREAD

**Issue by srigar** [webpack/webpack#13541]
# Bug report

**What is the current behavior?**
Server should get start without any error with **webpackPrefetch** in dynamic import. But it is failed to start if the webpack version is >= 5.25.0 and it is working fine if webpack version <= 5.24.0. 

Got below error while starting server
```js
/Users/Documents/dev/product/build/server.js:21367
/******/ webpack_require.O(0, ["server"], () => (), 5);
^

SyntaxError: Unexpected token ')'
at wrapSafe (internal/modules/cjs/loader.js:1053:16)
at Module._compile (internal/modules/cjs/loader.js:1101:27)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
at Module.load (internal/modules/cjs/loader.js:985:32)
at Function.Module._load (internal/modules/cjs/loader.js:878:14)
at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
at internal/main/run_main_module.js:17:47
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Issue is because of adding webpackPrefetch in below import

```js
import loadable from '@loadable/component';

const Component = loadable(
    () =>
        import(
            /* webpackPrefetch: true */ /* webpackChunkName: "compChunk" */ '../component'
        ),
    { ssr: false }
);
```

**What is the expected behavior?**

Server should get start without any error with **webpackPrefetch** in dynamic import

**Other relevant information:**
webpack version:  5.38.0
Node.js version:  12.18.4
Operating System: Mac 10.14.6

**Comment by akgupta0777** [comment]
Not reproducible with webpack version 5.38.1.
Please give us more info.
Also show us webpack config

**Comment by alexander-akait** [comment]
Duplicate https://github.com/webpack/webpack/issues/12993, feel free to feedback or provide example how we can reproducible if it is no duplicate
