### ISSUE TITLE
watchOptions is not copied in Compiler.js properly

### ISSUE THREAD

**Issue by wbecker** [webpack/webpack#1354]
At https://github.com/webpack/webpack/blob/master/lib/Compiler.js#L26 it should use [Object.assign()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign), not [Object.create()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create). 

Object.create is for creating new objects with a prototype...

Because of this poll:true cannot be set in webpack.options under watchOptions.

**Comment by sharang-d** [comment]
I was thinking of taking this up. The conversation in https://github.com/webpack/webpack/pull/1367 is confusing though. Can someone please confirm if this is still a to-do? 

@wbecker @sokra @bebraw

**Comment by bebraw** [comment]
@sharang-d `this.watchOptions = assign({}, watchOptions);` would probably do the trick, yeah. Note that webpack depends on `object-assign` now so we could just use that to create the clone (I think that was the intention there).

You could try that and report how it goes.

**Comment by sharang-d** [comment]
What I actually meant to ask was if the last comment on the thread by @wbecker was true in which case this issue would be closed.

> Is not a legit bug? Why so?
