### ISSUE TITLE
jsonp chunk loading doesn't work on legacy platforms (Function.prototype.bind)

### ISSUE THREAD

**Issue by llooz** [webpack/webpack#13545]
**Do you want to request a *feature* or report a *bug*?**

bug / feature

**What is the current behavior?**

Jsonp chunk loading uses `Function.prototype.bind` and on old platforms where it's not available there is no way to use a polyfill.
https://github.com/webpack/webpack/blob/ff1b314d30fbf996dc0acf37b7b789eab8ca33e1/lib/web/JsonpChunkLoadingRuntimeModule.js#L419
Using the `entries` like this is too late 
```
entry: {
  bootstrap: [
     'core-js/modules/es.function.bind',
     // needed for Webpack dynamic import
     // https://babeljs.io/docs/en/babel-plugin-syntax-dynamic-import
     'core-js/modules/es.promise',
     'core-js/modules/es.array.iterator',
     './src/bootstrap',
   ],
},
``` 

**If the current behavior is a bug, please provide the steps to reproduce.**

Try to use dynamic imports where `Function.prototype.bind` isn't available.

**What is the expected behavior?**

We develop web apps for legacy platforms and by heavily using babel and core-js we didn't have any issues so far.

We know that we can't expect Webpack to automagically work on legacy platforms but we wan't to have a way to polyfill it if necessary.
In this specific case we just need to require `core-js/modules/es.function.bind` before the jsonp module.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

- TV Samsung Orsay 2012 
- Webpack 5.37.0

**Comment by alexander-akait** [comment]
Sorry webpack dones't polyfill old browser itself, you need do it in own application side, because you want to use polyfill runtime you need manually add polyfill before running webpack generated code, sorry we can't it here. 

Also you can create own plugin for this, example https://github.com/gregberge/loadable-components/issues/636#issuecomment-742646656
