### ISSUE TITLE
Prop `className` did not match

### ISSUE THREAD

**Issue by biggywk** [webpack/webpack#13547]
Webpack 5 causes className of client-side didn't match with server-side and UI go wrong when refreshing the page.
UI won't go wrong when using Webpack 4.

  "dependencies": {
    "@material-ui/core": "^4.11.4",
    "@material-ui/icons": "^4.11.2",
    "@material-ui/lab": "*",
    "next": "^10.0.7",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "swr": "^0.3.11"
  },
  "devDependencies": {
    "typescript": "^3.9.9",
    "@types/node": "^12.20.4",
    "@types/react": "^16.14.4",
    "@types/react-dom": "^16.9.11"
  }

# Bug report

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

**Comment by alexander-akait** [comment]
Not related to wetback, sorry, please ask this in `next` repo
