### ISSUE TITLE
Loading assets via a loader's `this.loadModule()` doesn't emit asset files

### ISSUE THREAD

**Issue by bastimeyer** [webpack/webpack#13552]
# Bug report

**What is the current behavior?**
When calling `this.loadModule( "some-path", callback )` from a loader while `some-path` is defined as an asset in the module rules (eg. `type: "asset/source"`), webpack won't emit `some-path` as an asset.

**If the current behavior is a bug, please provide the steps to reproduce.**
See my simple reproduction repo here: https://github.com/bastimeyer/webpack-load-module-asset

Relevant files
- https://github.com/bastimeyer/webpack-load-module-asset/blob/b6c670f2011ba7d4cc0cf2def17df0359b3c98c6/webpack.config.js
- https://github.com/bastimeyer/webpack-load-module-asset/blob/b6c670f2011ba7d4cc0cf2def17df0359b3c98c6/src/index.js
- https://github.com/bastimeyer/webpack-load-module-asset/blob/b6c670f2011ba7d4cc0cf2def17df0359b3c98c6/src/loader.js

Build log (verbose stats):
https://github.com/bastimeyer/webpack-load-module-asset/runs/2794477055?check_suite_focus=true#step:5:1

**What is the expected behavior?**
Webpack should emit the asset loaded from within the loader just like when loading the asset from an import / require call / etc, or when using the file-loader for emitting resolved asset files.

**Other relevant information:**
webpack version: 5.38.1 (currently the latest version)
Node.js version: 16.3.0 (irrelevant)
Operating System: Arch Linux (irrelevant)
Additional tools: yarn (irrelevant)

**Comment by alexander-akait** [comment]
You need specif syntax here in this case: ``${this.resourcePath}.webpack[asset/source]!=!${request}`,`

**Comment by bastimeyer** [comment]
The point is that this was working correctly on webpack4 while using the `file-loader` (or any other loader/combination), and nothing in the migration guide, changelog or documentation is describing this breaking change.

I am not sure what you mean with "specific syntax" in the context of the loader's `loadModule` method and passing it an arbitrary request string.

https://webpack.js.org/api/loaders/#thisloadmodule
> `loadModule(request: string, callback: function(err, source, sourceMap, module))`
> Resolves the given request to a module, applies all configured loaders and calls back with the generated source, the sourceMap and the module instance (usually an instance of `NormalModule`).

Even though the resolved+loaded asset doesn't get emitted in the output, the `module` parameter of the callback function (instance of `NormalModule`) has `emit` set to `true` on its `generator` property (instance of `AssetGenerator`).

**Comment by alexander-akait** [comment]
You need pass specific syntax to `request`, otherwise built-in parser/generator will not work

**Comment by bastimeyer** [comment]
Your suggestion does not work and no asset file is being emitted by the generator. See my demo-changes and the build log:
- https://github.com/bastimeyer/webpack-load-module-asset/commit/307c62a90b13abba6d53fa2cf923c02d56bb1509
- https://github.com/bastimeyer/webpack-load-module-asset/runs/2802577559?check_suite_focus=true#step:5:7

My intention of this issue thread is not seeking for help or asking a question, but reporting a bug/regression in Webpack 5 as it has deprecated the `{file,raw,url}-loader`s in favor of native asset modules and currently it's not possible to load assets from within a loader (while loading them from regular imports works - of course).

Also, special syntax should not be needed for this, because otherwise it's a breaking change, and this is not documented. And if this is indeed needed, then how is a loader supposed to know when a certain request is an asset and when not? This is not the job of the loader but the module rules configuration and webpack resolving it correctly.

----

I haven't found any documentation in regards to this request syntax and thus took a look at the code and found the responsible parts in the `resolve` hook of the `NormalModuleFactory`.
- https://github.com/webpack/webpack/blob/6a4cb8e39d717ef3d710eaebd3db31accf229dec/lib/NormalModuleFactory.js#L353-L374
- https://github.com/webpack/webpack/blob/6a4cb8e39d717ef3d710eaebd3db31accf229dec/lib/NormalModuleFactory.js#L506-L514

While setting breakpoints and debugging through this code, it looks like a simple type override, but unfortunately it doesn't do anything in this case. The `this.ruleSet.exec` call from above which is supposed to find the rule where the asset type is defined (I think) doesn't return anything either.

**Comment by bastimeyer** [comment]
Still broken in the latest release, v5.52.1.

Would submitting a pull request with a failing test help with this in addition to my already posted reproduction repo?
Why has this not been acknowledged as a bug/regression?

As said, this is a regression with asset files and definitely a problem since webpack 5 has officially deprecated the file-loader.
https://webpack.js.org/guides/asset-modules/

Just as a short description how I've been running into this problem: I'm using a custom loader for parsing JSON files which have entries for certain file paths which need to be resolved and emitted as asset files. Webpack5 doesn't allow me to do this without the deprecated file-loader. Declaring those file paths as assets in the webpack5 config does not work, hence this bug report. The "specific syntax" mentioned above does not work and it shouldn't be required either, as described in my previous post.

**Comment by decademoon** [comment]
Is there no webpack 5 loader API to load a module as if it were `require`d and get the final generated module source (after all loaders *and* asset transformation)?

**Comment by vankop** [comment]
First, I would like to make clear what 
```
loadModule(request: string, callback: function(err, source, sourceMap, module))
```
does

> Resolves the given request to a module, applies all configured loaders and calls back with the generated source, the sourceMap and the module instance (usually an instance of NormalModule).

This means webpack applies ALL settings to this module ( like `import x from "x"` ) and return source, map, and module itself, **but** that does not mean that this module depends on original module ( and will be added in code generation results/output ).

So..
@alexander-akait you don't need `${this.resourcePath}.webpack[asset/source]!=!x` request for that.
@bastimeyer I don't think that webpack will support what you expect by default, but it could make a sense to make this possible. My question is what is your use case for that?

**Comment by bastimeyer** [comment]
> My question is what is your use case for that?

I've already explained it here
https://github.com/webpack/webpack/issues/13552#issuecomment-920433570

> Just as a short description how I've been running into this problem: I'm using a custom loader for parsing JSON files which have entries for certain file paths which need to be resolved and emitted as asset files. Webpack5 doesn't allow me to do this without the deprecated file-loader. Declaring those file paths as assets in the webpack5 config does not work, hence this bug report. The "specific syntax" mentioned above does not work and it shouldn't be required either, as described in my previous post.

To give you an explicit example:
https://github.com/streamlink/streamlink-twitch-gui/blob/v2.0.0/src/app/package.json#L18
https://github.com/streamlink/streamlink-twitch-gui/blob/v2.0.0/build/tasks/webpack/loaders/parse-json-loader.js#L25-L37
https://github.com/streamlink/streamlink-twitch-gui/blob/v2.0.0/build/tasks/webpack/configurators/nwjs.js#L24-L45
https://github.com/streamlink/streamlink-twitch-gui/blob/v2.0.0/build/tasks/webpack/configurators/stylesheets-and-assets.js#L74-L82

Also see the example repo I've posted in the OP (just a simple loader demonstrating the issue, though)
https://github.com/bastimeyer/webpack-load-module-asset/tree/b6c670f2011ba7d4cc0cf2def17df0359b3c98c6

**Comment by decademoon** [comment]
@bastimeyer That’s literally my exact use case too.

See https://github.com/usmanyunusov/webpack-webmanifest-loader for a webpack 5 loser which does a similar thing. It loads a webmanifest file (json) and replaces paths to image assets with the final bundled path of that asset. It uses child compilers and stuff which goes over my head.

**Comment by vankop** [comment]
we discussed this internally.. In my opinion there is no need to create specific api for that. mostly you always need an url to this asset. So in case:
>Just as a short description how I've been running into this problem: I'm using a custom loader for parsing JSON files which have entries for certain file paths which need to be resolved and emitted as asset files. Webpack5 doesn't allow me to do this without the deprecated file-loader. Declaring those file paths as assets in the webpack5 config does not work, hence this bug report. The "specific syntax" mentioned above does not work and it shouldn't be required either, as described in my previous post.

You can transform your json to js
json
```json
{ "asset": "./a.txt" }
```
transformed
```js
import a from "./a.txt";

export default { "asset": a }
```
