### ISSUE TITLE
webpack5 > webpack.IgnorePlugin  failure

### ISSUE THREAD

**Issue by HYzihong** [webpack/webpack#13557]
# Bug report

**What is the current behavior?**

In the process of learning Webpack 5

```bash

> webpack5-ignoreplugin@1.0.0 build
> webpack

asset main.js 628 KiB [emitted] (name: main) 1 related asset
runtime modules 1020 bytes 4 modules
modules by path ./node_modules/moment/dist/locale/*.js 407 KiB 135 modules
./src/index.js 300 bytes [built] [code generated]
./node_modules/moment/dist/moment.js 150 KiB [built] [code generated]
./node_modules/moment/dist/locale/ sync ^\.\/.*$ 3.21 KiB [optional] [built] [code generated]
webpack 5.38.1 compiled successfully in 1237 ms

```

Expectations for main.js <=170kb

**If the current behavior is a bug, please provide the steps to reproduce.**

```javascript
// src/index.js

import moment from 'moment'
console.log(moment().format('MMMM Do YYYY, h:mm:ss a'));

```

```javascript

// webpack.config.js

const path = require('path')
const webpack = require('webpack');

module.exports = {
  mode:'none',
  devtool:'source-map',
  context:process.cwd(),
  entry:'./src/index.js',
  output:{
    path: path.resolve(__dirname, 'dist'),
    filename: '[name].js',
  },
  resolve: {
    modules:['node_modules'],
    mainFields:['jsnext:main','main']
  },
  plugins:[
    new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/),
  ]
}


```

**What is the expected behavior?**

ignore

moment>dist>locale 

**Other relevant information:**
webpack version:  ^5.38.1
Node.js version: v12.16.3
Operating System:  mac 10.15.7
Additional tools:

**Comment by alexander-akait** [comment]
Please use:
```
new webpack.IgnorePlugin({
  resourceRegExp: /^\.\/locale$/,
  contextRegExp: /moment/,
}),
```

From docs:
```
// Supported in webpack 4 and earlier, unsupported in webpack 5:
new webpack.IgnorePlugin(resourceRegExp, [contextRegExp]);
```

**Comment by alexander-akait** [comment]
We should throw an validation error

**Comment by myNameIsDu** [comment]
@alexander-akait I found that it had validation code
```javascript
	constructor(options) {
		validate(schema, options, {
			name: "Ignore Plugin",
			baseDataPath: "options"
		});
		this.options = options;

		/** @private @type {Function} */
		this.checkIgnore = this.checkIgnore.bind(this);
	}
```

```javascript
{
  "title": "IgnorePluginOptions",
  "anyOf": [
    {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "contextRegExp": {
          "description": "A RegExp to test the context (directory) against.",
          "instanceof": "RegExp",
          "tsType": "RegExp"
        },
        "resourceRegExp": {
          "description": "A RegExp to test the request against.",
          "instanceof": "RegExp",
          "tsType": "RegExp"
        }
      }
    },
    {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "checkResource": {
          "description": "A filter function for resource and context.",
          "instanceof": "Function",
          "tsType": "((resource: string, context: string) => boolean)"
        }
      }
    }
  ]
}
```
And he really doesn't throw errors, which I think are validate errors

**Comment by alexander-akait** [comment]
Yes, feel free to send a PR with fix, just remove it from schema

**Comment by myNameIsDu** [comment]
> Yes, feel free to send a PR with fix, just remove it from schema

Sorry, there are some problems mentioned above, should be increased
```javascript
"required": [ "resourceRegExp"]
"required": [ "checkResource" ]
````
I will send a PR later

**Comment by jcamden** [comment]
I'm a little confused. Can you guys help me understand why this IgnorePlugin config (for co-located tests) doesn't work with Webpack 5 enabled (but does work with Webpack 4):

const webpack = require('webpack');

```
module.exports = {
  future: {
    // very sadly, must revert to Webpack 4 in order for IgnorePlugin (below) to successfully ignore co-located tests
    webpack5: false,
  },
  webpack: (config) => {
    config.plugins.push(
      new webpack.IgnorePlugin({
        resourceRegExp: /.test.(ts|tsx)$/,
      })
    );
    return config;
  },
};
```
It seems like it would be fine, vis-a-vis [the relevant docs](https://webpack.js.org/plugins/ignore-plugin/), but it doesn't work. Am I gathering from this thread that both resourceRegExp and a checkResource filter are required? That would be surprising. Can you help understand?

**Comment by myNameIsDu** [comment]
@jcamden from this configuration, it works in Webpack5. Can you give an example of an error

**Comment by myNameIsDu** [comment]
@jcamden 
```javascript
/\.test\.(ts|tsx)$/
````
you can try again

**Comment by myNameIsDu** [comment]
```javascript
/\.test\.(ts|tsx)$/
```
you can try this, if not you can provide an error example

**Comment by jcamden** [comment]
Thanks @myNameIsDu . I was intentionally not escaping the periods, but I should have added a glob, and you're right that my regex probably should include escaped periods to be more specific: (i.e. `/.*\.test(\.).*(ts|tsx)$/` ) Here's what I'm running:
```
const webpack = require('webpack');

module.exports = {
  future: {
    webpack5: true,
  },
  webpack: (config) => {
    config.plugins.push(
      new webpack.IgnorePlugin({
        resourceRegExp: /.*\.test(\.).*(ts|tsx)$/,
      })
    );
    return config;
  },
};
```
Seems to work with Webpack 4, but build fails with Webpack 5 enabled: 
```
info  - Creating an optimized production build  
Failed to compile.

HookWebpackError: Cannot read property 'slice' of undefined


> Build error occurred
Error: > Build failed because of webpack errors
    at /home/.../next/dist/build/index.js:17:924
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at runNextTicks (node:internal/process/task_queues:63:3)
    at processImmediate (node:internal/timers:437:9)
    at async Span.traceAsyncFn (/home/...trace.js:6:584)
```

I assume this means that the modified Webpack config didn't add up to a proper array in some regard, but I'm not sure.

**Comment by jcamden** [comment]
Ah, by the way, it looks like pageExtensions is the best solution to the problem of co-location: https://github.com/vercel/next.js/discussions/23959#discussioncomment-894210

**Comment by harish-sethuraman** [comment]
@alexander-akait  Is it enough if we change the `anyOf` to `oneOf` in the [ignorePlugin.json](https://github.com/webpack/webpack/blob/master/schemas/plugins/IgnorePlugin.json) to allow one of the two objects and throw error ?
