### ISSUE TITLE
webpack gets stuck in compile stage

### ISSUE THREAD

**Issue by jedwards1211** [webpack/webpack#1355]
All of the sudden, without me changing anything in my Webpack config, Webpack started in the middle of building modules.  Unlike other issues, this is before the the optimizing chunk assets stage and involves no UglifyJS.  I've repro'd with:
* Webpack 1.10.1 and 1.11.0
* Node v0.10.36
* Ubuntu 14.10 64-bit.
When it hangs, its CPU usage appears to go to zero.
I don't know if Webpack or a loader is at fault, but if loaders could be at fault, is there a way for me to get better debug output?

`webpack.config.client.js`:

```
var path = require('path');
var webpack = require('webpack');

module.exports = {
  entry: [
    'babel/polyfill',
    './client',
  ],
  output: {
    path: path.join(__dirname, 'assets'),
    filename: 'client.bundle.js',
    publicPath: '/assets/',
  },
  resolve: {
    extensions: ['', '.js', '.jsx'],
    alias: {
      'mindfront-react-components': path.resolve(__dirname, 'mindfront-react-components'),
    }
  },
  module: {
    loaders: [
      {
        test: /\.jsx?$/,
        loader: 'babel?stage=0',
        exclude: /node_modules/,
      }, 
      {
        test: /\.css$/,
        loader: 'style-loader!css-loader'
      }, 
      {
        test: /\.sass/,
        loader: 'style-loader!css-loader!sass-loader?indentedSyntax&outputStyle=expanded&' +
        "includePaths[]=" +
        (path.resolve(__dirname, "./node_modules"))
      }, 
      {
        test: /\.scss/,
        loader: 'style-loader!css-loader!sass-loader?outputStyle=expanded&' +
        "includePaths[]=" +
        (path.resolve(__dirname, "./node_modules"))
      }, 
      {
        test: /\.(png|jpg)$/,
        loader: 'url-loader?limit=8192'
      },
    ],
  },
};
```

`webpack.config.client.dev.js`:

```
var webpack = require('webpack');
var config = require('./webpack.config.client');
var _ = require('lodash');

var devProps = require('./devProps');

var config = module.exports = _.assign(_.cloneDeep(config), {
  devtool: 'eval',
  entry: [
    'webpack-dev-server/client?' + devProps.baseUrl,
    'webpack/hot/only-dev-server',
  ].concat(config.entry),
  output: _.assign(_.cloneDeep(config.output), {
    publicPath: devProps.baseUrl + '/assets/',
  }),
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoErrorsPlugin(),
    new webpack.PrefetchPlugin('react/addons'),
  ],
  devServer: {
    publicPath: devProps.baseUrl + '/assets/',
    hot: true,
    historyApiFallback: true,
    contentBase: devProps.contentBase,
  }
});

// inject react-hot loader

var jsLoader = _.find(config.module.loaders, function(loader) {
  return loader.test.test('.js');
});

if (jsLoader) {
  jsLoader.loader = 'react-hot!' + jsLoader.loader;
}
```

**Comment by jedwards1211** [comment]
Okay, I've determined that the sass-loader is hanging it -- when I make it load sass files with url-loader instead, it finishes.  There are issues in the sass-loader github project about this.
The native code sass-loader depends on has been causing problems for quite awhile.

**Comment by davedx** [comment]
FWIW upgrading sass-loader to v2 fixed this for me.

**Comment by jedwards1211** [comment]
Yup, they finally figured out a workaround for deadlock issues in `node-sass`.

**Comment by lenciel** [comment]
how did you figure out it is sass-loader/node-sass blocking the build?

**Comment by leoselig** [comment]
This issue is ancient (in JS-time). But I'd like to add that our webpack compilation was stuck randomly at certain modules and did not continue at all after upgrading `sass-loader` from 6 to 7. Downgrading fixed the issue for us again.

(I'm so glad I stumbled over this and didnt' read it carefully enough to notice the very different version that this was about)

**Comment by jedwards1211** [comment]
@lenciel if you had scrolled up less than one page you would have seen how I figured it out (https://github.com/webpack/webpack/issues/1355#issuecomment-131237172):

> when I make it load sass files with url-loader instead, it finishes

**Comment by jedwards1211** [comment]
@leoselig Sass itself is ancient in JS-time, haven't you gotten on the CSS-in-JS bandwagon yet? :trollface:

**Comment by sumantka** [comment]
@jedwards1211 we're facing a similar issue but we're not even sure if this is the plugin that's causing it. I'm trying to understand what you meant by loading along with url-loader. Would you mind providing an example. That might help us. Thanks and apologize for bringind this up

**Comment by jedwards1211** [comment]
@sumantka I just needed to use *some* other loader to diagnose the problem, in this case I used `url-loader` but you could use `raw-loader` or anything else that wouldn't cause compile errors on sass files.  Since the build was hanging when I used `sass-loader` but not when I used `url-loader`, I concluded that `sass-loader` was hanging.

So try replacing your `sass-loader` rule(s) with the following and see if your build stops hanging.
```js
      {
        test: /\.s[ac]ss/,
        loader: 'url-loader',
      }, 
```

**Comment by sumantka** [comment]
Thanks @jedwards1211 appreciate it., although the options are slightly different though.
Here's my sass-loader config:
```
{
    loader: 'sass-loader',
    options: {
      data: '@import "theme.scss";',
      sourceMap: false,
      includePaths: [pathToGlobalStyles, pathToRisksenseStyles, pathToFonts],
    },
  },
```
Any ideas as to how to deal with this as url-loader 's doc doesn't seem to be supporting these params

**Comment by sumantka** [comment]
let me try replacing sass with url and see what happens. Thanks again

**Comment by jedwards1211** [comment]
@sumantka I'm only suggesting to use `url-loader` temporarily for diagnosing the problem -- it isn't a workaround, and wouldn't actually make your webapp show the correct CSS.  All this change does is help you determine if `sass-loader` is hanging the build.

**Comment by sumantka** [comment]
I gotcha

**Comment by sumantka** [comment]
yea that wasn't the issue. Issue still seems to be with TerserPlugin like so:
`92% chunk asset optimization TerserPlugin` should I file a bug report with terser. Thanks

**Comment by jedwards1211** [comment]
I see, hopefully it's not because the project is so large that minification takes a long long time

**Comment by sumantka** [comment]
shouldn't be, we are trying to upgrade to webpack v4 from v2 although in v4 if we don't specify any minifier it seems webpack 4 automatically adds terser and some other plugins so maybe issue is with one of these plugins. Also we currently have webpack 2 and the compilation is pretty fast even though we have lot of js.jsx files and the compilation with the newer config works locally too
