### ISSUE TITLE
Plugins can't provide custom WASM loading types

### ISSUE THREAD

**Issue by Jules-Bertholet** [webpack/webpack#13560]
# Bug report

**What is the current behavior?**
Running `EnableWasmLoadingPlugin.setEnabled(compiler, "custom-loading-type")` from an `afterEnvironment` hook fails to add a custom WASM loading type.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Create a new plugin with an `apply` method containing the following code:
```javascript
compiler.hooks.afterEnvironment.tap("PluginName", () => {
	EnableWasmLoadingPlugin.setEnabled(compiler, "custom-loading-type");
});
```
2. Add the plugin to your Webpack config
3. In `webpack.config.js`, set `output.wasmLoading` to `"custom-loading-type"`
4. Build your WASM-containing project with Webpack
5. You will get the following error:
```
Error: Unsupported wasm loading type custom-loading-type.
Plugins which provide custom wasm loading types must call EnableWasmLoadingPlugin.setEnabled(compiler, type) to disable this error.
```

**What is the expected behavior?**
Running `EnableWasmLoadingPlugin.setEnabled(compiler, "custom-loading-type")` from an `afterEnvironment` hook adds a custom WASM loading type so plugins can use their own WASM processing pipeline.

**Other relevant information:**
webpack version:  5.38.1
Node.js version: 14.7.0
Operating System: Fedora 34

**Comment by alexander-akait** [comment]
No problem:
```
 {
      apply(compiler) {
        compiler.hooks.afterEnvironment.tap("PluginName", () => {
          EnableWasmLoadingPlugin.setEnabled(compiler, "custom-loading-type");
        });
      }
    }
```

output:
```
webpack 5.38.1 compiled successfully in 1014 ms
```

**Comment by Jules-Bertholet** [comment]
Oops, forgot a step in the reproduction instructions, `output.wasmLoading` needs to be set also
