### ISSUE TITLE
require('path/' + moduleName) fails if module is in moduleName/index.js file

### ISSUE THREAD

**Issue by skyh** [webpack/webpack#1357]
Assume we have this folder structure
```
src
├── plugins
│   ├── Plugin1
│   │   └── index.js
│   └── Plugin2
│       └── index.js
└── entry.js
```

entry.js is webpack entry module with code like this

```js
module.exports = function askPlugin(pluginName, question) {
    var plugin = require('./plugins/' + pluginName)
    return plugin.respondTo(question)
}
```

when packing, webpack takes `plugins` directory and builds files map like this

```js
var map = {
    "./Plugin1/index": 4,
    "./Plugin1/index.js": 4,
    "./Plugin2/index": 5,
    "./Plugin2/index.js": 5
};
```

this map is incomplete, because there are missing folder modules `./Plugin1` and `./Plugin2` (in this example). So, correct map should be
```js
var map = {
    "./Plugin1": 4,
    "./Plugin1/index": 4,
    "./Plugin1/index.js": 4,
    "./Plugin2": 5,
    "./Plugin2/index": 5,
    "./Plugin2/index.js": 5
};
```

because we can call `require('./plugins/Plugin1')` and it is correct shorthand for `require('./plugins/Plugin1/index')`

**Comment by bebraw** [comment]
@skyh What's the status of this? Do you want to PR that change of yours?

**Comment by skyh** [comment]
I don't remember. Please, close this PR.
