### ISSUE TITLE
When the outputModule of the experiments is configured as true, the method of importing the module packaged by the dll plugin is undefined

### ISSUE THREAD

**Issue by duan602728596** [webpack/webpack#13578]
# Bug report

When webpack is configured

```javascript
{
  experiments: {
    outputModule: true
  }
}
```

Introducing the module packaged by webpack.DllPlugin, the method will be undefined.

**What is the current behavior?**

After a module is packaged by webpack.DllPlugin, the method of importing the module, the method is undefined, resulting in an error.

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/duan602728596/webpack-dll-bug

1. `npm install`
2. `npm run dll`
3. `npm run start`
4. Check index.html, the console will output the method

**What is the expected behavior?**

**Other relevant information:**
webpack version:  5.39.0
Node.js version: 16.3.0
Operating System: 
Additional tools:

**Comment by alexander-akait** [comment]
No problems, DLL by default create `commonjs` format (look at the `type` option), so you should use `default` export, you can use:
```js
import * as react from 'react';

const { createElement } = react;
```

but yes, it is not good. 

i.e. you need to set (unfortunately we cannot inherit `outputModule`, you need explicitly set `type`, same for `library.target`):
```
new webpack.DllPlugin({
  path: path.join(__dirname, 'dll/manifest.json'),
  name: '[name]_[hash:5]',
  type: 'module'
})
```

Unfortunately, external pure ECMA modules is not supported yet, close in favor https://github.com/webpack/webpack/issues/8895
