### ISSUE TITLE
Quadratic time and memory explosion for storing JSON module in filesystem cache

### ISSUE THREAD

**Issue by andersk** [webpack/webpack#13588]
# Bug report

**What is the current behavior?**

In a project with a JSON module containing a moderately sized object, using `cache.type = "filesystem"` causes webpack to take an enormous amount of time and memory. For example, with an object of 10000 keys, webpack takes 10 seconds and 2.5 GiB. When changing the size of the object, both time and memory appear to scale quadratically.

**If the current behavior is a bug, please provide the steps to reproduce.**

You can reproduce from [this Gist](https://gist.github.com/andersk/695d39eb544ea03481890a8bd5b209cf) with `npm run build`.

**`package.json`**

```json
{
  "dependencies": {
    "webpack": "^5.39.1",
    "webpack-cli": "^4.7.2"
  },
  "scripts": {
    "build": "npm i && node gen.js && \\time webpack"
  }
}
```

**`gen.js`**

```js
const fs = require("fs");
fs.writeFileSync("src.json", JSON.stringify({ ...[...Array(10000).keys()] }));
```

**`webpack.config.js`**

```js
module.exports = {
  mode: "development",
  cache: {
    type: "filesystem",
  }
};
```

```console
$ npm run build
[…]
asset main.js 137 KiB [emitted] (name: main)
./src.json 115 KiB [built] [code generated]
webpack 5.39.1 compiled successfully in 101 ms
10.86user 0.64system 0:10.66elapsed 107%CPU (0avgtext+0avgdata 2622824maxresident)k
0inputs+2896outputs (0major+652413minor)pagefaults 0swaps
```

**What is the expected behavior?**

webpack should take negligible time and memory on this project.

**Other relevant information:**
webpack version: 5.39.1
Node.js version: 14.17.0
Operating System: Linux

**Comment by sokra** [comment]
hmm yeah. I'll fix it...
