### ISSUE TITLE
Add readonly mode for filesystem cache

### ISSUE THREAD

**Issue by SkReD** [webpack/webpack#13581]
## Feature request

Add `readonly` mode for filesystem cache to outcome shared cache missing limitation

**What is the expected behavior?**

It should be possible to use already existing cache without tackling problems of concurrent write access, handling unused entries and managing uncontrolled grow of cache.

**What is motivation or use case for adding/changing the behavior?**

This will allow reuse at least common node_modules cached entries when running multiple compilations in parallel.

To clarify situation, where it's need:
1. Project is monorepo with several (or more) packages where every one of them is compiled to single js file. Packages are quite big (result file is about 1-2 Mb). node_modules are hoisted to root and can be effectivly cached between all packages.
2. Build is almost always production and not in watch mode.
3. We need to somehow reduce compilation time of all packages. Especially in CI.
4. Separate cache for every package is not efficient in terms of time: in CI it's not helping and memory: we have server and client builds and cache for them is about 100 Mb for one package
5. Multiple entries not share they memory cache (at least that what it's looks like when i try that) and even result to build hang.

So this solution looks pretty light and bring our build with webpack 5 to be at least not slower than with webpack 4, which, in turns, will allow us to move to webpack 5.

**How should this be implemented in your opinion?**

Flag `cache.readonly` in config, which is disable cache store in store method of `PackFileCacheStrategy`

**Are you willing to work on this yourself?**
yes

**Comment by alexander-akait** [comment]
You can implement this using custom plugin

**Comment by SkReD** [comment]
@alexander-akait could you point me where can i do that? Is it this place, where i should register my own plugin instead of bundled
https://github.com/webpack/webpack/blob/master/lib/WebpackOptionsApply.js#L560 and for that allow to pass custom plugin via `cache.store`?

**Comment by SkReD** [comment]
Do it that way
```
import webpack from "webpack";

const pluginName = 'ReadonlyCachePlugin';

class ReadonlyCachePlugin {
  apply(compiler: webpack.Compiler) {
    compiler.cache.hooks.store.intercept({
      register: (tapInfo) => {
        compiler.getInfrastructureLogger('webpack.cache.ReadonlyCachePlugin').info(`Cache is in readonly mode. Suppressing ${tapInfo.name} tap to hooks.store.`)
        return {
          name: pluginName,
          type: tapInfo.type,
          fn: function preventCacheStore() {}
        }
      }
    });
  }
}

export default ReadonlyCachePlugin;
```

**Comment by alexander-akait** [comment]
Yep, it is good solution, ideally we should fix and allow to use shared cache instead trying to do workarounds

**Comment by SkReD** [comment]
> Yep, it is good solution, ideally we should fix and allow to use shared cache instead trying to do workarounds

agreed, but shared caches are staying in review status for a long time already. And fixing it is beyond my capabilities for this moment.

**Comment by alexander-akait** [comment]
We have PR, but we need time to finish https://github.com/webpack/webpack/pull/10491

**Comment by Jack-Works** [comment]
I'd like to share our use case on this issue. We have a single application that builds multiple times with different flags. This is what I do: build the `base` version on its own (so it can write cache into the fs), then parallelly build the rest targets (they share the cache). The problem is those parallel builds will try to write the file system cache.

Happy to see this fixed, thanks!

**Comment by Jack-Works** [comment]
hmm sorry but I'm still waiting for this

**Comment by Jack-Works** [comment]
👀

**Comment by Jack-Works** [comment]
ping
