### ISSUE TITLE
5.40 breaks type of webpack-dev-server

### ISSUE THREAD

**Issue by otakustay** [webpack/webpack#13621]
# Bug report

**What is the current behavior?**

![image](https://user-images.githubusercontent.com/639549/123063007-9a331800-d43f-11eb-8c7f-07ef1ef79781.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

1. install `webpack` and `@types/webpack-dev-server`
2. create a variable of type `Configuration` from`webpack`
3. Try to access its `devServer` property

**What is the expected behavior?**

For webpack 3.38.1, this works

![image](https://user-images.githubusercontent.com/639549/123063187-c353a880-d43f-11eb-9a32-e5059537a9eb.png)

**Other relevant information:**
webpack version:  5.40.0
Node.js version: v16.3.0
Operating System: macOS 11.4
Additional tools: TypeScript 4.3.2 and `@types/webpack-dev-server@3.11.1`, `@types/webpack-dev-server@3.11.4` also reproduces this issue

**Comment by alexander-akait** [comment]
Feel free to send PR

**Comment by myNameIsDu** [comment]
> Feel free to send PR

:cold_sweat:I notice it doesn't seem to have a declaration file

**Comment by l-zoy** [comment]
@alexander-akait 
Hi, I tried to solve it, but found yarn run special-lint-fix
`
type IsAnyReplaceObeject<T> = true extends T & false
? {[Key: String]: Any}
: T;
type DevServer = IsAnyReplaceObeject<import(‘webpack-dev-server’).Configuration>
`
Finally, types.d.ts will become `DevServer: {[key: string]: any }`

Is there any way to skip compiling `import(‘webpack-dev-server’).Configuration` ?

The extension type in webpack-dev-server does not seem to be automatically recognized

**Comment by cspotcode** [comment]
We will need clarification on the appropriate fix for this bug.

This issue says that a PR is appropriate, but #13666 was closed.  webpack ships its own types which eliminates the need for @types/webpack.  Yet in #13666, it is claimed that the webpack-dev-server types *should remain* in DefinitelyTyped.  This seems contradictory and so is likely to confuse anyone attempting a fix for this issue.

**Comment by sokra** [comment]
`@types/webpack-dev-server` extends the webpack typings with the `devServer` property:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/415b6859c78cc7fe694fb12a10ea88f1fadfe958/types/webpack-dev-server/index.d.ts#L347-L355

For this to work `webpack` must not provide a `devServer` property in `Configuration`.

This seems fine and nothing has changed between these version.

* Make sure you don't have `@types/webpack` installed (`yarn why/npm ls @types/webpack`)
* Make sure you don't have `webpack` installed below `@types/webpack-dev-server` (`yarn why/npm ls webpack`)
* Make sure you don't have multiple versions of `webpack` or `@types/webpack-dev-server` installed

**Comment by cspotcode** [comment]
The confusion is as follows:

webpack 5 bundles types, eliminating the need for @types/webpack
Does webpack also want to bundle types with the dev server to eliminate the need for @types/webpack-dev-server?

Avoiding @types/webpack and yet requiring @types/webpack-dev-server is inconsistent.  If this is the intended approach, a documentation update can avoid the confusion.

Regardless of the answer, it may necessitate a documentation update: https://webpack.js.org/configuration/configuration-languages/

But I think the update will be different depending on the answer.

**Comment by alexander-akait** [comment]
We should add types to webpack-dev-server

**Comment by sokra** [comment]
> Does webpack also want to bundle types with the dev server to eliminate the need for @types/webpack-dev-server?

No webpack doesn't want to bundle dev server types. They are not part of webpack.

What you want is webpack-dev-server bundling it's own types.

> I think we will do it for 4.1

I think that's a breaking change so it should be a major release...

**Comment by cspotcode** [comment]
> What you want is webpack-dev-server bundling it's own types.

Yes, that is precisely what I was asking:  "Does the webpack team want to do that?"

**Comment by alexander-akait** [comment]
Yes, we want to add types for webpack-dev-server
