### ISSUE TITLE
Webpack ignores errors thrown in callback passed to `runAsChild()`

### ISSUE THREAD

**Issue by Mesoptier** [webpack/webpack#13624]
# Bug report

**What is the current behavior?**
If the callback passed to `runAsChild()` throws an error for whatever reason (e.g. https://github.com/webpack-contrib/mini-css-extract-plugin/pull/763), webpack will swallow/ignore the error and happily continue compiling. Eventually the process will finish "without errors" (i.e. error code `0`).

The only trace of anything actually having gone wrong is a `UnhandledPromiseRejectionWarning` warning in the console output and a completely broken build.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Take a webpack setup with any plugin that uses `runAsChild()` (in my case: mini-css-extract-plugin). 
2. Add `throw Error('test')` in the callback passed to `runAsChild`:
    ```
    childCompiler.runAsChild((error, entries, compilation) => {
        throw new Error('test');
        ...
    });
    ```
3. Run the build script
4. You will get a warning like this:
    ```
    UnhandledPromiseRejectionWarning: Error: test
        at /code/node_modules/mini-css-extract-plugin/dist/loader.js:290:11
        at /code/node_modules/webpack/lib/Compiler.js:538:11
        at /code/node_modules/webpack/lib/Compiler.js:1106:17
        at eval (eval at create (/code/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:11:1)
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
        at runNextTicks (internal/process/task_queues.js:66:3)
        at processImmediate (internal/timers.js:434:9)
    ```

**What is the expected behavior?**

Instead of logging a UnhandledPromiseRejectionWarning (the default behaviour of Node, for now), weback should `catch` the synchronously thrown error and handle it with webpack's regular error handling such as logging it and terminating the build.

My workaround for now is to add the `--unhandled-rejections=strict` option to my `node` process:
```
node --unhandled-rejections=strict ./node_modules/.bin/webpack ...
```
This way at least the build will fail when a plugin contains an error for some reason.

All in all, I would expect a webpack build to fail when a plugin throws an error, just like it would when you would call `callback(err)`.

**Other relevant information:**
webpack version: 5.39.0 and 5.40.0
Node.js version: v12.20.1
Operating System: Ubuntu 20.02
Additional tools:

**Comment by alexander-akait** [comment]
bump

**Comment by vankop** [comment]
not sure what webpack should do here? @alexander-akait 

in code
```js
compiler = compiler.createChildCompiler(...);
compiler.runAsChild(() => {
  throw new Error(); // <- this is async code
});
```
so webpack only can add error to parent compilation only..

**Comment by alexander-akait** [comment]
@vankop hm, I think failed child compilation should fail parent too, I think we have this behavior
