### ISSUE TITLE
Higher stable memory usage in Webpack 5 on cold start

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [webpack/webpack#13626]
# Bug report

**What is the current behavior?**

https://github.com/JoshuaKGoldberg/webpack-5-memory-repro

I set up ☝️  reproduction repository to show a surprising behavior with Webpack 5 compared to Webpack 4: although the _peak_ memory usage is improved on cold start, the _stable_ amount is an extra 50%+ higher.

Webpack 4 memory usage grows towards a peak, then down to a stable amount:

| Run | Stable  | Peak    |
| --- | ------- | ------- |
| 1   | 1.04 GB | 2.49 GB |
| 2   | 1.08 GB | 2.29 GB |
| 3   | 1.07 GB | 2.37 GB |

Webpack 5 memory usage remains stable at roughly its peak:

| Run | Stable  |
| --- | ------- |
| 1   | 1.65 GB |
| 2   | 471 MB  |
| 3   | 471 MB  |

Is there a memory leak on cold start?

**If the current behavior is a bug, please provide the steps to reproduce.**

See README.md steps in that repo.

**What is the expected behavior?**

After whatever cold start logic runs, it should go down to 471 MB.

Sorry if this isn't the right repository to post this issue; I wasn't sure given the tool dependencies...

**Other relevant information:**
webpack version: 5.23.0, comparing to 4.44.1
Node.js version: 12.16.0
Operating System: macOS
Additional tools: `webpack-dev-server`: 3.11.2, comparing to 3.9.0

**Comment by alexander-akait** [comment]
Problem in non official plugins

**Comment by alexander-akait** [comment]
You can look at memory usage here https://webpack.github.io/benchmark/

**Comment by alexander-akait** [comment]
Also please note using https://github.com/JoshuaKGoldberg/webpack-5-memory-repro/blob/main/script5/webpack/app.config.js#L62 increase memory because we need collect buffers and save them

**Comment by JoshuaKGoldberg** [comment]
> Also please note using https://github.com/JoshuaKGoldberg/webpack-5-memory-repro/blob/main/script5/webpack/app.config.js#L62 increase memory because we need collect buffers and save them

Fascinating: trying out memory or no cache made it more deterministic _(makes sense)_ but also a bit worse for peak memory usage. I updated the README.md.

**cache: true ('memory')**

| Run | Stable  | Peak    |
| --- | ------- | ------- |
| 1   | 1.18 GB | 1.84 GB |
| 2   | 1.27 GB | 1.84 GB |
| 3   | 1.25 GB | 1.84 GB |

**cache: false**

| Run | Stable  | Peak    |
| --- | ------- | ------- |
| 1   | 1.38 GB | 1.84 GB |
| 2   | 1.39 GB | 1.88 GB |
| 3   | 1.26 GB | 1.84 GB |

**Comment by alexander-akait** [comment]
@JoshuaKGoldberg due problems in non official plugins as I described above

**Comment by JoshuaKGoldberg** [comment]
Sorry, I'm a little unclear on what your intent with that is: are you saying I should re-post this issue in `webpack-dev-server`?

**Comment by alexander-akait** [comment]
@JoshuaKGoldberg Can you measure memory with/without dev server, also I found https://github.com/JoshuaKGoldberg/webpack-5-memory-repro/blob/main/script5/webpack/app.config.js#L2/https://github.com/JoshuaKGoldberg/webpack-5-memory-repro/blob/main/script5/webpack/app.config.js#L3/https://github.com/JoshuaKGoldberg/webpack-5-memory-repro/blob/main/script5/webpack/app.config.js#L7/etc non official plugins, so will be great to measure memory without them (only for testing purposes)

**Comment by alexander-akait** [comment]
In prod or development? How many modules? Do you have source maps? We need more information to help you

**Comment by evenstensberg** [comment]
They have 5 entry points in a very large app. I don'tk now number of modules. The application follows best practises and everything is done correctly. For instance, `[chunkhash:8]` is done, and disabling cache on prod is also done. It is using babel, but the bottleneck here is that webpack consumes too much memory. Anything more you need access to @alexander-akait ? I've monitored/researched the application and found no improvement points, except from minification with esbuild, that could trim some time.

**Comment by JoshuaKGoldberg** [comment]
Ah, yeah, I'd hoped to send details privately but it's looking like this isn't something we have time to make progress on. Internally we're moving to Next.js microfrontends instead, each of which have Webpack 5 running quite nicely.

Cheers!
