### ISSUE TITLE
TypeError: SyncHook is not a constructor on Webpack 5.40.0

### ISSUE THREAD

**Issue by brendonco** [webpack/webpack#13620]
Upgrading to 5.40 got:

 npx webpack serve

[webpack-cli] TypeError: SyncHook is not a constructor

```
Package              Current  Wanted  Latest
webpack               5.39.0   5.40.0      5.40.0
```

node v12.16.0

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
