### ISSUE TITLE
loading non-required files

### ISSUE THREAD

**Issue by duivvv** [webpack/webpack#1362]
is it possible to use a loader on files that you don't require anywhere?

for example:
I'm building my front-end code with Webpack but I also want to lint all *.js files in a server specific folder.

thanks in advance.
Geoffrey

**Comment by IngwiePhoenix** [comment]
Separate entrypoint. You dont have to use it’s output, but that way you can lint the server code.

**Comment by duivvv** [comment]
@IngwiePhoenix but there will always be an output?

**Comment by duivvv** [comment]
is there a plugin or way to ignore a file for output?, I only need to lint it

**Comment by bebraw** [comment]
@duivvv Maybe it's better to deal with linting your backend code outside of Webpack? When do you want to trigger the process?

**Comment by duivvv** [comment]
I'm linting on nodemon restart now, works perfect
