### ISSUE TITLE
Persistent caching return stale results when updating resolve.alias

### ISSUE THREAD

**Issue by slorber** [webpack/webpack#13627]
# Bug report

**What is the current behavior?**

When changing `resolve.alias`, affected persistent cache entries are still used instead of being evited.

**If the current behavior is a bug, please provide the steps to reproduce.**

I'm using the filesystem cache with resolve aliases:

```js
const myAliases = {
 "@theme/MyComponent": "/dirname/OLD_COMPONENT.js",
};

module.exports = {
  cache: {
    type: "filesystem",
  },
  resolve: { alias: myAliases }
}
```

Now, let's change the aliases:

```js
const myAliases = {
 "@theme/MyComponent": "/dirname/NEW_COMPONENT.js",
};

module.exports = {
  cache: {
    type: "filesystem",
  },
  resolve: { alias: myAliases }
}
```

When building/running again (dev server or prod), Webpack will keep using the code from `OLD_COMPONENT.js`, while it should rather use `NEW_COMPONENT.js`

When cleaning `node_modules/.cache/webpack`, the next build will use `NEW_COMPONENT.js` successfully.

**What is the expected behavior?**

I would expect Webpack to be able to discard cache entries that are affected by the alias changes.

A workaround is to use `cache.version` to discard the whole cache when aliases are updated, but this is a bit too aggressive to clean the whole cache for a single alias change.

```js
const myAliases = {
 "@theme/MyComponent": "/dirname/NEW_COMPONENT.js",
};

module.exports = {
  cache: {
    type: "filesystem",
    version: md5HashString(myAliases),
  },
  resolve: { alias: myAliases }
}
```

Doc says: 

> Update the version when configuration changed in a way which doesn't allow to reuse cache.

It is not totally clear to me what configuration changes are handled by webpack, and what configuration changes should we handle in userland. I think it would be nice to have this supported in webpack core as it's hard to implement in an efficient way in userland.

**Other relevant information:**
webpack version:  5.40
Node.js version: 14.x
Operating System: macos sierra
Additional tools:

**Comment by alexander-akait** [comment]
No problems here... How you run webpack? If you use webpack-cli we automatically added your configuration as `buildDependencies` https://github.com/webpack/webpack-cli/blob/master/packages/webpack-cli/lib/webpack-cli.js#L1855, so any changes in file will invalidate cache, but if you use external file you need do it manually, also we have https://webpack.js.org/configuration/other-options/#cacheversion for this purpose

**Comment by alexander-akait** [comment]
> I think it would be nice to have this supported in webpack core as it's hard to implement in an efficient way in userland.

It is impossible, webpack can't know about your external variables/envs/files/etc

**Comment by alexander-akait** [comment]
In theory we can keep resolved aliases from `resolve.alias` for each module and invalidate module only when something in `resolve.alias` was changed, but `version` does not let us know which of these variables is used as `alias`. Also, this can be said about many options from configuration, it is really complex and kill cache performance

**Comment by slorber** [comment]
Sorry, my example was a bit wrong:  I'm reading aliases from the filesystem structure, and they are not static in the webpack config file (so I guess `buildDependencies: {config: [__filename]}` can't kick in):

```js
const myAliases =  getAliases("/dirname/theme")

module.exports = {
  cache: {
    type: "filesystem",
  },
  resolve: { alias: myAliases }
}
```

I could maybe add `/dirname/theme/**` to buildDependencies as well, but it is also quite aggressive to evict the cache if any of the files are updated.

--- 

> It is impossible, webpack can't know about your external variables/envs/files/etc

Actually, I don't ask webpack to know about external things, but only aliases that I explicitly provide as webpack config.

> In theory we can keep resolved aliases from resolve.alias for each module and invalidate modules only when something in resolve.alias was changed, but version does not let us know which of these variables is used as alias. Also, this can be said about many options from configuration, it is really complex and kill cache performance

I totally understand it is a complex problem to solve. I don't really expect it to be solved in the near future and my workaround will be fine. Wanted to document this issue a bit as others might encounter it. I also think the doc could explain better which config changes are supported by webpack caching and which the user should take care of.

**Comment by alexander-akait** [comment]
Yep, feel free to send an improvement to docs

> I could maybe add /dirname/theme/** to buildDependencies as well, but it is also quite aggressive to evict the cache if any of the files are updated.

You can create more smart function to collect only necessary cache dependencies.

> Actually, I don't ask webpack to know about external things, but only aliases that I explicitly provide as webpack config.

We already have doing it, the main problem here, they are in external files, if you will use `require`/`import` webpack config, webpack invalidate cache, when something was changed in required/imported files, but I think you are using `glob` here. Also even we will store aliases for modules, it will create a lot of checks, which can actually kill the whole point of the cache

To be honest, I don't think this will ever be resolved at all.

**Comment by slorber** [comment]
> You can create more smart function to collect only necessary cache dependencies.

Not sure it solves the problem. Even if I filter the buildDependencies, any change will evict the whole cache.

>  I think you are using glob here

Yes

> To be honest, I don't think this will ever be resolved at all.

I understand

---

Was wondering if Webpack offers any API for imperatively invalidate/manipulate some cache entries. 
Current options (buildDependencies/version) seem to evict all entries at once.

**Comment by alexander-akait** [comment]
> Was wondering if Webpack offers any API for imperatively invalidate/manipulate some cache entries.

in theory it is possible, here we implement logic for resolving https://github.com/webpack/webpack/blob/master/lib/cache/ResolverCachePlugin.js, also we have hooks for get/store cache
