### ISSUE TITLE
splitChunks: new `issuer` option for `cacheGroups`

### ISSUE THREAD

**Issue by dkrnl** [webpack/webpack#13623]
I need separate some polyfills and vendor chunk by new option -- `splitChunks.cacheGroups.{cacheGroup}.issuer`.

## Feature request

And i try write code, using undocumented field `module.resourceResolveData`. This work well only first build. 
But second build (with cache enabled) `module.resourceResolveData` already empty.

This code is not a bug report, but just an example:
```js

const corejsDir = path.dirname(require.resolve('core-js'));
const polyfillsDir = path.join(__dirname, 'source/js/polyfills/');
const polyfillsEntry = path.join(__dirname, 'source/js/polyfills.js');

...
splitChunks: {
    cacheGroups: {
        polyfills: {
            chunks: 'initial',
            enforce: true,
            test: ({ resource, resourceResolveData }) => {
                if ((
                    resourceResolveData
                    && resourceResolveData.context
                    && resourceResolveData.context.issuer
                    && resourceResolveData.context.issuer.indexOf(polyfillsDir) === 0
                ) || (
                    resource
                    && (
                        resource.indexOf(corejsDir) === 0
                        || resource.indexOf(polyfillsEntry) === 0
                        || resource.indexOf(polyfillsDir) === 0
                    )
                )) {
                    return true;
                }
                return false;
            },
            name: 'vendor.polyfills',
            priority: 10,
        },
    },
},
...
```
**What is the expected behavior?**
...

**What is motivation or use case for adding/changing the behavior?**

I need separate some polyfills and vendor chunk for modern browser build

**How should this be implemented in your opinion?**

```js
...
splitChunks: {
    cacheGroups: {
        polyfills: {
            chunks: 'initial',
            enforce: true,
            issuer: /[\\/]source[\\/]js[\\/]polyfills/, // <-- here
            test: /[\\/]node_modules[\\/]/, 
            name: 'vendor.polyfills',
            priority: 10,
        },
    },
},
...
```

**Are you willing to work on this yourself?**
no

**Comment by alexander-akait** [comment]
You can have multiple `issuers`, also some modules just don't have issuers, relying only on it is not always a good idea

**Comment by dkrnl** [comment]
Ok, thank you!

Can i write bug-report for empty `module.resourceResolveData` (undocumented field) in cached build?

**Comment by alexander-akait** [comment]
`resourceResolveData` can be empty too, it is expected
