### ISSUE TITLE
module: true does not provide all exports

### ISSUE THREAD

**Issue by guybedford** [webpack/webpack#13639]
# Bug report

**What is the current behavior?**

A module like:

```js
module.exports = 'test';
```

when running under the `module: true` mode will not export anything. Ideally `module.exports` should be treated as the `default` export surely.

In addition, a module like:

```js
exports.valid = true;
exports['in valid'] = false;
```

would be expected to at least export `export const valid = true` but this does not seem to be the case.

**If the current behavior is a bug, please provide the steps to reproduce.**

A comprehensive replication can be provided if needed.

**What is the expected behavior?**

Ideally, a best effort can be made to export named exports as appropriate based on user intent.

**Other relevant information:**
webpack version:  5.36.2

**Comment by sokra** [comment]
What do you mean with `module: true`?

**Comment by guybedford** [comment]
I mean the output option https://webpack.js.org/configuration/output/#outputmodule when used alongside `libraryTarget: 'module"`.

**Comment by sokra** [comment]
Hmm yes that not implemented yet. That's also why it's flagged as experimental.

You can try https://github.com/webpack/webpack/pull/13622 which implements basic support for that.

**Comment by alexander-akait** [comment]
I think we can close, fixed https://github.com/webpack/webpack/pull/13622
