### ISSUE TITLE
filename=[chunkhash] illegal only with HMR

### ISSUE THREAD

**Issue by syranide** [webpack/webpack#1363]
I use `output.filename = '[chunkhash:12].js'` which works just fine (can't use plain `[hash]` because of multiple entries), but when I try to run the same config with hot/HMR enabled I get the following error:

```
Cannot use [chunkhash] for chunk in '[chunkhash].js' (use [hash] instead)
```

It's not really a problem, but it seems peculiar to me that it only applies to HMR.

**Comment by Sinewyk** [comment]
Shouldn't it actually be the opposite ? Apparently you should use `[hash]` if multiple entries, and chunkhash if you are effectively using async loading/require.ensure (which create chunks). Multiple entries !== chunks.

Source : https://github.com/webpack/webpack/blob/master/test/Errors.test.js#L132

**Comment by syranide** [comment]
>  Apparently you should use [hash] if multiple entries

That doesn't make any sense to me, [hash] is the hash of the entire compilation so using it with multiple entries without anything else to differentiate means all entries will have the same filename.

> Multiple entries !== chunks.

Sure, but I don't really care about semantics here, call it [filehash] or w/e, I'm interested in it for long-term caching (which means I'm currently fine because [chunkhash] works for non-hot right now)... but it would be nice to use the same method for my hot dev builds too.

**Comment by sokra** [comment]
You can use `[hash]-[id].js` for multiple entry points.

With HMR the entry chunk depends on the hash of the compilation and because of this `[chunkhash]` is not possible. (The filename must change with every recompilation not only when a module in the entry chunk changes)

**Comment by syranide** [comment]
@sokra Yep, that's what I'm using right now, I'll just keep using that then :)

**Comment by superddr** [comment]
This is really a problem. I used CommonsChunkPlugin, I hope it to keep not touched when I change any of my entries. Now I have two problems: 1 is for the CommonsChunkPlugin will always change the file(even if i restrict it to use some specific modules; 2 is that the HMR dont allow the CommonsChunkPlugin to use chunkhash...
