### ISSUE TITLE
Source Map Shows Generated Code File

### ISSUE THREAD

**Issue by gita-codaio** [webpack/webpack#13633]
# Bug report

**What is the current behavior?**
For any of the devtool modes or using the configured SourceMapDevToolPlugin the generated code file for the source maps also shows up. 
There are two files for each file -- the generated code and the original code. 
For example the generated code file shows up as `webpack-internal:///./modules/browser/react-components/icon.ts` and the original file source map shows up as `webpack-internal:///modules/browser/react-components/modules/browser/react-components/icon.ts`.

 In webpack 4 I recall just the original code file to show up.

**If the current behavior is a bug, please provide the steps to reproduce.**
I can come up with a small repro if needed.

**What is the expected behavior?**
For just the original code to show up for source maps.

**Other relevant information:**
webpack version:  5.40.0
Node.js version: 14.17.1
Operating System: Mac OS 10.15.6
Additional tools: Chrome Version 91.0.4472.114 (Official Build) (x86_64)

**Comment by alexander-akait** [comment]
It means you have two plugins for source map generation, please use https://github.com/webpack/webpack/discussions if you can't create reproducible test repo

**Comment by gita-codaio** [comment]
I only have one plugin defined using devtools -- if I remove that then there is no source map. I will try and create repro.

**Comment by sokra** [comment]
That's expected when using the eval-source-map devtool. It's a workaround needed for chrome to handle breakpoints in source-maps correctly.

**Comment by alexander-akait** [comment]
Answered, feel free to feedback
