### ISSUE TITLE
webpack-cli can only be found as a sibling package

### ISSUE THREAD

**Issue by agurney** [webpack/webpack#13632]
# Bug report

**What is the current behavior?**

When running webpack, it will check to see if webpack-cli is installed. If not, it will issue an interactive prompt. Whereas this check previously used `require.resolve`, it's now a plain search for `node_modules` directories in the current hierarchy. That means that it can no longer find webpack-cli if that's installed globally but webpack is installed locally (or the reverse).

Because of the interactive prompt, this caused an issue for an unattended process where it would hang indefinitely. (In a setup where we happened to have installed the two modules in different ways, due to a quirk of the build process.)

The new behavior is from https://github.com/webpack/webpack/pull/13529.

**If the current behavior is a bug, please provide the steps to reproduce.**

In a fresh project,
```
$ yarn add webpack
$ yarn global add webpack-cli
$ node ./node_modules/webpack/bin/webpack.js
```
will result in webpack complaining that it can't find webpack-cli.

```
CLI for webpack must be installed.
  webpack-cli (https://github.com/webpack/webpack-cli)

We will use "yarn" to install the CLI via "yarn add -D webpack-cli".
Do you want to install 'webpack-cli' (yes/no): %
```

(Similarly with npm rather than yarn - the point is that webpack-cli is installed elsewhere.)

**What is the expected behavior?**

Although not everybody thinks that globally-installed stuff is a good idea, that's still part of the way Node works. Webpack should try harder to find webpack-cli, in particular by looking in whatever the global module path happens to be. This is what the original code was doing, by following the same logic as node itself.

**Other relevant information:**
webpack version: 5.39.0 and later
Node.js version: (any)
Operating System: (any)
Additional tools: yarn

**Comment by alexander-akait** [comment]
Here two limitations:
- `require.resolve` never resolve global packages and it will not work before (try it) (here package for it https://github.com/sindresorhus/resolve-global, but please read below)
- `require.resolve` caches requests and we can't use it for interactive installation

I want to say it is limitation, if you want to use `webpack-cli` globally you need to install `webpack` globally too, if you want to use `webpack-cli` locally you need to install `webpack` locally, even more it is not safe, in the next version of `webpack-cli` we will drop webpack v4, but locally you can have `webpack` v4 (and versa vice) and it will not work.
