### ISSUE TITLE
Webpack output differs between operating systems (works on OSX, breaks on CentOS)

### ISSUE THREAD

**Issue by csvan** [webpack/webpack#13638]
# Bug report

**What is the current behavior?**
The same dependency gets different ids when building on different OS - one of those IDs is invalid, and leads to crashing during runtime.

**If the current behavior is a bug, please provide the steps to reproduce.**
Unfortunately I don't have a repro for this, since it involves building a proprietary system on different operating systems. I will do my best to break down what is happening instead, and hopefully someone with more insight can point out what might be going wrong.

Basically, the following happens:
1. I have a Webpack 5 project, all dependencies are locked via `yarn .lock` and hence always the same.
2. I build the app on OSX Catalina. One of the following chunks has the dependency 57966 loaded:

![Screenshot 2021-06-25 at 23 22 28](https://user-images.githubusercontent.com/1127729/123486393-3742ac00-d60c-11eb-84e6-a9396604b905.png)

This works fine when running in the browser, however

3. I then build then app on CentOS 8, running in a docker image. However, inspecting the output from the build, I now see that the same chunk has (I assume) the same dependency with a completely different ID (62001), the other deps are the same:

![Screenshot 2021-06-25 at 23 26 00](https://user-images.githubusercontent.com/1127729/123486640-b7691180-d60c-11eb-9972-e6974f0af24e.png)

When running in the browser, the app crashes because dependency 62001 does not exist (`Cannot read property 'call' of undefined`).

Inspecting the OSX build, the dependency 62001 does not exist anywhere in the output. It is only generated when building on CentOS.

**What is the expected behavior?**

Given the same dependencies, webpack projects should generate consistent output.

**Other relevant information:**
webpack version:  5.40.0
Node.js version: 16 on Catalina, 14 on CentOS
Operating System: OSX Catalina, CentOS 8.
Additional tools:

**Comment by alexander-akait** [comment]
I think you have problem with case insensitivity, on mac os you can have `import foo from './Module.js'`,  but in file system `Module.js` and `module.js`, so it will work on macos but broken on case sensitivity os

> When running in the browser, the app crashes because dependency 62001 does not exist (Cannot read property 'call' of undefined).

I think you load this module using dynamic `import()`

**Comment by alexander-akait** [comment]
You can use `named` and debug the problem https://webpack.js.org/configuration/optimization/#optimizationmoduleids

**Comment by csvan** [comment]
Closing this since I am pretty sure it has nothing to do with Webpack per se, but rather how we use it. This happened when two particular builds (out of dozens) happened to run in parallel, so I am guessing something weird was going on.

@alexander-akait probably has the right idea, but everything started working as soon as these two builds were run separately. Webpack is working as intended.
