### ISSUE TITLE
"export * from" breaks tree shaking

### ISSUE THREAD

**Issue by csvan** [webpack/webpack#13641]
# Bug report

**What is the current behavior?**
One of our dependencies re-exports the index.js file of https://www.npmjs.com/package/@material-ui/core like so:

```
export * from '@material-ui/core';
```

We would expect Webpack 5 to tree shake this as per https://webpack.js.org/blog/2020-10-10-webpack-5-release/#nested-tree-shaking, however, inspecting the build shows that the ENTIRE `@material-ui/core` is included in the bundle - even if no modules from this package are used.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Set up basic webpack project
2. In a dependency in node_modules, re-export `@material-ui/core` as per the above
3. Create production build
4. Inspect generated chunks

**What is the expected behavior?**

Webpack should deep-shake the re-exported package.

**Other relevant information:**
webpack version:  5.40.0
Node.js version: 14
Operating System: OSX Catalina
Additional tools:

**Comment by csvan** [comment]
Hm, looking into it, it seems like this is non-standard syntax (still a proposal - https://github.com/tc39/proposal-export-default-from), I suppose that is the reason it does not work?

**Comment by Slapbox** [comment]
That would explain a lot about how little good tree-shaking does on our project.

**Comment by csvan** [comment]
Would be helpful to know which non-standard constructs currently work with tree shaking. For example, I noticed Material UI and several others use the export-default-as format:

```
export { default as Icon } from './components/Icon';
```

Does this for example work with TS?

**Comment by sokra** [comment]
`export *` is not related to the export-default-from proposal.
Nonetheless all of these constructs are supported for tree shaking.

Could you please provide a complete reproduction for the problem?

**Comment by csvan** [comment]
@sokra thanks for clarifying, will see what I can do
