### ISSUE TITLE
Truncated codes when Function exported as federated module

### ISSUE THREAD

**Issue by brendonco** [webpack/webpack#13665]
# Bug report

**What is the current behavior?**
Currently have 42 line of codes in a utils.js file which will be used in another Module Federation.

**Federate Module 1**

delta.js // with 22 line of codes
```
export const SAMPLE = 'SAMPLE';
```

utils.js // with 42 line of codes. All are exported functions
```
import { getUserProfile }  from './config';
import * as delta from './delta'; 

export const thisMethodIsTruncated = () => {
const { user } = getUserProfile();
....
}

export const method2 = () => { ... }

export const method3 = () => { ... }

.... //upto line 42 or more
```

webpack.config.js
```
new ModuleFederationPlugin({
  name: 'module1',
  exposes: {
    './utils': './src/common/utils.js',
  },
  ...
})
```

**Federated Module 2**

module2.js

```
useEffect(() => {
  import('module1/utils').then((util) => {
    const { thisMethodIsTruncated  } = util;
    thisMethodIsTruncated() // thisMethodIsTruncated  is not a function
  })
}, [])
```

webpack.config.js //module 2

```
new ModuleFederationPlugin({
  name: 'module2',
  remotes: {
    module1: 'module1',
  }
...
});
```

**Solution Weird**
Create a new file and move this method thisMethodIsTruncated

**If the current behavior is a bug, please provide the steps to reproduce.**
steps provided above

**What is the expected behavior?**
should be able to import federated module 1 in federated module 2.

**Other relevant information:**
webpack version:  5.41.0
Node.js version: 12.16.0
Operating System: windows 10
Additional tools: na

**Comment by alexander-akait** [comment]
Duplicate https://github.com/webpack/webpack/issues/13457
