### ISSUE TITLE
5.41.0 regression: Cannot use keyword 'await' outside an async function

### ISSUE THREAD

**Issue by glen-84** [webpack/webpack#13664]
# Bug report

**What is the current behavior?**

I'm using `experiments.topLevelAwait`, and after upgrading to 5.41.0, I'm seeing:

> Module parse failed: Cannot use keyword 'await' outside an async function (11:0)

**If the current behavior is a bug, please provide the steps to reproduce.**

Create a webpack config with `experiments.topLevelAwait` set to `true`, and use top-level await.

I can create a repro if it helps.

**What is the expected behavior?**

No error, as this worked perfectly fine in previous versions.

**Other relevant information:**
webpack version: 5.41.0
Node.js version: 14.17.1
Operating System: Windows 10
Additional tools: n/a

**Comment by sokra** [comment]
as workaround update the acorn version. We need to force push the version in the package.json. If you want to you can set a PR.
