### ISSUE TITLE
Consistent capitalization between the watcher and running webpack

### ISSUE THREAD

**Issue by jeaxelrod** [webpack/webpack#1366]
Hi,

I had an import statement `import Component from 'path/to/file';` where the 'path/to/file' was incorrectly capitalize like 'Path/to/file'. I was still able to correctly run webpack, however my watcher stopped working. I feel like the behavior for both should be consistent.

**Comment by shama** [comment]
Could you provide an example that reproduces this issue? Thanks!

**Comment by bebraw** [comment]
If still relevant, please re-open at https://github.com/webpack/watchpack/issues .
