### ISSUE TITLE
File path info in chunkFilename function when optimization.chunkIds is deterministic

### ISSUE THREAD

**Issue by gpoitch** [webpack/webpack#13671]
## Feature request

**What is the expected behavior?**
I am using the `output.chunkFilename` function to generate friendly readable chunk filenames based on their source path.  This works well if `optimization.chunkIds` is set to `named`.  However, this leaves big long ids in the source code references (e.g. "src_web_app_components_home_index_js").  Ideally, I'd like to leave `optimization.chunkIds` set to `deterministic` (the default in a production build), so the chunk ids are small numbers. The issue is that the chunk info provided to the `chunkFilename` function no longer has any identifiable information about the file paths to generate the filenames anymore.

**What is motivation or use case for adding/changing the behavior?**
Automatic readable filenames with smaller code.

**How should this be implemented in your opinion?**
Include more information to the chunkFilename regardless of the optimization.chunkIds setting.

**Are you willing to work on this yourself?**
yes

**Comment by alexander-akait** [comment]
You can use `/* webpackChunkName: "my-chunk-name" */`

**Comment by alexander-akait** [comment]
Also you can implement own plugin for naming, example https://github.com/webpack/webpack/blob/main/lib/ids/DeterministicChunkIdsPlugin.js

**Comment by gpoitch** [comment]
I want the file naming to be automatic based on the source path without having to add webpackChunkName comments everywhere. I also just want the default DeterministicChunkIdsPlugin id generation.

I guess i'm looking for where `output.chunkFilename` gets called in the source code.  All of the name & files info gets excluded from the `chunk` in deterministic mode.

**Comment by alexander-akait** [comment]
> I guess i'm looking for where output.chunkFilename gets called in the source code. All of the name & files info gets excluded from the chunk in deterministic mode.

it is not easy and not possible in some cases

**Comment by gpoitch** [comment]
I'm having some success simply applying both plugins. Not sure of any unintended side-effects yet:

```js
const { DeterministicChunkIdsPlugin, NamedChunkIdsPlugin } = require('webpack').ids

class NamedDeterministicChunkIdsPlugin {
  apply(compiler) {
    // Apply named chunks plugin (assigns name to chunk.id)
    new NamedChunkIdsPlugin().apply(compiler)

    compiler.hooks.compilation.tap('NamedDeterministicChunkIdsPlugin', (compilation) => {
      compilation.hooks.chunkIds.tap('NamedDeterministicChunkIdsPlugin', (chunks) => {
        chunks.forEach((chunk) => {
          chunk.name = chunk.id // Store the name on another field
          chunk.id = null // null out id so the next plugin will reassign it
        })
      })
    })

    // Apply deterministic chunks plugin (reassigns chunk.id to a short numeric id)
    new DeterministicChunkIdsPlugin().apply(compiler)
  }
}
```

**Comment by alexander-akait** [comment]
Interesting solutions :smile:  but should work without problems :smile:

**Comment by gpoitch** [comment]
The example I posted breaks in watch mode.  Ended up just making a simpler plugin to assign a `chunk.name` based on the root module file path.  Ideally webpack could leave all the chunk info in deterministic mode.

**Comment by jamesarosen** [comment]
> Ended up just making a simpler plugin to assign a chunk.name based on the root module file path.

Would you mind posting that or the most salient pieces? I'm currently struggling because `/* webpackChunkName "[request]" */` is resulting in conflicts when I have, e.g. `import('path/one/to/bar.js')` and `import('path/two/to/bar.js')`.

**Comment by gpoitch** [comment]
@jamesarosen  This was my final solution. As-is, it would give you `bar.js` for both, but you should have all the pieces there to adjust it.
```js
class AutoChunkNamePlugin {
  apply(compiler) {
    compiler.hooks.compilation.tap('AutoChunkNamePlugin', (compilation) => {
      compilation.hooks.chunkIds.tap('AutoChunkNamePlugin', (chunks) => {
        chunks.forEach((chunk) => {
          if (!chunk.name) {
            const chunkModule = compilation.chunkGraph.getChunkRootModules(chunk)[0]
            const rootModule = (chunkModule && chunkModule.rootModule) || chunkModule
            const rootPath = rootModule && rootModule.userRequest
            const name = rootPath && rootPath.split(path.sep).slice(-2)[0]
            if (name) chunk.name = name
          }
        })
      })
    })
  }
}
```
