### ISSUE TITLE
Minimize optimization changes program logic with certain Nullish Coalescing usages

### ISSUE THREAD

**Issue by oxygene** [webpack/webpack#13679]
# Bug report
I'd like to raise awareness that program logic can be broken when using the nullish coalescing operator and minimize optimization using webpack 5.

**What is the current behavior?**
A special use case of the nullish coalescing operator breaks when minimize optimization is turned on using terser.

**If the current behavior is a bug, please provide the steps to reproduce.**
See bug report in terser repo:

https://github.com/terser/terser/issues/1003

There, an example is given.

**What is the expected behavior?**
Obviously, don't silently break the program logic.

**Other relevant information:**
webpack version:  5.40
Node.js version: 6.14.5
Operating System: Ubuntu Linux
Additional tools:

**Comment by alexander-akait** [comment]
Close in favor https://github.com/terser/terser/issues/1003, sorry we can't solve it here, please wait the fix in terser
