### ISSUE TITLE
 error  in ./node_modules/@vue/reactivity/dist/reactivity.esm-bundler.js

### ISSUE THREAD

**Issue by hy739455177** [webpack/webpack#13688]
Could you tell me how to solve this problem???When I create a new Vue  project,then yarn serve

environment  "@vue/cli-service": "~4.5.0",

Module parse failed: Unexpected token (763:13)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| }
| class RefImpl {
>     _rawValue;
|     _shallow;
|     _value;

 @ ./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js 1:0-233 2:0-216 2:0-216 2:0-216 2:0-216 2:0-216 2:0-216 2:0-216 2:0-216 2:0-216 2:0-216 2:0-216 2:0-216 2:0-216 2:0-216 2:0-216 2:0-216 2:0-216 2:0-216 2:0-216 16:4-17 40:4-17 107:13-18 108:32-37 115:16-21 1958:8-13 1962:13-23 1968:35-45 1970:16-21 1973:21-31 2071:19-25 2094:8-12 2135:8-13 2210:29-34 2557:27-30 2558:26-29 2559:28-31 2905:16-29 2912:16-29 3043:28-36 3362:41-56 3378:28-33 3463:8-15 3500:32-37 3647:27-32 3823:29-34 3951:12-25 3958:12-25 4568:17-22 4592:13-18 5173:26-32 5336:8-21 5340:8-21 5755:16-20 5761:12-16 6296:27-32 6328:12-19 6338:16-23 6356:93-100 6357:15-20 6767:60-75 6768:60-75 6769:60-75 6770:59-74 6847:16-21 6997:16-21 7150:21-28 7160:8-21 7161:134-149 7162:8-21 7210:30-39 7264:8-21 7266:8-21 7314:23-38 7334:46-55 7334:56-63 7389:14-24 7576:21-26 7586:21-31 7593:24-34 7596:21-31 7624:53-58 7630:52-57 7696:48-53
 @ ./node_modules/@vue/runtime-dom/dist/runtime-dom.esm-bundler.js
 @ ./node_modules/vue/dist/vue.runtime.esm-bundler.js
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080&sockPath=/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

**Comment by hy739455177** [comment]
> _仅适用于维护者：_
> 
> * [ ]  webpack-4
> * [ ]  webpack-5
> * [true]  漏洞
> * [ ]  严重错误
> * [ ]  增强
> * [ ]  文件
> * [ ]  表现
> * [ ]  依赖
> * [ ]  问题

**Comment by hy739455177** [comment]
bug







------------------&nbsp;原始邮件&nbsp;------------------
发件人: "webpack ***@***.***&gt;; 
发送时间: 2021年7月2日(星期五) 中午11:49
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [webpack/webpack]  error  in .***@***.***/reactivity/dist/reactivity.esm-bundler.js (#13688)





 
For maintainers only:
  
 webpack-4
 
 webpack-5
 
 bug
 
 critical-bug
 
 enhancement
 
 documentation
 
 performance
 
 dependencies
 
 question

**Comment by snitin315** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

**Comment by hy739455177** [comment]
> _仅适用于维护者：_
> 
> * [ ]  webpack-4
> * [ ]  webpack-5
> * [ checked]  漏洞
> * [ ]  严重错误
> * [ ]  增强
> * [ ]  文件
> * [ ]  表现
> * [ ]  依赖
> * [ ]  问题

**Comment by jingleding** [comment]
我也遇到这个问题，怎么解决呢，今天一来打包就坏了

**Comment by jingleding** [comment]
"webpack": "^4.46.0",
@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-router": "~4.5.0",
    "@vue/cli-plugin-typescript": "~4.5.0",
    "@vue/cli-plugin-vuex": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.0.0-0",
    "@vue/eslint-config-prettier": "^6.0.0",
    "@vue/eslint-config-typescript": "^5.0.2",
    这是我的配置文件

**Comment by hy739455177** [comment]
我没解决，我也不知道咋整，然后想了下，还是用vite吧，vite和vue3更配




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "webpack/webpack"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月2日(星期五) 下午4:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [webpack/webpack]  error  in .***@***.***/reactivity/dist/reactivity.esm-bundler.js (#13688)





 
"webpack": "^4.46.0",
 @vue/cli-plugin-babel": "~4.5.0",
 ***@***.***/cli-plugin-eslint": "~4.5.0",
 ***@***.***/cli-plugin-router": "~4.5.0",
 ***@***.***/cli-plugin-typescript": "~4.5.0",
 ***@***.***/cli-plugin-vuex": "~4.5.0",
 ***@***.***/cli-service": "~4.5.0",
 ***@***.***/compiler-sfc": "^3.0.0-0",
 ***@***.***/eslint-config-prettier": "^6.0.0",
 ***@***.***/eslint-config-typescript": "^5.0.2",
 这是我的配置文件

**Comment by jingleding** [comment]
哦，我是今天突然不行了，之前是可以的



---Original---
From: ***@***.***&gt;
Date: Fri, Jul 2, 2021 16:34 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [webpack/webpack]  error  in .***@***.***/reactivity/dist/reactivity.esm-bundler.js (#13688)




 我没解决，我也不知道咋整，然后想了下，还是用vite吧，vite和vue3更配 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "webpack/webpack"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2021年7月2日(星期五) 下午4:10 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [webpack/webpack]  error  in .***@***.***/reactivity/dist/reactivity.esm-bundler.js (#13688) 
 
 
 
 
 
   
 "webpack": "^4.46.0", 
  @vue/cli-plugin-babel": "~4.5.0", 
  ***@***.***/cli-plugin-eslint": "~4.5.0", 
  ***@***.***/cli-plugin-router": "~4.5.0", 
  ***@***.***/cli-plugin-typescript": "~4.5.0", 
  ***@***.***/cli-plugin-vuex": "~4.5.0", 
  ***@***.***/cli-service": "~4.5.0", 
  ***@***.***/compiler-sfc": "^3.0.0-0", 
  ***@***.***/eslint-config-prettier": "^6.0.0", 
  ***@***.***/eslint-config-typescript": "^5.0.2", 
  这是我的配置文件

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Please use English.

**Comment by liamfend** [comment]
> 我没解决，我也不知道咋整，然后想了下，还是用vite吧，vite和vue3更配
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "webpack/webpack" ***@***.***&gt;; 发送时间:&nbsp;2021年7月2日(星期五) 下午4:10 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [webpack/webpack] error in .***@***.***/reactivity/dist/reactivity.esm-bundler.js (#13688) "webpack": "^4.46.0", @vue/cli-plugin-babel": "~4.5.0", ***@***.***/cli-plugin-eslint": "~4.5.0", ***@***.***/cli-plugin-router": "~4.5.0", ***@***.***/cli-plugin-typescript": "~4.5.0", ***@***.***/cli-plugin-vuex": "~4.5.0", ***@***.***/cli-service": "~4.5.0", ***@***.***/compiler-sfc": "^3.0.0-0", ***@***.***/eslint-config-prettier": "^6.0.0", ***@***.***/eslint-config-typescript": "^5.0.2", 这是我的配置文件 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
你去 node_modules看下webpack版本。。。  强制指定一下版本webpack的版本 。。
