### ISSUE TITLE
Nested Routing with webpack dev server not working

### ISSUE THREAD

**Issue by mdirshaddev** [webpack/webpack#13681]
I have a query webpack is used to build the creact-react-app and so cra works properly with nested routing with react-router-dom. But when i configure react app with webpack 5. Nested routing stops working. Its says history.pushState error.

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Please ask this in CRA repo
