### ISSUE TITLE
* in html parameters need to be escaped

### ISSUE THREAD

**Issue by vicentelyrio** [webpack/webpack#1369]
I do not know if it's exactly a bug, but after a lot of debug to find out why the watch had stopped, I discovered that the problem was in the "accept" property of file input:
 <input accept="images/*" /> .

The * must be be escaped.

edit: I'm using JSX.

**Comment by shama** [comment]
Could you provide more information to reproduce this issue and how it relates to webpack? Thanks!

**Comment by vicentelyrio** [comment]
I'm sorry, just now I realized that my comment was truncated.

**Comment by shama** [comment]
Weird. Can you post an example so I can try and reproduce? Thanks!

**Comment by vicentelyrio** [comment]
I tried to reproduce using a clean project (https://github.com/webpack/react-starter), but no error occurred.
The project which occurs is rather large and has many layers, so I will try to investigate further, and try to isolate the problem.

**Comment by bebraw** [comment]
@vicentelyrio Any luck in figuring out how to reproduce the issue?

**Comment by vicentelyrio** [comment]
Hi man, I just made a stack with everything that I was using in the project in which the error occurred, basically webpack, gulp, babel, react and jsx.
And I was unable to reproduce, so I get back to the project and started to remove things, and after removing a gulp task that handles translation, it worked as expected.

So the problem is in the (confused), stack that this project has. 

Sorry about that, and thanks for all the feedback.
