### ISSUE TITLE
Improve emitAsset error with sourceFilename

### ISSUE THREAD

**Issue by artaommahe** [webpack/webpack#13695]
## Feature request

Currently assets with the same filenames provide an error like `Conflict: Multiple assets emit different content to the same filename ${file}`. This error includes final file destination (like `assets/smth.svg` e.x.) but there is no way to know what particular local files lead to this.
https://github.com/webpack/webpack/blob/c181294865dca01b28e6e316636fef5f2aad4eb6/lib/Compilation.js#L3506

**What is the expected behavior?**

Error message should provide info about what file has same final filename.

**What is motivation or use case for adding/changing the behavior?**

It's hard to search through dozen files with same name in monorepo to find that single one that conflicts with other.

**How should this be implemented in your opinion?**

Add `assetInfo.sourceFilename` to the error to help find files.

**Are you willing to work on this yourself?**
nope

**Comment by alexander-akait** [comment]
Note, not all assets can have `sourceFilename`, but there it possible we can do

**Comment by artaommahe** [comment]
🙂
