### ISSUE TITLE
TypeError: Cannot read property 'jsonData' of undefined

### ISSUE THREAD

**Issue by jkthinksmart** [webpack/webpack#13709]
During app rebuild this error happens:

let data = module.buildInfo.jsonData;
TypeError: Cannot read property 'jsonData' of undefined

Webpack 5.42.0

**Comment by dnsnx** [comment]
This bug is already mentioned here:

https://github.com/webpack/webpack/issues/13691

**Comment by dnsnx** [comment]
Duplicate of #https://github.com/webpack/webpack/issues/13691
