### ISSUE TITLE
Target: node12 throws no dynamic import

### ISSUE THREAD

**Issue by guybedford** [webpack/webpack#13700]
# Bug report

**What is the current behavior?**

When setting `target: 'node12'` for a modules build, I get the message:

```
Error: For the selected environment is no default ESM chunk format available:
ESM exports can be chosen when 'import()' is available.
JSONP Array push can be chosen when 'document' is available.
Select an appropriate 'target' to allow selecting one by default, or specify the 'output.chunkFormat' directly.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Set `target: 'node12'` and build a module with a dynamic import into an output module.

**What is the expected behavior?**

Node.js 12 supports the latest modules features so should work equally well as a target here.

**Other relevant information:**
webpack version:  5.42.0
Node.js version: Building on Node.js 14.15.5
Operating System: 
Additional tools:

**Comment by alexander-akait** [comment]
Do you use es module output?

**Comment by guybedford** [comment]
Yes this is for the es module output specifically.

**Comment by alexander-akait** [comment]
You need specify Node.js version https://github.com/webpack/webpack/blob/main/lib/config/target.js#L174, because 12 includes `12.0.0`/`12.1.0`/etc but these versions are not supported dynamic import

**Comment by guybedford** [comment]
Right, is there a way to specify latest 12 though? It seems a bit unintuitive otherwise to expect all versions of a release line.

**Comment by alexander-akait** [comment]
12.7 means your support 12.7 and above, ideally you should set the same version of node as you specify in package.json, it's like a lower limit

**Comment by guybedford** [comment]
Ah ok thanks I wasn't aware that syntax was supported. So effectively `12` means `12.0` and not `12.latest`. Is there a syntax for `12.latest` without knowing the current minor?

**Comment by alexander-akait** [comment]
No `latest` syntax

**Comment by guybedford** [comment]
Thanks for the info. Closing.
