### ISSUE TITLE
Specify target context for chunk loading

### ISSUE THREAD

**Issue by ColCh** [webpack/webpack#13735]
## Feature request

**What is the expected behavior?**

Specify `window` context (as for `document.createElement` as following) AND element append target for `ensureChunkHandlers`

**What is motivation or use case for adding/changing the behavior?**

This is useful for bundling libraries using webpack. Let me elaborate on this a bit.

As lib author (like playerjs or hls.js - that are examples, I'm not author nor collaborator) we need to avoid patched prototypes at `window` execution context. I'm speaking of these: https://stackoverflow.com/questions/55283724/monkey-patch-of-array-prototype-filter-breaks-angularjs-1-6 or https://developers.google.com/web/updates/2018/03/smooshgate

That is library? It's bundled JS code loaded from the CDN, like jQuery. But it bundles by company and does some business logic (imagine like "Facebook like widget" or something like that)

And, to solve global `prototype` patching, one of ways to resolve that (for library code). One of ways to resolve is to create new `iframe` and execute code inside of it's context of execution.

Let me show some code lines for that

```js
// we want to load this in "fresh" unpatched window context
const scriptSrcToLoad = 'http://example.com/foobar_widget.js';

const iframe = document.createElement('iframe');
document.body.appendChild(iframe);
iframe.document.open(); iframe.document.close(); // that's for Firefox

const unpatchedWindow = iframe.contentWindow;
const scriptElement = unpatchedWindow.document.createElement('script');
scriptElement.src = scriptSrcToLoad;
unpatchedWindow.document.body.append(scriptSrcToLoad);

// that's it, `scriptSrcToLoad` will be loaded inside of `iframe` window,
// therefore, will have un-monkeypatched objects.
```

The problem is, we can't do that for webpack chunks, like `import` and other.

--------
Sidenote: Also, we have Realms proposal https://github.com/tc39/proposal-realms which does same thing as isolated `window` from `iframe` (in context of retrieving monkeypatch-free global environment). There even is an example **Realms vs iframes** https://github.com/tc39/proposal-realms/blob/main/explainer.md#example-iframes-vs-realms

**How should this be implemented in your opinion?**

For this function,

https://github.com/webpack/webpack/blob/c181294865dca01b28e6e316636fef5f2aad4eb6/lib/RuntimeGlobals.js#L78-L81

we just want to provide more control for it

Here is code which inserts `script` tag for jsonp (script) chunks

https://github.com/webpack/webpack/blob/c181294865dca01b28e6e316636fef5f2aad4eb6/lib/runtime/LoadScriptRuntimeModule.js#L152

So, my proposal is to replace hardcoded `document.head` with runtime global (correct me here if I'm wrong)

So if we want to append our chunks into `<body>`, we just can write this:

```js
__webpack_chunk_append__ = document.body;

import('./src/my-stuff.js'); // hooray, <script> append into <body>!
```

**Are you willing to work on this yourself?**
yes, BUT tell me if this should be included into webpack or not, and help me discussing this issue.

AND may be this feature should be a bit more universal than just for `jsonp` script chunks?

what about `<link>` prefetch? https://github.com/webpack/webpack/blob/c181294865dca01b28e6e316636fef5f2aad4eb6/lib/web/JsonpChunkLoadingRuntimeModule.js#L217
--------------------------
And, may be, this issue is already resolved?

By using `output.chunkLoading: 'import'` and `output.importFunctionName: 'MY_CUSTOM_IMPORT'`

https://webpack.js.org/configuration/output/#outputchunkloading
https://webpack.js.org/configuration/output/#outputimportfunctionname

But I don't really understand if these are really related. Please correct me if i'm wrong and subject feature should not be implemented in webpack.

--------

Hacky hacks. Seems that desired behaviour is achievable via `output.chunkLoading: 'import'`, custom `importFunctionName` and mocking it out with custom implementation.

Demo project with sandbox: https://github.com/ColCh/webpack-13735

I'm not sure if this issue is really resolved by this demo project though...

**Comment by sokra** [comment]
I don't think that use case is that common to be included in the core.

It's possible to replace the whole `LoadScriptRuntimeModule` with your own variant of it.

Alternatively I'm open to add a `__webpack_load_script__` module API to override the script loading at runtime. That's only a 5 LOC change and would allow to do that:

``` ts
const old = __webpack_load_script__;
__webpack_load_script__ = (url: string, done: (event: Event)=>void, key?: string, chunkId?: string | number): void => {
  // Your custom implementation
  // Optionally falling back to 'return old(url, done, key, chunkId)'
};
```

**Comment by ColCh** [comment]
Sure, that's why I was not sure writing that text :)

I think that dynamic `import()` + `importFunctionName` is way more functional, and I really like it.
Demo is here: https://github.com/ColCh/webpack-13735

And it's really looks like `__webpack_load_script__` override, but it seems to cover all our needs for `import()` control... "Seems to"

Let my try to work a bit on that... I may return with `__webpack_load_script__` proposal next time. Load script function override at runtime is a bit different than current issue, so it's good idea to just create new one for that.

Thank you for your time, and best of luck :) closing the issue.
