### ISSUE TITLE
Webpack 5: Invalid export when using runtimeChunk 'single'

### ISSUE THREAD

**Issue by bkuster** [webpack/webpack#13731]
# Webpack 5: Invalid `export` when using runtimeChunk 'single'

**What is the current behavior?**
When exporting a `module` from a multiple entry project with a common runtime chunk, the `export` is wrapped in an arrow function.

**If the current behavior is a bug, please provide the steps to reproduce.**
I created a small reproducable repo [here](https://github.com/bkuster/webpack-runtime-bug).

In short:
1. Create two entry files, both exporting something.
2. Use experiments outputModules, create an esm library and optimize to use a runtime chunk (see attached config below).
3. Checkout the create file, you will see the export wrapped in an arrow function. This is not valid syntax, export is not expected in any other scope then the top level of a module.

**What is the expected behavior?**
Im not sure, since im not sure how the runtime chunk works on a lower level. But I do expect webpack to produce valid syntax, as such _failing_ would be the initial valid behavior I would expect.

**Other relevant information:**
webpack version:  5.42.1
Node.js version: 12.18.0
Operating System: Ubuntu 20.04.4
Additional tools: None

**Attachment: Config**
```js
module.exports = {
  experiments: {
    outputModule: true,
  },
  entry: {
    app: './index.js',
    other: './otherIndex.js',
  },
  mode: 'development',
  output: {
    path: path.join(__dirname, 'dist'),
    filename: '[name].js',
    library: {
      type: 'module',
    },
    module: true,
  },
  optimization: {
    runtimeChunk: 'single',
  },
}
```

**Comment by alexander-akait** [comment]
Fixed https://github.com/webpack/webpack/releases/tag/v5.44.0, please update webpack, also to avoid es6 syntax, please set `target: ['web', 'es5']`, or create browserslist with required browsers https://webpack.js.org/configuration/target/#browserslist
