### ISSUE TITLE
Source maps only generated for .js files

### ISSUE THREAD

**Issue by guybedford** [webpack/webpack#13740]
# Bug report

**What is the current behavior?**

In ncc, when generating builds for `.cjs` or `.mjs` files, source maps seem to be disabled for these non-`.js` extensions.

**If the current behavior is a bug, please provide the steps to reproduce.**

ncc currently includes the following hack for the `.cjs` file extension:

* Adding a `.js` extension to the output filename - https://github.com/vercel/ncc/blob/main/src/index.js#L260
* Then reverting this in the asset layer - https://github.com/vercel/ncc/blob/main/src/index.js#L436

Ideally this shouldn't be necessary to hack around and seems to be affecting `.mjs` as well in my initial tests.

**What is the expected behavior?**

Source maps should be fully supported for all JS file extensions.

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

**Comment by alexander-akait** [comment]
Yep, bug, feel free to send a fix

**Comment by guybedford** [comment]
After further checking this does seem to be working fine for the `.mjs` cases, it is just the `.cjs` hack that is needed here.

**Comment by alexander-akait** [comment]
Bug here https://github.com/webpack/webpack/blob/78e9a002c6b2ba2a4461769f8074256bce6cd9ff/lib/SourceMapDevToolPlugin.js#L155, just add cjs extension
