### ISSUE TITLE
Inject vendor bundle globally

### ISSUE THREAD

**Issue by malykhinvi** [webpack/webpack#1374]
The case:
1. There is old school angular application.
2. There is index.html, that contains a list of vendor dependencies (jquery, jquery-ui, moment, lodash, angular and so on). After vendor dependencies there is a huge list of angular components, related to the application itself.
3. All vendor dependencies are minified.

I'm trying to use webpack to build all the stuff and create two bundles vendor.js and application.js. I don't want to use not minified versions of the vendor scripts, because of two reasons:
* it will increase the build time, since I'll have to at lease uglify them for production.
* probably, vendor knows how to uglify sources better, than me. For example, uses Google Closure compiler with advanced flag.

I've played around combination of ```externals```, ```ProviderPlugin```, ```exports, imports, expose-loaders, raw```, but my solution look like crutch.

Is there some straightforward way to include all minified vendor files in the global scope, as it would be if I would have included them in the document in ```<script>``` tag?

**Comment by shama** [comment]
I would create 2 builds:
```js
module.exports = {
  entry: {
    vendor: './src/vendor.js',
    application: './src/app.js',
  },
  output: {
    path: './dist/',
    filename: '[name].js'
  }
}
```
then include both script tags as needed.

You can expose a library globally with `window.$ = window.jQuery = require('jquery')`

If you need to dynamically add a script tag:
```js
var script = document.createElement('script')
script.src = '/path/to/script.js'
document.body.appendChild(script)
```

or last resort is the [script-loader](https://github.com/webpack/script-loader) which uses `execScript/eval` to simulate a script being added like it was placed with a script tag. The script loader has some drawbacks with source maps and some security concerns though.
