### ISSUE TITLE
Question: Is it a bad idea to run a new webpack instance from within a loader

### ISSUE THREAD

**Issue by adjavaherian** [webpack/webpack#1375]
I've been working on this loader which creates a new webpack instance with the entry file, runs the dependencies and collects all the sass files into one css file for that entry point.  Is there a better way to do this? I feel like spawning a new webpack instance from within the loader is overkill and its definitely slow. Here's the repo and example of it working.

https://github.com/adjavaherian/sass-lifter-loader

**Comment by bebraw** [comment]
Is this relevant still?

**Comment by adjavaherian** [comment]
I don't think I ever got an answer.  Is it  unecessary to run a new webpack instance from within a loader?

Thanks.

**Comment by bebraw** [comment]
It definitely feels a bit much and it's probably better to avoid it if possible. Perhaps someone else has a better answer. You can try to figure out how other loaders deal with the same problem.

**Comment by adjavaherian** [comment]
sounds good.  ya, lets go ahead and close this one.  thanks.

**Comment by jhnns** [comment]
@adjavaherian I think, this should be doable with a plugin. If you don't know how you get all scss files, you can also provide a loader which keeps track of all scss files (similar to the extract-text-webpack-plugin)
