### ISSUE TITLE
WebAssembly module is (sometimes) included in initial chunk.

### ISSUE THREAD

**Issue by jkosir** [webpack/webpack#13755]
# Bug report

**What is the current behavior?**
When including a wasm module with `const wasmPromise = import('@/path/to/wasm/module.wasm')` the build sometimes fails without any other changes being done to the code or configuration (like 1 in 15 times). Otherwise it works as expected, wasm module is not included in initial chunk and is loaded asynchronously when requested.

I have even tried wrapping the import in an additional function as suggested, but the behaviour stays the same.
```
export function import_wasm (): Promise<any> {
    return import('@/path/to/wasm/module.wasm')
}
```

The full error is:
```
WebAssembly module is included in initial chunk.
This is not allowed, because WebAssembly download and compilation must happen asynchronous.
Add an async splitpoint (i. e. import()) somewhere between your entrypoint and the WebAssembly module:
multi ./src/boot.ts --> ./src/boot.ts --> ./src/store/index.ts --> ./src/store/modules/builder/index.ts --> ./src/store/modules/builder/actions.ts --> ./src/wasmWrapper.ts --> ./src/wasm/import_wasm.ts --> ./src/wasm/module.wasm
```

**What is the expected behavior?**
Webpack build is deterministic.

**Other relevant information:**
webpack version:  4.46.0
Node.js version:  7.7.6
Operating System: Docker image based on `debian:stretch`
Additional tools: Webpack config as generated by `@vue/cli 4.5.11`
Full package.json:
https://gist.github.com/jkosir/3d83889c63244184d38ead44084d7188

**Comment by alexander-akait** [comment]
Fixed in webpack v5, please consider to update, webpack v4 only accept security fixes, sorry, also you can ask vue cli about webpack v5 compatibility
