### ISSUE TITLE
Explicit error message when missing `filename` in `output`?

### ISSUE THREAD

**Issue by henriquea** [webpack/webpack#1376]
One of the stupid and silly things you miss when you're working at 1am. 

If you don't have the `filename` in your config when you run webpack cli it doesn't throw any error message instead it just outputs the help.

```js
output: {
  path: path.join(__dirname, 'dist'),
  publicPath: './'
}
```

Maybe display an explicit error message would be more appropriate here no?

**Comment by peduarte** [comment]
👍

**Comment by akx** [comment]
:+1: 

Just bumped into this myself.

**Comment by henriquea** [comment]
@sokra 🙌
