### ISSUE TITLE
Dynamic imports with query parameters

### ISSUE THREAD

**Issue by youroff** [webpack/webpack#13760]
## Feature request

**What is the expected behavior?**
I'm trying to use dynamic module loading like this:
```
  const App = lazy(() => import('./protected?token=' + token));

  return <Suspense fallback={<div>Loading... </div>}>
    {token && <App/> || <Login/>}  
  </Suspense>;
```
Currently the module is perfectly resolved and split when no query parameters used. Once I add query param, the build fails with: `protected\:5 Uncaught Error: Cannot find module './protected?token=XXXXXXX'`

**What is motivation or use case for adding/changing the behavior?**
In my case it's some authentication for the part of the app code.

**How should this be implemented in your opinion?**
`?` and the rest could be just stripped on the module resolution and added back once the final url is formed.

**Are you willing to work on this yourself?**
yes, with some hints

**Comment by alexander-akait** [comment]
> Currently the module is perfectly resolved and split when no query parameters used. Once I add query param, the build fails with: protected\:5 Uncaught Error: Cannot find module './protected?token=XXXXXXX'


It means you have invalid URL, please create reproducible example to I can help you
