### ISSUE TITLE
Option to generate only one banner.txt file - webpack.BannerPlugin

### ISSUE THREAD

**Issue by knynkwl** [webpack/webpack#13769]
## Feature request

**What is the expected behavior?**
Only generate one banner.txt file

**What is motivation or use case for adding/changing the behavior?**
Currently, we have a lot of js files that are being split. This plugin adds a new file for every js file generated, but all the copyright is the same across all txt files.

**How should this be implemented in your opinion?**
As an option

**Are you willing to work on this yourself?**
no :(

**Comment by alexander-akait** [comment]
Sorry, banner plugin for creating something on the top of file(s), creating new file is out of scope banner plugin, anyway you can create own plugin https://webpack.js.org/contribute/writing-a-plugin/.

Also you can have `test`/`include`/`exclude` (https://webpack.js.org/plugins/banner-plugin/) to add something on a one file.
