### ISSUE TITLE
Webpack throws an error when tslint-loader has errors

### ISSUE THREAD

**Issue by xgidiussenjensent-els** [webpack/webpack#13763]
# Bug report

We are having problems with a change introduced in Webpack version 5.22.0 (https://github.com/webpack/webpack/pull/12632).
With that change, Webpack throws errors when a module has errors. 

In our case, we use the tslint-loader module for linting. 
We have configured the tslint-loader module to emit linting errors as errors and not warnings. 

**What is the current behavior?**

Webpack throws an error when a module (in this case tslint-loader) throws an error (in this case a linting error).

Running with the following webpack rule for the tslint-loader module:
````
{
  test: /\.ts(x?)$/,
  enforce: "pre",
  use: [
    {
      loader: 'tslint-loader',
      options: {
        emitErrors: true,
        failOnHint: true
      }
    }
  ],
  exclude: excludeDir
};
````
Then starting an express server with `webpack-dev-middleware`. 
When saving a tsx file that causes the slint-loader module to throw a lint error, webpack now throws an error, which breaks the express server.

**What is the expected behavior?**
Webpack does not throws an error when a loaded module throws an error. 
Either this is the default behavior or it can be achieved through configuration.

**Other relevant information:**
webpack version: v5.44.0
Node.js version: v14.17.1
Operating System: Ubuntu 20.04.2
Additional tools: N/A

**Comment by alexander-akait** [comment]
Please open an issue in `tslint-loader`, we can't fix it here, sorry

**Comment by xgidiussenjensent-els** [comment]
That's ok @alexander-akait, thank you
