### ISSUE TITLE
Question: get list of files rebuilt in stats

### ISSUE THREAD

**Issue by kolodny** [webpack/webpack#1377]
What I'm trying to do is rerun only the tests that relied on that dep tree, So assume I had this structure:

```js
// ./index.js
import { a } from './a';

//###############

// ./a.js
import { b } from './b';
import { c } from './c';

//###############

// ./b.js
export const b = 'b';

//###############

// ./c.js
export const c = 'c';
```

Assuming I have files `./test/a.js`, `./test/b.js`, `./test/c.js` that import the `a`, `b`, and `c` modules respectively so on initial build I want to run all those files through my tester, but if I later change `./c.js` I only want to run tests `./test/a.js` and `./test/c.js` but not `./test/b.js`.

I tried dumping the stats in the `compiler.plugin('done', fn)` callback but it doesn't look like the tree has this information, here's what my config file looks like:

```js
  entry: {
    main: './index',
    tests: glob.sync("./test/**/*.js")
  },
  output: {
    path: path.join(__dirname, 'static'),
    filename: '[name].entry.js',
    publicPath: '/static/'
  },

```

Is there a way to do this?

**Comment by aaronjensen** [comment]
I'm interested in this as well, I was thinking of modifying karma-webpack to make use of this information. It seems like it would be available via the mechanisms used in https://github.com/webpack/webpack/blob/master/lib/HotModuleReplacementPlugin.js but I don't understand the code well enough...

**Comment by sokra** [comment]
The information is in the stats. There is a `cached` or `built` flag on modules.

**Comment by aaronjensen** [comment]
@sokra Thanks, does it also include which files are affected by the rebuilds? In other words if ModuleA is rebuilt, and ModuleB depends on it, we can know that ModuleB was affected?

**Comment by sokra** [comment]
Each module in stats include a list of reasons, which is a list of module that depend on this module. You need to follow the graph.

**Comment by aaronjensen** [comment]
Awesome, thanks @sokra. So I can just use the `compiler.plugin("done", ...)` hook and do work there. I'll give it a shot, thanks!

**Comment by kolodny** [comment]
@aaronjensen keep me posted if you make any progress

**Comment by aaronjensen** [comment]
@kolodny I got it working, seems to work well. I'm testing in our project now and will open a pull back to karma-webpack if it works out. 

Feel free to try it out:

https://www.npmjs.com/package/karma-webpack-with-fast-source-maps

https://github.com/aaronjensen/karma-webpack/compare/file-source-map-support...aaronjensen:master

/cc @sokra

**Comment by kolodny** [comment]
@aaronjensen Nice! Any plans on a mocha version?

**Comment by aaronjensen** [comment]
@kolodny karma is a runner that can run mocha tests. mocha-loader already supports hot reloading in a browser.

**Comment by kolodny** [comment]
@aaronjensen I was thinking of having the tests run on node on the command line

**Comment by aaronjensen** [comment]
ah, yea that'd be cool. I probably won't do it though. It shouldn't be too hard to adapt what I did to that.
