### ISSUE TITLE
Uncaught ReferenceError: Cannot access '__WEBPACK_DEFAULT_EXPORT__' before initialization

### ISSUE THREAD

**Issue by Abito12** [webpack/webpack#13779]
# Bug report

 
I saw the issue https://github.com/webpack/webpack/issues/13411. This talks about the circular dependencies.

 
But in my case the only change is webpack upgrade from 4 to 5.
![IssueWebpack](https://user-images.githubusercontent.com/18062708/125288905-44fe6e00-e33c-11eb-86de-d98f61881030.PNG)

webpack version:  5.40.0
Node.js version: v14.17.2
Operating System: windows OS

**Comment by alexander-akait** [comment]
Please do not ignore the issue template, fix it and I will reopen

**Comment by alexander-akait** [comment]
Fill out all fields from https://github.com/webpack/webpack/issues/new?assignees=&labels=&template=Bug_report.md

**Comment by alexander-akait** [comment]
But in 99% cases you have circular dependencies

**Comment by Abito12** [comment]
I can see a difference in the file generated before and after upgrade from v4 to v5.

![image](https://user-images.githubusercontent.com/22198939/125299869-29e52b80-e347-11eb-8732-36d5c5e039a5.png)

``
__webpack_require__.d(__webpack_exports__, {
    /* harmony export */
    "default": ()=>(__WEBPACK_DEFAULT_EXPORT__)/* harmony export */
});
``
This is the extra line of code getting generated and is causing the issue.

![image](https://user-images.githubusercontent.com/22198939/125300315-88120e80-e347-11eb-9290-d4804596f9fa.png)

**Comment by alexander-akait** [comment]
Because you have circular deps

**Comment by AnubhutiRoX** [comment]
how can you identify circular dependencies. any suggestions ?

**Comment by alexander-akait** [comment]
You can try https://github.com/aackerman/circular-dependency-plugin
