### ISSUE TITLE
".s" in AMD target bundled js often change and cause content hash change

### ISSUE THREAD

**Issue by geekeren** [webpack/webpack#13773]
There is always a ".s" equal to a number, in my bundled javascript, which is in a AMD target, and I will use requireJS to load the js file.

for example

```javascript

define("ModuleName", [], (function () {
    return function (t) {
        var e = {};

        function r(n) {
            if (e[n]) return e[n].exports;
            var o = e[n] = {i: n, l: !1, exports: {}};
            return t[n].call(o.exports, o, o.exports, r), o.l = !0, o.exports
        }

        return r.m = t,... , r.o = function (t, e) {
            return Object.prototype.hasOwnProperty.call(t, e)
        }, r.p = "", r(r.s = 142)
    }({
        142: function (t, e, r) {
            r("x4Sl"), t.exports = r("QNkY")
        }
```

Sometimes, The number "142" in the bundled js will change (into 141) even though my source code doesn't.
 I want to know what is the ".s=" and the number after it in the code. And how can I avoid the number's change to cause content-hash changed?

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

**Comment by alexander-akait** [comment]
Please respect time of other developers, we don't know your version/code/configuration/etc, so it is impossible to help
