### ISSUE TITLE
Webpack 5 - failed to load chunk on IE 11. Problem with script added with appendchild

### ISSUE THREAD

**Issue by stachupl** [webpack/webpack#13772]
# Bug report

Question on StackOverflow: https://stackoverflow.com/questions/68317209/webpack-5-failed-to-load-chunk-on-ie-11-problem-with-script-added-with-append

**What is the current behavior?**
After upgrade webpack from version 4 to 5 I have problem with IE 11. I have all chunks in path '/' and I have script with code:
```
var url = './assets/js/vendor/library/lib.js'
var script = document.createElement('script')
script.src = url
script.async = true
document.getElementsByTagName('head')[0].appendChild(script)
```
After executing the above code, the browser starts trying to fetch chunks from the path '/assets/js/vendor/library/chunk.js', not from '/chunk.js' even lib.js is empty file. In Chrome everything works fine. When I comment on the above code, everything starts to work.

Variable window.location.pathname is setted correctly to '/'.

**If the current behavior is a bug, please provide the steps to reproduce.**
Add the above code

**What is the expected behavior?**
After executing the above code, the chunks should be fetched from the path '/'.

**Other relevant information:**
webpack version:  5.44.0
Node.js version: 14.17.3
Operating System: Windows 10 Enterprise version 20H2 19042.1083
Additional tools:

**Comment by alexander-akait** [comment]
Expected, you need polyfill https://developer.mozilla.org/ru/docs/Web/API/Document/currentScript or set `publicPath: '/'`
