### ISSUE TITLE
Build simple bundle no runtime chunk

### ISSUE THREAD

**Issue by cdalexndr** [webpack/webpack#13787]
## Feature request

**What is the expected behavior?**

Build simple bundle without any runtime chunk code overhead.
Stackoverflow question: https://stackoverflow.com/questions/68369841/webpack-simple-bundle-no-runtime-chunk

**What is motivation or use case for adding/changing the behavior?**

Building simple, independent bundles. No need for additional runtime code (useless overhead).

**How should this be implemented in your opinion?**
Add either:

- target: 'bundle'
- optimization.runtimeChunk: 'disabled'

**Are you willing to work on this yourself?**
no

**Comment by alexander-akait** [comment]
Duplicate, already tracked https://github.com/webpack/webpack/issues/11382 and https://github.com/webpack/webpack/issues/2933, but it is possible only for libraries
