### ISSUE TITLE
不开启mfsu或dynamicImport，build失败

### ISSUE THREAD

**Issue by rimline** [webpack/webpack#13784]
# Bug report

**What is the current behavior?**
**图一：**
![image](https://user-images.githubusercontent.com/16633071/125558144-9560c6b5-c444-4b63-b29b-cc187ca562f7.png)
[https://github.com/webpack/webpack/issues/12345#issuecomment-755273757](url)
**图二**
![Snipaste_2021-07-14_11-52-58](https://user-images.githubusercontent.com/16633071/125558427-9a64ea56-8ae4-40b1-92f9-ba1930dc0176.png)
初步分析：图一的构建失败，造成图二中报错的出现
**复现条件**：配置文件不开启mfsu或dynamicImport，build失败

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
umi version: 3.5.8
webpack version:  5
Node.js version: 14.16.1
Operating System: win10

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Please use English
