### ISSUE TITLE
ModuleFederationPlugin does not pass down options.shareScope to ContainerPlugin

### ISSUE THREAD

**Issue by jacobp100** [webpack/webpack#13797]
# Bug report

ModuleFederationPlugin does not pass down options.shareScope to ContainerPlugin

In these lines, https://github.com/webpack/webpack/blob/7fbf3af0950713ccd2de7130b7208ae02f51616b/lib/container/ModuleFederationPlugin.js#L63-L69, `options.shareScope` is not passed down, even though ContainerPlugin accepts this.

**What is the current behavior?**

nil

**If the current behavior is a bug, please provide the steps to reproduce.**

nil

**What is the expected behavior?**

Either it should be passed down, or an additional option under a separate name to pass down (i.e. `containerShareScope`)

**Other relevant information:**
webpack version:  5.44.0
Node.js version: v14.15.1
Operating System: macOS Big  Sur
Additional tools: nil

**Comment by alexander-akait** [comment]
Because it is different options? `ContainerPlugin` is low level api.

**Comment by jacobp100** [comment]
@alexander-akait If I'm not mistaken, shared scopes don't work without passing this down to the container plugin. If share scope considered low level, maybe it should be taken out of `ModuleFederationPlugin`.

**Comment by alexander-akait** [comment]
Please provide how we can reproduce the problem?

**Comment by jacobp100** [comment]
@alexander-akait Please see repo https://github.com/jacobp100/webpack-13797. Please let me know if you have further questions.

**Comment by meetdheeraj** [comment]
I would wish to quickly fix this issue. Please assign so I can raise a PR. Thanks.
