### ISSUE TITLE
Watch mode: Changes from node_modules are ignored unless package version is changed

### ISSUE THREAD

**Issue by vgaraschuk** [webpack/webpack#13793]
# Bug report

**What is the current behavior?**

When you start webpack in the watch mode, then change something in a module from node_modules, webpack initializes the build process, but the changes are not reflected in the resulting file. However if you change the version of that module, the changes are applied properly.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Open any node+webpack project with at least one production dependency.
2. Type "npm install".
3. Run webpack using "webpack watch --mode=development".
4. Go to node_modules/\<any-production-dependency\> and change one of its js files.
Actual result: the webpack watch detects the change in the js file, but does not include it in the webpack output file.
5. Go to node_modules/\<any-production-dependency\> and change "version" field in its package.json.
Actual result: the webpack watch detects the change in package.json, and includes the changed js file in the webpack output file.

**What is the expected behavior?**

The webpack watch should reflect any changes of node_modules in the output file. Looks like it doesn't do that now, because it invalidates the module cache only if its version is changed. The cache should be invalidated if webpack detects a change in the js files, even if the module version stays the same. This is useful when developing a library, linked with npm link.

**Other relevant information:**
webpack version:  5.44.0
Node.js version: 14.17.0
Operating System: Windows 10
Additional tools: None

**Comment by alexander-akait** [comment]
Expected and will be answered a lot of time https://github.com/webpack/webpack/issues/11612
