### ISSUE TITLE
DefinePlugin doesn't replace argument to a function using typescript

### ISSUE THREAD

**Issue by Wesleysaur** [webpack/webpack#13794]
**Do you want to request a *feature* or report a *bug*?**

Bug fix

**What is the current behavior?**
The key in my code is not replaced with the proper value. `undefined` is printed in console.log

**If the current behavior is a bug, please provide the steps to reproduce.**
```
yarn create react-app min-reproducable --template typescript
cd min-reproducable/
yarn eject
```
Add the following to the webpack config:
```
      new webpack.DefinePlugin({
        TEST: "test_string_here",
      })
```
Create a constants.tsx file in the src directory with the following:
```
declare var TEST: string;
export {TEST};
```
Add the following to App.tsx
```
import {TEST} from "./constants";

console.log(TEST);
```
Finally, run `yarn start`. `undefined` is printed in the console, not `test_string_here`. 

I've got a minimal reproducible repo here:
https://github.com/Wesleysaur/min-reproducable-webpack-define

**What is the expected behavior?**
I expected the identifier to be replaced with the value defined in my webpack config.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

node v14.13.1
"webpack": "4.44.2"
"typescript": "^4.1.2"

Thanks so much!!

**Comment by alexander-akait** [comment]
`DefinePlugin` doesn't change identifier in `import`/`export`, it is expected, you need to use:
```ts
var MY_TEST = TEST;
export {MY_TEST as TEST};
```

**Comment by alexander-akait** [comment]
Also please use:
```ts
 new webpack.DefinePlugin({
        TEST: JSON.stringify("test_string_here"),
})
```

https://webpack.js.org/plugins/define-plugin/#usage

Feel free to feedback

**Comment by Wesleysaur** [comment]
Got it, thanks
