### ISSUE TITLE
Optional chaining operator stripped when used with imported file

### ISSUE THREAD

**Issue by Cherry** [webpack/webpack#13792]
# Bug report

**What is the current behavior?**

When importing a file that exports a simple object, attempting to use that import with optional chaining results in the operator being stripped.

A full reproduction can be found on the repo here: https://github.com/Cherry/webpack-optional-chaining-imports, but here's a quick example:

- An `imported.js` and an `index.js`. `imported.js` looks like 
```js
export const foo = {
	bar: {
		baz: {},
	},
};
```
- `index.js` looks like this:
```js
import {foo} from './imported.js';

console.log(foo?.bar?.baz?.thing?.unknown);

const bar = {
    foo2: {
        baz2: {}
    }
};

console.log(bar?.foo2?.baz2?.thing?.unknown);
```

The resulting output is then as follows (removing the webpack bootstrap):
```js
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var _imported_js__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! ./imported.js */ "./src/imported.js");


console.log(_imported_js__WEBPACK_IMPORTED_MODULE_0__.foo.bar.baz.thing.unknown);

const bar = {
    foo2: {
        baz2: {}
    }
};

console.log(bar?.foo2?.baz2?.thing?.unknown);
```
As you can see, the optional chaining for the initial import from `imported.js` is entirely stripped, which causes a `TypeError` when run. The optional chaining on the inline object remains intact.

**What is the expected behavior?**

The expected behaviour would be for the `console.log(_imported_js__WEBPACK_IMPORTED_MODULE_0__.foo.bar.baz.thing.unknown);` line to instead read `console.log(_imported_js__WEBPACK_IMPORTED_MODULE_0__.foo?.bar?.baz?.thing?.unknown);`

**Other relevant information:**
webpack version:  5.44.0
Node.js version: 14.7.3
Operating System: Windows 10 21H1

**Comment by alexander-akait** [comment]
Thanks

**Comment by Cherry** [comment]
Looks like this might be a duplicate of #12960 after investigating further - sorry!

**Comment by alexander-akait** [comment]
Yep, you are right, duplicate, let's close in favor https://github.com/webpack/webpack/issues/12960, thanks for hing
