### ISSUE TITLE
Webpack 5 multiple web workers with shared chunks failing to load

### ISSUE THREAD

**Issue by ItsOnlyBinary** [webpack/webpack#13791]
# Bug report

**What is the current behavior?**
Multiple web workers within webpack are unable to load shared chunks from the correct url due to the workers self.location being different than the window.location of the original page

**If the current behavior is a bug, please provide the steps to reproduce.**
I have created a demo project to reproduce the issue here: https://github.com/ItsOnlyBinary/webpack-issue

please see the README.md for how to start the demo

**What is the expected behavior?**
Webpack should be able to detect its relative url for the shared chunks within the web workers so they are loaded from the correct url.

**Other relevant information:**
webpack version:  5.44.0
Node.js version: v12.16.3
Operating System: Windows
Additional tools:

**Comment by alexander-akait** [comment]
You have wrong `publicPath` due local server, please use ` publicPath: 'auto',`, empty `publicPath` is invalid in most of cases, we strongly recommend to use `auto` value if you need relative URLs

**Comment by qingwufong** [comment]
@alexander-akait we have same problem, when use `publicPath: './'`. we have been troubled by this problem for a long time.

**Comment by alexander-akait** [comment]
@qingwufong What is webpack version?

**Comment by qingwufong** [comment]
> @qingwufong What is webpack version?

webpack@5.31.0 ,   It seems that upgrading to the latest version of webpack is still not working，is need set the HtmlWebpackPlugin and  plublicPath , and how？

**Comment by qingwufong** [comment]
> @qingwufong What is webpack version?

webpack@5.31.0 ,   It seems that upgrading to the latest version of webpack is still not working，is need set the HtmlWebpackPlugin and  plublicPath , and how？

**Comment by alexander-akait** [comment]
Please provide example how we can reproduce, I think you have `publicPath` option for `HtmlWebpackPlugin`

**Comment by qingwufong** [comment]
> Please provide example how we can reproduce, I think you have `publicPath` option for `HtmlWebpackPlugin`
We found that the version of webpack after 5.31 have this problem, but 5.22 is OK.
and reproduce the issue here: https://github.com/qingwufong/webpack-issue

**Comment by qingwufong** [comment]
> Please provide example how we can reproduce, I think you have `publicPath` option for `HtmlWebpackPlugin`

We found that the version of webpack after 5.31 have this problem, but 5.22 is OK.
and reproduce the issue here: https://github.com/qingwufong/webpack-issue

**Comment by alexander-akait** [comment]
You have wrong `publicPath`, please use `publicPath: 'auto',` (I strongly recommend to use, also you will have relative URLs), why it happens, because we use `importScripts`, in `dist/static/js/worker-1.js` (in other worker too), so you have `importScripts("./static/js/vendors-node_modules_lodash_lodash_js.js")`, and you have `./static/js/static/js/vendors-node_modules_lodash_lodash_js.js`
