### ISSUE TITLE
Module Federation runtime-dynamic share scope

### ISSUE THREAD

**Issue by jacobp100** [webpack/webpack#13800]
## Feature request

We're trying to have a very strict setup, where all versions of MFEs get the exact versions of packages they were tested with locally. We're having a few hiccups with peer dependencies - mainly react UI libraries where react is marked as a peer dependency. Two MFEs could have the same version of a react UI library, but different versions of react.

For now, we've got a share scope with a convention to use the name and version of singleton package (i.e. `shareScope: "react@17.0.1"` - as below). However, this won't scale well past more than one singleton package.

I've noticed the code outputs this for container initialization:-

```js
var init = (shareScope, initScope) => {
	if (!__webpack_require__.S) return;
	var oldScope = __webpack_require__.S["react@17.0.1"];
	var name = "react@17.0.1"
	if(oldScope && oldScope !== shareScope) throw new Error("Container initialization failed as it has already been initialized with a different share scope");
	__webpack_require__.S[name] = shareScope;
	return __webpack_require__.I(name, initScope);
};
```

If we changed this to:-

```diff
- var init = (shareScope, initScope) => {
+ var init = (shareScope, initScope, name) => {
+	if (!name) name = "react@17.0.1"
	if (!__webpack_require__.S) return;
-	var oldScope = __webpack_require__.S["react@17.0.1"];
+	var oldScope = __webpack_require__.S[name];
-	var name = "react@17.0.1"
	if(oldScope && oldScope !== shareScope) throw new Error("Container initialization failed as it has already been initialized with a different share scope");
	__webpack_require__.S[name] = shareScope;
	return __webpack_require__.I(name, initScope);
};
```

Then I think we have most of what we need to support this - with this pseudo-code,

```js
const webpackScopes = [];

const loadMFE = async (name, singletonPackages) => {
  let scope = webpackScopes.find((scope) => {
    return singletonPackagesAreCompatible(
      singletonPackages,
      scope.singletonPackages
    );
  });

  if (!scope) {
    scope = { name, singletonPackages };
    await __webpack_init_sharing__(scope.name);
    webpackScopes.push(scope);
  } else {
    updateScopeWithNewSingletonPackages(scope, singletonPackages);
  }

  const container = await loadMFERemoteEntry(name);

  // @ts-expect-error Webpack internals
  await container.init(__webpack_share_scopes__[scope.name], undefined, scope.name);

  const initModule = await container.get(".");

  return initModule();
};
```

**What is the expected behavior?**

nil

**What is motivation or use case for adding/changing the behavior?**

Dynamic scope generation

**How should this be implemented in your opinion?**

Detailed in description

**Are you willing to work on this yourself?**

yes

**Comment by alexander-akait** [comment]
Because it is expected, and should not be used in this way?

**Comment by jacobp100** [comment]
@alexander-akait What's wrong with the approach set out? I don't think we'll be the only ones that want to dynamically create share scopes at runtime

**Comment by alexander-akait** [comment]
two reacts with different versions?

**Comment by jacobp100** [comment]
Yeah, it is possible for our use case. Each MFE gets one HTML element - and can use whatever framework it wants to on that element. So each MFE using React basically does `ReactDOM.render(<MFE />, element)`.

The MFEs server render too, so we need to make sure that if they're using react, they'll hydrate the MFE with the same version of react on the server.

Did the description in the initial post make sense for the issue we're having regarding peer dependencies?

**Comment by alexander-akait** [comment]
We stringy recommend don't do it, there are a lot of side effect which will break your app

**Comment by jacobp100** [comment]
I did find another reason this might be necessary - you could have the following setup,

```js
new ModuleFederationPlugin({
  shared: {
    'normal-package': { scopeName: 'default' },
    'package-a': { scopeName: 'a' },
    'package-b': { scopeName: 'b' }
  },
  shareScope: 'default'
})
```

This can be necessary for peer dependencies.

However, there's no way to initialise sharing for both `package-a` and `package-b` - so you could end up with extra network requests. If either of those packages rely on being singletons - like event busses - you'll also get correctness issues.

With this suggestion, you'd be able to do,

```js
await Promise.all([
  __webpack_init_sharing__('default'),
  __webpack_init_sharing__('a'),
  __webpack_init_sharing__('b')
])

const container = window['example-package'];

const initScope = [];
await Promise.all([
  container.init(__webpack_share_scopes__['default'], initScope, 'default'),
  container.init(__webpack_share_scopes__['a'], initScope, 'a'),
  container.init(__webpack_share_scopes__['b'], initScope, 'b')
])
```

This seems to be the only way to have these scoped packages avoid extra network requests.

**Comment by jacobp100** [comment]
Possibly one way we could make this API nicer is doing the following,

```js
// ...
var init = (shareScope, initScope) => {
	return initSharing("react@17.0.1", shareScope, initScope);
};

var initSharing = (name, shareScope, initScope) => {
	if (!__webpack_require__.S) return;
	var oldScope = __webpack_require__.S[name];
	if(oldScope && oldScope !== shareScope) throw new Error("Container initialization failed as it has already been initialized with a different share scope");
	__webpack_require__.S[name] = shareScope;
	return __webpack_require__.I(name, initScope);
}

// This exports getters to disallow modifications
__webpack_require__.d(exports, {
	get: () => (get),
	init: () => (init),
	initSharing: () => (initSharing)
});
```

**Comment by alexander-akait** [comment]
still can break, better solve it on own side

**Comment by jacobp100** [comment]
Out of interest, what do you expect could break? (Assuming the user is using the API correctly)

**Comment by jacobp100** [comment]
Closing in favour of #13834 (listed as bug report rather than feature request)
