### ISSUE TITLE
webpack 5.45.0 doesn't work with jQuery

### ISSUE THREAD

**Issue by yura3d** [webpack/webpack#13817]
# Bug report

**What is the current behavior?**
webpack 5.45.0 (latest) doesn't work with jQuery 3.6.0 (latest):
```
ERROR in ./node_modules/jquery/dist/jquery.js 936:9
Module parse failed: Unexpected token (936:9)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|  * @param {Function} fn Passed the created element and returns a boolean result
|  */
> function assert( fn ) {
|       var el = document.createElement( "fieldset" );
|
 @ ./assets/js/index.js 1:0-23 65:21-22 73:23-24

webpack 5.45.0 compiled with 1 error in 3015 ms
```

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Install `webpack`, `webpack-cli` and `jquery`.
2. Create 1 entrypoint which should be a file that imports jQuery.
3. Run webpack in production mode.

**What is the expected behavior?**
Successful compilation (downgrade only the `webpack` package to 5.44.0 solves the problem).

**Other relevant information:**
webpack version:  5.45.0
Node.js version: 16.5.0
Operating System: Debian GNU/Linux 10.10 x64
Additional tools: -

**Comment by alexander-akait** [comment]
Duplicate https://github.com/webpack/webpack/issues/13814, please use search before post

**Comment by elpollouk** [comment]
The node.js [buffer](https://github.com/feross/buffer) modue also has a similar issue matching on asser.

```
ERROR in ./node_modules/buffer/index.js 184:9
Module parse failed: Unexpected token (184:9)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| Object.setPrototypeOf(Buffer, Uint8Array)
| 
> function assertSize (size) {
|   if (typeof size !== 'number') {
|     throw new TypeError('"size" argument must be of type number')
```

An example of a failed build with this issue can be found here:
https://github.com/elpollouk/Itokawa/pull/195/checks?check_run_id=3089083712
