### ISSUE TITLE
Parse `jest.*` methods in similar manner to commonjs `require` calls.

### ISSUE THREAD

**Issue by richardscarrott** [webpack/webpack#1382]
I'm working on integrating Webpack with Jest by extending (and hopefully replacing) [Jest's `HasteModuleLoader`](https://github.com/facebook/jest/blob/master/src/HasteModuleLoader/HasteModuleLoader.js) for a Webpack alternative.

I've got 90% of Jest's features working (everything but manual \_\_mocks\_\_) but still need to write a Webpack plugin to piece it together by transforming Jest api calls, e.g.

```
jest.dontMock('./foo.js'); => jest.dontMock(1);
jest.mock('./foo.js'); => jest.mock(1);
jest.genMockFromModule('./foo.js'); => jest.genMockFromModule(1);
jest.setMock('./foo.js'); => jest.setMock(1);
```
I had hoped this would be easy enough to achieve as it's almost identical to standard commonjs `require` calls however I've been unable to work out the best approach, do you have any pointers?

**Comment by sokra** [comment]
A simple webpack plugin could solve this. Maybe something similar to:

``` js
plugins: [function() {
  function resolveArgument(expr) {
    if(expr.arguments.length !== 1) return;
    return this.applyPluginsBailResult("call require:commonjs:item", expr, this.evaluateExpression(expr.arguments[0]));
  }
  this.parser.plugin("call jest.dontMock", resolveArgument);
  this.parser.plugin("call jest.mock", resolveArgument);
  // ...
}]
```

**Comment by richardscarrott** [comment]
Amazing, thanks for the help!
