### ISSUE TITLE
Sealing hashing takes forever when hot: true

### ISSUE THREAD

**Issue by dispalt** [webpack/webpack#13825]
# Bug report

Performance for hot: true seems to be pretty bad, taking a 12s compile to a 110s compile.  And it seems to be completely dependent on a slowing hashing function from `webpack-sources`.  It only appears when you have lots of small files, like 3k+.  Here's the last status update by the progress flag:

` [webpack.Progress] 65% building 4/4 entries 26696/26696 dependencies 6288/6288 modules`

It seems to be thrashing memory-wise, as you can see by the second image it's spending 37s in GC.

**What is the current behavior?**

It seems when there is a lot of files, webpack exponentially slowes down.

Since this project is scala.js I can generate javascript files two different ways
1) With lots of small files
2) With fewest files.

So for the first one, here is a chart:
![image](https://user-images.githubusercontent.com/46037/126198967-8681f0c4-355a-4ed1-aa9e-546cff3de147.png)
And the bottoms up view (Heavy methods)
![image](https://user-images.githubusercontent.com/46037/126201460-02aff9d5-8e8a-4c1a-97b3-cd1160ab936f.png)

And for the second one here is another chart, which looks normal.
![image](https://user-images.githubusercontent.com/46037/126199052-9cfc9fd4-d612-4124-adc0-5a4c5a218e78.png)

Practically this is the same code just organized differently.

**If the current behavior is a bug, please provide the steps to reproduce.**

I'll try to find a way to give some code where it's reproducible, but I have something like 3195 files just in my project not including dependencies in the first option. And 30 files with the second one.

**What is the expected behavior?**

Have linear performance with regard to the number of files processed by webpack.

**Other relevant information:**
webpack version:  5.45.1
Node.js version:  v14.17.0
Operating System: Linux
Additional tools:

**Comment by alexander-akait** [comment]
> If the current behavior is a bug, please provide the steps to reproduce.

Please do it, otherwise we can't help, I think something wrong in non official webpack plugin, no problems in our tests

**Comment by sokra** [comment]
Interesting profile. Do you have the cpuprofile for the first one?

**Comment by dispalt** [comment]
I have no plugins enabled, and just css loader and asset module.  There are just a ton of files and modules in this project.

> Interesting profile. Do you have the cpuprofile for the first one?

I could get one real quick. brb.

**Comment by dispalt** [comment]
[issue 13825 - v1.zip](https://github.com/webpack/webpack/files/6843140/issue.13825.-.v1.zip)

Here's a similar run with the same characteristics. @sokra

**Comment by sokra** [comment]
Thanks that was very useful. I'll see tomorrow if that can be fixed.

**Comment by dispalt** [comment]
And, just confirmed it is totally fixed, wow, thank you @sokra!
