### ISSUE TITLE
Unable to initialise federated module sharing with multiple shareScopes

### ISSUE THREAD

**Issue by jacobp100** [webpack/webpack#13834]
# Bug report

**What is the current behavior?**

When using ModuleFederationPackage, the `shared` option allows specifying different `scopeName`s for each package. It is not possible to initialise sharing via (`container.init(...)`) for any but the default scope.

**If the current behavior is a bug, please provide the steps to reproduce.**

Make an example package with a set up similar to,

```js
new ModuleFederationPlugin({
  shared: {
    'normal-package': { scopeName: 'default' },
    'package-a': { scopeName: 'a' },
    'package-b': { scopeName: 'b' }
  },
  shareScope: 'default'
})
```

Initialise default sharing with,

```js
await Promise.all([
  __webpack_init_sharing__('default'),
  __webpack_init_sharing__('a'),
  __webpack_init_sharing__('b')
])

const container = window['example-package'];

await container.init(__webpack_share_scopes__['default']);
```

It is not possible initialise sharing in the example package for the scopes 'a', and 'b'.

**What is the expected behavior?**

It should be possible to initialise sharing for 'a' and 'b'

The current initialisation code hardcodes the scope name, even though there may be more than one.

```js
var init = (shareScope, initScope) => {
	if (!__webpack_require__.S) return;
	var oldScope = __webpack_require__.S["default"];
	var name = "default"
	if(oldScope && oldScope !== shareScope) throw new Error("Container initialization failed as it has already been initialized with a different share scope");
	__webpack_require__.S[name] = shareScope;
	return __webpack_require__.I(name, initScope);
};
```

If we changed this container code (keeping API compatibility) to the following,

```js
var init = (shareScope, initScope) => {
	return initSharing("default", shareScope, initScope);
};

var initSharing = (name, shareScope, initScope) => {
	if (!__webpack_require__.S) return;
	var oldScope = __webpack_require__.S[name];
	if(oldScope && oldScope !== shareScope) throw new Error("Container initialization failed as it has already been initialized with a different share scope");
	__webpack_require__.S[name] = shareScope;
	return __webpack_require__.I(name, initScope);
}

// This exports getters to disallow modifications
__webpack_require__.d(exports, {
	get: () => (get),
	init: () => (init),
	initSharing: () => (initSharing)
});
```

We could then initialise sharing for the other scopes via,

```js
// ...
await Promise.all([
  await container.initSharing('default', __webpack_share_scopes__['default']),
  await container.initSharing('a', __webpack_share_scopes__['a']),
  await container.initSharing('b', __webpack_share_scopes__['b']),
])
```

See #13800

**Other relevant information:**
webpack version: 5.44.0
Node.js version: v14.15.1
Operating System: macOS Big Sur
Additional tools: nil

**Comment by alexander-akait** [comment]
No bugs here, wrong template for the issue

**Comment by jacobp100** [comment]
Example repo:- https://github.com/jacobp100/webpack-13834

Would you accept the fix I've proposed?

**Comment by sokra** [comment]
What's the use case for that?

**Comment by jacobp100** [comment]
Our MFE implementation supports having multiple versions of React running. It's not recommended, but we support it so if one MFE updates from React 17 to 18, they don't need to wait for others - the page will be less performant, but won't be functionally broken.

The big issue we've had is peer dependencies. We could have the same version of a UI library in two MFEs, which use two different versions of React.

We support this by putting React and any packages that peer dependency React into a `React@17` or `React@18` scope.

We don't want to put every module in  this scope, however. Things like event busses cannot exist multiple times, or the events won't be dispatched correctly. These have to exist under the `default` scope.

Without adding this, we either initialise our `React@<version>` scope, or our `default` scope - but not both. This can mean extra downloads of packages (like downloading the exact same version of React multiple times), or our event busses being broken.

**Comment by alexander-akait** [comment]
> We don't want to put every module in this scope, however. Things like event busses cannot exist multiple times, or the events won't be dispatched correctly. These have to exist under the default scope.

You really break an app due two version of react... somebody will forget about it and then we have a problem in bug tacker...

**Comment by sokra** [comment]
@jacobp100 I think you can put react 17 and 18 in the default scope and put the package with peer dependency on react under a different key into the share scope.

Assuming a `react-lib` uses `react`.

``` js
// react 17 app which uses "react-lib"
shared: ["react", {
  "react-lib": {
    shareKey: "react-lib for react@17"
  }
}]
// react 18 app which uses "react-lib"
shared: ["react", {
  "react-lib": {
    shareKey: "react-lib for react@18"
  }
}]
```

**Comment by jacobp100** [comment]
@sokra Thanks - that works surprisingly well! I'll assume you don't need the PR any more - but I'm happy to continue with it if you do need it (for other reasons etc.)

**Comment by DevHunvee3** [comment]
@jacobp100 Hi, I know it's been more that 1.5 years since this thread, but I needed to ask how did you mange to allow both versions of React (17 and 18) to run simultaneously?

**Comment by fcano-ut** [comment]
I mentioned this issue in another issue, hoping someone can bring some light into how to set this up. Sorry for the spammy comment but I think this is relevant for both issues,so I'll quote the comment here to give it more reach:

> Has anyone figured out what are the settings that allow you to load multiple versions of React with Dynamic Remote Containers?
> 
> I was following this example: https://github.com/module-federation/module-federation-examples/tree/master/different-react-versions-16-18; but I couldn't make it work, since it is relying on registering the different react versions as singletons, under different shareScopes. I think this doesn't work with dynamic federation due to this bug: [webpack/webpack#13834](https://github.com/webpack/webpack/issues/13834)
> 
> As suggested in the other issue I mentioned, I currently have these settings:
> 
> ```js
> react: {
>   eager: type === 'host', // eager for host, not eager for micro-frontends
>   requiredVersion: dependencies.react,
> },
> 'react-dom': {
>   eager: type === 'host',
>   requiredVersion: dependencies['react-dom'],
> },
> // customize the share key of
> // any dependency that has react as peerDependency
> // workaround to: https://github.com/webpack/webpack/issues/13834
> 'react-lib': {
>   eager: type === 'host',
>   requiredVersion: dependencies['react-lib'],
>   shareKey: `react-lib for react@17`,
> },
> ```
> 
> However, this is failing with dynamic federation about 30% of the times. It fails without errors, the bug is due to a promise that is never solved:
> 
> ```js
>     if (!(this._config.remoteName in window)) {
>       const fetchedContainer: any = await this.fetchRemote();
>       await fetchedContainer.init(__webpack_share_scopes__['default']);
>     }
> 
>     const container: any = window[this._config.remoteName as any];
>     const factory = await container.get(moduleName); // ❌ Sometimes this promise hangs forever
>     const Module = factory();
> ```
> 
> As suggested in this issue, I also tried these settings, but it's failing in the same place for the same reason:
> 
> ```js
> react: {
>   eager: type === 'host', // eager for host, not eager for micro-frontends
>   requiredVersion: dependencies.react,
>   shareKey: 'react@17', // or "react@18"
>   shareScope: 'react@17',
>   singleton: true,
> },
> 'react-dom': {
>   eager: type === 'host',
>   requiredVersion: dependencies['react-dom'],
>   shareKey: 'react-dom@17',
>   shareScope: 'react@17',
>   singleton: true,
> },
> // customize the share key of
> // any dependency that has react as peerDependency
> // workaround to: https://github.com/webpack/webpack/issues/13834
> 'react-lib': {
>   eager: type === 'host',
>   requiredVersion: dependencies['react-lib'],
>   shareKey: `react-lib for react@17`,
> },
> ```
> 
> I'm confused, since the only example of two react versions that seems to be working relies on multiple share scopes, but there is an issue with that feature and dynamic remote containers.
> 
> If someone has any information, I'd be super grateful to hear it. I've spent three days trying different stuff to try and figure this out, but I haven't discovered something that works reliably yet.
