### ISSUE TITLE
Weird code generated in bundle.js

### ISSUE THREAD

**Issue by Queuecumber** [webpack/webpack#1383]
I have some code that I am deploying using webpack. The generated bundle.js needs to be edited by hand to function correctly because it generates some weird code. The original code is 

```
    if(viewmodelPaths.length > 0)
    {
        // Dynamically load missing viewmodels
        require(viewmodelPaths, (function ()
        {
            for(var i = 0; i < arguments.length; i++)
            {
                this.components()[viewmodelIdx[i]].viewModel = arguments[i];
            }

            callback();
        }).bind(this));
    }
    else
    {
        callback();
    }
```

The generated code is 

```
if(viewmodelPaths.length > 0)
        {
            // Dynamically load missing viewmodels
            __webpack_require__(10)!/* require */(/* empty */function() { var __WEBPACK_AMD_REQUIRE_ARRAY__ = viewmodelPaths; ((function ()
            {
                for(var i = 0; i < arguments.length; i++)
                {
                    this.components()[viewmodelIdx[i]].viewModel = arguments[i];
                }

                callback();
            }).bind(this).apply(null, __WEBPACK_AMD_REQUIRE_ARRAY__));}());
        }
        else
        {
            callback();
        }
```

The issue is the 3rd line: `_webpack_require__(10)!/* require */(`... the `!` should no be there, and deleting it makes everything work as expected. 

Why is webpack generating this code and is it a bug on your end or should I change something to make things work better?

**Comment by SpaceK33z** [comment]
Have you tried using `require.ensure` instead of `require`?

**Comment by Queuecumber** [comment]
I haven't, but this is a third party library that we would like not to modify. It was written for requirejs AMD.
