### ISSUE TITLE
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by patelanand553** [webpack/webpack#13848]
well,
i freshly installed nextjs using `yarn create next-app`
after that i install chakra-ui's packages and start using it.
after few minutes it's starts show in console.

`
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: TypeError: Cannot read property 'length' of undefined
wait  - compiling...
event - compiled successfully
wait  - compiling...
event - compiled successfully
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: TypeError: Cannot read property 'length' of undefined
wait  - compiling...
event - compiled successfully
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: TypeError: Cannot read property 'length' of undefined
wait  - compiling...
event - compiled successfully
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: TypeError: Cannot read property 'length' of undefined
wait  - compiling...
event - compiled successfully
wait  - compiling...
event - compiled successfully
wait  - compiling...
event - compiled successfully
wait  - compiling...
event - compiled successfully
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: TypeError: Cannot read property 'length' of undefined`

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

**Comment by alexander-akait** [comment]
Please respect time of other devleopers
