### ISSUE TITLE
No code / way to identify "Cannot find module" error for requires with expressions

### ISSUE THREAD

**Issue by matthewoates** [webpack/webpack#1384]
When the webpack require fails we don't specify an error code in some cases.

```
var foo = 'bogus';
try {
    require('./' + foo);
} catch (e) {
    console.log('e.code:', e.code);
    console.log('e instancesof Error:', e instanceof Error);
    console.log('Object.keys(e):', Object.keys(e));
}
```

result:

```
 ➤ node out.js 
e.code: undefined
e instancesof Error: true
Object.keys(e): []
```

While the require with string literals produces the error as expected:

```
try {
    require('./bogus');
} catch (e) {
    console.log('e.code:', e.code);
    console.log('e instancesof Error:', e instanceof Error);
    console.log('Object.keys(e):', Object.keys(e));
}
```

```
 ➤ node out.js 
e.code: MODULE_NOT_FOUND
e instancesof Error: true
Object.keys(e): [ 'code' ]
```

Here's the webpack.config.json for the above code:

```
module.exports = {
  entry: './test.js',
  output: {
    path: __dirname,
    filename: 'out.js',
  }
};
```

I suggest we stick with the behavior of node.js/io.js.

```
> try { require('bogus'); } catch (e) { console.log(e.code) }
MODULE_NOT_FOUND
```

Use case: I'm making a toy app to familiarize myself with webpack, flow, and a few other technologies. This repo contains solutions to Project Euler problems. Each solution is in its own file, and I'm not going to have files for the ~500 problems from day one, (or likely ever) so some kind of runtime check of module availability seems necessary. I found this (https://github.com/webpack/webpack/issues/526) but I'm not trying to write any webpack-specific code.

**Comment by sokra** [comment]
You can send a PR.
