### ISSUE TITLE
Tree-shaken code shared between multiple remotes in same app broken in production mode

### ISSUE THREAD

**Issue by BakoviDagi** [webpack/webpack#13843]
# Bug report

**What is the current behavior?**
When an app exposes multiple remote entrypoints, it looks like they use the same ID for modules, and so if that code is tree-shaken, then there is a race condition where if an entrypoint imports a module, but doesn't use it until after another entrypoint imports that module, the initial import is overridden and there can be missing functions.

**If the current behavior is a bug, please provide the steps to reproduce.**
https://github.com/BakoviDagi/webpack-federation-bug

I'm not sure why, but this example is strangely dependent on the lodash import in _createElement. Perhaps because this forces there to be a split chunk?

I had it sporadically breaking with `concatenateModules` and `minimize` set to true, but for easier debugging I set them to false and can't seem to get it to happen with them true anymore. In my actual code, it breaks in both cases.

If you switch mode to "development" then everything works fine

**What is the expected behavior?**
Production mode should work just like development mode does. There should be no errors when loading the page.

**Other relevant information:**
webpack version:  5.46.0
Node.js version: v14.16.0
Operating System: Windows 10/Linux
Additional tools:

**Comment by alexander-akait** [comment]
Change name `webpack-federation-bug` on other for `RemoteApp`

**Comment by alexander-akait** [comment]
Did it help?

**Comment by BakoviDagi** [comment]
nope

**Comment by tommypepsi** [comment]
I think we're having the same issue with our webpack config. Everything works in development but the production build gets an error (```t[e] is undefined```) with one of our dynamic imports. Something seems to be missing from our build. 

Strange thing is that it seems to be working on node 13 but not on node 14 and higher. We tried with node 12, 13, 14 and 16 and only 12 and 13 is working correctly.

**Comment by BakoviDagi** [comment]
This is still happening

**Comment by alexander-akait** [comment]
Expected, press F5 multiple times and you will see racing, sometimes it even works, also you can look at `Network` panel and see the same. You can share `dom` package between them, look at generated bundles, you have multiple copies of `lodash`

**Comment by semiaddict** [comment]
> Everything works in development but the production build gets an error (`t[e] is undefined`) with one of our dynamic imports. Something seems to be missing from our build.

@tommypepsi, did you ever figure out the source of your issue?
I am getting the same type of errors randomly on production builds.
I believe my issue is different from the one described in the original post, but what you wrote sounds closer to my issue (see #16343), for which I'm still trying to find a solution.
