### ISSUE TITLE
Same module imported via `import` and `import -> require` points to different code

### ISSUE THREAD

**Issue by oleg-slapdash** [webpack/webpack#13853]
# Bug report

**What is the current behavior?**

When the same library from the same location is imported via commonjs `require` and es6 `import` results in two different instances for classes and duplicate code in the bundle. 

**If the current behavior is a bug, please provide the steps to reproduce.**

If an app imports a class directly and then uses a commonjs-based 3rd party library that uses the same library it results having duplicate code in the bundle and `instancesof` does not work properly. The real issue happens with `superstruct` package, however, see the demo below with boiled down-version.

Visualization:
```
["app" - es6 / `import`] -> [library] -> index.es.js -> class CustomError {}
         |
[3rd party module - commonjs / `require`] -> [library] -> index.cjs -> class CustomError {}
```
Repro: https://github.com/oleg-slapdash/webpack-issue-commonjs-es6-deduplication
```bash
git clone https://github.com/oleg-slapdash/webpack-issue-commonjs-es6-deduplication
cd webpack-issue-commonjs-es6-deduplication/
cd app
yarn
yarn webpack
yarn node dist/main.js

Output:
localError.source() ===  index.es.js
thirdPartyError.source() ===  index.cjs
localError instanceof CustomError === true
thirdPartyError instanceof CustomError ===  false
```

**What is the expected behavior?**

Webpack should be able to de-duplicate commonjs and es6 imports of the same library. The bundle should contain only one implementation of the library and instances should be able to be checked via `instanceof`.

**Other relevant information:**
webpack version: ^5.46.0
Node.js version: v15.1.0
Operating System: Mac OS 10.15.7
Additional tools: N/A

**Comment by alexander-akait** [comment]
expected, resolution using `require` and `import` are different due https://github.com/oleg-slapdash/webpack-issue-commonjs-es6-deduplication/blob/main/library/package.json#L7, Node.js works same
