### ISSUE TITLE
Error: url.replace is not a function

### ISSUE THREAD

**Issue by olegKusov** [webpack/webpack#13851]
# Bug report

yarn start and getting error . Same error with css plugin, So I think if this error happens not just in html webpack plugin then it can be related to Webpack

https://github.com/webpack-contrib/mini-css-extract-plugin/issues/793

**What is the current behavior?**

![image](https://user-images.githubusercontent.com/28058268/126774387-d73133e5-3a33-41f9-9f19-328d536297ff.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

1. yarn start
2. wait for build

**What is the expected behavior?**

No error

**Other relevant information:**
webpack version:  "5.46.0"
html-webpack-plugin: "5.3.2",
Node.js version: 14.17.1
Operating System: windows 11 wsl 2

**Comment by alexander-akait** [comment]
Please open an issue in `html-webpack-plugin`

**Comment by olegKusov** [comment]
> html-webpack-plugin

is it html-webpack-plugin related issue?

**Comment by alexander-akait** [comment]
I have reproducible test repo, give me time to investigate

**Comment by olegKusov** [comment]
> I have reproducible test repo, give me time to investigate

my mistace. I used relative path in link to favicon inside html template. sorry

**Comment by alexander-akait** [comment]
@olegKusov Can you clarify?

**Comment by olegKusov** [comment]
> @olegKusov Can you clarify?

![image](https://user-images.githubusercontent.com/28058268/126778923-f54b9df9-a27a-4751-942a-0750af4d2d17.png)
commented this thing and it works.

**Comment by alexander-akait** [comment]
hm, should work, what is `context`?

**Comment by olegKusov** [comment]
> hm, should work, what is `context`?

context?

**Comment by alexander-akait** [comment]
https://webpack.js.org/configuration/entry-context/#context

**Comment by olegKusov** [comment]
> https://webpack.js.org/configuration/entry-context/#context

I don't have it in config

**Comment by alexander-akait** [comment]
Maybe you can provide reproducible test repo too? Because it should be work

**Comment by olegKusov** [comment]
> Maybe you can provide reproducible test repo too? Because it should be work

Ok! Give me some time!

**Comment by olegKusov** [comment]
> Maybe you can provide reproducible test repo too? Because it should be work

https://github.com/olegKusov/reproduce-err

I found in my config html-loader. I don't remember why it's there but with it it throws this error but without it it's ok

**Comment by alexander-akait** [comment]
Problem here:
```
{
    test: /\.svg$/,
    use: ['@svgr/webpack', 'url-loader'],
    type: 'javascript/auto',
  },
```

you need to use:
```
{
    test: /\.svg$/,
    exclude: /favicon\.svg$/,
    use: ['@svgr/webpack', 'url-loader'],
    type: 'javascript/auto',
  },
```

otherwise `../src/assets/icons/favicon.svg` generate svgr output i.e. URL and react component, but it can be used inside HTML file
