### ISSUE TITLE
ESM output: const a = (class extends A {…} ⇒ class a extends A {…}

### ISSUE THREAD

**Issue by dilyanpalauzov** [webpack/webpack#13856]
## Feature request

As far as I can see, when the input contains:
```javascript
export default class extends A {...}
```
and the output is ES6 concatenated modules:
```javascript
export default {
    optimization: {
        concatenateModules: true
    },
    experiments: {
        outputModule: true
    },
    output: {
        library: {
            type: 'module'
        },
        filename: 'abc.js',
        publicPath: '/dist'
    }
}
```
the output contains:
```javascript
/* harmony default export */ const a = (class extends A {…}
```
The output should be simpler:
```javascript
class a extends A {…}
```

**What is motivation or use case for adding/changing the behavior?**
More compact output.

**Are you willing to work on this yourself?**
No

webpack 5.46.0

**Comment by alexander-akait** [comment]
Expected, use `mode: "production"` to avoid this

**Comment by dilyanpalauzov** [comment]
If I set `mode: 'production', optimization: {minimize: 'false'}`, the code differs from `mode: 'development'` by:
```diff
@@ -26,12 +26,28 @@
 /******/       __webpack_require__.o = (obj, prop) => (Object.prototype.hasOwnProperty.call(obj, prop))
 /******/ })();
 /******/ 
+/******/ /* webpack/runtime/make namespace object */
+/******/ (() => {
+/******/       // define __esModule on exports
+/******/       __webpack_require__.r = (exports) => {
+/******/               if(typeof Symbol !== 'undefined' && Symbol.toStringTag) {
+/******/                       Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
+/******/               }
+/******/               Object.defineProperty(exports, '__esModule', { value: true });
+/******/       };
+/******/ })();
+/******/ 
 /************************************************************************/
 var __webpack_exports__ = {};
+/*!***********************************!*\
+  !*** ./src/index.js + 41 modules ***!
+  \***********************************/
+// ESM COMPAT FLAG
+__webpack_require__.r(__webpack_exports__);
 
 // EXPORTS
 __webpack_require__.d(__webpack_exports__, {
-  "Z": () => (/* binding */ src)
+  "default": () => (/* binding */ src)
 });
 
 ;// CONCATENATED MODULE: ./src/js/common/code-snippet.js
@@ -8325,6 +8341,9 @@
 
 /* harmony default export */ const calendar = (Calendar);
 
+;// CONCATENATED MODULE: ./src/css/main.styl
+// extracted by mini-css-extract-plugin
+
 ;// CONCATENATED MODULE: ./src/index.js
 /**
  * @fileoverview The entry file of fullcalendar
@@ -8336,5 +8355,5 @@
 
 /* harmony default export */ const src = (calendar);
 
-var __webpack_exports__default = __webpack_exports__.Z;
+var __webpack_exports__default = __webpack_exports__.default;
 export { __webpack_exports__default as default };
```
The + lines are skipped in the production code.

Why is it fine not to have these lines in production code, but the lines (the ESM compat flag call) is necessary in development code?

Moreover, the `extend class` from the subject is not rewritten by webpack, it is rewritten by terser sometimes.  But the rewriting does not abolish the const, it only renames the long names to shorter terms.

**Comment by dilyanpalauzov** [comment]
`mode: "production"` does not avoid this.

**Comment by dilyanpalauzov** [comment]
I was wrong.  When the input in `x.js` is `export default class extends A`, the output is `const x = (class extends A) {…}`.

When the input in `y.js` is
```javascript
class Y extends A {…}
export default Y
```
the output is:
```javascript
class Y extends A {…}
const y = (Y);
```
In both cases there shall be no assignment, but just `class x extneds A` or `class y extends A` output.

The brackets on the last statement are not necessary.

**Comment by dilyanpalauzov** [comment]
Can this be reopened?

**Comment by alexander-akait** [comment]
Sorry, no, because it is expected, it is protection

**Comment by dilyanpalauzov** [comment]
How does the output of `const x = (class {...})` versus just `class x {...}` offer protection?

The output is suboptimal.  I do not need the protection, but prefer to have optimal output.

**Comment by alexander-akait** [comment]
You can run `prettier` if you need beautiful output, webpack was not design for beautiful output, it protects when we concatenated modules, because after `const a` you can have any code

**Comment by dilyanpalauzov** [comment]
The identifier for `const x =` is chosen by webpack and webpack has to ensure that it is unique.  it does not matter what follows, since webpack has to ensure that this identifier is unique and the rest of the code does not change it.

**Comment by dilyanpalauzov** [comment]
>  and the rest of the code does not change it.

even if it is not `const`.

**Comment by vankop** [comment]
> webpack has to ensure that this identifier

webpack does this. btw this is the same for `class a extends A {}` a should be unique

**Comment by dilyanpalauzov** [comment]
If the identifier after `const` is unique, then it is not changed afterwards.  Then `const a12=(class {...})` can be written shorter as `class a12 {...}` and there is no need for protection.  Here `a12` is the uniique identifier chosen by webpack.
