### ISSUE TITLE
Webpack fails with function parameter 'private' in ES5 script

### ISSUE THREAD

**Issue by Bikeman868** [webpack/webpack#13859]
# Bug report

**What is the current behavior?**
If I am packaging plain ES5 javascript with no transpilation, and I define a function that takes an argument called 'private' then webpack fails in production mode but succeeds in development mode.

**If the current behavior is a bug, please provide the steps to reproduce.**

Add a source file similar to:
```javascript
const myMixin = function(private, public) {
  private.something = "some value";
}
``` 
My webpack.config.js is pretty simple:
```javascript
const path = require('path');

var env = process.env.NODE_ENV || "development";

module.exports = {
  mode: env,
  entry: './src/index.js',
  output: {
    filename: 'frag.min.js',
    path: path.resolve(__dirname, env === 'development' ? 'samples' : 'dist')
  },
  devtool: env === 'development' ? false : 'source-map', 
  watchOptions: {
    ignored: '**/node_modules'
  }
};
```

I invoke webpack with 
```bash
NODE_ENV=production npx webpack
```
The output I get is:
```bash
ERROR in frag.min.js from Terser
Unexpected token: name (private) [webpack://./src/Cameras/cameraMixin.js:1,0][frag.min.js:1018,43]
    at js_error (./node_modules/terser/dist/bundle.min.js:550:11)
    at croak (./node_modules/terser/dist/bundle.min.js:1274:9)
    at token_error (./node_modules/terser/dist/bundle.min.js:1282:9)
    at unexpected (./node_modules/terser/dist/bundle.min.js:1288:9)
    at Object.add_parameter (./node_modules/terser/dist/bundle.min.js:1766:33)
    at binding_element (./node_modules/terser/dist/bundle.min.js:2023:29)
    at parameter (./node_modules/terser/dist/bundle.min.js:1830:17)
    at parameters (./node_modules/terser/dist/bundle.min.js:1804:25)
    at _function_body (./node_modules/terser/dist/bundle.min.js:2077:19)
    at function_ (./node_modules/terser/dist/bundle.min.js:1728:20)

webpack 5.38.1 compiled with 1 error in 1670 ms
```
Note that I edited the output to redact the full path name and replaced it with `./node_modules/..etc`

**What is the expected behavior?**

Webpack should not error out just because I named my function argument `private`. This is an ES5 script file with no modules or other ES6 features. If I rename the argument to any other name then this file is packed successfully.

**Other relevant information:**
webpack version:  5.38.1
Node.js version: 15.14.0
Operating System: Ubuntu 20.04
Additional tools: npm 7.18.1

**Comment by alexander-akait** [comment]
Bug in `terser` https://github.com/terser/terser

**Comment by alexander-akait** [comment]
Reported https://github.com/terser/terser/issues/1041

**Comment by alexander-akait** [comment]
Fixed https://github.com/terser/terser/issues/1041 (https://github.com/terser/terser/commit/9101e63817573e38b122daab7d9eab5f711242f4), please wait `terser` release and update your deps, thanks for the issue
