### ISSUE TITLE
Bundled React library throws Invalid hook call error

### ISSUE THREAD

**Issue by vasilev-alex** [webpack/webpack#13868]
# Bug report

**What is the current behavior?**

I get the following React error when trying to use my library built with Webpack

```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
```

<img width="1016" alt="Screenshot 2021-07-26 at 15 54 22" src="https://user-images.githubusercontent.com/4973437/126992980-4298c76c-3c1e-48fd-8e89-afb791d0b648.png">

**If the current behavior is a bug, please provide the steps to reproduce.**

I've created a simple library https://github.com/vasilev-alex/webpack-example which reproduces the above error. As soon, as I import a React hook in my lib I get the above error.

**What is the expected behavior?**

I can use Webpack to bundle React libraries.

**Other relevant information:**
webpack version: 5.46
Node.js version: v12.22.1
Operating System: macOS Big Sur
Additional tools: -

I also posted this comment https://github.com/facebook/react/issues/13991#issuecomment-886656170 in the respecting issue https://github.com/facebook/react/issues/13991, none of the suggested solutions helped me.

P.S. using Rollup for the same library works fine.

**Comment by alexander-akait** [comment]
Try to disable minimication and update deps - terser plugin and terser itself

**Comment by vasilev-alex** [comment]
@alexander-akait I'm not using Terser for the library, and Terser that comes with `react-scripts` is used only in production mode

**Comment by alexander-akait** [comment]
You have mixed version of `webpack`, please wait when CRA will be update own code base for webpack v5 (run `yarn list webpack` to check it), so some plugins used from webpack v4 and some from webpack v5 (unfortunately they are not intended for this use and have breaking changes between v4 and v5), so you have broken output, unfortunately we can't fix it on our side, sorry, feel free to feedback

**Comment by vasilev-alex** [comment]
@alexander-akait that makes sense. Thanks!

**Comment by vasilev-alex** [comment]
@alexander-akait just tried to downgrade webpack to `4.44.2` and it doesn't seem to work either

**Comment by alexander-akait** [comment]
Something wrong on CRA side, can you try to setup it again from get started?

**Comment by vasilev-alex** [comment]
@alexander-akait same thing again : (

**Comment by alexander-akait** [comment]
> I just wonder if anybody else faces this issue

Yes, me too, because a lot of developers use CRA

Why you set `libraryTarget`?

**Comment by vasilev-alex** [comment]
`commonjs2` but I also tried 

```js
{
  // ...
  libraryTarget: 'module',
},
 experiments: {
    outputModule: true
},

**Comment by alexander-akait** [comment]
Just remove `libraryTarget`

**Comment by vasilev-alex** [comment]
Then I get the following error:

<img width="1042" alt="Screenshot 2021-08-04 at 14 08 21" src="https://user-images.githubusercontent.com/4973437/128170965-f35d3032-b5e2-45cc-b03b-e4aadeab099c.png">

**Comment by alexander-akait** [comment]
Do you want to create library or application? CRA for applications

**Comment by vasilev-alex** [comment]
I'm building a library that I use in a CRA app

**Comment by alexander-akait** [comment]
hm, looks like different react versions, give me time I will look at this deeply

**Comment by alexander-akait** [comment]
Remove `LoaderOptionsPlugin` and add `externals: { react: 'react', 'react-dom': 'react-dom',}`, set `devtool: "source-map"` for production, you have two versions of `react`, it is invalid, also you can use `libraryTarget: 'module'`, note - `commonjs2` and `module` generates different exports so `import`/`require` can be different in your application, previously, developers generated both commonjs and ecma modules versions of library, now you can generate only ecma modules and use `import { Counter } from "your-library"`;

**Comment by alexander-akait** [comment]
```
environment: {
  module: true,
},
```

You need this due https://github.com/vasilev-alex/webpack-example/blob/main/package.json#L21 and your browsers doesn't support ECMA modules, when you bundle library you don't need this, most of developers uses bundlers so `import`s will be bundled, for direct usage ECMA modules should be supports in browser, so I recommend to remove it, if you have app and library in one repo - you can use monorepo or solution from above
