### ISSUE TITLE
Large served bundle yields net::ERR_CONTENT_LENGTH_MISMATCH in Chrome

### ISSUE THREAD

**Issue by jimbojw** [webpack/webpack#13869]
# Bug report

**What is the current behavior?**
When served using `webpack serve`, large bundles may not load in the browser fast enough, getting cut off (perhaps due to underlying connection timeout). The result in the console is `net::ERR_CONTENT_LENGTH_MISMATCH`.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Use webpack to build a large bundle (~5-10MB should be big enough).
2. Serve it with `webpack serve`, listening on all interfaces (`0.0.0.0`).
3. Use an SSH tunnel to connect from `localhost` on another machine.
4. Attempt to load the page.
5. Observe the Chrome developer tools Network tab. See that the bundle gets cut off at around 15 seconds.

**What is the expected behavior?**
Served page loads without error.

**Other relevant information:**
webpack version:  5.39
Node.js version: 14.16.1
Operating System: Linux
Additional tools: N/A

**Comment by jimbojw** [comment]
# Workaround

Compressing the served content can help it get through to the browser before the underlying timeout expires. Use the [`devServer.compress`](https://webpack.js.org/configuration/dev-server/#devservercompress
) option to enable.
```
module.exports = {
  //...
  devServer: {
    compress: true,
  },
};
```

**Comment by jimbojw** [comment]
Related:
- https://github.com/angular/angular-cli/issues/7197
- https://github.com/angular/angular-cli/pull/7563

Angular fixed this by setting their own `httpServer.keepAlive' to 30000 (30 seconds).

Would be nice if there was a `devServer` option to override whatever default webpack uses.

**Comment by alexander-akait** [comment]
Not related to webpack itself sorry, please open an issue in dev server repo

**Comment by jimbojw** [comment]
Link to the appropriate repo?
