### ISSUE TITLE
Produce Production and Development at the same time

### ISSUE THREAD

**Issue by IngwiePhoenix** [webpack/webpack#1386]
My site features the ability to have certain users be identified as Developers, Debuggers or Testers, allowing them to see console messages and other things that normal people should not.

However, I would like to tell WebPack to adhere. Currently, building my code produces

```
[hash]-main.js
[hash]-libwebpack.js
[hash]-compatibility.js
```

Now, I want to have WebPack produce these files with and without UglifyJS turned on. I.e.:

```
[hash]-main.js and [hash]-main.dev.js
[hash]-libwebpack.js and [hash]-libwebpack.dev.js
[hash]-compatibility.js and [hash]-compatibility.dev.js
```

What would be the proper way to do so?

Kind regards,
Ingwie

**Comment by bebraw** [comment]
I would solve this through [webpack-merge](https://www.npmjs.com/package/webpack-merge). It allows you to set up a single configuration you can then invoke through webpack. The project README should give you some idea how to achieve that. I go into more detail at my [book chapter discussing development with Webpack](http://survivejs.com/webpack_react/developing_with_webpack/). I hope this helps.

**Comment by sokra** [comment]
Let the webpack.config.js export multiple configurations in an array.
