### ISSUE TITLE
`eval-source-map` issue with Hot Module Replacement

### ISSUE THREAD

**Issue by nighca** [webpack/webpack#13867]
# Bug report

**What is the current behavior?**

source-map does not work correctly with `devtool: eval-source-map` when app hot updating. If the hot-updated code causes runtime error, we will get something like:

```
VM3252 utils.ts:6 Uncaught TypeError: Cannot read property 'b' of undefined
    at echo (VM3252 utils.ts:6)
    at eval (index.ts?a959:5)
```

in which the stack info is not source-mapped correctly.

**If the current behavior is a bug, please provide the steps to reproduce.**

I created a demo here: https://github.com/nighca/webpack-eval-source-map. Follow the README and we can reproduce the bug.

**What is the expected behavior?**

The hot-updated code should be source-mapped correctly, and the stack info of runtime error should be like:

```
utils.ts?8813:2 Uncaught TypeError: Cannot read property 'b' of undefined
    at echo (utils.ts?8813:2)
    at eval (index.ts?a959:5)
```

**Other relevant information:**
webpack version:  5.46.0
Node.js version: v14.16.1
Operating System:  macOS
Additional tools:

**Comment by alexander-akait** [comment]
No problems with `eval-source-map` (try to any value), you have bug in code `window.a` is undefined

**Comment by nighca** [comment]
@alexander-akait It's a problem with `eval-source-map`. I made the `window.a undefined` error to reveal the source-map problem:

> in which the stack info is not source-mapped correctly.

By looking into stack info of the error, you can find that code is not correctly source-mapped. I've also submitted the expected stack info above.

**Comment by alexander-akait** [comment]
Using `5.48.0` version outputs:
```
utils.ts?8813:2 Uncaught TypeError: Cannot read property 'b' of undefined
    at echo (utils.ts?8813:2)
    at eval (index.ts?a959:5)
```

as you describe in expected

**Comment by nighca** [comment]
@alexander-akait I just tried with webpack v5.48.0, I'm afraid it didn't solve my problem.

As I mentioned in the [demo's README](https://github.com/nighca/webpack-eval-source-map):

> #### 2. edit `utils.ts`
> 
> First, comment line 2 of file `utils.ts`
> 
> ```ts
> // console.log((window as any).a.b)
> ```
> 
> Then save file, which should cause a hot update.
> 
> Then uncomment line 2 of file `utils.ts` and save file, which should cause another hot update and a new runtime error:
> 
> ```
> VM3252 utils.ts:6 Uncaught TypeError: Cannot read property 'b' of undefined
>     at echo (VM3252 utils.ts:6)
>     at eval (index.ts?a959:5)
> ```

You need to edit and save file to cause a hot update with a runtime error. Then you will get the unexpected output

**Comment by alexander-akait** [comment]
Oh I see, bug in chrome, we need report them, try to use firefox or safari - stack trace is fine (as expected)

**Comment by alexander-akait** [comment]
Interesting:
```
utils.ts?8813:2 Uncaught TypeError: Cannot read property 'b' of undefined
    at echo (VM111 utils.ts:6)
    at eval (index.ts?a959:5)
```

`utils.ts?8813:2` is right place, but stack trace is wrong

**Comment by alexander-akait** [comment]
Reported - https://bugs.chromium.org/p/chromium/issues/detail?id=1237014

**Comment by alexander-akait** [comment]
I'm afraid we can't fix it here, need to wait fix on chrome side

**Comment by nighca** [comment]
Thx @alexander-akait . I'll keep watching that issue.

**Comment by AhmedBHameed** [comment]
I'm getting the same issue with node server script.
I'm using class and trying to call private method using `this` keyword, but getting `undefined` context.
