### ISSUE TITLE
Create asset module from custom loader

### ISSUE THREAD

**Issue by otakustay** [webpack/webpack#13870]
## Feature request

We have a [@ecomfe/svg-mixed-loader](https://github.com/ecomfe/svg-mixed-loader) which transforms an svg file to multiple formats, previously we use `url-loader` and `file-loader` to generate an DataURI or standalone asset according to user configuration.

Since `url-loader` and `file-loader` are deprecated and webpack recommends asset module instead, is it still possible to generate an `asset/resource` or `asset/inline` from my loader?

**What is the expected behavior?**

I'd prefer to have some helpers like `generateAssetModule(this.resource, options)` that can be used inside a loader implementation:

```
// Inside loader
const url = await generateAssetModule(this.resource, this.getOptions().asset);
return `export const url = ${JSON.stringify(url)}`;
```

**What is motivation or use case for adding/changing the behavior?**

Currently generating an asset involves end user configuration of `module.resolve`, we want it to be transparent to end user and encapsulated inside a loader

**How should this be implemented in your opinion?**

A helper function in `webpack` or `loader-utils` to manually generate asset from a file

**Are you willing to work on this yourself?**

Not familiar with that

**Comment by alexander-akait** [comment]
Not need just create simple loader, developers should own decide what they need - inline or assets, forcing they is bad idea, feel free to feedback

**Comment by otakustay** [comment]
Just one problem, what we are doing now is a multi-format loader, the output of this loader looks like:

```
// foo.svg
export const url = `data:html/svg,...';

export const ReactComponent = () => createElement(...);
```

We have tried to ask developers to differentiate them by using `.svg` and `.component.svg` but got strongly opposed.

We want the `url = 'data:html/svg...` part can generate a standalone asset when it exceeds the `maxSize` user option, but so far this is not possible to us without `file-loader` and `url-loader.

Not sure what is the recommended practice for such case, in which only part of a loader's output can be an asset.

**Comment by alexander-akait** [comment]
Why you need change output of assets modules, we recommend use default options, also it is good practice to add `new URL('./image.png?inline', import.meta.url)`, so you can allow developers say what need to be inlined/raw https://webpack.js.org/guides/asset-modules/#replacing-inline-loader-syntax

**Comment by otakustay** [comment]
I'm not "changing" the out of asset modules, I'm just working with a certain file type (`.svg`) and convert it to a javascript module with 2 exports, accidentally in which one of them represents an asset.

The real world case is we import `.svg` file as a react component in component files like:

```jsx
import {ReactComponent as FooImage} from './foo.svg';

return (
  <div>
    {/* In this way we can specify the color and size */
    <FooImage style={{fill: 'color'}} />
  </div>
);
```

And in other javascript files we need it as a url string:

```js
import fooImageURL from './foo.svg';

document.body.style.backgroundImage = fooImageURL;
```

We have tried to use `.svg` and `.svg?react` to make differentiate them, but TypeScript complains:

```ts
declare module "*.svg" {
    const url: string;
    export default url;
}

declare module ".svg?react" {
    const value: number;
    export default value;
}

import foo from './foo.svg';
import bar from './bar.svg?react'; // Cannot find module './bar.svg?react' or its corresponding type declarations
```

Finally we have to make svg compiled to a javascript module with multiple exports.

**Comment by alexander-akait** [comment]
> I'm just working with a certain file type (.svg) and convert it to a javascript module with 2 exports, accidentally in which one of them represents an asset.

Do you need content of file?

> We have tried to use .svg and .svg?react to differentiate them, but TypeScript complains:

hm, should work... maybe will be great to open an issue in typescript

**Comment by otakustay** [comment]
> Do you need content of file?

For the implement of loader, yes, we need it to generate a react component.

To make things more clear, I past a part of our compiled svg to javascript module here:

```js
const url = "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTYiIGhlaW..."

const ReactComponent = props => /*#__PURE__*/external_React_default().createElement("svg", _extends({
  height: "16",
  width: "16",
  viewBox: "0 0 16 16",
  xmlns: "http://www.w3.org/2000/svg"
}, props), /*#__PURE__*/external_React_default().createElement("g", {
  fill: "currentColor",
  fillRule: "evenodd"
}, /*#__PURE__*/external_React_default().createElement("path", {
  d: "M14.988 1.396c-.059-.275-.31-.446-.562-.383l-2.442.618a.488.488 0 00-.343.353.545.545 0 00.112.5l.533.601-2.847 2.772L7.96 4.33a.441.441 0 00-.66.019l-3.172 3.63c0 .247.35.616.695.685l2.832-3.241 1.452 1.5a.44.44 0 00.634.01l3.196-3.11.607.686c.117.132.29.185.454.14a.491.491 0 00.335-.363l.65-2.642a.554.554 0 00.005-.247z",
  fillRule: "nonzero"
}), /*#__PURE__*/external_React_default().createElement("path", {
  d: "M14.5 7.038a.5.5 0 00-.5.5V11.5a.5.5 0 01-.5.5h-12a.5.5 0 01-.5-.5v-10a.5.5 0 01.5-.5h8.291a.5.5 0 100-1H1.5A1.5 1.5 0 000 1.5v10A1.5 1.5 0 001.5 13h12a1.5 1.5 0 001.5-1.5V7.538a.5.5 0 00-.5-.5zM14.769 15H.73a.491.491 0 00-.481.5c0 .276.216.5.481.5h14.04a.491.491 0 00.481-.5c0-.276-.216-.5-.481-.5z",
  fillRule: "nonzero"
}), /*#__PURE__*/external_React_default().createElement("circle", {
  cx: "4.5",
  cy: "8.2",
  r: "1.5"
})));
ReactComponent.displayName = "IconTest";

export default url;
export const {url, ReactComponent};
```

The `const url` can be a url referenced to a standalone asset if file exceeds 8KB.

**Comment by alexander-akait** [comment]
why do not generate:
```js
const url = new URL('./image.svg', import.meta.url);

const ReactComponent = props => /*#__PURE__*/external_React_default().createElement("svg", _extends({
  height: "16",
  width: "16",
  viewBox: "0 0 16 16",
  xmlns: "http://www.w3.org/2000/svg"
}, props), /*#__PURE__*/external_React_default().createElement("g", {
  fill: "currentColor",
  fillRule: "evenodd"
}, /*#__PURE__*/external_React_default().createElement("path", {
  d: "M14.988 1.396c-.059-.275-.31-.446-.562-.383l-2.442.618a.488.488 0 00-.343.353.545.545 0 00.112.5l.533.601-2.847 2.772L7.96 4.33a.441.441 0 00-.66.019l-3.172 3.63c0 .247.35.616.695.685l2.832-3.241 1.452 1.5a.44.44 0 00.634.01l3.196-3.11.607.686c.117.132.29.185.454.14a.491.491 0 00.335-.363l.65-2.642a.554.554 0 00.005-.247z",
  fillRule: "nonzero"
}), /*#__PURE__*/external_React_default().createElement("path", {
  d: "M14.5 7.038a.5.5 0 00-.5.5V11.5a.5.5 0 01-.5.5h-12a.5.5 0 01-.5-.5v-10a.5.5 0 01.5-.5h8.291a.5.5 0 100-1H1.5A1.5 1.5 0 000 1.5v10A1.5 1.5 0 001.5 13h12a1.5 1.5 0 001.5-1.5V7.538a.5.5 0 00-.5-.5zM14.769 15H.73a.491.491 0 00-.481.5c0 .276.216.5.481.5h14.04a.491.491 0 00.481-.5c0-.276-.216-.5-.481-.5z",
  fillRule: "nonzero"
}), /*#__PURE__*/external_React_default().createElement("circle", {
  cx: "4.5",
  cy: "8.2",
  r: "1.5"
})));
ReactComponent.displayName = "IconTest";

export default url;
export const {url, ReactComponent};
```

So webpack create data url or assets and you will have react component?

**Comment by otakustay** [comment]
Sorry to ask further questions, but when I tried to configure webpack like this:

```js
module: {
    rules: [
        {
            test: /\.svg$/,
            use: {
                loader: 'my-svg-mixed-loader',
            },
            type: 'asset',
        },
    ],
},
```

It generates a DataURI from `my-svg-mixed-loader`'s output, including the `new URL('./foo.svg', import.meta.url)` part and the `ReactComponent` part, not only the svg's raw content, this is broken to us.

The problem is now how can I having `.svg` transformed through custom loader and have `type: 'asset'`, but only want asset modules to consume the content of original `.svg` file?

**Comment by alexander-akait** [comment]
In this case you should not add `type: 'asset'`, you don't need it, webpack itself take care about assets modules, your loader should generate this content:
```js
const myURL = new URL('./image.svg?asset-module', import.meta.url);
const ReactComponent = props => /*#__PURE__*/external_React_default().createElement("svg", _extends({});

export default myURL;
export { ReactComponent }; 
```

And use this:
```js
module: {
    rules: [
        {
            test: /\.svg$/,
            resourceQuery: { not: /asset-module/ },
            use: [
              "babel-loader", // optional, if you need convert new ECMA syntax
              "your-custom-loader.js" // you loader generate code above
            ],
        },
        {
            test: /\.svg$/,
            resourceQuery:  /asset-module/,
            type: 'asset',
        },
    ],
},
```

We use `not` to prevent overlapping between two rules with `svg` extension, also in near future we will have `import assertions`, so it can be simplified in future too

**Comment by otakustay** [comment]
Successfully implement it, works like a charm! Thanks a lot
