### ISSUE TITLE
Initial styles are broken with lazyCompilation and style-loader

### ISSUE THREAD

**Issue by stefan-toubia** [webpack/webpack#13880]
# Bug report

The `lazyCompilation` experimental feature is very useful for multi-entry projects, the switch to webpack 5 did cause an overall slow down for cold builds and hot module reload times but I've been able to improve the situation with a bit of tuning.

This issue is kind of minor since reloading the page does fix the broken styles, but it's still a big enough issue that I'm going to have to continue using `mini-css-extract-loader` in development until this issue is resolved.

**What is the current behavior?**

At startup with `lazyCompilation`, it seems that styles from **external** styles, such as those loaded from a shared component library, are not being injected into the document. As mentioned, the styles do load successfully after reloading the page.

**If the current behavior is a bug, please provide the steps to reproduce.**

I'm using `less`, so the config looks like this:

```js
  {
    test: /\.less$/,
    use: ["style-loader", "css-loader", "less-loader"],
  }
```

Use `lazyCompilation`:
```js
 experiments: {
    lazyCompilation: true,
  },
```

Example entry point:

```js
import React from "react";
import ReactDOM from "react-dom";
// Local component that has it's own stylesheet.
import Widget from "../components/Widget";
// Component from component library that also imports it's own stylesheet.
import SharedWidget from "shared-components/Widget";

const App = () => {
  return (
    <>
      {/* Styles work as expected */}
      <Widget />
      {/* Styles are not added to the document after the initial compilation. */}
      <SharedWidget />
    </>
  );
};

ReactDOM.render(<App />, document.getElementById("root"));

```
I'm actually using Suspense here with a lazy loaded App component but it doesn't seem to affect this issue.

1. Start webpack dev server
2. Load the entry point
3. Wait for the entry point to compile
4. `Widget` styles are added to the document, `SharedWidget` styles are not.
5. Refresh the page to fix the issue.

**What is the expected behavior?**

`SharedWidget` styles should be added to the document without having to manually reload the page.

**Other relevant information:**
webpack version:  ~5.45.0
Node.js version: 10, same on 14
Operating System: macos
Additional tools:

Some of the related dependencies:
```json
// v5 claims not to be compatible with webpack 5 but we haven't been able to switch over yet
// due to some breaking changes. I get the same results on v7.
"less-loader": "^5.0.0",
"mini-css-extract-plugin": "1.3.6",
"css-loader": "^3.4.1",
"style-loader": "^2.0.0",
"esbuild-loader": "^2.13.0",
```

**Comment by salmanansari14** [comment]
I can contribute

**Comment by alexander-akait** [comment]
bump

**Comment by alexander-akait** [comment]
Weird, can't reproduce with the later webpack version and style-loader, so I want to close, anyway feel free to feedback or open a new issue if you faced with this bug, thank you
