### ISSUE TITLE
ConstPlugin generates the wrong code with Tagged Template Literals 

### ISSUE THREAD

**Issue by maccullt** [webpack/webpack#13884]
**Do you want to request a *feature* or report a *bug*?**
This is a BUG

**What is the current behavior?**
```let x = SomeFunc`some string` ?? some_default;```

gets generated as something like

```let x = SomeFunc`some string` ?? 0;```

This is incorrect if `SomeFunc` can return null in some circumstances.
See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#tagged_templates

**If the current behavior is a bug, please provide the steps to reproduce.**

```
function SomeTimesNullTag(strings, ...args) {
	if (strings.length !== 1) 
		return null;
	return strings[0];
}

function testNullTags() {
	let y = SomeTimesNullTag`a` ?? 'y default';	
	console.log(`y: ${y}`);
	let z = SomeTimesNullTag`a${y}b` ?? 'z default';
	console.log(`z: ${z}`);
}

```
After being built, the above code produces:

```
y: a
z: 0
```

... because the code was transformed into:

```
function n(o,...l){
	if(o.length!==1)
		return null;
	return o[0]}

function t(){
	let o=n`a`??0;
	console.log(`y: ${o}`);
	let l=n`a${o}b`??0;
	console.log(`z: ${l}`)
}
```

It looks like a bug in ConstPlugin.
For example https://github.com/webpack/webpack/blob/efeb1287e52870036cc01b22476852205e99c31a/lib/ConstPlugin.js#L325

keepRight is false because template strings returns false for asNullish()

https://github.com/webpack/webpack/blob/efeb1287e52870036cc01b22476852205e99c31a/lib/javascript/BasicEvaluatedExpression.js#L262

This means the right hand term gets incorrectly replaced with 0 for a tagged template string.

ConstPlugin

**What is the expected behavior?**

In the case of tagged template literals they might produce null.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

  "webpack": "^5.45.1"

**Comment by alexander-akait** [comment]
Feel free to send a fix

**Comment by sokra** [comment]
We should not treat **tagged** template literals as template literals, since they do not behave like them.

**Comment by vankop** [comment]
bump
