### ISSUE TITLE
Lazy uploading remoteEntry script with Module Federation

### ISSUE THREAD

**Issue by ramory-l** [webpack/webpack#13896]
## Feature request

**What is the expected behavior?**
Expected that share scope will be visible and useable after importing module via System.import('/js/script.js') (SystemJS)

**What is motivation or use case for adding/changing the behavior?**
It will be more effective to upload remoteEntries when they needed via SystemJS. However, for now you can only get script works when it uploads within index.html when client entries to the site.

**How should this be implemented in your opinion?**
One more variable with shared dependencies needs to be added in module's object.
Expected something like this (Code on screenshot works if I uncomment init):
<img width="799" alt="Screenshot 2021-07-30 at 18 50 03" src="https://user-images.githubusercontent.com/48647803/127678857-2ed8f7eb-8045-4872-a318-01dfa59f1e4e.png">
What I get with SystemJS:
<img width="1142" alt="Screenshot 2021-07-30 at 18 51 36" src="https://user-images.githubusercontent.com/48647803/127679324-3924e507-42f5-45d0-b71a-7741f2727f67.png">

**Are you willing to work on this yourself?**
yes, may need your help

**Comment by ScriptedAlchemy** [comment]
Share scope is not accessible through the object, you'll have to look at the remote container to see what was outputted 

you can also `console.log(__webpack_share_scopes__)` from inside a webpack built application

**Comment by ramory-l** [comment]
Ok. Is it possible to import remote entry somehow dynamically like with SystemJS but with share scope initialization?

**Comment by ramory-l** [comment]
Thank you very much! I guess that to achieve a cool result, need to combine both methods of loading scripts and choose the best in a certain situation.

**Comment by alexander-akait** [comment]
@ramory-l Can we close?

**Comment by ramory-l** [comment]
I found out [here](https://github.com/module-federation/module-federation-examples/blob/master/advanced-api/dynamic-remotes/app1/src/App.js) that there must be one more line of code `await __webpack_init_sharing__("default");`. How can I write it in webpack 4?

**Comment by alexander-akait** [comment]
No, webpack v4 is not support it
