### ISSUE TITLE
Allow to replace asset/resource with `new URL(import.meta.url, '...')` when `output.libraryTarget` is 'module'

### ISSUE THREAD

**Issue by hronro** [webpack/webpack#13899]
## Feature request

**What is the expected behavior?**

Currently asset/resource works like this:

```js
import mainImage from './images/main.png';

img.src = mainImage; // '/dist/151cfcfa1bd74779aadb.png'
```

However, this does not work when using webpack to build a library. But luckily, if the `output.libraryTarget` is 'module', we can use `import.meta.url` like this:

```js
import mainImage from './images/main.png';

img.src = mainImage; // new URL(import.meta.url, './151cfcfa1bd74779aadb.png')
```

**What is motivation or use case for adding/changing the behavior?**

This make assets work for libraries. The output of the library may not compatible with all bundlers, but at lease it works with the browser's native es module.

Alse see: #2933

**Comment by alexander-akait** [comment]
Sorry, out of scope webpack, please use custom plugin for this, `import mainImage from './images/main.png';` should not be used in libraries, please migrate code on `new URL(...)` or create custom loader for this
