### ISSUE TITLE
Allow require.context() passing a fixed chunk name

### ISSUE THREAD

**Issue by yyj08070631** [webpack/webpack#13894]
## Feature request

**What is the expected behavior?**

Support a syntax like `require.context('./modules', true, /\.js$/, 'lazy', 'myModule')` to allow specifying a fixed chunkName.

**What is motivation or use case for adding/changing the behavior?**

I want to split some code and pack them into a single file about operating dialogs from a enormous module.

- `require.context()` doesn't support specifying a fixed chunkName.
- `require.ensure()` and `import()` don't support passing expressions as module names.

**How should this be implemented in your opinion?**

I try to turn `webpack\lib\dependencies\RequireContextDependencyParserPlugin.js` into a new [async-import-plugin](https://github.com/yyj08070631/async-import-plugin/blob/c73e2ba651bd861579821d8496838525c685b024/async-import-plugin.js#L13). It supports the fifth param which can pass a fixed chunkName. The following is a replaying step.

- Clone the repo [async-import-plugin](https://github.com/yyj08070631/async-import-plugin/blob/c73e2ba651bd861579821d8496838525c685b024/async-import-plugin.js#L13), run `npm i`.
- Modify some code about managing chunkName in `webpack\lib\ContextModule.js`.
![impicture_20210730_174940](https://user-images.githubusercontent.com/27988527/127635622-5d15a6d3-9592-4a02-82c6-ff45d2be467b.png)
- Run `npm run build`, then `require.asyncImport('./modules', true, /\.js$/, 'lazy', '$myModule$')` in index.js can achieve the target.

**Are you willing to work on this yourself?**
yes

**Comment by yyj08070631** [comment]
> _For maintainers only:_
> 
> * [ ]  webpack-4
> * [ ]  webpack-5
> * [ ]  bug
> * [ ]  critical-bug
> * [ ]  enhancement
> * [ ]  documentation
> * [ ]  performance
> * [ ]  dependencies
> * [ ]  question

**Comment by yyj08070631** [comment]
> _For maintainers only:_
> 
> * [ ]  webpack-4
> * [ ]  webpack-5
> * [ ]  bug
> * [ ]  critical-bug
> * [ ]  enhancement
> * [ ]  documentation
> * [ ]  performance
> * [ ]  dependencies
> * [ ]  question

**Comment by yyj08070631** [comment]
> _For maintainers only:_
> 
> * [ ]  webpack-4
> * [x]  webpack-5
> * [ ]  bug
> * [ ]  critical-bug
> * [x]  enhancement
> * [ ]  documentation
> * [ ]  performance
> * [ ]  dependencies
> * [ ]  question

**Comment by alexander-akait** [comment]
Duplicate https://github.com/webpack/webpack/issues/9184
