### ISSUE TITLE
Explicitly require another entry chunk on-demand?

### ISSUE THREAD

**Issue by rubyruy** [webpack/webpack#1390]
I have an app that I want to treat more-or-less like an SPA even though there are several distinct pages which which serve as entry points into it (e.g. `/login`, `/signup`, `/password-reset`). Each of these entry points corresponds to a named entry in `webpack.config` (e.g. `{login: 'pages/login.jsx', signup:'pages/signup.jsx', ...}` and so forth). I also emit a separate HTML page for each entry point using `HtmlWebpackPlugin` - it's a very small HTML wrapper that simply includes the one entry chunk used for that page. So far so good, it all works really well and we can optimize shared code chunks and so on as advertised.

What I'm having trouble with is allowing navigation between "pages" using pushState alone, minimizing needless downloads and code loading. Ideally I should be able to go from `/login` to `/signup` simply by loading the `signup` entry chunk at runtime (i.e. `pages/signup.jsx`). I'm not sure if this is actually possible... I might be missing something.

If I load something like `require('bundle?lazy!pages/signup.jsx')` (or use `require.ensure` without `bundle-loader`... though as far as I understand it amounts to the same thing), well.. that works actually, except a new chunk would be created, distinct from the entry chunk (and as such would download all over again when the `/signup` html page is accessed directly), even though the content _should_ be identical. I thought maybe `require('bundle?lazy&name=signup!pages/signup.jsx')` might work (explicitly giving it the same name as the entry chunk) but this seems to confuse webpack, I get an uncaught `TypeError: Cannot read property 'call' of undefined` at runtime.

Is this outright not supported (if so, don't suppose it could be?) or am I just going about it wrong?

**Comment by sokra** [comment]
This works but is a bit more complex. You have two different chunk types: entry chunks and additional chunks. `require.ensure` loads additional chunks. entry chunks include the webpack runtime. You only want to have a single webpack runtime on the page. To archive this the orginal entry chunks shouldn't be entry chunks. This can be done with the CommonsChunkPlugin.

``` js
{
  entry: {
    a: ["./a"], // must be arrays
    b: ["./b"]
  },
  plugins: [
    new webpack.CommonsChunkPlugin({
      name: "commons",
      minChunks: Infinity // this is optional if you want only the runtime in this chunk
        // i. e. to inline it into the HTML
    });
  ]
}
```

``` js
// You must specify the name elsewise an additional chunk will be created
// Be careful: Loading this chunk also executes the entry point "./a" as sideeffect
require.ensure([], function() {

}, "a");
// or
require("bundle?lazy&name=a!./a");
```

**Comment by rubyruy** [comment]
Ok I think I understand the problem with the runtime and the entry chunks, but that aside, is `require("bundle?lazy&name=a!./a");` the way to load another chunk by name? It still seems to get confused when using output.chunkFilename containing a hash... which makes sense since that call isn't really "loading another chunk by name" - it's creating a new chunk that maybe happens to have the same name as something else, which will (almost accidentally) be loaded instead. Is that about right?

Is there a way to actually, *explicitly* just load a chunk by name, in a way that would work with `[hash]` ?

**Comment by sokra** [comment]
Why doesn't it work with `[hash]`? The chunk names should be independent of the filenames.

**Comment by rubyruy** [comment]
Ah indeed, `[hash]` was not the problem - I was basically still just trying to manually load entry chunks. 

I'm running into some further trouble trying to make sense of this while trying to load a chunk on-demand based on a run-time value. I do know, ahead of time, all the possible modules I might want loaded this way, however, it's not just all the files in a folder (in which case the default context behavior would more or less work out of the box) - it's just a list of arbitrary module paths (as in, what would be passed to `require` - both local-relative paths as well as module-relative paths). I as able to create a custom context for these using `require.context` and abusing `DefinesPlugin` a little, and it is correctly aware of all the possible modules it can load (and will correctly load them by calling the context module... but it will do so synchronously, not on-demand). Subsequent `require.ensure` calls don't seem to be aware of the previously defined context... 

It's all gotten pretty messy. I'll probably just make do with using regular dynamic contexts and live without the ability to dynamically load non-entry chunks outside of the `./pages/ + viewName + '.jsx'`  folder, unless there is actually a way more straight-forward way of doing this. I mean ideally I could just define the chunks I know I'll want up front (in `webpack.config.js`) and load them explicitly by chunk name in the run-time code.

**Comment by rubyruy** [comment]
Actually, @sokra, let me just try to clear up my general understanding of webpack concepts. Can you confirm as true or false the following statements:

- In webpack, **the only way**  to load code on demand, at run time, is using `require.ensure` (or `require(deps, callback)`).
- In webpack, **the only way** to load a module based on a run-time value is on-demand and using a [context module](http://webpack.github.io/docs/context.html).

Is that right so far? I have to use the `require.ensure` and contexts no matter what - the `CommonsChunkPlugin` only comes into deciding what code goes in what chunk?

If that is all the case, I have some less straight-forward follow-up questions:

- Do you have to use dynamic contexts to load a module on demand based on a run-time value, or is it possible to combine this approach with explicitly created contexts (using `require.context`)
- Are context modules by necessarily tied to a specific root folder and scanning the files within? Is there no way to just feed it a list of potential require paths (i.e. to concrete modules, not just a folder) instead?

**Comment by Metallium** [comment]
I think you're mostly right. Webpack 2 introduces more convenient System.import syntax for chunk separation

btw you can create a loader that would generate your own context based on your own spec. That rules :)

**Comment by sokra** [comment]
> In webpack, the only way to load a module based on a run-time value is on-demand and using a context module.

In webpack, the only way to load a module based on a run-time value is ~~on-demand and~~ using a context module.

A context doesn't load modules on-demand. You need to explicitly combine both concepts to archive this.


> Are context modules by necessarily tied to a specific root folder and scanning the files within? Is there no way to just feed it a list of potential require paths (i.e. to concrete modules, not just a folder) instead?

Currently yes, they need to tied to a root folder, but for no technical reason. It's propably useful to add a `ManualContextPlugin` which overrides the list of requireable modules in a context. (This would require a small change in webpack...)

**Comment by jakeNiemiec** [comment]
@webpack-bot I still care about this, but thank you for the warning.

**Comment by abhinavsingi** [comment]
@jakeNiemiec Fixed or caring no more?
