### ISSUE TITLE
infinity fetch when xxxxx.hot-update.json not found

### ISSUE THREAD

**Issue by SquirrelJimmy** [webpack/webpack#13921]
# Bug report

**What is the current behavior?**
if xxxxxx.hot-update.json not found, infinity fetch that make browser dead

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  5.48.0
Node.js version: v14.16.1
Operating System: macOS 11.4 (20F71) Darwin 20.5.0
Additional tools:

**Comment by alexander-akait** [comment]
It was fixed in https://github.com/webpack/webpack/releases/tag/v5.48.0, run `npm ls webpack` and check your version

> If the current behavior is a bug, please provide the steps to reproduce.

If you still have problems using `5.48.0` please fill out this and I will reopen
