### ISSUE TITLE
Tree shaking class methods

### ISSUE THREAD

**Issue by wuweikd** [webpack/webpack#13922]
It likes https://github.com/rollup/rollup/issues/349. 

I want use Tree-shaking in class methods, but it's not work.

I know it's hard to solve, and I'm a rookie, so I hope others can help me.

**Comment by vankop** [comment]
This will require a lot of static analysis..

**Comment by alexander-akait** [comment]
bump

**Comment by alexander-akait** [comment]
It is part of webpack, we can do deep analyze
