### ISSUE TITLE
How to split specified modules and their dependencies into one bundle

### ISSUE THREAD

**Issue by curly210102** [webpack/webpack#13923]
### Discussed in https://github.com/webpack/webpack/discussions/13917

<div type='discussions-op-text'>

<sup>Originally posted by **curly210102** August  3, 2021</sup>
The main entry `index.js` import module `a` and `b` under the "components" directory, and module `a` import module `c`, `index.js` and `c` are not related directly. I want to split the imported modules under "components", bundle them with the modules they depend on. Below is the webpack config.

``` js
const path = require("path");
const BundleAnalyzerPlugin = require("webpack-bundle-analyzer")
  .BundleAnalyzerPlugin;

module.exports = {
  mode: "production",
  entry: "./src/index.js",
  output: {
    path: path.resolve(__dirname, "dist")
  },
  optimization: {
    runtimeChunk: "single",
    splitChunks: {
      cacheGroups: {
        vendor: {
          test: /[\\/]components[\\/]/,
          name: "vendors",
          chunks: "all",
          priority: 10,
          enforce: true,
          reuseExistingChunk: true
        }
      }
    }
  },
  plugins: [
    new BundleAnalyzerPlugin({
      openAnalyzer: false
    })
  ]
};

```

You can reproduce it in https://codesandbox.io/s/silly-violet-k6gew?file=/webpack.config.js

![image](https://user-images.githubusercontent.com/76864176/128015652-f07a438f-1c69-4e61-b7e8-ceb10f3b5c50.png)

As shown in the analysis, module `c` is splitted into the main bundle. I expect the custom group have higher priority to inculde depend on modules, how to achieve it?

Thanks for help ❤️ </div>

**Comment by alexander-akait** [comment]
Please be patient and use `Discussions` for questions, when somebody will be available you get help, no need duplicate, it creates unnecessary issues not related to bugs

**Comment by curly210102** [comment]
> _For maintainers only:_
> 
> * [ ]  webpack-4
> * [x]  webpack-5
> * [ ]  bug
> * [ ]  critical-bug
> * [ ]  enhancement
> * [ ]  documentation
> * [ ]  performance
> * [ ]  dependencies
> * [x]  question

**Comment by nyngwang** [comment]
@curly210102 Hi, cute dog. Could you please teach me how did you choose the value of the option `splitChunks.chunks`? You can reply in my Discussion thread #18040. Thanks!
