### ISSUE TITLE
Plugin: Questions

### ISSUE THREAD

**Issue by IngwiePhoenix** [webpack/webpack#1392]
I want to make a plugin.

The fact that nobody has made a PurifyCSS plugin thus far is somewhat of a confusion, to me. So I want to make a plugin not for PurifyCSS, but rather a general-purpose plugin that allows post-processing of files with custom code. Effectively I want to use PurifyCSS with that.

In order to make it, I want to know a few things about writing a plugin. Yes, I did look into the docs - but the explanations seem super sparse.

- I know that I have to use the `Tapable` thing. Which is the phase or step in which I can access all the final bundle files? Like, all the JS and CSS files that have been put together. I want to operate on these.
- Which method do I need to provide for this kind of plugin to work?
- In general, what phases can a plugin hook into?

Kind regards,
Ingwie

**Comment by sokra** [comment]
The `emit` hook is propably the best: http://webpack.github.io/docs/plugins.html#emit-async

**Comment by bebraw** [comment]
Given you got the plugin running, closing. 👍
