### ISSUE TITLE
Module Federation: injecting scripts for remotes with HtmlWebpackPlugin

### ISSUE THREAD

**Issue by serrg** [webpack/webpack#13924]
# Bug report

**What is the current behavior?**

During runtime when request to remote application **is pending**, injected script is blocking the page.

**If the current behavior is a bug, please provide the steps to reproduce.**

In the scenario we have host and remote applications:

- host application `shell` (`localhost:3000`)
- remote `app` (`localhost:3002`) which is not responding, we simulate `request pending` by setting the timeout

`shell` webpack configuration:
```
new ModuleFederationPlugin({
  name: "shell",
  filename: "remoteEntry.js",
  remotes: {
    app: 'app@http://localhost:3002/remoteEntry.js',
  }
})
new HtmlWebpackPlugin({
    template: "./public/index.html",
    inject: "body",
})
```

Source code of `app`:
```
const express = require("express");
const app = express();
const port = 3002;
app.use((req, res, next) => setTimeout(next, 30000));
app.get("*", (req, res) => { res.send("Hello World!"); });
app.listen(port, () => { console.log(`Example app listening at http://localhost:${port}`); });
```

<img width="759" alt="Screenshot 2021-08-04 at 13 52 19" src="https://user-images.githubusercontent.com/1391453/128181279-3b7bd876-9183-4553-9ae9-d0ce7d85296b.png">

As you can see script connecting for the remote entry is located in `head` tag. 

We can use [promise based loaders for remotes](https://webpack.js.org/concepts/module-federation/#promise-based-dynamic-remotes), pass a promise to this remote and inject into `body` tag:
```
market: `promise new Promise(resolve => {
  const remoteUrl = 'http://localhost:3002/remoteEntry.js'
  const script = document.createElement('script')
  script.async = true;
  script.defer = true;
  script.src = remoteUrl
  document.body.appendChild(script);
})
`
```

and at runtime script is located at the end body but the page is still blocked by loading remote entry.
 
<img width="566" alt="Screenshot 2021-08-04 at 14 13 31" src="https://user-images.githubusercontent.com/1391453/128181649-8c31677f-606b-4725-b343-339fc02c9f17.png">

Alternatively we can dynamically load remotes during runtime using [this](https://github.com/webpack/webpack/issues/11033#issuecomment-644349386) 

**What is the expected behavior?**

1. When `inject: body` is set with `HtmlWebpackPlugin` put loading script at the end of the body tag.
2. Do not block page/application when remote entry is not responding.

**Other relevant information:**
webpack version:  5.38.1
Node.js version: 14.17.1
Operating System:  macOS/Ubuntu
Additional tools: html-webpack-plugin: 5.3.1

**Comment by alexander-akait** [comment]
Please open an issue in `HtmlWebpackPlugin`, it should be solved there

**Comment by serrg** [comment]
> Please open an issue in `HtmlWebpackPlugin`, it should be solved there

Asked [here](https://github.com/jantimon/html-webpack-plugin/issues/1671), thanks!

**Comment by mstaniuk** [comment]
After adding `script.async = true;` here:
https://github.com/webpack/webpack/blob/c181294865dca01b28e6e316636fef5f2aad4eb6/lib/runtime/LoadScriptRuntimeModule.js#L100
The script is still halting rendering till the request is resolved. 🤔 
![image](https://user-images.githubusercontent.com/25054081/128339935-fb6389bc-03a4-4b2d-a083-c19426cccaaf.png)

**Comment by serrg** [comment]
That is strange, because @jantimon says that "All scripts injected by html-webpack-plugin are using the defer property to allow async loading" via https://github.com/jantimon/html-webpack-plugin/issues/1671#issuecomment-893218108

**Comment by DevHunvee3** [comment]
Has anyone solve this?

**Comment by serrg** [comment]
@DevHunvee3 The issue still occurs for us and we are using workaround for non blocking render:

```
import { ComponentType } from 'react';

declare global {
  interface Window {
    __remotes__: Record<string, string>;
  }

  // eslint-disable-next-line @typescript-eslint/camelcase
  const __webpack_init_sharing__: any;
  // eslint-disable-next-line @typescript-eslint/camelcase
  const __webpack_share_scopes__: any;
}

const getRemoteEntryUrl = (module: string) =>
  `${module}@${getPublicPath(module)}${REMOTE_ENTRY}`;


const dynamicImport = async (path: string): Promise<{ default: ComponentType<any> }> => {
  const remoteName = path.split('/')[0];

  if (!remoteName) {
    throw new Error(`URL not configured for remote '${path}'.`);
  }

  const remoteUrl = getRemoteEntryUrl(remoteName);

  if (remoteUrl.split('@').length !== 2) {
    throw new Error(`URL misconfigured for remote '${path}'`);
  }

  const [moduleName, moduleUrl] = remoteUrl.split('@');

  await __webpack_init_sharing__('default');

  await new Promise<void>((resolve, reject) => {
    const element = document.createElement('script');

    element.src = moduleUrl;
    element.type = 'text/javascript';
    element.async = true;

    element.onload = () => {
      element.parentElement?.removeChild(element);
      resolve();
    };

    element.onerror = (err: Event | string) => {
      element.parentElement?.removeChild(element);
      reject(err);
    };

    document.head.appendChild(element);
  });

  // eslint-disable-next-line @typescript-eslint/ban-ts-ignore
  // @ts-ignore
  const container = window[moduleName] as any;

  // eslint-disable-next-line @typescript-eslint/camelcase
  await container.init(__webpack_share_scopes__.default);

  const component = `.${path.replace(remoteName, '')}`;
  const factory = await container.get(component);

  return factory();
};

```

and using `dynamicImport` like:
```
const Comp = () => {
  const fallback = <></>;
  const RemoteService = lazy(() => dynamicImport('remoteService'));

  return (
    <ErrorBoundary FallbackComponent={() => <></>}>
      <Suspense fallback={fallback}>
        <RemoteService />
      </Suspense>
    </ErrorBoundary>
  );
};
```

where `remoteService` is remote path from module federation config
