### ISSUE TITLE
When the library is umd in development mode, the exported content is {}

### ISSUE THREAD

**Issue by xiangyin1987** [webpack/webpack#13926]
# Bug report
**What is the current behavior?**
When the library is umd in development mode, the exported content is {}, When injectClient is set to false, it can be exported normally, but it loses the ability of hot loading

**If the current behavior is a bug, please provide the steps to reproduce.**
1. config webpack output
```
outpub:{
...
filename:'index.js',
libray:{
   name: 'my-lib',
   type: 'umd'
}
}
```
2. config webpack devServer
```
devServer:{
   ...
   injectClient: true
}
```
**What is the expected behavior?**
When configuring injectClient: true, hope to export umd normally

**Other relevant information:**
webpack version:  5.48.0
Node.js version:  12.21.0
Operating System: macOS/Ubuntu
Additional tools: webpack-dev-server

**Comment by alexander-akait** [comment]
Fixed in `rc` release in webpack-dev-server, stable release will be soon, you don't need `injectClient`, please try `4.0.0-rc.0`
