### ISSUE TITLE
Missing acorn peer dependency

### ISSUE THREAD

**Issue by ZebraFlesh** [webpack/webpack#13935]
# Bug report

**What is the current behavior?**
When I install the latest version of `webpack` (5.48.0), I receive the warning:
```
npm WARN acorn-import-assertions@1.7.6 requires a peer of acorn@^8 but none is installed. You must install peer dependencies yourself.
``` 

This is quite strange since `acorn` is an explicit dependency of `webpack`: https://github.com/webpack/webpack/blob/v5.48.0/package.json#L13

Output from `npm ls acorn`:

```
> npm ls acorn
my-project@4.7.0 /Users/me/git/my-project
├─┬ eslint@7.32.0
│ └─┬ espree@7.3.1
│   └── acorn@7.4.1 
├─┬ jest@27.0.6
│ └─┬ @jest/core@27.0.6
│   └─┬ jest-config@27.0.6
│     └─┬ jest-environment-jsdom@27.0.6
│       └─┬ jsdom@16.7.0
│         ├── acorn@8.4.1 
│         └─┬ acorn-globals@6.0.0
│           └── acorn@7.4.1  deduped
└─┬ webpack@5.48.0
  └── UNMET PEER DEPENDENCY acorn@8.4.1 
```

**If the current behavior is a bug, please provide the steps to reproduce.**

`npm install -D webpack`

**What is the expected behavior?**

Able to install without peer dependency warnings.

**Other relevant information:**
webpack version:  5.48.0
Node.js version: 14.17.3
Operating System: macOS 11.5.1 (Intel silicon)
Additional tools:
- npm: 6.14.13

**Comment by ZebraFlesh** [comment]
Even stranger. The following resolves the issue:

```
npm uninstall webpack eslint jest
npm install -D webpack
npm install -D eslint jest
```

Combining the last two commands into one (e.g., `npm install -D webpack eslint jest`) does not resolve the issue.

**Comment by alexander-akait** [comment]
due bug in npm
