### ISSUE TITLE
Require Resolve to a path failes 

### ISSUE THREAD

**Issue by lukepolo** [webpack/webpack#13931]
# Bug report

**What is the current behavior?**
When trying to run production build of app errors out on 

`node dist/main.js`
```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type number (3320)
```

`main.js`

```
const uiBasePath = path_1.default.dirname(/*require.resolve*/(3320));
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Use https://github.com/lukepolo/webpack-resolve-bug/tree/main/dist, run `node dist/main.js` , and you should see the error.

**What is the expected behavior?**
To properly resolve the path as a string

**Other relevant information:**
webpack version:  5.48.0
Node.js version: v12.16.3
Operating System: osx
Additional tools:

**Comment by lukepolo** [comment]
Adding `moduleIds: 'named'` does fix the issue, but I don't think thats a long term fix.

**Comment by alexander-akait** [comment]
Limitation due:
```
const uiBasePath = path_1.default.dirname(require.resolve('@bull-board/ui/package.json'));
```

Duplicate https://github.com/webpack/webpack/issues/9367#issuecomment-508703051

You can use `moduleIds: 'named'` as workaround or rewrite code, in ECMA modules you should use `fs` to read file or `import pck from './package.json' assert { type: "json" }` so you will not faced with the problem.

Feel free to feedback
