### ISSUE TITLE
TypeError: __webpack_require__(...).posix is undefined

### ISSUE THREAD

**Issue by nik-swarmagency** [webpack/webpack#13941]
This bug was already documented and tested in another github issue. See here: https://github.com/eslint/eslint/issues/14885
# Bug report

**What is the current behavior?**
This bug was already documented and tested in another github issue. See here: https://github.com/eslint/eslint/issues/14885

**If the current behavior is a bug, please provide the steps to reproduce.**
This bug was already documented and tested in another github issue. See here: https://github.com/eslint/eslint/issues/14885

**What is the expected behavior?**
This bug was already documented and tested in another github issue. See here: https://github.com/eslint/eslint/issues/14885

**Other relevant information:**
webpack version:      "react": "^17.0.2",
    "react-dom": "^17.0.2",
Node.js version: This bug was already documented and tested in another github issue. See here: https://github.com/eslint/eslint/issues/14885
Operating System: This bug was already documented and tested in another github issue. See here: https://github.com/eslint/eslint/issues/14885
Additional tools:

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

**Comment by alexander-akait** [comment]
You should polyfill `path` for web target
