### ISSUE TITLE
How to create a loader that can handle loader style requires?

### ISSUE THREAD

**Issue by kkirby** [webpack/webpack#1394]
Hello,

I'm wondering if there is a way to make a loader that can itself process require statements, offloading the actual loading to WebPack and get back the result. The reason is I want to be able to add functionality to SASS like so:

```
@import 'image-size!someImage.png' as $myImage;

div {
    $width: $myImage.width;
    $height: $myImage.height;
}
```

Which is translated to:

```
$myImage: (
   width: 100px,
   height: 200px,
   url: './someImage/png'
);

div {
   width: map-get($myImage,width);
   height: map-get($myImage,height);
}
```

The loader would take in the original SASS, find the `@import` statement, run it through web pack. Get the resulting Javascript, convert it to a SASS map, and replace the import statement with the newly created SASS map.

I really, really feel like this is possible, but I have no idea where to start.

Thanks,
Kyle

**Comment by kkirby** [comment]
After looking around, I think I found what I was looking for: `this.loadModule` inside the loader. If I'm mistaken, let me know. Thanks!

**Comment by sokra** [comment]
`this.loadModule` is what you are looking for.
