### ISSUE TITLE
Invalid warning on Windows: reported dependencies need to be absolute paths.

### ISSUE THREAD

**Issue by FrozenKiwi** [webpack/webpack#13949]
# Bug report

**What is the current behavior?**
When importing "electron" on windows, the following warning is displayed:
```
Invalid dependencies have been reported by plugins or loaders for this module. All reported dependencies need to be absolute paths.
```

However, the paths listed are already absolute.  

This appears to be the same issue resolved here: https://githubmemory.com/repo/sysgears/mochapack/issues/99

**If the current behavior is a bug, please provide the steps to reproduce.**

For a minimal repro, copy the ABSOLUTE_PATH_REGEX: https://github.com/webpack/webpack/blob/d77d8636015ae71195b16b39dd0e6daebdcace83/lib/NormalModule.js#L87 into [regex101](https://regex101.com/r/mJ8BQu/1) and test the following absolute path: C:/src/TheCoin/apps/admin/node_modules/electron/dist/chrome_100_percent.pak.  The regex will fail to match

I have traced the issue to the line `import { ipcRenderer } from 'electron';`

**What is the expected behavior?**

No errors.  The paths are absolute and things are (to the best of my knowledge) working correctly

I didn't look any further because the regex kinda doesn't make sense the way it's setup.  The () brackets don't separate the characters, so the `|` or statements don't switch on the path separator.  I'm not actually sure what's it is testing, but it clearly seems to want to test `^[a-zA-Z]:(\\|\\\\|\/)` (note the different opening `(`

If there are valid reasons to leave the regex as-is, then I'll try and figure out why this issue is happening the way it is.  There may be alternative ways to resolve this.  

**Other relevant information:**
webpack version:  5.39.0.  I can't test latest (I'm locked to electron-forge's version) but the regex has not changed, so I assume the issue still exists.
Node.js version: 14
Operating System: Win10
Additional tools: Electron

**Comment by sokra** [comment]
> C:/src/TheCoin/apps/admin/node_modules/electron/dist/chrome_100_percent.pak

The slashes are wrong. They need to be backslashes on windows.

C:\src\TheCoin\apps\admin\node_modules\electron\dist\chrome_100_percent.pak

**Comment by alexander-akait** [comment]
Answered, feel free to feedback

**Comment by FrozenKiwi** [comment]
Please reopen.

If forward slashes aren't supported, that regex makes even less sense

**Comment by alexander-akait** [comment]
It is limitation, otherwise it is not possible to distinguish which path is absolute and which is not, please fix it in a plugin/loader

**Comment by FlyingDR** [comment]
@sokra It is true that directory path separator in Windows is backslash, but it is possible to use forward slash too and these paths are considered correct by the OS and works fine.

Please also notice that current regular expression fails to match `\absolute\path` kind of path which is also valid in Windows according to [official documentation](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#fully-qualified-vs-relative-paths).

I've prepared a [test suite](https://regex101.com/r/1Unqus/1
) with updated regexp and all kinds of paths. 

Please consider updating `ABSOLUTE_PATH_REGEX` to use it:
```js
const ABSOLUTE_PATH_REGEX = /^([a-zA-Z]:(\\|\/)|\\|\\\\|\/)/; 
```

**Comment by Edge00** [comment]
Came across to this problem on windows too.
