### ISSUE TITLE
Allow node require when target is node

### ISSUE THREAD

**Issue by tsu-complete** [webpack/webpack#1395]
Building node dependencies into the project when in a node environment forces the use of webpack require which is not always desired (particularly when the required file is unknown before hand)

The use case is a node script which loads configuration files as js which may or may not exist and is determined after a build. (Node executable runs on another npm package directory and searches for configurations) 

Named packages can be circumvented:
```coffee
if "node" is compiler_options.target
  (compiler_options.externals or= [ ]).push ( context, request, callback ) ->
    if /^[a-z\-_0-9]+$/i.test request
      callback null, "commonjs #{request}"
    else do callback
```
But this is sloppy and results in unnecessary wrappers:
```js
function(module, exports) {
  module.exports = require("fs");
}
```
And still throws warnings when the dependency cannot be resolved immediately:
```
Critical dependencies:
82:33-46 the request of a dependency is an expression
 @ ./src/util/package.coffee 82:33-46
```
Which actually causes a failure given the expression will only be checked by webpack's known dependencies, even though the point is to not know the dependency until runtime.

I would propose a fallback when the target is node, knowing the environment will be node if the package cannot be found, use node's native require.
It would also be great to have the externals with commonjs prefix not create unnecessary wrapper code in this mode.

If this is not desired for most builds (let me know why if you feel so, would be curious the reason) it should at least be available with a flag (--fallback/--no-fallback?) otherwise it restricts developers from using a feature of node.

**Comment by tsu-complete** [comment]
I can make the warning go away with
```coffee
compiler_options.module ?= { }
compiler_options.module.exprContextRegExp ?= /$^/
compiler_options.module.exprContextCritical ?= false
```
but that only replaces the lookup with a strict error instead... not better...
```js
!(function webpackMissingModule() { var e = new Error("Cannot find module \".\""); e.code = 'MODULE_NOT_FOUND'; throw e; }());
```
For reference the code is:
```coffee
for name in package_files when name isnt "package.json"
  file = path.join package_directory, name
  # ...
  if match = name.match /\.?(.+?).conf(?:ig)?.js$/i
    match_object = { }
    try
      match_object[match[1]] = require file # !< problem line
    catch e
      match_object[match[1]] = error: e
    extend package_file.config, match_object
  # ...
```

**Comment by tsu-complete** [comment]
Alright this is a bit better, I actually don't mind it for resolving known packages.



```coffee
builtins = { } # maps are better for lookup
for builtin in require "builtins"
  builtins[builtin] = true

# there is more to env but it's essentially this but look up the tree until found or at root
env = require path.join do process.cwd, "package.json"

if "node" is compiler_options.target
  (compiler_options.externals or= [ ]).push ( context, request, callback ) ->
    if builtins[request] or env.dependencies[request]
      callback null, "commonjs #{request}"
    else do callback
```
http://coffeescript.org/#try:builtins%20%3D%20{%20}%0Afor%20builtin%20in%20require%20%22builtins%22%0A%20%20builtins[builtin]%20%3D%20true%0A%0Aenv%20%3D%20require%20path.join%20do%20process.cwd%2C%20%22package.json%22%0A%0Aif%20%22node%22%20is%20compiler_options.target%0A%20%20%28compiler_options.externals%20or%3D%20[%20]%29.push%20%28%20context%2C%20request%2C%20callback%20%29%20-%3E%0A%20%20%20%20if%20builtins[request]%20or%20env.dependencies[request]%0A%20%20%20%20%20%20callback%20null%2C%20%22commonjs%20%23{request}%22%0A%20%20%20%20else%20do%20callback

Still **REALLY** need a solution to the major issue here, in fact even this line
```coffee
require path.join do process.cwd, "package.json"
```
would fail issuing a warning during compilation and an error during runtime

I forked and would be more than happy to contribute a solution but I don't know the code base that well and I am sure there is a best approach so I would like to at least discuss possibilities first... (I really need this change though so if I don't get a reply this week I will implement something locally).

**Comment by sokra** [comment]
Try this plugin:

``` js
plugins: [function() {
  this.parser.plugin("call require", function(expr) {
    if(expr.arguments.length !== 1) return;
    var param = this.evaluateExpression(expr.arguments[0]);
    if(!param.isString() && !param.isConditional()) return true;
  });
}]
```

**Comment by tsu-complete** [comment]
So this is great, but to make it work for externals as well I needed to modify it a bit, is there a way to do this entirely from the plugin? I would like to be able to make an actual plugin rather than modifying the compiler options in this way.

```js
var is_path;

is_path = new RegExp(path.sep);

(compiler_options.externals || (compiler_options.externals = [])).push(function(context, request, callback) {
  if (is_path.test(request)) {
    return callback(null, "commonjs " + request);
  } else {
    return callback();
  }
});

(compiler_options.plugins || (compiler_options.plugins = [])).unshift(function() {
  return this.parser.plugin("call require", function(expr) {
    var param;
    if (1 !== expr["arguments"].length) {
      return;
    }
    param = this.evaluateExpression(expr["arguments"][0]);
    if (!(param.isString() || param.isConditional() || (new RegExp(path.sep)).test(param.string))) {
      return true;
    }
  });
});
```

**Comment by bebraw** [comment]
@tsu-complete Safe to close now?

**Comment by tsu-complete** [comment]
Up to you, I think it answers my question but there is potential work here, it would really be great to see this as a plugin option instead of a compiler option - I don't think it's too uncommon

**Comment by bebraw** [comment]
@tsu-complete Ok, I marked this as an enhancement in case someone wants to tackle it.

**Comment by tsu-complete** [comment]
Sounds great, thanks!

**Comment by milankarunarathne** [comment]
@tsu-complete There should be options to avoid this. I used this approach and it works for me.
http://jlongster.com/Backend-Apps-with-Webpack--Part-I#Getting-Started

Part of `webpack.config.js` file

```javascript
var fs = require('fs');

var nodeModules = {};
fs.readdirSync('node_modules')
  .filter(function(x) {
    return ['.bin'].indexOf(x) === -1;
  })
  .forEach(function(mod) {
    nodeModules[mod] = 'commonjs ' + mod;
  });

module.exports = {
  target: 'node',
  externals: nodeModules
}
```

**Comment by sokra** [comment]
https://www.npmjs.com/package/webpack-node-externals
