### ISSUE TITLE
[webpack5]  __webpack_modules__[moduleId] is not a function

### ISSUE THREAD

**Issue by hello-lun** [webpack/webpack#13951]
webpack  The version used when packaging : v5.44.0
webpack Version at the time of project use： v4.46.0

![image](https://user-images.githubusercontent.com/34638158/128630960-68b872be-3219-48d3-b13a-8907efeddf2b.png)

![image](https://user-images.githubusercontent.com/34638158/128631130-06d184d1-ee2e-4ee1-a72c-736b4065da0d.png)

Problem Description：
When webpack5 uses the packaging library, it uses extenals to exclude some node_modules, and the packaged library code includes require syntax. When used in the webpack4 project, the package introduced by require will use 【__webpack_require__】 to find it, causing an error 【index.js:56 Uncaught TypeError: __webpack_modules__[moduleId] is not a function】

But I use webpack5 to use the library, it seems there is no problem

I used webpack5's production mode to package a.js. But using a.js in the development mode of webpack4 will cause the above problems. But using webpack4 to package a.js is no problem. How did you solve it

like issues： https://github.com/webpack/webpack/issues/11277

**Comment by vasilev-alex** [comment]
same thing for me, but only when I build a library in the `development` mode

**Comment by hello-lun** [comment]
> same thing for me, but only when I build a library in the `development` mode

I used webpack5's production mode to package a.js. But using a.js in the development mode of webpack4 will cause the above problems. But using webpack4 to package a.js is no problem. How did you solve it

**Comment by vasilev-alex** [comment]
@hello-lun I did not. Let's see what the maintainers say. Should this be supported?

**Comment by hello-lun** [comment]
> @hello-lun I did not, ended up using Rollup to bundle my library.
> 
> Let's see what the maintainers say. Should this be supported?

What a coincidence, I ended up packing it with rollup. But webpack4 can also achieve the goal
