### ISSUE TITLE
Include `stats` section in `examples` folder on this repo

### ISSUE THREAD

**Issue by fregante** [webpack/webpack#13950]
I just found out the examples folder on this repo, it's great!

https://github.com/webpack/webpack/tree/main/examples/

I'd love to see the output of [`stats`](https://webpack.js.org/configuration/stats/) included here as well. I have no idea of what each of these do exactly. What's an asset? What's a module? What's a chunk? Show me.

The output for each setting would be generated with the config:

```js
module.exports = {
  //...
  stats: {
    all: false,
    [thisSetting]: true
  },
};
```

plus joint options like `groupAssetsByChunk` that need to be combined with other options.

**Comment by alexander-akait** [comment]
Pr welcome

**Comment by salmanansari14** [comment]
I want to contribute

**Comment by snitin315** [comment]
Bump

**Comment by dollar22** [comment]
I wanna work what should i add in this

**Comment by dollar22** [comment]
@snitin315 hope you are fine is this issue is still open

**Comment by fregante** [comment]
Sigh

**Comment by fregante** [comment]
Ping ☺️
The stats are mostly undocumented or unclear to what they refer to to anyone who's not very familiar with webpack.
