### ISSUE TITLE
Module not found for path with backslash

### ISSUE THREAD

**Issue by Download** [webpack/webpack#1396]
Hi, I stumbled on #428 which describes nearly my problem, except that I am already (I think?) specifying an absolute path for the resolve root...

**Project structure:**

    webpack-test/
        src/
            greeting/
                greeting.js
                greeting.css
            app.js
        dist/
        node_modules/
        webpack.config.js

**Import in greeting.js:**

    import 'greeting.css';

**Error message:**

> ERROR in ./greeting/greeting.js
> Module not found: Error: Cannot resolve module 'greeting.css' in C:\Users\Stijn\Documents\GitHub\webpack-test/src\greeting
> @ ./greeting/greeting.js 15:0-23

The file does exist. In fact, if I copy-paste the path in the error message to a Windows Explorer window, it immediately takes me to the right folder and I see it right there.

**Contents of my webpack.config.js:**
```javascript
module.exports = {
	context: __dirname + '/src',
	entry: {
		javascript: './app.js',
	},
	output: {
		filename: 'app.js', 
		path: __dirname + '/dist',
		publicPath: 'http://localhost:8090/assets'
	},
	module: {
		loaders: [
			{test: /\.js$/,  include: /src/, loaders: ['react-hot', 'babel-loader']},
			{test: /\.css$/, include: /src/, loaders: ['style-loader', 'css-loader']}
		]
	},
	externals: {
		'react': 'React'
	},
	resolve: {
		extensions: ['', '.js', '.jsx', '.css']
	},
	resolveLoader: {
		root: __dirname + '/node_modules'
	}
}
```

I also tried with a relative import:

    import './greeting.css';

But then I get **2** errors that look more difficult... :)

> ERROR in ./greeting/greeting.css
> Module not found: Error: Cannot resolve 'file' or 'directory' ./../../node_modules/css-loader/index.js > in C:\Users\Stijn\Documents\GitHub\webpack-test/src\greeting
> @ ./greeting/greeting.css 4:14-82

> ERROR in ./greeting/greeting.css
> Module not found: Error: Cannot resolve 'file' or 'directory' ./../../node_modules/style-loader/addStyles.js in C:\Users\Stijn\Documents\GitHub\webpack-test/src\greeting
> @ ./greeting/greeting.css 7:13-71

Any tips for  webpack n00b?

**Comment by Metallium** [comment]
import project files as relative paths like ./greeting.css
delete context, resolveLoaders sections
sections, they seem to be redundant
use path.combine instead of concating path strings
strings

**Comment by Metallium** [comment]
you'll have to use absolute paths in config (e.g. entry points)

**Comment by sokra** [comment]
`__dirname + '/node_modules'` is not an absolute path on windows. Windows uses `\` as path separator. Better use `path.resolve(__dirname, "node_modules")`.

**Comment by Download** [comment]
Thanks guys, you were right. It had to do with me concatenating paths manually. You should indeed use the `Path` helper. I was following some tutorials were they were doing it manually so I just copied that. I guess the author must have been using Mac/Linux.

Weird thing is that the path did work when copy-pasted into Windows Explorer... So I guess there must be some internal APIs in Windows that are not consistent with what Explorer accepts.

Thanks all!

**Comment by gnudle** [comment]
Thank you thank you
