### ISSUE TITLE
UmdLibraryPlugin code enters the `amd` branch even when the code is loaded in a `script` tag - when `requirejs` is present on the window

### ISSUE THREAD

**Issue by liady** [webpack/webpack#13979]
# Bug report

**What is the current behavior?**
When using `UmdLibraryPlugin`, and when `require.js` is present on the window - the generated code mistakenly enters the `amd` branch, even for scripts that are loaded in a `script` tag. This causes a `mismatched anonymous module` error in `require.js`, breaking the code.
This happens since this line:
```
else if(typeof define === 'function' && define.amd)
```
does not differentiate between `define` that an amd loader injects, and a `window.define` that might be present on the window regardless of how this code is loaded.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Build a `umd` bundle (which uses `UmdLibraryPlugin`).
2. Create a simple HTML page -
3. Load [require.js](https://requirejs.org/) on the page.
4. Load the bundle in a regular script tag (not amd).
5. The code will break.

**What is the expected behavior?**
The code shouldn't enter this `else if` branch if loaded via a script tag and not using an amd loader.
One option for a solution is first remove the `gloablThis.define` from the global object, then check for `typeof define`, then restore `gloablThis.define`.

**Other relevant information:**
webpack version:  *
Node.js version:  *
Operating System:  *
Additional tools: UmdLibraryPlugin

**Comment by alexander-akait** [comment]
Sorry, works as expected, please rename global `define` function for `requirejs`
