### ISSUE TITLE
Conditional triggering of build in watch mode

### ISSUE THREAD

**Issue by dko-slapdash** [webpack/webpack#13978]
## Feature request

Would be cool to have one more property under `watchOptions`:
```
watchOptions: {
  condition: async () => {
    // Called on each files batch change, after aggregateTimeout debouncing.
    // Check that all other watch-build tools, like tsc, succeeded.
    // Return true to trigger webpack watch-build and false to skip it this time.
  }
}
```

**What is the expected behavior?**

Before triggering a watch-build, be able to run a custom code and ignore files changes if some condition is met.

**What is motivation or use case for adding/changing the behavior?**

An example: sometimes webpack is used to bundle artifacts generated by other tools (e.g. tsc in a large monorepo with cross-dependencies between packages, where tsc generates dist/ folders with `*.js`, and then webpack uses these `dist/*.js` and `dist/*.map` to build public/ and not waste time on dependent packages rebuild from their sources). 

The problem is that, when the monorepo is large, there can be multiple processes of `tsc --watch` (one per each monorepo package), and the set of tsc builds does not settle immediately after `git pull` affecting multiple packages. E.g. if there are A -> B -> C packages dependencies in the monorepo, they all start watch-building after the pull, and until e.g. C is fully built, A and B builds may fail. The status of a package build is reflected in tsconfig.buildinfo file, and eventually everything in tsc settles, but - there is a time period when we're not yet ready to tell webpack to start the watch-build.

For such cases, the new `condition` option may be written to verify that all tsconfig.buildinfo files are clean and do not contain errors. If they do, then there is no sense in triggering a watch-build (it burns lots of CPU cycles and freezes the laptop in a large monorepo project, especially when there are multiple webpack built packages involved!); instead, it's better to wait until all tsconfig.buildinfo files have no errors, i.e. all monorepo packages are watch-build by tsc successfully.

**How should this be implemented in your opinion?**

There can be an additional check after chokidar (or whatever is used for watching) unfreezes.

**Are you willing to work on this yourself?**

yes

**Comment by alexander-akait** [comment]
I don't think we need this, it is very exotic and requires a lot of code rewriting

**Comment by dko-slapdash** [comment]
> requires a lot of code rewriting

Why so? In Watchpack, there is [_onTimeout](https://github.com/webpack/watchpack/blob/master/lib/watchpack.js#L339) method which is called on every timer aggregation event (aggregateTimeout). It's already a part of the logic. My proposal is to be able to add an additional callback here which checks the condition (e.g. checks that all tsc projects in the monorepo were built successfully based on tsconfig.buildinfo file; this buildinfo dependent code can be user-defined, not a part of webpack itselt) and, if the condition is false, don't run the timer code; instead, just reschedule the timer.

> it is very exotic 

Most likely I haven't done a good job explaining the usecase above. Monorepos are very common, and mutually-dependent packages in these monorepos are common too, definitely not exotic.

**Comment by dko-slapdash** [comment]
It appeared that this feature is very easy to implement via just the regular plugins API. Here is the implementation:
https://www.npmjs.com/package/conditional-aggregate-webpack-plugin
