### ISSUE TITLE
Webpack build output depends on the absolute path of the project since v5.48.0

### ISSUE THREAD

**Issue by weiwei-lin** [webpack/webpack#13970]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

build depends on the absolute path of the project.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. run webpack
2. move the project to another directory
3. run webpack again
4. Observe that the build output are different.

**What is the expected behavior?**

webpack should produce the same output regardless the project's path.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

node: v12.12.0
webpack: v5.48.0 (it works in v5.47.1)

**Comment by alexander-akait** [comment]
> If the current behavior is a bug, please provide the steps to reproduce.

It is not enough to solve the problem, please provide more information (configuration/reproducible test repo) and I will reopen
