### ISSUE TITLE
Add an stats option to show side effects

### ISSUE THREAD

**Issue by abhishekrathore03** [webpack/webpack#13973]
## Add stats for Side Effects

**What is the expected behavior?**
After enabling this feature Webpack should show all the files which has got side effects and may impact tree shaking

**What is motivation or use case for adding/changing the behavior?**
It's generally very difficult in a big framework which uses multiple self made or external modules to identify where tree shaking went wrong, if developers can know where is the issue it would be very easy for them to fix

**How should this be implemented in your opinion?**
Apologies but no idea

**Are you willing to work on this yourself?**
No

**Comment by abhishekrathore03** [comment]
i am fine with not doing in a default way but there should be a way for this.
somewhat similar to the following - 

`webpack --profile --json > stats.json`

Or any other alternative
Or may be a plugin for this?

**Comment by alexander-akait** [comment]
I think better solution to create plugin for this

**Comment by abhishekrathore03** [comment]
okay, so what's the next step?
can you port this issue on correct place or i will have to create a new issue somewhere?

**Comment by alexander-akait** [comment]
Just create own plugin

**Comment by vankop** [comment]
feel free to use https://github.com/vankop/side-effect-free-webpack-stat-plugin
