### ISSUE TITLE
Cannot use `contenthash` in output if using Web Worker and any plugin that taps into mainTemplate.hooks.localVars

### ISSUE THREAD

**Issue by roninjin10** [webpack/webpack#13982]
# Bug report

**What is the current behavior?**
If [using contenthash](https://github.com/AprilArcus/webpack-sri-workers-contenthash-repro/blob/main/webpack.config.js#L15) with a [WebWorker](https://github.com/AprilArcus/webpack-sri-workers-contenthash-repro/blob/main/index.js#L1) and any plugin is calling [Maintemplate.prototype.hook.localVars](https://github.com/AprilArcus/webpack-sri-workers-contenthash-repro/blob/main/minimalplugin.js#L22) such as the [webpack-subresource-integrity plugin](https://github.com/waysact/webpack-subresource-integrity/blob/main/webpack-subresource-integrity/index.ts#L168), the runtime starts requesting for undefined when it tries to load the web worker chunk both observed in the console and from [adding logging in webpacks source](https://github.com/webpack/webpack/blob/main/lib/runtime/GetChunkFilenameRuntimeModule.js#L240) .  

Since this is happening as a sideeffect of calling .tap, I think the issue lies downstream of https://github.com/webpack/webpack/blob/c181294865dca01b28e6e316636fef5f2aad4eb6/lib/RuntimePlugin.js#L365 but I'm not sure.  

This is related to https://github.com/waysact/webpack-subresource-integrity/issues/165
This is also possibly related to https://github.com/webpack/webpack/issues/13801 

**If the current behavior is a bug, please provide the steps to reproduce.**
Minimal Reproduction: https://github.com/AprilArcus/webpack-sri-workers-contenthash-repro

1. Use a worker with the new webpack 5 worker API
2. Use contentHash in output.chunkFileName
3. Create a plugin that simply taps into maintemplate.hook.localVars

**What is the expected behavior?**
Expected Behavior:  It shouldn't be putting undefined in the runtime for this chunk

**Other relevant information:**
webpack version:  5.50.0
Node.js version: 16.6.0
Operating System: macos / ubuntu
Additional tools: none

**Comment by alexander-akait** [comment]
Please do not duplicate issues, we already have repo here https://github.com/webpack/webpack/issues/13801, put your investigation here https://github.com/webpack/webpack/issues/13801 with example of reproducing

**Comment by roninjin10** [comment]
Sorry didn't know if it was related or not for sure

**Comment by alexander-akait** [comment]
Same problem with the same plugin, it is related
