### ISSUE TITLE
Question: Gulp, Grunt(build systems) vs webpack (bundles system)

### ISSUE THREAD

**Issue by evilebottnawi** [webpack/webpack#1398]
I would like to deal with any problem can not cope webpack. Is it possible to replace build systems on webpack or there are tasks that require the build system. How much faster webpack cope with the assembly than gulp (grunt)?

**Comment by SpaceK33z** [comment]
Yes, in many cases you can completely replace gulp / grunt with webpack. Webpack can compile your Sass / Less -> CSS, handle image minification etc.. The small things that are left, you can often also do with npm scripts. An example `package.json` file:

```json
{
  "devDependencies": {
    "webpack": "1.12.0"
  },
  "scripts": {
    "build": "npm run clean && webpack --progress",
    "clean": "rm -rf dist/*"
  }
}
```

Now you can run `npm run build`.

**Comment by bebraw** [comment]
@evilebottnawi Safe to close perhaps?

**Comment by evilebottnawi** [comment]
@bebraw yes
