### ISSUE TITLE
Allow child compilations to set a different mode

### ISSUE THREAD

**Issue by jeffposnick** [webpack/webpack#13984]
## Feature request

**What is the expected behavior?**

When creating a child compilation via `createChildCompiler()`, there should be a mechanism for overriding the parent compilation's `mode`.

Manually setting `childCompiler.options.mode` has no effect, and attempting to add a `DefinePlugin` to set a different `process.env.NODE_ENV` value just results in 

```
WARNING in DefinePlugin
Conflicting values for 'process.env.NODE_ENV'
```

since the parent compilation's `DefinePlugin` is automatically inherited by the child compilation.

**What is motivation or use case for adding/changing the behavior?**

See https://github.com/GoogleChrome/workbox/issues/2843—there's a use case where a developer wants the main compilation to be in `mode: 'production'` but would like the child compilation, which is managed by our plugin, to have `mode: 'development'`.

**How should this be implemented in your opinion?**

I'd imagine that this needs to be an option passed to `createChildCompiler()`, as it seems like it might be too late to change anything after the child compilation has already been created?

**Are you willing to work on this yourself?**
no

**Comment by alexander-akait** [comment]
I think it is not safe, plugins can add hook from parent compilation, so they will work even your change `mode`, anyway you can solve this:
- using:
```js
const childCompiler = compilation.createChildCompiler(
    `${pluginName} ${request}`,
    outputOptions
);
childCompiler.options.mode = 'development';
```
- adding additional option on your plugin side, anyway changing `mode` is not safe, `mode` is just sugar, in fact, it just activates additional plugins, no more, so I recommend to add more options

**Comment by jeffposnick** [comment]
Hello @alexander-akait!

Setting `childCompiler.options.mode = 'development';` does not lead to what you'd expect from being in development mode. In the child compilation, `NODE_ENV` still ends up being set to `'production'`, the code is still minified, etc.

I do understand that `mode` just activates additional plugins, but as far as I can tell, by the time `createChildCompiler()` returns, those additional plugins (`DefinePlugin`, minification, etc.) have already tapped into the child compilation's hooks if the parent was in `mode: 'production'`. Is there a supported API for iterating over all of the plugins that are already tapped into a hook and "un-tapping" the ones we want to disable? As I mentioned, I can't just add an additional `DefinePlugin` instance to set `processs.env.NODE_ENV`, since if I don't disable the one that's already tapping the hook, I get `WARNING in DefinePlugin Conflicting values for 'process.env.NODE_ENV'`

**Comment by sokra** [comment]
Maybe you can use a new compiler instead of a child compiler. Otherwise I don't see a way of solving that.

**Comment by jeffposnick** [comment]
I think I'd rather not go the new compiler route just to solve this problem, as using a child compiler gives us the behavior we want in general, and most folks are fine with inheriting all the settings from the parent.

It's good to have some confirmation that it's not possible right now, and if there's no appetite for changing child compiler creation to support it, I'll just adjust our plugin's documentation to make it clear that the use case isn't supported.

Thanks for letting me know!
