### ISSUE TITLE
webpack-cli ReferenceError: require is not defined

### ISSUE THREAD

**Issue by mgdeveloper79** [webpack/webpack#13998]
I have a following configuration

Package.json
```
{
		"name": "my-project",
		"version": "1.22.11",
		"type": "module",
		"dependencies": {
				"html-webpack-plugin": "^5.3.2",
				"react": "^17.0.1",
				"react-dom": "^17.0.1",
				"react-router-dom": "^5.2.0"
		},
		"scripts": {
				"build": "webpack --config webpack/webpack.config.dev.js",
				"test": "jest",
				"dev": "yarn build && cross-env NODE_ENV=dev node ./src/index.js"
		},
		"devDependencies": {
				"@babel/preset-env": "^7.15.0",
				"@babel/preset-react": "^7.14.5",
				"babel-core": "^6.26.3",
				"babel-jest": "^26.6.3",
				"babel-loader": "^8.2.2",
				"cross-env": "^7.0.3",
				"css-loader": "^6.2.0",
				"enzyme": "^3.11.0",
				"enzyme-adapter-react-16": "^1.15.6",
				"enzyme-to-json": "^3.6.1",
				"jest": "^26.6.3",
				"mini-css-extract-plugin": "^2.2.0",
				"webpack": "^5.50.0",
				"webpack-cli": "^4.7.2"
		}
}

```
webpack configuration

```

const path = require('path');
const MiniCssExtractPlugin = require("mini-css-extract-plugin");
const HtmlWebpackPlugin = require('html-webpack-plugin')

module.exports = {
  entry: './index.js',
  target: 'web',  
  mode: 'development',
  output: {
    filename: 'bundle-web.js',
    path: path.resolve(__dirname, '../dist'),
  },  
  plugins: [
    new HtmlWebpackPlugin(),
    new MiniCssExtractPlugin()],
  module: {
    rules: [     
     {
      test: /\.(js|jsx)$/,
      exclude: ['/node_modules/'],
      use: {
        loader: 'babel-loader',
      }
    },     
    {
      test: /\.css$/i,
      use: [MiniCssExtractPlugin.loader, "css-loader"],
    },
    ],
  },
  resolve: {
    extensions: ['*', '.js',  '.mjs']
  },  
};

```
.babelrc
```
{
    "presets": [
        "@babel/preset-env",
        "@babel/preset-react"
    ]
 }
```

index.html
```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Title</title>
</head>

<body>
    <div id="app"></div>
    <script src=bundle-web.js"></script>
</body>

</html>
```

```
index.js (proprietary code excluded). 
import * as React from 'react';
import {
  BrowserRouter as Router,
  Switch,
  Route,
  Link
} from "react-router-dom";
import ReactDOM from 'react-dom';
import './index.css';
.
.
.
```

Node version: v13.14.0
OS: Windows 7. (Yes I know should replace it, but I don't believe OS is the problem here).
Yarn:  1.22.5

The bundle is created as I can see in the dist folder but when I run "yarn dev" 

I am getting the following error. I tried all kinds of solutions of google, gitbub and stackoverflow , no luck.
```
webpack --config webpack/webpack.config.dev.js
webpack-cli] Failed to load \project\webpack\webpack.config.dev.js' config
webpack-cli] ReferenceError: require is not defined
   at file:///project/webpack/webpack.config.dev.js:1:14
   at ModuleJob.run (internal/modules/esm/module_job.js:110:37)
   at async Loader.import (internal/modules/esm/loader.js:179:24)
   at async importModuleDynamicallyWrapper (internal/vm/module.js:422:15)
   at async WebpackCLI.tryRequireThenImport (project\node_modules\webpack-cli\lib\webpack-cli.js:57:26)
   at async loadConfig project\webpack-cli\lib\webpack-cli.js:1536:27)
   at async project\webpack-cli\lib\webpack-cli.js:1589:36
   at async Promise.all (index 0)
   at async WebpackCLI.resolveConfig project\node_modules\webpack-cli\lib\webpack-cli.js:1587:38)
   at async WebpackCLI.createCompiler project\node_modules\webpack-cli\lib\webpack-cli.js:2045:22)```

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

**Comment by 476421978** [comment]
try to remove  `"type": "module"` of **webpack.config.js**

**Comment by 476421978** [comment]
remove  "type": "module" of package.json

**Comment by mgdeveloper79** [comment]
Even though the issue is closed, I am replying here in a hope that it can help someone running into the same issue. Basically the issue was my thought process was reversed. You can either choose ES6 or Common JS, by defining type: module, I was saying all my code base including the webpack config now becomes ES6 syntax, hence I was getting the error. So I removed type:module stating that all my code base including the webpack configuration files should be treated as Common JS. Then I used babel to transpile my ES6 import statements of my actual source (not the webpack config since its already written in common JS) into common JS and that resolved all the issue. The second alternative was to use type:module to state that it's a ES6 and then use import statements and ES6 equivalent code to write the webpack configuration. However because most of examples in Webpack was in common JS, I chose the former option, because I am sort of new to JavaScript and I wanted to avoid any basic mistakes such as this. So in a nutshell there was a misunderstanding on my part, I hope this comment helps newbie JS developers.
Thank you!
