### ISSUE TITLE
Async module library with `type: "module"` exports `undefined`

### ISSUE THREAD

**Issue by yujunjung** [webpack/webpack#13995]
# Bug report

**What is the current behavior?**

```
Welcome to Node.js v16.6.1.
Type ".help" for more information.
> await import(`./dist/bundle.js`)
[Module: null prototype] { a: undefined }
```

**If the current behavior is a bug, please provide the steps to reproduce.**

package.json
```json
{"type":"module"}
```

```js
// entry.js

export const a = await Promise.resolve(1);
```

```js
// webpack.config.js

export default {
	mode: "development",
	entry: "./entry.js",
	devtool: false,
	output: {
		path: new URL("./dist", import.meta.url).pathname,
		filename: "bundle.js",
		library: {
			type: "module"
		}
	},
	experiments: {
		topLevelAwait: true,
		outputModule: true
	}
};
```

**What is the expected behavior?**

```
Welcome to Node.js v16.6.1.
Type ".help" for more information.
> await import(`./dist/bundle.js`)
[Module: null prototype] { a: 1 }
```

**Other relevant information:**
webpack version:  5.50.0
Node.js version: 16.6.1
Operating System:  macos big sur
Additional tools:

**Comment by alexander-akait** [comment]
I can't reproduce, my output is `1`

**Comment by alexander-akait** [comment]
Also you reproducible test steps doesn't work

**Comment by yujunjung** [comment]
@alexander-akait not a library output

**Comment by yujunjung** [comment]
i tried to build a standalone esm library

**Comment by alexander-akait** [comment]
What is `target`? Browser? Please provide valid reproducible steps

**Comment by yujunjung** [comment]
i tested on nodejs, but esm it is target independent

**Comment by alexander-akait** [comment]
Oh, reproduced, bug

**Comment by alexander-akait** [comment]
Let's add test case for https://github.com/webpack/webpack/pull/13997/
