### ISSUE TITLE
When using 'run' node api with gulp watch, sometimes does not make bundles

### ISSUE THREAD

**Issue by preco21** [webpack/webpack#1400]
I would like to make gulp watch task by webpack Node API, as like this example:
https://github.com/webpack/webpack-with-common-libs/blob/master/gulpfile.js

But when execute `run` function on second time in watch process, it doesn't create new bundle. (hash not changed)

webpack.config.js:

``` javascript
var webpack = require('webpack');
var config = require('./gulp/config.js');

module.exports = {
    target: 'web',
    debug: true,
    devtool: '#source-map',
    entry: config.webpack.entry,
    output: {
        path: __dirname + '/' + config.webpack.output,
        filename: config.webpack.dest
    },
    module: {
        loaders: [{
            test: /\.js$/,
            exclude: /node_modules/,
            loader: 'babel?optional[]=runtime'
        }],
        postLoaders: [{
            test: /\.json$/,
            exclude: /node_modules/,
            loader: 'json'
        }]
    },
    plugins: [
        // new webpack.optimize.CommonsChunkPlugin(config.webpack.commons)
    ]
};
```

gulp webpack task:

``` javascript
var webpackCompiler = webpack(webpackConfig);
gulp.task('webpack-dev', ['source-lint'], function(callback) {
    webpackCompiler.run(function(error, stats) {
        if (error) {
            throw new util.PluginError('webpack', error);
        }

        util.log('[webpack]', stats.toString({colors: true}));
        callback();
    });
});
```

gulp watch task:

``` javascript
gulp.task('watch', ['build'], function() {
    gulp.watch(config.copy.source, ['copy']);
    gulp.watch(config.minify.target, ['minify']);
    gulp.watch(config.target, ['babel']);
    gulp.watch(config.webpack.target, ['webpack-dev']);
});
```

And it seems to file hash not updated. But I'm exactly updated my source files:

![b4a2548e-4e4f-11e5-8bf7-441ec973c097](https://cloud.githubusercontent.com/assets/4936201/10829940/442b8cba-7ec0-11e5-8247-1d51741ae380.png)

I'm using Windows 10 and io.js 3.0.0

**Comment by nwbb** [comment]
Having the same issue, too.  My  gulp task + config are nearly identical in structure.

When initially calling webpackCompiler.run(), everything builds fine.  Calling it a second time (by gulp watch triggering the task again) spits out stats as normal, with no updated bundle.  Change the file, trigger 'watch' which triggers the task, and from this point forward it builds appropriately.  

Looking at the compiler output, I can see that - after initial run - `fileTimestamps` is not populated.  After the second `.run()`, `fileTimestamps` is populated and seems to always output a new file from this point forward.

**Comment by bm2u** [comment]
@preco21 and @nwbb I've got the same issue and a compareable configuration. In my case adding `cache: false` to my webpack configuration solves the problem. Although it is not as performat as before. But helps :-) I'm using Windows 8.1 with wepback 1.12.9

**Comment by bebraw** [comment]
Can you see this issue in webpack 2?

**Comment by preco21** [comment]
Never tested since I have moved to use only standalone `webpack-dev-server` and npm scripts. Maybe I can test it with my old project.

**Comment by preco21** [comment]
@bebraw Okay, I can confirm this issue has been fixed:

![image](https://cloud.githubusercontent.com/assets/4936201/26066558/48484c38-39d2-11e7-9e63-e85c19b65ab3.png)

![image](https://cloud.githubusercontent.com/assets/4936201/26066567/4bb185a6-39d2-11e7-8b2b-d3ee46655f52.png)

Hash changes as expected even if set the `cache` option to `true`.
