### ISSUE TITLE
webpack({devServe:{}}) is error//typescript node api

### ISSUE THREAD

**Issue by see7788** [webpack/webpack#14006]
webpack@5.44.0
import webpack, {webpack as w} from "webpack"
webpack({devServe:{}})//error
w({devServe:{}})//error

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
