### ISSUE TITLE
How likely is resolve.unsafeCache to fail?

### ISSUE THREAD

**Issue by trusktr** [webpack/webpack#1401]
I'm debating whether I should enable it for my build tool (rocket:module for Meteor). Do you have sample cases of when it fails? How much time can we save compared to having a top-level `cache` object?

**Comment by Metallium** [comment]
Give it a try.
Personally used it and found no reasons to keep it - there were no statistic difference when building/watching a large project (4-5k modules)

**Comment by bebraw** [comment]
@trusktr Any update? I wonder if the situation has changed since August. Please note that Webpack 2 is near so maybe that will help.

**Comment by trusktr** [comment]
@bebraw I haven't played with it. I might just update to 2.0 when that's ready and evaluate the options at that point. Caching (safe) had wished fine.
