### ISSUE TITLE
Module id not stable when compiling the same code in different folders

### ISSUE THREAD

**Issue by randing89** [webpack/webpack#14014]
# Bug report

**What is the current behavior?**
This week we upgrade webpack from `5.33.2` to `5.50.0`. The module ids became unstable between builds produced from different CI instances.

**If the current behavior is a bug, please provide the steps to reproduce.**
- Clone https://github.com/randing89/github-brwfkb
- Execute `npm install && npm run build` in folder a and b
- Observe webpack assigning different module ids to the same file

_With webpack 5.50.0_
![image](https://user-images.githubusercontent.com/640557/129934152-dbb5e448-f411-4798-890f-99e1c25fef2a.png)

_With webpack 5.33.2_
![image](https://user-images.githubusercontent.com/640557/129934262-098c1bea-bc4e-41b8-9125-55e95e61e4bf.png)

**What is the expected behavior?**
Module id not change like the old version

**Comment by alexander-akait** [comment]
Please provide reproducible test repo or steps to reproduce

**Comment by randing89** [comment]
@alexander-akait Hi. I am having trouble creating a repo. When will a module id contains layer information? I mean the hash attached after the `module.request`?

**Comment by alexander-akait** [comment]
Can you clarify?

**Comment by randing89** [comment]
@alexander-akait I suspect the problem is from this line https://github.com/webpack/webpack/blob/1f0bdf722098975919e5758475c32a02bfe14d06/lib/NormalModule.js#L307 where the `this.layer` was changing in my different CI environments. However when I try to repo locally I had trouble making an example that would produce a module id with layer hash. Like the code was always executing the condition branch of `this.layer === null`. Do you know when the `this.layer` will not be null?

**Comment by alexander-akait** [comment]
https://webpack.js.org/configuration/experiments/, `layers`, example from test https://github.com/webpack/webpack/tree/c181294865dca01b28e6e316636fef5f2aad4eb6/test/configCases/layer/rules

**Comment by randing89** [comment]
@alexander-akait Thanks for help I can reproduce the issue now. Here is the repo: https://github.com/randing89/github-brwfkb. I used `patch-package` to add a console log in `DeterministicModuleIdsPlugin.js`. After cloning the repo, execute `npm install && npm run build` in folder `a` and `b`. You can see webpack is assigning different module ids these 2 runs. However the code is exactly the same in those folders.

![image](https://user-images.githubusercontent.com/640557/129932797-c3eed8ff-1317-4d8c-93ca-48ff598669c4.png)

**Comment by alexander-akait** [comment]
Thanks

**Comment by randing89** [comment]
@alexander-akait Thanks! I also updated the ticket with the result of webpack 5.33.2
