### ISSUE TITLE
config `module.generator.emit` is no longer available

### ISSUE THREAD

**Issue by Diablohu** [webpack/webpack#14022]
# Bug report

**What is the current behavior?**

It seems that in latest version (v5.50) the `emit` of global options for seperate generators ' (e.g. `module.generator.asset.emit` `module.generator['asset/resource'].emit`) is no longer available?

I tried changing my config to using config for seperate rules which worked fine.

I checked recent change logs and found nothing about this change. I assume it is a bug?

![image](https://user-images.githubusercontent.com/1946774/129949888-575c76d1-6cb8-4c87-9c6d-8bc39c06cf47.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

Add config `module.generator.asset.emit = false`. Webpack building process should encounter error.

**What is the expected behavior?**

Config `module.generator.asset.emit = false` `module.generator['asset/resource'].emit = false` should work and will not emit asset module files.

**Other relevant information:**
webpack version:  5.50.0
Node.js version: 14.16.0
Operating System: Windows 10 21H1
Additional tools:

**Comment by sokra** [comment]
The `asset/inline` module has no `emit` option. A data URI doesn't emit a file, so that's not something you can disable here.

**Comment by Diablohu** [comment]
> The `asset/inline` module has no `emit` option. A data URI doesn't emit a file, so that's not something you can disable here.

My bad.
Correction: The configuration for seperate asset module in global generator options, e.g. `module.generator.asset.emit` `module.generator['asset/resource'].emit`

**Comment by sokra** [comment]
> Correction: The configuration for seperate asset module in global generator options, e.g. `module.generator.asset.emit` `module.generator['asset/resource'].emit`

That is fine, but the error message state `asset/inline`, so you added the `emit` option to a module of type `asset/inline`

**Comment by alexander-akait** [comment]
Answered, feel free to feedback
