### ISSUE TITLE
Invalid configuration object

### ISSUE THREAD

**Issue by dxdleikai** [webpack/webpack#14029]
# Bug report
Invalid configuration object. Object has been initialized using a configuration object that does not match the API schema.
 - configuration has an unknown property '_assetEmittingPreviousFiles'. These properties are valid:
   object { bonjour?, client?, compress?, dev?, firewall?, headers?, historyApiFallback?, host?, hot?, http2?, https?, injectClient?, injectHot?, liveReload?, onAfterSetupMiddleware?, onBeforeSetupMiddleware?, onListening?, open?, openPage?, overlay?, port?, proxy?, public?, setupExitSignals?, static?, stdin?, transportMode?, useLocalIp? }
![image](https://user-images.githubusercontent.com/20314225/130054377-3c5c9e82-d9c4-40fb-b42c-85c0e5fba375.png)

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

**Comment by anshumanv** [comment]
Please update webpack-dev-server to v4 and webpack-cli to v4.8.0

**Comment by alexander-akait** [comment]
Answered, please use search before update
