### ISSUE TITLE
Dev server runtime breaks umd library export

### ISSUE THREAD

**Issue by janv** [webpack/webpack#14021]
# Bug report

**What is the current behavior?**

I'm trying to port the webpack setup for our UMD-compiled library to webpack 5.
Everything works so far, but I'm failing to set up liveReload.
Setting `target` to `web` and having the webpack runtime  in the main chunk leads to the export of the UMD module being undefined.

Following the compiler, I figured that the [JavascriptModulesPlugin adds a line](https://github.com/webpack/webpack/blob/main/lib/javascript/JavascriptModulesPlugin.js#L845) to the generated entry module for my library that shadows the `__webpack_exports__` variable.

The reason seems to be that in the order of modules, the module containing the webpack runtime comes after my own module. This seems a rather arbitrary reason for this setup to fail.

**If the current behavior is a bug, please provide the steps to reproduce.**

I created a repository with a minimal setup that exhibits the behavior at https://github.com/janv/webpack-hot-library

**What is the expected behavior?**

I would expect my main module to write its exports into the `__webpack_exports__` startup variable.
If this combination of runtime/hot-loader and umd-library output is not supported, I would expect some sort of error message or a hint in the documentation.

**Other relevant information:**
webpack version:  5.50
Node.js version: 
Operating System: 
Additional tools:

**Comment by alexander-akait** [comment]
Fixed in `webpack-dev-server@rc-1`, stable release will be today
