### ISSUE TITLE
NPE in FileSystemInfo

### ISSUE THREAD

**Issue by HitkoDev** [webpack/webpack#14028]
# Bug report

**What is the current behavior?**

~~Null pointer error~~ Error due to null object in `FileSystemInfo.getContextTimestamp`

**If the current behavior is a bug, please provide the steps to reproduce.**

Call `FileSystemInfo.getContextTimestamp` with an immutable path (immutable path prefixes are provided in `FileSystemInfo` constructor).

**What is the expected behavior?**

`_readContextTimestamp` (processor for `contextTimestampQueue`) returns `null` for immutable paths:

https://github.com/webpack/webpack/blob/bd7cb37f1c0d872cfff9fc27c7db52a25e1ba6a3/lib/FileSystemInfo.js#L3016-L3020

so the queue callback in `getContextTimestamp` should handle `entry` possibly being null: https://github.com/webpack/webpack/blob/bd7cb37f1c0d872cfff9fc27c7db52a25e1ba6a3/lib/FileSystemInfo.js#L1164-L1168

**Other relevant information:**
webpack version:  5.51.0
Node.js version: all
Operating System: all
Additional tools: N/A

**Comment by HitkoDev** [comment]
Related: https://github.com/webpack/webpack/pull/14019

**Comment by alexander-akait** [comment]
What is `Null pointer`? It is not Java

**Comment by HitkoDev** [comment]
> What is `Null pointer`? It is not Java

True, JavaScript has "nullable types" instead of "null pointers", and `typeof null === "object"`, so technically I should say "null object error" or "error due to null object". But perhaps enough nitpicking, let's focus on the fact that callback receives `null` and doesn't handle it.

**Comment by kandangit** [comment]
I have also this problem

FileSystemInfo.js:816
        if (entry.resolved !== undefined) return entry.resolved;
                 ^

TypeError: Cannot read property 'resolved' of null


This looks like a recent webpack update. (use webpack as a transitive dependency in my Node project).

**Comment by HitkoDev** [comment]
> This looks like a recent webpack update. (use webpack as a transitive dependency in my Node project).

It appeared in 5.51.0, so just downgrade to 5.50.0

**Comment by sokra** [comment]
Yep that is a bug. Could one of you give me a stack trace of that?

**Comment by HitkoDev** [comment]
> Yep that is a bug. Could one of you give me a stack trace of that?

```
TypeError: Cannot read property 'resolved' of null
    at getResolvedTimestamp (node_modules/webpack/lib/FileSystemInfo.js:816:12)
    at node_modules/webpack/lib/FileSystemInfo.js:1165:21
    at node_modules/webpack/lib/util/AsyncQueue.js:352:5
    at Hook.eval [as callAsync] (eval at create (node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (node_modules/tapable/lib/Hook.js:18:14)
    at AsyncQueue._handleResult (node_modules/webpack/lib/util/AsyncQueue.js:322:21)
    at node_modules/webpack/lib/util/AsyncQueue.js:305:11
    at node_modules/webpack/lib/FileSystemInfo.js:3100:5
    at Array.<anonymous> (node_modules/webpack/lib/FileSystemInfo.js:2960:13)
    at runCallbacks (node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:27:15)
```
