### ISSUE TITLE
IStats type definition is not compatible with that in TypeScript

### ISSUE THREAD

**Issue by perqin** [webpack/webpack#14036]
As [defined in TypeScript](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/fs/promises.d.ts#L611), the `fs.stat` in Node.js returns value of type `Stats | BigIntStats`. While in Webpack's type definition, the API `InputFileSystem.stat` [returns value of type `IStats`](https://github.com/webpack/webpack/blob/51637ae59b4ec8a7e38d4ecde22fee93f6176935/types.d.ts#L4356-L4382), which is not assignable to `Stats | BigIntStats`.

This becomes a problem for me. I'm using `fast-glob`, and its `sync` API offers an `fs` option. However, I can't assign the `LoaderContext.fs` to this option.

Is the `InputFileSystem` API wrongly typed in Webpack? And if this is the expected behavior, how could I adapt the `InputFileSystem` API to NodeJS's `fs` API?

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
