### ISSUE TITLE
Automatically trigger verbose stats when using `--profile`

### ISSUE THREAD

**Issue by fregante** [webpack/webpack#14046]
## Feature request

The flags `--progress --profile` explicitly tell webpack to produce a detailed output but instead the output is clipped with `+ 243 hidden lines`

**What is the expected behavior?**

It makes no sense to clip the output I just requested, so those two flags should imply `--stats verbose`

**What is motivation or use case for adding/changing the behavior?**

It might just be me, but this makes me incredibly frustrated. I found the flag to do what I want and **it does not work.** It doesn't help that the problem isn't Googlable and I had to open https://github.com/webpack/webpack/discussions/14016

**How should this be implemented in your opinion?**

A new default automatic behavior

**Comment by alexander-akait** [comment]
`--progress` shows percents,
`--profile` for profiling using webpack itself
`--stats verbose` for stats

it is very different flags...

**Comment by fregante** [comment]
Say what you want about their specific intent, but if I request `--profile` and the answer is `243 lines hidden` then this flag is broken.

I removed mentions of `--progress`.

Also this is not a question but a change request (or more appropriately an intentional bug, as far as webpack users are concerned)

**Comment by alexander-akait** [comment]
But you can use `--profile` and avoid output stats, I don't understand what is the problem with `--stats verbose`

**Comment by fregante** [comment]
> I don't understand what is the problem with `--stats verbose`

I don't know what `--stats verbose` is, I had to go on a forum and be told from the project maintainer. As far as I'm concerned, that's `--stats` is completely unrelated from `--profile`, yet it's required for `--profile` to work.

Could webpack be smarter about "we're capturing profiling information but there's no output"?

**Comment by alexander-akait** [comment]
`--stats` for output staticis about build, i.e. time/entries/etc, i.e.:
```
asset bundle.mjs 6.02 KiB [compared for emit] [javascript module] (name: main)
runtime modules 2.8 KiB 4 modules
./foo.mjs 43 bytes [built] [code generated]
webpack 5.51.1 compiled successfully in 53 ms
```
`--profile` for profiling using webpack itself, i.e. time spent on loaders/plugins/actions inside webpack

**Comment by sokra** [comment]
Verbose will print a lot information, when you have many modules. The idea is that profiling only prints expensive modules by default, because that's what you care about.

**Comment by fregante** [comment]
Profiling means I want to know what's going on in detail, in my mind. 4 lines aren't enough of a profile if my intent is improving the performance of my build.

**Comment by sokra** [comment]
By default it will print:
* a single module when it took more than 200ms to compile
* a loaders combination when all modules that are compiled by them took more than 200ms in total

Isn't that enough to find the problems?
