### ISSUE TITLE
Type ResolvePluginInstance is not exported

### ISSUE THREAD

**Issue by harelmo** [webpack/webpack#14045]
`ResolvePluginInstance` is exported here:
https://github.com/webpack/webpack/blob/514ecd0490c9dc98dea5cebb2ab5c0ae1ca1016d/declarations/WebpackOptions.d.ts#L1622
but not here:
https://github.com/webpack/webpack/blob/c61466e43895f84ff56fb98e69cbe3f3e19f47c2/types.d.ts#L9282
so it cannot be publicly used in extending classes (like we have in our project).

**Comment by alexander-akait** [comment]
Close in favor https://github.com/webpack/webpack/issues/11630, please always use the issue template and search before posting, please clarify why you need this types publicly here https://github.com/webpack/webpack/issues/11630
