### ISSUE TITLE
Using jQuery global in browser's console with webpack-ed code.

### ISSUE THREAD

**Issue by littlee** [webpack/webpack#1404]
I include the file packaged in my html file;
```html
<script src="bundle.js"></script>
```
and I require jquery in the entry file
```js
require('jquery')
```
and when I type `jQuery` in chrome's console, it cause an error:

![jj](https://cloud.githubusercontent.com/assets/7534668/9574454/bc58a90c-4ff9-11e5-81a9-a4251052c8c9.png)

Because I want to use console to do some quick test. Like
```js
// to quickly know the number of some elements inside console
$('li').length
```
Is there any way I can reference jQuery in console while using to code I packaged?

**Comment by iamstarkov** [comment]
why are you including jquery twice?

**Comment by littlee** [comment]
I didn't.
I require jquery in entry file.
And I include bundle.js(webpack generated file) in html.
And I want to use jQuery in browser's console to do some quick test. How can I do this?

**Comment by iamstarkov** [comment]
What does network tab tell you?

**Comment by littlee** [comment]
![net](https://cloud.githubusercontent.com/assets/7534668/9595061/8ae068f4-5096-11e5-9951-ee976387ff10.png)

**Comment by sokra** [comment]
This is working as intended. The bundle shouldn't leak to the environemnt. Explicitly expose jQuery either with the `output.library` option or the `expose-loader`.

**Comment by SpaceK33z** [comment]
When debugging I often expose a module temporarily to `window` to test it. So like this:
```js
window.jQuery = require('jquery');
```

**Comment by littlee** [comment]
@SpaceK33z 
Where should I put this code in `window.jQuery = require('jquery');`?
I tried webpack.config.js
but get an error:
```
window.jQuery = require('jquery');
^
ReferenceError: window is not defined
```

**Comment by SpaceK33z** [comment]
This code would be in the entry file, where you also put the other `require('jquery')`.

**Comment by bilalghouri** [comment]
can anyone please post a solution to this? also facing the same issue.
