### ISSUE TITLE
outputFileSystem.readFile behaves differently than its documented type and for Stats | BigIntStats

### ISSUE THREAD

**Issue by harelmo** [webpack/webpack#14048]
# Bug report

**What is the current behavior?**

Using `outputFileSystem.readFile` with an `encoding` argument is valid and applies the given encoding over the read content, even though the type definition for it states otherwise: 

https://github.com/webpack/webpack/blob/c61466e43895f84ff56fb98e69cbe3f3e19f47c2/types.d.ts#L8189

**If the current behavior is a bug, please provide the steps to reproduce.**

For example, running this code returns the output file's content as a UTF-8 string, and changing the `utf8` argument to `hex` affects the output's encoding as well:

```js
const path = require("path");
const webpack = require("webpack");

const wp = webpack({
  context: path.resolve(__dirname),
  entry: "./entry.js",
  output: {
    path: path.resolve(__dirname, "dist"),
  },
});

wp.run((err, stats) => {
  wp.outputFileSystem.readFile("./dist/main.js", "utf8", (e, content) => {
    console.log(content);
  });
});

```
**What is the expected behavior?**

The `readFile` function should have to typed overloads:
```
	readFile: (
		arg0: string,
        arg1: <possible encoding values>
		arg2: (arg0?: null | NodeJS.ErrnoException, arg1?: string | Buffer) => void
	) => void;
```
and the existing defintion:
```
	readFile: (
		arg0: string,
		arg1: (arg0?: null | NodeJS.ErrnoException, arg1?: string | Buffer) => void
	) => void;
```

**Other relevant information:**

webpack version: 5.51.1
Node.js version: 14.17.0
Operating System: maOS Big Sur 11.4

**Comment by alexander-akait** [comment]
Feel free to send a PR

**Comment by sokra** [comment]
That would be a breaking change...

**Comment by sokra** [comment]
You can provide a custom filesystem which doesn't have to support these undocumented calling variants of these methods. Currently that's fine, but changing the typings would make that invalid.

The filesystem caching would also be a little bit sad if you use the encoding argument as it's only caching calls and doesn't convert between encoding.

**Comment by harelmo** [comment]
@sokra I see, thanks for clearing that out 👍 
Closing this, as it's probably more of a `memfs` thing (which is the FS I used in my case) that needs to be sorted out.
