### ISSUE TITLE
Add an error getter to ModuleBuildError

### ISSUE THREAD

**Issue by harelmo** [webpack/webpack#14049]
## Feature request

**What is the expected behavior?**

[ModuleBuildError](https://github.com/webpack/webpack/blob/c181294865dca01b28e6e316636fef5f2aad4eb6/lib/ModuleBuildError.js#L55) would expose an `error` getter, to allow access to the inner error it wraps

**What is motivation or use case for adding/changing the behavior?**

On some occasions, we'd like to access the inner error and use several properties of it, without relying on its message that's concatenated to WebPack's `ModuleBuildError`.

**How should this be implemented in your opinion?**

By adding a simple getter to the class:

```js
get error() {
   return this.error;
}
```

**Are you willing to work on this yourself?**

Yes.

**Comment by alexander-akait** [comment]
No need to implement getter, please use `error.error`

**Comment by harelmo** [comment]
@alexander-akait thanks for clarifying this. My intent is that an internal field would not be accessed directly, potentially breaking code using the field directly if the implementation changes in the future.
If that's not a concern, I guess it just needs to be added to the type-definition of `ModuleBuildError`. 
Makes sense?

**Comment by sokra** [comment]
It should be already part of the type definition in `WebpackError` which is the base class
