### ISSUE TITLE
Download external resources

### ISSUE THREAD

**Issue by saulshanabrook** [webpack/webpack#1405]
Is it possible for tell webpack to download and parse external URL's when building?

For example in my css file I import the roboto font:

```css
@import url(https://fonts.googleapis.com/css?family=Roboto:400,700)
```

Currently when someone goes to my site, it makes an external request to that URL when it loads, which both breaks offline access (say someone is using my site only on a local network and have no internet access) and potentially slower they have to download a separate resource.

Can I get webpack to inline all external URLs?

**Comment by bebraw** [comment]
Currently [css-loader](https://www.npmjs.com/package/css-loader) resolves imports like that but I can't see support for downloads like that. Perhaps it would be possible to implement a loader that would do what you need (maybe one exists already, look around).

**Comment by saulshanabrook** [comment]
OK I'll close this then, since it seems like it could resolved with an external library.
