### ISSUE TITLE
[Question]Will Webpack support CSS module scripts?

### ISSUE THREAD

**Issue by AkifumiSato** [webpack/webpack#14063]
It seems that Chrome implements `CSS module scripts` which imports CSS using import assertion.
https://web.dev/css-module-scripts/
```js
import sheet from './styles.css' assert { type: 'css' };
document.adoptedStyleSheets = [sheet];
shadowRoot.adoptedStyleSheets = [sheet];
```

This seems to have different specifications than when using css-loader.
I'm wondering if I need to be aware of the difference between css-loader and `CSS module scripts` in the future.
```js
// CSS module scripts
import sheet from './styles.css' assert { type: 'css' };
// with css-loader
import sheet from './styles.css';
```
Are there any plans to support this on the Webpack side?
Is this a problem that another library should address?

**Comment by sokra** [comment]
Yes, we want to support that, but no plans have been made to implement it yet

**Comment by alexander-akait** [comment]
@AkifumiSato 

> I'm wondering if I need to be aware of the difference between css-loader and CSS module scripts in the future.

We can improve css-loader and have the same behavior

**Comment by alexander-akait** [comment]
@AkifumiSato Anyway what is the problem with `css-loader`?

**Comment by AkifumiSato** [comment]
> Anyway what is the problem with css-loader and import sheet from './styles.css' assert { type: 'css' };?

Import results are different for `css-loader` and `css module script`.
```js
// CSS module scripts
import sheet from './styles.css' assert { type: 'css' };
console.log(sheet instanceof CSSStyleSheet) // true

// with css-loader
import sheet from './styles.css';
console.log(sheet instanceof CSSStyleSheet) // false, `sheet` is Record<string, string>.
```

My understanding is that if you import it with `css module script`, it will not be available for className of ReactElement.
```css
/* index.css */
.title {
  font-size: 20px;
}
```

```jsx
import React from 'react'
import styles from './index.css' assert { type: 'css' }

export const Title: React.FC = ({ children }) => (
  // `styles.title` is undefined.
  <h1 className={styles.title}>{children}</h1>
)
```

**Comment by alexander-akait** [comment]
hm, we can fix it, if `assert { type: "css" }` setted we can return `CSSStyleSheet`

**Comment by alexander-akait** [comment]
And you can use classes as named export https://github.com/webpack-contrib/css-loader#namedexport

**Comment by AkifumiSato** [comment]
> hm, we can fix it, if assert { type: "css" } setted we can return CSSStyleSheet

With the support of `css module script`, I think it's difficult for users to be aware that the return value changes depending on the presence or absence of `assert {type:'css'}`, but can't it be helped?
For example, how about implementing an assert that returns a record similar to css-loader, such as `assert {type:" cssModules "}`?

**Comment by alexander-akait** [comment]
Yep, we can improve this too, it is not hard

**Comment by AkifumiSato** [comment]
@alexander-akait thx a lot!
Should I keep this issue open?

**Comment by alexander-akait** [comment]
Yep, first we improve css-loader, then in future we will move logic inside webpack core

**Comment by sokra** [comment]
`assert` handling is already in the core. You can do that:

``` js
module.rules: [ {
  test: /\.css$/,
  oneOf: [
    { assert: { type: "css" }, loader: "css-loader", options: { exportStylesheet: true } },
    { loader: "css-loader", options: { exportStylesheet: false } }
  ]
} ]
```

**Comment by alexander-akait** [comment]
@AkifumiSato https://github.com/webpack-contrib/css-loader/pull/1368

**Comment by AkifumiSato** [comment]
@alexander-akait It looks like the fix is complete, should I close the Issue?

**Comment by vankop** [comment]
bump

**Comment by alexander-akait** [comment]
let's close in favor https://github.com/webpack/webpack/issues/14893
