### ISSUE TITLE
Support Trusted Types in EvalSourceMapDevToolPlugin

### ISSUE THREAD

**Issue by tosmolka** [webpack/webpack#14075]
## Feature request

**What is the expected behavior?**

Say webpack is configured with _[output.trustedTypes](https://webpack.js.org/configuration/output/#outputtrustedtypes) = true_ and _[devtool](https://webpack.js.org/configuration/devtool/#devtool) = "eval-cheap-module-source-map"_. I expect that generated code can still use `eval` but the script will be created using [createScript](https://w3c.github.io/webappsec-trusted-types/dist/spec/#dom-trustedtypepolicy-createscript) method from Trusted Types policy. 

**What is motivation or use case for adding/changing the behavior?**

This is needed when working with Trusted Types during local development. Passing `string` argument into `eval()` is forbidden when you enforce `require-trusted-types-for 'script'` CSP directive. This is exactly what `EvalSourceMapDevToolPlugin` is doing and therefore it is hard to debug such application locally. 

**How should this be implemented in your opinion?**

We could probably follow similar approach as with `CreateScriptUrlRuntimeModule` and based on whether trusted types are enabled or not return either raw string or output of `policy.createScript()`. This value can then be passed to `eval()`. 

**Are you willing to work on this yourself?**
yes

**Comment by alexander-akait** [comment]
Yep, PR welcome

**Comment by tosmolka** [comment]
@alexander-akait , could you please review the PR for me? Thanks.

**Comment by tosmolka** [comment]
Hello @alexander-akait , any update on the PR? Thanks.

**Comment by tosmolka** [comment]
@alexander-akait , @sokra , can we pls get a feedback on https://github.com/webpack/webpack/pull/14173? Happy to change the approach if you have any suggestions. Thank you.

**Comment by alexander-akait** [comment]
Fixed https://github.com/webpack/webpack/pull/14173
