### ISSUE TITLE
Error handling on doBuild resulting in an error

### ISSUE THREAD

**Issue by ChrisSG** [webpack/webpack#14071]
Shouldn't the error be passt as an argument to the callback here?

https://github.com/webpack/webpack/blob/4e5e0aca41f0efaf7466c512095295421f17e4d5/lib/NormalModule.js#L925

I had no clue that ts-loader was failing because the compilation finished without errors but not parsing any file...

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

We can't say that is the problem without example of the problem
