### ISSUE TITLE
SVG referenced in CSS is being chunked for some reason

### ISSUE THREAD

**Issue by neil-morrison44** [webpack/webpack#14076]
# Bug report

**What is the current behavior?**

- I'm updating from Webpack 4 to Webpack 5.
- I've got an image that's referenced from SCSS in a `background-image` property
- the image is in my app code at `../images/icon.svg` (relative to the main scss file)

For some reason webpack appears to be attempting to put the svg into its own `08091391c9c753ed62a1.svg` chunk like

```js
module.exports = __webpack_public_path__ + "icon.de13c92715e9ed451af2bca25ee38006.svg";
```

which obviously `background-image` can't deal with.

This happens in both `webpack-dev-server` watch & regular builds.

**If the current behavior is a bug, please provide the steps to reproduce.**

I can't provide a public repo for this so I'll go through my setup the best I can...

scss / css / sass files should be being run through `"sass-loader"` -> `"postcss-loader" ("postcss-preset-env")` -> `"css-loader"` -> `"style-loader"` with no options set other than `postcss-preset-env` (can remove `postcss-loader` though and the issue persists)

There's no loaders set up for SVG files so that'll just be default.

`optimization.splitChunks` is set to
```js
        chunks: "all",
        minChunks: 3,
        maxSize: 30e6,
```

(but removing it doesn't fix the issue)

I've not got any other plugins installed related to sass, chunking, or SVGs.

Let me know what else might be helpful and I'll do my best to provide it.

**What is the expected behavior?**

The SVG is passed as a normal direct-to-svg relative URL to `background-image` the same way it was with Webpack 4 with the same config.

**Other relevant information:**
webpack version:  v5.51.1
Node.js version: v14.16.1
Operating System: docker image based on `FROM buildpack-deps:buster-curl`
Additional tools: N/A

**Comment by sokra** [comment]
It looks like you handling assets twice. Maybe with `file-loader` and via `type: "asset`.

You could try to remove the `file-loader` rule or add `dependency: { not: ["url"] }` to that rule

**Comment by alexander-akait** [comment]
Answered, you can find the same issue in `css-loader`

**Comment by neil-morrison44** [comment]
Can confirm that swapping the `file-loader` for Resource Assets https://webpack.js.org/guides/asset-modules/#resource-assets got it working again.

Had a look but I couldn't find which issue in `css-loader` was relevant
