### ISSUE TITLE
module.exports is empty when using require.resolve

### ISSUE THREAD

**Issue by ensconced** [webpack/webpack#14078]
# Bug report

See [minimal repro](https://github.com/ensconced/webpack-issue-repro). With `mode: 'production'`, when including an ES module by using `require.resolve`, and then executing using `__webpack_require__`, the received `module.exports` object is empty.

Setting `mode: 'development'` or `optimization: { usedExports: false }` fixes the issue.

# Expected behavior

All exports are included, as with `mode: 'development'`.

**Other relevant information:**
webpack version:  5.51.1. The issue is present since 5.0.0.
Node.js version: v14.17.5
Operating System: macOS Big Sur

**Comment by alexander-akait** [comment]
You should not use `__webpack_require__` in such way, it is internal function

https://webpack.js.org/api/module-variables/#__webpack_require__-webpack-specific

> The raw require function. This expression isn't parsed by the Parser for dependencies.

So `foo.js` marked as unused and dropped

**Comment by ensconced** [comment]
I appreciate that `__webpack_require__` is not parsed for dependencies, but `require.resolve` should be, right? The docs for `require.resolve` say: "The compiler will ensure that the dependency is available in the output bundle".  Am I misunderstanding?

**Comment by alexander-akait** [comment]
Yep, but it is analyze only module, not module exports

**Comment by ensconced** [comment]
Sorry but I don't understand - in this case `__webpack_require__(moduleId)` just gives an empty object. If that is correct behaviour, then what is meant by "The compiler will ensure that the dependency is available in the output bundle"?

**Comment by alexander-akait** [comment]
here bottleneck, using `require.resolve` is not analyzable, so using `__webpack_require__` will drop unused exports (in your case it is all exports), in theory wen can mark module in `require.resolve` as non tree shackable , but you will get all module without optimizations and it is bad, why do not use `require` with `try/catch`?

**Comment by joe-barnett** [comment]
I'm not sure how `require`/`import()` with `try/catch` would help me here. My aim is to include the entire module in the bundle, but to defer the actual module execution until later. I now have this working using `require.resolve` and `__webpack_require__`. I was just a little surprised that it was necessary to set `unusedExports: false` to make it work.

**Comment by ensconced** [comment]
I'm not sure how `require`/`import()` with `try/catch` would help me here. My aim is to include the entire module in the bundle, but to defer the actual module execution until later. I now have this working using `require.resolve` and `__webpack_require__`. I was just a little surprised that it was necessary to set `unusedExports: false` to make it work.

**Comment by alexander-akait** [comment]
>  I was just a little surprised that it was necessary to set unusedExports: false to make it work.

Because when you don't have `require`/`import` we don't know which exports do you use from your package, so webpack drop them all, you can use:
```
let myMod;

try { 
 // `await import()`
  myMod = require("something");
} catch (error) {
  // Logic to handle error
}

Again, `require.resolve` just mark you need module in bundle, but because you don't have any export, webpack drop them, also you use `require.resolve` with ECMA module, it is wrong and invalid, change it on commonjs
