### ISSUE TITLE
[HMR] hot mod config issue

### ISSUE THREAD

**Issue by hussion** [webpack/webpack#1407]
if i use `webpack-dev-server --content-base build/ --hot --line`, it works. But if i use by `webpack.config.js`,

like this: 
```
devServer: {
        contentBase: "./build",
        hot: true,
        inline: true
}
```

it does not works. and the browser throws a error: `Uncaught Error: [HMR] Hot Module Replacement is disabled.`

**Comment by vramana** [comment]
@hussion You need to add `webpack/hot/dev-server` in your entry point. See this http://webpack.github.io/docs/webpack-dev-server.html#hot-mode
