### ISSUE TITLE
Npm install error

### ISSUE THREAD

**Issue by nilveryawesome** [webpack/webpack#1408]
node -v
v0.12.7
npm -v
2.11.3

npm ERR! install trying to install 3.0.2 to /node_modules/webpack/node_modules/watchpack/node_modules/chokidar/node_modules/anymatch/node_modules/micromatch/node_modules/parse-glob
npm ERR! install but already installed versions [ '3.0.2' ]

**Comment by sokra** [comment]
I cannot help you with this information...

**Comment by bebraw** [comment]
Closing as there's not enough info. Please open again if you can repro.
