### ISSUE TITLE
Module Federation with Library Type Module (ESM) is not working

### ISSUE THREAD

**Issue by saravanan10393** [webpack/webpack#14111]
# Bug report

**What is the current behavior?**
When setting 
```  
    new ModuleFederationPlugin({
      name: "app1",
      filename: "remoteEntry.js",
      library: {
        type: "module"
      },
      remotes: {
        app2: "http://127.0.0.1:3002/remoteEntry.js",
      },
      exposes: {
        "./Button": "./src/Button",
      }
    })
```
in module federation plugin config, the generate remote entry is not exporting anything. Or simply saying, consuming remote is not working.

**If the current behavior is a bug, please provide the steps to reproduce.**

(https://github.com/saravanan10393/mf-es-module)[Here is the reproduce repo] also (https://gist.github.com/saravanan10393/8185ef0a3e56f9419bbc5a299815aad4)[here is the generated removeEntry of app1.]

**What is the expected behavior?**
The remoteEntry with ESM target support is needed.

**Other relevant information:**
webpack version:  5.51.1
Node.js version: 14
Operating System:  Mac
Additional tools:

**Comment by saravanan10393** [comment]
@sokra any idea on this

**Comment by ckken** [comment]
i fine when use es5 
![image](https://user-images.githubusercontent.com/3890513/140748835-51fe945c-30d5-46cc-bd46-c054c0b24e20.png)
is work, when use ES2015 
![image](https://user-images.githubusercontent.com/3890513/140748993-8fc162e6-0f8e-4fbe-8f4d-d473c59da3bb.png)
the library is change~ and load failed

**Comment by rakshans1** [comment]
@ckken Try setting library.type to `window`

```
    new ModuleFederationPlugin({
      name: 'app',
      filename: 'remoteEntry.js',
      remotes: {},
      exposes: {
        './App': './app.js',
      },
      shared: sharedDependencies,
      library: {
        type: 'window',
        name: 'app',
      },
    }),
```

**Comment by alexander-akait** [comment]
Fixed https://github.com/webpack/webpack/pull/14827

**Comment by ckken** [comment]
no work also in 5.64.4 when build bundle

**Comment by alexander-akait** [comment]
Please create reproducible test repo

**Comment by ckken** [comment]
Are there any simple demos? My cases are more complex

**Comment by ckken** [comment]
Maybe I set it wrong

**Comment by alexander-akait** [comment]
That is why I asked repo, you do not need to provide the entire project, cut it to reproduce repo

**Comment by ckken** [comment]
https://github.com/saravanan10393/mf-es-module it work! thanks

**Comment by alexander-akait** [comment]
It works with ESM? So I don't need to check it?

**Comment by ckken** [comment]
![mmexport1637917597941](https://user-images.githubusercontent.com/3890513/143558401-4682965c-97e3-4f6e-8a7a-2601042583b8.png)
work well!

**Comment by erickbelfy** [comment]
Is there a place or documentation where I can see all the library types? I'm passing through the same problem above, with same configuration, but I  can't find a place where there's a detailed explanation of library types.

**Comment by alexander-akait** [comment]
You can open an issue in our docs and we will try to improve

**Comment by wibed** [comment]
i still expirience this issue:

reference to reproduction,
https://github.com/module-federation/module-federation-examples/issues/3108
