### ISSUE TITLE
Conditional sourcemaps?

### ISSUE THREAD

**Issue by dallonf** [webpack/webpack#1411]
The current biggest bottleneck in my build time is in generating sourcemaps. But it seems to me like I don't want to use the same strategy throughout the whole app - namely, it would make a lot of sense to use `eval` or `cheap-eval-source-map` on anything under `node_modules` because I know I'm not running any transforms on that content and don't particularly care about the original source. Meanwhile, I'd like to use `inline-source-map` or `eval-source-map` for all of my own code. 

If there isn't a way to do this already that I'm missing, I think it would be very useful and speed up the development process significantly!

**Comment by sokra** [comment]
You can decide on file-level, but not in module level.

**Comment by dallonf** [comment]
Not sure I understand the response. Do you mean configurable by output file? In that case, is it possible to set everything from node_modules to be part of a different output file with a different `devtool` setting?

**Comment by brenoc** [comment]
@dallonf, what @sokra is saying is that you can exclude files from generating sourcemaps. 

You should remove the `devtool` option from your config and use SourceMapDevToolPlugin instead.

An example of how you could achieve what you want is to create a separate entry point for you vendor modules and exclude its sourcemap.

Example:
```js
{
  entry: {
    'main': './src/index.js',
    'vendor': [
      'react',
      'react-dom'
    ]
  },

  plugins: [
    new webpack.optimize.CommonsChunkPlugin({
      name: ['vendor'],
      minChunks: Infinity
    }),
    new webpack.SourceMapDevToolPlugin({
      filename: '[file].map',
      exclude: ['vendor.js']
    })
  ]
}
```

**Comment by bebraw** [comment]
Just realized @brenoc's answer covers this nicely. Closing. :+1:
