### ISSUE TITLE
Missing docs for `devserver.public` path for webpack 5x

### ISSUE THREAD

**Issue by FullStackForger** [webpack/webpack#14116]
Getting dev server to work with proxy using below configuration works as expected.
```
{
  // ...
  devServer: {
    public: 'localhost:9000'
  }
}
```
Snippet was created based on [documentation](https://v4.webpack.js.org/configuration/dev-server/#devserverpublic) for 4x. 
Documentation for `devserver.public` is missing.

**Comment by alexander-akait** [comment]
Nope, it is not missing and described here https://github.com/webpack/webpack-dev-server/blob/master/migration-v4.md, it was removed

**Comment by alexander-akait** [comment]
> public, sockHost, sockPath, and sockPort options were removed in favor client.webSocketURL option:

**Comment by FullStackForger** [comment]
Thanks Alexander! I have missed it. Much appreciated.
