### ISSUE TITLE
Ionic and Webpack cannot find module Cannot find module './ion-app_8-md.entry.js'

### ISSUE THREAD

**Issue by zombieleet** [webpack/webpack#14123]
# Bug report

**What is the current behavior?**
Webpack fails to load ionic modules. As displayed in the below screenshot

<img width="1055" alt="Screenshot 2021-09-02 at 21 22 05" src="https://user-images.githubusercontent.com/14893363/131910927-d74005d9-5178-46be-a89b-0c8c9b222a81.png">

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
The expected behavior is for webpack to properly load this modules, since they are located in the directory webpack is looking for them.

On checking `./../node_modules/@ionic/core/dist/esm-es5` the files webpack is trying to load are load located there, but what seems very weird to me is , after following the stack trace and trying to see what causing the issue, I saw this line of code in webpack  which was why I decided to ask for help.
`webpackEmptyAsyncContext.id = "../../node_modules/@ionic/core/dist/esm-es5 lazy recursive ^\\.\\/.*\\.entry\\.js$ include: \\.entry\\.js$ exclude: \\.system\\.entry\\.js$";` ,

below is my webpack config file

```javascript

module.exports = {
  entry: './src/main.tsx',
  devtool: 'inline-source-map',
  devServer: {
    hot: true,
    host: 'localhost',
    port: 3000,
    proxy: {
      '/api': {
        target: 'http://localhost:5000/',
        secure: false,
        changeOrigin: true
      }
    }
  },
  module: {
    rules: [
      {
        test: /.*\.ts(|x)$/,
        use: 'ts-loader',
        exclude: /node_modules/
      },
      {
        test: /\.svg$/,
        use: ['@svgr/webpack'],
      },
      {
        test: /.*\.(js|jsx)$/,
        exclude: /node_modules/,
        resolve: {
          extensions: [".js", ".jsx"]
        },
        use: {
          loader: "babel-loader",
          options: {
            presets: [
              '@babel/preset-env',
              '@babel/preset-react'
            ]
          }
        }
      },
      {
        test: /\.s[ac]ss$/i,
        use: [
          "style-loader",
          "css-loader",
          "sass-loader",
        ],
      },
      {
        test: /\.css$/i,
        use: ["style-loader", "css-loader"],
      },
    ]
  },
  resolve: {
    extensions: ['', '.js', '.jsx', '.ts', '.tsx'],
    modules: [path.resolve(__dirname, 'src'), 'node_modules', '../../node_modules'],
    plugins: [new TsconfigPathsPlugin({ configFile: "./tsconfig.json" })]
  },
  output: {
    filename: '[name].[contenthash].js',
    path: path.resolve('./', 'public'),
    clean: true
  },
  plugins: [
    new HtmlWebpackPlugin({
      template: path.join(__dirname, 'public', 'index.html'),
    }),
    new NodePolyfillPlugin()
  ]
};

```

**Other relevant information:**
webpack version:  5.47.1
Node.js version: 14.16.1
Operating System:  osx 
Additional tools:
ionic v5

**Comment by alexander-akait** [comment]
Sorry, not related to webpack, please report to `@ionic`

**Comment by alexander-akait** [comment]
And never ignore `**If the current behavior is a bug, please provide the steps to reproduce.**`, otherwise you will not get verbose help
