### ISSUE TITLE
Filenames normalisation

### ISSUE THREAD

**Issue by artola** [webpack/webpack#14137]
I have upgraded from v4 to v5 and found a problem with the code using `babel-plugin-relay`, affecting only Windows.
I have created a repo an I can see that it happens with or without TS (ts-loader), but might be similar to https://blog.johnnyreilly.com/2021/04/20/ts-loader-goes-webpack-5/
I guess that might be solved re-writting in the loader but should not be done in the babel-plugin else it should work differently in each environment.

@sokra I would appreciate your feedback, about how/where to proceed on this issue: [relay]( https://github.com/facebook/relay/issues/3272#issuecomment-911654887)

**Comment by alexander-akait** [comment]
Sorry, we can't control external code and I don't think you have the same problem
