### ISSUE TITLE
Are DefinePlugin and jshint-loader incompatible?

### ISSUE THREAD

**Issue by rondonjon** [webpack/webpack#1413]
Given: the following minimal test module:
```
   module.exports = __DEF__;
```

Given: the following plugin configuration for webpack:
```
   plugins: [ new webpack.DefinePlugin({ "__DEF__": "hi there" }) ]
```

Given: the following preloader:
```
   {
      test: /\.js$/,
      exclude: /node_modules/,
      loader: "jshint-loader"
}
```

__Expected result:__ the DefinePlugin replaces `__DEF__` with `"hi there"`, and jshint has nothing to complain about.

__Actual result:__ jshint-loader reports `W117 '__DEF__' is not defined.`

__Note:__ moving the jshint-loader into the loaders or the postLoaders makes no difference. Apparently the jshint-loader is always invoked before the DefinePlugin gets to work. The reason may be in the design of both extensions, but the combination of definitions and hinting is certainly not rare in development environments, and it would be helpful if they worked better together.

__Question:__ I don't fully understand the DefinePlugin implementation, but couldn't the DefinePlugin listen to a different event that is fired BEFORE all loaders have been invoked, __or__ at least before the postLoaders are invoked (with jshint-loader being used as a postLoader, although it sure wasn't intended as such)?

**Comment by sokra** [comment]
DefinePlugin runs after all loaders, because it extends the webpack parser.

**Comment by phdesign** [comment]
You could add 
```
"globals": {
  "__DEF__": true
}
```
to `.jshintrc` or `.eslintrc`.
