### ISSUE TITLE
WebPack stop minifying inline JavaScript after encountering handle bar template syntax

### ISSUE THREAD

**Issue by TechMaster** [webpack/webpack#14143]
# Bug report

I use Go HTML template in a server side rendering web project. In a HTML view template, I have some inline JavaScript code.

- When there is no template variable assignment in JavaScript (pure inline JavaScript), WebPack can optimize correctly.
- When I assign template variable to a variable in JavaScript (inline JavaScript mixed with template), WebPack does not optimize any more.

**What is the current behavior?**
Before minimizing
```js
<script>
    let foo = {{ Foo }}
    function factorialize(num) {
      if (num < 0)
        return -1;
      else if (num == 0)
        return 1;
      else {
        return (num * factorialize(num - 1));
      }
    }
    factorialize(5);
</script>
```

After minizing: WebPack stops minifying after encountering `{{ Foo }}`
```javascript
<script>let foo = {{ Foo }}
    function factorialize(num) {
      if (num < 0)
        return -1;
      else if (num == 0)
        return 1;
      else {
        return (num * factorialize(num - 1));
      }
    }
    factorialize(5);</script>
```
**steps to reproduce.**
Include inline JavaScript with view template syntax Handle Bar or Go HTML template then run
```
yarn build
```
Check output HTML file in dist folder

**What is the expected behavior?**
WebPack should ignore template syntax and optimize whole inline JavaScript code
```js
<script>let foo = {{ Foo }} function factorialize(i){return i<0?-1:0==i?1:i*factorialize(i-1)}factorialize(5)</script>
```

**Other relevant information:**
webpack version:  ^5.44.0
Node.js version: 16.5.0
Operating System: MacOSX 10.13.6

**Comment by alexander-akait** [comment]
Sorry, not related to webpack, we don't compress HTML (maybe you use `html-webpack-plugin`), and yes it is wrong syntax, so minimizer can't handle it
