### ISSUE TITLE
aliases in webpack.config.ts not resolved

### ISSUE THREAD

**Issue by eng-dibo** [webpack/webpack#14149]
webpack allows to write the config file with typescript, however it may contain alias paths that needed to be resolved to its mapped paths.

note that I am talking here about thecfile `webpack.config.ts` itself, not other `.ts` files

paths already defined in tsconfig.json and work well with `tsc` command.

even if you temporary used the real paths in `webpack.config.ts` file, it still complains of alias paths that these real paths request.

how to use aliases in a webpack config file?

**Comment by sokra** [comment]
webpack is using https://github.com/TypeStrong/ts-node to run a `webpack.config.ts` file. You need to look there.

**Comment by eng-dibo** [comment]
ok, so how to provide `ts-node` configs (i.e paths) to webpack to use it when compiling `webpack.config.ts`?
@sokra

**Comment by eng-dibo** [comment]
I set `module` to `commonjs`
running `ts-node webpack.config.ts` runs successfully, but `webpack --config=webpack.config.ts` fails with the shown error in the issue description
