### ISSUE TITLE
Output name handling with multiple entry points

### ISSUE THREAD

**Issue by WhackoJacko** [webpack/webpack#1414]
Having config like:

entry: {
        header_basket: './header-basket/main.jsx',        
        basket: './basket/main.jsx'
    },
    output: {
        path: path.join(process.env['HOME'], 'project/js/'),
        filename: '[name].js',
        sourceMapFilename: '[name].map',
        libraryTarget: 'var',
        library: '[name]'
    }

I want webpack to build bundles with names 'header_basket' and 'basket', but libraries names should be in CamelCase. Is it possible?

**Comment by sokra** [comment]
Nope. Sorry.
