### ISSUE TITLE
webpack doesn't respect `ts-node` options

### ISSUE THREAD

**Issue by eng-dibo** [webpack/webpack#14157]
I am trying to write `webpack.config` file in typescript

I set my `tsconfig.json` file to use `module: es2020` but override it for `ts-node` only which `webpack` uses to compile webpack config files written in typescript, i.e: `webpack.config.ts` to be `module: commonjs`.

```
{
compilerOptions:{
"module": "es2020"
},
"ts-node": {
    "compilerOptions": {
      "module": "commonjs"
    },
  }
}
```
the output of `ts-node --show-config` shows that it uses `module: commonjs` and running `ts-node webpack.config.ts` runs successfully.

but running it through webpack `webpack --config webpack.config.ts` doesn't respect values overridden by ts-node and fails with error `Cannot use import statement outside a module`

to confirm that the problem is coming from not respecting the `ts-node` property in `tsconfig` file I changed the main `module` to `commonjs` and run the webpack cmd again and it run successfully.

**Comment by alexander-akait** [comment]
Yes, expected https://webpack.js.org/api/cli/#troubleshooting
