### ISSUE TITLE
Specify asset embedding strategy 

### ISSUE THREAD

**Issue by GerkinDev** [webpack/webpack#14189]
## Feature request

**What is the expected behavior?**

I'd like to use assets module to embed files by source, not data url.

The current behavior of `rule.type: 'asset'` is to embed the given asset below a certain size as a data url, like `asset/inline`. I'd like to override this behavior so that it embeds via `asset/source` instead. 

**What is motivation or use case for adding/changing the behavior?**

In my app, I rely on multiple text files, of various sizes. Those text files are actually larger as base64 than the source. Having such option would help to decouple build optimization for large & small size, while keeping extra configuration very limited. 

**How should this be implemented in your opinion?**

We could add a new key in `options` aside to `limit `, that could be called `preferredStrategy`. This option would default to `asset/inline` if not specified. If asset size is below the limit, use the strategy. Otherwise, use `asset/resource`. 

**Are you willing to work on this yourself?**

Yes

**Comment by alexander-akait** [comment]
You can do it using configuration on own side

**Comment by 19Qingfeng** [comment]
> You can do it using configuration on own side
What is it ?  Do you refer to url-loader ?
