### ISSUE TITLE
Duplicated instances of modules with loaders other than the default one (or babel's)

### ISSUE THREAD

**Issue by guigrpa** [webpack/webpack#1419]
I've seen this with **coffee-loader** and **cjsx-loader**, but #1249  also reports this problem with **jsx-loader**. The problem seems to appear when we require the same file from outside a module and from within the module:

`a.coffee` (within module `bb`):
```coffee
module.exports = {just: 'an object'}
```

`b.coffee` (within module `bb`):
```coffee
module.exports = require './a'
```

`odd.coffee`:
```coffee
a = require('bb/a');
b = require('bb/b');
console.log a is b  # should be true
```

When you run `coffee odd.coffee`, sure enough, you get: `true`.
But when you run it through Webpack (with coffee-loader):

* You get module `a` bundled twice:

```
    [0] ./odd.coffee 94 bytes {0}
    [1] /Users/guillermo/Docs/Docs.Prog/JavaScript/bb/a.coffee 56 bytes {0} [built]
    [2] /Users/guillermo/Docs/Docs.Prog/JavaScript/bb/b.coffee 59 bytes {0}
    [3] /Users/guillermo/Docs/Docs.Prog/JavaScript/bb/a.coffee 56 bytes {0} [built]
```

* What's worse, you get an unexpected result in the browser: `false`

**Comment by guigrpa** [comment]
There's absolutely no problem with the default loader: you get the expected result: `true`.

**Comment by phuu** [comment]
I've also seen this, I think, and put together a [little demo](https://github.com/phuu/webpack-dependency-demo).

@guigrpa Do you think these are the same issue? It definitely only happens when the loader (in my case `babel`) is added.

**Comment by guigrpa** [comment]
Yes, I believe that's the same issue (although I thought the Babel loader didn't have that problem).

**Comment by phuu** [comment]
`npm dedupe` seemed to fix it, as did switching to npm3 (so I've gone with the latter).

**Comment by bebraw** [comment]
@guigrpa Safe to close?

**Comment by guigrpa** [comment]
I really don't know, since I'm no longer having the same structure in my program.

**Comment by bebraw** [comment]
Ok. Let's close this in favor of #1418.
