### ISSUE TITLE
React library throws Invalid hook call error in react-live

### ISSUE THREAD

**Issue by daring123** [webpack/webpack#14196]
i have a package A which build in Federation module.This is my webpack config below
![image](https://user-images.githubusercontent.com/5986074/132709230-9051c6fb-80a9-43dc-9ff9-3fbc2f089370.png)

when i use react-live , i import package A in this way:
![image](https://user-images.githubusercontent.com/5986074/132709972-7f29fbf4-2fab-418c-bfef-70f590615aa5.png)

however ,it show the error below:
![image](https://user-images.githubusercontent.com/5986074/132706700-4b9360bd-6d58-4536-81de-711f2f3107f4.png)

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
