### ISSUE TITLE
output.environment don't work

### ISSUE THREAD

**Issue by hec9527** [webpack/webpack#14191]
# Bug report

**What is the current behavior?**
my `webpack.config.js` as below, I want to remove `arrowFunction` and `forof` and so on from output. But it seems don't work.

refer to the [webpack document](https://webpack.js.org/configuration/output/#outputenvironment)
```js
const path = require('path');

/** @type {import("webpack").Configuration} */
module.exports = {
  mode: 'production',

  entry: './src/index.js',

  output: {
    path: path.resolve(__dirname, '../dist'),
    filename: './js/[name].[id].[contenthash:5].js',
    environment: {
      arrowFunction: false,
      bigIntLiteral: false,
      const: false,
      destructuring: false,
      dynamicImport: false,
      forOf: false,
      module: false,
    },
    clean: true,
  },
};
```

this is me source code
```js
const show = () => {
  const info = {
    bigInt: 10086n,
    str: '10086',
  };
  const { bigInt, str } = info;
  console.log(bigInt);

  for (let i of [1, 2, 3, 4, 5]) {
    console.log(i);
  }
};
show();
```
and, this is output 
```js
(()=>{const{bigInt:o,str:n}={bigInt:10086n,str:"10086"};console.log(o);for(let o of[1,2,3,4,5])console.log(o)})();
```

`arrowFunction` and `const` and everything is still there.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

I want to remove or transfrom  ES-features above. 

They are not needed in the output because the runtime environment may not support them

**Other relevant information:**
webpack version:   5.52.0
Node.js version:   v12.22.5
Operating System:  MacOs 11.5.2
Additional tools:

**Comment by alexander-akait** [comment]
Expected, we don't rewrite your code, you need `babel-loader`
