### ISSUE TITLE
Http2 Empty Mock not Used

### ISSUE THREAD

**Issue by FrankEssenberger** [webpack/webpack#14197]
# Bug report

**What is the current behavior?**

When building a react app using `webpack@4.44.2` a compile error is created because the required `http2` module is not present. 

**If the current behavior is a bug, please provide the steps to reproduce.**

- create a react app
- include a dependency requiring `http2`
- execute `npm run build`

**What is the expected behavior?**

The build should work. I investigated the issue and the root cause and in the [NodeSourcePlugin.js](https://github.com/webpack/webpack/blob/3956274f1eada621e105208dcab4608883cdfdb2/lib/node/NodeSourcePlugin.js#L32) it is looped over all keys of the [node-libs-browser](https://github.com/webpack/node-libs-browser/blob/master/index.js) table. Since the `http2` is not in there, you never reach the point where the empty mock is set. If I add the line in the table `http2 = null` the compilation works.

Unfortunately the `node-libs-browser` is deprecated and I do not know if changes are possible there. Since the webpack version is defined by react I can also not update to the newer webpack version in which the node module filling is done differently.

**Other relevant information:**
webpack version:  4.44.2
Node.js version: 14.X.Y
Operating System: macOS
Additional tools: -

**Comment by alexander-akait** [comment]
Sorry, webpack v4 is deprecated and only accept security fixes, please consider update to v5

**Comment by FrankEssenberger** [comment]
Just as an infor for people finding this. The react developers working on an update to version 5 of [webpack](https://github.com/facebook/react/pull/22267). So I hope this should resolve the issue.
