### ISSUE TITLE
`global` is defined for the browser

### ISSUE THREAD

**Issue by dosentmatter** [webpack/webpack#14210]
# Bug report

**What is the current behavior?**
`global` points to `globalThis` or `window` in the browser. As far as I know from reading docs on MDN, `global` is only defined in node.

Also the webpack code seems to suggest the same thing:

[`global` is a `nodeProperty`](https://github.com/webpack/webpack/blob/c181294865dca01b28e6e316636fef5f2aad4eb6/lib/config/browserslistTargetHandler.js#L287)

[`web` has `global: false`](https://github.com/webpack/webpack/blob/c181294865dca01b28e6e316636fef5f2aad4eb6/lib/config/target.js#L100-L120)

**If the current behavior is a bug, please provide the steps to reproduce.**
Piggybacking off the [getting started guide](https://webpack.js.org/guides/getting-started/):

```dist/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Getting Started</title>
  </head>
  <body>
    <script src="main.js"></script>
  </body>
</html>
```

```src/index.js
function component() {
  console.log(global); // EXPECT `undefined`
  const element = document.createElement('div');

  element.innerHTML = 'Hello World';

  return element;
}

document.body.appendChild(component());
```

```webpack.config.js
const path = require('path');

module.exports = {
  entry: './src/index.js',
  output: {
    filename: 'main.js',
    path: path.resolve(__dirname, 'dist'),
  },
};
```

```sh
npx webpack --config webpack.config.js
open dist/index.html # open in default browser
```

---

The bundled `dist/main.js` looks like this (beautified):
```js
(() => {
    var n = {};
    n.g = function() {
        if ("object" == typeof globalThis) return globalThis;
        try {
            return this || new Function("return this")()
        } catch (n) {
            if ("object" == typeof window) return window
        }
    }(), document.body.appendChild(function() {
        console.log(n.g);
        const t = document.createElement("div");
        return t.innerHTML = "Hello World", t
    }())
})();
```

The `n.g` is `__webpack_require__.g`. Normally, it looks something like this when unminified and not concatenated:
```js
/******/ 	/* webpack/runtime/global */
/******/ 	!function() {
/******/ 		__webpack_require__.g = (function() {
/******/ 			if (typeof globalThis === 'object') return globalThis;
/******/ 			try {
/******/ 				return this || new Function('return this')();
/******/ 			} catch (e) {
/******/ 				if (typeof window === 'object') return window;
/******/ 			}
/******/ 		})();
/******/ 	}();
```

This seems to be generated by this [template](https://github.com/webpack/webpack/blob/c181294865dca01b28e6e316636fef5f2aad4eb6/lib/runtime/GlobalRuntimeModule.js#L20-L42) and the [variable name is specified here](https://github.com/webpack/webpack/blob/c181294865dca01b28e6e316636fef5f2aad4eb6/lib/RuntimeGlobals.js#L253-L256).

**What is the expected behavior?**
The console should log `undefined` for `global`, but instead it logs `window`:
![image](https://user-images.githubusercontent.com/5732253/132909659-1fc7917c-e751-46c6-8dd8-d183a5c7fdd0.png)

Webpack seems to be replacing all references of `global` to be `__webpack_require__.g`. The code for `__webpack_require__.g` can return `globalThis` or `window`, which causes `global` to be defined for the browser.

Is this expected behavior? I found this issue because I was trying to optimize browser code with `DefinePlugin`:

```js
new DefinePlugin({
  "typeof global": JSON.stringify(process.env.IS_SERVER ? "object" : "undefined"),
})
```

And then I noticed how `global` was being replaced with `__webpack_require__.g`, so `typeof global === 'object'` would be `true` on the browser.

[`lodash` uses `typeof global` here](https://github.com/lodash/lodash/blob/898b378f069ecb6c92b7713529985ba78ff34d31/.internal/freeGlobal.js#L2) and I'm not sure if webpack causes any problems with that.

**Other relevant information:**
webpack version:  
```
webpack 5.52.1
webpack-cli 4.8.0
```
Node.js version: `v14.16.1`
Operating System: macOS Big Sur 11.5.2
Additional tools: N/A

**Comment by alexander-akait** [comment]
Update dev server to the latest stable version, we don't generate `global` for `browser`

**Comment by alexander-akait** [comment]
Oh, no let's keep separately
