### ISSUE TITLE
Bug when using `globalThis` from core-js

### ISSUE THREAD

**Issue by romainmenke** [webpack/webpack#14213]
# Bug report

**What is the current behavior?**

This code throws in IE8 with : `Object doesn't support this action`

```js
(typeof globalThis !== "undefined") && (typeof globalThis.String !== "undefined")
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Test results : 
https://mrhenry.github.io/web-tests/#8dda6a67-3527-4f7c-b2ab-0c6a455a1710

Test source code : 
https://github.com/mrhenry/web-tests/blob/main/specifications/tc39/ecma262/18.1.1.globalThis/test.pure.js

Transpiled/bundled code : 
https://github.com/mrhenry/web-tests/blob/main/specifications/tc39/ecma262/18.1.1.globalThis/test.babel_webpack.js

Error occurs on line 1092 : 
https://github.com/mrhenry/web-tests/blob/main/specifications/tc39/ecma262/18.1.1.globalThis/test.babel_webpack.js#L1092

HTML file with this code : https://gist.github.com/romainmenke/f3751b88a50b8433425a1f1058ed552d
**loading this file in IE8 will illustrate the error**

Webpack config : 
https://github.com/mrhenry/web-tests/blob/main/webpack.config.js

Build with Webpack CLI :
`npm run webpack -- --entry $(mkfile_dir)test.pure.js --output-path $(mkfile_dir) --config webpack.config.js`
https://github.com/mrhenry/web-tests/blob/main/specifications/tc39/ecma262/18.1.1.globalThis/Makefile#L9

**What is the expected behavior?**

I expected no interrop issues with `core-js` `globalThis`

**Other relevant information:**
webpack version:  5.52.1
Node.js version: 16.x
Operating System: macos
Additional tools: babel, core-js, preset-env

**Comment by alexander-akait** [comment]
Sorry, not related to webpack, we don't have this code `(typeof globalThis !== "undefined") && (typeof globalThis.String !== "undefined")`, feel free to feedback

**Comment by alexander-akait** [comment]
Also from our docs:

> Webpack supports all browsers that are ES5-compliant (IE8 and below are not supported)

**Comment by romainmenke** [comment]
The error happens in webpack code :

>Error occurs on line 1092 :
>https://github.com/mrhenry/web-tests/blob/main/specifications/tc39/ecma262/18.1.1.globalThis/test.babel_webpack.js#L1092

```js
/******/ 	/* webpack/runtime/define property getters */
/******/ 	!function() {
/******/ 		// define getter functions for harmony exports
/******/ 		__webpack_require__.d = function(exports, definition) {
/******/ 			for(var key in definition) {
/******/ 				if(__webpack_require__.o(definition, key) && !__webpack_require__.o(exports, key)) {
/******/ 					Object.defineProperty(exports, key, { enumerable: true, get: definition[key] });
/******/ 				}
/******/ 			}
/******/ 		};
/******/ 	}();
```

Webpack works fine in IE8 for all our other tests.
Can you take a second look please?

Thank you!

**Comment by zloirock** [comment]
You could try to use ESM -> CJS Babel transform that does not use accessors, https://github.com/zloirock/core-js/blob/858461ea1421a53e4fdca91bcac0922f79a3762b/babel.config.js#L26.

**Comment by romainmenke** [comment]
@zloirock Thank you for the suggestion and for noticing this issue :)
Running tests now with that transform 🤞

**Comment by romainmenke** [comment]
Hehe, that change breaks too many other things.
Will just have to accept that `globalThis` won't work in this configuration or do a build specific for IE8.

Thank you @zloirock for taking a look anyway :)

**Comment by zloirock** [comment]
@romainmenke I didn't say that *this* will work in your case, I say that required ESM -> CJS Babel transform that does not use accessors. For my test cases, this transform is enough, you could try to use another - for example, default `babel-plugin-transform-modules-commonjs` (however, I'm not sure that it will work in all cases).

**Comment by romainmenke** [comment]
I'll also check out that other plugin!

It is fine if we have some failures in this test suite.
It is a side project and the main goal at this point is to see if we can reliably test (no flaky results) a lot of things in a lot of browsers.

I'll try a few more configurations to see if I can get IE8 to pass :)
