### ISSUE TITLE
Use `supports X` Browserslist query instead of exact versions list

### ISSUE THREAD

**Issue by ai** [webpack/webpack#14226]
In [`browserslistTargetHandler.js`](https://github.com/webpack/webpack/blob/main/lib/config/browserslistTargetHandler.js#L107-L126) we have a few objects with browsers support data.

Instead of hardcoding this versions, we can use Can I Use data:

```js
let dynamicImport = browserslist('supports es6-module-dynamic-import')
```

Reasons:

1. One source of truth
2. Less code in webpack
3. Future-proof for new browsers

**Comment by ai** [comment]
@alexander-akait I found this improvement idea during the investigation of #14203

**Comment by alexander-akait** [comment]
We try to do it before, but it was rejected due invalid browsers versions

**Comment by alexander-akait** [comment]
Check out versions and check what browserslist returns, open a real browser and check it - failed

**Comment by ai** [comment]
Is it because Can I Use data for some features was incorrect?

**Comment by alexander-akait** [comment]
Yes

**Comment by alexander-akait** [comment]
If they fix it, then we will return to the syntax you suggested, otherwise we generated invalid code, currently versions was checked by me manually using real browsers and as you can see no problems a long ago.

**Comment by ai** [comment]
What about Can I Use data right now?

**Comment by alexander-akait** [comment]
Still invalid checked a week ago

**Comment by vankop** [comment]
bump

**Comment by ai** [comment]
@alexander-akait did they fixed Can I Use data? How we can fix it?

**Comment by alexander-akait** [comment]
@ai Still not fixed :disappointed: Looks like it's not good so no one wants to fix it, let's reopen

**Comment by ai** [comment]
What do we need to fix in Can I Use. I can send PR.

**Comment by alexander-akait** [comment]
@ai these versions https://github.com/webpack/webpack/blob/main/lib/config/browserslistTargetHandler.js#L107-L126 was changed manually by me, so caniuse data should have almost the same versions, so if we fixed it we can use browserslist('supports es6-module-dynamic-import'), my previously check has other versions

**Comment by ai** [comment]
@alexander-akait I decided to review a difference. I started from Chrome. `≥ 61` in Can I Use vs `≥ 63` in webpack.

I used Browserstack to load Chrome 61 and run [ES tests from MDN](https://github.com/mdn/js-examples/tree/master/module-examples). All tests except `dynamic-module-imports` were passed.

Why do you think Chrome 61 does not support ESM?

Maybe there is some bugs?

**Comment by alexander-akait** [comment]
@ai As far as I remember when I tested I took information from MDN https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import (63 there)

**Comment by ai** [comment]
For dynamic `import()` we have exactly the same results:

* https://caniuse.com/es6-module-dynamic-import
* https://github.com/webpack/webpack/blob/main/lib/config/browserslistTargetHandler.js#L107-L126

Did I miss any difference?

**Comment by alexander-akait** [comment]
Looks like fixed, because previously it was not 61, do we have `supports x` for each item from https://github.com/webpack/webpack/blob/main/lib/config/browserslistTargetHandler.js#L127 (i.e. `const`/`arrow-functions`/etc)

**Comment by ai** [comment]
> Looks like fixed

Let’s replace to Browserslist 🥳

> do we have supports x for each item from

Yeap, we can use it everywhere since you already have Browserslist in dependencies.

**Comment by ai** [comment]
@alexander-akait should we re-open it?

**Comment by steverep** [comment]
If there are still compatibility issues here to work out, can some output warnings or documentation be added to inform users in the meantime?

I have a query that uses `supports es6-module-dynamic-import`, and much to my confusion, I had to dig into the runtime code to find it wasn't using dynamic imports at all.

**Comment by steverep** [comment]
For dynamic import at least, it seems the versions agree between Webpack and CanIUse with the exceptions of UC and kaios.
