### ISSUE TITLE
Adding entry points dynamically after dev server started

### ISSUE THREAD

**Issue by schovi** [webpack/webpack#1422]
Hi,

I am working on blueprint for making chrome extensions with webpack https://github.com/schovi/webpack-chrome-extension and I want to make it as smooth as possible :)
For that I need to dynamicaly change entry points based on some source file (in this case manifest.json).
Problem is only in development environment, where you can add or remove source files. I want to listen on these changes and tell webpack what files to serve.
In production I can prepare webpack config and make build, so there is no problem.

I tried to dig into plugins, but didn't find anything helpful. 

If you have any idea, or just way which I should go, please tell me :)

**Comment by sokra** [comment]
Either restart webpack when the config file changes.

Or you can write a plugin which dynamically adds entry points. Take a look at https://github.com/webpack/webpack/blob/master/lib/SingleEntryPlugin.js#L19-L23.

**Comment by schovi** [comment]
@sokra thanks for hint!

**Comment by schovi** [comment]
@sokra 
I am trying to simulate simple usecase, when entry point is added after some time.
Unfortunately it does not works that simple. As you can see i have simple timeout for simulating that user changed some source file and add another entry point. Without that setTimeout it works just fine.

```javascript
function DynamicEntries() {}
DynamicEntries.prototype.apply = function(compiler) {  
  setTimeout(() => {
    console.log("Add entry")
    const name = 'content/index'
    const item = [
      'webpack-dev-server/client?https://localhost:3001',
      'webpack/hot/only-dev-server',
      '/Users/schovi/work/webpack-chrome-extension/src/content/index.js'
    ]

    compiler.apply(new MultiEntryPlugin(null, item, name);)
  }, 2000)
};
```

In plugin documentation I found part http://webpack.github.io/docs/plugins.html#emit-async
```
emit(c: Compilation) async
The Compiler begins with emitting the generated assets. Here plugins have the last chance to add assets to the c.assets array.
```

If I understand to lifecycle of webpack compilation, there is some event named `emit` and after that I can't add another entryPoint.

I guess it does not have solution, but on other hand webpack plugins and background is kind of magic for average immortal and maybe there is a way :)

Any suggestions?

**Comment by bew** [comment]
@schovi Hi, it's been a long time but I have a similar use case, do you remember if you managed to make it work?

**Comment by TSMMark** [comment]
Anyone successfully been able to add in additional entry points after dev server already started?

**Comment by vankop** [comment]
you should apply [EntryPlugin](https://github.com/webpack/webpack/blob/main/lib/EntryPlugin.js) and run compiler

**Comment by TSMMark** [comment]
> you should apply [EntryPlugin](https://github.com/webpack/webpack/blob/main/lib/EntryPlugin.js) and run compiler

Would you be able to elaborate at all? How to apply entry plugin with a new entry point after WDS is already running?

**Comment by vankop** [comment]
@TSMMark 
```js
const webpack = require("webpack");
const compiler = webpack(require("./webpack.config"));

const watching = compiler.watch({}, (stats) => {});

// add new entry https://webpack.js.org/plugins/internal-plugins/#entryplugin
new webpack.EntryPlugin(/* entry plugin options here */).apply(compiler);
watching.invalidate((err) => {
  if (!err) {
    // rebuilded
  }
});
```
EntryPlugin options:
- context - build context (e.g. `__dirname`)
- entry string like common webpack `entry` (e.g. `"./index.js"`)
- entry options https://github.com/webpack/webpack/blob/main/types.d.ts#L3222 + optional `name`

**Comment by vankop** [comment]
Also maybe you can use https://github.com/webpack/webpack/blob/main/lib/DynamicEntryPlugin.js , it allows on each build return  `N` entry (e.g. `{ entry1: { import: "a" }, entry2: { import: "b" } }`)

**Comment by goranton** [comment]
`class DevEntriesPlugin {
        apply(compiler) {
            compiler.hooks.beforeCompile.tap('DevEntriesPlugin', () => {
                new compiler.webpack.EntryPlugin(
                    compiler.context,
                    `${require.resolve('../...')}?devPort=${compiler.options.devServer.port}`,
                    {name: undefined},
                ).apply(compiler);
            });
        }
    }

    return { // webpack.config.js
        plugins: [new DevEntriesPlugin()],`

you can do something like that

**Comment by goranton** [comment]
```
class DevEntriesPlugin {
        apply(compiler) {
            compiler.hooks.beforeCompile.tap('DevEntriesPlugin', () => {
                new compiler.webpack.EntryPlugin(
                    compiler.context,
                    `${require.resolve('<relative path to entry>')}?devPort=${compiler.options.devServer.port}`,
                    {name: undefined},
                ).apply(compiler);
            });
        }
    }

    return { // webpack.config.js
        plugins: [new DevEntriesPlugin()],
```

you can try something like this
