### ISSUE TITLE
why Chrome giving wrong error info?

### ISSUE THREAD

**Issue by astwyg** [webpack/webpack#1423]
hi, everybody:

  i am trying to use webpack@1.12.1 with react@0.13.3, webpack-dev-server@1.10.1, the project is like a demo and i upload it to `https://github.com/astwyg/react-df`.

  well, my Chrome tell me there is an error at file`webpack:///./~/react/lib/ReactClass.js`: `Uncaught TypeError: Cannot read property '__reactAutoBindMap' of undefined`. the line Chrome marked error is `if (this.__reactAutoBindMap) {`.

  it is obviously that line cannot have that error, and i change react version to 0.11.2, everything works fine.

  so, there are 2 questions:
  1. is webpack support the latest version of react(0.13.x)?
  2. if Chrome giving a obviously wrong error info, how to debug?

  thank you for any idea.

**Comment by astwyg** [comment]
we still don't know why Chrome giving a wrong error position, but we have slove the problem by using babel-loader instead of jsx-loader.

**Comment by sokra** [comment]
`if (this.__reactAutoBindMap) {` can have the error `Uncaught TypeError: Cannot read property '__reactAutoBindMap' of undefined`. When `this` is `undefined`.

**Comment by astwyg** [comment]
i do not think `this` is able to be `undefined` in js, obviously, Chrome is giving a wrong debug info, it appeared times in my environment.

**Comment by SimenB** [comment]
`this` can be undefined in strict mode at least.

![image](https://cloud.githubusercontent.com/assets/1404810/9832646/291e7e54-5982-11e5-9207-20849b8dd30f.png)

**Comment by astwyg** [comment]
thanks to @SimenB , but ,Chrome is really giving a wrong debug info in some case, is anyone else encounted this problem?

**Comment by ianbytchek** [comment]
@astwyg just raised a similar issue, #1655. Obviously it's not the undefined part, but seems like the same behaviour. Safari does something similar but points to a different place within js. Webpack really does manage to make both debuggers go nuts.

**Comment by ianbytchek** [comment]
The issue was with source map files confusing chrome. See if your code or any dependencies use them, or try stripping all comments to see if you're getting a different result.
