### ISSUE TITLE
Request: webpack --clean to remove built files

### ISSUE THREAD

**Issue by ronkorving** [webpack/webpack#1424]
It's not a big deal, but... Since all my webpack configuration is nicely tucked away in webpack.config.js, if I want to make a `clean` NPM script or Makefile target, I need it to be aware of where the built files will end up (and possibly what they're named). Webpack however already knows all this through it's configuration. I think it would be nice if I could remove my built files by simply running `webpack --clean` or something along those lines.

**Comment by sokra** [comment]
`rm -rf build`

**Comment by ronkorving** [comment]
I'm saying it might be considered more elegant if it would remove *exactly* the files that the webpack configuration refers to. It's not that big a deal though. The trigger for this was my `make clean` calling exactly `rm -rf build`, and it took me a while to realize my build folder was actually `www/build` in my webpack config.

Anyway, if you think it's useless, by all means close this issue.

**Comment by Metallium** [comment]
your `www/build` folder still can contain useful data
webpack will need to compile bundle just to see what files are going to be emitted
seems an overkill

**Comment by ronkorving** [comment]
It can extract all its information from the config file, no?
Anyway, seems there's no interest in this, so I won't push for it any further.
Thanks for an amazing project either way :)
