### ISSUE TITLE
IE11: "Expected Identifier"

### ISSUE THREAD

**Issue by Download** [webpack/webpack#14253]
# Bug report

**What is the current behavior?**
Webpack 'compilation' fails to deliver a bundle that works in IE11.

**If the current behavior is a bug, please provide the steps to reproduce.**
* Clone my repo at https://github.com/download/ulog checkout tag 2.0.0-beta.19
* Run `npm install` && `npm run build` and check *tutorial/index.html* in IE11

The problematic code, according to IE, is found in *ulog.min.js*, line 1, column 6623.
It seems it can't cope with the destructured assignment in this fragment:

```js
var r,i,[u,c,f]=e,a=0;
```

**What is the expected behavior?**
It should compile to support Internet Explorer 11.

**Other relevant information:**
webpack version:  5.52.1
Node.js version: 10.16.3
Operating System: Windows 10
Additional tools: Webpack CLI 4.8.0

Also see this old, closed issue on webpack-cli:
https://github.com/webpack/webpack-cli/issues/1069

**Comment by vankop** [comment]
@Download did you tried `optimization.minimize=false`?

**Comment by Download** [comment]
No. Should I?

**Comment by Download** [comment]
Is it maybe just wrong config?

I have this:

```js
var path = require('path')
var dir = path.resolve(__dirname)
const TerserPlugin = require("terser-webpack-plugin");

module.exports = {
  node: false,
  context: dir,
  entry: {
    ulog: './ulog.bundle.js',
    full: './full.bundle.js',
  },
  output: {
    path: dir,
    filename: '[name].min.js',
    environment: {
      // The environment supports arrow functions ('() => { ... }').
      arrowFunction: false,
    }
  },
  devtool: false,
  optimization: {
    minimize: true,
    minimizer: [
      new TerserPlugin({
        extractComments: false,
      }),
    ],
  },
}
```

**Comment by Download** [comment]
With minimization turned off, it still fails. This time it points to this part of the code:

```js
var [chunkIds, moreModules, runtime] = data;
```

Any way to prevent Webpack from emitting array-destructuring code?

**Comment by Download** [comment]
I guess I missed this part:
https://webpack.js.org/migrate/5/#need-to-support-an-older-browser-like-ie-11

Will look if adding a browserlist config helps.

**Comment by Download** [comment]
Ok, sorry for raising the alarm. I didn't realize I had to use `browserslist` and configure that I wanted support for IE11 explicitly in later versions, but it makes sense. Gotta forget about IE at some point :)
