### ISSUE TITLE
A bug in #14174 cause Webpack hangs after build finished

### ISSUE THREAD

**Issue by malash** [webpack/webpack#14258]
# Bug report

**What is the current behavior?**

cc @sokra

I find a bug that cause Webpack hangs after build finished in latest version 5.32.1 because of [this line](https://github.com/webpack/webpack/pull/14174/files#diff-428c41964bad5dfd5424e7be2839c92ff9395632a7f29399eb21b37977f1ee5eR81) in https://github.com/webpack/webpack/pull/14174 

Webpack 5.52.1 prod build with cache:
```
webpack 5.52.1 compiled with 8 warnings in 2010 ms
✨  Done in 61.31s.
```

Webpack 5.52.0 prod build with cache:
```
webpack 5.52.0 compiled with 8 warnings in 1974 ms
✨  Done in 2.72s.
```

The root cause of this bug is `setTimeout(..., MAX_TIME_IN_FRESH_PACK)` keeps event loop not empty util 1mins passed.

> For more details, in this question [When does Nodejs process quit?](https://stackoverflow.com/questions/19699619/when-does-nodejs-process-quit) it said 
> Node's mechanism is the event loop and a node process will generally exit when:
> 1. The event loop's queue is empty.
> 2. No background/asynchronous tasks remain that are capable of adding to the queue.

**If the current behavior is a bug, please provide the steps to reproduce.**

Since it is an obvious bug that I could find the root cause line of code. I didn't prepare a reproduce example. But I believe and Webpack 5.52.1 with cache enabled could reproduce this issue.

**What is the expected behavior?**

Webpack process should exit immediately after finished build.

**Other relevant information:**
webpack version:  5.52.1
Node.js version: 14.15.3
Operating System: Darwin Malash-MacBook-Pro.local 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64 i386 MacBookPro16,1 Darwin
Additional tools:

**Comment by alexander-akait** [comment]
Duplicate https://github.com/webpack/webpack/issues/14250
