### ISSUE TITLE
Regression: Webpack 5.52.1 takes a full minute to shut down

### ISSUE THREAD

**Issue by nifgraup** [webpack/webpack#14250]
# Bug report
Webpack 5.52.1 introduced an issue not seen in 5.52.0.

**What is the current behavior?**
It takes full minute to wait for webpack to shut down after printing message "compiled successfully".

**If the current behavior is a bug, please provide the steps to reproduce.**
1.  Run `node node_modules/webpack-cli/bin/cli.js --progress` a couple of times to fill the cache.
2. Run again and notice message: `webpack 5.52.1 compiled successfully in 3467 ms`.
3. Wait a minute until Webpack returns.

**What is the expected behavior?**
Return after "compiled successfully" message as in 5.52.0.

**Other relevant information:**
webpack version:  5.52.1
Node.js version: v12.22.6
Operating System: Linux
Additional tools:

**Comment by alexander-akait** [comment]
Expected, https://github.com/webpack/webpack/releases/tag/v5.52.0

**Comment by alexander-akait** [comment]
> automatically close an active watching when closing the compiler

You need to close compiler too

**Comment by alexander-akait** [comment]
If you need help, please provide full steps to reproduce

**Comment by nifgraup** [comment]
repro

webpack.config.js:
```
module.exports = function(env = {}) {
  return {
    mode: 'development',
    cache: {
      type: 'filesystem',
    },
    entry: {
      "bundle": "./empty.js",
    },
  };
};
```

```
npm install webpack@5.52.1 webpack-cli@4.8.0
touch empty.js
node node_modules/webpack-cli/bin/cli.js --progress # returns correctly
node node_modules/webpack-cli/bin/cli.js --progress # waits for a minute
```

**Comment by fz6m** [comment]
using filesystem cache the second build will have a long delay

<img src='https://user-images.githubusercontent.com/59400654/133444383-034c4d0e-6369-43d4-9362-058bab0bb4d0.png' width='50%' />
