### ISSUE TITLE
dynamic import fails when using template literal 

### ISSUE THREAD

**Issue by steveja42** [webpack/webpack#14257]
# Bug report

**What is the current behavior?**

    import(`./pageEffects/${effectModules[iPrank].fileName}`)  

fails with error "effectModules is not defined"
but 

    import('./pageEffects/'`  + effectModules[iPrank].fileName) 

succeeds.

**If the current behavior is a bug, please provide the steps to reproduce.**
try to use dynamic import with a template literal using the production build of an app made with create react app.

**What is the expected behavior?**
For dynamic import to function the same as when using a string literal.

**Other relevant information:**
webpack version:   
the version with "react-scripts": "4.0.1"
Node.js version: 
14.15.1
Operating System:  
windows 10
Additional tools: 
Create React App

**Comment by alexander-akait** [comment]
PR welcome

**Comment by alexander-akait** [comment]
Please run `npm ls webpack`

**Comment by steveja42** [comment]
I am using pnpm, but 
pmpm ls webpack 
doesn't show anything because webpack is not a direct dependency in my package.json

**Comment by alexander-akait** [comment]
Yes, you are using webpack v4, it is fixed in webpack v5, please migrate on webpack v5 https://github.com/facebook/create-react-app/issues/9994
