### ISSUE TITLE
In production mode, the ID is a character string

### ISSUE THREAD

**Issue by a599155162** [webpack/webpack#14277]
### as shown in the figure:
![企业微信截图_16319455862972](https://user-images.githubusercontent.com/28429119/133878462-6c943208-10e9-404b-a8e5-0f6ae6c72a0b.png)
![企业微信截图_16319456153719](https://user-images.githubusercontent.com/28429119/133878458-5a13e93e-b165-41a5-8a04-40e5216e82c7.png)
![企业微信截图_16319456273082](https://user-images.githubusercontent.com/28429119/133878461-404c000d-38ed-4101-8d57-f708790e7314.png)

#### Packages:
```` 
{
    "@vue/compiler-sfc": "3.1.5",
    "add-asset-html-webpack-plugin": "3.2.0",
    "chalk": "4.1.0",
    "chokidar": "3.5.1",
    "clean-webpack-plugin": "4.0.0-alpha.0",
    "connect-history-api-fallback": "1.6.0",
    "copy-webpack-plugin": "8.1.0",
    "core-js": "3.15.2",
    "css-mquery-packer": "1.2.4",
    "cssnano": "4.1.10",
    "download": "8.0.0",
    "express": "4.17.1",
    "fork-ts-checker-webpack-plugin": "6.2.0",
    "fs-extra": "9.1.0",
    "html-webpack-plugin": "5.3.1",
    "http-proxy-middleware": "2.0.1",
    "inquirer": "8.0.0",
    "ip": "1.1.5",
    "loader-utils": "2.0.0",
    "lodash": "4.17.11",
    "log-update": "4.0.0",
    "mini-css-extract-plugin": "2.3.0",
    "minimist": "1.2.5",
    "postcss-scss": "3.0.5",
    "typescript": "4.2.3",
    "vue-loader": "15.9.8",
    "vue-template-compiler": "2.6.14",
    "webpack": "5.53.0",
    "webpack-dev-middleware": "5.1.0",
    "webpack-merge": "5.8.0",
    "webpack-node-externals": "2.5.2",
    "ws": "8.0.0"
  }
````

**Comment by alexander-akait** [comment]
Expected, we reduce size and convert string to number in production

**Comment by goblin-pitcher** [comment]
老哥，遇到同样的问题了，你之前是怎么解决的？

**Comment by a599155162** [comment]
> 预期，我们在生产中减小大小并将字符串转换为数字

后续更新新版本后没出现过这种问题了
需要你的话，你发下你的配置看看，我可以帮你对比一下

**Comment by goblin-pitcher** [comment]
> > 预期，我们在生产中减小大小并将字符串转换为数字
> 
> 后续更新新版本后没出现过这种问题了 需要的话你发下你的配置看看，我可以帮你对比一下

我这个问题其实更接近这个issue: https://github.com/webpack/webpack/issues/13010
生产环境下moduleId本来应该是数字，结果转换成了`9503b1`这样的结构，关键是打包的时候也没报错，页面加载时`9503b1`直接报`Invalid or unexecpted token`了。

**Comment by goblin-pitcher** [comment]
> > 预期，我们在生产中减小大小并将字符串转换为数字
> 
> 后续更新新版本后没出现过这种问题了 需要的话你发下你的配置看看，我可以帮你对比一下
公司代码，现在电脑上暂时没有配置
我这个问题其实更接近这个issue: https://github.com/webpack/webpack/issues/13010
生产环境下moduleId本来应该是数字，结果转换成了9503b1这样的结构，关键是打包的时候也没报错，页面加载时9503b1直接报Invalid or unexecpted token了。
我一开始发现比较大的mouduleId才有这个现象，然后把optimization.moduleIds改成natural，这样moduleId的数字不会很大了，但是还是治标不治本，代码里有用到加密相关的算法，里面有些很大的数字，也被转换成这种带字母的数字结构里，我一开始以为是terser大数字转16进制导致的bug，但是我把optimization.minimize关了还是有这个现象

**Comment by goblin-pitcher** [comment]
> > 预期，我们在生产中减小大小并将字符串转换为数字
> 
> 后续更新新版本后没出现过这种问题了 需要的话你发下你的配置看看，我可以帮你对比一下

哥们，昨天搜了下其他issue，发现和这个[issue](https://github.com/webpack/webpack/issues/13398)很像，我看你的问题，估计你应该也用`[contenthash:5]`这类的语法限制了contenthash的长度。
我看这个现象感觉就像是谁写了个webpack插件，但是没用ast分析，直接上正则替换字符串了，一开始我以为是我们项目里哪个傻x乱写插件导致的问题，结果一个个排查了发现所有插件都没有这类操作，后来看到了那个issue里官方人员的回复，然后我试了下，设置`optimization.realContentHash`为false真能解决这个问题，我后来看了下内置的`RealContentHashPlugin`插件，搜索`replace`，发现代码里真有这种正则替换内容的操作：[代码](https://github.com/webpack/webpack/blob/4fda15571d66bb593a1bad69835a6797b2f911c6/lib/optimize/RealContentHashPlugin.js#L348)。

我本地打了断点，发现真是这行代码导致的，解决方式就是设置`optimization.realContentHash`为false，但这个会导致内容相同的文件重复打包的问题，所以只能把contentHash长度设长一点...这样误伤正常代码的概率就小了
