### ISSUE TITLE
ModuleParseError does not report faulty module's file path (`request`)

### ISSUE THREAD

**Issue by Domiii** [webpack/webpack#14287]
# Bug report

### **What is the current behavior?**

`webpack` build fails with `ModuleParseError`, but the file that caused it is not reported.

(In my case: In some broken build setup (complex multi-layered issue), dependencies were not resolved correctly.)

### **If the current behavior is a bug, please provide the steps to reproduce.**

(Does not matter.)

### **What is the expected behavior?**

* `ModuleParseError` should report the path of the failed module but doesn't.
* This bug existed before and has been addressed in #5008 (in webpack v3), but apparently it has regressed since then.

### **Other relevant information:**

webpack version:  `5.47.1`
Node.js version:  `16+`
Operating System: `Windows`
Additional tools: `storybook`

# Possible solution

[When constructing the `ModuleParseError` in `NormalModule`](https://github.com/webpack/webpack/blob/e73864c0367acdaad58c5129c1396410f986b392/lib/NormalModule.js#L941), also add `this.request` (which is the location of the module) to the error message and incorporate it into the final `message`.

PS: I made the change locally manually, and after knowing the module in question, I could solve the problem within 1 minute.

**Comment by alexander-akait** [comment]
PR welcome

**Comment by alexander-akait** [comment]
Weird, works fine:
```
ERROR in ./entry.js 4:0
Module parse failed: Unexpected token (4:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     return 0;
| }
> .;l
|  ,matchMedia(. .j 'djas')
```

```
ERROR in ./foo.js 4:8
Module parse failed: Unexpected token (4:8)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| 
> exports default patt;
| 
 @ ./entry.js 1:0-27
```

Works fine, file name on top of error, feel free to feedback

**Comment by alexander-akait** [comment]
Or please provide a case when it was not shown
