### ISSUE TITLE
Question: Is there a better way to use webpack within webpack?

### ISSUE THREAD

**Issue by adjavaherian** [webpack/webpack#1429]
I've written this loader that spawns a new webpack process for each entry file.  I use webpack within the loader to capture all the required sass files in the graph from the entry point, (similar to the way they do it in react-proxy-loader).  Is there a better way to do this?  I feel like running webpack within webpack is  overkill, it works well, but its a bit slower because of all the new processes.  Opinions or alternative solutions would be greatly appreciated.  Thanks.

https://github.com/adjavaherian/sass-lifter-loader

**Comment by sokra** [comment]
There is a `createChildCompiler` function on the `Compiler` object (`this._compiler`) that assist you creating child compilations within a loader. i. e. the worker-loader does this to compile a worker bundle from the required file.

The react-proxy-loader doesn't do that.

It doesn't look like a good idea to do this in my optinion, but I only took a short look at your loader.
