### ISSUE TITLE
package.json, and bower.json?

### ISSUE THREAD

**Issue by jtangelder** [webpack/webpack#143]
I am looking for the option to let webpack also look for a `bower.json` file. This can also contain the `main` entry property. Looking in the source, i saw i can change the `modulesDirection` to add the bower components dir, and change the `packageMains`, but this is only for the `main` property.

A property like `packageFiles` would be awesome.

``` js
resolve: {
    modulesDirectories: ["./node_modules", "./bower_components"],
    packageFiles: ['package.json','bower.json','.bower.json']
}
```

**Comment by jjalonso** [comment]
@mrm007 Agree totally, is 2015 and is not working still, any new?

**Comment by jtangelder** [comment]
Well you could open a PR for this...

**Comment by mrm007** [comment]
I think nowadays this is a moot point. See the discussion [here][enh]. Between @sokra's workaround and [bower-webpack-plugin][bwp], you're covered. Personally I'm using @sokra's method and it does the job just fine.

[enh]: https://github.com/webpack/enhanced-resolve/pull/4
[bwp]: https://github.com/lpiepiora/bower-webpack-plugin

**Comment by jjalonso** [comment]
But the PR is there, I saw a commit changing it. This is needed and simple
guys.

**Comment by cameronjroe** [comment]
What happens when a `bower.json` has a main attribute as an array `main: ["jquery-ui.js"]`. Webpack throws an error..
