### ISSUE TITLE
Multiple projects using CommonsChunkPlugin

### ISSUE THREAD

**Issue by brenoc** [webpack/webpack#1430]
I have two separate projects that uses Webpack and CommonsChunkPlugin.

So there's something like this:
```js
<script src="/assets/project-one/commons.js"></script>
<script src="/assets/project-one/ComponentA.js"></script>
<script src="/assets/project-one/ComponentB.js"></script>

<script src="/assets/project-two/commons.js"></script>
<script src="/assets/project-two/ComponentC.js"></script>
<script src="/assets/project-two/ComponentD.js"></script>
```

The problem is: there is two "webpackBootstrap" files, that leads to the second project requiring modules from the first project. 

That happens because the `__webpack_require__` function from `project-one/commons.js` is passed as a parameter to a component in "project-two".

How can I avoid this? How can two separate projects on the same window use CommonsChunkPlugin? Is there an alternative?

Thanks in advance!

**Comment by brenoc** [comment]
Is this the exception mentioned in the docs:
> The entry chunk contains the runtime and there must only be one runtime on a page **(there are exceptions)**.

**Comment by sokra** [comment]
Provide different `output.jsonpFunction` parameters for each project, so they an coexist on a page.

**Comment by brenoc** [comment]
Thank you, @sokra. That worked. You're awesome :+1:
