### ISSUE TITLE
Declare some of entry as Worker/ServiceWorker in the config

### ISSUE THREAD

**Issue by Jack-Works** [webpack/webpack#14316]
## Feature request

**What is the expected behavior?**

I want to declare some entry points are (service) workers.

**What is motivation or use case for adding/changing the behavior?**

In Chrome Extension manifest V3, the background process of an extension becomes a service worker, therefore Service Worker can be the top-level entry points without any other JS to register/start it.

**How should this be implemented in your opinion?**

Add a new option to the [entry descriptor](https://webpack.js.org/configuration/entry-context/#entry-descriptor).

**Are you willing to work on this yourself?**
I don't know how

**Comment by alexander-akait** [comment]
Please use multi compiler mode, it was created for this case

**Comment by Jack-Works** [comment]
> Please use multi compiler mode, it was created for these case

Is it possible to share chunks between different config?

**Comment by alexander-akait** [comment]
Yes, but need to be configured, as you can understand we can't generate different runtime code for different targets (we have an issue for universal target, you ca find it here), if you specify `target: 'node'` and `target: 'web'` for different chunks, it will require generate platform depending code, If you have a problem please provide example I will show you how better to solve it.

**Comment by Jack-Works** [comment]
Currently use `chunkLoading: "import-scripts"` resolves my needs

**Comment by alexander-akait** [comment]
Yes, ecma modules can solve most of issues, we will migrate on them in future
