### ISSUE TITLE
Provide a way to write a library that supports different dependencies on Node and the Browser

### ISSUE THREAD

**Issue by nex3** [webpack/webpack#14314]
## Feature request

Author of Sass here :wave:! I'm talking with @markwhitfeld about trying to get Dart Sass's JS output running in the browser, and we're running into some hassles with Webpack in particular that I think a new feature could address.

**What is the expected behavior?**

I need to meet all the following requirements:

1. I want to be able to distribute a single npm package with minimal duplication...
2. that works on both Node.js and the web...
3. with nothing more complicated than `npm i sass` and `require('sass')`...
4. and plays nicely with Webpack bundling on both platforms...
5. without needing any special configuration...
6. and uses some libraries that are only available on Node...
7. while gracefully degrading when those libraries aren't available on the web.

As a special bonus non-requirement, it would be *nice* if the JS file we generate can be used as-is on web pages *without* bundling.

**What is motivation or use case for adding/changing the behavior?**

As far as I can tell, there's no way to meet all of the above requirements right now. If I didn't have to worry about Webpack, I'd just write

```js
const chokidar = typeof window === 'undefined' ? require('chokidar') : null;
```

and be on my merry way, but that won't actually prevent webpack from bundling the dependency's code when targeting a browser so it fails requirement 4.

**How should this be implemented in your opinion?**

I'm agnostic on the best way to make this work, as long as it satisfies the requirements outlined above. The simplest solution might be to recognize `typeof window === 'undefined`' as a magic check that can be inlined and used for constant-folding. A more explicit solution might be to provide a `__webpack_target_browser__` constant that explicitly indicates whether the platform is a browser.

**Are you willing to work on this yourself?**

No.

**Comment by alexander-akait** [comment]
Duplicate of https://github.com/webpack/webpack/issues/6525

**Comment by nex3** [comment]
Hey @alexander-akait! I may be misunderstanding #6525, but I don't *think* this is the same request. To be clear, I am not personally running Webpack; I'm just trying to distribute a library that has some `require()` calls in it that work well *when my users run Webpack*. So I don't think being able to create a universal bundle would actually work for me.

**Comment by alexander-akait** [comment]
So do you want to create library which will work on Node.js and browser?

**Comment by nex3** [comment]
Exactly!

**Comment by alexander-akait** [comment]
This is a rather related issue, here multiple solutions:
- `universal`, output with ecma modules/umd output, create protection for only Node.js packages (i.e. `const chokidar = typeof window === 'undefined' ? require('chokidar') : null;` as you written above), unfortunately it requires change logic on you side, no job for webpack here, some modules can be shimming
- `exports` https://nodejs.org/api/packages.html#packages_conditional_exports, using multi compiler mode and create different files for Node.js and web target
- avoid using Node.js modules, but it's not applicable for some cases

Also if we are saying about `sass`, it is possible to do even better - most of Node.js dependencies need only for CLI, so you can create `sass-cli` package and move Node.js logic to own package, `sass` will be free from Node.js and make be compiled without any problems.

**Comment by nex3** [comment]
> * `universal`, output with ecma modules/umd output, create protection for only Node.js packages (i.e. `const chokidar = typeof window === 'undefined' ? require('chokidar') : null;` as you written above), unfortunately it requires change logic on you side, no job for webpack here, some modules can be shimming

Can you go into more detail on how this would work? We're willing to change our logic as long as the end product satisfies all the requirements.

> * `exports` https://nodejs.org/api/packages.html#packages_conditional_exports, using multi compiler mode and create different files for Node.js and web target

How does this interact with Webpack? Does Webpack-bundling-for-Node use the `node` export and Webpack-bundling-for-browser use the `default` one? Does Webpack support any sort of special `browser` export?

> Also if we are saying about `sass`, it is possible to do even better - most of Node.js dependencies need only for CLI, so you can create `sass-cli` package and move Node.js logic to own package, `sass` will be free from Node.js and make be compiled without any problems.

This is something we'd like to do, but making it work well with our build system is a lot of work especially since @markwhitfeld would probably be the one implementing it and he's not very familiar with Dart or our Dart-based build system.

**Comment by alexander-akait** [comment]
> Can you go into more detail on how this would work? We're willing to change our logic as long as the end product satisfies all the requirements.

webpack bundle `chokidar` (bundle all `require`/`import` modules), but load module only when `window` is `undefined`, yes, it increases size of library, but no runtime errors and allow to run library on different targets (i.e. `web`/`node.js`/etc).

> How does this interact with Webpack? Does Webpack-bundling-for-Node use the node export and Webpack-bundling-for-browser use the default one? Does Webpack support any sort of special browser export?

Yes, https://webpack.js.org/guides/package-exports/#target-environment, if developer want to build for Node.js we will get `node`, but if it will be `web` we will take `browser`, also you do it better using ecma modules and commonjs, using:
```
"exports": {
    "node": {
      "module": "./sass.node.mjs",
      "require": "./sass.node.cjs"
    },
    "default": "./sass.browser.mjs"
  }
```

**Comment by nex3** [comment]
> > 
> 
> webpack bundle `chokidar` (bundle all `require`/`import` modules), but load module only when `window` is `undefined`, yes, it increases size of library, but no runtime errors and allow to run library on different targets (i.e. `web`/`node.js`/etc).

We'd really like to avoid bundling that into the library we push to `npm`. It's not good for our Node users because they don't have any control over which version of chokidar they're using, and it's not good for our browser users because they get a bunch of extra code they definitely won't use.

> Yes, https://webpack.js.org/guides/package-exports/#target-environment, if developer want to build for Node.js we will get `node`, but if it will be `web` we will take `browser`, also you do it better using ecma modules and commonjs, using:
> 
> ```
> "exports": {
>     "node": {
>       "module": "./sass.node.mjs",
>       "require": "./sass.node.cjs"
>     },
>     "default": "./sass.browser.mjs"
>   }
> ```

We could probably do this. It would take some work to properly factor out the dependencies between multiple entrypoints like this, but it should be doable.

I'd still like to keep this feature request open, though, because having an inline way of writing "require this but not on the web" and similar things without needing to jump through one of these hoops would still be very useful.

**Comment by vankop** [comment]
```
and uses some libraries that are only available on Node...
while gracefully degrading when those libraries aren't available on the web.
```

you probably will need some guide to mock this Node.js libraries ( or use also universal alternatives ) for bundling.

Not sure about `exports` field since then users could not do something like `require('sass/lib/something')`, if it is a case for you pls use https://github.com/defunctzombie/package-browser-field-spec

**Comment by alexander-akait** [comment]
@nex3 but there is not universal solutions, how do you present a solution from our side? We can't do magic here, you application/lib should be written for both targets or bundled for different targets. In fact you want to bundle universal lib - i.e. library works fine for Node.js and web targets.

**Comment by markwhitfeld** [comment]
@nex3 As an alternative, do you think we could potentially use the `imports` field?
https://nodejs.org/api/packages.html#packages_imports

Something like this:
```JS
// package.json
{
  "imports": {
    "#chokidar": {
      "node": "chokidar",
      "default": "./empty.js"
    }
  },
  "dependencies": {
    "chokidar": ">=3.0.0 <4.0.0"
  }
}
```

**Comment by nex3** [comment]
@alexander-akait The issue is that I *can* write a JS library that works for multiple targets, but Webpack's bundler won't play nice with it. As a toy example, if I wanted to create the `store-some-data` package, I could write:

```js
const fs = window ? null : require('fs/promises');

function storeSomeData(data) async {
  if (fs) {
    await fs.promises.writeFile('data', data);
  } else {
    document.cookie = `data=${data}`;
  }
}
```

This works fine on its own, but when bundling for the browser Webpack will choke on the `require` even though in a browser context it will never be executed.

---

@markwhitfeld Good find! It looks like that *doesn't* work for built-in Node modules, which I filed https://github.com/webpack/enhanced-resolve/issues/310 to track, but it does work for dependencies which should be enough to satisfy our needs.
