### ISSUE TITLE
Question: how to require webpack bundle from memfs right?

### ISSUE THREAD

**Issue by lapanoid** [webpack/webpack#1432]
I am trying to build react components in memory with webpack for testing purposes, I already done most of the work but stuck with one error. here is gist - https://gist.github.com/lapanoid/dd0c15eda3ed9df78325
I basically do test.script.js with webpack.result.js and get addComponentAsRefTo ERROR, this happens only if I build component that requires other component, If I build component without deps on other components - everything is fine. addComponentAsRefTo ERROR - usually happens when you require two instanses of react, but webpack.result.js has only one as you can see. 
Any help with this puzzle?
I also thought that maybe eval(memFs.readFileSync(fileName), 'utf-8’) not even right way to require module from memFs, maybe there is some other magic.. Most confusing for me that no dependancy components works with this.
BTW: Thanks @sokra for webpack it is totally awesome!

**Comment by sokra** [comment]
React should be an external. Use a different `libraryTarget` is commonjs.

``` js
var m = { exports: {} };
var f = eval("(function(module, exports, require) {" + code + "})");
f(m, m.exports, require);
var Component = m.exports
```

**Comment by bebraw** [comment]
@lapanoid Did you figure this out?

**Comment by lapanoid** [comment]
@bebraw I did not. I solved my problem without this whole compilation in memory thing for now - https://github.com/lapanoid/cosmos-mocha . I want to make this faster, so maybe I will to return to this later. Sorry for long reply.
