### ISSUE TITLE
module federation build error: remoteEntry.js from Terser plugin Unexpected character '@' 

### ISSUE THREAD

**Issue by feng-fu** [webpack/webpack#14329]
When I set module federation plugin like this:

```javascript
new ModuleFederationPlugin({
    name: 'app3',
    filename: 'remoteEntry.js',
    library: { name: 'app3', type: 'var' },
    exposes: {
      './App': './src/App',
    },
    remotes: {
      app2: 'app2@http://localhost:3002/remoteEntry.js',
    },
    shared: { react: { singleton: true }, 'react-dom': { singleton: true } },
  })
```

and use webpack to build project, get an error:

```
ERROR in remoteEntry.js
remoteEntry.js from Terser plugin
Unexpected character '@' [remoteEntry.js:46,21]
```

then I set optimization.minimize to false, the remoteEntry.js code:

```
module.exports = app2@http://localhost:3002/remoteEntry.js; 
```

Obviously, the browser can't parse above code.

lately, I deleted ` library: { name: 'app3', type: 'var' }`, build success.

but I need set library.type to use window[scope].get.

I don't know what happened, this is a demo:

https://stackblitz.com/edit/node-lvdh8t?file=webpack.config.js

use `npm run build` and `npm run build:dev` can recurrence the issue.

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
