### ISSUE TITLE
webpack is invisible to npm when installed globally on Windows 10, and doesn't get updated

### ISSUE THREAD

**Issue by JoeUX** [webpack/webpack#14331]
# Bug report

**What is the current behavior?**

Webpack is invisible to npm after installing (global) on Windows 10, with default config. This has been the case for more than a year.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Install Node 14.17.6 LTS (latest LTS).
2. Update global npm to 7.24.1 (latest).
3. Install webpack 5.5.4 globally (latest).
4. List your installed global packages.
5. Webpack is not listed.
6. Wait until you know webpack has an update and check npm for outdated packages.
7. Webpack is not listed.

Here's a screenshot showing webpack in the node_modules folder, but not listed by npm as installed:

![Webpack problem](https://user-images.githubusercontent.com/8071692/134814623-1262da27-1109-494d-8bc9-1f12636a8c96.JPG)

**What is the expected behavior?**
npm should "see" webpack like any other package, list it, and install webpack updates when they become available.

It looks like webpack isn't registering itself to npm or Node the way other packages do, and the way webpack _used to do_, since at some point more than a year ago webpack behaved normally and was fully accounted for. I skimmed the package.json and other files for webpack and other packages (e.g. eslint) and couldn't find any obvious differences.

**Other relevant information:**
webpack version:  5.5.4 (applies to earlier releases going back at least a year)
Node.js version: 14.17.6 LTS (applies to earlier node LTS releases going back at least a year)
Operating System: Windows 10 Pro 64-bit 21H1
Additional tools: npm 7.24.1 (applies to earlier releases going back at least a year)

**Comment by alexander-akait** [comment]
Sorry not related to webpack, I recommend to add `webpack`/`webpack-cli`/`webpack-dev-server` to your `package.json` and avoid to using global version
