### ISSUE TITLE
Feature Request: Options to keep `require.resolve` as external

### ISSUE THREAD

**Issue by LumaKernel** [webpack/webpack#14351]
Continuation of https://github.com/webpack/webpack/issues/8636 (closed because of inactivity)
Related: https://github.com/webpack/webpack/issues/9393 (closed because of inactivity)

versions

```
webpack 5.54.0
webpack-cli 4.8.0
```

## Feature request

```js
// webpack.config.js
const path = require('path');

/** @type {import('webpack').Configuration} */
module.exports = {
  mode: 'none',
  entry: './src/entry.js',

  externals: [
    ({request}, cb) => request.startsWith('extpack') ? cb(null, 'extpack', 'commonjs') : cb(),
  ],

  output: {
    path: path.resolve(__dirname, "dist"),
    filename: "[name].js",
  },
};
```

```js
// src/entry.js
console.log(require('extpack'));
console.log(require.resolve('extpack/some/file.txt'))
```

It produces following `dist/main.js`

```js
// ...
/* 1 */
/***/ ((module) => {

"use strict";
module.exports = require("extpack");

/***/ })
// ...
console.log(__webpack_require__(1));
console.log(/*require.resolve*/(1))
// ...
```

**What is the expected behavior?**

With some options to produce following.

```js
// ...
console.log(__webpack_require__(1));
// OR
// console.log(require('extpack'))
console.log(require.resolve('extpack/some/file.txt'))
// ...
```

**What is motivation or use case for adding/changing the behavior?**

Entrust all resolutions about some packages to `node`.
It may seem no need to use `webpack`, but I'd like to use this combined with [vercel/next.js](https://github.com/vercel/next.js).

Also it seems no matter to bundle, but some packages are using node native binaries ([nodejs/node-gyp](https://github.com/nodejs/node-gyp)) like `require('./build/some.node')` or `require.resolve('./build/some.node')`. They should be resolved in unbundled environment. `*.node` can't be run only with itself, so I can't use `type: 'asset/resource'` for this. It can be seen as `*.node` is out of webpack resolution/depedants detection.

**How should this be implemented in your opinion?**

1.

- New import type for `externals`, like `"commonjs-require-resolve"`
- And add new property like `originalType` in `context` arg to know whether it is `require.resolve`'d in original source.

```js
// ...
externals: [
  ({request, originalType}, cb) => request.startsWith('extpack') ? cb(null, 'extpack', originalType === 'commonjs-require-resolve' ? originalType : 'commonjs') : cb(),
],
// ...
```

I'm not passing `originalType` itself because to correctly transform `import ...` for example.

Some type of imports are not used as output, so they should be something like `"unknown"`, `null`, `"input-import"`, etc...

EDIT:

2. or add new types (`"native-commonjs"`).

```js
// ...
externals: [
  ({request}, cb) => request.startsWith('extpack') ? cb(null, 'extpack', 'native-commonjs') : cb(),
],
// ...
```

**Are you willing to work on this yourself?**
a little but I'm sorry I can't work it on soon. It may be after Dec 2021

**Comment by alexander-akait** [comment]
bump

**Comment by vankop** [comment]
I'm not sure that this will be supported.. you should do this in another `external` module like
```
// src/entry.js
console.log(require('extpack'));
console.log(require('resolved-paths').extpack)
```

**Comment by vankop** [comment]
please use
```js
const binary = require("binary");
```
webpack.config.js
```js
module.exports = {
  externals: {
        "binary": "var require.resolve('./binary.node')"
    }
};
```
I don't see a reason to implement special case for Node.js api.

**Comment by LitileXueZha** [comment]
@vankop Actually when using `require.resolve` in nodejs, we want it returns the absolute path of this file/module, but webpack bundle it as a module id.

For example:
```javascript
const my_file_path = require.resolve('module/lib/file.js');
// Expected "/c/users/name/.../node_modules/module/lib/file.js"
```
Webpack output:
```javascript
const my_file_path = /*require.resolve*/('module/lib/file.js');
// Unexpected "module/lib/file.js"
```

In browser it maybe worked, but this is not a expected behavior in nodejs.

**Comment by LitileXueZha** [comment]
@alexander-akait Emmmm, we maybe not care files' hash in nodejs. As I know, hash is used for caching and gradually upgrading in browser, these not much affect on server.

In another way,  webpack only keep module id although it also bundle the external moudle.

```javascript
// webpack.config.js
```

**Comment by alexander-akait** [comment]
@LitileXueZha Hash used internally not only for contenthash, and for perf/comparation/predictable output. Why you need absolute path?

**Comment by bitQ2019** [comment]
any update on this? 
i got this `require.resolve` problem  on @vercel/ncc

**Comment by Amareis** [comment]
Ok, I run into this, and easiest method is to use eval - 
`const req = eval('require')` 
Works both in pure node.js and in webpack-compiled node app. Dirty, but simple.
