### ISSUE TITLE
Webpack5 breakchange loader options passed as query string 

### ISSUE THREAD

**Issue by maoxiaoke** [webpack/webpack#14377]
# Bug report

**What is the current behavior?**

Webpack5 breakchange loader options passed as query string (loader?some&params).

+ original code that breaks: https://github.com/webpack/webpack/blame/main/lib/ProgressPlugin.js#L412

+ And the code that been affected: https://github.com/alibaba/ice/blob/master/packages/webpack-plugin-import/src/webpack-plugin-import.js#L95

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  v5.55.1
Node.js version: v16.9.0
Additional tools:

**Comment by sokra** [comment]
passing a string to the `loaders` array is not valid. You need to pass an object with `{loader: string, options: string | object, ...}`.

**Comment by alexander-akait** [comment]
Answered
