### ISSUE TITLE
aliases couldn't be resolved without an extra slah

### ISSUE THREAD

**Issue by eng-dibo** [webpack/webpack#14370]
if you set aliases for webpack.config like this as mentioned in the official docs
```
// webpack.config.js

module.exports = {
  //...
  resolve: {
    alias: {
      Utilities: path.resolve(__dirname, 'src/utilities/'),
      Templates: path.resolve(__dirname, 'src/templates/'),
    },
  },
};
```
now you can use it like this
```
import Utility from 'Utilities/utility';
```
and it works fine.

but if we need to move the trailing slash to the alias definition to be compatible with `tsConfig.compilerOptions.paths` property to be like this

```
// webpack.config.js

module.exports = {
  //...
  resolve: {
    alias: {
     // -----> note the extra trailing '/'
      '@': path.resolve(__dirname, 'src/utilities/') + '/',
    },
  },
};
```

now we want to use it like this: `import Utility from '@utility';`, instead of `import Utility from '@/utility';`
note that we want to use '@' not '@/'
tsconfig can resolve it, but webpack complains about it

environment:
- webpack: v5
- nodejs: v12 and v14

**Comment by alexander-akait** [comment]
Because `@utility` is package name (yes, npm doesn't allow to use it, but it can be used potentially), you should use `@/utility`, it means resolve `@` directory and looking for `utility` module

**Comment by eng-dibo** [comment]
I don't mean `@` execluevely, I mean the concept.
forexample `~alias` instead of `~/alias`

**Comment by alexander-akait** [comment]
Same answer for `~`, `~alias` can be directory and can be module in `node_modules`, you can have `node_modules/~alias` and `~alias` with `'~': path.resolve(__dirname, 'src/utilities/') + '/',`
