### ISSUE TITLE
PackFileCacheStrategy warnings with global Promise hook

### ISSUE THREAD

**Issue by jokeryu** [webpack/webpack#14376]
# Bug report

**What is the current behavior?**

I was runing a nextjs project with webpack5. When I added following code

```js
class HookPromise extends Promise {}
global.Promise = HookPromise
```

I got some warnings like

```
<w> [webpack.cache.PackFileCacheStrategy] Restoring failed for Compilation/codeGeneration|external "@babel/runtime-corejs2/core-js/parse-int"|webpack-runtime from pack: Error: A lazy value that has been unmemorized can't be called again
<w> [webpack.cache.PackFileCacheStrategy] Restoring failed for Compilation/codeGeneration|external "next/dist/server/image-config.js"|webpack-runtime from pack: Error: A lazy value that has been unmemorized can't be called again
<w> [webpack.cache.PackFileCacheStrategy] Restoring failed for Compilation/codeGeneration|external "next/dist/shared/lib/to-base-64.js"|webpack-runtime from pack: Error: A lazy value that has been unmemorized can't be called again
<w> [webpack.cache.PackFileCacheStrategy] Restoring failed for Compilation/assets|chunkpages/blog from pack: Error: A lazy value that has been unmemorized can't be called again
```

**If the current behavior is a bug, please provide the steps to reproduce.**

see above

**What is the expected behavior?**

in `lib/cache/PackFileCacheStrategy.js`:

```js
if (value instanceof Promise) {
  ...
}
```

I changed the conditional statement, the warnings were disappeared

```js
if (value && typeof value.then === 'function') {
  ...
}
```

**Other relevant information:**
nextjs version: 11.1.2
webpack version:  nextjs bundled version
Node.js version:  14.16.0
Operating System:  mac os 11.4
Additional tools:

**Comment by alexander-akait** [comment]
PR welcome

**Comment by vankop** [comment]
I think there was a PR for that already..

**Comment by Pulkit3234** [comment]
@alexander-akait Can i work on this issue and create a PR?

**Comment by alexander-akait** [comment]
Yes, PR welcome

**Comment by Pulkit3234** [comment]
@alexander-akait Can you guide me on how to resolve this issue, the fix is giving an error message -> 'Property 'then' does not exist on type 'PackContentItems | Promise<PackContentItems>'.

**Comment by alexander-akait** [comment]
Example of fix inside the issue, we should change `value instanceof Promise` on `value && typeof value.then === 'function'`
