### ISSUE TITLE
Require using ~/foo

### ISSUE THREAD

**Issue by kolodny** [webpack/webpack#1437]
When I need to require something which I know is in the root of my project or one folder in, I would like to be able to do something like `require('~/foo')` and not have to figure out where it is relative to me like `require('../../../foo')`, is there any way to do that?

I already know about using something like `modulesDirectories: ['.', 'node_modules']` but I want to be able to differntiate between downloaded modules and internal modules, so I know the difference between `require('utils')` and `require('~/utils')`, meaning I want the `~` char there or something similar

**Comment by SimenB** [comment]
Have you tried aliasing `~` to the root?

**Comment by jhnns** [comment]
Aliasing shoot work, but I'd recommend not to use `~` because its too ambiguous. You could call it `root` or `app`.

**Comment by kolodny** [comment]
aliasing is what I was looking for, thanks
