### ISSUE TITLE
feature request: new magic comments to integrate with ECMAScript ShadowRealm proposal 

### ISSUE THREAD

**Issue by Jack-Works** [webpack/webpack#14383]
## Feature request

[ShadowRealm](https://github.com/tc39/proposal-shadowrealm/) is a stage 3 ECMAScript proposal that allows creating a new execution environment that is isolated from the current one. It contains a function called `importValue` that works like a dynamic import in that environment.

```js
const realm = new ShadowRealm()
realm.importValue('./app.js')
// works like
realm.evaluate(` import('./app.js') `)
```

This API is not a special syntax like dynamic import, therefore it's hard to support code-splitting by static analysis.

**What is the expected behavior?**

Add a new magic comment to allow add a new chunk.

```js
realm.importValue( /** webpackDynamicEntry: esmodule */ './app.js' )
```

Syntax: `webpackDynamicEntry: _chunk_loader_`

`./app.js` should be bundled like `new Worker(new URL('./app.js', import.meta.url))`, which is, it should contain its own webpack runtime because it will run in a new environment instead loaded in the current one.

**What is motivation or use case for adding/changing the behavior?**
Easy to integrate with ShadowRealm proposal.

**How should this be implemented in your opinion?**
Like other magic comments.

**Are you willing to work on this yourself?**
I don't know how

**Comment by alexander-akait** [comment]
We supports only stage 4 ECMAScript

**Comment by alexander-akait** [comment]
but you can't always write comments in source code, ideally each type of comments should have an option in `webpack.config.js`

**Comment by Jack-Works** [comment]
> but you can't always write comments in source code, ideally each type of comments should have an option in `webpack.config.js`

Yeah, I agree, but this case is actually not easy to static analyze. (Track all calls of `importValue` of `ShadowRealm` accurately is not possible). There is another use case. With these new magic comments, library authors can control how it works without telling users they need to change their webpack config to use.

For example, I have a custom Worker class named "OnDemandWorker". If I want to create a new Worker of this kind, I need to tell users to add this: `parser: { worker: ['OnDemandWorker', '...'] }`. But if we have this new comment, I can write `new OnDemandWorker(/** webpackDynamicEntry: importScript */ new URL("./worker.js", import.meta.url))`. Therefore when I ship this code as a library, my custom worker type can be automatically recognized as a worker entry without modifying webpack config.
