### ISSUE TITLE
Without `cache: false` webpack detect changes only once

### ISSUE THREAD

**Issue by dehghani-mehdi** [webpack/webpack#14391]
# Bug report

**What is the current behavior?**
webpack detect changes only once.

**If the current behavior is a bug, please provide the steps to reproduce.**
```
// webpack.config.js
module.exports = {    
    module: {
        rules: [
            {
                test: /\.(js|jsx)$/,
                exclude: /node_modules/,
                use: ['babel-loader']
            }
        ],
    },    
    resolve: {
        extensions: ['*', '.js', '.jsx']
    }
};
```

```
// src/index.js
import ReactDom from "react-dom";
import App from "./App";

ReactDom.render(<App />, document.getElementById('app'));
```

```
// src/app.js
export default () => <div>Welcome to React App</div>;
```

**What is the expected behavior?**
After any change, webpack should be able to detect it.

Adding `cache: false` resolve the issue, but I think it's a bug. I also tried ` cache: { type: 'filesystem' }`, but doesn't work.

**Other relevant information:**
webpack version:  `5.56.0`
Node.js version: `12.18.2`
Operating System: Windows 10 x64
Additional tools: -

**Comment by vankop** [comment]
Could you create reproducible repo? You probably using `webpack-dev-server`, so from this description your setup is unclear to me.
