### ISSUE TITLE
Possible to have multiple output files? (i.e. multiple output configs)

### ISSUE THREAD

**Issue by dashed** [webpack/webpack#144]
Is it possible to have multiple files?

What I'm hoping to do is configure `webpack.config.js` to output:
1. mylibrary.js - non-minified
2. mylibrary.min.js - minified (uglifyjs)

I looked around the webpack docs to see if this is possible -- but didn't find anything useful.

It'll be good to have various output configs.

**Comment by ericclemmons** [comment]
I just tried something like this...

- `webpack.config.js` creates `client.js` and `vendor.js`
- `webpack.config.optimize.js` uses theses as entry points and tries to `process.node.NODE_ENV` using `DefinePlugin`.

Unfortunately, it doesn't seem to do anything at all, besides add the webpack headers & some other bulk, so it just grows instead.

**Comment by tuvistavie** [comment]
For small builds, I use something like this, it works fine.

webpack.config.js :

```
var webpack = require('webpack');

var env = process.env.WEBPACK_ENV;

module.exports = {
  entry: './src/index.js',
  output: {
    filename: env === 'dist' ? 'app.min.js' : 'app.js',
    path: './dist'
  },
  plugins: env === 'dist' ? [
    new webpack.optimize.UglifyJsPlugin({minimize: true})
  ] : []
};
```

Makefile:

```
all: dev dist

dev:
	webpack

dist:
	WEBPACK_ENV=dist webpack

.PHONY: dist
```

For bigger builds it is probably better to create a file for each environment, or to use another build tool, as mentioned in the other answers.
