### ISSUE TITLE
Question/Possible bug: You provided an invalid object where a stream was expected error in Module Federation environment

### ISSUE THREAD

**Issue by dragonflypl** [webpack/webpack#14405]
I've migrated one app to MFE Architecture using Module Federation and mysteriously looking error is thrown at runtime:

`You provided an invalid object where a stream was expected error. You can provide an Observable, Promise, Array, or Iterable`.

The code that causes it looks like this:

```ts
this
  .getSomeObservable()
  .pipe(
    switchMap(() => this.getOtherObservable()) // switching here causes the error
  ).subscribe()
```

However I was pretty sure code was ok...

When analysing stack trace, error originates from:

> https://github.com/ReactiveX/rxjs/blob/6.6.7/src/internal/util/subscribeTo.ts

```ts
export const subscribeTo = <T>(result: ObservableInput<T>): (subscriber: Subscriber<T>) => Subscription | void => {
  if (!!result && typeof result[Symbol_observable] === 'function') {
    return subscribeToObservable(result as any);
  } else if (isArrayLike(result)) {
    return subscribeToArray(result);
  } else if (isPromise(result)) {
    return subscribeToPromise(result as Promise<any>);
  } else if (!!result && typeof result[Symbol_iterator] === 'function') {
    return subscribeToIterable(result as any);
  } else {
    const value = isObject(result) ? 'an invalid object' : `'${result}'`;
    const msg = `You provided ${value} where a stream was expected.`
      + ' You can provide an Observable, Promise, Array, or Iterable.';
    throw new TypeError(msg);
  }
};
```

In my case, `result` is of type `BehaviorSubject`.

However, when I compared stack trace when app is running in non-federated to federated, the issue is here: 

> https://github.com/ReactiveX/rxjs/blob/6.6.7/src/internal/innerSubscribe.ts#L110

```ts
  if (result instanceof Observable) {
    return result.subscribe(innerSubscriber);
  }
```

Without module federation, this `if` is truthy, when I look at prototypes, deeper I can find `Observable`.

However in federated environment, this expression is falsy.

The good news it that refactoring to:

```ts
this
  .getSomeObservable()
  .subscribe(() => this.getOtherObservable().subscribe())
```

does not throw error any more.

Do you have any ideas how to properly fix it? 

It looks like Webpack is doing something under the hood that breaks this kind of checks.

## UPDATE 1

https://github.com/ReactiveX/rxjs/issues/6628 - the same issue opened on rxjs side. Questions were asked, but unfortunately I do not know the answers... Perhaps webpack team can answer it on rxjs side?"

**Comment by alexander-akait** [comment]
Please provide steps to reproduce
