### ISSUE TITLE
--watch not working with Node v4.0

### ISSUE THREAD

**Issue by hilooooo** [webpack/webpack#1441]
Mac OS X 10.10.5，process exited, and there's no error. but, I switched to 0.12.7, all goes well.

**Comment by bebraw** [comment]
Just making sure, did you recompile for 4.0? How did you run webpack (global or local install?)?

**Comment by hilooooo** [comment]
hi @bebraw , I install 4.0 with the .pkg installer, webpack global available, and run webpack via gulp flow with webpack.config.js

**Comment by Shearerbeard** [comment]
I'm not sure if it helps but I had a similar issue with a large webpack project. This fixed the crash for me:

1. Upgrade to node 4.0 stable with NVM
2. Install webpack and webpack-dev-server globally (not sure if this is required, but its a step I took so its listed here)
  ```
   npm install -g webpack && npm install -g webpack-dev-server
```
3. Blow away your local node_modules directories
4. Run ```npm install`` again in your local project.
5. Run webpack and be happy.

**Comment by hilooooo** [comment]
@Shearerbeard thank you!

**Comment by louiscntr** [comment]
I cannot seem to get `webpack --watch` working with Node 4, even after trying the steps above.
I have to roll back to 0.12.

**Comment by whoughton** [comment]
I'm on Node 4.2.0 and have an issue where if I change a js file the watch works, but if I change a css file the watch does nothing.

Using postcss and postcss-import (along with some other plugins) for css management.

**Comment by bebraw** [comment]
@whoughton Are you still seeing the issue?

**Comment by whoughton** [comment]
Honestly I've changed configurations and versions enough by this stage that I am no longer able to really comment. Which means from my view it cannot be replicated any more.

**Comment by bebraw** [comment]
Ok, let's close this one. Please re-open if you can reproduce the issue. Make sure to include a test project.
