### ISSUE TITLE
The result of asset/resource's generator.filename will be trimmed unexpectedly

### ISSUE THREAD

**Issue by hrsh7th** [webpack/webpack#14424]
# Bug report

**What is the current behavior?**

When to use `wepbkac@5.52.0` or later, the `asset/resource`'s `generator.filename` result will be trimmed unexpectedly.

**If the current behavior is a bug, please provide the steps to reproduce.**

I don't know it is a bug or intentional. But the behavior was changed from `webpack@5.52.0`.
I've created the reproducible project.

https://github.com/hrsh7th/webpack-asset-resource-repro

**What is the expected behavior?**

The result of CSS's `url(...)` isn't trimmed.

**Other relevant information:**

I think this problem is related to https://github.com/webpack/webpack/issues/14392

**Comment by alexander-akait** [comment]
@webpack-bot move to webpack-contrib/mini-css-extract-plugin
