### ISSUE TITLE
webpack doesn't clear up errors report in watch mode for multi-entries config

### ISSUE THREAD

**Issue by dnutels** [webpack/webpack#1442]
When having this configuration:

``` javascript
var webpackConfig = {
    entry: {
        sdk: ['./src/sdk.js']
    },
    output: {
        filename: './dist/sdk.js'
    },
    bail: false
};
```

any errors (syntax, mostly) are not cleared in watch mode upon rebuilds.

Below the details.
### Case 1 - working as expected

**Confguration**

``` javascript
var webpackConfig = {
    entry: './src/sdk.js',
    output: {
        filename: './dist/sdk.js'
    }
    bail: false
};
```

**`sdk.js` file**

``` javascript
var a = 10;
```

**Initial result**

![image](https://cloud.githubusercontent.com/assets/1825272/9830138/4fb7310c-592b-11e5-8e51-5a81192671f8.png)

**intentionally incorrect `sdk.js` file**

``` javascript
var a =;
```

**Result for incorrect `sdk.js` file**

![image](https://cloud.githubusercontent.com/assets/1825272/9830173/ccc8bf02-592c-11e5-8a8d-71c258b40f58.png)

Now, restoring the `sdk.js` file back to **correct state** produces:

**Result for fixed `sdk.js` file**

![image](https://cloud.githubusercontent.com/assets/1825272/9830183/2111fcae-592d-11e5-967e-0155e1841537.png)
### Case 2 - not working as expected

Same `sdk.js` file, _slightly_ different configuration.

**Confguration**

``` javascript
var webpackConfig = {
    entry: {
        sdk: ['./src/sdk.js']
    },
    output: {
        filename: './dist/sdk.js'
    },
    bail: false
};
```

**`sdk.js` file**

``` javascript
var a = 10;
```

**Initial result**

![image](https://cloud.githubusercontent.com/assets/1825272/9830198/a35ab05c-592d-11e5-8f57-f247cc2db67d.png)

**intentionally incorrect `sdk.js` file**

``` javascript
var a =;
```

**Result for incorrect `sdk.js` file**

![image](https://cloud.githubusercontent.com/assets/1825272/9830206/db404a22-592d-11e5-8b9f-cad9d0670aa6.png)

Now, restoring the `sdk.js` file back to **correct state** produces:

**Result for fixed `sdk.js` file**

![image](https://cloud.githubusercontent.com/assets/1825272/9830214/07aadd7a-592e-11e5-8794-8228c1c1ecf5.png)

---

Moreover, doing the same break-fix sequence multiple time results in:

![image](https://cloud.githubusercontent.com/assets/1825272/9830218/3371e700-592e-11e5-8b50-8d98ef0594d6.png)

**Comment by dnutels** [comment]
LOL

That's an interesting way to handle issues... If you don't answer long enough and the issuer doesn't feel like nagging -- eventually it will go away.

**Comment by alexander-akait** [comment]
Fixed, update webpack to latest stable, sorry for delay :disappointed:
