### ISSUE TITLE
require.context in watch mode reacts to any file change (regardless to extension etc)

### ISSUE THREAD

**Issue by rogovdm** [webpack/webpack#1443]
Two things happening in my code:

— calling `require.context` within certain `folder` and regexp matching `*.js` files;
— assigning `watch = true` in a webpack config file;

And the problem is:
— when I create any file with any extension in that `folder` — watch catches to this event and rebuild by bundle. And I assume that rebuild will happen only when a Create / Update / Delete is made within `*.js` files.

How can I deal with my problem? It is a bug or expected behaviour? Thanks.

**Comment by rogovdm** [comment]
This happens regardless to loaders.
— tested with native loader
— tested with babel loader

**Comment by sokra** [comment]
It currently implemented this way. It could propably implemented in another way, but this would take too much time and it's not worth it. It should only trigger a rebuild, but the rebuild shouldn't result in a new bundle.

**Comment by rogovdm** [comment]
@sokra how about this workaround?

If it would be possible to pause and unpause watch? I've tracked dawn that there is a `pause` method in some watch-related class (but seems there is not unpause method). So how about to expose access to those methods to loader? Maybe through firing up some events. That would be nice I think.

**Comment by Metallium** [comment]
(offtopic) pausing watcher would be a real deal for some cases in large projects like switching to another branch in git (now webpack locks some files and git can fail)

**Comment by carljm** [comment]
When used with karma-webpack, this also results in lots of spurious test runs (especially when using an editor like Emacs that creates transient lock files, backup files, and flycheck files next to the file being edited). With a large test suite, this is a serious (almost deal-breaking) issue.

**Comment by carljm** [comment]
@sokra When you say "take too much time," do you mean performance-wise it would be too slow in some way? Or just that it would take too much development time to fix this bug?

**Comment by SummerWish** [comment]
+1. my compiling directory is a subdirectory of the watched folder and webpack falls into infinite loops in watching mode.
