### ISSUE TITLE
v5: stats data `assetsByChunkName` missing split ("dynamic") chunks

### ISSUE THREAD

**Issue by OliverJAsh** [webpack/webpack#14433]
# Bug report

**What is the current behavior?**
When I generate stats data (JSON), the `assetsByChunkName` property is missing chunks that were dynamically generated according to `splitChunks`.

This was not the case in v4—`assetsByChunkName` did include those chunks.

**If the current behavior is a bug, please provide the steps to reproduce.**
Full reduced test case: https://github.com/OliverJAsh/webpack-stats-split-chunks

There are two branches:

- `master`: uses webpack v5
- `v4`: same setup but uses webpack v4

### webpack v4

```bash
# webpack v4
git checkout v4

yarn

rm -rf dist && webpack --json=stats.json && cat stats.json | jq '.assetsByChunkName'
```

✅ The dynamic chunk appears in `assetsByChunkName` as `vendors~routeA~routeB`.

```json
{
  "main": "main.17477d07c051418b1d7f.js",
  "routeA": "routeA.58496c9fa628f03eb391.js",
  "routeB": "routeB.d37744a3fa56ba7c8da0.js",
  "vendors~routeA~routeB": "vendors~routeA~routeB.65d7b92d01e53d3f6a94.js"
}
```

### webpack v5

```bash
# webpack v5
git checkout master

yarn

rm -rf dist && webpack --json=stats.json && cat stats.json | jq '.assetsByChunkName'
```

❌ The dynamic chunk does not appear in `assetsByChunkName`.

```json
{
  "main": [
    "main.1eb1d043c6fd288f2377.js"
  ],
  "routeA": [
    "routeA.7628c97244f6243219ec.js"
  ],
  "routeB": [
    "routeB.d7177b0b2156e694ec50.js"
  ]
}
```

**What is the expected behavior?**
`assetsByChunkName` did includes chunks that were dynamically generated according to `splitChunks`.

Alternatively, this should be mentioned somewhere as a breaking change with some guidance on how to achieve the old behaviour.

For context, we are relying on this information when we use [`webpack-flush-chunks`](https://github.com/faceyspacey/webpack-flush-chunks).

**Other relevant information:**
webpack version: v5
Node.js version: 16.3.0
Operating System: macOS latest
Additional tools:

**Comment by sokra** [comment]
`stats.chunks[].files` has all files for a chunk
