### ISSUE TITLE
Loader error! — unable to get past the Asset Management stage in the Getting started guide...

### ISSUE THREAD

**Issue by MattAppleton** [webpack/webpack#14444]
# Bug report

**What is the current behavior?**

Webpack build fails on the second step of the Getting-started tutorial. I also get a warning, but the main issue is that I am unable to follow the tutorial due to this build error.

```
> webpack-learn@1.0.0 build
> webpack

assets by status 69.8 KiB [cached] 1 asset
runtime modules 1010 bytes 5 modules
cacheable modules 532 KiB
  ./src/index.js 325 bytes [built] [code generated]
  ./node_modules/lodash/lodash.js 531 KiB [built] [code generated]
  ./src/style.css 24 bytes [built] [code generated] [1 error]

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value.
Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/

ERROR in ./src/style.css 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> .hello {
|   color: red;
| }
 @ ./src/index.js 2:0-21

webpack 5.58.1 compiled with 1 error and 1 warning in 1812 ms
The terminal process "/bin/zsh '-c', 'npm run build'" terminated with exit code: 1.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

I have been following the steps on [this tutorial page](https://webpack.js.org/guides/asset-management/) faithfully, and I am unable to complete a build on the 'Asset Management' step...

https://github.com/MattAppleton/webpack-learn

**What is the expected behavior?**

**Other relevant information:**

    "css-loader": "^6.3.0",
    "style-loader": "^3.3.0",
    "webpack": "^5.58.1",
    "webpack-cli": "^4.9.0"

Node.js version: Node v12.16.1
Operating System: OSX 10.15.7 
Additional tools:

**Comment by alexander-akait** [comment]
Move `webpack.config.js` to root of problem, i.e. from `src` directory to root directory of the project

**Comment by alexander-akait** [comment]
Use `webpack --mode production` for productions builds, and `webpack --mode development` for development builds
