### ISSUE TITLE
processContextHashSnapshot(path, tsh.hash) throws error

### ISSUE THREAD

**Issue by getTobiasNielsen** [webpack/webpack#14441]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

Running `npx next build`

Causes the following error:
`info  - Creating an optimized production build . project-path\node_modules\next\dist\compiled\webpack\bundle5.js:59190
                                                                processContextHashSnapshot(path, tsh.hash);`  
                                                                                                     ^        

`TypeError: Cannot read property 'hash' of null`

**If the current behavior is a bug, please provide the steps to reproduce.**

All I assumingly did was adding a layout and components, e.g. footer

**What is the expected behavior?**

Building instead of failing, or failing gracefully

**Other relevant information:**
webpack version: 5.58.1 (that came with the next version)
next: 11.1.2

Solution:
I deleted `.next` to fix this. I'd run `vercel --force` to skip the build cache if I was on vercel.

If a webpack dev wants to, they can get access to the private repo, and see the differences between the commits in detail.

**Comment by getTobiasNielsen** [comment]
I also added it to https://github.com/vercel/next.js/issues/29752

**Comment by alexander-akait** [comment]
@getTobiasNielsen Can you provide steps to reproduce?

**Comment by alexander-akait** [comment]
Something changes more except HTML? Maybe `package.json`? Maybe you have hooks on install deps on switching branches

**Comment by getTobiasNielsen** [comment]
> Something changes more except HTML? Maybe `package.json`? Maybe you have hooks on install deps on switching branches

I wish it so.

Here's everything that's being done.

![123qwe123qwe - Copy](https://user-images.githubusercontent.com/54803528/136668355-20073d00-62d2-4d51-8e25-d78964ffb0c9.PNG)

I tried re-adding the api folder and hello.ts, but didn't change anything.

**Comment by getTobiasNielsen** [comment]
I specifically deleted the client-production cache of webpack, to clear the problem

**Comment by getTobiasNielsen** [comment]
https://github.com/Publica-Fides/publica-fides-webapp

There are two branches, switching between test4 and test5 and building them with ` npx next build` should introduce the error.

Let me know if you are able to.
