### ISSUE TITLE
Make import.meta.url dynamic

### ISSUE THREAD

**Issue by Congelli501** [webpack/webpack#14445]
# Bug report

**What is the current behavior?**

`import.meta.url` is replaced by the current file location at the build time.
https://github.com/webpack/webpack/blob/main/lib/dependencies/ImportMetaPlugin.js#L99

**If the current behavior is a bug, please provide the steps to reproduce.**

If you build 
```
console.log(import.meta.url)
```
it will ouput a constant string (le location of the file on the current system).

This is problematic to build a project using yargs (https://github.com/yargs/yargs), as it uses `meta.import.url` (https://github.com/yargs/yargs/blob/main/lib/platform-shims/esm.mjs#L18).

When building under an Unix file system, `meta.import.url` is replaced by something like `file:///path/to/your/project/src/index.js`. When trying to run the built code under a Windows filesystem, a `TypeError [ERR_INVALID_FILE_URL_PATH]: File URL path must be absolute` is thrown, as the filename doesn't contain `file://C:/...`.

Making the `meta.import.url` variable dynamic (based on __dirname) should solve the problem.

**What is the expected behavior?**

`import.meta.url` should be based on `__dirname` for cjs build, to keep the original intended behavior of the application developer.

**Other relevant information:**
webpack version:  5.58.1
Node.js version: 16.10.0
Operating System: Ubuntu Linux 20.04
Additional tools: yargs

**Comment by alexander-akait** [comment]
Duplicate https://github.com/webpack/webpack/issues/14072

**Comment by Congelli501** [comment]
The linked issue is about supporting `__dirname` & `__filename` in a commonjs module required via an ESM module.

This issue is about supporting dynamic `import.meta.url` in a full ESM build, I don't think those issues are duplicates.

**Comment by mika-fischer** [comment]
> We are doing the same for `__filename` in commonjs

Yes, but that behavior can be adjusted via https://webpack.js.org/configuration/node/#node__filename and https://webpack.js.org/configuration/node/#node__dirname

We have those both set to `false` which means webpack will not touch `__filename` and `__dirname` at all. And we need a way to do the same for `import.meta.url`.

I agree that #14072 is a completely orthogonal issue and that this should be reopened.

**Comment by alexander-akait** [comment]
Make sense to allow keeping it

**Comment by Silvia813** [comment]
Any updates?

**Comment by pavelsavara** [comment]
Hi all, I tried to [contribute](https://github.com/webpack/webpack/pull/15246) new configuration option to fix this, but I struggle to make all tests work. I would appreciate some help.

Also I wonder what is the use-case for the current behavior, with the file name from build time. Could somebody advise ? @vankop

**Comment by dandeancook** [comment]
> Also I wonder what is the use-case for the current behavior

I have a lib, which is loaded by app through http:
```
import libfoo from "https://bar.exampleserver.com";
```
and inside libfoo, it has to know whether it is loaded from in order to load other specific files for that server.
