### ISSUE TITLE
Wrong compression

### ISSUE THREAD

**Issue by MineYuanlu** [webpack/webpack#14455]
# Bug report

**What is the current behavior?**  
Webpack incorrectly removed {}, causing the "this" environment to fail

**If the current behavior is a bug, please provide the steps to reproduce.**  

src: `data = ({ f: func, data: data }).f();`
dist: `a = func()`

func: 
```
function (){
//use this.data
}
```

**What is the expected behavior?**

dist: `a=({func:f,data:d}).func()`

**Other relevant information:**
webpack version:  5.58.1
Node.js version: v14.16.1
Operating System: Win10
Additional tools: none

**img**

src: ![图片](https://user-images.githubusercontent.com/38997444/136727568-4cd4034e-e8c9-4b00-a646-98ff6e7da65b.png)
dist: ![图片](https://user-images.githubusercontent.com/38997444/136727628-861b7be0-fbdd-46a7-ac97-de4945bee52b.png)

**Comment by alexander-akait** [comment]
Yes, we can't fix it here
