### ISSUE TITLE
Segmentation fault - Node v4.0

### ISSUE THREAD

**Issue by clubajax** [webpack/webpack#1445]
> webpack-dev-server --devtool eval --progress --colors --hot --content-base build
[1]    95058 segmentation fault  npm run dev1

This is a problem for react - jest requires v4, and webpack-dev-server doesn't work on v4. I've tried different versions of node, jest, and tried reloading my npm modules. Nothing is working.

**Comment by Coobaha** [comment]
@clubajax Have you tried to reinstall webpack and dev-server and other deps?

**Comment by clubajax** [comment]
@Coobaha, yes, I uninstalled 1.12 and installed 1.13. It works for you?

**Comment by clubajax** [comment]
I had it installed globally, and I was mixing up webpack with webpack-dev-server (hence the incorrect place for this issue). The latest install worked! Thanks.
