### ISSUE TITLE
Read keys from ENV will increase bundle size

### ISSUE THREAD

**Issue by behnammodi** [webpack/webpack#14453]
# Bug report

If we destructure more than one key from `process.env`, all keys will append to bundle file.

```bash
# .env file
REACT_APP_NAME=BEHNAM
REACT_APP_SURNAME=MOHAMMADI
```

```js
// app
const { REACT_APP_NAME, REACT_APP_SURNAME } = process.env;
```

**What is the current behavior?**
```js
// bundle file
var e=Object({NODE_ENV:"production",PUBLIC_URL:"",WDS_SOCKET_HOST:void 0,WDS_SOCKET_PATH:void 0,WDS_SOCKET_PORT:void 0,FAST_REFRESH:!0,REACT_APP_NAME:"BEHNAM",REACT_APP_SURNAME:"MOHAMMADI"}),t=e.REACT_APP_NAME,n=e.REACT_APP_SURNAME;
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Just destructure more than 1 key from `process.env`
```js
const { REACT_APP_NAME, REACT_APP_SURNAME } = process.env;
```

**What is the expected behavior?**
```js
// bundle file
var t='BEHNAM',n='MOHAMMADI';
```

**Other relevant information:**
webpack version:  4.41.2
Node.js version: 14.16.1
Operating System: macOS
Additional tools: Create React App

**Comment by behnammodi** [comment]
@alexander-akait  Thanks, why does this code work?

```js
const { REACT_APP_NAME } = process.env;
const { REACT_APP_SURNAME } = process.env;
```

**Comment by alexander-akait** [comment]
@vankop I think we have this issue, I can't find...

**Comment by behnammodi** [comment]
@alexander-akait @vankop Thanks a lot, so have you any plan to handle destructure?

**Comment by alexander-akait** [comment]
It is not easy, but maybe yes

**Comment by vankop** [comment]
closing in favor of https://github.com/webpack/webpack/issues/14800

**Comment by BradPrit09** [comment]
> Avoid using `process.env` and destructuring, it is limitation, please use `process.env.REACT_APP_NAME` and `process.env.REACT_APP_SURNAME` directly, even more `process.env` is not safe to use, you can have sensitive data there, not all things can be tree shaking and you can leak your local env.

Hi Alex, Thank you for your effort. But I have doubt regarding the documentation of the web-pack 5. Specially [EnvironmentPlugin](https://webpack.js.org/plugins/environment-plugin/) and [DefinePlugin](https://webpack.js.org/plugins/define-plugin). There it's mentioned we can use process.env clearly. 
Additionally, I can access process.env in my configs, whereas in the migration it's written that webpack5 removed process pollyfills. Can you please elaborate on this ? 
```
**VERSION USING**
"webpack": "^5.73.0",
```

**Comment by alexander-akait** [comment]
@BradPrit09 in documentation we use directly `process.env.ENV_NAME` (maybe we should improve docs to avoid misleading here, so feel free to do it).

You can use `process.env` inside `webpack.config.js` safely
