### ISSUE TITLE
Loader for two resources? 

### ISSUE THREAD

**Issue by elfet** [webpack/webpack#1446]
Hi!

Is it possible to create loader which will return 2 resources?

I want to return JS and CSS from single file.

 Thanks!

**Comment by sokra** [comment]
You need a loader that splitts the resource into two resources and return one of these depending on query param. i. e. `get-part-loader?css` and `get-part-loader?js`. Than you can use the [multi-loader](https://github.com/webpack/multi-loader) to get both.

``` js
{
                test: /\.jscss$/,
                loader: multi(
                    "style-loader!css-loader!get-part-loader?css",
                    "get-part-loader?js"
                )
}
```

**Comment by elfet** [comment]
Some think like this. 

But i need two separate files. Here's and example:
From `require ('component.js')`:
```js
/* styles
.component {
    background: ...;
}
*/

export function () {
   // Some JS code.
}
```

I want to get two files:
```css
.component {
    background: ...;
}
```
And `bundle.js`:
```
module.exports = function () {
   // Some JS code.
};
```
Is it possible?

**Comment by sokra** [comment]
yep, but you need to write a loader...

**Comment by elfet** [comment]
That's what i want to do!! But how to write this kind of loader? Call `this.callback` two times?

**Comment by sokra** [comment]
> You need a loader that splitts the resource into two resources and return one of these depending on query param. i. e. get-part-loader?css and get-part-loader?js. Than you can use the multi-loader to get both.
> 
> {
>                 test: /\.jscss$/,
>                 loader: multi(
>                     "style-loader!css-loader!get-part-loader?css",
>                     "get-part-loader?js"
>                 )
> }

**Comment by elfet** [comment]
Thanks!
