### ISSUE TITLE
Watch error on Webpack 5.55.0+

### ISSUE THREAD

**Issue by syberon** [webpack/webpack#14484]
# Bug report

**What is the current behavior?**

I used in my project Webpack, Mini-CSS-Extract-plugin and Font-awesome library. There are no problems on Webpack versions prior to 5.55.0. After updating Webpack from 5.54.0 to version 5.55.0 (and above) i get compile error on every file update in watch mode.

```
./css/styles.scss 39 bytes [built] [1 error]

ERROR in ./css/styles.scss
Module build failed (from ../node_modules/mini-css-extract-plugin/dist/loader.js):
Error: waitFor can only be called for an already started item
    at AsyncQueue.waitFor (D:\14\frontend\node_modules\webpack\lib\util\AsyncQueue.js:180:5)
    at D:\14\frontend\node_modules\webpack\lib\Compilation.js:4690:25
    at processQueue (D:\14\frontend\node_modules\webpack\lib\util\processAsyncTree.js:50:4)
    at processTicksAndRejections (node:internal/process/task_queues:78:11)

```

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Setup a project what uses: Webpack 5.55.0+, Mini-CSS-Extract-plugin, Font-awesome
2. Run this project in Watch mode
3. Make a change in every source CSS-file in Watch mode.

I made a simple project to reproduce this behavior:
[Simple project to reproduce this bug](http://sybernas.myqnapcloud.com:8080/share.cgi?ssid=0nAhchK)

**What is the expected behavior?**

The recompile process is working withou any problems on Webpack versions prior 5.55.0

**Other relevant information:**
webpack version:  5.58.2
Node.js version:  16.10.0
Operating System: Windows 10 21H1
Additional tools:

**Comment by alexander-akait** [comment]
Another reproducible example - https://github.com/akphi/issue-repo/pull/3
