### ISSUE TITLE
webpack5 upgrade find a Lot of error

### ISSUE THREAD

**Issue by lanmch** [webpack/webpack#14493]
# Bug report

**What is the current behavior?**
recently, i try to update the webpack version from 4 to 5.
All configuration not change(except the webpack change docs told me what property should I remove or change)
But when I run my project, I find too much errors like 'Super expression must either be null or a function', and these error all about occur on the npm modules.

can u help me to solve this problem?
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  5.45.1
Node.js version: 14.15
Operating System: mac OS

**Comment by lanmch** [comment]
> 请提供可重现的 repo

I think i cannot provide the detail. Because my project is too large, and there are too many configuration.
the project can run with webpack 4 of the configuration(like babel ,  other loader or plugin), but it can not run with webpack 5

**Comment by alexander-akait** [comment]
Can you provide stack trace of errors?

**Comment by lanmch** [comment]
```
Uncaught TypeError: Super expression must either be null or a function
    at _inherits (inherits.js?ed6d:5)
    at eval (hyperlink.js?c752:25)
    at eval (hyperlink.js?c752:396)
    at Module../node_modules/@platform-fe/comment/dist/view/web/components/textarea/editor-plugins/hyperlink.js (doc_index_vendors.[dev].js:1601)
    at __webpack_require__ (manifest_app.[dev].js:31)
    at eval (editor.js:13)
    at Module../node_modules/@platform-fe/comment/dist/view/web/utils/editor.js (doc_index_vendors.[dev].js:1886)
    at __webpack_require__ (manifest_app.[dev].js:31)
    at eval (editor.js:10)
    at Module../node_modules/@platform-fe/comment/dist/view/web/helpers/editor.js
```

**Comment by lanmch** [comment]
> 生产版本有这个错误吗？请提供配置

I dont have any error with the development mode. It just occur when I run my project in chrome with webpack5.
about configuration its too many to show u

**Comment by alexander-akait** [comment]
Sorry without example or configuration nobody can help

**Comment by lanmch** [comment]
> 抱歉，没有示例或配置，没有人可以提供帮助

I think i might find some 'error configuration(loaders)' leads to these error.
I try to delete these loader configuration, and these error disappear.
About these configuration in webpack 4:
the first configuration is about compiling some modules of the es6 version of cjs, so we compile it with babel and use the property 'sourceType: unambiguous'.
the second configuration is about some npm modules' dist is es6 version, so we also pack it with babel-loader.
the function utils.getCacheLoader just use the babel-loader with babelrc file.

When I update the webpack version, these configuration might lead to these error. So no I have to delete them temporarily.

Note that some npm modules are in our company’s internal npm source, you may not be able to find them on npmjs.com.

Below is the configuration
```javascript
  {
          test: /\.jsx?$/,
          // cjs 的 es6 版本， babel 进行编译，但加入编译后 @babel/plugin-transform-runtime 会
          // 引入 import 语法，导致import 和 module.exports 混用，所以 sourceType 需要配置 'unambiguous'
          // https://github.com/webpack/webpack/issues/4039#issuecomment-419284940
          include: [,
            /node_modules\/use-context-selector/,
            /node_modules\/(yallist|lru-cache|core-decorators|shallowequal)/,
            /node_modules\/(split-on-first|strict-uri-encode)/,
            /node_modules\/p\-(queue|timeout|finally)/,
            /node_modules\/@bb\/doc-f-graph/,
            /node_modules\/d3-.*/,
            /node_modules\/highlight\.js/,
            /node_modules\/@ud\/biz-react/,
            /node_modules\/@pf\/suite-url-parser/,
            /node_modules\/@pf\/postcss-ccm-theme/,
            /node_modules\/parse5/,
          ],
          use: utils.getCacheLoader([
            getBabelLoader({
              cacheDirectory: true,
              sourceType: 'unambiguous',
            }),
          ]),
        },
 {
          test: /\.jsx?$/,
          // 有一些库的发布产物是es6,所以需要一起打包
          include: [
            /node_modules\/ismobilejs/,
            /node_modules\/@luk\/components/,
            /node_modules\/@ad/,
            /node_modules\/@pf\/sha-common/,
            /node_modules\/@pf\/sha-business/,
            /node_modules\/@pfe\/w-pc/,
          ],
          use: utils.getCacheLoader([
            getBabelLoader({
              cacheDirectory: true,
            }),
          ]),
        },

```

**Comment by alexander-akait** [comment]
`cache-loader` is deprecated and can lead to problems, please migrate on  https://webpack.js.org/configuration/cache/

**Comment by lanmch** [comment]
> `cache-loader`已弃用并可能导致问题，请在[https://webpack.js.org/configuration/cache/ 上](https://webpack.js.org/configuration/cache/)迁移 [](https://webpack.js.org/configuration/cache/)

I have removed cache loader in the 'utils.getCacheLoader' function, it is just a name

**Comment by lanmch** [comment]
> 也许你可以提供重现的步骤，没有看到代码/配置真的很难帮助，不需要提供整个配置/项目，只是其中的一部分来重现问题

sorry, i cant understand what did you say. The configuration which leads to error is on the top.
