### ISSUE TITLE
Webpack sourcemaps contain absolute URLs

### ISSUE THREAD

**Issue by rickihastings** [webpack/webpack#1450]
Hi all,

I'm having an issue with sourcemaps in a project I'm working on, it's quite an old code base and we're gradually moving components over to React + webpack so half of the code is built using other methods, so we're having to jump though some hoops. The issue is our sourcemaps are containing full absolute URLs, see below:

```
{
    "version" : 3,
    "sources" : [
        "webpack:///c:/Workspace/Project/Common/Modules/Example/factory.js",
        "webpack:///c:/Workspace/Project/src/modules/example/src/main.js",
        "webpack:///c:/Workspace/Project/~/react/react.js",
        "webpack:///c:/Workspace/Project/~/react/lib/React.js",
        "webpack:///c:/Workspace/Project/~/webpack/~/node-libs-browser/~/process/browser.js",
        "webpack:///c:/Workspace/Project/~/react/lib/EventPluginUtils.js",
        "webpack:///c:/Workspace/Project/~/react/lib/EventConstants.js",
        "webpack:///c:/Workspace/Project/~/react/lib/keyMirror.js",
        "webpack:///c:/Workspace/Project/~/react/lib/invariant.js",
        "webpack:///c:/Workspace/Project/~/react/lib/ReactChildren.js",
        "webpack:///c:/Workspace/Project/~/react/lib/PooledClass.js",
        "webpack:///c:/Workspace/Project/~/react/lib/ReactFragment.js",
        "webpack:///c:/Workspace/Project/~/react/lib/ReactElement.js",
        "webpack:///c:/Workspace/Project/~/react/lib/ReactContext.js",
        "webpack:///c:/Workspace/Project/~/react/lib/Object.assign.js"
    ],
    names: []
    ...
}
```

Obviously I don't want the `c:/Workspace/Project` part as that's the root of the project, this wouldn't be a problem during development but it causes issues when uploading our sourcemaps to sentry for error tracking. Any other webpack projects I've worked on just have a `webpack:///./[filename]` format. I've tried using cheap source maps and that fixes this, however we don't get to see our original code in sourcemaps before babel has transpiled it.

I tried looking through the source code, and it seems that whatever is transforming the `[resourcePath]` has full paths not relative to the project for some reason.

Thanks!

**Comment by sokra** [comment]
Set the `context` option to a common root directory.

**Comment by rickihastings** [comment]
This doesn't seem to have solved the issue, the `sources` array is still full of absolute paths even if I define the `context` option.

**Comment by rickihastings** [comment]
I've loaded the suspect line to https://github.com/webpack/webpack/blob/master/lib/SourceMapDevToolModuleOptionsPlugin.js#L17

If I set this to false the correct URLs are produced, what is this actually doing because if I set this to false, then it works fine and the source maps are still produced?

**Comment by alexw23** [comment]
Having the same issue too we end up with like `webpack:///../~/angular-credit-cards/src/index.js`

**Comment by danielbayerlein** [comment]
Does anyone have a solution for this problem? 😕
