### ISSUE TITLE
ERROR in RealContentHashPlugin: Some kind of unexpected caching problem occurred

### ISSUE THREAD

**Issue by andersk** [webpack/webpack#14514]
# Bug report

**What is the current behavior?**

After modifying a CSS file in my project that uses the webpack filesystem cache, I got this error from webpack:

```
ERROR in RealContentHashPlugin
Some kind of unexpected caching problem occurred.
An asset was cached with a reference to another asset (cf6a1d7431b4b61d80f8) that's not in the compilation anymore.
Either the asset was incorrectly cached, or the referenced asset should also be restored from cache.
```

I minimized a test case and bisected the bug to b16568a253d58910ddcc9fe473eb211fe359e775 “upgrade filename runtime module to full hash module when referencing a full hash chunk” (#14112).

**If the current behavior is a bug, please provide the steps to reproduce.**

Clone the minimal test case from https://gist.github.com/andersk/c468e3ea8e68af0e969de8d9dd74a8f1 and run:

```console
$ npm i

$ npx webpack
…
webpack 5.58.2 compiled successfully in 417 ms

$ echo >> style.css

$ npx webpack
…
ERROR in RealContentHashPlugin
Some kind of unexpected caching problem occurred.
An asset was cached with a reference to another asset (cf6a1d7431b4b61d80f8) that's not in the compilation anymore.
Either the asset was incorrectly cached, or the referenced asset should also be restored from cache.
Referenced by:
 - main.66a6b12d7cfb6f8092c5.js: ...i.miniCssF=e=>"main.cf6a1d7431b4b61d80f8.css",i.g=function()...

webpack 5.58.2 compiled with 1 error in 169 ms
```

**What is the expected behavior?**

This should build successfully.

**Other relevant information:**
webpack version: 5.58.2
Node.js version: 14.18.0
Operating System: Linux (NixOS 21.11)
Additional tools: css-loader 6.4.0, mini-css-extract-plugin 2.4.2, webpack-cli 4.9.1

**Comment by alexander-akait** [comment]
@andersk @shentr Please try https://github.com/webpack-contrib/mini-css-extract-plugin/releases/tag/v2.4.4
