### ISSUE TITLE
Better local import paths for Webpack?

### ISSUE THREAD

**Issue by gsklee** [webpack/webpack#1451]
Is there some way to achieve something like this in Webpack?

https://gist.github.com/branneman/8048520

That is, I can `import 'src/module/a';` instead of `import './src/module/a';` ?

**Comment by SpaceK33z** [comment]
Yes. Add this to your config:

```js
resolve: {
  root: path.join(__dirname, 'src'), // or wherever your src folder is located.
}
```

**Comment by gsklee** [comment]
Great, thanks!
