### ISSUE TITLE
bash: !css: event not found

### ISSUE THREAD

**Issue by kaiyulee** [webpack/webpack#1453]
Execute `webpack ./entry.js bundle.js --module-bind "css=style!css"` in bash (I'm using git bash on windows 10) will prompt this error `bash: !css: event not found`

### So-called Solution:
`webpack ./entry.js bundle.js --module-bind 'css=style!css'` use single quote instead!

**Comment by LeeHyungGeun** [comment]
Thank you. I also got the problem using git bash on windows 7 and I solved it with your solution.

**Comment by IngwiePhoenix** [comment]
Explanation: Bash actually does something when a ! is encountered within a string, or outside.

http://unix.stackexchange.com/a/3748

**Comment by FrankFan** [comment]
LOL

I met up with them same question.

**Comment by huangyanxiong01** [comment]
3q,very much!

**Comment by gustavolanna** [comment]
I'm having the same problem in mac

**Comment by gustavolanna** [comment]
Problem solved using single quotes

**Comment by carlpoole** [comment]
Encountered this problem on a mac too. As suggested, using single quotes fixes it.

**Comment by Ellacf** [comment]
3Q. I am having the same problem in mac.

**Comment by MapleGu** [comment]
Why?I am having the same problem in ubuntu1404?

**Comment by marvinhagemeister** [comment]
@MapleGu: Like @IngwiePhoenix already said: the !-sign is a special character in a bash terminal. Mac and pretty much any linux distro use bash for their terminal. Similar to php the single quotes make sure that the special characters or variables inside the string won't be executed.

**Comment by MapleGu** [comment]
@marvinhagemeister :3Q.I see.

**Comment by Passerby** [comment]
3q
