### ISSUE TITLE
Webpack errors when config is empty array

### ISSUE THREAD

**Issue by ksonnad** [webpack/webpack#1455]
webpack v1.12.1
node v4.0.0

webpack.config.js
```javascript
module.exports = [];
```

Running webpack with that config yields the following error:

```
.../node_modules/webpack/bin/webpack.js:53
var outputOptions = Object.create(options.stats || firstOptions.stats || {});
                                                               ^

TypeError: Cannot read property 'stats' of undefined
    at Object.<anonymous> (.../node_modules/webpack/bin/webpack.js:53:64)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3
```

Since arrays of configs are supported, it seems like empty arrays should be too (in which case webpack would just do nothing, I imagine).

Use case: 
I need to conditionally compile multiple bundles for different services based on environment.  Sometimes, one or more bundles are needed, so my config file exports an array of one of more configs.  Sometimes, no bundles are needed, so I'd like to export an empty array and have webpack do nothing.

**Comment by towry** [comment]
If it's an empty array, why dont just make the config file empty?
