### ISSUE TITLE
Webpack 5 triggers a slow V8 `concat` path resulting in significant performance degradation in some scenarios

### ISSUE THREAD

**Issue by eoin** [webpack/webpack#14580]
Early in Webpack 5 development the [`arrayToSetDeprecation`](https://github.com/webpack/webpack/blob/main/lib/util/deprecation.js#L72) helper was added to support migrating some objects from `Array` to `Set`. In order to maintain `Array`-like behaviour in `concat` the helper sets [`Symbol.isConcatSpreadable`](https://github.com/webpack/webpack/blob/746d3776142c9b8072be6e504ba0d34f4ba5dd75/lib/util/deprecation.js#L164). On V8, setting `Symbol.isConcatSpreadable` anywhere puts [all subsequent invocations](https://github.com/v8/v8/blob/bf4b542a1b31bbe8106e394b1dbeff02571dff4b/src/builtins/builtins-array.cc#L1460) of `concat` within an `Isolate` on [a slow path](https://github.com/v8/v8/blob/bf4b542a1b31bbe8106e394b1dbeff02571dff4b/src/builtins/builtins-array.cc#L1255). 

There are cases where this can result in significant performance degradation. In [this repro case](https://github.com/callstack/linaria/issues/797), builds go from 1s with Webpack 4 to 16s with Webpack 5. We came across this when debugging [this Linaria issue](https://github.com/callstack/linaria/issues/797), where our production build slowed from ~10s to 2m+. I wonder if this could be the cause of some issues in https://github.com/webpack/webpack/issues/12102.

**Comment by eoin** [comment]
For anyone who might be interested we did [a writeup](https://engineering.tines.com/blog/understanding-why-our-build-got-15x-slower-with-webpack) up how we tracked down this issue.

**Comment by zloirock** [comment]
@eoin deprecated versions of `core-js` (version < 3.3) cause the same problems, now about 20-30% of TOP 10000 websites use those deprecated versions. [It's `@@isConcatSpreadable` and (mainly) `@@species` feature detection, even without polyfilling.](https://github.com/zloirock/core-js/issues/679) Workarounds of those V8 whims were added 2+ years ago, but who read deprecation notes?

![image](https://user-images.githubusercontent.com/2213682/142706660-00f29b04-ea06-44ef-8a54-b09c57067261.png)
