### ISSUE TITLE
loading html string from bundle.js

### ISSUE THREAD

**Issue by ildella** [webpack/webpack#1460]
Hi. I have a webpack build to create an embeddable Form. Everything is webpack compliant, and bundled using require. Everything but two HTML files that are needed for the form. 
I can require the HTML files of course: 

require("html!./pages/custom.html");
require("html!./pages/follow.html");

The html is now in bundle.js but I do not know how to use it from the host page. Actually in the host page, the form is embedded this way: 

          
          <div data-bind="page: {id: 'custom', source: 'pages/custom.html''}"></div>
          <div data-bind="page: {id: 'follow', source: 'pages/follow.html'}"></div>
          

The "source" param can't work in the webpack version.  
One way is to write the actual html imported from the "source"  directly inside the <div> block. But I need to write some code that 

1. gets the HTML from bundle.js
2. inject it inside the <div data-bind="page: .... ></div>

Is this possible? How? Now the HTML required is a string exported but without any identifier...
Is there a better way to do this? 

Thanks.

**Comment by shama** [comment]
I'm not sure which template syntax `<div data-bind="page: {id: 'custom', source: 'pages/custom.html''}"></div>` is but their might have a way to dynamically create that binding with the library you're using. But I've never seen that syntax before so really have no idea.

Using the native browser API, you can do:

```js
var html = require("html!./pages/custom.html");
document.querySelector('form').innerHTML = html;
```

and it will place whatever HTML that has been bundled into the form.

See: https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML
