### ISSUE TITLE
Visually differences between build and server env.

### ISSUE THREAD

**Issue by alucardu** [webpack/webpack#14609]
# Bug report

**What is the current behavior?**
The build version of my React app is visually different from my server environment.

**If the current behavior is a bug, please provide the steps to reproduce.**
Link to github repo: https://github.com/alucardu/movieseat-react

![image](https://user-images.githubusercontent.com/779921/139665552-ebf0b9f4-b70f-4726-9f98-a1b900d21056.png)
![image](https://user-images.githubusercontent.com/779921/139666338-9b40e0d4-68b1-4993-a874-d0425e43f463.png)

The differences are small. But the icons seem a bit larger on the server environment (also the text in the inputfield is slightly). There is no issue with caching and the actual CSS of the elements is the same. The issue is also prevalent on my local build, so it's also not related to the server environment. 

**What is the expected behavior?**
Build should be the same visually as the server environment.

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

**Comment by alexander-akait** [comment]
Sorry, not related to webpack, please use stackoverflow for these questions

**Comment by alucardu** [comment]
No problem. My brain kinda freezed, my Chrome tab on the server was zoomed in to 110% and the build/production was at 100%. I thought I had reset it before I opened this question. My apologies.
