### ISSUE TITLE
Webpack 5 incorrect import in bundle

### ISSUE THREAD

**Issue by AAAstorga** [webpack/webpack#14601]
Hello everyone! I am running into a really weird webpack 5 bug with @loadable/component. The resolved module is not being imported correctly when looking at server.js output from webpack.

Webpack 4:
When bundling my code and requiring the @loadable/component package it looks like this:

/* harmony import */ var _loadable_component__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! @loadable/component */ "@loadable/component");
/* harmony import */ var _loadable_component__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(_loadable_component__WEBPACK_IMPORTED_MODULE_1__);
Webpack 5:

/* harmony import */ var _loadable_component__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! @loadable/component */ "@loadable/component");
Why is Webpack 5 missing the second line that Webpack 4 produces? This is the only module that is having issues. Because of what Webpack 5 produces I get TypeError: _loadable_component__WEBPACK_IMPORTED_MODULE_1__ is not a function. I've been trying to figure out what is going wrong here for a couple days and I am stumped. Anyone have any ideas?

This is the only place I am seeing this weird behavior and I have no idea why it is happening now. I appreciate the help!

Note: All my @Loadable packages are up to date.

"@loadable/babel-plugin": "^5.13.2",
"@loadable/webpack-plugin": "^5.15.1",
"@loadable/component": "^5.15.0",
"@loadable/server": "^5.15.0",
Edit: The component in question that is causing the "is not a function" error.

import React from "react";
import loadable, { DefaultComponent } from "@loadable/component";
import { LoadingPage } from "../LoadingPage";

export const loadablePage = <T extends {}>(loader: (props: T) => Promise<DefaultComponent<T>>) =>
  loadable(loader, {
    fallback: <LoadingPage />,
  });

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

**Comment by e1himself** [comment]
I have the same problem: webpack converts `import someFunc from 'somelib-in-node-modules'` that does not take into account default export.

```js
import someFunc from 'somelib-in-node-modules'; 

someFunc();
```

becomes

``js
/* harmony import / var somelib_in_node_modules__WEBPACK_IMPORTED_MODULE_1_ = __webpack_require__("somelib-in-node-modules");

somelib_in_node_modules__WEBPACK_IMPORTED_MODULE_1_();
```

which fails, because `somelib_in_node_modules__WEBPACK_IMPORTED_MODULE_1_` is an object `{ default: function() {...}  }`.

**Comment by e1himself** [comment]
The code responsible for unwrapping `{ default }` in Webpack 4:

[this.buildMeta](https://github.com/webpack/webpack/blob/444e59f8a427f94f0064cae6765e5a3c4b78596d/lib/RuntimeTemplate.js#L215-L220)

The code responsible for unwrapping `{ default }` in Webpack 5:

https://github.com/webpack/webpack/blob/27411f8f0f404aa6779810726cca7dc9fac53af3/lib/RuntimeTemplate.js#L684-L692

So this is why previously there was a `_default` variable introduced with `__webpack_require__.n()` and now there's not -- the condition has changed. Will dig deeper.

**Comment by e1himself** [comment]
@AAAstorga 

Please see #14836

So the problem is actually `@loadable/component` improperly ships its CommonJS code with ES-style-shaped exports: `{ __esModule: true, default: ... }`, which is not really a CommonJS module.

A default export in CommonJS is `module.exports = yourSymbol` and not `module.exports = { default: yourSymbol }`.
