### ISSUE TITLE
target: 'nwjs' with node.__filename: true, displays "Uncaught ReferenceError: __filename is not defined"

### ISSUE THREAD

**Issue by sirisian** [webpack/webpack#14600]
# Bug report

**What is the current behavior?**

```Uncaught ReferenceError: __filename is not defined```
```
/******/ 	/* webpack/runtime/readFile chunk loading */
/******/ 	(() => {
/******/ 		__webpack_require__.b = require("url").pathToFileURL(__filename);
```
This is the only instance of __filename in the whole generated bundle.

**If the current behavior is a bug, please provide the steps to reproduce.**

With the latest nwjs and webpack 5. My webpack.config.js is like this, but with loader rules:
```js
module.exports = {
	devtool: 'source-map',
	entry: {
		main: './src/main.js',
	},
	target: 'nwjs',
	node: {
		__dirname: true,
		__filename: true
	},
	output: {
		publicPath: 'src/',
		filename: '[name]-bundle.js',
		path: path.resolve(__dirname, ''),
	},
};
```
I have my index.html and main.js in a src folder in the nwjs folder. The package.json that nwjs and my project looks like:
```json
{
	"name": "MyProject",
	"main": "src/index.html",
	"chromium-args": "",
	"window": {
		"kiosk": false,
		"width": 600,
		"height": 600,
		"always_on_top": true
	},
	"webkit": {
		"plugin": true
	},
	"node-remote": [],
	"permissions": [
		"cookies",
		"serial",
		"*"
	],
	"scripts": {
		"build": "webpack --config webpack.config.js"
	},
	"dependencies": {
	},
	"devDependencies": {
		"@babel/core": "^7.15.8",
		"@babel/preset-env": "^7.15.8",
		"babel-loader": "^8.2.3",
		"copy-webpack-plugin": "^9.0.1",
		"css-loader": "^6.5.0",
		"style-loader": "^3.3.1",
		"terser-webpack-plugin": "^5.2.4",
		"webpack": "^5.60.0",
		"webpack-cli": "^4.9.1"
	}
}
```
The index.html is very basic, but I'll include it in case I'm doing something wrong:
```html
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="no-cache">
	<meta http-equiv="Expires" content="-1">
	<meta http-equiv="Cache-Control" content="no-cache">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
	<title>My Project</title>
	<script type="module" src="main-bundle.js"></script>
<script>
document.addEventListener('DOMContentLoaded', async e => {
	//...
});
</script>
</head>
<body></body>
</html>
```

**What is the expected behavior?**

I'm not sure on the specifics, but if I set __filename manually to ```''``` that tries to load resources from say:
```file:///C:/Users/Username/Desktop/src/fonts/Roboto.woff```
What I'd expect is:
```file:///C:/Users/Username/Desktop/MyProject/src/fonts/Roboto.woff```

Everything works if I manually change __filename to be ```'./'```:
```__webpack_require__.b = require("url").pathToFileURL('./');```

So I'm guessing __filename should be set to './' as a global? That the bundle is generated with it undefined seems like maybe something recent was changed, so perhaps this is a regression. I didn't test old versions of webpack or nw.js.

**Other relevant information:**
webpack version:  5.60.0 and webpack-cli is 4.9.1
Node.js version: v14.18.0
Operating System: Ubuntu
Additional tools:

**Comment by alexander-akait** [comment]
Please read https://github.com/nwjs/nw.js/issues/1319

**Comment by alexander-akait** [comment]
Also you use `<script type="module" src="main-bundle.js"></script>` there are not `__dirname` and `__filename` in ESM

**Comment by alexander-akait** [comment]
For using ESM you should do more configurations https://webpack.js.org/configuration/experiments/#experimentsoutputmodule

**Comment by sirisian** [comment]
I'm aware that __filename won't exist in the browser context in nwjs. That's why I was wondering how to set the value. I use document.body and other web features which is why I'm not using require() and ```output.library.type: 'commonjs'``` features. (I know I could pass in these things, but this codebase is used in the web also and other projects, so it wouldn't be ideal).

I tried a number of ideas with outputModule before, but was getting errors similar to [this bug report in the nw.js repo](https://github.com/nwjs/nw.js/issues/7639). Perhaps I'm just using it wrong though. Tried again using:

```js
const path = require('path');
const webpack = require('webpack');
const CopyPlugin = require("copy-webpack-plugin");

module.exports = {
	devtool: 'source-map',
	context: path.resolve(__dirname, ''),
	entry: {
		main: {
			import: './src/main.js',
			library: { type: 'module' },
		}
	},
	target: 'nwjs',
	node: {
		__dirname: true,
		__filename: true
	},
	output: {
		publicPath: 'src/',
		filename: '[name]-bundle.js',
		path: path.resolve(__dirname, ''),
		chunkFormat: 'module', // This gets rid of the __filename lines it seems?
		environment: { module: true }
	},
	module: {
		rules: [
			{
				test: /\.css$/i,
				oneOf: [
					{ assert: { type: "css" }, loader: "css-loader", options: { exportType: 'css-style-sheet' } },
					{ use: ["style-loader", "css-loader"] }
				]
			},
			{
				test: /\.(png|jpe?g|gif|svg)$/,
				type: 'asset/resource',
				generator: {
					filename: './images/[name][ext]'
				}
			},
			{
				test: /\.(woff(2)?|ttf|eot|svg)(\?v=\d+\.\d+\.\d+)?$/,
				type: 'asset/resource',
				generator: {
					filename: './fonts/[name][ext]'
				}
			},
			{
				test: /\.node$/,
				use: 'node-loader'
			}
		],
	},
	plugins: [
		new CopyPlugin({
			patterns: [
				{ from: 'src/index.html' }
			],
		})
	],
	resolve: {
		modules: [
			path.resolve(__dirname, 'src'),
			'node_modules',
		]
	},
	externalsType: 'module',
	experiments: {
		outputModule: true,
	},
};
```
I just get ```Uncaught TypeError: Failed to resolve module specifier "module". Relative references must start with either "/", "./", or "../".``` whenever I try to ```import fs from 'fs-extra';``` or any other node-code. The node-main workaround might work, but it has the same issue I believe where you can't just access a global document browser context object.

My previous comment about just changing ```const __filename = './';``` really does seem the simplest for me. This makes all the browser and nw features global. Seems like every other method breaks this simplicity.

For reference, my real full config is:

```js
const path = require('path');
const TerserPlugin = require("terser-webpack-plugin");
const webpack = require('webpack');
const { DuplicatesPlugin } = require("inspectpack/plugin");
const CopyPlugin = require("copy-webpack-plugin");

module.exports = {
	devtool: 'source-map',
	context: path.resolve(__dirname, ''),
	entry: {
		container: './src/container.js'
	},
	target: 'nwjs',
	node: {
		__dirname: true,
		__filename: true
	},
	output: {
		publicPath: 'src/',
		filename: '[name]-bundle.js',
		path: path.resolve(__dirname, ''),
	},
	module: {
		rules: [
			{
				test: /pdf\.worker\.js$/,
				type: 'asset/inline',
				generator: {
					dataUrl: content => {
						return content.toString();
					}
				}
			},
			{
				test: /\.css$/i,
				oneOf: [
					{ assert: { type: "css" }, loader: "css-loader", options: { exportType: 'css-style-sheet' } },
					{ use: ["style-loader", "css-loader"] }
				]
			},
			{
				test: /\.(png|jpe?g|gif|svg)$/,
				type: 'asset/resource',
				generator: {
					filename: './images/[name][ext]'
				}
			},
			{
				test: /\.(woff(2)?|ttf|eot|svg)(\?v=\d+\.\d+\.\d+)?$/,
				type: 'asset/resource',
				generator: {
					filename: './fonts/[name][ext]'
				}
			},
			{
				test: /\.node$/,
				use: 'node-loader'
			}
		],
	},
	plugins: [
		new CopyPlugin({
			patterns: [
				{ from: 'src/index.html' }
			],
		}),
		new DuplicatesPlugin({
			verbose: true
		})
	],
	resolve: {
		modules: [
			path.resolve(__dirname, 'src'),
			'node_modules',
		]
	},
	optimization: {
		usedExports: true,
		minimize: false,
		minimizer: [
			new TerserPlugin({
				extractComments: false
			}),
		],
	}
};
```

```html
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="no-cache">
	<meta http-equiv="Expires" content="-1">
	<meta http-equiv="Cache-Control" content="no-cache">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
	<title>Container</title>
	<script type="module" src="container-bundle.js"></script>
<script>
document.addEventListener('DOMContentLoaded', async e => {
	try {
		window.InitializeContainer();
	} catch (err) {
		console.log(err.stack || err);
	}
});
</script>
</head>
<body></body>
</html>
```

When I build I add ```const __filename = './';``` to the top of the bundle. This makes everything work.

**Comment by alexander-akait** [comment]
Can you create small reproducible repo and I will look

**Comment by sirisian** [comment]
https://github.com/sirisian/nwjs-webpack

I created instructions in the README. I used the nw package to try to make it streamlined so it puts everything in the dist folder and can be ran.

I included examples of the various loaders I use so that we can verify the bundle is correct. Noticed a new error though other than the __filename issue. I changed node-loader because it was creating non-relative paths and switched to webpack-asset-relocator-loader. That's creating ```Uncaught ReferenceError: __dirname is not defined``` errors. I cannot for the life of me get rid of them or understand what the issue is. I thought it was because I was using target: 'nwjs' and not 'node', but I have no idea.

I'll keep working on this tomorrow, but you might notice the issue immediately, so I decided update.

**Comment by sokra** [comment]
`target: "nwjs"` is not correct, when including the bundle via `<script>`. That's just a normal `target: "web"`

**Comment by saulpalv** [comment]
i am experiencing the same problem when loading fonts in css font face, if the css font face import is commented out from the typescript file it works, but if presents the font load fails, and works when i set the target to electron-main

**Comment by saulpalv** [comment]
i managed to get font load working by downgrading from webpack 5 to webpack 4, indeed the porblem was the generated asset serving path, was incorrect in webpack 5, the following list show the  webpack 4 pckage versions i got working

1. style-loader@2.0.0
2. css-loader@5.2.7
3. url-loader@4.1.1
4. webpack@4.46.0
5. @types/webpack@4.41.32
6. webpack-cli@4.9.1
7.  webpack-dev-server@4.7.1
8. ts-loader@8.3.0

**Comment by saulpalv** [comment]
For some practical cases `electron-renderer` target should behave as `nwjs` target

**Comment by vankop** [comment]
you probably want to use `mock` option, see https://webpack.js.org/configuration/node/
