### ISSUE TITLE
When I update webpack 4 to webpack 5, I get a manifest error.

### ISSUE THREAD

**Issue by lanmch** [webpack/webpack#14608]
# Bug report

**What is the current behavior?**
when I update version of webpack to 5, I get an error about the manifest.
![image](https://user-images.githubusercontent.com/37408756/139649657-39342129-1ce8-47ef-84e1-26a7cce355f7.png)
But when I delete the property: optimization.runtimeChunk, there is no error. How can I solve it with this property?

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  5.51.0
Node.js version: 14.16
Operating System: macos

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

Please fill out all fields, we can't help you without it

**Comment by lanmch** [comment]
There was an issue before, I showed you my configuration, but you just suggested that I update the latest package, but this is of no use

**Comment by alexander-akait** [comment]
Sorry we can't help you without additional information, it's impossible to just guess
