### ISSUE TITLE
Webpack is tree-shaking away some used imports in a monorepo

### ISSUE THREAD

**Issue by vpukhanov** [webpack/webpack#14607]
# Bug report

**What is the current behavior?**

Webpack is tree-shaking away some imports in a monorepo which are actually used, which breaks the output bundle at runtime.

**If the current behavior is a bug, please provide the steps to reproduce.**

Repro with detailed description in README here: https://github.com/vpukhanov/webpack-treeshaking-repro

**What is the expected behavior?**

```
npm install
npm run bootstrap
npm start
```

**Expected result:** program runs successfully and outputs `30` to console.

**Other relevant information:**
webpack version:  5.61.0
Node.js version: 14.18.0
Operating System: macOS 11.6
Additional tools: -

**Comment by vankop** [comment]
use `include: path.resolve(__dirname, 'src'),` for `module.rules`

**Comment by vpukhanov** [comment]
Thank you, this works, but in that case my monorepo dependencies do not go through `babel-loader` and transforms are not applied (in the repro example the use of async in `@local/important-function-package` does not get transformed).

**Comment by vankop** [comment]
I see some strange bug. Try to use only babel, for me works fine. (change main to `src/index.ts`)

**Comment by vpukhanov** [comment]
In this sample repo this is possible, because only the `babel-loader` is used, but in our actual project we depend on multiple loaders for different file types, so we can't really use babel directly. We have a workaround for now, so this isn't a blocker for us. Would be great to get this fixed anyway 👍🏻

**Comment by sokra** [comment]
To fix the problem add `sourceType: 'unambiguous',` to the babel options.

Otherwise babel assumes that all files are `ESM` by default. Your CommonJs modules are treated as ESM without any exports in that case.

**Comment by vpukhanov** [comment]
Thanks so much, this works great 🤗
