### ISSUE TITLE
Feature request: Allow asset modules to also output linked source maps

### ISSUE THREAD

**Issue by noinkling** [webpack/webpack#14604]
## Feature request

**What is the expected behavior?**

When a CSS/JS file is loaded as an [asset module](https://webpack.js.org/guides/asset-modules/) using `type: 'asset/resource'`, and it contains a relative `sourceMappingURL`, there should be a way to emit that source map file along with the CSS/JS file.

**What is motivation or use case for adding/changing the behavior?**

Vendor libraries sometimes come with precompiled CSS styles (or JS) that you want in your dependency graph, but don't want to process, so loading it as an `asset/resource` module is preferred. For example if you install the `bootstrap` package, you can `import 'bootstrap/dist/bootstrap.min.css'` (maybe in production you make it an [external](https://webpack.js.org/configuration/externals/) and use a CDN). This file has a `sourceMappingURL` that references the `bootstrap.min.css.map` file in the same folder. In development it would be nice to also output/serve this source map in order to see the LESS source in devtools.

[source-map-loader](https://webpack.js.org/loaders/source-map-loader/) is supposed to help with this kind of thing, however it   works by letting Webpack process the source map (as if it was generated) and strips the comment from the CSS/JS (expecting another loader to add one back in later). If you try to use it together with asset modules, the comment is missing from the output file, and nothing else happens. Of course there's probably some combination of loaders/plugins that would make it work, but that defeats the point of avoiding unnecessary processing, and seems excessive when all that's essentially needed is a file copy (+maybe a rename).

Currently using `copy-webpack-plugin` seems to be the best alternative, but that loses the benefit of being able to import the file and have it be part of the dependency graph, with all the other downsides that entails.

**How should this be implemented in your opinion?**

I'm not sure what's technically feasible or desirable. Maybe `source-map-loader` could have a mode specifically for asset modules, though I don't know how you would make the two sides integrate under-the-hood.

**Are you willing to work on this yourself?**

I don't know enough about Webpack internals to feel like I could contribute significantly.

**Comment by alexander-akait** [comment]
`type: 'asset/resource'` can't contain source maps, `copy-webpack-plugin` is valid usage

**Comment by noinkling** [comment]
Let's say I do this:

```
type: 'asset/resource',
use: [
  'css-loader',
  'source-map-loader',
]
```

It doesn't work because css-loader generates a JS module and that becomes the output "CSS" file. Is there a way to evaluate it back to CSS source before asset modules takes over?

Alternatively let's say I use MiniCssExtractPlugin:

```
use: [
  MiniCssExtractPlugin.loader,
  'css-loader',
  'source-map-loader',
]
```

By default this creates a single combined CSS file for the entire initial chunk. I don't know if you can even configure it to behave like `asset/resource`, but if you can, it's no doubt complicated.

----
After thinking about it, I guess what I really want is a loader that treats `sourceMapURL` references like imports/`url()`/etc. Then I could have a config like this:

```
module: {
  rules: [
    {
      test: /foo\.min\.css$/,
      type: 'asset/resource',
      use: ['new-source-map-loader'],
    },
    {
      test: /\.(css|js).map$/,
      type: 'asset/resource',
    },
  ]
}
```

I assume a loader like that would be possible?

**Comment by alexander-akait** [comment]
I don't understand what you want to achieve

**Comment by alexander-akait** [comment]
Please use `source-map-loader` as pre loader and as separated loader, as in docs https://github.com/webpack-contrib/source-map-loader#getting-started
