### ISSUE TITLE
`host` option for lazyCompilation is `number` instead of `string` in option schema

### ISSUE THREAD

**Issue by karmeleon** [webpack/webpack#14617]
# Bug report

**What is the current behavior?**
Webpack expects `host` to be a `number` instead of a `string`, so attempting to give the lazy compilation experiment a hostname to listen on causes Webpack to error out on starting.

**If the current behavior is a bug, please provide the steps to reproduce.**
Configure the lazy compilation experiment with a hostname like this:

```
experiments: {
   lazyCompilation: {
       backend: {
            listen: {
                host: `www.${user}.dev.website.com`, // errors on Webpack boot because a number is expected
                port: 55555,
            },
            protocol: 'http',
       },
    },
}
```

Then, start up a webpack dev server.

**What is the expected behavior?**
Webpack's lazy compilation feature should boot up and serve lazily compiled code on the hostname and port that the user has provided. When editing [the offending line](https://github.com/webpack/webpack/blob/adc5fdda5810bafef2289191f79c06d9135863b6/schemas/WebpackOptions.json#L1641) in the options schema to make `host` a `string`, this behavior occurs.

**Other relevant information:**
webpack version:  5.60.0
Node.js version: 14.17.4
Operating System: Ubuntu 18.04 x86-64
Additional tools: webpack-dev-server@3.10.1

**Comment by snitin315** [comment]
Related PR - https://github.com/webpack/webpack/pull/14599
