### ISSUE TITLE
UglifyJsPlugin: mangle property names via option.

### ISSUE THREAD

**Issue by IngwiePhoenix** [webpack/webpack#1462]
Within the UglifyJS plugin, this little bit of code would be helpful: https://github.com/jrhite/grunt-contrib-uglify/blob/master/tasks/lib/uglify.js#L120-L137

It would be apriciated if this was added in WebPack. Of course, I'd voluteer for a PR, if needed :)

**Comment by bebraw** [comment]
You can pass `mangle` to `UglifyJsPlugin` now so this should be possible.
