### ISSUE TITLE
[Proposal] Target: Separate electron into electron-main and electron-renderer

### ISSUE THREAD

**Issue by chentsulin** [webpack/webpack#1463]
Electron have two different type process - main process (more like node) and renderer process (more like browser). Using electron target in electron renderer process will break some of browser module, so I build a module for this: https://github.com/chentsulin/webpack-target-electron-renderer.

@sokra Is any possible can make this become a bulit-in target? Maybe separate electron into `electron-main` (original electron target) and `electron-renderer` two different targets.

**Comment by sokra** [comment]
Sounds useful. Do you want to do a PR? Ensure backward-combatibility.

**Comment by chentsulin** [comment]
I prepare a PR in #1467. I am not familiar with those Plugins, please check this. Thank you.

**Comment by chentsulin** [comment]
Released in 1.x and 2.x

**Comment by naivefun** [comment]
What is the difference between electron-main & renderer? Can I just use main?
