### ISSUE TITLE
`url` in `query` is handled incorrect while writing custom loader

### ISSUE THREAD

**Issue by leftstick** [webpack/webpack#1466]
Once i want to develop a custom loader which can receive an `JSON` options in the `query` as following:

``` javascript
var urls = JSON.stringify({
    value: {
        cdnUrl: 'http://xxx.domain.com/imgs/'
    }
});

module.exports = {
    entry: {
        index: path.resolve(__dirname, 'public', 'js', 'index.js')
    },
    output: {
        path: path.resolve(__dirname, '..', '..', '..', '..', 'public', 'build', 'js'),
        filename: '[name].bundle.js',
        chunkFilename: '[id].bundle.js',
        publicPath: '/build/js/'
    },
    module: {
        loaders: [
            {
                test: /\.scss$/,
                loader: 'my-custom-loader?' + urls
            }
        ]
    }
};
```

The thing i found is the `this.query` always remove one `/` right after `http:` from the passed options:

``` javascript
module.exports = function(source) {
    'use strict';
    this.cacheable && this.cacheable();
    console.log(this.query);//?{"value":{"cdnUrl":"http:/xxx.domain.com/imgs/"}}
};
```

Is this by design?

**Comment by sokra** [comment]
No. I don't think this is caused by webpack. It just passes the string to the loader.

**Comment by sokra** [comment]
Or maybe it's caused by the resolving stuff, which tries to eliminate duplicate path separators.

**Comment by leftstick** [comment]
@sokra HI, do you have any suggestion about this issue? Thanks

**Comment by leftstick** [comment]
And the `\` will be replaced to `/` which is not expected. See following:

```javascript
var urls = JSON.stringify({
    options: {
        interpolate: {
            pattern: '%([\\s\\S]+?)%'
        }
    },
    value: {
        color: '#000'
    }
});
```

While passing this to `loader`, it should be `?{"options":{"interpolate":{"pattern":"%([\\\\s\\\\S]+?)%"}},"value":{"color":"#000"}}`.

But in fact, it is transformed to `?{"options":{"interpolate":{"pattern":"%([//s//S]+?)%"}},"value":{"color":"#000"}}`

Is there any clue for solving this?

**Comment by leftstick** [comment]
There is still no fix or work around for this currently. So sad

**Comment by bebraw** [comment]
Can someone confirm this on webpack 2?
