### ISSUE TITLE
Performance issue with DefaultStatsPrinterPlugin.js

### ISSUE THREAD

**Issue by martinsp** [webpack/webpack#14678]
# Bug report

**What is the current behavior?**

DefaultStatsPrinterPlugin.js is slow to process/display results when large error message is returned.

**If the current behavior is a bug, please provide the steps to reproduce.**

Reproduction in repo: https://github.com/martinsp/webpack-printer-issue running `npx webpack` will take significant amount of time

I have narrowed the issue down to this line: https://github.com/webpack/webpack/blob/14dd4f912c013f060bf7843a3d5462a51ff3051b/lib/stats/DefaultStatsPrinterPlugin.js#L1163 when it's commented out then the webpack command completes within a short amount of time

**What is the expected behavior?**

webpack results shown in a short amount of time

**Other relevant information:**
webpack version:  5.62.1
Node.js version: v17.0.1
Operating System: macOS Monterey
Additional tools:

**Comment by alexander-akait** [comment]
Thanks

**Comment by martinsp** [comment]
Unfortunatelly I don't see a lot of improvement after the fix. 

These are my findings after running `time yarn run webpack` with the code in https://github.com/martinsp/webpack-printer-issue

```
# current 5.62.1 release
webpack 5.62.1 compiled with 2 errors in 1314 ms
yarn run webpack  81.29s user 0.23s system 100% cpu 1:20.94 total

# with uncommented regex line
webpack 5.62.1 compiled with 2 errors in 1316 ms
yarn run webpack  2.42s user 0.13s system 127% cpu 2.005 total

# with "webpack": "webpack/webpack#12e028518a726c4ebf336ecfe823d27f51776b13" in package.json
webpack 5.62.1 compiled with 2 errors in 1332 ms
yarn run webpack  69.06s user 0.16s system 100% cpu 1:08.57 total
```

Maybe there is a way to return early from `formatError` in `DefaultStatsPrinterPlugin.js` when webpack is run with `--no-color` option?

**Comment by alexander-akait** [comment]
You have very big error message, and regexp spend time to highlight error message, why do not avoid errors? It is non normal usage and the error should be fixed

**Comment by martinsp** [comment]
I agree that this is somewhat an edge case, maybe mini-css-extract-plugin should limit the size of an error message.

I would gladly like to have a "write error-less code" superpower unfortunately I don't :(

The thing is that mini-css-extract-plugin is included in the default config of rails/webpacker project and if I include large css framework like Bootstrap and I have a typo/error in a css file, the compilation gets stuck for at least 1 minute. For my own usage I can fork the webpack project and return early from formatError and never worry about that again in my own projects. But I think quite a few users would be bitten by this behavior because this can be triggered from default Rails 6 install.

I don't mind if you close the ticket. I know how to workaround the issue if I'll encourage it during refactoring in some of my projects.

**Comment by vankop** [comment]
@martinsp yes this is on webpack side
