### ISSUE TITLE
[loader] Failed to decode downloaded font. OTS parsing error: invalid version tag

### ISSUE THREAD

**Issue by io3** [webpack/webpack#1468]
my config:

```
            { test: /\.eot/, loader: 'url-loader?limit=100000&mimetype=application/vnd.ms-fontobject' },
            { test: /\.woff2/, loader: 'url-loader?limit=100000&mimetype=application/font-woff2' },
            { test: /\.woff/, loader: 'url-loader?limit=100000&mimetype=application/font-woff' },
            { test: /\.ttf/, loader: 'url-loader?limit=100000&mimetype=application/font-ttf' }
```

chrome console:

```
Failed to decode downloaded font: data:application/font-woff2;base64,bW9kdWxlLmV4cG9ydHMgPSAiZGF0YTphcHBsaWNh…dXbXR0MlhlVWZrVDBjZUhZTHVWSFlCVFJoMU4waUtEeHE0bHd0L01NcWZUZS9IL1R1MzlYIg==
OTS parsing error: invalid version tag
```

**Comment by SimenB** [comment]
Have you tried added `$`'s to the end of `test`? Like `test: /\.eot$/,`

**Comment by io3** [comment]
But the url is `.woff2?v=4.4.0` and `.woff2?xxxx`

**Comment by io3** [comment]
Thank you. It works when the test is `/\.woff2(\?\S*)?$/`.

**Comment by skeefo** [comment]
I have similar (probably) problem. 
> Failed to decode downloaded font: http://localhost:8080/d396b5051cc2b597286ba6be02bd1327.woff2
> OTS parsing error: Failed to convert WOFF 2.0 font to SFNT
> Failed to decode downloaded font: http://localhost:8080/1a5f7cb348ebfe17ee45a78fac811c1d.woff
> OTS parsing error: incorrect file size in WOFF header
> Failed to decode downloaded font: http://localhost:8080/06d05732fc1f7dbb1bf6f9d4b2b895f4.ttf
> OTS parsing error: incorrect entrySelector for table directory

config is 
```
      { test: /\.woff(\?.*$|$)/, loader : 'file-loader' },
      { test: /\.woff2(\?.*$|$)/, loader : 'file-loader' },
      { test: /\.ttf(\?.*$|$)/, loader : 'file-loader' },
      { test: /\.eot(\?.*$|$)/, loader : 'file-loader' },
      { test: /\.svg(\?.*$|$)/, loader : 'file-loader' },
```

**Comment by dodyargentina** [comment]
Please verify on .css file if the url path for fonts are ok. It works for me.

**Comment by isramv** [comment]
this is my config:
```
{ test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: "url-loader?limit=10000&minetype=application/font-woff" },
            { test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: "file-loader" }
```

**Comment by hmichelkernix** [comment]
Hello @isramv, on your snippet, I think there is a typo on `minetype`, shouldn't be `mimetype` ?

**Comment by mbifulco** [comment]
I'm having this same issue, and none of the above seem to work for me.

**Comment by barberj** [comment]
@mbifulco any luck?

**Comment by mbifulco** [comment]
Not yet, unfortunately :/

**Comment by refaelos** [comment]
@mbifulco if you find anything I'd love to see that as well .. :disappointed:

**Comment by StaticSphere** [comment]
Thanks, @isramv !!!  This worked great for me.

**Comment by aspirisen** [comment]
Have the same

**Comment by Lacroute** [comment]
Didn't work neither, but now it's ok. What I did: 
```
{
        test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/,
        loader: 'url',
        query: {
          limit: 10000,
          mimetype: "application/font-woff",
          name: utils.assetsPath('fonts/[name].[hash:7].[ext]')
        }
      },
      {
        test: /\.(eot|ttf|otf)(\?.*)?$/,
        loader: 'url',
        query: {
          limit: 10000,
          name: utils.assetsPath('fonts/[name].[hash:7].[ext]')
        }
      },
```

I also re-converted my fontfiles using online convertors, and now it works like a charm.

**Comment by designbyadrian** [comment]
@Lacroute What is "utils" in your example?

**Comment by lubien** [comment]
I'd like to share the solution to my problem that's fairly same as yours for those who google they way out here (like me).

Given my folder structure
```sh
/ # root of web server
   css/
       file-that-import-fonts.css
   fonts/
       font-file.ext
```

The output css file was trying to import font files at the same folder level of it.

So it always hit 404 `/css/font.x` and my server rendered 404 error was mistaken as a broken font. That's why `Failed to decode downloaded font. OTS parsing error: invalid version tag`.

The following snippet solved:

```js
{
  test: /\.(otf|eot|svg|ttf|woff|woff2)$/,
  loader: 'file-loader',
  query: {
    outputPath: 'fonts/',
    publicPath: '../fonts/' // That's the important part
  }
},
```

Now my font files are properly referenced within my css file.

**Comment by Lacroute** [comment]
@designbyadrian sorry I didn't see `utils` was not defined...

I adapted my config from [this template](https://github.com/vuejs-templates/webpack/blob/master/template/build/webpack.base.conf.js). So `utils` is the require of this file > https://github.com/vuejs-templates/webpack/blob/master/template/build/utils.js

**Comment by Gynidark** [comment]
Hi @isramv, thank you !

**Comment by vchyzhevskyi** [comment]
Recently I also had the same problem, the following webpack config script snipped is solved the issue:

```
    {
      test: /\.svg(\?v=[0-9]\.[0-9]\.[0-9])?$/,
      loader: 'url?limit=65000&mimetype=image/svg+xml&name=/[name].[ext]'
    },
    {
      test: /\.woff(\?v=[0-9]\.[0-9]\.[0-9])?$/,
      loader: 'url?limit=65000&mimetype=application/font-woff&name=/[name].[ext]'
    },
    {
      test: /\.woff2(\?v=[0-9]\.[0-9]\.[0-9])?$/,
      loader: 'url?limit=65000&mimetype=application/font-woff2&name=/[name].[ext]'
    },
    {
      test: /\.[ot]tf(\?v=[0-9]\.[0-9]\.[0-9])?$/,
      loader: 'url?limit=65000&mimetype=application/octet-stream&name=/[name].[ext]'
    },
    {
      test: /\.eot(\?v=[0-9]\.[0-9]\.[0-9])?$/,
      loader: 'url?limit=65000&mimetype=application/vnd.ms-fontobject&name=/[name].[ext]'
    }
```

The most important thing from the config above is _name_ query parameter for url loader, with my config fonts will be rendered as <host>/<fontfile>, you may prefixed this with, for example, fonts: `&name=/fonts/[name].[ext]`

**Comment by naulacambra** [comment]
@vchyzhevskyi thanks!! It worked after few hours searching a solution

**Comment by Lacroute** [comment]
@vchyzhevskyi this way you'll encode your fonts in base64 into your css file no ? Could be better to have font files to light the weight of your app..

**Comment by cyberhck** [comment]
it worked for me after I specify the format like this:

```css
@font-face {
    font-family: "shop-icons";
    src: url(node_modules/mypkg/fonts/shop-icons.svg) format("svg"),
        url(node_modules/mypkg/fonts/shop-icons.ttf) format("truetype"),
        url(node_modules/mypkg/fonts/shop-icons.eot),
        url(node_modules/mypkg/fonts/fonts/shop-icons.woff) format("woff");
}
```
Initially I didn't have format and my style looked like:
```css
@font-face {
    font-family: "shop-icons";
    src: url(node_modules/mypkg/fonts/shop-icons.svg),
        url(node_modules/mypkg/fonts/shop-icons.ttf),
        url(node_modules/mypkg/fonts/shop-icons.eot),
        url(node_modules/mypkg/fonts/fonts/shop-icons.woff);
}
```

**Comment by timotew** [comment]
Has Similar issue, This works for me:
`{
			test: /\.(eot|woff|ttf|svg)$/,
			loaders: ["file?name=[path][name].[ext]?[hash]"]
		  },
		  {
			test: /\.woff2(\?\S*)?$/,
			loaders: ["file?name=[path][name].[ext]?[hash]"]
		  }`

**Comment by Pushplaybang** [comment]
none of these solutions are working for me.

still getting the error :)

**Comment by kaankucukx** [comment]
@Pushplaybang have u realized wuts going on ? me either having the same erros and still cant figure it out.. :(

**Comment by Pushplaybang** [comment]
@kaankucukx  - ok, will try that out. thanks.

**Comment by jessiezf** [comment]
> I removed all other config and used this:
> 
> ```
> { test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: "url-loader?limit=10000&minetype=application/font-woff" },
> { test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: "file-loader" }
> ```
> I hope this helps someone else too.
> remember: remove other font test configurations for fonts.

This works for me thinks

**Comment by vis97c** [comment]
> @Pushplaybang have u realized wuts going on ? me either having the same erros and still cant figure it out.. :(
> 
> Edit :
> 
> I come up with this. simply removed the loader and it worked.
> 
> I have to mention, my build is with **Vue Cli 3** and applying this configuration on **vue.config.js**
> 
> Hope this helps. 🎉
> 
> ```js
>        {
>           test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/,
>         }
> ```

This solved the issue, thanks!!

**Comment by ZeroByter** [comment]
> { test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: "url-loader?limit=10000&minetype=application/font-woff" },
> { test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: "file-loader" }

Strangely, this worked for me. If anyone out there is stuck on this with no hope, give this bizarre solution a try ;)
