### ISSUE TITLE
Exporting multiple configs each with different context causes webpack to stuck

### ISSUE THREAD

**Issue by ibrahimra7al** [webpack/webpack#14689]
# Bug report

**What is the current behavior?**
When exporting an array of configurations from webpack.config.js if some of them have different context paths the build will be stuck

**If the current behavior is a bug, please provide the steps to reproduce.**
just create any webpack config file that exports an array contains two simple configs objects each have a different context path

**What is the expected behavior?**
it shouldn't be stuck instead it should do the bundle the code normally

**Other relevant information:**
webpack version:  "4.46.0"
Node.js version: v14.16.1
Operating System: Linux Ubuntu 20.04.2 LTS

**Comment by alexander-akait** [comment]
Please provide reproducible test repo

**Comment by alexander-akait** [comment]
And `webpack version: "4.46.0"` is deprecated please use `5` version

**Comment by Chrobob2021** [comment]
> Please provide reproducible test repo

#14784

**Comment by vankop** [comment]
please upgrade webpack to version 5. Feel free to create a reproducible repo with webpack@5.
