### ISSUE TITLE
node_modules `version` change is no longer tracked since 5.55.0 in watch mode

### ISSUE THREAD

**Issue by alan-agius4** [webpack/webpack#14699]
# Bug report

**What is the current behavior?**

Prior to version [`5.55.0`](https://github.com/webpack/webpack/releases/tag/v5.55.0), when caching is enabled and a version of the package was being tracked during incremental build. The caused certain cases when users used `npm link` to allow them to alter via an automated process) the package.json version and the changes get picked up by Webpack. 

Now, however, it appears that the version is only being tracked during the initial build. 

**If the current behavior is a bug, please provide the steps to reproduce.**
Reproduction https://github.com/alan-agius4/webpack-version-track/, with steps in the readme.

**What is the expected behavior?**
version is tracked and a rebuild is trigger during incremental builds

**Other relevant information:**
Webpack version:  5.63.0
Node: 16.13.0
OS: darwin x64

**Comment by sokra** [comment]
During watching the unsafe cache is enabled for node_modules. That means that most changes to node_modules are ignored. I wonder why that even worked before...

**Comment by alan-agius4** [comment]
> That means that most changes to node_modules are ignored

I agree about this, and this was the case previously, unless the version changes.  From my understanding of the [docs](https://webpack.js.org/configuration/cache/#cachemanagedpaths) if the `version` in the `package.json` changes than code changes should be picked up.

**Comment by alan-agius4** [comment]
What I noticed is that it seems that the package.json file is no longer tracked. When it is changed a rebuild is not triggered, while changing a js file  in node_modules does triggered although the output is not updated.

**Comment by sokra** [comment]
We discussed that internally and yes it's a bug. It should still detect changed to package.json and rebuild these modules.

The problem is that the package.json is no longer watched and so that changes are not detected...
