### ISSUE TITLE
--help option should cause webpack to exit

### ISSUE THREAD

**Issue by dbkr** [webpack/webpack#1469]
Currently, if I create a webpack.config.js file, the options appear to be combined with any specified on the CLI, as expected. However, this means that running webpack -h makes webpack execute with the options in the config file, hence it builds my project instead of outputting the help message.

I think it would be better to print the help message and exit if the help option is specified. This is what GNU make does, for instance.

**Comment by SpaceK33z** [comment]
So the bug is just that `-h` should do the same as `--help`, right?

**Comment by dbkr** [comment]
I just tried to test whether -h and --help behaved differently but both now seem to have the behaviour I'd expect, so it looks like this has been fixed. Thanks!
