### ISSUE TITLE
"Cannot resolve module" for CSS files

### ISSUE THREAD

**Issue by joezimjs** [webpack/webpack#1470]
When I try to require CSS files, I get an error:

> ERROR in ./src/client/scripts/display-test.js
> Module not found: Error: Cannot resolve module 'style' in C:\Users\u659408\localhost\bp\src\client\scripts
> @ ./src/client/scripts/display-test.js 3:12-60

It's pointed to the correct file. I can tell because when I try to point it to a file that doesn't exist, it gives a different error:

> ERROR in ./src/client/scripts/display-test.js
> Module not found: Error: Cannot resolve 'file' or 'directory' ../../styles/components/heading.css in C:\Users\u659408\localhost\bp\src\client\scripts
> @ ./src/client/scripts/display-test.js 3:12-58

I'm using gulp-webpack, so that *might* be the difference, but I don't see why it would be for this error. The config being passed into it is super simple:

```js
{
  module: {
    loaders: [
      { test: /\.css$/, loader: 'style!css' },
      { test: /\.jsx?$/, loader: 'babel?stage=0', exclude: /node_modules/ },
    ]
  }
}
```

I tried using the normal `require` instead of ES2015 `import`. Nothing. I tried a whole ton of things and couldn't find an answer. If you have any ideas, let me know. One of these days I'll try without gulp-webpack, but that'll be a little bit.

**Comment by leftstick** [comment]
According to the error message you shown:

```
Module not found: Error: Cannot resolve module 'style' in 
...
...
```

This points to the missed `style-loader`. Have you `npm install --save-dev style-loader`?
If not, make sure to install the loader you required first.

**Comment by joezimjs** [comment]
Oops! Thanks. I guess I just assumed the style- and css-loader came with webpack automatically.

**Comment by imnotnerd** [comment]
exactly the same situation I'm in.Thank you!

**Comment by msangel** [comment]
`npm install --save-dev style-loader` and `npm install --save-dev css-loader` make it working for me. looks like these modules are no longer a part of standard bundle.

**Comment by ClaudiaHunter** [comment]
first step:
    npm install  style-loader css-loader 

second:
    resolve: {
             extensions: ['', '.js', '.jsx','.css'],//add '.css' 
             "root": __dirname
        }

**Comment by tracer-Zzz** [comment]
thanks leftstick

**Comment by Peakdrum** [comment]
For me I have to put this in my `webpack.config.js`

```
      { test: /\.css$/, loader: "style-loader!css-loader" }```

**Comment by jprocess** [comment]
Still a problem for me. @ClaudioHunter: where does this go?

resolve: { extensions: ['', '.js', '.jsx','.css'],//add '.css' "root": __dirname }"

**Comment by wujunchuan** [comment]
@msangel  It work for me!Thanks

**Comment by rhaseven7h** [comment]
2017/06/22 : My solution was this:

```javascript
            // Process SASS/SCSS
            {
                test: /\.s[ac]ss$/,
                include: paths.appSrc,
                loaders: [
                    require.resolve('style-loader'),
                    require.resolve('css-loader'),
                    require.resolve('sass-loader')
                ]
            },
```

**Comment by lxm7** [comment]
After trying EVERYTHING i ended up just including these in one of the top most components to insert in to the actual DOM :

`import "!style-loader!css-loader!react-grid-layout/css/styles.css"`
`import "!style-loader!css-loader!react-resizable/css/styles.css"`

**Comment by arimourao** [comment]
I'm having this problem. I have style-loader and css-loader installed. Funny thing is, I import several css files from some components that I'm using without a problem. Now I'm trying to import a .css file made by myself and I get this error: ```Module not found: Error: Can't resolve '../index.css'```

Here is the relevant part of my webpack.config:
```{
        test: /\.css$/,
        use: [ 'style-loader', 'css-loader' ]
      }```

Any help would be much appreciated.

**Comment by justtesti** [comment]
I solved my problem by changing css path like this:
import css from "mycss.css"  ==> import css from "./mycss.css"

**Comment by FabioGuerreiro** [comment]
@justtesti great that solved it for me too!

**Comment by nokola** [comment]
For me this also works (typescript):
```
import 'style.css';
```

**Comment by hafidsmail** [comment]
you have to add this on your project in " webpack.config.js "  :
for CSS files   :
`rules: [
      {
        test: /\.css$/,
        use: [ 'style-loader', 'css-loader' ]
      },
      
    ]

for CSS files   : 
    rules: [
      {
        test: /\.tsx?$/,
        use: 'ts-loader',
        exclude: /node_modules/
      },
      {
        test: /\.css$/,
        use: [ 'style-loader', 'css-loader' ]
      },
      
    ].`

**Comment by hafidsmail** [comment]
```
rules: [
      {
        test: /\.css$/,
        use: [ 'style-loader', 'css-loader' ]
      },
      
    ]

for CSS files   : 
    rules: [
      {
        test: /\.tsx?$/,
        use: 'ts-loader',
        exclude: /node_modules/
      },
      {
        test: /\.css$/,
        use: [ 'style-loader', 'css-loader' ]
      },
      
    ].
```

**Comment by hafidsmail** [comment]
The solution is to Add this one in your webpack.config.js 
for Typescript and CSS files   : 
```
    module: {
    rules: [
      {
        test: /\.tsx?$/,
        use: 'ts-loader',
        exclude: /node_modules/
      },
      {
        test: /\.css$/,
        use: [ 'style-loader', 'css-loader' ]
      },
      
    ]
  },
```

**Comment by lecaoquochung** [comment]
In my case, just change from
```
@import url('/..);
```
to
```
@import url('//..);
```

**Comment by ekremcoban** [comment]
if you type code in react, you have to remove node_modules, and then install it again.

**Comment by DHBuild002** [comment]
> For me this also works (typescript):
> 
> ```
> import './style.css';
> ```

Legend! Thank you for that. This is obvious to me now.

My index.js file required me to use import <VarName> from '../style/css'.

Doh! Just worked out how to do it the other way too. I was right but had not gone far enough up in the directories.

**Comment by mbsanchez** [comment]
I've solved the issue just importing Browser animations module in the app.module.ts

import {BrowserAnimationsModule} from '@angular/platform-browser/animations';

**Comment by Vivekguptaji** [comment]
it is very simple you have to install the fist syle-loader the css-loader.

**Comment by MasterMindNET** [comment]
In my case I forgot to add `.css`
`import './styles/styles'` - 
Correct one:
`import './styles/styles.css'`
or this:
`import css from "./styles/styles.css"`

**Comment by chientrm** [comment]
> According to the error message you shown:
> 
> ```
> Module not found: Error: Cannot resolve module 'style' in 
> ...
> ...
> ```
> 
> This points to the missed `style-loader`. Have you `npm install --save-dev style-loader`?
> If not, make sure to install the loader you required first.

You'd just saved me!

**Comment by RikiSharon** [comment]
To me, replacing Path separator from `@import ".\\assets\\styles\\styles.css";`  to `@import "./assets/styles/styles.css";`  - solved the issue.

**Comment by Edx0n** [comment]
I did "npm install rollup-plugin-sass -D" in my terminal and it works for me, hope it works for you too.
