### ISSUE TITLE
lazyCompilation of dynamic imports fail to load without handling hmr manually

### ISSUE THREAD

**Issue by dannylindquist** [webpack/webpack#14705]
# Bug report

**What is the current behavior?**
When `experiments.lazyCompilation` is enabled, dynamic imports fail to load. The promise of import('filename') never resolves.

**If the current behavior is a bug, please provide the steps to reproduce.**
Create an entry point that dynamically imports another file. Webpack will log that an hmr update failed and then things are broken until a refresh occurs.

[Reproduction here](https://github.com/dannylindquist/webpack-lazy-compilation)
```
yarn install
yarn start
//open localhost:8080
//check console to see failed hmr
//lazyLoaded component never renders
```

**What is the expected behavior?**
A dynamically imported file, even if lazy loaded should just work. Should be compiled and returned to the calling file without extra behavior. 
The one caveat that I found is that things work if you explicitly handle `module.hot.accept(dynamicallyImportedFile)`, but this seems like it should be an unnecessary step.

webpack version:  5.62.1
Node.js version: v14.17.3
Operating System: MacOS
Additional tools:

**Comment by alexander-akait** [comment]
Expected, you have multiple runtime HMR on the same page, https://github.com/webpack/webpack-dev-server/issues/2792, please use https://github.com/webpack/webpack-dev-server/issues/2792#issuecomment-808328432
