### ISSUE TITLE
Context Option when using asset modules with webpack 5

### ISSUE THREAD

**Issue by janwidmer** [webpack/webpack#14717]
## Feature request

We have switched from webpack 4 to 5 and also from using `file-loader` to `asset modules` as recommended in the migration guide. Now we are missing an option to set the context when using `asset modules`.

**What is the expected behavior?**

Imagine the following file structure:
```
src
   assets
      img
         image.svg
         logo.svg
         icons
            icon-1.svg
            icon-2.svg
            icon-3.svg
            icon-4.svg
```

Desired dist structure:

```
dist
   img
      image.svg
         logo.svg
         icons
            icon-1.svg
            icon-2.svg
            icon-3.svg
            icon-4.svg   
```

With webpack 4, it was possible to preserve (part of) the src folder structure of the assets when copying them via `file-loader` by using the following config:

```
 {
          test: /\.(gif|png|jpe?g|svg)$/i,
          use: [
            {
              loader: 'file-loader',
              options: {
                esModule: false,
                context: 'src/assets/',
                name: '[path][name][contenthash].[ext]',
                outputPath: 'img/',
              },
            },
}
```
By setting the `context` and `outputPath` option in the `file-loader` only the folder structure within `assets` was preserved within the dist folder.

With the new asset modules of webpack 5, it does not seem possible anymore to do so. The only option seems to define the filename by setting `assetModuleFilename` in the `output` object or within the `generator` object of the rule:

```
{
          test: /\.(gif|png|jpe?g|svg)$/i,
          type: 'asset/resource',
          generator: {
            filename: '[path][name][contenthash].[ext]'
          },
},
```

By using `[path]`, it takes the whole path and also adds a subfolder `assets` in my `dist` folder. Just using `[name]` does not take any subfolders at all and put's all files in the root.

**What is motivation or use case for adding/changing the behaviour?**

Having the same dist output as with webpack 4.

**How should this be implemented in your opinion?**

Allow to preserve the src (sub) folder structure for assets when using asset modules.

**Are you willing to work on this yourself?**
no

**Comment by alexander-akait** [comment]
You have `context` at the top of your configuration, if you use custom function for `filename` and implement own logic (https://github.com/webpack/webpack/blob/main/schemas/WebpackOptions.json#L1157), sorry, we don't want to add this

**Comment by janwidmer** [comment]
Thanks for your input, that also works for me. :-)
