### ISSUE TITLE
Question: custom uglify version support

### ISSUE THREAD

**Issue by phated** [webpack/webpack#1471]
Would it be possible or desirable to support custom versions of uglify as long as they provide the expected APIs?  lodash-fp uses webpack to build but has very specific needs for uglify (version/options/etc) and it would be very helpful if a custom uglify could be passed.

Ref https://github.com/lodash/lodash-fp/issues/28

/cc @jdalton

**Comment by mzgoddard** [comment]
@phated For options you can you can pass options to the plugin. For a specific version, if it matches webpack's semver range npm 2 and up should install the one version and webpack will use that? I haven't read enough of the referenced issue to know if that helps.

options.compress https://github.com/webpack/webpack/blob/master/lib/optimize/UglifyJsPlugin.js#L86
options.mangle https://github.com/webpack/webpack/blob/master/lib/optimize/UglifyJsPlugin.js#L91
options.beautify https://github.com/webpack/webpack/blob/master/lib/optimize/UglifyJsPlugin.js#L96

**Comment by phated** [comment]
@mzgoddard relying on semver to specify the version only works to a point.  It would be nice if an `uglify` option could be used to pass in a custom instance that conforms to the API.

**Comment by monolithed** [comment]
`UglifyJS` is a package for `peerDependencies`. Why not?

**Comment by Kitanotori** [comment]
How can I use [the Harmony branch of UglifyJS2](https://github.com/mishoo/UglifyJS2/tree/harmony) with Webpack in order to handle ES6 minification?

**Comment by fulls1z3** [comment]
I'm hereby trying to help by providing detailed instructions:

- Fork webpack,
- On that fork, delete all branches except master,
- Clone master branch to a local folder,
- On the local folder, delete all files,
- Commit the empty local folder,
- Download the latest release (ex: v2.1.0-beta.27 at the moment)
- Extract contents of zip file to the local folder,
- On the local folder, edit forked package.json, change
```
"uglify-js": "git+https://github.com/mishoo/UglifyJS2.git#harmony"
```
to point UglifyJs2 (harmony branch) dependency to that branch.
- Commit changes,
- Finally, point webpack in your package.json to your custom fork:
```
"webpack": "[USERNAME]/webpack#master"
```

OR,

- Point webpack in your package.json to [fulls1z3/webpack](https://github.com/fulls1z3/webpack) (ES6/ES2015 friendly webpack fork):
```
"webpack": "fulls1z3/webpack#v2.1.0-beta.27-harmony"
```

**Comment by bebraw** [comment]
There's [uglifyjs-webpack-plugin](https://github.com/webpack-contrib/uglifyjs-webpack-plugin) for this now. We might make that the official option in the next major release.
