### ISSUE TITLE
Using loader for file in a dependency requires the dependency to have that loader installed

### ISSUE THREAD

**Issue by dbkr** [webpack/webpack#1472]
library a is a plain javascript library.
Application has a file b.js that does require('a'), application uses webpack
If webpack needs a loader to load any file in module a, the loader needs to be installed in library a's node_modfules folder. webpack will fail with error, "Cannot resolve module" if the loader is installed only in the application's node_modules folder.

Webpack should be able to load the loader from the application's node_modules folder such that libraries which don't use webpack don't have to depend on webpack loaders in order for applications that use them to use webpack.

**Comment by dbkr** [comment]
I'd still be interested in seeing this fixed.

**Comment by vankop** [comment]
Should work with `webpack@latest`. Feel free to report new issue with reproducible repo.
