### ISSUE TITLE
webpack **serve** lists common chunk as dependency to unrelated entry point

### ISSUE THREAD

**Issue by mbehzad** [webpack/webpack#14727]
# Bug report

**What is the current behavior?**

There are 3 entry points `a.js`, `b.js` and `c.js`. a and b have a common dependency to `utils.js`. Webpack with `optimization.splitChunks` option will generate a `common.js` chunk (with `utils.js`' content) which `a.bundle.j` and `b.bundle.js` are depending on. The `c.bundle.js` can be used standalone because it has no (shared) dependency with other entries.

This is the behavior when using the webpack cli with the `webpack` command:

cmd output: 
```cmd
Entrypoint a = common.js a.bundle.js
Entrypoint b = common.js b.bundle.js
Entrypoint c = c.bundle.js   //  <----------------
```

**But** when generating the bundles via **webpack-dev-server** (or with `webpack serve` cli command), the common chunk is listed as an output for entry c and therefor needed to be loaded with its bundle. even when it has no common dependency in the source code with other entries:

cmd output:

```cmd
Entrypoint a = common.js a.bundle.js
Entrypoint b = common.js b.bundle.js
Entrypoint c = common.js c.bundle.js  //  <------- 
```

In c.bundle.js:

```js
/******/ 	// add entry module to deferred list
/******/ 	deferredModules.push([2,"common"]);
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Minimal reproducible repo:
https://github.com/mbehzad/webpack-dev-server-common-chunk-bug

```js
// webpack.config.js

module.exports = {
  devServer: {
    compress: true,
    port: 9000,
    hot: false,
  },
  entry: {
    a: "./src/a.js", // has dependency to utils.js
    b: "./src/b.js", // has dependency to utils.js
    c: "./src/c.js", // has no (shared) dependency
  },
  output: {
    filename: '[name].bundle.js',
    path: __dirname + '/dist'
  },
  mode: "development",

  optimization: {
    splitChunks: {
      cacheGroups: {
        commons: {
          name: "common",
          filename: "common.js",
          chunks: "initial",
          minChunks: 2,
          minSize: 0,
        },
      },
    },
  },

}
```

**What is the expected behavior?**

Preferably `webpack serve`'s output should have the same common chunk dependency as `webpack build`'s output.

**Other relevant information:**
webpack version:  5.64.0 
Node.js version: 16.3.0
Operating System: Windows 10
Additional tools:  webpack-cli v4.9.1, webpack-dev-server v4.5.0

**Comment by mbehzad** [comment]
The issue seems to be that webpack dev server loads some additional modules (e.g. for showing error messages) for each bundle. which will then land in the common chunk and make all bundles dependent on loading the "common" chunk independent of the dependencies in the source code.

**Comment by sokra** [comment]
> The issue seems to be that webpack dev server loads some additional modules (e.g. for showing error messages) for each bundle. which will then land in the common chunk and make all bundles dependent on loading the "common" chunk independent of the dependencies in the source code.

yes, but that's expected.

Best avoid `splitChunks.cacheGroups.xx.name/filename` as it will prevent multiple common chunks being created.
Instead you can use [`idHint`](https://webpack.js.org/plugins/split-chunks-plugin/#splitchunkscachegroupscachegroupidhint).

That should lead to something like:

```
Entrypoint a = common-yyy.js common-xxx.js a.bundle.js
Entrypoint b = common-yyy.js common-xxx.js b.bundle.js
Entrypoint c = common-yyy.js c.bundle.js
```

**Comment by alexander-akait** [comment]
Answered, feel free to feedback
