### ISSUE TITLE
Webpack asset generator with publicPath not working (version 5.64.1)

### ISSUE THREAD

**Issue by kngell** [webpack/webpack#14739]
when upgrading webpack to version 5.64.0, module.rule.generator.publicPath has stopped working properly.

module.exports={
  // ....,
  generator: {
    filename: devMode
      ? "../fonts/[name][ext][query]"
      : "fonts/[name][hash][ext][query]",
    publicPath: "fonts",
  },
}
and I have this error:

ERROR in ./src/frontlib.sass
Module build failed (from ./node_modules/mini-css-extract-plugi/dist/loader.js):
HookWebpackError: Invalid URL at tryRunOrWebpackError 
Now I still have the same error even if I downgrade Webpack to the previous version.

How to set generator publicPath into the new Webpack version?

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

It means you have invalid URL
