### ISSUE TITLE
Argument of type 'RawSource' is not assignable to parameter of type 'Source'.

### ISSUE THREAD

**Issue by Edge00** [webpack/webpack#14754]
# Bug report

**What is the current behavior?**
```js
import { RawSource } from 'webpack-sources'

// inside a plugin
const source = new RawSource(jsonString)
compilation.emitAsset('app.json', source)
```
Tsc reports following error:
```bash
src/webpack-config/plugins/XhsMpEntryPlugin.ts:78:44 - error TS2345: Argument of type 'RawSource' is not assignable to parameter of type 'Source'.
  The types returned by 'map(...)' are incompatible between these types.
    Type 'null' is not assignable to type 'Object'.

78       compilation.emitAsset('app.json', source)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
`compilation.emitAsset` param type should be aligned with `RawSource` return type

**Other relevant information:**
webpack version:  5.51.2
Node.js version: 14.17.1
Operating System: macOS
Additional tools: webpack-source@3.2.2

**Comment by alexander-akait** [comment]
> If the current behavior is a bug, please provide the steps to reproduce.

Please fill out it and I will reopen
