### ISSUE TITLE
Wasm import sometimes resolves as an empty object

### ISSUE THREAD

**Issue by jkosir** [webpack/webpack#14759]
# Bug report

**What is the current behavior?**
The included .wasm module (either with async `import('module.wasm')` or sync `import * as module from 'module.wasm'`) is sometimes (like 50%) of the time properly loaded, while in other 50% of builds it's resolved as `{ default: {} }`, basically an empty object.

We have a simple `.wasm` module which fails immediately after import. I'm trying to make it work with `experiments: { asyncWebAssembly: true}` and running into this issue.

If we use webpack4 compatibility wasm loading (`experiments: { syncWebAssembly: true}`) it results in the same problems as reported here: https://github.com/webpack/webpack/issues/13755

It's not a runtime issue, after every build the bundled app will always either resolve the .wasm module correctly or incorrectly.

**If the current behavior is a bug, please provide the steps to reproduce.**
Import a .wasm file with `experiments: { asyncWebAssembly: true }` in webpack config, then inspect the result of said import.

**What is the expected behavior?**
Wasm module should always be resolved correctly, webpack compilation should be deterministic.

**Other relevant information:**
webpack version: 5.63.0
Node.js version: 7.7.6
Operating System: Docker image based on debian:stretch
Additional tools:

**Comment by alexander-akait** [comment]
Please create reproducible test repo
