### ISSUE TITLE
Dynamic expressions in import() with node_modules not working

### ISSUE THREAD

**Issue by zwif** [webpack/webpack#14758]
# Bug report
[Dynamic expressions in import](https://webpack.js.org/api/module-methods/#dynamic-expressions-in-import) from `node_modules` cause webpack to run very long and potentially crash without any error / information.

I do understand that - [as documented](https://webpack.js.org/api/module-methods/#:~:text=The%20import()%20must%20contain%20at%20least%20some%20information%20about%20where%20the%20module%20is%20located.%20Bundling%20can%20be%20limited%20to%20a%20specific%20directory%20or%20set%20of%20files%20so%20that%20when%20you%20are%20using%20a%20dynamic%20expression%20-%20every%20module%20that%20could%20potentially%20be%20requested%20on%20an%20import()%20call%20is%20included.) - webpack can't build module when dynamic imported like ``import(`${my-module}`)`` since it could be located anywhere. But I don't see why it wouldn't work when 'hard' defining a subfolder of node_modules and only having the last part dynamic.

**What is the current behavior?**
Having a Dynamic import which has a path to somewhere in `node_modules` (e.g. `node_modules/@my-org/${package-name}`)  will cause webpack to never finish its build process.

**If the current behavior is a bug, please provide the steps to reproduce.**
Clone this minimal reproduction repository: https://github.com/zwif/webpack-issue-dynamic-expression-in-import
1. `npm install`
2. `npm run build`
3. ⇒ the browser console for the dev-server (`localhost:8080`) will have "import successful" logged (expected)
4. comment/remove line `5` in `src/index.js` and uncomment line `6` - changing   
   `./../node_modules/@xtuc/long` to `./../node_modules/@xtuc/${dynamicPart}`
5. webpack is no longer able to finish the build.

**What is the expected behavior?**
An Import with a dynamic expression like `node_modules/@my-org/${package-name}` should just work like the import when all hardcoded (`node_modules/@my-org/my-package`).

**Other relevant information:**
webpack version:  5.64.1
Node.js version: 14.15.5
Operating System: Debian 11
Additional tools: -

**Comment by alexander-akait** [comment]
> webpack is no longer able to finish the build

Finished due:

```
ERROR in ./node_modules/@xtuc/long/index.d.ts 1:7
Module parse failed: Unexpected token (1:7)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> export = Long;
| export as namespace Long;
```

There is the error, Why? Because you try to bundle not only JS files, go to `node_modules/@xtuc/` and you will see all files, i.e. `LICENSE`, `README.md`/`long.js.map`/etc, you should exclude them
