### ISSUE TITLE
webpack compiling twice on startup when importing a file within a typescript react setup

### ISSUE THREAD

**Issue by bahtou** [webpack/webpack#14768]
# Bug report

**What is the current behavior?**

Working on a TypeScript React project when running webpack the compilation happens twice at startup. This happens when a file is being imported from the root react `index.tsx`.
Not sure if its similar to https://github.com/webpack/webpack/issues/13618?

**If the current behavior is a bug, please provide the steps to reproduce.**
1. https://github.com/bahtou/issues/tree/webpack-rebuild
2. follow the readme

you should be able to see two rebuilds
```
👀   1 . compilation afterEmit 2021-11-18T22:01:58.573Z
👀   1 . compilation is done 2021-11-18T22:01:58.575Z
```
```
👀   2 . compilation afterEmit 2021-11-18T22:01:58.872Z
👀   2 . compilation is done 2021-11-18T22:01:58.872Z
```

**What is the expected behavior?**

compilation should only run once

**Other relevant information:**
webpack version:  5.64.1
Node.js version: v14.18.1
Operating System: OSX
Additional tools: none

**Comment by markjm** [comment]
I think this is related to https://github.com/webpack/webpack/pull/14735.

The invalidation comes from 
```
_invalidate(..., ..., Set(0) {} Set(2) {
  '/workspaces/issues/node_modules/package.json/package.json',
  '/workspaces/issues/node_modules/swc-loader.js/package.json'
}
```
This indicated that watchpack.watch is called with these invalid file entries. When encountering these paths, it then tries to adds watchers for these files, fails (because they dont exist `"initial-missing / scan (parent directory missing in initial scan)"`) and marks them as removed.

**Comment by wood1986** [comment]
I think it has nothing with TS. My JS repo has the same issue and it compile 3 times

**Comment by bahtou** [comment]
@wood1986 I switched to webpack v5.64.0 and I still get the double compilation. With the repo above you can test it out. Agree that it has nothing to do with TS. The webpack config is not using TS for anything. I just mentioned it since I was setting up a new project.

**Comment by alexander-akait** [comment]
Yep, it is bug

**Comment by alexander-akait** [comment]
@bahtou `v5.64.0` doesn't have this problem, just tested on your repo

**Comment by sokra** [comment]
should be fixed by https://github.com/webpack/webpack/releases/tag/v5.64.2
