### ISSUE TITLE
How to reuse a tab in webpack 5 ?

### ISSUE THREAD

**Issue by fangwei18** [webpack/webpack#14764]
Hi, I use this config to reuse a tab in webpack4, but this config is invalid in webpack5, is there another method to reuse a tab?

```js
  devServer: {
    open: true,
    after: () => {
      openBrowser('http://localhost:8080')
    },
  },
```

**Comment by snitin315** [comment]
What is your `webpack-dev-server` version? Please do not ignore the issue template.

**Comment by fangwei18** [comment]
```
"webpack": "^5.64.0",
"webpack-dev-server": "^4.5.0",
```

**Comment by snitin315** [comment]
Please read the [migration guide for webpack-dev-server v4](https://github.com/webpack/webpack-dev-server/blob/master/migration-v4.md). 

`after` was removed in favor of [onAfterSetupMiddleware](https://webpack.js.org/configuration/dev-server/#devserveronaftersetupmiddleware).

```js
  devServer: {
    open: true,
    onAfterSetupMiddleware: () => {
      openBrowser('http://localhost:8080')
    },
  },
```

**Comment by fangwei18** [comment]
Thanks! That works perfectly!
