### ISSUE TITLE
[webpack-dev-server] unable to open "http://localhost:8887" page in "chrome" ,if you are running in a headless environment,please 。。。。

### ISSUE THREAD

**Issue by Yuanbaby0077** [webpack/webpack#14787]
# Bug report

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
update webpack to the latest, unable to open the chrome browser automatically after the server start，error message is following:

[webpack-dev-server] unable to open "http://localhost:8887" page in "chrome" ,if you are running in a headless environment,please do not use the "open" option or related flags like "--open", "--open-target" and "--open-app"

**Other relevant information:**
webpack version:  5.64.1
Node.js version: 14
Operating System: window10
Additional tools:

**Comment by alexander-akait** [comment]
Please read the error message and fix your configuration

**Comment by alexander-akait** [comment]
It means you don't have chrome or chrome used other application name, for example - `google-chrome`

**Comment by Yuanbaby0077** [comment]
> It means you don't have chrome or chrome used other application name, for example - `google-chrome`

finally we had the conclusion, since open@7.2 in our environment, it can not open the browser, maybe the limits of authority

**Comment by Yuanbaby0077** [comment]
> It means you don't have chrome or chrome used other application name, for example - `google-chrome`

In fact, I try to use the option open.app.name = 'chrome' or 'google-chrome', whatever setting is ineffectiveness

**Comment by alexander-akait** [comment]
Sorry, we can't fix it here

**Comment by Yuanbaby0077** [comment]
> Sorry, we can't fix it here

okay, I will open browser manually
