### ISSUE TITLE
`experiments.lazyCompilation.backend.protocol: 'https'` not working as intended

### ISSUE THREAD

**Issue by Clarkkkk** [webpack/webpack#14790]
# Bug report

**What is the current behavior?**
Webpack config:
```js
module.exports = {
  entry: './src/index.js',
  mode: 'development',
  output: {
    filename: 'main.js',
    path: path.resolve(__dirname, 'dist'),
  },
  devServer: {
    static: './dist',
    https: true
  },
  experiments: {
    lazyCompilation: {
      backend: {
        protocol: 'https'
      }
    },
  },
  plugins: [
    new HtmlWebpackPlugin({
      title: 'Development',
    }),
  ],
};
```

Output in the terminal: 
```
[LazyCompilationBackend] [Error: 16092:error:14201076:SSL routines:tls_choose_sigalg:no suitable signature algorithm:c:\ws\deps\openssl\openssl\ssl\t1_lib.c:2760:
] {
  library: 'SSL routines',
  function: 'tls_choose_sigalg',
  reason: 'no suitable signature algorithm',
  code: 'ERR_SSL_NO_SUITABLE_SIGNATURE_ALGORITHM'
}
```

Out in the console of browser:
```
Failed to load resource: net::ERR_SSL_VERSION_OR_CIPHER_MISMATCH
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Serve the web page as intended.

**Other relevant information:**
webpack version:  5.64.2
Node.js version: v16.13.0
Operating System: Windows 11 21H2 (not working in Windows 10 either)
Additional tools: -

**Comment by vankop** [comment]
you need to provide `key` and `cert`, e.g. like here https://github.com/webpack/webpack/tree/main/test/hotCases/lazy-compilation/https

**Comment by alexander-akait** [comment]
Answered, feel free to feedback
