### ISSUE TITLE
Hash changes if a filename is changed

### ISSUE THREAD

**Issue by dmitry** [webpack/webpack#1479]
Hash is differently generated on different computers.
I've tried without image optimizations and source map.

More details on this issue:
https://github.com/erikras/react-redux-universal-hot-example/issues/251

**Comment by dmitry** [comment]
I can reproduce this issue with following code:

webpack.config.js
```
var path = require('path');

var ROOT_PATH = path.resolve(__dirname);

module.exports = common = {
  entry: path.resolve(ROOT_PATH, 'app'),
  resolve: {
    extensions: ['', '.js']
  },
  output: {
    path: path.resolve(ROOT_PATH, 'build'),
    filename: 'bundle.js'
  },
  module: {
    loaders: [
      {
        test: /\.js$/,
        loaders: []
      }
    ]
  }
};
```

index.js
```
require('react');
```

**Comment by dmitry** [comment]
Using `webpack-md5-hash` it was solved for me, but still I would like to see it working out of the box.

**Comment by dmitry** [comment]
Looks like an issue is related to the relative path in the libraries.

**Comment by dmitry** [comment]
Looks like this one could be related to this one: https://github.com/webpack/webpack/issues/1450

**Comment by ianwith** [comment]
Any progress on this issue?
Hash is different on different machines, it's troublesome...Can anyone tell how does webpack generate the [hash]

**Comment by bradrobertson** [comment]
I also have this problem and have spent hours trying to figure out the problem. See [here](http://stackoverflow.com/questions/33791096/webpack-hashing-after-uglification).

What I can tell is it's not *machine* specific per se as I can reproduce it locally by moving my project into 2 different folders.

Effectively, *my* issue is that we're adding in absolute paths to `includePaths` in the `style-loader`, which ultimately generates different JS output. These paths actually get stripped on uglification, so the resulting JS between 2 builds is the same, however the hashing happens *before* uglification, so any dead code optimizations that remove these differences don't affect the final chunkhash.

I'm unable to get this working with the `webpack-md5-hash` plugin at all, I still get different hash names on my files for the same JS.

Furthermore if you use the CommonChunks plugin, webpack seems to reference chunks using these chunkhashes, so the actual common.js file generated is different for the 2 builds, even though the actual entries themselves are the same.

This feels like a fundamental issue with the way webpack generates its hashes. They're somehow generated high up in the compilation chain, based on the JS generated after modules are bundled up, which may or may not (depending on loaders etc) include path specific information. This, thus can make the actual JS output different, which obviously generates a different chunkhash.

I'm pretty much out of ideas at this point, it just seems like a failing in the underlying compilation mechanism. I *don't* think its a stretch to expect consistent hashing of files **no matter where** the files are compiled.

**Comment by dmitry** [comment]
@bradrobertson I've found the same root, read more about it here: https://github.com/webpack/webpack/issues/1155#issuecomment-157997666

**Comment by wedgex** [comment]
Has any progress been made or work arounds found for this? 

We've brought in the webpack-md5-hash plugin but are still having one chunk change chunkhash when built on a different machine (or just different directory).

**Comment by LukeLin** [comment]
I have this problem too.

**Comment by LukeLin** [comment]
I found it's caused by requiring CSS files, built by extract-text-webpack-plugin

**Comment by chilicomputer** [comment]
#2215

**Comment by heldrida** [comment]
@LukeLin can you provide more information; how is it caused by requiring css files ? Can you show some examples ? I'm having the same issue that is reported here, the image hash are different, on different machines; The SVG was quite persistent, but adding a query parameter helps regenerate the correct hash filnema.svg?somestring

**Comment by asjudy** [comment]
I have this problem too.

**Comment by pumbers** [comment]
Same here - I'm on 1.12.9. Hash appears consistent between different Windows 7 workstations, but when built on a Red Hat box under Jenkins we get a different hash. We're not loading CSS either, and webpack-md5-hash shows the same problem.

**Comment by dmitry** [comment]
The problem persists when the libraries are loaded into the scripts through the require. Seems like node_modules absolute path converts differently.

**Comment by michael8090** [comment]
Same here. And it breaks the deploy of our prod server... as we deploy frontend files and backend files on different machines.

**Comment by dmitry** [comment]
@michael8090 can you please report webpack and node version, and your paths of deployment on different servers (capistrano or you are using own solution)?

**Comment by michael8090** [comment]
@dmitry thanks for your concern. I've resolve the problem by adding the `webpack-md5-hash` plugin to the plugins of webpack. 

I hope the others facing the same issue could try `webpack-md5-hash` first.

**Comment by michael8090** [comment]
@dmitry

I've two machines for development, one is a mbp and the other is a pc. 

mbp: node@6.2.2, webpack@1.13.2

pc: node@6.7.1, webpack@1.13.2

On mac I have `projectA` and a `projectB` cloned from A .

Before using the `webpack-md5-hash` plugin, the bundle content of A and B are the same, but the chunkhashes are different.

After using the `webpack-md5-hash`, the bundle content and hashes are the same.

But the content and hashes are different from the build on my PC, no matter if I use the plugin or not.......

**Comment by dmitry** [comment]
@michael8090 as I remember, in my case it was an issue when I required react library, or any other lib from the node_modules. When there are no requirements for the node_modules, it worked without issues. I believe once you require, webpack takes absolute path and somehow it changes whole code, so the chunkhash is different.
I don't see any solution how to solve it, may be @sokra knows how?

**Comment by dmitry** [comment]
@michael-ciniawsky have you tried webpack >= 2.0?

**Comment by paramsingh88** [comment]
@dmitry I have the same issue, any help?? I'm using webpack 1.13.1

**Comment by dmitry** [comment]
@paramsingh88 there are no solution at the moment. You have to use some webpack plugins or PR with a fix of that issue.

**Comment by paramsingh88** [comment]
Any webpack plugin you can suggest?

**Comment by dmitry** [comment]
webpack-md5-hash

**Comment by michael8090** [comment]
Update: after using `webpack-md5-hash` the hashes for the same content are the same now. But the content of the bundles on different machines are different.... It looks like the `OccurenceOrderPlugin` doesn't work, as the module orders are not the same. I also tried `recordsPath` but with no luck.

<img width="587" alt="screen shot 2016-10-07 at 4 27 28 pm" src="https://cloud.githubusercontent.com/assets/2306105/19183451/026e7e46-8cab-11e6-9922-ba0dc551b759.png">


 I'm running out of ideas now. Any help ?

**Comment by dmitry** [comment]
@michael8090 I suggest you to try out new webpack version, could be there are fixed this issue.

**Comment by michael8090** [comment]
@dmitry Do you mean webpack2 or the newer minor update of webpack1?

**Comment by michael8090** [comment]
@dmitry Webpack2 requires Promise pollyfill on old browsers, so it's not an option for our business.

**Comment by dmitry** [comment]
@michael8090 I thought about webpack2, major version. What kind of issues do you have when webpack2 is used along with promise pollyfill on older browsers?

**Comment by michael8090** [comment]
@dmitry I could not introduce the pollyfill just to make the content hash work...Not worth it.

**Comment by michael8090** [comment]
Update: 

It clearly has something to do with the path of the source code. As shown below, 'wtf-webpack', 'wtf-webpack-4' and 'wtf-webpack-5' has 'replace.eddb7ea40a020255062d.js' while 'wtf-webpack-2' has 'replace.73538f954096e7f818b2.js'...


<img width="1054" alt="screen shot 2016-10-08 at 10 04 22 am" src="https://cloud.githubusercontent.com/assets/2306105/19209625/dbf6316e-8d40-11e6-82ba-fd00ac53205e.png">
<img width="1048" alt="screen shot 2016-10-08 at 10 04 53 am" src="https://cloud.githubusercontent.com/assets/2306105/19209628/defaa700-8d40-11e6-9cdc-3507c8a66e9c.png">

**Comment by dmitry** [comment]
I don't think it will be ever fixed in webpack 1, as the latest updates in webpack v1 were done in April.

**Comment by paramsingh88** [comment]
@dmitry @sokra That's it. I've had enough of this issue. Its so silly of webpack that it creates different chunkhash on different machines for same content. I've tried everything including webpack-md5-hash but no luck. My production app is suffering. I'm moving to gulp+browserify.

**Comment by dmitry** [comment]
@paramsingh88 yes, I also felt something like that, but after all, I don't remember, but something were solved an issue for me. I don't believe gulp + browserify could be as advanced as webpack flexible is. I think it's much better to upgrade to the webpack2. :)

**Comment by jhnns** [comment]
Hashes are not guaranteed to be the same across different installations. This is because the module output is affected by loaders, which are installed [by npm in a non-deterministic way](https://docs.npmjs.com/how-npm-works/npm3-nondet).

If you want persistent hashes across multiple compilations, you need to specify a [`recordsPath`](http://webpack.github.io/docs/configuration.html#recordspath-recordsinputpath-recordsoutputpath). This is because the ordering of module ids may change between compilations, for instance: `__webpack_require__(1)` now needs to be changed to `__webpack_require__(2)`. If the order of module ids changes, the entire output of webpack is affected. With a `recordsPath`, webpack persists the assigned module ids to a `records.json`. This way, it is guaranteed that webpack will only change the hashes of chunks that contain new code.

**Comment by jhnns** [comment]
See also #90

**Comment by michael8090** [comment]
@jhnns Unfortunately I tried `recordsPath` and still had different hashes on different machines.

**Comment by michael8090** [comment]
Here is my testing codes, with `recordsPath` enabled. Anyone having some interest could clone it and run `npm install && gulp` on different machines to see how the hash differs.

**Comment by dmitry** [comment]
@jhnns yes, it's not related to the ordering of module ids that may change between different builds. I've tried similar aproach with just `react` module - and it didn't worked well. As I remember, when I removed npm_modules path, hash didn't changed. Hash was changed only when machine was changed.

**Comment by jhnns** [comment]
> different hashes on different machines.

This is always possible. We can't change that because of the way how npm works.

**Comment by dmitry** [comment]
@jhnns any points to push this forward and solve?

**Comment by michael8090** [comment]
@jhnns NPM seems not to be the root cause of the issue. As shown above, the hash changes simply by changing the folder name of the project on the same machine, but it's not that easy to reproduce compared with that on different machines:

>
It clearly has something to do with the path of the source code. As shown below, 'wtf-webpack', 'wtf-webpack-4' and 'wtf-webpack-5' has 'replace.eddb7ea40a020255062d.js' while 'wtf-webpack-2' has 'replace.73538f954096e7f818b2.js'...

**Comment by jhnns** [comment]
I've create a small test repository with a README about my findings: https://github.com/jhnns/webpack-hash-test

I can confirm that hashes change if a filename is changed. This is surprising to me (and probably a bug) because the bundle does not contain any information about filenames anymore. I can also confirm that hashes are different on different OS. This is a logical consequence since Windows uses backslashes as path separator. It's probably also due to the fact that Windows uses `CRLF` for new lines. There's nothing we can do about it.

Can someone of you checkout my test repository and compare the hashes (and then tell me what OS you're using)?

**Comment by jhnns** [comment]
However, please keep in mind that there are a lot of potential causes for legitimate hash changes, see also #1315.

**Comment by dmitry** [comment]
@jhnns thanks for digging deeper. Here is my changes https://github.com/dmitry/webpack-hash-test, when hashes **DO** change if the path outside webpack's context change.

**Comment by jouni-kantola** [comment]
Thank you for sharing your findings, @dmitry. This has always puzzled me as well, and remains the same with Webpack 2. As I go back and forth from Windows, MacOS and CI, I see quite a lot of hash changes. This issue explained quite a lot.

As I see it, CI is pretty much a requirement for running Webpack. Local push is too fragile, since people will most definitely have different setups.

This issue is related: https://github.com/webpack/webpack/issues/1856

**Comment by knowThis** [comment]
![image](https://user-images.githubusercontent.com/13791930/28399654-0dd0855a-6d41-11e7-9108-8aa8c9a29e3f.png)
![image](https://user-images.githubusercontent.com/13791930/28399674-22c28eb8-6d41-11e7-8bd2-e594a9184b31.png)


I have the same problem! I get version number from "package.json" ,write it in output.filename.when i change version number ,The vendor chunkhash change.

**Comment by iamakulov** [comment]
webpack 3.8.1 & Node.js 8.8.0

Can confirm that renaming a file still causes `chunkhash` to change:

![image](https://user-images.githubusercontent.com/2953267/32346602-e016172a-c01e-11e7-8ed3-b2b7db07a51a.png)

Can confirm that using [the `WebpackChunkHash` plugin](https://www.npmjs.com/package/webpack-chunk-hash) doesn’t fix the issue (the plugin was mentioned in #1856 as a possible solution):

![image](https://user-images.githubusercontent.com/2953267/32346759-6b08b1c6-c01f-11e7-90d0-214da1d64185.png)

Can confirm that using the `webpack.HashedModuleIdsPlugin()` plugin doesn’t fix the issue:

![image](https://user-images.githubusercontent.com/2953267/32346851-de52a934-c01f-11e7-80f2-bc9cd9942190.png)

----

What’s interesting though is that with `webpack.HashedModuleIdsPlugin()`, hashes of `b.js` and `c.js` are different – despite the files are the same (I was just renaming `b.js` to `c.js` and vice versa). Hash of `a.js` stays the same. Could this be related to the problem?

**Comment by aguynamedben** [comment]
This just ruined our Webpack deploy in the 11th hour after 2 weeks of work migrating to Webpack. We had to roll back to figure out what to do. We have 2 webservers behind a load balancer. ~50% of the time, the webserver would request a Webpack-produced file and the request would be routed to the other webserver, resulting in a very confusing situation where some assets loaded and some didn't. It took an hour of wonky partial outage to understand the cause.

FWIW we're using djang-webpack-loader, webpack-bundle-tracker, and WhiteNoise to serve Webpack assets. This was very surprising and there aren't really any solutions offered aside from "invest in your CI a bunch more" or "track bundles in git and dirty up your repo".

**Comment by dmitry** [comment]
@aguynamedben have you tried `webpack-md5-hash`, as I remember it partially solved an issue (don't really remember when it fails to fix). 

BTW we had similar server topology: 1 load balancer -> 2 app servers.

**Comment by aguynamedben** [comment]
@dmitry I tried that but was still having issues. I ended up using https://github.com/pirelenito/git-revision-webpack-plugin to use the sha1 from the latest commit. It works for now, but issue this was very surprising and concerning behavior after I had built a lot of trust. The idea of hashing (I think) is to reliably be able to determine if the contents of the files are identical (i.e. for CDN usage). Implementation details in dependency management impacting the hashes is a bug in my book. I'm glad this ticket is still open. 🙏

**Comment by tenkiller** [comment]
Yes, this is still an issue. The same problem is happening for our team. We deploy the same web application across multiple UI servers, and the assets built on one of them is named differently from the others for some unknown reason, even when using `[contenthash]`. We're hoping that the Git revision plugin @aguynamedben referred to solves the problem for us.

**Comment by mingyuyuyu** [comment]
this is still an issue

**Comment by hopperhuang** [comment]
Is the bug fixed ?

**Comment by hopperhuang** [comment]
I also have found that the hashes will change  with different  folders
