### ISSUE TITLE
Issue with node: urls 

### ISSUE THREAD

**Issue by apidev234** [webpack/webpack#14798]
# Bug report
**What is the current behavior?**
Im using [Wallpaper](https://npmjs.com/package/wallpaper)
and I Get a node: urls error

```
 App •  ERROR  •  Renderer  in node:util

UnhandledSchemeError: Reading from "node:util" is not handled by plugins (Unhandled scheme)  .
  Webpack supports "data:" and "file:" URIs by default.
  You may need an additional plugin to handle "node:" URIs.
  ```
  This might be a duplicate, but i dont understand the other issues because they were'nt providing a clear solution
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  5
Node.js version: 16.x.x
Operating System: MacOS
Additional tools: Quasar, VueJs

**Comment by vankop** [comment]
Thanks for your report, pls use externals for `node:util`. In your webpack config:
```js
module.exports = {
   externals: {
       'node:util': 'commonjs util'
   }
}
```

**Comment by apidev234** [comment]
I Didnt Have webpack.config.js in The Root File before, Created Now and Added 
```
module.exports = {
   externals: {
       'node:util': 'commonjs util'
   }
}
```
Still Getting The Same Error
```
 App •  ERROR  •  Renderer  in node:util

UnhandledSchemeError: Reading from "node:util" is not handled by plugins (Unhandled scheme)  .
  Webpack supports "data:" and "file:" URIs by default.
  You may need an additional plugin to handle "node:" URIs.
  
  - NormalModule.js:825 
    [wallpapers-application]/[webpack]/lib/NormalModule.js:825:25
  
  ```
  
  
  ![Screenshot 2021-11-23 at 1 10 21 PM](https://user-images.githubusercontent.com/78847111/142986522-fc9d6c58-bc12-4194-a118-cbaddd562ead.png)

**Comment by vankop** [comment]
you probably need to use https://quasar.dev/quasar-cli/handling-webpack , pls ask questions regarding `quasar` in quasar repo.

**Comment by apidev234** [comment]
Okay.

**Comment by yusufkandemir** [comment]
There are two ways of configuring webpack as stated in https://quasar.dev/quasar-cli/handling-webpack.

`chainWebpack` solution:
```ts
chainWebpack(chain) {
  chain.merge({
    externals: {
      'node:util': 'commonjs util',
    }
  })
}
```

`extendWebpack` solution:
```ts
extendWebpack(cfg) {
  cfg.externals = {
    ...cfg.externals, // To preserve the previous configuration
    'node:util': 'commonjs util',
  }
}
```

As https://github.com/sindresorhus/wallpaper uses more of them, you would need to add all of them to externals.
