### ISSUE TITLE
Passing an argument to all files in a directory

### ISSUE THREAD

**Issue by dannycallaghan** [webpack/webpack#1480]
Each of my required (Angular) files returns a function, like so:

```javascript
export default app => {

  // with app, do something
  // such as app.controller('MyController', MyController);

};
```

At the moment, I require each file individually, like so:

require('/files/script1.js')('MyApp');
require('/files/script2.js')('MyApp');

How can I require all files in a directory, passing my 'MyApp' argument?

**Comment by bebraw** [comment]
You can achieve this easily by setting up a [require.context](https://webpack.github.io/docs/context.html). That will give you `req.keys()`. You can then iterate over that and hit each modlue with `MyApp`.

**Comment by dannycallaghan** [comment]
@bebraw 

Great, got it...

```javascript
const _ = require('underscore');

let services = require.context('./services', true, /^.*\.(js)$/);
_.each(services, function (element, index, list) {
    services(element)('MyApp');
});
```

Thanks
