### ISSUE TITLE
With library.type: module, import.meta.url shouldn't be replaced with static string

### ISSUE THREAD

**Issue by wmurphyrd** [webpack/webpack#14809]
# Bug report

**What is the current behavior?**

When bundling a library with `type: 'module'`, source references to `import.meta.url` are replaced with static `file:///...` strings. 

As a result, operations on query parameters like the [example from the MDN page on `import.meta`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import.meta#using_import.meta) do not work.

**If the current behavior is a bug, please provide the steps to reproduce.**

Observable at https://immers-space.github.io/immers-client/

```html
<script type="module" src="https://unpkg.com/immers-client/dist/destination.bundle.js?position=top-right&title=immers-client%20Documentation"></script>
```

```js
// destination.bundle.js source
scriptArgs = Object.fromEntries(new URL(import.meta.url).searchParams)
```

```js
// destination.bundle.js output
P = Object.fromEntries(new URL("file:///home/username/git/immers-client/oneLiner.js").searchParams)
```

`scriptArgs` is always empty because the `import.meta.url` is replaced with the build-time filepath

Webpack config (45 lines): https://github.com/immers-space/immers-client/blob/main/webpack.common.js

**What is the expected behavior?**

`import.meta.url` appears unmodified in the output and I am able to retrieve query parameters from it at runtime

**Other relevant information:**
webpack version:  5.64.2
Node.js version: v16.13.0
Operating System: Ubuntu 21.10
Additional tools: none

**Comment by alan-agius4** [comment]
I did came across this issue, as I was trying to use `import.meta.url` natively in the browser at runtime in an application build, but it turned out that Webpack will always replace this with a static string.

**Comment by alexander-akait** [comment]
Now we allow to disable `import.meta.url` behavior https://github.com/webpack/webpack/pull/15246

**Comment by alexander-akait** [comment]
So original issue resolved, just disable it for required files and it will work

**Comment by wmurphyrd** [comment]
Thanks @alexander-akait this looks like it will work. I'll try it out as soon as it is released

**Comment by vankop** [comment]
yep, this can be closed
