### ISSUE TITLE
libraryTarget and library

### ISSUE THREAD

**Issue by AqilbekAbilaev** [webpack/webpack#14815]
It is my part of webpack.dev.js 
output: {
        path: path.join(__dirname, 'dist'),
        filename: 'bundle.min.js',
        libraryTarget: 'var',
        library: 'Client'
    },
    
    here it is my html 
    <input type="submit" name="" value="submit" onclick="return Client.handleSubmit(event)" onsubmit="return handleSubmit(event)">
 
 
But every time I try npm run build-dev everything works cool but when I press submit button in the console 
formHandler.js:6 Uncaught TypeError: Client.checkForName is not a function
    at Module.handleSubmit (formHandler.js:6)
    at HTMLInputElement.onclick (?input=:23) keeps appearing :(

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

**Comment by alexander-akait** [comment]
You can use discussion if you can't provide example https://github.com/webpack/webpack/discussions

**Comment by AqilbekAbilaev** [comment]
Could you help me If I upload the source ?
