### ISSUE TITLE
Global package: problem to resolve loaders

### ISSUE THREAD

**Issue by Alphapage** [webpack/webpack#1482]
Hello,

I'm building a global npm package, but I get this error when using babel-loader:
```
Error: Cannot find module './node_modules/babel-loader/index.js'
```
The problem is webpack tries to resolve loaders from the target folder instead of my global package installation folder and of course I don't want webpack to be installed in the target folder because it is unnecessary.
How to tell webpack to use the babel-loader module from my global install ?

Thanks in advance for your help.

**Comment by bebraw** [comment]
You might need to set [resolve.root](https://webpack.github.io/docs/configuration.html#resolve-root). Read those configuration bits carefully. The solution is likely there.

**Comment by Alphapage** [comment]
I tried :
```
resolveLoader: {
      root: [
          path.join(__dirname, "node_modules")      ]
}
```
and even:
```
resolveLoader: {
      root: [
          path.join(require.resolve("webpack"),"../")
      ]
}
```
without success.
Maybe I don't use the right var since __dirname points to the target folder and I need the global folder path. 
Any suggestion ?

**Comment by bebraw** [comment]
I think the key is the statement "...global package installation folder...". Make sure the `root` points at that. It's hard to say anything more without knowing more about the file layout.

**Comment by Alphapage** [comment]
You are perfectly right.
From local folder, I know I can use __dirname to get the current working directory.
But from my global module, I don't know how to get the global folder path (that's why I tried path.join(require.resolve("webpack"),"../")) without success.
I'm sorry, I'm not a node module expert for now and I can't find that folder var by googling (nobody needs to work with a global node_modules path like me maybe)

**Comment by bebraw** [comment]
Can you get `tree` output? I need to understand how your `webpack.config.js` relates to your `node_modules`. Most likely there's some little utility at [the path module](https://nodejs.org/api/path.html) we can use here.

**Comment by Alphapage** [comment]
I found a way to point to the global npm installation folder like this (little hacky):
```
resolve: { fallback: path.join(require.main.filename,"../../../..") },
  resolveLoader: { fallback: path.join(require.main.filename,"../../../..") }
```
which points to c:\programfiles\nodejs\node_modules , but webpack doesn't resolve the package again.
What I'm missing now ? It should work !

**Comment by bebraw** [comment]
Forgot to ask... Is there any reason why you cannot make the package local to your project? Depending on a global version is a little risky always.

**Comment by Alphapage** [comment]
I need a global package because it will be used to create, manage... a project.
It is necessary to keep control over the project and it is impossible to do locally.
I hope you understand my requirements and why I don't want to install babel-loader inside the created project because it is unnecessary.

**Comment by bebraw** [comment]
Alright. Just curious. I would try

```javascript
resolve: {
  fallback: process.env.NODE_PATH,
  ...
}
```

No guarantees this will work but it seems like a cleaner solution to me.

**Comment by Alphapage** [comment]
I get process.env.NODE_PATH is undefined.
Sorry

**Comment by bebraw** [comment]
@Alphapage Ok. You usually set NODE_PATH on Unixy platforms just for these kind of cases. I expect you might do something similar on Windows. I don't have access to it at the moment so difficult to say.

**Comment by Alphapage** [comment]
Even if I add the real path : "C:\Program Files (x86)\nodejs" or "C:\Program Files (x86)\nodejs\node_modules".

It seems to be a bug in webpack which only search node modules locally even if resolveLoader is set to global node_modules path.

**Comment by bebraw** [comment]
Yeah, sounds like it. :disappointed:

**Comment by Alphapage** [comment]
Finally, I will add loaders in my local project as dependencies.
Thank you very much for your help. :+1:

**Comment by gajus** [comment]
Whats the reason this was closed if it is a bug?

**Comment by s-trooper** [comment]
I've similar problem and that work for me:

```js
    resolve: {
        fallback: process.env.NODE_PATH,
    },
    resolveLoader: {
        fallback: process.env.NODE_PATH
    },
```

where process.env.NODE_PATH is the global module installation path.

**Comment by sokra** [comment]
`resolveLoader` instead of `resolve` is the trick for resolving loaders

**Comment by Tiendq** [comment]
@bebraw Why not local? I want to install your package globally to test it before publishing, as explained here [](https://docs.npmjs.com/misc/developers)

`process.env.NODE_PATH` doesn't work on OSX too, but we can use known absolute path, it's just for our tests.

```js
resolve: {
  fallback: "/usr/local/lib/node_modules"
}
```
