### ISSUE TITLE
Webpack is unable to resolve "data:0" in uri

### ISSUE THREAD

**Issue by vsnikkil** [webpack/webpack#14831]
# Bug report
Webpack is unable to resolve the uri scheme which contains "data:0". In my case, I have a css file which tries to set `list-style-image: url(data:0)`. I'm not taking a stand on whether this is correct or not, it is a library file which content I cannot affect and preferable set the value to "none" (which by the way solves the build issue).

**What is the current behavior?**
Webpack throws an UnhandledSchemeError.
```
Module build failed: UnhandledSchemeError: Reading from "data:0" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.
You may need an additional plugin to handle "data:" URIs.
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Please use the following github repository to reproduce the issue:
https://github.com/vsnikkil/webpackurltest

**What is the expected behavior?**
Webpack resolves the data url correctly.

**Other relevant information:**
webpack version:  5.64.2
Node.js version: v17.1.0
Operating System: ubuntu linux

**Comment by alexander-akait** [comment]
Because it is invalid data uri, please use `data:0,`
