### ISSUE TITLE
Aliases and externals

### ISSUE THREAD

**Issue by jeron-diovis** [webpack/webpack#1483]
I'm using webpack to build server-side bundle. 
To don't include anything from `node_modules` to build, I'm using this solution found in internet:
```JS
{
 externals: fs.readdirSync("node_modules”)
    .filter(x => x !== ".bin")
    .reduce(
      (modules, name) => {
        modules[name] = `commonjs ${name}`;
        return modules;
      },
      {}
    )
}
```

Now, I want to use alises. Like `{ _: "lodash" }`. 
But, when I do `import "_"` (or `require("_")`), webpack does not understand, that "_" is "lodash", which is external. And includes it to build.

Is this correct behavior? Is it possible to configure an "external alias"?

**Comment by bebraw** [comment]
You probably should extend the code to map `_` as `lodash`. The simplest way I can see goes like this (pseudocode):

```javascript
externals: alias([['_', 'lodash']], fs.readdirSync(...))

function alias(aliases, files) {
  // you probably want to avoid mutating here. just being fast/cheap
  aliases.forEach((alias) => {files[alias[0]] = files[alias[1]});

  return files;
}
```

**Comment by jeron-diovis** [comment]
Found it in docs.
http://webpack.github.io/docs/configuration.html#externals

Format of `externals` is very flexible, so I ended up with smth like this:

```js

const nodeModules = fs.readdirSync("node_modules").filter(x => x !== ".bin");
const aliasesMap = ...my aliases here...;
const aliasedNodeModules = Object.keys(aliasesMap).filter(x => nodeModules.indexOf(aliasesMap[x]) >= 0);

const prefixCommonJs = (list, map = {}) => list.reduce(
  (modules, name) => {
    const realName = map[name] || name;
    modules[name] = `commonjs ${realName}`;
    return modules;
  },
  {}
);

...

{
   externals: [
     prefixCommonJs(nodeModules),
     prefixCommonJs(aliasedNodeModules, aliasesMap)
  ]
}
```

**Comment by bebraw** [comment]
Cool to know. :+1:
