### ISSUE TITLE
module Federation init too many remote.js

### ISSUE THREAD

**Issue by zhangzippo** [webpack/webpack#14837]
webpack5
# Bug report
when i see the code after build, i think something wrong with this:
![image](https://user-images.githubusercontent.com/20042465/143523818-100e594b-bd92-459d-864b-cf4ce38f8861.png)
the code from  __webpack_require__.I 
it case when init a remote container, all the container init env you use import().  when open first page. will init too many remote.js
i don't know why , thanks for telling me why

**Comment by zhangzippo** [comment]
moduleFederationplugin don't add the sharescope to the ContainerReferencePlugin , if i do this , it can run when router only 
init one remote, don't init all the remotes
![image](https://user-images.githubusercontent.com/20042465/143540511-8e73c6f7-4d59-4225-b033-bc05ad4f1d49.png)

**Comment by zhangzippo** [comment]
waiting for a answer, thanks

**Comment by vankop** [comment]
could you create a reproducible repo? it is hard to help you from this screenshots

**Comment by sokra** [comment]
might be related to https://github.com/webpack/webpack/pull/13819

**Comment by zhangzippo** [comment]
> 
oh yes, thanks.

**Comment by zhangzippo** [comment]
> might be related to #13819

but why it has't publish a version ? i see the pr not merge

**Comment by alexander-akait** [comment]
Because not tests in PR
