### ISSUE TITLE
assetModuleFilename doesn't affect chunkhash of final javascript file

### ISSUE THREAD

**Issue by stuff** [webpack/webpack#14839]
# Bug report

**What is the current behavior?**
Changing `assetModuleFilename` in configuration doesn't change `chunkhash` of files using `import`ed images.
this can lead to various caching problems (browser, procies, cdn etc)

**If the current behavior is a bug, please provide the steps to reproduce.**

you can find an example here https://github.com/stuff/webpack-assets-bug

webpack config:
```javascript
{
  mode: 'development',
  entry: './src/index.js',
  output: {
    filename: '[name].[chunkhash].js',
    path: path.resolve(__dirname, 'dist'),
    assetModuleFilename: 'img/[name]-[hash][ext]',
  },
  module: {
    rules: [
      {
        test: /\.(png|jpg|gif)$/i,
        type: 'asset/resource',
      },
    ],
  },
}
``` 
both ` assetModuleFilename: 'img/[name]-[hash][ext]'` and  `assetModuleFilename: 'assets/[name]-[hash][ext]'` results in a js file named `main.09783b82d14c2e26304e.js` actually resulting in 2 differents files with:

```javascript
eval("module.exports = __webpack_require__.p + \"img/oc-c1f902d15bfedbcc2538.png\"
``` 

```javascript
eval("module.exports = __webpack_require__.p + \"assets/oc-c1f902d15bfedbcc2538.png\";
``` 

**What is the expected behavior?**

I would expect that the final js filename has a different `chunkhash`

**Other relevant information:**
webpack version:  5.64.4
Node.js version: v16.13.0
Operating System: ubuntu 20.04

**Comment by alexander-akait** [comment]
Because the hash and chunkhash is the same for both builds...

**Comment by stuff** [comment]
@alexander-akait 
> Because the hash and chunkhash is the same for both builds...

is there something I should do on my side to prevent this? We don't change that configuration everyday, but we had bad times finding what was the issue here!

**Comment by alexander-akait** [comment]
But why you expected they should be different - same code, same configuration (except output), so hash is the same

**Comment by stuff** [comment]
I would expect a different filename just because that's the way cdn caches (like cloudflare) know that they should refetch the file.
In my case, `main.09783b82d14c2e26304e.js` was cached by cloudflare, and after I made the change in the config, any client trying to fetch it did get the old version, with the incorrect path to the image.

**Comment by alexander-akait** [comment]
You can add custom hash in your palceholders if you need something this, we generate the same hashes because we break caches if we will don't do it, it is long term cache

**Comment by vankop** [comment]
@alexander-akait I think you did not get what @stuff is expecting..
It is ok that *asset* has same hash. it is not ok that *js chunk* that uses this asset has same hash. (pls note file name are different `img/` vs `asset/` prefix
)

**Comment by stuff** [comment]
exactly this ;)
