### ISSUE TITLE
Please export PathData in types.d.ts

### ISSUE THREAD

**Issue by Knagis** [webpack/webpack#14858]
In order to properly create a function for processing output filenames, we need to declare `(pathData: webpack.PathData, assetInfo: webpack.AssetInfo) => string` however while AssetInfo is exported, PathData is not - it is only available when writing configuration inline or via something like: `Exclude<webpack.Configuration["output"]["assetModuleFilename"], string | undefined>`

Please export `PathData` interface.

**Comment by alexander-akait** [comment]
You can do it already using using ts helpers to extract arguments

**Comment by alexander-akait** [comment]
And please always use the issue template, respect time other developers, thanks

**Comment by Knagis** [comment]
yes, sorry about the template..

this does work but is the ability to do this sufficient reason not to export an interface that is otherwise present in the public API?

`Exclude<Exclude<webpack.Configuration["output"], undefined>["assetModuleFilename"], string | undefined>`

**Comment by alexander-akait** [comment]
Anyway PR welcome

**Comment by sokra** [comment]
Send a PR

**Comment by Knagis** [comment]
Is it ok to add it to declarations/index.ts? Because it probably is a bug in tooling/generate-types that it doesn't export types from the callback parameters, but i don't know if or when i would have time to dig into that part.

**Comment by alexander-akait** [comment]
Just add https://github.com/webpack/webpack/blob/main/lib/index.js#L47
```
/** @typedef {import("./path/to/pathData").StatsError} PathData */
```

**Comment by snitin315** [comment]
I will add it 👍🏻

**Comment by Knagis** [comment]
thank you! i am having troubles with `yarn special-lint-fix` breaking types.d.ts.. Seems it doesn't work on Windows? (trying WSL now)

**Comment by snitin315** [comment]
Hmm, I am facing similar issue on MacOS

**Comment by alexander-akait** [comment]
What is the problem?

**Comment by Knagis** [comment]
![image](https://user-images.githubusercontent.com/8700285/144408286-83948ee0-9aec-44ba-a85c-83d2c8c11dad.png)

**Comment by snitin315** [comment]
After adding `/** @typedef {import("./Compilation").PathData} PathData */`

`yarn special-lint-fix` fails.

<img width="1136" alt="Screenshot 2021-12-02 at 4 19 44 PM" src="https://user-images.githubusercontent.com/46647141/144408115-df5a5409-1d3a-4f55-8a5a-11de965644d1.png">

**Comment by alexander-akait** [comment]
Yep, looks like bug

**Comment by vankop** [comment]
bump
