### ISSUE TITLE
webpack@5.x.x can't detected and  polyfilled global variable  when  imported npm package which package.json's `type` value is "module"

### ISSUE THREAD

**Issue by TrickyPi** [webpack/webpack#14871]
# Bug report

## Current behavior
Not generated webpack runtime global code in bundled file

## Reproduce
[Minimal reproducible Github repository](https://github.com/TrickyPi/webpack-global-ponyfill-issue)

### How to reproduce
1. npm i
2. node ./addGlobalModule.js
3. npm run build --workspaces
4. See packages/webpack5/dist/bundle.js

## Expected behavior
genreate webpack runtime global code in bundled file
```js
/******/ 	/* webpack/runtime/global */
/******/ 	(() => {
/******/ 		__webpack_require__.g = (function() {
/******/ 			if (typeof globalThis === 'object') return globalThis;
/******/ 			try {
/******/ 				return this || new Function('return this')();
/******/ 			} catch (e) {
/******/ 				if (typeof window === 'object') return window;
/******/ 			}
/******/ 		})();
/******/ 	})();
```
## Fixed ?

I guess the reason is no javascript/esm handler in NodeStuffPlugin.js
[Target code](https://github.com/webpack/webpack/blob/main/lib/NodeStuffPlugin.js#L164)

**Comment by TrickyPi** [comment]
Can I submit a PR?

**Comment by vankop** [comment]
You have `type: module` in `is-global-module`, this marks `is-global-module` as type `javascript/esm`. In esm there is no Node.js globals, thats why webpack does not support them for `javascript/esm`. 

You can try to force this package to `javascript/auto`, e.g.
```js
module: {
        rules: [{
            type: 'javascript/auto'
        }]
    },
```

Feel free to feedback

**Comment by TrickyPi** [comment]
> You have `type: module` in `is-global-module`, this marks `is-global-module` as type `javascript/esm`. In esm there is no Node.js globals, thats why webpack does not support them for `javascript/esm`.
> 
> You can try to force this package to `javascript/auto`, e.g.
> 
> ```js
> module: {
>         rules: [{
>             type: 'javascript/auto'
>         }]
>     },
> ```
> 
> Feel free to feedback

@vankop May I ask you the meaning of In esm there is no Node.js globals ?

**Comment by TrickyPi** [comment]
> this one https://nodejs.org/api/esm.html#differences-between-es-modules-and-commonjs

@vankop Thanks for your reply, but  i didn't find `global` differences in this doc 😭 .

**Comment by vankop** [comment]
In esm environment we should not substitute `global`. Same for `__dirname` you can use it but we should leave it unchanged.

**Comment by TrickyPi** [comment]
Ok !
But webpack@4.x.x  and webpack@5.x.x are different，webpack@4.x.x substitute global In esm environment .

**Comment by vankop** [comment]
`webpack@4` does not support `type: module`

**Comment by vankop** [comment]
you should consider this as a breaking change from webpack@4 -> webpack@5

**Comment by TrickyPi** [comment]
Ok ! 
I got it .
Many thanks for your reply .
