### ISSUE TITLE
Using require with loader pulls returned module into main chunk 

### ISSUE THREAD

**Issue by janlent1** [webpack/webpack#14889]
# Bug report

**What is the current behavior?**
If you replace require with import it wil create a separate chunk. With require as is it won't.

**If the current behavior is a bug, please provide the steps to reproduce.**
Here is the repo for repro: https://github.com/janlent1/testrepo.git
If you replace require with import within entrypointFile.js it wil create a separate chunk. With require as is it won't.

**What is the expected behavior?**
It should both times create a separate chunk. Both require and import with loaders should handle chunk creation correctly.

**Other relevant information:**
webpack version:  "webpack": "^5.64.4"
Node.js version: v12.17.0
Operating System: MAC
Additional tools:

**Comment by alexander-akait** [comment]
Expected, because we create chunks only for `import()` by default, feel free to feedback, if you need to use require and have chunk you can use https://webpack.js.org/api/module-methods/#requireensure, but I strongly do not recommend do it
