### ISSUE TITLE
Destructuring DefinePlugin variables causes runtime error

### ISSUE THREAD

**Issue by villesau** [webpack/webpack#14883]
# Bug report

**What is the current behavior?**

Destructuring DefinePlugin variables causes runtime error `Uncaught ReferenceError: process is not defined`

**If the current behavior is a bug, please provide the steps to reproduce.**

1. have DefinePlugin plugin defined in the webpack config like this:

```
  plugins: [
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV)
    })
  ]
```
2. try to access `NODE_ENV` via destructuring: `const { NODE_ENV } = process.env;`
3. you get runtime failure `Uncaught ReferenceError: process is not defined`

However!

if you access NODE_ENV like `const NODE_ENV = process.env.NODE_ENV;` instead of `const { NODE_ENV } = process.env;` you don't get runtime error and everything works like expected.
 

**What is the expected behavior?**

Both ways of accessing the variable should be equal and should not cause runtime error.

It is pretty confusing and hard to debug problem and also problematic due to widely used `prefer-destructuring` eslint rule.

**Other relevant information:**
webpack version:  5.64.4
Node.js version: v16.13.0
Operating System: MacOS Big Sur
Additional tools:

**Comment by alexander-akait** [comment]
Duplicate https://github.com/webpack/webpack/issues/14800, limitation
