### ISSUE TITLE
Bug with gulp-uncss

### ISSUE THREAD

**Issue by kaidez** [webpack/webpack#1489]
I have a two separate build processes: one where webpack both builds out JS and inlines styles, and another where gulp runs an uncss task. When uncss runs on a page with webpack-processed .js files, I get the following error
   
    TypeError: 'undefined' is not a function (evaluating 'setImmediate.bind(window, flush)')

    http://localhost:8888/wp-content/themes/kaidez-swiss/js/common.js:9788
    http://localhost:8888/wp-content/themes/kaidez-swiss/js/common.js:9833
    http://localhost:8888/wp-content/themes/kaidez-swiss/js/common.js:9628
    http://localhost:8888/wp-content/themes/kaidez-swiss/js/common.js:11633
    http://localhost:8888/wp-content/themes/kaidez-swiss/js/common.js:11635
    http://localhost:8888/wp-content/themes/kaidez-swiss/js/common.js:51 in __webpack_require__
    http://localhost:8888/wp-content/themes/kaidez-swiss/js/common.js:107
    http://localhost:8888/wp-content/themes/kaidez-swiss/js/common.js:51 in __webpack_require__
    http://localhost:8888/wp-content/themes/kaidez-swiss/js/home.js:5
    http://localhost:8888/wp-content/themes/kaidez-swiss/js/common.js:51 in __webpack_require__
    http://localhost:8888/wp-content/themes/kaidez-swiss/js/common.js:22 in webpackJsonpCallback
    http://localhost:8888/wp-content/themes/kaidez-swiss/js/home.js:819

Where `common.js` contains common chunks while `home.js` contains specific code that also inlines styles on a page.

Thx!

**Comment by bebraw** [comment]
It's hard to say anything concrete without a test case.

Note that there's [purifycss-webpack-plugin](https://www.npmjs.com/package/purifycss-webpack-plugin) for webpack now.
