### ISSUE TITLE
ERROR in this.options.callback is not a function

### ISSUE THREAD

**Issue by code-masala** [webpack/webpack#14892]
ERROR in this.options.callback is not a function
in webpack@5.64.4
 don't know is it related to webpack or not.
Currently I updated to webpack in facing this issue.

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
