### ISSUE TITLE
Webpack  [contenthash] changes on file rename or if file is moved to another directory

### ISSUE THREAD

**Issue by Sebi2020** [webpack/webpack#14905]
# Bug report

**What is the current behavior?**
Contenthash depends on filename and target directory of source file.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Create a standard webpack config
2. Add the following to your webpack config:
```
  mode: 'production',
  ...
  output: {
    filename: '[name].[contenthash].js',
    clean: true
  }
```
3. Run webpack
4. Move your entry file to another directory or change it's filename without modification of the file content.
5. Run webpack again
6. => Contenthash changed

**What is the expected behavior?**

Contenthash should only depend on the file content,  not on the filename or the directory the file sits in.
If the content does not change, the hash should stay the same.

**Other relevant information:**
webpack version: webpack: 5.64.4, webpack-cli: 4.9.1
Node.js version:  v14.15.4
Operating System:  Windows 
Additional tools: Typescript

Related Issues:  #1479

**Comment by Sebi2020** [comment]
Related #1479

**Comment by alexander-akait** [comment]
Expected, if you need real content hash you should enable https://webpack.js.org/configuration/optimization/#optimizationrealcontenthash, it is `true` by default in `production` mode, and disabled by default in development mode due perf

**Comment by Sebi2020** [comment]
@alexander-akait Sad, that you directly closed the issue, cause **I am in production mode**! So if it is enabled by default it does not work as you describe.

**Comment by alexander-akait** [comment]
Can you provide reproducible example? Thanks

**Comment by a474516631** [comment]
The same problem occurs in gitlab CI. In the parallel construction task, package.json has not changed, but the hash value has changed, causing the persistent cache to become invalid

**Comment by vankop** [comment]
@Sebi2020 Could you reduce an issue to reproducible repo?

**Comment by Sebi2020** [comment]
@alexander-akait
@vankop
I will do so as soon as I find time to create a presentable minimal example.

**Comment by krishnasaga** [comment]
@Sebi2020 hope you have solved this problem already. 

I think the ash can be easily calculated after magnification 

Why not after the build run the below bash script to  rename the files with its content has ?

`find . -type f -exec bash -c 'mv "${1%.*}.$(md5 -q $1).${1##*.}"' bash {} \;`

This hash is generated on file that been emitted and written to the file system. So it is alway evident  that it there will be differentiate between before minification and after minification.    

Reference 
https://remarkablemark.org/blog/2017/09/24/rename-file-with-md5-hash/
