### ISSUE TITLE
webpack^5.64.4 can't support copy-webpack-plugin^10.0.0

### ISSUE THREAD

**Issue by freezyh** [webpack/webpack#14903]
# Bug report

**What is the current behavior?**
<e> [webpack-dev-middleware] HookWebpackError: Not supported
<e>     at processTicksAndRejections (internal/process/task_queues.js:97:5)
<e> -- inner error --
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  5.64.4
Node.js version:  v12.16.1
Operating System: win10 64
Additional tools:
"webpack-dev-server": "^4.6.0"

**Comment by alexander-akait** [comment]
Please update Node.js version, copy-webpack-plugin uses `import()` and you need to use the new version of Node.js
