### ISSUE TITLE
ES6 arrow functions & webpack.DefinePlugin

### ISSUE THREAD

**Issue by igl** [webpack/webpack#1490]
I am building my node app with Webpack and babel. Since node-v4* supports all kinds of es6 features already i started blacklisting stuff in my babel config.
Disabling es6.arrowFunctions will however break the definePlugin.

Whenever i use a baked-in variable inside of an arrow-function i get runtime errors like:

    ReferenceError: __DEV__ is not defined

Since webpack does not nag on compile-time, i assume it has no problem tokenizing es6 and this is a bug.

**Comment by sokra** [comment]
That's a bug.

**Comment by paveleremin** [comment]
+1 seems I have the same problem
