### ISSUE TITLE
.webpackrc

### ISSUE THREAD

**Issue by mdreizin** [webpack/webpack#1493]
As developer I would like to have ability to extend `core` API.

For example, I would like to add some processing of webpack options in addition to `WebpackOptionsDefaulter`. In my case I would be `WebpackOptionsExtender` from #1491 without modifying the core of `webpack`.

IMHO it gives ability to have more flexible architecture.

Probably `.webpackrc` will look like:

``` json
{
    "processOptions": {
        "pre": [
            "webpack-config-defaults",
            "webpack-config-extends"
        ],
        "post": [
            "webpack-config-apply"
        ]
    }
}
```

`webpack-config-defaults` - extracted from `WebpackOptionsDefaulter.js`
`webpack-config-extends` - extracted from `WebpackOptionsExtender.js` #1491
`webpack-config-apply` - extracted from `WebpackOptionsApply.js`

`WebpackOptionsDefaulter.js`, `WebpackOptionsExtender.js` and `WebpackOptionsApply.js` should inherit some stuff from `webpack-core`.

Now some parts of webpack code will look like:

_before_

``` js
new WebpackOptionsDefaulter().process(options);
new WebpackOptionsExtender().process(options);
// ...
compiler.options = new WebpackOptionsApply().process(options, compiler);
```

_after_

``` js
webpackrc.processOptions.pre.forEach(function(processor) {
    processor.process(options);
});
// ...
webpackrc.processOptions.post.forEach(function(processor) {
    compiler.options = processor.process(options, compiler);
});
```

If you agree with this I can help with implementing.

cc @sokra

**Comment by mdreizin** [comment]
Currently we can replace `OptionsDefaulter` with `OptionsResolver`:

```js
function OptionsResolver() {}

OptionsResolver.prototype.resolve = function(options) {
    return options; // it should return `options`
};

module.exports = OptionsResolver;
```

For instance, `WebpackOptionsExtender` will be moved to `webpack-config-extend-resolver` package and should inherit `OptionsResolver `.

In this case `.webpackrc` will look like:

```json
{
  "optionsResolvers": [
    "webpack-config-extend-resolver"
  ]
}
```

```js
var config = new Config();

config.resolveOptions(options);
```

```js
function Config() {}

Config.prototype.resolveOptions = function(options) {
    var config = this.getConfig();

    config.optionsResolvers.forEach(function(resolver) {
        options = resolver.resolve(options);
    });

    return options;
};

module.exports = Config;
```

**Comment by bebraw** [comment]
@sokra Any thoughts? Perhaps it's better to leave experiments like this outside of the core and make sure they are possible to implement.
