### ISSUE TITLE
Analyze tool is down

### ISSUE THREAD

**Issue by mattydoincode** [webpack/webpack#1494]
Seems to be a simple http vs https problem:  https://webpack.github.io/analyse/

**Comment by mattydoincode** [comment]
On a related note, does anyone know where the source code is for this tool so I can run it myself? I found this: https://github.com/robertknight/webpack-bundle-size-analyzer  but it's pretty bare bones.

**Comment by taurose** [comment]
Works without https: http://webpack.github.io/analyse/ . You might have to disable HTTPS Everywhere for the page if you use that. Or, you can allow "unsafe scripts"/"insecure content" via the browser (e.g. Chrome and Firefox show a shield icon in the URL bar).

From what I can tell:
* Repo: https://github.com/webpack/analyse
* Issue: https://github.com/webpack/analyse/issues/6
* PR: https://github.com/webpack/analyse/pull/8
