### ISSUE TITLE
AMD breaks strict mode

### ISSUE THREAD

**Issue by benmosher** [webpack/webpack#1495]
I have a module that uses AMD and `'use strict'`, and as a result, here are the first few lines of webpack output:

```js
/***/ },
/* 36 */,
/* 37 */,
/* 38 */
/***/ function(module, exports, __webpack_require__) {

	var __WEBPACK_AMD_DEFINE_ARRAY__, __WEBPACK_AMD_DEFINE_RESULT__;'use strict';
        // ... later, some `let` statements
```

Since the `'use strict'` is not the first statement, strict mode is not actually enabled. 

As a workaround, I can add another `'use strict'` inside th module definition callback.

The simple solution would seem to be to insert the var declaration after any `'use strict'` that is present in the module. 

I am willing to take a stab at this in a PR if you'd like, though I suspect it's a quick fix if you know where to look. 😅

**Comment by sokra** [comment]
> I am willing to take a stab at this in a PR if you'd like, though I suspect it's a quick fix if you know where to look.

I suspect it's more complex to fix :(

**Comment by benmosher** [comment]
Ah, bummer. 

Worth me taking a stab at it as a first bug, do you think? Or is it too deep?

**Comment by sokra** [comment]
fixes

**Comment by haishengwu-okta** [comment]
@sokra would you link the fix commit and what's the release version the fix has?
