### ISSUE TITLE
bug: webpack should properly eliminate dead code when doing variable re-assignments

### ISSUE THREAD

**Issue by liamdebeasi** [webpack/webpack#14963]
# Bug report

**What is the current behavior?**

When using Webpack and a single entry point file for importing items, re-assigning variables causes the contents of that variable to be bundled with an application, even if the application never imports that variable.

In the example below, both the `Badge` and `Avatar` components get bundled even though the application only imports `Badge`.

**If the current behavior is a bug, please provide the steps to reproduce.**

Minimal reproduction: https://github.com/liamdebeasi/webpack-reassignment-demo
1. Run `npm install`.
2. Open `src/index.js`. Observe that only `Badge` is imported.
2. Run `npx webpack`.
3. Run `grep -o -i -E 'avatar bundle|badge bundle' dist/main.js`. This will search the built output for the `"avatar bundle"` and `"badge bundle"` strings. These strings are found in the `avatar.js` and `badge.js` files and are used to quickly tell if Webpack is bundling the components when building. Observe that both strings appear, meaning both `Badge` and `Avatar` are bundled with the app.
4. In `components/avatar.js` remove `Avatar = Avatar`.
5. In `components/badge.js` remove `Badge = Badge`.
6. Run `npx webpack`.
7. Run `grep -o -i -E 'avatar bundle|badge bundle' dist/main.js`. Observe that only the ``"badge bundle"`` string appears, meaning only `Badge` is bundled.

**What is the expected behavior?**

I would expect only the `Badge` component to get bundled since that is what the application imports.

**Other relevant information:**
webpack version:  5.65.0
Node.js version: 16.11.1
Operating System: macOS 11.6.1
Additional tools: webpack-cll@4.9.1

This was also discussed at https://github.com/webpack/webpack/discussions/14962

**Comment by sokra** [comment]
I guess that would be possible to implement...

**Comment by vankop** [comment]
hm.. should this work right now with `sideEffects: false` + `/*@__PURE__*/` notation?

**Comment by vankop** [comment]
Ok, this works for me 

Badge.js
```js
Badge = /*@__PURE__*/ Badge;
```

Avatar.js
```js
Avatar = /*@__PURE__*/ Avatar;
```

package.json
```json
{
  "name": "webpack",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "webpack": "^5.65.0",
    "webpack-cli": "^4.9.1"
  },
  "sideEffects": false
}
```

in result will be only Badge bundled

**Comment by alexander-akait** [comment]
I think reassign should not be market `Pure` (this issue about this), yes you provide good workaround

**Comment by vankop** [comment]
hm.. unsure. Can we have side effect here?

**Comment by alexander-akait** [comment]
In theory yes -  `foo = bar() = foo`;
