### ISSUE TITLE
Worker will not load if URL is not inline

### ISSUE THREAD

**Issue by Akxe** [webpack/webpack#14960]
# Bug report

If I were to initialize the worker in way described bellow:
```js
const workerURL = new URL('./worker.ts', import.meta.url);
const worker = new Worker(workerURL);
console.log(worker,workerURL  workerURL);
```

As for the reason why I wanted this, it is because I want to initialize a `SharedWorker`, if possible otherwise I want a `Worker`. This originated from https://github.com/angular/angular-cli/issues/22362

**What is the current behavior?**

The load fails with an error: `Failed to fetch a worker script.`.

From my observation, the URL provided to the worker is a typescript file that is otherwise correct.

**If the current behavior is a bug, please provide the steps to reproduce.**

* Create an angular project (`npx ng new worker-app`)
* Create wire angular worker (`ng generate web-worker`)
* Instead of inlining the URL, create a variable of it and pass the constant to the constructor.

**What is the expected behavior?**

The code provided to the worker should be compiled the same even if the code is not inline

**Other relevant information:**
webpack version:  5?
Node.js version: 14.15.4
Operating System: Windows
Additional tools: Angular, Nrwl

**Comment by alexander-akait** [comment]
Expected, because it is not statically analyzable, you should use `new URL(...)` inside `new Worker()`

**Comment by alexander-akait** [comment]
Webpack see your code as asset module - https://webpack.js.org/guides/asset-modules/

**Comment by alexander-akait** [comment]
Please use:
```
if (SharedWorker) {
	worker = new SharedWorker(new URL('./worker/fetcher.worker', import.meta.url), { name: 'fetcher' });
	worker.port.onmessage = (event: MessageEvent) => this.messages$.next(event.data);
	sendMessage = worker.port.postMessage.bind(worker.port);
	worker.port.start();
} else {
	console.warn('App is running per in per tab basis');
		worker = new Worker(new URL('./worker/fetcher.worker', import.meta.url), { name: 'fetcher' });
	worker.onmessage = (event: MessageEvent) => this.messages$.next(event.data);
	sendMessage = worker.postMessage.bind(worker);
}
```
