### ISSUE TITLE
HMR breaks async module graph + dynamic import (Top level await or Async WebAssembly)

### ISSUE THREAD

**Issue by Jack-Works** [webpack/webpack#14974]
# Bug report

**What is the current behavior?**

Webpack generates invalid code:

> Uncaught (in promise) ReferenceError: _defer_js__WEBPACK_IMPORTED_MODULE_1__ is not defined

**If the current behavior is a bug, please provide the steps to reproduce.**

Reproduction: https://github.com/Jack-Works-forks/webpack-hmr-async-module-bug

```sh
npx webpack serve --mode development --hot
```

**What is the expected behavior?**

Works normally

**Other relevant information:**
webpack version:  5.65.0
Node.js version: 17.2.0

**Comment by Jack-Works** [comment]
Webpack config:

```js
const html = require('html-webpack-plugin')
module.exports = {
    devtool: false,
    experiments: { topLevelAwait: true },
    optimization: { minimize: false },
    plugins: [new html()]
}
```

> src/index.js

```js
import './tla.js'
import('./defer.js').then(console.log)
import.meta.webpackHot.accept(['./defer.js'], () => console.log('hmr'))
```

> src/defer.js

```js
import log from './tla.js'
log()
```

> src/tla.js

```js
await Promise.resolve()
export default function log() {
    console.log('log called')
}
```

**Comment by alexander-akait** [comment]
Yes, bug, thanks for the issue

**Comment by Jack-Works** [comment]
Is there any ongoing fix? Or if I should try it?

**Comment by alexander-akait** [comment]
You can send a PR
