### ISSUE TITLE
HMR does not work when page require output bundles from multiple entries

### ISSUE THREAD

**Issue by toBeTheLight** [webpack/webpack#14981]
# Bug report

**What is the current behavior?**

HMR does not work when page require output bundles from multiple entries in webpack 5.
But it works in webpack 4.

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/toBeTheLight/issue-20211215

1. Require multiple bundles in page from two entries(single complier or multiple compliers):
  ```
  // from { first: ['xxxx']} in entry config
  <script src="./first.js">
  // from { second: ['xxxx']} in entry config
  <script src="./second.js">
  ```
2. change second.js
3. hmr work
4. change first.js
5. page request first.hot-update.js,but report an error `Uncaught TypeError: Cannot set properties of undefined (setting './src/first.js')` and a warning `Update failed: ChunkLoadError: Loading hot update chunk first failed`

**What is the expected behavior?**
Hmr of all files work.

**Other relevant information:**
webpack version:  v5.0.0~latest

I guess, in webpack5, hrm context of first.js has be overwritten by second.js(which is loaded later).

For example，in [webpack5](https://github.com/webpack/webpack/blob/main/lib/web/JsonpChunkLoadingRuntimeModule.js)：
```js
var currentUpdatedModulesList;
var waitingUpdateResolves = {};
function loadUpdateChunk(chunkId) {
	return new Promise((resolve, reject) => {
		waitingUpdateResolves[chunkId] = resolve;
		var url = __webpack_require__.p + __webpack_require__.hu(chunkId);
		var error = new Error();
		var loadingEnded = (event) => {
      // ......
		};
		__webpack_require__.l(url, loadingEnded);
	});
}

self["webpackHotUpdatewebpack5"] = (chunkId, moreModules, runtime) => {
  // ......
	if(waitingUpdateResolves[chunkId]) {
		waitingUpdateResolves[chunkId]();
		waitingUpdateResolves[chunkId] = undefined;
	}
};
```
After first.js emit hmr, function `loadUpdateChunk` run. And then, when `self["webpackHotUpdatewebpack5"]`  is running, `waitingUpdateResolves` in `self["webpackHotUpdatewebpack5"]` is the one be declared by second.js, and it is empty, so update of first.js failed.

When in single complier, using `optimization.runtimeChunk` can resolve this problem. But it is not available for multiple compliers.

And maybe relate to https://github.com/webpack/webpack/commit/887852f6df9774d52b017c0bd8781466966a64e7 of webpack 4?

**Comment by alexander-akait** [comment]
Answered https://github.com/webpack/webpack-dev-server/issues/2792#issuecomment-808328432, please set `optimization.runtimeChunk`, you have multiple runtime on the same page, it is bad

**Comment by toBeTheLight** [comment]
@alexander-akait 
Need to set different plugins and  different `optimization.splitChunks` config for different functional files, we must use multiple compliers.  
But setting `optimization.runtimeChunk` doesn't work for multiple compliers, because `__webpack_require__.h` are difference from each compliers, although we can set runtime output file to same name. 

see https://github.com/toBeTheLight/issue-20211215/blob/master/webpack5/package.json and run `npm run compliers`

**Comment by alexander-akait** [comment]
You different unique names for compilers, just add `name` and `output.uniqueName` for each compiler https://github.com/toBeTheLight/issue-20211215/blob/master/webpack5/webpack.compliers.config.js#L3, it will generated different runtimes for different compilers

**Comment by alexander-akait** [comment]
Multi compilers and multi entries was design for different purposes, you can't use multiple entries (from one compiler) on the same  page without `optimization.runtimeChunk`

**Comment by toBeTheLight** [comment]
And I noticed the warning under runtimeChunk in documentation
> Imported modules are initialized for each runtime chunk separately, so if you include multiple entry points on a page, beware of this behavior.

Could I know why can't use multiple entries (from one compiler) on the same page without optimization.runtimeChunk, what would happen in bad case?

We have so many scenes using multiple entries on the same page from one compiler 😅, and they could not split chunks, because the output file may be use in current project and other projects by cdn（something like library）.🤔 Maybe I should split that kind of entries into difference compilers and set different `output.uniqueName`.

**Comment by alexander-akait** [comment]
> Could I know why can't use multiple entries (from one compiler) on the same page without optimization.runtimeChunk, what would happen in bad case?

Because each entry has own part of runtime code (i.e. chunks/code/logic/ they can have different public path and more), you can get problems (I can describe them, but there are a lot of them), you need to merge runtime and extract runtime in separated chunk, even more it will better for long term cache with hashes for production usage.

Note - you need do it only for configurations where you have multi entries on the same page, if you reuse bundle from other compiler just check you have unique name for runtime, we have `output.uniqueName` option for this, but by default generate name from `package.json` (the `name` field), so if you have monorepo most likely you will not face this problem

**Comment by toBeTheLight** [comment]
Find https://github.com/webpack/webpack/issues/13316, study later, thanks.
