### ISSUE TITLE
Define library in EntryObject does not give the same output than define library in output

### ISSUE THREAD

**Issue by PierBJX** [webpack/webpack#14990]
# Bug report

**What is the current behavior?**
If I define the `library` in the `EntryObject` or  in the `Output` with `JQuery` in externals it does not give the same output. Indeed, `Jquery` is not define or require anymore when library is defined in `EntryObject`.

**If the current behavior is a bug, please provide the steps to reproduce.**
- Find a reproductive example [here](https://github.com/PierBJX/fluffy-enigma/tree/main/webpack/output-library) and clone the repo. 
- Go to `output-library` folder and run ```webpack```.
- Check the bundled file in the dist, you will have something like that:
```
(function webpackUniversalModuleDefinition(root, factory) {
	if(typeof exports === 'object' && typeof module === 'object')
		module.exports = factory(require("jQuery"));
	else if(typeof define === 'function' && define.amd)
		define("library/example", ["jQuery"], factory);
	else if(typeof exports === 'object')
		exports["library/example"] = factory(require("jQuery"));
	else
		root["library"] = root["library"] || {}, root["library"]["example"] = factory(root["jQuery"]);
})(self, function(__WEBPACK_EXTERNAL_MODULE_jquery__) {
```

- Uncomment the library property in the `entry.example` and comment the library property in the `output`.
- Run ```webpack```.
- Check the bundled file in the dist, you will have something like that:
```
(function webpackUniversalModuleDefinition(root, factory) {
	if(typeof exports === 'object' && typeof module === 'object')
		module.exports = factory();
	else if(typeof define === 'function' && define.amd)
		define("library/example", [], factory);
	else if(typeof exports === 'object')
		exports["library/example"] = factory();
	else
		root["library"] = root["library"] || {}, root["library"]["example"] = factory();
})(self, function() {
```

As you can see there is no more `JQuery` in the bundle file.

**What is the expected behavior?**
We should have the same bundle file.

**Other relevant information:**
webpack version:  5.64.4
Node.js version: 14.17.5
Operating System: Windows 10
Additional tools:

**Comment by sokra** [comment]
When `externals` do not explicitly specified a type of external, they will use the `externalsType` type, which defaults to `output.library.type`.

By not specifying `output.library.type` you are basically switching the externals to a different type. From `amd` to `var`. So they no longer appear in the amd library.

Either set `externalsType: "amd"` or `externals: { jquery: "amd jQuery` }`

**Comment by PierBJX** [comment]
Thanks it works !
