### ISSUE TITLE
Questions, webpack running order?

### ISSUE THREAD

**Issue by gseok** [webpack/webpack#15008]
My webpack config file return function style and final return array. that time webpack running order?

e.g) webpack.conf.js (example)

```
module.exports = () => {
  return [getClientConfig(), getServerConfig()];
};
```

- In these case, webpack running `client` build and `server` build.
- But I don't known, running order.. A or B?
  - A. Array order -> First (Client Build) -> Second (Server Build)
  - B. reverse order -> First (Server Build) -> Second (Client Build)

I'm very curious. Please answer me!! (ps. I'm using webpack5)

**Comment by sokra** [comment]
They run concurrently. You could set `parallelism` on the array to control how many run concurrently:

``` js
module.exports = () => {
  const configs = [getClientConfig(), getServerConfig()];
  configs.parallelism = 1;
  return configs;
};
```

You can also use `dependencies` in the config to define dependencies between configurations.
