### ISSUE TITLE
Inaccurate parsing of  sourcemap in production mode

### ISSUE THREAD

**Issue by Magin-CC** [webpack/webpack#15018]
# Bug report

**What is the current behavior?**
![image](https://user-images.githubusercontent.com/16484068/146672722-91ab010e-28a8-42cf-8f1d-995b04db636a.png)
This is my dist code build with `production` mode. The `source` is not falseLike, but sourcemap chose the wrong branch.

**If the current behavior is a bug, please provide the steps to reproduce.**
```
const arr = window.arr ||  [];
function test(n) {
    if(window.nn) {
        return window.nn;
    }
    const source = [...arr, n];
    if(source) {
        window.nn = source;
        return source;
    } else {
        return [];
    }
}
window.test = test;
```
This is my minimal reproducible code. Build it then debug the `test` mehod.
I think this maybe a bug from Terser or esbuild ( I tryed use my customize EsbuildPlugin as minimizer) . Because when I set `minimize` to `false`, the behavior of sourcemap is normal.
Do you have any suggestions for this ？
Grateful to you !

**Other relevant information:**
webpack version:  4.46.0 / 5.65.0
Node.js version: 10.24.1
Operating System: windows 10
Additional tools: Chrome 96.0.4664.110

**Comment by alexander-akait** [comment]
Please open an issue in `EsbuildPlugin`, thanks

**Comment by alexander-akait** [comment]
Also we support esbuild as minimizer https://github.com/webpack-contrib/terser-webpack-plugin#esbuild, so you don't need to use custom plugins
