### ISSUE TITLE
Compile stuck at "additional chunk assets"

### ISSUE THREAD

**Issue by fresheneesz** [webpack/webpack#1501]
After updating to node v4.1.2, I'm seeing my production compilation take much much longer. I think it took around 40 seconds before, and it now takes about 4 minutes. I tried updating from webpack 1.4.13 to 1.12.2, but didn't seem to change anything. I added the ProgressPlugin, and the compilation is hanging for minutes on "additional chunk assets" at 79%. If I remove the UglifyJsPlugin that wait time is gone, similar to this issue: https://github.com/webpack/webpack/issues/537 . I tried `sourceMap: false` in the Uglify plugin but that doesn't seem to help.

Also, is it usual for the percentages to not always increase with the ProgressPlugin? I'm seeing percentages go from 25->26->27->28->27->26 and then back up. Is that normal? That part's not a huge deal, just weird.

**Comment by fresheneesz** [comment]
I also tried webpack v1.7.2 and v1.7.0, which someone had suggested in https://github.com/webpack/webpack/issues/537 , but I had the same issue.

**Comment by adjavaherian** [comment]
Are you sure its source maps?  I'm using 4.1.1 with source maps.  but I'm using this one.

`devtool: '#eval-source-map',`

no probs, here.  perhaps its node-sass?  that should be re-compiled whenever you switch node versions.

**Comment by sokra** [comment]
> Also, is it usual for the percentages to not always increase with the ProgressPlugin? I'm seeing percentages go from 25->26->27->28->27->26 and then back up. Is that normal? That part's not a huge deal, just weird.

percentages are approximate. We don't know the exact modules could beforehand. modules are discovered when dependencies are followed.

**Comment by jontonsoup** [comment]
+ 1

**Comment by vsabella** [comment]
+1 we are seeing the same issue. Any hints on how this can be debugged?

**Comment by Gerarddp** [comment]
+1 If I remove the UglifyJsPlugin it works fine but the size increases by about 50%. And I couldn't find a way to show which file is causing the problem.

**Comment by FrendEr** [comment]
I have the same issue!!!

**Comment by JsonHunt** [comment]
I was able to resolve the "79% additional chunk assets" slowness by adding this line in webpack-config:
```
module: {
   noParse: new RegExp("node_modules"),
   ....
```

**Comment by fresheneesz** [comment]
@JsonHunt And your application still works after that?? You're ignoring all your npm modules bro..

**Comment by JsonHunt** [comment]
@fresheneesz Check out updated comment above. It works if you exclude just the dev dependencies

**Comment by Tzaphkiel** [comment]
I also have the same problem when I do a build for production and I include in the code a big dependency like 'alloyeditor'. When I remove it, it works fine.
The `node` process is not actually blocked, it uses CPU and its memory goes up and up and up...
This happens just before the optimize chunks.

**Comment by framerate** [comment]
I can get it to build with `devtool: false` but it takes about ~6 minutes to build a single file with 3 dependencies. Something is definitely up with uglify.... Removing uglify and the build is instant.

`new webpack.optimize.UglifyJsPlugin({compress: {warnings: false}, sourceMap: false}),`

**Comment by creeperyang** [comment]
#2616 maybe will help with this issue

**Comment by bebraw** [comment]
Can you try against webpack 2?

**Comment by yantakus** [comment]
Having the same issue. Upgrading to webpack 2 doesn't help. Any ideas?
