### ISSUE TITLE
Source Maps not Compatible with Visual Studio - Unsupported format of the sourcemap

### ISSUE THREAD

**Issue by samunro** [webpack/webpack#1502]
I was getting the following error when trying to debug TypeScript that had been bundled using webpack.

```
Unsupported format of the sourcemap
```

I provided lots of details on how I isolated the problem in a [StackOverflow answer](http://stackoverflow.com/a/32952254/81595) and a [Visual Studio Connect bug](https://connect.microsoft.com/VisualStudio/feedback/details/1873069/unsupported-format-of-the-sourcemap-errors).

The long and short of it though, is that the Source Maps that webpack is generating, include short segments in the mappings property at the ends of some lines (where lines are separated by semi colons).

After I manually edited the source map files be removing these segments, I was able to debug TypeScript files (set breakpoints that would be hit) without any problems.

Browsers do not seem to have any problem with the weppack generated source files. I don't know whether that means the format is correct or just that they are more lenient than Visual Studio. At any rate, I would consider modifying the source maps to make them compatible with Visual Studio.

You can use the following regular expression within Visual Studio to replace the short segments.

```
,\s*[^\s\";]{1,3}?(;|\")
```

Just make sure that you have regular expressions enabled in the find and replace pane and that matches are replaced with the following - which will be either a semi colon or a quote if it is the last line in the mappings property..

$1

Also, I attached a solution to the [Visual Studio Connect bug](https://connect.microsoft.com/VisualStudio/feedback/details/1873069/unsupported-format-of-the-sourcemap-errors) which will demonstrate the problem. There are two versions of the source map (before and after removing the short segments). The before version will result in the error above.

**Comment by sokra** [comment]
VisualStudio bug... these seqments are part to the SourceMap and removing them would modify the SourceMap.

Feel free to write a webpack plugin which "fixes" the SourceMap. Or try the `cheap-module-source-map` devtool, which generates only a simple mapping per line for performance. This could avoid short mappings.

**Comment by samunro** [comment]
Thanks sokra. I linked to your feedback in the bug for Visual Studio that I submitted. I don't have any feedback from that so far.

**Comment by joevbruno** [comment]
@sokra @samunro I wrote a webpack plugin that seems to solve most of this issue, at least for now: https://github.com/joevbruno/vs-fix-sourcemaps

**Comment by Sleepyowl** [comment]
@sokra @joevbruno @samunro 
It seems that the problem might lie with inline source maps in modules that webpack glues together.

For instance, VS rejects a source map after encountering the following segment: `+sQ`.
Decimal representation would be [8399]. Only lines that are that long in the generated file are inline maps.

Problem goes away after addition of `webpack.optimize.UglifyJsPlugin`.

**Comment by joevbruno** [comment]
@sokra @samunro @cellvia
I think may be on to something with the UglifyJSPlugin helping to a certain extent. There does seem to be an issue with the source-map line segments; however, what seems to be a bigger issue is this:

 if you look at a generated source-map WITHOUT the webpack uglifyJS plugin, the `sources` list is incomplete (you should notice a number of your files are not there) and the `names` array is completely empty - at least it is for me. 

Once I re-add the webpack uglify js plugin, the names array is heavily populated and the sources list is complete. Once this happens, Visual Studio seems to be sort of happy. When debugging in IE, the bundled webpack file will fill out with all of the thousands of dependencies and you actually can set breakpoints. Unfortunately, it is difficult to work in because everything is mangled and the line-numbers appear to be badly off as a result of the mangling. Anyone have any ideas as to why the names field is unpopulated by 'default' and the sources list is incomplete?

**Comment by IAMtheIAM** [comment]
I found the solution. You just had to add the Uglify plugin because the comments are messing visual studio up.  

Look at [this webpack config](https://github.com/joevbruno/vs-fix-sourcemaps/issues/3#issuecomment-220070725) for an example of how to do it.

**Comment by joevbruno** [comment]
new version of this plugin should fix most of these issues now: https://github.com/joevbruno/vs-fix-sourcemaps

**Comment by acostaf** [comment]
@joevbruno 


Getting and error with the plugin **TypeError: VSFixSourceMapsPlugin is not a constructor** I am using version 1.0.1
 

`		var webpack = require('webpack');
		var VSFixSourceMapsPlugin = require('vs-fix-sourcemaps');

		module.exports = {
			entry: './app/main.ts',
			output: {
				path: './dist/',
				filename: 'bundle.js'
			},
			resolve: {
				// Add `.ts` and `.tsx` as a resolvable extension.
				extensions: ['', '.ts', '.js']
			},
			devtool: 'source-map',
			plugins: [
				new VSFixSourceMapsPlugin()
			]...`

**Comment by bebraw** [comment]
Can you see this in webpack 2?

**Comment by involve-it** [comment]
@acostaf Use `new VSFixSourceMapsPlugin.default();`, worked for me!
