### ISSUE TITLE
The type of err should include null

### ISSUE THREAD

**Issue by swnf** [webpack/webpack#15029]
# Bug report

**What is the current behavior?**
The type of `err` in the callback of `Compiler.run` and `Compiler.runAsChild` is `Error | undefined`. If the compilation is successful, the actual value of `err` is `null`.

**If the current behavior is a bug, please provide the steps to reproduce.**
Just run the compiler, e.g. as described [here](https://webpack.js.org/contribute/writing-a-loader/#testing).

**What is the expected behavior?**
If `err` cannot be `undefined`, the type should be `Error | null`. Otherwise, the type should be `Error | undefined | null` (or `err?: Error | null`).

**Other relevant information:**
webpack version:  5.65.0
Node.js version: v16.13.0
Operating System: Ubuntu 21.10
Additional tools: Typescript 4.5.4

**Comment by luffy84217** [comment]
Hello, is anyone working on this? Besides, is this bug confirmed? If so, I'll try to do it.

**Comment by alexander-akait** [comment]
PR welcome

**Comment by alexander-akait** [comment]
Fixed https://github.com/webpack/webpack/pull/15050
