### ISSUE TITLE
The cache.maxGenerations config works in filesystem cache to keep .cache directory slim.

### ISSUE THREAD

**Issue by hiyuki** [webpack/webpack#15034]
## Feature request

**What is the expected behavior?**
The `cache.maxGenerations` config works in `filesystem` cache to keep cache files slim.

**What is motivation or use case for adding/changing the behavior?**
Our project is huge, which generate a huge .cache directory over 800MB, and the cache size keep increasing with the passes of compilation. We run the CI progress in a new docker environment everytime when the project code changed, so we need store the .cache directory in outside storage, huge cache file will slow down the CI progress obviously.

I read the source code and find that filesystem cache always keep the unused items until the maxAge is exceeded, so what i need is to set maxGenerations limit to 1 and remove unused items from cache files everytime.

**How should this be implemented in your opinion?**
Record the generations in pack content items, read the `cache.maxGenerations` config and decide to keep or remove unused items in `Pack._optimizeUnusedContent`.

**Are you willing to work on this yourself?**
Yes

**Comment by alexander-akait** [comment]
Duplicate https://github.com/webpack/webpack/issues/13291

**Comment by hiyuki** [comment]
@alexander-akait 
Perhaps it is a different issue with #13291.
What we want is to remove the unused cache items, which is contained in `Pack.content[i].items`, but in #13291, it is the unused cache files, this is another question but we could solve it by adding an extra process which remove the old file judged by mtime.

**Comment by alexander-akait** [comment]
These are interrelated problems, we should solve them together. Removing unused cache from fs is not only about files.

**Comment by alexander-akait** [comment]
The `maxGenerations` option is only to cache memory, we show it in our docs `Define the lifespan of unused cache entries in the memory cache.` https://webpack.js.org/configuration/cache/#cachemaxgenerations, but I see your problem, and we should solve, feel free to put feedback in https://github.com/webpack/webpack/issues/13291 so that we don't lose it too

**Comment by alexander-akait** [comment]
We have layer cache, i.e. when you use `filesystem` we still use memory cache, but also store it in fs

**Comment by hiyuki** [comment]
Ok, thanks for your answer, i will expect it.
