### ISSUE TITLE
Building library with webpack in postinstall script

### ISSUE THREAD

**Issue by errashe** [webpack/webpack#15046]
# Bug report

**What is the current behavior?**

Tryin to import and build library with webpack in postinstall script. Have repo for understanding - https://github.com/errashe/somelib. 

Used by yarn like - "somelib": "git+ssh://git@github.com:errashe/somelib.git#master".

And postinstall script generate errors like this - 
```Module parse failed: Unexpected token (1:19) You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file.```

Looks like a bug for me. Cuz that's pretty fine building like standalone library. Even more - if i yarn-link that library into my project - that's easily building and could be used.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Create new project with yarn.
2. Add library into package.json file with `"somelib": "git+ssh://git@github.com:errashe/somelib.git#master"`
3. Run `yarn install`

**What is the expected behavior?**

Builded library and generated dist inside node_modules/somelib directory.

**Other relevant information:**
webpack version:  5.65.0
Node.js version: v17.2.0
Operating System: maxOS 12.0.1 21A559

**Comment by alexander-akait** [comment]
Sorry, no problems with webpack, we don't have special logic for package managers or scripts, also your problem is not reproducible, double check your environment
