### ISSUE TITLE
Harmony Reexport Cause Error on Legacy Firefox

### ISSUE THREAD

**Issue by fynncfchen** [webpack/webpack#15056]
# Bug report

**What is the current behavior?**

When using nested export all like following in source file:

```javascript
// es/index.js
export * from './core';
export * from './react';

// es/core/index.js
export * from './types';

// es/react/index.js
export * from './types';
```

it will be transpiled as

```javascript
/* harmony reexport (unknown) */ for(const __WEBPACK_IMPORT_KEY__ in _types__WEBPACK_IMPORTED_MODULE_14__) if([/* other modules... */].indexOf(__WEBPACK_IMPORT_KEY__) < 0) __WEBPACK_REEXPORT_OBJECT__[__WEBPACK_IMPORT_KEY__] = () => _types__WEBPACK_IMPORTED_MODULE_14__[__WEBPACK_IMPORT_KEY__]
```

which causes Firefox 34 with following error

```
SyntaxError: invalid for/in left-hand side
```

**If the current behavior is a bug, please provide the steps to reproduce.**

```
.
├── core
│   └── index.js
├── react
│   └── index.js
├── index.js
├── package.json
├── webpack.config.js
└── yarn.lock
```

`webpack.config.js`
```javascript
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
  devtool: 'source-map',
  mode: 'development',
  entry: './index.js',
  plugins: [
    new HtmlWebpackPlugin()
  ]
}
```

`index.js`
```javascript
export * from './core';
export * from './react';

console.log('hello')
```

`core/index.js`
```javascript
// empty
```

`react/index.js`
```javascript
// empty
```

1. Install packages
2. Launch application by `webpack serve`
3. Access to `http://localhost:8080` on Firefox 34
4. Got error on console `SyntaxError: invalid for/in left-hand side`

**What is the expected behavior?**

No errors, maybe use `var` instead of `const` for backward compatibility, or have an option to transpile it.

```javascript
for(var __WEBPACK_IMPORT_KEY__ in _core__WEBPACK_IMPORTED_MODULE_0__)
```

**Other relevant information:**
webpack version:  4.9.1
Node.js version: v12.22.1
Operating System: macOS Monterey 12.0.1 (Intel)
Additional tools:

**Comment by alexander-akait** [comment]
Set `target: ['web', 'es5']` or create browserslist with supported browsers (https://github.com/browserslist/browserslist), we are generating runtime based on your supported browsers https://github.com/webpack/webpack/blob/main/lib/config/browserslistTargetHandler.js#L129 (for `const`), if not provided we use `web` (and generate `es6` code, i.e. `const`/etc), it is breaking change for webpack v5

**Comment by axetroy** [comment]
I also got the same problem and found this issue. Bug `target: ['web', 'es5']` did not resolve it in Webpack 5.91.0

<img width="915" alt="截屏2024-05-17 15 25 46" src="https://github.com/webpack/webpack/assets/9758711/dd509016-2b04-4fe4-9b47-c7077561c695">

Am I missing something?
