### ISSUE TITLE
Question: node-libs-browser

### ISSUE THREAD

**Issue by adjavaherian** [webpack/webpack#1505]
When I look at my webpack bundle with http://chrisbateman.github.io/webpack-visualizer/ I notice that roughly 10% of the bundle is dedicated to node-libs-browser.  I've removed all references to node common api's in my app code, but it looks like libs-browser deps are still bundled up.  Is that normal?  Do these libs have to be included with all bundles?  If not, how do I configure them out?

**Comment by sokra** [comment]
They are only included when you require them (or any dependency). You can use the [analyse tool](http://webpack.github.io/analyse/) to find these references.
