### ISSUE TITLE
Feature request: Multiple entry points => 1 file

### ISSUE THREAD

**Issue by jmeas** [webpack/webpack#1506]
Is it possible to take multiple entry points and produce a single file? The use case are unit tests.

I have a large application with `n` unit tests. Each test file is independent from one another, so webpack requires that they be specified as multiple entry points. However, webpack seems to take an `n => n` approach to multiple entry points: each entry file produces an output.

Is there any way to do `n => 1` where the files are simply concatenated at the end? Browserify is another module loader I know of that supports this (that's what I'm using now).

**Comment by SimenB** [comment]
At work we use karma to run the tests, and https://github.com/webpack/karma-webpack/blob/master/README.md#alternative-usage works fine for us. It creates multiple bundles, but that could probably be disabled by `new webpack.optimize.LimitChunkCountPlugin({maxChunks: 1})` or something similar if it's a problem for you.

**Comment by jmeas** [comment]
Ah, of course...a plugin! I should have been more thorough with my digging through the docs. @SimenB , it looks like the `LimitChunkCountPlugin` will do the job for me.

And thanks for the Karma link! I've been considering switching to Karma.

Gonna close, 'cause this seems to be an existing feature.
