### ISSUE TITLE
Import a .js and redirect to .ts(x)

### ISSUE THREAD

**Issue by otakustay** [webpack/webpack#15063]
## Feature request

**What is the expected behavior?**

For TypeScript's new `nodenext` module resolution (which is still in nightly build), we are required to write a full file name including extension like:

```ts
import {foo} from './foo.js';
```

Even though we have a source code `foo.ts` or `foo.tsx`, the file extension on import statement is `.js`, this results webpack to fail with errors like:

```
error  in ./src/index.tsx

Module not found: Error: Can't resolve './Boundary.js' in '/Users/otakustay/Develop/react-suspense-boundary/src'
```

**What is motivation or use case for adding/changing the behavior?**

We need to satisfy TypeScript's coming `nodenext` module resolution and be compatible with pure ESM resolve rules

**How should this be implemented in your opinion?**

Make `.js` a special case that on resolve webpack could remove the `.js` part and then do a normal resolve

Another solution is to make `resolve.fallback` a function so that we can remove `.js` part before webpack do it's resolve

**Are you willing to work on this yourself?**

not familiar with this

**Comment by alexander-akait** [comment]
Duplicate https://github.com/webpack/webpack/issues/13252, current solution https://github.com/webpack/webpack/issues/13252#issuecomment-971922821, maybe we move it in core
