### ISSUE TITLE
Feature: Implement require("@parent/myfile") to get parent module

### ISSUE THREAD

**Issue by Alphapage** [webpack/webpack#1508]
Hello,

Is it possible to implement such a feature in webpack without waiting npm approbation because npm features are added extremely slowly?

https://github.com/npm/npm/issues/9945

Thanks in advance for your answers.

**Comment by Phoenixmatrix** [comment]
It's not NPM that has to do this, its node/commonjs standards themselves.

**Comment by sokra** [comment]
Not possible, because a module could have multiple parents.
