### ISSUE TITLE
externals for multiple entry

### ISSUE THREAD

**Issue by moshuying** [webpack/webpack#15084]
## Feature request

I use `webpack:"^5.64.4"` to package my multi-entry program, which is used by me to build various web programs based on different technical architectures, such as `react, vue, raw-javascript`, each technology The content that needs to be excluded on the page of the framework is not the same. If I introduce a heavyweight program in a light program, it will be catastrophic. When I tried to use `"html-webpack-plugin": "^5.5.0"` to automatically exclude, I found that there is no plug-in or configuration item that can do this, such as `html-webpack-deploy-plugin` Either `html-webpack-tags-plugin` or `html-webpack-externals-plugin` and other plug-ins, they either put all references in or cannot run at all. When I try to debug to understand the running details of these plugins, I finally understand that it is difficult to achieve this requirement by plug-ins alone, so I will share this idea with you. I don’t know if anyone can help.

**Comment by alexander-akait** [comment]
Please open an issue in `html-webpack-plugin` repo, thanks, webpack doesn't generate html code yet (we will maybe implement it in future)
