### ISSUE TITLE
I have an HTML file with style elements containing sass-css code:

### ISSUE THREAD

**Issue by M4j2cxc** [webpack/webpack#15088]
I have an HTML file with style elements containing sass-css code:

```html
<style>
  $font-stack: Helvetica, sans-serif;
  $primary-color: #333;
  
  body {
    font: 100% $font-stack;
    color: $primary-color;
  }
</style>
```

Is it possible to process CSS code in `<style>` elements with Webpack 5?

I'd like to compile them to CSS using SASS and minify the CSS code.

_Originally posted by @BlueNebulaDev in https://github.com/webpack/webpack/discussions/15087_

**Comment by alexander-akait** [comment]
No need to duplicate, you already have a discussion, you need to write loader for this
