### ISSUE TITLE
External require without Webpack?

### ISSUE THREAD

**Issue by kraftwer1** [webpack/webpack#1509]
Some third person without Webpack (or even Browserify) would like to require modules out of my `bundle.js` - during runtime (browser). I've tried to set it up as described in: https://github.com/webpack/docs/wiki/webpack-for-browserify-users#external-requires

At my entry point:
```coffeescript
externalRequire = ((parentRequire) ->
    (module) ->
        parentRequire module
)(if typeof __non_webpack_require__ is "function" then __non_webpack_require__ else (->
    throw new Error "Module \"" + module + "\" not found"
))

`export default externalRequire`
```

My config:
```javascript
{
    entry: "./app/index.js",
    output: {
        library: "require",
        libraryTarget: "this"
    }
}
```

But when I try requiring it in the browser...
```javascript
require("./config"); // works during Webpack compilation
```
...I get the error: **Uncaught Error: Module "[object Object]" not found**

Now the docs say "webpack for browserify users", does that mean the above code explicitly only runs on Browserify, or does it not require another module loader at all (since `window.require` is now defined)?

**Comment by IngwiePhoenix** [comment]
Did you find a solution? I'd like to know it.

**Comment by kraftwer1** [comment]
I've found out that the third person actually has an AMD loader and I've tricked Webpack using this syntax:

```javascript
window["define"]("config", function() {
    return require("./config");
});

window["define"]("math", function() {
    return require("./math");
});
```

So these two modules can be required using an AMD loader like this one: https://github.com/ember-cli/loader.js
