### ISSUE TITLE
Update watchpack dependency in webpack 4 to fix deprecated warning

### ISSUE THREAD

**Issue by 1Jesper1** [webpack/webpack#15096]
Update `watchpack `dependency in `webpack `4 to fix deprecated warning: `chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.`

**Comment by alexander-akait** [comment]
Please migrate on webpack v5, webpack v4 accepts only security fixes
