### ISSUE TITLE
Support "browser" field

### ISSUE THREAD

**Issue by sokra** [webpack/webpack#151]
https://gist.github.com/defunctzombie/4339901

**Comment by shawninder** [comment]
It seems this `browser` field needs the full path to a file instead of allowing for a path to a directory and defaulting to index.js. I'd like to propose adding this functionality to allow usage similar to node and browserify.

**Comment by mnpenner** [comment]
Since the answer isn't posted here, it appears `browser` *is* a default field now. [Documentation here](https://webpack.js.org/configuration/resolve/#resolve-mainfields)

**Comment by mitra42** [comment]
Any idea how you would use this to stop a node module trying to load fs? 
For libsodium, adding   "browser": { "fs": false }, to packages.json seems to work, but this approach doesn't work for webtorrent, so its not clear if the libsodium project did something different than webtorrent.

**Comment by dy** [comment]
That does not seem to work with objects defined as `browser` field, eg.
```js
"browser": { "index.js": "browser.js", "sync.js": "browser.sync.js" }
```

**Comment by Bkucera** [comment]
I think this should be re-opened, since webpack does not currently respect objects set in the `browser` field.

**Comment by davnicwil** [comment]
@Bkucera which version are you on? The following is working for me with v4.19.0

```json
  "browser": {
    "module": false
  }
```
