### ISSUE TITLE
Watching symlinks doesn't work in dev mode

### ISSUE THREAD

**Issue by pauldraper** [webpack/webpack#15100]
# Bug report

**What is the current behavior?**

Watching symlinks doesn't work after multiple changes in development mode.

**If the current behavior is a bug, please provide the steps to reproduce.**

**webpack.config.js**

```
module.exports = {
  entry: './main.js',
  watchOptions: { followSymlinks: true, },
  mode: "development",
  output: {
    path: __dirname,
    filename: 'bundle.js',
  },
  resolve: { symlinks: false }
};
```

**main.js**

Symlink to ./data/123.js

**data/123.js**

```js
console.log("A");
```

Run

```
webpack --watch
```

```
echo 'console.log("B")' > main.js
echo 'console.log("C")' > main.js
```

**What is the expected behavior?**

I expected bundle.js to contain `console.log("C")`, but it contained `console.log("B")`.

**Other relevant information:**

webpack version:  5.65.0
Node.js version: 17.3.0
Operating System: Ubuntu 20.04
Additional tools:

---

Strangely, this example works fine in production mode.

**Comment by alexander-akait** [comment]
Yep, bug, it is not reproduced in production due the `cache` option https://github.com/webpack/webpack/blob/main/lib/config/defaults.js#L168 (disabled in production)

**Comment by markjm** [comment]
Seems maybe this is solveable within webpack. To work around the issue, @pauldraper you can set `snapshot.module.hash = true`. to use hash of content instead of timestamp

**Comment by markjm** [comment]
Watchpack is properly watching `data/123.js` in addition to `main.js`. When we get the change event on `data/123.js`, we see the updated timestamp, and correctly emit `main.js` as the changed file into webpack (via "aggregated" event). However, the `fileTimestamps[main.js]` is not updated, so when we check snapshots, its still valid and goes to cache.

**Comment by pauldraper** [comment]
Wow, thanks! (Spent all day tracking that one down, and creating a WatchFileSystem that worked for my particular needs.)

I confirmed that `snapshot.module.hash = true` fixes the issue.

**Comment by markjm** [comment]
Obviously not an efficient solution, but confirmed that fixing the timestamps correctly invalidates cache|

![image](https://user-images.githubusercontent.com/16494982/148140965-4dc4a816-5306-4b48-809c-54efbb448bcf.png)

looking though watchpack, it seems we would need a little more in the way of piping through some information to really fix this at the source.

**Comment by assetinsights** [comment]
Hello, Is there any further progress on this? We are having the same issue when linking between packages and was wondering if there was a fix that would be released?

**Comment by andreialecu** [comment]
I'm seeing this with Angular 13. It used to work with Angular 11.

It appears that making any changes in a shared library which is symlinked into Angular 13 will not result in the changes being applied properly. 

I'm also using `preserveSymlinks` in `angular.json` which sets `resolve: { symlinks: false }` as per: https://github.com/angular/angular-cli/blob/a0784bd8cb64bd719ed499f97603522fbc9db02d/packages/angular_devkit/build_angular/src/webpack/configs/common.ts#L317

Angular 13 does catch the change and it does trigger a recompilation, but if I look at the generated .js bundle, they're never there. It seems like the previous version gets stuck until the process is restarted. (cc @alan-agius4)

**Comment by alan-agius4** [comment]
@andreialecu, your issue is not related to this one. What you are describing is actually expected and working as intended. `node_modules` are considered immutable and also get invalidated once the version in package manifest changes.

See https://github.com/angular/angular-cli/issues/22104 and https://github.com/angular/angular-cli/issues/20962

**Comment by pauldraper** [comment]
>  this may be a limitation with some of the symlink settings

FWIW, I would be confused why watchOptions.followSymlinks would even exist as an option. It only makes sense to be true if resolve symlinks are disabled.

**Comment by HillLiu** [comment]
It could work by add `cache:false` in top level for yarn link + webpack hot update case.

And don't need others such as napshot.module.hash = true and watchOptions: { followSymlinks: true, }.

https://github.com/react-atomic/reshow/blob/main/packages/reshow-app/src/webpack.client.js#L52

**Comment by guio12** [comment]
Thanks for the tip, it works indeed, but unfortunately on my project the update / watch recompilation becomes so slow (~2 minutes for each change instead of 10 seconds) it is unusable.

**Comment by thaoula** [comment]
> @andreialecu, your issue is not related to this one. What you are describing is actually expected and working as intended. `node_modules` are considered immutable and only get invalidated once the version in package manifest changes.
> 
> See [angular/angular-cli#22104](https://github.com/angular/angular-cli/issues/22104) and [angular/angular-cli#20962](https://github.com/angular/angular-cli/issues/20962)

Hi @alan-agius4, I still think Angular 13, 14 does have this issue. We have a symlinked model folder that is shared between and Angular app and a NodeJs project. The folder is not in node_modules. 

When we change a file. For example, adding a property to a class .. Angular recompiles but complains that the class does not contain this new property. Killing the build and starting again resolves the issue but this is starting to become a massive drag on productivity.

Is there anyway to utilise any of the strategies above in the Angular.json or disable caching for a specific folder?

Regards,
Tarek

**Comment by alan-agius4** [comment]
> Is there anyway to utilise any of the strategies above in the Angular.json or disable caching for a specific folder?

No, you either enable or disable caching. If you do want to modify the webpack configuration you can do so using 3rd party builders. However, this is not supported by the Angular team.

**Comment by alexander-akait** [comment]
bump
