### ISSUE TITLE
Treeshaking failing to remove an export that's only dynamically imported

### ISSUE THREAD

**Issue by ditkin** [webpack/webpack#15102]
# Bug report

**What is the current behavior?**

I found a bug with treeshaking, and will link to [this repo](https://github.com/ditkin/graphql-tutorial/tree/main/frontend) to explain it.

The `RxFunctionList` file defines 2 named exported variables - [one small](https://github.com/ditkin/graphql-tutorial/blob/main/frontend/src/RxFunctionList.tsx#L27-L31) (a graphQL fragment) and [one heavy](https://github.com/ditkin/graphql-tutorial/blob/main/frontend/src/RxFunctionList.tsx#L12-L25) (the entire list of rxjs exports).
Another file, `App`, [statically imports the light export](https://github.com/ditkin/graphql-tutorial/blob/main/frontend/src/App.tsx#L4) from `RxFunctionList`, and [dynamically imports the heavy export](https://github.com/ditkin/graphql-tutorial/blob/main/frontend/src/App.tsx#L6-L9).

**Goal: for webpack's treeshaking to remove the heavy export from the main bundle, as we only statically import the light variable from `RxFunctionList`.** We want the main bundle to be free of any of the rxjs exports.

Test case | Static import only | Dynamic import only | BUG: Static AND dynamic import 
-|-|-|-
Result | treeshaking removes rxjs exports as expected | the bundle does not contain rxjs exports (they are code split) | **BUG: treeshaking fails, bundle includes rxjs exports**
Main bundle size (before minification) | 589kb | 588kb | 802kb
Webpack bundle analzyer | ![image](https://user-images.githubusercontent.com/5571242/148147279-b1542245-c744-48e1-b476-84b6d9e5271f.png) | ![image](https://user-images.githubusercontent.com/5571242/148147747-29cf3b9a-4cd7-49b7-b7b8-625ee725041b.png) | ![image](https://user-images.githubusercontent.com/5571242/148147007-8f5c7401-8574-48b8-8e51-c4ed1b0d2e81.png)
Branch code | [static import](https://github.com/ditkin/graphql-tutorial/blob/static-import-only/frontend/src/App.tsx#L4) | [dynamic import](https://github.com/ditkin/graphql-tutorial/blob/dynamic-import-only/frontend/src/App.tsx#L6-L9) | [static import](https://github.com/ditkin/graphql-tutorial/blob/main/frontend/src/App.tsx#L4) and [dynamic import](https://github.com/ditkin/graphql-tutorial/blob/main/frontend/src/App.tsx#L6-L9)

## Steps to reproduce

1. make sure your node version is 17+
2. `git clone` [this repo](https://github.com/ditkin/graphql-tutorial/issues/1)
3. `cd frontend`
4. `yarn install`
5. `yarn build`
6. `webpack-bundle-analyzer` should open, and the main bundle should be 800+ kb (before minification). 
7. for further proof the bundle contains rxjs, open `dist/main.bundle.js` and see that it includes rx functions like `bindnodecallback`, `dematerialize`

## Additional information

I found [this discussion](https://github.com/webpack/webpack/discussions/15052) of a similar topic and [made sure to enable Terser in my webpack config](https://github.com/ditkin/graphql-tutorial/blob/main/frontend/webpack.prod.config.js#L13). As explained in the grid above, I am getting treeshaking to work properly when only statically importing from a file - but it fails to treeshake exports that are dynamically imported, despite the fact they are never statically imported.

**Other relevant information:**
webpack version:  5.65
Node.js version: 17
Operating System: Mac OS 
Additional tools: yarn, react, typescript

## Are you willing to work on this yourself

Potentially

**Comment by alexander-akait** [comment]
But:
1. Don't use `rxjs`, because you don't use `RxFunctionList`
2. You still have `rxjs`, `rxjs` inside chunk `353.chunks.js`
3. Webpack move `rxjs` inside one chunk because it is better for code splitting

For `2` and `3` fully size is the almost same

**Comment by ditkin** [comment]
@alexander-akait Thanks for the response. Yes 2 and 3 full size is about the same, but I'm confused about 
>Webpack move rxjs inside one chunk because it is better for code splitting

Code in the main chunk needs to be downloaded up front by the browser, which adds latency and hurts parse time. Shouldn't webpack be treeshaking `rxjs` out of the main bundle in the third case, since it is never statically imported?

**Comment by alexander-akait** [comment]
You have this https://github.com/ditkin/graphql-tutorial/blob/main/frontend/src/RxFunctionList.tsx#L17, so we can't remove `rxjs`, why you think it should be removed?

**Comment by ditkin** [comment]
Because `RxFunctionList` is never statically imported into the main bundle. [It is only imported dynamically](https://github.com/ditkin/graphql-tutorial/blob/main/frontend/src/App.tsx#L7). 

I expect `RxFunctionList`, and all imports that are only consumed in `RxFunctionList`, to be in a split chunk, but they are going into the main bundle.

**Comment by alexander-akait** [comment]
You can setup `splitChunks` to do it, by default we decide to keep this in one chunk

**Comment by vankop** [comment]
@alexander-akait should we close this?

**Comment by alexander-akait** [comment]
Yep
