### ISSUE TITLE
`asset/source` option to change line endings from CRLF to LF

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [webpack/webpack#15113]
## Feature request
When using `type: 'asset/source'`, I get a string which contains `\r\n`. I want the string to be consistent on all platforms regardless of if the file on the file system was CRLF or not. The feature request is to add a way of changing all `\r\n` to `\n` as part of the imported string.

**What is the expected behavior?**
Imported string should have LF line endings

**What is motivation or use case for adding/changing the behavior?**
I am using the imported string in `useState` in react. The `\r\n` is causing an unnecessary re-render because the code changes it to `\n` and my `useEffect`s get called twice, with basically the same string (but with different line endings).

**How should this be implemented in your opinion?**
### Breaking change
Always replace CRLF with LF

### Option
Maybe an option to process the text before, or an option to set the line ending.

**Are you willing to work on this yourself?**
maybe, depending on how many changes it needs

**Comment by alexander-akait** [comment]
Sorry, out of scope webpack, you can write a plugin

**Comment by ChocolateLoverRaj** [comment]
@alexander-akait Would the plugin process the file first before the `asset/source` happens?

**Comment by alexander-akait** [comment]
You can also create loader (it will be even easy), and remove newlines using RegExp, it is not safe to move this logic in core
