### ISSUE TITLE
`createModule` `NormalModuleFactory` hook has incomplete typing

### ISSUE THREAD

**Issue by chrissantamaria** [webpack/webpack#15112]
👋 this isn't strictly a bug, though I noticed there's some slightly incomplete types which make interfacing with Webpack via Typescript a bit tricky.

I'm attempting to use the `createModule` `NormalModuleFactory` hook and read properties from its returned `createData`. However, Typescript gives an error:
```js
normalModuleFactory.hooks.createModule.tap(PLUGIN_NAME, (createData) => {
  // Typescript gives error "Property 'resource' does not exist on type 'Object'
  const { resource } = createData;
});
```

From what I can tell, this is due to `createData` being loosely typed as `Object`:

https://github.com/webpack/webpack/blob/ccecc17c01af96edddb931a76e7a3b21ef2969d8/lib/NormalModuleFactory.js#L42-L56

However, a complete type _does_ exist in the constructor for `NormalModule`:

https://github.com/webpack/webpack/blob/ccecc17c01af96edddb931a76e7a3b21ef2969d8/lib/NormalModule.js#L248-L266

From what I can tell, this constructor object's shape should be identical to the `createModule` hook argument (`ResolveData["createData"]`):

https://github.com/webpack/webpack/blob/ccecc17c01af96edddb931a76e7a3b21ef2969d8/lib/NormalModuleFactory.js#L303-L314

Is there any reason the `NormalModule` constructor typing can't be reused in `ResolveData`? I've attempted this locally and it seems to generate types in `types.d.ts` as expected, fixing the issue for both the `createModule` and `module` hooks.

If this sounds okay, I'm happy to open a PR and take a stab at this :)

**Comment by alexander-akait** [comment]
PR welcome
