### ISSUE TITLE
configuration.resolve.alias['node:'] should be a non-empty string

### ISSUE THREAD

**Issue by tjx666** [webpack/webpack#15129]
# Bug report

I want to replace all the module name like `node:fs` to `fs`, so I set resolve.alias:

```javascript
resolve: {
        alias: {
            'node:': ''
        },
    },
```

**What is the current behavior?**

error message: 

```
configuration.resolve.alias['node:'] should be a non-empty string
```

**What is the expected behavior?**

No validate configuration failed error.

**Other relevant information:**
webpack version:  5.65.0
Node.js version: 16.13.1
Operating System: MacOS 12.1

**Comment by alexander-akait** [comment]
Duplicate https://github.com/webpack/webpack/issues/14166, current solution https://github.com/webpack/webpack/issues/14166#issuecomment-923840210
