### ISSUE TITLE
add a module "magic comment" to force federated import

### ISSUE THREAD

**Issue by AlonMeytalVia** [webpack/webpack#15139]
## Feature request
Add a "magic comment" (see here https://webpack.js.org/api/module-methods/#magic-comments) to help Webpack understand imported module is federated.

**What is the expected behavior?**
today, it seems like federated module have to be imported explicitly, so that the transpiled import code would look like this:
(wrapper by `React.lazy()`)
```javascript
react__WEBPACK_IMPORTED_MODULE_0___default().lazy(() => __webpack_require__.e(/*! import() */ "webpack_container_remote_<module name>").then(__webpack_require__.t.bind(__webpack_require__, /*! <module name> */ "webpack/container/remote/<module name>", 23)))
```
instead of
```javascript
react__WEBPACK_IMPORTED_MODULE_0___default().lazy(() => __webpack_require__("./src/blocks lazy recursive")(widgetName));
```
When adding the "magic comment" `/* webpackFederatedModule: true */` inside an `import` statement, Webpack will compile it as if the module was recognized by the `ModuleFederationPlugin` (resulting in the first example above, rather than the second).

**What is motivation or use case for adding/changing the behavior?**
Allow dynamically importing modules using module federation for use-cases such as dynamic dashboard/plugin systems.

**How should this be implemented in your opinion?**
again - magic comment would be best (least amount of footprint in the code).
a different import function would also work.

**Are you willing to work on this yourself?**
I wish. Maybe with some guidance from a senior contributor.

**Comment by alexander-akait** [comment]
> Webpack will compile it as if the module was recognized by the ModuleFederationPlugin (resulting in the first example above, rather than the second).

Can you clarify? Import works the same for any `import`

**Comment by AlonMeytalVia** [comment]
You can see in the attached example, the transpiled code for `import(<federated module name>)` and for `import(<variable holding federated module name>)` end up very differently

**Comment by alexander-akait** [comment]
Because it is different imports, sorry I don't understand your request

**Comment by AlonMeytalVia** [comment]
it seems that because the explicit import is identified as a remote module the result transpiled code is different.
is it like that for all explicit (vs. implicit) imports??

**Comment by alexander-akait** [comment]
I don't understand what you try to achieve, please provide example

**Comment by sokra** [comment]
You want context support for module federation so ``import(`mfe1/${expr}`)`` works

**Comment by AlonMeytalVia** [comment]
@sokra thanks for the input. put I want the "opposite", I want to use a dynamic remote, not a dynamic component.
@alexander-akait you asked for an example, our use case is as follows:
We have a dashboard of widgets. Each widget will developed by a different team.
We want to allow the team to "subscribe" with their remote to a single source, and pull both remotes and the widgets inside of them dynamically based on user needs.

**Comment by sokra** [comment]
Something like that: https://h3manth.com/posts/dynamic-remotes-webpack-module-federation/

**Comment by AlonMeytalVia** [comment]
yeah. just "natively".

**Comment by sokra** [comment]
If the remote is listed in the remotes list, I think that would work for you:

> You want context support for module federation so ``import(`mfe1/${expr}`)`` works

**Comment by alessioerosferri** [comment]
@AlonMeytalVia I am having the same problem, how did you solve it? Thanks

**Comment by AlonMeytalVia** [comment]
@alessioerosferri using the code in the example @sokra provided.
