### ISSUE TITLE
LIBERTY LIBERTY LIBERTY when building for production

### ISSUE THREAD

**Issue by alexsorinsky** [webpack/webpack#15130]
well, hi there... a really have no one idea what's going on (yes i am not sure that this problem related to webpack), but as soon as i've updated local npm deps and run "**npm run build**" this happened:

![pic](https://i.imgur.com/6Y3Crj8.png)

i think that some repo being cracked and just wonna inform you all guys, about this

btw: **npm run serve** - works fine (so i just start my local dev server). this happens only when i run webpack in production mode

my package.json i some one would like to chek it out (possible someone of this repos being hacked):

```json
{
  "name": "frmlibs",
  "version": "1.0.0",
  "description": "",
  "private": true,
  "scripts": {
    "serve": "webpack serve --mode development --config config/webpack.config.js",
    "build": "webpack --mode production --config config/webpack.config.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@popperjs/core": "^2.11.2",
    "animate.css": "^4.1.1",
    "bootstrap": "^5.1.0",
    "cash-dom": "^8.1.0",
    "jquery": "^3.6.0",
    "lit": "^2.0.2",
    "lodash-es": "^4.17.21",
    "scrollama": "^3.0.2"
  },
  "devDependencies": {
    "@babel/core": "^7.15.0",
    "@babel/plugin-proposal-class-properties": "^7.14.5",
    "@babel/plugin-proposal-decorators": "^7.15.8",
    "@babel/plugin-syntax-dynamic-import": "^7.8.3",
    "@babel/plugin-transform-runtime": "^7.15.0",
    "@babel/preset-env": "^7.15.0",
    "@nurminen/html-beautify-webpack-plugin": "^1.1.3",
    "@webdiscus/pug-loader": "^1.4.4",
    "babel-loader": "^8.2.2",
    "copy-webpack-plugin": "^9.0.1",
    "core-js": "^3.16.1",
    "css-loader": "^6.2.0",
    "favicons": "^6.2.2",
    "favicons-webpack-plugin": "^5.0.2",
    "html-loader": "^2.1.2",
    "html-webpack-plugin": "^5.3.2",
    "install": "^0.13.0",
    "mini-css-extract-plugin": "^2.2.0",
    "postcss": "^8.3.6",
    "postcss-flexbugs-fixes": "^5.0.2",
    "postcss-loader": "^6.1.1",
    "postcss-preset-env": "^6.7.0",
    "sass": "^1.37.5",
    "sass-loader": "^12.1.0",
    "style-loader": "^3.2.1",
    "terser-webpack-plugin": "^5.1.4",
    "webpack": "^5.50.0",
    "webpack-cli": "^4.7.2",
    "webpack-dev-server": "^3.11.2",
    "webpack-manifest-plugin": "^4.0.2"
  }
}
```

**Comment by alexsorinsky** [comment]
yep, this is something other... here is the problem https://github.com/Marak/colors.js/issues/285

OMG, WTF, that's not good that Webpack after update is going to be paralized by that issue

**Comment by DanielRuf** [comment]
As this is not directly related to webpack but a deeply nested dependency, I think we can close here.

The maintainer of colors.js added an infinite loop, which causes this.

**Comment by alexsorinsky** [comment]
very cringe

yep, in a case if someone makes new build - you are n't hacked... this is how opensource works and grugs affects ))

**Comment by jkterry1** [comment]
So, I'm just an amused onlooker from reddit and not really a javascript developer myself, but like:

 The guy fully yanked another large javascript package 3 days ago (https://www.reddit.com/r/javascript/comments/rwdu3h/fakerjs_gets_erased/), posted an incoherent rant about the update color.js update that caused this and removed all the other maintainer's access from npm (https://github.com/Marak/colors.js/issues/285) and was recently made homeless after accidentally firebombing his own apartment (https://abc7ny.com/suspicious-package-queens-astoria-fire/6425363/, https://twitter.com/marak/status/1320465599319990272). Accordingly, there's pretty healthy chance that color.js in its current incarnation is permanently offline.

If color.js is a "a deeply nested dependency" for webpack, then surely this constitutes a webpack issue and not a color.js issue at this point..?

**Comment by jkterry1** [comment]
So, I'm just an amused onlooker from reddit and not really a javascript developer myself, but like:

 The guy fully yanked another large javascript package 3 days ago (https://www.reddit.com/r/javascript/comments/rwdu3h/fakerjs_gets_erased/), posted an incoherent rant about the update color.js update that caused this and removed all the other maintainer's access from npm (https://github.com/Marak/colors.js/issues/285) and was recently made homeless after accidentally firebombing his own apartment (https://abc7ny.com/suspicious-package-queens-astoria-fire/6425363/, https://twitter.com/marak/status/1320465599319990272). Accordingly, there's pretty healthy chance that color.js in its current incarnation is permanently offline.

If color.js is a "a deeply nested dependency" for webpack, then surely this constitutes a webpack issue and not a color.js issue at this point..?

**Comment by DanielRuf** [comment]
> If color.js is a "a deeply nested dependency" for webpack, then surely this constitutes a webpack issue and not a color.js issue at this point..?

A problem of the library which uses `colors`, can be checked with `npm ls colors`.

**Comment by DanielRuf** [comment]
I have tried `npm i webpack && npm ls colors` but this returns nothing. The installed webpack version is 5.65.0.

In the npm / JS world the package which directly uses `colors` has to pin the version since any tricks with `resolutions` and patches does not work for globally installed packages like the webpack CLI package.

**Comment by DanielRuf** [comment]
I have copied the given package.json file to a new GitHub Codespaces instance, did `npm i && npm ls colors` and got this:

```
npm ls colors
frmlibs@1.0.0
└─┬ favicons@6.2.2
  └── colors@1.4.1
```

Please contact the maintainer of the favicons package:
https://www.npmjs.com/package/favicons?activeTab=dependencies
https://github.com/itgalaxy/favicons/blob/master/package.json#L44

So this is clearly not part of webpacks own dependency tree.

**Comment by DanielRuf** [comment]
You can use this issue: https://github.com/itgalaxy/favicons/issues/370
