### ISSUE TITLE
Typing error for dev server

### ISSUE THREAD

**Issue by IvanSavoskin** [webpack/webpack#15131]
When I try to set the configuration for webpack-dev-server, I get an error
```Object literal may only specify known properties, and 'devServer' does not exist in type 'Configuration'.```

```ts
const devOptions: Configuration = {
        devServer: {
            static: {
                directory: PATHS.dist
            },
            port: 8888,
            client: {
                overlay: {
                    warnings: false,
                    errors: true
                }
            },
            open: true,
            hot: true,
            historyApiFallback: true,
            server: "https"
        }
    };
```

**Other relevant information:**
webpack version:  5.65.0
webpack-dev-server version: 4.7.2
typescript version: 4.5.4
Node.js version: 14.17.0
Operating System: macOS 12.1

**Comment by alexander-akait** [comment]
Answer https://github.com/webpack/webpack/discussions/15076#discussioncomment-1887720

**Comment by IvanSavoskin** [comment]
It's a shame it works like that now, as it breaks the normal webpack-merge operation

**Comment by alexander-akait** [comment]
Shame? Don't be toxic, what is the problem with `webpack-merge`?

**Comment by IvanSavoskin** [comment]
Sorry, I used a little incorrect word.  I wanted to write "very sad".
The problem with webpack-merge is that it requires the Configuration type from the webpack package as input, and the dev-server field is missing from it.

**Comment by IvanSavoskin** [comment]
Earlier I had done something like this
```ts
import webpack, { Configuration } from "webpack";
import { merge } from "webpack-merge";

const isProduction = process.env.NODE_ENV === "production";

module.exports = () => {
  const devOptions: Configuration = {
          static: {
              directory: PATHS.dist
          },
          port: 8888,
          client: {
              overlay: {
                  warnings: false,
                  errors: true
              }
          },
          open: true,
          hot: true,
          historyApiFallback: true,
          server: "https"
      };
  
      const config: Configuration = {
          target: "web",
          resolve: {
              ...
          },
          output: {
             ...
          },
      };
  
      return isProduction ? config : merge(config, devOptions);;
}
```

Now this option no longer works.

**Comment by alexander-akait** [comment]
You can use `type ConfigurationAndDevServer = Configuration & { devServer: DevServerConfiguration };`, in future webpack-dev-server will be just plugin, so the `devServer` option will not exists

**Comment by IvanSavoskin** [comment]
Got it, then you have to change the current behavior. Thank you
