### ISSUE TITLE
Use of dynamic imports w/ expressions + ContextReplacementPlugin makes builds non-reproducible / project location dependant

### ISSUE THREAD

**Issue by ziir** [webpack/webpack#15140]
# Bug report

**What is the current behavior?**

When using dynamic imports with expressions together with `ContextReplacementPlugin` in order to limit the possible file matches, some module ids which should deterministic, are actually dependent on the project's location.
Meaning two identical projects (code, dependencies, configuration etc..) built on the same machine have different build outputs based on their location on the filesystem.

**If the current behavior is a bug, please provide the steps to reproduce.**

- use dynamic imports with expessions
  - ie: **import(`../i18n/${locale}.json`)**)
- configure Webpack to use `ContextReplacementPlugin` to limit which JSON files should be bundled
  - ie: `new webpack.ContextReplacementPlugin(/i18n/, regExpForLocales)`
- build the project for production
- duplicate the project at another location on the filesystem at a different path root level
  - ie: `/home/project` vs `/home/work/projects`
- build the project for production at the new location
- diff both output bundles, observe that both bundles are different, invalidating the project build's reproducibility 

```bash
$ diff -u context-a/dist/main.js folder-b/context-b/dist/main.js
```
```diff
--- context-a/dist/main.js	2022-01-10 14:52:49.395750091 +0100
+++ folder-b/context-b/dist/main.js	2022-01-10 14:52:52.143773687 +0100
@@ -4,7 +4,7 @@
     t,
     o,
     n = {
-      595: (e, r, t) => {
+      174: (e, r, t) => {
         var o = { "./a.json": [359, 359], "./b.json": [376, 376] };
         function n(e) {
           if (!t.o(o, e))
@@ -16,7 +16,7 @@
             n = r[0];
           return t.e(r[1]).then(() => t.t(n, 19));
         }
-        (n.keys = () => Object.keys(o)), (n.id = 595), (e.exports = n);
+        (n.keys = () => Object.keys(o)), (n.id = 174), (e.exports = n);
       },
     },
     i = {};

```

[Minimal reproduction repository](https://github.com/ziir/webpack-repro-dynamic-import-context-replacement-deterministic-module-id)

**What is the expected behavior?**

- both bundles should be identical irrelevant of their location on the filesystem

**Other relevant information:**
webpack version:  *5.65.0*
Node.js version:  *14.18.1*
Operating System: *Linux Ubuntu 20.04.3 LTS*
Additional tools: *N/A*

**Comment by alexander-akait** [comment]
Can you provide your configuration file?

**Comment by ziir** [comment]
Hi @alexander-akait, updated the issue's description with a link to the [minimal reproduction repository](https://github.com/ziir/webpack-repro-dynamic-import-context-replacement-deterministic-module-id) containing [the configuration file](https://github.com/ziir/webpack-repro-dynamic-import-context-replacement-deterministic-module-id/blob/main/context-a/webpack.config.js)

**Comment by markjm** [comment]
I believe the issue presents specifically when the regex of `ContextReplacementPlugin` contains `|` characters.

When hashing modules (in `DeterministicModuleIdsPlugin`), we make calls to `IDHelpers.getFullModuleName` -> `makePathsRelative` -> `_makePathsRelative`. Here, the identifier is split on `|` and `!` characters, then passed to `absoluteToRequest`.

While `absoluteToRequest` handles regex's in identifiers, the splitting in `_makePathsRelative` splits up the regex in the identifier to look like 2 seperate "pieces", which `absoluteToRequest` will then attempt to `path.relative`-ize
