### ISSUE TITLE
With output.environment.module, packaged dependency gets incorrect reference to external dependency

### ISSUE THREAD

**Issue by MustafaHaddara** [webpack/webpack#15143]
# Bug report

**What is the current behavior?**
I'm building a react component library, so I declare react and react-dom as `externals`. I'm using webpack to build our library as a module, with `experiments.outputModule = true`, `output.environment.module = true`, and `output.library.type = 'module'`.

I'm using a library that also declares `react` as an external dependency.

When I do my build:

- In the compiled code, we end up getting a reference to `react` as `external_react_`
- my code's calls to `React.createContext` get compiled correctly as `external_react_.createContext()`
- my dependency's calls to `React.createContext` get compiled **incorrectly** as `external_react_["default"].createContext()`

This results in a hard crash in consumers of my library, because `external_react_["default"]` is `undefined` and then `external_react_["default"].createContext()` throws.

**If the current behavior is a bug, please provide the steps to reproduce.**

reproduction case: https://github.com/MustafaHaddara/webpack-external-repro-case

**What is the expected behavior?**

My dependency's calls to `React.createContext` should get compiled as `external_react_.createContext()`

**Other relevant information:**
webpack version:  5.65.0
Node.js version: 14.16.0, also reproduced with 16.7.0
Operating System: 
Additional tools:

**Comment by alexander-akait** [comment]
But I don't see any problems, put `console.log(external_react_["default"])` and look at output, all works fine...

**Comment by MustafaHaddara** [comment]
How did you import it? I realized I got the `main` and `module` keys wrong in my `package.json` in my repro case so you might have been importing the root `index.js`, I've updated my reproduction case now. 

I say this because when I import my component into a create-react-app project, I get this crash:
```
warning.js:62 Uncaught TypeError: __webpack_require__.r is not a function
    at Object../node_modules/webpack-external-repro-case/es/index.js (warning.js:62)
```

When I switch `optimization.minimize` to `true`, I get the initial error I reported:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'createContext')
    at index.js:2
    at Module../node_modules/webpack-external-repro-case/es/index.js (index.js:2)
    at __webpack_require__ (bootstrap:856)
    at fn (bootstrap:150)
    at Module.<anonymous> (index.module.css?438e:82)
```

(this suggests to me that I should be reporting a second bug related to disabling minification?)

---

Your first example seems to work for me, though. I can't tell from the docs, what are the drawbacks of mixing CJS with ESM? 
Does it boil down to these chunks being different in the output? 

module:
```
import * as __WEBPACK_EXTERNAL_MODULE_react__ from "react";
// truncated

/***/ 810:
/***/ ((module) => {

var x = y => { var x = {}; __webpack_require__.d(x, y); return x; }
var y = x => () => x
module.exports = __WEBPACK_EXTERNAL_MODULE_react__;

/***/ })
```

vs. commonjs:

```
/***/ 556:
/***/ ((module) => {

module.exports = require("react");

/***/ })
```

**Comment by alexander-akait** [comment]
> How did you import it? I realized I got the main and module keys wrong in my package.json in my repro case so you might have been importing the root index.js, I've updated my reproduction case now.

I tested it using https://github.com/MustafaHaddara/webpack-external-repro-case/blob/main/es/index.js, just run this in browser or using `Node.js` (document will be undefined)

What is webpack version in CRA? Please run `npm ls webpack`

**Comment by MustafaHaddara** [comment]
CRA is using `webpack@4.44.2` via `react-scripts@4.0.3`

**Comment by alexander-akait** [comment]
There is the problem, webpack v4 doesn't fully support ESM, you need to update CRA and use webpack v5

**Comment by MustafaHaddara** [comment]
If I can't currently update CRA, is there a config option to teach webpack v4 to not use ESM and import CJS instead? My actual package ships both ESM and CJS builds. Or is that a bad idea?

Also, do you want another bug report about the minification or is that another known Webpack v4 bug?

**Comment by alexander-akait** [comment]
> If I can't currently update CRA, is there a config option to teach webpack v4 to not use ESM and import CJS instead? My actual package ships both ESM and CJS builds. Or is that a bad idea?

CRA doesn't provide ability to change options, so I think there is only one solution - only commonjs, not it is not bad idea, but in future make sense to use only ESM

> Also, do you want another bug report about the minification or is that another known Webpack v4 bug?

Probably yes, webpack v4 is real old and contains old version of terser

**Comment by MustafaHaddara** [comment]
ok, that makes sense. 

thanks for your help!
