### ISSUE TITLE
TS Error: class Dependency's type & category property

### ISSUE THREAD

**Issue by Chen-jj** [webpack/webpack#15150]
# Bug report

**What is the current behavior?**

TS Error 2611.

```ts
import { dependencies } from 'webpack'

class AMDRequireItemDependency extends dependencies.ModuleDependency {
  constructor (request, range) {
    super(request)
    this.range = range
  }

  // TS Error 2611
  get type () {
    return 'amd require'
  }

  // TS Error 2611
  get category () {
    return 'amd'
  }
}
```

**If the current behavior is a bug, please provide the steps to reproduce.**

No TS Error.

https://github.com/webpack/webpack/blob/753fdea847fafe2f1a7e1cb2324e5f7cafa63c83/types.d.ts?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L2588

```ts
declare class Dependency {
  readonly type: string;
  readonly category: string;
  // Should type & category turn into getter instead of readonly?
  get type (): string;
  get category(): string;
}

```

**What is the expected behavior?**

**Other relevant information:**
webpack version:  5.65.0
Node.js version: 
Operating System: 
Additional tools:
TS latest

**Comment by sokra** [comment]
> ```ts
> Should type & category turn into getter instead of readonly?
> ```

yes, that seem to work
