### ISSUE TITLE
CRA's HMR doesn't work

### ISSUE THREAD

**Issue by TianYu0605** [webpack/webpack#15152]
# Bug report

**What is the current behavior?**
When I use Module Federation, CRA's HMR doesn't work, maybe why?

**If the current behavior is a bug, please provide the steps to reproduce.**
Use CRA*4 create a project, then update webpack to version 5, now HMR is working. when i use Module Federation, HMR doesn't work

**What is the expected behavior?**
HMR can be used normally

**Other relevant information:**
webpack version:  5.64.1
Node.js version: 16.13.0
Operating System: mac OS
Additional tools: CRA  v4

**Comment by alexander-akait** [comment]
Please open an issue in CRA
