### ISSUE TITLE
Watch option doesn't update fonts hashes

### ISSUE THREAD

**Issue by AlexKovalevych** [webpack/webpack#1516]
Having such config:

```
    ...
    output: {
        path: path.join(distPath, '[hash]'),
        filename: "[name].[hash].js"
    },
    ...
```

where `distPath` is `var distPath = path.resolve(__dirname, 'web/static/dist');` 

and some code which cleans previous builds (it removes all directories in the `web/static/dist` except the current hash directory) after build is complete.

I'm running it this way:

```
node_modules/.bin/webpack --watch --inline --progress --colors
```

I use a font-awesome library which includes some fonts (ttf, svg, etc.) inside this way:

``` less
  src: url('@{fa-font-path}/fontawesome-webfont.eot?v=@{fa-version}');
```

During the very first run - everything works fine and fonts are created in the `web/static/dist/[hash]` directory but after i change the code - it recreates all js files with a new hash, but without fonts. In result i don't have any fonts with a new hash. I guess it happens because fonts are not directly defined in the `entry` block but imported inside a library.

Could you please advice me a good solution here? Is there a way to force webpack recreate all files with a new hash even if they are not directly defined in the `entry` block but imported from the vendor library?

**Comment by Phoenixmatrix** [comment]
The fonts aren't changing though, so they won't have a new hash. That's normal.

**Comment by sokra** [comment]
Propably a bug, but it better to not use `[hash]` in `path`. Use `[hash]` in path will invalidate caching for all assets for every build (`[hash]` changes with every build). But fonts are not changed and could be cached longer. Remove `[hash]` from path.

This is a better config:

``` js
    output: {
        path: distPath,
        filename: "[hash]/[name].js",
        chunkFilename: "[hash]/[id].js"
    },
```

Or even:


``` js
    output: {
        path: distPath,
        filename: "[name].[chunkhash].js",
        chunkFilename: "[id].[chunkhash].js"
    },
```

**Comment by AlexKovalevych** [comment]
@sokra Ok, but what is a good practice to clean up obsolete assets if all of them are in the same directory?

**Comment by sokra** [comment]
If the new version of your app doesn't include an asset this doesn't mean it's now obsolete. Users can keep browser windows open for weeks and deleting assets from server can give 404s for them.

Better wait a few weeks after publishing a new version before deleting old assets. Last modified time is a good hint. I think webpack rewrites assets (and timestamp) on every fresh build.

**Comment by davidfraser** [comment]
For reference: I had exactly this issue, where using a `[hash]` in the output path meant that assets like fonts weren't being loaded when running webpack in `--watch`. I solved it by moving the fonts specifically into a different directory by specifying a sibling directory to the hash path in the loader rules:
```js
test: /\.(ttf|eot)(\?..., loader: "file-loader?outputPath=../fonts/&publicPath=../fonts/"
```

Since we already configured the name of the font files to include a hash, they don't need to be included in the hashed path - but this allows us to still include the hash in the path for other assets.
