### ISSUE TITLE
Webpack 5 and Module Fed.: Duplication of lib code when using multiple named entry points and eager: true

### ISSUE THREAD

**Issue by manfredsteyer** [webpack/webpack#15164]
# Bug report

When having several named entry points and sharing a lib with ``eager:true``, the lib code is duplicated to all resulting bundles.

Example for entry points:

```javascript
  entry: {
    main: "./shell/main", 
    styles: "./shell/styles.css",
    polyfills: "./shell/polyfills"
  },
```

Example for shared:

```javascript
      shared: {
        "rxjs": {
          eager: true,
          singleton: true,
        },
      }
```

**What is the current behavior?**

The shared lib is duplicated to all bundles (main and polyfills in the example shown).

**What is the expected behavior?**

The shared lib should not be duplicated but only put into one bundle

**Other relevant information:**
webpack version:  Every version since webpack 5
Node.js version: 16.13.2 LTS
Operating System: windows
Additional tools: no

**Comment by manfredsteyer** [comment]
One can reproduce this issue with this repo here:
https://github.com/manfredsteyer/federation-demo

Use the file ``webpack.shell.config.js`` and build the app with ``npm run build:shell``.

As mentioned, this happens with all versions since webpack 5.

**Comment by alexander-akait** [comment]
I think it is expected, because you use multi entry mode

**Comment by sokra** [comment]
`splitChunks.chunks: "all"` can also help

**Comment by manfredsteyer** [comment]
Thanks for this hint, @sokra. I've tried this:

```
  optimization: {
    splitChunks: {
      chunks: 'all'
    }
  },
```

Even though I've used ``eager:true``, this setting made webpack to put each shared lib into a bundle of its own like when ``eager`` is ``false``.

**Comment by manfredsteyer** [comment]
The ``dependOn`` solutions seem to work well.

If you have any idea for making it work with optimization.xyz, that would be awesome b/c it seems to be a bit less obstrusive.

**Comment by alexander-akait** [comment]
I am afraid it is limitation, I think we need to document it

**Comment by manfredsteyer** [comment]
As discussed with @alexander-akait, I'm putting this further issue we are running into with ``eager:true`` here:




If we share libs via the host using ``eager:true`` but don't use them, they are removed. Hence, they need to be loaded alongside the first remote that needs them. As we are speaking about quite a lot libs, this is dramatically slowing down the application.

@alexander-akait already mentioned in another thread that this is very like a limitation. Perhaps we find a way to work aroud it.

**Comment by sokra** [comment]
yeah, that's our eager work. It will always load them, but it's only known at runtime if they are needed.
eager is an option for some rare edge cases. You usually don't want to use it.

**Comment by duyphuong2101** [comment]
Currently, I use module-federation (MF) v7.0.8 and share lib for other slides, it does not duplicate, but I upgraded to version 8.2.2 above, and the duplicate problem will return:

My shared:
`
```javascript
shared: {
        '@t1rearc-ui-base/component': {
          singleton: true,
          requiredVersion: dependencies['@t1rearc-ui-base/component'],
        },
        '@t1rearc-ui-base/core': {
          singleton: true,
          eager: true,
          requiredVersion: dependencies['@t1rearc-ui-base/core'],
        },
        './services/event': {
          singleton: true,
          eager: true,
          requiredVersion: false,
        },
        zustand: {
          singleton: true,
          requiredVersion: dependencies['zustand'],
        },
      },
    };
``` `
![image](https://github.com/webpack/webpack/assets/5600270/8db1773e-9a8f-4610-8204-71cc1f700aa2)

I logged an issue: https://github.com/module-federation/module-federation-examples/issues/3776

**Comment by dfeunjee** [comment]
Dooray! Failure Notice



  
  
    
    
  
  
    
        Failure Notice
    
  
  
    
        
        Your message sent to
          
***@***.***
          has failed to be delivered.
        
        
          Please refer to the below for details.
        
    
  
  
    
      
        
          
            * Recipient : 
***@***.***
          
          
            * Sent time : 
2024-03-28T20:07:04
          
          
            * Subject : 
Re: [webpack/webpack] Webpack 5 and Module Fed.: Duplication of lib code when using multiple named entry points and eager: true (Issue #15164)
          
          
            
              
                * Remote host said : 
              
              
                
대외비/기밀 메일은 외부 계정으로 발송이 제한되어 일부 메일 발송 실패(수신자가 전달 설정한 경우 포함)
                
              
            
                      
          
        
      
    
  
  
    
        
          This message was sent from a notification-only address that cannot accept incoming email.
          For more information, please contact           ***@***.***
        
    
  
  
    
        © Dooray!.
