### ISSUE TITLE
Webpack 5 Module Federation: eager:true with unused lib

### ISSUE THREAD

**Issue by manfredsteyer** [webpack/webpack#15169]
# Bug report

If we share libs via the host using ``eager:true`` but don't use them, they are removed. Hence, they need to be loaded alongside the first remote that needs them. As we are speaking about quite a lot libs, this is dramatically slowing down the application.

**What is the current behavior?**
**If the current behavior is a bug, please provide the steps to reproduce.**

If we use ``eager:true`` but don't use the respective lib, it's removed

**What is the expected behavior?**

The lib should be put into the bundle because it might be needed by a remote. This is the reason why we configured it with ``eager:true``.

**Other relevant information:**
webpack version:  all versions since 5
Node.js version: 16.13.2
Operating System: windows
Additional tools: none

**Comment by alexander-akait** [comment]
Please report about it here https://github.com/webpack/webpack/issues/15164, the problem in one place, but it is not problem, it is limitations

**Comment by manfredsteyer** [comment]
IMHO, they are two different however related issues. As suggested, I've added it to the mentioned issue.
