### ISSUE TITLE
Duplicate modules are found in both entrypoint chunks and async chunks

### ISSUE THREAD

**Issue by Mensu** [webpack/webpack#15173]
# Bug report

**What is the current behavior?**
Under certain circumstances, modules in entrypoint chunks will be bundled into other async chunks.

**If the current behavior is a bug, please provide the steps to reproduce.**
Here is the reproducible test repo: https://github.com/Mensu/webpack-reproduce-issue-15173

To reproduce the issue, simply run `npm install` and `npm run build`. After the build is finished, search for `"moduleAB"` in the `dist` folder, and find out module `src/moduleAB.js` was bundled into chunk `dist/entryA.js`, chunk `dist/entryB.js` (entrypoint chunks, which is expected) and chunk `dist/commonAsync.js` (async chunks, which is unexpected)

Module `src/moduleAB.js` is statically imported by entrypoint modules `src/entryA.js` and `src/entryB.js`, therefore is available in entrypoint chunks `dist/entryA.js` and `dist/entryB.js`. Since `dist/commonAsync.js` is an async chunk, the factory of module `src/moduleAB.js` must have been available in the entrypoint chunks when we are to load `dist/commonAsync.js`, therefore it seems unnecessary to duplicately bundle `src/moduleAB.js` into `dist/commonAsync.js`.

**What is the expected behavior?**
Module `src/moduleAB.js` was only bundled into entrypoint chunks `dist/entryA.js` and `dist/entryB.js`, not into `dist/commonAsync.js`.

I kind of believe the problem lies here `availableModules.has(module) || availableModules.plus.has(m)`
https://github.com/webpack/webpack/blob/v5.66.0/lib/buildChunkGraph.js#L906-L909

The first condition checks whether `availableModules` has `module`, but when it comes to the second condition, it checks whether `availableModules.plus` has `m` instead of `module`, which is inconsistent with the first condition. I'm not sure whether checking against `m` is intended for some reason I'm missing, or it's just a typo. Changing the condition to `availableModules.plus.has(module)` may fix this issue, but I don't know whether the change will break other codes or not.

**Other relevant information:**
webpack version:  5.66.0
Node.js version: 12.10.0
Operating System: Mac OS
Additional tools: N/A

**Comment by alexander-akait** [comment]
You can set:
```
optimization: {
    splitChunks: {
      chunks: 'all',
      minSize: 0,
    }
  }
```

And they will be moved to own chunk

**Comment by Mensu** [comment]
> You can set:
> 
> ```
> optimization: {
>     splitChunks: {
>       chunks: 'all',
>       minSize: 0,
>     }
>   }
> ```
> 
> And they will be moved to own chunk

@alexander-akait Thanks for your suggestion, but in my real project, there are many modules duplicately bundled in the way described in the OP. Applying the suggestion results in so many small chunks, one for each of the duplicate modules, which seems unnecessary to me.

I think it's natural to bundle the duplicate modules only into the entrypoint chunks when the modules are imported by modules of both entrypoint chunks and async chunks, as webpack has already achieved this in most of the cases (For example in the OP, webpack wouldn't duplicately bundle module `src/moduleAB.js` into `dist/featureA.js`, whereas `dist/featureA.js` imports `src/moduleAB.js`. I take it that webpack knows `src/moduleAB.js` is already available in the entrypoint chunk `dist/entryA.js`, so it's unnecessary to bundle `src/moduleAB.js` again into `dist/featureA.js`)

**Comment by alexander-akait** [comment]
Not in all cases, that is why we provide `splitChunks` option, where you can setup necessary behavior, yes, sometimes it is not easy to setup, but we can't provide the best output for all

**Comment by Mensu** [comment]
> Not in all cases, that is why we provide `splitChunks` option, where you can setup necessary behavior, yes, sometimes it is not easy to setup, but we can't provide the best output for all

@alexander-akait I agree that you can't provide the best output for all cases, but I think it's possible for this case.

Looking around the codes after `availableModules.plus.has(m)`
https://github.com/webpack/webpack/blob/v5.66.0/lib/buildChunkGraph.js#L906-L909

I find that other codes in similar logics are like `availableModules.plus.has(module)`, not checking agains `m`
https://github.com/webpack/webpack/blob/v5.66.0/lib/buildChunkGraph.js#L1006-L1009
https://github.com/webpack/webpack/blob/v5.66.0/lib/buildChunkGraph.js#L1060-L1063

Considering that changing `m` to `module` would fix this case, I'm so curious about the inconsistence.  @sokra might have some context for this inconsistence?
