### ISSUE TITLE
concatenateModules produces suboptimal ES6-modules output

### ISSUE THREAD

**Issue by dilyanpalauzov** [webpack/webpack#15176]
I use webpack 5.66.0 with
```javascript
export default {
    experiments: {
        outputModule: true
    },
    optimization: {
        concatenateModules: true
    },
    output: {
        library: {
            type: 'module'
        },
    }
}
```
The output contains, apart from the concatenated source files:
```javascript
/******/ // The require scope
/******/ var __webpack_require__ = {};
/******/ 
/************************************************************************/
/******/ /* webpack/runtime/define property getters */
/******/ (() => {
/******/        // define getter functions for harmony exports
/******/        __webpack_require__.d = (exports, definition) => {
/******/                for(var key in definition) {
/******/                        if(__webpack_require__.o(definition, key) && !__webpack_require__.o(exports, key)) {
/******/                                Object.defineProperty(exports, key, { enumerable: true, get: definition[key] });
/******/                        }
/******/                }
/******/        };
/******/ })();
/******/ 
/******/ /* webpack/runtime/hasOwnProperty shorthand */
/******/ (() => {
/******/        __webpack_require__.o = (obj, prop) => (Object.prototype.hasOwnProperty.call(obj, prop))
/******/ })();
/******/ 
/************************************************************************/
var __webpack_exports__ = {};

// EXPORTS
__webpack_require__.d(__webpack_exports__, {
  "Z": () => (/* binding */ src)
});

/* harmony default export */ const src = (some_variable_name);

var __webpack_exports__default = __webpack_exports__.Z;
export { __webpack_exports__default as default };
```
In this particular case, webpack shall generate just `export default some_variable_name;` and skip the rest.  The current output is suboptimal.

Moreover to save space, the two IIFE at the beginning can be squashed into a single IIFE.

**Comment by alexander-akait** [comment]
They are merged in production mode

**Comment by dilyanpalauzov** [comment]
I do call `webpack --mode production`, it does not change anything.

Moreover I do not see why shall this depend on `mode`.  With webpack I create intermediary packages, which are then used by different packages.  The intermediary packages shall not be compressed/minified/stripped, but at the same time shall not emit useless code.

That said, neither does production-mode lead in the particular case to less emitted code, nor does it make sense to reduce the code only in production mode.

**Comment by alexander-akait** [comment]
Sorry, that's how it was originally designed, minificator should remove unused items, you can setup terser do not remove spaces and remove/simplify only necessary things, if you want to avoid webpack bootstrap code we have https://github.com/webpack/webpack/issues/11382

**Comment by dilyanpalauzov** [comment]
I want to avoid emitting the code, which is mentioned in the ticket.  I have not tried, but I do not think that terser can remove that code.  The almost dead code code shall not be emitted in first place, irrespective of the webpack options.

https://github.com/webpack/webpack/issues/11382 is for a similar, but not identical use case.

**Comment by alexander-akait** [comment]
Sorry, right now we can't implement this, your problem is part of https://github.com/webpack/webpack/issues/11382 and should be done together
