### ISSUE TITLE
Enable to pass output without wrapping

### ISSUE THREAD

**Issue by tsapko3628** [webpack/webpack#15189]
## Feature request

**What is the expected behavior?**
When building esm modules, where is no way to build them fully natively. Webpack generate code with static imports of dependencies, but also wrap them and source in its own modules which use __webpack_require__ instead of real imports.

**What is motivation or use case for adding/changing the behavior?**
I wanted to build node application. I used tsc but I need to have some transformations with ts code (I am going to write loader for them). I use nodejs 16 and esm modules and want to see esm imports in output. So, I had them with tsc and partially have them with Webpack. Also I need this for my web app where I want to build sources (from ts with assets) to esm output.

Additional problem is that I can't build code without bundling, that I want to do for esm.

**How should this be implemented in your opinion?**
I wanted to options for:
* disable bundling (for esm only or not): I want to see dist folder like after tsc but with assets and loader transformations.
* disable wrapping in __webpack_require__ for esm modules

Both of this points are because this manipulation are not needed for esm modules at all and brake all import/export idea.

**Are you willing to work on this yourself?**
no, sorry.

**Comment by tsapko3628** [comment]
for example. this is output (imports not bundled by config):
```js
import *as r from './external';
import *as e from './main.module';

var t, a, o, n, p, i = {
  908: (r, e, t) => {
    t.a(
      r,
      (
        async r => {
          var e = t(665), a = t(966);
          await e.CliApplication.run(a.MainModule), r();
        }
      ),
      1,
    );
  }, 665: (e, t, a) => {
    var o, n;
    e.exports = (
      o = { CliApplication: () => r.CliApplication }, n = {}, a.d(n, o), n
    );
  }, 966: (r, t, a) => {
    var o, n;
    r.exports = (
      o = { MainModule: () => e.MainModule }, n = {}, a.d(n, o), n
    );
  },
}, l = {};

function c(r) {
  var e = l[r];
  if (void 0 !== e) {
    return e.exports;
  }
  var t = l[r] = { exports: {} };
  return i[r](t, t.exports, c), t.exports;
}

t = 'function' == typeof Symbol ? Symbol('webpack then') : '__webpack_then__', a = 'function' == typeof Symbol ? Symbol(
  'webpack exports') : '__webpack_exports__', o = r => {
  r &&
  (
    r.forEach((
      r => r.r--
    )), r.forEach((
      r => r.r-- ? r.r++ : r()
    ))
  );
}, n = r => !--r.r && r(), p = (r, e) => r ? r.push(e) : n(e), c.a = (r, e, i) => {
  var l,
    c,
    u,
    f = i && [],
    s = r.exports,
    m = !0,
    v = !1,
    b = (r, e, a) => {
      v ||
      (
        v = !0, e.r += r.length, r.map((
          (r, o) => r[t](e, a)
        )), v = !1
      );
    },
    h = new Promise((
      (r, e) => {
        u = e, c = () => (
          r(s), o(f), f = 0
        );
      }
    ));
  h[a] = s, h[t] = (r, e) => {
    if (m) {
      return n(r);
    }
    l && b(l, r, e), p(f, r), h.catch(e);
  }, r.exports = h, e((
    r => {
      if (!r) {
        return c();
      }
      var e, i;
      l = (
        r => r.map((
          r => {
            if (null !== r && 'object' == typeof r) {
              if (r[t]) {
                return r;
              }
              if (r.then) {
                var e = [];
                r.then((
                  r => {
                    i[a] = r, o(e), e = 0;
                  }
                ));
                var i = {};
                return i[t] = (t, a) => (
                  p(e, t), r.catch(a)
                ), i;
              }
            }
            var l = {};
            return l[t] = r => n(r), l[a] = r, l;
          }
        ))
      )(r);
      var u = new Promise((
        (r, t) => {
          (
            e = () => r(i = l.map((
              r => r[a]
            )))
          ).r = 0, b(l, e, t);
        }
      ));
      return e.r ? u : i;
    }
  ))
    .then(c, u), m = !1;
}, c.d = (r, e) => {
  for (var t in e) {
    c.o(e, t) && !c.o(r, t) && Object.defineProperty(r, t, { enumerable: !0, get: e[t] });
  }
}, c.o = (r, e) => Object.prototype.hasOwnProperty.call(r, e);
var u = c(908);
u = u.default, u = await u;
```
this is an input:
```ts
import { CliApplication } from './external';
import { MainModule } from './main.module';

await CliApplication.run(MainModule);
```

this is an output with tsc:
```js
import { CliApplication } from './external';
import { MainModule } from './main.module';
await CliApplication.run(MainModule);
//# sourceMappingURL=main.js.map
```
I wanted some result like that

**Comment by tsapko3628** [comment]
part of config:
```
mode: 'production',
...
target: ['node', 'es2022'],
...
output: {
  module: true,
  clean: true,
  chunkFormat: 'module',
  libraryTarget: 'module',
  libraryExport: 'default',
},
externalsPresets: { node: true },
experiments: {
  topLevelAwait: true,
  outputModule: true,
},
optimization: {
  minimize: true,
  concatenateModules: false,
},
node: false,
```

**Comment by alexander-akait** [comment]
Duplicate https://github.com/webpack/webpack/issues/11382

**Comment by tsapko3628** [comment]
Is there any known plugins for now or maybe it is possible to write it(I have no experience with writing webpack plugins). Can webpack plug-in do this?

**Comment by alexander-akait** [comment]
Currently no, it is planned

**Comment by tsapko3628** [comment]
Thanks

**Comment by alexander-akait** [comment]
You should use `output.library` to enabled exports output

**Comment by tsapko3628** [comment]
I have `{ library: { type: 'module' } }` and it doesn't work.

It doesn't work only with reexport.

for example:
input: (a.ts)
```
export class A {}
```
output:
```
... (module wrappers)
export { __webpack_exports__A as A };
```

input: (index.ts)
```
export * from './a';
```

output:
```
import * as __A__webpack_module__ from './a';

...some useless wrappers
```
export is missed

**Comment by alexander-akait** [comment]
Can you create minimum reproducible test repo?

**Comment by tsapko3628** [comment]
yep

**Comment by alexander-akait** [comment]
Feel free to ping when it was ready

**Comment by tsapko3628** [comment]
Here is reproduce: https://github.com/tsapko3628/webpack-reexport-repro

**Comment by tsapko3628** [comment]
emitted module (without import wrappings) is:
```
var __webpack_exports__ = {};
// This entry need to be wrapped in an IIFE because it need to be isolated against other modules in the chunk.
(() => {
/* harmony import */ var _some_func__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(953);


})();
```
`_some_func__WEBPACK_IMPORTED_MODULE_0__` doesn't adds into `__webpack_exports__` and there is not `export` statement at the end of file (I suppose it's because of `__webpack_exports__` is empty)

**Comment by tsapko3628** [comment]
so. for fix my initial issue need to add `harmony: boolean` into config.module (like https://webpack.js.org/configuration/module/#module-contexts) to pass it to https://github.com/webpack/webpack/blob/c181294865dca01b28e6e316636fef5f2aad4eb6/lib/dependencies/HarmonyModulesPlugin.js#L102

also need add conditions to some if's statements in just one method. So I have an example and can contribute. It also fixes bug with reexporting

**Comment by alexander-akait** [comment]
But you don't have `export` in `main.ts`, for `some-func.js` you have `export`

**Comment by tsapko3628** [comment]
and as you can see. every file in src uses as entry for split dist like tsc. if use chunks, all external libraries (like node modules) will be imported in entry point

**Comment by tsapko3628** [comment]
So. I found a solution:
```js
class DisableHarmonyPlugin {
	apply(compiler) {
		compiler.hooks.compilation.tap(
			"DisableHarmonyPlugin",
			(compilation, { normalModuleFactory }) => {

				const handler = (parser, parserOptions) => {
					parserOptions.harmony = false;
				};

				normalModuleFactory.hooks.parser
					.for("javascript/auto")
					.tap("HarmonyModulesPlugin", handler);
				normalModuleFactory.hooks.parser
					.for("javascript/esm")
					.tap("HarmonyModulesPlugin", handler);
			}
		);
	}
}
```

This is all I needed for do that I want. one small thing is `var __webpack_exports__ = {};` useless line in each output file.

**Comment by tsapko3628** [comment]
So there is one more thing. I not found the way to emit import() into dist. It's import module statically and then Resolve it like it was loaded dynamically.

**Comment by alexander-akait** [comment]
Because you build app, webpack drops unused exports, you can use multi compiler mode and build some files like library, some like application
