### ISSUE TITLE
Plugin "ChromeExtensionLiveReloadPlugin": append js-code to the chunk.

### ISSUE THREAD

**Issue by Stas404** [webpack/webpack#1520]
Hi. I write plugin "ChromeExtensionLiveReloadPlugin" for autoreloading the extension after files change (webpack watching):
https://github.com/WebDevArchive/Webpack4ChromeExtension/blob/master/utils/webpack/ChromeExtensionLiveReloadPlugin/ChromeExtensionLiveReloadPlugin.js
Is this a correct way to append a code to the chunk (background.js)?

**Comment by sokra** [comment]
You can write a plugin that adds code to the webpack runtime.

I. e. here is how to HMR Plugin adds it's code to the runtime: https://github.com/webpack/webpack/blob/master/lib/HotModuleReplacementPlugin.js#L129-L139

**Comment by stas-webwork** [comment]
Thanks, Sokra. 
Sorry for my English. 
I don't quite understand - can I use mechanism of HotModuleReplacement or not? Will it really reload the chrome extension on the fly? 
My thoughts: 
To reload the extension when the file changes, call Chrome API chrome.runtime.reload() from the background page (background.js). 
Two ways how to tell background.js when to do it: 
1. Make the check (of the file with build-timestamp) via setInterval and XMLHttpRequest. 
2. Sockets (webpack-dev-server?) // overhead in my opinion. 
In my plugin, I just embed [js-code](https://github.com/WebDevArchive/Webpack4ChromeExtension/blob/master/utils/webpack/ChromeExtensionLiveReloadPlugin/reloadExtension.js.hbs) with "chrome.runtime.reload()" to [compilation.assets](https://github.com/WebDevArchive/Webpack4ChromeExtension/blob/master/utils/webpack/ChromeExtensionLiveReloadPlugin/ChromeExtensionLiveReloadPlugin.js#L21-L30). 
And it works well. Do you think this is the wrong way?
