### ISSUE TITLE
Webpack removes parentheses inside Typescript decorators

### ISSUE THREAD

**Issue by etiennenoel** [webpack/webpack#15212]
# Bug report

**What is the current behavior?**
I have created a repository that you can download and reproduce the issue for yourself:  https://github.com/etiennenoel/webpack-or-ts-loader-parentheses-issue

Here's an explanation:

In file `src/greeter.ts`, I have the following class and a decorator that accepts an anonymous function:

```
const test = (condition: any) => {
    return condition;
}

export class Greeter {
    @test((o: { allo: any; target: any; }) => (o.allo && o.target) || (o.allo) )
    name: string;

    constructor(name: string) {
        this.name = name;
    }

    greet(): void {
        console.log(`Hi, ${this.name}!`);
    }
}
```

If you run `npm run build` and look in the generated file `dist/main.bundle.js`, you can see that the parentheses in the condition are removed:

**Expecting to see the following parentheses**
```
...
(o.allo && o.target) || (o.allo)
...
```

**Actual result**
```
...
e.allo&&e.target||e.allo
...
```

I believe it's a bug in webpack or in ts-loader (I'm not sure how to test who's at fault here) since when I run `tsc`, I obtain the proper output:

```
...
(o.allo && o.target) || (o.allo);
...
```

**Other relevant information:**
webpack version:  5.66.0
Node.js version: 14.15.3
Operating System: MacOS
Additional tools:
I'm also using ts-loader so not such who's precisely at fault.

**Comment by alexander-akait** [comment]
Hello, [terser](https://github.com/terser/terser) remove parens around `&&` because `&&` have more precedence than `||` https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence

**Comment by vankop** [comment]
yep, this is [terser](https://github.com/terser/terser) optimization

**Comment by etiennenoel** [comment]
Oh wow, I guess you learn something everyday. I was totally convinced that this wouldn't work. I'll go and learn more about how operators work in Javascript, thanks for the quick response!
