### ISSUE TITLE
Related to execution/es6

### ISSUE THREAD

**Issue by 12sam12** [webpack/webpack#15215]
# Bug report

**What is the current behavior?**
Lets consider the following screenshot:
![image](https://user-images.githubusercontent.com/13358855/149645488-c515f9e1-140c-4843-aea5-d657797b33ab.png)
![image](https://user-images.githubusercontent.com/13358855/149645544-bb32c50e-f7bd-4670-8a32-c01ee4bf8703.png)

Even after the control reaches the let assignment statement, the previous imports are undefined. Could anyone explain why is that so?
Also the following shows that the bundled internal variables are defined though:
![image](https://user-images.githubusercontent.com/13358855/149645560-e0595dfe-bdfc-494d-8a07-f373a2a7095a.png)
![image](https://user-images.githubusercontent.com/13358855/149645562-10f8ed38-7309-48a9-ac18-31c8430e3ff1.png)

Why does this behavior exist in javascript? Is this expected or something different.
Its in mozilla firefox browser (95.0.1)
Its undefined even for npm libraries as well, which is in node_modules folder. Why does this happen, which seems slightly not so logical. Is there any issue with the bundler?

**If the current behavior is a bug, please provide the steps to reproduce.**

   1. Create a react app. Introduce redux in it.
   2. Import that store and provide it in the index.js while rendering the root component.

**What is the expected behavior?**
Just pls explain why is this happening in the browser (firefox 95.0.1) ? Because of this none of the variables imported have any valid values. How to use them in the file post that lines' execution?
Pl give your answer in a more descriptive manner instead of just saying that this behavior is expected. What is exactly this behavior. If this exists how can anyone use any of the imports in the file below? Whats the purpose of importing something you need above, if it will never get imported even after that line is executed?

As far as I know as javascript is a synchronous language except the specific functionalities like promises, async/await, I guess everything else must be synchronous by its design, which is why this unpredictability in its behavior is confusing.

**Other relevant information:**
webpack version: 5.66.0
Node.js version: 16.13.2
Operating System: Linux
Additional tools:

Dummy code repo created : I also created a dummy repo if anyone looks into it at [12sam12/dummy_app](https://github.com/12sam12/dummy_app)

**Comment by vankop** [comment]
this is not an issue in webpack. You probably [using sourcemaps](https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Use_a_source_map),  if you want to see "real" code disable sourcemaps in devtool.

**Comment by 12sam12** [comment]
The question is not about sourcemaps. Its about why the values of the imports used in the unminified or jsx version of files are undefined?? Source maps are nothing and just for the simplicity/conveniency of the debugger. Only when sourcemaps are enabled the client would even be able to view files in this manner and granularity. So already the client is able to view in this manner, which shows that the source maps are enabled.

Then why the following person asked for a test repo in the following discussion??
https://github.com/webpack/webpack/discussions/15180

**Comment by vankop** [comment]
> Its about why the values of the imports used in the unminified or jsx version of files are undefined??

they are `undefined` in console because console executes in current script and in script this variables have different name (because of mangling, minifying ) .

> Source maps are nothing and just for the simplicity/conveniency of the debugger

they map your source code to code in current script ( your first screenshot ).
Names in "real" code could be different from source code ( second screenshot )

**Comment by 12sam12** [comment]
Im actually using firefox only. See basically I just wanna offload all these extra work to these libraries. Thats why I install them. I basically generate a create-react-app. Then I start coding within it and I expect atleast the es6 forms of imports must work fine without doing any further editing to the config of webpack without requiring me to eject this app. Isnt this the normal working behavior?? Why should I worry about sourcemaps?? First of all if I dont edit the webpack config asking it to do some sourcemappings, why will the source have any sort of file with the normal code that was written in the project? First of all even in that unmapped version not the variables in that particular store.js file's imports are not there. I just checked randomly. Those are some other variables.
Could you pls suggest me some edits which would fix the issue without having to modify any config ejecting the app ( to the demo source project in that repo) ?

**Comment by vankop** [comment]
> Could you pls suggest me some edits which would fix the issue without having to modify any config ejecting the app ( to the demo source project in that repo) ?

You should ask/look in create-react-app issues/docs to find a way to disable sourcemaps (set in webpack.config `devtool: false`)

**Comment by 12sam12** [comment]
Infact already the webpack config when app is rejected has the following line in it:

devtool: isEnvProduction
      ? shouldUseSourceMap
        ? "source-map"
        : false
      : isEnvDevelopment && "cheap-module-source-map"

So it already handles sourcemaps. What exactly is the issue. Pls elaborate it somewhere and finish it off sooner.

**Comment by vankop** [comment]
If I understand what you are expect, you should set `devtool` to `false`

**Comment by 12sam12** [comment]
Even if at all the sourcemaps were the issue, then the source code must run without any errors irrespective of what is being shown in the debugger. But infact the redux sagas never get started I suppose and never really catch any of the triggers made in the app. I thought they were happening due to the fact that they were not defined properly.

**Comment by vankop** [comment]
> I thought they were happening due to the fact that they were not defined properly.

thats case very unlikely (otherwise webpack would have a lot of such issues). You should report issue in redux sagas repo.

**Comment by 12sam12** [comment]
See the issue is not just the saga. Its happening for many variables in the redux store.

**Comment by vankop** [comment]
>  But infact the redux sagas never get started I suppose and never really catch any of the triggers made in the app

thats your application code, there is no webpack can do about it. If there is an issue pls report it in redux/redux sagas repo.

> Its happening for many variables in the redux store creation file

Import names are mangled and work correctly (otherwise webpack would have a lot of such issues), errors in console are because "real" names are different (you can set devtool=false or disable source maps in devtool).

**Comment by vankop** [comment]
so your screenshots looks correct to me.. you have disabled sourcemaps => you see only bundle.js without additional information about modules

> If there is an issue in the app code, then there will be some sort of error displayed while running it, as Im calling several methods on those imports in those files

Same stands for webpack, if webpack bundle import wrong/undefined module  you will gain runtime error. I can't help you with your app code..

**Comment by 12sam12** [comment]
Im asking nothing for my app code. Im just asking why the imports were undefined? If at all they were really undefined, then while executing the following lines, they must throw some form of error right? Here in this instance as createStore was undef, the function call must have thrown something. My argument is just that the webpack is not properly showing the values of the app's imported variables, which is one of its intended objectives. This could probably happen only when the sourcemaps work fine I guess.

```
const store = createStore(
    rootReducer,
    persistedState,
    composeEnhancers(applyMiddleware(...middlewares))
);
```
