### ISSUE TITLE
Webpack 5.66.0: "Serializing big strings" warnings

### ISSUE THREAD

**Issue by AprilArcus** [webpack/webpack#15219]
# Bug report

Starting with Webpack 5.66.0, my build began to issue these warnings:

```
<w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (112kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)
<w> [webpack.cache.PackFileCacheStrategy] Serializing big strings (109kiB) impacts deserialization performance (consider using Buffer instead and decode when needed)
```

I bisected the problem to https://github.com/webpack/webpack/commit/8ae9507196d99a52d5ea34192283b42a343c540a, "add support for url() in css". The previous commit (on both master and the [feature/css-modules branch](https://github.com/webpack/webpack/pull/14894), https://github.com/webpack/webpack/commit/77b5589c1a6c8f5ab5583d40c3c38bbbd08236de, does not issue the warning.

[experiments.css](https://webpack.js.org/configuration/experiments/#experimentscss) is not enabled; all CSS is handled by a typical chain of `style-loader@3.3.1`, `css-loader@6.5.1`, `resolve-url-loader@5.0.0`, and `sass-loader@12.4.0`, and the slightly less typical `@teamsupercell/typings-for-css-modules-loader@2.5.1` (all versions latest). Removing the exotic `typings-for-css-modules-loader` did not resolve the issue.

**What is the current behavior?**

Warning regarding serializing large strings is emitted. Warning is unexpected based on webpack commit history and setting, and steps to resolve are unclear.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

If the warning is not legitimate for style-loader, do not emit a warning.
If the warning is legitimate, provide instructions directing the user to the provenance of the oversized string.

**Other relevant information:**
webpack version:  5.66.0
Node.js version: 
Operating System: Linux 
Additional tools:  `style-loader@3.3.1`, `css-loader@6.5.1`, `resolve-url-loader@5.0.0`, `sass-loader@12.4.0`, `@teamsupercell/typings-for-css-modules-loader@2.5.1`

Possibly related to https://github.com/webpack-contrib/mini-css-extract-plugin/issues/643, but note that my build does not use any text extraction plugins

**Comment by sokra** [comment]
Good bisecting work. That commit adds an problematic piece of code. It store the encoded data url of an asset module in the code generation result, which is serialized. For large enough data urls this will trigger the warning now...
