### ISSUE TITLE
Document webpack/hot/only-dev-server entry point

### ISSUE THREAD

**Issue by bjrmatos** [webpack/webpack#1522]
is there any documentation about webpack/hot/only-dev-server entry point? i just know about it because it is used in react-hot-loader.

**Comment by SimenB** [comment]
Somewhat here at least: http://webpack.github.io/docs/hot-module-replacement-with-webpack.html#what-can-i-do-with-it

**Comment by bebraw** [comment]
Closing given this has been documented as pointed out by @SimenB.
