### ISSUE TITLE
Module Federation - add export for all modules available from a remote

### ISSUE THREAD

**Issue by schirrel** [webpack/webpack#15229]
## Feature request

Export all components available on a remote for dynamic import being possible

**What is the expected behavior?**
Alongside with `get`  and `init` the remote scope on `window` have available a list of all the modules exposed so it can be loaded dynamic with some sort of ``modules.forEach(module => import(`remote/${module}`))`` approach.

**What is motivation or use case for adding/changing the behavior?**
I am working on a master thesis project to integrate modules with MF, but our project is a SPA that is required to work offline, needing to cache all modules. I am working on this offline orchstration, so far i've a simple but work implementation as can be seen at this [issue](https://github.com/module-federation/module-federation-examples/issues/1323) on module-federation-examples, a big thanks to @ScriptedAlchemy.
But mine solution required to have a "much described" modules and remotes. I was thinking/planing/willing to do a more dinamic thing.

**How should this be implemented in your opinion?**
I've made a fork of webpack and commited a version of what could work for this on [here](https://github.com/schirrel/webpack/commit/b27f058cf21d84ff64951c5cf94a1ab2e270abd3).
Even tho @ScriptedAlchemy realised that the dynamic string importation may not be work as is wishing (``import(`remote/${module}`)``), he said it on this [tweet](https://twitter.com/ScriptedAlchemy/status/1483964196949618688), having the modules available would at least turn possible to do something like
``await window[myRemoteName].get(`./${module}`);`` whitout having to specify all modules in a json within a project.

**Are you willing to work on this yourself?**
yes

**Comment by schirrel** [comment]
@alexander-akait @vankop @ScriptedAlchemy @sokra DO you guys think i can open a PR based on this branch of mine https://github.com/schirrel/webpack/tree/feature/module-federation-modules-prop-to-import?
Its a simple code but would help a lot on offline orchestrations for Offline PWA.

**Comment by alexander-akait** [comment]
Yes, you can send a PR

**Comment by schirrel** [comment]
thanks @alexander-akait done at #15357
