### ISSUE TITLE
Value `assign-properties` of `output.library.type` not working with `export default class`

### ISSUE THREAD

**Issue by Sir-Will** [webpack/webpack#15228]
# Bug report

**What is the current behavior?**
The library type `assign-properties` uses a loop to assign the exports. This works correctly when an object is exported, but not when a function is exported.

This is what `assign-properties` has created:
```js
/******/ function(__webpack_require__) { // webpackRuntimeModules
/******/ var __webpack_exec__ = function(moduleId) { return __webpack_require__(__webpack_require__.s = moduleId); }
/******/ var __webpack_exports__ = (__webpack_exec__("./javascripts/form-module.js"));
/******/ var __webpack_export_target__ = (ServerList = typeof ServerList === "undefined" ? {} : ServerList);
/******/ var __webpack_exports_export__ = __webpack_exports__["default"];/******/ for(var i in __webpack_exports_export__)  __webpack_export_target__[i] = __webpack_exports_export__[i];
/******/ if(__webpack_exports_export__.__esModule) Object.defineProperty(__webpack_export_target__, "__esModule", { value: true });
/******/ }
```
and `form-module.js` contains the code below:
```js
export default class Form {
  constructor() {
    console.log('Hello World');
  }
}
```
The variable `__webpack_exports_export__` contains the class Form as type `function` and therefore the loop doesn't run and 
 doesn't assign it to the library object.

In a different file I have the export below which results in an object and `assign-properties` working correctly.
```js
export default {
    Core
}
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Handle functions and other types which can't be looped and assign them correctly.

**Other relevant information:**
webpack config:
```js
{
    entry: {
        app: './javascripts/main.js',
        form: {
            dependOn: 'app',
            import: './javascripts/form-module.js',
        }
    },
    mode: 'development',
    devtool: "source-map",
    output: {
        library: {
            name: 'ServerList',
            type: 'assign-properties',
            export: 'default',
        },
        filename: '[name].bundle.min.js'
    },
    module: {
        rules: [
            {
                test: /\.js$/,
                exclude: /node_modules/,
                use: {
                    loader: 'babel-loader'
                }
            }
        ],
    },
}
```
webpack version:  5.66.0
Node.js version: 14.18.3

**Comment by alexander-akait** [comment]
PR welcome

**Comment by sokra** [comment]
It's kind of expected that the assign-properties library type only works for things that have properties. What is the result you expect? Maybe you want to use the `assign` library type instead?

**Comment by Sir-Will** [comment]
@sokra it's the only option which will not overwrite the existing library name, taken from the information in the docs. `assign` would overwrite the main file when an optional module gets loaded.

I expected it to check the type and assign it directly if it's not an object or array.

**Comment by Sir-Will** [comment]
> PR welcome

PR submitted

**Comment by sokra** [comment]
I think you want this?

```
export default Core
```

```
        library: {
            name: ['ServerList', 'Core'],
            type: 'assign',
            export: 'default',
        },
```
