### ISSUE TITLE
Incremental rebuild performance regression in v5.54.0

### ISSUE THREAD

**Issue by mattlewis92** [webpack/webpack#15231]
# Bug report

**What is the current behavior?**
Webpack spends several seconds inside of [`lib/Watching.js`](https://github.com/webpack/webpack/blob/main/lib/Watching.js) after an incremental rebuild:

This profile is from `5.54.0`:
![5 54 0](https://user-images.githubusercontent.com/6425649/150650804-7b6f74a7-0d06-4308-9cf8-d3f77d2dfdae.png)

And I verified it's still an issue in `5.67.0` (as well as a few versions in between):
![5 67 0](https://user-images.githubusercontent.com/6425649/150650806-905b1a99-0d77-4815-a1c5-195c5d401fcb.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
I'm not sure how to reproduce this outside of our app, I think it's only really noticeable by it being a large application. I've included the [profiles](https://github.com/webpack/webpack/files/7919005/profiles.zip) from the debugger, so I hope that's enough to go on? If not let me know if there's anything else I can do to help diagnose the root cause.

**What is the expected behavior?**
Webpack should spend only about a second on this step. This profile is from `5.53.0` (but also seeing the same lower speeds on `5.50.0` and `5.52.1` so I'm confident it's not a fluke)
![5 53 0](https://user-images.githubusercontent.com/6425649/150650813-57c8612d-9a7a-4dd2-9c79-8a00070ffea6.png)

**Other relevant information:**
webpack version:  All versions of webpack from `5.54.0`
Node.js version: v16.13.1
Operating System: MacOS Monterey
Additional tools: This is being run from the angular cli

**Comment by alexander-akait** [comment]
Is it happen before 5.54?

**Comment by mattlewis92** [comment]
> Does this happen before 5.54?

Nope, I tried a few versions to be sure and `5.50.0`, `5.52.1` and `5.53.0` don't have the issue. This chart is from `5.53.0` but it's a similar story on the other earlier versions:
![image](https://user-images.githubusercontent.com/6425649/150777175-c213cc2e-1acc-4973-94f4-8a088eb31c3a.png)

On all versions from `5.54.0` onwards that I tried, I saw the consistently slower times.

**Comment by alexander-akait** [comment]
Very strange because we don't change nothing related to watch in 5.53, maybe something in plugins, can you locally debug?

**Comment by vankop** [comment]
@mattlewis92 Does you use exactly same project/setup ? Is it possible reduce issue to reproducible repo ?

**Comment by mattlewis92** [comment]
> Very strange because we don't change nothing related to watch in 5.53, maybe something in plugins, can you locally debug?

I'll do what I can to debug locally and see if I can work out what's wrong.

> @mattlewis92 Do you use exactly same project/setup ? Is it possible reduce issue to reproducible repo ?

Yep exactly the same each time, all I did between each of those profiles was run `npm i -D webpack@version` and then run an incremental rebuild. I'm not sure how to reproduce it standalone in a repo as our app is enormous, and I suspect the problem is caused by it being a large app, rather than a specific issue within it.

**Comment by gluxon** [comment]
https://github.com/webpack/webpack/pull/15991 may address this partially. I don't know if it'll bring the 7.65s `Watching.js` call back down to 1.02s, but it should be much less.
