### ISSUE TITLE
Module federation: sync load support

### ISSUE THREAD

**Issue by crodriguez-plitzi** [webpack/webpack#15240]
# Bug report

so, i would like to create this ticket to give more visibility to https://github.com/webpack/webpack/issues/11811 and see if we can finally get this fixed

**What is the current behavior?**

crash with error
`Uncaught Error: Shared module is not available for eager consumption: webpack/sharing/consume/default/react/react`

**If the current behavior is a bug, please provide the steps to reproduce.**

this is a repository to reproduce the problem
https://github.com/crodriguez-plitzi/webpack-federation-playground
* yarn
* yarn start (its using lerna)

**What is the expected behavior?**

this should works in sync ways without the requirements of "bootstraps" or lazy imports

**Other relevant information:**
webpack version:  latest (5.67)
Node.js version:  16.13
Operating System: ubuntu/linux
Additional tools:

@ScriptedAlchemy @alexander-akait  @sokra hi, i would like to revive this topic, after few days debugging the whole sharing modules i think we can do some changes to make sync works

basically the main problem is
![Screenshot from 2022-01-24 02-54-24](https://user-images.githubusercontent.com/86263126/150714473-9b8b7a0c-f5f6-476b-9e56-8eafcaae084e.png)

when we do the initial load and we try to load shared dependencies, like react in this example, this is trying to call the next code

`"webpack/sharing/consume/default/react/react": () => (loadSingletonFallback("default", "react", () => (__webpack_require__.e("vendors-node_modules_react_index_js").then(() => (() => (__webpack_require__(/*! react */ "./node_modules/react/index.js"))))))),`

logically this is wrong because, in the initial load we should not wait for the chunk, instead of that, dependencies should be loaded and stored in cache and when this be required by chunks we should be able to read the cache to get the references,

the second things is that this should be considered a cascade imports

![Screenshot from 2022-01-24 03-04-56](https://user-images.githubusercontent.com/86263126/150715649-cec13217-e8ed-4349-a949-2d7a0f58a013.png)

i was trying to fix it but im not very involved in the core of webpack, but after debugging this im thinking that the fix should not be too complicated to make MF be able to work in `sync` mode, and can be optional with props to keep original functionality like is actually,

the reason that MF works async is because primitive dependencies (from node_modules) are already loaded, but this doesnt make sense if from the beginning we dont have access to them, basically the `HOST` must have it loaded but the logic should not require to have `eager` enabled, this can be refactored to works in a better way to support scenarios like

scenario1: HOST1 -----> HOST2 ------> PLUGINS
scenario2: HOST1 -----> PLUGINS

what we should check if in the initial load shared dependencies arent loaded, if thats the case should be loaded

when we works based on shared we should consider that the `HOST` should provide these shared dependencies to keep some armony between dependencies if not the plugin have the "opportunity to load it from his bundle"

the main file where the problem i think is located is this one

`/webpack/lib/sharing/ConsumeSharedRuntimeModule.js`

the main problem is webpack and how he negotiate the shared resources, and thats why im suggesting it, and about versions can be designed in the way that we can store the versions also, and if the shared that is expecting the child MF plugin or the chunk is not there, we can implement a way to continue loading it in the current way getting this from `node_modules`

at high level should be like this
User Story
APP (entry point, chunk1, chunk2) and will load as MF (plugin1)
config = react will be singleton

how webpack should manage this complex scenario in sync way

something like this
![image (53)](https://user-images.githubusercontent.com/86263126/150754303-3857de44-62fe-489f-a426-d4adbf4d7b02.png)

webpack load process and negotiations should be based on tree logic, the first one that loads a shared dependency can be considered the host when this is configured as singleton, and works based on cache, if a MF plugin or chunk or anything else is trying to load a shared library and the version dont match, should load it and store it in the cache and keep the same flow

in any case if u want to use same resource across the whole execution this should keep using `requiredVersion: false` and also, this can solve the problem about run the whole stuff in sync way and finally remove the bootstrap hack way that is being used to make it works

```
But it does present a challenge to start an application if the dependencies are not hoisted and frontloaded asynchronously.

I believe there is a workaround that if you use shareKey and import, and give the object some key other than react, like fakeReact: it won't move out of the graph into another chunk. However you are then in host only mode, similar to eager:true
```
if a shared resource is remote, we can detect it and also we could add new attributes in webpack config to make it explicit,
but to be honest shared singleton shouldnt be remote, for remote we have explicitly `remotes` 

 ```
new ModuleFederationPlugin({
      name: "app1",
      filename: "remoteEntry.js",
      remotes: {
        app2: "app2@http://localhost:3005/remoteEntry.js",
      },
      exposes: {
        "./Button": "./src/Button",
      },
      // sharing code based on the installed version, to allow for multiple vendors with different versions
      shared: [
        {
          react: { singleton: true, requiredVersion: false },
          "react-dom": { singleton: true, requiredVersion: false },
          "react-redux": { singleton: true, requiredVersion: false },
        },
      ],
    })
```

hopefully this makes sense, sadly i still reading webpack to try be able to help, but the logic and negotiations i think is pretty clear

**Comment by alexander-akait** [comment]
@crodriguez-plitzi Please avoid extra pinging, if you have idea how to improve this, feel free to send a PR

**Comment by crodriguez-plitzi** [comment]
i have a high level solution but i dont know on deep webpack to be able to write it, thats why i shared before the information, but i would need someone with experience about webpack source to see if we can make a PR

**Comment by crodriguez-plitzi** [comment]
PR started https://github.com/webpack/webpack/pull/15259
