### ISSUE TITLE
[Question]  NPM link works only when cache is set to `false`

### ISSUE THREAD

**Issue by divyanshu747** [webpack/webpack#15258]
**What I am trying to do** :

I have a shared package as a node module that is added as a dependency in the parent app. During the development of the shared module, in the past, I usually `npm link` the shared module and then `npm link modue-name` in the parent app so I can see my changes right away rather than having to publish it. This speeds up development process as I have webpack watcher running at both ends. Any change the shared module is picked up by the watcher running in the parent app and I can right away see the changes in UI.

Version used : Webpack V4.x.x

**What is the issue** :

However, after updating Webpack to V5 (5.37.0), I noticed that the parent app was able to watch for dependencies and build the files but I was not able to see the changes in UI. I did some research and it seems to be an issue with Webpack caching. After setting the `cache: false` it just worked fine but now the watch takes couple of minutes and is trying to build the entire codebase for a single line change.

**What I need help with**

Is there a cache config I can set where it can watch for "linked modules using npm link" and rebuild quickly just like it does when I make a file change in the parent application?

**Other things I did to get `npm link` working** :

Along with the cache config, I had to also update the watchOptions and remove this `ignored: /node_modules/,`. I know we can use anymatch, regex and `not` ignore specific `node_modules`. 

Thank you!

**Comment by vankop** [comment]
> After setting the cache: false it just worked fine but now the watch takes couple of minutes and is trying to build the entire codebase for a single line change.

Since the rebuild does not use cache anymore it is slow. You should remove your package from `immutablePaths` and `managedPaths` https://webpack.js.org/configuration/other-options/#immutablepaths

**Comment by vankop** [comment]
Could you provide your webpack.config please?
