### ISSUE TITLE
In some cases, webpack is generating source maps that are not consumed by the node with --enable-source-maps flag

### ISSUE THREAD

**Issue by dimitor115** [webpack/webpack#15260]
# Bug report

**What is the current behaviour?**
In some cases, Webpack is generating invalid source maps which cannot be consumed by node in `--enable-source-maps` mode. I've observed that when the project contains for example an [ajv](https://www.npmjs.com/package/ajv) or [mongodb](https://www.npmjs.com/package/mongodb) dependency the nodejs is not able to map stack trace using source maps. 

I believe this is a webpack issue because, when I bundle the same project with for example esbuild the node is working well with generated source maps. 

**If the current behaviour is a bug, please provide the steps to reproduce.**
I've prepared a reproduction repo with two super simple node + webpack setups. One with some standard dependencies like axios and moment where everything works correctly and second with ajv dependency where source maps are not consumed by the node. 

[Reproduction repository](https://github.com/dimitor115/webpack-source-maps-bug-reproduction)

To reproduce yourself:
- Create a simple node project with webpack bundler
- Add ajv dependency
- Create a file with some code that throws an error
- Bundle it using webpack (with `devtool: 'source-map' `option)
- Run with --enable-source-maps flag and see that stack trace is not mapped

**What is the expected behaviour?**

The source maps should be consumed by the node and I should see original files in the stack trace. 

**Other relevant information:**
webpack version:  5.67.0
Node.js version: v12.22.6, v14.18.1, v16.11.1
Operating System: Mac OS 12.0.1
Additional tools:

**Comment by alexander-akait** [comment]
Interesting, I think bug in Node.js, if you try to test `not_working` and `working` in browser (just create html file and script tag), all is fine (in chrome and firefox)

**Comment by dimitor115** [comment]
@alexander-akait should I report this issue to the Node.js team?

**Comment by alexander-akait** [comment]
Make sense :+1:

**Comment by wjddlsy** [comment]
@dimitor115 It's been a long time since you posted this issue, I want to know if you solved this problem. I have trouble with the same issue and struggle to fix it...! 

Please give me some clues for it 😭 Thanks...!

**Comment by dimitor115** [comment]
@wjddlsy Unfortunately I didn't solve it. We just have start using Sentry for error monitoring and there source maps are interpreted properly.
