### ISSUE TITLE
asset module filename does not honor [fullhash]

### ISSUE THREAD

**Issue by sspiff** [webpack/webpack#15269]
# Bug report

**What is the current behavior?**
When "[fullhash]" is included in the filename for an asset/resource, the compilation hash is not substituted into the final build output file name; the file name literally contains the substring "[fullhash]" instead.  By comparison, file-loader does support fullhash substitution in its output file names.

**If the current behavior is a bug, please provide the steps to reproduce.**
In a webpack configuration, specify an assetModuleFilename (or a generator.filename) that includes "[fullhash]".  For example:

```
module.exports = {
  entry: './index.js',
  output: {
    path: path.resolve(__dirname, 'dist/'),
    filename: '[name].[fullhash].js',
    assetModuleFilename: '[name].[fullhash][ext]',
  },
  module: {
    rules: [
      {
        test: /\.asset$/,
        type: 'asset/resource',
      },
      {
        test: /\.assetgen$/,
        type: 'asset/resource',
        generator: { filename: '[name].[fullhash][ext]' },
      },
      {
        test: /\.file$/,
        loader: 'file-loader',
        options: { name: '[name].[fullhash].[ext]' },
      },
    ],
  },
}
```

The build will report, for example:

```
asset bar.39bb7756e74a89205e71.file 0 bytes [emitted] [from: bar.file] (auxiliary name: main)
asset baz.[fullhash].assetgen 0 bytes [emitted] [from: baz.assetgen] (auxiliary name: main)
asset foo.[fullhash].asset 0 bytes [emitted] [from: foo.asset] (auxiliary name: main)
```

**What is the expected behavior?**
The substring "[fullhash]" should be replaced by the compilation hash when naming the build output files:

```
asset bar.39bb7756e74a89205e71.file 0 bytes [emitted] [from: bar.file] (auxiliary name: main)
asset baz.39bb7756e74a89205e71.assetgen 0 bytes [emitted] [from: baz.assetgen] (auxiliary name: main)
asset foo.39bb7756e74a89205e71.asset 0 bytes [emitted] [from: foo.asset] (auxiliary name: main)
```

**Other relevant information:**
webpack version:  5.67.0
Node.js version: 16.13.1
Operating System: macOS 10.15.7
Additional tools: webpack-cli 4.9.2, file-loader 6.2.0

**Comment by alexander-akait** [comment]
`[fullhash]` for `file-loader` is just `[contenthash]`, `[fullhash]` available only `Compilation level` and ideally should be used as directory, i.e. `path: path.resolve(__dirname, 'dist/[fullhash]/')`, we can't calculate full hash when we build modules

**Comment by sspiff** [comment]
Thanks for the clarification!  Actually, I was trying to use `[fullhash]` as a directory similar to what you describe, but had tried to simplify here for illustration.  The output directory structure I'm going for is something like:

```
dist/index.html
dist/[fullhash]/js/index.js
dist/[fullhash]/assets/asset1
dist/serviceWorker.js
```

But, so far I have not been able to get `HtmlWebpackPlugin` or workbox's `InjectManifest` to cooperate.  I will try a different approach.
