### ISSUE TITLE
`webpack.config.ts` ESM support

### ISSUE THREAD

**Issue by tavoyne** [webpack/webpack#15277]
## Feature request

**What is the expected behavior?**

We should be able to import ESM modules inside a `webpack.config.ts` file.

**What is motivation or use case for adding/changing the behavior?**

More and more packages are becoming ESM only. They can't be used right now in a TS configuration file.

**How should this be implemented in your opinion?**

Webpack is loading the configuration through `ts-node`, which [now supports ESM](https://github.com/TypeStrong/ts-node#commonjs-vs-native-ecmascript-modules) via the `ts-node/esm` loader.

**Are you willing to work on this yourself?**
yes

**Comment by alexander-akait** [comment]
We support ESM, in `webpack.config.js`/`webpack.config.ts`, please read https://github.com/webpack/webpack-cli/issues/2458#issuecomment-800377324
