### ISSUE TITLE
webpack sourcemap include absolute path

### ISSUE THREAD

**Issue by xiaoxiangmoe** [webpack/webpack#15274]
# Bug report

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

 https://github.com/xiaoxiangmoe/webpack-source-absolute-path-bug
* `git clone https://github.com/xiaoxiangmoe/webpack-source-absolute-path-bug.git`
* `cd webpack-source-absolute-path-bug`
* `yarn install && yarn build`

see file `src/index.js`

```js
const foo = Math.random() > 0.5 ? "a" : "b";
const m = require(`./foo/${foo}.js`);
console.log(m);
```

see file `dist/main.js.map.json` line 8

```json
{
  "version": 3,
  "file": "main.js",
  "mappings": "...",
  "sources": [
    "webpack:///./src/foo/a.js",
    "webpack:///./src/foo/b.js",
    "webpack:////Users/zhaojinxiang/repos/webpack-sourcemap-bug/src/foo|sync|/^\\.\\/.*\\.js$/",
    "webpack:///webpack/bootstrap",
    "webpack:///webpack/runtime/hasOwnProperty shorthand",
    "webpack:///./src/index.js"
  ],
}
```

You can find a absolute file path in line 8

**What is the expected behavior?**

It should be

```json
{
  "version": 3,
  "file": "main.js",
  "mappings": "...",
  "sources": [
    "webpack:///./src/foo/a.js",
    "webpack:///./src/foo/b.js",
    "webpack:///./src/foo|sync|/^\\.\\/.*\\.js$/",
    "webpack:///webpack/bootstrap",
    "webpack:///webpack/runtime/hasOwnProperty shorthand",
    "webpack:///./src/index.js"
  ],
}
```

**Other relevant information:**
webpack version:  5.67.0
Node.js version: v16.12.0
Operating System: macos 12.1

**Comment by xiaoxiangmoe** [comment]
```
Build at: 2022-01-29T14:12:35.840Z - Hash: bd281d67ec38a4ce - Time: 261ms
```
Another problem is 
* dist/main.js.map.json varies if we build in different dir.
* why stat hash is always `bd281d67ec38a4ce`.

**Comment by alexander-akait** [comment]
Yes, it is bug, we convert absolute paths to relative in source maps, but `/Users/zhaojinxiang/repos/webpack-sourcemap-bug/src/foo|sync|/^\\.\\/.*\\.js$/` is not path and we can't covert it, maybe we can refactor code to use regexp and avoid it, I can provide lines where it happens if you want to fix it

**Comment by xiaoxiangmoe** [comment]
Another problem is: why source maps file don't change stat hash? Is this also bug?

**Comment by xiaoxiangmoe** [comment]
> I can provide lines where it happens if you want to fix it

Can you tell me which line?

**Comment by alexander-akait** [comment]
I think problem somewhere here https://github.com/webpack/webpack/blob/main/lib/SourceMapDevToolPlugin.js#L92

> Another problem is: why source maps file don't change stat hash? Is this also bug?

What hash? Hash of build?

**Comment by xiaoxiangmoe** [comment]
> What hash? Hash of build?

Yes.

see https://github.com/webpack/webpack/issues/15274#issuecomment-1025096351

**Comment by alexander-akait** [comment]
Source map is not part of build hash, I am afraid it is limitation

**Comment by sokra** [comment]
Bug in `ContextModule`. It should use relative source paths for `new OriginalSource`, similar to `NormalModule`

**Comment by TrickyPi** [comment]
Is anyone resolving this issue?

**Comment by cool-little-fish** [comment]
I'am fixing it, maybe take a little time.

**Comment by TrickyPi** [comment]
well, I find some points, we can get relative source paths by using `makePathsRelative` function https://github.com/webpack/webpack/blob/main/lib/util/identifier.js#L275

and use `makePathsRelative(this.options.context,this._identifier)` instead of `this.identifier()` here. 
https://github.com/webpack/webpack/blob/main/lib/ContextModule.js#L1062

I hope this will help.

**Comment by cool-little-fish** [comment]
yeah, and actually that's what I am trying to do...
