### ISSUE TITLE
require.ensure seems to ignore chunkName

### ISSUE THREAD

**Issue by use-strict** [webpack/webpack#1527]
I have a split point done like this:
```javascript
require.ensure([], function() {
    var lazyModule = require('./lazyModule');
    //...
}, "myFeature");
```

I would expect a bundle file "myFeature.bundle.js" to be created instead of an "unnamed" "1.bundle.js". This doesn't happen, unless I also add a dummy entry point having the same name. If I do this, webpack seems to know to merge all the lazy-loaded modules into this chunk. However, this is far from ideal, because it will require me to add everything explicitly in the webpack config file. Not to say a bunch of dummy files which do nothing.

I'm using the chunkName for two reasons.
1. I want to avoid numbered bundles, so I can keep track of what each bundle is for and how large it is.
2. I am loading bundles using a script loader with custom logic, so I need to know the name of the bundle at compile time.

**Comment by sokra** [comment]
Set `output.chunkFilename` to `"[name].bundle.js"`.

**Comment by use-strict** [comment]
It is already set.
