### ISSUE TITLE
Outputted lambda in conditional fails with Qt WebKit 

### ISSUE THREAD

**Issue by bitfridge** [webpack/webpack#15285]
# Bug report

Bundles cannot be loaded by the Qt WebKit browser and fail with console message 
`':'. Expected a ';', ']', '}', ')', ',', line terminator or EOF following a arrow`

Bundles should load without an error.

**Other relevant information:**
webpack version:  5.67.0
Node.js version: 
Operating System: 
Additional tools:

**Comment by bitfridge** [comment]
The problem is caused by `CompatGetDefaultExportRuntimeModule`. It generates this code:
```
/* webpack/runtime/compat get default export */
/******/ 	(() => {
/******/ 		// getDefaultExport function for compatibility with non-harmony modules
/******/ 		__webpack_require__.n = (module) => {
/******/ 			var getter = module && module.__esModule ?
/******/ 				() => (module['default']) :
/******/ 				() => (module);
/******/ 			__webpack_require__.d(getter, { a: getter });
/******/ 			return getter;
/******/ 		};
/******/ 	})(); 
```
It works with Qt WebKit if it looks like this:
```
/* webpack/runtime/compat get default export */
/******/ 	(() => {
/******/ 		// getDefaultExport function for compatibility with non-harmony modules
/******/ 		__webpack_require__.n = (module) => {
/******/ 			var getter = module && module.__esModule ?
/******/ 				(() => (module['default'])) :
/******/ 				(() => (module));
/******/ 			__webpack_require__.d(getter, { a: getter });
/******/ 			return getter;
/******/ 		};
/******/ 	})(); 
```

I can create a pull request if that solution is viable. For me it works with this change: https://github.com/bitfridge/webpack/commit/42ccfbcacd199df72c247c21b93335be62867e88

**Comment by alexander-akait** [comment]
Please report bug in Qt WebKit, it is valid JS

**Comment by vankop** [comment]
hm.. maybe your browser does not supports arrow functions? since your changes does not change anything..

try to disable arrow function support https://webpack.js.org/configuration/output/#outputenvironment

**Comment by alexander-akait** [comment]
Looks like bug in JS engine, because `(() => (module['default']))` works fine in report

**Comment by alexander-akait** [comment]
I see this bug somewhere long ago in chrome, I think it is the same problem

**Comment by bitfridge** [comment]
True but I have no influence on the browser. It is part of an embedded system and not going to change. Qt  WebKit is deprecated. 
If this compatibility issue is not fixed in Webpack then there is no way my application can work on the system. 
Maybe I'll have to maintain this patch for my use case.

**Comment by alexander-akait** [comment]
Please use https://webpack.js.org/configuration/output/#outputenvironment and disable arrows functions if they not supported

**Comment by bitfridge** [comment]
Ok, that works. Thanks! So I guess no need to change Webpack for that old browser.
