### ISSUE TITLE
Watchpack Error (watcher): Error: EACCES

### ISSUE THREAD

**Issue by melsiir** [webpack/webpack#15297]
# Bug report

**What is the current behavior?**

I am trying to use my react webpack setup on my Android system but this watcher warning annoying I don't know why it trying to watch system root directory which should not be accessible to users unless they have root access : Watchpack Error (watcher): Error: EACCES: permission denied, watch '/data/data' Watchpack Error (watcher): Error: EACCES: permission denied, watch '/data' Watchpack Error (initial scan): Error: EACCES: permission denied, scandir '/data/data' Watchpack Error (initial scan): Error: EACCES: permission denied, scandir '/data'

This my project cwd where home directory is my $HOME I don't know why webpack trying to go beyond that :

/data/data/com.termux/files/home/react

I tried to ignore the data/ directory by adding this option in webpack config :

watchOptions: { ignored: [”../../../../../../"] } But this make hot reloading stop working anyone had experienced this before I will appreciate help

**If the current behavior is a bug, please provide the steps to reproduce.**

Just launch devServer it happened also with npx create-next-app 
**What is the expected behavior?**

No warrnigs

**Other relevant information:**
webpack version:  5.57.0
Node.js version: v17.4.0
Operating System: Android 10
Additional tools: termux terminal

**Comment by alexander-akait** [comment]
Duplicate https://github.com/webpack/watchpack/issues/187
