### ISSUE TITLE
Importing a particular file from an external-dependecy, does not handle the file as external dependency

### ISSUE THREAD

**Issue by dilyanpalauzov** [webpack/webpack#15294]
# Bug report

**What is the current behavior?**

I have:
```javascript
// this is webpack.config.js
import webpack from 'webpack'

export default {
    optimization: {
        minimize: false,
        concatenateModules: true
    },
    experiments: {
        outputModule: true
    },
    output: {
        environment: {
            module: true
        },
        library: {
            type: 'module'
        }
    },
    node: { global: false },
    externals: {
        "@popperjs/core": "@popperjs/core"
    }
}
```
and
```javascript
// this is src/index.js
import * as Popper from '@popperjs/core';

export default Popper.createPopper(null, null);
```

My package.json has `"type": "module",`.

This works as expected, the output of `yarn webpack` is 1700 bytes.  I change src/index.js to
```javascript
import * as Popper from '@popperjs/core/dist/esm/popper-lite.js';

export default Popper.createPopper(null, null);
```
The change is in the import-line.  Now not the whole module is imported, but a file from it.

The output file of `yarn webpack` is now 37kb and practically ignores the external dependency.

Webpack recognizes, that '@popperjs/core' is external dependeny.

Webpack shall recoginze, that '@popperjs/core/dist/esm/popper-lite.js' is also part of the external dependency.

**What is the expected behavior?**

The expected behaviour in the case of  `import * as Popper from '@popperjs/core/dist/esm/popper-lite.js';` is to have output of approximately 1700bytes.  Instead the code from '@popperjs/core/dist/esm/popper-lite.js' is not handled as external dependency.

**Other relevant information:**
webpack: 5.68.0
webpack-cli: 4.9.2
node: v16.13.1

**Comment by vankop** [comment]
`externals` is kind of one to one mapping, you probably need to use `function` to handle all sub requests https://webpack.js.org/configuration/externals/#function

**Comment by dilyanpalauzov** [comment]
Yes, with a function it does work, likewise it works when I spell each imported file explicitly in
```
externals: [
  'mod1/file1.js': 'mod1/file1.js',
  'mod1/file2.js': 'mod1/file2.js',
  'mod1/file2.js': 'mod1/file3.js'
]
```
but it would be better, if webpack recognizes the prefix from externals, and handles everything beneath that prefix as external dependency.

**Comment by vankop** [comment]
> if webpack recognizes the prefix from externals

Unfortunately, this works another way around as well.. It is possible to bundle only part of a library

**Comment by dilyanpalauzov** [comment]
Fair enough.
