### ISSUE TITLE
update default target when `output.module=true`

### ISSUE THREAD

**Issue by vankop** [webpack/webpack#15292]
## Feature request

update defaults when bundling esm library

**What is the expected behavior?**

with
```js
output: {
   module: true
}
```
webpack should set default `output.environment.module=true`

**What is motivation or use case for adding/changing the behavior?**

when building esm bundle/library output environment  should support es modules

**How should this be implemented in your opinion?**

update defaults

**Are you willing to work on this yourself?**
yes

**Comment by alexander-akait** [comment]
@vankop I think we can do it only in the next major release, because externals, plugins and chunk loading can be different and do not support ESM output

**Comment by vankop** [comment]
this is will work only with `experiments.outputModule=true`, so it is ok..

**Comment by dilyanpalauzov** [comment]
See also https://github.com/webpack/webpack/discussions/15291 and https://github.com/webpack/webpack/issues/15290.
