### ISSUE TITLE
`baseUri` option for entries

### ISSUE THREAD

**Issue by vankop** [webpack/webpack#15303]
## Feature request

webpack should allow to pass `baseUri` in `loaderContext.importModule`, this will allow to create correct public path for assets. related issue https://github.com/webpack-contrib/mini-css-extract-plugin/issues/872

**What is motivation or use case for adding/changing the behavior?**

correct public path for assets

**How should this be implemented in your opinion?**

- baseUri option on entry
- all chunk loading runtime modules need to use the baseUri option
- importModule pass baseUri option along

**Are you willing to work on this yourself?**
yes

**Comment by alexander-akait** [comment]
Maybe we can keep one issues, the root of the problem one - https://github.com/webpack/webpack/issues/15172#issuecomment-1027287563, just update title and provide more context

**Comment by vankop** [comment]
I have update an issue with `baseUri` changes. So this is kind of separate issue

**Comment by vankop** [comment]
done https://github.com/webpack/webpack/pull/15424
