### ISSUE TITLE
IgnoreWarningsPlugin not functioning properly

### ISSUE THREAD

**Issue by JarynChen** [webpack/webpack#15314]
# Bug report

**What is the current behavior?**
The IgnoreWarningsPlugin cannot ignore the warnings I specify normally
Steps to reproduce:
1. clone this repo: https://github.com/JarynChen/malagu
2. then open the project root directory 
3. run `lerna bootstrap` to install packages
4. run `cd examples/backend-app` to change to the test directory
5. run `malagu build`
6. you can see output warning
![image](https://user-images.githubusercontent.com/41881490/152522618-9d1c548a-0f44-4cab-ac30-5d59bbd62db4.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
1. open `node_modules/webpack/lib/IgnoreWarningsPlugin.js` file
2. replace with this code: https://github.com/JarynChen/webpack/blob/8a61ec80c24a6ba74cb10542904c7daead73be9e/lib/IgnoreWarningsPlugin.js#L24
3. then you can see warning ignored

**What is the expected behavior?**
Ignore warnings normally

**Other relevant information:**
webpack version:  5.52.0
Node.js version:  16
Operating System:  macos
Additional tools: vscode

**Comment by alexander-akait** [comment]
Where you use `IgnoreWarningsPlugin`? I can't found, please in future try to reduce complex of reproducible example, respect time of other developers, thanks

**Comment by JarynChen** [comment]
> Where you use `IgnoreWarningsPlugin`? I can't found, please in future try to reduce complexity of reproducible example, respect time of other developers, thanks

https://github.com/JarynChen/malagu/blob/2f74c52a3d5f3ebcfb982819052c4cfbc62225f4/dev-packages/cli-service/src/webpack/config/plugin-config-factory.ts#L75

**Comment by alexander-akait** [comment]
Somethings wrong with `@soda/friendly-errors-webpack-plugin`...

**Comment by JarynChen** [comment]
omg...

**Comment by alexander-akait** [comment]
Shorty - we use factory to print stats, and run `processWarnings` hooks only when trying print stats (but we still keep warnings in stats), but plugin https://github.com/sodatea/friendly-errors-webpack-plugin/blob/master/src/friendly-errors-plugin.js#L137 doesn't use our factory, just get warnings from stats, so you see warning

**Comment by alexander-akait** [comment]
https://github.com/webpack/webpack/blob/main/lib/stats/DefaultStatsFactoryPlugin.js#L487

**Comment by JarynChen** [comment]
Thanks again

**Comment by alexander-akait** [comment]
Ideally plugin should use `compilation.getWarnings()` to get filtered warnings, we keep store warnings in stats to other tools, they can do additional analyze and hints

**Comment by JarynChen** [comment]
ok, thanks
