### ISSUE TITLE
Exporting directories with `exports` field in package.json is now deprecated!

### ISSUE THREAD

**Issue by MuhammadSawalhy** [webpack/webpack#15317]
# Bug report

**What is the current behavior?**

I am not sure if this is really a bug or not, but let's assume it is a bug in the documentations.

It seems that you still have the exported directories in your [documentations of package exports](https://webpack.js.org/guides/package-exports/) which is now deprecated when trying to export a directory and importing it from an the parent package that installed this exporting package (which exports), or by [self-importing](https://nodejs.org/dist/latest-v14.x/docs/api/packages.html#packages_self_referencing_a_package_using_its_name) that directory.

```
(node:983501) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /tmp/test-new-daunting-package-fields/package.json imported from /tmp/test-new-daunting-package-fields/src/a/b/c/index.js.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**What is the expected behavior?**

Deprecated, so to be excluded from the documentations.

**Other relevant information:**

Node.js version: `v16.13.2`
Operating System: `Arch Linux x86_64`

**Comment by MuhammadSawalhy** [comment]
I took much time trying to understand the `exports` and `imports` fields including reading the nearly all the comments of this issue: https://github.com/webpack/webpack/issues/9509.

**Comment by vankop** [comment]
> (node:983501) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at /tmp/test-new-daunting-package-fields/package.json imported from /tmp/test-new-daunting-package-fields/src/a/b/c/index.js.
Update this package.json to use a subpath pattern like "./*".

 this is Node.js warning, webpack I think does not produce any warning in this case
