### ISSUE TITLE
webpack cjs targetType compile jsPdf show error `Can't import the named export 'SVGPathData' (imported as 'SVGPathData') from default-exporting module (only default export is available)`

### ISSUE THREAD

**Issue by wind4gis** [webpack/webpack#15339]
# Bug report

**What is the current behavior?**
i use webpack5 to compile a vue2 component, which use `jspdf`.when i run webpack compile, it shows error...
![image](https://user-images.githubusercontent.com/3963291/152973756-d6cf8a5a-2c87-4a4a-877a-f0e30aea5baa.png)

when i debug the code, i found that webpack resolve buildMeta of svg-pathdata which is used in jspdf dependence canvg,  to `default-only`. but i look at [the svg-pathdata code in github](https://github.com/nfroidure/svg-pathdata#readme), svg-pathdata do not have a default export, it use rollup to compile the library...

**If the current behavior is a bug, please provide the steps to reproduce.**
component code
```
import { jsPDF } from 'jspdf';
const pdfInstance = new jsPDF(image.width >= image.height ? 'landscape' : 'portrait', 'px', [image.width, image.height]);
```

webpack code
```
{
      name: 'cjs',
      target: 'web',
      context: path.join(ctxDir, entry.originalName),
      output: {
        path: path.join(ctxDir, entry.originalName, 'dist/cjs'),
        library: {
          type: 'commonjs2',
        },
      },
}
```

**What is the expected behavior?**
it should resolve `default-with-named` when webpack resolve svg-pathdata

**Other relevant information:**
webpack version:  5.68.0
Node.js version: v14.18.2
Operating System: mac
Additional tools: vscode

**Comment by alexander-akait** [comment]
Can you create small reproducible repo?

**Comment by wind4gis** [comment]
@alexander-akait https://github.com/wind4gis/test-webpack

**Comment by wind4gis** [comment]
@alexander-akait @vankop enter packages/test folder, and run `yarn build` command

**Comment by vankop** [comment]
this works fine https://gist.github.com/vankop/cd8e40b78b11808417080dab602a2cd8

**Comment by wind4gis** [comment]
i delete lerna and cli, you can checkout `test` branch, it's a simple repo...
and i found that maybe the image file loader rule cause the problem
```
{
        test: /\.png|jpg|gif|jpeg|svg/,
        type: 'asset',
        parser: {
          dataUrlCondition: {
            maxSize: 10 * 1024,
          },
        },
        generator: {
          filename: 'images/[base]',
        },
      },
```
when i run `build` comand it works ok, run `build:svg` it works wrong.
you can checkout `test` branch, it's so strange @vankop

**Comment by vankop** [comment]
@wind4gis you should put `$` in the end of your `test` option
```
test: /\.png|jpg|gif|jpeg|svg$/,
```
with this one should be ok
