### ISSUE TITLE
webpack doesn't reload module in the watch mode after a file reported as a dependency by a loader gets renamed or removed from the file system

### ISSUE THREAD

**Issue by denvned** [webpack/webpack#1533]
Consider the following loader:

``` JavaScript
var path = require('path');
var fs = require('fs');

module.exports = function(input) {
    this.cacheable();

    var footerPath = path.resolve('./footer.txt'):
    this.addDependency(footerPath);
    if (fs.existsSync(footerPath))
        input += fs.readFileSync(footerPath);

    return input;
};
```

This loader appends constents of _footer.txt_, but only if it exists.
**In the watch mode** the user expects that when she renames _footer.txt_ or deletes it from the file system, the bundle gets repacked with no footer included. Instead, _webpack_ ignores renaming and deletion of dependencies, and doesn't repack the bundle, so, the bundle becomes out of sync with the sources.

Of course, my actual use case is more complex, and relates to [my TypeScript loader](https://github.com/denvned/webpack-typescript). For example, the problem is that _webpack_ doesn't repack the bundle when the extension of a dependency is changed from _.tsx_ to _.ts_, even if contents of the file is changed after renaming.

**Comment by narqo** [comment]
Any plans for the issue?

**Comment by veged** [comment]
👍
