### ISSUE TITLE
Add CLI command to output current configuration in full

### ISSUE THREAD

**Issue by SetTrend** [webpack/webpack#15331]
## Feature request

I propose to add a new command to Webpack CLI that outputs a project's current configuration in full detail – including default values.

The output should be a full-fledged JS file, with actual values used for each single configuration property. If no configuration value is provided, the actual and the computed default value should be added in a comment next to the value (which usually is `undefined`, as it is undefined).

For example, given a configuration like this:

```js
module.exports =
{
  mode: "development",
};
```

… the proposed Webpack CLI `config` command:

```powershell
npx webpack config [config-path [config-name]]
```

… should output the following to `stdout`:

<details>
<br/>

**Excerpt only:**

```js
const path = require('path');

module.exports = {
  target: undefined /* "web" */,
  mode: "development",
  entry: undefined /* "./src" */,
  output: {
    path: undefined /* path.resolve(__dirname, "dist") */ /* "C:\repos\myproject\dist" */,
    filename: undefined /* "[name].js" */,
    publicPath: undefined /* "/assets/" */,

  // ...
  // ...
  // ...

  optimization: {
    chunkIds: undefined /* "size" */,
    moduleIds: undefined /* "size" */,
    mangleExports: undefined /* "size" */,
    minimize: undefined /* true */,
    minimizer: undefined /* null */
  )
}
```

</details>

Please note the following in the above excerpt:

1. `mode` is the only property not being output as `undefined`, because it's being defined in the configuration file.
1. `mode` is the only property without a default value comment, because no default is applied to it.
1. Suppose, no `browserlist` file exists in this example. Then the actual default value for the `target` property is `"web"`, as is depicted in the excerpt above.
1. The actual default value for the `output.path` property is a computation (`path.resolve(__dirname, "dist")`). This will result in a second comment being added to the property, containing the computed default value, which is `"C:\repos\myproject\dist"`.
<br/>

#### What is motivation or use case for adding/changing the behavior?

Although there are many useful default values being applied to Webpack when a small configuration in a Webpack configuration file is used, it's still obscure which actual values are being used for all untouched Webpack configuration properties. So, it's hard to figure out unwanted or less than perfect build behaviour.

Moreover, with the proposed output, GUI tools can be written to provide form based helpers or linters for editing/optimizing webpack configurations.
<br/>

#### What is the expected behavior?

A new Webpack CLI command, `config`, should output a configuration's actual and default values. Values not defined in the config file should output `undefined` as the property value plus an additional comment added, showing their actual default value. If that actual default value is a computation, a second comment should be added to the output, showing the computed value.

NB: Redirection of the output to a file should be possible.

<br/>

#### How should this be implemented in your opinion?

An additional CLI command should be written, resulting in a syntax like the following:

```powershell
npx webpack config [config-path [config-name]]
```
<br/>

#### Are you willing to work on this yourself?
no

**Comment by vankop** [comment]
your idea could be useful, but full webpack really big + there is no way to serialize `object` like parameters (plugins objects, functions)

**Comment by alexander-akait** [comment]
@vankop in theory we can export https://github.com/webpack/webpack/blob/main/lib/config/normalization.js#L528 and output default values (funtions/classes/etc) will be outputed as serialized

**Comment by SetTrend** [comment]
@vankop: Yes, you are right. I expect the output to be large. In my vision, the main target of this output are supposed to be linters and external tools, not human beings.

But actually, an optional, additional parameter to the proposed Webpack CLI command could be used to filter the output, e.g.:

```powershell
npx webpack config [[--file ]config-path] [--name config-name] [--include included-properties]
```

… so, given the following existed …

```c#
npx webpack config --include output,cache
```

… the output could be similar to:

```js
module.exports = {
output: {
    library: 'someLibName',
    libraryTarget: 'umd',
    filename: 'someLibName.js',
    auxiliaryComment: 'Test Comment',
  },
  cache: {
    type: 'filesystem',
    allowCollectingMemory: true,
  },
};
```

**Comment by alexander-akait** [comment]
I think we will move this issue in `webpack-cli` repo after we expose some methods from webpack

**Comment by SetTrend** [comment]
Sounds great!

Please pardon me for choosing the wrong repo. I had not been aware of the other repository.

**Comment by SetTrend** [comment]
@alexander-akait:

Would you want to put this improvement request on your roadmap?

**Comment by alexander-akait** [comment]
You can send a PR, it is already in ROADMAP, but I don't have time on this currenty, sorry

**Comment by SetTrend** [comment]
Perfect. I was just asking you because the webpack-bot was about to close this issue. Unfortunately I cannot afford the time to contribute at this time, though I'd very much liked to do so.

**Comment by SetTrend** [comment]
@alexander-akait: I believe this issue is still important.

**Comment by alexander-akait** [comment]
Yeah :+1:

**Comment by SetTrend** [comment]
So, this isn't going to be implemented..?
