### ISSUE TITLE
Used exports are excluded with the "unused export" comment when using `export * as ...`

### ISSUE THREAD

**Issue by mifopen** [webpack/webpack#15346]
# Bug report

**What is the current behavior?**
Some used exports are excluded with the "unused export" comment when using `export * as ...`

**If the current behavior is a bug, please provide the steps to reproduce.**
(not really minimal reproduction, but it shows the problem very well)
1. Clone https://github.com/microsoft/monaco-editor
2. `cd samples/browser-esm-webpack-monaco-plugin`
3. Add file `file.js` with one line `export * as monaco from 'monaco-editor/esm/vs/editor/editor.api';`
4. Replace `import * as monaco from 'monaco-editor/esm/vs/editor/editor.api';` in `index.js` with `import { monaco } from './file';`
5. `NODE_ENV=production npm run build`

**What is the expected behavior?**
`dist/main.bundle.js` should contain
`_common_network_js__WEBPACK_IMPORTED_MODULE_8__/* .RemoteAuthorities.setPreferredWebSchema */ .WX.setPreferredWebSchema(/^https:/.test(window.location.href) ? 'https' : 'http');
`
but instead it has
`/* unused export .RemoteAuthorities.setPreferredWebSchema */ undefined(/^https:/.test(window.location.href) ? 'https' : 'http');
`
which cause a runtime error (you can open `dist/index.html` in browser to see)

You can switch between the old line in `index.js` and the new one to see the difference.
Works similar in development mode.

**Other relevant information:**
webpack version:  5.68.0
Node.js version: 16.13.0
Operating System: macos
Additional tools:

**Comment by vankop** [comment]
@mifopen Could you check without monaco plugin in webpack.config ?

**Comment by mifopen** [comment]
Just checked and yes, works ok without a plugin (there is another sample called `browser-esm-webpack`).
But what kind of bug could cause such strange behaviour? Сould you please tell me where to start?

**Comment by vankop** [comment]
it looks like plugin produces cjs exports https://github.com/microsoft/monaco-editor/blob/main/webpack-plugin/src/loaders/include.ts#L34 ..
