### ISSUE TITLE
Inline loader seems not supporting loader option value in which type is function.

### ISSUE THREAD

**Issue by mizok** [webpack/webpack#15361]
# Bug report

Here the doc mentioned that we have to pass a `JSON` or  a`query string` value for loader option when using ` inline loader `
https://webpack.js.org/concepts/loaders/#inline

But it seems both of `JSON` & `query string`  do not support  `function` values, so I suppose this is a bug? Since some loader does have options in which type is function. (for example: `html-loader` : `preprocessor`)

In my case, I just need `inline loader` to defined which loader to use for specific `.ejs` files, and I am going to use these files in `htmlWebpackPlugin` as template, so I can't use the `module.rules` way to set the loaders.

You can check the library I am working on here ( just read the `Passing individual values` part of `README.md`)
https://github.com/dc7290/template-ejs-loader

**What is the current behavior?**
If I pass a function type value as option value to `inline loader `, it just become `undefined`.

**If the current behavior is a bug, please provide the steps to reproduce.**
You can try to pass the option `preprocessor` of `html-loader` using  `inline loader`, then you will get what I am meaning about I guess.

**What is the expected behavior?**
`inline loader` must support option values in any type. 

**Other relevant information:**
webpack version:  5.66.0
Node.js version: v14.17.5
Operating System:  macOS Catalina
Additional tools:

**Comment by alexander-akait** [comment]
Not related to webpack, please open an issue in html-loader

**Comment by mizok** [comment]
> Not related to webpack, please open an issue in html-loader
@alexander-akait 
But obviously any loader that have option values in function type will get this problem I guess?
