### ISSUE TITLE
[HMR] Hot Module Replacement:  request 404

### ISSUE THREAD

**Issue by VectorHo** [webpack/webpack#1536]
when I will use HMR( [Combining with an existing server] (http://webpack.github.io/docs/webpack-dev-server.html#combining-with-an-existing-server)), I found some problems.

```js
> node myserver.js // Listen on port 3000
> webpack-dev-server  // Listen on port 8080
```

### webpack.config.js 
![image](https://cloud.githubusercontent.com/assets/7578264/10655845/0b69fa76-78ab-11e5-9511-f1e5ba61d119.png)
![image](https://cloud.githubusercontent.com/assets/7578264/10655869/5c8ec3e6-78ab-11e5-8678-c751282b18af.png)

### change  chunk
![image](https://cloud.githubusercontent.com/assets/7578264/10655836/f2516ee8-78aa-11e5-8076-a9f9992c71ab.png)

### request 404 -> old hash Chunk (brower can not change)
![image](https://cloud.githubusercontent.com/assets/7578264/10655820/d846156c-78aa-11e5-9871-d2ac705e809b.png)

### webpack-dev-server generating new hash Chunk
![image](https://cloud.githubusercontent.com/assets/7578264/10655857/2b69435e-78ab-11e5-8399-b259db2b4591.png)

Hash chunk  is not consistent by request，this is the reason why can't find.

**Comment by liondancer** [comment]
+1

**Comment by igorokb** [comment]
+1 Facing with similar issue...

**Comment by demiurga** [comment]
@VectorHo did you solve it? Can you share your solution?
