### ISSUE TITLE
`require.context` not parsed in ESM packages

### ISSUE THREAD

**Issue by tavoyne** [webpack/webpack#15372]
# Bug report

**What is the current behavior?**

In packages with `type: "module"`, webpack fails to parse and replace `require.context()` expressions.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Clone https://github.com/tavoyne/webpack-2ece8c.
2. Run `yarn webpack --mode=production`.
3. Inspect the `dist/main.js` file and notice that the `require.context()` expression is still present.
4. (Remove `type: "module"` from the `package.json` file.)
5. (Inspect the `dist/main.js` file again and notice how the `require.context()` expression was successfully replaced.)

**What is the expected behavior?**

The replacement to be successful at step (3).

As `require` is not available in ESM environments, it could be called `import.context` in order to avoid confusion.

**Other relevant information:**
webpack version:  `5.68.0`
Node.js version: `17.4.0`
Operating System: MacOS
Additional tools: N/A

**Comment by tavoyne** [comment]
I understand, but the fact that it's called `require.context` is anecdotical, isn't it? I mean Webpack doesn't use the `require` function under the hood, it just parses the expression. In this case it's a shame to restrict its usage to CJS environments only, don't you think?

> Ah.. if you need context you still can use import('/a/a' + name)

I agree this is handy, but I need the filenames.

**Comment by vankop** [comment]
Webpack tries to follow specs. Since esm kind of strict environment there is no cjs stuff in it.

**Comment by tavoyne** [comment]
But `require.context` is not a _cjs stuff_, it's webpack's.

**Comment by alexander-akait** [comment]
`require.context` exists only because webpack starts when ESM was not ready, so `require.context` is just hack for `import(...)`, because currently ESM is preferable and we should reduce usage of commonjs, we stop to add new features for `require` (i.e. CommonJS) and also block them to ESM

**Comment by vankop** [comment]
@sokra should we add `import.meta.context` ?

**Comment by tavoyne** [comment]
I agree with you @alexander-akait. But `require.context()` has an extra functionality compared to `import()`: it's the fact that you can access filenames.

**Comment by tavoyne** [comment]
Here's an example of what you can do with `require.context` but not with `import()`.

```js
const posts = require.context("./pages", true, /\.js$/u, "lazy");

const render = async () => {
  const { pathname } = window.location;

  if (posts.keys().includes(`.${pathname}`)) {
    renderHtml(await posts(pages));
  } else {
    renderHtml("Not found");
  }
};
```

> @sokra should we add import.meta.context ?

Could it be even more agnostic, e.g. `webpack.context`?

**Comment by alexander-akait** [comment]
@vankop @tavoyne To be honest, I have quite different feelings, on the one hand, I understand well how it is used and why it is needed, on the other hand, we already had the experience of adding new stuff to module system and it always ended badly.

**Comment by alexander-akait** [comment]
It changes `import` logic, it is very bad idea, we should not do it, in this case better to use `import.meta.context()`, because `import.meta.*` is free to use, maybe even `import.meta.webpackContent` to prevent overlapping with other tools

**Comment by tavoyne** [comment]
Makes complete sense. Could work on a PR if it's something that you'd consider integrating.

**Comment by alexander-akait** [comment]
@sokra What do you think?

**Comment by sokra** [comment]
`import.meta.webpackContext` would be the name to choose here.

But we should use the chance to improve the API a bit and let it take an object instead of many arguments. This would also allow to add the other options a context takes, like `include` or `exclude` or `mode`

**Comment by maoxiaoke** [comment]
similar phenomenon was found when using [require.resolveWeak](https://webpack.js.org/api/module-methods/#requireresolveweak) in a pure ESM package @sokra @alexander-akait
