### ISSUE TITLE
Incremental build with --watch?

### ISSUE THREAD

**Issue by samunro** [webpack/webpack#1537]
Going on the documentation for [incremental builds](http://webpack.github.io/docs/build-performance.html#incremental-builds), it looks as though I should be able to get an incremental build using `--watch`.

Further, cache should be [enabled by default](http://webpack.github.io/docs/configuration.html#cache).

This does not appear to be working though. I have split out one small module from a relatively large one. The small one is to the bottom left of this [analyse screenshot](http://www.evernote.com/shard/s120/sh/5d14bec4-20fe-415f-9b9e-9d98d754c5f7/9db3627a62970afaadc3cce9bbf41501). I would expect that a change to the small chunk should only require that chunk to be rebuilt and that it should complete much faster than a change to the main chunk which I presume would require a rebuild of that much bigger chunk.

This is the command that I am using. I wait for the initial build to complete and then make a change in either the small or main chunk.

```
webpack --colors --bail --watch --config webpack.config.js
```

I don't see any difference in build times for changes in the small and main chunks. Am I missing something?

**Comment by jhnns** [comment]
Do you use grunt or something similar to trigger the builds? You need to ensure that the process keeps running. Could you also give us your `webpack.config.js`?

**Comment by samunro** [comment]
I am running the webpack command that I included above from the command line and the process stays running.

I was not able to add attachments so I have included the contents of the two files that we use to configure webpack inline below.

---webpack.config.js---
    var webpack = require('webpack');

    var baseConfig = require("./webpack.base.config.js");
    var config = Object.create(baseConfig);

    config.isDev = true;
    config.plugins.push(new webpack.HotModuleReplacementPlugin());

    config.entry.main = [
        'webpack-dev-server/client?http://localhost:9090', // listens to webpack-dev-server messages and passes them to HMR runtime.
        'webpack/hot/dev-server', 'app.entry.ts'
    ];   // Hot Module Replacement runtime that knows how to apply hot updates.]

    config.entry.silverlight = "silverlight/silverlight.entry.ts";

    config.output.publicPath = "http://localhost:9090/dev-build/";

    //Set the following URL for an issue related to getting absolute paths working.
    //https://github.com/webpack/webpack/issues/238
    config.plugins.push(new webpack.SourceMapDevToolPlugin({
        filename: '[file].map',
        exclude: ['vendor.js', "core.js"],
        moduleFilenameTemplate: "../../app/[resource-path]",
        fallbackModuleFilenameTemplate: "../../app/[resource-path]?[hash]"
        //moduleFilenameTemplate: "[absolute-resource-path]",
        //fallbackModuleFilenameTemplate: "[absolute-resource-path]"
    }));

    module.exports = config;
---webpack.config.js---

---webpack.base.config.js---
    var path = require('path');
    var webpack = require('webpack');
    var console = require('console');
    var ngAnnotatePlugin = require('ng-annotate-webpack-plugin');
    var appModulesPath = path.join(__dirname, 'app');
    var nodeModulesPath = path.join(__dirname, 'node_modules');
    var bowerComponentsPath = path.join(__dirname, 'bower_components/');
    var externalLibraryPaths = path.join(__dirname, 'Scripts/');


    var baseConfig = {
        isProduction: false,
        isDev: true,
        isTest: false,
        isStaging: false,
        cache: true,
        context: appModulesPath,
        entry: {
            core: ["jquery", "angular"],
            vendor: [ "bootstrap", "toastr", "angular-new-router", "breeze", "breeze.angular", "moment", "angular-block-ui", "BootstrapDialog", "breeze.directives"]
        },

        output: {
            path: path.resolve('./dev-build'),
            filename: "[name].bundle.js",
            chunkFilename: '[id].bundle.js'
        },

        contentBase: appModulesPath, // this is the base path where all contents exist
        resolve: {
            // tells webpack to query these directories for modules
            root: [appModulesPath, nodeModulesPath, bowerComponentsPath],
            alias: {
                jquery: externalLibraryPaths + 'jquery',
                angular: externalLibraryPaths + 'angular',
                bootstrap: bowerComponentsPath + "bootstrap/js/modal",
                "BootstrapDialog": appModulesPath + "/components/bootstrap-dialog/dist/js/bootstrap-dialog",
                toastr: externalLibraryPaths + "toastr",
                "angular-new-router": externalLibraryPaths + "router.es5",
                breeze: bowerComponentsPath + "breezejs/breeze.debug",
                "breeze.angular": bowerComponentsPath + "breezejs/labs/breeze.angular",
                "breeze.directives": appModulesPath + "/components/breezejs/breeze.directives",
                moment: bowerComponentsPath + "moment/moment",
                "angular-block-ui": bowerComponentsPath + "angular-block-ui/dist/angular-block-ui",
                "underscore": bowerComponentsPath + "underscore/underscore",
                "scriptjs": bowerComponentsPath + "scriptjs/dist/script"
            },
            extensions: [
                '',
                ".webpack.js", ".web.js", '.ts',
                '.js', '.coffee',
                '.html', '.jade',
                '.css', '.styl', '.scss', '.less'
            ]
        },
        resolveLoader: {
            root: nodeModulesPath
        },

        plugins: [new ngAnnotatePlugin({ add: true }),
                    new webpack.optimize.CommonsChunkPlugin("core", "core.js", ["main", "silverlight", "vendor"]),
                    new webpack.optimize.CommonsChunkPlugin("vendor","vendor.js", ["main"]),
              
                    new webpack.ResolverPlugin([new webpack.ResolverPlugin.DirectoryDescriptionFilePlugin("bower.json", ["main"])]),
                    new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/),
                     //new webpack.PrefetchPlugin('lodash'),
                    new webpack.ProvidePlugin({
                        $: "jquery",
                        jQuery: "jquery",
                        "window.breeze": "breeze",
                        "breeze": "breeze",
                        "BootstrapDialog": "BootstrapDialog",
                        "moment": "moment"
                    }), function () {
                        this.plugin("done", function (stats) {
                            if (stats.compilation.errors && stats.compilation.errors.length && process.argv.indexOf('--watch') == -1) {
                                console.log(stats.compilation.errors);
                                process.exit(1); // or throw new Error('webpack build failed.');
                            }
                            // ...
                        });
                    }],

        // call this method to ask webpack not to parse files which are already minimized.
        addVendor: function (name, path) {
            this.resolve.alias[name] = path;
            this.module.noParse.push(new RegExp(path));
        },

        module: {
            loaders: [
                // Exports Angular
                { test: /[\/]angular\.js$/, loader: "exports?angular" },

                //export jquery to global window object. this is because there are javascript functions which requires
                // jquery in the app.html page. the two loader below will expose jquery to window.$ or window.jquery
                // We need jquery to hide and show app.
                 { test: /jquery\.js$/, loader: 'expose?$' },
                { test: /jquery\.js$/, loader: 'expose?jQuery' },

                // Script Loaders
                { test: /\.coffee$/, loader: "coffee" },
                // Markup Loaders
                { test: /\.html$/, loader: "raw" },
                { test: /\.jade$/, loader: "template-html" },
                // Typescript loader nodeModulesPath
                 { test: /\.ts$/, loader: 'babel-loader!ts-loader' },
           
                // Sass Loader
                { test: /\.scss/, exclude: /\.useable\.scss/, loader: "style!css!autoprefixer!sass" },
                { test: /\.useable\.scss/, loader: "style/useable!css!autoprefixer!sass" },
                {
                    test: /\.less$/,
                    loader: "style!css!less"
                },
                {
                    test: /\.(otf|eot|svg|ttf|woff|woff2)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
                    loader: 'url?limit=10000'
                },
                // File loader
                  { test: /\.jpe?g$|\.gif$|\.png$|\.svg$|\.woff$|\.ttf$|\.eot$/, loaders: ['file?hash=sha512&digest=hex&name=[hash].[ext]',
                                                                          'image-webpack?bypassOnDebug&optimizationLevel=7&interlaced=false' ]}
            ]
        }
    }

    module.exports = baseConfig;
---webpack.base.config.js---

**Comment by tvararu** [comment]
It sounds to me like you have the same issue I do, https://github.com/webpack/webpack/issues/1530.

> I would expect that a change to the small chunk should only require that chunk to be rebuilt and that it should complete much faster than a change to the main chunk which I presume would require a rebuild of that much bigger chunk.

This was my expectation as well, but it does not seem to be the case. I'm curious as to why.

**Comment by Phoscur** [comment]
Migrating from RequireJS and Bower, I finally got it working without the Bower Webpack or any DirectoryDescriptionsFilePlugin. Still confused what those were actually doing. I had to keep the root absolute "bower_components/.." prefix and alias each module.

Also the Breeze Mongo Dataservice needed some special imports to work as expected, I'm also adding this shim as a solution.
```javascript
// webpack.config.js extract
resolve: {
    root: [__dirname],
    moduleDirectories: ['bower_components', 'node_modules'],
    extensions: ['', '.ts', '.coffee', '.js', '.json', '.css', '.html'],
    alias: {
        'breeze': 'bower_components/breeze-client/breeze.debug',
        'breeze.angular': 'bower_components/breeze-client/build/adapters/breeze.bridge.angular',
        'breeze-directives': 'bower_components/breezejs/labs/breeze.directives',
        'breeze-dataservice-mongo': 'bower_components/breeze-client/build/adapters/breeze.dataService.mongo',
},
loaders: [
        {
          test: /[\/\\]breeze\.dataService\.mongo\.js$/,
          loader: 'imports?this=>window'
        },
        {
          test: /[\/\\]angular\.js$/,
          loader: 'exports?angular'
        },
//...
]
```

**Comment by bebraw** [comment]
Closing in favor of #1530.
