### ISSUE TITLE
integrate npm packages in webpack

### ISSUE THREAD

**Issue by js08** [webpack/webpack#1538]
I have a sample app is it possible to integrate depcheck-es6 package in the below app

https://github.com/rackt/redux/tree/master/examples/todomvc

so that I dont need to run depcheck-es6 in my terminal everytime and I can make it to automate.
I looked at API section but not sure how to do it. Is it possible to integrate in webpack to

```javascript
var path = require('path');
var depcheck = require('depcheck-es6');

var options = {
  withoutDev: false, // check against devDependencies
  ignoreBinPackage: false, // ignore the packages with bin entry
  ignoreDirs: [ // folder with these names will be ignored
    'sandbox',
    'dist',
    'bower_components'
  ],
  ignoreMatches: [ // ignore dependencies that matches these globs
    'grunt-*'
  ],
  parsers: { // the target parsers
    '*.js': depcheck.parser.es6,
    '*.jsx': depcheck.parser.jsx
  },
  detectors: [ // the target detectors
    depcheck.detector.requireCallExpression,
    depcheck.detector.importDeclaration
  ],
  specials: [ // the target special parsers
    depcheck.special.eslint,
    depcheck.special.webpack
  ]
};

depcheck('/path/to/your/project', options, function(unused) {
  console.log(unused.dependencies); // an array containing the unused dependencies
  console.log(unused.devDependencies); // an array containing the unused devDependencies
  console.log(unused.invalidFiles); // files that cannot access or parse
  console.log(unused.invalidDirs); // directories that cannot access
});
```

**Comment by bebraw** [comment]
Perhaps it would be smarter to solve this problem outside of webpack? Set up a custom npm script for it for example. You can trigger the script through your CI or something like [git-prepush-hook](https://github.com/sturdynut/git-prepush-hook) to match that automation requirement.

**Comment by bebraw** [comment]
You probably should push this to a plugin or a loader. See [npm-install-webpack-plugin](https://www.npmjs.com/package/npm-install-webpack-plugin) and [eslint-loader](https://www.npmjs.com/package/eslint-loader) for reference.
