### ISSUE TITLE
dynamic import is not working when the imported library has been listed in externals.

### ISSUE THREAD

**Issue by songshuzhong** [webpack/webpack#15380]
# Bug report

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  4.44.2
Node.js version: 14.18.1
Operating System: mac
Additional tools:

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
