### ISSUE TITLE
Idea: html-loader

### ISSUE THREAD

**Issue by jhnns** [webpack/webpack#154]
Loading html-files is currently done with the raw-loader. Unfortunately this way static images and other files referenced by the html file can't be emitted into the bundle folder.

What do you think? Is it out of scope of webpack to detect dependencies of other modules than js-files, like html-files? Is it possible to implement this with a specific html-loader?

I think it's quite easy to scan the dependencies of html files with a regex.

Since html-files and css-files are currently added as JavaScript-strings, is it possible to add minification to these generated strings?

**Comment by David263** [comment]
I'm planning to write a simple PHP or Golang program to combine all the css and js files in a project into one css file and one js file. Then the HTML will use <script> and <link> once to include these files. This will allow me to write using many files, one for each component. Especially if I us Go it should be very fast, so I can switch between editing and testing.

Or I may just decide to hide components in manually combined text files using a programmable editor like Emacs. Either way, it should run faster and more reliably than using webpack.
