### ISSUE TITLE
RFC: Add stat reporting for tree-shaken modules

### ISSUE THREAD

**Issue by cdaringe** [webpack/webpack#15400]
## Feature request

If a module is tree-shaken, provide a stat entry field claiming which dependencies have been shaken.

**What is the expected behavior?**

When studying a module stat, offer the information if a dependency is shaken.

```js
{
  "name": "my-module.js",
  "reasons": [{ filename: "/a/b/c.js", treeShaken: true }, /* ... */]
}
```

Or similar. This would imply that `/a/b/c.js` imported `my-module.js`, but it was shaken from `c.js`. There are certainly other schemas that could be used instead.

**What is motivation or use case for adding/changing the behavior?**

I seek to:

- apply new `rules: [{ test: myTest, sideEffects: false }]`, but need to do an audit of the tree-shaken modules to know that turning on this rule is safe
    - by getting a list of shaken modules, I can do a manual study to assert that no reading/writing from the global scope occurs, and verify that my optimization is _safe_
    - my project has _thousands_ of modules, so studying each of them is challenging. I want `sideEffects: false` set for nearly all ESM modules in my codebase, but want to audit those that are pruned with precision (vs many thousands in play). Having reporting will help me see what webpack is optimizing out, and allow me to assert these optimizations are safe before checking in the optimization

**How should this be implemented in your opinion?**

I assume that webpack _already_ identifies these modules during compilation. Allow for that state to be captured into the `Stats` interface, so as to help provide diagnostics.

**Are you willing to work on this yourself?**

Possibly, if given low to mid level coaching on what modules are in play, what edge cases to look out for, etc.

**Comment by vankop** [comment]
btw there is a plugin that marks modules with sideEffect flag https://github.com/vankop/side-effect-free-webpack-stat-plugin

**Comment by cdaringe** [comment]
Thanks @vankop , I will try evaluating this module shortly!

**Comment by cdaringe** [comment]
Hey @vankop, thx again. In retrospect, I'm already _declaring_ my modules as effect free--getting that added to the stat isn't exactly what I'm after.

I seek to find which modules were shaken.

I have high confidence that my thousands of monorepo modules are all sideEffect free, which is why I mark them as such using the `module.rules.[...]` discussed above. By marking them explicitly as effectFree, my codebase will be transformed such that some modules will be shaken.

I need to observe which modules are shaken, so I can apply a manual audit of them and know with confidence that the `sideEffects: false` declaration was correct.

Is there an API to _observe_ when something is shaken? Can I tap into a shake event?

**Comment by vankop** [comment]
[side-effect-free-webpack-stat-plugin](https://github.com/vankop/side-effect-free-webpack-stat-plugin) help a little bit on output analyze + you can use things like bundle analyzer or https://statoscope.tech/

**Comment by cdaringe** [comment]
Thanks @vankop.

- ya, the perf remark makes sense
- statoscope--already use it!

Nonetheless, the compiler is doing great work (skipping content), and even with the above--I don't have a solid way to _see_ the content that was dropped, which is important for asserting on the safety of my migration/optimization.

I've been trying to study the source, and I'm thinking that [the FlagDependencyUsagePlugin](https://github.com/webpack/webpack/blob/dfdc8b133d3d49371251e29efeefb9d31b982c9e/lib/FlagDependencyUsagePlugin.js#L158) may be where dependencies are introspected, identified as unused, then simply _not added_ into the dep graph?  It seems like this very return may implicitly be where tree-shaking occurs?

**Comment by cdaringe** [comment]
🐝
