### ISSUE TITLE
multiple externalsType support

### ISSUE THREAD

**Issue by paztis** [webpack/webpack#15406]
In a project I already use lot of externals (basic var one). They were manually handle by script injection since webpack 3

In webpack 5 externalsType appears and provide the 'script' mode.
I'd like to use for s new external that will point to a CDN, without changing the old ones.
But it seems externalsType is targeting all the externals.

We need a way to manage different externalType  for each externals in webpack 5

**Comment by ks-stack** [comment]
+1
