### ISSUE TITLE
devServer.index removed

### ISSUE THREAD

**Issue by rcketscientist** [webpack/webpack#15408]
In Webpack 5 `devServer.index` was removed.  What was the reasoning for this?  

I have a bit of a strange setup I inherited, but if I can change the name of the index that devServer loads it will reduce a lot of headaches in a migration of an archaic (and poorly designed) app.

I can place the logic on a an alternative HTML plugin, but I'm left wondering why the simple option was dropped.

**Comment by alexander-akait** [comment]
Please respect time and work of other developers and use the issue template, but if you have questions please use https://github.com/webpack/webpack/discussions.

`index` was not removed, please read https://github.com/webpack/webpack-dev-server/blob/master/migration-v4.md

> fs, index, mimeTypes, publicPath, serverSideRender, stats, and writeToDisk (related to [webpack-dev-middleware](https://github.com/webpack/webpack-dev-middleware)) were moved to devMiddleware option.
