### ISSUE TITLE
Persist cache doesn't work when using webpack API, but wepack-cli works.

### ISSUE THREAD

**Issue by dexbol** [webpack/webpack#15411]
# Bug report

**What is the current behavior?**
I use webpack by API, like:
```javascript
// ./run.mjs
import webpack from 'webpack';

const compiler = webpack({
    mode: 'development',
    infrastructureLogging: {
        level: 'verbose'
    },
    cache: {
        type: 'filesystem'
    }
});

compiler.run((err, stats) => {
    if (err) {
        console.error(err);
    }
    console.log(stats.toString());
});

// run it:
// node run.mjs
```
But `./node_modules/.cache` doesn't exsit. But it is works by `webpack-cli` using totally same configure object:

```javascript
// webpack.config.mjs
export default {
    mode: 'development',
    infrastructureLogging: {
        level: 'verbose'
    },
    cache: {
        type: 'filesystem'
    }
};
// run it by:
// npx webpack --config ./webpack.config.mjs
```
Then `./node_modules/.cache` will exists.

**If the current behavior is a bug, please provide the steps to reproduce.**
See the first example above.

**What is the expected behavior?**
It should generate `.cache` directory in `./node_modules`

**Other relevant information:**
webpack version:  v5.69.0
Node.js version: v17.0.1
Operating System: Mac OS 12.2.1
Additional tools: webpack-cli@4.9.2

**Comment by vankop** [comment]
@dexbol not sure, maybe you need to call `compiler.close()` in callback to store cache.

**Comment by dexbol** [comment]
> @dexbol not sure, maybe you need to call `compiler.close()` in callback to store cache.

It works 🎉 ! Much appreciated !
