### ISSUE TITLE
Webpack Compiling Twice In Watch Mode

### ISSUE THREAD

**Issue by daniel-nagy** [webpack/webpack#15438]
# Bug report

**What is the current behavior?**

When saving a file it appears Webpack is recompiling twice.

**If the current behavior is a bug, please provide the steps to reproduce.**

Create a barebones project [test.zip](https://github.com/webpack/webpack/files/8126010/test.zip). Run Webpack in watch mode. Save a file.

![2022-02-23 10 20 24](https://user-images.githubusercontent.com/1622446/155362119-cb227dfc-7aab-44b8-8374-84e9268c21bb.gif)

**What is the expected behavior?**

It should only recompile once.

**Other relevant information:**
webpack version:  5.69.1
Node.js version: 14.15.4
Operating System: Mac OS 11.6.4
Additional tools: yarn 1.22.5

**Comment by alexander-akait** [comment]
Duplicate https://github.com/webpack/webpack/issues/15431

**Comment by vankop** [comment]
@daniel-nagy workaround https://github.com/webpack/webpack/issues/15431#issuecomment-1048832781

**Comment by daniel-nagy** [comment]
@vankop Thanks, that does appear to prevent the double compilation.
