### ISSUE TITLE
Hot Reloading Runtime interrogation

### ISSUE THREAD

**Issue by Yomguithereal** [webpack/webpack#1543]
Hello @webpack. I am trying to set up a HMR routine and finds myself not able to receive module updates because of [those](https://github.com/webpack/webpack/blob/master/lib/HotModuleReplacement.runtime.js#L262-L264) lines. Can someone explain the reasons why it stops the update process when the `moduleId` is `0` please?

**Comment by jcreamer898** [comment]
Wow, I was literally about to create the exact same issue. I'm using chunking, and it just so happens that the chunk id is 0 and this is causing hot loading to not work at all for me.

**Comment by jcreamer898** [comment]
FWIW, when I comment that line out, it works as expected.

**Comment by jcreamer898** [comment]
https://github.com/webpack/webpack/commit/ea53b8761d99fed415517de955d271c23e5640c9

**Comment by Yomguithereal** [comment]
Same thing for me @jcreamer898. If I remove those line it works for me. But I guess those lines are here for a reason.

**Comment by Yomguithereal** [comment]
@jcreamer898 did you find a way to inject a modified version of the runtime without having to run a forked version of webpack?

**Comment by jcreamer898** [comment]
I just went in to node_modules and commented those lines out. It's such a small change that even if I get a new version of webpack I could do it again.

**Comment by Yomguithereal** [comment]
Unfortunately I cannot ask my users to do that :).

**Comment by jcreamer898** [comment]
hahaha, why not? :-p

**Comment by jcreamer898** [comment]
I'm noticing some oddities still even with that line commented out. It makes my SASS hot load fine, but my JS doesn't.

**Comment by mzgoddard** [comment]
`moduleId` being `0` means that the module that changed is your entry file. Hot swapped modules are accepted by other modules that use the hot swapped module. There shouldn't be anything that can accept the entry module because that is the highest module in the dependency hierarchy and webpack will explicitly error if anything depends on the entry file.

Which `webpack/hot` file are you using? You might be using the file (webpack/hot/only-dev-server) that ignores changes that cannot be applied. You should use `webpack/hot/dev-server` instead.

**Comment by jcreamer898** [comment]
I'm actually using `grunt-webpack` which has it's own task for the `webpack-dev-server` https://github.com/webpack/grunt-webpack/blob/master/tasks/webpack-dev-server.js

**Comment by Yomguithereal** [comment]
Thanks for the answer @mzgoddard. My issue occurs when attempting to accept updates from a module required from the entry module not when trying to hot reload the entry module itself (which would be pointless, I agree with you on that). I can elaborate a bit more if you have time and show you the incriminated code.

**Comment by Yomguithereal** [comment]
Ok, I found where I was mistaking. One of my entry files was requiring a file (the one I needed to hot reload) that was also in the entries array by mistake. I dropped the file from the entries array and it worked as expected.

So I guess everything works fine here. Closing the issue.
