### ISSUE TITLE
failed to inference ONNX model: TypeError: Cannot read properties of undefined (reading 'InferenceSession')

### ISSUE THREAD

**Issue by raphael10-collab** [webpack/webpack#15443]
Two weeks ago I opened a thread in `StackOverFlow` asking for help about `ONNX` not "read"/"loaded" by `webpack`:
https://stackoverflow.com/questions/71067989/failed-to-inference-onnx-model-typeerror-cannot-read-properties-of-undefined

but didn't receive any help.

I wrote a `GitHub's issue` in the Microsoft's ONNX page: https://github.com/microsoft/onnxruntime/issues/10516
and, according to them : https://github.com/microsoft/onnxruntime/issues/10516#issuecomment-1049295718 
, in order to be able to load `ONNX` through `webpack`, the `webpack.config.js` should have these traits:
`onnxruntime-web` NOT in `externals` , `target`: `web`,  and `NO alias`.

This is my complete `webpack.config.js` of my `Electron-React-Typescript-Webpack` app:

        const path = require('path');
        const cwd = process.cwd();
        const HtmlWebpackPlugin = require('html-webpack-plugin');
        const CopyPlugin = require("copy-webpack-plugin");
        const MiniCssExtractPlugin = require('mini-css-extract-plugin');
        const webpack = require('webpack');
        
        
        // https://hackernoon.com/how-to-run-machine-learning-models-in-the-browser-using-onnx?source=rss
        
        // https://github.com/Leaflet/Leaflet/issues/4849
        
        //const sqlite3 = require('sqlite3');
        
        //const RedisGraph = require("redisgraph.js").Graph;
        const RedisGraph = require("redisgraph.js");
        
        
        // https://github.com/Devtography/electron-react-typescript-webpack-boilerplate/blob/master/webpack.config.js
        
        function srcPaths(src) {
          return path.join(__dirname, src);
        }
        
        // Creates Webpack Aliases using CWD path
        //const createWebpackAliases = (als) => {
          //const result = {};
          //for (const name in als) {
            //result[name] = path.join(cwd, als[name]);
          //}
          //return result;
        //};
        
        //const aliases = createWebpackAliases({
          //'@src': 'src',
          //'@app': 'src/app',
          //'@app_A': 'src/app_A',
          //'@app_B': 'src/app_B',
          //'@app_C': 'src/app_C',
          //'@app_D': 'src/app_D',
          //'@app_E': 'src/app_E',
          //'@app_F': 'src/app_F',
          //'@app_G': 'src/app_G',
          //'@app_webpdf': 'src/app_webpdf',
          //'@app_trial': 'src/lib/pdfjs-dist/web',
          //'@about': 'src/sections/about',
          //'@account': 'src/sections/Account/account',
          //'@static': 'src/static',
          //'@pdfviewer': 'src/lib/pdfjs-dist/web/viewer',
        //});
        
        const isEnvProduction = process.env.NODE_ENV === 'production';
        const isEnvDevelopment = process.env.NODE_ENV === 'development';
        
          // main process
        var main_config = {
            mode: isEnvProduction ? 'production' : 'development',
            entry: './src/main/main.ts',
            target: 'electron-main',
            resolve: {
              extensions: ['.jsx', '.js', 'ts'],
            },
            // https://github.com/slackapi/node-slack-sdk/issues/746#issuecomment-778804407
            externals: [
              {
                'utf-8-validate': 'commonjs utf-8-validate',
                bufferutil: 'commonjs bufferutil',
              },
              //{
                //'sqlite3': sqlite3,
              //},
            ],
            module: {
              rules: [
                {
                  test: /\.ts$/,
                  include: /src/,
                  use: [{ loader: 'ts-loader' }]
                },
                {
                  // css files
                  test: /\.(sass|less|css)$/i,
                  use: [
                    {
                      loader: 'style-loader'
                    },
                    {
                      loader: 'css-loader'
                    },
                    {
                      loader: 'less-loader',
                    },
                  ],
                },
        
                {
                  test: /\.s?css$/,
                  use: [
                    {
                      loader: MiniCssExtractPlugin.loader,
                      options: {
                        sourceMap: true
                      }
                    },
                    {
                      loader: 'css-loader',
                      options: {
                        sourceMap: true
                      }
                    },
                    {
                      loader: 'sass-loader',
                      options: {
                        sourceMap: true
                      }
                    }
                  ]
                },
                {
                  test: /\.(png|jpe?g|svg|gif)$/i,
                  use: [
                    {
                      loader: "file-loader",
                      options: {
                        name: "[path]/[name].[ext]",
                      },
                    },
                  ],
                },
                {
                  test: /\.geojson$/,
                   use: [
                     {
                       loader: "json-loader",
                     }
                  ],
                }
              ]
            },
            output: {
              path: __dirname + '/dist',
              filename: 'main.js'
            },
            node: {
              __dirname: false,
              __filename: false
            },
            experiments: {
              asyncWebAssembly: true,
              syncWebAssembly: true,
              topLevelAwait: true
            }
          // renderer process
        var renderer_config =  {
            mode: isEnvProduction ? 'production' : 'development',
            entry: {
              // https://stackoverflow.com/questions/53477466/react-referenceerror-regeneratorruntime-is-not-defined
              app: ['./src/app/index.tsx', 'react-app-polyfill/stable'],
              app_A: './src/app_A/index_A.tsx',
              app_B: './src/app_B/index_B.tsx',
              app_C: './src/app_C/index_C.tsx',
              app_D: './src/app_D/index_D.tsx',
              app_E: './src/app_E/index_E.tsx',
              app_F: './src/app_F/index_F.tsx',
              app_G: './src/app_G/index_G.tsx',
              app_webpdf: './src/app_webpdf/index_webpdf.tsx',
              infoBasket: './src/app/sections/infobasket/Infobasket.tsx',
              style: './src/app/styles/index.css',
              style_A: './src/app_A/styles/index.css',
              style_B: './src/app_B/styles/index.css',
              style_C: './src/app_C/styles/index.css',
              style_D: './src/app_D/styles/index.css',
              style_E: './src/app_E/styles/index.css',
              style_F: './src/app_F/styles/index.css',
              style_G: './src/app_G/styles/index.css',
              //style_leaflet: path.resolve(__dirname, 'node_modules/leaflet/dist/leaflet.css'),
              style_webpdf: './src/app_webpdf/styles/index.css'
            },
            //target: 'electron-renderer',
            //target: 'web',
            target: ['web', 'es5'],
            //node: {global: true, fs: 'empty'},
            resolve: {
              extensions: ['.jsx', '.js', '.tsx', '.ts'],
              //alias: {
                // Custom Aliases
                //...aliases,
              //},
            },
            output: {
              path: __dirname + '/dist/',
                //filename: 'renderer.js'
              filename: '[name].js',
            },
            // https://github.com/slackapi/node-slack-sdk/issues/746#issuecomment-778804407
            externals: [
              {
                'utf-8-validate': 'commonjs utf-8-validate',
                bufferutil: 'commonjs bufferutil',
                //ort: 'ort',
              },
              //{
                //'sqlite3': sqlite3,
              //},
              {
                'RedisGraph': RedisGraph,
              },
            ],
            module: {
              rules: [
                {
                  test: /\.(js|ts)x?$/,
                  exclude: /node_modules/,
                  use: {
                    loader: 'babel-loader',
                  },
                },
                {
                  // css files
                  test: /\.css$/i,
                  use: [
                    {
                      loader: 'style-loader'
                    },
                    {
                      loader: 'css-loader'
                    },
                  ],
                },
                {
                  // Font files
                  test: /\.(woff|woff2|ttf|otf)$/,
                  loader: 'file-loader',
                  options: {
                    name: '[hash].[ext]',
                    outputPath: 'dist/assets/css/'
                  }
                },
                {
                  // image files
                  test: /\.(jpe?g|png|gif|svg)$/i,
                  loader: 'file-loader',
                  options: {
                    name: '/pics/[name].[ext]',
                    outputPath: 'dist/assets/pics/'
                  }
               },
                {
                  // epub files
                  test:/\.epub$/i,
                  loader: 'file-loader',
                  exclude: /node_modules/,
                }
              ],
            },
            node: {
              __dirname: false,
              __filename: false
            },
            experiments: {
              asyncWebAssembly: true,
              syncWebAssembly: true,
              topLevelAwait: true
            },
                // filename: This is the cornerstone parameter, which distingues different html templates
                // Because for each template, html-webpack-plugin produces, if not otherwise specified in filename,
                // an index.html file.
            plugins: [
              new HtmlWebpackPlugin({
                filename: 'index.html',
                template: './src/app/index.html',
                inject:'body',
                chunks: ['app'],
              }),
              new HtmlWebpackPlugin({
                filename: 'index_A.html',
                template: './src/app_A/index_A.html',
                inject: 'body',
                chunks: ['app_A']
              }),
              new HtmlWebpackPlugin({
                filename: 'index_B.html',
                template: './src/app_B/index_B.html',
                inject: 'body',
                chunks: ['app_B']
              }),
              new HtmlWebpackPlugin({
                filename: 'index_C.html',
                template: './src/app_C/index_C.html',
                inject: 'body',
                chunks: ['app_C']
              }),
              new HtmlWebpackPlugin({
                filename: 'index_D.html',
                template: './src/app_D/index_D.html',
                inject: 'body',
                chunks: ['app_D']
              }),
              new HtmlWebpackPlugin({
                filename: 'index_E.html',
                template: './src/app_E/index_E.html',
                inject: 'body',
                chunks: ['app_E']
              }),
              new HtmlWebpackPlugin({
                filename: 'index_F.html',
                template: './src/app_F/index_F.html',
                inject: 'body',
                chunks: ['app_F']
              }),
              new HtmlWebpackPlugin({
                filename: 'index_G.html',
                template: './src/app_G/index_G.html',
                inject: 'body',
                chunks: ['app_G']
              }),
              new HtmlWebpackPlugin({
                filename: 'index_webpdf.html',
                template: './src/app_webpdf/index_webpdf.html',
                inject: 'body',
                chunks: ['app_webpdf']
              }),
              new HtmlWebpackPlugin({
                filename: 'viewer.html',
                template: './src/lib/pdfjs-dist/web/viewer.html',
                inject: 'body',
                chunks: ['app_viewer']
              }),
              new HtmlWebpackPlugin({
                filename: 'index_trial.html',
                template: './src/app_A/index_trial.html',
                inject: 'body',
                chunks: ['index_trial']
              }),
              new MiniCssExtractPlugin({
                filename: '[name].css',
                chunkFilename: '[id].css',
                linkType: 'text/css',
              }),
              new MiniCssExtractPlugin({
                filename: './src/lib/conversejs/converse.css'
              }),
              new CopyPlugin({
                patterns: [
                  {
                    from: path.resolve(__dirname, "./src/lib"),
                    to: path.resolve(__dirname, "./dist/lib")
                  },
                  {
                    from: path.resolve(__dirname, "./src/assets/css"),
                    to: path.resolve(__dirname, "./dist/assets/css")
                  },
                  {
                    from: path.resolve(__dirname, "./src/assets/pics"),
                    to: path.resolve(__dirname, "./dist/assets/pics")
                  },
                  {
                    from: path.resolve(__dirname, "./src/assets/geojson"),
                    to: path.resolve(__dirname, "./dist/assets/geojson")
                  },
                  {
                    from: path.resolve(__dirname, "./src/assets/svg"),
                    to: path.resolve(__dirname, "./dist/assets/svg")
                  },
                  {
                    from: path.resolve(__dirname, "./src/assets/epub"),
                    to: path.resolve(__dirname, "./dist/assets/epub")
                  },
                  {
                    from: path.resolve(__dirname, "./node_modules/onnxruntime-web/dist/*.wasm"),
                    to: path.resolve(__dirname, "[name][ext]")
                  },
                  {
                    from: path.resolve(__dirname, "./src/assets/onnx"),
                    to: path.resolve(__dirname, "./dist/assets/onnx")
                  }
                ],
                options: {
                  concurrency: 100,
                },
              }),
            ]
        }
        
        //module.exports = [ main_config, renderer_config];
        module.exports = [
          main_config,
          renderer_config,
        ];

Microsoft's ONNX people suggested this: `"If you still cannot solve this issue, you need to dig deep into webpack to find the root cause. With imported value ort being undefined, there is little thing I can help in this stage"`

So.... what else has to be included and / or modify in the `webpack.config.js` file, in order to make `webpack` correctly see and load `onnxruntime-web` ?

Other info:

    "copy-webpack-plugin": "^7.0.0"
    "css-minimizer-webpack-plugin": "^1.2.0",
    "fork-ts-checker-webpack-plugin": "^6.1.0",
    "html-webpack-plugin": "^5.1.0",
    "node-polyfill-webpack-plugin": "^1.0.2"
    "webpack": "^5.23.0",
    "webpack-bundle-analyzer": "^4.4.0",
    "webpack-cli": "^4.5.0"
    node: v16.13.0
    O.S.: Ubuntu 20.04 Desktop

Looking forward to your kind help

**Comment by alexander-akait** [comment]
Please use the issue template

**Comment by raphael10-collab** [comment]
I close this question and open another one with `issue template`
