### ISSUE TITLE
Webpack+babel produces code that is suboptimal for minification

### ISSUE THREAD

**Issue by jimbolla** [webpack/webpack#1544]
For example, if I have the js:

```javascript
    import React, {PropTypes} from "react";

    import Branding from "./Branding";

    const Layout = ({children, customSignIn}) => (
        <div className="container" style={{marginTop: 60}}>
            <div className="well" style={{padding: 50}}>

                <div className="panel-body">
                    <div className="col-lg-6" style={{textAlign: "center"}}>
                        <Branding customSignIn={customSignIn} />
                    </div>
                    <div className="col-lg-6">
                        {children}
                    </div>
                </div>
            </div>
        </div>
    );

    Layout.propTypes = {
        children:     PropTypes.node,
        customSignIn: PropTypes.string,
    };

    export {Layout as default};
```

Webpack+babel produces:

```javascript
    "use strict";
    
    Object.defineProperty(exports, "__esModule", {
        value: true
    });
    
    function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { "default": obj }; }
    
    var _react = __webpack_require__(3);
    
    var _react2 = _interopRequireDefault(_react);
    
    var _Branding = __webpack_require__(283);
    
    var _Branding2 = _interopRequireDefault(_Branding);
    
    var Layout = function Layout(_ref) {
        var children = _ref.children;
        var customSignIn = _ref.customSignIn;
        return _react2["default"].createElement(
            "div",
            { className: "container", style: { marginTop: 60 } },
            _react2["default"].createElement(
                "div",
                { className: "well", style: { padding: 50 } },
                _react2["default"].createElement(
                    "div",
                    { className: "panel-body" },
                    _react2["default"].createElement(
                        "div",
                        { className: "col-lg-6", style: { textAlign: "center" } },
                        _react2["default"].createElement(_Branding2["default"], { customSignIn: customSignIn })
                    ),
                    _react2["default"].createElement(
                        "div",
                        { className: "col-lg-6" },
                        children
                    )
                )
            )
        );
    };
    
    Layout.propTypes = {
        children: _react.PropTypes.node,
        customSignIn: _react.PropTypes.string
    };
    
    exports["default"] = Layout;
    module.exports = exports["default"];
```

Notice all the instances of `_react2["default"]`... these don't minify well because the "default" is not minified. What would be better would be if webpack added a `var _reactDefault = _react2["default"];` declaration at the top and used that instead.

Notice it also "inlined" my PropTypes definition and the usage became `_react.PropTypes`. Again, this is less minifiable than if it had generated `var _reactPropTypes = _react.PropTypes`.

This pattern isn't specific to React, but React code certainly suffers greatly from it.

**Comment by chemzqm** [comment]
It looks a jsx issue, jsx complier should optimize that

**Comment by SimenB** [comment]
This isn't a webpack issue though, it's a babel one

**Comment by taurose** [comment]
Afaik the reason you get this ugly looking code is that ES6 modules [export bindings](http://www.2ality.com/2015/07/es6-module-exports.html). If it were to compile as you suggested this code wouldn't work ([source](http://www.2ality.com/2014/09/es6-modules-final.html#cyclic_dependencies_in_ecmascript_6)):

```js
//------ lib.js ------
export let counter = 0;
export function inc() {
  counter++;
}
    
//------ main.js ------
import { inc, counter } from 'lib';
console.log(counter); // 0
inc();
console.log(counter); // 1
```

I don't think it matters much after gzip though.

**Comment by jimbolla** [comment]
@chemzqm @SimenB I assumed it was webpack due to the variable names. I'll post a babel issue.

@taurose That code *shouldn't* work. `counter` should be a constant reference. `import` is supposed to be static. My understanding of es2016 import/export, based on [this post](http://www.2ality.com/2014/09/es6-modules-final.html), is that the imports and exports are considered static and eligible for "compile time" optimization.

**Comment by cesarandreu** [comment]
@jimbolla That code does and *should* work. Those are live bindings. `counter` is not a constant reference. It's still a static import and perfectly valid.

**Comment by jimbolla** [comment]
Yep. Read up on it. That's the "correct" behavior. Case closed.
