### ISSUE TITLE
Module Federation block loading app

### ISSUE THREAD

**Issue by ar53n** [webpack/webpack#15441]
# Bug report

**What is the current behavior?**

Hello there is a problem with playwright testing in synchronous mode. 

I have entry file `bootstrap.js` with content
```
import('./app.js')
```

I also have a federation module that is loaded on the `/demo` page. But in synchronous mode, the application does not start without loading `remoteEntry.js` and any e2e tests

I can't test my main page without loading `remoteEntry.js`

My Demo app structure with sync imports from module federations
<img width="748" alt="image" src="https://user-images.githubusercontent.com/7085102/155534598-fc0f692a-fea1-44ab-b747-fce9df35c6c3.png">

**If the current behavior is a bug, please provide the steps to reproduce.**
https://github.com/module-federation/module-federation-examples

1. Clone repo
2. run complete-react-demo
3. Block remoteEntry url in devtools

**What is the expected behavior?**

Allow to mock modules and not block loading without  `remoteEntry.js`
If I understand correctly, this PR can solve some problems
https://github.com/webpack/webpack/pull/15271

**Other relevant information:**
webpack version:  ^5.51.1
Node.js version: 14.15.1
Operating System:  MacOS
Additional tools: **jest**, **playwright**

**Comment by innManish** [comment]
@ar53n ,
see my pull req,
helped or not

**Comment by vankop** [comment]
not sure what webpack should do here... I think you should handle this in your test case ( e.g. wait loading remoteEntry in your test case )
