### ISSUE TITLE
`BannerPlugin` does not work as expected with `watch: true` and `mode: 'development'`

### ISSUE THREAD

**Issue by BrokenSourceCode** [webpack/webpack#15447]
# Bug report

**What is the current behavior?**

Hi,

The issue occurs with `watch: true` and `mode: 'development'`. This **causes a serious PERFORMANCE PROBLEM** when we have many entry points like me (build during watching takes ~60s instead of ~2s).

Please note that, in my example, the files don't import each other.

**WITHOUT** the `BannerPlugin` plugin, only the changed file is emitted: this is the expected behavior. On the screenshot (step 2), you can see that I have only changed the file `view/test/a.js` and only `view/test/a.js` has been emitted.

![without_banner_plugin](https://user-images.githubusercontent.com/59090546/155859334-e795484a-9df5-4cd4-912e-330b3611919f.png)

**WITH** the `BannerPlugin` plugin, all files are emitted when a single file is changed: this **ISN'T** the expected behavior. On the screenshot (step 2), you can see that I have only changed the file `view/test/a.js` and both `view/test/a.js` and `view/test/b.js` have been emitted.

![with_banner_plugin](https://user-images.githubusercontent.com/59090546/155859348-830cb204-82b2-429d-a30e-fb9afd5ad713.png)

Results:
| `BannerPlugin` enabled | Emitted files    | Is expected behavior? |
|------------------------|------------------|-----------------------|
| NO                     | The changed file | YES                    |
| YES                    | All files        | NO _(ISSUE !!!)_                |

**If the current behavior is a bug, please provide the steps to reproduce.**

You can use [this repository](https://github.com/BrokenSourceCode/webpack-bannerplugin-issue) that I created on purpose to reproduce the bug. Please comment [this line](https://github.com/BrokenSourceCode/webpack-bannerplugin-issue/blob/main/webpack.config.js#L17) if you want to get the expected behavior.

`webpack.config.js`:
```js
import path from 'path';
import webpack from 'webpack';
import WebpackBar from 'webpackbar';

export default {
	mode: 'development',
	devtool: 'source-map',
	watch: true,
	entry: {
		'view/test/a': path.resolve('view/test/a.js'),
		'view/test/b': path.resolve('view/test/b.js')
	},
	output: {
		path: path.resolve('./dist')
	},
	plugins: [
		new webpack.BannerPlugin({banner: 'My license'}), // If we comment this line, we get the expected behavior.
		new WebpackBar({
			reporters: [
				'fancy',
				'stats'
			]
		})
	]
};
```

**What is the expected behavior?**

**WITH** the `BannerPlugin` plugin, only the changed file should be emitted (exactly like without the plugin).

**Other relevant information:**
webpack version:  5.69.1
Node.js version: 16.13.2
Operating System: Windows 10

**Comment by sokra** [comment]
Yep, we need a WeakMap cache in the BannerPlugin. Maybe `WeakMap<Source, { comment: string, result: Source }>`.
