### ISSUE TITLE
After starting webpack serve, the name of the grandpa folder of the file cannot be modified？

### ISSUE THREAD

**Issue by banli17** [webpack/webpack#15452]
For example, I have a src/a/b/index.js file with webpack configured as follows.

After starting webpack serve, I can modify the b directory name, but I can't modify the a's name, vscode will prompt no permission.

![image](https://user-images.githubusercontent.com/12556069/155925237-8710e36b-a0fc-4a45-8f72-aaf9ad7421fb.png)

![image](https://user-images.githubusercontent.com/12556069/155925447-94e4b9ce-c498-4c9c-9e13-b977c4ef8142.png)

**webpack.config.js**
```js
const path = require('path')

module.exports = {
	entry: {
		index: path.resolve(__dirname, './packages/a/b/index.js'),
	},
	output: {
		path: path.resolve(__dirname, 'dist'),
		filename: '[name].bundle.js'
	}
}

```

package.json webpack versoin

```
{
  "name": "test-webpack",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "dev": "webpack serve"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "webpack": "^5.69.1",
    "webpack-cli": "^4.9.2",
    "webpack-dev-server": "^4.7.4"
  }
}
```

**Comment by alexander-akait** [comment]
You don't have permission to do it, please check your user, maybe you run webpack under other user (root/admin?), I can't reproduce it, also please use the issue template in future
