### ISSUE TITLE
what is the timeline for the release of webpack 2?

### ISSUE THREAD

**Issue by benmonro** [webpack/webpack#1545]
I'm looking forward to using this feature: https://github.com/webpack/webpack/tree/webpack-2/examples/harmony-unused

but since this is in the webpack 2 branch, i'm curious as to when this will be released?  what is the timeline?  

Thanks
Ben

**Comment by killswitch** [comment]
:+1:

**Comment by sokra** [comment]
Soon...

**Comment by killswitch** [comment]
@sokra's reaction: ![](http://i.imgur.com/C0zqFPx.jpg)

**Comment by sokra** [comment]
yeah.

I don't have a timeline yet. I depends on the available time for webpack.

**Comment by killswitch** [comment]
One of my favorite new features, don't feel pressured, I am anxious for it. Thanks for all the hard work you do.

**Comment by igl** [comment]
Recently saw this in http://rollupjs.org/. This kind of dead-code removal coming to webpack is awesome!

But where to we get our uncompiled es6 libraries?
npm won't have it until es6-module support is in v8 for a few versions. Nodes new LTS strategy does not help there.
JSPM focuses on browsers..
I guess that only leaves: sokra needs to hack something together there too ;)

**Comment by andrew-w-ross** [comment]
Is there a roadmap for what needs to be completed before 2 can come out?

**Comment by sokra** [comment]
Here is a list of my notes: https://docs.google.com/document/d/1tRc0MzvRdGK7EbG2LRW8vSyoxKhR_EvRUz3AQRyFZso/edit?usp=sharing

**Comment by andrew-w-ross** [comment]
@sokra Thanks, what would you like help with?

**Comment by sokra** [comment]
You could prepare a PR to the webpack-dev-server which removes the `iframe` mode and only uses the inline mode. Merge it with the PR about webworkers.

**Comment by moostad** [comment]
@sokra Any update about this topic? why webpack doesn't have blog?

**Comment by Delagen** [comment]
@moostad I cannot get it work with the base loader as source-map-loader. So it is unusable in this state. 1.13 works fine, but es6 is needed ASAP

**Comment by sokra** [comment]
ASAP... :-O

**Comment by Delagen** [comment]
I was trying to use beta, but it not usable in this state, alpha versions of another products more usable

**Comment by kristian-puccio** [comment]
I mean seriously given how much we are paying for this, I would expect
better!

**note: sarcasm**

**Comment by andrew-w-ross** [comment]
@kristian-puccio Yeah when I pay nothing for something I expect results.

**Comment by bbottema** [comment]
I would probably pay if there was some kind of crowdfunding to get a new release done!

**Comment by 5loop** [comment]
@bbottema There's a link to tip on the repo page :)

**Comment by sokra** [comment]
There propably will be some crowdfunding in the near future. I need to work at least part time on webpack to cope with the demands...

**Comment by joshmanders** [comment]
Webpack is great, please let us know when and where we can donate, I have no issues helping you out, you've taken a crap ton of time off my work plate with this.

**Comment by brianblakely** [comment]
I'm a little surprised that Facebook hasn't gotten more deeply involved, considering how common it is for React and Webpack to be used together.

**Comment by KingScooty** [comment]
Is there an upgrade doc for upgrading to webpack2? Proxying, and React hot loading has completely broken on me, and i'm struggling to figure out why :(

**Comment by andreicek** [comment]
@sokra any updates on the crowdfunding funding?

**Comment by shubhamsizzles** [comment]
It would be great to get sense of what's blocking webpack's transition from beta to stable. 

We understand that its gone through a fundamental rewrite, and a lot of great effort has gone into the 13 beta revisions that have taken place in slighly less than a year now, but we are hoping for some transperancy leading to 2.0 release.

The roadmap docs don't seem to be updated any longer, and documentation for 2.0 is insufficient at best. It would be helpful if there was a short blog post / github post outlining a roadmap.

**Comment by matteocng** [comment]
@andreicek +1, crowdfunding v2 would be great!

**Comment by graingert** [comment]
@igl jsnext:main

**Comment by pmorch** [comment]
We're about to embark on Webpack, and can see that Webpack 2 is "any day now". In the meantime, we'll use Webpack 1 of course. 

I'm assuming that with a new major version number will come breaking changes. 

Does the team already know what will break in a version 1 => 2 migration? Are there any hints as to any Webpack 1 idioms or approaches one should either employ or avoid because they'll help/give problems later with Webpack 2?

**Comment by cecilemuller** [comment]
This is not an exhaustive list, but if it helps, I recently [updated one of my boilerplates to webpack2](https://github.com/wildpeaks/webpack2-es2015-boilerplate), so what I had to change was just:
 - the version number of packages `webpack`, `webpack-dev-server` and `extract-text-webpack-plugin`
 - replaced custom commandline flags by --env parameters
 - removed the script and link tags from the HTML template

So far, the transition was pretty smooth :)

**Comment by bholloway** [comment]
@pmorch It does depend on the plugins/loaders you intend to use.

I maintain a couple and have had feedback that they are not Webpack 2 compatible. In my new job I am not dog-fooding so I've not yet looked into the migration process.

**Comment by mkscrg** [comment]
Is there an updated timeline for a stable v2 release? Alternatively, is there a list of issues/bugs for would-be contributors to jump on?

Also +1 for crowdfunding webpack—it's become an important piece of infrastructure!

**Comment by tjoskar** [comment]
Correct me if I'm wrong but I think it's mostly documentation left: https://github.com/webpack/webpack.js.org/issues?q=is%3Aopen%20is%3Aissue%20milestone%3A%22Webpack%202%20-%20Documentation%20MVP%22

And some bugs: https://github.com/webpack/webpack/milestone/9

**Comment by ChrisCinelli** [comment]
This coming Sunday is the first birthday of this issue =)
@sokra commented "soon..." on Oct 26, 2015.

But it looks like there are still some big issues outstanding now that we are at `beta 25`. 

I think some people early this year were thinking that we were close to stable release. 
I saw that some plugins were releasing a new version for webpack 2. I saw some boilerplates rushing to upgrade to webpack 2. I started a project with a boilerplate that used v2. But as time went by, people realized that we may still far from a stable v2 .

So getting pragmatic: 

I am having some problems with dependencies every once in a while. My hope to see everything working soon are pretty low. But before I spend a few days on this, I want to ask it.

Should I wait just a little more or I should I downgrade to v1 in the meanwhile?

**Comment by joshmanders** [comment]
ping @TheLarkInn

**Comment by TheLarkInn** [comment]
Omg, you guys are so funny. Okay, so we stuck to our word posted on various mediums that when our [doc milestone is completed](http://github.com/webpack/webpack.js.org/milestone/1).

So we are at 84% and there is a little bit of work left, but the more help we have from you in the effort, the faster you get webpack v2.

**Comment by TheLarkInn** [comment]
> But it looks like there are still some big issues outstanding now that we are at beta 25.

What issues were you referring to? Besides one change, (in regards to adding `import()` for the loader spec).

**Comment by corysimmons** [comment]
1) Just use Webpack 2 right now. Who cares if it's perfect? It works and you'll know if it breaks something. I've heard from plenty of people they've been using it for a while.
2) Just super hyped about dead code elimination? Use Rollup or Closure Compiler?

It's not like you guys won't see "WEBPACK 2 LAUCNH D OMG!!!" on every site for a week when it finally lands.

Lock thread and have pizza party instead. :\

**Comment by bbottema** [comment]
@corysimmons Some of us are actually professionals. I'm not going to push our enterprise projects with 20 developers into "yet another tool" that might go extinct the next month. Switching to Webpack 1 already was dicey enough. I just got our devs used to it.

What I need is an actively developed tool with lots of documentation and an active community. Webpack 2 isn't any of that.

**Comment by pastelsky** [comment]
@bbottema
Your being an enterprise user matters very little in the context of an open source project. You aren't paying for these tools and hence it's silly to demand  hard ETA'S and enterprise level documentation.
Why don't you and your enterprise try contributing to the blockers instead?

**Comment by bbottema** [comment]
@pastelsky wow, are you seriously suggesting enterprise only have rights to rely on paid projects? How do you think Angularjs got so much traction. Excluding large enterprise users from open source dialogs this way is *not* the way forward. And as I said earlier in this thread, I would gladly help pay for extra focused man hours if there was some kind of crowd funding going on. But no, I don't have the freedom nor the power to direct our own personel to external projects. I don't think that surprises anyone. It's not like we can't do it without gulp. There's no real business case there other than making our developers happy and hopefully more productive.

**Comment by fab1an** [comment]
Okay, the way I see it, please correct me if I'm wrong, is that many people would like to contribute to get webpack 2 finished.

The problem seems to be that the missing part is mainly documentation, which is harder to get into than actual code. Because you need to fully understand what the code does to be able to document it, am I right?

If not, are there areas other than documentation that need polishing or testing?

**Comment by fab1an** [comment]
@bbottema I would stay with webpack 1 for now. There's babel-minify (https://babeljs.io/blog/2016/08/30/babili) around the corner as well, which might provide another way towards treeshaking and the minification of ES2015.

**Comment by TheLarkInn** [comment]
> What I need is an actively developed tool with lots of documentation and an active community. Webpack 2 isn't any of that.

@bottema we have almost finished our MVP docs milestone. webpack.js.org is the newest page and we have our migration guide under the how to section. 

Is there anything else you are referring to that you would like to see?

**Comment by corysimmons** [comment]
@TheLarkInn It might be a good idea to slap that webpack.js.org link on the top of Webpack's README with some label like "Looking for Webpack 2 (still in beta) documentation?"

**Comment by joshmanders** [comment]
@bbottema 

>  into "yet another tool" that might go extinct the next month.

Webpack has proven itself that it won't "go extinct the next month." So that argument is moot.

> What I need is an actively developed tool with lots of documentation and an active community. Webpack 2 isn't any of that.

Yeah man, webpack is not an active community and no documentation. 🙄 

> Excluding merges, **10 authors** have pushed **14 commits** to master and **23 commits** to all branches. On master, **61 files** have changed and there have been **6,591 additions** and **1,758 deletions**.

Get off your horse, this attitude is what drives great open source developers away, your entitlement is not needed or wanted here. There is no rush for webpack 2, if you think there is, by all means, dig in and contribute, otherwise keep your trap shut.

**Comment by corysimmons** [comment]
https://youtu.be/nSipYY933eU?t=52

**Comment by fab1an** [comment]
Wow, I haven't seen such rude communication in a github-issue for quite some time. Could you please stop telling each other off?

**Comment by TheLarkInn** [comment]
@corysimmons we are actively working on having that done. 

@joshmanders by all means I appreciate the support and statistics. Currently working for a Fortune 500 insurance company myself, I understand the Enterprise Architecture awareness that @bbottema is coming from and do not take it personally. (Although we are all professionals here and this is not the place to question otherwise.)

I would like to answer or reassure @bbottema if I can about any information or questions if he has them (therefore I have not locked the thread). 

So I ask you all kindly please to not attack or question each other for whatever reason. Rather, **let me help answer the questions that he has.** 

> And nobody is demanding anything (are you trolling). All I did was voicing a thumbs up and suggesting a crowd funding might help move things along.
> As I said earlier in this thread, I would personally gladly help pay for extra focused man hours if there was some kind of crowd funding going on. But no, I don't have the freedom nor the power to direct our own personel to external projects. I don't think that surprises anyone. It's not like we can't do it with Gulp instead. There's no real business case there other than making our developers happy and hopefully more productive.

In fact we just released and announced from our [latest medium publication](https://medium.com/webpack) that we are now apart of open collective. This is a free and trackable way to donate to our causes: http://opencollective.com/webpack. I hope that answers that question @bbottema. We are always looking for sponsorship, etc. 

If you would be willing to take the time to do so, I would strongly encourage you to look at [our new doc page](webpack.js.org), and then please submit any [github issues for where you believe documentation is lacking](https://github.com/webpack/webpack.js.org/issues/new).

**Comment by joshmanders** [comment]
I apologize, it just bothers me when hard working people are giving their free time to make all our lives easier and better get bossed around and told what to do by entitled people. I don't care if you're enterprise or a solo developer. Nobody and I NOBODY has the right to talk with such a tone towards open source developers. We all should be grateful for the work you're doing for us.

I personally feel if they can speak that way towards others, then they should not be avoided being spoken back to that way.

**Comment by TheLarkInn** [comment]
I agree and we will leave it at that please and thank you.

**Comment by bbottema** [comment]
I'm not bossing around anyone nor demanding anything. Why the poisonous tone, guys? I'm an open source developer myself, check my history so I know very well what it means to maintain an open source project. I'm also an external contractor with enterprise sized clients, so I also know what how that angle plays out. Webpack 1 is awesome and I'm rooting for Webpack 2. I wish to leave it at that, I have no need to wage some proxy war on behalf of enterprise or OS developers such as myself.

**Comment by TheLarkInn** [comment]
Alright, again. Any more responses on this and non-webpack related issues I will close the thread. We all get our intentions were not to be malicious. Last warning

**Comment by TheLarkInn** [comment]
@bbottema Do you have _any other questions_ in regards to webpack 2's release, and has it not been stated clearly?

**Comment by bbottema** [comment]
Please close this down. I've had enough.

**Comment by TheLarkInn** [comment]
Ill leave the issue open for anyone else who has questions. Thank you for the timely response.

**Comment by turadg** [comment]
> Okay, so we stuck to our word posted on various mediums that when [our doc milestone](https://github.com/webpack/webpack.js.org/milestone/1) is completed.

It may help to update https://webpack.github.io/docs/roadmap.html to indicate that? When I search for "webpack 2", it's the first hit. And that pages says,
> (for the most up to date version see https://docs.google.com/document/d/1tRc0MzvRdGK7EbG2LRW8vSyoxKhR_EvRUz3AQRyFZso/edit?pli=1)

That gives a very different answer. For example, implying a block on two open issues. Is that Google Doc authoritative anymore?

It might be helpful to answer these on an authoritative FAQ page:
1. When will Webpack 2.0 be released?
2. How can I help Webpack 2.0 to be released sooner?
3. What parts of Webpack 2.0 are lacking documentation?

**Comment by sokra** [comment]
1. We will announce it 1 week beforehand. This year. There are some critical issues left in the core and the documentation must reach a minimum quality. Some loaders need to be updated to use webpack 2 features and reflect webpack 2 changes in documentation (could be finished after the release).
2. easiest way is to help with the new documentation. It doesn't need to be a perfect contribution. We review the PRs and will do a review of the complete documentation before release.
3. https://github.com/webpack/webpack.js.org/projects/1 and https://github.com/webpack/webpack.js.org/issues or just try to read the documentation at https://webpack.js.org/ and check what's missing (create issue)

**Comment by ChrisCinelli** [comment]
Awesome! Thanks @sokra and @TheLarkInn for the updates. 
I echo what was said here: https://github.com/webpack/webpack/issues/1545#issuecomment-255601410

I think people could help with documentation, but they need to know it and know how to do it.
I think step 1 is to make sure that it is clear what the status is and what need to be done. And this without having to go through a few google searches and read multiple issues on Github like this with about 50 or more comments.

My suggestions:

1. Establish a place that is the source of truth for Webpack 2 status. To me a page on https://github.com/webpack/webpack/wiki seems the easier place where people can keep things updated without to much overhead. This page can have direct links to drill down specific aspects. For example: "How to help with Webpack 2", "I am the author of a loader or plugin, what do I need to do", etc.

2. Make sure that it is clear where the source of truth is and it is easy to find it. This is what I get from Google: 
<img width="1053" alt="search weppack 2 on google" src="https://cloud.githubusercontent.com/assets/153101/19629839/5305367c-9932-11e6-8bba-5324ff472a4c.png">

This is what the first result look like:
<img width="1095" alt="webpack roadmap" src="https://cloud.githubusercontent.com/assets/153101/19629840/55b254f4-9932-11e6-9a80-4e00e0438481.png">

This is the doc:
<img width="997" alt="todo webpack 2" src="https://cloud.githubusercontent.com/assets/153101/19629847/916da6ba-9932-11e6-8847-6cd6cf45128f.png">

I have not seen any update on these links for a while. The perception is that there is that webpack 2 is stuck.

Can the roadmap and the google doc point to the same place where things are kept updated?

3. There is a huge dependency problem currently if people do not fix the version in their `package.json`.  Any thing that uses `^` or `~` starts breaking every now and then. 
I think there should be a clear guidance  to help people and plugin author to fix the dependency problems. Having kept webpack in `beta` for one year with breaking changes from a beta version to the other did not help. Can you guys adopt [Semver](http://semver.org/) ?

**Comment by Luchillo** [comment]
Hi @ChrisCinelli, i took a look at the roadmap and this is what it shown:
![image](https://cloud.githubusercontent.com/assets/9698639/20395932/8ebcb684-acb2-11e6-8c80-06863100571f.png)

It says the new docs are in https://webpack.js.io, however the wiki says it should be https://webpack.js.org/, who should i let know about it to get it fixed? i banged my head to the wall a few times before taking a look to the wiki (thanks to your comment above).

**Comment by bjornstar** [comment]
[The milestone](https://github.com/webpack/webpack.js.org/milestone/1) looks cleaned out and things sound pretty stable.

Looking forward to the release of Webpack 2!

**Comment by sokra** [comment]
https://github.com/webpack/webpack/milestone/9

and we still want to review the docs

but we are nearly there. Expect a Release Candidate this year... :christmas_tree: :fireworks:

**Comment by bebraw** [comment]
We are running RCs now. Probably time to close this issue.
