### ISSUE TITLE
require.context with folders

### ISSUE THREAD

**Issue by iliakan** [webpack/webpack#1546]
I have the following structure:

```
routes/
  about/
    index.js
  home/
    index.js
```

Say I need to require `about`. Guess, it should be like that:

``` js
let context = require.context('./routes', true);
let route = context('./about');
```

Unfortunately, that doesn't work, `./about` not found.

The map in the context module looks like this:

``` js
var map = {
    "./about/index": 2,
    "./about/index.js": 2,
    "./home/index": 3,
    "./home/index.js": 3
};
```

So I need to call `context('./about/index')` to require the module.

Is there a sane way to make the map look like this?

``` js
var map = {
  "./about": 2,
  "./home": 3
};
```

P.S. I checked `ContextModuleFactory` and it seems, there isn't :(

**Comment by bebraw** [comment]
Maybe it would be sensible to write a custom function that does the mapping for you? Idea:

```javascript
let req = require.context('./routes', true);
let route = resolveIndex(req, './about');

...

function resolveIndex(req, page) {
  // you can make this more robust by checking against req.keys() perhaps
  return req(page + '/index.js');
}
```

**Comment by singggum3b** [comment]
upvote?

**Comment by rainboxx** [comment]
I'd also vote her. The context map should contain the directory as well.

**Comment by roshecode** [comment]
+

**Comment by iliakan** [comment]
Bugs just get closed, not fixed?

**Comment by roshecode** [comment]
@montogeek sorry, I don't know how but I missed the sentence `If you think this is still a valid issue, please file a new issue with additional information.` :confused: 

@iliakan seems it is not fixed, but I should open a new issue for that :grinning:

**Comment by iliakan** [comment]
@roshecode you using WP4?

**Comment by roshecode** [comment]
@iliakan 4.8.2
