### ISSUE TITLE
Both module and import field in exports field are resolved for same library

### ISSUE THREAD

**Issue by huozhi** [webpack/webpack#15484]
# Bug report

Both "module" export and "import" export of exports field are resolved in duplication.

**What is the current behavior?**

3rd party lib swr's output assets are resolved in different cases:

* When swr is imported, it resolves to `swr/dist/index.esm.js`
* Then subpath import `swr/infinite` is imported, which is relying on `swr`
* Then swr is resolved in 2nd time, but now `swr/dist/index.mjs` is resolved

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/beeebox/webpack-esm-duplicated-resolve

yarn start
browser should open on localhost:3000
open devtools and search "swr"
you'll see `swr/dist/index.esm.js` and `swr/dist/index.mjs` are both resolved there

**What is the expected behavior?**

`swr/dist/index.mjs` or `swr/dist/index.esm.js` is resolved only all the time

**Other relevant information:**
webpack version: v5.70.0
Node.js version: v14.17.0
Operating System: MacOS 12.0.1
Additional tools:

**Comment by vankop** [comment]
You have wrong babel configuration. After `babel-loader` run `Test.component.js` looks like this
```js
"use strict";

function _typeof(obj) { "@babel/helpers - typeof"; return _typeof = "function" == typeof Symbol && "symbol" == typeof Symbol.iterator ? function (obj) { return typeof obj; } : function (obj) { return obj && "function" == typeof Symbol && obj.constructor === Symbol && obj !== Symbol.prototype ? "symbol" : typeof obj; }, _typeof(obj); }

require("core-js/modules/es.array.iterator.js");

require("core-js/modules/es.object.to-string.js");

require("core-js/modules/es.string.iterator.js");

require("core-js/modules/es.weak-map.js");

require("core-js/modules/web.dom-collections.iterator.js");

require("core-js/modules/es.object.get-own-property-descriptor.js");

require("core-js/modules/es.symbol.js");

require("core-js/modules/es.symbol.description.js");

require("core-js/modules/es.symbol.iterator.js");

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = NewsAppStart;

var _react = _interopRequireDefault(require("react"));

var _swr = _interopRequireWildcard(require("swr"));

var _infinite = _interopRequireDefault(require("swr/infinite"));
...
```
So in case of require `module` export name is used in [exports field](https://nodejs.org/api/packages.html#main-entry-point-export) (result to `esm.js` resolve). In case of resolving `swr` in `swr/infinite` `import` export name is used since it uses `import {} from 'swr'` (result to `mjs` resolve)

**Comment by huozhi** [comment]
Thanks @vankop! Looks like removing `@babel/plugin-transform-modules-commonjs` works
