### ISSUE TITLE
Split Chunks optimisation breaks web workers

### ISSUE THREAD

**Issue by danielannan17** [webpack/webpack#15485]
# Bug report

**What is the current behavior?**
When you turn on the split chunks optimisation, workers which are created from a worker script are not able to receive and possibly send messages. Removing the split chunks optimisation from the webpack config restores the functionality however common dependencies will be included in both scripts.

**If the current behavior is a bug, please provide the steps to reproduce.**
Create a webpack config which uses the splitChunk optimisation
Have 2 output files generated, 1 to be used as a worker script, another which has the same dependencies so the common dependencies are split out.
In another module, create a web worker from the worker script.

Additional Info
I'm creating the the worker in a different package.
E.g. Module A has the sendData function below which uses the outputted worker.min.js from module B to created the web worker

Module A
```
  async sendData(data) {

    let worker = new Worker(new URL('second-mod/dist/umd/worker.min.js', import.meta.url));

    return new Promise(function (resolve, reject) {
        worker.onmessage = function (event) {
        if (event.data != null && event.data.error) {
          reject(event.data.error);
        } else if (event.data != null) {
          resolve(event.data);
        }
        worker.terminate();
      };

      worker.onerror = function (error) {
        reject(error);
        worker.terminate();
      };

      worker.postMessage(data);
    });
  }
```
Module B
webpack config
```
{
      name: 'base',
      plugins: [new NodePolyfillPlugin()],
      module: {
        rules: [
          // Process JS with Babel.
          {
            test: /\.(js|jsx|mjs)$/,
            loader: require.resolve('babel-loader')
          }
        ]
      },
      optimization: {
        minimize: true,
        minimizer: [new TerserPlugin({
          extractComments: false,
        })],
        splitChunks: {
          chunks: 'all',
        }
      },
    },
    {
      name: 'prod',
      mode: 'production',
      entry: {
        worker: { import: './src/worker.js', filename: './umd/worker.min.js' },
        main: { import: './src/index.js', filename: './umd/main.min.js', library: {
          name: 'examplelib',
          type: 'umd'
        } },
      }
    }
```
which are combined using `webpack --config-name base --config-name prod --merge`

worker.js
```
self.onmessage = function (event) {
  console.log('got message')
}
```

**What is the expected behavior?**
The web workers should be able to receive messages and execute the relevant code. Both generated scripts should be smaller as their common dependencies are separated.

**Other relevant information:**
webpack version:  5.70.0
Node.js version: v12.22.3
Operating System: macos monterey
Additional tools: React

**Comment by vankop** [comment]
Could you provide full reproducible repo (as small as possible), from your description it is unclear..

**Comment by danielannan17** [comment]
I've created the repo
https://github.com/danielannan17/webpack-recreate/tree/main

**Comment by vankop** [comment]
you don't need to bundle worker first. In webpack@5 you can (and should) use 
```js
 new Worker(new URL('<esm worker script>', import.meta.url))
```
webpack will add `<esm worker script>` as a separate entry point and bundle it.
