### ISSUE TITLE
Package exports - require.context

### ISSUE THREAD

**Issue by MaorDanielD** [webpack/webpack#15495]
Hi,
after upgrading svgr package from version 5.5 to version 6.0.0 I have a problem passing options in require.context
I'm getting an error:

"module not found: Error: Package path ./?{"titleProp":true} is not exported from package ../node_modules/@svgr/webpack (see exports field in ../node_modules/@svgr/webpack/package.json"

(There is exports field in the package.json)

my code:
require.context(@svgr/webpack?{"titleProp":true}![path], true, /.svg$/)

What did I suppose to do?
How should I handle that?

Thanks.

webpack version:  5
Node.js version: 12

**Comment by vankop** [comment]
I think you should ask in `@svgr/webpack` issue tracker. thanks.

**Comment by MaorDanielD** [comment]
I don't think so, this relates to the webpack.

https://webpack.js.org/guides/package-exports/

<img width="832" alt="Screen Shot 2022-03-09 at 16 49 56" src="https://user-images.githubusercontent.com/99175500/157465763-59d4eac5-b849-4bff-be2d-dde710dcd805.png">

**Comment by vankop** [comment]
please create reproducible repo, I will take a look.

**Comment by alexander-akait** [comment]
@vankop problem in `require.context`, we don't know about export so we can't found valid field in `exports`, that is why `context` requests are not good, there is the same issue

**Comment by alexander-akait** [comment]
Let's close in favor https://github.com/webpack/webpack/issues/13865, the root of the problem is the same
