### ISSUE TITLE
sourcemap sources does not support template string

### ISSUE THREAD

**Issue by 2239559319** [webpack/webpack#15490]
# Bug report

**What is the current behavior?**

sourcemap sources property does not convert to chunk name

**If the current behavior is a bug, please provide the steps to reproduce.**
config with follow
![image](https://user-images.githubusercontent.com/34960995/157214085-6f436b65-183a-437e-914b-b63095b2fdfc.png)
get sourcemap with
![image](https://user-images.githubusercontent.com/34960995/157213924-761aee44-d809-4214-8cb1-6eb679c1dd8d.png)

expected entry chunk name

**What is the expected behavior?**

**Other relevant information:**
webpack version:  5.66.0
Node.js version: v14.18.2
Operating System: Debian GNU/Linux 10
Additional tools:

**Comment by cool-little-fish** [comment]
see doc https://webpack.js.org/configuration/output/#outputdevtoolmodulefilenametemplate

**Comment by vankop** [comment]
there is no such replacement, see link above. thanks.
