### ISSUE TITLE
Error when using a regex with managedPaths unless the regex includes a capture group

### ISSUE THREAD

**Issue by SystemParadox** [webpack/webpack#15491]
# Bug report

**What is the current behavior?**

Using a regex with managedPaths results in the following error:

```
Uncaught error TypeError: Cannot read properties of undefined (reading 'length')
    at getManagedItem (node_modules/webpack/lib/FileSystemInfo.js:769:22)
    at checkManaged (node_modules/webpack/lib/FileSystemInfo.js:1992:26)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

```
// webpack.config.js
module.exports = () => ({
    snapshot: {
        managedPaths: [
            /node_modules\/(?!@private\/).*\//,
        ],
    },
});
```

It appears that checkManaged uses `match[1]` when it should be using `match[0]`.

Workaround: Enclosing the entire regex in a capture group fixes it.

**What is the expected behavior?**

A regex in managedPaths should work without a capture group. If for some reason a capture group is actually necessary then it should be clearly documented with an example and an explanation of the reason.

**Other relevant information:**

webpack version:  5.70.0
Node.js version: 16.14.0
Operating System: Linux
Additional tools: N/A

**Comment by SystemParadox** [comment]
This is still an issue.

**Comment by vankop** [comment]
created an issue in docs. https://github.com/webpack/webpack.js.org/issues/6205
_______

Capture group is expected and it is path itself
