### ISSUE TITLE
Option to merge multiple JSON files during compilation when using asset/resource

### ISSUE THREAD

**Issue by andy1547** [webpack/webpack#15502]
## Feature request

**What is the expected behavior?**

I'm currently using the asset/resource module rule to explicitly generate a JSON bundle containing runtime settings (pure JSON - no JS) with the filename "[name].[contenthash].bundle.json". When importing the JSON file in my entry file I'm provided with the hashed filename, which I pass to a window.fetch request to retrieve the JSON content. 

The intent of this JSON file is to serve as appsettings file, allowing runtime settings to be modified after deployment. The browser would always fetch this file during the entry point bootstrapping process. 

I was wondering whether it's possible to combine multiple JSON files into one before generating the asset/resource? For example, if appsettings.dev.json was present, a single JSON bundle would be generated from the combined results of merging appsettings.json and appsettings.dev.json. 

It's not clear whether asset/resource can be chained with other loaders? Originally I was thinking of writing my own loader which transforms the appsettings.json with the dev config (if present) using webpack-merge, however I think I'd need to chain in the file-loader which has been deprecated in v4. 

**What is motivation or use case for adding/changing the behavior?**
I'd like to simplify local development by adding an optional appsettings.dev.json file which is merged with appsettings.json.

**How should this be implemented in your opinion?**
Don't have prerequisite knowledge just yet...

**Are you willing to work on this yourself?**
Don't have prerequisite knowledge just yet...

**Comment by alexander-akait** [comment]
You need custom loader for this, it is out of scope webpack

**Comment by andy1547** [comment]
@alexander-akait thanks for the quick response.
Is it possible to chain asset/modules and loaders? I'd prevent not to duplicate asset/modules.

**Comment by alexander-akait** [comment]
Yes, just use `use` with loaders and set `type: "asset/resource"`

**Comment by andy1547** [comment]
For anyone else reading this, I used the MergeJsonWebpackPlugin to merge JSON files at compile time and the fetch API to retrieve JSON at runtime:
````
// webpack.common.js
...
new MergeJsonWebpackPlugin({
	output: {
		groupBy: [
			{
                                // this does not throw when only appsettings.json is present
				pattern: "{./appsettings.json,./appsettings.*.json}",
				fileName: "appsettings.json",
			},
		]
	},
	globOptions: {
		nosort: true,
	},
	space: 4
})

// .gitignore
appsettings.*.json

// app.js (entry point)
// may need to manually polyfill fetch if targeting IE11, see https://github.com/babel/babel/issues/9160
import 'whatwg-fetch';

// generating a hashed chunk has no advantage here as admins can modify runtime settings after app is deployed. 
// always fetch (no cache) so users get the latest runtime settings if modified by admin
const result = await fetch("appsettings.json", {cache: "no-store"});    
const appSettings = await result.json();
````
@alexander-akait thanks for your assistance.
