### ISSUE TITLE
Allowing including additional files/directories to watch with the development server

### ISSUE THREAD

**Issue by hamza1311** [webpack/webpack#15506]
## Feature request

**What is the expected behavior?**

Watch specific file(s) or folder(s) in addition to the code from the package being built.

**What is motivation or use case for adding/changing the behavior?**

Consider a project structured like this:
```
.
├── angular.json
├── browserslist
├── client
│  └── ...
│     ├── ...
├── package.json
├── packages
│  ├── shared
│  │  ├── src
│  │  └── package.json
│  └── package xyz
│     ├── package.json
│     ├── src
├── tsconfig.json
├── webpack.config.js
```

- `client/` contains the client source code being built and served with webpack - could be an angular app, etc
- `packages/*` contains source code that client depends upon. These may be published separately as well. They're regular npm packages.

When we serve the client app, the webpack dev server watches changes in `client/` directory. If a change in made in `packages/*` directory, the client needs to be rebuilt and updated accordingly, but it is not. It should be.

**How should this be implemented in your opinion?**

Add an option similar to [`watchOptions.ignored`](https://webpack.js.org/configuration/watch/#watchoptionsignored), such as `include`.

**Workarounds**

- https://stackoverflow.com/questions/44743790/webpack-dev-server-watch-arbitrary-directory-files-and-reload

**Are you willing to work on this yourself?**
No

**Comment by alexander-akait** [comment]
We have https://webpack.js.org/configuration/dev-server/#devserverwatchfiles, please use it

**Comment by hamza1311** [comment]
I did not know that existed. Thanks!

**Comment by hamza1311** [comment]
@alexander-akait I used that and it seems that it doesn't solve the issue. The packages under the `packages` directory are *not* being re-built. Is there a solution to that?

I'll re-open the issue and update the description with more details
