### ISSUE TITLE
Getting entry's filename within `DefinePlugin.runtimeValue` method

### ISSUE THREAD

**Issue by theOnlyBoy** [webpack/webpack#15516]
## Feature request

Webpack version: 5.70.0

**What is the expected behavior?**

Would like to get a currently processing webpack entries' filename within `webpack.DefinePlugin`.

**What is motivation or use case for adding/changing the behavior?**

Tried to find a solution, googled and debugged `webpack.DefinePlugin.runtimeValue()` output, but couldn't find any prop that provides a current entry (aka `entries[smth]` prop in webpack config).

I know, there is the possibility to use multiple webpack configurations via the same config (`module.exports = [...]`) , but it's not the case.

**How should this be implemented in your opinion?**

Not sure if it's a limitation for all plugins or only for `webpack.DefinePlugin`, but it would be nice to have this data.
The plugin allows you to set other context-related values, but entry-related ones.

**Are you willing to work on this yourself?**
yes

**Comment by vankop** [comment]
I think it is not possible. you can have several entries for one module.

**Comment by theOnlyBoy** [comment]
@vankop That's the problem. I can fetch any data related to current source (filename, comments, blocks, etc.), but for some reason there is no entry filename available (which I need the most). Maybe it's possible to upgrade the plugin a little with such value.

**Comment by vankop** [comment]
`runtimeValue` evaluated for module, but module could be in several entries (when evaluation happens it is unknown how much entries use this module). e.g.
webpack.config.js
```js
module.exports = { entry: { a: "./a", b: "./b" } };
```
module with runtime value (file `module.js`)
```js
const a = __RUNTIME_VALUE__;
```
e.g. in entry `a` we have module chain a -> c -> d -> module.js
in entry `b` we have module chain b -> module.js

So `__RUNTIME_VALUE__` should be evaluated once but we can not determine entry for this module.

**Comment by theOnlyBoy** [comment]
@vankop Thank you for the explanation, mate! Appreciate that.
