### ISSUE TITLE
"Cannot find module" error though build is successful

### ISSUE THREAD

**Issue by zuzusik** [webpack/webpack#1551]
We are using Papaparse from Bower with WebPack and TypeScript 1.5. And though the build is successful (e.g. app is working), we are getting this error in `stats.toString()`:
```
ERROR in /app/shared/services/papa.service.ts
./app/shared/services/papa.service.ts
  /app/shared/services/papa.service.ts (1,23): Cannot find module 'papaparse'.
```
WebPack config:
```javascript 
plugins: [
  new webpack.ResolverPlugin(
    new webpack.ResolverPlugin.DirectoryDescriptionFilePlugin('bower.json', ['main'])
  )
],
```
Import:
```typescript
import * as Papa from 'papaparse';
```
TS files are loaded through `ts-loader`: 
```javascript
loaders: [
  {
    test: /\.ts$/,
    loader: 'ts-loader?target=es5'
  }
]
```
Papaparse: 
bower.json: https://github.com/mholt/PapaParse/blob/master/bower.json
main file to which points bower.json: https://github.com/mholt/PapaParse/blob/master/papaparse.js

How this can be solved?

**Comment by SpaceK33z** [comment]
Have you read the '[usage with bower](https://webpack.github.io/docs/usage-with-bower.html)' doc?

**Comment by zuzusik** [comment]
@SpaceK33z yep, I have. But `Papaparse` has all this module stuff defined: https://github.com/mholt/PapaParse/blob/master/papaparse.js#L39
So the info from "prefer Node section" is not about it.

**Comment by zuzusik** [comment]
One more thing I noticed
When I look into my bundle, for moment.js (which I use the same way and it doesn't print error) I see comment
```javascript
/* WEBPACK VAR INJECTION */ 
```
and for papaparse I see
```javascript
var _WEBPACK_AMD_DEFINE_RESULT_;
```
What could be the result of such a difference?

**Comment by zuzusik** [comment]
And one more note here: I have `bail` set to `true` but my build is still successful. So maybe this errors aren't errors but erroneous error signalisation?

**Comment by sokra** [comment]
This is a typescript error. You need to ask there.

**Comment by zuzusik** [comment]
After updating  to `TS 1.6` it started to print the error code: 
```
ERROR in ./app/shared/services/papa.service.ts
(1,23): error TS2307: Cannot find module 'papaparse'.
```
I searched for the code and found this answer: http://stackoverflow.com/a/33403658/4219836

In few words - it happens when there is no definition file for the module that isn't a TS module

**Comment by giona69** [comment]
Hi zuzusik

so how do you include a module in angular2 when there is no definition file?

**Comment by zuzusik** [comment]
@giona69 I guess you can try to write module definition yourself. 
Start from simple code:
```ts
declare module yourmodulename {};
```
This should suppress the error. 

If you need some typings for methods inside module you can continue adding them yourself.

Here is some docs on this topic: https://www.typescriptlang.org/docs/handbook/modules.html#working-with-other-javascript-libraries

**Comment by giona69** [comment]
thanks @zuzusik !

anyway later I found I can add typings through npm install @types

**Comment by zuzusik** [comment]
@giona69 ahh, cool!

I thought you were aware about typings installation, but haven't found typings for your module.

**Comment by giona69** [comment]
I have this problem with another library, and followed anyway your suggestion ... great!

thanks again!
