### ISSUE TITLE
Add a disclaimer in the documentation for third-party loaders and plugins

### ISSUE THREAD

**Issue by ddadon10** [webpack/webpack#15512]
The official webpack documentation has guides to use third party loaders and plugins, for example:
- The ts-loader guide https://webpack.js.org/guides/typescript/
- All the loaders from webpack-contrib https://webpack.js.org/loaders/

Without a proper disclaimer, a read of the documentation can think those plugins are maintained by webpack when this is not the case.

Third party plugins potentially don't have the same support, security policy, or license as webpack, so it would be nice to add a disclaimer for that.

**Comment by vankop** [comment]
created an issue in docs
