### ISSUE TITLE
Webpack v4 migration to v5 effort is running into a "JavaScript heap out of memory" 

### ISSUE THREAD

**Issue by duhmojo** [webpack/webpack#15529]
# Bug report

Hi. I have a webpack v4 legacy webpack.config.js that I'm trying to update to work with webpack v5. The only hiccup I ran into was my use of `webpack-dev-server -d --host 0.0.0.0 --open` was breaking the new devtool config in v5. So I corrected it to `webpack serve --host 0.0.0.0 --open` and all seemed ok (no errors building or starting) but I can' figure out why it's basically eating up memory then crashing with a "JavaScript heap out of memory" error.

I'm using:

webpack version:  5.70.0
Node.js version:  14.16.0
Operating System: CentOS 8 Stream

Here's my legacy webpack.config.js that worked with webpack v4. I tried writing a new one from scratch, but evertime I try to build it just eats up memory and crashes:

```
var HtmlWebpackPlugin = require('html-webpack-plugin');
const path = require('path');

module.exports = () => {
    return {
        devtool: 'eval-source-map',
        mode: 'development',
        module: {
            rules: [
                {
                    test: /\.jsx?$/,
                    loader: 'babel-loader',
                    options: {
                    presets: ['@babel/preset-env',
                        '@babel/react',{
                            'plugins': ['@babel/plugin-proposal-class-properties']}]
                }
                },
                {
                    test: /\.(css|scss)$/,
                    use: [
                        {
                            loader: 'style-loader'
                        },
                        {
                            loader: 'css-loader',
                            options: {url:false}
                        }
                    ]
                },
                {
                    test: /\.(woff)$/,
                    use: [
                        {
                            loader: 'url-loader',
                            options: {
                                name: 'fonts/[name].[ext]',
                                mimetype:'application/font-woff'
                            }
                        }
                    ],
                },
                {
                    test: /\.(woff2)$/,
                    use: [
                        {
                            loader: 'url-loader',
                            options: {
                                name: 'fonts/[name].[ext]',
                                mimetype:'application/font-woff2'
                            }
                        }
                    ],
                },
                {
                    test: /\.(ttf|otf)$/,
                    use: [
                        {
                            loader: 'url-loader',
                            options: {
                                name: 'fonts/[name].[ext]',
                            }
                        }
                    ],
                },
                {
                    test: /\.(png|svg|jpg|gif|ico)$/,
                    use: [
                        {
                            loader: 'file-loader',
                            options: {
                                name: '[name].[ext]',
                                outputPath: 'images/'
                            }
                        }
                    ],
                }
            ]
        },
        name: '[name].[ext]',
        resolve: {
            extensions: ['.js', '.jsx'],
            alias: {
                '@': path.resolve(__dirname, 'src/'),
                'NodeModules': path.resolve(__dirname, 'node_modules'),
            }
        },
        plugins: [new HtmlWebpackPlugin({
            template: './src/index.html'
        })],
        devServer: {
            historyApiFallback: true
        },
        externals: {
            // global app config object
            config: JSON.stringify({
                //apiUrl: '/api'
                apiUrl: 'http://127.0.0.1:4000/api'
            })
        },
        output: {
            filename: "main.js",
            publicPath: "/",
        }
    }
}

```

Here's the output from trying to start with `webpack serve` with `--progress` thrown in:

```
<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:8080/
<i> [webpack-dev-server] On Your Network (IPv4): http://172.16.240.144:8080/
<i> [webpack-dev-server] Content not from webpack is served from '/home/chris/Development/verity/frontend/public' directory
<i> [webpack-dev-server] 404s will fallback to '/index.html'
<i> [webpack-dev-middleware] wait until bundle finished: /
10% building 0/1 entries 0/0 dependencies 0/0 modules
```

And nothing else is logged. I monitored top and node was using GBs of memory and 100% CPU. When I just let it go it eventually it crashes:

```
<--- Last few GCs --->

[482203:0x563619071c30]   190078 ms: Mark-sweep 1976.4 (2084.9) -> 1956.6 (2078.5) MB, 401.5 / 0.0 ms  (average mu = 0.260, current mu = 0.108) task scavenge might not succeed
[482203:0x563619071c30]   190677 ms: Mark-sweep 1974.9 (2080.7) -> 1958.6 (2080.7) MB, 395.6 / 0.0 ms  (average mu = 0.301, current mu = 0.340) allocation failure scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x5636168852a4 node::Abort() [webpack]
...
```

I'm lost here and I can't tell if this is a bug of some kind of user error. I've posted this Q to stackoverflow as well, and I've looked through the repo issues for an answer without much luck.

Any advice is welcome.

**Comment by vankop** [comment]
This error occurs when the memory allocated for the executing application is less than the required memory. By default, the memory limit in Node.js is 512 MB. To increase this amount, you need to set the memory limit argument `--max-old-space-size=x`. It will help avoid a memory limit issue.

**Comment by duhmojo** [comment]
So I increased the memory limit from the default 512MB to 4GB and it still runs out of memory. The progress options `--progress` still indicates nothing is happening and it takes a while for the memory limit to be hit. Like longer than it took to build with webpack v4.

**Comment by duhmojo** [comment]
I tried profiling webpack in Chrome and here's the top consumers while the progress sits at 10%:

```
5161.5 ms43.39 %	5416.5 ms45.54 %	cachedJoin path.js:180	
1960.0 ms16.48 %	1960.0 ms16.48 %	cdUp DescriptionFileUtils.js:159	
1029.5 ms8.65 %	3542.2 ms29.78 %	doResolve Resolver.js:394	
440.1 ms3.70 %	906.1 ms7.62 %	provide CachedInputFileSystem.js:154	
420.9 ms3.54 %	420.9 ms3.54 %	(garbage collector)	
271.0 ms2.28 %	278.5 ms2.34 %	wrapSafe internal/module…/loader.js:964	
165.3 ms1.39 %	165.3 ms1.39 %	(program)	
152.6 ms1.28 %	255.0 ms2.14 %	join path.js:144	
147.0 ms1.24 %	147.0 ms1.24 %	add LazySet.js:92	
132.0 ms1.11 %	9112.0 ms76.60 %	(anonymous) DescriptionFileUtils.js:52	
124.3 ms1.04 %	124.3 ms1.04 %	open	
69.0 ms0.58 %	69.0 ms0.58 %	(anonymous) internal/per_co…mordials.js:23	
65.5 ms0.55 %	8799.9 ms73.98 %	(anonymous) DescriptionFileUtils.js:115	
63.8 ms0.54 %	100.5 ms0.84 %	normalize path.js:1004	
```

I only let it run for 5-10 seconds. I figured if there was some controlled loop it would be clear pretty early. I see cachedJoin.js eating up the most time. I'm disabling caching like so:

```
module.exports = {
  cached: false,
  ...
```

Maybe caching isn't disabled? I'm not sure what to make of the profile.

**Comment by alexander-akait** [comment]
Do you use polyfill Node.js runtime? I.e. for example do use use `babel-register` (or `ts-register`/`ts-node`/etc) to run webpack?

**Comment by duhmojo** [comment]
No, I'm not using babel-register. In my latest webpack.config.js for a dev build I'm just using babel-loader, with babel-refresh for dev where I have new webpack.HotModuleReplacementPlugin():

```
module.exports = {
  ...
    rules: [
      // ... other rules
      {
        test: /\.[js]sx?$/,
        exclude: /node_modules/,
        use: [
          // ... other loaders
          {
            loader: require.resolve('babel-loader'),
            options: {
              plugins: [
                // ... other plugins
                require.resolve('react-refresh/babel'),
              ].filter(Boolean),
            },
          },
        ],
      },
    ],
  ...
```

**Comment by duhmojo** [comment]
Ok, I'm making some progress but I'm not ready to explain it. webpack is now doing something with a config.js that I managed to reduce, and I'm working things back in to see what the issue is.

**Comment by duhmojo** [comment]
Ok, I know what the problem is. It's a resolve we have in the config.js that points to some external source code (just in a different directory that we pull in) and when I remove it from the build it completes with webpack v5. When I add it back in I get the high CPU/memory and crash. I'm going to see if I can spot some kind of resolve loop in there. I have no clue how to debug this.

**Comment by duhmojo** [comment]
The problem was an alias to an external directory. I don't know if there was some circular reference causing the problem because the same path was declared twice, but I found the issue by removing the # version because I couldn't find an actual use of it anywhere.

```
  resolve: {
    extensions: ['.js', '.jsx'],
    alias: {
        '#': path.resolve(__dirname, '../../external'),
        'external': path.resolve(__dirname, '../../external'),
    }
```

It builds now. The webpack server isn't serving the bundle, but I'll work on it outside of this issue. Maybe there's something here worth noting in the doc, but honestly even if it was in the docs I wouldn't have noted then remembered it when dealing with this situation. Thanks for the replies.

**Comment by vankop** [comment]
yeah, that is known bug
