### ISSUE TITLE
Cannot access '<val>' before initialization.

### ISSUE THREAD

**Issue by stefan-toubia** [webpack/webpack#15533]
# Bug report / Question

**What is the current behavior?**

I've been getting a large number of `Cannot access 'something' before initialization` errors. I took a look at a similar issue #12724 and also tried running `CircularDependencyPlugin` to identify any circular dependencies but none were identified. I also use the ESLint rule `import/no-cycle`. Looking at the generated module chunk I can't really make sense of it, but I'm not too familiar with the internals of the webpack runtime.

I have a simple file like this:

```tsx
import React from "react";
import { QueryClientProvider } from "react-query";
import { queryClient } from "./client";

export const AppQueryProvider = ({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element => {
  return (
    <QueryClientProvider client={queryClient} contextSharing>
      {children}
    </QueryClientProvider>
  );
};

export function withAppQueryClientProvider<TProps>(
  Component: React.ComponentType<TProps>
): typeof Component {
  return (props: TProps) => {
    return (
      <AppQueryProvider>
        <Component {...props} />
      </AppQueryProvider>
    );
  };
}
```

Which generates a chunk like this:

```tsx
    93992: (e, t, r) => {
      "use strict";
      r.d(t, { k: () => m });
      var s = r(87711),
        n = r.n(s),
        o = r(94812),
        a = r(29404),
        i = Object.defineProperty,
        c = Object.getOwnPropertySymbols,
        l = Object.prototype.hasOwnProperty,
        u = Object.prototype.propertyIsEnumerable,
        d = (e, t, r) =>
          t in e
            ? i(e, t, {
                enumerable: !0,
                configurable: !0,
                writable: !0,
                value: r,
              })
            : (e[t] = r);
      const v = ({ children: e }) =>
        n().createElement(
          o.QueryClientProvider,
          { client: a.IR, contextSharing: !0 },
          e
        );
      function m(e) {
        return (t) =>
          n().createElement(
            v,  // ReferenceError: Cannot access 'v' before initialization
            null,
            n().createElement(
              e,
              ((e, t) => {
                for (var r in t || (t = {})) l.call(t, r) && d(e, r, t[r]);
                if (c) for (var r of c(t)) u.call(t, r) && d(e, r, t[r]);
                return e;
              })({}, t)
            )
          );
      }
    },
```

So basically the error says `Cannot access 'AppQueryProvider' before initialization`. I'm not sure what the `r.d` dh function on the third line does (`r.d(t, { k: () => m });`, but it sure seems like the `k` function that returns `withAppQueryClientProvider` is being called before `AppQueryProvider` is initialized. I'm also wondering why `r.d(t, { k: () => m });` is at the top of the module, shouldn't it be called after the module has been initialized?

I'm really just looking for some help debugging this issue and figuring out what's going on, as well as confirmation on whether the generated code looks correct.

This extra context may or may not be relevant:

This is a React project that uses `ModuleFederationPlugin`. I'm seeing many of these errors reported from one of our legacy clients that is still on Webpack 4, so I'm are manually initializing the remote by injecting a script for the `remoteEntry.js`, something like below. Also because of this, I'm not doing anything to initialize a shared context, as far as I know I don't think that would be possible when the host is on Webpack 4. Not sure if this is relevant.

```js
  // This is not the real code that initializes the remote, just proto code to give an example
  // Part of `loadRemote` function
...
   const varName = "react_federated_remote"
    const onLoad = () => {
      const remoteVar = window[varName];
      callback?.(remoteVar);
    };
      const script = document.createElement("script");
      script.type = "text/javascript";
      script.addEventListener("load", onLoad);
      script.src = "/react-remote/static/remoteEntry.js";
      document.body.appendChild(script);
...
// Helper function that returns the async remote module

export const getRemoteModule = async () => {
  const remote = await loadRemote();
  return (await remote.get("./TheRemoteModule"))().default;
};
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Sorry, I'm not really sure how to repro at this time.

**What is the expected behavior?**

**Other relevant information:**
webpack version:  5.51
Node.js version:  10.24.1
Operating System: macos 
Additional tools: yarn 1.22.17

**Comment by alexander-akait** [comment]
Can you try to disable minification? Maybe terser bug

**Comment by vankop** [comment]
it looks like terser bug, please report in terser issue tracker
