### ISSUE TITLE
build target=electron-renderer, Uncaught ReferenceError: global is not defined

### ISSUE THREAD

**Issue by clotee** [webpack/webpack#15532]
"webpack": "^5.64.4",
    "webpack-dev-server": "^4.6.0",
    "webpack-manifest-plugin": "^4.0.2",

<img width="616" alt="image" src="https://user-images.githubusercontent.com/11476395/158423215-d6c329fa-f390-498f-9212-438293744d95.png">

**Comment by vankop** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us by recreating the issue using one of our templates.

Please fill out all fields, we can't help you without it

**Comment by vankop** [comment]
Also reproducible repo with webpack config will help a lot.

**Comment by ncaq** [comment]
Workaround.

I added globalThis of output.

```js
  output: {
    path: path.resolve(__dirname, 'app'),
    filename: '[name].js',
    globalObject: 'globalThis',
  },
```

**Comment by ncaq** [comment]
However, this workaround does not solve the problem of being misidentified as being in Node space, so you will probably see them trying to get the Node module with require.

`Uncaught ReferenceError: require is not defined
`

**Comment by Faithnone** [comment]
webpack  target: web
