### ISSUE TITLE
Some folders are ignored when building or compiling.

### ISSUE THREAD

**Issue by John-Soul** [webpack/webpack#15548]
## Feature request

**What is the expected behavior?**
Some folders are ignored when building or compiling.

**What is motivation or use case for adding/changing the behavior?**
Most project codes are common, and there are multiple projects under the views folder.

example.
I have three projects in one main folder. they use main folder some code, layout, style, components etc.
views/projectA | views/projectB | views/projectC
entry file in themself folder. 
I will input `npm run dev -- --project A`  compile the projectA.
compile  the projectB or projectC use same way.
This method save my ssd space and maintenance time.

But the more project in the views file, It will be slow.
I hope webpack have a method or plugin, some folders are ignored when building or compiling.

**How should this be implemented in your opinion?**
Expose some interface ignore some folders when compiling or building.
example.

new somePlugin({
  ignore: ['@/src/views/projectB', '@/src/views/projectC']
})

**Are you willing to work on this yourself?**
yes

**Comment by vankop** [comment]
Thanks for your issue, you should run only needed entries per run.
____
Or I did not understand what you mean, please explain.

**Comment by John-Soul** [comment]
Excuse me for my bad english grammer.
I mean in a vue project, in "views" folder have many project  will be slowly.
![image](https://user-images.githubusercontent.com/20299172/158957360-16cc54aa-72b1-42bb-a0b7-0bfee00f2b4c.png)
How can I ignore other project at runtime or buiding.

For example, when I  npm run dev for project "yhyth", webpack can ignore compile other project. "mzysz", "zyyzz" etc.

Thank you so mush.

**Comment by vankop** [comment]
> I mean in a vue project

probably better ask in `vue-cli` (or what are you using) issue tracker if it is possible. In webpack you just need to provide correct entrypoint.
