### ISSUE TITLE
webpack.config.js exposes module increase the heap memory size while build or serve the application in angular

### ISSUE THREAD

**Issue by ashif-sayyad** [webpack/webpack#15543]
I am using the dynamic module federation in angular. in that I am exposes the modules and access in another angular application. but when I am triggered the production build it increase the memory size. and throws the FATAL ERROR:
## Feature request
![K6tNJ](https://user-images.githubusercontent.com/98470160/158793597-d2935563-b357-4f02-bd87-0eb85e7c12b9.png)

**What is the expected behavior?**

**What is motivation or use case for adding/changing the behavior?**

**How should this be implemented in your opinion?**

**Are you willing to work on this yourself?**
yes

**Comment by vankop** [comment]
This error occurs when the memory allocated for the executing application is less than the required memory. By default, the memory limit in Node.js is 512 MB. To increase this amount, you need to set the memory limit argument --max-old-space-size. It will help avoid a memory limit issue. Please try to use `--max-old-space-size=x`.

**Comment by alexander-akait** [comment]
Also you use `ng`, they can have memory leaking too (due custom plugins or other tools), please report this to angular team, thanks
