### ISSUE TITLE
Tree shaking in development - outdated docs?

### ISSUE THREAD

**Issue by trozler** [webpack/webpack#15556]
When trying to follow the very simple tree shaking guide from the [docs]( https://webpack.js.org/guides/tree-shaking/),  for some reason code does not seem to shake. 

Are the docs outdated? 

For personal sanity help would be appreciated.

NOTE: code does shake when mode is `production`.
Link to Github repo: https://github.com/trozler/webpack-treeshaking

**What is the expected behavior?**

`square()` should be shaken, when setting `"sideEffects": false` in package.json.

<img width="463" alt="Screenshot 2022-03-19 at 14 26 32" src="https://user-images.githubusercontent.com/43752286/159122994-1be5a7f5-f1e5-4251-87ee-707b16367ad2.png">

**Other relevant information:**
webpack version:  5.70.0
webpack-cli version:  4.9.2
Node.js version: v16.13.2
Operating System: Mac OS Monteray

**Comment by trozler** [comment]
> So we've cued up our "dead code" to be dropped by using the import and export syntax, but we still need to drop it from the bundle. To do that, set the mode configuration option to [production](https://webpack.js.org/configuration/mode/#mode-production).

Just read this from the bottom of the guide. Closing issue. 
However would be incredibly useful if this is mentioned further up in the guide.

**Comment by alexander-akait** [comment]
Feel free to send PR in docs :+1:
