### ISSUE TITLE
Loaders to js seems to skip everything within require.ensure

### ISSUE THREAD

**Issue by prasannavl** [webpack/webpack#1555]
Adding 
`
postLoaders: [{
                    test: /\.js[x]?$/i,
                    loader: "file?name=" + jsPath
                }]
`

to the config seems to skip the entire set inside require.ensures. 

`require.ensure([], function(require) {
 require("./app");
});
`
The result generated by webpack ends up as a verbatim. And the "./app" dependency is entirely ignored when used this way.

**Comment by prasannavl** [comment]
Hmm.. This seems more to be an issue with file-loader, than webpack. Adding the same postloader into loader seems to end up with the same output. 
Webpack skips the entire lazy loaded bundle in that case. Is there a work around to this?

**Comment by sokra** [comment]
I don't think so.

btw. using the `file-loader` for js files seems very wrong. I hope this was only an example...

**Comment by prasannavl** [comment]
@sokra, yes, its just an example, and while I do agree that it does seem wrong, don't you think that it should semantically work? 

Since its just chained loaders. It feels like a quirky that it doesn't.
