### ISSUE TITLE
Issues with local CSS on mode: "production"

### ISSUE THREAD

**Issue by adhamali450** [webpack/webpack#15560]
# Bug report

**What is the current behavior?**
Some of the styles doen't get applied on `mode: "production"`

**If the current behavior is a bug, please provide the steps to reproduce.**
to reproduce: 
[webpack.config](https://pastebin.com/HF5VPt0Y)
[package.json](https://pastebin.com/2dSNNuYW)

**What is the expected behavior?**
styles renders and it does in `mode: "developement"`

Everyting runs ok with mode: "development". However, when I switch for `mode: "production"`, some of the styles doesn't get applied. I searched for it and there was [Github issue](https://github.com/webpack/webpack/issues/6741) and this [Stackoverflow question](https://stackoverflow.com/questions/52702536/webpack-custom-style-is-missing-after-production-build) that stated briefly that we should remove `"side-effects": false`. I don't have this attribute and I seem to fing nothing about this.

**Other relevant information:**
webpack version:  ^5.70.0
Node.js version: v12.22.5
Operating System: popOS
Additional tools: VSCode

**Comment by alexander-akait** [comment]
Please provide all steps to reproduce

**Comment by adhamali450** [comment]
> Please provide all steps to reproduce

Well, actually the only step is changing the mode to `production`. Without it eveything is fine.

**Comment by alexander-akait** [comment]
Can you provide link on your project

**Comment by adhamali450** [comment]
Sure! [here](https://github.com/adhamali450/portfolio)

**Comment by adhamali450** [comment]
> Can you provide link on your project

[Live version](https://adhamali.tech)
[Github repo](https://github.com/adhamali450/portfolio)

**Comment by alexander-akait** [comment]
@adhamali450 Can you provide which styles not applied? I have the same result

**Comment by adhamali450** [comment]
@alexander-akait  

Styles not applied: 
- first 2 inputs on the form (last section on the page)
- background color for the header on browsers that doesn't support backdrop blur.

Keep in mind the current commit on the repo is set with mode = 'development' for testing. If you cloned it locally and tried mode = 'production' you will find the issues mentioned.

**Comment by alexander-akait** [comment]
@adhamali450 Sorry, I can't reproduce your problems, please check your disable cache in browser, we don't modify your files, just bundle them, I see you use `postcss-preset-env`, maybe problem in `postcss-preset-env`, but I can't reproduce, you can provide screenshots, maybe it will help

**Comment by dilyanpalauzov** [comment]
Looks like https://github.com/webpack-contrib/mini-css-extract-plugin/issues/904:
> When I run webpack in delevopment mode, the CSS output is not minified, but the javascript contains extra code.
