### ISSUE TITLE
module federation webpack.config.js expose module increase the build application size in angular

### ISSUE THREAD

**Issue by ashif-sayyad** [webpack/webpack#15571]
Hi, I am using the module federation in angular.
without adding module federation it is build the application well and run without any error.
but, when I expose the module from webpack.config.js file. and access in another angular application. when I am triggered the production build it increase the application size. and throws the FATAL ERROR:
![K6tNJ](https://user-images.githubusercontent.com/98470160/159257770-7592e89d-30be-4921-9a6b-4f509059b1f2.png)
## Feature request
My webpack.config.js file:

const ModuleFederationPlugin = require("webpack/lib/container/ModuleFederationPlugin");
const mf = require("@angular-architects/module-federation/webpack");
const path = require("path");
const share = mf.share;

const sharedMappings = new mf.SharedMappings();
sharedMappings.register(
  path.join(__dirname, 'tsconfig.json'),
  [/* mapped paths to share */]);

module.exports = {
  output: {
    uniqueName: "eProcurement",
    publicPath: "auto"
  },
  optimization: {
    runtimeChunk: false
  },
  resolve: {
    alias: {
      ...sharedMappings.getAliases(),
    }
  },
  experiments: {
    outputModule: true
  },
  plugins: [
    new ModuleFederationPlugin({
      library: { type: "module" },

      // For remotes (please adjust)
      name: "eProcurement",
      filename: "remoteEntry.js",
      exposes: {
        './departments': './src/app/e-procurement/departments/departments.module.ts',
        './sections': './src/app/e-procurement/sections/sections.module.ts',
        './units': './src/app/e-procurement/units/units.module.ts',
        './noticeperiods': './src/app/e-procurement/notice-periods/notice-periods.module.ts',
        './functionality': './src/app/e-procurement/functionality/functionality.module.ts',
        './responsiveness': './src/app/e-procurement/responsiveness/responsiveness.module.ts',
        './procurementmethods': './src/app/e-procurement/procurement-methods/procurement-methods.module.ts',
        './stepapprovals': './src/app/e-procurement/step-approvals/step-approvals.module.ts',
        './commodities': './src/app/e-procurement/commodities/commodities.module.ts',
        './deviations': './src/app/e-procurement/deviation-reasons/deviation-reasons.module.ts',
        './defaults': './src/app/e-procurement/defaults/defaults.module.ts',
        './requisitions': './src/app/e-procurement/requisition/requisition.module.ts',
        './commodityaccess': './src/app/e-procurement/commodity-access/commodity-access.module.ts',
        './accountscommodityaccess': './src/app/e-procurement/accounts-commodity-access/accounts-commodity-access.module.ts',
        './allrequisitions': './src/app/e-procurement/all-requisitions/all-requisitions.module.ts',
        './stepevents': './src/app/e-procurement/step-events/step-events.module.ts',
        './requisitionincidents': './src/app/e-procurement/requisition-incidents/requisition-incidents.module.ts',
        './supplierscommodityaccess': './src/app/e-procurement/supplier-commodity-access/supplier-commodity-access.module.ts',
        './udfpreferences': './src/app/e-procurement/criteria-supplier-preference/criteria-supplier-preference.module.ts',
        './filecategories': './src/app/e-procurement/file-category/file-category.module.ts',
        './rfqpreview': './src/app/e-procurement/rfq-report-preview/rfq-report.module.ts',
        './rfqreportpreview': './src/app/e-procurement/reports-evaluation-rfq-preview/reports-evaluation-rfq-preview.module.ts',
        './requisitionpreview': './src/app/e-procurement/requisition-report-preview/requisition-report-preview.module.ts',
        './requisitionlistingpreview': './src/app/e-procurement/requisition-listing-report-preview/requisition-listing-preview.module.ts',
        './postedrequisition': './src/app/e-procurement/posted-requisition/posted-requisition.module.ts',
        './deviationincidents': './src/app/e-procurement/deviation-incidents/deviation-incidents.module.ts',
        './deviationpreview': './src/app/e-procurement/deviation-incidents-report-preview/deviation-incidents-report-preview.module.ts',
        './deviationresponse': './src/app/e-procurement/deviation-response/deviation-response.module.ts',
        './manageusers': './src/app/e-procurement/manage-users/manage-users.module.ts',
        './subsections': './src/app/e-procurement/sub-sections/sub-sections.module.ts',
        './tenderquotes': './src/app/e-procurement/tender-quotes/tender-quotes.module.ts',
        './responsivenessevaluation': './src/app/e-procurement/responsiveness-evaluation/responsiveness-evaluation.module.ts',
        './functionalityevaluation': './src/app/e-procurement/functionality-evaluation/functionality-evaluation.module.ts',
        './invitationfeedback': './src/app/e-procurement/committee-invitation-feedback/committee-invitation-feedback.module.ts',
        './evaluatetender': './src/app/e-procurement/evaluate-tender/evaluate-tender.module.ts',
        './tenderpriceevaluation': './src/app/e-procurement/tender-price-evaluation/tender-price-evaluation.module.ts',
        './tenderfinalapproval': './src/app/e-procurement/tender-final-approval/tender-final-approval.module.ts',
        './incidentreassign': './src/app/e-procurement/incident-reassign/incident-reassign.module.ts',
        './reportstenderpreview': './src/app/e-procurement/reports-tender-preview/reports-tender-preview.module.ts',
        './tenderpreview': './src/app/e-procurement/tender-report-preview/tender-report-preview.module.ts',
        './reportdeviations': './src/app/e-procurement/reports-deviations/reports-deviation.module.ts',
        './reportrequisitionlisting': './src/app/e-procurement/reports-requisition-listing/reports-requisition-listing.module.ts',
        './generatepo': './src/app/e-procurement/generate-po/generate-po.module.ts',
        './pricevaluation': './src/app/e-procurement/price-evaluation/price-evaluation.module.ts',
        './reportrfq': './src/app/e-procurement/reports-rfq/reports-rfq.module.ts',
        './reporttender': './src/app/e-procurement/reports-tender/reports-tender.module.ts',
        './reportevaluation': './src/app/e-procurement/reports-evaluation/reports-evaluation.module.ts',
        './reportevaluationpreview': './src/app/e-procurement/reports-evaluation-preview/reports-evaluation-preview.module.ts',
        './reportevaluationdetailpreview': './src/app/e-procurement/reports-evaluation-detail-preview/reports-evaluation-detail.module.ts',
        './reporttenderesponsespreview': './src/app/e-procurement/reports-tenderesponses-preview/reports-tenderesponses-preview.module.ts',
        './reportminitendepreview': './src/app/e-procurement/reports-minitender-preview/reports-minitender-preview.module.ts',
        './reportPOpreview': './src/app/e-procurement/reports-po-preview/reports-po-preview.module.ts',
        './reportreqhistorypreview': './src/app/e-procurement/reports-reqhistory-preview/reports-reqhistory-preview.module.ts',
        './reportdevhistorypreview': './src/app/e-procurement/reports-devhistory-preview/reports-devhistory-preview.module.ts',
        './reportcommodities': './src/app/e-procurement/reports-commodities/reports-commodities.module.ts',
        './reportsuppliercommoditypreview': './src/app/e-procurement/reports-supplier-commodities-preview/reports-supplier-commodities.module.ts',
        './reportaccountcommoditypreview': './src/app/e-procurement/reports-account-commodities-preview/reports-account-commodities.module.ts',
        './reporttenderregisterpreview': './src/app/e-procurement/reports-tender-register-preview/reports-tender-register-preview.module.ts',
        './reporttenderopeningregisterpreview': './src/app/e-procurement/reports-tender-opening-register-preview/reports-tender-opening-register-preview.module.ts',
        './reportdeclarationpreview': './src/app/e-procurement/reports-declaration-preview/reports-declaration-preview.module.ts',
        './reportinvalidtenders': './src/app/e-procurement/report-invalid-tenders/report-invalid-tenders.module.ts',
        './reportinvalidtenderpreview': './src/app/e-procurement/report-invalid-tenders-preview/report-invalid-tenders-preview.module.ts',
        './budgetoverride': './src/app/e-procurement/budget-override/budget-override.module.ts',
        './viewbudgetoverride': './src/app/e-procurement/detail-budget-override/detail-budget-override.module.ts',
        './reportarchivedreq': './src/app/e-procurement/reports-archived-req-preview/reports-archived-req-preview.module.ts',
        './reportfilteredaccounts': './src/app/e-procurement/reports-filtered-accounts-commodities-preview/reports-filtered-accounts-commodities-preview.module.ts',
        './reportfilteredsupplier': './src/app/e-procurement/reports-filtered-supplier-commodities-preview/reports-filtered-supplier-commodities-preview.module.ts',
        './usersettings': './src/app/e-procurement/user-settings/user-settings.module.ts',
        './viewallrequisitions': './src/app/e-procurement/view-all-requisitions/view-all-requisitions.module.ts',
        './quotereasons': './src/app/e-procurement/invalid-quote-reasons/invalid-quote-reasons.module.ts',
        './regretletterpreview': './src/app/e-procurement/regret-letter-preview/regret-letter-preview.module.ts',
        './appointmentletterpreview': './src/app/e-procurement/appointment-letter-preview/appointment-letter-preview.module.ts',
        './reportprocmethodpreview': './src/app/e-procurement/reports-proc-method-preview/reports-proc-method-preview.module.ts',
        './rfqresubmission': './src/app/e-procurement/rfq-resubmission/rfq-resubmission.module.ts'
      },

      // For hosts (please adjust)
      // remotes: {
      //     "mfe1": "http://localhost:3000/remoteEntry.js",

      // },

      shared: share({
        "@angular/core": { singleton: true, strictVersion: true, requiredVersion: 'auto' },
        "@angular/common": { singleton: true, strictVersion: true, requiredVersion: 'auto' },
        "@angular/common/http": { singleton: true, strictVersion: true, requiredVersion: 'auto' },
        "@angular/router": { singleton: true, strictVersion: true, requiredVersion: 'auto' },

        ...sharedMappings.getDescriptors()
      })

    }),
    sharedMappings.getPlugin()
  ],
};

![knAZb](https://user-images.githubusercontent.com/98470160/159258871-dfa4d55d-955a-4a6e-a96e-1a0be06dff6d.png)

![b0lqQ](https://user-images.githubusercontent.com/98470160/159258922-46ec1c50-8740-4df9-ba1b-805063b29808.png)

**What is the expected behavior?**
It should not throw the fatal error of memory.

**What is motivation or use case for adding/changing the behavior?**

**How should this be implemented in your opinion?**
it should run smoothly after expose the module.

**Are you willing to work on this yourself?**
yes
@Kumar-Aakash

**Comment by alexander-akait** [comment]
If you have big application you should increase memory usage, sorry I am afraid it is not fixable, especial without reproducible example

**Comment by vankop** [comment]
This error occurs when the memory allocated for the executing application is less than the required memory. By default, the memory limit in Node.js is 512 MB. To increase this amount, you need to set the memory limit argument `--max-old-space-size=x`. It will help avoid a memory limit issue.

**Comment by Kumar-Aakash** [comment]
@vankop Application is small. Every single component has its own module which is getting lazy-loaded and the app has around 20-30 pages so we have lazy routing for each of them.  I wanted to understand what is the reason where dist size gets increased significantly from a few MBs to GBs. May I get the answer for this so that we can modify our code structure accordingly? 

Our problem would be that we cannot go to production with this huge size. Increasing memory size is a valid option and through that, it is working fine but yes we are looking for a way to reduce this size once we use webpack config exports.

Thanks in advance.

**Comment by vankop** [comment]
please create a minimal repro then. thanks.

**Comment by ashif-sayyad** [comment]
@vankop @Kumar-Aakash I have created the demo repos of module federation webpack. and expose the module from webpack.config.js.
port 4202.
please have a look it.
https://github.com/ashif-sayyad/module-federation-demo/tree/master/demo-project

**Comment by vankop** [comment]
it does not work for me..
```
> demo-project@0.0.0 start
> ng serve

An unhandled exception occurred: ENOENT: no such file or directory, lstat '/Users/ivankopeykin/Repositories/module-federation-demo/demo-project/node_modules/devextreme/dist/css/generic.greenmist-compact.custom.css'
See "<log>" for further details.
⠋ Generating browser application bundles (phase: setup)...%   
```
btw I can not help with angular, you should ask this in angular issue tracker.
