### ISSUE TITLE
BannerPlugin does not honor raw

### ISSUE THREAD

**Issue by bolinfest** [webpack/webpack#15576]
# Bug report

**What is the current behavior?**

A string value for `banner` that is a JS comment does not appear to work with `raw: true`.

For example, if I specify the following for a `.css` file that is generated by webpack:

```
BannerPlugin({banner: '/* hello world */', raw: true})
```

I would expect `/* hello world */` to get prepended to my file.

Instead, nothing is prepended.

Yes, I know that I could do:

```
BannerPlugin({banner: 'hello world, raw: true})
```

but that would produce:

```
/*! hello world */
```

which is not what I want. I am at the mercy of other tooling that expects the start of the file to be in a very specific format.

**If the current behavior is a bug, please provide the steps to reproduce.**

See above.

**What is the expected behavior?**

The content of my `banner` string should have nothing to do with `raw: true` doing what it says it should do.

**Other relevant information:**
webpack version:  5.70.0
Node.js version: v14.14.0
Operating System: macOS Monterey, v12.2.1
Additional tools: I am using a webpack config generated by create-react-app, though with heavy use of rewire to add customizations, such as including `BannerPlugin` in the `optimization.minimizer` list.

**Comment by bolinfest** [comment]
Possibly related: https://github.com/webpack-contrib/css-minimizer-webpack-plugin/issues/64

**Comment by vankop** [comment]
without minimizing it works fine?

**Comment by alexander-akait** [comment]
@bolinfest `BannerPlugin` only for JS, when we will have build-in support for CSS, it will work, currently if you need it you should ask minifier developers to add option for this

@vankop We can mark this as enchantment for built-in CSS support

**Comment by vankop** [comment]
technically BannerPlugin processes all assets.. need to test this

**Comment by alexander-akait** [comment]
@vankop oh, it means cssnano (built-in minifier) remove it as comment

/cc @ludofischer

**Comment by bolinfest** [comment]
Currently, I am using https://cdn.jsdelivr.net/npm/react-scripts@5.0.0/config/webpack.config.js and trying not to fork it because it is pulled in via create-react-app. This is the workaround I have found thus far:

```javascript
const rewire = require('rewire');
const defaults = rewire('react-scripts/scripts/build.js');
const config = defaults.__get__('config');

const CssMinimizerPlugin = config.optimization.minimizer.pop();
config.optimization.minimizer.push(
  new CssMinimizerPlugin.constructor({
    minify: [
      CssMinimizerPlugin.constructor.cssnanoMinify,
      (data, inputMap, _minimizerOptions) => {
        const theSource = inputMap.sources[0];
        const theMinifiedCSS = data[theSource];
        const CSS_HEADER = `\
/**
 * My custom header.
 */
`;
        return Promise.resolve({
          code: CSS_HEADER + theMinifiedCSS + '\n',
        });
      },
    ],
  }),
);
```

**Comment by alexander-akait** [comment]
@ludofischer I think we should implement this `comments` - https://github.com/terser/terser#format-options, i.e. allow to keep some comments, for example `/*! Text */` used only for licences comments and by default most of minimizer preserve them or plugin api to get them https://github.com/webpack-contrib/terser-webpack-plugin/blob/master/src/utils.js#L109

**Comment by bolinfest** [comment]
With respect to "special comments," as I noted in my original bug report:

> I am at the mercy of other tooling that expects the start of the file to be in a very specific format.

I would have hoped that listing `BannerPlugin` "last" in the `minimizer` list (or is it the `plugins` list?) would ensure it runs after the other minifiers such that any comment it adds would not get stripped.

At least for `TerserPlugin`, I can use its `preamble` option, though I also had to set `extractComments` to `{condition: false, banner: false}`.

**Comment by vankop** [comment]
@alexander-akait I think there is nothing to do in webpack..

**Comment by alexander-akait** [comment]
@vankop I think this plugin can work with CSS (and other textual types)

**Comment by vankop** [comment]
and it does.. problem in minimization https://github.com/webpack/webpack/issues/15576#issuecomment-1076692277

**Comment by alexander-akait** [comment]
@vankop theoretically we can allow to use an another hook, so we will add a comment to already minified code...

**Comment by alexander-akait** [comment]
bump

**Comment by krutoo** [comment]
same issue

**Comment by alexander-akait** [comment]
Yeah, let's fix it

**Comment by alexander-akait** [comment]
@krutoo weird, I can't reproduce, can you provide a reproducible test repo

**Comment by krutoo** [comment]
> @krutoo weird, I can't reproduce, can you provide a reproducible test repo

https://github.com/krutoo/isomorph-bun-vs-node

maybe i use wrong config, you can run `npm i && npm run dev` nodejs 20

**Comment by alexander-akait** [comment]
Please use:
```
 new TerserPlugin({
        terserOptions: {
          format: {
            comments: /@bun/i,
          },
        },
        extractComments: false,
      }),
```

The original problem was resolved, I want to close in favor https://github.com/webpack-contrib/css-minimizer-webpack-plugin/issues/64 and allow to set stage, will implement soon
