### ISSUE TITLE
Can't resolve node builtin modules in esm build dependency

### ISSUE THREAD

**Issue by keenwon** [webpack/webpack#15574]
# Bug report

**What is the current behavior?**

```bash
<w> [webpack.cache.PackFileCacheStrategy] Caching failed for pack: Error: Can't resolve 'url' in '/Users/keenwon/Test/webpack-test'
<w> while resolving 'url' in /Users/keenwon/Test/webpack-test as file
<w>  at resolve esm file url
<w>  at file dependencies /Users/keenwon/Test/webpack-test/webpack.config.mjs
<w>  at file /Users/keenwon/Test/webpack-test/webpack.config.mjs
<w>  at resolve commonjs /Users/keenwon/Test/webpack-test/webpack.config.mjs
```

**If the current behavior is a bug, please provide the steps to reproduce.**

works fine, no warnings

**What is the expected behavior?**

**Other relevant information:**
webpack version:  5.70.0
Node.js version: v14.19.0
Operating System: macOS 12.3
Additional tools:

**demo**

repo https://github.com/keenwon/webpack-test, **switch to node-prefix branch**

![image](https://user-images.githubusercontent.com/5516478/159485407-88a3be9c-f9be-4589-8774-d8cdfdecdbc4.png)

`node:` doesn't work either

![image](https://user-images.githubusercontent.com/5516478/159485500-a1be2179-4cff-427b-a2b7-2026d0b124f5.png)

**Comment by alexander-akait** [comment]
Duplicate https://github.com/webpack/webpack/issues/14166

**Comment by alexander-akait** [comment]
Please use https://github.com/webpack/webpack/issues/14166#issuecomment-923840210

**Comment by vankop** [comment]
your config should be
```
externals: { 'node:X': 'commonjs2 X' }
```
where X is used module (`url`, `path` etc)

**Comment by keenwon** [comment]
I have committed to the **node-prefix** branch([repo](https://github.com/keenwon/webpack-test,))

<img width="858" alt="image" src="https://user-images.githubusercontent.com/5516478/159626311-7f5ae49e-7e12-420e-a50d-44a7b4d52131.png">

![image](https://user-images.githubusercontent.com/5516478/159626382-c2d331c0-d1ae-4d9f-a6af-54bf7f96a37a.png)

**Comment by vankop** [comment]
ok, I understand what you are doing.. please use `url` and `path` modules in `webpack.config`.. (without `node:` prefix)

settings with `externals` works only for bundling code, not webpack config..

**Comment by keenwon** [comment]
Yes, that's the weird part. the `url` also not works

(Please see the first picture of this issue)

**Comment by vankop** [comment]
I found a problem.. For now I can suggest to use commonjs config format..

**Comment by vankop** [comment]
solved in https://github.com/webpack/webpack/pull/15611
