### ISSUE TITLE
React app compiles with errors if we use absolute imports after adding jsconfig.json

### ISSUE THREAD

**Issue by 12sam12** [webpack/webpack#15570]
# Bug report

**What is the current behavior?**
Created using create react app, compiles with errors if we use absolute imports after adding jsconfig.json
Module not found: Error: Can't resolve '@/components'
```javascript
{
  "compilerOptions": {
    "baseUrl": "./",
    "paths": {
      "@/src/*": ["src/*"],
      "@/components/*": ["src/components/*"],
    }
  },
  "exclude": ["node_modules"]
}
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Generate a react app using npx create-react-app my-app
Add jsconfig.json
Create component with some absolute imports.
Run it, error.

**What is the expected behavior?**

**Other relevant information:**
webpack version:  5.70.0
Node.js version: 16.13.2
Operating System: Linux
Additional tools: React ^17.0.2, redux ^4.1.2 app

**Comment by vankop** [comment]
please ask in create-react-app issue tracker. thanks

**Comment by 12sam12** [comment]
But webpack is only compiling with errors.
