### ISSUE TITLE
使用bannerplugin时设置raw为true报错

### ISSUE THREAD

**Issue by ddmy** [webpack/webpack#15590]
# Bug report

**What is the current behavior?**
 ```js
      new webpack.BannerPlugin({
        banner: '// qwewqeqwe',
        raw: true, 
      })
```
`Build failed with errors.`

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

有些特殊情况我并不希望使用 /**/ 的形式来添加注释，或者我想自己添加注释直接输出到文件当中。但这个行为会引起报错。这可能是webpack内部的限制。所以恳请能支持一下这个功能，增加一个配置项，当开发者确定内容是有效的且符合自身业务的情况下，可以输出原内容到文件中。谢谢。

**Other relevant information:**
webpack version:  5.70.0
Node.js version: 
Operating System: 
Additional tools:

**Comment by vankop** [comment]
`BannerPlugin` works for all assets and in css there is no `//` line comments..

**Comment by ddmy** [comment]
> `BannerPlugin` works for all assets and in css there is no `//` line comments..

@vankop 感谢，我对你的回复有一些疑问， 我认为`BannerPlugin` 适用用所有文件  是因为有`test ` `include ` `exclude `字段让我们可以更灵活的选择去处理文件，而不应该是在webpack内部做出了这些限制。

或者我想要这样一个配置
```js
  new webpack.BannerPlugin({
       banner: '/* AUTHORIZATION  ES10 */\n',
       // raw: true, 
   })
```

显然，我就希望这个注释在独立的一行，现在也不支持。BannerPlugin不够灵活。
