### ISSUE TITLE
Async externals don't work with commonjs

### ISSUE THREAD

**Issue by clyfish** [webpack/webpack#15596]
# Bug report

**What is the current behavior?**
Async externals work with es modules, but don't work with commonjs.

**If the current behavior is a bug, please provide the steps to reproduce.**
webpack.config.js (copied from https://github.com/webpack/webpack/blob/v5.70.0/test/configCases/externals/async-externals/webpack.config.js)
```js
module.exports = {
  externals: {
    'promise-external': 'promise new Promise(resolve => setTimeout(() => resolve(42), 100))',
  },
}
```
src/index.js
```js
import value from 'promise-external'
const value2 = require('promise-external')
console.log(value, value2)
```
The console logs
```
42 Promise {<fulfilled>: 42}
```

**What is the expected behavior?**
The expected console logs
```
42 42
```

**Other relevant information:**
webpack version:  5.70.0
Node.js version: v16.14.2
Operating System: Linux
Additional tools:

**Comment by vankop** [comment]
this is expected otherwise `import("promise-external")` will return promise in promise..
Think about it like top level await..
