### ISSUE TITLE
Webpack adds unwanted chunk to the bundle when using conditional dynamic imports based on json file

### ISSUE THREAD

**Issue by Mikilll94** [webpack/webpack#15591]
# Bug report
In the code I have a JSON config file (config.json):

```json
{
    "useUtils": false
}
```

I have also a conditional dynamic import:

```js
import configJson from '../config.json';

function component() {
    //if (1 == 2) { // this if condition Webpack understands and it does not add utils.js to the bundle
    if (configJson.useUtils) {
        import(/* webpackChunkName: "utils" */ './utils').then(() => {
            console.log("UTILS LOADED DYNAMICALLY");
        });
    }

    const element = document.createElement('div');  
    element.innerHTML = "Hello webpack";
    return element;
  }
  
  document.body.appendChild(component());
```

Webpack does not understands that `configJson.useUtils` is always false and it adds unwanted `utils.js` chunk to the output bundle.

**What is the current behavior?**
Webpack adds unwanted `utils.js` chunk to the `dist` folder.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Download the project
[webpack-bug.zip](https://github.com/webpack/webpack/files/8355153/webpack-bug.zip)

2. Run
`npm install`
`npm run build`

3. As you can see, `utils.js` file is included in the final bundle (in the `dist` folder) although the condition `if (configJson.useUtils)` is never satisfied.

**What is the expected behavior?**
Webpack should not add `utils` chunk to the final bundle.

**Other relevant information:**
webpack version: 5.70.0
Node.js version: 16.14.2
Operating System: Windows 21H1
Additional tools:
npm: 8.5.5

**Comment by vankop** [comment]
> Webpack does not understands that configJson.useUtils is always false and it adds unwanted utils.js chunk to the output bundle.

yeah, this does not work..

**Comment by vankop** [comment]
I rethink this a little bit.. supporting this will need additional evaluation.. please instead of
```js
import {} from "config.json";
```
use `DefinePlugin`
