### ISSUE TITLE
node_modules are not excluded

### ISSUE THREAD

**Issue by jon-link-jon** [webpack/webpack#15592]
I have created a minimal file to reproduce the bug, removing extneral dependencies such as path.  I have upgraded to the latest version of webpack and posted on [stackoverflow](https://stackoverflow.com/questions/71563663/why-wont-webpack-ignore-my-node-modules).

# Bug report

**What is the current behavior?**

node_modules are being processed despite exclusion.

**If the current behavior is a bug, please provide the steps to reproduce.**

This is my config file that I use ...

```

const jsx = {
  test: /\.jsx?/,
  exclude: /node_modules/,
  use: {
    loader: 'babel-loader',
    options: {
      presets: ['@babel/preset-react']
    }
  }
};

const file_types = {
  rules: [
    jsx
  ]
};

const entry = '/Users/c/top/tiny/index.jsx';

const output = {
  filename: 'bundle.js',
  path: '/Users/c/top/tiny/dist'
};

const config_obj = {
  entry:          entry,
  output:         output,
  module:         file_types
};

module.exports = (env) => {
  return config_obj;
};

```

**What is the expected behavior?**
node_modules to not be processed

**Other relevant information:**
webpack version:  5.70.0
Node.js version:  14.18.0
Operating System: macOS 
Additional tools:

**Comment by vankop** [comment]
`exclude: ...` means that rule will not be applied to this resources, but webpack will bundle `node_modules/...` if this modules was requested (`import x from "x"`) by user.

**Comment by jon-link-jon** [comment]
I understand that they will be bundled of course, or I could not use React and Redux.  The problem is that webpack is still processing the files, i.e. compiling files that do not need to be compiled.

What normally takes msec is now taking 4 seconds.

```
asset bundle.js 132 KiB [compared for emit] [minimized] (name: main) 1 related asset
orphan modules 55.3 KiB [orphan] 30 modules
cacheable modules 186 KiB
  modules by path ./node_modules/hoist-non-react-statics/ 5.36 KiB 3 modules
  modules by path ./node_modules/react/ 6.48 KiB 2 modules
  modules by path ./node_modules/react-dom/ 119 KiB 2 modules
  modules by path ./node_modules/scheduler/ 4.91 KiB
    ./node_modules/scheduler/index.js 198 bytes [built] [code generated]
    ./node_modules/scheduler/cjs/scheduler.production.min.js 4.72 KiB [built] [code generated]
  modules by path ./node_modules/react-is/ 2.48 KiB
    ./node_modules/react-is/index.js 196 bytes [built] [code generated]
    ./node_modules/react-is/cjs/react-is.production.min.js 2.29 KiB [built] [code generated]
  ./index.jsx + 20 modules 46 KiB [built] [code generated]
  ./node_modules/object-assign/index.js 2.06 KiB [built] [code generated]
webpack 5.70.0 compiled successfully in 3875 ms

```

**Comment by vankop** [comment]
you see this modules in log since they are bundled, but this does not mean that loader was used.

**Comment by jon-link-jon** [comment]
The loader is likely being used because normally it takes < .5 second .... in the msec range to bundle an empty project.  It takes 4 seconds because it is compiling I believe.  Is there a way for me to troubleshoot this further.

I have seen nice clean compiles under < .5s when it is running as it should.   ~ 4 seconds is too long for an empty project.

**Comment by alexander-akait** [comment]
Can you provide code? Maybe reproducible example?

**Comment by jon-link-jon** [comment]
Here is the repo ...

https://github.com/jon-link-jon/tiny

You should be able to clone it, install it, and run `npm run client` to get the same results.  Or if you just want the config file it is above.

**Comment by jon-link-jon** [comment]
Mine runs between 3400 and 3900 msec.  A lot of variation on one machine.  Can you post your output?
```

[asset bundle.js 132 KiB [compared for emit] [minimized] (name: main) 1 related asset
orphan modules 55.3 KiB [orphan] 30 modules
cacheable modules 186 KiB
  modules by path ./node_modules/hoist-non-react-statics/ 5.36 KiB 3 modules
  modules by path ./node_modules/react/ 6.48 KiB 2 modules
  modules by path ./node_modules/react-dom/ 119 KiB 2 modules
  modules by path ./node_modules/scheduler/ 4.91 KiB
    ./node_modules/scheduler/index.js 198 bytes [built] [code generated]
    ./node_modules/scheduler/cjs/scheduler.production.min.js 4.72 KiB [built] [code generated]
  modules by path ./node_modules/react-is/ 2.48 KiB
    ./node_modules/react-is/index.js 196 bytes [built] [code generated]
    ./node_modules/react-is/cjs/react-is.production.min.js 2.29 KiB [built] [code generated]
  ./index.jsx + 20 modules 46 KiB [built] [code generated]
  ./node_modules/object-assign/index.js 2.06 KiB [built] [code generated]
webpack 5.70.0 compiled successfully in 3510 ms](url)
```

**Comment by alexander-akait** [comment]
My output:
```
asset bundle.js 132 KiB [compared for emit] [minimized] (name: main) 1 related asset
orphan modules 55.3 KiB [orphan] 30 modules
cacheable modules 186 KiB
  modules by path ./node_modules/hoist-non-react-statics/ 5.36 KiB 3 modules
  modules by path ./node_modules/react/ 6.48 KiB 2 modules
  modules by path ./node_modules/react-dom/ 119 KiB 2 modules
  modules by path ./node_modules/scheduler/ 4.91 KiB
    ./node_modules/scheduler/index.js 198 bytes [built] [code generated]
    ./node_modules/scheduler/cjs/scheduler.production.min.js 4.72 KiB [built] [code generated]
  modules by path ./node_modules/react-is/ 2.48 KiB
    ./node_modules/react-is/index.js 196 bytes [built] [code generated]
    ./node_modules/react-is/cjs/react-is.production.min.js 2.29 KiB [built] [code generated]
  ./index.jsx + 20 modules 46 KiB [built] [code generated]
  ./node_modules/object-assign/index.js 2.06 KiB [built] [code generated]
webpack 5.70.0 compiled successfully in 1469 ms
```

Anyway you can speed up it using:
```js
const config_obj = {
  entry:          entry,
  cache: {
    type: "filesystem"
  },
  output:         output,
  module:         file_types
};
```

After this my output is:
```
asset bundle.js 132 KiB [compared for emit] [minimized] (name: main) 1 related asset
cached modules 242 KiB [cached] 43 modules
webpack 5.70.0 compiled successfully in 155 ms
```

**Comment by jon-link-jon** [comment]
Thanks for your responses.  However, I would like to understand why my system takes 4 seconds to create and empty project.  The includes libraries (react, react-dom, redux) are already transpiled and minified.  So it should just be a simple concatenation operation.  Is there documentation on how to read the standard output?
