### ISSUE TITLE
[Docs] Update README

### ISSUE THREAD

**Issue by guelate** [webpack/webpack#15603]
## Feature request

**What is the expected behavior?**

I want to add the dependency for Twitter

[![Twitter follow](https://img.shields.io/twitter/follow/Webpack?style=social)](https://twitter.com/Webpack)

**What is motivation or use case for adding/changing the behavior?**

I think it is important to put forward the community.

**Comment by alexander-akait** [comment]
Feel free to send a PR

**Comment by yadunandanbhat** [comment]
Is this still open? If yes, then can I work on this?

**Comment by alexander-akait** [comment]
PR welcome

**Comment by yadunandanbhat** [comment]
Also the image beside the "downloads" badge is broken. Should I just delete that?

**Comment by yadunandanbhat** [comment]
![image](https://user-images.githubusercontent.com/54680617/163186804-b0a651c9-dc30-4814-ab47-1a041a4cd15a.png)

**Comment by alexander-akait** [comment]
Ideally will be great to repair it

**Comment by yadunandanbhat** [comment]
Which link did it reference? Because opening it is saying 404 error

**Comment by yadunandanbhat** [comment]
its saying "First-time contributors need a maintainer to approve running workflows". Please approve it!

**Comment by yadunandanbhat** [comment]
The pr is #15667
