### ISSUE TITLE
feature request: '.node' loader

### ISSUE THREAD

**Issue by CxRes** [webpack/webpack#1560]
Webpack seems unable to handle '.node' file. Atleast I could not find a loader and I am told the same when I asked on Stackoverflow: http://stackoverflow.com/questions/33381663/webpack-how-to-load-raw-node-node-files/33381811.

So, if you allow a `target:node` packaging, I think it is reasonable to request a `.node` file loader. 

Thanks in advance if you decide to make it.

**Comment by IngwiePhoenix** [comment]
But there is a node-loader…?

https://github.com/webpack/node-loader <https://github.com/webpack/node-loader>

**Comment by CxRes** [comment]
Thanks @IngwiePhoenix  for pointing this out. 

Its not documented though, I'll edit the documentation...
