### ISSUE TITLE
webpack5 seems to catch the error of promise.reject(), causing the page to crash.

### ISSUE THREAD

**Issue by 24kglod** [webpack/webpack#15602]
# Bug report

**What is the current behavior?**
In my react project built by webpack5, when I encounter promise.reject, the page will report an error.
![image](https://user-images.githubusercontent.com/23623809/160802239-1968f8cc-fd63-41cd-89b3-ae30eb37f592.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
`<button onClick={() => {return Promise.reject()}}>promise rejected</button>`

**What is the expected behavior?**
I think this error should only appear in the console and not on the page.
So what configuration should I go through to prevent this behavior?

**Other relevant information:**
webpack version:  5.28.0
Node.js version:  14.16.0
Operating System:  win11
Additional tools:

**Comment by 24kglod** [comment]
`devServer: {
        client: {
            overlay: false,
        },
}`

**Comment by vankop** [comment]
please provide steps to reproduce. Would be great if you reduce this to reproducible repo. thanks

**Comment by 24kglod** [comment]
> 请提供重现步骤。如果您将其减少到可重现的回购，那就太好了。谢谢
hey bro this is the address of the git repository.
https://github.com/24kglod/webpack5-test

**Comment by vankop** [comment]
this error layout is not from webpack.. not sure which module/plugin adds it..
