### ISSUE TITLE
webpack removes files specified in package.json sideEffects 

### ISSUE THREAD

**Issue by YuanboXue-Amber** [webpack/webpack#15610]
# Bug report

**What is the current behavior?**

Files specified in package.json `sideEffects` is removed

**If the current behavior is a bug, please provide the steps to reproduce.**

Minimum reproduction: https://stackblitz.com/edit/node-thpmrj?file=dist%2Fwebpack.js

Note that _src/lib/package.json_ has `sideEffects: ["./injectDevTools.js"]`, but `injectDevTools.js` does not show up in final result _dist/webpack.js_

Interesting findings while debugging:
I added console logging in `SideEffectsFlagPlugin.js`, it returns true when checking 'injectDevTools.js' against the sideEffects flag

**What is the expected behavior?**
Files specified in sideEffects should be kept. 
In the above example, `injectDevTools.js` should be included in final result _dist/webpack.js_

**Other relevant information:**
webpack version:  5.70.0
Node.js version: 16.14.2
Operating System: 
Additional tools:

**Comment by vankop** [comment]
webpack does not track transitive `sideEffects` ( in your case it technically should be since `index.js` depends on `injectDevTools.js`), so you should mark all files by yourself.

In other words `sideEffects` flag does not have transitive state, so in your case `index.js` is side effects free.

**Comment by YuanboXue-Amber** [comment]
Thanks for the answer, it worked when I have both index.js and injectDevTools.js in the sideEffects array

**Comment by amitbeck** [comment]
@vankop I have a similar issue in an Angular app (See [SO question](https://stackoverflow.com/questions/72390897/why-are-these-modules-imported-for-side-effects-not-included-in-webpack-bundle) for more details).
My `index.ts` imports 2 modules (`abstract-control.ts` and `abstract-control.directive.ts`) for side effects, and exports another module (`custom-control-status.directive.ts`) therefore also acting as a barrel file. `custom-control-status.directive.ts` is imported through the barrel file (`index.ts`), therefore I thought `index.ts` and the 2 modules imported for side effects would be included in the bundle, but they're removed in the tree shaking process. Despite specifying `index.ts`, `abstract-control.ts` and `abstract-control.directive.ts` in my `package.json`'s `"sideEffects"`, they are all excluded from the bundle.
How do I get `abstract-control.ts` and `abstract-control.directive.ts` to be included in the bundle? What am I doing wrong?

**Comment by vankop** [comment]
@amitbeck please create a small reproducible repo I will take a look

**Comment by amitbeck** [comment]
> please create a small reproducible repo

@vankop Here you go: https://github.com/amitbeck/ng-webpack-sideEffects-repro
You should get the following error: `TypeError: this.formGroup.controls.text.setWarnings is not a function`. That means that the files `abstract-control.ts`, `abstract-control.directive.ts` and `index.ts` in `src/app/utils/forms/` were not included in the bundle.
Thanks in advance!
