### ISSUE TITLE
Module Federation, unused modules will also be loaded during initialization

### ISSUE THREAD

**Issue by lzxb** [webpack/webpack#15620]
<img width="1530" alt="image" src="https://user-images.githubusercontent.com/8424643/161375827-f9d9724c-afbf-47d3-bea1-b8fec026ef3b.png">

**Comment by lzxb** [comment]
<img width="958" alt="image" src="https://user-images.githubusercontent.com/8424643/161375893-8bbf94a4-8bec-4d06-9c93-046deef8dd68.png">

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
