### ISSUE TITLE
[Plugins] Wrong path in compiler.options

### ISSUE THREAD

**Issue by frantic** [webpack/webpack#1563]
x-post from https://github.com/gajus/write-file-webpack-plugin/issues/1:

Seems like for some reason [this plugin](https://github.com/gajus/write-file-webpack-plugin/) gets a wrong path in `compiler.options`. In the following case instead of `./dist` I just get `/`. It seems to just use webpack's API so I suspect it's webpack issue.

My config:

```javascript
var WriteFilePlugin = require('write-file-webpack-plugin');

module.exports = {
  entry: "./src/main.js",
  output: {
    path: __dirname + "/dist",
    filename: "bundle.js",
    publicPath: "/dist"
  },
  module: {
    loaders: [{
      test: /\.js$/,
      exclude: /(node_modules|examples)/,
      loader: 'babel-loader?stage=0'
    }]
  },
  plugins: [
    new WriteFilePlugin()
  ]
};
```

but the plugin creates a file in my root - `/bundle.js`. I've added some logging. The config exported from `webpack.config.js` looks like this:

```
{ entry: './src/main.js',
  output:
   { path: '/Users/frantic/code/flexbox/dist',
     filename: 'bundle.js',
     publicPath: '/dist' },
  module: { loaders: [ [Object] ] },
  plugins: [ { apply: [Function: apply] } ] }
```

however inside plugin's `apply` when I `console.log(compiler.options);` I get:

```
{ entry:
   [ '/usr/local/lib/node_modules/webpack-dev-server/client/index.js?http://localhost:8080',
     './src/main.js' ],
  output:
   { path: '/',
     filename: 'bundle.js',
     publicPath: '/dist',
     libraryTarget: 'var',
     sourceMapFilename: '[file].map[query]',
     hotUpdateChunkFilename: '[id].[hash].hot-update.js',
     hotUpdateMainFilename: '[hash].hot-update.json',
     crossOriginLoading: false,
     hashFunction: 'md5',
     hashDigest: 'hex',
     hashDigestLength: 20,
     sourcePrefix: '\t',
     devtoolLineToLine: false },
  module:
   { loaders: [ [Object] ],
     ...
```

(note different `output.path` in both cases)

webpack v1.12.2

cc @gajus

**Comment by gajus** [comment]
This appears to be either a bug or undocumented behaviour (https://github.com/gajus/write-file-webpack-plugin/issues/1#issuecomment-152236151).

Regardless, how do I get the original `output.path`?

**Comment by sokra** [comment]
This happens with the webpack-dev-server. It compiles in-memory so there is no need for a output path.

**Comment by pksjce** [comment]
This issue was moved to webpack/webpack.io#149
