### ISSUE TITLE
Webpack does not watch for file changes

### ISSUE THREAD

**Issue by marekwalach** [webpack/webpack#15638]
I want webpack to build expressjs written in typescript and use nodemon to serve (locally) app on each file change. I cant make webpack to watch correctly  - it reloads on package.json or on webpack.config.js files change but not on actual app files.

When i run `npx webpack` it builds and serve app correctly  but nothing is happening on file change.

My setup:
package.json:
```
{
  "name": "fake-api-test",
  "version": "1.0.0",
  "scripts": {
    "serve": "npx webpack"
  },
  "dependencies": {
    "express": "^4.17.3"
  },
  "devDependencies": {
    "@types/express": "^4.17.13",
    "nodemon": "^2.0.15",
    "ts-loader": "^9.2.8",
    "typescript": "^4.6.3",
    "webpack": "^5.71.0",
    "webpack-cli": "^4.9.2",
    "webpack-shell-plugin-next": "^2.2.2"
  }
}
```

webpack.config.js:
```
const path = require('path');
const WebpackShellPluginNext = require('webpack-shell-plugin-next');

module.exports = () => {
    return {
        entry: './src/app.ts',
        mode: 'development',
        target: 'node',
        watch: true,
        output: {
            filename: 'app.js',
            path: path.resolve(__dirname, 'build')
        },
        module: {
            rules: [
                {
                    test: /\.ts?$/,
                    use: 'ts-loader',
                    exclude: /node_modules/
                }
            ]
        },
        resolve: {
            extensions: ['.ts', '.js']
        },
        plugins: [
            new WebpackShellPluginNext({
                onBuildEnd: {
                    scripts: ['npx nodemon build/app.js']
                }
            })
        ]
    }
};
```
src/app.ts
```
import express from 'express';
const app = express();

app.get('/', (req, res) => {
    res.send('hello world');
})

const port =  2666;
app.listen(port, () => {
    console.log('App is ready');
})
```

webpack version:  `5.71.0`
Node.js version: `16.13.2`
Operating System: `MacOS 12.2.1`

**Comment by vankop** [comment]
does webpack rebuild? or it just does not reload? Could you create small reproducible repo please?

**Comment by marekwalach** [comment]
On app.ts change it does nothing. 
Here is repo: https://github.com/marekwalach/webpack-express-ts-watch-test

**Comment by await-ovo** [comment]
> On app.ts change it does nothing. Here is repo: https://github.com/marekwalach/webpack-express-ts-watch-test

I just looked at the code in the repository and webpack rebuild is working fine, maybe just need to set the WebpackShellPluginNext's onBuildEnd scripts to `paralle: true`:

```js
 plugins: [
            new WebpackShellPluginNext({
                onBuildEnd: {
                    scripts: ['npx nodemon build/app.js'],
                    parallel: true,
                }
            })
        ]
```

**Comment by marekwalach** [comment]
@await-ovo thank you - it was it. After adding `parallel: true` everything is working as expected.
