### ISSUE TITLE
in-operator broken; `"property" in object` ALWAYS gets inlined as true

### ISSUE THREAD

**Issue by JTBrinkmann** [webpack/webpack#15633]
# Bug report

**What is the current behavior?**

Webpack v5 incorrectly evaluates & bundles `"property" in object` as `true`, when `object` imported from a different file, even if the property is not present in the object (e.g. `"doesNotExist" in { }`).

**If the current behavior is a bug, please provide the steps to reproduce.**

create the following files (e.g. in an empty src folder):
```js
// testObject.js
export const testObject = {}
```
```js
// main.js
import { testObject } from './testObject'
console.log('property' in testObject ? 'buggy' : 'not buggy')
```
With or without a webpack configuration, run webpack (e.g. `npx webpack-cli`).
Inspect the emitted bundle. (below: without a configuration file)
```js
// main.js (NODE_ENV=production)
!function(){"use strict";console.log("buggy")}();
```
```js
// main.js (NODE_ENV=development)
... console.log(true ? 'buggy' : 'not buggy') ...
```

**What is the expected behavior?**

The expression `'property' in testObject` should evaluate to `false`, or be evaluated at runtime.

For comparison, with webpack v4 or when using terser directly, I get
```js
console.log("property"in{}?"buggy":"not buggy")}
```

**Workarounds:**

The issue does not appear / can be worked around if `testObject` is defined within the same file or if it's indirectly referenced. The following three examples work correctly:
```js
import { testObject } from './testObject'
console.log('property' in (0, testObject) ? 'buggy' : 'not buggy')  // => not buggy

const indirectReference = testObject
console.log('property' in indirectReference ? 'buggy' : 'not buggy')  // => not buggy

const testObject2 = {}
console.log('property' in testObject2 ? 'buggy' : 'not buggy')  // => not buggy
```

**Other relevant information:**
webpack version:  5.71.0
Node.js version: v16.14.0
Operating System: Windows 10

This appears to be the root of https://github.com/chakra-ui/chakra-ui/issues/5804 and https://github.com/chakra-ui/chakra-ui/issues/5812, where currently downgrading to webpack v4 (by downgrading react-scripts) is suggested as a workaround.

**Comment by vankop** [comment]
yeah, please use `webpack@5.70` for now..

**Comment by stefanKuijers** [comment]
I can verify, we had to step back to 5.70 as well

**Comment by yoyo837** [comment]
This issue also breaks react-redux.

**Comment by Quovadisqc** [comment]
Might help someone that also have the same issue as I had but this also breaks 
[Socket-io](https://github.com/socketio/socket.io-client) by making connections throw timeouts because of this
[this function](https://github.com/socketio/engine.io-client/blob/master/lib/transports/websocket.ts#L238)

**Comment by DavidDudson** [comment]
@Quovadisqc We had to rollback to webpack 5.70 due to the use of socke.io aswell.

**Comment by cdeutsch** [comment]
Is this fixed for people in `v5.72.0`?

I'm still stuck on `v5.70.0`, but it's possible it's not the same issue.

**Comment by yoyo837** [comment]
> This issue also breaks `react-redux`.

I'm just as confused, `5.72.0` still breaks `react-redux`.

**Comment by yoyo837** [comment]
Double decorators.

```js
@SomeDecorators1()
@SomeDecorators2()
export default Class1 {
}
```

**Comment by yoyo837** [comment]
> @yoyo837 could you reduce your reproducible repo?

I'll try it.

**Comment by yoyo837** [comment]
[mini-repo.zip](https://github.com/webpack/webpack/files/8472350/mini-repo.zip)


1. yarn/npm install
2. yarn/npm run dev

I got ` Could not find "store" in the context of "Connect(TestComp)". Either wrap the root component in a <Provider>, or pass a custom React context provider to <Provider> and the corresponding React context consumer to Connect(TestComp) in connect options.`

I found the solution as below:

1. Downgrade webpack to 5.70.0.
2. remove Drawer `handler` props in `src\routes\App.js`. (Don't know the reason at the moment)
3. remove the decorator `@connect()`  in `src\routes\App.js` - class `TestComp`. (Do not use `redux`)

**Comment by alexander-akait** [comment]
@vankop Looks like still valid

**Comment by cdeutsch** [comment]
> I got Could not find "store" in the context of "Connect(TestComp)". Either wrap the root component in a <Provider>, or pass a custom React context provider to <Provider> and the corresponding React context consumer to Connect(TestComp) in connect options.

I'm getting a similar error in `mobx-react@6.3.0`
> Store 'myStore' is not available! Make sure it is provided by some Provider

When I have a nested `<Provider>`, the props provided by the parent are missing. 

Was thinking this could be a different issue than `in`
