### ISSUE TITLE
Allow resolve plugins to handle fs when target is node 

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [webpack/webpack#15635]
## Feature request

I have target set to `node`, so webpack automatically sets fs as external. I want my resolve plugin to still be able to modify imports to `fs`.

**What is the expected behavior?**
When a resolve plugin does `resolver.hooks.resolve.tapPromise`, it should be able to handle Node.js modules like `fs` and `http`. 

**What is motivation or use case for adding/changing the behavior?**
I want to use webpack for mocking modules when testing. When I import `jsonfile` I want it to use a mock file system. For that I need to change imports from `fs` to `memfs`

**How should this be implemented in your opinion?**
Let the resolve plugins modify requests to external modules. Also let the plugins mark a module as external.

**Are you willing to work on this yourself?**
no

**Comment by vankop** [comment]
use `externals` option, e.g.
```
externals: { fs: "Memfs" },
```
and in entrypoint
```js
global.Memfs = require("memfs");
```

**Comment by ChocolateLoverRaj** [comment]
@vankop That doesn't solve my issue because I want to replace `fs` with `memfs` conditionally, depending on the path of the file which is importing `fs`.

**Comment by vankop** [comment]
external could be a function in case of fs resolving to fs external should looks like `externals: { fs: "commonjs fs"}`
