### ISSUE TITLE
webpack @font-face problem

### ISSUE THREAD

**Issue by a6965921** [webpack/webpack#15646]
webpack @font-face problem
`@font-face {
    font-family: 'iconfont';  /* project id 2838616 */
    src: url('');
    src: url('?#iefix') format('embedded-opentype'),
    url('https://at.alicdn.com/t/font_2838616_h34s9inm0q.woff2') format('woff2'),
    url('https://at.alicdn.com/t/font_2838616_h34s9inm0q.woff') format('woff'),
    url('https://at.alicdn.com/t/font_2838616_h34s9inm0q.ttf') format('truetype'),
    url('#iconfont') format('svg');
}
    
  .iconfont {
      font-family: "iconfont" !important;
      font-style: normal;
      -webkit-font-smoothing: antialiased;
      -moz-osx-font-smoothing: grayscale;
  }`

run it  but  can't load url above   and no show error

**Comment by vankop** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us by recreating the issue using one of our templates.

Please fill out all fields, we can't help you without it
