### ISSUE TITLE
Webpack 5 Module Federation error when using  optimization.runtimeChunk

### ISSUE THREAD

**Issue by bingoYB** [webpack/webpack#15641]
I want to use the module federation feature , but I have a problem when using  attributes `optimization.runtimeChunk`，the error message is as follows:
```
Uncaught ScriptExternalLoadError: Loading script failed.
(missing: http://localhost:3002/remoteEntry.js)
while loading "./App" from webpack/container/reference/app2
    at Object.webpack/container/reference/app2 (main.js:266:25)
    at __webpack_require__ (main.js:308:33)
    at initExternal (main.js:584:28)
    at Function.__webpack_require__.I (main.js:597:15)
    at main.js:1101:47
    at Object.webpack/sharing/consume/default/react/react?5e40 (main.js:1155:72)
    at main.js:1188:56
    at Array.forEach (<anonymous>)
    at Object.__webpack_require__.f.consumes (main.js:1171:36)
    at main.js:389:40

```
and the demo of the problem is reproducible below
https://stackblitz.com/edit/github-hdudnt-pjkjaw?file=app2/webpack.config.js

**Comment by alexander-akait** [comment]
Sorry you link is broken and I can't open it

**Comment by YangtzeQi** [comment]
i can open it now and i have the same problem
`Loading script failed.
(error: http://localhost:9999/remoteEntry.js)
while loading "./payments" from webpack/container/reference/pwm`

**Comment by kasec** [comment]
Any updates of this?
I'm having a similar issue.

**Comment by vankop** [comment]
in this case you should import remote runtime chunk by yourself

**Comment by cfaester** [comment]
> in this case you should import remote runtime chunk by yourself
> 
> In output you have something like `runtime~main.js` and `runtime~app2.js`. so you need to import `runtime~app2` by yourself

For anyone who stumbles upon this; what they mean is, where you have your   
`<script src="http://localhost:3002/remoteEntry.js"></script>`  in app1  
you should also have a  
 `<script src="http://localhost:3002/runtime~app2.js"></script>` tag.

**Comment by ScriptedAlchemy** [comment]
Runtime:false on the MF plugin

**Comment by vinayashreeram** [comment]
any help on this 
tried everything its not working
getting error like this 

ScriptExternalLoadError: Loading script failed.
(missing: http://localhost:1234/copilotEntry.js)
while loading "./CopilotBtn" from webpack/container/reference/Copilot

**Comment by romanshutsman** [comment]
it helped me (since I had shared packages):

    optimization: {
        splitChunks: false,
    },
    
    or you can remove at all optimization section
