### ISSUE TITLE
Circular dependency not working with worker-loader?

### ISSUE THREAD

**Issue by trusktr** [webpack/webpack#1564]
I've got package A that depends on package B, which depends on package C (worker), which depends on package A.

I'm getting an error like this: http://trusktr.io:7777/ixujinuzij

**Comment by trusktr** [comment]
To reproduce, clone github.com/infamous/webpack-skeleton and checkout the webpack-issue-1564 branch, then clone github.com/infamous/motor and and checkout the webpack-issue-1564 branch. Then, `npm install && npm run prepublish && npm link` inside the infamous/motor repo, then `npm install && npm link motor.js && webpack` inside the infamous/webpack-skeleton repo and you should see the error.

**Comment by trusktr** [comment]
If it's something I'm doing wrong with the way I'm importing things, what might you recommend?

**Comment by trusktr** [comment]
Could this be the issue, https://github.com/webpack/worker-loader/issues/5, that a new worker file with a new name is made in each loop of the circle?

**Comment by trusktr** [comment]
I guess not. I tried configuring webpack with 

```js
    worker: {
        output: {
            filename: "[name].worker.js",
        },
    },
```

but the problem still happens, except that this time only a single file is created instead of multiple [hash].worker.js files.

**Comment by trusktr** [comment]
I'm guessing that the problem is that the SceneWorker eventually imports a new SceneWorker, over and over.

**Comment by sokra** [comment]
yep that's propably a problem.

But hey, you can use Workers in Workers, that's cool ;)

The problem is so rar that you either need to:

* refactor your code
* send a PR to the worker-loader fixing the problem (difficult)

**Comment by RReverser** [comment]
I seem to be running into the same issue :( (well, the original snippet is no longer available, but I'm getting OOM in Node.js / V8)

I suppose the "refactor your code" solution still stands?

**Comment by evilebottnawi** [comment]
@RReverser Can you create reproducible test repo?

**Comment by RReverser** [comment]
I think it should be simple enough, yeah - IIUC what's going on, it just requires a regular module importing a Worker one, and a Worker one importing something back from the original module.

Finding time might be a bit more problematic, but I can try sometime later next week.

**Comment by evilebottnawi** [comment]
@RReverser feel free to ping me

**Comment by RReverser** [comment]
@evilebottnawi Ok I've used hello-webpack template on Glitch for a quick start and added a sample circular worker dependency to showcase the issue: https://glitch.com/~obvious-petal-worm

You should be able to see how Glitch instance memory grows while it tries to build the project and then eventually OOMs.

(You can also download the code of the project locally if you want to play with it with custom build of webpack instead.)

**Comment by evilebottnawi** [comment]
@webpack-bot move webpack-contrib/worker-loader
