### ISSUE TITLE
npm install not working properly

### ISSUE THREAD

**Issue by onepseudoxy** [webpack/webpack#15644]
**npm install is not working properly**

**Whenever I run npm install
for example npm i -D webpack webpack-cli
I get the following output

up to date, audited 1 package in 13s

found 0 vulnerabilities**

And in the node_modules: there is no webpack folder and the webpack-cli folder is empty
same goes when I do npm i -D jest

**I expect the module to be installed**

**Environment:**
webpack version:  5.72.0
Node.js version: 16.14.2
Operating System: windows 10
Additional tools: nvm 1.1.9

**Comment by vankop** [comment]
Looks like this installation problem is only on your side.. I don't have any issues.
