### ISSUE TITLE
webpack 5 load image dynamically from different folder

### ISSUE THREAD

**Issue by piyushmani-raj** [webpack/webpack#15651]
I have a webpack 5 and react application and I have to chose a folder at runtime for images based on variable. however I am able to define path using require but in final build images from all folder are included .

const ASSETS_DIR = IVI_CONSTANTS.THEME_CONSTANTS// from external api 

asset-folder1
asset-folder2
asset-folder3

<img src={require(`../../assets/${ASSETS_DIR}/${iconName}.svg`).default} />

but in final prod build all image from all folders are included in build.

**Comment by vankop** [comment]
> however I am able to define path using require but in final build images from all folder are included .

thats how context `require` works. webpack doesn't know which assets you will use and bundle all of them.

**Comment by piyushmani-raj** [comment]
so how to deal with this scenario , I want images from only folder defined by ASSETS_DIR

**Comment by vankop** [comment]
> so how to deal with this scenario , I want images from only folder defined by ASSETS_DIR

simple solution will be
```jsx
<img src={require(`../../assets/ASSETS_DIR/${iconName}.svg`).default} />
```
where `ASSETS_DIR` will be your directory in string format.

Hard solution is to create webpack plugin and evaluate `IVI_CONSTANTS.THEME_CONSTANTS` to string.. like this https://github.com/webpack/webpack/blob/main/lib/dependencies/ImportMetaPlugin.js#L156
