### ISSUE TITLE
Webpack 5 support for --display-modules option

### ISSUE THREAD

**Issue by rese** [webpack/webpack#15654]
Webpack 4 had support for `--display-modules` option which seems to have been deprecated in v5 since passing that option gives me `[webpack-cli] Error: Unknown option '--display-modules'`. I can't seem to find an equivalent in the v5 options and I can't find anything online about it being removed.

**Comment by vankop** [comment]
I'm not familiar with such option, probably it is related to stats. In `webpack@5` there is a lot stats options ( maybe you need `--stats-modules` ) all [stats options in doc](https://webpack.js.org/configuration/stats/)
