### ISSUE TITLE
Question : who uses Webpack ?

### ISSUE THREAD

**Issue by nicodimuss** [webpack/webpack#1565]
Hi. I have a task from my lecturer  to gather a list of projects/companies using webpack, for development.  Logo and a short description on how you use webpack and how it has helped you is also welcome. Thank you very much.!

**Comment by IngwiePhoenix** [comment]
A little questionair? Count me in.

I don't have a logo for the project itself, but I will link you instead the logo of the site that uses it.

![Dragon's Inn logo](http://ingwie.me/o.o/dragonsinn.png)
Project: [BIRD3](https://github.com/DragonsInn/BIRD3)

BIRD3 is a community software that I develop in my free time. Based on a mix of PHP and NodeJS, using the latest technology such as WebPack, laravel, Express, SocketCluster, Hprose and a couple more, this is likely one of the fastest systems that there is. I didn't do a lot of benchmarking, but the fact that an overall process-cache (nData) is used by SocketCluster and cache-able things stored in Redis, make this thing super nice.

In this project, I use WebPack to build my front-end using a subset of JavaScript, [oj](https://github.com/musicthoery/oj). WebPack allows me to run preprocessors and use language dialects with which I feel way more confortable than anything else. It also allows me to take advantage of the newest JavaScript features without a big problem.

I have already supplied a number of own loaders and I have a little PurifyCSS plugin hidden inside the BIRD3 source tree, too!

I think that @sokra's work has seriously improved front-end development as a whole. Wether you're making a single-page app, or a traditional app which uses the WebPack generated assets to still be super awesome.

---
I hope this is what you were looking for. :)

**Comment by bebraw** [comment]
@nicodimuss You could try to ask at [Reactiflux](http://www.reactiflux.com/) perhaps.
