### ISSUE TITLE
What does PrefetchPlugin do?

### ISSUE THREAD

**Issue by halt-hammerzeit** [webpack/webpack#1566]
It says:

```
A request for a normal module, which is resolved and built even before a require to it occurs. This can boost performance.
```

I don't see how it can boost performance.
Why is a nested `require()` much slower than the same root level `require()`?

**Comment by aackerman** [comment]
The plugin is for prefetching assets over the wire before the require is executed. For example prefetching code to render a different view in a single-page app. So while a user is looking at the current page the code for another page that is not in the original page payload is downloaded before the user attempts to navigate to that page.

**Comment by halt-hammerzeit** [comment]
@aackerman oh, that makes sense. But how does it boost Webpack build performance? (as per Analyse Tool hints)

**Comment by aackerman** [comment]
That part is pretty unclear to me, check this out. http://stackoverflow.com/questions/32923085/how-to-optimize-webpacks-build-time-using-prefetchplugin-analyse-tool

**Comment by halt-hammerzeit** [comment]
@aackerman 
ha ha, actually, I've already linked this discussion from that stackoverflow question:
http://stackoverflow.com/a/33415019/970769

I thought that maybe @sokra would answer if he wrote that thing

**Comment by eladmoshe** [comment]
+1

**Comment by loopmode** [comment]
+1

**Comment by pizza2code** [comment]
+1

**Comment by octatone** [comment]
+1

**Comment by DontRelaX** [comment]
+1

**Comment by elektronik2k5** [comment]
+1

**Comment by pigcan** [comment]
+1

**Comment by TheLarkInn** [comment]
@sokra heh I think we need more than a few lines to explain how this one works on our docs.

**Comment by epikhighs** [comment]
uhm... so does this really do anything?  does it help w/ recompile times?

**Comment by Kovensky** [comment]
I tried reading through the code, but all I can find is it setting some flags in the internal module object (prefetch or prefetched), but nothing that actually _reads_ those flags 😕 

The only guess I can make, from the documentation, is that if the specified module would've been split into a separate chunk (via e.g. `require.ensure`), that the webpack bootstrap will attempt to fetch that chunk as soon as possible, instead of having to wait until the `require.ensure` call is hit to start the fetch.

**Comment by jakwuh** [comment]
@Kovensky from what I see that's not totally correct.

Actually, PrefetchPlugin does nothing with bundles and chunks. It only `prefetches` module during compilation (as well as in watch mode) but does not include them into any chunks. I guess this is for the sake of performance. AutomaticPrefetchPlugin is a great example of usage prefetching.

**Comment by Kovensky** [comment]
I am not sure what kind of gain would that sort of prefetching do, unless you're compiling in a distributed filesystem or some other case where I/O is the bottleneck in the compilation...

**Comment by jakwuh** [comment]
@Kovensky sure, that's the question for @sokra

**Comment by andreypopp** [comment]
I think prefetching would shine if we are able to achieve CPU saturation: what about trying this with happypack?

**Comment by sokra** [comment]
> Actually, PrefetchPlugin does nothing with bundles and chunks. It only prefetches module during compilation (as well as in watch mode) but does not include them into any chunks. I guess this is for the sake of performance.

**Comment by Kovensky** [comment]
@sokra but how does what it does help performance?

**Comment by sokra** [comment]
long chains of requires can form a chain where webpack will know about the last module very late. This could slow down the compilation because webpack has to wait for I/O (esp. resolving). The PrefetchPlugin starts modules earlier so I/O is less an concern.

**Comment by Kovensky** [comment]
I also realized that, for my speculated use case of prefetching chunks, you can just do that without needing any plugins by doing a `require.resolve` call that does nothing with the resolved modules.

**Comment by sokra** [comment]
`require.resolve` include the module in the chunk.

**Comment by pksjce** [comment]
This issue was moved to webpack/webpack.io#126
