### ISSUE TITLE
Cannot access '__WEBPACK_DEFAULT_EXPORT__' before initialization

### ISSUE THREAD

**Issue by JesonAnne** [webpack/webpack#15677]
it will close

**Comment by vankop** [comment]
please reduce this to reproducible repo.. I didn't understand from description what could cause this.

**Comment by alexander-akait** [comment]
I think you have circular dependencies

**Comment by JesonAnne** [comment]
> please reduce this to reproducible repo.. I didn't understand from description what could cause this.

I'm sorry I didn't make that clear. With version 5.56 of webpack, when packaging the output, there is one more line defining default ,than in version 4.44. This line of code causes an error to be reported
```
"default": () => (__WEBPACK_DEFAULT_EXPORT__)
```

**Comment by alexander-akait** [comment]
@JesonAnne Sorry without code it is hard to say there is a problem

**Comment by abannachZen** [comment]
@alexander-akait I'm experiencing the same issue with a dependency of a dependency. `@spinnaker/core` depends on `react-virtualized`. I've created a sample repo. Instructions for reproducing are in the Readme https://github.com/abannachZen/test-deck-plugin

Key point I think here is that I'm not really in control of the codebase that contains the circular dependency. It's two layers removed, and the repo owner is unresponsive. See https://github.com/bvaughn/react-virtualized/issues/1308 and stale PR https://github.com/bvaughn/react-virtualized/pull/1609

**Comment by alexander-akait** [comment]
Yep, in this case two solutions:
1. Do fork and fix it (makse sense because if developer doesn't response it means this package can be outdated and it will be a problem in future - new features/fixes/security problems)
2. Build `react-virtualized` using ts in separate command and use JS version inside your code
