### ISSUE TITLE
WebPack使用require函数来导入组件时,会把指定目录下所有的目录全部遍历

### ISSUE THREAD

**Issue by LIBai11** [webpack/webpack#15674]
## Feature request

**What is the expected behavior?**
希望可以改善一下require导入的方式

**What is motivation or use case for adding/changing the behavior?**

比如说xicons这个库有一万多个图标,当我从服务请求回字符串数据后,想通过字符串动态导入这些图标时,就需要用到require,
但这会使我的项目热更新很慢,并且浏览器会因此崩溃

**How should this be implemented in your opinion?**
通过require中的包含的名称参数来动态的辨别大概的位置,比如在文件首字母A-D之间,
或者使用缓存,可以将需要使用的组件缓存起来,避免下次使用再重新遍历

**Are you willing to work on this yourself?**
yes,but my coding skills are not enough

**Comment by alexander-akait** [comment]
Please use the English, thanks

**Comment by LIBai11** [comment]
For example, the library xicons has more than 10,000 icons. When I request string data from the service and want to dynamically import these icons through strings, I need to use require.
But it makes my project hot update very slow and the browser crashes because of it


 use the cache, you can cache the components that need to be used to avoid re-traversing the next time you use it

**Comment by alexander-akait** [comment]
Please reformat your issue using English

**Comment by qq281113270** [comment]
中国网友（Chinese netizens）
