### ISSUE TITLE
Suggestion: replace `json-parse-better-errors` to `json-parse-even-better-errors`

### ISSUE THREAD

**Issue by Semigradsky** [webpack/webpack#15672]
[json-parse-even-better-errors](https://github.com/npm/json-parse-even-better-errors) is a fork of [json-parse-better-errors](https://github.com/zkat/json-parse-better-errors).

Example of improvement in https://github.com/sindresorhus/parse-json/pull/23

**Comment by alexander-akait** [comment]
PR welcome

**Comment by Semigradsky** [comment]
Done
