### ISSUE TITLE
Backporting version detection API across major versions

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack#15679]
## Feature request

**What is the expected behavior?**
The version detection logic for webpack has either not existed, changed, or moved from each Major version of webpack. 

**What is motivation or use case for adding/changing the behavior?**
As I have been working on a variety of Plugins, I have noticed that each project has been using custom webpack version detection logic. In version 5 this is easy because of the addition of `compiler.webpack.version` however this was only added in webpack 5.

See: 
* v4: https://github.com/webpack/webpack/blob/3956274f1eada621e105208dcab4608883cdfdb2/lib/webpack.js#L80
* v5: https://github.com/webpack/webpack/blob/a72548f97037c941db3320397392a329f52db66a/lib/index.js#L123 

We could clean up a variety of detection logic across our community plugins by including `compiler.webpack.version` across our major versions.

**How should this be implemented in your opinion?**
To make this version API consistent and have backwards compatibility (which is essential to the purpose of this plugin), we would want to backport the v5 API into v4/v3/v2/v1 if possible. 

**Are you willing to work on this yourself?**
Yes, however a concern is that a change like this would require patch level bumps to previous versions of webpack.

**Comment by vankop** [comment]
technically latest major plugins versions supports only v4/v5. So you can detect v4 when there is no `compiler.webpack` and vice versa for v5.
