### ISSUE TITLE
How is this AMD implementation broken?

### ISSUE THREAD

**Issue by mendelk** [webpack/webpack#1567]
I have a very basic webpack config file.

My entry file is simple, like so:

```js
var $ = require("jquery");
require("jquery-mousewheel")($)
```

While this compiles, it throws an error in the browser (`Uncaught TypeError: __webpack_require__(...) is not a function`).

This is fixed by disabling AMD like so:

```js
var $ = require("jquery");
require("imports?define=>false!jquery-mousewheel")($)
```

My question is: what is broken about [jquery-mousewheel's AMD implementation](https://github.com/jquery/jquery-mousewheel/blob/1299f364ca13460c19cd1b1db63bad04541f515a/jquery.mousewheel.js#L10-L19) that necessitates this fix?

It seems to be the basic paradigm for AMD.

I can't solve my issue with `imports?define=>false!` because I'm actually requiring *another* vendor lib which requires jquery-mousewheel. I also can't apply it as a global loader, because it conflicts with other custom loaders I have.

Any help would be really appreciated!

**Comment by jnwng** [comment]
so in your first example,
```
require('jquery-mousewheel')($)
```
you're expecting that `require('jquery-mousewheel')` returns a function. however, when webpack is parsing the `jquery-mousewheel` library that you linked, `define` is, well, defined, so it goes into the first branch [here](https://github.com/jquery/jquery-mousewheel/blob/1299f364ca13460c19cd1b1db63bad04541f515a/jquery.mousewheel.js#L12). the result of that expression does **not** return anything, so attempting to pass in `jquery` will fail.

the reason it works when using the `imports` loader is that you're explicitly setting `define` to false, causing it to go into the [second branch](https://github.com/jquery/jquery-mousewheel/blob/1299f364ca13460c19cd1b1db63bad04541f515a/jquery.mousewheel.js#L15), which __does__ return something via `module.exports`.

in the end, you shouldn't need to pass anything to `jquery-mousewheel` - webpack is going to parse the `jquery-mousewheel` file, see the `define(['jquery'], factory)` call, and write it to get the webpack reference to the jquery file and insert the dependency for you.

**Comment by mendelk** [comment]
Aha. I see. So if I understand correctly, it is insufficient to follow a library's directions for importing for ( CJS | AMD ). You need to check out which branch is checked first and explicitly request it in that format.

**Comment by jnwng** [comment]
here's the excerpt about the library instructions, for posterity:
```
In your browser-side javascript:

var $ = require('jquery-browserify');
require('jquery-mousewheel')($);
```
note that it mentions "browser-side" javascript - the key point here is that `webpack` compiles code on the server-side, not on the browser (client) side. the instructions that they provide for server-side usage depend on browserify, but i believe what i mentioned above (just calling `require('jquery-mouse-wheel')`) should work.

see if it does - if it then complains about not having the `$` variable, you may need to look into using the [ProvidePlugin](https://webpack.github.io/docs/shimming-modules.html#plugin-provideplugin).

**Comment by sokra** [comment]
It actually a pretty bad pratice by the module to export different things depending on which module format is supported.

**Comment by bebraw** [comment]
@mendelk Is this relevant still?

**Comment by mendelk** [comment]
Not really. It was never really an issue with webpack, rather a "bug" with another lib (see malihu/malihu-custom-scrollbar-plugin#371), which already has a (hackish?) workaround.

Thanks to all in this thread that helped me, and I'll go ahead and close this 😄 .
