### ISSUE TITLE
Package path ./browser is not exported from package

### ISSUE THREAD

**Issue by LIMPIX31** [webpack/webpack#15687]
# Bug report

Exports in package,json of my npm package :
```json
"exports": {
  ".": "./lib/index.js",
  "./browser": "./lib/browser.js"
},
"typesVersions": {
  "*": {
    "browser": ["lib/browser.d.ts"]
  }
},
```

```ts
import { x } from 'mypackage/browser' // Error
```

**What is the current behavior?**

```
Module not found: Error: Package path ./browser is not exported from package ... (see exports field in ...\package.json)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

This is the repository I used: [Electron-React-Boilerplate](https://github.com/electron-react-boilerplate/electron-react-boilerplate]).
I already created an issue in this repository and got the answer that this problem is related to webpack

**What is the expected behavior?**

I expect the submodule to be successfully imported and built with webpack

**Other relevant information:**
webpack version:  5.71.0
Node.js version: 16.14.2
Operating System: Windows 10
Additional tools: React 18, Electron 18

**Comment by vankop** [comment]
hm.. we have test for this. Could you create reproducible repo?

**Comment by LIMPIX31** [comment]
> hm.. we have test for this. Could you create reproducible repo?

I provided a link to the template I was using, I did not change the webpack settings in it.
Does the fact that I installed my module with `npm link` affect it?

**Comment by vankop** [comment]
maybe.. we need repro to understand your setup, by default this should work..

**Comment by LIMPIX31** [comment]
> maybe.. we need repro to understand your setup, by default this should work.. ( as I said we have tests for this )

This is probably a bug in my package, because I get undefined if I import anything from the root of the package
