### ISSUE TITLE
when using babel-loader ,the results will change in different modes,How should I configure it

### ISSUE THREAD

**Issue by Idcra** [webpack/webpack#15696]
```javascript
//webpack.demo.js
const path = require('path');
module.exports = {
    entry: "./demo.js",
    output: {
        path: path.resolve(process.cwd(), 'dist'),
        clean: true
    },
    module: {
        rules: [
            {
                test: /\.js$/,
                use: {
                    loader: 'babel-loader'
                }
            }
        ],
    },
    mode: "development",
    // mode: "production"
}
```
```javascript
//demo.js
new Promise.all([])
.then(function(){

})
.catch(function(){})
```
development result
![image](https://user-images.githubusercontent.com/49867647/164607521-4b913567-0073-45e6-854c-c38c51ac8fb2.png)
production result
![image](https://user-images.githubusercontent.com/49867647/164607477-dba7a325-eae6-473c-8712-c17c009f8bfc.png)

How can I configure it so that the results do not change

**Comment by Idcra** [comment]
```json
{
"webpack": "^5.72.0",
"babel-loader": "^8.2.5",
"@babel/preset-env": "^7.16.11",
"@babel/core": "^7.17.9",
}
```

**Comment by Idcra** [comment]
> ```js
> //webpack.demo.js
> const path = require('path');
> module.exports = {
>     entry: "./demo.js",
>     output: {
>         path: path.resolve(process.cwd(), 'dist'),
>         clean: true
>     },
>     module: {
>         rules: [
>             {
>                 test: /\.js$/,
>                 use: {
>                     loader: 'babel-loader'
>                 }
>             }
>         ],
>     },
>     mode: "development",
>     // mode: "production"
> }
> ```
> 
> ```js
> //demo.js
> new Promise.all({})
> .then(function(){
> 
> })
> .catch(function(){})
> ```
> 
> development result ![image](https://user-images.githubusercontent.com/49867647/164605989-3c924789-6a94-492e-9afa-4bc129c95131.png) production result ![image](https://user-images.githubusercontent.com/49867647/164606059-7e7b5281-7ccb-4aa2-9d8e-6d28ce79de6c.png)
> 
> How can I configure it so that the results do not change

**Comment by vankop** [comment]
not sure what you expect. On second screenshot there is `devtool` enabled. you can set `devtool=false`.

**Comment by Idcra** [comment]
changed  ["catch"] to .catch, But i need ["catch"]

**Comment by Idcra** [comment]
i want webpack not to  change the babel-loader result 

> not sure what you expect. On second screenshot there is `devtool` enabled. you can set `devtool=false`.

**Comment by alexander-akait** [comment]
webpack doesn't change babel output, it done by terser check your options
