### ISSUE TITLE
Webpack v5 may be not come with the latest terser-webpack-plugin out of the box.  

### ISSUE THREAD

**Issue by ZheningLin** [webpack/webpack#15694]
# Bug report

**What is the current behavior?**
Webpack v5 may be not come with the latest terser-webpack-plugin out of the box.

<img width="533" alt="image" src="https://user-images.githubusercontent.com/20638584/164472249-fda6ace6-f5fc-408c-9460-7f3a3c51ab53.png">

<img width="684" alt="image" src="https://user-images.githubusercontent.com/20638584/164472403-f943346b-d904-4106-8eee-4e963267349b.png">
 

**If the current behavior is a bug, please provide the steps to reproduce.**

If minimizer has configuration item （such as: new CssMinimizePlugin(), not TerserPlugin),  OptimizationDefaults can not apply TerserPlugin. 
 
In 'A' function, it should judge configuration item.

<img width="688" alt="image" src="https://user-images.githubusercontent.com/20638584/164472989-633f6b7d-c819-4d8e-bd77-d128852a90ca.png">

<img width="538" alt="image" src="https://user-images.githubusercontent.com/20638584/164480353-9cc6d475-cb29-4556-9e12-af6fb3d4c41e.png">

**What is the expected behavior?**

It should judge if the configuration item contains the TerserPlugin. If not, it should apply TerserPlugin.

Webpack v5 **can** come with the latest terser-webpack-plugin out of the box.

**Other relevant information:**
webpack version:   5.72.0
Node.js version:  16.3.0
Operating System: macOS
Additional tools:

**Comment by vankop** [comment]
you should use `optimization: { minimizer: ["...", new YourMinimizerPlugin()] }`

**Comment by ZheningLin** [comment]
> you should use `optimization: { minimizer: ["...", new YourMinimizerPlugin()] }` to make defaults work

Thxs.It works, but it doesn't seem very elegant. The doc can add relevant hint.
