### ISSUE TITLE
Output statically resolvable dynamic import expressions

### ISSUE THREAD

**Issue by jacobp100** [webpack/webpack#15697]
## Feature request

**What is the expected behavior?**

If I have the following,

```js
import('test.js')
```

with the config,

```js
module.exports = {
  output: {
    chunkFormat: "module",
  },
  target: ["web", "es2020"],
};
```

You get the following output

```js
(()=>{var e,t,r,o,n={},f={};function i(e){var t=f[e];if(void 0!==t)return t.exports;var r=f[e]={exports:{}};return n[e](r,r.exports,i),r.exports}i.m=n,t=Object.getPrototypeOf?e=>Object.getPrototypeOf(e):e=>e.__proto__,i.t=function(r,o){if(1&o&&(r=this(r)),8&o)return r;if("object"==typeof r&&r){if(4&o&&r.__esModule)return r;if(16&o&&"function"==typeof r.then)return r}var n=Object.create(null);i.r(n);var f={};e=e||[null,t({}),t([]),t(t)];for(var u=2&o&&r;"object"==typeof u&&!~e.indexOf(u);u=t(u))Object.getOwnPropertyNames(u).forEach((e=>f[e]=()=>r[e]));return f.default=()=>r,i.d(n,f),n},i.d=(e,t)=>{for(var r in t)i.o(t,r)&&!i.o(e,r)&&Object.defineProperty(e,r,{enumerable:!0,get:t[r]})},i.f={},i.e=e=>Promise.all(Object.keys(i.f).reduce(((t,r)=>(i.f[r](e,t),t)),[])),i.u=e=>e+".js",i.o=(e,t)=>Object.prototype.hasOwnProperty.call(e,t),i.r=e=>{"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},r={179:0},o=e=>{var t,o,{ids:n,modules:f,runtime:u}=e,a=0;for(t in f)i.o(f,t)&&(i.m[t]=f[t]);for(u&&u(i);a<n.length;a++)o=n[a],i.o(r,o)&&r[o]&&r[o][0](),r[n[a]]=0},i.f.j=(e,t)=>{var n=i.o(r,e)?r[e]:void 0;if(0!==n)if(n)t.push(n[1]);else{var f=import("./"+i.u(e)).then(o,(t=>{throw 0!==r[e]&&(r[e]=void 0),t}));f=Promise.race([f,new Promise((t=>n=r[e]=[t]))]),t.push(n[1]=f)}},i.e(4).then(i.t.bind(i,4,23))})();
```

Notably - the `import("./"+i.u(e))`

Is there a way to force this to output a statically analysable import statement (i.e. `import("./4.js")`)?

**What is motivation or use case for adding/changing the behavior?**

If you're using webpack to produce libraries that may be used in other build tools (including webpack), statically analysable imports improve optimisations

**How should this be implemented in your opinion?**

The current config should produce statically analysable imports

```diff
-(i.e = (e) =>
-    Promise.all(Object.keys(i.f).reduce((t, r) => (i.f[r](e, t), t), []))),
+(i.e = (e, importFunction) =>
+    Promise.all(Object.keys(i.f).reduce((t, r) => (i.f[r](e, t, importFunction), t), []))),
-(i.u = (e) => e + ".js"),
 (i.f.j = (e, t, importFunction) => {
     var n = i.o(r, e) ? r[e] : void 0;
     if (0 !== n)
     if (n) t.push(n[1]);
     else {
-        var f = import("./" + i.u(e)).then(o, (t) => {
+        var f = importFunction().then(o, (t) => {
         throw (0 !== r[e] && (r[e] = void 0), t);
         });
         (f = Promise.race([f, new Promise((t) => (n = r[e] = [t]))])),
         t.push((n[1] = f));
     }
 }),
-i.e(4).then(i.t.bind(i, 4, 23));
+i.e(4, () => import("./4.js")).then(i.t.bind(i, 4, 23));
```

**Are you willing to work on this yourself?**

No - this is way out of my depth 😅

**Comment by alexander-akait** [comment]
No, it is impossible, we need public path, otherwise it will not work

**Comment by jacobp100** [comment]
@alexander-akait If you follow the logic, the exact same behaviour happens - `import()` is called with `./4.js`. The only change is that in my proposal, there is no abstraction between the `import()` function and its argument, so it's fully statically analysable.

**Comment by alexander-akait** [comment]
Why you need it? There are more logic in `i.t`, look at uncompressed code, if you want to create library with statically analizable code there is another issue about it

**Comment by jacobp100** [comment]
> If you're using webpack to produce libraries that may be used in other build tools (including webpack), statically analysable imports improve optimisations

Webpack itself really benefits from having static import expressions - so it only makes sense that it should be able to output them as such.

With the changes I've demonstrated, it does work as expected. It doesn't really matter what's happening in `i.t.` here - that happens after the module has been imported.

**Comment by alexander-akait** [comment]
> Webpack itself really benefits from having static import expressions - so it only makes sense that it should be able to output them as such.

Again, we have public path and we should respect it `import("./4.js"))` will not work, not each application have relative assets, there are more different approaches to store assets.

Also there are more JS size, that is not good, can you answer why you need it?

**Comment by jacobp100** [comment]
Yeah - if you set a public path, the `"./4.js"` would be updated in accordance with that. That's what currently happens in the `i.u` function. I'm not seeing the issue.

> can you answer why you need it?

I'm really not sure which bit isn't clear. Non-statically analysable dynamic imports cause problems for about every build tool - including webpack. If you use webpack to build a library that makes use of a statically analysable dynamic import in its uncompiled code, it is not possible to produce an output that has this dynamic import and retains the static analysis.

As you can see in the example, `import("./test")` was fully statically analysable, and webpack knew exactly what to do. In the ouput, `import("./" + someFunction)` is not fully statically analysable.

**Comment by alexander-akait** [comment]
> Yeah - if you set a public path, the "./4.js" would be updated in accordance with that. That's what currently happens in the i.u function. I'm not seeing the issue.

Default public path is "auto", so we need `currentScript` and more logic than just `update string`

> It's duplicated though, so it will hardly affect anything after gzip

Not really

> I'm really not sure which bit isn't clear. Non-statically analysable dynamic imports cause problems for about every build tool - including webpack. If you use webpack to build a library that makes use of a statically analysable dynamic import in its uncompiled code, it is not possible to produce an output that has this dynamic import and retains the static analysis.

There is another issue about it as I written above https://github.com/webpack/webpack/issues/2933

There are two common solutions for using webpack:
- application, we need more logic for public path and it is impossible to output statically analyzable `import()` (in theory it is possible but we many limitations and I don't see any cons to do it)
- library https://github.com/webpack/webpack/issues/2933, you need to use it to setup webpack to output statically analyzable code
