### ISSUE TITLE
How do I migrate file-loader with postTransformPublicPath to asset?

### ISSUE THREAD

**Issue by p3k** [webpack/webpack#15693]
We currently apply the following file-loader configuration:

```js
{
	test: imageFileExtensions,
	loader: "file-loader",
	options: {
		name: "[path][name].[ext]",
		outputPath: url => getRelativeImagePath(url),
		publicPath: url => getRelativeImagePath(url),
		postTransformPublicPath: p => `__webpack_public_path__ + ${p}`
	}
}
```

According to the docs, migrating this loader with the asset module should look something like this:

```js
{
	test: imageFileExtensions,
	type: "asset/resource",
	generator: {
		filename: "[path][name][ext]",
		outputPath: url => getRelativeImagePath(url),
		publicPath: url => getRelativeImagePath(url)
		// postTransformPublicPath???
	}
}
```

However, as the commented line indicates, there is no support for the `postTransformPublicPath` option in the asset module…

How would I proceed from here, any suggestions?

**Comment by vankop** [comment]
there is no `postTransformPublicPath` alternative. webpack does `__webpack_public_path__ + ${p}` by default

**Comment by p3k** [comment]
ah ok thanks for the hint @vankop – is this documented somewhere?

**Comment by vankop** [comment]
no, this is webpack internal. 
wait.. I think if you use `publicPath` it will not concatenate `__webpack_public_path__ + ${p}`, otherwise it will respect `__webpack_public_path__` ( this need to be documented, yes)

**Comment by p3k** [comment]
> So if you have output. publicPath, generator.publicPath should be output. publicPath + your path ( if you need to respect output. publicPath )

hm, not sure i understand this. what should the generator look like, also regarding the concatenation of `__webpack_public_path__ + ${p}` is not happening when i use `publicPath`?


like this?

```js
{
  publicPath: url => `__webpack_public_path__ + ${getRelativeImagePath(url)}`
}
```

**Comment by vankop** [comment]
e.g. you have
webpack.config.js
```js
module.exports = {
  output: { publicPath: "/public" },
  module: {
     rules: [
       {
         type: "asset",
         generator: {
             publicPath: "/public-asset"
         }
       }
     ]
  }
};
```
webpack will generate `/public-asset` for assets, if you need to respect `output.publicPath` you should pass `generator.publicPath="/public/public-asset"`

**Comment by ReinisV** [comment]
what if the public path is not known at build time but only at runtime? 
with `postTransformPublicPath` you could pass code, which would be executed in the browser and evaluate the public path there.

**Comment by p3k** [comment]
I was really struggling with this – somehow missing the following remark in https://github.com/webpack/webpack/issues/15693#issuecomment-1104984527:

> wait.. I think if you use `publicPath` it will not concatenate `__webpack_public_path__ + ${p}`, otherwise it will respect `__webpack_public_path__` ( this need to be documented, yes)

So my current understanding is:

1. Generally, `__webpack_public_path__` is still supported with asset modules
2. If `generator.publicPath` is *undefined* `__webpack_public_path__` will be prepended to an asset’s path
3. **If `generator.publicPath` is *defined* this disables prepending of `__webpack_public_path__`**
4. `generator.postTransformPublicPath` is *not supported* with asset modules – `generator.publicPath` must be used for piecing together the desired path (see 3.)

It looks like this is stilll undocumented, especially 3. – which is not obvious at all.
