### ISSUE TITLE
Caught Exception on Line in _iter-detect.js Module

### ISSUE THREAD

**Issue by JF0001** [webpack/webpack#15704]
**Do you want to request a *feature* or report a *bug*?** Question

Upon a page refresh, the debugger stops on `Array.from(riter, function () { throw 2; });` line of the _iter-detect.js module below. What is the root cause of this?

`var ITERATOR = require('./_wks')('iterator');
var SAFE_CLOSING = false;

try {
  var riter = [7][ITERATOR]();
  riter['return'] = function () { SAFE_CLOSING = true; };
  // eslint-disable-next-line no-throw-literal
  Array.from(riter, function () { throw 2; });
} catch (e) { /* empty */ }

module.exports = function (exec, skipClosing) {
  if (!skipClosing && !SAFE_CLOSING) return false;
  var safe = false;
  try {
    var arr = [7];
    var iter = arr[ITERATOR]();
    iter.next = function () { return { done: safe = true }; };
    arr[ITERATOR] = function () { return iter; };
    exec(arr);
  } catch (e) { /* empty */ }
  return safe;
};`

**What is the expected behavior?** Please see above.

**If this is a feature request, what is motivation or use case for changing the behavior?** No

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.** Any latest browser. Webpack 4, Ubuntu

**Comment by vankop** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us by recreating the issue using one of our templates.

Please fill out all fields, we can't help you without it

**Comment by JF0001** [comment]
My apologies @vankop You are right, I was looking in the wrong library. I will close this case.
