### ISSUE TITLE
devServer.static set false is Not effective

### ISSUE THREAD

**Issue by galaxy-s10** [webpack/webpack#15703]
```js
module.exports = {
  //...
  devServer: {
    static: false,
  },
};
```
is no effective，public still is static directory

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

**Comment by galaxy-s10** [comment]
> 感谢您创建此问题。但是，问题需要遵循我们的模板之一，以便我们可以清楚地了解您的特定情况。
> 
> 请帮助我们通过使用我们的模板之一重新创建问题来帮助您。

thank you,i knowed my encounter the problem, i created mini demo ,found is no webpack problem, is me problem
