### ISSUE TITLE
unable to access on Windows10 platform

### ISSUE THREAD

**Issue by sdeass** [webpack/webpack#15702]
# Bug report

**What is the current behavior?**

able to access on Mac OS platform , unable to access on Windows10 platform when I tried to run npm run dev 

**If the current behavior is a bug, please provide the steps to reproduce.**

wish can access  on Windows10 

**What is the expected behavior?**

**Other relevant information:**
webpack version:  
    "webpack": "^5.24.2",
    "webpack-bundle-analyzer": "^4.4.0",
    "webpack-cli": "^3.3.12",
    "webpack-dev-server": "^3.11.2",
    "webpack-merge": "^5.7.3",
    "webpackbar": "^5.0.0-3"
Node.js version: v16.14.2  npm 8.7.0
Operating System: vmware windows 10
Additional tools:

**Comment by alexander-akait** [comment]
Sorry, not related to webpack, please use stackoverflow for questions
