### ISSUE TITLE
What is the proper way to consume a dependency that also uses webpack?

### ISSUE THREAD

**Issue by ropez** [webpack/webpack#1570]
Using this as an example: https://github.com/clappr/clappr (but I'm having similar issues with several libraries that I'm trying to use)

In my project, I've defined `clappr` as a dependency, and added this inside one of my source files:

```
import { Player } from 'clappr'
```

Trying to understand how this works, I've found that what I'm actually loading here, and including in my bundle is `dist/clappr.min.js` as defined in the package.json of the dependency. Is this the proper way to load a dependency?

Now, I'm able to use the Javascript library like this, but it turns out that there are CSS and Fonts bundled with the dependency, and the fonts fail to load in my app. In the webpack.config.js of the dependency, I find this:

```
loaders: [
   ...
   test: /\.(png|woff|eot|ttf|swf)/, loader: 'url-loader?limit=1'
   ...
]
```

In _my_ webpack config, I have something similar, but that does not seem to have any effect in this case. So I tried to include `clappr/src/main` in my project instead, but it turns out that this doesn't work, since the dependency is defining a custom `resolve.root` path, and use that to resolve imports rather than relative paths.

I could probably set up my project to include the `root` path of the dependency, but it seems like a bad idea to be copying the entire webpack configuration from the dependency in order to consume it.

What am I missing? Is it possible to make _my_ webpack config somehow _include_ the config from the dependency? Since I'm using webpack, and trying to consume a dependency that is also using webpack, it should be very easy, right? Is it something wrong with the way they are building `clappr`, or is it something wrong with the way I'm trying to use it?

**Comment by twDuke** [comment]
Also interested

**Comment by acthp** [comment]
I'm also stuck on this. webpack will complain if you require() another webpack bundle. But how else can you do it? The docs are silent. The dependency has its own webpack config.

**Comment by bebraw** [comment]
It's probably better to forget a dependency might use webpack and treat it as a black box instead. Ideally you should be able to consume it as a node package.

I can see how images etc. could be problematic, though, so local adjustments may be needed. You can push issues like this upstream and see what the package authors have to say. Bundling images/fonts to a distribution bundle doesn't seem nice to me.
