### ISSUE TITLE
Problem with importing library that contains dynamic imports

### ISSUE THREAD

**Issue by fabb** [webpack/webpack#15708]
There is a problem when a library is built with webpack, and includes dynamic imports, and then is used in an app that uses webpack too.

## Reproduction

We need a lib that is built with webpack and includes a dynamic import and .d.ts types. And we need an app that is built with webpack too and that imports the lib.

See https://github.com/fabb/webpack-wrapped-dynamic-dependency-problem

### Expected Result

The app should build successfully.

### Actual Result

There is a compile error:

```
Failed to compile.

../lib/libraryDist/dyn.d.ts
Module parse failed: Unexpected token (1:8)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> declare namespace _default {
|     const x: string;
| }

Import trace for requested module:
../lib/libraryDist/ sync ^\.\/.*$
../lib/libraryDist/main.js
./pages/index.tsx
```

## Root Cause Analysis

The built library (`lib/libraryDist/main.js`) contains this code which is generated to dynamically load chunks:

```
(o.f.require = (r, t) => {
    e[r] ||
        ((r) => {
            var t = r.modules,
                n = r.ids,
                i = r.runtime
            for (var f in t) o.o(t, f) && (o.m[f] = t[f])
            i && i(o)
            for (var u = 0; u < n.length; u++) e[n[u]] = 1
        })(require('./' + o.u(r)))
})
```

This is the problematic part: `require('./' + o.u(r))`. This style of require is interpreted as a [Wrapped Dynamic Import](https://webpack.js.org/configuration/module/#module-contexts) by the app that imports the library. That is why in the webpack import trace, we see this: `../lib/libraryDist/ sync ^\.\/.*$`.

So basically the issue is that webpack in the app does not know which chunks of the lib are loaded dynamically because of the way the dynamic loading code is generated in the lib webpack build. Webpack in the app just sees `*.*` and also tries to load the `.d.ts` files, which should not be loaded and fail the build because there is no loader for them.

There is an additional problem: because of the interpretation of `*.*` in the app build, all of the dynamically loaded chunks of the library are put into a single chunk in the application build output, basically turning dynamic imports into static imports. The resulting chunk gets unnecessarily big, because it contains code that is not needed at runtime.

Do you have any suggestions on how to resolve this issue? I think one way to the solution would be to somehow preserve the dynamic import statements in the code instead of generating the webpack loading code `require('./' + o.u(r))` - not sure how to do that though.

**Comment by vankop** [comment]
don't use chunks in library, to remove extra chunks you can use
```js
plugins: [
        new webpack.optimize.LimitChunkCountPlugin({ maxChunks: 1 })
    ]
```
also there are other cjs library types https://webpack.js.org/configuration/output/#outputlibrarytype

**Comment by fabb** [comment]
Thanks, limiting the chunks to 1 fixes the .d.ts issue.

The issue that the application puts everything into a single chunk including code that is not needed at runtime still persists though. No wonder when there is only a single library chunk. Not sure if that is fixable with the other output library types. I guess not. Probably I need to make my lib tree-shakable and directly build it with tsc instead of webpack to keep the dynamic imports.
