### ISSUE TITLE
Idea: text-based macro preprocessor loader

### ISSUE THREAD

**Issue by jedwards1211** [webpack/webpack#1571]
Upon reading https://github.com/jtangelder/sass-loader/issues/181 and reading about how Sassport enables one to share variables between Sass and JS, I realized an ideal solution might go much deeper.   Why not have a way to share variables and even computed values between files of any type?

Obviously it's something that could be done fairly easy with a webpack loader.  Imagine macros that invoke JS functions and get replaced with the return value!

I figure such a loader must exist already, but I haven't found one yet.  Does anyone know?

The main difficulty would be that the macro syntax would have to vary depending on the file being loaded.  But that might not be such a huge problem; users could specify what kind of macro escape chars they want in the loader config.

**Comment by IngwiePhoenix** [comment]
I had thought of creating a C-like preprocessor loader for Webpack too. But I suck at writing stuff like that. :)

What I did instead is... https://github.com/IngwiePhoenix/sassport-loader
