### ISSUE TITLE
Uncaught SyntaxError: Unexpected token '}'

### ISSUE THREAD

**Issue by otanim** [webpack/webpack#15710]
# Bug report

**What is the current behavior?**

Webpack randomly fails to bunle which causes `Uncaught SyntaxError: Unexpected token '}'` error message and broken code:

It seems like it adds the following segment twice, which causes the problem:
```
/******/ })()
;
```
![image](https://user-images.githubusercontent.com/7108843/165164825-293261bc-bbd6-4065-a3fc-cc0d1a8e347f.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

The issue occurs randomly, the same codebase might fail without any code change.
`cross-env NODE_ENV=production webpack --config ./webpack.config.js` is being used here.

**What is the expected behavior?**

The build shouldn't fail randomly, the last 2 duplicate lines shouldn't be added at the end of the file.

**Other relevant information:**
webpack version:  5.72.0 (this started happening after we've upgraded Webpack from v4 to v5)
Node.js version: 14.0
Operating System: Ubuntu 20.04
Additional tools: gulp, tailwind v1.2, react v16.8

**Comment by alexander-akait** [comment]
You have invalid JS, please provide reproducible test repo, otherwise we can't help

**Comment by alexander-akait** [comment]
Maybe you can provide plugin list?

**Comment by otanim** [comment]
@alexander-akait, here is the list of used plugins:
- Webpack v5.72.0: AggressiveMergingPlugin
- mini-css-extract-plugin v2.4.5

**Comment by alexander-akait** [comment]
@otanim Can you try to disable AggressiveMergingPlugin? Maybe you can create small example? Just remove most of code

**Comment by otanim** [comment]
@alexander-akait, regarding disabling AggressiveMergingPluging, please note that the issue was occurring randomly, like every 15-30 builds (and each takes ~15m), so it would've been quite hard to test.

Regarding providing an example, unfortunately, I'm not in a position to extract any source code from the subject repository. It's an NDA stuff.

**Comment by alexander-akait** [comment]
@otanim 

> Regarding providing an example, unfortunately, I'm not in a position to extract any source code from the subject repository. It's an NDA stuff.

I don't ask to provide source code of your project, you can put any code, it is just to provide example of a problem, otherwise we can't help you and an issue will be closed

**Comment by otanim** [comment]
I do want to mention, that my previous statement was incorrect, the issue started popping up afterward, we've managed to fix the issue by disabling `yarn`'s asynchronous multithreaded bundling.
