### ISSUE TITLE
62% 🐶building 668/768 modules 100 active  ...  

### ISSUE THREAD

**Issue by flyingDandelionYD** [webpack/webpack#15718]
when I  run dev, It just shutdown the terminal when it goes  about 60%,and  when I  remove some packages, it just works well,
I guess the package may be larger! 
But I do not konw why? May it has some other cause?
Thanks!

**Comment by vankop** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us by recreating the issue using one of our templates.

Please fill out all fields, we can't help you without it
