### ISSUE TITLE
Replaced folder junction link isn't updated by watcher

### ISSUE THREAD

**Issue by tb2johm** [webpack/webpack#15716]
# Bug report

**What is the current behavior?**

First of all: I'm not a 100% sure that this really is a webpack issue. We run CRA and from what I understand it uses webpack to watch for code changes.

In our project we have a _config_ folder, this folder (in the _src_ folder) is a junction link (windows) to a folder outside the _src_ folder.

From start (`npm start`) the link works fine, and any changes I do in the config files are pushed to the browser.

However if I want to change the link while running, the watch function for the _config_ folder breaks and no updates in the config files are pushed. If I do an update in the file that was previously linked, then the watcher updates to the new link.

**If the current behavior is a bug, please provide the steps to reproduce.**

I have created a small CRA based repository to demonstrate.

https://github.com/tb2johm/watch-link-test

Wish I could make the example smaller, but you won't have to read any code to understand the problem. The config is also not made by me, it's just the standard cra config (however I doubt that this is a config issue).

How to reproduce:
1. To setup the _config_ folder run the `init-link` script (`npm run init-link`).
   This will create a link in the: _./src/config_ folder to the _./config-dev_ folder.
2. Start server (`npn start`)
3. Make minor change in _./config-dev/index.json_ (for example add an additional _!_) to verify that watch work.
4. Replace junction link (change to prod config using the `switch-to-prod` script (`npn run switch-to-prod`))
5. Note that text on page hasn't changed, even reloading the page wont update the text.
6. Make minor change in _./config-prod/index.json_ and notice how watch no longer work.
7. Make minor change in _./config-dev/index.json_ and note that the changes made in previous step now is pushed to browser.

**What is the expected behavior?**

It would be great if changed files in replaced junction folders were watched. Not sure how to trigger the such a watch update.

**Other relevant information:**
webpack version:  5.72.0
Node.js version: 16.14.0
Operating System: Windows 10
Additional tools: CRA: react-scripts: 5.0.0

**Comment by vankop** [comment]
yeah, do not change symlink while running build..

**Comment by tb2johm** [comment]
Ok, how comes the watch starts working when updating in the file linked at startup? And most importantly, is there anyway to trigger a full "re-watch"? Restarting the dev server takes a couple of minutes, and it would be great if that could be avoided.
