### ISSUE TITLE
Hoist RegExp Literals in SourceMapDevToolPlugin

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack#15720]
# Bug report

**What is the current behavior?**
The use of RegExp literals create unnecessary object references/allocations especially in iterated hot paths like SourceMapDevToolPlugin. We should hoist these to the top of file and give them useful names so people understand what the heck they do. 

**If the current behavior is a bug, please provide the steps to reproduce.**
Some Examples: 

Mapping over a RegExp literal: https://github.com/webpack/webpack/blob/3ad4fcac25a976277f2d9cceb37bc81602e96b13/lib/SourceMapDevToolPlugin.js#L419

Big Async ForEach Statement with multiple RexExp Literal statements: 
https://github.com/webpack/webpack/blob/3ad4fcac25a976277f2d9cceb37bc81602e96b13/lib/SourceMapDevToolPlugin.js#L384-L551

**What is the expected behavior?**
Less memory allocation, less garbage collection triggered.

Happy to PR this. There are quite a few of these examples still lying around webpack that should be cleaned up but I'll start with this.

**Comment by markjm** [comment]
This makes sense to me - I wonder if you have any perf traces or anything that could show any marked improvement from this change?

**Comment by TheLarkInn** [comment]
![image](https://user-images.githubusercontent.com/3408176/165856603-e3c9d5ed-ecc0-47de-ba88-9d0480809d4f.png)

@markjm Here is an example of mem allocation hotpath if this helps. This tree is during the forEach calls referenced in the PR.

**Comment by alexander-akait** [comment]
bump

**Comment by alexander-akait** [comment]
@TheLarkInn Do we still need it?

**Comment by TheLarkInn** [comment]
I'll address PR comments and then we can reopen and close once we merge it.
