### ISSUE TITLE
Webpack stops with no error - html/Uglify issue

### ISSUE THREAD

**Issue by kzima** [webpack/webpack#1573]
It seems like there could be a problem with new Vue.js syntax and how html is uglified by Webpack. 

When I run webpack with no uglify plugin it works.
When I run webpack with uglify or just wepack -p than it stops (see [screenshot](http://grab.by/LEcu))
When I remove new syntax ( @click="dismiss" ) and replace it with (v-bind:click="dismiss") in my html, it works in both cases.

To replicate the issue just require this [file](https://gist.github.com/kzima/1c57a2fde9628a65fffd) in your test on win10 64 with standard webpack config.

It could be related to https://github.com/webpack/webpack/issues/522 and https://github.com/webpack/webpack/issues/537

**Comment by bebraw** [comment]
To quote @sparty02:

> I am having this same issue and I think I've narrowed it down to something related (either directly or indirectly) to a combination of using UglifyJsPlugin in conjunction with html-loader. Looks like there is a related issue going on with #1573.

**Comment by sparty02** [comment]
For triaging, I commented out the minification logic in the ```html-loader``` [here](https://github.com/webpack/html-loader/blob/master/index.js#L59) and, sure enough, my bundle finished fine.

**Comment by zcoding** [comment]
i'm doing something with vue.js(yeah, ^1.0 version) and webpack, and i found a similar problem...

i cannot compress my project now and this problem really annoys me.

:sob:

**Comment by kzima** [comment]
@zcoding Just use full syntax like so v-bind:click="dismiss" and you should be fine. It worked for me.

**Comment by smastous** [comment]
I am having the same problem, and I am not using Vue.js or @ syntax in any html templates.  All of the my templates are just standard html.  I tried commenting out the code @sparty02 suggested and it fixed the issue for me as well.

**Comment by blacksonic** [comment]
html?minimize=false also made it work for me

**Comment by rjoo** [comment]
For those Vue users that are stumbling upon this, there's a `vue-html-loader`: https://github.com/vuejs/vue-html-loader/, which allows you to minimize and use the `@` syntax.

**Comment by Humeira** [comment]
@blacksonic Have you been able to minify html?

**Comment by blacksonic** [comment]
haven't tried

**Comment by Humeira** [comment]
@blacksonic got this error while minifying 
`ERROR in ./~/vue-html-loader!./~/vue-loader/lib/selector.js?type=template&index=0!.`
looks familiar?

I have this in my config
```
     new webpack.optimize.UglifyJsPlugin({
            minimize : true,
            sourceMap : false,

        })
```

**Comment by bebraw** [comment]
Is this relevant still?
