### ISSUE TITLE
Imports from "node:" namespace are not supported

### ISSUE THREAD

**Issue by zdm** [webpack/webpack#15741]
# Bug report

**What is the current behavior?**
Code below produce errors:
```
import Events from "node:events";
```
```
Module build failed: UnhandledSchemeError: Reading from "node:events" is not handled by plugins (Unhandled scheme).
  Webpack supports "data:" and "file:" URIs by default.
  You may need an additional plugin to handle "node:" URIs.
```
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
I am expecting, that `events` module will be imported or replaced with the polyfill.

**Comment by alexander-akait** [comment]
Because you have `target: 'web'`, you need to use `externals` to support protocol based URLs and Node.js modules in browser or switch to node target if you build code for Node.js, feel free to feedback

**Comment by ronilan** [comment]
FWIW, I got same error while building a `<pkg>` with `target: 'node'`. The `<pkg>` was locally linked to `<other-pkg>` that was also built with `target: 'node'` and that uses `node:events`.

Issue was resolved by running `rm -rf node_modules` and `npm link <other-pkg>` in the `<pkg>` directory.
