### ISSUE TITLE
`experiments.css` cannot be disabled when `experiments.futureDefaults` is enabled

### ISSUE THREAD

**Issue by jdanil** [webpack/webpack#15742]
# Bug report

**What is the current behavior?**

When `experiements.futureDefaults` is enabled but `experiments.css` is disabled, webpack fails with the following error.

```
Error: Conflict: Multiple chunks emit assets to the same filename main.css
```

I believe this behaviour was introduced in `5.67.0` via (#15200). Specifically...
https://github.com/webpack/webpack/blob/1489b91a98daf7e59207da7d3b29ad12750a9ecf/lib/config/normalization.js#L185

When `experiments.css` is set to `false`, its value is normalised as `undefined`. So the `experiments.futureDefaults` value is used in its place here...
https://github.com/webpack/webpack/blob/1489b91a98daf7e59207da7d3b29ad12750a9ecf/lib/config/defaults.js#L164

**If the current behavior is a bug, please provide the steps to reproduce.**

`webpack.config.js`

```javascript
{
  experiments: {
    css: false,
    futureDefaults: true,
  },
}
```

**What is the expected behavior?**

webpack should build successfully with `experiments.css` disabled.

I would like to be able to enable `experiments.futureDefaults` so that I can ensure compatibility with the next major webpack version. But for some experiments, like `experiments.css`, I would like to be able opt-out for now until I better understand the upgrade path.

**Other relevant information:**
webpack version:  5.72.0
Node.js version: 16.14.2
Operating System: Ubuntu

**Comment by alexander-akait** [comment]
Thanks for a report, feel free to send a fix

**Comment by sokra** [comment]
You can opt-out of that by changing the default module type for `.css` files to something else.

e. g. in your rule with `test: /\.css$/i` set `type: "javascript/auto"`
