### ISSUE TITLE
Webpack 5 Module Federation not importing the remote package

### ISSUE THREAD

**Issue by itsvamshiks** [webpack/webpack#15744]
Hello.

I have a vanilla JS app and an Angular app. I am trying to link both these apps using module federation, both on my local environment. The following is webpack config file for vanilla js app which acts as remote

```
module.exports = {
    entry: ['./src/index.js'],
    output: {
        publicPath: config.get('publicPath')
    },
    module: {
        rules: [
            {
                test: /\.js$/,
                exclude: /(node_modules)/,
                use: ['babel-loader'],
            }
        ]
    },
    plugins: [
        new HTMLWebpackPlugin({
            template: path.resolve(__dirname, 'demo/index.html')
        }),
        new ModuleFederationPlugin({
            name: 'remote',
            exposes: {
                './createWidget': './src/index.js'
            }
        }),
    ],

    devServer: {
        host: "localhost.remote.org",
        port: 8080
    }
};
```

Started the webpack-dev-server, so hitting http://localhost.remote.org:8080/remote.js will give me the file. So this is the webpack of my Angular app which is consuming the remote app

```
module.exports = {
    devtool: 'source-map',
    context: __dirname,
    entry: {
        polyfills: './src/polyfills.ts',
        main: './src/main.ts'
    },
    ...
    ...
    plugins : [
        new ModuleFederationPlugin({
            name: "HostApp",
            remotes: {
                remote: "remote@http://localhost.finra.org:8080/remote.js",
            }
        }),
    ]
}
```

So when trying to import the remote dependency, I get ```TS2307 : Cannot find module error```. Could anyone help me with fixing this? 

```
import * as Widget from 'remote/createWidget'
```

NOTE : Tried asking on Stackoverflow and Gitter. Got no responses so I created an issue here

**Comment by alexander-akait** [comment]
Sorry, `TS2307 : Cannot find module error` is not webpack problem, it is from typescript, we can't fix it here

**Comment by itsvamshiks** [comment]
@alexander-akait . Yes, it’s a typescript error which is coming from not being able to import the exposed module using webpack. I wanted some help in figuring out what’s going wrong in exposing and importing the remote using module federation

**Comment by alexander-akait** [comment]
You should mark this module as external, for example like you do with external jQuery https://stackoverflow.com/questions/32050645/how-to-use-jquery-with-typescript, sorry this question is not related to webpack

**Comment by ArishAzmat** [comment]
Module federation remote file name is "remoteEntry.js".
Just change it from "remote.js" to "remoteEntry.js".

https://webpack.js.org/concepts/module-federation/

remotes: {
        app1: 'app1@http://localhost:3001/remoteEntry.js',
      },
