### ISSUE TITLE
error building with json-loader

### ISSUE THREAD

**Issue by cch5ng** [webpack/webpack#1575]
hi, when I run webpack, I am getting errors like the following, (although I have installed json-loader).

ERROR in node_modules/i18next/lib/i18nextWrapper.js
Module not found: Error: Cannot resolve module 'json-loader' in node_modules/i18next/lib
 @ node_modules/i18next/lib/i18nextWrapper.js 8:22-48

ERROR in node_modules/i18next/lib/i18nextWrapper.js
Module not found: Error: Cannot resolve module 'json-loader' in node_modules/i18next/lib
 @ node_modules/i18next/lib/i18nextWrapper.js 9:28-66

ERROR in node_modules/express/~/send/~/statuses/index.js
Module not found: Error: Cannot resolve module 'json-loader' in node_modules/express/node_modules/send/node_modules/statuses
 @ node_modules/express/~/send/~/statuses/index.js 2:12-35

ERROR in node_modules/express/~/send/~/mime/mime.js
Module not found: Error: Cannot resolve module 'json-loader' in node_modules/express/node_modules/send/node_modules/mime
 @ node_modules/express/~/send/~/mime/mime.js 87:12-35

ERROR in node_modules/mime-types/lib/index.js
Module not found: Error: Cannot resolve module 'json-loader' in node_modules/mime-types/lib
 @ node_modules/mime-types/lib/index.js 11:8-30

ERROR in node_modules/mime-types/lib/index.js
Module not found: Error: Cannot resolve module 'json-loader' in node_modules/mime-types/lib
 @ node_modules/mime-types/lib/index.js 12:8-30

ERROR in node_modules/mime-types/lib/index.js
Module not found: Error: Cannot resolve module 'json-loader' in node_modules/mime-types/lib
 @ node_modules/mime-types/lib/index.js 13:10-34

----

this is part of my webpack.config.js, is there an issue with the configuration?
```
  module: {
    loaders: [
      { test: /\.json$/,
        loader: 'json-loader'
      },
      {
        test: /\.jsx?$/,
        exclude: /node_modules/,
        loaders: ['babel-loader', 'gettext-loader'],
      }
    ],
  },
  externals: {
          // Use external version of React
          'react': 'React'
      },
  resolve: {
      extensions: ['', '.js', '.jsx', '.json'],
      root: 'node_modules/',
      alias: {
          'chai': 'chai/lib/chai.js',
          'jquery': 'jquery/src/jquery.js',
          'i18next': 'i18next/lib/i18next.js',
          'require-json': 'require-json/index.js',
          'json-loader': 'json-loader/index.js'
      },
  },
  node: {
      fs: "empty",
      net: 'empty'
    }
};
```

**Comment by aackerman** [comment]
You might need to same `resolve.alias` for `json-loader` in `resolveLoader.alias`. See [here](https://webpack.github.io/docs/configuration.html#resolveloader)

**Comment by cch5ng** [comment]
@aackerman thanks. I ended up adding the following and the errors cleared:

```
  resolveLoader: {
      packageMains: ['json-loader']
  }
```

thanks for the config pointer.
