### ISSUE TITLE
CORS on localhost

### ISSUE THREAD

**Issue by pgarzina** [webpack/webpack#15752]
This is indirectly connected with Webpack as we are using Angular.

The issue is that after updating Angular 12 to Angular 13 we are no longer able to access our app served on localhost from outside of it, the request is being blocked by CORS. Basically when switching from Webpack 4 to Webpack 5.

this is what worked in Angular 12
`ng s --project app-search --disable-host-check --port 4207 --deploy-url https://localhost:4207/ --ssl --public-host https://localhost:4207/`
and stopped working in Angular 13.

We were looking into the docs around Webpack 4 and Webpack 5 and we can see that the disableHostCheck flag is removed from webpack 5 doc but is in webpack 4 docs. We tried playing around with disable host check and allowed hosts passing it to ng serve per official docs (https://angular.io/cli/serve) but with no luck.

Not quite sure if this is a bug or do the flags have to be passed in a different way to enable the same behavior that we had before.

Happy to provide more info if needed.

Any help or info is much appreciated.

**Comment by vankop** [comment]
as I see `disableHostCheck` was removed you need to set `allowedHosts: "all"`

**Comment by pgarzina** [comment]
Thanks for the prompt response.

**Comment by pgarzina** [comment]
for anyone stumbling across this seems the issue is in webpack-dev-server: https://github.com/webpack/webpack-dev-server/issues/4180
