### ISSUE TITLE
`return"field" in Module` will be evaluated as `returntrue` or `returnfalse`

### ISSUE THREAD

**Issue by IronLu233** [webpack/webpack#15759]
# Bug report
Hi, Webpack team. I found a bug when I upgrade it's version in my work project.

in version 5.71.0, there is a commit eb5d12415052b58098aee261c42ffc85aa20b03b.
It can evaluate the statement like `"Component" in React` to `true` on build time.
However, the is a edge case:
``` js
function foo() {
  return"Component" in "React"
}
```
that will be transformed to "returntrue". It misses a space before "true"

**What is the current behavior?**
`returntrue` or `returnfalse` will be a transformed result.
And will cause runtime error as `returntrue is not defined`

**If the current behavior is a bug, please provide the steps to reproduce.**
## reproduce
I create a PR for fix it. #15760.
comment this line https://github.com/webpack/webpack/pull/15760/files#diff-82d9a7fff0d25b8895057d34b65f83eb05cc28f11ed58132609ea7c565030745R113
and run 
```
 yarn jest test/TestCasesDevelopment.test.js -t harmony-export-import-specifier
```
the test will produce an error:
![image](https://user-images.githubusercontent.com/20639676/166406584-048e716f-bcd4-4444-a321-44fbb368354e.png)

**What is the expected behavior?**
Should be transformed to `return true` or `return false`

**Other relevant information:**
webpack version:  5.71.0
Node.js version: v16.14.1
Operating System: Linux
Additional tools: N/A

**Comment by vankop** [comment]
this is merged in `main` branch, please wait for release..

**Comment by vankop** [comment]
fixed in webpack@latest
