### ISSUE TITLE
localIndentName hash Name changed (Webpack To v5 from v4) 

### ISSUE THREAD

**Issue by sachinpatil55** [webpack/webpack#15764]
# Bug report

**What is the current behavior?**

- We have upgraded webpack 4 to webpack 5 and everything works fine except localIndentName has changed in CSS bundle files 

- we are using css-loader v6.6.0 for webpack 5  and configuration for the css loader is as follows 

 {
                        loader: 'css-loader',
                        options: {
                            modules: {
                                localIdentName: `${packageName}-[local]--[hash:base64:8]`
                            },
                            sourceMap: false
                        }
}

- packageName is separate variable name for each css-module  
-  previously className (webpack 4) - .${packageName}-${local}--**2sQngLez**
- now with webpack 5 the last hash version is changed to  - .${packageName}-${local}--**pWmRUIaV**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

Expectation should be webpack 5 build should generate CSS build ( hash ) with the same name 

**Other relevant information:**
webpack version:   5.68.0
Node.js version: 14.19.1
Operating System: 
Additional tools:

**Comment by alexander-akait** [comment]
@webpack-bot move to webpack-contrin/css-loader
