### ISSUE TITLE
Webpack Profiling Plugin Errors on Load into Chrome Performance Tab

### ISSUE THREAD

**Issue by MichaelrMentele** [webpack/webpack#15770]
# Bug report

**What is the current behavior?**
Follow instructions here, get https://webpack.js.org/plugins/profiling-plugin/ and get:
```
Malformed timeline data: SyntaxError: Unexpected token 
 in JSON at position 115
```

**If the current behavior is a bug, please provide the steps to reproduce.**
-- trying to figure out how to shave this down

**What is the expected behavior?**
It should load the events.json into the performance timeline in chrome and let me inspect the flame chart

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

**Comment by vankop** [comment]
do you using `webpack@5` ?

**Comment by vankop** [comment]
hm.. all works for me..
