### ISSUE TITLE
`require.resolveWeak` is not parsed in ESM packages

### ISSUE THREAD

**Issue by johndiiorio** [webpack/webpack#15775]
# Bug report

**What is the current behavior?**
In packages with `type: "module"`, webpack fails to parse and replace `require.resolveWeak()` expressions.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Clone https://github.com/johndiiorio/webpack-require-resolveWeak
2. Run `npm install`
3. Navigate to both `./cjs` and `./esm` and run `npm run build` from within each directory.
4. Notice that in `./cjs/dist/bundle.js`, the `require.resolveWeak` call was replaced, but was not in `./esm/dist/bundle.js`.

**What is the expected behavior?**
The replacement was successful regardless of the type.

**Other relevant information:**
webpack version: 5.72.0
Node.js version: 17.9.0
Operating System: Arch Linux 5.17.1-arch1-1
Additional tools: n/a

This appears to be similar to #15372, as mentioned [here](https://github.com/webpack/webpack/issues/15372#issuecomment-1070234970).

**Comment by vankop** [comment]
this done intentionally since in esm there is no `require`, you should not use `type: "module"` for this module.. You can fix this using webpack.config e.g. setting type in `module.rules`:
```js
module.exports = {
   module: {
      rules: [{ type: "javascript/auto" /* you can add test property here */ }]
   }
};
```
