### ISSUE TITLE
Add logging to DefinePlugin

### ISSUE THREAD

**Issue by hdragos** [webpack/webpack#15778]
## Feature request

**What is the expected behavior?**
`DefinePlugin` should be able to log which of the strings got replaced and with what they got replaced. Also, it should be able to log which of the strings didn't get replaced. For example, let's suppose that we have the following configuration:
```js
new webpack.DefinePlugin({
    'process.env.BACKEND_URL': 'someurl',
    'process.env.NICE_FEATURE': JSON.stringify(true),
    'process.env.UNUSED_VAR: 'somevalue',
}),
new webpack.DefinePlugin({
    'process.env.SOME_SECRET': 'secret',
}),
```

There should be some logs regarding the success and failure of the replacement, something along the following lines:
```
DefinePlugin: replaced 'process.env.BACKEND_URL' with 'someurl' in file `backendClient.jsx` at line 11.
DefinePlugin: replaced 'process.env.NICE_FEATURE' with 'true' in file `homepage.jsx` at line 35.
DefinePlugin: replaced 'process.env.SOME_SECRET' with [OBFUSCATED] in file `api.jsx` at line 24.
...
DefinePlugin: The following provided strings were not found during bundling: `process.env.UNUSED_VAR`.
```

**What is motivation or use case for adding/changing the behavior?**
This will help with the visibility of the env var usage, thus being able to see if there are any secret leaks or if there are redundant variables in our configurations that are not getting replaced. Currently, the only way to see if the strings got replaced or not is to run a text search on the output bundle.

**How should this be implemented in your opinion?**
`DefinePlugin` should accept an `options` parameter which should feature a `debug` flag (or something that enables logging). The `debug` flag could have 2 different values: `normal`, for logging the full value of the replaced string and `obfuscate`, for logging an obfuscated value of the string. A proposed usage example would look like this:
```js
new webpack.DefinePlugin({
    'process.env.BACKEND_URL': 'someurl',
    'process.env.NICE_FEATURE': JSON.stringify(true),
    'process.env.UNUSED_VAR: 'somevalue',
}, {
    debug: 'normal',
}),
new webpack.DefinePlugin({
    'process.env.SOME_SECRET': 'secret',
}, {
    debug: 'obfuscate',
}),
```
The actual logging could be implemented [here (link)](https://github.com/webpack/webpack/blob/main/lib/DefinePlugin.js#L372).

**Are you willing to work on this yourself?**
yes

**Comment by vankop** [comment]
> redundant variables in our configurations that are not getting replaced

I think warning in this case should be enough..

**Comment by sushruth** [comment]
looks like this was solved with a very aggressive fix. Now all I see is that log when I build something.
