### ISSUE TITLE
Webpack Prefetch not work

### ISSUE THREAD

**Issue by xpromise** [webpack/webpack#15774]
# Bug report

repo: https://github.com/xpromise/webpack_preload

```js
document.getElementById("btn").onclick = function () {
  import(
    /* webpackChunkName: "math", webpackPrefetch: true */ "./js/math"
  ).then(({ mul }) => {
    console.log(mul(3, 3));
  });
};
```

**What is the current behavior?**

`webpackChunkName` works, but `webpackPrefetch` doesn't

**What is the expected behavior?**

Want to generate `<link rel="prefetch" href="js/math">` in HTML，but not

**Comment by vankop** [comment]
I think you need https://github.com/GoogleChromeLabs/preload-webpack-plugin for that.

Anyway, webpack nothing can do with html-plugin, please report this issue there, thanks.
