### ISSUE TITLE
Webpack code splitting with es6 modules

### ISSUE THREAD

**Issue by jamesfiltness** [webpack/webpack#1579]
The Webpack documentation for code splitting specifies that you can define a split point when using commonjs and AMD methods.

 I'm using ES6 modules. Is it possible to do code splitting with ES6?

**Comment by sokra** [comment]
With webpack-2 yes, with babel no (but you can the CommonJs/AMD Code Splitting, as you can mix all syntaxes).

webpack 2:

``` js
import normal from "normal";

System.import("on-demand").then(funtion(OnDemand) {
  /* do something with OnDemand */
});

```
