### ISSUE TITLE
Webpack4 compiler.seal doesn't wait for new entry added on compliation.buildModule hook

### ISSUE THREAD

**Issue by lancelotnemoj** [webpack/webpack#15808]
# Bug report

**What is the current behavior?**

I'm working on some custom logic which add new entries after babel-loader transform source codes. So I use complication.buildModule hook and addEntry to compliation

But I get such error `TypeError: Cannot read property 'addChunk' of null`, It occured by Complier.seal(675: 18) , and I log the error preparedEntrypoint at 1301 in compliation, its module is null and it is the module I just added in plugin.

So, I think the problem is because the complier starts seal process without waiting for the new entry added

Demo plugin
```javascript
const sharedStore = {
  'part1': require('path).join(process.cwd(), './src/more/one'),
  'part2': require('path').join(process.cwd(), '/src/more/two'), 
}

class AddEntryPluginDynamic {
  createDependencies(entry, name) {
    return SingleEntryPlugin.createDependency(entry, name);
  }

  apply(compiler) {
    compiler.hooks.make.tapAsync('MyAddEntryPlugin', (compilation, callback) => {
      compilation.hooks.buildModule.tap('MyAddEntry', () => {

        const chunkPrefix = 'part-';

        Object.keys(sharedStore[entryKeys]).map(key => {
          const fullPath = sharedStore[key];
          delete sharedStore[key];
          const name = chunkPrefix + key;

          const dep = this.createDependencies(fullPath, name);

          compilation.addEntry(this.context, dep, name, e => console.error(e));
        });
      });
      callback();
    });
  }
}
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Copmlier.Seal process waits for new entry added by plugin on buildModule hook

**Other relevant information:**
webpack version:  4.46.0
Node.js version: 14.17.3
Operating System: macOS Monterery 12.3.1
Additional tools:

**Comment by alexander-akait** [comment]
webpack v4 is outdated and accept only security fixed, please consider to update webpack v5
