### ISSUE TITLE
Missing documentation for webpack alias as array

### ISSUE THREAD

**Issue by plourenco** [webpack/webpack#15804]
Hello,

While following the documentation of webpack 5, it is stated that `resolve` `alias` expects an object in the key value form of `name: path`. However, I recently found out that `alias` can also be passed as an array, which is particularly useful to ensure a certain order when matching paths or sub-paths. However, I could not find any documentation about it.

```js
module.exports = {
  resolve: {
    alias: [
      {
        alias: path.resolve(__dirname, "a/1.js"),
        name: "@alias",
        onlyModule: false
      }
    ]
  }
};
```

Is there any reason for that? Is this becoming a deprecated feature?
I would be interested in contributing to this purpose. Thanks.

**Comment by vankop** [comment]
there is in docs. https://webpack.js.org/configuration/resolve/#resolvealias

example from docs:
```js
module.exports = {
  //...
  resolve: {
    alias: {
      _: [
        path.resolve(__dirname, 'src/utilities/'),
        path.resolve(__dirname, 'src/templates/'),
      ],
    },
  },
};
```

**Comment by plourenco** [comment]
Hi @vankop ,

Yes, but my understanding is that it isn't very clear. For instance, an array could be provided such as:

```javascript
module.exports = {
  resolve: {
    alias: [
      {
        alias: path.resolve(__dirname, "a/1.js"),
        name: "@alias",
        onlyModule: false
      }
    ]
  }
};
```

But there's no indication of such a template in the form of `{alias, name, onlyModule}`, one has to guess. In addition, `alias` is referred to as accepting an object, while instead, it should be `object/array`.
