### ISSUE TITLE
externals=scripts & module federation 

### ISSUE THREAD

**Issue by ckken** [webpack/webpack#15800]
# Bug report

```js
externals:{
  react: 'React@https://cdn.jsdelivr.net/npm/react@17.0.2/umd/react.development.js',
}
```
![image](https://user-images.githubusercontent.com/3890513/167364798-12e88700-4e3f-4885-98a3-ded3fb9f0738.png)

**Comment by ckken** [comment]
externalsType='script'

**Comment by vankop** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us by recreating the issue using one of our templates.

Please fill out all fields, we can't help you without it

**Comment by ks-stack** [comment]
+1

**Comment by ks-stack** [comment]
why externalsType is only global config?

**Comment by alexander-akait** [comment]
@ks-stack What did you mean, please clarify
