### ISSUE TITLE
Webpack couldn't import node_modules to Audio Worklets.

### ISSUE THREAD

**Issue by novikov-alexander** [webpack/webpack#15814]
# Bug report

Hello, 
I try to make make an Audio Workets using "aubiojs" library.
I installed the library via npm.
The worklet works via "WorkerURL" plugin but import of the library breaks it. 

My tuner.ts has the following lines:

```
const frequencyProcessorUrl = new WorkerUrl(new URL('./frequency-processor.ts', import.meta.url));

    this.audioContext.audioWorklet.addModule(frequencyProcessorUrl).then(() => {
      self.audioWorklet = new AudioWorkletNode(self.audioContext, "frequency-processor");
      ...
    })
```

frequency-processor.ts:
```

import aubio from "aubiojs";
aubio();
class FrequencyProcessor extends AudioWorkletProcessor {
...
}
registerProcessor('frequency-processor', FrequencyProcessor);
```

**What is the current behavior?**

Webpack replaces `aubio()` by  __webpack_require__(/*! aubiojs */ "./node_modules/aubiojs/build/aubio.js") and can't resolve this.

**If the current behavior is a bug, please provide the steps to reproduce.**

Please, look into this branch https://github.com/novikov-alexander/tuner/tree/v-alnovi/pitchTeacher 

**What is the expected behavior?**

I guess that it would be convenient if we could bundle workers code with its dependencies in build time. 
Currently that's not possible because it causes an error of undefined AudioWorkletProcessor.

**Other relevant information:**
webpack 5.72

**Comment by vankop** [comment]
At list from what I see your setup is wrong.. you need to use multicompiler mode:

webpack.config.js
```js
module.exports = [
   { name: "worker", entry: "./path/to/worker-entry.js", target: "webworker", output: { filename: "worker.js" } },
   { name: "app", dependencies: ["worker"] }
];
```

and in code:
```js
this.audioContext.audioWorklet.addModule(new URL('./frequency-processor.ts', import.meta.url)).then(() => {});
```

**Comment by alexander-akait** [comment]
Can you provide full code of worker bulding? Sounds like webpack doesn't consider it as worker

**Comment by vankop** [comment]
@alexander-akait `worklet.addModule()` require url as an argument, so right now it is possible only prebuilding worker as script

**Comment by novikov-alexander** [comment]
@vankop 
I decided to simplify things and to build it without TypeScript temporarily. 
https://github.com/novikov-alexander/tuner/commit/47ba9ee158f28c7dca87a9edee24d7de02d705bb

```
const appConfig = {
  ...config,
  entry: {
    bundle: "./app/app.js"
  },
  output: {
    filename: "[name].js",
    path: path.resolve(__dirname, "dist"),
    publicPath: '/',
  },
  dependencies: ["frequency-processor-worklet"],
  devServer: {
    open: true,
    host: "localhost"
  },
}

const processorConfig = {
  ...config,
  name: "frequency-processor-worklet",
  entry: "./app/frequency-processor.js",
  target: "webworker",
  output: { 
    filename: "frequency-processor-worklet.js",
    path: path.resolve(__dirname, "dist"),
    publicPath: '/',
    globalObject: 'this'
  }
}
```

This line:
```
this.audioContext.audioWorklet.addModule(new URL('frequency-processor-worklet.js', import.meta.url))
```
causes the following error:
Module not found: Error: Can't resolve 'frequency-processor-worklet.js' in 'J:\Repositories\tuner\app'

So, that means that `import.meta.url` forces webpack to look for a physical source not for a bundled js, am I right?
The idea which implies from that is use the next line:
```
this.audioContext.audioWorklet.addModule('./frequency-processor-worklet.js')
```

But it causes:
Uncaught ReferenceError: self is not defined

in webpack-dev-server/client/index.js

which I can't fix by changing the global object.

Is my idea to remove `import.meta.url` correct?
Do you have any ideas why it still isn't working?

**Comment by vankop** [comment]
@novikov-alexander not sure what you trying to do.. https://github.com/novikov-alexander/tuner/pull/1 this is working solution

**Comment by novikov-alexander** [comment]
Unfortunately your solution still throwing 
Module not found: Error: Can't resolve './webworker.min.js' in 'J:\Repositories\tuner\app'
 on my machine

**Comment by novikov-alexander** [comment]
> [@novikov-alexander](https://github.com/novikov-alexander) Did you find a solution to this in the end? Trying to achieve something similar.

I didn't investigate it anymore but you can check the continuation of the thread here:
https://github.com/webpack/webpack/issues/15824
