### ISSUE TITLE
Webpack doesn't generate correct ensure code when use with CommonsChunkPlugin

### ISSUE THREAD

**Issue by skatou** [webpack/webpack#1581]
Hi,

I'm building a multi-page web app with webpack, I use CommonsChunkPlugin to extract two lib JS files (boot.js and common.js), I don't want webpack do the code split for me base on my "require" calls, so I have the build config,
```javascript
var CommonsChunkPlugin = require("webpack/lib/optimize/CommonsChunkPlugin");

var JS_PATH = "./assets/js/";
var BUILD_PATH = "./build/";


module.exports = {
    entry: {
        boot: JS_PATH + "module/boot",
        common: [
            JS_PATH + "module/startup",
            ...
        ],
        index: JS_PATH + "index",
    },
    output: {
        path: BUILD_PATH,
        publicPath: "/",
        filename: JS_PATH + "[name].js",
        chunkFilename: JS_PATH + "[name].js",
    },
    plugins: [
        new CommonsChunkPlugin({
            names: [ "common", "boot" ],
            minChunks: Infinity,
        }),
    ],
}

```
after built I get 4 types of JS files for each page
```
boot.js
common.js
[page_name].js
[other webpack chunks...]
```

and my html file looks like this,
```html
<html>
<head>
<script src="/assets/js/boot.js"></script>
</head>
<body>
    ...
    <script src="/assets/js/[page_name].js"></script>
</boby>
</html>
```

I expect my page work like this,
1. boot.js contains webpack runtime and loads first
2. common.js is loaded by [page_name].js, asynced, indirectly when a "common module" is required
so I have my index.js
```javascript
require(["./module/startup"], function(startup) {
    startup.doSomething();
});
```

However, when I deployed and ran my page "common.js" is never loaded, I noticed "__webpack_require__.e" is not call in the generated code.

I thought webpack knows startup.js is bundled in common.js, so when I require startup asynced, webpack would loaded common.js for me.  Do I expect too much from webpack?  What's the work around?

**Comment by ctulek** [comment]
I think you need to also include common.js in the <head>

**Comment by skatou** [comment]
@ctulek Yes I can, however I want to load it async with code, so that I have the option to handle error on load failure (with plugin say async-module-plugin).

**Comment by sokra** [comment]
Doing `entry: common` and `require(["./module/startup"` will create two **separate** chunks.

So you either only use the `common` entry point and include it in your HTML.

OR you require it async, don't use it as entry point and don't use it in the CommonChunkPlugin. This way you have to require everything formerly in the common chunk async. I would recommend to use the optimization plugins for merging the chunks into fewer chunks, but you could also enforce everything in a single chunk by giving the `require.ensure` a chunk name (`require.ensure([], f() {}, "common")`).
