### ISSUE TITLE
⠦ [Webpack] Watch service... Console (animation) cuts out console.log/s

### ISSUE THREAD

**Issue by naretini** [webpack/webpack#15815]
# Bug report

**What is the current behavior?**
 I'm using webpack (watch mode enabled) along with serverless framework and serverless.offline, serverless-webpack plugins
Runtime Nodejs w/ Typescript.

**If the current behavior is a bug, please provide the steps to reproduce.**
When I test locally my serverless app executing on console:
`sls offline start `

I see the following webpack watcher message(animation) on the console:
`⠦ [Webpack] Watch service...` ( dots are animated )

While the app is running and I starts logging, webpack watch service message might refresh

_When webpack watch is polling this message will overwrite last lines on my console logs.
Preventing me to see latest information._

Following is my webpack.config.js file:

```
const path = require('path');
const slsw = require('serverless-webpack');
const nodeExternals = require('webpack-node-externals');

module.exports = {
  context: __dirname,
  mode: slsw.lib.webpack.isLocal ? 'development' : 'production',
  entry: slsw.lib.entries,
  devtool: slsw.lib.webpack.isLocal ? 'cheap-module-source-map' : 'source-map',
  resolve: {
    extensions: ['.mjs', '.json', '.ts'],
    symlinks: false,
    cacheWithContext: false,
  },
  output: {
    libraryTarget: 'commonjs',
    path: path.join(__dirname, '.webpack'),
    filename: '[name].js',
  },
  target: 'node',
  externals: [nodeExternals()],
  module: {
    rules: [
      {
        test: /\.(tsx?)$/,
        loader: 'ts-loader',
        exclude: [
          [
            path.resolve(__dirname, 'node_modules'),
            path.resolve(__dirname, '.serverless'),
            path.resolve(__dirname, '.webpack'),
          ],
        ],
        options: {
          transpileOnly: true,
          experimentalWatchApi: false,
        },
      },
    ],
  },
  watchOptions: {
    poll: 1000,
    ignored: ["node_modules"]
  }
};
```

**What is the expected behavior?**

**Other relevant information:**
webpack version:  "^5.70.0"
Node.js version: v14.18.0
Operating System: macOS 12.x
Additional tools: 
```
"serverless": "~3.12.0",
"serverless-offline": "^8.5.0",
"serverless-webpack": "^5.6.1",
```

**Comment by vankop** [comment]
not sure what you expect.. webpack logs in stdout/stderr during build, this is not related to your application logs, maybe you need to change your setup..

**Comment by alexander-akait** [comment]
Yes, not related to webpack, please open an issue in `serverless-webpack`/`serverless`/`serverless-offline` repo
