### ISSUE TITLE
Module Federation eager shared libs break anytime a remote build is requested from a host build

### ISSUE THREAD

**Issue by rubixibuc** [webpack/webpack#15829]
# Bug report

**What is the current behavior?**

Module Federation eager shared libs break anytime a remote build is requested from a host build

**If the current behavior is a bug, please provide the steps to reproduce.**

example: https://github.com/rubixibuc/broken-mf-eager

1. create two module federation builds
2. in the first build, import any lib without first creating an async chunk. don't use import('./bootstrap')
3. in the first build, declare that lib as `eager: true`
4. in the second build, expose a module using module federation `exposes`
5. import([second build module]) somewhere inside the first MF build

* everything works without step 5
* technically everything works if build 1 and build 2 have no overlapping shareScope, but when the possibility exists that build 1 and build 2 can share a dependency nothing can successfully be eagerly loaded in build 1 - which seems to defeat the whole point of eager: true

It looks like eagerly loaded libs fail when there is a promise pending, and step 5 creates a pending promise that doesn't resolve in time.

**What is the expected behavior?**

I would expect that eagerly loaded lib to either be shared or superseded for the pending remotes version so that regardless of the two copies only one is actually executed.

**Other relevant information:**
webpack version:  5.72.1
Node.js version: 16.15.0
Operating System: MacOS 12.3.1
Additional tools: ModuleFederation Plugin

**Comment by ScriptedAlchemy** [comment]
Do you get a warning in browser like “failed to init external” or something along those lines?

**Comment by rubixibuc** [comment]
> Do you get a warning in browser like “failed to init external” or something along those lines?

This is the generated error: `Uncaught Error: Shared module is not available for eager consumption: webpack/sharing/consume/default/react/react`

**Comment by ScriptedAlchemy** [comment]
try removing unneeded plugins, try disabling webpack dev server package

**Comment by rubixibuc** [comment]
I went through the source code when I originally reported this. There was a bug in the module resolving code. It could be fixed now, so I'll test with the latest version of webpack and report back

**Comment by alexander-akait** [comment]
@rubixibuc Hello, did you test it? Thank you

**Comment by rubixibuc** [comment]
@alexander-akait I haven't, and Ty for the reminder, will test this week

**Comment by rubixibuc** [comment]
Still happening after bumping library versions

```
"@babel/core": "^7.21.3",
"@babel/preset-react": "^7.18.6",
"babel-loader": "^8.3.0",
"external-remotes-plugin": "^1.0.0",
"html-webpack-plugin": "^5.5.0",
"webpack": "^5.76.2",
"webpack-cli": "^4.10.0",
"webpack-dev-server": "^4.12.0"
```

![Screenshot 2023-03-16 at 12 28 14 AM](https://user-images.githubusercontent.com/15688746/225514557-16709e7b-5038-44c1-bdbc-1b17c3b00afe.png)

@ScriptedAlchemy Are you able to confirm this config is either valid or invalid in the example repo:

https://github.com/rubixibuc/broken-mf-eager

**Comment by danishgrappus** [comment]
I am still running into the same issue:
"webpack": "^5.85.1",
    "webpack-bundle-analyzer": "^4.4.1",
    "webpack-cli": "^5.1.3",
    "webpack-dev-server": "^4.15.0"
    
  I am attaching {eager: true} to every library it gives the error for.
  For eg: I got the same error for "babel/ployfill". So I edited the webpack config as follows:
 ```
  new ModuleFederationPlugin({
name: "host",
filename: "remoteEntry.js",
remotes: {
		remote:"remote@http://localhost:5500/remoteEntry.js"
},
  shared:{
  ...deps,
 "babel-polyfill": { eager: true }
  }
  })
  ```
  
  This fixed the issue for "babel-polyfill" library.
  
  But then again, I got same error for "redux", "react", "prop-types" .. etc etc and I keep applying the above fix for all libraries.
  
  Has anyone found the solution..? Please help!

**Comment by alexander-akait** [comment]
Sorry, don't look at this currently, you can debug and try to find the root of the problem

**Comment by scottMan1001** [comment]
so,  Anyone  can fix it , I also face the same issue with  vue,

**Comment by scottMan1001** [comment]
> Still happening after bumping library versions
> 
> ```
> "@babel/core": "^7.21.3",
> "@babel/preset-react": "^7.18.6",
> "babel-loader": "^8.3.0",
> "external-remotes-plugin": "^1.0.0",
> "html-webpack-plugin": "^5.5.0",
> "webpack": "^5.76.2",
> "webpack-cli": "^4.10.0",
> "webpack-dev-server": "^4.12.0"
> ```
> 
> ![Screenshot 2023-03-16 at 12 28 14 AM](https://user-images.githubusercontent.com/15688746/225514557-16709e7b-5038-44c1-bdbc-1b17c3b00afe.png)
> 
> @ScriptedAlchemy Are you able to confirm this config is either valid or invalid in the example repo:
> 
> https://github.com/rubixibuc/broken-mf-eager
> 
> > @rubixibuc Hello, did you test it? Thank you
> 
> @alexander-akait Are you running into a similar issue?

hi ,did you fix it , I also face the same issue like yours.  Although use by vue

**Comment by alexander-akait** [comment]
Okay, I looked at https://github.com/rubixibuc/broken-mf-eager, and sorry you can't do it, because of `Shared module is not available for eager consumption`, shorty:

Here import:
```
import React from 'react'
```

but it can't be here, because:
```
new ModuleFederationPlugin({
  name: "app1",
  remotes: {
    app2: "app2@[app2Url]/remoteEntry.js",
  },
  shared: {react: {singleton: true, eager: true}, "react-dom": {singleton: true, eager: true}},
}),
```

webpack can't init shared module(s) in such case - module should be loaded once and share own state beween different application, there is an answer and solution https://webpack.js.org/concepts/module-federation/#troubleshooting:

You need to use and load them in `bootstrap.js`
```
import('./bootstrap.js');
```

we can't do it in the sync mode, sorry

It is not a bug, it works as expected

Also you have `ExternalTemplateRemotesPlugin`, but it is only for `externals` (module.constructor.name === 'ExternalModule' https://github.com/module-federation/external-remotes-plugin/blob/main/index.js#L17), there are not externals, you can write:
```
 externals: {
    react: "React",
    "react-dom": "ReactDOM",
  },
```  

But in this case you need to have such externals.

So I don't see any bugs here, everything works as expected.

Anyway feel free to feedback
