### ISSUE TITLE
lazy-compilation first request style-loader add style error

### ISSUE THREAD

**Issue by micheal-zhibin** [webpack/webpack#15822]
# Bug report

**What is the current behavior?**
when the first request, only add one(the very last one import css/less file) to the html, cause the page style error

**example**
index.jsx(entry):
import 'styles/my.less';
import 'styles/index.less';

**expected html**
<head>
  <style>{my.less content}</style>
  <style>{index.less content}</style>
</head>

**first request result html**
<head>
  <style>{index.less content}</style>
</head>

**second or more request result html**
<head>
  <style>{my.less content}</style>
  <style>{index.less content}</style>
</head>

**bug reason**
style-loader will check the module.id and then use it to identify and add dom to html, but during the first request, the hot module is missing the id property, so cause the error

**a simple solution**
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/19724409/168262869-ff257b0b-547a-44e3-895d-58afd7d03a66.png">

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  v5.72.0
Node.js version:  v12.19.2
Operating System: macOS
Additional tools:
style-loader@3.3.1

**Comment by vankop** [comment]
Could you create small reproducible repo? It is hard to get whats is problem about..

**Comment by micheal-zhibin** [comment]
> 

when using lazycompilation, I found that css module will not find module.id when I first time request and casued the style-loader miss the style, but when I request for it an other time, module.id will happen and the style will be added properly

**Comment by vankop** [comment]
@micheal-zhibin could you create small repro? I will take a look.

**Comment by micheal-zhibin** [comment]
> @micheal-zhibin could you create small repro? I will take a look.

I create a demo for this, https://github.com/micheal-zhibin/reactTemp

**Comment by micheal-zhibin** [comment]
@vankop please fix this problem when you are free~

**Comment by vankop** [comment]
you should use
```js
lazyCompilation: {
      entries: false,
      imports: true
}
```
