### ISSUE TITLE
support magic comments in experimental css

### ISSUE THREAD

**Issue by vankop** [webpack/webpack#15821]
## Feature request

support `/* webpackIgnore: true */`

**What is the expected behavior?**
ignore `url()`

**What is motivation or use case for adding/changing the behavior?**
ignore `url()` requests

**How should this be implemented in your opinion?**
support `/* webpackIgnore: true */` magic comment

**Are you willing to work on this yourself?**
yes

**Comment by alexander-akait** [comment]
bump

**Comment by alexander-akait** [comment]
Added here https://github.com/webpack/webpack/issues/14893, we handle all possible cases for CSS urls, expect (`src` and `image`, I will implement them soon) right now
