### ISSUE TITLE
when request with error(like 404),  the script(which created by dynamic import) fires a timeout instead of the onerror

### ISSUE THREAD

**Issue by lanmch** [webpack/webpack#15823]
# Bug report

**What is the current behavior?**
About the dynamic import, when the script's(like some js resource in CDN) get an error(like 404 or abort), the webpack made it trigger the timeout logic instead of the onerror logic. So, it will throw an error after 120 seconds rather than right now.

eg.
when I block the url, the error throw after 120s.
![image](https://user-images.githubusercontent.com/37408756/168264784-b9184fbe-a04e-49d4-b1d3-734698053533.png)
![image](https://user-images.githubusercontent.com/37408756/168265166-f6efb613-d57c-4674-9de4-42fb1a4b6f9f.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
you can clone the demo project form here: https://github.com/lanmch/webpack-dynamic-error-demo
run the script
```
npm install
npm run build
then open the dist/index.html in browser
```
may there are some speciel code in our project.
Like  the dynamic module's name is src_dynamic-module_js, so that the file js name is src_dynamic-module_js.bundle.js.
To make my js resource preloaded, I insert the src_dynamic-module_js with script into the final html by HtmlWebpackPlugin.
So that I find the code of __webpack_require__.l's definition may have some error about this case.

**What is the expected behavior?**
I think the error maybe throw right now when it have problem with network, or in few minutes rather than 120s.

**Other relevant information:**
webpack version:  5.72.1
Node.js version: 14.16.0
Operating System: macOS

**Comment by vankop** [comment]
you have timeout error...
_______

Since webpack inserts script it can't control http flow. So webpack has 3 options => onError ( loading error ), onLoad and setting custom timeout. In your case it fires timeout, not sure why onError doesn't triggered..

**Comment by lanmch** [comment]
because in __webpack_require__.l, the same src with dynamic import not generate(so the onerror can bind the function onCompletet), but it trigger the timeout.

**Comment by lanmch** [comment]
I think there should have to judge the dynamic import script is be load before in html or not

**Comment by vankop** [comment]
I don't understand what you mean.. e.g. in your example if just delete `src_dynamic_import.js` chunk onError will be triggered..

**Comment by lanmch** [comment]
![image](https://user-images.githubusercontent.com/37408756/168285831-6594b207-c679-4457-9651-f3efce286df2.png)
you mean delete here?

**Comment by vankop** [comment]
no, remove this script from `dist` folder and you will get onError error

**Comment by lanmch** [comment]
the dist is generate by webpack, how can I remove it? It one of the dynamic import bundle js file

**Comment by lanmch** [comment]
aha?

**Comment by vankop** [comment]
I don't understand then.. in your example I have error because of 
```html
<script src="file:///Users/bytedance/Desktop/demo-project/webpack-dynamic-demo/dist/src_dynamic-module_js.bundle.js"></script>
```
that doesn't exists on my disk...

_________

You getting timeout error because of your network.. ( thats why it is fired after 120s ) With "normal" chunk loading error it will be fired immediately.

**Comment by lanmch** [comment]
> I don't understand then.. in your example I have error because of
> 
> ```
> <script src="file:///Users/bytedance/Desktop/demo-project/webpack-dynamic-demo/dist/src_dynamic-module_js.bundle.js"></script>
> ```
> 
> that doesn't exists on my disk...
> 
> You getting timeout error because of your network.. ( thats why it is fired after 120s ) With "normal" chunk loading error it will be fired immediately.

sorry, you can change the script in webpack-dynamic-error-demo/index.html to simulate it
```html
<script src="{your project path}/webpack-dynamic-demo/dist/src_dynamic-module_js.bundle.js"></script>
```

In our project, we use a plugin like preload-webpack-plugin for webpack5, to make the main purpose here is to make some scripts on the main link as early as possible to avoid the insertion of some asynchronous tasks. Because to show the minimal reproducible demo, I dont show you the plugin. So I try to use the hard code to let you know the final build result in my project

**Comment by lanmch** [comment]
> > I don't understand then.. in your example I have error because of
> > ```
> > <script src="file:///Users/bytedance/Desktop/demo-project/webpack-dynamic-demo/dist/src_dynamic-module_js.bundle.js"></script>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > that doesn't exists on my disk...
> > You getting timeout error because of your network.. ( thats why it is fired after 120s ) With "normal" chunk loading error it will be fired immediately.
> 
> sorry, you can change the script in webpack-dynamic-error-demo/index.html to simulate it
> 
> ```
> <script src="{your project path}/webpack-dynamic-demo/dist/src_dynamic-module_js.bundle.js"></script>
> ```
> 
> In our project, we use a plugin like preload-webpack-plugin for webpack5, to make the main purpose here is to make some scripts on the main link as early as possible to avoid the insertion of some asynchronous tasks. Because to show the minimal reproducible demo, I dont show you the plugin. So I try to use the hard code to let you know the final build result in my project

In final result, the script maybe like
```
<script src="https://www.cdnpath.com/js/src_dynamic-module_js.bundle.js" ></script>
```
So, there is no file path about 'file://' in the code actually

**Comment by vankop** [comment]
ok, you can preload this way.. but how it is related to timeout error? 

> sorry, you can change the script in webpack-dynamic-error-demo/index.html to simulate it

this way all works fine for me..

**Comment by lanmch** [comment]
like this in your dist/index.html
```html
<script src="{your project path}/webpack-dynamic-demo/dist/src_dynamic-module_js.bundle.js"></script>
```
when the website run with index.html, the webpack_require__.l will try to append the dynamic import script to html.
![image](https://user-images.githubusercontent.com/37408756/168572587-5e16108c-c2f7-484f-bc2f-838a47d4cb0a.png)
But at first, it will judge if the html has the script same tag, and set the 'needAttach' value.
eg. in the demo, when the index.html run, it will try to append the script with the src of 'src_dynamic-module_js.bundle.js', but at first in the judge function, it already exists, so it will not append to html. 
![image](https://user-images.githubusercontent.com/37408756/168572799-6a607641-5fce-454e-a44e-70abf149d29a.png)
![image](https://user-images.githubusercontent.com/37408756/168574580-bf339d44-2b88-4091-82b3-a2fbf2fb84dd.png)

Then, in the code behind, it will define a timeout about this js resource, but not append it to html dom

So when we have an error with network of 'src_dynamic-module_js.bundle.js', the script of it will load with error in Chrome. And as the code executes to load the dynamic import js, it judge and define timeout but not append script.
The final phenomenon is the onerror with the onScriptComplete will throw after the timeout code is executed（120000ms)

**Comment by vankop** [comment]
ok, but this is possible only with non-blocking js + I'm not sure is it possible to kind of miss error event...

**Comment by vankop** [comment]
ah... ok I see, need to debug first..

**Comment by vankop** [comment]
not sure that it is possible to solve this.. we can't track loading state for `script` tag..

**Comment by lanmch** [comment]
> not sure that it is possible to solve this.. we can't track loading state for `script` tag..

yes, I also can not find a very good way to solve this problem till now.
In my project, I just set the timeout value from 120000 to 10000 when the needAttach is false.

**Comment by lanmch** [comment]
> not sure that it is possible to solve this.. we can't track loading state for `script` tag..

for another, could you please tell me why the default timeout time is 120 seconds rather than other value?
