### ISSUE TITLE
(ubuntu 20.04 error)idealTree:es6-set npm ERR! code ENOTEMPTY npm ERR! syscall rename npm ERR! path /root/my-project/node_modul es/babel-code-frame npm ERR! dest /root/my-project/node_modul es/.babel-code-frame-HOOlptpd npm ERR! errno -39 npm ERR! ENOTEMPTY: directory not empty, rename '/root/my-project/node_modules 

### ISSUE THREAD

**Issue by aswallz** [webpack/webpack#15837]
# Bug report

**What is the current behavior?**
when i create vue webpack,it is panic

vue init webpack hello
npm install
npm run dev

**If the current behavior is a bug, please provide the steps to reproduce.**
vue init webpack hello
npm install
npm run dev

**What is the expected behavior?**

it can be runned smoothly
**Other relevant information:**
webpack version:  5
Node.js version: 18.1.0
Operating System: ubuntu 20.04
Additional tools: no

**Comment by vankop** [comment]
please ask in vue ( vue-cli? ) issue tracker.. or maybe babel.. at least from your error this is not related to webpack.
