### ISSUE TITLE
Webpack5 node modules issue

### ISSUE THREAD

**Issue by Naiym223** [webpack/webpack#15839]
./node_modules/owl.carousel/dist/assets/owl.carousel.css.webpack[javascript/auto]!=!./node_modules/next/dist/compiled/css-loader/cjs.js??ruleSet[1].rules[2].oneOf[5].use[1]!./node_modules/next/dist/compiled/postcss-loader/cjs.js??ruleSet[1].rules[2].oneOf[5].use[2]!./node_modules/owl.carousel/dist/assets/owl.carousel.css
TypeError: Object.fromEntries is not a function

why am i getting this error all of a sudden?

**Comment by vankop** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us by recreating the issue using one of our templates.

Please fill out all fields, we can't help you without it
