### ISSUE TITLE
[StackOverflow] Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by despairblue** [webpack/webpack#1583]
```
Uncaught RangeError: Maximum call stack size exceeded
  hotAddUpdateChunk @ bundle.js:736
  webpackHotUpdateCallback @bundle.js:5
  webpackHotUpdateCallback @ bundle.js:6
  webpackHotUpdateCallback @ bundle.js:6
  webpackHotUpdateCallback @ bundle.js:6
  webpackHotUpdateCallback @ bundle.js:6
  webpackHotUpdateCallback @ bundle.js:6
  webpackHotUpdateCallback @ bundle.js:6
  webpackHotUpdateCallback @ bundle.js:6
  webpackHotUpdateCallback @ bundle.js:6
```

What happens is that after a successful hot reload, [webpackHotUpdateCallback](https://github.com/webpack/webpack/blob/9f440e30ecac00bfc27b91d372a969d3414d194c/lib/JsonpMainTemplate.runtime.js#L7) keeps calling [hotAddUpdateChunk](https://github.com/webpack/webpack/blob/9f440e30ecac00bfc27b91d372a969d3414d194c/lib/HotModuleReplacement.runtime.js#L191) which returns immediately since `hotAvailibleFilesMap[0] === true` but `hostRequestedFilesMap[0] === false`. 

I also can't find a place where `parentHotUpdateCallback` is unset, so I don't see how this circle could ever be broken? Is this used for polling? Then a `setTimeout` could at least reset the stack. 

But maybe I'm missing something here.

Thanks for working on this and making things like hot module replacement possible!

**Comment by despairblue** [comment]
This happens when starting the dev server with `--hot` and also having `webpack/hot/only-dev-server'` in your entry array in `webpack.config.js`. Then the hot loading snippet is sourced twice creating this ping pong effect that keeps calling those two functions.

**Comment by despairblue** [comment]
This also leads to things like:
```jsx
if (module.hot) {
  module.hot.accept('./App', function () {
    require('./App')
  })
}
```
compiling into:
```jsx
if (true) {
  module.hot.accept(230230, function () {
    __webpack_require__(230);
  });
}
```

**Comment by despairblue** [comment]
Only using one of them does also not work.

If only using `--hot` then the accept callbacks are never called. And only using the `webpack/hot/only-dev-server` entry point without `--hot` makes the dev server refresh the browser on every change instead of hot swapping the modules.

**Comment by despairblue** [comment]
Ok I found a combination that worked:

1. use the webpack-dev-server with `--hot`
2. do use the entry point `webpack/hot/only-dev-server` (with or w/o `only`) in the config
3. **DO NOT** add `new webpack.HotModuleReplacementPlugin()` to the config's plugin section

Is this intended behaviour? If yes, should there be something in the documentation warning about this? If no, should there be some guards catching these cases?

**Comment by damionvega** [comment]
We're using npm scripts to run webpack and came across the same problem. This is very confusing. Thanks @despairblue

**Comment by perpaer** [comment]
Happens to me also. Thanks @despairblue for the quick fix.

**Comment by Delagen** [comment]
+1

**Comment by theoutlander** [comment]
@despairblue Thanks for the detailed follow-up and solution!

**Comment by pksjce** [comment]
This issue was moved to webpack/webpack.io#136

**Comment by xingyesh** [comment]
thanks。 the same problem
