### ISSUE TITLE
Webpack issues on node 4.0.0

### ISSUE THREAD

**Issue by joshikeerti** [webpack/webpack#1584]
Hi,
I recently upgraded to node version 4.0.0. and I am unable to run webpack.
I did a nom install -g webpack and installed it locally on my project. however when I run webpack command, it says command not found.

**Comment by despairblue** [comment]
When you install with `-g` it actually shouldn't install it into your project's local node_modules folder.
So doing `npm -g webpack` should link the webpack binary into the same folder npm is linked to.

What OS are you using?

**Comment by aackerman** [comment]
@joshikeerti, yes @despairblue is correct the `-g` flag means install this package globally on my machine. In the case where webpack is installed globally the binary must still be in your PATH on OSX, Linux or other Unix-like systems for you to have access to it.

If you run `type webpack` in your terminal I would imagine there are no entries of webpack in your PATH.

**Comment by bebraw** [comment]
@joshikeerti Any luck with this? Please note that you can hit `node_modules/.bin/webpack` to trigger webpack installed locally to a project.

**Comment by MacgyverMartins** [comment]
I have a similar problem.
If I run `webpack` in my terminal, return error `zsh: command not found: webpack`
but if I run `node_modules/.bin/webpack` it's work and build my app.

How can I fix that? Why `webpack` are not found?

**Comment by bebraw** [comment]
@MacgyverMartins Do other globally installed packages work for you? Could this be a path issue? Have you set `NODE_PATH` at your zsh config?

**Comment by MacgyverMartins** [comment]
@bebraw I think the problem happened because I was using nvm, and somehow, It doesn't work. Today I uninstall nvm node versions and install again using [npm n](https://www.npmjs.com/package/n). And the  webpack work great.
Sorry my bad english

**Comment by alteredtastes** [comment]
Helpful npm package for this issue. Solved it for me using zsh.
https://www.npmjs.com/package/add-local-binaries-to-path
