### ISSUE TITLE
Dynamic imports are getting lost using Windows11 inside the worker scope

### ISSUE THREAD

**Issue by tobiu** [webpack/webpack#15852]
# Bug report

**What is the current behavior?**
While the build works perfectly fine using MacOS (e.g. Monterey), the map containing paths to imports and split chunks is missing inside a Windows based env. The build fails silently (no JS errors).

Inside the app worker, we use the following code:
<img width="409" alt="Screenshot 2022-05-19 at 15 52 17" src="https://user-images.githubusercontent.com/1177434/169508692-cb13d8f2-f71e-4acc-8df1-b580301f0a7e.png">
https://github.com/neomjs/neo/blob/dev/src/worker/App.mjs#L98

Using MacOS, the output looks as follows:
<img width="1249" alt="Screenshot 2022-05-19 at 15 54 03" src="https://user-images.githubusercontent.com/1177434/169508860-834969e0-8ea4-467e-866b-648019608402.png">

Using Windows11, the entire map for the split-chunks is missing.

**If the current behavior is a bug, please provide the steps to reproduce.**
The easiest way to reproduce it:
1. clone the neo.mjs repository: https://github.com/neomjs/neo
2. npm install
3. npm run build-all
4. open `dist/production/appworker.js`

**What is the expected behavior?**
The output should be the same for MacOS and Windows11. Right now, the Windows output is completely broken, since the map is missing. It did work around 5 weeks ago using Windows10, but I did not verify yet if this is still the case.

**Other relevant information:**
webpack version:  5.72.1
Node.js version: v16.2.0
Operating System: Windows11
Additional tools:

**Comment by alexander-akait** [comment]
Sounds like a problem with Regexps

**Comment by tobiu** [comment]
In case it helps: I did a testing log at the very bottom of the `ImportParserPlugin` => https://github.com/webpack/webpack/blob/main/lib/dependencies/ImportParserPlugin.js#L266 => console.log(dep) and the output was the same for Monterey and Windows11.

**Comment by tobiu** [comment]
we can probably already close the issue.

@sokra recommended to add backslashes into the neo regexes.

i am not 100% sure though what changed: either win10 was using the linux kernel and win11 does not or some accenture settings changed this setting for my colleagues. just guessing as a mac user.

https://github.com/neomjs/neo/commit/28e33bd875cbf897af8521d3b3347784f1a50dca

**Comment by vankop** [comment]
yeah, you should use `[/\\]` in regexp
