### ISSUE TITLE
Duplicate chunk-names inside split-chunks maps

### ISSUE THREAD

**Issue by tobiu** [webpack/webpack#15853]
# Bug report

**What is the current behavior?**
This ticket is not critical, since the `dist/production` env still works, but there seems to be some not needed redundancy.
<img width="1220" alt="Screenshot 2022-05-20 at 12 31 28" src="https://user-images.githubusercontent.com/1177434/169510303-15e703f1-0b1a-4875-b9f2-229ce00035cd.png">

The map contains the the same chunk-names for many (not all) entries at the first and last position of the arrays.

**If the current behavior is a bug, please provide the steps to reproduce.**
The easiest way to reproduce it:

1. clone the neo.mjs repository: https://github.com/neomjs/neo
2. npm install
3. npm run build-all
4. open dist/production/appworker.js

**What is the expected behavior?**
Chunk-names should be unique for each path / array. One easy way to fix it is probably to convert the array into a [Set](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) and back.

it could make sense though to investigate why this is happening

**Other relevant information:**
webpack version: 5.72.1
Node.js version: v16.2.0
Operating System: Monterey
Additional tools:

**Comment by vankop** [comment]
from code bellow `map` you can see that this is intended:
```js
var ids = map[req], id = ids[0];
	return Promise.all(ids.slice(1).map(__webpack_require__.e)).then(() => {
		return __webpack_require__(id);
	});
```

**Comment by tobiu** [comment]
@vankop I think you perfectly showed why it is breaking :)

the problem is the `slice(1)`, so we build a map for all ids except the very first one, which explains why this is the only one which does get dupliacted.

should be an easy fix.

**Comment by vankop** [comment]
some ids are different, not sure why.. need @sokra explanation here..
