### ISSUE TITLE
Module federation cannot resolve version of secondary entry points with no version

### ISSUE THREAD

**Issue by yharaskrik** [webpack/webpack#15864]
# Bug report

**What is the current behavior?**

When trying to use packages that have secondary entry points but those entry points package.jsons do not have a version in them, webpack throws warnings like:

```
shared module @apollo/client/core -> /Users/jaybell/WebstormProjects/trellis-mono4/node_modules/@apollo/client/core/index.js - Warning: No version specified and unable to automatically determine one. No version in description file (usually package.json). Add version to description file, or manually specify version in shared config.
```

`@apollo/client/core` has a package.json with a version, `@apollo/client/core` has a package.json but does not have a version. What is the workaround for this? If a package does not have a version in it's published version but the root package does how should I configure webpack so that it can resolve the root version?

I tried adding additional shared mappings but that doesn't seem to work

**If the current behavior is a bug, please provide the steps to reproduce.**

Simplest way:

Generate an Nx with angular preset
generate a host and remote app
use `@apollo/client` (or any other package with a secondary entry point that is lacking a version)
Run the serve target for the host and see the error.

**What is the expected behavior?**

Should be able to use packages even if their secondary entry points do not have a version possibly should inherit the version from the root of the package, unless there is a reason or explanation as to why it is working the way it is.

**Other relevant information:**
webpack version:  5.69.0
Node.js version:  14.19.0
Operating System: MacOS 10.15.17
Additional tools:

Reported it here too:
https://github.com/nrwl/nx/issues/10460

**Comment by vankop** [comment]
please create small reproducible repo

**Comment by vankop** [comment]
please create small reproducible repo

**Comment by yharaskrik** [comment]
> please create small reproducible repo

Will do! I'll try and get that done tomorrow for ya!

**Comment by yharaskrik** [comment]
Here ya go!

https://github.com/yharaskrik/mfe-secondary-entry-point-demo

**Comment by vankop** [comment]
So..
For `shared module @apollo/client/core -> /.../mfe-secondary-entry-point-demo/node_modules/@apollo/client/core/index.js`
You have package.json in `/.../mfe-secondary-entry-point-demo/node_modules/@apollo/client/core` equals to
```json
{
  "name": "@apollo/client/core",
  "type": "module",
  "main": "core.cjs",
  "module": "index.js",
  "types": "index.d.ts",
  "sideEffects": false
}
```
and webpack use it instead of package.json `/.../mfe-secondary-entry-point-demo/node_modules/@apollo/client` since regarding Node.js resolve algorithm this is nearest package.json to source

Same for `shared module @apollo/client/link/batch -> /.../mfe-secondary-entry-point-demo/node_modules/@apollo/client/link/batch/index.js`
nearest package.json is `/.../mfe-secondary-entry-point-demo/node_modules/@apollo/client/link/batch`
```json
{
  "name": "@apollo/client/link/batch",
  "type": "module",
  "main": "batch.cjs",
  "module": "index.js",
  "types": "index.d.ts",
  "sideEffects": false
}
```

**Comment by vankop** [comment]
this should be solved by package authors

**Comment by nkalinov** [comment]
What about the "...or manually specify version in shared config." part?
Adding `@apollo/client/core: { requiredVersion: 'whatever' }` to `shared` doesn't work. Am I missing something?

**Comment by saeedghasemi72** [comment]
@nkalinov you can add version of packeges, that work for me, like this:
`"mapbox-gl": {
              requiredVersion: "^2.11.0",
              version: "^2.11.0",
              singleton: true,
    }`

**Comment by vigie** [comment]
I fixed this issue with the following shared function (using nx's implementation of federation):

```javascript
    shared: (libraryName, defaultConfig) => {
        if (libraryName.includes(`@apollo/client/`)) {
            return {
                ...defaultConfig,
                version: defaultConfig.requiredVersion
            }
        }
        return defaultConfig;
    },
```

**Comment by stumpykilo** [comment]
I ended up using this in the host and remotes:
```
const coreLibraries = new Set([
  'react',
  'react-dom',
  'react-router-dom',
  'react-redux',
  '@reduxjs/toolkit'
]);

module.exports = {
  name: 'host-mfe',
  remotes: [
    'remote1-mfe',
    'remote2-mfe',
  ],
  shared: (
    /** @type {string} */ libraryName,
    /** @type {any} */ defaultConfig
  ) => {
    if (coreLibraries.has(libraryName)) {
      return defaultConfig;
    }

    if (libraryName?.startsWith('@apollo/client')) {
      return { ...defaultConfig, eager: false, strictVersion: false };
    }

    // Returning false means the library is not shared.
    return false;
  }
};
```

**Comment by vigie** [comment]
thanks for sharing your solution @stumpykilo and also apologies - there was an error in my post above: the reason you were getting the `unsatisfied version` error is that you need to strip out the semver chars from `defaultConfig.requiredVersion` so that it is just the number for that technique to work. I've updated my solution to reflect that
