### ISSUE TITLE
`compiler.watchMode` should be `true` when running `webpack-dev-server`

### ISSUE THREAD

**Issue by ccjmne** [webpack/webpack#15884]
# Bug report

**What is the current behavior?**

When using a plugin while running `webpack-dev-server`, `compiler.watchMode` is `false`, yet the `watchRun` and `watchClose` hooks are active.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. create a `WebpackPluginInstance` that gets passed a `Compiler` in its `WebpackPluginInstance#apply(compiler: Compiler)` method.
2. run `webpack serve`
3. the `compiler.watchMode` is `false`, yet the `watchRun` and `watchClose` hooks are active.

**What is the expected behavior?**

1. create a `WebpackPluginInstance` that gets passed a `Compiler` in its `WebpackPluginInstance#apply(compiler: Compiler)` method.
2. run `webpack serve`
3. the `compiler.watchMode` should be `true`.

**Other relevant information:**
webpack version: `5.70`
Node.js version: `16.13.0`

**Comment by alexander-akait** [comment]
Expected, `watchMode` changed only when you webpack starts watch (https://github.com/webpack/webpack/blob/293e677b355da0d5bc4ddfc97d2afec114912711/lib/Compiler.js#L415), if you put code in `apply` `watchMode` will be false, because webpack initializates plugins and nothing more, you need to check it in hook or override from hook.

**Comment by ccjmne** [comment]
Thanks @alexander-akait!

I didn't think it was expected, since all I could read in the documentation about it was that the "watch mode" (albeit indeed maybe not the `watchMode` property) brings the `watchRun` and `watchClose` hooks to life...

> The Compiler supports [watching](https://webpack.js.org/api/node/#watching) which monitors the file system and recompiles as files change. When in watch mode, the compiler will emit the additional events such as `watchRun`, `watchClose`, and `invalid`. This is typically used in [development](https://webpack.js.org/guides/development), usually under the hood of tools like `webpack-dev-server`, so that the developer doesn't need to re-compile manually every time. Watch mode can also be entered via the [CLI](https://webpack.js.org/api/cli/#watch-options).

— from https://webpack.js.org/api/compiler-hooks/#watching

I still think it's odd if not inconsistent, but I understand what you're saying, thank you!

Shall I then simply test for `compiler.watchMode || process.env.WEBPACK_SERVE === 'true'` instead of just `compiler.watchMode`?

Thanks again for your swift reply!

**Comment by alexander-akait** [comment]
> Shall I then simply test for compiler.watchMode || process.env.WEBPACK_SERVE === 'true' instead of just compiler.watchMode?

`process.env.WEBPACK_SERVE` is not good idea, but yes, it will work.

Why you need it in `apply`? Maybe better to rewrite on hooks? In most cases it says you should refactor code, rely on it it really not good, you should run logic in hooks, logic should be agnostic to watch or simple build

**Comment by ccjmne** [comment]
Thanks @alexander-akait!

Indeed, maybe I'm doing something wrong...

I'm trying to build a Webpack plugin that simply prints out some **HTML** content in **PDF**.
When the code is updated, `HTMLWebpackPlugin` compiles a new HTML document, and then my own plugin "PDFPrinterPlugin" consumes it and prints it out as a PDF document.

While developing, I use `webpack serve` to continuously watch-build the HTML and check that the PDF document looks similar (some HTML/CSS isn't always printed exactly as expected).
Then, we run a one-off "production" build in our CI pipeline that just generates one static HTML asset, and prints it into HTML just once.

The problematic was to have the printing service (Chromium's **Puppeteer**) gracefully shut down after the entire workload has been handled.
Some testing some time ago showed that `afterDone` would emit after every asset update, even in "watch" mode (through `webpack serve`, not quite `webpack --watch`), and that's how I came to using:

```typescript
(compiler.watchMode
  ? compiler.hooks.watchClose
  : compiler.hooks.afterDone
).tap(`${PDFPrinter.PLUGIN_ID}:shutdown`, () => this.shutdown());
```

If I'm not approaching it the proper way, I'd very much appreciate your valuable input there!

Here's the full body of my plugin's `apply` method:

```typescript
  public apply(compiler: Compiler): void {
    const logger = compiler.getInfrastructureLogger(PDFPrinter.PLUGIN_ID);
    logger.info('Reading contents from', this.uri);
    logger.info('Compiling PDF at', this.output);

    compiler.hooks.afterEmit.tap(`${PDFPrinter.PLUGIN_ID}:compile`, async () => {
      try {
        await this.print();
        logger.info('Successfully printed', this.output);
      } catch (trace) {
        logger.error('An error occurred while attempting to compile PDF document');
        logger.error(trace);
      }
    });

    (compiler.watchMode || process.env.WEBPACK_SERVE === 'true'
      ? compiler.hooks.watchClose
      : compiler.hooks.afterDone
    ).tap(`${PDFPrinter.PLUGIN_ID}:shutdown`, () => this.shutdown());
  }
```

Thanks again for following up and pointing me in the right direction!

**Comment by alexander-akait** [comment]
Why not use `afterDone` always? webpack calls this hook for closing too https://github.com/webpack/webpack/blob/508877c91defb31db9a726f05056e26679b1ac94/lib/Watching.js#L311

**Comment by ccjmne** [comment]
The problem with using `afterDone` in "dev" mode is that my Puppeteer instance is shut down in that hook.

I only want to shut it down **once**, when I complete/cancel the watch (in "development" mode), or immediately after the first and only compilation has taken place, in "production" mode.

The `afterDone` hook is called every time a new compilation is triggered and finished, in watch mode... is that right?

**Comment by alexander-akait** [comment]
We have reusable compiler, you can run compiler in watch, when stop and when use it as simple build and again run watch and more and more as you want.

I think you are looking this https://github.com/webpack/webpack/blob/main/lib/Compiler.js#L1218

It will be called when `watch` closed and when `just build` finished

**Comment by ccjmne** [comment]
Thank you so much, Alexander!!
The `shutdown` hook is indeed what I was looking for!

How come it's not documented anywhere I've looked?
For instance, https://webpack.js.org/api/compiler-hooks/ makes no mention of it.
Is it here to stay?

In any case, it works wonders for me, thanks again for your valuable insight 🙇‍♂️

**Comment by vankop** [comment]
https://github.com/webpack/webpack.js.org/issues/6187
