### ISSUE TITLE
Setting up runtimeChunk and splitChunks, execute the `npm start` command the page is blank

### ISSUE THREAD

**Issue by salleyliu** [webpack/webpack#15887]
# Bug report

**What is the current behavior?**
When runtimechunk is **false**: The page shows normal.
When runtimechunk is **{name: entrypoint => `runtime-${entrypoint.name}`,}**: **The page keeps loading, showing a blank page without any error messages**

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Create a simple project(create-react-app v5): `npx create-react-app my-test-app`
2. Add splitchunks and runtimechunk in webpack.config.js
optimization : {
     runtimeChunk: {
        name: entrypoint => `runtime-${entrypoint.name}`,
      },
      splitChunks: {}
}
3. Execute `npm start`
4. Show blank page.

**What is the expected behavior?**
The page is loaded successfully and no blank page is displayed.

**Other relevant information:**
Browser: Chrome
webpack version:  v5.72.1
Node.js version: v17.4.0
Operating System: macOS
Additional tools: VScode

**Comment by vankop** [comment]
could you provide full webpack.config, not sure how this works with create-react-app, maybe you should address issue there..
