### ISSUE TITLE
Error: ChunkGroup.addOptions: No option merge strategy for name

### ISSUE THREAD

**Issue by pentatiby** [webpack/webpack#15883]
# Bug report

**What is the current behavior?**
```
[...]/node_modules/webpack/lib/ChunkGroup.js:117
                                        throw new Error(
                                        ^

Error: ChunkGroup.addOptions: No option merge strategy for name
    at Entrypoint.addOptions ([...]/node_modules/webpack/lib/ChunkGroup.js:117:12)
    at iteratorBlock ([...]/node_modules/webpack/lib/buildChunkGraph.js:512:8)
    at processBlock ([...]/node_modules/webpack/lib/buildChunkGraph.js:634:4)
    at processQueue ([...]/node_modules/webpack/lib/buildChunkGraph.js:740:6)
    at visitModules ([...]/node_modules/webpack/lib/buildChunkGraph.js:1202:3)
    at buildChunkGraph ([...]/node_modules/webpack/lib/buildChunkGraph.js:1367:2)
    at Compilation.seal ([...]/node_modules/webpack/lib/Compilation.js:2942:3)
    at [...]/node_modules/webpack/lib/Compiler.js:1187:20
    at [...]/node_modules/webpack/lib/Compilation.js:2757:4
    at _next3 (eval at create ([...]/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)

Node.js v18.2.0
```

**If the current behavior is a bug, please provide the steps to reproduce.**
When adding an entry with a specific name and then dynamically importing the same file, with the same name as that entry, this error occurs. 

I can come back with a codesandbox example if necessary.

**What is the expected behavior?**
I am not entirely sure if this is supposed to work, but the error message is pretty cryptic, so, if the steps are done by mistake, it can take a very long time to debug. I opened this in the hope that it may help someone, and, it case it needs to be fixed and no one picks it up, I might give it a try.

**Other relevant information:**
webpack version:  `"webpack": "^5.72.1",`
Node.js version:  `Node.js v18.2.0`
Operating System:  OS X
Additional tools: N/A

**Comment by alexander-akait** [comment]
> v

Yes, please

**Comment by vankop** [comment]
> I can come back with a codesandbox example if necessary.

please create small reproducible repo or codesandbox

**Comment by bahtou** [comment]
@alexander-akait @vankop 
Ran into the same issue. Repo to reproduct
https://github.com/bahtou/webpackv5-merge-stategy-error

**Comment by bahtou** [comment]
Seems like changing the webpack comments in `index.tsx` (or removing them) makes the error go away:

```
const LazyHome = lazy(() => import(/* webpackChunkName: "home" */ './pages/home'));
const LazyAbout = lazy(() => import(/* webpackChunkName: "about" */ './pages/about'));
```
TO
```
const LazyHome = lazy(() => import(/* webpackChunkName: "homePage" */ './pages/home'));
const LazyAbout = lazy(() => import(/* webpackChunkName: "aboutPage" */ './pages/about'));
```
OR

```
const LazyHome = lazy(() => import('./pages/home'));
const LazyAbout = lazy(() => import('./pages/about'));
```

**Comment by pentatiby** [comment]
Yes, that is the original behaviour observed in this issue – thank you for adding an example @bahtou.

> When adding **an entry** with **a specific name** and then dynamically importing the same file, with **the same name as that entry**, this error occurs. 

(changing the webpack comments or removing them changes the name to a different one)

Is this a bug, or is this use case just not supported?

**Comment by vankop** [comment]
@bahtou you have entry point with the same name as chunk since entrypoint also is a chunk ( just initial one you getting error )
_________________

anyway we should improve error in this case..


 @pentatiby do you have same situation?

**Comment by pentatiby** [comment]
@vankop yes, I did run into this and worked around it 

It would be nice for the error message to be more specific, yes (that is why I opened this issue, as it took quite a while to debug it)

Not sure if possible, but it would be great if this use case was allowed instead of throwing an error.

**Comment by vankop** [comment]
>  it would be great if this use case was allowed instead of throwing an error.

thats impossible since `[name]` should be unique
