### ISSUE TITLE
Modules imports for side effects from barrel files are not included in bundle

### ISSUE THREAD

**Issue by amitbeck** [webpack/webpack#15882]
# Bug report

**What is the current behavior?**

I have a `index.ts` which imports 2 modules (`abstract-control.ts` and `abstract-control.directive.ts`) for side effects, and exports another module (`custom-control-status.directive.ts`) therefore also acting as a barrel file. `custom-control-status.directive.ts` is imported through the barrel file (`index.ts`), therefore I thought `index.ts` and the 2 modules imported for side effects would be included in the bundle, but they're removed in the tree shaking process. Despite specifying `index.ts`, `abstract-control.ts` and `abstract-control.directive.ts` in my `package.json`'s `"sideEffects"`, they are all excluded from the bundle.
The current workaround is to not use barrel files, meaning to import `abstract-control.ts`, `abstract-control.directive.ts` and `custom-control-status.directive.ts` directly in `app.module.ts`.

**If the current behavior is a bug, please provide the steps to reproduce.**

Repro repository: https://github.com/amitbeck/ng-webpack-sideEffects-repro
Either:
1. Run `npm run build`, or
2. Run `npm run serve` and access through http://localhost:4200

The contents of `abstract-control.ts`, `abstract-control.directive.ts` and `index.ts` in `src/app/utils/forms/` are not included in the bundle, and you therefore the side effects will not be performed. You should get the following runtime error:
> TypeError: this.formGroup.controls.text.setWarnings is not a function.

**What is the expected behavior?**

The contents of `abstract-control.ts` and `abstract-control.directive.ts` should be included in the bundle, and the side effects should be performed. No runtime errors should occur.

**Other relevant information:**
webpack version: 5.67.0
Node.js version: 16.13.1
Angular version: 13.2.7
Operating System: macOS Monterey 12.4

[My SO question](https://stackoverflow.com/questions/72390897/why-are-these-modules-imported-for-side-effects-not-included-in-webpack-bundle)
https://github.com/webpack/webpack/issues/15610#issuecomment-1138473225
According to an Angular team member, it seems to be a webpack issue: https://github.com/angular/angular-cli/issues/23246#issuecomment-1141113638

**Comment by amitbeck** [comment]
> you need to mark `index.ts` as side effect module also

But I did, it's specified in `"sideEffects"` in that directory/module's `package.json`
https://github.com/amitbeck/ng-webpack-sideEffects-repro/commit/9f0fc52d0210efc4cdedd2082e550a19e3a7fa9c/src/app/utils/forms/package.json#L4

**Comment by vankop** [comment]
hm.. sorry I missed it. Could you reduce this just to webpack.config? I'm not familiar with angular..

**Comment by amitbeck** [comment]
Here's the webpack config of Angular 13.2.7:
https://github.com/angular/angular-cli/blob/dc0895222032531d69d9418bc4efee7358a6889a/packages/angular_devkit/build_angular/src/webpack/configs/common.ts#L306-L453

And here's my extension of Angular's webpack config (using [`@angular-builders/custom-webpack`](https://github.com/just-jeb/angular-builders/tree/master/packages/custom-webpack)):
https://github.com/amitbeck/ng-webpack-sideEffects-repro/blob/9f0fc52d0210efc4cdedd2082e550a19e3a7fa9c/custom-webpack.config.js#L3-L13

Composing these configs, we should end up with something like (excerpt with essentials only):
```js
{
  mode: 'production',
  devtool: false,
  target: [
    'web',
    'es2015',
  ],
  context: root,
  module: {
    strictExportPresence: true,
    rules: [
      {
        // Mark files inside `rxjs/add` as containing side effects.
        // If this is fixed upstream and the fixed version becomes the minimum
        // supported version, this can be removed.
        test: /[/\\]rxjs[/\\]add[/\\].+\.js$/,
        sideEffects: true,
      },
      {
        test: /\.ts$/,
        include: ['<project root>/src/app/utils/forms/'],
        sideEffects: true,
      },
    ],
  },
  node: false,
}
```

**Comment by vankop** [comment]
it looks like somehow `CustomControlStatusDirective` is used in  `/src/app/app.component.ts`
```js
;// CONCATENATED MODULE: ./src/app/app.component.ts




let AppComponent = /*#__PURE__*/(() => {
  class AppComponent {
    constructor() {
      this.formGroup = new FormGroup({
        text: new FormControl('')
      });
    }

    ngAfterViewInit() {
      window.setTimeout(() => {
        this.formGroup.controls['text'].setWarnings({
          warning: true
        }); // <- TypeError: this.formGroup.controls.text.setWarnings is not a function
      });
    }

  }

  AppComponent.ɵfac = function AppComponent_Factory(t) {
    return new (t || AppComponent)();
  };

  AppComponent.ɵcmp = /*@__PURE__*/ɵɵdefineComponent({
    type: AppComponent,
    selectors: [["app-root"]],
    decls: 2,
    vars: 1,
    consts: [[3, "formGroup"], ["type", "text", "formControlName", "text"]],
    template: function AppComponent_Template(rf, ctx) {
      if (rf & 1) {
        ɵɵelementStart(0, "form", 0);
        ɵɵelement(1, "input", 1);
        ɵɵelementEnd();
      }

      if (rf & 2) {
        ɵɵproperty("formGroup", ctx.formGroup);
      }
    },
    directives: [ɵNgNoValidate, NgControlStatusGroup, FormGroupDirective, DefaultValueAccessor, NgControlStatus, FormControlName, CustomControlStatusDirective],
    styles: [""]
  });
  return AppComponent;
})();
```
this is some angular magic that fails with side-effects...

**Comment by vankop** [comment]
need to take a look stats with `stats.source=true`, is it possible with `ng`?

**Comment by amitbeck** [comment]
> this is some angular magic that fails with side-effects...

Indeed very weird, brought this up in https://github.com/angular/angular-cli/issues/23246#issuecomment-1144573753

> need to take a look stats with `stats.source=true`, is it possible with `ng`?

You should be able to apply it in [`custom-webpack.config.json`](https://github.com/amitbeck/ng-webpack-sideEffects-repro/blob/9f0fc52d0210efc4cdedd2082e550a19e3a7fa9c/custom-webpack.config.js) which should extend Angular's webpack config. If for some reason it doesn't work, just set `stats.source=true` in Angular's webpack config in `node_modules/@angular-devkit/build-angular/src/webpack/configs/common.js`.

**Comment by vankop** [comment]
ok `app.component` looks like
```js
import { FormControl, FormGroup } from '@angular/forms';
import * as i0 from "@angular/core";
import * as i1 from "@angular/forms";
import * as i2 from "./utils/forms/custom-control-status.directive";
```
and `app.module`
```js
import { ReactiveFormsModule } from '@angular/forms';
import { BrowserModule } from '@angular/platform-browser';
import { AppComponent } from './app.component';
import * as i0 from "@angular/core";
```

so angular magic doesn't respect side effects

**Comment by amitbeck** [comment]
Apparently [the Angular AOT compiler removes anything under `NgModule.declarations`](https://github.com/angular/angular-cli/issues/23246#issuecomment-1144610149), such as `CustomControlStatusDirective`. It's indeed an issue with Angular's emitted code and not webpack. To overcome this, one must indeed add another reference to that import, such as [declaring a `static` property in that `NgModule` class](https://github.com/angular/angular-cli/issues/21952#issuecomment-945752429).
@vankop Thanks a lot for the investigation!

**Comment by vankop** [comment]
yeah, issue should be solved by preventing removing reexport. webpack@5 can handle reexport, so instead of 
```
import * as i2 from "./utils/forms/custom-control-status.directive";
```
should be
```
import * as i2 from "./utils/forms"; // or another import "./index"
```

**Comment by vankop** [comment]
would you open issue in angular/cli ?

**Comment by amitbeck** [comment]
I already have opened https://github.com/angular/angular-cli/issues/23246, which was closed because it seems to be intentional, and can be solved with a workaround as explained in https://github.com/angular/angular-cli/issues/21952#issuecomment-945752429.

**Comment by vankop** [comment]
I created an issue
