### ISSUE TITLE
 __webpack_base_uri__ is not defined

### ISSUE THREAD

**Issue by Ghayour-vialogic** [webpack/webpack#15881]
I am facing following error. Has anyone encountered this before? if yes, how did you manage to resolve?
![image](https://user-images.githubusercontent.com/91672426/171138553-c91d1865-a1c6-4d39-9eb4-180d727094da.png)

**Comment by vankop** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us by recreating the issue using one of our templates.

Please fill out all fields, we can't help you without it

**Comment by vankop** [comment]
please provide webpack.config and what webpack version you are using, thanks.

**Comment by Ghayour110** [comment]
Here is my webpack.config file 

const HtmlWebPackPlugin = require('html-webpack-plugin');
const ModuleFederationPlugin = require('webpack/lib/container/ModuleFederationPlugin');


// webpack.config.js
const Dotenv = require('dotenv-webpack');
const deps = require('./package.json').dependencies;
__webpack_public_path__ = process.env.BASE_PATH_URL;

module.exports = {
  output: {
    publicPath: __webpack_public_path__
  },
  resolve: {
    extensions: [".tsx", ".ts", ".jsx", ".js", ".json"],
  },

  devServer: {
    historyApiFallback: true,
    allowedHosts: ['all'],
    // host: '0.0.0.0',
    port: 3002
  },
  module: {
    rules: [
      {
        test: /\.m?js/,
        type: 'javascript/auto',
        resolve: {
          fullySpecified: false,
        },
      },
      {
        test: /\.(sass|less|css)$/i,
        use: ['style-loader', 'css-loader'],
      },
      {
        test: /\.(woff(2)?|ttf|eot|svg)(\?v=\d+\.\d+\.\d+)?$/,
        use: 'file-loader'
      },
      {
        test: /\.json$/,
        loader: 'json-loader'
      },
      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader',
          options: { presets: ['@babel/env','@babel/preset-react'] }
        },
      },
      {
        test: /\.(png|jpg|gif)$/i,
        type: 'asset/resource'
      },
    ],
  },
  plugins: [
    new ModuleFederationPlugin({
      name: 'citizen',
      filename: 'remoteEntry.js',
      remotes: {
      },
      exposes: {
        './Routes': './src/App.jsx',
      },
      shared: {
        ...deps,
        react: {
          singleton: true,
          requiredVersion: deps.react,
        },
        'react-dom': {
          singleton: true,
          requiredVersion: deps['react-dom'],
        },
        'react-router-dom': {
          singleton: true,
          requiredVersion: deps['react-router-dom'],
        },
      },
    }),
    new Dotenv(),
    new HtmlWebPackPlugin({
      template: './src/index.html',
    }),
  ],
};

**Comment by alexander-akait** [comment]
Please update `HtmlWebPackPlugin` to the latest stable version

**Comment by Ghayour110** [comment]
@alexander-akait  is up to date. But still I am facing the issue

**Comment by alexander-akait** [comment]
@Ghayour110 Can you create small reproducible repo?

**Comment by alexander-akait** [comment]
Also can you remove `file-loader` and use https://webpack.js.org/guides/asset-modules/

**Comment by Ghayour110** [comment]
@alexander-akait yes sure, I can create a repo.
