### ISSUE TITLE
why module federation load url wrong

### ISSUE THREAD

**Issue by CHANCCCZQ** [webpack/webpack#15896]
# Bug report

**What is the current behavior?**
app A load from app B which is expose some component use module federation case wrong url.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. app B expose somethings
![image](https://user-images.githubusercontent.com/22274839/171560465-513c2cb9-08eb-4f47-8675-703b241cdd7e.png)
2. app A use it
![image](https://user-images.githubusercontent.com/22274839/171560510-7a0b687c-e6fc-4a20-bd98-a96dc3f97ad5.png)
3. app A load remoteEntry.js
![image](https://user-images.githubusercontent.com/22274839/171560554-eb5e71a4-05eb-4e82-a17f-15636a5e352f.png)
4. app A load component from remoteEntry.js but it domain comes from app A, the correct domain is from app B
![image](https://user-images.githubusercontent.com/22274839/171560710-84685b44-f41d-40e5-8c90-7a39c660461a.png)
**it must be localhost:1000**, that was my app A server domain.

**What is the expected behavior?**
do the right things,thanks.

**Other relevant information:**
webpack version:  5.72.0
Node.js version:  16.13.1
Operating System:  win 10
Additional tools: nextjs for server-side render

**Comment by CHANCCCZQ** [comment]
https://github.com/module-federation/module-federation-examples/tree/master/nextjs-react when i follow nextjs-example，it present same result.

**Comment by vankop** [comment]
maybe you should specify `publicPath` ?

**Comment by lifeilu** [comment]
> publicPath

I have the same problem, did you find a solution ？

**Comment by lifeilu** [comment]
> https://github.com/module-federation/module-federation-examples/tree/master/nextjs-react when i follow nextjs-example，it present same result.
@CHANCCCZQ I have the same problem, did you find a solution ？

**Comment by lifeilu** [comment]
> maybe you should specify `publicPath` ?

How to specify publicPath? The publicPath is '/' in my host and remote project.

**Comment by alexander-akait** [comment]
@lifeilu Why you need `/`? Can you remove public path everywhere?
