### ISSUE TITLE
about  the callback of  'require.ensure'

### ISSUE THREAD

**Issue by meiyouqing** [webpack/webpack#1589]
at first time, the callback of  'require.ensure'  execute asynchronous,but the second time ,it execute synchronous.
but, the logic in the callback may different while the callback execute asynchronous or synchronous!
how to fix this?

**Comment by IngwiePhoenix** [comment]
`require.ensure` ensures that the modules that are listed exist. Once they do, it become ssync. This is the way it is intended to work. Use `require(array Deps, function Callback[, string Chunkname])` if you want it to always be async. As far as i know, the "normal" function is never sync, if given an array and function as params.

**Comment by sokra** [comment]
> Use require(array Deps, function Callback[, string Chunkname]) if you want it to always be async

It also behaves sometimes sync, sometimes async.

---

I also notices that this behavior is against best pratices with async function and the behavior is different for webpack 2. In webpack 2 it is always async. But I can't change it for webpack 1 because this would be a breaking change.
