### ISSUE TITLE
Unable to bundle javascript file built with emscripten

### ISSUE THREAD

**Issue by grkblood13** [webpack/webpack#15893]
# Bug report

**What is the current behavior?**

After creating a bundle made up of one line importing a emscripten-built javascript file, the client fails to run properly.

The developer console prints the following:

```
speex.js:40215 Uncaught ReferenceError: util is not defined
    at eval (speex.js:40215:1)
    at eval (speex.js:40339:2)
    at Object../src/speex.js (bundle.js:29:1)
    at __webpack_require__ (bundle.js:63:42)
    at eval (index.js:2:67)
    at Module../src/index.js (bundle.js:19:1)
    at __webpack_require__ (bundle.js:63:42)
    at bundle.js:115:37
    at bundle.js:117:12
```

**If the current behavior is a bug, please provide the steps to reproduce.**

I've created a very basic test repository with the code in question here that will create the issue:

https://github.com/grkblood13/webpack-speex

**What is the expected behavior?**

The developer console in Chrome shouldn't output any errors.

**Other relevant information:**
webpack version:  5.72.1
Node.js version: v16.4.0
Operating System: Ubuntu 21.10
Additional tools:

**Comment by vankop** [comment]
regarding builded code it should be not `util.xxxx`, code should looks like `global.util.xxxx`. in `speex.js` code global is `this`, but in common js modules `this` is equal to `module.exports`, so `speex.js` doesn't work as bundled version. So you have 2 options:
- build speex to commonjs and use it as module
- or insert speex as script tag and use as external in webpack
