### ISSUE TITLE
webpackv5 is not supported ESM bundle?

### ISSUE THREAD

**Issue by PachVerb** [webpack/webpack#15908]
## Feature request
- Provide unified packaging support for esm and umd

**What is the expected behavior?**
Provide unified packaging support for esm and umd

**What is motivation or use case for adding/changing the behavior?**

**How should this be implemented in your opinion?**

**Are you willing to work on this yourself?**
yes

**Comment by alexander-akait** [comment]
We support ESM and UMD, please fill out all fields in issue template and I wil, reopen, thank you
