### ISSUE TITLE
compiler.watch error

### ISSUE THREAD

**Issue by qq281113270** [webpack/webpack#15905]
# Bug report

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:    5.72.1 
Node.js version:  v16.14.2
Operating System:  windows
Additional tools: 

My configuration is going to look like this。

let compiler = webpack(webpackConfig);

compiler.watch((err, stats) => {
if (err || stats.hasErrors()) console.error(err);
console.log('Webpack refresh...');
});

 I configured it so that launching webPack would generate an error message，ConcurrentCompilationError: You ran Webpack twice. Each instance only supports a single concurrent compilation at a time.。Watch is fine if I don't use compiler.watch, but I need to use the compiler.watch method。You know what I'm saying？

**Comment by alexander-akait** [comment]
Please stop duplicate, you will get your answer here https://github.com/webpack/webpack/discussions/15901 in near future
