### ISSUE TITLE
you should not provide watch options in `webpack.config` then, use them in `compiler.watch` as an argument

### ISSUE THREAD

**Issue by qq281113270** [webpack/webpack#15904]
you should not provide watch options in `webpack.config` then, use them in `compiler.watch` as an argument

_Originally posted by @vankop in https://github.com/webpack/webpack/issues/15890#issuecomment-1144726957_

**Comment by qq281113270** [comment]
How should I configure it? Could you please provide me with a demo？

**Comment by alexander-akait** [comment]
Please do not duplicate, wait your answer here https://github.com/webpack/webpack/discussions/15901
