### ISSUE TITLE
Support Conditions based on browserlist queries

### ISSUE THREAD

**Issue by 12wrigja** [webpack/webpack#15903]
## Feature request

Background: 

I'm one of the maintainers for a [Temporal polyfill](https://github.com/js-temporal/temporal-polyfill). The package aims to support as many browsers as possible, including those that don't support native bigint (IE11, older versions of Safari, etc). That being said, we continue to get issues filed against us to provide a modern build of the polyfill that doesn't use JSBI (the ponyfill we use) ([ex](https://github.com/js-temporal/temporal-polyfill/issues/155)).

**What is the expected behavior?**

A user can install the Temporal polyfill and use a more modern version of the code (that we provide/ship as part of the npm package content) instead of the current build (which uses JSBI, not native BigInt).

**What is motivation or use case for adding/changing the behavior?**

Provide smaller bundles using more modern code for browsers that support the relevant features, while still retaining compatibility for older browsers.

**How should this be implemented in your opinion?**

One possible solution to this could be use to use [conditions](https://webpack.js.org/guides/package-exports/#conditions-custom) to change the package export to use a different build artifact if we knew the browsers being targetted support bigint. Alternatively, this could make use of the concept of a "featureset year", something that whatwg is considering to allow as the basis for differential serving (https://github.com/whatwg/html/issues/4432).

I believe supporting multiple builds could potentially be done today using an entirely custom condition, but it would be nice if it could be automatically inferred, similar to the "target" attribute for builds (https://webpack.js.org/configuration/target/#browserslist). The condition could be some syntax to match against the resolved browser list (or maybe a js function?).

**Are you willing to work on this yourself?**
no - I'm not at all familiar with Webpack, and am already stretched too thin to commit to working on this.

**Comment by alexander-akait** [comment]
I don't think it is webpack job

**Comment by jkrems** [comment]
I think this could be valuable to other polyfill-style packages as well. E.g. it would allow a package like `whatwg-fetch` to declare that it can be replaced with an mostly empty file in modern browsers, preventing accidentally bloated bundles.

**Comment by alexander-akait** [comment]
In this case we need big map avaliable globals in browser for each verison, it is real big projects, it is out of scope webpack

**Comment by 12wrigja** [comment]
>  big map avaliable globals in browser for each verison,

If the condition allowed for executing arbitrary JS, then this could be easily answered using something like https://github.com/Nyalab/caniuse-api, which can see whether a list of browsers supports some feature.

**Comment by alexander-akait** [comment]
You can create own function to create alises with empty modules and use it here https://webpack.js.org/configuration/resolve/#resolvealias

Also you can create an own plugin for webpack and do it, not sure how we can generally solve it without many limitations and potential unsafe things

**Comment by 12wrigja** [comment]
Is my understanding correct that our users would then have to install a webpack plugin to be able to run our custom behavior? That is not particularly useful - for our use-case, there is already a Babel plugin we point our users to, but we want to eliminate having all our downstream users having to extensively configure this, especially when the info we need is available (indirectly)  from the browserlist.

It would be interesting to allow a browserlist query string as the condition, and iff all browsers a user must support pass the query then use that export. This would mean copying/hard-coding a lengthy condition into the package.json for Temporal, but that seems fine to me.

**Comment by vankop** [comment]
you can right a plugin that will provide in configuration [conditionNames](https://webpack.js.org/configuration/resolve/#resolveconditionnames), looks like this is the best solution for this.
