### ISSUE TITLE
opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ]

### ISSUE THREAD

**Issue by Shashank8271** [webpack/webpack#15900]
# Bug report

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (E:\full stack web dev\React Project\my-app\node_modules\webpack\lib\util\createHash.js:90:53)
    at NormalModule._initBuildHash (E:\full stack web dev\React Project\my-app\node_modules\webpack\lib\NormalModule.js:401:16)
    at E:\full stack web dev\React Project\my-app\node_modules\webpack\lib\NormalModule.js:433:10
    at E:\full stack web dev\React Project\my-app\node_modules\webpack\lib\NormalModule.js:308:13
    at E:\full stack web dev\React Project\my-app\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at E:\full stack web dev\React Project\my-app\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (E:\full stack web dev\React Project\my-app\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at E:\full stack web dev\React Project\my-app\node_modules\babel-loader\lib\index.js:51:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
npm start should display the page which is being failed

**Other relevant information:**
webpack version:  webpack@4.28.3 
Node.js version: v18.2.0
Operating System: windows 11 64 bit
<img width="959" alt="Screenshot 2022-06-02 155542" src="https://user-images.githubusercontent.com/43841494/171610213-dbe05d21-9301-46e1-97a6-7917cbfbacea.png">
<img width="958" alt="Screenshot 2022-06-02 -m" src="https://user-images.githubusercontent.com/43841494/171610822-fff314f8-60fd-4dab-9468-e3538d9346ea.png">

Additional tools: React.js

**Comment by vankop** [comment]
solved in https://github.com/webpack/webpack/issues/14532

**Comment by prabhuteja985** [comment]
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\admin\Downloads\new\examination-management-system\client\esm-client\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\admin\Downloads\new\examination-management-system\client\esm-client\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\admin\Downloads\new\examination-management-system\client\esm-client\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\admin\Downloads\new\examination-management-system\client\esm-client\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\admin\Downloads\new\examination-management-system\client\esm-client\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\admin\Downloads\new\examination-management-system\client\esm-client\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\admin\Downloads\new\examination-management-system\client\esm-client\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\Users\admin\Downloads\new\examination-management-system\client\esm-client\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
C:\Users\admin\Downloads\new\examination-management-system\client\esm-client\node_modules\react-scripts\scripts\start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\admin\Downloads\new\examination-management-system\client\esm-client\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\admin\Downloads\new\examination-management-system\client\esm-client\node_modules\webpack\lib\NormalModule.js:417:16)
    at C:\Users\admin\Downloads\new\examination-management-system\client\esm-client\node_modules\webpack\lib\NormalModule.js:452:10
    at C:\Users\admin\Downloads\new\examination-management-system\client\esm-client\node_modules\webpack\lib\NormalModule.js:323:13
    at C:\Users\admin\Downloads\new\examination-management-system\client\esm-client\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\Users\admin\Downloads\new\examination-management-system\client\esm-client\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (C:\Users\admin\Downloads\new\examination-management-system\client\esm-client\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at C:\Users\admin\Downloads\new\examination-management-system\client\esm-client\node_modules\babel-loader\lib\index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

**Comment by prabhuteja985** [comment]
**
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\admin\Downloads\new\examination-management-system\client\esm-client\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\admin\Downloads\new\examination-management-system\client\esm-client\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\admin\Downloads\new\examination-management-system\client\esm-client\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\admin\Downloads\new\examination-management-system\client\esm-client\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\admin\Downloads\new\examination-management-system\client\esm-client\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\admin\Downloads\new\examination-management-system\client\esm-client\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\admin\Downloads\new\examination-management-system\client\esm-client\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\Users\admin\Downloads\new\examination-management-system\client\esm-client\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
C:\Users\admin\Downloads\new\examination-management-system\client\esm-client\node_modules\react-scripts\scripts\start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\admin\Downloads\new\examination-management-system\client\esm-client\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\admin\Downloads\new\examination-management-system\client\esm-client\node_modules\webpack\lib\NormalModule.js:417:16)
    at C:\Users\admin\Downloads\new\examination-management-system\client\esm-client\node_modules\webpack\lib\NormalModule.js:452:10
    at C:\Users\admin\Downloads\new\examination-management-system\client\esm-client\node_modules\webpack\lib\NormalModule.js:323:13
    at C:\Users\admin\Downloads\new\examination-management-system\client\esm-client\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\Users\admin\Downloads\new\examination-management-system\client\esm-client\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (C:\Users\admin\Downloads\new\examination-management-system\client\esm-client\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at C:\Users\admin\Downloads\new\examination-management-system\client\esm-client\node_modules\babel-loader\lib\index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
**

**Comment by highglow** [comment]
As a little workaround, you can try running node in DEBUG by setting your environment variable in bash
`export DEBUG=true`
<img width="597" alt="image" src="https://user-images.githubusercontent.com/1484905/196067769-a67b59c0-c1ea-4e17-a14b-b84cfb0f6308.png">

For somereason the DebugHash() alternative worked fine.

**Comment by Ahmadshehu54** [comment]
Please i face the same problem as this one, please can someone help me with how i am going to solve it

**Comment by waisay1422** [comment]
don't worry update your node js dependencies .......................

**Comment by iTsChEtAn07** [comment]
> don't worry update your node js dependencies .......................

how will I get to know requirements according to my system?

**Comment by drashan14** [comment]
Don't worry you just add this script in your pakage.json file then your error will be solved.
"scripts": {
    "start": "react-scripts --openssl-legacy-provider start",
    "build": "react-scripts --openssl-legacy-provider build",
}

**Comment by jacob20223** [comment]
pls i also face same problem but im using vue frame-work

**Comment by hansenf** [comment]
> Don't worry you just add this script in your pakage.json file then your error will be solved. "scripts": { "start": "react-scripts --openssl-legacy-provider start", "build": "react-scripts --openssl-legacy-provider build", }

This one was worked for my case, thank you!

**Comment by AleksandarMunje** [comment]
> Don't worry you just add this script in your pakage.json file then your error will be solved. "scripts": { "start": "react-scripts --openssl-legacy-provider start", "build": "react-scripts --openssl-legacy-provider build", }

pls help me implement this to my code!  I dont know how to make it work

**Comment by JC7515** [comment]
hola tengo el mismo problema y es frustacion, yo estoy que trabajo con vite y estoy intentando instalar storybook y ejecutarlo, pero me sale el error :

  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

intente resolverlo poniendo el mensaje : --openssl-legacy-provider  , en mis scripts, pero no me funciono.
Estos son mis scripts: 
"scripts": {
    "dev": " vite",
    "build": " vite build",
    "preview": "vite preview",
    "storybook": " start-storybook -p 6006",
    "build-storybook": "build-storybook"
  },
ayuda porfavor :(

**Comment by JC7515** [comment]
Hi, I have the same problem and it's frustrating, I'm working with vite and I'm trying to install storybook and run it, but I get the error:

   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
   library: 'digital envelope routines',
   reason: 'unsupported',
   code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

I tried to solve it by putting the message : --openssl-legacy-provider , in my scripts, but it didn't work for me.
These are my scripts:
"scripts": {
     "dev": "vite",
     "build": " vite build",
     "preview": "visit preview",
     "storybook": " start-storybook -p 6006",
     "build-storybook": "build-storybook"
   },
please help :(

**Comment by GioDevJS** [comment]
Have you tried this?
 "start": "react-scripts --openssl-legacy-provider start",
"build": "react-scripts --openssl-legacy-provider build",

**Comment by GioDevJS** [comment]
Cambia el script x : "start": "react-scripts --openssl-legacy-provider start".

**Comment by deepsinh231** [comment]
"scripts": {
    "start": "export SET NODE_OPTIONS=--openssl-legacy-provider && react-scripts start",
    "build": "export SET NODE_OPTIONS=--openssl-legacy-provider && react-scripts build"
}

**Comment by sanat-surya** [comment]
use this it will solve your all problem
npm install react-scripts@latest

**Comment by Mussassa** [comment]
> Don't worry you just add this script in your pakage.json file then your error will be solved. "scripts": { "start": "react-scripts --openssl-legacy-provider start", "build": "react-scripts --openssl-legacy-provider build", }

Thanks, this solved my issue!

**Comment by Friosn** [comment]
> Don't worry you just add this script in your pakage.json file then your error will be solved. "scripts": { "start": "react-scripts --openssl-legacy-provider start", "build": "react-scripts --openssl-legacy-provider build", }

And if I do have the same error but I am working with vue.js? u.u

**Comment by jagdishpal02000** [comment]
> Don't worry you just add this script in your pakage.json file then your error will be solved. "scripts": { "start": "react-scripts --openssl-legacy-provider start", "build": "react-scripts --openssl-legacy-provider build", }

worded for me also but why it worked ?

**Comment by tiobista** [comment]
> Don't worry you just add this script in your pakage.json file then your error will be solved. "scripts": { "start": "react-scripts --openssl-legacy-provider start", "build": "react-scripts --openssl-legacy-provider build", }

Thank you it just worked for me

**Comment by Pratik-Jha** [comment]
> Hi, I have the same problem and it's frustrating, I'm working with vite and I'm trying to install storybook and run it, but I get the error:
> 
> opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ], library: 'digital envelope routines', reason: 'unsupported', code: 'ERR_OSSL_EVP_UNSUPPORTED' }
> 
> I tried to solve it by putting the message : --openssl-legacy-provider , in my scripts, but it didn't work for me. These are my scripts: "scripts": { "dev": "vite", "build": " vite build", "preview": "visit preview", "storybook": " start-storybook -p 6006", "build-storybook": "build-storybook" }, please help :(

Try this 
"scripts": { "dev": "SET NODE_OPTIONS=--openssl-legacy-provider && vite", "build": " vite build", "preview": "visit preview", "storybook": "SET NODE_OPTIONS=--openssl-legacy-provider && start-storybook -p 6006", "build-storybook": "SET NODE_OPTIONS=--openssl-legacy-provider && build-storybook" },

**Comment by lingzizheng** [comment]
> Don't worry you just add this script in your pakage.json file then your error will be solved. "scripts": { "start": "react-scripts --openssl-legacy-provider start", "build": "react-scripts --openssl-legacy-provider build", }

Save my life! Tried to use ChatGPT but it failed to answer.

**Comment by Livingston-k** [comment]
Here are two options now -

Try to uninstall Node.js version 17+ and reinstall Node.js version 16+
You can re-install the current LTS Node.js version from their [Official site](https://github.com/coreybutler/nvm-windows). Or more specific downloads from [here](https://github.com/nvm-sh/nvm);

You can use NVM (Node Version Manager)

Linux and Mac users can use this nvm package [link](https://github.com/nvm-sh/nvm)
Windows users can use this nvm package [link](https://github.com/coreybutler/nvm-windows)
Open a terminal and paste these as described:
Linux and macOS (Windows Git Bash)-

export NODE_OPTIONS=--openssl-legacy-provider
Windows command prompt-

set NODE_OPTIONS=--openssl-legacy-provider
Windows PowerShell-

$env:NODE_OPTIONS = "--openssl-legacy-provider"

**Comment by omjaju18** [comment]
> "scripts": { "start": "react-scripts --openssl-legacy-provider start", "build": "react-scripts --openssl-legacy-provider build", }

its not working for me but 
it shows error

**Comment by Livingston-k** [comment]
You can also modify your scripts in the package.json like below, am giving a vue example here but you can borrow an idea to react and other frameworks

 "scripts": {
  "serve": "export NODE_OPTIONS=--openssl-legacy-provider && vue-cli-service serve",
  "build": "export NODE_OPTIONS=--openssl-legacy-provider && vue-cli-service build",
  "lint": "export NODE_OPTIONS=--openssl-legacy-provider && vue-cli-service lint"
},

**Comment by NaveenMS45** [comment]
> Don't worry you just add this script in your pakage.json file then your error will be solved. "scripts": { "start": "react-scripts --openssl-legacy-provider start", "build": "react-scripts --openssl-legacy-provider build", }

yeah it really helped.

**Comment by Daniel15** [comment]
Not sure why so many comments are talking about `react-scripts`, Vue, Vite and Storybook when this is the Webpack repo, not the repo for all those other systems.

For Webpack itself... I hit the same issue in one of my apps. These were my scripts:
```
    "build-dev": "cross-env NODE_ENV=development webpack --config webpack/dev.js",
    "build-prod": "cross-env NODE_ENV=production webpack --config webpack/prod.js",
    "check-types": "tsc",
    "watch": "cross-env NODE_ENV=development webpack-dev-server --progress --color --port 3004 --config webpack/dev.js"
```

I just added `NODE_OPTIONS=--openssl-legacy-provider` to the `cross-env` call to fix it:
```
    "build-dev": "cross-env NODE_ENV=development NODE_OPTIONS=--openssl-legacy-provider webpack --config webpack/dev.js",
    "build-prod": "cross-env NODE_ENV=production NODE_OPTIONS=--openssl-legacy-provider webpack --config webpack/prod.js",
    "watch": "cross-env NODE_ENV=development NODE_OPTIONS=--openssl-legacy-provider webpack-dev-server --progress --color --port 3004 --config webpack/dev.js"
```

**Comment by Ismail826** [comment]
"scripts": {
    "start": "react-scripts  --openssl-legacy-provider start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  }

**Comment by Jamal-ReachFirst** [comment]
Reopen

**Comment by Ole994** [comment]
> Don't worry you just add this script in your pakage.json file then your error will be solved. "scripts": { "start": "react-scripts --openssl-legacy-provider start", "build": "react-scripts --openssl-legacy-provider build", }

Thanks. It worked :)

**Comment by JamAlves** [comment]
opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Esse e o meu erro em aplicação Vue não sei como resolver , help-me plaese

**Comment by shiraliali** [comment]
What i can do to fix it in React Native?

**Comment by Daniel15** [comment]
> What i can do to fix it in React Native?

This is the repo for Webpack. React Native doesn't use Webpack. You should search the issues in the React Native Github repo to see if a fix is listed there.

**Comment by belly34** [comment]
> Don't worry you just add this script in your pakage.json file then your error will be solved. "scripts": { "start": "react-scripts --openssl-legacy-provider start", "build": "react-scripts --openssl-legacy-provider build", }
this worked for me i appriciate for the help

**Comment by WriestTavo** [comment]
lo solucione de  la siguiente manera: en el package.json
`
    "scripts": {
    "start": "craco --openssl-legacy-provider start",
    "build": "craco --openssl-legacy-provider build",
    "test": "craco test",
    "eject": "craco eject"
  }
`

**Comment by Jamal-ReachFirst** [comment]
Just upgrade the react-native version, resolve the issue for me

**Comment by Digital-Nerd** [comment]
> Don't worry you just add this script in your pakage.json file then your error will be solved. "scripts": { "start": "react-scripts --openssl-legacy-provider start", "build": "react-scripts --openssl-legacy-provider build", }

Thank you for your help...... it really helped and my code is now working !!!!

**Comment by lEduFranco** [comment]
> > Hi, I have the same problem and it's frustrating, I'm working with vite and I'm trying to install storybook and run it, but I get the error:
> > opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ], library: 'digital envelope routines', reason: 'unsupported', code: 'ERR_OSSL_EVP_UNSUPPORTED' }
> > I tried to solve it by putting the message : --openssl-legacy-provider , in my scripts, but it didn't work for me. These are my scripts: "scripts": { "dev": "vite", "build": " vite build", "preview": "visit preview", "storybook": " start-storybook -p 6006", "build-storybook": "build-storybook" }, please help :(
> 
> Try this "scripts": { "dev": "SET NODE_OPTIONS=--openssl-legacy-provider && vite", "build": " vite build", "preview": "visit preview", "storybook": "SET NODE_OPTIONS=--openssl-legacy-provider && start-storybook -p 6006", "build-storybook": "SET NODE_OPTIONS=--openssl-legacy-provider && build-storybook" },


for the storybook it worked for me removing the "SET":

`"storybook": "NODE_OPTIONS=--openssl-legacy-provider && start-storybook -p 6006",`

**Comment by davmaene** [comment]
I had the same problem but this solved the problem using ```umi```

```
  "scripts": {
    "start": "SET NODE_OPTIONS=--openssl-legacy-provider && umi dev",
    "build": "SET NODE_OPTIONS=--openssl-legacy-provider && umi build",
...
}
```

**Comment by umid0608** [comment]
> "scripts": { "start": "react-scripts --openssl-legacy-provider start", "build": "react-scripts build", "test": "react-scripts test", "eject": "react-scripts eject" }

What about angular?

**Comment by Daniel15** [comment]
> What about angular?

@umid0608 This issue is specifically for Webpack. You should search the Angular repo if you need information for Angular-specific tooling.

**Comment by msalmankhalid23** [comment]
> Don't worry you just add this script in your pakage.json file then your error will be solved. "scripts": { "start": "react-scripts --openssl-legacy-provider start", "build": "react-scripts --openssl-legacy-provider build", }

This worked for me

**Comment by Jatingupta9120** [comment]
please someone help me 
Error:-D:\7 sem\ReactPractise\Gofood\node_modules\react-scripts\scripts\start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (D:\7 sem\ReactPractise\Gofood\node_modules\webpack\lib\util\createHash.js:90:53)
    at NormalModule._initBuildHash (D:\7 sem\ReactPractise\Gofood\node_modules\webpack\lib\NormalModule.js:401:16)
    at D:\7 sem\ReactPractise\Gofood\node_modules\webpack\lib\NormalModule.js:433:10
    at D:\7 sem\ReactPractise\Gofood\node_modules\webpack\lib\NormalModule.js:308:13
    at D:\7 sem\ReactPractise\Gofood\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at D:\7 sem\ReactPractise\Gofood\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (D:\7 sem\ReactPractise\Gofood\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at D:\7 sem\ReactPractise\Gofood\node_modules\babel-loader\lib\index.js:51:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.14.0

  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },

**Comment by Harry180** [comment]
For node 18.19.0 adding this line to `output` of your `webpack.config.js` fixes the problem:
> hashFunction: 'sha512',

**Comment by CyveTech** [comment]
> Don't worry you just add this script in your pakage.json file then your error will be solved. "scripts": { "start": "react-scripts --openssl-legacy-provider start", "build": "react-scripts --openssl-legacy-provider build", }

This worked for me:

**Comment by Sandip-Kanzariya** [comment]
> use this it will solve your all problem 
```bash
npm install react-scripts@latest
```
