### ISSUE TITLE
require.context is not a function is ESM (type: module)

### ISSUE THREAD

**Issue by wclr** [webpack/webpack#15917]
**What is the current behavior?**

If we have ES module (example):

```js
const context = require.context(
  "./icons",
  true,
  /^[.\\/a-zA-Z\d-]+\.svg$/,
  "sync"
)

export const icons = context
  .keys()
  .map(context)
  .map(m => m.default)
```
and the nearest `package.json` contains `{"type": "module"}` then while a build we get the error:

```
require.context is not a function
```

If to remove `{"type": "module"}` in `package.json` there will be no error, build is ok.

**If the current behavior is a bug, please provide the steps to reproduce.**

webpack version:   5.72.0
Node.js version: 16
Operating System: Windows 10

**Comment by alexander-akait** [comment]
`require.context` doesn't exit in ESM, please use `import(...)`

**Comment by wclr** [comment]
@alexander-akait 
What you mean by `import(..)`? What is the replacement for `require.context` in ESM? 

Here I found https://webpack.js.org/api/module-variables/#importmetawebpack

I tried to use `import.meta.webpackContext` but got the error: `{}.webpackContext is not a function`

**Comment by wclr** [comment]
It turned out that this happens when `import.meta.webpackContext` is used inside `html-webpack-plugin` template module.
```js
    new HtmlWebpackPlugin({
      filename: "index.html",
      template: "template.js",
    }),
```

and tempalte.js somethingn like (just for the sake of example):

```
import.meta.webpackContexts()

export default ""
```


It throws the error: `{}.webpackContexts is not a function`

![image](https://user-images.githubusercontent.com/736697/172479749-d77f05f4-1697-4709-9aba-5df554972577.png)

Any ideas what is the reason and how this can be fixed?

**Comment by vankop** [comment]
you are using `import.meta.webpackContexts` but should use `import.meta.webpackContext` ( without `s` in the ending )

**Comment by wclr** [comment]
@vankop hah that's funny, actually when I tried this in the code it was spelled correctly, I'm not sure why added `s` here. So the error with  `import.meta.webpackContext` happens as well:

![image](https://user-images.githubusercontent.com/736697/172568468-d599a4d3-3bc8-4f8d-bb92-2d89447eb86a.png)

**Comment by vankop** [comment]
then you have loader that changes `import.meta.webpackContext` to `{}.webpackContext`

**Comment by alexander-akait** [comment]
@wclr Bug in `html-webpack-plugin`, they don't support this feature... they execute template using Node.js, so you don't have `webpackContext`, it is not webpack module, it is just JS file, HTML webpack plugin needs to redesign code to support it...

**Comment by wclr** [comment]
@alexander-akait 
> they execute template using Node.js, so you don't have webpackContext,

But why if I use CJS module I can use `require.context` here?

**Comment by alexander-akait** [comment]
I think due to this https://github.com/jantimon/html-webpack-plugin/blob/main/lib/child-compiler.js#L90, ESM is just not enabled here...

**Comment by wclr** [comment]
@alexander-akait hah thanks!

I just replaced `require.context` with `import.meta.webpackContext` and got call with 4 params:

```
const context = import.meta.webpackContext(
  "@charta/client/fonts/proxima",
  true,
  /^((?!(Thin)).)*$/,
 "sync"
)
```

And got this error. So it is about illegal use of params of `import.meta.webpackContext` - it is quite strange and misleading behaviour -)

**Comment by alexander-akait** [comment]
`webpackContext` has other aguments:
```ts
webpackContext: (
		request: string,
		options?: {
			recursive?: boolean;
			regExp?: RegExp;
			include?: RegExp;
			exclude?: RegExp;
			preload?: boolean | number;
			prefetch?: boolean | number;
			chunkName?: string;
			exports?: string | string[][];
			mode?: "sync" | "eager" | "weak" | "lazy" | "lazy-once";
		}
	) => webpack.Context;
```

i.e. you should pass `regExp` and `mode` in options (the second argument)

**Comment by wclr** [comment]
@alexander-akait Yes I see this in docs)) it works ok now. It is just misleading webpack error.

**Comment by vankop** [comment]
bump

**Comment by alexander-akait** [comment]
@vankop What do we have to solve here?

**Comment by vankop** [comment]
> I think we should throw an error on empty import.meta.webpackContext()

**Comment by zhangv** [comment]
Try this:

```javascript
const files =  import.meta.globEager('./*.js');
const keys = Object.keys(files);
for (let path of keys) {
    //do your thing
}
```

**Comment by alexander-akait** [comment]
For webpack you should use `import.meta.webpackContext`
