### ISSUE TITLE
Bundle difference between 5.21.2 and 5.22.0+

### ISSUE THREAD

**Issue by LunaticMuch** [webpack/webpack#15928]
# Bug report

I have noticed there's a difference in the format of the bundle between 5.21.2 and 5.22.0+.
I am making a change to a small loader which today is using `5.9.0` and since I moved to `5.73.0` all my tests have stopped working. The resulting bundle can't be evaluated.

**What is the current behavior?**

The `bundle.js` returned using [this configuration](https://github.com/LunaticMuch/svg-as-symbol-loader/blob/feat/deps-bump/test/loader.spec.js#L15-L37) does not include anymore, at the top, the `module.exports =` which prevent my [evaluation function](https://github.com/LunaticMuch/svg-as-symbol-loader/blob/feat/deps-bump/test/loader.spec.js#L51-55) from working.

[bundle_5.73.0.txt](https://github.com/webpack/webpack/files/8861083/bundle_5.73.0.txt)

**If the current behavior is a bug, please provide the steps to reproduce.**

You can reproduce it cloning my repo, on `master` branch, with webpack `5.9.0` everything works. On `feat/deps-bump` with webpack `5.73.0` it does not work.  Doing few tests, I discovered the behavior changes from `5.21.2` and `5.22.0.`

**What is the expected behavior?**

[bundle_5.9.0.txt](https://github.com/webpack/webpack/files/8861084/bundle_5.9.0.txt)

**Other relevant information:**
webpack version:   5.73.0
Node.js version:  16.14
Operating System:  MacOS
Additional tools:

**Comment by alexander-akait** [comment]
Unfortunately it is unsafe to rely on this, using `eval` you need to have `return`, but it is invalid when we build libraries, you need to rewrite tests. I recommend these steps
1. Let's set `target: 'node'` firstly, because we want to tests it and we will have `node` env (in some cases you can generate code for browser and it will be a problem)
2. Then let's rewrite:
```js
async function evaluateGeneratedBundle() {
  return eval(`require("${getBundleFile()}")`);
}
```

It is even faster, you don't need to read a file
3. I recommend to generate tmp file (https://github.com/raszi/node-tmp)/unique file name for each output, otherwile you can have racing here and tests will not be stable

**Comment by LunaticMuch** [comment]
I now about `eval` unfortunately. I will take your suggestion later and give them a go. I though I could remove eval and change approach; although I ended in a rabbit hole with trying to find the reason the bundle was coming out differently.

**Comment by LunaticMuch** [comment]
The problem is effectively sorted, it used to exports modules and not we have a closure. The side issue, not related to this, is that because I use a `require` as per your solution, the first test passes, but when I generate a second bundle and require it again, node has the old (same file name) in the cache, so it does not update it. 
Interestingly, deleting node module cache seems not an easy and effective solution (as opposed to what the logic would suggest). I am going to use `[contenthash]` or another identifier in the module name which should in theory solve the problem.
