### ISSUE TITLE
recordsPath: Potentially breaks build if used incorrectly

### ISSUE THREAD

**Issue by IngwiePhoenix** [webpack/webpack#1593]
...and I did that.

Basically, here is what happened:

- I saw the docs about `recordsPath` and was like, "increasing build perfs might be nice!" and threw `recordsPath: path.join(app.root, "cache")` into my config. that folder exists, so I thought I was fine.
- Before testing it, I had updated node using `n`: `n stable` --> `node v5.0.0`
- Now, running this particular configuration resulted in:

    Error: EISDIR: illegal operation on a directory, read
        at Error (native)

Now, it took me a good forever (2 hours that I could've used to sleep...) to figure this out.

Using the Node debugger, it continiously reported that WP was trying to access `.../app/System/Config/webpack.js/package.json` - well duh, that IS not a folder, yep.

Throwing a lot of `console.log`s into the code finally revealed, that it was triyng to access the records and read off them. Hnnngh... okay. o.o

So I would like to ask for a simple example of how to use the `recordsPath` - because the docs only have a 1-liner about them...

Kind regards, Ingwie

**Comment by sokra** [comment]
records doesn't increase performance.

http://webpack.github.io/docs/configuration.html#recordspath-recordsinputpath-recordsoutputpath

There are 3 lines...
