### ISSUE TITLE
In the webpack v5.73.0, use the compiler = webpack(config) report an error  what compiler.plugin is not a function   at setupCompiler

### ISSUE THREAD

**Issue by hcxmj** [webpack/webpack#15939]
var webpack = require('webpack');
var config = require('../config/webpack.config.dev');

function setupCompiler(host, port, protocol) {
   compiler = webpack(config, handleCompile);
   compiler.plugin('invalid', function() {XXXXX
   compiler.plugin('done', function(stats) {
}

 TypeError: compiler.plugin is not a function at setupCompiler

**Comment by alexander-akait** [comment]
Expected, we don't have `plugin` method, we have hooks, please look at documentation https://webpack.js.org/api/compiler-hooks/

**Comment by hcxmj** [comment]
Ok,thank you very much @alexander-akait ；
I used the following way to deal with：
###########################
compiler = webpack(config, handleCompile);
  if (compiler.hooks) {
    const plugin = { name: 'FriendlyErrorsWebpackPlugin' };

    compiler.hooks.done.tap(plugin, doneFn);
    compiler.hooks.invalid.tap(plugin, invalidFn);
  } else {
    compiler.plugin('done', doneFn);
    compiler.plugin('invalid', invalidFn);
  }
##########################
