### ISSUE TITLE
[ERR_REQUIRE_ESM]: require() of ES Module when using ES loader

### ISSUE THREAD

**Issue by wclr** [webpack/webpack#15930]
# Bug report

Trying to use a ESM module as a loader, simple repro:

https://github.com/wclr/webpack-esm-loader-issue

**What is the current behavior?**

```
Module build failed (from ./loader.js):
Error [ERR_REQUIRE_ESM]: require() of ES Module ..\webpack-esm-loader-issue\loader.js from D:\Code\webpack-esm-loader-issue\node_modules\loader-runner\lib\loadLoader.js not supported.
Instead change the require of loader.js in ..\webpack-esm-loader-issue\node_modules\loader-runner\lib\loadLoader.js to a dynamic import() which is available in all CommonJS modules.
```

**Other relevant information:**
webpack version:  5.73.0
Node.js version: 16
Operating System: Windows 10

**Comment by jramstedt** [comment]
`ERROR in ./assets/a.png?split-alpha&quality=1&colors=4
Module build failed: Error [ERR_REQUIRE_ESM]: require() of ES Module ***\loaders\splitalpha.js from ***\node_modules\webpack\lib\ProgressPlugin.js not supported.
Instead change the require of splitalpha.js in ***\node_modules\webpack\lib\ProgressPlugin.js to a dynamic import() which is available in all CommonJS modules.`

**Comment by vankop** [comment]
should be fixed by https://github.com/webpack/webpack/pull/15198

**Comment by alexander-akait** [comment]
bump

**Comment by alexander-akait** [comment]
Close in favor https://github.com/webpack/webpack/issues/13233, we will ship it in the next release, sorry for delay
