### ISSUE TITLE
How to correctly parse the chunk resources in the library packaged by another webpack in webpack5?

### ISSUE THREAD

**Issue by llllllllllx** [webpack/webpack#15947]
webpack version: 5.73.0

The content of this library is roughly as follows
````js
// wepback.config.js
module.exports = {
    entry: './entry.js',
    output: {
        filename: 'index.js',
        chunkFilename: 'chunk.[chunkhash:8].js',
        path: path.join(__dirname, './dist'),
        publicPath: 'auto',

        library: {
           type: 'module',
        },
    },

    experiments: {
        outputModule: true,
    },
}

// entry.js
export default async () => {
    const num = (await import('./test.js')).default
    return 1 + num()
}

//test.js
export default() => 2

````

After build, index.js and chunk.xxxx.js are generated in dist folder

After calling this library in another webapck project, the brief code is as follows
````js

import getNumber from 'xx/dist/index.js'

window.onload = async() => {
    console.log(await getNumber())
}

````

After the code is executed, it will report the error _Not allowed to load local resource: file:///Users/os/xxx/dist/chunk.xxxx.js_

Then I checked the function `__webpack_require__.f.j` that loads the chunks resource in the index.js file in the library, the url of the chunk resource in the generated code is
````js
var url = __webpack_require__.p + __webpack_require__.u(chunkId);
````

I think this is the reason for the error, because the variable url always returns a file address (file://xxx/xxx/), I think it should be the address that uses the URL for processing, such as
````js
var url = new URL(__webpack_require__.u(chunkId), import.meta.url)
````

But after I modified the code, it still could not be parsed correctly until the value of `__webpack_require__.u(chunkId)` was directly filled in, which is the file name of the chunk
````js
var url = new URL('chunk.xxxx.js', import.meta.url);
````

At this time, the call is normal, and the url of the chunks file can be parsed normally.

**Comment by vankop** [comment]
`library.type=module` need some enhancement, but unfortunately this is low priority...

**Comment by vankop** [comment]
added on board https://github.com/webpack/webpack/projects/8#column-18928777

**Comment by alexander-akait** [comment]
игьз

**Comment by alexander-akait** [comment]
Let's close in favor https://github.com/webpack/webpack/issues/17121
