### ISSUE TITLE
Target es5 does not transpile node modules dependencies to es5 in some cases

### ISSUE THREAD

**Issue by zakuru** [webpack/webpack#15942]
# Bug report
I have a case where I include a library which is not es 5 transpiled
I was expecting that by setting target to ["web", "es5", "browerslist"] that webpack would transpile the whole finale bundle to es5
The but is that IE 11 break even though the target is set. My browerslist contains IE 11

**What is the current behavior?**
Third party libraries coming from node modules are not (always) transpiled correctly according to the webpack target.
Is is actually a but of by design ?

Thanks  

**If the current behavior is a bug, please provide the steps to reproduce.**
Create a small project that references punycode npm

**What is the expected behavior?**
The target setting should apply to all third party dependencies

**Other relevant information:**
webpack version:  5.70
Node.js version:  14.18.2
Operating System:  window / linux
Additional tools:

**Comment by vankop** [comment]
webpack doesn't modify user modules. You should use tools like babel for this..
_____
`target: "es5"`  means webpack runtime code will be produced matching es5.

**Comment by zakuru** [comment]
thanks !

**Comment by ellenmartin22** [comment]
Zakuru San ***@***.***> schrieb am So. 12. Juni 2022 um 12:18:
