### ISSUE TITLE
webpackMode: "weak" is fail, When module is in node_modules

### ISSUE THREAD

**Issue by myNameIsDu** [webpack/webpack#15941]
# Bug report

**What is the current behavior?**
`webpackMode: "weak"` faile, when module is in `node_modules`

**If the current behavior is a bug, please provide the steps to reproduce.**
https://stackblitz.com/edit/webpack-webpack-js-org-pdtara?file=src/component.jsx

**What is the expected behavior?**
Load modules correctly

**Other relevant information:**
webpack version:  5.38.1
Node.js version: v16.14.2

**Comment by vankop** [comment]
`<C />` component is used so `react-intl` is used.. (Also it is used in `index.jsx`)

**Comment by myNameIsDu** [comment]
> `<C />` component is used so `react-intl` is used.. (Also it is used in `index.jsx`)

Thanks very much for spending the time to check this issue. But if it the `react-intl` is used, It shouldn't out an error. And now it was outed an error.

<img width="1189" alt="image" src="https://user-images.githubusercontent.com/53305259/189486480-246913b0-4036-4a8f-834a-4d7bf6a0e9d6.png">

**Comment by alexander-akait** [comment]
Hm, do you load this component before using?

**Comment by myNameIsDu** [comment]
> Hm, do you load this component before using?

Thanks for your reply,  Here's the example: https://stackblitz.com/edit/webpack-webpack-js-org-tjvtv8?file=src/index.jsx

I loaded `react-intl` in `index.jsx`, And i created another module `external.js`. And it won't throw an error.

<img width="629" alt="image" src="https://user-images.githubusercontent.com/53305259/189537378-3c939ae7-2fdc-4e8f-9125-b33a3e571015.png">

<img width="1348" alt="image" src="https://user-images.githubusercontent.com/53305259/189537403-0fd2e94c-25a6-4a3b-9d56-88372314de57.png">

**Comment by alexander-akait** [comment]
Please look at this firstly:
```
npm ERR! While resolving: react-intl@3.12.1
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR!   peer react@"17.0.2" from react-dom@17.0.2
npm ERR!   node_modules/react-dom
npm ERR!     react-dom@"^17.0.2" from the root project
```

Anyway, I don't see problems here, you don't need to use `weak` here

> 'weak': Tries to load the module if the module function has already been loaded in some other way (e.g. another chunk imported it or a script containing the module was loaded). A Promise is still returned, but only successfully resolves if the chunks are already on the client. If the module is not available, the Promise is rejected. A network request will never be performed. **This is useful for universal rendering when required chunks are always manually served in initial requests (embedded within the page), but not in cases where app navigation will trigger an import not initially served.**

Please read this https://indepth.dev/posts/1483/demistifying-webpacks-import-function-using-dynamic-arguments, here good explain why it happens

**Comment by alexander-akait** [comment]
Also you can do it using:
```js
const IntlProvider = (await import(
          /* webpackMode: "weak" */ 'react-intl/lib/src/components/provider.js'
        )).default;
```
