### ISSUE TITLE
IE8 does not support indexOf method of Array, 

### ISSUE THREAD

**Issue by shelbeniskb** [webpack/webpack#1595]
I meet the code in webpack
```
if(installedModules[request].parents.indexOf(moduleId) < 0)
```
but the IE8 seems not support indexOf, how can I make a workaround?

**Comment by noomorph** [comment]
@shelbeniskb, well, maybe you could include a polyfill beforehand into your source HTML file...
```
<script type="text/javascript">
/* indexOf polyfill */
</script>
```

**Comment by shelbeniskb** [comment]
@noomorph Thanks, it can solve the problem, but not very well.
there is also another similar solution:

```
entry: {
    main: [
      'es5-shim',
      './src/js/main.js'
    ]
  }
```

**Comment by noomorph** [comment]
@shelbeniskb , ohhh, I thought webpack's bootstrap section in entry file is incomptabile with IE8... Your suggested option is a bit safer and cleaner.
