### ISSUE TITLE
Compilation Error while processing magic comment should not be downgraded to warning

### ISSUE THREAD

**Issue by ryanwilsonperkin** [webpack/webpack#15960]
# Bug report

**What is the current behavior?**

When building a project that contains an invalid webpackChunkName (eg. `/* webpackChunkName: foo */) the compiler emits the message

```
Compilation error while processing magic comment(-s): /* webpackChunkName: foo */: foo is not defined
```

Which then results in just a warning at the build level. This should be a build error instead of just a warning, as the chunk does end up getting built but with an unpredictable name, which can break other processes.

(The solution of course is that `foo` should be `'foo'`, but since this doesn't fail the build it can be undetected in large Webpack builds that might have lots of output)

**If the current behavior is a bug, please provide the steps to reproduce.**

Reproduction here: https://github.com/ryanwilsonperkin/webpack-dynamic-import-compilation-warning
1. Fetch this repo
2. `yarn` to install dependencies
3. `yarn build`

Alternatively, create another minimal reproduction with two files that look like so:

```
// src/index.js
import(/* webpackChunkName: foo */ './foo')

// src/foo.js
console.log("A separate module")
```

And then run the default `webpack` build (which finds the src/index.js as default entrypoint)

**What is the expected behavior?**

I would expect that the term "Compilation Error" indicates that this is an error and should prevent the build from completing, which will make it easier for developers to detect that something is written incorrectly and correct it.

**Other relevant information:**
webpack version:  5.73.0
Node.js version: v18.2.0
Operating System: MacOS
Additional tools:

**Comment by alexander-akait** [comment]
Yeah, I think too, but it can be breaking change...

**Comment by ryanwilsonperkin** [comment]
How about a configuration option that defaults to `warn` but can be manually set to `error`?
Should prevent it from being a breaking change, but could be swapped to `error` in the next major release if desired.

**Comment by alexander-akait** [comment]
@ryanwilsonperkin We have https://webpack.js.org/configuration/experiments/#experimentsfuturedefaults, so we can change it when it is `true`

**Comment by ryanwilsonperkin** [comment]
That'd be great, would you be interested in a PR adding this behaviour?

**Comment by alexander-akait** [comment]
Yep, feel free to send a PR

**Comment by vankop** [comment]
I don't think that this should be an error.. but maybe we should in `webpack@6` add one more level of errors? like:
```
critical error P0
error P1
warning P2
```

what do you think @sokra @alexander-akait ?

**Comment by alexander-akait** [comment]
@vankop Why? I think any behaviour which can lead to unexpected result(s) should be an error, but I am fine with extra option here

**Comment by vankop** [comment]
as I understand we trying to achieve build result if possible, e.g. if you have webpack running in watch mode in this case you can get working output, but very likely you have an error in your setting.. it is kind of same behavior as:

index
```js
import { a, b } from "a";
// use a, b
```

a.js
```
// export only a
export { a }
```

webpack compiles or not depending on `exportsPresense` mode. Here is same one:
- webpack can compile
- depending on setting produce warning/error ( maybe error that doesn't result in non-zero exit code )

**Comment by sokra** [comment]
If everything that can lead to unexpected behavior would be an error, then all our warnings would need to be errors.

For these comment parsing, it can happen that we try to parse a normal comment like `/* webpack allows to add comments here */`, where we definitely don't want to error the build.

So these problems are warnings, because we are not 100% sure that this is an real problem and you can ignore warnings.
Errors are cases where we are really sure that it's wrong.

**Comment by alexander-akait** [comment]
Maybe that - https://github.com/taehwanno/warnings-to-errors-webpack-plugin?

**Comment by ryanwilsonperkin** [comment]
Yep! We're currently evaluating that plugin for this purpose, though I'd still stand by the point that it seems like this seems appropriate to be core functionality.

**Comment by sokra** [comment]
> 1. An option to treat all warnings as errors, effectively failing a build if there's any warning

That could be an option for the webpack-cli.

**Comment by vankop** [comment]
> That could be an option for the webpack-cli.

yeah, this also should solve problem.. https://github.com/webpack/webpack-cli/issues/3315
