### ISSUE TITLE
Force webpack resolver to solve node as target for specific package

### ISSUE THREAD

**Issue by Eichenschlaf** [webpack/webpack#15967]
Lets suppose hypothetically our dependency has the following package.json described as:

```
{
  "name": "some-dependency",
  "exports": {
    ".": {
      "browser": {
        "import": "...",
        "require": "..."
      },
      "node": {
        "import": "...",
        "require": "..."
      },
    }
  }
}
```

How can someone force webpack to resolve the node export individually only for some-dependency?. 
I thought `resolve.conditionNames: ["node", "some-dependency"],` would do the trick, but it didn't.

**Comment by alexander-akait** [comment]
Why you need it? It was not design for this, also it is dangerous, but you can see to use https://webpack.js.org/configuration/resolve/#resolvealias

**Comment by Eichenschlaf** [comment]
@alexander-akait I know right and I don't like what I am doing to be honest, but the provider where I host, uses an alternative version of v8 js engine which isn't literally node, so if I wanted to use some nodejs dependency, the target env will be solved to "browser" for some reason. of course, setting the target and bundling individually with some runtime checks, work, but I'm not satisfied with the final solution.

**Comment by vankop** [comment]
yeah, by design `resolve.conditionNames` is used for all packages
__________
you can put you condition names in `rules.resolve` option https://webpack.js.org/configuration/module/#ruleresolve

**Comment by alexander-akait** [comment]
@Eichenschlaf alternativity you can write own plugin, look at code https://github.com/webpack/enhanced-resolve/blob/main/lib/ConditionalPlugin.js, it is simple, because it is exotic I think it will be the right direction
