### ISSUE TITLE
Chrome 102 bug - workaround?

### ISSUE THREAD

**Issue by danielgindi** [webpack/webpack#15976]
# Bug report

**What is the current behavior?**
There may be duplicate resource urls in the sourcemaps. Which is neither defined as valid, nor as invalid.

**If the current behavior is a bug, please provide the steps to reproduce.**

This is actually a query about an existing bug report:
https://bugs.chromium.org/p/chromium/issues/detail?id=1329997

It's a known bug now in Chrome 102, which has been bugging me for 3 weeks now.  
I was wondering if there's a simple way to deduplicate urls in the sourcemap, so we can workaround the Chrome bug.  
People may come here in search of a bugreport on webpack (I initially though it was a webpack issue and downgraded but it did not help).

**What is the expected behavior?**

Should play nice with Chrome Devtools.
The guys at Chromium say that they have been going back and forth between considering duplicate urls and deduplicating them. One side of it causes one kind of bug, the other side causes another kind of bug.
So if there's an override from webpack, we could avoid this hassle altogether.

**Other relevant information:**
webpack version:  5.73.0
Node.js version:  16.3.2
Operating System: WIndows 10
Additional tools:

**Comment by alexander-akait** [comment]
How we can reproduce it?

**Comment by danielgindi** [comment]
In the google bugreport there are reproductions of this, but for me it happens due to an imported component that's compiled with core-js in its sourcemap. Having core-js imported by webpack+babel too - causes duplicate urls. Each url after those in the sourcemap - is treated in an index offset and therefore the breakpoints are not even in the correct file.
Happens in Chrome 103 too, as they have not fixed it yet.

**Comment by alexander-akait** [comment]
Can yo try without babel? Because babel pass source maps to webpack

**Comment by danielgindi** [comment]
Removing babel solves this for me, but that may not be the case for others. Anyway, a fix [has landed](https://chromium-review.googlesource.com/c/devtools/devtools-frontend/+/3720705/3/front_end/core/sdk/SourceMap.ts) already.
And in the meanwhile, my workaround is to download [Chromium 101](https://chromium.cypress.io/win64/stable/101.0.4951.67) for debugging.
