### ISSUE TITLE
Incorrect types for rules, minimizer and plugins

### ISSUE THREAD

**Issue by TheMatrixan** [webpack/webpack#15978]
# Bug report

**What is the current behavior?**
In file: `declarations\WebpackOptions.d.ts` you can see types:
```ts
/**
 * A list of rules.
 */
export type RuleSetRules = ("..." | RuleSetRule)[];

/**
 * Plugins for the resolver.
 */
plugins?: ("..." | ResolvePluginInstance)[];

/**
 * Minimizer(s) to use for minimizing the output.
 */
minimizer?: ("..." | WebpackPluginInstance | WebpackPluginFunction)[];
```

**If the current behavior is a bug, please provide the steps to reproduce.**
N/A

**What is the expected behavior?**
 `"..."`  should be removed from the types for these properties.

**Other relevant information:**
webpack version:  5.73.0
Node.js version: N/A
Operating System: All
Additional tools: N/A

**Comment by alexander-akait** [comment]
`"..."` is valid, you can use `...` to merge with default minimizer and options
