### ISSUE TITLE
warn / bail when invalid paths are used in rule.include

### ISSUE THREAD

**Issue by DanielRuf** [webpack/webpack#15972]
## Feature request

It happens sometimes that invalid paths are entered (via `path.resolve`) in `rule.include`. But webpack silently "accepts" this and the loader does nothing. But the user is confused why nothing has changed. Debugging of this simple but silent error is not that easy.

**What is the expected behavior?**

Invalid paths in `rule.include` (and probably also exclude) like for example `path.resolve(__dirname, 'src', 'node_modules'),` should throw a warning / error so the user knows that there is something not correct.

**What is motivation or use case for adding/changing the behavior?**

Better DX and feedback from webpack, easier debugging.

**How should this be implemented in your opinion?**

Warning and optional setting to bail on invalid paths.

**Are you willing to work on this yourself?**
no (not much time anymore)

**Comment by alexander-akait** [comment]
@DanielRuf We used regexps in `include`/`exclude`, so we can't validate your path

**Comment by DanielRuf** [comment]
> @DanielRuf We are using regexps in `include`/`exclude`, so we can't validate your path

`include` supports:
* regex
* string
* string array (array of conditions)
* function
...

the issue covers the string / string array method, not regex. Maybe that was a bit unclear from my side (`path.resolve()` generates a string).

https://webpack.js.org/configuration/module/#ruleinclude
https://webpack.js.org/configuration/module/#condition

**Comment by DanielRuf** [comment]
> @DanielRuf Why you can't validate paths on your side?

In general webpack config files can have hundreds of files, many loaders and so on. In our case only a person with Node experience would have spotted this but other developers who try to make these changes get no feedback what is wrong.

> also it reduce build time.

This is why I would make this optional / opt-in via setting - and some "strict" webpack mode.

Please keep beginners, juniors, unexperienced developers in mind - we could improve the DX of webpack with such simple steps.

**Comment by DanielRuf** [comment]
> @DanielRuf Why you can't validate paths on your side?

In general webpack config files can have hundreds of lines, many loaders and so on. In our case only a person with Node experience would have spotted this but other developers who try to make these changes get no feedback what is wrong.

> also it reduce build time.

This is why I would make this optional / opt-in via setting - and some "strict" webpack mode.

Please keep beginners, juniors, unexperienced developers in mind - we could improve the DX of webpack with such simple steps.

**Comment by vankop** [comment]
maybe this could make sense, but this will be a breaking change.

**Comment by DanielRuf** [comment]
> maybe this could make sense, but this will be a breaking change.

Not if it is like I proposed: an opt-in setting (opt-in means you have to actively enable / activate it).

**Comment by sokra** [comment]
I think that makes sense. We can show warnings for invalid paths passed to options with `absolutePath: true`, that are not output paths.

**Comment by cmawhorter** [comment]
this is an issue with webpack configs [resolve.aliases](https://webpack.js.org/configuration/resolve/) too.  i was going to open a documentation issue but it almost seems like a webpack util for specifying paths makes more sense e.g. `webpack.resolve`

path.resolve is essentially path.join.  there is [module.resolve](https://nodejs.org/api/modules.html#requireresolverequest-options) which will throw MODULE_NOT_FOUND if the target doesn't exist, but it's not exactly a drop-in replacement for path.resolve.  maybe someone with more knowledge of module.resolve and webpack would know if this is a doc issue or not?

i'm pretty dumb and need to be protected from myself sometimes. asserting paths i enter actually exist would be one of those times.
