### ISSUE TITLE
Webpack HMR Uncaught TypeError: Cannot set properties of undefined

### ISSUE THREAD

**Issue by chenmingzhen** [webpack/webpack#15988]
# Bug report

**What is the current behavior?**
My problem right now is kind of like this one<https://github.com/webpack/webpack/discussions/14873>. But that didn't solve my problem. Let me describe my situation. Webpack Dev Server runs on port 4001. My service is running on port 4000. I export a configuration Array to WebpackDevServer, one for the packaging style and one for the packaging code. Template.html is returned when browsing the localhost:4000 page. HMR fails to update the browser content when I casually modify the contents of the index.tsx file, and it throws the following error.😕
```
Uncaught TypeError: Cannot set properties of undefined (setting './index.tsx')
    at self.webpackHotUpdatewebpack_export_array_config_hotupdate_undefined (style.js:995:39)
    at app.afbfca92b434b6b3dfaf.hot-update.js:10:72
```
I'm not sure if this is a Webpack bug or a WebpackDevServer bug, as I see that the browser has already received the updated WS message.

**If the current behavior is a bug, please provide the steps to reproduce.**
<https://github.com/chenmingzhen/Webpack-HMR-export-array-config-hotUpdate-undefined>
I created a repo to reproduce the problem. The Webpack configuration I exported is an array.
```
module.exports = [
  /** for style */
  {
    entry: [
      path.resolve(__dirname, "style.ts"),
      path.resolve(__dirname, "index.less"),
    ],
    output: {
      filename: "style.js",
      publicPath: "http://localhost:4000/",
    },
    mode: "development",
    module: {
      rules: [
        {
          test: /\.tsx?$/,
          exclude: [/node_modules/],
          use: [
            {
              loader: "esbuild-loader",
              options: {
                loader: "tsx",
                target: "es2015",
              },
            },
          ],
        },
        {
          test: /\.less$/,
          use: [
            {
              loader: MiniCssExtractPlugin.loader,
            },
            {
              loader: "css-loader",
            },
            {
              loader: "less-loader",
            },
          ],
        },
      ],
    },
    plugins: [
      new MiniCssExtractPlugin({
        filename: "style.css",
      }),
    ],
  },

  /** for ts */
  {
    entry: {
      app: path.resolve(__dirname, "index.tsx"),
    },
    output: {
      filename: "app.js",
      publicPath: "http://localhost:4000/",
    },
    mode: "development",
    module: {
      rules: [
        {
          test: /\.tsx?$/,
          exclude: [/node_modules/],
          use: [
            {
              loader: "esbuild-loader",
              options: {
                loader: "tsx",
                target: "es2015",
              },
            },
          ],
        },
      ],
    },
  },
];
```

**What is the expected behavior?**
I expect the browser to update the content as the TS code and CSS change

**Other relevant information:**
webpack version:  5.73.0
Node.js version: 16.15.1
Operating System: Window 10
Additional tools: webpack-dev-server 4.9.2, webpack-cli 4.7.0

**Comment by alexander-akait** [comment]
Please set v, because you have multiple entries on the same page
