### ISSUE TITLE
Variable instead string path into dynamic import

### ISSUE THREAD

**Issue by rustam-gasymov** [webpack/webpack#15999]
Hi, I really hope that you can help me...
I have 5 applications that i connect them using module-federation.
 All of names of libraries i putted to array. Its like 
const arr = ["app/MyButton"]; 
Right now i wont to get from all my libraries all modules in the function, something like this 
 const foo = async (arr: string[]) => {
  for (let i = 0; i < arr.length; i++) {
    const module = await import(arr[i]);
    console.log(module);
  }
};

const arr = ["app/MyButton"];
foo(arr);

but i got all of time error

Critical dependency: the request of a dependency is an expression

I really glad if you can help me solve this problem.

Thanks a lot

**Comment by rustam-gasymov** [comment]
My Webpack config

const HtmlWebpackPlugin = require("html-webpack-plugin");
const ModuleFederationPlugin = require("webpack").container.ModuleFederationPlugin;
const deps = require("./package.json").dependencies;
const path = require("path");

module.exports = (_, { mode }) => {
  console.log(mode);
  return {
    mode: mode ?? "development",
    entry: "./src/index",
    output: {
      filename: "index.js",
      path: path.resolve(__dirname, "dist"),
      libraryTarget: "umd",
      clean: true,
    },
    resolve: {
      extensions: [".ts", ".tsx", ".js"],
    },
    devtool: "source-map",
    devServer: {
      static: {
        directory: path.join(__dirname, "dist"),
      },
      port: 3021,
      open: true,
      hot: true,
    },
    module: {
      rules: [
        {
          test: /\.m?js/,
          resolve: {
            fullySpecified: false,
          },
        },
        {
          test: /\\.js$/,
          loader: "babel-loader",
          exclude: "/node_modules/",
        },
        {
          test: /\.css$/,
          use: [
            "style-loader",
            {
              loader: "css-loader",
              options: {
                importLoaders: 1,
                modules: true,
              },
            },
          ],
          include: /\.module\.css$/,
        },
        {
          test: /\.tsx?$/,
          loader: "babel-loader",
          exclude: /node_modules/,
          options: {
            presets: ["@babel/preset-react", "@babel/preset-typescript"],
          },
        },
        {
          test: /\.css$/,
          use: ["style-loader", "css-loader"],
          exclude: /\.module\.css$/,
        },
        {
          test: /\.(ts|tsx)?$/,
          use: ["ts-loader"],
          exclude: /node_modules/,
        },
        {
          test: /\.(svg|png|jpg|gif)$/i,
          use: [
            {
              loader: "url-loader",
              options: {
                limit: 8192,
              },
            },
          ],
        },
      ],
    },
    plugins: [
      new ModuleFederationPlugin({
        name: "host",
        filename: "remoteEntry.js",
        remotes: {
          app: "app@http://localhost:3022/remoteEntry.js",
        },
        shared: {
          ...deps,
          react: {
            singleton: true,
            requiredVersion: deps.react,
          },
        },
      }),
      new HtmlWebpackPlugin({
        template: "./public/index.html",
        hash: true,
        favicon: "public/favicon.ico",
      }),
    ],
  };
};

**Comment by rustam-gasymov** [comment]
in console of browser i got this error

Error: Cannot find module 'app/MyButton'
 
But if i put regular string i got my module

Thanks

**Comment by vankop** [comment]
webpack can't statically analyze `import(variable)` only string literals like `import("blabla")` or computed templates `import(`./my-file-${process.env.NODE_ENV}.js`)`

**Comment by avikt18** [comment]
Hey @vankop I saw similar error "Critical dep: the request of a dependency is an expression" as I imported some modules using variables:
```javascript
const filePath = path.join(__dirname, file)
const module = require(filePath)
```
I understand the reason for this warning: webpack can't statically analyze and so bundles all possible modules.
To get rid of the warning I tried using template literals:
```javascript
const filePath = path.join(__dirname, file)
const module = require(`${filePath}`)
```
and this made the error go away but I am confused why. Webpack still doesn't know the filePath at build time as it is still dynamic, how does using template literals in place of just variables makes a difference.

**Comment by avikt18** [comment]
@alexander-akait ^^

**Comment by avikt18** [comment]
Also...Can you pls help me with standard way of getting rid of this warning. I can't remove `expr` in require as the I am reading file dynamically through `fs.readDirSync()`. 

> const filePath = path.join(__dirname, file)
const module = require(filePath)

Appreciate your help :sweat_smile: .
PS: I guess ContextReplacementPlugin is the way, but not sure how?

**Comment by avikt18** [comment]
@alexander-akait

**Comment by alexander-akait** [comment]
You can use https://webpack.js.org/api/module-methods/#webpackignore, also please enable it for `require` using https://webpack.js.org/configuration/module/#moduleparserjavascriptcommonjsmagiccomments, because it is disabled by default for perf reasons
