### ISSUE TITLE
ModuleFederationPlugin can not directly get shared module default export in .mjs file

### ISSUE THREAD

**Issue by wxpwxpwxp** [webpack/webpack#16000]
# Bug report

**What is the current behavior?**
when import vue in .mjs file，compiler result didn't use compatGetDefaultExport to get default export
```javascript
// bootstrap.js
import './foo.mjs'
import './foo.js'

// foo.mjs and foo.js
import Vue from 'vue'
import bar from './bar'

console.log('bar', bar)
console.log('vue', Vue)

// webpack config
...
      new ModuleFederationPlugin({
        name: 'core',
        filename: 'remoteEntry.js',
        exposes: {
            ...
        },
        shared: require('./package.json').dependencies,
      }),
...
```
get following wrong result
<img width="628" alt="image" src="https://user-images.githubusercontent.com/51726580/176408453-85ae202a-993d-4ae0-bba8-424eb27e70da.png">

**What is the expected behavior?**
use compatGetDefaultExport when import shared module in .mjs file

**Other relevant information:**
webpack version:  5.70.0
Node.js version: 16.1.0
Operating System: macos
Additional tools:

**Comment by vankop** [comment]
thats expected `.mjs` is es module, so there is no compatability for it..

**Comment by lzxb** [comment]
I have also encountered this issue. If module sharing is cancelled, it is normal

**Comment by lzxb** [comment]
Is there a way to solve this?

**Comment by lzxb** [comment]
I raised this question again
https://github.com/webpack/webpack/issues/17874
