### ISSUE TITLE
Property 'webpackHot' does not exist on type 'ImportMeta'

### ISSUE THREAD

**Issue by matriarx** [webpack/webpack#16015]
# Bug report

**What is the current behavior?**
Running a typescript type check fails with the error `Property 'webpackHot' does not exist on type 'ImportMeta'`.  

**Steps to reproduce (I think)**
In `package.json` I have `"type": "module"`.  
In `webpack.config.js` I have `hot: true`.  
In `tsconfig.json` I have `"module": "nodenext"` and `"moduleResolution": "nodenext"`.  
The place where it breaks is after following the official documentation setup:

```
// @ts-expect-error
if (import.meta.webpackHot) {
  // @ts-expect-error
  import.meta.webpackHot.accept()
}
```

Then running `tsc --emitDeclarationOnly` on the codebase breaks the above `import.meta.webpackHot` and gives the above error.  

**What is the expected behavior?**
I am not sure what is wrong here, but I would expect that webpack should have a type for it.  The documentation shows to use it like above so I'm not sure why typescript says it doesn't exist.  

**Note:**
Webpack still seems to work fine, and the hot reloading actually works just fine, it seems like a false error, purely type related.  However it is breaking my lint-staged type check which is annoying so for now I've let typescript ignore the code using `@ts-expect-error`.  

**Other relevant information:**
webpack version:  5.73
Node.js version: 18
Other tools being used: react-refresh

**Comment by alexander-akait** [comment]
I think you need to use this https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html#-reference-path-

**Comment by vankop** [comment]
https://github.com/vankop/webpack-api-types maybe there is more efficient way to reference dts file
