### ISSUE TITLE
Do we have NextJs @12.X.X version support for this plugin?

### ISSUE THREAD

**Issue by 12dkaskar** [webpack/webpack#16011]
I have started the microapp upgrade to latest next version i.e 12.X.X, please let me know do we cover the support or not,
Issue facing: Remote entry file created by microapp build is not loading the exposed components and due to which we are unable to import the application in shell app.

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

**Comment by 12dkaskar** [comment]
can you provide me the template to put the issue again?? for better
understanding. I highly appreciate your help and quick response.

**Comment by alexander-akait** [comment]
You can use this link https://github.com/webpack/webpack/issues/new?assignees=&labels=&template=Bug_report.md
