### ISSUE TITLE
Is require() wasting memory?

### ISSUE THREAD

**Issue by ronkorving** [webpack/webpack#1602]
We're about to start using webpack on a huge (megabytes of JS) project. On a project of that scale, memory use and waste really starts to matter and I was wondering about Webpack. So I dove into the **webpack_require** function. For reference, here is the code I would like to discuss:

``` js
/******/    function __webpack_require__(moduleId) {
/******/
/******/        // Check if module is in cache
/******/        if(installedModules[moduleId])
/******/            return installedModules[moduleId].exports;
/******/
/******/        // Create a new module (and put it into the cache)
/******/        var module = installedModules[moduleId] = {
/******/            exports: {},
/******/            id: moduleId,
/******/            loaded: false
/******/        };
/******/
/******/        // Execute the module function
/******/        modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
/******/
/******/        // Flag the module as loaded
/******/        module.loaded = true;
/******/
/******/        // Return the exports of the module
/******/        return module.exports;
/******/    }
```

What I notice is that once a module's wrapper function has been executed, we'll have the module object cached (makes sense, for the require call). However we also still have the wrapper function (`modules[moduleId]`) which will never ever get executed again, because of the if-statement at the start of the function. So why are we keeping it around? It seems we could reclaim memory by simply assigning `undefined` to `modules[moduleId]`.

Am I missing something or is this a really easy opportunity to reclaim memory?

**Comment by kpdecker** [comment]
Have you done a retains heap analysis on this to see how much memory this structure actually retains? It seems like there could be some savings by clearing this, but I'm not sure exactly how much since any closures, etc will be referenced by the `installedModules` object.

**Comment by ronkorving** [comment]
Sure, and that's fine. I don't expect the module object and all its references to disappear. But the original function definition should still be taking up space I reckon. The JS engine won't be able to deduce (easily) that the function will never be called again. We'll do some tests, see what we can measure.

**Comment by IngwiePhoenix** [comment]
Yes, the memory will be populated by the functions, and not garbage collected because the object is...

- In active use.
- Part of a parent which is frequently accessed.

Your idea of `undefine`'ing it seems fine with me. However, this should only happen if the function doesn't fail, imho.

You can send a PR to modify the function.

But I would assume you do a memory usage test first. Because these wrappers arent that huge, really. So make sure if it is worth the efford. Thanks. :)

**Comment by ronkorving** [comment]
You're right, they're not big. But I'm working on a game with literally hundreds (we may have reached thousands by now) of required files. You can imagine RAM use is sensitive here :)

We'll try to do a test, and see what comes out of it. Even a 0.1% improvement would be worth it on a project like this given that it's just a one-liner with no (imho) drawbacks.

**Comment by IngwiePhoenix** [comment]
A game compiled by webpack?
… You seriously should let us know of a beta, it’d be nice to link to something like that as a usecase :)

Anyway BTT:

When you have some results, post them here. Then, you can try to remove the function by setting it to NULL or undefined and re-test. See if that changed something and how much.

**Comment by ronkorving** [comment]
I will see if I can announce what this is all about :) What I can say for now, is that it's for tablets, and it's probably the biggest (in terms of content) game to hit the app stores .. pretty much ever.

We'll give it a shot, do some heap dumps, diff them, and see if there's any benefit. Thanks.

**Comment by micky2be** [comment]
So I made some Heap Snapshot of this huge game in Chrome ;)
(Yes, I'm working with @ronkorving)
We have a total of 920 modules.
Here some basic result on startup of the game/app:
![screen shot 2015-11-20 at 15 09 20](https://cloud.githubusercontent.com/assets/728644/11293159/aa0db338-8f9a-11e5-8bfa-2d7a083f5006.png)

Snapshots from 2 to 5 have been made with vanilla webpack.
While Snapshots from 6 to 8 have been made by simply adding a `modules[moduleId] = undefined;` after the function call.
Seems we clearly get about 400KB of RAM freed

Made an other test by going a little bit farther in the game (1-4 vanilla, 5-8 setting undefined).
And again we can see some gain in memory.
![screen shot 2015-11-20 at 15 38 53](https://cloud.githubusercontent.com/assets/728644/11293423/5c75c680-8f9d-11e5-9767-8ae5f3033dcd.png)
The difference might not be huge compare to the total used but for a big game like this one, it can make a huge difference.

**Comment by sokra** [comment]
> However we also still have the wrapper function (modules[moduleId]) which will never ever get executed again

That sadly not true. It can be executed multiple in this cases:

* HMR: You are hot updating a module and this module is in the dispose chain but wasn't updated.
* `require.cache`: The node.js API allows to manually delete modules from the cache. So to be compatible we must offer this.

But you can do the cleanup manually:

``` js
// after bootstraping you app
Object.keys(require.cache).forEach(function(id) {
  // delete __webpack_modules__[id];
  // or
  __webpack_modules__[id] = wasRemoved;
});

function wasRemoved() {
  throw new Error("This module function was removed for memory reasons. You can't require it again.");
}
```
