### ISSUE TITLE
Custom runtime chunk loader (because urls are unknown during build time)

### ISSUE THREAD

**Issue by stupkad** [webpack/webpack#16021]
## Feature request

Load chunks from locations, which are unavailable during build time.

When uploading JavaScript assets to Hubspot CMS, the files are automatically minified, post-processed and pushed to a CDN, for caching reason Hubspot delivers each asset **from a different location**. So I am looking for a solution to load chunks from a location, which is **not known during build time**.

Find more details at the end.

**What is the expected behavior?**

Possibility to inject a custom chunk loader which provided the correct filename without the need of hacking the created JavaScript files.

**What is motivation or use case for adding/changing the behavior?**

During upload to Hubspot, JavaScript files are post processed and served from different locations for caching reasons.

**How should this be implemented in your opinion?**

Unclear.

**Are you willing to work on this yourself?**
yes

## More details

when uploading JavaScript assets to Hubspot CMS, the files are automatically minified, post-processed and pushed to a cdn, for caching reason Hubspot delivers each asset from a different location. So I am looking for a solution to load chunks from a location, which is not known during build time.

**Locally**

 - js/widget.js
 - js/41.widget.js
 - js/393.widget.js

**Remote**

- http://f.hubspotusercontent-eu1.net/hub/xxx/hub_generated/template_assets/50239061735/1656576587321/index.js
- http://f.hubspotusercontent-eu1.net/hub/xxx/hub_generated/template_assets/50238026977/1656576587779/41.widget.js
- http://f.hubspotusercontent-eu1.net/hub/xxx/hub_generated/template_assets/unknown/location/393.widget.js

And here the challenge starts, as 41.widget.js or 393.widget.js cannot be loaded, as they are not within the same url as index.js. Unfortunately, the final urls are not available during build time, the are created during upload to Hubspot.

During the upload to hubspot, some placeholders within the JavaScript assets are replaced (Hubspot Template language HubL). So, if I manage to define the output.publicPath **for each chunk** as ``https://{{get_asset_url('./js/<chunk>.js')}}`` Hubspot could replace this by the correct url. 

I tried to manually patch the created index.js which does the trick, but seems a bit risky for me, unstable and hard to automate.

```
!function () {

    /* much more */

    o.u = function (e) {
        console.log("Load chunk");
        console.log(e);
        var result = "";
        if (e === 41) result = "{{get_asset_url('/theme/js/widgets/41.widgets.js')}}";
        if (e === 393) result = "{{get_asset_url('/theme/js/widgets/393.widgets.js')}}";
        console.log(result);
        return result;

    }, o.p = "https://", 

    /* much more */
}();

```

**Comment by vankop** [comment]
> for caching reason Hubspot delivers each asset from a different location

thats is useless if you using `[hash]` ( or other hash placeholders ) in output.. maybe there is setting for this.. 

> So, if I manage to define the output.publicPath for each chunk as https://{{get_asset_url('./js/<chunk>.js')}} Hubspot could replace this by the correct url.

you can post process assets replacing `chunk.js` to `{{get_asset_url()}}`
