### ISSUE TITLE
Does webpack5 support esbuild？

### ISSUE THREAD

**Issue by qq281113270** [webpack/webpack#16037]
## Feature request

**What is the expected behavior?**

**What is motivation or use case for adding/changing the behavior?**

**How should this be implemented in your opinion?**

**Are you willing to work on this yourself?**
yes

I expect WebPack to compile and start up as fast as Vite in the development environment, using Esbuid

**Comment by vankop** [comment]
there is only loader https://github.com/privatenumber/esbuild-loader
