### ISSUE TITLE
Automatic publicPath selection fails due to additional external script

### ISSUE THREAD

**Issue by yvanham** [webpack/webpack#16041]
# Bug report

**What is the current behavior?**

If the `publicPath` value (under `output`) is not set in the Webpack config, Webpack calls the `AutoPublicPathRuntimeModule` ([link](https://github.com/webpack/webpack/blob/c181294865dca01b28e6e316636fef5f2aad4eb6/lib/runtime/AutoPublicPathRuntimeModule.js)) to find the current path by looking at the last included script file. This works if the last script file is [a] not an inline script and [b] part of the webpack output and therefore the src attribute is a reasonable reference to the intended public path.

If neither of those criteria is matched, e.g. a script added by Google Tag Manager, the `AutoPublicPathRuntimeModule` cannot find the current path, and throws the following error:
`Automatic publicPath is not supported in this browser`

The red rectangle on the screenshot below highlights an example of an external script added to the end of the script list. It is added by Google Tag Manager on Linux devices only and results in the error described above.

<img width="914" alt="Screenshot_webpackissue" src="https://user-images.githubusercontent.com/108366479/178465210-2356bb67-2966-4e6e-b724-70798864c5db.png">

On Windows and macOS, this Google Tag Manager script is not added and the last script is `main.5dd691d8552e0c47.js`. This script is then selected by the `AutoPublicPathRuntimeModule` to find the current path, and works without issues.

**If the current behavior is a bug, please provide the steps to reproduce.**

See above.

**What is the expected behavior?**

While it can be solved by setting the `publicPath` value in the Webpack config file, the `AutoPublicPathRuntimeModule` should not use the last script to find the current path, as this is prone to errors caused by other packages adding additional external scripts. 
If that is not possible, the logged error message (`Automatic publicPath is not supported in this browser`) could be improved, as it is supported in this browser, but obstructed by a script added by a different package.

**Other relevant information:**
webpack version: 5.64.0
Node.js version: v16.11.1
Operating System: Linux (issue), Windows (no issue), MacOS (no issue)
Additional tools: Chrome (V103), Firefox

**Comment by alexander-akait** [comment]
It is fallback for old browsers... Can you provide value of `RuntimeGlobals.global`, but yes, we can improve this

**Comment by vankop** [comment]
hm.. strange in your example for main.js should be `document.currentScript.src`, but yes `else` case could be improved..

**Comment by sokra** [comment]
It should use `import.meta.url`. Maybe you forgot to set the script type to `module` in webpack config, as you are using script tags with `type="module"`?

**Comment by alexander-akait** [comment]
bump
