### ISSUE TITLE
Is it possible for webpack module federation to support multiple versions of a singleton library running?

### ISSUE THREAD

**Issue by sabeekaq** [webpack/webpack#16042]
So currently I have the following architecture:
- one host react app
- 2 microfrontend react apps
- a component library which I have developed

Currently, the only way the component library can work with the current setup is if we declare it as a singleton (I believe this was needed for theming and sharing state). However, for our use case this is not scalable as teams working on different apps may not want to upgrade their version of the component library at the same time as other apps. Therefore, we may need multiple versions of the component library running at the same time.

Is it possible for webpack module federation to support multiple versions of a singleton library running?

**Comment by vankop** [comment]
> Is it possible for webpack module federation to support multiple versions of a singleton library running?

it is not same anymore.. I think no.. maybe you need to change versioning in this case e.g. `my-library-next`, `my-library-beta` instead of version

**Comment by ScriptedAlchemy** [comment]
Put it under another share scope

**Comment by sabeekaq** [comment]
@ScriptedAlchemy  - are you referring to [this](https://webpack.js.org/concepts/module-federation/#dynamic-remote-containers)?

**Comment by ScriptedAlchemy** [comment]
Look up advanced api module federation. I wrote a medium article a few years ago about some of the share options.
