### ISSUE TITLE
Webpack tries to import a chunk that does not exist

### ISSUE THREAD

**Issue by hronro** [webpack/webpack#16040]
# Bug report

**What is the current behavior?**
Webpack is trying to import a chunk that does not exsit.

**If the current behavior is a bug, please provide the steps to reproduce.**

I have prepare a repo for reproducing it:

- Clone https://github.com/hronro/webpack-chunk-issue
- Run `pnpm i && pnpm build`
- Check `dist/main.c1ecce6e.js`. In the bottom of the file, it contains something like this:

```js
import * as __webpack_chunk_0__ from "./style.e9792867.js";
```

However, `style.e9792867.js` does not exsit.

**What is the expected behavior?**
Webpack should not import that unexist file.

**Other relevant information:**
webpack version:  5.73.0
Node.js version: 18.5.0
Operating System: macOS
Additional tools: PNPM

**Comment by alexander-akait** [comment]
Bug, thanks you for the report

**Comment by Sagargajare** [comment]
@alexander-akait 
```
import * as __webpack_chunk_0__ from "./style.e9792867.js";
```

Can we fix it by removing this line of code?

**Comment by alexander-akait** [comment]
We should not generate them, something wrong in graph...

**Comment by sokra** [comment]
Bug in `experiments.outputModule`. It should not add imports for chunks that do not contain JS. Usually it checks for that in many places, but seems like it was missed here. Send a PR

**Comment by Gautam-Arora24** [comment]
Can I work on this issue?

**Comment by Gautam-Arora24** [comment]
Can I work on this issue?

**Comment by snitin315** [comment]
@Gautam-Arora24 yes, feel free.

**Comment by Gautam-Arora24** [comment]
Can anyone help me by giving some leads as to where/how to solve this issue? This is my first time contributing to webpack.

**Comment by AnmolBansalDEV** [comment]
> 

hey, where to find `experiments.outputModule` file?

**Comment by ScriptedAlchemy** [comment]
It’s in the ESM directory. There’s a series of plugins there. You can also see what plugins are applied when by looking at the applyOptions file. It takes the config and translates it to plugins applied to compiler.

**Comment by hronro** [comment]
active

**Comment by hronro** [comment]
I can confirm this issue still exist in the latest version of webpack (v5.75.0).

Why did webpack-bot add an inactive label and then close it without sending me any notification this time? (At least in the last time the webpack-bot add the inactive label with a comment, so I can get a notification)

Should this issue be reopened or should I file a new issue?

cc @alexander-akait @sokra

**Comment by alexander-akait** [comment]
Reopened, we will resetup our bot soon (planned), yeah, it is very annoying
