### ISSUE TITLE
[Webpack Stats] Improve how dynamically imported chunks are determined as "initial"

### ISSUE THREAD

**Issue by hyshka** [webpack/webpack#16055]
## Feature request

Right now when analyzing my compilation stats some async chunks are being marked as "initial" because they are also used in regular imports from within other entry points. Here's an example to illustrate this:
- first entry
  - Dynamic import for "hello.js"
    - "hello.js" then contains a dynamic import for "world.js"
- second entry
  - Regular import for "world.js"

When using the SplitChunksPlugin the result is that the chunk containing "world.js" is marked as an "initial" chunk, even though it is also used as an async chunk. This messes with reporting tools based on the compilation stats because since the "world.js" chunk is marked as "initial" it counts towards the "initial" size of the "first entry" bundle.

I mocked up a small example to reproduce this here: https://github.com/hyshka/webpack-async-chunk-marked-as-initial

**What is the expected behavior?**
I would expect to be able to determine through the compilation stats list of chunks when a chunk is included as "initial" or "async" for each location that it is used.

**What is motivation or use case for adding/changing the behavior?**
The motivation for me purely comes from reporting on the size of entry points and how much code is loaded immediately versus asynchronously.

**How should this be implemented in your opinion?**
I am not very familiar with how the compilation stats are implemented but I think you may be able to do this if you computed the "initial" value for each origin within the chunk. Obviously, this could add a lot of complexity.

**Are you willing to work on this yourself?**
Not at this time.

**Comment by sokra** [comment]
> I would expect to be able to determine through the compilation stats list of chunks when a chunk is included as "initial" or "async" for each location that it is used.

You can look up the `entrypoints` property in the stats for list of chunks per entrypoint. They are "initial" in these entrypoints.

**Comment by hyshka** [comment]
I must have missed the notification for this previously @sokra. So to confirm:

Any modules within the `chunks` or `assets` properties of those entries listed via `entrypoints` are expected to be "initial"?

![image](https://user-images.githubusercontent.com/2090758/197561571-1850c1d9-e1bc-483f-8820-8eaf085a37ab.png)

In that case, these are assumed to be "initial" chunks, while all other children are not "initial":
- "runtime"
- "first"

This is a lot of cross-referencing to do as a consumer. The root of my request here is to make the "initial" property within the list of `chunks` accurate or replace it with a more robust system. We should not need to reference the `chunks` or `assets` properties within each entry point.
