### ISSUE TITLE
Cannot resolve module 'babel' if context is specified

### ISSUE THREAD

**Issue by SoonDead** [webpack/webpack#1606]
I'm getting the following error:

    ERROR in Entry module not found: Error: Cannot resolve module 'babel' in C:\[omitted]\webpack-test\Scripts\

It's because I have specified a context in webpack.config.js:

	var path = require('path');
	var webpack = require('webpack');

	module.exports = {
		context: path.join(__dirname, "Scripts/"),
		entry: {
			index: './index'
		},
		output: {
			path: path.join(__dirname, '/build'),
			filename: '[name].bundle.js',
		},
		module: {
			loaders: [
				{ 
					test: /\.jsx?$/, 
					loader: 'babel'
				}
			]
		},
		resolve: {
			extensions: ['', '.js', '.jsx']
		},
		externals: {
			react: 'React',
		},
		plugins: []
	};

I want webpack to focus on the Scripts directory (where the index.js file is), and specifying the context worked fine before.

How can I use context and loaders hand-by-hand?

Or am I misusing something?

**Comment by bebraw** [comment]
Can you try setting [resolveLoader.modulesDirectories](https://webpack.github.io/docs/configuration.html#resolveloader)? You can also look into the resolve options to see if you can find something that fits your purposes there.

**Comment by IngwiePhoenix** [comment]
WebPack uses the context as the root-most folder. So any node_modules that are above and beyond that, simply arent minded.

Contexts are meant to define the root of your app, regardless of the place of your config. Your entries and such will be relative to the context. If not set, it becomes the current working directory or the folder where the config is, as far as I know.

**Comment by SoonDead** [comment]
Thank you for the tip @bebraw . It is indeed possible to point to the proper module directory this way.

Thank you for the explanation @IngwiePhoenix . Must have been a bug in resolving the node_modules directory in older webpack and I have been using it as a feature.
