### ISSUE TITLE
Global asset generator configuration with filename breaks usage of inline asset rules

### ISSUE THREAD

**Issue by timothympace** [webpack/webpack#16063]
# Bug report

**What is the current behavior?**
Specifying a `filename` value in `config.module.generator.asset` breaks any usage of `asset/inline` module rules. The [docs](https://webpack.js.org/configuration/module/#modulegenerator) do not specify what the behavior should be if `filename` is set at the `asset` level, but once set there it is impossible to override on `asset/inline` or any `module.rules`.

**Steps to reproduce.**
A config with at least the below options:
```
{
  module: {
    generator: {
      filename: 'any_value',
    },
    rules: [
      { test: /some_file_regex/, type: 'asset/inline' }
    ]
  }
}
```

Import a file that matches the test for the rule and observe this error:
```
Module not found: Invalid generator object. Asset Modules Plugin has been initialized using a generator object that does not match the API schema.
 - generator has an unknown property 'filename'. These properties are valid:
   object { dataUrl? }
   -> Generator options for asset/inline modules.
```

**What is the expected behavior?**
Unsure, but nextjs is configured this way and it makes it unclear how to add custom `asset/inline` rules. See [this discussion](https://github.com/vercel/next.js/discussions/36981) for more details.

**Other relevant information:**
webpack version:  5.73.0
Node.js version: 16
Operating System: MacOS Big Sur
Additional tools: next@12.1.6

**Comment by vankop** [comment]
this is expected.. please use
```
module: {
    rules: [
      {
        test: /some_file_regex/,
        type: 'asset/inline',
        generator: {},
      }
    ]
  }
```
`module.generator` options should be used in more general way..

**Comment by timothympace** [comment]
@vankop Ive tried your suggested solution and it doesn’t work. `filename` will always be merged into the generator options if set at the asset level. There is no way, as far as I can tell, to override it.

**Comment by vankop** [comment]
> Are you suggesting to avoid using module.generator in this way?

yes
