### ISSUE TITLE
ModuleFederation cant share vue-demi correctly

### ISSUE THREAD

**Issue by promer94** [webpack/webpack#16060]
# Bug report

**What is the current behavior?**
ModuleFederation cant share vue-demi correctly.

<img width="1302" alt="Screen Shot 2022-07-16 at 20 06 47" src="https://user-images.githubusercontent.com/15878786/179354269-7647bd26-4aba-493c-83b7-215ecc4fd272.png">

**If the current behavior is a bug, please provide the steps to reproduce.**
 
https://github.com/promer94/demi-mf-bug

**What is the expected behavior?**
vue-demi should be able to access vue

**Other relevant information:**
webpack version:  5.73.0
Node.js version:  16.5.0
Operating System:  MacOS 12.4
Vue version 2.6.14

**Comment by promer94** [comment]
Normal build: 
<img width="1235" alt="normal-build" src="https://user-images.githubusercontent.com/15878786/179553149-0486d2fa-2f34-408f-8357-ebb4c3c5fe6c.png">

With mf and shared config
<img width="1687" alt="Screen Shot 2022-07-18 at 23 44 18" src="https://user-images.githubusercontent.com/15878786/179553254-c70e3da1-c9b4-47b3-9b01-44d1212c02ee.png">


It seems like that ```import Vue from 'vue``` should be convered to `vue__WEBPACK_IMPORTED_MODULE_0__['default']` instead of `vue__WEBPACK_IMPORTED_MODULE_0__` when using module federation

**Comment by hangboss1761** [comment]
> Normal build: <img alt="normal-build" width="1235" src="https://user-images.githubusercontent.com/15878786/179553149-0486d2fa-2f34-408f-8357-ebb4c3c5fe6c.png">
> 
> With mf and shared config <img alt="Screen Shot 2022-07-18 at 23 44 18" width="1687" src="https://user-images.githubusercontent.com/15878786/179553254-c70e3da1-c9b4-47b3-9b01-44d1212c02ee.png">
> 
> It seems like that `import Vue from 'vue` should be convered to `vue__WEBPACK_IMPORTED_MODULE_0__['default']` instead of `vue__WEBPACK_IMPORTED_MODULE_0__` when using module federation

@promer94 
May I ask how you solved this problem, I also encountered.

**Comment by Dreamer-Somebody** [comment]
For me,set webpack alias can solve the problem;
```javascript
alias: {
    'vue-demi': 'vue-demi/lib/v2/index.cjs',
}
```
then clear webpack cache```(./node_modules/.cache)```and reboot your project.

**Comment by workkk98** [comment]
mark
