### ISSUE TITLE
splitChunks options: minSize,maxSize does not work to async module

### ISSUE THREAD

**Issue by mr18** [webpack/webpack#16076]
**What is the current behavior?**

the webpack entrypoint is  `a.js`
this webpack  optimization options such as:
```
optimization: {   
    splitChunks: {
      minSize: 1,
      maxSize: 100,
    },
  }
```

**If the current behavior is a bug, please provide the steps to reproduce.**

```
// a.js
class Index {
  render() {
    import("./x").then((mod) => {
      Object.keys(mod).forEach((name) => {
        console.log(mod[name]);
      });
    });
  }
}
```

```
// x.js
export default class x {
  render() {
    console.log("ss");
  }
}
export let a = 10;
```

**What is the expected behavior?**

when I add code to `x.js` more then maxSize, I expect the output files will be split  into multiple files.
but in fact, no matter how large the `x.js` file is, only one file is generated.
so how can I split the async chunk of  `x.js`  into multiple files.

**Other relevant information:**
webpack version:  5.73.0
Node.js version: v16.15.1
Operating System: windows 10

**Comment by vankop** [comment]
`x.js` can't be splitted since it should be executed in sync way. `minSize` and `maxSize` allow webpack to split/union async chunks or initial chunk

**Comment by mr18** [comment]
thank you，
I can split `x.js` into several files and import these files to solve the problem.
