### ISSUE TITLE
Webpack module federation load component with the wrong prefix.

### ISSUE THREAD

**Issue by lifeilu** [webpack/webpack#16087]
# Bug report

**What is the current behavior?**
app A load component from app B which is expose components use module federation case wrong url, the wrong url has the same prefix with app A.

![image](https://user-images.githubusercontent.com/18047854/181022928-87e2f447-0440-479b-89f8-f40db89d275b.png)

![image](https://user-images.githubusercontent.com/18047854/181023066-2f46124e-60a0-45e6-b8cb-6f5cec644f75.png)

![image](https://user-images.githubusercontent.com/18047854/181023466-3f2e7e42-87c5-453b-b26f-a0fc18beba3c.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
1. start the project of app A and app B;
2. import component from appB in appA;
3. the url has the wrong prefix.

**What is the expected behavior?**
the component can be loaded correctly.

**Other relevant information:**
webpack version:  ^5.73.0
Node.js version: v18.4.0
Operating System:  MacOs
Additional tools: Chrome

**Comment by alexander-akait** [comment]
> If the current behavior is a bug, please provide the steps to reproduce.

Please provide reproducible test repo, thank you
