### ISSUE TITLE
Add 'files-changed' hook or add changed files to stats

### ISSUE THREAD

**Issue by lubert** [webpack/webpack#1608]
I'd like to get a list of the changed files while in watch mode.  The intent is to write a 'test-runner' plugin, so that once a test or react component is saved, the corresponding test would be run right away. I was taking a look at the source, and I think the only place this is surfaced is `filesModified` on https://github.com/webpack/webpack/blob/master/lib/Compiler.js#L101. I was thinking that it would be nice to add a new `files-changed` hook or dump the file change info into the stats, but is there a different way that the changed files list is surfaced?

**Comment by micky2be** [comment]
Looks interesting indeed

**Comment by tjwebb** [comment]
+1

**Comment by richardscarrott** [comment]
I would be interested in this for the same reason -- I was hoping it would be possible to surface all the changed files, including those which depend on files that have changed.

**Comment by tehOPEologist** [comment]
would love to see this become a thing as well, as using multiple entry points with multiple outputs in tandem with watch doesn't give the opportunity to show what bundle was partially built.

**Comment by himynameisdave** [comment]
This would still be cool!

**Comment by smashingpat** [comment]
I agree, wished I knew a way to read this from the stats. Reading the `stats.compilation.stats` for the `emitted` files doesn't always work if you changed the CSS only but the entry point .js file also gets emitted although there weren't any changes.

**Comment by imsontosh** [comment]
Yes it a must have feature

**Comment by phcorp** [comment]
Modified files list can be obtained from compilation chunks as described here: https://webpack.github.io/docs/how-to-write-a-plugin.html

**Comment by jescalan** [comment]
Still interested in this. The snippet at the provided link 404s, and the equivalent on the new docs page does not actually work. I just want to know, when watch mode recompiles, which file changed, and its proving to be extremely difficult, unfortunately.

**Comment by isaachinman** [comment]
@jescalan Hey there - did you ever figure this one out? Looks like the current docs have some [`changedFiles`](https://webpack.js.org/contribute/plugin-patterns/#monitoring-the-watch-graph) example that simply doesn't work for me.

**Comment by jescalan** [comment]
@isaachinman yeah I did but it's definitely not as smooth as it could be: https://github.com/hashicorp/prebuild-webpack-plugin/blob/master/index.js#L57

**Comment by isaachinman** [comment]
@jescalan Wow - thanks! Copy-pasted your `getChangedFile` and am up and running.
