### ISSUE TITLE
require statement of a dependency is not correctly resolved by webpack

### ISSUE THREAD

**Issue by marwan38** [webpack/webpack#16089]
# Bug report

**What is the current behavior?**

Bundling @apollo/client has a require statement that is not resolved correctly by webpack. The final output of webpack has references to `require('react-dom/server')` when it hasn't been marked as external. All other dependencies (react) are correctly bundled and resolved to the included code.

This has always worked, for the past 2 years or so, the source code has not changed. Not sure what happened to make this stop resolving it correctly.

**If the current behavior is a bug, please provide the steps to reproduce.**

Repro repo (with steps): https://github.com/marwan38/webpack-5-apollo-repo

**What is the expected behavior?**

`require('react-dom/server')` should be bundled and correctly resolved to the included bundled code.

The resolved output of an older branch:
```
renderFunction: (__webpack_require__(/*! react-dom/server */ "../../node_modules/react-dom/server.js").renderToStaticMarkup)
```

The current output (in repro repo):
```
renderFunction: require("react-dom/server").renderToStaticMarkup
```

**Other relevant information:**
webpack version:  5.72.0
Node.js version: 16.14.2
Operating System: Mac (arm64) and Ubuntu 20.04
Additional tools: N/A

**Comment by vankop** [comment]
`@apollo/client/react/ssr` has package.json with `"type": "module"` this forces webpack to drop cjs detection.. you can force webpack in webpack config:
```js
module: {
        rules: [
            {
                include: path.resolve(__dirname, "node_modules", "@apollo", "client"),
                type: "javascript/auto"
            }
        ]
    }
```

**Comment by marwan38** [comment]
> `@apollo/client/react/ssr` has package.json with `"type": "module"` this forces webpack to drop cjs detection.. you can force webpack in webpack config:
> 
> ```js
> module: {
>         rules: [
>             {
>                 include: path.resolve(__dirname, "node_modules", "@apollo", "client"),
>                 type: "javascript/auto"
>             }
>         ]
>     }
> ```

Thank you for getting back to me and clearing it up! I was wondering, is this exact thing mentioned in the docs or implicitly inferred somewhere? Just for my own knowledge.

**Comment by alexander-akait** [comment]
@marwan38 We have the same behavior as Node.js, but feel free to improve docs
