### ISSUE TITLE
Module federation - Missing reload/invalidate mechanism for remoteEntry.js when some chunk fails to load

### ISSUE THREAD

**Issue by talsi** [webpack/webpack#16081]
# Bug report

**What is the current behavior?**
Simplified description of my scenario:

I have a typical setup of 3 angular apps built with module federation plugin.

host-app (shell-app)
remote-app (mfe1)
remote-app (mfe2)
The shell app loads the remote-apps on demand according to user navigation. Pretty straight forward.

Problem:
When user visits the app, it loads the remoteEntry files of mfe1 and mfe2.
Let's say that user navigates to mfe1 and spend some time working with that app.
In the meanwhile, a new version of mfe2 has been deployed, replacing everything related to the previous version of mfe2.
Now if the user decides to go to app2, it will fail to load, because it tries to load chunks based on a stale remoteEntry.js

Note:
This can happen also if i don't initially load all remoteEntry.js files. It can happen even if remoteEntry.js is loaded dynamically and some chuck has been updated.

**If the current behavior is a bug, please provide the steps to reproduce.**
As described above.

**What is the expected behavior?**
Having a retry mechanism, reloading remoteEntry.js and the relevant chunk it failed to load.

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

**Comment by vankop** [comment]
> it tries to load chunks based on a stale remoteEntry.js

this works same way for SPA. when you open SPA you open application version `N`. if version is changed while you using application, it is application code task to notify user or gracefully update application..

__________

@ScriptedAlchemy could you suggest any solution for this?

**Comment by talsi** [comment]
Hi @vankop ,

> this works same way for SPA.

Yeah, I think i get what you mean. It'll be the same whenever you are using a cache-buster mechanism combined with dynamic loading of assets.

Unfortunately however, we are using a very simple static file server to serve our front-end apps. Detecting if a new version has been deployed will be possible only if we'll check it explicitly (polling). 

So it's not a bug, but still, i think it would be great to have an option to make webpack "revalidate" remoteEntry.js, just once.

**Comment by ScriptedAlchemy** [comment]
```js
      remotes: {
        app1:
          `promise new Promise(mainResolve => {
            var __webpack_error__ = new Error();
            new Promise(function (resolve, reject) {
              if (typeof home !== 'undefined') return resolve();
              __webpack_require__.l(
                'http://localhost:3001/_next/static/chunks/remoteEntry.js?' + Date.now(),
                function (event) {
                  if (typeof home !== 'undefined') return resolve();
                  var errorType = event && (event.type === 'load' ? 'missing' : event.type);
                  var realSrc = event && event.target && event.target.src;
                  __webpack_error__.message =
                    'Loading script failed.\\n(' + errorType + ': ' + realSrc + ')';
                  __webpack_error__.name = 'ScriptExternalLoadError';
                  __webpack_error__.type = errorType;
                  __webpack_error__.request = realSrc;
                  reject(__webpack_error__);
                },
                'home',
              );
            }).then(function () {
              return mainResolve(home);
            });
          })`,
      },
```

**Comment by talsi** [comment]
hi @ScriptedAlchemy,

thank you for the quick response.

i implemented your suggestion above but seems like it doesn't really solves the issue.
in my case, the issue is when it fails to load a chunk, not the remoteEntry.js.

1. browser loads main.js
2. browser loads all remoteEntry.js files
3. user is working with remote-app-A successfully
4. meanwhile, remote-app-B artifacts has been changed due to a deployment
5. user goes to remote-app-B page
6. browser fails to load remote-app-B chucks

![image](https://user-images.githubusercontent.com/5717665/182848041-e984dfbf-d410-4346-94c2-2b733021981c.png)

**Comment by ScriptedAlchemy** [comment]
This is a general problem with any code split application. Not federation specific. 

Keep the previous deploy accessible on your cdn. Like all my assets persist in Akamai for 7 days. Because any user who uses dynamic import. Regardless of Federation, still need to be able to access chunks that are listed on the webpack runtime that was loaded. 

If you don't want to use a cdn to persist then try catch the import and reload the page. No way around it in any application that relies on loading more than 1 file
