### ISSUE TITLE
Bundler doesn't appear to tell worker where to look for bundled file

### ISSUE THREAD

**Issue by finlaymh** [webpack/webpack#16090]
# Bug report

**What is the current behavior?**
I have a worker which imports a local js file using the ```self.importScripts()``` syntax, however when I try to trigger it, I receive a 404 error in the browser console. The 404 due to the worker trying to read the path provided in my code, rather than a bundled version (specifically it looks for http://localhost:8081/maths/decomposition.js). This leads me to believe that when the project is bundled, it does not update the path in the ```self.importScripts()``` function.

The worker code is as follows:
```js
self.onmessage = function ({data: question}) {
    console.debug("decomposer called");
    self.importScripts("../../maths/decomposition.js");
    let decomposer = new Decomposition(
        question.dataset1,
        question.dataset2,
        question.maxOrder
    );
    console.debug("Starting decomp");
    let startTime = Date.now();
    decomposer.overlap();
    decomposer.decompose();
    
    console.debug("That took:", (Date.now() - startTime)/1e3, "seconds"); 
    console.debug("fv1", decomposer.featureVector1Raw);
    console.debug("fv2", decomposer.featureVector2Raw);
    // Decomposition.printMatrix(concat(decomposer.featureVector1, decomposer.featureVector2));
    self.postMessage({decomposer});

};
```
I originally had been trying to import using the ```import { x } from y``` syntax but that gave the error "import declarations may only appear at the top level of a module".
The code calling the worker is:
```js
            let url = new URL("./decompWorker.js", import.meta.url);
            console.log("url", url);
            const worker = new window.Worker(url);
            console.debug("worker made");
            worker.postMessage({ 
                question: {
                    dataset1: this.dataset1,
                    dataset2: this.dataset2,
                    maxOrder: this.maxOrder
                }
            });
            console.debug("message posted");
            worker.onmessage = ({ data: {answer}}) => {
                console.debug(answer);
            };
```
as part of a Vue component. I believe this is related to #15165 , but not identical. One workaround I did try was to just combine the worker and the decomposition.js file, but this resulted in the same import declaration error.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Create a Vue component with a worker
2. Create a worker.js file that tries to import a local js file
3. Run

**What is the expected behavior?**
The worker should load the imported file and use the functionality it provides.
The bundler should tell the import function the updated location of the imported file.

**Other relevant information:**
webpack version:  5.30.0
Node.js version: 
Operating System: Windows 10
Additional tools: Vue.js

**Comment by finlaymh** [comment]
After including ```{ type: 'module' }``` in the declaration of the worker, I instead get an error saying "Loading Worker from “http://localhost:8081/393a5da5702deb8346cc.js” was blocked because of a disallowed MIME type (“text/html”)."

**Comment by finlaymh** [comment]
> After including `{ type: 'module' }` in the declaration of the worker, I instead get an error saying "Loading Worker from “[http://localhost:8081/393a5da5702deb8346cc.js”](http://localhost:8081/393a5da5702deb8346cc.js%E2%80%9D) was blocked because of a disallowed MIME type (“text/html”)."

Also still has a 404 error, but this time it appears to have bundled correctly(?) but the js file doesn't appear to be there

**Comment by alexander-akait** [comment]
```js
let url = new URL("./decompWorker.js", import.meta.url);
console.log("url", url);
const worker = new window.Worker(url);
```

is not statizally analizable, you should always to use `new Worker(new URL(...))`, also avoid `window` prefix (or add them using options)

That is why it is not working, feel free to feedback

**Comment by finlaymh** [comment]
So I did try without ```window``` with the same result. I'm not sure what you mean by statically analyzable (I'm new to js), but does that mean it's impossible to have workers import libraries or other classes? It feels like that really limits their useability.

**Comment by alexander-akait** [comment]
@finlaymh What is statically analizalbe, look at code:
```
const result = await import("./foo.js");
```

`./foo.js` is string, it means we don't need to evaluate other variables or context, just parse file -> get string -> search file and bundle it.

You have:
```js
let url = new URL("./decompWorker.js", import.meta.url);
console.log("url", url);
const worker = new window.Worker(url);
```

`url` is variables and we don't know value (more complex example - you get variable from `window` or another global object, and we don't know it, evaluation can be hard or impossible).

Just change your code to:
```js
const worker = new Worker(new URL("./decompWorker.js", import.meta.url));
```

**Comment by finlaymh** [comment]
That's what I originally had, I only split it up so I could log the url, moved it back and changed my import from
```js
self.importScripts("../../maths/decomposition.js");
```
to
```js
let Decomposition = import("../../maths/decomposition.js")
```
Which gives the same error I mention here https://github.com/webpack/webpack/issues/16090#issuecomment-1198012149

The worker is created fine, it just falls over when it tries to trigger the ```self.onmessage``` function (I don't see "decomposer called" outputted at all)

**Comment by finlaymh** [comment]
I've also just noticed it seems to be trying to request undefined.bundle.js which doesn't seem correct
![image](https://user-images.githubusercontent.com/30186827/181755322-8600538f-e8e1-4842-9012-e4b9b5a2577a.png)

**Comment by alexander-akait** [comment]
We don't have `self.importScripts("../../maths/decomposition.js");`, only ESM

`let Decomposition = import("../../maths/decomposition.js")` is not worker, it is just async chunk

404 due invalid public path, remove `publicPath` from configuration, webpack by default create relative paths and known where you store files

**Comment by finlaymh** [comment]
AFAIK publicPath isn't in my config (assuming you mean webpack.config.js).

Is this line then invalid?
```js
let Decomposition = import("../../maths/decomposition.js")
```

**Comment by alexander-akait** [comment]
Line is valid, something wrong with static of your application (it can be due invalid public path and non standard place of a static directory), if you need help you can create small reproducible test repo (with your problems and what you expected) and I will help show you how to solve it

**Comment by alexander-akait** [comment]
Line is valid, something wrong with static of your application (it can be due invalid public path and non standard place of a static directory), if you need help you can create small reproducible test repo (with your problems and what you expected) and I will help show you how to solve it
