### ISSUE TITLE
Enabling the experimental option experiments.buildHttp will cause HMR to not work.

### ISSUE THREAD

**Issue by LP1994** [webpack/webpack#16091]
# Bug report

**What is the current behavior?**
Enabling the experimental option experiments.buildHttp will cause HMR to not work.

**If the current behavior is a bug, please provide the steps to reproduce.**
1、I've provided a small library of examples to reproduce the problem:
https://github.com/LP1994/experiments_buildHttp_hmr.git
2、After downloading the project, go to the project root directory and execute the commands in the following order:
  1)npm --force install
  2)npm run dev

**What is the expected behavior?**
Enable experimental option experiments.buildHttp. HMR also works fine.

**Other relevant information:**
webpack version:  
webpack 5.74.0

Node.js version: 
node 18.6.0

Operating System: 
Windows 11 Professional Edition 21H2 22000.832

Additional tools:
npm 8.15.1

My demo library:
https://github.com/LP1994/experiments_buildHttp_hmr.git

**Comment by LP1994** [comment]
However, I found that if you manually import 'webpack/hot/dev-server.js' and 'webpack-dev-server/client/index.js' into the entry point, you can use both experiments.buildHttp and HMR.

**Comment by LP1994** [comment]
> However, I found that if you manually import 'webpack/hot/dev-server.js' and 'webpack-dev-server/client/index.js' into the entry point, you can use both experiments.buildHttp and HMR.

However, it should not be done as I mentioned above, because webpack already provides the hot option and the HMR plugin to enable HMR. And this obviously goes against the "out of the box" philosophy of webpack 5.

**Comment by LP1994** [comment]
My demo library:
https://github.com/LP1994/experiments_buildHttp_hmr.git

There are 6 screenshots inside.

The file on the left in the figure is the compiled file with experiments.buildHttp disabled and hot option enabled, which can use HMR normally.

The file on the right in the picture is a compiled file with experiments.buildHttp enabled and the hot option enabled, but HMR cannot be used normally.

Compare the file differences on the left and right sides of the image.You will find that the writing of three files is mainly missing.
![image](https://user-images.githubusercontent.com/12012671/181827882-7cc6446d-e2dc-4a9f-8305-a3cfabbc02da.png)

![image](https://user-images.githubusercontent.com/12012671/181827896-5577394b-f00c-4206-902e-9a941093d8e4.png)

![image](https://user-images.githubusercontent.com/12012671/181827914-05f558cf-741a-4894-ae37-2467c05acd80.png)

Other small differences can be seen in those 6 pictures.

Hopefully the above description will help developers who solve this problem.Again, thanks in advance.

Personally, I like the "experiments.buildHttp" function very much. It reminds me of Deno's "decentralization" and no longer relies on many npm packages.

So, in the future, it (experiments.buildHttp) will be a great feature.

**Comment by vankop** [comment]
there is no url how to handle `jpg` file https://github.com/LP1994/experiments_buildHttp_hmr/blob/master/webpack.config.js#L168 + I'm not sure that this will work with `css-loader`..

**Comment by LP1994** [comment]
> there is no rule how to handle `jpg` file https://github.com/LP1994/experiments_buildHttp_hmr/blob/master/webpack.config.js#L168 + I'm not sure that this will work with `css-loader`..

I'll add it, but it's the same as before.

**Comment by LP1994** [comment]
> there is no rule how to handle `jpg` file https://github.com/LP1994/experiments_buildHttp_hmr/blob/master/webpack.config.js#L168 + I'm not sure that this will work with `css-loader`..

<img width="431" alt="image" src="https://user-images.githubusercontent.com/12012671/182347549-8c8e2699-f97d-435e-86b9-0824c3bebcf0.png">
After adding the image processing, it still does not work, and there is still no ws request.

**Comment by vankop** [comment]
I didn't get it, so hmr doesn't work entirely or only with `buildHttp`

**Comment by LP1994** [comment]
> I didn't get it, so hmr doesn't work entirely or only with `buildHttp` ?

If buildHttp is enabled, HMR will not work.
Conversely, HMR can still be used without enabling buildHttp.

**Comment by vankop** [comment]
@alexander-akait not sure where redirect this.. webpack works fine, looks like hot-middleware not connecting.. ( sounds like bug in options applying )

**Comment by alexander-akait** [comment]
@vankop Bug here https://github.com/webpack/webpack/blob/main/lib/config/defaults.js#L1019, `buildHttp` disable `web` target, so webpack-dev-server is assuming we are not in web enviroment and avoid including clients

**Comment by LP1994** [comment]
> @vankop Bug here https://github.com/webpack/webpack/blob/main/lib/config/defaults.js#L1019, `buildHttp` disable `web` target, so webpack-dev-server is assuming we are not in web enviroment and avoding include client code for hot reloading
@vankop 

According to what you said, I changed "!buildHttp && targetProperties && targetProperties.web" in "https://github.com/webpack/webpack/blob/main/lib/config/defaults.js#L1026" to " targetProperties && targetProperties.web", although HMR is OK, but the browser console reported a new error:
<img width="857" alt="image" src="https://user-images.githubusercontent.com/12012671/184469225-f880dde0-fd3f-45f1-a2f7-31b6a687290d.png">

**Comment by alexander-akait** [comment]
@LP1994 Your should not change it in webpack, change it to `true` https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js#L478, also remove `watchFiles` (from dev server, it is only for resources which are not in bundle, for example - change PHP files)

Because webpack change `compiler.options.externalsPresets` (https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js#L464), we should provide ability to undestand we are in browser env or not...

**Comment by LP1994** [comment]
> @LP1994 Your should not change it in webpack, change it to `true` https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js#L478, also remove `watchFiles` (from dev server, it is only for resources which are not in bundle, for example - change PHP files)
> 
> Because webpack change `compiler.options.externalsPresets` (https://github.com/webpack/webpack-dev-server/blob/master/lib/Server.js#L464), we should provide ability to undestand we are in browser env or not...

According to what you said, I removed the "watchfiles" option, also, I have added configuration to my demo library(https://github.com/LP1994/experiments_buildHttp_hmr/blob/master/webpack.config.js#L164):
![image](https://user-images.githubusercontent.com/12012671/184536312-f48c1369-9c01-4b72-abee-05f176864aeb.png)

although HMR is OK, but the browser console reported a new error:
![image](https://user-images.githubusercontent.com/12012671/184536299-976ea0bf-4992-4f04-9fae-48fd31bd4de3.png)

Is there any other configuration I haven't configured?

**Comment by alexander-akait** [comment]
Not sure, I can't reproduce your problem..., can you provide steps?

**Comment by LP1994** [comment]
> Not sure, I can't reproduce your problem..., can you provide steps?

OK. I have updated my demo library:
https://github.com/LP1994/experiments_buildHttp_hmr.git

After downloading the project, go to the project root directory and execute the commands in the following order:
1)webpack init
2)npm run dev

Other relevant information:
webpack 5.74.0
webpack-dev-server 4.10.0
node 18.7.0
npm 8.17.0

Operating System:
Windows 11 Professional Edition 21H2 22000.832

**Comment by alexander-akait** [comment]
Why you run `webpack init`?

**Comment by LP1994** [comment]
> Why you run `webpack init`?

Just to initialize the dependencies needed in the project for those who don't have the corresponding npm package installed.

**Comment by alexander-akait** [comment]
Also you have:
```
  externalsPresets: {
    web: true,
  },
 ```
 
 you should not do it, workarond to enalbe HMR and buildHttp right now (I remove unnecessary options, but you can return them if you need):
 ```js
 /*
 Project: experiments_buildHttp_hmr
 FileDirPath: webpack.config.js
 Author: 12278
 Email: 1227839175@qq.com
 IDE: WebStorm
 CreateDate: 2022-07-28 19:30:55 Thursday
 */

'use strict';

const path = require( 'path' );

const HtmlWebpackPlugin = require( 'html-webpack-plugin' );

module.exports = {
  context: path.resolve( __dirname, './' ),
  devServer: {
    allowedHosts: 'all',
    bonjour: true,
    client: false,
    compress: true,
    devMiddleware: {
      index: false,
      methods: [
        'GET',
        'HEAD',
        'POST',
        'PUT',
        'DELETE',
        'CONNECT',
        'OPTIONS',
        'TRACE',
        'PATCH',
      ]
    },
    historyApiFallback: true,
    host: '0.0.0.0',
    hot: true,
    liveReload: true,
    port: 8100,
  },
  entry: {
    index: {
      import: [
        'webpack-dev-server/client/index.js?hot=true&live-reload=true&overlay=true',
        './src/index.css',
        './src/index.js',
      ],
    },
  },
  experiments: {
    buildHttp: {
      allowedUris: [
        uri => {
          // experiments.buildHttp.allowedUris.uri--->http://huyaimg.msstatic.com/avatar/1095/ea/540f76f690f002fde18957f5ac920f_180_135.jpg
          console.log( `\n\n\nexperiments.buildHttp.allowedUris.uri--->${ uri }\n\n\n` );

          return true;
        },
      ],
    },
  },
  mode: 'development',
  module: {
    rules: [
      {
        test: /\.css$/i,
        use: [
          'style-loader',
          'css-loader',
        ],
      },
      {
        test: /\.(jng|bmp|dcx|gif|icns|ico|jbig2|jpe|jpeg|jpg|pam|pbm|pcx|pgm|png|pnm|ppm|psd|rgbe|tga|tif|tiff|wbmp|xbm|xpm|svg|svgz|webp|heif|heic)$/i,
        type: 'asset',
        generator: {
          emit: true,
          filename: '[name][ext]',
        },
      },
    ],
  },
  name: 'webpack.config.js',
  plugins: [
    new HtmlWebpackPlugin( {
      inject: 'body',
      scriptLoading: 'defer',
    } ),
  ],
  target: [
    'web',
    'es2022',
  ],
  watch: true,
};
 ```

**Comment by alexander-akait** [comment]
> Just to initialize the dependencies needed in the project for those who don't have the corresponding npm package installed.

Use `npm i` for this, not `webpack init`

**Comment by LP1994** [comment]
@alexander-akait 
thanks. I will try again.

**Comment by LP1994** [comment]
> However, I found that if you manually import 'webpack/hot/dev-server.js' and 'webpack-dev-server/client/index.js' into the entry point, you can use both experiments.buildHttp and HMR.

@alexander-akait 
Perfect indeed. Thanks again.

When I asked this question at the beginning, I also found that "webpack/hot/dev-server.js" and "webpack-dev-server/client/index.js" were manually added at the entry. can use both experiments.buildHttp and HMR.

However, at the time I thought that since webpack already provides the hot option and the HMR plugin to enable HMR, it would be somewhat redundant to manually add both of them.

Just came to ask. Then I'll do it first.

I will write another judgment logic to avoid introducing both of them in the production environment.

**Comment by LP1994** [comment]
@alexander-akait 
Thanks again for your prompt reply.

**Comment by LP1994** [comment]
If anyone else encounters the same problem in the future, you can refer to my demo library.

I have updated my demo library:
https://github.com/LP1994/experiments_buildHttp_hmr.git

Here, thanks again to the maintainers who helped to answer the questions.

Personally, I will close this question first.

**Comment by goleft4E** [comment]
> # Bug report
> **What is the current behavior?** Enabling the experimental option experiments.buildHttp will cause HMR to not work.
> 
> **If the current behavior is a bug, please provide the steps to reproduce.** 1、I've provided a small library of examples to reproduce the problem: https://github.com/LP1994/experiments_buildHttp_hmr.git 2、After downloading the project, go to the project root directory and execute the commands in the following order: 1)webpack init 2)npm run dev
> 
> **What is the expected behavior?** Enable experimental option experiments.buildHttp. HMR also works fine.
> 
> **Other relevant information:** webpack version: webpack 5.74.0
> 
> Node.js version: node 18.6.0
> 
> Operating System: Windows 11 Professional Edition 21H2 22000.832
> 
> Additional tools: npm 8.15.1
> 
> My demo library: https://github.com/LP1994/experiments_buildHttp_hmr.git
