### ISSUE TITLE
regression due #15899

### ISSUE THREAD

**Issue by alexander-akait** [webpack/webpack#16097]
> please create small reproducible repo

Here you go:
https://github.com/jsg2021/webpak-hanging-bundle-example

_Originally posted by @jsg2021 in https://github.com/webpack/webpack/issues/15899#issuecomment-1151461516_

**Comment by alexander-akait** [comment]
bump

**Comment by steverep** [comment]
I'm not sure if this is the same issue yet, but something completely broke @home-assistant frontend from 5.72.1 to 5.73.0.  The app now just completely hangs - no webpack errors or warnings and nothing in the console either.

@jsg2021 you mentioned in the PR that you were able to work around the problem.  How?

**Comment by jsg2021** [comment]
> @jsg2021 you mentioned in the PR that you were able to work around the problem.  How?


In my example repo, it's importing a module that uses a top-level await... i factored that module out of my graph. I can't remember if i got rid of it, or marked it external. It's been a while.

**Comment by steverep** [comment]
Ah okay.  Thanks anyway.

**Comment by steverep** [comment]
@alecmev you had mentioned having a similar issue.  Were you ever able to figure it out?

**Comment by alecmev** [comment]
@steverep Nope, still pinned to `5.72.1`, sorry.

**Comment by jsg2021** [comment]
@steverep That suggests it's a different issue. In my case the file is served...it just never calls back to the module graph to finish bootstrapping. (the top-level await)

In your case...What is serving the files? refusing to serve the file would be a bug in the web service configuration, but the output files's mine type (i don't think) is not handled by webpack ?? 

most systems map mime type by file extension. some file systems can set it as metadata on the file.

**Comment by steverep** [comment]
@jsg2021 sorry my comment wasn't very clear.  The entry chunk actually does begin to load, so that error is caused by the webpack runtime trying to load an async chunk somewhere.

**Comment by steverep** [comment]
Just following up on my previous comments.. The  type `text/plain` error is actually unrelated and caused by an empty module.  I can fix that and the bigger issue remains.

In short, loading the entrypoint either with `import()` or `<script>` appears to be done successfully, but async chunks never start loading.

I've been through the diffs between 5.72.1 and 5.73.0 multiple times and #15899 seems like the only viable one to blame (and also the one I understand the least 😕).

**Comment by steverep** [comment]
I can confirm that conditional TLA is the problem.  When I refactor to remove the conditionals from the `await`, I can upgrade to 5.73.0 or 5.81.0 without any issue.

@ConnorLanglois thanks for figuring this out 👏🏻 

@alexander-akait maybe it's time to remove "possible" from the issue title? 😉

**Comment by alexander-akait** [comment]
Yeah, feel free to send a fix if you want to help, also put this in our board
