### ISSUE TITLE
upgrade to webpack5,  libraryTarget system use externals cause error

### ISSUE THREAD

**Issue by closertb** [webpack/webpack#16098]
# Bug report
when i upgrade my builder to webpack5，it compile right, but it run failed with the error: 
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'render')
```
here is my demo code:
```js
import { useState } from 'react';
import ReactDOM from 'react-dom';
import { Button } from 'antd';
import { StepBackwardOutlined } from '@ant-design/icons'

const App = () => {
  const [cn, setCn] = useState(5);
  return (
    <div>
      <div><Button type="primary">start test</Button></div>
      cn value is {cn}
      <div><StepBackwardOutlined /></div>
    </div>);
};
```

**What is the current behavior?**

I debuged, and found the defference between from v5 and v4:
v4:
![image](https://user-images.githubusercontent.com/22979584/182003784-4459e2f0-a56c-4681-aa44-55c483329fde.png)

v5:
![image](https://user-images.githubusercontent.com/22979584/182003786-177a5eb3-4d1f-494a-923f-85d3c66e1321.png)

webpack5 when set output.libraryTarget to system, the default import is directly from the module（module['default']）, but webpack4 import with __webpack_require__.n(__webpack_require__.n(module))，it will tell wether the module is esmodule。

and I also found, maybe the problem is all the extarnal treat as an esmodule, so when import it ignore whether is an esmodule or not. `but react or react-dom is not an esmodule, which don't have a default export`

![image](https://user-images.githubusercontent.com/22979584/182005742-b4df9100-8228-45ab-a437-2305e633c7d8.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

here is my demo:
git clone https://github.com/closertb/webpack5Demo.git

npm i

npm start

open in chrome, you can find the bug. when checkout the branch to v4. and npm i, npm start, you can see it render ok in the browser

**What is the expected behavior?**

the code runs correct without any change;

don't treat all the external module to `esmodule` when output.libraryTarget is system。

**Other relevant information:**
webpack version:  5.74.0
Node.js version:  14
Operating System:  macos
Additional tools:

**Comment by closertb** [comment]
@vankop @alexander-akait can someone have a look?

**Comment by alexander-akait** [comment]
Change to: `import { render } from 'react-dom';`.

After babel you have ECMA modules code, so webpack assume code in ECMA Modules and you have `default` import, but you use system js (and load UMD from CDN, when remap methods).

Not sure what is the best solution here... 

Also you can change code to:
```
  <script>
    systemSelfRegister('React', { useDefault: true });
    systemSelfRegister('ReactDOM', { useDefault: true });
    systemSelfRegister('antd', { useDefault: true });
    systemSelfRegister('icons', { useDefault: true });
  </script>
```

**Comment by closertb** [comment]
> Change to: `import { render } from 'react-dom';`.
> 
> After babel you have ECMA modules code, so webpack assume code in ECMA Modules and you have `default` import, but you use system js (and load UMD from CDN, when remap methods).
> 
> Not sure what is the best solution here...
> 
> Also you can change code to:
> 
> ```
>   <script>
>     systemSelfRegister('React', { useDefault: true });
>     systemSelfRegister('ReactDOM', { useDefault: true });
>     systemSelfRegister('antd', { useDefault: true });
>     systemSelfRegister('icons', { useDefault: true });
>   </script>
> ```
> 
> Or always remap all methods in defaults...

at first, I try to solve the problem by change the export with the default. but i found I should change every project export which use the builder;

now i write the a plugin, change the output code like: 

```
setters: [
			function(module) {
                                module = _selfDefaultHelper(module);
                                Object.keys(module).forEach(function(key) {
					__WEBPACK_EXTERNAL_MODULE_react__[key] = module[key];
				});
			},
			function(module) {
                                module = _selfDefaultHelper(module);
                                Object.keys(module).forEach(function(key) {
					__WEBPACK_EXTERNAL_MODULE_react_dom__[key] = module[key];
				});
			}]
```

for now, it is work. but i still suggest, we should solve this problem, whatever it will take

**Comment by alexander-akait** [comment]
@closertb How we can solve it? You use default import, but want to load it in system js, it should be solved on application side, we align with esm spec and output of other bundlers
