### ISSUE TITLE
Static `name` attribute of a class behaves differently in development than in production

### ISSUE THREAD

**Issue by sakamossan** [webpack/webpack#16096]
**Do you want to request a *feature* or report a *bug*?**

Looks like a bug to me.

**What is the current behavior?**

Apps built with `--mode=development` and apps built with `--mode=production` behave differently.

**If the current behavior is a bug, please provide the steps to reproduce.**

I confirmed this by applying the following diff right after create-react-app.

```diff
diff --git a/src/App.tsx b/src/App.tsx
index a53698a..b4eb117 100644
--- a/src/App.tsx
+++ b/src/App.tsx
@@ -2,7 +2,12 @@ import React from 'react';
 import logo from './logo.svg';
 import './App.css';
 
+class MyError extends Error {
+  name = "myerror";
+}
+
 function App() {
+  console.log(MyError.name);
   return (
     <div className="App">
       <header className="App-header">

```

```console
$ npx create-react-app myapp --template typescript && cd myapp
$ cat /tmp/_.diff | git apply
$ (npm run build && cd build && python3 -m http.server)
```

This `console.log` output depends on the mode.

#### development 

The app run with `npm start` (in create-react-app), the output is as expected.

> "myerror"

#### production

The app build with `npm run build` will output a single letter of the alphabet.

> "f"

**What is the expected behavior?**

Either behavior is fine, but it would be better if the application behavior is the same even if the mode is different.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

I checked in this environment.

```console
$ sw_vers
ProductName:	macOS
ProductVersion:	12.4
BuildVersion:	21F79
$ node -v
v16.14.2
$ cat ./package.json | jq .dependencies.webpack
"^5.64.4"
$ /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version
Google Chrome 103.0.5060.134
```

**Comment by alexander-akait** [comment]
This is due `terser`, sounds like a bug, please open an issue in terser repo, also please check you have the latest version of `terser` (as workaround you can switch on `swc`, look at terser-webpack-plugin docs)

**Comment by sakamossan** [comment]
I found it was not caused by `terser` but by `tsc`.

```ts
$ cat ./index.ts
class SomeClass { 
    name = "this is name" 
}
console.log(SomeClass.name);
```

```console
$ npx ts-node ./index.ts
SomeClass
```

This is caused by the existance of `Function.name` in JavaScript.

- [Impossible to define static 'length' function on class · Issue #442 · microsoft/TypeScript](https://github.com/microsoft/TypeScript/issues/442)

It is not a webpack issue, so close it. thanks.
