### ISSUE TITLE
This function doesn't export a CJS compatible module.

### ISSUE THREAD

**Issue by marciotc** [webpack/webpack#16092]
https://github.com/webpack/webpack/blob/9fcaa243573005d6fdece9a3f8d89a0e8b399613/lib/ExternalModule.js#L106

Is there a specific reason behind the function having a CJS output mention `import`? 
At least in what I found, this functions is not being used anywhere else but the `_getSourceData` method.

I've tried to use the module-federation with the `commonjs` lib type, and it went under the case of the line [555](https://github.com/webpack/webpack/blob/9fcaa243573005d6fdece9a3f8d89a0e8b399613/lib/ExternalModule.js#L555). Basically disabling the possibility of working it with SSR.

Can I patch it? 
Thanks in advance.

**Comment by vankop** [comment]
try to set `output.module=false`
