### ISSUE TITLE
"Auto" publicPath does not work well with "amd"

### ISSUE THREAD

**Issue by eramitmittal** [webpack/webpack#16108]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
if publicPath is set to "auto" and an amd module loader (like require.js) is used to load the output file, wrong publicPath gets computed. The publicPath that gets computed is the path of the last script loaded

**If the current behavior is a bug, please provide the steps to reproduce.**
Please follow the gist at : https://gist.github.com/eramitmittal/1e41e8b96ca26dc7fefdc0310a5dd178
The gist uses webpack to prepare code-split amd module. 
It has an index,html which loads the webpack output and then a script (loader.js) uses require.js to actually run the code captured in the amd module. It can be seen from console output that the auto computed publicPath refers to location of loader.js instead of the webpack output.

**What is the expected behavior?**
Expected behavior is that publicPath should get auto-computed correctly.

Current behavior happens as document.currentScript.src does not work in case the code is being called in the context of a callback. Amd require, executes the code as callback. Due to this auto-compute logic of publicPath falls back to looking at the src property of the last loaded script. This is highly error-prone.

Instead, src property of the script tag with the required chunk name in it can be looked at.

For instance:
                        var scripts = Array.from(document.getElementsByTagName("script")).filter((script)=> /.*my-bundle.js$/.test(script.src));
                        if(scripts.length) scriptUrl = scripts[scripts.length - 1].src

instead of 
			var scripts = document.getElementsByTagName("script");
                        if(scripts.length) scriptUrl = scripts[scripts.length - 1].src

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
Webpack version: "5.74.0"

**Comment by vankop** [comment]
> Current behavior happens as document.currentScript.src does not work in case the code is being called in the context of a callback. Amd require, executes the code as callback. Due to this auto-compute logic of publicPath falls back to looking at the src property of the last loaded script. This is highly error-prone.

you have specific logic.. please define `publicPath` in config

**Comment by eramitmittal** [comment]
Hi,

This is not my specific logic. This is how AMD has always worked ('require' function invoking the factory method registered as callback using 'define').

Besides defining publicPath in config is not an option if the AMD library bundled using WebPack is to be released on Internet. At the level of library the required publicPath can't be known beforehand as it will depend on the user of the library.

**Comment by eramitmittal** [comment]
Sorry, didn't see it has been marked closed....
Is it right to mark an issue closed without properly understanding the reported issue or at-least waiting for a confirmation from the reporter?

**Comment by vankop** [comment]
> Besides defining publicPath in config is not an option

not sure what you trying to achieve.. `publicPath` should be used only for applications, not for libraries..

> This is not my specific logic. This is how AMD has always worked

In this case there is no way to determine `publicPath` in `"auto"` mode, so you should define it youself..

**Comment by eramitmittal** [comment]
> not sure what you trying to achieve.. publicPath should be used only for applications, not for libraries..
Well if a complex enough code (for e.g. monaco-editor) is bundled as a library using webpack and library target is 'amd', wouldn't the webpack output need public path to load chunks or other assets?
Look at the gist I have included in the bug report. The gist is a working example of a library packaged using webpack requiring publicPath to load a chunk. Gist clearly shows the issue.

>In this case there is no way to determine publicPath in "auto" mode, so you should define it youself...
But, there is a way. Locating for the script tag whose url actually contains the name of the current JS file instead of assuming that the last loaded script is the required one. It is not clear why you think it is not a solution.

**Comment by vankop** [comment]
> It is not clear why you think it is not a solution.

because chunk content hash is based on data inside of this chunk. therefore, you getting circular dependency => in chunk code you want to have something like `this-chunk.hash.js` and same hash in the naming of this chunk...

**Comment by eramitmittal** [comment]
Understood.

Am I right in thinking that the variable '__webpack_require__.p' (i.e. RuntimeGlobals.publicPath) ever ends up in the main module as defined by "output.filename" option in the config file. The chunks actually never define this variable.

If this is true then, AutoPublicPathRuntimeModule will only ever impact the main file (output.filename) which is not hashed!!!
AutoPublicPathRuntimeModule already determines the chunkName which is same as output.fileName. 
Just that it does not use it to determine the src of the script tag loading the main file.

**Comment by eramitmittal** [comment]
Also, the fixed code will be using a variable and not hardcoded name. It can't create a circular dependency.
