### ISSUE TITLE
Output.chunkFilename [name] not working?

### ISSUE THREAD

**Issue by tilleps** [webpack/webpack#1610]
I'm not sure whether I'm correctly understanding **output.chunkFilename**'s `[name]`.  My assumption was that `[name]` would match `[name]` in **output.filename**.
### Using vue-webpack-example: https://github.com/vuejs/vue-webpack-example

``` javascript
module.exports = {
  entry: "./src/main.js",
  output: {
    path: "./build",
    publicPath: "/build/",
    filename: "build.js"
  },
  module: {
    loaders: [
      { test: /\.styl$/, loader: "style!css!stylus" },
      { test: /\.html$/, loader: "html" }
    ]
  }
}
```

Creates the following files:
- build.js
- 1.build.js
- 2.build.js
### If I change option.filename to: `build.[name].js`

``` javascript
module.exports = {
  entry: "./src/main.js",
  output: {
    path: "./build",
    publicPath: "/build/",
    filename: "build.[name].js"
  },
  module: {
    loaders: [
      { test: /\.styl$/, loader: "style!css!stylus" },
      { test: /\.html$/, loader: "html" }
    ]
  }
}
```

Creates the following files:
- build.main.js
- 1.build.1.js
- 2.build.2.js

**Shouldn't it create the following files?:**
- build.main.js
- 1.build.main.js
- 2.build.main.js
### Setting [name] in output.chunkFilename always seems to become the [id]

``` javascript
module.exports = {
  entry: "./src/main.js",
  output: {
    path: "./build",
    publicPath: "/build/",
    chunkFilename: "[name].[id].js",
    filename: "build.[name].js"
  },
  module: {
    loaders: [
      { test: /\.styl$/, loader: "style!css!stylus" },
      { test: /\.html$/, loader: "html" }
    ]
  }
}
```

Creates the following files:
- 1.1.js
- 2.2.js
- build.main.js

**Comment by IngwiePhoenix** [comment]
You are mistaking something.

A chunk can be named.

```javascript
require(["jquery"], function($){
    // Something awesome with jQuery.
}, "jQueryStuff");
```

Then, it would build `bundle.jQueryStuff.js` or `jQueryStuff.bundle.js` instead.

A chunk without a name gets an incrementing ID.

**Comment by tilleps** [comment]
When attempting to name a chunk:
```javascript
require(["jquery"], function($){
    // Something awesome with jQuery.
}, "jQueryStuff");
```
I get the following errors:
```javascript
18:6-13 require function is used in a way in which dependencies cannot be statically extracted
Module not found: Error: a dependency to an entry point is not allowed
```

@IngwiePhoenix Are you saying that `[name]` in **filename** and **chunkFilename** are different?

**Comment by psimoneau22** [comment]
@tilleps The AMD 'require' does not allow you to name a chunk, so you need to use the commonjs option.  ie change your code to this and you will not get the error

require.ensure([], function(require){
    var $ = require("jquery")  // you may need to add .default here 
    // Something awesome with jQuery. $
}, "jQueryStuff" // this will be passed webpack template under [name] and can be used with chunkFileName);

**Comment by andy9775** [comment]
I'm trying to deal with this right now and `[name].[name].bundle.js` gives me `0.chunk_name.bundle.js`

**Comment by mkousta** [comment]
I am new to webpack and I had the same question. I'm trying to migrate a project from require.js to webpack. I expected that `chunkFilename: '[name]-bundle.js'` with my AMD's would result in named chunks but doesn't. @psimoneau22's suggestion worked but that would mean that I have to switch to CJS syntax the entire project.
Is there anyone who can explain if this is intentional and if so why?

**Comment by rafaeleyng** [comment]
Is `chunkFilename` a feature to be used only with code-splitting? Because I'm doing some tests with Webpack (not using code-splitting) and setting any value to `chunkFilename` doesn't make a difference in my build output.

**Comment by anish000kumar** [comment]
same issue, why wouldn't chunckFilename work ?

```javascript
  splitChunks: {
      automaticNameDelimiter: "-",
      cacheGroups: {
        vendor: {
          name: "1_chunk_vendors",
          chunks: "all",
          minChunks: 3,
        }
      }
    },
```
