### ISSUE TITLE
There is a problem i must ask . 

### ISSUE THREAD

**Issue by WenXuanYuan** [webpack/webpack#1611]
I'm a fresher for webpack, when i use babel to handle es6 and jsx code , I write my webpack.config.js like this : 
{test: /\.js$/, loaders: ['react-hot', 'babelr?presets[]=es2015'], exclude: /node_modules/}
I recognized my jsx was not handled by babel and webpack threw an error in the line which contains jsx code . By google I found I should add presets:['react'] , but when i add query[], it threw another error . 
How should I do ? only you can save me .

**Comment by bebraw** [comment]
You are missing the [jsx preset](https://babeljs.io/docs/plugins/syntax-jsx/). JSX isn't supported by default anymore.

**Comment by WenXuanYuan** [comment]
It's said that babel can transform jsx code into js code by setting presets[]=react

**Comment by bebraw** [comment]
@WenXuanYuan Did you get it to work? If so, feel free to close.

**Comment by WenXuanYuan** [comment]
Ok， thank you , I have solved it use another way .
