### ISSUE TITLE
 Duplicate path segment error in dynamic imports in Web Worker (webpack 5)

### ISSUE THREAD

**Issue by kenlyon** [webpack/webpack#16119]
# Bug report

**What is the current behavior?**
When I use webpack to bundle code that includes a Web Worker which contains a dynamic import, the resulting code erroneously duplicates the file path of the chunk that it's trying to load. Instead of requesting something like `foo/bar/abc.[a1b2c3d4].chunk.js`, it requests `foo/bar/foo/bar/abc.[a1b2c3d4].chunk.js`.

**If the current behavior is a bug, please provide the steps to reproduce.**

I encountered this in the context of `create-react-app`, so that's how I reproduce it. I don't know enough about webpack config to be able to distill it down to the absolute minimum. The issue may be with `create-react-app` or `webpack`.

My steps to reproduce are described in this bug report:

[Duplicate path segment error in dynamic imports in Web Worker (react-scripts 5, webpack 5)](https://github.com/facebook/create-react-app/issues/12503)

**What is the expected behavior?**

The path to the dynamically imported chunk should not have the duplicated path in front of the file name.

**Other relevant information:**
webpack version:  5.74.0
Node.js version: 16.15.0
Operating System: Windows 10
Additional tools:

**Comment by alexander-akait** [comment]
This problem in `create-react-app`, sorry, we can't fix it here

**Comment by kenlyon** [comment]
> This problem in `create-react-app`, sorry, we can't fix it here

@alexander-akait Are you saying that because I discovered it in `create-react-app`, or did you determine the cause? If I knew more about which part of the configuration caused it, perhaps I could reproduce it without `create-react-app`. There's a lot of configuration, though, and I don't know enough about it to know which parts contribute to this.

**Comment by alexander-akait** [comment]
@kenlyon Can you create reproducible test repo?

**Comment by kenlyon** [comment]
> @kenlyon Can you create reproducible test repo?

@alexander-akait Yes, I just added one now. It'd be great if you could give it a look for me. It is located here: https://github.com/kenlyon/webpack-duplicate-path-segments. Please follow the instructions in the `README.md` to reproduce it. If you already have `node` and `yarn` installed, it'll be very quick to do.

**Comment by vankop** [comment]
you have public path `./`, you should have `/`, not sure why `create-react-app` set this..

**Comment by kenlyon** [comment]
@vankop The public path of `./` is necessary for our production environment. The application has other path segments before it, like so:
```
https://www.foo.com/bar/fizz/buzz/<myApp>
```
If I used `/`, I think it would need to be accessed directly via the domain name, like so:
```
https://www.foo.com/<myApp>
```
