### ISSUE TITLE
[Module Federation] Exposed container name cannot be 'module'

### ISSUE THREAD

**Issue by malkomich** [webpack/webpack#16118]
# Bug report

**What is the current behavior?**
When the host is application tries to import the remote module, it shows the following error:

```
Uncaught (in promise) TypeError: fn is not a function
while loading <component_name> from webpack/container/reference/module
```

, where "<component_name>" is the name of the exposed component.

---

**If the current behavior is a bug, please provide the steps to reproduce.**
In the remote application, configure the ModuleFederationPlugin name to be 'module':

```
new ModuleFederationPlugin({
      name: 'module',
      filename: 'whatever.js',
      exposes: {
          '<component_name>': '<component_path>',
      },
}),
```

---

**What is the expected behavior?**
The host application, the remote components are successfully loaded.
Otherwise, the error should be consistent with the actual issue, and it should be mentioned in the [documentation](https://webpack.js.org/concepts/module-federation/)

---

**Other relevant information:**
webpack version:  `5.74.0`
Node.js version: `16.16.0`
Operating System: `Windows` (not relevant)
Additional tools: `html-webpack-plugin`, `webpack-dev-server`

**Comment by alexander-akait** [comment]
Please create reproducible test repo

**Comment by ScriptedAlchemy** [comment]
Might be a reserved name since there’s module exports and other module references in the runtime code itself
