### ISSUE TITLE
Cannot read property '__esModule' of undefined

### ISSUE THREAD

**Issue by ajayjaggi97** [webpack/webpack#16114]
# Bug report

**What is the current behavior?**
We have a components library where we have multiple entry points setup for components. Since we had nesting of components as well, we were ending up duplicating the code. 

Hence we used the optimization block inside the config.
```
optimization: {
    splitChunks: {
      chunks: 'all',
      minChunks: 1,
      minSize: 1000,
      maxInitialRequests: Infinity,
      cacheGroups: {
        vendorCss: {
          test: /[\\/]node_modules[\\/](@hotstar\/isomorphic-style-loader|css-loader)[\\/]/,
          name: 'vendor_css_loaders',
          chunks: 'all',
        },
      }
    },
```

But after using this to bundle our components lib, and using this library inside the next.js app we get the error
```
TypeError: Cannot read property '__esModule' of undefined
    at /Users/ajayjaggi/Desktop/Hotstar/web-website/node_modules/@hotstar/web-ui-components-lib/modern/components/Molecule/CustomError/src/index.js:328:34
    at Object.<anonymous> (/Users/ajayjaggi/Desktop/Hotstar/web-website/node_modules/@hotstar/web-ui-components-lib/modern/components/Molecule/CustomError/src/index.js:330:12)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.@hotstar/web-ui-components-lib/modern/components/Molecule/CustomError/src (/Users/ajayjaggi/Desktop/Hotstar/web-website/packages/website/.next/server/pages/_app.js:1273:18)
    at __webpack_require__ (/Users/ajayjaggi/Desktop/Hotstar/web-website/packages/website/.next/server/webpack-runtime.js:33:42)

```

which arises from here at 192 line.
![Screenshot 2022-08-04 at 12 34 19 PM](https://user-images.githubusercontent.com/85304785/182784693-1eb46b9f-6478-47e2-aeaa-b3ec4682eff6.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
 Mentioned above

**What is the expected behavior?**
It should run without giving any errors

**Other relevant information:**
webpack version:  5.40
Node.js version:  14.0.0
Operating System: mac os
next.js version: 12.0.7

**Comment by vankop** [comment]
please create small reproducible repo, thanks

**Comment by derpoho** [comment]
We can confirm this, our splitChunks Setup is like this:

```
splitChunks: {
      chunks: 'all',
      cacheGroups: {
        default: false,
        vendors: false,
        vendor: {
          name(module, chunks, cacheGroupKey) {
            const moduleFileName = module
              .identifier()
              .split('/')
              .reduceRight(item => item)
            const allChunksNames = chunks.map(item => item.name).join('-')
            return `${cacheGroupKey}.${allChunksNames}`
          },
          filename: config.isDev ? 'scripts/[name].js' : 'scripts/[name].js',
          chunks: 'all',
          test: /node_modules/,
          reuseExistingChunk: false,
        },
      },
    },
```

we also have multiple entry points and the chunks should create different vendor chunks for each of the entry points. It works in production mode, but not in development.

Error ist exactly the same as mentioned above.

**Comment by derpoho** [comment]
i have thrown together a small repo to reproduce this issue: https://github.com/derpoho/webpack-esmodule-error

maybe someone can look into this?

**Comment by alexander-akait** [comment]
@derpoho Sorry for delay, you need because you extract vendors, shorty - webpack tried to load amodule, but the module is not  available so you got this error:

```
<script src="http://localhost:5200/scripts/vendor.entryMain-entry01-entry02-entry03.js"></script>
<script src="http://localhost:5200/entryMain.js"></script>
```

You can look at stats output and found it.
