### ISSUE TITLE
discuss for remove unused argument in runtime function template in webpack5

### ISSUE THREAD

**Issue by VisonM** [webpack/webpack#16126]
I'm not sure if this is a bug or expected feature(not compatibility for the wrong module library)，so I marked it as discuss.

## good case
when we not use module spec keyword like `module`,`require` ,`import`,`export` etc in js file
```js
// a.js
console.log(1)
```

in webpack4 ,we will get output like 
```js
function(module, exports){
  console.log(1)
}
```

but webpack5 ( [maybe this commit](https://github.com/webpack/webpack/commit/2525c8b7aa1db995f57f973f54a1c0989334f1a8) ) ,we will get output like
```js
function(/* argument is omit for unused */){
  console.log(1)
}
```
I think this is a useful optimization in most cases。

## bad case
However. suppose you have a library whick name "A"
```js
// my simple lib A
eval("if(typeof module === 'object') module.exports='A'")
```

in webpack4 we will get string `"A"` with  `import A from "A"`
```js
function(module, exports){
  eval("if(typeof module === 'object') module.exports='A'")
}
```
but in webpack5 we get an empty object `{}`. because arcon ast can not detect the correlation of the `module` variable.so that the first module argument will be remove due to unused
```js
function(/* argument is omit for unused */){
  eval("if(typeof module === 'object') module.exports='A'")
}
```

## real case
we use a lib which name watermark-dom(it has a star close to 1k [github](https://github.com/saucxs/watermark-dom) [npm](https://www.npmjs.com/package/watermark-dom)) in webpack5

Below is the minimal reproduce link
https://github.com/VisonM/webpack-reproduce-demo

## Summarize
I have to say the npm package of watermark-dom is terrible, but do we still need to be compatible with such libs？if we should keep unused argument when code exist some keyword like `eval`,`new Function` etc

**Comment by Magin-CC** [comment]
Use the `module` or `exports` api in eval code means that module strong dependence on these two APIs. 

If you don't use webpack bundle that module, it also doesn't work in chrome runtime.

btw, that module change its output mode in 2.3.1, maybe upgrade your dependence version is good solution.

**Comment by Magin-CC** [comment]
btw,  eval code will prevents the identifiers minify of the scope chain.

**Comment by VisonM** [comment]
You are right. but I am more curious about the compatibility considerations of webpack5 for such situations. I also dislike such non-standard libs. (btw v2.3.1 is still in beta 😂, I would choose to release a custom version by self just not use eval）

Can I understand that under the current latest webpack version, or even in future versions, webpack is no longer compatible with such weird libs for minimize runtime output.

I see a lot of optimization strategies for runtime output since webpack5, this is very interesting.
for example:
https://github.com/webpack/webpack/blob/main/lib/javascript/JavascriptModulesPlugin.js#L529-L536

but,I don't see any instructions about this in the relevant weback documentation or migration guide, am I missing something? I think adding documentation may be helpful to those who care it, and I'm willing to contribute pr if needed

**Comment by vankop** [comment]
webpack in general is designed for modules, so webpack doesn't parse `eval()` code. Therefore, this is not possible to support..

**Comment by VisonM** [comment]
@alexander-akait @vankop  Thanks for your patience！🌈  just closed this issue.

I think ` noParse` is  enough for such weird libraries.

I also found [docs about runtime optimization in release blog](https://webpack.js.org/blog/2020-10-10-webpack-5-release/#runtime-modules), but I think it's a little obscure for developers, I may send a docs pr to optimized, make it more understandable, but it's a bit difficult for me, I haven't done anything like that, but I'll try my best.
