### ISSUE TITLE
Types issue with having `(RuleSetRule | "...")` instead of `RuleSetRule`

### ISSUE THREAD

**Issue by oriSomething** [webpack/webpack#16124]
# Bug report

**What is the current behavior?**

Wrong type of `(RuleSetRule | "...")` repeated in a few places in `types.d.ts`

**If the current behavior is a bug, please provide the steps to reproduce.**

Search for `(RuleSetRule | "...")` in `types.d.ts`

**What is the expected behavior?**

Having just `RuleSetRule`

**Other relevant information:**
webpack version:  `master` / `5.74.0`
Node.js version: Doesn't matter
Operating System: Doesn't matter
Additional tools: TypeScript issue

**Comment by alexander-akait** [comment]
Why do you think this is a mistake?

**Comment by oriSomething** [comment]
Because nothing really written about it inside https://webpack.js.org/configuration/module/
And to be honest it's not the most intuitive API (Not saying I have a better solution). After seeing https://github.com/webpack/webpack/blob/9fcaa243573005d6fdece9a3f8d89a0e8b399613/lib/config/defaults.js#L80 I see it's actual a thing.
Thanks anyway 🙏 Sorry for wasting your time
