### ISSUE TITLE
How to solve ./node_modules/handlebars/lib/index.js:15:11-24 - Error: Module not found: Error: Can't resolve 'fs' in module federation config?

### ISSUE THREAD

**Issue by prisia** [webpack/webpack#16128]
./node_modules/handlebars/lib/index.js:15:11-24 - Error: Module not found: Error: Can't resolve 'fs' in '/Users/dino/Documents/puro/node_modules/handlebars/lib

Hello, i got this error when -> npm start my application
can anyone help me with this? 
tried this approach
https://github.com/handlebars-lang/handlebars.js/issues/1174
but it seems not working on my case
Thank you 😄

**Comment by MohammedAshikKP** [comment]
in webpack config add ` resolve: {
        fallback: {
            fs:false
     },
    },`

this might solve the isse
