### ISSUE TITLE
[Module Federation] when mjs consumes a shared module , it will use shared module as commonjs 

### ISSUE THREAD

**Issue by promer94** [webpack/webpack#16131]
# Bug report
**What is the current behavior?**
Currently when you import a shared module in a .mjs file. It will use shared module as commonjs

Source: 
<img width="2239" alt="Screen Shot 2022-08-10 at 14 21 45" src="https://user-images.githubusercontent.com/15878786/183830190-c234032d-0a22-4095-b2db-01c21a867572.png">

Build Result:
<img width="2517" alt="Screen Shot 2022-08-10 at 14 24 08" src="https://user-images.githubusercontent.com/15878786/183830260-69026bfb-5c90-478f-a7ff-a4019d2b8526.png">

**If the current behavior is a bug, please provide the steps to reproduce.**
minimial repro: https://github.com/promer94/mf-mjs-reproduction

**What is the expected behavior?**
shared module should be correctly used based on their meta info

**Other relevant information:**
webpack version:  5.74.0
Node.js version:  v16.16.0
Operating System:  macos 12.3.1 (21E258)

**Comment by huozhi** [comment]
Can you try this to see if this resolves your issue? https://github.com/webpack/webpack/issues/16125#issuecomment-1210447191

**Comment by alexander-akait** [comment]
Duplicate https://github.com/webpack/webpack/issues/16125, feel free to feedback

**Comment by promer94** [comment]
Although this is problem is actully comming from the #16125. 

But this is a more general problem about module federation.  The same issuse still happen when it is vue or any other es module libs

<img width="2321" alt="Screen Shot 2022-08-10 at 20 41 04" src="https://user-images.githubusercontent.com/15878786/183904162-f72af9bb-76e7-4566-9d57-cc5bc5700b43.png">

**Comment by alexander-akait** [comment]
Give me small time to investigate, because I am thinking we should to solve them together (if no I will reopen)

**Comment by promer94** [comment]
I would love to do that. But webpack code is really hard to understand for me. I will try my best.

Currently my finding is that shared modules seems lost their `buildMeta` and `mjs` make `strict` become true ? 
So it fallback to `default-with-named`
https://github.com/webpack/webpack/blob/9fcaa243573005d6fdece9a3f8d89a0e8b399613/lib/Module.js#L428-L487 

https://github.com/webpack/webpack/blob/9fcaa243573005d6fdece9a3f8d89a0e8b399613/lib/RuntimeTemplate.js#L771-L784
