### ISSUE TITLE
Debugging HMR

### ISSUE THREAD

**Issue by phaistonian** [webpack/webpack#1614]
Hello.

Currently working on a rather large project utilizing Dev server.

A while ago HMT stopped working for me and, not matter what I tried, I am unable to figure out what (module?) caused it.

Both the browser log and `noInfo: false` flags did not help much.

Any ideas?

Thank you.

**Comment by karlnp** [comment]
Did you update the technique to the react-transform one, as opposed to react-hot-loader?

**Comment by phaistonian** [comment]
Hey. 

To be honest, I don't really get what you are asking/suggesting 

Plus, I think it has nothing to do with react. 

My guess is this is related to style loaded.

**Comment by sokra** [comment]
The browser console should display various messages regarding HMR. They start with `[HMR]`.

**Comment by phaistonian** [comment]
@sokra Nothing pointing to anything specific came up.

Unfortunately.

**Comment by sokra** [comment]
This may help: https://github.com/gaearon/react-hot-loader/blob/master/docs/Troubleshooting.md
