### ISSUE TITLE
ESM output: single runtime chunk resolved to wrong path when using subpath entrys

### ISSUE THREAD

**Issue by ScriptedAlchemy** [webpack/webpack#16143]
# Bug report

**What is the current behavior?**

If i create entrypoints that include a path in their name, when runtimeChunk: single is set - webpack imports the runtime from the wrong directory. 

**If the current behavior is a bug, please provide the steps to reproduce.**

using this config:

```js
module.exports = {
	output: {
		module: true
	},
	target: ['es2022','async-node'],
	mode: "development",
	entry: {
		'/test/one': './counter',
		'/test/two': './example'
	},

	optimization: {
		usedExports: true,
		concatenateModules: true,
		runtimeChunk: 'single'
	},
	experiments: {
		outputModule: true
	}
};

```

Emits the following
<img width="1250" alt="image" src="https://user-images.githubusercontent.com/25274700/184450870-5cbb416b-b3f5-413b-a233-ed5bbc548fb8.png">

the `runtime.js` file is getting imported from `../../` instead of `../` 

**What is the expected behavior?**

runtime chunk should resolve it correct location

**Other relevant information:**
webpack version:  5.74.0
Node.js version: 16
Operating System: OSX
Additional tools:

**Comment by ScriptedAlchemy** [comment]
@alexander-akait  opened a PR https://github.com/webpack/webpack/pull/16153

**Comment by alexander-akait** [comment]
@sokra We need your advice here

**Comment by sokra** [comment]
That seem to be caused by the leading `/` in the entry name
