### ISSUE TITLE
ignoreWarnings does not work

### ISSUE THREAD

**Issue by lovetingyuan** [webpack/webpack#16142]
# Bug report

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

**Comment by ccccchar** [comment]
i have the same question that it does not work while the docs has the feature.
<img width="1342" alt="image" src="https://github.com/webpack/webpack/assets/37041600/f236c763-b31d-4612-a452-7dc25482de7d">
