### ISSUE TITLE
[ext] template string should include leading dot as webpack does

### ISSUE THREAD

**Issue by 16188722** [webpack/webpack#16140]
Operating System: Windows
Node Version: 16.16.0
NPM Version: 8.11.0
webpack Version: 5.74.0
file-loader Version: 6.2.0

**Expected Behavior**
The [ext] template string would be replaced with the file extension including the leading . (dot) as [webpack itself does](https://webpack.js.org/configuration/output/#template-strings)

**Actual Behavior**
The . (dot) is not included means files like examplesvg instead of example.svg.

**Code**
// webpack.config.js

module : {
  rules:[
      {
        test: /\.(woff|woff2|ttf|eot)$/,
          First method:
         type: "asset/resource",
        generator: {
          filename: "../fonts/[name][ext]",
      },  
       //Second Method:
        use: [
          "cache-loader",
          {
            loader: "file-loader",
            options: {
              name: "../fonts/[name][ext]",
            },
          },
        ],
      },

]
}

Tried both the ways but same result. This issue I am facing after migrating from webpack 4 to 5

**Comment by alexander-akait** [comment]
`file-loader` is deprecated, please don't use it

**Comment by 16188722** [comment]
{
test: /.(woff|woff2|ttf|eot)$/,
First method:
type: "asset/resource",
generator: {
filename: "../fonts/[name][ext]",
},

This one also not working, Getting same error

**Comment by alexander-akait** [comment]
> Extension with leading . (not available for [output.filename](https://webpack.js.org/configuration/output/#outputfilename))

Please create reproducible test repo, I can't rreproduce it

**Comment by 16188722** [comment]
> > Extension with leading . (not available for [output.filename](https://webpack.js.org/configuration/output/#outputfilename))
> 
> Please create reproducible test repo, I can't reproduce it

I can't share the code because it is confidential Could you please help me in getting the compatible plugins and loader. List of loader and plugins that we are using is below:
"compression-webpack-plugin": "10.0.0",
    "concurrently": "5.3.0",
    "copy-webpack-plugin": "5.1.2",
    "css-loader": "6.7.1",
    "execa": "1.0.0",
    "file-loader": "6.2.0",
    "font-awesome-sass": "4.7.0",
    "fork-ts-checker-webpack-plugin": "7.2.13",
    "fs-extra": "8.0.1",
    "glob": "7.1.6",
    "got": "9.6.0",
    "html-loader": "4.1.0",
    "html-webpack-plugin": "5.5.0",
    "intl": "1.2.5",
    "json-loader": "0.5.7", 
    "mini-css-extract-plugin": "2.6.1",
    "node-sass": "7.0.1",
    "null-loader": "4.0.1",
    "optimize-css-assets-webpack-plugin": "6.0.1",
    "raw-loader": "4.0.2",
    "sass-loader": "13.0.2",
    "shx": "0.3.2",
    "style-loader": "3.3.1",
    "sw-precache-webpack-plugin": "1.0.0",
    "thread-loader": "3.0.4",
    "to-string-loader": "1.2.0",
    "ts-loader": "9.3.1",
    "uglifyjs-webpack-plugin": "2.2.0",
    "unzip-stream": "0.3.0",
    "webpack": "5.74.0",
    "webpack-bundle-analyzer": "4.5.0",
    "webpack-cli": "4.10.0",
    "webpack-dev-server": "4.10.0",
    "webpack-merge": "5.8.0",
    "worker-loader": "3.0.8",
    "clean-css": "5.3.1"

**Comment by alexander-akait** [comment]
@16188722 I see you still have `file-loader`...

**Comment by alexander-akait** [comment]
`[ext]` is always include leading dot, please provide which files are not include it
