### ISSUE TITLE
Should contentHash happen before the moduleIds process?

### ISSUE THREAD

**Issue by adamma1024** [webpack/webpack#16158]
## Feature request

I notice our static dependency file's hash will be changed sometimes. After my investigation it's caused by different `moduleIds`.
I take an experiment to prove it. 
First, I saved my project in two version while their `monaco-editor` versions are identity. When I used the `moduleIds: 'named'` and built my  project in prod env. They got the same content hash. 
But when I changed the `modulesIds` to an Id type, e.g. 'deterministic', 'size'. They got different hash values. 
I did not have idea for why it happened since it was hard to read in prod env. But I think it was caused by importing different modules.
However, the dependencies's content are identity. So I expect the content hash will be identity.

**What is the expected behavior?**
Hash content should not be disturbed by `moduleIds`.

**What is motivation or use case for adding/changing the behavior?**
To avoid the content hash being disturbed by moduleIds

**How should this be implemented in your opinion?**
Hash content before moduleIds optimization will avoid this issue.

**Are you willing to work on this yourself?**
no

**Comment by alexander-akait** [comment]
How many chunks you have? Do you extract runtime? If you have dymanic chunks their names are changed so contenthash is different. Maybe you can provide small example?

**Comment by adamma1024** [comment]
> How many chunks you have? Do you extract runtime? If you have dymanic chunks their names are changed so contenthash is different. Maybe you can provide small example?

Thanks for your reply. I found this issue on `monaco-editor` package. It's a third part package, I never change its codes. And I don't know if it used the dymanic chunks within. 
Do you mean the `moduleIds` differences are caused by dymanic chunks? Sure, it could have some additional dymanic chunks in our new codes. And it would cause the `moduleIds` difference indeed.
But I think it should not become a factor to change a file's contenthash which is never been changed, right?
So my question is "Should the contenthash be influenced by moduleIds?" That's the thing I feel weird. 
From my perspective, the calculating `contenthash` process should be earlier than calculating `moduleIds` to ensure the content hash is only influenced by content, not others.

**Comment by adamma1024** [comment]
Btw, what's the rule for calculating the `moduleIds` ? Is there another way to let all of `moduleIds` fixed in the `monaco-editor`. I just know a way is to set `moduleIds: 'named'`. Unfortunately, t will increase the size of the bundle.

**Comment by vankop** [comment]
> I saved my project in two version while their monaco-editor versions are identity.

what does it means? The important thing is when
```js
import("monaco-editor") /* add a non-initial chunk */
```
happens with same configuration it should have same content hash (if editor was not changed)

**Comment by vankop** [comment]
if you have something like 1st webpack config with one `moduleIds` ( result in 1st content hash ) and change webpack config to another `moduleIds` => this will change content hash since module ids alaso a part of content..

**Comment by alexander-akait** [comment]
@adamma1024 Do you have special plugin for `monaco-editor` (if I remember right there is bug there, it was reported multiple times). Also maybe you can create small reprocible test repo?

**Comment by adamma1024** [comment]
> > I saved my project in two version while their monaco-editor versions are identity.
> 
> what does it means? The important thing is when
> 
> ```js
> import("monaco-editor") /* add a non-initial chunk */
> ```
> 
> happens with same configuration it should have same content hash (if editor was not changed)

Yes, indeed, but it will be changed in the following scenario:
Monday, we released our project named `version1`, the release contained a `monaco.1.js`
Tuesday, some guys add new `dynamic`  modules to the project and released the `version2`. Will it still be calculated to `monaco.1.js`? I think it should be. But the fact is as @alexander-akait  said, it probably was `monaco.2.js` since the `module number changed`.
What is its effect of it? It will let our user's browser cache doesn't work. They need to download `monaco.2.js` when we publish our `version2`. The worse thing is it won't just influence one module. I am not sure how many packages will be influenced.
Any time we add new `dynamic` modules it probably happens. That's why I want to report it. It's not friendly and it's weird. Because I never change the `monaco` version. But its content hash probably is changed.

**Comment by adamma1024** [comment]
> @adamma1024 Do you have the special plugin for `monaco-editor` (if I remember right there is bug there, it was reported multiple times). Also maybe you can create small reprocible test repo?

I just used `new MonacoWebpackPlugin({ globalAPI: true })`.
I am not sure that I can provide a reproducible test repo. As we all know, the dependency's module id won't be changed at any time. And I have not found a way to repro it.
But I can promise that I will provide it to you as long as I create a reproducible repo.

**Comment by adamma1024** [comment]
> if you have something like 1st webpack config with one `moduleIds` ( result in 1st content hash ) and change webpack config to another `moduleIds` => this will change content hash since module ids alaso a part of content..

The webpack's config was never changed. But the module id in Monaco has been changed. Just like:
```
//monaco.js
import A from 'A'
```
After compiled:
```
import A from [1] // 1 is module id
```
If we import a new dynamic module it probably be that:
```
import A from [2] // Since the 1 is taken by the dynamic module.
```
So the content hash will be changed when it happens.

**Comment by alexander-akait** [comment]
Sounds like a bug in `MonacoWebpackPlugin` (i faced with it some time ago), is it possible to check this bug without this plugin (because we don't have reproducible test repo we should check all possible places)
