### ISSUE TITLE
why runtime/chunk not processed by babel-loader？

### ISSUE THREAD

**Issue by luckymore** [webpack/webpack#16159]
# Bug report

**What is the current behavior?**
contain es6 syntax `array destruction`
![image](https://user-images.githubusercontent.com/5390013/185108340-7718ae14-8466-4192-ac37-795eba2b6d15.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
```js
// webpack.config.js
{
  test: /\.(js|jsx|ts|tsx)$/,
  exclude: [
    /node_modules[\/
    ]core-js/,
    /node_modules[\/
    ]webpack[\/
    ]buildin/,
  ],
  use: [
    {
          loader: 'babel-loader',
          options: {
              cacheDirectory: true
      }
    },
    {
          loader: 'ts-loader',
          options: {
              transpileOnly: true,
      },
    },
  ],
}
```

```json
// babel.config.json
{
  "sourceType": "unambiguous",
  "presets": [
    [
      "@babel/preset-env",
      {
        "useBuiltIns": "usage",
        "modules": false,
        "loose": true,
        "corejs": {
          "version": "3",
          "proposals": true
        }
      }
    ],
    "@babel/preset-react"
  ]
}
```

**What is the expected behavior?**
It should be like this
![image](https://user-images.githubusercontent.com/5390013/185108565-54107774-3ae3-460d-b303-c9db5b7b6697.png)

**Other relevant information:**
webpack version:  5.74.0
Node.js version: v16.16.0
Operating System: macOS Monterey 12.0.1 (21A559)
Additional tools: -

**Comment by alexander-akait** [comment]
Please set `target: ['es5', 'web']`, otherwise webpack generate es6 runtime output, thank you

**Comment by alexander-akait** [comment]
It means you env support `array destruction` and you can use it

**Comment by alexander-akait** [comment]
Anyway if you want to say webpack don't generate it you can use https://webpack.js.org/configuration/output/#outputenvironment and set `destructuring` to `false`

**Comment by luckymore** [comment]
thx!!! I never notice this, but why webpack don't use babel take it
[babel online](https://babeljs.io/repl#?browsers=android%3E%3D5%2Cios%3E%3D8&build=&builtIns=usage&corejs=3.21&spec=false&loose=true&code_lz=G4QwTgBA2iA0ECMC6EC80lA&debug=false&forceAllTransforms=true&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-3&prettier=false&targets=&version=7.18.12&externalPlugins=&assumptions=%7B%22arrayLikeIsIterable%22%3Atrue%7D
)

**Comment by alexander-akait** [comment]
Yes, webpack doesn't run babel loader on generated runtime, it will be very bad for perf and increase output, so we have these variables (and get them from browserslist for better DX)
