### ISSUE TITLE
LitElement doesn't work when target is 'electron-renderer'

### ISSUE THREAD

**Issue by cantrell** [webpack/webpack#16152]
# Bug report

**What is the current behavior?**
When I set my build target to 'electron-renderer' the app builds fine, but at runtime, I get the error:

```
Uncaught (in promise) TypeError: h.createComment is not a function
    at r (lit-html.js:15:200)
    at A (lit-html.js:15:947)
    at gui.update (lit-element.js:143:76)
    at gui.performUpdate (reactive-element.js:19:5123)
    at gui.scheduleUpdate (reactive-element.js:19:4770)
    at gui._$Ej (reactive-element.js:19:4678)
```

When the target is set to 'web' everything is rendered as expected.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Create an Electron project using Webpack and LitElement.
2. Create a build target for your Electron renderer.
3. Set the target to 'electron-renderer'.
4. Build and run.

**What is the expected behavior?**

The web component should render just as it does with the target set to 'web'.

**Other relevant information:**
webpack version:  5.74.0
Node.js version: 16.16.0
Operating System: macOS 12.4
Additional tools: Webpack, Electron, LitElement, TypeScript

**Comment by vankop** [comment]
please create small reproducible repo

**Comment by cantrell** [comment]
Hi, there. Here's a minimal project that demonstrates the issue:

https://github.com/cantrell/Electron-LitElement-TypeScript-Webpack-Boilerplate

When the renderer target is set to `web`, the page renders fine, and I see this:

<img width="912" alt="web" src="https://user-images.githubusercontent.com/138986/184888630-5c142983-2cd1-4246-89df-32909bcdb00c.png">

However, when the renderer target is set to `electron-renderer`, I get the following client-side error:

<img width="912" alt="electron-render" src="https://user-images.githubusercontent.com/138986/184888670-041f36ae-afd2-4fde-a8be-9c46e2412a16.png">

**Comment by alexander-akait** [comment]
@cantrell Do you solve the problem? Sorry for delay

**Comment by cantrell** [comment]
Hi, there. I didn't solve the problem (I just found a workaround). I'll reopen if someone is willing to take a look. The repo referenced above is once again available. Thanks!

**Comment by alexander-akait** [comment]
@cantrell Can you provide workaround - just for infromation

**Comment by alexander-akait** [comment]
@cantrell Sorry for delay, but I can't reproduce your problem, I used your reproduce example https://github.com/cantrell/Electron-LitElement-TypeScript-Webpack-Boilerplate and set `electron-renderer`, and all works fine :confused:
