### ISSUE TITLE
Paths to relative modules should be expressed as file names

### ISSUE THREAD

**Issue by ColinLaws** [webpack/webpack#16164]
# Bug report

**What is the current behavior?**
Webpack is failing to bundle a file due to how an imported local module ('webpack/lib/Module.js') is imported (in 'webpack/lib/FileSystem.js'). 

See here in `FileSystemInfo.js`. 

https://github.com/webpack/webpack/blob/9fcaa243573005d6fdece9a3f8d89a0e8b399613/lib/FileSystemInfo.js#L9

I am receiving the following error, which indicates that webpack is failing to resolve it's own local module. I suggest we simply change this line to be the name of the local file it's targeting. 

```
ERROR in ../node_modules/webpack/lib/FileSystemInfo.js 9:19-36
Module not found: Error: Can't resolve 'module' in '/home/work/s/REDACTED/node_modules/webpack/lib'
resolve 'module' in '/home/work/s/REDACTED/node_modules/webpack/lib'
  Parsed request is a module
```

**If the current behavior is a bug, please provide the steps to reproduce.**

I am simply running webpack with the following configuration on one JavaScript file, a service-worker.template.js file.
Here is my relatively simple webpack configuration. I have quite a few fallbacks defined to polyfill parts of nodejs which I need while building. I've specified `preferRelative`, which I expect to fix the issue of resolving `import nodeModule = require('module');` to `Module.js`, which is a file sitting directly next to `FileSystemInfo.js`.

```
module.exports = {
    mode: 'production',
    entry: './service-worker.template.ts',
    output: {
        path: path.resolve(__dirname, '.'),
        filename: 'service-worker.js',
    },
    module: {
        rules: [
            {
                test: /\.ts$/,
                loader: 'ts-loader',
            },
        ],
    },
    resolve: {
        preferRelative: true,
        extensions: ['.js', '.ts'],
        fallback: {
            os: require.resolve('os-browserify/browser'),
            stream: require.resolve('stream-browserify'),
            constants: require.resolve('constants-browserify'),
            http: require.resolve('stream-http'),
            https: require.resolve('https-browserify'),
            vm: require.resolve('vm-browserify'),
            crypto: require.resolve('crypto-browserify'),
            process: require.resolve('process'),
            url: require.resolve('url'),
            querystring: require.resolve('querystring-es3'),
            child_process: false,
            fs: false,
            worker_threads: false,
            inspector: false,
            zlib: require.resolve('browserify-zlib'),
        },
    },
    plugins: [
        new webpack.ProvidePlugin({
            process: 'process/browser',
        }),
    ],
};
```

**What is the expected behavior?**

I'm expecting that when setting `resolve.preferRelative`, Webpack would resolve, when saying `require('module')` to attempt to load from the local `Module.js` file. 

**Other relevant information:**
webpack version:  5.74.0
Node.js version: 16.5.1
Operating System: Windows 11 (Build 22000)
Additional tools:

**Comment by vankop** [comment]
this log
```
ERROR in ../node_modules/webpack/lib/FileSystemInfo.js 9:19-36
Module not found: Error: Can't resolve 'module' in '/home/work/s/REDACTED/node_modules/webpack/lib'
resolve 'module' in '/home/work/s/REDACTED/node_modules/webpack/lib'
  Parsed request is a module
```

looks like a webpack resolve error. Do you bundling webpack?

**Comment by ColinLaws** [comment]
Yes, I believe you have helped me fix the issue. I was passing my `webpack.config.js` as the last argument to webpack when running `npx webpack example.js webpack.config.js`.
