### ISSUE TITLE
DLLReferencePlugin not working after update to Webpack v5

### ISSUE THREAD

**Issue by ChiLaXCoding** [webpack/webpack#16168]
# Bug report

**What is the current behavior?**

Webpack build succeeds, but loading the page in the browser throws an error 

> Uncaught ReferenceError: vendor_lib is not defined
    at dll-reference vendor_lib (app.js:29526:18)
    at __webpack_require__ (app.js:34046:33)
    at fn (app.js:34270:21)
    at ../../node_modules/react/index.js (app.js:29374:19)
    at __webpack_require__ (app.js:34046:33)
    at fn (app.js:34270:21)
    at eval (react-hot-loader.development.js?4e17:7:1)
    at ../../node_modules/react-hot-loader/dist/react-hot-loader.development.js (app.js:25893:1)
    at __webpack_require__ (app.js:34046:33)
    at fn (app.js:34270:21)

**If the current behavior is a bug, please provide the steps to reproduce.**

webpack.dll.common.js
`
const plugins = [
  new webpack.DllPlugin({
    path: path.join(moduleDirectory, '..', 'dist', 'js', '[name]-manifest.json'),
    name: '[name]_lib'
  }),
  new webpack.SourceMapDevToolPlugin({
    filename: '[file].map'
  }),
  new webpack.DefinePlugin({
    'process.env': { NODE_ENV: JSON.stringify(process.env.NODE_ENV) }
  })
];

module.exports = {
  target: 'web',
  devtool: 'source-map',
  plugins,
  output: {
    filename: 'js/[name].[hash].dll.js',
    path: path.join(moduleDirectory, '..', 'dist'),
    library: '[name]_lib',
    publicPath: '/'
  }
};`

The webpack.dll.common.js is used in a vendor configuration file and an icons configuration file that loads svgs.

webpack.common.js
`
plugins: [
...,
    new webpack.DllReferencePlugin({
      manifest: require('../dist/js/vendor-manifest.json')
    }),
    new webpack.DllReferencePlugin({
      manifest: require('../dist/js/icons-manifest.json')
    }),
    new AddAssetHtmlPlugin({
      glob: path.resolve(moduleDirectory, '../dist/js/*.dll.js'),
    })
  ]
`

The webpack.common.js is used in a dev and a production configuration file. I am using the dev configuration with a devServer and hotReloadModule to serve the website. I migrated from a v2 to v5 webpack setup, and fixed all webpack build errors using the migration guide from v4 to v5 and lots of googling. 

**What is the expected behavior?**

The website should startup and show the login page. Building the previous v2 webpack setup works and there is no problem with the vendor / icons dlls.

**Other relevant information:**
webpack version:  5.74.0
Node.js version: v18.7.0
Operating System: Windows 10
Additional tools: Visual Studio, Git Bash

**Comment by alexander-akait** [comment]
Please create reproducible test repo, there are a lot of things changed, thank you
