### ISSUE TITLE
Automatically tree shake dynamic imports without needing magic comments

### ISSUE THREAD

**Issue by ChocolateLoverRaj** [webpack/webpack#16171]
## Feature request
This is a feature request after I asked this question: https://github.com/webpack/webpack/discussions/15565. The answer to the question said to use `webpackExports` magic comment to manually tree-shake import. This feature request is for webpack to automatically tree shake common dynamic import patterns that only import some exports.

Example of common patterns:
```js
// Basically simplest way of just importing `meta` export.
(await import('./index.js')).meta
```

```js
// To import multiple exports, but not all of them
const { a, c } = await import('./exportsABC')
```

**What is the expected behavior?**
Code imported with `(await import('./index.js')).meta` should tree shake to only include `meta` export.

**What is motivation or use case for adding/changing the behavior?**
There are two problems with doing `/* webpackExports: ["abc", "default"] */`:
1. Extra line of code, usually have to look up syntax, might be hard to confirm that it is actually working.
2. Renaming the exports with TypeScript will not automatically rename exports in comments, which could cause bugs.

**How should this be implemented in your opinion?**
Change existing behavior to do some simple checks about which exports are being used by the script that does the dynamic import.

**Are you willing to work on this yourself?**
no

**Comment by alexander-akait** [comment]
Thank you for an issue

**Comment by vankop** [comment]
it is hard to analyze all imports..

**Comment by ChocolateLoverRaj** [comment]
@vankop but aren't all dynamic imports already kind of 'analyzed'?

**Comment by alexander-akait** [comment]
bump
