### ISSUE TITLE
dynamic imports always eager loads on library Type: module

### ISSUE THREAD

**Issue by giladv** [webpack/webpack#16181]
# Bug report

**What is the current behavior?**
dynamic imports always eager loads when ``library.type`` is ``module``

**If the current behavior is a bug, please provide the steps to reproduce.**
- minimal webpack setup with output.libraryTarget = 'module'
- entry file:
```
const start = async () => {
    await import(/* webpackMode: "lazy" */'http://somehwere.com/module.js')
}

```

see bundle output: a native import function on the first line although it should be only inside the start function
this is the first bundle line:
```
import * as __WEBPACK_EXTERNAL_MODULE_http_somehwere_com_module_js_2a4e5372__ from "http://somehwere.com/module.js";
```

**What is the expected behavior?**
import() call should be only inside the start function

**Other relevant information:**
webpack version:  latest
Node.js version: 16.10
Operating System: osx
Additional tools: none

**Comment by alexander-akait** [comment]
Hm, you can do it using:
```
externals: {
    "http://somehwere.com/module.js": "import http://somehwere.com/module.js"
},
```

By default webpack hoists them.
