### ISSUE TITLE
Major Build Performance Regressions when using ContainerPlugin in childCompiler

### ISSUE THREAD

**Issue by ScriptedAlchemy** [webpack/webpack#16191]
# Bug report

**What is the current behavior?**
Build should not be 2-3x slower

**If the current behavior is a bug, please provide the steps to reproduce.**
If i create a childCompiler and use `exposes` (ContainerPlugin) a webpack compile (initial compile and dev rebuilds) are twice as slow compared to if i do not expose any modules. 

If I run two separate instances of webpack, the speed rebuild speed is not impacted, if I use exposes on main compile, speed is not impacted. Only when it's in childCompiler

```js
const childCompiler = compilation.createChildCompiler(
        CHILD_PLUGIN_NAME,
        childOutput,
        [
          new ModuleFederationPlugin({
            ...this._options,
            exposes: {
              ...this._options.exposes,
              ...(this._extraOptions.exposePages
                ? exposeNextjsPages(compiler.options.context)
                : {}),
            },
            runtime: false,
            shared: {
              ...externalizedShares,
              ...this._options.shared,
            },
          }),
          new webpack.web.JsonpTemplatePlugin(childOutput),
          new LoaderTargetPlugin('web'),
          new LibraryPlugin('var'),
          new webpack.DefinePlugin({
            'process.env.REMOTES': JSON.stringify(this._options.remotes),
            'process.env.CURRENT_HOST': JSON.stringify(this._options.name),
          }),
          new AddRuntimeRequirementToPromiseExternal(),
        ]
      );
```

**What is the expected behavior?**
Build time should not be degraded so significantly, when using ContainerPlugin on the main compilation, it adds almost no extra time, but when on a childCompiler, it adds 40+ seconds to a large build. 

**Other relevant information:**
webpack version:  latest
Node.js version: 
Operating System: macos
Additional tools: next.js

**Comment by alexander-akait** [comment]
@ScriptedAlchemy Do you have any investigation (just for infromation)

**Comment by ScriptedAlchemy** [comment]
I'm investigating. Hood on issue, might be a problem with child compiler hook being called many times

**Comment by alexander-akait** [comment]
bump
