### ISSUE TITLE
Error: No module factory available for dependency type: Dependency

### ISSUE THREAD

**Issue by scottburch** [webpack/webpack#1622]
I have created a small sandbox here that shows the error with minimal code
https://github.com/scottburch/rewire-error
To reproduce:
npm install
webpack

I have found that webpack 1.12.2 works, 1.12.3 does not.

**Comment by sokra** [comment]
@jhnns This require a change to rewire-webpack. A `Dependency` must correctly have a `constructor` property on it's prototype. The `Class` property is not needed anymore.

**Comment by scottburch** [comment]
Thanks.  Maybe this change should have been a minor version bump rather than a revision bump.

**Comment by sokra** [comment]
yeah, maybe, but now it's too late... ;)

**Comment by scottburch** [comment]
@sokra I just read that you wrote most of the code for webpack-rewire.  Thank you.  People like you, make me look good.

**Comment by jhnns** [comment]
Has been fixed with rewire-webpack `1.0.1`
