### ISSUE TITLE
module federation remoteType

### ISSUE THREAD

**Issue by zhangHongEn** [webpack/webpack#16236]
remoteType: "umd" error

# Bug report

**What is the current behavior?**
error

**If the current behavior is a bug, please provide the steps to reproduce.**
https://stackblitz.com/edit/github-faw5we-nztzyp?file=app1%2Fwebpack.config.js

// app1
ModuleFederationPlugin({
  remoteType: "umd",
  remotes: {
    "app2": "app2@http://localhost:3002/remoteEntry.js"
  }
})
// app2
ModuleFederationPlugin({
  name: "app2",
  library: { type: "umd", name: "app2" }
})

**What is the expected behavior?**

**Other relevant information:**
webpack version:  5.74.0
Node.js version: 16.13.0
Operating System: 
Additional tools:

**Comment by ScriptedAlchemy** [comment]
Remote seems to lose its global scope or not inject container at all when umd

**Comment by alexander-akait** [comment]
UMD is just not supported by module federation, so if you want it feel free to send a PR, sorry, it is not high priority, because developers mostly don't use this format for module federation

**Comment by zhangHongEn** [comment]
> UMD is just not supported by module federation, so if you want it feel free to send a PR, sorry, it is not high priority, because developers mostly don't use this format for module federation

ok, I'm implementing "webpack-4 module consumption". I just want to compare the appearance of "webpack-5" during implementation. In fact, I don't need "module consumption" output as "umd"
