### ISSUE TITLE
Experimental module output drops external import assertions

### ISSUE THREAD

**Issue by laverdet** [webpack/webpack#16238]
# Bug report

**What is the current behavior?**
When using the experimental module output format import assertions are not emitted in the output.

This is related to #2933, @alexander-akait requested I open a new issue.

**If the current behavior is a bug, please provide the steps to reproduce.**
`main.js`
```js
import test from "test" assert { type: "json" };
console.log(test);
```

`package.json`
```json
{
  "name": "test",
  "type": "module",
  "dependencies": {
    "webpack": "^5.74.0",
    "webpack-cli": "^4.10.0"
  }
}
```

`webpack.config.js`
```js
export default {
	entry: "./main.js",
	mode: "development",
	experiments: {
		outputModule: true,
	},
	externals: [
		"test",
	],
}
```

At the top of `dist/main.mjs` we get `import * as __WEBPACK_EXTERNAL_MODULE_test__ from "test";` which will make applications fail under runtimes which expect the assertion (nodejs v18).

**What is the expected behavior?**
The assertion should be preserved in the output.

**Other relevant information:**
webpack version:  5.74.0
Node.js version: 18.9.0

**Comment by alexander-akait** [comment]
bump

**Comment by pablomendezroyo** [comment]
Same issue

**Comment by alexander-akait** [comment]
Marked as low because it is still on `stage: 2` https://github.com/tc39/proposal-import-attributes and changed

**Comment by laverdet** [comment]
@alexander-akait should this be reopened?

**Comment by alexander-akait** [comment]
Fixed by https://github.com/webpack/webpack/pull/18251/
