### ISSUE TITLE
support pass function to loader for better support for prebundle

### ISSUE THREAD

**Issue by hardfist** [webpack/webpack#16237]
## Feature request
support pass loader as a function

**What is the expected behavior?**
support the following usage
```js
// webpack.config.js
module.exports = {
   module: {
     rules: [{use: function inilne_loader(x){ do_some_transform(x)}}]
  }
}
```
**What is motivation or use case for adding/changing the behavior?**
it's hard to prebundle loader with webpack for tools wrapping webpack if loader only supports string,
and prebundle is key to the stability of these tools

**How should this be implemented in your opinion?**
support pass function to loader

**Are you willing to work on this yourself?**
yes

**Comment by alexander-akait** [comment]
Sorry, no, we already diccussed about it and decide don't do it (also it will be bad for cache), anyway you can do it in your configuration.

Just create a file, and do this:
```
module.exports = function loader(options) {
 const options = this.getOptions();
 
 // Logic
};
```

And pass required logic using loader's options.

feel free to feedback

**Comment by hardfist** [comment]
why is it bad for cache？

**Comment by alexander-akait** [comment]
Because we can invalidate cache from your variables

**Comment by hardfist** [comment]
> Because we can invalidate cache from your variables
so webpack use loader path as cache key, if support loader as function then webpack don't know what to use as loader key?

**Comment by alexander-akait** [comment]
No, it is not working in this way, we use content of file (i.e. hash) and timestap

**Comment by hardfist** [comment]
then why loader function is bad for cache is it's not used as cache key?

**Comment by alexander-akait** [comment]
Options are also cached, but when you use own variables we can't track their value
