### ISSUE TITLE
multiple enties, each entry has its own chunkLoadingGlobal

### ISSUE THREAD

**Issue by laomu1988** [webpack/webpack#16233]
## Feature request

**What is the expected behavior?**
 multiple enties, each entry has its own chunkLoadingGlobal，example "webpackChunk_[entryName]"。

**What is motivation or use case for adding/changing the behavior?**
my application is loaded by qiankun, main application and child application has same chunkLoadingGlobal cause scope conflict

**How should this be implemented in your opinion?**
no idea

**Are you willing to work on this yourself?**
yes

**Comment by alexander-akait** [comment]
That is expected, you can use `optimizations.runtimeChunk` to extract this into own chunk https://webpack.js.org/configuration/optimization/#optimizationruntimechunk. You have multi compiler mode please set the `name` option
