### ISSUE TITLE
CommonsChunkPlugin not working with "target: atom"

### ISSUE THREAD

**Issue by llhupp** [webpack/webpack#1623]
When utilizing the `atom` target for building for electron, I get an error about `exports is not defined`. This does not happen when I do not use the `CommonsChunkPlugin` and just use the `main.js` files themselves.

### Example:
webpack config
```
entry: {
	main_app: ['./src/main_app/main.js'],
	splash: ['./src/splash/main.js'],
	shared_dependencies: [
		'react', 'react-router', 'underscore', 'jquery'
	]
},
output: {
	path: path.resolve('build'),
	filename: '[name]/main.js'
},
target: 'atom',
plugins: [
        new webpack.optimize.CommonsChunkPlugin('shared_dependencies', 'shared_dependencies.js', Infinity)
],
```
splash index.html
```
<!doctype html>
<html>
<head>
	<meta charset="utf-8">
</head>
<body>
	<div id="app"></div>
	<script src="shared_dependencies.js"></script>
	<script src="splash/main.js"></script>
</body>
</html>
```
main_app index.html
```
<!doctype html>
<html>
<head>
	<meta charset="utf-8">
</head>
<body>
	<div id="app"></div>
	<script src="shared_dependencies.js"></script>
	<script src="main_app/main.js"></script>
</body>
</html>
```

**Comment by sokra** [comment]
#1467

**Comment by llhupp** [comment]
Can you briefly explain how this commit affects the CommonsChunkPlugin? At a glance, it seems that the "atom", "electron", "electron-main", and "electron-renderer" target should continue to work the same aside from which modules are handled by ExternalsPlugin. My issue seems to be that the CommonsChunkPlugin makes the compiled file unusable in Electron.

**Comment by sokra** [comment]
The CommonsChunkPlugin only works when using JSONP chunk loading. For the atom/electron target node.js `require` is used to load chunks. The PR splits the electron target into two parts, one using node.js chunk loading and the other (electron-renderer) using JSONP chunk loading.

**Comment by llhupp** [comment]
Interesting. Thanks for the quick work!

**Comment by disshishkov** [comment]
on which release will it be included?
