### ISSUE TITLE
Module Federation: Remote Initialization fails with single runtime chunk + multiple entrypoints

### ISSUE THREAD

**Issue by ScriptedAlchemy** [webpack/webpack#16242]
# Bug report

**What is the current behavior?**
If a federated import exists under a specific entrypoint that is not yet loaded, and webpack uses `runtimeChunk: single` - the initialization will fail. 

```
Initialization of sharing external failed: Error: Cannot find module 'checkout@http://localhost:3000/_next/static/ssr/remoteEntry.js'
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Import different remotes under different entrypoints that are not loaded on the page at the same time. 
For example, next.js - pages are entrypoints.

When booting the application, the webpack runtime will attempt to initialize the external, but crashes because the module containing the containerReference module is not yet loaded/on the page.

```js
/******/ 				case "default": {
/******/ 					register("next/dynamic", "12.3.0", function() { return __webpack_require__.e("node_modules_next_dynamic_js").then(function() { return function() { return __webpack_require__(/*! ../node_modules/next/dynamic.js */ "../node_modules/next/dynamic.js"); }; }); });
/******/ 					initExternal("webpack/container/reference/home"); // initialized correctly
/******/ 					initExternal("webpack/container/reference/shop"); // moduleID doesnt exist yet, entrypoint not loaded
/******/ 					initExternal("webpack/container/reference/checkout"); // module id doesnt exist yet, entrypoint not loaded
/******/ 				}
```

**What is the expected behavior?**

ContainerReferences should be hoisted to initial chunk so that webpack runtime can properly initialize all remotes. This should only happen when `runtimeChunk: single` is set

**Other relevant information:**
webpack version:  5.64.4
Node.js version: 16
Operating System: MacOS
Additional tools: Next.js, module-federation/nextjs-mf plugin

**Comment by ScriptedAlchemy** [comment]
@sokra  @alexander-akait  any workaround we can do till this is resolved?

**Comment by alexander-akait** [comment]
Currently no, we need to fix it inside webpack...

**Comment by c-falardeau** [comment]
I currently facing the same issue.

**Comment by ScriptedAlchemy** [comment]
import your remotes in all the entrypoints, i have a loader that requires(app1/noop) and so on in every entrypoint as a workaround.

**Comment by c-falardeau** [comment]
You mean import the generated remote entries js files inside the entries I defined in the wepback (like my index.tsx file for example) ?

**Comment by ScriptedAlchemy** [comment]
Yeah. I use a pitching loader to hoist all my remotes to entries automatically, but it's basically the same as manually doing it.

**Comment by trystan2k** [comment]
> Yeah. I use a pitching loader to hoist all my remotes to entries automatically, but it's basically the same as manually doing it.

Hi @ScriptedAlchemy , do you have this loader available somewhere ? Or an example on how to implement it ?

Thanks

**Comment by arunvishnun** [comment]
Does anyone has a workaround of fix for this issue ?

**Comment by ScriptedAlchemy** [comment]
I am also working on a solution to single runtime chunk via embeded containers: https://github.com/module-federation/universe/pull/1268

https://github.com/module-federation/universe/pull/1268/files#diff-024af026ca8fe4de094d0d858f3153c97857c5849b6b4d34dc562f4e1d1ffd49
