### ISSUE TITLE
How to check in loader what hot update is on?

### ISSUE THREAD

**Issue by elfet** [webpack/webpack#1624]
Hi,

Is it possible to check if hot update is on? `--hot` or via plugin.

Thanks!

**Comment by sokra** [comment]
Check in the loader generated code with `if(module.hot) {`.

**Comment by elfet** [comment]
Yes, i know that. But i do not want to generate extra code at all then it's does not needed. Now i use something like this: `my-loader?hot`

[loader](https://github.com/monkberry/monkberry-loader/blob/master/src/index.js#L15):
```js
 if (query.hot) {
    node.add([
      'if(module.hot) {\n',
      '		module.hot.accept();\n',
      '   var content = require(' + loaderUtils.stringifyRequest(this, '!!' + request) + ');\n',
      '   var update = require(' + loaderUtils.stringifyRequest(this, '!' + path.join(__dirname, 'hot/update.js')) + ');\n',
      '   update(content, "' + name + '");\n',
      '}\n'
    ]);
  }
```

**Comment by sokra** [comment]
webpack replaces `module.hot` with `false` if HMR is switched off, so the code would be removed when minimized.
