### ISSUE TITLE
Webpack build file always return an empty object

### ISSUE THREAD

**Issue by m4nuC** [webpack/webpack#1625]
Webpack entry file
```
module.exports = { foo: 'bar' };
```

Build command
`$ webpack ./src/index.js ./dist/jsfp.js`

An other JS file
```
var jsfp = require('../dist/jsfp');
console.log(jsfp) //<- {}
```

The module always returns empty object.
Any ideas on what could be wrong?

I am using webpack1.12.2 and node 5.0

**Comment by SimenB** [comment]
webpack doesn't export by default, if I'm not mistaken.

https://webpack.github.io/docs/configuration.html#output-library

**Comment by m4nuC** [comment]
Yes that was it. Thanks you!

**Comment by BorisKozo** [comment]
@SimenB Thank you so much! I spent 5 hours trying to understand why it wasn't working and your comment was the solution.

**Comment by joseneto-fixeads** [comment]
Man, you saved my day!!!

**Comment by alex996** [comment]
I was having the same issue in Webpack 4. This worked for me

```javascript
output: {
  /* ... */
  library: 'beta',
  libraryTarget: 'umd',
  globalObject: "typeof self !== 'undefined' ? self : this"
},
```
By the way, the link is dead. See this instead https://webpack.js.org/configuration/output/#output-library
The link is dead.
