### ISSUE TITLE
`webpackAST` returned in `extraInfo` from custom loader appears ignored internally

### ISSUE THREAD

**Issue by jdb8** [webpack/webpack#16256]
# Bug report

I *think* this is some kind of bug, but it's a little confusing since this optimisation seems under-advertised. The [docs](https://webpack.js.org/api/loaders/#thiswebpack:~:text=It%20can%20be%20useful%20to%20pass%20an%20abstract%20syntax%20tree%20(AST)%2C%20like%20ESTree%2C%20as%20the%20fourth%20argument%20(meta)%20to%20speed%20up%20the%20build%20time%20if%20you%20want%20to%20share%20common%20ASTs%20between%20loaders.) do mention:

>It can be useful to pass an abstract syntax tree (AST), like [ESTree](https://github.com/estree/estree), as the fourth argument (meta) to speed up the build time if you want to share common ASTs between loaders.

but this omits the specific variable name of `webpackAST` (it implies the fourth argument should just be the AST itself), so I'm basing this report on the source code and checked-in testcases instead.

If I'm doing something wrong here, please let me know!

**What is the current behavior?**

When defining a custom loader which returns an `extraInfo` object containing an acorn `webpackAST` property, webpack appears to ignore the supplied ast.

**If the current behavior is a bug, please provide the steps to reproduce.**

* Create a custom loader which looks like the ast-loader test case: https://github.com/webpack/webpack/blob/9fcaa243573005d6fdece9a3f8d89a0e8b399613/test/cases/parsing/precreated-ast/ast-loader.js#L27
* Add a console.log to `NormalModule.js` here to log the value of `this._ast` and `extraInfo`: https://github.com/webpack/webpack/blob/293e677b355da0d5bc4ddfc97d2afec114912711/lib/NormalModule.js#L794-L799
* Notice that the logs show `extraInfo` as `null` always:

```
{ extraInfo: null, ast: null }
```

According to a log earlier on, at [this spot](https://github.com/webpack/webpack/blob/293e677b355da0d5bc4ddfc97d2afec114912711/lib/NormalModule.js#L768), `result` always appears to be a single-item array containing only the code, despite the loader using `this.callback(null, code, map, { webpackAST });`.

**What is the expected behavior?**

Webpack and `NormalModule` should use the supplied `extraInfo` + `webpackAST` to avoid re-parsing files.

**Other relevant information:**
webpack version:  `5.73.0`
Node.js version: `16.13.2`
Operating System: `Ubuntu 18.04.5 LTS`
Additional tools: `n/a`

**Comment by alexander-akait** [comment]
Strange, we have a test for this case https://github.com/webpack/webpack/blob/main/test/cases/parsing/precreated-ast/ast-loader.js and test passed, can you provide link on the loader or example how you use it?

**Comment by jdb8** [comment]
@alexander-akait yeah, that's why I'm surprised this doesn't work - I basically copied that test case.

Here's a simplified version of my loader:

```js
const { urlToRequest } = require('loader-utils');

module.exports = function myTransformLoader(source) {
    const filename = urlToRequest(this.resourcePath);

    const { code, map, webpackAST } = myCustomTransformFn({ source, filename });

    this.callback(null, code, JSON.parse(map), {
        webpackAST,
    });
};
```

**Comment by jdb8** [comment]
To simplify even further, even if I replace my loader with:

```js
module.exports = function myTransformLoader(source) {
    this.callback(null, source, null, {
        webpackAST: 'some_incorrect_value',
    });
};
```

I still see `{ extraInfo: null, ast: null }` inside `NormalModule` (from here: https://github.com/webpack/webpack/blob/293e677b355da0d5bc4ddfc97d2afec114912711/lib/NormalModule.js#L794-L799).

I wondered if maybe I was just logging in the wrong place, but `NormalModule` seems like the only location where `webpackAST` is accessed in the source code.

**Comment by jdb8** [comment]
Actually I may have spoken too soon: I'm trying to simplify things down and may have found _another_ loader which is swallowing up the AST. I'm guessing the issue in my setup might be that I have a secondary AST-unaware loader, which needs to pass through the value of `webpackAST`?

As suspected, likely an issue with my setup. I'll edit this comment if/when I find out the root cause here.

**Comment by alexander-akait** [comment]
@jdb8 Yeah, another loader can do another things, so can you provide example if you configuration with this loader, I will look

**Comment by alexander-akait** [comment]
And do you another loaders before you? (They can change JS, so we need to invalidate AST)

**Comment by jdb8** [comment]
@alexander-akait I think that was the issue: my loader above had another custom loader in front of it that was not passing in or returning the `meta` argument:

```js
function anotherLoader(source) {
    ...
    return modifiedSource;
}
```

Removing that loader, or updating it to pass through the `map` and `meta` arguments resolved the issue (I'm now seeing the console.log in `NormalModule` log what I expect:

```js
function anotherLoader(source, map, meta) {
    ...
    this.callback(null, modifiedSource, modifiedMap, modifiedMeta);
}
```

I'm curious though, are there any examples in the wild of `webpackAST` being used for this kind of performance optimisation? I'm working on a caching layer which can pre-crunch transpiled sources, and the plan was to also pre-generate `acorn` ASTs compatible with webpack to skip its internal parsing work.

I haven't benchmarked things properly yet, but so far I'm not seeing _that_ much of a speedup. I'm wondering if the lack of advertising for this optimisation means that it might not be worth aiming for?

If it _is_ worth doing, would you be open to a PR updating some of the documentation around this? I think adding a warning that all loaders in the chain must support `meta` might help someone else avoid making the mistake I did. Would also look to more explicitly document the shape of the `meta` arg beyond what's currently listed in [the current docs](https://webpack.js.org/api/loaders/#thiswebpack:~:text=It%20can%20be%20useful%20to%20pass%20an%20abstract%20syntax%20tree%20(AST)%2C%20like%20ESTree%2C%20as%20the%20fourth%20argument%20(meta)%20to%20speed%20up%20the%20build%20time%20if%20you%20want%20to%20share%20common%20ASTs%20between%20loaders.).

I'll close this issue since there doesn't seem to be a bug here, though - thanks for taking a look!

**Comment by alexander-akait** [comment]
@jdb8 

> If it is worth doing, would you be open to a PR updating some of the documentation around this?

PR welcome

Anyway, there is some trick(pseudo code, just idea):

```js
const otherLoader = require('other-loader');
const { urlToRequest } = require('loader-utils');

module.exports = function myTransformLoader(..args) {
    const filename = urlToRequest(this.resourcePath);

    const result = otherLoader.call(this, options);

    const { code, map, webpackAST } = myCustomTransformFn({ source, filename });
  

    this.callback(null, code, JSON.parse(map), {
        webpackAST,
    });
};
```

So you can run any loader inside your loader and do another fancy things
