### ISSUE TITLE
Improve docs

### ISSUE THREAD

**Issue by shlomiassaf** [webpack/webpack#1627]
This is a proposal to improve documentation in the code.

Currently the documentation addresses "users" and not developers, this is great for spreading the word but it leaves an unmapped gap for contributors wanting to help.

Docs should be implemented in code comments.

We need several steps done:
* Decide on the documentation system
* Build documentation process for auto generated docs
* Write background about core objects (Chunk, Module, Plugin, Template, Dependency, etc), especially how they interact with each other in the flow
* Prioritize files/objects for documentation
* Start documenting file by file.

Since webpack is well built and each file represents a type it should be easy to do it gradually.

One thing to think of is how to document the plugin system...

**Comment by sokra** [comment]
:+1:

**Comment by pksjce** [comment]
This issue was moved to webpack/webpack.io#100

**Comment by pksjce** [comment]
This issue was moved to webpack/webpack.io#129
