### ISSUE TITLE
Include information about ALL chunk groups in stats

### ISSUE THREAD

**Issue by smikula** [webpack/webpack#16287]
## Feature request

Include information about _all_ chunk groups in stats.  Currently `stats.toJson` provides details about _named_ chunk groups, but there is no way (as far as I can tell) to know what the other chunk groups are.

**What is the expected behavior?**

Stats contains enough information to know all the chunk groups that exist (named and otherwise) and which chunks are in each).

**What is motivation or use case for adding/changing the behavior?**

This would be helpful information for bundle analysis, for understanding things like duplicated code and how bundles change between builds.

**How should this be implemented in your opinion?**

This could be implemented with a new top-level `chunkGroups` property on the stats object, containing all the data about the chunk groups.

Alternately, a simple solution that would meet my needs would be for each chunk to list the chunk groups it is a part of (e.g. by the chunk group ids).

**Are you willing to work on this yourself?**

Yes, given some guidance towards the preferred solution.

**Comment by alexander-akait** [comment]
We have this option https://webpack.js.org/configuration/stats/#statschunkgroups...

**Comment by thatsmydoing** [comment]
That option is unfortunately only for `namedChunkGroups` whereas this was asking for all chunk groups.

One workaround for this issue is by accessing `stats.compilation` via the webpack API. It's not very well documented though so it's definitely not ideal.
