### ISSUE TITLE
fetch api does not parse response headers properly

### ISSUE THREAD

**Issue by eslym** [webpack/webpack#16293]
# Bug report

**What is the current behavior?**
The fetch api sometimes (but actually most of the time) are getting empty or weird headers
```js
{ req: "/assets/css/app.css?id=300e29a2f3c29cee824a18f8faad7ec9", headers: { } }
{ req: "/_debugbar/assets/stylesheets?v=1657531602&theme=auto", headers: { } }
{ req: "/_debugbar/assets/javascript?v=1657531602", headers: { } }
{ req: "/assets/js/app.js?id=c8789ab28c9fcdd81120fe41670de297", headers: { "1o00": "1A0 1o00" } }
{ req: "/favicon.ico", headers: { host: "localhost", date: "Sun, 25 Sep 2022 20:35:29 GMT", connection: "close", "content-type": "image/vnd.microsoft.icon", "content-length": "0" } }
{ req: "/api/graphql", headers: { } }
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Here is the simple reverse proxy i trying to make with bun
```ts
Bun.serve({
    port: 8080,
    async fetch(req: Request){
        let url = new URL(req.url);
        let newReq = req.clone();
        newReq.headers.set('X-Forwarded-Host', req.headers.get("host")); // hostname from req.url is not accurate
        newReq.headers.set('X-Forwarded-Proto', url.protocol.replace(':', ''));
        let res = await fetch("http://127.0.0.1:8000" + url.pathname + url.search, newReq);
        console.log({req: url.pathname + url.search, headers: res.headers.toJSON()});
        return res;
    }
});
```
most of the response will became otect-stream when going through this reverse proxy

**What is the expected behavior?**

the response should be getting correct headers

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: Linux 4.4.0-19041-Microsoft #1237-Microsoft Sat Sep 11 14:32:00 PST 2021 x86_64 x86_64 x86_64 GNU/Linux
Additional tools:

**Comment by alexander-akait** [comment]
We are not bun, sorry

**Comment by eslym** [comment]
sorry, i posted it wrongly
