### ISSUE TITLE
Update terser-webpack-plugin to avoid terser vulnerability

### ISSUE THREAD

**Issue by santinozaracho** [webpack/webpack#16306]
Update [terser-webpack-plugin](https://www.npmjs.com/package/terser-webpack-plugin) to avoid terser vulnerability:

- Filename: terser:5.13.1 | Reference: 1081698 | CVSS Score: 7.0 | Category: | The package terser before 4.8.1, from 5.0.0 and before 5.14.2 are vulnerable to Regular Expression Denial of Service (ReDoS) due to insecure usage of regular expressions.

This can be solved in the last [terser-webpack-plugin](https://www.npmjs.com/package/terser-webpack-plugin) because is in terser@5.15.0

**Comment by imki123** [comment]
@alexander-akait I have a same issue. `webpack@^5.74.0` have dependencies on `terser-webpack-plugin@^5.1.3`.
`terser-webpack-plugin@^5.1.3` have dependencies on `terser@^5.7.2`.
`terser@^5.7.2(5.10.0)` has a terser vulnerability issue. Plase update dependency on `terser-webpack-plugin`.
![스크린샷 2022-10-25 오후 4 15 23](https://user-images.githubusercontent.com/43270441/197708797-d098ddb4-fbf5-4c3e-b949-ed3e668c4d72.png)

**Comment by alexander-akait** [comment]
The latest `terser` version is https://github.com/terser/terser/blob/master/package.json#L7, so run `rm -rf package-lock.json node_modules && npm i`

**Comment by imki123** [comment]
@alexander-akait 
Oh, thank you. It works fine. It looks like the yarn.lock file had an older version cached.
