### ISSUE TITLE
Quieting printGeneratedCodeForStack() from outputting entire (large) files to console?

### ISSUE THREAD

**Issue by JasonKleban** [webpack/webpack#16300]
https://github.com/webpack/webpack/blob/18c3590b28fcaaa84b63f18968b09602e4a7e259/lib/javascript/JavascriptModulesPlugin.js#L57-L65

This function seems to be dumping entire large files to console output, flooding the console and making errors difficult to identify.  Is there an option to quiet it down somewhere in the call chain?

**Comment by alexander-akait** [comment]
Because it is an error we print all possible infromation, you can't disable it, just fix your errors

**Comment by JasonKleban** [comment]
This results in a wall of transformed css so large that it exhausts the console buffer such that the actual error is rolled off.  Also, due to performance issues with console logging in vscode, for example, it adds 25 seconds to the execution time printing out all that garbage.

Something as simple as this allows me to diagnose the issues:

```
const lines = code.split("\n").slice(0,4).map(l => l.substr(0, 80));
```

**Comment by alexander-akait** [comment]
Ok, let's reopen this, feel free to send a PR, but we need an option for this

**Comment by alexander-akait** [comment]
Fixed in the latest verison, now we have https://webpack.js.org/configuration/stats/#statserrorsspace
