### ISSUE TITLE
when production model and optimization.sideEffects:true，should ignore package.json sideEffects

### ISSUE THREAD

**Issue by galaxy-s10** [webpack/webpack#16316]
## Feature request
When optimization.sideEffects is set to true, the code will not be analyzed for side effects during production mode construction，
The sideEffects field in package.json will still be used
Whether sideEffects in package.json should be ignored when optimization.sideEffects is true and in production mode

**What is the expected behavior?**
Whether sideEffects in package.json should be ignored when optimization.sideEffects is true and in production mode,
but when production model and optimization.sideEffects:true，Still use package.json's sideEffects

**What is motivation or use case for adding/changing the behavior?**
https://github.com/galaxy-s10/issue-demo/blob/master/demo1/webpack.config.js

**How should this be implemented in your opinion?**

**Are you willing to work on this yourself?**
emm

**Comment by alexander-akait** [comment]
Please be patient we already have dicussion, if it will be consider as bug - we open PR or issue, no need to duplicate

**Comment by alexander-akait** [comment]
`sideEffects` mostly is used for dependecies, no need to setup it on appliction level

**Comment by galaxy-s10** [comment]
> 



> 主要`sideEffects`用于依赖项，无需在应用程序级别设置它

Well, I try to configure the dependency
