### ISSUE TITLE
external field of config with module federation plugin

### ISSUE THREAD

**Issue by rustam-cloud** [webpack/webpack#16319]
hi, i am using module federation to build a big application, i am using dynamic remotes with the function 

/*
(async () => {
return async () => {
    await _webpack_init_sharing_('default');
    const container = await window[scope as keyof typeof window];
    if (!container) return null;
    await container.init(_webpack_share_scopes_.default);
    const factory = await window[scope as keyof typeof window].get(module);
    const Module = await factory();

    return Module;
  };
})();
*/

i have a lot of remote applications with the same package.json 

/*
"dependencies": {
    "@apollo/client": "^3.6.2",
    "@emotion/react": "^11.9.3",
    "@emotion/styled": "^11.9.3",
    "@mui/material": "^5.8.4",
    "@reduxjs/toolkit": "^1.8.2",
    "cesium": "1.96.0",
    "i18next": "^21.8.14",
    "lodash": "^4.17.21",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-i18next": "^11.18.3",
    "react-redux": "^8.0.2",
    "resium": "^1.15.0"
  },
*/

i want to add to my webpack production config field 

/*
externals: {
    "cesium": "cesium",
    "i18next": "i18next",
    "lodash": "lodash",
    "react": "react",
    "resium": "resium"
}
*/

because I dont need remote application in standalone mode, just that it will work in my host application

But when a add this field module federation fail to get container in this line 

/*
const factory = await window[scope as keyof typeof window].get(module);
*/

How can i use externals in webpack production config with module federation, that i can exclude some libraries because all 
of the libraries are already in my host application and i want to deccrease my bundle

Thanks in advance for your help

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
