### ISSUE TITLE
build optimization problem  in prod mode after project migration from NX 13 (Angular 13) to NX 14 (Angular 14)

### ISSUE THREAD

**Issue by eugenephilipov7** [webpack/webpack#16311]
# Bug report

We have problem with build optimization in prod mode after project migration from NX 13 (Angular 13) to NX 14 (Angular 14).
In NX 13 we did not have issues.
While running nx run my-mf:serve, we don't have any problem.
Running nx run my-mf:serve:production, we have error.
The same error with nx run my-mf:build --skip-nx-cache.

ERROR NullInjectorError: R3InjectorError[yu -> yu -> undefined -> undefined -> undefined]: 
  NullInjectorError: No provider for undefined!
    at au.get (537.167380f1e67f7b44.js:1:44933)
    at pu.get (537.167380f1e67f7b44.js:1:47603)
    at pu.get (537.167380f1e67f7b44.js:1:47603)
    at pu.get (537.167380f1e67f7b44.js:1:47603)
    at qm (537.167380f1e67f7b44.js:1:34022)
    at K (537.167380f1e67f7b44.js:1:34120)
    at Di (537.167380f1e67f7b44.js:1:34552)
    at Object.r [as factory] (537.167380f1e67f7b44.js:1:50241)
    at pu.hydrate (537.167380f1e67f7b44.js:1:48980)
    at pu.get (537.167380f1e67f7b44.js:1:47556) 

If change production.optimization to false in project.json, there is no error in nx run my-mf:serve:production or nx run my-mf:build.

How to reproduce:
git clone https://github.com/eugenephilipov7/migration_problem
npm i
nx run my-mf:serve:production

Expected: no difference while development (nx run my-mf:serve) and build (nx run my-mf:build or nx run my-mf:serve:production).

**Other relevant information:**
webpack version:  5.74
Node.js version: 16.17.1
Operating System: Windows Linux
Additional tools: NX,
    "@angular-architects/module-federation": "14.3.10",
    "@angular-architects/module-federation-tools": "14.3.10",

**Comment by alexander-akait** [comment]
Please open an issue in `angular` repo, thank you, but it sound like you have commonjs module, not it is ESM, check it firstly
