### ISSUE TITLE
Cannot use typescript references in webpack.config.ts without first building reference

### ISSUE THREAD

**Issue by aboe026** [webpack/webpack#16324]
# Bug report

**What is the current behavior?**
Cannot use typescript references in webpack.config.ts without first building references.

**If the current behavior is a bug, please provide the steps to reproduce.**
https://github.com/aboe026/webpack-typescript-references

**What is the expected behavior?**
There should be a way to configure webpack to automatically build typescript references (basically do a `tsc --build` before parsing `webpack.config.ts`)

**Other relevant information:**
webpack version:  5.74.0
Node.js version: 16.13.2
Operating System: Windows 11 Pro 10.0.22621
Additional tools:

**Comment by alexander-akait** [comment]
Not related to webpack, you should build `@webpack-typescript-references/env` firstly, if you want to use it late, webpack is not `orchestrator` and don't know which dependecies should be build fisrtly

**Comment by aboe026** [comment]
I understand that webpack is not an orchestrator, but one of the main uses of Typescript References (and the `--build` flag) is to be able to build dependent projects implicitly, without needing to manually build all dependent projects in the reference tree. I think it would be very intuitive and useful if webpack incorporated support for that aspect of Typescript for it to claim full Typescript support. In essence, it would not be webpack doing the orchestration, it would just be webpack respecting typescripts abilities to do the orchestration for it.

**Comment by alexander-akait** [comment]
I don't see how we can implement this, we don't know your graph and don't know what depends on what

**Comment by aboe026** [comment]
Typescript abstracts it, you don't need to know the graph, all webpack would need to do is run a `tsc --build` before ingesting the `webpack.config.ts`, the `tsc --build` command would automatically build the graph of the workspace so all/any dependent projects referenced in the `webpack.config.ts` would be properly built.

**Comment by alexander-akait** [comment]
Sorry, not it doesn't work as you write, you can have big monorepo and don't use all libraries inside your application, also we don't know which package should be build first, you can have very complex graph, if we will run `tsc --build` before you will get the HUGE perfomance degradation, you can look at `bazel` if you want to desribe how to build your deps, even more you can use `babel` or `swc` to run new code on new version, and we can't know it, and there are a lot of other limitations

**Comment by aboe026** [comment]
`you can have big monorepo and don't use all libraries inside your application`
Typescript is actually very smart about what it builds and only includes projects in the direct dependency graph.

`also we don't know which package should be build first`
Webpack does not need to know anything about the order of typescript reference dependencies, its all abstracted by Typescript.

`you will get the HUGE perfomance degradation`
Typescript actually runs a difference check and only builds projects that have either not been built or have changes since their last build. So the performance impact should not be that large, especially after the first build.

In any case, it could be an optional opt-in flag so it won't impact any users unless the explicitly desire the functionality. Unless there is already some existing "pre-compile" flag that allows users to specify a command to run before the `webpack.config.ts` is ingested that I'm not aware of, I think it would be a very valuable functionality to add.

**Comment by alexander-akait** [comment]
> Typescript is actually very smart about what it builds and only includes projects in the direct dependency graph.

But we don't have ability to undestand it, just running `tsc --build` will have big problem with perfomance

> Webpack does not need to know anything about the order of typescript reference dependencies, its all abstracted by Typescript.

And which library should be build firstly? I don't know

> Typescript actually runs a difference check and only builds projects that have either not been built or have changes since their last build. So the performance impact should not be that large, especially after the first build.

No all projects uses incremental build, some projects add more flags to `tsc --build`, some projects uses babel/swc as I written above, some projects have more complex building and not only run `ts`.

> In any case, it could be an optional opt-in flag so it won't impact any users unless the explicitly desire the functionality. Unless there is already some existing "pre-compile" flag that allows users to specify a command to run before the webpack.config.ts is ingested that I'm not aware of, I think it would be a very valuable functionality to add.

You can just put own command before run `webpack`, that is why you have `scripts` in `package.json`

No one bundler or other tools do it, it is out of scope webpack

**Comment by aboe026** [comment]
`You can just put own command before run webpack, that is why you have scripts in package.json`
As you can see in the reproduction repository I linked in the initial comment that is exactly what I am doing to work around the issue. It would just be nice if the webpack integration with typescript did that for users natively.

`No one bundler or other tools do it, it is out of scope webpack`
I disagree, as webpack is well known for the variety of plugins that are written for it. I was hoping to be fix this issue with a plugin initially (such as the [webpack-shell-plugin-next](https://www.npmjs.com/package/webpack-shell-plugin-next) to do the `tsc --build` for me), but the problem is I need the compilation (`tsc --build`) to happen before the `webpack.config.ts` is even read. Is there any mechanism to do this? I feel like it would be extremely useful for users, and not just restricted to my own use case. Something like a `--pre-config` flag to run any arbitrary command before the config file is read in?
I'm not sure how that would ever have a negative impact on a user since it is opt-in, so any "slowdown" would be self-inflicted by the user themselves, and it would be up for them to decide if the ability to do something is worth the tradeoff in slowness (in my case, I would prefer to actually be able to do something rather than nothing, even if it comes with the slight performance hit that needs to come anyways, regardless of where the `tsc --build` command happens).

**Comment by alexander-akait** [comment]
Sorry, we will not implement this, it is out of scope, please use `scripts`/`bazel`/other orchestrators, tomorrow you can have more build tools and we can't support all of them, sorry again
