### ISSUE TITLE
I have a question about dependencies library:Tapable.js

### ISSUE THREAD

**Issue by zeyongTsai** [webpack/webpack#1632]
node_modules rootpath \ webpack \ node_modules \ tapable \ lib \ Tapable.js : 164

arguments[i].apply<this>;

TypeError:Cannot read property 'apply' of undefined.........

so,what should I do?

/*----Tapable.js source code----*/

Tapable.prototype.apply = function apply() {
	for(var i = 0; i < arguments.length; i++) {
		arguments[i].apply(this);
	}
};

/*---end---*/

It's easy to fix this bug,like this: 

arguments[i] && arguments[i].apply(this);

but I don't know  the real reason and what will happen?

**Comment by leoselig** [comment]
+1
We just experienced the same issue

**Comment by sokra** [comment]
You are propably passing something as plugin that is not a plugin.

**Comment by zeyongTsai** [comment]
@sokra 

I hava three plugins in npm > node_modules
1、babel    2、browser-sync   3、webpack

and in current project's node_modules
1、.bin    2、babel-core    3、babel-loader    4、webpack

devDependencies 3 & 4  in package.json

other info: WIN7 64 ,node 4.2.1 , npm 2.14.7,webpack 1.12.6 

BTW,that's OK in my WIN XP computer.

and I found the same issue in webpack/tapable https://github.com/webpack/tapable/pull/6

**Comment by zeyongTsai** [comment]
@sokra I see what plugin is right now :D   U r right! thanks!

**Comment by roryprimrose** [comment]
I had the same issue because the end of one of my plugins array entries was ,, instead of just ,

**Comment by jask84** [comment]
@roryprimrose I literally just encountered the same issue after spending hours trying to debug. Lucky I saw your comment and decided to have a look in my plugins array.

**Comment by alphapilgrim** [comment]
@sokra  i have the very same problem here's my webpack.test.config.js
`const webpack = require('webpack');
const path = require('path');
const commonConfig = require('./base.js');
const webpackMerge = require('webpack-merge');

module.exports = function(env) {
    return webpackMerge(commonConfig(), {
        devtool: 'inline-source-map',
        entry: {
            vendor: ['angular-mocks']
        },
        output: {
            filename: '[name].js',
            path: path.resolve('dist'),
            pathinfo: true
        },
        plugins: [
            'karma-webpack',
            'karma-chai',
            'karma-mocha',
            'karma-sourcemap-loader',
            'karma-mocha-reporter'
        ],
    })
};
`
return the following error: 

> ERROR [preprocess]: Can not load "webpack"!
  TypeError: arguments[i].apply is not a function
    at Compiler.apply (/node_modules/tapable/lib/Tapable.js:306:16)
    at webpack (/node_modules/webpack/lib/webpack.js:32:19)

if i remove the set of plugins then i get the following error: 

> Error
    at MemoryFileSystem.mkdirpSync (/node_modules/memory-fs/lib/MemoryFileSystem.js:144:10)
    at MemoryFileSystem.(anonymous function) [as mkdirp] (/node_modules/memory-fs/lib/MemoryFileSystem.js:279:34)
    at Compiler.<anonymous> (/node_modules/webpack/lib/Compiler.js:322:27)
