### ISSUE TITLE
A default export must be at the top level of a file or module declaration.

### ISSUE THREAD

**Issue by B2D1** [webpack/webpack#16338]
# Bug report

**What is the current behavior?**

in runtime~main.js, it causes a error named A default export must be at the top level of a file or module declaration.

<img width="538" alt="image" src="https://user-images.githubusercontent.com/36991862/194266916-a4d1e93d-47f4-4eac-9fd6-d6e68ddbc127.png">

```js
const path = require("path");
const Html = require("html-webpack-plugin");

module.exports = {
  entry: path.join(__dirname, "./src/app.js"),
  output: {
    path: path.join(__dirname, "dist"),
    clean: true,
    chunkFormat: "module",
  },
  target: "es2021",
  mode: "development",
  devtool: false,
  optimization: {
    runtimeChunk: true,
  },
  plugins: [
    new Html({
      scriptLoading: "module",
    }),
  ],
};
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  "^5.74.0",
Node.js version: v14.19.3
Operating System: macOS
Additional tools:

**Comment by alexander-akait** [comment]
> If the current behavior is a bug, please provide the steps to reproduce.

Please fill out this and will reopen
