### ISSUE TITLE
Square brackets not escaped in sourcesContent within source maps.

### ISSUE THREAD

**Issue by samunro** [webpack/webpack#1633]
The following line in url.js is resulting in the source maps that are generated by Webpack to be invalid.

```
delims = ['<', '>', '"', '`', ' ', '\r', '\n', '\t'],
```

It looks to me as though square brackets are not being escaped properly.

The following is am extract (I replace some content with an ellipses and truncated it after the relevant bit) of the sourcesContent element that is generated for the url.js file. Note that the square brackets from above are not escaped.

"// Copyright Joyent, Inc. and... // We actually just auto-escape these.\n    delims = ['<', '>'"', '`', ' ', '\r', '\n', '\t'],\n\n    // RFC 2396: characters not allowed for various reasons.

**Comment by sokra** [comment]
Uhgg... Why? It's just `JSON.stringify()`. Could you prepare a repro case?

**Comment by IngwiePhoenix** [comment]
Can we be sure that it actually _is_ a webpack bug, and not one by the sourcemaps generator?

I would suggest that we actually try something; replacing `'>'` with `">"`. Something tells me that this is a bug unrelated to webpack itself, but rather a dep.

**Comment by bebraw** [comment]
Can you set up a standalone test case for this?

**Comment by bebraw** [comment]
Not enough info. Please re-open if still relevant.
