### ISSUE TITLE
stats: 'errors-warnings' setting does not suppress success message

### ISSUE THREAD

**Issue by jordanbtucker** [webpack/webpack#16348]
# Bug report

**What is the current behavior?**

When the `stats` option is set to `'errors-warnings'`, it still outputs the message `webpack compiled successfully` to the console.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Open `webpack.config.js`.
2. Set the `stats` option to `'errors-warnings'`.
3. Run `webpack`.
4. Note the message `webpack compiled successfully`.

**What is the expected behavior?**

Webpack should not log a success message when `stats` is set to `'errors-warnings'` since the success message is neither an error nor a warning.

**Other relevant information:**
webpack version:
webpack: 5.74.0
webpack-cli: 4.10.0

Node.js version: 
v16.17.1

Operating System: 
Ubuntu

Additional tools:
VS Code

**Comment by alexander-akait** [comment]
Expected, please set `none` if you don't need any message, in another case we always output this message, sorry, we don't want to change it

**Comment by jordanbtucker** [comment]
What's the justification for not wanting to change it?

**Comment by alexander-akait** [comment]
`webpack compiled successfully` uses a lot of tools to indicate finished build (especial on CI), I want to say it is historical reasons, there are hooks to change it on the plugin level https://github.com/webpack/webpack/blob/main/lib/stats/StatsPrinter.js, so if you reall want it you can create a small plugin

**Comment by jordanbtucker** [comment]
Thanks for the history and suggestion! Would you accept a pull request to mention this in the docs?

**Comment by alexander-akait** [comment]
Yes, of couse, any docs improvements are welcome
