### ISSUE TITLE
get assets content in stats?

### ISSUE THREAD

**Issue by VisonM** [webpack/webpack#16350]
### Is there any way to get each `assets/chunk` content in `stats` or `compilation`?

I had set `stats:verbose` and just see each asset is `SizeOnlySource` object. so i can not get chunk source. Am I missing some docs?

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/40595135/194713783-205d1dce-b470-4f19-9c09-a9af38da5391.png">

webpack version: 5.74.0

**Comment by alexander-akait** [comment]
No, it is impossible, otherwise there will be a large memory consumption, you should use hooks and collect them if you need it

**Comment by VisonM** [comment]
##### Thanks for such a quick reply 💗!
I agree it will be a large memory consumption,but if each `asset` has more source info will be very useful for `debugging` or `test` and I give an example of what actually happened:

I just try run some test in [css-loader](https://github.com/webpack-contrib/css-loader/blob/master/test/esModule-option.test.js) or [style-loader](https://github.com/webpack-contrib/style-loader/blob/master/test/attributes-option.test.js) ,but all assets output to momeyfs to match snapshot. so I can't see what the end result is.

I have to admit that `SizeOnlySource` is a very high performance output type,I love webpack5! 

but can we provide a configuration that can replace the default `SizeOnlySource` to something like `CacheSource` or `VerboseSource` 😆 .It does not violate the high-performance design of webpack5, and enriches the functions of webpack. I hope you can consider this idea

in fact webpack4（4.44.1） is the way, so I can just copy the asset directly.

<img width="1210" alt="image" src="https://user-images.githubusercontent.com/40595135/194715959-1e4acdb0-6834-43cc-80cd-0392b5c235d5.png">

Finally, please forgive my English is not very good, it's all google translation 😂

**Comment by VisonM** [comment]
> No, it is impossible, otherwise there will be a large memory consumption, you should use hooks and collect them if you need it
> 
> Feel free to feedback

##### Thanks for such a quick reply 💗!
I agree it will be a large memory consumption,but if each `asset` has more source info will be very useful for `debugging` or `test` and I give an example of what actually happened:

I just try run some test in [css-loader](https://github.com/webpack-contrib/css-loader/blob/master/test/esModule-option.test.js) or [style-loader](https://github.com/webpack-contrib/style-loader/blob/master/test/attributes-option.test.js) ,but all assets output to momeyfs to match snapshot. so I can't see what the end result is.

I have to admit that `SizeOnlySource` is a very high performance output type,I love webpack5! 

but can we provide a configuration that can replace the default `SizeOnlySource` to something like `CacheSource` or `VerboseSource` 😆 .It does not violate the high-performance design of webpack5, and enriches the functions of webpack. I hope you can consider this idea

in fact webpack4（4.44.1） is the way, so I can just copy the asset directly.

<img width="1210" alt="image" src="https://user-images.githubusercontent.com/40595135/194715959-1e4acdb0-6834-43cc-80cd-0392b5c235d5.png">

Finally, please forgive my English is not very good, it's all google translation 😂
