### ISSUE TITLE
Webpack cache is not invalidated properly after updating one dependency

### ISSUE THREAD

**Issue by maksbotan** [webpack/webpack#16352]
# Bug report

**What is the current behavior?**

When using webpack cache, I get contaminated build after updating one of dependencies. Specifically, my project has a git dependency, after updating commit ref webpack seems to "merge" old one and new one.

**If the current behavior is a bug, please provide the steps to reproduce.**

I tried to construct minimal reproducing example for this, but my sample project seem to work fine, but main project does not.

What I do:

1. Have my project depend on `git+https://git.server.local/repo#old-branch-name`
2. In my `webpack.config.js` I configure `ts-loader` + `babel-loader`, asking them to work on **dependent repo**:
   ```js
    module: {
        rules: [{
            test:    /\.tsx?$/,
            // also process TS files from the dependency
            exclude: /node_modules(?!\/REPO)/,
            use: [{
                    loader: 'babel-loader',
                    options: require(path.resolve("babel.config.js")),
            }, {
                loader: 'ts-loader',
                options: {
                    transpileOnly: true,
                },
            }]
        }]
    },
   ```
4. Build with webpack
5. In that (dependent) repo, I heavily rewrite some files, and rename others (in particular, bunch of `index.js` to `index.ts`).
6. Run `npm i git+https://git.server.local/repo#NEW-branch-name`
7. Build with webpack again

After second build, I actually get a _mix_ of old and new package files from `REPO` in resulting bundle: one of the new `index.ts` files imports another module, but webpack actually inserts OLD code for OLD `index.js` from that module. That old code does not even exist in `node_modules/REPO` anymore.

If I remove `node_modules/.cache/webpack` and run build again, I get only NEW code in the bundle.

**What is the expected behavior?**

webpack should detect that `REPO` was updated and invalidate its cache for that package. 

**Other relevant information:**
webpack version:  5.73.0
Node.js version: 16.13.1
Operating System: macOS 12.4 Monterey
Additional tools:
```json
    "babel-loader": "^8.2.5",
    "ts-loader": "^9.3.1",
    "typescript": "^4.8.4",
```

**Comment by alexander-akait** [comment]
You should manually invalidate cache in this case, webpack can't do it for you, you can use https://webpack.js.org/configuration/cache/#cacheversion and store version of dependeices (hash of all urls or something else), if you have ability to use filesystem (for example remote disk), you can put paths here https://webpack.js.org/configuration/cache/#cachebuilddependencies

Feel free to feedback

**Comment by maksbotan** [comment]
Thanks for the answer!

Can you please elaborate a bit about `cache.buildDependencies`? This is a list of file or something else? Can I add `package-lock.json` to it in some way?

**Comment by alexander-akait** [comment]
This is a list of files, webpack stores snapshots of them (i.e. timestamp and hash of content, also if it is js, webpack parses them and include all `require`/`import` in deps, too under the hood), so any changes in these files invalidate your build, by default we store this here - https://github.com/webpack/webpack/blob/main/lib/config/defaults.js#L364 and webpack-cli by default add `webpakc.config.js` to this list too

**Comment by maksbotan** [comment]
Well, this is very confusing behavior. I've set up my CI to store webpack cache between builds. Do I understand correctly that each time I update some of my dependency's version, I have to manually clean that cache?

Would it make sense instead to add `package-lock.json` to `cache.buildDependencies`? Or at least mention this in the docs? I can make PR for that.

**Comment by alexander-akait** [comment]
> Do I understand correctly that each time I update some of my dependency's version, I have to manually clean that cache?

Webpack by default get your `package.json` and store infromation, but if you want to change default `buildDependencies`, you need to include `package.json`, so developer can create any own cache strategy. You can run webpack in watch mode with cache and change `package.json` (and install new deps or update and you will see - webpack compile the new version).

All webpack cache based on snapshot logic - https://github.com/webpack/webpack/blob/main/lib/config/defaults.js#L382 and you can see that we consider your version and updates (cache based on this logic too)

**Comment by maksbotan** [comment]
Sorry, I do not follow.

When I set, according to webpack documentation (https://webpack.js.org/configuration/cache/#cachebuilddependencies), `cache.buildDependencies: [__filename]` I __disable__ default behavior of depending on `package.json`?

Or if I don't, why it doesn't work?

**Comment by alexander-akait** [comment]
webpack-cli by default add `webpack.config.js` to `buildDependencies`, shortly - `buildDependencies` is list of files on which build depends, so if you have custom webpack runner you should put there all files, `package.json` will be considered in any way because `snapshot` logic depends on it

**Comment by maksbotan** [comment]
I have a hypothesis about why I get this behavior. I have a dependency on git _branch_, not a specific commit hash. So anytime I push to that branch and update the dependency, I get changes only in `package-json.lock`, __not__ in `package.json` itself.

May it be the case?

**Comment by alexander-akait** [comment]
Yes, so you need to use `version` to detect it, anyway if you have changes in `package-json.lock`, you can put them in `buildDependencies` too

**Comment by maksbotan** [comment]
Thank you for the answer!
