### ISSUE TITLE
Webworker target builds should work for module workers

### ISSUE THREAD

**Issue by cwli24** [webpack/webpack#16358]
## Feature request
When setting webpack config target to `'webworkers'`, the bundled code references `importScripts`. If we then want to run the code as a worker per se, it'd fail for `{type:'module'}` workers.

**What is the expected behavior?**
Webpack output code targeting webworkers should be able to run in both classic and module workers.

**What is motivation or use case for adding/changing the behavior?**
The original intention is to insert compiled+bundled code from a project or script into another worker-specific script (from another project). Right now, you can stitch the raw contents together, and they may run in a classic worker but not a module worker since the latter references `importScripts`.

**How should this be implemented in your opinion?**
Not too sure about the internals but ESM workers should follow ESM import behavior such as loading asynchronously and allowing dynamic imports.

**Are you willing to work on this yourself?**
no

**Comment by alexander-akait** [comment]
> Webpack output code targeting webworkers should be able to run in both classic and module workers.

Sorry, it is impossible, you can't use `importScripts` for ESM modules

You should build two workers and load them based on ESM supporting, you can use multi compiler mode, feel free to feedback

**Comment by cwli24** [comment]
@alexander-akait May I ask how do you build for the ESM worker if using `target: webworkers` => build with `importScripts` by default?

**Comment by alexander-akait** [comment]
You can use `library.type: "module"` to build ESM webworkers
