### ISSUE TITLE
About ModuleFederationPlugin host app hot reload when remote app change

### ISSUE THREAD

**Issue by UNDERCOVERj** [webpack/webpack#16366]
Is there a solution about "both start host app and remote app，then use host url to visit website，when remote app code changes，can host app hot reload，and host url website update immediately?"

**Comment by alexander-akait** [comment]
No solution, bidirectial reloading is not implemented yet, here are multiple issues about it https://github.com/webpack/webpack/discussions/16368 and you more, it is traced
