### ISSUE TITLE
is it possible to specify sourceMappingURL?

### ISSUE THREAD

**Issue by pkantsedalov** [webpack/webpack#1636]
Hi guys.

Help, please, with the specifying of sourceMappingURL.
We have our own dev-server, so we need to specify sourceMappingURL as a static asset URL like **/dist/bundle.js.map**, but the default output of the webpack is 
**# sourceMappingURL=bundle.js.map**.

Thanks in advance.

**Comment by sokra** [comment]
You can use the `append` option for the SourceMapDevToolPlugin. i. e. `append: "\n//# sourceMappingURL=/dist/"`

**Comment by pkantsedalov** [comment]
Thanx a lot for the response.
But tell, please, how could I specify it for the dynamic names like **bundle.js**, **1.bundle.js** ... **n.bundle.js**?
