### ISSUE TITLE
Worker

### ISSUE THREAD

**Issue by ronag** [webpack/webpack#1637]
Does the worker-loader still work on modern browsers?

When trying it on Chrome 46 I get the following error:

```javascript
Uncaught SecurityError: Failed to construct 'Worker': Script at 'http://localhost:8080/build/9001f291ed60186c4323.worker.js' cannot be accessed from origin 'http://localhost:8000'.
```

**Comment by sokra** [comment]
This is propably only a problem with the webpack-dev-server, because the script is served from a different domain. Try to serve the worker script from the same domain as the HTML page. i. e. with the proxy option of the dev-server.

**Comment by ronag** [comment]
I see. Have no idea how to use that so I'll have to figure that out. Thanks.
