### ISSUE TITLE
Hide Invalid Non-Strict Singleton Versions on Production Console

### ISSUE THREAD

**Issue by indeediansbrett** [webpack/webpack#16374]
## Feature request

**What is the expected behavior?**

`index.js:2 Unsatisfied version x.y.z from ------- of shared singleton module ----- (required ^x.y.z)` warnings should not appear on production console.

**What is motivation or use case for adding/changing the behavior?**

End users on browsers see these errors and think there's something wrong with the page.

**How should this be implemented in your opinion?**

Provide a setting to hide these warnings and/or only show them during build: 

https://github.com/webpack/webpack/blob/0bc3a2ea02ba85e23e4d1e01b4b1f15fb27b5c1d/lib/sharing/ConsumeSharedPlugin.js#L308-L310

https://github.com/webpack/webpack/blob/0bc3a2ea02ba85e23e4d1e01b4b1f15fb27b5c1d/lib/sharing/ConsumeSharedRuntimeModule.js#L118-L124

**Are you willing to work on this yourself?**
yes

**Comment by alexander-akait** [comment]
PR welcome, but I think it can be the problem for debugging

**Comment by indeediansbrett** [comment]
Do I not have permission to create a new branch? I have something to PR, but can't push up a new branch.

**Comment by indeediansbrett** [comment]
Ah nm, forked it. Will figure out the CLA with my org here.
https://github.com/webpack/webpack/pull/16388

**Comment by indeediansbrett** [comment]
Can I get a resolution on this MR? We were discussing programmatically removing every warn code snippet in two runtime modules, but I have concerns about maintainability with this approach.
