### ISSUE TITLE
Will there be webpack6? 

### ISSUE THREAD

**Issue by parrot-designa** [webpack/webpack#16377]
# Bug report

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

**Comment by alexander-akait** [comment]
Yes, webpack 6 will be, we have small pause for webpack itself (soon it will end), but we are continuing work in webpack ecosystem - loader and plugins, so don't worry, also there are a lot of tasks for webpack v5

**Comment by Rush** [comment]
I believe it would be beneficial for Webpack 6 to place an even **greater emphasis on performance optimization**. Given the competitive landscape, where rivals often tout performance as their main advantage, there's a clear opportunity for Webpack to catch up. Despite the competition's focus on speed, they frequently fall short in terms of features offered.

Would be great to see a public roadmap for Webpack 6.

**Comment by alexander-akait** [comment]
@Rush Yes we are already working on it, you can see a lot of performance optimizations in our latest releases, we don't have a public roadmap right now but it is one of the important improvements for us right now

**Comment by alexander-akait** [comment]
We don't have roadmap right now, we have issues which want to solve, so when our issues for webpack 5 will be solved we will make an major release, most of good features don't need a new major release
