### ISSUE TITLE
-c does not alias --config as it says in the --help message

### ISSUE THREAD

**Issue by jv-PintoBobcat** [webpack/webpack#1639]
I'm using version 1.12.6 and although the --help message shows that -c is an alias for --config, it doesn't work in practice. It acts as if my config file is my entry point. 

I'm running node 5.x.x.

**Comment by camhux** [comment]
This was patched in https://github.com/webpack/webpack/pull/1525, but this commit for whatever reason hasn't been included in following releases. The "-c" alias for "--config" is later overwritten by the "-c" for "--color". 

Tangentially, is there any reason why flags are declared both in the `bin/config-optimist.js` config script and in the `bin/webpack.js` command script? Having two separate sections of declarations might have led to the overwritten aliases in the first place.

**Comment by sokra** [comment]
> Tangentially, is there any reason why flags are declared both in the bin/config-optimist.js config script and in the bin/webpack.js command script? Having two separate sections of declarations might have led to the overwritten aliases in the first place.

True. `bin/config-optimist` is shared with the webpack-dev-server `bin/webpack` isn't.
