### ISSUE TITLE
Module Federation shareScope doesn't work as intended

### ISSUE THREAD

**Issue by daTrux** [webpack/webpack#16398]
# Bug report

**What is the current behavior?**
shareScope flag in the shared library object doesn't work as intended. If the shareScope property is added to the “share” object, then the shared package is downloaded multiple times. (One for each microfrontend that imports the package with the shareScope)

**If the current behavior is a bug, please provide the steps to reproduce.**
Here's a link to a github repository: https://github.com/daTrux/Module-Federation-Example
There you will find a simple example that consists in 4 angular projects in which:

- Two remotes have the shareScope set
- the shell and the remaining remote has no shareScope set

Run npm install in all projects and the use the ng serve command to start all the 4 applications.
In the browser dev tools, you will see that the projects which use the shareScope are downloading the package two times.

**What is the expected behavior?**
Adding a shareScope should result in a library to be downloaded only once per scope. (has explained in https://webpack.js.org/plugins/module-federation-plugin/#sharescope)

**Other relevant information:**
webpack version:  5.73.0
Node.js version: 14.18.1
Operating System: Windows 11

**Comment by 2heal1** [comment]
`ContainerPlugin` has `shareScope` option , but `ModuleFederationPlugin` not set `shareScope` to `ContainerPlugin`, which cause this problem .

After set `shareScope` option , the shared library are downloaded only once per scope

#16407

**Comment by 2heal1** [comment]
Usually, it can set [remotes.shareScope](https://github.com/webpack/webpack/blob/main/schemas/plugins/container/ModuleFederationPlugin.json#L314) to specify the shareScope that initializes the shared in `host` ,and set [shareScope](https://github.com/webpack/webpack/blob/main/schemas/plugins/container/ModuleFederationPlugin.json#L504) in  `producer`. 

But in this case ,it load remote module dynamic . And the `loadRemoteModule` will automatic init remote shared module by setting shareScope as `'default'` ,which will cause `mfe2` can't use `mfe3`'s shared module 。

You can load remote module and then set specify shareScope to init shared module manually. More detail [view this](https://github.com/daTrux/Module-Federation-Example/commit/7c9d6db2f036c2e5bf1d0df4a083d2247ca54123) .

And I found, `ContainerPlugin` has shareScope option , but `ModuleFederationPlugin` not set shareScope to `ContainerPlugin`. So I send PR #16407 .

Summarize, I solve this problem by using #16407 combined with setting [specify shareScope](https://github.com/daTrux/Module-Federation-Example/commit/7c9d6db2f036c2e5bf1d0df4a083d2247ca54123) .

hope this can be helpful

**Comment by daTrux** [comment]
Hi @2heal1 and thank you for your time.
I think I don't understant your messagge fully. I tried your solution [here](https://github.com/2heal1/Module-Federation-Example/commit/69bf8c58c77789a63b3178933c2142df5d12b041), but it seems that now, not only the problem i have is not solved but it also download the packages from `mfe1` that weren't previously downloaded, because there were shared with the shell
![image](https://user-images.githubusercontent.com/48359967/197555539-64fa66f3-45f0-40e9-b8cb-f444cae38bae.png)

Am I missing something? 
Thank you again

**Comment by 2heal1** [comment]
> Hi @2heal1 and thank you for your time. I think I don't understant your messagge fully. I tried your solution [here](https://github.com/2heal1/Module-Federation-Example/commit/69bf8c58c77789a63b3178933c2142df5d12b041), but it seems that now, not only the problem i have is not solved but it also download the packages from `mfe1` that weren't previously downloaded, because there were shared with the shell ![image](https://user-images.githubusercontent.com/48359967/197555539-64fa66f3-45f0-40e9-b8cb-f444cae38bae.png)
> 
> Am I missing something? Thank you again

Hi @daTrux , I miss something to push... And I found webpack@5.74.0 has already fixed PR #16407 .

I update webpack config and push , try [this](https://github.com/daTrux/Module-Federation-Example/commit/69bf8c58c77789a63b3178933c2142df5d12b041) again...

![image](https://user-images.githubusercontent.com/41466093/197674586-823e00ae-a156-4f94-bb44-1219d3408ef9.png)

**Comment by ScriptedAlchemy** [comment]
All remotes need to be initialized upfront. Otherwise you run the risk of partially patching share scope into another runtime. We can't reinitialize a remote, so at point or initialization, that's the only keys the remote has, if you add more remotes after the fact - they can assign shares to the scope, but runtimes already initialized cannot access these new shares. 

There are some ways around this - however it might lead to unexpected behavior which is why we seal the scope at point of initialization per runtime. 

You could use an es proxy 

Remote.init(new Proxy(webpackSharescope)) and add a handler to it. Then the object never "changes" but when querying scope you can get the latest memory references with updated keys.
