### ISSUE TITLE
Incorrect file extension in source map when using eval-source-map

### ISSUE THREAD

**Issue by sidx1024** [webpack/webpack#16415]
# Bug report

**What is the current behavior?**
- When using `"devtool": "eval-source-map"`, the generated source map contains invalid file extension `.js.js` instead of just `.js`. The same behaviour is seen for `.jsx` files, the extension is `.jsx.js`.
- The following is the source map JSON post converting it from the data URI format. See the value of `file` attribute.
```json
{
  "version": 3,
  "file": "./index.js.js",
  "mappings": "AAAA;AACA;AACA;AACA;AACA;AACA",
  "sources": ["webpack://source-map/./index.js?41f5"],
  "sourcesContent": [
    "// Sum of two numbers\nfunction sum(a, b) {\n  return a + b;\n}\n\nconsole.log(sum(7, 8));\n"
  ],
  "names": [],
  "sourceRoot": ""
}
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Code and instructions in this sample repo: https://github.com/sidx1024/eval-source-map-webpack-bug-repro

**What is the expected behavior?**
- When using `"devtool": "eval-source-map"`, the generated source map should have the correct file extension `.js`.

**Other relevant information:**
webpack version:  v5.74.0
Node.js version: v14.18.3
Operating System: MacOS
Additional tools: N/A

**Comment by alexander-akait** [comment]
Thank you for the report, PR welcome

**Comment by fromaline** [comment]
I'll try to fix this bug
