### ISSUE TITLE
perView: "auto" how to remove easing animation

### ISSUE THREAD

**Issue by Dachi301** [webpack/webpack#16422]

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

**Comment by Dachi301** [comment]
https://user-images.githubusercontent.com/69164520/198294596-bb12fbe2-5fb0-445f-8aed-e4320a42180d.mp4


I want to remove that easing animation

![sliderRef_img](https://user-images.githubusercontent.com/69164520/198294807-d43b80c3-3a24-4a36-99fe-9e927f6e24f3.jpg)

**Comment by Dachi301** [comment]
When I have perView to auto, it has that animation and I want to prevent that

**Comment by alexander-akait** [comment]
Sorry, it is a bug tracker for webpack, please ask this on stackoverflow
