### ISSUE TITLE
Webpack "lazyStyleTag" configuration won't copy fonts after upgrade to Angular 13

### ISSUE THREAD

**Issue by rb-mwindh** [webpack/webpack#16429]
Hi @alexander-akait ,
I hope you are doing well. Despite the tense and unpleasant situation worldwide, I wanted to ask if you can help me solve my problem: 

https://stackoverflow.com/questions/74234161/webpack-lazystyletag-configuration-wont-copy-fonts-after-upgrade-to-angular-1

Cheers, Markus

**Comment by alexander-akait** [comment]
@webpack-bot move to webpack-contrib/style-loader
