### ISSUE TITLE
TerserWebpackPlugin  - build for a long time（有什么方法）

### ISSUE THREAD

**Issue by ZHENGFANNN** [webpack/webpack#16437]
![image](https://user-images.githubusercontent.com/53977416/199177475-a6dfd7b7-8ed3-4bbc-bb00-6fea4ee283e0.png)

**Comment by alexander-akait** [comment]
Yes, minification take a time, you can use `swc` - https://github.com/webpack-contrib/terser-webpack-plugin#swc to speed up

**Comment by ZHENGFANNN** [comment]
> Yes, minification take a time, you can use `swc` - https://github.com/webpack-contrib/terser-webpack-plugin#swc to speed up

thanks

**Comment by ZHENGFANNN** [comment]
> Yes, minification take a time, you can use `swc` - https://github.com/webpack-contrib/terser-webpack-plugin#swc to speed up

My problem is solved very well, thank you
