### ISSUE TITLE
Add an option to suppress webpack chunk loading errors when using Entry Points

### ISSUE THREAD

**Issue by sxguo** [webpack/webpack#16442]
## Feature request
Add an option to suppress webpack chunk loading errors when using Entry Points to split code. An error is currently thrown in the chunk loading module, which seems to be included by default in webpack 4 and 5:
- webpack 4: [JsonpMainTemplatePlugin.js](https://github.com/webpack/webpack/blob/webpack-4/lib/web/JsonpMainTemplatePlugin.js)
- webpack 5: [JsonpChunkLoadingRuntimeModule.js](https://github.com/webpack/webpack/blob/main/lib/web/JsonpChunkLoadingRuntimeModule.js)

**What is the expected behavior?**
There should be an option to suppress webpack chunk loading errors when using Entry Points to do code splitting. I'd like to be able to control exactly what happens when webpack fails to load a chunk, without changing my implementation entirely to use dynamic imports instead of Entry Points.

**What is motivation or use case for adding/changing the behavior?**
Currently, an error is thrown in the requireEnsure function when a file webpack tries to load is not found, and there doesn't seem to be a way to catch these errors. When the user uses dynamic imports to specify exactly when and how a chunk should be loaded, it IS possible to implement retry logic, or other custom behavior. With Entry Points however, there doesn't seem to be a way to specify what happens after webpack attempts to load a module. Even with webpack loaders, we seem to only be able to modify the filenames and contents of the files to load, not what happens if the file load fails.

**How should this be implemented in your opinion?**
This could be an extra option on the `config` object for each module that suppresses Entry Point loading errors altogether, or a hook into the module loading function that lets devs specify exactly what behavior they want at that time in the module-loading lifecycle.

**Are you willing to work on this yourself?**
no

**Comment by alexander-akait** [comment]
I don't think you really need this, can you provide example?

**Comment by sxguo** [comment]
I'm using Entry Points to split code, and sometimes webpack requests chunks that fail to load. I'd like to control exactly what errors are thrown by webpack without resorting to doing something hacky like overriding the window.onerror function, which is likely to interfere with other code on the page. These webpack chunk-loading errors do not seem to be catchable, but please correct me if I'm wrong.

**Comment by alexander-akait** [comment]
@sxguo Can you provide small example?
