### ISSUE TITLE
webpack cannot re-export external modules

### ISSUE THREAD

**Issue by JaylyDev** [webpack/webpack#16440]
# Bug report

webpack seems to cannot compile aggregate modules syntax when the module is marked as external.
It works with modules that includes the original source (not marked as external), but not the ones marked as external.

**What is the current behavior?**

webpack cannot re-export external modules.

src/Main.js
```js
export * from 'fs';
```

dist/index.js
```js
import * as e from "fs"; // 'e' is declared but its value is never read.
var r = {
  d: (e, o) => {
    for (var t in o)
      r.o(o, t) &&
        !r.o(e, t) &&
        Object.defineProperty(e, t, { enumerable: !0, get: o[t] });
  },
  o: (e, r) => Object.prototype.hasOwnProperty.call(e, r),
};
r.d({}, {});
```

**If the current behavior is a bug, please provide the steps to reproduce.**

webpack.config.js
```js
const path = require("path");

module.exports = {
  entry: "./src/Main.js",
  target: ["es2020"],
  output: {
    filename: 'index.js',
    path: path.resolve(__dirname, 'dist'),
    library: {
      type: 'module',
    },
  },
  experiments: {
    outputModule: true,
  },
  externalsType: "module",
  externals: {
    'fs': 'fs',
  }
}
```

src/Main.js
```js
export * from 'fs';
```

![image](https://user-images.githubusercontent.com/65847850/199783788-fbbba48c-a716-4714-a3d9-cd371fe85f49.png)

**What is the expected behavior?**

external module should be re-exported in the bundled file. Something like
```js
export * from 'fs';
// webpack generated code here...
```

**Other relevant information:**
webpack version:  5.74.0
Node.js version: 16.16.0
Operating System: Windows 10
Additional tools:

**Comment by alexander-akait** [comment]
Webpack drops external `fs` because thinking it is unused (you can set `mode: "development"` and use `export * from 'fs';`).

You can try `export * as default from 'fs';` and it will work

Anyway thank you for the issue
