### ISSUE TITLE
Document a proper way to debug applications bundled by webpack

### ISSUE THREAD

**Issue by adamziel** [webpack/webpack#1646]
As far as I understand, right now the recommended way to debug are source maps in this mode:  
`eval - Each module is executed with eval and`  
There are a number of problems with using source maps in development:

1. Only some stacktraces are mapped using a source maps. Other are looking like this: `at eval (eval at <anonymous>  http://localhost:8082/js/app.js:2004:2), <anonymous>:43:67)`. Also, tracebacks produced by `console.error`, `console.trace` etc are not mapped - and this is a big deal if you happen to use library that does it, e.g. almost any `Promise` library.
1. It tends to be slow in big bundles

I am aware of [sourcemapped-stacktrace](https://github.com/novocaine/sourcemapped-stacktrace) - this is both slow, and error-prone.

One way of approaching it would be (optionally) eliminate source-maps from the process altogether and  add an option for webpack to behave similar to `require.js`: somehow tell it to split code at every single module.  
Since there would be no more single giant source-mapped bundle, and the code would live in a module with name same as the source file, and with the same line structure (e.g. babel has a `--retain-lines` option), chrome would consistently construct actually useful tracebacks.

Honestly guys I hope I am just missing something and there is an actual solution that I just didn't find :-)

**Comment by adamziel** [comment]
Similar issues:
https://github.com/webpack/webpack/issues/740
https://github.com/webpack/webpack/issues/1360

Related chrome issue:
https://code.google.com/p/chromium/issues/detail?id=376409

**Comment by adamziel** [comment]
Related issue in firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=583083

**Comment by sokra** [comment]
That's something browser vendors have to solve. SourceMaps are made for this.

**Comment by pksjce** [comment]
This issue was moved to webpack/webpack.io#110
