### ISSUE TITLE
oneOf rule has been picked multiple times

### ISSUE THREAD

**Issue by xiaoxiaojx** [webpack/webpack#16466]
# Bug report

https://github.com/vercel/next.js/pull/42283

**What is the current behavior?**

!!xxx/css-loader/src/index.js??xxx/postcss-loader/src/index.js??ruleSet[1].rules[3].oneOf[6].use[2]!./globals.css will not pick any loader, but asset/resource can be merged in

**What is the expected behavior?**

<img width="1066" alt="image" src="https://user-images.githubusercontent.com/23253540/201306107-d7783312-31e4-42ee-98f4-9aad0ee54e7b.png">

I'm guessing that the following new judgment statement should be added
```diff
+ if (r.type !== "type" || (r.type === "type" && r.value === settings.type) ) {

+ }
```

**Comment by alexander-akait** [comment]
Can you create reproducible test repon without next.js, seems they have overlapping in configurations

**Comment by xiaoxiaojx** [comment]
@alexander-akait  I wrote a reproducible demo
<img width="826" alt="image" src="https://user-images.githubusercontent.com/23253540/201533035-13ed205a-bf6c-4221-bbdc-4985e534567b.png">
```
git clone https://github.com/xiaoxiaojx/webpack-issuer-16466.git

yarn && yarn start

# dist/index.html opens in a browser
```

**Comment by alexander-akait** [comment]
bump
