### ISSUE TITLE
React Native App fails only just after setting up project with: Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.

### ISSUE THREAD

**Issue by JuliusGoddard** [webpack/webpack#16468]
# Bug report

**What is the current behavior?**

React Native Project fails to start after just setting it up

**If the current behavior is a bug, please provide the steps to reproduce.**

1. npx create-expo-app rate-repository-app --template expo-template-blank@sdk-46
2. npx expo install react-native-web@~0.18.7 react-dom@18.2.0 @expo/webpack-config@^0.17.0

error: ValidationError: Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'mimeTypes'. These properties are valid:
   object { allowedHosts?, bonjour?, client?, compress?, devMiddleware?, headers?, historyApiFallback?, host?, hot?, http2?, https?, ipc?, liveReload?, magicHtml?, onAfterSetupMiddleware?, onBeforeSetupMiddleware?, onListening?, open?, port?, proxy?, server?, setupExitSignals?, setupMiddlewares?, static?, watchFiles?, webSocketServer? }

**What is the expected behavior?**
Project should start without problems

**Other relevant information:**
webpack version:  4.43.0
Node.js version: 16.14.2
Operating System:  Windows
Additional tools: Visual Studio Code

**Comment by alexander-akait** [comment]
Please open an issue in `expo-template-blank` (or in repo there is template located), we can't fix validation problems here, sorry
