### ISSUE TITLE
webpack not respecting native node modules build from source

### ISSUE THREAD

**Issue by theofficialgman** [webpack/webpack#16470]
# Bug report
**What is the current behavior?**
using `npm run webpack` when `npm install --build-from-source` was previous specified ignores the build from source request and copies over prebuilt files to the `generated` directory.

**If the current behavior is a bug, please provide the steps to reproduce.**

using a repo with native node modules with prebuilts using prebuildify.

```
npm install --build-from-source
npm run webpack
```

current behavier copies over the prebuilt assets regardless of the rebuild being specified

**What is the expected behavior?**

expected behavier is that the built from source assets are used and copied over to the `generated/modules` folder but this is not the case.

**Other relevant information:**
webpack version:  latest
Node.js version: 16
Operating System: Linux
Additional tools: prebuildify

**Comment by alexander-akait** [comment]
We don't use `*.node` files in our deps or other binary libraries (only JS), I don't think we can fix it here, sorry
