### ISSUE TITLE
AngularJS 1.5 ng-pattern escape bug

### ISSUE THREAD

**Issue by jamesbcn** [webpack/webpack#16488]
**Bug report**

**What is the current behavior?**
I am migrating AngularJS, and some inputs have ng-pattern attribute. Webpack removes back-slashes in regex inside this attribute and because of this regex is not valid.

**tsconfig.json**
`{
    "compilerOptions": {
      "baseUrl": "",
      "declaration": false,
      "emitDecoratorMetadata": true,
      "experimentalDecorators": true,
      "lib": ["es6", "dom"],
      "mapRoot": "./",
      "module": "es6",
      "moduleResolution": "node",
      "outDir": "../dist/out-tsc",
      "sourceMap": true,
      "target": "es5",
      "typeRoots": [
        "./node_modules/@types"
      ]
    }
  }`

**webpack.config.js**
`
module.exports = {
    entry: "./app/main.ts",
    output: {
        filename: "src/dist/bundle.js"
    },
    resolve: {
        // Add '.ts' and '.tsx' as a resolvable extension.
        extensions: [".webpack.js", ".web.js", ".ts", ".tsx", ".js"]
    },
    module: {
        rules: [
            // all files with a '.ts' or '.tsx' extension will be handled by 'ts-loader'
            { test: /\.tsx?$/, loader: "ts-loader" }
        ]
    },
    optimization:{
        minimize: false
    }
};
`

**If the current behavior is a bug, please provide the steps to reproduce.**

In my code I have `ng-pattern="/^\+[\d]{7,15}$/"` and output is `ng-pattern="/^\+[\d]{7,15}$/"`

The same problem was reported and fixed in HTML-Loader [here](https://github.com/webpack-contrib/html-loader/pull/153). Since I am using TS-Loader I reported it there but they explained that TS-Loader does not touch the HTML. 

**What is the expected behavior?**
Regex back-slashes should not be removed within ng-pattern expressions. The regex within ng-pattern should be left alone.

**Other relevant information:**
Webpack version: 5.75.0
TS-Loader version: 9.4.1
Environment: Windows 10

**Comment by alexander-akait** [comment]
Sorry, not related to webpack, please open an issue in angular-cli repo or in loader which used to load templates, we don't touch HTML too

**Comment by alexander-akait** [comment]
Anyway if you created reproducible test repo I will show you there is the problem

**Comment by jamesbcn** [comment]
Not related to Webpack? I am not using Angular-CLI...

The problem was first reported by someone using HTML-loader as their Webpack loader. It was fixed.

I am using TS-Loader and I have been informed that they do nothing with the HTML.

The problem occurs when I transpile with Webpack. And I am not using Angular-CLI.

Why have you closed this?

**Comment by alexander-akait** [comment]
webpack don't touch HTML, your content handled by a loader or plugin, that is why I ask about a reproducible test repo, we can't fix it here, sorry
