### ISSUE TITLE
Make TemplatedPathPlugin's replacePathVariables available as a utility.

### ISSUE THREAD

**Issue by lzilioli** [webpack/webpack#1648]
I am working on writing a plugin that produces a manifest file when a webpack build completes.

As options to the plugin, I want to be able to let the user specify filenames/paths using webpack's available values such as `[chunk]`, etc.

Right now, that logic is tied up with the TemplatedPathPlugin.

I would like to break it out so that I can do something like this for my own webpack plugin:

## Plugin

```
var replacePathVariables = require( 'webpack/lib/TemplatedPathHelper' ).replacePathVariables;

function manifestPluginFactory( opts ) {
	return function() {
		this.plugin( 'done', function( stats ) {
			var manifestContents = _.chain( stats.compilation.namedChunks )
				.map( function( chunk ) {
					// The key is the canonical way to reference the
					// file.
					var key = chunk.name;
					// Get the root directory
					var serverPath = path.join( opts.root, opts.path, opts.fileName );
					// Leverage existing webpack replacePathVariables method
					stats.chunk = chunk;
					serverPath = replacePathVariables( serverPath, stats );
					return [ key, serverPath ];
				} )
				.object()
				.value();
			fs.writeFileSync( opts.manifestDest, JSON.stringify( manifestContents ) );
		} );
	}
}
```

## Webpack Config
```
{ plugins: [
	manifestPluginFactory( {
		root: '/webpack/build/',
		path: '[hash]/mobile/',
		fileName: '[name].js',
		manifestDest: 'path.join( process.cwd(), 'webpack/build/manifest.json' )'
	} )
] }
```

## Output

Contents of file written to manifestDest:
```
{ "mobile/store-test": "/webpack/build/366c982a5175bd728f12/mobile/store-test.js",
  "mobile/store": "/webpack/build/366c982a5175bd728f12/mobile/store.js" }
```

**Comment by lzilioli** [comment]
Submitted #1649 to address this issue. Feedback welcome, I would love to get this into a release if possible.

**Comment by sokra** [comment]
You can use it in your plugin.

`TemplatedPathPlugin` is not this thing that does the replacement. It's just a plugin that add some replacements. The actual API is the hook `asset-path` that's usable by everything that has a reference to the mainTemplate (which is in the compiler and the compilation).

``` js
mainTemplate.applyPluginsWaterfall("asset-path", "some string [hash]", {
	hash: hash,
	chunk: chunk
})
```

If you want to improve something here, add a `getAssetPath(string, options)` function to the `MainTemplate` that calls the hook and replace all occurences. That would look better.

see also #427
cc @diurnalist

**Comment by lzilioli** [comment]
@sokra Thanks a lot for the detailed response. This does, in fact meet my needs.
