### ISSUE TITLE
Package imported solely in import with `webpackChunkName` must not be splitted by `splitChunks`

### ISSUE THREAD

**Issue by mvorisek** [webpack/webpack#16497]
# Bug report

When a package is imported solely with in import with `webpackChunkName` flag, such package must be not create an extra vendor chunk.

**How to reproduce?**

checkout https://github.com/atk4/ui/commit/034f075b056dd0436d966176c1a8763c214df2d0 and run `npm run build` in `js` dir

in https://github.com/atk4/ui/blob/034f075b056dd0436d966176c1a8763c214df2d0/js/src/services/vue.service.js#L84 this file:

https://github.com/atk4/ui/blob/034f075b056dd0436d966176c1a8763c214df2d0/js/src/vue-components/query-builder/query-builder.component.vue is imported which imports `fomantic-ui-group.component.vue` and `fomantic-ui-rule.component.vue` (in the same dir) which import from `vue-query-builder` package

no other files import from `vue-query-builder` package

**What is the current behavior?**

`public/js/vendor-vue-query-builder.js` is created but the content should go into `public/js/atk-vue-query-builder.js` especially when https://github.com/atk4/ui/blob/034f075b056dd0436d966176c1a8763c214df2d0/js/webpack.config.js#L41-L44 lines are removed (tested, the files are still vendored)

**What is the expected behavior?**

I would expect webpack to detect `vue-query-builder` is used from single (already chunked) exported (already chunked) `public/js/atk-vue-query-builder.js` file and NOT create additional/uneeded `public/js/vendor-vue-query-builder.js` chuck

**Other relevant information:**
webpack version:  5.75.0 / latest

**Comment by alexander-akait** [comment]
Do you try https://webpack.js.org/plugins/split-chunks-plugin/#splitchunkscachegroupscachegroupreuseexistingchunk?

**Comment by mvorisek** [comment]
I tried:

![image](https://user-images.githubusercontent.com/2228672/203988492-e82cb690-a697-4dfb-b002-a28e670f469b.png)

but the build dir `public/js` has exactly the same content

**Comment by alexander-akait** [comment]
Also you can try https://webpack.js.org/plugins/split-chunks-plugin/#splitchunkscachegroupscachegrouppriority too and mark more priorities chunks and modules were moved to require chunks due this

**Comment by mvorisek** [comment]
I did several experiments with `splitChunks.cacheGroups.{cacheGroup}.priority` and all built files were the same (except some/unrelated/expected swapped load order).

I belive the problem is when `webpackChunkName` (annotation based configuration) is used together with `splitChunks` (file based configuration).

The problem can be reproduced on https://github.com/atk4/ui/tree/034f075b056dd0436d966176c1a8763c214df2d0/js, would you be ok to clone it locally and debug on your side? The expected result is NO `public/js/vendor-vue-query-builder.js` file, the content must be put inside `public/js/atk-vue-query-builder.js` as not imported anywhere else.
