### ISSUE TITLE
Windows problem: Can we add endOfLine: "auto" to .prettierrc.json?

### ISSUE THREAD

**Issue by jhribal** [webpack/webpack#16504]
Hello webpack,

Because of how `.gitattributes` is set and that [prettier default value](https://prettier.io/docs/en/options.html#end-of-line) for `endOfLine` option is `"lf"` from version 2.0.0 i ended up struggling with constant complain from vscode about my ugly `"crlf"` line ending.

Problem is solved by updating **.prettierrc.json** with `endOfLine: "auto"` and restarting vscode.

Thanks.

**Comment by alexander-akait** [comment]
Not related to webpack, sorry

**Comment by jhribal** [comment]
> Not related to webpack, sorry

I believe it is. Except if webpack doesn't care about those who clone Webpack repo on Windows. The problem wasn't caused by my setup or vsode. Webpack has dev dependency on prettier version that complains about CRLF line ending and there is no way how to force git to checkout (on Windows without modifications of repo source code) this repo with LF as line ending character.

Nevermind. Just wanted to avoid this issue for others who would clone on Windows.
