### ISSUE TITLE
Genereate a unique id for each compilation and use the id as key for map rather than reference

### ISSUE THREAD

**Issue by ShuiRuTian** [webpack/webpack#16507]
## Feature request

**What is the expected behavior?**
Current behavior: `NormalModule.getCompilationHooks` is using a map whose key is the reference of compilation.
expected behavior: give each compilation a unique id, and use the id as the key of the map to find hooks.

**What is motivation or use case for adding/changing the behavior?**
For myself, I am developing a successor of speed-measure-webpack-plugin to measure the time of each loader and plugin, to do this, I use Proxy(like speed-measure-webpack-plugin) to warp loader and tap method so that I could run extra logic before and after each loader and hook is really executed.
However, to proxy tap method, I need to proxy everything between compiler and the tap, including the compilation.
But if webpack is using reference-equal for some map, because the proxied compilation and the real compilation is different, there is some strange error.

There might be some other ways to do the trick, but it will be pretty good if webpack is able to make this small change.

**How should this be implemented in your opinion?**

When each compilation is created, generate a uuid as ID. Then use the ID as the key of the internal map inside `NormalModule.getCompilationHooks` to get hooks.

**Are you willing to work on this yourself?**
yes

**Comment by alexander-akait** [comment]
In theory you can do the same on the plugin side, I am not agains it, but just want to verify we can't solve it on the plugin side

**Comment by ShuiRuTian** [comment]
Sure, let me dig into code and have some more investigation....

**Comment by ShuiRuTian** [comment]
I found that we could hack `WeakMap` to try to use a custom ID. So we do not need to change webpack itself. This approach works fine for now.

Thanks!
