### ISSUE TITLE
Add support for referring to loaders as modules instead of paths

### ISSUE THREAD

**Issue by emilmuller** [webpack/webpack#16502]
Feature request: Add support for this (see bottom comment):

```
webpack({
    module: {
        rules: [
        {
            test: /\.(ts|js)x?$/,
            exclude: /node_modules/,
            use: {
                loader: require("babel-loader"), // <- Add support for accepting modules
```

When you use the [context](https://webpack.js.org/configuration/entry-context/) option, you are required to put the loaders inside the context path, or at least in a manner such that module resolution works, which is very inconvenient. It makes it impossible to use the Node interface to run Webpack on an arbitrary folder containing e.g. only .ts files.

**Comment by alexander-akait** [comment]
Sorry, we don't want to implement this due cache invalidation (it was dicussed a lot of time), you can use `require.resolve("../path/to/my/loader")`
