### ISSUE TITLE
InputFileSystem.readJson type should not be optional

### ISSUE THREAD

**Issue by jeengbe** [webpack/webpack#16515]
# Bug report

https://github.com/webpack/webpack/blob/7025319/lib/util/fs.js#L116

The type `InputFileSystem.readJson` should not be optional.

If the types are correct, then the behaviour at runtime should be altered since there really is no reason for this to be `| undefined`

**What is the current behavior?**

n/a

**If the current behavior is a bug, please provide the steps to reproduce.**

n/a

**What is the expected behavior?**

n/a

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

**Comment by alexander-akait** [comment]
This is expected, to avoid breaking change when we add new methods for `inputFileSystem`, we can revisit it for webpack v6, feel free to feedback
