### ISSUE TITLE
Webpack ModuleFederationPlugin breaks the build of libraries with default import

### ISSUE THREAD

**Issue by sviat9440** [webpack/webpack#16528]
# Bug report

Webpack ModuleFederationPlugin breaks the build of libraries with default import

**What is the current behavior?**

Library code:
```
import Test from 'some-library/entry1';
console.log(Test.isValidString('test'));
```
Was bundled to
```
"use strict";
exports.id = "some-library_esm_entry2_index_js";
exports.ids = ["some-library_esm_entry2_index_js"];
exports.modules = {

/***/ "./some-library/esm/entry2/index.js":
/*!******************************************!*\
  !*** ./some-library/esm/entry2/index.js ***!
  \******************************************/
/***/ ((__unused_webpack___webpack_module__, __webpack_exports__, __webpack_require__) => {

__webpack_require__.r(__webpack_exports__);
/* harmony import */ var some_library_entry1__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! some-library/entry1 */ "webpack/sharing/consume/default/some-library/entry1/some-library/entry1");

console.log(some_library_entry1__WEBPACK_IMPORTED_MODULE_0__.isValidString('test'));


/***/ })

};
;
```
When run this code, i getting error:
```
console.log(some_library_entry1__WEBPACK_IMPORTED_MODULE_0__.isValidString('test'));
                                                             ^

TypeError: some_library_entry1__WEBPACK_IMPORTED_MODULE_0__.isValidString is not a function
```

Build without ModuleFederationPlugin then everything works

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/sviat9440/webpack-module-federation-bug

**What is the expected behavior?**

Code with plugin ModuleFederationPlugin is equals with code without plugin.
Expected code:
```
console.log(some_library_entry1__WEBPACK_IMPORTED_MODULE_0__.default.isValidString('test'));
```

**Other relevant information:**
webpack version:  5.75.0
Node.js version: 16
Operating System: Windows 11
Additional tools:

**Comment by alexander-akait** [comment]
Please use:
```js
new ModuleFederationPlugin({
      shared: {
        'some-library/index': {
          singleton: true,
        },
      },
    }),
```    

or

```js
new ModuleFederationPlugin({
      shared: {
        'some-library': {
          singleton: true,
        },
      },
    }),
```

From docs - `Module requests with trailing / in shared will match all module requests with this prefix`

**Comment by sviat9440** [comment]
This is also not working as intended. 
https://github.com/sviat9440/webpack-module-federation-bug/tree/nultiple_declaration_bug
Project structure is:
- some-library (third party)
- shared
- module1

`shared` is used `some-library`
`module1` is used `some-library` and `shared`

everything from `some-library` is initialized twice and fails the equality check, despite the fact that `some-library` is marked as singleton.

**Comment by sviat9440** [comment]
start:shared & start:module1, then open http://localhost:3003.

Problem in code: new shared.Test() instanceof someLibEntry.default.
It's return false without trailing slash.

**Comment by sviat9440** [comment]
@alexander-akait

**Comment by sviat9440** [comment]
@alexander-akait I do not agree with the fact that you have closed this issue. Please reopen until the problem is resolved.

**Comment by alexander-akait** [comment]
Sorry for delay, I will look at this soon

**Comment by alexander-akait** [comment]
Here example to solve it:
```js
Promise.all([import('some-library'), import('shared')]).then(async ([someLibEntry, shared]) => {
    console.log(new shared.Test(), someLibEntry.default);
    console.log(new shared.Test() instanceof someLibEntry.default);
});
```

```
module.exports = {
    Test: require('some-library').default,
};
```

```
".": {
      "types": "./types/entry/index.d.ts",
      "import": "./esm/entry/index.js",
      "default": "./esm/entry/index.js"
    },
```

If you want to use `entry`, you should use the same in `shared` and `require` should be be align, because `shared` is not quite a module name, it is scope, but mostly used as module name.

**Comment by alexander-akait** [comment]
I really don't recommend to rely on `/`, because it can be misleading for resolver in some cases
