### ISSUE TITLE
Is UglifyJsPlugin missing an output-config-feature?

### ISSUE THREAD

**Issue by johannesnagl** [webpack/webpack#1652]
Hi guys, 

according to https://webpack.github.io/docs/list-of-plugins.html the UglifyJsPlugin does not support the "output" options (https://github.com/mishoo/UglifyJS2#usage, http://lisperator.net/uglifyjs/codegen). Is this correct?

I tried to add the following config:

```json
new webpack.optimize.UglifyJsPlugin({
      compress: {
        warnings: false,
      },
      output: {
        beautify: true,
        indent_level: 0,
      },
    }),
```

but the output does not change at all. Is this intended?

**Comment by sokra** [comment]
https://github.com/webpack/webpack/blob/master/lib/optimize/UglifyJsPlugin.js#L95-L108

**Comment by johannesnagl** [comment]
Thx for showing me the correct lines in the UglifyJsPlugin. I tested it again and the "output"-settings provided above do not make any difference.

Do you have a working example? (Google with "uglifyjsplugin beautify example" has not) I would like to have an output, where code is split up in multiple lines, like this:

![screen shot 2015-11-23 at 10 18 25](https://cloud.githubusercontent.com/assets/610811/11333123/9021a5be-91cb-11e5-8e67-c8554368f86c.png)
(example from the exact same options i pass to my old gulp uglify process)

I'm using webpack 1.12.2

**Comment by johannesnagl** [comment]
Sorry guys, I had a problem with the package.json, where a simple "-p" was defined in the "npm run build" command. Everything's working fine!
