### ISSUE TITLE
Code splitting in library mode causes undefined component import

### ISSUE THREAD

**Issue by xleepy** [webpack/webpack#16520]
# Bug report

**What is the current behavior?**
When code splitting used (common chunk usage) imported component resolved as undefined. 
I don't want to include shared code in each component import but i cannot achieve this with chunks or dependOn. 

**Library module import without code splitting**
![without_chunks](https://user-images.githubusercontent.com/26363903/204165783-50cc0d66-9371-4dd6-87d6-8e55f138200d.png)

**Library module import with code splitting**
![chunks_issue](https://user-images.githubusercontent.com/26363903/204165786-e7be37c6-2011-4747-aed2-a94a26ece7ed.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
Repository to reproduce: https://github.com/xleepy/webpack-library-code-splitting

**What is the expected behavior?**
Module should not return undefined module in case common chunk used (at least i hope)

**Other relevant information:**
webpack version:  5.75.0
Node.js version: v18.12.1
Operating System:  Xubuntu 22.04.1/macOS
Additional tools:

Thanks for any suggestion!

**Comment by xleepy** [comment]
I didn't deep dive in yet but I'll continue investigation.

**Comment by xleepy** [comment]
Tried to use externals with `dist/shared` `@test/shared-code-exmpl/shared` provided and still without no success

**Comment by xleepy** [comment]
@alexander-akait then Can you recommend to proceed with example if for example i'll have one large icons chunk and in case i'll not use code splitting this chunk will be in both components. Should i process local shared components once again in client build?

**Comment by alexander-akait** [comment]
@xleepy I recommend bundle (even more - you can avoid bundling and keep it in ESM) icons as a separate library and put in TODO how to use them, it's possible if you (an another developer) want to customize icons. Example:
```js
function Welcome(props) {
  return <img src={props.icon}>;
}

const root = ReactDOM.createRoot(document.getElementById('root'));
const element = <Welcome icon={new URL("my-library-icons/welcome.svg", import.meta.url)} />;
root.render(element);
```

Also developer can:
- optimize svg
- allow to setup any public path (it will be solved on the bundle side)
- use it in browsers without bundlers
- split code as wants

**Comment by xleepy** [comment]
Thanks for advice!
