### ISSUE TITLE
Facing Webpack ProvidePlugin is not defined

### ISSUE THREAD

**Issue by abhiseksubham** [webpack/webpack#16549]
I am trying to polyfill for process in webpack5 ,

something like this: 

`module.exports = {
  webpack: function (config, env) {
    config.externals = function (context, request, callback) {
      if (/canvg|pdfmake/.test(request)) {
        return callback(null, "commonjs " + request);
      }
      callback();
    };
    let loaders = config.resolve;
    loaders.fallback = {
      fs: false,
      tls: false,
      net: false,
      https: false,
      stream: require.resolve("stream-browserify"),
      crypto: require.resolve("crypto-browserify"),
    };

    config.plugins.push(
      new ProvidePlugin({
        process: "process/browser",
      })
    );
    return config;
  },
};`

But facing error "ProvidePlugin" isn't defined!!

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
