### ISSUE TITLE
commonjs Modules Do Not Work Correctly With externalsType of 'promise'

### ISSUE THREAD

**Issue by stevematney** [webpack/webpack#16544]
# Bug report

## What is the current behavior?

_**EDIT:**_ As per [this comment below](https://github.com/webpack/webpack/issues/16544#issuecomment-1358333143) this behavior seems to be isolated to commonjs modules (and possibly other non-esm modules).

When using `externalsType: 'promise'`, all known used exports get wrapped in an `async` function, and their `externals` dependencies are awaited. Modules marked as `__unused_webpack_module` _do not_ get wrapped with `async`, and _do not_ `await` their dependencies.

This can be resolved by the upstream dependency doing a different thing in their package.json and `exports`, but it seems unreasonable to expect that to be the case for _all_ dependencies. Quite often upstream dependencies do have exports that are marked as unused, even if they actually are used. These exports will break when `externalsType` is set to `promise`.

## If the current behavior is a bug, please provide the steps to reproduce.

1. Pull down this repo: https://github.com/stevematney/webpack-promise-externals-bug-example
2. Run `npm install && npm start`
3. Open `localhost:9000` in a browser.
4. Because we are not _also_ externalizing `react-dom`, our build does not run.

Notice in the resulting webpack bundle we see `react-dom` defined with this pattern:
```javascript
        /***/
        "./node_modules/react-dom/cjs/react-dom.development.js": /*!*************************************************************!*\
  !*** ./node_modules/react-dom/cjs/react-dom.development.js ***!
  \*************************************************************/
        /***/
        ((__unused_webpack_module,exports,__webpack_require__)=>{

            "use strict";
            /** @license React v17.0.2 ... */
```
    
Whereas our base module is defined with this pattern:
    
```javascript
 /***/
        "./src/index.js": /*!**********************!*\
  !*** ./src/index.js ***!
  \**********************/
        /***/
        ((module,__webpack_exports__,__webpack_require__)=>{

            "use strict";
            __webpack_require__.a(module, async(__webpack_handle_async_dependencies__,__webpack_async_result__)=>{

```

See that `react-dom` is missing the `async` setup. When it loads `__webpack_require__('react')`, it gets a Promise which it does not `await`, thus breaking when it looks for `ReactSharedInternals.ReactCurrentDispatcher`. `ReactSharedInternals` gets defined as `undefined` instead of the property of the `react` dependency that it should be.

## What is the expected behavior?
All modules should correctly resolve external dependencies using the async setup pattern, whether or not these modules are unused.

## Other relevant information:
webpack version:  5.75.0
Node.js version: 16.18.1
Operating System: macOS Ventura - 13.0.1 (22A400)

**Comment by stevematney** [comment]
It may be a _bigger_ concern that exports that are actually used are getting marked as unused, but I'm not as familiar with how webpack decides what is used and unused. My direct problem is that the externals aren't resolved correctly, but there may be more concern around used exports being marked as unused.

**Comment by alexander-akait** [comment]
Hello, why do you have wrappers - `Promise.resolve(...)`? Just remove them, and not extra promises

**Comment by stevematney** [comment]
I understand that I could remove the Promises to make everything work, and not use `externalsType: ‘promise’`, but the repo is written with the explicit intention to show the bug. The scenario in the example repo is contrived because it’s an extremely simple and unpolluted path to displaying the errant behavior we’re seeing in webpack.

Our real use case has quite a bit of complexity around it. I didn’t want to convolute the example with a lot of extra stuff to work through.

**Comment by alexander-akait** [comment]
@stevematney But you can't use `Promise.resolve` in externals when you have `externalsType: "promise"`, otherwise you need rewrite your code (and maybe some hacks in `webpack`).

Am I correct in assuming that some modules return a promise in their export (i.e. `export default new Promise.resolve(somthing)`)? (There are some limitations here and behaviour may differ between before/after bundling)

> Our real use case has quite a bit of complexity around it. I didn’t want to convolute the example with a lot of extra stuff to work through.

Maybe you can simplify it and show me?

**Comment by stevematney** [comment]
> ...You can't use Promise.resolve in externals when you have externalsType: "promise"...

I don't understand this. It's definitely working as expected, for the most part. In fact, the example repo I posted works perfectly if you just uncomment [this line](https://github.com/stevematney/webpack-promise-externals-bug-example/blob/main/webpack.config.js#L31). So it seems like you _can_ use it.

Also, looking at [the docs](https://webpack.js.org/configuration/externals/#externalstypepromise) it says that this:
```js
module.exports = {
  // ...
  externalsType: 'promise',
  externals: {
    jquery: '$',
  },
};
```

Will generate something like:
```js
const jq = await $;
jq('.my-element').animate(/* ... */);
```

This implies that `$` is actually some kind of Promise; otherwise using `await` with that value would be unnecessary. So, if the docs hold true:
```js
module.exports = {
  // ...
  externalsType: 'promise',
  externals: {
    jquery: 'Promise.resolve($)',
  },
};
```

Will generate something like:
```js
const jq = await Promise.resolve($);
jq('.my-element').animate(/* ... */);
```

This is definitely what I'm seeing on the other side except that modules marked with `__unused_webpack_module` are not doing what the docs say. (That is, they are not doing the `await $` part.)

> There are some limitations here and behaviour may differ between before/after bundling

The docs do not mention limitations or behavior variances, so I'm not sure what you're referring to.

> Maybe you can simplify it and show me?

What I have in the example repo is ultimately the simplest representation of what we need to do—we need to `await` a Promise for our externals which resolves to the external dependency. If that's not what `externalsType: 'promise'` does, I don't know what else it would be used for.

And, to be clear, that _is_ what `externalsType: 'promise'` is doing when a module is _not_ marked as unused. I'm not sure what I'm missing. 😧

**Comment by alexander-akait** [comment]
webpack can't undestand what code is in `Promise.resolve($)`, so we can't `awai` it twice, when you have:
```js
const jq = await Promise.resolve($);
jq('.my-element').animate(/* ... */);
```

`$` is promise
and `Promise.resolve` is promise too

So you have Promise inside Promise, that is why I say you need to do it on application side or hack webpack using a custom plugin.

You see `__unused_webpack_module` due above reasons, webpack can't handle such things, `Promise.resolve($)` is just a string, not more

> The docs do not mention limitations or behavior variances, so I'm not sure what you're referring to.

Yes, we don't have all possible limitations in docs (mostly because no one use it in such way and some of them are really very very rare).

**Comment by stevematney** [comment]
I understand what you're saying, but in the case of my example repo, none of the parameters passed to `Promise.resolve` are themselves promises. For example, in the case of `Promise.resolve(React)`, `React` is not a promise, but a `React` object. So none of these things would need to be double-awaited. I'm using `Promise.resolve` as a substitute for more complex code that boils down to the same thing when it comes time to require it in webpack—the `externals` are Promises (not Promises within Promises) that need to be awaited.

> You see __unused_webpack_module due above reasons, webpack can't handle such things, Promise.resolve($) is just a string, not more

`__unused_webpack_module` is _not_  being applied to my external packages, though. It's being applied to dependencies that the webpack tree should know about in more detail than the externals rendered with `Promise.resolve`.

In the case of the example repo, `react-dom` is a _non-externalized_ dependency that itself has a dependency on one of the externalized packages (`'react'`). Technically speaking, `react-dom` is _used_, but is erroneously getting marked as unused. Even without any `externals` configured at all, that package still has `__unused_webpack_module`. So `Promise.resolve` _cannot_ be the thing causing it to be marked as unused.

But that whole discussion seems to be a tangent from the issue itself, which is that _all modules_ marked as unused are doing the _wrong_ thing with `externalsType: promise`. None of them are awaiting the external dependency. It's not a case of my configuration necessitating a double `await`, it's a case of the _first_ `await` not happening at all.

**Comment by stevematney** [comment]
> You want inject promised external deps in non promised code...

This is what using `externalsType: promise` already does. My original modules may or may not be written with promises, but Webpack handles awaiting the externals by basically rewriting my original modules into async methods.

I noticed that this `async` rewrite _also_ happens with third-party code that is written as non-async ES Modules. This lead me to think that maybe it was the module _type_ that allowed the for awaiting promises. It turns out, that is correct. I wrote a local React component as a commonjs module rather than an ES Module, and that code also does not `await` the external dependency.

So, to be clear:
This file works: https://github.com/stevematney/webpack-promise-externals-bug-example/blob/main/src/index.js
This file does not: https://github.com/stevematney/webpack-promise-externals-bug-example/blob/main/src/CommonJsTest.js

**Comment by stevematney** [comment]
> ...and plus added more `Promise.resolve()`...

I want to be clear: there are no extra Promises involved. We're only talking about awaiting a single Promise. We're _never_ talking about resolving a Promise to another Promise, and expecting Webpack to know how to await that. I'm saying that I expect `externalsType: 'promise'` to work as described, and it does not seem to do so with modules that are not esm.

**Comment by stevematney** [comment]
> I noticed that this async rewrite also happens with third-party code that is written as non-async ES Modules. This lead me to think that maybe it was the module type that allowed for awaiting promises. It turns out, that is correct. I wrote a local React component as a commonjs module rather than an ES Module, and that code also does not await the external dependency.

Was there ever any followup investigation on whether this behavior around `externalsType: ‘promise’` is correct for non-esm modules? The docs don’t describe varying behavior for module types, and I don’t know of any express restrictions on other module types that would preclude async/await functionality, but I definitely don’t know everything, and I may be missing something there.

**Comment by alexander-akait** [comment]
So you expected `const React = require("react");` will work, right (i.e. - https://github.com/stevematney/webpack-promise-externals-bug-example/blob/main/src/CommonJsTest.js)?

**Comment by stevematney** [comment]
> So you expected const React = require("react"); will work, right

Yes, that’s what I would expect.

**Comment by alexander-akait** [comment]
hm, do you want to fix it or undestand why it doesn't work with commonjs?

Solution - use `externals` as a function:
```js
externals: async function foo({ context, request, contextInfo, getResolve }) {
    if (request === "react") {
     if  (contextInfo.issuer.includes("CommonJsTest.js")) {
       return "React";
     }

      return "Promise.resolve(React)";
    }

    if (request === "react-dom") {
      return "Promise.resolve(ReactDOM)";
    }

    if (request === "@material-ui/core") {
      return "Promise.resolve(MaterialUI)";
    }

    return Promise.resolve();
  },
```


It happens because you say webpack to wrap `react` in `Promise.resolve(...)`, and module is commonjs format, due this you need to use `await` in soure code in this case (you can enable topLevelAwait), also you can look at source code and found that you don't have `__webpack_handle_async_dependencies__` in commonjs

You can also use:
```js
externals: {
   react: "promise React",
   "react-dom": "promise ReactDOM",
   "@material-ui/core": "promise MaterialUI",
},
```

**Comment by alexander-akait** [comment]
> I think this is the main source of the problem. I will experiment with enabling topLevelAwait. Will doing so add __webpack_handle_async_dependencies__ to commonjs?

No, only ESM

**Comment by alexander-akait** [comment]
What do you try to solve? Why don't use `externals` as a function?

**Comment by stevematney** [comment]
> What do you try to solve? Why don't use externals as a function?

Sorry, we can definitely use externals as a function, but we can't use that function to sometimes return a Promise and sometimes not return a Promise. We're doing a few different things:
1. Loading externals asynchronously via UMD urls
2. Running multiple bundles on a page, but sharing the loaded text of the externals between bundles by processing them on a context object isolated to each bundle rather than on the global scope
3. Ensuring that we only request an external a single time over the network
4. Using webpack's `promise` external type to deliver those externals at runtime, allowing us to run bundles _as the externals are loading_, and for that code to only pause while the external is loaded.

The [isolated-externals-plugin README](https://github.com/WTW-IM/isolated-externals-plugin#usage) explains what we're doing and why more completely.

**Comment by alexander-akait** [comment]
Yeah, I see ... to be honest I don't see an universal solution here... anyway give me time to think about it, hard solution is copy/paste externals plugin code and change code (but yes, I undestand, it is an unwanted solution)

**Comment by stevematney** [comment]
Sounds good! Thank you for following up on it.

**Comment by stevematney** [comment]
Just an update: we worked around this issue in our plugin by using a special loader which gets applied if any of the parents of an external are non-esm. The loader preloads the externals into a synchronous object before running the original entry code. The downstream dependencies are overwritten to reference this synchronous object _instead of_ the Promised externals.

**Comment by stevematney** [comment]
Is it possible to reopen this without opening a new issue? This is definitely still a thing we are working around.
