### ISSUE TITLE
types.d.ts is invalid in 5.75

### ISSUE THREAD

**Issue by iain-logan** [webpack/webpack#16548]
# Bug report

**What is the current behavior?**
`types.d.ts` is valid prior to version 5.75, but in 5.75 it becomes invalid.

**If the current behavior is a bug, please provide the steps to reproduce.**
Using 5.75, it's not possible to compile (`tsc`) typescript projects using webpack because the syntax of `types.d.ts` is invalid.

It looks like this commit changed any occurrence of `readonly` to `get` in that file, which isn't valid syntax: https://github.com/webpack/webpack/commit/c18203c89447cd6728aa1f9d77b03aff7ae6e03f

**What is the expected behavior?**
Typing syntax is valid.

**Other relevant information:**
webpack version:  5.75
Node.js version: 14
Operating System: macOS 12.6
Additional tools:

**Comment by alexander-akait** [comment]
I can't reproduce, please provide example

**Comment by iain-logan** [comment]
Sure. Please see this minimal repo: https://github.com/iain-logan/webpack-bug-16548

`npm run build` fails on 5.75, but does not on 5.74.

Compile errors here: https://gist.github.com/iain-logan/dc66dea65b213e6f14b3a4a8ce301c6f

**Comment by alexander-akait** [comment]
Please check your typescript version and verify you don't change it, because I can't reproduce your problem using your repo

**Comment by iain-logan** [comment]
If I extend the repo with an npm script as below:
```
  "scripts": {
    "version": "tsc -v",
  ...
```

I can confirm the typescript version in use
```
➜  webpack-issue npm run version

> 16548@1.0.0 version /Volumes/workplace/webpack-issue
> tsc -v

Version 4.0.5
```

With this version above, I see the failure to build.

However, when using the latest version of typescript, this issue is not there when building.

```
➜  webpack-issue npm run version

> 16548@1.0.0 version /Volumes/workplace/webpack-issue
> tsc -v

Version 4.9.4
```

---

I'm not super familiar with .d.ts files, perhaps there was a syntax extension/bug fix between these version of typescript that is relevant here?

What version of typescript should the type definitions for webpack support? Would it be expected that all 4.* version of typescript would function with the type definitions?

**Comment by alexander-akait** [comment]
You should use the latest version of `typescript` (or as minimum 2-3 minors version before), sounds like old 4 versions have bugs (and fixed them late), I am afraid we can't fix it, because we prefer to use the latest stable version

**Comment by alexander-akait** [comment]
And `4.0.5` is really very old version, we are trying to avoid such situations, but sometimes it is impossible

**Comment by iain-logan** [comment]
Understood, thanks for your response.
