### ISSUE TITLE
Chrome reports wrong stack trace information and sees things that don't exist

### ISSUE THREAD

**Issue by ianbytchek** [webpack/webpack#1655]
Have been having the strangest issue for ages, now it's getting out of control and turns out to be related to handlebars. When my js fails from time to time, chrome often reports an error with the following stack trace. Now I need to debug something online, so I've put `debugger` statement, to find out chrome stopping at the exact same place.

```
Uncaught Error
OopUtility.mixin.onMount @ no-conflict.js:12
OopUtility.mixin.mount @ no-conflict.js:12
Mountable @ no-conflict.js:12
Network @ no-conflict.js:12
jQuery.fn.(anonymous function) @ no-conflict.js:12
JQueryUtility.bindPlugin @ no-conflict.js:12
(anonymous function) @ no-conflict.js:12
__webpack_require__ @ no-conflict.js:12
(anonymous function) @ no-conflict.js:12
(anonymous function) @ no-conflict.js:12
__webpack_require__ @ no-conflict.js:12
(anonymous function) @ no-conflict.js:12
(anonymous function) @ no-conflict.js:12
```

`no-conflic.js` is a tiny script, that looks like this:

```js
/* global window */
export default function(Handlebars) {
  /* istanbul ignore next */
  let root = typeof global !== 'undefined' ? global : window,
      $Handlebars = root.Handlebars;
  /* istanbul ignore next */
  Handlebars.noConflict = function() {
    if (root.Handlebars === Handlebars) {
      root.Handlebars = $Handlebars;
    }
  };
}
```

I package everything with webpack into `main.js` and it's the only script that I have executing. Where chrome gets this file? It's not even loaded into the browser nor available on the server. I've raised this issue at handlebars repo already, https://github.com/wycats/handlebars.js/issues/1134, but since webpack is responsible for packaging everything up and essentially is the entry point into this all, I think it well might be responsible in what's going on.

Did anybody see anything like this before? What might this be?

**Comment by ianbytchek** [comment]
I have an idea. Can this be related to source maps? The original `no-conflict.js` contains the following line, which I don't see in chrome.

```
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbImxpYi9oYW5kbGViYXJzL25vLWNvbmZsaWN0LmpzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7Ozs7bUJBQ2UsVUFBUyxVQUFVLEVBQUU7O0FBRWxDLFFBQUksSUFBSSxHQUFHLE9BQU8sTUFBTSxLQUFLLFdBQVcsR0FBRyxNQUFNLEdBQUcsTUFBTTtRQUN0RCxXQUFXLEdBQUcsSUFBSSxDQUFDLFVBQVUsQ0FBQzs7QUFFbEMsY0FBVSxDQUFDLFVBQVUsR0FBRyxZQUFXO0FBQ2pDLFVBQUksSUFBSSxDQUFDLFVBQVUsS0FBSyxVQUFVLEVBQUU7QUFDbEMsWUFBSSxDQUFDLFVBQVUsR0FBRyxXQUFXLENBQUM7T0FDL0I7S0FDRixDQUFDO0dBQ0giLCJmaWxlIjoibGliL2hhbmRsZWJhcnMvbm8tY29uZmxpY3QuanMiLCJzb3VyY2VzQ29udGVudCI6WyIvKiBnbG9iYWwgd2luZG93ICovXG5leHBvcnQgZGVmYXVsdCBmdW5jdGlvbihIYW5kbGViYXJzKSB7XG4gIC8qIGlzdGFuYnVsIGlnbm9yZSBuZXh0ICovXG4gIGxldCByb290ID0gdHlwZW9mIGdsb2JhbCAhPT0gJ3VuZGVmaW5lZCcgPyBnbG9iYWwgOiB3aW5kb3csXG4gICAgICAkSGFuZGxlYmFycyA9IHJvb3QuSGFuZGxlYmFycztcbiAgLyogaXN0YW5idWwgaWdub3JlIG5leHQgKi9cbiAgSGFuZGxlYmFycy5ub0NvbmZsaWN0ID0gZnVuY3Rpb24oKSB7XG4gICAgaWYgKHJvb3QuSGFuZGxlYmFycyA9PT0gSGFuZGxlYmFycykge1xuICAgICAgcm9vdC5IYW5kbGViYXJzID0gJEhhbmRsZWJhcnM7XG4gICAgfVxuICB9O1xufVxuIl19
```

**Comment by sokra** [comment]
yep, use this source-map-loader to integate the existing source-map into the webpack SourceMap

**Comment by ianbytchek** [comment]
@sokra cool. True, the issue seems to be those source map urls. Just tried stripping all the comments, and it worked as expected. Is there a built-in feature or plugin to disable them, not to integrate?
