### ISSUE TITLE
Página Web? 🤨

### ISSUE THREAD

**Issue by NOoByXz** [webpack/webpack#16553]
## Feature request

**What is the expected behavior?**

**What is motivation or use case for adding/changing the behavior?**

**How should this be implemented in your opinion?**

**Are you willing to work on this yourself?**
yes

**Comment by NotFenixio** [comment]
# Hello.

Create a new repository with the name of **ChangeThisName.github.io**.

Then, create a new file named **index.html**

You will need to know some HTML to start giving some life to your website.
Check out [my website](https://github.com/NotFenixio/web/blob/main/index.html) for some inspiration.

Then, go to your repo page settings (https://github.com/NOoByXz/YourRepoName/settings/pages), and check the instructions in there.

That's all forks!
