### ISSUE TITLE
Cannot resolve dynamic imports at runtime

### ISSUE THREAD

**Issue by mwaqar666** [webpack/webpack#16565]
# Bug report

**What is the current behavior?**
I am using Nx. I built an app using Webpack. Now in a dependent library, there's a dynamic import statement. Webpack gives error on runtime as `Module not found` with complete path of the file that is not found. Interestingly the file is present in it's location. Basically I am finding all the files that ends with `.migration.js` using glob pattern and then importing them at runtime.

**If the current behavior is a bug, please provide the steps to reproduce.**
Here's the repro steps: 
1. Clone the repo: [https://github.com/mwaqar666/sca](https://github.com/mwaqar666/sca)
2. Switch to branch backend/backend-integration
3. Run `npx nx run sca-cmd:build` (This will build the command-line application using Webpack)
4. Run `npx nx run backend-data-access-layer:build` (This will build the project using `tsc` compiler from which files are imported dynamically)
5. Run `npx nx run sca-cmd:run:dev --verbose -- migration:up` (This simply executes the `sca-cmd` app using `node`)

**What is the expected behavior?**
The dynamic import statement should find and import the file without any error

**Other relevant information:**
webpack version:  5.75.0
Node.js version: 18.12.1
Operating System: Ubuntu 22.04.1 LTS (Jammy Jellyfish)
Additional tools: Nx v15.3.3, Typescript v4.9.4

**Comment by alexander-akait** [comment]
> Error: Config validation error: "ACCESS_TOKEN_SECRET" is required

Using `If the current behavior is a bug, please provide the steps to reproduce.`
