### ISSUE TITLE
path-prefix for define/require for amd library type

### ISSUE THREAD

**Issue by long76** [webpack/webpack#16561]
## Feature request

**What is the expected behavior?**
call define from specify object

**What is motivation or use case for adding/changing the behavior?**
complex app may has many libraries and sometimes use window object to mapping libraries for example `window['requirejs']` or `window['jQuery3']`

**How should this be implemented in your opinion?**
like option for amd plugin `globalObject`
if option specifed before define/require put `${globalObject}.`

**Are you willing to work on this yourself?**
yes

**Comment by TheLarkInn** [comment]
Am reviewing now.

**Comment by long76** [comment]
thanks!
