### ISSUE TITLE
Add option to bail on build if MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by sdemjanenko** [webpack/webpack#1657]
I've run into an issue where when im running webpack in a production mode to build production assets the resulting bundles have messaging for `MODULE_NOT_FOUND` but there is no indication from the command-line that webpack was unable to find a module.  There should be some option that I can pass that will throw an exception in this case since I most definitely do not wish to push an asset with such a warning.

**Comment by sokra** [comment]
`--bail`

**Comment by sdemjanenko** [comment]
Does this flag work with grunt-webpack?  I have tried `bail: true` in the config and I dont get any warning in the command line
