### ISSUE TITLE
support css/auto as css module type

### ISSUE THREAD

**Issue by hardfist** [webpack/webpack#16572]
## Feature request

**What is the expected behavior?**
I want to use webpack css module to handle less-loader result
```ts
{
   module: {
    rules: [{
       test: /\.less$/,
       use: ['less-loader'],
       type: 'css/auto'
     }]
   }
}
```
without css/auto we need to configure two rules
```ts
{
   module: {
    rules: [{
       test: /\.module.less$/,
       use: ['less-loader'],
       type: 'css/module'
     },{
       test: /(?<!module).less$/,
       use: ['less-loader'],
       type: 'css/global'
     }]
   }
}
```
**What is motivation or use case for adding/changing the behavior?**
simplify the interop of experimental.css with less | sass
**How should this be implemented in your opinion?**
add a separate `css/auto` to automatic handle css file like css-loader https://github.com/webpack-contrib/css-loader/blob/ef749f29f8696b93f9eea61e6d00f2bb30ce094c/src/utils.js#L543
**Are you willing to work on this yourself?**
yes

**Comment by alexander-akait** [comment]
Make sense, feel free to send a PR, it should be easy
