### ISSUE TITLE
Should NormalModuleLoaderContext<OptionsTypes> have loaderContext._module as optional? 

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack#16574]
**What is the current behavior?**
Doing a little webpack 4 => 5 upgrading and using the types as my guide, but then it struck me when I saw a type notation that `loaderContext._module` is of type `NormalModule | undefined` in the types file. 

https://github.com/webpack/webpack/blob/4b4ca3bb53f36a5b8fc6bc1bd976ed7af161bd80/declarations/LoaderContext.d.ts#L21-L53

When I checked the code where the loaderContext is created: 

https://github.com/webpack/webpack/blob/4b4ca3bb53f36a5b8fc6bc1bd976ed7af161bd80/lib/NormalModule.js#L553-L674

It is unconditionally set to `this` aka `NormalModule`. I think that the types for the `NormalModuleLoaderContext<OptionTypes>` should not declare _module as possibly undefined. I believe this should also probably apply to _compiler and _compilation. 

Is there something I'm missing that would make these possibly `undefined`?

Happy to produce a PR.

**Comment by TheLarkInn** [comment]
Perhaps since this is happening in `_build` this could fail and result in the context not being set?

**Comment by alexander-akait** [comment]
The loader API initially originally designed to be used outside of webpack (but it didn't become popular), and when you are use them in non webpack ecosystem `_module`/`_compilation`/`_compiler` will be undefined...

**Comment by TheLarkInn** [comment]
Ahhhhh, but now these are inside of webpack and (perhaps) permanent fixtures for now given their usage. Should we update these to not be optional @alexander-akait?

**Comment by alexander-akait** [comment]
I don't have strong opinion here, but I am afraid it will be breaking change for some developers, because some of them can use loaders without webpack, I know couple projects which used `sass-loader` without webpack
