### ISSUE TITLE
In modelefederation, remotes'propertyname can't use webpack alias

### ISSUE THREAD

**Issue by garen-men** [webpack/webpack#16589]
I try to use webpack-resolve-alias for modulefederation remotes. It's not work.
like: remotes:{ '@xxx/core102': 'xxxx_core@https://cdn.xxx.com/xxx-core.js' }
    resolve: {
      alias:{ '@xxx/core102': '@xxx/core' }
    }

and in my code: import core from '@xxx/core/App';

build failed : Module not found

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
