### ISSUE TITLE
HMR load chunk fail if disable chunk filename hash.

### ISSUE THREAD

**Issue by underfin** [webpack/webpack#16599]
# Bug report

**What is the current behavior?**

HMR load chunk fail if disable chunk filename hash.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. add  `webpack.config.js` at https://github.com/webpack/webpack/tree/main/test/hotCases/runtime/dispose-removed-chunk floder.

``` .ts
module.exports = {
	output: {
		chunkFilename: "[id].js"
	}
};
```
2. run this test, you can see this code is not execute. https://github.com/webpack/webpack/blob/4b4ca3bb53f36a5b8fc6bc1bd976ed7af161bd80/test/hotCases/runtime/dispose-removed-chunk/index.js#L16

I debugger this and found the error is the `__webpack_require__.l` load script runtime is found before the same `a_js.js` url at document.head, so not create new script element to load new a_js.js chunk. Hope get some advice to let it fixed. Thank you.

**What is the expected behavior?**

HMR load chunk should correct if enable chunk filename hash.

**Other relevant information:**
webpack version:  
Node.js version: 
Operating System: 
Additional tools:

**Comment by alexander-akait** [comment]
> I debugger this and found the error is the __webpack_require__.l load script runtime is found before the same a_js.js url at document.head, so not create new script element to load new a_js.js chunk. Hope get some advice to let it fixed. Thank you.

Please clarify, I don't undestand, maybe you can create reproducible test repo?

**Comment by underfin** [comment]
Sorry for later feedback. You can checkout https://github.com/underfin/webpack/tree/test-hmr-16599 the branch and run `npx jest test/HotTestCasesWeb.test.js -t dispose-removed-chunk`

**Comment by alexander-akait** [comment]
@underfin Sorry for the delay, but the tests don't work because they weren't written for that case (they was written for `[name].chunk.[fullhash].js`). Maybe I something missing? I tried to reproducible locally, but it works :confused:

**Comment by underfin** [comment]
@alexander-akait it is wired. Maybe you forget to add `chunkFilename: "[id].js"` config?

**Comment by alexander-akait** [comment]
No, I can provide examples, with self written HMR and with react HMR, maybe you can provide more details
