### ISSUE TITLE
UglifyJsPlugin will change the class.name property

### ISSUE THREAD

**Issue by PinkyJie** [webpack/webpack#1659]
I'm using webpack with `webpack.optimize.UglifyJsPlugin` on an Angular app, I'd like to use this syntax to define controller:

```
// in header.controller.js
class HeaderController {...}
export default HeaderController;
```

```
// in app.js
import HeaderController from './header.controller'
angular.module('app', [])
    .controller(HeaderController.name, HeaderController);
```

However, I found uglify will change the class name, how to disable this?

**Comment by sokra** [comment]
https://www.npmjs.com/package/ng-annotate-loader

**Comment by PinkyJie** [comment]
@sokra That's not the case, `ng-annotate` can only handle the missing dependencies, but this issue is related to function name has been mangled. I tried to use the config below:
```
new webpack.optimize.UglifyJsPlugin({
        compress: {
                warnings: false,
                keep_fnames: true
        },
        mangle: {
            keep_fnames: true
            }
})
```
But it can not solve this issue.

**Comment by PinkyJie** [comment]
Finally I found the root cause, if you use `-p`, the UglifyJSPlugin will mangle variables by default, even if you have another `new webpack.optimize.UglifyJsPlugin` in your config, so if you want to config the UglifyJSPlugin, do not use `-p`.

I also file a bug on Webpack's doc https://github.com/webpack/docs/issues/49, the default mangle option for UglifyJsPlugin is not false, so if you do not want to mangle variables, you need to explicitly set this to false: `new webpack.optimize.UglifyJsPlugin({mangle: false})`.

**Comment by lvbeck** [comment]
@PinkyJie I have nearly same problem with you, I also use ES6 class and babel together in my angular app, my compressed javascript bundle works for google chrome , firefox and microsoft edge now but fails on Internet Explorer 11, with Error: [ng:areq] http://errors.angularjs.org/1.4.9/ng/areq?p0=MainController&p1=not%20a%20function%2C%20got%20undefined

**Comment by PinkyJie** [comment]
Hi @lvbeck, could you provide the detail error, e.g. the code snippet of the error line  `MainController`?

**Comment by lvbeck** [comment]
@PinkyJie , here are my error stack trace:
```
HTML1300: Navigation wurde ausgeführt.
login
Error: [ng:areq] http://errors.angularjs.org/1.4.9/ng/areq?p0=MainController&p1=not%20a%20function%2C%20got%20undefined
   at rb (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.9/angular.min.js:22:124)
   at Qa (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.9/angular.min.js:22:217)
   at Anonymous function (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.9/angular.min.js:80:210)
   at v (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.9/angular.min.js:60:176)
   at I (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.9/angular.min.js:61:28)
   at g (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.9/angular.min.js:55:97)
   at Anonymous function (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.9/angular.min.js:54:239)
   at Anonymous function (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.9/angular.min.js:20:99)
   at r.prototype.$eval (https://ajax.googleapis.com/ajax/libs/angularjs/1.4.9/angular.min.js:133:435)
   at r.prototype.$apply (https://ajax.googleapis.com/ajax/libs
```
and here are the error line:
```
function assertArg(arg, name, reason) {
  if (!arg) {
    throw ngMinErr('areq', "Argument '{0}' is {1}", (name || '?'), (reason || "required"));
  }
  return arg;
}

```
and 
```
    modules.unshift('ng');
    var injector = createInjector(modules, config.strictDi);
    injector.invoke(['$rootScope', '$rootElement', '$compile', '$injector',
       function bootstrapApply(scope, element, compile, injector) {
        scope.$apply(function() {
          element.data('$injector', injector);
          compile(element)(scope);
        });
      }]
    );
    return injector;
  };
```

**Comment by PinkyJie** [comment]
@lvbeck Sorry, I mean your source code snippet containing `MainController`, because I see the error message is `MainController not a function got undefined`.

**Comment by lvbeck** [comment]
@PinkyJie here is my controller in ES6 syntax

```

class MainController {
    constructor($rootScope, $scope) {
      ...
    }
}

MainController.$inject = ['$rootScope', '$scope'];

export default MainController;

```

and here is my angular app.js where include the controller:
```
import angular from 'angular';
import angular_sanitize from 'angular-sanitize';
import angular_cookies from 'angular-cookies';
import uirouter from 'angular-ui-router';
import config from './config';
import controller from './controller';

let dependencies = [
      uirouter
    , angular_sanitize
    , angular_cookies
];

export default angular.module('app', dependencies)
    .config(config)
    .controller(controller .name, controller )
    .name
;

```

**Comment by PinkyJie** [comment]
@lvbeck I think it's the same problem as mine, you can try to change `controller.name` to hard-code string `'MainController'`, if the problem is gone, then it's because UglifyJS has mangled `controller.name` property.

**Comment by lvbeck** [comment]
@PinkyJie thanks now it works for IE too! the only thing I still can not understand is, if UglifyJS mangled the controller name how it works for other browsers?

**Comment by PinkyJie** [comment]
@lvbeck I'm confused too...

**Comment by Zorbash** [comment]
This issue is not AngularJS specific. I'm using webpack@1.13.0 for a React application and the mangling of class names as a default config option in for `-p` builds is affecting me. I don't understand why this issue is closed with a link to a doubtful workaround applicable only to AngularJS apps.

**Comment by PinkyJie** [comment]
@Zorbash The only thing we can do is not using `-p` option and disable `mangel` option manually. I was thinking if we need to report an issue on https://github.com/mishoo/UglifyJS2.

**Comment by zhendong590** [comment]
@PinkyJie i met the same error but it didn't work when i config `mangel:false`,In my app,
```javascript
function bundle() {
  return new Promise((resolve, reject) => {
    webpack(webpackConfig).run((err, stats) => {
      if (err) {
        return reject(err);
      }
      console.log(stats.toString(webpackConfig[0].stats));
      resolve();
    });
  });
}
``` 
i donot know how disbale `-p`
my error message is 
```
ERROR in main.js?868be7d428f4b8777113 from UglifyJs
    Unexpected token: name (HsfClient) [main.js?868be7d428f4b8777113:105095,8]
```
the error js file is 
```javascript
class HsfClient extend extends Base{
// XXXX
}
```

**Comment by giscafer** [comment]
666,it works!!! thks guys

     "webpack": "^1.12.9"

```javascript
/**
     * compress js
     */
    new webpack.optimize.UglifyJsPlugin({
        compress: {
             warnings: false
        },
        mangle: {
            except: ['$super', '$', 'exports', 'require', 'angular'],
            keep_fnames: true//it works
        }
    }),
````

**Comment by sokra** [comment]
You may should not use `Function.prototype.name`. Disabling mangling is only a workaround.

**Comment by devdoomari3** [comment]
@sokra I'd love to not use 'Function.prototype.name'
but... other libraries (eg. Reflect-metadata) use a lot of 'constructor.name' :(

anyway, would it possible to have 'preserve name after this line' comments?
I remember angular1 had some feature related to 'ng-inject'.

e.g)
```
@pre<User>('save', async function (this: User) {
  this.createdAt = new Date()
})
/// WEBPACK:PRESERVE-NAME
class User extends Typegoose {
 // ...
}
