### ISSUE TITLE
[Module Federation] Loading remote assets with url() does not work

### ISSUE THREAD

**Issue by artgoce** [webpack/webpack#16596]
I have one host app (http://localhost:4200) and a remote app (http://localhost:4201), remote app uses url() to resolve assets in SASS files such as svg. The host application loads the remote correctly, but the assets are being resolved through the host app causing a 404 error while loading .svg files.

I've tried publicPath config in webpack output and in file-loader but nothing works. Is there any way to tell remote app from where url needs to resolve assets?

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

**Comment by alexander-akait** [comment]
Sorry without configurations we can't help you
