### ISSUE TITLE
Target: electron-preload outputs non-working js

### ISSUE THREAD

**Issue by MikeJerred** [webpack/webpack#16617]
# Bug report

**What is the current behavior?**
When setting the `target` in webpack to e.g. `electron22.0-preload`, the generated js includes webpack boilerplate code that uses `__dirname`, however `__dirname` is no longer available in electron preload scripts (https://github.com/electron/forge/issues/2931). The specific code that I am seeing is this:

```javascript
/******/ 	/* webpack/runtime/compat */
/******/ 	
/******/ 	if (typeof __webpack_require__ !== 'undefined') __webpack_require__.ab = __dirname + "/native_modules/";
```
The result is that electron cannot load the preload script, resulting in the whole app failing to load.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

Webpack should output code that is valid for the specified target, in this case it should just not output the `__webpack_require__` boilerplate at all.

**Other relevant information:**
webpack version: 5.75.0
Node.js version: 16.17.1
Operating System: Windows 10
Additional tools: electron 22.0.0

**Comment by alexander-akait** [comment]
Hello, can you provide configurations?

**Comment by MikeJerred** [comment]
Sure, my webpack config looks something like this:

```js
const path = require('path');
const merge = require('webpack-merge').merge;

module.exports = env => {
  const config = {
    devtool: 'inline-source-map',
    mode: 'development',
    optimization: {
      emitOnErrors: true,
      minimize: false
    },
    context: __dirname,
    output: {
      filename: '[name].js',
      chunkFilename: '[name].bundle.js',
      library: {
        type: 'commonjs2'
      },
      path: path.resolve(__dirname, 'dist'),
      devtoolModuleFilenameTemplate: '[absolute-resource-path]'
    },
    externals: [],
    node: {
      __dirname: false,
      __filename: false
    },
    module: {
      rules: [
        {
          test: /\.ts$/,
          exclude: /node_modules/,
          loader: 'ts-loader',
          options: {
            transpileOnly: true
          }
        }
      ]
    }
  };

  return [
    merge(config, { entry: { preload: path.resolve(__dirname, 'src/preload.ts') }, target: 'electron22.0-preload' }),
    merge(config, { entry: { main: path.resolve(__dirname, 'src/main.ts') }, target: 'electron22.0-main' }),
    merge(config, { entry: { worker: path.resolve(__dirname, 'src/worker.ts') }, target: 'electron22.0-main' })
  ];
};
```

Right now I am working around the issue by excluding the `preload` script from my webpack build and instead writing my own `preload.js` file

**Comment by alexander-akait** [comment]
Try to use `target: ['electron22.0-main', 'webworker']` for worker. Is `worker` is real worker or is it `renderer`?

**Comment by MikeJerred** [comment]
The worker script is a node.js worker that is started from the main process. I have no problems with this script - it is working fine - the problem is with the preload script as detailed in the issue description.

**Comment by alexander-akait** [comment]
@MikeJerred Sorry for big delay, weird, maybe bug in `webpack-merge`, do you have the lastest version? Can you show me output:
```
console.log([
    merge(config, { entry: { preload: path.resolve(__dirname, 'src/preload.ts') }, target: 'electron22.0-preload' }),
    merge(config, { entry: { main: path.resolve(__dirname, 'src/main.ts') }, target: 'electron22.0-main' }),
    merge(config, { entry: { worker: path.resolve(__dirname, 'src/worker.ts') }, target: 'electron22.0-main' })
]);
```

**Comment by MikeJerred** [comment]
> @MikeJerred Sorry for big delay, weird, maybe bug in `webpack-merge`, do you have the lastest version? Can you show me output:
> 
> ```
> console.log([
>     merge(config, { entry: { preload: path.resolve(__dirname, 'src/preload.ts') }, target: 'electron22.0-preload' }),
>     merge(config, { entry: { main: path.resolve(__dirname, 'src/main.ts') }, target: 'electron22.0-main' }),
>     merge(config, { entry: { worker: path.resolve(__dirname, 'src/worker.ts') }, target: 'electron22.0-main' })
> ]);
> ```
Hi, I have investigated this and it turns out that the problem is coming from a plugin: https://github.com/vercel/webpack-asset-relocator-loader
If I remove this plugin it works correctly, so I think this issue can be closed!

**Comment by alexander-akait** [comment]
Oh, yeah some non official loaders/plugins can have problems, it is good that you found a place why and where it happends, feel free to report it `webpack-asset-relocator-loader` developers and feel free to feedback
