### ISSUE TITLE
Debug Mode crashes in VS Code by webpack 

### ISSUE THREAD

**Issue by crechberger** [webpack/webpack#16612]
### Issue Description

When I create a new NS project from scratch with angular and want to debug the code of the sample project, it starts up the app in the simulator, however the debugger in VS Code crashes because of a webpack issue. 

### Reproduction

1. Install NativeScript for iOS (https://docs.nativescript.org/environment-setup.html#macos-ios)
2. ns create myCoolApp --angular
3. Install VS Code
4. Install the extension NativeScript in VS Code
5. Open the project in VS Code
6. Click on the run and debug Menu
7. Click on "create a launch.json file"
8. Select "NativeScript"
9. Click on "Launch on iOS"
10. Then after starting the app in the simulator and after the debugger crashed you can see the debug output in the bottom menu "Debug Console" and select "Launch on iOS"

### Relevant log output (if applicable)

```shell
Error when trying to require webpack.config.js file from path '/Users/test/Desktop/myCoolApp/webpack.config.js'. Error is: Error: Cannot find module '/package.json'
Require stack:
- /Users/test/Desktop/myCoolApp/node_modules/@nativescript/webpack/dist/helpers/project.js
- /Users/test/Desktop/myCoolApp/node_modules/@nativescript/webpack/dist/helpers/dependencies.js
- /Users/test/Desktop/myCoolApp/node_modules/@nativescript/webpack/dist/helpers/externalConfigs.js
- /Users/test/Desktop/myCoolApp/node_modules/@nativescript/webpack/dist/index.js
- /Users/test/Desktop/myCoolApp/webpack.config.js
- /Users/test/.vscode/extensions/nativescript.nativescript-0.12.3/out/debug-adapter/nativeScriptDebugAdapter.js
- /Users/test/.vscode/extensions/nativescript.nativescript-0.12.3/out/debug-adapter/nativeScriptDebug.js
- /[eval]
```

### Expected behavior

The vs code debugger does not crash after a few seconds and the webpack error does not appear 

### Environment

```yaml
OS: macOS 13.1
CPU: (8) arm64 Apple M1
Shell: /bin/zsh
node: 18.11.0
npm: 8.19.2
nativescript: 8.4.0

### Dependencies

```json
  "dependencies": {
    "@angular/animations": "~15.0.0",
    "@angular/common": "~15.0.0",
    "@angular/compiler": "~15.0.0",
    "@angular/core": "~15.0.0",
    "@angular/forms": "~15.0.0",
    "@angular/platform-browser": "~15.0.0",
    "@angular/platform-browser-dynamic": "~15.0.0",
    "@angular/router": "~15.0.0",
    "@nativescript/angular": "~15.0.0",
    "@nativescript/core": "~8.4.0",
    "@nativescript/theme": "~3.0.2",
    "rxjs": "~7.5.0",
    "zone.js": "~0.11.5"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~15.0.0",
    "@angular/compiler-cli": "~15.0.0",
    "@nativescript/ios": "8.4.0",
    "@nativescript/types": "~8.4.0",
    "@nativescript/webpack": "~5.0.12",
    "@ngtools/webpack": "~15.0.0",
    "typescript": "~4.8.4"
  }
```

Your help is appreciated!!

**Comment by alexander-akait** [comment]
Please open an issue in `nativescript` extension, thank you
