### ISSUE TITLE
Module parse failed: Unexpected token on ? and ?? (Nullish operators) with AWS-SDK

### ISSUE THREAD

**Issue by robertlario** [webpack/webpack#16627]
Under Node.js v16.17.0, when webpack@4.46.0 is applied to aws-sdk@2.1291.0, webpack fails on @aws-sdk/client-sns/dist-cjs/protocols/Aws_query.js, @aws-sdk/client-sns/dist-cjs/runtimeConfig.js, and @aws-sdk/client-sns/dist-cjs/endpoint/EndpointParameters.js.

It appears to hang on operators '?' and '??'
as an example, with Aws_query.js webpack calls out the '? as the offending token in the line:

 'if (input.AWSAccountId?.length === 0) {':

    if (input.AWSAccountId != null) {
|         const memberEntries = serializeAws_queryDelegatesList(input.AWSAccountId, context);
>         if (input.AWSAccountId?.length === 0) {
|             entries.AWSAccountId = [];
|         }

Here is what is generated by webpack in index.js:

/***/ "../../@aws-sdk/client-sns/dist-cjs/protocols/Aws_query.js":
/*!*******************************************************************************************************************************************************!*\
  !*** C:/XXXX/node_modules/@aws-sdk/client-sns/dist-cjs/protocols/Aws_query.js ***!
  \*******************************************************************************************************************************************************/
/*! no static exports found */
/***/ (function(module, exports) {

throw new Error("Module parse failed: Unexpected token (2801:31)\nYou may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders\n|     if (input.AWSAccountId != null) {\n|         const memberEntries = serializeAws_queryDelegatesList(input.AWSAccountId, context);\n>         if (input.AWSAccountId?.length === 0) {\n|             entries.AWSAccountId = [];\n|         }");

/***/ }),

/***/ "../../@aws-sdk/client-sns/dist-cjs/runtimeConfig.js":
/*!*************************************************************************************************************************************************!*\
  !*** C:/XXXX/node_modules/@aws-sdk/client-sns/dist-cjs/runtimeConfig.js ***!
  \*************************************************************************************************************************************************/
/*! no static exports found */
/***/ (function(module, exports) {

throw new Error("Module parse failed: Unexpected token (31:34)\nYou may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders\n|         runtime: \"node\",\n|         defaultsMode,\n>         bodyLengthChecker: config?.bodyLengthChecker ?? util_body_length_node_1.calculateBodyLength,\n|         credentialDefaultProvider: config?.credentialDefaultProvider ?? (0, client_sts_1.decorateDefaultCredentialProvider)(credential_provider_node_1.defaultProvider),\n|         defaultUserAgentProvider: config?.defaultUserAgentProvider ??");

/***/ }),

**Comment by alexander-akait** [comment]
Please migrate on webpck v5, webpack v4 is not supported nullish operator
