### ISSUE TITLE
how to exclude files from loader

### ISSUE THREAD

**Issue by pavel06081991** [webpack/webpack#1662]
I have the next config for webpack loaders:
```javascript
 module: {
    loaders: [{
      test: /\.js$/,
      include: rootDir + '/src',
      loader: 'babel?presets[]=es2015'
    }, {
      test: /\.css$/,
      loader: 'style!css!autoprefixer?browsers=last 2 versions'
    }, {
      test: /\.(png|gif|jpg|svg|ttf|eot|woff|woff2)$/,
      loader: 'file?name=[path][name].[ext]'
    }]
  }
```
I want to exclude some files from autoprefixer loader. How can I do this? If I do like this:
```javascript
{
  test: /\.css$/,
  exclude: 'someFile',
  loader: 'style!css!autoprefixer?browsers=last 2 versions'
}
```
someFile will be excluded not only from autoprefixer loader, it will be excluded from styles, css and autoprefixer loader, but I need exclude file only from autoprefixer loader. How can I do this?

**Comment by bebraw** [comment]
What if you had another rule like

```javascript
{
  test: /\.css$/,
  include: 'someFile',
  loader: 'style!css'
}
```

to deal with that requirement?

**Comment by pavel06081991** [comment]
sure, but what about adding autoprefixer to the chain? I mean how in this case to add autoprefixer?

**Comment by pavel06081991** [comment]
What about second rule which I wrote in the privious post, in this case it will not someFile anymore? only your rule will get this file?

**Comment by bebraw** [comment]
The idea was to write separate rules based on your requirements. You would include/exclude (accepts arrays) based on your exact need.

**Comment by pavel06081991** [comment]
I understood. Thanks, Juho.

**Comment by bebraw** [comment]
Safe to close?
