### ISSUE TITLE
Infinity loop in moduleFederationPlugin, in runtime loading module

### ISSUE THREAD

**Issue by AndreyGladkov** [webpack/webpack#16626]
# Bug report

**What is the current behavior?**
If your shared module do not import all modules in main index.js file(use for tree shaking), fallback module infitity looping browser runtime.
[Consumes](https://github.com/webpack/webpack/blob/main/lib/sharing/ConsumeSharedRuntimeModule.js#L311) function should call infinity, while maximum call stack size exceeded.

**If the current behavior is a bug, please provide the steps to reproduce.**
#### Provider:
```
{
  ...,
  "ui/blocks/address/address": {
    "import": "./libs/ui/blocks/address/address.js",
    "requiredVersion": "^164.1.0",
    "version": "164.1.0",
    "packageName": "ui/build/blocks/address/address.js"
  },
  "ui/blocks/address/geoObjectHelper": {
    "import": "./libs/ui/blocks/address/geoObjectHelper.js",
    "requiredVersion": "^164.1.0",
    "version": "164.1.0",
    "packageName": "ui/build/blocks/address/geoObjectHelper.js"
  },
  "ui/blocks/address/location": {
    "import": "./libs/ui/blocks/address/location.js",
    "requiredVersion": "^164.1.0",
    "version": "164.1.0",
    "packageName": "ui/build/blocks/address/location.js"
  },
  ...
}
```
#### Consumer:
```
...,
{
  "ui/blocks/address/address": {
    "requiredVersion": "^168.1.3",
    "version": "168.1.3",
  },
  "ui/blocks/address/geoObjectHelper": {
    "requiredVersion": "^168.1.3",
    "version": "168.1.3",
  },
  "ui/blocks/address/location": {
    "requiredVersion": "^168.1.3",
    "version": "168.1.3",
  }
},
...
```
#### Example moduleToHandlerMapping
```
...,
"webpack/sharing/consume/default/ui/blocks/address/addressContent/ui/blocks/address/address": () => (loadStrictVersionCheckFallback("default", "ui/blocks/address/address", [1,168,1,3], () => (__webpack_require__.e("ui-fallback").then(() => (() => (__webpack_require__(/*! ui/blocks/address/addressContent */ "./node_modules/@hh.ru/ui/build/blocks/address/addressContent.js"))))))),
"webpack/sharing/consume/default/ui/blocks/address/addressHeader/ui/blocks/address/geoObjectHelper": () => (loadStrictVersionCheckFallback("default", "ui/blocks/address/geoObjectHelper", [1,168,1,3], () => (__webpack_require__.e("ui-fallback").then(() => (() => (__webpack_require__(/*! ui/blocks/address/addressHeader */ "./node_modules/@hh.ru/ui/build/blocks/address/addressHeader.js"))))))),
"webpack/sharing/consume/default/ui/blocks/address/addressFooter/ui/blocks/address/location": () => (loadStrictVersionCheckFallback("default", "ui/blocks/address/location", [1,168,1,3], () => (__webpack_require__.e("ui-fallback").then(() => (() => (__webpack_require__(/*! ui/blocks/address/addressFooter */ "./node_modules/@hh.ru/ui/build/blocks/address/addressFooter.js"))))))),
...
```

#### Example ChunkMapping
```
{
    'ui-fallback': [
        'webpack/sharing/consume/default/ui/blocks/address/address',
        'webpack/sharing/consume/default/react/react',
        'webpack/sharing/consume/default/ui/blocks/address/geoObjectHelper/ui/blocks/address/geoObjectHelper',
        'webpack/sharing/consume/default/ui/blocks/address/location/ui/blocks/address/location',
    ],
    ...
}
```

#### Register
```
...,
register("ui/blocks/address/address", "168.1.3", () => (Promise.all([__webpack_require__.e("ui-fallback"), __webpack_require__.e("vendors-node_modules_react_jsx-runtime_js")]).then(() => (() => (__webpack_require__(/*! ./node_modules/ui/blocks/address/address.js */ "./node_modules/ui/blocks/address/address.js"))))));
...,
```
#### Example 
Consumer front should use fallback version, but runtime code is falled by maximum call stack.
I debugged the problem and found the problematic place: https://github.com/webpack/webpack/pull/16625
return statement not work in forEach loop. I replaced to for loop and add check to start init modules(it fixes infinity looping).

**What is the expected behavior?**
Fallback modules loaded without infinity looping

**Other relevant information:**
webpack version: 5.62.0
Node.js version: ^14 | ^16 | ^18
Operating System: macos 13.1
Additional tools: chrome browser

**Comment by alexander-akait** [comment]
Can you provide reproducible example?

**Comment by anicioalexandre** [comment]
had the same issue, would be awesome to see https://github.com/webpack/webpack/pull/16625 resolved, it solved the problem in my case

**Comment by alexander-akait** [comment]
@anicioalexandre we need a test case for it and we can merge, can you provide it?

**Comment by anicioalexandre** [comment]
@alexander-akait I tried to clean the repo (it's a private one) to reproduce it but then I guess I removed too much stuff and I couldn't reproduce it again, I will see if I can try again

**Comment by alexander-akait** [comment]
@anicioalexandre yeah, we just need a test case and we can merge :smile:

**Comment by AndreyGladkov** [comment]
> we just need a test case and we can merge
@alexander-akait hi here is an example:

https://github.com/AndreyGladkov/webpack-mfp-infitity-loop-example/tree/main/dynamic-system-host#bug-description
