### ISSUE TITLE
imported module becomes `undefined` when using `splitChunks`

### ISSUE THREAD

**Issue by meowtec** [webpack/webpack#16624]
# Bug report

**What is the current behavior?**

My app run into error when I config `splitChunks`:

```js
  optimization: {
    minimize: false,
    splitChunks: {
      chunks: 'all',
      minSize: 5000,
      cacheGroups: {
        vendors: {
          test: /node_modules/,
          name: 'vendors',
          filename: '[name].js',
        },
        common: {
          filename: '[name].js',
          name: 'common',
          test: /src\/icons/,
        },
      },
    },
  },
```

![image](https://user-images.githubusercontent.com/4006436/211306834-02092cec-7e7c-49e6-ad31-48f771f4d885.png)

In the screenshot, `esm_extend` is the babel helper module which is injected by the babel loader. 

But it is `undefined`, because `786 == __webpack_require__.j` is `false` so `var esm_extends = __webpack_require__(882);` in line 18 was not executed.

Online example: https://meowtec.github.io/webpack-minimal-reproduce-20230109/index.html
And minimal reproduction: https://github.com/meowtec/webpack-minimal-reproduce-20230109

**If the current behavior is a bug, please provide the steps to reproduce.**
See the code repo: https://github.com/meowtec/webpack-minimal-reproduce-20230109

[reproduce.zip](https://github.com/webpack/webpack/files/10373221/reproduce.zip)

**What is the expected behavior?**

Should render a SVG icon

**Other relevant information:**
webpack version:  5.75.0
Node.js version: v16.16.0
Operating System: macOS 12.5.1
Additional tools:
    babel-loader: ^9.1.2 => 9.1.2 
    webpack: ^5.75.0 => 5.75.0 
    webpack-cli: ^5.0.1 => 5.0.1

**Comment by alexander-akait** [comment]
If you want to use the each entry as separated page you need to configure https://webpack.js.org/configuration/optimization/#optimizationruntimechunk.

Set:
```
runtimeChunk: {
      name: 'runtime',
},
```

and

```
<script src="./dist/runtime.js"></script>
<script src="./dist/vendors.js"></script>
<script src="./dist/common.js"></script>
<script src="./dist/c.js"></script>
```    

To avoid writting it manually I recommend to use `html-webpack-plugin`

**Comment by alexander-akait** [comment]
Feel free to feedback
