### ISSUE TITLE
how to preload images with webpack

### ISSUE THREAD

**Issue by pavel06081991** [webpack/webpack#1663]
For example I have module "menu". This module depends on menu.js, menu.css modules. In menu.css there are some styles with image url. For example there is menu.sprite.png And I have module "home.page". When you click "load menu" button on home page, I want for menu.css and menu.sprite.png to be loaded before showing module "menu". How can I do loading images with webpack? Is there any loader which adds img tag on page and then uses onload event for this image?

**Comment by sokra** [comment]
Out of scope for webpack. Just use the normal methods for preloading.

**Comment by pavel06081991** [comment]
Thanks for reply. But why is it out of webpack scope? If to think about images as about modules, images must be loaded before resolving. I think it is a good thing because now when our pages is loaded browser have not loaded images yet and we do not see images on our page, then when images are loaded, browser will show them on page. It is bad. I want for all images to be loaded before the module which depends on some images to be resolved and to be showed on page.

**Comment by sokra** [comment]
> I think there must be any webpack loader or plugin which makes this.

Feel free to create one. You basically need to call `new Image().src = url;`.

**Comment by sokra** [comment]
Hint: it's a pitching loader.

**Comment by pavel06081991** [comment]
If I'm strong in nodejs I would make it... Anyway thanks. Maybe I'll try.

**Comment by glebmachine** [comment]
Hi @sokra!
I'm trying to implement same loader. 
Main idea is to warm up all assets from css file, filtered by `device pixel ratio`.

My issues:
 - I can't find the way, to defer export (like promise or whatever).
 - I can generate file with require.ensure, but, then i can't filter images (all images for 1x,2x,3x will be loaded + problem with large base64 images)

Please, can you give few more hits)

**Comment by pavel06081991** [comment]
@glebmachine, please, write here when you finish this loader :) Thanks.

**Comment by glebmachine** [comment]
@pavel06081991 it's not so easy as @sokra said)

**Comment by pavel06081991** [comment]
@glebmachine I believe you can do it! :)

**Comment by glebmachine** [comment]
@sokra, please, give me a clue(

**Comment by sokra** [comment]
``` js
// preload-image-loader
module.exports = function() {};
module.exports.pitch = function(remainingRequest) {
  this.cacheable();
  return [
    "var url = require(" + loaderUtils.stringifyRequest("!!" + remainingRequest) + ");",
    "new Image().src = url;",
    "module.exports = url;"
  ].join("\n");
}
```

``` js
module.loaders: [
  { test: /\.png$/, loaders: [
    "preload-image-loader",
    "file-loader"
  ] }
]
```

``` js
var url = require("./image.png"); // start preloading...

// do something with url
module.exports = "<img src='" + url + "'>";
```

**Comment by glebmachine** [comment]
Thank you! 
Appreciate that, will try soon)

Gleb Mikheev

+7 916 118 2821

**Comment by glebmachine** [comment]
@sokra 
Sorry, again(

This start preload, but, dont wait until images are fully loaded (like require.ensure "wait" for all inner modules)

As i wrote (twice, first in comment and second in email), i can't find the way to finish preloading all images before module resolves

**Comment by jessehattabaugh** [comment]
@sokra I am attempting to use the `preload-image-loader` you describe above. Can you please explain this part `"var url = require(" + loaderUtils.stringifyRequest("!!" + remainingRequest) + ");"`

What is the '!!' for? The docs for `stringifyRequest` show it being used with `this` not `remainingRequest`, why are you using it that way here?

**Comment by BuonOmo** [comment]
FYI: sokra's code is available in an nom package (https://www.npmjs.com/package/preload-image-loader)

Didn't work for me though..

**Comment by pycarlos** [comment]
Hi there, Any news?

**Comment by glebmachine** [comment]
I gave writen image preloader on framework layer, not webpack.

**Comment by pycarlos** [comment]
@glebmachine can you share your fix? 
I tried to use preload-image-loader but its not work.

**Comment by glebmachine** [comment]
That is not a loader for webpack, it's a just some code like this:

```js
function preloadImage(url) {
  const image = document.createElement('img');
  img.onload = function(){
    alert('loaded');
  }
  img.src = url;
}
```

that's all
