### ISSUE TITLE
`require.main` is not supported

### ISSUE THREAD

**Issue by TechStudent10** [webpack/webpack#16661]
# Bug report

**What is the current behavior?**

Webpack outputs `require.main` isn't required when in #64, it looks like support was added. When looking in the bundled code, Webpack replaces the statement with `(void 0)`.

![image](https://user-images.githubusercontent.com/76978184/213926389-ea476e3b-20ac-4f91-a07f-43a2b6c852b0.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Create a file that uses `require.main`.
2. Compile it
3. See warning in webpack output
4. See `(void 0)` in bundled code

Webpack config: https://gist.github.com/TechStudent10/a53cb2007c052129fa505d794b8afadf

**What is the expected behavior?**

`require.main` shouldn't be compiled to `(void 0)`, but rather `Module` (according to the NodeJS docs):

![image](https://user-images.githubusercontent.com/76978184/213926638-7b35e1b3-ab04-4fe8-8a10-f9435337c112.png)

**Other relevant information:**
webpack version:  5.75.0
Node.js version: v19.1.0
Operating System: Windows 11 21H2
Additional tools:

**Comment by alexander-akait** [comment]
You should set `target: 'node'` if you want to support it, for `target: 'web'` it is converted to `void 0` for bakcward compatbility with some legacy code, feel free to feedback

**Comment by TechStudent10** [comment]
> You should set `target: 'node'` if you want to support it, for `target: 'web'` it is converted to `void 0` for bakcward compatbility with some legacy code, feel free to feedback

I feel like this should be included in the error message, it is rather cryptic for such as simple fix.

**Comment by alexander-akait** [comment]
@TechStudent10 we can't understand the `target` based on the code, but we can improve our documentation, feel free to send a PR, webpack mostly used for web applications so the default value of `target` is `web`

**Comment by TechStudent10** [comment]
> @TechStudent10 we can't understand the `target` based on the code, but we can improve our documentation, feel free to send a PR, webpack mostly used for web applications so the default value of `target` is `web` or `browserslist`

All I'm saying is that if the fix is so simple, you should add a warning whenever `require.main` is detected and the `target` isn't `node`. I'm not sure I understand your message.

**Comment by alexander-akait** [comment]
@TechStudent10 I am about:
```js
if (require.main) {
  // Logic for Node env
} else {
// Logic for non Node env
}
```

And it will be false positive and I can provide more cases for all Node stuff. Ideally - a linter can help to catch such things (mix node and browser code, but you can isomorphic application and it is normal to have such code), but it will not say about the `target` option for webpack, I would say that this is a small part of the knowledge that you should know.

I'm not opposed to warning improvements, but if you look at different applications you will find that they very often have use mixed of browser and node code to detect env and it will be very annoing for such developers. Feel free to feedback

**Comment by TechStudent10** [comment]
> I'm not opposed to warning improvements, but if you look at different applications you will find that they very often have use mixed of browser and node code to detect env and it will be very annoing for such developers. Feel free to feedback

Ah okay I think I get it now.
