### ISSUE TITLE
how to replace statics tags uri  automaticly

### ISSUE THREAD

**Issue by todo-mvc** [webpack/webpack#1666]
when i use webpack with express and ejs, 
i found that when i finish build the static files (with hash in the name),i need to replace script/css tags in ejs files manual.
any idear?
just like below (index.ejs);
 ``` ... <script src="index.js" ></script>... ```
to
``` ... <script src="index.[hash].js"></script> ...```

**Comment by bebraw** [comment]
You can get the generated names through [stats](https://github.com/FormidableLabs/webpack-stats-plugin) and then use some templating solution for that. I also suggest looking into [html-webpack-plugin](https://github.com/ampedandwired/html-webpack-plugin).
