### ISSUE TITLE
code-splitted-require.context question

### ISSUE THREAD

**Issue by jefferygan** [webpack/webpack#1667]
In this example https://github.com/webpack/webpack/tree/master/examples/code-splitted-require.context, getTemplate() files in ../require.context/templates ^\.\/.*$ are all bundle into 1.output.js. 
I hope the code can be splitted by the arguments pass to getTemplate(), not all the files in the ../require.context/templates ^\.\/.*$. for example, getTemplate(''a''), it will bundle the  ../require.context/templates/a.js and others file required in a.js.
The actual demand i quesitioned in http://stackoverflow.com/questions/33888819/how-to-use-webpack-define-a-function-to-dynamic-require-files.

**Comment by sokra** [comment]
fixed in `System.import` in webpack 2

**Comment by GilbertGan** [comment]
have any other methods?

**Comment by bebraw** [comment]
Closing given it has been fixed in webpack 2.
