### ISSUE TITLE
Expensive module hashing for all files on every rebuild

### ISSUE THREAD

**Issue by DrewML** [webpack/webpack#16673]
# Bug report

**What is the current behavior?**

When running `webpack` with `watch` mode and collecting a CPU profile, I can observe that the `createModuleHashes` step in the `seal` phase is costing us a large amount of time (often 1s+). In the screenshot below, it took ~400ms

<img width="1362" alt="image" src="https://user-images.githubusercontent.com/5233399/214899286-f30ed902-d33d-42b5-b6a9-9b8084499c3a.png">

**If the current behavior is a bug, please provide the steps to reproduce.**

The steps on our project are:

1. Run `npx webpack --watch`, then making a change to a file

**What is the expected behavior?**
My expectation is that webpack would keep a cache of hashes for all modules that have _not_ triggered a change, and would re-use those hashes. This may be a bad expectation depending on what webpack is using the hash for (is it just file contents? maybe includes changes to deps?).

It _looks_ like `lib/Compilation.js` does keep a cache for hashes in `createModuleHashes` (`moduleMemCaches2`), but it's empty in our project whenever a rebuild is triggered:

<img width="1427" alt="image" src="https://user-images.githubusercontent.com/5233399/214900412-191b7a3f-9546-497c-90b8-3d7ca59c812b.png">

At the end of this method, `statModulesFromCache` is always a number > 2k

**Other relevant information:**
webpack version:  `5.73.0`
Node.js version: `16.12.0`
Operating System: macOS
Additional tools:

**Comment by TheLarkInn** [comment]
@DrewML would you be willing to contribute a fix here?

**Comment by TheLarkInn** [comment]
@DrewML would you be able to try https://webpack.js.org/configuration/experiments/#experimentscacheunaffected this flag in webpack to see whether or not this improves the performance of you build.

**Comment by TheLarkInn** [comment]
Friendly Ping on this.
