### ISSUE TITLE
Can't resolve module 'https' ... but it is installed.

### ISSUE THREAD

**Issue by Ju777** [webpack/webpack#16688]
# Bug report

Hello, 

I did previously try to ask questions on stackoverflow : https://stackoverflow.com/questions/75298355/cant-install-the-https-module-in-react-webpack?noredirect=1#comment132868538_75298355

**What is the current behavior?**
The compiling gives the following error message related to the ``https`` module which is actually installed but not found :
```
Module not found: Error: Can't resolve 'https' in '/home/etcetera ...'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
    - add a fallback 'resolve.fallback: { "https": require.resolve("https-browserify") }'
    - install 'https-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
    resolve.fallback: { "https": false }
```

**I can't find any ``webpack.config.js`` to apply what is suggested in the error message.**

**If the current behavior is a bug, please provide the steps to reproduce.**
1 - npx create-react-app any_name
2 - npm install https
3 - try to import the https module with ``import https from 'https'``
4 - write ``npm start`` in the terminal, and then you should get the error previously mentionned.

**What is the expected behavior?**
I expect a nice compiling step without error and being able to use the ``https`` package.

**Other relevant information:**
webpack version: I did not install a webpack package. It's all in my react app "under the hood" as I used create-react-app.
Node.js version: v18.6.0
Operating System: Ubuntu
Additional tools: I am using WSL

**Comment by alexander-akait** [comment]
Because you don't have `https` package in browser (your target is `web` by default), you can try to provide polyfill in such case, because most of things will not work, node.js env !== browser's env, feel free to feedback
