### ISSUE TITLE
Minimum chromium version for Webpack5

### ISSUE THREAD

**Issue by Yahma054** [webpack/webpack#16690]
I'm currently working on an IOT project where we have a chromium version 32. It's used to render the react app that's been built to display on a tv panel. In this project we're using webpack v.3 and there are no problems. However, when we were looking to upgrade to webpack v.5, it completley broke the application. Is there a minimum required chromium version required to run webpack 5?

Something to take into consideration: We have another iteration of the same project with a new iteration of the hardware with a chromium version of 76. When we upgraded the exact same project to webpack v.5, it had no issues. This is what leads myself and others on my team to believe that the issue is with the chromium version running on our hardware.

**Comment by csvan** [comment]
From the docs:

```
Webpack supports all browsers that are [ES5-compliant](https://kangax.github.io/compat-table/es5/) (IE8 and below are not supported). Webpack needs Promise for [import() and require.ensure()](https://webpack.js.org/guides/code-splitting/#dynamic-imports). If you want to support older browsers, you will need to [load a polyfill](https://webpack.js.org/guides/shimming/) before using these expressions.
```
https://webpack.js.org/concepts/#browser-compatibility

You should verify if this is the case for Chromium 32, which is extremely old by now.

**Comment by Yahma054** [comment]
Based on what i'm seeing on `caniuse.com` chromium fully supported `es5` starting in `chromium 23`. So it's a bit perplexing as to why it would crash. In any case, I'll close the issue. Thanks for the info @csvan!
