### ISSUE TITLE
1.5GB events.json generated by profiling plugin

### ISSUE THREAD

**Issue by icy0307** [webpack/webpack#16691]
# Bug report

**What is the current behavior?**
Events.json generated by the profiling plugin gets too large to show in chrome's developer tool.

**If the current behavior is a bug, please provide the steps to reproduce.**
It is a private company project so I can't show the code base directly.
How ever I managed to upload the zipped file to google drive
https://drive.google.com/file/d/1JOx_RGYj3qIOkEL04DAasvtWimFZuN3E/view?usp=sharing
Even after being compressed to 20.1 MB, Chrome still fails to open it.

**What is the expected behavior?**
Be able to track the build time

**Other relevant information:**
webpack version:  5.73.0
Node.js version: 
Operating System: 
Additional tools:

My original question is my build performance in production varies greatly in different machines, or even on the same machine.
On a single machine, it ranges from 5min to 30min.  Is there any cache for the production build?

**Comment by TheLarkInn** [comment]
If you are looking for alternatives to printing a `.cpuprofile` you can use the `--cpu-prof` node flag:  https://github.com/nodejs/node/blob/main/doc/api/cli.md#--cpu-prof. Additionally a webpack plugin: https://github.com/kenotron/cpupro-webpack-plugin made by my coworker which works very well. If the file is too large consider uploading to another tool like: https://github.com/lahmatiy/cpupro

As for addressing caching, webpack does attempt to cache as much as possible, however a variety of factors will invalidate the cache. 

I would start by uploading a `.cpuprofile` and analyzing it. Will close this for now. But i'd implore you to contribute this information to our documentation so you can save the next person from submitting an issue on it, and also a contributor from answering. 🙏💌

**Comment by icy0307** [comment]
Thanks for your detailed answer, I will try this approach sometime around next week, and create a pr for documentation❤️
@TheLarkInn
