### ISSUE TITLE
Node.js on server

### ISSUE THREAD

**Issue by getsetgopi** [webpack/webpack#16695]
Do I need to have Node.js running on production to use **Webpack Module Federation**? Will it work if I just do a build (host and consumer app) in Jenkins and promote to production?

**Comment by csvan** [comment]
You only need Node during the build process itself. The generated static files will have everything needed for module federation to work (depending on how you implement it).

**Comment by getsetgopi** [comment]
Thanks for the prompt response! We have node available in Jenkins build. I will build and host in prod and see if it works.

**Comment by TheLarkInn** [comment]
Appears answered. Will close for now.
