### ISSUE TITLE
UglifyJsPlugin error with `qs` package

### ISSUE THREAD

**Issue by quangbuule** [webpack/webpack#1670]
I got error when trying to use `qs` package with UglifyJsPlugin

```
ERROR in js/vendor.js from UglifyJs
Unexpected token name «i», expected punc «;» [./~/qs/lib/utils.js:14,0]
```

I don't know what's wrong with the code
https://github.com/hapijs/qs/blob/master/lib/utils.js#L14

**Comment by farneman** [comment]
It appears from https://github.com/mishoo/UglifyJS2/issues/448 that UglifyJS does not properly support ES2015/ES6 syntax yet. I'm guessing that probably your issue if you're not running your code through a transpiler before it hits the Uglify plugin.

**Comment by craigbeck** [comment]
Just ran into this as well. I by default exclude `node_modules` except for a few problem children. My loaders have entries like this:

```js
[
    { test: /\.jsx?$/, exclude: /node_modules/, loaders: ["react-hot", "babel?optional[]=runtime&stage=1"] },
    { test: /node_modules\/(jws|jwa|qs)\/.*\.js$/, loaders: ["babel?optional[]=runtime&stage=1"] },
    // other loaders...
]
```

**Comment by lemonCMS** [comment]
@craigbeck thx, you saved my day!
