### ISSUE TITLE
Analyse tool does not work

### ISSUE THREAD

**Issue by jeron-diovis** [webpack/webpack#1672]
Just tried to upload my profile to http://webpack.github.io/analyse.
Got this:
![screenshot 2015-11-26 10 44 16](https://cloud.githubusercontent.com/assets/2756868/11418588/dcb3fa16-9429-11e5-9f32-98957a04e11b.png)
And nothing more happens.

**Comment by bebraw** [comment]
Are you using webpack 1 or 2? Can you provide a simplified version of your *stats.json* (no need to have private info)?

**Comment by jeron-diovis** [comment]
@bebraw webpack 1.12.2
Here is a fragment: http://dpaste.com/0FKRZVF
It causes same error.

**Comment by bebraw** [comment]
Confirmed.

If you feel like debugging, you can try to [run the tool locally](https://github.com/webpack/analyse). Maybe that will give better idea. The error just tells me it expects an array where there is none. Perhaps adding a check against that case would do the trick.

Note that the analyse tool will be rebuilt. If you want to follow the progress, subscribe [here](https://github.com/webpack/analyse-tool).

**Comment by bebraw** [comment]
Just noticed there's already [an issue for this](https://github.com/webpack/analyse/issues/18) so I'm closing this one in favor of that.
