### ISSUE TITLE
createRequire not detected when imported with `node:` prefix

### ISSUE THREAD

**Issue by tripodsan** [webpack/webpack#16724]
# Bug report

**What is the current behavior?**

using `createRequire` isn't detected when imported with `node:` prefix. i.e. the imported module is not resolved.

**If the current behavior is a bug, please provide the steps to reproduce.**

A dependency (`@adobe/fetch`) uses createRequire to import the package.json:

```js
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const pkg = require('../../package.json');
```

the generated bundle contains:

```js
const require = (0,node_module__WEBPACK_IMPORTED_MODULE_0__.createRequire)("file:///..../node_modules/@adobe/fetch/src/core/request.js");
const pkg = require('../../package.json');
```

which doesn't work, since the `package.json` will not be available once using the bundle.

when we change the import and remove the `node:` prefix:

```js
import { createRequire } from 'module';
const require = createRequire(import.meta.url);
const pkg = require('../../package.json');
```

then bundle package.json is resolved and included in the bundle:

```js
const require = /* createRequire() */ undefined;
const pkg = __webpack_require__(/*! ../../package.json */ "./node_modules/@adobe/fetch/package.json");
```

**What is the expected behavior?**

`createRequire` should be detected even if it's imported via the `node:module` prefix. 

**Other relevant information:**
webpack version:  5.75.0
Node.js version: 18.13.0
Operating System: macOS

**Comment by alexander-akait** [comment]
@tripodsan Sorry for delay, is your target `node`? Can you show me your `resolver` value?

**Comment by tripodsan** [comment]
hi @alexander-akait, how can I obtain that? here's our webpack config:
https://github.com/adobe/helix-deploy/blob/a50182b1a0b4c50bc5d9e1dc6bca7245157dcbb1/src/bundler/WebpackBundler.js#L72-L81

**Comment by alexander-akait** [comment]
Yeah, bug...

**Comment by alexander-akait** [comment]
I think due https://github.com/webpack/webpack/issues/14166 :smile: I will look can we fix it, because it is easy to catch due `node:` prefix

**Comment by alexander-akait** [comment]
Fix - https://github.com/webpack/webpack/pull/16904
