### ISSUE TITLE
Externals not added as dependencies when building AMD modules using require

### ISSUE THREAD

**Issue by thebreiflabb** [webpack/webpack#1673]
I came across an issue with one of our big projects, when I was bundling an AMD module. The module will be used by another project which already uses these external dependencies.

External dependencies does not become a part of the define dependency array if the external dependency is not a part of the main entry point dependencies. Leading to `Uncaught ReferenceError: __WEBPACK_EXTERNAL_MODULE_X__ is not defined`

I have created a simple project which displays this issue below

Example:
https://github.com/thebreiflabb/webpack-amd-test

[`webpack-config.js`](https://github.com/thebreiflabb/webpack-amd-test/blob/master/webpack-config.js)
```javascript
var config = {
	context: './src',
	entry: {
		main1: 'main1.js',
		main2: 'main2.js'
	},
	output: {
		filename: '[name].bundle.js',
		path: './dist',
		publicPath: 'dist/',
		libraryTarget: 'amd'
	},
	externals: {
		jquery: 'jquery',
		backbone: 'backbone',
		underscore: 'underscore'
	},
	resolve: {
		root: './src'
	}
};

module.exports = config;
```

[`src/main2.js`](https://github.com/thebreiflabb/webpack-amd-test/blob/master/src/main2.js)
```javascript
define(['underscore'], function(_) {
	console.log('main2 loaded');

	return function() {
		require(['modules/other2'], function(other) {
			console.log('other from main2 loaded');
			alert('main2 loaded, result from other: ' + other());
		});
	}
});
```

[`src/modules/other2.js`](https://github.com/thebreiflabb/webpack-amd-test/blob/master/src/modules/other2.js)
```javascript
define(['jquery', 'backbone'], function($, Backbone) {
	return function() {
		return 10;
	}
});
```

This fails on runtime, because [`src/modules/other2.js`](https://github.com/thebreiflabb/webpack-amd-test/blob/master/src/modules/other2.js)'s external dependencies cannot be loaded. If however the `other2` dependency becomes a part of the entry point's define dependency array, it works fine:

[`src/main1.js`](https://github.com/thebreiflabb/webpack-amd-test/blob/master/src/main1.js)
```javascript
define(['underscore', 'modules/other'], function(_, other) {
	console.log('main1 loaded');
	console.log('other from main1 loaded');

	return function() {
		alert('main1 loaded, result from other: ' + other());
	}
});
```

[`src/modules/other.js`](https://github.com/thebreiflabb/webpack-amd-test/blob/master/src/modules/other.js)
```javascript
define(['jquery'], function($) {
	return function() {
		return 3;
	}
});
```

**Comment by luqin** [comment]
+1

**Comment by tomasAlabes** [comment]
+1
