### ISSUE TITLE
topLevelAwait is still under experimental section

### ISSUE THREAD

**Issue by iSokrat** [webpack/webpack#16738]
## Feature request

According to the latest docs, `topLevelAwait` should be used via `experimental` [section](https://webpack.js.org/configuration/experiments/). In the same time, top level await is already a part of [specification](https://tc39.es/ecma262/#sec-async-function-definitions) (stage 4). I think it's time already to remove it from experimental section.

**What is the expected behavior?**

Excluded `topLevelAwait` from `experimental` section.

**What is motivation or use case for adding/changing the behavior?**

No reason to consider this feature as experimental since it's already in specification.

**How should this be implemented in your opinion?**

Just exclude this option and this behaviour should be enabled by default.

**Are you willing to work on this yourself?**
no

**Comment by alexander-akait** [comment]
Hello, yeah, you are right, I think we can enable it by default

@TheLarkInn What do you think?

**Comment by iSokrat** [comment]
@alexander-akait @TheLarkInn Hello, are there any updates?

**Comment by alexander-akait** [comment]
@iSokrat  Yeah, do you want to send a PR, I think we are ready to enable it by default

**Comment by iSokrat** [comment]
@alexander-akait  Didn't plan to do this is initially, maybe, some day I could do this but not for now. In case if there is someone else who wants to do this - feel free to prepare needed changes
