### ISSUE TITLE
"_interopRequireDefault" is not wrapping 'default' keyword in quotes anymore

### ISSUE THREAD

**Issue by simonvizzini** [webpack/webpack#1674]
I have updated webpack from 1.12.2 to 1.12.4 (and now also tried the latest 1.12.9), and I have noticed an issue in IE8 since the update, causing "Expected identifier, string, or number" errors to be thrown by IE8. The function ``_interopRequireDefault`` is not wrapping the ``default`` keyword in quotes anymore.

This is what 1.12.2 did output:
``function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { 'default': obj }; }``

And this is what 1.12.4 and 1.12.9 outputs:
``function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }``

Only difference are the missing quotes.

**Comment by simonvizzini** [comment]
Looks like quotes are missing everywhere where a default export is being imported.

For example my cookie utility function used to get compiled to this:
````javascript
if (_utilsCookies2['default'].hasCookie(COOKIE_NAME)) {
	state = JSON.parse(_utilsCookies2['default'].getCookie(COOKIE_NAME));
}
````

but now it looks like this:
````javascript
if (_cookies2.default.hasCookie(COOKIE_NAME)) {
	state = JSON.parse(_cookies2.default.getCookie(COOKIE_NAME));
}
````

**Comment by SimenB** [comment]
That's babel, not webpack. You probably upgraded to babel 6, or a dep did

**Comment by simonvizzini** [comment]
Ah I see, thanks for letting me know! I thought this function is related to the other ``__webpack_*`` functions. I will report it in the babel repository then, thanks!

**Comment by SimenB** [comment]
For completeness, [this](http://babeljs.io/docs/plugins/transform-es3-property-literals/) is the plugin you want

**Comment by ian-r-johnson** [comment]
Just in case you still needed this or anyone else like I did.

The plugin you are looking for is: 

http://babeljs.io/docs/plugins/transform-es3-property-literals/

**Comment by sirugh** [comment]
The transform for member expression literals doesn't seem to be working.

```
var _foo = __webpack_require__(1);
var _foo2 = _interopRequireDefault(_foo);
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { 'default': obj }; }

new _foo2.default();
```

The `default` property is protected in the generated `interopRequireDefault` function but not in the generated accessing code.

**Comment by SimenB** [comment]
Known bug. https://phabricator.babeljs.io/T2817

**Comment by sirugh** [comment]
And similarly: https://phabricator.babeljs.io/T6863

Thanks.

**Comment by aniddan** [comment]
+ 1
