### ISSUE TITLE
Built file with webpack outputs entire built content  

### ISSUE THREAD

**Issue by brunolnetto** [webpack/webpack#16751]
I built a Node module with webpack and hosted on [npmjs](https://www.npmjs.com/package/arqeo). The resulting code is very compact, even when I use `js-beautifier` on it. However, when I try to user-test an error scenario, it outputs the WHOLE one-line code, which is quite ugly in my opinion.

![image](https://user-images.githubusercontent.com/13961685/220445759-0c3f62d9-bc9d-4c86-ad7b-525897079dfd.png)

I know it is nit-picky, but do you have any advice, inside or outside webpack, to avoid the above unnecessary sausage-code output?

**Comment by alexander-akait** [comment]
Please set https://webpack.js.org/configuration/optimization/#optimizationminimize to `false` to disable such optimization for the production usage, thank you and feel free to feedback

**Comment by brunolnetto** [comment]
This is me now.

![image](https://user-images.githubusercontent.com/13961685/223754720-90a36a7e-096d-4cd6-8ebf-836ed058579d.png)
