### ISSUE TITLE
Types: `target` not available on loader context

### ISSUE THREAD

**Issue by askoufis** [webpack/webpack#16753]
# Bug report

**What is the current behavior?**

The `target` property is not available on the `LoaderContext` (`this`) type, despite [the documentation stating that it should be there](https://webpack.js.org/api/loaders/#thistarget), and my experience with an existing loader that successfully accesses this property at runtime.

**If the current behavior is a bug, please provide the steps to reproduce.**

Import the `LoaderContext` type and try to access the `target` property.
```ts
import { type LoaderContext } from 'webpack';

const myLoader = (this: LoaderContext<any>) => {
  console.log(this.target); // TypeScript error: Property 'target' does not exist on type 'LoaderContext<any>'
}
```

**What is the expected behavior?**

The property should be accessible on the type and there should be no TypeScript error.

**Other relevant information:**
webpack version:  `5.75.0`
Node.js version: `16.19.0`
Operating System: MacOS 13.1
Additional tools: `pnpm`

**Comment by TheLarkInn** [comment]
@askoufis Would you be willing to submit a fix here?! The `loaderContext` types last I remember are manually typed here: 

https://github.com/webpack/webpack/blob/b7fc4d876deb958d7ee81ecc00a312e39a354a44/declarations/LoaderContext.d.ts#L1-L58

**Comment by TheLarkInn** [comment]
See `yarn special-lint-fix` command for type generation.
