### ISSUE TITLE
When compiling dynamic async import(), webpack always return package under default property

### ISSUE THREAD

**Issue by rdsedmundo** [webpack/webpack#16757]
# Bug report

Webpack will always transpile `await import('module')` into a syntax that returns `{default: module}` even if the importing module doesn't have a default export.

**What is the current behavior?**
```ts
import assert from 'node:assert';

async function handler() {
  const { Readable } = await import('node:stream');
  assert(typeof Readable !== 'undefined', 'Readable is undefined.');
}

void handler();
```

Real world use case, I'm using a package which does dynamic import, and I'm unable to bundle it with webpack for this solely reason: https://github.com/puppeteer/puppeteer/issues/8531.

I tried to use a loader like this one: https://github.com/morganney/magic-comments-loader to add `/*webpackIgnore: true*/` to any dynamic imports, but it's super slow, unfortunately.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Install repo: https://github.com/rdsedmundo/webpack-bug-dynamic-import-default
2. Run `npm test`.

**What is the expected behavior?**

I realize this may be expected behavior due to design limitations (found a few references to this on the documentation as outlined below), but I was wondering if there are any workarounds on this besides marking the package as an external. It feels overkill that no matter which package it is, if they try to use a dynamic import on this fashion, then we automatically need to skip bundling it completely.

https://webpack.js.org/guides/code-splitting/
> The reason we need default is that since webpack 4, when importing a CommonJS module, the import will no longer resolve to the value of module.exports, it will instead create an artificial namespace object for the CommonJS module. For more information on the reason behind this, read [webpack 4: import() and CommonJs](https://medium.com/webpack/webpack-4-import-and-commonjs-d619d626b655).

https://webpack.js.org/guides/lazy-loading/
> Note that when using import() on ES6 modules you must reference the .default property as it's the actual module object that will be returned when the promise is resolved.

**Other relevant information:**
webpack version: 5.75.0
Node.js version: 18.13.0
Operating System: macOS 13.1
Additional tools: N/A

**Comment by TheLarkInn** [comment]
This is a bit of an unsavory user experience. This needs a bit of discussion to see how this could be addressed.

**Comment by TheLarkInn** [comment]
We need to potentially change how this is accessed as default only/not. Potentially bug.

**Comment by kgram** [comment]
I spent quite a while digging before finding this issue. For other people searching, I'll include the error produced by puppeteer, to hopefully lead them straight to an explanation:

```
TypeError: Readable is not a constructor
```

As far as I can tell, this stems from legacy nodejs behavior regarding the `stream`-module. When using `require`, the returned module is a function (this is not the case with `import('stream')`, which is also confusing in and off itself). Since functions are objects too, properties like `Readable` can still be accessed without issue. Without this legacy behavior, modules such as [send](https://www.npmjs.com/package/send), which is used widely in server-libraries, breaks completely, so hacks with externals, alias etc. to only expose the non-legacy exports cannot be used.

The problem arises when webpack tries to create a fake namespace object for the module. Since the module is not an object, but a function, it is assumed that it should instead be treated as the default-export. It's hard to see a simple fix that will allow webpack to create fake namespace objects for legacy modules and not break on this, except if all native modules could be excepted from the fake namespace behavior. Maybe it could look for custom properties on function-exports as well, but there might be tons of ways this could break for other modules.

The solution I ended up with is a god-awful hack, but it works: a babel plugin to inject `/* webpackIgnore: true */`-comments into dynamic imports where the source matches a predefined list. If there's interest, I may publish it as a module, or someone else with experience creating and maintaining babel plugins may do so freely. It's unlikely to have real applications outside of this single issue, but you never know.

```js
/**
 * Add webpackIgnore-comments to dynamic imports matching a specific list.
 * Primarily useful for avoiding problematic handling of the `stream` module by
 * webpack.
 *
 * Provide a list of targeted modules as the `ignore`-option.
 * 
 * Related webpack-issue: https://github.com/webpack/webpack/issues/16757
 */
module.exports = ({ template, types }) => ({
	visitor: {
		Import(path, { opts: { ignore = [] } = {} }) {
			// Check if import statement seems to be completely straightforward, single string argument, no leading comments
			if (path.parent.arguments.length !== 1) return
			const source = path.parent.arguments[0]
			if (!types.isStringLiteral(source) || source.leadingComments) return
			// Check if module should be ignored
			if (!ignore.includes(source.value)) return
			types.addComment(source, 'leading', ' webpackIgnore: true ')
		}
	}
})
```

Usage in babel config (I would recommend a JS config, so `require.resolve` can be used for an absolute path to the plugin-file):

```json
["./path-to-ignore-plugin", { ignore: ["stream"] }]
```

Make sure that your babel-loader is run on puppeteer-files (and any other modules with the same issue).

**Comment by rdsedmundo** [comment]
@TheLarkInn would you mind linking the discussion here if you have already created it? I couldn't seem to find it.

**Comment by botlikes456** [comment]
I encountered the same issue. When using `Nest.js` and `Puppeteer`, following the `Nest.js` documentation, if I start with the `nest start` command, there are no problems. However, if I build using `nest build --webpack`, I get a runtime exception like the following:

```log
2023-12-11T15:06:29.808Z [PrintSync] [ERROR] Readable is not a constructor TypeError: Readable is not a constructor
    at getReadableFromProtocolStream (/path-to-project/dist/npm/puppeteer-core.js:24018:12)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async CdpPage.createPDFStream (/path-to-project/dist/npm/puppeteer-core.js:18260:16)
    at async CdpPage.pdf (/path-to-project/dist/npm/puppeteer-core.js:18264:26)
    at async PrintPdfPipelineStep.printPdf (/path-to-project/dist/npm/290.js:5664:25)
    at async PrintPdfPipelineStep.doPerform (/path-to-project/dist/npm/290.js:5687:22)
    at async /path-to-project/dist/npm/290.js:3460:28
    at async PrintPdfPipelineStep.performAndCatch (/path-to-project/dist/npm/290.js:3451:20)
    at async PrintPdfPipelineStep.perform (/path-to-project/dist/npm/290.js:3459:16)
    at async steps.reduce.Promise.resolve.content (/path-to-project/dist/npm/290.js:3508:34)
    at async /path-to-project/dist/npm/290.js:3505:30
    at async PipelineStepSets.performWithContext (/path-to-project/dist/npm/290.js:3499:16)
    at async PipelineStepSets.doPerform (/path-to-project/dist/npm/290.js:3502:16)
    at async /path-to-project/dist/npm/290.js:3460:28
    at async PipelineStepSets.performAndCatch (/path-to-project/dist/npm/290.js:3451:20)
    at async PipelineStepSets.perform (/path-to-project/dist/npm/290.js:3459:16)
```

If I add the following configuration in `webpack.config.js`, then there are no issues at all. After observing the compiled output files, it is evident that after adding the configuration, `Puppeteer` and its dependencies are not included in the compilation process, and no compiled files are generated. Instead, the packages are still referenced from the `node_modules` directory. I suspect this is why `nest start` can run without any problems.

```javascript
externals: {
  puppeteer: "require('puppeteer')"
},
```

**Comment by bradwoo8621** [comment]
I encountered the same issue. When using `Nest.js` and `Puppeteer`, following the `Nest.js` documentation, if I start with the `nest start` command, there are no problems. However, if I build using `nest build --webpack`, I get a runtime exception like the following:

```log
2023-12-11T15:06:29.808Z [PrintSync] [ERROR] Readable is not a constructor TypeError: Readable is not a constructor
    at getReadableFromProtocolStream (/path-to-project/dist/npm/puppeteer-core.js:24018:12)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async CdpPage.createPDFStream (/path-to-project/dist/npm/puppeteer-core.js:18260:16)
    at async CdpPage.pdf (/path-to-project/dist/npm/puppeteer-core.js:18264:26)
    at async PrintPdfPipelineStep.printPdf (/path-to-project/dist/npm/290.js:5664:25)
    at async PrintPdfPipelineStep.doPerform (/path-to-project/dist/npm/290.js:5687:22)
    at async /path-to-project/dist/npm/290.js:3460:28
    at async PrintPdfPipelineStep.performAndCatch (/path-to-project/dist/npm/290.js:3451:20)
    at async PrintPdfPipelineStep.perform (/path-to-project/dist/npm/290.js:3459:16)
    at async steps.reduce.Promise.resolve.content (/path-to-project/dist/npm/290.js:3508:34)
    at async /path-to-project/dist/npm/290.js:3505:30
    at async PipelineStepSets.performWithContext (/path-to-project/dist/npm/290.js:3499:16)
    at async PipelineStepSets.doPerform (/path-to-project/dist/npm/290.js:3502:16)
    at async /path-to-project/dist/npm/290.js:3460:28
    at async PipelineStepSets.performAndCatch (/path-to-project/dist/npm/290.js:3451:20)
    at async PipelineStepSets.perform (/path-to-project/dist/npm/290.js:3459:16)
```

If I add the following configuration in `webpack.config.js`, then there are no issues at all. After observing the compiled output files, it is evident that after adding the configuration, `Puppeteer` and its dependencies are not included in the compilation process, and no compiled files are generated. Instead, the packages are still referenced from the `node_modules` directory. I suspect this is why `nest start` can run without any problems.

```javascript
externals: {
  puppeteer: "require('puppeteer')"
},
```

**Comment by bradwoo8621** [comment]
The issue has been finally resolved as follows, instead of using the standard import in the reference.

Original:

```typescript
import puppeteer, {Browser, PaperFormat, PDFOptions, Viewport} from 'puppeteer';
```

Change to:

```typescript
import {Browser, PaperFormat, PDFOptions, Viewport} from 'puppeteer-core/lib/cjs/puppeteer/puppeteer-core.js';
import puppeteer from 'puppeteer/lib/cjs/puppeteer/puppeteer.js';
```

it works for me. @rdsedmundo
