### ISSUE TITLE
Sourcemaps contain invalid source webpack/bootstrap

### ISSUE THREAD

**Issue by frapontillo** [webpack/webpack#1676]
When generating external sourcemaps (`'source-map'`), the resulting map files has, as first element in the `sources` array, something like `"webpack:///webpack/bootstrap 170846d63e93fb4a12c6"`.
This causes the impossibility to further reprocess the sourcemaps with other tools, as it introduces an invalid file that doesn't exist on the file system.

Is this something that can be fixed?
Thanks.

**Comment by pksjce** [comment]
This issue was moved to webpack/webpack.io#143

**Comment by djskinner** [comment]
For any future travelers, this StackOverflow answer offers some explanation of why this entry appears: https://stackoverflow.com/a/45068039/120497
