### ISSUE TITLE
ESM file in cache buildDependencies

### ISSUE THREAD

**Issue by zdm** [webpack/webpack#16769]
Hi.
I need to add ESM file as build dependency, but seems it is not suppported.

I added full path to the target file, but `filesystem` cache is not created. 
When I removed this dependency - everything works as it should.
CommonJS dependencies also works fine.

This is bug?

**Comment by alexander-akait** [comment]
It should work please provide reproducible exampe, thank you

**Comment by zdm** [comment]
Hmm, it works now.
