### ISSUE TITLE
Webpack 5 incorrectly compiles CJS module `marked`

### ISSUE THREAD

**Issue by laustdeleuran** [webpack/webpack#16776]
# Bug report

## What is the current behavior?

When loading [`marked`](https://github.com/markedjs/marked) (CJS) through a [`pnpm`](https://pnpm.io/) monorepo package with Webpack 5, it compiles incorrectly. `marked` compiles to:

```js
/***/ "../node_modules/.pnpm/marked@4.2.12/node_modules/marked/lib/marked.cjs":
/*!******************************************************************************!*\
  !*** ../node_modules/.pnpm/marked@4.2.12/node_modules/marked/lib/marked.cjs ***!
  \******************************************************************************/
/***/ ((module, __unused_webpack_exports, __webpack_require__) => {

"use strict";
module.exports = __webpack_require__.p + "static/media/marked.79f9f27bbd94805ba150.cjs";

/***/ }),
```

According to the maintainers of `marked` [this looks like a bug in Webpack](https://github.com/markedjs/marked/issues/2265#issuecomment-1454358096). 

## If the current behavior is a bug, please provide the steps to reproduce.

There's a minimal repo showcasing the bug here: 
https://github.com/laustdeleuran/marked-2265-module-import-export-issue

And some deeper context in this issue in `marked`: 
https://github.com/markedjs/marked/issues/2265#issuecomment-1451124186

## What is the expected behavior?

`marked` gets compiled correctly. 

## Other relevant information:
**webpack version:** 5
**Node.js version:** 14 or 16
**Operating System:** MacOS
**Additional tools:** [`pnpm`](https://pnpm.io/) and [`create-react-app`](https://create-react-app.dev/)

**Comment by laustdeleuran** [comment]
Haven't dug too deep, but it looks like this might be related to #16680 or #16570

**Comment by UziTech** [comment]
It looks like this might have something to do with webpack incorrectly compiling `.cjs` files in packages that are `"type": "module"`

In @laustdeleuran's [repo](https://github.com/laustdeleuran/marked-2265-module-import-export-issue), If I remove `"type": "module"`  and rename `marked.cjs` to `marked.js` everything works fine.

Detailed Steps to reproduce:

1. Open repo https://github.com/laustdeleuran/marked-2265-module-import-export-issue
2. Run `pnpm i`
3. Open File `/node_modules/.pnpm/marked@4.2.12/node_modules/marked/package.json`
4. Edit line 24
   ```diff
   - "default": "./lib/marked.cjs"
   + "default": "./lib/marked.js"
   ```
5. Remove line 6
   ```diff
   - "type": "module",
   ```
6. Rename File
   ```diff
   - /node_modules/.pnpm/marked@4.2.12/node_modules/marked/lib/marked.cjs
   + /node_modules/.pnpm/marked@4.2.12/node_modules/marked/lib/marked.js
   ```
7. Run `cd some-cra`
8. Run `pnpm start`

**Comment by laustdeleuran** [comment]
Any update on this, @Webpack? Seems like we have a legit bug here with minimal repros, steps to reproduce and a potential path for resolution. Is there anything else we can do to move this forward? Thanks!

**Comment by laustdeleuran** [comment]
Hm, seems like this might actually be an issue in `create-react-app`: https://github.com/webpack/webpack/issues/16776

**Comment by alexander-akait** [comment]
@laustdeleuran Can you reproduce this bug without CRA? Because we have tests for these cases

**Comment by laustdeleuran** [comment]
@alexander-akait Sorry for the noise. After some more investigation, I do think this is a `create-react-app` issue and not a `webpack` issue. 

There's some more context in https://github.com/facebook/create-react-app/issues/12700, including a couple of PRs to solve this issue, as well as a couple of workaround. 

Closing this issue.
