### ISSUE TITLE
jQuery object visibility with ProvidePlugin

### ISSUE THREAD

**Issue by scabbiaza** [webpack/webpack#1678]
Hello, guys!

I have a question about including jQuery with `ProvidePlugin`.
```js
var Webpack = require('webpack');

module.exports = {
  entry: {
    vendors: './src/vendors.js',
    app: './src/app.js'
  },
  output: {
      filename: 'dist/[name].js'
  },
  module: {
    loaders: [
      // JS
      {test: /\.(js(\?.*)?)$/, loaders: ["babel?stage=0"]},
    ]
  },
  plugins: [
    new Webpack.ProvidePlugin({
        $: "jquery",
        jQuery: "jquery",
    })
  ],
};
```

As from what i understood, each bundle will have own version of the jQuery object, and not the global one.

Let me write the code to be clear.

`index.html`
```html
<html>
    <body>
        <script src="dist/vendors.js"></script>
        <script src="dist/app.js"></script>
    </body>
</html>
```

I have two bundles: `vendors.js` and `app.js`.
`vendors.js` includes `select2` library, that adds itself as a function to jQuery object.

(Select2 is here just for the example)
https://github.com/select2/select2/blob/stable/3.5/select2.js
```js
...
$.fn.select2 = function () { ...}
...
```

`vendors.js`
```js
import "./select2.js";
console.log("VENDORS.JS: $.fn.select2: ", $.fn.select2); // function exists
```

And then I want to have access in `app.js` to the select2.
```js
$(document).ready(function(){
	console.log("APP.JS: $.fn.select2:", $.fn.select2); // function doesn't exist
});
```

Is it possible?

**Comment by farneman** [comment]
From the ProvidePlugin docs:
>Module (value) is loaded when the identifier (key) is used as free variable in a module. The identifier is filled with the exports of the loaded module.

So as I understand it everywhere you're using `$` in your `vendors.js` or `app.js` files Webpack is setting the `$` var to equal the jQuery module object. Since it's essentially instantiated each time, the select2 function added in `vendors.js` is on a different copy of the jQuery object than the one you get in `app.js`.

**Comment by sokra** [comment]
>         <script src="dist/vendors.js"></script>
>         <script src="dist/app.js"></script>

You need to use the `CommonsChunkPlugin` here, elsewise you'll have multiple webpack runtimes on the page. This will also fix the jquery issue.

**Comment by scabbiaza** [comment]
Thank you guys! It's clear now.

**Comment by f3l1x** [comment]
I have exactly the same problem.

```json
	entry: {
		vendor: './www/assets/js/vendor.js',
		app: './www/assets/js/app.js'
	},
```

```json
	plugins: [
		new webpack.optimize.CommonsChunkPlugin({
			name: "vendor",
			minChunks: Infinity
		}),
		new webpack.ProvidePlugin({
			$: "jquery",
			jQuery: "jquery",
			'window.jQuery': "jquery",
			'window.$': "jquery"
		}),
		new ExtractTextPlugin("[name].css")
	],
```

The **CommonsChunkPlugin** helps.
