### ISSUE TITLE
Add `{ withFileTypes: boolean }` options type on `compiler.inputFileSystem.readdir`

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack#16780]
Today `compiler.inputFileSystem.readdir` doesn't include the type information for passing `{withFileTypes: boolean}` options parameter. This is useful if you are leveraging inputFileSystem for and you want to read `Dirint` objects instead of `string | buffer` types. 

This is low hanging fruit that anyone could contribute to. Location to code: https://github.com/webpack/webpack/blob/main/lib/util/fs.js#L113-L205

**Comment by TheLarkInn** [comment]
In addition we should try and flesh out the `fs` API as much as possible. We could look at the `graceful-fs` types or Node@x types and try to maintain compatibility across node versions.

**Comment by TheLarkInn** [comment]
Need to also update how enhanced-resolve handles these functions (not just a type update).

**Comment by fu1996** [comment]
"I am a new github user, and I want to try to solve this problem and strive to meet the PR standards.". If there is anything that does not meet the requirements, I hope to receive your correction and help. Thank you.  @TheLarkInn 

In addition, I have recently been learning the enhancement resolver library. I feel that this library is great, and I very much hope to make some modest contributions to it. The following content is related to my learning notes, which I have placed in some technical communities.

[01](https://juejin.cn/post/7167978104881676319?share_token=f3717888-314e-4876-a795-44469a2a2154)

[02](https://juejin.cn/post/7204356282588676156?share_token=6d647677-7fd2-48e1-8748-a882ba31b916)

**Comment by TheLarkInn** [comment]
https://github.com/webpack/enhanced-resolve/pull/374 

I think all that remains for this is to bump enhanced-resolve in webpack. @fu1996 we are doing a release of enhanced-resolve later today and someone can open a PR for updating.

**Comment by alexander-akait** [comment]
Fixed
