### ISSUE TITLE
require.ensure and es6 modules bug

### ISSUE THREAD

**Issue by pavel06081991** [webpack/webpack#1680]
Here is my code:

app.js:
```javascript
require.ensure([], function (require) {
  var mod = require('./myModule');
});
```

myModule.js:
```javascript
var myModudeValue = 10;

export default myModuleValue;
```

In the var mod of app.jss file I do not get 10, I get object which has property default which equals 10.
Why do not I have value 10 inside mod variable, but I have this value inside mod.default?

**Comment by farneman** [comment]
Based on your (I'm assuming psuedo) code above I'm getting the value of `mod` as 10 and type number. Can you provide some more information about your scenario?

**Comment by pavel06081991** [comment]
Sure. I have module myFirstModule.js:
```javascript
var myFirstModule = angular.module('FirstModule', []);

export default myFirstModule;
```

And I have module mySecondModule.js:
```javascript
import myFirstModule from './myFirstModule';

var mySecondModule = angular.module('SecondModule', [myFirstModule.name]);

export default mySecondModule;
```

Now all works good, because in mySecondModule.js variable myFirstModule.name will be converted to _SOMENEWVARNAME_.default.name

But if I use require.ensure enstead of import, myFirstModule.name will not be converted to _SOMENEWVARNAME_.default.name, so myFirstModule.name returns undefined.

**Comment by farneman** [comment]
Being unfamiliar with Angular modules it's hard for me to provide any further help. That being said, my guess is that `angular.module` doesn't play nice with the async dependencies that `require.ensure` provides or at least not the way you're attempting to define them.

**Comment by pavel06081991** [comment]
It does not depend on angular. You can just do like this:
```javascript
var myModule = {name: 'myModule'};
export default myModule;
```
and you will have the same problem. Tomorrow I'll try to make some files with code and you will see it better.

**Comment by pavel06081991** [comment]
I found out. It is because of babel. Here you can read about this http://stackoverflow.com/questions/33505992/babel-6-changes-how-it-exports-default
