### ISSUE TITLE
async module loading and waiting for its dependencies are resolved

### ISSUE THREAD

**Issue by pavel06081991** [webpack/webpack#1682]
When you use require.js library then if you define module, for example like this:

myFirstModule.js:

``` javascript
define(['mySecondModule'], function(mySecondModule) {
    var mySecondModuleExport = 10;

    ... // some code

    return mySecondModuleExport;
});
```

If some module in its dependency has mySecondModule, then mySecondModule will be async loaded.

But in webpack it is not loaded async, it is just added to a bundle. It is first of all strange and it is bad for me, because using require.ensure does not solve my issue.

I want for each module to have its own chunk. It is said in documentation it is necessary to use require.ensure for this. I'll describe why require.ensure is not suitable. 

I have myFirstModule.js:

``` javascript
myFirstModuleExport = 10;

require.ensure([], function(require) {
    var mySecondModule = require('mySecondModule');

    // here we do something when mySecondModule is resolved
});

module.exports = myFirstModuleExport;
```

myFirstModule.js:

``` javascript
var myFirstModuleExport;

require.ensure([], function(require) {
    var myThirdModule = require('myThirdModule');

    myFirstModuleExport = myThirdModule();
});

module.exports = myFirstModuleExport; // here I have to export some value which depends on myThirdModule, but when module.exports line will be executed, myThirdModule is not even resolved.
```

So, tell me please how to define module for it:
1) to have its own chunk
2) to be not resolved until its dependencies are not resolved?

**Comment by pavel06081991** [comment]
In other words here is code:

myFirstModules.js
```javascript
define(['./mySecondModule'], function(mySecondModule) {
  var myFirstModuleExports = mySecondModule();

  return myFirstModuleExports;
});
```
I want for './mySecondModule' to be set in additional separate chunk. And myFirstModules must not be resolved until './mySecondModule' is async loaded and resolved.

**Comment by sokra** [comment]
It makes no sense to load the dependencies of `define` on demand. The remaining code would wait. It's more performant to load them together in one chunk.

**Comment by pavel06081991** [comment]
I'll better give you example for what it is necessary. Imagine that we have module menu.js:
```javascript
var appConfig = require('appConfig');

require('promise?bluebird!./themes/' + appConfig.currentTheme + '/ltr/menu.sass');
var menuTpl = require('menu.html');
... // here is js code of menu

function someMethodOfMenu()  {
	...
}

var api = {
	someMethodOfMenu: someMethodOfMenu
};

module.exports.menuTpl = menuTpl;
module.exports.api = api;
```
As you can see my site can have lots of css themes and current theme is loaded dynamically. When you require menu.js module, then you will add menuTpl to DOM and user will see html of menu, but styles are still not loaded, so user sees nacked html.
Then styles will be loaded and applied and menu will look good.

So if there were opportunity not to resolve menu.js module until its css theme file is loaded, it would be great because the user would not see nacked html.

**Comment by denich** [comment]
I've faced with similar issue. 
Is there any updates here?

**Comment by pavel06081991** [comment]
@sokra, you said "It makes no sense to load the dependencies of define on demand. The remaining code would wait. It's more performant to load them together in one chunk.". But now we have http 2.0 and native es6 modules will behave like AMD modules. So are you planning to add support for first loading module dependencies(es6 imports) and only when all dependencies are resolved, run module code? In other words are you planning to add the same behaviour as es6 modules have.

**Comment by nezed** [comment]
@pavel06081991 you want to use asynchronous provide which is not able in Webpack.
You can use [yms](https://github.com/ymaps/modules) or RequireJS workaround

[More about yms (RU)](https://events.yandex.ru/lib/talks/3682/)
