### ISSUE TITLE
Fix v8 Deopt in ModuleGraph due to `wrong map` 

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack#16829]
ModuleGraph.js causes a v8 deoptimization here: 

https://github.com/webpack/webpack/blob/b7fc4d876deb958d7ee81ecc00a312e39a354a44/lib/ModuleGraph.js#L136-L147

### Isolate Log File Snippet

```log
LoadIC,0x6551df9bde,16223580,563,20,1,P,0x01ad7455adf9,_getModuleGraphModule,,
code-deopt,16223649,640,0x1dc8d5a8320,-1,3848,deopt-eager,<C:\\Users\\selarkin\\Code\\webpack\\lib\\ModuleGraph.js:138:18>,wrong map
```

This is because `freeze()` method is introducing a new property to the ModuleGraph instance (`this._cacheStage`) after its already been initialized causing a Map transition and a "wrong map" deoptimization, preventing inline caching. 

Below shows the v8 Map of the object changing into Polymorphic caused by `freeze()` and causing a IC miss: 

### First Map Shape: Initialization
![image](https://user-images.githubusercontent.com/3408176/225157825-4d285bfb-0b9f-46b9-9cc5-96c716177233.png)

### Map Transition: `freeze()`
![image](https://user-images.githubusercontent.com/3408176/225157889-13a066d9-3497-4cbc-9d8a-f310c2f4dd58.png)

Initializing `this_cacheStage` in the constructor will fix this problem:

```javascript
class ModuleGraph {
	constructor() {
		/** @type {WeakMap<Dependency, ModuleGraphConnection>} */
		this._dependencyMap = new WeakMap();
		/** @type {Map<Module, ModuleGraphModule>} */
		this._moduleMap = new Map();
		/** @type {WeakMap<any, Object>} */
		this._metaMap = new WeakMap();

		/** @type {WeakTupleMap<any[], any>} */
		this._cache = undefined;

		/** @type {Map<Module, WeakTupleMap<any, any>>} */
		this._moduleMemCaches = undefined;

		/** @type {string} */
		this._cacheStage = undefined;
	}
	
```

**Comment by TheLarkInn** [comment]
@snitin315 if you are still looking for easy work, this one is super simple and up your alley!

**Comment by snitin315** [comment]
@TheLarkInn yes, I'll send a PR for this.
