### ISSUE TITLE
Assertion `(it) != (env->id_to_function_map.end())' failed. v5.76.1

### ISSUE THREAD

**Issue by mts** [webpack/webpack#16835]
# Bug report

**What is the current behavior?**
Following build error occurs when using `Webpack v5.76.1` which did not occur when using `Webpack v5.76.0`:
```bash
 webpack[17723]: ../src/module_wrap.cc:599:MaybeLocal<v8::Promise> node::loader::ImportModuleDynamically(Local<v8::Context>, Local<v8::Data>, Local<v8::Value>, Local<v8::String>, Local<v8::FixedArray>): Assertion `(it) != (env->id_to_function_map.end())' failed.
  1: 0x107f8f325 node::Abort() (.cold.1) [/usr/local/bin/node]
  2: 0x1068dbab9 node::Abort() [/usr/local/bin/node]
  3: 0x1068db861 node::Assert(node::AssertionInfo const&) [/usr/local/bin/node]
  4: 0x10689a7a1 node::loader::ImportModuleDynamically(v8::Local<v8::Context>, v8::Local<v8::Data>, v8::Local<v8::Value>, v8::Local<v8::String>, v8::Local<v8::FixedArray>) [/usr/local/bin/node]
  5: 0x106bdd40d v8::internal::Isolate::RunHostImportModuleDynamicallyCallback(v8::internal::MaybeHandle<v8::internal::Script>, v8::internal::Handle<v8::internal::Object>, v8::internal::MaybeHandle<v8::internal::Object>) [/usr/local/bin/node]
  6: 0x1070b9265 v8::internal::Runtime_DynamicImportCall(int, unsigned long*, v8::internal::Isolate*) [/usr/local/bin/node]
  7: 0x1074fe774 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvInRegister_NoBuiltinExit [/usr/local/bin/node]
 sh: line 1: 17723 Abort trap: 6           webpack --config webpack/webpack.release.babel.js --progress
```

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Switch to `Git v2.39.2`, `Node 19.8.0`, `NPM v9.5.1`
2. Clone reproduction [repo](https://github.com/papillonbits/dealer)
3. Check out to reproduction [branch](https://github.com/papillonbits/dealer/tree/webpack-5761-assertion-failed)
4. Run `npm run install-packages && npm run bootstrap-release` in terminal at repo root folder.
5. Check out the following build error in terminal: 
```bash
webpack[23589]: ../src/module_wrap.cc:599:MaybeLocal<v8::Promise> node::loader::ImportModuleDynamically(Local<v8::Context>, Local<v8::Data>, Local<v8::Value>, Local<v8::String>, Local<v8::FixedArray>): Assertion `(it) != (env->id_to_function_map.end())' failed.
```
![image](https://user-images.githubusercontent.com/28991521/225324786-6971e816-0d55-41a5-b2f1-52cf238a1fd3.png)
6. Check out webpack configuration [here](https://github.com/papillonbits/dealer/tree/webpack-5761-assertion-failed/packages/core/webpack) and [here](https://github.com/papillonbits/papillonbits/tree/master/packages/setup/src/webpack)

**What is the expected behavior?**
1. Webpack build should work just as the same as in the reproduction repo master [branch](https://github.com/papillonbits/dealer) which builds successfully using `Webpack v5.76.0`
2. Follow the following steps to try out the working version on repo master branch
   - `git reset --hard` in case any changes on current branch
   - `git checkout master`
   - Switch to `Git v2.39.2`, `Node 19.7.0`, `NPM v9.5.0` en run `npm run clean-up && npm run install-packages && npm run bootstrap-release` in terminal
   - Check out successful build results in terminal.

**Other relevant information:**
webpack version:  v5.76.1
Node.js version: 19.8.0, NPM v9.5.1
Operating System: MacOS Monterey
Additional tools: Git v2.39.2

**Comment by TheLarkInn** [comment]
This is actually a confirmed Node.js bug with version 19.8.0!

You can track the issue here: https://github.com/nodejs/node/issues/47096

Closing as not a webpack problem.

**Comment by mts** [comment]
@TheLarkInn Alright. Thank you for your swift response. Appreciated.
