### ISSUE TITLE
Is it possible to turn off replacement of "global"

### ISSUE THREAD

**Issue by Daniel15** [webpack/webpack#1683]
I have a module with code like this:
```
global.Foo = require('bar/foo');
```

The output from Webpack ends up looking something like this:
```
/* 0 */
/***/ function(module, exports, __webpack_require__) {

	/* WEBPACK VAR INJECTION */(function(global) {
	global.Foo = __webpack_require__(1);
	/* WEBPACK VAR INJECTION */}.call(exports, (function() { return this; }())))

/***/ },
```

But I want to actually have the resulting code explicitly reference `global` rather than replacing it with `function() { return this; }()`. How do I turn that off for this module?

**Comment by sokra** [comment]
see `node.global` option

**Comment by Daniel15** [comment]
:+1:

**Comment by stackOverMind** [comment]
This is the exact question I want to ask.
I am still confused that I can't find any document about the `node.global` option.Anybody help me?

**Comment by zhaoshengjun** [comment]
probably [this](https://nodejs.org/api/globals.html#globals_global)?

**Comment by stackOverMind** [comment]
thanks @zhaoshengjun ,but how?
My problem is to use `global` in none-node env.Usually assign `window` to `global`,what if I want to assign another varible to `global`?
in strict mode `(function(){return this})()` is sensored and return `undefined` so I want to replace `(function(){return this}())` with just a simple `window`.
Searched a lot,but still no luck

**Comment by aniruddhand** [comment]
@stackOverMind Did you get a solution for your problem? We want to do the same in our project i.e. to instruct webpack to use 'window' object instead of 'this'.

**Comment by diydyq** [comment]
[node
Include polyfills or mocks for various node stuff:

console: true or false
global: true or false
](https://webpack.github.io/docs/configuration.html)
