### ISSUE TITLE
TS2322: Type 'number' is not assignable to type 'SSRSlot'

### ISSUE THREAD

**Issue by michaelcozzolino** [webpack/webpack#16834]
# Bug report

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**
when using dynamic slot with v-for with vue components, i'm getting the following errors:

`
 error  in /home/michael/Development/app/symfony-demo-vue-bug/assets/vue/components/Parent.vue.ts                                                                                               8:00:25 AM

[tsl] ERROR in /home/michael/Development/app/symfony-demo-vue-bug/assets/vue/components/Parent.vue.ts(5,93)
      TS2322: Type 'number' is not assignable to type 'SSRSlot'.

 error  in /home/michael/Development/app/symfony-demo-vue-bug/assets/vue/components/Parent.vue.ts                                                                                               8:00:25 AM

[tsl] ERROR in /home/michael/Development/app/symfony-demo-vue-bug/assets/vue/components/Parent.vue.ts(6,37)
      TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type '<K extends string | number | symbol>(slotName: any) => { name: any; fn: Function; }' is not assignable to parameter of type '<K extends string | number | symbol>(value: any, key: K, index: number) => VNodeChild'.
      Type '{ name: any; fn: Function; }' is not assignable to type 'VNodeChild'.
`
![image](https://user-images.githubusercontent.com/41123653/225232127-bf0f0e32-6d4d-4a65-b78e-5a3bfc40f1a3.png)

I tried to create a vue app with the same components without webpack and it compiles without errors.

steps to reproduce:
1) git clone https://github.com/michaelcozzolino/symfony-demo-vue-bug
2) composer install
3) yarn install
4) yarn watch or yarn build
5) observe the errors
6) php -S localhost:8000 -t public/

The components are in `assets/vue/components` and the purpose of them is to show a list of names by using dynamic slot names.
by going to http://localhost:8000/en/blog/
the names are shown correctly.

**What is the expected behavior?**

I don't expect to get the error.

**Other relevant information:**

Operating System: ubuntu 22.04

**Comment by alexander-akait** [comment]
Sorry wrong repo, please ask this in `typescript`/`vue` repo, we are not responsible for type checking
