### ISSUE TITLE
Build using ModuleFederationPlugin crashes in the browser when using splitChunks

### ISSUE THREAD

**Issue by burhanuday** [webpack/webpack#16832]
# Bug report

Build using ModuleFederationPlugin crashes in the browser when using `splitChunks` in `webpack.config.js`.

A workaround solution is available as of now - https://github.com/module-federation/module-federation-examples/issues/692#issuecomment-1382670317

This workaround works by ignoring all chunks that are managed by ModuleFederationPlugin from SplitChunksPlugin

This should be solved in webpack core instead. Willing to fix this myself but not clear whether to fix in SplitChunksPlugin or ModuleFederationPlugin

**What is the current behavior?**

The page crashes completely with the following error in the console

```shell
Uncaught (in promise) ScriptExternalLoadError: Loading script failed.
(missing: http://localhost:8081/remoteEntry.js)
while loading "./RemoteApp" from webpack/container/reference/remote
    at webpack/container/reference/remote (main.js:29:25)
    at __webpack_require__ (main.js:71:33)
    at initExternal (main.js:336:28)
    at __webpack_require__.I (main.js:349:15)
    at main.js:838:47
    at webpack/sharing/consume/default/react/react (main.js:892:67)
    at main.js:923:56
    at Array.forEach (<anonymous>)
    at __webpack_require__.f.consumes (main.js:906:36)
    at main.js:154:40
```

Edit: additional info
On further trial and error:
The build works when splitChunks is enabled in host but disabled in remote.
Here's a diff of the remote entry files generated without and with split chunks - https://www.diffchecker.com/O7K3DdGs/

The error disappears and page works as expected when splitChunks config is commented out

**If the current behavior is a bug, please provide the steps to reproduce.**

Reproduction repo with steps in the readme:
https://github.com/burhanuday/webpack-mf-split-chunks-repro

**What is the expected behavior?**

App should not crash when splitChunks config is enabled.

**Other relevant information:**
webpack version:  5.76.1
Node.js version: 16.15.0
Operating System: MacOS
Additional tools:

**Comment by burhanuday** [comment]
// cc: @ScriptedAlchemy Might be of interest to you

**Comment by burhanuday** [comment]
On further trial and error:
The build works when splitChunks is enabled in host but disabled in remote.
Between the two builds, this is the difference in the remote entry file generated by remote
```js
	/******/ 	/* webpack/runtime/chunk loaded */	
/******/ 	(() => {	
/******/ 		var deferred = [];	
/******/ 		__webpack_require__.O = (result, chunkIds, fn, priority) => {	
/******/ 			if(chunkIds) {	
/******/ 				priority = priority || 0;	
/******/ 				for(var i = deferred.length; i > 0 && deferred[i - 1][2] > priority; i--) deferred[i] = deferred[i - 1];	
/******/ 				deferred[i] = [chunkIds, fn, priority];	
/******/ 				return;	
/******/ 			}	
/******/ 			var notFulfilled = Infinity;	
/******/ 			for (var i = 0; i < deferred.length; i++) {	
/******/ 				var [chunkIds, fn, priority] = deferred[i];	
/******/ 				var fulfilled = true;	
/******/ 				for (var j = 0; j < chunkIds.length; j++) {	
/******/ 					if ((priority & 1 === 0 || notFulfilled >= priority) && Object.keys(__webpack_require__.O).every((key) => (__webpack_require__.O[key](chunkIds[j])))) {	
/******/ 						chunkIds.splice(j--, 1);	
/******/ 					} else {	
/******/ 						fulfilled = false;	
/******/ 						if(priority < notFulfilled) notFulfilled = priority;	
/******/ 					}	
/******/ 				}	
/******/ 				if(fulfilled) {	
/******/ 					deferred.splice(i--, 1)	
/******/ 					var r = fn();	
/******/ 					if (r !== undefined) result = r;	
/******/ 				}	
/******/ 			}	
/******/ 			return result;	
/******/ 		};	
/******/ 	})();
```

**Comment by zhangchao828** [comment]
+1

**Comment by alexander-akait** [comment]
There is a `edit` button on your issue, avoid extra pinning and multipl posting, thank you.

Regarding your issue, you can't split `chunks: "all" when you use module federation right now, even more I strongly recommend don't use `chunks: "all" (and when you don't use module federation),` at all, anyway we can fix it.

And the main question, why you want to split remote, what is the point?

**Comment by burhanuday** [comment]
> chunks: "all" when you use module federation right now

which is what i'd like to fix. It's not just chunks: all, but in multiple projects, we use the SplitChunksPlugin to create "vendor" and "common" cache groups for better caching on the browser. Even those don't work when module federation plugin is added

> And the main question, why you want to split remote (especial initial), what is the point?

I am not trying to split remote, just pointing out the difference in the remote entry file that gets generated with and without SplitChunksPlugin, which i believe is the cause of the app crashing in the browser

> What you expected - many requests for initial chunks, it is not a good idea?

For large projects, yes, i do believe this is an issue even with HTTP2 because there is overhead and in HTTP2, the number of parallel requests are limited to 25 (i am not very sure of this number, different sources say different numbers)

In any case, either this is a bug which should be fixed OR a wont-fix that should atleast be documented on the module federation plugin docs

on a side note, can you point out why `chunks: "all"` is bad? because it is explicitly recommended in the code splitting guide in the docs - https://webpack.js.org/guides/code-splitting/#splitchunksplugin

**Comment by alexander-akait** [comment]
> which is what i'd like to fix. It's not just chunks: all, but in multiple projects, we use the SplitChunksPlugin to create "vendor" and "common" cache groups for better caching on the browser. Even those don't work when module federation plugin is added

I can provide a lot of cases, can you provide your case (with minumim code and etc, just for help)

I agree that we have, let's say, a problem and nowhere in the documentation is it said about it.

Shorty - splitting any initial chunks can break your module federation, that is why we have https://github.com/webpack/webpack/blob/main/lib/config/defaults.js#L1186 by default.

We can fix by filtering it, like in provided worarkund by you (there is some things were missed and that is why you found that it dones't work for you). 

> on a side note, can you point out why chunks: "all" is bad? because it is explicitly recommended in the code splitting guide in the docs - https://webpack.js.org/guides/code-splitting/#splitchunksplugin

Good catch, we should fix our docs, I will open an issue after we finished this issue, we should recommend to use `default` setting, I think this example is just for example, and it was not particularly apparently assumed that someone was using it, but apparently we were mistaken
