### ISSUE TITLE
Support Typescript@5 moduleResolution bundle

### ISSUE THREAD

**Issue by tal-rofe** [webpack/webpack#16845]
### Discussed in https://github.com/webpack/webpack/discussions/16682

<div type='discussions-op-text'>

<sup>Originally posted by **tal-rofe** January 29, 2023</sup>
TypeScript@5 now can configure `moduleResolution` to `bundle`
When configuring it, Webpack emits an error as it does not know it,

Is it going to be supported?</div>

When I did:
```json
		"moduleResolution": "bundler",
```

I got this error: 

```

ERROR in ./tsconfig.base.json:6:23
TS6046: Argument for '--moduleResolution' option must be: 'node', 'classic', 'node16', 'nodenext'.
    4 |                 "target": "ES2017",
    5 |                 "module": "ESNext",
  > 6 |                 "moduleResolution": "bundler",
      |                                     ^^^^^^^^^
    7 |                 "noEmit": true,
    8 |                 "baseUrl": "./",
    9 |                 "allowJs": false,

webpack 5.76.2 compiled with 1 error in 536 ms
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by alexander-akait** [comment]
Sorry, it is not a webpack plugin, please read carefully

> TS6046: Argument for '--moduleResolution' option must be: 'node', 'classic', 'node16', 'nodenext'.

It means you still have old typescript version that doesn't support `bundler`, please read typescript documentation and check since which version it will work and update to this version, we can't fix it here, sorry again
