### ISSUE TITLE
some bug of realcontenthash plugin

### ISSUE THREAD

**Issue by lanmch** [webpack/webpack#16858]
# Bug report

**What is the current behavior?**
some string (which matched old file hash) will be replace in realContentHashPlugin.
(ps. 'old hash' means the content hash before dealing with realContentHashPlugin)

**If the current behavior is a bug, please provide the steps to reproduce.**
First, the hash matched src content is a very small probability event. So I try to mock some data to  reproduce it.

```javascript
// webpack.config.js
module.exports = {
  mode: 'production',
  entry: {
    app: './src/index.js',
  },
  output: {
    path: "dist",
    filename: '[name].[contenthash:8].chunk.js',
  },
  devtool: 'source-map',
  optimization:{
    minimize: false,
  }
};

// src/index.js
import React from 'react';
import ReactDOM from 'react-dom';
import { renderToString } from 'react-dom/server'
import(/* webpackChunkName: 'index' */ './x');
console.log('renderToString: 11c46ae742 ', renderToString);
console.log('ReactDOM: ', ReactDOM);
console.log(React);

// src/x.js
console.log('123123xx~c46ae742');
```

in webpack/lib/optimize/realContentHashPlugin, mock a hash and generate the hashRegexp by it.
![image](https://user-images.githubusercontent.com/37408756/227441818-9c363d16-6301-4174-b98d-9d1cecebad6a.png)
![image](https://user-images.githubusercontent.com/37408756/227442032-77033308-20a5-49ed-ae91-c15d5b20abbf.png)

Then you can run npm run build. In dist, you can find that all string of 'c46ae742' has been replaced.
![image](https://user-images.githubusercontent.com/37408756/227442344-22cf7d0c-4fd1-4fcd-b2dc-53535ab70e27.png)
![image](https://user-images.githubusercontent.com/37408756/227442395-79be3ec2-f498-4520-ab98-0d7c06186881.png)

**What is the expected behavior?**
the string of 'c46ae742' will not be replaced

**Other relevant information:**
webpack version:  5.75.0
Node.js version:  14.16.0
Operating System:  macOS

**My point of view**
webpack should not replace asset source by  hash regexp (global [`/c46ae742|a1563cb9/g`]), the regexp may be more limited
![image](https://user-images.githubusercontent.com/37408756/227442946-d87992a3-04a3-4545-9706-fcaee407a5a9.png)

**Comment by alexander-akait** [comment]
Yeah, known problem, let's close in favor https://github.com/webpack/webpack/issues/14058 (because it is the same, we fixed circular error, but it is still override some things), workaround - set hash to 12

**Comment by lanmch** [comment]
您好，我已收到您的邮件，我会尽快给您回复。

**Comment by lanmch** [comment]
> Yeah, known problem, let's close in favor #14058 (because it is the same, we fixed circular error, but it is still override some things), workaround - set hash to 12

Why set hash to 12 is useful？I can't agree with it. Like the same problem https://github.com/webpack/webpack/issues/14574. I think the more useful solution is hash in content has fixed prefix or suffix.
When I set hash to 12, for example, webpack generate a hash like 'ab12ceio91xq', and in my source code, a string might be set to `var s = xxxxab12ceio91xqyyy`, it also will be replace too?(althought this variable's define is not a reasonable way, but it is defined in npm package, I can't fix it easily)

**Comment by alexander-akait** [comment]
Sorry again, it is a known issue, in order to solve it we need to rewrite a lot of logic, currently it is not possible, so you can:
- disable content hash plugin
- increase length of hash

**Comment by lanmch** [comment]
get it thanks

**Comment by romanlex** [comment]
> Sorry again, it is a known issue, in order to solve it we need to rewrite a lot of logic

@alexander-akait 
Why can’t you do replay only in those files/code that belong to the webpack itself?
Why can’t you make a replacement in AST, and not with regular language?
What does this replacement have to do with third-party code?

**Comment by lanmch** [comment]
您好，我已收到您的邮件，我会尽快给您回复。
