### ISSUE TITLE
Uncaught TypeError: __webpack_require__(...).ensure is not a function

### ISSUE THREAD

**Issue by ezsper** [webpack/webpack#1685]
I'm not able to load my chunks on demand because `require.ensure` is not defined. What I'm getting wrong here?

    if (!global.Intl) {
      require.ensure(["intl"], function (require) {
        require('intl');
      });
    }

produces:

`Uncaught TypeError: __webpack_require__(...).ensure is not a function`

I'm loading CommonsChunkPlugin

`new webpack.optimize.CommonsChunkPlugin("vendor", 'vendor.js'),`

and injecting `vendor.js` correctly into my page along with the main chunks.

I'm using the following webpack versions:

"webpack": "^1.12.9",
"webpack-dev-middleware": "^1.4.0",
"webpack-hot-middleware": "^2.5.0"

and my webpack.prod.config.js

    require('babel/polyfill');

    // Webpack config for creating the production bundle.
    var path = require('path');
    var webpack = require('webpack');
    var CleanPlugin = require('clean-webpack-plugin');
    var ExtractTextPlugin = require('extract-text-webpack-plugin');
    var strip = require('strip-loader');

    var relativeAssetsPath = '../static/dist';
    var assetsPath = path.join(__dirname, relativeAssetsPath);

    // https://github.com/halt-hammerzeit/webpack-isomorphic-tools
    var WebpackIsomorphicToolsPlugin = require('webpack-isomorphic-tools/plugin');
    var webpackIsomorphicToolsPlugin = new WebpackIsomorphicToolsPlugin(require('./webpack-isomorphic-tools'));

    module.exports = {
      devtool: 'source-map',
      context: path.resolve(__dirname, '..'),
      entry: {
        'main': [
          'bootstrap-sass!./src/theme/bootstrap.config.prod.js',
          'font-awesome-webpack!./src/theme/font-awesome.config.prod.js',
          './src/client.js'
        ],
        intl: [
          'intl'
        ]
      },
      output: {
        path: assetsPath,
        filename: '[name]-[chunkhash].js',
        chunkFilename: '[name]-[chunkhash].js',
        publicPath: '/dist/'
      },
      module: {
        loaders: [
          { test: /\.js$/, exclude: /node_modules/, loaders: [strip.loader('debug'), 'babel']},
          { test: /\.(yml|yaml)$/, loader: 'json-loader!yaml-loader' },
          { test: /\.json$/, loader: 'json-loader' },
          { test: /\.less$/, loader: ExtractTextPlugin.extract('style', 'css?modules&importLoaders=2&sourceMap!autoprefixer?browsers=last 2 version!less?outputStyle=expanded&sourceMap=true&sourceMapContents=true') },
          { test: /\.scss$/, loader: ExtractTextPlugin.extract('style', 'css?modules&importLoaders=2&sourceMap!autoprefixer?browsers=last 2 version!sass?outputStyle=expanded&sourceMap=true&sourceMapContents=true') },
          { test: /\.woff(\?v=\d+\.\d+\.\d+)?$/, loader: "url?limit=10000&mimetype=application/font-woff" },
          { test: /\.woff2(\?v=\d+\.\d+\.\d+)?$/, loader: "url?limit=10000&mimetype=application/font-woff" },
          { test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/, loader: "url?limit=10000&mimetype=application/octet-stream" },
          { test: /\.eot(\?v=\d+\.\d+\.\d+)?$/, loader: "file" },
          { test: /\.svg(\?v=\d+\.\d+\.\d+)?$/, loader: "url?limit=10000&mimetype=image/svg+xml" },
          { test: webpackIsomorphicToolsPlugin.regular_expression('images'), loader: 'url-loader?limit=10240' }
        ]
      },
      progress: true,
      resolve: {
        modulesDirectories: [
          'src',
          'node_modules'
        ],
        extensions: ['', '.json', '.js']
      },
      plugins: [
        new webpack.optimize.CommonsChunkPlugin("vendor", '[name]-[chunkhash].js'),
        new CleanPlugin([relativeAssetsPath]),

        // css files from the extract-text-plugin loader
        new ExtractTextPlugin('[name]-[chunkhash].css', {allChunks: true}),
        new webpack.DefinePlugin({
          __CLIENT__: true,
          __SERVER__: false,
          __DEVELOPMENT__: false,
          __DEVTOOLS__: false
        }),

        // ignore dev config
        new webpack.IgnorePlugin(/\.\/dev/, /\/config$/),

        // set global vars
        new webpack.DefinePlugin({
          'process.env': {
            // Useful to reduce the size of client-side libraries, e.g. react
            NODE_ENV: JSON.stringify('production')
          }
        }),

        // optimizations
        new webpack.optimize.DedupePlugin(),
        new webpack.optimize.OccurenceOrderPlugin(),
        /*new webpack.optimize.UglifyJsPlugin({
          compress: {
            warnings: false
          }
        }),*/
        webpackIsomorphicToolsPlugin
      ]
    };

**Comment by joliveros** [comment]
I have the same problem: 

http://stackoverflow.com/questions/33683539/webpack-require-is-not-a-function-when-using-babel-6/33968865#33968865

**Comment by ezsper** [comment]
I can `require` any module as normal, I got this error only when I try to use `require.ensure` for code splitting.

**Comment by ezsper** [comment]
When I try to webpack, it says:

    WARNING in ./src/client.js
    Critical dependencies:
    90:16-23 require function is used in a way in which dependencies cannot be statically extracted
     @ ./src/client.js 90:16-23

**Comment by sokra** [comment]
`require.ensure` takes an **array** as first argument.

**Comment by joliveros** [comment]
@ezsper I can replicate this issue with webpack and babel 6. So you are not crazy. With babel 5 `require.ensure` works perfectly. I believe it has something to do with the module system being used and the way `require` statements are transpiled. I'm not familiar with the source but I think a transform for babel that knows how to transpile `require.ensure` might be needed.

**Comment by ezsper** [comment]
Although I'm using babel 5.8.34.

**Comment by ezsper** [comment]
@sokra You are right, though my actual code has the first argument wrapped in arrays, here I didn't copy and paste, I typed myself. Despite of that, this is not the problem, the error will trigger anyway.

**Comment by davegomez** [comment]
I'm getting the same error using babel 6
```
Uncaught TypeError: __webpack_require__(...)(...) is not a function
```

This is my code:

`hello.js`
```
export default name => console.log(`Hello ${name}`);
```

`index.js`
```
import "../scss/main.scss";

console.log('Wellcome to the TEST!');

const getModule = (moduleName, cb) =>
  require.ensure([], require => cb(require(`./${moduleName}`)()));

const btn = document.getElementById('btn');
btn.addEventListener('click', event => getModule('hello', hello => console.log(hello)));
```

**Comment by davegomez** [comment]
I found the issue.

This piece of code is returning and object when we use export default in a ES6 module:
```
require(`./${moduleName}`)
```

So we have to explicitly return the default function to be use in the callback like this:

```
require.ensure([], require => cb(require(`./${moduleName}`).default));
```

Now you can load the module on demand:
```
const btn = document.getElementById('btn');
btn.addEventListener('click', event => getModule('hello', hello => hello('Dave')));
```

**Comment by bebraw** [comment]
@ezsper Safe to close?

**Comment by joliveros** [comment]
by using `require(...).default` I was able resolve this issue in my webpack builds. However, this only applies to es6 modules. Other modules can be left as is. Thank you!

@bebraw @ezsper I think this is safe to close. Unless there is someway to do this automatically?

**Comment by bebraw** [comment]
@joliveros Can you try with [babel-plugin-add-module-exports](https://www.npmjs.com/package/babel-plugin-add-module-exports)? Just a hunch.

**Comment by joliveros** [comment]
@bebraw that worked! Thank you. I had to go remove `require(...).default` everywhere. This also brought new errors to life in my style loader where some paths were being resolved before, now they weren't. Also, a lot of undefined variable errors showed up. Things that should have thrown errors before. After fixing all of that I have webpack builds working.

If anyone sees new errors, just go ahead and fix them.

**Comment by jypblue** [comment]
when i first start node server by using babel-plugin-add-module-exports, it's useful but when i refresh the page it still will be wrong

**Comment by rcalabro** [comment]
Hi, if you are using `webpack-isomorphic-tools` you should set `patch_require: true`, it is false by default.

From documentation:

> // enables support for `require.context()` and `require.ensure()` functions. 
> // is turned off by default  
> // to skip unnecessary code instrumentation 
> // because not everyone uses it. 
> // 
> // patch_require: true, // is false by default

**Comment by lili21** [comment]
still have the problem.
