### ISSUE TITLE
XMLHttpRequest cannot load http://localhost/info

### ISSUE THREAD

**Issue by jeron-diovis** [webpack/webpack#1686]
Hi.
I'm using webpack with webpack dev server and hot module replacement enabled, all standard configs:
```js
var compiler = webpack({
      entry: [
        'webpack-dev-server/client?',
        'webpack/hot/only-dev-server',
        'path/to/my/entry.js'
      ],

      plugins: [
        new webpack.HotModuleReplacementPlugin()
      ]
    });

var server = new WebpackDevServer(compiler, { hot: true, publicPath: "..." });
```

After loading page I see in devtools this message repeating again and again:
```
XMLHttpRequest cannot load http://localhost/info?t=1448890058458. 
No 'Access-Control-Allow-Origin' header is present on the requested resource. 
Origin 'http://localhost:5001' is therefore not allowed access. 
The response had HTTP status code 403.

[WDS] Disconnected!
sock.onclose @ (program):67
```

What it wants from localhost/info? Should I do smth with my server, or I configured webpack wrong?

**Comment by jeron-diovis** [comment]
Found it. Setting `webpack-dev-server/client?http://localhost:<port>` solved the problem.

It's interesting that everything works just perfect even without explicit declaring host on webpack-dev-server < 1.13. 
What was done there that so handy behavior is no more available?

**Comment by bebraw** [comment]
You can avoid those entries if you run webpack-dev-server in `inline` mode. That's one way to solve it I think.
