### ISSUE TITLE
@swc/helpers is incorrectly removed/tree shaked from the production bundle

### ISSUE THREAD

**Issue by andersekdahl** [webpack/webpack#16861]
# Bug report

**What is the current behavior?**

When using `swc-loader` with `@swc/helpers` and mixing ESM and CommonJS it seems that the tree shaking process in webpack incorrectly marks `@swc/helpers` as not used. When changing the repro below to only use ESM I can no longer reproduce it.

My first instinct was that this was an SWC issue and not a webpack issue, but from what I can tell SWC correcty determines the module type and injects `import` statements into ESM code and `require` statements into the CJS code.

Injected into ESM:
```js
import _create_class from "@swc/helpers/src/_create_class.mjs";
```

Into CJS:
```js
var _create_class = require("@swc/helpers").create_class;
```

**If the current behavior is a bug, please provide the steps to reproduce.**

I've created a small repro here:
https://github.com/andersekdahl/webpack-swc-helpers-repro

entry.js:
```js
import common from "./common";
import esm from "./esm";
console.log(common, esm);
```

common.js:
```js
const x = class {
  method() {}
};

console.log(x);

module.exports = "commonjs";
```

esm.js:
```js
const x = class {
  method() {}
};

console.log(x);

export default "esm";
```

webpack.config.js:
```js
module.exports = {
  entry: "./src/entry.js",
  module: {
    rules: [
      {
        test: /\.js$/,
        use: {
          loader: "swc-loader",
          options: {
            jsc: {
              externalHelpers: true,
            },
            isModule: "unknown",
          },
        },
      },
    ],
  },
};
```

Prettified final bundle:
```js
(() => {
  var e = {
      915: (e, r, o) => {
        var n = o(835).class_call_check,
          t = o(835).create_class,
          a = (function () {
            "use strict";
            function e() {
              n(this, e);
            }
            return t(e, [{ key: "method", value: function () {} }]), e;
          })();
        console.log(a), (e.exports = "commonjs");
      },
      835: () => {},
    },
    r = {};
  function o(n) {
    var t = r[n];
    if (void 0 !== t) return t.exports;
    var a = (r[n] = { exports: {} });
    return e[n](a, a.exports, o), a.exports;
  }
  (o.n = (e) => {
    var r = e && e.__esModule ? () => e.default : () => e;
    return o.d(r, { a: r }), r;
  }),
    (o.d = (e, r) => {
      for (var n in r)
        o.o(r, n) &&
          !o.o(e, n) &&
          Object.defineProperty(e, n, { enumerable: !0, get: r[n] });
    }),
    (o.o = (e, r) => Object.prototype.hasOwnProperty.call(e, r)),
    (() => {
      "use strict";
      var e = o(915),
        r = o.n(e);
      function n(e, r) {
        for (var o = 0; o < r.length; o++) {
          var n = r[o];
          (n.enumerable = n.enumerable || !1),
            (n.configurable = !0),
            "value" in n && (n.writable = !0),
            Object.defineProperty(e, n.key, n);
        }
      }
      var t = (function () {
        function e() {
          !(function (e, r) {
            if (!(e instanceof r))
              throw new TypeError("Cannot call a class as a function");
          })(this, e);
        }
        var r, o;
        return (
          (r = e),
          (o = [{ key: "method", value: function () {} }]) && n(r.prototype, o),
          e
        );
      })();
      console.log(t), console.log(r(), "esm");
    })();
})();
```

Note in the final bundle that module id `835` has an empty function that doesn't return the exports `create_class` and `class_call_check` as expected.

**What is the expected behavior?**

That the needed exports from `@swc/helpers` are still in the final production bundle.

**Other relevant information:**
webpack version:  5.76.3
Node.js version:  Tested on 18.13.0 and 16.19.1
Operating System: Tested on Windows and Ubuntu
Additional tools:

**Comment by alexander-akait** [comment]
@andersekdahl As I can see we can close this in favor https://github.com/swc-project/swc/issues/7144? :smile:

**Comment by alexander-akait** [comment]
> If I manually remove sideEffects: false from package.json I do get something in the final bundle from @swc/helpers, but wierdly enough it's not what it's supposed to be.

Can you clarify?

**Comment by andersekdahl** [comment]
I couldn't quite tell what code it was that got placed in the webpack module for @swc/helpers but I was pretty sure that it wasn't correct because it didn't contain the exports that the requiring code was expecting.

It's possible to reproduce in my repro repo by just removing `sideEffects: false` in node/modules

**Comment by andersekdahl** [comment]
> No problem with webpack, swc-loader returns for commonjs module:

I do believe that there's an issue with webpack still. @swc/helpers had a big as well here which they've fixed but not released. But if you manually patch node_modules/@swc/helpers/lib/index.js in my repro all of the helpers are still stripped from the final bundle.

**Comment by alexander-akait** [comment]
Please clarify, used helpers will be removed - yes

**Comment by andersekdahl** [comment]
If I change the code for node_modules/@swc/helpers/lib/index.js to export the correct names that the require statements expect the helpers are still removed from the bundle.

**Comment by alexander-akait** [comment]
Sorry, I can't reproduce:
```
akait@akait-notebook:~/IdeaProjects/webpack-swc-helpers-repro$ npx webpack --mode production && node ./dist/main.js 
asset main.js 70.5 KiB [emitted] (name: main)
orphan modules 61.7 KiB [orphan] 82 modules
runtime modules 663 bytes 3 modules
cacheable modules 69.1 KiB
  modules by path ./node_modules/@swc/helpers/src/*.mjs 68.2 KiB
    ./node_modules/@swc/helpers/src/index.mjs + 81 modules 67.4 KiB [built] [code generated]
    ./node_modules/@swc/helpers/src/_class_call_check.mjs 176 bytes [built] [code generated]
    ./node_modules/@swc/helpers/src/_create_class.mjs 580 bytes [built] [code generated]
  modules by path ./src/*.js 924 bytes
    ./src/entry.js + 1 modules 507 bytes [built] [code generated]
    ./src/common.js 417 bytes [built] [code generated]
webpack 5.76.3 compiled successfully in 402 ms
[Function: x]
[Function: x]
commonjs esm
```

it is really a simple case, there is no problems with webpack, seems you have not applied valid fix

**Comment by alexander-akait** [comment]
I just have changed generated code by `swc-loader`, from `require("@swc/helpers").create_class` to `require("@swc/helpers").createClass`, same for `class_call_check`.

**Comment by magic-akari** [comment]
The new @swc/core with new @swc/helpers@0.5.0 is published.
Could you try with the new version?

**Comment by andersekdahl** [comment]
I can confirm that the latest version of @swc/core and @swc/helpers fixes the issue, thank you! I must have made a mistake somehow when trying to see if patching @swc/helpers would fix the issue. Thanks!
