### ISSUE TITLE
Treeshake dynamic imports based on destructuring

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack#16872]
Given the following code: 

```javascript
import('lodash-es').then(({uniq}) => uniq)
```

When webpack bundles this code, it should only include the module tree for `uniq` and tree-shake the rest of the exports in `lodash-es` as unused.

**Comment by vankop** [comment]
with `then` it is very tricky. we definitely could not support all cases. I thought about async/await support or simply only assigning support things like:
```js
import * as ns from 'a';
 const {b} = ns;
 const {c} = await import('c');
 const {d} = process.env; // or any defined value

**Comment by TheLarkInn** [comment]
What are the scenarios which couldn't be supported with `.then()`?

**Comment by icy0307** [comment]
We are facing the same issue too, for a really long time.
What I currently do to bypass this is to add an intermediate file that imports statically and re-export.
like  
``` 
import { uniq} from 'lodash-es' 
export uniq
```
I understand that object deconstruction dead code elimination is very difficult, which means performing dead code on object property. 
As we wrote `const {uniq} = await import('lodash-es');`, a [module namespace object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import#module_namespace_object) has already been created.
A single-line analyzation of `const {uniq} = await import('lodash-es');` would not be that hard?  @vankop 
What is tricky is when using babel to compile
A simple 
``` js
async function main() {
    const {uniq} = await import('lodash-es);
    console.log(uniq);
}
main();
```
would be transpiled to 
``` js
import _regeneratorRuntime from "@babel/runtime/helpers/regeneratorRuntime";
import _asyncToGenerator from "@babel/runtime/helpers/asyncToGenerator";
function main() {
  return _main.apply(this, arguments);
}
function _main() {
  _main = _asyncToGenerator( /*#__PURE__*/_regeneratorRuntime().mark(function _callee() {
    var _yield$import, uniq;
    return _regeneratorRuntime().wrap(function _callee$(_context) {
      while (1) {
        switch (_context.prev = _context.next) {
          case 0:
            _context.next = 2;
            return import('lodash-es');
          case 2:
            _yield$import = _context.sent;
            uniq = _yield$import.uniq;
            console.log(uniq);
          case 5:
          case "end":
            return _context.stop();
        }
      }
    }, _callee);
  }));
  return _main.apply(this, arguments);
}
main();
```
which uses "switch case" based on runtime value, making it impossible to statically analyze.

**Comment by icy0307** [comment]
BUT, Treeshake dynamic imports based on destructuring are still pretty important for bundlers because of the possible code size it could save. 
Maybe we could 
1. Somehow add intermediate files automatically by user's plugin , which creates a virtual module that statically imports and re-exports the used exports and changes this source code before handing it to babel.  
2. Do javascript parsing before any loaders for js, and mark unused export before any loaders. 
@vankop @alexander-akait @sokra 
What is your opinions on this?

**Comment by vankop** [comment]
@TheLarkInn  because of javascript complexity:
```js
const a = import('a');
a.then(({b}) => {});
a.then(({c}) => {}); // this will work I guess

a.then(v => {
  const {c} = v;
  return v;
}).then(() => {}); // quite difficult to catch all thens here
```

we could support **only** this syntax like:
```js
import().then((__destructing_here__) => {});
```

problem here we introduce some "non-stable" build in terms of tree-shaking. e.g. like in example user will "refactor" destructing to destructing from variable. in case of async/await:
```js
const b = await import('b');
const { a, c } = b;
```
should work ( we have something like variable replacement in JavascriptParser )

**Comment by alexander-akait** [comment]
Note - we have `/* webpackExports: ["abc", "default"] */` for non analizable imports

**Comment by alexander-akait** [comment]
In fact we already support this, I opened it to improve different edge cases and for new proposals

**Comment by Alok-2005** [comment]
Hey @TheLarkInn I am interested in contributing for this issue,  can just guide me through this issue more ?

**Comment by Alok-2005** [comment]
hey @TheLarkInn can I work on this issue as a part of gsoc 2025

**Comment by Supriya-57** [comment]
"@TheLarkInn, is this issue available for contribution under GSoC 2025? I'd like to work on it."

**Comment by alexander-akait** [comment]
This issue was solved
