### ISSUE TITLE
Use CommonsChunkPlugin twice on one page

### ISSUE THREAD

**Issue by andrewbranch** [webpack/webpack#1688]
As part of our caching strategy, I have set up a configuration where we have two instances of CommonsChunkPlugin: one for vendor scripts; one for common app code. Now we want to include both on every page. But the generated `vendor.js` and `commons.js` each include the webpack runtime, which doesn't work.

Is there a way to remove the runtime from one of those bundles, or is there a different correct way to do this?

**Comment by fredericgrati** [comment]
I have two instances of CommonsChunkPlugin : vendor and common.
webpack.conf:
```
var entry = {
        profile: [ './app/frontend/javascripts/profile/main.es6'],
        projects: [ './app/frontend/javascripts/projects/main.es6'],
        // the vendor entry point
        vendor: ['babel-polyfill', 'lodash', 'jquery']
    };
```
```
    var plugins = [
        new webpack.optimize.CommonsChunkPlugin("common", 'common' + (options.longTermCaching ? '-[chunkhash].js' : '.js'), ['projects', 'profile']),
        new webpack.optimize.CommonsChunkPlugin("vendor", 'vendor' + (options.longTermCaching ? '-[chunkhash].js' : '.js' ), ['common', 'vendor'], Infinity)
    ];
```

The webpack runtime is only present into the vendor bundle and I can use them like this :
```
  <script src="[...]/assets/vendor.js"></script>
  <script src="[...]/assets/common.js"></script>
  <script src="[...]/assets/profile.js"></script>
```
I hope this will help you (I don't know if it is the correct way to do it but it seems to work)

**Comment by sokra** [comment]
> Is there a way to remove the runtime from one of those bundles, or is there a different correct way to do this?

@andrewbranch You can do it the way @fredericgrati does it. One of the Plugins should have the name of the other commons chunk in the `chunks` property.

**Comment by andrewbranch** [comment]
I'm a little confused but that seems to work nicely. Thanks!
