### ISSUE TITLE
Can we generate the exported part at the end of current module?

### ISSUE THREAD

**Issue by aleen42** [webpack/webpack#16888]
## Feature request

**What is the expected behavior?**

If there is a ES module like this:

```js
console.log('module');
export default const a = () => {};
```

Webpack currently generates the code like this:

```js
// EXPORTS
__webpack_require__.d(__webpack_exports__, { 'default' : function () { return a } });
console.log('module');
const a = () => {};
```

I hope that it can generate the exported part at the end of the module:

```js
console.log('module');
const a = () => {};
// EXPORTS
__webpack_require__.d(__webpack_exports__, { 'default' : function () { return a } });
```

**What is motivation or use case for adding/changing the behavior?**

In ES3 context, we hope to use a ES3 harmony plugin to redefine `Object.defineProperty` like this:

```js
console.log('module');
vara = () => {};
// EXPORTS
__webpack_exports__['default'] = (function () { return a })();
```

If the part is at the top of the module, `a` will be `undefined`, which cannot be easily patched.

**How should this be implemented in your opinion?**

Add an option to the `ConcatenatedModule` to specify the position?

**Are you willing to work on this yourself?**
yes

**Comment by alexander-akait** [comment]
Yeah, feel free to send a PR

**Comment by hai-x** [comment]
See more in https://github.com/webpack/webpack/issues/18494#issuecomment-4506741950 for the reason behind generating it at an earlier stage.

The good news is that we now support optimizing export generation for `const` bindings in the corresponding PR under `optimization.inlineExports` option.
