### ISSUE TITLE
Replace all string literals / regexp literals referencing RuntimeGlobals

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack#16897]
We can reuse it from https://github.com/webpack/webpack/blob/main/lib/RuntimeGlobals.js#L11

_Originally posted by @alexander-akait in https://github.com/webpack/webpack/pull/16896#discussion_r1154736826_

**Comment by TheLarkInn** [comment]
Been a bit swamped on this so looking for contributions here!

**Comment by snitin315** [comment]
I can help with this.

**Comment by TheLarkInn** [comment]
By all means. Happy to review it.

**Comment by dev-cj** [comment]
I have mentioned a PR for this issue. Which only replaces the exact use of the string "__webpack_require__".


I was about to replace more references where concatenation or template strings were used with `__webpack_require__` and where `RuntimeGlobals` was already imported. Should I continue with this in a new PR?
![image](https://user-images.githubusercontent.com/47112778/236319169-6e600180-0c74-4e14-a3e1-0f642e1b16ee.png)

**Comment by cwj0417** [comment]
is this issue can be closed as complete?

**Comment by tthijm** [comment]
@TheLarkInn are [this line](https://github.com/webpack/webpack/blob/611bded369b5a9ea695f2669b25a6f88b67d7826/lib/DefinePlugin.js#L311) and the next one the only ones who remain to be replaced? If so, could you assign me to this task?
