### ISSUE TITLE
sharing chunks between main and a worker does not work under certain conditions

### ISSUE THREAD

**Issue by mmomtchev** [webpack/webpack#16895]
# Bug report

**What is the current behavior?**

In the repro repo below, `sqlite3-bundler-friendly.mjs` will get included in each bundle (main, worker).
It is worth noting that one of the chunks is initial, the other one is async.
A very slight change of the `main.js` code makes the problem go away:

```js
export async function initSyncSQLite() {
  return sqlite().then(() => {
    return;
  });
}
```

becomes

```js
sqlite().then(() => {
  return;
});
```

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/mmomtchev/webpack-code-sharing
```
webpack --mode=production 
```

**What is the expected behavior?**

`sqlite3-bundler-friendly.mjs` should be in a separate chunk, shared between both main and worker

**Other relevant information:**
webpack version:  5.77.0
Node.js version: v18.15.0
Operating System: Ubuntu 22.04
Additional tools:

**Comment by alexander-akait** [comment]
Please use:
```
splitChunks: {
      cacheGroups: {
        appAndWorkerCommon: {
          name: "app-and-worker-common",
          chunks: 'all',
          test(module, chunks) {
            return /deps/.test(module.nameForCondition());
          },
        },
      },
},
```

You need to force merge them into the one group, because webpack doesn't undestand just `chunks: 'all'` in your case

**Comment by alexander-akait** [comment]
Some notes here - https://github.com/webpack/webpack/issues/6472

**Comment by mmomtchev** [comment]
I am publishing a library and I cannot (prefer not to) ask everyone to configure webpack to manually create chunks. Transparent bundler support was one of main goals for `sqlite-wasm-http`.

I settled on using dynamic `import()` both in main and in the worker which works as expected and doesn't break Node.js.

**Comment by alexander-akait** [comment]
@mmomtchev Because this case have different runtimes (due loading wasm and assets modules), and you need to manully split them, by default webpack doesn't do this because it's potentially unsafe, if your code isn't written correctly then you could break your application, not sure it is possible to analyze

**Comment by mmomtchev** [comment]
How do they have the same runtime when not using a function?

The right answer is that this particular case fell through the cracks in the `splitChunks` optimizer. Now I understand that it cannot cover every possible case - as JS leaves room for lots of creativity when importing modules - I just thought to share that one because it is a fairly common pattern. I will try to go through it - it will of course take me crazy amounts of time since it is fairly complex and I do not know my way around - but I have enough time on my hands - and I will come back to you with a solution.
