### ISSUE TITLE
Clarification for "output.libraryTarget" documentation

### ISSUE THREAD

**Issue by Daniel15** [webpack/webpack#1690]
The documentation for `output.libraryTarget` says:

> If output.library is not set, but output.libraryTarget is set to a value other than `var`, every property of the exported object is copied (Except `amd`, `commonjs2` and `umd`).

The "Except amd, ...." at the end confuses me, since `var`, `amd`, `commonjs2` and `umd` are four of the six available library targets, and they're all listed in the same sentence :smile: . Does it actually mean this:

> If output.library is not set and output.libraryTarget is set to `this` or `commonjs`, every property of the exported object is copied

Or does it mean that  `amd`, `commonjs2` and `umd` are treated some different way altogether, and thus there's really three separate groups here:
 - `var`: Does nothing special
 - `this` and `commonjs`: Exports every property individually
 - `amd`, `commonjs2` and `umd`: ???

**Comment by sokra** [comment]
`amd`: anonymous amd module.
`umd`:  not useful
`commonjs2` ignores the `output.library` property.

**Comment by sokra** [comment]
Could you update the documentation?

**Comment by Daniel15** [comment]
> Could you update the documentation?

Sure :) The reason I posted this issue was to make sure I completely understand how the `libraryTarget` option works, before updating the documentation. I didn't want to add any incorrect information.

**Comment by pksjce** [comment]
This issue was moved to webpack/webpack.io#109
