### ISSUE TITLE
duplicate code in multi chunks or sooooo big common chunk file

### ISSUE THREAD

**Issue by Treri** [webpack/webpack#1693]
### duplicate code in multi chunks and sooooo big common chunk file

Suppose I have a SPA website. And I have a file `main.js` in which I config the route.

```js
define(function(){
  // suppose I define route here
  route.when('#/aaa', function(){
    // a code split point
    require([
      'services/A',
      'style/a',
      'module/a'
    ])
  }).when('#/bbb', function(){
    // a code split point
    require([
      'services/A',
      'services/B',
      'style/b',
      'module/b'
    ])
  }).when('#/ccc', function(){
    // a code split point
    require([
      'services/B',
      'serivces/C',
      'style/c',
      'module/c'
    ])
  }).when('#/ddd', function(){
    // a code split point
    require([
      'services/A',
      'serivces/C',
      'style/d',
      'module/d'
    ])
  })// and has many route configs like this
});
```

I use webpack to bundle code. My `webpack.config.js` like this

```js
module.exports = {
  entry: {
    main: path.resolve(__dirname, 'main.js')
  },
  output: {
    path: path.resolve(__dirname),
    filename: 'bundle.js'
  },
  plugins: [
    new webpack.optimize.CommonsChunkPlugin({
      name: 'main',
      async: true
    })
  ]
}
```

When I run webpack, various chunks have duplicate `services/A` `services/B` etc. code.
This is not I want.

I read webpack docs, and then I add `minChunks: 2` option to CommonsChunkPlugin.

Then I run webpack again.

Now, every chunk only have its own code. But I also get a **big** common chunk file, which include
`services/A`, `services/B`, `services/C` and other shared code between various page file.

When I run these code, in page `/aaa`, the `/aaa`'s files loaded, and also the big common chunk file.

Now the big problem is, page `/aaa` doesn't need `services/B` and `services/C` code at all, But the common chunk files contains all shared code between various page files. So the common chunk file is so big, and have many unused code.

I know I can set `minChunks` to bigger number, but in this way, every page file may agagin have duplicate code.

## **HELP!**

Can I have other methods to only load necessary common chunks when route to different page?

**Comment by Treri** [comment]
@sokra Could you please take a look at my question? Thanks very much!!

**Comment by sokra** [comment]
There is a tradeoff here. 

move more stuff into the commons chunk means less duplication, bigger commons chunk and more unneeded code loaded.

You can try multiple levels of CommonsChunks and/or manualy splitting of the chunks (`minChunks` can be a function).

**Comment by Treri** [comment]
@sokra sorry, could you please explain what's the meaning of multiple levels of commonChunks? 
I think I may need something like this. 
and I will see the example for seting minchunks to function to see if can solve my problem.

thanks for your reply and awesome work on webpack.

**Comment by sokra** [comment]
see two-explicit-vendor-chunks example in the examples folder

**Comment by Treri** [comment]
In your example, all webpackJsonp like functions will go into vendor.js

but in my question, that files are not vendor(all third party libraries and plugins are in vendor.js), just common chunks, and I want to async load them when required, insteadof loading them in html before `app.js` or `main.js` or something else as shown in your example.

Anyway, thanks for your reply.

**Comment by Treri** [comment]
Hello @sokra I follow your two-explicit-vendor-chunks example, and add one example Treri/webpack-example

but the common used code not only exist in separate file but also these files required them.

Could you please take a look at my demo project?

You may say I can remove `app` from commonChunks plugins' `names` list, but If I do that, `app.js` will not have webpack's initialize code, and throw `webpackJsonp is not defined` error.

Could you give me some advise please?

**Comment by Treri** [comment]
Hello again @sokra 

I bring a good news. I solved my problem! New code is in my webpack-example then-loader branch https://github.com/Treri/webpack-example/tree/feature/then-loader

This is what I want. And I think it is a typical use case, that's only bunlde each page's own sources, and async load common chunks(like common service or something else). Happy to migrate my project to webpack~~

**Comment by jrs320** [comment]
Awesome! I had the same issue for a few days, i am so happy to find a solution at here,now i am taking a closer look at your then-loader, thanks very very much @Treri

**Comment by Treri** [comment]
@jrs320 Thanks. I have updated code in mater branch. You can have a look the newest code in https://github.com/Treri/webpack-angular-example

**Comment by wzup** [comment]
@Wyntau Broken link
https://github.com/Treri/webpack-example/tree/feature/then-loader

**Comment by Wyntau** [comment]
@wzup the new code is in https://github.com/Wyntau/webpack-angular-example master branch.
