### ISSUE TITLE
Uncaught TypeError: (0 , _typeof3.default) is not a function with babel6 in webpack 

### ISSUE THREAD

**Issue by jtHwong** [webpack/webpack#1694]
Compile some code below:
```javascript
async function sleep(timeout) {
    return new Promise((resolve, reject) => {
        setTimeout(function () {
            resolve();
        }, timeout);
    });
}

(async function () {
    console.log('Do some thing, ' + new Date());
    await sleep(3000);
    console.log('Do other things, ' + new Date());
})();
```

Compile successfully, but  error occurs in browser: 
```
Uncaught TypeError: (0 , _typeof3.default) is not a function
```

Use Babel6 and compile the code, it worked in NodeJS. And, how to make it work well in browser with webpack

**Comment by bebraw** [comment]
Can you try Babel 5? Is it any different?

**Comment by jtHwong** [comment]
I will try Babel 5. I keep on  focusing on the problem at [babel-loader #161](https://github.com/babel/babel-loader/issues/161) and close it. 

If it works well with Babel5, I will use await/async in Browser with Babel5. 
Thank you.

**Comment by jtHwong** [comment]
Everything is ok with Babel5.

When I used Babel6, there were some errors in compile progress.

**Comment by bebraw** [comment]
@jtHwong Ok, sounds like a Babel issue then. Thanks for closing. :+1:

**Comment by jrop** [comment]
In my case, I added the following to my webpack config "module.loaders":

```
exclude: /node_modules/
```

For completeness, my full webpack config looks like:

```
{
	devtool: 'inline-source-map',
	module: {
		loaders: [{
			test: /\.js$/,
			exclude: /node_modules/,
			loader: 'babel'
		}]
	}
}
```

When I add the exclusion to node_modules/ everything works as expected.

**Comment by vhlongon** [comment]
if anyone is still having issues with this make sure that the exclude does note contain quotes, i.e. "/node_modules/" or '/node_modules/' . there is a lot of examples and boilerplate code like this, so I was still getting this compile error, because webpack as ignoring the exclude item on the loaders array. Thankfully I got some help on the babel slack channel! I hope that helps someone going bananas like I was before :dancer:

**Comment by tavurth** [comment]
Found this from Google.

In my case it was because I was importing `A.js` from `B.js`, and `B.js` from `A.js`.
