### ISSUE TITLE
Source maps from external node_modules are not working

### ISSUE THREAD

**Issue by davidreher** [webpack/webpack#1695]
Hey,

I have a typescript project with different node modules: parent and child. Child creates some output files with sourcemaps. I setup the webpack.config.js according to the docu with
````javascript
  devtool: 'source-map',
  module: {
    preloaders: [
      { test: /\.js$/, loader: "source-map" }
    ],
````
When I want to consume the sourcemaps in parent to get the original typescript files in the browser, the bundle is built by webpack but the original typescript files are not working.

The bundled files still contain references to the old sourcemap locations, but they are not updated to match the correct url for webpack
````javascript
//# sourceMappingURL=index.js.map


/*****************
 ** WEBPACK FOOTER
 ** ../child/dist/index.js
 ** module id = 1
 ** module chunks = 0
 **/
````

I have set up a minimal project to reproduce this issue: https://github.com/davidreher/webpack-external-sourcemaps

Can someone help me with this one?

**Comment by Mischi** [comment]
same problem here :wink:

**Comment by Mischi** [comment]
The problem has been fixed via this commit https://github.com/davidreher/webpack-external-sourcemaps/commit/8ef6a45bbcbcbcf62c6cf96387dfd51f84ebb077
The property is called "preLoaders" instead of "preloaders".

@davidreher i think you can close the issue :smile:

**Comment by yugandhar-pathi** [comment]
If you are working on react application and using `create-react-app` and came here like me, please refer [this](https://stackoverflow.com/a/58964565/1773256)
