### ISSUE TITLE
What sort of loaders do you want in the list of loaders?

### ISSUE THREAD

**Issue by nickdeis** [webpack/webpack#1696]
Not sure if this is the forum, but I recently wrote a loader for my own needs: [lzstring-loader](https://github.com/nickdeis/lzstring-loader). I found it so easy to write that I plan to write more loaders (for colleagues and friends).
What sort of loaders should I suggest to be put on "list of loaders"? Is there a list of guidelines?

**Comment by shama** [comment]
The ones in the readme are common ones selected by @sokra. The loaders listed in the documentation are added by the community and there are no guidelines to add. The docs are freely editable. Please add your loader to the list here: https://github.com/webpack/docs/wiki/list-of-loaders/_edit

**Comment by nickdeis** [comment]
Thank you!

**Comment by IngwiePhoenix** [comment]
@nickdeis Nice idea with the lz-loader. You think there is a way that javascript strings in general could be optimized using lzstring? Like compressing stringified html templates and such

**Comment by nickdeis** [comment]
@IngwiePhoenix 
Good question. lz-string has always been a niche solution for niche problems.
Serverside compression should always be the preferable way to handle this problem.

### Motivation
I wrote this loader for a project that creates HTML files which include all the resources in the file. I call them "uber htmls".  The reason is that the tool is primarily used in secured environments with ssh/sftp access only, and needs to generate reports based on metadata that isn't considered as secure (stats).

This isn't a new idea by any means, but I ran into the unique problem of these reports blowing up to 50Mb+. I want my product to be easy to use, so I just zip up data+js+css in the html report.
Hence, my clients just sftp the reports off their server, and they can just open it with a click of button.

I use React primarily, so no html templates, but I could imagine you could use this with html.

My clients originally wanted PDF, but I showed this to them, and they were *thrilled* (to say the least) , so I dodge a bullet.
