### ISSUE TITLE
` __webpack_require__(…) is not a function` when using babel 6

### ISSUE THREAD

**Issue by blackendstudios** [webpack/webpack#1697]
Everything seems to build fine but when you run the app you get __webpack_require__(…)

to solve it is simple, you have to removed all of your 'require' and replace them with 'import'

```javascript
require('./devTools')(store); 
//to
import devTools from './devTools';
devTools(store);
```

solution found here:
http://stackoverflow.com/questions/33683539/webpack-require-is-not-a-function-when-using-babel-6

**Comment by shama** [comment]
@blackendstudios Did you say you solved this or is there a further issue here I am missing?

**Comment by blackendstudios** [comment]
I didn't say that I solved it, Tried to find a solution here, but I couldn't, I found a solution so posted here, really helped me, save my day

**Comment by sokra** [comment]
babel 6 changed the `default` behavior.
