### ISSUE TITLE
[Bug] Infinity recursion in hot/poll / [HMR] Nothing hot updated again in 5.78.0.

### ISSUE THREAD

**Issue by nawbc** [webpack/webpack#16972]
# Bug report
Infinity recursion in hot/poll / [HMR] Nothing hot updated.
This bug has fixed in v5.48.0, but now it has reappeared. #13876
![image](https://user-images.githubusercontent.com/45007226/231496278-d9a337c0-c914-4013-bcf3-975eae18336c.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

Occasionally, Save the file after fixing syntax error. 

**What is the expected behavior?**
None of the above.

**Other relevant information:**
webpack version:  5.78
Node.js version: 18.15.0
Operating System:  windows
Additional tools:

**Comment by TheLarkInn** [comment]
@Nawbc can you provide a small reproducible example so we can track it down and fix 🙏

**Comment by Nawbc** [comment]
> @Nawbc can you provide a small reproducible example so we can track it down and fix 🙏

Sorry, I am unable to reproduce by creating a new demo.  This is my project https://github.com/deskbtm-letscollab/letscollab. 

But I found that the code fixed in version 5.48 has been removed in the current version.  https://github.com/webpack/webpack/pull/13877/files

**Comment by alexander-akait** [comment]
@Nawbc Because it was not valid fix, sounds like you have a problem with HMR generated code

**Comment by chinyifei** [comment]
I also had a similar problem, but my webpack version is 5.47.1
If I made an obvious grammatical error, I would keep repeating the error.
<img width="1412" alt="image" src="https://github.com/webpack/webpack/assets/48936497/56a00987-822a-4eba-97e3-a6ba9c44d951">
When I fix the grammatical error, the non-existent resource will be loaded repeatedly, and I don't know why its hash value has not changed.
<img width="341" alt="image" src="https://github.com/webpack/webpack/assets/48936497/bc23cc24-46b6-44e7-9b74-dca7776cc2d5">
<img width="1440" alt="image" src="https://github.com/webpack/webpack/assets/48936497/00f3483b-010c-4650-a41e-cd23c7631b8d">
If I want to solve this problem later, can I only upgrade webpack？
