### ISSUE TITLE
"fetchPriority" for script tags

### ISSUE THREAD

**Issue by aboktor** [webpack/webpack#16989]
# Feature Request
Ability to set _fetchPriority_ attribute on script tags.

Webpack doesn't offer any way to set _fetchPriority_ attribute on script tags that are managed/added by webpack.

I propose adding `output.scriptFetchPriorty` option with values `boolean = false, string: 'high' | 'low' | 'auto'`
When !== false, it is used in LoadScriptRuntimeModule to add the attribute to the script tag.

## Relevant links
https://html.spec.whatwg.org/multipage/scripting.html#the-script-element
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#browser_compatibility

**Comment by TheLarkInn** [comment]
@aboktor (also cc @alexander-akait @snitin315): 

If we create an `output.scriptFetchPriority` option, this would mean that _every_ lazy loaded bundle would apply the same priority. 

Similar to how we provide the `prefetch` and `preload` options: 

```js
import(
  /* webpackInclude: /\.json$/ */
  /* webpackExclude: /\.noimport\.json$/ */
  /* webpackChunkName: "my-chunk-name" */
  /* webpackMode: "lazy" */
  /* webpackPrefetch: true */
  /* webpackPreload: true */
  `./locale/${language}`
);
``` 

Would it be a better design to have customizable fetch priority _pre_ lazy-loaded bundle? 

```js
import(
  /* webpackFetchPriority: "high" */
  `./locale/${language}`
);
```

Alternatively we could have both options. If we go that route I would want to limit the users barrier to complexity with managing both of the options and how they override eachother. That would need to be fleshed out if so. A suggestion for this "dual design" would be: 

- [ ] `output.scriptFetchPriority` applies fetch priority to all lazy loaded bundles, it defaults to `false`
- [ ] `webpackFetchPriority` magic comment _overrides_ the global `output.scriptFetchPriority` if used also defaults to `false` 

Thoughts?

**Comment by aboktor** [comment]
My usecase requires applying it globally to every lazy loaded bundle.
If we think users will want to customize this per `import` then I think what @TheLarkInn is proposing would work quite well.

**Comment by TheLarkInn** [comment]
If you are onboard with this work as suggested, I think we are happy to take a PR for this. Can iterate on regular or draft PR. Either works!

**Comment by alexander-akait** [comment]
@aboktor Let's use `fetchPriority`, because we have built-in CSS support and it will be useful to implement for `link` too

**Comment by alexander-akait** [comment]
@aboktor i.e. I think we don't need `output.scriptFetchPriority`, we have such things for modules - https://webpack.js.org/configuration/module/#moduleparserjavascriptdynamicimportpreload, so you can specify it there

**Comment by aboktor** [comment]
@alexander-akait So basically use `module.parser.javascript.dynamicImportFetchPriority` instead?

**Comment by alexander-akait** [comment]
@aboktor Yeah, so you can apply it in different places, also `/* webpackFetchPriority: "high" */` should be supported too

**Comment by TheLarkInn** [comment]
I'm on board with this. It still applies the "global nature" for dev experience but is customizable at the module rule level and can apply to many module types.
