### ISSUE TITLE
Angular project build failed after upgrading to Webpack 5.79.0

### ISSUE THREAD

**Issue by ArturQuirino** [webpack/webpack#16981]
# Bug report

**What is the current behavior?**

After updating to version 5.79.0 I am receiving this error during the build on my angular project:

```
Error: Module parse failed: parser.destructuringAssignmentPropertiesFor is not a function
File was processed with these loaders:
 * ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js
You may need an additional loader to handle the result of these loaders.
TypeError: parser.destructuringAssignmentPropertiesFor is not a function
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Update the package to version 5.79.0 and try to build the Angular project.

**What is the expected behavior?**

No errors during the build of the project.

**Other relevant information:**
webpack version:  5.79.0
Node.js version: 14.X
Operating System: Linux
Additional tools:

**Comment by alexander-akait** [comment]
Due this https://github.com/webpack/webpack/commit/45754f45d06f01773f2c3a499591250c9c863f0e

/cc @vankop Can we return old name, looks like a breaking change

**Comment by vankop** [comment]
You are using DefinePlugin not from the same webpack version. You are using latest  DefinePlugin, but building with old webpack

Отправлено с iPad

**Comment by alexander-akait** [comment]
@ArturQuirino Can you run `npm ls webpack`?

**Comment by ArturQuirino** [comment]
```
my-app@0.0.0 /home/artur/source/my-app
├─┬ @angular-devkit/build-angular@13.3.11
│ ├─┬ @angular-devkit/build-webpack@0.1303.11
│ │ └── webpack@5.79.0 deduped
│ ├─┬ @ngtools/webpack@13.3.11
│ │ └── webpack@5.79.0 deduped
│ ├─┬ babel-loader@8.2.5
│ │ └── webpack@5.76.1 deduped
│ ├─┬ circular-dependency-plugin@5.2.2
│ │ └── webpack@5.79.0 deduped
│ ├─┬ copy-webpack-plugin@10.2.1
│ │ └── webpack@5.79.0 deduped
│ ├─┬ css-loader@6.5.1
│ │ └── webpack@5.79.0 deduped
│ ├─┬ less-loader@10.2.0
│ │ └── webpack@5.79.0 deduped
│ ├─┬ mini-css-extract-plugin@2.5.3
│ │ └── webpack@5.79.0 deduped
│ ├─┬ postcss-loader@6.2.1
│ │ └── webpack@5.79.0 deduped
│ ├─┬ sass-loader@12.4.0
│ │ └── webpack@5.79.0 deduped
│ ├─┬ source-map-loader@3.0.1
│ │ └── webpack@5.79.0 deduped
│ ├─┬ stylus-loader@6.2.0
│ │ └── webpack@5.79.0 deduped
│ ├─┬ webpack-dev-middleware@5.3.0
│ │ └── webpack@5.79.0 deduped
│ ├─┬ webpack-dev-server@4.7.3
│ │ └── webpack@5.79.0 deduped
│ ├─┬ webpack-subresource-integrity@5.1.0
│ │ └── webpack@5.76.1 deduped
│ └── webpack@5.76.1
├─┬ babel-loader@8.3.0
│ └── webpack@5.79.0 deduped
├─┬ git-revision-webpack-plugin@5.0.0
│ └── webpack@5.79.0 deduped
├─┬ webpack-subresource-integrity@1.5.2
│ └── webpack@5.79.0 deduped
└─┬ webpack@5.79.0
  └─┬ terser-webpack-plugin@5.3.7
    └── webpack@5.79.0 deduped
    
```

**Comment by alexander-akait** [comment]
Yeah, due to this `webpack@5.76.1` and `webpack@5.79.0`, we are trying to avoid such changes, but sometimes it happens, can you update webpack everywhere?, i.e.

```
webpack-subresource-integrity@5.1.0
│ │ └── webpack@5.76.1 deduped
```

**Comment by ArturQuirino** [comment]
To update everywhere I would have to update the `@angular-devkit/build-angular` to the version 16.x, because 13.3, 14.2 and 15.2 are using webpack at 5.76.1.

But I do not intend to update the angular version of the project right now. Version 16 is not even LTS yet.

I'd rather fix webpack at 5.78.0 than update  from Angular 13 to 16 right now.

**Comment by alexander-akait** [comment]
> I'd rather fix webpack at 5.78.0 then update from Angular 13 to 16 right now. 

We can't fix it here, because you have incompatibility webpack versions

> To update everywhere I would have to update the @angular-devkit/build-angular to the version 16.x, because 13.3, 14.2 and 15.2 are using webpack at 5.76.1.

You don't need to update everywhere, you need update only `webpack` in `webpack-subresource-integrity`

**Comment by ArturQuirino** [comment]
I updated the webpack-subresource-integrity to the version 5.1.0 and the error persists. Same error.

```
my-app@0.0.0 /home/artur/source/my-app
├─┬ @angular-devkit/build-angular@13.3.11
│ ├─┬ @angular-devkit/build-webpack@0.1303.11
│ │ └── webpack@5.79.0 deduped
│ ├─┬ @ngtools/webpack@13.3.11
│ │ └── webpack@5.79.0 deduped
│ ├─┬ babel-loader@8.2.5
│ │ └── webpack@5.76.1 deduped
│ ├─┬ circular-dependency-plugin@5.2.2
│ │ └── webpack@5.79.0 deduped
│ ├─┬ copy-webpack-plugin@10.2.1
│ │ └── webpack@5.79.0 deduped
│ ├─┬ css-loader@6.5.1
│ │ └── webpack@5.79.0 deduped
│ ├─┬ less-loader@10.2.0
│ │ └── webpack@5.79.0 deduped
│ ├─┬ mini-css-extract-plugin@2.5.3
│ │ └── webpack@5.79.0 deduped
│ ├─┬ postcss-loader@6.2.1
│ │ └── webpack@5.79.0 deduped
│ ├─┬ sass-loader@12.4.0
│ │ └── webpack@5.79.0 deduped
│ ├─┬ source-map-loader@3.0.1
│ │ └── webpack@5.79.0 deduped
│ ├─┬ stylus-loader@6.2.0
│ │ └── webpack@5.79.0 deduped
│ ├─┬ webpack-dev-middleware@5.3.0
│ │ └── webpack@5.79.0 deduped
│ ├─┬ webpack-dev-server@4.7.3
│ │ └── webpack@5.79.0 deduped
│ └── webpack@5.76.1
├─┬ babel-loader@8.3.0
│ └── webpack@5.79.0 deduped
├─┬ git-revision-webpack-plugin@5.0.0
│ └── webpack@5.79.0 deduped
├─┬ webpack-subresource-integrity@5.1.0
│ └── webpack@5.79.0 deduped
└─┬ webpack@5.79.0
  └─┬ terser-webpack-plugin@5.3.7
    └── webpack@5.79.0 deduped
    
```

**Comment by alexander-akait** [comment]
You still have `webpack@5.76.1`, `babel-loader` use it, update them too

**Comment by mikejpeters** [comment]
I think a lot of people using Angular + custom webpack with the Define plugin are going to run into this issue, since as stated above `@angular-devkit/build-angular` [depends specifically on `webpack@5.76.1`](https://github.com/angular/angular-cli/blob/15.2.x/packages/angular_devkit/build_angular/package.json#L64). 

Solutions I'm aware of (none are really ideal):
- `npm install` an older version of wepback like 5.78.1 that stays "compatible" with 5.76.1
- `npm dedupe` to hopefully get just one version of webpack (will be 5.76.1 for the angular scenario above) - but also dedupes other node modules

I don't know the "correct" solution here, but if it affects enough users, maybe the most user-friendly solution is to to keep webpack 5 versions compatible (i.e. don't rename methods)?

**Comment by alan-agius4** [comment]
Using the same version that `@angular-devkit/build-angular` uses does seem like a reasonable solution.  

That said, rename a non private method does sound like a breaking change to be.

Maybe the new property can be aliased with the old name, marked as deprecated and removed in the next major?

**Comment by alexander-akait** [comment]
@alan-agius4 To be honestly, it was not the public method, don't know why it was used...

**Comment by TheLarkInn** [comment]
@mikejpeters @ArturQuirino I think we should raise an issue with angular/angular-cli and coordinate with them to find a resolution for you all. I agree that this is problematic.

**Comment by mikejpeters** [comment]
@TheLarkInn maybe that's a good idea, although I guess Angular CLI treats webpack as an internal dependency and they want to avoid things breaking as well. I think this issue only happens with Angular CLI when using [@angular-builders/custom-webpack](https://github.com/just-jeb/angular-builders/tree/master/packages/custom-webpack), but in that project I don't even see a `webpack` dependency (maybe in the goal of using whatever version Angular CLI already has installed).

**Comment by TheLarkInn** [comment]
Agreed. Can I ask you to open an issue on `angular/angular-cli` so we can track this and coordinate with them also?

**Comment by alan-agius4** [comment]
@TheLarkInn  no need to open an issue. I am on the Angular team and I am following this.

Side note: from the Angular CLI point of view, by using a non official builder the user made the decision to go off the supported path. 

That said, let me have a chat with the rest of the team if we want to bump a dependency on a patch version.

**Comment by TheLarkInn** [comment]
Appreciate the quick response @alan-agius4

**Comment by alan-agius4** [comment]
We did have a chat around this and since this is not a supported use-case in this case users need to manage the versions themselves. 

Therefore in this case changing the dev dependency to match the same 
`webpack` version provided by `@angular-devkit/build-angular` is the right solution.

This could also be seen as feature request to the custom webpack builder, to provide access to the webpack used to avoid issues caused by mismatching versions.

**Comment by markwoon** [comment]
FYI, this is also a problem with @storybook/builder-webpack5.

**Comment by noorsilkaredia1** [comment]
Installing 5.78 fixed it for me for both Angular 15 and Storybook 6

**Comment by Patriksafar** [comment]
Hey, I've got same issue with webpack@5.79.0 and storybook 6 version.

@noorsilkaredia1 thank you, after downgrading to 5.78 it seems to work again.

**Comment by GeKorm** [comment]
### Storybook 6

With Yarn, using resolutions is a decent workaround `"@storybook/builder-webpack5/webpack": "5.83.1",` , eg:

##### package.json
```json
"resolutions": {
  "@storybook/builder-webpack5/webpack": "5.83.1"
}
```

Replace `"5.83.1"` with your webpack version.

This may also be possible with the **npm `overrides` field**, but I haven't tested it.

**Comment by mizozobu** [comment]
https://github.com/webpack/webpack/issues/16981#issuecomment-1507662465

I had to dedupe my webpacks. `npx yarn-deduplicate` might save your life.

https://github.com/scinos/yarn-deduplicate

**Comment by gabe-spaero** [comment]
I encountered the same message `parser.destructuringAssignmentPropertiesFor is not a function` in a different context: deploying a Next.js app to Chromatic. I ran `pnpm dedupe` and that addressed the issue. Thanks @mizozobu for the comment, it saved my Saturday 🥳

**Comment by jjinux** [comment]
This issue just became more "severe" because of [Webpack's AutoPublicPathRuntimeModule has a DOM Clobbering Gadget that leads to XSS](https://github.com/advisories/GHSA-4vvj-4cpr-p986). Hence, some people like me are desperate to get to Webpack 5.94.0 even though I'm on an old version of Angular :(

I'm going to try to see if I can work around the problem with resolutions...

**Comment by alexander-akait** [comment]
The original problem was fixed, please update to the latest stable version - `@angular/cli` and `webpack`, thank you
