### ISSUE TITLE
Image files required through url-loader/file-loader are corrupt

### ISSUE THREAD

**Issue by brianchirls** [webpack/webpack#1698]
I'm trying to require image files:

```javascript
require('../images/marble.jpg')
```
My loader configuration looks like:
```javascript
test: /\.(jpg|png)$/,
loader: 'url-loader',
query: {
	limit: 8192,
	name: 'images/[name].[ext]'
}
```

When I use image files (both png and jpg) over the limit, they are copied incorrectly. The output files are much bigger than the originals, and they are no longer correctly formatted images. They are still binary files, though, so it is difficult to tell what's going wrong. (Images below the limit work fine.)

For example, I'm using a jpg that's 61.9kb. the output log from webpack reports the file size correctly. However, the copied file is about 114kb and no browser or image viewer can open it.

(possibly related to #1668)

**Comment by karlnp** [comment]
Is your config/calling context the parent directory to images/?

**Comment by brianchirls** [comment]
My JavaScript source is at `src/js/index.js`, and my image is at `src/images/marble.jpg`. All the output files are going to `dist/`, so the output image is at `dist/images/marble.jpg`.

I know the input and output paths are correct because:
1. If I change the input path to one that doesn't exist, webpack reports an error that it's missing and refuses to build.
2. If I change the input path to a different jpg file, the resulting copied jpg file is a different size, though still broken.
3. The browser does actually load the copied jpg file, so I know the output path is correct.

**Comment by sokra** [comment]
Could you open the file with a text editor? You propably applied the url-loader twice.

**Comment by brianchirls** [comment]
I tried that, but it's all binary so I can't make sense of it.

I'm pretty sure the loader is only applied once, since it's specified in my webpack config but I'm not explicitly using it in the `require` call. Even if I were using it twice, it's not supposed to modify the jpg file, so it should just copy it cleanly twice.

**Comment by miqid** [comment]
@brianchirls, I think I may have just stumbled across the same (?) problem as you in regards to corrupt JPG images.

I also see this inflated file size effect on images in bundled distributions of my web application. For example, the original size of one arbitrary JPG file is 746KB but turns out being 1524KB in the bundled distribution folder. Similar to what you also observed, the URL paths to the images in my bundled web application are correct - it's simply the images that aren't loading because they're corrupt.

I should add that I'm also using webpack-dev-server, which actually has no problem in resolving the images and displaying the correctly in the unbundled development version of my web application.

I might try construct a bare bones project to isolate this problem.

Here's my loader configuration in case it helps:

```
{
  test: /.*/,
  loader: 'file?name=assets/[name].[ext]&context=./src/app/',
  include: [
    /assets[\\\/]images.+/,
    /assets[\\\/]data.+/
  ]
}
```

**Comment by karlnp** [comment]
I'd be interested to see a bare-bones repro.

**Comment by brianchirls** [comment]
@miqid Any chance you're using gulp and/or webpack-stream?

**Comment by brianchirls** [comment]
Looks like this was a problem with webpack-stream. It appears to be fixed by updating to v3.0.1, as patched here:
https://github.com/shama/webpack-stream/commit/6169c96fa6d666568bf1df6d9d304fa5c8fee8fd

If @miqid can confirm the fix, I'm happy to close this issue.

**Comment by miqid** [comment]
@brianchirls, thank you for the suggestion - that version bump for webpack-stream also did the trick for me! :smile:

All the minimal Webpack projects (incidentally sans Gulp and webpack-stream) I tried to construct had no JPG file corruption problems with file-loader, which left me puzzled.

**Comment by brianchirls** [comment]
Great! You're welcome, @miqid. I had the same results with a minimal webpack test project, so I figured it was gulp and then on a hunch thought I'd check out webpack-stream. It was just lucky that it was patched early this morning.

**Comment by karlnp** [comment]
Huh. The NPM ecosystem never fails to surprise me in its ability to generate intractable errors. Cool to know the resolution.

**Comment by tobycox** [comment]
Note that if you're using the babel loader, then you don't need to include a file-loader for your images. The babel loader will take care of that for you.
https://github.com/webpack/file-loader/issues/35

**Comment by felixhao28** [comment]
In my case, the produced png is actually a text file which reads like this: `export default __webpack_public_path__ + "57932d035c09d6efea1e56136cbe134f.png";`. And `57932d035c09d6efea1e56136cbe134f.png` is the real file name of that png.

I solved this by disabling url resolving in css-loader like this:

```js
rules: [
        ...,
        {
            test: /\.css$/i,
            use: ["style-loader", {
                loader: "css-loader",
                options: { url: false }
            }],
        }
]
```

Then use CopyPlugin to copy the files to the output folder:

```js
    plugins: [
        new CopyPlugin({
            patterns: [{
                from: "assets",
                to: path.resolve("../output_folder", "assets")
            }]
        })
    ],
```

This wasn't an issue before but it is after a dependencies' update.

**Comment by alexander-akait** [comment]
`file-loader` and `url-loader` is deprecated, please always read changelog when you update dependencies, you use `css-loader` v6, but `file-loader` and `url-loader` are deprecated in favor assets modules
