### ISSUE TITLE
Implement CSS Module `fetchpriority` 

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack#16999]
Yes, because you can want to set it for JS, but not for CSS and verca vice and for both, so CSS will have an own option, we need to add this to CSS todo list

_Originally posted by @alexander-akait in https://github.com/webpack/webpack/pull/16991#discussion_r1167632698_

**Comment by alexander-akait** [comment]
Let's put it there https://github.com/webpack/webpack/issues/14893, I am changing it and track all issues
