### ISSUE TITLE
typograpical error

### ISSUE THREAD

**Issue by grosfaignan** [webpack/webpack#16993]
on the page https://webpack.js.org/plugins/install-webpack-plugin

title is InstallWebpackPlugin but subject si NpmInstallWebpackPlugin (as writted here :https://webpack.js.org/plugins/ ,  see NpmInstallWebpackPlugin and follow the link ).

of course command should be 
`npm install --save-dev npm-install-webpack-plugin`

and not
`npm install --save-dev install-webpack-plugin`

**Comment by alexander-akait** [comment]
@webpack-bot move to webpack-contrib/install-webpack-plugin
