### ISSUE TITLE
declarations.d.ts is not published

### ISSUE THREAD

**Issue by hardfist** [webpack/webpack#17008]
# Bug report

**What is the current behavior?**
missing declarations.d.ts cause lots internal type to be inferred any
**If the current behavior is a bug, please provide the steps to reproduce.**
https://unpkg.com/browse/webpack@5.79.0/ not contains declrations.d.ts but the published code use declarations.d.ts type https://github.com/webpack/webpack/blob/main/lib/config/defaults.js#L26-L51

**What is the expected behavior?**
I'm not sure whether it's by design but it causes some type problem when debug webpack in node_modules( goto type definition not working)

**Other relevant information:**
webpack version:   5.79.0
Node.js version: none
Operating System: none
Additional tools: none

**Comment by alexander-akait** [comment]
We don't have `declarations.d.ts`, our types here `"types": "types.d.ts",` and they exit in 5.79.0 version...

**Comment by hardfist** [comment]
but the published code contains reference to declarations see https://unpkg.com/webpack@5.79.0/lib/index.js

**Comment by hardfist** [comment]
![image](https://user-images.githubusercontent.com/8898718/232482679-be5306e9-cd1f-4f4c-b711-b29791bbe74b.png)
it will cause these type inferred as any because lack of declarations folder

**Comment by alexander-akait** [comment]
And it is expected, you should not try to infer types inside source code in `node_modules`, even more - it will not work with other libraries which have bundle/build step

**Comment by hardfist** [comment]
oh it's ok not support infer type inside node_modules
