### ISSUE TITLE
Increase/make configurable HMR request timeout

### ISSUE THREAD

**Issue by KnutHelland** [webpack/webpack#1700]
Hi,

The 10s timeout that is hard coded here: [JsonpMainTemplate.runtime.js:29](https://github.com/webpack/webpack/blob/72e8dd01475841b5123607efd8b3c7b892c1a32a/lib/JsonpMainTemplate.runtime.js#L29) gives me trouble since rebuilding my LESS module (everything in one big module) often takes more than 10 seconds to recompile, so this request times out.

I don't know if there are benefits of having this so low. Can it be increased? Or made configurable in some way so I can easily increase myself?

The similar timeout in [WebWorkerMainTemplate.runtime.js#L23](https://github.com/webpack/webpack/blob/72e8dd01475841b5123607efd8b3c7b892c1a32a/lib/webworker/WebWorkerMainTemplate.runtime.js#L23) is hard coded as well.

_I know it is not optimal to have such a big module taking that long time to recompile. In fact, watching the less code with grunt or gulp seems to go much faster, so Webpack is probably not ideal for this. But it simplifies things since I don't need another live reload mechanism for the stylesheet._

Knut

**Comment by paraboom** [comment]
PR was merged, you can close that issue.
