### ISSUE TITLE
How to abort compilation using plugin API

### ISSUE THREAD

**Issue by mdreizin** [webpack/webpack#1702]
Hello @sokra,

I would like to abort compilation based on some conditions:

``` js
function abortIf(callback) {
    callback(true);
}

function AbortCompilationPlugin() {}

AbortCompilationPlugin.prototype.apply = function(compiler) {
    abortIf(function(flag) {
        if (flag === true) {
            // TODO abort compilation
        }
    });
};
```

How to do it via plugin API?

**Comment by nickdeis** [comment]
@mdreizin 
I would highly recommend seeing if (callback-loader)[https://github.com/Kreozot/callback-loader] fits your needs here.

**Comment by mdreizin** [comment]
@nickdeis Thanks, but it's not something I was looking for :(

**Comment by sokra** [comment]
At which point do you want to abort the compilation?

**Comment by mdreizin** [comment]
@sokra Currently I'm developing functionality which prevents to compile `webpack.config.js`  in `run` mode if nothing changes. It mostly to improve completion speed of "heavy" configs.

My API tries to compare custom dependency tree: during initial phase it restores previous dependency tree form the file and tries to compare with current one. If they are equal then I would like to abort compilation. If they are not equal then I would like to compile.

**Comment by msand** [comment]
Next.js would also like to cancel compilation if you make a change and quickly afterwards make another change: https://github.com/zeit/next.js/issues/1083

**Comment by TheLarkInn** [comment]
@msand you could see how Nuxt is doing it. They have a pretty quick process for this.

**Comment by elpddev** [comment]
Is there an easy way to do this in webpack4?
