### ISSUE TITLE
AST was illegal after webpack process

### ISSUE THREAD

**Issue by quanru** [webpack/webpack#17030]
# Bug report

**What is the current behavior?**
We say a entry file src/index.js, when bundle with webpack, there are two version ast:

- ast/ast-1.json is a ast snapshot in https://github.com/webpack/webpack/blob/main/lib/javascript/JavascriptParser.js#L3465

- ast/ast-2.json is a ast snapshot in https://github.com/webpack/webpack/blob/v5.80.0/lib/javascript/JavascriptParser.js#L3475

the ast-1.json is legal, but ast-2.json is illegal(can't not be traversed by acorn-walk and can't not restore to source code)

it seems due to https://github.com/webpack/webpack/blob/v5.80.0/lib/javascript/JavascriptParser.js#L2489

more detail see demo: https://github.com/quanru/webpack-ast-demo

**If the current behavior is a bug, please provide the steps to reproduce.**

git pull the demo, and debug JavascriptParser.js file

**What is the expected behavior?**

ast is walkable and recoverable

**Other relevant information:**
webpack version:  5.80.0
Node.js version: 16.18.1
Operating System: Mac OS
Additional tools: none

**Comment by xiaoboost** [comment]
I think the problem is where:

https://github.com/webpack/webpack/blob/386201511c13a5501106df69492f122a6a5c1eb3/lib/javascript/JavascriptParser.js#L2485

The variable `scopeParams` should not use AST arr ref, a new array should be created instead.

```ts
const scopeParams = expression.params.slice();
```
