### ISSUE TITLE
Investigate breaks in experiments for webpack on `performance-benchmark`.

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack#17036]
1. Fork or clone: https://github.com/TheLarkInn/performance-compare
2. Add `experments.futureDefaults` & `experiments.lazyCompilation` to both babel and swc webpack configurations 
3. Run the individual start command `npm run start:webpack`
4. Open the dev server link

Expected Output: 
- webpack dev mode loads the page just like all the other benchmarks do

Actual Outcome: 
- Console errors related to `lazyCompilation`
![image](https://user-images.githubusercontent.com/3408176/233437790-aa559634-c6ea-4deb-95f1-343d23aa0912.png)

- Console errors related to `futureDefaults`
![image](https://user-images.githubusercontent.com/3408176/233437001-dc0e9466-6b6b-48cd-83f9-91f0e356409b.png)

**Comment by TheLarkInn** [comment]
I believe since there isn't many integrations that this is caused by: https://github.com/pmmmwh/react-refresh-webpack-plugin

**Comment by alexander-akait** [comment]
@TheLarkInn Is it broken?

**Comment by TheLarkInn** [comment]
I think this plugin breaks when used with `experiments.futureDefaults` and `experiments.lazyCompilation`. We can reduce further if needed but the original repo should be enough to triage I think. cc @pmmmwh

**Comment by TheLarkInn** [comment]
My concern is that this is a very popular plugin for webpack+react users so we should prioritize futureproofing finding the bugs in the plugin for when we enable these future defaults and features.

**Comment by alexander-akait** [comment]
Yeah, agree

**Comment by hardfist** [comment]
I'm digging this issue to investigate how webpack rebuild can become, and find it's the `experiments.css:true` and `node.global:warn` cause the runtime error and warning.
this config works on my machine
```js
module.exports = 
{
   node: {
    global: false,
  },
  experiments: {
    css:false,
    futureDefaults:true
  }
}
```

**Comment by pmmmwh** [comment]
Bump - I'll try to investigate this soon and hopefully we can figure out what's wrong

**Comment by alexander-akait** [comment]
bump

**Comment by hardfist** [comment]
@alexander-akait  I investigated it before, it's not related to react-refresh-webpack-plugin, it's caused by futureDefault enable experiments.css by default which conflicts with style-loader, so disable experiments.css could solve this

**Comment by alexander-akait** [comment]
@hardfist oh, thank you, I think we need to send a fix there
