### ISSUE TITLE
Webpack Dynamic Module Error Management Problem | 

### ISSUE THREAD

**Issue by thevobos** [webpack/webpack#17037]
Hello,

I want to check if there is a wrong module name but I couldn't do it with async or try-cath. how can i solve this?

My Code:

function loadComponent(scope, module) {
     return async() => {
         await __webpack_init_sharing__("default");
         const container = window[scope];
         await container.init(__webpack_share_scopes__.default);
         const factory = await window[scope].get(module);
         const Module = factory();
         return Module;
     };
}

"Module "./AppModule" does not exist in container. "

I am getting this error code. I'm trying Try-Catch or a different control, it doesn't work, how can I solve it?

const Component = React.lazy( loadComponent(props.scope, props.module) );

        return (
                <Suspense fallback={<LoadView status={"loading"} title={"Module Loading"}/>}>
                    <Component {...props?.props} />
                </Suspense>
        );

**Comment by alexander-akait** [comment]
Close in favor https://github.com/webpack/webpack/discussions/17035

Please do not duplicate, it is a bug tracker, for questions/dicussion we have https://github.com/webpack/webpack/discussions, will be patient, there are other developers here with their own issues/questions
