### ISSUE TITLE
webpack should support publicPath with different port for testing on mobile devices

### ISSUE THREAD

**Issue by jedwards1211** [webpack/webpack#1703]
It's hard to integrate `webpack-dev-server` with an existing server like Meteor and then load the page on a mobile device connected to my dev machine via LAN.

The problem is that while `publicPath: "http://localhost:8080/"`  (or `publicPath: "http://0.0.0.0:8080"`) works for testing the page on my dev box, they don't work for testing the page on a mobile device.

If Webpack simply supported config like this it would solve the problem:
```js
output: {
  publicPath: "/",
  publicPort: 8080,
}
```
Meaning that if I load a resource `doge.png` with `url-loader`, the bundle will request it from `<page base URL>:8080/doge.png` and will load properly on a mobile device.

**Comment by sokra** [comment]
``` js
output: {
  publicPath: "//" + require("os").hostname() + ":8080/"
}
```

**Comment by jedwards1211** [comment]
That's an interesting idea, I didn't think about trying that way.  I wonder if it will be possible to resolve my dev machine via hostname over a public WLAN though?

**Comment by jedwards1211** [comment]
In any case thanks to getting websocket proxying to work, this isn't really a problem for me anymore

**Comment by thenewguy** [comment]
This is still a problem for me.  I thought all was dandy when I got going with `publicPath: "http://0.0.0.0:8080"` but I've hit this now that I am trying to test over LAN.  Your suggestion on the hostname won't work because my app dev server is a vagrant box and the hostname isn't resolvable off the host

**Comment by bpinto** [comment]
Same problem here, @jedwards1211 could you give an example of what you did?

**Comment by jedwards1211** [comment]
Can't remember...in any case is there a technical reason why having `url-loader` request an image as just `/doge.png` (letting the browser fill in the host being used) is unsupported?
