### ISSUE TITLE
Large wasm file adds significant build latency

### ISSUE THREAD

**Issue by Dig-Doug** [webpack/webpack#17044]
# Bug report

**What is the current behavior?**

I am trying to load a large wasm file into my web app. The build works, however it's incredibly slow:

```bash
npx webpack --mode development                                                                                                   
asset c37ad502f0b49101ff66.module.wasm 22.6 MiB [emitted] [immutable] (auxiliary name: main)
asset main.js 797 KiB [emitted] (name: main)
runtime modules 4.99 KiB 10 modules
cacheable modules 610 KiB (javascript) 22.6 MiB (webassembly)
  modules by path ./wasm/pkg/ 78.7 KiB (javascript) 22.6 MiB (webassembly)
    ./wasm/pkg/wasm.js 139 bytes [built] [code generated]
    ./wasm/pkg/wasm_bg.js 74.5 KiB [built] [code generated]
    ./wasm/pkg/wasm_bg.wasm 4.04 KiB (javascript) 22.6 MiB (webassembly) [built] [code generated]
  ./src/index.js 344 bytes [built] [code generated]
  ./node_modules/lodash/lodash.js 531 KiB [built] [code generated]
webpack 5.80.0 compiled successfully in 25725 ms
```

**If the current behavior is a bug, please provide the steps to reproduce.**

I have created a small project that reproduces the problem based on the webpack quickstart [here](https://github.com/Dig-Doug/bug-reproductions/tree/webpack-wasm-slow). To reproduce, do:

```bash
cd /tmp
git clone -b webpack-wasm-slow https://github.com/Dig-Doug/bug-reproductions.git
cd bug-reproductions/webpack-wasm-slow/
npm install
npx webpack --mode development
```

The wasm library is built from a rust library. I have included the generated JS/wasm files so you do not need to build them, but if you would like to regenerate them you can do the following:

- Setup rust: https://www.rust-lang.org/learn/get-started
- Setup wasm-pack: https://github.com/rustwasm/wasm-pack
- Do:

```bash
cd wasm
wasm-pack build
```

**What is the expected behavior?**

I do not need the wasm file to optimized or changed in any way. As far as I can tell, webpack is not modifying the file so I'd expect the wasm file to not impact the build latency significantly.

**Other relevant information:**
webpack version:   5.80.0
Node.js version: v16.13.1
Operating System: Ubuntu
Additional tools: n/a

**Comment by Dig-Doug** [comment]
After profiling webpack, I believe this issue is caused by the wasm parser. I've opened a PR to fix the underlying issue.

**Comment by alexander-akait** [comment]
Yeah, I start to looking into this and found webpack doesn't do something special here
