### ISSUE TITLE
Cannot resolve Windows paths

### ISSUE THREAD

**Issue by falsandtru** [webpack/webpack#17043]
# Bug report

**What is the current behavior?**

Webpack cannot resolve Windows paths.

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/falsandtru/spica/blob/v0.0.719/webpack.config.js doesn't work with the latest glob.

```
{
  entry: glob.sync('./src/**/*.ts', { dotRelative: true }),
}
```

```
ERROR in main
Module not found: Error: Can't resolve '.\src\uuid.ts' in '...'
Did you mean './.\src\uuid.ts'?
Requests that should resolve in the current directory need to start with './'.
Requests that start with a name are treated as module requests and resolve within module directories (node_modules).
If changing the source code is not an option there is also a resolve options called 'preferRelative' which tries to resolve these kind of requests in the current directory too.
```

**What is the expected behavior?**

No error.

**Other relevant information:**
webpack version:  5.80.0
Node.js version: 19.9.0
Operating System: Win 10
Additional tools: glob 10.2.1

**Comment by alexander-akait** [comment]
You can't use `'.\src\uuid.ts'`, you need to use aboslute path or url or relative linux paths, `'.\src\uuid.ts'` is invalid path
