### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by ajsharp** [webpack/webpack#1706]
I've noticed that when either webpack (in watch mode) or webpack-dev-server is running, each process consistently consumes about 50% CPU. This seems relatively high for something that should be sitting relatively idly waiting for files to change. Is this a webpack limitation or a node one? Thanks!

**Comment by DLMR** [comment]
This was partially answered by @sokra on Gitter.
> @ajsharp compilation is expensive. It consumes a full CPU. If you have a dual core -> 50%.

**Comment by ajsharp** [comment]
Right, but the process consumes 50% even while its idle, not compiling
anything.

**Comment by sokra** [comment]
Do you have polling enabled for watching?

**Comment by ajsharp** [comment]
I don't.

**Comment by ajsharp** [comment]
When polling is off, does webpack use file system change hooks of some kind?

**Comment by ajsharp** [comment]
I think maybe this was due to `fsevents` not being installed properly? I have it installed now and CPU usage seems to be much lower.

**Comment by tomasholub** [comment]
Yes, it could be related to fsevents not being installed properly. I had an old version of node.js (v0.10.26) and fsevents didn't install. My CPU usage was 130% all the time when running gulp from webpack. I reinstalled node to v5.3.0 and reinstalled all the modules. This time fsevents installed correctly. And my CPU usage from gulp (devpack) is back to zero when idle.

**Comment by phallstrom** [comment]
FWIW, on OSX, if you're locked to an older version of `chokidar` (part of watchpack) it won't install `fsevents` automatically. Running `npm install fsevents` worked for me and dropped my CPU usage completely.

You can see if webpack is polling using `sudo fs_usage -f pathname -w` and watch for lines with `node` at the end. If you see thousands of them, you're polling.

**Comment by mattkime** [comment]
just came across this and found it _very_ helpful in fixing my own problems. 

i wonder if it would be possible for webpack to provide a warning when file polling is going nuts.

**Comment by laggingreflex** [comment]
Facing the same issue but on Windows 10, and I can't install fsevents, [it's an OS X-only module](https://github.com/strongloop/fsevents/issues/132)...

**Comment by Venryx** [comment]
I'm on Windows 10, and after installing the latest version of Node, I was able to turn polling off and get my cpu usage to drop to <1% (from ~8% constantly). I couldn't do this before because polling-mode was the only way it would consistently pick up my file-saves.

Now I can, I assume because the latest version of Node had the fsevents module install correctly this time. (I know at one point before I was getting a warning about fsevents not being installed or something, which I don't seem to get anymore--I forget where I saw it, so I can't verify for certain)

**Comment by umermughal** [comment]
I'm using Windows 7 and after upgrading Node version to latest my cpu drops to almost zero. One more thing if you were using polling = true in settings then don't forget to change it to false.

**Comment by lekhnath** [comment]
45+% cpu usage reduced to <8% by adding `ignored: /node_modules/` to `watchOptions` config option of webpack-dev-server

**Comment by vjpr** [comment]
Chokidar (the library used to watch files in webpack) does not report an error if `fsevents` fails to be required. You can add a console.log statement to see why it is failing to be required. I created an issue here: https://github.com/paulmillr/chokidar/issues/599

**Comment by tashrifbillah** [comment]
I used:
```js
  watchOptions: {
    ignored: /node_modules/,
  },
```

But that didn't help. Linking the documentation of [watchOptions](https://webpack.js.org/configuration/watch/#watchoptionsignored) for future Googlers regardless.
