### ISSUE TITLE
webpack does not produce all assets during build when lazyCompilation experiment is enabled

### ISSUE THREAD

**Issue by burhanuday** [webpack/webpack#17086]
# Bug report

[lazyCompilation](https://webpack.js.org/configuration/experiments/#experimentslazycompilation) webpack experiment should only be enabled for development server. In most cases, when running `build` command, the expectation is to generate all assets at build time.

The `lazyCompilation` experiment is more useful for development server to improve startup times.

Keeping it enabled for builds will result in missing assets and webpack does not show a warning for this either 

**What is the current behavior?**

webpack silently does not output assets for files which are lazily compiled

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

during `build` mode, webpack should output all assets irrespective of `lazyCompilation` value

**Other relevant information:**
webpack version: 5.72.0  
Node.js version: 18
Operating System: MacOS
Additional tools: -

**Comment by alexander-akait** [comment]
Please create reproducible test repo

**Comment by alexander-akait** [comment]
Because it is lazy we build only imported assets, not all assets
