### ISSUE TITLE
ERROR in main Module not found: Error: Can't resolve './src' in 'project'

### ISSUE THREAD

**Issue by Kranthi32** [webpack/webpack#17092]
please help me on this issue.

ERROR in main
Module not found: Error: Can't resolve './src' in 'project'
resolve './src' in 'project'
  using description file: project\package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: project\package.json (relative path: ./src)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        project\src doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        project\src.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        project\src.json doesn't exist
      .wasm
        Field 'browser' doesn't contain a valid alias configuration
        project\src.wasm doesn't exist
      as directory
        project\src doesn't exist

webpack 5.80.0 compiled with 1 error in 71 ms

**Comment by alexander-akait** [comment]
Close in favor https://github.com/webpack/webpack/discussions/17091

**Comment by Judahmeek** [comment]
To anyone here from a search engine, `ERROR in main Module not found: Error: Can't resolve './src'` likely means that one or more of your configured `entry` values results in `undefined` & webpack is trying to use [its default entry value](https://github.com/webpack/webpack/blob/main/lib/config/defaults.js#L174), which doesn't exist in your codebase.
