### ISSUE TITLE
Satisfy version miscomputed

### ISSUE THREAD

**Issue by alessandro308** [webpack/webpack#17090]
# Bug report

Running the function `satisfy` from https://github.com/webpack/webpack/blob/main/lib/util/semver.js results in a possible bug. Specifically:
```
satisfy(['^3.0.0'], '3.0.0-dev.5') === false
satisfy(['3.0.0-dev.5'], '3.0.0-dev.5') === false
satisfy(['^3.0.0'], '3.0.0') === true
```
but I expect 3.0.0-dev.5 to be greater than 3.0.0 so I expect the function to return true. Am I wrong?

**Comment by alexander-akait** [comment]
It is by design, we don't support `-dev.5` currently to reduce runtime size (feel free to update our docs), but maybe we revisit it https://github.com/webpack/webpack/pull/16945
