### ISSUE TITLE
missing Documentations

### ISSUE THREAD

**Issue by grosfaignan** [webpack/webpack#17104]
## Feature request
here is the problematic url : https://webpack-v3.jsx.app/api/module-factories/

**What is the expected behavior?**
documentation missing

**What is motivation or use case for adding/changing the behavior?**

**How should this be implemented in your opinion?**
with detailed examples...

**Are you willing to work on this yourself?**
no

**Comment by alexander-akait** [comment]
Please use the latest version, webpack 3 is deprecated and please open an issue in https://github.com/webpack/webpack.js.org and **describe in details what is missing**, thank you
