### ISSUE TITLE
Complex paths breaks watch functionality

### ISSUE THREAD

**Issue by koutsenko** [webpack/webpack#1711]
I've created a simple project for education purposes.
When project has complex path like "/home/kds/files/! STUDY/learn.javascript.ru/code"

"Watch" feature completely breaks, it waits silently while I editing sources and do nothing.
So moving files to something like "/home/kds/code" resolves issue.

**Comment by sokra** [comment]
webpack doesn't support `!` in paths. Sorry, but you need to rename that folder if you want to use webpack here.
