### ISSUE TITLE
Weird exclude behaviour

### ISSUE THREAD

**Issue by gregersrygg** [webpack/webpack#1712]
A few of our developers were not able to build one of our projects. Even with exactly the same dependencies on the same hardware. After lots of debugging I found out that the source-map-loader plugin was not used on their computers because we exclude `/(?:src)/`, and they had checked out the project in a folder named 'src' (a parent folder of the project).

Here is the relevant part of webpack.config.js:
```js
        preLoaders: [
            {
                test: /\.js$/,
                loader: "source-map-loader",
                exclude: /(?:src)/,
                include: /(?:node_modules)/
            }
        ]
```

So if the project is stored in `/Users/foo/src/project/`, then the `source-map-loader` would never match any files.

Is this a bug or intended behavior? I would have expected that it only checked against a relative path from the project folder. It was very hard to trace down what the cause of this problem was.

I have started on making a reduced example to reproduce the problem, but thought it would be smart to ask first if this is intended behaviour or not. Can also try to make a fix if that is desiarable.

**Comment by gregersrygg** [comment]
I have now created a minimal reproducible example here: https://github.com/gregersrygg/webpack-exclude-bug-example

**Comment by sokra** [comment]
Instead of using RegExps for `include` and `exclude` you should better use absolute paths: 

``` js
{
                test: /\.js$/,
                loader: "source-map-loader",
                exclude: path.resolve(__dirname, "src"),
                include: path.resolve(__dirname, "node_modules")
}
```

**Comment by gregersrygg** [comment]
Ok, thanks. I updated the docs: https://github.com/webpack/docs/wiki/configuration/_compare/b8eaacdd7a7b41b54fe59afdba6e277966ec0298...e4cb780ed3228a6c15e8d003e6c7bfd90cd60e16
