### ISSUE TITLE
Updating worker example to output ESM, async worker chunk fails to load

### ISSUE THREAD

**Issue by jasonsanjose** [webpack/webpack#17125]
# Bug report

**What is the current behavior?**

Example branch https://github.com/webpack/webpack/pull/17124 built on top of in-repository `examples/worker`. This branch changes the example to output ESM.

Runtime error when loading an async ESM worker chunk:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at installChunk (http://localhost:8080/dist/workers/fibonacci.js:521:25)
    at async Promise.all (index 0)
    at async onmessage (webpack:///./fib-worker.js?:2:24)
installChunk @ fibonacci.js:521
```

**If the current behavior is a bug, please provide the steps to reproduce.**

```bash
# update to include webpack-dev-server
$ yarn
# cd examples/workers
$ ../../bin/webpack.js serve --config webpack.config.js --mode development
```

1. Run the above commands to launch a dev server
2. Open http://localhost:8080
3. Change value of third input `<input id="fib2" type="number">`
4. Observe runtime errors:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at installChunk (http://localhost:8080/dist/workers/fibonacci.js:521:25)
    at async Promise.all (index 0)
    at async onmessage (webpack:///./fib-worker.js?:2:24)
installChunk @ fibonacci.js:521
```

```javascript
// examples/worker/fib-worker.js
onmessage = async event => {
        // THIS chunk fails to load 😢 
	const { fibonacci } = await import("./fibonacci");
	/* ... */
};
```

<img width="1424" alt="Screenshot 2023-05-02 at 1 51 45 PM" src="https://user-images.githubusercontent.com/1148713/235785165-6430fff4-455d-48ea-964f-b1be690f2bfe.png">

**What is the expected behavior?**

Async ESM chunks in workers appear to be supported but in this simple example a runtime error occurs.

**Other relevant information:**
webpack version:  5.81.0
Node.js version: 16.14.2
Operating System: macOS 13.2.1
Additional tools:

**Comment by alexander-akait** [comment]
@jasonsanjose Weird, I can't reproduce your problem... Do you use the latest version? Can you provide more infromation? I jsut install webpack-dev-server and run `../../bin/webpack.js serve --config webpack.config.js --mode development --static .`

Do you try to import this as ESM (i.e. `type="module"`)?
