### ISSUE TITLE
ProvidePlugin does not work inside require()

### ISSUE THREAD

**Issue by pavel06081991** [webpack/webpack#1715]
I'm using provide plugin for my own appConfig module. When I use appConfig variable like this:
```javascript
var currentTheme = appConfig.currentTheme;
```
it works. But if I use it like this:
```javascript
var siteStyles = require('./themes/' + appConfig.currentTheme + '/' + appConfig.currentThemeDirection + '/site.sass');
```
it does not work and when I open my site page I get the next error message:
"Uncaught ReferenceError: appConfig is not defined"

**Comment by bebraw** [comment]
[require.context](https://webpack.github.io/docs/context.html) might do the trick perhaps. The problem is that Webpack doesn't support dynamic cases like that. You need to set up a context and require from there. Let me know if this works for you.

**Comment by pavel06081991** [comment]
Yes, if to use require.context it works.
