### ISSUE TITLE
Chunks generated with require.ensure do not respect output path

### ISSUE THREAD

**Issue by phaistonian** [webpack/webpack#1716]
Hello.

```javascript
require.ensure(['../public/js/test-ensure.js'], function(require) {
  let test = require('../public/js/test-ensure.js');
  console.log(test);
});
```

The above code works fine in dev, yet in production (-p) results in loading the generared chunks from the current path and not the path set for output in the config.

Additionally, if I have a `<base ..>` set in my `<head>` then the script being loaded (chuck) points to the `baseUri/chunk.js` and that's (of course) not found.

How do I tell webpack where to look for the chunk, or how do I make it "respect" the webpack.config.output path and not use the current path?

Thank you.

**Comment by phaistonian** [comment]
As I noticed, `__webpack_require__.p` is, perhaps, the key to resolve this.

**Comment by saknarak** [comment]
I issued with this problem.
Now I solved this issue by add trailing slash

  output: {
    path: path.resolve('./dist/public/js'),
    publicPath: '/js/',
    filename: '[name].js',
    chunkFilename: '[name]-[chunkhash].js',
  },

**Comment by lvv83** [comment]
You can specify path inside `filename` and `chunkFilename` properties:
``` js
output: {
   filename: 'scripts/[name]-[chunkhash].js',
   chunkFilename: "scripts/[chunkhash].js"
}
```

**Comment by StrongerSY** [comment]
I also encounter this problem ! The chunk files' paths are all relative to my website root url ~ But I can't set the path of chunkfile

**Comment by OmarMakled** [comment]
I got the same issue with  `webpack 2.4.1` 

You should define publicPath `/` is important 

```
    output: {
       path: path.join( __dirname, 'dist' ),
       publicPath: path.join( __dirname, 'dist/' ),
       filename: '[name].js',
       chunkFilename: '[name].js'
    }
```
