### ISSUE TITLE
Help with finding Bundler Resolving Method/Logic

### ISSUE THREAD

**Issue by Galcarmi** [webpack/webpack#17172]
Hey guys,

following this issue https://github.com/webpack/enhanced-resolve/issues/382 (enhance-resolved issue)

i need to find the method/logic which webpack uses to resolve packages entrypoints.

meaning, given `target = 'webworker'` && `packageJsonPath == 'somepath'` i want to get the package worker entrypoint.
so lets say i have this Package.json in `packageJsonPath == 'somepath'` i want it to return `"./dist/index-worker.js"`
```
      {
        name: "sampleModuleWithMultipleEntries",
        version: "0.0.1",
        main: "./dist/index.js",
        browser: "./dist/index-browser.js",
        exports: {
          ".": {
            module: {
              node: "./dist/index-node.js",
              worker: "./dist/index-worker.js",
              browser: "./dist/index-browser.js",
              default: "./dist/index-node.js",
            },
            default: "./dist/index-node.js",
          },
          "./package.json": "./package.json",
        },
```

can anyone help me find where this logic is implemented in webpack?

**Comment by alexander-akait** [comment]
Close in favor https://github.com/webpack/enhanced-resolve/issues/382, please don't duplicate issues
