### ISSUE TITLE
ModuleFederationPlugin reading shared package version from incorrect package.json

### ISSUE THREAD

**Issue by crshmk** [webpack/webpack#17188]
# Bug report

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

I have a `ModuleFederationPlugin` shared dependency configured as 

```javascript
shared: {
  ...,
  ramda: {
    requiredVersion: '^0.29.0',
  }
}
```

but I get this error: 
`
WARNING in shared module ramda -> path_to_project/node_modules/ramda/es/index.js
No version specified and unable to automatically determine one. No version in description file (usually package.json). Add version to description file path_to_project/node_modules/ramda/es/package.json, or manually specify version in shared config.
`

This is because ramda versions itself in `node_modules/ramda/package.json`, not `node_modules/ramda/es/package.json`.

`node_modules/ramda/es/package.json` is simply 
```json
{"type":"module"}
```

and if i edit it to 
```json
{"type":"module", "version": "^0.29.0"}
```

the above error is solved. 

---
**What is the expected behavior?**

`ModuleFederationPlugin` should read a version from `package.json` at the root of the package when a subfolder does not specify it.

---

**Other relevant information:**
webpack version:  5.81.0
Node.js version: 19.6.0
Operating System: macOS 12.06 Monterey
Additional tools:

**Comment by alexander-akait** [comment]
Sorry, please always have version
