### ISSUE TITLE
import error @schema-utils

### ISSUE THREAD

**Issue by misak-yt** [webpack/webpack#17187]
when i build tsconfig.json with ”tsc -b tsconfig”

```
node_modules/webpack/types.d.ts:91:10 - error TS2305: Module '"schema-utils/declarations"' has no exported member 'validate'.

91 import { validate as validateFunction } from "schema-utils";
            ~~~~~~~~


Found 1 error.
```

i fixed at node_modules\webpack\types.d.ts from
`import { validate as validateFunction } from "schema-utils"`
to
`import { default as validateFunction } from "schema-utils/declarations/validate";`

**Comment by alexander-akait** [comment]
Sorry, not related to webpack
