### ISSUE TITLE
HookWebpackError: Cannot read property 'e' of undefined

### ISSUE THREAD

**Issue by jfnault-seedbox** [webpack/webpack#17213]
# Bug report

Since we run npm update and got 5.83, build script fail with this error:

Creating an optimized production build...
Failed to compile.

HookWebpackError: Cannot read property 'e' of undefined
-- inner error --
TypeError: Cannot read property 'e' of undefined
Generated code for /sources/xxx/encoding/web/node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[1]!/sources/xxx/encoding/web/node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[1].oneOf[5].use[2]!/sources/xxx/encoding/web/node_modules/source-map-loader/dist/cjs.js!/sources/xxx/encoding/web/src/App.css
 1 | __webpack_require__.r(__webpack_exports__);
 2 | /* harmony import */ var _node_modules_css_loader_dist_runtime_sourceMaps_js__WEBPACK_IMPORTED_MODULE_0__ = 

**Other relevant information:**
webpack version:  5.83.0
Node.js version: >14
Operating System: ubuntu

**Comment by vikvikvr** [comment]
Same here.

The log ends with `d.e.f.a.u.l.t`, not sure if the issue is there

/* harmony default export */ __webpack_exports__.d.e.f.a.u.l.t = (___CSS_LOADER_EXPORT___);

**Comment by CristinaSolana** [comment]
+1

**Comment by anndro** [comment]
same here. rollback to webpack@5.82.1 solved issue for now.

` error  in ./node_modles/@yartu/ui-kit/assets/css/tailwind-input.css

Syntax Error: HookWebpackError: Cannot read properties of undefined (reading 'e')
-- inner error --
TypeError: Cannot read properties of undefined (reading 'e')
`

**Comment by alexander-akait** [comment]
And no one provide an example of the problem?

**Comment by TheLarkInn** [comment]
If you can provide a small reproducible example that would be very helpful 🙏

**Comment by alexander-akait** [comment]
WIP

**Comment by eclipse-reality-steven** [comment]
This has happened in all of our build pipelines as well. We believe this is happening after this npm update went to this version of webpack. 

![image](https://github.com/webpack/webpack/assets/122565506/8ed21ec4-6917-4168-a062-18860b7b0fa6)


![image](https://github.com/webpack/webpack/assets/122565506/ab6bf92d-b620-47cc-a662-9daaeb688149)

**Comment by Barron-Brock** [comment]
Reverting my version of webpack seems to be a temporary fix

```
  "overrides": {
    "webpack":"5.82.1"
  },
```

**Comment by alexander-akait** [comment]
Found a bug, fix will be soon

**Comment by EapRules-Revolt** [comment]
> Found a bug, fix will be soon

🌈

**Comment by techbridgedev** [comment]
I'm getting the same error on my Vercel deployment. FWIW I can build locally (Docusaurus 2.0)

**Comment by Vrq** [comment]
Anyone has an idea why this breaks existing production builds which contained no changes?

**Comment by TheLarkInn** [comment]
> I'm getting the same error on my Vercel deployment. FWIW I can build locally (Docusaurus 2.0)

This is specifically a regression targeting mini-css-extract-plugin. Production builds will see this instead of local development builds (which do not use the plugin). Fix in progress we just need to add a test case which will cover this scenario so we can confidently make changes to this code in the future. I'll ship a bugfix patch today once finished. 

Thanks for the patience all 😊

**Comment by alexander-akait** [comment]
Please update https://github.com/webpack/webpack/discussions/17217

**Comment by jensenbox** [comment]
If you have come here because your CI builds have been failing today, the following would be a very good read: https://github.com/yarnpkg/yarn/issues/4147
