### ISSUE TITLE
OccurrenceOrderPlugin misspelled in docs

### ISSUE THREAD

**Issue by graue** [webpack/webpack#1722]
Hi, although the correct spelling has been accepted in Webpack itself for awhile, and is mandatory in the Webpack 2.0 betas, [the list of plugins in the docs](https://webpack.github.io/docs/list-of-plugins.html) still shows it as OccurenceOrderPlugin.

(Is there a GitHub repo for the website where I can contribute PRs? I couldn't find it.)

**Comment by shama** [comment]
The docs are freely editable here: https://github.com/webpack/docs/wiki/list-of-plugins/_edit Thanks!

**Comment by shama** [comment]
Fixed: https://github.com/webpack/docs/wiki/list-of-plugins/0593e4b154446d86bbc3b4d11e68697badc17562
