### ISSUE TITLE
Scrollbar not visible in sidebar.

### ISSUE THREAD

**Issue by Riyan911** [webpack/webpack#17232]
# Bug report

**What is the current behavior?**
Scrollbar is not visible in microsoft edge linux. 
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  
Node.js version:
Operating System:
Additional tools:

**Comment by alexander-akait** [comment]
Sorry, not related to webpack

**Comment by Riyan911** [comment]
I'm sorry I didn't provide complete information on the issues. The actual issues it this:
##

![Screenshot from 2023-05-20 21-51-33](https://github.com/webpack/webpack/assets/107925299/79c37f45-c306-43a8-85e2-c88ed195c155)

##
<h2>The scrollbar on the left hand side is unscrollable. The browser I'm using is MS Edge and my OS is Ubuntu.</h2>

**Comment by alexander-akait** [comment]
Can you capture video and open dev tools?

**Comment by Riyan911** [comment]
Sure

**Comment by Riyan911** [comment]
[Screencast from 20-05-23 10:30:57 PM IST.webm](https://github.com/webpack/webpack/assets/107925299/0ac81d21-928c-4f5f-8ef1-e4212449e7e2)

**Comment by alexander-akait** [comment]
@webpack-bot move to webpack/webpack.js.org
