### ISSUE TITLE
Render a component server side

### ISSUE THREAD

**Issue by ateev** [webpack/webpack#1723]
I have a react component. `<myFooter>`. It is a simple footer.
```
import React from 'react';
import './my-footer.scss';

export default class myFooter extends React.Component {
  render() {
    return (
    <footer className="col-xs-12">
      hello !
    </footer>
    );
  }
}
```
I want to render it from the server-side. On the backend, I have an express server. For that I wrote this:
```
import myFooter from '../components/my-footer.jsx';

app.get('/footer', function(req, res) {
  var string1 = ReactDOMServer.renderToString(myFooter);
  res.send(string1);
});
```
Now the problem is that server cannot read sass files. For client side rendering, I am using webpack. Webpack builds everything and gives a bundle file.

But i'm not sure what happens if its the server side. How can I compile using webpack. If I can, will i need to compile my app for each request on node server ?

**Comment by sokra** [comment]
> How can I compile using webpack.

`target: "node"`

> If I can, will i need to compile my app for each request on node server ?

No you can compile it once.
