### ISSUE TITLE
webpack crashes my system when run for ~30 mins

### ISSUE THREAD

**Issue by seekshiva** [webpack/webpack#1724]
I have a MacBook Air with 4GB ram. When `webpack -w` is run for longer duration, my laptop starts heating up and my laptop just freezes and gets damn slow.

When I checked the activity monitor, it says the process 'node' is taking up 80-90% CPU... when i kill webpack, the system runs smoothly again.

I've been developing with webpack for 5-6 months now.. I've started to notice the issue a lot only in the last few weeks.

Any help would be deeply appreciated.

**Comment by seekshiva** [comment]
![screen shot 2015-12-08 at 4 07 42 pm](https://cloud.githubusercontent.com/assets/484349/11653705/dec6455c-9dc5-11e5-8191-029bdd84add0.png)

**Comment by seekshiva** [comment]
My laptop gets super hot and is unusable. Would be great if I can find a fix to this soon.

**Comment by bebraw** [comment]
Can you see the problem in the current version?
