### ISSUE TITLE
Webpack 2 is unable to bundle react-relay

### ISSUE THREAD

**Issue by hannesj** [webpack/webpack#1725]
I get the following exception when bundling react-relay with webpack 2.0.1-beta. It is caused by acorn, which is expecting ES2015 code, even tough we are feeding it regular ES5 code. This is a regression from webpack 1.x. 

```
ERROR in ./~/react-relay/lib/RelayTaskScheduler.js
Module parse failed: ./node_modules/react-relay/lib/RelayTaskScheduler.js The keyword 'await' is reserved (90:18)
You may need an appropriate loader to handle this file type.
|    *   );
|     */
|   await: function await() {
|     for (var _len = arguments.length, callbacks = Array(_len), _key = 0; _key < _len; _key++) {
|       callbacks[_key] = arguments[_key];
 @ ./~/react-relay/lib/RelayPublic.js 24:25-56
```

**Comment by kassens** [comment]
We've fixed this on the Relay side now by not using the reserved keyword `await` as a method name for now.

Repro might be:

```javascript
var x = {
  function: 1,
  await: 2,
  other: 3,
};
```

It should parse and the first 2 keys would ideally be quoted to not confuse Edge (have not verified this myself).
