### ISSUE TITLE
Having a global variable named "URL" prevents css sourcemaps from correctly linking to the source file

### ISSUE THREAD

**Issue by laggingreflex** [webpack/webpack#1726]
I've encountered a weird bug. Having a global variable named `URL` prevents CSS sourcemaps to correctly link to the source file.

Here's a simple test setup to replicate the bug, almost identical to the one in the [getting-started]:

    document.write('It works.');
    require('./css.css');

The above works ok, the css styles display the correct source. 

But if I define a global variable `URL` then it fails to show the source and just points to the `<style>` element as a source:

    document.write('It works.');
    URL = require('url');           // problem
    // global.URL = require('url'); // problem
    // URL = 'anything';            // problem
    // global.Url = require('url'); // works
    require('./css.css');

![scr]

It also works if I have the css before the URL:

    document.write('It works.');
    require('./css.css'); // works
    URL = require('url');

[getting-started]: http://webpack.github.io/docs/tutorials/getting-started
[scr]: https://cloud.githubusercontent.com/assets/2523987/11653863/2fc984f4-9dc7-11e5-8192-5ec7af9046bf.png

**Comment by sokra** [comment]
yes, because overriding the global `URL` overrides the browser API: https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/url

Having a global called `document` also breaks stuff...

globals are bad!

so wontfix.
