### ISSUE TITLE
reason: 'unsupported',   code: 'ERR_OSSL_EVP_UNSUPPORTED'

### ISSUE THREAD

**Issue by Mohammad-Ali-Rauf** [webpack/webpack#17285]
when i run ``yarn build`` i got this error:

0 0.448 yarn run v1.22.19
0 0.478 $ react-scripts build
0 1.778 Creating an optimized production build...
0 1.927 Error: error:0308010C:digital envelope routines::unsupported
0 1.927     at new Hash (node:internal/crypto/hash:71:19)
0 1.927     at Object.createHash (node:crypto:133:10)
0 1.927     at module.exports (/app/node_modules/webpack/lib/util/createHash.js:90:53)
0 1.927     at NormalModule._initBuildHash (/app/node_modules/webpack/lib/NormalModule.js:401:16)
0 1.927     at handleParseError (/app/node_modules/webpack/lib/NormalModule.js:449:10)
0 1.927     at /app/node_modules/webpack/lib/NormalModule.js:481:5
0 1.927     at /app/node_modules/webpack/lib/NormalModule.js:342:12
0 1.927     at /app/node_modules/loader-runner/lib/LoaderRunner.js:373:3
0 1.927     at iterateNormalLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
0 1.927     at iterateNormalLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
0 1.927     at /app/node_modules/loader-runner/lib/LoaderRunner.js:236:3
0 1.927     at runSyncOrAsync (/app/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
0 1.927     at iterateNormalLoaders (/app/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
0 1.927     at Array.<anonymous> (/app/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
0 1.927     at Storage.finished (/app/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
0 1.927     at /app/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
0 2.578 /app/node_modules/react-scripts/scripts/build.js:19
0 2.578   throw err;
0 2.578   ^
0 2.578 
0 2.578 Error: error:0308010C:digital envelope routines::unsupported
0 2.578     at new Hash (node:internal/crypto/hash:71:19)
0 2.578     at Object.createHash (node:crypto:133:10)
0 2.578     at module.exports (/app/node_modules/webpack/lib/util/createHash.js:90:53)
0 2.578     at NormalModule._initBuildHash (/app/node_modules/webpack/lib/NormalModule.js:401:16)
0 2.578     at /app/node_modules/webpack/lib/NormalModule.js:433:10
0 2.578     at /app/node_modules/webpack/lib/NormalModule.js:308:13
0 2.578     at /app/node_modules/loader-runner/lib/LoaderRunner.js:367:11
0 2.578     at /app/node_modules/loader-runner/lib/LoaderRunner.js:233:18
0 2.578     at context.callback (/app/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
0 2.578     at /app/node_modules/react-scripts/node_modules/babel-loader/lib/index.js:51:103 {
0 2.578   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
0 2.578   library: 'digital envelope routines',
0 2.578   reason: 'unsupported',
0 2.578   code: 'ERR_OSSL_EVP_UNSUPPORTED'
0 2.578 }
0 2.578 
0 2.578 Node.js v18.7.0
0 2.613 error Command failed with exit code 1.
0 2.614 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
failed to solve: process "/bin/sh -c yarn build" did not complete successfully: exit code: 1

node version: 18.7.0
yarn version: 1.22.19
my os: ubuntu linux (22.10)

**Comment by alexander-akait** [comment]
Close in favor of https://github.com/webpack/webpack/issues/14532, please look at solutions
