### ISSUE TITLE
How to trigger a throw on import / require

### ISSUE THREAD

**Issue by kmalakoff** [webpack/webpack#1729]
I'm a big fan of webpack and have stumbled on an interesting pattern for electron where I can shim browser stubs or versions like this so I don't need to modify the node code directly:

// electron

```
config.externals = {
  'fs': require.resolve('fs')
}
```

// browser

```
config.alias = {
  'fs': require.resolve('fs-memory/singleton')
}
```

Really amazing! 

I have a case that I'm trying to solve....I want to throw in the browser like this since the module import is being wrapped by a try / catch already to fallback to a less efficient implementation...

// electron

```
config.externals = {
  'fsevents': require.resolve('fsevents'),
}
```

// browser

```
config.alias = {
  'fsevents': THROW AN ERROR!
}
```

I originally, naively implemented it like:

// browser

```
config.alias = {
  'fsevents': require.resolve('stubs/throw')
}
```

but when I have multiple throwing shims or the module is loaded in multiple places, it only throws the first time as you would expect since the second time the module is in cache.

How can I throw each and every time for multiple modules and multiple import / require call?

```
config.alias = {
  'fsevents': THROW AN ERROR!,
  'somethingelse': THROW AN ERROR!
}
```

**Comment by kmalakoff** [comment]
@bebraw thank you! I'm not sure if it is a question or a feature request.

**Comment by sokra** [comment]
``` js
externals: {
  fsevents: "(function() { throw new Error("test"); }())"
}
```

**Comment by kmalakoff** [comment]
Thank you for the configuration. I realized that my description wasn't clear... 

I've put together a [test repo](https://github.com/kmalakoff/webpack-test) to show the problem.

If you compare webpack to node, you'll see they behave differently:

Node.js
```
$ node entry.js

Module1: pre-require
Module1: post-require (error)
Module1: post-require (finally)
Module2: pre-require
Module2: post-require (error)
Module2: post-require (finally)
```

```
$ webpack
$ open index.html

(console)
Module1: pre-require
Module1: post-require (error)
Module1: post-require (finally)
Module2: pre-require
Module2: async undefined
Module2: post-require (finally)
```

Basically, node throws each time the module is required, but webpack only throws the first time.

The use case I had was where multiple libraries used require('fsevents') to feature detect whether fsevents was available inside a try / catch block. The first library caught the exception which changed the program flow, but the second library received an empty object from webpack so their try / catch logic for fallback wasn't triggered.

This might be an edge-case where webpack doesn't need to be identical to node. I just ran into the discrepancy so filed the "bug" / "feature".

Thank you for webpack!

**Comment by sokra** [comment]
webpack should behave identical to node.js here.

**Comment by sokra** [comment]
This requires a try-catch block in the webpack runtime. This would have big performance implications...

As nobody noticed it for year, we could be incompatible to node.js here, for performance reasons.

**Comment by sokra** [comment]
For reference: https://github.com/nodejs/node/blob/master/lib/module.js#L434-L442

**Comment by kmalakoff** [comment]
The performance, feature parity, and "hasn't been a problem for anyone so far" arguments all make sense.

I've found a work around by forking one of the libraries so not a problem for me anymore so I'll leave it in your hands to discuss and decide. Thank you!

**Comment by sokra** [comment]
Ok we discuss it and will add a opt-in option to enable correct behavior for exceptions while module loading.

**Comment by kmalakoff** [comment]
Sounds like a good balance. Thank you!
