### ISSUE TITLE
Default-importing UMD module in ESM file didn't take `default` named export from UMD module

### ISSUE THREAD

**Issue by chenxinyanc** [webpack/webpack#17318]
# Bug report

**What is the current behavior?**
Suppose we are consuming a library published with UMD module (actually it's a Webpack-bundled UMD library module) that exports the following members
* `HighchartsReact`: a React component
* `default`: exactly the same instance as `HighchartsReact` when being exported.
* `__esModule`: `true`

I'm importing this library in a ESM js file (I've enabled ESM in `package.json` for my own project) with something like this

```jsx
import HighChartsReact from 'highcharts-react-official';

// inside a React component...
return <HighChartsReact ... />;
```

and I see the following Error

> Element type is invalid: expected a string (for built-in ccmponents) or a class/function (for composite components) but got: object. 
Check the render method of `[SomeComponent]`

I've checked the runtime value of `HighChartsReact` and I see something like this

![image](https://github.com/webpack/webpack/assets/50703224/ba3215d2-da12-47a5-9abb-203c41a742d8)

Note that I'm default-importing `highcharts-react-official` as `HighChartsReact`, but during runtime, it looks almost the same as if I were importing the module with star import

```js
import * as HighChartsReact from 'highcharts-react-official';
```

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/chenxinyanc/webpack-esm-default-import-issue

**What is the expected behavior?**

I expect by calling
```js
import HighChartsReact from 'highcharts-react-official';
```

I receive similar effect as
```js
const HighChartsReact = (await import('highcharts-react-official')).default;
```

rather than
```js
const HighChartsReact = await import('highcharts-react-official');
```

**Other relevant information:**
webpack version:  5.85.0
Node.js version: 18.16.0
Operating System: Windows 11
Additional tools: yarn

I've done some preliminary investigation and it seems  the `getDefaultExport` helper didn't get emitted, because `exportsType` was `default-with-named` during build-time.
https://github.com/webpack/webpack/blob/cc3fd6ee19c295dd322a643093a5e280061a115b/lib/RuntimeTemplate.js#L771-L784

**Comment by alexander-akait** [comment]
Sorry, I can't use https://github.com/chenxinyanc/webpack-esm-default-import-issue and I want to say it works as expected there is not `default `in UMD, try to run your code without webpack (covert jsx to js)

**Comment by chenxinyanc** [comment]
Oops. My bad. Just made the repo public.

> it works as expected there is not `default` in UMD

Did you mean there is no `default` keyword in UMD or were you suggesting the package I'm importing might lack the `default` export?

> try to run your code without webpack (covert jsx to js)

My reproduction repo is not using JSX, and nodejs won't let me import UMD module in ESM with synchronous import statement.

> same for commonjs and etc

I guess the default import syntax works if I just convert my repo into CJS in package.json. Will try out later.

**Comment by alexander-akait** [comment]
I will look at this soon, thank you for updating

**Comment by alexander-akait** [comment]
As I said above - expected, run it without webpack, i.e. `node src/index.js` with this code:
```js
import HighChartsReact_default from 'highcharts-react-official';
// import * as HighChartsReact_star from 'highcharts-react-official';
// import { HighchartsReact } from 'highcharts-react-official';

export function printMyImports() {
  // const outputEl = document.getElementById("output");

  console.log("import default from ->", HighChartsReact_default);
  // console.log("import * from ->", HighChartsReact_star);
  // console.log("import { HighchartsReact } from ->", HighchartsReact);

  function writeLine(str) { console.log(str); }
  function printImportObjectOutline(obj) {
    writeLine(`  __esModule=${obj.__esModule}; $$typeof=${obj.$$typeof?.description}; default=${obj.default}`);
    writeLine(obj.default);
    writeLine("");
  }

  writeLine("import default from 'highcharts-react-official'");
  printImportObjectOutline(HighChartsReact_default);
  // writeLine("import * as Foo from 'highcharts-react-official'");
  // printImportObjectOutline(HighChartsReact_star);
  // writeLine("import { HighchartsReact } from 'highcharts-react-official'");
  // printImportObjectOutline(HighchartsReact);
}

printMyImports();
```

Output:
```
import default from -> {
  HighchartsReact: [Getter],
  default: {
    '$$typeof': Symbol(react.memo),
    type: {
      '$$typeof': Symbol(react.forward_ref),
      render: [Function: HighchartsReact]
    },
    compare: null
  }
}
import default from 'highcharts-react-official'
  __esModule=true; $$typeof=undefined; default=[object Object]
{
  '$$typeof': Symbol(react.memo),
  type: {
    '$$typeof': Symbol(react.forward_ref),
    render: [Function: HighchartsReact]
  },
  compare: null
}
```

So we align to Node.js behaviour and align to other bundlers behaviour, just try it on `esbuild`, you will have the same.

We have a lot of tests to align with Node.js behaviour and other bundlers, so I see the same result everywhere.

> My reproduction repo is not using JSX, and nodejs won't let me import UMD module in ESM with synchronous import statement.

UMD is universal, so you can run it on node and browser and not only

> import default doesn't unwrap the UMD module and behaves exactly the same as import * as ...

Yes, because source exported in commonjs format and you have `type: "module"`, there is no ESM `default` in commonjs

> As long as I remove type: "module" from package.json, everything works as expected -- I can consume UMD module even if I'm using ES6 import syntax (instead of require("...")).

Since the logic is different between ESM and CommonJS, when you import `index.js` webpack tries to resolve it and gets what it has `type: "module"` so now you have logic for ESM.

And don't know who written docs about that you can use `default` import in pure ESM, it is not truth.

Anyway you can fix it using `type: "javascript/auto"`, you already set `fullySpecified: false`, so it is not compatibility with ESM:
```js
module: {
  rules: [
    {
      test: /\.m?js$/,
      type: "javascript/auto",
      resolve: {
        fullySpecified: false,
      },
    },
  ],
},
```    

Simplifed example:

**test.mjs**

```js
import foo from "./foo.cjs";

console.log(foo)
```

**foo.cjs**

```js
module.exports = {
    default: "test"
};
```

Feel free to feedback

**Comment by chenxinyanc** [comment]
Thanks for your detailed explanation! I think I've been having misunderstanding regarding to this statement for a while:

> And don't know who written docs about that you can use default import in pure ESM, it is not truth.

After some googling, I found [this article](https://adamcoster.com/blog/commonjs-and-esm-importexport-compatibility-examples) and realized that NodeJS (and therefore other bundlers) is not following the `__esModule` sentry (proposed by TypeScript, I guess).

So, in summary, I think the current situation is, when importing CJS modules,
* Default imports in NodeJS (and webpack / esbuild / etc.) behaves exactly the same as star imports.
* There is no way to overwrite default import unless the module imported is also ESM, rather than CJS.

Does it sound correct to you?

**Comment by alexander-akait** [comment]
> Default imports in NodeJS (and webpack / esbuild / etc.) behaves exactly the same as star imports.

Yes

> There is no way to overwrite default import unless the module imported is also ESM, rather than CJS.

Yes, but you can have `babel`/`swc`/etc to override/change it
