### ISSUE TITLE
load multiple files under single directory

### ISSUE THREAD

**Issue by matt212** [webpack/webpack#1732]
how to load multi static files under directory !
module.exports = {
  
  entry: './assets/js/.*js',
  output: {
    filename: 'bundle.js'       
  }
};
i am unable to find proper docmentation  with working sample code?

**Comment by bebraw** [comment]
Note that `entry` accepts an array. You could glob the files you need and pass a resulting array to it. It still might not do what you expect, though.

How are you going to use the resulting bundle?

**Comment by matt212** [comment]
i will use final consolidated js file and replace all existing files from js directory in prod version

**Comment by matt212** [comment]
i want o achieve something like this 
http://stackoverflow.com/questions/17008472/how-to-minify-multiple-javascript-files-in-a-folder-with-uglifyjs and then consolidated all file into one file

**Comment by bebraw** [comment]
The following would output a build file per each entry. It assumes you are using [glob](https://www.npmjs.com/package/glob) but any other library would do.

```javascript
...
entry: toObject(glob.sync(<pattern>)), // object of entries in format {name: path}
output: {
  filename: '[name].min.js' // note [name], that's where entry name goes
}
...
```

That `toObject` thinger will figure out the object keys. Those keys are then passed to `[name]`. You can try hardcoding something at first to see how it works and generalize from there as you like.

**Comment by matt212** [comment]
thanks , really good approach ! bebraw 
could we use below 
var path = require('path');
module.exports = {
  
  entry: path.join(__dirname, 'assets'),
  output: {
    filename: 'bundle.js'       
  }
};

iam getting error "ERROR in Entry module not found: Error: Cannot resolve 'file' or 'directory'"

**Comment by bebraw** [comment]
Nope. You need something like this:

```javascript
var glob = require('glob');

module.exports = {
  entry: toObject(glob.sync('assets/**/*.js*')),
  output: {
    filename: '[name].js'
  },
  ...
};

function toObject(paths) {
  var ret = {};

  paths.forEach(function(path) {
    // you can define entry names mapped to [name] here
    ret[path.split('/').slice(-1)[0]] = path;
  });

  return ret;
}
```

**Comment by matt212** [comment]
Hi, 
great the logic work awesome but stumbling unto below error

ERROR in Entry module not found: Error: Cannot resolve module 'assets/js/utility
.js'

the file exists  in path!

**Comment by bebraw** [comment]
Make sure the paths you generate are absolute. That might resolve it.

**Comment by matt212** [comment]
Hi sorry my bad 
just put " ./"
entry: toObject(glob.sync('assets/**/*.js*')),
and it start working great man

**Comment by incubux** [comment]
and how import from main?

**Comment by ajaygoyal771** [comment]
i have tried the webpack.config.js given above and now it is giving me this error
Conflict: Multiple assets emit to the same filename [bundle].js.

I wanted to generate the output of all files in a single bundle.js file.Can anyone help me?

**Comment by sectsect** [comment]
I created a npm package for entry-points based on these.

See README
https://github.com/sectsect/webpack-sweet-entry

**Comment by Ganpatkakar** [comment]
To generate the proper folder structure with the file path you need something like below:-

You can use this as below:-
```const glob = require('glob');

function toObject(paths) {
    var ret = {};

    paths.forEach(function(path) {
        // you can define entry names mapped to [name] here
        ret[path] = path;
    });

    console.log(ret);
    return ret;
}

module.exports = {
    entry :  toObject(glob.sync('./src/**/*.js*')),
    output: {
        path: path.resolve(__dirname, 'lib'),
        filename: '[name].js'
    },
}```

refined a little bit like entry object key and value both should be `path` so it will generate the same `lib` folder structure like `src` folder.

Thanks @bebraw
