### ISSUE TITLE
mode: performance regression

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack#17322]
Looking at the chart here we introduced a performance regression in webpack prod builds. Adding this bug to track this and marking as a priority. 

![image](https://github.com/webpack/webpack/assets/3408176/cd1f5cef-4e49-4796-8585-ceebe401c021)

**Comment by alexander-akait** [comment]
@fabiosantoscode Hello, after some investigation we determined that the regression occurred on the `terser` side, on https://github.com/terser/terser/releases/tag/v5.16.8 release, I still continue investigation to undestand what changes make it.

It is still present in `terser`, you can follow the link (https://webpack.github.io/benchmark/ and choose `production-build` for `Scenario`) and see all our measurements, since March 25, the build speed has dropped by about 19-20 seconds.

Any thoughts?

**Comment by fabiosantoscode** [comment]
Glad you're keeping track of this!

If you know it to be that tag, I'm highly suspicious of https://github.com/terser/terser/commit/21600d91cf6dd071b45e76922b15975f5dcf879f#diff-2c2f73414005bd447f18acde4b1ed462b5380eadbf3faeaa86d517091c58b2f6R504-R566

It's a bug fix for functions that are hoisted into a place a `var` wasn't executed yet.

**Comment by fabiosantoscode** [comment]
I'll have a look tomorrow

**Comment by alexander-akait** [comment]
@fabiosantoscode 

> If you know it to be that tag, I'm highly suspicious of https://github.com/terser/terser/commit/21600d91cf6dd071b45e76922b15975f5dcf879f#diff-2c2f73414005bd447f18acde4b1ed462b5380eadbf3faeaa86d517091c58b2f6R504-R566

Yeah, I thought the same

> I'll have a look tomorrow

Thank you.

As a last resort, I can try to clone everything and run these checks manually without this change, it takes a lot of time, but it will allow to find out exactly what caused this. Keep me posted, if you can't figure out anything, then I'll start looking into the problem in depth.

**Comment by fabiosantoscode** [comment]
Terser has its own benchmarks, don't worry. The problem is that I'm not keeping track

**Comment by fabiosantoscode** [comment]
Did a quick check before going to sleep but didn't find anything much. Only a difference between 4.9 seconds and 5.2 seconds. Tomorrow I'll try to get my hands on the actual inputs used in this benchmark and test then.

**Comment by fabiosantoscode** [comment]
I've reproduced the issue by swapping the terser dep using yarn's `resolutions` thing.

However I found that the [TERSER_DEBUG_DIR](https://terser.org/docs/reporting-issues/#obtaining-the-source-code-given-to-terser) env var doesn't get passed down to Terser by the benchmark (or webpack) so I'm not sure how I can grab the inputs.

**Comment by alexander-akait** [comment]
@fabiosantoscode 

> I've reproduced the issue by swapping the terser dep using yarn's resolutions thing.

Great

We use https://github.com/webpack-contrib/terser-webpack-plugin to run terser and we use multithreading, that is why `[TERSER_DEBUG_DIR](https://terser.org/docs/reporting-issues/#obtaining-the-source-code-given-to-terser)` is not avaliable, just do moneky patch https://github.com/webpack-contrib/terser-webpack-plugin/blob/master/src/index.js#L344 and return `0`

**Comment by fabiosantoscode** [comment]
I was able to grab the input through changing the webpack.config.js of the common-libs folder to disable `optimization.minimize` and grabbing dist/main.js.

The suspicious commit https://github.com/terser/terser/commit/21600d91cf6dd071b45e76922b15975f5dcf879f slows down the `compress` step significantly compared to the commit before. This slowdown doesn't occur when `reduce_vars` is disabled.

Before, it took 8.1s, at the bad commit it takes 23.0s

**Comment by fabiosantoscode** [comment]
Ok, performance is pretty comparable now. Not as fast as before, but it still retains the fix for the defun hoisting issue. I'll release on monday to avoid weekend breakage.

**Comment by alexander-akait** [comment]
@fabiosantoscode Great, big thank you :heart: , I will update and check it and provide some feedback

**Comment by fabiosantoscode** [comment]
5.18.1 is out!

**Comment by alexander-akait** [comment]
The original problem was fixed @fabiosantoscode thank you
