### ISSUE TITLE
Escape ! in binding loaders section of the tutorial

### ISSUE THREAD

**Issue by cweems** [webpack/webpack#1733]
In the [tutorial](http://webpack.github.io/docs/tutorials/getting-started/#binding-loaders), I encountered an error "event not found: css" when doing:

```
$ webpack ./entry.js bundle.js --module-bind "css=style!css"
```
It appears that the ! before css needs to be escaped in order to function properly:
```
$ webpack ./entry.js bundle.js --module-bind "css=style\!css"
```
A note reminding users to escape that might be helpful. I spend a few minutes trying to figure this one out.

**Comment by dgoguerra** [comment]
It seems to be updated in the [docs](https://github.com/webpack/docs/blob/master/tutorials/getting-started/1.5%20binding-loaders/README.md) repo (changed to using single quotes), just not published yet.

**Comment by sokra** [comment]
Closing because we are working on a new documentation for webpack 2
