### ISSUE TITLE
How to set some module to be loaded first of all?

### ISSUE THREAD

**Issue by aspirisen** [webpack/webpack#1734]
Hi, I have some problem with inheritance: for example class Component is dependent from some other modules which is not loaded yet, as I understood webpack postpones loading this module. In some place another class extends this component and hence gets undefined and throws a error that can't read of undefined. How to tell webpack that this module must be loaded first of all, despite the dependencies, or maybe there is another way of solving that?

P.S. I use TypeScript.

**Comment by aspirisen** [comment]
I asked about similar situation on [StackOverflow](http://stackoverflow.com/questions/34184268/webpack-how-to-set-some-modules-to-be-loaded-firstly)

**Comment by shama** [comment]
This is likely an issue with TypeScript, the TypeScript loader you are using or just misconfigured. When compiling, TypeScript should be resolving the order as it has it's own module system. By the time it gets to webpack, it should have generated javascript that loads via commonjs or amd.
