### ISSUE TITLE
Add `fetchpriority="high"` to <script /> for loading async js source

### ISSUE THREAD

**Issue by xingxinglieo** [webpack/webpack#17392]
For example, if you load an asynchronous route, the JS load after the first screen is a low-priority load, and then your chunks are split into dozens of chunks, then you will be blocked by some requests.The most serious problem is that the chunks are cached locally by the browser, but it takes hundreds of milliseconds to load them
see [Network requests stuck in pending state 
](https://bugs.chromium.org/p/chromium/issues/detail?id=891940)

![image](https://github.com/webpack/webpack/assets/48762792/b6cc0f52-66fd-45bd-9e35-1825b2bbbafa)
to resolve: `script.setAttribute("fetchpriority","hight")`
see [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script)

**Comment by alexander-akait** [comment]
Sorry, no, we don't want to change default behaviour, we have https://github.com/webpack/webpack/pull/17249 if you want to set it

**Comment by xingxinglieo** [comment]
The problem has been solved, the option is a good way to solve, thank you for the answer
