### ISSUE TITLE
import TaggedTemplateExpression should generate indirect call

### ISSUE THREAD

**Issue by underfin** [webpack/webpack#17390]
# Bug report

**What is the current behavior?**

 The input code 
``` js
import a from "a"
a();
a``;
```
The output code
``` js
/* harmony import */ var _a__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! a */ "./a.js");

(0, _a__WEBPACK_IMPORTED_MODULE_0__["default"])()
_a__WEBPACK_IMPORTED_MODULE_0__["default"]`` // here should be indirect call
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

The expected output

``` js
/* harmony import */ var _a__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! a */ "a.js");

(0, _a__WEBPACK_IMPORTED_MODULE_0__["default"])()
(0, _a__WEBPACK_IMPORTED_MODULE_0__["default"])`` // here should be indirect call
```

Here has babel playground output. https://babeljs.io/repl#?browsers=&build=&builtIns=usage&corejs=3.21&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAEzgMyhEcBEA6A9AQwCMBjTAKDIQAoBKAbgoQAMmg&debug=false&forceAllTransforms=true&modules=false&shippedProposals=true&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=&prettier=false&targets=&version=7.21.8&externalPlugins=%40babel%2Fplugin-transform-modules-commonjs%407.20.11%2C%40babel%2Fplugin-transform-function-name%407.18.9&assumptions=%7B%7D

**Other relevant information:**
webpack version:  
Node.js version:
Operating System:
Additional tools:

**Comment by alexander-akait** [comment]
@underfin Thank you for the report, fix - https://github.com/webpack/webpack/pull/17397, feel free to feedback (maybe more tests?)
