### ISSUE TITLE
Inbuilt support for alternate minifiers

### ISSUE THREAD

**Issue by burhanuday** [webpack/webpack#17398]
## Feature request

Have out of the box support for a faster minifier (possibly behind an experiment with the intention to make it default with webpack 6)

https://github.com/privatenumber/minification-benchmarks contains benchmark information for available minifiers. At this time, i dont have a strong preference towards an option

We have an open PR for a CSS minifier that we should consider under this issue as well https://github.com/webpack/webpack/pull/17309

**What is the expected behavior?**

Faster minification

**What is motivation or use case for adding/changing the behavior?**

To improve the build speed and DX, we should make it easy to switch to an alternate minifier

I am aware that another minifier can be passed explicitly but most devs dont know about this and face long build time issues. Minification is an area where we depend on an external tool that is not closely coupled to webpack

**How should this be implemented in your opinion?**

Let terser be the default choice for now. Have a flag `experiment.<minifier-name>` that when enabled, changes the JS (and possibly CSS) minifier

**Are you willing to work on this yourself?**
yes

**Comment by alexander-akait** [comment]
We already support it - https://github.com/webpack-contrib/terser-webpack-plugin#swc, I don't think we need extra options, because it just a couple of lines

**Comment by alexander-akait** [comment]
Also we supported almost all minifiers - https://github.com/privatenumber/minification-benchmarks, excpet:
- `babel-minify` - abadoned
- `google-closure-compiler` - no official plugins, https://github.com/webpack-contrib/closure-webpack-plugin looks abadoned, but you can use it as a custom minimizer function
- `minify-js` - no one asked about it
- `dewolff/minify` the same here, no one asked about it

For last two we can add a support to https://github.com/webpack-contrib/terser-webpack-plugin#swc, feel free to send a PR

**Comment by burhanuday** [comment]
I see, are we looking to change the default minifier to something faster with the next webpack version?

**Comment by alexander-akait** [comment]
@burhanuday We haven't discussed this yet. I think will be great to align with rspack team here and maybe switch to `swc`, but before it we should check perf - not for minimizer, but for webpack - we have https://webpack.github.io/benchmark/, so lets add an extra scenario - `production-build+swc-minimize` - https://github.com/webpack/benchmark. Can you do it?

**Comment by burhanuday** [comment]
@alexander-akait yes. will work on it.

**Comment by burhanuday** [comment]
@alexander-akait opened a PR to the benchmark repo
