### ISSUE TITLE
Using [name] in publicPath

### ISSUE THREAD

**Issue by jonnystoten** [webpack/webpack#1739]
It looks like we can't use [name] inside publicPath config like this:

```
output: {
    path: "/some/path",
    filename: "js/[name].js",
    publicPath: "http://[name].example.com/"
}
```

Is this for a reason or is it just not implemented? I would be happy to take a look at implementing it, but I would appreciate a pointer on where the code that does this lives.

Thanks!

**Comment by sokra** [comment]
`[name]` doesn't work on `publicPath`, because the public path is constant over all chunks.

**Comment by hypeJunction** [comment]
Is there anything hindering `publicPath` from being a closure resolved in the client? I have a situation where I need to load the resources from a timestamped public path, but the timestamp is only known in the client, not at build time.

**Comment by javadbat** [comment]
what if we have a multi-entry bundle that every bundle has its own chunks?
