### ISSUE TITLE
default export for experiments css modules

### ISSUE THREAD

**Issue by ahabhgk** [webpack/webpack#17403]
## Feature request

For now experiments css modules only have namespace export or named export, but some project may prefer default export

**What is the expected behavior?**

`import classes from './index.module.css'`

**What is motivation or use case for adding/changing the behavior?**

some project use default export for css modules, and css-loader default to `false` for [namedExport](https://github.com/webpack-contrib/css-loader#namedexport)

**How should this be implemented in your opinion?**

add `namedExport` generator options for `css/module` type and `css/global` type (and default to `true` for compatible with current behavior)

**Are you willing to work on this yourself?**
yes

**Comment by alexander-akait** [comment]
To be honestly I think we don't need it, because `namedExport` will be `true` default behaviour for the next css-loader release (and last) and allow to apply a lot of optmizations (and do better tree shaking, in future we can treeshake CSS classes too), I don't have strong opinion here, but do we really need to support all legacy things?

**Comment by alexander-akait** [comment]
Maybe named export should be a default (and only) behaviour

**Comment by burhanuday** [comment]
Wasnt aware of default export being legacy behaviour. Repo does not say anything about either - https://github.com/css-modules/css-modules#css-modules

We can keep `namedExport` as the default but we should support default export behind a flag at least till other bundlers support that syntax

**Comment by ahabhgk** [comment]
Is that possible to also tree-shaking default export (`namedExport: false`)? json module is using default export and can be tree-shaken

**Comment by SuperOleg39** [comment]
> but do we really need to support all legacy things

Tried to use `namedExport: true` in our projects few weeks ago, and found possible migration to named exports very painful (custom UI-kit, tens of applications)

Fallback with default and named exports mix will be ideal.

Ofc we always can specify pattern only for files where named exports will be used - but again, for large applications it is painful

**Comment by ScriptedAlchemy** [comment]
Bumping conversation here, this creates blocker for rspack. What's the direction we intend on taking within webpack for css experiment and differences with css loader? @alexander-akait when you are back - can we discuss?

**Comment by hardfist** [comment]
bump

**Comment by alexander-akait** [comment]
@ahabhgk After moving CSS options in the generator, I think we can implement `namedExport`, I am fine with it
