### ISSUE TITLE
Local module not replacing Global module

### ISSUE THREAD

**Issue by christopherjbaker** [webpack/webpack#1740]
I have several related but distinct applications, all of which use webpack. This is my file structure:
- node_modules
- webpack, et al
  - babel, et al
- app1
  - webpack.config.js
- category
  - app2
    - webpack.config.js
  - app3
    - webpack.config.js

The any of those webpack.config.js files can `require('webpack')` with no issue, however the global webpack is unable to find it, as it is looking in `process.cwd()/node_modules/webpack...".

Essentially, the desired effect would be to execute `require('webpack')` from the cwd. To that end, I have a possible solution, by creating a new fake module (in memory only) at `process.cwd()`, then executing a require on it, and making sure the returned module is not the current one.

``` javascript
var path = require("path");
var Module = require("module");

try {
    var localModule = new Module();
    try {
        localModule.load( path.join(process.cwd(), 'dummy') );
    }
    catch (e) {}

    var localWebpack = localModule.require(path.join("webpack", "bin", "webpack.js"));
    if(localWebpack !== module.exports) {
        return localWebpack;
    }
} catch(e) {}
```

**Comment by sokra** [comment]
Would you like to send a PR making this change?

**Comment by HMUDesign** [comment]
I had considered this and normally would, but this feels a bit hackish to me. I was hoping somebody might reply with some suggestions or something. =]

**Comment by sokra** [comment]
Finding the nearest node_modules folder could work.

**Comment by arturparkhisenko** [comment]
@sokra I solved it but I'm not sure which way is preferred. 
The first way my own implementation finding nearest `node_modules` folder function named `resolveLocalWebpack` in 35 lines (was inspired by `require.resolve` [doc](https://nodejs.org/api/modules.html#modules_all_together)),
the second way is simply using a new package dependency `resolve` in 2 lines.
And I wrote about tests in PR, maybe someone could help with that or give me the right way, currently reading all content of the test folder)
