### ISSUE TITLE
Add option to cli for excluding files from processing

### ISSUE THREAD

**Issue by xabikos** [webpack/webpack#1741]
Currently there is no way to exclude some folders from the processing with loaders, the equivalent of configuration object
`
loaders: [
      { 
        test: /\.js$/,
        exclude: /node_modules/,
        loader: 'babel-loader',
      }
`
or to indicate which folder to take into account with include. I think an option like --module-exclude would be handy.

**Comment by sokra** [comment]
not really necessary, as configuration can be used in this cases
