### ISSUE TITLE
Including files from an outside directory

### ISSUE THREAD

**Issue by ericwooley** [webpack/webpack#1742]
## EDIT:

I have discovered that this actually occurs with just react-hot-loader, so I guess it has nothing to do with being in a module, eg: 

React-hot-loader

``` js
import React from 'react';
import ReactDOM from 'react-dom';
import App from '../../react-dev-component/test/test-component';

ReactDOM.render(<App body="test" />, document.getElementById('root'));
```

Produces the same result, so does the module need to be in the same root path or something? Maybe is a babel loader problem?
## Original issue

I am writing https://github.com/ericwooley/react-dev-component which is based on https://github.com/gaearon/react-hot-boilerplate

The utility takes a specified file, eg: `node server.js --component test/test-component.js`, spins up a webpack server with react-hot-loader, and includes the file specified (admitidly, through a bit of a [hack](https://github.com/ericwooley/react-dev-component/blob/master/server.js#L7)). 

This works fine when you are developing locally, and the file you are including is in the webpack directory, but no longer works when you try to pass in a file that is outside the folder. Eg:  `node server.js --component ../eee/src/js/json-explorer/json-explorer.js` or (when installed globally) `react-dev-component --component src/js/json-explorer/json-explorer.js`

```
Module parse failed: /Users/eriwoole/Projects/EEE/src/js/json-explorer/json-explorer.js Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| import React, {Component} from 'react'
| export default class JSONExplorer extends Component {
|   render () {
 @ ./src/index.js 17:20-97
```

Really stumped by this one.

**Comment by ericwooley** [comment]
Nobody has any ideas?

**Comment by ajsharp** [comment]
I just ran into this issue when trying to include files outside of the webpack project root.

**Comment by ajsharp** [comment]
Possibly relevant: http://jsroad.blogspot.com/2015/09/using-modules-outside-of-app-root.html

**Comment by SaulHarwin** [comment]
Maybe this could be of use: 
https://stackoverflow.com/questions/45490589/how-can-i-read-files-outside-src
