### ISSUE TITLE
Very hard failure with watch on OS X

### ISSUE THREAD

**Issue by ronkorving** [webpack/webpack#1743]
We are running a fairly large project with 922 JavaScript and .less files being watched by Webpack's watch function on OS X (10.10.2) running on Node.js 5.2.0. During the initial build, or right when it's done with that, the following happens:

```
2015-12-10 18:01 node[76106] (FSEvents.framework) FSEventStreamScheduleWithRunLoop: failed to create the cffd
2015-12-10 18:01 node[76106] (FSEvents.framework) FSEventStreamCreate: _FSEventStreamCreate: ERROR: could not open kqueue
2015-12-10 18:01 node[76106] (FSEvents.framework) FSEventStreamScheduleWithRunLoop(): failed assertion 'streamRef != NULL'

2015-12-10 18:01 node[76106] (FSEvents.framework) FSEventStreamStart(): failed assertion 'streamRef != NULL'

2015-12-10 18:01 node[76106] (FSEvents.framework) FSEventStreamStop(): failed assertion 'streamRef != NULL'

2015-12-10 18:01 node[76106] (FSEvents.framework) FSEventStreamUnscheduleFromRunLoop(): failed assertion 'streamRef != NULL'

2015-12-10 18:01 node[76106] (FSEvents.framework) FSEventStreamInvalidate(): failed assertion 'streamRef != NULL'

2015-12-10 18:01 node[76106] (FSEvents.framework) FSEventStreamRelease(): failed assertion 'streamRef != NULL'
```

I've made an issue about this at https://github.com/libuv/libuv/issues/645, but I was wondering if this is something other Webpack users have also suffered from and if a workaround is known. Thanks.

**Comment by shama** [comment]
This might have been fixed in `chokidar` see https://github.com/paulmillr/chokidar/issues/167 and we just need to update the dep in [watchpack](https://github.com/webpack/watchpack).

**Comment by ronkorving** [comment]
The chokidar dependency in watchpack is already set to `"chokidar": "^1.0.0"`, so it should be using the latest release.

**Comment by bebraw** [comment]
Should be fixed by now.

**Comment by ronkorving** [comment]
@bebraw Mind sharing why/how?

**Comment by ronkorving** [comment]
Based on the above, it wasn't. Watchpack at the time was already on the latest chokidar. It may be possible that it's fixed at the OS X level (seems possible given the comments on the issue mentioned above), or perhaps even chokidar. I have a hard time reproducing it now, but can't claim with certainty that based on anything tangible, the problem has actually disappeared.

On my end, nobody on the team working on that large project who had the issues still uses watch. I can ask for some people to try again.

**Comment by bebraw** [comment]
Ok, if you can repro, we can definitely re-open and mark this as a bug. That said, it's very hard to do anything about the issue if there's no concrete test case to run and debug.

**Comment by ronkorving** [comment]
Understood

**Comment by grimen** [comment]
I ran into this issue too after updating some NPM libraries for hobby project to latest tags. I guess I will downgrade libs until it works again.

**Comment by ds3783** [comment]
I met the problem, it seems a mac OS's bug, after I reboot my mac, it disappear.

**Comment by Andyczc** [comment]
I also met this problem on the iterm, my solution is to put the iterm closed to restart again, to solve

**Comment by ronkorving** [comment]
@Andyczc Which version of Webpack?

**Comment by wilon** [comment]
I met this problem too,  and solved by this Command:

    npm install -g

**Comment by xixixao** [comment]
Happened to me after macOS soft rebooted, perhaps connected. iTerm restart fixed it.

**Comment by mfferreira** [comment]
Same issue here. Simply restarting iTerm fixed it.

**Comment by crowmagnumb** [comment]
Just to add to the mix. My mac soft crashed on me (back to the login screen), logged back in, and was getting this. Restarted iTerm and all was good. Thanks everyone.

**Comment by MacKentoch** [comment]
Just restarting iTerm fixed for me too!

Thank you @xiaomoinfo  @mfferreira

**Comment by ronkorving** [comment]
Just my 2 cents, but IMHO having to restart your terminal is not a fix. Somewhere, something is broken. I'm not saying that's Webpack, but *something* is broken. So I wouldn't want to dismiss this as a non-issue, simply because it's "fixed" for everyone.

**Comment by sprinklr-gurgaon** [comment]
Shouldn't it be resolved by increasing ulimit value?
`ulimit -n <value>`
or any other way which fixes it at the root

**Comment by peterarends** [comment]
Restarting iTerm fixed it for me too, thanks. @ronkorving you are absolutely right, but it is iTerm in this case, because things like starting ssh sessions also stop working at the same time.

**Comment by samunplugged** [comment]
In my case it was a plugin. I added https://www.npmjs.com/package/node-sass-once-importer and my webpack started to behave crazy. This plugin was added to help us remove multiple imports. It worked during dev server start-up, but in watch mode making file changes would randomly cause this error: `FSEvents.framework) FSEventStreamCreate: _FSEventStreamCreate: ERROR: could not open kqueue. `
Fixed by removing this plugin from dependency and instead now we're using css-loader that can remove duplicate CSS.

**Comment by marani** [comment]
Same soft crash problem, though I didn't need to restart iterm, just close the working pane and use a new pane. The crash causes some other weird issues as well, including ssl error when curl, npm install, yarn. Solved with the same solution, do it in a new pane.
