### ISSUE TITLE
If output directory doesn't exist, create it on build

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack#1746]
Looks like it's possible for build to fail on Ubuntu if the output directory doesn't exist and `devtool` is set. 

Related: https://github.com/webpack/webpack/issues/1736

**Comment by sokra** [comment]
webpack runs mkdirp on the output directory. And this is totally separate from the `devtool` option.

https://github.com/webpack/webpack/blob/master/lib/Compiler.js#L258
https://github.com/webpack/webpack/blob/master/lib/Compiler.js#L274

Really wondering why this should be a problem. Maybe `output.path` or `output.filename` wrong? Is `output.path` an absolute path?

**Comment by jhnns** [comment]
In my test setup it is working. Could you provide an example project @bebraw?

**Comment by bebraw** [comment]
No Ubuntu...

@Kay2dan Can you provide a test case for this? This is related to https://github.com/webpack/webpack/issues/1736.

**Comment by Kay2dan** [comment]
@sokra is correct. It is generated. 

However, as per @jhnns, initially, a LOT of my build just didnt work for one reason or another. I eventually gave up trying to find the error and just retrying. Now, it all works.

Here is the test build : https://github.com/Kay2dan/webpack_build_test
node_modules folder not provided so please install the npms. Hope that helps.

**Comment by balazsorban44** [comment]
Hi! I have the same problem, but after reading this issue, I still could not solve it. This is the first time I use webpack, so the following code will be an almost unmodified code I found on the internet with changes only on the paths.

Commenting out the devtool line has no effect for me, the file is not created, though in terminal it says it is emitted without errors.

```
var debug = process.env.NODE_ENV !== "production";
var webpack = require('webpack');
var path = require('path');

module.exports = {
  context: __dirname,
  //devtool: debug ? "inline-sourcemap" : null,
  entry: "./assets/js/main.js",
  module: {
    loaders: [
      {
        test: /\.jsx?$/,
        exclude: /(node_modules|bower_components)/,
        loader: 'babel-loader',
        query: {
          presets: ['react', 'es2015', 'stage-0'],
          plugins: ['react-html-attrs', 'transform-decorators-legacy', 'transform-class-properties'],
        }
      }
    ]
  },
  output: {
    path: __dirname,
    filename: "main.min.js"
  },
  plugins: debug ? [] : [
    new webpack.optimize.DedupePlugin(),
    new webpack.optimize.OccurrenceOrderPlugin(),
    new webpack.optimize.UglifyJsPlugin({ mangle: false, sourcemap: false }),
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: JSON.stringify('production')
      }
    }),
  ],
};
```
And here is the line I added to my package.json to be able to run it with npm run dev
` "dev": "webpack-dev-server --content-base . --inline --hot",`


When I run webpack command only, it works fine, and the file is created.

**Comment by frank3stein** [comment]
I had the same issue. Try replacing __dirname with path.resolve(__dirname) . 

I had my output 
```
    output: {
        path: __dirname + 'dist/',
        filename: 'app.bundle.js'
    }
```
changed it to 
```
   output: {
        path: resolve(__dirname, 'dist/'),
        filename: 'app.bundle.js'
    }
```

Now it creates the file.

**Comment by AlanStewart6** [comment]
so

**Comment by aydzz** [comment]
Hi, I just had this problem and it was because of the path used in the output property. I was originally using

```
const wpProdConfg = merge(wpCommonConfig, {
  mode: "production",
  output: {
    filename: "[name].[contenthash].js",
    path: path.resolve(__dirname, "/public/dist/"),
    clean: true,
  },
  plugins: [new CleanWebpackPlugin()],
});
```

but strangely, the path resolves to C:/public/dist/. 

I tried to use concatenation instead and it now works.
![image](https://github.com/webpack/webpack/assets/52524021/d9d99322-9e0b-475a-a550-db404a2890c0)
