### ISSUE TITLE
resolve.alias is ignoring exports field in package.json

### ISSUE THREAD

**Issue by marcincichocki** [webpack/webpack#17478]
# Bug report

**What is the current behavior?**

`resolve.alias` is not resolving code via `exports` field. I would expect this to work as described in: https://webpack.js.org/concepts/module-resolution/#module-paths

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/marcincichocki/webpack-exports

**What is the expected behavior?**

webpack should resolve packages's entry point from its `exports` field and build should be successful. If I add 

```json
+  "main": "./src/index.js"
```

to package.json of aliased package it starts to work (if secondary export is removed from the entry file), however, I cannot use secondary entry points then.

**Other relevant information:**
webpack version:  5.88.1
Node.js version: 16.20.1
Operating System: ubuntu 20
Additional tools: 

I've found one very similar issue here: https://stackoverflow.com/questions/71666958/unable-to-resolve-modules-specified-in-package-jsons-exports-field

**Comment by WNLee** [comment]
Hi, I'm learning the source code of webpack. Maybe I can help you.  Here, some idea for this question.First, webpack resolves request depending on `enhanced-resolve`. `enhanced-resolve` confirms if it is a module by the `path` string ([refs](https://github.com/webpack/enhanced-resolve/blob/a998c7d218b7a9ec2461fc4fddd1ad5dd7687485/lib/util/path.js#L40)).  `resolve.alias` turns module request into path request. So `package.json` won't work. Second, using `resolve.modules` can resolve the issue. change `resolve.alias: { xxx }` to `resolve.modules: ['dist/libs', 'node_modules']`. and change the directory from `dist/libs/core` to `dist/libs/@workspace/core`. It works!
   Hope this can help you.

```javascript
// webapck.config.js

import { resolve } from "node:path";

export default {
  entry: "./index.js",
  mode: "production",
  output: {
    path: resolve("./dist"),
    filename: "[name].js",
  },
  resolve: {
    // alias: {
    //   "@workspace/core": resolve("dist/libs/core"),
    // },
    modules: ['dist/libs', 'node_modules'],
    extensions: [".js"],
    exportsFields: ["exports"],
  },
};

```

<img width="275" alt="截屏2023-07-11 下午6 52 55" src="https://github.com/webpack/webpack/assets/3413551/7eb3cd61-6b3d-41dc-a703-32efd6e11692">

**Comment by marcincichocki** [comment]
@WNLee I tested it and it does work. Thanks a lot. I'll close this issue.
