### ISSUE TITLE
Production mode seems to break worklet detection

### ISSUE THREAD

**Issue by chrisguttandin** [webpack/webpack#17489]
# Bug report

**What is the current behavior?**

The following code gets correctly parsed in development mode but doesn't work in production mode.

```js
// index.js
let audioContext = null;

if (audioContext === null) {
    audioContext = new AudioContext();
}

audioContext.audioWorklet.addModule(new URL("./worklet.js", import.meta.url));
```

Please note that the if statement in the snippet above is rather useless. The original code that made me aware of this issue was way more complicated but this seems to be enough to reproduce the issue.

**If the current behavior is a bug, please provide the steps to reproduce.**

Save the snippet above as `index.js`. Create a dummy worklet saved as `worklet.js`.

```js
// worklet.js
import { TRUE } from './dependency.js';

class SomeProcessor extends AudioWorkletProcessor {
    process() {
        return TRUE;
    }
}

registerProcessor('some-processor', SomeProcessor);
```

Add another file to fake a dependency.

```js
// dependency.js
export const TRUE = true;
```

Create a config file named `config.js` with the following content.

```js
// config.js
module.exports = {
    module: {
        parser: {
            javascript: {
                worker: [
                    "*audioContext.audioWorklet.addModule()",
                    "*audioWorklet.addModule()",
                    "..."
                ]
            }
        }
    }
};
```

With all this in place running `npx webpack --config ./config.js --entry ./index.js --mode production` will not produce the expected result. The `worklet.js` file remains unprocessed and seems to be treated like an asset. The import statement remains untouched.

However running `npx webpack --config ./config.js --entry ./index.js --mode development` will produce the expected outcome. The `worklet.js` file gets processed as JavaScript and the dependency will be inlined.

**What is the expected behavior?**

I would expect the `worklet.js` file to get processed in both modes.

**Other relevant information:**
webpack version: v5.88.1
Node.js version: v18.16.1
Operating System: macOS
Additional tools: npm/npx v8.19.3

**Comment by chrisguttandin** [comment]
Sorry, I forgot to mention that this is probably related to the changes made in #17212.

**Comment by chrisguttandin** [comment]
I created a repo with the test case mentioned above.

https://github.com/chrisguttandin/webpack-audio-worklet-bug

The bug still persists with webpack v5.89.0.

**Comment by alexander-akait** [comment]
bump
