### ISSUE TITLE
v5.88.2 has not been published to npm

### ISSUE THREAD

**Issue by jneidel** [webpack/webpack#17500]
At the time of writing the latest [Release on Github](https://github.com/webpack/webpack/releases/tag/v5.88.2) is v5.88.2.

This version however has not been published on npm!
![screenshot_23-07-17_09:49:58](https://github.com/webpack/webpack/assets/25589715/e830ce87-bbef-4030-a863-3693a4343779)

An oversight?

Maybe just automate the npm publishing [like so](https://github.com/jneidel/oraclett/blob/master/.github/workflows/release.yml) (also adds npm provenance)?

**Comment by TheLarkInn** [comment]
Whoops I'm so sorry! Yes I'll push right away!

**Comment by TheLarkInn** [comment]
![image](https://github.com/webpack/webpack/assets/3408176/5fe566cc-185f-45b6-933a-2c92650ce5df)

Was oversight by myself! Forgot the last step 😅
