### ISSUE TITLE
How to test a loader

### ISSUE THREAD

**Issue by sullenor** [webpack/webpack#1751]
Hi,

I would like to know about good way to write tests for the webpack-loaders.

Currently, I figured out that loaders depend on the calling context and in order to test them I have to make a real config and launch the webpack to build files. So, I would like to know if there is a shorter way to do this? Is it possible to use any mock or smthing similar?

kind regards,
Alexey

**Comment by ChristopherBiscardi** [comment]
You could try using MemoryFS and the node API to script the webpack build process. I've attempted this with mocha but ran into some issues that I haven't had time to push through yet.

https://webpack.github.io/docs/node.js-api.html#compile-to-memory

**Comment by sullenor** [comment]
Yea, I tried using MemoryFS, but failed :)
Unfortunately, it requires patching webpack and I haven't checked all the possible issues here.

Thank you for the information, I will try to make another attempt on the weekend.

**Comment by sullenor** [comment]
Hi, looks like I got success at using *memory-fs*. Here is a small example in case if you are interested:
https://github.com/sullenor/webpack-loader

**Comment by sullenor** [comment]
okay, finally I figured how it works.

thanks
