### ISSUE TITLE
PUBLIC_URL is ignored if set in .env

### ISSUE THREAD

**Issue by tillganster** [webpack/webpack#17519]
# Bug report

I try to host my application beneath different paths. To control this is se the `PUBLIC_URL` variable in my .env files. 

**What is the current behavior?**

In my generated index.html the script tag for static js does not start with my path which I set via the `PUBLIC_URL` in .env file. If I set the variable on the host like `PUBLIC_URL=/some-path rpm run build`, the static path will start with `/some-path`. Additionally if I inspect `webpack.output.publicPath` the correct value is displayed.

**If the current behavior is a bug, please provide the steps to reproduce.**

- react-scripts project with craco enabled
- use `CracoEnv` plugin 
- create `.env.production`
- run `craco build --mode production`

**What is the expected behavior?**

The static js path should have a prefix, which can be set in .env.

I am aware that react-scripts is not scope of this repository. But that the behavior diverges when using a host environment vs a .env variable seems to be a bug.

**Other relevant information:**
webpack version:  ^5.64.4
Node.js version: v16.19.1
Operating System: MacOs Ventura 13.2.1
Additional tools: react-scripts & craco to override webpack config

**Comment by snitin315** [comment]
Make sure the `PUBLIC_URL` is added in the webpack config via the [DefinePlugin ](https://webpack.js.org/plugins/define-plugin/#root)

**Comment by tillganster** [comment]
Thanks for the hint.

But actually `PUBLIC_URL` is present in the Define Plugin see:
```
definitions: {
    'process.env': {
      NODE_ENV: '"production"',
      PUBLIC_URL: '"/test"',
     // additional variables ..
    }
}
```

**Comment by snitin315** [comment]
Not sure, I haven't used `craco` before. Would be great if you can create a repo on github to reproduce and share and share full webpack config.

**Comment by tillganster** [comment]
I just created a reproduction project. And the issue did not happen there. It seems that the `6.x.x` version of craco has this problem. Now with the latest `7.x.x` everything works fine. 

I guess the issue can be resolved on my side by updating dependencies. Thanks anyways for your help. 😄
