### ISSUE TITLE
tree shaking is enabled in development mode

### ISSUE THREAD

**Issue by xiaoxiaojx** [webpack/webpack#17516]
# Bug report
It is mentioned in the [documentation](https://webpack.js.org/guides/tree-shaking/#conclusion) that one of the conditions for tree shaking to be enabled is mode: production.

But I found that the development mode code disappeared. I never believed that it was caused by tree shaking, because the document was very sure that it would not be enabled, 😢 until I found this problem by debugging.

This is easy to reproduce, such as this warehouse [xiaoxiaojx/webpack-issuer](https://github.com/xiaoxiaojx/webpack-issuer)

**What is the current behavior?**
tree shaking is enabled in development mode

**What is the expected behavior?**
Modify the webpack documentation or fix the development mode bug

If it is confirmed to be a bug, I can contribute this pr

**Other relevant information:**
webpack version:  5.88.2

**Comment by xiaoxiaojx** [comment]
@TheLarkInn @alexander-akait Hello everyone, here I am again. Although turbopack, esbuild, and vite are very popular at present, my favorite is still webpack ❤️

**Comment by xiaoxiaojx** [comment]
This change caused  https://github.com/webpack/webpack/commit/e1b5a78a241cc6037031a2dba121a604ebf0a6e0

**Comment by xiaoxiaojx** [comment]
bump

**Comment by alexander-akait** [comment]
@xiaoxiaojx Yeah, side effects optimization is enabled in any mode to avoid big different between development and production, especial problems with side effects, because developers often make mistakes there, do you want to update our docs?
