### ISSUE TITLE
Webpack 5 not able to process node polyfills mentioned inside resolve.fallback and giving 59 errors to me

### ISSUE THREAD

**Issue by nandu901nandu** [webpack/webpack#17520]
**What is the current behavior?**

I tried all the solutions provided in internet from past 10 days and finally I am giving up, please help me for my job.
Uploaded  the webpack configs and package json and error files at this location:
https://gist.github.com/nandu901nandu/5683fa7533efb993f172604bd3dd1139

I added like this but still I am getting 59 errors:
 resolve: {
    fallback: {
      assert: require.resolve('assert'),
      buffer: require.resolve('buffer'),
      console: require.resolve('console-browserify'),
      constants: require.resolve('constants-browserify'),
      crypto: require.resolve('crypto-browserify'),
      domain: require.resolve('domain-browser'),
      events: require.resolve('events'),
      http: require.resolve('stream-http'),
      https: require.resolve('https-browserify'),
      "fs": 'empty',
      "path": 'empty',
      "os": 'empty',
      // os: require.resolve('os-browserify/browser'),
      // path: require.resolve('path-browserify'), // Add this line for 'path' module
      punycode: require.resolve('punycode'),
      process: require.resolve('process/browser'),
      querystring: require.resolve('querystring-es3'),
      stream: require.resolve('stream-browserify'),
      string_decoder: require.resolve('string_decoder'),
      sys: require.resolve('util'),
      timers: require.resolve('timers-browserify'),
      tty: require.resolve('tty-browserify'),
      url: require.resolve('url'),
      util: require.resolve('util'),
      vm: require.resolve('vm-browserify'),
      zlib: require.resolve('browserify-zlib'),
    },
  }

**What is the expected behavior?**
Should compile and run the website without issue

**Other relevant information:**
webpack: 5.88.2
webpack-cli: 4.10.0
webpack-dev-server 4.15.1
Node.js version: 14.21.3
Operating System: Mac
Additional tools:

**Comment by nandu901nandu** [comment]
<img width="1228" alt="image" src="https://github.com/webpack/webpack/assets/140332625/1d5cbdd0-81ef-4053-975a-d20095eddead">

**Comment by carlosrobert0** [comment]
It remained inactive but without a solution!
Shouldn't you guys from the webpack team bring the solution instead of inactivating the topic?
