### ISSUE TITLE
webpack-2: System.import breaks with dynamic output filename

### ISSUE THREAD

**Issue by mattkrick** [webpack/webpack#1752]
This one stumped me for awhile...
This works:
```
entry: {
    bundle: ['./src/client/index.js']
  },
  output: {
    filename: 'bundle.js',
 }
```
But if I try this (dynamic name):
```
entry: {
    bundle: ['./src/client/index.js']
  },
  output: {
    filename: '[name].js',
 }
```
And then async import something in the `index.js` *that wasn't previously required*:
`System.import('./foo').then(foo => {/*...*/})`

I get the following:
```
Uncaught SyntaxError: Unexpected token <
bootstrap 03fdf37…:568Uncaught (in promise) Error: Loading chunk 1 failed.(…)onScriptComplete @ bootstrap 03fdf37…:568
```

Let me know if this is enough info, happy to help however I can. Big thanks for everything you've done!

**Comment by sokra** [comment]
Does it work if you provide the `output.chunkFilename` option?

**Comment by mattkrick** [comment]
wow you're good. yep, that fixes it.

**Comment by benjasHu** [comment]
Hi @sokra. How could I install the version 2? I have tried install from the repository but always throws same error: *Uncaught ReferenceError: System is not defined*

In NPM is still 1.12.2.

Any help please? Thanks!

**Comment by mattkrick** [comment]
type `npm view webpack` to see all releases, 2 is still in beta, so you have to type `npm i -D webpack@2.0.1-beta`

**Comment by benjasHu** [comment]
Hi @mattkrick I've followed that with no luck... same error. Also, i have installed globally.

Must I have to update babel and babel-loader or anything else?

Thanks for your time.

**Comment by mattkrick** [comment]
yeah, uninstall webpack globally & locally. avoid global packages like the plague. then install as a local dependency, run webpack --version. if that doesn't work change your package.json to reference the master branch on github to go around npm all together.

**Comment by benjasHu** [comment]
wow! done! I had to uninstall webpack (locally & globally), update Babel from v5 to v6 (following steps [here](https://medium.com/@malyw/how-to-update-babel-5-x-6-x-d828c230ec53#.3ncur95fq) and finally install again webpack beta 2.0.1.

Thanks @mattkrick for your support!
