### ISSUE TITLE
splitChunks emits the same content multiple times when using with layers

### ISSUE THREAD

**Issue by denzelem** [webpack/webpack#17528]
# Bug report

I noticed that building a chunk with `webpackChunkName` and using the experimental `layer` feature results in duplicate content withing the chunk.

I created an example application to reproduce the issue: https://github.com/denzelem/webpack5-issue-20230725

*webpack.config.js*

```
const path = require("path")

module.exports = {
  mode: "production",
  entry: {
    light: { import: "./app/assets/light.js", layer: 'light' },
    dark: { import: "./app/assets/dark.js", layer: 'dark' },
  },
  output: {
    filename: "[name].js",
    sourceMapFilename: "[file].map",
    path: path.resolve(__dirname, "public/assets"),
    clean: true,
  },
  experiments: {
    layers: true,
  },
}
```

*app/assets/dark.js*

```
require('./javascripts/main')
```

*app/assets/light.js*

```
require('./javascripts/main')
```

*app/assets/javascripts/large_lib.js*

```
console.log('hello large lib')
```

*app/assets/javascripts/main.js*

```
import(/* webpackChunkName: "largeLib" */ './large_lib').then(() => {
  console.log('hello main')
})
```

**Result**:

```
cat public/assets/largeLib.js
(self.webpackChunkwebpack5_issue_20230725=self.webpackChunkwebpack5_issue_20230725||[]).push([[849],{616:()=>{console.log("hello large lib")},850:()=>{console.log("hello large lib")}}]);
```

**What is the current behavior?**

Having multiple layers results in duplicate content in a shared chunk. Notice the duplicate `hello large lib` in `public/assets/largeLib.js`.

**If the current behavior is a bug, please provide the steps to reproduce.**

Checkout https://github.com/denzelem/webpack5-issue-20230725:

- Install Node version `v19.7.0`
- `npm install`
- `npm run build`

And inspect `public/assets/largeLib.js`.

**What is the expected behavior?**

I would expect that having different layers should not result in duplicate content within shared chunks.

**Other relevant information:**
webpack version: 5.88.2
Node.js version: 9.7.0
Operating System: Ubuntu
Additional tools: -

**Comment by sibelius** [comment]
where can I get more info on layers?

**Comment by denzelem** [comment]
@alexander-akait Can you consider having a look at this issue? If it is not a bug aka intended behaviour I will consider using https://github.com/webpack/webpack/discussions to better understand how I should get this working within webpack. Thank you!

**Comment by ahabhgk** [comment]
From what I understand about the webpack source code, this is an expected behavior, layer is just a modifier prepend to the module's identifier, which can make the module have different instance with different layer.

In this reproduce, if you want to only have one instance of `large_lib.js`, you can specific the `large_lib.js`'s layer to `common`

```js
module: {
  rules: [
    { test: /large_lib\.js/, layer: 'common' }
  ]
}
```

before:

`(layer dark) dark.js` -> `(layer dark) main.js` -> `(layer dark) large_lib.js`
`(layer light) light.js` -> `(layer light) main.js` -> `(layer light) large_lib.js`

after:

`(layer dark) dark.js` -> `(layer dark) main.js` -> `(layer common) large_lib.js`
`(layer light) light.js` -> `(layer light) main.js` --^

**Comment by alexander-akait** [comment]
Yes, that is expected, you can create `shared`/`common` layer to prevent it
