### ISSUE TITLE
ModuleId conflict results in incorrect object being referenced

### ISSUE THREAD

**Issue by chrisbing** [webpack/webpack#17526]
# Bug report

**What is the current behavior?**
<img width="845" alt="image" src="https://github.com/webpack/webpack/assets/3222731/efa76149-a960-4956-b3bf-75c83abfb91e">

in the dist, a variable "a" was defined in module 261, but in module 374 the object was undefined, causing an error.

**If the current behavior is a bug, please provide the steps to reproduce.**

repository: https://github.com/chrisbing/demo-for-webpack-bug-module-id

webpack.config.js
```js
const HtmlWebpackPlugin = require('html-webpack-plugin')

module.exports = {
    entry: {
        a: './src/index-a.js',
        b: './src/index-b.js'
    },
    mode: "production",
    plugins: [
        new HtmlWebpackPlugin({
            chunks: ['b', 'a']
        })
    ]
}
```

source code:
<img width="1488" alt="image" src="https://github.com/webpack/webpack/assets/3222731/990d4578-5d94-4f0f-9f41-1037e0979950">

dist:
<img width="1705" alt="image" src="https://github.com/webpack/webpack/assets/3222731/f723bbf3-e423-48fe-9d0c-60ed89e390c7">

Because module 70 was loaded first, module 261 in 70.js was registered preferentially, and the dataA variable in this module has already been tree-shaken.

**What is the expected behavior?**
It was expected that module 374 would be able to access the corresponding object "a" in module 261 and successfully execute console.log.

**Other relevant information:**
webpack version:  5.88.2
Node.js version: v16.20.0
Operating System: macOs 13.4.1 arm64
Additional tools:  
html-webpack-plugin: 5.5.3

**Comment by hikerpig** [comment]
Setting `optimization: { runtimeChunk: 'single' }` and this error seems go away. Check [my branch](https://github.com/hikerpig/demo-for-webpack-bug-module-id/tree/demo-single-runtimeChunk) to see the diff.

This is most likely a bug with Webpack.
