### ISSUE TITLE
Output file contains try...finally block causing application failed in IE8 

### ISSUE THREAD

**Issue by BorelTung** [webpack/webpack#1753]
Built files contains try{ } finally{ } block without catch{} block, which causes applicaion failed in IE8.

**Comment by sokra** [comment]
Where?

**Comment by bebraw** [comment]
@BorelTung Can you provide a simple, runnable example (GitHub repo)?

**Comment by BorelTung** [comment]
In my built file app.[hash].js, it begin as
```
webpackJsonp([3], {
	0 : function (e, t, n) {
		try {
			(function () {
				"use strict";
				function e(e) {
					return e && e.__esModule ? e : {
						"default" : e
					}
				}
				var t = n(4),
				o = e(t),
				r = n(53),
				a = n(40),
				l = n(163),
				i = e(l);
				(0, r.render)(o["default"].createElement(a.Provider, {
						store : l.store
					}, o["default"].createElement(i["default"], null)), document.getElementById("app"))
			}).call(this)
		}
		finally {}
	},
```

**Comment by BorelTung** [comment]
It seems that every module will cause a try{}finally{} without catch{}. In my vender.[hash].js, there are 14 try{}catch{} without finally{}, and I just have exactly 14 3rd party lib in my vendor entry.
```
entry: {
    app: 'my-path',
    vendor: [
      'classnames',
      'es5-shim',
      'es5-shim/es5-sham',
      'history',
      'jquery',
      'lodash',
      'normalize.css',
      'react',
      'react-dom',
      'react-redux',
      'react-router',
      'redux',
      'redux-router',
      'redux-thunk'
    ]
  },
```

**Comment by BorelTung** [comment]
@bebraw Here is the [example](https://github.com/BorelTung/webpack-building-test).

**Comment by bebraw** [comment]
Why do you have hot loading enabled in your `dist` configuration? If I change `'react-hot!babel-loader'` to `'babel-loader' at *cf/dev.js*, the `try/finally` block goes away. I guess your dev configuration must leak to dist one somehow.

Please note that *react-hot* has been deprecated and it's preferable to use a [babel-plugin-react-transform](https://github.com/gaearon/babel-plugin-react-transform) based setup instead.

**Comment by BorelTung** [comment]
@bebraw  You are right. My dev configuration leaks to dist one.

The `_.assign` method only clone the reference of the object's array property, instead of clone deeply all those values. So the `push` method in my `dev.js` will modify the `loaders` property of the object that my `base.js` exports.

Thank you!

**Comment by BorelTung** [comment]
It does not work well though, in the vendor.[hash].js.

**Comment by BorelTung** [comment]
Maybe it is similar to this [issue](https://github.com/mbest/knockout-deferred-updates/issues/11).

**Comment by bebraw** [comment]
I'm not sure. You would have to figure out what generates the `try/finally`.
