### ISSUE TITLE
Loader with wrong include path does not throw error

### ISSUE THREAD

**Issue by yoriiis** [webpack/webpack#17541]
# Bug report

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

Babel transpilation is ignored without warning/error when the loader includes a wrong path. The problem is transparent and production code can be broken without transpilation.

The following repository illustrates the problem
https://github.com/yoriiis/webpack-loader-wrong-path

The loader include path is intentionally incorrect in [webpack.config.js#L27](https://github.com/yoriiis/webpack-loader-wrong-path/blob/main/config/webpack.config.js#L27), it should be `path.resolve(__dirname, '../src')`

Instruction to reproduce the problem on the repository:

- `git clone https://github.com/yoriiis/webpack-loader-wrong-path.git`
- `cd ./webpack-loader-wrong-path`
- `nvm use`
- `npm install`
- `npm run build`

**The build with the incorrect path and without transpilation**

![image](https://github.com/webpack/webpack/assets/2563298/9a2a0f55-6a80-4eab-a47d-f1d78744973c)

**The build with the correct path and with transpilation**

![image](https://github.com/webpack/webpack/assets/2563298/2b8aa155-751f-4c51-af79-dc2e77c034b7)

**What is the expected behavior?**

Webpack should trigger an error when the path is incorrect.

For example if the path to the Babel configuration file with [configFile](https://github.com/yoriiis/webpack-loader-wrong-path/blob/main/config/webpack.config.js#L32) is incorrect, it will throw an error.

I also notice that the path error for the Babel file is not triggered if the path of the includes field of the loader is incorrect. Is it linked? If not, I can report this issue on `babel-loader`, tell me.

**Other relevant information:**
webpack version: `5.88.1`
Node.js version: `18.12.0`
Operating System: `MacOS 13.4`
Additional tools: -

**Comment by yoriiis** [comment]
Always up to date

**Comment by alexander-akait** [comment]
Yeah, I see your problem, but test/include/exclude are regexps, so we can't undestand when it is a real path or it is a just regexp

**Comment by yoriiis** [comment]
Hello @alexander-akait, thanks for your reply. Do you think a check could be added? It's strange to have invalid paths and no warning.

**Comment by alexander-akait** [comment]
@yoriiis We have such things on our roadmap, but it is not a priority, also we have an idea to support globs here

**Comment by alexander-akait** [comment]
Let's close in favor https://github.com/webpack/webpack/issues/2553, maybe we will implement this in future
