### ISSUE TITLE
Webpack runtime can't resolve 1000+ chunks causing stackoverflow

### ISSUE THREAD

**Issue by maulshh** [webpack/webpack#17548]
# Bug report

When a webpack build creates a lot of chunks (1000 chunks), the logic used in webpack runtime to resolve chunkId -> assetUrl are easily causing maximum call stack on some browsers.

**What is the current behavior?**

A webpack build page that have 1000+ chunks to resolve on runtime.js will throw stackoverflow on Chrome, while it will still work on Firefox.

**If the current behavior is a bug, please provide the steps to reproduce.**

This fiddle is to reproduce the logic on webpack runtime with 1200 chunks will fail on Chrome:
https://jsfiddle.net/a2y46Lo7/

**What is the expected behavior?**

This could work if instead of using ternary operations webpack runtime use some object mapping instead, on
https://github.com/webpack/webpack/blob/1f99ad6367f2b8a6ef17cce0e058f7a67fb7db18/lib/runtime/GetChunkFilenameRuntimeModule.js#L279

Supposedly a build with thousands of chunks are very rarely needed, but some browsers may actually have less max stack and these errors can happen with just a few hundred of chunks. We have a lot of constraints on our build process and this stackoverflow error happened in our case.

**Other relevant information:**
webpack version:  5.75.0
Node.js version: 14
Operating System: Mac OS 13.4
Additional tools: Chrome 115, Firefox 115

**Comment by Solo-steven** [comment]
Hi @alexander-akait  I am interested in this bug, I would like to take this if possible, thanks

**Comment by Solo-steven** [comment]
Hi, @alexander-akait  @maulshh  It seems like the function webpack generated have really using object mapping as a lookup table, 
https://github.com/webpack/webpack/blob/1f99ad6367f2b8a6ef17cce0e058f7a67fb7db18/lib/runtime/GetChunkFilenameRuntimeModule.js#L285
webpack would generate object mapping with a sequence of if statements to return the correct url. Are the ternary operations  @maulshh mentioned webpack code after some ast transform?
Any help is greatly appreciated ~

**Comment by maulshh** [comment]
this bug is actually caused by Terser minification rather than webpack. 

> have really using object mapping as a lookup

That `Array` is for multiple ids that resolve to the same chunk-name, and it will return an if statement https://github.com/webpack/webpack/blob/1f99ad6367f2b8a6ef17cce0e058f7a67fb7db18/lib/runtime/GetChunkFilenameRuntimeModule.js#L289

it will create a chain of if statements
<img width="606" alt="image" src="https://github.com/webpack/webpack/assets/6881882/2b7de8e1-2710-490c-bd98-b95f9666c531">

and terser minification will change it to nested ternary causing the stackoverflow error.

**Comment by Solo-steven** [comment]
@maulshh Thanks for your reply! So I think I can open another issue on Terser to fix this bug and update the dep on webpack.

**Comment by fabiosantoscode** [comment]
@Solo-steven the fix is in Terser 5.19.4. Thanks for bringing this up on there!
