### ISSUE TITLE
How is import.meta.url assigned?

### ISSUE THREAD

**Issue by bh3605** [webpack/webpack#17558]
## Feature request

More of a series of questions than a feature request. How is import.meta.url assigned? Why are you unable to see the assigned value in a debugger like Chrome's? Why is import.meta.url only available in esm modules? The documentation doesn't explain this and it seems "magical" this variable is only available when you set scriptType to "module" and turn on the experiments.outputModule flag.

**Comment by absidue** [comment]
`import.meta.url` is part of the ES Modules spec, it is not a webpack specific feature. I recommend reading the docs about about `import.meta` https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import.meta
