### ISSUE TITLE
Webpack internal EntryPlugin does not work with multiple entries

### ISSUE THREAD

**Issue by adragich** [webpack/webpack#17554]
## Feature request

EntryPlugin does not produce multiple chunks in the case multiple entries are present. Currently, EntryPlugin always produces one chunk. If you try to pass an array of entries there it fails with a TS error, as it's not supported:

```Type 'string[]' has no properties in common with type 'EntryDescriptionNormalized'.ts(2559)
(property) metadataFetcher: string[]
```

**What is the expected behavior?**

Entry plugin produces as many entries as passed in the parameters.

**What is motivation or use case for adding/changing the behavior?**

Consistency between EntryPlugin and webpack entry configuration. It unlocks usage of EntryPlugin for the applications with multiple entries.

**How should this be implemented in your opinion?**

Accept an array of entries, compile each.

**Are you willing to work on this yourself?**

No. I am not aware what are the reasons why MultiEntryPlugin is deprecated in latest Webpack, seems like this functionality was present in Webpack4 but removed.

**Comment by alexander-akait** [comment]
@adragich Sorry for delaty, still valid?
