### ISSUE TITLE
How to use webpack on browser ?

### ISSUE THREAD

**Issue by WanderWang** [webpack/webpack#1757]
I want to use webpack on browser . There is the business requirement :

* Show some React JSX Example ( from user edited ) in browser
* compile it with webpack ( on browser ) and show the result view from a iframe .

I write the code such as this : 

```
var webpack = require("webpack");
webpack(option , callback);
```

It can run in browser because of ``` WebEnvironmentPlugin.js ``` , but it print lot's of error in ``` terminal webpack ```

**Comment by sokra** [comment]
It worked in the browser a while ago. I'm not sure if it still works.

Here is a very old demo: http://webpack.github.io/playground/

And here is the code: https://github.com/webpack/playground

You can start by updating this demo to a newer webpack version. It propably needs PRs to webpack to fix some issues.

**Comment by WanderWang** [comment]
hi @sokra , there are some exception when I install playground , I fixed it and send a PR https://github.com/webpack/playground/pull/1

**Comment by JIACHENG9** [comment]
I developed a library to simulate Nodejs in the browser so you can run the latest webpack4 in the browser (Chrome)

demo: https://nodebowl.com/static/examples/webpack.html
code: https://github.com/nodebowl/nodebowl
