### ISSUE TITLE
And no one provide an example of the problem?

### ISSUE THREAD

**Issue by PKhamorn302531** [webpack/webpack#17587]
And no one provide an example of the problem?

_Originally posted by @alexander-akait in https://github.com/webpack/webpack/issues/17213#issuecomment-1551849750_

**Comment by snitin315** [comment]
We appreciate your effort in raising this issue. To ensure clarity in understanding your situation, we kindly request you recreate the issue using one of our provided templates. 

Your collaboration will assist us in providing you with effective assistance.
