### ISSUE TITLE
Allow opt-in tree-shaking of class properties

### ISSUE THREAD

**Issue by rattrayalex** [webpack/webpack#17596]
## Feature request

Disclaimer: I assume this is not possible, and has already been discussed and rejected many times – but I couldn't find any previous discussion, so I thought I'd raise the topic in case there have been any advances in tree-shaking that could allow this.

**What is the expected behavior?**

Given a library that exposes an instance with methods for most operations ([real-world example](https://github.com/openai/openai-node/blob/v4/src/index.ts#L123-L124)):

```ts
import Completions from './completions'
import Images from './images'

export default class OpenAI extends APIClient {
  completions: Completions = new Completions(this);
  images: Images = new Images(this);
}
```
which is used like so:
```ts
import OpenAI from 'openai'

const client = new OpenAI()

const result = await client.completions.create()
```

It would be nice to have a way to tree-shake away the `images` API in the above example. 

Of course, this would have the dangerous result of changing the structure of the `OpenAI` class, here, in such a way that properties which are supposed to be a certain type would throw at runtime – eg, `client[calculateService()]` would either have to disable tree-shaking or throw.

**What is motivation or use case for adding/changing the behavior?**

There is a [tension between those who want efficient builds](https://twitter.com/jaredpalmer/status/1690420651117477888) (e.g., for fast boots on edge runtimes), and [developers](https://twitter.com/SheltonLouisX/status/1690421167373303808) who [like fluent APIs](https://twitter.com/mattpocockuk/status/1690446495542067200). 

For example, AWS had to fully [rewrite their SDK](https://aws.amazon.com/blogs/developer/modular-packages-in-aws-sdk-for-javascript/) to allow modularity, but this unfortunately hurts discoverability – per one developer I know, "I've used the new version of the AWS SDK and it is completely terrible when it comes to being able to actually find what you need". 

Devlopers would ideally [like to see](https://twitter.com/dillon_mulroy/status/1690423856320626688) bundlers improve their ability to handle patterns like this, to dodge the tradeoff entirely.

**How should this be implemented in your opinion?**

Perhaps like so:

```ts
import Completions from './completions'
import Images from './images'

export default class OpenAI extends APIClient {
  /** webpackTreeShakeableProperty: true */
  get completions(): Completions {
    return this._completions ??= new Completions(this);
  }
  
  /** webpackTreeShakeableProperty: true */
  get files(): Files {
    return this._files ??= new Files(this);
  }
}
```

which, with the above usage, would get transpiled to this:

```ts
import Completions from './completions'
export default class OpenAI extends APIClient {
  get completions() {
    return this._completions ??= new Completions(this);
  }
  
  get files() {
    throw new Error('property `files` on class `OpenAI` removed by webpack tree-shaking; see https://some.url/with-docs')
  }
}
```

Even better if the library author can use normal properties instead of getter methods.

**Are you willing to work on this yourself?**

I'd be willing to fund this work, depending on the scope.

**Comment by CoolBoyLeo** [comment]
Thank you very much for your detailed feedback. After testing with webpack 5.88.2, I also noticed the issue you mentioned: Unused class properties were not removed. Inspired by your suggestion, I created a simple demo based on AST to address this problem.

**The main steps are as follows:**

1. Use @babel/parser to parse the code into an AST (Abstract Syntax Tree).
2. Traverse the AST with @babel/traverse, noting class method definitions and invocations.
3. Determine the class methods that have not been called based on the records.
4. Traverse the AST again, removing nodes for unused class methods.
5. Use @babel/generator to produce new code from the optimized AST.

**Original Code:**
```JavaScript
class OpenAI {
    constructor() {
   }

    completions() {
        console.log("Completion result from OpenAI.")
    }

    images() {
        console.log("Generating images...");
    }
}

const client = new OpenAI()
const result = client.completions()
console.log(result);
```

**Trimmed Code:**
```JavaScript
class OpenAI {
  constructor() {}
  completions() {
    console.log("Completion result from OpenAI.");
  }
}
const client = new OpenAI();
const result = client.completions();
console.log(result);
```

**Implementation Code:**
```JavaScript
const parser = require("@babel/parser");
const traverse = require("@babel/traverse").default;
const generator = require("@babel/generator").default;
// This class represents a study session a student might have.
const code = `
class OpenAI {
    constructor() {
   }

    completions() {
        console.log("Completion result from OpenAI.")
    }

    images() {
        console.log("Generating images...");
    }
}

const client = new OpenAI()
const result = client.completions()
console.log(result);
`;

// Parse the code to generate AST
const ast = parser.parse(code, {
    sourceType: "module",
    plugins: ["jsx", "classProperties"],
});

// Store the methods from the classes and track if they've been called
const methods = new Map();

// Map variables to their class names for reference
const variableToClassMap = new Map();

traverse(ast, {
    ClassMethod(path) {
        const className = path.findParent((p) => p.isClassDeclaration()).node.id.name;
        const methodName = path.node.key.name;
        methods.set(`${className}.${methodName}`, false);
    },
    VariableDeclarator(path) {
        if (path.node.init.type === "NewExpression") {
            variableToClassMap.set(path.node.id.name, path.node.init.callee.name);
        }
    },
    CallExpression(path) {
        const callee = path.node.callee;

        if (callee.type === "MemberExpression") {
            const className = variableToClassMap.get(callee.object.name) || (callee.object.type === "ThisExpression" ? "this" : null);
            const methodName = callee.property.name;

            if (methods.has(`${className}.${methodName}`)) {
                methods.set(`${className}.${methodName}`, true);
            }
        }
    },
});
const unusedMethods = [...methods.entries()]
    .filter(([method, used]) =>
        !used &&
        !method.endsWith('.constructor')
    )
    .map(([method]) => method);


console.log("Unused methods:", unusedMethods);

// Traverse the AST again to remove the unused methods
traverse(ast, {
    ClassMethod(path) {
        const className = path.findParent((p) => p.isClassDeclaration()).node.id.name;
        const methodName = path.node.key.name;

        const methodKey = `${className}.${methodName}`;

        if (unusedMethods.includes(methodKey)) {
            path.remove(); // This deletes the node representing the method from the AST.
        }
    },
});

// Generate the optimized code and output it
const output = generator(ast).code;
console.log(output);
```
This method still has its limitations. It might not cover all scenarios and may not be fully compatible with webpack. If you have better suggestions or any other points for discussion, please share. I look forward to engaging in a deeper dialogue with you and collectively refining this solution.

**Comment by RobertCraigie** [comment]
This would still be really helpful!

**Comment by alexander-akait** [comment]
Technically, I think you can setup terser to do it without `webpackTreeShakeableProperty`, but yeah, terser doesn't build a graph so you need manually provide values, and yes, it is a hard tasks, you can try to implement your own plugin to make such things, we have an API for it
