### ISSUE TITLE
Feature request: Add `__non_webpack_import__`

### ISSUE THREAD

**Issue by Ayc0** [webpack/webpack#17597]
## Feature request

**What is the expected behavior?**

Add a ~`import.meta.import()`~ `__non_webpack_import__()` that would behave exactly like the native `import()` from browsers, but that wouldn't be modified by webpack (nor transpilers like babel)

**What is motivation or use case for adding/changing the behavior?**

I have a piece of code like this: `import(dynamicVariablePointingToACDN)`

But due to wepback's default behavior, it tries to find this dynamically in its module context.

I tried to use `externalsPresets: { asyncWeb: true }}` with ``import(`https://${dynamicVariablePointingToACDN.replace('https://', '')}`)`` but it didn't seem to work (and instead I used `eval(import(dynamicVariablePointingToACDN))` to avoid webpack's transpilation)

Either way, all of those seem like hacks / seem really brittle (could break at any change in the config). Whereas `import.meta.import` would just represent how browser work (so more robust in the long term)

**How should this be implemented in your opinion?**

At compile time, we can transform those to native `import()` (maybe if other flags are also enabled, like `experiments: { outputModule: true }`, or we could always compile them to `import()` and in case of errors, use the default browser mechanism for those, and not built-in logic in webpack).

**Are you willing to work on this yourself?**

I have no knowledge of webpack's internal so no, but I can give it a try

**Comment by AprilArcus** [comment]
My team would love to have this as well, for the same use case. Generally, this would provide ESModules feature-parity with respect to [__non_webpack_require__](https://webpack.js.org/api/module-variables/#__non_webpack_require__-webpack-specific) function available in CommonJS.

**Comment by Ayc0** [comment]
Maybe this should be `__non_webpack_import__` to match the other convention

**Comment by Ayc0** [comment]
I created this branch: https://github.com/webpack/webpack/compare/main...Ayc0:webpack:Ayc0/import?expand=1

If this issue is considered worthy of being fixed, I can open it

**Comment by Ayc0** [comment]
@TheLarkInn what do you think about this feature?

**Comment by alexander-akait** [comment]
Why don't use `import(/* webpackIgnore: true */ "my-name")`?

**Comment by Ayc0** [comment]
> Why don't use `import(/* webpackIgnore: true */ "my-name")`?

I won't lie, I completely forgot about that. Does `webpackIgnore` also makes so that the imported file is not injected in the bundle (and just outputs a native `import()` in the generate code)?

**Comment by alexander-akait** [comment]
@Ayc0 

Source:

```js
async function test() {
  const my_logic = await import(/* webpackIgnore: true */ "my-name");

  return my_logic;
}


test();
```

Output:

```js
/******/ (() => { // webpackBootstrap
var __webpack_exports__ = {};
/*!**********************!*\
  !*** ./src/index.js ***!
  \**********************/
async function test() {
  const my_logic = await import(/* webpackIgnore: true */ "my-name");

  return my_logic;
}


test();

/******/ })()
;
```

we keep `import(...)` as is

**Comment by Ayc0** [comment]
oh!
I didn't know, thanks!
