### ISSUE TITLE
List un-hot-reloadable parent modules when module is not hot-reloadable

### ISSUE THREAD

**Issue by matthewgertner** [webpack/webpack#1760]
If a module cannot be hot-loaded, the infamous "The following modules couldn't be hot updated" error is displayed in the console. If my understanding is correct, this means that the module is imported by at least one other module that is not hot-reloadable. If this is right, it would be incredibly useful to be able to get a list of the parent modules in question. So if my module is used by modules A, B and C, and only C is hot-reloadable, it would tell me that it can't hot-reload my module because A and B are not hot-reloadable. Something like:

```
[HMR] The following modules couldn't be hot updated: (They would need a full reload!)
[HMR]  - 523
[HMR] (module is imported by modules 42 and 1337 that cannot be hot updated)
```

Does this make sense? If so, does something like this already exist?

**Comment by sokra** [comment]
Makes sense.
