### ISSUE TITLE
Experiments.css reliance on fact that css should be loaded before js is a huge breaking change

### ISSUE THREAD

**Issue by IdeaHunter** [webpack/webpack#17611]
# Bug report/breaking change
Im trying experimental feature: #14893 

Imagine you have following code
index.js:
```js
import './index.css'
addEventListener("DOMContentLoaded", (event) => {
     //do something useful here
})
```
index.html:
```html
<!DOCTYPE html>
<html>
    <head>
        <script src="./main.js"></script>
        <link rel="stylesheet" href="./main.css"></link>
    </head>
    <body>

    </body>
</html>
```

**What is the current behavior?**
This code would fail:
```
Uncaught TypeError: __webpack_modules__[moduleId] is not a function
    at __webpack_require__
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Here I made a repo to reproduce:
1) Clone [https://github.com/IdeaHunter/webpack-serve-css-modules-repro](https://github.com/IdeaHunter/webpack-serve-css-modules-repro)
2) `yarn install`
3) `yarn webpack` or `yarn webpack serve`

**What is the expected behavior?**
No error should happen or if its intended behavior there should be a friendly error message and there should be a breaking change entry in migration docs for webpack 6

**Other relevant information:**
webpack version:  5.88.2
Node.js version: 18.16.0
Operating System: windows
Additional tools: yarn

**Comment by IdeaHunter** [comment]
Bump

**Comment by mems** [comment]
I've got the same issue with a HTML fragment (which contains styles and scripts of an entry which is pure CSS) loaded (with jQuery) in the document. The script try to find the loaded chunk, but it' can't can't access to the `sheet` property and check before loaded CSS chunk before the CSS is loaded (non blocking?).

I think it's related to [how entry startup work](https://github.com/webpack/webpack/blob/1f13ff9fe587e094df59d660b4611b1bd19aed4c/lib/javascript/StartupHelpers.js#L51-L55) that consider the stylesheet not a chunk, means all modules should be available synchronously when the entry start.
Maybe the [CSS loading runtime](https://github.com/webpack/webpack/blob/1f13ff9fe587e094df59d660b4611b1bd19aed4c/lib/css/CssLoadingRuntimeModule.js#L171) should wait/watch each stylesheet loading to detect if the CSS module is loaded (via the custom CSS variable). 
Or [use additional attributes](https://github.com/webpack/webpack/issues/16147#issuecomment-1596316526) that describe the file content (and optionally need to detect if the file load or fail to load)

**Comment by alexander-akait** [comment]
Close https://github.com/webpack/webpack/issues/14893, I added it and we need improve it

**Comment by alexander-akait** [comment]
Also you should use `link` not `<script src="./main.css"></script>`, but I think it is just a typo, feel free to feedback

**Comment by IdeaHunter** [comment]
Ok, thanks, closing it

@alexander-akait im curretly using workaround that embeds part of css with variable --webpack-bla-bla via pluing into js.
It would be nice if expements.css could give it as an option right out of the box to flip some flag. this option is best for me since i dont use css export at all

**Comment by alexander-akait** [comment]
We can do it, please write about it here https://github.com/webpack/webpack/issues/14893 with examples so we don't forget about it, there are a lot of good improvements too

**Comment by hardfist** [comment]
@alexander-akait maybe this shouldn't be closed and should be tracked separately, it's actually a bug which cause experiments.css nearly impossible to work 100% right in production environment. if the css file is loaded after js start(which heavily depends on network status), the js will likely fail

**Comment by hardfist** [comment]
> @hardfist we have #14893
> 
> > #14893 - allow link be before/after script
> 
> I think we might need an option for this to avoid generating extra runtime code.

yeah i'm aware of #14893 but it seems #14893 is better for tracking unsupported feature other than bug

**Comment by alexander-akait** [comment]
@hardfist yeah, typo

**Comment by alexander-akait** [comment]
@hardfist 

> if the css file is loaded after js start(which heavily depends on network status), the js will likely fail

Do you mean that the link is located above `script`, but due to network problems, the CSS is not loaded? If I'm not mistaken - `link` mandatory for loading...

**Comment by alexander-akait** [comment]
@hardfist 

> it is loaded but finish loaded after js start execute，there is no mechanism on js side that waiting until css is fully loaded before js start execute

Weird, because `link` mandatory for loading according to specification...

Can you demonstrate the problem?

**Comment by hardfist** [comment]
@alexander-akait  you can reproduce here https://github.com/hardfist/css-loading-bug

**Comment by alexander-akait** [comment]
@hardfist Oh `safari browser`...

**Comment by mems** [comment]
> @hardfist
> 
> > it is loaded but finish loaded after js start execute，there is no mechanism on js side that waiting until css is fully loaded before js start execute
> 
> Weird, because `link` mandatory for loading according to specification...
> 
> Can you demonstrate the problem?

As [DOMContentLoaded page on MDN](https://developer.mozilla.org/en-US/docs/Web/API/Document/DOMContentLoaded_event) mention it:
> `DOMContentLoaded` does not wait for style sheets to load, however deferred scripts do wait for style sheets, and the `DOMContentLoaded` event is queued after deferred scripts.

But.. it's only the case if the style sheet is created directly by the document parser.
That means, [in my case](https://github.com/webpack/webpack/issues/17611#issuecomment-1738842049), the JS that inject the HTML fragments must load style sheets before it inject scripts to simulate script-blocking style sheet.

See also [4.2.7 Interactions of styling and scripting - HTML Standard](https://html.spec.whatwg.org/multipage/semantics.html#interactions-of-styling-and-scripting)

**Comment by alexander-akait** [comment]
@mems 

> As [DOMContentLoaded page on MDN](https://developer.mozilla.org/en-US/docs/Web/API/Document/DOMContentLoaded_event) mention it:

> DOMContentLoaded does not wait for style sheets to load, however deferred scripts do wait for style sheets, and the DOMContentLoaded event is queued after deferred scripts.

We don't use `DOMContentLoaded`, we use `load` event and wait it

> But.. it's only the case if the style sheet is created directly by the document parser.
> That means, https://github.com/webpack/webpack/issues/17611#issuecomment-1738842049, the JS that inject the HTML fragments must load style sheets before it inject scripts to simulate script-blocking style sheet.

I think something like this should be organized by the app

**Comment by alexander-akait** [comment]
I reproduced and am looking deeper

**Comment by alexander-akait** [comment]
The problem is here - `getComputedStyle`, because Safari fires DomReady before linked resources and deferred scripts are loaded...
