### ISSUE TITLE
How to fix MIME type Error and key already exists in the object store.

### ISSUE THREAD

**Issue by dctls** [webpack/webpack#17624]
- Hello, @emkay @jdelStrother @marcus @jscheid @jdalton 
- I am working on React js project and using Webpack to try to create a build, I use this dependence

    "webpack": "^5.75.0",
    "webpack-cli": "^4.10.0",
    "webpack-dev-middleware": "^5.3.3",
    "webpack-dev-server": "^4.11.1"
    "sass-loader": "^12.6.0",
    "scss-loader": "^0.0.1",
    "style-loader": "^3.3.3",
    "url-loader": "^4.1.1",
    "file-loader": "^6.2.0",
    "css-loader": "^6.8.1",
    "html-webpack-plugin": "^5.5.3", 

- try to find a solution but not any perfect answer to fix that errors.
![image](https://github.com/webpack/webpack/assets/127742478/315feaae-5bd6-4b79-8bfb-da5734a14de9)

**Comment by alexander-akait** [comment]
Sorry without reproducible test repo we can't help
