### ISSUE TITLE
Suggestions to solve lazy-cache with webpack

### ISSUE THREAD

**Issue by kmalakoff** [webpack/webpack#1763]
Would you be able to review the following issue and let us know what the solution space is? https://github.com/jonschlinkert/lazy-cache/issues/3

**Comment by mgreer** [comment]
Webpack has its own code-splitting methodology, which I think might work better for you: https://webpack.github.io/docs/code-splitting.html

**Comment by kmalakoff** [comment]
@mgreer thank you! Currently, I am aliasing the offending modules to browser-friendly replacements, but that may not always be acceptable (it involves maintaining different implementations) and unfortunately, doesn't really address the underlying issue.

The question is more on @jonschlinkert's side who is hoping that there is a compile-time or loader-based work around so that people can use lazy-cache with webpack.

**Comment by jonschlinkert** [comment]
> hoping that there is a compile-time or loader-based work around so that people can use lazy-cache with webpack.

that would be great. although after doing more research, ideally it would be great to fix the problem directly in webpack, since the issue is technically caused by a webpack implementation choice - meaning how webpack renames the `require` function, otherwise it shouldn't be a problem (as with browserify).

**Comment by kmalakoff** [comment]
@jonschlinkert to manage your expectations a little bit here...

webpack and browserify are very different architectures and webpack's key architectural decision is to do static analysis which creates benefits / opportunities and tradeoffs that are quite different from browserify...their goal is not for feature parity nor compatibility with each other, but to innovate around what could be a better browser development experience. 

It looks me some time to get comfortable with their design decisions, but I really love it now for web applications. Unfortunately, I've had to do things in different ways that I would in other environments and it means I need to avoid doing certain things in node to maintain compatibility (specifically around dynamic string-based module loading). At the same time, there are things that I can do amazingly easily in webpack so the tradeoff is worth it for me and my front end teams.

For that matter..brunch, duo, component, require.js / AMD, ES6, and all the new kids on the block, approach modules and pipelines a little differently with their own take on what might be best for the browser environments and / or workflow (eg. different goals = different solutions).

I'm not sure what will be possible to resolve this, but I'm hoping someone will come up with something that works!

**Comment by jonschlinkert** [comment]
that's a great summary, thanks! I mentioned earlier that I don't actually use either browserify or webpack, since that's not the kind of development I do usually, but i will be soon so this helps. 

I'm willing to roll up my sleeves to find a solution to this, so even if we can get more information on where to start, that would be helpful.

**Comment by jonschlinkert** [comment]
I've removed lazy-cache from micromatch and underlying libs. @doowb made a loader that fixes the problem, but it seems impossible to let everyone know this in advance. I guess this should be closed

**Comment by doowb** [comment]
@kmalakoff I published [unlazy loader](https://www.npmjs.com/package/unlazy-loader). I tested it on one project that I know has `lazy-cache` in the dependencies and it works. It follows the pattern that we use to allow browserify to work, so if there are still issues in a dependency that isn't setup with that pattern, an issue should be open on that repo.

As @jonschlinkert mentioned, the hard part (or brittle part) is notifying people they need to use this with webpack.

**Comment by kmalakoff** [comment]
@jonschlinkert I've installed the updated version of micromatch and it works without a hitch in webpack.

@doowb with a non-lazy version of micromatch, I'm good. Thank you for publishing the module (my comment about the alias solution I not needed I suppose).

Closing...

**Comment by jonschlinkert** [comment]
:+1: great to know, thanks for sorting it out with us!
