### ISSUE TITLE
HookWebpackError: HMR is not implemented for module chunk format yet [webpack 5]

### ISSUE THREAD

**Issue by agarwalamn** [webpack/webpack#17636]
# Bug report

**What is the current behavior?**

We're currently encountering an issue while attempting to build our webpack based projects using the target browserlist (last 10 version) configuration. The error message we're encountering is: "HMR is not implemented for module chunk format yet."
Our goal is to transition our application to use ESM (ECMAScript Modules), and to achieve this, we've been working with the required ESM configuration. While we have been able to successfully build the project, this HMR-related error is causing a roadblock in our development process.

Upon investigation, we've traced the source of this error to the code snippet found at this location: Webpack [ModuleChunkFormatPlugin](https://github.com/webpack/webpack/blob/853bfda35a0080605c09e1bdeb0103bcb9367a10/lib/esm/ModuleChunkFormatPlugin.js#L55).

**If the current behavior is a bug, please provide the steps to reproduce.**

N/A

**What is the expected behavior?**

We would greatly appreciate your guidance and assistance in resolving this issue. We believe that enabling HMR support for the module chunk format would be a valuable enhancement, especially for projects like ours that are moving towards ESM adoption

**Other relevant information:**
webpack version:  5
Node.js version: 18

**Comment by alexander-akait** [comment]
It is still under development and in our roadmap, sorry for delay, we have an issue for full compatibility ES modules

**Comment by ozyx** [comment]
@alexander-akait 
Are there any known workarounds? This is blocking us from fully switching to ESModules with webpack.

**Comment by faceyspacey** [comment]
any word

**Comment by Timar-91** [comment]
me too

**Comment by jmedrano10** [comment]
Hola.

Al crear un single-spa application:
create-single-spa --framework react

me encuentro con el error:

HookWebpackError: HMR is not implemented for module chunk format yet

**Comment by joeldenning** [comment]
The create-single-spa webpack config has been patched to fix this. See https://github.com/single-spa/create-single-spa/releases/tag/webpack-config-single-spa%407.0.1

**Comment by mariusGundersen** [comment]
@alexander-akait is this being tracked in another issue?

**Comment by alexander-akait** [comment]
@mariusGundersen Yes, we also have a good PR, hope we will merge it for 5.100.0
