### ISSUE TITLE
source maps not working on exceptions

### ISSUE THREAD

**Issue by geddski** [webpack/webpack#1765]
I've got sourcemaps enabled with the `cheap-source-map` option. They're working great for console.logs, debugger statements etc. But when runtime exceptions are thrown, Chrome is showing the source as the compiled output file rather than the actual source. Webpack v1.12.9 and webpack-dev-server 1.14.0

**Comment by geddski** [comment]
It's worth noting that `eval` option *does* work on excpetions

**Comment by sokra** [comment]
That's an browser issue.

**Comment by geddski** [comment]
@sokra ok good to know. Thx
