### ISSUE TITLE
Webpack 4.47.0 was published as 'lastest' instead of 'webpack-4' on npmjs.com

### ISSUE THREAD

**Issue by Quintinon** [webpack/webpack#17658]
# Bug report
**What is the current behavior?**
Running the 'npm outdated' command returns 4.47.0 as the latest version of webpack instead of 5.88.2

**If the current behavior is a bug, please provide the steps to reproduce.**
install webpack 5.88.2 via npm
run npm outdated
notice that the reported latest version is 4.47.0 instead of 5.88.2

**What is the expected behavior?**
I expect 5.88.2 to be marked as latest while 4.47.0 would appear as the 'webpack-4' branch version.

**Other relevant information:**
webpack version:  
Node.js version:
Operating System:
Additional tools:

**Comment by TheLarkInn** [comment]
That was accidental by me! Thanks for the report this should now be resolved as of a few hours ago.
