### ISSUE TITLE
Asset module type 'source' outputs weird file.

### ISSUE THREAD

**Issue by KorayAydemir** [webpack/webpack#17652]
# Bug report
source type from asset modules is not working as expected

**What is the current behavior?**
asset/source type is supposed to be like raw-loader and just leave my ejs file as it is, according to documentation. However, it processes my ejs file into this:
``` 
var _ = eval("require")("/Users/kaydemir/code/projects/react/newyasamnedir/node_modules/.pnpm/lodash@4.17.21/node_modules/lodash/lodash.js");module.exports = function (templateParams) { with(templateParams) {return (function(data) { var __t, __p = ''; __p += '<!DOCTYPE html>\n<html lang="en">\n <head>\n <title></title>\n <meta charset="UTF-8">\n <meta name="viewport" content="width=device-width,initial-scale=1">\n </head>\n <body>\n <div id="root"></div>\n <div>\n <p>This is a dynamic value from EJS: ' + ((__t = ( dynamicValue )) == null ? '' : __t) + '</p>\n </div>\n </body>\n</html>\n'; return __p })();}}
```
However, if i use raw-loader npm package by only changing 1 line, it just works. It does not touch my ejs file. Therefore I'm forced to use a deprecated package.
```
            {
                test: /\.ejs/,
                use: 'raw-loader', // when this is type: 'asset/source', it breaks my ejs file like above.
            },
```
**If the current behavior is a bug, please provide the steps to reproduce.**
1- Clone and go to this commit hash on my new, pretty simple project: https://github.com/KorayAydemir/yasam-nedir-website/tree/884c57cc889d68b3de6883adb75fd4f887ef0159
2- `pnpm install`
3- In  webpack/webpack.dev.config.js, just change `use: 'raw-loader'` to `type: asset/source`.
4-`pnpm dev`
5- It will give you that weird ejs file in build/views/index.ejs

**What is the expected behavior?**
same as raw-loader's behaviour, as stated in docs. It should just leave the ejs file as it is, as far as i understand.

**Other relevant information:**
webpack version:  
    "webpack": "^5.88.2",
    "webpack-cli": "^5.1.4",
Node.js version: 18.16.0
Operating System: MacOS Ventura 13.4.1
Additional tools:

**Comment by uytruong** [comment]
I had the same problem when loading .html files using `type: asset/source`

**Comment by uytruong** [comment]
I found that using this solve the issue
`{
        test: /\.html$/,
        type: 'asset/source',
        exclude: /index\.html/
      }`

**Comment by alexander-akait** [comment]
Sorry for delay, yes, because you have `ejs` loader, `HtmlWebpackPlugin` uses it to generate content, just use `exclude: /public\/views\/index\.ejs$/,`
