### ISSUE TITLE
EvalSourceMapDevToolPlugin with append= false add always source map url

### ISSUE THREAD

**Issue by francesc79** [webpack/webpack#17663]
# Bug report

**What is the current behavior?**

according with documentation https://webpack.js.org/plugins/eval-source-map-dev-tool-plugin/#options
append = false the sourceURL should be not be appended

instead in the dist/main.js is added sourceURL 
//# sourceURL=[module]\n//# sourceMappingURL=

**If the current behavior is a bug, please provide the steps to reproduce.**

git clone https://github.com/francesc79/webpack-source-map
npm i
npm run build

**What is the expected behavior?**

that sourceURL will not be added but create a file. Thi works with SourceMapDevToolPlugin

**Other relevant information:**
webpack version:  5.88.2
Node.js version: v18.17.1
Operating System:
Additional tools:

**Comment by rafalp** [comment]
Interestingly this bug only occurs when map files names end in `*.map` As long as I change this to something else, this setting is respected.

**Comment by alexander-akait** [comment]
Yeah, it is a bug, feel free to send a PR with fix, it should be easy

**Comment by alexander-akait** [comment]
I have studied the problems carefully. 

You need to set `devtool: false` if you use sourcemaps plugins, i.e. `EvalSourceMapDevToolPlugin` or `SourceMapDevToolPlugin`

But yes, append is broken, WIP on this

**Comment by rafalp** [comment]
Not OP, but I've had Django deployments blow up because WebPack would include `//# sourceURL=something.mjs` where `something.mjs` didn't exist in bundle or final build.

**Comment by francesc79** [comment]
@alexander-akait thanks for time to investigate for my problem.
My idea is to include source map in a production bundle and import them with chome dev tools when need for debug. If sourceURL is not set another developer can't see the source. I would like to store the source map in a protected folder from server.

**Comment by alexander-akait** [comment]
@francesc79 Can you provide steps how do you want to do it? Just want to undestand better, thank you

**Comment by francesc79** [comment]
the steps are:

1.  open dev tools
2. go to source tab
3. select a chunk
4. in a source code press dx mouse button and select add source map
5. add a link a source map

**Comment by alexander-akait** [comment]
@francesc79 where did you get source maps? because eval source maps generate base64 code inside eval

**Comment by francesc79** [comment]
@alexander-akait when use EvalSourceMapDevToolPlugin or SourceMapDevToolPlugin the plugin create a source map file 
es. something.mjs where is something.js module. If append = false (now not working) in module something.js you not have //# sourceURL=something.mjs  so in this case the browser not known about source map. But if you go in devtools you can add sourcemap and debug easaly your code.

**Comment by alexander-akait** [comment]
@francesc79 So you want to use source maps generated by `SourceMapDevToolPlugin`, but when `EvalSourceMapDevToolPlugin` is used? Why just don't use `hidden-nosources-source-map`?

**Comment by francesc79** [comment]
@alexander-akait you have right, For my use case hidden-nosources-source-map is a right way. Thanks

**Comment by snitin315** [comment]
I think we need to update the docs here

**Comment by alexander-akait** [comment]
@snitin315 Yeah, feel free to do it
