### ISSUE TITLE
How to change the index file for require?

### ISSUE THREAD

**Issue by kilianc** [webpack/webpack#1767]
I usually require something like: `components/foo/foo.jsx` and since I am lazy I started renaming components to `index.jsx` so that I can simply require `components/foo`.

Is there a way to hack around the require resolve algorithm?

**Comment by sokra** [comment]
You can write a resolver plugin. 

https://github.com/webpack/enhanced-resolve/blob/master/lib/DirectoryDefaultFilePlugin.js

**Comment by kilianc** [comment]
YEah but I just realized my test suite won't work because it's running in node :/

**Comment by IngwiePhoenix** [comment]
If I understand correctly, you can use the libraryTarget option.
Its written in the docs. It let’s you choose how your stuff is exported.

**Comment by kilianc** [comment]
@IngwiePhoenix nope I don't think that's it, but it turns out I know how to do it but it won't be isomorphic with server / test suite so it's not worth it.
