### ISSUE TITLE
noParse: /node_modules/ leads to Cannot find module

### ISSUE THREAD

**Issue by Jormundir** [webpack/webpack#1768]
With the following config, I'm unable to require modules from my app directory without getting a `Cannot find module` error (at nodejs run time).

```
var config = {
  context: path.join(__dirname, '..'),
  module: {
    loaders: [
      { test: /\.jsx?$/, loader: 'babel', query: { presets: ['react', 'es2015'] } },
      { test: /\.s?css$/, loader: ExtractTextPlugin.extract('style', 'css', 'sass') }
    ],
    noParse: /node_modules/
  },
  resolve: {
    extensions: ['', '.js', '.jsx'],
    modulesDirectories: ['node_modules', 'app']
  }
};
```

What I'm trying to do: I'd like to get rid of the `externals` hack for my server side bundle.

**Comment by sokra** [comment]
> noParse: /node_modules/

That makes no sense. Use externals if you don't want these modules inside the bundle.

**Comment by Jormundir** [comment]
Why does that not make sense?

**Comment by xjamundx** [comment]
@Jormundir  Because webpack needs to process all of the modules in the node_modules folder

**Comment by elado** [comment]
Take a look at https://github.com/liady/webpack-node-externals

**Comment by vyorkin** [comment]
as I understand the reason why it cannot find modules when you set `noParse: /node_modules/` is that `noParse` is tested against absolute file path that also includes a loading absolute path, e.g. `/Users/foo/bar/baz/qux/node_modules/babel-loader/index.js!/Users/foo/bar/baz/quux/your/project/file.js`, so it matches when you specify `/node_modules/` and this is why everything is ignored

not sure my explanation is clear enough though :)
