### ISSUE TITLE
Custom conditionNames break default conditionNames

### ISSUE THREAD

**Issue by guybedford** [webpack/webpack#17692]
Hi, I was looking to figure out the correct Webpack configuration to load with condition names, and there is very little information about what default condition names apply.

I'm using the Webpack `resolve` `conditionNames` configuration to add a custom platform condition for `"fastly"`. But from reading the documentation I'm unable to determine how this will interact with other conditions in Webpack.

It took a lot of searching to find https://gist.github.com/sokra/e032a0f17c1721c71cfced6f14516c62, which is a great resource, although doesn't clarify the interaction with custom `resolve: { conditionNames }` either.

When specifying custom conditionNames, I do not want the Webpack default handling of standard conditions to be disabled.

Specifically I had the following questions:

1. Do I need to explicitly configure the `"default"` condition? Reading the code, I can't see this condition being always used, despite the fact that Node.js specifies that it must always be resolved.
2. From reading other issues, I see that `"import"` and `"require"` aren't automatically used and must be specified, due to the resolver having no context bit to know if the importer is CJS or ESM. Again, this is breaking against the Node.js specification of how resolution should work.
3. I know Webpack automatically uses the `"module"` condition, again there is no documentation on whether this condition is automatically applied, or if I need to specify it manually.
4. It's also not clear to me if the `"browser"` or `"node"` conditions are being automatically added.

esbuild has really great handling for the above in doing "the right thing" and covers all these details really succinctly in https://esbuild.github.io/api/#conditions.

Perhaps Webpack should offer a new `platformConditions` or otherwise field that simply composes with the default condition names handling. The final list is always a union of different rules, having users provide it explicitly is just not a great user experience.

If there's a better way and I've missed it, I would really appreciate a pointer as well.

**Comment by alexander-akait** [comment]
Hello, you can use such things like `conditionNames: ["my-name", "..."]` or `conditionNames: ["...", "my-name"]` to modify `conditionNames` and keep `default` variants, also you can set it on loader level or globally, also you can set it by type https://github.com/webpack/webpack/blob/main/lib/config/defaults.js#L1448, also you can see all default values

**Comment by richvdh** [comment]
It would be great if this sort of vital information could make it into the documentation at https://webpack.js.org/configuration/resolve/#resolveconditionnames.
