### ISSUE TITLE
NormalModuleReplacementPlugin  Replace error

### ISSUE THREAD

**Issue by allallisyou** [webpack/webpack#17699]
# Bug report

I want to use NormalModuleReplacementPlugin  to replace resources，I have a file foo.js，foo.js inclue WebGLBackground1.js（import XXX from WebGLBackground1.js），I want to use NormalModuleReplacementPlugin   to replace WebGLBackground1.js to other WebGLBackground2.js，but I found when the other WebGLBackground2.js also has a resources XXX.js，when WebGLBackground2.js init，XXX.js is undefined 

`        new webpack.NormalModuleReplacementPlugin(
            /\.\/webgl\/WebGLBackground1\.js/,
            '../../../../core/renderers/webgl/WebGLBackground2.js'
        ),`

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  5
Node.js version:16
Operating System:m
Additional tools:

**Comment by alexander-akait** [comment]
Please use `alias` for such purposes
