### ISSUE TITLE
Can't run sinon in node when webpacked

### ISSUE THREAD

**Issue by altano** [webpack/webpack#177]
webpack is converting this:

``` javascript
    var isNode = typeof module !== "undefined" && module.exports;
    var isAMD = typeof define === 'function' && typeof define.amd === 'object' && define.amd;

    if (isAMD) {
        define(function(){
            return sinon;
        });
    } else if (isNode) {
        ...
    }
```

into this:

``` javascript
    var isNode = typeof module !== "undefined" && module.exports;
    var isAMD = 'function' === 'function' && typeof (require(11)) === 'object' && (require(11));

    if (isAMD) {
        {var __WEBPACK_AMD_DEFINE_RESULT__ = (function(){
            return sinon;
        }(require, exports, module)); if(__WEBPACK_AMD_DEFINE_RESULT__ !== undefined) module.exports = __WEBPACK_AMD_DEFINE_RESULT__;};
    } else if (isNode) {
        ...
    }
```

and '11' refers to some webpack code which is definitely defined.

Is there a way to make webpack _not_ load a module in such a way that `define.amd` gets converted to something that is defined?

**Comment by dmatteo** [comment]
@jhnns +1 for that

Also a wise idea to tie it up to a specific commit, since can be unstable until release
```
    "sinon": "git://github.com/cjohansen/Sinon.JS#b672042043517b9f84e14ed0fb8265126168778a"
```

**Comment by jhnns** [comment]
Yup :+1:

**Comment by jacek-dargiel** [comment]
@jhnns @dmatteo Did you try to use sinon.fakeServer with the sinon-2.0 branch? It's not working for me (typeof sinon.fakeServer === undefined)

**Comment by jhnns** [comment]
Nope, haven't tested so far

**Comment by dmatteo** [comment]
Me neither sorry

**Comment by iam4x** [comment]
@jacek-dargiel @jhnns @dmatteo Any new info about `sinon.fakeServer`? Have you find a replacement?

**Comment by jacek-dargiel** [comment]
@iam4x To some extent - I've used [karma-sinon-chai](https://www.npmjs.com/package/karma-sinon-chai) with karma.

**Comment by iam4x** [comment]
Oh! I'm so dumb, forgot about the karma plugins :+1:

**Comment by tomatau** [comment]
Is there any progress going to be made moving sinon-2-0 into the master branch? Also I can see the browserify branch... what's the value of each of these? The browserify seems to be the most recently updated.

**Comment by altano** [comment]
@iam4x I use https://github.com/moll/node-mitm instead of sinon for dealing with XHR mocking.  It was super easy, not at all flaky, and works perfectly with webpack.

**Comment by iam4x** [comment]
Nice alternative @altano thank's

**Comment by srph** [comment]
Thanks @simple10 :+1:

**Comment by atondelier** [comment]
I encountered the same issue: sinon doesn't export itself correctly when webpacked.

_____________

### Solution without karma

I first ended up with this solution.

Add the following [imports loader](https://github.com/webpack/imports-loader) configuration in webpack configuration loaders array:
```JS
{
    test: /sinon\.js$/,
    loader: "imports?define=>false,require=>false"
}
```
Notice the addition of `require=>false` to @simple10 's solution.
Then sinon can be required using the built package:
```JS
const sinon = require('sinon/pkg/sinon');
```
You are free to add an alias from "sinon" to "sinon/pkg/sinon" in your test webpack configuration.

_____________

### Solution with karma

My case was browser-side, so packages like [karma-sinon-chai](https://github.com/kmees/karma-sinon-chai) which can make the browser load the built file of sinon are a solution. Sinon is not part of the test webpacked bundle file any more.

**Comment by trodrigues** [comment]
I landed here and after trying all the solutions and having none of them worked, I figured out that sinon 2 fixes this. It's currently still on npm as 2.0.0-pre, so just use that and it'll work fine. Also, @altano maybe worth editing your original comment with a note on that :)

**Comment by wwalser** [comment]
Thanks @trodrigues, just hours apart but you saved me loads of time.

**Comment by danielbush** [comment]
Has anyone tried to use sinon-as-promised with any of the above solutions?
If I'm using sinon 1, I have to import/require `sinon/pkg/sinon` in my code and use `loader: "imports?define=>false,require=>false"` in my webpack config (with `test: /sinon\.js/`).  But sinon-as-promised uses `require('sinon')` and falls over - if I reach into the code and change it to use sinon/pkg/sinon like my tests, it works.  I've tried changing the webpack test from `/sinon\.js/` to `/sinon.*\.js/` to see if I can get requiring 'sinon' to work instead of falling back to 'sinon/pkg/sinon', but didn't get anywhere with it and had to exclude things like sinon-chai etc.

If I switch to sinon 2.0.0-pre (and remove the import loader hack and use of sinon/pkg/sinon),  sinon-as-promised gets a little further but falls over for probably a compatibility reason, since it is peer-dependent with sinon 1.

Sad face.  Another js session lost to tooling.

**Comment by srph** [comment]
Add `resolve.alias`.

```
{
  resolve: {
    alias: { sinon: 'sinon/pkg/sinon' } // https://github.com/webpack/webpack/issues/177#issuecomment-185718237
  }
}
```

**Comment by kadamwhite** [comment]
We ran into this issue when using Enzyme to test react components, and what worked for us (to document for posterity) was a combination of above approaches:

```js
webpack: {
  resolve: {
    alias: {
      'sinon': 'sinon/pkg/sinon'
    }
  },
  module: {
    // don't run the sinon module through babel-loader
    noParse: [
      /sinon/
    ],
    // ...
```

**Comment by ericlau-solid** [comment]
I have to read the entire thread to figure out what I actually need to do. To summarize this for everyone, all the webpack.config changes required to get sinon to work:

```
resolve: {
		alias: { sinon: 'sinon/pkg/sinon' }
    },
	loaders: [{	test: /sinon.*\.js$/,	loader: "imports?define=>false,require=>false"	}],
	noParse: [/sinon/]
```

**Comment by alanclarke** [comment]
@ericlau-solid does that work for you when calling useFakeTimers?

**Comment by alanclarke** [comment]
nm, just use sinon@2.0.0-pre

**Comment by aaronjensen** [comment]
fwiw, we had better luck using:

```js
import 'expose?lolex!lolex'
import 'script!sinon/pkg/sinon'
```

(replace with require/webpack aliases/loader config/etc if you want)

**Comment by ZebraFlesh** [comment]
By far, the easiest solution is to use sinon@2.0.0-pre. I tested with sinon@2.0.0-pre.2 and sinon.useFakeXMLHttpRequest, worked great.

**Comment by renminghao** [comment]
@atondelier thanx

**Comment by Lexicality** [comment]
To prevent imports-loader clobbering `sinon-chai`, I had to change the loader config to
```javascript
{
    test: /sinon\/pkg\/sinon/,
    loader: "imports?define=>false,require=>false"
}
```
