### ISSUE TITLE
loader importModule api breaks webpack silently

### ISSUE THREAD

**Issue by jantimon** [webpack/webpack#17702]
# Bug report

**What is the current behavior?**

Using `this.importModule` on a `.js` file causes webpack to exit without output and without error.  
https://webpack.js.org/api/loaders/#thisimportmodule

## 1. Create a new project with the following 4 files:

loader.js
```js
module.exports = async function (source) {
  const config = await this.importModule(this.rootContext + "/config.js");
  result = source.replace("hello", config.text);
  return result;
};
```

config.js (the file loader by loader.js)
```js
export const text = "Greetings"
```

index.js (the file to be compiled)
```js
console.log("hello WORLD!")
```

webpack.config.js
```js
module.exports = {
    entry: "./index.js",
    module: {
        rules: [
        {
            test: /\.js$/,
            use: [
            {
                loader: require.resolve("./loader.js"),
            },
            ],
        },
        ],
    },
}
```

## Run webpack

`npx webpack`

## Result:

`webpack-cli` **exits without any error and without generating any file**

`webpack-dev-server` freezes in `<i> [webpack-dev-middleware] wait until bundle finished: /`

**What is the expected behavior?**

- webpack should show an error or create a bundled file
- importModule should provide an easy way to exclude the current loader

**Other relevant information:**

the problem seems to be an endless recursion:

 1. webpack loads `index.js`
 2. webpack calls `loader.js`
 3. the loader calls importModule on `config.js`
 4. import module calls `loader.js`
 5. goto step 3

<details>
  <summary>
<code>webpack --version</code>
</summary>

```
  System:
    OS: macOS 13.4
    CPU: (10) arm64 Apple M1 Max
    Memory: 140.73 MB / 64.00 GB
  Binaries:
    Node: 18.16.0
    Yarn: 1.22.19
    npm: 9.5.1 
  Browsers:
    Brave Browser: 116.1.57.64
    Chrome: 116.0.5845.187
    Chrome Canary: 119.0.6028.0
    Safari: 16.5
    Safari Technology Preview: 17.0
  Packages:
    webpack: ^5.88.2 => 5.88.2 
    webpack-cli: ^5.1.4 => 5.1.4 
    webpack-dev-server: ^4.15.1 => 4.15.1 
```

</details>

Please let me know if I can be of any help to understand, reproduce or fix this problem

**Comment by alexander-akait** [comment]
bu,p
