### ISSUE TITLE
execute examples\css\build.js unresponsive if i didn't install webpack

### ISSUE THREAD

**Issue by weidehai** [webpack/webpack#17705]
# Bug report

**What is the current behavior?**
execute examples\css\build.js unresponsive
**If the current behavior is a bug, please provide the steps to reproduce.**
cd .\examples\css
node .\build.js（do not install webpack）

**What is the expected behavior?**
should show install webpack tips in terminal

**Other relevant information:**
webpack version:  5.88.2
Node.js version:16.16.0
Operating System:window10
Additional tools:

**Comment by alexander-akait** [comment]
We have docs here https://github.com/webpack/webpack/tree/main/examples#building-an-example
