### ISSUE TITLE
`experiments.css` is not equivalent to the `mini-css-extract-plugin` it's meant to replace

### ISSUE THREAD

**Issue by fregante** [webpack/webpack#17700]
# Bug report

`mini-css-extract-plugin` can be used to extract every imported stylesheets into a single file, without _also_ loading it. This is the default behavior of the plugin.

This behavior is absent from `experiments.css`.

**What is the current behavior?**

Using `experiments.css = true`:

- `import "./style.css"` creates `main.css` and it will attempt to load the file
- `new  URL("./style.css", import.meta.url)` creates multiple `[hash].css` files and it won't attempt to load them

**If the current behavior is a bug, please provide the steps to reproduce.**

You can find the source and `dist` results in https://github.com/fregante/webpack-sandbox/tree/main/experiments.css

In short, the config is just `{experiments: {css: true}}`

**What is the expected behavior?**

It should match the behavior of the previous plugin, which just created a unified `main.css` file and _did not attempt to load it_. As a bonus, the resulting `main.js` is [completely empty](https://github.com/fregante/webpack-sandbox/tree/main/experiments.css/dist-import-mini-css-extract):

```js
module: {
	rules: [
		{
			test: /\.css$/,
			use: [
				MiniCssExtractPlugin.loader,
				'css-loader',
			],
		},
	]
},
plugins: [
	new MiniCssExtractPlugin(),
],
```

**Other relevant information:**
webpack version:  5.88.2
Node.js version: 18
Operating System: macOS
Additional tools:

_Originally reported in https://github.com/webpack/webpack/issues/14893#issuecomment-1704046657_

**Comment by alexander-akait** [comment]
The new logic will autoload stylsheets by default, because it will allow preload/prefetch/track loaded modules and etc, we will provide an option to disable such behaviour, so close in favor https://github.com/webpack/webpack/issues/14893 (I updated our roadmap)
