### ISSUE TITLE
Webpack 4.x will remove useful variable at some condition

### ISSUE THREAD

**Issue by simo-an** [webpack/webpack#17713]
# Bug report

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

install a umd format package, like `pack-sdk`.

This package content is

```ts

(function (global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined' ? factory(exports) :
    typeof define === 'function' && define.amd ? define(['exports'], factory) :
      (global = typeof globalThis !== 'undefined' ? globalThis : global || self, factory(global.AgoraRTCShared = {}));
})(this, (function (exports) {
  'use strict';
  function packSDK() {
    const sdk = () => console.warn("pack-sdk");
    try {
      const sdk = 1;
      console.warn("run: ", sdk);
    } finally {
      sdk();
    }
  }

  exports.packSDK = packSDK;

}));

```
`packSDK` can run normally at browser.

The create `index.js`

```ts
import { packSDK } from "pack-sdk";

packSDK();
```

webpack config is

```
const path = require('path');

module.exports = {
  entry: './index.js',
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'test.bundle.js',
  },
};
```

use `npx webpack build` to build it.

The output code will remove  `const sdk = () => console.warn("pack-sdk");` and causes the code cannot be ran.

![16959171945367](https://github.com/webpack/webpack/assets/38021707/96c09dba-5f0e-4478-9a8e-7c8fb924cd30)

please check the repo: https://github.com/simo-an/webpack-build-variable-lost

**What is the expected behavior?**

keep code `const sdk = () => console.warn("pack-sdk");`

when I use webpack 5.x , It's fine.

![16959170981373](https://github.com/webpack/webpack/assets/38021707/519222d1-f385-4de8-bacc-4844326c19e1)

**Other relevant information:**
webpack version:  4.47.0
Node.js version: v12.22.12
Operating System: win10
Additional tools: 

Thanks!

**Comment by simo-an** [comment]
when terser upgrade to 5.16.4 , it will `Make sure catch and finally aren't children of try in the AST` , see: https://github.com/terser/terser/blob/master/CHANGELOG.md#v5164

So the original code

```ts
function num() { return 1 }

function print() {
  let a = num();

  try {
    let b = 2;
    console.warn(b)
  } finally {
    console.warn(a)
  }
}
```

will be built to

```ts

function num() {
  return 1;
}
function print() {
  let n = num();
  try {
    let n = 2;
    console.warn(n);
  } finally {
    console.warn(n);
  }
}

```

terser@5.16.4 will use the same variable `n`

BTW, terser@5.16.3 output
```
function num() {
  return 1;
}
function print() {
  let n = num();
  try {
    let t = 2;
    console.warn(t);
  } finally {
    console.warn(n);
  }
}

```

-------------

So the code use `try catch finally` and built by terser@5.16.4+ will not work well with webpack@4.x


Waiting for the fix.

**Comment by csvan** [comment]
Webpack 4 is no longer supported

**Comment by simo-an** [comment]
> Webpack 4 is no longer supported

Oh No, this is a very serious issues. It will cause all the sdk or package built by rollup@5.16.3+ running abnormally with webpack 4.x.

It is do very necessary and important to fix it !!!

**Comment by csvan** [comment]
I am not familiar with Rollup, but if they have hard dependencies on legacy Webpack APIs you should open a ticket there and ask them to update it. Webpack 4 has been dead for over 2 years now.

**Comment by simo-an** [comment]
Although webpack 4.x is no longer maintained, but it is still used by lots of projects.
It is not the rollup's issue. 

as long as the code use the same var name in try { } and outside of it. Like

```js
function num() {
  return 1;
}
function print() {
  let n = num();
  try {
    let n = 2;
    console.warn(n);
  } finally {
    console.warn(n);
  }
}
```

webpack4.x will remove the first var `n`

**Comment by csvan** [comment]
These projects should not have EOL libraries as critical dependencies, open a ticket with them and ask them to upgrade to Webpack 5. Again, Webpack 4 has been dead for over 2 years, there is no excuse not to upgrade.

**Comment by alexander-akait** [comment]
Yeah, sorry, but webpack v4 is outdated and no longer supported
