### ISSUE TITLE
Make webpack compile resolve vars to disable dynamic require() function

### ISSUE THREAD

**Issue by alexsandro-xpt** [webpack/webpack#1771]
Sorry, I'm post my question here, I read the guidelines and then post it at stackoverflow in some days, but I haven't any answer.

http://stackoverflow.com/questions/34222378/can-a-loader-or-some-function-to-run-in-build-time-to-transform-string-var-in-a

Lets go:

I have this code bellow:

```
var m = app.getModuleMetadata(__filename);

module.exports = [m.rota, {
    url: '/costumer/phone/listar',
    templateProvider: function ($q) {
        return $q(function (resolve) {
            require.ensure([], function () {
                resolve(require('../../template/listar.html'));
            });
        });
    },
    controller: m.controller,
    resolve: {
        load: [
            '$q', '$ocLazyLoad', function ($q, $ocLazyLoad) {
                return $q(function (resolve) {
                    require.ensure([], function () {
                        var modulo = require('../controller/listar.js');
                        $ocLazyLoad.load({ name: modulo.name });
                        resolve(modulo.controller);
                    });
                });
            }
        ]
    }
}];
```

I disire simplify him some thing like:

```
var m = app.getModuleMetadata(__filename);

module.exports = [m.rota, {
    url: '/costumer/phone/listar',
    templateProvider: function ($q) {
        return $q(function (resolve) {
            require.ensure([], function () {
                resolve(require(m.templatePath));
            });
        });
    },
    controller: m.controller,
    resolve: {
        load: [
            '$q', '$ocLazyLoad', function ($q, $ocLazyLoad) {
                return $q(function (resolve) {
                    require.ensure([], function () {
                        var modulo = require(m.controllerPath);
                        $ocLazyLoad.load({ name: modulo.name });
                        resolve(modulo.controller);
                    });
                });
            }
        ]
    }
}];
```

By the way, webpack compile said:

`WARNING in ./modules/costumer/phone/js/rota/listar.js
Critical dependencies:
12:24-35 the request of a dependency is an expression
 @ ./modules/costumer/phone/js/rota/listar.js 12:24-35`

This is because require() function run in a other context, in webpack build context, not in runtime javascript web browser context.

So, require() function needs a static string to give us a expected result.

So, I think... if I create a node function to run before at same context of require() function to resolve string vars?

I know the `__filename` var is in node context like require() function.

I thing in a loader plugin, but I don't know if it work.

Someone else have some idea how can I run a function which run at same context of require() to `resolve(require(m.templatePath));` to give a require param `m.templatePath` a string value?

Thanks in advance.

**Comment by dpundir** [comment]
i am also looking for the solution where lazyload module name can be provided by some variable.

**Comment by sokra** [comment]
webpack is a static bundler. It must be a static analysable string passed to the require function.
