### ISSUE TITLE
Loading Web Worker from string in Webpack

### ISSUE THREAD

**Issue by directcuteo** [webpack/webpack#17712]
# Bug report

**What is the current behavior?**
On runtime, my app will create a `web worker` from some string code (not from file), using `Blob`, but because of the `webpack` bundling, there are unreferenced variables inside the `web worker's` code. The variables are declared by `webpack` at top of the bundle, but not included in the `web worker's` code itself.

**If the current behavior is a bug, please provide the steps to reproduce.**
This is the code of the `web worker` creation.

```
function inlineWorker(src) {
  let blob = new Blob([src], { type: 'application/javascript' });
  let url = URL.createObjectURL(blob);
  let worker = new Worker(url);
  URL.revokeObjectURL(url);
  return worker;
}
```

**What is the expected behavior?**
I saw projects where same code works. This code is from an external npm library.
I am using `Angular` with custom-webpack.config.js
I saw some react+next projects where same library is used and they work fine.

Not sure if the code is actually the problem. The important part is that there are some global variables referenced inside some functions after the build but they don't exist in the code of the working apps I saw. Let me show you:

## This is my error code:
(`_xc is not defined` - _xc is declared outside the web worker by the bundler and on runtime ofc it is not included in the web worker, therefore is `undefined`)
![image](https://github.com/webpack/webpack/assets/37619567/fd236908-054f-453d-8da2-51bbe91a10b3)

## And this is the same source code but from a react app
![image](https://github.com/webpack/webpack/assets/37619567/6b7d09f5-a9c7-41a3-9edd-b7df3e37b725)

The difference is big. Any help would be great! I don't know how to debug this issue. Thanks!

**Other relevant information:**
webpack version:  5.88.2
Node.js version: 18.12.1
Operating System: MacOS

**Comment by alexander-akait** [comment]
@directcuteo Sorry for delay, still valid?

**Comment by directcuteo** [comment]
Hello! Yes. Apparently this is not happening in a non angular, but Webpack based javascript project. So I would assume there is a lack of compatibility with Angular.

**Comment by alexander-akait** [comment]
@directcuteo Did you create the problem in angular cli?

**Comment by directcuteo** [comment]
Yes! The response is that because Angular doesn't support from the default configuration the top level await feature(you can add it manually), then this is not an issue on their side, but rather on this library side. 😐
