### ISSUE TITLE
Firefox console warns of Prototype Mutation code (Buffer related)

### ISSUE THREAD

**Issue by gregglind** [webpack/webpack#1772]
From a webpacked file:
```
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create
```
Seems to be related to:

```js
	if (Buffer.TYPED_ARRAY_SUPPORT) {
	  Buffer.prototype.__proto__ = Uint8Array.prototype
	  Buffer.__proto__ = Uint8Array
	}
```
Until #729 lands, is there a work around?

**Comment by gregglind** [comment]
(Sorry, I think this is Babel, not Webpack.  Closing.)

**Comment by lindell** [comment]
@gregglind Did you fix this problem? For me, babel does not generate any __proto__ but when running through webpack it does. Using __proto__ will break IE10 and 9 support for me so It's crucial that I get this solved. Can't find any other topics discussing this.

**Comment by gregglind** [comment]
@lindell my problem was NOT webpack, but a uuid library.  (`node-uuid` => `uuid`, in mozilla/self-repair-server#217 )

To solve:  check / comment out ALL libraries.  Even the unlikely ones!
