### ISSUE TITLE
When adding TerserPlugin() to `optimization.minimizer`, the result of minimized code is different to the default.

### ISSUE THREAD

**Issue by rudyhuynh** [webpack/webpack#17725]
# Bug report

**What is the current behavior?**
I just follow the step in here https://webpack.js.org/plugins/terser-webpack-plugin/#root to add TerserPlugin to webpack config. Then I see the output file is different compare to without the plugin:
```js
const TerserPlugin = require("terser-webpack-plugin");

module.exports = {
  optimization: {
    minimize: true,
    minimizer: [new TerserPlugin()],
  },
};
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Step 1: Clone this repo: https://github.com/rudyhuynh/terser-webpack-defaults.git
Step 2: `npm install` , then `npm run build`.

the webpack config:

```js

module.exports = {
  entry: "./src/main.ts",
  output: {
    filename: "[name].js",
    path: path.resolve(__dirname, "dist"),
    clean: true,
  },
  mode: "production",
  resolve: {
    extensions: [".ts", ".tsx", ".js", ".jsx"],
  },
  module: {
    rules: [
      {
        test: /\.[jt]sx?$/,
        loader: "esbuild-loader",
        options: {
          target: "es2022",
        },
      },
    ],
  },
  // optimization: {
  //   minimize: true,
  //   minimizer: [new TerserPlugin()],
  // },
};
```

dist/main.js: (re-format by prettier for readability)

```js
(() => {
  "use strict";
  !(function () {
    const t = document.getElementById("root");
    if (!t) throw new Error("root element not found!");
    t.textContent = `${2}^${5} = 32`;
  })();
})();
```

Step 3 : Add TerserPlugin to the webpack config, then `npm run build` again:

webpack config:
```js

module.exports = {
  entry: "./src/main.ts",
  output: {
    filename: "[name].js",
    path: path.resolve(__dirname, "dist"),
    clean: true,
  },
  mode: "production",
  resolve: {
    extensions: [".ts", ".tsx", ".js", ".jsx"],
  },
  module: {
    rules: [
      {
        test: /\.[jt]sx?$/,
        loader: "esbuild-loader",
        options: {
          target: "es2022",
        },
      },
    ],
  },
  optimization: {
    minimize: true,
    minimizer: [new TerserPlugin()],
   },
};
```

dist/main.js: (re-format by prettier for readability)

```js
(() => {
  "use strict";
  !(function () {
    const t = document.getElementById("root");
    if (!t) throw new Error("root element not found!");
    var o, e;
    t.textContent = `${(o = 2)}^${(e = 5)} = ${o ** e}`;
  })();
})();
```

**What is the expected behavior?**
Notice that before I add TerserPlugin, the code is compressed further than when I add TerserPlugin (`32` vs `o**e`)
My expectation is when adding TerserPlugin(), it should give the same default result.
Also, how can I setup TerserPlugin to give the same result as default?

**Other relevant information:**
webpack version:  5.88.2
Node.js version: 19.7.0
Operating System: MacOS Ventura

**Comment by ahabhgk** [comment]
The default TerserPlugin in webpack will add `compress.passes = 2`
https://github.com/webpack/webpack/blob/1f13ff9fe587e094df59d660b4611b1bd19aed4c/lib/config/defaults.js#L1339-L1345

so if you want the same result you should also add this to your TerserPlugin

**Comment by alexander-akait** [comment]
@ahabhgk thank you for the answer

Resolved
