### ISSUE TITLE
Webpack supporting SRI integrity checking?

### ISSUE THREAD

**Issue by curiousdev** [webpack/webpack#17726]
Apologies if I'm asking in the wrong place. Does Webpack support SRI integrity checking? 

### Example:

My module is hosted at `https://cdn.mycompany.com/module-v1.js`.

When `https://app.mycompany.com` is loading dynamic modules it needs to check the integrity of each module. When we deploy new version, we register a new integrity hash at app.mycompany.com.

**Comment by sowtame** [comment]
Hi, I also encountered this problem, I solved it here. https://github.com/waysact/webpack-subresource-integrity/pull/220
You can install the package with support MF https://www.npmjs.com/package/@sowtame/webpack-subresource-integrity

**Comment by alexander-akait** [comment]
Close in favor https://github.com/waysact/webpack-subresource-integrity/pull/220/
