### ISSUE TITLE
Force full page HMR from a plugin

### ISSUE THREAD

**Issue by kevlened** [webpack/webpack#1773]
I maintain the [CopyWebpackPlugin](https://github.com/kevlened/copy-webpack-plugin). The plugin makes it easier for me to copy files and directories that need to be directly copied over, not in chunks. It's commonly used to copy a root html file to the build directory ([example](https://github.com/rauschma/react-starter-project/blob/master/webpack.config.js)).

I'm facing an issue with HMR. When I change a js file, HMR works as expected and the proper chunks on the page are reloaded. However, when I change the html file, I have to manually refresh the browser to see the updates.

I saw on the [hot module replacement docs](https://webpack.github.io/docs/hot-module-replacement-with-webpack.html) where it says:

```
webpack/hot/dev-server reloads the entire page after the HMR update fails
```

I'd like to support the HMR feature, even on html, so my current idea is to hack it on:
1. Add a trigger file to watch for changes (`canary.txt`)
2. When I see there's an update to the html
3. Append a failing piece of code to the end of every chunk (`throw;`)
4. The page will refresh
5. After a brief wait (200ms or so)
6. Trigger another change by modifying `canary.txt`
7. Don't modify any chunks this last time

Is there a better way to do this?

Related issue:
kevlened/copy-webpack-plugin#1

**Comment by sunjay** [comment]
+1

**Comment by af7** [comment]
+1

**Comment by bebraw** [comment]
Hi,

Did you figure this out? I see some progress was made. Is there anything specific left?

**Comment by kevlened** [comment]
@bebraw I never took the time to build this out
