### ISSUE TITLE
https://github.com/EricSchles/federalist/commit/6ad14fec13826778d20a2046bdf2e41b36bec660

### ISSUE THREAD

**Issue by Valecia2023** [webpack/webpack#17745]
# Bug report

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  
Node.js version:
Operating System:
Additional tools:

**Comment by Valecia2023** [comment]
https://github.com/EricSchles/federalist/commit/6ad14fec13826778d20a2046bdf2e41b36bec660

**Comment by Valecia2023** [comment]
k8s-gateway/kustomization.yaml

**Comment by csvan** [comment]
???
