### ISSUE TITLE
Finish Modules steps tooks long time

### ISSUE THREAD

**Issue by JiangWeixian** [webpack/webpack#17752]
Currently, I develop a huge `react` project with

- `webpack@5.85.1`. 
-  Apple M1 Max

When edit some files to trigger HMR, in progress plugin output, `finishModules` step tooks long time. So I add https://github.com/jantimon/cpuprofile-webpack-plugin to find out which step cost a lot, here is cpu profile screenshot:

![image](https://github.com/webpack/webpack/assets/6839576/d99132da-b680-4fca-b5ff-1d267f48c494)

![image](https://github.com/webpack/webpack/assets/6839576/1a67eba8-8943-41bc-8a67-b1a2b57cabc9)

Any ideas to optimize it? I already tried:

1. https://github.com/webpack/webpack/issues/8557 replace dynamic `import` to `promise.resolve`
2. disable cache and progress in dev mode

It does't help. But when I comments `sortItemsWithChunkIds` inside `Compliation.js`, e.g.

```
// this.sortItemsWithChunkIds();
```

It make finish module step from `7s` to `2s`.

_Originally posted by @JiangWeixian in https://github.com/webpack/webpack/discussions/17751_

**Comment by alexander-akait** [comment]
@JiangWeixian Maybe you have a lot of modules... We need more information to help you...

**Comment by JiangWeixian** [comment]
@alexander-akait  yep..

It's a huge project, server and client compiler will each compile 25k+ modules. I took some methods (from `next.js` and other repos) to optimize it.

1. only compile used route
2. shake unused modules earlier(in swc transfrom stage), e.g. remove `no_ssr` & `useEffect & useLayoutEffect` code in server compiler; use swc optimizier & minify options in swc-loader
3. optimize barrel packages

After above methods, server and client compiler will each compile 10k modules...(in MAC M1 Pro, from 240s startup to 110s) It looks like no more methods to make it less:(. 

I will try `rspack` to make compile fast in next few months
