### ISSUE TITLE
satisfy version miscomputed tilde ranges

### ISSUE THREAD

**Issue by 2heal1** [webpack/webpack#17756]
# Bug report

The webpack inner semver function computed result is different from the npm package semver , and the webpack inner function result seems not right.

**What is the current behavior?**

Running the function satisfy from [semver]( https://github.com/webpack/webpack/blob/main/lib/util/semver.js)  and [parseRange](https://github.com/webpack/webpack/blob/main/lib/util/semver.js#L91) results in a possible bug. Specifically:

```js
satisfy(parseRange('~1'), '1.2.3') === false
```

**What is the expected behavior?**
```js
satisfy(parseRange('~1'), '1.2.3') === true
```

**Other relevant information:**
the result is not the same with [semver](https://www.npmjs.com/package/semver)
```js
const semver = require('semver');
semver.satisfies('1.2.3','~1') === true
```

**Comment by 2heal1** [comment]
I added a reproduction repository

https://github.com/2heal1/webpack-demo

Running test by the follow steps: 

1. instal deps

```js
npm i
```

2. run test

```js
npm run test-special-tilde
```

```js
npm run test-special-x-range
```

**Comment by alexander-akait** [comment]
@2heal1 Sounds like a bug, do you want to send a PR?

**Comment by rohannsahh** [comment]
@alexander-akait hey is the still open ? can i try it ?

**Comment by alexander-akait** [comment]
Yes, feel free to send a PR
