### ISSUE TITLE
Enums are tree-shaken when they shouldn't be

### ISSUE THREAD

**Issue by MeddahAbdellah** [webpack/webpack#17750]
# Bug report

**What is the current behavior?**
I am trying to use a package I deployed, which contains enums, but they're behaving in a way I did not expect.

I have a package in node_module that exports an enum like this:
```javascript
(function (MyEnum) {
    MyEnum["A"] = "a";
    MyEnum["B"] = "b";
    MyEnum["C"] = "c";
})(MyEnum || (exports.MyEnum = MyEnum = {}));
```
I use it in my code like this:
```typescript
import {MyEnum} from '@my-package';

const MyEnumTitlesMap = new Map<MyEnum, string>([
  [MyEnum.A, 'title for A'],
  [MyEnum.B, 'title for B'],
  [MyEnum.C, 'title for C'],
]);

@Component({
  selector: 'app-test',
  templateUrl: './test.component.html',
  styleUrls: ['./test.component.scss'],
})
export class TestComponent {
  ...
  myMethod() {
    const title = MyEnumTitlesMap.get(MyEnum.A)
  }
}
```
Typescript recognizes the enum `MyEnum` but at runtime `MyEnum` is undefined. 

When I look a the generated bundle using @angular-devkit/build-angular:browser  as builder,  with `buildOptimized: true` the genrated bundle has 
```javascript
var MyEnum = /*#__PURE__*/(() => {
  MyEnum = MyEnum || {};
  MyEnum["A"] = "a";
  MyEnum["B"] = "b";
  MyEnum["C"] = "d";
  return MyEnum;
})();
```
MyEnum is no longer exported, that's why at runtime it's undefined.

**If the current behavior is a bug, please provide the steps to reproduce.**
I have spent 4 days trying to reproduce in a simple project but I couldn't.
What I have is a commonJs package on npm registry which I install using yarn on my angular 16 project, the packag exports an enum which I can only use if It's inside the component for example a public property of the component and not in a const outside the component, in which case it gets tree shaken.

**What is the expected behavior?**

Being able to use the enum, and it wouldn't be tree-shaken.

**Other relevant information:**
webpack version:  5.75.0
Node.js version: 16.20.0
Operating System: MacOs Montrey 12.5
Yarn: 1.22.19
Angular: 16.0.0

**Comment by alexander-akait** [comment]
Please open an issue in `angular-devkit`, thank you
