### ISSUE TITLE
Does Webpack import all files in a library into bundles(concluded from source map files)?

### ISSUE THREAD

**Issue by iamusenix** [webpack/webpack#1775]
I was using 'react-bootstrap' in my project and using webpack to build bundles and chunks. However, I found my bundles and chunks were getting bigger and bigger... So I build out the source map files and found these records in.

'webpack:///./~/react-bootstrap/lib/AffixMixin.js',
  'webpack:///./~/react-bootstrap/lib/ButtonGroup.js',
  'webpack:///./~/react-bootstrap/lib/ButtonInput.js',
  'webpack:///./~/react-bootstrap/lib/Col.js',
  'webpack:///./~/react-bootstrap/lib/DropdownToggle.js',
  'webpack:///./~/react-bootstrap/lib/FormControls/index.js',
  'webpack:///./~/react-bootstrap/lib/FormGroup.js',
  'webpack:///./~/react-bootstrap/lib/Grid.js',
  'webpack:///./~/react-bootstrap/lib/Interpolate.js',
  'webpack:///./~/react-bootstrap/lib/ListGroupItem.js',
  'webpack:///./~/react-bootstrap/lib/ModalBody.js',
  'webpack:///./~/react-bootstrap/lib/ModalFooter.js',
  'webpack:///./~/react-bootstrap/lib/ModalHeader.js',
  'webpack:///./~/react-bootstrap/lib/ModalTitle.js',
  'webpack:///./~/react-bootstrap/lib/Nav.js',
  'webpack:///./~/react-bootstrap/lib/NavBrand.js',
  'webpack:///./~/react-bootstrap/lib/NavItem.js',
  'webpack:///./~/react-bootstrap/lib/Overlay.js',
  'webpack:///./~/react-bootstrap/lib/PanelGroup.js',
  'webpack:///./~/react-bootstrap/lib/utils/EventListener.js',
  'webpack:///./~/react-bootstrap/lib/utils/TransitionEvents.js',
  'webpack:///./~/react-bootstrap/lib/utils/domUtils.js',
  'webpack:///./~/react-bootstrap/~/babel-runtime/helpers/interop-require-wildcard.js',

but I didn't use all this components. For example, I didn't use 'AffixMixin.js' at all but It seems it's included in my bundles.
In codes, I just import components like this:

import {Modal} from 'react-bootstrap'

Does anybody can help? How to just import part of the library into the built bundles?thanks.

**Comment by bebraw** [comment]
Can you point to the bits you need directly? Rough example:

```javascript
import ModalBody from 'react-bootstrap/lib/ModalBody';
```

You would do something similar for each part you need.

Webpack 1 doesn't do any kind of tree shaking, but as far as I understand Webpack 2 might perform better on that front.

**Comment by iamusenix** [comment]
@bebraw Thanks for your comments. 
What I want to know is whether Webpack can pick up the files really necessary when I import components from a library(react-bootstrap for example). It turns out I have to import components individually like the codes in your comments. Otherwise, webpack will include all components in 'react-bootstrap' which make the chunk to size of 450KB even I just import a Button. 
I will try Webpack 2 to see whether there is a better solution. 
Thank you again.

**Comment by bebraw** [comment]
@iamusenix See [this post](http://www.2ality.com/2015/12/webpack-tree-shaking.html) for a more advanced approach. Getting "tree shaking" to work requires webpack 2 and some Babel setup, but maybe that would work for you.

**Comment by iamusenix** [comment]
@bebraw Very interesting and helpful post. Thanks a lot.
