### ISSUE TITLE
TLS 1.2 Restriction in Node 18 Affects Proxy Configuration for HTTPS Backends

### ISSUE THREAD

**Issue by Neizan93** [webpack/webpack#17765]
# Bug report

**What is the current behavior?**

When utilizing Angular 15 and Node 18 in a local development environment, the proxy configuration in webpack fails to function as expected when targeting HTTPS backends using TLS 1.2. This issue arises from the TLS 1.2 restriction imposed by OpenSSL 3, which is used by Node 18. The restriction prevents connections to remote endpoints using TLS versions lower than 1.3 due to security concerns.

**If the current behavior is a bug, please provide the steps to reproduce.**

- Set up a local development environment with Angular 15 and Node 18.
- Configure the proxy settings in webpack to point to a backend using HTTPS with TLS 1.2.
- Attempt to access the backend via the proxy from the local development environment.
- Observe the failure in proxy configuration, preventing access to the backend due to TLS 1.2 restriction.

```
// Example of webpack proxy configuration
module.exports = {
  //...
  devServer: {
    proxy: {
      '/api': {
        target: 'https://your-backend.com',
        secure: false
      }
    }
  }
};

```
**What is the expected behavior?**

The proxy configuration should function correctly, allowing the local development environment to communicate with the backend using TLS 1.2 without any issues. This functionality is crucial for a smooth development, testing, and debugging process, especially in environments where upgrading to TLS 1.3 is not immediately feasible.

**Other relevant information:**
webpack version: 5.89.0
Node.js version: 18.18.2
Operating System: Windows and Ubuntu (Linux)
Additional tools: Angular CLI

**Comment by humblepie** [comment]
I run into the same issue with just trying to proxy normal http requests to localhost.  So I don't think this issue is specific to https.  If I downgrade to node 16.20.1 then the proxying works again.

Angular 16
Node.js: 17.9.1 & 18.8.2 (both fail)
webpack version: 5.89.0
OS: macOS

proxy.conf.js:
`{
  "/api": {
    "target": "http://localhost:3003",
    "secure": false,
    "logLevel": "warn"
  }
}`

**Comment by Neizan93** [comment]
> Not sure if this is the same issue. But I ran into ECONNREFUSED error trying to proxy normal http requests to localhost. If I downgrade to node 16.20.1 then the proxying works again with localhost.
> 
> I did find out that starting with [node 17+, node prefers IPV6 over IPV4.](https://github.com/chimurai/http-proxy-middleware#nodejs-17-econnrefused-issue-with-ipv6-and-localhost-705) So DNS resolution for localhost isn't guaranteed to be 127.0.0.1, it could be ::1. When I used the ip address proxying worked again using node 17+.

It is not the same issue. Our "target" is not a localhost, is a remote backend with https (TLS 1.2).
Using a backend with TLS 1.3 works well.

**Comment by alexander-akait** [comment]
Sorry for delat, please open an issue in `Angular CLI` repo, I don't think there is a problem with webpack itself, thank you and feel free to feedback
