### ISSUE TITLE
build js expression literal `/=/` error

### ISSUE THREAD

**Issue by gweesin** [webpack/webpack#17769]
# Bug report

**What is the current behavior?**

run `webpack --mode production` error when compile `/=/` literal.

This is the minimal reproduction env:

https://github.com/gweesin/webpack-js-expression-literal-error

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

It should be the same as compile `new RegExp('=')`.

**Other relevant information:**
webpack version:  5.89.0
Node.js version:16.20.0
Operating System: win11
Additional tools:

**Comment by dear-lizhihua** [comment]
update acorn@8.11.2
https://github.com/acornjs/acorn/commits/master
https://github.com/acornjs/acorn/commit/7cd08bfd978bb688361b9e425eb46693da5b624c
https://github.com/acornjs/acorn/commit/9cbe3f6470f7ce7986fb67b211047e4ead32046e

**Comment by gweesin** [comment]
LGTM! Thank you for your reply.

**Comment by gweesin** [comment]
LGTM! Thank you for your reply.
