### ISSUE TITLE
trying to consume a pure esm package in normal code

### ISSUE THREAD

**Issue by sibelius** [webpack/webpack#17772]
# Bug report

**What is the current behavior?**

When I try to import `wrap-ansi` (https://github.com/chalk/wrap-ansi), it throws this error:

```
Error [ERR_REQUIRE_ESM]: require() of ES Module
```

My project uses commonjs and webpack, we can't easily change our monorepo to esm.

**If the current behavior is a bug, please provide the steps to reproduce.**

Just import a pure ESM package in a commonjs project using webpack

**What is the expected behavior?**

It should work

How can I make this work? should I transpile the pure ESM package?

What is the recommendation for this use case?

**Other relevant information:**
webpack version:  5.89.0
Node.js version: 20.0.0
Operating System: mac os x
Additional tools:

**Comment by alexander-akait** [comment]
Sorry for delay, how you import this package and which version?

**Comment by sibelius** [comment]
latest version: v9.0.0

I import like this `import wrapAnsi from 'wrap-ansi';`

should I make webpack babel-loader/swc-loader to transpile this packages?

**Comment by alexander-akait** [comment]
@sibelius Sorry, I can't reproduce the problem, can you provide reproducible test repo?

**Comment by alexander-akait** [comment]
@sibelius friendly ping

**Comment by Thiago-Mota-Santos** [comment]
This is the error

![image](https://github.com/webpack/webpack/assets/75326612/02f4026b-d7c0-46e8-b4bc-2dda52da7fd9)

repo: https://github.com/Thiago-Mota-Santos/webpack-concepts

**Comment by alexander-akait** [comment]
There are no problems with webpack itself, you ask typescript to use `require`, but try to load ESM module, please use:
```
{
    "compilerOptions": {
        "noImplicitAny": true,
        "target": "ES5",
        "moduleResolution": "bundler",
        "module": "esnext",
        "allowSyntheticDefaultImports": true
    }
}
```

and ts-loader will generate `import ... from ...`.

Yeah, if you have commonjs project, you can't use `import wrapAnsi from 'wrap-ansi';`, you need to use dynamic `import("wrap-ansi")`, we can't load ESM module using `require()`. There's nothing we can do with it. 

Feel free to feedback
