### ISSUE TITLE
Issue Closed and Marked as "Ready To Merge", but these states are invalid.

### ISSUE THREAD

**Issue by stevematney** [webpack/webpack#17785]
Hello! #16544 was closed and marked as "Ready To Merge", but I don't think any work was done toward resolving it. I can at least be sure that no work was done that referenced the issue itself.

In the discussion on the issue, it was acknowledged as a bug (at least that's how I understood [this comment](https://github.com/webpack/webpack/issues/16544#issuecomment-1516727562)), but one which may be difficult to resolve.

We have done a lot of work to get around the issue, but it still persists, and still causes us some problems occasionally. I'm making this new issue because I would hate for the discussion on #16544 to be lost and for the original concern never to be addressed.

**Comment by alexander-akait** [comment]
Yeah, thank you for the report, we will fix it soon
