### ISSUE TITLE
TypeError: __webpack_require__(...) is not a function

### ISSUE THREAD

**Issue by Dhiren321** [webpack/webpack#17792]
An unhandled exception occurred while processing the request.
NodeInvocationException: Prerendering failed because of error: TypeError: __webpack_require__(...) is not a function
at ./node_modules/react/index.js (C:\Project3\VSENode20Upgrade\VSE_AppDashBoard\ClientApp\dist\main-server.js:8227:95)
at __webpack_require__ (C:\Project3\VSENode20Upgrade\VSE_AppDashBoard\ClientApp\dist\main-server.js:8583:42)
at eval (webpack-internal:///./ClientApp/boot-server.tsx:5:63)
at ./ClientApp/boot-server.tsx (C:\Project3\VSENode20Upgrade\VSE_AppDashBoard\ClientApp\dist\main-server.js:5147:1)
at __webpack_require__ (C:\Project3\VSENode20Upgrade\VSE_AppDashBoard\ClientApp\dist\main-server.js:8583:42)
at C:\Project3\VSENode20Upgrade\VSE_AppDashBoard\ClientApp\dist\main-server.js:8640:37
at Object.<anonymous> (C:\Project3\VSENode20Upgrade\VSE_AppDashBoard\ClientApp\dist\main-server.js:8645:12)
at Module._compile (node:internal/modules/cjs/loader:1241:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
at Module.load (node:internal/modules/cjs/loader:1091:32)
Current directory is: C:\Project3\VSENode20Upgrade\VSE_AppDashBoard
Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance.InvokeExportAsync<T>(NodeInvocationInfo invocationInfo, CancellationToken cancellationToken)

Stack Query Cookies Headers Routing
NodeInvocationException: Prerendering failed because of error: TypeError: __webpack_require__(...) is not a function at ./node_modules/react/index.js (C:\Project3\VSENode20Upgrade\VSE_AppDashBoard\ClientApp\dist\main-server.js:8227:95) at __webpack_require__ (C:\Project3\VSENode20Upgrade\VSE_AppDashBoard\ClientApp\dist\main-server.js:8583:42) at eval (webpack-internal:///./ClientApp/boot-server.tsx:5:63) at ./ClientApp/boot-server.tsx (C:\Project3\VSENode20Upgrade\VSE_AppDashBoard\ClientApp\dist\main-server.js:5147:1) at __webpack_require__ (C:\Project3\VSENode20Upgrade\VSE_AppDashBoard\ClientApp\dist\main-server.js:8583:42) at C:\Project3\VSENode20Upgrade\VSE_AppDashBoard\ClientApp\dist\main-server.js:8640:37 at Object.<anonymous> (C:\Project3\VSENode20Upgrade\VSE_AppDashBoard\ClientApp\dist\main-server.js:8645:12) at Module._compile (node:internal/modules/cjs/loader:1241:14) at Module._extensions..js (node:internal/modules/cjs/loader:1295:10) at Module.load (node:internal/modules/cjs/loader:1091:32) Current directory is: C:\Project3\VSENode20Upgrade\VSE_AppDashBoard
Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance.InvokeExportAsync<T>(NodeInvocationInfo invocationInfo, CancellationToken cancellationToken)
Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance.InvokeExportAsync<T>(CancellationToken cancellationToken, string moduleName, string exportNameOrNull, object[] args)
Microsoft.AspNetCore.NodeServices.NodeServicesImpl.InvokeExportWithPossibleRetryAsync<T>(string moduleName, string exportedFunctionName, object[] args, bool allowRetry, CancellationToken cancellationToken)
Microsoft.AspNetCore.NodeServices.NodeServicesImpl.InvokeExportWithPossibleRetryAsync<T>(string moduleName, string exportedFunctionName, object[] args, bool allowRetry, CancellationToken cancellationToken)
AspNetCoreGeneratedDocument.Views_Main_Index.ExecuteAsync() in Index.cshtml
+
    var prerenderResult = await prerenderer.RenderToString("ClientApp/dist/main-server", customDataParameter: Model);
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, bool invokeViewStarts)
Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, string contentType, Nullable<int> statusCode)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, string contentType, Nullable<int> statusCode)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, string contentType, Nullable<int> statusCode)
Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0<TFilter, TFilterAsync>(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext<TFilter, TFilterAsync>(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultFilters>g__Awaited|28_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.SpaServices.Webpack.ConditionalProxyMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

package.json
{
  "name": "webapp",
  "private": true,
  "version": "0.1.0",
  "devDependencies": {
    "@babel/core": "7.7.2",
    "@hot-loader/react-dom": "16.11.0",
    "@types/history": "4.7.3",
    "@types/react": "16.9.11",
    "@types/react-dom": "16.9.4",
    "@types/react-helmet": "5.0.14",
    "@types/react-redux": "7.1.5",
    "@types/react-router": "5.1.3",
    "@types/react-router-dom": "5.1.2",
    "@types/webpack": "4.41.0",
    "@types/webpack-env": "1.14.1",
    "aspnet-prerendering": "3.0.1",
    "aspnet-webpack-react": "4.0.0",
    "babel-loader": "8.0.6",
    "babel-plugin-import": "^1.13.0",
    "case-sensitive-paths-webpack-plugin": "^2.4.0",
    "css-loader": "3.2.0",
    "cssnano": "4.1.10",
    "file-loader": "4.2.0",
    "fork-ts-checker-webpack-plugin": "3.1.0",
    "ignore-loader": "0.1.2",
    "mini-css-extract-plugin": "0.8.0",
    "node-noop": "1.0.0",
    "optimize-css-assets-webpack-plugin": "5.0.3",
    "react-dev-utils": "9.0.1",
    "react-dropzone": "^14.2.2",
    "react-hot-loader": "4.12.18",
    "rimraf": "3.0.0",
    "sass": "^1.64.1",
    "sass-loader": "^10.4.1",
    "style-loader": "1.0.0",
    "terser-webpack-plugin": "1.3.0",
    "ts-loader": "6.2.1",
    "ts-nameof": "4.2.0",
    "ts-nameof-loader": "1.0.2",
    "typescript": "^4.9.5",
    "url-loader": "2.2.0",
    "webpack": "^5.89.0",
    "webpack-cli": "^5.1.4",
    "webpack-dev-middleware": "^3.7.2",
    "webpack-hot-middleware": "^2.25.4",
    "webpack-merge": "^5.10.0"
  },
  "dependencies": {
    "@babel/polyfill": "7.7.0",
    "@material-ui/core": "^4.11.0",
    "@reduxjs/toolkit": "1.1.0",
    "aspnet-webpack": "3.0.0",
    "aspnet-webpack-react": "4.0.0",
    "awesome-debounce-promise": "2.1.0",
    "axios": "0.21.1",
    "bootstrap": "^4.5.0",
    "chokidar": "^3.5.3",
    "connected-react-router": "6.6.0",
    "core-js": "^3.32.1",
    "custom-event-polyfill": "1.0.7",
    "debug": "^4.3.4",
    "domain-browser": "^4.23.0",
    "domain-wait": "^1.3.0",
    "event-source-polyfill": "1.0.9",
    "formik": "2.0.4",
    "history": "4.10.1",
    "ini": "^4.1.1",
    "mkdirp": "^3.0.1",
    "nval-tippy": "^1.0.40",
    "query-string": "^5.1.1",
    "react": "16.12.0",
    "react-app-polyfill": "^1.0.6",
    "react-bootstrap": "1.0.0-beta.16",
    "react-dom": "16.12.0",
    "react-helmet": "6.0.0-beta",
    "react-redux": "7.1.3",
    "react-router": "5.1.2",
    "react-router-bootstrap": "0.25.0",
    "react-router-dom": "5.1.2",
    "react-select": "^3.1.0",
    "react-toastify": "5.4.1",
    "redux": "4.0.4",
    "redux-thunk": "2.3.0",
    "uuid": "^9.0.0"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all",
      "ie 11"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version",
      "ie 11"
    ]
  },
  "scripts": {
    "build:dev": "node build.before.js --mode=development && node ./node_modules/webpack/bin/webpack.js --config webpack.config.vendor.js && node ./node_modules/webpack/bin/webpack.js --config webpack.config.js",
    "build:prod": "node build.before.js --mode=production && node ./node_modules/webpack/bin/webpack.js --config webpack.config.vendor.js --env.prod=true && node ./node_modules/webpack/bin/webpack.js --config webpack.config.js --env.prod=true"
  }
}

web.config
const path = require('path');
const webpack = require('webpack');
const { merge } = require('webpack-merge');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin');
const CaseSensitivePathsPlugin = require('case-sensitive-paths-webpack-plugin');
const WatchMissingNodeModulesPlugin = require('react-dev-utils/WatchMissingNodeModulesPlugin');
const CssNanoPlugin = require("cssnano");
const TerserWebpackPlugin = require("terser-webpack-plugin");
const OptimizeCSSAssetsPlugin = require("optimize-css-assets-webpack-plugin");

module.exports = (env) => {
    const isDevBuild = !(env && env.prod);

    // Configuration in common to both client-side and server-side bundles.
    const sharedConfig = () => {

        var mode = isDevBuild ? "development" : "production";

        console.log('\x1b[36m%s\x1b[0m', "=== Webpack compilation mode: " + mode + " ===");

        var config = {
            mode,
            optimization: {
               
                moduleIds: 'named',

                minimize: !isDevBuild,
                usedExports: isDevBuild,
                minimizer: !isDevBuild ? [
                    // Production.
                    new TerserWebpackPlugin({
                        terserOptions: {
                            output: {
                                comments: false,
                            },
                        },
                    }),
                    new OptimizeCSSAssetsPlugin({
                        cssProcessor: CssNanoPlugin,
                        cssProcessorPluginOptions: {
                            preset: ["default", { discardComments: { removeAll: true } }]
                        }
                    })
                ] : [
                    //developement
                        new TerserWebpackPlugin({
                            terserOptions: {
                                output: {
                                    comments: false,
                                },
                            },
                        }),
                        new OptimizeCSSAssetsPlugin({
                            cssProcessor: CssNanoPlugin,
                            cssProcessorPluginOptions: {
                                preset: ["default", { discardComments: { removeAll: true } }]
                            }
                        })
                    ]
            },
            stats: { modules: false },
            resolve: {
                fallback: {
                    "domain": false,
                    dgram: false,
                    fs: false,
                    net: false,
                    tls: false,
                    child_process: false },
                extensions: ['.js', '.jsx', '.ts', '.tsx', '.jpg','.ico'],
                alias: {
                    "@Layouts": path.resolve(__dirname, "ClientApp/layouts/"),
                    "@Components": path.resolve(__dirname, "ClientApp/components/"),
                    "@Images": path.resolve(__dirname, "ClientApp/images/"),
                    "@Store": path.resolve(__dirname, "ClientApp/store/"),
                    "@Utils": path.resolve(__dirname, "ClientApp/utils"),
                    "@Styles": path.resolve(__dirname, 'ClientApp/styles/'),
                    "@Pages": path.resolve(__dirname, 'ClientApp/pages/'),
                    "@Services": path.resolve(__dirname, 'ClientApp/services/'),
                    "@Models": path.resolve(__dirname, 'ClientApp/models/'),
                    "@Core": path.resolve(__dirname, 'ClientApp/core/')
                }
            },
            output: {
                filename: '[name].js',
                publicPath: 'dist/', // Webpack dev middleware, if enabled, handles requests for this URL prefix.
            },
            module: {
                rules: [
                    {
                        test: /\.tsx?$/, include: /ClientApp/,
                        use: [
                            {
                                loader: 'babel-loader',
                                options: {
                                    compact: true,
                                    plugins: [
                                    ]
                                },                    
                            },
                            {
                                loader: 'ts-loader',
                                options: {
                                    // Disable type checker - we will use it in fork plugin.
                                    transpileOnly: true
                                }
                            },
                            'ts-nameof-loader'
                        ]
                    },
                    {
                        test: /\.(gif|png|jpe?g|svg)$/i,
                        use: ['file-loader']
                    }
                ]
            },
            plugins: [
                new ForkTsCheckerWebpackPlugin(),
                // Moment.js is an extremely popular library that bundles large locale files
                // by default due to how Webpack interprets its code. This is a practical
                // solution that requires the user to opt into importing specific locales.
                // https://github.com/jmblog/how-to-optimize-momentjs-with-webpack
                // You can remove this if you don't use Moment.js:
                new webpack.IgnorePlugin({ resourceRegExp: /\.\/native/, contextRegExp: /\/pg\// })
            ].concat(isDevBuild ? [
                // Development.

                // Add module names to factory functions so they appear in browser profiler.
                //new webpack.NamedModulesPlugin(),
                // Watcher doesn't work well if you mistype casing in a path so we use
                // a plugin that prints an error when you attempt to do this.
                // See https://github.com/facebookincubator/create-react-app/issues/240
                new CaseSensitivePathsPlugin(),
                // If you require a missing module and then `npm install` it, you still have
                // to restart the development server for Webpack to discover it. This plugin
                // makes the discovery automatic so you don't have to restart.
                // See https://github.com/facebookincubator/create-react-app/issues/186
                new WatchMissingNodeModulesPlugin(path.resolve(__dirname, '..', 'node_modules'))
            ] : [
                // Production.
            ])
        };

        if (isDevBuild) {

            // Change config for development build.

            config = {
                ...config,
                // Turn off performance hints during development because we don't do any
                // splitting or minification in interest of speed. These warnings become
                // cumbersome.
                performance: {
                    hints: false,
                },
                //IE11 isn't a fan of the eval() code that gets inserted by webpack.
                //Using webpackConfig.devtool = 'none' (or one of the alternative values) should fix it
                devtool: 'eval-source-map'
                //devtool: 'none'
            };

            config.resolve.alias = {
                ...config.resolve.alias,
                'react-dom': '@hot-loader/react-dom'
            };
        }

        return config;
    };

    // Configuration for client-side bundle suitable for running in browsers.
    const clientBundleOutputDir = './wwwroot/dist';
    const clientBundleConfig = merge(sharedConfig(), {
        entry: { 'main-client': './ClientApp/boot-client.tsx' },
        module: {
            rules: [
                { test: /\.css$/, use: isDevBuild ? ['style-loader', 'css-loader'] : [MiniCssExtractPlugin.loader, 'css-loader'] },
                { test: /\.(scss|sass)$/, use: isDevBuild ? ['style-loader', 'css-loader', 'sass-loader'] : [MiniCssExtractPlugin.loader, 'css-loader', 'sass-loader'] }
            ]
        },
        output: { path: path.join(__dirname, clientBundleOutputDir) },
        // Some libraries import Node modules but don't use them in the browser.
        // Tell Webpack to provide empty mocks for them so importing them works.
        //node: {
        //    dgram: 'empty',
        //    fs: 'empty',
        //    net: 'empty',
        //    tls: 'empty',
        //    child_process: 'empty',
        //},
        plugins: [
            new webpack.DllReferencePlugin({
                context: __dirname,
                manifest: require('./wwwroot/dist/vendor-manifest.json')
            })
        ].concat(isDevBuild ? [
            // Development.
            new webpack.SourceMapDevToolPlugin({
                filename: '[file].map', // Remove this line if you prefer inline source maps.
                moduleFilenameTemplate: path.relative(clientBundleOutputDir, '[resourcePath]') // Point sourcemap entries to the original file locations on disk
            })
        ] : [
            // Production.
            new MiniCssExtractPlugin({
                filename: "site.css"
            })
        ])
    });

    // Configuration for server-side (prerendering) bundle suitable for running in Node.
    const serverBundleConfig = merge(sharedConfig(), {
        module: {
            rules: [
                { test: /\.(scss|sass)$/, use: "ignore-loader" }
            ]
        },
       
        resolve: {
            fallback: {
                "domain": false,
                dgram: false,
                fs: false,
                net: false,
                tls: false,
                child_process: false }, mainFields: ['main'] },
        entry: { 'main-server': './ClientApp/boot-server.tsx' },
        plugins: [
            new webpack.DllReferencePlugin({
                context: __dirname,
                manifest: require('./ClientApp/dist/vendor-manifest.json'),
                sourceType: 'commonjs2',
                name: './vendor'
            })
        ],
        output: {
            libraryTarget: 'commonjs',
            path: path.join(__dirname, './ClientApp/dist')
        },
        target: 'node'
    });

    return [clientBundleConfig, serverBundleConfig];
};

how to resolve the issue

**Comment by shavidze** [comment]
Some plugins and loaders may not be fully compatible with Webpack 5. For example:
  - `optimize-css-assets-webpack-plugin` has been replaced by `css-minimizer-webpack-plugin` in Webpack 5.
 - `terser-webpack-plugin` and `mini-css-extract-plugin` should be checked for the latest versions that support Webpack 5.

**Comment by Dhiren321** [comment]
I removed both from development condition yet the same error :(

**Comment by Dhiren321** [comment]
Can anyone please help kind of stuck at this

**Comment by shavidze** [comment]
share your code link here

**Comment by Dhiren321** [comment]
I have share all the files above which code is missing?

**Comment by Dhiren321** [comment]
Any help still stuck

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
