### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by Sir519** [webpack/webpack#17800]
# Bug report

**What is the current behavior?**
After upgrading from webpack4 to webpack5 and running it on the browser, an error was reported:
`Uncaught ReferenceError: require is not defined
    at whatwg-fetch (app.1699600212814.js?_t=1699600212814:85584:1)
    at __webpack_require__ (app.1699600212814.js?_t=1699600212814:85635:33)
    at app.1699600212814.js?_t=1699600212814:86843:83
    at __webpack_require__.O (app.1699600212814.js?_t=1699600212814:85681:23)
    at app.1699600212814.js?_t=1699600212814:86847:53
    at app.1699600212814.js?_t=1699600212814:86850:12
    at webpackUniversalModuleDefinition (app.1699600212814.js?_t=1699600212814:17:27)
    at app.1699600212814.js?_t=1699600212814:18:3`

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Upgrade webpack to the latest version through NPM
2. Update related dependencies to the latest version
3. Modify the configuration file and run npm run dev
4. Resolve errors during the compilation process
5. The project ran successfully and opened the browser. Enter the project opening address, but the above error appears

**What is the expected behavior?**
The expected result is that after webpack5 packages the Vue project, the browser will still be compatible with the 'require' syntax

**Other relevant information:**
webpack version:  5.89.0
Node.js version:14.21.3
Operating System: window
Additional tools: vscode

**Comment by Pixelherz23** [comment]
I also get the `Uncaught ReferenceError: require is not defined` when setting up the vsocode extetnion boilerplate code + Typescript and then add a simple .ts file that tries to import a node lib

**Comment by Pixelherz23** [comment]
I have found the solution to my problem. Maybe it help for yours:
The compiled Typescript code was running on the client-side/browser. Since my webpack.config.ts file was configured to compile this code for the server side, require() (which does not exist in the browser) was used during compilation.
I changed my config.ts to compile client code files as `target: 'web',` and server code as` target: 'node'`

**Comment by alexander-akait** [comment]
You can't use Node.js modules in a browsers, `whatwg-fetch` uses dynamic `require(...)` so webpack keeps this as is in a code, but this code is not design to use in a browser so you got this problem, maybe you use an old version of `whatwg-fetch` or also check you have `target: 'web'`, feel free to feedback
