### ISSUE TITLE
webpack build overwrites existing files, invalidating long-term cache chunks

### ISSUE THREAD

**Issue by mrtnbroder** [webpack/webpack#1780]
I figured out that, when doing a webpack build that this would overwrite existing files, even though the file has exactly the same contents (and hash).

This actually leads to a major issue – it invalidates the cache and my users get a `GET 200` and fetch the whole thing again, even though the file is the same.

When I temporarily move my `vendor.[md5hash].js` file out of the build dir, run another webpack build, and then moved it back into the build dir (overwriting it again), I get the expected `GET 304` from the file.

I guess because of the header `Last-Modified`.

In any case, I think we could improve a lot of stuff here by just skipping the whole build for files, when we can detect that the last output is the same.

Since webpack can keep records and stats for each build, why not check the hash of all files related to the chunk, detect a change, and then decide on what to skip for the build. This could improve production build-times *a lot*.

**Comment by donasaur** [comment]
This is something that is outside of webpack's scope.

If you're using hashing for file names, then what you're actually trying to do is prevent the user from sending a lot of `GET 304` requests. If your users are sending a lot of those for resources that you expect the user to pull from their local cache, then you set your server response headers incorrectly.

When you have hashed file names, you want the user to not send web requests, instead, pulling responses from cache, via `GET 200 (from cache)`. This can be achieved by making sure your server responses include a header such as `Cache-Control: max-age=31536000`

Let me see if I understand your proposal correctly: you would like webpack to read the previous state of the files that it is considering bundling, and then compare that state to the current state of the files before bundling to see if bundling (a costly process) is even required.

Keeping this sort of state in-between bundles is outside of the library's scope however. You could however do this yourself using the [webpack node.js api](https://webpack.github.io/docs/node.js-api.html) within a general build script to read/write states of files before and after bundling, to see if bundling is actually necessary. Here, I'm assuming that webpack provides a way for you to easily compare states of the files that it's about to bundle.

**Comment by donasaur** [comment]
Actually, I've been taking a look at your proposal further, and here are 2 links that may be of use:
https://github.com/webpack/webpack/issues/250 (your proposal is an open issue)
https://github.com/markfinger/webpack-build (someone tried their hand @ an in-disk cache)
