### ISSUE TITLE
Files marked sideEffects are missing from webpack build products.

### ISSUE THREAD

**Issue by jiesia** [webpack/webpack#17806]
# Bug report

**What is the current behavior?**

Files marked sideEffects are missing from webpack build products.

**If the current behavior is a bug, please provide the steps to reproduce.**

This is minimal github repository to reproduce: https://github.com/jiesia/webpack-side-effects-bug. And here I give a rough description.

Suppose there is a package named `package`, and sideEffects is declared in its package.json:

```json
{
  "name": "package",
  "sideEffects": [
    "has-side-effects.js"
  ]
}
```

The entry file of this package exports two packages, one with sideEffects and one without sideEffects:

```js
export { sideEffects } from './has-side-effects';
export { noSideEffects } from './no-side-effects';
```

When the code using this package only imports  `noSideEffects`, the module `has-side-effects.js` is not packaged into the final product. As a result, the side-effect code is not executed

**What is the expected behavior?**

The build artifact contains side-effect code for module `has-side-effects.js`.

**Other relevant information:**
webpack version:  5.89.0
Node.js version: 20.9.0
Operating System: mac m1 pro

**Comment by alexander-akait** [comment]
Because you have `console.log`, it is a side effect, we can't remove your code, please read https://codesweetly.com/side-effect#how-does-consolelog-cause-a-function-to-have-side-effects, just remove it and you will see

Also you need to set `mode: "production"` to enable all optimizations

Feel free to feedback
