### ISSUE TITLE
Error when require.ensure shim is used

### ISSUE THREAD

**Issue by yurydelendik** [webpack/webpack#1781]
Based on #183, there shall be a way to shim `require.ensure` node.js functionality. However webpack (@1.12.9) throws an error:

```
WARNING in ./entry.js
Critical dependencies:
2:2-9 require function is used in a way in which dependencies cannot be statically extracted
 @ ./entry.js 2:2-9
```

entry.js:
```
if (typeof module !== 'undefined' && module.require) {
  require.ensure = require('node-ensure'); // shim for node.js
}

require.ensure([], function () {
  require('./other.js');
});
```

I would like to move other.js content into separate file -- it's huge and it's used seldom, so bundle/module split using `require.ensure` sounds like a good way to solve it. However the same module cannot be run in node.js. 

It's expected to ignore any related to `require.ensure` shims constructs during parsing: the one like above, and another one is https://www.npmjs.com/package/require-ensure-shim. Currently, accessing `require` or `require.ensure` throws a warning and produces wrong bundling results.

**Comment by sokra** [comment]
Try this:

``` js
if(typeof require.ensure === "undefined")
  require.ensure = require('node-ensure'); // shim for node.js
}
```

**Comment by yurydelendik** [comment]
I see, `if(typeof require.ensure...` part of the shim (https://github.com/webpack/webpack/blob/9f440e30ecac00bfc27b91d372a969d3414d194c/lib/dependencies/RequireEnsurePlugin.js#L32), That works, but it still needs to have check for node.js branch to use in the browser wthout webpack:

```
if (typeof module !== 'undefined' && module.require) {
  if (typeof require.ensure === "undefined")
    require.ensure = require('node-ensure'); // shim for node.js
  }
}
```

Closing as answered. Thanks.
