### ISSUE TITLE
Failed to deploy rails app to heroku

### ISSUE THREAD

**Issue by dimis1988** [webpack/webpack#17822]
Hello to all,
Im trying to deploy a rails app to heroku with updated ruby version due to end-of-life-stack-18. When i run ./bin/webpack-dev-server locally everything work as it should including javascript,react libarries etc, But when i try to deploy i keep getting the following error.

-----> Installing dependencies
       Prebuild detected (node_modules already exists)
       Rebuilding any native modules
       rebuilt dependencies successfully
       npm notice 
       npm notice New minor version of npm available! 10.1.0 -> 10.2.4
       npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.2.4>
       npm notice Run `npm install -g npm@10.2.4` to update!
       npm notice 
       Installing any new modules (package.json)
       npm ERR! code ERESOLVE
       npm ERR! ERESOLVE could not resolve
       npm ERR! 
       npm ERR! While resolving: @webpack-cli/serve@2.0.5
       npm ERR! Found: webpack@4.47.0
       npm ERR! node_modules/webpack
       npm ERR!   webpack@"^4.46.0" from the root project
       npm ERR!   webpack@"^4.46.0" from @rails/webpacker@5.4.4
       npm ERR!   node_modules/@rails/webpacker
       npm ERR!     @rails/webpacker@"5.4.4" from the root project
       npm ERR!   13 more (babel-loader, compression-webpack-plugin, css-loader, ...)
       npm ERR! 
       npm ERR! Could not resolve dependency:
       npm ERR! peer webpack@"5.x.x" from @webpack-cli/serve@2.0.5
       npm ERR! node_modules/@webpack-cli/serve
       npm ERR!   dev @webpack-cli/serve@"^2.0.5" from the root project
       npm ERR! 
       npm ERR! Conflicting peer dependency: webpack@5.89.0
       npm ERR! node_modules/webpack
       npm ERR!   peer webpack@"5.x.x" from @webpack-cli/serve@2.0.5
       npm ERR!   node_modules/@webpack-cli/serve
       npm ERR!     dev @webpack-cli/serve@"^2.0.5" from the root project
       npm ERR! 
       npm ERR! Fix the upstream dependency conflict, or retry
       npm ERR! this command with --force or --legacy-peer-deps
       npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
       npm ERR! 
       npm ERR! 
       npm ERR! For a full report see:
       npm ERR! /tmp/npmcache.84VfW/_logs/2023-11-23T10_57_25_323Z-eresolve-report.txt
       
       npm ERR! A complete log of this run can be found in: /tmp/npmcache.84VfW/_logs/2023-11-23T10_57_25_323Z-debug-0.log
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
       
       Some possible problems:
       
       - node_modules checked into source control
         https://devcenter.heroku.com/articles/node-best-practices#only-git-the-important-bits
       
       Love,
       Heroku
       
 !     Push rejected, failed to compile Node.js app.

i have tried everything like updated webpack and webpacker to the latest version etc but each time i get a different error. Any suggestions????

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
