### ISSUE TITLE
Load dist bundle js file as a component in another React(Typerscript) application.

### ISSUE THREAD

**Issue by nehatanvashi** [webpack/webpack#17834]
"react": "^18.2.0",
"react-dom": "^18.2.0"
"typescript": "^5.3.2"
"webpack": "^5.89.0"

I have created the react application with above packages. In the react application the virtual chatbot is rendered. I have created the dist bundle file using webpack.

The same dist folder I want to consume in another react application(typescript) without serving dist.

Is there any way to achieve it?

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
