### ISSUE TITLE
Module Federation with library.type (window) is not working

### ISSUE THREAD

**Issue by OnlyYu1996** [webpack/webpack#17844]
What is the current behavior?

I currently have three applications. Due to the need to integrate with micro-frontends, JavaScript needs to be loaded within a scoped environment, so it's necessary to set 'library.type' to 'window'. When there are two applications (where the first application provides components, and the second application only uses components without providing any), setting the 'library.type' of the provider to 'window' meets the expectations. However, when the second application starts providing components to the outside, setting its 'library.type' to 'window' leads to issues. The second component fails to find the components from the first application when attempting to load them.

![image](https://github.com/webpack/webpack/assets/42717106/657aaab7-946f-4bff-8762-ee592400f5f3)

What is the expected behavior?

The expectation is that the components provided by multiple applications can be accessed through mounting on the 'window'.
I have provided a simple repository with [reproducible code.](https://github.com/OnlyYu1996/wujie-federation-demo)

**Comment by OnlyYu1996** [comment]
The main goal is to mount sub-applications with module federation in a micro-frontend application, where the final effect can be fully demonstrated on [this website](https://wujie-micro.github.io/doc/wujie/) with each application displayed.

**Comment by alexander-akait** [comment]
Hello, sorry for delay, because `window` is not design for such purposes, you can use window when you have mutliple containters on the same page, but here you have different containers on different pages, but anyway you can do it using low level API:
```vue
<script>
import { defineAsyncComponent } from 'vue';

async function loadComponent(scope, module) {
  // Initializes the shared scope. Fills it with known provided modules from this build and all remotes
  await __webpack_init_sharing__('default');
  const container = window[scope]; // or get the container somewhere else
  // Initialize the container, it may provide shared modules
  await container.init(__webpack_share_scopes__.default);
  const factory = await window[scope].get(module);
  const Module = factory();
  return Module;
}

export default {
components: {
    ContentElement:defineAsyncComponent(() => loadComponent('home', './Content')),
    ButtonElement:defineAsyncComponent(() => loadComponent('home', './Button')),
  }
};
</script>
```

Also don't forget to load:

```html
<script src="https://localhost:3001/remoteEntry.js"></script>
<div id="app"></div>
```

Feel free to feedback
