### ISSUE TITLE
`module`.`rules` refuses to accept my loader

### ISSUE THREAD

**Issue by ericmorand** [webpack/webpack#17843]
I'm trying to test my Webpack loader, but in my test case, the compiler refuses to accept my loader as the handler for the module rule:

```typescript
import twigLoader from "../../src/lib/loader";
import {webpack} from "webpack";

const compiler = webpack({});
        
compiler.options.module = {
    rules: [
        {
            test: /\.twig$/,
            use: twigLoader // TS2322: Type
        }
    ]
};
```

I suspect the TypeScript types to we faulty and only declare `use` as being a `string` which obviously makes passing loader from the node API impossible.

Is there a workaround? Can I fix the types in some way?

**Comment by alexander-akait** [comment]
Because it should be a path to the loader, i.e. string, here you have a function, feel free to feedback

**Comment by ericmorand** [comment]
@alexander-akait, thanks, I ended up understanding that point, but it raises a question: how can we test loaders before publishing them if Webpack expect loaders to be resolved by their path? Must we first build the loader, then change the path of the loader in the test suite, then run the test?

It seems more difficult than necessary and quite unusual.

**Comment by alexander-akait** [comment]
You can use jest and run webpack comliation in every test, you can look `css-loader` for examples

**Comment by ericmorand** [comment]
`css-loader` builds the loader before running the test - as is my own legacy twing loader doing. But it was years ago (4 or 5 I'd say) and it was already more complicated than needed - and made the testing process awkward. 

That it is the case today, after another major version of webpack that had the opportunity to include a breaking change, is very disappointing - just being honest here.

Well. That's how it is. 🤷🏻‍♂️
