### ISSUE TITLE
Memory leak from child compilation in watch mode (`Sources` strings)

### ISSUE THREAD

**Issue by helloitsjoe** [webpack/webpack#17857]
# Bug report

NOTE: This issue is very similar to https://github.com/webpack/webpack/issues/17851 (child compilations), but these are two separate leaks. This one is related to duplicate strings added to the in-memory cache.

**What is the current behavior?**

When running in watch mode, Webpack caches source code from child compilations (e.g. `HtmlWebpackPlugin`) without removing them:

<details open>

  <summary>Duplicated strings in memory</summary>

  <img width="1707" alt="Duplicate strings" src="https://github.com/webpack/webpack/assets/8823810/4d50e028-a0df-4a91-ab1d-579ae7766394">

</details>

<details open>

  <summary>Retained Sources</summary>

  <img width="1464" alt="Retained Sources" src="https://github.com/webpack/webpack/assets/8823810/99efa7ea-930d-48c5-a116-e11b27279a80">

</details>

The leak is worse when we have build-time dependencies, as in the reproduction repo:

<details open>
  <summary>Duplicated build-time dependencies source</summary>
  
  <img width="1707" alt="strings" src="https://github.com/helloitsjoe/webpack-cache-memory-leak/assets/8823810/499fb875-7067-406f-b09b-d733ad1889ff">

</details>

**Investigation done**

One place these are being cached is [in a `Map` in `MemoryCachePlugin`](https://github.com/webpack/webpack/blob/87660921808566ef3b8796f8df61bd79fc026108/lib/cache/MemoryCachePlugin.js#L27). When a child compiler caches them it uses the child compiler ID, for example (note the `HtmlWebpackPlugin_0-7`, the 7th time I ran a recompilation):

```
'HtmlWebpackCompiler|0|Compilation/codeGeneration|javascript/esm|data:text/javascript,__webpack_public_path__ = __webpack_base_uri__ = htmlWebpackPluginPublicPath;|HtmlWebpackPlugin_0-7'
```

This seems problematic because entry will never be found, since the key uses an ID unique to each iteration.

**If the current behavior is a bug, please provide the steps to reproduce.**

Minimal reproduction repo including steps to reproduce here: https://github.com/helloitsjoe/webpack-cache-memory-leak

**What is the expected behavior?**

Dependency source code should be cached only once (or maybe twice including the child compilation). A few potential options:

1. Remove the child compiler sources from the cache during `_cleanupLastCompilation`, but I don't see a way to clear entries from the `MemoryCache` map currently.
2. Only cache compiler sources for the parent compilation, or replace the previous child compilation's cached sources.

I'm also not sure `MemoryCache` is the only place the sources are being referenced, so fixing this leak might require more changes. I'm happy to help however I can.

**Other relevant information:**
webpack version: 5.89.0
Node.js version: 20.5.1
Operating System: MacOS (darwin 22.5.0)
Additional tools: `HtmlWebpackPlugin` (child compiler), custom loader in https://github.com/helloitsjoe/webpack-cache-memory-leak to cache build-time dependency sources

**Comment by alexander-akait** [comment]
Thank you for the issue, do you want send a PR with fix?

**Comment by helloitsjoe** [comment]
I will see if I can determine the root cause here, it's not clear to me yet. This might actually be an issue in HtmlWebpackCompiler, if that turns out to be the source I'll close this issue!

**Comment by helloitsjoe** [comment]
I think I've narrowed this down to a commit in HtmlWebpackPlugin. I've opened an issue over there, I'll follow up here if it's confirmed to be a problem there: https://github.com/jantimon/html-webpack-plugin/issues/1835

**Comment by helloitsjoe** [comment]
@alexander-akait I noticed you're a maintainer of HtmlWebpackPlugin as well, does the change I'm suggesting in this PR look like a reasonable fix for this? https://github.com/jantimon/html-webpack-plugin/pull/1836

I'm happy to look more into this if not.

**Comment by helloitsjoe** [comment]
Thank you!
