### ISSUE TITLE
Functioning of require.ensure()

### ISSUE THREAD

**Issue by jashan777** [webpack/webpack#17856]
### Discussed in https://github.com/webpack/webpack/discussions/17849

<div type='discussions-op-text'>

<sup>Originally posted by **jashan777** December  6, 2023</sup>
In require.ensure() , if i change the callback function syntax to a arrow function syntax withouth the require parameter, everything works without breaking. 

from
```
require.ensure(['b'], function(require){
                        
var c = require('c');
             
});
```
to 

```
require.ensure(['b'], () => {
                        
    var c = require('c');
             
});
```
can someone explain me the reason, why implementation of the require function is sent as a parameter to this function (callback function) as given in the documentation ? 
https://webpack.js.org/api/module-methods/#requireensure

**Comment by GaganpreetKaurKalsi** [comment]
I see there are many examples in webpack repo, where at some places they have "require" as parameter....while other places they don't (see one such example below). 
<img width="672" alt="image" src="https://github.com/webpack/webpack/assets/54144759/2e9b1725-cf35-48bc-8497-34ff88b835c8">

The webpack docs is not very clear about the require implementation as parameter.....if it is an ordinary require or does something different.

**Comment by jashan777** [comment]
> I see there are many examples in webpack repo, where at some places they have "require" as parameter....while other places they don't (see one such example below). <img alt="image" width="672" src="https://private-user-images.githubusercontent.com/54144759/290409412-2e9b1725-cf35-48bc-8497-34ff88b835c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1NDg3MTgsIm5iZiI6MTcwMjU0ODQxOCwicGF0aCI6Ii81NDE0NDc1OS8yOTA0MDk0MTItMmU5YjE3MjUtY2YzNS00OGJjLTg0OTctMzRmZjg4YjgzNWM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDEwMDY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkNjZjYmY0NjU4OGRhM2Q3ZWZjZjI5YzBhOWFiOTdlZTZkYjliZjg1MTMzYTI1ZjhjMTAzOTI0NzliOWJlZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7WUw_RnyI16wdyoli3S_cVZT63WnmLmoBnbqNQ1D_us">
> 
> The webpack docs is not very clear about the require implementation as parameter.....if it is an ordinary require or does something different.

agreed webpack docs are no so clear about require implementation as parameter

**Comment by alexander-akait** [comment]
Looks like `swc` does it https://github.com/swc-project/swc/issues/7505

I see https://github.com/swc-project/swc/issues/7505#issuecomment-1700860794 swc team doesn't want to fix it, you can try to send a PR with the fix, sorry, we really can't do something here, anyway feel free to feedback
