### ISSUE TITLE
【document bug】Why is the'inline-nosources-source-map' option not included in the devtool configuration  document in webpack4? Is there a problem with this option, or is it just that the document was forgotten to update? The source code should support the inline-nosources-source-map option

### ISSUE THREAD

**Issue by WormGirl** [webpack/webpack#17859]
# Bug report

**What is the current behavior?**
webpack4 docs do not has inline-nosources-source-map option at devtool config, this is supported.
![image](https://github.com/webpack/webpack/assets/16078260/141141a7-fb8d-4ced-b601-ffe1ca26316e)
![image](https://github.com/webpack/webpack/assets/16078260/0ca40fc1-50a3-434a-b931-e2500d7b1190)

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  4.46.0
Node.js version: 16.20.1
Operating System:
Additional tools:

**Comment by alexander-akait** [comment]
Feel free update our docs, I think we don't document it because it is very rarely used

**Comment by WormGirl** [comment]
> Feel free update our docs, I think we don't document it because it is very rarely used

so use `inline-nosources-source-map` at webpack@latest is safe?
