### ISSUE TITLE
Watching.prototype.invalidate should have a callback

### ISSUE THREAD

**Issue by jantimon** [webpack/webpack#1785]
`Watching.prototype.invalidate` allows to recompile however it is really hard to get feedback once it is complete

https://github.com/webpack/webpack/blob/master/lib/Compiler.js#L113

Could you please add a callback?

**Comment by Arslanbekov** [comment]
How to solve?

**Comment by TheLarkInn** [comment]
@jantimon Can you show me how you would pass in the callback. Or have a code example. I'd like to work on this PR but need a bit more context.

**Comment by viniciusRib** [comment]
I'm a beginner and i want to fix this issue to accomplish a work for college. I tried to fix but i don't know how to say if it's correct. Someone could help me?

**Comment by TheLarkInn** [comment]
@jantimon can you show the use case for this?

**Comment by jantimon** [comment]
Invalidate will cause a recompilation but you won't know when it's done.
Usually you would change the configuration, invalidate and continue as soon as the new configuration is valid again.

**Comment by viniciusRib** [comment]
I solve the problem, how can i submit this issue?

**Comment by alexortiz201** [comment]
Should this callback trigger on  all cases? or only if paused, running, or else?

**Comment by kutyel** [comment]
@jantimon is this already fixed or can I work on it? Happy #hacktoberfest!

**Comment by jantimon** [comment]
It's not fixed yet

**Comment by kutyel** [comment]
Ok perfect, so what is the expected behaviour, what else needs to be done? I am willing to work on this 😉

**Comment by kutyel** [comment]
@jantimon should be fixed now, why is the codecov first check not passing btw? I would appreciate some feedback 😉
