### ISSUE TITLE
[Plugin] Names for replaces

### ISSUE THREAD

**Issue by IngwiePhoenix** [webpack/webpack#1786]
I had to scrap that together from APIPlugin.js and MainTemplate.js, but this is something I think should be made available as a map - as in, what translates to what.

```
require -> __webpack_require__
require.ensure -> __webpack_reqnure__.e
require.cache -> __webpack_require__.c
require.onError -> __webpack_require__.oe
```

I am developing a plugin that must know these names, as it transpiles from one language to another, and will have to properly resolve calls from the other language to JS. So I need to properly translate the calls.

**Comment by sokra** [comment]
Yes sounds reasonable. You can send a PR that defines some constants on the `Template` class and use them.

**Comment by aleury** [comment]
I have a patch for this if no one else has claimed it. I can't seem to find any information about project code style. Does webpack use uppercase variables for all constants?
