### ISSUE TITLE
When libraryTarget is set to module, the externals configuration appends hardcoded arrow functions that cannot be transformed

### ISSUE THREAD

**Issue by versole** [webpack/webpack#17861]
webpack version :5.89.0

libraryTarget: module
fileName: bundle.js
externals: react, react-dom

babel settings:@babel/preset-env @babel/preset-react

bundle.js file still includes arrow function like 
`
external_react_dom_x = y => { var x = {}; __webpack_require__.d(x, y); return x; }
var external_react_dom_y = x => () => x
// from getSourceForModuleExternal or generateModuleRemapping
`
![image](https://github.com/webpack/webpack/assets/36833118/ae17bacf-ed61-4828-a71e-3c4b28c21dee)

I need to provide a component to another project, but that project uses tools like 'es-check' which do not allow arrow functions.

Is there any method that could help me transform these hardcoded arrow functions into normal functions?

**Comment by alexander-akait** [comment]
We can fix it, but if your browser supports modules, it means you have support arrow functions

**Comment by versole** [comment]
> We can fix it, but if your browser supports modules, it means you have support of arrow functions

How are you going to fix it？If the issue is converting arrow functions to regular functions, I’m willing to create a PR to resolve it.

**Comment by alexander-akait** [comment]
@versole We have https://github.com/webpack/webpack/blob/main/lib/RuntimeTemplate.js#L139 and should use there to generate code, so if you will set `output.environment.arrowFunction` to false and we will generate a regular function, so the fix is easy, you can send a PR

**Comment by daydayhappychao** [comment]
Has anyone still followed up on this issue?
I can give a PR soon.
