### ISSUE TITLE
ModuleFederationPlugin路径解析问题

### ISSUE THREAD

**Issue by pvfhv** [webpack/webpack#17866]
# Bug report

react.development.js:1309 Uncaught ReferenceError: Cannot access '__WEBPACK_DEFAULT_EXPORT__' before initialization

new ModuleFederationPlugin({
        name: 'intelligence',
        filename: 'remoteEntry.js',
        exposes: {
          './InformationManage': './src/pages/information-management/information-manage/components/monitor',
        },
        shared: {
          react: {
            singleton: true,
          },
          'react-dom': {
            singleton: true,
          },
        },
      }),

monitor内容
import React from 'react'
// import { Button } from 'antd'

const NewsList = () => (
  <div className="bg">
    新闻列表:
    <hr />
    {/* <Button>登录</Button> */}
    <div className="text">less 样式</div>
  </div>
)

export default NewsList

其中无components这个目录即可加载成功

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  5.76.2
Node.js version: 16.20.2
Operating System: mac os
Additional tools: tabby

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
