### ISSUE TITLE
Web Workers in a project with `experiments.outputModule = true` call `importScripts` despite being loaded with `{type: "module"}`

### ISSUE THREAD

**Issue by gingershaped** [webpack/webpack#17870]
# Bug report

**What is the current behavior?**

In a project with `experiments.outputModule = true`, the following code:
```js
// main code
new Worker(new URL("<worker path>", import.meta.url))
```
```js
// worker code
import { Stuff } from "some-really-big-module-that-gets-its-own-chunk"
```

will generate a main file that calls `new Worker("<processed URL>", { type: "module" })`, but a worker that calls `importScripts()` to load `some-really-big-module-that-gets-its-own-chunk`. This results in an error when the worker is loaded.

**Reproduce**

A minimum viable example may be found at https://github.com/gingershaped/webworker-mre.

**What is the expected behavior?**

Workers loaded in a project under these conditions should only use ES module imports to load dependencies.

**Other relevant information:**
webpack version: 5.89.0
Node.js version: 18.13.0
Operating System: Debian Bookworm
Additional tools: None

**Comment by alexander-akait** [comment]
I want to say it is a feature, we don't support ES module output for workers right now

**Comment by alexander-akait** [comment]
bump

**Comment by thomastay** [comment]
@alexander-akait not really a bump but more of a question whether this is intended to be supported eventually? I see this is in the Webpack 5/6 project roadmap under Priority - Medium, but is the plan to make Workers respect outputModule as well?

Our use case for this would be to allow parallel dynamic imports of modules in Worker scripts. The current importScripts API is a synchronous API. I'm not really sure if we could use `experiments.outputModule` to do what we want anyway, but just wondering what is the planned status of this work.

**Comment by alexander-akait** [comment]
> but is the plan to make Workers respect outputModule as well?

Yeah, but I am afraid I can't find time for this near future, but I am glad to any PRs

**Comment by Aghassi** [comment]
It looks like, to my understanding, the only way around this issue until a fix is released is to do this multi build setup correct? https://github.com/webpack/webpack/discussions/13655#discussioncomment-2584809

Essentially build the worker separately with the experiment on, then reference it in the app.

**Comment by alexander-akait** [comment]
I am afraid using `experiment on` still will generate code for `importScripts`, but need test

**Comment by alexander-akait** [comment]
There are 2 problems:
1. We use `importScripts`, but should `import()` - fixed in main
2. https://github.com/webpack/webpack/issues/17014

I want to close in favor - https://github.com/webpack/webpack/issues/17014, will try to fix soon

**Comment by thomastay** [comment]
> We use importScripts, but should import() - fixed in main

@alexander-akait Didn't realize this has already been fixed, could you point me to where this has been changed? This might be helpful for us

**Comment by alexander-akait** [comment]
@thomastay 

https://github.com/webpack/webpack/releases

> Use optimistically logic for output.environment.dynamicImport to determine chunk format when no browserslist or target

Do you have a problem?

**Comment by thomastay** [comment]
@alexander-akait nope, just excited to hear about it as it's a feature we're tracking. We want to be able to use dynamic imports in the worker.

So right now in Webpack main, `import` is transpiled to `import` and not `importScripts`, but the linked issue #17014 still prevents module workers from generating entry chunks that depend on common chunks, is that correct?

**Comment by alexander-akait** [comment]
@thomastay Yeah, want to fix it soon
