### ISSUE TITLE
[Plugin] Replacing a piece of source code

### ISSUE THREAD

**Issue by IngwiePhoenix** [webpack/webpack#1787]
WebPack does that a _lot_ with `require` and `define`. But how does a plugin implement that?

Let's say we have this in our entry:

```javascript
foo("bar");
```

That gives me:
```javascript
{ range: [ 0, 10 ],
  loc: WrappingSourceLocation { start: { line: 1, column: 0 }, end: { line: 1, column: 10 } },
  type: 'CallExpression',
  callee: 
   { range: [ 0, 3 ],
     loc: SourceLocation { start: [Object], end: [Object] },
     type: 'Identifier',
     name: 'foo' },
  arguments: 
   [ { range: [Object],
       loc: [Object],
       type: 'Literal',
       value: 'bar',
       raw: '"bar"' } ] }
```

But how do I replace it to come out as:
```javascript
bar("bar");
```

I can see how it somehow is being done:
https://github.com/webpack/webpack/blob/master/lib/dependencies/LocalModuleDependency.js#L22

But that piece doesn't quite make me understand. Would be nice to hear back :)

**Comment by sokra** [comment]
a plugin can add a `Dependency` to the module. For a Dependency a template is registered, which can do string replacements or inserts on the source code.
