### ISSUE TITLE
ES6 import implementation does not handle circular dependencies for "default"

### ISSUE THREAD

**Issue by loganfsmyth** [webpack/webpack#1788]
Filing since it would be cool if this could be consistent with Babel. The current import logic for default exports does not handle circular dependencies properly. The presence of a 'default' properly is not enough to ensure proper functionality, at least with the current export implementation.

For example

```
// a.js
import b from './b';
export default 'a-default';

// b.js
import a from './a';
export default 'b-default';

// main.js
import './a';
```

will cause the `b.js` import to `require` `a.js` before it has executed its body, so `"default"` will not yet exist, and `a` in `b.js` will end up being the `exports` object rather than the default properly.

One option would be to hoist the initial assignment of `exports['default']` so `a.js` is more like

```
exports['default'] = undefined;
import b from './b';
exports['default'] = 'a-default';
```

This issue is solved in Babel similarly, but in Babel, a `__esModule` flag is used instead to also avoid treating ES5 modules that happen to have a 'default' property as default exports, where they may not expect to be.

Either way, something needs to be set on the `exports` object of anything that has ES6 exports, before any of that module's dependencies are executed. It'd be awesome if we could all standardize on `__esModule` though.

**Comment by loganfsmyth** [comment]
cc @trusktr

**Comment by sokra** [comment]
Could you add an example which prints something and include the actual and expected output? As far as I know webpack should behave correctly according to the ES6 modules spec.

**Comment by trusktr** [comment]
I wonder if this is just something that isn't specified in the spec? I'm having [similar problems](https://github.com/benjamn/install/issues/4) (in fact, the same problem in that issue happens exactly the same with Webpack) with a seemingly unrelated project.

**Comment by sokra** [comment]
It's specified in the spec. In the example above by @loganfsmyth the execution order is `b.js`, `a.js`, `main.js`. `b.js` would not be able to see the exports of `a.js` because `a.js` wasn't executed yet. But because ES6 imports are binds `b.js` can see the exports of `a.js` once it is executed. `main.js` would see all exports of `a.js` and `b.js`.

**Comment by loganfsmyth** [comment]
Ah, I was testing on the small scale and made an example based on that and it looks like the output changed more than I expected it to when I tweaked something. I was taking a look at Webpack because I was thinking it was the cause of @trusktr's "similar problems" above, but now I'm not sure.

My concern essentially came down to seeing

```
return __WEBPACK_IMPORTED_MODULE_0__b__ && typeof __WEBPACK_IMPORTED_MODULE_0__b__ === 'object' &&
        'default' in __WEBPACK_IMPORTED_MODULE_0__b__ ? __WEBPACK_IMPORTED_MODULE_0__b__['default'] : __WEBPACK_IMPORTED_MODULE_0__b__;
```

In the general case of circular dependencies, there isn't a guarantee that the `default` key will exist at the point where this function is called, because the default export may not have been assigned yet.  It looks like Webpack strips out that logic based on the module being imported though, so it actually isn't present in the example I posted. That said, it does seem dangerous to me since it'll fail in the circular case. What is the motivation for checking `'default' in` in that context if it isn't for ES6 modules? It seems like that would be a breaking behavior for standard CommonJS.

@sokra There are a few other ES6 module things I want to file that I noticed when checking this, but I don't want to file them if they are still in the works. Do you still have more to add, or should I assume they are stable as-is and file a few more bugs?

**Comment by sokra** [comment]
This piece of code is a special compatibility layer, which is only emitted when you import `default` from a not-ES6 module (i. e. a CommonJs module). If you take a closer look on the generated code you will notice that I took extra care to make it safe for circular dependencies.

Here is an example an the generated code:

``` js
// cjs.js
if(Math.random() > 0.5) {
  // Either this style
  module.exports = 1234;
} else {
  // or this style
  exports.default = 1234;
  // i. e. if transpiled by any other tool.
}
// which module style is used is only known at runtime
```

``` js
// main.js
import value from "./cjs"

export function test() {
  console.log(value);
}
```

Generated code for main.js (reformatted for readability):

``` js
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0_cjs__ =
  __webpack_require__(/*! commonjs */ 4);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0_cjs___default = function() {
  return __WEBPACK_IMPORTED_MODULE_0_cjs__ &&
    typeof __WEBPACK_IMPORTED_MODULE_0_cjs__ === 'object' &&
    'default' in __WEBPACK_IMPORTED_MODULE_0_cjs__ ?
      __WEBPACK_IMPORTED_MODULE_0_cjs__['default'] :
      __WEBPACK_IMPORTED_MODULE_0_cjs__;
}
/* harmony import */ Object.defineProperty(
  __WEBPACK_IMPORTED_MODULE_0_cjs___default,
  'a',
  {
    get: function() {
      return __WEBPACK_IMPORTED_MODULE_0_cjs___default();
    }
  }
);
/* harmony export */ exports["test"] = test;

function test() {
  console.log(__WEBPACK_IMPORTED_MODULE_0_cjs___default.a);
}
```

The check if `default` is in the module object or not is made when the value is accessed not when the module is executed.

**Comment by loganfsmyth** [comment]
I admit these aren't massive, but that has two downsides:

1. If the CommonJS module happens to have a `.default` property and is used from ES6 code, that will be used even if not intended. e.g.

    ```
    module.exports = function foo(){};
    module.exports.default = 'something else';
    ```

    The first is primarily something that concerns me because it is a potentially unexpected behavior in comparison to Babel, so if devs tried to transition a codebase using Babel's ES6 modules to Webpacks for tree shaking for instance, it could break if they had a CommonJS module that had a `.default` properly. Or if they are going the other way and had manually added a `.default` to their CommonJS module, it would not be the default in Babel.

2. If there is a circular dependency between a CommonJS-style module and a ES6 module (say if a codebase was mid-transition to ES6), it will return incorrectly, e.g.
    ```
    // main.js
    import './a';

    // a.js
    var b = require('./b');
    exports.default = 4;

    // b.js
    import a from './a';
    console.log(a);
    ```

    Main will run 'a', and 'a' will run 'b' and then when 'b' loads 'a', it should realistically be `undefined` but instead it would return the exports object.

    I admit this one is very edge-casey, so if you want to deem this so and ignore it, I'll accept that. This seems unlikely to actually break anything, though I could see it causing confusion when transitioning a codebase to ES6.

**Comment by sokra** [comment]
So it now behaves similar to babel.

``` js
// a.js
module.exports = function() {};
module.exports.default = 42;
module.exports.xyz = 123;
```

``` js
import a from "./a";
// webpack and babel:
// a = function() {}

// but this is different
import { xyz, default } from "./a";
// webpack: xyz = 123, default = 42;
// babel: xyz = undefined, default = function() {}
```

I think it makes more sense to thread the module as ES6 module when using import with specifiers. Discuss...

``` js
import { readFile, exist } from "fs";
```

**Comment by bendc** [comment]
What's the state of this in webpack 2 beta? I'm experiencing a lot of issues presumably caused by cyclic dependencies on ES6 modules using default exports, so I assume it's not supported yet?

**Comment by DelvarWorld** [comment]
I implemented a tool to check your webpack build for ES6 (or require) cyclical imports :) https://github.com/DelvarWorld/webpack-cyclic-dependency-checker

**Comment by kylecordes** [comment]
We've seen accidental and hard-to-spot circular dependencies using "barrel" index.ts files. This is using AngularJS (not at fault here!), TypeScript 2.0, and Webpack 2.x as imported by Angular-CLI. So there is a tall stack... but it appears to be this same underlying issues.

**Comment by timoxley** [comment]
This silently breaks valid, working code. It should probably be labelled as a bug.

**Comment by sokra** [comment]
Everything behave as specced

**Comment by timoxley** [comment]
@sokra on latest webpack 2 beta?

**Comment by dionysiusmarquis** [comment]
Are circular dependencies supported now? To be honest, I didn't get the consensus to this topic.

**Comment by ronichoudhury** [comment]
I'm running into a problem in my projects that seems very much to be related to this issue. Would be awesome to hear an update.

**Comment by th3fallen** [comment]
Can confirm as of today on beta 27 that circular dependencies are NOT handled correctly @sokra if that is spec'd they may need another once over.

**Comment by timoxley** [comment]
Can confirm this also, my app does not work while circular dependencies exist, though I was not able to produce a simple reproducible example.

**Comment by csvan** [comment]
Confirming this on webpack 1.13 running an angular 1.x project.

**Comment by thinkingmedia** [comment]
I'm hitting this problem with a deep circular dependency. It's taken me many hours to even see that it's a circular problem and an issue with webpack.

I don't even get a reasonable error message, but just this error message when the app bootstraps.

```
main.bundle.js:22949 Uncaught TypeError: Cannot read property 'prototype' of undefined
    at __extends (main.bundle.js:22949)
    at main.bundle.js:22966
    at Object.<anonymous> (main.bundle.js:22980)
    at __webpack_require__ (inline.bundle.js:53)
    at Object.<anonymous> (main.bundle.js:14103)
    at __webpack_require__ (inline.bundle.js:53)
    at Object.<anonymous> (main.bundle.js:23073)
    at __webpack_require__ (inline.bundle.js:53)
    at Object.<anonymous> (main.bundle.js:14001)
    at __webpack_require__ (inline.bundle.js:53)
```

**Comment by th3fallen** [comment]
@thinkingmedia there's a plugin linked above that can help you identify them out helps a lot

**Comment by gund** [comment]
Hi everyone. I just run into this issue as well and thankfully found it in the early stage so can give a minimal [repro here](https://gist.github.com/gund/fa244bfef5024ebe2aba72d31d565cb0).

For nowI have no idea how to workaround this.
Thanks.

**Comment by trusktr** [comment]
Hi @gund, see my solution here: https://gist.github.com/gund/fa244bfef5024ebe2aba72d31d565cb0#gistcomment-1957158

(Note, I made a typo, which I mentioned in a following comment)

**Comment by mrchess** [comment]
Ran into this recently as well. Basically the ducks paradigm is useless because you can't detect circular imports. Does anyone know a real solution and not a hack one? Is this a webpack bug? If I move back to require instead of imports, will it fix it?

**Comment by abhinavsingi** [comment]
Ran into this once I switch on the default module imports now supported in webpack by adding {modules:false} in babel presets options.

Error coming is `TypeError: __webpack_require__.i(...) is not a function` .
__webpack_require__.i is the identity function and the "function" going in it is imported in de-structured manner having cyclic dependency.
It comes out to be undefined and hence the error.

@sokra - Do you need an example or are already aware of this? How best to tackle this?
Removing {modules:false} and adding back add-module-exports plugin of babel does solve it - but then tree shaking doesn't work.
Any help appreciated!

**Comment by Spongman** [comment]
| Everything behave as specced

i was considering using webpack going forward. but this comment changed by mind. thanks for clearing that up for me @sokra

**Comment by lebed2045** [comment]
Three years later and it still doesn't work.

**Comment by loganfsmyth** [comment]
@lebed2045 @Spongman I don't really contribute much on Webpack, but in my experience in OSS, comments on old closed issues are unlikely to elicit responses because there's barely enough time to keep up with new issues, let alone every comment on every existing issue. I no longer have a horse in this race, but if you're having issues, filing a new bug with clear reproduction would likely be a better way to get the conversation going again.
