### ISSUE TITLE
Source Map is inorrect when enable extractComments.banner of terser-webpack-plugin

### ISSUE THREAD

**Issue by kerm1it** [webpack/webpack#17899]
# Bug report

[webpack-terser-bug](https://github.com/kerm1it/webpack-source-map-bug)

**What is the current behavior?**

When my project using json file and `use-sync-external-store@1.2.0`,  the source map is incorrect:

![incorrect](https://github.com/webpack/webpack/assets/33770367/e6567d15-9a0f-441e-931e-b5bedcba6c07)

Find `a.json` is mapped to `use-sync-external-store` incorrectly.

**What is the expected behavior?**

When disable `extractComments` options of `terser-webpack-plugin`，the behavior is correct.

![correct](https://github.com/webpack/webpack/assets/33770367/5afc9067-8c1d-4f3c-b009-3ec17972fcfc)

`a.json` is no-source, this is expected.

**Other relevant information:**
webpack version:  5.89.0
Node.js version: v18.18.0
Operating System: MacOS m2

**Comment by kerm1it** [comment]
any update ？

**Comment by alexander-akait** [comment]
Close due https://github.com/webpack-contrib/terser-webpack-plugin/issues/589
