### ISSUE TITLE
Document module.hot.accept(moduleId, callback)

### ISSUE THREAD

**Issue by halt-hammerzeit** [webpack/webpack#1790]
`module.hot.accept(moduleId, callback)` accepts a `moduleId`. What is `moduleId`? Is it a global path on the filesystem? Is it a relative path to the `context` project folder? Is it relative to the current `js` file?

**Comment by sokra** [comment]
`module.hot.accept` takes a `dependency` as first argument, which is the same as `require` takes.

http://webpack.github.io/docs/hot-module-replacement.html#accept

**Comment by halt-hammerzeit** [comment]
So, if module `A` in folder `A` requires module `B` in folder `B` (`require('./B/index.js')`) and module `B` in folder `B` requires module `C` in folder `C` (`require('./C/index.js')`) then should we write `module.hot.accept('./B/C/index.js')` in module `A`? Or should it be `module.hot.accept('./C/index.js')` no matter in what parent module is it written?
Or `module.hot.accept('relative/path/to/module')`

**Comment by halt-hammerzeit** [comment]
To rephrase it, must `module.hot.accept` be called only in the immediate parent module (the one that has the `require()` call) or can `module.hot.accept` be called in arbitrary parent module up the `require()` chain?

**Comment by halt-hammerzeit** [comment]
I guess it's just for the immediate parent module.
I feel that I get it now.

**Comment by sokra** [comment]
> I guess it's just for the immediate parent module.

yes

**Comment by halt-hammerzeit** [comment]
Also it can be noted that `module.hot.accept(required_path, () => { alert('won't work') })` won't work with the variable holding the required path - it must be a constant like this `module.hot.accept('../path/to/the/module', () => { alert('works') })`

**Comment by jharris4** [comment]
I just encountered the issue with trying to use a variable holding the required path, like this:

var theFile = './test.js';
if (module.hot)
  module.hot.accept(theFile, function() { })

It only works with the string literal instead of the variable, any chance someone could give an explanation for this limitation, or suggestions for workarounds to avoid using string literals?

**Comment by sokra** [comment]
Workaround:

``` js
var theFile = require.resolve('./test.js');
if (module.hot)
  module.hot.accept(theFile, function() { })
```

**Comment by halt-hammerzeit** [comment]
@sokra Are you saying that this theoretically should work?

```javascript
function enable_hot_reload(path_to_file)
{
    if (module.hot)
    {
        module.hot.accept(path_to_file, function() { ... })
    }
}
```

**Comment by sokra** [comment]
> Are you saying that this theoretically should work?

Yes, but it's bad because it creates a context just like `require(path_to_file)`. Try to avoid dynamic requires...

**Comment by halt-hammerzeit** [comment]
@sokra So it won't work as a library?

```javascript
export function enable_hot_reload(path_to_file)
{
    if (module.hot)
    {
        module.hot.accept(require.resolve(path_to_file), function() { ... })
    }
}
```

`npm install hot-reloader`

```javascript
import { enable_hot_reload } from 'hot-reloader'

enable_hot_reload('./code/component.js')
```

**Comment by sokra** [comment]
Nope it doesn't work as library.

It must be statically resolvable...

**Comment by jharris4** [comment]
@sokra Thanks for the workaround, that part is working great. I've updated my code to look like this:

```
var theFile = './someFile.js';
var resolvedFile = require.resolve(theFile);
if (module.hot) {
    module.hot.accept(resolvedFile, function() {
        // ...
        require(theFile);
    });
}

require(theFile);
```

Using ```require(theFile);``` inside the ```module.hot``` block works fine, but I'm stuck using ```require('./someFile.js')``` outside of the block.

Any further advice on how to resolve this last little issue? I'd really like to have the file name be parameterized as a variable to make this code reusable for more than one specific file...

**Comment by halt-hammerzeit** [comment]
@jharris4 You can use `require('./code/folder/' + module + '.js')` and Webpack will bundle the whole `./code/folder/` folder for runtime resolving. Therefore you should be specific enough about the required path.

**Comment by jharris4** [comment]
@halt-hammerzeit Thanks! I'm starting to get the general picture here; once you stop using require('static-file') you're stepping into the realm of dynamic/async requires...

**Comment by sokra** [comment]
> dynamic/async

dynamic and async is not the same. Here you only mean only dynamic.

| source | dynamic | async |
|---|---|---|
| `require("./file")` | no | no |
| `System.import("./file")` | no | yes |
| `require("./dir/" + expr)` | yes | no |
| `System.import("./dir/" + expr)` | yes | yes |

**Comment by halt-hammerzeit** [comment]
@sokra is `System.import("./file")` supposed to replace the old `require.ensure([], ...)` syntax? Is it from Webpack 2 beta?

**Comment by sokra** [comment]
yep...

**Comment by jharris4** [comment]
Yeah, I'm looking forward to being able to use System.import so that I can stop using the following plugin to handle errors with async requires: https://github.com/richardscarrott/require-error-handler-webpack-plugin

I tried in vain to find any info about the ETA for the release of Webpack 2... Does anyone have any info about that?

**Comment by halt-hammerzeit** [comment]
@sokra I'm trying to implement HMR in my project and it works in this case:

```javascript
var locale = 'ru'

require('./international/ru.js')

if (module.hot)
{
	module.hot.accept(require.resolve('./international/' + locale + '.js'), function()
	{
		alert('hot reload locale')
	})
}
```

But it doesn't work in this case (when require is dynamic):

```javascript
var locale = 'ru'

require('./international/' + locale + '.js')

if (module.hot)
{
	module.hot.accept(require.resolve('./international/' + locale + '.js'), function()
	{
		alert('hot reload locale')
	})
}
```

Can HMR work in the second case with dynamic `require()`?

**Comment by jharris4** [comment]
@halt-hammerzeit You might want to use require.context here. Something like this:

```
var context = require.context("./international", true, /^\.\/.*\.js/);
var russianLocale = context('./ru.js');
if (module.hot) {
  module.hot.accept(context.id, function() {
    console.log("Module reloaded!");
    context = require.context("./internation", true, /^\.\/.*\.js/);
    russianLocale = context('./ru.js');
  });
}
```

**Comment by halt-hammerzeit** [comment]
@jharris4 You seem to have been diggin it deep down.
Thanks for the suggestion.
Seems that I walked in the wrong direction because I shouldn't be putting international translations into the main bundle to begin with: they must be loaded on demand.
So, I'm rewriting my code with statics only:

```javascript
// doesn't matter, just initialize it with something
let _locale = 'en'

...

		load_localized_messages_while_rendering_page: locale =>
		{
			_locale = locale

			switch (locale)
			{
				case 'ru':
					return new Promise(resolve =>
					{
						require.ensure(['./international/ru'], require =>
						{
							resolve(require('./international/ru'))
						})
					})

				default:
					return new Promise(resolve =>
					{
						require.ensure(['./international/en'], require =>
						{
							resolve(require('./international/en'))
						})
					})
			}
		}

...

		// `_development_` flag is needed here
		// to make sure that Webpack doesn't include
		// the whole `./international` folder into the `main` bundle
		// in production mode (because that's the sole point of code splitting)
		//
		if (_development_ && module.hot)
		{
			module.hot.accept(require.resolve('./international/' + _locale + '.js'), function()
			{
				rerender()
			})
		}
```
