### ISSUE TITLE
What does “publicPath” in webpack do?

### ISSUE THREAD

**Issue by jasonleft** [webpack/webpack#1791]
i realy watch docs carefully and many times, but i can't understand what does it mean.
> The output.path from the view of the Javascript / HTML page.

Can anybody explain this ? Better with a sample, Thx.

Here the [docs for publicPath](http://webpack.github.io/docs/configuration.html#output-publicpath).

**Comment by jasonleft** [comment]
Here the [docs for publicPath](http://webpack.github.io/docs/configuration.html#output-publicpath).

**Comment by bebraw** [comment]
Assuming you are using a CDN, you could make it point to the CDN root path. After that Webpack would look your assets from there.

**Comment by jasonleft** [comment]
@bebraw if some js under my src folder, another (such as jquery, underscore ...) use CDN, the publicPath points to the CDN root path. Then  how to find my src js file ?

**Comment by bebraw** [comment]
@jasonleft I just did a quick test. It seems to alter every asset path. Can you set up a little demo for me to study? It's easier to come up with a solution that way.

**Comment by cangku** [comment]
i have this question, only the img use the `publicPath`. Please give me some advice. (https://github.com/unpractice/webpack-question.git)[https://github.com/unpractice/webpack-question.git]

**Comment by bebraw** [comment]
@cangku Look into [html-webpack-plugin](https://www.npmjs.com/package/html-webpack-plugin). I think you can generate the paths you want using it. You may need to implement a little template of your own to get exactly what you want.

**Comment by jasonleft** [comment]
@bebraw 
##### Project Dir Look Like This: 
```
mkdir demo & cd demo
npm init
mkdir app & cd app
touch index.js
//add a picture to this dir (name vslogo.png)
cd ..
mkdir build & cd build
touch index.html
cd ..
touch webpack.config.js
```

##### And `index.html`:
```
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title></title>
</head>
<body>
	<script src="bundle.js"></script>
</body>
</html>
```

##### And `index.js`:
```
var app = document.createElement('div');
app.innerHTML = '<h1>Hello World APP</h1>';
document.body.appendChild(app);

var img = document.createElement('img');
img.src = require('./vslogo.png');
document.body.appendChild(img);
```

##### And `webpack.config.js`:
```
var path = require('path');
var HtmlWebpackPlugin = require('html-webpack-plugin');
var webpack = require('webpack');

var ROOT_PATH = path.resolve(__dirname);
var APP_PATH = path.resolve(ROOT_PATH, 'app');
var BUILD_PATH = path.resolve(ROOT_PATH, 'build');

module.exports = {
	entry: APP_PATH,
	output: {
		path: BUILD_PATH,
		filename: 'bundle.js',
		publicPath: 'assets/'
	},
	module: {
		loaders: [
			{test: /\.(png|jpg)$/, loader: 'url?limit=10'}
		],
	},
}
```

**Then visit index.html by http way. The bundle.js include a module:**
```
/* 1 */
/***/ function(module, exports, __webpack_require__) {

	module.exports = __webpack_require__.p + "471c6d744dd33627434556a807bb0898.png";

/***/ }
```

**`__webpack_require__.p` is `assets/`, so i wonder if any resource will add `__webpack_require__.p` prefix, and if this, assum my project has index.js and jquery.js from CDN, how i should write this publicPath property ? I am so confused .**

**Comment by bebraw** [comment]
@jasonleft Can you set up a standalone example for me to study? Where/how do you want to host your assets? Assuming it's through a CDN, you would put your CDN path to `publicPath`. See also https://stackoverflow.com/questions/28846814/what-does-publicpath-in-webpack-do .

**Comment by jasonleft** [comment]
@bebraw 
I had read this question on statckoverflow before. I prefer agree with **jhnns**'s viewport. **Sean** say that this property is both for dev server and in production env. I think this property help me in development phase, because the img and other assets are under my project folder. I can refer them by relative path. When the project is online release, we put img and other static assets on another server so i had to reference them by `xxdomain/assest/aaa.png`. Webpack use this property to add prefix to every asset. Do i understand that right ?

**Comment by jasonleft** [comment]
@bebraw 
Actually i want to know this property's use scenario, I am so sorry i know a little about github. I am not skillful github user, because i spend lot time on back-end. Thank you for patience!

**Comment by jasonleft** [comment]
@bebraw 
Eh.. I think i know this property already. This property indicates where to load assets when use webpack-dev-server. Because everything load from memory, and relative to `output.path`, not a real relative path.

**Comment by bebraw** [comment]
@jasonleft Is it clear enough to you now? Did you get your use case handled?

**Comment by jasonleft** [comment]
@bebraw Yes, i get it, Thx.

**Comment by wlxscn** [comment]
@jasonleft I want to know how you handle your case when only some  assets in cdn in production.Can you show your code.Thx.
