### ISSUE TITLE
ES6 export resolution behavior not respected properly

### ISSUE THREAD

**Issue by loganfsmyth** [webpack/webpack#1792]
Basically all from http://www.ecma-international.org/ecma-262/6.0/#sec-resolveexport

1. Star exports should not include 'default'
    ```
    // entry.js
    import def from './a';
    console.log(def);

    // a.js
    export * from './b';

    // b.js
    export default 'b-default';
    ```
    should log `undefined` because `export * from` only applies to named exports, not `default`. This is the main one on this list that seems like a problem, because it silently does the wrong thing, and users may accidentally rely on it.

2. Local exports take precedence over star exports.
    ```
    // entry.js
    import {foo} from './a';
    console.log(foo);

    // a.js
    export var foo = 'a-foo';
    export * from './b';

    // b.js
    export var foo = 'b-foo';
    ```
    should log `a-foo` since named exports take precedence over star exports. Currently it throws because the `export * from` tries to redefine the non-configurable property.

3. Local exports take precedence over indirect exports
    ```
    // entry.js
    import {foo} from './a';
    console.log(foo);

    // a.js
    export var foo = 'a-foo';
    export {foo} from './b';

    // b.js
    export var foo = 'b-foo';
    ```
    should log `a-foo` since named exports take precedence over indirect exports. Currently it throws because the `export * from` tries to redefine the non-configurable property.

4. Indirect exports take precedence over star exports.
    ```
    // entry.js
    import {foo} from './a';
    console.log(foo);

    // a.js
    export {foo} from './c';
    export * from './b';

    // b.js
    export var foo = 'b-foo';

    // c.js
    export var foo = 'c-foo';
    ```
    should log `c-foo` because indirect exports take precedence.

**Comment by IngwiePhoenix** [comment]
Isn’t that a Babel kinda related question, though? AFAIK, WebPack does not transform ES6 - or does webpack2? Because if that is the case, then I need to STFU and RTFM ^^.

**Comment by loganfsmyth** [comment]
Webpack 2 does, number 2/3/4 also exist in Babel too and are also filed over there, I just figured I'd make sure they got tracked here too.

**Comment by IngwiePhoenix** [comment]
Oh, alright. Thanks for the heads-up :)

**Comment by sokra** [comment]
Uhg... I'll try to fix those ~~edgecases~~ issues... ;)

**Comment by sokra** [comment]
@loganfsmyth could you please check if this test case covers all issues above?
https://github.com/webpack/webpack/blob/master/test/cases/parsing/harmony-export-precedence/index.js

**Comment by e-cloud** [comment]
when i try to upgrade acorn to the latest version, errors come up.

see the [code online with babel](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Ces2015-loose%2Ces2016%2Ces2017%2Clatest%2Cstage-0&code=export%20function%20a()%20%7B%20return%20%22a1%22%3B%20%7D%0Aexport%20%7B%20a%2C%20b%20%7D%20from%20%22.%2Fb%22%3B%0Aexport%20*%20from%20%22.%2Fc%22%3B%0Aexport%20%7B%20d%2C%20e%20%7D%20from%20%22.%2Fb%22%3B%0Aexport%20var%20e%20%3D%20%22e1%22%3B%0A)

it turns out that https://github.com/webpack/webpack/blob/master/test/cases/parsing/harmony-export-precedence/a.js has illegal syntax and that case doesn't cover the problem issued by @loganfsmyth.

**Comment by e-cloud** [comment]
I was wrong above, it covered the third case. However, the third case is illegal some how. See [the spec about import](http://www.ecma-international.org/ecma-262/6.0/#sec-imports-static-semantics-early-errors) @loganfsmyth

**Comment by e-cloud** [comment]
i was wrong above. It covered the third case. However, the third case is illegal. See [the spec about module semantics](http://www.ecma-international.org/ecma-262/6.0/#sec-module-semantics-static-semantics-early-errors) @loganfsmyth

**Comment by loganfsmyth** [comment]
Seems like that test just needs to have the names of the exports tweaked.

**Comment by e-cloud** [comment]
The key problem is what's the point of case 3 compared to case 2?

And the comment of case3 is a little misleading:
> should log `a-foo` since named exports take precedence over indirect exports. Currently it throws because the `export * from` tries to redefine the non-configurable property.

there is no `export * from` in case 3.

> Local exports take precedence over indirect exports

this rule is not what the spec indicates.

**Comment by loganfsmyth** [comment]
You're totally right. I was describing the order of operations defined in http://www.ecma-international.org/ecma-262/7.0/#sec-resolveexport, but that doesn't take into account that duplicate export names are already disallowed in http://www.ecma-international.org/ecma-262/7.0/#sec-module-semantics-static-semantics-early-errors via an early error.

**Comment by e-cloud** [comment]
One interesting thing is, when i dig down the problem with babel and typescript, they both don't behave as 100% as the spec requires.

see [my sample repo](https://github.com/e-cloud/module-export-override-semantic)
