### ISSUE TITLE
When `require.context` is used in a module that has been discovered through an entry in `resolve.modules`, the keys are duplicated.

### ISSUE THREAD

**Issue by cha0s** [webpack/webpack#17927]
# Bug report

**What is the current behavior?**

When `require.context` is used in a module that has been discovered through an entry in `resolve.modules`, the keys are duplicated.

**If the current behavior is a bug, please provide the steps to reproduce.**

To reproduce this issue:

1. Clone [this repository](https://github.com/cha0s/webpack-bug-require-context/tree/master)
2. `npm install`
3. `npm --silent start`

You will see the output:

```
require.context: [ './thing.js', 'test/things/thing.js' ]
```

**What is the expected behavior?**

the correct output would be:

```
require.context: [ './thing.js' ]
```

**Other relevant information:**
webpack version:  5.89.0
Node.js version:
Operating System:
Additional tools:

**Comment by cha0s** [comment]
The duplicates are created at https://github.com/webpack/webpack/blob/main/lib/dependencies/RequireContextPlugin.js#L133

If someone could explain what this code is meant to do, I could probably write a PR.

**Comment by alexander-akait** [comment]
I want to say it is expected, for example:
```js
const cache = {};

function importAll(r) {
  r.keys().forEach((key) => (cache[key] = r(key)));
}

importAll(require.context('../components/', true, /\.js$/));
// At build-time cache will be populated with all required modules.
```

It means you can import a module using `'./thing.js'` and `'test/things/thing.js'`, you can solve it - using regexp and exclude duplicate

**Comment by cha0s** [comment]
Thanks for the explanation!

There's something about it that just *feels wrong*. It definitely violated my expectation as a user. Perhaps a note in the documentation?

That being said, it's easy enough to work around with a `RegExp`. :)

**Comment by alexander-akait** [comment]
@cha0s I am fine with updating docs, do you want to send a PR? Thank you
