### ISSUE TITLE
Webpack2 support for import * as Name

### ISSUE THREAD

**Issue by Globegitter** [webpack/webpack#1794]
It seems that if we have a module that exports as follows:

```js
// changeState.js (more or less the same as navigateTo.js)
import {createAction} from 'reflux';

export const changeState = createAction({
  actionCategory: 'serverRequest',
  children: ['completed', 'failure']
});


// modules.js
export {changeState} from './changeState/changeState';
export {navigateTo} from './navigateTo/navigateTo';

// other-file.js
import * as Actions from 'modules.js';
```

And webpack 2 throws an error that Actions is undefined. Where-as with webpack 1.x using babel 6 to transpile the es6 imports/exports it all works fine.

**Comment by sokra** [comment]
Could you paste the complete exception with stack trace and more details of `other-file.js` and where and how `Actions` is used?

It does work fine in my test case https://github.com/webpack/webpack/blob/master/test/cases/parsing/harmony/index.js#L3

**Comment by Globegitter** [comment]
Just leaving for Christmas now to the airport, but I am seeing that https://github.com/webpack/webpack/blob/master/test/cases/parsing/harmony/index.js#L26 does not test for c: `export {c} from "./abc_c";` in that module. That is the only difference that I can see and our use works more like that.

Can try to add this to the test/show a more involved example as soon as I got some more time on hand.

**Comment by sokra** [comment]
You're right, it's not tested. I fixed the test, but it's still fine.

**Comment by Globegitter** [comment]
Ok will provide an example as soon as I am back on a working machine again - thanks for already looking into this.

**Comment by Globegitter** [comment]
Provided now an example here: #1840 

As a side note if I change `export {temp as d};` to `export const d = temp;` it works, but the first example also works with babel 6.
