### ISSUE TITLE
Documentation Suggestions

### ISSUE THREAD

**Issue by sanfordstaab** [webpack/webpack#1796]
I am having a pretty hard time building a boiler-plate webpack project that supports jsx, react, defines with source files in one directory and targets in another.

What would really help me (and I think others in my shoes) would be:
1) have the examples all include complete webpack.config.js files so I can just run webpack and webpack-dev-server in each example directory and watch it work.  Complete working examples would be so much better.  I did try downloading the master project and building the examples with build.js but these do not include webpack.config.js files in many cases.  The examples are simply too terse to really sink in what I need to understand.
2) Make some fairly complex, real-world webpack.config.js files and put copious comments in them with all the sources needed to run them.
3) The configuration docs themselves are quite sparse in areas and assume the reader knows more than he might.  Anyone can read JSON or JS but its what is happening underneath and how the data is interpreted that is important.  Cooking up some real-world example webpack.config.js files that use each/all/many of the config options with comments as to why and what they will do would really help as well.

 A section on how to debug loaders and plugins might be helpful - I know, this probably seems obvious or stupid to a seasoned node developer - but I am a newbie that is trying to learn the best path and minimize what I have to learn.  I would be glad to fix or improve the docs myself if I could figure out my own answers.  If I can be of any assistance please let me know.

Thanks for listening.  Hope this helps.

**Comment by bebraw** [comment]
Hi Sanford,

I've been developing material to address some of these issues. See [Developing with Webpack](http://survivejs.com/webpack_react/developing_with_webpack/), [Webpack and React](http://survivejs.com/webpack_react/webpack_and_react/), and [Building Kanban](http://survivejs.com/webpack_react/building_kanban/) chapters of my book. This work evolves continuously as I figure out ways to make it more accessible.

You can see the approach I cover in the book at [my boilerplate](https://github.com/survivejs/react-component-boilerplate). That shows how it all goes together.

Speaking of cooking up, earlier this year I wrote a [cookbook](https://christianalfoni.github.io/react-webpack-cookbook/) with Christian. That's something I'll likely revisit at some point and modernize.

If you have any comments about the book material, feel to pop by the [issue tracker](https://github.com/survivejs/webpack_react) or contact me directly through other means (gitter, email).

**Comment by IngwiePhoenix** [comment]
A _really_ good resource, if you have no idea where to go, is the Gitter chat. By no doubt, it is super supportive. Funnily, the heading says "no support" - but the actual opposite is happening. So if you are stuck, head into the Gitter. I am around fairly often and can answer most general questions. I just don't `react` very well to some ;).

But I can see what you mean. I might as well do something about it there, or jin my effords with @bebraw . I actually have an idea on how to do this: A github org that holds only WebPack samples and boilerplates. A repo of repos, of sorts. But this is still something lingering in my mind...

**Comment by mikechau** [comment]
Hi @sanfordstaab,

You can checkout my [webpack configs](https://github.com/mikechau/js-config-gen/tree/master/dist/react-web) here where everything is commented, it also provides links to the documentation as well.

There's a 'base' config, because I generate it statically and then extend it in my projects as seen in that examples subfolder.

If you need a full example, my projects typically end up looking something like [this](https://github.com/mikechau/js-config-gen/tree/master/demos/react-web).

I hope this helps you!

**Comment by sanfordstaab** [comment]
Thanks Mike - great stuff - put a link to these resources in the docs.
Sandy

Date: Thu, 24 Dec 2015 11:52:41 -0800

**Comment by sanfordstaab** [comment]
Good stuff.  Thanks.Sandy


Date: Wed, 23 Dec 2015 23:22:53 -0800

**Comment by sanfordstaab** [comment]
Excellent links - I'm all over it.  Thanks!
Sandy

Date: Wed, 23 Dec 2015 21:44:28 -0800

**Comment by IngwiePhoenix** [comment]
Dat emailtail. (:

**Comment by bebraw** [comment]
We are redeveloping the documentation [here](https://github.com/webpack/webpack.io). Feel free to check the status and pitch in.
