### ISSUE TITLE
Dynamic Imports that are marked external are hoisted

### ISSUE THREAD

**Issue by mohamedmansour** [webpack/webpack#17986]
Given this code:

```
// a.js
console.log('a');

// b.js
console.log('b');

// index.js
async function onButtonClick() {
  await import('./a.js') 
  await import('./b.js')
}
```

Where we mark `b.js` as external, the bundler prints this:

- dynamically imports "b" => console logs "b"
- User clicks on button
- dynamically imports "a" => console logs "a"

It should rather be:

- User clicks on button
- dynamically imports "a" => console logs "a"
- dynamically imports "b" => console logs "b"

Webpack hoists all external dynamic imports to the very top, not making it dynamic import. Which defeats its purpose.
```
{
  mode: "production",
  externalsType: 'module'
  externals: {
    /b.js/i,
  },
  output: {
    chunkFormat: 'module',
    chunkLoading: 'import',
    module: true
  }
}
```

It would be great if Webpack does not wrap native ESM imports with promises as well.

**Other relevant information:**
"webpack": "5.89.0",
"webpack-cli": "5.1.4",
"webpack-dev-server": "4.15.1",

**Comment by alexander-akait** [comment]
I want to say it is not a bug, just change `externalsType: 'module'` to `externalsType: "import",`.

I think we should add a new value for `externalsType` - `import-module` (maybe the best name) and set it by default for ES modules, i.e. keep `import(...)` and `import ... from "module";` for externals how they were written

**Comment by alexander-akait** [comment]
Also you can specify the type for an each item using https://webpack.js.org/configuration/externals/#string

**Comment by mohamedmansour** [comment]
Thank you @alexander-akait , that actually solves the hoisting, but it brings that hoisting still back to the main bundle into a function. For example, `index.ts` dynamically imports `lazy.ts`, and `lazy.ts` dynamically imports an external named `external.ts`. The definition of `externals` is hoisted to the main bundle `index.js`, instead it should have been inside `external.js`

I don't think we need another `externalsType`, why would someone who specifies `module` would want the imports hoisted for dynamic imports? That feels wrong. If they want it to be hoisted, then define them as `import "foo"` instead of `import("foo")`. It feels more like a bug. By definition in webpack docs: ` webpack will output ECMAScript module syntax whenever possible`

My recommendation would be to keep `externalsType` as `module` and don't transform it, just keep it in its place.

**Comment by alexander-akait** [comment]
@mohamedmansour No, it is not a bug, I can't find a discussion about it, but there was already a question about it here, there are scenarios when developers want to hoist (preload big modules in the first run), some want to load dynamically (lazy evaluation), especial in diffucult applications (you can improve perf in some cases, for example some modules can take a lot of time on import but you used them in rare cases and you can't change vendor library code), that is why I said, we need the another value to allow to keep dynamic import as dynamic and static as static. The same logic works for other values of the `externalsType` option.

**Comment by mohamedmansour** [comment]
It is actually a more serious bug when we move to `import` it breaks the natural ESM sequence since our web app is strictly ESM (esnext, modules). So we cannot use it. 

We need true browser platform ESM outputs. In the example below, `error-reporting.js` is marked external. And we get the error:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'log')
```

For example:

index.ts
```
import './error-reporting.js';
import 'app.js';
```

error-reporting.js
```
export function hookErrorReporting(name) {
  chrome.errorReporting.reportError(name);
}

window.chrome = {
  'log': () => console.log('logger');
} 
```

app.js
```
window.chrome.log();
```

**Comment by alexander-akait** [comment]
As I said above we just need a new value -  `import-module`, we can't keep them as is when you have `import` or `module`, because it will be breaking change and can break a lot of configuration

**Comment by mohamedmansour** [comment]
Bump (activity)

**Comment by xuri** [comment]
Thank you for your great work on webpack. Any version release plan for this feature?

**Comment by xuri** [comment]
Hi @alexander-akait, thank you for your great work on webpack. Any version release plan for this feature?

**Comment by alexander-akait** [comment]
I think I will do release next week, want to finish some fixes and CSS features
