### ISSUE TITLE
How does webpack search path?

### ISSUE THREAD

**Issue by ibufu** [webpack/webpack#1798]
//webpack.config.js
alias: {
     header: "./static/js/app/src/common/header.js"
  }

//entry.js
require("header");

Module not found: Error: Cannot resolve 'file' or 'directory' ./static/js/app/src/common/header.js in c:\demo\static\js\app\src\price

So,how import header.js correctly?

**Comment by bebraw** [comment]
@ibufu Can you try `path.join(__dirname, "./static/js/app/src/common/header.js")`? Just a hunch.

**Comment by ibufu** [comment]
@bebraw thank you very much!
