### ISSUE TITLE
New case for "__webpack_modules__[moduleId] is not a function" error with Module Federation

### ISSUE THREAD

**Issue by tqnghia1998** [webpack/webpack#17989]
# Bug report

**What is the current behavior?**
With a certain dependency graph, webpack module federation applications crash with error:
```
__webpack_modules__[moduleId] is not a function
or Cannot read properties of undefined (reading 'call')
```
This is indeed a known bug and had been fixed, but it happens again with module federation https://github.com/webpack/webpack/issues/11770
Issue describe:
* Folder structure:
```
/src
├── /components
│   ├── Button.js
├── /helpers
│   ├── index.js
├── /utils
│   ├── index.js
├── App.js
```
* Dependency graph:

![example remote app](https://github.com/webpack/webpack/assets/41647635/955ec8c3-7751-485e-a17e-f3ca847beb50)

* Bundle result: 

![chunking result](https://github.com/webpack/webpack/assets/41647635/a49bd137-2474-48ff-a5cc-a23ae184b5de)

* What is the problem:
`./src/utils/index.jsx` module is declared in `src_helpers_index_js` but required in `src_comopnent_Button_js`, so in runtime, it cannot find the module

Like I mentioned, this is a known issue and @sokra had fixed it in https://github.com/webpack/webpack/issues/11770. But he didn't handle for module federation case, because in this case, two federated modules `./RemoteApp` and `./helpers` are using the same runtime id

**If the current behavior is a bug, please provide the steps to reproduce.**
https://github.com/tqnghia1998/webpack-chunking-error-demo  (latest webpack version, just yarn install, then yarn start)

**What is the expected behavior?**
No runtime errors, `./src/utils/index.jsx` should be initialized when loading RemoteApp

**Other relevant information:**
Webpack version:  5.89.0
Node.js version: v18.12.1
Operating System: Mac 14.2.1
Additional tools: -

**Comment by alexander-akait** [comment]
PR welcome
