### ISSUE TITLE
Code splitting single JS files based on which functions are used by which parent components or files.

### ISSUE THREAD

**Issue by jchabotamica** [webpack/webpack#18007]
### Discussed in https://github.com/webpack/webpack/discussions/18006

<div type='discussions-op-text'>

<sup>Originally posted by **jchabotamica** January 25, 2024</sup>
I have been looking into ways to deeper code split my js files.  We are up to date with the latest versions of webpack, babel, etc.

We already do code splitting, but it seems to just do it on a file by file basis.  What I'd like to see is for it to further code split by which functions are used (not like pure tree shaking though because we have that too 😄 ).

As a visual:

src/index.ts
&nbsp;&nbsp;-- references function 1 from file A
&nbsp;&nbsp;--lazy load component A 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-- references function 2 from file A

I'm looking for this to split file A so that function 1 gets bundled with the main bundle, and function 2 gets bundles with the separate chunk which includes component A.

Also not, these are you using import/export syntax:
```
    //fileA
    export const function1 = () => {...};
    
    //index.ts
    import {function1} from 'fileA';
```
</div>

**Comment by alexander-akait** [comment]
Close in favor https://github.com/webpack/webpack/discussions/18006, please don't duplicate, it just slows down the help process
