### ISSUE TITLE
Exported object names not minified since 5.79

### ISSUE THREAD

**Issue by alexander-akait** [webpack/webpack#18013]
### Discussed in https://github.com/webpack/webpack/discussions/17988

<div type='discussions-op-text'>

<sup>Originally posted by **vjhebbar** January 21, 2024</sup>
Hello,

Since I updated to webpack 5.79+ in my project, bundle sizes have increased because some exported object names are not minified.

It turns out that this is due to those objects being destructured in modules where they are imported. 
Refactoring the code to remove the object destructuring minimizes the name again. 

Prior to 5.79, the names were minified regardless of the use of destructuring. 

Is this behavior aligned with #16941?

If this is not expected behavior, I'll share my configs and minimum reproducible code.

Looking forward to your thoughts and suggestions.

The latest version where the issue is reproducible is 5.90.
</div>

**Comment by alexander-akait** [comment]
Repo: https://github.com/vjhebbar/webpack579test

**Comment by vjhebbar** [comment]
The root is that canMangle is set to false in lib/dependencies/HarmonyImportDependencyParserPlugin.js. 
Should this flag be set according to the mangleExports optimization value?
