### ISSUE TITLE
System.import with concat option

### ISSUE THREAD

**Issue by teaegg** [webpack/webpack#1802]
Multi System.import support  nginx-concat-module liked uri?

```
http://example.com/??1.js,2.js,foo/3.js
```

``` javascript

// webpack.config.js
// [name].js instead of  [id].[name].js
// chunkFilename: '[name].js'

// Generate 3 chunks instead of 1.
// Promise.all(...);
System.import(['1.js', '2.js', 'foo/3.js']).then(...);
```

for saving disk space on a multi domain hosted server, and reusing modules.

**Comment by bebraw** [comment]
`System.import` was dropped. Use dynamic `import` and `Promise` based composition instead.
