### ISSUE TITLE
Warning appeared after updating node version

### ISSUE THREAD

**Issue by dushajni** [webpack/webpack#18026]
### Discussed in https://github.com/webpack/webpack/discussions/18022

<div type='discussions-op-text'>

<sup>Originally posted by **dushajni** January 29, 2024</sup>
Hi. 
I'm using Module federation on CRA react projects. I have one parent and one child app as micro frontend. After updating node version from v16.x.x to v20.11.0, removing node modules and running npm install, I started getting this warning in console for the parent app (local environment):

```
The generated code contains 'async/await' because this module is using "external script".
However, your target environment does not appear to support 'async/await'.
As a result, the code may not run as expected or may cause runtime errors.

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

WARNING in external "remote@http://localhost:3002/remoteEntry.js"
The generated code contains 'async/await' because this module is using "external script".
However, your target environment does not appear to support 'async/await'.
As a result, the code may not run as expected or may cause runtime errors.
webpack compiled with 1 warning
```

I'm importing external component like this:

`const ChildComponent = React.lazy(() => import('remote/ChildComponent'));`

I tried several things, tried  // eslint-disable-next-line above the line I just pasted, but warning is still present. 

Is there any way to solve this?</div>

**Comment by alexander-akait** [comment]
Please don't duplicate, close due https://github.com/webpack/webpack/issues/18026
