### ISSUE TITLE
Prefer webpack.config.js to webpack.config.ts (or to other extensions)

### ISSUE THREAD

**Issue by aspirisen** [webpack/webpack#1803]
I have webpack.config that was written on TypeScript and I compile it using tsc, but when I run tsc in this folder webpack prefers to use typescript version which it can't handle.

**Comment by raveclassic** [comment]
@aspirisen I solved similar issue by explicitly pointing to desired config with `--confg` cli argument.

Besides I believe it would be great to support TS configs the same way as ES6 is now supported by adding `babel` to config name: `webpack.babel.js`. Something like `webpack.typescript.ts`.

**Comment by aspirisen** [comment]
Ok, thanks a lot for the advice. Idea about `webpack.typescript.ts` it is good, but i suppose it has some difficulties in implementation, because in this file you can use some modules with `d.ts`. How to tell `tsc` to seach for the defenitions in some other directories.

**Comment by raveclassic** [comment]
@aspirisen tsc relies on `tsconfig.json` where you can define `files` or `filesGlob` (in the latest) section and list your `d.ts` there

**Comment by aspirisen** [comment]
@raveclassic true, but `tsconfig.json` can be not in the root or on the one level with `webpack.config.js`, also, there are could be more than one config file, for example for the server and for the front-end.

**Comment by Dynalon** [comment]
I got the same issue and I don't really think this issue should be labeled a  `question`. IMHO compilation of the `webpack.config.ts` file should not be handled by webpack but be left to the developer using tsc. But as long as webpack prefers the .ts extension over the .js extension, one has to pass the `--config webpack.config.js` manually.

**Comment by akre54** [comment]
The simple solution is to make sure `js` comes before `ts` in [`convert-argv.js`](https://github.com/webpack/webpack/blob/v1.12.14/bin/convert-argv.js#L31-L33). Right now the extensions are simply sorted by length, but it could special-case `.js` so that it is always the 0th element in the array.

Something like:

```js
Object.keys(interpret.extensions).sort(function(a, b) {
  return a === '.js' ? -1 : b === '.js' ? 1 : a.length - b.length;
});
```

**Comment by RefactorMan** [comment]
I still have this issue. It prefer .ts file ...

**Comment by cecilemuller** [comment]
Might as well stick to JS for the Webpack config If you use `module`:`esnext` in tsconfig.json (for preserving `import`/`export` statements for Webpack chunks and three shaking): either Webpack would have to force `ts-node` to run with `module`:`commonjs`, either it would need another tsconfig.

However, sticking to `require` and `module.exports` would work, but parts of `@types/webpack` types (like Rule and Configuration) only seem to work with `import`, not `require` statements unfortunately.
