### ISSUE TITLE
Lazily-loaded vendor bundle?

### ISSUE THREAD

**Issue by kawing-chiu** [webpack/webpack#1807]
I'm trying to combine the [two-explicit-vendor-trunk](https://github.com/webpack/webpack/tree/master/examples/two-explicit-vendor-chunks) example with code splitting. But cannot make it to work.

I have two pages (NOT real pages, it's an SPA using react and react-router):
- / : needs only `vendor.js`
- /d3 : needs both `vendor.js` and `d3.js`

The goal is: when visiting /, only `app.js` and `vendor.js` are loaded. When the user navigates to /d3, `d3.js` is loaded as needed. Here is how I try:

[webpack](https://github.com/kawing-chiu/flask-react-redux-example/blob/bc6b52b8eb4978a98561a83f3cf623b041c80a65/client/webpack_config/webpack.dev.config.js) [config](https://github.com/kawing-chiu/flask-react-redux-example/blob/bc6b52b8eb4978a98561a83f3cf623b041c80a65/client/webpack_config/common.config.js):

```
entry: { 
  vendor: [ 
    'react',
    'react-dom',
    'react-router',
    ...
  ],
  d3: [ 
    'd3',
  ],
  app: [
      './src/js/index',
  ],
},
plugins: [ 
  new webpack.optimize.CommonsChunkPlugin({
    name: 'vendor',
    minChunks: Infinity,
  }),
  new webpack.optimize.CommonsChunkPlugin({
    name: 'd3',
    minChunks: Infinity,
    // not sure about the async option here, but without it error occurs
    async: true,
  }),
  ...
],
```

[Router.jsx](https://github.com/kawing-chiu/flask-react-redux-example/blob/bc6b52b8eb4978a98561a83f3cf623b041c80a65/client/src/js/Router.jsx) (I'm using react-router):

```
export default (
  <Router history={createBrowserHistory()}>
      ...
      <Route path="d3" getComponent={(location, callback) => {
        require.ensure([], (require) => {
          callback(null, require('./pages/D3'));
        });
      }} />
      ...
  </Router>
);
```

This config doesn't work as expected since the `d3.js` bundle is generated but completely ignored by other bundles. And `d3.js` is also duplicated in chunk `1.1.js`. So how can I make this to work? I need this configuration because d3 is too large and slows down initial loading on home page a lot. Furthermore I need to do long-term caching on both `vendor.js` and `d3.js` so both must be split out as vendor chunks.

**Comment by kawing-chiu** [comment]
I've investigated this issue further and unfortunately come to the conclusion that this config is currently not possible with webpack (at least not with the CommonsChunkPlugin, maybe possible with some plugin that I'm not aware of?). Correct me if I'm wrong.

The CommonsChunkPlugin is only meant to be used on entry chunks. And from my test, `require.ensure` cannot be nested (i.e. first `require.ensure` on the page that use d3, then `require.ensure` d3 in that page). So I can find no way to extract vendor chunk from a non-entry chunk created by `require.ensure`.

So I think this issue should be an enhancement, not a question? @bebraw

**Comment by bebraw** [comment]
@kawing-chiu Yeah, converted to *enhancement*.

**Comment by antpaw** [comment]
maybe because you module name is 'd3' and the commonChunk is also named 'd3'? i think you should try to rename the commonChunk to 'd3-vendor' it should have no effect (only for the script tag)

**Comment by kawing-chiu** [comment]
@antpaw Hi. I've tested it. It doesn't work either. The main problem here is that the `CommonsChunkPlugin` doesn't work well with `require.ensure`. I've kind of made it to work in the last two days by using a combination of `CommonsChunkPlugin`, `require.ensure` and `bundle-loader`. But it's quite hacky.

**Comment by bardt** [comment]
@kawing-chiu could you please share your final config? I've come to the same issue and your solution would be really helpful, even if it is hacky.

**Comment by kawing-chiu** [comment]
@bardt Hi. Here are my configs: [webpack configs](https://github.com/kawing-chiu/flask-react-redux-example/tree/66dae874e4a28f1b023299a9aa03e02a2a904f6b/client/webpack_config),  and [the place](https://github.com/kawing-chiu/flask-react-redux-example/blob/66dae874e4a28f1b023299a9aa03e02a2a904f6b/client/src/js/Router.jsx) where d3 is lazily loaded. Specifically, please look for `CommonsChunkPlugin` in the file `common.config.js` under `webpack_config/`. And the `bundle` thing is from [bundle-loader](https://github.com/webpack/bundle-loader). Not sure this is the correct way of doing things. Hope it helps.

**Comment by windsome** [comment]
@kawing-chiu  any other method?

**Comment by tkrotoff** [comment]
Stupid bot, this should stay open
