### ISSUE TITLE
Over a 400% performance gain from distributed transformations

### ISSUE THREAD

**Issue by amireh** [webpack/webpack#1810]
Hi! I just wanted to share my findings on something I got really excited about, and hopefully get some ideas on how to take this further..

Our problem was the initial build times with webpack were becoming a show-stopper; the application currently has around 3.3k modules and on some machines, webpack would take over 70 seconds to just fire up. With the changes I'm about to describe, I managed to get the build on one machine (a normal 13" MacBook) down from 59 seconds to 24 seconds, then to 11 seconds after caching and using a DLL!

On another machine (a high-end desktop with 12 cores), the build went down from 38 seconds to 14 seconds and then 7 seconds after caching and using a DLL.

After profiling for a while (so many thanks for the awesome analyse tool, @sokra) - what I had noticed was that much of the time was spent in a) resolving, b) applying loaders. The second one really surprised me because we're only using the babel transformer and it really shouldn't take _that_ long.

The solution ended up as a simple plugin (see [happypack](https://github.com/amireh/happypack)) that moves the transformation responsibility from webpack to the plugin, which then uses multiple "threads" (node child processes really) for applying the transformations in a _semi-parallel_ fashion.

The reason I say semi-parallel is because there's no way to apply the transformations on _all_ the source files until webpack actually scrapes through the dependency graph. Currently, I'm doing the transformations on the `build-module` compiler hook. **Is there a better/different way to do this?**

The other thing I'm really curious about, but I doubt can be managed in such a simple way, is whether we can do **a similar thing with the resolving routine**? I remember from past experience (this isn't the first time I try to optimize webpack build times) that the resolving phase has a lot of meta-data tied to the (process-bound) cache and it might be very difficult to distribute it.

What do you guys think? I'm really curious to see if you would achieve similar results with your own builds using the plugin. Please share if interested!

Needless to say, thanks so much for webpack <3

**Comment by Dashed** [comment]
This sounds really interesting, especially parallelizing babel transforms.  @amireh Do you happen to have a sample repo that showcases these performance improvements? I'd be interested in trying out the benchmark on my machine.

**Comment by amireh** [comment]
@Dashed That would be a good idea, but the repository would need to have a lot of files for this to show proper effect. I'm actually not sure how well it behaves on smaller projects, that'd be nice to see.

I'll see what I can do, maybe find an existing open project to use (the one I did test on is closed-source, sadly.)

**Comment by amireh** [comment]
So, I got happypack to consume some of webpack's stock loaders (simple ones, at least) instead of custom transformers! It runs successfully with babel-loader, handlebars-loader, coffee-loader, react-i18nliner/loader and a few more!

I really wish webpack had encapsulated the application of loaders in a separate package, which could've been utilized by such a project. I'm keeping track of the support progress in https://github.com/amireh/happypack/pull/4 which as you'll see there's quite a lot to do. Perhaps when this is complete, webpack can integrate it?

Unfortunately, since we won't be able to share webpack internal objects like the compiler and compilation, things like `this._compiler` and `this._compilation` on the loader context will never be supported. :( I'm glad the docs say that these are hacky accesses, so that's not a big loss.

I'm adamant that we can apply such an approach to webpack's resolving process, but I don't have enough insight into that process yet. If/when we do, we can get builds for huge projects going in mere seconds rather than minutes.

If anyone's interested in helping out with this, please give a shout out.
