### ISSUE TITLE
@import CSS at-rule not always respected when determining order

### ISSUE THREAD

**Issue by Hypnosphi** [webpack/webpack#18111]
# Bug report

**What is the current behavior?**

Despite `a.css` being imported by `b.css`, it comes later in the resulting css file.

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/Hypnosphi/webpack-css-order

```
npm install
npm run build
```

**What is the expected behavior?**

`a.css` should go before `b.css` because it's imported. The [spec](https://drafts.csswg.org/css-cascade-5/#at-import) explicitly states that the imported rules should be treated as if they were written in place of the `@import` rule.

It works OK in 5.90.0. The issue is probably caused by https://github.com/webpack/webpack/pull/18009

**Other relevant information:**
webpack version:  5.90.3
Node.js version: 18.18.2
Operating System: macOS

**Comment by qxprakash** [comment]
I would like to work on this issue

**Comment by alexander-akait** [comment]
@Hypnosphi Anyway I recommend to avoid rely on CSS order when you have multiple `import ... from ...` and `@import`, there are a lot of limitations

**Comment by JSerFeng** [comment]
I believe the same problem exists in Rspack. I will look into this
