### ISSUE TITLE
Moving shared modules into common chunks

### ISSUE THREAD

**Issue by justinbach** [webpack/webpack#1812]
I'm working on converting a website from a RequireJS to a Webpack-based workflow, and I'm having trouble with the way that the CommonsChunkPlugin is distributing module dependencies. Ideally, each page on the website would serve a common file that includes the Webpack runtime and all shared dependencies, as well as a page-specific bundle.

Currently, all of the page-specific bundles use AMD-style definitions to list the modules they need to be available, which includes a reference to a 'shared' module. 

So page-a.js would be something like:

``` javascript
require(['shared', 'a1', 'a2']);
```

And page-b.js:

``` javascript
require(['shared', 'b1', 'b2']);
```

And finally, shared.js:

``` javascript
require(['s1', 's2']);
```

The good news is that Webpack is correctly putting pretty much all of the shared bundle into its own chunk. However, the problem that I'm running into is that almost every module (a1, a2, b1, b2, s1, s2 ...) has an AMD-declared dependency on jQuery, and Webpack is putting copies of jQuery into the page-specific chunks (both page-a and page-b), rather than the shared chunk. This means that as users visit multiple pages on the website, they have to re-download jQuery as part of each page-specific bundle's chunk, rather than as a single download that can be cached as part of the shared chunk.

All page-specific bundles include the shared bundle as a dependency.

What can I do to get jQuery into the shared chunk and out of the page-specific chunks? I've been using documentation and examples like https://github.com/webpack/webpack/tree/master/examples/multiple-entry-points as a point of reference without success; at best, I've ended up with copies of jQuery in both the page-specific chunks and the shared chunk.

**Comment by bebraw** [comment]
What does your configuration look like? I'm particularly interested in how you set up `entry` and plugins. 

Here's how I [split the bundles](http://survivejs.com/webpack_react/building_kanban/#splitting-app-and-vendor-bundles). Maybe that helps.

**Comment by justinbach** [comment]
Hi,

My entry points are configured by reading all files from a specified bundle-containing directory, as follows (assume that env.dev is set to false for these examples, though I don't think it should matter):

```
var bundles = {};
var bundleFiles = fs.readdirSync(bundlePath);

var devHostWithPort = 'http://' + env.hostname + ':' + env.port;

bundleFiles.map(function (f) {
    var filename = f.split('.')[0];
    var currentBundle;

    if (env.dev) {
        currentBundle = [];
        // make the bundle hot-reload aware
        currentBundle.push('webpack-dev-server/client?' + devHostWithPort);
        currentBundle.push('webpack/hot/only-dev-server');
        currentBundle.push(bundlePath + filename);
    } else {
        currentBundle = bundlePath + filename;
    }

    bundles[filename] = currentBundle;
});
```

The plugins are configured similarly:
```
var plugins;
var commonPlugins = [
    new CommonsChunkPlugin("common.js"),
    new DefinePlugin({
        'process.env': {
            'NODE_ENV': JSON.stringify(env.dev ? 'development' : 'production')
        }
    })
];

if (env.dev) {
    // Enable hot module replacement in development only
    plugins = commonPlugins.concat([
        new HotModuleReplacementPlugin(),
        new WriteFilePlugin()
    ]);
} else {
    // only minify on production
    plugins = commonPlugins.concat([
        new DedupePlugin(),
        new OccurrenceOrderPlugin(true),
        new UglifyJsPlugin({
            sourceMap: false,
            compress: {
                warnings: false
            }
        })
    ]);
}
```
And finally, everything is brought together in the webpack.config module's exports like so:
```
// Always load JS through Babel
var jsLoaders;
var commonJsLoaders = [
    'babel-loader?presets[]=es2015,presets[]=react'
];

if (env.dev) {
    // Load JS through the React hot loader only in development
    jsLoaders = ['react-hot'].concat(commonJsLoaders);
} else {
    jsLoaders = commonJsLoaders;
}

// Select dev tool based on environment
// On production: line-based mappings to original modules, slow but not too slow to build
// On dev: modules are evaled, transformed strings, fast to build
var devtool = (env.dev === true) ? 'eval' : 'cheap-module-source-map';

module.exports = {
    devtool: devtool,
    entry: bundles,
    devServer: {
        outputPath: __dirname + '/templates/javascript/dist/bundles/'
    },
    output: {
        path: __dirname + '/templates/javascript/dist/bundles/',
        publicPath: (env.dev ? devHostWithPort : '') + '/templates/javascript/dist/bundles/',
        filename: '[name].js',
        chunkFilename: "[id].[chunkhash].chunk.js",
        sourceMapFilename: '[file].map'
    },
    plugins: plugins,
    resolve: {
        extensions: ["", ".webpack.js", ".web.js", ".js", ".mtpl", ".jsx"],
        modulesDirectories: ['templates/javascript', 'node_modules'],
        alias: {
            "jquery": "vendor/jquery/dist/jquery.min",
            // more aliases
        }
    },
    module: {
        loaders: [
            {
                test: /\.jsx?$/,
                loaders: jsLoaders,
                exclude: /node_modules|vendor/
            },
            {
                test: /\.mtpl/,
                loader: 'mustache'
            },
            // more loaders
        ]
    }
};
```
Thanks for your assistance!

**Comment by bebraw** [comment]
Especially `new CommonsChunkPlugin("common.js")` is suspicious. Note that the signature looks like this:

```
new webpack.optimize.CommonsChunkPlugin(/* chunkName= */"vendor", /* filename= */"vendor.bundle.js")

// or
new webpack.optimize.CommonsChunkPlugin({
  names: ['vendor', 'manifest']
}),
```

Maybe it would make sense to set up an entry point that has **jquery** in it and then pass the entry point name **CommonsChunkPlugin**. I think that should give you the bundle you expect. It may take more elaborate setup to achieve what you want, but that feels like a starting point.

Go through [my guide](http://survivejs.com/webpack_react/building_kanban/#splitting-app-and-vendor-bundles) to understand how it works in more detail. That will help if you want to introduce hashes to filenames (client-side caching) and so on.

**Comment by justinbach** [comment]
I've created an entry point (shared.js) for all of the modules that should be shared across pages and have called it out specifically for use by the CommonsChunkPlugin:
```
new CommonsChunkPlugin("shared", "shared.js"),
```
And now it seems to be the case that the shared.js includes all of the modules that you'd expect it to (jQuery, etc), but they're also still being included in page-specific bundle chunks (which do have a traceable dependency on them, but I'd expect them to be provided by the shared chunk rather than included in both).

The guide was helpful for learning more about caching and clean builds -- thanks! -- but I'm still trying to figure out how to address the code-splitting problem under discussion.

**Comment by bebraw** [comment]
Did you set up `new webpack.optimize.DedupePlugin()`? It's a little strange jQuery ends up in your other chunks too. Perhaps the official docs can shed some light on that. Maybe we're missing something obvious here.

**Comment by justinbach** [comment]
Yes, I tried using the Dedupe plugin, but unfortunately, it didn't have the desired effect.

Here's something interesting, though; when I changed the shared entry point to use synchronous CommonJS-style imports, rather than the AMD syntax I shared in my first comment, jQuery (and the rest of the shared dependencies) ended up in just the shared entry point, which is the behavior that I was looking for from the beginning.

The only problem left to solve is that of synchronous vs asynchronous script delivery. Right now, in order for the JS to work as expected, I have to load the shared script synchronously, because the page-specific script depends on it in order to work. This has implications for page loading time, as synchronously-loaded scripts incur a performance penalty.

Ideally, I'd like to asynchronously load all shared modules (using the shared entry point) and then asynchronously load all page-specific modules (using the page-specific entry point) once  the shared modules are loaded. I tried setting the 'async: true' option on CommonsChunkPlugin, but that gets me back to having all page-specific bundles include shared dependencies like jQuery. I could use a lightweight script loader to asynchronously load both scripts in the desired order, but that seems unnecessary given that Webpack is great at asynchronously loading resources when they're needed.

Are there best practices for addressing this problem?

**Comment by bebraw** [comment]
See [code splitting](https://webpack.github.io/docs/code-splitting.html). I think `require.ensure` might work for you.

**Comment by justinbach** [comment]
The example on the  [code splitting](https://webpack.github.io/docs/code-splitting.html) page that illustrates [splitting app and vendor code] (https://webpack.github.io/docs/code-splitting.html#split-app-and-vendor-code) loads both scripts synchronously (vendor plus runtime followed by app code), which I'd like to avoid. Is there any way around that?

**Comment by bebraw** [comment]
@justinbach Would setting `async` attribute for `script` work? Maybe we can solve this on browser level.

**Comment by justinbach** [comment]
@bebraw Setting async on both <script> tags would create a race condition; the page-specific bundle relies on the Webpack runtime and shared dependencies in the shared bundle, so if it finishes loading before the shared bundle, JS errors would result. Setting async only on the page-specific bundle would work, but is less than ideal, as the shared bundle contains lots of shared module code and would still have to be loaded synchronously.

The ideal scenario would be one in which the shared bundle contains only the Webpack runtime and the __webpack_require__ call to load the shared bundle's chunk asynchronously, and the page-specific bundle contains only the __webpack_require__ call that loads the page-specific bundle's chunk asynchronously (but waits until the shared bundle's chunk has been loaded to resolve shared dependencies). If we had those bundles, we could load them using script tags synchronously (which would be very fast, because they wouldn't contain the module contents -- just the async loading code) or even inject them directly into an inline script tag.

It sounds to me like I'm trying to solve a problem similar to the one described here:

http://stackoverflow.com/questions/33001985/webpack-with-small-initial-script-and-async-loading-of-all-other-scripts

Based on the answer to that question and the resulting comment thread, it's not clear to me that it was ever resolved.

Thanks again for your help in trying to figure this out!

**Comment by bebraw** [comment]
Based on that I would say you'll want to avoid multiple entries and try to rely on `require.ensure`. As the thread states, each entry corresponds to a `script` entry and that's exactly what we don't want here.

**Comment by justinbach** [comment]
Hmm, I just tried getting rid of the shared entry point and using require.ensure to load the shared dependencies before the page-specific ones, resulting in page-specific bundles like the following:
```javascript
require.ensure(['shared'], function(require) {
    require('a1');
    require('a2');
});
```
and now Webpack is putting a copy of jQuery into every chunk again, instead of just one copy in a single shared chunk. 

This happens both with and without the CommonsChunkPlugin configured for the shared bundle.

**Comment by bebraw** [comment]
D'oh. So we ended up back where we started from... Maybe we're missing something obvious.

**Comment by justinbach** [comment]
Okay, so I've finally got this functioning more or less as desired, but I can't say that it's entirely clear to me why the solution that I've arrived at is working. 

I'm still using `require.ensure` to load the shared bundle into page-specific bundles as described in my last comment.

In addition, I've created a new entry point called `allBundles.js` that uses CJS `require()` calls to load in every page-specific bundle:
```javascript
// this isn't actually used as an entry point anywhere, but it seems to help Webpack 
// understand how code is shared, as "a" and "b" share children
require('page-a');
require('page-b');
```

Finally, I modified my CommonsChunkPlugin usage as follows:
```javascript
var plugins = [
    new CommonsChunkPlugin({
        name: 'runtime',
        filename: 'runtime.js'
    }),
    new CommonsChunkPlugin({
        async: true
    }),
    // other plugins
];
```
This results in the creation of `runtime.js`, which contains just the Webpack runtime, and page-specific JS files that contain the `__webpack_require__` calls required to load the shared chunks and page-specific chunks asynchronously as needed. Thankfully, shared dependencies like jQuery no longer appear in page-specific chunks.

I can't pretend to understand why this works, but without both the new `allBundles.js` file and a second async CommonsChunkPlugin (rather than a single async runtime.js ComonsChunkPlugin), I end up with a copy of jQuery in every page-specific bundle, which is the problem I was initially trying to solve.

It would be great if someone more experienced with Webpack than me could explain why this is working and my previous approaches were not...

**Comment by bebraw** [comment]
I guess we'll have to wait for the author to pop in to get a better idea of the behavior. :+1:

**Comment by KpjComp** [comment]
I'm having the same problems with repeated code..

Seems to work fine if using Entry Points, but using "require.ensure", I get say JQuery / bluebird in multiple chunks..  :-(

**Comment by maysale01** [comment]
@KpjComp Just recently encountered this. Any updates?

**Comment by sokra** [comment]
CommonsChunkPlugin in async mode solves this.
