### ISSUE TITLE
Installing to a different $NODE_PATH gives "Cannot resolve module" error for loaders

### ISSUE THREAD

**Issue by dcosson** [webpack/webpack#1813]
I expected the loaders to work the same way as `require()` and check for node modules in the env var $NODE_PATH if it's set.

In my `webpack.config.js`:

```
var config = {
  module: {
    loaders: {
      test: /\.js$/,
      loader: 'babel',
    }
  }
}
module.exports = config;
```

This doesn't work if I npm install to a different NODE_PATH instead of the local ./node_modules. It does work if I set the loader name to an absolute path, e.g.  `loader: process.env.NODE_PATH + '/babel-loader'`.

Can the loaders be updated to check NODE_PATH when specified by name?

**Comment by mzgoddard** [comment]
You're looking for the [resolveLoaders](http://webpack.github.io/docs/configuration.html#resolveloader) option.

**Comment by IngwiePhoenix** [comment]
You can add `process.env.NODE_PATH` to your config.

Adding it to `resolve.root` will cause this to be a top-level search-point for modules (likely what you want).
Adding it to `resolve.modulesDirectories` would include a folder name for each subsequent search (probably not what you want, but mentioned for completeness).

So, in your case, I'd probably do:

```javascript
module.exports = {
  resolve: {
    root: [ process.env.NODE_PATH || "node_modules" ]
  }
}
```

**Comment by bebraw** [comment]
Closing given this was answered.
