### ISSUE TITLE
Can't import child_process

### ISSUE THREAD

**Issue by taxuexunshang** [webpack/webpack#18141]
Hello, I want to use child_process to invoke an exe file in a React + Electron Project. But some error happend when I import child_process module.
The first is  `Module not found: Error: Can't resolve 'child_process'`
I solve it by add 
`"browser": {
    "child_process": false 
 }` to `package.json` ,It package  successfully.
But when I click a button which use child_process  invoke an external exe.  It will throw a second error `spawn() is not a function`.
I have tried
- [ x ]  change `import { spawn } from 'child_process'` to `const { spawn } = require('child_process')`

The project sorece code in [electron-react-boilerplate](https://github.com/electron-react-boilerplate/electron-react-boilerplate), I just add a button to test child_process spawn() invoke an exe.
Please help me, thanks~

**Comment by alexander-akait** [comment]
Please don't duplicate, close in favor https://github.com/webpack/webpack/discussions/18142
