### ISSUE TITLE
Template strings and arrow functions

### ISSUE THREAD

**Issue by klimashkin** [webpack/webpack#1814]
Hello! Is there any plans to support template literals and arrow functions in dynamic requires? Maybe in webpack2?
For example, this doesn't work, only if replace arrow with normal function and template string with classic concatenation

``` javascript
export default _.transform(langs, (result, lang) => {
   result[lang] = require(`./${lang}/index.js`).default;
})
```

ES6 is supported more and more, so some specific applications don't need to be compiled in ES5

**Comment by klimashkin** [comment]
And rest operator inside function fails build too

**Comment by ddemyanov** [comment]
+1

**Comment by th0r** [comment]
+1

**Comment by fenderz** [comment]
+1

**Comment by le0nik** [comment]
+1

**Comment by velther** [comment]
+1

**Comment by TheLarkInn** [comment]
@sokra is this still an issue in later beta builds? Would anyone participating like to verify this?

**Comment by sokra** [comment]
Arrow function should work. Template strings don't work (if not transpired by babel)

**Comment by bebraw** [comment]
Is this relevant still?

**Comment by Kovensky** [comment]
Both are supported now (arrows more recently, not sure it got into a release yet).

**Comment by TheLarkInn** [comment]
It is as.of RC.2 Specifically in AMDDependencyBlock, technically anywhere 'getFunctionExpression' is called
