### ISSUE TITLE
Working with node-archiver

### ISSUE THREAD

**Issue by cloudy064** [webpack/webpack#1815]
When I developed my app with webpack, I found that it can't work well with node-archiver, reporting an error as follows:
```
[1333:1229/113633:ERROR:nw_shell.cc(336)] Error: append: input source must be valid Stream or Buffer instance
    at Archiver.append (file:///Users/cloudy/workspaces/javascript/push_message/bundle.js:22006:25)
    at Object.<anonymous> (file:///Users/cloudy/workspaces/javascript/push_message/bundle.js:963:10)
    at __webpack_require__ (file:///Users/cloudy/workspaces/javascript/push_message/bundle.js:20:30)
    at Object.<anonymous> (file:///Users/cloudy/workspaces/javascript/push_message/bundle.js:47:19)
    at __webpack_require__ (file:///Users/cloudy/workspaces/javascript/push_message/bundle.js:20:30)
```
It fails on instanceof Stream which returns false.

**Comment by bebraw** [comment]
Can you provide more information? What kind of an application are you trying to build?

**Comment by cloudy064** [comment]
Just a simple tool for packing some images into a zip file. I developed this with react.js, nw.js and webpack. Oh, it's a desktop application. For the moment, I solved this problem by adding the node-archiver as an external module.
```json
    externals: {
        "archiver": "archiver"
    },
``` 
I inspected the bundle.js just now. Maybe, pasting some code will help.
```javascript
// my code
archive
  .append(fs.createReadStream(file1), { name: 'file1.txt' })
  .append(fs.createReadStream(file2), { name: 'file2.txt' })
  .finalize();
}
```

```javascript
// definition of append
	Archiver.prototype.append = function(source, data) {
        //some codes here...
	  source = util.normalizeInputSource(source);
        //some codes here...
  }
```

```javascript
// definition of normalizeInputSource
	var util = module.exports = {};

	util.isStream = function(source) {
	  return source instanceof Stream; // Should have returned true here.
	};

	util.normalizeInputSource = function(source) {
	  if (source === null) {
	    return new Buffer(0);
	  } else if (typeof source === 'string') {
	    return new Buffer(source);
	  } else if (util.isStream(source) && !source._readableState) { 
	    var normalized = new PassThrough();
	    source.pipe(normalized);

	    return normalized;
	  }

	  return source;
	};
```

**Comment by bebraw** [comment]
That's puzzling. Can you figure out the type of `source`? Why would it be something different when bundled?

**Comment by cloudy064** [comment]
I print the type of `source` and I got an `Object`. So I try to figure out the prototype of Stream, and noting different. Weird~

**Comment by cloudy064** [comment]
The type of `source` is `ReadStream`. Its base type is `Readable`. And the base type of `Readable` is `Stream`.

**Comment by bebraw** [comment]
It's hard to say why it's different. Esp. that `I print the type of source and I got an Object.` sounds strange. Why would it be `Object`?

**Comment by cloudy064** [comment]
Well, maybe I have found the problem. I print the prototype of the `Stream` exported by `require("stream")` and the prototype of the `Stream` in `bundle.js`. There are some differences between them.
![image](https://cloud.githubusercontent.com/assets/11996961/12038019/6f76da06-ae8f-11e5-93a7-1119219d0f8e.png)
Chances are that I used `stream-browserify` modules of multiple versions. But more time is needed for the real problem.

**Comment by bebraw** [comment]
Yeah, a difference like that would be enough and would explain why the test fails. You would have to dig deeper to understand where that initial instance comes from.

**Comment by VikramTiwari** [comment]
Hey, @cloudy064 did you find a solution to this?

**Comment by lwx475784** [comment]
Hey, I fount a way to fix it, turn your stream obj to PassThrough and use it,  like this:
`const source = new PassThrough()
  stream.pipe(source)`
it works for me!
