### ISSUE TITLE
License scan badge shown as failing

### ISSUE THREAD

**Issue by matkoniecz** [webpack/webpack#18163]
# Bug report

**What is the current behavior?**

https://github.com/webpack/webpack - license badge is self-reported as failing

**If the current behavior is a bug, please provide the steps to reproduce.**

Open https://github.com/webpack/webpack

**What is the expected behavior?**

This badge is not present or not failing

**Other relevant information:**

https://app.fossa.io/projects/git%2Bgithub.com%2Fwebpack%2Fwebpack/refs/branch/master/4972fd8bd6790eb1ee45602c35f38b7f79849b61/preview is linked from badge, showing "7 Flagged License Issues"

Any details are loginwalled.

The linked page also claims that webpack has 11 abandoned dependencies, 67 outdated and 15 vulnerabilities.

webpack version:  latest ( https://github.com/webpack/webpack/commit/6842c9a2c9b70e760143188ffa5baa19a72799cb )
Node.js version: none
Operating System: irrelevant
Additional tools: none

**Comment by Ark898** [comment]
I tried this same scan on FOSSA, which shows license scan-passing.

**Comment by matkoniecz** [comment]
What you see at https://github.com/webpack/webpack ?

![screen](https://github.com/webpack/webpack/assets/899988/5924dbfd-0c14-4bdb-9d96-217c39293aa2)

For reference, https://app.fossa.io/projects/git%2Bgithub.com%2Fwebpack%2Fwebpack/refs/branch/master/4972fd8bd6790eb1ee45602c35f38b7f79849b61/preview appears to me as

![screen01](https://github.com/webpack/webpack/assets/899988/becc277f-98cf-49b2-9171-cec3223b8c98)

**Comment by Ark898** [comment]
![Screenshot (151)](https://github.com/webpack/webpack/assets/137332440/113c60ad-73c6-4b35-b7ec-725748a2441a)

**Comment by matkoniecz** [comment]
I see you are logged in.

What is displayed when you log out - or in a private mode?

**Comment by matkoniecz** [comment]
Also, it seems you have a different link. Can you paste it?

https://app.fossa.io/projects/git%2Bgithub.com%2Fwebpack%2Fwebpack/refs/branch/master/4972fd8bd6790eb1ee45602c35f38b7f79849b61/preview  is target of readme badge for me.

Also, how you see readme badges? Are any failing?

**Comment by Ark898** [comment]
Yeah, I tried using a different link https://app.fossa.com/projects/git%2Bgithub.com%2FArk898%2Fwebpack/refs/branch/main/6842c9a2c9b70e760143188ffa5baa19a72799cb. For your link, it shows license scan-failing. Might need to reinstall or update the template I guess, because it is showing alright to me.

**Comment by matkoniecz** [comment]
> Might need to reinstall 

Reinstall what? I am checking on website, following what is linked in the readme.

**Comment by Ark898** [comment]
Reinstall/Update the template u are using for showing css in the readme.

**Comment by alexander-akait** [comment]
Let's remove this badge, it is not useful

**Comment by matkoniecz** [comment]
Looks like https://github.com/webpack/webpack/tree/main?tab=readme-ov-file#license is also affected

**Comment by matkoniecz** [comment]
Stale bot hiding issues are deeply obnoxious, I guess I should not bother with reporting anything broken in webpack.
