### ISSUE TITLE
failed to import ffmpeg-core.js

### ISSUE THREAD

**Issue by nareshallakonda** [webpack/webpack#18169]
./node_modules/@ffmpeg/ffmpeg/dist/umd/ffmpeg.js 55:4
Module parse failed: Unexpected character '#' (55:4)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   new Error("failed to import ffmpeg-core.js");
|   class i {
>     #e = null;
|     #t = {};
|     #s = {};

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
