### ISSUE TITLE
Progress callback for code split / async require.

### ISSUE THREAD

**Issue by DylanVann** [webpack/webpack#1817]
There should be a way to show the progress during an asynchronous require.

It could be the same interface as XMLHttpRequest progress.

``` js
require.ensure(["module-a", "module-b"], {
    progress: function(oEvent) {
        if (oEvent.lengthComputable) {
            var percentComplete = oEvent.loaded / oEvent.total;
            // ...
        } else {
            // Unable to compute progress information since the total size is unknown
        }
    },
    load: function(require) {
        var a = require("module-a");
        // ...
    }
});
```

Not sure about this syntax, but the feature would be helpful.

**Comment by brandondurham** [comment]
Oh how I would love this.

**Comment by YikaJ** [comment]
I want this feature!!!

**Comment by suhaotian** [comment]
:+1:

**Comment by geekingin** [comment]
This is a very helpful feature! It will help us build a web app with loading page with webpack handling all the assets, no need for loadImg/loadCSS/loadScript any more!

**Comment by zhiqunq** [comment]
The weak-weak question，how is it going？
