### ISSUE TITLE
Custom loader fails to resolve files

### ISSUE THREAD

**Issue by brandon-arnold** [webpack/webpack#1818]
Hi all,

I'm confused why [my loader](https://www.npmjs.com/package/strip-json-comments-loader) is failing to resolve CSS import paths. At least, failing to resolve them consistently with other loaders in the pipeline.

I have only altered slightly this [webpack config from react-starter-kit](https://github.com/kriasoft/react-starter-kit/blob/master/tools/webpack.config.js). The module loaders in the ```/\.scss$/``` section have my loader earliest, viz:

```javascript
//module.loaders: [...
{
  test: /\.scss$/,
  loaders: [
    'isomorphic-style-loader',
    'css-loader?' + (DEBUG ? 'sourceMap&' : 'minimize&') +
    'modules&localIdentName=[name]_[local]_[hash:base64:3]',
    'postcss-loader',
    'strip-json-comments-loader',
  ],
}, //...
```

Without ```strip-json-comments-loader```, the module imports files correctly relative to the importing document. With it, they are relative to the shell root. After ```npm run build```:

```bash
    ERROR in ./~/css-loader?sourceMap&modules&localIdentName=[name]_[local]_[hash:base64:3]!./~/postcss-loader!./~/strip-json-comments-loader!./src/components/App/App.scss
    Module build failed: Error: C:\path\to\project\node_modules\strip-json-comments-loader\index.js!C:\path\to\project\src\components\App\App.scss:3:1: Failed to find '../../../node_modules/normalize.css/normalize.css' from C:\path\to\project
        in [
            C:\path\to\project\node_modules\strip-json-comments-loader\index.js!C:\path\to\project\src\components\App
        ]
        at C:\path\to\project\node_modules\strip-json-comments-loader\index.js!C:\path\to\project\src\components\App\App.scss:3:1
```

I thought loaders did not have to "know" about the source path, as they're little more than a function transforming an input stream.

**Comment by dfrankland** [comment]
This is fixed by adding the `?parser=postcss-scss` option to `postcss-loader`: https://github.com/jonathantneal/precss/issues/49#issuecomment-169146317

**Comment by brandon-arnold** [comment]
Thanks. I'll continue this at the postcss-scss or PreCSS projects; continued [here](https://github.com/jonathantneal/precss/issues/49#issuecomment-169462233).
