### ISSUE TITLE
failed to import ffmpeg-core.js

### ISSUE THREAD

**Issue by nareshallakonda** [webpack/webpack#18183]
when i install ffmpeg and import { createFFmpeg, fetchFile } from '@ffmpeg/ffmpeg'; 
import like above , its getting like this new issue .! 

./node_modules/@ffmpeg/ffmpeg/dist/umd/ffmpeg.js 55:4
Module parse failed: Unexpected character '#' (55:4)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   new Error("failed to import ffmpeg-core.js");
|   class i {
>     #e = null;
|     #t = {};
|     #s = {};

**Comment by alexander-akait** [comment]
Please update webpack to the latest version

**Comment by nareshallakonda** [comment]
> Please update webpack to the latest version

webpack updated latest version but getting same issue !
