### ISSUE TITLE
The word "loader" doesn't make sense for describing what you call loaders

### ISSUE THREAD

**Issue by fresheneesz** [webpack/webpack#182]
I'm reading about webpack "loaders" and I wanted to point out that it is a very confusing term to use for what are essential code transforms. "Loader" is already a term used to describe code used to "load" javascript from the network. These are things like [curl](https://github.com/cujojs/curl). The functionality described in the documentation as "loaders" has absolutely nothing to do with loading at all. This is very confusing.

A much more informative and understandable word to use would be "transform". Mathematical transforms is one example of where an analogous construct uses that term. "Preprocessor" would also make more sense.

**Comment by montogeek** [comment]
This is going to change in 2?

**Comment by bebraw** [comment]
@sokra Any thoughts on this?

Given `loaders` have been established as a term, replacing it with yet another might lead to confusion (invalidates lots of existing material). But if it was replaced, I would use `transforms` myself and alias it to `loaders`. Then drop `loaders` in webpack 3.

**Comment by jhnns** [comment]
I think we should close this one. The eco system has already evolved too far to change this. After all, the term loader is not too uncommon (The original CommonJS spec and AMD used it).

**Comment by montogeek** [comment]
@bebraw I like your idea, Webpack 3 could replace it entirely, after all is a mayor version update

**Comment by bebraw** [comment]
Let's close and possibly revisit in webpack 3. As mentioned in the thread, the current terms, even if not perfect, have been established.
