### ISSUE TITLE
How to access current module path inside NormalModuleReplacementPlugin in webpack?

### ISSUE THREAD

**Issue by raveclassic** [webpack/webpack#1820]
I am trying to extend/reimplement `webpack.NormalModuleReplacementPlugin` to allow using filter callback instead of RegExp.

I am able to inject into `normal-module-factory/after-resolve` hook and to replace resolved module path with the one I need. But the problem is that I also need to support "requiring of replaced module inside of replacing".

I mean that if module `A` is being replaced with `B`, then module `B` should be able to require module `A` without circular loop. (it is very similar to calling `super` inside of a subclass)

Here's an example:

``` javascript
//module A: ./core/A.jsx
export default class A extends React.Component {
 render() {
  return <div>A</div>;
 }
}

//module B which replaces module A: ./override/A.jsx
import A from '../core/A.jsx'; //here's a circular loop as now we are requiring ourself
export default class A extends React.Component {
 render() {
  return (
   <div><A/>is overridden!</div>
  );
 }
}
```

**And here is the question:** is there any way to access path of current module trying to require module `A` to check if it is equal to the path of the module `B` and skip replacement?

All I have found is `result.context` property inside `after-resolve` callback, but it's only a directory containing current module, not the module itself.

If I'm using wrong plugin hook, what should I use then? I tried to dig into `ResolverPlugin` and `file` hook but I believe it's not the proper way as long as I don't need to resolve anything but only substitute the module.

TIA

**Comment by bebraw** [comment]
Hi,

Did you manage to progress with this? I expect the API might be a little different with webpack 2.

**Comment by raveclassic** [comment]
@bebraw Nope, I ended up with checking `result.context`. It turned out to be enough.
I haven't looked on webpack2 yet - waiting for release.

**Comment by raveclassic** [comment]
Webpack 2 is officially released so I'm closing this.
