### ISSUE TITLE
with babel 6 async router is wrong

### ISSUE THREAD

**Issue by zhoujianlin8** [webpack/webpack#1821]
export default {
  path: 'ok',
  getComponent(location, cb) {
    require.ensure([], (require) => {
      cb(null, require('./index'))
    })
  }
}

babel 5 is  ok

but the babel 6  not exec render

**Comment by IngwiePhoenix** [comment]
This is rather sparse. What exactly is it?

This is rather babel@6 specific, but:
- Did you add the plugins/presets to transpile this?
- Did you run your code through the babel command line tool and look at the ES5 that it generates? you u could use that to predict behaviour of your code.

If I take your code up here for instance, it produces:

```javascript
// $ babel --presets es2015 t.js
'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = {
  path: 'ok',
  getComponent: function getComponent(location, cb) {
    require.ensure([], function (require) {
      cb(null, require('./index'));
    });
  }
};
```

**Comment by zhoujianlin8** [comment]
$ babel --presets es2015 t.js

i have add it

https://phabricator.babeljs.io/T6901

**Comment by bebraw** [comment]
As this is Babel 6 specific, please push the question upstream. :+1:
