### ISSUE TITLE
Parser Plugin: Questions about Dependencies and Templates

### ISSUE THREAD

**Issue by IngwiePhoenix** [webpack/webpack#1822]
hey @sokra :)
I know what kinda days it currently is in Germany - I mean, I live here too - so I decided to take my questions from Gitter and properly form an issue ticket of them instead. Hopefully you can get back to me.

So as you know I am working on a plugin. To detail things a bit, I am working on bringing [Uniter](https://github.com/uniter) to WebPack. In short, Uniter is a set of tools and libraries, that if used together, let you transpile PHP into JavaScript. Me and @asmblah have been putting our heads together for this since a while, and recently I was able to bring the first prototype to compile a basic app - it also works with the standard `require` already. So, in theory, a basic PHP app could be compiled with WebPack. Which is, lightly said, amazing.

But there are a few things that I am stuck on. The main focus of this plugin is the Parser plugins. Uniter also has an architecture to allow me to transpile specific AST nodes as I please. For instance, I have a custom transpile for `require` statements. The step for Uniter's transpiler to run is within a loader.

Once all the loaders were run and WebPack puts itself to work, I attach a few `call` expression plugins, such as `parser.plugin("call __uniter_require__", f(){});`. This way, I can tell WebPack which parts of the transpiled code is a module and which is not - and, properly register them.

PHP has a few ways of handling inclusion or addition of files to a run:

- `require` and `require_once`
- `include` and `include_once`
- `use Name\space\s;`

The `_once` functions is what you would get regularily in Node or WebPack. A file is loaded once, the actions cached, and on subsequent calls, the cache is returned. Whilst the non-`_once` variants always do a fresh request. The best way to implement this is to clear the module off the webpack cache, and re-run the code. Basically:

```javascript
delete __require_require__.c[id];
var val = __require_require__(id);
```

So, here is the question number one:
For the case of a non-`_once` call, I would create a new Dependency class: `UniterRequireOnceDependency`. This, I could pass the whole range for the entire call. But, from within the dependency, how could I get a module ID? I know that for a regular require, I could just use `LocalModule` (or was it `LocalDependency`? im too lazy to check my code ;)). But since for this case, I actually need the module ID to construct the delete-and-require code. So how do I get it?

One option I see is having a Dependency to track the range of the statement, i.e.:

```
__uniter_require_once__("./foo.php");
```

The dependency would also get an argument for just the module request, that I could store as well. In this case, that would be `"./foo.php"`.

Then I would need to make a Template, which would transform the entire statement accordingly. I know that Templates that work with classes like `CommonJsRequireDependency` have access to the module and it's ID. I didn't figure out when and how it would get it, but I know that it does.

So, what is the best way to handle this case?

Now, that's that. But there still is `use`. I can simply re-use the same code from the previous one to implement the difference between `include` and `require` (the one causes an error, the one just emits a warning but doesnt shut down). I can resolve namespaces to a specification file, similar to a `package.json` and a folder structure.

For instance, if we have:

```php
<?php
use Foo\Bar;
```

Then I know that we want the class `Bar` of namespace `Foo`. Looking into the `autoload` section of the `composer.json` and making some initial assumptions, I can most likely predict the location of the file, check for it, and access it.

However, I am torn between the fact that NodeJS is async and my resolving would likely need to be too - but Parser plugins seem to be sync! So, what is the best place to do an async resolving like described above? Let's take for instance:

```javascript
function pseudoNamespaceResolve(ns, className, fileThatHasUseStatement, done) {
    var composerJson = this.options.Uniter.composerJson;
    var requestOrigin = fileThatHasUseStatement;
    async.forEach(composerJson.dependencies, function(dep, cb){
        var depDir = path.join(rootDir, "vendor", dep);
        var depJson = parse_json_from_file(depDir+"/composer.json");
        var autoload = depJson.autoload;
        var loadableDirs = [];
        // ... snip: Iterate over autoload's entries, and grab the dirnames int he fields. ...
        async.forEach(loadableDirs, function(dir, step){
            fs.exists(path.join(dir, className+".php"), function(){ /* ... */ })
            // ... snip: Iterate over the loadable dirs, and try finding the class file. ...
        });
    });
}
```

At some point, we'd end up calling `done(null, "/some/path.php")`, once it was found. At that moment, I have a very good idea of where the file is, and could tell WebPack about it. But, where and how? Parser plugins seem sync. The resolver most likely will be async.

So what is the best place to put such an async resolver?

And then, I'd also need to edit the code, too. So that the PHP file, that has the class that we want, was executed, so the class is actually available... So I would once again need to make a custom template, allowing me to re-write the code too. But in this instance, this might be the easier task :P ...

I'm trying really hard to understand the WebPack internals - which is why I have searched `Dependency.js` and `Compilation.js` for clues. But out of nowhere, dependencies have a `this.module` property that is filled with a module. I was not able to pinpoint how the modules are being picked up, and how to get WebPack to fill one in.

Hopefuly you can shed some light here, because my lightbulbs are busted altogether...

Also, I am documenting my code. I plan on using it in order to explain others how they can make plugins or to improve the Plugin docs! So, i really want to help - but in order to provide more help, I need to ask more myself (:

I wish you a happy new year's day, since I am pretty sure you won't spend your night on your computer at that time. So I'll patiently wait. :)

Kind regards,
Ingwie.

PS. Sorry for the wall! XD

**Comment by IngwiePhoenix** [comment]
Oh! I also totally forgot array dependencies, like `require([], cb(require))`... But I should ask that later. x)

**Comment by sokra** [comment]
Let's clear up some responsibilities in webpack:

* Parsing: Parser Plugin
  * Result: One or multiple subclasses of `Dependency` were added to the module
* Resolving: `ModuleFactory` + `Compilation`
  * Result: `module` property on the `Dependency` is set to the resolved module
* Emitting: `DependencyTemplate`
  * Result: Some cool replacements in the module source were made

So you have to do the following:

* Create a parser plugin that looks from your `__uniter_require_once__` calls.
  * Don't try to resolve anything here
  * Create an instance of `UniterRequestOnceDependency` and add it to the module
* In the `compilation` hook
  * register `UniterRequestOnceDependency` with the `normalModuleFactory` to the standard resolving kicks in
  * register `UniterRequestOnceDependency` with the `UniterRequestOnceDependencyTemplate`
* In `UniterRequestOnceDependencyTemplate`
  * replace the statement with your code, using only `__webpack_require__` which is the internal require function, which takes a module id. i. e. `delete __webpack_require__.c[id]; var XYZ = __webpack_require__(id)`

> But, from within the dependency, how could I get a module ID?

The from the `DependencyTemplate` you can access the module id with `dep.module.id` where `dep` is the Dependency.

> I could just use LocalModule

`LocalModule` is something completely different only used for AMD. Don't use it.

> But, where and how? Parser plugins seem sync. The resolver most likely will be async.

Don't do resolving in the parser plugin. You should do in in a ModuleFactory, or extend the standard module factory with a resolver plugin.

> So what is the best place to put such an async resolver?

In a resolver plugin or in a `ModuleFactory`

---

I'm not sure if I understand the `use` part correctly, but here is how I understand it:

It's just like a `require` but with a different resolution algorithm.

You could just write you own `ModuleFactory` and register it with the `UseDependency`. In this ModuleFactory you implement the resolving algorithm and return a new `NormalModule`.

---

You may need to know which classes a module defines to generate the correct require statement. Here you can use the `this.state.module.meta` object from a parser plugin to store meta information about the module (i.e. the defined classes). In a `DependencyTemplate` you can access these meta data via `dep.module.meta` and use it somehow.

**Comment by IngwiePhoenix** [comment]
Woah! That is pretty amazing, and straightforward. Thank you a lot for these explanations! I have understood this so far and I will go and code them in now. :)

However, how about the async and `array`ied functions, such as:

```javascript
// Async and array:
require(["my-module"], function(myModule){ ... });

// As chunk:
require.ensure([
  "my-module"
], function(require){
  var myModule = require("my-module");
}, "myModuleThing");
```

How are they handled?

With your above explanation, i can successfuly implement the synchronous dependencies, since these are passed basically the string of the request. But how about these? Which subclass of `Dependency` is used to address `["my-module-1", "my-module-2"]`? And how do I properly tell WebPack about a new chunk, in the case of a `require.ensure` call? I was unfortunately unable to find these in the sourcecode, yet. It would be great if you could point me somewhere there.

Again, thanks for this detailed answer. I will make sure to find a way to let you know when the plugin has a working release on NPM. :)

**Comment by sokra** [comment]
A `Module` is a subclass of `DependencyBlock`.

A `DependencyBlock` is a tree-like structure of `Dependencies`.

There is another subclass of `DependencyBlock` which is `AsyncDependencyBlock`. In a Parser plugin you can add an `AsyncDependencyBlock` to the module and add `Dependencies` into this block. Take a look at the `RequireEnsureParserPlugin`.

**Comment by IngwiePhoenix** [comment]
Alright, thanks @sokra :)

Just looked at the suggested classes and I think I am set now. Thank you a lot!!
