### ISSUE TITLE
packages/tailwindcss/src/compile.ts

### ISSUE THREAD

**Issue by lvrocky** [webpack/webpack#18238]
export function compileCandidates(
  rawCandidates: Iterable<string>,
  designSystem: DesignSystem,
  { onInvalidCandidate }: { onInvalidCandidate?: (candidate: string) => void } = {},
) {
  // ...

  for (let rawCandidate of rawCandidates) {
    let candidate = designSystem.parseCandidate(rawCandidate)
    if (candidate === null) {
      if (onInvalidCandidate) {
        onInvalidCandidate(rawCandidate);
      } else {
        throw new Error(`Invalid candidate: "${rawCandidate}"`);
      }
      continue; // Bail, invalid candidate
    }
    candidates.set(candidate, rawCandidate);
  }

  // ...
}

export function compileAstNodes(rawCandidate: string, designSystem: DesignSystem) {
  let candidate = designSystem.parseCandidate(rawCandidate);
  if (candidate === null) {
    throw new Error(`Invalid candidate: "${rawCandidate}"`);
  }

  // ...
}

1. **Specific Error Messages**:
   - **Problem**: Current error handling mainly involves calling the `onInvalidCandidate` callback function to handle invalid candidates, and printing corresponding error messages to the console.
   - **Optimization Suggestion**: Directly throw an error with specific error messages when encountering invalid candidates, providing better insight into what went wrong.

**Comment by snitin315** [comment]
We appreciate your effort in raising this issue. To ensure clarity in understanding your situation, we kindly request you recreate the issue using one of our templates. 

Your collaboration will help us in providing you with effective assistance.
