### ISSUE TITLE
compiler.run callback doesn't receive any errors

### ISSUE THREAD

**Issue by gfpacheco** [webpack/webpack#1823]
If I run `webpack` cli tool I get errors (which is correct!), but if I run it as a Node module i don't get any errors in my callback.

I made [this repo](https://github.com/gfpacheco/webpack-no-errors-issue) to help you reproduce the issue.

**Comment by IngwiePhoenix** [comment]
Did you check the stats object for the errors? They should be there.

**Comment by gfpacheco** [comment]
Yes I do, both the `error` and the `stats.errors`, there's nothing there.

**Comment by gfpacheco** [comment]
Damn it, I found the error: the right way of checking for errors is by `stats.hasErrors()`.

Although it could be easier to find out =/
