### ISSUE TITLE
webpack5.90.0 Modifying files in the node_modules directory (local component library) cannot trigger hot updates

### ISSUE THREAD

**Issue by coder-fengjun** [webpack/webpack#18249]
# Bug report

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  5.90.0
Node.js version: 16.19.1
Operating System: M1 OS
Additional tools: Vue-cli

**Comment by alexander-akait** [comment]
Please read https://github.com/webpack/webpack/issues/11612
