### ISSUE TITLE
Webpack ignores --color option

### ISSUE THREAD

**Issue by pavellishin** [webpack/webpack#1824]
Even if no --color option is passed, output is colorized.

**Comment by bebraw** [comment]
By the looks of it, the code relies on [supports-color](https://www.npmjs.com/package/supports-color). Reading from there I can see it respects `--no-color`. So if you pass that, it likely won't colorize your output.

**Comment by pavellishin** [comment]
Sure, but this doesn't address this particular issue. 

1. --no-color isn't documented in webpack.
2. If webpack stops using `supports-color`, the `--no-color` option goes away.
3. Even if webpack keeps using it forever, it seems silly to pass arguments based on specific internal implementation details.

**Comment by bebraw** [comment]
Yeah, I agree it's not ideal. Let's wait to hear what the author has to say. :)

**Comment by scottaddie** [comment]
What is the recommended way to enable colors? [This issue](https://github.com/madskristensen/WebPackTaskRunner/issues/14) indicates that the `--colors` switch isn't working in Webpack 2.0.5-beta. I'm looking for a single CLI switch that's compatible with both Webpack 1.x and 2.x. Does such a switch exist?

**Comment by bebraw** [comment]
@scottaddie On a quick look Webpack 2 seems to depend on **supports-color** as well. Here are [the flags it supports](https://www.npmjs.com/package/supports-color#info). You can also force color through env.

I think `--colors` was dropped a while back.

**Comment by pavellishin** [comment]
The author seems pretty committed to using the `supports-color` options: https://github.com/webpack/webpack/pull/1825

I still disagree, but it ain't my decision :)

**Comment by ericnewton76** [comment]
so this is still an issue, the command line --colors doesnt work.

however, --no-color did work.

**Comment by bebraw** [comment]
@ericnewton76 The logic is different now. Colors are enabled if the terminal supports them and you have to explicitly disable colors with `--no-color` if you don't want them.

**Comment by ericnewton76** [comment]
@bebraw either way, --color, which is what is documented, doesn't work as explained.  Nor does `--color=false` or `--color false` with a terminal that supports colors.

`--no-color` does work on mine, but is not mentioned anywhere

**Comment by bebraw** [comment]
@ericnewton76 Ok, perfect.
