### ISSUE TITLE
Using `[name]` within `output.library`, the correct value isn't utilized in the source map namespace

### ISSUE THREAD

**Issue by bwhite94** [webpack/webpack#18243]
# Bug report

**What is the current behavior?**
When utilizing multiple entry points, and specifying a custom library name which includes the `[name]` placeholder, the source-map resource path is excluding the replaced `[name]` value with an empty string.

This is causing issues where sources will not be presented properly or may conflict if generated with the same `output.library` pattern.

**If the current behavior is a bug, please provide the steps to reproduce.**
Minimal reproduction repository: https://github.com/bwhite94/webpack-source-map-issue

1. Configure your webpack config to have multiple named entry-points.
2. Specify `output.library` to include the `[name]` placeholder. E.g: `library-[name]`
3. Ensure `devtool: 'source-map'` exists in your webpack config object. (This may also exist with other devtools but haven't been tested)
4. Run webpack build and inspect source map files. You will notice the sources will include values like: `webpack://library-/...`

**What is the expected behavior?**
The source map sources should include the correct namespace with the `[name]` value present. E.g: `webpack://library-entry-a/...` and `webpack://library-entry-b/...`

**Other relevant information:**
webpack version:  5.91.0
Node.js version: 20.11.1
Operating System: Windows 11
Additional tools:

**Comment by alexander-akait** [comment]
Feel free to send a PR

**Comment by keshav861** [comment]
@bwhite94 where is the webpack.config.js file i have got the issue and i think that i have a solution for it but i was not able to find the file in the repo can you help me out.

**Comment by bwhite94** [comment]
> @bwhite94 where is the webpack.config.js file i have got the issue and i think that i have a solution for it but i was not able to find the file in the repo can you help me out.

It's in the minimal reproduction repo, but more specifically [here](https://github.com/bwhite94/webpack-source-map-issue/blob/main/webpack.config.js).

I know of workarounds like generating separate webpack config objects for each entry-point that needs a different library name, but that defeats the purpose of using things like the `[name]` placeholder and adds extra overhead that could potentially break your webpack configuration if you're not careful.

**Comment by Nightrider0098** [comment]
@alexander-akait Currently we are generating sources is constructed with [uniqueName](https://github.com/Nightrider0098/webpack/blob/c586c7b1e027e1d252d68b4372f08a9bce40d96c/lib/config/defaults.js#L860). Either we need to use some other variable this is later parsed with getAssetPath or we need to update the uniqueName getter function.

**Comment by alexander-akait** [comment]
Yeah, feel free to send a PR, we can pass some things as options

**Comment by snitin315** [comment]
I think using placeholders like `[name]` was never supported for `output.library` option. Did you find it mentioned in docs somewhere?

**Comment by snitin315** [comment]
> Currently we are generating sources is constructed with [uniqueName](https://github.com/Nightrider0098/webpack/blob/c586c7b1e027e1d252d68b4372f08a9bce40d96c/lib/config/defaults.js#L860). Either we need to use some other variable this is later parsed with getAssetPath or we need to update the uniqueName getter function.

We already have [`output.devtoolNamespace`](https://webpack.js.org/configuration/output/#outputdevtoolnamespace) option, however the bug is that this option doesn't support template literal as of now. I'll fix it.

**Comment by alexander-akait** [comment]
bump
