### ISSUE TITLE
[5.91.0] "Fixed fs types" breaks `outputFileSystem` compatibility with `memfs`

### ISSUE THREAD

**Issue by birdofpreyru** [webpack/webpack#18242]
# Bug report

**What is the current behavior?**

After Webpack upgrade from v5.90.3 to 5.91.0 in an existing project, the TypeScript does not allow the code given in [Custom File Systems docs](https://webpack.js.org/api/node/#custom-file-systems) because of typing conflict mismatch:

```
Type 'IFs' is not assignable to type 'OutputFileSystem'.
  Types of property 'writeFile' are incompatible.
    Type '{ (id: TFileId, data: TData, callback: TCallback<void>): any; (id: TFileId, data: TData, options: string | IWriteFileOptions, callback: TCallback<...>): any; }' is not assignable to type 'WriteFile'.
      Types of parameters 'callback' and 'options' are incompatible.
        Type 'WriteFileOptions' is not assignable to type 'TCallback<void>'.
          Type 'null' is not assignable to type 'TCallback<void>'.ts(2322)
(property) Compiler.outputFileSystem: OutputFileSystem | null
```

I guess the change for "_Fixed fs types_" led to a regression.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  
Node.js version:
Operating System:
Additional tools:

**Comment by alexander-akait** [comment]
Please open an issue in memfs, they have broken fs types, I wrote them, but no feedback, I can't fix it here, sorry

**Comment by alexander-akait** [comment]
You can make sure to use this:
```
const fs = require("fs");
const fs1 = require("graceful-fs");

compiler.outputFileSystem = fs;
compiler.outputFileSystem = fs1;
```

but problems only with memfs, because some methods have wrong types

**Comment by alexander-akait** [comment]
Anyway feel free to feedback

**Comment by birdofpreyru** [comment]
I created this issue mostly to make sure you've noticed this problem, and you know that example in Webpack docs does not really work as is now. For my purposes, just forcing the assignment via TypeScript casting is fine, so I don't feel any urge to do anything else about it.

**Comment by alexander-akait** [comment]
Yeah, memfs works fine with webpack, we have a lot of tests, just the types problem

**Comment by michaelfaith** [comment]
I just hit this issue as well.  It doesn't look like this has been reported in the `memfs` repo.  @birdofpreyru were you planning to file that?

**Comment by birdofpreyru** [comment]
Nah @michaelfaith , I got distracted by different stuff and never reported it. Please report it there if you have a moment :)
