### ISSUE TITLE
Implement ability to use "node:" prefixes for Node.js core modules

### ISSUE THREAD

**Issue by krutoo** [webpack/webpack#18277]
## Feature request

**What is the expected behavior?**

Based on this discussion:
https://github.com/webpack/webpack/discussions/18265

**What is motivation or use case for adding/changing the behavior?**

In order for the bundle to be used in runtimes that support Node.js core modules (for example Deno), we need to implement an option that would force the internal webpack code to use `node:` prefixes

**How should this be implemented in your opinion?**

As @alexander-akait says here:
https://github.com/webpack/webpack/discussions/18265#discussioncomment-8987841

> we need to implement `nodePrefixForCoreModules` here https://github.com/webpack/webpack/blob/main/lib/config/browserslistTargetHandler.js#L336, put version there, than implement `supportsModePrefixForCoreModules() {}` in `RuntimeTemplate.js` and use it everywhere we generate external exports for core modules

**Are you willing to work on this yourself?**
no

**Comment by alexander-akait** [comment]
For me:
```
Version	Changes
v16.0.0, v14.18.0	
Added `node`: import support to require(...).
```
