### ISSUE TITLE
`exportsPresence` does not work for unused imports

### ISSUE THREAD

**Issue by menelaos** [webpack/webpack#18273]
# Bug report

**What is the current behavior?**

Setting [`exportsPresence`](https://webpack.js.org/configuration/module/#moduleparserjavascriptexportspresence) to `'error'` does not emit an error if the import is unused.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. `git clone https://github.com/rwieruch/minimal-webpack-setup`
2. `cd minimal-webpack-setup`
3. `npx npm-check-updates -u`
4. `npm install`
5. Create `src/foo.js` with the following content:
   ```javascript
   export const foo = 42;
   ```
6. Modify `webpack.config.js` to include
   ```javascript
   module: { parser: { javascript: { exportsPresence: 'error' } } },
   ```
7. Modify `src/index.js` to look like:
   ```javascript
   import { bar, foo } from './foo';

   console.log(foo);

   // Uncommenting the following line will result in an error
   // console.log(bar);
   ```
8. `npx webpack`

**What is the expected behavior?**

Webpack should emit an error that `bar` is an invalid import regardless of whether `console.log(bar)` is commented out or not.

**Other relevant information:**
webpack version:  5.91.0
Node.js version: 21.7.1

This seems to be a regression since the same issue was reported a few years ago and allegedly resolved (https://github.com/webpack/webpack/issues/4897).

**Comment by alexander-akait** [comment]
hm, intresting, no sure we can't fix it, because we don't handle at all unused imports for perf reasons, maybe linter is the best solution here

**Comment by alexander-akait** [comment]
@vankop What do you think? Honestly, I'm not sure that we should process this, personally I think it's more work for a linter, because `bar` import is not unsed and we just drop it, so we don't generate broken code

**Comment by vankop** [comment]
probably original issue was closed as a stale one.. 

So basically idea of the warning/error here is to notify user about __highly likely__ issues at runtime ( if exports are reachable code ), with unused imports it is not a problem. If you didn't disable optimisations in config, webpack will remove unused exports for you.

If you want to improve your source code in this case better to use some linters (e.g. `eslint` )
