### ISSUE TITLE
mangled exports breaks with destructuring assignment of JSON imports

### ISSUE THREAD

**Issue by ikydd-bbc** [webpack/webpack#18278]
# Bug report

**What is the current behavior?**

As of 5.90.2 (including 5.91.0), destructuring assignment on a JSON import does not work because the property names have been changed (using default settings). Setting `optimization.mangleExports` to `false` fixes this, but it worked fine in 5.90.1 and it works fine accessing properties with dot notation in 5.90.2+. 

Essentially the following:
```
import data from './data.json';

// this works ...
console.log(data.foo.bar)

// ...but this does not
const { bar } = data.foo;
```

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/ikydd-bbc/spike-webpack-minify-bug

**What is the expected behavior?**

Destructuring of JSON imports should work as they did previously in 5.90.1. We should be able to import a JSON file using the default export and then use destructuring assignment to pick out whatever properties we choose. 

**Other relevant information:**
webpack version:  5.90.2 + 
Node.js version: 18.19.0
Operating System: OSX
Additional tools:

**Comment by alexander-akait** [comment]
Thank you for the issue, do you want to send a pr?

**Comment by ahabhgk** [comment]
I think there is already have a warning for named export with JSON https://github.com/webpack/webpack/blob/7090328ba33f8887db2dcf41767ba72f7bfb90bd/lib/json/JsonParser.js#L62-L63

What about disable named export with JSON in next major and when `futureDefaults: true`?

I will take a look and try to fix this bug in the next few days

**Comment by alexander-akait** [comment]
@ikydd-bbc Just intresting, why you used named export for JSON? Legacy code?

**Comment by alopix** [comment]
@alexander-akait 
The use case shown is not really a named export from JSON though, is it?
It uses a default import and then destructures the already imported default.

> ```
> import data from './data.json';
> 
> // this works ...
> console.log(data.foo.bar)
> 
> // ...but this does not
> const { bar } = data.foo;
> ```

**Comment by alexander-akait** [comment]
@alopix Oh, I see, my mistake, sometimes the eyes are wrong :smile: We will look at this soon

**Comment by codeth** [comment]
Also stumbled into this issue whilst upgrading a project to Webpack 5.

I've noticed it doesn't seem to mangle _all_ of the properties in the imported JSON, just the ones referenced wherever it has been imported. For example...

Source file:

```ts
import graphqlSpec from './graphqlSpec.json'; // {"data":{"schema":{"types":[...

const { types: schemaTypes } = graphqlSpec.data.schema;

schemaTypes.reduce(...
```

Production build output:

```js
const i = JSON.parse('{"p":{"w":{"gK":[...etc'); // Objects within gK are **not** mangled

const { types: w } = i.p.w;

// Reading w fails because types has been mangled to gK
w.reduce(...
```
