### ISSUE TITLE
hot loader with vendor pack not working

### ISSUE THREAD

**Issue by arolson101** [webpack/webpack#1828]
I have a vendor pack set up and a module that I'm trying to get working with hot reloading.  I get this log:

```
[HMR] Cannot apply update. Need to do a full reload!
vendor.js:9383 [HMR] Error: Aborted because 642 is not accepted
    at hotApply (http://localhost:8080/vendor.js:380:31)
    at hotUpdateDownloaded (http://localhost:8080/vendor.js:293:13)
    at hotAddUpdateChunk (http://localhost:8080/vendor.js:273:13)
    at webpackHotUpdateCallback (http://localhost:8080/vendor.js:29:12)
    at http://localhost:8080/0.96b12353822225150b52.hot-update.js:1:1
```

It looks like the bug is in HotModuleReplacement.runtime.js in getAffectedStuff:
```js
				if($require$.s === moduleId) {
					return;
				}
```

I think it should be a ```continue```, ```break``` or ```return [outdatedModules, outdatedDependencies];```, because it does find my ```module.hot.accept``` registration and adds it to the list.

**Comment by gabrielalan** [comment]
I'm getting this error too, but I don't know if is the same issue... my webpack.config.js:

`var path = require('path'),
    webpack = require('webpack'),
    ExtractTextPlugin = require("extract-text-webpack-plugin");

module.exports = {
    entry: ['webpack/hot/dev-server', 'babel-polyfill', path.normalize(__dirname + '/src/js/main')],
    devtool: 'cheap-module-source-map',
    output: {
        filename: 'bundle.js',
        path: path.join(__dirname, 'dist'),
        publicPath: 'dist/'
    },
    module: {
        loaders: [
            {
                loader: 'babel',
                test: /\.js$/,
                include: [path.resolve(__dirname, 'src', 'js')],
                query: {
                    plugins: ['transform-runtime'],
                    presets: ['es2015']
                }
            },
            {
                test: /\.scss$/,
                loader: ExtractTextPlugin.extract(['css','sass'])
            }
        ]
    },
    plugins: [
        new webpack.optimize.UglifyJsPlugin({minimize: true}),
        new ExtractTextPlugin("[name].css"),
        new webpack.DefinePlugin({
            'process.env': {
                'NODE_ENV': JSON.stringify('production')
            }
        })
    ]
};`

**Comment by bebraw** [comment]
@arolson101 Can you provide a standalone example? It's not possible to debug this otherwise.

@gabrielalan You shouldn't use `ExtractTextPlugin` and `UglifyJsPlugin` in your development configuration. A standalone example would be useful here as well.

**Comment by gabrielalan** [comment]
@bebraw I removed ExtractTextPlugin, but Uglify? What is your recommendation?

**Comment by bebraw** [comment]
@gabrielalan Drop Uglify from your development setup as well. It won't do much good there as you don't need to care about the bundle size during development.

**Comment by gabrielalan** [comment]
@bebraw that was the production bundle hehehe... in fact it was in the earlier days of the project, today we already fixed the bug, but I don't remember how.

**Comment by bebraw** [comment]
Ok, I guess I'll close this for now. Feel free to re-open with more details (standalone project, please).
