### ISSUE TITLE
[feature] create cli

### ISSUE THREAD

**Issue by RSS1102** [webpack/webpack#18295]
## Feature request

**What is the expected behavior?**

Should we also create a create cli to help users quickly start using webpack templates for development?

**What is motivation or use case for adding/changing the behavior?**

When I want to quickly develop React using Webpack, I need to learn from and read React's CLI. If I use Vue, I need to use Vue CLI. Why doesn't Webpack create its own CLI to make it easier for users to start a new Webpack project?

**How should this be implemented in your opinion?**
Create a tool `pnpm create webpack` can be used

**Are you willing to work on this yourself?**
yes

**Comment by RSS1102** [comment]
And I see [create-react-app](https://github.com/facebook/create-react-app)  haved stopped maintaining updates, so when I create React, I prefer to use [Vite's](https://github.com/vitejs/vite/tree/main/packages/create-vite) template to configure my project

**Comment by alexander-akait** [comment]
It is already implemented, `webpack-cli init`, soon we will implement more templates

**Comment by RSS1102** [comment]
> It is already implemented, `webpack-cli init`, soon we will implement more templates

Yes, I discovered him later, perhaps because he was not placed in the most prominent position on the official website: **Quick Start**, which made users want to use webpack quickly and encountered doubts.
