### ISSUE TITLE
`--hot` flag should not add HMR plugin when it's already there, causes wrong moduleId in hot.accept

### ISSUE THREAD

**Issue by Download** [webpack/webpack#1830]
I am struggling getting HMR to work.

I see in the generated code that the moduleId in the `hot.accept` call is generated wrong.
In my case it reads `1010` whereas it should be `10`.
It looks like the moduleId is inserted twice?

I found an existing issue in which the same problem is described:
https://github.com/webpack/webpack/issues/406#issuecomment-62756894

However I don't know what the solution is. It's suggested that the issue is with the `output.path` but I have no idea what to do. My output path is set to an absolute directory and the docs suggest that this is correct?

**Comment by Download** [comment]
Ok... So after re-reading the issue it suddenly dawned upon me that I had both `--hot` and the `HotModuleReplacementPlugin` in my config... @sokra explicitly mentions that as the cause but it never clicked when I read it the first time... When I removed the plugin it all started working!

However, I have to say I find this behavior very unexpected. I would expect command line arguments to override the config, not just add the plugin again... Especially when that ends up breaking everything.

If it's possible to detect that the plugin is already there then maybe that would be much better behavior for the `--hot` switch. To add the plugin, only when it's not already configured. I'm going to change the title of this issue to reflect that, and remove the question label. My question is answered, but I feel this is actually a bug.

**Comment by Download** [comment]
Ah I can't remove labels. Ok.  :)

**Comment by sebastienbarre** [comment]
Consider closing the issue? This makes it a bit easier to navigate open issues (there are so many). Thanks.
