### ISSUE TITLE
Uncaught TypeError: (0 , _whatwgFetch2.default) is not a function

### ISSUE THREAD

**Issue by xwartz** [webpack/webpack#1831]
```js
import fetch from 'whatwg-fetch'

store.fetchItems = (api) => {
  return fetch(api, {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json;charset=UTF-8'
    },
    mode: 'no-cors'
  }).then(res => {
    if (res.status >= 200 && res.status < 300) {
      return Promise.resolve(res)
    } else {
      return Promise.reject(new Error(res.statusText))
    }
  }).then(res => {
    return res.json()
  }).then(data => {
    return data
  }).catch(err => {
    console.log(err)
  })
}
```

Some error occurs in browser under Babel6:

`Uncaught TypeError: (0 , _whatwgFetch2.default) is not a function`

**Comment by bebraw** [comment]
I think this might be related to https://phabricator.babeljs.io/T2212.

**Comment by aljux** [comment]
did this get solved?

**Comment by abimelex** [comment]
+1 have the same issue

**Comment by kuppula-pmap** [comment]
It worked for me also

**Comment by tessact** [comment]
Is it the same case with import fetch from 'isomorphic-fetch' 
Do I have to just include : import 'isomorphic-fetch' instead

**Comment by oliverbenns** [comment]
@tessact Yes and no. Their docs don't assign a variable to it, but many examples online show that it does. I ended up assigning a variable to it - much nicer imo.
