### ISSUE TITLE
Webpack preventing access to library global object but works fine though CDN

### ISSUE THREAD

**Issue by simkessy** [webpack/webpack#1834]
A lot of the encryption libraries I've been trying to bundle with webpack have been missing some of the global objects or modules. 

For example, I've been working with [cryptico](https://github.com/wwwtyro/cryptico) and there should be a RSA object but it's undefined. Same with forgejs, jsrsasign and a few others. However, if I just include the files in my index through a CDN, it works fine. The CDN file and the node-module files are identical. So I'm not sure what's happening in webpack that's causing this.

**Comment by sokra** [comment]
It doesn't seem to use a module system at all... Try http://webpack.github.io/docs/shimming-modules.html

**Comment by simkessy** [comment]
Thank you ill give it a shot.
