### ISSUE TITLE
Does Webpack support javascript code using UTF8 variables?

### ISSUE THREAD

**Issue by ibiza240** [webpack/webpack#1837]
I have created a react webapp that uses d3.js

In the d3.js source code, there is a line:
var ε = 1e-6, ε2 = ε * ε, π = Math.PI, τ = 2 * π, τε = τ - ε, halfπ = π / 2, d3_radians = π / 180, d3_degrees = 180 / π;

that is transformed into:
var Îµ = 1e-6, Îµ2 = Îµ * Îµ, Ï€ = Math.PI, Ï„ = 2 * Ï€, Ï„Îµ = Ï„ - Îµ, halfÏ€ = Ï€ / 2, d3_radians = Ï€ / 180, d3_degrees = 180 / Ï€;

in the outputted bundle.js

Does Webpack support packaging javascript code that uses UTF8 variable names?

**Comment by brysgo** [comment]
@ibiza240 - I'm having the same issue, did you figure out how to work around it?
