### ISSUE TITLE
No Reference for <App/> component and Webpack still able to build it without any errors.

### ISSUE THREAD

**Issue by pavangayakwad** [webpack/webpack#18381]
# Bug report

`<App/>` component is not imported in index.js file but builds and runs without reporting any errors. It must not be.

**If the current behavior is a bug, please provide the steps to reproduce.**
[react-app.zip](https://github.com/webpack/webpack/files/15212388/react-app.zip)

Extract above source code a folder and run following commands
- npm i
- npm run build

The build must fail but it succeeds.

**What is the expected behavior?**

The build must throw error asking for the reference of the component <App/> in index.js file

**Other relevant information:**
"webpack": "^5.91.0",
"webpack-cli": "^5.1.4",
"webpack-dev-server": "^5.0.4"

**Comment by alexander-akait** [comment]
Sorry we don't validate your code, please use eslint for such purposes, also after build you can find you have a problem - open console and you will see `Uncaught ReferenceError: App is not defined`
