### ISSUE TITLE
Is there a way to delete outdated output files automatically after build?

### ISSUE THREAD

**Issue by JohnnyZhao** [webpack/webpack#1839]
hi, I have my output file name config like this:

```
    ....
    output: {
        path: path.resolve('./assets/bundles/'),
        filename: "[name]_[chunkhash].js"
    },
    ....
```

with --watch, after several file updating, there are more and more output files with different hash generated, I wonder if there is a way to automatically remove these outdated output files? Maybe a config I don't know yet?

Thanks~

more and more output files like this:

```
......
bundle_js_b4ae71e2a15bc18de7c6.js
bundle_js_3d48b8b6de039eec3dfb.js
......
```

**Comment by bebraw** [comment]
[clean-webpack-plugin](https://www.npmjs.com/package/clean-webpack-plugin) works well for this purpose.

**Comment by JohnnyZhao** [comment]
Thank you very much! :)
