### ISSUE TITLE
webpack can't parse the webpack module

### ISSUE THREAD

**Issue by fresheneesz** [webpack/webpack#184]
I don't know if this is expected or not - its not really something i intended, but i thought i'd report it anyway. I had a `require('webpack')` in the script i was bundling, and when bundling got this:

```
../~/webpack/package.json
Module parse failed: F:\<omitted>\node_modules\webpack\package.json Line 2: Unexpected token :
| {
|   "name": "webpack",
|   "version": "1.0.1",
|   "author": {
 @ ../~/webpack/lib/Stats.js 77:11-37
```

**Comment by g-patel** [comment]
> This means require("./package") resolve to package.json.

@sokra Even though late post here, I can't get it working without adding `.json` in the require. However, it works when I have have full file name including `.json` in the require.
