### ISSUE TITLE
Rename target "atom" to "electron"

### ISSUE THREAD

**Issue by mnquintana** [webpack/webpack#1841]
Thanks for all the awesome work on webpack! :tada: 

It would be great to rename the `target` option `atom` to `electron` to avoid confusion between the two (since one is the runtime, and the other is an app that happens to be built on the runtime).

**Comment by gabrielstuff** [comment]
As from what I get, you can already use `electron` : 
https://github.com/webpack/webpack/blob/v1.12.10/lib/WebpackOptionsApply.js

I think it is a fallback and a legacy key

**Comment by mnquintana** [comment]
Ah okay, in that case it would be good to just update the docs (they still use `atom`)

**Comment by bebraw** [comment]
@mnquintana If you have time, free free to modify the [docs](https://github.com/webpack/docs/wiki) directly.

**Comment by mnquintana** [comment]
Added in https://github.com/webpack/docs/wiki/configuration/e31fd1a0faeda7317720bed4dc66c59a184eb8fb

**Comment by bebraw** [comment]
@mnquintana Great! Thanks.

FYI, there are a bunch of [easy documentation](https://github.com/webpack/webpack/issues?q=is%3Aopen+is%3Aissue+label%3Adocumentation+label%3Aeasy) issues if you want to contribute. Some of those other documentation issues might be doable as well.

**Comment by mnquintana** [comment]
@bebraw Sure! I'll take a look at those.

Btw, how often are the docs at http://webpack.github.io/docs regenerated?

**Comment by bebraw** [comment]
@mnquintana By the looks of it, the site was updated [three months ago](https://github.com/webpack/docs/tree/gh-pages)...

@sokra Do you have some cronjob for updating the docs?
