### ISSUE TITLE
output,charset: true does not work

### ISSUE THREAD

**Issue by alexstock1** [webpack/webpack#18410]
# Bug report
**What is the current behavior?**

output,charset: true does not add to charset="utf-8" to script tag

https://webpack.js.org/configuration/output/#outputcharset

**Other relevant information:**
webpack version:  5.91
Node.js version: any version
Operating System: any os

**Comment by uditjainstjis** [comment]
yes charset:true cant add to charset="utf-8", as
charset="utf-8" is added by boolean = true

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
