### ISSUE TITLE
Superagent with Webpack

### ISSUE THREAD

**Issue by hoodsy** [webpack/webpack#1842]
I recently tried to use the browser version of superagent located in superagent/lib/client, but got this error:

```
Emitter(Request.prototype);
^
TypeError: Emitter is not a function
```

Looking in the package.json, the browser field is set to map emitter -> component emitter:

```
"browser": {
    "emitter": "component-emitter"
}
```
But for some reason, this wasn't working with my webpack build. Maybe this was an issue specific to my build, but replacing require('emitter') to require('component-emitter') resolved my problem.

I originally posted this issue to [superagent](https://github.com/visionmedia/superagent/issues/822), and was directed here.

**Comment by thuringia** [comment]
@hoodsy I didn't need to add any webpack-specifc configuration to make superagent work.
My modules just use
```js
import superagent from 'superagent'
```

**Comment by hoodsy** [comment]
@thuringia Trying that, I get ```request is not defined```

**Comment by thuringia** [comment]
@hoodsy How are you calling superagent? We've decided to import the superagent function as 'superagent' in our project, however most examples in the documentation require the module as
```js
const request = require('superagent');
```

Are you sure it's not a naming error in your code?

**Comment by bebraw** [comment]
Still relevant? Feel free to re-open if you repro. I tried superagent a while ago myself and it worked without any hiccups.
