### ISSUE TITLE
Source maps returned by loaders are ignored for asset modules

### ISSUE THREAD

**Issue by ArcanoxDragon** [webpack/webpack#18438]
# Bug report

When a source file is bundled as an asset module (e.g. `asset/resource`) using one or more loaders that returns a source map, the source map is discarded. Some types of assets (such as CSS files transpiled from SCSS/LESS/etc.) benefit from having source maps, so it doesn't make sense to assume that no asset will ever have a source map.

For example, `sass-loader` can be used to produce `.css` asset files from `.scss` source files. (This is in contrast to using something like `css-loader`/`style-loader`...sometimes a large website may need to reference site-wide static styles instead of having a script import them.)

**What is the current behavior?**

Webpack assumes all modules with a type starting with `asset/` (such as `asset/resource`) are "binary", and discards any source maps returned by loaders for these modules.

In my case, `sass-loader` returns source maps generated by the SASS implementation, which `NormalModule.js` retrieves as such: 

https://github.com/webpack/webpack/blob/ac8e83a4a2984ed977fd6c23a609da5cb43da492/lib/NormalModule.js#L851-L853

At this point, `source` is of type `string` (not `Buffer`), and `sourceMap` is a valid source map object.

However, several lines later, the `source` string gets converted to a `Buffer` because the constructor for `NormalModule` sets `this.binary` to `true` for all asset modules:

https://github.com/webpack/webpack/blob/ac8e83a4a2984ed977fd6c23a609da5cb43da492/lib/NormalModule.js#L315
https://github.com/webpack/webpack/blob/ac8e83a4a2984ed977fd6c23a609da5cb43da492/lib/NormalModule.js#L870-L875

This causes `createSource` to ignore the source map passed into it and return a `RawSource` for the buffer:

https://github.com/webpack/webpack/blob/ac8e83a4a2984ed977fd6c23a609da5cb43da492/lib/NormalModule.js#L782-L796

**If the current behavior is a bug, please provide the steps to reproduce.**

I can't provide my exact configuration due to proprietary company information, but this is reproducible with any Webpack configuration that uses SASS for asset modules.

- Set up `sass-loader` in a rule for modules with `type: "asset/resource"`. This will need the `sass-loader` and `sass-embedded` packages to be installed.
  ```js
  {
    test: /\.scss$/i,
    type: "asset/resource",
    use: [
      {
        loader: "sass-loader",
        options: {
          api: "modern",
          sourceMap: true,
          sassOptions: {
            sourceMapIncludeSources: true,
          },
        },
      },
    ],
  }
  ```
- Enable Webpack's source maps, e.g. with `devtool: "inline-source-map"`
- Provide a `.scss` file as an entry point
- Run the Webpack compiler
- View the `.css` file in the output directory and observe that it does not contain a source map file adjacent to it, nor does it contain an inline source map comment

**What is the expected behavior?**

Loaders for Asset Modules should be able to return a source map for certain types of assets, and these source maps should be included just like they would be for JavaScript modules instead of being unconditionally ignored.

If I change line 872 in `NormalModule.js` to the following, the source maps from SASS start working as expected:
```js
    (this.binary && !sourceMap) ? asBuffer(source) : asString(source),
```

Obviously this is not suitable as a one-size-fits-all fix; it's a hacky workaround that fixes the problem in my specific situation. Non-text assets (and even many text assets) would not be compatible with source maps (although I wouldn't expect loaders for these asset types to return a source map in the first place).

Perhaps there needs to be a way to opt into source maps on a per-module-rule basis, possibly in the `generator` settings? 

**Other relevant information:**
webpack version:  5.91.0
Node.js version: 20.13.1
Operating System: Windows 10 x64 (version 22H2)
Additional tools:
- `sass-loader = 14.2.1`
- `sass-embedded = 1.77.2`

**Comment by alexander-akait** [comment]
I think you try to achive - https://github.com/webpack-contrib/sass-loader/issues/962

**Comment by alexander-akait** [comment]
We've already had a discussion about this, but we haven't come up with a reasonable solution. We can solve this in two ways - at the loader level or like you provide here. I am fine with option for generator, but there are another problem - loaders generate absolute paths in `sources`, it will allow us combine source maps and avoid conflicts in `sources`, so we still need small things in `sass/less/stylus/etc-loader` to allow generate relative sources maps

**Comment by alexander-akait** [comment]
Do you want to send a PR for webpack here and I will implement an option for `sass/less/stylus/etc-loader` to generate relative source maps (relative to context by default, maybe make it optinal)

**Comment by alexander-akait** [comment]
I am fine with the `sourceMap: boolean` for generator

**Comment by ArcanoxDragon** [comment]
I actually encountered that problem as well - when using `sass-embedded` with `sass-loader`, it wasn't returning paths _at all_ (which would result in the actual inline source being used as the path, and the browsers don't know what to do with that)

I was planning on submitting a PR to `sass-loader` if this got accepted so that they can include a `sourceMapUrl` on the result.

**Comment by ArcanoxDragon** [comment]
> I am fine with the `sourceMap: boolean` for generator

How should I utilize that option? Should I change the `this.binary = /^(asset|webassembly)\b/.test(type);` check so that `this.binary` ends up as `false` if `sourceMap` is true? That seems a bit indirect and improper...

Alternatively I could skip the conversion to `Buffer` if the result is originally a string and the `sourceMap` option is true.

**Comment by alexander-akait** [comment]
> I was planning on submitting a PR to sass-loader if this got accepted so that they can include a sourceMapUrl on the result.

I think better allow to setup `sourceMap: boolean | "from-options"` (we don't set any custom source maps options and respect your) and also we skip this - https://github.com/webpack-contrib/sass-loader/blob/master/src/index.js#L107, so you can flexible setup source maps options

> How should I utilize that option? Should I change the this.binary = /^(asset|webassembly)\b/.test(type); check so that this.binary ends up as false if sourceMap is true? That seems a bit indirect and improper...

hm, okay, we can allow to setup `binary: boolean` on the module level, so you can make something modules (in your case `asset.*`) as a non-binary, I think it is a better name and cleary here

**Comment by ArcanoxDragon** [comment]
> hm, okay, we can allow to setup `binary: boolean` on the module level, so you can make something modules (in your case `asset.*`) as a non-binary, I think it is a better name and cleary here

I went ahead and pushed a slightly cleaned-up version of my original workaround fix to the PR for now, but I think I like the idea of having an override for `this.binary` on a module rule a bit more. I do think that if we go that route, there should be some documentation somewhere about the fact that Asset Modules will **not** receive source maps unless the `binary: false` override is used.

**Comment by alexander-akait** [comment]
Yeah, we just update our docs

**Comment by ArcanoxDragon** [comment]
> > I was planning on submitting a PR to sass-loader if this got accepted so that they can include a sourceMapUrl on the result.
> 
> I think better allow to setup `sourceMap: boolean | "from-options"` (we don't set any custom source maps options and respect your) and also we skip this - https://github.com/webpack-contrib/sass-loader/blob/master/src/index.js#L107, so you can flexible setup source maps options

Actually the main problem that I identified was not an issue with the `sourceMap` option itself, but rather the fact that the custom SCSS importer used by `sass-loader` does not include `sourceMapUrl` in its importer result:
https://github.com/webpack-contrib/sass-loader/blob/master/src/utils.js#L694

This causes source mappings for imported SCSS files to be completely garbled in the browser because it tries to use the actual contents of the file as the source URL. Adding `sourceMapUrl: canonicalUrl` fixes the issue, but I'm not sure if that's the correct fix as it would result in absolute URLs being returned for imported files.

**Comment by alexander-akait** [comment]
For such purposes we need to introduce a new value for `sourceMap` option, like I written above
