### ISSUE TITLE
CSS Modules: Nested CSS Classes

### ISSUE THREAD

**Issue by Swivelgames** [webpack/webpack#18441]
## Feature request

When importing CSS Modules, [nested classes](https://developer.mozilla.org/en-US/docs/Web/CSS/Nesting_selector) are not supported.

```css
.foo {
    color: blue;

    .bar {
        color: red;
    }
}
```

```javascript
import styles from "styles.module.css";

console.log(styles.bar);
```

Current Console Output:
```
> undefined
```

**What is the expected behavior?**

```
> src-styles-module-css__bar
```

Or something similar.

**What is motivation or use case for adding/changing the behavior?**

[CSS Nesting](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_nesting) has been available in all major browsers since December 2023. This ticket is to track the implementation to bring Webpack up to spec.

**How should this be implemented in your opinion?**

Nested CSS classes should be treated the same way as top-level classes.

**Are you willing to work on this yourself?**

Unfortunately, I don't have the capacity to right now :(

**Comment by alexander-akait** [comment]
We already support it, just use `import * as styles from "./styles.module.css";`, by default we use named export, but we you can set it to `false` if you want to use default export

**Comment by Swivelgames** [comment]
Ah! My apologies. Looks like the project is using `postcss`. Just tried with `css-loader` + `style-loader` (also probably would've been a better place for this issue to begin with), and it looks like it's working just fine!
