### ISSUE TITLE
Allow custom ModuleDependency by exposing `webpack/lib/util/makeSerializable` 

### ISSUE THREAD

**Issue by Danielku15** [webpack/webpack#18445]
## Feature request

**What is the expected behavior?**

I need `webpack/lib/util/makeSerializable` exposed as part of the public/top-level API surface to be able to implement a custom ModuleDependency. 

In a standard setup I might be able to import the submodule directly when installed via NPM, but frameworks like next.js ship a bundled version of webpack where these nested files are not accessible anymore.  

**What is motivation or use case for adding/changing the behavior?**

As a plugin author I am creating custom `ModuleDependency` to add new functionalities to WebPack like a specialized WebWorker and Audio Worklet translation. 

WebPack internally uses [ModuleDependencies heavily](https://github.com/webpack/webpack/tree/main/lib/dependencies) to implement features. e.g. looking at the `WorkerPlugin` it [registers](https://github.com/webpack/webpack/blob/400db90db807d630b6c9f5e7ccde2b8f01690f3b/lib/dependencies/WorkerPlugin.js#L104) the `WorkerDependency` + its template in the compilation and [adds](https://github.com/webpack/webpack/blob/400db90db807d630b6c9f5e7ccde2b8f01690f3b/lib/dependencies/WorkerPlugin.js#L352) `WorkerDependency` instances in the plugin logic.

Aspects like `ModuleDependency`, `RuntimeModule`, `NormalModuleFactory` are already exposed but in order to fully implement a custom dependency you need `makeSerializable`: 

https://github.com/webpack/webpack/blob/400db90db807d630b6c9f5e7ccde2b8f01690f3b/lib/dependencies/WorkerDependency.js#L131

**How should this be implemented in your opinion?**

Add `makeSerializable` as export like other utils:  https://github.com/webpack/webpack/blob/main/lib/index.js#L566

**Are you willing to work on this yourself?**
code wise yes, but I'm not willing to sign the CLA with my real life mailing address and signature. 

```diff
	util: {
		get createHash() {
			return require("./util/createHash");
		},
		get comparators() {
			return require("./util/comparators");
		},
		get runtime() {
			return require("./util/runtime");
		},
		get serialization() {
			return require("./util/serialization");
		},
+		get makeSerializable() {
+			return require("./util/makeSerializable");
+		}
		get cleverMerge() {
			return require("./util/cleverMerge").cachedCleverMerge;
		},
		get LazySet() {
			return require("./util/LazySet");
		}
	},

```

**Comment by alexander-akait** [comment]
We already have such API (i think we need to update our docs, feel free to send a PR or open an issue), look how we implement it for custom plugins - https://github.com/webpack-contrib/mini-css-extract-plugin/blob/master/src/index.js#L491

Feel free to feedback

**Comment by Danielku15** [comment]
gosh, I should have looked one level deeper 🤦‍♂️ The exposed serializable.register will fit my needs perfectly. 

Sorry for the noise and thanks a lot for the help. 🙇‍♂️
