### ISSUE TITLE
FlagDependencyExportsPlugin is slow with large JSON imports

### ISSUE THREAD

**Issue by albertxing** [webpack/webpack#18458]
# Bug report

**What is the current behavior?**

Projects importing large JSON files take multiple seconds to build, even incremental builds in watch mode. Most of the time in incremental rebuilds is spent in FlagDependencyExportsPlugin loading values from memory cache, in [`restoreProvided`](https://github.com/webpack/webpack/blob/d9ce3b1f87e63c809d8a19bbd92257d65922e81f/lib/FlagDependencyExportsPlugin.js#L81)

**If the current behavior is a bug, please provide the steps to reproduce.**

I've created a minimal repro here: https://github.com/albertxing/webpack-json-issue
With a large, deeply nested JSON default import, a lot of time (on my computer, 2-3s on every rebuild) is spent computing and re-hydrating the export tree, even though we only use the default export, and no tree shaking is required.

**What is the expected behavior?**

FlagDependencyExportsPlugin shouldn't take multiple seconds to process large JSON files, especially during incremental rebuilds in watch mode.
I can think of a few options we could explore:
- Skip some of the expensive export tree computations specifically for default imports of JSON modules
- Allow a maximum export depth to be specified in the webpack config for JSON files
  - webpack 4 only computed top-level exports for JSON: https://github.com/webpack/webpack/blob/v4.47.0/lib/JsonParser.js#L20
- Allow disabling FlagDependencyExportsPlugin entirely for JSON modules via config

**Other relevant information:**
webpack version:  5.91.0
Node.js version: v20.12.2
Operating System: macOS
Additional tools:

**Comment by alexander-akait** [comment]
> Allow a maximum export depth to be specified in the webpack config for JSON files
> webpack 4 only computed top-level exports for JSON: 
> https://github.com/webpack/webpack/blob/v4.47.0/lib/JsonParser.js#L20

I am fine with it

**Comment by alexander-akait** [comment]
Why do you use `FlagDependencyExportsPlugin` for devevelopment purposes?

**Comment by ahabhgk** [comment]
You can disable `optimization.providedExports` in development, webpack enabled it by default in development, the only case I encountered where enabling `providedExports` in development mode was effective is `re-exports + cycle reference`, `SideEffectsFlagPlugin` will use provided exports to skip the re-exports module, which avoid the error caused by cycle reference in re-exports module, but in actual usage scenarios, this situation is very rare. (I'm not sure whether there are other reasons for enabling providedExports in development by default)

In your provided reproduce, with `optimization.providedExports = false`, ~2s -> ~70ms for every rebuild

**Comment by alexander-akait** [comment]
Maybe good place to look how we can speedup it (cache? better logic? etc)

**Comment by albertxing** [comment]
We experimented with disabling `optimization.providedExports`, and while this did make the development build faster, it also silenced errors related to incorrectly named exports. For example, changing a named export while in watch mode would normally show a build error if not all imports were updated with the new name, but after removing the `providedExports` optimization this was no longer the case. I'm not sure if this is a bug or expected behaviour.

At the moment our temporary solution has been to use a slightly updated version of the [old json-loader](https://github.com/webpack-contrib/json-loader) instead of using Webpack's built-in JSON generation, but it'd be great to remove this shim and get a fix in upstream.

I'm happy spending some more time on this writing a max depth PR and potentially looking at performance optimizations when I get a chance!

**Comment by hai-x** [comment]
After look into this issue in depth

> Allow a maximum export depth to be specified in the webpack config for JSON files
webpack 4 only computed top-level exports for JSON:
[v4.47.0/lib/JsonParser.js#L20](https://github.com/webpack/webpack/blob/v4.47.0/lib/JsonParser.js#L20) 

It will make json `untreeshakable` and its key `unmangled` in production mode.

for example

```
// data.json
{
  "used": "used",
  "unused": "unused",
  "nested": {
    "used": "used",
    "unused": "unused",
    "nested": {
      "used": "used",
      "unused": "unused",
      "nested": {
        "used": "used",
        "unused": "unused",
        "nested": {
          "used": "used",
          "unused": "unused",
          "nested": { "used": "used", "unused": "unused" },
          "depth": 5
        },
        "depth": 4
      },
      "depth": 3
    },
    "depth": 2
  },
  "depth": 1
}

// index.js
import data from './data.json';
console.log(data.nested.nested.nested.nested.nested.used);
```

output with treeshaking and mangle
```js
(()=>{"use strict";const c=JSON.parse('{"cY":{"cY":{"cY":{"cY":{"cY":{"k":"used"}}}}}}');console.log(c.cY.cY.cY.cY.cY.k)})();
```


output without treeshaking and mangle when limit json nested depth
```js
(() => { "use strict"; const e = JSON.parse('{"cY":{"used":"used","unused":"unused","nested":{"used":"used","unused":"unused","nested":{"used":"used","unused":"unused","nested":{"used":"used","unused":"unused","nested":{"used":"used","unused":"unused"},"depth":5},"depth":4},"depth":3},"depth":2}}'); console.log(e.cY.nested.nested.nested.nested.used) })();
```

because we consume its exportsInfo in `FlagDependencyUsagePlugin`

https://github.com/webpack/webpack/blob/3612d36e44bda5644dc3b353e2cade7fe442ba59/lib/FlagDependencyUsagePlugin.js#L97

maybe we can adopt it in `development` mode?

**Comment by alexander-akait** [comment]
@hai-x Yeah, tested it too, I tried to improve caching, but it only solves the problem of repeated runs (but it's not really worth it if you already have cache activated), I think that the solution for the `development` mode here will be the best

>  But it will cause JsonExportsDependency to be coupled to options.mode that I don't think it's appropriate.

We can implement a new parameter - deep, `development` - for the `developer` mode I think parameter 1 is the most suitable, for the `production` - infinity.

What do you think about this, i think it would speed up development in the `development` mode well

**Comment by hai-x** [comment]
@alexander-akait 

> We can implement a new parameter - deep, development - for the developer mode I think parameter 1 is the most suitable, for the production - infinity.
What do you think about this, i think it would speed up development in the development mode well

Good idea. maybe `depth`?  `getExportsFromData` can consume it.

**Comment by alexander-akait** [comment]
@hai-x `depth` is good for me :+1:

**Comment by hai-x** [comment]
> @hai-x `depth` is good for me 👍

I will open one pr soon.

**Comment by alexander-akait** [comment]
Fixed for dev mode, in prod we still try to optimize, anyway you can set your own value if you want to speed up
