### ISSUE TITLE
Conflicting issue resolutions: #13125 & #15885 vs. #15545

### ISSUE THREAD

**Issue by bworline** [webpack/webpack#18463]
# Issue

The recommended resolution for issues #13125 & #15885 conflicts with the resolution for #15545.

#15545 is about the use of `"this"` as the `output.globalObject`.  The fix PR #15551 was to start using the `output.environment.arrowFunction` setting to generate the IIFE in umd.  Taking advantage of that fix **_requires_** one to use arrow functions.

#13125 & #15885 are about a large performance regression when enabling arrow functions in webpack-generated glue.  The regression came when `output.environment.arrowFunction` started being used to generate the IIFE.  The recommended workaround from those issues is to **_stop_** using arrow functions until the issue is fixed on the V8 side.  

# Discussion

Looking at the [V8 issue 42209446](https://issues.chromium.org/issues/42209446) that refers to [this document](https://docs.google.com/document/d/19xTAM4A75tz0xUq_velMzGA4JHEgXpyflUxXTcuNiyE/edit#heading=h.lwf44zsfrtq6) and the description of the PIFE heuristic, it's fairly clear that V8 feels that this existing heuristic is well known and tools such as webpack should continue to format IIFEs in a particular way to trigger the heuristic.  That is, they won't be fixing V8 issue 42209446.

Large projects like the one I work on are looking for ways to reduce bytes-over-wire.  Given the size of our codebase and the number of modules and exports we have, enabling arrow functions is a measurable performance win for us--or would be, if not for the performance loss due to the failure to eagerly parse and compile arrow-function IIFEs.

The fix for #15545 caused a new issue, #15885, which is the subject of _this_ issue. In addition, #15545 wasn't actually fixed in PR #15551, as you have to enable arrow functions to get the fix and that doesn't work for those that have to use standard functions.  An alternative solution for #15545 would be to set `output.globalObject` to [`"globalThis"`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis) and perhaps even explicitly disallow passing `"this"`.

# Suggested Resolution

Decouple IIFE generation from the `output.environment.arrowFunction` setting.  Create a second, separate setting called `output.environment.arrowFunctionForIIFE` that governs IIFE generation and defaults to whatever `output.environment.arrowFunction` is.  Performance testing is required to determine if this new setting should be used for only chunk-level IIFE generation or additionally for module-level IIFE generation.

**Comment by alexander-akait** [comment]
@bworline Looks like the problem was resolved on V8 side https://issues.chromium.org/issues/42209446 and https://chromium-review.googlesource.com/c/v8/v8/+/5691712, so I think we can close it now

**Comment by bworline** [comment]
Perhaps, but it could take years for that change to roll out to all of our customers, esp. corporate customers with strict, explicit, and slow upgrade policies.

**Comment by alexander-akait** [comment]
@bworline I think in the such case you can manually disable `arrowFunction` using `output.environment.arrowFunction` until customers get updates

**Comment by bworline** [comment]
The point of this issue is that that advice conflicts with the advice for #15545. 

Also, I happen to want to use arrow functions for reduced bundle size.

**Comment by alexander-akait** [comment]
@bworline Do you want to build UMD without arrow functions? Can you provide your configuration which broken? Original issues was resolved on V8 side

**Comment by jagpreetrahi** [comment]
I want to work on this issue , but i am new here to this project . Can you tell how i could be understandable
