### ISSUE TITLE
Change naming convention from *-webpack-plugin to webpack-plugin-*

### ISSUE THREAD

**Issue by gajus** [webpack/webpack#1847]
webpack has established an odd convention of suffixing plugin names with `-webpack-plugin` as opposed to a prefix `webpack-plugin-`. webpack 2 seems like a good opportunity to change this.

**Comment by Vizer** [comment]
Obviously, it makes sense to define naming convention similar to `@angular` and `@types`. So that plugins will be grouped together in config file and in `node_modules` directory.

**Comment by TheLarkInn** [comment]
Personally I like the *-webpack-plugin naming convention. It matches the format similarily to core plugins. But I don't have time to :bike: shed

**Comment by Vizer** [comment]
There is one benefit using common prefix. It might provide better autocomplete

**Comment by caub** [comment]
it allows to have them grouped in `package.json` too
