### ISSUE TITLE
[Feature request]: Support friendly worker import

### ISSUE THREAD

**Issue by axetroy** [webpack/webpack#18497]
## Feature request

The current use of Worker requires ESM

```js
new Worker(new URL('./worker.js', import.meta.url));
```

It is not very friendly to older browsers.

**What is the expected behavior?**

It should support older browsers, just like other modules

Parsing the syntax of new Worker, If a string is given as an argument, it should be a dependency of this file

**Input:**

```js
new Worker('./test.worker.js');
```

**Output:**

```js
// __webpack_require__($0) --> return "./test.worker.[contenthash].js"
new Worker(__webpack_require__($0));
```

`__webpack_require__($0)` is a javascript module that return the asset URL

**What is motivation or use case for adding/changing the behavior?**

For compatibility with older browsers, and this is more universal.

**How should this be implemented in your opinion?**

Keep the same functionality as `worker-loader`. Since `worker-loader` is no longer maintained, it should become a built-in feature of webpack5.

1. Bundle worker file (process with other loaders)
2. Emit bundled file as assets
3. Replace import statement with a wrapper

```is
// test.worker.js
self.onmessage = () => {
  // ...
}
```

Wrap into

```js
// test.worker.js
module.exports = "./asset/path/to/test.worker.js"
```

**Are you willing to work on this yourself?**
no, I can't

**Relative Issue**

https://stackoverflow.com/questions/66710729/how-do-you-use-web-workers-with-webpack-5
https://github.com/GoogleChromeLabs/worker-plugin/issues/88

I investigated many issues and found no other solution except worker-loader

**Comment by alexander-akait** [comment]
For old browsers please use:

**webpack.config.js**

```js
const path = require("path");

module.exports = [
	{
		name: "worker",
		entry: {
			// You can have any name
			name: "./src/worker.js"
		},
		mode: "development",
		devtool: false,
		target: "webworker",
		output: {
			path: path.resolve("dist/"),
			filename: "[name]-worker.js"
		}
	},
	{
		name: "application",
		dependencies: ["worker"],
		entry: "./src/entry.js",
		mode: "development",
		devtool: false,
		output: {
			path: path.resolve("dist/")
		}
	}
];
```

**entry.js**

```js
function loadWorker() {
        // To load relative to file, you can extract it in helper
	new Worker(document.currentScript.src.split('/').slice(0, -1).join('/') + '/' + "./name-worker.js");
}

loadWorker();
```

**worker.js**

```js
console.log("Worker");
// You will see `DedicatedWorkerGlobalScope`
console.log(globalThis);
```

Sorry using `new Worker('./test.worker.js');` is not loading relative to the current script, and we do not want to change the semantics of the work because this could cause problems in libraries/applications

Feel free to feedback
