### ISSUE TITLE
Multiple webpack-dev-server for multiple-compiler configs?

### ISSUE THREAD

**Issue by rubyruy** [webpack/webpack#1849]
When using an array of configurations as demonstrated [here](https://github.com/webpack/webpack/tree/master/examples/multi-compiler), `webpack-dev-server` seems to just pick the first one. Is there a way to get it to to spawn a different dev-server instance per each `devServer` key in the config array? I.e. assigning each to a different `host`/`port` and serving from a different `contentBase`.

If not, is there a way to specify exactly which config it uses? It is _always_ the first one? Will it still re-compile all configs as `webpack --watch` would? Could one pass it the `name` for a config instead? (Incidentally, what is `name` actually used for - I can't find any mention of it being used at all - and the example project doesn't show it actually being used either.)

 The whole multiple-compiler feature doesn't seem to be documented at all actually (beyond the one example) - is it actually unsupported?

**Comment by thomassuckow** [comment]
I was trying to figure out a similar issue. I have a library that I want to share in a multi-compiler setup. If I run webpack I can have it generate the output file for the library and the other compiler setups will pick it up. But webpack-dev-server doesn't put it in the filesystem so it is not found.

I suppose I may be abusing the multi-compiler feature?

**Comment by fbialek** [comment]
I have similiar problem to @rubyruy. Here is a part of my webpack config:

```
var config = {
//cut for brevity 
},
  devServer: {
    contentBase: './dist/',
    colors: true,
    inline: true
  }
}

var app1 = Object.assign({}, config, {
  name: 'app1',
  entry: './src/app1/app1',
  output: {
    path: './dist/app1',
    publicPath: '/app1/',
    filename: 'bundle1.js'
  }
})

var app2 = Object.assign({}, config, {
  name: 'app2',
  entry: './src/app2/app2',
  output: {
    path: './dist/app2',
    publicPath: '/app2/',
    filename: 'bundle2.js'
  }
})
```

When I run webpack everything works as expected: bundle1.js is in dist/app1 and bundle2.js is in dist/app2. However when I run webpack-dev-server all bundles are served from dist/app1/ - or broadly speaking  - from whatever path that is specified in output.publicPath in my first object in config (app1). 

Is this behaviour normal? For me it makes webpack-dev-server troublesome to use bc I have to specify two paths in my html files - one for wds and one for webpack. Is there a way to specify paths in webpack-config (using multi-compiler) that will be respected by webpack-dev-server?

**Comment by jeroentradecast** [comment]
Running into this problem now. I have multiple configs for different setups, and I'd like webpack-dev-server to target a specific one, or even all if I'd like (passing on different ports per config).

**Comment by alexisgahon** [comment]
Having the same problem/needs. Any update on this ? @sokra

**Comment by iMoses** [comment]
I am running multi-compiler configs for a single web-server, different entries have different resolving strategies etc. I'd appreciate a solution that will allow for multi-compiler configs to run under a single webpack-dev-server host & port.

**Comment by hovissimo** [comment]
The i18n-webpack-plugin requires the use of multiple configurations because different entry points in a single config can't be uniquely configured to use the plugin for different languages (per the webpack configuration documentation at https://webpack.github.io/docs/configuration.html).

See an example multi-config setup at https://github.com/webpack/webpack/tree/master/examples/i18n (this same project!)

Ideally, using the webpack dev server with the example setup in the i18n plugin all languages would be available from a single instance of the dev server.

**Comment by iMoses** [comment]
You can check out the PR I made in order to fix it, let me know if you find any issues with it, and please upvote it if you find it useful.

https://github.com/webpack/webpack-dev-middleware/pull/151

**Comment by SpaceK33z** [comment]
Hey, could anyone who uses multi-compiler verify that @iMoses's PR fixes the issue (webpack/webpack-dev-middleware#151)?

**Comment by SpaceK33z** [comment]
Closing because there is a ticket for this on webpack-dev-server; https://github.com/webpack/webpack-dev-server/issues/641.

**Comment by gruckion** [comment]
> I was trying to figure out a similar issue. I have a library that I want to share in a multi-compiler setup. If I run webpack I can have it generate the output file for the library and the other compiler setups will pick it up. But webpack-dev-server doesn't put it in the filesystem so it is not found.
> 
> I suppose I may be abusing the multi-compiler feature?

Webpack dev server won't put files on the filesystem because the contents are held in memory.
