### ISSUE TITLE
require.ensure arrow function fails

### ISSUE THREAD

**Issue by brigand** [webpack/webpack#1851]
When compiling code that uses require.ensure, an arrow function causes weird broken behavior. 1.bundle.js isn't created, the require() isn't rewritten, and the require.ensure call is just stripped.

To repro run `webpack a.js bundle.js` with these files and no webpack.config.js.

```js
// a.js
require.ensure([], () => {
  require('./b');
});

// b.js (empty)
```

Excerpt from bundle.js
```js
!/* require.ensure */(() => {
  require('./b');
}(__webpack_require__));
```

**Comment by sokra** [comment]
fixed in webpack 2

**Comment by brigand** [comment]
@bebraw this is a bug report.
