### ISSUE TITLE
[ProvidePlugin] force load modules whether use it or not

### ISSUE THREAD

**Issue by CrazyWood007** [webpack/webpack#18528]
## Feature request

**What is the expected behavior?**
With some config option like `force`, generate `window.someModule = require('someModule')` without checking whether use `window.someModule` or not.

**What is motivation or use case for adding/changing the behavior?**
Module uses globals config `{react: 'React'}` can't work well without `window.React`.
I use this module in HTML by `<script>`.
So I want to generate `window.React = require('react')` in the top of my script automatically.

**How should this be implemented in your opinion?**
Support using some option to configure the behavior of `ProvidePlugin`.

**Are you willing to work on this yourself?**
No

**Comment by alexander-akait** [comment]
Sorry, it is out of scope `ProvidePlugin`, you can use `expose-loader` for this - https://github.com/webpack-contrib/expose-loader/tree/master
