### ISSUE TITLE
webpack5 devtools hidden-source-map does not generate sourcemap

### ISSUE THREAD

**Issue by oopses** [webpack/webpack#18547]
webpack: 5.92.1

set webpack config  devtools hidden-source-map does not generate sourcemap，set source-map  will generate

I have searched for the following similar questions and have not found a solution:

https://github.com/webpack/webpack/issues/5491

https://github.com/webpack/webpack/issues/5569

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
