### ISSUE TITLE
Modules builded by Webpack dont work with SSH

### ISSUE THREAD

**Issue by tamtakoe** [webpack/webpack#18549]
# Bug report

**What is the current behavior?**
I can't use builded modules for target web for SSR applications because of
```sh
5:36:22 PM [vite] Error when evaluating SSR module /main.server.mjs:
|- ReferenceError: document is not defined (or self is not defined)
```
and the same errors.

This is because
```js
/******/ 	/* webpack/runtime/jsonp chunk loading */
/******/ 	(() => {
/******/ 		__webpack_require__.b = document.baseURI || self.location.href;
```

**What is the expected behavior?**

Webpack should check that document/self doesn't exist and avoid the errors. E.g.
```js
typeof document !== 'undefined' && document.baseURI || typeof self !== 'undefined'  && self.location.href;
```

This is my responsibility to define which browser api should be mocked for SSR in my plugin, which fallback should I use etc. But Webpack break all work in the SSR case.

My for example webpack.config
https://github.com/tamtakoe/base-select/blob/master/webpack.config.js

**Other relevant information:**
webpack version:  5.92.1
Node.js 20.9.0:
Operating System: MacOS Sonoma

**Comment by tamtakoe** [comment]
Works with 
```
output: {
      chunkLoading: false,
}
```
Anyway I have no clue why Webpack shows error if document/self undefined if no option e.g. to define this default value

**Comment by nickbabcock** [comment]
I see this is same stacktrace for next.js edge runtime targeted endpoints where web workers are used on the client. 

Ref: https://github.com/vercel/next.js/issues/67910

**Comment by alexander-akait** [comment]
I have looked into your problem and you want a universal environment, i.e. `target: ["node", "web"]`, unfortunately this is not possible for `umd`, you have `url('data:image/svg+xml;utf8,...)`, webpack handles this as a request and he needs it `__webpack_require__.b` to loader it:

- ignore `data:image/svg+xml` using configuration
- using `chunkLoading: false` as you written above
- using ESM, still in `experiments` for universal target

Feel free to feedback

**Comment by Coiggahou2002** [comment]
If you are using Webpack5 + Vue2 to build an SSR framework, `vue-server-renderer` will have related problems when using Vue2 under Webpack5. The `server-bundle.js` packaged by webpack5 will have this statement below. (see [url-assets](https://webpack.js.org/guides/asset-modules/#url-assets))
```js
__webpack_require__.b = require('url').pathToFileURL(__filename)
```
but `vue-server-renderer` [wraps a layer of function](https://github.com/vuejs/vue/blob/9e88707940088cb1f4cd7dd210c9168a50dc347c/packages/server-renderer/src/bundle-renderer/create-bundle-runner.ts#L67C5-L67C20) and provides empty `__dirname` and `__filename`. [This PR](https://github.com/vuejs/vue/pull/12242) provides a solution but has not been officially merged by Vue so far.
