### ISSUE TITLE
Getting React Dev Tools To Work With Webkit

### ISSUE THREAD

**Issue by Kay2dan** [webpack/webpack#1858]
Apologies if this kind of post is not allowed, however, I feel this issue might merit some insight. I posted this question on Stackoverflow (http://stackoverflow.com/questions/34607345/getting-react-developer-tools-to-work-with-webpack) & I am still looking for a solution.

Summary: My app is using React & being served via Webpack. However, both Firefox & Chrome React Developer Tools fail to identify React & thus are inaccessible. FelipeT. @Stackoverflow was kind enough to spend some time, however, we were unable to resolve this.

Please let me know if I should paste the content of Webpack.config.js & .babelrc & package.json files here for reference. I have not pasted them in order to keep the post size small.

Any guidance / review would be much appreciated.

**Comment by bebraw** [comment]
Is this relevant still? The dev tools work for me in the current version of React. You don't need to expose React as a global anymore

**Comment by Kay2dan** [comment]
It still is for me, unfortunately. I am unable to use React Dev Tools both in FF Developer Version & Chrome with webpack. Without webpack, it seems to work fine. 
Ive ignored React Dev Tools as we need Webpack more than that.

**Comment by bebraw** [comment]
@Kay2dan Can you try with webpack 2 beta?
