### ISSUE TITLE
PnP API is not discovered when compiling file from different directory, leading to Module not found error

### ISSUE THREAD

**Issue by AtofStryker** [webpack/webpack#18586]
# Bug report

**What is the current behavior?**

It looks like the webpack compiler invoked in a process that does not have `pnp` enabled is unable to discover `pnp` dependencies for the file it is compiling in a different directory. This used to work in webpack 4 with `pnp-webpack-plugin`

**If the current behavior is a bug, please provide the steps to reproduce.**

I have created a reproduction [repository](https://github.com/AtofStryker/webpack-pnp-reproduction) in order to recreate the problem/issue

**What is the expected behavior?**

I would expect either a way to provide the webpack compiler with the `yarn PnP` api instance or the instance is automatically discovered in order to compile the file with the correct dependencies. Is the first option possible? It looks like it may be as a [resolver option](https://github.com/webpack/webpack/blob/main/types.d.ts#L11771) but I'm unsure on how to consume it properly.  Any ideas? Any help would be much appreciated!

**Other relevant information:**
webpack version:  5.93.0
yarn version: 4.1.1
Node.js version: 20.15.1
Operating System: Mac OS Sonoma 14.3

**Comment by alexander-akait** [comment]
Duplicate https://github.com/webpack/enhanced-resolve/issues/273?

**Comment by AtofStryker** [comment]
@alexander-akait I actually think there is an issue in my reproduction. I was able to get [`webpack 4`](https://github.com/AtofStryker/webpack-pnp-reproduction/tree/webpack-4) and [`webpack 5`](https://github.com/AtofStryker/webpack-pnp-reproduction/tree/webpack-5) to work upon revisiting, and it looks like updating `enhanced-resolve `from `5.15.0` to `5.17.0` fixed the issue? I am going to close this as it doesn't seem to be an issue and more of an operator error on my end 🥴 .
