### ISSUE TITLE
Provide a way to get a worker bundle without wrapping in `new Worker()`

### ISSUE THREAD

**Issue by tomprince** [webpack/webpack#18616]
## Feature request

**What is the expected behavior?**

I'd like some way to get the URL of a module that is to be loaded into a web worker, to be able to pass it to some existing code
that creates a webworker, or that passes it to an existing webworker to be loaded into it.

**What is motivation or use case for adding/changing the behavior?**

I'm using monaco, and trying to create a custom typescript web worker for the editor. To do so, I need to pass
the URL of a script to be loaded (via `importScripts`) in an existing worker.
```javascript
languageDefaults.setWorkerOptions({
  customWorkerPath: workerUrl,
});
```

At the moment, I'm using a dedicated module to get this to work:
```javascript
// Webpack has syntax for passing the URL of a script to be loaded in a web worker to
// various functions (such as `new Worker(...)`). However, since we just want the URL of
// the script, we tell webpack that in this module, `String(new URL(...))` should be
// treated as creating a web worker. That gives us access to the URL of the script,
// which we can pass to monaco.
const url = String(
  new URL(
    /* webpackChunkName: "custom-ts" */
    "./worker.ts",
    import.meta.url,
  ),
);
export default url;
``` 
specifying `parser: { worker: ["String()"] }`  for that module.

**How should this be implemented in your opinion?**

This can perhaps be implemented by better documenting the syntax for `parser.worker`. I tried a number of ways to define a `getWorkerURL` function which was either the identity function, or an alias for `String`, which would be recognized by the worker plugin but couldn't figure out the right incantation.

**Are you willing to work on this yourself?**
possibly

**Comment by alexander-akait** [comment]
You can use multi compiler mode and bundle your worker separately https://github.com/webpack/webpack/blob/main/examples/multi-compiler/README.md, just set `target: "webworker"`
