### ISSUE TITLE
Abort clear dir when dir have .git folder

### ISSUE THREAD

**Issue by nexusprime-here** [webpack/webpack#18610]
## Feature request

**What is the expected behavior?**
When clean output is enabled, abort clear if current dir have .git file, or not delete it.

**What is motivation or use case for adding/changing the behavior?**
There's no reason to delete a .git directory, and it can save some inattentive peaples

**How should this be implemented in your opinion?**
A simple conditional verifing what have on folder can do this.

**Are you willing to work on this yourself?**
sure

**Comment by alexander-akait** [comment]
You can use `CleanPlugin` and the `keep` option https://github.com/webpack/webpack/blob/main/lib/CleanPlugin.js#L329

**Comment by nexusprime-here** [comment]
> You can use `CleanPlugin` and the `keep` option https://github.com/webpack/webpack/blob/main/lib/CleanPlugin.js#L329

Bro it's different. It's just a security feature, not a new customization option

**Comment by alexander-akait** [comment]
I don't see any security features here, if you need to disable clean if directory has .git, just make it check in your webpack.config.js and disable `clean`
