### ISSUE TITLE
ENHANCEMENT: nodemon-like rs command in watch mode

### ISSUE THREAD

**Issue by jlchereau** [webpack/webpack#1863]
Like webpack, nodemon uses chokidar to watch file changes. Nevertheless, there are scenarios where chokidar does not trigger file changes (I am experiencing one with a custom webpack plugin that converts nodeJS server side i18n JSON resource files into client side JS files - rebuild is not triggered in watch mode when JSON files are modified).

[nodemon has an "rs" command that forces a restart](https://github.com/remy/nodemon#manual-restarting). It would be nice to have the same in webpack watch mode.

**Comment by bebraw** [comment]
Moved to https://github.com/webpack/webpack-cli/issues/12 . Track there. Thanks.
