### ISSUE TITLE
[Feature request] Port resolveWeak to javascript/esm

### ISSUE THREAD

**Issue by guillaumewuip** [webpack/webpack#18633]
## Feature request

**What is the expected behavior?**
CommonJS code allows the usage of `require`, and so the corresponding webpack rule [type](https://webpack.js.org/configuration/module/#ruletype) `javascript/auto` will transform `require.resolveWeak` into the corresponding runtime code.

ESM code does not allow the usage of require, and so `javascript/esm` type does not transform `require.resolveWeak`, as we don't expect to see `require` in this context.

Still, libraries like `@lodable/components` or `react-loadable` leverage this `require.resolveWeak` capability to implement their code-splitting abstractions. When generating ESM code that use them, we end up with `require.resolveWeak` inside ESM, which webpack does not understand by default. This creates runtime failures.

**What is motivation or use case for adding/changing the behavior?**
As far as I know multiple options can mitigate the issue:
1. not using ESM
2. not using those libraries 
3. forcing `javascript/auto` for the concerned ESM files (see issue [here](https://github.com/webpack/webpack/issues/15372))

   ```js
    {
      test: /\.js$/,
      include: /path\/to\/esm\/files\/with\/resolveWeak/,
      type: 'javascript/auto',
    }
   ```

No option is perfect here:
1. is not future-proof
2. means that we lose key features of those libs like server-side rendering chunk extractions (eg. `@loadable/server`)
3. requires extra config (and maybe it has negative side effects on other aspects like performances?)

**How should this be implemented in your opinion?**
Webpack started to leverage `import.meta`, which is free to use, to implement `import.meta.webpackContext`, for [example](https://github.com/webpack/webpack/pull/15446). 

Can we imagine following this path to port the `resolveWeak` capability to `javascript/esm` also? This is also mentioned in this [comment](https://github.com/webpack/webpack/issues/15372#issuecomment-1070234970).

This way, code historically leveraging `require.resolveWeak` will be able to migrate to `import.meta.resolveWeak` or something similar when bundled in ESM.

**Are you willing to work on this yourself?**
I can help, but I've never contributed to webpack so this might be a very challenging tasks for me 😅 
I'm probably better suited to do update PRs on https://github.com/gregberge/loadable-components/ and https://github.com/swc-project (loadable plugin).

**Comment by alexander-akait** [comment]
What is `requireWeak`? You can use `import.meta.webpackContext('./directory', { mode: "weak" });`

**Comment by guillaumewuip** [comment]
Sorry, I mean `require.resolveWeak` 🤦 I've fixed the issue title and the description accordingly.

> You can use import.meta.webpackContext('./directory', { mode: "weak" });

Does it mean that code that today is written with `require.resolveWeak` like so

```js
require.requireWeak('./OtherComponent.js')
```

can be migrated to this in ESM without anything more to handle?

```js
import.meta.webpackContext('./OtherComponent.js', { mode: "weak" });
```

**Comment by alexander-akait** [comment]
Let's close in favor https://github.com/webpack/webpack/issues/16693, we don't support `resolve` for ESM right now, so we need to implement `import.meta.resolve` and `import.meta.resolveWeak`
