### ISSUE TITLE
Webpack not extracting "default" with externals and mjs file extension

### ISSUE THREAD

**Issue by AlekseiRusanov** [webpack/webpack#18632]
# Bug report

**What is the current behavior?**

Webpack does not extract the default export when I mark one dependency as external and there's another dependency the exports a file with .mjs extension.
That is, instead of outputting something like this (which extracts "default" from the module)

```
/* harmony import */ var external_dep__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(external_dep__WEBPACK_IMPORTED_MODULE_0__);
external_dep__WEBPACK_IMPORTED_MODULE_0___default()();
```

It outputs just this
`external_dep__WEBPACK_IMPORTED_MODULE_0__();`

**If the current behavior is a bug, please provide the steps to reproduce.**

I created my own configuration: https://github.com/AlekseiRusanov/Webpack_Issue.
It has the following dependency graph:
Main App -> internal_dep -> external_dep
external_dep is marked as externals in webpack config:

```
    externals: (ctx, callback) => {
        if(["external_dep"].indexOf(ctx.request) !== -1){
            callback(null, `assign-properties ${ctx.request}`);
            return;
        }
        callback()
    }
	
```
internal_dep has "index" file that exports one function as default

```
import external_dep_default from 'external_dep'
export default () => {
    console.log("Hello from internal_js_dep");
    external_dep_default();
}
```

If internal_dep exports "index" with .mjs extension (in package.json):
```

  "exports": {
    ".": {
      "import": {
        "default": "./index.mjs"
      }
    }
  },
  
```
Then after building Main App, I see this in the output:

```
/* harmony import */ var external_dep__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! external_dep */ "external_dep");

/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (() => {
    console.log("Hello from internal_mjs_dep");
    external_dep__WEBPACK_IMPORTED_MODULE_0__();
});

/***/ })
```
Which is wrong because "external_dep__WEBPACK_IMPORTED_MODULE_0__" does not equal "default".

If choose not to mark "external_dep" as "external", or if "internal_dep" exports index with .js extension instead of .mjs then it works as expected:

```
/* harmony import */ var external_dep__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! external_dep */ "external_dep");
/* harmony import */ var external_dep__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(external_dep__WEBPACK_IMPORTED_MODULE_0__);

/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (() => {
    console.log("Hello from internal_js_dep");
    external_dep__WEBPACK_IMPORTED_MODULE_0___default()();
});

```

**What is the expected behavior?**

I expect it to extract "default" correctly, even if internal_dep exports index.mjs and I mark "external_dep" as "external", i.e. like this:

```
/* harmony import */ var external_dep__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! external_dep */ "external_dep");
/* harmony import */ var external_dep__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(external_dep__WEBPACK_IMPORTED_MODULE_0__);

/* harmony default export */ const __WEBPACK_DEFAULT_EXPORT__ = (() => {
    console.log("Hello from internal_mjs_dep");
    external_dep__WEBPACK_IMPORTED_MODULE_0___default()();
});
```

**Other relevant information:**
webpack version:
5.93.0
Node.js version:
v20.11.1
Operating System:
Windows 11
Additional tools:
None

**Comment by alexander-akait** [comment]
Please use `callback(null, `assign-properties ${ctx.request}.default`);`, `assign-properties` is just for assign and know nothing about ESM

Feel free to feedback
