### ISSUE TITLE
Consider new configuration option "data"

### ISSUE THREAD

**Issue by DarkPark** [webpack/webpack#1864]
Instead of an `entry` option it would be nice to use sometimes option `data` where it's possible to put dynamically generated JavaScript code as entry point.

configuration object example: 

``` js
{
    context: __dirname + "/app",
    data: "require('module1'); require('module2'); // some more code",
    output: {
        path: __dirname + "/dist",
        filename: "main.js"
    }
}
```

The same idea is used in [node-sass](https://github.com/sass/node-sass#data), [jade](http://jade-lang.com/api/) and other compilers.

**Comment by IngwiePhoenix** [comment]
This is rather hard, since the file is used as the base to resolve relative paths. What I could see instead is something like:

```
{
  entry: {
    main: {
        data: "... js code ...",
        path: path.join(__dirname, "main.js")
    }
  }
```

Basically, an object of `.data` and `.path`, so that webpack could treat the string as if it was of that path, making relative require possible again.

**Comment by DarkPark** [comment]
Good as well.
But is this really necessary? It's possible to give automatically a standard file name for example `stdin` (as they do in `node-sass`) and use `context` option for path so my first example would resolve to this path: 

```js
__dirname + "/app" + "/stdin"
```

**Comment by sokra** [comment]
You can use `entry: "./some-file-generating-code.js!"` with

``` js
// some-file-generating-code.js
module.exports = function() {
  return "... code ...";
}
```

**Comment by DarkPark** [comment]
I would prefer not to save this generated code to not mess with user's edited/created files.
