### ISSUE TITLE
Stats object; assets; related - type mismatch

### ISSUE THREAD

**Issue by SStranks** [webpack/webpack#18657]
# Bug report

**What is the current behavior?**

The stats object produced by setting the CLI flag `--json=compilation-stats.json` has a mismatch between the returned value and the type definition _if_ there are no entries for the 'related' property under assets object. It returns an empty object, as opposed to an empty array which the type definition implies it should.

![image](https://github.com/user-attachments/assets/44803f33-4228-4090-ac2c-5f15e8ad5cd7)

**If the current behavior is a bug, please provide the steps to reproduce.**

Set the CLI flag `--json=compilation-stats.json`, and have a build asset with no related files.

**What is the expected behavior?**

If there are no entries for the related property an empty array should be returned - alternatively the type definition should match the current output if the source code is acting as it should.

**Other relevant information:**
webpack version:  5.90.1
Node.js version: 20.9.0
Operating System: WSL2 Ubuntu
Additional tools:

**Comment by alexander-akait** [comment]
It is different types, look at output:
```
"assets": [
    {
      "type": "asset",
      "name": "one.js",
      "size": 3627,
      "emitted": true,
      "comparedForEmit": true,
      "cached": false,
      "info": {
        "javascriptModule": false,
        "related": { "sourceMap": "one.js.map" },
        "size": 3627
      },
      "chunkNames": ["one"],
      "chunkIdHints": [],
      "auxiliaryChunkNames": [],
      "auxiliaryChunkIdHints": [],
      "filteredRelated": 0,
      "related": [
        {
          "type": "sourceMap",
          "name": "one.js.map",
          "size": 3245,
          "emitted": false,
          "comparedForEmit": true,
          "cached": false,
          "info": { "development": true, "size": 3245 },
          "chunkNames": [],
          "chunkIdHints": [],
          "auxiliaryChunkNames": ["one"],
          "auxiliaryChunkIdHints": [],
          "related": {},
          "chunks": [],
          "auxiliaryChunks": [101],
          "isOverSizeLimit": false
        }
      ],
      "chunks": [101],
      "auxiliaryChunks": [],
      "isOverSizeLimit": false
    }
  ],
```

The first `related` is an array - all assets related to this, the second is an object with `Record<string, any>` type, where we store all related assets and type of relation (is it source map or compressed or something else)

**Comment by alexander-akait** [comment]
Can you show me a code how you use it?

**Comment by alexander-akait** [comment]
Maybe you can show me a structure when you get `related: {}`

**Comment by SStranks** [comment]
> Maybe you can show me a structure when you get `related: {}`

Your code example does, at line 32. If I copy across that code into an object with the StatsCompilation type applied it gives the type error too.

> Can you show me a code how you use it? Because it should be `Array`

I'm using Webpack 5.90.1, with Node v20.1.0. I assumed it should be an Array, the type says it should be, but it's not.

Literally all I've done is follow the Webpack documentation that says add `--profile --json=compilation-stats.json` flag to the CLI. In my webpack.config I have a stats object - for the example above I removed all its properties except 'assets: true' just to be sure. 

Then all I did was change the extension of the json output file to ts, assign the object to a variable and add the StatsCompilation type to it. It's the only type-error in the object structure.

**Comment by alexander-akait** [comment]
Can you show me a code which generates `{}`? Maybe bug in non official plugins, because I can't reproduce it

**Comment by SStranks** [comment]
[codesandbox.io](https://codesandbox.io/p/devbox/fervent-shannon-449zhv?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clzluesej0005356l3obz10cn%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clzluesei0002356lfw08a07l%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clzluesei0003356l3u5kg8o3%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clzluesei0004356ln237kb5u%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clzluesei0002356lfw08a07l%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clzlueseh0001356ln2skx0he%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clzluicww0023356l19xaj5dr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A21%252C%2522startColumn%2522%253A5%252C%2522endLineNumber%2522%253A21%252C%2522endColumn%2522%253A5%257D%255D%252C%2522filepath%2522%253A%2522%252Fconfig%252Fwebpack.prod.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clzluesei0002356lfw08a07l%2522%252C%2522activeTabId%2522%253A%2522clzluicww0023356l19xaj5dr%2522%257D%252C%2522clzluesei0004356ln237kb5u%2522%253A%257B%2522id%2522%253A%2522clzluesei0004356ln237kb5u%2522%252C%2522activeTabId%2522%253A%2522clzlueu46000k356l9x4x218v%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522SETUP_TASKS%2522%252C%2522id%2522%253A%2522clzlueu46000k356l9x4x218v%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clzluesei0003356l3u5kg8o3%2522%253A%257B%2522id%2522%253A%2522clzluesei0003356l3u5kg8o3%2522%252C%2522activeTabId%2522%253A%2522clzlugfv00012356lndoj0lx0%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%252C%2522id%2522%253A%2522clzlugfv00012356lndoj0lx0%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Afalse%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

This is a codesandbox I found which uses Webpack 5.73.0. I tweaked their build script (build.js) to output the compilation-stats.json, added in the stats object in the prod webpack config. Same as in my local project. It produces the same result; see src/compilation-stats.ts.
