### ISSUE TITLE
Async imports in tree-shaken functions still end up in the bundle

### ISSUE THREAD

**Issue by abettadapur** [webpack/webpack#18653]
# Bug report

**What is the current behavior?**
Dynamic imports that are tree-shaken away still end up including their contents in the bundle. This does not occur with re-exports. See code example below.

**If the current behavior is a bug, please provide the steps to reproduce.**
```typescript
// barrel.ts
export async function getAsyncChunk() {
    const module = await import('./lazy');
    return module.foo;
}

export function doSomething() {
    console.log("Done")
}

// entry.ts
import { doSomething } from "./barrel"
doSomething()
```
With the above code, Webpack will treeshake and eliminate `getAsyncChunk`. However, it will create chunks for `lazy` if `asyncChunks: true`, and will bundle the code in the main bundle if `asyncChunks: false`. 

The following code works as expected
```typescript
// wrapper.ts
export async function getAsyncChunk() {
    const module = await import('./lazy');
    return module.foo;
}

// barrel.ts
export { getAsyncChunk } from './wrapper'

export function doSomething() {
    console.log("Done")
}

// entry.ts
import { doSomething } from "./barrel"
doSomething()
```
Now, the contents of `lazy` are not included in the final output at all.

Repro project: https://github.com/abettadapur/webpack-chunk-treeshake-repro

**What is the expected behavior?**

I'd expect that because `getAsyncChunk` was eliminated from the final bundle, the async imports it contains should also be eliminated.

**Other relevant information:**
webpack version:  5.91.0
Node.js version: 20.x
Operating System: MacOS Sonoma

**Comment by alexander-akait** [comment]
This is expected, because removing dead code is on `terser` side (set `optimization.minimize` to false to see the code what webpack generates), so yes, chunk will be outputed, dynamic imports are not analizable like `import ... from ...` and we know nothing about your code execution (and logic when something will be called). Technically this can be solved, but we will need a second time to build the graph, which will be extremely bad for performance. Also the main generated code doesn't containt any extra code for the lazy chunk, so it seems to me that this logic is the best solution. 

Feel free to feedback

**Comment by abettadapur** [comment]
Could you explain this a bit more to me? 

Why can we eliminate the import from `'./lazy'` in this case
```typescript
import {lazyLib} from "./lazy"
export function foo() {
   return lazyLib
}
```


But not in this case?
```typescript
export function foo() {
   return await import('./lazy')
}
```

Does it have something to do with module concatenation? How is the static import in case 1 actually eliminated?


As for re-exports, I assume we can eliminate the chunk entirely here because SideEffectsFlagPlugin actually modifies the graph according to `usedExports`?

**Comment by abettadapur** [comment]
@alexander-akait In general, this seems quite unintuitive to me and should at least be documented somewhere in the tree shaking docs

**Comment by abettadapur** [comment]
And sorry, last thing

With `usedExports` on, Webpack is clearly aware that `getAsyncChunk` is unused, as it adds 

```
/* unused harmony export getAsyncChunk */
```

So can't there be a process in a single compile pass where we analyze these unused exports for async imports like this?

**Comment by alexander-akait** [comment]
Because `import()` is not analizable before execution (like `import ... from ...`), it is a dynamic code, we don't know when you will call it, terser just remove unused code, so you don't have `getAsyncChunk`, but webpack don't know it
