### ISSUE TITLE
Pragma style with eval-source-map devtool does not follow documentation

### ISSUE THREAD

**Issue by keirlawson** [webpack/webpack#1865]
Documentation states that the pragma style for source maps defaults to #, yet I'm finding with Webpack 1.12.10 with devtool set to eval-source-map, the pragma style seems to default to @, causing Firefox to complain:

`Using //@ to indicate sourceMappingURL pragmas is deprecated. Use //# instead`

**Comment by sokra** [comment]
> Documentation states that the pragma style for source maps defaults to #

Propably already updated for webpack 2...

You can specify: `devtool: "#eval-source-map"`

**Comment by ivanistheone** [comment]
I'm getting the same annoying warning in FF 43 using webpack 1.12.11. I can confirm  `//@ ` is used in the source.

Is there a webpack confg/setting I could tweak to fix this? Or maybe there a way to disable this warning in FF? Will updating to a more recent version of webpack fix this?

**Comment by cageygee3** [comment]
I'm also seeing this. Adding a hash to the front of the `devtool` setting string does fix the problem, but indicates that the documentation is wrong about the default.

**Comment by pavel-zubkou** [comment]
I updated documentation to clarify defaults for each major version. Change could be seen at https://github.com/webpack/docs/wiki/configuration/_compare/207d9e5b0e8d69b1bdd15675e1fb5a40ab29457c...3c4be00157ddad325e3aa52e2d99a01accfcb6b2

@sokra Could you please review and publish that change?

**Comment by irnc** [comment]
I updated documentation to clarify defaults for each major version. Change could be seen at https://github.com/webpack/docs/wiki/configuration/_compare/207d9e5b0e8d69b1bdd15675e1fb5a40ab29457c...3c4be00157ddad325e3aa52e2d99a01accfcb6b2

@sokra Could you please review and publish that change?

**Comment by pksjce** [comment]
This issue was moved to webpack/webpack.io#120
