### ISSUE TITLE
output.iife and output.library.type = 'umd' used together will generate wrong code

### ISSUE THREAD

**Issue by hardfist** [webpack/webpack#18687]
# Bug report

**What is the current behavior?**
use `output.iife=true` and `output.library.type = 'umd'` together will generate wrong code.
```js
     })(self, () => {
          return "use strict"; // wrong here cause iife wrapper is removed 
// The require scope
var __webpack_require__ = {};

/************************************************************************/
// webpack/runtime/define_property_getters
(() => {
__webpack_require__.d = function(exports, definition) {
	for(var key in definition) {
        if(__webpack_require__.o(definition, key) && !__webpack_require__.o(exports, key)) {
            Object.defineProperty(exports, key, { enumerable: true, get: definition[key] });
        }
    }
};
})();
```
**If the current behavior is a bug, please provide the steps to reproduce.**
https://github.com/hardfist/github-webpack-iife-bug

**What is the expected behavior?**
I can think of two solutions here
* don't remove wrap iife even when use set iife:false, and give warning to users
* when iife and type: 'umd' set together, throw error 

**Other relevant information:**
webpack version:  5.38.1
Node.js version:22
Operating System: macos
Additional tools:

**Comment by alexander-akait** [comment]
@hardfist 

> don't remove wrap iife even when use set iife:false, and give warning to users

I think it is better for DX

**Comment by hardfist** [comment]
> @hardfist
> 
> > don't remove wrap iife even when use set iife:false, and give warning to users
> 
> I think it is better for DX

agree, I will make a pr later to fix this
