### ISSUE TITLE
Error destructuring from default import if a default property has the same name as a named export in ESM module

### ISSUE THREAD

**Issue by EJLearner** [webpack/webpack#18692]
# Bug report

**What is the current behavior?**

Please see the provided repo. In an ESM module. If a property on an object exported by default and a named import use the same name, destructuring of the imported default does not get the correct value if the named import is also used. The compiled code references a key that doesn't exist.

https://github.com/EJLearner/webpack-issue

**What is the expected behavior?**

Instead of the compiled destructuring code referencing a non-existent key. It should use the correct object key from the code.

**Other relevant information:**
webpack version:  5.93.0
Node.js version: seen in node 19 and node 20
Operating System: seen in redhat linux and windows 10

**Comment by alexander-akait** [comment]
Thank you for report, the problem is known and has already been fixed - https://github.com/webpack/webpack/pull/18676, release will be tomorrow

feel free to feedback
