### ISSUE TITLE
Build takes twice as long with >=5.92.0 compared to 5.91.0

### ISSUE THREAD

**Issue by mandykoh** [webpack/webpack#18694]
# Bug report

**What is the current behavior?**

Our project takes around 55 sec to build with Webpack versions 5.92.0 and later (tested up to 5.93.0), compared to 24 sec on 5.91.0 and earlier with no other changes.

```
⬡ webpack: 673 assets
  runtime modules 1.9 MiB 1835 modules
  orphan modules 408 KiB [orphan] 209 modules
  built modules 14.5 MiB (javascript) 5.88 MiB (asset) [built]
    javascript modules 13.4 MiB
      modules by path ./node_modules/ 2.76 MiB 753 modules
      modules by path ./src/ 10.6 MiB 559 modules
      ./languages/ lazy ^\.\/.*\.json$ namespace object 160 bytes [optional] [built] [code generated]
    asset modules 9.56 KiB (javascript) 5.88 MiB (asset) 233 modules
    json modules 1.11 MiB
      optional modules 929 KiB [optional] 7 modules
      modules by path ./src/ 78.4 KiB
        …
  webpack 5.92.0 compiled successfully in 55360 ms
```

A very long time seems to be spent at this stage:

```
● Webpack █████████████████████████ sealing (89%)
 after hashing
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

Build times similar to the previous version:

```
⬡ webpack: 673 assets
  runtime modules 1.9 MiB 1835 modules
  orphan modules 408 KiB [orphan] 209 modules
  built modules 14.5 MiB (javascript) 5.88 MiB (asset) [built]
    javascript modules 13.4 MiB
      modules by path ./node_modules/ 2.76 MiB 753 modules
      modules by path ./src/ 10.6 MiB 559 modules
      ./languages/ lazy ^\.\/.*\.json$ namespace object 160 bytes [optional] [built] [code generated]
    asset modules 9.56 KiB (javascript) 5.88 MiB (asset) 233 modules
    json modules 1.11 MiB
      optional modules 929 KiB [optional] 7 modules
      modules by path ./src/ 78.4 KiB
        …
  webpack 5.91.0 compiled successfully in 24074 ms
```

**Other relevant information:**
webpack version:  See above
Node.js version: 20.16.0
Operating System: macOS 14.6.1
Additional tools: Svelte project (predominantly compiled static HTML/JS)

Let me know how I can help diagnose.

**Comment by alexander-akait** [comment]
HM, can you profile or provide reproducible test repo? I don't see any regressions, even more we are a little bit faster https://webpack.github.io/benchmark/ since June

**Comment by alexander-akait** [comment]
The latest perf regression was on `terser` side. Do you have a problem for producation mode or both?

**Comment by mandykoh** [comment]
Production seems fine. Looks like it's only affecting development mode (sits at "sealing (89%)" for a long time).

How do I profile?

**Comment by alexander-akait** [comment]
https://webpack.js.org/plugins/profiling-plugin/ or more deeply - https://developer.chrome.com/docs/devtools/performance/nodejs

**Comment by mandykoh** [comment]
After dragging the events `.json` into Chrome, it thinks for a bit then says this:

![Screenshot 2024-08-21 at 08 37 22](https://github.com/user-attachments/assets/20321466-7913-4cd3-b789-3ce9c290d326)

Not sure how to troubleshoot that.

**Comment by alexander-akait** [comment]
@mandykoh Can you put the file here?

**Comment by mandykoh** [comment]
It's quite large, at 293 MB.

**Comment by alexander-akait** [comment]
@mandykoh can you try https://github.com/webpack/webpack/issues/18458 

> It's quite large, at 293 MB. Maybe I'll see if I can come up with a minimal repro instead.

Feel free to upload it in any place

**Comment by mandykoh** [comment]
No minimal repro just yet but I've narrowed it down to using `devtool: 'source-map'`. Without it, 5.92.0 is very comparable to 5.91.0.

**Comment by alexander-akait** [comment]
Weird, we don't have changes in source maps for these versions, maybe you update other tools too and enable source map generation?

**Comment by mandykoh** [comment]
Don't think so—I can trigger the difference in build times by literally only changing the Webpack version.

Using `eval` source maps still seems to be fast, but other options (eg inline) result in the large build time difference.

**Comment by alexander-akait** [comment]
@mandykoh We don't have any changes for devtools - https://github.com/webpack/webpack/compare/v5.91.0...v5.92.0 (except types for typescript and they are for `eval`).

I see this `json modules 1.11 MiB` and https://github.com/webpack/webpack/issues/18458 is about JSON files, it was slow before, but now we handle more destructuring patterns.

> after hashing

https://github.com/webpack/webpack/compare/v5.91.0...v5.92.0#diff-80ac9a306b3cf98810b51158b9f9eef4ba452d8a2e5f3ea6f266e7f0df646812

please try to provide the steps to reproduce or profile file, at least please provide configuration file, otherwise we can't help you and we will need to move it to dicussions, thank you

**Comment by mandykoh** [comment]
Minimal repro:

[webpack-slowness.tar.gz](https://github.com/user-attachments/files/16776152/webpack-slowness.tar.gz)

```
webpack 5.94.0 compiled successfully in 637 ms
…
webpack 5.91.0 compiled successfully in 390 ms
```

**Comment by alexander-akait** [comment]
I think we need to move this logic - https://github.com/webpack/webpack/pull/18348/files#diff-820a04017e95cec05fd58ca44cd7f6c9cfa5b698a144471d5a0f523932486c56R1403 to `ConcatenatedModule`, so we will run it only when necessary...

**Comment by fi3ework** [comment]
@alexander-akait The expensive part is re-parsing the AST of modules, and it's hard to eliminate as we can't get the info from the previous steps, it also caused a regression in Rspack, but because JS is not multi-threaded this problem is more serious.

What about adding an option to control this behavior, like `optimization.entryIife` with options:

- `true`: default, keep the way before #18348.
- `"development"`: keep IIFE only in development mode.
- `"production"`: keep IIFE only in production mode.
- `false`: keep the way after #18348.

This feature makes build time and production run speed trade-offs, for most cases, maybe we could choose build time as the default.

I could adding the new option if it's good to go or any other suggestion is welcomed!

**Comment by alexander-akait** [comment]
@fi3ework What's about to do it when only `concatenateModules: true`? So `development` will not be affacted. We can make `entryIife` for developers which want to disable it and prefer speed time, because if I undestand correctly this code makes nonthing when you have `concatenateModules: false`?

**Comment by fi3ework** [comment]
> because if I undestand correctly this code makes nonthing when you have concatenateModules: false?

No matter with or without `concatenateModules` enabled, this optimization will take effect. When `concatenateModules` is enabled, the entry module is usually a large concatenated module in most cases, so the performance impact will be significant, while without enabling it, the module is usually of normal size.

**Comment by alexander-akait** [comment]
@fi3ework Got it, let's make a new option for this, not sure about default value here, but for development mode I prefer `false`

**Comment by fi3ework** [comment]
> Got it, let's make a new option for this, not sure about default value here, but for development mode I prefer false

Making it disabled in development and enable in production will sufficient. I'll launch a PR in a few days.

**Comment by alexander-akait** [comment]
@fi3ework Thank you

**Comment by alexander-akait** [comment]
@fi3ework Sorry for extra ping, do you need a help with it?

**Comment by fi3ework** [comment]
@alexander-akait  I was trying to extract the optimization logic in `JavascriptModulesPlugin` into a plugin, but it seems to lack some hooks. I'll finish the option as discussed above first, sorry for the delay.
