### ISSUE TITLE
Webpack performance issue when using webpack-merge

### ISSUE THREAD

**Issue by nparoski** [webpack/webpack#18701]
# Bug report

**What is the current behavior?**

When using official docs [production setup ](https://webpack.js.org/guides/production/#root) I've noticed significant performance loss in development and production build times.

Before moving to `webpack-merge` approach I was using the following way to split dev and prod config:

```
const config = { ... }
module.exports = (webpack, args) => {
  const isProduction = args.mode === "production";

  config.plugins.push(
    new DefinePlugin("process.env.NODE_ENV", JSON.stringify(args.mode)),
  );

  if (isProduction) {
    config.mode = "production";
    delete config.devServer;
    delete config.devtool;
  } else {
    config.mode = "development";
  }

  return config;
};
```
And In `package.json`
```
  "scripts": {
    "start": "webpack serve",
    "build": "webpack --mode=production"
  },
```

Also something interesting that I observed is bundle sizes are very different with `webpack-merge` approach they are much smaller than my original which was reason I started witching to `webpack-merge` approach.

**If the current behavior is a bug, please provide the steps to reproduce.**

For reproduction please visit the following repo:
1. "Slow" `webpack-merge` approach https://github.com/nparoski/webpack-performance/tree/webpack-merge
2. Faster, beefy bundles approach https://github.com/nparoski/webpack-performance/tree/master

**What is the expected behavior?**

**Other relevant information:**
webpack version:  ^5.93.0
Node.js version: 16.15.1
Operating System: macOS Sonoma 14.5
Additional tools:
Github sandbox repo: https://github.com/nparoski/webpack-performance/tree/master

**Comment by alexander-akait** [comment]
Because of `devtool: "source-map"` - https://github.com/nparoski/webpack-performance/blob/webpack-merge/webpack.prod.js#L6 and https://github.com/nparoski/webpack-performance/blob/master/webpack.config.js#L85, they are different, in first case - no source maps, in second - yes
