### ISSUE TITLE
Duplicate loader test sections with alternate include/exclude paths

### ISSUE THREAD

**Issue by brandon-arnold** [webpack/webpack#1871]
Does anyone know why this isn't working?

I'd like Webpack to load one directory of```.scss``` files with ```sass-loader```, and the rest to use ```postcss-loader```. I figured I could just have two sections in my Webpack config that would test for ```/\.scss$/```, using ```exclude: [...bootstrap folder...]``` in the one that uses postcss and ```include: [...bootstrap folder...]``` in the one that uses Bootstrap. But webpack seems to completely ignore my second definition.

The motivation for this is I've found that the PostCSS Sass loader isn't able to load Bootstrap v4, due to circular dependencies in its mixins (see my [issue](https://github.com/jonathantneal/precss/issues/49#issuecomment-170016133) on their project and numerous conversations with that group on Gitter.im). So I'm trying to isolate the Bootstrap ```.scss``` files to load with the Sass loader, which can do this. Webpack doc seems to suggest it's supported.

Here are my Scss loader sections:

```javascript
{
  test: /\.scss$/,
	exclude: [
    path.resolve(__dirname, '../node_modules/bootstrap/scss'),
    path.resolve(__dirname, '../node_modules/bootstrap/scss/mixins'),
	],
  loaders: [
    'isomorphic-style-loader',
    'css-loader?' + (DEBUG ? 'sourceMap&' : 'minimize&') +
    'modules&localIdentName=[name]_[local]_[hash:base64:3]',
    'postcss-loader?parser=postcss-scss&pack=compile',
    'postcss-loader?pack=import',
  ],
}, {
  test: /\.scss$/,
  include: [
    path.resolve(__dirname, '../node_modules/bootstrap/scss'),
    path.resolve(__dirname, '../node_modules/bootstrap/scss/mixins'),
  ],
  loaders: [
    'isomorphic-style-loader',
    'css-loader?' + (DEBUG ? 'sourceMap&' : 'minimize&') +
    'modules&localIdentName=[name]_[local]_[hash:base64:3]',
    'sass-loader',
  ],
}
```

And the errors are, for example: 

```bash
    ERROR in ./~/css-loader?sourceMap&modules&localIdentName=[name]_[local]_[hash:base64:3]!./~/postcss-loader?parser=postcss-scss&pack=compile!./~/postcss-loader?pack=import!./src/components/App/App.scss
    Module build failed: Error: C:\path\to\project\node_modules\bootstrap\scss\_mixins.scss:18:1: Failed to find 'mixins/breakpoints' from C:\path\to\project
        in [
            C:\path\to\project\node_modules\bootstrap\scss,
            C:\path\to\project\src\components,
            C:\path\to\project\src\components\App
        ]
```

**Comment by brandon-arnold** [comment]
I def think that @bebraw should have the final say in tagging these, but this seems like a bug with Webpack as I know numerous people find the description in the doc to be counter to how ```include```/```exclude``` actually works.

**Comment by bebraw** [comment]
@brandon-arnold Ok, changed to a bug. At the very least this is something that should be documented. Changing the behavior could break things for people.

**Comment by sokra** [comment]
You are `@import`ing "bootstrap" from `./src/components/App/App.scss`. `@import` is handled by postcss and is not handled by webpack.

**Comment by brandon-arnold** [comment]
@sokra: Well, it isn't supposed to be. My postcss configuration object has PostCSS-Import forwarding everything to Webpack. But I will ask the PostCSS guys, then.

**Comment by pksjce** [comment]
This issue was moved to webpack/webpack.io#111
