### ISSUE TITLE
EnvironmentPlugin types don't allow passing null

### ISSUE THREAD

**Issue by jtbandes** [webpack/webpack#18719]
It seems like [this PR](https://github.com/webpack/webpack/pull/18647) broke the types for EnvironmentPlugin. [According to docs](https://webpack.js.org/plugins/environment-plugin/), both undefined and null are accepted as values (and have different behavior), however with this change it is no longer allowed to pass null: ([playground link](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbwKIDsBuwoRSApimABQBsBXAc2BQF84AzLEOAIgHdcAjMAQwGMBrZgG4AUCJS5WcVBiw58RMpRQAKBCLia4AMQDyugFxxSKACa46VXKYA0GrQCEAggCUjKUsWJ3qASiFAA))

<img width="956" alt="image" src="https://github.com/user-attachments/assets/a521b889-b25a-46d5-9c0f-617891921990">

_Originally posted by @jtbandes in https://github.com/webpack/webpack/pull/18647#discussion_r1735125053_

**Comment by slorber** [comment]
Similar case here, we used to be able to pass booleans and arrays

The type now forbids it, see https://github.com/facebook/docusaurus/pull/10455#issuecomment-2317593528

But it still works in practice:

![image](https://github.com/user-attachments/assets/c9b0ed77-4f68-44ab-b421-c4fe36d443fe)
