### ISSUE TITLE
mangle destructuring default in dynamic import

### ISSUE THREAD

**Issue by artola** [webpack/webpack#18720]
# Bug report

**What is the current behavior?**

Dynamic import is mangled. (Only happens on mode `production`!)

**If the current behavior is a bug, please provide the steps to reproduce.**

The following code worked in up to `5.76.1`(**at least**) but when I did upgrade to `5.94.0` produces a wrong output.

```javascript
const {default: data} = await import(/* webpackChunkName: "xxx" */ 'foo/bar.json');
```

In working versions, `data` becomes something like `{"x": 123}`. In the broken, the module is `{}` with no default.

If I avoid the destructuring with rename, then there is no problem.

```javascript
const json = await import(/* webpackChunkName: "xxx" */ 'foo/bar.json');
const data = json.default;
```

**What is the expected behavior?**

Dynamic import must not be mangled. This recent fix and may be others before could be involved as it is also about similar topic:

https://github.com/webpack/webpack/pull/18531

**Other relevant information:**
webpack version:  5.94.0
Node.js version: 20.13.1
Operating System: OSX 
Additional tools:

**Comment by alexander-akait** [comment]
@ahabhgk hello, can you look at this? thank you

**Comment by ahabhgk** [comment]
> const {default: data} = await import(/* webpackChunkName: "xxx" */ 'foo/bar.json');

@artola I can't reproduce with this, can you provide a reproduce demo?

**Comment by artola** [comment]
> > const {default: data} = await import(/* webpackChunkName: "xxx" */ 'foo/bar.json');
> 
> @artola I can't reproduce with this, can you provide a reproduce demo?

Yes, I am just finishing a repo for this. Give me 10 miinutes. I can confirm that there is a bug, when the filename is interpolated, and it happens since version 5.80.0 (before than it works in all the tested versions).
