### ISSUE TITLE
Dynamic require fails with two variables

### ISSUE THREAD

**Issue by ivan-kleshnin** [webpack/webpack#1873]
```js
let mode = "javascript";
require("codemirror/mode/javascript/" + mode);
```

`codemirror/mode/javascript/javacript.js` becomes bundled

```js
let mode = "javascript";
require("codemirror/mode/" + mode + "/" + mode);
```

All files from `codemirror/mode/` become bundled.

Looks like a bug but one never can be sure about Webpack ;)

**Comment by bebraw** [comment]
If I've understood right, this sets up a require context. In the first case it bundles from `codemirror/mode/javascript/` whereas the latter picks all from `codemirror/mode` as that becomes the context. As a result you get all those files there.

I'm leaving this open for now to get a confirmation from the author.

**Comment by sokra** [comment]
Working as expected.
