### ISSUE TITLE
[webpack-2] Import from 'module/path'

### ISSUE THREAD

**Issue by wrwrwr** [webpack/webpack#1874]
```es6
import c from 'webpack/lib/Chunk';
```
fails to resolve with 2.0.2-beta (with the referenced module installed globally).

On one hand, such imports work with 1.x + Babel, on the other, the standard seems to leave the interpretation of the module specifier open ([ES6#15.2.1.17](http://www.ecma-international.org/ecma-262/6.0/#sec-hostresolveimportedmodule)).

Making the path absolute lets it resolve, but causes a source map error in the uglify plugin.

**Comment by sokra** [comment]
It should only resolve to locally installed modules. Globally installed modules are only for CLI tools...

**Comment by wrwrwr** [comment]
Indeed, works with locally installed modules. What about the `resolve.fallback` option, doesn't seem to make any difference, shouldn't it?

**Comment by sokra** [comment]
ah, the `resolve` configuration changed: 

``` js
resolve: {
  modules: ["node_modules", "/abs/path/to/modules"],
}
```

See [here](https://github.com/webpack/enhanced-resolve/blob/master/lib/ResolverFactory.js#L43-L86) until it's documented...

**Comment by wrwrwr** [comment]
In case anyone finds this, the same works for `resolveLoader`. Many thanks for the info, and sorry for the commotion.

**Comment by sokra** [comment]
I hope the new configuration syntax is more clear in constrast to the old resolve options. Feel free to give feedback.
