### ISSUE TITLE
Compatibility with typescript 5.6

### ISSUE THREAD

**Issue by mrginglymus** [webpack/webpack#18748]
# Bug report

**What is the current behavior?**

```
.yarn/__virtual__/webpack-virtual-5df32c374e/3/AppData/Local/Yarn/Berry/cache/webpack-npm-5.94.0-d1e43de389-10c0.zip/node_modules/webpack/types.d.ts:13611:2 - error TS2416: Property '[Symbol.iterator]' in type 'SortableSet<T>' is not assignable to the same property in base type 'Set<T>'.
  Type '() => IterableIterator<T>' is not assignable to type '() => SetIterator<T>'.
    Type 'IterableIterator<T>' is missing the following properties from type 'SetIterator<T>': map, filter, take, drop, and 9 more.

13611  [Symbol.iterator](): IterableIterator<T>;
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Run `tsc` on a webpack project with `skipLibCheck: false`

**What is the expected behavior?**

No errors

**Other relevant information:**
webpack version:  5.94.0
typescript version: 5.6.2

**Comment by slorber** [comment]
Also seeing this error when using `skipLibCheck: false`

Note: I initially had more Webpack errors, but they were solved by upgrading `@types/node` to the latest `22.5.4`. But this specific error remains after the upgrade.
