### ISSUE TITLE
Getting GC, process out of memory error while bundling

### ISSUE THREAD

**Issue by abhinavsingi** [webpack/webpack#1875]
Getting following error when bundling my project with webpack.
When I have only a few chunk (split) points (require.ensure ones) then it runs okay, but when I increase the split points following error comes

```
<--- Last few GCs --->

  124541 ms: Mark-sweep 1379.0 (1457.1) -> 1378.9 (1457.1) MB, 891.6 / 0 ms [allocation failure] [GC in old space requested].
  125398 ms: Mark-sweep 1378.9 (1457.1) -> 1378.9 (1457.1) MB, 857.0 / 0 ms [allocation failure] [GC in old space requested].
  126289 ms: Mark-sweep 1378.9 (1457.1) -> 1378.9 (1457.1) MB, 890.5 / 0 ms [last resort gc].
  127136 ms: Mark-sweep 1378.9 (1457.1) -> 1378.9 (1457.1) MB, 847.1 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x18342c237339 <JS Object>
    1: get [/path/node_modules/babel-traverse/lib/path/index.js:~75] [pc=0x126413012f98] (this=0x30cb87230cc1 <JS Function NodePath (SharedFunctionInfo 0xa7d7f38b8d9)>,_ref2=0x2b8f0305a311 <an Object with map 0x365041d49801>)
    2: node [/path/node_modules/babel-traverse/lib/index.js:~119] [pc=0x126412dd40f5] (...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
Abort trap: 6
```

**Comment by sokra** [comment]
`node --max_old_space_size=4096 ./node_modules/webpack/bin/webpack.js ...`

**Comment by abhinavsingi** [comment]
I gave it 8192 instead of 4096 - it's working there.
But now getting another error: https://github.com/webpack/webpack/issues/537#issuecomment-170640104
Which got fixed if I don't set source map to true - which is not quite what I require

**Comment by Pines-Cheng** [comment]
I have add the config of `--max_old_space_size=4000"`in the `webpack.cmd` under Windows，but it sames unused. @sokra 
```
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe --max_old_space_size=4000"  "%~dp0\..\webpack\bin\webpack.js" %*
) ELSE (
  @SETLOCAL
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node  "%~dp0\..\webpack\bin\webpack.js" %*
)
```

**Comment by damianobarbati** [comment]
@sokra I'm currently using the `node --max_old_space_size=4096 ./node_modules/webpack/bin/webpack.js` on all of my projects to not have the GC error.

I was wondering: would it be possible to add the memory increase as an arg to the Webpack executable?

I.E: `wepack --max-memory 4096`

**Comment by yakovenkoroman1993** [comment]
How I can set an alias in package.json ? I want to replace node --max_old_space_size=4096 to simple node My scripts section is ugly.

**Comment by Kris-Lee-SH** [comment]
As @damianobarbati says, configure the heap size limit with a larger number.
e.g.
```bash
node --max_old_space_size=4096 ./node_modules/webpack-dev-server/bin/webpack-dev-server.js --host 0.0.0.0 --progress --quiet --no-info
```
