### ISSUE TITLE
Unable to build WebPack  code in nodejs latest version 

### ISSUE THREAD

**Issue by Madavic51** [webpack/webpack#18760]
When i give a build i am getting build error

  ./node_modules/events/events.js 14.5 KiB [built] [code generated]

ERROR in main
Module not found: Error: Can't resolve './src/index.js'/ 
(relative path: ./src/index.js)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
 i dont have index.js file in my solution but y this error is comming not sure

**Comment by snitin315** [comment]
We appreciate your effort in raising this issue. To ensure clarity in understanding your situation, we kindly request you recreate the issue using one of our provided templates.
