### ISSUE TITLE
_angular2.default.module is not a function

### ISSUE THREAD

**Issue by aneurysmjs** [webpack/webpack#1877]
hi there, I having this annoying issue, I'm working on a huge app, and mostly of its packages are from npm and that's pretty cool :) the problem is that there are some packages only available on bower so I have to setup webpack to use bower as is in the documentation by using resolve and the webpack.ResolverPlugin.

here is my webpack.config.js file

``` javascript
var path = require('path'),
      webpack = require('webpack');

var config = {
   //context: __dirname + '/client/app/app.js',
   devtool: 'source-map',
   stats: {
      colors: true,
      reasons: true
   },
   entry: [
      'babel-polyfill',
      './client/crm/crm.js',
      './client/crm/assets/stylus/styles.styl'
   ],
   output: {
      path: __dirname + '/client/build',
      publicPath: 'http://localhost:1989/assets/',
      filename: 'bundle.js'
   },
   resolve: {
      modulesDirectories: ['node_modules', 'bower_components']
   },
   module: {
      preLoaders: [{test: /\.js$/, loader: 'jshint-loader', exclude: /node_modules/}],
      loaders: [
         {
            test: /\.js$/,
            loader: 'babel',
            exclude: [
               path.resolve(__dirname, 'node_modules')
            ],
            // Options to configure babel with
            query: {
               plugins: ['transform-runtime'],
               presets: ['es2015', 'stage-0']
            }
         },
         {test: /\.html$/, loader: 'html', exclude: /node_modules/},
         {test: /\.css$/,  loader: 'style!css', exclude: /node_modules/},
         {test: /\.styl$/, loader: 'style!css!stylus', exclude: /node_modules/},
         {test: /\.png/,   loader: 'url?limit=100000&mimetype=image/png' },
         {test: /\.jpg/,   loader: 'file-loader' },
         {test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: 'url-loader'},
         {test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: 'url-loader' }
      ]
   },
   plugins: [
      new webpack.ResolverPlugin(
         new webpack.ResolverPlugin.DirectoryDescriptionFilePlugin('bower.json', ['main'])
      )
   ]
};

if (process.env.NODE_ENV === 'production') {
   config.output.path = __dirname + '/dist';
   config.plugins.push(new webpack.optimize.UglifyJsPlugin());
   config.devtool = 'source-map';
}

module.exports = config;
```

and it loads the bower package that I need.

![load](https://cloud.githubusercontent.com/assets/4050205/12250149/d752963a-b892-11e5-96e1-aad7504c1f11.png)

but I got this error when run the app.

![angular-module](https://cloud.githubusercontent.com/assets/4050205/12250167/e7763346-b892-11e5-8b22-671b2f1f36d0.png)

Uncaught TypeError: _angular2.default.module is not a function

this is were the error points

![login](https://cloud.githubusercontent.com/assets/4050205/12250267/a96359ca-b893-11e5-99e6-a04bcb2d9d6d.png)

but if I remove the plugin

``` javascript
 new webpack.ResolverPlugin(
         new webpack.ResolverPlugin.DirectoryDescriptionFilePlugin('bower.json', ['main'])
      )
```

everything runs normally but doesn't load the bower package I need 

hope you someone can help me, my boss will kill if I can't get this working, thanks for your attention

**Comment by bebraw** [comment]
It feels like this could be something Babel 6 related. The behavior changed there a bit. See http://stackoverflow.com/questions/33505992/babel-6-changes-how-it-exports-default and https://www.npmjs.com/package/babel-plugin-add-module-exports for a better idea.

**Comment by blackendstudios** [comment]
@bebraw well,I did what those articles and not result, everything still the same, just webpack.ResolverPlugin is what is causing this

**Comment by kentcdodds** [comment]
I'm guessing that however you're processing `angular` it's not importing what you think. Put a breakpoint on that line and see what the devtools tell you about the `angular` variable.

**Comment by blackendstudios** [comment]
@kentcdodds look, it is loading angular correctly...

![bp1](https://cloud.githubusercontent.com/assets/4050205/12274716/334d9974-b93a-11e5-84b2-aba16a8ad4db.png)

//////////////

![bp2](https://cloud.githubusercontent.com/assets/4050205/12274722/3c4b2e24-b93a-11e5-936f-b7afe5d99fbe.png)


here is the scope from devtools

![bp3](https://cloud.githubusercontent.com/assets/4050205/12274767/6e09f80a-b93a-11e5-90c7-cf738834ae96.png)

I see the default property from _angular2 and I installed the babel-plugin-add-module-exports to change that behavior but didn't work

**Comment by blackendstudios** [comment]
I found the same issue when I try to use angular as a plugin

```javascript
var path = require('path'),
    webpack = require('webpack');

var config = {
   context: __dirname,
   devtool: 'source-map',
   entry: {
      main: [
         'babel-polyfill',
         './client/crm/crm.js',
         './client/crm/assets/stylus/styles.styl'
      ]
   },
   output: {
      path: __dirname + '/client/build',
      //publicPath: 'http://localhost:8080/client/crm/',
      filename: 'bundle.js'
   },
   module: {
      preLoaders: [{test: /\.js$/, loader: 'jshint-loader', exclude: /node_modules/}],
      loaders: [
         {
            test: /\.js$/,
            loader: 'babel',
            exclude: [
               path.resolve(__dirname, 'node_modules')
            ],
            // Options to configure babel with
            query: {
               cacheDirectory: true,
               plugins: ['transform-runtime'],
               presets: ['es2015', 'stage-2']
            }
         },
         {test: /\.html$/, loader: 'html', exclude: /node_modules/},
         {test: /\.css$/,  loader: 'style!css', exclude: /node_modules/},
         {test: /\.styl$/, loader: 'style!css!stylus', exclude: /node_modules/},
         {test: /\.png/,   loader: 'url?limit=100000&mimetype=image/png' },
         {test: /\.jpg/,   loader: 'file-loader' },
         {test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: 'url-loader'},
         {test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: 'url-loader' }

      ]
   },
   plugins: [
      new webpack.ProvidePlugin({
         'angular': 'angular'
      })
   ]
};

if (process.env.NODE_ENV === 'production') {
   config.output.path = __dirname + '/dist';
   config.plugins.push(new webpack.optimize.UglifyJsPlugin());
   config.devtool = 'source-map';
}

module.exports = config;
```

again _angular2.default.module is not a function

![error1](https://cloud.githubusercontent.com/assets/4050205/12298406/f526b0f8-b9df-11e5-94de-ae070ade62cc.png)

and points directly on the module 

![error2](https://cloud.githubusercontent.com/assets/4050205/12298416/05389858-b9e0-11e5-9b4b-b65ac4ee4a8d.png)

**Comment by lili21** [comment]
same issue

**Comment by lili21** [comment]
add `exports-loader` for `angular.js`, don't know why.
```
{ test: /[\/]angular\.js$/, loader: 'exports?angular' }
```

**Comment by lili21** [comment]
@blackendstudios  this may be helpfull
[https://github.com/webpack/webpack/issues/192#issuecomment-40006118](https://github.com/webpack/webpack/issues/192#issuecomment-40006118)

**Comment by blackendstudios** [comment]
@lili21 didn't work :( I'm so stuck with this jajaja don't know what to do
![angular-module-is-not-a-function](https://cloud.githubusercontent.com/assets/4050205/12431622/7e8733b6-bec4-11e5-8a86-9d3ee4202712.png)

**Comment by radu-m** [comment]
Updating the Angular version 1.5.0-rc.1 solved it for me - hope it will work for you too.

**Comment by blackendstudios** [comment]
@radu-m nope, didn't worked either :(

**Comment by IngwiePhoenix** [comment]
I didnt read all the posts. But long story short:

`_angular2.default.module` not being found simply means that Angular didn't export an object as `default`.

```javascript
export default {
  // ... This object would be the default exports.
}
export function module() {
  // ... This is NOT within the default exports.
}

// So in order to get what you want,
import {module as AngularModule} from "angular";

AngularModule./*... do your stuff now. */
```

This is part of the ES6 module spec. Its a bit mean, but eh. If you want to export _everything_ from Angular, basically what you get with require,

```javascript
import {* as angular} from "angular";
``` 

This would give you `angular.module`. But it wouldn't play nice with things such as tree shaking. :). But this is a while till this gets into Webpack for now.

**Comment by sivaramsi** [comment]
I too got stuck in the same issue. is there any quick fix for this problem.

**Comment by alukach** [comment]
I was banging my head against this for weeks.  None of my coworkers were having this problem so I assumed that it was an environment error.  In the end, I renamed my global NPM packages (`sudo mv /usr/local/node_modules /usr/local/OLD_node_modules`), globally reinstalled `bower`, rebuilt my project, and the problem went away.  YMMV, good luck.

**Comment by sivaramsi** [comment]
when i try to use bower webpack plugin i got this error.

**Comment by sivaramsi** [comment]
I just removed angular from the bower_components directory everything  works fine for me :)

**Comment by blackendstudios** [comment]
@sivaramsi I've removed it but didn't work for me

**Comment by edencore** [comment]
```
rm -rf ./node_modules && npm install
```
solved the problem for me, thanks to @alukach for idea

**Comment by abobwhite** [comment]
@lili21 's solution won't work on Windows. Try this instead:

```
 loaders: [
            { test: /[\/\\]angular\.js$/, loader: "exports?angular" }
        ]
```

**Comment by DaqingFeng** [comment]
Anybody resolved it ! i got the same issue . i can't fixed it help!

**Comment by DaqingFeng** [comment]
I resolved this issue .So i find the webpackconfig.js file  contains '  exclude:'node_modules'  ' config .But this  angular  was npm installed . it in the node_modules folder. 
  so just delete this config  it just working .

 

 ```
 loaders: [
         {
            test: /\.js$/,
            loader: 'babel',
            exclude: [
               path.resolve(__dirname, 'node_modules')   //**Delete this config**
            ],
            // Options to configure babel with
            query: {
               cacheDirectory: true, 
               plugins: ['transform-runtime'],
               presets: ['es2015', 'stage-2']
            }
         },
```

**Comment by abobwhite** [comment]
@DaqingFeng That may get this working for you but babel shouldn't be processing your 3rd party code (node_modules in this case). In the end, `import angular from 'angular'` worked fine. Or, you can explicitly do the above so as to not let babel parse node_modules

```
 loaders: [
  { test: /[\/\\]angular\.js$/, loader: "exports?angular" }
 ]
```

**Comment by DaqingFeng** [comment]
@abobwhite   Yeah, I  guess i removed the ( exclude node_modules)  it can be working fine ,but not yet.  Then i found the right solution  is   using  import {module} from 'angular'  to my project. although  my config contains loaders  'angular ' config   .  i hope the information can be help somebody. Thanks

**Comment by iredjee** [comment]
Check my answer here #1921 Maybe it will be helpful.

**Comment by erperejildo** [comment]
Same issue here
