### ISSUE TITLE
webpack try to load arbitrary files when use variable parameter in dynamic import

### ISSUE THREAD

**Issue by suguanYang** [webpack/webpack#18787]
# Bug report

**What is the current behavior?**
when use dynamic import with variable like this:
```
import(varableA)
```
webpack will try to load any files in the same directory, which cause error:
```
ERROR in ./modA/index.text 1:13
Module parse failed: Unexpected token (1:13)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
```

**If the current behavior is a bug, please provide the steps to reproduce.**

1. clone https://github.com/suguanYang/webpack-dynamic-issue
2. yarn install
3. yarn build

**What is the expected behavior?**
only try files defined in the `resolve.extensions`
```
const path = require('path');
module.exports = {
  target: ['web'],
  mode: 'production',
  devtool: false,
  resolve: {
    extensions: ['.js'],
  },
  entry: {
    index: path.join(__dirname, 'index.js'),
  },
  output: {
    path: path.join(__dirname, 'dist'),
  },
  optimization: {
    minimize: false,
  },
};

```

**Other relevant information:**
webpack version:  ^5.94.0
Node.js version: v20.10.0
Operating System: 
Additional tools:

**Comment by alexander-akait** [comment]
Expected, because we can't bundle not statically analyzable code, but we always warn/error in this case, so you don't miss anything, you can use `import(/* webpackIgnore: true */ 'ignored-module.js');`

**Comment by suguanYang** [comment]
@alexander-akait Thx for your comments, but I still wonder is therr any unknow impacts if we change the behavior to "only try to resolve files that defined in the resolve.extensions or parsable by the loaders"? or can you tell some workaround (not the way to change the source code, sorry for that...) which we can change the expected behavior you metioned in webpack? we are much expected from a programming way like the a custom plugin

**Comment by alexander-akait** [comment]
Use this:
```js
const webpack = require('webpack');
const path = require('path');
module.exports = {
  target: ['web'],
  mode: 'production',
  devtool: false,
  resolve: {
    extensions: ['.js'],
  },
  entry: {
    index: path.join(__dirname, 'index.js'),
  },
  output: {
    path: path.join(__dirname, 'dist'),
  },
  optimization: {
    minimize: false,
  },
  plugins: [
    new webpack.IgnorePlugin({
      checkResource(resource) {
        if (/\.text$/.test(resource)) {
          return false;
        }

        return true;
      },
    })
  ]
};
```
