### ISSUE TITLE
Error during webpack plugin compilation with typescript 5.6.2

### ISSUE THREAD

**Issue by AndreaDelliGatti** [webpack/webpack#18788]
# Bug report

**What is the current behavior?**
I developed a plugin that I use inside my nextjs application. The plugin compilation has always been successful without any problem. I was updating the dependencies of my project when updating typescript the compilation fails with the following error

```
../../node_modules/webpack/types.d.ts:13611:2 - error TS2416: Property '[Symbol.iterator]' in type 'SortableSet<T>' is not assignable to the same property in base type 'Set<T>'.
  Type '() => IterableIterator<T>' is not assignable to type '() => SetIterator<T>'.
    Type 'IterableIterator<T>' is missing the following properties from type 'SetIterator<T>': map, filter, take, drop, and 9 more.

13611  [Symbol.iterator](): IterableIterator<T>;
       ~~~~~~~~~~~~~~~~~


Found 1 error in ../../node_modules/webpack/types.d.ts:13611
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Since I moved from one minor release of typescript to another I expected the build process to be successful. I moved from typescript 5.5.4 to typescript 5.6.2

**Other relevant information:**
webpack version:  5.94.0
Node.js version: 20.16.0
Operating System: windows 11
Additional tools: 
- typescript 5.6.2

**Comment by alexander-akait** [comment]
Already fixed, please wait the next release soon
