### ISSUE TITLE
Run webpack.optimize.UglifyJsPlugin on JS assets (that aren't in a chunk)

### ISSUE THREAD

**Issue by joshhunt** [webpack/webpack#1879]
I'm using copy-webpack-plugin to copy a file into a public directory, and I'm hoping to have it minified in the process (during production builds).

I'm using `webpack.optimize.UglifyJsPlugin`, but that only operates on the output of chunks, and the assets of `copy-webpack-plugin` don't belong to chunks so they aren't minified.

How could I get Webpack to minify Javascript files copied using the `copy-webpack-plugin` plugin?

**Comment by sokra** [comment]
> How could I get Webpack to minify Javascript files copied using the copy-webpack-plugin plugin?

That's not supported. Use webpack to process your js assets.

**Comment by joshhunt** [comment]
Fair enough. This is for a third party JS SDK which needs to be in a public
location, doesn't require any extra JS or anything.

I think I might just make an entry point which is just that one file.
