### ISSUE TITLE
Multiple initial chunks with different targets for one and the same set of entries

### ISSUE THREAD

**Issue by alexpods** [webpack/webpack#1880]
I'm working on [universal starter for angular2](https://github.com/alexpods/angular2-universal-starter). It should prerender the application on a server and execute it in a web worker on a client. So I have three environments (targets):
- **browser main thread**
- **web worker**
- **server**

There are several chunks that can be shared between these three environments (in parentheses I pointed on the environments where the chunk should be executed):
- `vendors` (**main_thread**, **web_worker**, **server**)
- `app` (**server**, **web_worker**)
- `server` (**server**)
- `browser` (**main_thread**)
- `worker` (**web_worker**)

I don't want a web worker to load its own `vendors` chunk, which differs from the main thread `vendors` chunk only in a name of a callback (`webpackChunk(cunkIds, cb)` vs `webpackJsonp(chunkIds, cb)`). A `vendors` chunk can be huge, no need for extra traffic. Also there is no need to compile the same chunks (`app` and `vendors`) several times for different targets (and I would like to have only one config after all). So I want something like this:

``` js
const TargetPlugin = webpack.optimize.TargetPlugin;
const CommonsChunkPlugin = webpack.optimize.CommonsChunkPlugin;

module.exports = {
  entry: {
    vendors: 'vendors.js',
    app: 'app.js',
    server: 'server.js',
    browser: 'browser.js',
    worker: 'worker.js'
  },
  output: { /* ... */ },
  plugins: [
    // remove duplicate "app"" code from 'server', 'browser' and 'worker',
    new CommonsChunkPlugin({ name: 'app', chunks: ['server', 'browser', 'worker'], minChunks: Infinity }),
    // remove duplicate "vendor" code from 'server', 'browser' and 'worker',
    new CommonsChunkPlugin({ name: 'vendor', chunks: ['server', 'browser', 'worker'], minChunks: Infinity }),
    // Initial chunk for server
    new TargetPlugin({ name: 'boot_server', chunk: 'server', target: 'node'}),
    // Initial chunk for browser's main thread
    new TargetPlugin({ name: 'boot_browser', chunk: 'browser', target: 'web' }),
    // Initial chunk for web worker
    new TargetPlugin({ name: 'boot_worker', chunk: 'client', target: 'webworker' }),
  ],
};

```

Because of  the `TargetPlugin` the `app`, `vendor`, `server`, `browser` and `worker` chunks are not initial chunks anymore. They are normal chunks and can be used with any of `boot_*` chunks (which are initial now). Could you tell me can something like this be implemented?

**Comment by bebraw** [comment]
Hi,

Did you manage to proceed with this?

**Comment by dhatawesomedude** [comment]
@alexpods @bebraw where you able to implement this?
