### ISSUE TITLE
Issue with Web Worker and Module Federation in Angular NX Project

### ISSUE THREAD

**Issue by wndffs** [webpack/webpack#18802]
# Bug report

**What is the current behavior?**

I am running a project with NX, dynamic Module Federation, and a Web Worker.
I expect that there should be no issues and that the Web Worker will function as it did previously without Module Federation.
However, if there are no imports in the Web Worker, everything works as expected.

So, i think, when ModuleFederationPlugin register shared libraries, libraries can be shared only in MF-applications, but not in web worker.

Modules, that webpack in worker want to register is undefined:

```
bootstrap:19 Uncaught (in promise) TypeError: __webpack_modules__[moduleId] is not a function
    at __webpack_require__ (bootstrap:19:1)
    at 8490 (my-web-worker.js:10:62)
    at __webpack_require__ (bootstrap:19:1)
    at bootstrap:34:1
    at __webpack_require__.O (chunk loaded:23:1)
    at __webpack_require__.x (bootstrap:35:1)
```

error in this function:
```
	// Check if module is in cache
	var cachedModule = __webpack_module_cache__[moduleId];
	if (cachedModule !== undefined) {
		return cachedModule.exports;
	}
	// Create a new module (and put it into the cache)
	var module = __webpack_module_cache__[moduleId] = {
		// no module.id needed
		// no module.loaded needed
		exports: {}
	};

	// Execute the module function
	__webpack_modules__[moduleId](module, module.exports, __webpack_require__);

	// Return the exports of the module
	return module.exports;
        }
```

**If the current behavior is a bug, please provide the steps to reproduce.**

repo for reproduce: https://github.com/wndffs/nx-ng-dyn-fed-web-worker-bug

1. npx nx serve dashboard --devRemotes=login
2. look at the console in devtools

**What is the expected behavior?**

When i use default executor `angular:webpack-browser` without custom webpack config, there are no problems, imports in web worker works fine.

webpack config diffs:
not MF:
```
optimization.runtimeChunk='single'
experiments.outputModule=undefined
output.publicPath=''

plugins.pluginOptions.jitMode=true
```
MF:
```
optimization.runtimeChunk=false
experiments.outputModule=true
output.publicPath='auto'
resolve.alias={ some shared libs, ...  }

plugins.pluginOptions.jitMode=false

plugins.[15]._options={ "name": "dashboard", "filename": "remoteEntry.mjs", 
"shared": { 
    "@ng-mf/data-access-user": { 
     "requiredVersion": false 
    }, 
     "@angular/core": {
         "singleton": true,
         "strictVersion": true,
         "requiredVersion": "18.0.4"
    }, } ... }
```

**Other relevant information:**
webpack version:  5.91.0
Node.js version: 18.20.4
Operating System: Windows 10 22H2 (19045.4842)
Additional tools:

**Comment by alexander-akait** [comment]
Please open an issue in `NX` repo, we don't have `angular:webpack-browser` executor, it is a custom setup and tooling, better to ask there about it, thank you

**Comment by alexander-akait** [comment]
Also I don't think you can use `runtimeChunk='single'` in your case

**Comment by wndffs** [comment]
@alexander-akait 'single' option is from working config. nvm.

I think that it doesn't matter which executor is used here, because the problem is that Webpack doesn't see the modules from the web worker.

`__webpack_modules__` is empty, but required `[moduleId]` rxjs 
`/* harmony import */ var rxjs__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! rxjs */ 4866);`

**Comment by alexander-akait** [comment]
If you make a configuration without using `NX` I will look, sorry, `NX` is complex and has a lot of things, the problem can be anywhere, that's why I suggest asking this firstly in `NX` repo

**Comment by alexander-akait** [comment]
Maybe related - https://github.com/webpack/webpack/issues/16173

**Comment by wndffs** [comment]
@alexander-akait that's it, for sure. Sorry for duplicate
maybe you know some workarounds?
I can't use multi compiler mode, because of schema, and `MarkWorkerAsInitialPlugin` gives me an error `Failed to execute 'importScripts' on 'WorkerGlobalScope': Module scripts don't support importScripts().`

**Comment by John-Ender** [comment]
I am also working in a large Nx repository that utilizes Module Federation and have been encountering these same issues getting Web Workers to work.

**Comment by wndffs** [comment]
> Can you show me pure webpack configuration, generated by nx,

sure:
[working-webpack-config-without-mf-wrapper.json](https://github.com/user-attachments/files/17168789/working-webpack-config-without-mf-wrapper.json)
[config-with-mf-wrapper.json](https://github.com/user-attachments/files/17168787/config-with-mf-wrapper.json)

**Comment by alexander-akait** [comment]
Yeah, looks the same - https://github.com/webpack/webpack/issues/16173, we need to fix it, pr welcome

**Comment by wndffs** [comment]
FYI:
Workaround in our case is to `build` web workers with webpack, each for one [name].mjs file 
Then use this built workers in app. (e.g. like assets with relative path instead of URL object)

cons: 
- increased worker size
- needs to rebuilt and reserve, if any changes in worker

pros: 
- it works
