### ISSUE TITLE
Webpack Stats Tool doesn't upload file

### ISSUE THREAD

**Issue by raybooysen** [webpack/webpack#1881]
https://webpack.github.io/analyse/

The stats analysis tool doesn't allow you to upload your stats JSON.

**Comment by bebraw** [comment]
Which browser are you using? Can you provide more information?

The tool works well for me in Chrome 47 on OS X.

**Comment by raybooysen** [comment]
No, this is my fault.  My JSON was malformed.  Apologies for the noise.
