### ISSUE TITLE
Upgrade schema-utils to latest version > 4.0.0

### ISSUE THREAD

**Issue by cperotAxway** [webpack/webpack#18820]
## Feature request

**What is the expected behavior?**
having schema-utils dependency more recent

**What is motivation or use case for adding/changing the behavior?**
I'm using yarn and I need to align depencies with other libraries that I use that depends on ajv > 8

**How should this be implemented in your opinion?**

**Are you willing to work on this yourself?**
no

**Comment by alexander-akait** [comment]
Close in favor - https://github.com/webpack/schema-utils/issues/191
