### ISSUE TITLE
Poor error message: "ERROR in Invalid value used in weak set"

### ISSUE THREAD

**Issue by paddymul** [webpack/webpack#18851]
# Bug report

I ran into an error with webpack, `ERROR in Invalid value used in weak set`.  There is no obvious way to debug what part in the webpack process caused this bug. 

This seems like it could be close to a css bug https://stackoverflow.com/questions/68546117/typeerror-invalid-value-used-in-weak-set-while-build-using-webpack but I am running webpack 5 (not 4 as that bug implies)

**What is the current behavior?**
For my repo (linked below) running webpack gives an Error message with no information about where in the webpack source code that was caused.
```
yarn webpack --config ./webpack.config.js --mode=development --debug
yarn run v1.22.19
$ /Users/paddy/buckaroo/node_modules/.bin/webpack --config ./webpack.config.js --mode=development
asset index.js 99 bytes [compared for emit] (name: main)

ERROR in Invalid value used in weak set

webpack 5.91.0 compiled with 1 error in 26 ms
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

```bash
git clone https://github.com/paddymul/buckaroo.git
cd buckaroo 
git checkout chore/fix-codepen
yarn install
yarn webpack --config ./webpack.config.js --mode=development
#or 
yarn run bundle
```
**What is the expected behavior?**

At a minimum I would expect a stacktrace showing what part of the code had failed.  I have no idea if this is part of a plugin, some part of my code, or some config setting.

If there is a command line option I should use, it would be nice if that was mentioned in the Error handler.

**Other relevant information:**
```bash
yarn run webpack -v
yarn run v1.22.19
$ /Users/paddy/buckaroo/node_modules/.bin/webpack -v

  System:
    OS: macOS 13.6.1
    CPU: (8) arm64 Apple M1
    Memory: 63.23 MB / 16.00 GB
  Binaries:
    Node: 18.16.0 - /var/folders/th/jfr8ccjx09g2j_18ty_t3xnh0000gn/T/yarn--1728755593766-0.6065021167113038/node
    Yarn: 1.22.19 - /var/folders/th/jfr8ccjx09g2j_18ty_t3xnh0000gn/T/yarn--1728755593766-0.6065021167113038/yarn
    npm: 9.5.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 129.0.6668.100
    Safari: 16.6
  Packages:
    css-loader: ^5.0.0 => 5.2.7 
    fork-ts-checker-webpack-plugin: ^6.1.0 => 6.5.3 
    html-loader: ^2.1.2 => 2.1.2 
    html-webpack-plugin: ^5.0.0 => 5.6.0 
    markdown-loader: ^7.0.0 => 7.0.0 
    postcss-loader: ^7.0.1 => 7.3.4 
    raw-loader: ^4.0.2 => 4.0.2 
    sass-loader: ^13.0.2 => 13.3.3 
    source-map-loader: ^0.2.4 => 0.2.4 
    style-loader: ^2.0.0 => 2.0.0 
    svg-url-loader: ^7.1.1 => 7.1.1 
    ts-loader: ^8.0.14 => 8.4.0 
    tsconfig-paths-webpack-plugin: ^3.3.0 => 3.5.2 
    url-loader: ^4.1.0 => 4.1.1 
    webpack: ^5 => 5.91.0 
    webpack-cli: ^5 => 5.1.4 
    webpack-dev-server: ^5 => 5.1.0 
```

**Comment by paddymul** [comment]
Thank you for the suggested fix on the other bug ( the core issue).

I still think this is a bug with webpack.  How was I supposed to figure out from the error message what the actual problem is?  Webpack should help users understand this type of problem.  That or I should be using typescript for webpack.config, which adds a nother layer of complexity and indirection.

**Comment by alexander-akait** [comment]
It can be fixed in https://github.com/webpack-contrib/mini-css-extract-plugin, not in webpack, it is javascript, we just pass compiler (class) or request(string), but the plugin signatures are the same, so we can't determine what type of plugin it is
