### ISSUE TITLE
[Plugin] No events on begin/end of compiling entry points

### ISSUE THREAD

**Issue by jakob101** [webpack/webpack#1886]
Hi, 

I'm creating a custom plugin and I need to know the begin/end event of every entry point as I should change the plugin's configuration depending on a specific entry point.

Reading through the docs, I can't find that event.

Thanks,
Jakob

**Comment by IngwiePhoenix** [comment]
Can you go a bit into detail?

As in, as far as I understand, you want to change your plugin’s config per-entrypoint, right? If so, then the this-compilation event is what you need. That is used per entry.

**Comment by jakob101** [comment]
Thank you, yeah, that's exactly what I need. Let me try that and get back to you.

**Comment by jakob101** [comment]
I'm listening on this-compilation. It's getting called once, but I have 2 entrypoints. This is my code:
<pre><code>entry: {
   textX: legacyStylesShared.concat(styles),
   textY: styles,
 },
</code></pre>
Plugin config:
<pre><code>compiler.plugin("this-compilation", function(compilation) {
       console.log("xxx");
       compilation.plugin("normal-module-loader", function(loaderContext, module) {
           console.log("yyy");
       });
   });
</code></pre>

**Comment by sokra** [comment]
I don't know what you try to do, but I'm pretty sure it doesn't work that way.

Instead you should use multiple compilation:

``` js
[
  { entry: "a", plugins: [ new YourPlugin("a") ] },
  { entry: "b", plugins: [ new YourPlugin("b") ] }
]
```

**Comment by jakob101** [comment]
I had only 1 compilation object. This will be helpful. Thank you for your help!
