### ISSUE TITLE
TypeError: Cannot read property 'endsWith' of undefined

### ISSUE THREAD

**Issue by whosyourlaowang** [webpack/webpack#18864]
# Bug report
webpack support node version >= 10
but in "lib/NormalModuleFactory.js" code use "endsWith"

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Other relevant information:**
webpack version:  5.92.0
Node.js version: 12.21.0
Operating System: 
Additional tools:

**Comment by alexander-akait** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/endsWith

> 4.0.0 (Released 2015-09-08)
