### ISSUE TITLE
Uncaught ReferenceError: global is not defined

### ISSUE THREAD

**Issue by cornerolive** [webpack/webpack#1887]
Hi, 

I have a problem with webpack. I have updated my package.json and I have this error

    Uncaught ReferenceError: global is not defined

This is my config file:

    module.exports = {
    resolve: {
        root: __dirname + "/src",
        extensions: ['', '.js', '.jsx'],
        alias: {
            vex: 'vex-js',
            modernizr$: __dirname + "/.modernizrrc"
        }
    },
    entry: {
        app: [
            'webpack-dev-server/client?http://localhost:8080',
            'webpack/hot/dev-server',
            'app.js'
        ],
        vendor: ["jquery", "bootstrap", "react", "metismenu", "vendor/sb-admin-2", "lodash", "vex-js" , "vendor/bootstrap-notify.min", "utils/crypto"]
    },
    output: {
        path: __dirname + "/",
        filename: "bundle.js"
    },
    plugins: [
        new webpack.HotModuleReplacementPlugin(),
        new webpack.optimize.CommonsChunkPlugin('vendor', 'vendor.bundle.js'),
        new webpack.ProvidePlugin({
            $: 'jquery',
            _: 'lodash'
        }),
        new ExtractTextPlugin("component.css")
    ],
    module: {
        loaders: [
            { 
                test: /\.jsx?$/, 
                loaders: ['react-hot', 'babel'], 
                include: "app.js" ,
                exclude: /node_modules/
            },
            { 
                test: /\.css$/, 
                loader: ExtractTextPlugin.extract('style-loader', 'css-loader!autoprefixer-loader')
            },
            { 
                test: /\.scss$/, 
                loader: ExtractTextPlugin.extract(
                    'style-loader', 
                    'css-loader?sourceMap!autoprefixer-loader!sass-loader?outputStyle=expanded&sourceMap=true&sourceMapContents=true'
                )
            },
            { 
                test: /^((?!config).)*\.jsx?$/, 
                exclude: /(node_modules|app\/components)/, 
                loader: "babel",
                query: {
                    presets: ['react', 'es2015', 'stage-1'],
                    plugins: ['transform-runtime']
                }
            },
            { 
                test: /\.html$/, 
                loader: 'raw' 
            },
            {
              test: /\.(png|jpg|gif)$/,
              loader: 'url-loader?limit=5000&name=img/img-[hash:6].[ext]'
            },
            { 
                test: /\.woff$/, 
                loader: "url-loader?limit=10000&minetype=application/font-woff" 
            },
            { 
                test: /\.ttf$/,    
                loader: "file-loader" 
            },
            { 
                test: /\.eot$/,    
                loader: "file-loader" 
            },
            { 
                test: /\.svg$/,    
                loader: "file-loader" 
            },
            { 
                test: /[\/\\]node_modules[\/\\]jquery[\/\\]dist[\/\\]jquery\.js$/,
                loader: "expose?$" 
            },
            { 
                test: /[\/\\]node_modules[\/\\]jquery[\/\\]dist[\/\\]jquery\.js$/,
                loader: "expose?jQuery" 
            },
            { 
                test: /\.*sb-admin-2\.js$/,
                loader: "script" 
            },
            { 
                test: /\.*crypto\.js$/,
                loader: "script" 
            },
            {
                test: /\.modernizrrc$/,
                loader: "modernizr"
            }
        ]
    },
    devtool: 'source-map'
    };

I don't know if it's babel or something else. This is making me crasy.

Thank you!

**Comment by sokra** [comment]
> Uncaught ReferenceError: global is not defined

While compiling? While executing? Stack trace? Full output?

**Comment by cornerolive** [comment]
Hi,

While executing. The problem is here **loaders: ['react-hot', 'babel'],**. I disabled react-hot-loader and all is working know. In fact, it's depreacted.

**Comment by hoodsy** [comment]
@sokra 
I get the same error when executing:
```
Uncaught ReferenceError: global is not defined
(anonymous function)	@	SetCache.js?9507:5
(anonymous function)	@	bundle.js:2675
```

which points here:
```
var cachePush = require('./cachePush'),
    getNative = require('./getNative');

/** Native method references. */
var Set = getNative(global, 'Set');
```

I recently upgraded to Babel 6, and am not using the react-hot package as @cornerolive was.

**Comment by bebraw** [comment]
Closing given there's a solution. Hot loader 3 is around the corner btw.

**Comment by Shub1427** [comment]
Just for understanding, with the latest Webpack, with the updated version of the above mentioned Config, where we are using `less-loader/sass-loader`, or use `webpack.ProvidePlugin`, Can we create a Universal React App, using webpack compiler and webpack-dev-middleware.
