### ISSUE TITLE
Any plans to write a clearer guide of how to write a plugin

### ISSUE THREAD

**Issue by lcxfs1991** [webpack/webpack#1888]
Hi, sokra

As said in the title, do you have any plans to write more on this part so that programmers can contribute to the community easily. 

When I start writing my first plugin last week, I found great difficulty in understanding the docs in the official site. I spent a lot of time reading codes of other plugins and wrote an article to explains how to write a plugin (I guess it is the first unofficial article which quite surprises me([link](https://github.com/lcxfs1991/blog/issues/1). It is in Chinese now but I will translate it into English soon). This article only covers part of APIs and techniques. If you really hope to nurture a better webpack-based community, please help to elaborate more on how to write a plugin and loader. I am also willing to help.

Best regards,

Lee from AlloyTeam, Tencent, China.

**Comment by lcxfs1991** [comment]
Any plans?

**Comment by lcxfs1991** [comment]
Am I ignored?

**Comment by sokra** [comment]
> Am I ignored?

No

> Any plans?

No time... sorry...

**Comment by bebraw** [comment]
Hi,

We are running a new documentation effort [here](https://github.com/webpack/webpack.io). Feel free to pitch in there. 👍

**Comment by lcxfs1991** [comment]
@bebraw thx bebraw

I have written some articles about webpack in past months. I plan to contribute to webpack  new doc and also hope to localize it.

https://github.com/lcxfs1991/blog
