### ISSUE TITLE
Webpack doesn't support "fs" methods like "readdirSync" on Node.js targets.

### ISSUE THREAD

**Issue by amirfarzamnia** [webpack/webpack#18888]
# Bug report

**What is the current behavior?**

When bundling a Node.js application with Webpack, it fails to support `fs` methods like `readdirSync`, causing the application to break in production when attempting to read files from a folder dynamically.

For example, the following code works fine in development but breaks after bundling:

```javascript
import path from 'node:path';
import fs from 'node:fs';

const files = fs.readdirSync(path.join(import.meta.dirname, 'functions'));

files.forEach((file) => import(path.join(import.meta.dirname, 'functions', file)).then((module) => module.default()));
```

The error typically seen is related to Webpack failing to detect or bundle the folder or its files properly.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Create a Node.js project with Webpack bundling.
2. Use `fs.readdirSync()` to read files dynamically from a folder.
3. Bundle the project using Webpack.
4. Run the bundled code in a production environment.

Here is a minimal reproduction:

```javascript
// index.js
import path from 'node:path';
import fs from 'node:fs';

const files = fs.readdirSync(path.join(import.meta.dirname, 'functions'));

files.forEach((file) => import(path.join(import.meta.dirname, 'functions', file)).then((module) => module.default()));
```

**What is the expected behavior?**

Webpack should be able to bundle and handle file system operations such as reading directories (`fs.readdirSync()`) without breaking the functionality in production builds. Ideally, the app should dynamically import files from a folder at runtime without requiring additional workarounds or hacks.

**Other relevant information:**

Webpack version: 5.95.0  
Node.js version: 22.10.0
Operating System: Windows 11  
Additional tools: N/A

**Comment by alexander-akait** [comment]
Sorry, but this is beyond the scope of webpack and it's simply impossible to implement because it's not statically analyzed code, if you are making a library you should be able to get paths as arguments to your functions, if you are making an application you should operate with relative paths

**Comment by alexander-akait** [comment]
Regarding - import.meta.dirname and import.meta.filename - https://github.com/webpack/webpack/issues/18320
