### ISSUE TITLE
Minification of CSS files through the Style/CSS/Less loader

### ISSUE THREAD

**Issue by CMCDragonkai** [webpack/webpack#189]
Do these loaders minimise the CSS once it has been loaded before attaching it to the DOM?

This section http://webpack.github.io/docs/optimization.html#minimize mentions "and your css, if you use the css-loader", but wasn't clear if the CSS was minimised or not.

**Comment by gunar** [comment]
This is actually a good unsolved question.  The answer is somewhat hidden in the [UglifyJSPlugin docs](https://webpack.github.io/docs/list-of-plugins.html#uglifyjsplugin).

>UglifyJSPlugin
>Minimize all JavaScript output of chunks. **Loaders are switched into minimizing mode.** You can pass an object containing UglifyJs options.

**Comment by SkaterDad** [comment]
@gunar The CSS minification happens at this point in `css-loader`, and uses `cssnano` to do it.
https://github.com/webpack/css-loader/blob/master/lib/processCss.js#L179

The `--optimize-minimize` or `-p` options enable this.

**Comment by Pashaster12** [comment]
For css minification usinf css-loader you should use the "minimize" option for loader. It solved the problem in my case:

```
...
use: [{
    loader: "css-loader",
    options: {
         minimize: true
    }
 },
...
```
