### ISSUE TITLE
@types/eslint-scope needs to be made a proper dependency in webpack@5.96

### ISSUE THREAD

**Issue by ashvinsrivatsa** [webpack/webpack#18916]
# Bug report

Starting in webpack@5.96.0, the `types.d.ts` file in the package root includes the following import:

```typescript
import { Scope } from "eslint-scope";
```

`eslint-scope` itself is in webpack's `dependencies`, so there's no runtime problem. But `eslint-scope` doesn't ship its own types - those live in the `@types/eslint-scope` package. And _that_ package is one of webpack's `devDependencies`. Consequently, packages that depend on webpack and interact with it via TypeScript might witness compilation errors.

**What is the current behavior?**

Compilation error.

**If the current behavior is a bug, please provide the steps to reproduce.**

```bash
$ npm init --yes
$ npm install @types/node webpack typescript
$ cat > tsconfig.json <<EOF
{
  "compilerOptions": {
    "target": "es2016",
    "module": "commonjs",
    "strict": true,
    "types": ["node"]
  }
}
EOF
$ echo "import { webpack } from 'webpack';" > index.ts
$ npx tsc
```

Result:

```
node_modules/webpack/types.d.ts:8:23 - error TS7016: Could not find a declaration file for module 'eslint-scope'. '[...]/node_modules/eslint-scope/lib/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/eslint-scope` if it exists or add a new declaration (.d.ts) file containing `declare module 'eslint-scope';`

8 import { Scope } from "eslint-scope";
                        ~~~~~~~~~~~~~~


Found 1 error in node_modules/webpack/types.d.ts:8
```

**What is the expected behavior?**

No compilation error. `@types/eslint-scope` should be added to webpack's `dependencies`.

**Other relevant information:**
webpack version:  5.96.0
Node.js version: 22.11.0

Workarounds:
* Add `@types/eslint-scope` as a top-level dependency of your own package.
* Enable `skipLibCheck` in tsconfig.json.

**Comment by AviVahl** [comment]
Saw this update failing in several repositories due to this issue.

https://github.com/AviVahl/ts-tools/pull/678
https://github.com/wixplosives/mocha-play/pull/710
(and several other closed source repositories)

**Comment by alexander-akait** [comment]
Fixed https://github.com/webpack/webpack/releases/tag/v5.96.1
