### ISSUE TITLE
Can HMR allow entry point modules with exports to be accepted by sibling entry point modules?

### ISSUE THREAD

**Issue by rubyruy** [webpack/webpack#1891]
I have the following entries setup:
```js
"entry": {
      "article": [
        "babel-polyfill",
        "router/initializer",
        "views/article.jsx"
      ],
      "articles": [
        "babel-polyfill",
        "router/initializer",
        "views/articles.jsx"
      ],
      "home": [
        "babel-polyfill",
        "router/initializer",
        "views/home.jsx"
      ]
    },
```

So a different entry chunk is generated for each view, and the `router/initializer` module can load arbitrary views by name (using `require.ensure` + contexts). Since the  initializer is always packaged into the same chunk as a particular view, requiring that view (using `require.ensure`) simply resolves immediately - it only every downloads a new chunk when trying to load a different view. This all works fine so far.

The problem is that HMR never considers the "current" view (i.e. the one packaged into that chunk) to be a dependency of anyone (not the initializer, nor the `views/*.jsx` context module). `module.hot.accept(viewsContext.id, ...)` doesn't do anything (nor does `module.hot.accept(viewsContext.resolve('./home.jsx', ...)`. `module.hot.apply({ignoreUnaccepted: true}, ...)` never applies it. Only `module.hot.accept()` in `home.jsx` itself does. I assume this is because HMR only looks as far as "is this module an entry point?" and since it is, assumes there are no exports and it can only accept itself. That's not the case here though - there _are_ exports - and they are used by _another_ entry point module.

Is that what's actually happening, or is something else the problem?

If that is the case, can HMR be made to go through the dependency checking of entry point modules anyway, as long as they have exports?

**Comment by rubyruy** [comment]
Nvm actually...  problem was I shouldn't have set up my entries that way. I keep forgetting entry chunks can't do double duty as dynamically loadable non-entry chunks.

**Comment by sokra** [comment]
You can try it this way: 

``` js
"entry": {
      "article": "./entry?views/article.jsx",
      "articles": "./entry?views/articles.jsx",
      "home": "./entry?views/home.jsx"
},
```

``` js
// entry.js
require("babel-polyfill");
require("router/initializer");
require(__resourceQuery.substr(1));
module.hot.accept(__resourceQuery.substr(1), function() {
  // here your accept handler
});
```

Or if you don't like the magic query string at the module, you can write a entry point per view...
