### ISSUE TITLE
Loader `this.importModule()` can't import `asset/resource` asset modules since 5.96.0

### ISSUE THREAD

**Issue by ezzatron** [webpack/webpack#18928]
# Bug report

**What is the current behavior?**

Under `5.96.x` using `this.importModule()` inside a loader to import an `asset/resource` asset module returns an empty object instead of the URL to the resource.

**If the current behavior is a bug, please provide the steps to reproduce.**

Here's a minimal reproduction: https://stackblitz.com/~/github.com/ezzatron/webpack-repro-5-96-loaders-broken?file=README.md

The README contains some commands to run in the console to reproduce the issue.

**What is the expected behavior?**

Using `this.importModule()` inside a loader to import an `asset/resource` asset should return the URL to the resource.

**Other relevant information:**
webpack version: `5.96.0` and beyond
Node.js version: N/A
Operating System: N/A
Additional tools: N/A

**Comment by alexander-akait** [comment]
I would say that this is a bugfix and the behavior was incorrect before, the main problem with webpack is that it always generates a JS file, which leads to the generation of extra JS code and extra chunks, this problem has existed for a long time, as you can see it is even in the bug tracker - https://github.com/webpack/webpack/issues/11671 and more.

In short, when the entry point is not a JS file, we do not generate JS code and extra chunks now, this allows you to use webpack as a regular tool for working with assets, CSS and other non-JS resources and has less runtime JS code.

How to fix this?

Write JS code to request an asset:

**loader.js**

```js
const { resolve } = require("path");
const { callbackify } = require("util");

module.exports = function loader(source) {
  const data = JSON.parse(source);

  callbackify(async () => {
    data.asset = await this.importModule(`!!./js-loader.js!${resolve(this.context, data.asset)}` );

    return JSON.stringify(data);
  })(this.async());
};
```

**js-loader.js**

```js
module.exports = function loader() {
  return `module.exports = require(${JSON.stringify(this.utils.contextify(this.context, this.remainingRequest))});`
}; 
```

After this, webpack will understand that it needs to generate execution code for JS and return URL. 

When you simply submit an asset, webpack simply generates a binary file of the asset and that's it.

**Comment by ezzatron** [comment]
Hmm, okay. I think that's going to break some established loaders e.g. https://github.com/autopulated/webpack-pwa-manifest-loader/blob/main/index.mjs

**Comment by ezzatron** [comment]
What would be your suggestion if you want to make a loader for something like web app manifests?

That is, the thing being loaded is an asset, and it contains references to other assets that you want to process through the Webpack build.

Is going via a JS loader and then another loader the only way to achieve this?

**Comment by ezzatron** [comment]
I applied your suggestion to the two actual loaders I'm trying to implement. It works (thank you!), but I did have to convert both from ESM to CJS so that I could consistently use `require.resolve` to get a relative path to the sub-loader, which feels like a bit of a shame.

For full context, here are the loaders:

- https://github.com/iconduit/browserconfig-loader
- https://github.com/iconduit/webmanifest-loader

**Comment by alexander-akait** [comment]
@ezzatron You can use `import.meta.resolve()` or just `path.resolve(__dirname, './js-loader.js')`, what is the problem with using them?

**Comment by ezzatron** [comment]
> @ezzatron You can use `import.meta.resolve()` or just `path.resolve(__dirname, './js-loader.js')`, what is the problem with using them?

You're probably right, I just couldn't figure out how to make it work at the time. I was in a bit of a hurry.

Thanks for your help!
