### ISSUE TITLE
Broken modules on reload

### ISSUE THREAD

**Issue by skolsuper** [webpack/webpack#1892]
I have been having a problem with jade-loader.  The bundle works on first build, but on every reload if I change a jade template it breaks.  The exception is "jade.attr is not a function".  I looked into the source where this is thrown and it starts with this line:

```
var jade = __webpack_require__(270);
```
on the first build.  After changing a template and being automatically recompiled, it starts with
```
var jade = __webpack_require__(1);
```

I guess this is the problem.

**Comment by skolsuper** [comment]
Also it sometimes doesn't break, and it sometimes is broken on first load.

**Comment by bebraw** [comment]
Did you figure this out? Could you set up a standalone example showcasing the issue?

**Comment by skolsuper** [comment]
I eventually just gave up on jade in that project, not tried it again since, sorry :(

**Comment by bebraw** [comment]
Ok, feel free to re-open if you can repro.
