### ISSUE TITLE
Expose internal libs, modules and plugins of core

### ISSUE THREAD

**Issue by scriptjs** [webpack/webpack#1893]
I believe both webpack and rollup suffer from some of the same issues in that their cores are monolithic and expose a surface area too small for developer access. While there are plugins, the internal code and APIs that drive transformation are not fully exposed properly for programmatic use. This limits their value.

On the current track, I am not certain that webpack nor rollup are the answer to module bundling. Their configuration and relationships to babel remain quite incoherent. Babel plugins also attempt to address some of the same issues. While it is possible to develop with this, that or some combination; bundling and build tooling is all growing in a way that is rather undesirable for use to say the least. Rollup also seems to be emulating much of webpack's config that has already been determined to be a significant sore point with developers.

The ask here is to consider exposing the internal libs in a way similar to lodash (that would not involve bringing the whole of the project to get access to these libs, modules or plugins within the core).

There is very good work being done by both projects and I applaud this. That said, the future of bundling may be neither webpack nor rollup specifically but projects that make use of libs that were thoughtfully crafted and exposed by these projects.

https://github.com/rollup/rollup/issues/449

**Comment by sokra** [comment]
See @Rich-Harris comment here: https://github.com/rollup/rollup/issues/449#issuecomment-172385469

Same is true for webpack. I do my best to make every package, that's worth it, standalone and independed of webpack.

Here some standalone packages that were created to be used by webpack and co:

* [enhanced-resolve](https://github.com/webpack/enhanced-resolve): The Resolver of webpack.
* Nearly every loader is webpack independed. You can use [loader-runner](https://github.com/webpack/loader-runner) to run them without webpack, or in another bundler.
* [tapable](https://github.com/webpack/tapable): The plugin system.
* [beautify-lint](https://github.com/sokra/beautify-lint): CI linting to beautified code.
* [watchpack](https://github.com/webpack/watchpack): The watching system.
* [memory-js](https://github.com/webpack/memory-fs): In memory filesystem, use i. e. by the webpack-dev-middleware.
* [fastparse](https://github.com/webpack/fastparse): Cool RegExp parsing library, used i. e. by some loaders.
* Some methods in [source-map](https://github.com/mozilla/source-map).
* [source-list-map](https://github.com/webpack/source-list-map): The module of the "cheap-source-maps" in webpack.

**Comment by IngwiePhoenix** [comment]
@scriptjs have you considered to actually `require("webpack/lib/...")`? You can access the actual Webpack components fairly easily, and the structure is pretty easy to get around with.

**Comment by bebraw** [comment]
Closing as there is a fair answer already.
