### ISSUE TITLE
bower module not found

### ISSUE THREAD

**Issue by gibo** [webpack/webpack#1894]
I'm currently having an issue resolving some bower dependancies.

My bower.json, references a module that has more dependancies.

I'm currently getting this error:
`ERROR in ./bower_components/ui-toolkit/dist/ui-toolkit.js`
`Module not found: Error: Cannot resolve module 'TweenMax' in /Users/xx/Documents/project/bower_components/ui-toolkit/dist`

It appears the webpack is not looking in the root `bower_components` directory.

Here is my webpack file:

    var webpackConfig = { 
      entry: {
        vendor: require('wiredep')()['js'],
        app: './src/app/index.module.js',
      },
      output: {
        path: './.tmp/serve/app',
        filename: '[name].js'
      },
      module: {
        loaders: [
          {
            test: /\.js$/,
            exclude: [/node_modules/, /bower_components/],
            loaders: ["babel"],
          },
        ]
      },
      plugins: [
        new webpack.ResolverPlugin(
            new webpack.ResolverPlugin.DirectoryDescriptionFilePlugin('bower.json', ['main'])
        ),
        new CommonsChunkPlugin({
          name: 'vendor',
          minChunks: Infinity,
        })
      ]
    };

**Comment by sokra** [comment]
You never told webpack to look into `bower_components`... Try adding it to `resolve.modulesDirectories`
