### ISSUE TITLE
The ModuleFederationPlugin does not support _webpack_public_path__

### ISSUE THREAD

**Issue by yangdan8** [webpack/webpack#18959]
# Bug report

The ModuleFederationPlugin does not support __webpack_public_path__, and the generated remote-entry.js does not include __webpack_require__. p = __webpack_public_path__, but instead has a fixed __webpack_require__.p = publicPath

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.
