### ISSUE TITLE
`ModernModuleLibraryPlugin` attempts undefined access when handling any module that is not `ConcatenatedModule`

### ISSUE THREAD

**Issue by turbocrime** [webpack/webpack#18967]
# Bug report

`ModernModuleLibraryPlugin.renderStartup` assumes that every input module is `ConcatenatedModule`, which is not guaranteed. This will error compilation when any output file represents a single chunk and a single input module.

This is quite likely if there are any:
- shared chunks
- workers
- dynamic imports
- imports with top-level async

## What is the current behavior?

the meta `exportsFinalName` is only created when a module is `ConcatenatedModule`

the name is mentioned in only 2 files: https://github.com/search?q=repo%3Awebpack%2Fwebpack+exportsFinalName&type=code

so `renderStartup` performs assignment of a potentially undefined property to `definitions`

https://github.com/webpack/webpack/blob/da41ad1845947139375fb557107fa8bd2f6f8f27/lib/library/ModernModuleLibraryPlugin.js#L88-L99

and later performs unsafe index access of `definitions` 

https://github.com/webpack/webpack/blob/da41ad1845947139375fb557107fa8bd2f6f8f27/lib/library/ModernModuleLibraryPlugin.js#L124-L128

## What is the expected behavior?

The plugin should not fail to output single-chunk files.

**Comment by alexander-akait** [comment]
modern module is not desing with multiple runtimes

**Comment by turbocrime** [comment]
> modern module is not desing with multiple runtimes 

sorry, not sure i understand. this doesn't involve multiple runtimes. will show repro today

**Comment by alexander-akait** [comment]
`workers` will not work, `runtimeChunk` will not work,  `shared chunks` will not work, it was design for just ESM code without any chunks

**Comment by turbocrime** [comment]
okay, thank you.

**Comment by alexander-akait** [comment]
@turbocrime  In future we merge `modern-module` and `module` and it will be more smart
