### ISSUE TITLE
Is it possible to make Webpack smarter about dropping unused modules?

### ISSUE THREAD

**Issue by philipwalton** [webpack/webpack#1896]
Consider the following file:

```js
// dev.js
export default function() {
  console.log('I should only be called in dev!');
}
```

If I require `dev.js` inside a falsy conditional, it does not appear in the final build:

```js
if (process.env.NODE_ENV != 'production') {
  require('./dev')();
}
```

But if, on the other hand, I require it at the top of the file like most people do, it *does* appear in the final build:

```js
const dev = require('./dev');

if (process.env.NODE_ENV != 'production') {
  dev();
}
```

At first I wasn't sure if it was UglifyJS's job or Webpack's job to remove this unused code, but as far as I can tell, it is Webpack that is dropping the module in the first example, so maybe it's possible to have Webpack figure that out in the second example too?

Just a suggestion, and thanks for the great tool!

**Comment by johanneslumpe** [comment]
This is actually something that's going to be interesting in regard to es2015 modules, where the `import` directive can only ever be at the top level.

**Comment by philipwalton** [comment]
@johanneslumpe yeah, that's exactly where I noticed it. Now I have to mix `import` and `require` statements.

**Comment by sokra** [comment]
I think it does work this way in the current state of webpack 2...

**Comment by johanneslumpe** [comment]
@sokra oh that's awesome!

**Comment by Download** [comment]
FWIW, What I am seeing is that if I conditionally require like this (with `LOG` set to `false`):

```js
let log; if(LOG) log = require('ulog')
```

Webpack succesfully removes the `ulog` module from the build. But if I require conditionally like this:

```js
const log = LOG && require('ulog')
```

Webpack does not recognize it and keeps the module `ulog` around. 
This is a shame as I think the second form is much nicer (shorter / more readable). But alas that's how it works and I guess it's not going to change in Webpack 1. 

However it's useful for people to know and this issue ranks high on related search terms so I though it be useful to add this comment here.
