### ISSUE TITLE
New UMD wrappers in Telerik Kendo UI 2016.1.112 break webpack build

### ISSUE THREAD

**Issue by jlchereau** [webpack/webpack#1897]
This might be a webpack issue.

Telerik have changed their UMD wrappers from (see kendo.listview.js):

```
(function(f, define){
    define([ "./kendo.data", "./kendo.editable", "./kendo.selectable" ], f);
})(function(){
    (function($, undefined) {

    // Their code

    })(window.kendo.jQuery);
    return window.kendo;
}, typeof define == 'function' && define.amd ? define : function(_, f){ f(); });

```

which used to work fine, to

```
(function (f, define) {
    define('kendo.listview', [
        'kendo.data',
        'kendo.editable',
        'kendo.selectable'
    ], f);
}(function () {
    var __meta__ = { ... };
    (function ($, undefined) {

        // Their code

    }(window.kendo.jQuery));
    return window.kendo;
}, typeof define == 'function' && define.amd ? define : function (a1, a2, a3) {
    (a3 || a2)();
}));
```

which trigger webpack error:

```
ERROR in ../js/vendor/kendo/kendo.listview.js
Module not found: Error: Cannot resolve module 'kendo.data' in C:\<project>\js\vendor\kendo
 @ ../js/vendor/kendo/kendo.listview.js 26:4-30:9

ERROR in ../js/vendor/kendo/kendo.listview.js
Module not found: Error: Cannot resolve module 'kendo.editable' in C:\<project>\js\vendor\kendo
 @ ../js/vendor/kendo/kendo.listview.js 26:4-30:9

ERROR in ../js/vendor/kendo/kendo.listview.js
Module not found: Error: Cannot resolve module 'kendo.selectable' in C:\<project>\js\vendor\kendo
 @ ../js/vendor/kendo/kendo.listview.js 26:4-30:9
```

**Comment by jlchereau** [comment]
I have found a workaround using:

```
module.exports =  {
    fallback: path.join(__dirname, "./js/vendor/kendo")
}
``

**Comment by brownieboy** [comment]
Could you provide a fuller example of how you solved this?  Where exactly did you put your "module.exports" workaround?

Do you have a github repo that shows this?

**Comment by jlchereau** [comment]
In ```webpack.config.js```

**Comment by brownieboy** [comment]
I couldn't get the `fallback` workaround to work for me.  What _did_ work for me was hard-coding the path to my kendo js modules as an entry in my resolve.modulesDirectories array, like so:

    resolve: {
        modulesDirectories: ['node_modules', 'bower_components',
            path.join(__dirname, 'bower_components/kendo-ui/src/js')
        ]
    },

This assumes that you have KendoUI Pro installed as a Bower package, as per the [Telerik instructions](http://docs.telerik.com/kendo-ui/intro/installation/bower-install).  Otherwise, adjust the paths accordingly.  (Remember, Webpack should work better with the source files rather than the minified ones.)

**Comment by samsfisher** [comment]
@brownieboy @jlchereau  How did you solve this issue. I have a wepack.config for global setup. Should i create another webpack config file within kendo-ui folder. I appreciate if you can share your setup.

**Comment by jlchereau** [comment]
@samsfisher check https://github.com/kidoju/Kidoju-Mobile/blob/master/webpack.config.js#L109

**Comment by brownieboy** [comment]
@samsfisher,

See https://github.com/brownieboy/kendo-webpack-systemjs for an example of how I used this in my config.

**Comment by samsfisher** [comment]
@brownieboy  thanks. That worked like a charm!
