### ISSUE TITLE
Watch webpack.config.js when using the --watch argument

### ISSUE THREAD

**Issue by dfoverdx** [webpack/webpack#1899]
I don't know if this is possible already or even possible in general, but it would be really nice if using the `--watch` parameter caused webpack to watch the `webpack.config.js` file for changes, as well as the entry points and their requirements.

I find myself, especially at the beginning of a project, editing/debugging my config file quite often, and it's frustrating having to rerun webpack.  Usually this debugging happens in tandem with debugging/changing my code files, so using the watch functionality is very useful in one place, but having to <kbd>ctrl + c</kbd> <kbd>y</kbd> <kbd>enter</kbd> <kbd>↑</kbd> <kbd>↑</kbd> <kbd>enter</kbd> in command prompt every time I make a change to the config file is rather frustrating.

**Comment by markfinger** [comment]
I used to do something like this in an old dev-oriented wrapper around webpack. Seemed to work well in test cases. It was a different story in typical dev environments where - after a couple of changes to the config file - the process would inevitably segfault. Not sure where the leaks were, could have been in my code, or webpack, or one of the many plugins and little bits from the ecosystem.

**Comment by bebraw** [comment]
There's a related issue at https://github.com/webpack/webpack-cli/issues/15 if you want to track.
