### ISSUE TITLE
Inconsistent Iteration Behavior in Queue Class Due to Iterator State Management

### ISSUE THREAD

**Issue by Muthukumar04** [webpack/webpack#18993]
# Bug report

The Queue class being referred to can be found here: [Webpack's Queue.js](https://github.com/webpack/webpack/blob/main/lib/util/Queue.js)

Relevant PR for this bug : https://github.com/webpack/webpack/pull/18992

**What is the current behavior?**  
The Queue class currently uses a persistent _iterator property to manage iteration, which can lead to unexpected behavior when iterating through elements. This redundancy can result in elements being missed when dequeuing if they are added after the initial iteration has completed.

**If the current behavior is a bug, please provide the steps to reproduce.**  
   While using Bun.js as the runtime for a Webpack build, an error surfaced in the FlagDependencyExportsPlugin, which utilizes the Queue class. The problem arises specifically due to the way the queue's _iterator handles elements added after initialization. Here's a code example that reproduces the issue:

```
class Queue {
  constructor(items) {
    this._set = new Set(items);
    this._iterator = this._set[Symbol.iterator]();
  }

  get length() {
    return this._set.size;
  }

  enqueue(item) {
    this._set.add(item);
  }

  dequeue() {
    const result = this._iterator.next();
    if (result.done) return undefined;
    this._set.delete(result.value);
    return result.value;
  }
}

const q = new Queue();

q.enqueue("item1");

console.log("outputs - item1", q.dequeue());  // output -> item1
console.log("outputs - undefined", q.dequeue());  // output -> undefined

q.enqueue("item2");
q.enqueue("item3");

console.log("outputs - item2", q.dequeue());  // Unexpected output -> undefined
console.log("outputs - item3", q.dequeue());  // Unexpected output -> undefined
console.log("outputs - undefined", q.dequeue());  // output -> undefined
```

**What is the expected behavior?**  
The Queue class should manage iteration without relying on a persistent _iterator. Each dequeue operation should create a fresh iterator that accurately reflects the queue's current state, ensuring that all elements are correctly handled even if added later.

**Suggested Fix:**
The suggested fix involves eliminating the _iterator property and directly managing iteration during each dequeue operation. This ensures that the queue correctly reflects its contents every time dequeue is called. Here's an improved version of the code:

```
class Queue {
  constructor(items) {
    this._set = new Set(items);
  }

  get length() {
    return this._set.size;
  }

  enqueue(item) {
    this._set.add(item);
  }

  dequeue() {
    const result = this._set[Symbol.iterator]().next();
    if (result.done) return undefined;
    this._set.delete(result.value);
    return result.value;
  }
}

const q = new Queue();

q.enqueue("item1");

console.log("outputs - item1", q.dequeue());  // output -> item1
console.log("outputs - undefined", q.dequeue());  // output -> undefined

q.enqueue("item2");
q.enqueue("item3");

console.log("outputs - item2", q.dequeue());  // Correct output -> item2
console.log("outputs - item3", q.dequeue());  // Correct output -> item3
console.log("outputs - undefined", q.dequeue());  // output -> undefined
```

In the suggested version, the iterator is no longer persistent. Instead, a fresh iterator is created every time dequeue is called, ensuring that new elements are recognized, even if they are added after the previous iteration has completed. This change aligns the Queue behavior with standard JavaScript practices and resolves potential edge cases.

**Other relevant information:**  
- **webpack version**:  5.93.0
- **Node.js version**: Using Bun 1.1.34
- **Operating System**: Darwin 24.1.0 arm64 arm
- **Additional tools**: (any other tools you are using)

In suggested method, the iterator is aware of the elements inside the _set even after the this.iterator returns { done : true}.

**Comment by alexander-akait** [comment]
Fixed by https://github.com/webpack/webpack/pull/18992
