### ISSUE TITLE
Webpack fails to parse my code when it ends with a comment.

### ISSUE THREAD

**Issue by letharion** [webpack/webpack#1900]
Given:

    //ResourceStore.subscribe(() => {
      ReactDOM.render(    
        <Provider store={store}>
          <ResourceList />
        </Provider>,
        document.getElementById('resList')
      );
    //});

(which is bad code, but that's a different issue ;) ) webpack fails with:

    ./node_modules/webpack/node_modules/webpack-core/node_modules/source-map/lib/source-map/source-node.js:100
                var code = nextLine.substr(0, mapping.generatedColumn -
                                              ^
    TypeError: Cannot read property 'substr' of undefined

Complete removal of the last line, the comment, removes the problem.

**Comment by letharion** [comment]
Sorry, that's not actually webpack failing, but another library. :)

**Comment by Pixcell** [comment]
Hi,

I'm sorry, but I'm facing the same issue. What was failing on your side ?

Thank you very much

**Comment by letharion** [comment]
@Pixcell Sorry, I don't immediately recall the details, but looking at the context I pasted above, based on `node_modules/source-map/lib/source-map/source-node.js` I'd wager a guess that `source-map` was the package having issues.

**Comment by vjpr** [comment]
I was having a similar issue and the cause was a faulty source map.
