### ISSUE TITLE
Should hot-update for css modules be self-accepted ?

### ISSUE THREAD

**Issue by JSerFeng** [webpack/webpack#19011]
After refactoring css loading by #18982

Here is one repo shows that modifying a style in css without accepted by ancestors, as there is no module that accept this hot update, page reloads.

[Repro](https://github.com/JSerFeng/webpack-issue-css-reload/), you find repro steps in its Readme

But I'm not sure if this is by design.

Should css modules hot update be accepted by upstream modules or themselves?

**Comment by alexander-akait** [comment]
I see, it's strange, when I tested it, locally everything worked fine, I'm figuring it out. Honestly, my first todo is to add HMR CSS tests and check the behavior before the next release :smile:
