### ISSUE TITLE
Webpack Aliases: Update documentation with warning about '#' alias prefix

### ISSUE THREAD

**Issue by SStranks** [webpack/webpack#19014]
Request: Update the Webpack documentation to include an explicit warning about using the '#' symbol as a prefix for aliases, specifically for Sass files; 

Potential locations for including warning: 
https://webpack.js.org/configuration/resolve/#resolvealias
https://webpack.js.org/loaders/sass-loader/#root

Took a few hours to track down my issue, but I was using '#' as a prefix for aliases and this was generating 'module already loaded' errors in Webpack compilation when I updated the Webpack configuration (sass-loader) to explicitly use the 'api: modern/modern-compiler' option, in preparation for Dart-Sass 2.0. The 'legacy' API generates warnings about future deprecation, with Dart-Sass 2.0, but it does not throw errors or hint at the underlying issue.

The issue has been discussed in these threads - '#' is parsed as a URL fragment and not a resource.
https://github.com/sass/sass/issues/3958
https://github.com/webpack-contrib/sass-loader/issues/1205

**Comment by alexander-akait** [comment]
We support using `#` for JS code (and other) and we can't handle it or it generates warnings because it is a breaking change (despite this, we do not recommend using it due such incompatibles), I recommend updating the SASS documentation
