### ISSUE TITLE
Help for a dynamic require

### ISSUE THREAD

**Issue by Dindaleon** [webpack/webpack#1902]
I am trying to use `ContextReplacementPlugin` but I keep getting `Error: Cannot find module './example/containers/'.`

```
new webpack.ContextReplacementPlugin(
  /extensions[\\\/]$/,
  /^\.\/(components|otherFolders|xyz)\/[^\/]+\index.js$/
)
```

To use it like this: 

```
var exampleContainerPath = './example/containers/'
var example = require(exampleContainerPath)
```

or

```
var exampleContainerPath = '../extensions/example/containers/'
var example = require(exampleContainerPath)
```

The relative path I need to match is this:

```
'../extensions/example/containers'
```

where example and containers are variables. It may or may not have index.js at the end.

**Comment by bebraw** [comment]
Can you try this against webpack 2?
