### ISSUE TITLE
If `--stats` is used, ignore loader/plugin logging?

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack#1904]
If you use `webpack --profile --json > stats.json` and some loader/plugin logs to the console, the log output will be included in `stats`. It might be a good idea to mute `console.log/warn/error` if `--json` is set or deal with this in other manner.

**Comment by sokra** [comment]
loaders and plugins should not log to the console. Loaders can log errors and warnings with `this.emitWarning` and `this.emitError`. Plugins can add them to `compilation.warnings` and `compilation.errors`.

**Comment by bebraw** [comment]
@sokra Ok, thanks! I wonder how many loaders/plugins log to console, though...

Do you think we should just close this or is there something that should be done about this?

**Comment by scottaddie** [comment]
@bebraw If you're looking for an example of a plugin, [clean-webpack-plugin](https://github.com/johnagan/clean-webpack-plugin) does log to the console. Personally, I find the output very useful.

**Comment by bebraw** [comment]
@scottaddie Yeah. The point is that plugins should use `this.emitWarning` or `this.emitError` instead of `console.log`. Then Webpack can control the output better and you get useful stats.

Now that I think of it, `verbose` flag seems a little redundant if we assume this is the way plugins work. Pushing control to Webpack over specific plugins seems a stronger solution. The problem is that there's no way to force plugin authors to use the correct logging methods. This is why I suggested monkeypatching `console`.

**Comment by scottaddie** [comment]
@bebraw Thank you for the clarification! It seems like monkeypatching `console` would certainly catch the plugin authors' attention. Since that change could break many plugins, it may be best to include that in Webpack 2.

**Comment by bebraw** [comment]
@scottaddie Most likely the only case where we would have to do that is when `--json` is used. I guess one way to get the plugins fixed would be to emit warnings when `console` is used. That way plugin authors know to fix their calls. But yeah, that's Webpack 2 stuff if @sokra wants it there.

**Comment by sokra** [comment]
I don't want webpack to monkeypatch the console...

If you have problems with plugins logging something, you can monkeypatch the console.log call in your webpack.config.js and report issues to the plugins.

``` js
var l = console.log;
console.log = function() {
  l.call(this, "CONSOLE.LOG in " + new Error().stack);
  l.apply(this, arguments);
};
```

**Comment by bebraw** [comment]
Ok, sounds good. The original issue was fixed. It was using `console.log` over `console.warn` in a certain place.
