### ISSUE TITLE
Error in "vite": "^6.0.3" during runtime

### ISSUE THREAD

**Issue by aqibnawazdev** [webpack/webpack#19088]
# Bug report
I just installed  "vite": "^6.0.3", and It gives following error when running the app

```
X [ERROR] Expected identifier but found "import"

    (define name):1:0:
      1 │ import.meta.dirname
        ╵ ~~~~~~ 
```

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**
 - Create react vite latest project 
 - RUN 
 - - ``` npm run dev ```
 

**What is the expected behavior?**

**Other relevant information:**
webpack version:  
Node.js version:
v20.13.1
Operating System:
-- Window
Additional tools:

**Comment by alexander-akait** [comment]
Not related to webpack, write to vite repo
