### ISSUE TITLE
Different requirements for entry and output.path configuration options.

### ISSUE THREAD

**Issue by DarkPark** [webpack/webpack#1908]
``` js
webpack({
    entry: 'src/js/main.js',
    output: {
        filename: 'main.js',
        path: 'app/js'
    }
}, callback);
```

Both `entry` and `output.path` have the same format - they are valid relative paths (relative to the `process.cwd()`).
This gives an error:

```
ERROR in Entry module not found: Error: Cannot resolve module 'src/js/main.js' in /home/dp/Projects/tests/spa-test
```

The file `/home/dp/Projects/tests/spa-test/src/js/main.js` of course is exist. 
To solve the problem it's enough to just add `./` in the `entry` option:

``` js
webpack({
    entry: './src/js/main.js',
    output: {
        filename: 'main.js',
        path: 'app/js'
    }
}, callback);
```

Seems path resolution is inconsistent for these two options.
Would be nice not to be forced to put `./` in the `entry` as it's not a strict requirement for relative paths.

**Comment by sokra** [comment]
> Both entry and output.path have the same format

No. `output.path` should be an absolute path.

`entry` is a module request (the thing you write into your `require` calls). `src/js/main.js` means the path `js/main.js` inside the **module** `src` which is looked up i. e. in `node_modules`.

**Comment by DarkPark** [comment]
`output.path` should be an absolute path according to the documentation.
Ok. But it accepts relative paths as well.
Wikipedia states that `./` is not mandatory for relative paths.

**Comment by sokra** [comment]
`entry` is not a relative path, it's a module request.

https://nodejs.org/dist/latest-v5.x/docs/api/modules.html#modules_all_together

**Comment by DarkPark** [comment]
@sokra, you are talking about inner implementation details.
From my point of perspective as a `webpack` user I shouldn't have such knowledge.
I see just two regular relative paths. One of them just works, the other requires some special treatment.

**Comment by Chyzwar** [comment]
In my case 

```
  output: {
    path: './build',
    filename: 'server.js',
    libraryTarget: 'commonjs2',
  },
```
Relative path work for server configuration.

``
  output: {
    path: './build/public/',
    filename: '[name].[hash].js',
  },
```
For client it s broken and produce this stack trace:
```
/home/raziel/MyProjects/legion-media/isomorphic/node_modules/webpack-middleware/middleware.js:129
			if(err) throw err;
			        ^
Error: invalid argument
    at pathToArray (/home/raziel/MyProjects/legion-media/isomorphic/node_modules/memory-fs/lib/MemoryFileSystem.js:44:10)
    at MemoryFileSystem.mkdirpSync (/home/raziel/MyProjects/legion-media/isomorphic/node_modules/memory-fs/lib/MemoryFileSystem.js:139:13)
    at MemoryFileSystem.(anonymous function) [as mkdirp] (/home/raziel/MyProjects/legion-media/isomorphic/node_modules/memory-fs/lib/MemoryFileSystem.js:279:34)
    at Compiler.<anonymous> (/home/raziel/MyProjects/legion-media/isomorphic/node_modules/webpack/lib/Compiler.js:229:25)
    at Compiler.applyPluginsAsync (/home/raziel/MyProjects/legion-media/isomorphic/node_modules/tapable/lib/Tapable.js:60:69)
    at Compiler.emitAssets (/home/raziel/MyProjects/legion-media/isomorphic/node_modules/webpack/lib/Compiler.js:226:7)
    at Watching.<anonymous> (/home/raziel/MyProjects/legion-media/isomorphic/node_modules/webpack/lib/Compiler.js:54:18)
    at /home/raziel/MyProjects/legion-media/isomorphic/node_modules/webpack/lib/Compiler.js:403:12
    at Compiler.next (/home/raziel/MyProjects/legion-media/isomorphic/node_modules/tapable/lib/Tapable.js:67:11)
    at Compiler.<anonymous> (/home/raziel/MyProjects/legion-media/isomorphic/node_modules/webpack/lib/CachePlugin.js:40:4)
```

Webpack should be able to deal with relative paths to some extend. Importing path module each time and remembering when to use relative and when absolute path is a problem. It is also unclear why relative path work well for some cases.

**Comment by chrisdothtml** [comment]
@sokra I've seen this topic come up in a few different issues now, and haven't been able to find an actual reason why the `output.path` needs to be absolute. Is there any reason why webpack can't resolve relative to the cwd by default, considering that is arguably the most common use case (also considering [it defaults to the cwd](https://github.com/webpack/webpack/blob/1ffcd28c0ee225dd224958b3f48be011da6936ba/lib/WebpackOptionsDefaulter.js#L59))?

It seems like a minor request, but as others have mentioned, it can lead to confusion when getting started with webpack since it's inconsistent with other commonly-used config properties such as `entry`.

I've opened a PR to change this. Hope you can take a look

**Comment by nyngwang** [comment]
@chrisdothtml Is it a joke? I got this:

```
[webpack-cli] Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.output.path: The provided value "./docs" is not an absolute path!
   -> The output directory as **absolute path** (required).
```

**Comment by nyngwang** [comment]
> entry is not a relative path, it's a module request.

@sokra Where can I get this info from the documentation?
