### ISSUE TITLE
How to stop/disable watch

### ISSUE THREAD

**Issue by vedarthk** [webpack/webpack#1911]
I have following webpack configuration:

```js
const config = {
    ...
    watch: false,
    plugins: [
        new webpack.optimize.CommonsChunkPlugin('vendors', 'vendors.js'),
        new Clean('public/webpack_build')
    ],
    ...
}
```

And I am running webpack as follows:

```bash
webpack --progress -d --colors --config webpack.config.babel.js
```

this command goes into watch mode even if I am specifying `watch: false` inside the config.

**Comment by vedarthk** [comment]
There was a plugin which was going into watch mode.

**Comment by ismailarilik** [comment]
@vedarthk what was that plugin?

**Comment by vedarthk** [comment]
@ismailarilik Sorry, I don't remember the plugin now and I am not facing the problem anymore so it seems the problem got fixed in the plugin.
