### ISSUE TITLE
should not call method slice on [object object]

### ISSUE THREAD

**Issue by BorelTung** [webpack/webpack#1912]
It seems that you want to skip some object in  `for...in` by setting enumerable false to it.
But IE8 does not have `Object.defineProperty`.

So the following built codes in my enrty file (vendor.js) throw en error in IE8,
`Object doesn't support property or method 'slice'`.

```
for (moduleId in moreModules) {
  var _m = moreModules[moduleId];

  // Check if module is deduplicated
  switch (typeof _m) {
    case "object":
      // Module can be created from a template
      modules[moduleId] = (function(_m) {
        // in IE8 _m maybe [object object] some time, but not [object Array]
        var args = _m.slice(1),
          templateId = _m[0];
        return function(a, b, c) {
          modules[templateId].apply(this, [a, b, c].concat(args));
        };
      }(_m));
      break;
    case "function":
      // Normal module
      modules[moduleId] = _m;
      break;
    default:
      // Module is a copy of another module
      modules[moduleId] = modules[_m];
      break;
  }
}
```

**Comment by BorelTung** [comment]
we may fix it like this

```
for (moduleId = 0;  moduleId < moreModules.length; moduleId++) {
  var _m = moreModules[moduleId];

  // Check if module is deduplicated
  switch (typeof _m) {
    case "object":
      // Module can be created from a template
      modules[moduleId] = (function(_m) {
        // in IE8 _m maybe [object object] some time, but not [object Array]
        var args = _m.slice(1),
          templateId = _m[0];
        return function(a, b, c) {
          modules[templateId].apply(this, [a, b, c].concat(args));
        };
      }(_m));
      break;
    case "function":
      // Normal module
      modules[moduleId] = _m;
      break;
    case "number":
      // Module is a copy of another module
      modules[moduleId] = modules[_m];
      break;
  }
}
```

**Comment by bebraw** [comment]
Can you set up a PR for the fix?

**Comment by BorelTung** [comment]
Yes. But I don't know where to fix the codes, cause I'm not familiar with webpack project. I just fix the built codes above.

**Comment by sokra** [comment]
I think we already fixed it a while ago. Do you use the latest version?

**Comment by BorelTung** [comment]
Yeah, I'v try the version 1.12.12. It still does not work.

**Comment by tjyuanpeng** [comment]
I have the same problem in webpack@1.13.1

**Comment by rupurt** [comment]
@tjyuanpeng I'm also having this problem in IE9.

@sokra can you merge #2546 into 1.13.x and create a new release? If you need some help I can prepare and test a new PR based on #2546.

**Comment by gaterking** [comment]
same problem in webpack@1.13.2

**Comment by rupurt** [comment]
@gaterking fwiw we've upgraded to the 2.1.0 beta and haven't had any problems. We also get a few nice new features like [`System.import`](http://moduscreate.com/code-splitting-for-react-router-with-es6-imports/) 😄

**Comment by gaterking** [comment]
@rupurt I need to support IE8, but 2.* latest not support IE8.
@sokra right？

**Comment by rupurt** [comment]
Sorry @gaterking :{ we're lucky enough not to be supporting IE8

**Comment by sokra** [comment]
After some discussion we decided for the following statement regarding IE8:

We don't support IE8 in webpack 2. IE8 is not supported by Microsoft and doesn't get security fixes. We think it's no responsible to allow web developers to build webapps which support IE8. They must break!
