### ISSUE TITLE
Webpack requires wrong version

### ISSUE THREAD

**Issue by fab1an** [webpack/webpack#1916]
I have an application which uses a plugin that I authored. In my app I require `lodash@4`, but my plugin requires `lodash@3`, both of are correctly specified in the two `package.json`s.

When I import something from my plugin like this:
```javascript
import * as deepAccess from "babel-plugin-check-data-access/lib/deepAccess"
```

the `deepAccess` function gets the `lodash@4` from my main-app (`node_modules/lodash/`) instead of the one sitting in it's own folder: `node_modules/babel-plugin-check-data-access/node_modules/lodash/`.

The plugin with the `require("lodash")` call is here: https://github.com/fab1an/babel-plugin-check-data-access/blob/master/lib/deepAccess.js
 
My webpack-config:

```javascript
const webpack = require('webpack'),
      path = require('path')

const SRC = path.resolve(__dirname, "src"),
      VENDOR = path.resolve(__dirname, "vendor"),
      NODE_MODULES = path.resolve(__dirname, "node_modules")

const babelSettings = {
  presets: ["es2015", "react"],
  plugins: [
    "check-data-access"
  ]
}

module.exports = {
  entry: [
    './src/index.js'
  ],
  module: {
    loaders: [{
      test: /\.jsx?$/,
      include: SRC,
      loader: `babel-loader?${JSON.stringify(babelSettings)}`
    }]
  },
  resolve: {
    root: [NODE_MODULES, SRC],
    extensions: ['', '.js', '.jsx'],
  },
  output: {
    path: path.resolve(__dirname, 'public', 'assets'),
    publicPath: '/assets',
    filename: 'bundle.js'
  },
};
```

**Comment by sokra** [comment]
> root: [NODE_MODULES, SRC],

You specified that only your apps node_modules should be used. That causes the issue.

**Comment by fab1an** [comment]
Thank you! What would be the correct line?

**Comment by sokra** [comment]
`root: SRC`
