### ISSUE TITLE
Files on server not being updated when using Webpack HMR

### ISSUE THREAD

**Issue by Dindaleon** [webpack/webpack#1917]
Hello,

I have tried using different tools for hot reloading code on the server but it doesn't seem to work. I have tried, webpack-dev-server, webpack-hot-middleware, webpack-dev-middleware, webpack --watch, webpack/hot/signal, webpack/hot/poll, piping and delete `require.cache`. Followed many tutorials, researched many issues.

I am using reactjs for the client and react-transform with webpack. When I edit my files, the changes are taking place on the client and webpack seems to be rebundling the changes on the server because I get a message like this:

```
Version: webpack 1.12.9
Time: 631ms
                               Asset      Size  Chunks             Chunk Names
                           bundle.js   2.21 MB       0  [emitted]  main
                         1.bundle.js    145 kB       1             IntlBundle
0.08d991a0f88c05497b95.hot-update.js   4.64 kB       0  [emitted]  main
08d991a0f88c05497b95.hot-update.json  36 bytes          [emitted]
webpack: bundle is now VALID.
```

However, when I reload my webpage, react complains with the following message;

```
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) =10=22.b:$/=10.5.0">So we are <
 (server) =10=22.b:$/=10.5.0">We are </
```

I guess that means that the code on server was not updated at all. Is this an issue with react or webpack? If it is for webpack, then what can I do to solve it?

**Comment by calvinrachuy** [comment]
@Dindaleon Is file watching working for you at all, regardless of hot loading?
File watching seems broken in my project and in a test directory following the steps at https://webpack.github.io/docs/tutorials/getting-started/
Neither `webpack --watch` nor `webpack-dev-server` seem to do anything on a source file change.
I cloned webpack (v1.12.11) and 8 `NodeWatchFileSystem` tests fail locally, reporting timeout.
<pre>4473 passing (3m)
  32 pending
  8 failing

  1) NodeWatchFileSystem should register a file change (change delayed):
     Error: timeout of 10000ms exceeded. Ensure the done() callback is being called in this test.
    at [object Object].<anonymous> (/home/calvin/projects/webpack/node_modules/mocha/lib/runnable.js:189:19)
    at Timer.listOnTimeout (timers.js:89:15)
  

  2) NodeWatchFileSystem should register a file change (watch delayed):
     Error: timeout of 10000ms</pre> ...
I'm new to webpack, so I thought I'd compare notes before filing a new issue. I'm unsure if my issue is my own setup or not.

**Comment by bebraw** [comment]
Can you set up a little example repo to study? It's hard to say anything concrete without.

Basically the error says that your server returns different markup than what the client expects. Maybe you could drop server side rendering for development usage.
