### ISSUE TITLE
ShimPlugin

### ISSUE THREAD

**Issue by sokra** [webpack/webpack#192]
Shimming modules in webpack seem to be to complex.

A ShimPlugin should simplify this.

**Comment by deanshub** [comment]
@kbdaitch i'm having the same problem integrating webpack with angular, would you please post an example (or a gist) of how you got it working?

**Comment by kbdaitch** [comment]
@deanshub [this repo](https://github.com/kbdaitch/NYCRestaurantBrowser) of mine shows what I did to get it working. Hope that helps.

**Comment by deanshub** [comment]
@kbdaitch thanks, it helped me very much, your comment about usage with ngResource didn't work for me, if you ever want to change it, this is the way it worked for me
```
{ test: /[\/\\]angular\.js$/, loader: 'exports?window.angular' },
{ test: /[\/]angular-resource\.js$/, loader: 'exports?angular.module(\'ngResource\')' },
```

**Comment by SimenB** [comment]
The newest version of Angular works fine with Browserify, so it should be good with WebPack as well.

I haven't tested it though, so might not be what you guys need.

http://blog.npmjs.org/post/114584444410/using-angulars-new-improved-browserify-support

**Comment by dtothefp** [comment]
Here is a good example of shimming modules using a combination of the `imports-loader`, `exports-loader` and `expose-loader`, as well as the `CommonsChunkPlugin` to create a shared bundle and `ProvidePlugin` to expose libs for extension such as jQuery with jquery.cookie in combo with the `externals` property.  The only problem I encountered was `backbone-validation` where the only way I could get it to work was to use the `expose-loader` because I didn't want to have to specifically require in `backbone-validation` into every file where I wanted to use it with `Backbone`.

```js
var path = require('path');
var webpack = require('webpack');
var join = path.join;
var CommonsChunkPlugin = webpack.optimize.CommonsChunkPlugin;

var plugins = [
  new webpack.ProvidePlugin({
      JSON: 'JSON',
      $: 'jquery',
      jQuery: 'jquery',
      moment: 'moment-timezone',
      'window.jquery': 'jquery',
      'Backbone.Validation': 'backbone-validation',
      Mustache: 'mustache',
      '_': 'lodash',
      Backbone: 'backbone',
      Pikaday: 'pikaday',
      Waypoint: 'waypoints',
      'global.moment': 'moment-timezone',
      'global._': 'lodash',
      'global.Backbone': 'backbone',
      'global.Mustache': 'mustache',
      'global.Pikaday': 'pikaday',
      'global.Waypoint': 'waypoints'
  }),
  new webpack.ResolverPlugin([
    new webpack.ResolverPlugin.FileAppendPlugin(['/src/waypoint.js'])
  ]),
  new CommonsChunkPlugin({
    name: 'vendor',
    filename: 'vendor.js',
    minChunks: 0
  })
];

module.exports = {
  entry: {
    vendor: [
      'jquery',
      'jquery.cookie',
      'console-polyfill',
      'es5-shim',
      'json3',
      'mustache',
      'moment-timezone',
      'lodash',
      'backbone',
      'backbone-validation',
      'pikaday',
      'waypoints'
    ],
    moment: './src/moment.js',
    mustache: './src/mustache.js',
    lodash: './src/lodash.js',
    backbone: './src/backbone.js',
    pikaday: './src/pikaday.js',
    waypoints: './src/waypoints.js'
  },
  output: {
    path: join(__dirname, 'dist'),
    filename: '[name].js'
  },
  externals: {
    jquery: 'jQuery',
    JSON: 'JSON'
  },
  resolve: {
    alias: {
      underscore: 'lodash'
    }
  },
  module: {
    loaders: [
      {
        test: /node_modules\/waypoints\//,
        loader: 'imports?root=>window!exports?window.Waypoint'
      },
      {
        test: require.resolve('backbone'),
        loader: 'expose?Backbone'
      },
      {
        test: require.resolve('backbone-validation'),
        loader: 'expose?Backbone.Validation'
      },
      {
        test: /\.json$/,
        loader: 'json'
      }
    ]
  },
  plugins: plugins
};
```

All this is done without Bower which I think is amazing and an example repo is here

https://github.com/dtothefp/webpack-no-bower

I agree with @agonbina that this is much easier than Browserify, and I would argue the Browserify cannot shim external modules at all like Webpack.

**Comment by bebraw** [comment]
Is this relevant still? Now shimming is handled through a combination of certain plugins/loaders.

**Comment by gdborton** [comment]
@bebraw I think this should be closed. It's certainly possible to Shim modules w/ webpack in a variety of ways.
