### ISSUE TITLE
Uncaught TypeError: _angular2.default.module is not a function when enable resolve.alias

### ISSUE THREAD

**Issue by aneurysmjs** [webpack/webpack#1921]
well, this is pretty critic to me, I was trying to optimize the bundle by letting webpack to use the minified versions of the dependencies in development to make the rebundling go as fast as possible.

``` javascript
var path = require('path'),
    webpack = require('webpack'),
    node_modules = path.resolve(__dirname, 'node_modules'),
    pathToAngular = path.resolve(node_modules, 'angular/angular.min.js'),
    pathToAngularAnimate = path.resolve(node_modules, 'angular-animate/angular-animate.min.js'),
    pathToAngularAria = path.resolve(node_modules, 'angular-aria/angular-aria.min.js'),
    pathToAngularHighlightjs = path.resolve(node_modules, 'angular-highlightjs/build/angular-highlightjs.min.js'),
    pathToAngularJwt = path.resolve(node_modules, 'angular-jwt/dist/angular-jwt.min.js'),
    pathToAngularSanitize = path.resolve(node_modules, 'angular-sanitize/angular-sanitize.min.js'),
    pathToAngularUiRouter = path.resolve(node_modules, 'angular-ui-router/build/angular-ui-router.min.js'),
    pathToBootstrap = path.resolve(node_modules, 'bootstrap/dist/js/bootstrap.min.js');

var config = {
   context: __dirname,
   devtool: 'source-map',
   entry: {
      main: [
         'babel-polyfill',
         './client/crm/crm.js',
         './client/crm/assets/stylus/styles.styl'
      ],
      vendors: [
         'angular',
         'angular-animate',
         'angular-aria',
         'angular-highlightjs',
         'angular-jwt',
         'angular-sanitize',
         'angular-ui-bootstrap',
         'angular-ui-router',
         'bootstrap',
         'core-js'
      ]
   },
   resolve: {
      alias: {
         'angular': pathToAngular,
         'angular-animate': pathToAngularAnimate,
         'angular-aria': pathToAngularAria,
         'angular-highlightjs': pathToAngularHighlightjs,
         'angular-jwt': pathToAngularJwt,
         'angular-sanitize': pathToAngularSanitize,
         'angular-ui-router': pathToAngularUiRouter,
         'bootstrap': pathToBootstrap
      }
   },
   output: {
      path: __dirname + '/client/build',
      publicPath: '/',
      filename: 'bundle.js'
   },
   module: {
      preLoaders: [{test: /\.js$/, loader: 'jshint-loader', exclude: /node_modules/}],
      loaders: [
         {
            test: /\.js$/,
            loader: 'babel',
            exclude: [
               path.resolve(__dirname, 'node_modules')
            ],
            // Options to configure babel with
            query: {
               cacheDirectory: true,
               plugins: ['transform-runtime'],
               presets: ['es2015', 'stage-2']
            }
         },
         {test: /\.html$/, loader: 'html', exclude: /node_modules/},
         {test: /\.css$/,  loader: 'style!css', exclude: /node_modules/},
         {test: /\.styl$/, loader: 'style!css!stylus', exclude: /node_modules/},
         {test: /\.png/,   loader: 'url?limit=100000&mimetype=image/png' },
         {test: /\.jpg/,   loader: 'file-loader' },
         {test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: 'url-loader'},
         {test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: 'url-loader' }
      ],
      noParse: [
         pathToAngular,
         pathToAngularAnimate,
         pathToAngularAria,
         pathToAngularHighlightjs,
         pathToAngularJwt,
         pathToAngularSanitize,
         pathToAngularUiRouter,
         pathToBootstrap
      ]
   },
   plugins: [
      new webpack.optimize.CommonsChunkPlugin('vendors', 'vendors.js'),
      new webpack.optimize.DedupePlugin(),
      new webpack.optimize.OccurenceOrderPlugin(),
      new webpack.optimize.LimitChunkCountPlugin({maxChunks: 10}),
      new webpack.optimize.MinChunkSizePlugin({minChunkSize: 3000})
   ]
};

if (process.env.NODE_ENV === 'production') {
   config.output.path = __dirname + '/dist';
   config.plugins.push(new webpack.optimize.UglifyJsPlugin());
   config.devtool = 'source-map';
}

module.exports = config;
```

the result is pretty

![bundle](https://cloud.githubusercontent.com/assets/4050205/12531709/ab5cdc70-c1cf-11e5-9927-1dc5804d2582.png)

but when I run the app, I got Uncaught TypeError: _angular2.default.module.

![bug](https://cloud.githubusercontent.com/assets/4050205/12531721/00ab3dfc-c1d0-11e5-9ffe-9272c5096980.png)

why this happens only when I use functionality that I need from webpack?

**Comment by blackendstudios** [comment]
also appears when using angular as a plugin, when use webpack.ResolverPlugin, and if run karma, I got webpackJsonp not found, so is in webpack? babel? my configuration? theres a specific version for webpack and babel to work with no issues?

**Comment by lili21** [comment]
```
{
     test: /[\/]angular\.js$/,
     loader: 'exports?angular'
}
```
use `exports-loader` for angular. works for me.

**Comment by blackendstudios** [comment]
@lili21 did exaclty the same but didn't work :(

![err](https://cloud.githubusercontent.com/assets/4050205/12665831/b4623706-c608-11e5-9cab-b017ec8c5d65.png)

![err2](https://cloud.githubusercontent.com/assets/4050205/12665845/c9caac18-c608-11e5-9ca8-fe329d7f4152.png)

**Comment by ozayolkan** [comment]
I'm having the exact same problem.

**Comment by blackendstudios** [comment]
if there a specific version of webpack to handle this?

**Comment by ozayolkan** [comment]
I'm using:
"webpack": "1.12.12",
"babel-loader": "5.3.2",

I''m not using babel-core though.

**Comment by blackendstudios** [comment]
mmm more strange either....

**Comment by blackendstudios** [comment]
even I update to babel 6.4.5, it still the same

**Comment by blackendstudios** [comment]
@sokra @lili21 I made a small app, I remove the babel stuff, just a regular SPA with es5 using webpack, when enabling resolve.alias to bundle the minified version of angular the same error appears, so babel is not the problem

https://github.com/blackendstudios/angular_with_webpack.git

**Comment by iredjee** [comment]
Thanks to @lili21 , nice idea. Just need some additional configuration to get it works.

_webpack.config.js_
```
...
// Add alias, so webpack looks for minified version of angular
resolve: {
    alias: {
        angular: "angular/angular.min.js"
    }
}

...
// Add exports loader for angular
modules: {
    loaders: [
        {
            test: /angular\.min\.js$/,
            loader: 'exports?angular'
        }
    ]
}

```

After this configuration we can easily import minified version of angular using the following command
```
let angular = require('angular');

// or es6 version

import angular from 'angular';
```

**Comment by mattiascaricato** [comment]
@lili21 why do we need `exports-loader` only for angular? I used `resolve.alias` with many libraries without using `exports-loaders` and it's working.

**Comment by balkarov** [comment]
@iredjee hello!
Thank for your answare. 
When I try use it I get error 

> Uncaught TypeError: angular.module is not a function

**Comment by iredjee** [comment]
@mattiascaricato Well, I don't know how you use other libraries, but I can explain the issue with `angular`.

When we want to use minified version of some library (`angular` in our case), we can define alias for this in webpack configuration file, where `key` is the name of library, and `value` is the path to minified version.

The problem with `angular.min.js` that unlike original `angular.js` file, it doesn't export any object, it just exposes some global variable. And to get it work, we have to export somehow this global variable, and here `exports-loader` save us.

That's it ;)
