### ISSUE TITLE
Code splitting and exports

### ISSUE THREAD

**Issue by calebmer** [webpack/webpack#1924]
I have a number of entry points, one for each page of my app, which all output files which export a component. I also have a commons chunk which I would like to contain the code which mounts the component. Is there a way to not output the commons chunk to the browser but output the other entries say in `__component__`?

**Comment by bebraw** [comment]
> Is there a way to not output the commons chunk to the browser but output the other entries say in __component__?

Can you expand on this idea? What sort of output do you need exactly?

**Comment by calebmer** [comment]
I opened this issue a long time ago and it is not applicable anymore. The way I worded it was confusing (even to me 😖) so I can't jump back into my mindset to clarify. Closing…

**Comment by bebraw** [comment]
It's ok. Thanks. :+1:
