### ISSUE TITLE
there are no any info when i distributed my code.

### ISSUE THREAD

**Issue by uinika** [webpack/webpack#1927]
below is my project.
https://github.com/uinika/saga.git

* my code is not packaged correctly and  there is no error info outputs.
PLS, checkout my project, and test it.
(1) clone my code and enter the project folder.
(2) take "npm install"
(3) run "npm start" will be ok. but "npm run dist" didn't.

**Comment by sokra** [comment]
I don't speak chinese... provide a simple testcase if you think it's a bug.

But I doubt that it's a bug... Propably a configuration issue...

**Comment by uinika** [comment]
Ok, I have already fix this. i think UglifyJsPlugin's lint check is unnecessary when distribute production.
Any way, THXS for ur advise.
`
  plugins: [
    new webpack.optimize.DedupePlugin(),
    new webpack.optimize.OccurenceOrderPlugin(),
    new webpack.optimize.AggressiveMergingPlugin(),
    new webpack.NoErrorsPlugin(),
    new webpack.optimize.UglifyJsPlugin({
      compress: { warnings: false }
    }),
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': '"production"'
    }),
  ],
`
