### ISSUE TITLE
Doc Request: More examples for plugin authors

### ISSUE THREAD

**Issue by donaldpipowitch** [webpack/webpack#1928]
Hi, I struggle writing plugins for webpack. I tried to get help on Gitter and StackOverflow ([see](http://stackoverflow.com/questions/34898364/how-to-prepend-a-file-to-my-output-file-in-webpack-with-a-plugin)), but while many people use webpack there are just a few plugin authors and its hard to get starting. It would be nice to have some simple commented plugin templates for common use cases:
- append/prepend files
- replace/check content
- use different files
- rewrite URLs
...

**Comment by bebraw** [comment]
Can you comment at [the new doc site repo](https://github.com/webpack/webpack.io)? That's the right place to resolve this.
