### ISSUE TITLE
Should webpack build exit error code when a loader fail?

### ISSUE THREAD

**Issue by JSteunou** [webpack/webpack#1929]
I wrote a very simple async loader, following the documentation step by step, and calling the callback with error when some, **but** webpack just log the error in console and continue, exiting 0 as everything went fine.

Is this an issue or am I missing something?

**Comment by sokra** [comment]
This changes with webpack 2 to a non-zero exit code. webpack 1 stays for backward compatiblitity.

**Comment by JSteunou** [comment]
Nice, thank you @sokra looking forward for v2 then ;)

**Comment by gmfun** [comment]
With webpack 2, when I deploy to heroku the builds fails because of exit code 2. @sokra is there any way to disable this new feature or force webpack to exit with code 0
