### ISSUE TITLE
Multiple entires, one as library

### ISSUE THREAD

**Issue by grimor** [webpack/webpack#1933]
Hi,

I've got my regular application code as entry. Now I want to add another entry and treat it as library (I just want to write simple library that I can require as commonjs module)

I've got
```javascript
  entry: {
    app: path.join(__dirname, './src/index.js'),
    lib: path.join(__dirname, './src/lib/index.js')
  },
  output: {
    path: path.join(__dirname, 'dist'),
    filename: 'bundle.js',
    publicPath: '/dist/'
  },
  plugins: [
    new webpack.optimize.CommonsChunkPlugin('lib', 'lib.js', Infinity),
  ]
```

To summarize I have `app` bundle and want to add `lib` bundle that can be required as commonjs module

The thing is I want to transform library code through babel using same webpack config. Is it possible in webpack ?

**Comment by sokra** [comment]
Use multiple configurations: http://webpack.github.io/docs/configuration.html#multiple-configurations
