### ISSUE TITLE
Error: Cannot find module './node-mongodb-native'.

### ISSUE THREAD

**Issue by sboutzen** [webpack/webpack#1935]
I am trying to compile a script to test out my database setup, and I have spent many hours trying to figure out what goes wrong. I am starting to think it is a bug. Here is my config:

	module.exports = {
		entry: './testing.js',
		module: {
			loaders: [
				{
					exclude: /node_modules/,
					loader: 'babel',
					query: {
						plugins: ['./build/babelRelayPlugin'],
					},
					test: /\.jsx?$/
				},
				{
					loader: 'node-loader',
					test: /\.node$/,
				},
				{
					loader: 'json-loader',
					test: /\.json$/,
				},
				{
					loader: 'html-loader!markdown-loader',
					test: /\.md$/,
				},
			]
		},
		output: {
			filename: 'app.js',
			path: __dirname
		},
		resolve: {
			extensions: ["", ".js", ".jsx", ".node", ".webpack-loader.js", ".web-loader.js", ".loader.js"]
		},
		node: {
			fs: "empty",
			net: "empty",
			tls: "empty"
		}
		// target: "node"
	}

When I compile the script, I get these warnings:

	WARNING in ./~/mongoose/lib/drivers/index.js
	Critical dependencies:
	8:11-74 the request of a dependency is an expression
	 @ ./~/mongoose/lib/drivers/index.js 8:11-74

	WARNING in ./~/bcrypt/~/bindings/bindings.js
	Critical dependencies:
	76:22-40 the request of a dependency is an expression
	76:43-53 the request of a dependency is an expression
	 @ ./~/bcrypt/~/bindings/bindings.js 76:22-40 76:43-53

and when I run it, I get this error:

	Error: Cannot find module './node-mongodb-native'.
		at C:\bifrostApp\app.js:3799:42
		at webpackContextResolve (C:\bifrostApp\app.js:3799:90)
		at webpackContext (C:\bifrostApp\app.js:3796:30)
		at Object.map../SPEC.md (C:\bifrostApp\app.js:3754:36)
		at __webpack_require__ (C:\bifrostApp\app.js:20:30)
		at Object.<anonymous> (C:\bifrostApp\app.js:2465:17)
		at Object.<anonymous> (C:\bifrostApp\app.js:3741:31)
		at __webpack_require__ (C:\bifrostApp\app.js:20:30)
		at Object.<anonymous> (C:\bifrostApp\app.js:128:19)
		at Object.<anonymous> (C:\bifrostApp\app.js:204:31)

This is the code thats failing, it is called with the path `'./node-mongodb-native'`:

	var map = {
		"./SPEC.md": 18,
		"./browser/ReadPreference": 19,
		"./browser/ReadPreference.js": 19,
		"./browser/binary": 20,
		"./browser/binary.js": 20,
		"./browser/index": 43,
		"./browser/index.js": 43,
		"./browser/objectid": 44,
		"./browser/objectid.js": 44,
		"./index": 16,
		"./index.js": 16,
		"./node-mongodb-native/ReadPreference": 45,
		"./node-mongodb-native/ReadPreference.js": 45,
		"./node-mongodb-native/binary": 177,
		"./node-mongodb-native/binary.js": 177,
		"./node-mongodb-native/collection": 178,
		"./node-mongodb-native/collection.js": 178,
		"./node-mongodb-native/connection": 221,
		"./node-mongodb-native/connection.js": 221,
		"./node-mongodb-native/index": 229,
		"./node-mongodb-native/index.js": 229,
		"./node-mongodb-native/objectid": 230,
		"./node-mongodb-native/objectid.js": 230
	};
	function webpackContext(req) {
		return __webpack_require__(webpackContextResolve(req));
	};
	function webpackContextResolve(req) {
		return map[req] || (function() { throw new Error("Cannot find module '" + req + "'.") }());
	};

I am not sure if I am doing something incredibly stupid, or if it is some kind of bug. Any suggestions?

**Comment by sboutzen** [comment]
I was trying to run it with `node` instead of `babel-node`. Herp derp, sorry for the disturbance.

**Comment by jzhang1** [comment]
Yeah I'm hitting the same error, any one have any ideas?

**Comment by uzarubin** [comment]
I'm also experiencing this.

**Comment by KingWu** [comment]
I face the same issue

**Comment by ramsaylanier** [comment]
I also have this issue while using bcrypt. If I remove the bcrypt import the error goes away.

**Comment by androiderik** [comment]
I got this error :( someone can help me?
i dont understand whats happening this issue :(

**Comment by TotallWAR** [comment]
Hey Evrb!
I resolved this problem by installing of mongoose of last version.
Type the command  "npm install mongoose -s". Note you should be into the folder your project is placed. Parameter -s will add the depency into your package file.

**Comment by Jeerjmin** [comment]
same issue with webpack and angular-cli

**Comment by LudwigPelaez** [comment]
> Hey Evrb!
> I resolved this problem by installing of mongoose of last version.
> Type the command "npm install mongoose -s". Note you should be into the folder your project is placed. Parameter -s will add the depency into your package file.

This one help me with the error, thanks!
