### ISSUE TITLE
Mangle is run by default while documentation states otherwise

### ISSUE THREAD

**Issue by juhamust** [webpack/webpack#1936]
Maybe I'm mistaken, but as I see it, the mangling in uglify plugin is not false by default, as it states in documentation. Instead, one have to disable it explicitly as it is undefined by default?

- http://webpack.github.io/docs/list-of-plugins.html#uglifyjsplugin -- "By default the mangle option is false."
- https://github.com/webpack/webpack/blob/master/lib/optimize/UglifyJsPlugin.js#L92 -- `if(options.mangle !== false) {`

**Comment by sokra** [comment]
changed documentation
