### ISSUE TITLE
Source Path Too Long

### ISSUE THREAD

**Issue by AnnotatedJS** [webpack/webpack#1937]
Developing in a Windows 8 environment using Meteor and Webpack. After a first build I can't copy the .meteor folder. I get the following message:

```
Source Path Too Long

The source file name(s) are larger than is supported by the file system. Try moving to a [....etc.]
```

NB. I posted this issue also at the meteor/meteor repository: [issue 6088](https://github.com/meteor/meteor/issues/6088)

**Comment by bebraw** [comment]
Closing given this was solved at https://github.com/meteor/meteor/issues/6088 .
