### ISSUE TITLE
[Plugin] Injecting dependencies based on contents of module

### ISSUE THREAD

**Issue by rbhalla** [webpack/webpack#1938]
I'm currently struggling to find a way to inject dependencies based on the contents of my module.

I'm using `compiler.parser.plugin` to determine which modules I need to inject dependencies into, but it seems to be too late to inject `require` statements into the source. If I do they're not parsed and converted to the `__webpack_require__` I'm used to seeing.

What is the recommended workflow here?

**Comment by sokra** [comment]
write a loader instead.

**Comment by rbhalla** [comment]
Yep that makes a lot more sense, thanks!
