### ISSUE TITLE
Webpack 2 - OverWriting Exposed (expose-loader) Dependency

### ISSUE THREAD

**Issue by dtothefp** [webpack/webpack#1940]
I'm using `expose-loader` in my `postLoaders` to expose some utility modules globally. With Webpack 2 one of the modules is getting "overwritten" by the other:

```js
//entry

```{
  main: [ 'webpack-hot-middleware/client?path=http://localhost:8080/__webpack_hmr&reload=true&noInfo=true',
    'babel-polyfill',
    'js-cookie',
    'query-string',
    './js/shims/index.js',
    './js/index.jsx'
  ]
}

```js
//postLoaders
[
  {
    test: require.resolve('js-cookie'),
    loader: 'expose?Cookie'
  },
  {
    test: require.resolve('query-string'),
    loader: 'expose?qs'
  }
]
```

result
<img width="328" alt="screen shot 2016-01-27 at 1 26 07 am" src="https://cloud.githubusercontent.com/assets/4656726/12605690/3f482fbc-c495-11e5-85db-c6290b828f9a.png">

From what I can tell the code exposing the modules is the same in Webpack 1 and 2 so I don't know how the `Cookie` module is getting clobbered?

Webpack 1
```js
/* 214 */
/***/ function(module, exports, __webpack_require__) {

	/* WEBPACK VAR INJECTION */(function(global) {module.exports = global["Cookie"] = __webpack_require__(786);
	/* WEBPACK VAR INJECTION */}.call(exports, (function() { return this; }())))

/***/ },

/* 319 */
/***/ function(module, exports, __webpack_require__) {

	/* WEBPACK VAR INJECTION */(function(global) {module.exports = global["qs"] = __webpack_require__(850);
	/* WEBPACK VAR INJECTION */}.call(exports, (function() { return this; }())))

/***/ },
/* 0 */
/***/ function(module, exports, __webpack_require__) {

	__webpack_require__(580);
	__webpack_require__(214);
	__webpack_require__(319);
	__webpack_require__(577);
	module.exports = __webpack_require__(558);


/***/ },
```
Webpack 2
```js
/* 204 */
/***/ function(module, exports, __webpack_require__) {

	/* WEBPACK VAR INJECTION */(function(global) {module.exports = global["Cookie"] = __webpack_require__(882);
	/* WEBPACK VAR INJECTION */}.call(exports, (function() { return this; }())))

/***/ },
/* 533 */
/***/ function(module, exports, __webpack_require__) {

	/* WEBPACK VAR INJECTION */(function(global) {module.exports = global["qs"] = __webpack_require__(497);
	/* WEBPACK VAR INJECTION */}.call(exports, (function() { return this; }())))

/***/ },
/* 1033 */
/***/ function(module, exports, __webpack_require__) {

	__webpack_require__(532);
	__webpack_require__(204);
	__webpack_require__(533);
	__webpack_require__(531);
	module.exports = __webpack_require__(530);

/***/ },
```

**Comment by sokra** [comment]
weird..

**Comment by dtothefp** [comment]
yup, thanks

**Comment by sokra** [comment]
Are you using any plugin?

If you have a small repro case I'll take a look.

**Comment by dtothefp** [comment]
@sokra I made a small example https://github.com/dtothefp/webpack-expose but unfortunately/fortunately the clobbering of globals is not happening here. My app that has the problem has a much more complicated config so I can keep trying to reproduce but for now I can't figure out the issue.

**Comment by dtothefp** [comment]
@sokra I figured out when this was happening, demo below:

```js
//webpack config entry
const entry = {
  main: [
    './some/index.js`,
    'js-cookie',
    'query-string`
  ]
}
```
or maybe I have some shims file
```js
import 'js-cookie';
import 'query-string';
import 'babel-polyfill'
```

and include that in my entry 
```js
//webpack config entry
const entry = {
  main: [
    './some/index.js`,
    '/abs/path/to/shims.js'
  ]
}
```

Then I'm getting the clobbering problem. `js-cookie` and `query-string` are getting included other places in my dependency tree so taking them out of shims or the entry works fine for my use case. 

I got my clobbering example to work for the modules directly in the entry, but it didn't work for the shim file example.

https://github.com/dtothefp/webpack-expose/blob/master/webpack.babel.config.js#L167

Maybe this is just something dumb I should never do but glad to track down the issue

**Comment by alexFaunt** [comment]
I think I'm having a very similar issue to this using exports-loader. I'm trying to narrow down exactly what is wrong, but it escapes me so far - below is some example config

What seems to be the problem is when I have multiple exports-loaders configured, it uses the query from the alphabetically first item and clobbers the rest with that.

```javascript 
resolve: {
	modules: ['src', 'node_modules'],
	alias: {
		Lib: 'libs/library.js',
		Globalize: 'libs/example.js'
	}
},
loaders: [
	{
		test: /library\.js$/,
		loader: "exports?lib"
	},
	{
		test: /example\.js$/,
		loader: "exports?example"
	},
	{
		loader: 'babel',
		test: /\.js$/,
		query: {
			presets: [
				"es2015"
			]
		}
	}
```

This is resulting in `module.exports = example` injected into the bottom of both library.js and example.js, rather than `module.exports = lib` being in the library.js

I then looked at the exports loader, and found that as it loops through both files the context contains these loaders: 

```javascript
this.loaders:
 [ {
     path: 'C:\\Home\\mobile-html5\\node_modules\\exports-loader\\index.js',
     query: '?example',
},
   {
     path: 'C:\\Home\\mobile-html5\\node_modules\\babel-loader\\index.js',
     query: '?{"presets":["es2015"]}'
} ],
```
and so it returns ```var query = loaderUtils.parseQuery(this.query); // === { example: true }```

Which is what then writes it out to the files, ignoring the query from the second loader, but i am yet to work out what is causing the loaders to be misconfigured in this case, as with a simple test case it seems fine.

Hope this is helpful - I will continue looking for the precise issue

**Comment by alexFaunt** [comment]
I'm just wildly digging around here as I've no idea of how webpack works, but I've narrowed it down a bit further. 

[webpack/lib/NormalModuleFactory.js:119](https://github.com/webpack/webpack/blob/master/lib/NormalModuleFactory.js#L118)

```javascript
var matchedLoaders = _this.loaders.match(resourcePath);
async.parallel([
	_this.resolveRequestArray.bind(_this, contextInfo, context, noPostAutoLoaders ? [] : _this.postLoaders.match(resourcePath), _this.resolvers.loader),
	_this.resolveRequestArray.bind(_this, contextInfo, context, _this.loaders.match(resourcePath), _this.resolvers.loader),
	_this.resolveRequestArray.bind(_this, contextInfo, context, _this.preLoaders.match(resourcePath), _this.resolvers.loader)
], function(err, results) {
	if(err) return callback(err);
	
	// Hacking down to the ones i'm interested in - exports loader in my case
	if (results[1].length > 1) {
		
		// The results here don't match, so somehwere during resolveRequestArray the query gets changed. 
		if (matchedLoaders[0].split('?')[1] !== results[1][0].split('?')[1]) {
			
			// Hack fix to prove it, swapping the query from the closure value corrects the issue and the build works fine. 
			results[1][0] = results[1][0].replace(results[1][0].split('?')[1], matchedLoaders[0].split('?')[1]);
		}
	}
	loaders = results[0].concat(loaders).concat(results[1]).concat(results[2]);
	onDoneResolving();
});
```

So _this.resolveRequestArray result returns a different query to what we obtain from the context before running it.

No explanation as to why it's intermittent or why this method is changing it somehow - i'll keep digging!

**Comment by alexFaunt** [comment]
After more digging I think I found a fix for the issue, when caching the loaders it doesn't include the query, and could then return the wrong item from the cache as the cacheIds are identical

https://github.com/webpack/enhanced-resolve/pull/26 created a PR here for consideration @sokra @dtothefp

**Comment by dtothefp** [comment]
@alexFaunt thanks for the help, looks like it got merged :smile:

**Comment by alexFaunt** [comment]
glad to help!
