### ISSUE TITLE
How does HMR event bubble in async modules?

### ISSUE THREAD

**Issue by jiyinyiyong** [webpack/webpack#1941]
I noticed that `module.hot.accpet` does not work for the files loaded with `require.ensure` and does not work in those files. So I think the bubbling is different there, but how does it work?

And I'm using Webpack `1.x`, would there be difference between `1.x` and `2.x`.

**Comment by sokra** [comment]
It's not different. `require.ensure` just loads the modules into the modules container. Every module is loaded via `require`.

**Comment by jiyinyiyong** [comment]
Any example I can follow please?

**Comment by sokra** [comment]
``` js
require.ensure([], function() {
  var x = require("x");
  module.hot.accept("x", function() {
    x = require("x");
    // do something when x was updated
  });
});
```

**Comment by jiyinyiyong** [comment]
So the `hot.accept` method should be called in the same function body where it's `require`d, that's why I my attempts failed. Thanks, I'll close this issue tomorrow when I confirm in my project.
