### ISSUE TITLE
__WEBPACK_AMD_DEFINE_FACTORY__

### ISSUE THREAD

**Issue by jmc420** [webpack/webpack#1942]
Hi 

I am using webpack 2 and everything has been working fine until I added node-notifier to my package.json.

When I added node-notifier, the webpack build worked ok but at run time I got this error:

Uncaught Exception:
TypeError: Invalid Version: function __webpack_require__(moduleId) {

This was called because when webpack bundled semver.js (which is used by node-notifier) it inserted these lines of code:

	// Use the define() function if we're in AMD land
	if (true)
	  !(__WEBPACK_AMD_DEFINE_FACTORY__ = (exports), __WEBPACK_AMD_DEFINE_RESULT__ = (typeof __WEBPACK_AMD_DEFINE_FACTORY__ === 'function' ? (__WEBPACK_AMD_DEFINE_FACTORY__.call(exports, __webpack_require__, exports, module)) : __WEBPACK_AMD_DEFINE_FACTORY__), __WEBPACK_AMD_DEFINE_RESULT__ !== undefined && (module.exports = __WEBPACK_AMD_DEFINE_RESULT__));

if I comment out these lines, the problems go away.

How do I stop webpack from inserting these lines?

**Comment by jmc420** [comment]
the problem is caused because node-notifier uses semver version 4.1.0 and this appears to cause webpack to think it is an amd module and this causes webpack to insert the WEBPACK_AMD_DEFINE_FACTORY code. Any way to stop this?

**Comment by sokra** [comment]
``` js
if (typeof define === 'function' && define.amd)
  define(exports);
```

This is wrong when exports is a function.

**Comment by al-the-x** [comment]
For people who find this issue in future because of the same bug, you can use [`imports-loader`](https://webpack.js.org/loaders/imports-loader/) on `semver@4` to [force `webpack` to ignore the faulty `define` call and force CommonJS](https://webpack.js.org/loaders/imports-loader/#disable-amd):

```js
// webpack.config.js
module.exports = (env) => ({
  // . . .
  module: {
    rules: [
      { test: require.resolve('semver'),
        use: 'imports-loader?define=false'
      }
    ]
  }
  // . . .
});
```
