### ISSUE TITLE
Any Way to Reverse the Order of Require.Context?

### ISSUE THREAD

**Issue by pixelshaded** [webpack/webpack#1945]
In my particular use case, I have a folder structure like this:

- angular
    - directives
        - date-range
            - index.js
        - module.js
- module.js

And id like to simply do
```javascript
require.context('./angular');
```

Right now it seems to include files in the bundle in child first order. So my directives are getting put in the file before the module definitions. Essentially Id like files higher up in the hierarchy to appear before files deeper in the hierarchy.

Is there anyway to do this with require.context?

**Comment by taurose** [comment]
I don't think the order in which they are included in the bundle should really make a difference, should it? I'm guessing you're concerned about the order in which they are executed if you have implicit dependencies like

````js
// a.js
window.ModuleA = ...;

// b.js
window.ModuleB = /* using window.ModuleA */;
```

In that case, I think you can achieve it like this:

```js
var context = require.context('./angular');
var modules = context.keys();

// sort them
var sortedModules = modules.slice().sort(function(a, b) {
  // by directory depth
  var diff = a.match(/\//g).length - b.match(/\//g).length;
  if ( diff !== 0) return diff;

  // if depth is the same, sort alphabetically to make it stable
  return a < b ? -1 : (a > b ? 1 : 0);
});

// execute them
sortedModules.forEach(function(key) {
  context(key);
});
```

**Comment by pixelshaded** [comment]
For this use case, the module files create the modules. The directive files then add directives to those modules. If those modules aren't run and exist before the directive code is run, things won't work right. These aren't commonjs at the moment. I'm really just using webpack process (es6 babel etc) and concat all the files together.

So I started comparing the output for better understanding, and it seems I totally misunderstood what's going on. I haven't gotten to the point yet of testing the bundle on a page and had assumed that the order in which the modules appeared in output was the order they would be executed (aka a pure concat). WRONG. I didn't realize an array of module functions was being passed to the bootstrapper. This is commonjs for front end. Nothing is run until you require a module. All require.context was doing was setting up the modules. So yes, the order of modules passed to the bootstrapper doesn't matter. The order in which you require those modules does, hence your example of re-ordering the keys based on directory depth and then executing them in that new order.

Thanks for taking the time to answer my question.
