### ISSUE TITLE
Broken loader and context upgrading from 2.0.2 to 2.0.4 (persists in 2.0.5)

### ISSUE THREAD

**Issue by mattkrick** [webpack/webpack#1947]
Everything working great in 2.0.2.
Starting in 2.0.4, `modules.loaders[].include` no longer accepts an array.

Additionally, calling `import` on filepaths that treat the context as the resource root are now broken.

Reproduction case here (just upgrade to 2.0.4+ to make it break): https://github.com/mattkrick/meatier/blob/master/webpack/webpack.config.dev.js

Not sure if the 2 are related, but given the very few changes that took place between the 2 commits I'd guess so.

**Comment by sokra** [comment]
> Additionally, calling import on filepaths that treat the context as the resource root are now broken.

The configuration changed a bit: `resolve.root` `resolve.moduleDirectories` and `resolve.fallback` => `resolve.modules`.

So your config need to be changed:

``` diff
   resolve: {
-    extensions: ['', '.js'],
-    root: path.join(root, 'src')
+    extensions: ['.js'],
+    modules: [path.join(root, 'src'), "node_modules"]
   },
```

> Starting in 2.0.4, modules.loaders[].include no longer accepts an array.

fixed

**Comment by mattkrick** [comment]
thanks for the quick fix! i like the look of the new resolve config, very clean.

**Comment by sokra** [comment]
> i like the look of the new resolve config, very clean.

:smile: It's not yet documented, but here is a list: https://github.com/webpack/enhanced-resolve/blob/master/lib/ResolverFactory.js#L40-L85
