### ISSUE TITLE
require.ensure doesn't work with DLLPlugin.

### ISSUE THREAD

**Issue by alexpods** [webpack/webpack#1948]
I have:

```js
// ./webpack.config.js
const webpack = require('webpack');
const DllPlugin = webpack.DllPlugin;

module.exports = {
  entry: {
   test: [__dirname + '/test.js']
  },
  output: {
    path: __dirname + '/dist',
    filename: '[name].js',
    library: '[name]_[hash]',
    libraryTarget: 'var'
  },
  plugins: [
    new DllPlugin({
      context: __dirname,
      name: '[name]_[hash]',
      path: __dirname + '/dist/test-manifest.json'
    })
  ],
  resolve: {
    extensions: ['', '.js']
  }
};


// ./test.js
require.ensure([], function(require) {
  console.log(require('./test2'));
});


// ./test2.js
module.exports = 10;
```

Then I run:
```
$ webpack --config webpack.config.js 
```
And webpack process **terminates abruptly without any error messages**

If I change `test.js` file to just:
```js
  console.log(require('./test2'));
```
then everything will work fine

webpack 1.12.12
node: v5.4.1

**Comment by alexpods** [comment]
@bebraw I think `bug` tag is much more appropriate then `enhancement`. And it's definitely not a `question`.

**Comment by sokra** [comment]
hmm... it does work in my test case, but I only tested it for webpack 2.

Could you try it with webpack@2.0.6-beta?

**Comment by alexpods** [comment]
@sokra Yes, of course. In 10 minutes I'll tell you the results.

**Comment by alexpods** [comment]
@sokra Yes, it works for *2.0.6-beta* on my computer too, but terminates for *1.12.12*.

**Comment by alexpods** [comment]
@sokra Hmm. It works with **1.12.12** on Ubuntu 14.04.3, but terminates on my mac:(

**Comment by alexpods** [comment]
@sokra Well, I'll just try to use second version of webpack. Feel free to close this issue.

**Comment by underbayan** [comment]
you can add the chunk* files into entry of config manually so the webPack will pack it ， and then the require ensure will work
