### ISSUE TITLE
dynamic import() chunk name

### ISSUE THREAD

**Issue by kesne** [webpack/webpack#1949]
Using `import()` with a module seems to just give it an id as a name. It would be nice to either be able to name the chunk, or to use a name derived from the name of the import.

**Comment by sokra** [comment]
The ES6 spec doesn't support this and webpacks `System.import` implemenation should be comply to the spec.

Why do you need a chunk name?

**Comment by kesne** [comment]
The chunk name can be really useful for debugging to figure out the filename that an error is being thrown from, for example.

I understand that this would be non-spec based on the current whatwg loader spec.

**Comment by jmurzy** [comment]
@sokra @kesne I agree webpack should not deviate from the loader spec. Given we only need the chunk name at build time, what about using configuration comments to achieve the same thing?

```js
System.import('./foo') // webpack chunk-name bar
```

Obviously, you can't dynamically name chunks but AFAIK that wasn't supported in Webpack 1 either.

**Comment by bardt** [comment]
I also worry about assets caching. Given a name has a pattern of `[chunkhash].[name].js`, we get something like `f4621a974f1f255ce2bf.0.js`, which has greater chances of name collision with another chunk in the future than, say, `f4621a974f1f255ce2bf.foo.js`. 

Do my words have sense?

**Comment by zazagag** [comment]
...plus we won't optimize them by CommonChunkPlugin with unknown chunk names. or I somthing missed?

**Comment by vinhlh** [comment]
+1

**Comment by whitecolor** [comment]
@bardt what collision do you expect based on hash value? The reason I would like to have meaningful names for chunks (not just numbers) is more easier debug/inspection of build result while dev and event production.

@sokra 
Just asked this question on SO http://stackoverflow.com/questions/39564726/webpack2-meaningful-names-of-chunks

**Comment by troutowicz** [comment]
Another benefit to chunk naming is the ability to save a trip when requesting initial assets for a SPA.

https://github.com/webpack/docs/wiki/optimization#single-page-app

**Comment by jharris4** [comment]
+1

I just took a shot at migrating from webpack 1.x to webpack 2.x and losing the ability to name the chunks means it's a lot harder to debug/inspect what's going on with the code splitting

**Comment by cvle** [comment]
@troutowicz I was able to do it using a solution combining webpack stats, `__filename` and line of code.

**Comment by whitecolor** [comment]
@cvle you could show it

**Comment by cvle** [comment]
@whitecolor @troutowicz I refactored my code and put the relevant code into a separate repository and published to npm.

Here is what I use to include initial chunks to the server response:
https://github.com/wikiwi/webpack-initial-chunks.

**Comment by cvle** [comment]
Here it is: https://github.com/wikiwi/webpack-content-chunks

**Comment by troutowicz** [comment]
@cvle Looks like an interesting approach! But I am no longer lazy loading chunks due to perf issues.

**Comment by tleunen** [comment]
It would be really great to have a proper way to name the chunks, it would help a lot debugging things and also knowing what needs to be improved right from the webpack output.
Right now.. We just see that the chunk 0, 1, 2, 3 have  a filesize of X :/ No idea why I need to change to improve the file size for example (without further investigation on what are the chunks obviously).

**Comment by mikestead** [comment]
Could we support something like this? 

```javascript
import('/Home?chunk=home');
```

**Comment by folmert** [comment]
The problem is that if you're using output.path, the ID is added not before chunk's name, but before the path, which leads to creating very weird directories.

For example with config like this:
```
output:  {
    path: './../../development/app/dist/js/', // this is added after ID
    chunkFilename: '[name].[id].js', // this is ignored
    publicPath: './'
}
```

something really strange appears in webpack's directory:

```
[0..] // yes, this is a directory name
--[development]
----[app]
------[dist]
--------[js]
-----------analytics.js
[1..]
--[development]
----[app]
------[dist]
--------[js]
	-----------analytics.js
[2..]
--[development]
----[app]
------[dist]
--------[js]
	-----------analytics.js
[node_modules]
webpack.config.js
```

**Comment by Kovensky** [comment]
I wonder if that's how you're supposed to use https://github.com/webpack/bundle-loader

**Comment by vjancik** [comment]
@sokra Given now that the `System.import` function was renamed to `import` because it [wasn't complying with the spec](https://webpack.js.org/guides/migrating/#code-splitting-with-es2015) anyway, could we reconsider adding an optional parameter to support naming chunks?

My personal usecase is using code splitting in combination with service-worker runtime caching.

Using `sw-toolbox` you can specify cahcing rules based on a regex of the name of the asset. I'd like to cache some chunks, and not cache others depending on how "rare" they are, from user's usage perspective.

**For that I need to be able to name chunks**.

**Comment by simon04** [comment]
Related/duplicates: #2369, #2682, #3132.

**Comment by danbucholtz** [comment]
Ionic Framework team would greatly like named chunks. It would make our lives easier for implementing a complicated build process and it would surely make debugging easier for our users utilizing code splitting.

Thanks,
Dan

**Comment by romulof** [comment]
How about adding a new `[module]` variable in `chunkFilename` config?

**Comment by bebraw** [comment]
My current understanding is that this could be implemented through a comment. Example:

```javascript
import('path/to/module' /* demoName */).then(doStuff)
```

This way would not interfere with the specification in any way in case they add new parameters etc. and would allow to keep this information specific to webpack.

**Comment by mc-zone** [comment]
Also in great need of this feature. I've pushed a PR #4573 to make it work with specific comment:
 
```javascript
import('./foo' /* webpackChunkName = "myChunkName" */).then(function(foo){
    //...  
});
```

@sokra @bebraw @simon04 Looking forward to your review and feedback. :)

**Comment by quinn** [comment]
glad there is a PR, but the comment theme seems weird compared to [this comment](https://github.com/webpack/webpack/issues/1949#issuecomment-286544528). It seems like there should be a way to just tell webpack to always do this and use the filename (instead of meaningless numbers)

**Comment by mc-zone** [comment]
@quinn Through the configuration may not flexible. Assume there are two entries that need import `moduleA` both, the one entry want to put it into `chunk-module-a`, but another want to put it into `chunk-tiny-modules`, then we have to make two versions of configuration. There are much difference with `require.ensure`'s useage and implementation.

**Comment by quinn** [comment]
@mc-zone thanks, I figured it was due to my limited understanding of webpack

**Comment by arackaf** [comment]
I don't quite understand why the name can't be computed from the full path of the file.  So 

import(./foo)

Might create, say,  

contacts-details-util-foo.js

Could be a useful default to have, so we wouldn't need to add a webpack-specific comment on every import to have meaningful chunk names.

**Comment by mikestead** [comment]
@arackaf What if you refactor and rename a folder or move things around, you'd need to update refs to your chunk names?

I'm also not a big fan of the comments though, which seems to have made it into webpack. I'm still in favour of the query parameter option `./Settings?chunk=settings`. Seems at home with webpack's import style.

**Comment by arackaf** [comment]
@mikestead I don't think so - async chunks that webpack makes usually have dynamic, names that are created on the fly; you're not normally able to reference those directly because you have *no idea* what webpack will call them. 

My comments were just suggesting that webpack instead give them more friendly names by default, derived from the file path, just so we can debug a bit more easily, ie have a better idea where the a problem is if its in contacts-utilities.js as opposed to 16-chunk.js.

But alas it seems I'm in a minority here :(

**Comment by Rhionin** [comment]
I agree with @arackaf that more human-readable default names would be nice. However, I'd still like to be able to give chunks a name that I specify, just like require.ensure did

**Comment by bebraw** [comment]
Yeah, I agree that having better names (and module ids) by default would be a step forward.

**Comment by arackaf** [comment]
@Rhionin ftr, I agree.  I'm glad the team added the comment naming to import().  I'd just like to see it coupled with some sane default naming scheme to get the best of both worlds.

**Comment by romulof** [comment]
Using `require.ensure` I could pass an array of modules to bundle in a separate chunk.
Is it possible to use several `import()` calls with the same `webpackChunkName` to bundle them in the same chunk or I'll have to use a proxy module?

**Comment by sokra** [comment]
> Is it possible to use several import() calls with the same webpackChunkName to bundle them in the same chunk?

yes

**Comment by chrisdeely** [comment]
@romulof @sokra 

> Is it possible to use several import() calls with the same webpackChunkName to bundle them in the same chunk?

> yes

Can anyone provide a working example of this? I cannot get a common chunk created with multiple files using the same ```webpackChunkName``` value.

```javascript
Promise.all([
    import('path/1/file1' /* webpackChunkName:"subload" */), //appears in subload.js
    import('path/2/file2')                     //appears in [id].js
])
```

```javascript
Promise.all([
    import('path/1/file1' /* webpackChunkName:"subload" */), //appears in [id].js
    import('path/2/file2' /* webpackChunkName:"subload" */) //appears in subload.js
])
```

Is it a problem to have the source files at different paths?

**Comment by romulof** [comment]
@chrisdeely this is working for me:

```es6
async function loadIntl() {
  await import(/* webpackChunkName: "polyfill-intl" */ 'intl');
  await import(/* webpackChunkName: "polyfill-intl" */ 'intl/locale-data/jsonp/en.js');
  warning(false, 'Intl polyfill enabled');
}
```

**Comment by chrisdeely** [comment]
Thanks @romulof working now, but not sure what I did wrong before

**Comment by hooblei** [comment]
For the record - the solution as described [here](https://webpack.js.org/guides/code-splitting-async/#chunk-names) and mentioned above doesn't work when comments are stripped along the way - e.g. setting `comments` to `false` in .babelrc

**Comment by simshanith** [comment]
Could it be possible to have a __dynamic__ chunk name for a dynamic import? E.g.

```js
(relativeModulePath, chunkName) =>
import(
  /* webpackChunkName: `chunk-${chunkName}` */ `./${relativeModulePath}`
)
```

Hardcoded chunk names limit dynamic chunking abilities.

**Comment by folmert** [comment]
Agree with @simshanith, that would be very useful when having large amount of dynamic imports. It would be even cooler to be able to define that in webpack config, like:
```
output: {
    filename:      'js/[name].js',
    chunkFilename: 'js/[filename].js' // so that import('module') creates module.js
    chunkMode:     'lazy-once' // so I can override default `lazy` option once and for all
}

**Comment by monkindey** [comment]
Use NamedChunksPlugin can custom your dynamic import chunk name

```js
...
// used by code below;
paths.assets = 'path/to/project/resource/assets';
```


```js
new webpack.NamedChunksPlugin(function(chunk) {
    // if it have name, and return name
    if (chunk.name) {
        return chunk.name;
    }
   
    const regex = new RegExp(`${paths.assets}/pages`);

    // every chunk have _modules, and iterate it.
    for (var m of chunk._modules) {
        // module context is the module path of webpack resolve for you.
        // such as require('react')
        // context will be /path/to/project/node_modules/react
        // because I want to locate the dynamic import url rather than other module.
        // and I know the dynamic import path have the prefix like /path/to/project/`resource/assets/pages`
        // so I can locate it use regex.
        if (regex.test(m.context)) {
            // return whatever name you defined
            return path
                .relative(paths.assets, m.context)
                .split('/')
                .slice(1)
                .join('_');
        }
    }

    return null;
})
```

**Comment by jimthedev** [comment]
@monkindey Thank you. One thing for future people using that to note is that path.assets should be the path to your source and you would need to bring in both webpack and path modules for this to work.

**Comment by monkindey** [comment]
yes, you are right. I omit it. Thanks.

**Comment by simshanith** [comment]
As a follow up to my dynamic chunk name request, looks like there have been dynamic placeholders since 2.6:

> webpackChunkName: A name for the new chunk. Since webpack 2.6.0, the placeholders [index] and [request] are supported within the given string to an incremented number or the actual resolved filename respectively.

https://webpack.js.org/api/module-methods/#import-

I have yet to try it, and don't know if it can be composed with other strings, but guessing it would look something like this:

```js
(relativeModulePath) =>
import(
  /* webpackChunkName: chunk-[request][index] */ `./${relativeModulePath}`
)
```

**Comment by andkhong** [comment]
This was inspired by monkindey

        const regex = new RegExp(`${sourcePath}`);
        new webpack.NamedChunksPlugin(function(chunk) {
            if (chunk.name) return chunk.name;
            for (var m of chunk._modules) {
                if (regex.test(m.context)) {
                    return path.basename(m.rawRequest);
                }
            }
        })

**Comment by monkindey** [comment]
Why not works fine in production?

**Comment by andkhong** [comment]
It somehow runs into errors with chunk names and styles. The app will still run but you end up with split code with weird names.

**Comment by monkindey** [comment]
Maybe some different environment between development and production ?

**Comment by andkhong** [comment]
Yes, due to different environments and, chunk names are in different paths so my logic above doesn't work. IMO, it's better to fall back to standard IDs because named chunks really only matter for debugging in development.

**Comment by jeremywiebe** [comment]
@simshanith Just note that you need quotes around the value passed to `webpackChunkName`. Took me a while to get your example working and that was the issue! 

```js
(relativeModulePath) =>
  import(
    /* webpackChunkName: "chunk-[request][index]" */ 
    `./${relativeModulePath}`
  )
```

**Comment by hckrmoon** [comment]
For React with typescript user, adding 'removeComments': false to ts-loader options is working rather than adding 'removeComments': false to tsconfig.json.

**Comment by tgxhx** [comment]
Hi, I wrote a babel plugin to name dynamic chunk:
``` javascript
importName('./a.js', 'name-a')
```

and it will be transformed to
``` javascript
import( /*webpackChunkName: 'name-a'*/'./a.js');
```

https://www.npmjs.com/package/babel-plugin-webpack-async-module-name

**Comment by hjzheng** [comment]
you can try https://gist.github.com/hjzheng/969c47661f4636d15a0234b3ce1edc72

**Comment by adi518** [comment]
I think this caters to more use-cases: https://github.com/bloody-ux/babel-plugin-path-chunk-name
