### ISSUE TITLE
compiler watchOptions are ignored in compiler.watch

### ISSUE THREAD

**Issue by DarkPark** [webpack/webpack#1951]
I have a compiler with watch options:

```js
var compiler = webpack({
    ...
    watchOptions: { ... }
    ...
});
```

then I start watching:

```js
compiler.watch(watchOptions, function ( error, stats ) {
    // why I should put watchOptions here again?
    // they are already set for compiler as described in documentation
});
```

it would be nice to be able to just start watching as it has all the necessary info:

```js
compiler.watch(function ( error, stats ) {
    ...
});
```

or even without callback as I may not need error/stats info:

```js
compiler.watch();
```

**Comment by sokra** [comment]
You don't need the `watchOptions` in the configuration. You only need to provide it in the watch call.

`watchOptions` in configuration is only used by the CLI. Just like the `devServer` key which is only used by the dev server CLI.

**Comment by DarkPark** [comment]
@sokra quote from documentation:
"(only used when using CLI or simple node.js API)"
and I exactly use it in simple node.js API.

From architectural point of view maybe it's reasonable to split page configuration to a couple of config files.

**Comment by sokra** [comment]
yep thanks, I changed the documentation.

**Comment by DarkPark** [comment]
It is still confusing.
The whole page https://webpack.github.io/docs/configuration.html is clearly about the single configuration object passed to webpack.
It's rather strange to describe some options among compiler options but forbid to use these options for compiler.

**Comment by pksjce** [comment]
This issue was moved to webpack/webpack.io#125
