### ISSUE TITLE
Can webpack accept required loaders?

### ISSUE THREAD

**Issue by sosz** [webpack/webpack#1954]
When adding a loader, we usually write:
```
{ tests: /\.js$/, loader: 'babel', query, include }
```

I was wondering if it is possible to provide the loader directly, e.g.:
```
{ tests: /\.js$/, loader: require('babel-loader'), query, include }
```

Also, for query parameters:
```
{ ...babelLoader, query: { plugins: [require('babel-plugin-transform-es2015-classes')] } }
```

I'm guessing webpack expects the query to be serializable, but it can be useful to do the above... Currently, webpack loaders receive the query as `{ plugins: [null] }`.

**Comment by sokra** [comment]
No. But you can use `loader: require.resolve('babel-loader')`
