### ISSUE TITLE
exclude module from entry point build

### ISSUE THREAD

**Issue by rosenfeld** [webpack/webpack#1955]
I'd like to move from Rails Assets Pipeline to webpack, but I'm planning doing this in baby steps.

The first move is to create chunks from npm packages similar to the ones currently used by our application.

I want to be able for example to generate a jquery.js and a jquery-ui.js, while the latter wouldn't contain the former. The externals configuration apply to the whole config file but I only want to tell webpack to not include jquery.js for the jquery-ui.js entry point. Something like this:

```javascript
  entry: { 'app/main': './js/main.js'
    , 'lib/jquery': './js/libs/jquery.js'
    , 'lib/jquery-ui': './js/libs/jquery-ui.js'
  }
```

js/libs/jquery.js has `require('script!jquery');`.
js/libs/jquery-ui.js has `require.context('jquery-ui/ui', true, /\.js/);`

How can I tell webpack to not include the jquery source for the 'lib/jquery-ui' entry point only?

My goal is to be able to generate alternative entry points which would contain jquery and other vendor libraries in some 'bundle/vendors' entry point for example, so I can't use the externals config.

Is there a way to set up externals in a per entry point basis? Or to tell some require to replace `require('jquery')` with `jQuery`?

**Comment by sokra** [comment]
Use http://webpack.github.io/docs/configuration.html#multiple-configurations

**Comment by rosenfeld** [comment]
Thanks! I have missed this! Very useful indeed!
