### ISSUE TITLE
Build error in sock-js after adding "resolve.packageAlias" option

### ISSUE THREAD

**Issue by jeron-diovis** [webpack/webpack#1956]
webpack@1.12.11

Just adding `packageAlias: "whatever"` in `resolve` section of my config, and build no more succeeds, failing with this:

```
ERROR in ./~/sockjs-client/~/faye-websocket/lib/faye/websocket/client.js
Module not found: Error: Cannot resolve module 'net' in /path/to/project/node_modules/sockjs-client/node_modules/faye-websocket/lib/faye/websocket
 @ ./~/sockjs-client/~/faye-websocket/lib/faye/websocket/client.js 2:13-27

ERROR in ./~/sockjs-client/~/faye-websocket/lib/faye/websocket/client.js
Module not found: Error: Cannot resolve module 'tls' in /path/to/project/node_modules/sockjs-client/node_modules/faye-websocket/lib/faye/websocket
 @ ./~/sockjs-client/~/faye-websocket/lib/faye/websocket/client.js 3:13-27
```

Without this option everything works.
Am I doing something wrong?

**Comment by sokra** [comment]
By adding `packageAlias: "whatever"` you are overwriting the default `packageAlias` (`"browser"`). This alias is used by many packages to provide browser versions (i. e. the `faye-websocket` lib). So configurate it with `packageAlias: ["whatever", "browser"]` to keep the browser mappings.

**Comment by jeron-diovis** [comment]
Hmm, strange, but this didn't help. 
And I didn't found `"browser"` field in package.json of `faye-websoket`: https://github.com/faye/faye-websocket-node/blob/master/package.json

**Comment by sokra** [comment]
Sorry, it's here: https://github.com/sockjs/sockjs-client/blob/master/package.json#L6-L12

**Comment by bebraw** [comment]
Closing as this has been answered.

**Comment by IzaGz** [comment]
@bebraw  how to fix this? i have the same  problem
