### ISSUE TITLE
Managing modules resolving priority

### ISSUE THREAD

**Issue by jeron-diovis** [webpack/webpack#1957]
The [docs says](http://webpack.github.io/docs/resolving.html#resolving-a-module-path) that resolving order is `resolve.root` => `resolve.modulesDiretories` => `resolve.fallback`.

Let say I have some repetitive structure:
```
/app
|- lib
|  |- ...
|- components
   |- my-component
       |- lib
       |   |- ...
       |- index.js
```
I know that my-component mostly uses it's local `lib`, and rarely needs something from global one too.
So I want `require("lib/...")` inside `components/my-component` to resolve to `components/my-component/lib` and some extra syntax to access global one. Or vice versa, also acceptable.

How to properly implement this with webpack?

For now I ended up with this config:
```
resolve: {
   fallback: "/path/to/app",
   alias: { "~":  "/path/to/app" }
}
```
and put `my-component/lib` into `my-component/web_modules/lib` (or any modulesDirectory I like).

It works as I want, but I don't know whether it is a "true" way. 
Please give me some advice about how real webpack ninjas would solve this task.

**Comment by sokra** [comment]
Inside your component you better use relative paths: `require("./lib/...")`.

So you only need `resolve.root: `/path/to/app/components` and the app alias.

**Comment by jeron-diovis** [comment]
@sokra In practice, `my-component` is one of app screens, and there are a lot of files there. Somewhere relative paths have 3-4 nesting levels. Writing paths like "../../../file" everywhere seems to be a bad idea, that's why I'm looking for some shortcuts.

**Comment by sokra** [comment]
With `resolve.moduleDirectories: ["lib", "node_modules"]` it will walk up the hierachy and resolve in every lib folder it finds.

**Comment by jeron-diovis** [comment]
But before `moduleDirectories` it will check `resolve.root`, right? So to make it work I should also use `resolve.fallback` instead `resolve.root`, otherwise `require("lib/...")` will resolve to `app/lib`.

**Comment by sokra** [comment]
yep

**Comment by jeron-diovis** [comment]
Hm, so my topic solution appears to be totally correct.
Well, thanks for your answers.
