### ISSUE TITLE
Loader the executes JS and returns its exports

### ISSUE THREAD

**Issue by sosz** [webpack/webpack#1961]
I'm trying to write a loader that takes an object and returns a string:

``` js
function myLoader(content: object): string {
    return myTransform(content);
}
```

I want to be able to apply this loader to JS module files with a custom extension:

``` js
// some-file.my-ext
export default { some: 'object' }
```

So I'm looking for a loader that can be run before mine, that will read the file and give me its exported contents:

``` js
{ default: { some: 'object' } };
```

Does anything like this already exist?

---
### Additional Notes

**The loader should Import other JS files from these custom files**

``` js
// normal-js-file.js
export default 42;

// other-file.my-ext
import value from './normal-js-file';
export const x = `the value is ${value}`; 
```

So I want my loader to receive:

``` js
{ x: { 'the value is 42' } }
```

**The loader should mark all imported files as dependencies**
In the example above, the loader should mark `normal-js-file.js` as a dependency.
Also, if `normal-js-file.js` itself had dependencies, they should be marked as well.

**Use other loaders to load the custom file and its dependencies**
Since the user is using his own JS loaders (like babel, ts, etc.), I want the loader to use these user-defined `.js` loaders to also load my custom `.my-ext` files, and all imports from `.my-ext` should work as usual (with existing loaders):

``` js
// some-file.my-ext
import jsFile from 'js-file';
import es6File from 'file.es6';
import pngFile from 'file.png';

export { jsFile, es6File, pngFile };
```

---

So, does something like this exist? Or am I going about it all wrong?

**Comment by bebraw** [comment]
What's the use case for this? Is the problem relevant with webpack 2?

**Comment by sosz** [comment]
I haven't looked much into webpack 2 yet. I still think this is relevant, unless webpack 2 somehow addresses this issue already.

A year ago I've worked on a small project to create a "js-to-css" transpiler. I wanted to create a loader for this transpiler. The idea was to transform Javascript objects such as `{ body: { "background-color":  "black" } }` to corresponding CSS declarations: `body { background-color: red; }`.

Of course, there would be many utility functions and all other possible JS-goodness that would contribute to create these CSS JS objects, so I want a loader that can simply take the exported object of a module after all relevant Webpack transformations have been applied to it.

**Comment by TheLarkInn** [comment]
Feel free to look at webpack.js.org/api/loaders for all of the options that you can use. Since this is more support/question, I'm going to close this issue in favor of recommending you reach out to gitter.im/webpack/webpack or StackOverflow, etc.
