### ISSUE TITLE
Node `global` polyfill is broken by 'use strict'

### ISSUE THREAD

**Issue by gaearon** [webpack/webpack#1963]
I think I may have found an issue caused by how how Webpack polyfills `global`.

[Here's what happened:](https://github.com/lodash/lodash/issues/1916)

0. Lodash uses `global` in its code
1. We introduced Lodash as a dependency into Redux
2. I noticed that the UMD build (created with Webpack) is broken *if transpiled another time with Babel*

We could argue that transpiling UMD builds is wasteful but some people do that due to bad configurations, and we don't want to break them.

So why is the build broken? This happens because Webpack `global` polyfill emits code like this:

```js
    /* WEBPACK VAR INJECTION */}.call(exports, (function() { return this; }())))
```

This works as a polyfill in most cases but if you add `'use strict'` at the top of the file, it will return `undefined` due to strict semantics. And Babel adds `'use strict'`.

It would be nice if the `global` polyfill was resistant to `'use strict'`. For example, Lodash uses `Function('return this')` as last resort, which is immune to strict semantics. However this may cause issues in restricted environments.

In practice, some combination of global checks might be helpful. Unfortunately I don't know enough about the ways to fix that, but hope it helps!

**Comment by sokra** [comment]
webpack emits non-strict code. You should not insert `"use strict"` at the top. This means: only use babel on ES6 code. The error is to run babel on the bundle. This could break other stuff too (that's why you shouldn't run the babel-loader on node_modules).

But anyway we can change the default to a more safe approach.

`(function() { return this; }())`
`(1,eval)('this')`
`Function('return this')()`

This mean more code and why better move it into a separate module instead of injecting it into every module.

**Comment by sokra** [comment]
This was fixed

**Comment by arb** [comment]
@sokra can you expand on "this was fixed"? What version? Where is code? I'm having the same issue and I'm babel transpiling a node-module that has "use strict;" at the top of it.

**Comment by sokra** [comment]
https://github.com/webpack/webpack/commit/2ff9a247e242f716b8ad41da460ca57108617d36

**Comment by sokra** [comment]
only in webpack 2. If you want to backport it to webpack 1 feel free to send a PR.

**Comment by phun-ky** [comment]
> that's why you shouldn't run the babel-loader on node_modules

@sokra hm, but if you want tree shaking to work then? Sorry for jumping into this issue like this.
