### ISSUE TITLE
Eliminate empty chunks?

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack#1967]
Assuming you have an entry pointing at just CSS files and use `ExtractTextPlugin` to push those to a file of its own, webpack will still generate a file like this for the chunk:

``` javascript
webpackJsonp([1,3],[function(n,c){}]);
```

This does literally nothing. But unfortunately tooling like `HtmlWebpackPlugin` will still generate a `script` tag for it. It might be sensible to detect `noop` cases like this and not to emit the JS files at all in these kind of cases.

**Comment by ccbikai** [comment]
+1

**Comment by inertum** [comment]
+1

**Comment by kfir124** [comment]
+1

**Comment by stefanfrede** [comment]
+1

**Comment by OlegLustenko** [comment]
+1

**Comment by gbhasha** [comment]
+1

**Comment by lancebiu** [comment]
+1

**Comment by shehi** [comment]
+1

**Comment by khronic** [comment]
+1

**Comment by liangsu1210** [comment]
+1

**Comment by Gpx** [comment]
Please avoid adding +1 comments, they only add confusion to the issue. Instead, add a reaction to the original comment

**Comment by rewmike** [comment]
+1

**Comment by rewmike** [comment]
Does anyone have a workaround for this?

**Comment by Kovensky** [comment]
There is a `webpack.optimize.RemoveEmptyChunksPlugin`, but I'm not sure it would deal with cases like the snippet in the OP. The code there does have a module in the chunk; it's the module that's empty, not the chunk.

**Comment by Velenir** [comment]
As a workaround you could use `exludeJSChunks: ["css-only chunk"]` with [html-webpack-template-pug](https://github.com/Velenir/html-webpack-template-pug)

/shameless self-promotion

**Comment by jkomusin** [comment]
I recently used a plugin with a hook for the 'done' event to remove files for chunks that I knew in advance were going to be empty. Not a great workaround, but it may work for some. https://www.npmjs.com/package/on-build-webpack is an example, as you can see from the source writing your own such plugin is trivial.

**Comment by kenberkeley** [comment]
Solution: https://github.com/jamesjieye/html-webpack-exclude-assets-plugin

**Comment by avesus** [comment]
@kenberkeley it's not what it's source code tell me it's doing. No solution yet.

**Comment by heyflo** [comment]
Any update on this ? Still having useless `*.js` files being generated when having a CSS-Only entry. Thanks for your time 👍

**Comment by xwenliang** [comment]
come from https://github.com/webpack-contrib/mini-css-extract-plugin/issues/279, any idea here?

**Comment by jimblue** [comment]
There is so many people having this problem... Is there any update about a fix... This issue is already 3 years old! 😞

**Comment by stephan-v** [comment]
Hahaha don't get your hopes up.

**Comment by evilebottnawi** [comment]
Let's close in favor https://github.com/webpack/webpack/issues/7300, because it is the same problem, and it fixed in master
