### ISSUE TITLE
problem with webpack handling array extensions Raw

### ISSUE THREAD

**Issue by Sigfried** [webpack/webpack#1969]
See http://stackoverflow.com/questions/35128241/extreme-es6-array-extension-weirdness-it-reverts-to-regular-array-with-webpack for a lengthy explanation, or use this gist: https://gist.github.com/Sigfried/5c96b880d7986776e541 to replicate. 

I use a setter on an object setting one of its properties to another object that is extended from a class extended from Array. The setter checks the type of thing it's getting, and it's getting an Array rather than the thing inherited from Array that it expects. The problem does not occur in node or in jsfiddle (https://jsfiddle.net/sigfried/n2pab49q/), so it seems like a webpack bug. With the gist, for instance, `node index.js` works fine, but `node bundle.js` shows the same error as running the webpack bundle in a browser.

**Comment by loganfsmyth** [comment]
Babel is the thing providing your implementation of `class`, this is a Babel-related issue, not a Webpack one. See my answer on the SO question.

**Comment by Sigfried** [comment]
Yeah, I think the problem is that webpack is loading a different version of Babel, but I'm not sure what's the right one or how to get it. How do I find your answer to the SO question?

**Comment by loganfsmyth** [comment]
I mean I wrote an answer on the question you posted on SO.

**Comment by Sigfried** [comment]
Sorry, hadn't seen it yet. Responded there. Thanks much for the explanation!
