### ISSUE TITLE
'use strict' with harmony imports

### ISSUE THREAD

**Issue by sosz** [webpack/webpack#1970]
I'm transpiling my **Node.js serverside code** using `babel-loader`.
In order to utilize tree-shaking, I do not use `babel-plugin-transform-es2015-modules-commonjs`.
Webpack successfully parses these imports.

The problem is that webpack leaves all `'use strict';` expressions at the middle of modules, instead of transferring them to the top of the scope (webpack adds code above `'use strict';`). This causes Node.js to ignore the call to `'use strict';` and throw `SyntaxError`s for `let`, `const`, `class`, etc.

Manually moving `'use strict';` from the middle of the block to its top solves the problem.

**Note**
In order to make babel emit `'use strict';` at the top of every file, I'm using `babel-plugin-transform-strict-mode`.

**Comment by mastercactapus** [comment]
I'm also seeing this issue.

Temporary workaround is to create a plugin to prepend "use strict": https://gist.github.com/mastercactapus/05da17090e4a49d23173

**Comment by Unhelpful** [comment]
I'm working on this. It's not that hard to test if the first statement is "use strict" via a parser plugin and move the statement before any inserted dependencies, but there are a few gotchas. The statement must be /only/ the string literal "use strict", but acorn strips enclosing parentheses unless the preserveParens option is set. The parser could be modified to check for a proper strict mode statement before actually parsing the file, it could parse the file with preserveParens and produce an AST with non-standard ParenthesizedExpression nodes that the parser and plugins using it would need to be aware of, or strict mode could be detected at some other stage. I'm not sure what's really best in terms of webpack coding style.

**Comment by zowers** [comment]
@Unhelpful there is no need to analyze module's contents and move "use strict" if found. harmony modules are always strict by spec. so "use strict" should always be the first line of a transformed harmony module.

**Comment by Unhelpful** [comment]
The problem I was experiencing was that the combination of babel transformation plus webpack2 harmony import inserted webpack's transformed import statement before the first line, making the result non-strict. This is probably fine when Babel is completely transforming other ES6 features, but it led to errors when relying on platform support for ES6 features.

I can stay out of parse entirely by checking for harmony dependencies and adding a "use strict" above them, if that would be considered the more appropriate solution.
