### ISSUE TITLE
Problem installing in docker

### ISSUE THREAD

**Issue by ir-fuel** [webpack/webpack#1971]
This could be a complicated problem, and I don't know where to put it, so I start by putting it here.

What happens on a regular basis is that when building a Docker image containing webpack that the build bails out with a 

```
> jpegtran-bin@3.0.6 postinstall /var/www/node_modules/image-webpack-loader/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin
> node lib/install.js



The command '/bin/sh -c npm install' returned a non-zero code: 1
```

This only happens when building inside Docker, never when doing an `npm install` on my dev machine. What makes this problem hard is that the module that fails during the install changes. Sometimes it's this one, sometimes it's `caniuse`, sometimes it's the png code ...

The only constant I find is that it always seems to happen during webpack install. I have plenty of Docker files in several projects and only these seem to fail. All the others build without any issues whatsoever (nodejs app, php, .... )

Sometimes deleting all docker images/caches and rebuilding again solves the problem, sometimes it doesn't.

I have no idea on how to figure out what happens here, so any clues as on how to tackle the problem would be welcome.

this is my package.json declaration:

```
  "devDependencies": {
    "autoprefixer": "^6.0.3",
    "babel": "^5.8.23",
    "babel-core": "^5.8.25",
    "babel-loader": "^5.3.2",
    "copy-webpack-plugin": "^0.2.0",
    "css-loader": "^0.21.0",
    "extract-text-webpack-plugin": "^0.8.2",
    "file-loader": "^0.8.4",
    "handlebars-template-loader": "^0.5.4",
    "image-webpack-loader": "^1.6.2",
    "json-loader": "^0.5.3",
    "postcss": "^5.0.10",
    "postcss-custom-properties": "^5.0.0",
    "postcss-focus": "^1.0.0",
    "postcss-import": "^7.1.0",
    "postcss-loader": "^0.7.0",
    "postcss-nested": "^1.0.0",
    "postcss-url": "^5.0.2",
    "react-hot-loader": "^1.3.0",
    "redux-devtools": "^2.1.5",
    "style-loader": "^0.13.0",
    "webpack": "^1.12.2",
    "webpack-dev-server": "^1.12.1",
    "webpack-module-hot-accept": "^1.0.3"
  },
  "dependencies": {
    "axios": "^0.7.0",
    "classnames": "^2.2.0",
    "co": "^4.6.0",
    "color-string": "^0.3.0",
    "es6-promise": "^3.0.2",
    "express": "^4.13.3",
    "geojson": "^0.2.1",
    "handlebars": "^4.0.3",
    "history": "^1.12.5",
    "immutable": "^3.7.5",
    "material-ui": "^0.13.0",
    "normalize.css": "^3.0.3",
    "react": "^0.14.0",
    "react-color": "^1.2.1",
    "react-dom": "^0.14.0",
    "react-redux": "^4.0.0",
    "react-router": "^1.0.0-rc3",
    "react-tap-event-plugin": "^0.2.1",
    "redux": "^3.0.4",
    "redux-logger": "^2.0.4",
    "redux-promise-middleware": "^2.0.0",
    "redux-router": "^1.0.0-beta3",
    "validator": "^4.2.1"
  }

```

my Dockerfile is built upon node 4.2.4 , and before running `npm install` I install the latest version of npm inside my image using `RUN npm install npm@latest -g`

Hopefully someone can help me out.

**Comment by ir-fuel** [comment]
Seems that this dockerfile was node 4, not 4.2.4. For some reason that solved it.
Still don't understand why though.

**Comment by Ch4s3** [comment]
I'm having the same problem.

**Comment by casprian** [comment]
did you solve this?
