### ISSUE TITLE
module loaders - exclude a specific file instead of a directory

### ISSUE THREAD

**Issue by sanathko** [webpack/webpack#1972]
want to exclude a specific file trying this 
exclude: /(node_modules|bower_components|unitTest|models\/myTestModel.js)\//,

want to exclude only this file inside models directory. Is this possible?

**Comment by piecyk** [comment]
yes, try it like this:
```js
exclude: [
  /(node_modules|bower_components|unitTest)/,
  path.resolve(__dirname, 'models/myTestModel.js.js'),
]

```

**Comment by IngwiePhoenix** [comment]
@sanathko Did @piecyk 's answer help?

**Comment by warmhug** [comment]
hi, I want to exclude a directory in `node_modules`, such as `node_modules/xx/xx.../my_key_word_dir/lib/style/assets/*.svg`, the "my_key_word_dir" maybe anywhere in the sub dir of node_modules. How to do it? Someone can help me? Thanks very much.
