### ISSUE TITLE
Will/does Webpack support jsnext:main?

### ISSUE THREAD

**Issue by TehShrike** [webpack/webpack#1979]
To allow importing of ES6 modules with an ES5 module in the package.json's "main" field.

As [proposed by rollup](https://github.com/rollup/rollup#can-i-distribute-my-package-as-an-es6-module).

**Comment by IngwiePhoenix** [comment]
I +1 this.

Proposed:
- `jsnext:main` should be within the default list ( https://github.com/webpack/webpack/blob/master/lib/WebpackOptionsDefaulter.js#L83-L88 ) in WebPack2, since it understands ES6 OOTB.

However... Should `jsnext:main` be treatened in a way that it can't be ignored? Just a thought.

Kind regards,
Ingwie.

**Comment by SimenB** [comment]
https://github.com/webpack/webpack/issues/1612#issuecomment-158466366

**Comment by taion** [comment]
Coming from https://github.com/reactjs/react-router/issues/3333, I'd really like if there were a way to specify the location of the ES module build for webpack users.

I'm a little bit frightened that people are importing from the subdirectory containing the ES modules directly.

**Comment by rosskevin** [comment]
Is there a way to plugin a resolver to webpack 2 to _prefer_ `jsnext:main` and otherwise fallback to `main`?   I see a reference to [resolve.mainFields](https://webpack.github.io/docs/configuration.html#resolve-packagemains) but don't we still have to either `include` that dynamically as part of the `src` loading?

**Comment by TheLarkInn** [comment]
@sokra I could take a stab at this if this is as easy as it **_appears_** to be.

**Comment by taion** [comment]
Why do you need a plugin for this? Just set e.g.

```js
mainFields: ['jsnext:main', 'browser', 'main']
```

in your webpack config.

**Comment by rosskevin** [comment]
@taion - The problem with this approach is transitive dependencies (or so it seemed when I tried it).  I don't think it is as simple as it looks to simply configure or plug-in, it needs to be considered in the primary resolution so that we can take advantage of tree-shaking etc.

**Comment by taion** [comment]
It works just fine transitively.

**Comment by rosskevin** [comment]
That is my error in that case; if you have figured it out I'm sure all the participants here would like to see an example of this running.

**Comment by taion** [comment]
In `webpack.config.js`, just do e.g.

```js
resolve: {
  mainFields: ['jsnext:main', 'browser', 'main'],
},
```

That's all you need.

**Comment by rosskevin** [comment]
hmm, that didn't work for me when I tried it and I had multiple transitive dependency failures.  Several projects including `react-router` provide these sources yet my imports failed.  I was sure to allow sources to be pulled (not excluded) from `node_modules`.

**Comment by TheLarkInn** [comment]
I'd assume this would be a desired default with fallback for main. No?

**Comment by adamdicarlo** [comment]
Besides adding `'jsnext:main'` to `mainFields`, don't you need to somehow teach Babel "you actually need to process _some_ stuff in my `node_modules` folder"?

**Comment by umidbekkarimov** [comment]
@adamdicarlo 

That works for me

```javascript
{
  test: /\.js$/,
  loader: 'babel',
  exclude: /node_modules\/(?!(([^\/]+?\/){1,2}(src|es6)))/,
}
```
Tested it [here](https://regex101.com/r/dS8tJ8)

**Comment by adamdicarlo** [comment]
that matches `/node_modules/react-router/node_modules/foo/es6/index.js`. but anyway, I don't think checking for a folder named `src` or `es6` is a long term/general solution.

Webpack supports callbacks for exclude/include; in the past, I've set up logic to do this:

1. figure out which package the file is a part of (by recursively scanning folder & parent folders for a `package.json`), and
2. inspect that `package.json` to figure out whether its source needs transpilation

but if Webpack will support `jsnext:main` out of the box, it seems pretty silly to manually need to set up this kind of mechanism for every project...

**Comment by taion** [comment]
Babel doesn't need to process anything in `node_modules`. By convention, an ES module build is the same as the CJS build, with the only exception being the module system. The rest of the ESNext features should still be transpiled.

**Comment by adamdicarlo** [comment]
Hmm, right. That's maybe good enough in general. There are downsides, though: _your_ host project's babel plugins do not get applied to the (e.g.) React components you `npm install`ed. So you can't, for instance, use `babel-plugin-rewire` to mock a package in `node_modules`. You can't apply `babel-plugin-react-transform` to those components either.

And when `npm link`ing packages and working on them in the context of a host app—which is already a pain, of course—you'd have to have the linked package's build watcher running, too.

**Comment by adamdicarlo** [comment]
Another thought: What about the (not too distant?) future where we want to ship ES2015 code to browsers? Surely packages will mostly be written in ES2016 (or ES2017) then — so they'd need to provide ES5 *and* ES2015 (and eventually ES2016) builds. ¯\\\_(ツ)\_/¯  (WebAssembly support can't come fast enough IMO...)

**Comment by taion** [comment]
wasm isn't going to fix anything because if for some bizarre reason you decide to compile JS to wasm, you're effectively opting out of the bulk of things that the JIT can do.

Yes, it's true that the "projects ship transpiled code" has some set of disadvantages – but that's orthogonal to the question of the choice of module system used for distribution.

**Comment by umidbekkarimov** [comment]
@adamdicarlo 
>  I don't think checking for a folder named src or es6 is a long term/general solution.

Webpack 2 still in beta, so it's just temporary workaround

@taion 
> Babel doesn't need to process anything in node_modules. By convention, an ES module build is the same as the CJS build, with the only exception being the module system. The rest of the ESNext features should still be transpired.

Yep, but modules like [redux-form](https://github.com/erikras/redux-form/blob/master/package.json#L6) or [moment](https://github.com/moment/moment/blob/develop/package.json#L26) use `/src` dir in `jsnext:main`

**Comment by TehShrike** [comment]
My `jsnext:main`'s value will almost always be `index.js`.

**Comment by taion** [comment]
If maintainers are publishing code that requires further transpilation as an ES module build, then they are publishing that build incorrectly – you should follow up with those maintainers to publish a correct ES module build.

**Comment by rosskevin** [comment]
@taion, you are suggesting contacting almost everylib owner and convincing them to publish absolute standard ES6, vs getting webpack to acknowledge the transpiration pipeline? 

Which makes more sense?

Which is most likely to succeed?

**Comment by taion** [comment]
The transpilation pipeline is an opaque implementation detail. What if a package uses custom transpilation plug-ins – I do this in React Router to strip out warning and invariant messages in production builds. What if a library uses Flow types? Most of the FB ones do. What if a library uses Buble?

"Transpiling the contents of `node_modules`" isn't even a bad solution – it's not a solution at all, instead a gross misunderstanding.

**Comment by rosskevin** [comment]
Buble and flow are part of each dependency's transpilation configuration which I am suggesting we should try to find a way to acknowledge.  

To your second statement, you state a gross misunderstanding without any argument as a basis. It's difficult to discuss with you when you are making perhaps valid but unsubstantiated claims.

Transpilation is here to stay, and I only assume it will become more and more varied.  ES5, ES6, ES7, the constant is not the transpiled artifact's standard, it is that we are transpiling. 

Attempting to acknowledge a module's discrete transpilation pipeline is a viable option, albeit not an easy one. 

Attempting to convince every single lib owner to transpile to ES5 and 6, then 7, then 8 (over time), is a continous battle and a forever losing proposition. 

I think instead of trying to force the world forever to fit a standard (that changes), the community has spoken by adoption of transpilation, and we should try to find better ways to work with it.

**Comment by taion** [comment]
That's literally not what `jsnext:main` is: https://github.com/rollup/rollup/wiki/jsnext:main

See also: https://github.com/reactjs/redux/issues/1042

You can take it up more broadly in other places, but jsnext:main has a specific meaning. Furthermore this also happens to be the meaning that projects like Redux and React Router take.

**Comment by rosskevin** [comment]
Then perhaps we need something better?

**Comment by taion** [comment]
No – library authors need to understand and follow the spec instead of treating `src` as the ES module build.

The ES module build is just another build target – just like CJS, UMD, whatever.

There's nothing unique or special about it. Certainly there are concerns down the road for language features more broadly, but that's unavoidable, and moreover it's entirely orthogonal to the question of CJS v ES modules.

Why? Because your module system is _never exposed to the browser in the first place_. Otherwise why even bother bundling with webpack?

**Comment by rosskevin** [comment]
You are saying no, but it seems like you could be in the minority. My proposition, while perhaps difficult initially, would be enduring and not force others to see the tech world exactly as you do. My proposition is flexible, yours is the expecting the whole world to fall inline. Which has the highest likelihood of success?

**Comment by taion** [comment]
No, your proposal is that _literally every library has to expose consistent hooks for webpack to do a custom transpilation as needed by the application_.

That's much, _much_ more prescriptive and dramatically more impractical than just treating ES modules as another build target.

There's a very good reason that the high-profile libraries in the React space are all doing the correct thing rather than the incorrect thing.

**Comment by rosskevin** [comment]
Reason, correct, incorrect, are all based on your individual point of view. Who determines right and wrong?

My proposal is to optionally acknowledge a dependency's babel pipeline if present. How is that more prescriptive than you must put in a jsnext:main that conforms to es6?

**Comment by taion** [comment]
This isn't some arbitrary thing I pulled out of thin air.

This is:
1. What rollup says `jsnext:main` means (and how rollup handles it)
2. _Already_ what both `redux` and `react-router` do

It is this way because the other approach is literally unworkable. My Babel transpilation pipeline is an implementation detail of my library.

This isn't Browserify.

**Comment by rosskevin** [comment]
Rollups jsnext is not a standard, they made it up, and it works for their usage, and I support that. If you were there at the time it was discussed there, posing the equivalent antagonist on the same premise, you would have argued that you can't do it because no one else does.

We can create new ways of doing things, just as Rich and the rollups contributors did. If our creations are genuinely useful, people will use them, if not, they die.

It is quite reasonable that your transpilation pipeline can be expose in a reasonably standard way to execute it.

Instead of being an antagonist, I'd love it if you put your talent towards how we could make something great and useful. Your suggestion that the world do exactly as you want is unlikely to come true. Let's put effort into something that has a great chance of succeeding, shall we?

**Comment by psirenny** [comment]
There's a lot of tension here :grin:

Personally, I'd like to see an alternative standard. As a library author I don't want to impose my build target on consumers. It's not fair to to call transpilation in this case an implementation detail. If I were using typescript or coffeescript... then fine. But when writing javascript, I shouldn't have to transpile my code for the lowest common denominator build target.

That being said, it does seem that `jsnext:main` has already been defined by the rollup guys. Trying to change that definition at this point would probably just be confusing. Plus, there's merit to having a main field that just plain works w/o a build process.

**Comment by TheLarkInn** [comment]
There is also this proposal that a lot of people are backing. https://github.com/dherman/defense-of-dot-js/blob/master/proposal.md

**Comment by taion** [comment]
@psirenny: Do you use `stage-0` or `stage-1`? Or anything at all beyond what's approved in standards? Because if you do, you're not writing "JavaScript". You're writing code that _might become_ JavaScript at some point in the future – but might well not! Consider what happened with decorators.

@TheLarkInn: In practice that proposal works more or less like `jsnext:main` – the module build will still have to be transpiled to remove non-standard features if you use anything beyond `es2015` or `es2016`.

**Comment by umidbekkarimov** [comment]
So if `jsnext:main` made up by rollup guys, why can't we made up something for non rollup users?
Just a proposal:
`main` - CommonJS + ES5
`es:main` - latest approved ECMAScript standard
`esm:main` - ES6 Native Modules + ES5
`jsnext:main` - let rollup users choose whenever they want to use there

**Comment by donaldpipowitch** [comment]
Short question: Webpack 2 supports a `module` property in `package.json` as an entry point (see  [`resolve.mainFields`](https://github.com/webpack/webpack/blob/40aac864fd88495cd56dbec9bab522f8f34a47ea/lib/WebpackOptionsDefaulter.js#L82)). What is this about? _Is this_ for webpack what `jsnext:main` is for rollup? E.g. an entry point for ES6 native modules? And if _yes_, is it webpack-specific? So we can assume to use `require`'s there for assets and so on?

**Comment by sokra** [comment]
> Webpack 2 supports a module property in package.json as an entry point

It's the `module` from https://github.com/dherman/defense-of-dot-js/blob/master/proposal.md

**Comment by donaldpipowitch** [comment]
Thanks, @sokra.

**Comment by TehShrike** [comment]
@umidbekkarimov `jsnext:main` is not Rollup-specific.  The idea is that every bundler can implement it, and expect that the file it references will be using ES6 imports/exports.  As opposed to `main` in `package.json`, which you could expect to point to a CommonJS module.

**Comment by jdalton** [comment]
@sokra 
> It's the module from https://github.com/dherman/defense-of-dot-js/blob/master/proposal.md

Just a heads up the Node ES6 Module Interoperability proposal has been updated. See [section 5.1](https://github.com/nodejs/node-eps/blob/master/002-es6-modules.md#51-determining-if-source-is-an-es-module).

**Comment by taion** [comment]
@jdalton: Do you plan to support `module` in `lodash-es`?

@sokra: Does webpack 2 support or plan to support `modules.root`?

**Comment by jdalton** [comment]
@taion 

> Do you plan to support module in lodash-es?

I'll support whatever webpack does. *(go team webpack)*

> @sokra: Does webpack 2 support or plan to support modules.root?

I kinda hope not. The problem with poly-packages is that the transpiled path isn't a 1:1 port so slight differences in behavior can creep into things.

**Comment by taion** [comment]
Fair 'nuff.

I'll go ahead and start adding `module` to all my `package.json` files then.

**Comment by TheLarkInn** [comment]
@jdalton thank you for your help in clarifying this.

**Comment by taion** [comment]
Okay, we added `module` entry points to React Router (https://github.com/reactjs/react-router/pull/3672) and Redux (https://github.com/reactjs/redux/pull/1871).

I've also opened an issue with Rollup asking them to support `module`: https://github.com/rollup/rollup-plugin-node-resolve/issues/48.

Given that, I think this issue should be closed out – `module` seems like a great way to go, and hopefully will soon be _the_ way to go here.

**Comment by TheLarkInn** [comment]
We should probably tackle this sooner than later. This is just adding a new default and prio.

**Comment by taion** [comment]
What is there to do here? Packages are broadly moving over to `module` now. There's no need to support `jsnext:main`.

**Comment by TheLarkInn** [comment]
Correction. https://github.com/webpack/webpack/commit/378163af513332dbc0e6e50ae026a010d93e80db 

This is now fixed

**Comment by jamuhl** [comment]
Hi there. I'm maintaining i18next and just added the `module` entry point in our package.json it leads to to the dist files of es build (same as commonjs just keeping the import/export module system). The result is a lot of confusion:

https://github.com/i18next/i18next/issues/836#issuecomment-259348903

----
Ok, interesting. So after some more digging I see that:

✅ Using import i18next with plain webpack2 works
❌ Using require('i18next') with plain webpack2 doesn't work
❌ Using import i18next with babel-loader and babel via webpack2 doesn't work
❌ Using require('i18next') with babel-loader and babel via webpack2 doesn't work
----

my explanation to that:

----
so a) you can't require them as those are no commonjs compatible:

❌ Using require('i18next') with plain webpack2 doesn't work
❌ Using require('i18next') with babel-loader and babel via webpack2 doesn't work

as there is nothing imported at all...

b) the last one using import and babel-loader:

you import the file and transpile it to commonjs - webpack wants to import it - but it's no longer using the export statement but is a commonjs file - so import will fail.

❌ Using import i18next with babel-loader and babel via webpack2 doesn't work
----

Would be great if someone with more experience could enlight the situation. Thanks a lot.

**Comment by andykenward** [comment]
@jamuhl most likely to do with [`export default` ](https://github.com/i18next/i18next/blob/1d6be8832cd11382c741f48c09f75738991e2b8d/src/index.js#L3). 

I had the same issue with [`react-helmet`](https://github.com/nfl/react-helmet/issues/190). And [tried to explain it](https://github.com/nfl/react-helmet/issues/190#issuecomment-258908213) and gave up. Check out the linked posts I mentioned.

[Misunderstanding ES6 Modules, Upgrading Babel, Tears, and a Solution](https://medium.com/@kentcdodds/misunderstanding-es6-modules-upgrading-babel-tears-and-a-solution-ad2d5ab93ce0#.s7gd1btag)

[ES6 Modules](https://ponyfoo.com/articles/es6#modules)

**Comment by taion** [comment]
Turn off CommonJS module transpilation in Babel. webpack 2 deals with that for you.

Always use the `import` syntax for ES modules in webpack 2.

Work around https://github.com/webpack/webpack/issues/3168 if needed.

**Comment by halt-hammerzeit** [comment]
I would also propose an idea of an extended `module` property
```js
"module": {
  "/": "index.es6.js",
  "/submodule": "submodule/index.es6.js"
}
```

**Comment by nadavsinai** [comment]
@taion said es2015 is just another build target like UMD....
my question is how to get webpack to output that es2015 module syntax *untranpiled*  whilst keeping the rest of the transpilation.  so I can have that file that "module" field in my package.json points to

**Comment by sokra** [comment]
@nadavsinai don't bundle. Point the "module" field to a tree of files. The user of your lib will bundle it.

**Comment by halt-hammerzeit** [comment]
@nadavsinai 
> how to get webpack to output that es2015 module syntax untranpiled whilst keeping the rest of the transpilation
Use `modules: false` babel preset?

**Comment by nadavsinai** [comment]
@sokra thanks for your reply, I am aware of such option, however this isn't a satiisfactory solution for libraries -  assuming I am using some transpiled language like typescript or even just a es7 feature with babel, I am forcing my consumer to either:
 - use the same transpilation features
 - use my UMD bundle thus removing the ability to tree-shake my module

the situation is worse if I use something that is webpack specific like the require ! syntax - obviously I can not force my library users to use webpack only, what I'd llike to do - and is possible today with rollup or even tsc typescript compiler   - is to go through the whole of the compilation process (with loaders and plugins and all) but *keep the directory structure and es2015 module syntax*

BTW -but don't get me wrong I *love* webpack -  for web apps it's great - well done for that 2.2 release.
I just wanted to point out something that is missing for library makers, perhaps a new issue should be opened for tracking this?

**Comment by donaldpipowitch** [comment]
@nadavsinai I've created an issue for this problem some months ago: https://github.com/webpack/webpack/issues/2933.

**Comment by idchlife** [comment]
Guys, so does webpack support choosing "browser"/"main"/"module" field in package.json? I'm using library and having needed script in "main" field, but webpack still uses "browser" field by default somehow.

**Comment by halt-hammerzeit** [comment]
@idchlife `module` works in Webpack 2. `main` works in Webpack 1.

**Comment by halt-hammerzeit** [comment]
@idchlife Haven't heard about `browser` though.

And by the way, the code example in the docs is wrong:
https://webpack.js.org/guides/author-libraries/#final-steps
It has been discussed before: `module` should NOT point to `src`, it should instead point to `dist-es6` or something like that.

**Comment by idchlife** [comment]
@halt-hammerzeit that's the weirdest part. I didn't hear about "browser" field too. Until now. Somehow webpack uses exactly this field.

**Comment by halt-hammerzeit** [comment]
@idchlife ok https://github.com/defunctzombie/package-browser-field-spec
I would assume that `browser`, if present, prevails over the others (`main`, `module`).

> When you specify a single string for the browser field, it will replace main and be the module entry point.

**Comment by idchlife** [comment]
@halt-hammerzeit no idea how to force using "main" in webpack config?

**Comment by halt-hammerzeit** [comment]
@idchlife Well, I guess there's no such thing as `browser-module` or something like that so it's either you go with ES6 `module` or you use `browser` detection

**Comment by rosskevin** [comment]
New 2ality blog post (part 3 of 3) on [Delivering untranspiled source code via npm](http://2ality.com/2017/06/pkg-esnext.html) and how to consume it with webpack.  He proposes using `esnext` `package.json` in part 2 [Transpiling dependencies with Babel](http://2ality.com/2017/04/transpiling-dependencies-babel.html).

**Comment by bradennapier** [comment]
umm... so any package that uses "module" in their package.json is causing errors and problems as of webpack 3.0.0 rc1 ?  I have to manually fix every single module that uses it every time i install anything.... what gives?

**Comment by halt-hammerzeit** [comment]
@bradennapier  What? Are you serious? Had to rename `jsnext:main` to `module` in **all** packages for the `2.x` release and now people have to do that again? Can't they just settle on something.

**Comment by MeirionHughes** [comment]
can someone just clarify that: 
* if I create a `library` with both `dist/commonjs/index.js` and `dist/es2015/index.js`, and
* the library has in it's `package.json`: 
```
  "main": "dist/commonjs/index.js",
  "module": "dist/es2015/index.js",
```
* then, when I consume `library` in a webpack `app`, webpack will resolve to `dist/es2015/index.js` by default?

**Comment by hccampos** [comment]
@MeirionHughes it looks that way, which is unfortunate for us. Since we are using the Angular CLI which has no transpiling other than Typescript, any modules which specify a module field will be imported as es2015 modules. And a lot of times things will only really break when you run it in an older browser that doesn't support class, something which you normally don't do everyday when developing.

**Comment by scopsy** [comment]
@hccampos Hey Hugo,
I'm currently running in an issue where a library I'm using is dependent on a package that uses "module" field in its package.json file. 
 When compiling `ng build --aot --prod` I'm getting an error: 

```bash
Unexpected token: name (CalendarVietnamese) [0.a821737870a81bd01043.chunk.js:8779,6]
```

When I removed the "module" from that package compilation works fine.

Any suggestions?

**Comment by hccampos** [comment]
@scopsy the only solutions I know of at the moment are:

1. Eject the webpack config and fix it manually.
2. Fork the library, the update package.json and use the fork in your project.

We are using option 2 and just maintaining forks of the original repos for libraries that don't work with the Angular CLI

**Comment by scopsy** [comment]
@hccampos When ejecting the webpack config what needs to be changed there?

**Comment by gaearon** [comment]
>Since we are using the Angular CLI which has no transpiling other than Typescript, any modules which specify a module field will be imported as es2015 modules. And a lot of times things will only really break when you run it in an older browser that doesn't support class, something which you normally don't do everyday when developing.

I think we might be conflating two different things here. The module entry point should point to code with ES6 **modules** but not necessarily **other ES6 features**. People who want their libraries to be in ESM format can still precompile other ES6 features so that older browsers don't break.

**Comment by donaldpipowitch** [comment]
> People who want their libraries to be in ESM format can/should still precompile other ES6 features so that older browsers don't break.

I asked for this as a feature request to support this as a native webpack feature a while ago, if someone is interested in this topic: https://github.com/webpack/webpack/issues/2933.

**Comment by hccampos** [comment]
@gaearon absolutely! That is what MobX does, for example. However, more and more libraries seem to be popping up which don't transpile the rest to es5, breaking builds which run without babel/bubble. The worst part is that you only notice the breakage when testing on older browsers, which usually happens on a CI environment or manually after deploy.
