### ISSUE TITLE
Optionally disable dynamic requires

### ISSUE THREAD

**Issue by hunterloftis** [webpack/webpack#198]
This 1-line file, when built with webpack, becomes **128K:**

``` js
var moment = require('moment');
```

It seems that webpack is tripping up over the dynamic language requires and including all 60+ languages that come with moment. I'd love a mechanism of turning off this feature that can sometimes be too smart for its own good.

@jmorrel @petehunt this was the culprit behind the huge file sizes.

relevant: https://github.com/webpack/webpack/issues/59

@sokra would you accept a patch enabling something like `resolve.dynamic: false`?

**Comment by FoxxMD** [comment]
thanks @jdivock :+1:

**Comment by jhnns** [comment]
ProTips™ :+1:

**Comment by voor** [comment]
Thanks @jdivock :+1:

**Comment by Sinewyk** [comment]
I'm using the noParse options.

```
module: {
  noParse: [/moment.js/]
}
```

according to the doc http://webpack.github.io/docs/configuration.html#module-noparse

`The files are expected to have no call to require, define or similar. They are allowed to use exports and module.exports.` Which means that the file is not parsed and using the regex that includes everything, but it still gets exported. It's pretty much the perfect behavior.

One should it for the browser and require elsewhere the locale data they want, or remove the noParse server side.

**Comment by burabure** [comment]
Thanks @Sinewyk ! Saved 150kb. BTW if you need locales or addons require 'moment/locale/..'

**Comment by Sinewyk** [comment]
By the way, for those interested, this behavior (full dynamic require) that was true by default, will become false by default in webpack@2 #729.

In the long run it should be good. At least no more unexpected bundling like moment.js

**Comment by fresheneesz** [comment]
```module: {noParse: [/moment.js/]}``` worked for me Sinewyk thanks!

**Comment by fresheneesz** [comment]
Looks like `new webpack.ContextReplacementPlugin(/.*$/, /NEVER_MATCH^/)` does the trick.

**Comment by Daniel15** [comment]
Thanks @fresheneesz, using a regular expression that will never match is a nice trick to avoid dynamic requires! I'm glad to hear they'll be disabled by default in Webpack 2 (as per #729).

**Comment by maciej-gurban** [comment]
For those who stumble upon this from google like me: whether your issue is locale files not being included, or unwanted locale being included, you can update your bower.json instead of modifying your build.
```
...
"overrides": {
  "moment": {
      "main": [
        "moment.js",
        "locale/en.js",
        "locale/de.js"
      ]
    }
}
...
```

**Comment by fresheneesz** [comment]
@maciej-gurban That's super useful! I wish I'd know that!

**Comment by fresheneesz** [comment]
@maciej-gurban Is `overrides` documented somewhere? I can't find it in the configuration docs.

**Comment by jjalonso** [comment]
Im a bit confused about all the conversation, I think this is matching my problem but Is hard to understand if the regular expression is to AVOID bundling and do it in runtime or the opposite.

I have to bundle everything in my project BUT NOT the requires that request files under a specific folder.

Of course im working in NODE, then i want to use the default node require. I want webpack to ignore it.

ex: 
```
require('./myfile.js') // Bundle it!
require('./dinamics/myfile.js') // Import it in runtime
```

**Comment by jhnns** [comment]
@jjalonso With [`resolve.alias`](http://webpack.github.io/docs/configuration.html#resolve-alias) you can rewrite paths. Then you can just rewrite all paths that point to a file inside `dinamics` to an empty dummy file

**Comment by jjalonso** [comment]
@jhnns Thanks for the answer, I took another pattern but is good to know for a future, thanks you!

**Comment by L3V147H4N** [comment]
@sokra disabling expression require doesn't seem to work for me

```
{
  module: {
    // require
    unknownContextRegExp: /$^/,
    unknownContextCritical: false,

    // require(expr)
    exprContextRegExp: /$^/,
    exprContextCritical: false,

    // require("prefix" + expr + "surfix")
    wrappedContextRegExp: /$^/,
    wrappedContextCritical: false
  }
}
```

I tried this but nothing changed, webpack keeps trying to handle it

**Comment by handycode** [comment]
thanks @Sinewyk ! 

webpack:
```
module:  {
  ...
  noParse: [/moment.js/]
}
```

your code
```
import moment from "moment"
import "moment/locale/fr"
moment.locale("fr")

or 

const moment = require("moment")
require("moment/locale/fr")
moment.locale("fr")
```
it's nice

**Comment by fergardi** [comment]
How about ignoring all locales with IgnorePlugin **except** some of my choosing? For example, ignore all except EN, ES, FR. Can that be done with a regular expression?

```javascript
plugins: [
  new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/)
]
```

**Comment by odykyi** [comment]
webpack.config.js

```


module.exports = {
  //...
  module: {
    noParse: /jquery|lodash/,
  }
};
module.exports = {
  //...
  module: {
    noParse: (content) => /jquery|lodash/.test(content)
  }
};

```
https://webpack.js.org/configuration/module/#modulenoparse
