### ISSUE TITLE
webpack-dev-server programmatic access to modules

### ISSUE THREAD

**Issue by MTyson** [webpack/webpack#1980]
If I run webpack-dev-server programmatically with the API, where does it load node_modules from?

I am calling dev-server from a node process which is run with npm run node-file.js, and has all the required dependencies defined, however, the dev-server is not finding them:

ERROR in ./app/js/main.js
Module not found: Error: Cannot resolve module 'jquery' in c:\Users\Matt\Documents\Projects\my-project\client\app\js
 @ ./app/js/main.js 1:13-30

etc...

**Comment by bebraw** [comment]
Can you ask again at [webpack-dev-server](https://github.com/webpack/webpack-dev-server/issues) repo?
