### ISSUE TITLE
UglifyJsPlugin can not mangle props?

### ISSUE THREAD

**Issue by hh9527** [webpack/webpack#1983]
by default UglifyJs will mangle only local variables. and give an option to mangle props with `--mangle-props --mangle-regex "[a-z][a-zA-Z0-9]_$"`, How could I use this feature in webpack with UglifyJsPlugin?

**Comment by bebraw** [comment]
Try passing `mangle: <regex>`. Here's the [related code](https://github.com/webpack/webpack/blob/eebc5ceaf60b101e9ccc65ae5bd07967ca9e803e/lib/optimize/UglifyJsPlugin.js#L92). See also [Uglify2 API](https://github.com/mishoo/UglifyJS2).

**Comment by hh9527** [comment]
@bebraw 

Did you mean `mangle: "^_"` or `mangle: { regex: "^_" }`?

**Comment by bebraw** [comment]
@hh9527 You would have to try various options out based on the resources I linked to. I don't mangle myself.

**Comment by hh9527** [comment]
@bebraw I tried, there is no possibility to use UglifyJS2's mangle_props feature.

So this should be a new feature request for webpack.

**Comment by bebraw** [comment]
@hh9527 Ok. I marked it as an `enhancement`. PR is likely welcome.
