### ISSUE TITLE
ES6 default reexports

### ISSUE THREAD

**Issue by bendc** [webpack/webpack#1984]
I have a simple ES6 module exporting a default value:
```javascript
// content.js
export default 42;
```
My entry file renames and reexports that module:
```javascript
// entry.js
export { default as foo } from "./content";
```
That works, but webpack 2.0.6-beta won't let me use the shorter form provided by ES6 modules:
```javascript
// entry.js
export { foo } from "./content";
```

**Comment by IngwiePhoenix** [comment]
The second example clearly tries to export the "foo" property instead. That is how I always understood it? That is also why the first example works.

**Comment by bendc** [comment]
You're right, I was confused by how default reexporting worked for some reason. Thanks!
