### ISSUE TITLE
Chrome-beta SourceMaps are missing

### ISSUE THREAD

**Issue by ddaza** [webpack/webpack#1987]
I dunno if this is the right place to report this.

In chrome-beta `Version 49.0.2623.28 beta (64-bit)` the source maps are missing. They work in chromium and the stable version of Chrome.

**Comment by sokra** [comment]
Sounds like a chrome bug...

**Comment by loganfsmyth** [comment]
Also seeing this. @ddaza did you end up reporting a Chromium bug for this?

**Comment by loganfsmyth** [comment]
It looks like Chrome has removed support for the `//@` style of sourcemap URLs. I know `//#` is the default now, we'd just still on an old version of Webpack. Explicitly doing `devtool: '#eval-source-map'` works fine.

**Comment by loganfsmyth** [comment]
Looks like https://github.com/webpack/webpack/pull/2075 was the core issue here, since it was still using the old deprecated format by default in some cases.

**Comment by ddaza** [comment]
Thanks for the response. Also, I can confirm `devtool: '#eval-source-map'` fixed the source maps for me on Chrome-Beta, the downside is that it breaks the source-maps everywhere else.
