### ISSUE TITLE
[Question][Plugin Development] Writing a plugin that combines async loadable chunks

### ISSUE THREAD

**Issue by asciidisco** [webpack/webpack#1988]
Hey there,

I´m trying to create a webpack plugin, but I´m totally stuck :(
I´ve created a gist: https://gist.github.com/asciidisco/b9cb189d1f969e0f3a19#file-the_problem-md
that explains what I´m trying to do (Thought it might be a bit too verbose, to put this all in this issue)

If someone could help me out & push me in the right direction, that would be wonderful.
Any help is appreciated (even RTFM -> if it includes a link that helps ;) )

**Comment by sokra** [comment]
You can take a look at the other chunk optimization plugins:

* http://webpack.github.io/docs/list-of-plugins.html#limitchunkcountplugin
* http://webpack.github.io/docs/list-of-plugins.html#minchunksizeplugin
* http://webpack.github.io/docs/list-of-plugins.html#aggressivemergingplugin

They also merge chunks.

Read the source (it's not so long). There is a function `integrate` which merges one chunk into another.

**Comment by asciidisco** [comment]
@sokra 

Thank you very much for the quick answer :)
The hint on the `integrate` function was exactly the thing I was missing.
