### ISSUE TITLE
Backport CLI fix for compilation errors

### ISSUE THREAD

**Issue by skovhus** [webpack/webpack#1998]
I'm experiencing UglifyJS failing but webpack version 1.12.13 CLI still succeeded with exit code 0. 

So I propose backporting the CLI change introduced in webpack 2 to version 1. See  https://github.com/webpack/webpack/blob/master/bin/webpack.js#L258

Let me know if I should prepare this in a pull request. : )

```
if (!options.watch && stats.hasErrors()) {
    process.on("exit", function() {
        process.exit(2); // eslint-disable-line
    });
}
```
https://github.com/webpack/webpack/blob/webpack-1/bin/webpack.js#L175

**Comment by sokra** [comment]
This is a breaking change. We cannot backport it...
