### ISSUE TITLE
Cannot resolve module installed in a childmodule or submodule

### ISSUE THREAD

**Issue by c0debreaker** [webpack/webpack#1999]
A. Main project's package.json contains app-services subModule listed in dependencies
```
dependencies: { "app-services": "^1.0.0" ..... }
```

B. The sub module "app-services" has a BackboneJS dependency, etc
```
dependencies: { "backbone": "^1.2.3",,,,, }
```

C. BackboneJS gets installed in app-services successfully during the build of Main project 

D. In Main app's src/index.js, it has the code below on the first line
```
import Backbone from 'backbone';
```  

E. However during build, webpack is complaining that it cannot resolve the module
```
ERROR in ./src/index.js
Module not found: Error: Cannot resolve module 'backbone' in /home/devuser/projects/Rekon/src
```

F. We don't want to add/install backbone in Parent since it's already being installed in app-services submodule. We want to re-use it.

**Comment by davidpelayo** [comment]
Then you need to use [npm dedupe](https://docs.npmjs.com/cli/dedupe) to avoid redundancy.

**Comment by c0debreaker** [comment]
That means, our dedupe is not working. I first heard this dedupe too yesterday from my teammate. He said using dedupe caused more issues. Does everyone in the team has to run npm dedupe?

**Comment by c0debreaker** [comment]
I missed your instructions above because I just woke up. :) So how is that alias created? Can you please show an example?

**Comment by c0debreaker** [comment]
I got it working. All I did was to upgrade node to 5.5.0 and npm to 3.7.1. It's not a webpack issue. It's an npm binary issue specifically! dedupe is working perfectly on this version :)
