### ISSUE TITLE
Align module-object to node's module-object

### ISSUE THREAD

**Issue by jhnns** [webpack/webpack#20]
I think it would be nice to align the module-object as much as possible to [node's module](http://nodejs.org/docs/latest/api/modules.html#modules_the_module_object) object although it's not too important for many modules (because most of the time you don't really need the module-object).

`module.id` could than be the module-id assigned by webpack.

**Comment by dominictarr** [comment]
`if(module.parent)` is often used to check wether you are in a main file in a node program. if it was truthy, that would work.
for example:
https://stackoverflow.com/questions/4981891/node-js-equivalent-of-pythons-if-name-main
and
https://stackoverflow.com/questions/6398196/node-js-detect-if-called-through-require-or-directly-by-command-line

There should be a way to do that - I don't think it matters wether it is really the parent module object, but this is a common usecase
