### ISSUE TITLE
Webpack fails when using export default

### ISSUE THREAD

**Issue by hamiltondanielb** [webpack/webpack#2001]
I am currently trying to update my webpack config file to use ES6. When i change

`module.exports = {...}` to `export default {...}` but when i do it fails to build with an output of Output filename not configured, which seems unrelated, but is likely caused because webpack doesn't know how to handle the `export default`

I have renamed my config file to webpack.config.babel.js and updated my .babelrc file to this

```
{
  "presets": ["react", "es2015", "stage-0"],
}
```

What am I missing?

**Comment by bebraw** [comment]
Did you remember to install [babel-register](https://www.npmjs.com/package/babel-register) to your project?

**Comment by hamiltondanielb** [comment]
Yes, babel-register is installed

**Comment by bebraw** [comment]
Hard to say anything concrete without having a project to run. `export default` works for me.

**Comment by sokra** [comment]
Which version are you using? ES6 configuration only works for webpack@2

**Comment by hamiltondanielb** [comment]
I updated to react v0.14 and downgraded to babel babel-core 5.x instead of 6.x and was able to get this to work.

**Comment by andreypopp** [comment]
`module.exports = {...}` and `export default {...}` are not equivalent in Babel 6. `export default ...` is roughly equal to `module.exports.default = ...`.
