### ISSUE TITLE
Explicit vendor chunk doesn't work with ProvidePlugin

### ISSUE THREAD

**Issue by sharkrice** [webpack/webpack#2008]
I have the following config:
```
module.exports = {
  entry:  {
    index: './src/index.js',
    page: './src/page.js',
    vendor: ['a', 'b', 'jquery']
  },
  output: {
    path: path.resolve(__dirname, '../dist/'),
    publicPath: '/',
    filename: '[name].js'
  },
  plugins: [
    new webpack.ProvidePlugin({
      '$': 'jquery'
    }),
    new webpack.optimize.CommonsChunkPlugin({
      name: 'vendor',
      filename: 'vendor.bundle.js',
      chunks: ['a', 'b', 'jquery']
    }),
    new webpack.optimize.CommonsChunkPlugin({
      name: 'commons',
      filename: 'commons.bundle.js',
      minChunks: 2
    }) 
  ]
}
```
If I use jquery as $ in index.js or other entry, jquery will not bundle into vendor chunk but into commons chunk.
If I doesn't use ProvidePlugin to expose jquery, jquery will bundle into vendor chunk, as well as if I doesn't use $ which is set to exports of jquery in index.js or other entry.
If I ues expose-loader to expose jquery as $ and I use $ in index.js or other entry , there is no problem.

**Comment by sokra** [comment]
`chunks: ['a', 'b', 'jquery']` chunks names are expected here, not module names
