### ISSUE TITLE
Webpack watch mode with babel-loader works only when new line is added

### ISSUE THREAD

**Issue by kiranps** [webpack/webpack#2009]
while using babel-loader with webpack watch mode changes made in a single line are not detected. if add another line watch mode works. webpack-dev-server do not have this issue it detects changes made in single line

code
[https://github.com/kiranps/ES6-Starter.git](https://github.com/kiranps/ES6-Starter.git)

**Comment by sokra** [comment]
Propably not an webpack issue. webpack doesn't care about the file content before babel. Watching only cares about timestamps. Maybe babel is caching stuff?

**Comment by BlueVajra** [comment]
I am having the same issue, and found this open webpack bug and wonder if it is related: https://github.com/webpack/webpack/issues/675

**Comment by kiranps** [comment]
@sokra webpack-dev-server do not have this problem

**Comment by rickyk586** [comment]
The temporary solution found in the webpack bug #675 worked for me: https://github.com/webpack/webpack/issues/675#issuecomment-224991459
