### ISSUE TITLE
I have a question __dirname setting of node config

### ISSUE THREAD

**Issue by blackpost38** [webpack/webpack#2010]
Hi there.

I'm using express with webpack.
I found __dirname needs set for node and i set like below

```
node: {
  __dirname: false
}
```

Docs comment `__dirname: true` is real __dirname, but Above works. Not `true` (true output '')
Is Docs correct, or not ?

thanks about greate tool!

**Comment by sokra** [comment]
`__dirname: false` disables webpack processing of `__dirname`. If you run the bundle in node.js it falls back to the __dirname of node.js (which makes sense for target: node).
`__dirname: true` let webpack replace `__dirname` with the path relative to you `context`. Makes sense for target: web if you need the path.

**Comment by krzkaczor** [comment]
I just have the same problem. I think that documentation is very unclear about what it will do:
```
__dirname: true (real dirname), "mock" ("/") or false
```

**Comment by blackpost38** [comment]
Great answer thanks!
I wish to apply that comment to docs :)

**Comment by jmlane** [comment]
Yeah, this is confusing. The documentation reads as if the boolean values should have the opposite effect in the resulting bundle.

**Comment by tejohnso** [comment]
> __dirname: false disables webpack processing of __dirname. If you run the bundle in node.js it falls back to the __dirname of node.js (**which makes sense for target: node**).

@sokra given what you said above re what makes sense, why is webpack unexpectedly breaking node's behaviour? Shouldn't the node options all be *false* automatically if target is *node*? The mangling of __dirname is counter intuitive and without warning. And in most cases, the output built for node will operate incorrectly rather than failing.
