### ISSUE TITLE
-w flag doesn't work (Windows 10)

### ISSUE THREAD

**Issue by gpresland** [webpack/webpack#2013]
Using version 1.12.13.
Running with webpack -w. Older version works fine on another machine. Latest version the -w flag is not watching for file changes. It does however compile manually.

**Comment by sokra** [comment]
Until which older version does it work? Could you bisect the versions on which it doesn't work anymore?

**Comment by gpresland** [comment]
Version 1.12.12 is working on my Windows 10 work PC. I installed 1.12.13 on my personal Windows 10 PC and the -w option isn't working.

**Comment by sokra** [comment]
Are you watching a local disk or a network share?

**Comment by gpresland** [comment]
Local disc. I've tried both my Window's disc (C:) and my data drive (E:).

**Comment by ciwchris** [comment]
I'm experiencing the same issue on Windows 7. Using webpack-dev-server also does not recompile. I can use nodemon to watch for file changes and have it rerun webpack. I tried earlier versions of webpack, 1.12.12 and 1.12.0. They also did not function.

**Comment by stevens32** [comment]
Watch broken for me as well on Windows 10, I'm using 1.12.14.

**Comment by Haubach** [comment]
Any updates on this bug? This bug is basically preventing my entire team from committing to using webpack on our upcomming projects.

**Comment by Haubach** [comment]
Are any of you guys using IDE's with ["safe write"](https://webpack.github.io/docs/webpack-dev-server.html#working-with-editors-ides-supporting-safe-write)? we were having issues with webpack not playing nice with this option enabled on windows machines.

**Comment by ciwchris** [comment]
I'm now on 1.13.1 and the watch seems to be functioning, so it appears this is no longer an issue for me.

**Comment by gpresland** [comment]
Upgraded to webpack 1.13.2 and issue is resolved.
