### ISSUE TITLE
Possible regression on webpack-2

### ISSUE THREAD

**Issue by holymonson** [webpack/webpack#2014]
Hi, I was upgrading to webpack-2 and found errors, while webpack-1 is always good. It should not be call _regression_ crossing major version, but I cannot found what's the breaking change between v1 and v2.

Output compare showed below:
```bash
[monson@Monson-MBP eleapp]$ webpack
Hash: 7473eb734d38d36b7466
Version: webpack 1.12.13
Time: 5246ms
  Asset     Size  Chunks             Chunk Names
main.js  4.72 MB       0  [emitted]  main
   [0] multi main 40 bytes {0} [built]
    + 397 hidden modules
[monson@Monson-MBP eleapp]$ webpack
Hash: c9a4b2a41ef5678c7117
Version: webpack 2.0.7-beta
Time: 6209ms
  Asset     Size  Chunks             Chunk Names
main.js  4.73 MB       0  [emitted]  main
 [397] multi main 40 bytes {0} [built]
    + 397 hidden modules

ERROR in ./~/blueimp-load-image/js/load-image-exif.js
Module not found: Error: Can't resolve 'load-image' in '/Users/monson/project/eleapp/node_modules/blueimp-load-image/js'
 @ ./~/blueimp-load-image/js/load-image-exif.js 18:8-58
```

The module is imported in my code by
```js
import loadImage from 'blueimp-load-image/js/load-image'
import 'blueimp-load-image/js/load-image-meta'
```
And in `load-image-meta.js`:
```js
(function (factory) {
    'use strict';
    if (typeof define === 'function' && define.amd) {
        // Register as an anonymous AMD module:
        define(['load-image'], factory);
    } else if (typeof module === 'object' && module.exports) {
        factory(require('./load-image'));
    } else {
        // Browser globals:
        factory(window.loadImage);
    }
}(function (loadImage) {
```
It seems like the ` define(['load-image']` fails to resolve, but `load-image.js` is definitely exists here.

Additional Info: The config sets `resolve.root = ['/Users/monson/project/eleapp/node_modules/blueimp-load-image/js']`, without it webpack-1 will fail with similar error too.

**Comment by sokra** [comment]
https://gist.github.com/sokra/27b24881210b56bbaff7

`resolve.root` doesn't exists anymore

**Comment by holymonson** [comment]
Thanks @sokra , the root reason is that `.` is not in default paths.
Patching the lib by `define(['load-image'] => define(['./load-image']` fix it.
