### ISSUE TITLE
Validate stats.toJSON() option types

### ISSUE THREAD

**Issue by aldendaniels** [webpack/webpack#2018]
The `context` is a string option which is defaulted to the current working directory. The other string options say `(string)` but this one doesn't. If you supply a boolean by mistake, you get a strange error message. 

Separately (separate issue if interest) it would be nice to validate the option types.

**Comment by sokra** [comment]
yep. Feel free to edit the docs. there is an edit button in the top right corner.

**Comment by aldendaniels** [comment]
Ah, missed the edit button. Thanks!

**Comment by bebraw** [comment]
If still relevant, please re-open. webpack 2 has validation etc. now.
