### ISSUE TITLE
RFE: Invalidation event

### ISSUE THREAD

**Issue by unilynx** [webpack/webpack#2021]
I'd like to request an enhancement to the watch api - the ability to receive a callback when the watcher detects a change and will (eventually) recompile a bundle. This would allow us to signal some sort of 'out-of-date' to developers until recompilation completes.

I've currently hooked the low level watch API (on 1.12.9) the following way:

```

bundleInvalidated(fswatcher) { ..... }

var watcher = compiler.watch({}, (err, stats) =>
  {
    watcher.watch = function()
    {
      watcher.__proto__.watch.apply(this, arguments)
      let fswatcher = watcher.compiler.watchFileSystem.watcher;
      fswatcher.once("change", () => bundleInvalidated(fswatcher));
    }
```

which works, but it'd be nice not to have to mess with the internals.

**Comment by sokra** [comment]
``` js
compiler.plugin("invalid", function() {

});
```

**Comment by okonet** [comment]
@sokra is there a way to determine what files are caused the invalidation event? 

Also, related: I'm trying to prevent a rebuild for a sub-tree when compiling for both server and client. What would be the correct way of doing this? I was hoping of catching files that caused the rebuild and exclude them from Watching instance somehow. But probably there is an easier way to do that. Thanks!
