### ISSUE TITLE
Build file cannot be imported

### ISSUE THREAD

**Issue by Tjorriemorrie** [webpack/webpack#2024]
I have a component:

    import React from 'react';
    import _ from 'lodash';
    
    
    class NotWorking extends React.Component {
        render() {
            console.info('notworking');
            return <div>why do they make this so hard?</div>;
        }
    }
    
    module.exports = {
        NotWorking
    };

Build it with:

    var path = require('path');
    
    module.exports = {
        entry: path.resolve(__dirname, 'src/NotWorking.jsx'),
        output: {
            path: path.resolve(__dirname, 'build'),
            filename: 'notworking.js'
        },
        module: {
            loaders: [
                {
                    test: /\.jsx?$/,
                    exclude: /(node_modules|bower_components)/,
                    loaders: ['babel?cacheDirectory,presets[]=react,presets[]=es2015']
                }
            ]
        }
    };

The idea is to have this as an npm module; so I want to include the build in another project (hopefully via node_modules then, for now I just require it as follows):

    import React from 'react';
    import ReactDOM from 'react-dom';
    import NotWorking from './../build/notworking.js';
    
    
    class MustWork extends React.Component {
    
        render() {
            console.info('mustwork');
            return <div>
                must work
                <NotWorking />
            </div>;
        }
    }
    
    ReactDOM.render(<MustWork />, document.getElementById('kitchen_sink'));

I build it with an exact same webpack config as above, except the filename changes.

I get this error when using it:

> Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `MustWork`.

Which means the notworking file is not building correctly? 
The imported module is just an empty object `{ }` 
[SO link](http://stackoverflow.com/questions/35287983/webpack-cannot-create-working-module/35288275?noredirect=1#comment58287198_35288275)

**Comment by sokra** [comment]
You never export it. Use the `output.library` option. And better use `export default` elsewise you can't import it with `import NotWorking form`

**Comment by Tjorriemorrie** [comment]
@sokra, thanks for the help. In my 2 weeks of agony and two SO questions, you seem to be the ONLY one knowing what's going on here.

So I've changed the component (that is how it originally was):
> export default class NotWorking extends React.Component {

And the config:
```
    output: {
        path: path.resolve(__dirname, 'build'),
        filename: 'notworking.js',
        library: 'NotWorking'
    },
```

But I still get:
>  Object {}

**Comment by Tjorriemorrie** [comment]
It works with adding:
`        libraryTarget: 'umd'`
