### ISSUE TITLE
References to require get turned into a call

### ISSUE THREAD

**Issue by technomage** [webpack/webpack#2025]
Reference to require as in the following
`var temp = require;`
get turned into a call to require('.') which is not at all what was expected.  In a Node environment trying to get require function into another variable to allow requires outside webpack.

**Comment by sokra** [comment]
http://webpack.github.io/docs/context.html
http://webpack.github.io/docs/context.html#critical-dependencies

**Comment by technomage** [comment]
It looks like it is probably an interaction with babel.
