### ISSUE TITLE
When targeting node allow require.extensions ?

### ISSUE THREAD

**Issue by lightsofapollo** [webpack/webpack#2026]
To give a specific example packing up `babel-register` results in roughly half the load time ... This works totally fine /w webpack except for [this](https://github.com/webpack/webpack/blame/master/lib/NodeStuffPlugin.js#L77) .. I suspect there is some reason for this warning but setting it to `ignore` would be very useful!

**Comment by sokra** [comment]
Instead of `babel-register` use the `babel-loader`. `require.extensions` will not work.

`babel-register` should not be in the code you want to bundle. It should be used only on application level.
