### ISSUE TITLE
Webpack 2 documentation

### ISSUE THREAD

**Issue by Chrisui** [webpack/webpack#2028]
I'm looking to write some pretty extensive plugins for webpack but am ever so aware that a v2 is set to be released at some point in the near future. If possible I would like to write my plugins against the future api rather than the existing one (to prevent needless refactor) but came up short of finding any documented changes (without looking through all pull requests).

Is there anywhere I can reference documentation for both "Plugin development" and "General usage" in v2?

Ps. Thanks for all the awesome work with webpack! Been a pleasure to use.

**Comment by sokra** [comment]
There won't be many changes in the plugin API. You should be able to write the plugin against v1 and it will work with v2 (or only require minimal changes)...

**Comment by Chrisui** [comment]
Awesome!

Are there any WIP (or any major) changes for general usage?

**Comment by sokra** [comment]
https://gist.github.com/sokra/27b24881210b56bbaff7

**Comment by Chrisui** [comment]
:+1: Appreciate it :)

**Comment by patrick91** [comment]
The new docs should be here: [https://webpack.js.org](https://webpack.js.org)

**Comment by DanielRamosAcosta** [comment]
Is it down the docs site?

![image](https://cloud.githubusercontent.com/assets/11427028/22401375/703b2700-e5c8-11e6-8047-9dbd8e68e83f.png)

**Comment by TheLarkInn** [comment]
Workin on it.
