### ISSUE TITLE
Split modules bundled via context into separate chunks

### ISSUE THREAD

**Issue by chrisui** [webpack/webpack#2029]
Considering I have the following context requirement in my application:

```
// entry.js
const reqFixtures = require.context('./components', true, /^\.\/.*\-fixture\.js$/);
```

Is there anyway, with existing plugins/features, I could tell webpack to split the output into a chunk per file found within the above context?

If my tree looks like:

```
- components/
  - button/
    - button-fixture.js
  - input/
    - input-fixture.js

```

in the case above I'd end up with chunks:

```
- button-fixture.js
- input-fixture.js
- entry.js
```

My use case is having a large test/playground application which can reference tens of fixtures with hundreds of components. I don't want to load all that if we only want to look at a single fixture for a single component, I'd much rather lazy load on demand.

---

If there are no existing mechanisms or plugins to achieve this it'd be great to have some pointers on how to approach a plugin to do this? I was thinking we could look at the emitted modules and if the module path matches against the same expression as the context used then we could pull that module out into a new chunk. That bit seems like it might be relatively trivial but then how to handle pulling dependencies of those matching modules into the chunks? Or would this be handled by `DedupePlugin`?

Anyway, thanks in advance and sorry if this has been discussed before!

**Comment by sokra** [comment]
for webpack 1 you can use the `bundle-loader` or the `promise-loader`: `require.context("bundle!./components", ...)`

for webpack 2 it's the default behavior for `System.import("./components/" + ...)`

**Comment by Chrisui** [comment]
Didn't even think of using loaders in context! I'll give this a try later.

Thanks!
