### ISSUE TITLE
Compiled bundle ignores "module.exports" values and exports empty object

### ISSUE THREAD

**Issue by wzup** [webpack/webpack#2030]
Why does bundle ignore `module.exports` and exports only an empty object?

Here is an example. In real code there are React components instead of plain functions. To simplify things I use plain functions. I use Webpack to compile React components and make two bundles - one for client, one for server. The server bundle has `module.exports`. The browser bundle has `ReactDOM.render`.

`ColorsComponents.js`:

```
// const React = require('react');

// this is actually React.createClass with jsx syntax
const Green = function () {
    console.log('[Green]:');
}

// this is actually React.createClass with jsx syntax
const Red = function () {
    console.log('[Red]:');
}

module.exports = {
    Green: Green,
    Red: Red
};
```

`browser.js` entry chunk. This one is ok, this works as expected. I just include ready bundle on the page `<script src="/js/browser.js" type="text/javascript" charset="utf-8"></script>` and it works ok:

```
// const ReactDOM = require('react-dom');

const Red = require('./ColorComponents').Red;
const Green = require('./ColorComponents').Green;

ReactDOM.render(
    <Red />, document.getElementById('red')
)
ReactDOM.render(
    <Green />, document.getElementById('green')
)
```

`server.js` entry chunk. But the bundle from this entry chunk doesn't work. It doesn't export values:

```
const Red = require('./ColorComponents').Red;
const Green = require('./ColorComponents').Green;

module.exports = {
    Green: Green,
    Red: Red
};
```

And here is my server file (`route.js`) that requires `server.js` bundle and expects to import compiled React components from it:

```
const components = require('./server');
const Red = components.Red;
const Green = components.Green;

// But "components" is just an empty object:
console.log("['components']:", components); // [components]: {}
```

And `webpack.config.js`:

```
const path = require('path');

module.exports.default = {
    context: process.cwd(),
    entry: {
        server: ['.react/dev/server.js'],
        browser: '.react/dev/browser.js'
    },
    debug: 1,
    output: {
        filename: '[name].js',
        path: path.join(__dirname, 'react/stage'),
        publicPath: '/assets/js/',
    },
    module: {
        loaders: [{
            test: /\.js$/,
            loader: 'babel',
            exclude: /(node_modules)/,
            query: {
                presets: ["es2015", "stage-0", "react"]
            },
        }],
    },
}
```

Why does `server.js` bundle export empty object and doesn't export specified values? What Webpacks' technical restriction is that? What part of documentation explains it?

**Comment by wzup** [comment]
So far I found this http://webpack.github.io/docs/code-splitting.html#chunk-loading
> Depending on the configuration option `target` a runtime logic for chunk loading is added to the bundle.

And `target` option:

> target
> * "web" Compile for usage in a browser-like environment (default)
> * "webworker" Compile as WebWorker
> * "node" Compile for usage in a node.js-like environment (use require to load chunks)

So if I understand it right, Webpack by default compiles everything for *browser-like environment* only. And consequently, my approach to compile one chunk for browser env and another one for Node env both in one operation is wrong. Ok. It is rather clarified. But why compiled bundle doesn't export values?

**Comment by sokra** [comment]
> But why compiled bundle doesn't export values?

see `output.library` and `output.libraryTarget` options.

**Comment by benduran** [comment]
@wzup did you manage to correct your issue? I just switched my whole project over to webpack this morning and I'm running into the same issue. It's incredibly frustrating that my module exports fine in one instance, and in another instance it is empty.

**Comment by andresilveira** [comment]
I'm facing the same problem. I've specified both `library` and `libraryTarget`, but no success.
```javascript
// /src/library.js
module.exports = {
  foo: function() {
    console.log('bar');
  }
};

// /webpack.config.js
output: {
      filename: 'library.js',
      path: './dist',
      library: 'library',
      libraryTarget: 'umd'
    }

// in another node project
var lib = require('library'); // returns empty object
```
I've also tried other values for `libraryTarget`. :/

**Comment by MeirionHughes** [comment]
I have this too; anyone fix it?

**Comment by aitoroses** [comment]
I experienced the same problem before and the problem lies in the `entry` that you specified when targeting UMD

```
entry: {
        server: ['.react/dev/server.js'],
        browser: '.react/dev/browser.js'
 }
```

Webpack can't figure out which one should be name as library. It would not make sense to have two entries that are named with the same library name. So it requires being a single file.

I hope that helps 😄

**Comment by warrenronsiek** [comment]
Same problem here. 

```
const paths = {
    src: path.join(__dirname, 'src'),
    dist: path.join(__dirname, 'dist'),
    nodeModules: path.join(__dirname, 'node_modules')
};

const build = {
    devtool: 'source-map',
    entry: paths.src,
    resolve: {
        extensions: ['', '.js']
    },
    output: {
        path: paths.dist,
        publicPath: '/',
        filename: 'matrix.js',
        library: "matrix",
        libraryTarget: "var"
    },
    module: {
        loaders: [
            {
                test: /\.js$/,
                loader: 'babel',
                exclude: paths.nodeModules
            }
        ]
    }
}
```

Even with library and library target specified, require still results in an empty object.

**Comment by imaasz** [comment]
Did anyone figure this out? I'm facing the same issue, setting the libraryTarget doesn't solve it.

**Comment by kz12** [comment]
If you're using es2015 syntax, then you should set libraryTarget = 'commonjs-module'. 

See [Webpack output property](https://webpack.js.org/configuration/output/)

**Comment by jonathanconway** [comment]
@kz12 saved my life.

**Comment by mbraint** [comment]
I have same issues, 
```
// foo is {empty object}
const foo = require('xxx')
```
```
//returns correct value of module
const foo = require('xxx').default
```
This is is not **Webpack** problem, this is **Babel 6**
For resolve this i use [**babel-plugin-add-module-exports**](https://github.com/59naga/babel-plugin-add-module-exports)

**Comment by sokra** [comment]
There is an option `output.libraryExport` for this now. I don't recommend using the babel plugin.

**Comment by mnpenner** [comment]
To elaborate, we should just [`libraryExport`](https://webpack.js.org/configuration/output/#output-libraryexport) to `"default"`

**Comment by atav32** [comment]
Haven't had a chance to look into `output.libraryExport`, but I got this setup to work.

*./src/library.js*
```javascript
export default function example() { console.log('example'); }
```

*webpack.config.js*
```javascript
module.exports = [{
  entry: './src/library.js',
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'index.js',
    library: 'example',
    libraryTarget: 'umd',
    umdNamedDefine: true
  },
  ...
```

*package.json*
```json
{
  "name": "example",
  "main": "dist/index.js"
}
```

- - - - -

*client.js*
```javascript
var example = require('example').default;
example();
```

**Comment by isbdnt** [comment]
babel-loader causes this weird problem.
ignoring the output directory  solves it;
![image](https://user-images.githubusercontent.com/26591233/35793979-be82ad70-0a8e-11e8-8826-aceadf48c69d.png)

**Comment by kevupton** [comment]
@MeirionHughes answer works.
```
output: {
    library: '',
    libraryTarget: 'commonjs'
  }
```
The documentation definitely needs to be more clear.

Cost me 2 hrs at the least trying to figure out something a simple as this.
Or at least why is this not a default thing ?

**Comment by cameronsutter** [comment]
Looks like webpack 4 (possibly sooner?) recommends using:
`libraryTarget: 'commonjs2'`

The other thing that I needed to do is:
`libraryExport: 'default'`

This link helped me the most: [webpack.js.org/configuration/output/](https://webpack.js.org/configuration/output/)

**Comment by gtournie** [comment]
In my case, I had 2 entries: `['./src/index.scss', './src/index.js']`
Js MUST be second, otherwise you'll get an empty object.

**Comment by tylerrrkd** [comment]
@mbraint Hi, friend.

I am maintaining an old project, and I met the same situation(mix `export` and `import`). I choose the same plugin you did, but it did not work well with Babel 7. Do you know how to fix it? Thanks a lot.

> babel-plugin-add-module-exports

**Comment by fredvollmer** [comment]
@gtournie wow, that is exactly what I needed to do in order to get exports working. Thank you very much for tracking this down. Shouldn't this be mentioned in the docs somewhere?

**Comment by msalsas** [comment]
This worked for me (Node and browser):

    output: {
        filename: 'index.js',
        path: path.resolve(__dirname, 'js'),
        libraryTarget: "umd",
        globalObject: "this"
    },

**Comment by DanielC-N** [comment]
**For those who upgraded from `Webpack 4` to `Webpack 5`**  
I'll leave that here in case this helps someone somewhere, one day : https://github.com/webpack/webpack/issues/11800

If you have : 
```js
output: {
    .
    .
    .
    library: 'index',
    libraryTarget: 'commonjs2'
}
```

Webpack 5 will make the exports look like this `module.exports.index=r` ... Because .. some reasons.

You want to get rid of `library` , after this, everything will work fine.
