### ISSUE TITLE
How to exclude node_modules but one

### ISSUE THREAD

**Issue by bORm** [webpack/webpack#2031]
Subj,
as example
I create some module in another folder ( /projects/MY_MODULE )
MY_MODULE not compiled, source code
then run npm link
after go to my project and run npm link MY_MODULE
Compile my project and have error two copies React

i`am try
```
{
        test: /\.js$/,
        exclude: [/node_modules/],
        include: [/node_modules\/MY_MODULE/]
      },
```

**Comment by sokra** [comment]
{
        test: /\.js$/,
        include: [/node_modules\/MY_MODULE/]
      },

**Comment by bORm** [comment]
@sokra 
```
./src/client.js
[0] Module parse failed: /Volumes/www/abrahamessays.com/src/client.js Line 4: Unexpected token
[0] You may need an appropriate loader to handle this file type.
[0] | * THIS IS THE ENTRY POINT FOR THE CLIENT, JUST LIKE server.js IS THE ENTRY POINT FOR THE SERVER.
[0] | */
[0] | import 'babel/polyfill';
[0] | import React from 'react';
[0] | import ReactDOM from 'react-dom';
[0]  @ multi main
[0] webpack built 12ed16c561926b4fa5a1 in 204ms
```
and not compiled(

**Comment by sokra** [comment]
Include you src directory and the other directory. Don't use exclude.

``` js
  include: [
    path.resolve(__dirname, "src"),
    path.resolve(__dirname, "node_modules/ui")
  ]
```

**Comment by bORm** [comment]
@sokra 
if i don't use exclude, i will get an error parsing jquery and other libraries over 200Kb size

**Comment by ghigt** [comment]
I have the same issue, I can't include all node_modules but just the one written in es6 to babelify it.

**Comment by ghigt** [comment]
I don't know if it could be the fix but in [lib/LoadersList.js](https://github.com/webpack/webpack/blob/b0fffd50d35dd0eef734d189928c1ac4c5c9fb97/lib/LoadersList.js#L99):
```js
LoadersList.prototype.matchObject = function matchObject(str, obj) {
	if(obj.test && !this.matchPart(str, obj.test)) return false;
	if(obj.include && !this.matchPart(str, obj.include)) return false;
	if(obj.exclude && this.matchPart(str, obj.exclude)) return false;
	return true;
};
```

Could it be better to have something like:
```diff
- if(obj.include && !this.matchPart(str, obj.include)) return false;
+ if(obj.include && this.matchPart(str, obj.include)) return true;
```

**Comment by ghigt** [comment]
@bORm: a solution:
```js
{
  test: /\.js$/,
  exclude: /node_modules\/(?!(MY-MODULE|ANOTHER-ONE)\/).*/,
},
```

**Comment by bORm** [comment]
@ghigt, oh thanks, but i just use webpack-node-externals
`
import nodeExternals from 'webpack-node-externals'
...
externals: [nodeExternals({
		whitelist: ['MY-MODULE','ANOTHER-ONE']
	})],
...
`

**Comment by megatolya** [comment]
dont know why but @sokra solution raised new exception
exclude inside exclude is my solution 😅:
```js
exclude: /node_modules(?!\/my-es6-raw-module)/
```

**Comment by nowells** [comment]
I didn't see this option listed here, so I thought I might as well drop in my findings. I found it useful to leverage the ability to specify an `include` or `exclude` as a function (I prefer the explicit `include` over `exclude` personally).

```js
{
  test: /\.js$/,
  exclude: function(modulePath) {
    return /node_modules/.test(modulePath) &&
        !/node_modules\/MY_MODULE/.test(modulePath);
  }
}
```

**Comment by KhramtsovMaksim** [comment]
`exclude: {
                        test   : resolve(__dirname, "node_modules"),
                        exclude: resolve(__dirname, "node_modules/unfetch")
                    },`

**Comment by KhramtsovMaksim** [comment]
example for webpack 2 [documentation](https://webpack.js.org/configuration/module/#rule-exclude)
```
exclude: {
    test   : resolve(__dirname, "node_modules"),
    exclude: resolve(__dirname, "node_modules/unfetch") // or your module - also can be an array (read doc)
}
```

**Comment by lxjwlt** [comment]
In Windows， `modulePath` would be `C:\path\to\project-name\node_modules\MY_MODULE`，solution may be : 

```javascript
exclude: /node_modules(?!(\/|\\)MY_MODULE)/
```

**Comment by mcelotti** [comment]
Linux uses "/" while Windows uses "\\" in `modulePath` so I ended up using the `exclude: function (modulePath) ` to handle both.

**Comment by flybayer** [comment]
I finally got a node_modules package to compile with `babel-loader` after hours of struggling.

The problem was that the package had it's own `.babelrc` published which was overriding my babel config (which is in my package.json).
```
node_modules/
  vue-match-media/
    .babelrc   <--- babel-loader was using this which didn't have my required config
    dist/
      index.js  <--- file I needed compiled
package.json  <--- contains the babel config I need everything to use
build/
  webpack.base.config.js <-- my weback config
src/
```

My solution is to set `babelrc: false` in the loader config and specify the babel config in the loader. However, I read this config from my package.json, so it's not duplicated.
```js
var readPackageJson = require('read-pkg')
var babelOptions = readPackageJson.sync().babel
babelOptions.babelrc = false

// ... rest of config
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [path.join(__dirname, '..', 'node_modules/vue-match-media')],
        options: babelOptions,
      },

```

**Comment by jh3141** [comment]
Building on @nowells suggestion above and incorporating the comment from @lxjwlt about Windows paths being different, I decided to make a function to build the necessary regexps automatically with the correct path separator:

```
function excludeNodeModulesExcept (modules)
{
    var pathSep = path.sep;
    if (pathSep == '\\') // must be quoted for use in a regexp:
        pathSep = '\\\\';
    var moduleRegExps = modules.map (function (modName) { return new RegExp("node_modules" + pathSep + modules)})

    return function (modulePath) {
        if (/node_modules/.test(modulePath)) {
            for (var i = 0; i < moduleRegExps.length; i ++)
                if (moduleRegExps[i].test(modulePath)) return false;
            return true;
        }
        return false;
    };
}
```

Usage is to put the above function in your preamble, and then call it to generate the "exclude" value, e.g.:

```
module.exports = {
  module: {
      rules: [
          {
              test: /\.js$/,
              loader: 'babel-loader',
              options: { presets: ['es2017', 'es2016', 'es2015' ] },
              exclude: excludeNodeModulesExcept(["lru_map"])
          },
```

You can add however many modules you need to exclude from exclusion to the list, although note that the test is O(n) in the number of modules, so if you have a *lot* of exclusions to process it may be worth finding a better way.

**Comment by danielo515** [comment]
The solution of @jh3141 is the only that I found that works for wepback 2 (thanks!)
Is there any other better or official approach ?

**Comment by sokra** [comment]
> Is there any other better or official approach ?

Don't use `exclude` always use `include`.

**Comment by danielo515** [comment]
Thanks @sokra,
I'm using a boilerplate (Quasar) which uses both, and currently I'm using both, and it works. Is it an anti-pattern or something like that ?

**Comment by wmyers** [comment]
I have an issue with `webpack-dev-server@2.9.3` and `webpack@3.8.1`. 

`webpack-dev-server@2.9.3` contains `const`s which throw a `SyntaxError: Unexpected keyword 'const'` error in Safari `9.1.2`. So I only want to transpile `node_modules/webpack-dev-server` with Babel.

This [thread](https://github.com/casesandberg/react-color/issues/314) provides a fix for older webpack config syntax. But if I use a `rule.include`(and _not_ a `rule.exclude`) then I get a strange error when webpack tries to bundle the first line of JSX in my React app.

This config:
```
module: {
    rules: [
      {
        test: /\.js$/,
        include: [
           path.resolve(__dirname, 'node_modules/webpack-dev-server/')
        ],
        use: [{
          loader: 'babel-loader',
          options: { 
            presets: ['env', 'react', 'stage-0'],
            plugins: ['transform-runtime'],
            cacheDirectory: true
          }
        }],
      }
   ]
}
```

Throws this error:
```
ERROR in ./src/index.js
Module parse failed: Unexpected token (19:2)
You may need an appropriate loader to handle this file type.
| const appContainer = document.getElementById('app');
| ReactDOM.render(
|   <Provider store={store} key="provider">
|     <div>
|       <App />
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./index.js
webpack: Failed to compile.
```

However if I change the config to use a `rules.exclude` in the manner shown by @KhramtsovMaksim above, then Webpack compiles successfully, Babel only transpiles `node_modules/webpack-dev-server` and the app now works on Safari.

```
module: {
    rules: [
      {
        test: /\.js$/,
        exclude: {
          test   : path.resolve(__dirname, "node_modules"),
          exclude: path.resolve(__dirname, "node_modules/webpack-dev-server")
        },
        use: [{
          loader: 'babel-loader',
          options: { 
            presets: ['env', 'react', 'stage-0'],
            plugins: ['transform-runtime'],
            cacheDirectory: true
          }
        }],
      }
    ]
  }
```

**Comment by Alphmega** [comment]
My solution is, overwritting `ModuleFilenameHelpers.matchObject`
```javascript
ModuleFilenameHelpers.matchObject = function matchObject(obj, str) {
  if(obj.test)
    if(typeof obj.test === 'function') return !!obj.test(str);
    else if(!ModuleFilenameHelpers.matchPart(str, obj.test)) return false;
  if(obj.include)
    if(!ModuleFilenameHelpers.matchPart(str, obj.include)) return false;
  if(obj.exclude)
    if(ModuleFilenameHelpers.matchPart(str, obj.exclude)) return false;
  return true;
};
```
And then,  use function as test

``` javascript
{
    test: /\.js$/,
    loader: 'babel-loader',
    test(str) {
        // return true if include
    },
    options: babelOptions,
},
```

**Comment by dlefloch** [comment]
@nowells provided a great and clean solution for this problem in the comments above, allows to exclude node_modules and selectively re-include some of them

**Comment by rafis** [comment]
After using hacks from up there I'm getting following error:

```
You should not need to recompile .ts files in node_modules.
Please contact the package author to advise them to use --declaration --outDir.
```

**Comment by northamerican** [comment]
[this webpack helper, babel-env-deps](https://github.com/andersdjohnson/webpack-babel-env-deps) is made to solve this problem, automatically transpiling modules according to your need as specified in .babelrc:

**Comment by abrkn** [comment]
In `package.json`

```javascript
    "transpile": "for f in auto-bind/index.js query-string/index.js query-string/node_modules/strict-uri-encode/index.js; do p=node_modules/$f; babel -o $p $p; done",
    "install": "npm run transpile"
```

Not pretty, but it works.

**Comment by ibufu** [comment]
https://babeljs.io/docs/en/config-files#6x-vs-7x-babelrc-loading
If you use babel 7.x, according to this documentation, you should change `.babelrc` to `babel.config.js`.

**Comment by joelworsham** [comment]
For anyone else stumbling upon this and still getting issues... there is one tiny gotcha that got me for the better half of the day. If your project directory matches the module you're trying to include, then it will not work. EG:

Project dir is named `my-cool-project` and your module you want to *include* is named `my-cool`. I don't know what the proper regex is to account for this, but changing your project directory will fix it.

Also, if you have a nested `node_modules` in your module due to a `package-lock.json` version inconsistency, this error also will happen.

**Comment by r00dY** [comment]
I like the fact there are so many solutions to this problem but why did no one suggest simply adding *two* rules? It works for me and is perfect because I can use different presets for library (or even specific file) from `node_modules`.

```
module.exports = {
    module: {
        rules: [
            // ...,
            // my application source code (added react preset)
            {
                test: /\.js$/,
                exclude: /node_modules/,
                loader: 'babel-loader',
                options: {
                    presets: ["@babel/preset-env", "@babel/preset-react"]
                }
            },
            // specific library (or could be file) from node_modules, only preset-env
            {
                test: /\.js$/,
                include: /node_modules\/LIBRARY/,
                loader: 'babel-loader',
                options: {
                    presets: ["@babel/preset-env"]
                }
            },
            // ....
        ]
    }
};
```

**Comment by dutchenkoOleg** [comment]
maybe someone will come in handy
https://github.com/WezomAgency/babel-loader-exclude-node-modules-except

**Comment by pezza3434** [comment]
Wow, lost 5 hours of my life to this.

I got this issue after updating babel. Was working absolutely fine before.

Issue was that I needed to change my babel config from .babelrc to 'babel.config.js' and simply change the file so that it exported an object, not just a json file.

**Comment by Johncy1997** [comment]
I finished one react-native app. But, now i should complete unit testing and code coverage report.Unfortunately, now i dont have idea about mocking node-modules..Suppose i test my Splash.js (which has imported react-native-languages,i18n-js,..etc). The testing has failed and throws **ReactNativeLanguages.default.addEventListener is not a function**.

**Package.json:**
********************

```
{
  "name": "pharmacy",
  "version": "1.0.4",
  "private": true,
  "rnpm": {
    "assets": [
      "Src/assets/fonts/"
    ]
  },
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start",
    "test": "jest --coverage --coverageDirectory=output/coverage/jest"
  },
  "dependencies": {
    "i18n-js": "^3.1.0",
    "react": "16.6.3",
    "react-native": "0.57.8",
    "react-native-fast-image-zoom-viewer": "^2.3.0",
    "react-native-firebase": "^5.1.1",
    "react-native-gifted-chat": "^0.7.2",
    "react-native-image-crop-picker": "^0.21.3",
    "react-native-image-zoom-viewer": "^2.2.25",
    "react-native-languages": "^3.0.1",
    "react-native-material-dropdown": "^0.11.1",
    "react-native-modal": "^7.0.2",
    "react-native-permissions": "^1.1.1",
    "react-native-progress": "^3.5.0",
    "react-native-restart": "0.0.9",
    "react-native-spinkit": "^1.1.1",
    "react-native-swiper": "^1.5.14",
    "react-native-view-toast": "0.0.1",
    "react-navigation": "^3.0.8",
    "react-redux": "^6.0.0",
    "realm": "^2.22.0",
    "redux": "^4.0.1",
    "redux-thunk": "^2.3.0",
    "rn-fetch-blob": "^0.10.15",
    "tipsi-stripe": "^7.1.0"
  },
  "devDependencies": {
    "babel-jest": "^23.6.0",
    "jest": "^23.6.0",
    "jest-junit": "^6.2.1",
    "metro-react-native-babel-preset": "^0.51.0",
    "react-test-renderer": "^16.6.3"
  },
  "jest": {
    "preset": "react-native",
    "transform": {
      "^.+\\.(js)$": "<rootDir>/node_modules/react-native/jest/preprocessor.js"
    },
    "setupFiles": [
      "./test/env.js"
    ],
    "coverageReporters": [
      "text"
    ],
    "reporters": [
      "default",
      "jest-junit"
    ],
    "collectCoverageFrom": [
      "Src/**/*.{js,jsx}",
      "!/node_modules/"
    ]
  },
  "jest-junit": {
    "output": "output/coverage/junit/junit.xml",
    "usePathForSuiteName": "true"
  }
}

```

**Splash-test.js:**
*********************
```
import React from 'react';
import Splash from '../Src/components/authentication/Splash';

import renderer from 'react-test-renderer';


test('renders correctly',()=>{
    const tree = renderer.create(
        <Splash />
        ).toJSON();
      expect(tree).toMatchSnapshot();
})
```
**test/env.js:**
***********

```
jest.mock('react-native-languages', () => class RNLocalization {
    language = 'en'
  
    constructor (props) {
      this.props = props
      this.setLanguage(this.language)
    }
  
    setLanguage (interfaceLanguage) {
      this.language = interfaceLanguage
      if (this.props[interfaceLanguage]) {
        var localizedStrings = this.props[this.language]
        for (var key in localizedStrings) {
          if (localizedStrings.hasOwnProperty(key)) this[key] = localizedStrings[key]
        }
      }
    }
  })
```
Someone help me, what should i do now, or give me some articles link for learning how to solve this immediately. I dont have enough time, i am under pressure to complete this unit testing.

**Comment by atkinchris** [comment]
> Someone help me, what should i do now, or give me some articles link for learning how to solve this immediately. I dont have enough time, i am under pressure to complete this unit testing.

@Johncy1997 - this is not the appropriate place for this, as it is not discussing this specific issue. Your examples are related to React Native and it's build tooling, not Webpack. If you believe this is a bug with the tools you are using, please raise an issue on the specific repository for the tool. If you require general support or guidance, please consult StackOverflow.

**Comment by jamesj2** [comment]
If you have a node_modules exclusion in babel.config.js you'll need to use regex to allow transpiling of your es6 node module. Similar to https://github.com/webpack/webpack/issues/2031#issuecomment-294706065.    After which I didn't need to modify my webpack config.

This is what I ended up with:
```
const ignore = [
  /node_modules[\\/](?!(query-string|strict-uri-encode)[\\/]).*/
];
```

**Comment by erdillon** [comment]
FYI. Ran into similar issue to what is listed here. I wasted 10h+ when the "fix" was to rename ".babelrc" to "babel.config.js" and change content with `module.exports=...`
Do read the https://babeljs.io/docs/en/config-files#6x-vs-7x-babelrc-loading carefully...

**Comment by YAN7** [comment]
> I like the fact there are so many solutions to this problem but why did no one suggest simply adding _two_ rules? It works for me and is perfect because I can use different presets for library (or even specific file) from `node_modules`.
> 
> ```
> module.exports = {
>     module: {
>         rules: [
>             // ...,
>             // my application source code (added react preset) - exclude all /node_modules/
>             {
>                 test: /\.js$/,
>                 exclude: /node_modules/,
>                 loader: 'babel-loader',
>                 options: {
>                     presets: ["@babel/preset-env", "@babel/preset-react"]
>                 }
>             },
>             // specific library (or could be file) from node_modules, only preset-env, include /node_modules/LIBRARY
>             {
>                 test: /\.js$/,
>                 include: /node_modules\/LIBRARY/,
>                 loader: 'babel-loader',
>                 options: {
>                     presets: ["@babel/preset-env"]
>                 }
>             },
>             // ....
>         ]
>     }
> };
> ```

thanks，It help me useful！！

**Comment by liqiang0335** [comment]
> example for webpack 2 [documentation](https://webpack.js.org/configuration/module/#rule-exclude)
> 
> ```
> exclude: {
>     test   : resolve(__dirname, "node_modules"),
>     exclude: resolve(__dirname, "node_modules/unfetch") // or your module - also can be an array (read doc)
> }
> ```



> https://babeljs.io/docs/en/config-files#6x-vs-7x-babelrc-loading
> If you use babel 7.x, according to this documentation, you should change `.babelrc` to `babel.config.js`.

work for me

**Comment by LeaveTheCapital** [comment]
For anybody trying this on windows, it is necessary to replace node_modules\/MY_MODULE with node_modules\\MY_MODULE because of windows using backslashes for file paths.. anyone who has ever diagnosed a bug to being a conflict between the direction of slashes on Windows vs Unix you will feel my pain!

**Comment by lake2** [comment]
> For anybody trying this on windows, it is necessary to replace node_modules/MY_MODULE with node_modules\MY_MODULE because of windows using backslashes for file paths.. anyone who has ever diagnosed a bug to being a conflict between the direction of slashes on Windows vs Unix you will feel my pain!

Thanks !!  Save my life!!

**Comment by WaterHong** [comment]
> @borm: a solution:
> 
> ```js
> {
>   test: /\.js$/,
>   exclude: /node_modules\/(?!(MY-MODULE|ANOTHER-ONE)\/).*/,
> },
> ```

it's work!

**Comment by dmitrienkop** [comment]
@jh3141 the most elegant solution, thanks!

**Comment by gabstin** [comment]
rules: [
      {
        test: /\.js$/,
        loader: 'babel-loader',
        exclude: {
          test: path.resolve(__dirname, "node_modules"),
          exclude: [
            path.resolve(__dirname, "node_modules/react-dnd"),
          ]
        },
      },

**Comment by brownieboy** [comment]
We ran into this issue recently when we started seeing "const must be initialized" errors in IE 11.  It turned out that some our dependencies, notably some of the D3 libraries, were no longer being transpiled to ES6.  (That's a deliberate decision on the part of D3's maintainer, FYI.)

Here's a rule that I added to our Webpack config file to transpile just the libraries affected:
```javascript
{
       include: mPath => {
         // Some npm modules no longer transpiled to ES5, which
         // causes errors such as "const must be initialized" IE 11 and crash
         // the build.  So we need to transpile just those modules here.

        const inclusionReg = /node_modules\/(.*(d3-array))|(.*(d3-delaunay))|(.*(d3-sankey))|(.*(d3-scale))/;
         // On Windows, mPath use backslashes for folder separators.  We need
         // to convert these to forward slashes because our
         // test regex, inclusionReg, contains one.
         const modulePath = mPath.replace(/\\/g, "/");

         if (inclusionReg.test(modulePath)) {

           // Don't need to see entire path in console
           const pathArray = modulePath.split(DIRNAMENIX);
           console.log("TCL: transpiling module: ", pathArray[1] || modulePath);
           return true;
         }
         return false;
       },
       test: /\.js$/,
       use: [
         {
           loader: "babel-loader",
           options: {
               presets: ["@babel/preset-env"]
             }
         },
       ],
     },
```

I find an `include` easier to get my head around than an `exclude`.  Like @nowells, I also prefer to implement it as a function, at least during the dev phase.  That way I can use a console.log() to track exactly which libraries are being picked up by the rule.

Note my inclusion Regex:
```javascript
const inclusionReg = /node_modules\/(.*(d3-array))|(.*(d3-delaunay))|(.*(d3-sankey))|(.*(d3-scale))/;
```
This picks up the listed libraries no matter far down they're nested in node_modules, as they may in there as dependencies of dependencies, e.g.:
* node_modules/d3-scale
* node_modules/@nivo/colors/node_modules/d3-scale/
and so on.


Finding which dependencies were causing our `const` errors in the first place took a bit of work.  Here's a Regex that I paste into VSCode's search box when searching through our /build folder:
`const(?:\s[^\s]+)\s{1,}(of|in)\s{1,}\w`

This will find all occurrences of `const foo in bar` or `const foo of bar`, which is what IE 11 was choking on for us.  (IE 11 actually supports `const` except for these two usages.)

**Comment by gottayan** [comment]
> > @borm: a solution:
> > ```js
> > {
> >   test: /\.js$/,
> >   exclude: /node_modules\/(?!(MY-MODULE|ANOTHER-ONE)\/).*/,
> > },
> > ```
> 
> it's work!

why does it not work for this?
{
        test: /\.js$/,
        use: ['babel-loader'],
        exclude: /node_modules\/(?!(cnchar|cnchar-trad)\/).*/,
      }

**Comment by jamesj2** [comment]
Try adding a backslash before the second to last forward slash.  

`exclude: /node_modules/(?!(cnchar|cnchar-trad)\/).*/,`

**Comment by gottayan** [comment]
{
test:&nbsp;/\.js$/,
use: ['babel-loader'],
exclude:&nbsp;/node_modules\/(?!(cnchar|cnchar-trad)\/).*/
｝

yeat.I had changed for this，but it did not work too.
could you give me a demo in the github？

发自我的iPhone


------------------ Original ------------------

**Comment by gottayan** [comment]
> { test:&nbsp;/\.js$/, use: ['babel-loader'], exclude:&nbsp;/node_modules\/(?!(cnchar|cnchar-trad)\/).*/ ｝ yeat.I had changed for this，but it did not work too. could you give me a demo in the github？ 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: James Johnson <notifications@github.com&gt; Date: Sun,Jan 3,2021 2:43 AM To: webpack/webpack <webpack@noreply.github.com&gt; Cc: gottayan <1174930941@qq.com&gt;, Comment <comment@noreply.github.com&gt; Subject: Re: [webpack/webpack] How to exclude node_modules but one (#2031) Try adding a backslash before the second to last forward slash. exclude: /node_modules/(?!(cnchar|cnchar-trad)\/).*/, — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

the regular expression is wrong.It can't match the package path in the node_modules.
the right one should be this. 
/node_modules(?!\/(.*cnchar|.*cnchar-trad)\/.*)/.test('node_modules/_cnchar@2.2.9@cnchar/cnchar.min.js')

**Comment by imantahriri** [comment]
```
rules: [
  {
    test: /\.(js|jsx)$/,
    exclude: /[\\/]node_modules[\\/](?!(nanoid)[\\/])/,
    loader: 'babel-loader',
  }
]
```
This used to work like a charm on Webpack 4, but since migrating to Webpack 5 I get this error in the console: 

```
Uncaught ReferenceError: module is not defined
    at eval (index.js:7)
    at eval (index.js:8)
    at Module../node_modules/nanoid/url-alphabet/index.js (bundle.js:3489)
```
I have been trying to fix it for a couple of days but I am running out of ideas now.

**Comment by nyngwang** [comment]
All idiots. The docs is very clear: https://webpack.js.org/configuration/module/#condition
