### ISSUE TITLE
Rewrite __dirname relative to output directory when targeting node

### ISSUE THREAD

**Issue by hayeah** [webpack/webpack#2033]
As is, `__dirname` isn't useful if we want to refer to static resources within a node package. One simple solution is to set `__outputdir` to be `__dirname` as is, and just refer to static resources relative to the output directory.

I also experimented with recovering the original __dirname semantic by calculating it relative to the output directory (assuming that the output directory is nested within the context).

Here's what I mean in terms of a plugin:

``` js
function DirnamePlugin() {
}

DirnamePlugin.prototype.apply = function(compiler) {
  compiler.parser.plugin("expression __outputdir", function() {
    this.state.current.addVariable("__outputdir", "__dirname");
  });

  compiler.parser.plugin("expression __moduledir", function() {
    const moduleRelativePathFromContext = path.relative(compiler.context, this.state.module.context);

    const outputDir = "__dirname";
    // TODO: Figoure out the package dir relative to outputdir. Now just assumes it to be the parent of outputdir.
    const packageDir = `${outputDir} + '/../'`;

        this.state.current.addVariable("__moduledir", `${packageDir} + ${JSON.stringify(moduleRelativePathFromContext)}`);
        return true;
    });
}
```

Right now I use `__moduledir` to mean `__dirname`. Would you consider something like this to be merged into NodeStuffPlugin?

**Comment by GuillaumeLeclerc** [comment]
I'm having this same problem. __dirname is not correct when targeting nodeJs

**Comment by hayeah** [comment]
@GuillaumeLeclerc try copy and paste the DirnamePlugin to your webpack.config, and see if `__moduledir` works for you.

```
config.plugins.push(new DirnamePlugin());
```

You may need to tweak the relative path to `packageDir` depending on where your output file is.

**Comment by hayeah** [comment]
@bebraw any suggestion for dealing with this problem?

**Comment by bebraw** [comment]
@hayeah Nope. I don't know the Node specific portion that well. :disappointed:

**Comment by ariporad** [comment]
Seconding this... It would be really great to have an option for this.

**Comment by anboxer** [comment]
I solve this issue by using  the **DefinePlugin** plugin
```
plugins: [
         new webpack.DefinePlugin({
            "__dirname": "__dirname"
        })
    ]
```
After adding this definition, webpack will not create **VAR INJECTION** for `__dirname`

PS: webpack@2.2.1
