### ISSUE TITLE
Exclude sourceMapContent from source maps

### ISSUE THREAD

**Issue by remko** [webpack/webpack#2034]
For production, I'd like to have a source map with file/line information, but I don't want to include the actual source code in the source map. Is there a way to do this with webpack? It seems that I always get `sourcesContent` in my source map.

**Comment by bebraw** [comment]
[SourceMapDevToolPlugin](https://webpack.github.io/docs/list-of-plugins.html#sourcemapdevtoolplugin) is your best bet. If it can't do it, open a feature request.
