### ISSUE TITLE
webpack.optimize.UglifyJsPlugin incorrectly compiling Font-Awesome

### ISSUE THREAD

**Issue by PeteJodo** [webpack/webpack#2037]
This may actually be a bug for uglifyjs but I figured I'd post the issue first because I'm not sure.

We're loading styles into our js files (so `require('some-scss.scss')`) and within a scss file we use a font-awesome mixin that's defined [here](https://github.com/FortAwesome/Font-Awesome/blob/master/scss/_mixins.scss#L6). What ends up being compiled looks like `font:normal normal normal 14px/\ 1 FontAwesome;` which is incorrect syntax obviously. I tracked it down to our call to `webpack.optimize.UglifyJsPlugin` that's causing it. It only appeared somewhat recently (within the last 2 months).

Here are the options I pass into the plugin:

``` javascript
{
    compress: {
        drop_console: true, // eslint-disable-line
        drop_debugger: true, // eslint-disable-line
        warnings: false
    },
    mangle: false
}
```

Any ideas?

**Comment by bebraw** [comment]
Can you try against webpack 2? In webpack 1 using UglifyJsPlugin causes css-loader to go into minifying mode. It doesn't do that in webpack 2. Perhaps that could be it.
