### ISSUE TITLE
 eval-source-map breakpoints do not get hit, and when setting breakpoint, breakpoint jumps to different line

### ISSUE THREAD

**Issue by duro** [webpack/webpack#2038]
I am trying for the life of me to get one of the more efficient source map option working.

When I use any `source-map` oriented devtool setting, if I try and set a breakpoint in Chrome 48.0.2564.82, it jumps to a different line that what I selected.

If I use `eval-source-map` not only do I get the line number jump, but I also never get a break point stop even on the line it jumped to.

**Comment by sesteva** [comment]
+1

**Comment by es6Test** [comment]
I'm considering ditching webback for system.js cause of this, absolute headache.

+10000000000000000000000000000000000000000000000000000000000000

**Comment by duro** [comment]
This appears to be the same issue as #1487

**Comment by notionslate** [comment]
I've noticed this as well. It does not occur in all methods of my code, but //comments seem to make it happen more often than not in code that follows the comment.

**Comment by bebraw** [comment]
Closing as duplicate.
