### ISSUE TITLE
Hot reload w hot/dev-middleware only works on publicPath:"/"

### ISSUE THREAD

**Issue by paulpflug** [webpack/webpack#2042]
I think this is probably a problem with the HotModuleReplacementPlugin

the variable `$hotMainFilename$` in [JsonpMainTemplate.runtime.js#L27](https://github.com/webpack/webpack/blob/master/lib/JsonpMainTemplate.runtime.js#L27) wont contain the `publicPath`, but webpack-dev-middleware is serving with `publicPath`

So it won't find the updated package

**Comment by sokra** [comment]
Configure `output.publicPath` correctly

**Comment by paulpflug** [comment]
ouch! - That took me way too long to be that simple.
Sorry for taking your time
