### ISSUE TITLE
ERROR in Cannot find module 'lodash/lang/isFunction'

### ISSUE THREAD

**Issue by petulla** [webpack/webpack#2044]
Hi

I'm not able to run webpack successfully with lodash > 4.0. I get the error:

```
ERROR in Cannot find module 'lodash/lang/isFunction'
```

prior to build.

Lodash < 4.0 is still working.

Hoping for resolution on the issue.

**Comment by bebraw** [comment]
You probably want to import `lodash/isFunction` instead. They flattened their namespace in 4.0.

See [lodash changelog](https://github.com/lodash/lodash/wiki/Changelog#compatibility-warnings) for further details.

**Comment by lilingling3** [comment]
I run webpack-dev-server ,and I have this question.
