### ISSUE TITLE
Simple functions as plugins

### ISSUE THREAD

**Issue by jhnns** [webpack/webpack#2046]
When webpack encounters a function as plugin, it is invoked to create a plugin object.

Since the plugin API is miraculously similar to the `function` API, wouldn't it be nicer to "inline" simple plugins that don't need to be parameterized just as functions?

Instead of 

```javascript
    plugins: [
        {
             apply: function (compiler) {
                 ...
             }
        }
    ]
```

you could write

```javascript
    plugins: [
        function (compiler) {
            ...
        }
    ]
```

I even think that this used to work. Why has this been changed?

**Comment by sokra** [comment]
``` js
     plugins: [
        function () {
            var compiler = this;
            ...
        }
    ]

**Comment by jhnns** [comment]
What? ^^ Why isn't the `compiler` passed as argument?

**Comment by sokra** [comment]
To keep it difficult to use ;)

**Comment by jhnns** [comment]
nice... :grin:

**Comment by sokra** [comment]
The real reason is that plain function work because of `Function.prototype.apply`.

**Comment by jhnns** [comment]
Yeah, that I was trying to say with:

> Since the plugin API is miraculously similar to the function API

But that seems logical to me... the `compiler` is passed as first argument to `apply()` ^^
