### ISSUE TITLE
UMD default export with babel6

### ISSUE THREAD

**Issue by kof** [webpack/webpack#2047]
Not sure if this is the right place. It seems like babel did the right fix in the latest version and now transpiles correctly. However the result when using umd wrapper in webpack doesn't seem to be correct.

``` javascript
  // something.js
  export default function something() {return 'hello'}

  // Using babel5 from global.
  window.something() // hello

  // Using babel 6 from global
  window.something // {__esModule: true,default: jssVendorPrefixer()}
  window.something.default() // hello
```

I would expect it to work in this case exactly as it did before when accessing via global object.

**Comment by sokra** [comment]
That's a babel change from 5 to 6. It's working correctly.

**Comment by kof** [comment]
Thats what I am trying to say. Babel 6 is fine, the end result after using webpacks umd - not really. Sounds like we can fix it in the umd wrapper by exposing the default if its provided.

**Comment by sokra** [comment]
babel 6 changed how modules are visible from non-es6-modules enviroments.`window.something.default` is correct.

**Comment by kof** [comment]
They changed the way how they convert es6 export default to cjs. They basically removed `module.exports = default` and now do only `exports.default = default`. This is fine for babel, because for them its just a internal change.

The end result for umd users however is different. Now we need to use explicitly `window.something.default` which means that now we need to consider that a module is transpiled from ES6. 

I don't think that end user of umd wrapped module, transpiled by babel6, should notice the difference.

The fix is easy. If there is an `exports.default`, use it.

Its not like webpack's umd is wrong. Its the lack of knowledge about `exports.default`. It worked before because babel5 was doing it wrong. Now they fixed that and umd exported api's are broken.

**Comment by kof** [comment]
feel free to close this when you still think it shouldn't be fixed and everything I wanted to point out is clear.

**Comment by kkwiatkowski** [comment]
I've fixed this issue/added support for module loaders in this pull request [#webpack/core/pull/23](https://github.com/webpack/core/pull/23)

**Comment by SpaceK33z** [comment]
Closing this since webpack 2 fixed a lot related to this, and I think it also fixed this situation. Feel free to re-open if I'm wrong.
