### ISSUE TITLE
Uncaught TypeError: angular.module is not a function

### ISSUE THREAD

**Issue by ace-han** [webpack/webpack#2049]
My `webpack.config.js` as below
```javascript
var path = require('path')
, webpack = require('webpack')

module.exports = {
	context : __dirname,

	resolve : {
		modulesDirectories : [ 'node_modules', 'bower_components' ],
		extensions : [ '', '.js', '.jsx' ]
	},
	
	entry : {
		app: './static/scripts/app.js'
	},
	output : {
		path : path.resolve('./assets'), // bridge point to django
		filename : '[name].js'
	},

	plugins : [
	    /*
   	    new webpack.ResolverPlugin(
   	    	new webpack.ResolverPlugin.DirectoryDescriptionFilePlugin('bower.json', ['main'])
   	    )
   	    */
	],

	devtool : 'source-map'
}
```
My demo project looks like
![image](https://cloud.githubusercontent.com/assets/1177332/13045323/9a2544ce-d40d-11e5-8e08-0a62a688d77f.png)

**if I enable** `webpack.ResolverPlugin`, I will get below error when open index.html in the browser
![image](https://cloud.githubusercontent.com/assets/1177332/13045405/0b1d2480-d40e-11e5-9096-82b955d37cdf.png)

Running `webpack` output(with `webpack.ResolverPlugin` or not) looks like below:
![image](https://cloud.githubusercontent.com/assets/1177332/13045461/67ce1aa4-d40e-11e5-8948-33533442b75c.png)

Where have I done wrong? 
Plz kindly help me out, thx.

**Comment by ace-han** [comment]
Listing other file sources, for quick test start 

```javascript
// app.js
define([
    'angular'
]
, function (angular) {
    'use strict';

    var app = angular.module('app', []);
    return app;
});
```

```html
<!-- index.html -->
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Angular Test</title>
  </head>

  <body>
  	angular test
	<script src="assets/app.js"></script>
  </body>
</html>
```

**Comment by danpantry** [comment]
Angular doesn't seem to support CommonJS. You'll need to shim it with `exports-loader`.

````
      { loader: 'exports?window.angular', test: require.resolve('angular') },
````

**Comment by ace-han** [comment]
@danpantry , I have already add this `exports-loader`, `angular` still an empty Object after `require('angular')`.
No luck...

![image](https://cloud.githubusercontent.com/assets/1177332/13167070/50ed94c8-d70a-11e5-9887-0c531f4cb0a6.png)

**Comment by danpantry** [comment]
Ahh, you're using AMD. I'm not sure how that format works with Webpack. I'll see if I can get a working example for you.

**Comment by mlent** [comment]
If it helps, you can have a look at a [blogpost](http://monicalent.com/blog/2015/08/03/converting-angular-js-app-from-require-js-to-webpack/) I wrote on working with Angular and Webpack. I definitely had a hard time getting Angular to load properly. They key ended up being something like:

```javascript
module: {
    loaders: [
      { test: /[\/]angular\.js$/, loader: "exports?angular" }
    ]
  },
  resolve: {
    alias: {
      angular: __dirname + '/app/vendor/angular/angular'
    }
  }
```

This works for us in files using AMD as well as those in ES6 module syntax.

**Comment by ace-han** [comment]
@mlent Your config snippet is working in AMD, thx!

Just out of curiosity, why adding a `webpack.ResolverPlugin` will has this side effect on angular?

**Comment by danpantry** [comment]
@ace-han the `main` field in `package.json` points to a commonjs file that uses `require` and assumes it to be synchronous. This won't work for AMD (I assume). The alias @mlent gives points directly to the raw angular.js script without the commonjs wrapping.

The exports loader then exports the `angular` variable from that module.

**Comment by ace-han** [comment]
@danpantry for the part 

>  When you use angular without the alias it will try and use the require from AMD (which is asynchronous), so the angular you get back from that module hasn't been fully defined yet.

Is this the default behaviour in AMD? 

As far as I know, in AMD below codes should work fine
```javascript 
define(['dep1', 'dep2'], function(dep1, dep2){ 
    // dep1, dep2 should be already fully loaded
    dep1.doSth1(); 
    dep2.doSth2();
})
require(['dep3', 'dep4'], function(dep3, dep4){ 
    // dep3, dep4 should be already fully loaded
    dep3.doSth3(); 
    dep4.doSth4();
})
```

Do I understand well?
I am referring to this page https://addyosmani.com/writing-modular-js/

**Comment by danpantry** [comment]
The code you've got there is completely asynchronous. The function you pass to `require` is executed at some point in the future after the `require` call (as early as the next tick), and is therefore asynchronous. And yes, this is the default behaviour of AMD.

**Comment by ace-han** [comment]
Thx @danpantry. Two more quick questions
```javascript
define(['angular'], function(angular){ 
    // here angular is just a reference, might not be fully loaded
    // Point_1
    angular.module('app', []);
    // other stuff...
})
```

1. Is there any mechanism to ensure the variable retrieved by AMD is fully loaded at `Point_1`?
2. Who is responsible for setting `angular` as an empty `Object` / `{}` at `Point_1` under current situation?

**Comment by danpantry** [comment]
Sure.

1. The value retrieved by AMD would be defined by the calling script calling `define(deps, function() { return value })`. The value returned the function (denoted by `return value` here) is what is passed to consumers of that `define`d library. 

At the point that the `define` or `require` function you have there is executed, any of the dependencies you've listed should be completely resolved. As such, by Point_1, the library is fully loaded.

2. Angular is. Angular's code does not have a UMD (Universal Module Definition) in it (at least not of writing), and it doesn't support AMD either, so it never calls `define()` - so AMD has no idea about what it returns. You should be able to 'shim' this using various loaders or plugins in Webpack. I'm not sure how AMD works in Webpack, but I would imagine `exports-loader` would be the path you'd take here.

I'd recommend that unless you're bound to AMD (via requirejs) that you use CommonJS or ES6 modules and only fall back on asynchronous loading if you absolutely have to. It just makes code easier to read about.

Recommended reading:

http://requirejs.org/docs/start.html
https://webpack.github.io/docs/loaders.html

**Comment by ace-han** [comment]
@danpantry Thx for the explanation!

**Comment by texonidas** [comment]
I feel this should be mentioned for anyone else who has found themselves here for the same reason, AMD stands for Asynchronous Module Definition.

**Comment by lili21** [comment]
@mlent It works. just wonder the reason. will `require('angular')` pass the `/[\/]angular\.js$/` test ?

**Comment by lili21** [comment]
@danpantry 
```
{ loader: 'exports?window.angular', test: require.resolve('angular') },
```
The solution does not work .  

`Cannot find module 'angular'`

**Comment by lili21** [comment]
@mlent and Your solution will have side effect. Consider a third-part dependency contains a file name `angular.js`, like [raven-js](https://docs.sentry.io/hosted/clients/javascript/integrations/angular/#module-loaders-commonjs), 

`require('raven-js/plugins/angular')` will give me `angular` rather then what suppose to be.

**Comment by danpantry** [comment]
@lili21 that indicates you've not got angular installed properly, my code snippet would not break that.

FWIW I actually use raven-js and @mlent's approach works fine.

**Comment by lili21** [comment]
@danpantry I can use angular by @mlent's approach, I just can't use it with raven-js togher.So I think I installed angular properly. I mean it just `npm install angular --save` right ?

are you using raven-js CommonJs way ?? like this 


```
var angular = require('angular');
var Raven = require('raven-js');

Raven
  .config('https://<key>@app.getsentry.com/<project>')
  .addPlugin(require('raven-js/plugins/angular'), angular)
  .install();
```

I output the result of `require('raven-js/plugins/angular')` , and it just angular.

**Comment by lili21** [comment]
@danpantry by the way, I rename `raven-js/plugins/angular.js` file  to something else, like `raven-js/plugins/ra-ng.js`, and It works.
