### ISSUE TITLE
Code splitting and chunks inter-dependency

### ISSUE THREAD

**Issue by rosenfeld** [webpack/webpack#2051]
Hi, I'd like to inform webpack that a lazily loaded chunk should depend on another to save some downloading and I think it's not currently possible.

There are basically two kind of users we support, clients and internal users. The internal users are able to use the client's features but additional features are supported for them. So, I'd like to lazily load some code for both clients and internals, but in the case of internal users, when they would require the advanced features, I'd like to instruct the system to only load the additional code, which is much smaller than the full chunk it currently generates, which is pretty similar to the other chunk for view-mode which is the only one enabled for clients. Here's some example to illustrate

viewer.js
require('./base.js')
// some code for the view mode

edit.js
require('./base.js')
// some code for the edit mode

Usually the edit mode would be launched after the view mode is active. Currently it will redownload 'base.js' and any other common dependencies which are not in the entry JS, while it would be much better if it could require 'viewer.js' if it's not yet loaded and then only load the code which is not shared by viewer.js. So, edit.js would contain some require.ensure(['./viewer.js']) before running the code. Additionally, when generating the edit.js chunk it would assume all modules required by viewer.js are already available.

Please let me know if I wasn't able to express myself very clearly.

**Comment by sokra** [comment]
I hope I understand you correctly. 

An on-demand chunk doesn't include modules of the parent chunk, as they are already available. If you require.ensure `viewer.js` from `edit.js`, `base.js` would only be in the edit-chunk and not in the viewer-chunk

**Comment by rosenfeld** [comment]
This is a bit tricky. What you are proposing is to write edit.js like this:

```javascript
require(['./viewer.js'], function() {
  require('./base.js')
  window.Edit = function(){...}
})

// then it would be called like this:

require(['feature/edit.js'], function(){console.log(window.Edit)}) // obviously it would undefined in the first call
```

One problem is that the call back will be called before edit.js actual code was processed. I have to add some setTimeout work-around to wait for window.Edit to become available before trying to use it.

Is there API I could call in some module to notify when it's considered loaded?

Another problem is that it was creating 2 chunks in the original example containing the View code. I had to use require.ensure and provide it a name in both places requiring 'viewer.js', so that webpack could understand that code should belong to the same chunk.

Also, from a design point of view, edit.js do not really depend on viewer.js. It only depends on base.js, but for performance optimization I prefer to bundle base and viewer in the same chunk and make the edit.js chunk depend on the view.js chunk because I think that makes sense due to how those codes are used in our application.

It would be awesome if webpack could provide me some means to specify such chunks dependencies and actually only run the handler once the parent chunk has been completely evaluated rather than running just after requesting the child chunk.

Please let me know if this explanation is confusing.

**Comment by bebraw** [comment]
@rosenfeld Did you manage to figure this out?

**Comment by rosenfeld** [comment]
To these days I'm still running a setTimeout and checking whether or not Edit is available every 10 ms. Something like this:

```CoffeeScript
    lazyRun = =>
      (setTimeout lazyRun, 10; return) unless window?.Edit # the actual name is a bit different
      @_runActualThing()
    require.ensure ['transactions/edit.js.coffee'],
      (-> require ['transactions/edit.js.coffee'], lazyRun), 'transaction-edit'
```
