### ISSUE TITLE
Is it possible to bundle the bundler?

### ISSUE THREAD

**Issue by a-s-o** [webpack/webpack#2057]
Hello. I have an odd question but first of all thanks for this great tool. It has been very useful.

I am working on a framework which uses webpack as the build process ([link](https://github.com/motorcode/relm)). Basically, I would like to provide an easy way for users to compile their code with a pre-configured webpack compiler. Currently, I have webpack and the the related loaders, babel-core, etc. as normal dependencies for my project. It is a little unpredictable and depending on npm version can break.

I would like to know if it is possible to bundle webpack in a single module along with all the loaders in order to shrinkwrap, in a sense, the whole compiler. This is what I have so far:
```javascript
// compiler.js
var webpack = require('webpack');

module.exports = function compiler () {
  const opts = arguments[0] || {};

  return new webpack({
    entry: opts.entry,
    output: opts.output,
    module: {
      loaders: [
        { test: /\.js$/, loader: 'babel-loader' }
      ]
    }
  });
};
```
And the following config:
```javascript
// webpack.config.js
var output = require('path').resolve(__dirname, './bundle');
var webpack = require('webpack');

module.exports = {
  entry: './compiler.js',
  output: {
    path: output,
    filename: 'compiler.js',
    library: 'Compiler',
    libraryTarget: 'commonjs2'
  },
  target: 'node',
  module: {
    loaders: [
      { test: /\.json$/, loader: 'json-loader' }
    ]
  },
  plugins: [
    new webpack.PrefetchPlugin('babel-loader')
  ]
};
```

This works in that I can bundle everything into one module (which is about 3mb) but then I run into the following error when I try to use that compiler function to transform some test code:
```shell
Hash: d6b7d6bad8ca0746b6ec
Version: webpack 1.12.13
Time: 34ms

ERROR in Cannot load loader, __webpack_require_loader__ not provided.
```
Is what I am doing even possible? If it is, is there a way to get around this error?

From what I see, module id 0, which is the bootstrap should be executing properly and it has a definition for __webpack__require__. I am not sure where __webpack__require__loader__ should be coming from.

Thanks in advance for any help. Much appreciated.

**Comment by a-s-o** [comment]
Hi, assuming this is not possible and closing the issue. Thanks

**Comment by imvetri** [comment]
Possibly similar discussion is happening here [https://github.com/webpack/webpack/issues/2797]. Hope it helps.

**Comment by zjuasmn** [comment]
It' possible. Just add `__webpack_require_loader__` to global scope 
```
global.__webpack_require_loader__ = function (loaderName) {
  return require('babel-loader');
}
let compiler = require('./bundle/compiler')
/* call the compiler */
//...
```
