### ISSUE TITLE
"TypeError: Path must be a string" after upgrading

### ISSUE THREAD

**Issue by phaistonian** [webpack/webpack#2059]
This issue came up after upgrading to 2.07b and it's probably related to Stylus loader.

Here's a link to the issue, as already posted by another guy: https://github.com/shama/stylus-loader/issues/96

Not sure this is related to stylus loader or it has to do with some API change in webpack 2 (or a bug).

Any clues?

Thank you.

**Comment by gitaarik** [comment]
Also getting this error on webpack@1.12.14

i'm not using stylus

**Comment by gitaarik** [comment]
Ok, I got this error because in there was an error in `webpack.config.js`, from the error message it was just not clear that this error came from the `webpack.config.js`, but after finding out it was easily solvable.

**Comment by L3V147H4N** [comment]
@gitaarik what was the error?

**Comment by gitaarik** [comment]
I gues `TypeError: Path must be a string` ;)

**Comment by L3V147H4N** [comment]
I solved it by removing webpack css-loader style-loader stylus-loader and installing again together with package stylus. Now it works find. I'm using node 6

**Comment by janv** [comment]
I got the same error after switching from node 5 to 6 with no other changes at all

**Comment by greennyreborn** [comment]
@janv Same for me. Do you find a solution?

**Comment by janv** [comment]
I simply went back to Node 5 :)
The update to 6 was more of an accident

**Comment by rohanthewiz** [comment]
It is your dependencies folks. Here is how I solved my stylus-loader issue (Path must be a string):
See my comment here: https://github.com/webpack/css-loader/issues/106#issuecomment-218787297

**Comment by hzitoun** [comment]
I had the same issue. Resolved that by downgrading to node v5.12.0.

**Comment by bebraw** [comment]
Looks like the related issue was fixed. Time to close.
