### ISSUE TITLE
Error: Cannot find module 'webpack/lib/node/NodeTemplatePlugin'

### ISSUE THREAD

**Issue by jrs320** [webpack/webpack#2060]
Hi,i met a problem,can anybody help me? (excuse me,my english is very pool  - - )

![image](https://cloud.githubusercontent.com/assets/6623047/13104265/0a06b68a-d597-11e5-904f-90e221546177.png)

my code aboved, i had installed html-webpack-plugin, when i webpack, a error happened:

![image](https://cloud.githubusercontent.com/assets/6623047/13104345/8d33b0f8-d597-11e5-8854-f36974dbb4e0.png)

what can i do,please help me, thanks.

**Comment by jrs320** [comment]
i get it, should install webpack local not global

**Comment by energy162** [comment]
why should install webpack local not global?

**Comment by kylezhang** [comment]
@timotius02
https://github.com/LeeChingYin/webpack/blob/e62b2ae5841a07d91fc0246b4d91b9a9527f62da/README.md

**Comment by sdbeng** [comment]
Tried to npm install NoteTemplatePlugin but node-template-plugin' is not in the npm registry.

**Comment by natsn** [comment]
@sdbeng this is what worked for me: https://github.com/webpack/webpack/issues/2131#issuecomment-191581752

**Comment by dynasty-fire** [comment]
@jrs320 thks

**Comment by gradylu** [comment]
i have the same issue
