### ISSUE TITLE
Option to avoid sparse arrays when calling webpackJsonp

### ISSUE THREAD

**Issue by mnpenner** [webpack/webpack#2063]
**Problem:**

Following the discussion [from here](https://gitter.im/webpack/webpack?at=56c4c454aa5f8e7a7f672a07) and [here](https://babeljs.slack.com/archives/discussion/p1455736086000592).

It appears that when `DedupePlugin` is enabled _and_ `NamedModulesPlugin` is disabled then webpack will use sparse arrays like so:

```
webpackJsonp([ 0, 4 ], [ , , , , , , , , function(module, exports, __webpack_require__) {
```

Instead of objects like so:

```
webpackJsonp([ 3, 11 ], {
    373: function(module, exports, __webpack_require__) {
```

The sparse arrays break IE8 (and below).

Tested with webpack 1.12.13.

**Potential solutions:**
1. Never use sparse arrays / make IE8 support the default
2. Add an option to avoid sparse arrays / support IE8 (akin to UglifyJS's `screw_ie8` option)

**Workarounds:**
1. Disable `DedupePlugin` (it might not even be reducing the output size)
2. Enable `NamedModulesPlugin`

**Comment by sokra** [comment]
After some discussion we decided for the following statement regarding IE8:

We don't support IE8 in webpack 2. IE8 is not supported by Microsoft and doesn't get security fixes. We think it's no responsible to allow web developers to build webapps which support IE8. They must break!
