### ISSUE TITLE
[doc] Loader include property needs a description

### ISSUE THREAD

**Issue by BrainCrumbz** [webpack/webpack#2068]
Hello all. Thanks for this great piece of software, first of all.

While browsing through webpack documentation, we found the following in [module loaders](https://webpack.github.io/docs/configuration.html#module-loaders) config section:

~~~
test: A condition that must be met
...
include: A condition that must be met
~~~

Shouldn't `include` have a different (and more meaningful) description? As a matter of fact, we were trying to figure out the spec for that property and could not find any.

HTH

**Comment by eisisig** [comment]
Right under the list there is a line describing what "condition" can be

> A condition may be a RegExp (tested against absolute path), a string containing the absolute path, a function(absPath): bool, or an array of one of these combined with “and”.

Did you have anything other than that in mind?

**Comment by BrainCrumbz** [comment]
Totally skipped that sentence, sorry about that. Without it, it seemed a kind of typo from copy & paste. Thanks for clarifying!

**Comment by eisisig** [comment]
I agree, without the description it wouldn't be enough info :)
