### ISSUE TITLE
HMR with Electron target

### ISSUE THREAD

**Issue by ccorcos** [webpack/webpack#2069]
I got everything working with React HMR and electron. The key was settings some configs to explicitly hit localhost:8080:

```js
  entry: {
    app: [
      'webpack-hot-middleware/client?path=http://localhost:8080/__webpack_hmr',
      './src/browser/app.js'
    ],
  },
  output: {
    path: path.join(__dirname, 'dist'),
    filename: 'bundle.js',
    publicPath: 'http://localhost:8080/'
  },
```

But then, when it came time to use the electron IPC api, I had to `require('electron')` and other built-in external modules. I think this is preventing HMR from working now because I get this in the browser console:

```
[HMR] Cannot find update (Full reload needed)
[HMR] (Probably because of restarting the server)
```

Any ideas?

**Comment by Phoenixmatrix** [comment]
When you use HMR with electron target, the HMR stuff tries to hit the local file system instead of the webpack dev server url for the newly compiled module. Since the webpack dev server (or middleware) obviously don't leave files on disk, it doesn't find it, and fail. I think this happens because HMR uses the `fs` polyfill when running in default mode, but in node/electron it uses native fs, so it tries to find stuff on disk. Not 100% sure though.

If you DON'T use the electron target, then it works as expected, but you have to add all of the "native" dependencies  like electron, to externals in your webpack config.

There's probably a better way to handle this, but that's what has worked for me until that feature gets some design tweaks.

**Comment by ccorcos** [comment]
Awesome -- I'll give that a shot!

**Comment by ccorcos** [comment]
So I've added this

```js
  externals: {
    electron: "electron"
  }
```

and now I get "electron is undefined"

**Comment by ccorcos** [comment]
Figured it out:

```js
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new webpack.ExternalsPlugin('commonjs', ['electron'])
  ],
```

Seems like that should be the default functionality of the electron target...

**Comment by Phoenixmatrix** [comment]
It should be. Also, I didn't need to use ExternalsPlugin directly. I just
defined by externals as an array, which also works.

externals: ['electron', 'fs']

On Sun, Feb 21, 2016 at 4:15 PM Chet Corcos <notifications@github.com>
wrote:

> Figured it out:
>
>   plugins: [
>     new webpack.HotModuleReplacementPlugin(),
>     new webpack.ExternalsPlugin('commonjs', ['electron'])
>   ],
>
> Seems like that should be the default functionality of the electron
> target...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/webpack/webpack/issues/2069#issuecomment-186919459>.
>
-- 
-Francois Ward

**Comment by ccorcos** [comment]
ah, I see -- should I close this or leave it open so it gets fixed/

**Comment by mike182uk** [comment]
I was also experiencing this issue. Using the `webpack.ExternalsPlugin` solved the problem, but as @Phoenixmatrix said, you should just be able to use the `externals` config options. When I originally tried to use `externals`, webpack would compile ok, but the external modules would be undefined in the app. I needed to add the `libraryTarget` config option to `output` to get `externals` to work without having to use the plugin:

```
output: {
    //...
    libraryTarget: 'commonjs2'
  },
  externals: ['remote'],
  //...
```

**Comment by otbe** [comment]
@ccorcos & all
Maybe it is a bit late, but do you bundle all dependencies (node_modules) into your bundle.js? 
This should not be necessary at all, shouldn't it?

Do you use ```http://localhost...``` or ```file://.....index.html``` in your ```loadURL()``` from electron?
I can't get HMR working at all with electron, but same config works fine in chrome.

**Comment by ccorcos** [comment]
@otbe you can check out everything I did [here](https://github.com/ccorcos/dev-tool)

**Comment by otbe** [comment]
Couldn't get it working. Also your example did not work for me. :/
Will give webpack2 beta a try this afternoon.

**Comment by ccorcos** [comment]
weird. it works for me -- can you file an issue with the error you get?

**Comment by bebraw** [comment]
@otbe Any luck?

**Comment by tj** [comment]
Anyone have real docs for how to get it working with Electron? I tried `externals: ['fs']` etc, but that compiles to the literal:

```js
/***/ function(module, exports) {

	module.exports = fs;

/***/ },
```

which just throws undefined
