### ISSUE TITLE
Webpack development server locks files when running under Windows

### ISSUE THREAD

**Issue by DullReferenceException** [webpack/webpack#2070]
I've had so many issues caused by what seems to be the file watcher of the webpack development server holding a lock on files. One problem this causes is `npm install` failing to delete temporary files, and another is rebases getting mucked up with symptoms like commits being skipped or the working directory getting into a bad state. I have to always remember to stop the dev server before doing these operations. Of course it's intermittent.

I'm not sure where to start looking into this, but could it be that watched files are being opened with overly-aggressive access levels?

**Comment by sokra** [comment]
webpack uses https://github.com/paulmillr/chokidar
you can report the issue there.
