### ISSUE TITLE
CLI help：How to remove the contents of 'output' folder when running ‘webpack’ command, I don't want to cover the old contents!

### ISSUE THREAD

**Issue by jrs320** [webpack/webpack#2071]
How to remove the contents of 'output' folder when running ‘webpack’ command, I don't want to cover the old contents!

**Comment by bebraw** [comment]
https://www.npmjs.com/package/clean-webpack-plugin works nicely. You can also perform `rm` outside of webpack before running it.

**Comment by jrs320** [comment]
let me look look, thinks!
