### ISSUE TITLE
Cannot use Microsoft Azure node.js SDK with Webpack "the request of a dependency is an expression"

### ISSUE THREAD

**Issue by dukedougal** [webpack/webpack#2076]
I'm wanting to use https://github.com/Azure/azure-sdk-for-node

And when I build I get:

WARNING in ./~/azure-common/~/request/lib/optional.js
Critical dependencies:
11:13-32 the request of a dependency is an expression
 @ ./~/azure-common/~/request/lib/optional.js 11:13-32

Can someone please suggest ideas for what I can do to fix this?

thanks!

**Comment by IngwiePhoenix** [comment]
What does the LoC look like?

**Comment by dukedougal** [comment]
Sorry what is LoC?

**Comment by IngwiePhoenix** [comment]
Line of code. :)

**Comment by dukedougal** [comment]
The entire code of optional.js looks like this:

```
'use strict';

module.exports = function(moduleName) {
  try {
    return module.parent.require(moduleName);
  } catch (e) {
    // This could mean that we are in a browser context.
    // Add another try catch like it used to be, for backwards compability
    // and browserify reasons.
    try {
      return require(moduleName);
    }
    catch (e) {}
  }
};

```

**Comment by IngwiePhoenix** [comment]
The code is trying to require a module by using a variable’s content. WebPack does not know what this variable may contain and therefore reports this problem. It might be acceptable in a Node environment, but breaks hard in a Web environment.

**Comment by dukedougal** [comment]
It looks like it has a dependency on an old version of request. I have gone up a level in npm/webpack problem resolution.

**Comment by bebraw** [comment]
Closing as an answer was presented.
