### ISSUE TITLE
Sourcemaps not generated for jsx files. No ability to change SourceMapDevToolPlugin test option.

### ISSUE THREAD

**Issue by awong-dev** [webpack/webpack#2078]
This makes handling jsx annoying, especially in Karma.  See
  https://github.com/webpack/karma-webpack/issues/104

**Comment by af7** [comment]
+1

**Comment by bebraw** [comment]
As mentioned in the linked issue, the problem is at https://github.com/webpack/webpack/blob/5b5775f9e2fc73fea46629f2d6a3ed7a1f8424d3/lib/SourceMapDevToolPlugin.js#L35 . By the looks of it you should pass custom `test` that includes `jsx` somehow.

**Comment by pksjce** [comment]
This issue was moved to webpack/webpack.io#151
