### ISSUE TITLE
Node target, possible to get a list of compiled assets from within the bundle?

### ISSUE THREAD

**Issue by olalonde** [webpack/webpack#2083]
I'm trying to use webpack with "target: node". It works fine but I need a way to get access to all the compiled assets from within the bundle to put them in my html header. Is such a thing possible?

**Comment by sokra** [comment]
Yes, this information is in the Stats. You get from the callback in the node.js API, or with `--json` in the CLI, or in a `done` plugin.

But the words `"target: node"` and `my html header` doesn't make sense together. target node is for consuming via `require` in node.js, target web is for consuming in a HTML page.

**Comment by olalonde** [comment]
I see, thanks. I'm rendering a React component server side which is why I need that info.
