### ISSUE TITLE
`Object.defineProperty` breaks bundles to do not work them in IE 8.

### ISSUE THREAD

**Issue by Pitzcarraldo** [webpack/webpack#2085]
When updated webpack from v1.12.12 to v1.12.13, below parts is changed.
And to use `Object.defineProperty` for object is not supported by IE8. So bundles made by v1.12.13 is not working well in IE8.

https://github.com/webpack/webpack/blob/v1.12.13/lib/HotModuleReplacement.runtime.js#L32

I know about IE8 support would be dropped. But according to semver rules, patch updates have to keep backwards-compatible, and this patch update breaks it.

I think it could be better that fix or notice to users about this.

Thanks.

**Comment by sokra** [comment]
Yeah, sorry. But I think IE8 doesn't support getters and I can't fix this without getters... :( So this propably means that IE8 is not supported when hot module replacement is enabled. Or do you have an idea how to fix it?

**Comment by SimenB** [comment]
Is it worth breaking IE8 in a patch release to fix #1650, which can be worked around with configuration, if I understand that issue correctly?

**Comment by sokra** [comment]
https://github.com/webpack/webpack/commit/59c0c4a4c85b8867116fa23c3c4ce2ba72fff0e7

**Comment by SimenB** [comment]
Great! It's possible to shim `Object.defineProperty` though, just not getters and setters, so that check might fail. React checks if it's available my catching the exception and exporting a boolean. Could you maybe do the same?

https://github.com/facebook/react/blob/master/src/shared/utils/canDefineProperty.js

**Comment by sokra** [comment]
Would you like to make a PR?

**Comment by SimenB** [comment]
I could do that.

Not sure exactly how you want it, but quick and dirty: #2087
