### ISSUE TITLE
How can I get the entry file name in the loaders?

### ISSUE THREAD

**Issue by weekeight** [webpack/webpack#2090]
If I have a entry `hello.js` like this:

```
require('./images/test.png');
```

and I use `file-loader` to handle this, then I want the built image named as "hello.test.png",how can I make it?

The following example can not fill my need:

```
{
  test: /\.(jpe?g|png|gif|svg)$/i,
  loaders: ['file?hash=sha512&digest=hex&name=[path][hash].[ext]']
}
```

**Comment by jeffijoe** [comment]
I doubt this is possible unless the `file-loader` lets you run arbitrary functions to format the file name.

**Comment by sokra** [comment]
``` js
{
  test: path.resolve("./images/test.png"),
  loader: "file?name=hello.test.png"
}
```

**Comment by weekeight** [comment]
@sokra The project has multiple entry file,not just one.I want the built image name prefixs with its related entry file name?Can we make it?

**Comment by indieveed** [comment]
Seems duplicate to #1381.
Interested in this issue too, though.

**Comment by wojohowitz** [comment]
recursive issue references here #1381 is pointing back to this one each citing a duplicate of the other  :)

**Comment by oleggromov** [comment]
Finally, guys, is there a way to get entry point name in a custom loader?

**Comment by FuriouZz** [comment]
The only way, I found was to explore the `reasons` of the module directly in the loader.

```
var findEntry = function( mod ) {
  if (mod.reasons.length > 0) {
    return findEntry( mod.reasons[0].module )
  }
  return mod.resource
}

module.exports = function MyLoader() {
  var entry = findEntry( this._module )
  ...
}
```

**Comment by mcm-ham** [comment]
Thanks FuriouZz, unfortunately it doesn't work during HMR compilation.

**Comment by PierBJX** [comment]
@mcm-ham Your solution is not working anymore. Do you have any idea?

**Comment by MuhammadMabrouk** [comment]
Any updates on this issue?!

**Comment by lishichao1002** [comment]
why this._module is undefind ?? @mcm-ham
