### ISSUE TITLE
Is there any good way to disable UglifyJS warning while using '-p' option?

### ISSUE THREAD

**Issue by simnalamburt** [webpack/webpack#2093]
Is there any good way to disable UglifyJS warning while using `-p` option?

You'll get *535* lines of warnings when you minify react codes. `-p` option of webpack just adds new UglifyJS plugin without checking existing plugin so there's no way to disable CLI-added UglifyJS's warning except running UglifyJS twice (which is highly undesired).

Help!

**Comment by bebraw** [comment]
Based on the code, no.

If you want to disable the warnings, skip using `-p` and set it up manually.
