### ISSUE TITLE
react-hot-loader doesn't work properly with webpack@2.1.0-beta.2 

### ISSUE THREAD

**Issue by alubchuk** [webpack/webpack#2094]
It does not cause hot-updates, only after refresh

**Comment by alubchuk** [comment]
After some investigation I found out, that it has broken in webpack@2.0.1-beta

**Comment by bebraw** [comment]
Given *react-hot-loader* has been deprecated, you most likely want to try out a [react-transform-hmr](https://github.com/gaearon/react-transform-hmr) based setup instead.

**Comment by alubchuk** [comment]
I see, thanks!
