### ISSUE TITLE
output script that does *not* use common vendor chunks

### ISSUE THREAD

**Issue by aj0strow** [webpack/webpack#2098]
I have a website, iframe, and embed script. 

```js
  entry: {
    website: "website/index.js",
    iframe: "iframe/index.js",
    embed: "embed.js",
    vendor: [ /* list of deps */ ],
  },
  ```

The vendor chunks stay cached between releases. It works great for the website and iframe. 

```html
<script src="vendor.js"></script>
<script src="website.js"></script>
```

However, it breaks the embed script which is used to autosize the iframe. 

```html
<div>
  <iframe src="/iframe.html"></iframe>
  <script src="/embed.js"></script>
</div>
```

It looks like the `webpackJsonp` call starts off `embed.js` even tho it doesn't use any vendor chunks at all. I assumed if there weren't any vendor imports, it wouldn't wrap the output. (Incorrect.)

```
embed.js:1 Uncaught ReferenceError: webpackJsonp is not defined
```

Is there a way to avoid the `webpackJsonp` call for `embed.js`? Ideally I'd want the following structure:

```
vendor.js
website.js (jsonp -- vendor.js)
iframe.js (jsonp -- vendor.js)
embed.js (*no jsonp*)
```

Is this possible?

**Comment by sokra** [comment]
> Is this possible?

Yes, use the `chunks` argument for the CommonsChunkPlugin.

**Comment by aj0strow** [comment]
@sokra thank you, that worked.

For anyone who finds this:

```js
new CommonsChunkPlugin({
  name: "vendor",
  chunks: [ "website", "iframe" ], 
})
```
