### ISSUE TITLE
webpack 2: Exported ES6 config function does not get called in

### ISSUE THREAD

**Issue by johanneslumpe** [webpack/webpack#2105]
When exporting an ES6 config function, webpack does not detect it as such, due to it being transpiled by babel into commonjs with a `default` prop on the `exports` object. Leaving the modules intact didn't work either, as this file is imported using node require, prior to webpack handling the file.

Could the solution be as simple as checking whether the required module has a `default` prop, which is a function?

**Comment by IngwiePhoenix** [comment]
Even when babel’ing your config, you can still use the module.exports object. Just use that instead of the export keyword - solves the problem.

**Comment by johanneslumpe** [comment]
@IngwiePhoenix Yeah I'm doing that, but I wanted to report this as it seems to be somewhat of a bug, given the fact that @sokra's examples show the use of a pure ES6 module. (https://gist.github.com/sokra/27b24881210b56bbaff7)

**Comment by sokra** [comment]
> Could the solution be as simple as checking whether the required module has a default prop, which is a function?

I thought so: https://github.com/webpack/webpack/blob/master/bin/convert-argv.js#L115-L117

**Comment by johanneslumpe** [comment]
@sokra Will send a PR as soon as I can. I think it might be enough to update L97-L99 to account for the es6 exported function and call that one.

**Comment by sokra** [comment]
merged
