### ISSUE TITLE
[Doc] is there a design document about webpack philosophy?

### ISSUE THREAD

**Issue by e-cloud** [webpack/webpack#2108]
i have been using webpack for a while and learned a lot of tutorial about how to use webpack and config it.
Now, i want to **dive** into its core and figure out its **excellent philosophy**.  But, yet i haven't found any blog or document with deep explanation in general.

So, i want to learn it from source code. However, i also found the `sloc` are nearly **20,000**. Without a general summary, it's hard and long time to finish the job.

Can anyone provide some help? Perhaps some **graphs** about the flow? Any guideline is welcomed.

**Comment by JohnnyZhao** [comment]
I need this documentation, too. Any suggested articles? Thanks.

**Comment by pksjce** [comment]
This issue was moved to webpack/webpack.io#112
