### ISSUE TITLE
source-list-map generates "undefined" if more mappings than lines

### ISSUE THREAD

**Issue by jgerigmeyer** [webpack/webpack#2111]
Given the following ``main.js`` file:

```js
function foobar () {
  return; // foo

}
```

And the following ``webpack-config.js``:

```js
module.exports = {
  entry: './main.js',
  output: {
    filename: 'out.js'
  },
  module: {
    loaders: [
      {
        test: /\.js$/,
        loader: 'babel'
      }
    ]
  },
  devtool: 'cheap-module-source-map'
};
```

Produces the following output file:

```js
/******/ ([
/* 0 */
/***/ function(module, exports) {

	function foobar() {
	  return; // foo
		}undefined
	

/***/ }
/******/ ]);
//# sourceMappingURL=out.js.map
```

Note the extra ``undefined``.

I've tracked it down to https://github.com/webpack/source-list-map/blob/master/lib/fromStringWithSourceMap.js#L21. In this example case, there are fewer ``lines`` (3) than ``mappings`` (4), which results in the final ``line`` being ``undefined``. I can only reproduce this when using ``babel-loader`` and webpack devtool ``cheap-module-source-map``. Additionally, the bug goes away if I remove the inline comment, or the empty newline before the closing brace.

I'm not sure if the root of this is actually a bug in how https://github.com/babel/babel-loader is generating sourcemaps, but at the very least it seems like https://github.com/webpack/source-list-map should protect against this possibility.

For a sample repo, see https://github.com/oddbird/webpack-babel-sourcemap.

**Comment by sokra** [comment]
> but at the very least it seems like https://github.com/webpack/source-list-map should protect against this possibility.

yep... do you want to create a PR to fix it?

**Comment by jgerigmeyer** [comment]
PR submitted: https://github.com/webpack/source-list-map/pull/1
