### ISSUE TITLE
Multiple Webpack entry points loaded

### ISSUE THREAD

**Issue by nwhite89** [webpack/webpack#2112]
I have a scenario where it is possible that multiple different entry points are loaded at the same time. These could be generated at different times and due to this ID's could conflict which can cause issues. Unfortunately there isn't anyway to ensure that they are generated together with common chunks etc. Is there a way to effectively namespace the id's generated for each different module with a unique id?

**Comment by Metallium** [comment]
try setting unique function name in output.jsonpFunction
```
output: {
        jsonpFunction: 'webpackJsonp' + Date.now()
}
```
http://webpack.github.io/docs/configuration.html#output-jsonpfunction

**Comment by nwhite89** [comment]
Ah Cheers :+1: I was thinking of module id's but looks like this will do the trick thanks

**Comment by folmert** [comment]
It's safer to use module's id as unique element, because output of `Date.now()` won't differ at all on fast machines if you're generating multiple bundles in one run. I've just tested it on my config and 4/5 of my bundles share the same jsonpFunction name.
