### ISSUE TITLE
Proposal: Profiles

### ISSUE THREAD

**Issue by IngwiePhoenix** [webpack/webpack#2116]
I see it from time to time, and it hits me too: the ability to use common settings, but only change a few for the difference of development or production builds.

That is why I would like to propose an addition to configuration: Profiles.
## Background

Suppose you have a library, and you want to output a minified and normal bundle. You'll have to either:
- Use two different config files
- Use three files with one exporting base config
- Export an array of objects containing the configs
- Use a config-management tool (there are some on NPM)

None of these options are optimal - and rather tend to confuse people. I see this happening a lot over on the Gitter chat - and I am also guilty of suggesting the multi-file approach ^^;

In my own case on the [BIRD3](https://github.com/DragonsInn/BIRD3) project, I keep restarting the server, just to turn uglifyjs either on, or off, whilst the webserver already very well knows when I want to see dev stuff, and when not. Appending `?dev` to the URL causes all sorts of minification and optimizations to be turned off, allowing me to verify that with and without these things still work - thus, I get to see what production will be like. This would be great to use with WebPack - but it's not that easy, unfortunately...
## Example

Let's return to the library idea to above. In fact, I do have a library called `o.o` currently burried inside BIRD3. But on release, I'll use WebPack to generate the minified bundle.

Assuming I want to build a basic bundle, and only use UglifyJS on the minified version, a configuration like this would be pretty obvious, to me.

``` javascript
var UglifyJS = require("webpack").optimize.UglifyJsPlugin;
var uglyConf = require("./uglifyjs.config");
module.exports = {
    entry: "./o.o.js",
    output: {
        path: "./dist"
    },

    // This is part of the proposal:
    profiles: {
        develop: {
            output: {
                filename: "o.o.dev.js"
            },
            // DevTool, soucemap, ...
        },
        minified: {
            output: {
                filename: "o.o.min.js"
            },
            plugins: [
                new UglifyJS(uglyConf)
            ]
        },
        regular: {
            // Not adding anything to it, to use default settings.
            output: {
                filename: "o.o.js"
            }
        }
    }
}
```

Obviously, this is very basic - no loaders, aliases, other plugins... just the bundle. Well, `o.o` is minimalistic anyway, so that's fine.

Now, to apply a profile:

Via the CLI, we'd introduce `--profile [...]` to allow selecting one. If none is selected, then **none should be loaded**. This makes up for perfect backwards compatibility to how we configure today.

Via the WebPack API:

``` javascript
var config = require("./webpack.config");
var webpack = require("webpack");

var compiler = webpack(config);
compiler.run(function(){}, {
  profile: "...", // name of profile to use
})
```

Passing a sort-of config object to `.run` allows us to load one compiler, but possibly execute multiple profiles if requested.
## Behavior

A profile, I bet you guessed, is a sub-configuration, that is deep-merged with the actual config. Really basic, but ont he other hand, really powerful. You could even use an IIFE to dynamically read profiles from disk and import them (using glob.sync and such), to allow dynamically extending the config. Well - thats a bit beyond the proposal here, but definitively something that could be useful.
### Errors

When a profile does not exist, WebPack should emit an error (`ProfileNotAvailable` or something) and tell the user to specify a valid one. If error details are enabled, we may as well use `Object.keys()` to show the user what profiles can be chosen.
### Multiple profile builds

It is debateable if we should allow the user to pass an array of profile names. We could utilize the MultiCompiler to load each "profiled" configuration that way, and allow all sorts of builds to perform simultaneously. useful for one-command-builds-all kinda use-cases, the dev-server or if you use a behavior similar to what BIRD3 does with `?dev` within the query.

Let me know what you think! I came up with this whilst just watching Gitter for a while :)
I am sure it would help quite a lot of people!

**Comment by sokra** [comment]
With webpack 2 you can pass a function taking one `env` argument:

``` js
export default function(env) {
  let base = {
    entry: "./o.o.js",
    output: {
      path: "./dist"
    }
  };

  switch(env) {
    case "develop":
      return {
        ...base,
        output: {
          ...base.output,
          filename: "o.o.dev.js"
        }
        // DevTool, soucemap, ...
      };
    case "minified":
      return {
        ...base,
        output: {
          ...base.output,
          filename: "o.o.min.js"
        }
        plugins: [
          new UglifyJS(uglyConf)
        ]
      };
    default:
      return {
        ...base,
        output: {
          ...base.output,
          filename: "o.o.js"
        }
        // Not adding anything to it, to use default settings.
      };
  }
}
```

``` text
webpack --env minified
```

**Comment by IngwiePhoenix** [comment]
Oh… That I obviously did not know. :o

And how would one pass an ENV in the Node API?

**Comment by dtothefp** [comment]
@IngwiePhoenix https://gist.github.com/sokra/27b24881210b56bbaff7 checkout configuration section

**Comment by SpaceK33z** [comment]
Closing since it was fixed with webpack v2.
