### ISSUE TITLE
Hot updates should ignore broken builds

### ISSUE THREAD

**Issue by gaearon** [webpack/webpack#2117]
If the build is broken, is there ever any reason to apply a hot update?

(Note: this issue is pretty much the same as #1105 but I understand the problem better now and there was no discussion there so let’s try formulating it again.)

I understand that `NoErrorsPlugin` exists to help alleviate this but it has a downside of serving the last successful bundle which can _really_ trip up people who aren’t familiar with this gotcha who refresh, see their app “working”, don’t notice there is an error in console, and can’t figure out why none of their new code has any effect. So I would prefer to avoid `NoErrorsPlugin`.

If I **don’t** use `NoErrorsPlugin` then hot reloading just breaks at the first bundle error:

<img width="458" alt="screen shot 2016-02-29 at 03 36 15" src="https://cloud.githubusercontent.com/assets/810438/13385174/d8cda990-de95-11e5-9d75-065ff5248c6a.png">

<img width="449" alt="screen shot 2016-02-29 at 03 36 19" src="https://cloud.githubusercontent.com/assets/810438/13385177/dfee3776-de95-11e5-9f68-fa623c16d80d.png">

After fixing the error, the update is just stuck:

<img width="294" alt="screen shot 2016-02-29 at 03 38 30" src="https://cloud.githubusercontent.com/assets/810438/13385199/fab6a5a2-de95-11e5-8f38-22282643e96e.png">

The main problem, as I see it, is that `hot-update.json` points to the hash of a broken build. **Does this ever make sense?** It’s not like you can cleanly apply it anyway. Can we just avoid pointing `hot-update.json` at broken builds?

**Comment by gaearon** [comment]
Locally, I was able to fix it by adding

```js
		if (options.skipUpdate) {
			hotCurrentHash = hotUpdateNewHash;
			hotSetStatus("idle");
			return callback(null, outdatedModules);
		}
```

in the beginning of `hotApply`. This allowed me to modify the custom hot client I use (https://github.com/glenjamin/webpack-hot-middleware) to pass `skipUpdate` for hashes that are known to contain errors.

This looks far from ideal solution but I wonder if you’d accept a PR implementing something like this.

**Comment by TheLarkInn** [comment]
@gaearon have you submitted a PR for this already, or were you concerned with whether or not @sokra would consider this PR first?

**Comment by gaearon** [comment]
I didn’t—I wasn’t sure what’s the correct way to address it.

**Comment by sokra** [comment]
ok I tried to fix it... at least for ES6 Modules.

**Comment by gaearon** [comment]
💯 Thank you!

**Comment by mikeengland** [comment]
Please can this fix get backported into Webpack v1? It looks like the commit went into v2.1.0-beta.16. Without this, Webpack dev server + the React Hot Reloader becomes quite painful to use!

**Comment by koddo** [comment]
I second to this. Please backport. HMR is unusable without this fix in v1.

**Comment by mikeengland** [comment]
@sokra I tried to upgrade to the latest webpack beta build (v25) and the latest webpack-dev-server. Although errors when misspelling a tag e.g. <Lnk> instead of <Link> show the React red box error, if you break a tag accidently like writing 'Link>', the error is shown in the console but then no further updates to the code are hot reloaded. Any idea why?
