### ISSUE TITLE
Can't find module within modulesDirectories

### ISSUE THREAD

**Issue by jeron-diovis** [webpack/webpack#2119]
webpack config:

``` js
resolve: {
    modulesDirectories: [
      "package_modules",
      "/path/to/app",
      "node_modules"
    ],
]
```

Option `resolve.root` is not defined.

Files tree:

```
/app
|- lib
|   \- index.js
|
\- my_package
      |- package_modules
      |     \- lib
      |          \- index.js
      |
      |- subfolder
      |     \- file_in_subfolder.js
      |
      \ - file_in_package.js
```

**lib/index**:
`export const foo = "foo"`;

**my_package/package_modules/lib/index**:
`export const bar = "bar"`;

**my_package/file_in_package**:

``` js
import * as obj from "lib";
console.log("lib in package root:", obj);
```

**my_package/subfolder/file_in_subfolder**:

``` js
import * as obj from "lib";
console.log("lib in package subfolder:", obj);
```

In console I have:

```
> lib in package root: { bar: "bar" }
> lib in package subfolder: { foo: "foo" }
```

Is it correct? I expected that it will be `{ bar: "bar" }` in both cases.
Changing import path to `lib/index` does not help.

**Comment by sokra** [comment]
It is correct.

**Comment by jeron-diovis** [comment]
So it works not exactly like node_modules does? I can't understand the logic.

**Comment by sokra** [comment]
`modulesDirectories` should not contain absolute paths. `/path/to/app` is wrong inside of `moduleDirectories`. `/path/to/app` should be inside of `resolve.root` or `resolve.fallback`.

**Comment by jeron-diovis** [comment]
Ok, got it.

My idea was to achieve following resolution order: `modulesDirectories` => `app root` => `node_modules` (to ensure that `node_modules` never overrides local app modules). It seems that the most correct solution will be to create one more `package_modules` folder at app root.

**Comment by sokra** [comment]
> It seems that the most correct solution will be to create one more package_modules folder at app root.

yep, that's the best solution with webpack 1.

with webpack 2 `modulesDirectories` `root` and `fallback` were merged into `modules`:

``` js
    modules: [
      "package_modules",
      "/path/to/app",
      "node_modules"
    ]
```

**Comment by jeron-diovis** [comment]
Wow :+1:  
From this moment I'm waiting for stable webpack 2 release  much more)

**Comment by jeron-diovis** [comment]
Playing with webpack 2 (2.1.0-beta.4), I implemented files structure as in topic and `modules` config as you described above. It works brilliant. 
Then, I renamed `lib` folder to `constants` folder everywhere in my files tree.
And my build crashed with this:
```
ERROR in ./~/constants-browserify/constants.json
Module parse failed: /path/to/project/node_modules/constants-browserify/constants.json Unexpected token (2:12)
You may need an appropriate loader to handle this file type.
| {
|   "O_RDONLY": 0,
|   "O_WRONLY": 1,
|   "O_RDWR": 2,
 @ ./src/index.js 5:17-37
```

After some debugging, I found the rule: everything from `node_modules` with `-browserify` suffix takes precedence before local modules. Other `node_modules` – no, I tried several. `-browserify` ones – yes.

Please explain what's going on here.

**Comment by jeron-diovis** [comment]
Actually, same happens even with the most simple configuration.

```
/
|- src
|  |- index.js
|  \- constants.js
\- webpack.config.js
```

**src/index.js**:
```js
console.log(require("constants"));
```

**src/constants.js**:
```js
module.exports = { foo: "foo" };
```

**webpack.config.js**:
```js
module.exports = {
	entry: "index.js",
	
	output: {
		filename: "build.js"
	},

	resolve: {
		modules: [
			__dirname + "/src"
		]
	}
};
```

`node_modules` are not included to `resolve.modules` at all. And still build fails with
```
ERROR in ./~/constants-browserify/constants.json
Module parse failed: /path/to/app/node_modules/constants-browserify/constants.json Unexpected token (2:12)
You may need an appropriate loader to handle this file type.
| {
|   "O_RDONLY": 0,
|   "O_WRONLY": 1,
|   "O_RDWR": 2,
 @ ./src/index.js 1:12-32
```

**Comment by sokra** [comment]
add the `json-loader`

**Comment by jeron-diovis** [comment]
How `json-loader` will prevent bundling external package `constants-browserify` instead of my own module `constants.js`?

**Comment by eisisig** [comment]
`constants-browserify` is is trying to load `/path/to/app/node_modules/constants-browserify/constants.json`... And webpack doesn't understand that until you have the right loader for that file type (.json)... Just as if something was trying to load a `*.less`or `*.jpg` file

That is not related to the first problem you posted. So I suggest installing json-loader to get past this

**Comment by jeron-diovis** [comment]
@eisisig @sokra Once again: in [this example](https://github.com/webpack/webpack/issues/2119#issuecomment-191726253) webpack is configured to search for modules **only** in `/path/to/app/src`, and `node_modules` are **not** included at all. So `require("constants")` in app module must resolve to `/path/to/app/src/constants.js`, isn't it?
And, anyway, I don't require `constants-browserify` in my code, I require just `constants` – **why** name 
`constants-browserify` considered matching this request?



> That is not related to the first problem you posted

Should I post this as separate issue?

**Comment by sqal** [comment]
@jeron-diovis I have encountered exactly the same problem. It's weird that webpack tries to import `node_modules/constants-browserify/constants.json` and not my local `constants/index.js`. When i change folder name from constants to whatever, it works as it should be. Did you perhaps solve your problem?

**Comment by jeron-diovis** [comment]
@sqal Nope, I have no idea what to do with this except of, yes, renaming the folder.
As I noticed above, it's reproducible not only for `constants`, but for all `whatever-browserify` modules.

So I'm just still waiting while @sokra come and explain us what's going on.

**Comment by bebraw** [comment]
Can you try against current webpack 2 rc? It handles JSON now.

**Comment by valerybugakov** [comment]
@bebraw same issue here with `webpack@2.2.1`

**Comment by bebraw** [comment]
@valerybugakov Any chance for a repository to study to confirm the issue?

**Comment by valerybugakov** [comment]
I can create one later today. But maybe you know a way to ignore this module in the client code?

**Comment by bebraw** [comment]
@valerybugakov Ok. There are things like `module.noParse`, but I would need to see some code to say more.

**Comment by valerybugakov** [comment]
@bebraw Short version of what I have right now: 
```js
import { ENTITIES } from 'constants';
```
it's transpiled into
```js
var _constants = __webpack_require__("./node_modules/constants-browserify/constants.json");
```
And webpack config:
```js
// some imports and env stuff here...

module.exports = {
  stats,
  devServer: {
    stats,
    hotOnly: true,
    contentBase: path.join(__dirname, 'dev')
  },

  devtool: dev ? 'eval' : false,

  entry: [
    path.join(__dirname, '../index.web.js')
  ],

  output: {
    filename: 'bundle.js'
  },

  module: {
    rules: [
      {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [
          path.resolve(__dirname, '../src'),
          path.resolve(__dirname, '../node_modules/react-native-vector-icons'),
          path.resolve(__dirname, '../node_modules/react-native-drawer'),
          path.resolve(__dirname, '../node_modules/react-native-popup-dialog'),
          path.resolve(__dirname, '../node_modules/react-native-modalbox'),
          path.resolve(__dirname, '../node_modules/react-native-flip-card'),
          path.resolve(__dirname, '../node_modules/react-native-snap-carousel'),
        ],
        options: { cacheDirectory: true },
      },
      {
        test: /\.(gif|jpe?g|png|svg|tff)$/,
        loader: 'url-loader',
        options: { name: '[name].[hash:16].[ext]' }
      },
      {
        test: /\.ttf$/,
        loader: 'file-loader', // or directly file-loader
        include: [
          path.resolve(__dirname, '../node_modules/react-native-vector-icons'),
          path.resolve(__dirname, '../src/assets/icons'),
        ]
      },
      {
        test: /\.worker.js$/,
        loader: 'worker-loader',
        options: { inline: true }
      },
      {
        test: /\.glsl$/,
        loader: 'shader-loader'
      },
    ],
  },

  resolve: {
    extensions: ['.js', '.web.js'],
    alias: {
      'react-native': 'react-native-web',
    },
    modules: [
      path.resolve(__dirname, '../src'),
      path.resolve(__dirname, '../node_modules'),
    ],
  },

  plugins,
};
```

**Comment by valerybugakov** [comment]
```js
  module: {
    noParse: /constants-browserify/,
  },
```
Didn't help :(
Got same the transpilation result.

**Comment by bebraw** [comment]
@valerybugakov Why `import { ENTITIES } from 'constants';` instead of `import ENTITIES from 'constants';` or `import * as ENTITIES from 'constants';`?

**Comment by valerybugakov** [comment]
@bebraw actually there're more destructured variables `import { ENTITIES, STICKY_CATEGORIES, ... } from 'constants';`

**Comment by bebraw** [comment]
@valerybugakov Ok, basically this feels like a JSON and ES6 module syntax specific problem. Could you open a separate issue with a little example we can run? You can also try the old `require` syntax to confirm. Perhaps some handling is missing.

**Comment by valerybugakov** [comment]
@bebraw Ok, let me try `require`.

**Comment by valerybugakov** [comment]
@bebraw no, same result:
```js
const constants = require('constants')
// transpiled into
var constants = __webpack_require__("./node_modules/constants-browserify/constants.json");
```

**Comment by bebraw** [comment]
@valerybugakov Ah... I understand better now. You basically want to inline the result (`var constants = { ENTITIES: ..., STICKY_CATEGORIES: ... }`), right? Importing might not be the way then. Look up solutions like `DefinePlugin`. You could perform a literal replacement like that through them.

**Comment by valerybugakov** [comment]
Lol, I found a workaround, but will open an issue with example later.
```js
    alias: {
      'react-native': 'react-native-web',
      'constants': path.resolve(__dirname, '../src/constants'),
    },
```

**Comment by valerybugakov** [comment]
@bebraw I think `DefinePlugin` has a little bit different purpose, I use it to define environment variables. In `constants.js` I have lots of string/array exports (similar to Redux action types).
```js
export const ENTITIES = ['some', 'entities', 'here', ...]
export const STICKY_CATEGORIES = [...]
```

**Comment by bebraw** [comment]
@valerybugakov Yeah, `DefinePlugin` would be sketchier for sure. Reading back, maybe `import { ... } from 'constants';` should have been `import { ... } from 'browserify-constants';`, but I'l know more after you open that issue.

**Comment by valerybugakov** [comment]
@bebraw yeah, will do that. Thanks for helping out :)

**Comment by valerybugakov** [comment]
@bebraw [done](https://github.com/webpack/webpack/issues/4159)

**Comment by jeron-diovis** [comment]
What is the status of this issue?
Is [this](https://github.com/webpack/webpack/issues/4159#issuecomment-276639319) a final recommended solution?
