### ISSUE TITLE
DefinePlugin NODE_ENV not visible to babel-loader

### ISSUE THREAD

**Issue by acthp** [webpack/webpack#2121]
Using DefinePlugin to set process.env.NODE_ENV, it remains unset in babel-loader. It is available in other steps, as webpack is able to drop requires inside conditionals checking NODE_ENV.

babel-loader explicitly checks for process.env.NODE_ENV in order to pass it on to babel, but it is undefined.

**Comment by danpantry** [comment]
Could you provide your `webpack.config.js`?

**Comment by dtothefp** [comment]
@acthp Babel loader uses the BABEL_ENV or NODE_ENV of the actual process that envies Babel. Therefore you need to set it via node and not Webpck unless I'm confused about your question

**Comment by acthp** [comment]
Ah, that was it, thanks. In ```webpack.config.js``` If I do

```javascript
process.env.NODE_ENV = '"production"'
```

in addition to configuring DefinePlugin, it is available to babel-loader as well as the other processors.

**Comment by imjared** [comment]
@acthp can you post your full webpack config or the parts affecting this issue? having similar problems and looking for something that works

**Comment by mzgoddard** [comment]
@imjared DefinePlugin transforms code parsed by webpack after all loaders. It doesn't do anything to the global environment. You can either literally set NODE_ENV in your `webpack.config.js` file as a single statement or set the environment when running webpack.

```js
// webpack.config.js
process.env.NODE_ENV = 'production';

module.exports = {
  entry: './index.js',
  // ...
  plugins: [
    new DefinePlugin({
      'process.env.NODE_ENV': '"production"',
    }),
  ],
};
```

OR

```shell
NODE_ENV=production webpack --config=webpack.config.js
```

If there is code that is going into the webpack'd source that tests process.env.NODE_ENV, you'll want both DefinePlugin and the actual shell environment variable to be set.

**Comment by joeLloyd** [comment]
what about using dotenv? with it always fail if you use that?
