### ISSUE TITLE
Webpack 2 resolve changes between 2.0 and 2.1

### ISSUE THREAD

**Issue by b4stien** [webpack/webpack#2122]
Hey,

Some changes between 2.0 and 2.1 broke the import of some modules (for instance https://github.com/twbs/bootstrap/blob/v4-dev/dist/js/umd/modal.js). I'm afraid I'm not familiar enough to tell what changed and if the problem comes from said modules or webpack.

I put up a small demo at https://github.com/b4stien/showcase_webpack_resolve, it's working flawlessly with webpack v2.0.7-beta but it's broken with v2.1.0-beta.4 (starting from v2.1.0-beta.0)... It seemed to be coming from the `require('./util')` (https://github.com/twbs/bootstrap/blob/v4-dev/dist/js/umd/modal.js#L5).

Feel free to redirect me to some other issue if it's already tracked somewhere... Or if I don't understand something.

**Comment by b4stien** [comment]
I realise my "bug report" is cryptic... After some more investigations it's actually https://github.com/twbs/bootstrap/blob/v4-dev/dist/js/umd/modal.js#L3 which behaviour is changing.

With webpack 2.0 the "real" `_util` is passed to https://github.com/twbs/bootstrap/blob/v4-dev/dist/js/umd/modal.js#L13 whereas in webpack 2.1 an empty object is passed.

**Comment by TheLarkInn** [comment]
@b4stien have you done any further investigating on this issue since reporting. Would you be willing to test this in 2.1.0-beta.14?

**Comment by b4stien** [comment]
It's working with beta 14 (didn't try the previous versions).

**Comment by TheLarkInn** [comment]
Thank you!
