### ISSUE TITLE
[Suggestion] Presets for easier configuration

### ISSUE THREAD

**Issue by kripod** [webpack/webpack#2127]
Getting familiar with webpack and its configuration options can be a tough and time-consuming task. As I saw the [react-project](https://github.com/ryanflorence/react-project) repository, I realized that there is a need for presets in webpack.

Presets shall work similar like [presets in Babel](http://babeljs.io/docs/plugins/#presets): They should offer sane defaults for plugins and module loaders.

For example, take the following `webpack.config.js` file:

``` js
module.exports = {
  presets: [ 'babel', 'react-hot-loader', 'optimize' ],
  entry: './src/public/main.jsx',
  output: {
    path: __dirname + '/build/public'
  }
};
```

In this particular case, 3 presets are used:
- `babel` is used for automatically transpiling every imported JS(X) file, except files at `/node_modules/`.
- `react-hot-loader` is used to flawlessly configure hot module replacement for every imported module, including the entry point(s). HMR shall not be activated during runtime whether `NODE_ENV === 'production'`.
- `optimize` is used for automatically utilizing CommonsChunkPlugin, DedupePlugin and OccurenceOrderPlugin.

While the configuration file above should be enough to get started with Babel (ES2015, JSX), React, hot module replacement and most of the production optimizations enabled, power-users may want to tweak the behavior of each preset:

``` js
module.exports = {
  presets: [
    { name: 'babel', exclude: /vendor/ }, // By default, /node_modules/ was excluded instead of /vendor/
    { name: 'react-hot-loader' },
    { name: 'optimize', dedupe: false } // Disable optimizations provided by DedupePlugin
    ]
  },
  entry: './src/public/main.jsx',
  output: {
    path: __dirname + '/build/public'
  }
};
```

Please be aware that custom module loaders and plugins could still be used:

``` js
module.exports = {
  presets: [ 'babel', 'react-hot-loader', 'optimize' ],
  entry: './src/public/main.jsx',
  output: {
    path: __dirname + '/build/public'
  },
  module: {
    loaders: [
      { test: /\.json$/, loaders: [ 'json' ] },
      { test: /\.css$/, loaders: [ 'style', 'css' ] },
      { test: /\.(png|jpg)$/, loaders: [ 'url?limit=8192' ] }
    ]
  }
};
```

**Comment by bebraw** [comment]
I developed something like this at [webpack-presets](https://github.com/survivejs/webpack-presets).

**Comment by kripod** [comment]
@bebraw Your implementation is great, but I would love to see built-in support for plugins. That would reduce the complexity of configuration.

**Comment by bebraw** [comment]
@kripod As far as I understand, changes like this would be something for webpack 3. The scope of webpack 2 is more about internals, ES6 support, and such. So we probably have to solve it in user space for now.

It would be fairly easy to adapt **webpack-presets** to your scheme. You would just do `module.exports = webpackPresets({... configuration goes here ...});` and it would return configuration you might expect. We could also validate the configuration through another function and so on.

**Comment by bebraw** [comment]
Let's close this. It's better to solve this in user space for now (separate layer on top of webpack). We may revisit ideas like this in webpack 3.
