### ISSUE TITLE
'//@ sourceURL' and '//@ sourceMappingURL' are deprecated, please use //# sourceURL= //# sourceMappingURL

### ISSUE THREAD

**Issue by morenoh149** [webpack/webpack#2128]
Am I the only one seeing this in chrome canary 51?

`'//@ sourceURL' and '//@ sourceMappingURL' are deprecated, please use '//# sourceURL=' and '//# sourceMappingURL=' instead.`

<img width="1052" alt="screen shot 2016-03-02 at 11 21 51 am" src="https://cloud.githubusercontent.com/assets/587438/13466669/ff73f5ca-e068-11e5-8c73-867edc527f18.png">

https://developers.google.com/web/updates/2013/06/sourceMappingURL-and-sourceURL-syntax-changed

**Comment by morenoh149** [comment]
ah I see it's a dupe of https://github.com/webpack/webpack/issues/91

**Comment by emamul** [comment]
In which technology you have developed this application.If MVC then don't allow to render by default js file like site.js.
