### ISSUE TITLE
make webpack fail on module parse errors

### ISSUE THREAD

**Issue by shaharmor** [webpack/webpack#2130]
Hi,

I'm seeing this error:

```
WARNING in ./src/utils/__tests__/some.test.js
Module parse failed: /projects/src/utils/__tests__/some.test.js Line 4: Unexpected token =>
You may need an appropriate loader to handle this file type.
| 
| describe('something', function() {
|   it('does something', function() => {
|     expect([]).filter((e) => {
|       return e === true;
 @ ./src \.test\.js
```

I know the parsing happens because of the `=>` which is ES6, but i want the warning to cause throw an error and not a warning so the build/test won't continue.

I think its coming from the webpackMiddleware.
Is that possible?

**Comment by sokra** [comment]
fixed in webpack 2. you can use `--bail` for webpack 1
