### ISSUE TITLE
I can`t use the css imported in my component , but use link is well . 

### ISSUE THREAD

**Issue by WenXuanYuan** [webpack/webpack#2133]
I used import to use my css file , but the html element can`t use the style I defined , when I used link to import my css file , all is well, would you please tell me the reason. Thank you!

**Comment by WenXuanYuan** [comment]
I find in my css , code wrote like this
.anticon-inbox:before {
  content: "\E67B";
}
But in the css packaged by webpack it changed to
.index__anticon-inbox___3i9qX:before{
  content:"\E67B"
}
The prefix and suffix was added, what should i do?

**Comment by iktl** [comment]
It sounds like you're using CSS Modules in your loader, which is hashing your CSS class names. To use that, you would want to use something like:

`import styles from './myStyles.css'`

And then use those styles on a component like:

<div className={styles.unhashedClassName} />

**Comment by WenXuanYuan** [comment]
I want to write code like this
<div className='unhashedClassName' />
what should I do?

**Comment by eisisig** [comment]
You recommend you read about webpack css-loader using css-modules [https://github.com/webpack/css-loader#css-modules](https://github.com/webpack/css-loader#css-modules) to get an understanding what is involved. It's a different way of thinking so I'd read more about before starting

**Comment by WenXuanYuan** [comment]
@eisisig You solved my problem perfectly, Thank you !
