### ISSUE TITLE
Re-usable JS artifact that can be used with different variables

### ISSUE THREAD

**Issue by yannispanousis** [webpack/webpack#2135]
Dear all,

This is a question on how to build / compile some Javascript modules into an entrypoint **once** and then be able to re-use the output in different environments, with potentially different configurations in each one.

A quick search on ways to pass variables into modules produces:

1. the webpack DefinePlugin
2. aliasing an environment-specific configuration module to have a fixed name in the Javascript code

However both of the above require that the configurations are known in advance and in order to be changed the whole entrypoint needs to be re-compiled.

Is there a way around this?

I'm wondering whether to look into the direction of DllPlugin and DllReferencePlugin, but I'd like to hear some more input on this in case I'm missing something simpler.

End-goal: I want to end up with a Docker container that houses a compiled version of the app and can be given different variables to run with, but not have to be recompiled.

Thanks in advance!

Yannis

**Comment by sokra** [comment]
> the webpack DefinePlugin

use a runtime variable here instead.

> aliasing an environment-specific configuration module to have a fixed name in the Javascript code

use a switch here instead.

**Comment by yannispanousis** [comment]
Hi @sokra thanks for your reply!

both your suggestions sound like exactly what I need, but

re DefinePlugin: I can't see a `runtime` option on the DefinePlugin parameters or something similar. How can I achieve a runtime variable?

re aliasing configuration module: that also sounds like what I need but given a compiled JS entrypoint I don't know how to abstract that concept. Are we assuming the use of the DllPlugin?

Maybe I'm missing something obvious so sorry about that!

Yannis

**Comment by ipanousis** [comment]
We've chosen to abstract this by a fixed name JS file that gets imported at runtime by HTML, and we can set all our variables in there. Thanks for your help!! Feel free to close the question

**Comment by yannispanousis** [comment]
We've chosen to abstract this by a fixed name JS file that gets imported at runtime by HTML, and we can set all our variables in there. Thanks for your help!! Feel free to close the question

Yannis

**Comment by mknapik** [comment]
@yannispanousis Could you share an example configuration which solved your problem?
That would be very helpful to implement our delivery pipeline efficiently.
