### ISSUE TITLE
Webpack web-workers loader not working

### ISSUE THREAD

**Issue by xavibonell** [webpack/webpack#2138]
Hi, I'm building an app using webpack, which it's been incredibly helpful so far,  but now I need to add some web workers into the mix, and I tryed using a built-in plugin to load them, but I followed the example [here](https://github.com/webpack/webpack/tree/master/examples/web-worker), the official repository, and I couldn't make it work.
My webpack.dev.js looks like this: 

```
import webpack              from 'webpack';
import assign               from 'object-assign';
import webpackDevMiddleware from 'webpack-dev-middleware';
import webpackHotMiddleware from 'webpack-hot-middleware';

import prodCfg              from './webpack.prod.config.js';

var ExtractTextPlugin = require("extract-text-webpack-plugin");
var DEBUG = process.env.NODE_ENV !== 'production' ? true : false;
var styles = 'css!less';

Object.assign = assign;

export default function (app) {
  const config = Object.assign(prodCfg, {
    devtool: 'cheap-module-inline-source-map',
    entry:  
     [
      'webpack-hot-middleware/client',
      './client',
      'styles/main.less'
    ],
    module: {
      loaders: [
        {
          test:    /\.jsx?$/,
          exclude: /node_modules/,
          loader:  'babel',
          query:   {
            plugins: [
              [
                'react-transform', {
                transforms: [{
                  transform: 'react-transform-hmr',
                  imports:   ['react'],
                  locals:    ['module']
                }]
              }
              ]
            ]
          }
        },
        {
          test: /\.css$/,
          loader: DEBUG ? 'style!' + styles : ExtractTextPlugin.extract(styles)
        },
        { 
          test: /\.less$/, 
          loader: DEBUG ? 'style!' + styles : ExtractTextPlugin.extract(styles)
        }
      ]
    },
    plugins: [
      new webpack.optimize.OccurenceOrderPlugin(),
      new webpack.HotModuleReplacementPlugin(),
      new webpack.NoErrorsPlugin(),
      new ExtractTextPlugin("style.css", {allChunks: true })
    ],
    worker: {
      output: {
        filename: "hash.worker.js",
        chunkFilename: "[id].hash.worker.js"
      }
    }
  });

  const compiler = webpack(config);

  app.use(webpackDevMiddleware(compiler, {noInfo: true, publicPath: config.output.publicPath}));
  app.use(webpackHotMiddleware(compiler));
}
```

and when I try to load the file I try it like this:
`
var Worker = require("worker!worker.js");`

It would never find the file, the only files exported by webpack are the bundle.js and the style.css, it looks like the worker loader is not loading anything at all.

Any help would be very welcomed! Thank you very much in advance!

**Comment by fresheneesz** [comment]
Try `require("worker-loader!worker.js")`. I noticed that using the shortened loader name wasn't working for me. @sokra Should we be able to use the shortened loader name (without "-loader") ?

**Comment by sokra** [comment]
> @sokra Should we be able to use the shortened loader name (without "-loader") ?

yes, but there is a bug and it doesn't prefer `worker-loader` over `worker` if both are installed. maybe that's the problem.

**Comment by xavibonell** [comment]
Hi @sokra, I tried to uninstall worker-loader but that was not the issue, still not working. My file is in the root and is called worker.js . Is that the right notation then? All the [id].hash. notation makes me feel uncomfortable and i'm not sure if I'm doing it right. Is there any working example out there a part the one inside the plugin examples? Thanks again for you patience!

**Comment by xavibonell** [comment]
@sokra, is there a way to export a bundle without the bootstrap bit added by webpack? Im using CommonsChunkPlugin to try to create a worker separate file, since worker plugin doesn't work for me, but it comes with a lot of stuff added by the plugin (the webpack bootstrap), so is there any way to export the plain file?
Thanks again!

**Comment by viskin** [comment]
What helped me a lot in my struggle with worker-loader was adding this loader to webpack configiration:
```
loaders: [
...
 {
    test: /worker\.js$/,
    loader: 'worker'
  },
]
```

**Comment by viskin** [comment]
This worked for me:

```
const Worker = require('worker-loader?name=worker_name.worker.js!./worker_name.worker');
```

This will generate worker_name.worker.js in output folder. No hash needed.
