### ISSUE TITLE
EnvironmentPlugin is not documented

### ISSUE THREAD

**Issue by axelson** [webpack/webpack#2139]
Mentioned here: https://github.com/mjohnston/envify-loader/issues/1

EnvironmentPlugin

## How to use

```
{
  plugins: [
    new webpack.EnvironmentPlugin([
      "NODE_ENV", "SECRET_KEY"
    ])
  ]
}
```

Then use in your code with `process.env.NODE_ENV` or `process.env.SECRET_KEY`

Documentation should be added https://github.com/webpack/docs/wiki/internal-webpack-plugins and https://webpack.github.io/docs/plugins.html (IMO)

**Comment by sokra** [comment]
Could you add it please? It's a wiki and everybody can edit it.

**Comment by zdelagrange** [comment]
added, issue can be closed.

https://github.com/webpack/docs/wiki/list-of-plugins#environmentplugin
