### ISSUE TITLE
Strange Behavior of require.ensure

### ISSUE THREAD

**Issue by marvinscharle** [webpack/webpack#2143]
For a project it is necessary to dynamically require / import components based on user inputs. Our team encountered a strange behavior of `require.ensure` that made it impossible for us to import components dynamically. 

For me, this looks like a bug of webpack, but I'm not sure and I'd like to discuss this with you. 

I prepared a [webpack app that displays the issue](https://github.com/marvinscharle/angular2-webpack-starter). 

The component [`ComponentLoader `](https://github.com/marvinscharle/angular2-webpack-starter/blob/master/src/app/ComponentLoader/ComponentLoader.ts) contains a few approaches to load one component dynamically based on a method argument.

The strange thing is calling this method
```typescript
   public static loadComponent2(componentName:string):Observable<Function> {
        var path = `../${componentName}/${componentName}`;

        return Observable.create((observer:Subscriber<Function>) => {
            require.ensure([], (require) => {
                var response = require(path);
                console.log(response);
            })
        });
    }
```

with `componentName="Component1"` results in `Uncaught Error: Cannot find module '../Component1/Component1'` but replacing the `var path` with `"../Component1/Component1"` results in a successful import of Component1 (see `loadComponent4()`). 

We could reproduce this error every time we use a variable to describe `path` in `require(path)`. Is this the intended behavior of `require` / `require.ensure`? What can we do to avoid this issue and dynamically import components?

Thank you in advance!
Marvin

**Comment by taurose** [comment]
Here's what I noticed:

* you have to put the path expression directly inside the require statement: `` var response = require(`../${componentName}/${componentName}`) ``
* project-relative paths like in your `loadComponent1` are not supported out of the box
* with a dynamic require path like `` `../${componentName}/${componentName}` ``, webpack will include all your files in the app (`..`) folder; it's not sophisticated enough to detect that you used the same variable twice and included a path separator (or even which modules you try to load during runtime). I'd suggest doing either
  * put all components you want to load like that into a common folder and use a path like `` `../components/${componentName}/${componentName}` ``
  * use `require.context` inside `require.ensure` and write a regex for the components
  * try to avoid dynamic requires in the first place, and use `bundle-loader` or `promise-loader` to better express your dependencies

**Comment by marvinscharle** [comment]
Thanks for the quick reply, @taurose!

I tried two of your suggestions: 

- putting `path` directly into `require()` crashes completely so that not even `console.log()` is displayed on the console [(see `loadComponent5()`)](https://github.com/marvinscharle/angular2-webpack-starter/commit/6f1693e4f1ed5e87d0f3928db219f1ba5e746750#diff-e344bf36061d72ce7a20f07325a2b9dbR85). Yet the following warning is displayed: 
```
Critical dependencies:
50:12-19 require function is used in a way in which dependencies cannot be statically extracted
@ ./src/app/ComponentLoader/ComponentLoader.ts 50:12-19`
```

- putting components to load in a subdirectory (`loadComponent6()`) works without issues. 

So this issue is solved in terms of handling dynamic require paths. But I still think that the behavior is some sort of strange, requiring dynamic components being in a subdirectory.

**Comment by taurose** [comment]
> putting path directly into require() crashes completely so that not even console.log() is displayed on the console (see loadComponent5()).

That's because the require statement will cause your test files to be included as well, but since those are excluded from transpiling, the browser runs into parsing errors.

> But I still think that the behavior is some sort of strange, requiring dynamic components being in a subdirectory.

Not sure what you'd expect. It needs to bundle all possible files that could be included via the dynamic require, and the most obvious way to limit that space is to give webpack a path prefix. It should also be easier to keep track of what's being included for developers. Currently, your dynamic require could also load `about/about` and `home/home`.

If you really need more flexibility you can use a regex via `require.context`:

```js
    public static loadComponent7(componentName:string):Observable<Function> {
        console.log("loadComponent7");
        return Observable.create((observer:Subscriber<Function>) => {
            require.ensure([], (require) => {
                var context = require.context('..', true, /^\.\/([^/]+)\/\1$/);
                var response = context(`./${componentName}/${componentName}`);
                console.log(response);
            })
        });
    }
```

**Comment by marvinscharle** [comment]
Thank you for your help, @taurose!
