### ISSUE TITLE
If error in package.json webpack returns error Cannot resolve 'file' or 'directory' about entry file

### ISSUE THREAD

**Issue by joeshub** [webpack/webpack#2150]
Cannot resolve 'file' or 'directory' is very confusing when you have an error in your package.json file.

Only way to actually see the error is by running using --display-error-details

**Comment by tarang9211** [comment]
Hey! Is this still open? I'd like to help out as my first PR on this repo.

**Comment by TheLarkInn** [comment]
Yup still open!! I'm not specifically sure how to reproduce this so I'm not sure where in the code to guide you. @bebraw are you familiar with this?

**Comment by tarang9211** [comment]
Awesome!

**Comment by bebraw** [comment]
> Yup still open!! I'm not specifically sure how to reproduce this so I'm not sure where in the code to guide you. @bebraw are you familiar with this?

Nope. You would have to walk through the code to tell any better. Look up where webpack refers to package.json.

**Comment by tarang9211** [comment]
So should I go through the entire src code?

**Comment by bebraw** [comment]
One option would be to walk through the code with a debugger till you get to the error. That would reveal the place to tweak most likely. It takes some setup to do this, but the process should be covered online.

**Comment by tarang9211** [comment]
@bebraw walk through the entire source code? Which process are you referring to?

**Comment by bebraw** [comment]
@tarang9211 Here's the [basic idea](https://medium.com/webpack/webpack-bits-learn-and-debug-webpack-with-chrome-dev-tools-da1c5b19554).

**Comment by tarang9211** [comment]
@bebraw awesome thanks! i got the setup done. I have a sample project that is using react with webpack. should I intentionally create an error in my package.json and then start the debugger?

**Comment by bebraw** [comment]
@tarang9211 Yeah, that sounds like a plan.

**Comment by tarang9211** [comment]
@bebraw so I was able to reproduce this successfully on a small project that is using webpack. Any idea how I should go about fixing it?

**Comment by bebraw** [comment]
@tarang9211 I'm thinking raising a good error as early as you detect the situation would be good enough for a PR.

**Comment by tarang9211** [comment]
@bebraw i can't seem to find where the package.json is being parsed or checked for errors. any idea?

**Comment by bebraw** [comment]
@tarang9211 Can you push the project somewhere? Easier to tell what's going on.

**Comment by tarang9211** [comment]
@bebraw I have not made any code changes yet. This is the `package.json` I am using https://github.com/tarang9211/ReduxBookList/blob/master/package.json#L12

On that line, instead of the comma, i replaced it with a semi colon to get the error to be thrown.

**Comment by tarang9211** [comment]
@bebraw any thoughts on my comment above?

**Comment by bebraw** [comment]
@tarang9211 Not really. You would have to see where webpack throws and study the backtrace to understand where to manage it better.

**Comment by yeskunall** [comment]
Is this issue still of concern? I don't see a PR that explicitly references this issue, so I'm guessing the problem still exists?

If it's already fixed, don't pay heed to my comment. Just making sure the bot does not close unresolved issues. 😁

**Comment by donocode** [comment]
I was unable to reproduce this, the current error message points to invalid syntax in the package.json

Tested with webpack@3.5.5 and node@6.11.1

**Comment by yeskunall** [comment]
Guess it's safe to close, then. Don't really know who to ping, so I guess I'll let @sokra close this issue.
