### ISSUE TITLE
Wrong proxy documentation

### ISSUE THREAD

**Issue by 0x80** [webpack/webpack#2152]
In the current documentation it is suggested that you configure the proxy using a path as key. I could only get it to work when you pass it an array of objects like this:

```javascript
proxy: [{
      path: new RegExp('/api/(.*)'),
      rewrite: rewriteUrl('/api/$1'),
      target: 'http://localhost:9000/'
    }],
```

**Comment by sokra** [comment]
You can edit the documentation with the button on the top right corner.

**Comment by pksjce** [comment]
This issue was moved to webpack/webpack.io#150
