### ISSUE TITLE
"stats" from config file are ignored

### ISSUE THREAD

**Issue by mdebbar** [webpack/webpack#2153]
When I tried providing a stats object inside `webpack.config.js` it didn't work. When I looked at [this code](https://github.com/webpack/webpack/blob/master/bin/webpack.js#L182), I thought `config.stats.errorDetails = true` should work, but it didn't. After some debugging, I found that [this line](https://github.com/webpack/webpack/blob/master/bin/webpack.js#L138) always returns an empty object, regardless of the presence of `options.stats`. I guess `Object.create()` is not the right function to use here (or maybe I'm missing something obvious).

**Comment by sokra** [comment]
> I found that this line always returns an empty object

It does return an empty object with prototype set to your stats object. console.log doesn't display that.

**Comment by mdebbar** [comment]
@sokra I see. But still `stats.errorDetails=true` doesn't have any effect. Is it supposed to work?

**Comment by sokra** [comment]
This is an old issue. I guess the problem was solved in the meantime. If not please open a new issue.
