### ISSUE TITLE
webpack error，  Module not found: Error: Cannot resolve module 'react' in xxx

### ISSUE THREAD

**Issue by notek** [webpack/webpack#2155]
hi，I used webpack to build the react project when I encountered an error：
![image](https://cloud.githubusercontent.com/assets/3304247/13624574/69f38786-e5ea-11e5-9a4a-810bea099d7a.png)

I have already installed react，Don't know why webpack can't find it....

this is webpack configure：
![image](https://cloud.githubusercontent.com/assets/3304247/13624708/725231a6-e5eb-11e5-9ac9-0c9b4294d1c4.png)
![image](https://cloud.githubusercontent.com/assets/3304247/13624712/772ab2fc-e5eb-11e5-8506-5755a8b90308.png)

this is my package.json file:

![image](https://cloud.githubusercontent.com/assets/3304247/13624755/ebd01e1c-e5eb-11e5-9354-190d27fd6fe7.png)

webpack version is 1.12.14

react version is 0.14.7

Why doesn't he work? Obviously have react, why can not find?

Who can help me? be deeply grateful!!

**Comment by bebraw** [comment]
How are you referring to react at your code? Any chance for a standalone example?

**Comment by sokra** [comment]
from http://webpack.github.io/docs/configuration.html#resolve-extensions

> An array of extensions that should be used to resolve modules. For example, in order to discover CoffeeScript files, your array should contain the string ".coffee".

> Default: ["", ".webpack.js", ".web.js", ".js"]

> IMPORTANT: Setting this option will override the default, meaning that webpack will no longer try to resolve modules using the default extensions. **If you want modules that were required with their extension (e.g. require('./somefile.ext')) to be properly resolved, you must include an empty string in your array.** Similarly, if you want modules that were required without extensions (e.g. require('underscore')) to be resolved to files with “.js” extensions, you must include ".js" in your array.**

**Comment by notek** [comment]
Well, it has solved the problem now.

Because the webpack resolve option value of extensions JSX in webpack and JS, will add the suffix to the default, can not find the file.

thanks all. @sokra Special thanks for giving me inspiration.

**Comment by AndrewStobie** [comment]
How exactly did you solve this problem? I'm still getting this issue with your proposed fix
