### ISSUE TITLE
WatchIgnorePlugin useless for files inside a watched directory

### ISSUE THREAD

**Issue by carljm** [webpack/webpack#2156]
If you create your own context using `require.context`, webpack tells the file watcher to watch that entire directory.

I have `WatchIgnorePlugin` configured to ignore certain file patterns (Emacs lock and auto-save files), but when these files appear inside a watched directory, the underlying watcher always considers it a change to the directory, and since the directory path itself doesn't match an ignore pattern, it still triggers a rebuild.

It seems like a fix might require a better implementation of `WatchIgnorePlugin`. Rather than just filtering the explicitly-given files and dirs to be watched against the ignore patterns once, what it should really do is pass an `ignored` function in the options all the way down into the underlying watcher (chokidar), which would allow chokidar to properly ignore changes to files that match the ignore patterns even if those files are newly-added within a watched directory, rather than having been in the explicit files-to-watch list.

**Comment by gbakernet** [comment]
It's worth also mentioning that contexts will be generated for dynamic requests

If you do something like this, you will be affected by this issue.
```javascript
require("./template/" + name + ".jade");
```

More on this in the docs. https://webpack.github.io/docs/context.html

I've removed some dynamic requires in my project (I was able to) to avoid this issue.
