### ISSUE TITLE
Minification of CSS in -p mode removes -moz/-o/-ms rules

### ISSUE THREAD

**Issue by robinsving** [webpack/webpack#2158]
I was testing out Webpack with the `-p` flag and got some weird results in my CSS compared to my regular page. One of these errors was the aparent removal of CSS code.

CSS in my .css-file:
```
.systembar::before {
  background: #0066b3;
  background: -o-linear-gradient(left, #a2c517 10%, #009046 30%, #0082b6 50%, #151f77 75%, #db0050 100%);
  background: -moz-linear-gradient(left, #a2c517 10%, #009046 30%, #0082b6 50%, #151f77 75%, #db0050 100%);
  background: -webkit-linear-gradient(left, #a2c517 10%, #009046 30%, #0082b6 50%, #151f77 75%, #db0050 100%);
  background: -ms-linear-gradient(left, #a2c517 10%, #009046 30%, #0082b6 50%, #151f77 75%, #db0050 100%);
  background: -webkit-gradient(linear, left top, right top, color-stop(0.1, #a2c517), color-stop(0.3, #009046), color-stop(0.5, #0082b6), color-stop(0.75, #151f77), color-stop(1, #db0050));
  background: linear-gradient(left, #a2c517 10%, #009046 30%, #0082b6 50%, #151f77 75%, #db0050 100%);
}
```

After inspecting the ::before object in Firefox:

```
{
    background: #0066b3;
    background: -webkit-linear-gradient(left,#a2c517 10%,#009046 30%,#0082b6 50%,#151f77 75%,#db0050);
    background: -webkit-gradient(linear,left top,right top,color-stop(.1,#a2c517),color-stop(.3,#009046),color-stop(.5,#0082b6),color-stop(.75,#151f77),color-stop(1,#db0050));
    background: linear-gradient(left,#a2c517 10%,#009046 30%,#0082b6 50%,#151f77 75%,#db0050);
}
```
This is of course not matched to Firefox, and the background becomes blue instead of gradient

It seems that the minification done by `-p` removed the Firefox/Opera/IE-specific lines, and kept only the Wekbit parts.
Why is this done, and how can I prevent this bug?

**Comment by palnes** [comment]
I would think this is down to the minification settings of the `css-loader`. 
https://github.com/webpack/css-loader#minification

Since most browsers now can use gradients as per W3C standards, the need for prefixes are less and less. Check also caniuse.com to check what versions need prefixes.

**Comment by robinsving** [comment]
It seems weird that I have the latest version of Firefox (45.0) and it doesn't work. Nevertheless I guess this is posted in the incorrect github repo. Thanks for the help @palnes .

**Comment by bebraw** [comment]
@robinsving Can you re-open this issue at the css-loader repo and close this one?

**Comment by SimenB** [comment]
adding `-autoprefixer` as an option to css-loader fixes this in our case. We use autoprefixer ourselves to manually add support for stuff for quite old IEs and Chromes, which cssnano removed

**Comment by warrenrumak** [comment]
For what it's worth, `-ms-linear-gradient` is completely unnecessary as there never was a non-beta release of IE that included `-ms-linear-gradient` but not `linear-gradient`.  `-o-linear-gradient` is unnecessary now as well as Opera has supported the standardized syntax since late 2012.

I get that it feels "completist" to support gradients in an IE10 technical preview and the 23rd-most-recent release of Opera, but maybe it's okay to let those things go.

**Comment by robinsving** [comment]
[Moved issue here](https://github.com/webpack/css-loader/issues/248) though it was already answered by @SimenB in this issue.
Closing.
