### ISSUE TITLE
FEATURE - DLLPlugin: Add everything as entry points if no defined

### ISSUE THREAD

**Issue by christianalfoni** [webpack/webpack#2159]
Hi there,

I am using the DLLPlugin to optimize www.webpackbin.com service for code sharing. This is done by using the DLLPlugin to create vendor bundles that does not need to be rebundled. They can also be reused across instances and saved to the database. So yeah, really great feature!

The problem is NPM packages that does not have a `main` entry point. An example being Angular2:

``` js
require('angular2/platform/browser');
```

It is not possible to require that file as I believe the `manifest.json` file needs to be configured correctly, but it can not because there is no `main` entry point in `package.json`.

I tried to manually traverse the package to grab all `js` files and add them as an **array entry point**, but that did not help. So yeah, I am not quite sure how this works.

Would appreciate some help on how to attack this issue. I would be happy to contribute with a fix or just create a new plugin to handle this. But yeah, I need to understand what is wrong first :-)

Big thanks!

**Comment by christianalfoni** [comment]
Thinking about this some more I do not think it is a good idea to traverse as packages can have a huge amount of unnecessary files. Not really sure how this can be solved, hm hm

**Comment by bebraw** [comment]
Is this relevant still?

**Comment by christianalfoni** [comment]
Nopes, identifying entry points manually is pretty much impossible with the freedom of NPM packages... webpack-packager project used by webpackbin and codesandbox is best effort :-)
