### ISSUE TITLE
If you explicitly define a vendor chunk with CommonsChunkPlugin, the module is always evaluated even without a require

### ISSUE THREAD

**Issue by alfonsomunozpomer** [webpack/webpack#2161]
webpack.config.js:

```
var webpack = require('webpack');
var path = require('path');

module.exports = {
    context: __dirname,
    entry: {
        "jquery-ui-demo": "./jquery-ui-demo.js",
        "dependencies": ['jquery', 'jquery-ui']
    },
    output: {
        libraryTarget: "var",
        library: "jQueryUIDemo",
        path: __dirname + "/dist",
        filename: "jquery-ui-demo.bundle.js"
    },

    plugins: [
        new webpack.optimize.CommonsChunkPlugin({
            name: "dependencies",
            filename: "vendor.bundle.js"
        })
    ]
};
```

jquery-ui-demo.js:

```
var $ = require('jquery');
//require('jquery-ui');

module.exports = function() {
    console.log("jQuery version " + $.fn.jquery);
    console.log("jQuery-UI version " + $.ui.version);
};
```

index.html:

```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/html">
<head lang="en">
    <meta charset="UTF-8">
    <script src="vendor.bundle.js"></script>
    <script src="jquery-ui-demo.bundle.js"></script>
    <title>Webpack example jQuery-UI</title>
</head>
<body>
</body>

<script>
    jQueryUIDemo();
</script>

</html>
```

The HTML above always outputs in the console:

```
jQuery version 2.2.1 jquery-ui-demo.bundle.js:49:6
jQuery-UI version 1.10.3
```

Even though jQuery-UI is not actually required. Without CommonsChunkPlugin, the second line in the console returns undefined, as it should.

**Comment by getsnoopy** [comment]
It seems like this has to do with how `CommonsChunkPlugin` is coded (at least in version `1.13.1`): if the chunk was defined in the entry chunks list, it will not make it into an initial chunk (without an entry point that requires all the include modules); if the chunk was not defined, then it will make it an initial chunk.

I have a similar problem, but with multiple commons chunks. I have the following setup:
```
entry: {
  foundation: [
    './utils/cookie.js',
    './utils/url.js',
    './utils/cache.js',
    './utils/native.js'
  ],
  app: './loader.js'
},
output: {
    path: 'dist/',
    filename: '[name].chunk.js',
    library: '[name]_require',
    libraryTarget: 'this',
  },
plugins: [
  new webpack.optimize.OccurrenceOrderPlugin(),

  // Extract all 3rd-party modules into a separate chunk
  new webpack.optimize.CommonsChunkPlugin({
    names: ['foundation', 'vendor'],
    minChunks: (module) => {
      return /node_modules/.test(module.resource)
    },
  }),

  // Separate out the runtime from the chunk created above
  new webpack.optimize.CommonsChunkPlugin({
    name: 'runtime',
    filename: 'runtime.js',
    minChunks: Infinity,
  }),
],
```

This creates 4 chunks in the end: `runtime.js` (with just the runtime), `foundation.chunk.js` (with just the modules I specified), `vendor.chunk.js` (with everything from `node_modules`), and everything else in`app.chunk.js`.

The above configuration works well except for the fact that in `foundation.chunk.js`, Webpack is outputting a module with ID `0` that requires all other modules in that chunk which basically executes those modules. The `vendor.chunk.js`, however, doesn't have this initial module, which is good. How do I have Webpack do the same thing for the `foundation.chunk.js` chunk?
