### ISSUE TITLE
module.e optimization breaks module.exports assignment

### ISSUE THREAD

**Issue by developit** [webpack/webpack#2162]
Hi @sokra: The optimization of switching to `module.e` instead of `module.exports` seems to break for modules that intentionally assign to `module.exports` as a way of exporting explicitly.

Is this a bug, or is there a loader we should be using for this style CommonJS exports?

For reference, the module is https://git.io/proptypes - the export is the result of Babel 5's loose commonjs module transform.  As you can see in the screenshot below, `module.e` remains an empty object (assigned by webpack), and `module.exports` is ignored:

<img width="675" alt="screen shot 2016-03-10 at 9 28 33 am" src="https://cloud.githubusercontent.com/assets/105127/13672380/81a6f92c-e6a2-11e5-91bf-38738edd0112.png">

**Comment by sokra** [comment]
Ah I see... I think the bug is in handling of `define(["module"], function(module) { })`

**Comment by grantila** [comment]
Also, this crashes on any module which re-defines export on module using `defineProperty`, like e.g. `ansi-styles` _(which has 15M downloads/month)_ with the following code: https://github.com/chalk/ansi-styles/blob/master/index.js#L128

This minification basically forces all modules to not export like that.

It seems to be able to affect roughly some hundred packages or so:
https://github.com/search?utf8=%E2%9C%93&q=%22Object.defineProperty+module+exports%22&type=Code&ref=searchresults

**Comment by sokra** [comment]
hmm... looks like I need to revert the change... people are doing crazy stuff.

**Comment by sokra** [comment]
reverted
