### ISSUE TITLE
Ignore require in String evaluation of JS function

### ISSUE THREAD

**Issue by Kurtas** [webpack/webpack#2164]
Hi, 

I can't find a way how to resolve following issue. 
I have a several node backend app's and I use a webpack for build, everything seems to work great. But I use ArangoDB in one app, where I need to use ```database.transation``` https://www.npmjs.com/package/arangojs#databasetransaction where I have to send string evaluation of a JavaScript function (```action``` param). This function is then executed at ArangoDB server, not in client.

see code below
```js
const action = String(documentsList => {
  const db = require('org/arangodb').db;
  const listKeys = documentsList.map(doc => doc.ip);
  const result = db.vTask.documents(listKeys).documents;
   ..... 
});
arongoDb.transaction({write: ['vTask']}, action, docToSaveList);
```

As you can see there is ```require('org/arangodb').db``` and this is resolved by Webpack and I get this error ```Module not found: Error: Cannot resolve module 'org/arangodb'.```

Is there any way, how to set a webpack so that this code will not be affected (changed)

Thanks in advance

**Comment by sokra** [comment]
Try this:

``` js
var require;
const action = String(documentsList => {
  const db = require('org/arangodb').db;
  const listKeys = documentsList.map(doc => doc.ip);
  const result = db.vTask.documents(listKeys).documents;
   ..... 
});
```

**Comment by Kurtas** [comment]
Wow how simple solution ;) Works great, many thanks!

**Comment by Kurtas** [comment]
Hmm, I was happy prematurely :(

This hack works for a babel, but when I use the ```webpack.optimize.UglifyJsPlugin``` then the resulting code is broken. UglifyJS renames require variable and use this new name also in string reprezentation of JS function.

Uglify result
```js
var t,
n=String(function(e){
  var n=t("org/arangodb").db,
  r=e.map(function(e){return e.ip}),
  i=n.vTask.documents(r).documents;
})
```

There isn't any other way how to solve it? I mean that I should use a loader for that, but I can't any relevant loader for this. Or I'm wrong with the loaders?

**Comment by taurose** [comment]
Have you looked at [the docs](https://webpack.github.io/docs/list-of-plugins.html#uglifyjsplugin)? You can whitelist `require`.

**Comment by Kurtas** [comment]
You have right, I overlooked this.
Thank you guys!
