### ISSUE TITLE
Env agnostic assets

### ISSUE THREAD

**Issue by mmahalwy** [webpack/webpack#2166]
I have an isomorphic app with the config.js file pulling variables from `process.env.XXX`.

I want to compile my assets to be agnostic and pull the variables from `process.env.XXX` at runtime (or from the server as window.process.env = {}) rather than using EnvironmentPlugin or DefinePlugin which replaces the variables at compile time.

Thoughts?

**Comment by sokra** [comment]
``` js
new DefinePlugin({
  "provess.env.XXX": "(typeof process === 'object' ? process.env.XXX : 'browser constant')"
});
```

**Comment by mmahalwy** [comment]
@sokra what does the `.XXX` stand for?
