### ISSUE TITLE
node target should ignore hashbang

### ISSUE THREAD

**Issue by ajcrites** [webpack/webpack#2168]
When building for the `node` target, the hashbang should be ignored. For example, if you have a file that has `require("JSONStream")` you will get an error because [this library's main file includes a hashbang](https://github.com/dominictarr/JSONStream/blob/master/index.js#L1)

The node interpreter itself will ignore the hashbang if you run the file, but webpack will treat this as an error.

**Comment by AndrewGrachov** [comment]
upvote

**Comment by martriay** [comment]
upvote

**Comment by Alexandre-Herve** [comment]
Did you find a workaround ? I have this problem with vendor JSONStream lib, don't know what to do !

**Comment by martriay** [comment]
@Alexandre-Herve I used https://github.com/JavascriptIsMagic/shebang-loader

**Comment by komplexb** [comment]
Hey @martriay, I'm having the same issue, but I'm unclear on how to use this plugin. Is it used in the `webpack.config.js` file? Could you post a snippet of it in use? Thanks.

**Comment by martriay** [comment]
@komplexb sure! As I had troubles with the `JSONStream` lib, my loader looks like this:

```    {
      test: /node_modules\/JSONStream\/index\.js$/,
      loaders: ['shebang', 'babel']
    }```

**Comment by komplexb** [comment]
@martriay thanks for that. 
So it's ignoring it, as in the shebang no longer stops my build. But I assumed it would leave the `#!/usr/bin/env node --harmony` at the top of my built file; or is that not how it works?

```
module: {
    loaders: [
      {
        test: /\.jsx?$/,
        exclude: /node_modules/,
        loader: ['shebang', 'babel'],
      }
    ]
  },
```

**Comment by bjackson** [comment]
Any update on this? It seems like it might be a good feature to be built in, so that external packages don't need to be updated (as the hashbang is allowed by node).

**Comment by Nevraeka** [comment]
Any update this?

**Comment by Kielan** [comment]
how is there not a solution to this. the only recommended package doesn't even explain how to use it.

**Comment by kyledecot** [comment]
Also running into this. Any update on an "official" fix?

**Comment by Zenbis** [comment]
Where do i drop the code `{
  test: /node_modules\/JSONStream\/index\.js$/,
  loaders: ['shebang', 'babel']
}`

**Comment by kthakre9** [comment]
any updates on this fix?

**Comment by mach-kernel** [comment]
Also running into this issue. This is affecting our web scale.

**Comment by rsimonton** [comment]
upvote

**Comment by CaerusKaru** [comment]
To use in latest versions of webpack:

```
module: {
    rules: [
      ...
      { test: /FILE_NAME/, loader: 'shebang-loader', include: [/node_modules\/MODULE_NAME/] },
      ...
    ]
  }

**Comment by dsslimshaddy** [comment]
Need a Fix for that! `shebang-loader` not working used the above ^^ code

**Comment by fxlemire** [comment]
If you want to use `shebang-loader` and you are on Windows you need to use the following:

```
module: {
  rules: [
    {
      test: path.resolve(__dirname, 'node_modules/jsonstream/index.js'),
      use: 'shebang-loader',
    },
  ],
},
```

**Comment by mnemanja** [comment]
I'm having the same problem with the **sqlite3** library when using it with **electron** and **create-react-app**, where I have no access to the Webpack (would like not to have to eject).

**Comment by fxlemire** [comment]
@mnemanja What you can do as a last resort is import it with the ! syntax

`import * as sqlite3 from 'shebang-loader!sqlite3';`

Problem is if you intend to write tests... This approach will break your jest tests since it does not use webpack. To fix it, you'd have to eject to be able to configure jest. Ironic right?

In my specific case of `JSONStream` I ended up using a fork, [jsonstream2](https://www.npmjs.com/package/jsonstream2), which got rid of the shebang line, among other things. You could maybe do that too with sqlite3.

Good luck!

**Comment by mnemanja** [comment]
@fxlemire Thanks for the suggestion!

I'll change the approach that I'm taking so that I'm going over the main process (in the structure my main process file is in the public folder so I was looking for an alternative and handle everything from inside of the render process).

Have a nice weekend :)

**Comment by mrchief** [comment]
For cross OS regex match, use this expression:

`include: [/node_modules[/\\]MODULE_NAME/]`

this will work in windows and linux environments alike.

**Comment by mrchief** [comment]
This one is tested with webpack3 on Windows and works:

```js
module: {
  rules: [
    {
        test: /node_modules[/\\]jsonstream/i
        , loader: 'shebang-loader'
    }
  ]
}
```

**Comment by johanpunkrock** [comment]
in your module.exports at webpack.config.js include
`externals: {
        "JSONStream": "require('JSONStream')"
     },`
and if you are in a Electron or Node environment don't forget to set target
`  target: 'electron-renderer',`

**Comment by ooflorent** [comment]
Superseded by #4603

**Comment by govindrai** [comment]
Any update to reflect this within webpack itself?
