### ISSUE TITLE
Splitting webpack "headers" from commons chunk  

### ISSUE THREAD

**Issue by TCMiranda** [webpack/webpack#2169]
Hello guys, I have the following use case, that I cant design with webpack

I have an "app" entry point optimized with CommonsChunkPlugin plugin

    entry: {
        app: './app.js',
        vendor: Object.keys(packageJSON.dependencies)
    },
    plugins: [
        new webpack.optimize.CommonsChunkPlugin(
            'vendor', '[name].js', Infinity
        )
    ]

It gives me 

    app.js
    vendor.js

Which I require on my index file, first vendor, then app.

I want to create another entry that loads a promise lib before `vendor` and another one that will prefetch some data while the user waits the 'vendor.js' file to load.

    entry: {
        promise: ['promise'],
        prefetch: './prefetch.js',
        app: './app.js',
        vendor: Object.keys(packageJSON.dependencies)
    },
    
The problem with that approach is that the webpack jsonp loader is defined on the vendor entry (also the largest one), and I want to transfer it to another file so my application could be loaded on the following order

    1: webpackLoader.js -> define webpack loaders
    2: promise.js -> exposes promise library polyfill
    3. prefetch.js -> requests data to be prefetched and parses them into a promise stored on global scope
    4. vendor.js -> vendors are loaded
    5. app.js -> uses vendor.js libraries to render stuffs 

How can I do it?

**Comment by IngwiePhoenix** [comment]
Did you try specifying an array of files for your vendor entry? All files specified in an entry - string or array - are guaranteed to be executed (unless you do something really … yknow.)

So you can add your prefetch and promise stuff in your vendor bundle as well - just specify it all as an array.

**Comment by TCMiranda** [comment]
Hi @IngwiePhoenix thanks

I am defining them as an array based on my dependencies

    vendor: Object.keys(packageJSON.dependencies)


My problem is that I cant load my `prefetch.js` before `vendor.js` because of webpack jsonp loader is defined on `vendor.js`.

>I want to create another entry that loads a promise lib before vendor and another one that will prefetch some data while the user waits the 'vendor.js' file to load.

**Comment by taurose** [comment]
When you say "wait for vendor file to load", do you mean you want to load the vendor chunk asynchronously?

**Comment by TCMiranda** [comment]
@taurose Yes, but I could also use the order I mentioned synchronously (which is what I suggested):

>1: webpackLoader.js -> define webpack loaders
2: promise.js -> exposes promise library polyfill
3. prefetch.js -> requests data to be prefetched and parses them into a promise stored on global scope
4. vendor.js -> vendors are loaded (load vendors)
5. app.js -> uses vendor.js libraries to render stuffs

**Comment by taurose** [comment]
For the synchronous case, does that work?

```js
entry: {
    promise: ['promise'],
    prefetch: './prefetch.js',
    app: './app.js',
    vendor: Object.keys(packageJSON.dependencies)
},
plugins: [
    new webpack.optimize.CommonsChunkPlugin(
        'vendor', '[name].js', Infinity
    ),
    new webpack.optimize.CommonsChunkPlugin('loader.js')
]
```

I'm a bit confused though, why you'd want to split your modules that much, when you plan to load them all up-front anyways.

**Comment by sokra** [comment]
https://github.com/webpack/webpack/tree/master/examples/two-explicit-vendor-chunks

``` js
        new CommonsChunkPlugin({
            names: ["vender", "prefetch", "promise"],
            minChunks: Infinity
        })
```

**Comment by TCMiranda** [comment]
Thank you guys, sokra's pattern worked for me!

@taurose the reason is to follow the "shell" structure, with offline apps. That way I can split my dependencies in offline / online, and manage them better with my service worker.
