### ISSUE TITLE
How to access modules bundled from webpack outside bundles/chunks

### ISSUE THREAD

**Issue by pjdicke** [webpack/webpack#2171]
I recently moved from RequireJS configuration to rolling up with Webpack. In some places in our Groovy app we have have a script tag in a GSP that will access modules through RequireJS like so:

```
<html>
<body>
...

  <script>
      require([
          'jquery',
          'customModule'
      ], function($, customModule){
          // do something with jquery
          // ...
          // do something with customModule
      });
  </script>

</body>
</html>
```

I would need to be able to do the equivalent with Webpack for a few reasons, the most important is our ability to inject Javascript from our admin side to hotfix any production bugs without pushing a maintenance release but in the event I needed access to a module I don't see how I can access to it?

Expecting I should be able to do something like this:

```
<html>
<body>
...

  <script>
      webpack_require([
          'jquery',
          'customModule'
      ], function($, customModule){
          // do something with jquery
          // ...
          // do something with customModule
      });
  </script>

</body>
</html>
```

**Comment by taurose** [comment]
You could use [expose-loader](https://github.com/webpack/expose-loader) to expose your own require.

```js
// config
module.exports = {
  entry: [
    'expose?myRequire!./myRequire',
    './app.js'
  ]
}


// myRequire.js
const modules = {
  jquery: () => require('jquery'),
  customModule: () => require('./customModule'),
};

export default function myRequire(modules, cb) {
  const instances = modules.map(m => modules[m]());
  cb(...instances);
}
```

**Comment by pjdicke** [comment]
so with that setup I could inject javascript and myRequire would be accessible globally like so:

    <html>
    <body>
     ...

      <script>
          myRequire([
              'jquery',
              'customModule'
          ], function($, customModule){
              // do something with jquery
              // ...
              // do something with customModule
          });
      </script>

    </body>
    </html>

But I would have to list every single module/lib/plugin in my-require.js in order for me to use it like I want in my hotfix scenario?

**Comment by TryingToImprove** [comment]
By using the example provided by @taurose I was able to something like this

```js
    const allModules = {
        React: () => require('react'),
        ReactDOM: () => require('react-dom')
    };

    module.exports = function load(modules, cb) {
        const loadedModules = modules.map(x => {
            // Have we alised the module name?
            let aliasedModule = allModules[x];

            // If we did not find any, then just use the require
            if (!aliasedModule) {
                aliasedModule = () => { return require(x); }
            }

            // Fetch them
            return aliasedModule();
        });

        cb(...loadedModules);
    }
```
------
Which returned:

    requireDependency(['ReactDOM', './components/Application'], (ReactDOM, Application) => console.log(ReactDOM, Application))
    //=Object {version: "15.4.2"} Object {__esModule: true}
