### ISSUE TITLE
performance problem when using the nested require.ensure

### ISSUE THREAD

**Issue by pavankumarkatakam** [webpack/webpack#2172]
I don't know is this intended one or a bug, but it is slow if we use nested _require.ensure_ . what the nested require.ensure means

```
require.ensure([],function(){
  require('chartjs'); // vendor dependency
  require.ensure([],function(){
            require("myownmodule);
  });
})
```

**Comment by pavankumarkatakam** [comment]
Hi @bebraw , is there any progress on this?

**Comment by bebraw** [comment]
@pavankumarkatakam No. Hopefully we'll get a comment from webpack author or someone else has time to dig deeper. :+1:

**Comment by bebraw** [comment]
Can you confirm this against webpack 2?
