### ISSUE TITLE
Not able to install webpack with npm

### ISSUE THREAD

**Issue by ast0708** [webpack/webpack#2173]
I run the following command on ubuntu 12.04 machine - 
npm install webpack -g

I get the following error

npm http GET http://registry.npmjs.org/karma/webpack
npm http 404 http://registry.npmjs.org/karma/webpack

npm ERR! TypeError: Object.keys called on non-object
npm ERR!     at Function.keys (native)
npm ERR!     at next_ (/usr/share/npm/lib/cache.js:428:34)
npm ERR!     at next (/usr/share/npm/lib/cache.js:415:44)
npm ERR!     at /usr/share/npm/lib/cache.js:408:5
npm ERR!     at saved (/usr/share/npm/lib/utils/npm-registry-client/get.js:147:7)
npm ERR!     at Object.oncomplete (/usr/lib/nodejs/graceful-fs.js:230:7)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /home/atul/dev/piggy/npm-debug.log npm
npm ERR! 
npm ERR! System Linux 3.8.0-44-generic
npm ERR! command "node" "/usr/bin/npm" "install" "webpack" "-g"
npm ERR! cwd /home/atul/dev/piggy
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! type obj_ctor_property_non_object
npm ERR! arguments [ 'keys' ]
npm ERR! message Object.keys called on non-object
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/atul/dev/piggy/npm-debug.log
npm not ok
root@Mark-II:/home/atul/dev/piggy# npm install webpack -g
npm http GET http://registry.npmjs.org/karma/webpack
npm http 404 http://registry.npmjs.org/karma/webpack

npm ERR! TypeError: Object.keys called on non-object
npm ERR!     at Function.keys (native)
npm ERR!     at next_ (/usr/share/npm/lib/cache.js:428:34)
npm ERR!     at next (/usr/share/npm/lib/cache.js:415:44)
npm ERR!     at /usr/share/npm/lib/cache.js:408:5
npm ERR!     at saved (/usr/share/npm/lib/utils/npm-registry-client/get.js:147:7)
npm ERR!     at Object.oncomplete (/usr/lib/nodejs/graceful-fs.js:230:7)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /home/atul/dev/piggy/npm-debug.log npm
npm ERR! 
npm ERR! System Linux 3.8.0-44-generic
npm ERR! command "node" "/usr/bin/npm" "install" "webpack" "-g"
npm ERR! cwd /home/atul/dev/piggy
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! type obj_ctor_property_non_object
npm ERR! arguments [ 'keys' ]
npm ERR! message Object.keys called on non-object
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/atul/dev/piggy/npm-debug.log
npm not ok
root@Mark-II:/home/atul/dev/piggy# npm install webpack
npm http GET http://registry.npmjs.org/karma/webpack
npm http 404 http://registry.npmjs.org/karma/webpack

npm ERR! TypeError: Object.keys called on non-object
npm ERR!     at Function.keys (native)
npm ERR!     at next_ (/usr/share/npm/lib/cache.js:428:34)
npm ERR!     at next (/usr/share/npm/lib/cache.js:415:44)
npm ERR!     at /usr/share/npm/lib/cache.js:408:5
npm ERR!     at saved (/usr/share/npm/lib/utils/npm-registry-client/get.js:147:7)
npm ERR!     at Object.oncomplete (/usr/lib/nodejs/graceful-fs.js:230:7)
npm ERR! You may report this log at:
npm ERR!     <http://bugs.debian.org/npm>
npm ERR! or use
npm ERR!     reportbug --attach /home/atul/dev/piggy/npm-debug.log npm
npm ERR! 
npm ERR! System Linux 3.8.0-44-generic
npm ERR! command "node" "/usr/bin/npm" "install" "webpack"
npm ERR! cwd /home/atul/dev/piggy
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! type obj_ctor_property_non_object
npm ERR! arguments [ 'keys' ]
npm ERR! message Object.keys called on non-object
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/atul/dev/piggy/npm-debug.log
npm not ok

**Comment by bebraw** [comment]
Your node and npm have very old versions. Those are supported anymore.

Can you try upgrading to the newest LTS (4.x) at least? That will come with npm 2. Node 5.x and npm 3 should work too.

**Comment by ast0708** [comment]
Thanks a lot. Node got update easily, but npm is now getting updated 
npm update -g npm

gives me the output - 
npm ERR! Linux 3.8.0-44-generic
npm ERR! argv "/root/.nvm/versions/node/v5.8.0/bin/node" "/root/.nvm/versions/node/v5.8.0/bin/npm" "update" "-g" "npm"
npm ERR! node v5.8.0
npm ERR! npm  v3.7.3
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on http://registry.npmjs.org/karma/npm
npm ERR! 404 
npm ERR! 404  'karma' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:


Thanks in advace

**Comment by bebraw** [comment]
I don't know that much about Ubuntu. It might be better to look into node/npm related help elsewhere. There's likely some official way to set it up.

I'm closing this issue as this goes beyond webpack. :smile:
