### ISSUE TITLE
Compatibility with config module

### ISSUE THREAD

**Issue by sedubois** [webpack/webpack#2174]
In my webpack project, I installed the `config` NPM module (`npm i --save config` + `import config from 'config';`), but then running `webpack` yields the error below. I am not yet very experienced neither with node, nor with webpack.

```
WARNING in ./~/config/lib/config.js
Critical dependencies:
845:21-42 the request of a dependency is an expression
871:21-42 the request of a dependency is an expression
 @ ./~/config/lib/config.js 845:21-42 871:21-42
```

The code at `~/config/lib/config.js:845` is indeed a dynamic require: `configObject = require(fullFilename)`. How should this module be handled with webpack? Or there any alternative module compatible with webpack?

Here is `webpack.config.js`:

```
var path = require('path');
var HtmlwebpackPlugin = require('html-webpack-plugin');
var webpack = require('webpack');
var merge = require('webpack-merge');

const TARGET = process.env.npm_lifecycle_event;
const appPath = path.join(__dirname, 'app');

process.env.BABEL_ENV = TARGET;

var common = {
  entry: appPath,
  output: {
    path: path.join(__dirname, 'build'),
    filename: 'bundle.js'
  },
  resolve: {
    extensions: ['','.js','.jsx','.wav']
  },
  module: {
    loaders: [
      { test: /\.css$/, loaders: ['style', 'css'] },
      { test: /\.jsx?$/, loader: 'babel', include: appPath },
      { test: /\.wav$/, loader: 'file', include: appPath },
      { test: /\.(woff|woff2)$/, loader:"url?prefix=font/&limit=5000" },
      { test: /\.eot(\?v=\d+\.\d+\.\d+)?$/, loader: "file" },
      { test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/, loader: "url?limit=10000&mimetype=application/octet-stream" },
      { test: /\.svg(\?v=\d+\.\d+\.\d+)?$/, loader: "url?limit=10000&mimetype=image/svg+xml" }
    ]
  },
  plugins: [
    new HtmlwebpackPlugin({
      title: 'Timer app'
    })
  ]
};

if(TARGET === 'dev' || !TARGET) {
  module.exports = merge(common, {
    devtool: 'eval-source-map',
    devServer: {
      historyApiFallback: true,
      hot: true,
      inline: true,
      progress: true,
      stats: 'errors-only',
      host: process.env.HOST,
      port: process.env.PORT || 3002
    },
    plugins: [
      new webpack.HotModuleReplacementPlugin()
    ]
  });
}
```

`npm list config` returns `config@1.19.0`.

**Comment by sedubois** [comment]
OK adding this to `webpack.config.js` solved the issue in the OP (cfr. https://github.com/webpack/webpack/issues/198#issuecomment-37306725):

```
    exprContextRegExp: /$^/,
    exprContextCritical: false,
```

However running `webpack` still raises 3 warnings and 5 errors for modules in `config.js` which cannot be loaded:

```
WARNING in ./~/config/lib/config.js
Module not found: Error: Cannot resolve module 'coffee-script' in /Users/sdubois/Documents/mindfulnets/website/node_modules/config/lib
 @ ./~/config/lib/config.js 863:17-41

WARNING in ./~/config/lib/config.js
Module not found: Error: Cannot resolve module 'iced-coffee-script' in /Users/sdubois/Documents/mindfulnets/website/node_modules/config/lib
 @ ./~/config/lib/config.js 874:13-42

WARNING in ./~/config/lib/config.js
Module not found: Error: Cannot resolve module 'yaml' in /Users/sdubois/Documents/mindfulnets/website/node_modules/config/lib
 @ ./~/config/lib/config.js 941:28-43

ERROR in ./~/config/lib/config.js
Module not found: Error: Cannot resolve module 'fs' in /Users/sdubois/Documents/mindfulnets/website/node_modules/config/lib
 @ ./~/config/lib/config.js 20:17-30

ERROR in ./~/config/lib/config.js
Module not found: Error: Cannot resolve module 'hjson' in /Users/sdubois/Documents/mindfulnets/website/node_modules/config/lib
 @ ./~/config/lib/config.js 989:14-30

ERROR in ./~/config/lib/config.js
Module not found: Error: Cannot resolve module 'toml' in /Users/sdubois/Documents/mindfulnets/website/node_modules/config/lib
 @ ./~/config/lib/config.js 997:13-28

ERROR in ./~/config/lib/config.js
Module not found: Error: Cannot resolve module 'cson' in /Users/sdubois/Documents/mindfulnets/website/node_modules/config/lib
 @ ./~/config/lib/config.js 1004:13-28

ERROR in ./~/config/lib/config.js
Module not found: Error: Cannot resolve module 'properties' in /Users/sdubois/Documents/mindfulnets/website/node_modules/config/lib
 @ ./~/config/lib/config.js 1015:16-37
```

**Comment by sedubois** [comment]
It's alright, I just use environment variables.

**Comment by diffractometer** [comment]
@sedubois any luck with this? I'm having the same error.

**Comment by sedubois** [comment]
@diffractometer No I concluded that `config` is simply not designed to run in the browser, and it made me realise (at this point) that all the possible configurations shouldn't be included in the static files, only the needed config should be accessible through the browser. So as I so far only have deployment configurations (e.g URLs and ports), I put them in a `.env` file which are loaded as environment variables via `dotenv` in the webpack config file, then in the static files I make use of those env vars such as `process.env.XXX` which are replaced by the proper values via the webpack `EnvironmentPlugin`.

**Comment by sebastienbarre** [comment]
Consider closing the issue? This makes it a bit easier to navigate open issues. Thanks.

**Comment by ohkaiby** [comment]
Just ran into this. Fixed it by using the [webpack-node-externals](https://www.npmjs.com/package/webpack-node-externals) module in my webpack server config.

**Comment by meinto** [comment]
Some people disliked the comment of @kaibyao. What are the disadvantages using webpack-node-externals targeting node applications?

**Comment by robpc** [comment]
@meinto Most of the cases I know of where you want to package a node application with webpack are cases where you can't or don't want to use `npm install` or copy the `node_modules` directory wholesale. Serverless applications are a good example of this, where minifying, tree-shaking, and just removing 90% of the files in `node_modules` that are non-runtime can have noticeable cost and performance benefits. As always, I'm sure there are others that I am less familiar with where that is not a concern, but that is my guess for where the down votes are coming from.
