### ISSUE TITLE
Link to CommonJS in README.md is dead.

### ISSUE THREAD

**Issue by rantler** [webpack/webpack#2176]

**Comment by TheLarkInn** [comment]
Looks like http://www.commonjs.org/specs/modules/1.0/ is a 404'd page now. Should we just link to the CommonJS Wiki instead?

**Comment by IngwiePhoenix** [comment]
I’d suggest so. for now, that sounds like a good option.

**Comment by TheLarkInn** [comment]
@IngwiePhoenix on it :-D

**Comment by bebraw** [comment]
Fixed. Closing.
