### ISSUE TITLE
Requiring jQuery at the global level for usage with Semantic UI modules

### ISSUE THREAD

**Issue by CameronK** [webpack/webpack#2180]
Hello, 

I'm working on an isomorphic React app, in which I would like to require jQuery modules from Semantic UI. Each module adds itself to jQuery by accessing the global variable. I have spent hours scouring pretty much every corner of Github and Stackoverflow (and other random websites) looking for solutions, but so far, not a single one has worked.

Methods I have tried:
- ProvidePlugin for $, jQuery, and window.jQuery - if I understand correctly, this provides new instances of jQuery each call so the window does not reflect any changes to the object made in required files
- expose loader (https://github.com/webpack/expose-loader) - crashes dev server upon usage
- imports loader (http://reactkungfu.com/2015/10/integrating-jquery-chosen-with-webpack-using-imports-loader/) - does absolutely nothing
- various other combinations of requiring jQuery at different locations in my stack

I'm clearly missing something here. Can someone point me to a (working) tutorial or explain the process by which I could get this working? I've spent so many hours on it now that I gave up and included both libraries manually...which completely defeats the purpose of converting to webpack anyway.

Thanks.

My webpack.config.js (for development)

``` javascript
var webpack = require('webpack');
var path = require('path');

var webpackConfig = {
    resolve: {
        extensions: ['', '.js', '.jsx', '.less', '.css'],
        resolve: {
            alias: {
                jquery: "jquery/src/jquery"
            }
        }
    },
    entry: [
        'webpack-dev-server/client?http://localhost:3000',
        'webpack/hot/only-dev-server',
        './client.js'
    ],
    output: {
        path: path.resolve('./dist'),
        publicPath: '/public/',
        filename: 'dev.js'
    },
    module: {
        loaders: [
            {
                test: /\.(js|jsx)$/,
                exclude: /node_modules/,
                loaders: [
                    require.resolve('react-hot-loader'),
                    require.resolve('babel-loader'),
                ]
            },
            {
                test: /\.css$/,
                loader: "style-loader!css-loader"
            },
            {
                test: /\.less$/,
                loader: "style!css!less"
            },
            {
                test: /\.json$/,
                loader: 'json-loader'
            }
        ]
    },
    node: {
        setImmediate: false
    },
    plugins: [
        new webpack.HotModuleReplacementPlugin(),
        new webpack.NoErrorsPlugin(),
        new webpack.DefinePlugin({
            'process.env': {
                NODE_ENV: JSON.stringify(process.env.NODE_ENV),
                BROWSER: JSON.stringify(true)
            }
        })
        // ,
        // new webpack.ProvidePlugin({
        //     $: "jquery",
        //     jQuery: "jquery"
        // }),
    ],
    devtool: 'eval'
};

module.exports = webpackConfig;
```

**Comment by IngwiePhoenix** [comment]
window.$ = window.jQuery = require("jquery");

This _always_ worked for me… Just do this in your entry and you should be golden.

**Comment by CameronK** [comment]
@IngwiePhoenix That was the first thing I tried and it does not work.

**Comment by IngwiePhoenix** [comment]
Wow. You tried litterally everything that there is, then. How are your components trying to use jQuery? I mean, jQuery plugins themselves only need it to either be globally available or injected via imports-loader. But you spoke of some UI components. Maybe you can see how they try to utilize jQuery?

**Comment by CameronK** [comment]
I've checked them. They assume "jQuery" is defined as a global variable.

I was just now able to get the whole compiled library to work when importing it in my client.js file, after the window.jQuery definition. So that'll do for now I suppose...Optimally, I would like to expose window.jQuery to all my component files and require individual semantic components based on what was needed per component, instead of the whole library.

**Comment by iamolivinius** [comment]
Have you already read this comment: https://github.com/Semantic-Org/Semantic-UI/issues/517#issuecomment-31698192

The examples helped me alot.

**Comment by akomm** [comment]
Could make it work, but without explicit jQuery import/quire. It is global. Tried 1.000 variations and its the cleanest.

ProvidePlugin. mapped global variables to jquery2 node lib.

```js
plugins: [
  new webpack.ProvidePlugin({
    $: 'jquery2',
    jQuery: 'jquery2'
  })
]
```

module.loaders:
```js
module: {
  loaders: [
    {
      test: /\.css$/,
      include: /semantic/,
      loaders: ['style-loader', 'css-loader']
    },
    {
      test: /\.js$/,
      include: /semantic/,
      loaders: ['imports-loader?this=>window']
    },
    {
      test: /\.(png|jpg|jpeg|svg|woff|woff2|ttf|eot)$/i,
      loaders: ['file-loader']
    }
  ]
},
```

**Comment by chungtinhlakho** [comment]
anyone ever got a solution for this?

**Comment by ryannealmes** [comment]
I have been trying to get this working like crazy for bootstrap. What was weird is even the simplest example didn't want to work ...

```javascript
var webpack = require('webpack');

module.exports = {
	entry: [
	'./utils',
	'./app'
	],
	output: {
		filename: 'bundle.js'
	},
	plugins: [new webpack.ProvidePlugin({ $: "jquery" })],
	module: {
		preLoaders: [{
			test: /\.js$/,
			exclude: /node_modules/,
			loader: 'jshint-loader'
		}],
		loaders: [{
			test: /\.es6$/,
			exclude: /node_modules/,
			loader: 'babel-loader'
		}]
	},
	resolve: {
		extensions: ['', '.js', '.es6']
	}
}
```

All I wanted to do was console log the jquery variable `$`. I think the problem is `ProvidePlugin` is broken in `v2.1.0-beta.25`. After downgrading to `"webpack": "^1.13.2"` it started to print out the variable again. I am guessing there has been a breaking change? It seems the functionality doesn't work at all anymore.

I guess if you stumble on this it could be a similar problem.

**Comment by chungtinhlakho** [comment]
I went thru the exactly game thing and got mine to work with exposed.  dont
have the code in front of me but will send it to you tomorrow.  remind me.
 thanks

**Comment by chungtinhlakho** [comment]
see the last loader, that does the trick, make jquery,$ available at the global level.  I am using  "webpack": "1.13.2",
    "webpack-dev-server": "^1.16.1"

```
var webpack = require('webpack');
var HtmlWebPackPlugin = require('html-webpack-plugin');
var path = require('path');

module.exports = {
    entry:'./src/main.ts',
    
    output:{
        path:'./dist',
        filename:'app.bundle.js'
    },
    module:{
        loaders:[{test:/\.ts$/, loader:'ts-loader'},
        { test: /\.css$/, loaders: ['to-string-loader', 'css-loader'] },
        { test: /\.html$/, loader: 'raw-loader' },
        { test: require.resolve('jquery'), loader: 'expose?jQuery!expose?$' }
      ]
    /*   loaders: [
      // .ts files for TypeScript
      { test: /\.ts$/, loaders: ['awesome-typescript-loader', 'angular2-template-loader'] },
      { test: /\.css$/, loaders: ['to-string-loader', 'css-loader'] },
      { test: /\.html$/, loader: 'raw-loader' }
    ]*/
    },
    resolve:{
        root: [ path.join(__dirname, 'src') ], //add this for dev server
        extensions:['','.js','.ts']
    },
    plugins:[
        
        //inject all the files above into this file
        new HtmlWebPackPlugin({
            template: './src/index.html'
        }),
        new webpack.ProvidePlugin({
            jQuery: 'jquery',
                $: 'jquery',
                jquery: 'jquery'
        })
        
    ]


}
```

**Comment by ryannealmes** [comment]
Thanks @chungtinhlakho, if you checkout my comment I mentioned that I did get it to work with the version you are using, but I can't get it to work with version v2.1.0-beta.25 :/ That is what I am trying to do.

**Comment by obonyojimmy** [comment]
@chungtinhlakho your solution works perfectly

**Comment by obonyojimmy** [comment]
Below works with v1.13.2 

```
module: {
 loaders: [
  { test: require.resolve("jquery"), loader: "expose?$!expose?jQuery" },
 ]
}
```

**Comment by wegry** [comment]
Have you tried using [externals](https://webpack.github.io/docs/library-and-externals.html) in lieu of the expose loader?

```
// webpack config (I use this idea with webpack 2.1.0-beta25 
module.exports = {
  ...
   externals: ['window']
}
```

```
// entry-point.js
import jQuery from 'jquery'

window.jQuery = jQuery
console.log(window.jQuery);
```

**Comment by bebraw** [comment]
Closing as solutions were presented.

**Comment by hshafy** [comment]
@chungtinhlakho why do you use both `webpack.ProvidePlugin` and `expose` as far as I understand these are two use cases, check the answer #23 in this thread http://stackoverflow.com/questions/29080148/expose-jquery-to-real-window-object-with-webpack

Also this fix didn't work for me, I tried with webpack 1.13.2 & 1.14 nothing works, I use React Starter Kit.

Any ideas?

**Comment by paxperscientiam** [comment]
Why is this so difficult?

> window.$ = window.jQuery = require("jquery");
> This always worked for me… Just do this in your entry and you should be golden.

@IngwiePhoenix Bless your heart.

**Comment by ztamizzen** [comment]
Documentation states:

new webpack.ProvidePlugin({
  'window.jQuery': 'jquery'
});

**Comment by wysihtml5-starry** [comment]
I solved it https://mule-studio400.github.io/qdTY2PaEIl25nzUCJP9ExQncPfZE1kOOf0iPbI6kLdLL4eqegsqSQi_PBA3Zdq9jk3uXg9va9ccV0bvePclqOg/
