### ISSUE TITLE
Multiple publicPath?

### ISSUE THREAD

**Issue by Catlite91** [webpack/webpack#2183]
If I have more than one CDN destination (such as one for css/js and another for images), how do I configure the entry.publicPath?

**Comment by tcstory** [comment]
I met the same problem, I only want to place image file in cdn, but js and css file in my server, but now if I set publicPath to cdn url ,all the file (includes js ,css image) will be prepend the cdn url,

**Comment by Catlite91** [comment]
donnot use the publicPath, just save them on the disk as normal then uoload
manually
2016年3月25日 下午2:18，"颜贵彬" <notifications@github.com>写道：

**Comment by zhangyihua** [comment]
It's the same problem to me, and I haven't found a valid solution, @Catlite91 can you give an example?

**Comment by Catlite91** [comment]
output: {
        path: path.resolve('publish', baseConfig.version.webVersion),
        filename: `${**baseConfig.cdn.statics**}/js/[name].[chunkhash].js`,
        chunkFilename: `${**baseConfig.cdn.statics**}/js/[id].[chunkhash].chunk.js`
    }

and add loaders:
        {
            test: /\.(png|jpg|jpeg|gif)$/,
            query: {
                name: `${**baseConfig.cdn.images**}/[name].[hash].[ext]`,
                limit: 8192
            },
            loader: 'url-loader'
        }
 It will create files in path 
-http:
    -s1.xxx.com
        xxx.png
        xxxx.png
    -s2.xxx.com
        -css
            xxx.css
            xxx.css
        -js
            xxx.js
            xxxx.js

just ignore the strange path name
