### ISSUE TITLE
Webpack 2 + System.import: default export has to be read with .default

### ISSUE THREAD

**Issue by Kovensky** [webpack/webpack#2188]
Snippet demonstrating the issue:

```js
// test.js
export default class Test {}

// index.js (with proper runtime available)
System.import('./test').then(Test => {
  new Test() // error! must use new Test.default()
})
```

The following code gets generated in webpack's chunk containing `test.js`:
```js
/* harmony default export */ exports["default"] = Test;
```

This behaves differently from when you use `import Test from './test'`, as when you use such a static import you can then call `new Test()` instead of having to call `new Test.default()`.

I also considered this might be an issue with babel transforms, but as it is getting emitted as a `/* harmony default export */`, I don't believe babel is transforming the export. I am using the `es2015-webpack` preset to preserve harmony imports/exports.

Not sure if this a webpack 2 bug or just a  documentation issue.

**Comment by Kovensky** [comment]
Hm, I just noticed that this basically has the same behavior as `import * as Test from './test'`. In this case, I would still have to access `Test.default` to get at the default export.

In this case, I suppose this is only a documentation (or expectation) issue.

**Comment by helloyou2012** [comment]
@Kovensky ,  I use this plugin to solve this problem: https://github.com/59naga/babel-plugin-add-module-exports

**Comment by sokra** [comment]
> Not sure if this a webpack 2 bug or just a documentation issue.

> Thus, I suppose this is only a documentation (or expectation) issue.

Yep, working as intended.

**Comment by sokra** [comment]
> @Kovensky , I use this plugin to solve this problem: https://github.com/59naga/babel-plugin-add-module-exports

I don't recommend this. babel has good reasons for no longer doing so.

**Comment by hkrutzer** [comment]
Take a look at https://medium.com/@kentcdodds/misunderstanding-es6-modules-upgrading-babel-tears-and-a-solution-ad2d5ab93ce0

**Comment by pksjce** [comment]
This issue was moved to webpack/webpack.io#122
