### ISSUE TITLE
Webpack 2: System.import (usually) fails on IE

### ISSUE THREAD

**Issue by phaistonian** [webpack/webpack#2189]
I think the title does the trick, but here goes:

`System.import` works like a charm (and feels much more elegant than the `require.ensure`), however it seems to fail most of the time (if not always) on IE.

Tested on IE10, IE Edge so far.

**Comment by phaistonian** [comment]
On further inspection, it seems that the issue is that, though the chunks are imported properly, the promise(s) does not resolve.

To be exact, they occasionally resolve, but that's super rare.

**Comment by phaistonian** [comment]
More info:

```
Promise.all([
    System.import('file`),
    System.import('file2')
  ])
    .then(() => {
      alert(1);
    });
```

This works every time I test it - even using a `setInterval` to check if this works every time.

Thing is, and this is SUPER weird, when having this an event handler (function), i.e

```
document.body.addEventListner('click', () =>  {
  Promise.all([
    System.import('file`),
    System.import('file2')
  ])
    .then(() => {
      alert(1);
    });
})
```
it does NOT work (though it works fine on all non-IE browsers).

Hopefully this will point somehwere.

**Comment by TheLarkInn** [comment]
@phaistonian would you be able to provide a bit more information: 
* webpack version being used?

Also can you update to 2.1.0-beta.14 and see if this issue still persists.

**Comment by mAAdhaTTah** [comment]
I'm getting this issue on IE10 as well. I'm running `2.2.1`, and its affecting `import` rather than `System.import`. My current theory is its caching related; the scripts for which the promise doesn't resolve appear to 304 in the network tab.
