### ISSUE TITLE
[2.1] Error: "Config did not export an object." when no --env is passed.

### ISSUE THREAD

**Issue by ju1ius** [webpack/webpack#2190]
Hi,

With a webpack config exporting a function:
```js
module.exports = function (options) {
  return {
     debug: options.dev,
    // etc...
  };
}
```
Calling webpack without the --env.dev switch:
```sh
$ webpack
> Config did not export an object.
```

Which is rather counter-intuitive. I would expect webpack to call the exported function, passing it an empty options object.

**Comment by sokra** [comment]
`options` should be undefined in this case.

**Comment by sokra** [comment]
Works for me

**Comment by TheLarkInn** [comment]
@ju1ius is this still an issue for you in recent versions of webpack 2.1.0-beta ?

**Comment by ju1ius** [comment]
Thank you very much! :tada:

**Comment by SteveVanOpstal** [comment]
@sokra `undefined` is logical but not really practical.
For example; the only way to get the before mentioned config to not be in debug mode is to do one of the next things:

1: Add hacky code:
```
module.exports = function (options) {
  if (!options) {
    options = {};
  }
  
  return {
     debug: options.dev,
    // etc...
  };
}
```

2: Add an unused argument:

`webpack --env.prod`

**Comment by SteveVanOpstal** [comment]
@TheLarkInn This is still an issue in webpack 2.1.0-beta.25

**Comment by kazimuth** [comment]
Still an issue for me as well.

**Comment by TheLarkInn** [comment]
Is this an issue in latest RC?

**Comment by kazimuth** [comment]
...As it turns out, I had the wrong version of Webpack installed.

Not actually a problem, sorry.

**Comment by mmclau14** [comment]
link is broken

**Comment by darincardin** [comment]
same issue when using webpack 1.13.1.
followed the webpack instructions from this page:
https://webpack.js.org/guides/production/

Is there a solution? Higher version of webpack?

**Comment by byrontuckett** [comment]
Worked for me after upgrade from 1.x. to webpack 3.6.0 (yeh I know... legacy project)
