### ISSUE TITLE
Force re-compile of file from loader

### ISSUE THREAD

**Issue by aleskafka** [webpack/webpack#2192]
I have file A that requires a file B. When compiling file A I either know about B in advance or I know there might possibly exists file B in future (without knowing its path so I can't use dependency system). When A doesn't know B, it emits error. When I come across valid file B (in loader), I need to recompile A to reflect dependency on discovered B.

Is there a way to force re-compile of A when I discover file B without setting anything in advance? It can even be some internal API that Watcher uses to emit changes. I did go through source code, but wasn't able to find my answer.

Fyi, I'm finishing goog-loader for Google Closure Library with advanced compilation for production. I have a good enough version, but recovery of invalid dependency without editing file A would be nice.

Thank you.

**Comment by aleskafka** [comment]
Allow me one more question with possible solution. I just need to know some edgy implementation details I could take advantage of.

How does async callback and emitWarning/emitError works? Does emitted warning cancel pending callback or not? Documentation provides no clue about this behaviour.

When I find that A is missing required file B, can I emitWarning and store pending callback for latter when I discover file B?

**Comment by sokra** [comment]
You could add a context dependency, which is a dependency to a whole directory. Is this enough for your use case?

If not you can flag the file as not cacheable and call `invalidate` on the watcher.

> When I find that A is missing required file B, can I emitWarning and store pending callback for latter when I discover file B?

no. compilation will not finish until callback is invoked.

**Comment by aleskafka** [comment]
Thank you. Yes, context dependency could be solution. I'd imagine it could expect glob pattern as argument, but even dirname is fine. I did notice this method exists, but not that it works with directories.

Allow me two follow-up questions.

How does file dependency works? Say I have file A dependent on B and file B dependent on C. Only file C is changed. Which files are recompiled?

How much overhead is there when I addContextDependency for all application files, but in 99% cases callback is provided with cached source from previous compilation (because there wasn't change that would force re-compilation of those files). Is webpack internally optimized when same source is provided to callback? Or is overhead minimum?

Thank you for your time.

**Comment by sokra** [comment]
> Say I have file A dependent on B and file B dependent on C. Only file C is changed.

It really A' depends on A and B, B' depends on B and C. Where A' and B' are the generated files from A and B. So when C changes only B' is recomplied.

> Is webpack internally optimized when same source is provided to callback?

yes, if it results in the same hash it is not threaded as changed module.

**Comment by aleskafka** [comment]
Thank you for your support. I can finalize goog-loader now, thanks to your input. If it stops acting weird on wrong namespace detection (with automatic revival of all files), I will release it for community.
