### ISSUE TITLE
webpack 2 output ES2015

### ISSUE THREAD

**Issue by graingert** [webpack/webpack#2194]
Is it possible to use webpack 2 to target browsers like Firefox 45 or Chrome 49? Ie only using the the es2015 modules transpiler

**Comment by evenfrost** [comment]
Webpack does not manage transpilation but Babel does. Refer to the [babel-loader](https://github.com/babel/babel-loader) config and [Babel](http://babeljs.io/docs/setup/#webpack) itself for further info.

**Comment by graingert** [comment]
@evenfrost ah it turns out it just works! https://github.com/graingert/webpack2-sandbox

**Comment by graingert** [comment]
@shubhamsizzles ^

**Comment by graingert** [comment]
and you can use this sweet preset for modern browsers: https://github.com/christophehurpeau/babel-preset-modern-browsers/blob/master/webpack2.js
