### ISSUE TITLE
"Cannot define 'query' and multiple loaders in loaders list"

### ISSUE THREAD

**Issue by jenius** [webpack/webpack#2195]
So when you have a loader config that uses multiple loaders, like perhaps `css!postcss`, you *must* use query string syntax in order to pass options to one of the loaders, instead of the `query` option. So if you have your options as an object, you can run `JSON.stringify` on them and inject into the loader string.

However, if you are passing any option at all that cannot be stringified (for example, a function), it breaks, and it seems to me like there is no possible method of doing this. It seems like cutting off the ability to pass anything that cannot be stringified whenever you have more than one loader is limiting (well, certainly it is for me now, which is why I'm opening this issue!)

Is there any way around this, or would you be open to a patch to fix this and allow some syntax for passing options for multiple loaders through `query`? Like maybe allowing `loaders: [{ loader: 'foo', query: { bar: 'baz' } }]`, instead of only allowing strings?

**Comment by bebraw** [comment]
FYI, this is valid:

```javascript
{
  test: /\.jsx?$/,
  loader: 'babel',
  query: {
    cacheDirectory: true,
    presets: ['react', 'es2015', 'survivejs-kanban']
  },
  include: PATHS.app
}
```

Not exactly what you requested, but perhaps close enough.

**Comment by jenius** [comment]
So just came across [this](https://webpack.github.io/docs/how-to-write-a-loader.html#programmable-objects-as-query-option) - presumably it's the solution here? Not the smoothest, but it works.

**Comment by sokra** [comment]
> Like maybe allowing loaders: [{ loader: 'foo', query: { bar: 'baz' } }], instead of only allowing strings?

This was added for webpack 2
