### ISSUE TITLE
conditional require style

### ISSUE THREAD

**Issue by shiroganee** [webpack/webpack#2196]
Is it possible to actually add conditional require?
I mean, i'm trying to add something like:

if (typeof window !== 'undefined' && process.env.ENV === 'z') {
    require('../../../../../public/stylesheets/admin.scss');
}

But it will add always that style (i mean the webpack) no matter what ENV i will set (you can see that by simply commeting this / uncommeting) the difference is maybe not big but I'm needing similar stuff few times in more places, which makes Webpack build time increase from 12sec to 30sec.

**Comment by sokra** [comment]
Yes, with the DefinePlugin
