### ISSUE TITLE
Size stats after plugins?

### ISSUE THREAD

**Issue by josh18** [webpack/webpack#2198]
Is it possible to view size stats after plugins (DefinePlugin, UglifyJsPlugin, etc) have run? Currently when I look at the module stats it is inaccurate compared to the result of after the plugins have finished.

Essentially I am trying to find a good way to measure how much each module contributes to the total size of my js file. I have a feeling this isn't possible but thought I would ask just in case I am missing something.

**Comment by bebraw** [comment]
The analyze tool gets close, but it's missing some of that info. Iirc there's a timing related request as well.

**Comment by josh18** [comment]
Just did a quick google search but I'm not quite sure which analyse tool you are referring to, are you able to link me to it?

**Comment by bebraw** [comment]
Sure. There are actually a couple. I have listed them [here](http://survivejs.com/webpack/building-with-webpack/analyzing-build-statistics/).

**Comment by josh18** [comment]
Thanks, just had a look at those and they are pretty interesting.

Unfortunately they don't really help with the problem I am trying to solve. The main problem is something like the React library which uses environment variables to greatly reduce its code size for production. However I assume it isn't possible to to check the size after plugins because I assume plugins are just run on the entire file rather than on individual modules?

I wonder if it is possible to do one compile, grab all the top level modules, then compile each top level module individually? Probably would be qutie slow and not 100% accurate but do you think something like that would work?

**Comment by bebraw** [comment]
We most likely need better instrumentation at webpack level to make this simple. You could definitely try to hack it like you proposed, but it's not going to be particularly neat or fast.
