### ISSUE TITLE
how to disable console.log HMR and WDS?

### ISSUE THREAD

**Issue by MegaJsTeam** [webpack/webpack#2199]

**Comment by bebraw** [comment]
You could try setting

```javascript
...
devServer: {
  stats: 'errors-only'
},
...
```

at your webpack configuration. webpack-dev-server will pick that up.

**Comment by MegaJsTeam** [comment]
omg)! epic! i change webpack module and delere all console.logs ))))
stats: 'errors-only' is epic))

This is stated in the documentation?

**Comment by bebraw** [comment]
Not yet. There's #1660 in case someone wants to update the docs.
