### ISSUE TITLE
`process.cwd()` gives wrong path

### ISSUE THREAD

**Issue by Gopikrishna19** [webpack/webpack#2204]
I have opened a [StackOverflow question](http://stackoverflow.com/questions/36073874/how-to-get-node-package-consumer-directory-from-node-modules) too. Initially I thought it was weird issue with node or I was doing something wrong. But then when I did the same with vanilla javascript I did not run into the issue.

I am trying to create a simple module called `creator` that creates a folder layout with help of `mkdirp`. This is my first time writing a reusable package in node. Thought I'd give it a try with webpack too. For now, just for this issue, I am logging `__dirname` and `process.cwd()` from the `creator` inside a function called `create`. When I run the module alone, I get the correct paths:
```js
export function createLayout(config) {
  console.log(__dirname, process.cwd());
}
// E:\projects\creator E:\projects\creator
```
When I do an `npm link` to another project called `consumer`, and call this function there I get `'/'`.
```js
var createLayout = require('creator').createLayout;
createLayout();
// '/' '/'
```
Which results in various issues I mentioned in stackoverflow. 

However if I write the export file in simple js ...
```js
module.exports = {
  createLayout: function() {
    console.log(__dirname, process.cwd());
  }
}
```
I get the following log:
```
E:\projects\creator\dist E:\projects\consumer
```

Here's my `webpack.config` for the creator:
```js
module.exports = {
  entry: [
    './index.js'
  ],
  output: {
    filename: 'creator.js',
    path: __dirname + '/dist',
    library: 'creator',
    libraryTarget: 'umd'
  },
  module: {
    loaders: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loader: 'babel'
      }
    ]
  },
  externals: {
    fs: 'fs'
  }
};
```

Please help me in understanding what I am doing wrong here. Thanks

**Comment by ev1stensberg** [comment]
You may be setting the path twice. __dirname is a nodejs reference to your project path, and while you load your files, you use your function, and webpack takes this and does something like /__dirname/dist/__dirname/__dirname (proccess.cwd() ). That's my impression :smiley:

**Comment by ev1stensberg** [comment]
So: Try change your entry point where __dirname is, and then your function to be [name]/[id]/[__dirname] in your output without invoking it through your console.log

**Comment by Gopikrishna19** [comment]
@ev1stensberg Thanks for you reply, your solution works, and another solution from the stackoverflow also worked: setting `target: 'node'` in config. I am closing this issue as resolved.

Thanks to all of you.
