### ISSUE TITLE
Minified css from sass files is broken, because of a backslash in font declaration, when creating build with "-p" option

### ISSUE THREAD

**Issue by tonitone** [webpack/webpack#2206]
Hi,

if i build my sources in Webpack with the "-p" option to minified them, my styles get broken.

I don't know how the backslash after the "...14px/" comes into my css file.

~~~
.fa {
    display: inline-block;
    font: normal normal normal 14px/\ 1 FontAwesome;
...       
~~~
Thanks
Toni

**Comment by sokra** [comment]
looks like an issue in the css minification.

**Comment by sokra** [comment]
The css-loader uses `cssnano` for minimizing...

**Comment by tonitone** [comment]
https://github.com/ben-eb/cssnano/issues/158
