### ISSUE TITLE
Incremental rebuild is slower and slower

### ISSUE THREAD

**Issue by Krisa** [webpack/webpack#2211]
I couldn't find any issue related so I'm wondering if I'm the only one experiencing that, and if so, why this happens. Basically, my initial build time takes around 15s, but that's alright. The first incremental rebuild is however pretty quick and takes roughly 2.5s. However, each subsequent rebuild takes an additional 800ms to 1s more, so that after a few edit and save of, even, the same file, it will take around 10s to rebuild after 10 rebuild. And this goes up so that after some time, it's just better for me to stop the server and restart it again. I'm using webpack 2.1.0-beta.4, and I start the dev server with following command:
`webpack-dev-server -d --progress --hot --inline --watch --content-base src/ --open --info`

Below is the `module.exports` of `webpack.config.js`:
```js
module.exports = {
	// our angular app
	cache: true,
	debug: true,
	devtool: 'eval',
	metadata: metadata[app],
	target: 'web',
	entry: {
		'main': './src/startApp.js'
	},
	module: {

		loaders: [{
			test: /\.sass$/,
			loader: 'style!css!sass?sourceMap&indentedSyntax',
			include: [helpers.root('/src')]
		}, {
			test: /\.html$/,
			loader: 'html',
			include: [root('/src')]
		}, {
			test: /\.js$/,
			loader: 'babel',
			include: [root('/src')]
		}, {
			test: /\.coffee$/,
			loader: 'coffee',
			include: [root('/src')]
		}, {
			test: /\.json$/,
			loader: 'json',
			include: [root('/src')]
		}, {
			test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/,
			loader: 'url-loader?limit=10000&mimetype=application/font-woff'
		}, {
			test: /\.(ttf|eot|svg|png|jpg|otf)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
			loader: 'file'
		}, {
			test: /(\\|\/)angular\.min\.js$/,
			loader: 'imports?jquery'
		}, {
			test: /(\\|\/)ionic-angular\.min\.js$/,
			loader: 'imports?ionicCore,animate,sanitize,touch,router!exports?ionic'
		}, {
			test: /coffee\-namespace(\\|\/)index\.js$/,
			loader: 'imports?global=>undefined&this=>window'
		}],
		noParse: [
			helpers.rootNode('angular-animate/angular-animate.js'),
			helpers.rootNode('angular-sanitize/angular-sanitize.js'),
			helpers.rootNode('angular-touch/angular-touch.js'),
			helpers.rootNode('angular-ui-router/release/angular-ui-router.js'),
			helpers.rootNode('angular-translate/dist/angular-translate.js'),
			helpers.rootNode('ionic-sdk/release/js/ionic-angular.min.js'),
			helpers.rootNode('ionic-sdk/release/js/ionic.min.js'),
			helpers.rootNode('lodash/lodash.min.js'),
			helpers.rootNode('jquery/dist/jquery.min.js'),
			helpers.root('/vendor/auth-legacy/connection.js'),
			helpers.root('/vendor/ydn/index.min.js')
		]
	},
	output: {
		path: helpers.root('dist'),
		filename: '[name].bundle.js',
		sourceMapFilename: '[name].map',
		chunkFilename: '[id].chunk.js'
	},
	resolve: {
		extensions: ['', '.js', '.coffee', '.json'],
		alias: {
			acnNg: helpers.root('/src/acn-one/acn-ng'),
			acnCore: helpers.root('/src/acn-one/acn-core'),
			angularTranslateLoaderStaticFiles: helpers.root('/vendor/angular-translate-loader-static-files/angular-translate-loader-static-files'),
			app: helpers.root('/src/apps/', app, 'app'),
			salesforce: helpers.root('/vendor/auth-legacy/salesforce'),
			client: helpers.root('/src/apps/' + app),
			connection: helpers.root('/vendor/auth-legacy/connection'),
			core: helpers.root('/src/acn-one/acn-core'),
			'coffee-namespace': helpers.root('/vendor/coffee-namespace/index'),
			coreapi: helpers.root('/src/acn-one/acn-ng/components/coreapi/coreapi'),
			components: helpers.root('/src/acn-one/acn-ng/components'),
			currentTheme: helpers.root('/src/themes/'),
			forcetk: helpers.root('/vendor/auth-legacy/forcetk'),
			'forcetk.ui': helpers.root('/vendor/auth-legacy/forcetk.ui'),
			ionic: helpers.rootNode('ionic-sdk/release/js/ionic-angular.min'),
			ionicCore: helpers.rootNode('ionic-sdk/release/js/ionic.min'),
			isoCountries: helpers.root('/vendor/iso-countries/dist/countries.min'),
			'localstorage-store': helpers.root('/vendor/localstorage-store/index'),
			'logentries': helpers.root('/vendor/logentries/index'),
			md2: helpers.root('/vendor/js-md2/src/md2'),
			mobileDetect: helpers.root('/vendor/mobile-detect/mobile-detect'),
			router: '@angular/router/angular1/angular_1_router.js',
			animate: 'angular-animate',
			sanitize: 'angular-sanitize',
			touch: 'angular-touch',
			lodash: 'lodash/lodash.min.js',
			jquery: 'jquery/dist/jquery.min.js',
			'ui.router': 'angular-ui-router',
			uiRouter: 'angular-ui-router',
			'angularTranslate': 'angular-translate',
			templatesApp: helpers.root('/build/templates-app'),
			templatesCommon: helpers.root('/build/templates-common'),
			vendor: helpers.root('vendor'),
			youOne: helpers.root('/src/you-one'),
			ydn: helpers.root('/vendor/ydn/index.min')
		}
	},
	plugins: [
		new ProvidePlugin({
			'Salesforce': 'salesforce',
			'forcetk': 'forcetk',
			'LE': 'logentries'
		}),
		new CopyWebpackPlugin([{
			from: 'src/acn-one/acn-ng/components/translations/ACN_EN.json'
		}, {
			from: 'src/you-one/translations/you-one.en.json'
		}]),
		new HtmlWebpackPlugin({
			template: './src/index.webpack.tpl'
		}),
		new webpack.optimize.MinChunkSizePlugin({
			minChunkSize: Infinity
		})
	],
	// our Webpack Development Server config
	devServer: {
		port: metadata.port,
		host: metadata.host,
		// contentBase: 'src/',
		historyApiFallback: true,
		watchOptions: {
			aggregateTimeout: 300,
			poll: 1000
		}
	},
	watch: true
};
```

**Comment by Krisa** [comment]
This came a bit as a surprise as I was trying to debug something else, but I decided to remove the --hot flag temporarily and the compilation time has been reduced from 2.5s (in the best case as mentioned above), to a constant 500ms (and then 1s of browser reload) - which is pretty amazing to say the least. 

With the hot module activated, it always needed "an additional pass", with the first pass taking constantly always 400 or 500ms and the second taking from 2s upwards. Removing the hot flag, seems to have removed the necessity to make an additional pass.

Maybe you should suggest this idea here: http://webpack.github.io/docs/build-performance.html

**Comment by whitecolor** [comment]
> but I decided to remove the --hot flag temporarily

but do you use hot reloading? or what?

**Comment by whitecolor** [comment]
> but I decided to remove the --hot flag temporarily

Yes I too noticed that that with `--hot ` flat module swapping becomes slower and slower with every change. If remove it and stay with `HotModuleReplacementPlugin` it seem to work well.

**Comment by stkrzysiak** [comment]
Hey @whitecolor, I thought the --hot flag just adds the [HotModuleReplacementPlugin config on the fly](http://webpack.github.io/docs/webpack-dev-server.html#hot-module-replacement), so that is a bit surprising to me.  Does your HMR work in either case(w/ flag or manual config)?
  For me, HMR broke entirely with an upgrade from 1.12/13 -> 2.1.0-beta2/5, while using  the --hot flag.  This is in conjunction with the increasing build time for the secondary pass as reported in this ticket.  So I guess I'll possibly make a ticket for the broken HMR, and just +1 this ticket for secondary pass time is ever-increasing.  I can watch mine start at ~4s and climb to 37s in a matter of hours.

**Comment by whitecolor** [comment]
@stkrzysiak hotreload on webpack 2 is working for me, when webpack and wds installed locally, and I use `--inline` flag (so I don't put anything in `entry` except app's entry potint)

**Comment by MoOx** [comment]
Same behavior for me: --hot loading works with webpack 2, but it's really slow compared to webpack 1.
Keeping --inline make build obviously faster, but poor DX :'(

**Comment by whitecolor** [comment]
@MoOx what does --inline give?

**Comment by MoOx** [comment]
No hot loading.

I used devServer.hot  +  HotModuleReplacementPlugin in my config and hot loading is back to normal. So --hot is doing something else and it slow :)

**Comment by whitecolor** [comment]
Here I described the problems I had with hot reloading when using --inline and --hot options
https://github.com/webpack/webpack/issues/2424

Basically I end up of defining everything in config and running wds using API, not CLI.

**Comment by TheLarkInn** [comment]
@Krisa @whitecolor Are you still seeing these issues in the latest webpack builds? If so please let me know so we can update and prioritize this. 

Also, I want to confirm the following based upon what I read:
**Is the slowness resolved after you remove the `--hot` flag?**

**Comment by quanganhtran** [comment]
This is still happening to me on webpack/wds 2.2.0
I'm not using any flag besides `--env development`

**Comment by whitecolor** [comment]
I think for me it is ok now.

**Comment by quanganhtran** [comment]
for me, I heard out that `multiStep` of HMR is not working with `html-webpack-plugin` at the moment, so I tried disabling it, and build time became constant again
