### ISSUE TITLE
Custom Loaders 

### ISSUE THREAD

**Issue by ev1stensberg** [webpack/webpack#2214]
Hi! I got a suggestion on custom loader loading. Let me show how it's intended to be used:

**1. User makes or add an array in 'webpack.loaders.js' and this gets registered by webpack.**

**2. They refer to it in 'webpack.config.js' as their array and webpack notices this. Note that I've imported the module. This was for testing.**

**3. User has a safe ecosystem where the errors that are with loaders are addressed much more specific. **
--------

The 'webpackLoaderFile.js' is what you integrate into 'webpack-core'. I actually got this to work, but webpack didn't pick this up as a loader, and therefore it didn't transpile my code, but the code ran smoothly. 
**_Also, I may not be the best coder, so feel free to take this and make adjustments. _**

edit: the forEach function takes just the 'load' and not an empty array, which means it needs to be changed for an array too, *
edit: add module.exports in the webpack.loaders.js if needed  *

![skjermbilde 2016-03-20 kl 22 52 43](https://cloud.githubusercontent.com/assets/16735925/13907445/985cf3e8-eeee-11e5-8968-7e278ab4ab60.png)
![skjermbilde 2016-03-20 kl 22 52 54](https://cloud.githubusercontent.com/assets/16735925/13907446/985f77ee-eeee-11e5-8dde-934463dcd8b6.png)
![skjermbilde 2016-03-20 kl 22 53 02](https://cloud.githubusercontent.com/assets/16735925/13907447/9861bae0-eeee-11e5-9e7e-f84880c749d7.png)

**Comment by jhnns** [comment]
Thank you for your suggestion :)
Could you tell us: what problem does this solve?

**Comment by ev1stensberg** [comment]
When having large applications, you tend to have very messy webpack config files, ex: webpack.prod.config.js, webpack.dev.config.js. This is a proposal of how  to make it cleaner to integrate your loaders into webpack, which many will favor when scaling their apps. 

Though this code isn't good enough to be integrated, I hope you got what I was thinking about when I explained this earlier. If not, feel free to contact me for more intel! :smile:

**Comment by jhnns** [comment]
> When having large applications, you tend to have very messy webpack config files, ex: webpack.prod.config.js, webpack.dev.config.js

Yes, that's true. However, you're free to split up your code as you would do it in your regular app. We deliberately made the `webpack.config.js` a JS-file instead of a static JSON. Just put the common stuff into separate modules and require it :grinning:

Thus new webpack users won't have to learn new magic features like auto-loading some file. And developers joining your project can immediately understand what's going on: it's just a module which requires other modules.

Does this solve your problem?

**Comment by ev1stensberg** [comment]
Yea! It somehow did! The main point here was to encourage you to implement loaders in an own webpack.config.loader.js file, and include them in the docs, so users can see that loaders could be split up, and you support it. I know many would think this is a nice feature if you want to include it in webpack.  :smiley_cat:

**Comment by jhnns** [comment]
It definitely is a good practice. But why should we implement something that is already available for free :grinning:?

Plus: your code contains explicit `require()` which is better for newcomers that don't need to learn some magic auto-loading.

**Comment by ev1stensberg** [comment]
Yeah I know! But I'm just proposing a nice feature :smiley:
