### ISSUE TITLE
Less @import absoulte path mixin less

### ISSUE THREAD

**Issue by leaven** [webpack/webpack#2220]
My project likes this,
├── components
│   ├── linecard
│   │   ├── linecard.jsx
│   │   └── linecard.less
│   └── searchbox
│       ├── searchbox.jsx
│       └── searchbox.less
└── static
    ├── css
    │   ├── base.less
    │   ├── components
    │   │   ├── button
    │   │   └── font
    │   ├── csslib.less
    │   └── reset.less
**csslib.less** is a mixin lib，in component less, csslib  can be  imported like this, `@import '../../static/css/csslib.less'`.
I don't wanna use relative path.And I wonder if there were some configs like **resolve.root** in js so it can be imported with absoulte path like `@import 'static/css/csslib.less'`

**Comment by bebraw** [comment]
Can you try setting up a [resolve.alias](https://webpack.github.io/docs/configuration.html#resolve-alias) pointing at `static`?

**Comment by leaven** [comment]
@bebraw  Thank you，finally I solved this by 
` resolve.alias: {
      'css': path.resolve('./common/static/css')
    },`
 and import like `@import '~css/csslib.less';`
