### ISSUE TITLE
Maybe, there needs some code analysis direction in wikis or docs.

### ISSUE THREAD

**Issue by whtoo** [webpack/webpack#2227]
Thanks to your work on webpack.In fact,I'd like to use it and write a bit of loaders.
But when I dig up,I find **the code logic of webpack is so _twisted_**!
Therefore,please give some attention to this issue and wirte some wikis for introducing
webpack to dev.

**Comment by pksjce** [comment]
This issue was moved to webpack/webpack.io#115
