### ISSUE TITLE
Webpack doesn't seem to find module when absolute context path is not based off current directory

### ISSUE THREAD

**Issue by dschissler** [webpack/webpack#223]
My folder structure looks like this:

```
project
    app
        public
            entry.coffee
    build
        webpack.config.js
    dist
    test
```

My webpack.config.js looks like this:

```
module.exports = {
    cache: true,
    context: path.resolve(__dirname + "/../app/public"),
    entry: "./entry.coffee",
...
```

I'm receiving this error:

ERROR in Entry module not found: Error: Cannot resolve file or directory ./entry.coffee in /usr/local/webprojects/webpack/app/public

but the file '/usr/local/webprojects/webpack/app/public/entry.coffee' does exist.

**Comment by towry** [comment]
This error may be caused by a syntax error in `package.json`.

**Comment by saschagehlich** [comment]
@towry's reply is the solution.

**Comment by ameensol** [comment]
@saschagehlich @towry could either of you elaborate? I'm running into the same issue and I can't figure out what's causing it.

**Comment by saschagehlich** [comment]
package.json needs to be in valid JSON syntax

**Comment by ameensol** [comment]
Thanks. Mine was. Turns out I was using ``webpack build`` instead of just ``webpack`` as my command, which strangely gave me the same error and led me here...

**Comment by richardscarrott** [comment]
thanks @towry, that's exactly what I experienced

**Comment by rawberg** [comment]
could also happen if you haven't installed `babel-loader`

**Comment by jmacdonald-tm** [comment]
Just had this same issue and @towry's answer resolved it. Just a trailing comma in package.json breaking the json. Thanks!

**Comment by smrq** [comment]
I just ran into this using the CLI.

```sh
$ webpack index.js
```

is valid, but

```sh
$ webpack index=index.js anotherPage=anotherPage.js
```

fails with this error.  The solution is to specify the full relative path:

```sh
$ webpack index=./index.js anotherPage=./anotherPage.js
```

**Comment by landed1** [comment]
My json is fine linted ok.
I have the following structure
ROOT/src/entry.js

ROOT:webpack.config.js
module.exports = {
  entry: './src',
  output: {
    path: 'build',
    filename: 'bundle.js',
  },
};

I tried ../src /src and src so I am a bit at a loss..anyone any ideas ? TY

**Comment by adjohnson916** [comment]
@towry Was right for me, I had invalid syntax in my `package.json`, correcting that fixed this.

**Comment by lancekuttner** [comment]
I had to ensure that I displayed the full extension e.g. './MyComponent.jsx' instead of './MyComponent'

**Comment by rbosneag** [comment]
@lancekuttner you could have used `resolve` in `webpack.config.js` to allow `.jsx` extensions:
```

  resolve: {
    extensions: [".jsx", ".json", ".js"]
  },
```

**Comment by totymedli** [comment]
For me this happened because in my `entry` object I wrote:

```
app: path.resolve(__dirname, '/test.js'),
```

While I should have written one of these:

```
app: path.join(__dirname, '/test.js'),
app: path.join(__dirname, 'test.js'),
app: path.resolve(__dirname, 'test.js'),
```

The problem was that `path.resolve` will [ignore any parameters](http://stackoverflow.com/a/39836259/1494454) given to it before the last parameter that starts with a `/`.

So `path.resolve(__dirname, '/test.js')`, will return `/test.js` instead of `/path/of/your/project/directory/test.js`.

**Comment by matthewmueller** [comment]
thanks @rawberg. I also ran into this because i didn't have the `babel-loader` installed, this error is quite misleading.

**Comment by dsslimshaddy** [comment]
@towry  is the best in the world

**Comment by dt-rush** [comment]
This happened to me, and this issue was that had the following:

```
    entry: {
	'app/public/bundle.js': 'app/index.js',
	'app/server.js': 'app/server.js'
    },

    output: {
	path: path.resolve (__dirname, 'dist'),
	filename: '[name]'
    },
```

... instead of:

```
    entry: {
	'app/public/bundle.js': './app/index.js',
	'app/server.js': './app/server.js'
    },
    output: {
	path: path.resolve (__dirname, 'dist'),
	filename: '[name]'
    }
```

See if you can even find the difference (and once you do, see if it should even matter... relative paths should be considered to be rooted at whatever "./" is by whatever is interpreting the relative path...... no?)

**Comment by scriptmaster** [comment]
I had a similar issue and I added this line to make it resolve:

```
  resolve: {
    extensions: [ '', '.js' ],
    ...
  }
```

Thought I could share my solution to help someone.

**Comment by adambugaj** [comment]
What is the problem in this webpack entry?

![image](https://user-images.githubusercontent.com/23665681/35690275-c1129490-0775-11e8-90c6-f89ae67b2436.png)

**Comment by irenebijo** [comment]
Hi 
I am unable to load  one of the modules. I am getting an error as pasted below.
![image](https://user-images.githubusercontent.com/6331167/44160878-5d385b80-a081-11e8-9c6e-fcac971fc321.png)

This is the code , i have used to run the above
---------------------
var path = require('path');

module.exports = {
  entry: './app/scripts/index.js',
  output: {
    filename: 'main.bundle.js',
    path: path.resolve(__dirname, 'target/dest/js')
  },

};
---------------------

![image](https://user-images.githubusercontent.com/6331167/44160925-83f69200-a081-11e8-9432-ec821983476f.png)

custom-slick-carousels was  there in the desired path as pasted below.

![image](https://user-images.githubusercontent.com/6331167/44161058-d33cc280-a081-11e8-8d60-84f655eba86e.png)

**Comment by AlvinLaiPro** [comment]
same problem!

**Comment by th0rgall** [comment]
@dt-rush thanks for [your answer](https://github.com/webpack/webpack/issues/223#issuecomment-338299435). It helped me solve a nasty similar problem.

In my project meant for use with node.js & the browser I include a module that uses the package.json [`browser` field](https://github.com/defunctzombie/package-browser-field-spec) to provide an alternative .js script for a script that is dependent on Node.js-specific libraries.

```
{
  "name": "moduleName",
  "browser": {
    "http.js": "browser-http.js"
  },
  "main": "http.js"
...
```

Webpac  couldn't find this module (used in a browser target project). However, this module works fine in pure node.js projects and for web with browserify. After many hours of debugging, it was indeed a missing `./` in front of the file paths. A working version of the included module:

```
{
  "name": "moduleName",
  "browser": {
    "http.js": "./browser-http.js"
  },
  "main": "./http.js"
...
```

**Comment by evilebottnawi** [comment]
@th0rgall should works fine, can you create minimum reproducible test repo?

**Comment by Arlen22** [comment]
In my case I had `resolve: { extensions: [] }` near the top of the object and `resolve: { alias: {} }` at the end, which took a while to discover because both resolves only had one object, so I just thought of them as alias and extensions, lol.
