### ISSUE TITLE
worker is always cached, despite changing file

### ISSUE THREAD

**Issue by ianks** [webpack/webpack#2231]
I am using worker-loader to load a web-worker. The worker exists in its own file, and is running properly. However, whenever I make changes to the file, webpack does not seem to update the workers code. It is forever cached until i restart webpack-dev-server.

I am currently using webpack 2.1.0-beta.4

**Comment by TheLarkInn** [comment]
@ianks are you still having issues with this defect in later webpack 2.1.0-beta builds?

**Comment by ianks** [comment]
@TheLarkInn Yes I am.

**Comment by bebraw** [comment]
Can you confirm this against the current stable version?
