### ISSUE TITLE
Resolving dependency after splitting

### ISSUE THREAD

**Issue by wyuenho** [webpack/webpack#2232]
I'm working on an app where I need to load JSON dependencies at runtime, these JSON deps do not have well-known paths until the app is served. Here's what I'd like to do:

1. Have the server-side bootstrap a path so the app can construct the moduleID paths for `require()` at runtime.
2. Code split modules, but have webpack ignore some rather complex dynamic require in the entry chunk. Basically, I'd like webpack to stop attempting to resolve these deps statically.
3. The app will construct the paths at runtime and load the required JSON dependencies on-demand, as soon as the JSON deps are loaded, the app should work as expected.

I'm using 2.1.0-beta.4, after compiling, I get a bunch of Critical dependency warnings telling me the deps cannot be statically extracted. Is there a way to configure webpack in such a way that I can accomplish the 3 points above?

Thanks

**Comment by wyuenho** [comment]
For anyone wondering, I'd love to be able to get rid of this in the compiled bundles.

```
!(function webpackMissingModule() { var e = new Error(\"Cannot find module \\\".\\\"\"); e.code = 'MODULE_NOT_FOUND'; throw e; }()).ensure(dependencies, function (require) {
```

**Comment by sokra** [comment]
`require.ensure` is not for runtime loading. Use something like async.js for this.

**Comment by wyuenho** [comment]
Then what does this mean?

https://gist.github.com/sokra/27b24881210b56bbaff7#code-splitting

**Comment by wyuenho** [comment]
@sokra I'm attempting to migrate to Webpack, currently I'm using browserify + factor-bundle + [bundle-collapser](https://github.com/substack/bundle-collapser) to do code splitting. I use [promisescript](https://github.com/terinjokes/promisescript) to load the split bundles and `require` them immediately after load.

When converting this setup to Webpack, I found out that I couldn't recreate this in Webpack. I've made an entry chunk that contains the runtime, and the rest of the split bundles are converted to Webpack normal chunks. There does not appear to be a map of chunk => module.id generated in the entry chunk, and there doesn't seem to be a way to get that at run-time using Webpack's __webpack_* APIs. Essentially, I'm looking for something like bundle-collapser for Webpack, is there such a thing? Please advice.

**Comment by wyuenho** [comment]
Okay so by looking at some of the generated normal chunks, I've found out that the webpackJsonp function wrapping the normal chunk will install and require the chunk. However, since my code does need to be able to translate a file system module path to a Webpack module ID, the issue in the above comment still stands.

In addition, the type of the value to `webpackJsonp` 's `executeModule` parameter is wrong in the chunks. `executeModule` should be a module ID that gets passed to `__webpack_require__` directly, but it's passed as an array of a number now. This is likely a bug in Webpack 2.1.0 beta 8.

**Comment by wyuenho** [comment]
In Webpack 1, the inverse of the map that I'm looking for seems to be dumped `requireEnsure`, is there a plan to bring that back to Webpack 2 and expose that? Maybe something like `__webpack_require__.resolve`?

**Comment by psimyn** [comment]
@wyuenho Did you find solution? Using async.js or something webpack side?

**Comment by wyuenho** [comment]
No. We need to be able to resolve chunks as requirable modules at runtime, Webpack explicitly prohibits that.
