### ISSUE TITLE
AMD/UMD externals define() nested modules

### ISSUE THREAD

**Issue by viveleroi** [webpack/webpack#2234]
When source code has the following:

    require('lodash.foreach');

And webpack is configured for either UMD or AMD, there appears to not be a way to generate the correct `define()` block.

Using an external configuration of `'lodash.foreach': 'var _.forEach'` generates the following in the compiled output:

    define(['_.forEach'], factory};

However, I need a way to configure it as:

    define(['lodash'], factory};

With the `module.exports` assigned to `_.forEach`.

The only alternative I can figure is to include lodash entirely in our project, which includes way too much code in our bundled files.

**Comment by bebraw** [comment]
You could set it up like this:

```javascript
  externals: {
    'lodash.foreach': {
        commonjs: 'var _.forEach',
        commonjs2: 'var _.forEach',
        amd: 'lodash',
        root: 'lodash' // not sure about this
    }
  },
```

**Comment by viveleroi** [comment]
I didn't realize that was an acceptable configuration, the docs could explain that better. I'm giving it a shot but because I'm including multiple lodash methods it's generating less than ideal code:

`define(["lodash", "lodash", "lodash", "lodash", "lodash", "lodash"], factory);`

I'm not seeing the same errors though, which is promising.

**Comment by bebraw** [comment]
Yeah, the code probably doesn't have any optimization for this particular case. If it was optimal, it would probably fold those imports into one. That said, it likely works. You just get some redundant code.

**Comment by viveleroi** [comment]
Ok, I'm not sure this will work either. I'm toying around with this and while the `define` block is including `lodash` correctly, webpack isn't assigning the properties correctly. So every single include is now mapped as `lodash`, not `forEach = _.forEach`

**Comment by bebraw** [comment]
That's expected, yeah. I can see how that could fail.

Have tried something like https://github.com/lodash/babel-plugin-lodash ? Maybe changing the import style is the key?

**Comment by viveleroi** [comment]
That plugin *helps*, but doesn't yet do enough to qualify as a solution.

- For some reason I specifically need to set the external as `{ _: 'lodash' }` which is backwards. Webpack starts thinking the name of the library is `_` and generates `define(['_'], factory);`. 
- I haven't looked at why, but the final code via this plugin include 143k of unwanted lodash code. When I have the portions I want specifically included the final file is 471k, but when this plugin tree shakes lodash for me it gives me a 614k file.

**Comment by viveleroi** [comment]
Looks like I can resolve the first issue by specifically telling webpack which name to use:

```
externals = {
        lodash: {
            commonjs: 'lodash',
            commonjs2: 'lodash',
            amd: 'lodash',
            root: '_'
        }
    };
```

For the second issue I'll run a diff and see what's being included that shouldn't be. I'm sure it'll be an issue for the babel-lodash plugin.

**Comment by sokra** [comment]
I think externals also accept an array, which can be used to get the property of an object.

``` js
externals: {
    'lodash.foreach': {
        commonjs: 'lodash.foreach',
        commonjs2: 'lodash.foreach',
        amd: ['lodash', 'forEach'],
        root: ['_', 'forEach']
    }
},
```

If this doesn't work, you can make a PR.
