### ISSUE TITLE
Installing webpack 1.12.14 makes my computer restart

### ISSUE THREAD

**Issue by formix** [webpack/webpack#2236]
command: `npm install -g webpack`
node 5.8
npm 3.8.1
windows 10

**Comment by sokra** [comment]
That's sad, but propably not related to webpack...

**Comment by formix** [comment]
@sokra: yeah, brand new computer but still... Windows 10. That said, I installed Linux and everything works fine in there. But that may be an issue that the core webpack team want to look at.
