### ISSUE TITLE
debugging module.hot.accept

### ISSUE THREAD

**Issue by fab1an** [webpack/webpack#2237]
I use hot-reloading in my application, sometimes it works, sometimes, when I restructure my app, it doesn't:

I have a class `ReloadableBehaviour` that I instantiate like this: `new Reloadable...(filename)`

In the class I use something like

```
module.hot.accept("behaviour/" + this.filename, () => {
    console.log("test");
    ...
});
```

If I change the file referenced by `filename`, webpack tells me that the module isn't accepted.

I even tried

```
let id = require.context('behaviour/').resolve(this.filename);
console.log("accepting: ", id);
module.hot.accept(id, () => {
...
})
```

which shows the correct id is being passed to `module.hot.accept`, but it doesn't work nevertheless.

How can I debug this?

**Comment by jauco** [comment]
HMR is kinda finicky, and require.context is finicky as well. I usually start with a known working version and then move that to the code that isn't working and then watch when it fails. In your case it might be that the module that calls module.hot.accept is not the module that is doing the `require()`ing (i.e. is not the parent module)

Here's a version that should be working:
```

var context = require.context("./filesToLoad", false, /\.js$/);
var modules = {};
context.keys().forEach(function (key) {
  var module = context(key);
  modules[key] = module;
  customReloadLogic(key, module, false);
})

if (module.hot) {
  module.hot.accept(context.id, function () {
    //You can't use context here. You _need_ to call require.context again to
    //get the new version. Otherwise you might get errors about using disposed
    //modules
    var reloadedContext = require.context("./filesToLoad", false, /\.js$/);
    //To find out what module was changed you just compare the result of the
    //require call with the version stored in the modules hash using strict
    //equality. Equal means it is unchanged.
    var changedModules = reloadedContext.keys()
      .map(function (key) {
        return [key, reloadedContext(key)];
      })
      .filter(function (reloadedModule) {
        return modules[reloadedModule[0]] !== reloadedModule[1];
      });
    changedModules.forEach(function (module) {
      modules[module[0]] = module[1];
      customReloadLogic(module[0], module[1], true);
    });
  });
}

function customReloadLogic(name, module, isReload) {
  console.log("module " + name + (isReload ? " re" : " ") + "loaded");
}

```

Save this to hmr_test.js in an empty directory and run

```
$ mkdir filesToLoad
$ echo "console.log('a')" >> filesToLoad/a.js
$ npm install webpack webpack-dev-server
$ ./node_modules/.bin/webpack-dev-server hmr_test.js  --hot --inline
```

That should work. Then change hmr_test piece by piece to make it look like what you're doing now and let us know what change breaks it.

**Comment by jauco** [comment]
I've published the example to github so it's easier to get started: https://github.com/jauco/webpack-hot-module-reload-with-context-example @sokra any non-idiomatic code that I should fix?

**Comment by fab1an** [comment]
I think the problem arises when you `module.hot.accept` a require-context and inside the callback function `require` the module again.

**Comment by sokra** [comment]
`module.hot.accept` doesn't accept expressions. Only compile-time constants. Just like `require`. webpack need to be able to resolve it while compiling.

**Comment by fab1an** [comment]
@sokra: I know, that is not the problem I was facing.

I think another "problem" is that `module.hot.accept` only registers one callback per given context, is that right? I basically had a class which `module.hot.accept`ed a filename. I instantiating the class multiple times, but only one callback fired.
It that a global thing or is it per file?

Maybe add a warning to the console that `accept`-handlers are being overwritten?

**Comment by sokra** [comment]
You can only have one accept handler, but feel free to implement multiple handlers on top of this:

``` js
var handlers = [];
module.hot.accept(function() {
  handlers.forEach(function(handler) { handler() });
});

handlers.push(function() { /* a */ });
handlers.push(function() { /* b */ });
```

**Comment by sokra** [comment]
> It that a global thing or is it per file?

module-level

**Comment by bartlomieju** [comment]
@jauco I used your solution, yet I'm still getting this warning: `[HMR] unexpected require(7) from disposed module 9`. Any idea what might cause that?

**Comment by bebraw** [comment]
Closing as this was answered.
