### ISSUE TITLE
Is it possible that webpack can require remote file and inject as <script> tag?

### ISSUE THREAD

**Issue by littlee** [webpack/webpack#2240]
sometimes I will want to use a third-party SDK,
so I was wondering code like below will work
```
require('http://www.somewhere.com/sdk.js');
```

and a `<script>` tag will insert to the page
```
<script src="http://www.somewhere.com/sdk,js"></script>
```

**Comment by hkrutzer** [comment]
No, see https://github.com/webpack/webpack/issues/150#issuecomment-32756166
https://github.com/walmartlabs/little-loader is a really small script loader.
