### ISSUE TITLE
resolve.fallback not working with resolve.alias ?

### ISSUE THREAD

**Issue by yonida** [webpack/webpack#2243]
I have the following project structure:
```
a
a/node_modules/x
a/node_modules/b
a/node_modules/b/node_modules/y
a/node_modules/b/node_modules/c
```
`a` is my main project and I want to make changes in my local `c` project and reflect in `a`
I used `resolve.alias` to point `c` to my local dir.
Some of `c` dependencies are located in `a`, and some in `b`, and when running webpack I'm getting the following errors:
`Module not found: Error: Cannot resolve module 'x' in c`
`Module not found: Error: Cannot resolve module 'y' in c`

Using `resolveLoader.fallback` fixed my `babel` loader errors, but i'm still having issues with "regular" modules that I require in `c`.
I tries using `resolve.fallback`, but it did not fix the errors.

I did find a way to workaround this, by setting specific aliases to every module `c` was dependant on that was not installed directly under its `node_modules` (for example: `x` and `y`)

Why isn't `resolve.fallback` working in this case?
This could be related to #784

**Comment by yonida** [comment]
My mistake, everything works.

**Comment by eranimo** [comment]
Can you explain what you did wrong?
