### ISSUE TITLE
Harmony function export randomly conflicts with var injection (ProvidePlugin)

### ISSUE THREAD

**Issue by Kovensky** [webpack/webpack#2246]
It seems that the order the `harmony export` and the `WEBPACK VAR INJECTION` entries get emitted in the output file is undefined, which causes webpack (2.1.0-beta.4) to emit incorrect syntax some of the time.

I am injecting the `whatwg-fetch` polyfill using ProvidePlugin as suggested in `whatwg-fetch`'s README:

```js
new webpack.ProvidePlugin({
  'fetch': 'imports?this=>global!exports?global.fetch!whatwg-fetch'
}),
```

With a sample file like:

```js
export async function theExport (param) {
  const req = await fetch('/resource')
  return await req.body()
}
```

The code is normally emitted somewhat like:

```js
/* WEBPACK VAR INJECTION */(function(fetch) {
   ... transpiled code (babel-loader) ...
/* harmony export */ Object.defineProperty(exports, "a", {configurable: false, enumerable: true, get: function() { return theExport; }});
/* WEBPACK VAR INJECTION */}.call(exports, __webpack_require__(/*! imports?this=>global!exports?global.fetch!whatwg-fetch */ 401)))
```

The code at the end, however, is occasionally invalid javascript:

```js
/* WEBPACK VAR INJECTION */}.call(exports, __webpack_require__(/*! imports?this=>global!exports?global.fetch!whatwg-fetch */ 401)))/* harmony export */ Object.defineProperty(exports, "a", {configurable: false, enumerable: true, get: function() { return theExport; }});
```

The `Object` identifier comes right after an unterminated statement, which is a syntax error. Even adding a `;` or newline doesn't help, as `theExport` is not available outside of the `WEBPACK VAR INJECTION` block. However, rerunning `webpack build`, or even just adding / removing random statements while `webpack watch` is running has a high chance of generating correct code.

**Comment by sokra** [comment]
fixed by https://github.com/webpack/webpack/commit/d483ed287865e81d4b3ac68d13c510b2d6801175
