### ISSUE TITLE
file-loader url not loading using webpack dev server

### ISSUE THREAD

**Issue by esayemm** [webpack/webpack#2248]
Thanks for all the work on webpack, it's awesome!
file-loader url works for built project, but when using webpack dev server it doesn't work. 

As seen below, the png image is being served from the dev server. If I hit localhost:8080/[hash].png directly it loads. And if I set the background-image: url in chrome debugger it also works, but the strange thing is the debugger setting I set is the exact same value as in the generated css rule as seen in the second screenshot. Is dev server not serving the css relative to the root as bundle.js is? If that is the case what is the solution for using url() inside css files?

Thanks!

<img width="273" alt="screen shot 2016-03-28 at 11 26 49 pm" src="https://cloud.githubusercontent.com/assets/4362861/14102043/27b4dda8-f54d-11e5-90e7-46d440626b58.png">

<img width="538" alt="screen shot 2016-03-28 at 11 26 23 pm" src="https://cloud.githubusercontent.com/assets/4362861/14102032/177aa06c-f54d-11e5-9a20-b46681cf6fb8.png">

**Comment by sokra** [comment]
It's relative to the HTML file. If you are using CSS SourceMaps it doesn't have a orgin and you need to use absolute urls.

**Comment by esayemm** [comment]
Ah ok, I turned off SourceMaps and something like `url(~assets/images/foo.png)` worked. I'm assuming I can't expect that line to work with SourceMaps on? Anyway that'll do, I think it's also fine to just use url-loader with no limits for dev. Thanks!
