### ISSUE TITLE
Webpack has issues with loading nested npm module

### ISSUE THREAD

**Issue by legaev-stas** [webpack/webpack#2249]
I am using npm for managing client libs. My application has dependency to legacy lodash (2.4.1) and I am trying to add redux (3.3.1), which also has own lodash (^4.2.1) dependency. Accordingly to NPM 3.3.12 I have following structure
-node_modules
----lodash@2.4.1
----redux@3.3.1
--------lodash@4.2.1

While I am trying to build my application with dependency to **redux** I get an error:
[log.txt](https://github.com/webpack/webpack/files/193269/log.txt)

Please see the example attached:
[bug.zip](https://github.com/webpack/webpack/files/193294/bug.zip)
Just extract and run:
1. npm i 
2. webpack

So, the issue is that during building my application webpack does not aware about nested/own dependencies of redux package.

**Comment by sokra** [comment]
``` js
    resolve: {
        root: __dirname,
        modulesDirectories: [
            __dirname,
            path.join(__dirname, 'node_modules')
        ]
    },
```

should be

``` js
    resolve: {
        root: __dirname,
        modulesDirectories: ['node_modules']
    },
```
