### ISSUE TITLE
webpack externals path

### ISSUE THREAD

**Issue by hellatan** [webpack/webpack#2253]
I've been trying to figure this out for sometime now but keep on hitting the a dead end. I have a module like this:

```js
module.exports = require('some-other-module');
```
When I bundle my app and this file is referenced, it is output like this:

```js
/***/ },
/* 100 */
/***/ function(module, exports) {

	module.exports = require("some-other-module");

/***/ },
/* 101 */
/***/ function (module, exports, __webpack_require__) { ... }
```

I'm starting up my app with [`pm2`](https://github.com/Unitech/pm2) and I keep on getting this error in the logs:

```
app-1 (err): Error: Cannot find module 'some-other-module'
app-1 (err):     at Function.Module._resolveFilename (module.js:337:15)
app-1 (err):     at Function.Module._load (module.js:287:25)
app-1 (err):     at Function._load (/usr/lib/node_modules/pm2/node_modules/pmx/lib/transaction.js:62:21)
app-1 (err):     at Module.require (module.js:366:17)
app-1 (err):     at require (module.js:385:17)
app-1 (err):     at Object.<anonymous> (/app/webpack:/external "some-other-module":1:1)
app-1 (err):     at __webpack_require__(/app/webpack:/webpack/bootstrap c8e7535f9701d2962e67:19:1)
app-1 (err):     at Object.<anonymous> (/app/webpack:/~/package/file2.js:11:1)
app-1 (err):     at __webpack_require__(/app/webpack:/webpack/bootstrap c8e7535f9701d2962e67:19:1)
app-1 (err):     at Object.<anonymous> (/app/webpack:/~/package/file1.js:18:1)
```

A couple questions:
1. `webpack:/external` - is this the same as defining an external under the `config.externals` property in the `webpack.config.js` file?
2. If that is the case for #1, then by doing `module.exports = require(module)` does that make webpack consider that as an external dependency when it is being compiled?

I have not added `some-other-module` as an external in any of my webpack configs so I'm confused as to why i'm seeing `webpack:/external` in that path. As you can see, it resolves `/app/webpack:/~/package` and I would have expected `some-other-module` to be resolved like `/app/webpack:/~/some-other-module` instead.

thoughts?

addendum:
I have a similar module like so:

```js
'use strict';
var anotherModule = require('another-module');
console.warn('this-module.js is deprecated.  Use another-module instead');
module.exports = anotherModule;
```

which outputs:
```js
/* 200 */
/***/ function(module, exports, __webpack_require__) {

	'use strict';
	var anotherModule = __webpack_require__(334);
	console.warn('this-module.js is deprecated.  Use another-module instead');
	module.exports = anotherModule;


/***/ },
/* 201 */
/***/ function(module, exports, __webpack_require__) { ... }
```

and as far as i can tell, this is not throwing any errors

**Comment by sokra** [comment]
Can you post your configuration? Is `some-other-module` installed?

**Comment by hellatan** [comment]
sorry, the log file i was referencing was really hard to decipher when certain errors happened (as in lacked timestamps!!!). My "use case" doesn't seem to be a use case as far as i can tell.
