### ISSUE TITLE
What webpack do in "optimize-chunk-assets" and "optimize-assets" stages?

### ISSUE THREAD

**Issue by Strate** [webpack/webpack#2257]
This is how my build looks like in incremental (watch) mode:
```
744ms build modules   
13ms seal
90ms optimize
28ms hashing
32ms create chunk assets
6ms additional chunk assets 
2368ms optimize chunk assets
1792ms optimize assets
58ms emit
Hash: d3cedff3f49d9942031a
Version: webpack 1.12.14
Time: 5363ms
```
This is not initial build. As you see, most time spent on optimize-chunk-assets and optimize-assets steps.
What webpack do in that stages?

**Comment by sokra** [comment]
by default nothing. Plugins do stuff here. i. e. the minimizing happens in optimize-chunk-assets.

**Comment by Strate** [comment]
but I have no plugins at all in my config. Seems that there is some built-in thing... How can I debug that?

**Comment by Strate** [comment]
RemoveParentModulesPlugin built-in runs in "optimize chunk assets"
SourceMapDevToolPlugin builtin runs in "optimize assets"

**Comment by PaquitoSoft** [comment]
@Strate did you find any way to disable _RemoveParentModulesPlugin_ in development mode?
Thanks.

**Comment by Strate** [comment]
@PaquitoSoft no, I did not. But I don't look to that deeply.
