### ISSUE TITLE
webpack --watch is not working on windows if root folder contains '(' or ')' in its name

### ISSUE THREAD

**Issue by homelchenko** [webpack/webpack#2258]
Hi,

I'm doing one of the tutorials that involves using webpack in watch mode, I noticed that whenever my 'root' (or rather current folder) contains '(' or ')' symbols in its paths, watching is not happening.

Am I missing anything? Can I tweak it in some way to get correct watching behaviour?

**Comment by homelchenko** [comment]
Sorry, forgot to mention. webpack version is 1.12.14

**Comment by vlad75r** [comment]
It's not just the root folder - it gets broken if there's a folder with '(' or ')' anywhere within the path to the root...

**Comment by shshaw** [comment]
Experiencing the same thing on OS X. Would love a solution for this, as most of my projects live in a Dropbox business account which has parentheses in the folder name that cannot be changed.

**Comment by RickyRomero** [comment]
I have the same problem, Dropbox for Business appends the parentheses to the folder name like so:

    ~/Dropbox (Personal)/
    ~/Dropbox (Company Account Name)/

I need to work outside of Dropbox because of this bug.

**Comment by Lutreer** [comment]
I the same thing on gulp and fis

**Comment by shshaw** [comment]
Tried to isolate the issue, and ran a simple test using only watchpack 1.1.0 on a folder with parenthesis. File change detection worked without a hitch.

**Comment by SpaceK33z** [comment]
This is most probably an issue in chokidar, see https://github.com/paulmillr/chokidar/issues/533. There is a [PR open](https://github.com/paulmillr/chokidar/pull/535) to fix it.

**Comment by Eccenux** [comment]
Seem like it's not only the braces problem. Exclamation character in path will also give you all kinds of problems on Windows (at least on Windows 10).

Example path causing problems: `c:\test\webpack\!_abc\`.

Problems:

1. `webpack entry.js bundle.js` will give you: `ERROR in Entry module not found: Error: Cannot resolve directory 'c:\test\webpack' in c:\test\webpack\!_abc`. You can workaround this issue by creating a simple `webpack.config.js`.
2. Watch will not work (even with `webpack.config.js`). `webpack --watch` will not refresh `bundle.js` after `entry.js` chnages.

No workaround for point 2 other then just not using special characters in your path.

**Comment by bebraw** [comment]
Moved to https://github.com/webpack/webpack-cli/issues/20.
