### ISSUE TITLE
Inconsistent behaviour when saving

### ISSUE THREAD

**Issue by latviancoder** [webpack/webpack#2261]
I've been using webpack-dev-server (gulp) with HMR for a long time now, and the larger the project gets (around 1000 files in 100 directories, 8 entry points), the more often I notice saving files doesn't trigger any reaction.

I mean, gulp console doesn't say "bundle is now INVALID", browser console doesn't say "App updated. Recompiling". Bundle doesn't get built, browser doesn't get refreshed. This happens every ~5th save or so.

I've tried to somehow understand the problem better, maybe some specific library/file/folder is the culprit, but to no avail. 

I am using Windows.

Is this a known problem? Do you have any ideas how I can solve this? Or how I can somehow debug this better.

**Comment by bebraw** [comment]
Can you provide a test case?
