### ISSUE TITLE
Please aid migration of 1.0 configuration in Webpack 2.0

### ISSUE THREAD

**Issue by pornel** [webpack/webpack#2262]
I'm trying to test Webpack 2, but I've got a complex configuration of resolvers and loaders. 

It would be helpful if Webpack 2 detected configuration directives from Webpack 1, and either supported them, or shown a warning that explains how to achieve the same thing in v2.

**Comment by bebraw** [comment]
Please track [webpack-cli](https://github.com/webpack/webpack-cli). They provide a migration tool exactly for this purpose.
