### ISSUE TITLE
Uncaught TypeError: Cannot read property 'apply' of undefined

### ISSUE THREAD

**Issue by l3ve** [webpack/webpack#2264]
if build single jsx ,everything will be ok.or will no.
and it's all right when i use  `webpack —watch` to build at first,but once i change the code,will throw the error.  the jsx just like this:
```javascript
import {Provider} from 'react-redux';
``` 
my `webpack.config.json` configure like this:
```javascript
entry: {
        “first”: ['jsx/first.jsx'],
        “second”:['jsx/second.jsx']
},
output: {
        path: 'assets',
        publicPath: 'assets',
        libraryTarget: 'umd', 
        umdNamedDefine: true,
        filename: "[name].js"
},
loaders: [
        {
            test: /\.(js|jsx)$/,
            loaders: ['babel?optional=runtime'],
            exclude: /(node_modules)/,
            include: path.join(__dirname, 'src')
        },{
            test: /\.(less|css)$/,
            exclude: /(node_modules)/,
            loader: 'style!css!autoprefixer!less'
        },{
            test: /\.(png|jpg|gif)$/,
            exclude: /(node_modules)/,
            loader: 'url?limit=8192'
        }
]
```
`first.jsx   second.jsx` same code,and will be used on different html
```javascript
import {Provider} from 'react-redux';
```

I am sorry for my poor English

**Comment by fernandojbf** [comment]
Hi.

Some people already report this issue.
 
The only solution for this problem that I saw was the reply from @Janusch on [Issue959](https://github.com/webpack/webpack/issues/959#issuecomment-199835414). 

Isn't a solution, but for now is how I can help you. (if this is your problem)

**Comment by l3ve** [comment]
@fernandojbf 
I have fixed the issue, just add the alias. i don’t know why.
But  thank you all the way.
```javascript
resolve: {
        alias: {
            'react-redux': path.join(__dirname, '/node_modules/react-redux/dist/react-redux.min')
        }
}
```
