### ISSUE TITLE
Resolving path to external module

### ISSUE THREAD

**Issue by zamb3zi** [webpack/webpack#2265]
Hi,

I've have an external module where the path is being re-written in my webpack externals config. So, I can write `require('../../config.json')` and it resolves just fine as `require('./config.json')`.

That's all good. The problem is that I need to resolve the absolute path to the module at runtime. I can't use `__non_webpack_require__` directly because I don't know the `'./config.json'` path at runtime (it can vary depending on application configuration).

The following is the hacky solution I came up with which involves parsing the module's function definition. There would surely be a better way if the feature was implemented natively in webpack. What do you think? Thanks.

``` javascript
/**
 * Resolve the path to a webpack external given the webpack module ID.
 * Example:
 *   resolveWebpackExternal(require.resolve('../config.json'))
 *   returns the absolute path to config.json which varies depending on application
 *  configuration.
 * @param  {[number]} moduleId The id returned from webpack's `require.resolve(...)`
 * @return {[string]} The absolute path to the module.
 */
export function resolveWebpackExternal(moduleId) {
    if(moduleId >= 0) {
        const module = __webpack_modules__[moduleId];
        const m = module && module.toString()
            .match(/require\s*\(\s*['"]([^'"]+)['"]\s*\)/i);
        return m && m[1] && __non_webpack_require__.resolve(m[1]);
    }
}
```

**Comment by zamb3zi** [comment]
Perhaps the solution should be that `require.resolve(...)` should resolve to a path for externals and an id for internals? If so, do externals even belong in the modules array? Shouldn't they be handled by just rewriting the `require()`d path as necessary?

**Comment by sokra** [comment]
replace all `require('../../config.json')` with `require('../../config')` in your app.
create a `config.js` file that calls `require("config.json")`.
configurate `config.json` as external (`"commonjs ./config.json"`)

**Comment by effectivecui** [comment]
`yarn add reqResolve` will help you.
