### ISSUE TITLE
More useful profiler wanted.

### ISSUE THREAD

**Issue by Strate** [webpack/webpack#2266]
It would be very nice to gen more powerful profiler output. Like:

```
ts-loader: XXXms total, XXXms average per module
babel-loader: XXXms total, XXXms average per module
ExternalPlugin: XXXms total, (hookName: XXms, hookName2: XXms)
```

This output very useful to quick get build performace problems.

**Comment by bebraw** [comment]
Can you comment at https://github.com/webpack/webpack/issues/3996 ? Let's merge this there. If we had a better logging interface and interception, that might achieve what you want.
