### ISSUE TITLE
export with class declaration on one line has incorrect output (webpack2)

### ISSUE THREAD

**Issue by kentcdodds** [webpack/webpack#2267]
I think I’ve found a webpack 2 bug.

input:

```javascript
export default class Foo {}
```

output:

```javascript
class Foo {}
```

To get it to output the export, I have to do it on a separate line.

input:

```javascript
class Foo {}
export default Foo
```

output:

```javascript
class Foo {}

/* harmony default export */ exports["a"] = Foo;
```

I'd happily contribute a fix if I can be pointed in the right direction :+1:

**Comment by TheLarkInn** [comment]
@kentcdodds my guess is to start at https://github.com/webpack/webpack/blob/5189d9a321bea3cfecf63039ed9797f8f7761556/lib/dependencies/HarmonyExportExpressionDependency.js

**Comment by kentcdodds** [comment]
Thanks @TheLarkInn. I'll see if I get a chance to work on this soon :-)

**Comment by TheLarkInn** [comment]
No prob, Same here.

**Comment by kentcdodds** [comment]
Weird, I am unable to reproduce this. Pretty certain I didn't change versions or anything. Some magic going on here... :sparkles:

Will reopen if I find that it's still an issue

**Comment by TheLarkInn** [comment]
@kentcdodds i never saw the harmony comments in my output but I also couldn't reproduce.
