### ISSUE TITLE
Can't require bundle on node.js

### ISSUE THREAD

**Issue by maxs15** [webpack/webpack#2268]
I can't require my bundle on the server side.
Looks like this is because the ``module.exports``statement is missing at the beginning of the file.
I fixed the issue by using the BannerPlugin
```
new webpack.BannerPlugin({ banner:"module.exports = ", raw: true, entryOnly: false })
```
Did I miss something or this is a bug in 2.0 ?

Thanks

**Comment by sokra** [comment]
`target: "node"` `output.libraryTarget: "commonjs"`
