### ISSUE TITLE
Webpack with --watch should save file when it has been deleted even if there are no changes

### ISSUE THREAD

**Issue by dschissler** [webpack/webpack#227]
In the beginning it is frustrating as hell and I deleted my bundle.js and then I added in a white space to my entry file and then saved it.  The watcher did not save a new file (even from cache) and I think that it should.  At this particular moment I wanted to make sure that the server was capable of writing that file (since I had been changing so many things) and I ended up being confused and wasting minutes.

If its all of the same then I think that the watcher should first check to see if any of the files that it recently created are missing before it decides not to write anything.  This will help people setting the environment up.

**Comment by gkiely** [comment]
@sokra is there a flag that will enable a build if unchanged, sometimes it's nice to do a rebuild/refresh the page with a simple cmd+s.
