### ISSUE TITLE
Ability to use Webpack with .NET Core Kestrel?

### ISSUE THREAD

**Issue by MarkPieszak** [webpack/webpack#2271]
When trying to use the newest ASP.NET Core, it seems Webpack which uses Node, doesn't play well with Kestrel. Any ideas on what could be done to either let them play well together or potentially let Kestrel be aware of webpack better?

There are small projects such as https://github.com/axefrog/webpack-dnx-browsersync, but unfortunately they aren't working. I'm wondering if this is a webpack issue, or more of a Kestrel issue.

Just wanted to get the conversation started, incase anyone else was trying to get this going as well!

**Comment by m-andrew-albright** [comment]
I'm currently fighting with this as well.  Considering just breaking the Aurelia application into its own standalone project outside of .NET (maybe hosted in NGINX or something), then creating a Web API project separately.

**Comment by MarkPieszak** [comment]
So far for development I've figured out to use `outputPath` to proxy the web-dev-server files to another `port`, that way they send to 5000 (Kestrels port) and the files work naturally, hot-module-reloading works like a charm, and I can set breakpoints for the Web API. If you'd like, I can get the code snippets so you can try to set yours up like it as well.

Might make a github repo for it soon as well.

**Comment by m-andrew-albright** [comment]
That would be a huge help if you could provide some snippets!  I'm almost positive my issues are all about paths and not knowing what configuration entries I need to add/modify to provide webpack with all the information it needs about my source.

**Comment by emzero** [comment]
@MarkPieszak There's a yeoman generator called aspnetcore-spa which generates an ASP.NET Core project with webpack and a SPA framework (angular2, react or knockout).

I can confirm that webpack is playing well with kestrel and providing hot reload and everything you would expect from it.

You can read more [here](http://blog.stevensanderson.com/2016/05/02/angular2-react-knockout-apps-on-aspnet-core/).

**Comment by MarkPieszak** [comment]
Yes, I've been trying to get help with that project, forgot I still had this issue open. I'll close it out. Thanks em
