### ISSUE TITLE
"stay in the same language in pre and post loaders"?

### ISSUE THREAD

**Issue by dwiyatci** [webpack/webpack#2272]
I'm about to create my first custom Webpack loader, but I'm not sure I understand well what the [loaders doc](http://webpack.github.io/docs/loaders.html#recommendations) stated:

> It is recommended to **stay in the same language in pre and post loaders**.

Hasn't the non-JS to JS transformation already happened before post-loaders kick in? So, what's "stay in the same language" supposed to mean there?

**Comment by dwiyatci** [comment]
🆙

**Comment by pksjce** [comment]
This issue was moved to webpack/webpack.io#144
