### ISSUE TITLE
Deprecate "optimize-extracted-chunks"?

### ISSUE THREAD

**Issue by gmac** [webpack/webpack#2276]
Looking at this line: https://github.com/webpack/webpack/blob/37d2b1a94da16833ad87868c6978b4982390bc42/lib/optimize/CommonsChunkPlugin.js#L48

Searching the repo, it looks like `"optimize-extracted-chunks"` is never actually called by Webpack. This is either old code, or else a mysterious hook into another Webpack extension. If it's old code, then it would be best if it were removed to obviate internals. If it's a mysterious hook into another extension, then I'd recommend adding a comment that explains where and how that hook ties into the engine.

**Comment by sokra** [comment]
It's used by the extract-text-webpack-plugin... propably not the best design here ;)

**Comment by gmac** [comment]
Well in that case... carry on! That's a high value plugin. Thanks for all
the great work, I'm consistently amazed by how much is built into the
engine.
