### ISSUE TITLE
Watch dont work if "context" is relative, but works if absolute (for windows)

### ISSUE THREAD

**Issue by vitrilo** [webpack/webpack#2279]
For Windows.

"entry" config option dont require Absolute path - compile and watch works without issue:

``` javascript
//working for compile and  watching 
module.exports = {
    entry: "./wwwroot/js/file.js",
    devtool: "source-map",
    output: {
        filename: "bundle.js"
    }
};
```

**"context" config option** dont require Absolute path for compile, **but require Absolute path** for watch:
(from the doc: Windows paths - webpack expects absolute paths for many config options.)

Corectly compile, but **dont really watching for file changes**:

``` javascript
//working for compile and NOT working for watching 
module.exports = {
    context: "./wwwroot",      
    entry: "./js/file.js",
    devtool: "source-map",
    output: {
        filename: "bundle.js"
    }
};
```

Corectly compile and **watching for file changes corectly**:

``` javascript
//working for compile and NOT working for watching 
module.exports = {
    context: "D:\\path\\wwwroot\\",   //using absolute path fixed the issue   
    entry: "./js/file.js",
    devtool: "source-map",
    output: {
        filename: "bundle.js"
    }
};
```

Same bug was already reported by @samanime but as comment https://github.com/shama/webpack-stream/issues/18#issuecomment-185549552

**Comment by sokra** [comment]
context must be absolute, this is validated now.
