### ISSUE TITLE
How to minify js file without webpackJsonp wrapper?

### ISSUE THREAD

**Issue by anhkhoi** [webpack/webpack#2281]
My webpack config:
```
{
    entry: {
        app: './app.js',
        vendor: [
            'a',
            'b',
            'c'
        ],
        vendor2: [
            'd'
        ]
    },
    output: {
        path: path.join(__dirname, 'js'),
        filename: '[name].bundle.js'
    },
    plugins: [
        new webpack.optimize.CommonsChunkPlugin('vendor', 'vendor.bundle.js'),
        new webpack.optimize.CommonsChunkPlugin('vendor2', 'vendor2.bundle.js')
    ]
}
```

My bundle file after bundled:
- vendor.bundle.js **without** webpackJsonp
- vendor2.bundle.js **with** webpackJsonp

How to remove **webpackJsonp** wrapper from my vendor2.bundle.js?

Also, terminal throw error 

`ERROR in CommonsChunkPlugin: While running in normal mode it's not allowed to use a non-entry chunk (vendor2)`

Thank for any help.

**Comment by sokra** [comment]
see two-explicit-vendor-chunks example

**Comment by anhkhoi** [comment]
I meant the vendors after minified (bundled) can require/include in other sites. These site don't use webpack. So, I don't want a webpack wrapper after bundled.
Eg.: My vendor have jquery, backbone libs. I bundled into "vendor.bundle.js". In other site, user include my vendor. They can use global variable from that vendor as: jQuery, Backbone.

**Comment by felipesabino** [comment]
@sokra Could you please elaborate? 

I don't think the question was answered. The example you provided has the same "problem" described in the question. 

There seems to be some webpack concept missing for me and @anhkhoi that prevented us from seeing  what is actually going on. I am looking at it and still could not figure it out why one `.js` file has a `webpackJsonp` wrapper and the other doesn't.

**Comment by MQuy** [comment]
@sokra, I think `two-explicit-vendor-chunks` is different with what @anhkhoi want. Do you have any updates on this issue?

**Comment by chrisui** [comment]
Agree this doesn't seem answered.

For me I want to use [html-webpack-inline-source-plugin](https://github.com/DustinJackson/html-webpack-inline-source-plugin) to inline some critical bootstrapping code to be run instantly before even loading the bundles however the {bootstrap: './bootstrap.js} entry has the webpackjsonp wrapper which I do not want (I just want an IIFEE or no wrapper at all).

**Comment by piehei** [comment]
I guess I'm facing a similar problem which I've documented more thorougly here: https://stackoverflow.com/questions/46476366/transfer-a-file-then-inline-it-without-webpack-bundling-loader-code

The gist of it being:
- all my js files bundled together and injected (not inlined) into index.html [this works of course!]
- one js file, which is not included in the bundle described above, inlined into index.html
- the inlined js file has to go through the Webpack "transformation pipe" since that js file depends on the Webpack build step

The one inlined file should not include any WebpackJSONP stuff, only transformed JavaScript and names provided by requires() that the webpack-loaders analyzed etc.

**Comment by MattCz** [comment]
I'm facing exactly the same issue. Any ideas how to get rid of that wrapper?

**Comment by vsDizzy** [comment]
I bet this could be done by custom plugin. I need to transpile some files and emit them without wrappers.

**Comment by Organizzzm** [comment]
I'm facing exactly the same issue.

**Comment by avesus** [comment]
I'm facing exactly the same issue when bundling the Service Worker code.

**Comment by eric-wood** [comment]
@avesus I was running into this issue when using the `CommonChunkPlugin` in our production webpack config.

The `CommonChunkPlugin` config can take in a list of chunks, but doesn't support any kind of blacklisting, so we have to filter them out ourselves.

This is roughly the solution I arrived at, although it may not look quite the same in your case:

webpack.dev.js:
```js
module.exports = {
  entry: [ /* all those entry points! */ ]
}
```

webpack.prod.js:

```
const devConfig = require('./webpack.dev.js')

const chunks = Object.keys(devConfig.entry).filter((name) => !name.match(/service-worker/))

module.exports = {
  ...devConfig,
  plugins: [
    new webpack.optimize.CommonsChunkPlugin({
      name: 'common',
      filename: './scripts/common.js',
      chunks,
    }),
  ]
}
```

Hope that helps!

**Comment by Hassija** [comment]
> I guess I'm facing a similar problem which I've documented more thorougly here: https://stackoverflow.com/questions/46476366/transfer-a-file-then-inline-it-without-webpack-bundling-loader-code
> 
> The gist of what I want being:
> 
> * all my js files bundled together and injected (not inlined) into index.html [this works of course!]
> * one js file, which is not included in the bundle described above, inlined into index.html
> * the inlined js file has to go through the Webpack "transformation pipe" since that js file depends on the Webpack build step
> 
> The one inlined file should not include any WebpackJSONP stuff, only transformed JavaScript and names provided by requires() that the webpack-loaders analyzed etc.

Any luck with this ? I am facing the same issue.

**Comment by Hassija** [comment]
> @avesus I was running into this issue when using the `CommonChunkPlugin` in our production webpack config.
> 
> The `CommonChunkPlugin` config can take in a list of chunks, but doesn't support any kind of blacklisting, so we have to filter them out ourselves.
> 
> This is roughly the solution I arrived at, although it may not look quite the same in your case:
> 
> webpack.dev.js:
> 
> ```js
> module.exports = {
>   entry: [ /* all those entry points! */ ]
> }
> ```
> 
> webpack.prod.js:
> 
> ```
> const devConfig = require('./webpack.dev.js')
> 
> const chunks = Object.keys(devConfig.entry).filter((name) => !name.match(/service-worker/))
> 
> module.exports = {
>   ...devConfig,
>   plugins: [
>     new webpack.optimize.CommonsChunkPlugin({
>       name: 'common',
>       filename: './scripts/common.js',
>       chunks,
>     }),
>   ]
> }
> ```
> Hope that helps!

This did not work for me.

**Comment by kasjerJanusz** [comment]
Hi, sorry for digging out the old thread, but I have currently same problem.
Posted question @ StackOverflow.com - [How to get rid of webpack wrappers and get plain minified and uglified ES5 IIFEs code while bundling AngularJS app](https://stackoverflow.com/questions/56874983/how-to-get-rid-of-webpack-wrappers-and-get-plain-minified-and-uglified-es5-iifes).

What I want to achieve is to use webpack to create two separate bundles: app code into app.bundle.js and 3rd party plugins into vendor.bundle.js.
Then, transpile whole code to ES5 and get rid of bundle wrappers like webpackJsonp to have only pure transpiled code (btw. which should be done first, transpiling or unpacking bundled code from wrappers?).

And the resulting code should be minified and uglyfied and results should be put into app.min.js and vendor.min.js.

Is it even possible?

**Comment by donutDonut123** [comment]
[@Doug from StackOverflow](https://stackoverflow.com/a/46381748/13198379) suggested solution:

Set your [target](https://webpack.js.org/concepts/targets/) to `node` in **webpack.config.js** (the default is `web`):
```
module.exports = {
  target: 'node'
};
```

> In the example above, using node webpack will compile for usage in a Node.js-like environment (uses Node.js require to load chunks and not touch any built in modules like fs or path).

Alternatively, if this is not appropriate for your use, you can also just change the `libraryTarget` in the [output](https://webpack.js.org/configuration/output/#output-librarytarget) (assuming you are using CommonJS):

```
output: {
    path: path.resolve(__dirname, 'build'),
    filename: '[name].js',
    libraryTarget: 'commonjs'
},
```

> libraryTarget: "commonjs" - The return value of your entry point will be assigned to the exports object using the output.library value. As the name implies, this is used in CommonJS environments.
