### ISSUE TITLE
Compatibily of bundled file syntax  with web browsers

### ISSUE THREAD

**Issue by maudema** [webpack/webpack#2282]
Hi !

I try to use a biojs module in a new component and I use webpack to bundle modules. When I use the bundled file in a html file , I obtain these error messages :

« SyntaxError: class is a reserved identifier »  in the bundle file with  mozilla firefox 44.0

« Uncaught SyntaxError: Unexpected token [ » in the bundle file with google chrome 48.0.2564.116 

My understanding is that the syntax use in the bundled file is not supported by web browsers. 
Is it  possible to modified the syntax use for write the bundled file ? 

My system is Ubuntu 15.04.

Thank you in advance.

**Comment by igor-im** [comment]
@maudema it sounds like you aren't preprocessing with Babel. Class is an ES2015 feature that needs to be transpiled to ES5. Are you using React?

**Comment by maudema** [comment]
I had not use React . It would seem that the problem took from one of my dependencies.
The issue is resolved now.

Thank you for your answer.
