### ISSUE TITLE
Does "usage with gulp" article needs update?

### ISSUE THREAD

**Issue by kamlekar** [webpack/webpack#2283]
Hi,

I was reading this [article](https://webpack.github.io/docs/usage-with-gulp.html) where there is no mention of `gulp-webpack` plugin. It is kind of confusing of what exactly I should use. I think the article needs update mentioning whether or not to use `gulp-webpack` plugin.

**Comment by sokra** [comment]
yes, feel free to update it.

**Comment by kamlekar** [comment]
@sokra I don't think I am the right guy to update it as I just started using webpack with gulp,  I don't have much knowledge on it.

**Comment by pksjce** [comment]
This issue was moved to webpack/webpack.io#138
