### ISSUE TITLE
Aliases are not being replaced on full match

### ISSUE THREAD

**Issue by raulferras** [webpack/webpack#2287]
My `resolve.alias` collection contains (among others) these to aliases:

```
"app/user": __dirname + "/common/user",
"app/user/action-proxy": __dirname + "/other/folder/action.proxy"
```

Then, when executing webpack those requiring "app/user/action-proxy" are not being replaced properly and instead, are being resolved to:

   __dirname + "/common/user/action-proxy.js"

Which then obviously build complains because there is no such file.  
It looks like the replacement is done with any part of the alias name.

Is this an expected behaviour?

**Comment by bebraw** [comment]
Can you try swapping the order and report back?

**Comment by raulferras** [comment]
It fails the same way

**Comment by bebraw** [comment]
Thanks. Marked as a bug. There could be something funky going on.

**Comment by raulferras** [comment]
Has this been addressed?

**Comment by vankop** [comment]
Should work with `webpack@latest`. Feel free to report new issue with reproducible repo.
