### ISSUE TITLE
devServer option

### ISSUE THREAD

**Issue by richburdon** [webpack/webpack#2289]
1). Adding a devServer field to my config throws an exception.
2). This option isn't well documented (https://webpack.github.io/docs/configuration.html#devserver)

module.exports = {
  ...
  devServer: {}    # Any values here.
  ...
}

events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8080
    at Object.exports._errnoException (util.js:890:11)
    at exports._exceptionWithHostPort (util.js:913:20)
    at Server._listen2 (net.js:1239:14)
    at listen (net.js:1275:10)
    at net.js:1384:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:63:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:82:10)

**Comment by bebraw** [comment]
By the looks of it, you have something else running in its default port. You could either drop the server running there or run webpack-dev-server in another port through the `devServer.port` option.

**Comment by tsaiDavid** [comment]
@richburdon - If you know that you aren't using port 8080, you might try to look for the process on that port and kill it, I've had to do that before.

http://stackoverflow.com/questions/11583562/how-to-kill-a-process-running-on-particular-port-in-linux
