### ISSUE TITLE
Module parse error (need an appropriate loader)

### ISSUE THREAD

**Issue by creeperyang** [webpack/webpack#2290]
Error msg is:

```bash
ERROR in ./config.js
Module parse failed: /xxx/config.js Line 1: Unexpected token
You may need an appropriate loader to handle this file type.
| import { resolve } from 'path';
| 
| /// env
```

It looks like a regular error reported by other issues. But it's not  exactly.

The webpack reported error about `import` syntax in `config.js`, but other files who use `import` remains ok.

And my loaders config:

```js
{
    test: /\.jsx?$/,
    loader: ['babel'],
    include: APP_PATH,
    exclude: /(node_modules|bower_components)/,
    query: {
        presets: ['es2015', 'stage-0', 'react'],
        plugins: DEBUG ? [['react-transform', {
            transforms: [{
                transform: 'react-transform-hmr',
                imports: ['react'],
                locals: ['module']
            }, {
                transform: 'react-transform-catch-errors',
                imports: ['react', 'redbox-react']
            }]
        }]] : [],
        babelrc: false
    }
}
```

**Comment by marvinhagemeister** [comment]
You only apply the babel loader for .jsx and not .js files in your configuration.

**Comment by bebraw** [comment]
Instead of `loader: ['babel']` you should use either `loaders: ['babel']` or `loader: 'babel'`.

**Comment by creeperyang** [comment]
@bebraw tested, and the same error.

**Comment by creeperyang** [comment]
@marvinhagemeister `test: /\.jsx?$/` is ok for both `js` and `jsx`.

**Comment by creeperyang** [comment]
I checked the loader config again, and finally I recognize the reason:

My `config.js` is at the same dir with `APP_PATH`, so `babel-loader` wont handle it.

Thanks for all.

**Comment by marvinhagemeister** [comment]
@creeperyang oh your right! My bad!
