### ISSUE TITLE
resolve.root Breaks - ModulesInRootPlugin and makeRootPlugin

### ISSUE THREAD

**Issue by wooliet** [webpack/webpack#2291]
Between 2.0.2-beta and 2.0.4-beta (2.0.3-beta not published), the `resolve.root` configuration stopped working. As best I can tell, the issue happens because:

_/lib/WebpackOptionsApply.js_

No longer includes `ModulesInRootPlugin` and `makeRootPlugin` is no longer called. The result is that all non absolute or relative path calls to `require` now fail. The verbose output shows that the path for `resolve.root` is never checked.

I believe the above changes are present up to the most recent release. I'm not sure if this is a design decision that hasn't yet been completed or if the intent is to use some other mechanism. If at all possible it would be nice to have this back or maybe a comment on how it should now work.

Thanks!

**Comment by sokra** [comment]
There is no `resolve.root` webpack 2 anymore. It has been renamed. See changelog.

**Comment by wooliet** [comment]
Thanks, I see now that it is `modules` only. Sorry for the PR.
