### ISSUE TITLE
require.ensure using a variable

### ISSUE THREAD

**Issue by jonathandion** [webpack/webpack#2292]
Hi, I would like to use a variable to require a specific file called 'home.js'.

There is my code : 

```
var currentView = "./home/home.js";
require.ensure([], function(require) {
        try {
          var req = require.context("./views", true, /^\.\/.*\.js$/);\
          var view = req(currentView) // this return all the .js file inside ./views
        } catch(e) {

        }
    });
```

How can I require only one file not all of them ?

Thanks.

**Comment by taurose** [comment]
Not sure if I understand you correctly, but if you're looking to put all files into different chunks so that they can be loaded individually, see https://github.com/webpack/webpack/issues/441#issuecomment-53854368 .

**Comment by jonathandion** [comment]
@taurose  I want to load home.js, about.js on demand. So if the user navigate to /about I want to load only about.js and his dependencies.

ex : inject that chunk (1.1.js) into my page /about

Make sense ? thanks !

**Comment by taurose** [comment]
Yeah, you should be able to  achieve that with the code in the comment I linked.

**Comment by codeofsumit** [comment]
I'm having the same problem. The comment linked may solve this issue, I haven't figured it out yet but it's missing the explanation why a `require` inside `require.ensure` isn't just loading 1 file when passed a variable but the whole folder.
