### ISSUE TITLE
Webpack 2: order of ES2015 imports gets reversed when using multiple entries

### ISSUE THREAD

**Issue by smrq** [webpack/webpack#2293]
Using: `webpack@2.1.0-beta.4`

It seems that when a file with ES2015 `import`s is included from multiple entries, sometimes the order of `import`s in the bundle gets reversed.  Since module imports may have side effects, this is very bad.  (I ran into this while importing modules with the `expose-loader`; one of my two bundles worked fine, but the other bundle had runtime errors where the proper globals had not yet been set.)

A minimal repro is available here: https://github.com/smrq/webpack-import-reverse-repro

Note that in this repro, the same file is simply bundled multiple times, with different results in each bundle.  The same bug appears if you have different entry points that import a common file--the `import`s in the common file are sometimes reversed.

It appears to happen on every second bundle; if you bump up the number of entries, the odd-numbered ones work fine and the even-numbered ones exhibit the bug.

This only happens with ES2015 imports; using `require('./foo');` instead of `import './foo';` does not exhibit this bug.

**Comment by smrq** [comment]
_DISCLAIMER: I have no idea what I'm doing in this codebase._

After digging into the source a bit, it appears to me that the problem is that what is being stored as the cached source for a module is a `ReplaceSource` instead of a `CachedSource`.  So when the module is rendered a second time, the modifications from the replace are applied an extra time, which seems to manifest in this problem.  Changing it to storing the `CachedSource` instead appears to fix the bug, and all tests still pass.

**Comment by smrq** [comment]
Okay, I figured out the problem for real.  It's in `ReplaceSource` in `webpack-sources`.  The problem is that `_sortReplacements` flips the order of inserted `replacement`s every time it is called.  They are initially pushed to the array in reverse order by `insert`; the first sort flips them to the correct order.  The second sort flips them back to the incorrect order, and so on, which is why this bug shows up on every other bundle.

**Comment by sokra** [comment]
https://github.com/webpack/webpack-sources/commit/c377352d5125162af1e331dc2304206e8e3ea3fa
