### ISSUE TITLE
$ missing at runtime despite ProvidePlugin

### ISSUE THREAD

**Issue by richburdon** [webpack/webpack#2294]
Webpack seems to not notice the use of globals intended to be provided by ProvidePlugin if they are not at the top-level of the file?

In the config I have:

    new webpack.ProvidePlugin({
      $: 'jquery'
    }),

If the source file uses "$" at the top-level things are fine; if the first use is in a callback then there are problems. E.g., 

    console.log($); // If I comment this out, the call below fails (ReferenceError: $ is not defined)

    class Foo {
      post() {
        $.ajax(); // Error here if log above is commented out.
      }
    }

**Comment by sokra** [comment]
webpack 1 doesn't understand ES6 syntax. webpack 2 will do.
