### ISSUE TITLE
[Question]: when will `module` be undefined in UMD webpackBootstrap.

### ISSUE THREAD

**Issue by pwang2** [webpack/webpack#2295]
In webpack UMD wrap, the 2nd **else** is detecting the `exports` ONLY here,  when would the `module` be empty and we have chance to attach it to the `exports`?  I saw when we call with any module, we always passing it as ` modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);`

Does it related with nodejs `module.exports=exports={};`?

```js
(function webpackUniversalModuleDefinition(root, factory) {
	if(typeof exports === 'object' && typeof module === 'object')
		module.exports = factory();
	else if(typeof define === 'function' && define.amd)
		define([], factory);
	else {
		var a = factory();
		for(var i in a) (typeof exports === 'object' ? exports : root)[i] = a[i];
	}
})(this, function() {
});
```

**Comment by sokra** [comment]
CommonJs 1.0 only specifies the `exports` object. node.js added `module` (CommonJs 1.1.1).

**Comment by pwang2** [comment]
Gotcha, I am still too new to the awesomeness.  Thank you.
