### ISSUE TITLE
when publicPath is cdn (http://cdn.example.com) ,but outputfile is http:/cdn.example.com

### ISSUE THREAD

**Issue by yangfeiloveG** [webpack/webpack#2296]

**Comment by bebraw** [comment]
Can you provide an example?

**Comment by yangfeiloveG** [comment]
webpack config:

```
let DEBUG = false
output: {
        // 在debug模式下，__build目录是虚拟的，webpack的dev server存储在内存里
        
        publicPath: DEBUG ? '/__build/' :'http://7xq22v.com2.z0.glb.qiniucdn.com'
    },
```

but finally 
<script src="http:/7xq22v.com2.z0.glb.qiniucdn.com/........." ></script>

**Comment by sokra** [comment]
what's the issue/question?

**Comment by MikaAK** [comment]
@yangfeiloveG you need a slash at the end of your url or it will remove the double slash in http. Try `http://7xq22v.com2.z0.glb.qiniucdn.com/`

**Comment by yangfeiloveG** [comment]
@MikaAK Thank you so much! It works!
