### ISSUE TITLE
[Question] How do update "sourceRoot" in sourcemaps?

### ISSUE THREAD

**Issue by Vloz** [webpack/webpack#2298]
(Related to this: https://github.com/webpack/webpack/issues/238#issuecomment-144261479)

I need to update the **sourceRoot** field of the generated sourcemap to use absolute path (to work with Visual Studio Code debugger) but i dont find anything about doing that. Is the feature missing?

**Comment by bebraw** [comment]
Based on a [search against the source](https://github.com/webpack/webpack/search?utf8=%E2%9C%93&q=sourceRoot) I would say it's not possible to set it yet. I don't see anything relevant in the configuration documentation either.

**Comment by nippur72** [comment]
@Vloz I don't know if this may help you, but I can debug in VS by having:
```
output: {        
   // ...   
   devtoolModuleFilenameTemplate: "[resource-path]"
   // ...   
}
```
this does not change the `sourceRoot` but changes the `sourceMappingURL` in the generated `.js` file directly.

**Comment by Vloz** [comment]
@nippur72 Thx for the advice, unfortunately both "[resource-path]" and "[absolute-resource-path]" are giving me the same working map path, the problem in my situation is more related to finding the right file source from the map file (to set breakpoint, etc...).
Maybe that's not enough in my case because i m using Ts source files... :S
(chaining transpiler :skull: )

**Comment by bebraw** [comment]
@Vloz Did you have any luck with this?

**Comment by vankop** [comment]
You need to provide `sourceRoot` option to [SourceMapDevToolPlugin](https://webpack.js.org/plugins/source-map-dev-tool-plugin/)

@evilebottnawi @sokra issue can be closed
