### ISSUE TITLE
Get bundle as a string with programmatically usage with 0.6.x

### ISSUE THREAD

**Issue by topa** [webpack/webpack#23]
We're using for [alamid's client tests](https://github.com/peerigon/alamid/tree/master/test/client) [nof5](https://github.com/peerigon/nof5). 
nof5 is basically a server which is able to use different bundlers, e.g. webpack, to bundle and serve client tests. One advantage of nof5 is that there is no need to write any tmp-file for the tests. So you won't have any problems with permissions. 
So nof5 expects from the bundlers to be able to return a bundle as a string.
This is how webpack is implemented as bundler for nof5: [WebpackBundler](https://github.com/peerigon/nof5/blob/master/lib/bundler/WebpackBundler.js).
I wanted to updated the dependecy to webpack to version 0.6.x, but webpack isn't return a string any more. 

Is there any possibility to get the bundle as string?

**Comment by adjohnson916** [comment]
How to do this with webpack 1.x or later? `emitFile` and `noWrite` seem gone. Already changed `absoluteFile` arg to `entry: absoluteFile` in config options.
