### ISSUE TITLE
Review webpack-validator

### ISSUE THREAD

**Issue by jonathanewerner** [webpack/webpack#2303]
Hi,
i wrote the tool [webpack-validator](https://github.com/jonathanewerner/webpack-validator) that validates webpack configs with the validation library [joi](https://github.com/hapijs/joi).
The supported properties are 95% dependent on webpack config documentation. I know that there are quite some undocumented properties. The tool disallows unknown keys, so it would be nice to add those undocumented properties in order to not throw false-positives. 
Would anyone be willing to audit the schema and maybe offer some advice if there's some way to find those undocumented properties without reading the whole webpack source? :)

**Comment by bebraw** [comment]
Do you think we should close this? I'm not sure if a lot of people read this tracker. I guess the key here would be to encourage usage through certain other means. Do you have a gitter for the project?

Tobias would likely know the best but I'm sure he is super busy these days. :smile:

**Comment by jonathanewerner** [comment]
Ok, lets close it. I'll do as you suggest. No gitter yet, will create one.
