### ISSUE TITLE
Please review my blog: "Webpack - The Confusing Parts"

### ISSUE THREAD

**Issue by rajaraodv** [webpack/webpack#2308]
Hi there,
Firstly thanks for the great tool! I am about to post a blog  "[Webpack - The Confusing Parts](https://medium.com/@rajaraodv/58712f8fcad9)". Despite the heading, the idea of the blog is to help newcomers get over the hump and confusion they may have (like I did).  

It's a blog on Medium. Appreciate if you can take a look and provide some comments. You can add comments by simply selecting the text and I'll update it.

cc:  @sokra @kennyt @gaearon 

- Raja

**Comment by sokra** [comment]
Very good...

Here are a few very small issues I found:

* `wepback` => `webpack`
* `Through webpack.config.js’s “devserver” object.` => `... devServer ...`
* `we are configuring url-loader to use URLs for images` => `we are configuring url-loader to use DataURLs for images`
* Not the `url-loader`, but the `file-loader` uses the `publicPath` option. The `url-loader` uses the `file-loader` when filesize is over the limit.
* `url-loader?limit=1` should better be `file-loader`
* `So Webpack let’s us to keep babel-loader’s configuration in babel’s own configuration file called .babelrc file.` actually it's not webpack, but babel itself which allows that.

PS for webpack 2 the following on your list changes:

* `--inline` is default
* `resolve.extensions` don't need the empty string anymore

**Comment by rajaraodv** [comment]
Thanks @sokra for reviewing it! Made all the changes. 

BTW, I'm planning 2 more posts next week around code splitting and async loading stuff.

**Comment by sokra** [comment]
@rajaraodv awsome...

**Comment by methodbox** [comment]
Great post, which I will definitely use as a reference going forward.

But I still can't load fucking jQuery properly.

Anything that makes something like that so convoluted when it should be simple makes me wonder if it's worth my time.

I spent at least an hour today trying to get jQuery to load properly with a webpack and Vuejs project.

Loading the index.html directly worked fine, jQuery works. Loading it via the webpack project was fucking hosed. $ was defined, but some jQuery functions refused to actually work correctly or would randomly say X is not a function.

The carousel plugin a la bootstrap but used from Materialize simply will not work, loaded statically or via any option in webpack. JQuery will work, but things that depend on jQuery fail to believe it exists (like carousel.js).

An hour fucking with jQuery isn't productive, regardless of the "efficiency" provided by webpack.
