### ISSUE TITLE
Funny packing of less comments

### ISSUE THREAD

**Issue by jlchereau** [webpack/webpack#2311]
This is the result:

![image](https://cloud.githubusercontent.com/assets/2556751/14410966/04c496da-ff34-11e5-96c2-e9080dc21ec6.png)

From what I guess is

![image](https://cloud.githubusercontent.com/assets/2556751/14411064/e6b5df4e-ff35-11e5-878f-6c069dd82280.png)

**Comment by sokra** [comment]
weird... looks like many spaces...

try to ask on the less-loader or less.js repo.

**Comment by jlchereau** [comment]
Is it possible to configure webpack to use the less compress option that removes all comments? See http://lesscss.org/usage/index.html

**Comment by sokra** [comment]
https://github.com/webpack/less-loader#less-options
