### ISSUE TITLE
definePlugin is not working with ES6 syntax

### ISSUE THREAD

**Issue by NekR** [webpack/webpack#2312]
See this https://github.com/NekR/offline-plugin/issues/34

Also I experience same problem in my local project (not related to `offline-plugin`) with latest webpack (`1.12.14`).
Seems like it doesn't working correctly only when using ES6 directly, e.g. without preprocessing with Babel. Though, in `offline-plugin` I use Babel to preprocess things, so not sure if it's really related to ES6.

**UPD:** Works okay in webpack 2. Should all with this problem migrate to v2?

My config in local project:

``` js
const path = require('path');
const webpack = require('webpack');

module.exports = (options) => {
  const browser = options.browser;

  return {
    entry: {
      // different entries
    },
    output: {
      path: path.join(__dirname, 'output'),
      filename: '[name].js'
    },
    module: {
      loaders: [
        {
          exclude: /(node_modules|bower_components)/,
          test: /\.tsx?$/,
          loader: 'babel',
          query: {
            "plugins": [
              "transform-es2015-modules-commonjs"
            ]
          }
        },
        {
          exclude: /(node_modules|bower_components)/,
          test: /\.tsx?$/,
          loader: 'ts',
        }
      ]
    },
    resolve: {
      root: path.join(__dirname, 'src'),
      extensions: ['', '.ts', '.tsx', '.js']
    },
    plugins: [
      new webpack.DefinePlugin({
        SOMETHING: true
      })
    ]
  }
};
```

**Comment by arusakov** [comment]
Same problem here.

**Comment by NekR** [comment]
Btw, while `DefinePlugin` works in `v2`, `DEBUG` variable doesn't exist there by default, so every plugin/loader/project which uses `DEBUG` will be broken.

**Comment by aaronshaf** [comment]
Confirmed. DefinePlugin not working within template literals

**Comment by NekR** [comment]
Activity.
