### ISSUE TITLE
Empty entry point causes build failure

### ISSUE THREAD

**Issue by KCreate** [webpack/webpack#2313]
Take this config as an example:

``` javascript
var config = {
    ...
    entry: [
        "", // empty string
        "./client/index.js"
    ],
    ...
};
```

The empty string causes a build error, with the following message:
`Module build failed: Error: Final loader didn't return a Buffer or String`

I'm not sure if this behaviour is wanted, but a more helpful error message would be nice.
Something that tells you that you, that you can't have empty entry points.

**Comment by johnstew** [comment]
Is this still an issue on RC3? I just took a look and wanted to try and help here but it looks like the output has been improved.

![screen shot 2017-01-03 at 6 33 32 pm](https://cloud.githubusercontent.com/assets/2146973/21627053/3b4d9648-d1e3-11e6-83ab-9ad36411188f.png)

Specifically last line:
```
* configuration.entry[0] should not be empty.
```

**Comment by tarang9211** [comment]
@TheLarkInn would this be a good issue for me since I am completely new to the repo?

**Comment by KCreate** [comment]
@tarang9211 As far as I understood this issue is solved? 

Check @johnstew's screenshot.

**Comment by KCreate** [comment]
I'm closing this issue as it is no longer relevant.
