### ISSUE TITLE
webpack-dev-server example code requires JADE plugin

### ISSUE THREAD

**Issue by dkts** [webpack/webpack#2316]
The following webpack-dev-server example from the [documentation](https://webpack.github.io/docs/webpack-dev-server.html)
```
config.entry.app.unshift("webpack-dev-server/client?http://localhost:8080");
```
may not work in standard configurations because the (implicitly used) `index.js` file needs a jade processor to compile properly.

Since the webpack-dev-server package already has a prepublish hook to generate an `index.bundle.js` in the client directory file during package installation, I would suggest to update the reference to that file?

```
config.entry.app.unshift("webpack-dev-server/client/index.bundle.js?http://localhost:8080");
```

**Comment by pksjce** [comment]
This issue was moved to webpack/webpack.io#117
