### ISSUE TITLE
webpack -d devtool default is not overridden in config

### ISSUE THREAD

**Issue by javascriptjedi** [webpack/webpack#2317]
From the docs it states:

"Note: With the next major version the default for -d will change to cheap-module-eval-source-map"

The behavior I'm seeing is the devtool config is ignored if I run webpack -d, it is honored if I just run webpack. The docs make it sound like cheap-module-eval-source-map is just a default and I would expect the config to be the value used if it is set. This was happening on both beta 4 and 5.

**Comment by sokra** [comment]
CLI options override the configuration options. So `-d` overrides `devtool: ...`.

`--devtool eval` overrides `-d`.

**Comment by pksjce** [comment]
This issue was moved to webpack/webpack.io#118
