### ISSUE TITLE
Unexpected token "!" in dynamic context

### ISSUE THREAD

**Issue by tomasAlabes** [webpack/webpack#2318]
I'm having an invalid bundle after webpack processing this snippet of code, I've simplified it as much as possible (I took the code from a library I'm using, the code itself won't make any sense but it reproduces the problem).

Command: `webpack entry.js bundle.js`

```
module.exports = function(locale, callback)
{
    var prefix = "myfolder/",
        requestedBundles = [prefix + locale + "/folder2"];

    requestedBundles.push(prefix + locale + "/folder3");    

    require(requestedBundles,
      function(translations, localeElements)
      {

      }
    );
};
```

Structure

```
.
├── myfolder
│   ├── folder2
│   └── folder3
└── oj2.js
```
#### bundle.js

```
/* 0 */
/***/ function(module, exports, __webpack_require__) {
    module.exports = function(locale, callback)
    {
        var prefix = "myfolder/",
            requestedBundles = [prefix + locale + "/folder2"];

        requestedBundles.push(prefix + locale + "/folder3");    

        __webpack_require__(1)!/* require */(/* empty */function() { var __WEBPACK_AMD_REQUIRE_ARRAY__ = requestedBundles; (function(translations, localeElements)
          {

          }.apply(null, __WEBPACK_AMD_REQUIRE_ARRAY__));}.call(this));
    };

/***/ }
```

The `(1)!/*require*/(...` is invalid.

Might be a problem with the parser? I don't know how to avoid it, if I add it to the module.noParse option the rest of the app get messed up.
I tried with webpack version 1.x and 2.x.

Thank you

**Comment by tomasAlabes** [comment]
Hi @bebraw, if you don't have the time to look at this could you give me a pointer to somewhere in the code where this erroneous code might be generated?
Thanks again.

**Comment by sokra** [comment]
The code is too dynamic for webpack to process anyway. Possible would be something like:

``` js
require(["myfolder/" + locale + "/folder"], function() {})
```

**Comment by tomasAlabes** [comment]
Thanks @sokra for the quick answer. But:

- In my case I don't have control over that code, is part of a external library (real function [here](https://github.com/oracle/oraclejet/blob/master/dist/js/libs/oj/debug/ojcore.js#L1809)). I will try to replace the context or add all bundles manually with `require.context`. I'll see how I can do it.
- **Most importantly, this case outputs an invalid js bundle**. Obviously if I add a `;` before the `!` in [AMDRequireDependency.js#L52](https://github.com/webpack/webpack/blob/webpack-1/lib/dependencies/AMDRequireDependency.js#L52) the output is valid, and the tests run fine, but I would need your feedback on that. I can create a PR whenever you tell me to.

Thanks again,
Tomas

**Comment by tomasAlabes** [comment]
Resolved.

**Comment by dpundir** [comment]
Have we got solution for the dynamic require through webpack problem?
I have similar requirement:
require([varname], function() {}) OR
require(["myfolder/" + locale + "/folder"], function() {})

**Comment by tomasAlabes** [comment]
It was resolved but in webpack 2, perhaps you can ask for a fix for webpack 1. I'm not able to test it right now but if you can confirm that is still a bug in webpack 1 I can reopen it.

**Comment by dpundir** [comment]
I am using webpack 1.13.1 and this "require([varname], function() {})" is still and issue.

**Comment by bebraw** [comment]
It's not going to get fixed for webpack 1 as the focus is on 2.
