### ISSUE TITLE
webpack ensure have number filename

### ISSUE THREAD

**Issue by DebugIsFalse** [webpack/webpack#2321]
Code :
router.map({
    '/index' : {
        component : function( resolve ){
            require.ensure(["../webcomponent/index/module-index.js"], function(require) {
               require( "../webcomponent/index/module-index.js" );
            },'module-index');
            
        }
    },
    '/foo': {
        component: function( resolve ){
            require.ensure(["../webcomponent/foo/foo.js"], function(require) {
               require( "../webcomponent/foo/foo.js" );
            },'foo');
        }
    }
})
when I webpack the Code,while built file will has number fillname,example 1.module-index.js or 2.foo.js and so on;
I want to know that why built file is that;

**Comment by sokra** [comment]
It depends on the `output.chunkFilename` option, which defaults to `[id].[name].js`
