### ISSUE TITLE
ResolverPlugin not defined in v2.1.0-beta.5

### ISSUE THREAD

**Issue by tomasAlabes** [webpack/webpack#2324]
Although the plugin is listed in https://github.com/webpack/webpack/blob/master/lib/webpack.js#L73, the plugin is not part of https://github.com/webpack/webpack/tree/master/lib. Found it while using the bower conf
```
new webpack.ResolverPlugin(
			new webpack.ResolverPlugin.DirectoryDescriptionFilePlugin("bower.json", ["main"])
		)
```
Error:
```
module.js:341
    throw err;
    ^

Error: Cannot find module './ResolverPlugin'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Function.Object.defineProperty.get [as ResolverPlugin] (/Volumes/Repositories/pcsV2/bpm/main/modules/composer/js/core/node_modules/webpack/lib/webpack.js:56:12)
    at Object.<anonymous> (/Volumes/Repositories/pcsV2/bpm/main/modules/composer/js/core/webpack.config.js:88:14)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
``` 
I didn't offer a PR as I don't know your intention here, to replace or remove it.

**Comment by sokra** [comment]
It was removed. There is now a option `resolve.plugins`. But for `bower` you don't need a plugin anymore, as the resolve options has been expanded. See: https://gist.github.com/sokra/27b24881210b56bbaff7#resolving-options

**Comment by leonid-bauxy** [comment]
But it says nothing about `resolve.plugins`. What does webpack expect in `resolve.plugins`? Where should the user get those plugins, if plugins from `enhanced-resolve` aren't exposed in any way?

**Comment by sokra** [comment]
`plugins` is for custom plugins. The plugins in enhanced-resolve are not needed for this.

**Comment by leonid-bauxy** [comment]
How do we access the `enhanced-resolve` plugins, like documented [here](https://github.com/webpack/docs/wiki/list-of-plugins#resolverpluginfileappendplugin) and [here](https://github.com/webpack/enhanced-resolve/wiki/Plugins)?

**Comment by sokra** [comment]
The documentation is for webpack 1. I'll publish new documentation with webpack 2.

**Comment by leonid-bauxy** [comment]
Ok, thank you!

For my use case i want to define a custom dynamic `mainFile` and can't figure out how to do it.

I'd like imports to `components/ComonentName/` resolve to `components/ComponentName/ComponentName.jsx` instead of `index.js` or `index.jsx`. I tried `NormalModuleReplacementPlugin`, but it gets request before the alias is resolved. I'd like it to be after that.

If it's no trouble, could you point me in the right direction? I think i'm supposed to hook into `resolve` process somehow, but i can't find any documentation it's plugins or stages for webpack 2.

**Comment by mgcrea** [comment]
Has the documentation been updated for webpack2? I'm struggling to use `enhanced-resolve` plugins in webpack2.

**Comment by d3viant0ne** [comment]
@mgcrea All of the documentation for Webpack2 will live in webpack/webpack.io. Outside of that, if you have a specific question I'd suggest opening a new issue which makes the resolution easier for others to find later.

**Comment by nilssolanki** [comment]
I'm very interested in the same problem as @leonid-bauxy. I would like to keep all the defaults and configs (such as `resolve.modules` and `resolve.extensions`) and only _add_ a `ComponentName/ComponentName.js` case. Is that possible?

**Comment by grantm44** [comment]
How does this resolve work can someone explain? I'm trying to add some bower_components and was only using the npm before. 
```
module.exports = {
  context: __dirname + '/client',
  entry: {
    client: './map.js',
    vendor: [
      'angular',
      'angular-route',
      'jquery',
      'bootstrap'
    ]
  },
  output: {
    filename: 'script.bundle.js',
    path: __dirname + '/public/scripts'
  },
  resolve: {
    modules: [path.join(__dirname, 'bower_components')]
  },
  plugins: [
    new webpack.optimize.CommonsChunkPlugin({name: 'vendor', filename: 'vendor.bundle.js'})
  ]
}
```
Now it's not finding the vendor packages

**Comment by ooXei1sh** [comment]
@grantm44 I only needed to add:

    resolve: {
        modules: ["bower_components", "node_modules"]
    },

After that it just worked. There's a thread [here](https://github.com/lpiepiora/bower-webpack-plugin/issues/39#issuecomment-291114301) that's in the old bower-webpack-plugin with commented resolve config.
