### ISSUE TITLE
Allow passing screw_ie8 option to uglify-js

### ISSUE THREAD

**Issue by lee-houghton** [webpack/webpack#2325]
This isn't just an efficiency thing, not using `screw_ie8` can cause UglifyJS2 to produce incorrect output (see https://github.com/mishoo/UglifyJS2/issues/409).

I may have time to supply a pull request for this one. If anyone else wants to look at it, I think there should be a single option which sets `screw_ie8` on the options to all of the following calls. (Some of them can be specified already, such as `{ compress: { screw_ie8: true } }` or `{ mangle: { screw_ie8: true } }`, but the key place is actually `figure_out_scope` in the case where it produces incorrect output.)
- Compressor().
- figure_out_scope().
- compute_char_frequency().
- mangle_names().
- OutputStream().

**Comment by acusti** [comment]
This would be great. So as I understand, if you add the UglifyJsPlugin like so:

```js
plugins: [
    new webpack.optimize.UglifyJsPlugin({
        compress: { screw_ie8: true },
        mangle: { screw_ie8: true }
    })
]
```

You will get the screw_ie8 behavior for the Compressor() and mangle_names() functions. Please correct me if I am mistaken. Thanks!

**Comment by lee-houghton** [comment]
mishoo/UglifyJS2#409 is now closed. `screw_ie8` is now the default behaviour as of UglifyJS2 2.7.0. I have no need this enhancement any more, although those people needing IE8 compatibility may want to keep it open.

**Comment by alqu** [comment]
This issue can easily be closed if the dependency  in package.json is adjusted from "~2.6.0" to "~2.7.0".

**Comment by Poky85** [comment]
@sokra So right now there is no chance to generate valid code for IE8, right?

**Comment by sokra** [comment]
You can pass `screw_ie8: false`, can't you?

**Comment by Poky85** [comment]
@sokra Trying to safely generate this code for IE8:

```javascript
export default {
	for: "hello",
	class: "world"
}
```

Expected results:

```javascript
// some Webpack code here...
{
	"for": "hello",
	"class": "world"
}
```

Found that uglify-js OutputStream should take care of that https://github.com/mishoo/UglifyJS2/blob/master/lib/output.js#L67

But passing these options doesn't work

```javascript
new webpack.optimize.UglifyJsPlugin({
	compress: { screw_ie8: false },
	mangle: { screw_ie8: false },
	output: { screw_ie8: false }
})
```

**Comment by lee-houghton** [comment]
I might be mistaken, because it was some time ago, but I don't think the `screw_ie8` flag is passed to all stages of the uglifyjs process. In particular I think it's the `figure_out_scope` call that I mentioned when I opened this issue, but I think there's a few others. The main thing this affected in my case was variable capturing in catch clauses.

https://github.com/webpack/webpack/blob/master/lib/optimize/UglifyJsPlugin.js#L95

**Comment by Kovensky** [comment]
Note that, if you use webpack 2, even if you get `screw_ie8: false` to work, your code will crash at runtime in IE8 because webpack 2's bootstrap depends on a properly functioning `Object.defineProperty`.

**Comment by sokra** [comment]
It may work when
* not using HMR
* not using ES2015 Modules
