### ISSUE TITLE
Ubuntu 16.04 Webpack Problem

### ISSUE THREAD

**Issue by WebRuin** [webpack/webpack#2327]
I was able to install Webpack globaly with sudo npm install webpack -g. However when I try to install webpack locally in my project with sudo npm i webpack -D or sudo npm install webpack --save-dev I get:

`npm ERR! Linux 4.4.0-18-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/local/bin/npm" "install" "webpack" "-D"
npm ERR! node v4.2.6
npm ERR! npm v3.8.6
npm ERR! code ENOSELF

npm ERR! Refusing to install webpack as a dependency of itself
`

Is this a known issue? I have to install all npm packages with sudo on my Ubuntu box. I now of npm "sudo fixes" for mac but not Ubuntu

**Comment by WebRuin** [comment]
https://github.com/npm/npm/issues/12322

**Comment by bebraw** [comment]
I'm closing this in favor of that npm issue given it looks like that thread is active and this is an upstream issue. 👍
