### ISSUE TITLE
How can I do something after a build

### ISSUE THREAD

**Issue by Jokcy** [webpack/webpack#2328]
My loader will create some cache files while building, and I want to remove these files at the end of build.

What can I do?

**Comment by bebraw** [comment]
You could write a plugin and then perform the cleanup at `emit`. See https://webpack.github.io/docs/plugins.html for the basic idea.

**Comment by bebraw** [comment]
Of course one option is to do nothing and write to a dotfile. Or you can let the user to toggle caching behavior through a flag.
