### ISSUE TITLE
How can append query string to chunk files request when I use require.ensure ?

### ISSUE THREAD

**Issue by mc-zone** [webpack/webpack#2329]
I have use `require.ensure` to generator async chunk files like: 
```javascript
require.ensure([],function(require){
  let Page1 = require('./page-1');
  let Page2 = require('./page-2');
//...
},'page-chunk')
```

When I want to refresh the broswer cache after I changed code and rebuild, I use `chunkhash` at config file and make chunks have a new flie name:
```javascript
output: {
  //...
  chunkFilename: outputDir + "/[id].[name]-[chunkhash].js"
},
```

But it has ouccr too many files over and over again. and I often need to delete old files both local and server(also maybe it is unsafe):

![Too many generator files](http://qzonestyle.gtimg.cn/aoi/sola/20160413204550_HrWJdAW6jt.png)

====
**QUESTION**: Is there any way I can use query string for chunk files? I mean, for example :

```javacript
require.ensure([],function(require){
  let Page1 = require('./page-1');
  let Page2 = require('./page-2');
//...
},'page-chunk', '?ver=[chunkhash]')
```

Then request should append search string when fetch the script like it:
```
http://cdn.com/path/output/1.page-chunk.js?ver=c5434xxxxxxx
```
Anyone have any experience on this? Thanks and looking forward to your help.   :frowning:

**Comment by sokra** [comment]
``` js
chunkFilename: outputDir + "/[id].[name].js?ver=[chunkhash]"
```

**Comment by sokra** [comment]
But better use the hash in filename and use no query parameter.

**Comment by mc-zone** [comment]
Thanks!  @sokra 
But what are the advantages of use hash in filename compare with query string? Well hope to hear your opinion.

**Comment by sokra** [comment]
* User opens app with hash 1234.
* User loads `app.js?1234` and `chunk1.js?1234`
* User leaves the app open
* You publish an update with hash 5678
* User requests another chunk: `chunk2.js?1234`
* App crashes because `chunk2.js?1234` (loaded after the update) isn't consistent with `app.js?1234` (loaded before the update), because `chunk2.js` was overwritten by your update and is now `chunk2.js?5678`.

**Comment by mc-zone** [comment]
I see. I understand now. Thanks again. :+1:

**Comment by Pedrozena** [comment]
What if I have to send some custom parameters that are known only when I call require.ensure? For example an identification key that authorize the user HTTP GET request for the given chunk on the server-side.

**Comment by RaSeR** [comment]
> * User opens app with hash 1234.
> * User loads `app.js?1234` and `chunk1.js?1234`
> * User leaves the app open
> * You publish an update with hash 5678
> * User requests another chunk: `chunk2.js?1234`
> * App crashes because `chunk2.js?1234` (loaded after the update) isn't consistent with `app.js?1234` (loaded before the update), because `chunk2.js` was overwritten by your update and is now `chunk2.js?5678`.

so just use contenthash - and there is no such problem anymore.

**Comment by aprilmintacpineda** [comment]
what about if I want to achieve this to append a pre-computed value on the query string? like so

`file.js?computedValue=somevalue`

**Comment by hiepxanh** [comment]
// https://github.com/webpack/webpack/issues/11816#issuecomment-716402552
```
declare var __webpack_get_script_filename__: any;
const oldFn = __webpack_get_script_filename__;

__webpack_get_script_filename__ = (chunkId) => {
  const filename = oldFn(chunkId);
  return filename + `?v=${environment.timestamp}`;
};
```

go enjoy, do you love me ?
