### ISSUE TITLE
how can i use online resource?

### ISSUE THREAD

**Issue by memotail** [webpack/webpack#2332]
i must use other resource like this
import 'http://map.google.com/....';

use amd can do it
require(['http://map.google.com/....'], () => {
});

and webpack?

i use react、webpack、babel。

**Comment by bebraw** [comment]
Webpack operates based on static code analysis so it cannot perform operations like this. You can, however, use a third party solutions like [little-loader](https://github.com/walmartlabs/little-loader) or [script.js](https://github.com/ded/script.js/) to achieve the result you want.
