### ISSUE TITLE
Webpack dev server with multiple entry files and dedupe plugin does not properly update

### ISSUE THREAD

**Issue by johanneslumpe** [webpack/webpack#2335]
When using the dev server with multiple entry points the initial render works fine. As soon as a file is changed though, the next execution will throw

`Uncaught TypeError: Cannot read property 'apply' of undefined`

When both apps are open, one of them will receive hot updates and break when refreshing the page. The other one will not receive hot updates, but render correctly when refreshing the page.

Is there anything special that needs to be taken into account when using multiple entry points?

// edit
It does not matter whether hot reloading is enabled or not - as soon as two entry points are present and one gets updated, the build is broken after refreshing the page.

**Comment by johanneslumpe** [comment]
After investigating more, it seems that it has to do with the dedupe plugin. So the actually issue seems to be that when having multiple entry points and the dedupe plugin, something breaks.

**Comment by bebraw** [comment]
I'm closing this as there's no `DedupePlugin` in webpack 2 anymore.
