### ISSUE TITLE
Webpack bundles empty module for process after readable-stream upgrade

### ISSUE THREAD

**Issue by quandrum** [webpack/webpack#2342]
Several days ago readable-stream, a dependency of stream-browserify that Webpack uses via node-libs-browser as a stream shim, to include a process check: 

https://github.com/nodejs/readable-stream/commit/c03d159affdc6816c4e7d5ff42236ea460cc7242

This resulted in runtime errors, because process was not defined in our browser build.

Webpack built this for readable-stream:

```
/* 499 */
/***/ function(module, exports, __webpack_require__) {

    /* WEBPACK VAR INJECTION */(function(process) {exports = module.exports = __webpack_require__(500);
    exports.Stream = __webpack_require__(498);
    exports.Readable = exports;
    exports.Writable = __webpack_require__(505);
    exports.Duplex = __webpack_require__(504);
    exports.Transform = __webpack_require__(507);
    exports.PassThrough = __webpack_require__(508);
    if (!process.browser && process.env.READABLE_STREAM === 'disable') {
      module.exports = __webpack_require__(498);
    }

    /* WEBPACK VAR INJECTION */}.call(exports, __webpack_require__(280)))

```

If we check require 280, we see:

```
/* 280 */
/***/ function(module, exports) {



/***/ }
```

process.js is correctly polyfilled above this at position 274. I'm not sure what's causing this, and we're locking down the version of readable-stream for now to prevent this, but it seems webpack is doing something wrong here.

This is webpack 1.12.15 fyi

**Comment by dignifiedquire** [comment]
I'm seeing the same issue on `webpack@2.1.0-beta.6`

**Comment by dignifiedquire** [comment]
I have found a workaround for this:

```js
```

**Comment by diasdavid** [comment]
Is this still an issue?

**Comment by diasdavid** [comment]
Seems it is not anymore with WebPack 3 and readable-stream 2.3.3 🎉
