### ISSUE TITLE
[plugins] Injecting a dependency and source code into a top-level module

### ISSUE THREAD

**Issue by wayspurrchen** [webpack/webpack#2343]
Hi! I'm trying to accomplish something a little weird with a webpack plugin and I think it should be possible, I'm just not sure how with webpack's internals.

I have multiple entry points that become named chunks. For each chunk, I want to take the top-level module and inject a dependency into it, and also add source code to the front of the module to execute the dependency's code. There's nothing special about the dependency; it's just a file on the filesystem, and it's also used in some other modules.

So my question is - what hooks do I need to plug into? At the moment i'm trying to use `"optimize-chunks"`, and then check if the chunk has a name and an origin. If it does, I feed the Compilation object a dependency I made up with addModuleDependencies:

``` javascript
MyPlugin.prototype.apply = function(compiler) {
    compiler.plugin('compilation', function( compilation, params ) {

        compilation.plugin('optimize-chunks', function( chunks ) {
            chunks.forEach( function ( chunk ) {
                if ( chunk.origins.length === 0 ) {
                    return;
                }

                var chunkOrigin = chunk.origins[ 0 ];

                if ( chunkOrigin.name ) {
                    compilation.addModuleDependencies(
                        chunkOrigin,
                        [ [ {
                            module: null,
                            request: 'owen/user-timing',
                            userRequest: 'owen/user-timing',
                            optional: false
                        } ] ]
                    );
                }
            } );
        });
    });
};
```

This is pretty clearly wrong since it doesn't work but I haven't been able to find the right point at which I can get into where Webpack figures out what files are being resolved. A pointer to the right line would be awesome.

Thanks!

**Comment by sokra** [comment]
What's the use case for this?

Run some code before each chunk?

**Comment by wayspurrchen** [comment]
@sokra Yes, pretty much, but we also want to run some code after the contents of the top chunk. I have a lot of chunks and would like to emit analytics data to our servers about the performance of each chunk.

**Comment by bebraw** [comment]
@TheLarkInn This is related to analytics so you might want to have a good look.
