### ISSUE TITLE
Regression in Webpack 2.0 beta: noParse makes `require()` return an empty object instead of the target module

### ISSUE THREAD

**Issue by aaugustin** [webpack/webpack#2345]
I'm using the `noParse` option to prevent webpack from complaining about a pre-built library, namely Google's libphonenumber which can only be built with Closure Compiler (AFAIK). Here's the warning I want to silence:

```
WARNING in ./~/google-libphonenumber/dist/browser/libphonenumber.js
Critical dependencies:
1:760-767 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/google-libphonenumber/dist/browser/libphonenumber.js 1:760-767
```

Since I upgraded to webpack 2 beta, this results in the library not loading anymore. Instead calling `require('google-libphonenumber')` returns an empty Object. In my testing, using an ES6 import or `require` doesn't make a difference.

----

Here's a reduced test case for reproducing this issue.

**Requirements**

* babel-core @ 6.7.6
* babel-loader @ 6.2.4
* babel-preset-es2015-webpack @ 6.4.0
* babel-preset-react @ 6.5.0
* babel-preset-stage-0 @ 6.5.0
* google-libphonenumber @ 1.0.17
* webpack @ 2.1.0-beta.5

**.babelrc**

```javascript
{
    "presets": [
        "es2015-webpack",
        "stage-0",
        "react"
    ],
}
```

**webpack.js**

```javascript
module.exports = {

    entry: './test.js',

    module: {
        loaders: [{
            test: /\.js$/,
            loader: 'babel',
        }],
        // Commenting this out makes the problem go away, but triggers a warning.
        noParse: [
            /\/libphonenumber\.js$/,
        ],
    },

    output: {
        filename: './test.pack.js',
    },

    resolve: {
        modules: [
            'node_modules',
        ],
    },

};
```

**test.js**

```javascript
window.libphonenumber = require('google-libphonenumber');
console.log(window.libphonenumber);
```

**index.html**

```html
<html>
    <head><title>Test webpack libphonenumber</title></head>
    <body><script src="test.pack.js"></script></body>
</html>
```

**Compile with webpack 2 & babel**

```
% webpack --config=webpack.js
[BABEL] Note: The code generator has deoptimised the styling of "/Users/myk/Documents/dev/amalfi-web/node_modules/google-libphonenumber/dist/browser/libphonenumber.js" as it exceeds the max of "100KB".
Hash: f2fe22f538e18542adf7
Version: webpack 2.1.0-beta.5
Time: 3438ms
         Asset    Size  Chunks             Chunk Names
./test.pack.js  351 kB       0  [emitted]  main
    + 2 hidden modules
```

**Open the inspector and load index.html**

`require('google-libphonenumber')` just returns `Object {  }`.

```
> libphonenumber.PhoneNumberFormat
undefined
```

----

Downgrading to webpack 1.13.0 resolves the issue.

**Recompile with webpack 1 & babel**

```
% webpack --config=webpack.js
[BABEL] Note: The code generator has deoptimised the styling of "/Users/myk/Documents/dev/amalfi-web/node_modules/google-libphonenumber/dist/browser/libphonenumber.js" as it exceeds the max of "100KB".
Hash: a733035fbcc3c09f6239
Version: webpack 1.13.0
Time: 2835ms
         Asset    Size  Chunks             Chunk Names
./test.pack.js  351 kB       0  [emitted]  main
    + 2 hidden modules
```

**Open the inspector and load index.html**

`require('google-libphonenumber')` returns the expected result.

```
> libphonenumber.PhoneNumberFormat
Object { E164: 0, INTERNATIONAL: 1, NATIONAL: 2, RFC3966: 3 }
```

**Comment by sokra** [comment]
yep, bug is know and the change will be reverted soon.

**Comment by aaugustin** [comment]
Great. Thanks! Let me know if I can help, perhaps by testing a change.

**Comment by sokra** [comment]
fixed

**Comment by ruimarinho** [comment]
@sokra is there anything that is being done by `google-libphonenumber` which could have prevented this from happening with webpack? I.e. is there any improvement to be made on the package side?

**Comment by sokra** [comment]
@ruimarinho It works fine now.
