### ISSUE TITLE
Under devServer key in webpack.config.js, I set hot: true option, but it dosen't work 

### ISSUE THREAD

**Issue by Authorlove** [webpack/webpack#2346]
CLI: webpack-dev-server --hot works, 
but
```js
devServer:{
    hot: true
}
```
it throws Uncaught Error: [HMR] Hot Module Replacement is disabled.

**Comment by bebraw** [comment]
If you use `hot: true` that way, I think you need to set

```javascript
plugins: [
  new webpack.HotModuleReplacementPlugin()
]
```

A little confusing, yeah.

**Comment by Authorlove** [comment]
Thanks for your help!
