### ISSUE TITLE
Webpack2: hot reload doesn't work if wds is not installed locally

### ISSUE THREAD

**Issue by whitecolor** [webpack/webpack#2348]
I noticed a stranage behaviour: I have webpack 2 and wds 2 beta installed globally. I run may run server `webpack-dev-server --hot --inline` - but then hot reload does not work, on file change I see in web console:

```
[WDS] Hot Module Replacement enabled.
[WDS] App updated. Recompiling...
[WDS] App hot update...
[WDS] App updated. Recompiling...
[WDS] App hot update.
```
An nothing happens.

If install webpack and wds locally and run the same from command line ``webpack-dev-server --hot --inline` it works as expected.

**Comment by TheLarkInn** [comment]
@whitecolor can you list the following: 

`webpack` & `webpack-dev-server` versions you experienced this?

If updating both packages to latest builds, do you see this issue still?

**Comment by whitecolor** [comment]
"webpack": "^2.1.0-beta.7",
"webpack-dev-server": "^2.0.0-beta",

**Comment by TheLarkInn** [comment]
Can you update to 2.1.0-beta.14 and let me know if this is still a problem.
