### ISSUE TITLE
import {x} from './a' doesn't work

### ISSUE THREAD

**Issue by whitecolor** [webpack/webpack#2349]
This seem  not to work without babel simple case of requiring named export:

module a.js:
```js
export const x = 1 // named export
export default 0 // default export
```
module b.js
```js
import {x} from './a' // named imported cases an errors
```
**it gives a like an error for all modules that require `a`**

if import default module in b.js, it works
```js
import a from './a' 
a == 0 // default imported ok
```

This is an obvious thing, sorry if the issue is exessive.

**Comment by bebraw** [comment]
Is this for webpack 2?

**Comment by whitecolor** [comment]
Yes, 2.1.0 beta5

**Comment by sokra** [comment]
hmm... works fine for me...

**Comment by sokra** [comment]
Which error is thrown?

**Comment by whitecolor** [comment]
Right I checked it work, maybe something related to this package I think `https://github.com/blakeembrey/free-style` 
```
Uncaught ReferenceError: __WEBPACK_IMPORTED_MODULE_0_free_style__ is not defined
```
But as I said with babel it works.

**Comment by TheLarkInn** [comment]
@whitecolor is this still an issue anymore in webpack@2.1.0-beta.14
