### ISSUE TITLE
Getting error in multiple-entry-points demo

### ISSUE THREAD

**Issue by kamrenz** [webpack/webpack#2350]
The commons.js file tries to load the 0.chunk.js from the root directory not from the js/ directory where Webpack built it into. In other words when I serve up Page A from "http://localhost:8080/pageA.html" the browser dev tools show me the chunk is trying to be fetched from "http://localhost:8080/0.chunk.js" when it should be coming from "http://localhost:8080/js/0.chunk.js". If I manually copy the chunk to the root then the demo works.

webpack.config.js
```
var path = require("path");
var webpack = require('webpack');
module.exports = {
	entry: {
		pageA: "./pageA",
		pageB: "./pageB"
	},
	output: {
		path: path.join(__dirname, "js"),
		filename: "[name].bundle.js",
		chunkFilename: "[id].chunk.js"
	},
	devtool: 'source-map',
	plugins: [
		new webpack.optimize.CommonsChunkPlugin({
			filename: "commons.js",
			name: "commons"
		})
	]
}
``` 
folder structure
```
server.js
package.json
common.js
pageA.html
pageA.js
pageAB.html
pageB.js
shared.js
webpack.config.js
js/
  0.chunk.js
  commons.js
  pageA.bundle.js
  pageB.bundle.js
```

**Comment by kamrenz** [comment]
Here is a GitHub repo with a server and package.json file. You'll notice I had to move the chunk.js file to the root manually.

**Comment by kamrenz** [comment]
Shouldn't I just be able to run webpack and have the webpack.config.js build the application? What is the purpose of build.js?

**Comment by sokra** [comment]
See option `output.publicPath`

**Comment by bebraw** [comment]
@kamrenz Did `output.publicPath` do the trick for you?

**Comment by kamrenz** [comment]
Thanks @bebraw, setting publicPath to my assets worked.
```
output: {
        path: path.join(__dirname, "js"),
        filename: "[name].bundle.js",
        chunkFilename: "[id].chunk.js",
        publicPath: "/js/"
    },
```
