### ISSUE TITLE
`resolve.root` is not working on master

### ISSUE THREAD

**Issue by rosenfeld** [webpack/webpack#2355]
I tried to run webpack from master to check how things are going. I'm not sure what is the recommended method so I simply cloned the repo under `node_modules/webpack` and `chmod +x node_modules/webpack/bin/*`. I'm getting errors like:

```
ERROR in multi app/client
    Module not found: Error: Can't resolve 'client.js' in '/home/.../app/resources/src'
     @ multi app/client
```

It works just fine with the same config in webpack 1. The `client.js` file actually lives in `src/js` but `resolve.root` has the full path for it:

```javascript
  , resolve: {
    root: [
      path.resolve('./src/js')
```

Any ideas on what is wrong?

**Comment by alexanderchr** [comment]
https://gist.github.com/sokra/27b24881210b56bbaff7

```
    modules: [path.resolve(__dirname, "app"), "node_modules"]
    // (was split into `root`, `modulesDirectories` and `fallback` in the old options)
    // In which folders the resolver look for modules
    // relative paths are looked up in every parent folder (like node_modules)
    // absolute paths are looked up directly
    // the order is respected
```

**Comment by rosenfeld** [comment]
Thanks, @alexanderchr! I tried to find the changes for webpack 2 in the past but haven't seen this document before, thanks for pointing me that out. I'm closing this because I think the decision is by design and not supposed to be backward-compatible, so not a bug really...
