### ISSUE TITLE
CommonsChunkPlugin async file name

### ISSUE THREAD

**Issue by iotch** [webpack/webpack#2363]
Hello. 
How should we configure the output file name when the CommonsChunkPlugin is used with the option `async: true`? Now it creates `0.js` file, and setting a filename, say, `filename: 'common-async.js'` breaks the merging and all the chunks stays big.
Thanks!

**Comment by sokra** [comment]
It's affected by the `output.chunkFilename` option.

**Comment by iotch** [comment]
It's strange, I have `output.chunkFilename` set to `[name]-chunk.js`, and it works fine with `require.ensure()` however, async file created by CommonsChunkPlugin is `0.js`.

**Comment by langpavel** [comment]
Cite from [doc](https://github.com/webpack/docs/wiki/configuration#outputchunkfilename):

> ## output.chunkFilename
> 
> The filename of non-entry chunks as relative path inside the output.path directory.
> 
> `[id]` is replaced by the id of the chunk.
> 
> `[name]` is replaced by the name of the chunk (or with the id when the chunk has no name).
> 
> `[hash]` is replaced by the hash of the compilation.
> 
> `[chunkhash]` is replaced by the hash of the chunk.

Do you configure your entries in array or in a object? If in array, key for first item will be `0`

**Comment by iotch** [comment]
Ok, here is the actual config:

````javascript
{
    devtool: 'source-map',
    debug: true,
    cache: true,
    context: path.join(__dirname, 'src'),
    resolve: {
        modules: [
            path.resolve(__dirname, 'src'), 
            path.resolve(__dirname, 'node_modules')
        ],
        extensions: ['', '.js', '.jsx', '.scss'],
    },
    entry: {
        app: './index.js',
    },
    output: {
        path: path.join(__dirname, 'public/assets'),
        publicPath: '/assets/',
        filename: '[name].js',
        chunkFilename: '[name]-chunk.js',
    },
    module: {
        loaders: [...],
    },
    plugins: [
        new webpack.optimize.CommonsChunkPlugin({
            children: true,
            async: true,
            minChunks: 2,
        }),
    ]
}
````
And webpack's output:
````
Hash: b92f66def6ed9f297ac3
Version: webpack 2.1.0-beta.5
Time: 7877ms
                  Asset     Size  Chunks             Chunk Names
             0-chunk.js   271 kB       0  [emitted]  
                 app.js  1.04 MB       1  [emitted]  app
    my-section-chunk.js   5.8 kB       2  [emitted]  my-section
fetch-polyfill-chunk.js  10.8 kB       3  [emitted]  fetch-polyfill
  home-section-chunk.js  2.01 kB       4  [emitted]  home-section
    + 270 hidden modules

````

**Comment by iotch** [comment]
Let me specify my question. 
How can I set the chunk name for the asyc chunk of the CommonsChunkPlugin? 

As you nay see from the example output above, all of my chunks have names set with the third argument of `require.ensure()`. 

How can I achieve the same with the CommonsChunkPlugin and it's option of `async: true`?

**Comment by sokra** [comment]
> How can I set the chunk name for the async chunk of the CommonsChunkPlugin?

Instead of `async: true` use `async: "name"`

**Comment by iotch** [comment]
It worked, thanks!

**Comment by phiphou** [comment]
I have exactly the same problem but @sokra solution doesn't work for me. Still produce a file named 1.js. Can't find anywhere any sample demonstrating that. Can you help me ? .

**Comment by sokra** [comment]
In addition to `async: "name"` you also need to set `output.chunkFilename` to something that includes `[name]`, i. e. `"[name].js"`.

`async: "name"` sets only the chunk name not the chunk filename

**Comment by phiphou** [comment]
Tried with [name].js, but with no luck (no diff between [id] and [name]).

So here is what I'm doing now, using es6-promise-loader in angular2.

```
@RouteConfig([
  ...,
  { path: '/route', 
    name: 'RouteName', 
    loader: () => require('es6-promise?es6-promise,ChunkName!./route/route.component')('RouteName') 
  }
])
```

And in webpack config : 

```
config.output = {
   ...,
  chunkFilename: [name].chunk.js';
}
```
And it works ;)
