### ISSUE TITLE
Visual Studio debugger breakes from adding When to WebPack bundle

### ISSUE THREAD

**Issue by henrify** [webpack/webpack#2364]
If I create a CommonJS compatible bundle using WebPack and include 'When' library in the bundle, then debugging in Visual Studio (2013 and 2015) brakes:
- Brakepoints are not hit
- Warning 'The breakpoint will not currently be hit. No symbols have been loaded for this document' is displayed next to breakpoints.

Additional info:
- If I don't include When to the bundle, but keep everything else exactly same, then debugger works fine.
- If I create the bundle using Browserify instead of WebPack, then debugger works fine.
- If I include another library of comparable size instead of 'When', then debugger works fine.

Please find attached Visual Studio solution for repro.

After running commands 'npm install' and 'webpack', you can debug this just fine in Visual Studio. If you remove the comments from the six lines that include 'When' to the bundle and run 'webpack' again, then Visual Studio debugging brakes.

I'm not sure if this is WebPack or When issue or bit of both, so crossposting. The issue in When project is https://github.com/cujojs/when/issues/486

[WebpackWhenSourcemapTest.zip](https://github.com/webpack/webpack/files/227776/WebpackWhenSourcemapTest.zip)

![when and webpack brake debugging](https://cloud.githubusercontent.com/assets/7379209/14672357/a69a9cda-073a-11e6-8c0c-856a6d1cd9d3.jpg)
![debugging works if when is commented out](https://cloud.githubusercontent.com/assets/7379209/14672358/ad312d70-073a-11e6-9798-bed759be4f43.jpg)

**Comment by henrify** [comment]
@bebraw  Moi. This is not a question. It's a 100% reproducible show stopper bug.

**Comment by bebraw** [comment]
Can you try against webpack 2 rc? Thanks.
