### ISSUE TITLE
require is not defined when using resolve.alias/noParse for minified react 

### ISSUE THREAD

**Issue by quirm** [webpack/webpack#2365]
I'm using a following config to use provided minified version (React 15.0):
```
var path = require('path');
var webpack = require('webpack');

module.exports = {
  entry: './src/client.js',
  devtool: 'eval',
  output: { ... },
  module: {
    noParse: /\.min\.js/,
    loaders: [{
      test: /\.js$/,
      exclude: /node_modules/,
      loaders: ['babel-loader'],
      query: {
        presets: ['es2015', 'react'],
      }
    }]
  },
  resolve: {
    modulesDirectories: ['node_modules'],
    alias: {
      'react': 'react/dist/react.min.js',
      'react-dom': 'react-dom/dist/react-dom.min.js'
    }
  }
};
```

It seems that webpack correctly merges minified libraries but "require" function is not provided and the whole bundle fails at point when the first require function is used within these two libs with `require is not defined`. What could I use for webpack 2.x to make this work?

**Comment by Someguy123** [comment]
@quirm From the docs on *noParse*:

>The files are expected to have no call to require, define or similar. They are allowed to use exports and module.exports.

**Comment by quirm** [comment]
Right, thank you for info. I got it to the same size as minified version with properly set webpack config.
