### ISSUE TITLE
Webpack 2.1.0-beta.5 build stucks

### ISSUE THREAD

**Issue by Strate** [webpack/webpack#2366]
I've tried webpack 2.1.0-beta5 on my project and it stuck due compilation on the styl file. Every time it stucks on the same file. How can I debug it?

**Comment by TheLarkInn** [comment]
@Strate Is this still a problem in `webpack@2.1.0-beta.14`? If so please respond so we can prioritize this issue.

**Comment by Strate** [comment]
@TheLarkInn there is no problems with webpack@2.1.0-beta.18. I'm closing this issue.
