### ISSUE TITLE
I18n with requirejs plugin

### ISSUE THREAD

**Issue by tomasAlabes** [webpack/webpack#2367]
Hi, sorry to post the question here but I haven't had luck in gitter nor [stack-overflow](http://stackoverflow.com/questions/36733617/webpack-requirejs-i18n-plugin-in-3rd-party-lib).

Due to some of my dependencies, I need to continue using my locales bundles dynamically with requirejs i18n plugin, I can't have 1 bundle per locale. Also I can't touch the `"i18n!translations"` calls because they are inside of my dependency, it should be something configured in webpack, basically:

**How do I tell webpack, when requests that start with `i18n!` are found, to skip them from analysis and use regular `require` in the browser?**

**Comment by tomasAlabes** [comment]
I think I solved it with an `externals` function. I'm just making my 3rd party lib external to have those requires outside webpack.
I wouldn't know how to make an unknown require test for /i18n/ and make it dynamic though, but it doesn't seem necessary anymore for me.
Thanks

**Comment by sppatel** [comment]
@tomasAlabes can you provide an example of what you did?

**Comment by tomasAlabes** [comment]
Something like this:

```javascript
externals: [
		function(context, request, callback) {
			if (/^(i18n\!)/.test(request)) {
				return callback(null, 'amd ' + request);
			}
			callback();
		}
	]
```
Make all dependencies that start with `i18n!` externals to my library.
Hope it helps.

**Comment by sppatel** [comment]
@tomasAlabes thx for the quick response! Its still a bit unclear to me.   So here is specifically what I have.. Here is a require.js/amd module that I have defined that depends on a custom requirejs nls plugin.

```
define("my_module", ["module", "jquery", "nls!common"], function(module, $, msgs) {

})
```

The plugin is a local file e.g nls.js which structurely contains something like..

```
(function () {
    function some_private_method() {}
    define("nls", {
        load: function (name, req, onload, config) {
            some_private_method();
        }
    });
} ());
```

When I run web pack it complains about nls!common unable to resolve it.  So is this essentially the same problem you faced?  If How would this translate to an external?

**Comment by tomasAlabes** [comment]
Try using my function with nls instead of i18n and see what happens. Try to imitate how i18n works but with your plugin (you will probably need to define where your plugin is the rjs config). 
If possible make a small project with these files and try everything there, it's easier to analyze.

**Comment by uzikilon** [comment]
Adding an external totally works. I used @tomasAlabes's suggestion:
```javascript
externals: [
  function(context, request, callback) {
    if (/^i18n\!/.test(request)) {
      return callback(null, 'amd ' + request);
    }
    callback();
  }
]
```
however, this minifies **all** languages into the target file ending up as a gigantic file in my case, while using requireJS it loads them from the server without packing, which only loads the specific locale used for the specific user/session.
is this something webpack is capable of doing?
