### ISSUE TITLE
Is there a way to read a package.json for embedding version information without storing the JSON?

### ISSUE THREAD

**Issue by dschissler** [webpack/webpack#237]
I would like to be able to use package.json for my project to embed the version information into the script.  Is there a way to do this without including the entire JSON into the script?  I want it to be evaluated and immediately dumped.  Should I use normal node commands for this?  I would like to be able to go through the webstack library so that I only have a single node dependency in my browser code.

**Comment by ssorallen** [comment]
Including "package.json" worked for me, but in order for Webpack to recognize it as a file instead of a module I had to prefix the string with "./", i.e.

```
// webpack.config.js
  plugins: [
    new webpack.DefinePlugin({
      VERSION: JSON.stringify(require("./package.json").version)
    })
  ]
```

**Comment by andreialecu** [comment]
Any ideas on how to make it detect changes to package.json when webpack is in watch mode? 

Currently I have to restart webpack every time I bump the version.

**Comment by Llorx** [comment]
Also interested in @andreialecu question.

**Comment by ArturBaybulatov** [comment]
@andreialecu I've asked the same question in #3530

**Comment by shura-sparrow** [comment]
@ArturBaybulatov hey, if you're interested in the point yet, I had the same situation and tried to fix it. The thing was that I had 2 webpack processes in 2 console tabs, so changes didn't work. After I killed one of the processes everything worked properly.

**Comment by ArturBaybulatov** [comment]
@shura-sparrow Hey, thanks! But i've got only one webpack process, so looks like problems are different. I've updated my issue if you'd like to take a look

**Comment by QuantumInformation** [comment]
I tried this without a JSON loader, but it didn't like it:

![image](https://cloud.githubusercontent.com/assets/216566/25009189/c6d851ee-205d-11e7-96d2-784df65ecde2.png)

I thought it would work cause of https://github.com/webpack/webpack/issues/3363

**Comment by Juanelorganelo** [comment]
I tried this

```js
compiler.plugin('compilation', (compilation, { normalModuleFactory }) => {
      const package = require('../package.json')
      compiler.apply(new DefinePlugin({ [this.name]: JSON.stringify(package.version) }))
    })

    compiler.plugin('emit', (compilation, callback) => {
      Array.prototype.push.apply(compilation.fileDependencies, files)
      callback()
    })
```
but it didnt worked

**Comment by Juanelorganelo** [comment]
Any ideas??

**Comment by dhrumil4u360** [comment]
For detecting "package.json" as file and resolving path properly, this worked fine for me...

 ```
     new webpack.DefinePlugin({
        VERSION: JSON.stringify(require(helpers.root('package.json')).version)
      }),
```

**Comment by chyzwar** [comment]
You can also use this:

```js
    new webpack.DefinePlugin({
      version: JSON.stringify(process.env.npm_package_version),
    }),
```

**Comment by Domvel** [comment]
Is there a way to inject the version with a typescript project (ts-loader). This solution (DefinePlugin) does not work.

**Comment by icodeforlove** [comment]
@chyzwar your approach makes the most sense as it will actually work when directly running with `npm`, and after running a packed script.

But for node only usage it makes a little more sense to keep the ENV name the same

```
new webpack.DefinePlugin({
	'process.env.npm_package_version': JSON.stringify(process.env.npm_package_version)
})
```

This way you don't have to toggle accessors.

**Comment by Mrcooder** [comment]
> You can use the [DefinePlugin](http://webpack.github.io/docs/list-of-plugins.html#defineplugin) to inject this information into the bundle:
> 
> ```js
> // webpack.config.js
>   plugins: [
>     new webpack.DefinePlugin({
>       VERSION: JSON.stringify(require("package.json").version)
>     })
>   ]
> ```
> 
> ```js
> // any-module.js
> console.log("Version: " + VERSION);
> ```

I got undefined VERSION :(

**Comment by jakeNiemiec** [comment]
@Mrcooder Can you post your `package.json` file?

**Comment by m-pd** [comment]
@Mrcooder Try this:

```
declare let VERSION;
console.log("Version: " + VERSION);
```

**Comment by Tofandel** [comment]
It's `process.env.VERSION` to access it, you should also have `process.env.npm_package_version` available without needing DefinePlugin

**Comment by benjamin-stern** [comment]
@Domvel as @m-pd said, full article for embedding with TypeScript: https://blog.johnnyreilly.com/2016/07/23/using-webpacks-defineplugin-with-typescript
