### ISSUE TITLE
Why isn't json-loader enabled by default?

### ISSUE THREAD

**Issue by mik01aj** [webpack/webpack#2370]
I'm coming from https://github.com/fb55/entities/pull/26. It's a commonly used tiny library, and the fact that it uses JSON files internally (which is fine with both Node and Browserify) requires anyone using libraries that use libraries that depend on `entities` add the `json` loader explicitly to their webpack config. I wonder why JSON files aren't handled correctly by default.

@sokra , could you please explain this design decision? Would you accept a PR changing this?

**Comment by Someguy123** [comment]
I can confirm this is annoying. I believe BitcoinJS also uses JSON files, which is why I had to enable it in my project (even though other things such as Browserify seem to support it by default)

**Comment by mik01aj** [comment]
@webpack, @sokra any feedback?

**Comment by taurose** [comment]
https://github.com/webpack/webpack/issues/184#issuecomment-36607967

**Comment by kentcdodds** [comment]
Seems to me like the reasons @sokra listed in #184 are legit and wont change so this should probably be closed.

**Comment by mik01aj** [comment]
seems so, yes.
