### ISSUE TITLE
Debugging a segmentation fault

### ISSUE THREAD

**Issue by robcalcroft** [webpack/webpack#2371]
Getting a seg fault when running my webpack:
`69% 352/354 build modulesSegmentation fault: 11`
I understand this is unlikely an issue with webpack itself but I'm not sure the best way to go about debugging this issue. I've tried some other versions of node and node-sass, which I've seen looks like the culprit for some others with this issue, but still getting this error. It has recently arisen as a cached version I have been working on works fine, just a fresh install that I'm seeing this.

**Comment by robcalcroft** [comment]
###Deps

```
{
  "devDependencies": {
    "babel-cli": "^6.6.5",
    "babel-eslint": "^6.0.0",
    "babel-loader": "^6.2.4",
    "babel-preset-es2015": "^6.6.0",
    "babel-preset-react": "^6.5.0",
    "babel-preset-stage-0": "^6.5.0",
    "css-loader": "^0.23.1",
    "eslint": "^2.5.3",
    "exports-loader": "^0.6.3",
    "file-loader": "^0.8.5",
    "html-webpack-plugin": "^2.15.0",
    "image-webpack-loader": "^1.6.3",
    "imports-loader": "^0.6.5",
    "node-sass": "^3.4.2",
    "sass-loader": "^3.2.0",
    "style-loader": "^0.13.1",
    "url-loader": "^0.5.7",
    "webpack": "^1.12.14",
    "webpack-dev-server": "^1.14.1"
  },
  "dependencies": {
    "dotenv": "^2.0.0",
    "express": "^4.13.4",
    "jquery": "^2.2.2",
    "json-loader": "^0.5.4",
    "localforage": "^1.4.0",
    "materialize-css": "^0.97.6",
    "moment": "^2.12.0",
    "morgan": "^1.7.0",
    "react": "^0.14.8",
    "react-dom": "^0.14.8",
    "react-router": "^2.0.1",
    "request": "^2.69.0",
    "sweetalert": "^1.1.3"
  }
}
```

**Comment by bebraw** [comment]
>  It has recently arisen as a cached version I have been working on works fine, just a fresh install that I'm seeing this.

You could try locking the version of `sass-loader` to the cached version and then bumping version a step at a time to see when it starts crashing. That will give us the offending version. Hopefully the resulting diff between a working and not working version helps.

**Comment by robcalcroft** [comment]
Yeh i've just fixed it by using 3.4.2 over 3.5.2 gonna close this as its a node-sass issue thanks :)

**Comment by bebraw** [comment]
@robcalcroft Ok, make sure the issue has been reported upstream. 👍

**Comment by robcalcroft** [comment]
@bebraw have done!
