### ISSUE TITLE
CommonsChunkPlugin is inadequate for defining a vendor chunk If cherry picking

### ISSUE THREAD

**Issue by jimbolla** [webpack/webpack#2372]
Given this webpack config:

```
{
    entry: {
        "vendor.js": [ "lodash", /* etc... */ ]
    },
    plugins: [
        new webpack.optimize.CommonsChunkPlugin({ name: "vendor.js", minChunks: Infinity }),
    ],
}
```

with js code like:
```
import flow from 'lodash/fp/flow';
import fromPairs from 'lodash/fp/fromPairs';
import groupBy from 'lodash/fp/groupBy';
```
The problem is that the entire `lodash` still gets put into vendor.js because that's its entry. I think the problem is that CommonsChunkPlugin depends on an entry. What I'd like to be able to do is define its inclusion criteria more like a loader. Something like:
```
new webpack.optimize.CommonsChunkPlugin({ test: /node_modules/, filename: "vendor.js" }),
```
Reading through the webpack docs, I haven't been able to find any want to achieve something like this.

**Comment by bebraw** [comment]
As a workaround you could define an entry that aggregates all those lodash imports you want. In this case you would literally have a file like this:

**src/lodash_entry.js**

```javascript
import flow from 'lodash/fp/flow';
import fromPairs from 'lodash/fp/fromPairs';
import groupBy from 'lodash/fp/groupBy';
```

You would then have

```javascript
"vendor.js": [ "./src/lodash_entry", /* etc... */ ]
```

I know it's a little painful as now you have an additional file to maintain. But that's at least one way out.

**Comment by sokra** [comment]
You can specify a inclusion criteria on the CommonsChunkPlugin. With the `minChunks` option. Just provide a callback function, which decides which module should be in the CommonsChunk.

**Comment by jimbolla** [comment]
Do I still have to define the entry then? If not, then that sounds exactly like what I want.

**Comment by jimbolla** [comment]
Testing it now... it does appear to work. I was able to completely remove the entry for vendor and define the plugin as:
```
 plugins: [
        new webpack.optimize.CommonsChunkPlugin({
          name: "vendor.js",
          minChunks: module => /node_modules/.test(module.resource)
        })
    ]
```

Thank you for your help, @sokra and@bebraw

**Comment by jgoux** [comment]
Thanks @sokra for the minChunks tip !

**Comment by mike3run** [comment]
@jgoux thanks for that tip, its a shame the first syntax doesn't work to shake the tree

**Comment by mike3run** [comment]
@jgoux I have found why is that, when defining the babel loader the usual line we copy without thinking is:

`exclude: /node_modules/`

So we are basically saying, hey webpack, dont analyze or parse anything inside node modules.

Removing that line sure enough makes

`import { add } from "ramda"` 

work properly with tree shaking, but make the build time a bit larger and I even noted that it might still produce slightly larger bundles than using:

`import add from "ramda/src/add"`

Here's a comparison:

Not excluding node_modules but using proper tree shaking syntax:

![screen shot 2017-10-04 at 4 08 10 pm](https://user-images.githubusercontent.com/7088511/31199897-7c764d82-a91e-11e7-9a07-763b0043e374.png)

Excluding node_modules but importing directly the module file we want to force the shake:
![screen shot 2017-10-04 at 4 08 15 pm](https://user-images.githubusercontent.com/7088511/31199956-aaec7420-a91e-11e7-99ea-f887dae7e16c.png)


Slight differences but then again my app is still really small anyways.

Food for thought.

**Comment by earslap** [comment]
Something I don't understand about the minChunks method @sokra posted above:

It works, I want all code referenced from my code that sits in node_modules in a vendor chunk. But I want the tree shaked versions and not referencing them as entries helps with that.

What I don't understand is that, inside the minChunks method, there is some **loader code** that gets passed in and ends up in the bundle. This is unintuitive to me. If I console.log module.resource, I get things like:

```
node_modules/style-loader/lib/addStyles.js
node_modules/style-loader/lib/urls.js
node_modules/css-loader/lib/css-base.js
```

They match the /node_modules/ test and actually end up in the bundle. Why are those files processed to begin with? If I reject them, they don't end up in the bundle (which is what I want) and my app works the same (css-loader, style-loader does their jobs.) So they just bloat the bundle?

I mean I can filter them out but I don't understand why loader code gets processed in my build to begin with, I don't reference them anywhere.

**Comment by bebraw** [comment]
@earslap Did you set `allChunks: true` at extract-text-webpack-plugin?

**Comment by earslap** [comment]
Thank you @bebraw that I was missing and enabling allChunks fixed the issue.

**Comment by mrchief** [comment]
> @jgoux I have found why is that, when defining the babel loader the usual line we copy without thinking is:

@mike3run Totally disagree! We always "copy" it "with" the thinking - _its on the internet, must be correct!_ 😉
