### ISSUE TITLE
Improve DllPlugin to respect aliasing

### ISSUE THREAD

**Issue by lostthetrail** [webpack/webpack#2374]
If you add aliases into your DllPlugin, it will only write out the raw file path. This causes issues when you have to dual maint. aliases. Also when you are trying to abstract out logic, such as locale-specific bundles.

@sokra Is there a likelihood that this feature is possible and would be accepted if I put in a PR?

Example:

**DllPlugin**

*vendor.js*
```
require('underscore');
```

*vendor.config.js*
```
{
    entry: {
        locale: [path.resolve('./vendor.js')]
    },
    output: {
        path: path.resolve('./build/'),
        filename: '[name].bundle.js',
        library: '[name]'
    },
    plugins: [
        new webpack.DllPlugin({
            name: '[name]',
            path: 'build/vendor-manifest.json'
        })
    ],
    resolve: {
        extensions: ['', '.js'],
        alias: {
            'underscore': path.join('bower_components', 'lodash', 'dist', 'lodash.js')
        }
    }
}
```

*vendor-manifest.json*
```
{
  "name": "vendor",
  "content": {
    "./bower_components/lodash/lodash.js": 1,
    "./vendor.js": 2
  }
}
```

**Comment by lostthetrail** [comment]
Let me know if you need to see the other side of the DllPlugin use.

**Comment by sokra** [comment]
You need to use the same resolve configuration on the other side. Just put it into a shared file or `require("./dll.config.js").resolve`.

**Comment by lostthetrail** [comment]
Drat. Sounds like this won't be the solution I was looking for.

I have an application with a bunch of locale-specific files I am trying to bundle by themselves.

I have probably 50 non-locale specific files, which will be the same for all locales. Then I have about 8 locale specific files, which I wanted to bundle together.

The output would end up looking something like this.

- app.bundle.js
- vendor.js
- app.locale-en_US.js
- app.locale-es_ES.js
- app.locale-de_DE.js


The app.js entry point has references to modules needing these locale-specific modules. Currently the modules are aliased to a generic name from locale specific webpack configs:
```
var locale = 'es';
'moment-locale': 'moment/locale/'+locale+'.js',
'news-messages': 'news/release/javascript/'+locale+'.js'
```

app.js
```
require('moment-locale');
require('news');
```

news.js
```
var messages = require('news-messages');
console.log(messages.hello); // Hola or Hello
```

The reason I outlined the above is that if I have to keep duplicate aliases, it means that my top level non-locale specific code will need to be locale specific at the build level.

Am I explaining this clearly? Do you see a cleaner way to handle this?

**Comment by sokra** [comment]
I thought you want to do this:

* vendor.js (locale independend)
* app.en_US.js
* app.es_ES.js
* app.de_DE.js

Where `vendor.js` is build using the DllPlugin, and `app.xxx.js` is build with multiple compilations and the DllReferencePlugin.

``` js
// app.config.js
var locales = ["en_US", "es_ES", "de_DE"];
module.exports = locales.map(locale => {
  return {
    resolve: {
      'moment-locale': 'moment/locale/'+locale+'.js',
      'news-messages': 'news/release/javascript/'+locale+'.js'
    },
    plugins: [
      // DllReference 
    ]
  }
});
```

**Comment by lostthetrail** [comment]
Ah, yes, I was able to achieve that. But it didn't solve three things for me:
1. Gulp/Webpack having a out of memory issue.
2. Improve build time.
3. Keep code segmented for longer term caching. Locale specific files are more likely to change regularly due to copywriter updates. 

I was able to resolve the memory failure temporarily by turning off Uglify sourcemaps, but my build time was still upward of 6 minutes. So I was trying to format my output the way I wanted it, hoping that these improvements would ultimately help the build time also.

**Comment by lostthetrail** [comment]
The only thought I have on how to solve this is pull the locale specific stuff into it's own webpack build which generates a global export. Then make an external entry in my application webpack build.

Thanks again for your help. Sorta hijacked this issue. :\

**Comment by lostthetrail** [comment]
Ah, I think some clarity just dawned on me.

To be able to have locale specific javascript in your bundles you have to do one of three things:
1. Create many locale-specific bundles. (app-en_US, app-es_ES, app-de_DE) [each 30kb]
2. Create one bundle containing all locales (app.js) [60kb]
3. Create a mechanism for loading locale-specific chunks into your generic bundle.
  - E.g. Locale bundle with export to var LTT.i18n; and app bundle with externals. Then on the page include both bundles explicitly, allowing the page to determine which locale bundle to request.

I have ruled out:
- Item 1 because it reduces code sharing and increases build time.
- Item 2 because it create overhead for our end users.

Which leaves item 3 as the only solution. The real question is what is the best mechanism for this. I have been unable to think of a way to make the locale specific dependencies available to the app dependencies without exposing them as a global variable.

Thoughts?

**Comment by lostthetrail** [comment]
The out of memory issue can be duct taped around using:
`--max-old-space-size=4096` in conjunction with node calling gulp.

REF: https://github.com/angular/angular/issues/5229

**Comment by lostthetrail** [comment]
This is no longer an open issue. But a useful conversation if you still have time.

**Comment by andrebautista** [comment]
Hi @lostthetrail, glad I ran into this thread before spending another day trying to get everything working! I'm currently trying to accomplish a similar task with no success. Did you figure out a way to accomplish  _"3. Create a mechanism for loading locale-specific chunks into your generic bundle."_?
