### ISSUE TITLE
NORMALMODULEFACTORY after-resolve(data) paths

### ISSUE THREAD

**Issue by NekR** [webpack/webpack#2377]
By some reason paths in this event some times are absolute and some times are not. What is the point here?

**Comment by NekR** [comment]
@bebraw it isn't question, it's more like a bug which cases bugs in plugins. Question is rhetorical here.

**Comment by MoOx** [comment]
Having similar issue, which cause unexpected behavior for some loaders in a particular context. Any pointers so we can make the situation better?

**Comment by bebraw** [comment]
Can you see this in webpack 2?

**Comment by NekR** [comment]
I'll try to check in it.

**Comment by NekR** [comment]
Activity.

**Comment by evilebottnawi** [comment]
@NekR problem still exists?

**Comment by NekR** [comment]
I'm not sure, I'll check with webpack 4.
