### ISSUE TITLE
CommonsChunkPlugin with hashing fix results with wrong bundle order in html file

### ISSUE THREAD

**Issue by mostr** [webpack/webpack#2378]
I'm trying to use CommonChunkPlugin with one "extra" chunk containing only webpack runtime to get proper hashing (this doesn't change vendor hash when only app files have changed). The trick is described  [here](https://github.com/webpack/webpack/tree/master/examples/chunkhash). 

This itself works fine, chunk hashes are correct, but the issue is that my HTML file generated has bundles in wrong order: **manifest, app and then vendor***, whereas it should be **manifest, vendor, app**.

CommonsChunkPlugin is configured as follows:

```
    new webpack.optimize.CommonsChunkPlugin({
      names: ['vendor', 'manifest']
    }),
```

and entries are as follows: 

```
    entry: {
      app: './index.js',
      vendor: ['foo', 'bar', 'baz']
    }
```

Currently it results with broken application as vendor libs should be available when app code gets evaluated. Is this "workaround" for consistent hashing broken, or do I need to configure something more to get it right? Thanks!

**Comment by sokra** [comment]
webpack doesn't generate the HTML. Do you use a plugin to generate the HTML page?

**Comment by mostr** [comment]
Yep, I use html-webpack-plugin. You're right this may be this plugin's issue although it works fine without this extra bundle. Will investigate this plugin a bit more. Thanks

**Comment by mostr** [comment]
Ok, got it. Looks like providing `chunksSortMode: 'dependency'` to `html-webpack-plugin` config solves this issue. So definitely not a webpack issue itself :) Thanks @sokra for hint on this.

One more question before I close this one (trying to investigate why default sorting breaks in html plugin): below is sample `console.log` from webpack chunks sorter gets:
```
[ { id: 0,
    rendered: true,
    initial: true,
    entry: true,
    extraAsync: false,
    size: 0,
    names: [ 'manifest' ],
    files:
     [ 'manifest.382c79c84a9f509c2b3b.js',
       'manifest.382c79c84a9f509c2b3b.js.map' ],
    hash: '382c79c84a9f509c2b3b',
    parents: [],
    origins: [] },
  { id: 1,
    rendered: true,
    initial: true,
    entry: false,
    extraAsync: false,
    size: 1383973,
    names: [ 'vendor' ],
    files:
     [ 'vendor.2a5db050d170e9f39b28.js',
       'vendor.2a5db050d170e9f39b28.js.map' ],
    hash: '2a5db050d170e9f39b28',
    parents: [ 0 ],
    origins: [ [Object] ] },
  { id: 2,
    rendered: true,
    initial: true,
    entry: false,
    extraAsync: false,
    size: 239343,
    names: [ 'app' ],
    files:
     [ 'app.816177d24b3793f201bd.js',
       'app.816177d24b3793f201bd.js.map' ],
    hash: '816177d24b3793f201bd',
    parents: [ 1 ],
    origins: [ [Object] ] } ]
```

What does `entry` property (boolean) mean here, in each chunk? I'm a bit confused because both (app and vendor) are defined as entries in webpack config, whereas manifest is not (but is marked here as "entry").
