### ISSUE TITLE
Compile sourcemaps for specified bundles.

### ISSUE THREAD

**Issue by dempfi** [webpack/webpack#2379]
I'm trying to reduce source maps compilation time and tried to use `webpack.SourceMapDevToolPlugin` with include and exclude options without specifying `devTool` option at all.
I'm configuring plugin like this
```js
new webpack.SourceMapDevToolPlugin({
  test: /.js$/,
  filename: '[file].map',
  append: false,
  include: options.sourceMap.map((v) => new RegExp(`^${v}-`))
  // exclude: options.sourceMap.map((v) => new RegExp(`^(?!${v}-)`))
})
```

`options.sourceMap` is the simple array of bundle names for what I need source maps to be compiled. It works correctly, with the filename as `[name]-[chunkhash].js` and produces source maps only for bundles from that array. But it took same amount of time as with `devtool: 'source-map'`. Seems like it compiles source maps for all the bundles and just save them to file for only specified.

I've tried to dig into that process and it seems that loaders are producing source maps that webpack later processing somehow. I'm using `coffee-loader` mainly( the project is written in coffee) and in coffee-loader I see that it [always compiles sourcemaps](https://github.com/webpack/coffee-loader/blob/master/index.js#L19). I just completely lost at this point. And will appreciate any help.

In general, I just need to compile source maps for some bundles.

**Comment by sokra** [comment]
While compiling the modules it's not yet defined in which files they are emitted. webpack need to compile SourceMaps for all modules. But the SourceMaps are not used when concatenating the file (which saves a bit).

**Comment by dempfi** [comment]
I found the issue, sass loader was the bottleneck. Didn't investigate exact reason in that loader but with turned off sourcemaps in that loader everything works fine.
