### ISSUE TITLE
Can we upgrade the project to the latest version of node?

### ISSUE THREAD

**Issue by zwhitchcox** [webpack/webpack#2381]
It would be nice to use arrow functions, const, let, etc.. I see a lot of big projects sticking to ES5 though, like React, while some are converting to ES6+. Is there anyway we could upgrade to Node v.5.5.0? And if not, may I ask the reasoning behind that?

**Comment by Someguy123** [comment]
I'd say that's a terrible idea. The current LTS is Node 4.4.3 - and that needs to be supported, because that's what most people will be using in production.

Things like React get around it thanks to Webpack+BabelJS, so that you can use either ES5 or ES6.

**Comment by zwhitchcox** [comment]
Could we use babel on this?

**Comment by iotch** [comment]
@zwhitchcox there is a `babel-loader`:

````js
    loaders: [
        {
            test: /\.jsx?$/,
            exclude: /(node_modules|bower_components)/,
            loader: 'babel-loader',
            query: {
                presets: ['es2015-webpack', 'react'],
            }
        }
    ]
````

**Comment by bebraw** [comment]
Probably not going to happen as someone still needs to do all that work of porting over and transpiling.
