### ISSUE TITLE
Dynamic import of small chunks with System.import

### ISSUE THREAD

**Issue by whitecolor** [webpack/webpack#2382]
As I see actually System.import doesn't work as kind of dynamic one. Say I have I directory:

```
./templates/
   templateA.js
   templateB.js
   templateC.js
    ...
main.js
```
I want to have a function that dynamically imports any of this template files by name:

so in `main.js` I have a function :
```js
function loadTemplate(templateNmae) {
  var templatePath = './templates/' + templateName
  return System.import(templatePath)
}
```
But I doesn't work webpack says: `can not resolve ./templates/templateA`

If to do this way:

```js
function loadTemplate(templateNmae) {
  return System.import('./templates/' + templateName)
}
```
Webpack just break with an error:
>
ERROR in chunk main [entry]
build.js
**Cannot read property 'length' of null**
webpack: bundle is now VALID.

But I think I just don't understand how `System.import` supposed to work in webpack and I wonder if what I want is achievable currently.

**Comment by sikanhe** [comment]
I don't know if i am right, but I think webpack does *static* analysis, so it does not know how to resolve the functions before returning import paths.

**Comment by whitecolor** [comment]
Ok I got now, that webpack is about static bundles.

**Comment by iotch** [comment]
This doc may help: https://webpack.github.io/docs/context.html

**Comment by whitecolor** [comment]
@iotch 
Yes right thanks I implement it via requiring the whole dir.
