### ISSUE TITLE
How to determine whether the component is loaded about ‘require.ensure’ ?

### ISSUE THREAD

**Issue by GitHubXur** [webpack/webpack#2386]
**Code splitting** will `only request a code`, if it fails, will not `request again`. 
Load failed to make it manually request the failed component files again?
how to know whether the component files loaded success or failure?

```
require.ensure(['a'], function(require){
   
})
```

Please help me

**Comment by bebraw** [comment]
Webpack 2 will provide `System.import('a').then(...).catch(...)` kind of structure. I think with webpack 1 you need to catch possible exception yourself. So wrap it in a `try-catch` and see how that goes.

**Comment by GitHubXur** [comment]
Load failed, how to manually load again, code splitting loads only once

**Comment by sokra** [comment]
You cannot catch it in webpack 1.
