### ISSUE TITLE
Uncaught TypeError: Cannot read property 'hot' of undefined

### ISSUE THREAD

**Issue by colinmeinke** [webpack/webpack#2387]
I have hot loading [setup and partially working](https://github.com/colinmeinke/universal-js/tree/hot-loader) with [React Hot Loader 3](https://github.com/gaearon/react-hot-boilerplate/pull/61).

Reloading components works fine. However, whenever I reload a Redux reducer or action I am receiving the following error:

```
Uncaught TypeError: Cannot read property 'hot' of undefined

  getAffectedStuff @ client.js:351
  hotApply @ client.js:386
  (anonymous function) @ only-dev-server.js:32
  hotUpdateDownloaded @ client.js:312
  hotAddUpdateChunk @ client.js:284
  webpackHotUpdateCallback @ client.js:5
  (anonymous function) @ 0.4221176….hot-update.js:1
```

[Relevant parts of code here](https://github.com/colinmeinke/universal-js/blob/hot-loader/src/client.js#L12L29):

``` js
configureStore({ url }).then( store => {
  render(
    <AppContainer component={ Root } props={{ store }} />,
    document.querySelector( '.app' )
  );

  if ( __DEVELOPMENT__ && module.hot ) {
    module.hot.accept([ './common/components/Root', './common/store/configureStore' ], () => {
      render(
        <AppContainer
          component={ require( './common/components/Root' ).default }
          props={{ store }}
        />,
        document.querySelector( '.app' )
      );
    });
  }
}).catch( console.error.bind( console ));
```

[And here](https://github.com/colinmeinke/universal-js/blob/hot-loader/src/common/store/configureStore.js#L18L22):

``` js
if ( __DEVELOPMENT__ && module.hot ) {
  module.hot.accept( '../reducers', () => {
    store.replaceReducer( require( '../reducers' ).default );
  });
}
```

**Comment by colinmeinke** [comment]
This is the line where Webpack crashes:

![](https://www.dropbox.com/s/a885fex1oezrnaj/Screen%20Shot%202016-04-25%20at%2018.21.00.png?raw=1)

**Comment by gaearon** [comment]
Have you had a change to give Webpack 2 a try? It might be fixed there, but I haven’t checked.

**Comment by colinmeinke** [comment]
I'll try and see if I can work out how to upgrade now

**Comment by colinmeinke** [comment]
It builds fine with Webpack 2 without any change in config.

HRM isn't working with it at all though. It claims to be, and doesn't error, but I'm getting no actual changes. I think I'll wait on Webpack 2 until there's some more documentation around it.

![](https://www.dropbox.com/s/l7jkoq0m8vi8t4i/Screen%20Shot%202016-04-27%20at%2020.59.33.png?raw=1)

**Comment by Download** [comment]
Just wanted to chime in that I have been observing this same issue for about a year now. Webpack 1. I have yet to discover a pattern. The bad thing is that after this has occurred, HMR seems no longer functional so we have to restart the app.

It would be great if there at least would be a guard added so that HMR doesn't crash.

**Comment by Kovensky** [comment]
This might have been fixed since there were a few hot reloading changes around June or so.

**Comment by Download** [comment]
Could we maybe add some diagnostics code? Because upgrading to Webpack 2 is a big time investment and at the moment still very risky.

I understand that it will be very difficult to fix from the current info, but the message clearly indicates that the HMR runtime is in a state it should never be in. The `module.parents` array apparently contains an ID of a module that is no longer found in `installedModules`. Might this happen when we remove an `import` / `require` statement? 

Maybe we can just test whether `parent` is `undefined` and if it is, log some debug info (so next time someone encounters it they'll have more info for us) and `continue` to the next loop iteration. That seems like a safe change to make that may help alleviate and finally fix this issue.

**Comment by nevir** [comment]
I'm seeing this issue on webpack 2, as well

**Comment by cescoferraro** [comment]
I think I can replicate this. Consider the same case @colinmeinke  where hot reloading the app works but fails to replaceReducer properly.

Assuming
```
let ReplacebleEpicMiddleware = createEpicMiddleware(RootEpic);

export const store = () => {
    const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose;
    let store = FirebaseStoreCreator(allReducers, {},
        composeEnhancers(
            applyMiddleware(ReplacebleEpicMiddleware)
        ));

    if (module.hot) {
        module.hot.accept(['./reducers.tsx', "./epics.tsx"], () => {
            const nextRootEpic = require('./epics.tsx').RootEpic;
            const nextRootReducer = require('./reducers.tsx').allReducers;
            store.replaceReducer(nextRootReducer);
            ReplacebleEpicMiddleware.replaceEpic(nextRootEpic);
        });
    }


    return store
};
```

Where `reducers.tsx` and `epics.tsx` should only contain a single reducer/epic like so, and is not HMRealoadable. And the "property 'hot' of undefined" error shows up here , if you happen to put the actual reducers/epics you are trying to hot-reload in any of those files respectively. My solution was to simply create an app folder and place my reducers in there. Maybe there is a better way to handle this IDK. 

```
import {pingEpic} from "./app/app.epic";
export const RootEpic = combineEpics(
    pingEpic,
    ....
);

import {reducer} from "./app/reducers";
export const allReducers = combineReducers({
    firebase: firebaseStateReducer,
    app: reducer,
    ...
});
```

uterReducer({ isUpdating, name });
```

**Comment by zackify** [comment]
I'm getting this running the webpack dev server using the nodejs api. weird

**Comment by wmertens** [comment]
I am encountering the same sporadically when hot reloading my server.

I think this may be the culprit: https://github.com/webpack/webpack/blob/028c51301733836abbedc88be7483af2623f5943/lib/HotModuleReplacement.runtime.js#L502

in all the other places `module` is guarded against being undefined but here apparently not?

**Comment by Kamilius** [comment]
Having exactly same issue, which kills my SCSS hot module replacement. Happens each time I'm trying to apply new SCSS changes.

**Comment by KhoaSydney** [comment]
I am using webpack 3 and still having the same error when running webpack dev server. Any update on this?

cheers,
Khoa

**Comment by guoerwei** [comment]
```
manifest.js:590 Uncaught TypeError: Cannot read property 'hot' of undefined
    at hotApply (manifest.js:590)
    at hotUpdateDownloaded (manifest.js:314)
    at hotAddUpdateChunk (manifest.js:294)
    at webpackHotUpdateCallback (manifest.js:37)
    at 0.a0cbf6c….hot-update.js:1
```

I‘m using webpack3 + vue-loader through webpack nodejs api.

when I modify the `template` tag in the `.vue` file, hmr worked fine.
moduleId `./App.vue` was in the installedModules array

but if I modify the code in the `script` tag, the error above was thrown,
and moduleId `./App.vue` was gone.

In my `dev.config.js` file, I added `hmr: ['webpack/hot/dev-server', 'webpack-dev-server/client?http://localhost:8080']` into the entry field, and `new webpack.HotModuleReplacementPlugin()` into the plugins array, also, `hot: true` was in the `webpackDevServer`'s second arguments as well

I tried CLI to run webpack-dev-server with `--hot --inline`, both `template` tag and `script` tag work fine.

**Comment by Download** [comment]
> Spiked (fixed) issue by wrapping // call accept handlers code (L497 - L532) into try/catch block in file ./node_modules/webpack/lib/HotModuleReplacement.runtime.js

@Kamilius You fixed it? Maybe try a PR? 

@sokra Would a PR for this make sense? What do you think? This issue has been in Webpack since v1. Maybe it can't hurt to try it?

**Comment by gabrielfin** [comment]
I've been having the same issue (version 2.6.1). I'm using Vue with vue-loader and it happens only on certain components when editing the contents of the script tag.
Don't know if this is a vue-loader or a general webpack issue.

The error comes from ``HotModuleReplacement.runtime.js`` line 500, because ``installedModules[moduleId]`` doesn't exist.

**Comment by wmertens** [comment]
I just experienced this in the browser, I added a breakdown of the situation at https://github.com/webpack/webpack/pull/5498#issuecomment-321741586

**Comment by Download** [comment]
Thanks @Kamilius and @sokra for getting this fixed! Great work!!

**Comment by wmertens** [comment]
I am happy to report that so far I have not experienced this problem any
more, Webpack is being super stable :-D
