### ISSUE TITLE
worker-loader causes webpack to run out of memory when dynamic requires are used

### ISSUE THREAD

**Issue by kujon** [webpack/webpack#2396]
The following works without issues:

``` javascript
// main.js
const MyWorker = require('worker!./my-worker');

// my-worker.js
const myModule = require('my-module');
self.onmessage = e => { /* do stuff */ };
```

However as soon as you start introducing dynamic requires, webpack compilation will enter an infinite loop and eventually run out of memory:

``` javascript
// main.js
const MyWorker = require('worker!./my-worker');

// my-worker.js
self.onmessage = e => {
    const myModule = require(e.data.modulePath);
    /* do stuff */
};
```

Am I missing sth obvious, or is it a legitimate bug?

**Comment by kujon** [comment]
Figured out what the issue was and it might be helpful to post the potential solution here:

1. `worker-loader` definitely slows things down and uses up more memory compared 'plain' webpack.
2. `require.context` generated for simple `require(myVar)` ends up being all possible modules. It's not an issue when not using the `worker-loader`, but becomes one as soon as your dynamic requires are in the worker file.
3. Specifying a custom and restrictive `require.context` solves the problem altogether.

**Comment by kuba-essentia** [comment]
One more correction in case that helps: it turns out not to be an infinite loop, just a very long one (compiling all entries in a massive default require context).

**Comment by kujon** [comment]
One more correction in case that helps: it turns out not to be an infinite loop, just a very long one (compiling all entries in a massive default require context).

**Comment by akinnee-gl** [comment]
+1 I am also experiencing this issue.

**Comment by akinnee-gl** [comment]
@kujon Can you give an example for what you set `require.context` to to fix the issue?

**Comment by kujon** [comment]
@akinnee-gl It depends on a specific use case. My problem was that I had a worker file which was dynamically loading a class with a certain interface. The decision which implementation to use was made by the UI thread and passed to the worker. So I ended up writing a regex which would match all the files which contained those implementations, so that webpack could generate the amount of worker bundles equal to the number of implementations, rather than equal to the number of files in my projects.

Check this out for more: https://webpack.github.io/docs/context.html#require-context

**Comment by roverso** [comment]
+1 Same issue here. Any developments?

**Comment by TJKoury** [comment]
Having this issue as well, and the amount of memory used seems to be really disproportionate to the bundle size being created.
