### ISSUE TITLE
The output path is wrong when I was using async loading

### ISSUE THREAD

**Issue by Lanfei** [webpack/webpack#2397]
I've used [async loading](https://github.com/petehunt/webpack-howto#9-async-loading) by this way:

```js
require.ensure([], () => {
	var SignComponent = require('../SignComponent');
}, 'sign');
```

And this is my `webpack.config.js`:

```js
module.exports = {
	output: {
		publicPath: '/',
		filename: 'js/[name].[chunkhash:6].js'
	}
	// ...
};
```

But finally I found the output file path is `1.js/sign.795b9b.js`, why?

**Comment by Lanfei** [comment]
Okay, I resolve this problem by updating my `webpack.config.js`:

```js
module.exports = {
	output: {
		publicPath: '/',
		filename: 'js/[name].[chunkhash:6].js',
		chunkFilename: 'js/[name].[chunkhash:6].js'
	}
	// ...
};
```

**Comment by kulelikule** [comment]
But I think there should be a better answer.
