### ISSUE TITLE
Performance problems

### ISSUE THREAD

**Issue by jhnns** [webpack/webpack#24]
I think there are some serious performance problems with webpack. Currently we're generating first bundles with alamid. The basic bundle (without application logic) contains about 50-60 modules. This is fine because we like modularity and prefer writing many short modules than a single long one.

Right now webpack takes about 2 secs (!) to compile the file. This is way too long. I don't know if you have any performance tests yet, but I think it is a good idea to spend some time on improving it. Maybe you can use [flame graphs](http://blog.nodejs.org/2012/04/25/profiling-node-js/) for it. 

We (at alamid) surely haven't done everything right and could reduce some file system calls. But I think the main problem lies in webpack.

One performance gain could be achieved by replacing all asynchronous file system tasks to synchronous ones. Since you're not bundling for every HTTP-request in production it's a good idea to make it synchronous.

**Comment by slyngbaek** [comment]
@sokra I'm trying to get the cache working without using watch mode. All of my loaders are cacheable.

Passing in an empty object in `options.cache` does not seems to actually cache. The `stats.toCache` and `stats.fromCache` flags are always `undefined`.

Is the CachePlugin supposed to be used in conjunction with this?

**Comment by jhnns** [comment]
Yes, I think so. A lot has changed since then.

[Reading from the source code](https://github.com/webpack/webpack/blob/1e37053f7ef9519ee22f4a9e61db4c5fdd2637e9/lib/CachePlugin.js) you could try this:

```javascript
// webpack.config.js
var CachePlugin = require("webpack/lib/CachePlugin")
var myCache = {};

module.exports = {
    ...
    plugins: [
        new CachePlugin(myCache);
    ]
};
```

However, it is still important that the node.js process keeps running. You need to keep a reference on the `myCache` object.

**Comment by slyngbaek** [comment]
It looks like all I need to provide in the config is an empty object in `options.cache`. The WebpackOptionsApply module seems to [create the cache plugin](https://github.com/webpack/webpack/blob/6173bb83bad2b07e8f9f965f19f1b777c652b2fb/lib/WebpackOptionsApply.js#L296) for us:
```javascript
	if(options.cache === undefined ? options.watch : options.cache) {
		var CachePlugin = require("./CachePlugin");
		compiler.apply(new CachePlugin(typeof options.cache === "object" ? options.cache : null));
	}
```

I tested both adding the CachePlugin instance to the list of plugins as well as just passing in an empty object (and both) but the `stats.toCache` and `stats.fromCache` are always `undefined`. Subsequent builds take the same duration even though the `cache` object gets populated.

On a side note, it looks like the Webpack module [exports](https://github.com/webpack/webpack/blob/master/lib/webpack.js#L74) the CachePlugin.

**Comment by slyngbaek** [comment]
It turns out I was using gulp-webpack which creates a new compiler instance every time thus ignoring whatever was put in the cache. Solved by simply using webpack and using the same compiler every run.

**Comment by trusktr** [comment]
A new compiler instance every time should be just fine according to the docs as long as you store the cache object somewhere where it remains alive between compiler instantiations.
