### ISSUE TITLE
Resolving remote or cdn urls?

### ISSUE THREAD

**Issue by shama** [webpack/webpack#240]
Is there an existing way to resolve a remote url? Such as:

``` js
require(['http://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js'], function(jquery) {
  $('body').html('It works!')
})
```

If not, I was going to attempt to write a plugin for it. Where it just bundles a call to asynchronously load the remote resource. Just wanted to check to make sure a solution doesn't already exist. Thanks!

**Comment by giovannipds** [comment]
@sokra is there a better approach nowadays (instead of `scriptjs`)?

**Comment by jlianphoto** [comment]
@giovannipds srciptjs is not support amd's require , god

**Comment by giovannipds** [comment]
@jlianphoto what? I don't know if I'm getting what you meant, how doesn't it, if it is working with commonjs' require? Why wouldn't it? Looking at the [repo](https://github.com/ded/script.js/), it seems there's a commit 6 years ago (on `Makefile`), commited as <q>- AMD support</q>... anyway...

Even though, my question was, if, is there a better approach nowadays, instead of `scriptjs`?

**Comment by light24bulbs** [comment]
Yes does anyone know if we have a more modern approach?  Maybe something in "externals" that is designed to tell the bundle to fetch the require from a URL..

**Comment by light24bulbs** [comment]
Oh, here we go: https://www.npmjs.com/package/webpack-require-http @giovannipds

**Comment by light24bulbs** [comment]
Okay, tried that lib and it isn't working for me, although it does LOOK perfect.  The creator has dropped off the face of github.  I think if that can be fixed and made to work with modern webpack, we are in business.

**Comment by giovannipds** [comment]
@light24bulbs thanks for letting us know. I guess it stays here to anyone interested in the same issue (I, personally, am not interested in this anymore).

Note: the [project on GitHub](https://github.com/darkty2009/webpack-require-http) looks normal, although I haven't tested it.

**Comment by webds** [comment]
> @jlianphoto what? I don't know if I'm getting what you meant, how doesn't it, if it is working with commonjs' require? Why wouldn't it? Looking at the [repo](https://github.com/ded/script.js/), it seems there's a commit 6 years ago (on `Makefile`), commited as - AMD support... anyway...
> 
> Even though, my question was, if, is there a better approach nowadays, instead of `scriptjs`?

This should interest you.
This is an updated library.
----
LoadJS is based on the excellent $script library by Dustin Diaz. We kept the behavior of the library the same but we re-wrote the code from scratch to add support for success/error callbacks and to optimize the library for modern browsers. LoadJS is 789 bytes (minified + gzipped).
----

https://github.com/muicss/loadjs

**Comment by ScriptedAlchemy** [comment]
@sviatoslav-lebediev does that work?

**Comment by sviatoslav-lebediev** [comment]
@ScriptedAlchemy It worked, I'm not sure about current behavior because I don't use webpack right now. You can read about `webpackIgnore` here https://webpack.js.org/api/module-methods/#magic-comments

**Comment by ScriptedAlchemy** [comment]
So wait wait wait, i can literally import(‘http://something/js/someChunk.js’).then();

What happens if what I’m importing happens to be yet another chunk from another webpack bundle? What’s in the then()?

Would something like this work on the end of the promise?! then(module => {module.default()})

Check this out: https://github.com/ScriptedAlchemy/webpack-external-import

I’m working to improve it, and looking for more webpack-native ways to do it. But basically, it lets me interleave dependencies between webpack builds. 

So i can import a code-split chunk from another webpack build and use it as if it were bundled with the original

**Comment by ScriptedAlchemy** [comment]
I wonder if this just literally uses the native ES6 import() which means no backward comparability with older browsers. @sviatoslav-lebediev i know you do not use webpack anymore, but did you happen to notice if this literally uses vanilla dynamic imports or does it still have some ES5-ish compatible script loading convention?

**Comment by sviatoslav-lebediev** [comment]
@ScriptedAlchemy you can load a remote library as a local module, here is an example, you can try to run it in dev tools console
```
import("https://cdn.rawgit.com/lodash/lodash/4.17.4-es/lodash.default.js")
.then(({default:_})=>{// load and use lodash 
 console.log(`lodash version ${_.VERSION} is loaded`)
 console.log('_.uniq([2, 1, 2]) :', _.uniq([2, 1, 2]));
});
```
>if this literally uses vanilla dynamic imports or does it still have some ES5-ish compatible script loading convention?

**it will use a vanilla dynamic import**
`webpackIgnore: true`  means that webpack will not add script code to your bundle but leaves it as is
import( /* webpackIgnore: true */ 'http://remote-resource') -- in your bundle you will find the same code

as for chunks, I can't say if you can use it but you definitely can use it for dynamically load additional bundles, I did it at my previous project.

> Would something like this work on the end of the promise?! then(module => {module.default()})

**yes if it's a module**

I would recommend to create a small project and play with it :) or take one from here https://webpack.js.org/starter-kits/

**Comment by ScriptedAlchemy** [comment]
Wow thanks for this. feel a little stupid that i didn't think about just ignoring it. 
I wonder if i could just craft an import polyfill for older browsers. 

`window.import = function`

**Comment by sviatoslav-lebediev** [comment]
@ScriptedAlchemy I would take a look at **nomodule** attribute
<script nomodule src="old_browser_import_polyfill.js"></script>

this can be useful as well https://github.com/systemjs/systemjs

**Comment by ScriptedAlchemy** [comment]
Have a pull request open which includes dimport, capable of poly filling the syntax.

I dont actually need the module exports because chunks are wrapped in a function anyways, so i use non_webpack_require after importing them in. 

https://github.com/ScriptedAlchemy/webpack-external-import/pull/34

**Comment by ScriptedAlchemy** [comment]
Here we go!! thank you @sviatoslav-lebediev - check out master branch for and youll see how i implemented your idea

Using `new Function` to get around webpack or babel from mutating `import()` when in a library, using `dimport` to polyfill dynamic imports, lastly using load.js for CORS imports or ooold school importing

**Comment by ScriptedAlchemy** [comment]
My pull request includes loading missing dependencies from fragment chunks.
