### ISSUE TITLE
Can't pass a variable to System.import 

### ISSUE THREAD

**Issue by mrdanimal** [webpack/webpack#2401]
When passing a plain string to `System.import`, it compiles to this:

```
 __webpack_require__.e/* System.import */(56).then(__webpack_require__.bind(null, /*! ./my/component */ 852)).then(function (module) {
   cb(null, module.default);
 }).catch(errorLoading);
```

But if I try to make a helper function and pass a variable to `System.import`, it compiles to this:
```
function loadComponent(componentPath, location, cb) {
  __webpack_require__(/*! . */ 1223)(componentPath).then(function (module) {
    cb(null, module.default);
  }).catch(errorLoading);
}
```

Then if I call `loadComponent` it cannot find the module. It seems that the path is resolved after compilation, so it can't be found?

Am I understanding how `System.import` should work? Thanks for your help.

**Comment by sokra** [comment]
webpack uses **static** analysis to determine which modules your requests point to. It can handle **some** dynamic expressions but only if the scope is limited.

* Works: `System.import("./dir/file")` (includes only the single file)
* Works: `System.import("./file" + expr)` (includes every file in the directory and subdirectories)
* Doesn't work: `System.import(expr)` (could be everything and is not resolvable on compile-time)

**Comment by mrdanimal** [comment]
Ah. Thanks for the explanation!

**Comment by jlberrocal** [comment]
According with @sokra explanation which is the right way to import a module using the value of a variable??? i'm facing a similar problem in this moment.

**Comment by web2style** [comment]
@jlberrocal Did you figure out how to do this? I need to do the same thing:

```
System.import(`containers/${module}`)
```
If I pass `HomePage` as `module` webpack throws the following error:
```
Dynamic page loading failed Error: Cannot find module './HomePage'.
```

For some reason it just ignores the string I prepend to the variable value.

**Comment by mrdanimal** [comment]
If I'm reading @sokra's explanation correctly, it's not possible.

**Comment by web2style** [comment]
But he said it works this way:
> Works: `System.import("./file" + expr)` (includes every file in the directory and subdirectories)

Or I'm misunderstanding something?

**Comment by jlberrocal** [comment]
as @mrdanimal say's is not possible i had to switch to SystemJS and left webpack behind

**Comment by web2style** [comment]
@jlberrocal  Yes, I thought about SystemJS either, but it seems weird for me to add extra 19kb of code to the app just to DRY the code.

**Comment by jlberrocal** [comment]
I had no alternatives, i had changed it, want it or not :-(

**Comment by mech** [comment]
What I usually do is have a folder called `splits` and inside define all the "root" components for any split point like:

```
/splits/DashboardForStaff.jsx
/splits/DashboardForEmployer.jsx
```

So when you do a dynamic import you can use:

```js
import(`./splits/${myDynamicSplitPoint}`)
```

The important thing is that your `DashboardForStaff` must be the root component to pull in all its child components elsewhere.

**Comment by dziamid** [comment]
@mech do you still do splits manually with latest webpack?

According to 
 [#dynamic-expressions](https://webpack.js.org/guides/migrating/#dynamic-expressions)

> It's possible to pass a partial expression to import(). 
> This is handled similar to expressions in CommonJS (webpack creates a context with all possible files).
> import() creates a separate chunk for each possible module.

**Comment by mech** [comment]
@dziamid I do still use a "split" folder. I just tried using without the `splits` folder and it generated much more files than I expected. From what I know I needed to give Webpack some help to set a boundary for where the "root" split points are or else Webpack will have a hard time knowing which is which.

**Comment by coconup** [comment]
just leaving this here.. it's obvious but it took me some time before realising that while this won't work:

```System.import(`containers/${module}`)```

this of course will:

```System.import(`containers/${module}/index`)```
