### ISSUE TITLE
Issue with debugging TypeScript in Chrome

### ISSUE THREAD

**Issue by galsch** [webpack/webpack#2404]
Hi all,

I'm running the following example demonstrating the most basic app written in Webpack + Angular2 + TypeScript (https://github.com/schempy/angular2-typescript-webpack). 

When I run webpack-dev-server and open Chrome to debug I can see the .ts files in Chrome when debugging:

<img width="868" alt="screen shot 2016-04-27 at 10 48 49 pm" src="https://cloud.githubusercontent.com/assets/16936673/14866068/668c8dac-0cca-11e6-8794-98a3d95ff227.png">

However, I decided to work on the project so I opened up my Webstorm and then suddenly I can no longer see the .ts files but instead I only see .js files.

It seems that Webstorm creates for each of the .ts file a .js file and .map file which cause a Chrome to only show the .js files and not the .ts files.
 
What's the problem here?

**Comment by sokra** [comment]
change

``` js
extensions: ['', '.js', '.ts']
```

to

``` js
extensions: ['', '.ts', '.js']
```

**Comment by galsch** [comment]
@sokra You rock.

Thanks!

**Comment by winnemucca** [comment]
@sokra @galsch I am using intellij which is close.  Which file did you do this in?
