### ISSUE TITLE
[Question] resolveLoader.root vs resolveLoader.fallback ?

### ISSUE THREAD

**Issue by nlarche** [webpack/webpack#2410]
What are differences between [resolveLoader.root] (https://webpack.github.io/docs/configuration.html#module-loaders)  and  [resolveLoader.fallback](https://webpack.github.io/docs/troubleshooting.html) 

When I link (npm link) a module on Linux both propetries are working 
But on windows only fallback is working

**Comment by sokra** [comment]
The only difference is the order: root is tried first, then modulesDirectories, then fallback. This is obsolute with webpack 2.

**Comment by sschaefer-rms** [comment]
How do I replace the configurations that are located in resolveLoader.root and resolveLoader.fallback in the new API?

**Comment by ColinCPhysna** [comment]
3 years later, I have the same question as @sschaefer-rms
