### ISSUE TITLE
preLoader watch mode behavior

### ISSUE THREAD

**Issue by pwang2** [webpack/webpack#2412]
Not sure this is in design or not.  when webpack work in watch mode, the preLoader only works for the changed file.  sometimes not that what we expect.  Here I save individule file 2 times and each time only the changed file itself get linted. 

./test-team-project/components/core/src/index.js
    line 11  col 2  Expected an assignment or function call and instead saw an expression.
    line 11  col 6  Missing semicolon.
    line 11  col 2  'adsf' is not defined.
./test-team-project/components/core/src/js/libs/mod1.js
    line 4  col 11  Expected an assignment or function call and instead saw an expression.
    line 4  col 15  Missing semicolon.
    line 4  col 5   'dsafa' is not defined.
**[13:08:36] webpack start build for core**
./test-team-project/components/core/src/js/libs/mod1.js
    line 4  col 11  Expected an assignment or function call and instead saw an expression.
    line 4  col 15  Missing semicolon.
    line 4  col 5   'dsafa' is not defined.
**[13:08:49] webpack start build for core**
./test-team-project/components/core/src/index.js
    line 11  col 2  Expected an assignment or function call and instead saw an expression.
    line 11  col 6  Missing semicolon.
    line 11  col 2  'adsf' is not defined.

**Comment by bebraw** [comment]
How should it work?

**Comment by pwang2** [comment]
Since it is a new bundle build, it makes more sense to lint all files for me.

**Comment by IanVS** [comment]
It would be nice to have the same behavior as the native ESLint cache.  Files with no errors are not re-linted unless they are changed, but all errors continue to be reported for all files until they are fixed.
