### ISSUE TITLE
Whats the difference b/w "loader" and "loaders" inside "loaders" object?

### ISSUE THREAD

**Issue by rajaraodv** [webpack/webpack#2415]
When I am using React-Hot-loader, I see syntax like "loaders" that takes an array of loaders like react-hot and babel. But for css, the loader is spelled "loader" and the value is a string where we pipe results of css-loader to style-loader. What's the difference? @sokra @gaearon 
``` 
module: {
    loaders: [{
        test: /\.jsx?$/,
        loaders: ['react-hot', 'babel'],
      },
      {
      test: /\.css$/,
      loader: 'style!css'
    }
    ]
  }
```

**Comment by sokra** [comment]
Since webpack 2 there is no difference.

In webpack 1, `loaders` takes an array, `loader` takes a string.

**Comment by rajaraodv** [comment]
Thanks a lot! The processing is still from right to left correct? In the above example, 'babel' and then 'react-hot'.

**Comment by sokra** [comment]
`loader = loaders.join("!")` is done internally.

**Comment by sokra** [comment]
loaders have two phases: the pitching phase and the normal phase.

for `style!css!./file.css` it is execute in this order:

* pitch style-loader
* pitch css-loader
* loader file.css
* normal css-loader
* normal style-loader

**Comment by rajaraodv** [comment]
Great! Thanks for the explanation!
