### ISSUE TITLE
Please review my blog: "Enabling Webpack’s HMR In React — The Missing Manual"

### ISSUE THREAD

**Issue by rajaraodv** [webpack/webpack#2418]
"Enabling Webpack’s HMR In React — The Missing Manual" https://medium.com/@rajaraodv/232336dc0d96

If you have suggestions or corrections, please select the text and Medium will show a tooltip w/ a lock symbol. If you click on that tooltip, it will allow you to add "private" comments and I'll get notifications.

I plan to post this Saturday afternoon. *You can make suggestion anytime even after it's posted and I'll update the blog * 😃

@sokra @gaearon 

Thanks,
Raja

**Comment by gaearon** [comment]
I would like to note that React Hot Loader 1 is deprecated, and version 3 is very different in the configuration. I’d appreciate if you documented version 3 instead. 

https://github.com/gaearon/react-hot-loader/pull/240
https://github.com/gaearon/react-hot-loader/pull/260

**Comment by rajaraodv** [comment]
Got it. It looks like there is so much going on! Not sure when it will be ready but when it is, I will deprecate the current blog and point to a new one. Thanks @gaearon

**Comment by gaearon** [comment]
It’s pretty stable at this point. The main reason I don’t release it as stable is because the docs are not ready 😉 . You can help with the docs: https://github.com/gaearon/react-hot-loader/pull/260.
