### ISSUE TITLE
Node 6 100% cpu

### ISSUE THREAD

**Issue by babeal** [webpack/webpack#2419]
Has anyone tried web pack with Node 6?  Any watch or extended execution like karma server causes the node process to take up an entire core.  It seems web pack related.

**Comment by MoOx** [comment]
Getting the exact same issue (I am using webpack 2, webpack-dev-server 2).
2 pass compilation is really slow too.

**Comment by MoOx** [comment]
Using node 5 make things way faster.

**Comment by askmatey** [comment]
keep me posted

**Comment by timothyallan** [comment]
I'm getting a constant 100% on one core with Node 6.2 and webpack-dev-server hot reloading.

**Comment by stevewillard** [comment]
@MoOx what version of Node 5? I'm having the same issue with 5.11.1 and 2.1.0-beta.7

**Comment by MoOx** [comment]
@stephan83 the same as you. Did you reinstall node_modules? (just in case)

**Comment by stevewillard** [comment]
Actually, I wiped away my node_modules and reinstalled everything and that seems to have helped. Webpack is not longing idling at 100%.

**Comment by bebraw** [comment]
Are you still seeing this? Did you reinstall the deps?

**Comment by fazalrasel** [comment]
Don't know why but it worked for me.
If you are using webpack-dev-server, remove `pull` from `watchOptions`
```
        watchOptions: {
          aggregateTimeout: 300,
          //pull: true, <--------
          ignored: /node_modules/
        },
```

**Comment by MoOx** [comment]
I recently switched to a new machine and I am facing this again: watch mode with dev server is working but consuming one core completely (my npm run process take 130% of my cpu).
Not sure what can cause this issue.

**Comment by MoOx** [comment]
Reinstalling node modules seems to fix the issue...

**Comment by bebraw** [comment]
@MoOx FYI, there's a [PR where we might move to sane over chokidar](https://github.com/webpack/watchpack/issues/36). I have a feeling that might help with this one.
