### ISSUE TITLE
hot module replacement simple example

### ISSUE THREAD

**Issue by timsuchanek** [webpack/webpack#242]
Hey, I'm trying to get [the wiki example for module replacement](https://github.com/webpack/docs/wiki/hot-module-replacement-with-webpack) working.
I created the files like decribed, but the following error occurs:

``` sh
→ webpack-dev-server webpack/hot/dev-server ./entry --hot --module-bind css=style!css
zsh: event not found: css
```

I think the `!css` is a problem. But if I try it without `!css`, it's not working, no index.html is found.
Ok, let's create a index.html in the same directory with a script tag, that references to main.

The index.html doesn't load ant script. Nothing happens.

What am I doing wrong?

Thanks

**Comment by jerryshew** [comment]
@jhnns 👍

**Comment by dancashman** [comment]
thank you!
