### ISSUE TITLE
Group modules in output

### ISSUE THREAD

**Issue by aight8** [webpack/webpack#2420]
When I use --display-modules I outputs me thousends of modules because I use lot of libraries of course. So I want to find out where the big chunks are. So I can ```--sort-modules-by size``` but the problem is that this just sort the small pieces from each package by size. I want to group this by packages literally. So I can find out which package eats how mache size.
So it's a group by functionality for analystical reasons.

Is there any solution for this today?

Otherwise it would be a great function for us..

**Comment by sokra** [comment]
https://github.com/robertknight/webpack-bundle-size-analyzer
