### ISSUE TITLE
HMR too heavy with webpack-dev-server

### ISSUE THREAD

**Issue by pwang2** [webpack/webpack#2421]
Following code will introduce a pretty big bundle for a minimal project and have to go through unwanted sourcemaping for webpack-dev-server module. 

Any easy way to get a prebundle of this and serve in the browser directly? this will make the process much quicker.

      Asset |       Size   |Chunks     |  Chunk Names
------------ | ------------- | ------------- | -------------
    test-project.js  | 291 kB |      0  [emitted]|  main
|test-project.js.map  | 319 kB  |     0  [emitted]|  main 

```
var config = require("./webpack.config.js");
config.entry.app.unshift("webpack-dev-server/client?http://localhost:8080/", "webpack/hot/dev-server");
var compiler = webpack(config);
var server = new webpackDevServer(compiler, {
  hot: true
  ...
});
```

**Comment by bebraw** [comment]
Could you move this to [webpack-dev-server](https://github.com/webpack/webpack-dev-server/issues) issue tracker? Thanks.
