### ISSUE TITLE
HMR and compile (and runtime) error (Cannot find update.)

### ISSUE THREAD

**Issue by whitecolor** [webpack/webpack#2424]
Windows 10 x64 node 5.5 webpack 2 beta
Didn't find answers to those questions.

HMR. I update the code at make mistake that lead to compilation error, and WDS reloads the page:

> [WDS] Hot Module Replacement enabled.
> client:46 [WDS] Errors while compiling.
> client:48 .....js
> Module build failed: SyntaxError:
> ...
> [WDS] App hot update...
> dev-server.js:47 [HMR] Checking for updates on the server...
> build.js:27 GET http://.../332d7c2e2f965cae2b6b.hot-update.json 404 (Not Found)(anonymous function) @ build.js:27hotDownloadManifest @ build.js:19hotCheck @ build.js:215check @ dev-server.js:12(anonymous function) @ dev-server.js:48EventEmitter.emit @ events.js:77reloadApp @ client:93onSocketMsg.errors @ client:50sock.onmessage @ client:83EventTarget.dispatchEvent @ eventtarget.js:49(anonymous function) @ main.js:274SockJS._transportMessage @ main.js:272EventEmitter.emit @ emitter.js:44WebSocketTransport.ws.onmessage @ websocket.js:35
> dev-server.js:14 [HMR] **Cannot find update. Need to do a full reload!**
> dev-server.js:15 [HMR](Probably because of restarting the webpack-dev-server)

Is it possible to avoid page reload, and wait for correction and then continue normal HMR work?

**Another case - runtimer error** (I've already created an issue for this https://github.com/webpack/webpack/issues/2385) when happens not compile error but runtimer error, while module execution:

> [HMR] **Cannot apply update. Need to do a full reload!**
> dev-server.js:36 [HMR] **ReferenceError: div1 is not defined**

I fix the code

> [WDS] Hot Module Replacement enabled.
> 2client:26 [WDS] App updated. Recompiling...
> client:91 [WDS] App hot update...
> dev-server.js:47 [HMR] Checking for updates on the server...
> log-apply-result.js:20 [HMR] Updated modules:
> log-apply-result.js:22 [HMR]  - 538
> dev-server.js:27 [HMR] App is up to date.

But nothing actually happens and HMR stops to work correctly it gets the updates, but does not apply it.

Is it possible to recover after such error without full reload? 

Wanted to hear @sokra about those I believe rather often met cases.

**BTW, browserify-hmr handles this kind of errors without troubles.**

**Comment by whitecolor** [comment]
The problem actually in running webpack-dev-server using CLI.
if to run it using node API like:
```js
var webpack = require('webpack');
var WebpackDevServer = require('webpack-dev-server');
var config = require('./webpack.config');
new WebpackDevServer(webpack(config), config.devServer)
  .listen(process.env.PORT);
```

Hope wepack2 will remove this ambiguity between different ways of running the same config: 
1) run `webpack-dev-server` and use `entry`s (`webpack-dev-server/client`, 'webpack/hot/only-dev-server') and `HotModuleReplacementPlugin` in config (without `--inline` or `--hot` options)
2) run `webpack-dev-server` CLI with `--inline` or `--hot` options (this works the worst way)
3) run web-dev-server using node API (works better way)

It would be great if webpack 2 removed this ambiguity between different ways of running the same hot-reload configuration.

**Comment by nahuel** [comment]
I'm getting this after failed builds using the node API. Related to https://github.com/webpack/webpack-dev-server/issues/358 ?
