### ISSUE TITLE
Removing runtime overhead

### ISSUE THREAD

**Issue by andersekdahl** [webpack/webpack#2425]
First off, I just want to say that Webpack is amazing!

Webpack 2 looks great, and tree shaking is really nice. But I can't find anything on removing runtime overhead. That's something that Rollup does nicely where it removes the need to a wrapping function around every module. It has a real impact on startup time when you have hundreds of modules or more.

Just wanted to see if this was on the roadmap?

**Comment by sokra** [comment]
It's on the roadmap...

**Comment by andersekdahl** [comment]
Great to hear, thanks!

**Comment by jdalton** [comment]
What is the [roadmap](https://webpack.github.io/docs/roadmap.html) entry listed as. I'm having trouble spotting in the [google doc](https://docs.google.com/document/d/1tRc0MzvRdGK7EbG2LRW8vSyoxKhR_EvRUz3AQRyFZso/edit?pli=1).
