### ISSUE TITLE
DefinePlugin does not inject variable

### ISSUE THREAD

**Issue by gajus** [webpack/webpack#2427]
I have been trying to figure this out for over an hour now. Here is the subject code:

```js
const ENVIRONMENT = process.env.NODE_ENV;
const BASENAME = process.env.APP_BASENAME;

console.log('process.env', {
    ENVIRONMENT: ENVIRONMENT,
    'process.env': process.env,
    NODE_ENV: process.env.NODE_ENV,
    APP_BASENAME: process.env.APP_BASENAME
});

if (ENVIRONMENT !== 'development' && ENVIRONMENT !== 'production') {
    throw new Error('Unknown ENVIRONMENT.');
}

export {
    BASENAME,
    ENVIRONMENT
};

```

Here is my webpack config:

```js
const webpack = require('webpack');
const path = require('path');

module.exports = {
    devtool: 'source-map',
    debug: false,
    context: __dirname,
    entry: {
        'app': [
            path.resolve(__dirname, './src/app')
        ]
    },
    output: {
        path: path.resolve(__dirname, './dist'),
        filename: '[name].js',
        publicPath: '/static/'
    },
    plugins: [
        new webpack.optimize.UglifyJsPlugin({
            compressor: {
                /* eslint-disable camelcase */
                screw_ie8: true,
                /* eslint-enable */
                warnings: false
            }
        }),
        new webpack.DefinePlugin({
            'process.env.NODE_ENV': '"production"',
            'process.env.APP_BASENAME': '"' + (process.env.APP_BASENAME || '') + '"'
        }),
        new webpack.DefinePlugin({
            'process.env': {
                NODE_ENV: '"production"',
                APP_BASENAME: '"' + (process.env.APP_BASENAME || '') + '"'
            }
        }),
        new webpack.optimize.OccurrenceOrderPlugin(),
        new webpack.optimize.DedupePlugin(),
        new webpack.NoErrorsPlugin()
    ],
    module: {
        loaders: [
            {
                include: path.resolve(__dirname, './src'),
                loader: 'babel',
                test: /\.js$/,
            },
            {
                loaders: [
                    'style?sourceMap',
                    'css?modules&importLoaders=1&localIdentName=[name]___[local]___[hash:base64:5]',
                    'resolve-url',
                    'sass?sourceMap'
                ],
                test: /\.scss$/
            }
        ]
    }
};

```

As you can see, I have tried multiple methods of using `DefinePlugin`:

```js
new webpack.DefinePlugin({
    'process.env.NODE_ENV': '"production"',
    'process.env.APP_BASENAME': '"' + (process.env.APP_BASENAME || '') + '"'
}),
new webpack.DefinePlugin({
    'process.env': {
        NODE_ENV: '"production"',
        APP_BASENAME: '"' + (process.env.APP_BASENAME || '') + '"'
    }
}),
```

Here is the console output:

```
{
    APP_BASENAME: "/campaign-master/upload-static",
    ENVIRONMENT: undefined,
    NODE_ENV: undefined,
    process.env: {
        APP_BASENAME: "/campaign-master/upload-static",
        NODE_ENV: "production"
    }
}
```

The script execution ends with an exception:

> Uncaught Error: Unknown ENVIRONMENT.

As a result of the condition that you can see in the `config.js`.

What is the reason `process.env.NODE_ENV` is not getting replaced?

**Comment by gajus** [comment]
Note, using `webpack@2.1.0-beta.6`.

**Comment by gajus** [comment]
That was painful experience.

My `.babelrc` has been configured as:

```json
{
    "presets": [
        "es2015",
        "stage-0",
        "react"
    ],
    "plugins": [
        "transform-export-default-name",
        "lodash-modularize",
        "transform-node-env-inline"
    ],
    "env": {
        "development": {
            "presets": [
                "react-hmre"
            ],
            "plugins": [
                "typecheck"
            ]
        }
    }
}

```

while I was executing webpack using:

```js
APP_BASENAME='/campaign-master/upload-static' webpack --config ./webpack.config.production.js
```

i.e. `babel-preset-react-hmre` is breaking `DefinePlugin`.

**Comment by gajus** [comment]
On a second look, I have just noticed that my `.babelrc` also includes `babel-plugin-transform-node-env-inline`, which duplicates with `DefinePlugin`.

**Comment by mdunnegan** [comment]
Hey @gajus, I think I'm facing the same problem that you did - DefinePlugin just isn't injecting the variables. I'm very new to webpack, please excuse my knowledge gaps. What exactly was the problem with babel-preset-react-hmre, and how is it fixed by updating .babelrc?

**Comment by stephensong** [comment]
Fwiw, I too am experiencing this problem.  Webpack injects undefined instead of the desired value(s).
Using Webpack 2.4.1

**Comment by bibekg** [comment]
Any updates here? I'm facing the same issue with Webpack 3.5.5. Seems to only affect variables that have some form of "ENV" in the name?

**Comment by stephensong** [comment]
I should confess that the problem I reported was actually of my own making.  Sadly, I can't actually recall the details of my error, but I can confirm that DefinePlugin is working ok for me now (using Webpack 3.5.5).  eg. the following works as expected:

  new webpack.DefinePlugin({
    'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV),
    'process.env.BUILD_TARGET': JSON.stringify(build),
  }),

hth.

**Comment by bibekg** [comment]
Just realized my problem wasn't much to do with DefinePlugin either. During development builds, we used
```js
const compiler = webpack(require('./webpack.config.js')(process.env.NODE_ENV);
server.use(webpackDevMiddleware(compiler, ...));
```
to load the webpack config but during staging/production, we instead just ran `webpack --progress` from the CLI which doesn't even pass in the `env` that I wanted to apply via DefinePlugin.

**Comment by jingpengw** [comment]
I am having the same problem with webpack-3.5.5.

**Comment by apolkingg8** [comment]
@jingpengw did you find some solution? I'm having same issue with `webpack 3.6.0` & `typescript 2.5.3`.

**Comment by jingpengw** [comment]
@apolkingg8 unfortunately, nope.

**Comment by cbioley** [comment]
@apolkingg8 I'm facing the same issue.

**Comment by GanchoDanailov** [comment]
same here

**Comment by mightyspaj** [comment]
I have the same issue. `process.env` is an empty object when I run my project in the browser. Setting `process.env.NODE_ENV` in my Webpack config also didn't change anything.

Here's my Webpack config:

```javascript
var path = require('path')
var webpack = require('webpack')
var BundleTracker = require('webpack-bundle-tracker')

module.exports = {
  context: __dirname,
  devtool: 'source-map',
  entry: [
    'react-hot-loader/patch',
    'webpack-dev-server/client?http://localhost:3000',
    'webpack/hot/only-dev-server',
    './src/js/index'
  ],
  output: {
    path: path.resolve('./src/bundles/'),
    filename: '[name]-[hash].js',
    publicPath: 'http://localhost:3000/src/bundles/'
  },
  plugins: [
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': JSON.stringify('development'),
    }),
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoEmitOnErrorsPlugin(), // Don't hot reload if there is an error
    new webpack.NamedModulesPlugin(),
    new BundleTracker({filename: './webpack-stats.json'})
  ],
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        exclude: [
          path.resolve('./node_modules/')
        ],
        include: [
          path.resolve('./src/js/')
        ],
        loader: 'babel-loader'
      }
    ]
  },
  resolve: {
    modules: [
      'node_modules',
      path.resolve(__dirname + '/src/js'),
      path.resolve(__dirname + '/node_modules')
    ],
    extensions: ['.js', '.jsx']
  }
}
```

`.babelrc`:

```
{
  "env": {
    "development": {
      "plugins": [
        "react-hot-loader/babel",
        "transform-decorators-legacy",
        "transform-object-rest-spread"
      ],
      "presets": [
        ["env", { "modules": false }],
        "react",
        "stage-1"
      ]
    },
    "test": {
      "plugins": [
        "react-hot-loader/babel",
        "transform-decorators-legacy",
        "transform-object-rest-spread"
      ],
      "presets": [
        "env",
        "react",
        "stage-1"
      ]
    }
  }
}
```

**Comment by amackintosh** [comment]
Hmm, I was just having this issue and it was trolling me. `process.env` was showing as an empty object, but after I read this https://github.com/webpack/webpack/issues/868 I tried explicitly calling `process.env.NODE_ENV` and `process.env.APP_VERSION`, and boom it worked fine. Watchout for that. It could be some of yours' problems...

```
    new webpack.DefinePlugin({
        'process.env.NODE_ENV': JSON.stringify('development'),
        'process.env.APP_VERSION': JSON.stringify(process.env.npm_package_version),
    })
```

Inside some module:

`console.log(process.env.APP_VERSION) === 0.0.1`

`console.log(process.env) === {}`

**Comment by jasonmerecki** [comment]
thanks @amackintosh, your answer helped me. 

I faced the same problem, without understanding the viewing the process.env in my debugger would still show an empty object. But the functionality is working fine.

**Comment by yuqingc** [comment]
@donce Thanks a lot. It works!! I have been researching the reason why everything was undefined when I tried getting the value from the `window` object. This `DefinePlugin` thing is really a trick.

**Comment by lpcman** [comment]
I was using create-react-app ejected app,  I find  config/webpack.config.prod.js file using new webpack.DefinePlugin(env.stringified), env imported in config/env.js 
![image](https://user-images.githubusercontent.com/4230823/42820669-4584de48-8a09-11e8-8d52-20661a8b4162.png)
and console.log(env.stringified) result is 
{ 'process.env':
   { NODE_ENV: '"development"',
     PUBLIC_URL: '""',
     VERSION: '"1.2.2"' } }, but in config/webpack.config.dev.js is this
![Uploading image.png…]()

It's really annoying, finally @amackintosh way works, Thanks.

**Comment by jcollum-nike** [comment]
@davalapar what command line are you using with that?

**Comment by davalapar** [comment]
Hmmm @jcollum-nike that's on my `webpack.config.js` on my project's folder.

Please check below gist for reference.

 https://gist.github.com/davalapar/ea078c2b6df9dc422fbfe09c94cf1983

**Comment by jcollum-nike** [comment]
I was wondering if you are using `webpack-dev-server`

**Comment by davalapar** [comment]
Nope I use nodemon

```js
// package.json

  "scripts": {
    "dev": "./node_modules/.bin/rimraf dist && ./node_modules/.bin/webpack --progress --mode=development --watch --colors",
    "prod": "./node_modules/.bin/rimraf dist && ./node_modules/.bin/webpack --progress --mode=production --watch --colors",
    "final": "./node_modules/.bin/rimraf dist && ./node_modules/.bin/webpack --progress --mode=production --colors",
    "nodemon": "./node_modules/.bin/nodemon dist/server/main.js"
  },
```

**Comment by matthiasdailey-ccri** [comment]
I'm not sure why it's called "DefinePlugin" --- it's more like a "identifier substitution plugin".

Also you might want to set `node: false` in the webpack config. By default webpack will mock node globals for the browser, which is why `process` and `process.env` are _defined_ instead of being completely undefined. That threw me off for a second.

**Comment by airinterface** [comment]
I had a same problem. 
1. I used dotenv to load from the file. But it might be the same.  
const dotenv  = require('dotenv');
dotenv.config({path:__dirname+'/.env'});
 const MYVAL    = process.env.MYVAL;

make sure that in the webpack config, you can console.log. 
    
    console.log( "MYVAL="  + MYVAL );

2. And In the webpack config's plugin section, I had 
    new webpack.DefinePlugin({
      'process.env.MYVAL': JSON.stringify( MYVAL )
    });

3. In my code, I defined console on the top.. 
    const myval = process.env.MYVAL; 
     * in the top level. 
    When I tried to refer it inside the function context, I was not 
    able to use that.

**Comment by alexey-sh** [comment]
just doesn't work with a simple config

```
const path = require('path');
const webpack = require('webpack');

module.exports = {
    entry: path.join(__dirname, 'app', 'good.js'),
    output: {
        filename: 'index.js',
        path: path.resolve(__dirname, 'dist'),
        library: 'myAwesomeLibrary', // public library name
        libraryTarget: 'umd',
        globalObject: 'this' // To make UMD build available on both browsers and Node.js
    },
    plugins: [
        new webpack.DefinePlugin({
            'VERSION': JSON.stringify(require('./package.json').version)
        })
    ],
    node: {
        fs: 'empty'
    },
    module: {
        rules: [
            {
                test: /\.js$/,
                include: path.join(__dirname, 'app'),
                use: {
                    loader: "babel-loader",
                    options: {
                        "presets": [
                            [
                                "@babel/preset-env",
                                {
                                    "targets": {
                                        chrome: '40',
                                        firefox: '52',
                                        ie: '11',
                                        safari: '9'
                                    }
                                }
                            ]
                        ]
                    }
                }
            }
        ]
    }
};

```

Really disappointed

**Comment by momesana** [comment]
As many people have pointed out, the substitution is a compile-time operation (_static_), i.e. it is carried out when the bundle is built, as opposed to being evaluated when the resulting application is run (_dynamic_) in node or the browser. You may pass in a computed value inside webpack.config.js but the value that ends up inside the template will be a fixed value determined before the application is ever run.

Another significant thing I noticed is that it **doesn't work well in combination with webpack's --watch mode**. That also makes sense as webpack will aggressively cache already compiled modules and only recompile them if the watched corresponding source files are changed. If we change the environment variables we pass in, the source files still remains unchanged thus webpack will happily skip recompiling that module if it's operating in watch mode. **We can only work around this by deleting the cache before running webpack**:
```bash
rm -rf node_modules/.cache && webpack --watch ...
```

**Comment by gagangoku** [comment]
I couldn't get webpack to work for my setup. But here's what worked. I have 2 use cases, a node server, SSR and React (ejected) code powering my SPA.

Just defining in webpack doesn't fix the problem because when running the node server babel is used, and babel doesn't know about the environment variable. Hence, I had to give the environment replacement in babel as well.


**.babelrc**
```
{
  "presets": ["@babel/env", "@babel/preset-react"],
  "plugins": [
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-proposal-optional-chaining",
    "@babel/transform-runtime",
    "transform-inline-environment-variables"
  ]
}
```


**webpack.config.js**
```
const path = require('path');
const webpack = require('webpack');

const BundleAnalyzerPlugin = require('webpack-bundle-analyzer').BundleAnalyzerPlugin;
const TerserPlugin = require('terser-webpack-plugin');

module.exports = env => {
    console.log('webpack ENVIRONMENT: ', env.ENVIRONMENT);
    return {
        // mode: 'production',
        entry: {
            client: './src/entry-points/client.js',     // client side companion for SSR
            bots: './src/entry-points/bots.js',         // For bots
            chat: './src/entry-points/chat.js',         // For Helo chat
            splash: './src/entry-points/splash.js',     // For splash page
            'media-recorder-polyfill': './src/media-recorder-polyfill.js',
        },
        output: {
            path: path.resolve(__dirname, 'assets'),
            filename: "[name].js"
        },
        module: {
            rules: [
                {
                    test: /\.js$/,
                    include: path.resolve(__dirname, 'src'),
                    loader: "babel-loader",
                    options: {
                        presets: [
                            '@babel/preset-env',
                            {'plugins': ['@babel/plugin-proposal-class-properties']},
                        ],
                        plugins: [
                            "transform-inline-environment-variables",
                        ],
                    }
                }
            ]
        },
        plugins: [
            // new BundleAnalyzerPlugin(),
            new webpack.DefinePlugin({
                // We get this value from babel, but for some reason webpack injects undefined
                'process.env.ENVIRONMENT': JSON.stringify(env.ENVIRONMENT),
                // This is for webpack to inject in the client bundle
                ENVIRONMENT: JSON.stringify(env.ENVIRONMENT),
            }),
        ],
        watchOptions: {
            aggregateTimeout: 1000,
            poll: 500,
            ignored: /node_modules/,
        }
    };
};

```

**Command to run in prod:**
`webpack --env.ENVIRONMENT=PRODUCTION --config webpack.config.js --watch --mode=development & ENVIRONMENT=PRODUCTION babel src -d dist --watch & browser-refresh dist/server/server.js
`

I also realized webpack is injecting undefined for the 'process.env.ENVIRONMENT' variable. But it injects correctly for the ENVIRONMENT variable. My guess is its to do with object.
But I need process.env.ENVIRONMENT so that I can pass the environment from Babel.

So I hacked my code where I use it to the following:
```
// HACK: Get the correct endpoints based on the environment. This hack depends on a combination of webpack & babel
// injecting the correct value for either process.env.ENVIRONMENT or ENVIRONMENT.
/* global process.env.ENVIRONMENT, ENVIRONMENT */
const env = process.env.ENVIRONMENT || ENVIRONMENT;
console.log('got ENVIRONMENT: ', env);
```


This works and I get the correct code in the client side bundle as well. For reference, this is what the compiled babel file and client bundle looks like.
**Babel compiled dist/constants.js:**
`var env = "PRODUCTION" || ENVIRONMENT;
`

**In client bundle:**
`var env = undefined || \"PRODUCTION\";
`


So i guess there is a bug somewhere. But for folks stuck here, see if this workaround helps.

**Comment by atleta** [comment]
It just doesn't work the documentation says it should.

I can define values for 'process.env' and access that from JS, I can also define top-level values but they are not visible to JS code. They can be used in the html templates, though. Based on what others have said above, what's going on here is probably:
* it only does some form of text substitution (hence it works in the html templaytes that generate the html files for the SPA)
* webpack somehow magically makes the process (or process.env) global available for JS code (node mode?) and that probably pulls the value from here
* and, on top of this, caching in the dev server will interfere with experimenting while you're trying to understand what's going on

Here is what I have in my webpack config:

```
    plugins: [
        new webpack.DefinePlugin({
            'process.env': require('../config/dev.env'),
            VERSION: JSON.stringify("DEVELOPMENT"),
        }),
...
]
```

`process.env` is what it should be, `VERSION` is undefined (and causes a compilation error with Babel).

**Comment by evilebottnawi** [comment]
Here simple and right answer https://github.com/webpack/webpack/issues/2427#issuecomment-379659188

**Comment by lschanaka** [comment]
**Good Solution**
### Working Done.

`    plugins: [
        new webpack.DefinePlugin({
            process: {
                env: {
                    VERSION: JSON.stringify("5fa3b99999"),
                    ETC: "..."
                }
            }
        })
    ]
`

**Comment by allestaire** [comment]
> **Good Solution**
> 
> ### Working Done.
> ` plugins: [ new webpack.DefinePlugin({ process: { env: { VERSION: JSON.stringify("5fa3b99999"), ETC: "..." } } }) ]`

I dont know why this works on build but different on running **webpack-dev-server**

**Comment by VioletFlare** [comment]
I ran into this issue today. I am using TypeScript and have a .ts file with a variable to be replaced. 
It looks like this:

```
private readonly _aVariableToBeReplaced: string = __aVariableToBeReplaced;
```

I was expecting my __aVariableToBeReplaced to become 'myvalue' as defined in the plugin.

It didn't.

However, I have also a .d.ts file where the variables are declared like so:

```
declare var __aVariableToBeReplaced: string;
```

Reading a post on StackOverflow, I found a mention that the variable won't be replaced if the variable is local. I don't understand how define plugin reasons about this but for me it was enough to remove the declaration from the .d.ts file and the variable got replaced in the output file.

**Comment by penseleit** [comment]
> **Good Solution**
> 
> ### Working Done.
> ` plugins: [ new webpack.DefinePlugin({ process: { env: { VERSION: JSON.stringify("5fa3b99999"), ETC: "..." } } }) ]`

Webpack's doc says you should NOT do this:

https://webpack.js.org/plugins/define-plugin/

**warning**
When defining values for process prefer 'process.env.NODE_ENV': JSON.stringify('production') over process: { env: { NODE_ENV: JSON.stringify('production') } }. Using the latter will overwrite the process object which can break compatibility with some modules that expect other values on the process object to be defined.
