### ISSUE TITLE
Allow to set sourceRoot field value in config

### ISSUE THREAD

**Issue by Vloz** [webpack/webpack#2430]
VisualStudioCode cant debug TS if this is field in the map file isn't correctly set.

Related to:
https://github.com/webpack/webpack/issues/238#issuecomment-207065290
https://github.com/webpack/webpack/issues/2298

**Comment by Vloz** [comment]
It has been fixed for webpack2 with https://github.com/webpack/webpack/commit/28776e28f357f69ab20f9de9aae4a01e935cf25d

and vscode no longer need it, since this week's update of vscode.

**Comment by frogcjn** [comment]
@Vloz Why VSCode no longer need it? Which version?

**Comment by Vloz** [comment]
@frogcjn Can't tell why, on VSCode 1.0 and earlier i had to set the sourceRoot to '/' to make absolute path work, but since VSCode 1.1.0 it run fine with an empty sourceRoot. 
[See there.](http://stackoverflow.com/questions/36470946/debug-webpack-bundled-node-ts-with-visual-studio-code)

**Comment by frogcjn** [comment]
@Volz, in my environment (VSCode 1.1.1), I should still set sourceRoot as `../`, because my bundle.js is in `./dist` and my source file is in `./src` and my webpack configuration is at the workspace root `./`.

**Comment by Vloz** [comment]
@frogcjn looks like you're using relative path for your map file and i m pretty sure VSCode wont be able to resolve this on its own unfortunately... :S

So,

you can switch to asbolute path (then you wont need to set sourceroot):
https://github.com/webpack/webpack/issues/238#issuecomment-144261479

--OR--

you can use webpack 2 beta and set the sourceRoot this way:
http://pastebin.com/xSN4pk6i
(replacing '/' by '../')
