### ISSUE TITLE
the problem of SVN version  (2)

### ISSUE THREAD

**Issue by w567675** [webpack/webpack#2436]
![qq 20160505141044](https://cloud.githubusercontent.com/assets/6658087/15037328/9ae5bc38-12cc-11e6-8f46-f29c362f12f3.png)

(pic-1)

![qq 20160505142535](https://cloud.githubusercontent.com/assets/6658087/15037392/41c92af8-12cd-11e6-9669-28be77fca04c.png)

(pic-2)

The same directory and same code with 2 operation.
1. module ID will change. (pic-1)
2. some modules ID redundant. (pic-2)

I don't know whether this is the result of this modification. （#2408）

**Comment by ismumu** [comment]
+1

**Comment by tender001** [comment]
++1

**Comment by w567675** [comment]
The bug seems to have gone, but this bug also appears. #2408
