### ISSUE TITLE
Documentation: Paradox in resolve.root

### ISSUE THREAD

**Issue by tobiasmuehl** [webpack/webpack#2437]
I was reading [this](https://webpack.github.io/docs/configuration.html#resolve-root) page in the documentation and found a paradox.

It says "It must be an absolute path! Don’t pass something like .**/app/modules**" and yet the example contains this exact path.

```js
var path = require('path');

// ...
resolve: {
  root: [
    path.resolve('./app/modules'), // <==
    path.resolve('./vendor/modules')
  ]
}
```

**Comment by sokra** [comment]
`path.resolve` converts a relative path to an absolute path
