### ISSUE TITLE
Invalid sourcemaps when using ---optimize-minimize

### ISSUE THREAD

**Issue by narak** [webpack/webpack#2438]
I get an error when I'm validating it via sourcemaps.io
    In webpack:///./js/forgot.js: Expected **webpack_require**, but found require('../css/nor

When I don't use --optimize-minimize and then minimize this file with uglifyjs myself, with mangle and compress, the sourcemaps validate just fine. I've been breaking my head over this for a few hours now and I'm unable to figure out why this.

Not sure what I am missing. I'm going to try and read through the UglifyJS plugin behaviour to see if I can make sense out of it.

**Comment by shriyanshagnihotri** [comment]
Having same issue. Any updates on this?

**Comment by bebraw** [comment]
Can you try against webpack 2?
