### ISSUE TITLE
when using `npm link`ed repos, loaders that accept files in node_modules have to be installed locally to all repos

### ISSUE THREAD

**Issue by seansfkelley** [webpack/webpack#2442]
Discovered this along with #2441, so you can see a repro at the same repo: https://github.com/seansfkelley/node-modules-alias-loader-bug under "bonus bug".

Summary: if you want to do local development across multiple repos and so have `npm link`ed them together, any loaders that accept files in `node_modules/` (such as `source-map-loader`, which is explicitly intended for this purpose) must also be installed in each linked repo. This is is unexpected, sine the linked repo may not even use Webpack. It should only be necessary in the root repo, which is the one actually running Webpack.

**Comment by sokra** [comment]
This is fixed for webpack 2, as configured loaders in configuration resolve relative to the configuration instead of relative to the resource.

**Comment by seansfkelley** [comment]
Good to hear! Is it possible to get a backport to Webpack 1?
