### ISSUE TITLE
TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by mmahalwy** [webpack/webpack#2443]
Using webpack 2 beta 6.

Trace:
```
chunk main [entry]
3-12ccc3f32505ae5e2d7e.js
Cannot read property 'length' of null
TypeError: Cannot read property 'length' of null
    at /Users/mmahalwy/Sites/sparrow/node_modules/webpack/lib/ContextModule.js:139:25
    at Array.forEach (native)
    at Module.ContextModule.source (/Users/mmahalwy/Sites/sparrow/node_modules/webpack/lib/ContextModule.js:137:6)
    at Template.ModuleTemplate.render (/Users/mmahalwy/Sites/sparrow/node_modules/webpack/lib/ModuleTemplate.js:14:28)
    at Template.renderChunkModules (/Users/mmahalwy/Sites/sparrow/node_modules/webpack/lib/Template.js:115:31)
    at Template.<anonymous> (/Users/mmahalwy/Sites/sparrow/node_modules/webpack/lib/MainTemplate.js:36:22)
    at Template.applyPluginsWaterfall (/Users/mmahalwy/Sites/sparrow/node_modules/tapable/lib/Tapable.js:34:24)
    at Template.MainTemplate.render (/Users/mmahalwy/Sites/sparrow/node_modules/webpack/lib/MainTemplate.js:129:20)
    at Compilation.createChunkAssets (/Users/mmahalwy/Sites/sparrow/node_modules/webpack/lib/Compilation.js:845:33)
    at Compilation.<anonymous> (/Users/mmahalwy/Sites/sparrow/node_modules/webpack/lib/Compilation.js:556:9)
```

Relevant code:
```
const loadContainerAsync = route => (location, cb) => {
  console.log(location, cb);
 //  require.ensure([], (require) => {
 //    cb(null, require('./containers/' + route + '/index.js'));
 // });
 // console.log(location);
 return System.import(`./containers/${route}/index.js`).then(module => cb(null, module)).catch(err => console.log(err));
};
```

**Comment by mmahalwy** [comment]
So the problem happens when trying to do dynamic `System.import`

**Comment by mmahalwy** [comment]
Thanks!

**Comment by sebastienbarre** [comment]
Boy did it take me many errors in node-inspector to track this error back to there. Would love to see that fix in beta-8. Thanks

**Comment by sebastienbarre** [comment]
@sokra I think there is still a problem here. 

`System.import()` used dynamically this way does not work for me if I try to import a module that has an `export default`. However, it works with a classic `modules.export`:
e.g.
```
var CollectionModel = AccessControlledModel.extend({
    resourceName: 'collection'
});
export default CollectionModel;
```
fails to be imported correctly with `System.import`.
However this work:
```
var CollectionModel = AccessControlledModel.extend({
    resourceName: 'collection'
});
module.exports = CollectionModel;
```
I noticed that the test you added in [issue-2443](https://github.com/webpack/webpack/tree/93f38132d118e19337dee3c091364902cf15f499/test/cases/chunks/issue-2443) imports 3 files, and they *all* use `module.exports`, not ES6 `export default`.

Maybe I'm misunderstanding `System.import`, but since it's introduced in the [ES6 Modules](https://gist.github.com/sokra/27b24881210b56bbaff7#es6-modules) section of "What's new in webpack 2", I assumed it would be able to handle `export default`, the same way `import... from...` does. I want to be able to import `CollectionModel` with `import...from`, as well as `System.import` (using a directory + pattern), but it seems I would have to provide *both* `export default` *and* `module.exports` in the same file?

Thanks

**Comment by sokra** [comment]
Have you tried

``` js
System.import(`...`).then(module => cb(null, module.default))
```

**Comment by sebastienbarre** [comment]
@sokra I'm not sure what it does but I'll try, thanks. 
In the meantime, I just looked at the issue-2443 test, and replaced all:
```
module.exports =
```
with
```
export default 
```
in `dir/one`, `dir/two`, `dir/three`, and the tests are indeed failing:
```
webpack (master)$ node_modules/.bin/mocha --harmony --full-trace --check-leaks --grep 2443
18 passing (1s)
  18 failing

  1) TestCases normal chunks issue-2443 should be able to use expressions in System.import (directory):
     AssertionError: expected Object { default: 1 } to equal 1
      at Assertion.fail (/Volumes/Users/Shared/Src/js/webpack/node_modules/should/lib/assertion.js:92:17)
      at Assertion.value (/Volumes/Users/Shared/Src/js/webpack/node_modules/should/lib/assertion.js:164:19)
      at /Volumes/Users/Shared/Src/js/webpack/test/js/normal/chunks/issue-2443/bundle.js:149:22
etc.
```

They were all passing before.

**Comment by mmahalwy** [comment]
@sokra I think your suggestion of this would work:
```
System.import(`...`).then(module => cb(null, module.default))
```

How would this work with add-module-exports babel plugin? https://www.npmjs.com/package/babel-plugin-add-module-exports

**Comment by valerybugakov** [comment]
@sokra @sebastienbarre hey guys, I'm trying to use dynamic imports as mentioned above
```
System.import(`./pages/${component}`).then(module => cb(null, module.default))
```
but module fails to be imported with the stack trace
```
ERROR in chunk app [entry]
2.chunk.js
Cannot read property 'length' of null
```
But it works with
```
require.ensure([], (require) => {
  cb(null, require(`./pages/${component}/index.js`))
})
```
Any suggestions how to fix that?

**Comment by sebastienbarre** [comment]
@valerybugakov sorry, the `module.default` trick worked for me...

**Comment by valerybugakov** [comment]
@sebastienbarre do you use variable in module name too? Error happens only if I'm trying to use dynamic path for `System.import`, `System.import(`./pages/Login`)` works for me.

**Comment by sebastienbarre** [comment]
@valerybugakov correct, with a variable. Like this:
```javascript
        System.import('girder/models/' + modelName).then(function (Model) {
            var parent = new Model.default();
...
```
