### ISSUE TITLE
Hot reload, recovering from error

### ISSUE THREAD

**Issue by Termina1** [webpack/webpack#2449]
As I understand, it is a known issue, that hot reload is not good at recovering after errors. Most of people use `NoErrorsPlugin` to deal with it.

For example, you can clone this repo https://github.com/Termina1/react-shower
1. npm i && npm start
2. go to localhost:3000
3. create any syntax error in presentation.js
4. fix error

You will see:

```
bundle.js:462 Uncaught TypeError: Cannot read property 'children' of undefinedhotApply 
@ bundle.js:462(anonymous function) 
@ bundle.js:8068hotUpdateDownloaded 
@ bundle.js:312hotAddUpdateChunk 
@ bundle.js:284webpackHotUpdateCallback 
@ bundle.js:5(anonymous function) 
@ 0.9b3ec8f….hot-update.js:1
```

It seems, if I accept changes that came with error, I create new installedModules array, but errored module is missing, however after fixing this error, webpack tries to update this module, but can't find it.

I create really simple fix for that here: https://github.com/Termina1/webpack/commit/bc2076738b686b9ac93ab8918916b0873c06f81d

I guess it's ugly, but it fixes the issue, may be somebody would have better thoughts on how to implement the recovery?

**Comment by bebraw** [comment]
Can you check this against webpack 2?
