### ISSUE TITLE
Test server dir in preloaders independently of other loaders

### ISSUE THREAD

**Issue by AppShipIt** [webpack/webpack#2453]
Continued from [Twitter](https://twitter.com/AppShipIt/status/729250536587956224):

> Any ideas how to get WebPack to run loaders selectively (e.g. only ESLint) per entry (e.g. server in universal app)???

@kristian-puccio suggested:

> It would be great if you could specify the `entry` name as a restriction to a `loader`

My use case is building the client of our <q>universal</q> app but reusing `preloaders` to test my server `entry` too. Is there an existing solution?

**Comment by bebraw** [comment]
I don't know if it would work for your case, but you could return an array of configurations. One of those would handle linting and so on. Worth a go at least.

**Comment by AppShipIt** [comment]
I didn't know that ([example](https://github.com/webpack/webpack/tree/master/examples/multi-compiler) for future reference)! That resolves my use case so I'm happy to close.

**Comment by bebraw** [comment]
Cool.
