### ISSUE TITLE
Hot module accept IIFE arrow function unexpected token

### ISSUE THREAD

**Issue by calebmer** [webpack/webpack#2455]
Before I explain the bug I'm hitting, I want to say that I do have an uncommon configuration which exposes this particular issue. I'm pretty sure this is an easy fix (unless it's a bug in Chrome…).

* * *

I'm building a JavaScript bundle targeted at `electron-renderer` using Node 6 with Webpack `2.1.0-beta.7` and Babel with *only* JSX transforms configured. In the code I'm bundling I have the following:

```js
module.hot.accept('./components/app/App.js', () => {
  render(
    <AppContainer>
      <App/>
    </AppContainer>
  )
})
```

Which Webpack builds to the following:

```js
module.hot.accept(67, function(callback) { /* harmony import */ __WEBPACK_IMPORTED_MODULE_3__components_app_App_js__ = __webpack_require__(67);
(() => {
   render(/* harmony import */__WEBPACK_IMPORTED_MODULE_0_react___default.a.createElement(
     /* harmony import */__WEBPACK_IMPORTED_MODULE_2_react_hot_loader__["AppContainer"],
     null,
     /* harmony import */__WEBPACK_IMPORTED_MODULE_0_react___default.a.createElement(/* harmony import */__WEBPACK_IMPORTED_MODULE_3__components_app_App_js__["default"], null)
   ));
 }()); });
```

Which I'm going to abbreviate (to help explain the error) to this:

```js
module.hot.accept(67, function(callback) {
(() => {
  // Unimportant stuff…
 }()); });
```

With the most important part being the IIFE which looks like this:

```js
(() => { }())
```

Chrome (the version bundled with Electron) throws an unexpected token error at this. It seems Chrome doesn’t like IIFEs written like: `(() => { }())`, but will accept an IIFE written like: `(() => { })()`. If you are viewing this in an edition of Chrome with arrow function support, you should be able to reproduce this (I was just able to reproduce this in my version of Chrome beta outside of Electron).

I'm not an ES spec expert so I'm not sure if this is a bug in Chrome, or incorrect code output on Webpack’s part. Either way this should be a simple fix for Webpack.

**Comment by sokra** [comment]
related to #2460
