### ISSUE TITLE
System.import in isomorphic app

### ISSUE THREAD

**Issue by mmahalwy** [webpack/webpack#2461]
Using webpack-2 and using the `System.import` feature. I cannot get it to work on an isomorphic app which errors with `System.import` is not a function, since `System` doesn't exist on the server.

Any ideas for how to get it working on both?

**Comment by kesne** [comment]
In Node, you can call `require` at any point, so you should be able to shim the `System.import` behavior with something like this:

```
System.import = function(path) {
  Promise.resolve(require(path));
};
```

**Comment by mmahalwy** [comment]
+1 to that @kesne I also ended up using https://github.com/thgreasi/babel-plugin-system-import-transformer

**Comment by sokra** [comment]
Three options:

#### polyfill

``` js
if(typeof System === "undefined") {
  var System = {
    import: function(path) {
      return Promise.resolve(require(path));
    }
  };
}
```

#### Transpile with babel

https://github.com/thgreasi/babel-plugin-system-import-transformer

#### Build with webpack

``` text
webpack --target node ...
```

**Comment by mmahalwy** [comment]
thanks @sokra for the awesome answer!

**Comment by mmahalwy** [comment]
Heads up, this is still not working as needed.

```
const loadRouteAsync = path => (nextState, cb) => {
    console.log(path);
      System.import(path).then(module => {
        cb(null, module)
      });
  };
```

returns warning:
```
Critical dependencies:
26:6-25 the request of a dependency is an expression
```

And when this happens, on the server it fails, but when I input a path string to import, it doesn't show warning nor break babel-plugin-system-import-transformer

**Comment by adriantoine** [comment]
@mmahalwy Hi! You can't import a path without a prefix like that, see https://github.com/webpack/webpack/issues/2401
