### ISSUE TITLE
Webpack's Acorn Dependency Choking on JSX on Node 6.0+ (Babel-Loader Not Being Loaded Correctly?)

### ISSUE THREAD

**Issue by joshburgess** [webpack/webpack#2462]
JSX code for me that works on Node 5.11 is failing with Node 6. It appears to be a problem with the Acorn module Webpack is relying on.

> ERROR in ./src/index.js
> Module parse failed: c:\code\app\src\index.js Unexpected token (17:2)
> You may need an appropriate loader to handle this file type.
> SyntaxError: Unexpected token (17:2)
>     at Parser.pp.raise (C:\code\canopy-app\node_modules\webpack\node_modules\acorn\dist\acorn.js:920:13)
>     at Parser.pp.unexpected (C:\code\canopy-app\node_modules\webpack\node_modules\acorn\dist\acorn.js:1483:8)
>     at Parser.pp.parseExprAtom (C:\code\canopy-app\node_modules\webpack\node_modules\acorn\dist\acorn.js:330:12)
>     at Parser.pp.parseExprSubscripts (C:\code\canopy-app\node_modules\webpack\node_modules\acorn\dist\acorn.js:225:19)
>     at Parser.pp.parseMaybeUnary (C:\code\canopy-app\node_modules\webpack\node_modules\acorn\dist\acorn.js:204:17)
>     at Parser.pp.parseExprOps (C:\code\canopy-app\node_modules\webpack\node_modules\acorn\dist\acorn.js:151:19)
> 
>     at Parser.pp.parseMaybeConditional (C:\code\canopy-app\node_modules\webpack\node_modules\acorn\dist\acorn.js:133:19)
>     at Parser.pp.parseMaybeAssign (C:\code\canopy-app\node_modules\webpack\node_modules\acorn\dist\acorn.js:110:19)
>     at Parser.pp.parseExprList (C:\code\canopy-app\node_modules\webpack\node_modules\acorn\dist\acorn.js:657:23)
>     at Parser.pp.parseSubscripts (C:\code\canopy-app\node_modules\webpack\node_modules\acorn\dist\acorn.js:249:29)
>  @ multi main

Extra info: 

Webpack version: 1.13.0

Referenced Acorn version within Webpack's node_modules: 3.1.0

Chunk of code the parser is choking on:

`render(
  <Root />,
  document.getElementById('root')
);`

It seems to just choke on basic JSX syntax. However, if I downgrade Node back to 5.11 it works as it should.

**Comment by sokra** [comment]
webpack doesn't accept JSX. You need to transpile it. i. e. use the babel-loader.

**Comment by joshburgess** [comment]
Sorry, perhaps this was poorly worded. I am actually using babel-loader to load all JS files in my src directory.

Here's the config related to that:

```
      {
        test: /\.js$/,
        loaders: ['source-map', 'babel'],
        include: [
          path.join(__dirname, 'src'),
        ],
        exclude: [
          path.join(__dirname, 'src', 'assets'),
        ],
      },
```

So, maybe the real problem is that babel-loader isn't being loaded properly in Node 6.0+ for whatever reason...

**Comment by mjasnikovs** [comment]
Same issue here, works in 4.4.4, not works in 6.2.0

**Comment by joshburgess** [comment]
I'm surprised this isn't getting more attention... Anybody else having issues?

**Comment by joshburgess** [comment]
Linking to issue in babel-node: #https://github.com/babel/babel-loader/issues/198

**Comment by eskhool** [comment]
I just wasted a few hours trying to debug this. My first real experience with node being an unstable land (I know its not their fault but they don't seem to have done anything to fix it). I just started working with node which was version 6.1 and it just wouldn't work!

**Comment by rabbitrun** [comment]
josh are you on a PC? or  Mac?  I ran into the same issue.  7 of our mac developers' build is working.  1 guy is on the PC and it's not working.  We all cloned our code repository.  The PC guy got the same error you have.

**Comment by joshburgess** [comment]
@rabbitrun I was on a Windows machine when I had this issue. I'll pull down the same project on my Mac at home & try it again and let you know what happens.

**Comment by joshburgess** [comment]
@all This appears to be working correctly for me now even on Windows. I forked my app to a new branch, completely removed the node_modules folder, then ran npm cache clean, then ran a fresh npm install of every dependency while on Node v6.2.0 and npm v3.3.6. Didn't have any issues this time... not 100% sure what the problem was. I think clearing the cache may be related. Going to close this for now.

**Comment by shalomvolchok** [comment]
@all Just wanted to post here in case someone else comes looking for a solution. The problem seems to be caused by having duplicate installations of react-relay (in my case nested node_modules folder). That is most likely why the clean install got it working.

**Comment by eskhool** [comment]
I can confirm that. I had a symlinked note_modules folder which is not
*liked* by npm at all.

**Comment by alf** [comment]
For me, the reason for this error was that I was running webpack in eshell and thus the PWD environment variable had the drive letter in lower case. Thus the include pattern for my jsx files did not match (the discovered files used upper case for the drive letter).

**Comment by threehams** [comment]
I've also seen this error when running a terminal within Visual Studio Code, which might have a similar cause.

**Comment by bijancamp** [comment]
Unfortunately, removing node_modules, followed by running `npm cache clean` and `npm install`, didn't work for me. I ended up just downgrading Node to 4.4.7, which fixed the problem for me.

**Comment by noahehall** [comment]
didnt work for me either

**Comment by lmanco** [comment]
I'm still getting this error regardless of what version of Node I use. I have done `npm cache clean` after removing node_modules and changing versions every time. Does anyone have any more information on this?

My webpack config is:
`const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
  entry: [
    './app/main.jsx'
  ],
  output: {
    path: './dist',
    filename: 'bundle.js'
  },
  resolve: {
    extensions: ['', '.js', '.jsx']
  },
  devtool: 'source-map',
  devServer: {
    inline: true,
    contentBase: './dist',
    port: 8100
  },
  module: {
    loaders: [
      {
        test: /\.jsx?$/,
        loader: 'babel',
        include: './app'
      },
      {
        test: /\.less$/,
        loader: "style!css!postcss!less",
        include: './app/theme'
      }
    ]
  },
  plugins: [
    new HtmlWebpackPlugin({
      template: './app/index.html',
      filename: 'index.html',
      inject: 'body'
    })
  ]
};
`

My .babelrc is:
`{
  "presets": [
    "react",
    "es2015"
  ]
}
`

Any help with this would be greatly appreciated.

**Comment by lmanco** [comment]
I'm still getting this error regardless of what version of Node I use. I have done npm cache clean after removing node_modules and changing versions every time. Does anyone have any more information on this?

My webpack config is:
```const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
entry: [
'./app/main.jsx'
],
output: {
path: './dist',
filename: 'bundle.js'
},
resolve: {
extensions: ['', '.js', '.jsx']
},
devtool: 'source-map',
devServer: {
inline: true,
contentBase: './dist',
port: 8100
},
module: {
loaders: [
{
test: /.jsx?$/,
loader: 'babel',
include: './app'
},
{
test: /.less$/,
loader: "style!css!postcss!less",
include: './app/theme'
}
]
},
plugins: [
new HtmlWebpackPlugin({
template: './app/index.html',
filename: 'index.html',
inject: 'body'
})
]
};
```

My .babelrc is:
```{
  "presets": [
    "react",
    "es2015"
  ]
}
```

Any help with this would be greatly appreciated.

**Comment by lmanco** [comment]
I'm still getting this error regardless of what version of Node I use. I have done npm cache clean after removing node_modules and changing versions every time. Does anyone have any more information on this?

My webpack config is:
```
const HtmlWebpackPlugin = require('html-webpack-plugin');

module.exports = {
entry: [
'./app/main.jsx'
],
output: {
path: './dist',
filename: 'bundle.js'
},
resolve: {
extensions: ['', '.js', '.jsx']
},
devtool: 'source-map',
devServer: {
inline: true,
contentBase: './dist',
port: 8100
},
module: {
loaders: [
{
test: /.jsx?$/,
loader: 'babel',
include: './app'
},
{
test: /.less$/,
loader: "style!css!postcss!less",
include: './app/theme'
}
]
},
plugins: [
new HtmlWebpackPlugin({
template: './app/index.html',
filename: 'index.html',
inject: 'body'
})
]
};
```


My .babelrc is:
```
{
  "presets": [
    "react",
    "es2015"
  ]
}
```

Any help with this would be greatly appreciated.

**Comment by creamidea** [comment]
@lmanco You are right. And I watch the problem:
```js
LoadersList.prototype.matchObject = function matchObject(str, obj) {
	if(obj.test)
		if(!this.matchPart(str, obj.test)) return false;
	if(obj.include)
		if(!this.matchPart(str, obj.include)) return false;
	if(obj.exclude)
		if(this.matchPart(str, obj.exclude)) return false;
	return true;
};
```
Here, code shows that webpack will test the `include`. So, if the value of `include `on different OS will make the result different. You can click [here ](https://github.com/creamidea/creamidea.github.com/issues/19)to learn more. 
At last, I recommend to replace `__dirname + '/app'` with `path.resolve(__dirname, 'app')`

Good luck :)

**Comment by Loopiezlol** [comment]
Found out this can also be related to `webpack-stream`.

Initially, I was running webpack from my gulp file:
```js
import webpack from 'webpack-stream';
// ...
gulp.task('main', ['lint', 'clean'], () =>
  gulp.src(paths.clientEntryPoint)
    .pipe(webpack(webpackConfig))
    .pipe(gulp.dest(paths.distDir)),
//    .pipe(connect.reload()),
);
```

By installing `webpack` as a dependency to my folder, the paths were the errors were thrown were under:
```
node_modules\webpack-stream\node_modules\acorn\
```

When switching to `webpack` with no `gulp` support (using `webpack` instead of `webpack-stream`) my problems were solved. Possibly because `webpack-stream` uses version`^1.12.9`?

Encountered this bug while trying to implement SendBird JavaScript library.

**Comment by andreiglingeanu** [comment]
@Loopiezlol well you're not the first one to have problems with `webpack-stream`. I was better off invoking the webpack compiler by myself (and using webpack's watcher instead of gulp ones) like [that](https://github.com/Creative-Themes/build-process/blob/ba73508d87b591c5d4d67fe13336ac461fe8a82f/webpack-task.js#L19-L58). 

The downside is that you'll have to configure entries using webpack syntax and not by using `gulp.src`, which is not a downside for me either. I find the webpack way for doing is way better, at least for my own needs.

**Comment by Loopiezlol** [comment]
@andreiglingeanu Thanks for the heads up and tip
the more you know..

**Comment by pts-moog16** [comment]
@Loopiezlol I am also using Gulp and webpack and have the same issues. Did you try adding the webpack lib into the arguments of the webpack-stream? Should look like this:

```
import webpackStream from 'webpack-stream';
import webpack from 'webpack';

// ...

gulp.task('main', ['lint', 'clean'], () =>
  gulp.src(paths.clientEntryPoint)
    .pipe(webpackStream(webpackConfig, webpack))
    .pipe(gulp.dest(paths.distDir)),
//    .pipe(connect.reload()),
);

```

**Comment by reefloretto** [comment]
@pts-moog16 did that work for you?
