### ISSUE TITLE
Queries are not overridden when aliasing preloader

### ISSUE THREAD

**Issue by schirrmacher** [webpack/webpack#2465]
My webpack config:

```
preLoaders: [
            {
                ...
                loader: 'my-loader?test=1',
                ...
            }
        ],
resolveLoader: {
        alias: {
            'my-loader': path.join(__dirname, 'my-loader.js?test=2')
        }
    }
```

Inside my loader:

```
console.log(this.query); // ?test=2
```

According to the [table](https://github.com/webpack/webpack/issues/1513#issuecomment-162828395) I should get  `?test=1` right?!

> alias: a: b?2 
> request: a?1
> result: b?1

**Comment by schirrmacher** [comment]
loader -> preloader

**Comment by cByst** [comment]
How is this intended to work if there are query parameters in both the alias and the request that do not match for instance:

```javascript
preLoaders: [
            {
                ...
                loader: 'my-loader?test=1&varTwo=6',
                ...
            }
        ],
resolveLoader: {
        alias: {
            'my-loader': path.join(__dirname, 'my-loader.js?test=2&varThree=4')
        }
    }
```
should the resulting query string be ?test=1&varTwo=6 or ?test=1&varTwo=6&varThree=4?

The below table does not really go into this detail.

alias	|request | result
-----------|-------|------
a: b	|a	|b
a: b	|a?1|	b?1
a: b?2|	a|	b?2
a: b?2	|a?1|	b?1

**Comment by chinesedfan** [comment]
@cByst 
I think it should be `?test=1&varTwo=6&varThree=4`, as well as `$.extend` in jQuery.

**Comment by iclanton** [comment]
Is there a plan to fix this soon? When might we expect to see this fixed in the webpack NPM package?

**Comment by sokra** [comment]
queries wont merge, as the syntax is up to the loader.
