### ISSUE TITLE
Requiring a library that assigns to module.exports within itself creates ReferenceError

### ISSUE THREAD

**Issue by ritcoder** [webpack/webpack#2467]
Hi,
I'm requiring a library which looks like this

````
/* 77 */
/***/ function (module, exports) {

        (function(){
           'use strict';
           
           function F2(fun)...
           ...
           var Elm = {};
           ...
           if (typeof module === 'object') {
             module['exports'] = Elm; //the export is internal
           }
           ...
        }).call(this);

        module.exports = Elm; //this is the error line. Elm is not defined. It is hidden in the function above
/***/ }
````

How do I get around this?
If there a way or config to set to have this exports changed to as below?

    if (!module.exports)
        module.exports = Elm;

**Comment by bebraw** [comment]
Can you try https://github.com/webpack/expose-loader ?

**Comment by ritcoder** [comment]
Using `var Elm = require("expose?Elm!./Main");` gives a new error

`Uncaught ReferenceError: global is not defined`

The module in the output js file is as follows

````
/* 63 */
/***/ function(module, exports) {

	module.exports = global["Elm"] = require("-!u:\\PlayGround\\Elm\\Testing 0.1.7\\node_modules\\elm-webpack-loader\\index.js!u:\\PlayGround\\Elm\\Testing 0.1.7\\src\\Main.elm");

/***/ }
````

**Comment by bebraw** [comment]
More ideas: https://webpack.github.io/docs/shimming-modules.html . This could be tricky to solve.

**Comment by ritcoder** [comment]
Looks like loaders was the way to go. Couldn't find one that could address this issue so wrote a simple one (no-export-loader) that simply removes the last module.exports line. Will push it later if there is no official way around this.

**Comment by bebraw** [comment]
Cool to hear!

**Comment by ritcoder** [comment]
Loader published [here](https://www.npmjs.com/package/no-export-loader).
