### ISSUE TITLE
[1.13.0] Patching __webpack_public_path__?

### ISSUE THREAD

**Issue by ojacobson** [webpack/webpack#2468]
I've got a webpack application that I'm deploying to [Aerobatic](https://www.aerobatic.com), who provide a CDN as part of their platform. Aerobatic provides some tools to allow JS running in the page to find the CDN root, which allows me to fetch assets from the CDN using code like

```js
((window['__aerobatic__'] || {})['staticAssetPath'] || '') + "/path/to/some/asset.png";
```

Not my real code, but you get the idea: when developing, assets are fetched from the same origin server as the page itself, while on Aerobatic, they're fetched from Aerobatic's CDN. Aerobatic also rewrites HTML so that asset references in the page (such as `<script>` tags) refer to the CDN, instead of fetching them directly from the origin.

Is there any way to take advantage of this in Webpack's chunk loader? Inspecting my compiled bundle, I see Webpack uses

```js
…
/******/ 			script.src = __webpack_require__.p + "chunks/" + ({}[chunkId]||chunkId) + "." + {"1":"5ee8ddc71a2ddb623a23","2":"6a7511be760e094d38ad","3":"cbf7d406633e0cb6805d"}[chunkId] + ".chunk.js";
/******/ 			head.appendChild(script);
…
/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "/js/";
…
```

to load chunks. The resulting script elements load chunks from the origin directly, even though the entry point came from a CDN. If I could replace the literal `"/js/"` (which comes from my `webpack.config.js`) with a function call, or if I could reliably modify `__webpack_require__.p` after the fact, I would be able to lazily load code while also using the CDN for those chunks. Since lazy chunks contain the majority of my app, that'd be a pretty big win for me.

Is there any way to do that? I'm willing to write plugins if necessary. If not, would some kind of support for this be a worthwhile patch?

**Comment by ojacobson** [comment]
The first thing I tried (reassigning `require.p` in my entry points) made Webpack fairly unhappy:

```js
'use strict';

import domReady from 'detect-dom-ready';
import asset from './App/asset';

// Use the Aerobatic CDN for loading assets. This must happen before calls to
// require.ensure.
require.p = asset(require.p);

domReady(() => {
    require.ensure([], (require) => {
        // use explicit module index as a concession to Mac OS developers. Stops "require('./App')" from resolving to
        // this very file.
        require('./App/index');
    });
});
```

Lead to this output:

```
Hash: a2779ed2f9e570813d32
Version: webpack 1.13.0
Time: 928ms
            Asset     Size  Chunks             Chunk Names
    app.bundle.js   898 kB       0  [emitted]  app
app.bundle.js.map  1.05 MB       0  [emitted]  app
  [80] ./js ^\.\/.*$ 622 bytes {0} [built] [2 warnings]
    + 243 hidden modules

WARNING in ./js/app.js
Critical dependencies:
15:0-7 require function is used in a way in which dependencies cannot be statically extracted
15:33-40 require function is used in a way in which dependencies cannot be statically extracted
 @ ./js/app.js 15:0-7 15:33-40

WARNING in ./js ^\.\/.*$
Module not found: Error: a dependency to an entry point is not allowed
 @ ./js ^\.\/.*$

WARNING in ./js ^\.\/.*$
Module not found: Error: a dependency to an entry point is not allowed
 @ ./js ^\.\/.*$
```

This is, somewhat notably, missing most of my chunks.

**Comment by helloyou2012** [comment]
@ojacobson you can do this from backend like this:

```
assetsPath = process.env.DEBUG? 'local' : 'http://cdn.com/xxx';
```

```
<script src="{{assetsPath}}/index.js"></script>
```

**Comment by bebraw** [comment]
@helloyou2012 I don't think there are official plans related to this. I marked the issue as "enhancement" if someone wants to try to tackle it, though.

**Comment by sokra** [comment]
You can set the `__webpack_public_path__` at runtime:

``` js
__webpack_public_path__ = "http://cdn.example.com";
```

**Comment by ojacobson** [comment]
@sokra I should've realized that would be sufficient. It's not in the current docs, but it is mentioned in the Github docs - thanks for pointing me in the right direction!

**Comment by ojacobson** [comment]
@helloyou2012 Thanks for the suggestion. Unfortunately, Aerobatic provides their own server, and I don't have the option of running my own code on it. That's a pretty good workaround, otherwise!
