### ISSUE TITLE
Webpack got error when I modify my package.json 

### ISSUE THREAD

**Issue by kidbai** [webpack/webpack#2470]
error msg: 
`ERROR in Entry module not found: Error: Cannot resolve 'file' or 'directory' ./demo1/js/demo1.js in /Users/Youngbye/pro/github/webpack_`

When I recover package.json,  webpack is OK. Why?

**Comment by bebraw** [comment]
Could you provide the files (package.json, webpack configuration) in question? It's hard to tell what's going on without additional information.

**Comment by kidbai** [comment]
package.json 

```
{
  "name": "webpack_",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "gulp": "^3.9.1",
    "webpack": "^1.13.0",
    "webpack-stream": "^3.2.0"
  },
  "dependencies": {
    "gulp-base64": "^0.1.3"
  }
}
```


webpack.config.js

```
var webpack = require('webpack');
module.exports = {
    entry: {
        demo1: './demo1/js/demo1.js'
    },
    output: {
        path: __dirname,
        filename: './demo1/build/[name].js'
    },
    plugins: [
       new webpack.optimize.UglifyJsPlugin({
           compress: {
               warnings: false
           }
       })
    ]
}
```


It will be error when I execute webpack command line if I delete "webpack-stream": "^3.2.0" this line in package.json.

**Comment by bebraw** [comment]
You could try an absolute path over `'./demo1/js/demo1.js'`. I mean something like `path.join(__dirname, 'demo1', 'js', 'demo1.js')`.

**Comment by sokra** [comment]
You propably caused the package.json to be invalid JSON. Also remove the dangling comma in the file:

``` diff
-    "webpack": "^1.13.0",
-    "webpack-stream": "^3.2.0"
+    "webpack": "^1.13.0"
```
