### ISSUE TITLE
libraryTarget umd & code splitting

### ISSUE THREAD

**Issue by davidagraf** [webpack/webpack#2471]
When splitting code in webpack, the chunks are loaded with temporary script tags:

```
/******/    var head = document.getElementsByTagName('head')[0];
/******/    var script = document.createElement('script');
/******/    script.type = 'text/javascript';
/******/    script.charset = 'utf-8';
/******/    script.async = true;
/******/    script.timeout = 120000;

/******/    script.src = __webpack_require__.p + "" + ({}[chunkId]||chunkId) + "." + "<some_key>" + ".js";
```

When creating an umd library, the library might be loaded by another bundler again (webpack, jspm, etc.). In that case, the script tag loading isn't nice. It would be better to keep the AMD (or System.import for webpack 2) in the chunks which will be interpreted by the other bundler. I didn't find an option to enable this. Is it a missing feature? Or am I missing something and code splitting in umd libraries not possible?

**Comment by sokra** [comment]
It's a missing feature..

**Comment by davidagraf** [comment]
This feature would be super handy for us. What's the difficulty in implementing it? I guess, replacing the temp script stuff with System.import is not complicated, right? Is the problem the current jsonp in the bundles?

**Comment by sokra** [comment]
It all starts here: https://github.com/webpack/webpack/blob/master/lib/JsonpTemplatePlugin.js

This is the important part: https://github.com/webpack/webpack/blob/master/lib/JsonpMainTemplatePlugin.js

You need to write a custom target too: https://github.com/webpack/webpack/blob/master/lib/WebpackOptionsApply.js#L68-L77

You can publish all off this as separate module like here:
https://github.com/chentsulin/webpack-target-electron-renderer#how-this-module-works

**Comment by AndyOGo** [comment]
@sokra 
I would need this feature too. Could you consider to reopen this?

**Comment by alexcastillo** [comment]
+1

**Comment by AndyOGo** [comment]
@davidagraf 
@alexcastillo 
@monteraphael
@LucaMele
@sokra 

I just created a new ticket, cause this was not reopenend, at #6818
