### ISSUE TITLE
How to have a bundle specific loader configuration?

### ISSUE THREAD

**Issue by gajus** [webpack/webpack#2474]
I need to make two versions of a bundle using different loaders.

Is there a way to define bundle specific loaders?

The only way I can think of that this can be done at the moment is two have two separate webpack configurations and run webpack build twice. This is far from ideal since this duplicates compilation of all assets.

**Comment by bebraw** [comment]
As far as I understand, nope. You could do `module.exports = [{...}, {...}]` and then use a utility like [webpack-merge](https://www.npmjs.com/package/webpack-merge) or similar to manage duplication.

Once the configuration is in a format like that, you can use [parallel-webpack](https://www.npmjs.com/package/parallel-webpack) to speed up execution. There will be overhead, but at least you'll get multiprocessing.
