### ISSUE TITLE
Caching

### ISSUE THREAD

**Issue by ajgreenb** [webpack/webpack#2475]
I [asked this question on StackOverflow][so-post], but it got down-voted so I'm going to try asking it here. If there's a better place to ask, I'd love to know!

Just out of curiosity, why does webpack have to re-build from scratch each time it starts?

What's stopping it from checking the last modified times of all the included files and comparing them to the last modified time of the bundle(s) and then doing incremental updates (like it does when it runs in watch mode)? Couldn't that prevent a long initial bundling?

[so-post]: http://stackoverflow.com/questions/37164259/why-does-webpack-have-to-re-build-from-scratch-each-time-it-starts

**Comment by bebraw** [comment]
Hi,

The core problem has to do with the fact that the key structures of webpack aren't serializable yet. You would need that to enable caching. This might change in the future (webpack 3?) but isn't possible at the moment.

You can sort of hack it with [DllPlugin](https://github.com/webpack/docs/wiki/list-of-plugins#dllplugin) (handy for vendor bundle). And then there are solutions like [happypack](https://www.npmjs.com/package/happypack).
