### ISSUE TITLE
Emitted file path in source map's sources entries is not correct when absolute-resource-path is used

### ISSUE THREAD

**Issue by sheetalkamat** [webpack/webpack#2481]
I added these three options to the multiple-commons-chunks to play around with debugger changes I am making for the typescript vs debugger extension that can debug sourcemap. 

Additions in webpack.config.js:

```
    devtool: 'source-map',
    output: {
        path: path.join(__dirname, "js"),
        filename: "[name].js",
        devtoolModuleFilenameTemplate: "[absolute-resource-path]?[hash]",
        devtoolFallbackModuleFilenameTemplate: "[absolute-resourcePath]?[hash]"
    },
```

The generated sourcemap contains entries like:
eg. in js/admin-commons.js.map

```
"C:\\webpack\\examples\\multiple-commons-chunks\\modules\\a-b-c.js?d463",
"C:\\webpack\\examples\\multiple-commons-chunks\\modules\\admin.js?7264*"
```

Shouldn't this be instead 

```
"file:///C:/webpack/examples/multiple-commons-chunks/modules/a-b-c.js?d463",
"file:///C:/webpack/examples/multiple-commons-chunks/modules/admin.js?7264*"
```

Because C:\webpack\examples\multiple-commons-chunks\modules\**admin.js?7264** would mean a file with name `admin.js?7264` in `C:\\webpack\\examples\\multiple-commons-chunks\\modules`.

**Comment by sokra** [comment]
``` js
devtoolModuleFilenameTemplate: "file:///[absolute-resource-path]",
```
