### ISSUE TITLE
Watch mode not working correctly with Node 6.1.0 on Mac OS X

### ISSUE THREAD

**Issue by trotzig** [webpack/webpack#2486]
I'm running webpack 1.13.0 on a Mac OS X running Yosemite 10.10.5 (14F27). My node version is 6.1.0.

When I make changes to certain files, webpack isn't recreating bundles. Not all files have this issue however. Changes to some files do cause webpack rebuilds. On top of that, I'm also seeing errors like these on webpack-dev-server startup:

```
2016-05-13 18:32 node[4171] (FSEvents.framework) FSEventStreamCreate: _FSEventStreamCreate: ERROR: could not open kqueue
2016-05-13 18:32 node[4171] (FSEvents.framework) FSEventStreamScheduleWithRunLoop(): failed assertion 'streamRef != NULL'
```
(there's a bunch of them, perhaps a few hundred)

Some googling led me to this page listing possible fixes for FSEvents on Mac OS X:
http://feedback.livereload.com/knowledgebase/articles/86239-os-x-fsevents-bug-may-prevent-monitoring-of-certai

I tried all of the suggested workarounds, none make the errors go away:
- rebooting the computer
- checking the disk and repairing permissions via Disk Utility
- adding the folder to Spotlight privacy list (the list of folders to not index), and then removing from it, effectively forcing a reindexing
- renaming the folder, and then possibly renaming it back
- re-creating the folder and moving the old contents back into it

Oddly enough, downgrading Node to 5.8.0 resolves the issue. What also works is using the `OldWatchingPlugin` (which I'm going to switch to as a workaround). I've tried upgrading to webpack `2.1.0-beta.7`but that also has the same issue.

I know deep down in webpack internals, [chokidar](https://github.com/paulmillr/chokidar) is used to watch files (right?). I tried running their example.js file in the same project, and that works the way it is supposed to; changes to files are picked up and logged. 

Any ideas what could be wrong? Anything I can do to better debug?

**Comment by trotzig** [comment]
It's likely this is related to or a copy of #2356

**Comment by 0x80** [comment]
No sure if this is related, but with node > 6 webpack continues to take 100% cpu when idle in watch mode. Switching back to node 5 solves it for me. 

Similar results for both with the dev-server and dev-middlware

**Comment by trotzig** [comment]
I'm still seeing this, though less so after upgrading to El Capitan.

**Comment by theandym** [comment]
I'm experiencing this issue as well. I recently bootstrapped a new dev environment on El Capitan 10.11.5. Running the `chokidar` example works fine, but when I attempt to use `webpack-dev-server` changes to files don't trigger rebuilds.

**Comment by sokra** [comment]
Does it work now with the recent node version?

**Comment by trotzig** [comment]
I'll give it a try @sokra. Did something change recently that would potentially make this go away?

**Comment by trotzig** [comment]
I have verified that node 6.5.0 makes this better. I'm not seeing the FSEvents errors any longer. Thanks for circling back @sokra!
