### ISSUE TITLE
[webpack 2] `watch` & System.import compile with new chunk name

### ISSUE THREAD

**Issue by mAAdhaTTah** [webpack/webpack#2490]
I've search high and low; I don't think anyone has reported this yet.

I'm building an application using dynamic code splitting with `System.import`, as detailed [here](https://gist.github.com/sokra/27b24881210b56bbaff7#dynamic-expressions). I've got a build that spits out an entry point (`app.js`) and two chunks (`0.js` & `1.js`). However, when running with `--watch`, if I make a change in one of the dependencies of `0` or `1`, `webpack` rebuilds the chunk with a new name, ouputting a new `3.js` chunk instead of updating the already-built chunks.

Because the main `app.js` chunk hasn't changed, it continues to load the already-emitted chunk `0.js` or `1.js` chunk (depending on the page), so the changes don't actually show up in the loaded scripts.

Here's my `webpack.config.js`:

```js
module.exports = {
    entry: {
        'app': './app.js'
    },
    devtool: 'sourcemap',
    debug: true,
    output: {
        path: './build/',
        filename: '[name].js',
        publicPath: './build/'
    },
    module: {
        loaders: [
            {
                test: /\.js$/,
                loader: 'babel'
            },
            {
                test: /\.hbs$/,
                loader: 'handlebars'
            }
        ]
    },
    resolve: {
        mainFields: ['jsnext:main', 'main']
    },
    plugins: []
};
```

Here's the output:

```bash
± |master {1} U:3 ✗| → webpack --watch
Hash: 101fd3abf438ec13be47
Version: webpack 2.1.0-beta.7
Time: 10508ms
     Asset     Size  Chunks             Chunk Names
      0.js   236 kB       0  [emitted]
      1.js   326 kB       1  [emitted]
    app.js   929 kB       2  [emitted]  app
  0.js.map   291 kB       0  [emitted]
  1.js.map   522 kB       1  [emitted]
app.js.map  1.57 MB       2  [emitted]  app
  [12] ./pages async ^\.\/.*\/controller$ 160 bytes {2} [built]
    + 307 hidden modules

Hash: 824513638c96c8df229c
Version: webpack 2.1.0-beta.7
Time: 603ms
   Asset    Size  Chunks             Chunk Names
    3.js  236 kB       3  [emitted]
3.js.map  291 kB       3  [emitted]
  [12] ./pages async ^\.\/.*\/controller$ 160 bytes {2} [built]
    + 307 hidden modules
```

**Comment by mAAdhaTTah** [comment]
Update: This is reproducible using the examples. Run this in `examples/code-splitting-harmony`:

```bash
node ../../bin/webpack.js --display-reasons --display-chunks --display-modules --display-origins --output-public-path "js/" --output-pathinfo --watch  ./example.js js/output.js
```

And modify either of the files in `node_modules/c` and you'll see new chunks emitted as `4.js` and `5.js`. I first modified `b.js` and saw the same chunk emitted, but modifying `c/1.js` emited the `4.js` and `5.js` chunks without emitting `output.js` again to point to the new chunks.

Output:

```bash
 ± |master U:1 ✗| → node ../../bin/webpack.js --display-reasons --display-chunks --display-modules --display-origins --output-public-path "js/" --output-pathinfo --watch  ./example.js js/output.js
Hash: f465a927aa22e2ad6277
Version: webpack 2.1.0-beta.7
Time: 82ms
    Asset       Size  Chunks             Chunk Names
     0.js  163 bytes       0  [emitted]
     1.js  163 bytes       1  [emitted]
output.js    5.96 kB       2  [emitted]  main
     3.js  155 bytes       3  [emitted]
chunk    {0} 0.js 13 bytes {2} [rendered]
    [3] ./~/c/2.js 13 bytes {0} [optional] [built]
        context element ./2 [1] ./~/c async ^\.\/.*$
        context element ./2.js [1] ./~/c async ^\.\/.*$
chunk    {1} 1.js 13 bytes {2} [rendered]
    [2] ./~/c/1.js 13 bytes {1} [optional] [built]
        context element ./1 [1] ./~/c async ^\.\/.*$
        context element ./1.js [1] ./~/c async ^\.\/.*$
chunk    {2} output.js (main) 427 bytes [rendered]
    > main [4] ./example.js
    [0] ./~/a.js 11 bytes {2} [built]
        harmony import a [4] ./example.js 1:0-18
    [1] ./~/c async ^\.\/.*$ 160 bytes {2} [built]
        System.import context c [4] ./example.js 8:8-34
    [4] ./example.js 256 bytes {2} [built]
chunk    {3} 3.js 11 bytes {2} [rendered]
    > [4] ./example.js 3:0-18
    [5] ./~/b.js 11 bytes {3} [built]
        System.import b [4] ./example.js 3:0-18

Hash: dcc310ee04125e6a380f
Version: webpack 2.1.0-beta.7
Time: 8ms
Asset       Size  Chunks             Chunk Names
 3.js  179 bytes       3  [emitted]
chunk    {2} output.js (main) 427 bytes
    > main [4]
     + 3 hidden modules
chunk    {3} 3.js 34 bytes {2} [rendered]
    > [4] 3:0-18
    [5] ./~/b.js 34 bytes {3} [built]
        System.import b [4] ./example.js 3:0-18

Hash: 87170b4039501c4c1363
Version: webpack 2.1.0-beta.7
Time: 4ms
Asset       Size  Chunks             Chunk Names
 3.js  156 bytes       3  [emitted]
chunk    {2} output.js (main) 427 bytes
    > main [4]
     + 3 hidden modules
chunk    {3} 3.js 12 bytes {2} [rendered]
    > [4] 3:0-18
    [5] ./~/b.js 12 bytes {3} [built]
        System.import b [4] ./example.js 3:0-18

Hash: 399feec7caf804009494
Version: webpack 2.1.0-beta.7
Time: 5ms
Asset       Size  Chunks             Chunk Names
 4.js  163 bytes       4  [emitted]
 5.js  187 bytes       5  [emitted]
chunk    {2} output.js (main) 427 bytes
    > main [4]
    [1] ./~/c async ^\.\/.*$ 160 bytes {2} [built]
        System.import context c [4] ./example.js 8:8-34
     + 2 hidden modules
chunk    {3} 3.js 12 bytes {2}
    > [4] 3:0-18
    [5] ./~/b.js 12 bytes {3} [built]
        System.import b [4] ./example.js 3:0-18
chunk    {4} 4.js 13 bytes {2} [rendered]
     + 1 hidden modules
chunk    {5} 5.js 36 bytes {2} [rendered]
    [2] ./~/c/1.js 36 bytes {5} [optional] [built]
        context element ./1 [1] ./~/c async ^\.\/.*$
        context element ./1.js [1] ./~/c async ^\.\/.*$
```

**Comment by aight8** [comment]
Have exactly the same problem. I first tought it's a problem of webpack-dev-server but the new chunk which is generated by code splitting is generated under a new file name. Dev server recognize the change but don't load the new chunk. On page reload the change isn't appear neither since the old chunk is loaded over and over again. I try it now with the traditional watch mode for now.

**Comment by mAAdhaTTah** [comment]
Are the chunk hashes stable between rebuilds or no? Maybe that's a workaround. What I've been doing in the meantime is just swapping out the dynamic part of the string with the piece I'm working on, but that may not work for everyone.

**Comment by mAAdhaTTah** [comment]
Retested on beta8 and issue remains.

**Comment by sokra** [comment]
Should be fixed now...

**Comment by mAAdhaTTah** [comment]
@sokra Issue remains but output is slightly different on beta12. Now I'm not seeing chunks re-emitted with new filenames, but I'm not seeing the changed file actually emitted.

**Comment by sokra** [comment]
hmm... running the webpack example as described above works fine for me now.

Does this only happen on your codebase or still on the webpack example?

**Comment by mAAdhaTTah** [comment]
It is happening on my codebase. I haven't checked the example yet.

**Comment by mAAdhaTTah** [comment]
More info: it works fine after modifying the direct dependency. In my case, I have a `System.import(controller).then(controller => controller(init));` and any changes in the controller were updated. However, the controller's dependencies, when changed, were not emitted.

This would suggest the example _should_ work fine, but that it isn't complex enough to capture the issue.

**Comment by impl** [comment]
Hi!

I think I've solved this issue (I was also experiencing it in my large codebase, but can't reproduce it in a test yet -- hence the comment instead of a PR). Here's the relevant patch against `cf00a1a`:

```diff
diff --git a/lib/ContextModule.js b/lib/ContextModule.js
index 92fd066..33f566e 100644
--- a/lib/ContextModule.js
+++ b/lib/ContextModule.js
@@ -5,7 +5,7 @@
 var Module = require("./Module");
 var OriginalSource = require("webpack-sources").OriginalSource;
 var RawSource = require("webpack-sources").RawSource;
-var DependenciesBlock = require("./DependenciesBlock");
+var AsyncDependenciesBlock = require("./AsyncDependenciesBlock");
 
 function ContextModule(resolveDependencies, context, recursive, regExp, addon, async) {
 	Module.call(this);
@@ -80,12 +80,13 @@ ContextModule.prototype.build = function(options, compilation, resolver, fs, cal
 			});
 		}
 		if(this.async) {
-			this.blocks = dependencies && dependencies.map(function(dep) {
-				var block = new DependenciesBlock();
-				block.parent = this;
-				block.dependencies = [dep];
-				return block;
-			}, this);
+			if(dependencies) {
+				dependencies.forEach(function(dep) {
+					var block = new AsyncDependenciesBlock(null, dep.module, dep.loc);
+					block.addDependency(dep);
+					this.addBlock(block);
+				}, this);
+			}
 		} else {
 			this.dependencies = dependencies;
}
```

I *think* the problem is that chunks were being retained across rebuilds. As a result, they weren't being re-added to the compilation chunk list [here](https://github.com/webpack/webpack/blob/ce76858334c47ec2ae08b6a9036e78fb31559333/lib/Compilation.js#L621-L633). `AsyncDependenciesBlock` removes the chunks on disconnect, fixing the problem.

This also fixed webpack/extract-text-webpack-plugin#188 for me.

**Comment by mAAdhaTTah** [comment]
Nice! If that does work, hope it gets integrated soon. The best I can do in terms of a reproducible test case would be to update the `example/code-splitting-harmony` to import a subdependency and see if I can reproduce it there.

**Comment by TheLarkInn** [comment]
@impl Would you mind submitting a PR for this? (If this is still a problem in 2.1.0-beta.14)

**Comment by impl** [comment]
I opened a PR for you, #2714. I still haven't had time to make a test case but I've been running this code for a week now and it's been working fine.

**Comment by mAAdhaTTah** [comment]
That PR appears to have resolved it for me. Thanks for the fix @impl.

**Comment by TheLarkInn** [comment]
Thank you @impl !!!!
