### ISSUE TITLE
A loader's test function disregards other settings, like include or exclude

### ISSUE THREAD

**Issue by dnutels** [webpack/webpack#2491]
So, I need to pass some files through some processing (book-keeping), without modifying them, and my idea was to use **a loader** to just pass them through, while processing them in some manner.

I was planning on writing a loader that would do that, and in the process stumbled upon this:

```
const PATH = require('path');

const webpack = require('webpack');

const APP_FOLDER = PATH.resolve(__dirname, 'src/');
const APP_ENTRY_FILE = PATH.resolve(APP_FOLDER, 'index.js');

const BUILD_FOLDER = PATH.resolve(__dirname, 'dist/');

const NODE_MODULES = PATH.resolve(__dirname, 'node_modules/');

module.exports = {
    entry: {
        app: [APP_ENTRY_FILE]
    },
    output: {
        path: BUILD_FOLDER,
        filename: '[name].js'
    },
    module: {
        loaders: [
            {
                test: (path) => {
                    console.log(path);
                    return true;   
                }, 
                exclude: [NODE_MODULES],
                loader: 'raw'
            },
            {
                test: /\.js$/, include: [APP_FOLDER], loader: 'babel',
                query: {compact: false, cacheDirectory: true}
            }
        ]
    },
    plugins: [     
        new webpack.NoErrorsPlugin()
    ]
};

```

**My expectation was that only files that satisfy `exclude` (i.e. not in `node_modules` folder), would get processed through the `test` function** and, consequently, `raw-loader`.

Alas. All files, **regardless of combinations of `include` and `exclude`** are passed through.

Is this the expected behavior and `test` function is expected to implement `include` and `exclude`?

**Comment by bebraw** [comment]
Can you try against webpack 2 beta?
