### ISSUE TITLE
Creating errors with webpack plugin doesn't work in after-emit with async

### ISSUE THREAD

**Issue by MikaAK** [webpack/webpack#2492]
I've created a plugin that uploads to s3 and i'm noticing errors don't get emitted from the upload if it should fail. After some debugging i am seeing the errors are correctly getting passed to `compilation.errors.push(error)` but they don't display. Is there some limit to how errors are displayed? The relevant code is [here](https://github.com/MikaAK/s3-plugin-webpack/blob/master/src/s3_plugin.js#L105), where the errors from the `then` do not emit.

**Comment by bebraw** [comment]
Is this relevant still?
