### ISSUE TITLE
Feature Request: UglifyJsPlugin that processes individual files

### ISSUE THREAD

**Issue by UnsungHero97** [webpack/webpack#2493]
The current implementation of `webpack.optimize.UglifyJsPlugin` works only on entire chunks, not on individual files. As such, the plugin won't skip individual dependencies, for example, an already minified library. This is already known: https://github.com/webpack/webpack/issues/1079

My specific use case is that I have a dependency on a library that is generated by [emscripten](https://github.com/kripken/emscripten), which is already uglified. It doesn't need to be processed a second time by `UglifyJs`. As a side effect, the fact that the plugin has to process the already uglified library (and others) triples wepback's build time.

It'd be really nice to have the plugin run on a more granular level, that is, on individual files (modules?) instead of chunks. If that's not something on the roadmap, or not high enough of a priority, I'd appreciate a pointer on how to write a plugin to do this. More specifically, where in the compilation process should I run `UglifyJs`? Am I headed in the right direction with the following?

```
compilation.plugin('optimize-modules', function(modules) {
  modules.forEach(function(module) {
    try {
      // this is pretty much a copy of what UglifyJsPlugin does, minus source maps
      var ast = uglify.parse(module._source.source());

      if(options.compress !== false) {
        ast.figure_out_scope();
        var compress = uglify.Compressor(options.compress);
        ast = ast.transform(compress);
      }

      if(options.mangle !== false) {
        ast.figure_out_scope();
        ast.compute_char_frequency(options.mangle || {});
        ast.mangle_names(options.mangle || {});
        if(options.mangle && options.mangle.props) {
          uglify.mangle_properties(ast, options.mangle.props);
        }
      }

      var output = {};
      output.comments = Object.prototype.hasOwnProperty.call(options, "comments")
        ? options.comments
        : /^\**!|@preserve|@license/;
      output.beautify = options.beautify;
      for(var k in options.output) {
        output[k] = options.output[k];
      }

      var stream = uglify.OutputStream(output);
      ast.print(stream);
      stream = stream + "";
      module._source = new RawSource(stream);

    } catch(e) {
      // handle exception
    }
  });
});
```

(Note: this feature request is related to a previous question I posted here: https://github.com/webpack/webpack/issues/2082)

**Comment by sasha240100** [comment]
Any updates on this topic?

**Comment by UnsungHero97** [comment]
@sasha240100 I gave up on the idea of writing a plugin to do this, and I haven't heard anything new on this topic.

**Comment by sasha240100** [comment]
@UnsungHero97 I use compiled ammo.js in my library and i don't want to uglify it. How can i do this?

**Comment by icai** [comment]
I agree this, if someone use multi entry

```javascript
 entry: {
	    "mylib": "./mylib.js",
	    "mylib.min": "./mylib.js",
},
```
`mylib` need to concat and beautify, but `mylib.min` need to concat and compress

**Comment by cgatian** [comment]
@icai that's not a very webpackish way to do it.  Most of the configuration plugins involve passing an array of regex or entries.

A syntax like this seems more correct.
new UglifyJsPlugin([
    'mylib.min'
]);

I

**Comment by bebraw** [comment]
Have you seen [uglify-loader](https://www.npmjs.com/package/uglify-loader)?
