### ISSUE TITLE
Does webpack 2.1-beta not support a profiler?

### ISSUE THREAD

**Issue by EdwardDrapkin** [webpack/webpack#2500]
I can find documentation anywhere and it seems my usual --profile flag doesn't work any more.

**Comment by sokra** [comment]
Should still work?

**Comment by salzhrani** [comment]
I am facing a simialr problem, this is the output I get.
```json
{
  "errors": [],
  "warnings": [
    "./~/jsondiffpatch/src/main.js\n48:20 Critical dependency: the request of a dependency is an expression",
    "./~/jsondiffpatch/src/main.js\n53:19 Critical dependency: the request of a dependency is an expression"
  ]
}
```

**Comment by salzhrani** [comment]
any update?

**Comment by sokra** [comment]
looks like a problem with the stats options. You didn't pass any option to the `stats` option, did you?

**Comment by salzhrani** [comment]
command used
```
webpack --config internals/webpack/webpack.prod.babel.js --profile --json > stats.json
```
based off https://github.com/mxstbr/react-boilerplate

**Comment by sokra** [comment]
https://github.com/mxstbr/react-boilerplate/blob/master/internals/webpack/webpack.base.babel.js#L85

`stats: false`

this disables all stat info.

**Comment by salzhrani** [comment]
it is set to `false` while displaying stats ... this is run on `2.1.0-beta.15`
on `2.1.0-beta.22` `stats.json` is blank. not sure where to go from here.
