### ISSUE TITLE
Misleading message when module-hot-reload fails

### ISSUE THREAD

**Issue by fab1an** [webpack/webpack#2501]
I found out this, unfortunately I don't have time to reproduce a test-case now:

Working case: `A.js` depends on `B.js`
When I change `A.js` it's replaced, when I change `B.js` it's replaced as well.

Now when I add a not hot-reloadable dependency `C.js` depends on `B.js` and I change `B.js` i get the message that it can be hot-reloading because it's module isn't accepted, when in reality `C.js` is the problematic module.

**Comment by sokra** [comment]
We could add all parent modules to the message.

**Comment by fab1an** [comment]
I think that would help in many bugreports!

**Comment by fab1an** [comment]
Thanks.
