### ISSUE TITLE
Plugin errors are surpressed

### ISSUE THREAD

**Issue by jescalan** [webpack/webpack#2504]
I feel like perhaps someone has already pointed this out somewhere, but I did honestly look and couldn't find anything so here goes. Apologies if it has, and shame on me!

Here's the use case. I make a plugin for webpack and load it up. Somewhere in that plugin, something throws an error. Webpack silently stalls out indefinitely and does not report any error.

The only solution I've been able to find so far is to wrap the entirety of every plugin in a `try/catch` statement, but this seems absurd. I feel like there must be a spot in the code where user-provided plugins are executed, and that one line could be wrapped in a try/catch and the error could be properly reported through webpack. If this is possible and a maintainer is ok with it, I'd be happy to take a stab at a pull request, would just need a push in the right direction as the codebase is absolutely enormous and mostly undocumented.

💖

**Comment by sokra** [comment]
Could you post an simple example where this happens?
