### ISSUE TITLE
peerDependencies with webpack

### ISSUE THREAD

**Issue by nsisodiya** [webpack/webpack#2505]
Ex - I have a project `A` which is dependent on `react`. project `B` is dependant on project `A`. project `C` is dependant on `B`.

react is peerDependencies for project A. So when I create bundle for project `A`, I do not want to include react in the bundle.

`A` is peerDependencies for project B. So when I create bundle for project `B`, I do not want to include `A` in the bundle.

`B` is peerDependencies for project C. So when I create bundle for project `C`, I do not want to include `B` in the bundle.

Project A,B,C are using webpack. Project A, B are published on npm. Project A, B and C has demo folders too. 
Now problem start here.
I want to build Project A which do not have dependency so I am adding react in webpack external config. But at the same time Project A has code for demo too. So I want to use `include` react for demo purpose !
same problem with other Project  B and C.

Please guide me.

**Comment by bebraw** [comment]
What if you fix React version as a `devDependency` for demo purposes? It should resolve as you expect then.

**Comment by nsisodiya** [comment]
@bebraw I do not understand !
I have one webpack configuration. which has two entry points. One entry is library itself.
another entry point is 

```json
{
entry: {
    "ReactComponents": "./src/index.js",
    "external": "./example/external.js"
  },
externals: {
    "@nsisodiya/flux": {
      commonjs: "flux",
      commonjs2: "flux",
      amd: "name",
      root: "name"
    },
    "react": {
      commonjs: "react",
      commonjs2: "react",
      amd: "React",
      root: "React"
    },
    "react-dom": {
      commonjs: "react-dom",
      commonjs2: "react-dom",
      amd: "ReactDOM",
      root: "ReactDOM"
    }
  }
}
```

first entry point is the library itself. because I have added externals in webpack config, react is not including the both entry points. second entry point belongs to demo. which look like this

`/example/external.js`

```js
import React from "react";
import ReactDom from "react-dom";
console.error(React);
//Register Globally
window.React = React;
window.ReactDom = ReactDom;
```

So the problem is here. I want external libraries not to be included in first entry point and to be included in second entry point because it belongs to demo where `ReactComponents.min.js` require these libraries as global !

**Comment by bebraw** [comment]
I think you are going to need separate configuration for demo. You could return an array of configurations and omit that React externals configuration for it there.

**Comment by nsisodiya** [comment]
multiple configuration , means multiple webpack-dev-server instance ?
I will try to do it and respond here !

**Comment by bebraw** [comment]
I mean

```javascript
module.exports = [{...}, {...}];
```

I guess **webpack-dev-server** should pick that up.
