### ISSUE TITLE
"You may need an appropriate loader to handle this file type"

### ISSUE THREAD

**Issue by jogjayr** [webpack/webpack#2507]
I have SVG icons, which I would like to inline into my application using the raw-loader. I also have SVG fonts, for which I want to use file-loader. Here's the relevant portion of my loaders.js:

    {
      test: /\.svgico/,
      exclude: /node_modules/,
      loader: 'raw'
    },
    {
      test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
      loader: fileLoader
    },

As you can see, I've named my SVG icons with the file extension `.svgico` to distinguish them from the icon fonts. The specific extension doesn't matter; I've also tried `.ico.svg` and even (just for the hell of it) `.svg2` and `.sgv`.

I import the SVG in my JS using:

    require('component_located_in_node_modules/path/to/svg/theicon.svgico');

**Expected**:

raw-loader is used for `.svgico`, file-loader is  used for `.svg` files.

**Actual**:

    Module parse failed: <proj_dir>/node_modules/path/to/icon/theicon.svgico Line 1: Unexpected token <
    You may need an appropriate loader to handle this file type.
    | <?xml version="1.0" encoding="UTF-8" standalone="no"?>
    | <svg width="10px" height="21px" viewBox="0 0 10 21" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">

**Notes**:

* As you can see, the file itself is being loaded (it's printing out the first few lines of the icon SVG file)
* I tried putting a console.log into raw-loader/index.js; it's never called
* I tried using the (I think, undocumented) function form of the loader test:

      ```
test: function(filename) {
        return filename.endsWith('.svgico')
}
    ```
  and confirmed that it's only matching the icon SVG files. Doesn't work

* Specifying the loader inline in the require statement works. Example:
    
    ```
    require('raw-loader!'component_located_in_node_modules/path/to/svg/theicon.svgico')
    ```

* I actually started out trying to use `svg-as-symbol-loader` configured with `tag=svg`. This used to work until yesterday but mysteriously broke today.
* I saw this (https://gist.github.com/sokra/27b24881210b56bbaff7#loaders-configuration) after creating the issue and it seems familiar. Is there already an issue discussing this? I've searched for "svg" in the issues (open and closed) and not found anything (though there's 95 issues total, so I could easily have missed it).

**Comment by langpavel** [comment]
Do you really `exclude` what you want to process via loader :question:
```js
{
  test: /\.svgico/,
  exclude: /node_modules/, // really?
  loader: 'raw'
},
```

**Comment by jogjayr** [comment]
@langpavel I thought the `exclude` property meant "exclude if the require is under node_modules". Is my understanding wrong?

I'm doing the require itself outside of `node_modules`.
