### ISSUE TITLE
webpack help message was truncated in node 6

### ISSUE THREAD

**Issue by qiu8310** [webpack/webpack#2511]
![image](https://cloud.githubusercontent.com/assets/1094697/15363804/8eb8e284-1d4c-11e6-9f10-08c60b6819a8.png)

And I found the [official node manual](https://nodejs.org/api/process.html#process_process_exit_code) not recommend to use:
```
if (someConditionNotMet()) {
  printUsageToStdout();
  process.exit(1);
}
```
I think this is the reason why the help message was truncated.

**Comment by qiu8310** [comment]
Sorry, I found you are using yargs, maybe this is yargs problem.

**Comment by owcc** [comment]
I have the same problem too

**Comment by sokra** [comment]
We need to upgrade the yargs version. Do you want to do a PR?

**Comment by qiu8310** [comment]
Ok, I will try it night.

**Comment by qiu8310** [comment]
I update the yargs to 4.7.1, it works well; but there are 6 failings test in my mac, should I PR this ?

**Comment by rbartoli** [comment]
@sokra I've noticed the same, there are 6 failing tests after cloning the project. Any idea?

**Comment by sokra** [comment]
run this in the cloned repo:

``` js
npm link
npm link webpack
```

**Comment by rbartoli** [comment]
@sokra thanks it did the trick. I'll submit another PR with those 2 commands added to https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md
