### ISSUE TITLE
How to disable "use strict" in webpack 2?

### ISSUE THREAD

**Issue by isergey** [webpack/webpack#2512]
With "use strict" ExtJS do not work...
In webpack 2.1.0-beta.6 "use strict" not append to file by default, but in 2.1.0-beta.7 "use strict" append by default.

**Comment by TriMoon** [comment]
You should post an example of your usage where it doesn't work, so we can find out what the exact cause is of the problem you face....

**Comment by isergey** [comment]
It is my config:
```javascript
  webpack({
      node: {
        fs: 'empty'
      },
      devtool: RELEASE_MODE ? 'hidden-source-map' : 'cheap-eval-source-map',
      watch: watch,
      devtool: 'source-map',
      context: srcScripts,
      entry: {
        index: './index.js',
      },
      output: {
        path: path.join(distScripts),
        filename: '[name].js',
        sourceMapFilename: '[file].map'
      },
      plugins: plugins,
      module: {
        preLoaders: [
          {
            test: /\.jsx?$/,
            loader: 'source-map-loader'
          }
        ],
      },
      resolve: {
        modules: [srcScripts, 'node_modules'],
        extensions: ['.js'],
      }
    },
    function (err, stats) {
      if (err) {
        throw new gutil.PluginError('webpack', err);
      }
      browserSync.reload();
      gutil.log('[webpack]', stats.toString({
        chunks: false
      }));
    });
```

When I updated Webpack from 2.1.0-beta.6 to 2.1.0-beta.7, my app broke. I compare generated codes and saw the difference with "use strict". In 2.1.0-beta.7 add by default. May be exist cofiguration parameter to control adding "use strict" (UseStrictPlugin eg)?

**Comment by sokra** [comment]
v2 doesn't add it by default. It only adds it to ES6 modules (spec). Which module is breaking? Could you paste a link to the relevant file.

**Comment by isergey** [comment]
I create test repo https://github.com/isergey/wptest
Clone and install depenedesies. Then **npm run build**.
After build **npm i --save-dev webpack@2.1.0-beta.6** and then **npm run build** again.

Gist to bundle.js of webpack@2.1.0-beta.6 https://gist.github.com/isergey/87d264b1204619b9b49e7a2179eb7df6

Gist to bundle.js of webpack@2.1.0-beta.7 https://gist.github.com/isergey/04523459d7f2a92683fbeb9cf948cda0

**Comment by isergey** [comment]
I think the problem in this commits
https://github.com/webpack/webpack/commit/e83e9b8c233e465e05850f26813c943efce96f83
https://github.com/webpack/webpack/commit/b98debb80970643ddc848344ac92ae1be4f99643

**Comment by TriMoon** [comment]
Not entirely true imho, i think they needs to change where they inserts the ``"use strict";`` string.
But, if you ask me, they should completely drop adding that at all and leave it to the user of webpack to add that statement.
All they needs to do, if they want to do it correctly (IMHO) is to check the source-code for either ``"use strict";`` **or** ``'use strict';`` because only the string is important not the quotation marks used. ([see MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode#Invoking_strict_mode))
When they find that string, they need to set the strict flag in their code and propagate it downwards.
(If they want to keep track of it for any reason, like they seem to do in e83e9b8c233e465e05850f26813c943efce96f83)

_(I use <b>they</b> above to indicate the webpack coders, not anyone in particular in this debate...)_

**Comment by sokra** [comment]
webpack behaves fine here. At least in your test repo.

The ES6 spec imply strict mode when using ES6 modules. So when you use `import` or `export` strict mode is automatically activated.

See also: http://stackoverflow.com/a/29285330/2260535

**Comment by trusktr** [comment]
@sokra 

> v2 doesn't add it by default. It only adds it to ES6 modules (spec).

I am passing code to Webpack 2 that looks like the following, which is not ES6 module format:

```js
var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};
var _UiCore_1 = require("@UiCore");
function main() {
    // Yay, we can use ES6 classes!
    var App = (function (_super) {
        __extends(App, _super);
        function App() {
            return _super !== null && _super.apply(this, arguments) || this;
        }
        App.prototype.initialize = function (options) {
            this.uiApplication = 'sticker_creator';
            this.uiContextName = 'app';
            _super.prototype.initialize.call(this, options);
            this.addToDOM();
        };
        return App;
    }(_UiCore_1.UiContext));
}
main();
```

However Webpack still adds `use strict` to it:

```js
/* 1 */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};
var _UiCore_1 = __webpack_require__(0);
function main() {
    // Yay, we can use ES6 classes!
    var App = (function (_super) {
        __extends(App, _super);
        function App() {
            return _super !== null && _super.apply(this, arguments) || this;
        }
        App.prototype.initialize = function (options) {
            this.uiApplication = 'sticker_creator';
            this.uiContextName = 'app';
            _super.prototype.initialize.call(this, options);
            this.addToDOM();
        };
        return App;
    }(_UiCore_1.UiContext));
}
main();


/***/ })
```

Is this a bug?

**Comment by sokra** [comment]
It doesn't do that for me:

``` js
/* 1 */
/***/ (function(module, exports, __webpack_require__) {

var __extends = (this && this.__extends) || function (d, b) {
    for (var p in b) if (b.hasOwnProperty(p)) d[p] = b[p];
    function __() { this.constructor = d; }
    d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
};
var Utils = __webpack_require__(0);
function main() {
    // Yay, we can use ES6 classes!
    var App = (function (_super) {
        __extends(App, _super);
        function App() {
            return _super !== null && _super.apply(this, arguments) || this;
        }
        App.prototype.initialize = function (options) {
            _super.prototype.initialize.call(this, options);
            this.blah();
        };
        return App;
    }(Utils.BaseApp));
}
main();

/***/ })
```

**Comment by seeden** [comment]
This issue is only on windows
