### ISSUE TITLE
webpack: how to ordering dependencies between entries

### ISSUE THREAD

**Issue by Trispa** [webpack/webpack#2513]
in my webpack config file I have two multy entries:

```
module.exports = {
      entry:{
             lib:["./scripts/file1.js","./scripts/fil2.ts"],
             app:["./scripts/login.js","./public/HSplitLayout.js"]
      },
      output: {
        path: 'builds',
        filename: '[name].js',
        publicPath: 'builds/',
        libraryTarget: "var"
    }
}
```
I want to ensure that the lib.js file is completely loaded before app.js is loaded.

Thank you for your help

**Comment by megakoresh** [comment]
Just put `<script src="lib.js"/>` before `<script src="app.js" />` in your page...

**Comment by Trispa** [comment]
thanks @megakoresh  i did that and it work well now
