### ISSUE TITLE
ArrayMap comparator issue

### ISSUE THREAD

**Issue by jescalan** [webpack/webpack#2515]
Ok so this issue is really strange, I'll try to explain it clearly but let me know if I failed.

I am using the `compilation.addEntry` method to inject a dependency into webpack's pipeline for a plugin I'm working on. In order to do this correctly, you need to create a `Dependency` using one of the many lovely classes you can require out of the `webpack/lib/dependencies` folder. Basically the signature looks like this:

```js
const SingleEntryDependency = require('webpack/lib/dependencies/SingleEntryDependency')

function apply (compiler) {
  compiler.plugin('make', function (compilation, done) {
    const dep = new SingleEntryDependency('./path/to/file')
    compilation.addEntry(compiler.options.context, dep, 'name')
    done()
  }
}
```

Now, if you require the `SingleEntryDependency` from the same webpack source that you use to then run the compile, this will work perfectly fine. However, if you require it from a different instance of webpack (for example, if a plugin has webpack as a dependency so it can require the `SingleEntryDependency`, but the plugin is simply added to the config of your local webpack which runs the compile), it fails, saying it could not find a module factory for the type `SingleEntryDependency`.

I dug into this a little further and found that it is happening [here](https://github.com/webpack/webpack/blob/master/lib/Compilation.js#L345). It didn't seem to me at first like anything should be going wrong, it simply takes the constructor from the dependency and matches it from an `ArrayMap` of all the valid dependency types.

**But** it turns out the issue is with the comparison. In the `ArrayMap` implementation [here](https://github.com/webpack/webpack/blob/master/lib/ArrayMap.js#L13), the constructors make their way into this comparison. When they come from the same webpack instance, they match and all goes well. When they come from different instances, however, crash and burn. This led me to believe that when comparing two functions using `===`, internally it must be looking for an exact match of the function instance. I verified this by adding `.toString()` to the end of each comparator, and indeed this fixed the problem -- webpack matched the constructors and everything compiled perfectly well.

However, when I ran the test suite with my `.toString()` patch, 6 tests failed. That being said, the same 6 tests also failed when I ran the test suite without my patch, so I'm inclined to believe that it's not actually breaking anything. I'm going to submit a PR in a moment so that you can see exactly what I'm talking about, but open to any feedback/direction on this one!

Thanks for taking the time to read this huge novel 💖

**Comment by sokra** [comment]
The hard comparison is intended. You should not include multiple copies of webpack. That could behave weird. Try to always require the same webpack thing. Install webpack locally.

**Comment by jescalan** [comment]
@sokra for this use case, how is that possible? If I release a plugin that wants to use one of webpack's dependency types, how could that plugin pull the dependency from whatever copy of webpack is running the compilation?

**Comment by andreypopp** [comment]
@jescalan add webpack as a peer dependency, users of the plugin already have webpack installed and so you only need to pin compatible webpack version and not install it.
