### ISSUE TITLE
Show in output module sizes after minifying with uglyfy

### ISSUE THREAD

**Issue by aight8** [webpack/webpack#2519]
Furthermore the current filesize beside the modules is the raw file size.
- Not minified
- Without tree shaking reduction

**Comment by sokra** [comment]
Good idea, but difficult to do. We need to parse the generated output and read sizes from AST.

**Comment by th0r** [comment]
That's exactly what [bundle analyzer](https://github.com/th0r/webpack-bundle-analyzer) does.
I think it would be nice to have it built into Webpack and I can help with it. 
@sokra What do you think?
