### ISSUE TITLE
webpack's resolve.alias doesn't seem to work for 3rd party modules

### ISSUE THREAD

**Issue by bbottema** [webpack/webpack#2520]
I'm trying to make npm [ng2-prism](https://github.com/tpadjen/ng2-prism) work with [angular2-seed](https://github.com/angular/angular2-seed), but it has an issue importing _angular2/http_, which as we know have recently been [rescoped into @angular](https://www.reddit.com/r/Angular2/comments/4hk0f8/the_angular2_team_is_changing_the_repository_on/).

However, I would have thought that the aliases in webpack's config would solve these, but for some reason it's not picking up the alias.

Here's the config, which is unchanged from the seed.

vendor.ts - this is the only file I modified to add ng2-prism to the vendor bundle

    // Angular 2
    import '@angular/platform-browser-dynamic';
    import '@angular/platform-browser';
    import '@angular/core';
    import '@angular/http';
    import '@angular/router-deprecated';
    
    import 'ng2-prism';

The import in ng2-prism's source code is straightforward (codeblock.component.d.ts:1:66):

    import { AfterViewChecked, AfterContentChecked, ElementRef } from 'angular2/core';

The alias configured in webpack.config.js

    (...)
    resolve: {
        root: [ path.join(__dirname, 'src') ],
        extensions: ['', '.ts', '.js', '.json', '.css', '.html', '.less'],
        alias: {
         (...),
          'angular2/core': path.join(__dirname, 'node_modules', '@angular', 'core', 'index.js'),
         (...)
        }
      },
    (...)

Logging the result indicates it found the correct absolute folder to resolve the alias to.

The error I'm getting on _npm start_:

> ERROR in [default] C:/workstation/simple-java-mail/src/main/webapp/node_modules/ng2-prism/src/codeblock.component.d.ts:1:66 
> Cannot find module 'angular2/core'.

Ofcourse [ng2-prism should update its dependencies](https://github.com/tpadjen/ng2-prism/issues/4), but this is a situation we will run into sooner or later with one library or another. 

But I don't see a reason why the import can't be resolved. What am I missing?

**Comment by sokra** [comment]
The error message seems to come from your typescript loader, not from webpack itself. You probably need to ask there.
