### ISSUE TITLE
Hash-based compilation cache?

### ISSUE THREAD

**Issue by evanw** [webpack/webpack#2526]
I'm running into huge build time issues with webpack. We're using a combination of TypeScript, CoffeeScript, and SCSS. I've tried poking around with disabling source maps and other stuff but it seems like the core issue is that the compilers for these languages are just slow. If I understand correctly, all of these languages have the property where the individual files can be compiled independently and the result will still be valid. Given this 1:1 mapping property it seems like webpack could build much faster with a plugin that maintains a content-addressed map of original files to compiled files on the file system and avoids rebuilding files that haven't changed (using webpack's in-memory watch functionality doesn't work for our use case). However I can't see any documentation about something like this, I can't find a plugin that does this, and I don't see any obvious way of building a plugin like that after poking around in the webpack source code for a bit. Is this something that could be made to work with webpack? Even better, does it already exist?

**Comment by nertzy** [comment]
This looks like a duplicate of #250

**Comment by evanw** [comment]
👍 we built our own version of webpack to get around this, so this is no longer an issue for us.
