### ISSUE TITLE
[QUESTION] Multiple "HMR ..." console outputs if >1 file in webpack.config.js entry?

### ISSUE THREAD

**Issue by rublev** [webpack/webpack#2527]
This is what I have at the top of my `webpack.config.js`, I'm wondering if this is desired output and if it is, why? Maybe I'm not understanding something fundamental about HMR/webpack.

![image](https://cloud.githubusercontent.com/assets/470273/15440649/ab43dfcc-1ea4-11e6-8b69-6a9f08dc5af7.png)

```
const PATHS = {
	app: path.join(__dirname, 'app'),
	test: path.join(__dirname, 'app', 'test.css'),
	style: [
		path.join(__dirname, 'app', 'main.css')
	],
	build: path.join(__dirname, 'build'),
};

const common = merge(
	{
		entry: {
			app: PATHS.app,
			style: PATHS.style,
			test: PATHS.test
		},
		output: {
			path: PATHS.build,
			filename: '[name].js'
		},
		resolve: {
			extensions: ['', '.js', '.jsx']
		},
		plugins: [
			new HtmlWebpackPlugin({
				title: 'Webpack demo'
			})
		]
	}
);
```

**Comment by bebraw** [comment]
I think this is by design. webpack-dev-server seems to create a client per each `entry`. Here's the relevant code https://github.com/webpack/webpack-dev-server/blob/a77eac516dace7f5072740206eda474a8141055b/bin/webpack-dev-server.js#L248 .
