### ISSUE TITLE
Thoughts on dynamic resource loading progress indicator 

### ISSUE THREAD

**Issue by biblesyme** [webpack/webpack#2531]
i want webpack could do
```
var xhr =  require.ensure([],function(require){
   require('a.js')
   require('b.css')
})
xhr.on('progress',function(evt){
//show progress
})
```

i want load every async resouces through ajax,and i could inject 'progress' listener to show progress indicator .  is there any way to do this?

**Comment by bebraw** [comment]
Not in webpack 1. Webpack 2 supports `System.import`. It's a promise based interface. That allows you to track progress on file level.
