### ISSUE TITLE
local loaders in web_loaders folder are no longer recognised by webpack 2.x

### ISSUE THREAD

**Issue by sudsy** [webpack/webpack#2532]
Hi There,

I have found that when migrating my configuration from webpack 1.x to webpack 2.x, the local loaders that I have placed in the web_loaders folder can not be found.

Is this something that you want to support in webpack 2 or is there a different approach. I have tried a few different ways and browsed through the test cases but can't find any indication that this is a supported configuration.

In trying to work around this, I have also tried using a relative path to the loader with no luck either.

If it is something you want to support I can see if I have time to contribute a PR if you would like one.

**Comment by sokra** [comment]
The default resolve paths were changed for webpack 2. Less paths means more performance, so I tried to minimize the default paths. The default is now only `["node_modules"]`.

This configuration should give you the desired experience:

``` js
resolveLoader: {
  modules: ["node_modules", "web_loaders"]
}
```

or even more performant:


``` js
resolveLoader: {
  modules: [
    "node_modules",
    path.resolve(__dirname, "web_loaders")
  ]
}
```

**Comment by sudsy** [comment]
Right you are! Thanks
