### ISSUE TITLE
nodejs api compiler.watch should come with `buildStart` optional callback

### ISSUE THREAD

**Issue by plantvsbirds** [webpack/webpack#2534]
`https://webpack.github.io/docs/node.js-api.html`

Now when you call `compiler.watch`, there's only a callback when building is done.
I think there should be an optional callback when build starts, so that people can output things to terminal or do some cleanup in the callback.
One good reason to have this is when the build is extremely long, there's no immediate feedback until the build is done

**Comment by sokra** [comment]
You can write plugins which does hook into these places. I think this should be enough.

``` js
compiler.plugin("watch-run", function(compiler, callback) {
  callback();
});
```
