### ISSUE TITLE
When can I except the release of webpack 2

### ISSUE THREAD

**Issue by adithyan** [webpack/webpack#2536]
I really excited about the new webpack 2, I don't want to use the beta in to my production
do u have any time line for the release?

**Comment by dmr** [comment]
Is there a list of pending release blocker issues?

**Comment by TheLarkInn** [comment]
I don't believe we have a blocking tag, however the issues labeled 'webpack2' and 'bug' is a great place to start.

**Comment by shubhamsizzles** [comment]
Aren't there always going to be bugs? When does it become stable enough for release?

**Comment by bebraw** [comment]
Closing in favor of #1545.
