### ISSUE TITLE
Specifying a salt for bundle/chunk hashes?

### ISSUE THREAD

**Issue by kmck** [webpack/webpack#2544]
I don't see it in the docs, and from skimming the source, it doesn't seem like there's a configuration option anywhere either. Is there a straightforward way to do this?

**Comment by heylookltsme** [comment]
bump. I also need this.

**Comment by enapupe** [comment]
this feature just saved my ass! 
some users cached files with wrong encoding so my only option was changing file names.

webpack rocks! thanks
