### ISSUE TITLE
ES6 minify / uglify

### ISSUE THREAD

**Issue by damianobarbati** [webpack/webpack#2545]
I'm pretty sure this is a duplicate, but I couldn't find another already open issue about it.

I'd like to not transpile my es6 code with babel to es5 before uglifying it: I'd rather use a minified es6 version of my codebase.
Is there any uglifier production-ready/webpack-ready for this?

Watching in the meantime:
https://gist.github.com/avdg/43002267f959210a69aa3ec0f21ed751

**Comment by bebraw** [comment]
The problem is that UglifyJS doesn't support ES6 yet so it's not possible to avoid that transformation yet. You can follow the progress at https://github.com/mishoo/UglifyJS2/issues/448 .

**Comment by Kitanotori** [comment]
Even though ES6 support for UglifyJS is still under development, I would like to know how to force Webpack to use a custom version of UglifyJS, such as [the Harmony branch](https://github.com/mishoo/UglifyJS2/tree/harmony). Is there an easy way to do this with npm?

Btw, this seems to be related to https://github.com/webpack/webpack/issues/1471.

**Comment by bebraw** [comment]
I can see two options:

1. Fork webpack and point `uglifyjs` dependency to the branch.
2. Extract the UglifyJs plugin from the project and point that to the branch.

I'm not actually sure why UglifyJS plugin is at the core level as it could easily be a package of its own. Extra dependency to manage then, though.

**Comment by sidjain26** [comment]
+1 for removing UglifyJS from the core level.

**Comment by sidjain26** [comment]
Or you could use `npm shrinkwrap` and modify the version to the harmony branch under the `webpack` dependency in the `npm-shrinkwrap.json` created. If you still want to keep webpack as dev dependency add it to your `.gitignore`. This might throw a non fatal error while updating via `npm version` (if you maintain an npm package).

**Comment by bebraw** [comment]
FYI, there's a Babel specific minifier these days. See https://github.com/boopathi/babili-webpack-plugin .

**Comment by sidjain26** [comment]
@bebraw I tried it in my project earlier, it produces unexpected results without any warnings. Same with uglifyjs2 but that happens less often than babili. Someone needs to write a bulletproof es6 minifier

**Comment by bebraw** [comment]
Did you see https://prosecco.surge.sh/ ?

There is not much we can do about this issue in webpack itself.

**Comment by sidjain26** [comment]
@bebraw This seems very experimental. The gitlab link returns a 404. Totally agree this isn't a webpack concern.

**Comment by fulls1z3** [comment]
I completely agree with the fist solution proposed by @bebraw. I try to help by providing detailed instructions:

- Fork webpack,
- On that fork, delete all branches except master,
- Clone master branch to a local folder,
- On the local folder, delete all files,
- Commit the empty local folder,
- Download the latest release (ex: v2.1.0-beta.27 at the moment)
- Extract contents of zip file to the local folder,
- On the local folder, edit forked package.json, change
```
"uglify-js": "git+https://github.com/mishoo/UglifyJS2.git#harmony"
```
to point UglifyJs2 (harmony branch) dependency to that branch.
- Commit changes,
- Finally, point webpack in your package.json to your custom fork:
```
"webpack": "[USERNAME]/webpack#master"
```

OR,

- Point webpack in your package.json to [fulls1z3/webpack](https://github.com/fulls1z3/webpack) (ES6/ES2015 friendly webpack fork):
```
"webpack": "fulls1z3/webpack#v2.1.0-beta.27-harmony"
```

**Comment by mikeerickson** [comment]
@bebraw Is this still the case?  Is there a way to get this for `webpack 2.2.0 final`

**Comment by bebraw** [comment]
@mikeerickson I think the instructions above should be valid. The problem is that uglify doesn't support es6 yet and webpack bundles the plugin. So it takes quite a bit of work.

**Comment by mikeerickson** [comment]
@bebraw Which of the two items should be used

- First solution, which [USERNAME] should be used
- Second solution, which version should be used with `fulls1z3/webpack...`

**Comment by bebraw** [comment]
@mikeerickson The first sequence is all the steps (forking etc.). The second is just pointing to https://github.com/fulls1z3/webpack, but that seems to be a little out of date already.

**Comment by mikeerickson** [comment]
Ok, I will make it work.  Just curious why there is no "official" version of UglifyJs which works with ES6 (harmony) within Webpack.  We are well passed the ES5 days :)

**Comment by Kitanotori** [comment]
@mikeerickson I guess that's a question we have to ask from [UglifyJS ](https://github.com/mishoo/UglifyJS2)team. Although adding `"uglify-js": "git://github.com/mishoo/UglifyJS2#harmony"` to my package.json is not a problem, having Git repos as dependencies feels a bit hacky.

**Comment by bebraw** [comment]
What if we did an experimental `uglifyjs-webpack-plugin` below the `webpack-contrib` org? I can set up rights etc. if someone is interested. We would basically push the Uglify bits there. It's easier to fork/patch that than webpack.

**Comment by Kitanotori** [comment]
@bebraw You mean extracting lib/optimize/UglifyJsPlugin.js into separate plugin project and removing UglifyJS dependency from Webpack?

**Comment by bebraw** [comment]
> @bebraw You mean extracting lib/optimize/UglifyJsPlugin.js into separate plugin project and removing UglifyJS dependency from Webpack? Or, leaving Webpack as it is and providing users the ability to have UglifyJS plugin that instead depends on the harmony branch?

`lib/optimize/UglifyJsPlugin.js` would literally become a project of its own, yeah. This may be a step we might want to take eventually anyway so it could be a nice idea to experiment with it a bit.

I don't mind setting up a little stub project if you are interested.

**Comment by fulls1z3** [comment]
Hi @bebraw @mikeerickson, the fork I've been built seems a lot of of date. Now the latest version of webpack is 2.2.0, and don't worry I'll update that fork in a few days :)

**Comment by Kitanotori** [comment]
@bebraw That doesn't sound too difficult. Yea, I think I could do it.

**Comment by Kitanotori** [comment]
@fulls1z3 I don't quite understand what you are/were trying to do with that fork. There is no need to fork Webpack in order to use the harmony branch; just add `"uglify-js": "git://github.com/mishoo/UglifyJS2#harmony"` to your project's package.json, `rm -rf node_modules`, and voilà.

**Comment by fulls1z3** [comment]
The aim of the fork is just to prevent dependency interference/mismatch (depending on the dev environment and npm). In other cases I agree with you, and voilà.

**Comment by bebraw** [comment]
@Kitanotori @fulls1z3 I set up [a repository](https://github.com/webpack-contrib/uglifyjs-webpack-plugin). There's a basic demo that works. I didn't port the tests over, though (it's a Jest based setup).

**Comment by fulls1z3** [comment]
@bebraw seems awesome!
I'll test it and share results with you.

**Comment by damianobarbati** [comment]
@Kitanotori you're right: anyway I expected the ES6-only bundle to me much smaller in size :\

**Comment by Kitanotori** [comment]
@damianobarbati There's not *that* much difference, but I think we all should strive for advancing the ecosystem. If we still keep transpiling to ES5 10 years from now on, I think the JavaScript ecosystem has failed miserably.

**Comment by fulls1z3** [comment]
Fork updated (to v2.2.1)

- "webpack": "fulls1z3/webpack#v2.2.1-harmony"

**Comment by meowgorithm** [comment]
While not an ideal solution, I've been using the very simple workaround:

1. Install the UglifyJS harmony branch via `npm install --save-dev uglify-js@github:mishoo/UglifyJS2#harmony`
2. Build with Webpack, sans uglifying: `webpack --define process.env.NODE_ENV="production"`
3. Run the harmonized Uglify on the build:

    #!/usr/bin/env bash
    UGLIFY_BIN=./node_modules/.bin/uglifyjs
    BUILD_DIR=./build/static
    for f in ./build/static/*.entry.*.js; do
        BASENAME=`basename $f`
        mv $f /tmp/$BASENAME
        $UGLIFY_BIN /tmp/$BASENAME -c -m > $f
    done

While the uglifying isn't built into Webpack per se, it's an extremely simple workaround.

**Comment by bkahl** [comment]
so updating my webpack reference to "webpack": "fulls1z3/webpack#v2.2.1-harmony", deleting my old node_modules and then running npm install will fix the webpack uglyfy issue and will allow me to minifi es6 with this new fork?

**Comment by fulls1z3** [comment]
Although the harmony branch of UglifyJs does not cover all es6 features, I suppose it will help you to uglify your es6 code. It did work on me.

Also you can check this post to determine what's covered by this branch:
https://github.com/mishoo/UglifyJS2/issues/448

**Comment by phips28** [comment]
I am using webpack 2.5.1 and "uglify-js": "git://github.com/mishoo/UglifyJS2#harmony",
It worked till 8th may 2017.

Now it fails with the error:
```
ERROR in express.js from UglifyJs
TypeError: Cannot read property 'reset' of undefined
    at filterdFiles.forEach.err (/Library/WebServer/Documents/dvel/waves-provider/api-provider/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:81:20)
    at Array.forEach (native)
    at Compilation.compilation.plugin (/Library/WebServer/Documents/dvel/waves-provider/api-provider/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:40:18)
    at next (/Library/WebServer/Documents/dvel/waves-provider/api-provider/node_modules/tapable/lib/Tapable.js:140:14)
    at Compilation.compilation.plugin (/Library/WebServer/Documents/dvel/waves-provider/api-provider/node_modules/webpack/lib/BannerPlugin.js:67:5)
    at Compilation.applyPluginsAsyncSeries (/Library/WebServer/Documents/dvel/waves-provider/api-provider/node_modules/tapable/lib/Tapable.js:142:13)
    at self.applyPluginsAsync.err (/Library/WebServer/Documents/dvel/waves-provider/api-provider/node_modules/webpack/lib/Compilation.js:635:10)
    at Compilation.applyPluginsAsyncSeries (/Library/WebServer/Documents/dvel/waves-provider/api-provider/node_modules/tapable/lib/Tapable.js:131:46)
    at sealPart2 (/Library/WebServer/Documents/dvel/waves-provider/api-provider/node_modules/webpack/lib/Compilation.js:631:9)
    at Compilation.applyPluginsAsyncSeries (/Library/WebServer/Documents/dvel/waves-provider/api-provider/node_modules/tapable/lib/Tapable.js:131:46)
    at Compilation.seal (/Library/WebServer/Documents/dvel/waves-provider/api-provider/node_modules/webpack/lib/Compilation.js:579:8)
    at /Library/WebServer/Documents/dvel/waves-provider/api-provider/node_modules/webpack/lib/Compiler.js:493:16
    at /Library/WebServer/Documents/dvel/waves-provider/api-provider/node_modules/tapable/lib/Tapable.js:225:11
    at _addModuleChain (/Library/WebServer/Documents/dvel/waves-provider/api-provider/node_modules/webpack/lib/Compilation.js:481:11)
    at processModuleDependencies.err (/Library/WebServer/Documents/dvel/waves-provider/api-provider/node_modules/webpack/lib/Compilation.js:452:13)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Does anyone has similar error?

**Comment by aedart** [comment]
@phips28 I'm facing the exact same issue - and I have no idea what's causing it :/

**Comment by ksjogo** [comment]
Same here.

**Comment by Kitanotori** [comment]
UglifyJS seems to have bumped to a new major version. Try

`"uglify-js": "git://github.com/mishoo/UglifyJS2#harmony-v2.8.22"`

**Comment by phips28** [comment]
@Kitanotori thx for the hint! it works

**Comment by ksjogo** [comment]
It works until I run yarn upgrade which will overwrite it with the 2.8.23 without harmony. Anybody knows a way how to pin the transitive dependencies?

**Comment by hirokiosame** [comment]
@ksjogo 

You can use npm shrinkwrap:
https://github.com/webpack/webpack/issues/2545#issuecomment-244524160

**Comment by Kitanotori** [comment]
@ksjogo That's weird. Doesn't happen for me.. Try deleting yarn.lock and node_modules and run yarn again.

**Comment by ixcat** [comment]
Just ran into this and while investigating discovered there is a fork of the harmony branch in NPM which seems to solve my issues ..

> $ npm info uglify-js-es6|grep github 
>     url: 'git+https://github.com/paulovieira/UglifyJS2.git' },
>  bugs: { url: 'https://github.com/mishoo/UglifyJS2/issues' },

patched up my local uglifyjs-webpack-plugin as follows:

> $ diff -urw  node_modules/uglifyjs-webpack-plugin/dist/in>
> --- node_modules/uglifyjs-webpack-plugin/dist/index.js.orig	Wed May 24 04:31:46 2017
> +++ node_modules/uglifyjs-webpack-plugin/dist/index.js	Wed May 24 04:33:14 2017
> @@ -16,7 +16,16 @@
>  var ConcatSource = require("webpack-sources").ConcatSource;
> var RequestShortener = require("webpack/lib/RequestShortener");
> var ModuleFilenameHelpers = require("webpack/lib/ModuleFilenameHelpers");
>-var uglify = require("uglify-js");
>+var uglify;
>+try {
>+  uglify = require("uglify-js-es6");
>+}
>+catch (e) {
>+  if (e.code !== 'MODULE_NOT_FOUND') {
>+    throw e;
>+  }
>+  uglify = require("uglify-js");
>+}
> 
> var UglifyJsPlugin = function () {
> 	function UglifyJsPlugin(options) {

Ideally wouldn't be relying on a fork either, but this IMHO is better than a direct github reference..

**Comment by robwierzbowski** [comment]
https://github.com/webpack-contrib/babel-minify-webpack-plugin mentioned in the commit above from @trazyn seems like it has a lot of potential.

**Comment by trazyn** [comment]
I have the same trouble with ES6, `babel-minify-webpack-plugin` is work well with ES6 in my project.

**Comment by ReeganExE** [comment]
Installing `"uglifyjs-webpack-plugin": "^1.0.0-beta.2"` works for me (with `"webpack": "^3.6.0"`).
```js
const UglifyJSPlugin = require('uglifyjs-webpack-plugin');
// ...
plugins: [
  // expose and write the allowed env vars on the compiled bundle
  new webpack.DefinePlugin({
    'process.env.NODE_ENV': JSON.stringify(env.NODE_ENV)
  }),
  new webpack.LoaderOptionsPlugin({
    minimize: true,
    debug: false
  }),
  new UglifyJSPlugin({
    uglifyOptions: {
      beautify: false,
      ecma: 6,
      compress: true,
      comments: false
    }
  })
]
```

**Comment by demonmind** [comment]
i used `babel-minify-webpack-plugin ` and worked well finally

**Comment by Apidcloud** [comment]
In my case, the problem was related to mangling. Setting `mangle` to **false** solved it (both `uglifyjs-webpack-plugin` and `babel-minify-webpack-plugin` have that option).

**Comment by xgqfrms** [comment]
# bug

> after minify, it doesn't work. what's wrong with this?

https://github.com/gildata/RAIO/issues/350
