### ISSUE TITLE
process is not defined

### ISSUE THREAD

**Issue by Fyre91** [webpack/webpack#2547]
I am trying to use require.ensure to get multiple chunks. But when i load the page i get the error process is not defined. Here's how I am trying to use:

```
  <Route path="/" component={App}>
        <IndexRoute getComponent={(location, cb) => {
          require.ensure([], (require) => {
             cb(null, require('./containers/Home/Home'))
          });
        }}/>

      <Route path="allCategories" getComponent={(location, cb) => {
        require.ensure([], (require) => {
          cb(null, require('./containers/AllCategories/AllCategories'))
       });
      }}/>
    </Route>
```

When i do `npm run build` I get multiple chunks which is fine and also when i load different pages different chunks are loaded but due to this error process is not defined no js seems to work on the page.

Any help would be great.

**Comment by bebraw** [comment]
Any chance for a stack trace or a standalone example? It's very hard to say anything concrete as I haven't encountered an issue just like this before. Are you using Node `process` module somehow?

**Comment by Fyre91** [comment]
I am setting process.env.NODE_ENV like this in prod.config.js....before require.ensure it was working fine

```
new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: JSON.stringify('production')
      }
    })
```

**Comment by bebraw** [comment]
Ok, sounds like a bug then.

**Comment by Fyre91** [comment]
@bebraw Is there anything I am missing here...pretty new to Webpack. Earlier I was plainly using Routes without require.ensure and the app was working. The bundle size was coming around to be 2mb so i decided to use require.ensure and while building i get different chunks. Its just that when i try to run the page i get this error. The server side rendering is also working fine.

**Comment by bebraw** [comment]
@Fyre91 I don't think so. Based on your report it just seems `require.ensure` and `DefinePlugin` won't work together nicely. So you might have to find another way to achieve the same result. I would look into [resolve.alias](https://webpack.github.io/docs/configuration.html#resolve-alias). It's a heavier solution (entire file) but it just might work.

**Comment by Fyre91** [comment]
It seems that the chunks are created and requested correctly. Its just that these components inside the chunks are not getting executed. Is this possible? Do  I have to do any extra step

**Comment by bebraw** [comment]
Could you set up a minimal repository illustrating the issue? I think that would help in resolving it.

**Comment by GatzJames** [comment]
I had this problem too and for me the solution was to clean `npm install` my dependencies. Investigating this further it had something to do with node-process `setTimeout` browser shimming which in 0.11.5 added a try catch method for it.

**Comment by bebraw** [comment]
Can you try against webpack 2?
