### ISSUE TITLE
Truncated Output From Webpack Help

### ISSUE THREAD

**Issue by andrewjmead** [webpack/webpack#2549]
I just updated to the latest version of webpack. Running `webpack -h` cuts off halfway through the process. Previous versions had more options and output.

<img width="1037" alt="image 2016-05-25 at 2 57 02 pm" src="https://cloud.githubusercontent.com/assets/2992789/15552628/51f89d98-2289-11e6-9269-139e1a64b19a.png">

**Comment by rbartoli** [comment]
Duplicate of #2511.

**Comment by andrewjmead** [comment]
Thanks!
