### ISSUE TITLE
10-30 second hot reload time with large assets and webpack dev server

### ISSUE THREAD

**Issue by DelvarWorld** [webpack/webpack#2552]
I'm developing [a game using ThreeJS and React](http://charismachameleon.com) (and Webpack). I have several "large" (several mb) JSON files for 3d models. When I change any line of code in my source, unrelated to the assets, my hot reload time is 10-30 seconds.

I've tried a few things and asked [on Stackoverflow](http://stackoverflow.com/questions/36139153/how-to-reduce-webpack-dev-server-rebuild-time) but no takers. I'll rephrase the SO question with added details:

I require those assets with Webpack, like:

    require('../../assets/models/house.json')

As you can see, doing things like this gives me a large initial bundle and large initial build time:

    [0]           main-ad421c4138968fe0a8ae.js    14.8 MB       0  [emitted]  main
    [0] webpack built ad421c4138968fe0a8ae in 26610ms

The real issue is **the rebuild time using the dev server:**

    [1] [piping] File src/Game.js has changed, reloading.
    [0] webpack built 80f5c6c75e347304002c in 10534ms

**I've tried** ignoring my assets folder entirely:

    new webpack.IgnorePlugin( /assets\/*/ ),

But as you might guess, this means I can no longer `require()` an asset by its local path, which is basically the whole point of using webpack.

I've also tried using the [webpack watch ignore plugin](https://github.com/christophercliff/watch-ignore-webpack-plugin) to ignore my assets folder, and node modules:

    new WatchIgnorePlugin([
        path.resolve( __dirname, '../assets/models/' ),
        path.resolve( __dirname, '../node_modules/' )
    ]),

However this doesn't reduce the build time either. I [filed a bug](https://github.com/christophercliff/watch-ignore-webpack-plugin/issues/5) because it appears the plugin doesn't actually do anything at all.

A comment on the SO question suggested I have multiple entry chunks, one for all the assets, and one for the rest of the code. I tried that:

```
  entry: {
    main: [
      'webpack-hot-middleware/client?path=http://' + host + ':' + port + '/__webpack_hmr',
      './src/client.js'
    ],
    assets: './src/assets.js'
  },
```

`assets.js` simply contains require statements:

```
require( '../assets/models/model1.json' );
require( '../assets/models/model2.json' );
...
```
...but this has no effect either. Note I still require() those paths in the `main` chunk - I have to to get the URLs.

I pass all models through the file loader only:

```
loaders: [
      { test: /models.+\.json$/, loader: "file" },
      ....
]
```

I've also tried `noParse`:

```
    noParse: [
      /models.+\.json$/
    ]
```

The only effect this has is crashing my app at runtime with `Uncaught ReferenceError: __webpack_public_path__ is not defined`. Build times are not changed.

I'm also using `devtool: 'inline-source-map'` but removing that line has no effect on build time nor rebuild time.

I don't know if this is a webpack bug or a configuration issue which is causing such huge reload times when I'm not changing the large files. But I can't figure out what to do next.

**Comment by sokra** [comment]
webpack need to write the output files, which means if they are big it's slower.

If you process the file with the file-loader, they should not be included in the bundle file, but emitted as separate files. This should reduce the rebuilding time as these files don't change.

WatchIgnore doesn't help here as the watching is not the expensive part, it's the emitting.

`inline-source-map` is also a very slow option for rebuilding (see table in documentation)

**Comment by DelvarWorld** [comment]
Hmm, well I am sending the json files to the file loader. I've confirmed the large files are not in the main bundle, but changing source code still shows a large rebuild time. I've also tried removing inline-source-map and devtool all together, but the rebuild time isn't affected.

**Comment by DelvarWorld** [comment]
It seems like the best way I can find to get around Webpack's rebundle-all-files-all-the-time behavior is to use the dllplugin. Writeup: https://github.com/erikras/react-redux-universal-hot-example/issues/616#issuecomment-228956242

**Comment by Pines-Cheng** [comment]
it is no use to me. just the build time reduce to 30s, rebuild time is still 13s.
