### ISSUE TITLE
Uncaught ReferenceError: webpackJsonp is not defined

### ISSUE THREAD

**Issue by frodrigueza** [webpack/webpack#2556]
I'm using CommonsChunkPlugin and when I push to production, sometimes I get this error when the page is loading and I refresh again, interrupting the page loading to load it again..

![captura de pantalla 2016-05-26 a las 4 31 13 p m](https://cloud.githubusercontent.com/assets/5264663/15587389/5ecb1de4-235f-11e6-9aa4-b3ab572b953e.png)

What could it be?

**Comment by sokra** [comment]
Investigate into the SyntaxError.

**Comment by mAAdhaTTah** [comment]
Possibly related to #2570?

**Comment by sokra** [comment]
Maybe, difficult to say without any information
