### ISSUE TITLE
webpack2 : remove comments with LoaderOptionsPlugin

### ISSUE THREAD

**Issue by Makio64** [webpack/webpack#2557]
Hi there,

Before with the UglifyPlugin, I could pass { comments: false } as options, how to do the same with LoaderOptionsPlugin ?

Thanks

**Comment by sokra** [comment]
The UglifyPlugin is not affect by the change. LoaderOptionsPlugin is only relevant for loaders that has minimizer includes (i. e. css, html).

**Comment by Makio64** [comment]
Ok, I was thinking LoaderOptionsPlugin replace the UglifyPlugin.
Thanks to clarify.

**Comment by tsm91** [comment]
@sokra is there anything else that tells the affected loaders to use the minimizer option?

for example `NODE_ENV=production` or the `-p` flag
