### ISSUE TITLE
Have issues generating dynamic chunk file names.

### ISSUE THREAD

**Issue by SMLMRKHLMS** [webpack/webpack#2562]
I am attempting to provide a dynamic string to `require.ensure` like so:
```js
require.ensure([], (require) => {
  cb(null, require('./components/views/Default/Default.js').default);
}, `${route.ID}`);
```
However, I am receiving this error when I attempt to do this:
```
TypeError: __webpack_require__(...).ensure is not a function(…)
```
This is what the transpiled code looks like:
```js
__webpack_require__(/*! . */ 573).ensure([], function (require) {
  cb(null, require('./components/views/Default/Default.js').default);
}, '' + route.ID);
```
When I provide `require.ensure` with a string literal, it works as expected:
```js
require.ensure([], (require) => {
  cb(null, require('./components/views/Default/Default.js').default)
}, 'hello');
```
Here is the transpiled code when I do so:
```js
__webpack_require__.e/* nsure */(2/*! hello */, function (require) {
  cb(null, __webpack_require__(/*! ./components/views/Default/Default.js */ 128).default);
});
```

Would be grateful for any direction you can provide. Not sure if this is a bug, or if I am implementing this incorrectly. Thanks.

**Comment by bebraw** [comment]
What's the point of the third parameter you are passing to `require.ensure`? I don't see it at the [docs](https://webpack.github.io/docs/code-splitting.html).

**Comment by SMLMRKHLMS** [comment]
@bebraw https://webpack.github.io/docs/api-in-modules.html#require-ensure
```
require.ensure(dependencies: String[], callback: function([require]), [chunkName: String])
```

**Comment by bebraw** [comment]
Ah, I see. It relies on static analysis so there's no way it could figure out the result in your first example.

**Comment by SMLMRKHLMS** [comment]
@bebraw Ah, I see. Thanks for your help.

**Comment by bebraw** [comment]
No probs. :+1:
