### ISSUE TITLE
Duplicated minified files

### ISSUE THREAD

**Issue by tomascharad** [webpack/webpack#2563]
Hi guys,

This might be related to chrome rather than webpack, but I'm not really sure about that.

I have a problem related to js files getting partially duplicated by the browser.

The following part of the minified js can visually seen duplicated:
- Checks if an event is supported in the current execution environment.
  *
  - NOTE: This will not work correctly for non-generic events such as `change`,

This happens when chrome is loading the js but I quickly navigate to another link in the website.
When I come back, and the files start to load again, then the file gets this duplication problem, this causes a js error that can be seen on console.

commonChunk.54cef61….bundle.js:41 Uncaught SyntaxError: Unexpected token !

The worst problem is that I'm caching files, so the user doesn't get rid of the error until he clears the cache.

If I wait for the file to load, then the file gets received perfectly by the user.

This seems only to be affecting commonChunk.

**Comment by tomascharad** [comment]
Need to note that this seems only to happen on commonChunk.

**Comment by tomascharad** [comment]
Hi @bebraw,

I'm still facing this problem with my app, I think that I have a better understanding on when it happens.

Do you think that you could guide me a bit? I can show you perfectly how to reproduce the error.

**Comment by bebraw** [comment]
@tomascharad Can you set up a standalone example?

**Comment by tomascharad** [comment]
Hi @bebraw,

I'm still facing this issue and I have upgraded webpack to version "webpack": "^2.4.1".

Here I'm enclosing a screenshot on where you can see the same webpacked file (one in an incognito window), loaded differently by chrome. The left hand side one has 122 lines (duplicated), while the right hand side one is ok and only has 79 lines.

![image](https://user-images.githubusercontent.com/1534092/27158741-8b4a93bc-5136-11e7-81a0-b8a3febefa43.png)

**Comment by bebraw** [comment]
@tomascharad To debug this, we would need some project to run. Thanks for getting back on this.

**Comment by tomascharad** [comment]
I haven't been able to reproduce this ao far. I was wondering if this could be caused by an incomplete async System.import?

**Comment by bebraw** [comment]
Maybe a network issue could explain it, yeah. I wonder how to simulate that in a smart way.

**Comment by tomascharad** [comment]
You can always use chrome devtools and restrict your network bandwidth. Ill try to have the demo today.

**Comment by tomascharad** [comment]
Hi,

I've narrowed the problem, it seems to deal with cache strategy I guess.

When serving the files with lite-server or serve, I cannot reproduce the issue. But when I serve the files with Rails, the error happens.

The first screenshots are from the headers when the assets are not cached, and the second ones are the headers after the files had been cached.

Left console is served from 'serve' and right hand side console is serve over Rails.

Before cache
![image](https://user-images.githubusercontent.com/1534092/28486764-f74c28e8-6e53-11e7-8107-e0229e8c43fc.png)

Served from memory
![image](https://user-images.githubusercontent.com/1534092/28486778-221caaac-6e54-11e7-8834-9aaa7daa8c7d.png)

The problem seems to happen when the files can be served from memory.

**Comment by tomascharad** [comment]
Ok, I prepared a sample project which behaves the same! I removed most of our business logic, then I made the bundles with webpack and pasted them into rails so it served the assets and it failed!

![image](https://user-images.githubusercontent.com/1534092/28487239-be05aa08-6e5a-11e7-8108-86da9fd42e11.png)

Here is the repo:

https://github.com/TCIT/webpack-duplication-sample

I've included a sample-duplicated-file which is what I get in chrome after have reloaded multiple times main.d90603e7e9c46c1577d5.bundle.js without allowing him to load completely.

**Comment by tomascharad** [comment]
Hi! Is there anything else that I can help with?

**Comment by evilebottnawi** [comment]
@tomascharad problem still exists?

**Comment by tomascharad** [comment]
Hi @evilebottnawi, yes.

**Comment by evilebottnawi** [comment]
@tomascharad do you have problem in `dev` or `production`? Because `npm run dev` don't works without `webpack.dev.config.js`. In `production` you have only comments in you bundle and seems all works fine.

**Comment by tomascharad** [comment]
@evilebottnawi the problems are in production.

In dev assets are not minified.

**Comment by evilebottnawi** [comment]
@tomascharad i have all fine using your repo? What is exactly wrong?

**Comment by tomascharad** [comment]
Well the history is quite long, but you might find relevant to read the history of the comments of the issues.

In summary, the minified files get duplicated when being served after refreshing the page a couple of times. You have to refresh the page before the loading of the minified file completes.

I left a sample in the  repo of how chrome duplicates the file: main.d90603e7e9c46c1577d5.bundle.js

The bundle process works fine.

**Comment by evilebottnawi** [comment]
@tomascharad do you have latest chrome version? I can't reproducible, all fine in your test repo.

**Comment by tomascharad** [comment]
Yeah, chrome updated.
I have a live application on which it happens: 

![image](https://user-images.githubusercontent.com/1534092/35574412-89c06382-05b8-11e8-8ac1-fead46737f55.png)

**Comment by evilebottnawi** [comment]
@tomascharad :confused: don't reproducible, maybe you have firewall or invalid network configuration, proxy cache server or maybe you provider sniff traffic? Try to install https (use let's encrypt) and check using https. Also try to reproduce problem in other place (home, friends, remote desktop).

**Comment by tomascharad** [comment]
@evilebottnawi .

It happens to all of my clients. Application is hosted on heroku, and I can reproduce in my local environment.

**Comment by tomascharad** [comment]
1. First disable cache, eveything will look normal (This way you clean caché)

![image](https://user-images.githubusercontent.com/1534092/35577329-06819e2a-05c0-11e8-9126-88ea80c7714e.png)
2. Hit refresh again with disabled cache again, now before the .js files load completly, hit refresh again and re-enable cache and keep hitting it multiple times before the .js files load (main.8b29a73ba42e9fe423b9.bundle.js)
![image](https://user-images.githubusercontent.com/1534092/35577462-675c4fce-05c0-11e8-9007-0d2056e14f1a.png)

3. After 5 or 7 times you will see the error

![image](https://user-images.githubusercontent.com/1534092/35577511-86d87bf2-05c0-11e8-9e35-56b25c7eac99.png)

Notice that this time, the error changed. The duplication happens differently depending on the page refresh, so the error message might change.

**Comment by tomascharad** [comment]
I'll make a video

**Comment by tomascharad** [comment]
https://drive.google.com/file/d/1qTJtVcKS1sCAcnqy79cPcZvfSWFCff4I/view?usp=sharing

**Comment by evilebottnawi** [comment]
@tomascharad can't reproduce :confused: but i watched your video, can you click on error file and show here which line affected error (also error stack).

**Comment by evilebottnawi** [comment]
@tomascharad congrats! Reproduce problem. Investigate :+1:

**Comment by tomascharad** [comment]
@evilebottnawi , did you de-activate disable cache button on the same iteration (In the video I do it really fast so you may have not noticed it)

Sure here is a screenshot:

![image](https://user-images.githubusercontent.com/1534092/35579079-91aab488-05c4-11e8-8b59-8863993a0bf8.png)

And here you can see how chrome duplicates the file:

![image](https://user-images.githubusercontent.com/1534092/35579149-bff11260-05c4-11e8-94c2-9085e42a2ec0.png)

Also, as I mentioned you can check a sample duplication file that I left in the repo: main.d90603e7e9c46c1577d5.bundle.js

**Comment by evilebottnawi** [comment]
@tomascharad Can you remove `Content-Range:bytes 829988-829988/1816878` header? Seems you have invalid bytes and so you got error. One part of main (first refresh) bundle concatenated with second part (second refresh).

**Comment by tomascharad** [comment]
@evilebottnawi 
That header is only sent after the file is duplicated...

Here you can see if it loads correctly it is ok:
![image](https://user-images.githubusercontent.com/1534092/35583314-504f571c-05d0-11e8-8aae-af1458639aa9.png)

Here is when it loads duplicated:
![image](https://user-images.githubusercontent.com/1534092/35583343-6963a442-05d0-11e8-9500-8728c78f416a.png)

**Comment by evilebottnawi** [comment]
@tomascharad can you remove to make sure problem not in header?

**Comment by tomascharad** [comment]
I'm not sure to be able to remove it, I'm not sure if I can control that.

**Comment by evilebottnawi** [comment]
@tomascharad problem not in webpack, because locally using `file://` this problem don't reproducible, server configuration problem. Also problem reproduce in firerfox and Edge.

**Comment by tomascharad** [comment]
@evilebottnawi, the server is Ruby on Rails, I don't seem to have problems with any other type of file rather than webpacked files

**Comment by evilebottnawi** [comment]
@tomascharad only on js files add this header, never before met this problem, seems it is invalid server configuration

**Comment by tomascharad** [comment]
@evilebottnawi But the header appears after the file is duplicated.
Give me a couple of days to dig into the header problem.

**Comment by evilebottnawi** [comment]
@tomascharad friendly ping

**Comment by tomascharad** [comment]
Hi @evilebottnawi ,

Just came back from vacations, give me a couple of days more please.

**Comment by tomascharad** [comment]
Hi, I've done a lot of tests, and the problem might be related with the server.
I just want to make sure that is the case narrowing down the problem the detail.

**Comment by evilebottnawi** [comment]
@tomascharad just try to put other big js file, example react framework, and include this in you html and test

**Comment by tomascharad** [comment]
Many thanks!

![image](https://user-images.githubusercontent.com/1534092/36422603-8022e480-161b-11e8-8403-069c806b9d93.png)

**Comment by evilebottnawi** [comment]
@tomascharad :+1:

**Comment by tomascharad** [comment]
Will continue trying to solve the problem here: https://github.com/rails/rails/issues/32068
