### ISSUE TITLE
[Feature] webpackfile/index.js

### ISSUE THREAD

**Issue by ThatTomPerson** [webpack/webpack#2569]
Being able to have the webpackfile be a folder (besides having an interesting name) would allow people to organise more complex webpack configs in a single place

This should be easy to implement, just add `'webpackfile/index'` to the array on https://github.com/webpack/webpack/blob/master/bin/convert-argv.js#L36

any thoughts / ideas before I submit a PR??

**Comment by bebraw** [comment]
Can you re-open this at [cli repo](https://github.com/webpack/webpack-cli/issues) if still interested? Thanks.
