### ISSUE TITLE
ContextReplacementPlugin does not apply

### ISSUE THREAD

**Issue by JulieWang2014** [webpack/webpack#2572]
I want to use ContextReplacementPlugin to remove unused language files in moment . I tried both  ContextReplacementPlugin and IgnorePlugin but none of them work. I debuged into the source code and found the plugin is created, but `ContextReplacementPlugin.prototype.apply` function never called. I am blocked in this problem, could anyone help me? Thanks very much!

The usage of plugin:

```
plugins: [
    new webpack.ContextReplacementPlugin(/moment[\/\\]locale$/, /de|fr|hu/)
    // new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/)
  ]
```

**Comment by bebraw** [comment]
Can you try with webpack 2? Can you set up a standalone project to test?
