### ISSUE TITLE
less-loader will filter `\`(bug)

### ISSUE THREAD

**Issue by weizongqi1990** [webpack/webpack#2573]
This is my less code:
`a { &:after { content: "\A"; white-space: pre; } }`
This is compiled css code:
`a:after { content: "A"; white-space: pre; }`

And I use \,this is my less code:
`a { &:after { content: "\\A"; white-space: pre; } }`
This is compiled css code:
`a:after { content: "\\A"; white-space: pre; }`
Why filter single backslash？

I tried sass-loader.It has problem that same

**Comment by bebraw** [comment]
Moved to https://github.com/webpack/less-loader/issues/123.
