### ISSUE TITLE
 Unknown plugin ..., attempted to resolve relative to 'an npm linked modules'

### ISSUE THREAD

**Issue by bertho-zero** [webpack/webpack#2581]
Hi,

I have a project '**users**' (_/home/bertho/oa/users_) with a '**react-components**' module linked (_/home/bertho/oa/react-components_).

If I compile when the module are linked then i have : 

> /home/bertho/oa/test-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:204
>           throw new ReferenceError(messages.get("pluginUnknown", plugin, loc, i, dirname));
>           ^
> 
> ReferenceError: Unknown plugin "transform-runtime" specified in "base" at 0, attempted to resolve relative to "/home/bertho/oa/react-components/build"
>     at /home/bertho/oa/test-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:204:17
>     at Array.map (native)
>     at Function.normalisePlugins (/home/bertho/oa/test-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:20)
>     at OptionManager.mergeOptions (/home/bertho/oa/test-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:300:36)
>     at OptionManager.init (/home/bertho/oa/test-app/node_modules/babel-core/lib/transformation/file/options/option-manager.js:488:10)
>     at compile (/home/bertho/oa/test-app/node_modules/babel-register/lib/node.js:112:69)
>     at loader (/home/bertho/oa/test-app/node_modules/babel-register/lib/node.js:158:14)
>     at Object.require.extensions.(anonymous function) [as .js] (/home/bertho/oa/test-app/node_modules/babel-register/lib/node.js:168:7)
>     at Module.load (module.js:458:32)
>     at tryModuleLoad (module.js:417:12)
>     at Function.Module._load (module.js:409:3)
>     at Module.require (module.js:468:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (SettingsContainer.js:29:11)
>     at Module._compile (module.js:541:32)
>     at loader (/home/bertho/oa/test-app/node_modules/babel-register/lib/node.js:158:5)
>     at Object.require.extensions.(anonymous function) [as .js] (/home/bertho/oa/test-app/node_modules/babel-register/lib/node.js:168:7)

And this work when I run 'npm unlink react-components && npm i' before.

my configuration : 

```
{
  devtool: 'cheap-module-eval-source-map',
  entry: entryFile,
  output: {
    path: path.dirname( tmpFile ),
    filename: path.basename( tmpFile )
  },
  module: {
    loaders: [
      {
        test: /\.jsx?$/,
        loader: 'babel',
        exclude: new RegExp( 'node_modules\\/(?!' + ourOwnModules.join( '|' ) + ')' )
      },
      {
        test: /\.json$/,
        loader: 'json'
      },
      {
        test: /\.ejs$/,
        loader: 'ejs'
      },
      {
        test: /\.(css|html|tblr)$/,
        loader: 'raw'
      }
    ]
  },
  progress: true,
  resolve: {
    extensions: [ '', '.js', '.jsx' ],
    moduleDirectories: [ path.join( process.cwd(), 'node_modules' ) ],
    fallback: path.join( process.cwd(), 'node_modules' )
  },
  resolveLoader: {
    root: path.join( process.cwd(), 'node_modules' ),
    fallback: path.join( process.cwd(), 'node_modules' )
  },
  plugins: [
    new webpack.DefinePlugin( {
      'process.env': {
        NODE_ENV: '"development"'
      },
      __CLIENT__: true,
      __SERVER__: false,
      __DEVELOPMENT__: true,
      __DEVTOOLS__: true
    } ),
    new webpack.IgnorePlugin( /(.*)/, /node_modules\/(imagesloaded|get-size|outlayer|fizzy-ui-utils)/ )
  ],
  node: {
    fs: 'empty'
  }
}
```

**Comment by sokra** [comment]
not related to webpack --> babel
