### ISSUE TITLE
Destructuring props in constructor (IE10+IE11)

### ISSUE THREAD

**Issue by katfa** [webpack/webpack#2583]
```
class EmbedModal extends React.Component {
  constructor(props) {
    super(props);
    let { one, two } = this.props
    one.callSomething() // one is undefined

    // Operations usually carried out in componentWillMount go here
  }
}
```

This works fine in Chrome and Firefox, was only having problems in IE10 and IE11.

**Comment by bebraw** [comment]
You probably want to push your code through Babel to transform it into a format the browsers in question can understand. See https://www.npmjs.com/package/babel-loader .
