### ISSUE TITLE
WDS auto disconnect per 1mins

### ISSUE THREAD

**Issue by neekychan** [webpack/webpack#2586]
![qq 20160602104038](https://cloud.githubusercontent.com/assets/3429041/15732277/7582daa0-28ae-11e6-9850-b608cc99e01d.png)

Chrome 52.0.2743.19 dev-m (64-bit)
"webpack": "^1.13.1",
"webpack-dev-server": "^1.14.1"

**Comment by bebraw** [comment]
Could you provide a standalone project to test against? It's not possible to say what's going on otherwise.

**Comment by SpaceK33z** [comment]
If you still have this issue, please make a more detailed issue in the [webpack-dev-server](https://github.com/webpack/webpack-dev-server/issues) repo.
