### ISSUE TITLE
Proposal: Dll-like Plugin for an external context - external manifest, dynamic module-map injection and loading

### ISSUE THREAD

**Issue by niieani** [webpack/webpack#2592]
Currently, the DllPlugin and DllReferencePlugin allows loading external modules from separately generated bundles. The problem is that we need to provide a manifest with all the modules being bundled **at the time of bundling**. This is limiting in certain scenarios, where we would like to dynamically load modules which are not known at the time of build (user input, external files). 

Example use case:

Imagine an docs-browser app, that dynamically loads the documentation text and executable examples, based on a JSON file that lists where they are contained. The documentation and examples are stored and built separately. They both can grow (more files are added) and we shouldn't need to republish the entire documentation website after every new addition to the documentation.

What I propose is that we delegate the manifest to the Dll bundle itself. This way the following could be possible:

``` js
require('https://domain.com/dll-bundle.js#jquery');
```

Assuming the `dll-bundle.js` file is a bundle that contains the module `jquery`, the above require would download the file (proper CORS required), load the manifest from it (listing all the mappings of modules and merging them with the preloaded ones) and finally load the code from the bundled module `jquery`. 

This would require the module IDs to be long and random (e.g. UUIDs) so that collisions do not occur, but they could technically also be generated based on prefixed some seeded value.

This would solve questions like https://github.com/webpack/webpack/issues/1421 or https://github.com/webpack/webpack/issues/150.

EDIT:
A helper method for requiring from an external bundle might make more sense, something like:

``` js
require.ensureExternal('https://domain.com/dll-bundle.js', function(require) {
  var $ = require('jquery');
})

// or even:
require.ensureExternal(dynamicallyGeneratedUrl, function(require) {
  var someModule = require(totallyDynamicName);
})
```

**Comment by sokra** [comment]
webpack doesn't take care of the module **loading**. You need to use another library for the loading part. But you can use webpack to bundle the main file and the loaded files. For your use case you don't need complex constructs like DLLs. Just define a interface for the loaded scripts, expose it with the `output.library` function and load them with a script loader like scriptjs.

Example:

``` js
function loadDocumentation(name) {
  return new Promise(function(resolve, reject) {
    scriptjs("https://domain.com/documentation-" + name + ".js", function() {
      var doc = window["documentation-" + name];
      resolve(doc);
    });
  });
}
```

documentation part build with `output.library = "documenation-" + name`

**Comment by niieani** [comment]
@sokra Indeed it doesn't take care of **module** loading, but it does take care of **bundle/chunk** loading. What I'm after is loading a bundle without knowing what modules it specifically contains (at least not at the time of compilation) and then handling the newly loaded modules as if they're originally compiled in. I feel it is very similar to the DLL construct, with the small difference of not mapping the modules during build-time, but during run-time.

**Comment by niieani** [comment]
@sokra Webpack wouldn't need to take care of loading anything from HTTP if the user had to provide a Promise or a Thunk that resolves to the contents of the bundle. This would also make it more flexible as to the source of the bundle.

Example:

```js
var bundleContents = fetch('https://domain.com/dll-bundle.js');

require.ensureExternal(bundleContents, function(require) {
  var $ = require('jquery');
})
```

**Comment by sokra** [comment]
``` js
// dll-bundle-entry.js
module.exports = function(request) {
  switch(request) {
    case "jquery": return require("jquery");
    // ...
  }
};
// or: module.exports = require.context(...)
```

``` js
var bundleContentsPromise = fetch('https://domain.com/dll-bundle.js');
var requireInBundlePromise = bundleContentsPromise.then(evalContent);

requireInBundlePromise.then(function(require) {
  require("jquery");
});
```

You don't need any special support for the runtime. You dll-bundle is just a library which exposes a require-like API, but you could use any API.

If writing the entry point manually is too much work, you could generate it with a loader.

**Comment by niieani** [comment]
@sokra That looks good, thanks. But won't the module IDs start to conflict when I import one Webpack project into another? They are stored in the global context, isn't that right?

**Comment by sokra** [comment]
> They are stored in the global context, isn't that right?

nope. They are stored inside the webpack runtime, which is in the entry chunk. bundles doesn't leak anything into the global scope except the jsonp function when using code splitting (you may rename it with a config option).

**Comment by mnzaki** [comment]
But `require.ensure` automatically loads bundles, and it would be really nice to have that functionality for `DllReferencePlugin` as well. Something like this:

```js
require.ensure([], () => {
  require('somelibrary');
});
```

And in webpack config:
```js
plugins: [
  new DllReferencePlugin({
    context: '.',
    manifest: require('../dll-manifest.json')
  })
]
```

Where the `dll-manifest.json` file contains a manifest generated by `DllPlugin` for a build that contains the `somelibrary` module.

If the `DllReferencePlugin` can cause this to autoload the DLL bundle, that would be awesome.

**Comment by mnzaki** [comment]
Actually, `require.ensure` is unrelated. It would be nice if `DllReferencePlugin`, or perhaps a wrapper around it, can auto-load DLL bundles when modules are `require()`ed from them.

**Comment by senritsu** [comment]
@sokra are there any plans of supporting async loading in the `DllReferencePlugin ` as outlined by @mnzaki at the moment? 

As both external dependencies and async dependencies (via split points) are supported, the infrastructure, in theory at least, seems to support integrating a script loader like scriptjs to the point that a regular `require.ensure` call without any further adjustments to the rest of the pipeline would *just work (tm)*, is that correct? 

After reading the sources for the `DllReferencePlugin` and related classes i have an inkling of how it works, but am still not really at a point where i understand it enough to be able to really judge the complexity of something like this, so any thoughts on that matter from someone who knows webpack in and out would be much appreciated.

**Comment by githoniel** [comment]
I need to share my code across several apps, and  it's impossible to build them together in one project(they will not develop in the same time). In order to use the browser cache, reduce the file size in server and client cache, supporting async loading in the DllReferencePlugin is a very good idea!

I know use scriptjs or other module loader can do this, even use requirejs with 'requirejs(['module'], a => { //todo })'. but those loaders cannot read dependency，alias and path settings from webpack，a duplicate setting  is need. it is so ugly  and inconvenient

**Comment by shaikhspear16** [comment]
@githoniel I am looking for a solution for the same. Did you find a way to achieve that?

For me, we create an angular 2 library such as a "Menu" that exposes a menu directive and host to to an internal CDN. We need to utilize this library from the CDN to all our other SPAs for the same reasons you mentioned above. It would be great to have some direction.

**Comment by githoniel** [comment]
@shaikhspear16  as I metioned，let webpack export AMD  Libaray and use requirejs to load them is the only way to do this as i know。

**Comment by CameronPlimsoll** [comment]
@githoniel do you have any sample code ?

**Comment by githoniel** [comment]
@CameronPlimsoll  its my pleasure

1、in you dll generator webpack config，use `assets-webpack-plugin` to outp a JSON object to descript you output libaray, like 
```js
module.exports = merge(baseWebpackConfig, {
     entry: utils.getLibaryEntry(),
     output: {
         path: config.libraryPath,
         jsonpFunction: `webpackJsonp${Date.now()}`,  //!! to avoid webpackJsonp conflict with reference webpack 
         filename: 'bundle.[id].js',
         chunkFilename: 'chunk.[id].[chunkhash].js',
         publicPath: '../../',   //you public Path
         libraryTarget: 'commonjs2'  //output  cmd 
     },
    plugins: [
         new AssetsPlugin({
             filename: 'helios-service-assets.json',
             fullPath: false,
             path: config.libraryPath,
             metadata: {
                 version: (new Date()).getTime()
             }
         }),
```

2. In my project , I use SystemJS to load js from dll project, I wrote a simple plugin to insert SystemJS code to webpack bootstrap, but insert SystemJS to html template maybe more easy. Then you need to set alias for Systemjs,  like
```js
return fetch(mapJsonLocation)
        .then(response => response.json())
        .then((asset) => {
            const map = {}
            if (asset.metadata) {
                delete asset.metadata
            }
            Object.keys(asset).forEach((key) => {
                const aliasKey = `${packageName}/${key}`
                const aliasPath = `${prefixPath}/${asset[key].js}`
                map[aliasKey] = aliasPath
            })
            SystemJS.config({
                map
            })
        })
```

3. Now you can write in your file
```js
System.import('packageName/moduleName')
  .then((module) => {
     //todo 
  })
```

4. If you use requirejs, Output AMD format libary and use
```
 requirejs(['module'], (module) => {})
```

**Comment by CameronPlimsoll** [comment]
@githoniel Thanks , appreciate the code snippet.
However i have run into some problems 
when i try an import the module it seems to ignore the systemJS config ?
```js
    let packageName = 'myAwesomePlugin';
    let packageMainPath = 'http://localhost/plugin/main.bundle.js'
    let prefixPath = 'http://localhost/plugin';
    let moduleName = 'AppModule';
    let mapLocation = 'http://localhost/plugin/helios-service-assets.json'

    this.http.get(mapLocation)
      .subscribe(res => {
        let asset = res.json()
        const map = {}
        if (asset.metadata) {
          delete asset.metadata
        }
        map[packageName] = prefixPath;
        Object.keys(asset).forEach((key) => {
          const aliasKey = `${packageName}/${key}`
          const aliasPath = `${prefixPath}/${asset[key].js}`
          map[aliasKey] = aliasPath

        })
        let packages = {}
        packages[`${packageName}`] = { main: 'main.bundle.js', defaultExtension: 'js' };
        SystemJS.config({
          baseURL: prefixPath,
          map,
          packages
        })
      }, (err) => {
      }, () => {
        //systemjs config has been set , try and import the module 
        SystemJS.import(`${packageName}/${moduleName}`).then((module) => {
          console.log(module);
        }).catch(err => {
          console.error(err);
        })
      });
  }
```
the above throws the following error
```
Error: (SystemJS) XHR error (404 Not Found) loading http://localhost/plugin/AppModule.js
```

when i try import the main.bundle created from output library i get the following 
```js
Error: (SystemJS) webpackJsonp1490526215268 is not defined
```
this is the directory structure of the library 
```
|-- plugin
        |-- favicon.ico
        |-- helios-service-assets.json
        |-- index.html
        |-- inline.bundle.js
        |-- main.bundle.js
        |-- polyfills.bundle.js
        |-- styles.bundle.js
        |-- vendor.bundle.js
```
any advice would be greatly appreciated

**Comment by githoniel** [comment]
It seem SystemJS config's problem,  i think baseURL is not needed

You can only load main.bundle by SystemJS from you entries in your dll webpack config.

**Comment by mastilver** [comment]
It's not related to DllPlugin but I think this plugin I wrote solves most of your issues (https://github.com/mastilver/modules-cdn-webpack-plugin):
- no need to specify library at build time
- dependencies are shared across build / apps

**Comment by niieani** [comment]
@webpack-bot fist-bump

**Comment by seajean** [comment]
I am looking for the same solution too,  Some of my SPA module was written by others in other project, and I want to load it asynchronously  and render it. Still  its requires my modules as  dependencies, If was in my project, it would be very easy to do by using webpack's import, but I can not find a way to load a module externally.

**Comment by ScriptedAlchemy** [comment]
If anyone is willing to help me make this less hacky. This works, pretty well - https://github.com/ScriptedAlchemy/webpack-external-import

**Comment by vankop** [comment]
I think this discussion could be closed in favor of [module federation thread](https://github.com/webpack/webpack/issues/10352)

**Comment by ScriptedAlchemy** [comment]
Yep. External import was rewritten and moved into webpack 5 as part of its core
