### ISSUE TITLE
Compiling without creating a dev-server

### ISSUE THREAD

**Issue by MariusGarbea** [webpack/webpack#2593]
Hi guys! How can I compile and run a page directly from index.html without starting webpack-dev-server? I'm a beginner so every explanation that could make me understand how this works and how it can be fixed would be great. Thanks!

**Comment by adithyan** [comment]
Check this out https://webpack.github.io/docs/tutorials/getting-started/

**Comment by MariusGarbea** [comment]
Ok I had it working. I think I didn't explain my problem well - sorry.
I would like to post my project on github gh-pages. If I store my project locally I have to manually compile it. Does github compile it by default or do I have to make other settings?

**Comment by MariusGarbea** [comment]
Ok I got it working. Running webpack in console created my bundled js. Thanks for your help! :D
