### ISSUE TITLE
Segmentation Fault: 11, webpack 2.1.0-beta.8, typescript loaders

### ISSUE THREAD

**Issue by rob-bateman** [webpack/webpack#2596]
been battling with this error for a day now, really putting me off trying to upgrade to webpack 2 :)

webpack 1.x runs without any issue. webpack 2.x runs, but only if i don't use any loaders

As soon as a loader is added, i get the `Segmentation Fault: 11` error.

tried deleting & reinstalling node_modules.
tried reinstalling node (running node 4.2.2, npm v2.15.0).
tried deleting & reinstalling global node_modules
tried reinstalling global webpack modules
tried forcing version of fsevents (from [this post](https://github.com/sass/node-sass/issues/1107)). Cannot complete install.

the loaders i am trying to get running are for typescript (tried both ts-loader and awesome-typescript-loader)

I see typescript compilation has been working in the past from [this blog post](http://www.jbrantly.com/es6-modules-with-typescript-and-webpack/), so i know it at least works for someone

should webpack 2.x be able to run with node 4.4.x without this error? Anyone else have it working with typescript?

running OSX 10.11.1

**Comment by TheLarkInn** [comment]
Which typescript loader were you trying to install.

**Comment by rob-bateman** [comment]
OK, i've found out a bit more about this, its actually something i've come across before when initially trying webpack 2

if i run webpack in a standard terminal rather than the builtin terminal in webstorm, i actually get errors - these are typescript-related errors todo with symlinked libs creating more than one path for a single file

so for example, if i link module m1 to module m2 because it uses class c1, thats all fine

however, if i introduce a third module that links both module m1 and module m2 and uses class m1, this class will be represented twice in the module tree hierarchy and typescript will output a nonsense errors such as

    type 'Node' is not a class derived from 'Node'

originally i took this to be a webpack issue but it turned out to be a typescript one (in fact it is reported and tracked [here](https://github.com/Microsoft/TypeScript/issues/6365)). From the issue, you can see it was recently patched and since then my webpack 1.x started working correctly again by pulling the 1.9 dev branch of the typescript compiler

For some reason, this fix doesn't seem to have made it to webpack 2.x - despite when compiling with ts-loader i see the trace stating it using the correct compiler. So there has to be something similar at work thatin webpack 2.x to the old typescript 1.8 compiler that is seeing this kind of symlinked structure as file duplicates when they are in fact referencing the same source files.

**Comment by rob-bateman** [comment]
I have been round the houses with this a couple more times and have more information on when and where i get errors

`Segmentation fault:11` seems to be something that frequently appears now when using webpack 2.x with my symlinked libs and `moduleResolution: "node"` in the tsconfig file, for both ts-loader and awesome-typescript-loader (at present I can't seem to reproduce the original symlinks-caused error, but there does seems to be some variability on the error reporting there)

setting `moduleResolution: "classic "` in tsconfig doesn't really work on its own because the typescript resolve mechanism cannot find things in node_modules, but i can workaround this by having the projects located all at the same level, including the project implementing the linked modules (which is how i was getting round the problem before the fix as it obviously removes using symlinked modules in the first place). With this approach, webpack 2.x runs without issue

If i keep  `moduleResolution: "node"` in tsconfig and downgrade back to webpack 1.x, i can also run without issue

So it would appear webpack 2.x still doesn't like the symlinked node modules when using `moduleResolution: "node"` in tsconfig, despite the fact that when using tsc 1.9.x on its own, this is a fixed problem

**Comment by TheLarkInn** [comment]
@rob-bateman I was seeing this issue until I updated to webpack@2.1.0-beta.14. Would you mind updating your webpack version and then let me know if this is still an issue?

**Comment by bebraw** [comment]
@rob-bateman Any update?
