### ISSUE TITLE
Hot Module Replacement

### ISSUE THREAD

**Issue by sokra** [webpack/webpack#26]
Reloading the whole page on bundle update is ok, but a far time goal is to replace modules on runtime. (Idea from #25)

It's a far time goal, but it may be good to start discussion early...

Steps:
1. Find a syntax.
2. Check how to implement it in webpack.
3. Implement it.

Goals:
- Don't interrupt other modules
- Let the developer use it for the whole or only parts of an application
- Module authors should be able to implement it for their modules. App devs shouldn't need to care.
- App devs should be able to implement hot module reloading for modules. Even if module authors don't care.
- It should be usable in production, if you want to. If not it should not make your bundle bigger.
- It should work with CommonJS and AMD modules.
- Opt-in for fallback to complete reload.
- Only transfer updated modules.
- There should be also a node.js version working with the same syntax

Problems:
- Side-Effects in modules. It must be a opt-in feature.
- Not possible for every module.
- A module may support it, but the author hasn't opt-in.
- When to check if new code is availible?
- Implentation
  - Module/Chunk Ids have to stay
- ...

**Comment by gaearon** [comment]
Thank you for doing this.
