### ISSUE TITLE
A loader for nested imports?

### ISSUE THREAD

**Issue by trusktr** [webpack/webpack#2602]
@benjamin has enabled the following experiment in Meteor: 

https://www.reddit.com/r/javascript/comments/4m5f03/meteor_133_introduces_nested_import_statements_if/

The Meteor user-base is wide, so the experiment will be highly tested. It might be nice for webpack to have a nested-imports-loader so that more people can experiment with the idea.

**Comment by sokra** [comment]
I took a look. Currently the implementation of ES6 Modules for meteor doesn't comply to the spec is more aspects than nested imports/exports (see https://github.com/benjamn/reify/pull/24). Let's focus on that before experimenting with new features.

**Comment by benjamn** [comment]
Thanks for sparking this [discussion](https://github.com/benjamn/reify/pull/24), @trusktr! The `reify` compiler, and by extension the Meteor community, will be much better off because of @sokra's feedback.

**Comment by bebraw** [comment]
@trusktr Is this relevant still?

**Comment by evilebottnawi** [comment]
Solution: https://github.com/airbnb/babel-plugin-dynamic-import-node
