### ISSUE TITLE
re-bundle css + js which split by System.import

### ISSUE THREAD

**Issue by leecade** [webpack/webpack#2608]
```js
System.import('1.js')
System.import('2.js')

// After `ExtractTextPlugin.extract('style')` , output:
// 1.js, 1.css, 2.js, 2.css
```

How to inline the css, get a new full-bundle like:

 `1.js` = `1.js` + `1.css`

It's useful for reduce http request

**Comment by sethkinast** [comment]
Why are you using ExtractTextPlugin if you want to inline the CSS as part of your JS module?

**Comment by leecade** [comment]
@sethkinast
I use `System.import` to split files and there is a big entry js, extract `entry.css` is a better way, not sure maybe I can ignore extract css from chunk files

**Comment by sokra** [comment]
> not sure maybe I can ignore extract css from chunk files

There is an option in the ExtractTextPlugin: `allChunks`, it defaults to `false`. So by default it should ignore css in chunks.

**Comment by leecade** [comment]
Great @sokra thank yo

**Comment by monkindey** [comment]
hi , @leecade , I suffering the react-router code splitting. When I switch different route and just download this route's static file, the js is OK, but the css not work. Can you provide your webpack.config.js or any suggestion to make it ?
