### ISSUE TITLE
ProgressPlugin Support for Webpack 1

### ISSUE THREAD

**Issue by serena-w** [webpack/webpack#2609]
Are there any plans to backport this commit https://github.com/webpack/webpack/commit/46b12b2095577391fbd88b6d29b7f0b858db4c5c to Webpack 1? It would be useful to have this feature for Webpack 1 so that we can see the live progress output when using the NodeJS API as discussed in this issue https://github.com/webpack/webpack/issues/1000.

**Comment by neutraali** [comment]
+1

**Comment by bebraw** [comment]
As a workaround you could try extracting it as `progress-webpack-plugin` (free atm) and consuming it from there for webpack 1. This assumes there haven't been any breaking changes in the API it uses.

**Comment by bebraw** [comment]
This probably isn't going to happen. If you want the plugin for webpack 1, you could try pushing it as a standalone package to consume.
