### ISSUE TITLE
records not working as expected.

### ISSUE THREAD

**Issue by kentcdodds** [webpack/webpack#2614]
My assumptions are based on [this gist](https://gist.github.com/sokra/ff1b0290282bfa2c037bdb6dcca1a7aa) from @sokra.

Specifically in `Level 3`:

> Changes to the code base invalidate only affected chunks. Font, images, etc. are only invalidated on change.

Here's a quick screencast demonstrating what I'm seeing: https://youtu.be/zWbFosBhea8

And here's the code: https://github.com/kentcdodds/es6-todomvc/tree/lesson/hashing-even-better

I feel like I either must be doing something wrong, misunderstanding the feature, or there's a bug.

**Comment by sokra** [comment]
That's the tricky part... You missed one step:

> Use an inlined manifest chunk to move the chunkhash mapping into the HTML file. (CommonsChunkPlugin with minChunks: Infinity and inline the resulting file)

Here it's explained with more details: https://github.com/webpack/webpack/tree/master/examples/chunkhash

Here is why:

Somewhere there must be a list of all chunkhashs so the runtime can load them. This list is included the entry chunk. This means in you case it's in the vendor file. As the chunkhashs list always changes when any chunkhash changes the vendor chunk is updated too often. The trick above inlines it into the html file.

There is an possible optimization to this process, but nobody implemented it yet. You can store the chunkhash map in a global variable (via plugin) and inline only this smaller json file into the HTML. This would inline less code, meaning more code is cached. But the difference is not soo big (1kb).

**Comment by kentcdodds** [comment]
Hmmm... I'll give it a look tomorrow. Not certain I understand. But thanks for explaining!
