### ISSUE TITLE
Sourcemapped code is truncated in Chrome Developer Tools

### ISSUE THREAD

**Issue by praveenaj** [webpack/webpack#2615]
All the source files found inside webpack:// in Chrome developer tools are missing a large portion of code and they all end with a similar comment line `WEBPACK FOOTER`. I'm trying to debug React and a npm module that I'm working on. I'm unable to evaluate code/set breakpoints because of this. Any clue? I tried uninstalling Chrome, deleting Profile data (Mac OS)
ex:

``````
module.exports = {
  areSame: function (values) {
    var isUniq = false;
    for (var i = 0, l = values.length; i < l; i++) {
      var next = values[i+1];
      var curr = values[i];
      if (next) {
        isUniq = next === curr;
      }
    }
    return isUniq;
  }
};



/*****************
 ** WEBPACK FOOTER
 ** ./src/components/SomeComponent.js
 ** module id = 623
 ** module chunks = 0
 **/```
``````

**Comment by rafde** [comment]
I think this is resolved and can be closed. I haven't found any issues, and I have a common chunk file that is 5mb in size.
