### ISSUE TITLE
hoisting harmony exports can break order-dependent code in webpack 2.1.0-beta.12

### ISSUE THREAD

**Issue by willheslam** [webpack/webpack#2618]
I'm using Babel 6, Webpack 2.
This wasn't an issue with v2.1.0-beta.8, but since I upgraded to v2.1.0-beta.12, I assume the problem is this commit:
https://github.com/webpack/webpack/commit/0bd5d281e297a615ed688cabe55e82a592fc20db
to hoist harmony exports.
(I could be totally wrong here - I'm not sure exactly how it works, just guessing it is putting harmony exports up near the top of chunks) 

It could be something else between those two releases though!

Here's an example from rxjs-es 5.0.0-beta.7 (though it could affect other rxjs versions):
File is rxjs-es/util/assign.js
```
import { root } from './root';
const Object = root.Object;
if (typeof Object.assign != 'function') {
    (function () {
        Object.assign = function assignPolyfill(target, ...sources) {
            if (target === undefined || target === null) {
                throw new TypeError('Cannot convert undefined or null to object');
            }
            const output = Object(target);
            const len = sources.length;
            for (let index = 0; index < len; index++) {
                let source = sources[index];
                if (source !== undefined && source !== null) {
                    for (let key in source) {
                        if (source.hasOwnProperty(key)) {
                            output[key] = source[key];
                        }
                    }
                }
            }
            return output;
        };
    })();
}
export const assign = Object.assign;
//# sourceMappingURL=assign.js.map
```

which is transformed into:
```
/* 346 */
/***/ function(module, exports, __webpack_require__) {

	"use strict";
	/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__root__ = __webpack_require__(9);
	
	/* harmony export */ Object.defineProperty(exports, "a", {configurable: false, enumerable: true, get: function() { return assign; }});
	var Object = __WEBPACK_IMPORTED_MODULE_0__root__["a" /* root */].Object;
	if (typeof Object.assign != 'function') {
	    (function () {
	        Object.assign = function assignPolyfill(target) {
	            if (target === undefined || target === null) {
	                throw new TypeError('Cannot convert undefined or null to object');
	            }
	            var output = Object(target);
	
	            for (var _len = arguments.length, sources = Array(_len > 1 ? _len - 1 : 0), _key = 1; _key < _len; _key++) {
	                sources[_key - 1] = arguments[_key];
	            }
	
	            var len = sources.length;
	            for (var index = 0; index < len; index++) {
	                var source = sources[index];
	                if (source !== undefined && source !== null) {
	                    for (var key in source) {
	                        if (source.hasOwnProperty(key)) {
	                            output[key] = source[key];
	                        }
	                    }
	                }
	            }
	            return output;
	        };
	    })();
	}
	var assign = Object.assign;
	//# sourceMappingURL=assign.js.map

/***/ },
```

because the const is turned into var and vars hoist (this I believe would also be a problem with const, potentially causing some kind of temporal dead zone issue), and the harmony export is put above that,
```
	/* harmony export */ Object.defineProperty(exports, "a", {configurable: false, enumerable: true, get: function() { return assign; }});
	var Object = __WEBPACK_IMPORTED_MODULE_0__root__["a" /* root */].Object;
```
is interpreted as
```
       var Object = undefined;
	/* harmony export */ Object.defineProperty(exports, "a", {configurable: false, enumerable: true, get: function() { return assign; }});
       Object = __WEBPACK_IMPORTED_MODULE_0__root__["a" /* root */].Object;
```
which throws
`Uncaught TypeError: Cannot read property 'defineProperty' of undefined`

Oops! This was working with v2.1.0-beta.8, I don't know the rationale of hoisting harmony exports - maybe we can isolate the effect of hoisting them, or is the nature of JS going to make this always potentially unsafe?

My dev dependencies are:
```
    "babel-loader": "^6.2.4",
    "babel-plugin-syntax-trailing-function-commas": "^6.8.0",
    "babel-plugin-transform-decorators": "^6.8.0",
    "babel-plugin-transform-function-bind": "^6.8.0",
    "babel-plugin-transform-node-env-inline": "^6.8.0",
    "babel-plugin-transform-object-rest-spread": "^6.8.0",
    "babel-plugin-transform-react-constant-elements": "^6.8.0",
    "babel-plugin-transform-react-inline-elements": "^6.8.0",
    "babel-preset-es2015": "^6.6.0",
    "babel-preset-es2015-webpack": "^6.4.0",
    "babel-preset-react": "^6.5.0",
    "webpack": "^2.1.0-beta.8"
```

I'm using the Webpack DedupePlugin and UglifyJSPlugin.

I get exactly the same problem when I turn off the babel transforms (function-bind, object-rest-spread, decorators, node-env-inline, syntax-trailing-function-commas, transform-react-constant-elements and transform-react-inline-elements) and the Webpack plugins listed above.

Using Webpack v2.1.0-beta.11 also gave me the same problem.

Please let me know if I can provide any more information about my build set up.

**Comment by sokra** [comment]
Oh that's any tricky edge case. I try to solve it...

**Comment by ndp** [comment]
I apologize for commenting on a closed bug. I've been unable to get rxjs-es to work well, and this seemed like the same hoisting problem still. As stated in the bug above, ES6 code:
```
  // assign.js of RxJS
  import { root } from './root';
  const Object = root.Object;
```
converts to `var Object = _root.root.Object;`, which has the `Object` var that is hoisted and masks webpack code trying to build the exports. When I rewrite the function with `const obj = root.Object;`, the problem is avoided. 

 It does seem like it may be cleanly stated:

>    If within an imported es6 module you use the construct `const Object = [anything]` 
>    to define a local const/variable, the code generated by Webpack creates a local `var` 
>    named `Object` that interferes with the ability of webpack to bundle, breaking lines
>    such as `Object.defineProperty(...)`.
> 

So... using `Object` as your own variable seems like a risky prospect, but I don't see it's a reserved word (http://www.ecma-international.org/ecma-262/6.0/#sec-reserved-words), so I am assuming this is legit and should be supported.

I've tried a few combinations Webpack 2.1.0-beta-8, 11, 12, 20 with similar versions as listed above and rxjs-es v5.0.0-beta.10. 

Here's one set of deps that fails:
    "babel-loader": "^6.2.4",
    "babel-preset-es2015": "^6.6.0",
    "babel-preset-es2015-webpack": "^6.4.0",
    "copy-webpack-plugin": "^0.2.0",
    "webpack": "^2.1.0-beta.12",
    "rxjs-es": "^5.0.0-beta.10",
    "webpack-dev-server": "latest"

Here is  a repo where I was able to isolate it, if that will help:
https://github.com/ndp/tests/tree/rxjs-es-babel-hmmm

**Comment by Kovensky** [comment]
This would still be a problem even without webpack converting the `const Object` to `var Object`. `Object` would just be in the temporal dead-zone when the import runs.

The only ways around it is to either internally rename the module-scope `Object` to, say, `_Object`, or use `global.Object` in places where webpack tries to call into `Object`...

**Comment by sokra** [comment]
I'll move the export statements into the runtime, as this is repeated often anyway.

**Comment by Kovensky** [comment]
Or that :D
