### ISSUE TITLE
Add an option to auto-detect third-party packages

### ISSUE THREAD

**Issue by kripod** [webpack/webpack#2626]
When using `CommonsChunkPlugin`, each third-party dependency must be added to `webpack.config.js` by hand. A plugin with the name`AbstractAwayDependencies` could be written to provide the functionality of abstracting away npm dependencies from the code into a separate file. (By default, `vendor-[hash].js`.)

**Comment by drew-walker** [comment]
In our project we create a file at ./src/vendor.js, then create an entry point to that file. This means you can keep your common dependencies out of the webpack config file. e.g.

**webpack.config.js (abbreviated)**

```
module.exports = {
    entry: {
        'app': ['./src/index'],
        'vendor': ['./src/vendor']
    },
    plugins: [
        new webpack.optimize.CommonsChunkPlugin({ names: ['vendor'] }),
    ]
}
```

**./src/vendor.js**

```
import 'react';
import 'react-dom';
import 'react-intl';
import 'react-router';
import 'react-document-title';
import 'react-redux';
import 'redux';
import 'redux-router';
import 'redux-thunk';
import 'classnames';
import 'history';
import 'immutable';
import 'underscore';
```

Is this what you meant?

**Comment by kripod** [comment]
I mean that webpack could probably auto-detect non-local dependencies: the name of a non-local dependency starts with an alphanumeric character (`0-9`, `a-Z`), while the name of a local dependency starts with `.`.

My wish is to be able to use a vendor chunk splitting plugin without explicitly declaring non-local dependencies.

**Comment by sokra** [comment]
This automatically selects modules based on the path:

``` js
new webpack.optimize.CommonsChunkPlugin({
  name: 'vendor',
  minChunks: function(module) {
    return module.resource && /node_modules/.test(module.resource)
  }
}),
```

But specifying dependencies manually has the advantage that the vendor chunk changes less often.

**Comment by kripod** [comment]
Whoa, thank you for the tip! The name of the `minChunks` property has become pretty misleading in this case, though.

I would be happy if such functionality could be abstracted to the `AbstractAwayDependenciesPlugin`.

**Comment by sokra** [comment]
Free free to publish it as own repo.

**Comment by Fouzyyyy** [comment]
Hi all,

There is a way to specify implicitly your prod dependencies, here is the trick:

- Go to your webpack.config.js file, and add the following module import statement:
`const prodDependencies = require('path to your package.json file');`

- now you need to update your entry points:
`entry: {
    vendor: Object.keys(prodDependencies.dependencies)
    // make sure the name you choose for this entry is the same you use for your 
   // CommonsChunkPlugin configuration so that you can move your redendent prod dependencies to that 
   // file as well
}`
