### ISSUE TITLE
webpack uses removed plugin

### ISSUE THREAD

**Issue by andrewQwer** [webpack/webpack#2629]
Hi guys, 

I use different webpack configs depending on environment, like dev, prod etc. My prod config includes UglifyJsPlugin. At some point I decided to remove this plugin from prod config for debugging but surprisingly running webpack for prod showed that UglifyJsPlugin was still in use. I don't have any references to this plugin but webpack somehow still uses it. I tried to null plugins section `plugins: []` and `plugins: null` but with no luck. Is there any cache I can clean for webpack?
My config structure looks like this:
webpack.common.js
webpack.dev.js
webpack.production.js

I merge dev/prod configs with common part.

**Comment by andrewQwer** [comment]
I interesting point: if I rename prod file to something custom like webpack.custom.js then production config doesn't use UglifyJsPlugin, but I just renamed it and nothing more.

**Comment by bebraw** [comment]
How are you referring to the configuration? Can you post your possible **package.json** `scripts`? There's not enough info to say anything concrete.

**Comment by andrewQwer** [comment]
```javascript
var colors = require('colors');
var validate = require('webpack-validator');
var path = require('path');
var args = process.argv.slice(2);

var configNames = {
    'dev': path.join(__dirname, 'webpack.dev.js'),
    'dev-watch': path.join(__dirname, 'webpack.dev-watch.js'),
    'prod': path.join(__dirname, 'webpack.production.js')
};

var webpackEnv = args[0];
//if the parameter is passed with dash symbol, we need to remove it to get correct config name
if (webpackEnv && webpackEnv.charAt(0) === '-') {
    webpackEnv = webpackEnv.substr(1);
}

var env = webpackEnv || process.env.npm_package_config_webpack_env || 'dev-watch';
console.log(colors.green('Webpack is running in %s mode'), env);
var config = require(configNames[env]);
module.exports = validate(config);
```
This is how I reference my configs,
I run webpack this ways:
`webpack -dev` or `webpack -prod`
My dev dependencies:
```
"devDependencies": {
    "autoprefixer": "6.3.6",
    "babel-core": "6.9.1",
    "babel-loader": "6.2.4",
    "babel-preset-es2015": "6.9.0",
    "babel-preset-react": "6.5.0",
    "bower": "1.7.9",
    "clean-webpack-plugin": "0.1.9",
    "colors": "1.1.2",
    "css-loader": "0.23.1",
    "expose-loader": "0.7.1",
    "extract-text-webpack-plugin": "1.0.1",
    "file-loader": "0.8.5",
    "node-sass": "3.7.0",
    "postcss-loader": "0.8.2",
    "react-addons-perf": "15.1.0",
    "resolve-url-loader": "1.4.3",
    "sass-loader": "3.2.0",
    "url-loader": "0.5.7",
    "webpack": "1.13.1",
    "webpack-merge": "0.14.0",
    "webpack-notifier": "1.3.0",
    "webpack-validator": "2.1.2"
  }
```

**Comment by bebraw** [comment]
One option. Webpack might parse `webpack -prod` as `webpack -p`. That will inject the uglify plugin. You would have to log webpack bin logic to say for sure.

**Comment by bebraw** [comment]
You could see if changing `env` to form like `var env = process.env.npm_lifecycle_event;` and webpack invocation to just `webpack` would help. This way it parses the target from npm script run.

**Comment by andrewQwer** [comment]
> You would have to log webpack bin logic to say for sure.

Could you please point me how to make this log?

**Comment by bebraw** [comment]
[convert-argv.js](https://github.com/webpack/webpack/blob/webpack-1/bin/convert-argv.js) might be a starting point.

You could also try simplifying the configuration as I suggested. If the simplification works, then it likely interprets `-prod` as `-p`.

**Comment by andrewQwer** [comment]
> You could also try simplifying the configuration as I suggested. If the simplification works, then it likely interprets -prod as -p.

Yeah, I am testing this suggestion and looks like you are right. Could you show me in the documentation why -p argument is treated for UglifyJsPlugin injection?

**Comment by bebraw** [comment]
[Here](https://github.com/webpack/docs/wiki/cli#production-shortcut--p).

This is actually a bug. Matching `-prod` feels wrong. I'll mark this as such.

**Comment by andrewQwer** [comment]
Thanks. Could you please also take a look at -d parameter? Currently we use `-dev` as argument and this could also affect our configuration in a wrong way

**Comment by bebraw** [comment]
Given there's `-d`, it could be the same, yeah. I would suggest branching as discussed above to avoid potential issues. 👍 

Webpack 2 will support `--env dev` kind of syntax.

**Comment by sokra** [comment]
`-prod` is a shotcut for `-p -r -o -d`.

**Comment by bebraw** [comment]
Ah, of course... Safe to close then I guess. 👍

**Comment by andrewQwer** [comment]
Thank you guys for your help
