### ISSUE TITLE
how i can use export default and require (webpack2)

### ISSUE THREAD

**Issue by arshtepe** [webpack/webpack#2631]
t.js: 
```js
export default class {

}
```
index.js:
```js
const cls = require("./t");

export default class PreferenceOmitDialogCondition extends cls {

}
```
**i know that i can  require("./t").default , but i have many old code and it difficult change.**

**Comment by TheLarkInn** [comment]
Is there a reason you are opposed to using: 

`import cls from './t';`

**Comment by arshtepe** [comment]
@TheLarkInn I know but i have very very big project and can not change it, and i need compatibility . Is exists solution  ?

**Comment by also** [comment]
Can you change `t.js`? If you want to use CommonJS `require`, you'll want to also use CommonJS exports. This will allow you to `require('./t')`:

**t.js**:
```js
module.exports = class {
}
```

Otherwise, using Babel and a plugin like [add-module-exports](https://github.com/59naga/babel-plugin-add-module-exports)] could help.

**Comment by arshtepe** [comment]
@also I can't change t.js it is as blackbox. This plugin not work on this code:
LinkUtils.js
```js
export default class {
    static getObjectParamsFromUrl() {
       ...code
    }
}
```
RouterHashParams:
```js
import LinkUtils from "./common/LinkUtils";
export default class RouterHashParams {

    constructor() {
        let linkParams = LinkUtils.getObjectParamsFromUrl();
    }
}
```
because after build i have:
RouterHashParams: 
```js
var __WEBPACK_IMPORTED_MODULE_2__common_LinkUtils__ = __webpack_require__(28);
  	class RouterHashParams {

	    constructor() {
	        let linkParams = __WEBPACK_IMPORTED_MODULE_2__common_LinkUtils__["a" /* default */].getObjectParamsFromUrl(); <<<< "a" overridden by  exports["default"]
           ....

```
LinkUtils
```js
/* harmony default export */ exports["a"] = class {
	    static getObjectParamsFromUrl() { 
            }
   ...
module.exports = exports["default"]; // <<<<<<<<<------- override exports
```

**Comment by arshtepe** [comment]
Why after build i have exports["a"] and exports["default"] ?

**Comment by sokra** [comment]
Don't mix babel es6 module handling with webpacks. webpack allows to mix CommonJs and ES6 modules this way:

``` js
// es6.js
import something from "./commonjs";

export default "xyz";
export var abc = "abc";
```

``` js
// commonjs.js
var xyz = require("./es6").default;
var abc = require("./es6").abc;

module.exports = "something";
```

Don't use the add-module-exports plugin.

PS: `exports.a` is used instead of `exports.default` when a es6 module is only imported via es6 imports. webpack mangles the export names.

**Comment by arshtepe** [comment]
@sokra  Yes, i know, but how i can solve this problem if i have code ashttps://github.com/webpack/webpack/issues/2631#issue-159642878 and i cannot change him ?

**Comment by sokra** [comment]
The code is wrong. Change it.

**Comment by earksiinni** [comment]
I'm having a related problem. I have a module that looks like this (note, I'm using Babel's `transform-class-properties` plugin, hence the class properties syntax):

```
import { observable } from 'mobx';

class AppStateStore {
  @observable firstName = 'hi';
  @observable lastName = '';
  @observable phoneNumber = '';
  @observable mail = '';
  @observable city = '';
  @observable referralCode = '';
  @observable backgroundCheckOk = false;

  constructor() {}
}

let appStateStore = new AppStateStore();

//module.exports = appStateStore;
export default appStateStore;
```

Then I shim the module using `ProvidePlugin` like so:

```
plugins: [
  new webpack.ProvidePlugin({
    'app.state': 'stores/app_state.js'
  })
]
```

Then when I call `app.state`, I get an object that has a property called `default` that has all of the properties like `firstName`, `lastName`, etc. But that's wrong, there shouldn't be any property called `default`. `app.state` should simply point to the instance that I created.

On the other hand, when I use commonJS-style exporting (i.e., `module.exports = appStateStore`), it works perfectly.

What gives?
