### ISSUE TITLE
add an option to generate sourcemap that doesnt have any sourcecode

### ISSUE THREAD

**Issue by psabharwal123** [webpack/webpack#2634]
Hi
It would be nice to be able to generate sourcemap that doesnt have embedded source code so that i can still use it in production but end users wont see the source code. When i have to debug i can point chrome to the source files (to which only i have access). Currently devtools:sourcemap generates a sourcemap file with source code embedded.

**Comment by sokra** [comment]
Put the source-map into a password protected folder.

**Comment by psabharwal123** [comment]
chrome wont download the password protected assetmap. how would i do that?

**Comment by bebraw** [comment]
Note that there's something known as hidden sourcemap now. It will give you only stacktraces. A little harder to find at least.

But as Tobias said, it's a concern that goes beyond webpack. Not much we can do there.
