### ISSUE TITLE
Sourcemap broken

### ISSUE THREAD

**Issue by justme1** [webpack/webpack#2636]
Hi all,

I have been working on an Angular2 + Webpack project and debugging my app using Chrome worked perfectly. But suddenly now when I put breakpoint I get into a different file and not to the right line. It seems like the sourcemap got broken. 

What may cause this issue? I've been working on this project for the last month and it worked perfectly, but now suddenly it is broken. Even if I go back to older commits which I'm sure it worked it's not working anymore.

**Comment by steida** [comment]
I think it's broken Chrome https://github.com/facebook/react-native/issues/7820

**Comment by justme1** [comment]
It works in Chromium version.
Great catch steida, thanks a lot!
