### ISSUE TITLE
CommonsChunkPlugin loses modules that css-loader injected when use ExtractTextPlugin

### ISSUE THREAD

**Issue by dexbol** [webpack/webpack#2637]
Reproduce demo: https://github.com/dexbol/webpack-problem

Reproduce situation:
1. Require a css file in the entry chunk, and require css files in asynchronous
   chunks that created by `require.ensure`.
2. Use CommonsChunkPlugin.
3. Use ExtractTextPlugin(only extract from the entry chunk).
4. The modules that css-loader injected lose:

```
Uncaught TypeError: Cannot read property 'call' of undefined
```

Please see the webpack config and details in the demo above.

**Comment by gagayang** [comment]
I have the same situation

**Comment by bebraw** [comment]
Can you try against webpack 2?

**Comment by dexbol** [comment]
webpack@2.2.0-rc.2 and extract-text-webpack-plugin@2.0.0-beta.4 WORK.
