### ISSUE TITLE
export ModuleFilenameHelpers

### ISSUE THREAD

**Issue by sashee** [webpack/webpack#2640]
I've written a plugin that does some obfuscation, and I've started out from the UglifyJsPlugin (https://github.com/webpack/webpack/blob/master/lib/optimize/UglifyJsPlugin.js). The plugin uses ModuleFilenameHelpers, which seems like an internal dependency, as it is not exported (https://github.com/webpack/webpack/blob/master/lib/webpack.js#L65).

I think it should be exported, so that external plugins can import it as `require("webpack").ModuleFilenameHelpers;` instead of `require("webpack/lib/ModuleFilenameHelpers.js");`

**Comment by sokra** [comment]
yep, feel free to send a PR.

**Comment by mxstbr** [comment]
I think this was fixed with 668121453d4158224f79347de685aa466b58c0b3, can be closed.
