### ISSUE TITLE
moduleExtensions should enforce `-loader`, not duplicate.

### ISSUE THREAD

**Issue by ericclemmons** [webpack/webpack#2642]
# I'm submitting a...
- [x] bug report

**Webpack version:**
2.1.0-beta.13

**Please tell us about your environment:**
OSX 10.11.5

**Current behavior:**
When loaders are defined with `-loader` (e.g. `babel-loader`), because the default value of `moduleExtensions` is `-loader`, module resolution attempts to find `babel-loader-loader`, which causes an erroneous `npm install` with this plugin:

> https://github.com/ericclemmons/npm-install-webpack-plugin

**Expected/desired behavior:**

Expected that that this _enforces_ the `-loader` extension, so that `babel` becomes `babel-loader`.  It should noop if `/-loader$/` matches.
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.** 

I believe this is due to these two files:

> https://github.com/webpack/enhanced-resolve/blob/d154f01b6f74b90f3ac3c5ea6cca89abead5236c/lib/ResolverFactory.js#L164-L169
> https://github.com/webpack/enhanced-resolve/blob/master/lib/ModuleAppendPlugin.js

**Comment by bebraw** [comment]
Can you check this against webpack 2 rc?

**Comment by bebraw** [comment]
Please re-open if you see this still.
