### ISSUE TITLE
Webpack replacing require.extensions with (void 0)

### ISSUE THREAD

**Issue by Itagiba** [webpack/webpack#2643]
I am using [ignore-styles](https://github.com/bkonkle/ignore-styles) So that babel-register handles sass/css files without trying to process them as .js. I am using [material-ui](http://www.material-ui.com/#/) and more specially the drawer menu. However when I build my project with webpack I get the following error:

`ignore-styles.js:45 Uncaught TypeError: Cannot read property '.css' of undefined`

And the Drawer does not work.

This is what it is pointing to in ignore-styles.js (45):

```
    oldHandlers[ext] = (void 0)[ext];
    (void 0)[ext] = handler;
  }
```

The code should be:

```
 oldHandlers[ext] = require.extensions[ext]
    require.extensions[ext] = handler
```

As indicated by the author of ignore-styles and it seems webpack is replacing require.extensions with (void 0).

I Installed this loader for webpack:

    { test: /\.css$/,
      loader: 'ignore-loader'
    },

Then for my scss:

    // Extract SCSS
    { test: /\.scss$/,
      loader: ExtractTextPlugin.extract("style-loader", "css-loader!sass-loader", 'ignore-loader')
    },
But it is making no difference whatsoever. I have tried using other drawer menus and get the same error. Why is webpack doing this?

**Comment by sokra** [comment]
webpack doesn't support `require.extensions` (there is an error emitted too). Modules relying on it are probably not webpack/browser-compatible.

**Comment by foxhound87** [comment]
Getting similar error: `TypeError: Cannot read property '.js' of undefined`
I'm not using `ignore-styles`, but maybe can be related to `material-ui`? I'm not sure.

After building with webpack (v1.13.1), 

Error thrown here: `oldHandlers[ext] = (void 0)[ext];` in `hookExtensions()`

Complete description: https://github.com/webpack/webpack/issues/2852
