### ISSUE TITLE
HMR runtime fails to run dependency accept handlers when a non-handled child is in the same update as an accepted one

### ISSUE THREAD

**Issue by Kovensky** [webpack/webpack#2648]
Possibly a bug with Harmony modules, but I am not sure.

`getAffectedStuff` in HotModuleReplacement.runtime.js calls `delete outdatedDependencies[parentId]` every time a dependency is not in the parent's `parent.hot._acceptedDependencies`, which might happen when a module is directly (or indirectly) required by multiple parents and any of the parents doesn't have an accept handler.

Removing it from `outdatedDependencies` then prevents the accept handlers from running.

**Comment by Kovensky** [comment]
The screenshot provided in #2649 happens to show one case that is affected by this.

It looks like the situation is hairier and kinda opposite than what I actually described above.

`getAffectedStuff` returns modules `[175, 299, 287, 174, 118, 300, 279, 805]` (the first time) in that example. Module 175 is the file that was edited.

Module 175 is required by 299 and 287. 287 is required by 174. 174 is required by 118. 118 re-exports one of the symbols imported from 174.  299 is required by 300. 279 is the entry point, and it requires both 118 (including the reexported symbol) and 300. 805 is webpack's multi loader. ASCII art representation:

```
    /---- 299 - 300 ----\
175 -- 287 - 174 - 118 -- 297 - 805
```

Module 279 requires 118 and registers an accept handler for it. `getAffectedStuff` first processes 118, sees its parent 279 has an accept handler, and sets `outdatedDependencies[279] = [118]`. When `getAffectedStuff` then gets around to 300, it sees that it also has parent `279`, and proceeds to delete `outdatedDependencies[279]`, preventing the accept handler from running and thus ruining everything.

**Comment by sokra** [comment]
The accept handler in a module is only called when the module is not disposed, because a module don't need to update it's dependency if it will be disposed anyway.

If there would be no connection between 299 and 300 the accept handler in 297 would be called and 297 would not be disposed. But there is this (unaccepted) way 175 -> 299 -> 300 -> 297 which means 297 must be disposed and accept handlers are not called.

Normally when an update bubbles up to the entry point the HMR fails and the page is reloaded. But this doesn't happen here (which is a bug). I assume you are using the CommonsChunkPlugin?

**Comment by Kovensky** [comment]
Yes, I am using CommonsChunkPlugin.

What I am trying to do here is hot-reloading redux reducers. 175 defines a reducer and it's action creators, 174 is the root reducer, 118 is a store factory. 297 sets up a store with the factory, and (tries to) accept changes to the store factory. As the store factory reexports the root reducer, this also depends on the root reducer (it would've been directly imported anyway otherwise).

299 is a component that happens to use 175's action creators, so it also appears in the chain. They're both Harmony modules, so in theory if 175 gets updated, the binding that 299 sees should be updated as well, even without a specific accept in here.

It looks like I can work around the issue by splitting the reducer and action creator files (and not adding a wrapper index.js that reexports them), but this makes the "user" API less ergonomic...

**Comment by sokra** [comment]
> so in theory if 175 gets updated, the binding that 299 sees should be updated as well, even without a specific accept in here.

You still need to accept it. But you can omit the accept handler in this case: `module.hot.accept(175)`

**Comment by Kovensky** [comment]
I see. So the problem is that the update is not outright rejected by the runtime for not having accepters in all paths.

This does look like it'd be hard to debug in some cases, though ("why is this module not hot reloading, I have accept handlers everywhere (\*but one place I don't realise)"), but I guess fully refusing it is better than incorrectly accepting it.

**Comment by Kovensky** [comment]
@sokra Is `only-dev-server` supposed to give `{ ignoreUnaccepted: true }` to apply? This prevents it from rejecting the update (and explaining why). `only-dev-server` is then just supposed to not reload, but it still should output diagnostics.

**Comment by sokra** [comment]
> This does look like it'd be hard to debug in some cases, though ("why is this module not hot reloading, I have accept handlers everywhere (*but one place I don't realise)"), but I guess fully refusing it is better than incorrectly accepting it.

We could add some more information to the message, including the path from the updated module to the root.

**Comment by sokra** [comment]
The HMR runtime was improved. Error message was improved.
