### ISSUE TITLE
HMR runtime unconditionally destroys installedModules cache

### ISSUE THREAD

**Issue by Kovensky** [webpack/webpack#2649]
This deletes all dependency information for the modules, which makes future hot reloads unable to propagate accepts, disposes or rejects.

Here's a screenshot of a debugging session, showing the first result of `getAffectedStuff` between the first and the second hot reloads of a session, as well as the state of `installedModules` and `modules`:
![](http://puu.sh/ptITE/0d34bc44df.png)

This seems to be an issue specific to Harmony modules. **All** `moduleId`s that were `outdatedModules` in the previous hot reload got deleted from `installedModules` (as part of the `dispose` step in `hotApply`), but never restored, as Harmony modules don't call `require`/`__webpack_require__` in their accept handlers; CommonJS accept handlers happen to do so, so they regenerate the caches.

**Comment by Kovensky** [comment]
Hm, it seems that this bug is indirectly caused by #2648, as there is a generated wrapper function that is supposed to call `__webpack_require__`.

**Comment by sokra** [comment]
I think this was fixed
