### ISSUE TITLE
Source-Map is picking random files

### ISSUE THREAD

**Issue by Vaccano** [webpack/webpack#2650]
- [x] bug report

Here are my versions:
Webpack: 1.12.14
Windows 7

Browsers:
Fails in:
Chrome: 51.0.2704.84

Works in:
IE 11, 
Chrome 53.0.2767.0 canary (64-bit)

Language:
TypeScript

Bug:
When I select a file in the chrome debugger, the file that actually opens is a random file from my project.

For example, I have the following file: `/src/views/configuration/configuration-vm.ts.`

When I open this file in the chrome debugger, a random file is loaded from my project instead.  The random file is sometimes a .ts or a .html file.  (However, the CSS files seem unaffected.)

NOTE: The WEBPACK FOOTER clearly says what the file name is along with its module ID.

The odd thing is that I have not updated WebPack for over a month.   

I tried this on Chrome Canary and it works fine. (Version 53.0.2767.0 canary (64-bit))  It also seems to work fine in Internet Explorer 11.

Just Chrome Stable seems to have this bug.

**Comment by egucciar** [comment]
+1 have same issue in Chrome v51, will try canary now. thanks!

**Comment by mmmeff** [comment]
Been seeing this in Webpack 2 as well for the past couple weeks. I have a feeling it might be Babel related

**Comment by Vaccano** [comment]
@mmmeff - I do not use Babel at all.  Just TypeScript to JavaScript.

**Comment by mmmeff** [comment]
Weird. Maybe this is a chrome bug then? I'm clueless.

Been seeing the sourcemap entirely failing to load in console messages lately too.

**Comment by egucciar** [comment]
@mmmeff if its bothering you just use Chrome canary for now. I did, very happy!

**Comment by mmmeff** [comment]
@egucciar Is this a known chrome bug then? Link?

**Comment by egucciar** [comment]
@mmmeff The OP mentions the source map works in Chrome canary so I tried that. Maybe someone should file this as a Chrome bug instead?

**Comment by mmermerkaya** [comment]
For me it works when I use `eval-source-map` or `cheap-eval-source-map`, but not without `eval`.

**Comment by DanielSundberg** [comment]
I have started to see this as well with Chrome 51.0.2704.103/webpack 3.5.3/Windows 10. Don't know exactly when it started since I don't do JS debugging every day. <code>eveal</code> works here too but since I'm using Babel and ES6 it's not optimal.

**Comment by bebraw** [comment]
Closing as this has been fixed in upstream (Chrome).
