### ISSUE TITLE
:bug: Inconsistent Path Resolving For Entry Module

### ISSUE THREAD

**Issue by dodekeract** [webpack/webpack#2656]
## :bug: Inconsistent Path Resolving For Entry Module

**Webpack version:** 1.13.1
**Language:** all
**OS:** Ubuntu 16.04
**Type:** Bug Report
#### When It Works:
- `example.js` and `example/` exist
- `webpack example bundle.js`
- :arrow_right: WebPack compiles
#### When It Doesn't Work Because Of Inconsistencies
- `example.js` exists, but **there is no `example/` folder**
- `webpack example bundle.js`
- :arrow_right: WebPack throws this error:

`ERROR in Entry module not found: Error: Cannot resolve module 'example' in /path/this/test/was/launched/in`
### Expected behavior:

a) WebPack correctly resolves the path and starts compiling.
b) WebPack throws an error in both cases and doesn't compile anything
### Simple Steps To Reproduce
1. place this `package.json` in an empty folder

``` json
{
    "scripts": {
        "a": "mkdir a && touch a.js && webpack a bundle-a.js",
        "b": "touch b.js && webpack b bundle-b.js"
    },
    "dependencies": {
        "webpack": "^2.2.0-rc.3"
    }
}
```

2, `npm i`
3. `npm run a`
4. `npm run b`

**Comment by TheLarkInn** [comment]
@dodekeract when you are able to reproduce this behavior: 

1. Do you have a package.json file in the project root? 
2. If yes, what is the 'main:' property set to (if there is one)

**Comment by sokra** [comment]
webpack accepts either a file or a module request on command line.

`example.js` is a file, `./example` is the module request.

For files you can't omit the extensions. (`rm example` neither removes `example.js`).

Relative module requests starts with `./`. `example` will load the npm module named example.

**Comment by dodekeract** [comment]
@TheLarkInn I do have a `package.json`. The `main` is set to `app.js`, which is invalid.

@sokra It did compile fine for me, when I accidentally had the folder in that location.

**Comment by dodekeract** [comment]
Added a really easy reliable repro for this.

**Comment by bebraw** [comment]
Can you try against webpack 2?

**Comment by dodekeract** [comment]
@bebraw Here you go:

## `npm run a`

```
> @ a /Users/dodekeract/webpack2
> mkdir a && touch a.js && webpack a bundle-a.js

Hash: fc76d1849c79aeae5cae
Version: webpack 2.2.0-rc.3
Time: 33ms
      Asset     Size  Chunks             Chunk Names
bundle-a.js  2.51 kB       0  [emitted]  main
   [0] ./a.js 0 bytes {0} [built]
```

## `npm run b`

```
> @ b /Users/dodekeract/webpack2
> touch b.js && webpack b bundle-b.js

Hash: 55d47c95714657d24d56
Version: webpack 2.2.0-rc.3
Time: 21ms

ERROR in Entry module not found: Error: Can't resolve 'b' in '/Users/dodekeract/webpack2'

npm ERR! Darwin 16.1.0
npm ERR! argv "/Users/dodekeract/.nvm/versions/node/v6.9.1/bin/node" "/Users/dodekeract/.nvm/versions/node/v6.9.1/bin/npm" "run" "b"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! @ b: `touch b.js && webpack b bundle-b.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @ b script 'touch b.js && webpack b bundle-b.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     touch b.js && webpack b bundle-b.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dodekeract/webpack2/npm-debug.log
```

## `npm list | grep webpack`

```
/Users/dodekeract/webpack2
└─┬ webpack@2.2.0-rc.3
  ├─┬ webpack-sources@0.1.3
```

**Comment by bebraw** [comment]
Thanks, tagged.

If you could push a test repo, that would be great.

**Comment by dodekeract** [comment]
@bebraw The only thing needed to reproduce this is the package.json I posed above. I think a repo is overkill and would only (further) pollute my GitHub profile. Sorry, but I won't do that for a single file.

**Comment by bebraw** [comment]
Ok, cool.
