### ISSUE TITLE
HMR stops updating after manifest download failure

### ISSUE THREAD

**Issue by amysutedja** [webpack/webpack#2660]
So I'm trying to integrate `react-hot-loader` into my Rails app, and I'm hitting an issue which I think has to do with Hot Module Replacement. I'm using the `only-dev-server` entry point as well as the `NoErrorsPlugin`.

Hot reload works great until I produce a syntax error, which causes this error: `[HMR] Update check failed: Error: Manifest request to http://localhost:3500/805bc20849df335c837e.hot-update.json timed out.` When that happens, HMR stops updating.

It seems like the issue might be here: https://github.com/webpack/webpack/blob/v1.13.1/lib/HotModuleReplacement.runtime.js#L198

When manifest download failure occurs, the value of `module.hot.status()` is never reset back to `idle` -- it just stays at `check`. That causes the status check that occurs before HMR update (https://github.com/webpack/webpack/blob/v1.13.1/hot/only-dev-server.js#L68) to consistently return false.

Webpack Version: 1.13.1

**Comment by bebraw** [comment]
Can you try against webpack 2 and open a separate issue with an example if this is still a problem?
