### ISSUE TITLE
A proposition to refactor for Isomorphism

### ISSUE THREAD

**Issue by ChrisCates** [webpack/webpack#2665]
https://github.com/ChrisCates/An-Open-Letter-to-Facebook-and-Webpack/blob/master/README.md
https://github.com/facebook/react/issues/7077

Would love your feedback, and a clear roadmap for me to implement this.

**Comment by ChrisCates** [comment]
I wrote a first draft of the transpiler. Obviously there are many edge cases. But I believe this should be helpful as a reference:

```
fs.removeSync(__dirname + '/src_prod')

  fs.copySync(__dirname + '/src', __dirname + '/src_prod')

  var asset_urls = [
    '/src_prod/img',
  ]

  var assets = []

  asset_urls.map(function (url) {
    fs.readdirSync(__dirname + url).map(function(file) {
      assets.push(url + '/' + file)
    })
  })

  var component_urls = [
    '/src_prod/components/containers',
    '/src_prod/components/presentation',
    '/src_prod/components/presentation/shared',
    '/src_prod/components/routes'
  ]

  var components = []

  component_urls.map(function (url) {
    fs.readdirSync(__dirname + url).map(function(file) {
      components.push(url + '/' + file)
    })
  })

  components.map(function (url) {
    if (url.match('.js')) {
      var webpack_code = fs.readFileSync(__dirname + url, 'UTF8')
      var deep_tree = url.split('/').length - 3
      var assets_match = []
      assets.map(function(asset) {
        var matching_url = ""
        for (var i = 0; i < deep_tree; i++) {
          if (i < deep_tree - 1) {
            matching_url = matching_url + "../"
          } else {
            matching_url = matching_url + ".."
          }
        }
        matching_url = matching_url + asset
        matching_url = matching_url.replace('/src_prod', '')

        webpack_code = webpack_code.replace('{require(\''+ matching_url +'\')}', '\'' + asset + '\'')

      })

      fs.writeFileSync(__dirname + url, webpack_code)

    }
  })
```

**Comment by sokra** [comment]
> The first inherent design issue with Webpack is that it's designed ONLY for client side rendering. The option to build an isomorphic app and compile Webpack source code to an isomorphic application is not an option.

It's an option: `target: "node"`.

> The proposal is to create a seamless continuous delivery flow that enables you to transpile Webpack code into plain HTML. This would enable you to send server side rendered code on request while also gracefully becoming a client side rendered script once the DOM is registered.

You can do that. It's called SSR (Server-side rendering or prerendering). see `React.renderToString()`.

**Comment by sokra** [comment]
For more details, please ask on StackOverflow. (And ask before claiming that stuff doesn't work)

**Comment by ChrisCates** [comment]
Thanks @sokra
