### ISSUE TITLE
webpack loaders: the "exclude" property is always ignored

### ISSUE THREAD

**Issue by jtiscione** [webpack/webpack#2667]
# I'm submitting a...
- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, see note at the top of this template. 

**Webpack version:**
1.10.x/2.x

**Please tell us about your environment:**
Windows 10

**Current behavior:**

I have bootstrap loaded via npm, and I'm using css-loader. My webpack.config.js has the following:

```
      {
        test: /\.css/,
        exclude: /node_modules/,
        //also tried: exclude: path.resolve(__dirname, 'node_modules'),
        //also tried: exclude: /bootstrap/
        loaders: [
          'isomorphic-style-loader',
          `css-loader?${JSON.stringify({
            sourceMap: true,
            // CSS Modules https://github.com/css-modules/css-modules
            modules: true,
            localIdentName:'[name]_[local]_[hash:base64:3]',
            // CSS Nano http://cssnano.co/options/
            minimize: false,
          })}`,
          'postcss-loader?pack=default',
        ],
      },
      {
        test: /bootstrap\.css$/,
          loaders: [
            'isomorphic-style-loader',
            `css-loader?${JSON.stringify({
              sourceMap: true,
              // CSS Modules https://github.com/css-modules/css-modules
              modules: true,
              localIdentName: '[local]',
              // CSS Nano http://cssnano.co/options/
              minimize: false,
            })}`,
            'postcss-loader?pack=default',
          ],
        },
```

The CSS class names in /node_modules/bootstrap/dist/css/bootstrap.css are being clobbered by the prefixes and suffixes in the first "localIdentName" property.

**Expected/desired behavior:**

I'm trying to handle bootstrap.css separately from the css that I have in my project- specifically I'm trying to have one loader add unique suffixes to the css class names, and one that handles bootstrap.css without changing any class names. 

To reproduce this bug, do the following:

```
git clone https://github.com/kriasoft/react-starter-kit.git
cd react-starter-kit
npm install
npm install --save bootstrap
```

In tools/webpack.config.js, find the loader with test: \/.css/ and replace it with the code above. You also have to add this stuff to avoid stupid errors with glyphicons, fonts etc.:

```
      {  // Loaders needed to avoid Bootstrap 3 problems
        test: /\.eot/,
        loader: 'url-loader?mimetype=application/vnd.ms-fontobject'
      }, {
        test: /\.ttf/,
        loader: 'url-loader?mimetype=application/x-font-ttf'
      }, {
        test: /\.woff/,
        loader: 'url-loader?mimetype=application/font-woff'
      }, {
        test: /\.woff2/,
        loader: 'url-loader?mimetype=application/font-woff2'
      }
```

Then enter the commands

```
npm build
npm start
```

The bootstrap class names are being mangled. You can verify that this is happening by changing

```
localIdentName:'[name]_[local]_[hash:base64:3]',
```

to this:

```
localIdentName: '[local]'
```

Rerun npm build and npm start, and the page looks totally different- showing that bootstrap.css is being processed by the first block despite the exclude /node_modules/ line being present.
- **Language:** [ES6/7]

**Comment by SpaceK33z** [comment]
Could you retry on the latest webpack 2 RC? IIRC there were some issues with this in an earlier beta.
