### ISSUE TITLE
Add an option to disable compilation of source code into sourcemap.

### ISSUE THREAD

**Issue by baseten** [webpack/webpack#2669]
I'm submitting a...
=====
- [ ] bug report
- [x] feature request
- [ ] support request 

**Webpack version:**
1.12.14

**Please tell us about your environment:**
OSX 10.11.3

**Current behavior:**
When creating sourcemaps with the `source-map` devtool, Chrome fails to parse them intermittently and even when it does, doesn't always load the correct source file during debugging. It appears to be because the sourcemaps in our project have become too large for it to handle properly (over 12MB), partly due to the size of the inlined source code inside `sourcesContent`. We are currently implementing [a workaround](http://stackoverflow.com/questions/37885749/is-it-possible-to-remove-sourcescontent-from-webpack-source-maps/37923133#37923133) to remove the `sourcesContent` from the sourcemaps.

**Desired behavior:**
Add an option to disable compilation of source code into `sourcesContent` property of sourcemap.

* **What is the motivation / use case for changing the behavior?**
This would be useful no only for our problem but also when users may want to host the source files elsewhere (I know it's possible to do this now, but the source is still inlined into the source map as well).
 
* **Browser:** [all] 
 
* **Language:** [all]

**Comment by sokra** [comment]
There is already an option: https://github.com/webpack/webpack/blob/master/lib/SourceMapDevToolPlugin.js#L117

`noSources: true`

**Comment by baseten** [comment]
Ah... We're running on a corporate npm registry which doesn't have the latest webpack in it! 

I even spent a while looking through (our local copy of) this file looking for this option. Looks like it was only added a couple of months ago? 

Might be helpful if it was added to [the docs](https://webpack.github.io/docs/list-of-plugins.html#sourcemapdevtoolplugin)?

Thanks!

**Comment by pksjce** [comment]
This issue was moved to webpack/webpack.io#133
