### ISSUE TITLE
winstonjs doesn't work with webpack because of dynamic requires

### ISSUE THREAD

**Issue by joshunger** [webpack/webpack#2672]
- [X] bug report

**Webpack version:**
2.x

**Please tell us about your environment:**
OSX 10.x

**Current behavior:**
1. Add winstonjs to entry.
2. webpack.
3. Run with node which throws the error

Error: Cannot find module "."

winstonjs has the following code -

https://github.com/winstonjs/winston/blob/master/lib/winston/transports.js

```
	Object.defineProperties(
	  exports,
	  ['Console', 'File', 'Http', 'Memory']
	    .reduce(function (acc, name) {
	      acc[name] = {
	        configurable: true,
	        enumerable: true,
	        get: function () {
	          var fullpath = path.join(__dirname, 'transports', name.toLowerCase());
	          return !(function webpackMissingModule() { var e = new Error("Cannot find module \".\""); e.code = 'MODULE_NOT_FOUND'; throw e; }())[name];
	        }
	      };
	
	      return acc;
	    }, {})
	);
```

**Expected/desired behavior:**
Should webpack be able to resolve this dynamic require?

**Comment by sokra** [comment]
One could rewrite the code like this:

``` js
          return require("./transports' + name.toLowerCase())[name];
```

This would work.

The original code is too complex to be statically analysed by webpack.

**Comment by joshunger** [comment]
@sokra, @bebraw thanks, I'll send them a bug.  You can close this one.

**Comment by TheLarkInn** [comment]
@joshunger feel free to reference this issue also in your report to winstonjs.
