### ISSUE TITLE
With node target, Bluebird promise doesn't work because webpack uses package.json browser field instead of main field

### ISSUE THREAD

**Issue by joshunger** [webpack/webpack#2674]
**I'm submitting a bug report**

**Webpack version:**
2.x

**Please tell us about your environment:**
OSX 10.x

**Current behavior:**

With node target, Bluebird promise doesn't work because webpack uses package.json browser field instead of main field.

1. Create entry.js that uses bluebird and promisifyAll -

```
var Promise = require("bluebird");
var fs = Promise.promisifyAll(require("fs"))
```

2. Run webpack with `output.target = 'node'` and `output.pathinfo = true`

3. Open up `bundle.js` and search for `bluebird.js`

**EXPECTING:**
Since I set the target as `node`, Webpack should have included `~/bluebird/js/release/bluebird.js`.

**ACTUAL:**
Webpack incorrectly included `~/bluebird/js/browser/bluebird.js`.

If you look at https://github.com/petkaantonov/bluebird/blob/master/package.json there is a browser and a main field.

In addition, if you run `node bundle.js` you'll get the following exception -

makeNodePromisified(key, THIS, key, fn, suffix, multiArgs);
^

TypeError: makeNodePromisified is not a function
    at promisifyAll (...)
    at Function.e.24.module.exports.Promise.promisifyAll (...)

**Comment by sokra** [comment]
It's `target = "node"` instead of `output.target = 'node'`

**Comment by MrBlenny** [comment]
It appears that `target: 'electron-main'` suffers the same issue and included the browser version not the node version.

**Comment by scottrippey** [comment]
I too am having this issue with `electron-main`, so I've opened this new ticket: #3121

**Comment by TheLarkInn** [comment]
Please check my update to this response.

**Comment by GuillaumeLeclerc** [comment]
I have the same problem and I have target='node' (in the config file not CLI though). @TheLarkInn I don't see the update to this response.
