### ISSUE TITLE
How to resolve files using NODE_PATH resolution logic?

### ISSUE THREAD

**Issue by gajus** [webpack/webpack#2676]
Using `webpack@2.1.0-beta.13` I have a project structure such as:

```
./src/index.js
./src/test.js
```

`index.js` requires `test.js` using `require('test.js')`.

I am expecting this to work because I have set:

```js
resolve: {
    fallback: path.resolve(__dirname, './../src'),
    root: path.resolve(__dirname, './../src'),
    modulesDirectories: [
        path.resolve(__dirname, './../src'),
        'src'
    ]
}
```

However, I am getting an error:

> Module not found: Error: Can't resolve 'test.js' in 'c:\...\src'
 @ ./src/index.js 13:0-18

This used to work in `webpack@1`. Has this behavior been removed?

Note, this attempts to simulate module resolution logic when set using `NODE_PATH`.

**Comment by gajus** [comment]
It appears that the configuration has been renamed.

http://moduscreate.com/webpack-2-tree-shaking-configuration/

> Resolvers
> In Webpack 2, resolvers from root, modulesDirectories, and fallback settings will merge into a single property – modules. Here is how we can resolve file and module locations in Webpack 2:
> 
>     resolve: {
>         modules: [
>           path.resolve('./client'),
>           'node_modules'
>         ]
>       },
> You can specify a number of directories in modules, but make sure not to forget node_modules or npm package dependencies will fail to load.

**Comment by sokra** [comment]
yep
