### ISSUE TITLE
Can't define process as external for target node; shim for using process in browser is always included

### ISSUE THREAD

**Issue by joshunger** [webpack/webpack#2677]
**I'm submitting a bug report**

**Webpack version:**
2.1.0-beta.13

**Please tell us about your environment:**
OSX 10.x

**Current behavior:**
Can't define process as external for target node; the shim for using process in browser is always included.

webpack.config.js
```
module.exports = {
  entry: './entry.cwd.js',
  output:
  {
    filename: 'bundle.js',
    libraryTarget: 'commonjs',
    target: 'node'
  },
  externals:
  [
    'process'
  ],
  node:
  {
    __dirname: false
  }
}
```

entry.cwd.js
```
console.log('cwd', process.cwd());
```

./node_modules/.bin/webpack --config webpack.config.cwd.js

Open bundle.js

EXPECTING: process is not replaced.
ACTUAL: process is replaced with process browser shim.

Did I miss a setting?  Thanks.

**Comment by sokra** [comment]
`target` should be inside of `output`. It's a root level option. For target node `process` is automatically externalized. `externals` only apply to modules (`require("process")`) not to free vars. To disable `process` the correct options would be `node.process = false`, but this is not needed for `target = "node"`.
