### ISSUE TITLE
Buffer polyfill is broken on MS Edge and Firefox

### ISSUE THREAD

**Issue by mzedeler** [webpack/webpack#2678]
**I'm submitting a bug report**

**Webpack version:** 1.13.1

**Please tell us about your environment:** Linux mint

**Current behavior:**
Depends on `node-libs-browser` version 0.5.3 which in turn uses `buffer` version 3.6.0 which has a broken implementation of `slice` on Microsoft Edge and Firefox, see https://github.com/feross/buffer/issues/120

**Expected/desired behavior:**
Bump the dependency on `node-libs-browser` to version 1.0.0.

**To reproduce:**

In the console on Microsoft Edge with `node-libs-browser` 0.5.3, run this:

```new Buffer([1, 2, 3, 4]).slice(2, 4).length === 2```

This returns `false` in Edge.

**What is the expected behavior?**

That the above returns `true`.

**What is the motivation / use case for changing the behavior?**

To support Microsoft Edge.
 
**Browser:** Firefox, Microsoft Edge 
 
**Language:** all

**Comment by orlandodemauro** [comment]
@bebraw @mzedeler did you get any feedback? thanks

**Comment by bebraw** [comment]
Hi,

I think a PR would be welcome. Hopefully Tobias can take a look at bumping that dep to fix this.

**Comment by orlandodemauro** [comment]
@bebraw @sokra I created a PR but of course is failing, any clue on possible a solution? this issue is also breaking mqtt.js with webpack 1.13 and FF48

**Comment by amasad** [comment]
Hitting this too. Seems to be serious breakage in the buffer library.

**Comment by mzedeler** [comment]
@orlandodemauro I'm not sure what you mean - this is still an issue, if thats your question...

**Comment by mzedeler** [comment]
Since MS Edge is growing, we should address this issue soon.

**Comment by orlandodemauro** [comment]
@mzedeler my question was related to my PR. I created a PR in node-libs that fix the issue.

**Comment by orlandodemauro** [comment]
@mzedeler @amasad issue fixed, new node-libs-browser package delivered v0.6.0.

@bebraw @sokra thanks a milion for the help

**Comment by bebraw** [comment]
Ok, closing then.

**Comment by mzedeler** [comment]
Great! Thanks!
