### ISSUE TITLE
Possible bug regarding imports

### ISSUE THREAD

**Issue by mike-robertson** [webpack/webpack#2680]
**I'm submitting a bug report**

**Webpack version:**
1.x/2.x

**Please tell us about your environment:**
OSX 10.x

**Current behavior:**
Imports don't seem to be working properly in some cases, possibly when there are lots of imports. My pattern is that files are in directories, and all files in that directory are imported/exported from an index.js file so that import statements can be 

`import { myThing } from 'myComponent';`

instead of

`import myThing from 'myComponent/myThing';`

The issue is very strange. Honestly I hope I just messed something up as I am having a lot of trouble understanding why this would break webpack.

I have 3 components: Table, Player, Match. They each have a directory structure as follows:

Table/
--index.js
--Table.jsx
--tableContainerFactory.js

Player/
--index.js
--Player.jsx

Match/
--index.js
--Match.jsx

Table/index.js has the following import and export:

```js
import createTable from './tableContainerFactory';
// ...
export { createTable };
```

Now both Match.jsx and Player.jsx do the following import:

```js
import {createTable} from '../Table';
// ...
const MyTable = createTable(...);
```

This works fine in the Match.jsx, but in Player.jsx, it doesn't work. I get an error message 'Uncaught TypeError: (0 , _Table.createTable) is not a function'. If i put console.log statements in the Table/index.js, they never fire before this error occurs. If I put a console.log in the Player.jsx and print createTable (what I imported), it is undefined). This happens regardless of which route I am hitting, so even if the Player.jsx is not being loaded immediately, it fails with this error.

I would normally think that somehow, I am just not importing the right file/the path is wrong. However,  incredibly strange thing is if I change the import in Player.jsx to 
```js
import createTable from '../Table/tableContainerFactory';
```
it works. There is no error, the console statements go through in Table/index.js, and everything works just fine.

I've tried various different webpack versions (1.14, 1.15, 2.1 beta), and they all behave the same. I have also noticed that at some point, the number of import and export statements seemed to be breaking source maps as well. That seems to have been fixed by switching to 2.1 beta, but I did see a github issue about strange behavior from webpack sourcemaps if you have too many imports.

**Expected/desired behavior:**
I should be able to import things in a consistent manner.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.** 

The code is all in the mike branch of yasp-data/ui repo 

https://github.com/yasp-dota/ui/tree/mike

You can clone it and run and see the same issue if you change the import from '../Table/tableContainerFactory' to '../Table' in /components/Player/Player.jsx.
 
* **Browser:** [all (as far as I can tell) ] 
 
* **Language:** [ES6/7]

**Comment by mAAdhaTTah** [comment]
In `Table/index.js`, try:

```js
export { default as createTable } from './tableContainerFactory';
```

For one, `export { createTable }` won't work, period, since the export doesn't have a name. I'm a little surprised it's not a syntax error, actually. Doing `export default { createTable }` would work, but...

My suspicion as to why this is happening has nothing to do w/ Webpack, and more to do with a misunderstanding in how ES6 modules work. When you `export default` an object, you retrieve that object by importing the default:

```js
import Table from '../Table';

const instance = Table.createTable();
```

Trying to destructure the import won't work the way you expect, because it's not trying to destructure off the default-exported object, but off of a **named export** with the name `createTable`, which is why I suggest the alternate syntax above. Exporting each submodule as its own named export will give you what you want, rather than default exporting the single object, hence the suggested alternative above.

Let me know if that makes sense.

**Comment by mike-robertson** [comment]
I'm not 100% sure I understand. I think my example might be a little confusing.

Table/tableContainerFactory.js is default exporting the createTable function (and it is the only export in that file). So it looks like:
```js
const createTable = () => ...;

export default createTable;
```

Table/index.js looks like:
```js
import Table from './Table';
import createTable from './tableContainerFactory';

export default Table;
export { createTable };
```

So I am default exporting Table from Table/index.js. If I want to use that container Factory, I am exporting it as a named export, so it has to be destructured in the import (from what I understand at least). However, if I am importing directly from Table/tableContainerFactory.js, createTable is the default export from that file, so I am importing it as if it were the default export (no destructuring). The main point is that I am not expecting createTable to be the default export from Table/index.js. Hopefully I understood what you meant.

Another reason why I don't think it's a syntax issue is because I am doing the exact same import in Match.jsx and it seems to work. However, after doing some refactoring (deleting TableContainer imports in Table/index.js since they are replaced by the factory createTable function), it is now working as intended in both places 
```js
import { createTable } from '../Table';
```

This makes me think even more it's not a syntax issue with module exports but rather an issue with webpack since I haven't changed anything except the Table/index.js file (number of things imported and number of things exported). For now though, since it seems to be working, I guess it's fine? It seems rather fishy to me though because as I said, I've only changed the number of things I am importing in the index.js and exporting, and the inconsistent behavior between Match.jsx and Player.jsx is the real thing which makes me think that there is something weird going on. Let me know if I am still misunderstanding module.exports as I was under the impression that it is something like this:
```js
export default myFunction;
export { otherExport, namedExport };
```
allows
```js
import MyDefaultExportedThing, { otherExport, namedExport } from './myFile';
```
based on this (3.3 section) http://www.2ality.com/2014/09/es6-modules-final.html

**Comment by mAAdhaTTah** [comment]
Nope, [you're right](http://exploringjs.com/es6/ch_modules.html). He has an example that looks just like your code:

```js
const MY_CONST = ···;
function myFunc() {
    ···
}

export { MY_CONST, myFunc };
```

I thought the `export { myFunc }` syntax wasn't supported. I usually write my exports inline:

```js
export const MY_CONST = ...
```

So I thought the other method was invalid. My apologies.

**Comment by Kovensky** [comment]
IIUC, you are supposed to use `export from` to re-export symbols from other methods.

```js
export { default as createTable } from './tableContainerFactory'
```

**Comment by mike-robertson** [comment]
I think you are right, though it does work to do it this longhanded way (I wasn't aware of this style when I first started the project). It could be that was causing some sort of issue though I would think it shouldn't really matter as it is just a better syntax (from what I understand).

**Comment by sokra** [comment]
Sounds like a circular dependency issue.

btw `export { default } from "./Table"` is different from `import Table from "./Table"; export default Table`. The first one is hoisted, the second one is not.

You could try using webpack 2 instead of babel to handle the ES6 modules (es2015-webpack preset instead of es2015) to see if it's a babel transfromation bug, but I guess it's not.

**Comment by Kovensky** [comment]
The first one also keeps it a live binding, the second one resolves the binding before exporting the result.

**Comment by LarsOL** [comment]
Sorry to slightly hijack the thread. We currently have a little wrapper: 
```javascript
import 'c3/c3.min.css'; //Webpack-Specific
import c3 from 'c3';

export default c3;
```

Is it a more correct pattern to write it as? : 
```javascript
import 'c3/c3.min.css'; //Webpack-Specific
export {default} from 'c3';
```
