### ISSUE TITLE
Unable to resolve github installed module

### ISSUE THREAD

**Issue by pke** [webpack/webpack#2681]
**I'm submitting a bug report**

**Webpack version:**
1.13.0

**Please tell us about your environment:**
Windows 8.1

**Current behavior:**

installed master version of Leaflet using
`npm i github:Leaflet/Leaflet`

`import L from "leaflet"`

does not resolve the module. It exists in `node_modules` though

when installed via:

`npm i leaflet`

everything works.

**Expected/desired behavior:**

Expect webpack to resolve the module.

**Comment by billyjanitsch** [comment]
This isn't a webpack bug. Leaflet's [`main`](https://github.com/Leaflet/Leaflet/blob/master/package.json#L25) file doesn't [exist](https://github.com/Leaflet/Leaflet/tree/master/dist) in the repo (it's only created on `npm run build`, before the package is published to the npm registry). When you install from github, it just clones the repo, and webpack can't resolve a file that isn't there.

**Comment by pke** [comment]
ah! Of course, stupid me. The webpack error output was just not very helpful. Webpack dev server was much more talkative and showed which files it tried to load. And true, none of them exist in the checked out repo. So just running `npm run build` should work?
