### ISSUE TITLE
How to pass backend variable to Webpack module?

### ISSUE THREAD

**Issue by coderlex** [webpack/webpack#2683]
I've tried to pack entry points into AMD libraries and include the following code on pages:
```javascript
<script type="text/javascript">
;(function(){
      var Entry = require('./entries/users/index');
      var entry = new Entry({
        ... // <--- PHP-generated parameters here
      });
})();
</script>
```
But browser says: `require is not defined`.
Ok. Maybe that approach is totally incorrect? How to handle the situations when I need to pass dynamicly created variables by my backend (PHP/Node/etc) to a module with webpack?

**Comment by sokra** [comment]
With `output.library = "Entry"` you can do this:

``` js
<script src="bundle.js"></script>
<script>
var entry = new Entry({
  ... // <--- PHP-generated parameters here
});
</script>
```

---

For security reasons I recommend to avoid inline scripts and read the PHP data from the bundle itself:

``` js
<script type="text/data" id="server-data">
  ... // <--- PHP-generated parameters here
</script>
<script src="bundle.js"></script>
```

**Comment by ryancwalsh** [comment]
@sokra Thank you so much for this hint! Today I'm trying to learn Webpack, and I'm seeing your comment almost a year after you wrote it. I've spent hours trying to figure out how bundle.js could read from `<script type="text/data" id="server-data">` as you indicated above. Would you be able to give another hint / point me in the right direction? I'd very much appreciate it. People recommend Webpack, so I'm very interested in getting this basic functionality working. 

Actually, are you saying to do something like this? `<div id="someInvisibleDiv" data-var1="here is a value" data-var2="I could add a ton of attributes like this"></div>`

Then, bundle.js could look for `#someInvisibleDiv` after the doc loaded and read those attributes.

Would that work? If not, or if using `<script type="text/data" id="server-data">` is superior, I'd love to know how to specify key-value pairs in there and how to access them from bundle.js.

Thanks!!

**Comment by bartaz** [comment]
> For security reasons I recommend to avoid inline scripts

@sokra What are the security concerns of using inline scripts to pass data?

Using something like:
```js
entry.init({ params });
```

seems much more explicit and controlled then:
```html
<script id="init-params">{ params }</script>
```
and having this specific element found by id inside of bundled module, data parsed, etc.

Are there any webpack docs that explain it in a bit more detail?

**Comment by gds03** [comment]
Looking for the same... Searching on the web I can't find nothing as well!

**Comment by gds03** [comment]
@sokra any update on this thread?
