### ISSUE TITLE
/AppData/Roaming/npm/webpack: line 14:  5292 Illegal instruction     node "$basedir/node_modules/webpack/bin/webpack.js" "$@"

### ISSUE THREAD

**Issue by duanSD** [webpack/webpack#2686]
/AppData/Roaming/npm/webpack: line 14:  5292 Illegal instruction     node "$basedir/node_modules/webpack/bin/webpack.js" "$@"

**Comment by sokra** [comment]
Closing because too few details. Follow the issue template.

**Comment by Jogiter** [comment]
i just got the same problem, here is the [link](http://stackoverflow.com/questions/38220816/webpack-illegal-instruction), what should i do

**Comment by SanthoshHari912** [comment]
I have a similar problem .I use node 4.2.1 and npm 2.14.7 in Win 7 Enterprise edition. When I run webpack it gives me the following error 
/c/Users/Myuser/AppData/Roaming/npm/webpack: line 14:  1588 Illegal instruction     node "$basedir/node_modules/webpack/bin/webpack.js" "$@"

**Comment by Jogiter** [comment]
Today i update my os to win10 and then webpack & webpack-dev-server works, it`s wired, it`s there any other solutions?

**Comment by Aggie123** [comment]
when webpacking , same error with node 6.3.0 and npm 3.10.3 on win7:  '/c/Users/**/AppData/Roaming/npm/webpack: line 14:  7996 Illegal instruction     node "$basedir/node_modules/webpack/bin/webpack.js" "$@"
'

**Comment by vino24** [comment]
same question,who can help me ?
