### ISSUE TITLE
Error with plugin `transform-runtime` 

### ISSUE THREAD

**Issue by lichenhao** [webpack/webpack#2688]
**I'm submitting a bug report**
```log
Module not found: Error: Cannot resolve module 'babel-runtime/helpers/inherits' in
```

**Webpack version:**
Webpack 1.13.1
Others version
```JSON
{
    "babel-core": "^6.10.4",
    "babel-loader": "^6.2.4",
    "babel-plugin-transform-runtime": "^6.9.0",
    "babel-preset-es2015": "^6.9.0",
    "babel-preset-es2015-loose": "^7.0.0",
    "babel-preset-stage-0": "^6.5.0",
}
```
My webpack config for babel
```JSON
{
    entry: {
      cill: './src/index.js'
    },
    output: {
      path: './build',
      filename: '[name].js'
    },
    module: {
      loaders: [
        {
          test: /\.js$/,
          exclude: /node_modules/,
          loader: 'babel-loader',
          query: {
            presets: ['es2015-loose', 'stage-0'],
            plugins: ['transform-runtime']
          }
        }
      ]
    }
  }
```

**Please tell us about your environment:**
OSX 10.11.5
Node 4.2.6

**Current behavior:**

ERROR in ./src/viewport.js
Module not found: Error: Cannot resolve module 'babel-runtime/core-js/object/define-properties' in /Users/Ryota/works/jbc/cill/src
 @ ./src/viewport.js 3:24-81

**Expected/desired behavior:**
babel transform and compile success without warn or error.

**Comment by sokra** [comment]
`babel-runtime` is not in dependencies.
