### ISSUE TITLE
On Windows, wepback build is blocked during 'emit' phase

### ISSUE THREAD

**Issue by lbar** [webpack/webpack#2689]
**I'm submitting a bug report**

**Webpack version:**
1.13.1

**Please tell us about your environment:**
Linux & Windows 10

**Current behavior:**
I created a simple webpack project for a Typescript library : https://github.com/lbar/test-webpackts-issue

On linux, `npm run build` finishes successfully:
```
> rimraf dist && webpack --progress --profile
10% 0/1 build modulests-loader: Using typescript@1.8.10 and /tmp/testwebpack/tsconfig.json                                                                                                                                   8030ms1217ms optimi5ms emit
Hash: 8eac1502f3b7a9a19be2
Version: webpack 1.13.1
Time: 2596ms
Asset       Size  Chunks             Chunk Names
index.js  816 bytes       0  [emitted]  index
index.js.map    6.07 kB       0  [emitted]  index
/tmp/testwebpack/dist/index.d.ts   31 bytes          [emitted]
/tmp/testwebpack/dist/src/info.d.ts   49 bytes          [emitted]
+ 2 hidden modules
```

On Windows, `npm run build` is blocked during 'emit' phase. The output is :
```
> rimraf dist && webpack --progress --profile

10% 0/1 build modulests-loader: Using typescript@1.8.10 and C:\tmp\testwebpack\tsconfig.jso
1836ms build modules
3ms seal
7ms optimize
3ms hashing
7ms create chunk assets
79ms additional chunk assets
19ms optimize chunk assets
837ms optimize assets
95% emit
```

The version of node differs: 6.2.2 on Windows and 4.4.5 on Linux. I don't know if it may be the cause. Has anyone an idea about the problem? Issue in webpack, ts-loader or typescript?

One more thing, call to `tsc` is working on both systems.

Thanks for your help

**Expected/desired behavior:**

Windows terminates building of package.
 
* **Language:** TypeScript 1..8

**Comment by t246246** [comment]
Are you using
```
declartion: true 
```
in ts.config?

So check the following:
https://github.com/TypeStrong/ts-loader/issues/185

**Comment by lbar** [comment]
Yes, exactly. So the issue comes from ts-loader and not webpack. Happy to learn that!
Thank you I close the issue.

**Comment by t246246** [comment]
Workaround is use `awesome-typesript-loader` instead of `ts-loader`, **without cache option**.
See https://github.com/s-panferov/awesome-typescript-loader/issues/152
