### ISSUE TITLE
docs on bundles, chunks, long term caching

### ISSUE THREAD

**Issue by greaber** [webpack/webpack#2692]
I'm posting this because I think I understand something about webpack, but I'm not sure, and whether I am right or not, I think the docs could be improved.

I have been using webpack for several months, and I was hazy for a long time about the difference between chunks and bundles.  As I now understand it, though, it is pretty simple.  a chunk is just any output produced by webpack, and a bundle is (essentially) all the outputs produced by webpack.  At an rate, the `chunkhash` directive, used in naming an output, expands to a hash of that output, while the `bundle` directive expands to a hash of all the outputs.  If this understanding is right, I think it could be made more clear in the docs.  Some things that make it confusing are that "bundle" is often used to name a particular output and that the long term caching docs suggest there are two options that you might equally want, using per-chunk hashes and using per-bundle hashes, whereas, if I understand correctly, you would almost always want to use a per-chunk hash.  (The only downside of that seems to be that, according to the docs, you cannot use it in conjunction with hot code replacement, but my understanding is that hot code replacement is a dev feature, and you don't need to use any of this hashing in dev because you can just use the dev server or simply disable caching.)

Another thing that is perhaps confusing about these concepts of chunks and bundles is the way the `output` section has options for `filename` and `chunkFilename`.  If my understanding is correct, all outputs are chunks, and all chunks outputs.  The `filename` option is just used to specify the names of entry chunks.  But the docs for it say "Specifies the name of each output file on disk", so not sure I am not confused about something.

**Comment by pksjce** [comment]
This issue was moved to webpack/webpack.io#134
