### ISSUE TITLE
Trailing space in loader configuration causes webpack to fail

### ISSUE THREAD

**Issue by mattcbaker** [webpack/webpack#2693]
**I'm submitting a bug report**

**Webpack version:**
1.13.1

**Please tell us about your environment:**
Windows 10, Node 6.2.2

**Current behavior:**
If a loader that is specified in a webpack.config.js has a trailing space, webpack will fail to run.

My specific use case:

```
{
	test: /\.jsx$/,
	exclude: /(node_modules|bower_components)/,
	loader: 'babel ', // <-- NOTICE THE SPACE AFTER BABEL, BEFORE SINGLE QUOTE
	query: {
		presets: ['es2015', 'react']
	}
}
```
Running webpack with this configuration fails with the following error:
```
ERROR in multi login
Module not found: Error: Cannot resolve module 'babel ' in C:\code\should-website
 @ multi login
```
This is due to the trailing space after the babel loader is specified. If I remove the trailing space, webpack executes successfully.

**Expected/desired behavior:**
Trim the `loader` option value when loading a webpack config.

* **What is the motivation / use case for changing the behavior?**
Ease of development
 
* **Language:** all

**Comment by sokra** [comment]
Won't fix... spaces are wrong here. The performance cost doesn't justify the benefit.
