### ISSUE TITLE
Feature request: Async configuration via webpack.config.js

### ISSUE THREAD

**Issue by aanno** [webpack/webpack#2697]
#### Feature request: Async configuration via webpack.config.js

**Webpack version:**
1.12.2

**Please tell us about your environment:**
Linux (OS independent problem)

**Current behavior:**
Configuration in webpack.config.js _must_ define an _object_ as module.exports.

**Expected/desired behavior:**
Configuration in webpack.config.js should also support _async_ resolving of module.exports (e.g. by assigning a promise, future and/or callback to module.exports). 

**What is the motivation / use case for changing the behavior?**
I stepped upon the same problem as described in [defineplugin-from-async](https://stackoverflow.com/questions/36066897/webpack-defineplugin-from-async-function). 

In my case I would like to include some git information (branch, last commit, current value of git-describe) as a constant into the bundled javascript code. With help of nodegit, it is relatively simple to retrieve this - but nodegit is an _asynchronous_ node library.

While there is a work-around (by running webpack through the node API, see link above), my feeling is that allowing an async configuration webpack would simplify more advanced use-cases.

**Comment by bebraw** [comment]
Yeah. With webpack 2 you get

```javascript
exports default function(options) {
    return {
        // ...
        devtool: options.dev ? "cheap-module-eval-source-map" : "hidden-source-map"
    };
}
```

Expanding to

```javascript
exports default function(options, cb) {
    cb(null, {
        // ...
        devtool: options.dev ? "cheap-module-eval-source-map" : "hidden-source-map"
    });
}
```

would seem like a good move to me.

**Comment by sokra** [comment]
You can return a Promise with webpack@2

**Comment by mathieumg** [comment]
It also works with Webpack 1. It doesn't work *yet* with Webpack 1's development server, however. See https://github.com/webpack/webpack-dev-server/pull/698 for that.

**Comment by trusktr** [comment]
For reference, for anyone stumbling here, returning a promise like what @sokra said looks something like this:

```js
const configPromise = new Promise(function(resolve, reject) {

    // ... do async stuff ...

    // then at some point call `resolve()` with the config object:
    resolve({
        entry: { /* ... */ },
        resolve: { /* ... */ },
        // etc
    })
})

module.exports = configPromise
```
