### ISSUE TITLE
AggressiveMergingPlugin does not merge System.import chunks

### ISSUE THREAD

**Issue by jaulz** [webpack/webpack#2700]
**I'm submitting a bug report**

**Webpack version:**
2.1.0-beta.14

**Please tell us about your environment:**
Windows 10

**Current behavior:**
Though I use the AggressiveMergingPlugin the chunks that were created via the new dynamic System.import mechanism are not merged even if I set minSizeReduce to 1 (i.e. merge all).

```
    new webpack.optimize.AggressiveMergingPlugin({
            minSizeReduce: 1,
            moveToParents: true
    }),
```

**Expected/desired behavior:**
I need one big file regardless of System.import was used or not. Chunks that were created by the new mechanism should be merged into the very same file.
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.** 
- Add AggressiveMerginPlugin with minSizeReduce = 1
- Use System.import 
- See stats -> multiple chunks are created
- **What is the expected behavior?**
  One big merged file should be the result.
- **What is the motivation / use case for changing the behavior?**
  I would like to use the big merged file to be run on the server with a MemoryFS. If multiple chunks are created `System.import` will lead to an error that the file could not be found because `System.import` tries to find the file in the actual file system and not the provided MemoryFS.
- **Browser:**
  all
- **Language:**
  ES6/7

**Comment by jaulz** [comment]
Just as an addition: LimitChunkCountPlugin with maxChunks=1 in contrast works.

**Comment by sokra** [comment]
System.import is decreated
