### ISSUE TITLE
Feature request:  To expand output.libraryTarget

### ISSUE THREAD

**Issue by gebilaoxiong** [webpack/webpack#2701]
**Webpack version:**
1.10.x/2.x

**Please tell us about your environment:**
OSX 10.x / Linux / Windows 10

**Current behavior:**
If I need to add a new libraryTarget, such as seajs module。
I need to cover [LibraryTemplatePlugin](https://github.com/webpack/webpack/blob/master/lib/LibraryTemplatePlugin.js#L32) and [ExternalModule](https://github.com/webpack/webpack/blob/master/lib/ExternalModule.js#L43).
Because of these two methods are used in a switch statement.

**Expected/desired behavior:**
I think here should use hooks instead of the switch.

Can I submit a PR?

**Comment by sokra** [comment]
How does a seajs module differ from a AMD module?

**Comment by gebilaoxiong** [comment]
@sokra 

**example：**

AMD(requireJS):

``` javascript

define('xxx/a.js' /*id?*/,  ['./b.js', './c.js'] /*dependencies*/, function(b, c) {
  //..
});

```

seajs Module:

```

define('xxx/a.js' /*id?*/,  ['./b.js', './c.js'] /*dependencies?*/, function(require, exports, module) {
  var b = require('./b.js');
  var c = require('./c.js');
});

```

so I wrote a plugin solve it [seajs-webpack-plugin](https://github.com/gebilaoxiong/seajs-webpack-plugin).The method is to cover [LibraryTemplatePlugin](https://github.com/webpack/webpack/blob/master/lib/LibraryTemplatePlugin.js#L32) and [ExternalModule](https://github.com/webpack/webpack/blob/master/lib/ExternalModule.js#L43).

I think the source code should use hooks, more conducive to extend.
