### ISSUE TITLE
Module with an equal name when case is ignored issue

### ISSUE THREAD

**Issue by lior-a** [webpack/webpack#2702]
**Webpack version:**
1.12.9

**Please tell us about your environment:**
OSX 10.11

**Current behavior:**
When I import a file within the same folder into 2 different files I end up with this error:

```
WARNING in ./src/Component//ComponentConstants.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.

WARNING in ./src/component//ComponentConstants.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.

```

If we go 1 folder above (parent) and go back to the folder than I don't have the issue. I tried to reproduce the issue with other similar structured folders but I couldn't.

**Expected/desired behavior:**

Shouldn't go to the parent to make it work.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.** 

file 1:
```
import * as constants from './ComponentConstants';
```

file 2:
```
import * as constants from './ComponentConstants';
```

How I solve it:

```
import * as constants from '../parentfolder/ComponentConstants';
```
- in both of the files
* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**
So we won't have to have this above hacky solution
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart | ...] 
E6/7

There are better ways to manage paths, maybe resolve?

**Comment by sokra** [comment]
Try to use webpack@2 for a more detailed error message.
