### ISSUE TITLE
SourceMap is missing when UglifyJSPlugin is enabled

### ISSUE THREAD

**Issue by qingweibinary** [webpack/webpack#2704]
**I'm submitting a bug report**

**Webpack version:**
2.1.0-beta.4

**Please tell us about your environment:**
OSX 10.x

**Current behavior:**
Source map is not generated when `new webpack.optimize.UglifyJsPlugin()` is used.
If I remove UglifyJSPlugin or use webpack version 1.13, it does produce source map.

**Expected/desired behavior:**
Source map should be generated.

* **My config** 

```
const path = require('path');
const webpack = require('webpack');
const WebpackNotifierPlugin = require('webpack-notifier');
const styleLintPlugin = require('stylelint-webpack-plugin');

const env = process.env.NODE_ENV;

module.exports = {
    devtool: 'source-map',
    entry: './src',
    output: {
        path: path.join(__dirname, 'dist'),
        filename: 'app.js',
    },
    plugins: [
        new webpack.DefinePlugin({
            'process.env': {
                NODE_ENV: JSON.stringify('production'),
            },
        }),
        new webpack.optimize.DedupePlugin(),
        new webpack.optimize.UglifyJsPlugin()
    ],
    module: {
        loaders: [
            { test: /\.js$/, exclude: /node_modules/, loader: 'babel' },
            { test: /\.js$/, exclude: /node_modules/, loader: 'eslint' },
            { test: /\.css$/, exclude: /node_modules/, loader: 'style!css?modules&importLoaders=1&localIdentName=[local]_[hash:base64:5]' },
        ],
    },
};

```
  
* **Language:** [ES6/7]

**Comment by sokra** [comment]
``` js
new webpack.optimize.UglifyJsPlugin({
  sourceMap: true
})
```

We changed the default, because it's pretty expensive

**Comment by jaydenseric** [comment]
Wouldn't it be better if the plugin detects if a `devtool` has been set, and toggles `sourceMap` accordingly as a default?

**Comment by aaugustin** [comment]
It would also be nice to mention this in the Building for Production docs, because currently it tells us to enable source maps, then to enable UglifyJS, and neglects to mention that the latter disables the former.

**Comment by bbottema** [comment]
> We changed the default, because it's pretty expensive

Wow. I have been searching for ages as to why it wasn't working.

> Wouldn't it be better if the plugin detects if a devtool has been set, and toggles sourceMap accordingly as a default?

This.

**Comment by stefanfisk** [comment]
I just lost an hour to this issue, speaking of expensive :(

**Comment by LaniMoo** [comment]
I lost an entire work day due to this.

**Comment by Vanuan** [comment]
How did you make it work?

**Comment by aaugustin** [comment]
The solution is in this comment: https://github.com/webpack/webpack/issues/2704#issuecomment-228860162

**Comment by Vanuan** [comment]
Doesn't seep to work:

```"mappings":"AAAA"```

**Comment by stevematdavies** [comment]
Doesn't work still with solution, no sourcemaps are produced

**Comment by RossMcMillan92** [comment]
Had the `"mappings":"AAAA"` issue too. Fixed by changing production source maps to `source-maps` and enabling `sourmap: true` in uglify. Before I had sourcemaps set to `cheap-module-source-map` which didn't work.

**Comment by grunmin** [comment]
can't work with `UglifyJsPlugin` and `cheap-module-source-map` either

**Comment by firestar300** [comment]
Same problem here. I have this : 

```
let config = {
	...
	devtool: dev ? 'cheap-module-eval-source-map' : false,
        ...
}
```

And this : 

```
new UglifyJsPlugin({
	sourceMap: true,
	comments: false
})
```

And no source maps generated.

**Comment by rezonant** [comment]
This should respect the `devtool` setting, or at least detect that `devtool` is set to produce source maps and emit a warning if the equivalent uglify plugin option is not set.

**Comment by corytheboyd** [comment]
We should at least add a log message if the `devtool` is configured and this option is missing.

**Comment by mwmwmw** [comment]
This was happening to me, I had to set the `sourceMapFilename`
```
  output: {
    ...
    sourceMapFilename: 'bundle.map'
  },
  plugins: [
    new webpack.optimize.UglifyJsPlugin({
      sourceMap: true
    })
  ] 
```
