### ISSUE TITLE
Support  webpack.config.es

### ISSUE THREAD

**Issue by graingert** [webpack/webpack#2707]
**I'm submitting a feature request**
**Webpack version:**
1.10.x/2.x
**Please tell us about your environment:**
OSX 10.x / Linux 
**Current behaviour:**
Opens webpack.config.babel.js, ignores webpack.config.es
**Expected/desired behavior:**
Open and transpile webpack.config.es
* **What is the motivation / use case for changing the behavior?**
bebal-register pulgin supports ".js", ".es", ".es6" and ".jsx" extensions.
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]  
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart | ...]

**Comment by sokra** [comment]
webpack uses https://github.com/js-cli/js-interpret
please report the issue there

**Comment by graingert** [comment]
@sokra I did, they don't want to because it encourages the use of those extensions. https://github.com/js-cli/js-interpret/pull/40

I think webpack should support it however

**Comment by sokra** [comment]
Looks like they had valid reasons...

**Comment by graingert** [comment]
Not sure if they apply to webpack
