### ISSUE TITLE
webpack2 error

### ISSUE THREAD

**Issue by durongzhang** [webpack/webpack#2710]
I just want to try the tree shaking, the results of the report is wrong, and can not find the answer,Please help me
### error:Module build failed: Error: Parse Error: Line 1: Illegal import declaration

![image](https://cloud.githubusercontent.com/assets/15725537/16406659/0d0d7702-3d42-11e6-885c-f94f2e08e0cb.png)

##### home.js
![image](https://cloud.githubusercontent.com/assets/15725537/16406697/4984c262-3d42-11e6-83a4-567910e5491e.png)

##### .babelrc
![image](https://cloud.githubusercontent.com/assets/15725537/16406690/3cde030c-3d42-11e6-8f44-2ab06719f980.png)

##### webpack.config
![image](https://cloud.githubusercontent.com/assets/15725537/16406755/a016389a-3d42-11e6-8e60-73a6c6341431.png)
![image](https://cloud.githubusercontent.com/assets/15725537/16406758/a62a8420-3d42-11e6-8ec4-049a87360562.png)

**Webpack version:**
2.1.0.beta.14

**Please tell us about your environment:**
 Windows 7

Browser: [all (as far as I can tell) ]

Language: [ES6/7]

**Comment by sokra** [comment]
the es3ify-loader is the problem. It doesn't support `import`.

**Comment by TheLarkInn** [comment]
@durongzhang I left an issue https://github.com/sorrycc/es3ify-loader/issues/3 for es3ify-loader that you can follow up with and/or track! I'm going to close this.

**Comment by chemzqm** [comment]
@TheLarkInn it looks not reasonable for es3ify to support es6 syntax, we could easily fix this problem by using `es3ify-load` as postLoader by
```
    postLoaders: [
      { test: /\.js$/, loader: 'es3ify' }
    ]

```

**Comment by CheolMinBae** [comment]
@chemzqm answer is only useful in webpack 1,
in webpack 2 must use enforce: "post" option

module {
   rules: {
        { 
           enforce: "post",
           test: /\.js$/,
           loader: 'es3ify'
         }
   }
}

**Comment by LiuYashion** [comment]
```
{
    "presets": [
        "es2015",
        "react",
        "stage-0"
    ],
    "plugins": [
        ["transform-runtime", {
            "helpers": false,
            "polyfill": false,
            "regenerator": true,
            "moduleName": "babel-runtime"
        }]
    ]
}
```
it works for me~
