### ISSUE TITLE
DOM Property.injection is undefined

### ISSUE THREAD

**Issue by raz21** [webpack/webpack#2711]
I am using loaders: [
	  {
      test: /\.jsx?$/,
	  loaders: ['react-hot', 'babel-loader?presets[]=es2015,presets[]=react&presets[]=stage-2&presets[]=stage-0'],
      exclude: [/node_modules\/(?!(react-native-gifted-messenger|react-native-gifted-spinner|react-native-parsed-text|react-native-button)\/).*/, '/node_modules/react-native-webrtc']
	  },

Which works fine on MAC but getting Error on window : "DOM Property.injection is undefined"

Please let me know what should I need to fix or add.

**Comment by sokra** [comment]
To fee details and probably not related to webpack.
