### ISSUE TITLE
Feature request: posibility to disable source-map generation for JS but keep it for SASS / LESS

### ISSUE THREAD

**Issue by codewizz** [webpack/webpack#2712]
**Webpack version:**
1.10.x/2.x

**Please tell us about your environment:**
OSX 10.x / Linux / Windows 10

**Current behavior:**
In order to be able to generate a SASS / LESS source maps, I need to define a devtool value that leads to a JS source map generation. 

```
module: {
    loaders: [
        {test: /\.less$/, loader: ExtractTextPlugin.extract('style-loader', 'css-loader?sourceMap!less-loader?sourceMap')},
        {test: /\.scss$/, loader: ExtractTextPlugin.extract('style-loader', 'css-loader?sourceMap!sass-loader?sourceMap')},
        {test: /\.sass$/, loader: ExtractTextPlugin.extract('style-loader', 'css-loader?sourceMap!sass-loader?sourceMap')}
    ]
},

devtool: 'source-map'
```

**Expected/desired behavior:**
I tried to search for a possible solution without any luck. The desired behavior would be a posibility to disable JS source map generation in the webpack config but keep the SASS / LESS one if configured in ExtractTextPlugin like in my example.

Atleast for our use-case SASS / LESS source maps are way more important. In addition JS source-maps add an additional overhead in run / code generation where we do not use / need them at all.

Looking forward!

**Comment by bebraw** [comment]
Have you tried the [SourceMapDevToolPlugin](http://survivejs.com/webpack/developing-with-webpack/enabling-sourcemaps/#-sourcemapdevtoolplugin-)?
