### ISSUE TITLE
Support tree shaking with import * as identifier from file;

### ISSUE THREAD

**Issue by wegry** [webpack/webpack#2713]
Over in the purescript repository (purescript/purescript/issues/1206), it seems webpack doesn't support [tree-shaking for the import {*](https://gist.github.com/sokra/27b24881210b56bbaff7#es6-specific-optimizations) syntax. Rollup does. Would it be possible to support this?

**Comment by sokra** [comment]
It's working now...

See example: https://github.com/webpack/webpack/tree/master/examples/harmony-unused#examplejs

**Comment by wegry** [comment]
Thanks!

**Comment by drcmda** [comment]
@sokra I tried Webpack 2 against the ongoing THREE.js transformation into modules, which has one gigantic index.js exporting all the modules. It did not work, the output was still half a MB. When going through the index manually, cutting out dependencies it decreased in size.

Is there something that i do wrong? The project is here: https://github.com/drcmda/three-modules
