### ISSUE TITLE
webpack source-map can not show the origin source code properly?

### ISSUE THREAD

**Issue by handane123** [webpack/webpack#2719]
Here is my webpack config file. I use chrome to debug my project, but it still generated the transformed code which I don't want.Could help me to find the fault of my config file or any useful suggestions?
![1](https://cloud.githubusercontent.com/assets/7983700/16461784/daeb2ede-3e60-11e6-8be5-b747af875cef.PNG)
![2](https://cloud.githubusercontent.com/assets/7983700/16461787/dc711ff2-3e60-11e6-8ec6-e26d85bccce9.PNG)
![3](https://cloud.githubusercontent.com/assets/7983700/16461791/de340822-3e60-11e6-9447-1fc22b776ef4.PNG)

**Comment by wdhorton** [comment]
The __cov__ in your Chrome window makes me think it's the fault of your 'instanbul-instrumenter' loader. Maybe disable that loader in dev/prod environments and only run it in test?

**Comment by handane123** [comment]
Thanks Great!
