### ISSUE TITLE
Sourcemaps created also included @Angular2, rxjs, etc maps

### ISSUE THREAD

**Issue by acostaf** [webpack/webpack#2721]
Hi All

I am working in a @angular2 project so I am creating bundles for it and also sourcemaps but maps are huge for the app that I am creating so i think libs maps are also being included.

any idea how to exclude everything from node_modules ?

**Comment by AndreVarandas** [comment]
Hi @acostaf adding the exclude property in your config should work.
```
{
        test: /\.js$/,
        loader: 'source-map-loader',
        exclude: 'node_modules'
}
```
