### ISSUE TITLE
[fsevents@^1.0.0] optional install error

### ISSUE THREAD

**Issue by acmeid** [webpack/webpack#2722]
**I'm submitting a bug report**

**Webpack version:**
1.13.1

**Please tell us about your environment:**
Linux

**Current behavior:**
[fsevents@^1.0.0] optional install error: Package require os(darwin) not compatible with your platform(linux)

**Expected/desired behavior:**
Successful installation

**Comment by bebraw** [comment]
`fsevents` is not required, hence it's marked as optional. The error is shown because it works only on a certain platform but webpack should work still. Is it failing to work entirely?

**Comment by acmeid** [comment]
Thank you. I will try again at Linux.

**Comment by devjoaoGustavo** [comment]
I got this message: 
`npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14`
I don't know if it is related with the current issue, but I can't use the webpack functionalities for this dependency problem.
I'm using `ubuntu MATE 16.04` with `nodejs v4.2.6` and `npm 3.5.2`
Thank you all

**Comment by bebraw** [comment]
[fsevents](https://www.npmjs.com/package/fsevents) is OS X only. The warning itself is harmless and webpack just won't use the dependency on other operating systems.

@devjoaoGustavo Can you provide more info? How exactly is it failing for you?

**Comment by bebraw** [comment]
No response, closing. Feel free to comment with more details, though.

**Comment by StefanKern** [comment]
I'd like to have this issue reopend because it is very gets it is highliy visible in an ASP.NET Core application:
![image](https://user-images.githubusercontent.com/2032760/28211541-7ca52312-689d-11e7-9e43-723e860f62a1.png)

This is the complate console output:
```
C:\XXX>npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
```
