### ISSUE TITLE
Would like support for polymer html imports

### ISSUE THREAD

**Issue by jjarrell50** [webpack/webpack#2723]
I did ask in Stackoverflow
http://stackoverflow.com/questions/37233781/how-to-use-polymer-with-webpack
**I'm submitting a feature request**

**Webpack version:**
1.13.1 

**Please tell us about your environment:**
Windows 7

**Current behavior:**
I do not know how to incorporate polymer-project.org into an angular2/webpack build.

**Expected/desired behavior:**
Angular2/polymer webpack build.

**Notes**
I've done some set up on a https://github.com/jjarrell50/angular2-seed-test.  This is light weight seed that pulls in the angular stuff. It's got a paper-button in it that does not render.

In the *readme of that repository* i've done some preliminary work, using vulcanize which would bundle all polymer imports, but that still ends up with on file that I don't know how to to bring in.

@TheLarkInn

**Comment by sokra** [comment]
There is currently nothing to do for us

**Comment by TheLarkInn** [comment]
Are you wanting to know how to use vulcanize with webpack?

**Comment by TheLarkInn** [comment]
https://www.npmjs.com/package/vulcanize-loader This could be a solution that you could look into if you haven't @jjarrell50

**Comment by jjarrell50** [comment]
it was more about getting polymer to work with webpack in an angular2
project. Vulcanize was just one thought on solving the problem.

I've since went to angular-cli and it is working over there. I am using the
scripts and html includes from index.html.  That approach may no longer
work with more recent versions of angular-cli. It broke in the last week or
so.  This breakage may be due to other things.

I stepped back from the bleeding edge a bit and am using a slightly older
version of angular-cli.  I've read somewhere that they (do they?) want
polymer to be a first class citizen so I'd expect it to ultimately work in
angular-cli.

Perhaps, Sean, you can confirm that Polymer is supported citizen in the
angular-cli world.

**Comment by TheLarkInn** [comment]
Currently it is not. I think there needs to be a settling of standard IRT this and web components. FWIW, if HTMLImports can be bundled that could be a future goal, but nothing _currently_ that is possible I believe.


Get Outlook for iOS<https://aka.ms/o0ukef>




On Thu, Sep 1, 2016 at 4:57 PM -0500, "Tobias Koppers" <notifications@github.com<mailto:notifications@github.com>> wrote:


There is currently nothing to do for us

-

**Comment by aruntk** [comment]
I've built a package to handle polymer/webcomponents files and html imports (with HMR support)

https://github.com/aruntk/wc-loader. check out.

Demo https://github.com/aruntk/polymer-webpack-demo
