### ISSUE TITLE
Documentation Request: Debugging with V8 Inspector

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack#2724]
**I'm submitting a feature request**

**Webpack version:**
1.10.x/2.x

**Current behavior:**
We don't have any documentation on how to use the new `node-nightly --inspect --debug-brk` feature with webpack. There are a few little details to implement so it is worth having documentation on it. 

**Expected/desired behavior:**
Having a small section in documentation explaining how to leverage the power of `node-nightly` which contains the --inspect flag letting you use the full chrome dev tools to profile, find memory leaks, and debug your webpack builds. 

* **What is the motivation / use case for changing the behavior?**
There are small leaky abstractions from miss use of certain webpack features. Mine being one of them. A useful profiler that people are familiar with like ChromeDevTools can be invaluable

**Comment by sokra** [comment]
see blog post

**Comment by TheLarkInn** [comment]
@bebraw we should try and move this issue over if we can. Then we can have atleast a tracker for it.

**Comment by bebraw** [comment]
Done, https://github.com/webpack/webpack.io/issues/90 .
