### ISSUE TITLE
Cheap source maps do not work with UglifyJsPlugin

### ISSUE THREAD

**Issue by wenbochang** [webpack/webpack#2725]
**I'm submitting a bug report**

**Webpack version:**
1.13.1

**Please tell us about your environment:**
OSX 10.11.5

**Current behavior:**
Source maps either error or generate empty files when using UglifyJsPlugin and `cheap` inside `devtool`

**Expected/desired behavior:**
`cheap` variants generate correct files when using UglifyJsPlugin

**To Reproduce:** 
1. Clone https://github.com/mrooding/webpack-babel-integration-example
2. Change config to https://gist.github.com/wenbochang/b1561d4a4c20faa4f854ab28112ce8c5

This is what I get for different `devtool` options running webpack:
1. `source-map` - works
2. `cheap-source-map` - Error: Failed to parse SourceMap
3. `cheap-module-source-map` - No error, but `bundle.js` is empty inside webpack://
4. `cheap-eval-module-source-map` - No `bundle.js.map` file gets generated

**Browser:** Chrome 51

**Language:** ES6

Thanks in advance for your time!

**Comment by bebraw** [comment]
I can confirm this. 👍

**Comment by robinelvin** [comment]
We seem to have the opposite:

1. ```source-map``` - Error: Failed to parse SourceMap
2. ```cheap-source-map``` - works

Webpack 1.13.1, Ubuntu, Chrome

**Comment by bebraw** [comment]
@robinelvin Any chance for a test repo? Or is it against the same?

**Comment by robinelvin** [comment]
@bebraw This is against our own (private) code. I can provide configs and output if required.

**Comment by bebraw** [comment]
@robinelvin Ok, having something standalone would be the ideal test case. Is it the same with webpack 2?

**Comment by robinelvin** [comment]
@bebraw Webpack 2 won't install due to other package dependencies so I can't test I'm afraid.

As this is a private repo I'm unable to provide the full codebase and unpicking just the Typescript/Javascript is going to take a little time.

**Comment by eloytoro** [comment]
I can confirm that this bug happens in webpack@2.1.0-beta13.
Steps to reproduce
* Set `devtool` to `'source-map'`
* Add `new webpack.optimize.UglifyJsPlugin()` to the list of plugins
* Bundle the project
* No source maps generated
* Remove the `UglifyJsPlugin`
* Bundle the project
* Source maps generated as expected

**Comment by eloytoro** [comment]
Downgrading to webpack@2.1.0-beta-6 solves the issue for me

**Comment by sokra** [comment]
``` js
new UglifyJsPlugin({
  sourceMap: true
})
```

**Comment by jbinto** [comment]
`1.13.1` here, with `source-map`, we get `Error: Failed to parse SourceMap`. Same as @robinelvin  https://github.com/webpack/webpack/issues/2725#issuecomment-231106014

**Comment by wenbochang** [comment]
@jbinto i believe that error is due to current Chrome, it goes away for me in Canary

does `cheap-source-map` work for you?

**Comment by jbinto** [comment]
@wenbochang Thanks. It appears Canary (54.0.2800.0) has resolved this issue. In Chrome 	51.0.2704.103 it is still an issue.

Related Chromium issue: https://bugs.chromium.org/p/chromium/issues/detail?id=611328

Based on the chat there, it seems source map filesize is a factor. With `source-map` our file was 18.5MB, with `cheap-source-map` it was only 2.5MB. Changing to `cheap-source-map` seems to have made it more intermittent in Chrome 51, e.g. only errors 50% of the time.

**Comment by prencher** [comment]
Using Webpack `2.2.0-rc.1`, I'm getting a 1KB source map using the following configuration:
```js
const fs = require('fs');
const path = require('path');

const webpack = require('webpack');
const { CheckerPlugin } = require('awesome-typescript-loader');

const rootDir = path.join(__dirname, '../../');
const sourceDir = path.join(rootDir, 'source');

const packageJson = JSON.parse(fs.readFileSync(path.join(rootDir, 'package.json')));

module.exports = {
    entry: {
        app: '', // Set by gulp task
        vendor: Object.keys(packageJson['dependencies']),
    },
    output: {
        path: '', // Set by gulp task
        filename: '[name].[chunkhash].js'
    },
    devtool: 'cheap-module-source-map',
    resolve: {
        extensions: ['.js', '.jsx', '.ts', '.tsx'],
    },
    module: {
        loaders: [
            { test: /\.json$/, loader: 'json-loader' },
            { test: /\.tsx?$/, loader: 'awesome-typescript-loader?silent=true', exclude: /node_modules/ },
        ]
    },
    plugins: [
        new webpack.LoaderOptionsPlugin({
            minimize: true,
            debug: false,
        }),
        new webpack.DefinePlugin({
            'process.env':{
                'NODE_ENV': JSON.stringify('production')
            }
        }),
        new CheckerPlugin(),
        new webpack.optimize.CommonsChunkPlugin({ name: 'vendor' }),
        new webpack.optimize.OccurrenceOrderPlugin(),
        new webpack.optimize.DedupePlugin(),
        new webpack.optimize.AggressiveMergingPlugin(),
        new webpack.optimize.UglifyJsPlugin({
            comments: false,
            compress: {
                warnings: false,
            },
            sourceMap: true,
        }),
    ],
};
```
It's obviously wrong, and it works as expected in development. If something isn't configured correctly then it is the most obscure thing I have seen in a long time.

**Comment by jjinux** [comment]
I'm pretty sure this is still broken.
