### ISSUE TITLE
Loaders are being expected in every folder where require is pointing to.

### ISSUE THREAD

**Issue by sultanahamer** [webpack/webpack#2726]
**I'm submitting a bug report**

**Webpack version:**
1.10.x/2.x

**Please tell us about your environment:**
OSX 10.x 

**Current behavior:**
while require is pointing to a file which is in sibling project, It is not able to resolve loaders.
**Error message:**
ERROR in ../common-code/directives/datasetSelector/datasetSelectorCtrl.js
Module not found: Error: Cannot resolve module 'raw-loader' in /Users/sultanm/Projects/MSF_OCA/common-code/directives/datasetSelector
 @ ../common-code/directives/datasetSelector/datasetSelectorCtrl.js 4:18-55
___________________________________
Current folder structure

common-code
         directives
              dataSetSelector
                 datasetSelectorCtrl.js
app
    js
      myfile.js

From myfile.js if I require  datasetSelectorCtrl.js from sibling project, I am getting the above error. After doing a npm install raw-loader in the sibling project(common-code), it worked( I have raw loader installed in app folder already).

**Expected/desired behavior:**
It should not throw this error, instead it should resolve the loaders from the working directory.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.** 
Prepare the above folder structure and make sure that the js that you are trying to require has a loader dependency and run webpack.

**Comment by sokra** [comment]
> Webpack version:
> 1.10.x/2.x

have you really tested it with webpack 2?

**Comment by sultanahamer** [comment]
Sorry, I missed that version part. It was the default template coming up. I did not test it with v2.x but with 1.13.1 its happening.

**Comment by sokra** [comment]
This is fixed in webpack 2. Loaders resolve relative to configuration file.
