### ISSUE TITLE
Synchronous dynamic require w/ Webpack 2

### ISSUE THREAD

**Issue by arcanis** [webpack/webpack#2728]
**I'm submitting a bug report**

**Webpack version:**
2.0.0 beta 15

**Please tell us about your environment:**
Linux

**Current behavior:**
While porting my project from Webpack 1 to Webpack 2, I noticed that both of these lines from my codebase are now failing with different errors:
```js
// Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
let req = require.context(`common/resources`, false, /Resource\.js$/);

// Critical dependency: the request of a dependency is an expression
let lang = new Jed(require(`locales/${language}.po`));
```

**Expected/desired behavior:**
They should work just like they do in Webpack 1.X

**What is the expected behavior?**
It shouldn't throw any error.

**What is the motivation / use case for changing the behavior?**
Synchronous dynamic require don't work anymore, which mean that Webpack 2 doesn't support codebases that were previously working fine. New projects can probably make use of `System.import`, but unfortunately, switching old projects from synchronous requires to asychronous imports is in no way a trivial task and should probably be avoided if possible.

 
**Browser:** Chrome 
**Language:**ES5/6

**Comment by sokra** [comment]
I think the problem are the template string, which are not yet supported. Either transpile them or use normal strings as workaround.

**Comment by sokra** [comment]
I'll close this, because we already have an issue for tracking the template string issue.
