### ISSUE TITLE
export var uses getter via Object.defineProperty that breaks <=IE8

### ISSUE THREAD

**Issue by fastest963** [webpack/webpack#2729]
**I'm submitting a bug report**

**Webpack version:**
2.1.0-beta.15

**Please tell us about your environment:**
Windows 10

**Current behavior:**
Original Code:

```
let dateNow = Date.now;
if (typeof dateNow !== 'function') {
  dateNow = function() {
    return (new Date()).getTime();
  };
}
export { dateNow };
```

After webpack:

```
/* harmony export */ __webpack_require__.d(exports, "f", function() { return dateNow; });
...
var dateNow = Date.now;
if (typeof dateNow !== 'function') {
  dateNow = function () {
    return new Date().getTime();
  };
}
```

**Expected/desired behavior:**

```
var dateNow = Date.now;
if (typeof dateNow !== 'function') {
  dateNow = function () {
    return new Date().getTime();
  };
}
exports["f"] = dateNow;
```

**What is the expected behavior?**
I expect that instead of hoisting the exports to the top, they could instead be placed where the export occurred and then the code could be. This would eliminate the necessity of using a getter for the case above.

**What is the motivation / use case for changing the behavior?**
Currently there's no way to polyfill `Object.defineProperty` with a `getter`, see [es5-shim's shams](https://github.com/es-shims/es5-shim#shams). I can't find a way to export a variable without it using `Object.defineProperty`. When using commonjs, there were ways to export without requiring the use of `Object.defineProperty`.

**Browser:**
IE 6-8

**Language:**
ES6/7 (with Babel)

**Comment by Kovensky** [comment]
ES6 module exports are hoisted by definition, and this behaviour is essential for live bindings.

The only export that is not hoisted is `export default`.

Now, it should be possible have webpack generate, say, a `getDateNow()` function instead of a getter and call that instead, but it's probably a bad idea to do it by default.

**Comment by sokra** [comment]
We may remove **some** Object.defineProperty calls but a complete ES6 impl require getters at some point. So full ES6 Modules are probably not IE8-compatible

Difficult parts:

### evals

``` js
import { doSomething } from "other";
// doSomething accesses the a export from this module
var a;
eval("for(var i = 0; i < 10; i++) { a = i; doSomething() }");
export { a }
```

### star reexports of non-es6 modules

``` js
export * from "other";
```

**Comment by mc-zone** [comment]
Is it possible that made a **Compatible Version** to IE8 and below ? :thought_balloon: 

I mean, replace all assignment expression about harmony export variables to `exports["a"] = ...`. Then remove use of `__webpack_require_.d` .

https://github.com/webpack/webpack/blob/master/lib/dependencies/HarmonyExportSpecifierDependency.js#L42

**Comment by mc-zone** [comment]
To be honest, I was attempt to to do this by a plugin, but I have not found a way can visit the `ast` about each modules in a plugin. 

When I use `compiler.parser.plugin('program',function(ast){})` , I don't know which module was it belong to. :flushed:

**Comment by sokra** [comment]
After some discussion we decided for the following statement regarding IE8:

We don't support IE8 in webpack 2. IE8 is not supported by Microsoft and doesn't get security fixes. We think it's no responsible to allow web developers to build webapps which support IE8. They must break!

**Comment by janv** [comment]
I could just observe a problem in our codebase related to the behavior in the current version of Firefox.

We have code that is structurally similar to the OPs example.
Firefox has a weird bug that results in the getter returning `undefined` unless I go to some lengths to make it retain the reference to `dateNow` (namely by doing `window.setTimeout(() => dateNow)`) 

So I would ask to reconsider changing the implementation to something like the desired behavior in the OP.
