### ISSUE TITLE
DefinePlugin breaks with ES6 string interpolation

### ISSUE THREAD

**Issue by niieani** [webpack/webpack#2733]
**I'm submitting a bug report**

**Webpack version:**
2.1.0-beta-15 (possibly ^1 too)

**Please tell us about your environment:**
OSX 10.11

**Current behavior:**
given this DefinePlugin in `webpack.config.js`:

   ```js
        new DefinePlugin({
          'process.env': {
            'WEBPACK_HOST': JSON.stringify('localhost'),
            'WEBPACK_PORT': JSON.stringify(9000)
          }
        })
   ```

and this source code:

```js
mainWindow.loadURL(`http://${process.env.WEBPACK_HOST}:${process.env.WEBPACK_PORT}/index.html`);
```

Webpack output yields this incorrect file:
```js
mainWindow.loadURL(`http://${"localhost"}:${"9000"}/index.html`);
```

**Expected/desired behavior:**
Webpack should correctly interpolate strings and drop `$` and the quotes `""` and brackets `{}` after replacing the variable:

```js
mainWindow.loadURL(`http://localhost:9000/index.html`);
```

* **Browser:** n/a
 
* **Language:** all

**Comment by sokra** [comment]
> Webpack output yields this incorrect file

It's not incorrect. The code is valid and works. You are requesting a minimizing optimization that should be done by uglifyjs

**Comment by niieani** [comment]
@sokra You are incorrect. The code (`${"localhost"}`) generates a syntax error:

```
Uncaught SyntaxError: Unexpected token {
```

Please reopen.

**Comment by niieani** [comment]
@sokra My bad, I initially forgot to stringify the token! 

All the best,
Bazyli
