### ISSUE TITLE
Call for new maintainers

### ISSUE THREAD

**Issue by sokra** [webpack/webpack#2734]
https://medium.com/webpack/webpack-its-getting-real-92c60fca1db1

Loaders:
* html-loader
* mocha-loader
* transform-loader
* jshint-loader
* json5-loader
* coffee-loader
* coffee-redux-loader
* coverjs-loader

Plugins:
* compression-webpack-plugin
* i18n-webpack-plugin
* component-webpack-plugin

Other:
* grunt-webpack
* karma-webpack

**Comment by TheLarkInn** [comment]
Tagging @gdi2290 for `json5-loader`

**Comment by d3viant0ne** [comment]
Well, I was just telling @TheLarkInn last week I was looking for a place to jump in and help out, may as well put my money where my mouth is.

I'll throw my hat in the ring for karma-webpack and if it isn't to time intensive in the coming weeks, I can pick up html-loader as well.

@sokra - If you have any questions of me, Sean knows how to get a hold of me outside github.

**Comment by sidjain26** [comment]
I don't know what I'd be able to help with, but I have been using webpack daily for the past few months. Let me know if there's anything mundane and not too exciting that I might be able to help with.

**Comment by Vall3y** [comment]
I have some time freed up, and would like to help. Besides the coffee loaders I'm willing to work on anything.

**Comment by tricoder42** [comment]
I could help with [mocha-loader](https://github.com/webpack/mocha-loader). I'm using it anyway and there're a lot of good PR.

**Comment by kostasmanionis** [comment]
Got way too much free time, could help out with `jshint-loader` or any of the plugins.

**Comment by lluia** [comment]
Have some free time too and would love to help maintaining some loader in the above list!

**Comment by imvetri** [comment]
I did my first suggestion in a comment for an issue in html-loader :)

I will provide my contribution as well.


P.S - I am a newbit to git code contribution

**Comment by sokra** [comment]
Great to see you all interested :heart:. I think we will wait a week before distributing the repos, so everybody has a chance to opt-in. :+1:

**Comment by nithinpb** [comment]
Hello. I have been webpack, specifically, jshint and mocha loaders regularly. I'll be happy to contribute.

**Comment by palmerj3** [comment]
I could help out with the compression-webpack-plugin

**Comment by petrunov** [comment]
Let me take html-loader & mocha-loader

**Comment by minwe** [comment]
I have used Browserify for a long time, maybe I can help with `transform-loader`.

**Comment by EcutDavid** [comment]
I want to help with i18n-webpack-plugin.   
For now it's seems in lack of documentation such as user may don't know they can replace `__` to other function name. https://github.com/webpack/i18n-webpack-plugin/blob/master/index.js#L30,

**Comment by andreicek** [comment]
I would be willing to help with maintaining `html-loader`.

**Comment by rajzshkr** [comment]
I'm willing to maintain grunt-webpack

**Comment by danez** [comment]
I could offer help for grunt-webpack.

**Comment by jon301** [comment]
Hi. I would be very happy to give some help on any of these :)

**Comment by lluia** [comment]
I actually would 💘  to help maintain one of those:  
• component-webpack-plugin
• i18n-webpack-plugin
• html-loader 
• json5-loader

**Comment by sidsarasvati** [comment]
I would be interested is dedicating some time on the webpack project. I would mostly be interested in:

- component-webpack-plugin
- i18n-webpack-plugin
- html-loader

**Comment by palnes** [comment]
@sidsarasvati @lluia Ref component-webpack-plugin, is that related to this? https://github.com/componentjs/component

**Comment by TheLarkInn** [comment]
Tagging @mikaak who personally expressed interest.

**Comment by MikaAK** [comment]
Thanks @TheLarkInn I'm interested in karma-webpack I would love to help out where I can

**Comment by ClemMakesApps** [comment]
I'd be happy to help out as well on any (besides coffeescript as i do not have experience there)

**Comment by dotBits** [comment]
I would be glad to give my contribution where needed. This tool is awesome!

**Comment by hemanth** [comment]
I am very much interested in `html-loader` and `jshint-loader` thank you!

**Comment by radubrehar** [comment]
Happy to support the webpack ecosystem! Any other loaders remained unmantained so I can help with them?

**Comment by micronaut** [comment]
I would like to help with maintaining any of the loaders, or any where else I can help out.

**Comment by IonutC** [comment]
I'd be more than happy to give a helping hand to any loader.

**Comment by goldhand** [comment]
I will help with any available but have a special interest in __karma-webpack__

**Comment by kiurchv** [comment]
I'd be happy to help with `compression-webpack-plugin`

**Comment by michael-ciniawsky** [comment]
@sokra would like to help out with ```html-loader``` for reasing why, i'm the author and maintainer of [posthtml](https://github.com/posthtml)```-loader``` and we depend on that one for exporting.

**Comment by abouthiroppy** [comment]
I'd be more than happy to help with `html-loader` and `mocha-loader` :)

**Comment by sidjain26** [comment]
For those of you active on Facebook and willing to share/learn Webpack knowledge: https://web.facebook.com/groups/webpack/

**Comment by km-tr** [comment]
I will help with any available but have a special interest in `transform-loader`, or anything.

**Comment by DanielaValero** [comment]
Bello, count on me for karna-webpack and documentation. I have been setting webpack and karma webpack in a project lately, and I can tell how painful the documentation is.

Let us do a work group to improve it, really, when the documentation is more intuitive, more people will be enabled to use webpack.

Let me know what the next steps are. I will be attend to it

**Comment by d3viant0ne** [comment]
@DanielaValero - https://github.com/webpack/webpack.io/issues is where all of the issues / proposals for the docs project live.

**Comment by carlos-** [comment]
Hi, I would like to help here. My experience is building a few plugins (small though) for an internal project. I did not have to build loaders though, but I would love to contribute there. 

We use in production:
* html-loader
* grunt-webpack
* karma-webpack

**Comment by sokra** [comment]
So we discussed it and here is the result:

* Everyone gets an invite to a webpack/contributor-team. Please join if you still want to help out.
* @TheLarkInn invites you to out slack, if he can grab your email from github. Elsewise contact him.
  * We'll have a room for you to discuss. If you want a separate room for your team you can ping @TheLarkInn 
* We assign one project leader to every project.
  * The project leader is responsible for managing the project, merging PRs, etc.
  * We may promote more people to project leaders, but we try to start with one to coordinate the discussion.
* We assigned you to a project, but if you feel unhappy with our choice feel free to switch projects (comment or contact me, I'll edit the list).
  * The project leader should assign a new project leader then... ;)
* We won't move the loaders into another namespace (organization/user), except to the namespace of the underlying library (i. e. webpack/pug-loader -> pugjs/pug-loader).
* We expect the first contributions to be:
  * Add issue and pull request templates (best copy the templates from webpack/webpack and modify them to fit to the project).
  * Add automated tests (CI) for the projects where they are missing.
    * This makes contributing easier and allows you to get into the project.
    * If unsure which framework to use: I use [Travis CI](https://travis-ci.org/), mocha and should.js for the webpack/webpack tests.
    * Here is an example how to write tests for simple loaders: [angular2-template-loader](https://github.com/TheLarkInn/angular2-template-loader/blob/master/test/loader.spec.js)
  * Edit the README (documentation) to reflect all current features.
  * Take care of existing PRs. Consider wisely if
    * they fit into the general direction of the loader.
    * they implement some feature in a reusable/general way.
    * they are tested.
    * they add documentation for new features.
    * you be able to maintain this feature in future.
  * Take care of existing issue.
  * Feel free to break compatiblity (major version), if there are good reasons.
  * If the project is in stable state and you want to publish it to npm, contact me I'll give you npm permissions.
    * I want to take a final look to make sure you don't delete everything... :smile:
  * You are free to use any coding style, managing style, whatever

Teams and leaders:

## html-loader: @hemanth

@d3viant0ne
@imvetri
@petrunov
@andreicek
@michael-ciniawsky
@abouthiroppy
(@lluia)
(@sidsarasvati)
(@carlos-)

## mocha-loader: @carlos-

@tricoder42
@nithinpb
@petrunov
@rajzshkr
@abouthiroppy

## transform-loader: @minwe 

@km-tr

## jshint-loader: @kostasmanionis 

@nithinpb
@hemanth

## json5-loader: @gdi2290

@d3viant0ne

## compression-webpack-plugin: @palmerj3 

@kiurchv

## i18n-webpack-plugin: @EcutDavid 

@lluia
@sidsarasvati

## component-webpack-plugin

This will be deprecated...

## grunt-webpack: @danez 

@rajzshkr
@carlos-

## karma-webpack: @MikaAK 

@d3viant0ne
@goldhand
@DanielaValero
(@carlos-)
(@d3viant0ne)

## documentation: @bebraw

@DanielaValero

## Unassigned

@sidjain26
@Vall3y
@lluia
@gholtslander-va
@jon301
@ClemMakesApps
@dotBits
@radubrehar
@micronaut
@IonutC

Either pick a team of your choice,
or any team leader is allowed to pick you for the team.
If none of these happens I'll assign you by random.

(people in brackets are already in another team and may concentrate on the other one)

PS: If there are any objections, feel free to comment or contact me privatly.

**Comment by radubrehar** [comment]
@sokra count me in for the `json5-loader` - lead by @gdi2290

**Comment by jon301** [comment]
I'll be happy to help on the karma-webpack plugin

**Comment by kentcdodds** [comment]
I already mentioned to Sean that I can help with `json5-loader` :+1:

**Comment by TheLarkInn** [comment]
Yup I shot @Sokra a message you'll see an invite

**Comment by sidjain26** [comment]
Would be happy to be on the `jshint-loader` team!

**Comment by radubrehar** [comment]
Have invites already been sent? If so, haven't received one :)

**Comment by d3viant0ne** [comment]
@radubrehar - you are on the unassigned list. 
![screen shot 2016-07-23 at 3 31 21 pm](https://cloud.githubusercontent.com/assets/8420490/17080146/8cc348d0-50ea-11e6-8f54-e1ed5ed2b34c.png)

**Comment by radubrehar** [comment]
@d3viant0ne  I just replied above I'd be happy to help with the `json5-loader` cc @gdi2290

**Comment by d3viant0ne** [comment]
Works for me, I've got html & karma to work on as well.

**Comment by d3viant0ne** [comment]
@sokra - Preference on which coverage tool to use?

**Comment by sokra** [comment]
No preference.

webpack/webpack [used istanbul](https://github.com/webpack/webpack/blob/master/package.json#L91) and uploads the result to [coveralls and codecov.io](https://github.com/webpack/webpack/blob/master/.travis.yml#L19-L22). That works pretty good.

**Comment by d3viant0ne** [comment]
I meant a preference between the two but both works :) Those will also require an admin to enable initially.

**Comment by sokra** [comment]
codecov.io

**Comment by sokra** [comment]
| project | test status | open issues | open pull requests |
|---|---|---|---|
| html-loader | [![Build Status](https://travis-ci.org/webpack/html-loader.svg?branch=master)](https://travis-ci.org/webpack/html-loader) | [![Github issues](https://img.shields.io/github/issues/webpack/html-loader.svg?maxAge=600)]() | [![Github pull requests](https://img.shields.io/github/issues-pr/webpack/html-loader.svg?maxAge=600)]() |
| mocha-loader | [![Build Status](https://travis-ci.org/webpack/mocha-loader.svg?branch=master)](https://travis-ci.org/webpack/mocha-loader) | [![Github issues](https://img.shields.io/github/issues/webpack/mocha-loader.svg?maxAge=600)]() | [![Github pull requests](https://img.shields.io/github/issues-pr/webpack/mocha-loader.svg?maxAge=600)]() |
| transform-loader | [![Build Status](https://travis-ci.org/webpack/transform-loader.svg?branch=master)](https://travis-ci.org/webpack/transform-loader) | [![Github issues](https://img.shields.io/github/issues/webpack/transform-loader.svg?maxAge=600)]() | [![Github pull requests](https://img.shields.io/github/issues-pr/webpack/transform-loader.svg?maxAge=600)]() |
| jshint-loader | [![Build Status](https://travis-ci.org/webpack/jshint-loader.svg?branch=master)](https://travis-ci.org/webpack/jshint-loader) | [![Github issues](https://img.shields.io/github/issues/webpack/jshint-loader.svg?maxAge=600)]() | [![Github pull requests](https://img.shields.io/github/issues-pr/webpack/jshint-loader.svg?maxAge=600)]() |
| json5-loader | [![Build Status](https://travis-ci.org/webpack/json5-loader.svg?branch=master)](https://travis-ci.org/webpack/json5-loader) | [![Github issues](https://img.shields.io/github/issues/webpack/json5-loader.svg?maxAge=600)]() | [![Github pull requests](https://img.shields.io/github/issues-pr/webpack/json5-loader.svg?maxAge=600)]() |
| compression-webpack-plugin | [![Build Status](https://travis-ci.org/webpack/compression-webpack-plugin.svg?branch=master)](https://travis-ci.org/webpack/compression-webpack-plugin) | [![Github issues](https://img.shields.io/github/issues/webpack/compression-webpack-plugin.svg?maxAge=600)]() | [![Github pull requests](https://img.shields.io/github/issues-pr/webpack/compression-webpack-plugin.svg?maxAge=600)]() |
| i18n-webpack-plugin | [![Build Status](https://travis-ci.org/webpack/i18n-webpack-plugin.svg?branch=master)](https://travis-ci.org/webpack/i18n-webpack-plugin) | [![Github issues](https://img.shields.io/github/issues/webpack/i18n-webpack-plugin.svg?maxAge=600)]() | [![Github pull requests](https://img.shields.io/github/issues-pr/webpack/i18n-webpack-plugin.svg?maxAge=600)]() |
| grunt-webpack | [![Build Status](https://travis-ci.org/webpack/grunt-webpack.svg?branch=master)](https://travis-ci.org/webpack/grunt-webpack) | [![Github issues](https://img.shields.io/github/issues/webpack/grunt-webpack.svg?maxAge=600)]() | [![Github pull requests](https://img.shields.io/github/issues-pr/webpack/grunt-webpack.svg?maxAge=600)]() |
| karma-webpack | [![Build Status](https://travis-ci.org/webpack/karma-webpack.svg?branch=master)](https://travis-ci.org/webpack/karma-webpack) | [![Github issues](https://img.shields.io/github/issues/webpack/karma-webpack.svg?maxAge=600)]() | [![Github pull requests](https://img.shields.io/github/issues-pr/webpack/karma-webpack.svg?maxAge=600)]() |

**Comment by d3viant0ne** [comment]
@sokra  karma-webpack & html-loader will be green this afternoon, I'm into the Travis / test issues now for both loaders.

**Comment by sokra** [comment]
no hurry, it's just a overview :smile: :+1:

**Comment by TheLarkInn** [comment]
Love this overview though. Think this deserves to be on the readme somewhere?

**Comment by d3viant0ne** [comment]
Agreed

**Comment by danez** [comment]
Looking forward to get together with all of you on slack. Have some questions but don't want to pollute this issues even more. Kindly asking when can we expect the invites to happen? :)

**Comment by TheLarkInn** [comment]
I believe I sent you an invite to the email on your github @danez

**Comment by radubrehar** [comment]
@TheLarkInn could you please send me as well an invite for slack? I'm on the `json5-loader` team.

**Comment by sidjain26** [comment]
@TheLarkInn not sure if the Slack invites were sent out already, but I didn't receive one yet. I'm on the `jshint-loader` team.

**Comment by michael-ciniawsky** [comment]
@sokra can you share the link to the loader's table you posted above? i'm currently updating the README for webpack/webpack and would like to add this to it. Currently WIP https://github.com/michael-ciniawsky/webpack, also plase share your critics, it's not complete yet if a few badges etc. are missing, i'm 'readding' them of course, but haven't found a good place for them yet :). And finally who are the maintainers for core besides shama, jhnns ?

**Comment by TheLarkInn** [comment]
If I have missed anyone please let me know.

**Comment by DanielaValero** [comment]
@TheLarkInn you've missed me, I sent you a message via twitter with my email

**Comment by imvetri** [comment]
@DanielaValero are you clarifying about slack invite?

**Comment by DanielaValero** [comment]
Sorry, I forgot that detail, yes, is about the invite :)

**Comment by IonutC** [comment]
@sokra can you put me in one of these 2 teams: grunt-webpack or json5-loader.
Thank you.

**Comment by sokra** [comment]
@IonutC I've put you into the grunt-webpack team

**Comment by palmerj3** [comment]
Hello can you send me the invite to the slack channel? I'm the maintainer of compression-webpack-plugin

**Comment by TheLarkInn** [comment]
For anyone who hasn't got an invite shoot me an email (should be listed on my github)

**Comment by ClemMakesApps** [comment]
I sent an email and @sokra can you add me to i18n-webpack-plugin? Thanks!

**Comment by sokra** [comment]
> can you add me to i18n-webpack-plugin

Good choice. There is much potential in this plugin, at lot to do, but a small team :+1:

**Comment by JanKanty** [comment]
If you need someone else. I can help with mocha / html loaders.

**Comment by sokra** [comment]
Sure, added you to the mocha-loader team.

**Comment by imvetri** [comment]
@sokra  I couldn't find your email address. Can you please send me the slack.

**Comment by TheLarkInn** [comment]
I am sending invites, email me if you haven't already. (My email is listed on my github)

**Comment by JanKanty** [comment]
@sokra are we gonna have any slack channel or sth for communicate?

**Comment by TheLarkInn** [comment]
@JanKanty https://github.com/webpack/webpack/issues/2734#issuecomment-234957114

**Comment by micronaut** [comment]
@sokra / @tricoder42 I would like to help out with mocha-loader

**Comment by sokra** [comment]
A note regarding the github teams:

Everyone is invited into the contributors-team. This doesn't give you any permission, but you are part of the organization.

Only the project leaders are invited into a project-specific team. i. e. for the json5-loader it's the json5-loader-team. This team give write permission for the project. The project leader is team maintainer: He can invite and kick people from the project-specific team.

This means in the current state only the project leader has write permissions. In this state it enforces a PR approach: Member create PR, team reviews it, project leader merge it.

The project leader may give more people to permission (by inviting them into the project-team), if he wants to. But he doesn't have to do that if he like more control over the direction of the project.

For bigger teams or complex project I recommend the PR approach, but the choice is yours...

I just want to make sure that nobody feels discriminate because he is not in the github project team even if my above list states otherwise. The github teams are just for permissions. Check the above list or the READMEs for the complete team.

**Comment by dashed** [comment]
I hope that a lot of the enthusiasm may be geared towards the webpack docs 😄  (disclaimer: unsure if there is a dedicated docs team).

**Comment by TheLarkInn** [comment]
@dashed anyone who is apart of this effort is also able to work on documentation. There is no specific obligation to be working on just the loaders and plugins.

**Comment by TheLarkInn** [comment]
But @bebraw is always looking for more able bodies to help with documentation.

**Comment by km-tr** [comment]
@TheLarkInn I have added profile the e-mail address. Can you please send me the slack invite?
(transform-loader)

**Comment by wong2** [comment]
I'm interested in `i18n-webpack-plugin`, which I'm using in my projects

**Comment by mover96** [comment]
@sokra @bebraw I would love to be on the documentation team

**Comment by d3viant0ne** [comment]
Mitchell is like Webpack documentation with a pulse, definitely should be on that team :)

**Comment by TheLarkInn** [comment]
I think I sent you a slack invite already @mover96

**Comment by TheLarkInn** [comment]
@sokra will add you to the documentation team

**Comment by mover96** [comment]
Yeah I'm in the slack, not sure if there is a documentation channel I need to be in. I'm working on some gists that I'll start posting the the webpack.io repo when they are ready.

**Comment by TheLarkInn** [comment]
Alright!!!

**Comment by datapimp** [comment]
I would love to help with documentation, and I have an electron app for managing webpack projects ( configuration, launching servers, inspecting the modules and assets ) that was part of a commercial effort of mine that I am winding down.  Would love to rewrite it and support it as part of an official open source effort

**Comment by bebraw** [comment]
@datapimp Thanks. I invited you to the Slack so see you there.

**Comment by manekinekko** [comment]
@sokra @TheLarkInn feel free to add me in. Plugin/loaders or core.

**Comment by blairg** [comment]
If you are still needing help on anything let me know. Just parked a side project I was working. Would be cool to get involved in something different.

**Comment by TheLarkInn** [comment]
@blairg We are always loving for people who can commit time. We have a few initiatives that we need help with. Obviously the above loaders/plugins. However our number one priority right now is our [new docs initiative](https://github.com/webpack/webpack.io)

Then we have a bunch of other things that can be done. @sokra can you add @manekinekko and @blairg to the contrib team? Thanks!!!!

**Comment by TheLarkInn** [comment]
@blairg shoot me an email with your email so I can invite you to our slack.

**Comment by sidsarasvati** [comment]
I'll be interested in getting involved

**Comment by TheLarkInn** [comment]
@sidsarasvati we would love some docs help!! Pick anything on github.com/webpack/webpack.io in our 2.x milestone. If we had 1 person tackle one doc and put in one PR for it (doesn't have to be perfect) we could have the doc milestone crushed.

**Comment by blairg** [comment]
Hi Sean,

My slack handle is @blair.garrett

Thanks
Blair

**Comment by bebraw** [comment]
Thanks for the interest guys. We've set up maintenance teams. We might still open specific issues at repositories needing attention. You can also contact us directly if you want to pitch in. 👍

**Comment by snitin315** [comment]
@sokra @TheLarkInn I would like to help with the documentation if needed.

**Comment by evilebottnawi** [comment]
If you want to help webpack, webpack-contrib or webpack ecosystem packages feel free to DM https://twitter.com/evilebottnawi
