### ISSUE TITLE
commonjs2 library with externals uses value instead of key for require

### ISSUE THREAD

**Issue by autochthe** [webpack/webpack#2738]
**Steps to reproduce**

Here is a minimal example ([webpack-externals-bug.zip](https://github.com/webpack/webpack/files/348522/webpack-externals-bug.zip)):

package.json
```json
{
  "name": "webpack-externals-bug",
  "version": "1.0.0",
  "description": "Minimal example demonstrating webpack externals error when exporting commonjs2 library",
  "main": "output.js",
  "scripts": {
    "prepublish": "webpack"
  },
  "author": "Mara Kim",
  "license": "ISC",
  "devDependencies": {
    "react": "^15.2.0",
    "webpack": "^1.13.1"
  }
}
```

webpack.config.js
```javascript
module.exports = {
    entry: __dirname + '/index.js',
    output: {
        filename: 'output.js',
        path: __dirname,
        library: "Test",
        libraryTarget: "commonjs2",
    },
    externals: {
        react: "React",
    },
};
```

index.js
```javascript
"use strict";

let React = require('react');

console.log(React);
```

To build:

    npm install

Open the resulting `output.js` and search for the line with `module.exports = require(`.

**Current output**
```javascript
    module.exports = require("React");
```

**Expected output**
```javascript
    module.exports = require("react");
```

It appears that webpack is incorrectly using the value instead of the key in the externals object to generate the require statement.

**Webpack version**
1.13.1

**Environment**
OSX 10.10.5

**Comment by autochthe** [comment]
Attempting to use the generated library with `require("react")` double imports React.js

**Minimal example**

[webpack-externals-bug-usage.zip](https://github.com/webpack/webpack/files/348583/webpack-externals-bug-usage.zip)

To build:

    cd webpack-externals-bug/ && npm install && cd .. && npm install

Search the resulting `output.js` for `var React =`.  Note how the React has been imported twice.  This minimal example doesn't generate any warnings for some reason, but this more complex example generates many warnings (https://github.com/autochthe/react-console/tree/master/example) complaining about modules with equal name ignoring case:

> WARNING in ./~/react/react.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.

> WARNING in ./~/React/react.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.

**Comment by sokra** [comment]
That's the correct behavior
