### ISSUE TITLE
[bug] Module evaluated twice.

### ISSUE THREAD

**Issue by trusktr** [webpack/webpack#2740]
**I'm submitting a bug report**

**Webpack version:**
1.10.x

**Please tell us about your environment:**
OSX 10.x

**Current behavior:**
A module is evaluated twice.

**Expected/desired behavior:**
This should not happen by default. It really goes against the [ES6 module contract](http://www.ecma-international.org/ecma-262/6.0/#sec-moduleevaluation).

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.** 
Using the `DedupePlugin` [does not solve the issue](https://github.com/webpack/webpack/issues/2134) (I tried and verified). No repro yet, but I have a file that starts with the following, and as you can see it has a console.log at the top level:

```js
// infamous/motor/Node.js
import 'geometry-interfaces'
import Motor from './Motor'
import MotorHTMLNode from '../motor-html/node'

console.log(' -- Node module ?????!')
```

Multiple modules in the app import that file, and the `console.log` statement is fired twice, as seen in the output:

![screen shot 2016-07-05 at 11 25 51 pm](https://cloud.githubusercontent.com/assets/297678/16609912/641914be-430c-11e6-9ac1-2b7244d7a8c2.png)

* **What is the expected behavior?**
The ` -- Node module ?????!` output should only appear once.

* **What is the motivation / use case for changing the behavior?**
If this isn't a bug, then to follow the spec, making modules easier to reason about and less error-prone. Problems can happen when data structures are expected to be singletons.
 
* **Browser:** not applicable
 
* **Language:** ES6/7 via Babel

**Comment by trusktr** [comment]
@bebraw This is happening with the same code base as I have in #2735. When I import `Node` from my app's entry point, I get this problem. But, when I import `Scene`, that's when I get #2735. Seems like depending on which module I import first dictates the order of module evaluation. In my case, the `Node` module has a dependency loop that eventually imports `Scene`, while `Scene` imports `Node` directly, and uses it during module evaluation at which point it is `undefined` (live binding or not).

**Comment by trusktr** [comment]
I was trying to make a reproduction, but apparently the results are different when getting the `infamous` dependency from GitHub (including built files normally build on prepublish). I am only able to reproduce by `npm link`ing `infamous` from the local file system (which is how I'm doing my development).

Reproduction script (I verified that it reproduces the problem each time):

```sh
# folder to contain everything
mkdir webpack-issue-2740
cd webpack-issue-2740

# set up infamous dependency
git clone git@github.com:trusktr/webpack.git infamous
cd infamous
git checkout issue-2740-infamous # infamous dependency stored in this branch
npm install
npm link
cd ..

# set up reproduction example
git clone git@github.com:trusktr/webpack.git app
cd app
git checkout issue-2740 # sample app is in this branch
npm install
npm link infamous # this step is required, otherwise we get errors relating to issue #2735
npm run local
```

Then open `localhost:8080/welcome` in your browser to see the duplicate output in the console.

Note, I `npm shrinkwrap`ped the infamous dependencies, but was not able to do so for the example app because the `npm link` step seems to get in the way of that. It should be fine though.

**Comment by trusktr** [comment]
I know the reproduction is a little complicated, but the app is as minimal as possible, importing only a single thing from the `infamous` dependency. I you guys could check it out, it would be highly appreciated; I put some time into making that repro. :]

**Comment by trusktr** [comment]
To see the original code where the `console.log` line originates, just open up `webpack-issue-2740/infamous/src/motor/Node`. Note, that file is compiled, and the app is actually using the transpiled version: `webpack-issue-2740/infamous/motor/Node` (omit the `src` folder in the path to access the build equivalents).

**Comment by trusktr** [comment]
Here's a dependency graph with other dependencies removed for simplicity, so I'm just showing the relevant circular dependencies. The arrows point to the importing module (f.e. you can see that `motor-html/web-component` is imported by `motor-html/base`). All are `.js` files.

![screen shot 2016-07-06 at 1 42 55 pm](https://cloud.githubusercontent.com/assets/297678/16633832/f3aa7a5a-437f-11e6-9a9f-69e67eeefdfb.png)

**Comment by sokra** [comment]
I can repo this.

webpack 1 resolves loaders configured in webpack.config.js relative to the file which contains the require/import. This means for `infamous/motor/Node` in `app/index.js` the `babel-loader` from `app/node_modules` is used. For `../motor/Node` in `infamous/motor-html/node.js` the `babel-loader` from `infamous/node_modules` is used.

Each module gets an identifier containing loaders and resource. This makes both modules different and the same module is emitted twice (and therefore executed twice).

webpack 2 changes this behavior as configurated loaders are resolved relative to the configuration file. You can simulate the same behavior with `resolveLoader.root = "...node_modules"`

**Comment by trusktr** [comment]
@sokra Thanks for the explanation. Did you mean `resolveLoader.root = "../node_modules"` or ``resolveLoader.root = "./node_modules"`` instead of ``resolveLoader.root = "...node_modules"``?

**Comment by trusktr** [comment]
Ah, nvm, you just were typing shortcut for absolute path I think.

**Comment by sokra** [comment]
yep, something like `path.join(__dirname, "node_modules")`

**Comment by trusktr** [comment]
@sokra Seems to have worked. Do you think it would be worth changing this in v1 so that it follows ES6 Module expectations out-of-the-box?

**Comment by sokra** [comment]
The change is a breaking change, so I don't change it in v1.
