### ISSUE TITLE
Webpack does not seem to load child folder views

### ISSUE THREAD

**Issue by ntinoco96** [webpack/webpack#2742]
Guys, I am not sure if this is BUG or something I am doing wrong.   I have posted the question in stackoverflow but I have not recieved any answers.   My issue is with webpack not loading child folder views even though the webpack build has no errors.  

More explanation here: http://stackoverflow.com/questions/38003193/webpack-with-oclazyloading-not-loading-partials

**Comment by sokra** [comment]
no webpack issue.
