### ISSUE TITLE
Ghost (Handlebars) template support/fix

### ISSUE THREAD

**Issue by eugeneross** [webpack/webpack#2743]
**I'm submitting a bug report** and/or **submitting a feature request**
I have a development environment utilizing Gulp and Webpack together. The sole purpose of using Gulp is to serve up a Ghost server for theme development using ReactJS (which I have working). The purpose for Webpack is to compile and serve my dependencies for my project. As of right now, I cannot load the bundled `.js` file within my test theme. I'm curious if this is a Webpack issue by itself, that it either can't load `.hbs` files or something within my configuration is messed up.

**Webpack version:**
1.13.0

**Please tell us about your environment:**
OSX El Capitan

**Current behavior:**
Ghost server loads fine, but when I switch to the theme I'm developing, the page errors out saying it can't find my bundled `.js` file with a 404. I'm thinking:
1. I _don't_ have Webpack configured to serve `.hbs` files correctly.
2. I _do_ have Webpack configured to serve `.hbs` files correctly, but my configuration in general is messed up.
3. This is an impossibility for Webpack at the moment (hence the added feature request 😉)

**Expected/desired behavior:**
Load bundled `.js` within served `.hbs` file for a Ghost theme.
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.** 

I've provided my project for an example. Just follow the super simple setup and you're good to go.

[Project link](https://github.com/eugeneross/react-ghost)

```
My-Project
|--/gulp
   |--/dev-tasks              //individual dev gulp tasks
      |-ghost.js              //Initializes Ghost config, run's sequence of tasks for webpack-dev-server
      |-init.js               //triggers symlinking of Ghost theme
      |-sequence.js           //maps out sequence of Gulp tasks
      |-styles.js             //style compiling
      |-symlink.js            //links local theme with Ghost configuration in /node_modules/
      |-task-runner.js        //runs Gulp tasks
      |-webpack-build-dev.js  // Loads the dev compiler 
      |-webpack-build-prod.js // Not worrying about this one...
      |-webpack-dev-server.js // Runs the devServer
   |-ghost-dev-config.js      //configures Ghost environment
|--/public
   |-default.hbs
   |-index.hbs
   |-package.json
|--/src
   |--/containers
      |-App.js
      |-Home.js
      |-StyleGuide.js
      |-Uploader.js
   |--/styles
      |-main.sass
   |-router.js
|-gulpfile.js
|-package.json
|-webpack.dev.config.js
|-webpack.prod.config.js


```
- **What is the motivation / use case for changing the behavior?**
  To support the loading of bundled `.js` file within `.hbs` files for use of templates. I'm aware of the `HTMLWebpackPlugin` for trying to load template files, then have Webpack spit out a desired file name and path that is specified, but I don't think this is doing me any justice. 
- **Language:** [ES6/7, ReactJS, Handlebars]

**Comment by bebraw** [comment]
Any luck with this? webpack can't load Handlebars without some extra configuration.

**Comment by eugeneross** [comment]
@bebraw I haven't touched on this project for a while because my issue still stands.
