### ISSUE TITLE
problem running localhost:3000

### ISSUE THREAD

**Issue by Shashank7gits** [webpack/webpack#2744]
hello there. I got stuck at the final stage of environment creation. just when i typed browser-sync start --server --directory --files "*" it ran but error occured (event.js:141 throw er;) <--this was the error shown. please tell me how to rectify such error.

I have version 4.4.7 of node.js and 3.10.3 version of npm installed in my windows pc.

please reply soon..

**Comment by andreicek** [comment]
Can you provide your `webpack.config.js`, and a full stack trace of the error?

**Comment by bebraw** [comment]
@Shashank7gits Did you figure it out?
