### ISSUE TITLE
Customization of application

### ISSUE THREAD

**Issue by knapeto** [webpack/webpack#2746]
Hi everybody. Actualy I working on customization of react app. I need something like css overriding. For example:

```javascript
<script src="custom.js"></script>
<script src="main.js"></script>
```

Custom and main file have component “Button” and when exist custom.js which has same component, I need use “Button” from custom.js
Any ideas?

**Comment by rafde** [comment]
You should probably look into CommonChunkPlugin http://webpack.github.io/docs/list-of-plugins.html#commonschunkplugin and have custom.js and main.js as an entry point which will produce a common file that both will reference.
