### ISSUE TITLE
cant use fs

### ISSUE THREAD

**Issue by XtremePlayzCODE** [webpack/webpack#2749]
I can not use fs with this. Would it be possible to make webpack make/read files from cookies or a localStorage item?

**Comment by ThatTomPerson** [comment]
I haven't tested this but you could probably use `memory-fs` in the browser

**Comment by sokra** [comment]
> Would it be possible to make webpack make/read files from cookies or a localStorage item?

yes, but that makes no sense. The semantics are different.

You can still do this manually via `resolve.alias = { fs: "your-browser-fs" }`

**Comment by XtremePlayzCODE** [comment]
Still have no clue about this, I will try to not use fs in my projects which may be hard but I'll do it.
