### ISSUE TITLE
the bundle has much empty module

### ISSUE THREAD

**Issue by zdying** [webpack/webpack#2751]
the bundle(eg. react.bundle.js) has much empty module.

        /* 176 */,
        /* 177 */,
        /* 178 */,
        /* 179 */,
        /* 180 */,
        /* 181 */,
        /* 182 */,
        /* 183 */,
        ......

**Comment by bebraw** [comment]
Can you provide some sort of test case (sample project)? It's hard to say anything concrete without.

**Comment by zdying** [comment]
@bebraw you can see: [https://github.com/webpack/webpack/tree/master/examples/multiple-commons-chunks#jscommonsjs](url)

it contains: 

     /* 1 */,
     /* 2 */,
     /* 3 */,

**Comment by Kovensky** [comment]
That's a side effect of CommonsChunkPlugin. The modules that are empty are loaded by other files; for example, the skipped `/* 2 */` is loaded by `pageA.js`.

**Comment by sokra** [comment]
It's an optimization:

If a chunk contains the modules 3, 4, 6 it would emit them as:

``` js
{3:xxx,4:xxx,6:xxx}
```

where xxx is a function containing the module.

But webpack has an optimization which emits the modules as array, which results in this:

``` js
[,,,xxx,xxx,,xxx]
```

You may notice that this is shorter in many cases.

This looks like there are empty modules, but this isn't the case. These module ids are just not in this chunk.
