### ISSUE TITLE
webpack --watch doesn't work with parenthesis in the project path

### ISSUE THREAD

**Issue by bradleyjames** [webpack/webpack#2753]
I would never in my right mind add parenthesis to a path name (i.e. "(" or ")").  Unfortunately Dropbox does this when you have a personal account and company account on the same machine.  I store my personal projects in "~/Dropbox (Personal)".  I've been trying for a while to figure out why I couldn't get react hot reloading to work and the parenthesis in the project path seem to cause watch to not notice file change.  To reproduce run the [webpack tutorial](https://webpack.github.io/docs/tutorials/getting-started/) from a directory with parenthesis in its name.

**Webpack version:**
1.13.1

**Please tell us about your environment:**
OSX 10.11.5

**Current behavior:**
webpack --watch will not notice changes in files and thus will not recompile or update the UI.

**Expected/desired behavior:**
Webpack worked just like it does with a path without parenthesis in the name.
- **What is the motivation / use case for changing the behavior?**
  Dropbox folder naming suckage.

**Comment by satrong** [comment]
There is also in Windows 10.

**Comment by Kovensky** [comment]
Does `chokidar-cli` work? e.g. `chokidar ~/'Dropbox (Personal)/**/*'` (the single quotes are important, you have pass the `*` themselves to `chokidar-cli`)

**Comment by antialias** [comment]
Pretty sure the issue is with Chokidar: https://github.com/paulmillr/chokidar/issues/344

**Comment by bebraw** [comment]
Moved to https://github.com/webpack/webpack-cli/issues/18.
