### ISSUE TITLE
Webpack 2 --output-filename not being taken into account.

### ISSUE THREAD

**Issue by kentcdodds** [webpack/webpack#2754]
**I'm submitting a bug report**

**Webpack version:**
2.1.0-beta.15

**Please tell us about your environment:**
OSX 10.x

**Current behavior:**
When providing `--output-filename` on the CLI, I get the following error:

```
Error: 'output.filename' is required, either in config file or as --output-filename
```

See [this repo (branch)](https://github.com/kentcdodds/starwars-names/tree/tmp/webpack-2-issue). Specifically [the config](https://github.com/kentcdodds/starwars-names/blob/tmp/webpack-2-issue/webpack.config.babel.js) and [these scripts](https://github.com/kentcdodds/starwars-names/blob/tmp/webpack-2-issue/package.json#L10-L11).

**Expected/desired behavior:**
I expect no error and the proper builds (as it works with 1.x).

I've looked a bit at the relevant webpack code, but I'm unable to determine what to change.

**Comment by lmymoonsky** [comment]
missed the s from your module.exports line?
