### ISSUE TITLE
How to prevent web app being blocked while the external vendor is inaccessible?

### ISSUE THREAD

**Issue by zheeeng** [webpack/webpack#2755]
In my web app, I insert `<script>` tag for importing external vendor:

index.html:
```
<script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=token"></script>
```

Then I told webpack it's a external vendor:

webpack.base.conf.js:
```
externals: {
  "BMap": "BMap"
}
```

It works fine wthen the network is good.

js file:
```
import BMap from 'BMap'
```

But, If the network broken:

In chrome console:
```
Uncaught ReferenceError: BMap is not defined
```
and the whole app stop resolving my app.js. Not only the component which use the `BMap` is not resolved, the Whole app is blocked by the import statement.

What is the best practice for this situation?

**Comment by psimyn** [comment]
it would depend how you want to handle BMap not being available. You could move the import statement to a (global) function, then call that in the `onload` of map.baidu script - that way you wouldn't need to include map script first and could make it async/defer.

Anywhere that you are going to use BMap in your code you'd need to check that it exists.

**Comment by sokra** [comment]
``` js
externals: {
  "BMap": "typeof BMap !== 'undefined' ? undefined : BMap"
}
```

and check if it's undefined when using
