### ISSUE TITLE
Uncaught ReferenceError: _createRoute is not defined

### ISSUE THREAD

**Issue by crapthings** [webpack/webpack#2756]
* **I'm submitting a bug report**

    Uncaught ReferenceError: _createRoute is not defined

* **Webpack version:**

1.13.1

* **Please tell us about your environment:**

OSX 10.11.5

* **Current behavior:**

webpack anonymous function undefined

* **Expected/desired behavior:**

it should work, but its not.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.** 

        git clone https://github.com/crapthings/webpack-choo-undefined

        npm i

        npm run dev

* **What is the expected behavior?**

the page should display a input box and you can see what you're typing.

* **What is the motivation / use case for changing the behavior?**

its just normal require a popular lib, but no working
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [ ES6/7 | ES5 ]

**Comment by crapthings** [comment]
node env

tested node 4.4.5 4.4.6, 6.3.0
npm 2 / 3

my config

    var path = require('path')

    var webpack = require('webpack')

    var autoprefixer = require('autoprefixer')
    var postcssShort = require('postcss-short')

    var StylusNibPlugin = require('nib')

    var ExtractTextPlugin = require("extract-text-webpack-plugin")

    var HtmlWebpackPlugin = require('html-webpack-plugin')

    module.exports = {
      devtool: 'cheap-eval-source-map',

      entry: [
        'webpack-dev-server/client?http://localhost:8080',
        'webpack/hot/dev-server',
        './src/loader'
      ],

      output: {
        path: path.join(__dirname, 'dist'),
        filename: 'bundle.js'
      },

      module: {
        loaders: [{
          test: /\.js$/,
          loader: 'babel-loader',
          include: path.join(__dirname, 'src')
        }, {
          test: /\.coffee$/,
          loader: "coffee-loader"
        }, {
          test: /\.(coffee\.md|litcoffee)$/,
          loader: "coffee-loader?literate"
        }, {
          test: /\.(css|styl)$/,
          // loader: 'style-loader!css-loader!postcss-loader!stylus-loader',
          loader: ExtractTextPlugin.extract(['css-loader', 'postcss-loader', 'stylus-loader'])
        }, {
          test: /\.hbs$/,
          loader: 'handlebars-loader'
        }, {
          test: /\.html$/,
          loader: 'raw-loader'
        }]
      },

      postcss: function () {
        return [autoprefixer, postcssShort]
      },

      stylus: {
        use: [StylusNibPlugin()],
        import: ['~nib/lib/nib/index.styl']
      },

      resolve: {
        extensions: ['', '.js', '.coffee', '.styl', '.css', '.html'],
        root: [
          path.join(__dirname, 'src')
        ]
      },

      plugins: [
        new webpack.HotModuleReplacementPlugin(),

        new ExtractTextPlugin('bundle.css'),

        new HtmlWebpackPlugin({
          title: 'webpack choo',
          template: './src/index.hbs'
        })
      ],

      devServer: {
        contentBase: './dist',
        hot: true
      }
    }

my package.json

    {
      "name": "webpack-choo-testfield",
      "version": "1.0.0",
      "description": "",
      "main": "./src/loader.js",
      "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1",
        "dev": "webpack-dev-server"
      },
      "author": "",
      "license": "ISC",
      "devDependencies": {
        "autoprefixer": "^6.3.7",
        "babel-core": "^6.10.4",
        "babel-loader": "^6.2.4",
        "babel-plugin-transform-runtime": "^6.9.0",
        "babel-polyfill": "^6.9.1",
        "babel-preset-es2015": "^6.9.0",
        "babel-preset-stage-0": "^6.5.0",
        "coffee-loader": "^0.7.2",
        "coffee-script": "^1.10.0",
        "css-loader": "^0.23.1",
        "extract-text-webpack-plugin": "^1.0.1",
        "handlebars": "^4.0.5",
        "handlebars-loader": "^1.3.0",
        "html-webpack-plugin": "^2.22.0",
        "nib": "^1.1.0",
        "postcss-loader": "^0.9.1",
        "postcss-short": "^1.4.0",
        "raw-loader": "^0.5.1",
        "style-loader": "^0.13.1",
        "stylus": "^0.54.5",
        "stylus-loader": "^2.1.1",
        "webpack": "^1.13.1",
        "webpack-dev-server": "^1.14.1"
      },
      "dependencies": {
        "babel-runtime": "^6.9.2",
        "choo": "^3.0.2",
        "faker": "^3.1.0",
        "lodash": "^4.13.1",
        "moment": "^2.14.1"
      }
    }

**Comment by crapthings** [comment]
https://github.com/yoshuawuyts/choo/issues/157#issuecomment-231998771

> FWIW, I had a issue running choo with webpack when the devtool was set to eval. I changed it to source-map and things started working fine.

**Comment by sokra** [comment]
Please provide more details how this relates to webpack. Test other browsers too (could be the chrome bug).

**Comment by crapthings** [comment]
i've change eval-cheap to source-map, it works.

    devtool: 'source-map',
