### ISSUE TITLE
cannot load css on demand in one single entry

### ISSUE THREAD

**Issue by edwardfhsiao** [webpack/webpack#2760]
for maintaining purpose, I have merged several entries into one single entry, and I am using `require.ensure([], function(require) {})` to include my js and css file on demand, which looks like:

``` javascript
// common.js
if($('#is_a_page').length) {
 require.ensure(['a.js', 'a.css'], function(require) {
      require('a.js');
      require('a.css');
    });
}
else if($('#is_b_page').length) {
 require.ensure(['b.js', 'b.css'], function(require) {
      require('b.js');
      require('b.css');
    });
}


// a.js
alert('its page A');

// b.js
alert("its page B");
```

``` css
/*a.css*/
body{
  backgroung: #fff;
}

/*b.css*/
body{
  backgroung: #000!important;
}
```

then on both of page A and page B, I require the common.js and common.css

now, when I visit page A, it alerts "its page A" as expect, and "its page B" alerts on page B as well,
everything is perfectly fine, HOWEVER, on both page A and page B, the body's background turns to #000, it seems "require.ensure" only works on separating JS file whereas there is no way to separate two css files. Is that correct? any suggestions?

**Comment by ecmadao** [comment]
same problem

**Comment by Kovensky** [comment]
Sounds like something ExtractTextWebpackPlugin would do

**Comment by edwardfhsiao** [comment]
@Kovensky 
thx!
 new ExtractTextPlugin('[name]_bundle.css', {
    allChunks: false
  }),
solved my prolem

**Comment by edwardfhsiao** [comment]
but once I set it as false, some css turned inline in the head, that is not what I expected

**Comment by sokra** [comment]
This is an old issue. I guess the problem was solved in the meantime. If not please open a new issue.
