### ISSUE TITLE
CSS file mix with LESS files into a single bundle gets ignored

### ISSUE THREAD

**Issue by jorgecas99** [webpack/webpack#2761]
**I'm submitting a bug report**

**Webpack version:**
1.10.x/2.x

**Please tell us about your environment:**
OSX 10.10.x

**Current behavior:**
When generating a single bundle.css made when LESS and compiled CSS, the CSS files get ignored and not included into the bundle.css.
Am using extractplugin to generated the bundle css, and css!less loaders to read the Less files and compile them.

**Expected/desired behavior:**
Webpack should grab all require files and included them into bundle.css, when it sees the CSS file it should be smart enough to know that no compiling is needed only aggregation.
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.** 

create a file and called it whatever. i.e. main.js with the following content:

require('./css/bootstrap/bootstrap.less');
require('./css/bootstrap-material/dist/bootstrap-material-design.css'); //this file gets ignore by webpack
require('./css/bootstrap-material/ripples.less');

Create a a css folder and add bootstrap Less files.
Create webpack.config file that uses extractPlugin.
Create a index.html that loads bundle.css
- **What is the expected behavior?**
  webpack should read and pull content of each require line in main.js, if the file getting pulled happens to be a file with .css extension it should ignore the compiling but still include the file onto the bundle.
- **What is the motivation / use case for changing the behavior?**
  All CSS files, whether precompile or compiled should be included in output file. Error message or info message should also be provided in the terminal if for some reason a file gets excluded by webpack.
- **Browser:** [Chrome XX  ] 
  Chrome xx
- **Language:** [ ES5] 
  ES5

**Comment by sokra** [comment]
Have you applied the ExtractTextPlugin to the css loader too?

**Comment by bebraw** [comment]
@jorgecas99 Any update?
