### ISSUE TITLE
Add a comma after "loaders" in the GitHub project description

### ISSUE THREAD

**Issue by McBrainy** [webpack/webpack#2765]
The current description contains the text:

> Through "loaders" modules can be CommonJs, AMD, ES6 modules, CSS, Images, JSON, Coffeescript, LESS, ... and your custom stuff.

Nitpicky, maybe, but I had to read the first part of that sentence several times before I understood what it was trying to say. It would read far better as:

> Through "loaders," modules can be...

**Comment by sokra** [comment]
done
