### ISSUE TITLE
Not work sourcemap with uglify [webpack 2]

### ISSUE THREAD

**Issue by arshtepe** [webpack/webpack#2766]
**I'm submitting a bug report**

**Webpack version:**
 2.1.0-beta.17

**Please tell us about your environment:**
 Linux 

config

``` js

module.exports =  {
    devtool: "cheap-source-map",
    debug: !isProduction,
    output: {
        filename: "[name].js",
        pathinfo: !isProduction
    },
    module: {
        loaders: loaders
    },
    loaders: [
        {
            loader: 'babel',
            test: /\.js$/
        }
    ],
    plugins: [
        new webpack.optimize.UglifyJsPlugin({
            sourceMap: true,
            compress: {
                sequences: true,
                properties: true,
                drop_debugger: true,
                dead_code: true,
                conditionals: true,
                booleans: true,
                unused: true,
                if_return: true,
                join_vars: true,
                drop_console: true,
                warnings: !isProduction
            }
        })

    ],
    resolve: {
        descriptionFiles: ["bower.json"],
        mainFields: ["main"],
        extensions: [".js"],
        alias: { },
        modules: [
            "bower_components",
            "node_modules"
        ]
    }
};

```

source map file

``` json
{"version":3,"file":"customersHistory.js","sources":["webpack:///customersHistory.js"],"mappings":"AAAA","sourceRoot":""}
```
- **Language:**  ES6/7

**Comment by jiaweihli** [comment]
The same problem happens in webpack 1.x too.
Uglifyjs doesn't produce correct sourcemaps right now.

**Comment by AceLeeWinnie** [comment]
Uglifyjs doesn't work in webpack 1.12.14 and 1.13 now. And the error prompt reveal the error in css-loader but it's wrong.
`ERROR in ./~/css-loader!./src/com/model/leg/models/Model.css`
`Module build failed: Error: Expected opening square bracket.`

**Comment by egoist** [comment]
I have a similar issue like this, webpack 2.0.0-beta.22 isn't generating source-map after adding `new webpack.optimize.UglifyJsPlugin`

**Comment by AceLeeWinnie** [comment]
Webpack can generate source-map again by getting rid of the minify feature in css-loader:
```
{
  test: /\.css$/,
  loader: 'style!css?-minimize'
} 
```
Because the Uglifyjs will minify the files already minified by css-loader
### reference:
1. https://github.com/webpack/webpack/issues/2752
