### ISSUE TITLE
Error: Chunk.initial was removed. Use isInitial() in BannerPlugin

### ISSUE THREAD

**Issue by thuringia** [webpack/webpack#2767]
**I'm submitting a bug report**

**Webpack version:**
2.1.0-beta.{16,17}

**Please tell us about your environment:**
OSX 10.10, 10.11 / Linux 

**Current behavior:**
BannerPlugin causes build failure.

**Expected/desired behavior:**
BannerPlugin should not fail due to API change.

There is already a similar issue for ExtractTextPlugin (#2764), not sure if these should be merged or not. Currently I have reverted to beta.15 which is the last version where both plugins work.

Thanks for all the hard work, it's very appreciated.

**Comment by sokra** [comment]
fixed
