### ISSUE TITLE
SourceMapDevToolPlugin not outputting full sourcemap during Hot Module Replacement

### ISSUE THREAD

**Issue by baseten** [webpack/webpack#2768]
**I'm submitting a bug report**

**Webpack version:**
1.13.1

**Please tell us about your environment:**
OSX 10.11.3

**Current behavior:**
When using WebpackDevServer with HMR enabled and the SourceMapDevToolPlugin with the following options:

```
{
	test: /\.(js|jsx|css)($|\?)/i,
	filename: 'bundle.js.map',
	noSources: true,
	moduleFilenameTemplate: 'file://[absolute-resource-path]'
	fallbackModuleFilenameTemplate: 'file://[absolute-resource-path]?[hash]'
}
```
After changing a source file, the newly generated sourcemap only contains mappings for the file that changed and nothing else. I initially thought it may be related to [this issue](https://github.com/webpack/webpack/issues/2478) but even after doing a hard refresh the sourcemap remains the same. If using the `devtool: 'sourcemap'` option then everything works as expected.

**Expected/desired behavior:**
A new sourcemap should be generated for all source files.

**Comment by sokra** [comment]
remove the `filename` property.
