### ISSUE TITLE
ES6 import causes missing dependency errors on NPM 2.x

### ISSUE THREAD

**Issue by kumar303** [webpack/webpack#2769]
**I'm submitting a bug report**

**Webpack version:**
1.13.1

Babel: 6.10.4
NPM: 2.x (only)

**Please tell us about your environment:**
OSX 10.10.5 (also happens on Linux and Windows)

**Current behavior:**

When installing with NPM 2.x (only) and building a common JS module, this import statement causes missing dependency errors:

```
import fs from "mz/fs";
```

If you change it to

```
import {fs} from "mz";
```

then all errors go away.

**Expected/desired behavior:**

It should work without any missing dependency errors.

Here's how to reproduce it with [webpack-mz-fs.zip](https://github.com/webpack/webpack/files/364358/webpack-mz-fs.zip):
- unzip the code and cd in
- make sure you're using npm 2.x
- npm install
- npm run build

**What is the expected behavior?**

It should build without errors. The error log you get on NPM 2.x is massive ([webpack-mz-fs-npm2.txt](https://github.com/webpack/webpack/files/364360/webpack-mz-fs-npm2.txt)) but starts with this error:

```
Module not found: Error: Cannot resolve module 'bluebird' in /Users/kumar/tmp/webpack-mz-fs/node_modules/mz/node_modules/any-promise/register
 @ ./~/mz/~/any-promise/register/bluebird.js 2:45-64
```

There are many other missing module errors like this.

You can edit `index.js` to change the import statement and see the workaround.

**What is the motivation / use case for changing the behavior?**

Webpack should support NPM 2.x because it's still the default on a lot of systems. NPM can be hard to upgrade, especially on Windows. This bug has made it very challenging to distribute a Node package to a wide audience.

**Browser:** N/A (only applies to NodeJS)

**Language:** [ES6/7] 

Babel says it's not their fault: https://phabricator.babeljs.io/T7491

**Comment by kumar303** [comment]
This may be widespread. I just caught another instance of it triggered by this import:

    import defaultFxRunner from 'fx-runner/lib/run';

Again, the workaround was:

    import {defaultFxRunner} from 'fx-runner';

**Comment by bebraw** [comment]
Can you try `import * as fs from "mz/fs";`. Are you using `default` exports?

**Comment by kumar303** [comment]
I tried this in the example project I uploaded. It makes no difference, the errors remain the same. The key difference in the statement `import {fs} from "mz"`, which works without error, is that it will parse `fs/index.js` (I think).

**Comment by kumar303** [comment]
> Are you using default exports?

I'm not sure what you mean by this. The module that causes the problem is [mz](https://github.com/normalize/mz) (an external dependency) but, as I posted above, this seems to happen for any object that is imported from a submodule path -- it's not just the `mz` module. When I look at `mz`, it declares all the right dependencies in its `package.json` so I don't think it is at fault.
