### ISSUE TITLE
Top-Level import will not be transpiled

### ISSUE THREAD

**Issue by antonkluev** [webpack/webpack#2770]
I have a bug as i try to import a lib from a top level. If i include a file, that is in the same directory, it will be transpiled. But if it is a lib from a top level, it will be ignored by babel and injected into a bundle, just as it is - raw. Here is my setup: 
[test.zip](https://github.com/webpack/webpack/files/364867/test.zip)

Maybe is something wrong with my setup?

**Comment by antonkluev** [comment]
Maybe its not just a question, but a bug? Just look on my setup, please

**Comment by sokra** [comment]
`resolve.modules` should contain an absolute path instead of a relative one. Maybe that's the issue.

**Comment by antonkluev** [comment]
Pardon, my friends, it was my issue. I should use the export function correctly. You can close this question and thank you very much for your support!
