### ISSUE TITLE
Module not found: Error: Cannot resolve 'file' or 'directory' (import sass with a relative font folder  in webpack)

### ISSUE THREAD

**Issue by eromoe** [webpack/webpack#2771]
My project structure is:
[![enter image description here](http://i.stack.imgur.com/OMagK.png)](http://i.stack.imgur.com/OMagK.png)

/src/styles/main.scss  

```
@import 'materialize/sass/materialize.scss';

....
```

I also try `@import './materialize/sass/materialize.scss';` here
notwork.

It only work when I import the lib in index.js

/src/index.js (this worked)

```
import './styles/reset.css';
import './styles/main.scss';
import './styles/font-awesome/font-awesome.scss';
```

webpack loader:

```
loaders: [
  {
    test: /\.js?/,
    exclude: [/node_modules/, /styles/],
    loaders: ['babel'],
    include: path.join(__dirname, 'src')
  },
  {
    test: /\.scss$/,
    loader: 'style!css!sass'
  },
  {
    test: /\.css$/,
    loader: "style-loader!css-loader"
  },
  {
    test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/,
    loader: 'url-loader?limit=10000&mimetype=application/font-woff'
  },
  {
    test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
    loader: 'file-loader'
  }
```

]

But got error:

```
ERROR in ./~/css-loader!./~/sass-loader!./src/styles/main.scss
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/roboto/Roboto-Thin.eot in E:\Project\simple-redux
-boilerplate\src\styles
 @ ./~/css-loader!./~/sass-loader!./src/styles/main.scss 6:73945-73987 6:74010-74052

ERROR in ./~/css-loader!./~/sass-loader!./src/styles/main.scss
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/roboto/Roboto-Thin.woff2 in E:\Project\simple-red
ux-boilerplate\src\styles
 @ ./~/css-loader!./~/sass-loader!./src/styles/main.scss 6:74104-74148

ERROR in ./~/css-loader!./~/sass-loader!./src/styles/main.scss
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/roboto/Roboto-Thin.woff in E:\Project\simple-redu
x-boilerplate\src\styles
 @ ./~/css-loader!./~/sass-loader!./src/styles/main.scss 6:74181-74224

ERROR in ./~/css-loader!./~/sass-loader!./src/styles/main.scss
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/roboto/Roboto-Thin.ttf in E:\Project\simple-redux
-boilerplate\src\styles
 @ ./~/css-loader!./~/sass-loader!./src/styles/main.scss 6:74256-74298

ERROR in ./~/css-loader!./~/sass-loader!./src/styles/main.scss
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/roboto/Roboto-Light.eot in E:\Project\simple-redu
x-boilerplate\src\styles
 @ ./~/css-loader!./~/sass-loader!./src/styles/main.scss 6:74430-74473 6:74496-74539

ERROR in ./~/css-loader!./~/sass-loader!./src/styles/main.scss
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/roboto/Roboto-Light.woff2 in E:\Project\simple-re
dux-boilerplate\src\styles
 @ ./~/css-loader!./~/sass-loader!./src/styles/main.scss 6:74591-74636

ERROR in ./~/css-loader!./~/sass-loader!./src/styles/main.scss
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/roboto/Roboto-Light.woff in E:\Project\simple-red
ux-boilerplate\src\styles
 @ ./~/css-loader!./~/sass-loader!./src/styles/main.scss 6:74669-74713

ERROR in ./~/css-loader!./~/sass-loader!./src/styles/main.scss
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/roboto/Roboto-Light.ttf in E:\Project\simple-redu
x-boilerplate\src\styles
 @ ./~/css-loader!./~/sass-loader!./src/styles/main.scss 6:74745-74788

ERROR in ./~/css-loader!./~/sass-loader!./src/styles/main.scss
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/roboto/Roboto-Regular.eot in E:\Project\simple-re
dux-boilerplate\src\styles
 @ ./~/css-loader!./~/sass-loader!./src/styles/main.scss 6:74922-74967 6:74990-75035

ERROR in ./~/css-loader!./~/sass-loader!./src/styles/main.scss
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/roboto/Roboto-Regular.woff2 in E:\Project\simple-
redux-boilerplate\src\styles
 @ ./~/css-loader!./~/sass-loader!./src/styles/main.scss 6:75087-75134

ERROR in ./~/css-loader!./~/sass-loader!./src/styles/main.scss
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/roboto/Roboto-Regular.woff in E:\Project\simple-r
edux-boilerplate\src\styles
 @ ./~/css-loader!./~/sass-loader!./src/styles/main.scss 6:75167-75213

ERROR in ./~/css-loader!./~/sass-loader!./src/styles/main.scss
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/roboto/Roboto-Regular.ttf in E:\Project\simple-re
dux-boilerplate\src\styles
 @ ./~/css-loader!./~/sass-loader!./src/styles/main.scss 6:75245-75290

ERROR in ./~/css-loader!./~/sass-loader!./src/styles/main.scss
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/roboto/Roboto-Medium.eot in E:\Project\simple-red
ux-boilerplate\src\styles
 @ ./~/css-loader!./~/sass-loader!./src/styles/main.scss 6:75401-75445 6:75468-75512

ERROR in ./~/css-loader!./~/sass-loader!./src/styles/main.scss
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/roboto/Roboto-Medium.woff2 in E:\Project\simple-r
edux-boilerplate\src\styles
 @ ./~/css-loader!./~/sass-loader!./src/styles/main.scss 6:75564-75610

ERROR in ./~/css-loader!./~/sass-loader!./src/styles/main.scss
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/roboto/Roboto-Medium.woff in E:\Project\simple-re
dux-boilerplate\src\styles
 @ ./~/css-loader!./~/sass-loader!./src/styles/main.scss 6:75643-75688

ERROR in ./~/css-loader!./~/sass-loader!./src/styles/main.scss
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/roboto/Roboto-Medium.ttf in E:\Project\simple-red
ux-boilerplate\src\styles
 @ ./~/css-loader!./~/sass-loader!./src/styles/main.scss 6:75720-75764

ERROR in ./~/css-loader!./~/sass-loader!./src/styles/main.scss
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/roboto/Roboto-Bold.eot in E:\Project\simple-redux
-boilerplate\src\styles
 @ ./~/css-loader!./~/sass-loader!./src/styles/main.scss 6:75875-75917 6:75940-75982

ERROR in ./~/css-loader!./~/sass-loader!./src/styles/main.scss
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/roboto/Roboto-Bold.woff2 in E:\Project\simple-red
ux-boilerplate\src\styles
 @ ./~/css-loader!./~/sass-loader!./src/styles/main.scss 6:76034-76078

ERROR in ./~/css-loader!./~/sass-loader!./src/styles/main.scss
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/roboto/Roboto-Bold.woff in E:\Project\simple-redu
x-boilerplate\src\styles
 @ ./~/css-loader!./~/sass-loader!./src/styles/main.scss 6:76111-76154

ERROR in ./~/css-loader!./~/sass-loader!./src/styles/main.scss
Module not found: Error: Cannot resolve 'file' or 'directory' ../fonts/roboto/Roboto-Bold.ttf in E:\Project\simple-redux
-boilerplate\src\styles
 @ ./~/css-loader!./~/sass-loader!./src/styles/main.scss 6:76186-76228
```

I found there are config in 
`/src/styles/materialize/sass/components/_variables.scss`:

```
$roboto-font-path: "../fonts/roboto/" !default;
```

It looks like `webpack` search for a wrong directory, not search `fonts` folder under `materialize`.

I got error every time when I put import sass lib in `main.scss`, which force me to put `import` to `index.js`.  Webpack should take the responsibility to generate correct absolute path base on imported relative path.

**Comment by rodrigobacelli** [comment]
Just had this problem too. It's an error in finding the right directory. Use the path relative to /.

In my case, instead of using `../../../assets/(...)`, I've changed the path to `/assets/(...)`.

**Comment by eromoe** [comment]
@rodrigobacelli I don't want to edit source file,  this https://www.npmjs.com/package/resolve-url-loader module can solve the problem.

**Comment by Sangd8** [comment]
@eromoe Can you post your webpack config to resolve this issue? I have tried to use resolve-url-loader but it still failed.

**Comment by eromoe** [comment]
I just add `resolve-url` to scss, it works for me.
```
loaders: [
  {
    test: /\.js?/,
    exclude: [/node_modules/, /styles/],
    loaders: ['babel'],
    include: path.join(__dirname, 'src')
  },
  {
    test: /\.scss$/,
    loader: 'style!css!sass!resolve-url!sass?sourceMap'
  },
  {
    test: /\.css$/,
    loader: "style-loader!css-loader"
  },
  {
    test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/,
    loader: 'url-loader?limit=10000&mimetype=application/font-woff'
  },
  {
    test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
    loader: 'file-loader'
  }
```

**Comment by Sangd8** [comment]
Thanks @eromoe it's working now.

**Comment by floviolleau** [comment]
Thanks a lot @eromoe. This comment helps me a lot :+1: :+1: . I was stuck on that problem since 2 days...

**Comment by sjunka** [comment]
Where is the webpack bundle configuration file for Angular Cli "version": "1.0.0-beta.17"??

**Comment by kilroy05** [comment]
@sjunka angular-cli does not have one

**Comment by martinreus** [comment]
@eromoe, @sjunka, do you have any idea how we could configure this with angular-cli?

**Comment by keerthivasan-r** [comment]
@martinreus Were you able to fix it? I have the same problem with angular-cli :worried:

**Comment by martinreus** [comment]
Hi @keerthivasan-r, no, unfortunately I wasn't able to fix the problem.. But I haven't invested much more time in it.. If you find a solution for this problem please let us know!

**Comment by ssijak** [comment]
Still have this problem.

**Comment by jkrnak** [comment]
@ssijak if you are having this issue, make sure that you are generating source map as shown in the example config by @eromoe .
See the docs: https://www.npmjs.com/package/resolve-url-loader#source-maps-required
```
    {
        test   : /\.scss$/,
        loaders: ['style-loader', 'css-loader', 'resolve-url-loader', 'sass-loader?sourceMap']
    }
```

**Comment by xuqinggang** [comment]
you can import css file
ex: @import materialize/css/materialize.css'

**Comment by bhvreddy** [comment]
```
$roboto-font-path: "~materialize-css/dist/fonts/roboto/";
@import "~materialize-css/sass/materialize";
```


 ```
{
                test: /\.(svg|woff|woff2|eot|ttf|otf)$/,
                loader: 'url-loader',
                options: {
                    name: 'fonts/[name].[ext]',
                    limit: 50,
                },
            },
```



its worked for me

**Comment by YannisMarios** [comment]
@bhvreddy 

Did you put 
$roboto-font-path: "~materialize-css/dist/fonts/roboto/";
@import "~materialize-css/sass/materialize";

in your _variables.scss?

**Comment by high-s0ciety** [comment]
@eromoe why do you have sass listed twice in your loader?

`loader: 'style!css!sass!resolve-url!sass?sourceMap'`

**Comment by eromoe** [comment]
@high-s0ciety   I can't remenber. I think, at the time when I posted that comment,  base config was copied from somewhere,  and `resolve-url` document told me add `sass?sourceMap`  to `loader` . Which result to twice sass, fixed now.

**Comment by vgjenks** [comment]
@eromoe Thanks so much! After struggling w/ this for hours, this "just worked". However, I'm no longer able to bundle and minify my .css with the ExtractTextPlugin. Was using it like so:

`			{
				test: /\.s?css$/,
				loader: ExtractTextPlugin.extract(["style-loader", "css-loader"])
			}
`
This had worked fine on my own .css files until I went down the rabbit-hole of putting Bootstrap into the mix.

**Comment by evilebottnawi** [comment]
I close the issue here, because related to `sass-loader` and `resolve-url` (see docs https://github.com/webpack-contrib/sass-loader#problems-with-url). Feel free to open issue in `sass-loader` or `resolve-url`, thanks to everyone.

**Comment by justgeek** [comment]
Without Modifying Webpack File, this works!!

```
$mdi-font-path: '~mdi/fonts/';
@import '~mdi/scss/materialdesignicons';
```

**Comment by AnkitOnclick** [comment]
npm run webpack giving me the following errors:

ERROR in ./~/jest/~/jest-config/build/vendor/jsonlint.js
Module not found: Error: Can't resolve 'file' in 'D:\Projects\HotelApp\hotel-cli
ent\node_modules\jest\node_modules\jest-config\build\vendor'
 @ ./~/jest/~/jest-config/build/vendor/jsonlint.js 730:14-29 730:35-50
 @ ./~/jest/~/jest-config/build/read_config_file_and_set_root_dir.js
 @ ./~/jest/~/jest-config/build/index.js
 @ ./~/jest/~/jest-cli/build/cli/index.js
 @ ./~/jest/~/jest-cli/build/jest.js
 @ ./~/jest/build/jest.js
 @ ./client/util/apiCaller.js
 @ ./client/modules/authorization/authActions.js
 @ ./client/modules/App/App.js
 @ ./client/routes.js
 @ ./client/App.js
 @ ./client/index.js

ERROR in ./~/jest-leak-detector/build/index.js
Module not found: Error: Can't resolve 'v8' in 'D:\Projects\HotelApp\hotel-clien
t\node_modules\jest-leak-detector\build'
 @ ./~/jest-leak-detector/build/index.js 13:55-68
 @ ./~/jest/~/jest-runner/build/run_test.js
 @ ./~/jest/~/jest-runner/build/index.js
 @ ./~/jest/~/jest-cli/build/test_scheduler.js
 @ ./~/jest/~/jest-cli/build/jest.js
 @ ./~/jest/build/jest.js
 @ ./client/util/apiCaller.js
 @ ./client/modules/authorization/authActions.js
 @ ./client/modules/App/App.js
 @ ./client/routes.js
 @ ./client/App.js
 @ ./client/index.js

ERROR in ./~/babel-core/lib/api/node.js
Module not found: Error: Can't resolve '../../package' in 'D:\Projects\HotelApp\
hotel-client\node_modules\babel-core\lib\api'
 @ ./~/babel-core/lib/api/node.js 60:15-39
 @ ./~/babel-core/index.js
 @ ./~/jest/~/jest-runtime/build/script_transformer.js
 @ ./~/jest/~/jest-runtime/build/index.js
 @ ./~/jest/~/jest-cli/build/cli/index.js
 @ ./~/jest/~/jest-cli/build/jest.js
 @ ./~/jest/build/jest.js
 @ ./client/util/apiCaller.js
 @ ./client/modules/authorization/authActions.js
 @ ./client/modules/App/App.js
 @ ./client/routes.js
 @ ./client/App.js
 @ ./client/index.js
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! mern-starter@2.0.0 webpack: `webpack`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the mern-starter@2.0.0 webpack script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\OCI\AppData\Roaming\npm-cache\_logs\2018-02-12T13_37_22_02
3Z-debug.log
------------------------------------------------------------------------------------------------------------------

var path = require('path')
var webpack = require('webpack')
var fs = require('fs')
var MenifestPlugin = require('webpack-manifest-plugin')
var console = require('console') 
module.exports = {
  entry: './client/index.js',
  output: {
      path: path.join(__dirname, 'dist'),
      filename: 'bundle.js',
      // publicPath: '/public/'
  },
  resolve: {
    extensions: ['*', '.js', '.jsx'],
    modules: [
      'client',
      'node_modules',
    ],
  },
  node: {
    fs: "empty",
    net:"empty",
    tls:"empty",
    dns:"empty",
    child_process: "empty",
    console:"empty",
    module:"empty",
    global: true,
    process: true,
    __filename: "mock",
    __dirname: "mock",
    Buffer: true,
    setImmediate: true
},
  module: {
    loaders: [{
      test: /\.(js|jsx)$/,
      exclude: /node_modules/,
      loader: 'babel-loader'
    },
    {
      test: /\.scss$/,
      loader: 'style!css!resolve-url!sass?sourceMap'
    },
    {
      test: /\.css$/,
      loaders: ['style-loader', 'css-loader']
    },
    {
      test: /\.(gif|png|jpe?g|svg)$/i,
      loaders: ['file-loader?hash=sha512&digest=hex&name=[hash].[ext]','image-webpack-loader']
    },
    {
      test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
      loader: 'file-loader'
    },
    {
      test: /\.json/,
      loader: 'json-loader'
    },
    ]
  },
};

**Comment by syedhaffiz7** [comment]
it is addressed in this [issue](https://github.com/angular/angular-cli/issues/4778).

CSS URL handling was changed. To replicate the behavior prior to beta.32, use a root relative URL (i.e., add a / to the beginning of each URL).

Thanks to [clydin](https://github.com/clydin)

**Comment by MIsmail80** [comment]
Thanks @syedhaffiz7 , work like a charm

**Comment by raphael-souza** [comment]
My problem was similar. I just fixed the reference in the configuration file:

> const webpack = require('webpack')

module.exports =
{
    entry: './ex/index.js',
    output: 
    {
        path: __dirname + '/public',
        filename: './bundle.js'
    },
    devserver:
    {
        port: 8080,
        contentBase: './public'
    }
}

**Comment by TomaszWaszczyk** [comment]
Does anyone has issue with `material-table` and `jsPDF`?
