### ISSUE TITLE
resolveLoader.alias should allow mapping to multiple loaders at once

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack#2772]
**I'm submitting a feature request**

**Webpack version:**
1.10.x/2.x

**Please tell us about your environment:**
OSX 10.x / Linux / Windows 10

**Current behavior:**

Currently you can set up a resolve loader alias like this:

``` javascript
resolveLoader: {
  alias: {
    catalog: 'catalog/lib/loader'
  }
}
```

This is great if you need to map `txt` to `raw` and so on. Useful with RequireJS.

**Expected/desired behavior:**

It would be better if the idea could be expanded to support loader chains like this:

``` javascript
resolveLoader: {
  alias: {
    catalog: ['catalog/lib/loader', 'raw']
  }
}
```
- **What is the motivation / use case for changing the behavior?**

This would allow to you to alias complicated loader chains to something simpler.

**Comment by akwuh** [comment]
@bebraw why not doing
```javascript
resolveLoader: {
  alias: {
    catalog: 'catalog/lib/loader!raw!whatever-loader'
  }
}
```
?

**Comment by bebraw** [comment]
@akwuh Makes sense. I guess ideally this should support the loader protocol (`resolve.loaders`) whatever that happens to be.

**Comment by sokra** [comment]
The resolving doesn't know about loaders. It always returns a single result. Could be difficult...

**Comment by bertho-zero** [comment]
:ear:

**Comment by astraldragon** [comment]
Yeah, I was hoping it would do this as well.  The simple use case I have is we use requireCSS and I'd like to write an alias that would use css and style loader.  Not sure if there's a way I could handle that in another way? (without having to write my own loader)

**Comment by korya** [comment]
This is a great feature that we are missing right now. A single loader it is pretty useless. What makes webpack a powerful tool is the ability to define pipelines of loaders. So IMHO it is very important to be able to define your loader pipelines once in a config file, name them and reuse them later anywhere in the project.

Our use case is pretty simple as well:
 - some assets have to be always bundled by default within its chunk;
 - some assets have to be always bundled separately and loaded lazily from the app;
 - all the rest are bundled according to a default configuration.

**Comment by wuservices** [comment]
Without this feature implemented, does that mean that it would be impossible for `css!*` to invoke multiple loaders?

If anybody could help me on SO, I'm also trying to migrate from RequireJS and trying to figure out the right way to migrate plugins.
https://stackoverflow.com/questions/52175315/in-webpack-how-do-i-map-require-js-css-plugin-syntax-to-use-less-module-rules

**Comment by astraldragon** [comment]
One thing I did to work around it was I aliased css to noop-loader and I wrote my resolvers like I would in a normal project.

```js
{
{
    ...
    module: {
        rules: [{
            test: /\.css$/,
            use: ['style-loader', 'css-loader']
        }
    },
    resolveLoader: {
        alias: {
            'css': 'noop-loader'
        }
    },
    ...
}
```

**Comment by vankop** [comment]
Should work with `webpack@next`. Feel free to report new issue with reproducible repo.
