### ISSUE TITLE
webpack sourceMap Issue

### ISSUE THREAD

**Issue by synchronizingtheworld** [webpack/webpack#2774]
issues url: https://jsfiddle.net/hehui/4a1kuLbo/6/

github url: https://github.com/synchronizingtheworld/testWebpackSourceMap

**Comment by bebraw** [comment]
Can you provide more details in English?

**Comment by synchronizingtheworld** [comment]
issues url: https://jsfiddle.net/hehui/4a1kuLbo/3/

/ *
= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
This is a show webpack sourceMap code can appear problem.
The embodiment of the way: page shows or js effect has a problem
The location of the problem: page < div class = "mui - the slider" > < / div >
Problem: the framework of https://github.com/dcloudio/mui
= = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
* /

**Comment by sokra** [comment]
This is not english..
