### ISSUE TITLE
Plugins can cause duplicate entries in records files

### ISSUE THREAD

**Issue by ojacobson** [webpack/webpack#2777]
**Webpack version:** 1.13.0

**Please tell us about your environment:** Mac OS 10.11.mumble, Node v6.2.2

**Current behavior:**

When running `webpack` (`npm run webpack`) in [this project](https://github.com/ojacobson/webpack-records-bloat), Webpack adds new entries to `webpack-records.json`, even though there are no code changes. Every run adds new records, causing the file to grow without bound.

Example diff:

``` diff
diff --git a/webpack-records.json b/webpack-records.json
index da2c839..05569d8 100644
--- a/webpack-records.json
+++ b/webpack-records.json
@@ -13,6 +13,20 @@
         "byName": {},
         "byBlocks": {}
       }
+    },
+    {
+      "nextFreeModuleId": 2,
+      "modules": {
+        "byIdentifier": {
+          "node_modules/css-loader/index.js?sourceMap!src/app.css": 0,
+          "node_modules/css-loader/lib/css-base.js": 1
+        }
+      },
+      "nextFreeChunkId": 1,
+      "chunks": {
+        "byName": {},
+        "byBlocks": {}
+      }
     }
   ],
   "nextFreeModuleId": 4,
```

(The added records are identical to records already present in the file.)

The duplicate records appear in the section associated with the `ExtractTextPlugin`, but I've been able to reproduce this with other plugins, as well (including `HtmlPlugin`).

**Expected/desired behavior:**
- Records files change only when modules are added to or removed from the bundle.
- Duplicate sections do not appear in records files.

**Comment by TheLarkInn** [comment]
Would you mind checking this in webpack@2?

**Comment by Kovensky** [comment]
This might be a problem with extract-text-webpack-plugin (or with child compiler handling), or at least I encountered a similar issue a few months ago with `webpack@2.1.0-beta.21` + `extract-text-webpack-plugin@2.1.0-beta.3`.

On every build that used the `recordsPath`, the `"extract-text-webpack-plugin"` array in the JSON would be appended with a new modules/chunks object.

This was a "disposable" project so I didn't pay it much mind, and I periodically delete the records anyway to re-optimize the chunk IDs.

**Comment by kisenka** [comment]
@sokra does it mean that child compilation produce right HMR update files?
