### ISSUE TITLE
[Webpack 2] Handling `System.import()` invalid chunk errors

### ISSUE THREAD

**Issue by umidbekkarimov** [webpack/webpack#2781]
Throw with some `InvalidChunkError` class so we can handle it like

```javascript
System.import('./Component.js').catch(e => {
    if (e instanceof InvalidChunkError) {
        // chunk load error
    } else {
        console.error(e); // any other error inside chunk
    } 
})

```

**Comment by sokra** [comment]
What does the spec say? Which error should be thrown by spec?

**Comment by kevinSuttle** [comment]
When I tried this before, I got: `Cannot read property 'match' of undefined`

**Comment by umidbekkarimov** [comment]
@sokra I found nothing according to the spec,

But I think that as soon as implementation will start we will have some new error in this [list](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error)

But for now, we need to split `chunk not found` error (if trying to load chunk from previous build)

And `syntax` or `runtime` thrown errors during loading chunk

Error type, some flag in error object (like `e.chunkNotFound === true`)

Currently i'm checking it like that

```javascript
 if (process.env.NODE_ENV === 'production') {
            window.location.reload(true)
        } else {
            console.error(e)
        }

**Comment by sokra** [comment]
We can revisit the error type once the spec specifies some

**Comment by matt-mcdaniel** [comment]
@umidbekkarimov that's a good solution, but in (albeit rare) cases where a chunk may be missing, are you doing anything to ensure that the browser doesn't reload indefinitely?

**Comment by umidbekkarimov** [comment]
I guess it would be problem with static file server, that can't serve required chunk, or webpack itself (but I guess it's too stable now) 
Bu It just never happened with me :) i'm logging this error in sentry and it occurres just once per user after updates.

Also I reduced number of chunks to decrease occupancy of these kind of errors.

IMGO Gziped chunks that smaller than 100kb doesn't help much to increase initial load and can be merged, or loaded with small delay - so navigation between pages will be smooth.

**Comment by sokra** [comment]
> it occurres just once per user after updates.

Don't remove the old assets (chunks) on update. A user can have the page open (even for a long time)...
