### ISSUE TITLE
WebpackJsonp is missing when running webpack twice with gulp

### ISSUE THREAD

**Issue by Niondir** [webpack/webpack#2787]
**I'm submitting a bug report**
**Webpack version:**
1.12.14

**Please tell us about your environment:**
Windows 7/10

**Current behavior:**
WebpackJsonp is missing in vendor.bundle.js

Checkout: https://github.com/Niondir/iot-dashboard/commit/f9053e2c844644ba08a0f512fe511d6507a37aff
Run: `npm run gulp webpack`

The task runs `webpack:client` and `webpack:tests` in parallel, but I also tested with gulp-sequence and observed the same issue.

Open `dist/vendor.bundle.js` - no webpackJsonp definition is included.

To verify that separate builds do not break anything:

Run: `npm run gulp webpack:client`
Open `dist/vendor.bundle.js` - webpackJsonp  is defined
Run: `npm run gulp webpack:tests`
Open `dist/vendor.bundle.js` - webpackJsonp  is defined

**Expected/desired behavior:**
I would expect a webpackJsonp definition when running `npm run gulp webpack`

* **What is the motivation / use case for changing the behavior?**
Webpack generated code is broken in a normal usecase
 
* **Browser:** all 
 
* **Language:** all

**Comment by Niondir** [comment]
Any progress here?

I found that webapck is "re-using" some plugins defined in another config that ran before.

**Comment by Niondir** [comment]
It's an issue with my require in the webpack config ...

**Comment by mrlucks** [comment]
@Niondir Can you explain how you fixed it?
