### ISSUE TITLE
webpack-dev-server and HMR

### ISSUE THREAD

**Issue by Thstone37** [webpack/webpack#2792]
when I use webpack-dev-server and HMR,
my config.js:

>    devServer:{
>     	historyApiFallback:true,
>     	hot:true,
>     	inline:true,
>     	progress:true,
>     }

> plugins: [
>         new webpack.HotModuleReplacementPlugin()
>     ]

I use **Command line mode,**such as 

> webpack-dev-server --inline --hot

,when change ths less file,Command line tell me something has changed,but the page do not show the change,I want to know,which reason cause it;

**Comment by bebraw** [comment]
Please note that `webpack-dev-server --inline --hot` injects`new webpack.HotModuleReplacementPlugin()` so you probably have it twice in your configuration now.

**Comment by Thstone37** [comment]
I figure out it the command line tell me,this change has exsit in memory,but the output js file doesn't change,when I add publicPath to the output options,It can work

**Comment by d3viant0ne** [comment]
For reference, @bebraw is correct. You are currently duplicating HMR which could make for some funky debugging though I'd have to try and make that break to say what the ramifications are.

**Comment by Thstone37** [comment]
@bebraw,when I add publicPath to the output options,It can work.
