### ISSUE TITLE
Module not found Error when i use the DllReferencePlugin & DllPlugin 

### ISSUE THREAD

**Issue by Justinidlerz** [webpack/webpack#2793]
#For example

project root
```
-layout
     |-index.js
     |-webpack.config.js
     |-node_module
                 |- jquery
-home
    |-index.js
    |-webpack.config.js
-dist
    |-layout.js
    |-home.js
    |-layout-manifest.json
```

##layout root   

index.js
```javascript
var jquery = require('jquery');
```   

webpack.config.js
```javascript
module.exports = {
	entry : {
		layout : ['./index.js']
	},
	output : {
		path : '../dist/',
		publicPath: "./",
		filename: '[name].js',
		library: "[name]_[hash]"
	},
	plugins : [
		new webpack.DllPlugin({
			path: path.join(__dirname, "../dist", "[name]-manifest.json"),
			name: "[name]_[hash]"
		})
	]
};

```

##home root  

index.js
```javascript
var $ = require('jquery');

console.log($);
```

webpack.config.js   
```javascript

module.exports = {
	entry : {
		home : './index.js'
	},
	output : {
		path : '../dist/',
		publicPath: "./",
		filename: '[name].js',
	},
	plugins : [
		new webpack.DllReferencePlugin({
			scope: "layout",
			manifest: require("../dist/layout-manifest.json")
		})
	]
};

```

##run
```
cd layout
webpack
cd ../home
webpack
```

**Comment by Justinidlerz** [comment]
layout-manifest.json
```
{
  "name": "layout_f6f5df3ecd15715133bf",
  "content": {
    "./index.js": 1,
    "./node_modules/.npminstall/jquery/3.1.0/jquery/dist/jquery.js": 2
  }
}
```

**Comment by sokra** [comment]
You are using the `scope` parameter incorrectly. Remove it

**Comment by pahund** [comment]
Is there someplace that explains how to use the scope parameter correctly? :-)

**Comment by martinko2009** [comment]
what is the use of scope?

**Comment by light24bulbs** [comment]
The documentation of the 'scope' option is confusing.  The documentation mentions two separate modes, scoped and mapped, but it doesn't explain what causes the plugin to run in mapped versus scoped mode.  I have assumed that it runs in mapped mode unless you specify "scope".

The explanation regarding resolution is also confusing, although it seems that if you use a scope, webpack doesnt try to actually resolve the modules, and thus they dont need to be anywhere locally accessible.  A big gotcha here that should be mentioned is your scope value better not match any folder in your directory tree or it will be ignored. 

Here is the offending documentation https://webpack.js.org/plugins/dll-plugin/

**Comment by Justinidlerz** [comment]
@andrebautista  like @ sokra talked, remove `scope` parameter.

**Comment by andrebautista** [comment]
I'm having trouble with a similar issue maybe @sokra can help clarify. My environment makes use of aliasing within the library code and import syntax which is different from all the examples I've been finding. I'm receiving the error `Module not found: Error: Can't resolve 'site'` when I try to import `myVar` into the main webpack bundle's code. I can clarify some of my build contents if needed, I tried to keep it compact.

**testVariables.js**
`export const myVar = "test";`

**site.js** I'm not exactly sure this syntax is correct to expose variables to import in the other bundle
`import { myVar } from "siteVariables";`

**webpack - library config**
```
...
 
 entry: {
      site: ["./src/site.js"]
 },
 output: {
     path: path.join(__dirname, "../dist"),
     filename: "[name].js",
     library: "[name]_[hash]"
 },
 resolve: {
     alias: {
         "siteVariables": path.resolve('testVariables.js)
     }
 }
 plugins: [
      new webpack.DllPlugin({
            name: "[name]_[hash]",
            path: path.join(__dirname, "../dist", "[name]-manifest.json")
      })
    ]
```

webpack - main bundle
```
new webpack.DllReferencePlugin({
          context: path.resolve("../sites/dist"),
          manifest: path.resolve('../sites/dist/site-manifest.json')
})
```

**bundle using library** not sure how to import the variables either? This is the line that gives me the error
`import ? from ?`
