### ISSUE TITLE
Nsp 130

### ISSUE THREAD

**Issue by doug-wade** [webpack/webpack#2795]
**I'm submitting a bug report**

**Webpack version:**
1.13.1

**Please tell us about your environment:**
OSX 10.11.5

**Current behavior:**

```
(+) 1 vulnerabilities found
┌───────────────┬─────────────────────────────────────────────────────────────────┐
│               │ ReDoS via long string of semicolons                             │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Name          │ tough-cookie                                                    │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Installed     │ 2.2.2                                                           │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Vulnerable    │ >=0.9.7 <=2.2.2                                                 │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Patched       │ >=2.3.0                                                         │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ Path          │ react-server-cli@0.4.0 > webpack@1.13.1 > watchpack@0.2.9 > ch… │
├───────────────┼─────────────────────────────────────────────────────────────────┤
│ More Info     │ https://nodesecurity.io/advisories/130                          │
└───────────────┴─────────────────────────────────────────────────────────────────┘
```

**Expected/desired behavior:**

```
(+) No known vulnerabilities found
```
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.** 

```
$ npm init --yes
$ npm i -S webpack@latest
$ npm i -D nsp
$ nsp check
```
- **What is the expected behavior?**

```
(+) No known vulnerabilities found
```
- **What is the motivation / use case for changing the behavior?**
  Security
- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
  N/A 
- **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart | ...] 
  N/A

For more information, see https://nodesecurity.io/advisories/130

**Comment by TheLarkInn** [comment]
@doug-wade Thank you very much for this. I will create a new label specifically for security. Have you evaluated this for webpack 2.1.0-beta.20 yet?

**Comment by d3viant0ne** [comment]
@TheLarkInn - I run nsp checks on my 2.1.0-beta.X project, i'll check the output

**Comment by d3viant0ne** [comment]
As an aside, given the ease of running nsp on a project should this not be part of our build validation?

**Comment by TheLarkInn** [comment]
For what it's worth I don't think the package specified ends up in the runtime template but security never hurts.
