### ISSUE TITLE
AMD 'define' should be a code split point

### ISSUE THREAD

**Issue by kmontag** [webpack/webpack#2796]
**I'm submitting a feature request**

**Webpack version:**
1.13.1

**Please tell us about your environment:**
OSX 10.11

Currently AMD modules using `define` are compiled as if their dependencies were synchronously required - i.e. webpack doesn't treat `define` as a code split point, even though its behavior is effectively identical (minus the optional first argument) to AMD's async `require`. This makes it difficult to do any chunking optimization, or take advantage of dynamic dependencies, in a large AMD codebase.

Example here: https://gist.github.com/kmontag/6a70bfc9593b8bd54c9285dfda2d4604

Desired behavior: AMD's `define` should be recognized as a code split point, either automatically or via some config option.

Thanks!

**Comment by rafde** [comment]
would that apply to this style?
```
define(function(require){
  var myModule = require('myModule');
  var myModule2 = require('myModule2');
});
```
where 
```
var myModule = require('myModule');
  var myModule2 = require('myModule2');
```
would create code split points?

**Comment by kmontag** [comment]
I think those should still be treated as synchronous dependencies,
actually, though it's a bit up to interpretation.

At least in the RequireJS case, those `require` calls would be expected to
error out unless the dependencies had been explicitly loaded sometime
before the factory gets invoked, which suggests to me that they should be
inlined.

**Comment by rafde** [comment]
Or a tleast have the option to enable it for code splitting.
Right now, I am looking making a plugin that will transform 
```
define(function(require){
  var myModule = require('myModule');
  var myModule2 = require('myModule2');
});
```
to 
```
require.ensure(['myModule', 'myModule2'], function(require){
  var myModule = require('myModule');
  var myModule2 = require('myModule2');
});
```
for development since the code base I am working has too many modules to start switching out to `require.ensure`, and in a naive attempt to make `webpack --watch --source-map inline-source-map` build faster.

**Comment by kmontag** [comment]
FWIW here's the hack I've been using to force a split point, which you may be able to modify for your use case: https://gist.github.com/kmontag/22fa1b15ea8e73e6a7ffaf7815739bf2

Though as I mentioned, IMHO the transformation you're talking about doesn't quite preserve the behavior that I'd expect from an AMD module.

**Comment by rafde** [comment]
> Though as I mentioned, IMHO the transformation you're talking about doesn't quite preserve the behavior that I'd expect from an AMD module.

As I mentioned, I am assuming code splitting will make my module rebuilds faster when using `--watch`
Interesting that you decided to use a different AST lib instead of using the AST that webpack provided from `this`[`._compiler`](http://webpack.github.io/docs/loaders.html#_compiler)[`.parse`](http://webpack.github.io/docs/plugins.html#the-parser-instance)

**Comment by kmontag** [comment]
Ah nice. I am just getting familiar with the WP internals, thanks for the
pointer :)

**Comment by sokra** [comment]
`define` has sync semantics. It's not possible to make it a split point as it would break the application. Keep the case it mind when `define` exports something.

``` js
// a.js
define(["./b"], function(b) {
  console.log(b);
});

// b.js
define(function() {
  return "Hello World";
});
```

**Comment by kmontag** [comment]
Ah, I see what you mean - though it still seems that the factory itself is allowed/expected to be executed asynchronously, so `a` and `b` are able to live in separate files.  E.g. using your example above, a RequireJS app would do the following:

```javascript
// app.js
require(["./a"], function() { });

// loads a.js via script tag
// loads b.js via script tag
// executes the b.js factory (return "Hello World")
// executes the a.js factory (console.log(b))
```

@sokra is there any way to achieve this separation with webpack? We have an application with a large number of `define`d modules that are depended on dynamically, and have previously (with RequireJS) been able to split them up into a handful of files that are loaded on demand.

**Comment by kmontag** [comment]
Alternately, is there any way to provide a module with an asynchronous export value, via a loader or some other method? That way `define(['a'], function(a) { return {dep: a}; }` could be rewritten to something like:

```javascript
callback = module.async();
define('require', function(require) {
  factory = function(a) {
    return {dep: a};
  };
  require.ensure(['a'], function(a) {
    callback(factory(a));
  });
});
