### ISSUE TITLE
Issues with module bindings - README.md Unexpected token (2:3)

### ISSUE THREAD

**Issue by loretoparisi** [webpack/webpack#2799]
I get several issues with module `bindings`:

`webpack` complains about critical dependencies:

```shell
WARNING in ./~/bindings/bindings.js
Critical dependencies:
113:22-40 the request of a dependency is an expression
113:43-53 the request of a dependency is an expression
 @ ./~/bindings/bindings.js 113:22-40 113:43-53
```

and about the `README.md` file (!)

```
WARNING in ./~/bindings/README.md
Module parse failed: /node_modules/bindings/README.md Unexpected token (2:3)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:3)
```

My configuration file is this 

```javascript
var path = require('path');
var webpack = require("webpack");

module.exports = {
  entry: './pgapi',
  output: {
    path: path.join(__dirname, 'dist'),
    filename: 'bundle.js'
  },
  module: {
    noParse: /node_modules\/json-schema\/lib\/validate\.js/,
    loaders: [
      { test: /\.json$/, loader: 'json-loader' }
      , {
          test: /\.js$/,
          loader: "transform?brfs"
        }
    ]
  },
  resolve: {
    extensions: ['', '.webpack.js', '.web.js', '.js']
  },
  node: {
    console: true,
    fs: 'empty',
    net: 'empty',
    tls: 'empty'
  },
  plugins: [
        //new webpack.optimize.UglifyJsPlugin(),
        //new webpack.optimize.DedupePlugin(),
        new webpack.DefinePlugin({
            __DEV__: true
        })
    ]
};
```

**Comment by sokra** [comment]
Native modules won't work in webpack

**Comment by loretoparisi** [comment]
@sokra ok there is anyway to exclude all native modules? I'm not using any native module directly, but there are inner dependencies from other modules at 2nd, 3rd or in depth levels.

**Comment by pushtheworldllc** [comment]
Having the same issue, trying to use `openbci` which has a dependency called `serialport` which has native dependencies. 

I have tried `noParse`. The issue with using the externals is that the module is not loaded properly into the main file and simply get's added as `module.exports = openbci` instead of injecting it or `module.exports = require('openbci')`. @loretoparisi  Did you get yours working?

**Comment by jtlindsey** [comment]
+1

**Comment by loretoparisi** [comment]
@aj-ptw nope, I have tried `noParse` as well, but it fails at some point, due to native module 2n and 3rd level dependencies as - the "mess" of those dependencies is described [here](http://stackoverflow.com/questions/38577161/node-how-to-make-dependency-analysis-and-remove-unused-module-dependecies)

**Comment by aj-ptw** [comment]
So for me I think the issue is that you have to add these native modules to the externals list but also build them for the right platform. In my use case I am using electron which is needs to build just the right native modules and still inject them properly.
