### ISSUE TITLE
Remove last comma in bundles

### ISSUE THREAD

**Issue by jhnns** [webpack/webpack#28]
It seems like webpack is adding a superfluous comma at the end of the bundle. Although it's not valid JavaScript modern browsers are handling this error decently. But older browsers like IE7 fail.

``` javascript
/******/},     <----
/******/
/******/})
// END OF BUNDLE
```

**Comment by gyf30827** [comment]
Has the problem been solved ，How about this one
![image](https://user-images.githubusercontent.com/22958382/190303269-3e948d96-1dac-4f45-8f61-eb0db0ae0260.png)

**Comment by alexander-akait** [comment]
We don't support IE7, sorry
