### ISSUE TITLE
Implement Stream interface?

### ISSUE THREAD

**Issue by mnichols** [webpack/webpack#280]
I am trying to use gulp-rev (https://www.npmjs.org/package/gulp-rev) to revision my assets. I know I _could_ manually do this for my webpack.config stuff but it raises a more important question to me: How can I pipe the output from webpack into an arbitrary stream? 
I couldnt find any examples and it doesnt look obvious to me. Any pointers? Can you show an example of piping output from webpack into gulp-rev?

**Comment by trusktr** [comment]
https://github.com/shama/webpack-stream
