### ISSUE TITLE
Module parse errors emit to stdout and seem to succeed

### ISSUE THREAD

**Issue by ajcrites** [webpack/webpack#2802]
**I'm submitting a bug report**

**Webpack version:**
1.13.x

**Please tell us about your environment:**
OSX 10.x / Linux 

**Current behavior:**
If you run `webpack` that results in a module parse error (but no other errors), the error will be reported on the console, but it will be written to `stdout` instead of `stderr`. The exit status will be 0 (success).

Essentially the build will appear to have succeeded, but there is no sane way to catch the error or stop the build even though it won't work.

**Expected/desired behavior:**
Any of:
* Module parse errors emit to stderr
* Any such errors cause a nonzero exit status for `webpack`
* The build is rolled back

# Example
Created an example repo to showcase the issue:
https://github.com/ajcrites/force-webpack-error

**Comment by sokra** [comment]
Fixed in webpack 2. Try `--bail` for webpack 1.
