### ISSUE TITLE
Modify source data

### ISSUE THREAD

**Issue by HumbleBeck** [webpack/webpack#2805]
Is it possible to somehow modify css file content that's included in js(without extract-text-webpack-plugin) on compilation stage by writing custom plugin?
I've read [plugins](https://github.com/webpack/docs/wiki/plugins) docs, but cant understand/find what hook to use.
If briefly I need to modify css before webpack have built result bundle, and even before it have built `compilation.assets`, is that possible?

**Comment by sokra** [comment]
put a custom loader before the css-loader.

**Comment by HumbleBeck** [comment]
OK, thank you, I think this question can be closed
