### ISSUE TITLE
Allow exports of multiple modules for libraries

### ISSUE THREAD

**Issue by wictorwilen** [webpack/webpack#2809]
**I'm submitting a feature request**
**Webpack version:**
All versions

**Please tell us about your environment:**
All environments

**Current behavior:**
When creating multiple bundles from TypeScript files only the last exported module class listed in the entry are actually exported in the resulting bundle file. This is for example the result of two TypeScript files (transpiled with ts-loader):

```JavaScript
__webpack_require__(4); // Exports from first file
module.exports = __webpack_require__(6); // Exports from second file
```

When loading this bundled file using, for instance SystemJs like this:
```JavaScript
System.import('bundle.js').then( function(scope) {
   // only the exports from the webpack module 6 (above) is available here
})
```

**Expected/desired behavior:**

I would like to have the option to make all bundled modules to be exported. The resulting JavaScript could look like this:

```JavaScript
var export4 = __webpack_require__(4);
for(var i in Object.keys(export4)) {
	module.exports[Object.keys(export4)[x]] = export4[Object.keys(export4)[x]]
};
var export6 = __webpack_require__(6);
for(var i in Object.keys(export6)) {
	module.exports[Object.keys(export6)[x]] = export6[Object.keys(export6)[x]]
}; 
```

This should be opt-in configurable (per entry?) so it will backwards compatible.

A simple change in MultiModule.js is required for this to work:
```JavaScript
if (dep.module) {
			if (outputOptions.exportAllModules) {
				str.push("var export" + dep.module.id + " = __webpack_require__(");
				if (outputOptions.pathinfo)
					str.push("/*! " + dep.request + " */");
				str.push("" + JSON.stringify(dep.module.id));
				str.push(")");
				str.push("\nfor(var i in Object.keys(export" + dep.module.id + ")) {\n\tmodule.exports[Object.keys(export" + dep.module.id + ")[i]] = export" + dep.module.id + "[Object.keys(export" + dep.module.id + ")[i]]\n}");
			} else {
				if (idx === this.dependencies.length - 1)
					str.push("module.exports = ");
				str.push("__webpack_require__(");
				if (outputOptions.pathinfo)
					str.push("/*! " + dep.request + " */");
				str.push("" + JSON.stringify(dep.module.id));
				str.push(")");
			}
		} else {
			str.push("(function webpackMissingModule() { throw new Error(");
			str.push(JSON.stringify("Cannot find module \"" + dep.request + "\""));
			str.push("); }())");
		}
```

* **What is the motivation / use case for changing the behavior?**

This change allows for a combination of dynamically loaded modules using SystemJS and using bundles from webpack
 
* **Browser:** all
 
* **Language:** TypeScript

**Comment by wictorwilen** [comment]
Demo of working system.import() with dynamic modules: https://github.com/wictorwilen/webpack-dynamic-modules/
Demo of not-working system.import() with multiple exports in dynamic modules: https://github.com/wictorwilen/webpack-dynamic-modules/tree/multiplewidgets

**Comment by Kovensky** [comment]
Can the same not be accomplished with `export * from 'a'`, `export * from 'b'`, etc in the entry point? That seems like the more future-proof way.

**Comment by sokra** [comment]
see @Kovensky answer
