### ISSUE TITLE
SystemJS (Registry) Target for Loader Spec 

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack#2810]
## Creating SystemJS Registry Target for ES6 Loader Spec

_Asside: This issue will be the tracker for our discussions and proposal with @GuyBedford after [last weeks meeting](https://github.com/webpack/meeting-notes/blob/master/2016-07/july-22.md#systemjs)._ Since my explanation will not be as far as detailed as the discussions between @sokra and @guyBedford, I will yield to them to fill in any details that I missed or got wrong. 

Details: 
Discussing the possibility of allowing, or making available _public modules_ in webpack to be exposed for the System registry and loader. 

This should be able to be done utilizing the same functionality from webpack's DllPlugin in which chunk/moduleId's are mapped to filenames per (@sokra). This will essentially provide a mapped context in which chunks can be loaded into the registry. 

Configuring this will be an opt-in property that can be set with `output.libraryTarget`. Maybe the target name can be `system`? (Can discuss further).

**Comment by wictorwilen** [comment]
I'm supportive of this as long as you enable dynamic loading of modules, as can be done in Webpack 1 with System.import().

**Comment by guybedford** [comment]
I've made a start on this in https://github.com/guybedford/systemjs-webpack-plugin.

This is by no means a completed project, but a starting point for further discussion.

It works really nicely though, and allows any dynamic System.import to load webpack modules and dynamically load webpack chunks on demand.

#### What it does

We generate a manifest that selects webpack module ids to map to public names to be set in the loader registry via System.register or System.registerDynamic (ES module and CJS module registrations respectively). This manifest is included in the main output file, and any progressively loaded chunks also write into the manifest as those chunks are loaded.

We also provide the ability for automatically creating bundles configuration in SystemJS. What this means is that `System.import('app/x')` can load the correct webpack chunk for `app/x` assuming `app/x` is specified as a public module in this manifest.

The manifest itself is generated through an array of `filter, keyname` pairs, which are explained in the README file. I tried to make this process as general as possible while still providing nice defaults so you can select any arbitrary modules and names to put into the registry.

#### Questions / todos

I still have a lot of ifs here, so feedback would be really welcome.

1. Should we output the manifest as a sparse array or object (I tried to follow the webpack convention sort of here, but perhaps an object would make more sense?)

2. We should have a better public module detection system based on whether the module is a main entry point or not.

3. How to handle naming cases for eg `lib/app/x.js` where I want to name that `mypublicName/x.js` currently we compute a structured module object for template replacement (https://github.com/guybedford/systemjs-webpack-plugin/blob/master/systemjs-register-public-modules.js#L41) but what is currently in place doesn't seem to handle cases like this. API feedback on  the `keyname` system would be welcome here. I think this is probably the most gritty and risky part of it.

4. Any ideas about how to handle caching for this are appreciated. I guess something like this is relatively cacheless, as it runs at a full compilation level and I don't think it's doing a lot of work anyway.

Any questions further are very welcome, especially if there are gaps in the understanding of what this is doing.

//cc @sokra @TheLarkInn @robwormald

**Comment by wictorwilen** [comment]
I made an extremely simple module to keep all `system.import` calls intakt, which is what I need in my project at the moment, where we have one project split into multiple chunks/bundles.
https://github.com/wictorwilen/keepsystemjs.webpack.plugin

**Comment by bebraw** [comment]
Any idea what to so with this as `System.import` was dropped in favor of dynamic `import`?

**Comment by sokra** [comment]
Not related to this issue.

As there is guys plugin (https://github.com/guybedford/systemjs-webpack-plugin) now, I think it's safe to close this issue.

**Comment by guybedford** [comment]
I would not recommend that plugin experiment as an approach here at all. It is very limited, and was really just to try and form a discussion point to think about how such an integration might work.

Having considered about this problem a little further, I think it's worth rather picturing webpack chunks themselves as the only public modules which should exist in the browser module registry. Such a model would adapt well to utilizing the `<script type="module">` tag in browsers without needing a further registry API. Any deeper layer of granularity does seem to just be a performance overhead without any benefit.

The plugin could likely be updated to such a model in future as well if there was interest.
