### ISSUE TITLE
What is the new syntax for style loader with extraction?

### ISSUE THREAD

**Issue by dschissler** [webpack/webpack#2812]
I can't figure out the syntax for using style text extraction or how to use PostCSS with Webpack 2.

Current correct Webpack 1:

``` javascript
  plugins: [
    new ExtractTextPlugin('css/[name].css', { allChunks: false}),
  ],
  loaders: [
      {
        test: /\.css$/,
        loader: ExtractTextPlugin.extract("style-loader", "css-loader!postcss-loader")
      {
  ]
```

New failed Webpack 2 experiment:

``` javascript
let extractCSS = new ExtractTextPlugin('css/[name].css');

  loaders: [
      {
        test: /\.css$/,
        loader: extractCSS.extract({
          notExtractLoader: 'style-loader',
          loaders: ['css', 'postcss']
        })
      }
  ]
```

**Comment by mover96** [comment]
You need to use the old loader syntax with `ExtractTextPlugin`. [See here](https://github.com/webpack/webpack/issues/2797#issuecomment-234706953).

**Comment by dschissler** [comment]
I'll close this issue up in half a day or so in case anyone has anything to add.

**Comment by dschissler** [comment]
@mover96 I still don't know the setup for that.  There are a million ways that I could do it incorrectly.

**Comment by mover96** [comment]
@dschissler This is how I am handling it in `webpack 2.1.0 beta.20`
```js
 module: {
        loaders: [
            { test: /\.(png|woff|woff2|eot|ttf|svg)$/, loader: 'url-loader?limit=100000' },
            { test: /\.css/, loader: extractCSS.extract(['css']) },
            { test: /\.json/, loader: 'json'}
        ]
    },
```

**Comment by dschissler** [comment]
So I think that the issue is that postcss isn't working for me.  It just never completes after minutes but works ok on my Webpack 1 setup.

Never completes

```javascript
        loader: extractCSS.extract(['css', 'postcss']),
```

completes in 2 seconds

```javascript
          loader: extractCSS.extract(['css']),
```

I've trimmed the entirety of my entry code down to just this:

```javascript
import $ from 'jquery'
import './style.css'

console.log('blah')
```

and the style is just this:

```css
.p{
  background-color: green;
}
```


My PostCSS setup:

```javascript
  postcss: function (webpack) {
    return [
      require("postcss-import")({
        addDependencyTo: webpack,
        path: [themeRoot, appModulesRoot, nodeModulesRoot]
      }),
      require("postcss-url")(),
      require("postcss-cssnext")({
        // Defined in './app/webpack/config'
        browsers: appConfig.browsers,
        import: {
          path: [themeRoot],
          // Setup watches on these files
          onImport: function(files) {
            files.forEach(this.addDependency);
          }.bind(this)
        }
      }),
      require("postcss-browser-reporter")(),
      require("postcss-reporter")(),
    ]
  }
```

**Comment by mover96** [comment]
>Never completes
loader: extractCSS.extract(['css', 'postcss']),

My `ExtractTextPlugin` experience is limited, but I'm pretty sure you want the `style-loader` as the first argument practically always, then chain the rest of the loaders. Try this:
```js
loader: extractCSS.extract(['style', 'css!postcss']),
```

**Comment by dschissler** [comment]
This fails immediately on Webpack 2

```javascript
          loader: extractCSS.extract('css!postcss']),
```

**Comment by mover96** [comment]
Use my line from above, if it fails what is the error?

**Comment by mover96** [comment]
I just edited my line above to remove the brackets. Try and use `loader: extractCSS.extract('style', 'css!postcss'),` and if it fails what is the error? @dschissler

**Comment by dschissler** [comment]
Ok I deleted my last post because it was a silly error.  It doesn't want to finish.

Both don't finish and when I try to hit the `webpack-dev-server` path it gives me this:

```javascript
Error: no such file or directory
    at MemoryFileSystem.readdirSync (/opt/webird/dev/node_modules/memory-fs/lib/MemoryFileSystem.js:126:10)
    at writeDirectory (/opt/webird/dev/node_modules/webpack-dev-server/lib/Server.js:77:21)
    at Server.<anonymous> (/opt/webird/dev/node_modules/webpack-dev-server/lib/Server.js:109:3)
    at Layer.handle [as handle_request] (/opt/webird/dev/node_modules/express/lib/router/layer.js:95:5)
    at next (/opt/webird/dev/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/opt/webird/dev/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/opt/webird/dev/node_modules/express/lib/router/layer.js:95:5)
    at /opt/webird/dev/node_modules/express/lib/router/index.js:277:22
    at Function.process_params (/opt/webird/dev/node_modules/express/lib/router/index.js:330:12)
    at next (/opt/webird/dev/node_modules/express/lib/router/index.js:271:10)
    at expressInit (/opt/webird/dev/node_modules/express/lib/middleware/init.js:33:5)
    at Layer.handle [as handle_request] (/opt/webird/dev/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/opt/webird/dev/node_modules/express/lib/router/index.js:312:13)
    at /opt/webird/dev/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/opt/webird/dev/node_modules/express/lib/router/index.js:330:12)
    at next (/opt/webird/dev/node_modules/express/lib/router/index.js:271:10)
```

**Comment by mover96** [comment]
Ok what happens if you do `loader: extractCSS.extract('style', 'css'),`?

**Comment by dschissler** [comment]
It finishes in 2 seconds and can produce the CSS file.

Is this an issue with the plugin chaining second argument or with PostCSS working with Webpack 2?

**Comment by mover96** [comment]
Looks like a `PostCSS` issue to me. I have no experience with that loader so I would try googling that error for a bit and if not make an issue on the loaders repo.

**Comment by dschissler** [comment]
ok.  Difficult to reproduce and take time making a script.  I'll try it later with SASS or LESS.

**Comment by d3viant0ne** [comment]
@dschissler - I'm about 2 hours away from having to do this with sass. I'll update here with issues / success.

**Comment by lavezzi1** [comment]
Same trouble here with postcss-loader and webpack 2-beta.21. 

Tried this 
`loader: ExtractTextPlugin.extract('style-loader', 'css-loader!postcss-loader')`

Then run webpack-dev-server and it doesn't finish.

**Comment by lavezzi1** [comment]
Still no solution, guys?

**Comment by OlegLustenko** [comment]
Have same issues, anyone find solution ?

**Comment by laggingreflex** [comment]
Following syntax works:

    {
      module: {
        rules: [
          {
            test: /\.css$/,
            loader: ExtractTextPlugin.extract({
              loader: ['css', 'postcss']
            })
          }
        ]
      },
      plugins: [
        new webpack.LoaderOptionsPlugin({
          options: {
            postcss: [
              require('precss'), 
              ...
            ]
          }
        }),
        new ExtractTextPlugin({
          allChunks: true,
          filename: 'app.css'
        })        
      ]
    }

with:

    +-- webpack@2.1.0-beta.25
    +-- extract-text-webpack-plugin@2.0.0-beta.4
    +-- postcss-loader@0.13.0
