### ISSUE TITLE
Support nested import declarations in webpack 2

### ISSUE THREAD

**Issue by Kovensky** [webpack/webpack#2814]
It's in [stage-0](https://github.com/tc39/proposals/blob/d26dd0a/stage-0-proposals.md) following the 2016-07 TC39 meeting.

Specification: https://github.com/tc39/ecma262/pull/646

"Sales pitch" / explanation: https://github.com/benjamn/reify/blob/master/PROPOSAL.md

Nested imports are still declarative so it doesn't change how webpack has to bundle them (they can't be split points, for example), but it does let you restrict the scope of the imported identifiers + allows the `__webpack_require__` call to be delayed.

Might need acorn support first, in case it early aborts on "unexpected ImportDeclaration". IIUC, the main needed changes are just also looking for non-top-level ImportDeclaration, and only hoisting to top of nearest containing Block (or Program).

Supporting use cases like `try { import }` or `if ('constant' != 'constant') { import }` could be good in the future, but I would consider that an optimization rather than a requirement. In the conditional import, the `__webpack_require__` still won't run so no unexpected behavior (other than bundling the unused module) happens.

Should I try making a PR?

**Comment by aluanhaddad** [comment]
It seems like a bad idea to support this when the semantics are still undecided and neither Babel nor TypeScript support it. Implicit await is not trivial and there seems to be an ongoing discussion around whether the `await` should be implicit at all.

**Comment by d3viant0ne** [comment]
I have to agree with @aluanhaddad 

I would personally hold off until this gets in the later stages with a solid spec or is picked up by the for mentioned TS / Babel where you could have a reasonable assurance of long term support.

**Comment by Kovensky** [comment]
Right, I hadn't considered that "just moving the `__webpack_require__` inside the block" would imply an `await`...
