### ISSUE TITLE
There is another module with an equal name when case is ignored.

### ISSUE THREAD

**Issue by uMaxmaxmaximus** [webpack/webpack#2815]
i use windows 10 x64
I upgrade node to 6.3.1 version and get:

```
WARNING in ./modules/ui-js/dom/core/html-parser.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.

WARNING in C:/localhost/ui-js/modules/ui-js/dom/core/html-parser.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.
```

This is error for ALL files in path `modules/ui-js`

Webpack config:

``` javascript
resolve: {
  modulesDirectories: ['modules', 'node_modules'],
  extensions: ['', '.js', '.coffee']
},
```

`modules`  directory i use to storage my custom npm modules

**Comment by zhouweiming** [comment]
+1 the same problem.

 when I use `c:\...` in cmd, get `WARNING in C:/...`,  use `C:\...` in cmd, get `WARNING in c:/...`.

**Comment by mover96** [comment]
Are these modules also in `node_modules`? It seems like the resolver is finding 2 possible files and it doesn't know which one to use

**Comment by rwilliams-scottlogic** [comment]
I have the same issue - I get the warning, and the said module is included twice in my bundle.

Env: Windows 7 x64, webpack 1.13.1, node 6.3.0.

```
WARNING in c:/dev/xxx/app/folder/constants.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.

WARNING in ./app/folder/constants.js
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.
```
webpack config:
```
resolve: {
  root: [
    path.resolve('./app')
  ]
}
```
(the purpose is to avoid many messy ../../../foo/bar style relative imports)

Necessary condition:
* a module imports constants.js via `import { NAME } from 'folder/constants';`
* another module imports constants.js via import { NAME } from './constants';

Bundle contains:
* ./app/folder/constants.js
* c:/dev/xxx/app/folder/constants.js

**Comment by zhouweiming** [comment]
@mover96 these warnings are all in `node_modules`. 

@rwilliams-scottlogic 

I have given up to solve and start develop on mac. I think this problem should be resolved on node level, because I get more puzzling warnings.

https://stackoverflow.com/questions/38656250/webpack-warning-on-windows-there-is-another-module-with-an-equal-name-when-cas

**Comment by Pomax** [comment]
One immediate mitigation is to update webpack so that it at least tells the users *which* modules are conflicting. Just knowing "that" there is a conflict does not have users track down the problem, whereas having the module name as basic information goes a long way towards at least knowing whether it's a real problem, or something unavoidable like a project that uses Node.js's own `Buffer` as well as the [buffer for browser](https://npmjs.com/package/buffer) package.

**Comment by Allov** [comment]
A temporary fix / hack that I've been using is to change the way the script is ran like so:

```
  ...
  "scripts": {
    ...
    "start": "cd .. && cd C%cd:~1% && mycommand"
  },
  ...
```

This way, it'll force the drive letter to be uppercase. The `cd ..` seems redundant, but Windows won't let us change the directory if it's the same as it ignores cases at this point. :/

**Comment by Pomax** [comment]
That solves part of the problem, but will still lead to the same issue cropping up for codebases with both `require('Buffer')` and `require('buffer')` (which are two different things entirely), or code where someone on a case-insensitive OS accidentally writes code with `require('React-Router')` when the rest of the code correctly uses `require('react-router')`.

**Comment by UsulPro** [comment]
To get rid of problems with lowercase drive letter on Windows you can try this https://www.npmjs.com/package/driveup as a hotfix for this issue. It changes the drive letter the UpperCase:
```
e:\your_project_path>driveup
 
E:\your_project_path>
```
or to launch your shell:

```
e:\>startcmd cmder e:\your_project_path
```
You can setup cmder launching to always have uppercase drive letter

**Comment by Pomax** [comment]
This is the kind of thing that someone from the webpack project should have a quick look at, because it deserves a test case to be added to the battery of tests that already run, for CI/regression testing on Windows using Appveyor (or similar service).

**Comment by Pomax** [comment]
In that case: bump. Someone from the webpack dev community needs to look at this to determine if it still needs fixing (because if this still happens, it needs fixing. If it doesn't, then clearly this can be closed as already fixed)

**Comment by evilebottnawi** [comment]
@Pomax It is breaking chage, can you describe use case for this?

**Comment by Pomax** [comment]
How is "making the webpack warning more informative" a breaking change? The only thing this issue requests is having webpack say which modules are conflicting due to case mismatch in the warning it is already writing out.

**Comment by evilebottnawi** [comment]
@Pomax thanks for clarify, PR welcome

**Comment by Pomax** [comment]
I'm sure they are, but it's not going to come from me - webpack is a _huge_ codebase and I'm already working on too many large projects to try to dive into what is required here.

**Comment by Pomax** [comment]
Final note: the error message was updated to be much more informative, with the latest 4.x now containing all the information necessary to pinpoint and fix the underlying problem.

Example:
```
WARNING in ./node_modules/Buffer/index.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* i:\temp\mj\node_modules\Buffer\index.js
    Used by 1 module(s), i. e.
    i:\temp\mj\wp.js
* i:\temp\mj\node_modules\buffer\index.js
    Used by 1 module(s), i. e.
    i:\temp\mj\wp.js
 @ ./node_modules/Buffer/index.js
 @ ./wp.js
```

**Comment by Megabyteceer** [comment]
I had the same problem. It was caused by total-commander. Total-commander sends launch commands with lower cased disk letters.
