### ISSUE TITLE
The SystemPlugin breaks tslib

### ISSUE THREAD

**Issue by Tragetaschen** [webpack/webpack#2817]
**I'm submitting a bug report**

**Webpack version:**
2.1.0-beta.20

**Please tell us about your environment:**
Windows 10

**Current behavior:**
tslib might register itself with SystemJS [when available](https://github.com/Microsoft/tslib/blob/master/tslib.js#L24).
The SystemPlugin replaces the first check of that line with `"object" === "object"` so at runtime (without SystemJS) the second check throws.

Note that the next check for AMD is also rewritten entirely (`else if (true)`)

**Expected/desired behavior:**
The plugin shouldn't break tslib.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.** 
A single `import 'tslib';` typescript entry point results in the broken check.

* **What is the expected behavior?**
Why do you ask a second time?

* **What is the motivation / use case for changing the behavior?**
So it doesn't break
 
* **Browser:** [all <s>| Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView </s>] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart | ...] 
What?

**Comment by TheLarkInn** [comment]
What System plugin are you referring to. Just want to confirm.

**Comment by Tragetaschen** [comment]
[This one](https://github.com/webpack/webpack/search?utf8=%E2%9C%93&q=systemplugin)

**Comment by sokra** [comment]
fixed
