### ISSUE TITLE
overwrite watch config from CLI

### ISSUE THREAD

**Issue by flyon** [webpack/webpack#2819]
I have a webpack.config.js with watch:true and I would like to overwrite that setting when I call "webpack" from the CLI in a certain environment. Is this possible? Like `webpack --watch=false` would be nice

**Comment by rafde** [comment]
why does it need to be in your config? why not use `--watch` through a separate script?

**Comment by flyon** [comment]
Because we already have three scripts for dev/staging/deployment and I now
want to create nonminified bundles for staging and deployment too, so I was
hoping to re-use the dev script for that, but it has watch:true for local
development. Its totally possible to create another script, was just
looking for other options

**Comment by rafde** [comment]
You could provide your own argument that is read in your dev config like --no-watch and process.argv.indexOf("--no-watch") >= 0 that's read from inside the config file

**Comment by flyon** [comment]
ah, that's how that works! thanks, thats perfect!
