### ISSUE TITLE
Webpack is stuck with DllReferencePlugin

### ISSUE THREAD

**Issue by vinhlh** [webpack/webpack#2820]
```

▀ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▀ ╢░░░░░░░░░░░░░░░░░░░░░ 75% advanced module optimization
```

It's stuck at this step.

My manifest file
```
{
  "name": "vendor_867d96888e41897a2594",
  "content": {
    "./node_modules/deep-equal/index.js": 140,
    "./node_modules/deep-equal/lib/is_arguments.js": 141,
    "./node_modules/deep-equal/lib/keys.js": 142,
    "./node_modules/fbjs/lib/EventListener.js": 74,
    "./node_modules/fbjs/lib/ExecutionEnvironment.js": 7,
    "./node_modules/fbjs/lib/camelize.js": 143,
    "./node_modules/fbjs/lib/camelizeStyleName.js": 144,
    "./node_modules/fbjs/lib/containsNode.js": 145,
    "./node_modules/fbjs/lib/createArrayFromMixed.js": 146,
    "./node_modules/fbjs/lib/createNodesFromMarkup.js": 147,

```

webpack config
```
import manifest from './build/manifest.vendor.json'

    new webpack.DllReferencePlugin({
      context: process.cwd(),
      manifest
    }),

```

webpack: 2 beta 20

**Comment by vinhlh** [comment]
found that it's stuck on looping `EnsureChunkConditionsPlugin`

**Comment by TheLarkInn** [comment]
@vinhlh thanks for reporting this, Could you please fill out the additional details we request in the github issue template. This will help us identify the issue better for you.

**Comment by vinhlh** [comment]
@TheLarkInn 
The root cause is because I used a function to pass the parameter to `getComponent`.
But webpack uses **static analysis** (based on AST) to analyze modules, so it will never works as my expectation.
```
const loadRoute = cb => module => cb(null, module.default)
const errorLoading = error => `Dynamic page loading failed ${error}`

// lazy load a component and its children
// - `${component}` is a hack to make webpack's static analyzer can recognize these lazy modules
const lazyLoad = component => (location, cb) => System.import(`${component}`).then(loadRoute(cb)).catch(errorLoading)

export default (
  <Route path="/" component={Layout}>
    <IndexRoute getComponent={lazyLoad('./pages/Home')} />
```

So, just have to change to:
```
const loadModule = cb => module => cb(null, module.default)
const errorLoading = error => `Dynamic page loading failed ${error}`

export default {
  path: '/',
  component: Layout,
  onEnter(nextState, replace) {
    replace('/home')
  },
  childRoutes: [
    {
      path: 'home',
      getComponent(nextState, cb) {
        System.import('./pages/Home').then(loadModule(cb)).catch(errorLoading)
      }
    },
```

**Comment by Kovensky** [comment]
@vinhlh you should be able to do something like `System.import('./pages/' + path)` (to bundle all files inside the `./pages/` folder, each as a separate split point). That unfortunately requires a string concatenation as template strings aren't supported yet.

**Comment by hossein-nasr** [comment]
@vinhlh It still never finishes for me, although I checked that my code is similar to your solution.
here is my code:

       const loadModule = (cb) => (componentModule) => {
             cb(null, componentModule.default);
       };
        ...
    {
      path: '/wizard',
      name: 'wizard',
      getComponent(nextState, cb) {
        const importModules = Promise.all([
          System.import('containers/Profile/Wizard/WizardContainerReducer'),
          // System.import('containers/Profile/Wizard/WizardContainer'),
        ]);

        const renderRoute = loadModule(cb);

        importModules.then(([reducer, component]) => {
          injectReducer('ui', reducer.default);
          renderRoute(component);
        });

        importModules.catch(errorLoading);
      },
    },
