### ISSUE TITLE
Add CLI option for selecting a config from a multi-config webpack.config.js file

### ISSUE THREAD

**Issue by mohsen1** [webpack/webpack#2821]
Following from this [SO question](http://stackoverflow.com/questions/38653493) add a CLI option for selecting one of many exported configs in a multi-config `webpack.config.js` file

Maybe `--config-index` is a good name for it?

**Comment by TheLarkInn** [comment]
Well you could simply have separate configs (in separate files) that are imported from a central `webpack.config.js` and exported as an array. That way you can make use of the webpack CLI `--config` flag. Would this accomplish what you are looking for?

**Comment by mohsen1** [comment]
That would work but having a CLI option would be great

**Comment by TheLarkInn** [comment]
Please free to submit a Pull Request!! However keep in mind one very important issue to use right now is mitigating user experience issues. Adding one more piece of functionality that can be obtained in multiple ways is am anti-pattern for what we are _striving_ to accomplish in the future. #2797

**Comment by mohsen1** [comment]
I'm fine if future webpack versions disallow multi-config config files but if that's an option, there should be an option to choose a config from set of configs exported in the config file.

**Comment by mohsen1** [comment]
I'll make a PR to implement `--config-index` when I find some time so we can discuss it further in there

**Comment by gdi2290** [comment]
you can probably do that with js like this
`webpack.config.server.js`
`webpack.config.client.js`
`webpack.config.js`
```es6
module.exports = function(env = {}) {
  var serverConfig = require('webpack.config.server');
  var clientConfig = require('webpack.config.client');
  var isDefaultConfig = env.server === undefined && env.client  === undefined;
  var config = [serverConfig, clientConfig];
  return isDefaultConfig ? config : config.filter(conf => Boolean(conf));
}
```

webpack
webpack --env.server
webpack --env.client
webpack --config webpack.config.client.ts
webpack --config webpack.config.server.ts

**Comment by rafde** [comment]
@mohsen1 you can pass anything you want to the CLI
for instance. `webpack --config webpack.config.js --dev-only`
in  webpack.config.js
```
var isDevOnly = process.argv.indexOf('--dev-only') >= 0
```
Then I do my whatever.
You have all the flexibility you need to do what you want with your configs.

**Comment by sokra** [comment]
@rafde this is not recommended and disallowed in webpack 2. @gdi2290 uses the correct form.

But anyway a `--config-name` would be great. In a multi-config you can give every config item an name with the `name` property.

**Comment by mohsen1** [comment]
This is done!
