### ISSUE TITLE
UglifyJsPlugin is preventing generation of sourcemaps in Webpack 2

### ISSUE THREAD

**Issue by laggingreflex** [webpack/webpack#2822]
**Bug report**

**Webpack version:**
2.1.0-beta.20

**Current behavior:**
Source-maps not generated when using UglifyJsPlugin

**Expected/desired behavior:**
Source-maps should be generated when using UglifyJsPlugin

**Steps to reproduce/Gist:** 
https://gist.github.com/laggingreflex/c6ae56c0a7edffa0a230ce4b46557742

[Similar issues](https://github.com/webpack/webpack/issues/2766) suggest that the source-maps are at least generated incorrectly, but in this above minimal gist they're not generated at all.

**Comment by laggingreflex** [comment]
sh%&! nevemind. Forgot to use `sourceMap: true` option in UglifyJsPlugin.

**Comment by cnweibo** [comment]
@laggingreflex , you saved me several hours. thanks!
