### ISSUE TITLE
Failed to load plugin html: eslint-plugin-html

### ISSUE THREAD

**Issue by lianer** [webpack/webpack#2823]
compiler error on dev environment

windows server 2012
nodejs 6.2

![](https://cloud.githubusercontent.com/assets/9332264/17270906/4422c4d2-56a0-11e6-9bc9-0118e97c3b33.png)

**Comment by jk77me** [comment]
I also get this error

**Comment by lianer** [comment]
It  can be  compiled   successfull   when  I  disabled  the eslint ，have  you  solved  it？

**Comment by jk77me** [comment]
yes， because my file‘name error ，I solved it
