### ISSUE TITLE
Webpack source map doesn't work with ES6 generator

### ISSUE THREAD

**Issue by cdchambers** [webpack/webpack#2824]
**I'm submitting a bug report**

Webpack 1.13.1
OSX 10.11
Chrome 52 (with the js-harmony flag enabled)

I have a simple webpack config and a couple simple generator functions.

``` javascript
module.exports = {
  entry: "./gen.js",
  output: {
      path: __dirname,
      filename: "bundle.js"
  },
  devtool: 'source-map',
  module: {
    loaders: [{
      test: /\.js$/,
      exclude: /node_modules/,
      loader: "babel-loader",
      query: {
        presets: ['es2015'],
      }
    }]
  }
}
```

``` javascript
import 'babel-polyfill';

function* anotherGenerator(i) {
  yield i + 1;
  yield i + 2;
  yield i + 3;
}

function* generator(i){
  yield i;
  yield* anotherGenerator(i);
  yield i + 10;
}

var gen = generator(10);

console.log(gen.next().value); // 10
console.log(gen.next().value); // 11
```

I can set a breakpoint in the generator functions if I don't transpile from ES6 to ES5. But if I transpile and use webpack source map, I can't set a breakpoint inside the generator function. The break point would jump to the top of the function. Like this:

![screen shot 2016-07-30 at 9 32 27 pm](https://cloud.githubusercontent.com/assets/1521435/17274591/401b4722-569d-11e6-8cb1-af2fa57acc09.png)

Is this a bug in webpack's source map?

**Comment by bebraw** [comment]
Can you try against webpack 2 and the newest Chrome?

**Comment by cdchambers** [comment]
Still seeing the problem with webpack: 2.2.0-rc.3. 
Tried it on both 
Chrome beta: 56.0.2924.28 beta (64-bit)
Chrome stable: 55.0.2883.87 (64-bit)

**Comment by yeyu456** [comment]
I met same problem using Typescript 2.1.4 with webpack 1.13.2, 1.14.0 and the latest version 2.2.0-rc.4.
And i have to insert //@ sourceURL= before first line.
Maybe insert sourceURL can help before the bug fixed. @cdchambers

**Comment by nicastelo** [comment]
Same here! 
webpack 1.14.0

**Comment by sokra** [comment]
Pretty old issue. I guess this works now.
