### ISSUE TITLE
If omitted all chunks are used?? Could you explain what do you mean?

### ISSUE THREAD

**Issue by wzup** [webpack/webpack#2827]
Could you please elaborate what you actually meant?

**CommonsChunkPlugin** 

At first read this, bold and italic part:

> `options.name` or `options.names` (`string|string[]`): The chunk name of the commons chunk. An existing chunk can be selected by passing a name of an existing chunk. If an array of strings is passed this is equal to invoking the plugin multiple times for each chunk name. ***If omitted and `options.async` or `options.children` is set all chunks are used***, otherwise `options.filename` is used as chunk name.

Now read this, bold and italic part:

> `options.async` (`boolean|string`): If `true` ***a new async commons chunk is created as child of `options.name`*** and sibling of `options.chunks`. It is loaded in parallel with options.chunks. It is possible to change the name of the output file by providing the desired string instead of true.

And a question is. 
How can you create a child of something that is omitted, that doesn't exist? 

1. If `options.name` or  `options.names`  is omitted and `options.async` is set
2. If  `options.async` is `true` a new async commons chunk is created as child of `options.name`

What did you actually mean?

**Comment by sokra** [comment]
If
* `name`(s) is not set
* `async` or `children` is true

then

all chunks are used by the CommonChunkPlugin.

The CommonsChunkPlugin iterates over all chunks of the compilation and does it job. It checks for common modules in the children of the chunk and creates an async chunk with the common modules.

**Comment by pksjce** [comment]
This issue was moved to webpack/webpack.io#123
