### ISSUE TITLE
callback is not a function for DefinePlugin and v2.1.0-beta.20

### ISSUE THREAD

**Issue by joshunger** [webpack/webpack#2828]
v2.1.0-beta.20

```
TypeError: callback is not a function
    at NullFactory.create (node_modules/webpack/lib/NullFactory.js:9:9)
    at node_modules/webpack/lib/Compilation.js:211:11
    at node_modules/webpack/node_modules/async/lib/async.js:181:20
```

This doesn't work -

```
       new webpack.DefinePlugin({
         'process.env':{
           'NODE_ENV': JSON.stringify('production')
         }
       })
```

This appears to work -

```
       new webpack.DefinePlugin({
         'process.env.NODE_ENV':JSON.stringify('production')
       })
```

**Comment by cristian-sima** [comment]
+1

**Comment by sokra** [comment]
Do you use any 3rd-party plugin?

**Comment by joshunger** [comment]
@sokra we have other plugins but I don't have access to the code at the moment. Let me know if you can't reproduce.

**Comment by sokra** [comment]
I can't. I assume it's some plugin that is incompatible with webpack 2. We changed the `Factory` interface to take an option object instead of multiple arguments.

**Comment by sokra** [comment]
Or an issue with mixed dependencies webpack 1 and webpack 2.

**Comment by joshunger** [comment]
I'll work on a repro for you. Do you happen to have a hyperdev template for a quick repro? It would be easier to submit bugs that way.

**Comment by sokra** [comment]
I don't care as long I ca repo the bug

**Comment by tomascharad** [comment]
+1

**Comment by tomascharad** [comment]
I think that in my case webpack-stream was causing the problem.

**Comment by jiyinyiyong** [comment]
Same error here, I was playing with [vue 2](https://github.com/vuejs/vue-hackernews-2.0/blob/master/build/webpack.client.config.js)(cloned weeks ago without latest commit actually) it's okay running with the expressjs middleware, but gives errors when I run it with `webpack-dev-server --config ...`

**Comment by blahah** [comment]
For me this was caused by a v1 webpack dependency still lurking around. Perhaps try `npm ls webpack` to check you don't have v1 somewhere too.
