### ISSUE TITLE
Why does the UglifyJsPlugin affect other loaders?

### ISSUE THREAD

**Issue by jhnns** [webpack/webpack#283]
That's more of a question than an issue.

I was wondering why `optimize.minimize` has been removed in favor of the UglifyJsPlugin? I prefer plugins over big configuration options, but it seems not logically to me that the UglifyJsPlugin switches all other loaders (even those which don't generate JS) into min-mode.

**Comment by gaearon** [comment]
Wow, this is quite unexpected!

**Comment by jhnns** [comment]
Lately, I was thinking about this again. This is still misleading for newcomers. Wouldn't it be better to remove all the minification stuff from the loaders?

I think the best solution would be to have different plugins for all the various web-compatible output files, like `MinifyJS`, `MinifyCSS`, `MinifyHTML`, `MinifyImages` that are applied on all files that are about to be emitted. However, the minification should happen before the hash calculation.

**Comment by sokra** [comment]
> I think the best solution would be to have different plugins for all the various web-compatible output files, like MinifyJS, MinifyCSS, MinifyHTML, MinifyImages that are applied on all files that are about to be emitted. However, the minification should happen before the hash calculation.

That doesn't work for inlined files... i. e. CSS or HTML inlined into JS.

--

Btw. This was changed in webpack. UglifyJs now only minimized js. A LoaderOptionsPlugin allows to switch on minimizing for loaders.

**Comment by barroudjo** [comment]
I wholeheartedly agree with the issue, so it's great if this has been solved, but I haven't seen it for the stable (1.x.x) version. Has this only been solved for the beta version ?

**Comment by sokra** [comment]
only in the 2.x version. It's a breaking change which cannot be done on 1.x version.

**Comment by uMaxmaxmaximus** [comment]
And the content of the line "JS", in the name of the plugin, all knocked me up, and I spent about two days in order to understand what was going on. What generally uneducated programmer invented it?

**Comment by azrahel** [comment]
It s kinda shame that even though it has JS in name, it forces all loaders into minimize option. 
Another shame is that it is not pointed in red, **bold** font on webpack page, but rather hidden somewhere between code snippets. 

Good point and kind of 'the answer' (?) when uglifyJS messes your production build (as it does in ours project), minification of css can be switched off using -minimize option on css-loader. 

Described here:
https://github.com/webpack/css-loader#minification

It overwrites uglifyJS forceful minification mode and in our case, let production build work as should.
