### ISSUE TITLE
why does webpack pack node-libs-browser in to the bundle.

### ISSUE THREAD

**Issue by zdying** [webpack/webpack#2830]
why does webpack pack node-libs-browser to the bundle.

when i use dll plugin. i find that webpack add the node-libs-browser to the manifest.json file.

how to disable it?

**Comment by zdying** [comment]
@bebraw 
Could you answer my questions? Thank you very much

**Comment by bebraw** [comment]
Hi,

It's hard to say anything concrete without code.

Could it be some specific dependency that's causing it to be bundled? I know React 15.3 is going to need `node: {process: false}` or else it will bundle something extra. It can be something like that.

**Comment by Kovensky** [comment]
I did not know React 15.3 was going to require that...

Turns out I indeed have `node-libs-browser` (bundled but not) running in production :D

**Comment by bebraw** [comment]
@Kovensky Yeah. It has to do with a Jest specific tweak they did. More [here](https://twitter.com/jbscript/status/760664988910432258).

**Comment by zdying** [comment]
@bebraw @Kovensky thx. :)

**Comment by joeporpeglia** [comment]
I came to this issue after discovering `node-libs-browser` in my bundle. Turns out something in `@babel/runtime` references the `process` object directly, which causes webpack to inject the browser package. I fixed the issue by adding `node: false` to my webpack config.

**Comment by joeporpeglia** [comment]
I came to this issue after discovering `node-libs-browser` in my bundle. Turns out something in `@babel/runtime` references the `process` object directly, which causes webpack to inject the browser package. I fixed the issue by adding `node: false` to my webpack config.
