### ISSUE TITLE
UglifyJsPlugin does not work with node5 babel preset

### ISSUE THREAD

**Issue by darkalor** [webpack/webpack#2836]
**I'm submitting a bug report**

**Webpack version:**
1.13.1

**Please tell us about your environment:**
Ubuntu Linux 16.04

**Current behavior:**
UglifyJsPlugin fails with `SyntaxError: Unexpected token: name ...` when using a node5 babel preset
(https://www.npmjs.com/package/babel-preset-node5 or https://www.npmjs.com/package/babel-preset-es2015-node5)

**Expected/desired behavior:**
UglifyJsPlugin works with babel node5 preset, when running on node 5.0+

**Webpack loader configuration**
```js
    loaders: [
      {
        test: /\.js?$/,
        loader: 'babel-loader',
        exclude: /node_modules/,
        query: {
          babelrc: false,
          presets: [
            'node5',
            'stage-0',
          ],
          plugins: [
            'transform-runtime',
          ],
        },
      },
    ],
```

**Comment by Kovensky** [comment]
Uglify is completely incompatibly with ES6 syntax.

If you really want to output anything newer than ES5, then either skip Uglify, minimize with something else like webpack-closure-compiler, or just don't minify, especially when not targeting a browser. It's a node module, so it's not like it'll have to be transferred or cache verified every time a script runs.

**Comment by darkalor** [comment]
@Kovensky Thanks for the information. Then it's just uglyfy's issue, was not aware they had this limitation.
Although, perhaps it's worth mentioning that in the [plugin's docs](https://webpack.github.io/docs/list-of-plugins#uglifyjsplugin). 
Otherwise, I guess this issue can be considered resolved.

> It's a node module, so it's not like it'll have to be transferred or cache verified every time a script runs.

Yep, that was never something I actually needed. I've just reused parts from another config I had, and ran into this error.

**Comment by SamHH** [comment]
^^ I agree that this should definitely be mentioned in the docs. Just had this error when I tried to remove the es2015 preset from my project for modern browsers.
