### ISSUE TITLE
ES6 module export instead of Node style require

### ISSUE THREAD

**Issue by stoplion** [webpack/webpack#2838]
Can Webpack be used with ES6 module export instead of Node style require? I'd prefer to keep things clean and only use ES6 module for everything? And if so, can we get some perhaps get some awesome documentation on how to? Thanks! :)

**Comment by wcjordan** [comment]
If you use Webpack 2 beta you can.  These resources may be useful:
https://gist.github.com/sokra/27b24881210b56bbaff7
http://moduscreate.com/webpack-2-tree-shaking-configuration/

If you use Webpack 1 you can still write with ES6 exports, but you'd need to use the Babel loader with Webpack to transpile to requires before bundling.
Here's a tutorial which should help
http://jamesknelson.com/using-es6-in-the-browser-with-babel-6-and-webpack/

**Comment by stoplion** [comment]
ty!
