### ISSUE TITLE
Webpack new watcher + git adding / removing files

### ISSUE THREAD

**Issue by danielgrippi** [webpack/webpack#2840]
**I'm submitting a bug report!**

**Webpack version:**
1.13.x

**Please tell us about your environment:**
OSX 10.11.6

**Current behavior:**
Webpack watcher isn't triggered by files added or removed by git.  Scenario:
1. Run `webpack --watch` within a git directory
2. Add new file, `lol.js` in directory (webpack discovers it just fine)
3. Run `git clean -f` (which actually moves `lol.js` into `./.git/`)
4. Observe that webpack doesn't detect the change until any other watched file is saved

NOTE: This is not reproducible when using `webpack.OldWatchingPlugin()`

**Expected/desired behavior:**
In the above example, running `git clean -f` should cause webpack to detect the change, rebundle, and the contents of `lol.js` shouldn't be present in said bundle.
- **Browser:** all
- **Language:** all

**Comment by Korzun** [comment]
👍

**Comment by bebraw** [comment]
Moved to https://github.com/webpack/webpack-cli/issues/19.
