### ISSUE TITLE
__webpack_require__ why is slow?

### ISSUE THREAD

**Issue by gagayang** [webpack/webpack#2842]
i find  __webpack_require__ is slow in chrome than requirejs, they all use AMD. but why???

and how make it faster??

**Comment by hkrutzer** [comment]
Have you measured the slowness? If so, what are the results?

**Comment by TheLarkInn** [comment]
@gagayang I'm going to close this for now as this not really a question worth answering unless you have merit-able performance data. If you have a better solution, I would recommend a proposal or PR along with reasonings and performance data to back it up.

**Comment by mmahalwy** [comment]
I have experienced this too - something weird is happening on chrome where it's really slow. I don't have performance measures as all of a sudden it started happening. I am on beta.20

**Comment by TheLarkInn** [comment]
If you could provide the information in the github issue template, then this will allow us to help you!!

**Comment by TheLarkInn** [comment]
Or create a new issue with useful information for us.

**Comment by Kovensky** [comment]
It is true that `__webpack_require__` will be the top of any flame chart and profile, since it's the function that actually runs literally everything else in the bundle, but the function itself should have negligible run time internally...

**Comment by mmahalwy** [comment]
Not sure what is best to describe this issue to be honest :S 

But this is my best stab at it so far:

![image](https://cloud.githubusercontent.com/assets/3749095/17819462/d347a374-65fc-11e6-868b-a7d5ae1c0cca.png)


Notice, after the javascript is loaded, there seems to be 20-30s gap between that and when `addStyles` kicks in to add the style blobs to the head. Not sure why - it only happens on chrome and not on safari.

**Comment by hkrutzer** [comment]
Can you provide a minimal working example?

**Comment by mmahalwy** [comment]
Sorry, it's part of work app :(
