### ISSUE TITLE
[bug] ? require('xxx')   case sensitive has different result between linux and mac

### ISSUE THREAD

**Issue by huyinghuan** [webpack/webpack#2843]
In mac, ```require``` isnot case sensitive, and in linux ， ```require`` ` is case sensitive.

Linux:  Centos 7.0
mac: 10.11.6 (15G31) 
Nodejs:  v4.4.7 LTS

there are files:
package.json
```
{
  "name": "test",
  "dependencies": {
    "vuex": "^1.0.0-rc.2",
    "webpack": "^1.13.1"
  }
}
```
app.js
```
require('Vuex')
```

build.js

```
'use strict';
const _webpack = require('webpack');
const _path = require('path');
let config = {
    entry: './app.js',
    output: {
        path: "build",
        filename: 'build.js'
    }
}
var compiler = _webpack(config);

compiler.run(function (err, stats) {
    console.log('Webpack ok!');
});
```

run

```
node build.js --harmony
```
then:

on linux,     throws error " Cannot find module \"Vuex\""  , this is reasonable,
But on mac,    webpack is pass.     this is not reasonable.

Why?  is this a bug?

**Comment by wcjordan** [comment]
By default, I believe mac hard disks are not case sensitive.  You should investigate if your disk is setup with a case sensitive hard disk.
Here's a stack exchange [post](http://apple.stackexchange.com/questions/71357/how-to-check-if-my-hd-is-case-sensitive-or-not) with directions.

If your disk is not case sensitive, I would expect this behavior from the resolver.

**Comment by huyinghuan** [comment]
Thanks.  my mac has a not case sensitive disk
