### ISSUE TITLE
Contradictory Documentation of Resolve.Root

### ISSUE THREAD

**Issue by machineghost** [webpack/webpack#2845]
**I'm submitting a documentation bug report**

Your documentation at:
https://webpack.github.io/docs/configuration.html#resolve-root

reads as follows:

    It must be an absolute path! Don’t pass something like ./app/modules.

    Example:

    var path = require('path');

    // ...
    resolve: {
      root: [
        path.resolve('./app/modules'),

Just in case the problem isn't clear, you tell the reader NOT to "pass something like ./app/modules" ... then less than ten lines later you provide an example of using exactly the thing you just said not to use.

It actually sort of looks like whoever wrote the warning didn't have access to edit the example, so the best they could do was try and warn people before they get to the bad example.  Clearly though a better solution would be to provide an example of what he user *should* do. :)

**Comment by jquense** [comment]
`path.resolve('./app/modules')` creates an absolute path. thats what the function does.

**Comment by machineghost** [comment]
It took me a second to get what you're saying, but I think I understand what the documentation is trying to say now.

If I understand correctly, the first reference is saying "don't pass something like `'./app/modules'` to `resolve.root`", while the second is saying "but do pass **the result of passing `'.app/modules'` to `path.resolve`** to `resolve.root` "

That makes perfect sense, but I think my bug remains valid; the phrase "Don't pass something like" doesn't in any way indicate *where* you aren't supposed to pass the something.  And while that may seem obvious to you as a skilled Webpack user, the current language is likely problematic to a new user without context or understanding of what `resolve.root` even is (after all, if they already understood `resolve.root` perfectly they wouldn't be reading the documentation page).

Two simple fixes I could see:

1) "Don’t pass something like "./app/modules"; you must first convert it to an absolute path (eg. `path.resolve('./app/modules')`

2)
    // ...
    resolve: {
      root: [
        path.resolve('./app/modules'), // not './app/modules'

**Comment by jquense** [comment]
It seems like you may not quite be clear on the distinction between relative and absolute file paths, or didn't realize that node API path.resolve resolves relative paths to absolute ones? 

 It seems clear to me, it says to not use a relative path e. g. './app/modules', and then demonstrates how to take that relative path and turn it into an absolute path to be used as the value of resolve.root . I appreciate that it wasn't clear to you, however it's not a bug the documentation is correct.

**Comment by jquense** [comment]
Sorry if  I'm coming off annoyed sounding. that's not my intention, writing on a phone quickly. I'm sure we can make the doc more clear, however I don't think we want to use words like "paths like" vs relative and absolute which are well understand technical terms and used elsewhere in the documentation as well

**Comment by machineghost** [comment]
>Sorry if I'm coming off annoyed sounding

I didn't think you were annoyed, I thought you were trying to convince me that the documentation was ok because the standard for it was:

> It seems clear to me

Since it meets that standard, close the ticket and stop trying to convince an internet stranger of anything ;-)

But then your second reply made it clear that you do want to support beginners with your documentation, and if that's the case then by all means use whatever terminology is appropriate to the document.

All I'm trying to say is, when you're new you don't always learn everything linearly.  You may not have read the docs on `path.resolve` when you read the ones on `resolve.root`.  It is 100% possible to create (and certainly to inherit) a functional Webpack setup with your only understanding being that "`path.resolve` is that function you pass your paths to before they go in to the config", and if that's your only understanding then it seems strange to see the docs say "don't use this string" moments before using that string.

Plus, as I said before, the specific language used ("Don't pass something") is ambiguous enough that if you don't have a solid grasp of `path.resolve`, instead of interpreting it the correct way ("don't pass it directly as a value of the Webpack config object") you can interpret it as "don't pass it to the magic function you always pass paths to when they go in to the Webpack config".

**Comment by Kovensky** [comment]
The good part is that `resolve.root` is completely gone in webpack 2. :tada:

**Comment by machineghost** [comment]
Heh, well the only thing that beats good documentation is not needing any documentation in the first place :)

**Comment by pksjce** [comment]
This issue was moved to webpack/webpack.io#139
