### ISSUE TITLE
Breakpoints on initial page load don't work on Chrome with "eval" source maps

### ISSUE THREAD

**Issue by taion** [webpack/webpack#2846]
Opening this at the request of @TheLarkInn.

Ref https://github.com/webpack/webpack/issues/2145#issuecomment-237933851

This is an upstream Chrome issue: https://bugs.chromium.org/p/chromium/issues/detail?id=459499

This is just a placeholder to note the issue. I'm not aware of anything that webpack can do here.

Users can work around this by not using "eval" source maps if they want to hit breakpoints on initial page load.

**Comment by bebraw** [comment]
Does the issue still exist?

**Comment by taion** [comment]
I think so. The upstream issue is still open, anyway.

**Comment by taion** [comment]
Looks like this was resolved in https://github.com/webpack/webpack/pull/5042.
