### ISSUE TITLE
Tree-Shaking getting rid of reexport line when it shouldn't

### ISSUE THREAD

**Issue by meenie** [webpack/webpack#2850]
**I'm submitting a bug report**

**Webpack version:**
2.x

**Please tell us about your environment:**
Windows 10

**Current behavior:**
It's not re-exporting a module because it thinks it's not being used, when it is.

**Expected/desired behavior:**
It should re-export the module

I have the following file structure:
```
first/
    index.js
    second/
        index.js
        thing.js
index.js
main.js
```

index.js:
```javascript
export * from './first';
```

main.js:
```javascript
import {wtf} from './';

console.log(wtf);
```

first/index.js:
```javascript
export * from './second';
```

first/second/index.js:
```javascript
export * from './thing';
```

first/second/thing.js:
```javascript
export const wtf = 'wtf';
```

The output from webpack is:
```javascript
webpackJsonp([0,2],[
/* 0 */
/***/ function(module, exports, __webpack_require__) {

"use strict";
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0____ = __webpack_require__(4);

console.log(__WEBPACK_IMPORTED_MODULE_0____["a" /* wtf */]);


/***/ },
/* 1 */
/***/ function(module, exports, __webpack_require__) {

"use strict";
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__second__ = __webpack_require__(2);
/* harmony namespace reexport */ for(var __WEBPACK_IMPORT_KEY__ in __WEBPACK_IMPORTED_MODULE_0__second__) if(__WEBPACK_IMPORT_KEY__ !== 'default') (function(key) { __webpack_require__.d(exports, key, function() { return __WEBPACK_IMPORTED_MODULE_0__second__[key]; }) }(__WEBPACK_IMPORT_KEY__));



/***/ },
/* 2 */
/***/ function(module, exports, __webpack_require__) {

"use strict";
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__thing__ = __webpack_require__(3);
/* harmony namespace reexport */ for(var __WEBPACK_IMPORT_KEY__ in __WEBPACK_IMPORTED_MODULE_0__thing__) if(__WEBPACK_IMPORT_KEY__ !== 'default') (function(key) { __webpack_require__.d(exports, key, function() { return __WEBPACK_IMPORTED_MODULE_0__thing__[key]; }) }(__WEBPACK_IMPORT_KEY__));



/***/ },
/* 3 */
/***/ function(module, exports, __webpack_require__) {

"use strict";

/* harmony export */ __webpack_require__.d(exports, "wtf", function() { return wtf; });var wtf = 'wtf';


/***/ },
/* 4 */
/***/ function(module, exports, __webpack_require__) {

"use strict";
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__first__ = __webpack_require__(1);
/* unused harmony namespace reexport */



/***/ },
/* 5 */,
/* 6 */
/***/ function(module, exports, __webpack_require__) {

module.exports = __webpack_require__(0);


/***/ }
],[6]);
//# sourceMappingURL=main.map
```

In the 4 module above, it should not have `/* unused harmony namespace reexport */`. It should actually re-export.

**Comment by Kovensky** [comment]
It's definitely easier to read the output with `NamedModulesPlugin`... could it be made the default when not using `minimize`? 😄 

It seems that module `0` is also treating the `wtf` name as an import of a default value, but no `export default` or `export { ... as default }` is in any of the files.

**Comment by meenie** [comment]
I'm actually using the new `angular-cli@webpack` release. So I don't have any control over the `webpack.config.js` file, unless I manually hack it.

**Comment by meenie** [comment]
I have created a git repo with a very simple project which shows the issue: https://github.com/meenie/webpack-import-barrel-bug

**Comment by 281330** [comment]
I am having the same issue.  I can `export * from './file'` just fine, but the LAST (or top before I actually import somewhere) index.ts I have to do `export { SomeComponent } from './file';`

So in my case I have a app/shared folder.

in app/shared/header, I have my header component.

in app/shared/header/index.ts, I have `export * from './header.component';`

in app/shared/index.ts, I have to do `export { HeaderComponent } from './header';` instead of export * which worked fine in systemjs

Please let me know if this is the same issue.

**Comment by meenie** [comment]
@281330: Yes, that's the same issue.  Tree-Shaking is not working properly.

**Comment by 281330** [comment]
Kind of unrelated to the specific issue, but you said that u cannot change the webpack config since its what angular-cli team thinks is best.  But how easy would it be to set up absolute paths so we can just do `import { Something } from 'app/shared/some-folder/something';` ?

**Comment by meenie** [comment]
I would be against doing that in my project.  Makes moving stuff around quite hard.

**Comment by 281330** [comment]
ok.  thx!

**Comment by LunicLynx** [comment]
Just ported an angular2 app from systemjs to webpack, got the same issue. 
Only Workaround for now is naming everything that should be reexported directly:

For the given example:
```
// in first/second/index.js
export {wtf} from './thing';

// in first/index.js
export {wtf} from './second';

// in index.js
export {wtf} from './first';
```

This get cumbersome from the get go, but works for now. Would love a fix!

**Comment by meenie** [comment]
@LunicLynx: This actually didn't fix it for me.  Try this scenario:
```
index.js
first.js
second.js
```

index.js:
```
export {test} from './first';
```

first.js:
```
export const test = 'hi';
```

second.js:
```
import {test} from './';

console.log(test); // undefined
```

**Comment by Kovensky** [comment]
(Crazy hypothesis but) could this be a regression caused by 3a6b649? It does change the behaviour of star imports, even though it's of imports of commonjs modules.

**Comment by meenie** [comment]
@Kovensky I tried reverted that commit and it did not fix it :(.

**Comment by romulof** [comment]
Related question: Does Webpack 2 features any kind of optimization for reexporting?

In the first example above, the `main.js` compiled code should call `__webpack_require__` with the index of `first/second/thing.js` module?

**Comment by meenie** [comment]
@sokra This is still an issue.  If you run my test repo (https://github.com/meenie/webpack-import-barrel-bug) you will notice that [sibling files that import each other's exports](https://github.com/meenie/webpack-import-barrel-bug/blob/78069173c18008470aea85fdf9c8da21c822d627/src/app/first/second/other_thing.js#L3) via the Import Barrel don't work.  Funnily enough, it will work if you do a `setTimeout(() => console.log('From other_thing.js:', thing), 0)`.

I'm using `^2.1.0-beta.21`.
