### ISSUE TITLE
what's the difference of "style!css!./style.css" and "!style!css!./style.css"?

### ISSUE THREAD

**Issue by zppro** [webpack/webpack#2851]
as question,
can't understand the character "!",any one can explain it ?

**Comment by Kovensky** [comment]
If you set up your `loaders` correctly, you almost never need any `!` in any of your requires.

`!` separates loaders. Note that, on the second string, you are passing the `./style.css` file to the `css` loader, then to `style` loader, then to the empty string loader, which will crash.

**Comment by zppro** [comment]
> `./style.css file to the css loader, then to style loader, then to the empty string loader, which will crash.`
i test two of them ,they both run ok!
but make me see that `!` is separtator to the loader.
