### ISSUE TITLE
TypeError: Cannot read property '.js' of undefined

### ISSUE THREAD

**Issue by foxhound87** [webpack/webpack#2852]
**Webpack version:**
1.13.1

**Environment:**
OSX 10.11.6

**Language:** 
ES6/7

**Current behavior:**

Error thrown here: `oldHandlers[ext] = (void 0)[ext];` in `hookExtensions()`

After building, when run I get the same error as explained here:
http://stackoverflow.com/questions/37275183/webpack-bundle-throwing-uncaught-type-error

**Webpack Configs**
- [/webpack.config.babel.js (main file)](https://github.com/foxhound87/rfx-stack/tree/5280cbbf839ae0a521a4c9dd9fc68018ad55bf9e/webpack.config.babel.js)
- [/webpack (all config files)](https://github.com/foxhound87/rfx-stack/tree/5280cbbf839ae0a521a4c9dd9fc68018ad55bf9e/webpack)

The issue occurs when disabling `externals: nodeModules()` from [webpack/config.server.js](https://github.com/foxhound87/rfx-stack/blob/5280cbbf839ae0a521a4c9dd9fc68018ad55bf9e/webpack/config.server.js#L32)
and removing the `webpack-hot-middleware` with all related stuff from the project (which prevent [webpack.config.babel.js](https://github.com/foxhound87/rfx-stack/tree/5280cbbf839ae0a521a4c9dd9fc68018ad55bf9e/webpack.config.babel.js) to be reloaded a second time [here](https://github.com/foxhound87/rfx-stack/blob/5280cbbf839ae0a521a4c9dd9fc68018ad55bf9e/src/web/server.js#L13))

**Comment by sokra** [comment]
You are not allowed to use `require.extensions` in code compiled with webpack.

**Comment by Kovensky** [comment]
AFAIK, `require.extensions` itself is at risk of being removed from node.
