### ISSUE TITLE
CommonsChunkPlugin problem with code splitting and multiple entry points

### ISSUE THREAD

**Issue by MilosRasic** [webpack/webpack#2855]
**I'm submitting a bug report**

**Webpack version:**
1.13.1

**Please tell us about your environment:**
Linux

**Current behavior:**
Trying to get code split between multiple entry points, with each entry point split into own code and vendor bundle, then commons extracted for both own code and vendor bundles.

Entry points look like:

```
        entry: {
            login: './src/Login/index.jsx',
            app: './src/index.jsx',
            vendor: Object.keys(packageDotJson.dependencies).filter(function (element) {
                return element !== 'font-awesome' && element !== 'jspdf';
            }),
            loginvendor: packageDotJson.loginDependencies
        },
```

The following works as expected:

```
            new webpack.optimize.CommonsChunkPlugin({
                name: "vendor",
                chunks: ["app"],
                minChunks: Infinity
            }),
            new webpack.optimize.CommonsChunkPlugin({
                name: "loginvendor",
                chunks: ["login"],
                minChunks: Infinity
            }),
            new webpack.optimize.CommonsChunkPlugin({
                name: "vendor.commons",
                chunks: ["vendor", "loginvendor"],
                minChunks: 2
            }),
```

Vendor bundles are extracted from each entry point bundle, then a common vendor bundle is extracted from the two vendor bundles.

Grepping the build results for definitions of commonly used packages like babal-polyfill and React, they are correctly found only in vendor.commons file.

Adding:

```
            new webpack.optimize.CommonsChunkPlugin({
                name: "commons",
                chunks: ["app", "login"],
                minChunks: 2
            }),
```

and testing for the same packages, we have:

```
> grep -R "var React = {" ./dist -l
./dist/vendor.commons.080acb7415d897182eca.js
./dist/commons.080acb7415d897182eca.js
```

It seems the final invoking of the plugin is selecting the original app and login chunks, as they were before vendor modules were removed into vendor and loginvendor chunks.

**Expected/desired behavior:**
Expecting

```
            new webpack.optimize.CommonsChunkPlugin({
                name: "commons",
                chunks: ["app", "login"],
                minChunks: 2
            }),
```

to select the app and login chunks with vendor modules removed and extract the common modules from them into commons chunk. Vendor modules shouldn't appear both in commons and vendor.commons chunks.
- **What is the motivation / use case for changing the behavior?**

It seems logical to expect that instances of the plugin will be ran sequentially and that every run will have access to chunks modified by the previous run.

This specific use case if for production build. We need vendor code in separate bundles to avoid generating sourcemaps for it. Multiple entry points are needed to avoid serving a lot of unnecessary code to the user. Common modules are extracted to avoid duplication.
- **Browser:** [ Chrome 52.0.2743.116 (64-bit) ] 
- **Language:** [ ES6/7 ]

**Comment by MilosRasic** [comment]
After "a little" more playing around with webpack, I came up with the following idea to create the commons chunk that doesn't also get vendor modules:
```
        new webpack.optimize.CommonsChunkPlugin({
            name: "commons",
            minChunks: function (module) {
                //custom solution to work around modified entry chunks not being available
                var inVendor = false;
                var ownCodeEntryNames = Object.keys(ownCodeEntries)
                var inOwnCodeEntriesCount = 0;

                for (var i = 0, len = module.chunks.length; i < len; i++)
                    if (module.chunks[i].name.indexOf('vendor') >= 0)
                        inVendor = true;
                    else if (ownCodeEntryNames.indexOf(module.chunks[i].name) >= 0)
                        inOwnCodeEntriesCount++;

                return inOwnCodeEntriesCount > 1 && !inVendor;
            }
        }),
```

Sadly, this causes vendor modules that aren't in both entry chunks to be returned to their entry chunk since inOwnCodeEntriesCount will be 1 and the callback will return false.

The solution to this would be to create commons and vendor.commons in the same plugin instance, using the same minChunks callback for both, like this:
```
        new webpack.optimize.CommonsChunkPlugin({
            names: ["commons", "vendor.commons"],
            minChunks: function (module) {
                    //some code
            }
        }),
```
The problem is that we don't have info on which common chunk the callback is being called for inside the callback, making it impossible to return differently for different chunks.

If there's no objections, I'd make a PR to change the minChunks callback call to `minChunks(module, count, commonChunk)`

**Comment by rafde** [comment]
@MilosRasic I've had more success doing

```
function _isVendor(module) {
  if (typeof userRequest !== 'string') {
    return false;
  }
  return  userRequest.indexOf('/node_modules/') >= 0  
} 

...

new webpack.optimize.CommonsChunkPlugin({
  name: "vendor",
  chunks: ["app", "login"],
  minChunks: function(module, count){
    return _isVendor(module);
  }
})
```
this removes the need to have that other `vendor` entry point you had earlier.

if you still want to get the vendors out of each entry you can

```
new webpack.optimize.CommonsChunkPlugin({
  name: "appvendor",
  chunks: ["app"],
  minChunks: function(module, count){
    return _isVendor(module);
  }
}),
new webpack.optimize.CommonsChunkPlugin({
  name: "loginvendor",
  chunks: ["login"],
  minChunks: function(module, count){
    return _isVendor(module);
  }
}),
new webpack.optimize.CommonsChunkPlugin({
  name: "vendor.commons",
  chunks: ["login", "app", "vendor", "loginvendor"],
  minChunks: function(module, count){
    return count >= 2 && _isVendor(module);
  }
}),
```
And now all the entry points have their own vendor and and a shared vendor chunk.

**Comment by sokra** [comment]
Note to myself: Check if non-entry chunks can be selected by the CommonChunkPlugin.

**Comment by MilosRasic** [comment]
@sokra It's been some time since I played with it, but iirc non-entry chunks can be selected. The problem is with selecting entry chunks that had some modules removed by previous runs of the plugin. They can be selected fine, but containing all the modules they originally did.

**Comment by kazazor** [comment]
It seems to me like non-entry chunks can't be selected by CommonChunkPlugin.

This is a problem for us since we would like to create the `vendors` chunk like this:
```js
    new webpack.optimize.CommonsChunkPlugin({
      name: 'vendors',
      minChunks: ({ resource }) => /node_modules/.test(resource)
    })
```

So what it forces me to do it for every dynamic import we're doing (using `import("path")`) we're also going and creating an entry chunk for it. Just so the above code will work.

Then, all of these "duplicate" chunks we're excluding from being added to the HTML using the `excludeChunks` of `HtmlWebpackPlugin`

So it basically looks like this:

```js
// Why do we need to exclude these entries?
// The entries here are being dynamically loaded per route in the application so we would like to set
// them to be excluded form HtmlWebpackPlugin auto inject of entry chunks.
//
// If they are being dynamically loaded in the system, so why do you need them here at all?
// We're creating a `vendors` chunk automatically from what being imported from `node_modules`, in order for webpack
// to know about what code exists in these route chunks we need to set them as entries here.
// That way we're getting everything we ever wanted! The `vendors` is being created out of ALL the vendors in the system,
// and we're still able to dynamically load these chunks per route without having them injected to index.html at the beginning.
const excludeEntries = {
  main: [path.join(chunksPath, 'main_chunk')],
  A_template_collection: [path.join(pagesPath, 'TemplateCollectionPage')],
  A_template_wizard: [path.join(pagesPath, 'TemplateWizardPage')],
  A_edit_template: [path.join(pagesPath, 'TemplateEditPage')],
  A_create_instance: [path.join(pagesPath, 'CreateInstancePage')],
  B_issues_collection: [path.join(pagesPath, 'IssuesCollectionPage')]
};

const entry = Object.assign({}, excludeEntries, {
  application: [path.join(chunksPath, 'application_chunk')]
});

const config = {
    entry,
    ...
    plugins: [
        new webpack.optimize.CommonsChunkPlugin({
          name: 'vendors',
          minChunks: ({ resource }) => /node_modules/.test(resource)
        }),
        new HtmlWebpackPlugin({
          title: indexHtmlTitle,
          resourceHintsMetaTags,
          inject: true,
          template: indexHtmlPath,
          favicon: srcPath + '/assets/favicons/autodesk-favicon.png',
          excludeChunks: Object.keys(excludeEntries)
        }),
    ]
    ...
}

```

The dynamic imports are being used on the same paths as the entry chunks that are being excluded from the html.

This causes some difficulties for us:

1. If you dynamically import something and forget to put it here as well it will not go into the vendors chunks and you'll lose cache
2. This creates for us chunks that we're not actually using. So for the same code I'll have the named entry chunk and I'll also have a chunk from the dynamic import. I'm not using the named entry-chunks but it's just noise to me.
That is even bigger when also using the ExtractTextPlugin

IMO we should add another issue on making `CommonChunkPlugin` support non-entry chunks.

@sokra - What do you think?

P.S:
I don't want to go ahead and import the `package.json` file and add to the vendors anything in `dependencies` since if for some reason I'll stop using a package and forget to remove it from the file, it will still be added to the `vendors` chunk.. Which is bad :)

**Comment by bebraw** [comment]
@kazazor What if you defined a heavier filter at `minChunks`? `module` (the first parameter) contains a lot of data. If you can detect the context based on that, you could then alter the behavior of the plugin as well.

**Comment by kazazor** [comment]
hi @bebraw , thanks for your response!

Maybe I'm missing here something, but the way I see it the `module`s I'll be getting are only the ones from the entry chunks to begin with.. So any information hold by the first parameter won't do me any good since to begin with the only modules that will get to this function are the ones **statically** imported in the entry chunks.

In any case, I looked at the `module` parameter and didn't see anything that I could use to change the behavior of the plugin..
Are you suggesting that some data in the `module` parameter could alter the behavior of the common chunk plugin to change its basic behavior and select also modules from non-entry chunks?

Maybe I missed something because it sounds to me like something that could only be achieved by a configuration to the plugin and not something in the `minChunks` function that got only modules statically imported to begin with..

**Comment by bebraw** [comment]
@kazazor Ok, if it doesn't go through the modules you want, it should probably be fixed on webpack core. What you need might simply not be possible at the moment.

**Comment by kazazor** [comment]
Yeah this is what I thought.. I'll go ahead and create a feature request for that.

Thanks for taking the time looking at it 👍

**Comment by kazazor** [comment]
Here you go :)

https://github.com/webpack/webpack/issues/4392

**Comment by mbrevda** [comment]
For anyone using the workaround of manually specifying all dynamic splits as entries: if you want to then remove those entries and not have them emitted or included in stats, see here: http://stackoverflow.com/a/39401288/747749
