### ISSUE TITLE
IgnorePlugin causes MODULE_NOT_FOUND error. webpack@2.1.0-beta.20

### ISSUE THREAD

**Issue by leonid-bauxy** [webpack/webpack#2858]
**I'm submitting a bug report**

**Webpack version:**
2.1.0-beta.20

**Please tell us about your environment:**
OSX 10.11.6

**Current behavior:**
```js
resolve: {
  alias: {
    'bluebird': path.join(__dirname, 'node_modules/bluebird/js/release/bluebird.js'),
  },
},
plugins: [
     // ...
     new webpack.IgnorePlugin(/map\.js$/, /node_modules\/bluebird\/js\/release/),
]
```

results in generated code

```js
__webpack_require__(!(function webpackMissingModule() { var e = new Error("Cannot find module \"./map.js\""); e.code = 'MODULE_NOT_FOUND'; throw e; }()))(Promise, PromiseArray, apiRejection, tryConvertToPromise, INTERNAL, debug);
```

**Expected/desired behavior:**
Error should not be thrown after some module is ignored by `IgnorePlugin`.

**Reproducable repo:**
https://github.com/le0nik/webpack-ignore-repro (see https://github.com/le0nik/webpack-ignore-repro/blob/master/dist/bundle.js#L3997 for the generated code)

**Comment by sokra** [comment]
This is working as expected. Instead of ignoring (which just omits the module from the bundle, but you are not allowed to require it), try to alias (`resolve.alias`) it to a mock module. Here you may use an empty function.

**Comment by le0nik** [comment]
Thanks! I've already done it with `NormalModuleReplacementPlugin` by changing those modules to `lodash/noop.js`. I thought `IgnorePlugin` was going to strip out the requires to the modules, too, not just the modules themselves.

**Comment by avesus** [comment]
@sokra is it possible to strip out the requires?

**Comment by samelie** [comment]
@sokra 

This was the solution for me. Combinations of options `externals` `NormalModuleReplacementPlugin` `IgnorePlugin` didn't work.
Was using this regex and it caught the modules: `/^(watson-developer-cloud\/speech-to-text\/v1|autodetect-decoder-stream|flac-parser|mp3-parser|ogg-parser|request)$/i` but was getting module not found / wasn't being replaced with `noop`.

This code was effective.

```
alias: {
        'flac-parser': join(constants.NULL_MODULES_DIR, 'flac-parser', 'index.js'),
        'ogg-parser': join(constants.NULL_MODULES_DIR, 'ogg-parser', 'index.js'),
        'mp3-parser': join(constants.NULL_MODULES_DIR, 'mp3-parser', 'index.js'),
        'autodetect-decoder-stream': join(constants.NULL_MODULES_DIR, 'autodetect-decoder-stream', 'index.js'),
        'request': join(constants.NULL_MODULES_DIR, 'request', 'index.js'),
        'watson-developer-cloud': join(
          constants.NULL_MODULES_DIR,
          'watson-developer-cloud',
        ),
   },
```
where _index.js_ = `module.exports = {}`

fyi, the reason for all this is we have a node version of the app we are 'modularizing' for browser.

**Comment by danburzo** [comment]
I've also experienced this issue in the following setup:

* load PNGs with file-loader
* obtain the generated URLs synchronously in code with `require('img/some-image.png')`

I'm now trying to use IgnorePlugin to exclude these PNGs from a build, but the code is failing in the `require()`...
