### ISSUE TITLE
Returning multiple results from a loader

### ISSUE THREAD

**Issue by jescalan** [webpack/webpack#2861]
**I'm submitting a bug report**
**Webpack version:** 1.10.x
**Please tell us about your environment:** OSX 10.x

So in the webpack documentation for loaders it says this:

> A single result can be returned in sync mode. For multiple results the this.callback must be called.

However, if you try to hit `this.callback` more than once, you get an error like this:

> Error: callback(): The callback was already called.

It is fairly reasonable why this is the case, however, I'm curious whether this is a bug, or misrepresented in the docs. I do have a situation where I need to export two modules out of a loader (a shared runtime dependency and template), and it seems like this would be the best way to do it. Although I am open to other suggestions!

**Comment by sokra** [comment]
You can call the callback with multiple parameters. But this doesn't result in multiple modules. Embed a require to your shared runtime instead.

**Comment by andreypopp** [comment]
>  I do have a situation where I need to export two modules out of a loader (a shared runtime dependency and template), and it seems like this would be the best way to do it. Although I am open to other suggestions!

You can just return a single module which requires a shared runtime dependency.

**Comment by jescalan** [comment]
So the runtime dependency in this case is actually dynamic, I can't require it from a set path. I get the code back for it on the first compile, so ideally I'd be able to inject the code directly as a new module. Is there a reasonable way to do this from a loader? I have managed to add source code as a module from a plugin, but it was quite difficult.

**Comment by sokra** [comment]
You still need to generate a require call. You can generate a require call to a loader directly: `require("!!/path/to/my/loader?arguments!")`

**Comment by jescalan** [comment]
@sokra makes sense, but I'm not sure I entirely understand how I can make this happen still. I have the runtime source code as a string in the loader (not in a file), in addition to the primary source code that the loader returns. I need to get the runtime source code added as a module before I can `require` it, right? 

I guess what I'm asking is whether I need to write the runtime source to a tempfile and then require that path, which seems inefficient, or whether there is a way to just add the source as a module and alias the name, then require that.

**Comment by sokra** [comment]
Option A: `require("!!/.../from-base64.js?97jn97v+z7az74t/fj9f34=!")`

---

Option B: `require("!!/.../from-hash.js?378d96bab239e9f1f0ef!")` and in loader
`var hash = require("./from-hash").add(source)`

**Comment by jescalan** [comment]
Awesome, thank you! Do the `from-hash` or `from-base64` loaders exist anywhere that I don't know about, or would I need to write them? Doesn't seem like they would be too difficult to write, just want to make sure I'm not reinventing the wheel. A quick google search didn't turn up anything promising.

**Comment by jescalan** [comment]
???

**Comment by satya164** [comment]
@sokra in my case I want to return a JS file and a CSS file from the loader. but if I use this inline loader trick, webpack fails on unexpected token because the file won't go through CSS loader. any workarounds?
