### ISSUE TITLE
hidden-source-map doesn't produce any source map

### ISSUE THREAD

**Issue by tleunen** [webpack/webpack#2862]
I'm testing webpack 2 on a project and I was using `hidden-source-map` with webpack 1 to produce a source map without having any references in the javascript file. (see [the doc](https://webpack.github.io/docs/configuration.html#devtool))

Testing the same value with webpack 2 doesn't create any source map.

**Comment by sokra** [comment]
Do other devTool options work?

**Comment by sokra** [comment]
i. e. `"source-map"`

**Comment by tleunen** [comment]
Haven't tried `source-map` but `inline-source-map` works.

**Comment by tleunen** [comment]
Tested with latest beta 21 and same issue.
`source-map` works as expected.

**Comment by WalterWeidner** [comment]
I dug into this a little bit. Looks like it is related to the UglifyJsPlugin. If I comment it out, I get source maps again.

**Comment by tleunen** [comment]
I don't have any `sourceMap` option on my `UglifyJsPlugin`. But I do have one for the css loader.
Maybe a conflict then @WalterWeidner ?

Should we especially set sourceMap: true for Uglify in addition of the `devtool` option?

**Comment by WalterWeidner** [comment]
Leaving `sourceMap: false` off of the Uglify plugin was good enough for us.

**Comment by tleunen** [comment]
https://github.com/webpack/webpack.js.org/blob/develop/content/how-to/upgrade-from-webpack-1.md#uglifyjsplugin-sourcemap

**Comment by prewk** [comment]
Might help someone:

We got source maps for CSS only, after reading this thread we explicitly set `sourceMap: true` for the `UglifyJsPlugin` and successfully got the js source maps again. `2.1.0-beta.25`

**Comment by tleunen** [comment]
Good to know. I'm blocked by other css/sass loader so I cannot really test it in my full project, but I'll close the ticket as soon as I can retest and make sure the sourcemap is there with the option.

**Comment by tleunen** [comment]
I can confirm the sourcemap is there with the option specified for the UglifyJsPlugin.

Closing the issue.
