### ISSUE TITLE
Memory Leak Sadness

### ISSUE THREAD

**Issue by iammerrick** [webpack/webpack#2863]
**I'm submitting a bug report**
[See this plugin](https://gist.github.com/iammerrick/945dac5d5049b309ee878c0fcb6a43f0)

**Webpack version:**
1.10.x

**Please tell us about your environment:**
OSX 10.11.6

**Current behavior:**
Recurrent builds (webpack-dev-server) with this plugin causes a memory leak which eventually crashes Node.js

**Expected/desired behavior:**
I would not expect this plugin to introduce a memory leak as I am not retaining any references. Does creating a child compiler cause a leak somehow?

Using the following plugin: https://gist.github.com/iammerrick/945dac5d5049b309ee878c0fcb6a43f0 Which uses the assets output by the webpack build to create a service worker in a template like fashion.

```
    new ServiceWorkerPlugin({
      entry: './src/sw',
      output: 'sw.js'
    }),
```

This plugin works as expected, however when used with webpack-dev-server every build grows memory until node eventually kills the process.
- **What is the expected behavior?**

Memory to state stable as it does without this plugin.
- **What is the motivation / use case for changing the behavior?**

Maybe behavior doesn't need to change? Maybe I just need better understanding of the child compiler API or a different way to solve this problem?
- **Language:** [all]

**Comment by TheLarkInn** [comment]
cc @paulirish since we've worked on this before, I'm just adding you for tracking incase you are interested. @iammerrick I'm going to try and get some time to tackle this next week. Sorry about the delay. Lots of things flying my way. But I think we can attempt to find this leak some how.

**Comment by iammerrick** [comment]
@TheLarkInn dude! Don't apologize, I am just so grateful for your help and enthusiasm. Fixing this is my full time job starting tomorrow (finally got my other tasks done for this sprint), I just know very little about webpack internals and why creating a child compiler would create a webpack leak so wanted to share it with people with more insight than me :-D

**Comment by sokra** [comment]
Do you use `[hash]` or `[chunkhah]` in your filenames? This will cause a leak.

**Comment by iammerrick** [comment]
@sokra  We don't. You can see our configuration here: https://gist.github.com/iammerrick/c3d3f0afd488c4e3223c3901e1b5f8a8

**Comment by iammerrick** [comment]
@sokra  thank you for your time btw.

**Comment by sokra** [comment]
maybe it was fixed by #2497

**Comment by TheLarkInn** [comment]
@iammerrick Please let us know if this improves things.

**Comment by iammerrick** [comment]
@TheLarkInn This fix like its only Webpack 2/Master is that correct?

**Comment by TheLarkInn** [comment]
This is on webpack@2.1.0-beta.21

**Comment by iammerrick** [comment]
@TheLarkInn Ok. Thanks.

**Comment by iammerrick** [comment]
Sad to report that putting this line in the 1.x branch this is not fixed. 
![image](https://cloud.githubusercontent.com/assets/109635/17945606/cf89bf48-6a01-11e6-9877-8ee1b60703a2.png)

**Comment by iammerrick** [comment]
I am going to tear out the Service Worker stuff till this gets ironed out, our development process has been crashing on memory every 45 minutes or so and unfortunately I couldn't iron down exactly where this leak was. Happy to try and help resolve it but for now I'm back-pedaling on this. Appreciate the help so far.
