### ISSUE TITLE
feat request: ProvidePlugin property import

### ISSUE THREAD

**Issue by Delagen** [webpack/webpack#2864]
I think it will be suitable to provide version of expression to ProvidePlugin to import PROPERTY of module

For example:

```
 new webpack.ProvidePlugin({
                'variable': ["npm-module","variable"]
            })
```

in this case it is resolved as require("npm-module")["variable"]

**Webpack version:**
2 latest NPM

**Please tell us about your environment:**
Windows 10

**Comment by Delagen** [comment]
And how to use Provide plugin for modules in external NPM modules, seems it skip it parsing

**Comment by sokra** [comment]
Similar bahavior is used in the library/libraryTarget code and could be reused...
