### ISSUE TITLE
UTF-8 Byte-Order-Mark BOM issue

### ISSUE THREAD

**Issue by JasonGoemaat** [webpack/webpack#2868]
**I'm submitting a bug report**
BOM (byte order mark) from UTF-8 files are included in the bundle causing 'unexpected token' errors.

**Webpack version:**
2.1.0-beta.20 (problem doesn't exist with Webpack 1.1.13)

**Please tell us about your environment:**
Windows 10

**Current behavior:**
Using private node modules created from wijmo 3rd party library that contains javascript files with BOM, the BOM is included in the middle of the bundle causing an error: 'Invalid or undexpected token'.  That's the weird characters after __WEBPACK_AMD_DEFINE_RESULT below:

/**_/ },
/_ 775 */
/***/ function(module, exports, **webpack_require**) {

var **WEBPACK_AMD_DEFINE_ARRAY**, **WEBPACK_AMD_DEFINE_RESULT**;ï»¿/*
    *

**Expected/desired behavior:**
Only the text of the file should be included, not the byte order mark
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.** 
  Sorry I can't provide the node module since it contains code from a 3rd party, and am unsure how to create a sample node module that is a library...
- **What is the expected behavior?**
  When reading any file, the byte order mark should not be included in the output.
- **What is the motivation / use case for changing the behavior?**
  I don't think there's a reason to include the BOM, and it can cause errors depending on how a file is saved.
- **Browser:** all
- **Language:** Typescript importing from Javascript

**Comment by MikeMatusz** [comment]
I'm seeing this, too (Windows 8, Webpack 2.4.1).  For me it's appearing in a bundle at the beginning of the bootstrap-slider library.  What's strange is that I didn't have any issues with the library initially, and then I started trying to use a couple new plugins (CleanWebpackPlugin, HtmlWebpackPlugin), removed a CommonsChunkPlugin instance that was no longer needed, and maybe something else, and then it started showing up, and persisted even after rolling back my changes.

**Comment by Inateno** [comment]
Anything about this ? I'm facing the same issue and don't found any fix.

Thx

**Comment by ooflorent** [comment]
Could someone create a gist or a repository to reproduce the issue?

**Comment by franklin-ross** [comment]
[Here you go](https://github.com/franklin-ross/webpack-issue-2868-repro). Just clone that, run `npm install`, then `npm run build`, then open `index.html` in Chrome.

For me on Windows 10, that produces a console error in Chrome like this: 
![image](https://user-images.githubusercontent.com/2695677/36137452-6f7f1914-10e9-11e8-9a8e-bfd8cbdfe679.png), and this kind of thing in the code 
![image](https://user-images.githubusercontent.com/2695677/36137475-926d4e46-10e9-11e8-878f-d05f89700408.png).

I recreated it by saving `src/bom.js` as UTF-8 with BOM, while `src/index.js` is UTF-8 without a BOM.

**Comment by adamcarr** [comment]
I am seeing this issue intermittently. Is there active work being done to fix this? Change the encoding type to UTF-8 fixes the issue.

**Comment by Bikeman868** [comment]
I am still experiencing this issue in 2021.
It looks like I only see this when mode=development. I have not been able to reproduce the problem with mode=production.
