### ISSUE TITLE
Symbol.hasInstance not working as expected.

### ISSUE THREAD

**Issue by trusktr** [webpack/webpack#2870]
**I'm (possibly) submitting a bug report**

**Webpack version:**
1.12.2

**Please tell us about your environment:**
OSX 10.10.2

**Current behavior:**
I have the following code:

```js
class A {
    static [Symbol.hasInstance] (instance) {
        console.log('custom instanceof check!', instance)
        return false
    }
}

class B extends A { constructor() {super()} }

class C extends B { constructor() {super()} }
class D extends B { constructor() {super()} }

let c = new C

console.log('should be false and not using custom hasInstance:', c instanceof D)
console.log('should be true and not using custom hasInstance:', c instanceof B)
console.log('should be false due to custom hasInstance:', c instanceof A)
```

The phrase `custom instanceof check!` gets logged three times, once per `instanceof` check, which is unexpected.

**Expected/desired behavior:**

I thought that my custom `hasInstance` method should only be called a single time, at the `instanceof A` check.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.** 

To reproduce,

```sh
git clone git@github.com:trusktr/webpack.git
cd webpack
git checkout hasInstance-fails
npm install
npm start
```

then visit localhost:3000.

You should see output like the following:

```
custom instanceof check! C {}
should be false and not using custom hasInstance: false
custom instanceof check! C {}
should be true and not using custom hasInstance: false
custom instanceof check! C {}
should be false due to custom hasInstance: false
```

* **What is the expected behavior?**
We should see the `custom instanceof check!` output only one single time for the `instanceof A` check.

**Comment by trusktr** [comment]
I believe the problem here is that the prototype of a constructor is the constructor that it extends from, so in my example, function A is the prototype of function B, which is the prototype of function C, and so the property lookup on `C` finds the `hasInstance` method on function `A`.

This seems to be problematic. How should the `hasInstance` function on `A` be specified, considering that the person who wrote class `A` may not know if his class gets extended (in general, such an assumption cannot be made)?

**Comment by trusktr** [comment]
Question, should the native `instanceof` operator be looking for an *own* property symbol? Or should it be doing normal lookup like what happens currently? It seems like searching for *own* symbols (and not looking on the prototype chain) may possibly be more intuitive and easier to deal with.

For example, in my above code, I'd expect the `instanceof B` check to work as normal, and was not expecting it to look for the `hasInstance` of `A`.

**Comment by Kovensky** [comment]
http://www.ecma-international.org/ecma-262/7.0/#sec-instanceofoperator

`instanceof` is defined by using `GetMethod`, which eventually uses `[[Get]]`, which does walk up the prototype chain.

**Comment by trusktr** [comment]
@Kovensky That seems to be opposite of useful. It completely throws `instanceof` for all sub classes, which forces subclass authors to have to work around it.

Do you know a good workaround so that the custom `hasInstane` function operates only on the constructor that it is assigned on, and otherwise works like the native `instanceof` with sub classes?

**Comment by Kovensky** [comment]
I think the idea is that any class that is special enough to have to implement its own `@@hasInstance` should also have special enough subclasses.

At any rate, it seems you can call `Function.prototype[Symbol.hasInstance]` as the default implementation, so you could either have the subclasses have their own `@@hasInstance` equal to that, or you could change the superclass' implementation to check if `this !== A` and call `Function.prototype[Symbol.hasInstance]` instead; but if you do that, then there is a problem if a subclass wants to use the superclass' `@@hasInstance`.

**Comment by trusktr** [comment]
@bebraw It's actually not a bug, and you guys can close it. I was just making  the wrong assumption about how `@@hasInstance` works, but it works like it's supposed to.

@Kovensky The problem with that is that then the author of a subclass of a subclass of a subclass of a subclass has to go and see the internal parts of the base class. If a subclass author write a `hasInstance` function, it may be tempting to use `Function.prototype[Symbol.hasInstance].call(this, instance)` if `this !== subclassCtor`, which may be a wrong assumption. The subclass author might have to actually use `SomeSuperClass.prototype[Symbol.hasInstance].call(this, instance)`, but may not know which `SomeSuperClass` to actually use.

Would `super[Symbol.hasInstance]` be helpful here? I haven't tested that yet, but it would be [statically limited](https://esdiscuss.org/topic/the-super-keyword-doesnt-work-as-it-should) (just as much as using direct references to the other classes).

**Comment by trusktr** [comment]
Sometimes I am not able to reproduce this problem, and instead I have the exact same problem as in this [Meteor issue](https://github.com/meteor/meteor/issues/7645), where my `hasInstance` function is for some reason not defined even though I've defined it.
