### ISSUE TITLE
Documentation for shims?

### ISSUE THREAD

**Issue by wearhere** [webpack/webpack#2871]
**I'm submitting a feature request**

**Webpack version:**
1.13.1

**Please tell us about your environment:**
OSX 10.11.5

**Current behavior:**
Webpack's automatic shimming of Node built-ins is not documented [so far as I can tell](https://www.google.com/search?espv=2&q=webpack+shim&oq=webpack+shim&gs_l=serp.3..0i71k1l8.0.0.0.1514941.0.0.0.0.0.0.0.0..0.0....0...1c..64.serp..0.0.0.9gqCe882Img).

**Expected/desired behavior:**

* **What is the expected behavior?**

  It would be documented, specifically (my stabs at documentation follow the colons):

  * how it's triggered: you `require` a Node built-in or use a Node global anywhere in
     your input to Webpack
  * what modules/globals are shimmed: so far I have seen `os`, `crypto`, and `Buffer`
  * how to disable this shimming: define the module as an [external](https://webpack.github.io/docs/library-and-externals.html)
     or use `DefinePlugin` to wrap the `require` in a [dead branch](https://github.com/webpack/webpack/issues/99#issuecomment-24985486)

* **What is the motivation / use case for changing the behavior?**

  I'm actually not advocating changing the automatic shimming, I just think it should be documented. It can be very nice, but is somewhat surprising, and you might accidentally bundle a huge shim using code like:

  ```js
  var os = require('os');
  var crypto;
  if (os.platform() === 'browser') {
    crypto = window.crypto;
  } else {
    crypto = require('crypto');
  }
  ```

  not realizing that you need to either mark `'crypto'` as an external or `define`-out the latter branch.

  Also if the shims used aren't documented, it's not clear where you'd go to file bugs against them (is Webpack responsible for them per se?)
 
* **Browser:** all
 
* **Language:** all

**Comment by wearhere** [comment]
Some further niceties:

* It might also be nice for Webpack to log, in its build output, what modules were shimmed, just so the developer can double-check what they expected to happen.
* I think Webpack should suggest that developers use browser APIs where available rather than relying on the shims. For instance, [`SubtleCrypto`](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto) is almost equivalent to `crypto`, the former's use of promises aside. Developers can save 100kB of JS, and worry less about correctness, by using the browser's API.

**Comment by TheLarkInn** [comment]
@wearhere you mind posting this issue also on [Our new docs repo](https://github.com/webpack/webpack.io/issues/new). This will help us track it in both places.

**Comment by pksjce** [comment]
This issue was moved to webpack/webpack.io#153

**Comment by wearhere** [comment]
Thanks for copying this over @pksjce !
