### ISSUE TITLE
Webpack 2's parser does not support the es2017 `async` or `await`

### ISSUE THREAD

**Issue by Kovensky** [webpack/webpack#2872]
As webpack uses acorn, this depends on https://github.com/ternjs/acorn/issues/441, but it's possible https://github.com/MatAtBread/acorn-es7-plugin/ can be used to work around it for now.

async did not make it into es7, but as it is now stage-4, it will be in "es8" :)

If this was available right now, it would allow me to disable the `babel-plugin-transform-async-to-generator` in my code (replacing with `babel-plugin-syntax-async-to-generator` for historical reasons) and use the native async/await implementation in Edge 14. Chrome 54 (currently Canary) also already has a native implementation behind the `--harmony` flag.

An alternative could be to switch to babylon + babel-traverse instead, but that would be a pretty big change; and I'm not sure babylon + babel-types/babel-traverse are API stable yet.

**Comment by MatAtBread** [comment]
I have a working webpack 2 plugin for this case 
https://github.com/MatAtBread/webpack-async-await

**Comment by hzoo** [comment]
@Kovensky not sure what you mean if babylon is API stable?

**Comment by Kovensky** [comment]
@hzoo I was wondering more about babel-types/babel-traverse; since they're part of the monorepo, they "might be more concerned" with being useful to babel-core than with keeping API compatibility with third parties.

Though third party plugins rely on them indirectly, so I guess they should be stable enough for the life of babel 6.

**Comment by TheLarkInn** [comment]
@ariya has also mentioned Esprima as an option for the future, but for now we rely heavily on acorns parse delegations.

**Comment by matAtWork** [comment]
The https://github.com/MatAtBread/webpack-async-await plugin (which did this) stopped working, probably due to https://github.com/webpack/webpack/releases/tag/v2.1.0-beta.23. If anyone has a fix that'll stop me having to spend a day working out what changed, it'd be much appreciated.

**Comment by ShimShamSam** [comment]
What's the status on this?

**Comment by kristianmandrup** [comment]
"webpack-async-await@^1.1.0 works with webpack@2.1.0-beta.23, for versions prior to beta.23, use webpack-async-await@1.0.4"

**Comment by kristianmandrup** [comment]
Or check here: https://www.npmjs.com/package/babel-preset-es2017
