### ISSUE TITLE
Feature Request: Hot Reloading

### ISSUE THREAD

**Issue by patryk0605** [webpack/webpack#2874]
I believe it would be beneficial to add an option to watch for new files added so a restart of webpack is not necessary every time a file is created. Thanks!

**Comment by sokra** [comment]
That should work

**Comment by patryk0605** [comment]
Say I have a config : 


```js
{ 
    ...
    entry : {
         about : 'js/about.js',
    }
}
```


And I want to add another entry:



```js
{ 
    ...
    entry : {
         about : 'js/about.js',
         contact : 'js/contact.js',
    }
}
```


Currently, this requires restarting `webpack-dev-server`, which for a big project, can take several minutes.

Is there a way to do this without restarting webpack?

**Comment by sokra** [comment]
No, changing the config requires restarting.

**Comment by nkzawa** [comment]
In our project (https://github.com/zeit/next.js), we do this by patching webpack and enable to change entries dynamically without restarting dev-server.

@sokra no chance to support it natively ? If you are interested, I'll happily help to add the feature.

**Comment by avindra** [comment]
@nkzawa : When I saw that feature in next.js, I immediately wondered how you guys were doing it, because we had the same issue / were trying to do the same thing. I would love to understand what you guys did with next.js!

**Comment by nkzawa** [comment]
@avindra We wrote some plugins to monkey-patch webpack.
For example, https://github.com/zeit/next.js/blob/master/server/build/plugins/dynamic-entry-plugin.js is a plugin which adds `compiler.addEntry` and `compiler.removeEntry` methods, and they are called according to file changes like https://github.com/zeit/next.js/blob/master/server/build/plugins/watch-pages-plugin.js#L30.

These plugins are just dirty workarounds, so I want webpack to support this if possible.
