### ISSUE TITLE
Dedupe plugin IE8 compatiblity

### ISSUE THREAD

**Issue by Reggino** [webpack/webpack#2877]
**I'm submitting a bug report**

**Webpack version:**
1.13.1

**Please tell us about your environment:**
Windows / Internet Explorer 8 :cry: 

**Current behavior:**
`webpack.optimize.DedupePlugin` breaks build for IE8:

Error:

```
 Object doesn't support property or method 'slice'
```

Happens here: https://github.com/webpack/webpack/blob/90d537ef4ce1092f76bd02ee2a75838c67b809fc/lib/optimize/DedupePlugin.js#L156 

**Expected/desired behavior:**

```
Expected behaviour: build should work in IE8
Desired behaviour: customer should stop requesting IE8 support
```
- **Browser:**  IE8

**Comment by sokra** [comment]
After some discussion we decided for the following statement regarding IE8:

We don't support IE8 in webpack 2. IE8 is not supported by Microsoft and doesn't get security fixes. We think it's no responsible to allow web developers to build webapps which support IE8. They must break!
