### ISSUE TITLE
Generating bundles for several targets at once

### ISSUE THREAD

**Issue by andreypopp** [webpack/webpack#288]
It would be useful to generate bundles for several targets at once.

I need this to generate bundles both for `web` and `node` targets, one is to send to a browser, another is to evaluate in Node to pre-render UI on server (with React).

Reasons why generating them at once could be useful:
- Shared cache, increa
- Shared watchers

These two will lead to less work done by webpack and so compilation should be faster and allocate less resources (memory, fds).

**Comment by mik01aj** [comment]
@sokra is there any documentation on this feature? I couldn't figure out how to use it from the [chat log](https://gitter.im/webpack/webpack/archives/2014/06/10).

**Comment by jhnns** [comment]
@mik01aj Your `webpack.config.js` may export an array of configs instead of just a single config.
