### ISSUE TITLE
Webpack segmentation faults for newer versions of node-sass

### ISSUE THREAD

**Issue by zg** [webpack/webpack#2880]
I've been getting segmentation faults from Webpack for a project I work on. From what I have read, the cause of these segfaults is due to the version of `node-sass` being beyond version 3.4.2. By [downgrading](https://github.com/webpack/webpack/issues/2371#issuecomment-212907115) or [pinning](https://gitter.im/webpack/webpack?at=57b39ba2d65128415f9c2bc7) to 3.4.2, people have mitigated the segfaulting from reoccurring.

In the case of the developer who downgraded from 3.5.2 to 3.4.2, there are a [small number of changes](https://github.com/sass/node-sass/commits/v3.5.2) that were made to `node-sass` between these versions. It might be easier to pinpoint the offending change, though I'm not familiar enough with Webpack's internals to pinpoint what changes could be causing these segfaults.

**Comment by sokra** [comment]
report it to the sass-loader project
