### ISSUE TITLE
require.context and file watches

### ISSUE THREAD

**Issue by kamilkp** [webpack/webpack#2881]
**I'm submitting a bug report**

**Webpack version:**
1.10.x

**Please tell us about your environment:**
OSX 10.x

**Current behavior:**

If I use

```
var contextRequire = require.context('../', true, /\.html$/);
```

Webpack sets up watchers to rebuild (when executed in watch mode) if any file inside the `../` directory changes not just the ones matching the regex.

**Expected/desired behavior:**

Rebuild only when a file matching the context regex changes (i.e. only html files).

**Comment by alexander-akait** [comment]
Close in favor https://github.com/webpack/webpack/issues/6093
