### ISSUE TITLE
System.import(module) should not show a warning

### ISSUE THREAD

**Issue by hansl** [webpack/webpack#2883]
#### Webpack Version

2.1.0-beta.18
#### Environment

Any.
#### Current behavior

The following code actually generates a warning (obfuscation to prevent webpack from being too clever):

``` typescript
const module = ['a', '/', 'string'].join('');
System.import(module).then(function() { console.log('loaded'); });
```

The warning is the following:

```
WARNING in ./src/main.ts
2:0 Critical dependency: the request of a dependency is an expression
```

The problem is this code: ([link](https://github.com/webpack/webpack/blob/b0fffd50d35dd0eef734d189928c1ac4c5c9fb97/lib/dependencies/ContextDependencyHelpers.js#L27))

``` javascript
    if(param.isWrapped() && (param.prefix && param.prefix.isString() || param.postfix && param.postfix.isString())) {
        var prefix = param.prefix && param.prefix.isString() ? param.prefix.string : "";
        var postfix = param.postfix && param.postfix.isString() ? param.postfix.string : "";
        var prefixRange = param.prefix && param.prefix.isString() ? param.prefix.range : null;
        var valueRange = [prefixRange ? prefixRange[1] : param.range[0], param.range[1]];
        var idx = prefix.lastIndexOf("/");
        var context = ".";
        if(idx >= 0) {
            context = prefix.substr(0, idx);
            prefix = "." + prefix.substr(idx);
        }
        var regExp = new RegExp("^" +
            prefix.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g, "\\$&") +
            options.wrappedContextRegExp.source +
            postfix.replace(/[\-\[\]\/\{\}\(\)\*\+\?\.\\\^\$\|]/g, "\\$&") + "$");
        dep = new Dep(context, options.wrappedContextRecursive, regExp, range, valueRange);
        dep.loc = expr.loc;
        dep.prepend = param.prefix && param.prefix.isString() ? prefix : null;
        dep.critical = options.wrappedContextCritical && "a part of the request of a dependency is an expression";
        return dep;
    } else {
        dep = new Dep(options.exprContextRequest, options.exprContextRecursive, options.exprContextRegExp, range, param.range);
        dep.loc = expr.loc;
        dep.critical = options.exprContextCritical && "the request of a dependency is an expression";
        return dep;
    }
```

Changing the import line to `System.import("" + module)` or `System.import(module + "")` fixes the problem.

The problem is that it checks if it has a prefix or suffix, but not if the expression has neither (and yet still valid). Having a single variable as an expression should be allowed without a warning.
#### Expected/desired behavior

No warning for the code above should be shown.

**Comment by hansl** [comment]
I think in general there's nothing wrong with having a `System.import` with an expression though. That's where `ContextReplacementPlugin` is useful.

**Comment by sokra** [comment]
Using the ContextReplacementPlugin should remove the warning...

**Comment by TheLarkInn** [comment]
https://github.com/angular/angular-cli/pull/1632/files#diff-a146e2d33c740fbf648803f29d27a81dR56

I pulled this down locally and was seeing this warning even with ContextReplacementPlugin being used. Would this not cover the case of where System.import() is being used?
