### ISSUE TITLE
install webpack@1.13.2 error: No compatible version found: node-libs-browser@^0.6.0

### ISSUE THREAD

**Issue by jaylone** [webpack/webpack#2886]
when I install webpack@1.13.2, it report error infomation below
`npm ERR! Darwin 15.5.0`
`npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "--registry=http://registry.npm.corp.qunar.com/" "--cache=/Users/wangchengyu/.npm/.cache/qnpm" "--userconfig=/Users/wangchengyu/.qnpmrc" "install"`
`npm ERR! node v4.4.7`
`npm ERR! npm  v3.10.6`

`npm ERR! No compatible version found: node-libs-browser@^0.6.0`
`npm ERR! Valid install targets:`
`npm ERR! 1.0.0, 0.5.3, 0.5.2, 0.5.1, 0.5.0, 0.4.3, 0.4.2, 0.4.1, 0.4.0, 0.3.1, 0.3.0, 0.2.1, 0.2.0, 0.1.2, 0.1.1, 0.1.0`
`npm ERR!` 
`npm ERR! `
`npm ERR! If you need help, you may report this error at:`
`npm ERR!     <https://github.com/npm/npm/issues>` 

it seem that  node-libs-browser version error in webpack package.json

code in webpack@1.13.1 package.json:
`"node-libs-browser": ">= 0.4.0 <=0.6.0",`

but code in webpack@1.13.2 package.json is below: 
`"node-libs-browser": "^0.6.0",`
it seem that node-libs-browser has no version "^0.6.0"

**Comment by Offirmo** [comment]
reported it: https://github.com/webpack/node-libs-browser/issues/43

**Comment by jaylone** [comment]
I found that **version 0.6.0** of node-libs-browser was not available on npm platform.

**Comment by Offirmo** [comment]
@jaylone it is on npm now. Maybe a DB replication glitch for some regions.

**Comment by jaylone** [comment]
![image](https://cloud.githubusercontent.com/assets/8166444/17774474/699b1e18-6586-11e6-95f6-3f0c23152a5f.png)

I saw this commit, maybe it is a bug for a long time.
