### ISSUE TITLE
CommonsChunkPlugin's Manifest Not Working

### ISSUE THREAD

**Issue by wlingke** [webpack/webpack#2887]
**I'm submitting a bug report**

**Webpack version:**
2.x

**Please tell us about your environment:**
Windows 10

**Current behavior:**
My configuration looks like so:

```
const config = () => ({
  context: config.paths.client(),
  entry: {
    app: ['./index'],
    vendor: ['react', 'react-dom']
  },
  output: {
    path: config.paths.build(),
    publicPath: config.paths.public(),
    filename: '[name].[chunkhash:8].js',
    chunkFilename: '[name].[chunkhash:8].chunk.js',
  },
  devtool: 'source-map',
  plugins: [
    new CleanWebpackPlugin([config.paths.build()], { root: __dirname }),
    new webpack.DefinePlugin(config.globals),
    new HtmlWebpackPlugin({
      inject: true,
      template: './index.html',
      // favicon: paths.appFavicon,
      minify: {
        removeComments: true,
        collapseWhitespace: true,
        removeRedundantAttributes: true,
        useShortDoctype: true,
        removeEmptyAttributes: true,
        removeStyleLinkTypeAttributes: true,
        keepClosingSlash: true,
        minifyJS: true,
        minifyCSS: true,
        minifyURLs: true,
      },
    }),
    new webpack.optimize.CommonsChunkPlugin({
      names: ['vendor', 'manifest'],
    }),
    new webpack.optimize.OccurrenceOrderPlugin(),
    new webpack.optimize.DedupePlugin(),
    new webpack.optimize.UglifyJsPlugin({
      compress: {
        warnings: false,
      },
    }),
  ],
  module: {
    loaders: [
      {
        test: /\.js/,
        loader: 'babel',
        exclude: /node_modules/,
        query: {
          babelrc: false,
          presets: [['es2015', { modules: false }], 'react'],
          plugins: [
            'transform-class-properties',
            'transform-object-rest-spread',
            'transform-react-constant-elements',
          ],
        },
      },
    ],
  },
});
```
If I add another `import React from 'react'` in another file that is part of the index.js tree, the compiled vendor.js hash changes.

Attached are two example outputs (I disabled uglify so it was easier to see the differences)
[vendors.zip](https://github.com/webpack/webpack/files/425978/vendors.zip)

**Expected/desired behavior:**
I would expect the vendor.js hash to remain the same and just the manifest.js hash to change.

* **What is the motivation / use case for changing the behavior?**
Long term caching
  
* **Language:** 
ES6/7

**Comment by wlingke** [comment]
I think this may be a webpack 2 issue. I tested a minimal configuration with webpack 1 and it worked as expected but when I upgraded to webpack 2, it did not work.

**Comment by Kovensky** [comment]
Does this still happen with https://github.com/szrenwei/inline-manifest-webpack-plugin ?

**Comment by wlingke** [comment]
The error is still there even with the inline plugin

**Comment by sokra** [comment]
You did not use records, as required for long term caching.

**Comment by wlingke** [comment]
That was it. thanks @sokra

**Comment by jasan-s** [comment]
@wlingke  can you post a code sample that you added since you got it working?

**Comment by wlingke** [comment]
@jasan-s There's too much other stuff in the config to post all of it here, but the parts that matter are:

```
//entry
entry: {
    app: ['./index'],
    vendor: ['react', 'react-dom', 'react-redux', 'react-router',
    'radium', 'rebass', 'redux', './polyfills'],
  },

```

```
//plugins
new webpack.optimize.CommonsChunkPlugin({
      names: ['vendor', 'manifest'],
    }),
new InlineManifestWebpackPlugin({
      name: 'webpackManifest',
    }),
```

```
recordsPath: config.paths.records(),
```

I'm running webpack 2 - but I remember this working with 1 too.

**Comment by wlingke** [comment]
@jasan-s It looks like you have all the components.. I would recommend reducing your config file to the most basic level and testing that. Maybe there's some logic error that's causing your config to not use the right parts in production.

**Comment by jasan-s** [comment]
thanks, adding a records path: to the records json file solved the problem.
