### ISSUE TITLE
Source map not loading on production

### ISSUE THREAD

**Issue by Fyre91** [webpack/webpack#2890]
I am using devtool as source-map and can see that the source maps are getting built. But in the network call on the production i am unable to see the source map or the better version of the script.

Is this something related to source map loading? It would be great if someone could describe how the source maps are loaded. Is it different from the way normally source maps are called.

**Comment by bebraw** [comment]
Can you provide more information so that the issue can be reproduced?

**Comment by SpaceK33z** [comment]
@Fyre91 do you still have this issue and if so, could you try the latest webpack version?
