### ISSUE TITLE
multiple-entry-points example error

### ISSUE THREAD

**Issue by es6Test** [webpack/webpack#2891]
**I'm submitting a bug report**

When running webpack on the multiple-entry-points example I get an error

**Webpack version:**
2.1.0-beta.21
OSX 10.x 

**Current behavior:**
`TypeError: chunk.hasRuntime is not a function
    at /Users/me/WebstormProjects/webpack/lib/optimize/CommonsChunkPlugin.js:89:20`

**Expected/desired behavior:**
No error

**Comment by TheLarkInn** [comment]
@es6Test Please provide an example of your configuration if possible. This will help us narrow down the source of the issue.

**Comment by es6Test** [comment]
I was just trying to run the example in the webpack repo.

**Comment by TheLarkInn** [comment]
Could you also provide what node version you were running?

**Comment by es6Test** [comment]
v6.4

**Comment by TheLarkInn** [comment]
Have you considered running this in v6. Just curious what the results is.

**Comment by wshiqtb** [comment]
I also met the same problem,
My node version is V4.4.0

**Comment by wshiqtb** [comment]
@es6Test:
I get it!
The reason is that CommonChunksPlugin file is part of webpack 2.x.
Solution, install webpack@1.13.2 , then change webpack.config.js 
`var webpack = require("webpack")
new webpack.optimize.CommonChunksPlugin({options})
`
It is ok

**Comment by unlight** [comment]
For me issue is reproduced when using `webpack-stream`, but not as cli.
Version: `webpack@2.1.0-beta.21`

**Comment by sokra** [comment]
Looks like a version conflict. Always install webpack locally.

**Comment by thomas-p-wilson** [comment]
Experiencing the same issue as @unlight. Reproducible using `webpack-stream`, but not cli.

`webpack@2.1.0-beta.25`

**Comment by JustFly1984** [comment]
Experiencing the same issue as @unlight and @thomas-p-wilson. Reproducible using webpack-stream, but not cli.

webpack@2.1.0-beta.10

Node 7.0.0

**Comment by zhaoshengjun** [comment]
Remember to run 
```
npm link
```
or
```
yarn link
yarn link webpack
```
before you run the examples.

It should work.

**Comment by karolyi** [comment]
having the same issue here, reinstalling node_modules didn't help. subscribing for a possible solution

**Comment by wshiqtb** [comment]
@karolyi 
at the head of webpack.config.js wrote:
`var webpack = require("webpack");
var commonChunkPlugin = webpack.optimize.CommonsChunkPlugin;`,
then plugins option wrote by commonChunkPlugin variable:
`new commonChunkPlugin({
            name: 'common',
            filename: 'common.js'
        }),`

**Comment by csvan** [comment]
People who are having issues with `webpack-stream`, instead of `.pipe(webpack(myConfig))`, do: .pipi(webpack(myConfig, require('webpack'))`.
