### ISSUE TITLE
DllReferencePlugin / DllPlugin does not respect file extensions found in manifest.json

### ISSUE THREAD

**Issue by moo3** [webpack/webpack#2892]
**I'm submitting a bug report**
Let me know if I can submit a PR if this is accepted as an issue.

**Webpack version:**
1.13.1

**Please tell us about your environment:**
OSX 10.x 

**Current behavior:**
DllReferencePlugin does not respect the extensions of the resources listed in manifest while resolving. When the vendor DLL library contains resources of various types (extensions) they are not accessible in the Consuming project where DllReferencePlugin is used.

```
// vendor.config ////////////
...
resolve: {
     extensions: ['', '.js', '.html']
},
plugins: [
	new webpack.DllPlugin({
		path: path.resolve('./vendor.manifest.json'),
		name: 'vendor_dll'
	}),
]
...

// vendor.manifest.json ////////////
{
  "name": "vendor_dll",
  "content": {
     "./view/elements/icon.js": 1,
     "./template/elements/tooltip.html": 2
  }
}

// app.config ////////////
...
resolve: {
        extensions: ['', '.js', '.html']
},
plugins: [
        new webpack.DllReferencePlugin({
            scope: 'vendor',
            manifest: require('./libs/vendor.manifest.json')
        }
]
...

// app.controller.js ////////////
...
      var iconView = require('vendor/view/elements/icon');
      var tooltipTemplate = require('vendor/template/elements/tooltip')
...

```

With this setup, attempts to build simply fails citing **Module not found** error.
`Module not found: Error: Cannot resolve module 'vendor/template/elements/tooltip' in <file path>` 

The root cause seems to be these two points where extensions of the DLL nor the consuming app are never used while resolving resources from a manifest.

https://github.com/webpack/webpack/blob/master/lib/DllReferencePlugin.js#L19 - where the options or extensions information is not passed downwards to the _DelegatedPlugin_ which funnels it down to _DelegatedModuleFactoryPlugin_.

https://github.com/webpack/webpack/blob/master/lib/DelegatedModuleFactoryPlugin.js#L15 - where extensions are expected and when not found uses the default limited set of extensions (["", ".js"])

**Expected/desired behavior:**
* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.** 
Code sample is shown above. If a full example app is needed. Please let me know.

* **What is the expected behavior?**
Since resolve.extensions are defined in both DLL and the app - I expect `require('vendor/template/elements/tooltip')` to resolve normally since HTML is allowed in the extensions.

* **What is the motivation / use case for changing the behavior?**
When DLLs pack resources of various extensions, they are not available in the consuming app.
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
Build time issue.
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart | ...] 
ES5

**Comment by sokra** [comment]
Yep, it looks like I missed passing this down to the impl.

**Comment by sokra** [comment]
I think the best solution is to add an `extensions` option to the `DllReferencePlugin` and pass it down. Do you want to do a PR?

**Comment by moo3** [comment]
Thanks for confirming. Sure I will, shortly.

**Comment by moo3** [comment]
PR merged

**Comment by developermj** [comment]
I think I am seeing this issue in Webpack 2.3.2. My webpack.config.js has the extensions option set on both the resolve.extensions and in the DllReferencePlugin options but my .ts files are not resolving. Any thoughts?
