### ISSUE TITLE
--watch changes in many files and folders

### ISSUE THREAD

**Issue by alexey2baranov** [webpack/webpack#2893]
Hello!

we have this webpack config for our project
```
module.exports = {
    entry: './src/index.js',
    output: {
        path: './bin',
        filename: 'index.webpack.js'
    },
    devtool: 'eval',
    watch: true,
    module: {
        loaders: [
            { test: /\.json$/, loader: 'json', },
            { test: /\.md$/, loader: "html!markdown" },
            { test: /\.js$/, loader: 'babel' }
        ]
    },
};
```

as we can see --watch option webpack rebuild entry point (./src/index.js) well each time index.js changed. But this index.js requires many other .js files from ./model, ./app and other folders. My question is how we can configure webpack to watch changes **in all this folders**?

Thanks!

**Comment by sokra** [comment]
It should do this automatically.
