### ISSUE TITLE
Error when trying to bundle typehead.js library

### ISSUE THREAD

**Issue by acrolink** [webpack/webpack#2896]
I had installed typehead,js library using bower and when I try to include it in the output (require it), the bundling fails and I get this error message:

`ERROR in ./~/node-libs-browser/~/timers-browserify/main.js
Module not found: Error: Cannot resolve module 'process/browser.js' in /srv/my_app/node_modules/node-libs-browser/node_modules/timers-browserify
 @ ./~/node-libs-browser/~/timers-browserify/main.js 1:15-44
`

**Comment by TheLarkInn** [comment]
Please fill out the information so kindly/helpfully provided to you on the github issue template seen [here](https://github.com/webpack/webpack/issues/new)
