### ISSUE TITLE
Allow marking an entry point as ignored during incremental builds.

### ISSUE THREAD

**Issue by d-ph** [webpack/webpack#2897]
**I'm submitting a feature request**

**Webpack version:**
1.10.x/2.x

**Please tell us about your environment:**
VM with linux

**Expected/desired behavior:**

S1. User uses this webpack config:

``` javascript
(...)

    entry: {
        'site-document-head': './src-frontend/ts/site/site-document-head.ts',
        'site-vendors': { path: './src-frontend/ts/site/site-vendors.ts', ignoreDuringIncrementalBuild: true },
        'site-main': './src-frontend/ts/site/site-main.ts'
    },

(...)
```

S2. User runs `webpack watch`
S3. Webpack builds all 3 entry points.
S4. Webpack discovers, that there is an entry point marked as `ignoreDuringIncrementalBuild: true`.
S4.1. Webpack creates an in-memory ignore list.
S4.2. Webpack populates that lists with all modules, that are reachable from the 'site-vendors' entry point (this in-memory ignore list serves the same purpose as DllPlugin's manifest file).
S5. Webpack enters into watch mode.
S6. User changes some source files, that are reachable by the 'site-main' entry point, and that `require()` some code, that is reachable from 'site-vendors'.
S7. User saves the files.
S8. Webpack detects files change.
S9. Webpack rebuilds 'site-main'.
S9.1. Webpack parses and rebuilds all modules reachable from 'site-main'.
S9.2. Webpack completely ignores all modules, that are reachable from 'site-main', but that are on the in-memory ignore list (this is the same behaviour as DllReferencePlugin's).
S10. User changes some source files, that are reachable by the 'site-vendors' entry point.
S11. Webpack does nothing.

Result: Faster incremental builds, because Webpack doesn't try to parse and follow dependency tree of the vendors' code.
- **What is the motivation / use case for changing the behavior?**

This solution is basically what DllPlugin/DllReferencePlugin does, but with these advantages:
1. It doesn't require maintaining 2 separate webpack config files.
2. It doesn't increase the complexity of the built app (no "library" part of the app).
3. It doesn't introduce any of the DllPlugin's problems, like:
   
   a) problems with code, that need to be imported before the "libraried" code, but that use the same dependencies as some of the "libraried" code (webpack compiles, but the built app doesn't work, because it assumes, that the "libraried" code is loaded first). This is the biggest problem and a show stopper with DllPlugin/DllReferencePlugin idea. It just doesn't work when these "libraried" code and the app code have some common dependencies and when the app code MUST run first (e.g. shims or bluebird (which is also a shim)).
   b) problems with shims, that can't shim the "global namespace"
   c) problems with source maps, when code outside of the "libraried" code tries to use the `expose-loader` on any of the "libraried" code.

The only reason, why people use DllPlugin/DllReferencePlugin, is to speed up incremental builds. With the presented solution implemented, you could deprecate the DllPlugin/DllReferencePlugin then, which would decrease the maintenance effort of the community.
- **Browser:** [ all ] 
- **Language:** [ all ]

**Comment by d-ph** [comment]
I took a look at how this could be done and I came to realization, that this probably can't be done (beyond what's already done with caching and so on). So feel free to close this ticket as wont-fix.

I don't know why I get better incremental build time performance, when using `DllPlugin` than when using `CommonsChunkPlugin`. In principle, they both should "cache" the chunks, that wasn't edited. Both of these do decrease the incremental build time, though. I guess I will just use the `CommonsChunkPlugin` for now.

**Comment by TheLarkInn** [comment]
DllPlugin however, will pre-bundle the vendors and when referenced in your app webpack config, will then ignore them and treat them as externals. Thus not 'processing' them.

**Comment by d-ph** [comment]
Yeah. This is what I'm after. To inform webpack, that it should not process any modules, that are reachable from an entry-point.
I put some thought on it yesterday, and realized, that we wouldn't need any new parameters in the config (i.e. the suggested `ignoreDuringIncrementalBuild: true`), because this:
```javascript
new webpack.WatchIgnorePlugin([
    path.resolve('node_modules')
]),
```
already conveys the idea, that any module, that sits in node_modules, should be watch-ignored. Currently, this config says, that webpack should not watch any of the files in the specified directory (reducing fs watch count, which reduces cpu usage). I think, that this config should go one step further and remove the specified modules from the modules count during the watch mode. E.g. by treating them as "external".

I might be missing something obvious here.

**Comment by d-ph** [comment]
Closing, because I'm fine with the latest webpack's performance. I also started running webpack from my host machine, instead of my vm with linux, which I guess also contributed to the performance.

**Comment by TheLarkInn** [comment]
Thank you very much for the timely response @d-ph
