### ISSUE TITLE
Unused classes in export remain in bundle even after tree-shaking

### ISSUE THREAD

**Issue by blacksonic** [webpack/webpack#2899]
**I'm submitting a bug report**

**Webpack version:**
2.1.0-beta.21

**Please tell us about your environment:**
Linux

**Current behavior:**

I have a class named Car in the [file car.ts](https://github.com/blacksonic/typescript-webpack-tree-shaking/blob/master/app/car.ts) and two other classes for the engines in another [file engine.ts](https://github.com/blacksonic/typescript-webpack-tree-shaking/blob/master/app/engine.ts).
car.ts

```
import { V8Engine, Engine } from './engine';

class SportsCar {
  constructor(private engine: Engine) {}

  toString() {
    return this.engine.toString() + ' Sports Car';
  }
}
```

engine.ts

```
export interface Engine {
  toString(): string;
}

export class V6Engine implements Engine {
  toString() {
    return 'V6';
  }
}

export class V8Engine implements Engine {
  toString() {
    return 'V8';
  }
}

export function getVersion() {
  return '1.0';
}

console.log(new SportsCar(new V8Engine()).toString());
```

The car.ts file only imports the V8Engine class, but the V6Engine class also appears even in the minified file. The unused function i export from engine.ts is stripped.

When running Webpack without UglifyJS plugin, the V6Engine class is marked with `/* unused harmony export V6Engine */` as expected.
But after adding the plugin i get this warning message from UglifyJS:

```
    WARNING in car.prod.bundle.js from UglifyJs
    Dropping unused function getVersion [car.prod.bundle.js:89,9]
    Side effects in initialization of unused variable V6Engine [car.prod.bundle.js:73,132]
```

I have [created a repository](https://github.com/blacksonic/typescript-webpack-tree-shaking) where the problem can be reproduced.
Cloning, installing and running `npm run webpack` and `npm run webpack-prod` reproduces the issue.

Don't know if this is a bug with the Typescript transpilation, UglifyJS or the orchestration of these tools.
I'm using Typescript with es2015 modules and Webpack 2.

**Expected/desired behavior:**

The unused class should be removed in the minified file.
- **What is the motivation / use case for changing the behavior?**
- **Browser:** all 
- **Language:** TypeScript 2.0-dev

**Comment by blacksonic** [comment]
can be caused by also https://github.com/mishoo/UglifyJS2/issues/1261

**Comment by TheLarkInn** [comment]
I left @mishoo a message asking if he needs any help. This is pretty important to us and there is a large Typescript/Angular2 userbase.

**Comment by Kovensky** [comment]
If typescript uses an IIFE for initializing the variable, uglify won't know enough to tell it can exclude the function... :/

**Comment by TheLarkInn** [comment]
@Kovensky is it safe to say we should speak with the TS team about this? CC @mhegazy @danielrosenwasser

**Comment by TheLarkInn** [comment]
Hey @blacksonic it's not an ideal workaround but would you consider trying to see if you can do ts transpile es6=>es6 and then babel es2015(modules:false) and see if this works. Maybe the way babel transpiles the classes down will yield a more 'removable' result.

**Comment by blacksonic** [comment]
@TheLarkInn bad news, it doesnt work with babel either
[example repo](https://github.com/blacksonic/babel-webpack-tree-shaking)

**Comment by blacksonic** [comment]
Created also a ticket on the Babel repository to let them know this issue exists not only with Typescript.
https://phabricator.babeljs.io/T7566

**Comment by Kovensky** [comment]
Probably the simplest fix is to have webpack comment out the declaration itself, instead of just marking with `unused harmony export`, and hoping for the best that the user really did not write something like `export foo = (() => { console.log('exporting foo') })()`. That would, however, cause problems if the exported declaration, despite not being used by other modules, was still used internally.

**Comment by Kovensky** [comment]
Another possible complication is with static class fields that are initialized with an IIFE.

```js
class Foo {
  static bar = (() => { console.log('side-effect :(') })()
}
```

Removing the declaration of `Foo` will also remove the side-effect of the declaration.

**Comment by blacksonic** [comment]
We have a new kid on the block: [Babili](https://github.com/babel/babili), it can strip unused classes after bundling.
See [example here](https://github.com/blacksonic/babel-webpack-tree-shaking).
For now i only tried it with ES6 code, but it works. Only drawback it doesnt strip comments, but there is a ticket for that.
https://github.com/babel/babili/issues/67

We might just need a Webpack plugin for Babili.

**Comment by blacksonic** [comment]
Fixed the comments issue
https://github.com/blacksonic/babel-webpack-tree-shaking/commit/78fe0ec4760711dccd6d5c86d1cdd20a7bad6828

**Comment by lbialy** [comment]
Any updates on this guys'n'gals?

**Comment by xe4me** [comment]
any update on this ? 
My bundle is 8mg !
Ridiculous for a simple web form .

**Comment by haotangio** [comment]
Webpack 3 released, do we have any update for this critical issue?

**Comment by sokra** [comment]
uglifyjs introduced the `PURE` annotation. Typescript (or any transpiler) can help uglifyjs to detect side-effect free code by generating code with this annotation now.

**Comment by Koslun** [comment]
Uglify introduced the PURE annotation through [this issue](https://github.com/mishoo/UglifyJS2/issues/1261) which links to many other relevant issues, particularly to transpilers trying to implement adding this annotation, on the request of some of the active participants in previously mentioned issue.

The TypeScript issue to add the PURE annotation @sokra mentioned can be found in issue https://github.com/Microsoft/TypeScript/issues/13721, where it has also been fixed in currently still open PR https://github.com/Microsoft/TypeScript/pull/16631 scheduled for TypeScript version 2.5.

The difference in the TypeScript case is that they are instead adding `/** @class */` for each class rather than the `/*#__PURE__*/` Uglify is expecting for pure functions. Thinking it however should be pretty easy to replace one for the other using a loader or plugin.

So this should radically help tree-shake unused classes pretty well for enormous size reductions for some libraries. According to Igor Minar (Angular Core Member):
> It depends on the app but basically all classes down leveled by tsc are
retained by uglify without this fix. Our code is mostly classes, so is rxjs
and material. So you can do the math. We are talking double digits. 60-70%
in some cases.

So this is by far what I am looking forward to the most in the coming months on the Webpack/TypeScript front as an Angular developer.

Don't believe Babel has a milestone for adding this yet but that there might be a Babel plugin that can do this referenced in the corresponding issue for adding a PURE annotation: https://github.com/babel/babel/issues/5632.

Given that TypeScript 2.4 just got released I'm thinking it's at least 2-3 months until 2.5. So might be worth throwing Babel into the mix in the mean time if you can get it working.

**Comment by sokra** [comment]
Thanks for the great comment @Koslun

**Comment by Koslun** [comment]
Thanks @sokra :)

Will then add the update that [`@angular-devkit/build-optimizer`](https://github.com/angular/devkit/tree/master/packages/angular_devkit/build_optimizer) has been released. Which, among other things, supports annotating classes with `/*@__PURE__*/` so that Uglify can remove them, as described earlier in this thread.

This loader and plugin combo has also been integrated into version [1.3.0-rc.0](https://github.com/angular/angular-cli/releases/tag/v1.3.0-rc.0) of `@angular/angular-cli` with [this commit](https://github.com/angular/angular-cli/commit/9ec5b4e). Though there is a warning that it can break people's build it should be a very low hanging fruit for angular-cli users and hopefully work well with most other webpack & TypeScript projects using `@angular-devkit/build-optimizer` directly.

**Comment by kzc** [comment]
@Koslun The Uglify `/*@__PURE__*/` annotation works best with the `compress` option `passes=3`. The Angular project should consider adding it.

https://github.com/angular/angular-cli/blob/9ec5b4ed66637f3605c74be1637464a2b0e8d44d/packages/%40angular/cli/models/webpack-configs/production.ts#L100

**Comment by filipesilva** [comment]
@kzc I did not know that, will experiment with it. Thanks for the tip!

**Comment by filipesilva** [comment]
@kzc I had a go with that option and on a medium project I use for benchmarks and saw no change.

Can you elaborate on why those options work better together? In your experience, what's the range of improvement you have seen?

**Comment by kzc** [comment]
@filipesilva It depends on the code base. 

Here's an example of how `passes` can further reduce code with `/*@__PURE__*/` annotations: https://github.com/mishoo/UglifyJS2/issues/1261#issuecomment-285203500

`passes` is a general uglify `compress` option not specific to pure annotations:
```
$ cat ex1.js
var letter = {
    foo: function(a, b, c){ return String["fromChar" + b](c) },
    bar: "unused"
}.foo(null, "Code", 97)
```
```
$ bin/uglifyjs -V
uglify-js 3.0.26
```
```
$ bin/uglifyjs ex1.js -m -c
var letter={foo:function(r,o,n){return String["fromChar"+o](n)},bar:"unused"}.foo(null,"Code",97);
```
```
$ bin/uglifyjs ex1.js -m -c unsafe,passes=2
var letter="a";
```

**Comment by filipesilva** [comment]
@kzc thanks for the great explanation, I'll include this in the CLI.

**Comment by morlay** [comment]
we can use [babel-plugin]([https://github.com/morlay/babel-plugin-annotate-pure-call-in-variable-declarator]) to force annotate `#__PURE__` for call expression in variable declarator.

I feel, call expression in variable declarator should not have side effects. 

Maybe we can enable the feature in webpack by default.

**Comment by morlay** [comment]
Btw,
For now webpack@3.4.1 will transform 
```js
import { querystring } from "querystring"
```
```js
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0_querystring__ = __webpack_require__(247);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0_querystring___default = __webpack_require__.n(__WEBPACK_IMPORTED_MODULE_0_querystring__);
```
This will may require unused package, I think we should annotate `#__PURE__` to `__webpack_require__` in variable declarator

and just ignore
```js 
import  "xxx.styl" 
```

**Comment by sokra** [comment]
Regarding unused classes: Transpiles (typescript, babel) need to annotate these transpiled class and minimizers need to handle this. webpack isn't involved in this process (we already remove our reference to the export).

> This will may require unused package, I think we should annotate #__PURE__ to __webpack_require__ in variable declarator

The spec says side effects in this package need to be evaluated. Annotating it with PURE would be incorrect according to the spec. But webpack 4 allows to opt-in into more aggressive optimization, which will do that. It will remove the module from the bundle.

**Comment by mhegazy** [comment]
TypeScript 2.5 and later emits an `@class` comment on classes to inform minifiers that there are transpiled from an ES6 class. See https://github.com/Microsoft/TypeScript/issues/13721 for more details.
It is also worth nothing that to use this with uglify a string-replace plugin is needed to convert to `/** @class */` to `/*@__PURE__*/`. see https://github.com/mishoo/UglifyJS2/issues/2279 for more details.

**Comment by kzc** [comment]
Also worth noting that Babel 7 will emit `/*@__PURE__*/` annotations for class IIFEs.

https://babeljs.io/blog/2017/09/12/planning-for-7.0#pure-annotation-in-specific-transforms-for-minifiers

**Comment by kimamula** [comment]
@kzc I found that if I build @blacksonic's example with webpack 4 using awesome-typescript-loader and `plugins: [new UglifyJsPlugin({ uglifyOptions: { compress: { passes: 3 } } })]`, unused classes can be tree-shaked.

Is this an expected behavior?

If yes, does this mean one does not need to use a string-replace plugin to tree-shake unused classes from TypeScript code as @mhegazy noted if they specify `{ compress: { passes: 3 } }`?

**Comment by kzc** [comment]
@kimamula If a `/*@__PURE__*/` annotation is already emitted for the class IIFE (via Babel 7 or other means) then a string replace step is not required.

**Comment by kimamula** [comment]
No, a `/*@__PURE__*/` annotation is not emitted.

To reproduce the behavior, uglify the following code (input.js)

```js
/******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};
/******/
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
/******/
/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId]) {
/******/ 			return installedModules[moduleId].exports;
/******/ 		}
/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			i: moduleId,
/******/ 			l: false,
/******/ 			exports: {}
/******/ 		};
/******/
/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
/******/
/******/ 		// Flag the module as loaded
/******/ 		module.l = true;
/******/
/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}
/******/
/******/
/******/ 	// expose the modules object (__webpack_modules__)
/******/ 	__webpack_require__.m = modules;
/******/
/******/ 	// expose the module cache
/******/ 	__webpack_require__.c = installedModules;
/******/
/******/ 	// define getter function for harmony exports
/******/ 	__webpack_require__.d = function(exports, name, getter) {
/******/ 		if(!__webpack_require__.o(exports, name)) {
/******/ 			Object.defineProperty(exports, name, {
/******/ 				configurable: false,
/******/ 				enumerable: true,
/******/ 				get: getter
/******/ 			});
/******/ 		}
/******/ 	};
/******/
/******/ 	// getDefaultExport function for compatibility with non-harmony modules
/******/ 	__webpack_require__.n = function(module) {
/******/ 		var getter = module && module.__esModule ?
/******/ 			function getDefault() { return module['default']; } :
/******/ 			function getModuleExports() { return module; };
/******/ 		__webpack_require__.d(getter, 'a', getter);
/******/ 		return getter;
/******/ 	};
/******/
/******/ 	// Object.prototype.hasOwnProperty.call
/******/ 	__webpack_require__.o = function(object, property) { return Object.prototype.hasOwnProperty.call(object, property); };
/******/
/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "";
/******/
/******/ 	// Load entry module and return exports
/******/ 	return __webpack_require__(__webpack_require__.s = 646);
/******/ })
/************************************************************************/
/******/ ({

/***/ 646:
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
Object.defineProperty(__webpack_exports__, "__esModule", { value: true });
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__export_class__ = __webpack_require__(73);

var SportsCar = /** @class */ (function () {
    function SportsCar(engine) {
        this.engine = engine;
    }
    SportsCar.prototype.toString = function () {
        return this.engine.toString() + ' Sports Car';
    };
    return SportsCar;
}());
console.log(new SportsCar(new __WEBPACK_IMPORTED_MODULE_0__export_class__["a" /* V8Engine */]()).toString());


/***/ }),

/***/ 73:
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
/* unused harmony export V6Engine */
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "a", function() { return V8Engine; });
/* unused harmony export getVersion */
var V6Engine = /** @class */ (function () {
    function V6Engine() {
    }
    V6Engine.prototype.toString = function () {
        return 'V6';
    };
    return V6Engine;
}());

var V8Engine = /** @class */ (function () {
    function V8Engine() {
    }
    V8Engine.prototype.toString = function () {
        return 'V8';
    };
    return V8Engine;
}());

function getVersion() {
    return '1.0';
}


/***/ })

/******/ });
```

with

```sh
$ npx uglifyjs -c passes=3 -- ./input.js
```

and

```sh
$ npx uglifyjs -- ./input.js
```

and compare the results (I am using uglify-es 3.3.9).
You can find `return"V6"` in the output of the latter but not in that of the former.

**Comment by kimamula** [comment]
@kzc I found your [comment](https://github.com/mishoo/UglifyJS2/issues/1261#issuecomment-362741305) mentioning this behavior.

Replacing `/** @class */` in JS code transpiled from TS with `/*@__PURE__*/` is still required for an effective tree shaking?

**Comment by chen86860** [comment]
The same as me, Could someone can help me :(
