### ISSUE TITLE
How to start indexes of modules at zero for each chunk?

### ISSUE THREAD

**Issue by Riim** [webpack/webpack#2904]
Sorry, translated with translate.google.ru

On change in one chunk there is a shift many indexes in many chunk. This leads to a large [diff](https://github.com/Riim/opal-components/commit/d72e4184ef90cdd26e881459c6e67d4f300c5bbd#diff-7b1ff1daf784795d4cb1c4c69f9bc723L71), and changes to a file that does not change the source code.

Why not count the index of modules of each chank from zero?

Thanks.

**Comment by Kovensky** [comment]
I believe you need to use https://webpack.github.io/docs/configuration.html#recordspath-recordsinputpath-recordsoutputpath to save which chunk IDs were used for each module.

If you're using webpack 1, IIRC you also need https://webpack.github.io/docs/list-of-plugins.html#occurrenceorderplugin

**Comment by TheLarkInn** [comment]
Also important to mention that its necessary to have an empty "inline" `CommonsChunkPlugin`.

```
new CommonsChunkPlugin({
  minChunks: Infinity,
  name: "inline",
  filename: "inline.js"
});
```

**Comment by Kovensky** [comment]
@TheLarkInn why is that?

**Comment by Riim** [comment]
recordspath+occurrenceorderplugin -- exactly what is needed, thanks you.
