### ISSUE TITLE
Can't set export var variable use webpack2 ?

### ISSUE THREAD

**Issue by agileago** [webpack/webpack#2906]
**I'm submitting a bug report**

**Webpack version:**
2.x

**Please tell us about your environment:**
OSX 10.x

**Current behavior:**
it is different that  webpack2 module  resolving with babel. for example

`foo.js`

```javascript
export let uid = 0
```

`bar.js`

```javascript
import { uid } from 'a.js'

uid++
```

when use babel it is ok. but webpack2 tell me **Cannot set property a of #<Object> which has only a getter(…)**

**Expected/desired behavior:**

it should be the same behavior with babel

**Comment by Kovensky** [comment]
If it works with babel, it's a bug in babel. ES6 exports are immutable from outside.

**Comment by agileago** [comment]
yes. i mistake
