### ISSUE TITLE
can't support Object(es6)?

### ISSUE THREAD

**Issue by keyiis** [webpack/webpack#2907]
I am use webpack2.1.0-beta.15,when run my code i get error:Object.entries() is not a function.
below is babel config in webpack
```
{
        test: /\.js$/,
        exclude: /(node_modules|backup)/,
        loader: 'babel', // 'babel-loader' is also a legal name to reference
        query: {
          presets: ['es2015']
        }
      },
```

**Comment by Kovensky** [comment]
You need to `import 'babel-polyfill'` at the top of your entry point.

**Comment by keyiis** [comment]
@Kovensky when added babel-polyfill,Object.entries() work well,but sequelizer can't work(No any error message),
has conflict between babel-polyfill and sequelizer?

**Comment by keyiis** [comment]
i used core-js replace babel-polyfill,all work fine.
