### ISSUE TITLE
Subsequent compilation with cache does not call val-loader

### ISSUE THREAD

**Issue by Delagen** [webpack/webpack#2913]
**I'm submitting a bug report**

**Webpack version:**
2.x

**Please tell us about your environment:**
Windows 10

**Current behavior:**
```
cache:{},
loaders:    [{
							test:  ...,
							loader: "val-loader"
						}]
```
Loader called only at first compilation

* **What is the expected behavior?**
Loader called every compilation

* **What is the motivation / use case for changing the behavior?**
Webpack 1.x working fine
 
* **Browser:** all
 
* **Language:** ES5

**Comment by sokra** [comment]
webpack 2 caches by default (for performance reasons). If you want some uncached generated file, you need to write your own loader.
