### ISSUE TITLE
triggering a rebuild in --watch when an unbundled file changes (specifically, .env files)

### ISSUE THREAD

**Issue by Pomax** [webpack/webpack#2919]
We have a project in which the environment variables can be overruled by an `.env` file that is handled by [habitat](http://npmjs.com/package/habitat), and have a webpack config that runs with `--watch` during development that we would like to trigger when the `.env` file is changed. However, since the file is not bundled in through a `require` (nor should, since it controls the environment, which we don't strictly want bundled in), the standard test/loader instruction doesn't do much. 

Is there an established way to trigger a rebuild while webpack is in --watch mode based on a file change that we *know* affects the build but isn't itself strictly speaking bundled in?

**Comment by sokra** [comment]
Does it affect the build or the build configuration?

**Comment by Pomax** [comment]
it's an `.env` file with feature flag, login server, resource db, etc. etc values. All of them drastically affect the build.

**Comment by sokra** [comment]
I assume it only affects the build configuration. This is currently not supported, but you can use standard tools to restart the process when files changed.

**Comment by Pomax** [comment]
We can, and that takes quite a long time as opposed to a webpack-native rebuild (because it'll know which files need updating and which don't). However, if it's not supported, then that is not an option.

Is there an issue open for adding this in? If so, can that issue # be crosslinked into this one?

**Comment by sokra** [comment]
The problem is once the webpack configuration changes, it can change anything in the build. webpack can't rely on the cache anymore and would need to do a full build anyway.

**Comment by Pomax** [comment]
hm, that's a good point. I guess a workable solution would be having a `chokidar` task that looks at the `.env` file, and on changes runs a compile.js script that enriches process.env with the `.env` values and then writes those to some kind of `config.json` that *is* under webpack's control, so that it only does a partial rebuild.

**Comment by svicalifornia** [comment]
@Pomax Did you ever solve this issue?

**Comment by bornkiller** [comment]
@Pomax Any solution now?
