### ISSUE TITLE
small JS chunk files when using watch mode for non-CommonChunk plugged files

### ISSUE THREAD

**Issue by rafde** [webpack/webpack#2923]
# [feature request] small JS chunk files when using watch mode for non-CommonChunk plugged files

Webpack version:
1.13.x/2.x

environment:
OSX 10.11.5

Browser:all

Language: JS

Current behavior:
Creates large bundled initial and anonymous chunk js files in watch mode.

Expected/desired behavior:
Create small chunk js files, or generate one module per chunk file in watch mode to allow dev-tools to not blank screen or crash. CommonChunks can be excluded.

Motivation:
I moved the system I am working on from using RequireJS CommonJS (CJS), 1000+ files with `define(function(require) { … })`, implementation to Webpack for production bundling.

I am also using Chrome DevTools Workspace to edit my files while debugging.
RequireJS CJS worked great with Workspaces because the modules would localhost load one file at time. Editing a file while on a breakpoint in the browser was easy in this fashion. 

Since I transitioned production to use Webpack, I’ve wanted to move the development workflow towards Webpack watch mode so we could start using Babel, pre-compiled templates, and other code transformers. But Chrome will, understandably, blank screen or crash if a large file changes, which get created as large files because it makes chunks include all  dependencies that are `require`d files that export through`define(function(require) { … })` . This makes Webpack watcher a difficult workflow selling point.

I figure that the best approach to address this issue would be to do what dev RequireJS did, http request each individual module. This could also be done by creating smaller chunk files, or one module per chunk file.

At first, I was hoping AggressiveSplitPlugin would do the job, but that wasn’t fast enough in watch mode. Also, I read [This is production only, don't use it in development](https://github.com/webpack/webpack/issues/1223#issuecomment-232311846)

I’ve looked into implementing this via plugin or loader, but I ended up learning that https://github.com/webpack/webpack/blob/daf2f31233a9f2dc36f79162577a66e8b4eba622/lib/WebpackOptionsApply.js#L243-L247
made it difficult do it in either cases since those plugins seem to get in the way of accomplishing my goal by reading and transforming the `define(function(require){})` string before other plugins can start doing work. But I am probably mistaken since Webpack is a very intimidating source to read, which makes it difficult for me to follow and debug my attempts. Maybe even allow for a way to prevent passing those plugins by passing an option param so other plugins can get a chance to implement bundling optimizations, etc.

:bow: Thanks for reading and making bundling easy. :bow:

**Comment by sokra** [comment]
Have you tried the `devtool` option?

**Comment by rafde** [comment]
@sokra this is my bare and rough minimum dev config (excluded module, resolve, and other plugins like Provide)
```js
// webpack.config.js for dev workflow
'use strict';
var path = require('path');
var baseDirectory = __dirname; //js
var buildPath = path.resolve(baseDirectory, './bundles');
var webpack = require('webpack');
// updates sourcemap path
function moduleFilenameString(info) {
  var resourcePath = info.resourcePath;

  if (resourcePath.indexOf('~/') >= 0) {
    return resourcePath.replace('../~', '/node_modules');
  }
  
  if (resourcePath.indexOf('../') >= 0) {
    return resourcePath.replace('../', '/');
  }
  
  if (resourcePath.indexOf('./') === 0) {
    return resourcePath.replace('./', '/js/');
  }
  
  return info.resourcePath;
}

module.exports = {
  context: baseDirectory,
  entry:{
    entry1:['./route1.js'],
    entry2:['./route2.js'],
    entry3:['./route3.js']
  },
  plugins: [
    new webpack.optimize.CommonsChunkPlugin({
      name: 'libs',
      minChunks: function(module){
        var userRequest = module.userRequest;
  
        if (typeof userRequest !== 'string') {
          return false;
        }
        // putting all external libs that are getting
        // required by internal modules
        return userRequest.indexOf('/node_modules/') >= 0;
     }
    })
  ]
  output: {
    filename: '[name].local.js',
    chunkFilename: '[name].local.js',
    path: buildPath,
    publicPath: '/js/bundles/'
  },
  debug: true,
  devtool: 'inline-source-map',
  // Attempt to source map to corresponding source file
  // when modules are duplicated across different chunks
  // Doesn’t work in some cases, doesn’t affect mapping.
  devtoolModuleFilenameTemplate: moduleFilenameString,
  devtoolFallbackModuleFilenameTemplate: moduleFilenameString
};
```

Command
`webpack --watch --profile --progress --display-chunks --display-modules --display-reasons --display-error-details --display-exclude --config js/webpack.config.js`

A lot of the files (1000+) I am working with start 
```js
define(function(require){
//...
});
```
which is great for production, doesn't work out for development.

**Comment by rafde** [comment]
So I learned that what I am looking for was https://github.com/webpack/bundle-loader or https://github.com/NekR/async-module-loader which I can't get working for other reasons. But this kinda of a start I was looking for. Closing.
