### ISSUE TITLE
FEATURE REQUEST for getting version

### ISSUE THREAD

**Issue by kentendo** [webpack/webpack#2930]
**I'm submitting a feature request**

I would like to get the version of webpack using `webpack -v` or `webpack --version`.

Currently I can only see the version by calling `webpack -h`  or `webpack --help`.

**Comment by TheLarkInn** [comment]
PR would certainly be appreciated! We'd be happy to help if you need guidance.

**Comment by kentendo** [comment]
Cool man....I'll give it a shot.

**Comment by kentendo** [comment]
Merged into master...
https://github.com/webpack/webpack/pull/2935
