### ISSUE TITLE
Confusing error message when asset file in wrong folder

### ISSUE THREAD

**Issue by GregS2** [webpack/webpack#2931]
**Feature request**

**Webpack version:**
1.13.2

**Environment:**
Windows 10

**Current behavior:**
Using the very simple project [here:](http://survivejs.com/webpack/developing-with-webpack/getting-started/) I had my index.js in the root folder instead of the /app folder. When I attempted to perform the build, the following very confusing error was displayed:

```
C:\webpack-demo>.\node_modules\.bin\webpack -display-error-details`
Hash: 861ec26824f86f50dc52
Version: webpack 1.13.2
Time: 927ms
     Asset       Size  Chunks             Chunk Names
index.html  127 bytes          [emitted]

ERROR in Entry module not found: Error: Cannot resolve 'file' or 'directory' C:\webpack-demo\app in C:\webpack-demo
Child html-webpack-plugin for "index.html":
        + 3 hidden modules
```

**Expected/desired behavior:**
A more helpful error message

**Comment by TheLarkInn** [comment]
@GregS2 Is this also an issue in webpack 2?
