### ISSUE TITLE
avoid boilerplate load code for single-bundle files

### ISSUE THREAD

**Issue by jippi** [webpack/webpack#2934]
**I'm submitting a feature request**

**Webpack version:**
2.x

**Current behavior:**
Single entry bundle still contain all the boilerplate for require components, not needed (?) when everything is one file

**Expected/desired behavior:**

A smaller bundle size since the `webpack__require` and friends can be omitted(?)

**Comment by sokra** [comment]
yep, part to the scope hoisting stuff will be a optimized runtime for single module bundles.

**Comment by jippi** [comment]
@sokra amazing ! :) do you have a guesstimate on when this could land? Q3 or Q4? Any "parent" issue i should follow for update on this?

I love webpack!

**Comment by TheLarkInn** [comment]
We know exactly when it will land @jippi: 

When we complete our [documentation milestone]( https://github.com/webpack/webpack.io/milestone/1), we then release webpack 2 without the `beta` tag. Once that is completed, we start development on Scope hoisting and optimizations.

**Comment by jippi** [comment]
@TheLarkInn thanks for the update!

**Comment by TheLarkInn** [comment]
As always, we are open to PR's however if you submit one, it _may_ take a bit for us to get back to you while we are focusing on our primary efforts.

**Comment by jippi** [comment]
@TheLarkInn I could give it a shot, though i know nothing about the internals of webpack - can you give me some pointers on how to approach it?

**Comment by sokra** [comment]
This is a difficult PR... better try issues tagged with `(PR)`.

**Comment by kentcdodds** [comment]
Ping. According to [the votes](https://webpack.js.org/vote/) this is the number 1 thing people want the webpack team working on. What do we need to do here?

**Comment by TheLarkInn** [comment]
We have this listed in our 2.4 milestone. Milestone we are on right now is 2.3. We have more PR's to land in master for perf, refactor, and then we start 2.4 which will contain our first feature from the voting list. 2.3 was added to ensure that we are not leaving behind any issues from dropping 2.2.

**Comment by jdb8** [comment]
Wondering if this is still in the works? I know that scope hoisting is now done, but it seems like single-bundle files still contain a fair amount of unnecessary boilerplate. For example, an entrypoint containing the one-liner `document.body.focus()` produces this output (without -p):

```
/******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};
/******/
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
/******/
/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId]) {
/******/ 			return installedModules[moduleId].exports;
/******/ 		}
/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			i: moduleId,
/******/ 			l: false,
/******/ 			exports: {}
/******/ 		};
/******/
/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
/******/
/******/ 		// Flag the module as loaded
/******/ 		module.l = true;
/******/
/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}
/******/
/******/
/******/ 	// expose the modules object (__webpack_modules__)
/******/ 	__webpack_require__.m = modules;
/******/
/******/ 	// expose the module cache
/******/ 	__webpack_require__.c = installedModules;
/******/
/******/ 	// define getter function for harmony exports
/******/ 	__webpack_require__.d = function(exports, name, getter) {
/******/ 		if(!__webpack_require__.o(exports, name)) {
/******/ 			Object.defineProperty(exports, name, {
/******/ 				configurable: false,
/******/ 				enumerable: true,
/******/ 				get: getter
/******/ 			});
/******/ 		}
/******/ 	};
/******/
/******/ 	// getDefaultExport function for compatibility with non-harmony modules
/******/ 	__webpack_require__.n = function(module) {
/******/ 		var getter = module && module.__esModule ?
/******/ 			function getDefault() { return module['default']; } :
/******/ 			function getModuleExports() { return module; };
/******/ 		__webpack_require__.d(getter, 'a', getter);
/******/ 		return getter;
/******/ 	};
/******/
/******/ 	// Object.prototype.hasOwnProperty.call
/******/ 	__webpack_require__.o = function(object, property) { return Object.prototype.hasOwnProperty.call(object, property); };
/******/
/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "";
/******/
/******/ 	// Load entry module and return exports
/******/ 	return __webpack_require__(__webpack_require__.s = 0);
/******/ })
/************************************************************************/
/******/ ([
/* 0 */
/***/ (function(module, exports) {

document.body.focus();


/***/ })
/******/ ]);
```

and with `-p`:

```
!function(n){function t(r){if(e[r])return e[r].exports;var o=e[r]={i:r,l:!1,exports:{}};return n[r].call(o.exports,o,o.exports,t),o.l=!0,o.exports}var e={};t.m=n,t.c=e,t.d=function(n,e,r){t.o(n,e)||Object.defineProperty(n,e,{configurable:!1,enumerable:!0,get:r})},t.n=function(n){var e=n&&n.__esModule?function(){return n.default}:function(){return n};return t.d(e,"a",e),e},t.o=function(n,t){return Object.prototype.hasOwnProperty.call(n,t)},t.p="",t(t.s=0)}([function(n,t){document.body.focus()}]);
```

As you can see, in both cases there seems to be additional code in the output bundle relating to ES modules and exports.

**Comment by jippi** [comment]
@TheLarkInn did this get lost in 2.x branch? :)

**Comment by jdb8** [comment]
This would still be really nice if there's a way it could be achieved without too much special-case logic, even though it's a bit of a niche usecase.

**Comment by noahbrenner** [comment]
Any update on this?

I thought I'd point out that it may not be as small of a use case as it seems. If you're using rollup, you may have several source files, but have them compiled into one before they're passed to webpack's bundling logic.

**Comment by evilebottnawi** [comment]
bump

**Comment by noahbrenner** [comment]
@TheLarkInn mentioned that this issue was in the 2.4 milestone. I'm having trouble finding that listed now. Did it get moved to a different milestone at some point?

**Comment by evilebottnawi** [comment]
@noahbrenner partially implemented for `webpack@5` for some cases

**Comment by noahbrenner** [comment]
@evilebottnawi Cool, thanks for the update! I'll be sure to check that out.

**Comment by sokra** [comment]
Fixed in webpack 5
