### ISSUE TITLE
Support module resolution which preserves symlinks (--preserve-symlink option in Node >= 6.3.0)

### ISSUE THREAD

**Issue by andreypopp** [webpack/webpack#2937]
**I'm submitting a feature request**

I think it would be useful (even if not have this the default behaviour) to be able to preserve symlinks when doing module resolution.

This should function the same as in Node >= 6.3.0 with `--preserve-symlinks` enabled. To quote docs on that:

> The --preserve-symlinks command line flag instructs Node.js to use the symlink path for modules as opposed to the real path.

More info in [Node.js docs](https://nodejs.org/api/cli.html#cli_preserve_symlinks).

**Comment by Meroje** [comment]
I could not get this to work, but before I open an issue, @andreypopp do you have a sample project showing this feature working ?

**Comment by vjpr** [comment]
@sokra Could we get a backport to `enhanced-resolve@~0.9`?

`create-react-app` depends on `webpack@1.13.2` which depends on `enhanced-resolve@~0.9` and when installing with `pnpm` to a global symlinked store (the fastest way to install deps currently and what yarn may support eventually).

**Comment by alolis** [comment]
@andreypopp, I am not sure, but has this been addressed?  `resolve` and `resolveLoader` didn't help i am afraid with my npm linked module which has two peer dependencies. I am still getting module error not found
