### ISSUE TITLE
Check for require: "function is used in a way in which dependencies cannot be statically extracted"

### ISSUE THREAD

**Issue by jublo** [webpack/webpack#2941]
**I'm submitting a bug report**

**Webpack version:**
1.13.1

**Please tell us about your environment:**
OS X 10.11.6

**Current behavior:**
./~/codebird/codebird.js
Critical dependencies:
1238:15-22 require function is used in a way in which dependencies cannot be statically extracted
@ ./~/codebird/codebird.js 1238:15-22

https://github.com/jublonet/codebird-js/blob/develop/codebird.js#L555

    } else if (typeof require === "function" && require) {

**Expected/desired behavior:**
No error should be seen.

* **What is the motivation / use case for changing the behavior?**
Checking if require is available should not cause this error.

**Comment by jublo** [comment]
See https://github.com/jublonet/codebird-js/issues/123

**Comment by sokra** [comment]
`} else if (typeof require === "function" && require) {`

rewrite it to

`} else if (typeof require === "function") {`

**Comment by jublo** [comment]
@sokra Thanks!

**Comment by stevenvachon** [comment]
I'm getting this error with this line:
```js
const broquire = require("broquire")(require);
```
