### ISSUE TITLE
Unexpected token in recordsPath (file corruption)

### ISSUE THREAD

**Issue by BabakMN** [webpack/webpack#2943]
Webpack: `1.13.1` on `Linux`

This is an initial bug report and I will provide additional information as necessary.

Problem: Webpack sometimes writes invalid JSON in the `records` file.

Here's a snippet showing the section where corruption happens (`}DOMContainerInfo.js`):

```json
  "nextFreeChunkId": 5,
  "chunks": {
    "byName": {
      "RenderServer": 0,
      "React": 1,
      "ReactRouter": 2,
      "Application": 3,
      "Axios": 4
    },
    "byBlocks": {}
  }
}DOMContainerInfo.js": 267,
      "../node_modules/react/lib/ReactDOMDebugTool.js": 268,
      "../node_modules/react/lib/ReactDOMEmptyComponent.js": 269,
```

This doesn't happen every single time. I delete the records file the first time it writes the file, on the second run the file gets larger, the third (or 4th or 5th) run it may become corrupt.

After that point webpack will say:
`SyntaxError: Cannot parse records: Unexpected token { in JSON at position 46313`

For context, I'm running a multi-compile of two compilations targeting `web` and `node`.

My gut feel tells me a race condition due to the multi-compile writing to the same file?

Edit: Hmm ... or I guess `recordsPath` MUST be different for each config object?

Edit: I have confirmed with unique `recordsPath` values for each config object corruption doesn't happen.

The client records file remains constant in size between different runs (25K) but the server records file gets larger on each run (115K increases by 5-10K every run). Not sure if that's normal/expected or if it's meant to remain constant.

**Comment by bebraw** [comment]
A standalone example would help to debug this I think.

**Comment by BabakMN** [comment]
Before I attempt to produce a standalone example I would like some clarification about the points below:

- When an array of objects is given to Webpack, must `recordsPath` in each one be a unique file? I assume yes.

- Is the size of the records file expected to remain the same between compilations (assuming nothing else has changed) or is it expected to grow in size?

**Comment by sokra** [comment]
> When an array of objects is given to Webpack, must recordsPath in each one be a unique file? I assume yes.

yes.

> Is the size of the records file expected to remain the same between compilations (assuming nothing else has changed) or is it expected to grow in size?

It should stay constant if nothing has changed. It can grow if you add and remove modules.

**Comment by trisys3** [comment]
I also ran into this. In my case, I had one config for site administrators and one ffor everyone else. I had the admin config extended from the user config and both used directly by different node servers, not an array form.

I don't completely understand if this is a race condition or what, but I get that we're doing something unexpected so unexpected things can and will happen.

It would still be nice to have this in the docs.
