### ISSUE TITLE
ES6 modules compatibility with commonjs

### ISSUE THREAD

**Issue by f0rr0** [webpack/webpack#2945]
**I'm submitting a bug report**

**Webpack version:**
2.1.0beta-21.0

**Please tell us about your environment:**
OSX 10.x

Can someone explain this to me. I am writing a library with `target: "node"` , `libraryTarget: "commonjs2"`  and `library: "jwt"`. 

From within my `src/index.js` file, I have multiple exports:

```javascript

export { a, b, c};

export default (d) => "e";

export const f = "g";
```

I consume this library in my project like:

```javascript

import jwt, { a, b, c, f } from "jwt";

```

However, `jwt` is set to the entire `module.exports` object rather than `module.exports["default"]`. Is this expected behavior or am I doing something wrong?

Note: I am not using Babel for any transpiling. This code is meant for `node >= 6.4.0`, so it can't be a Babel issue.

**Comment by sidjain26** [comment]
Using `transform-es2015-modules-commonjs` results in the expected behavior. But that defeats the point of using native modules and webpack for tree shaking. Another thing I noticed is, webpack does not set `__esModule` flag on transpiled ES6 modules. This breaks functionality. See:
https://github.com/esnext/es6-module-transpiler/issues/86
https://github.com/Microsoft/TypeScript/issues/2719
https://github.com/markdalgleish/static-site-generator-webpack-plugin/issues/46#issuecomment-241088084

**Comment by sidjain26** [comment]
@bebraw I believe you should escalate the priority to something more important than "important" as this is absolutely critical to maintain consistency across different module formats and with other transpilers.

**Comment by TheLarkInn** [comment]
@sidjain26 I would like to you to confirm something for me as well. I believe we are coming across this via webpack@2.1.0-beta.21 and Angular RC6. Would you be please willing to downgrade to webpack@2.1.0-beta.19 and confirm that this is still a problem on this version? 

If it is not, (which I am seeing the same behavior) then we might be seeing the same bug.

**Comment by sidjain26** [comment]
@TheLarkInn I see the same behavior with `2.1.0-beta.19`. Made a repository to reproduce it at - https://github.com/sidjain26/webpack-bug. Do
```
npm start # in ./consume
```

**Comment by sokra** [comment]
`__esModule = true` need to be set only on library export. `__esModule` need to be set on the exports of the entry module.

Workaround:

`export const __esModule = true` in entry module.

**Comment by TheLarkInn** [comment]
Thank you for the work around. Will test.

**Comment by sidjain26** [comment]
@sokra Workaround fits in nicely for now, maybe this should be mentioned in the docs somewhere until it is fixed

**Comment by TheLarkInn** [comment]
Please instead wait for a release to be cut instead. If you are using the angular-cli reach out on their gitter or github for ways to workaround the issue.

**Comment by sokra** [comment]
I added a new `libararyTarget` `"commonjs-module` which represents a harmony/ES6 module which is wrapped via CommonJs (`__esModule`).

**Comment by kevinSuttle** [comment]
But what about within the webpack.config.js file itself? 

e.g.

Webpack 2 "supports ES6 modules", but you cannot `import` or `export`.

**Comment by f0rr0** [comment]
@kevinSuttle try renaming it to `webpack.config.babel.js` and make sure you include `babel-register` in your project.

**Comment by MrCoder** [comment]
@sokra adding `libraryTarget: 'commonjs-module'` does not work for me.

**Comment by sBaASBAA** [comment]
__WEBPACK_IMPORTED_MODULE_1__ionic_native_paypal__
I am getting this error if integrated paypal in ionic .
Please help me to solve this issue
