### ISSUE TITLE
Dynamic require("folder/file.svg?fill=" + myColor) doesn't work

### ISSUE THREAD

**Issue by pke** [webpack/webpack#2947]
**I'm submitting a bug report**

I want to dynamically require an SVG file. The `resourceQuery` that the `svg-fill-loader` uses should come from a variable value. The variable value is `const` so it is known at compile time. All webpack should have to do is resolve the `COLORS.main` during compile time and create the final required filename.

```es6
import { COLORS } from "colors"
const mySVG = require("images/my.svg?fill=" + COLORS.main)
```

**Webpack version:**
1.13.1

**Please tell us about your environment:**
Windows 8.1

**Current behavior:**

The file cannot be resolved during runtime.
`Module "images" not found`.

Compiler output is:
`[1298] ./products/xxx/images ^\.\/my.svg\?fill=.*$ 160 bytes {0} [built]`

**Expected/desired behavior:**

I expected the dynamic import to return the path to the compiled SVG.

**Comment by sokra** [comment]
> All webpack should have to do is resolve the COLORS.main during compile time and create the final required filename.

Too complex. webpack is a static bundler.

Won't fix
