### ISSUE TITLE
There is a error of  '$ is not a function', when I package jquery-1.9.1.min.js

### ISSUE THREAD

**Issue by treadpit** [webpack/webpack#2948]
I package jquery-2.2.4.min.js, everthing is well, but when I use jquery-1.9.1.min.js, there is a error in browser console

> Uncaught TypeError: $ is not a function

webpack.config.js:
```

plugins: [
  new webpack.ProvidePlugin({
     $: 'jquery',
     jQuery: 'jquery'
  })
],

alias: {
    "jquery": path.join(__dirname, "src/js/lib/jquery-1.9.1.min.js")
}
```
Is there any way to solve it?

**Comment by sokra** [comment]
Use stackoverflow
