### ISSUE TITLE
require.context() falls into symlink cycles

### ISSUE THREAD

**Issue by bradleyayers** [webpack/webpack#2952]
When pointing `require.context(…, true, …)` at a directory that contains symlink cycles, it never returns.

**Webpack version:**
1.10.x

**Please tell us about your environment:**
OSX 10.x

**Current behavior:**

`require.context()` falls into symlink cycles, which causes it to never return and instead consume all available system memory until crashing.

An example directory would be:

```
symlinks/
├── a -> b
└── b -> a
```

**Expected/desired behavior:**

Webpack would follow symlinks, but only once. This would avoid it endlessly cycling.

**Comment by sokra** [comment]
What's the motivation in creating a symlink cycle?

**Comment by bradleyayers** [comment]
In the up coming lerna release it's how packages are linked together, and it's possible to circular dependencies or devdependencies
