### ISSUE TITLE
Cannot Redefine Property error importing @angular/core library.

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack#2953]
**I'm submitting a bug report**

**Webpack version:**
`webpack@2.1.0-beta.21`

**Please tell us about your environment:**
OSX 10.x

**Current behavior:**
It appears that since @angular/core package has updated to RC6, there has been some reworking of how the packages are structure (ESM, etc.).

```javascript
import {ViewEncapsulation} from '@angular/core';

console.log(ViewEncapsulation);
```

I receive the following errors in my console: 

![screen shot 2016-09-03 at 10 36 37 pm](https://cloud.githubusercontent.com/assets/3408176/18228907/5c8a1ec4-7227-11e6-848b-024541042499.png)

![screen shot 2016-09-03 at 10 36 40 pm](https://cloud.githubusercontent.com/assets/3408176/18228903/44a3de12-7227-11e6-89d1-084f066d19f0.png)

**Expected/desired behavior:**
That there would be no error, and that `import`ing this exported member would not be undefined. 

This is critical for the AngularCLI to use with angular RC6. I'm cc'ing @robwormald who has also been trying to hunt down this issue. We have both been unsure if we missed a case for harmony namespace exports with named reexports underneath nested.

The named export mentioned is originally defined [here](https://github.com/angular/angular/blob/master/modules/%40angular/core/src/metadata/view.ts#L19-L43) and is then [rexported up a level here](https://github.com/angular/angular/blob/master/modules/%40angular/core/src/core.ts#L14) which is then [namespaced reexported here](https://github.com/angular/angular/blob/master/modules/%40angular/core/index.ts#L14). 

This was part of a major package overhaul by @mhevery in https://github.com/angular/angular/commit/979657989bab4fb93faf6a207d30760faa9bd696. 

### To Reproduce:
  * `git clone https://github.com/TheLarkInn/webpack-developer-kit && cd webpack-developer-kit && git checkout experiment/show_beta_21_bug && npm install && npm run dev`
  * Open browser and inspect console 
  * See error there.

* **Interesting information: *
This still appropriately works on downgrade to `webpack@2.1.0-beta.19` so I assume it is a change from there till .21.

* **Browser:** [all] 
 
* **Language:** [all|TypeScript|ES6/7|ES5]

**Comment by TheLarkInn** [comment]
So following up on this: https://github.com/angular/angular-cli/pull/1937#issuecomment-244587179 states that by overriding `mainFields` fixes the issue, but that isn't quite clear to me why. Regardless, useful information for us tackling this.

**Comment by Kovensky** [comment]
I don't know how TypeScript transforms `export enum` or `export * from`; is there a place where both the commonjs and the es6 output is available?

**Comment by Kovensky** [comment]
Quick look on the version published in npm shows no sign of `__esModules` in the umd bundle, which is what was used by default by webpack prior to beta.20.

I'm still not sure if the bad behavior with the ES6 modules version is angular's or webpack's fault, but the absence of `__esModules` (what babel uses to flag ES6 module exports transformed into commonjs) would definitely cause a behavior change.

**Comment by sidjain26** [comment]
@Kovensky Right on! https://github.com/webpack/webpack/issues/2945

**Comment by sokra** [comment]
It's a webpack bug. `export *` is tree shaked incorrectly.

**Comment by sokra** [comment]
fixed and published as beta.22

**Comment by TheLarkInn** [comment]
Fixed with https://github.com/webpack/webpack/commit/19eabc7bb64ed8a46d5bd3ecc2a36d7c4fc5ba60

**Comment by TheLarkInn** [comment]
@sokra is this also related to #2945?
