### ISSUE TITLE
cli and webpack config give different results

### ISSUE THREAD

**Issue by nufercle** [webpack/webpack#2956]
**I'm submitting a bug report**

**Webpack version:**
1.13.2

**Please tell us about your environment:**
OSX 10.x

**Current behavior:**
Running `webpack -d` from the command line results in:
```
                 Asset      Size  Chunks             Chunk Names
     webpack.bundle.js   1.84 MB       0  [emitted]  main
 webpack.bundle.js.map   1.96 MB       0  [emitted]  main
```

Removing the -d command line option and adding: (as part of the config object)
```
output.pathinfo = true
devtool = 'eval-cheap-module-source-map'
``` 
to `webpack.config.js` results in:
```
                 Asset      Size  Chunks             Chunk Names
     webpack.bundle.js   4.45 MB       0  [emitted]  main
```
**Expected/desired behavior:**
Output to be equal.

**Comment by sokra** [comment]
`-d` means `devtool: "source-map"`

**Comment by nufercle** [comment]
@sokra Thanks, I just looked at the source locally and saw this.

My confusion was that I had seen https://github.com/webpack/webpack/blob/master/bin/convert-argv.js#L23 and assumed that your commit https://github.com/webpack/webpack/commit/67656b90e2c4750a7a347dcefcefdf935fb39e1c, on Nov 16, 2015 had made it into releases made since that date.
