### ISSUE TITLE
`define cannot be used indirect` is thrown when code uses a function named 'define' 

### ISSUE THREAD

**Issue by CxRes** [webpack/webpack#2958]
**I'm submitting a bug report**

**Webpack version:**
1.13.2

**Please tell us about your environment:**
Windows 10

**Current behavior:**
`define cannot be used indirect` is thrown when code containing the [stat-mode](https://github.com/TooTallNate/stat-mode) module is compiled. It uses `define` as a function name. This seems like a regression given that others have identified the bug earlier - though I have not tested it with earlier versions.

**Expected/desired behavior:**
Webpack should understand that `define` is a function and not produce code that throws an error .
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.** 
- Create a node project that requires **stat-mode**.
- Open it in a browser environment like nwjs (don't run it like like server side code). I use `target : node-webkit` in my webpack setup.
- **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
  nwjs
- **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart | ...] 
  ES5

**Comment by CxRes** [comment]
Hello? Anybody listening?

**Comment by XZzYassin** [comment]
Hello? Anybody listening?!!

**Comment by yazeed** [comment]
Hello! Having the same issue here!
