### ISSUE TITLE
Unresolved bower dependency

### ISSUE THREAD

**Issue by lyssdod** [webpack/webpack#2960]
**I'm submitting a bug report**

**Webpack version:**
1.13.2

**Please tell us about your environment:**
Linux

**Current behavior:** bower dependency can not be resolved either using http://webpack.github.io/docs/usage-with-bower.html or https://github.com/lpiepiora/bower-webpack-plugin

**Expected/desired behavior:** 
Dependency is resolved

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.** 
Demo: https://github.com/lyssdod/kutesvg-bower-webpack

* **What is the expected behavior?**
Bundle compiles without errors

* **What is the motivation / use case for changing the behavior?**

 * **Browser:** all
 * **Language:** vanilla js

Does anybody know what can cause the problem?

**Comment by sokra** [comment]
It fails in you configuration file at `require.resolve('KUTE.js')`. This is handled by node.js. use `path.resolve` instead.

**Comment by lyssdod** [comment]
I've changed it to use `path.resolve`, but still get the error:

```
lyssdod@lynn /storage/kutesvg-bower-webpack $ webpack 
Hash: 0846efba40210938c7f9
Version: webpack 1.13.2
Time: 83ms
    Asset     Size  Chunks             Chunk Names
bundle.js  2.26 kB       0  [emitted]  main
   [0] ./main.js 480 bytes {0} [built] [2 errors]

ERROR in ./main.js
Module not found: Error: Cannot resolve module 'KUTE.js/kute-svg.js' in /storage/kutesvg-bower-webpack
 @ ./main.js 1:0-18:2

ERROR in ./main.js
Module not found: Error: Cannot resolve module 'KUTE.js' in /storage/kutesvg-bower-webpack
 @ ./main.js 1:0-18:2
```

It also appears when I comment `loaders` completely. My current config:

```js
var path = require('path');
var webpack = require("webpack");
var BowerWebpackPlugin = require("bower-webpack-plugin");

module.exports = {
  entry: './main.js',
  output: {
    path: '.',
    filename: 'bundle.js'
  },
  module: {
    resolve: {
      modulesDirectories: ['node_modules', 'bower_components', 'web_modules']
    },
    plugins: [
       new webpack.ProvidePlugin({
            KUTE: "kute.js"
       }),
    /*new BowerWebpackPlugin({
        modulesDirectories: ['bower_components'],
        manifestFiles: ['bower.json', 'package.json'],
        includes: [/.*\.js/],
        excludes: [/.*\.less/],
        searchResolveModulesDirectories: true
    })*/,
       new webpack.ResolverPlugin(
            new webpack.ResolverPlugin.DirectoryDescriptionFilePlugin("bower.json", ["main"])
       )
    ],/*
    loaders: [
      { test: path.resolve('KUTE.js'), loader: 'imports?this=>window!expose?KUTE' },
    ]*/
  }
};
```
