### ISSUE TITLE
error while running angular 2 with webpack in production server

### ISSUE THREAD

**Issue by eslammostafa** [webpack/webpack#2961]
**I'm submitting a bug report**

**Webpack version:**
2.x

**Please tell us about your environment:**
OSX 10.x / Linux

**Current behavior:**
i am getting an error in production mode saying
uncaught error t.match is not a function

and i have wrote an issue in angular2-webpack-starter,

https://github.com/AngularClass/angular2-webpack-starter/issues/958

since it is the repo i cloned my project from,
but i am guessing its a webpack issue because angular is working just find in development mode,
so i thought it would be better to write an issue here.

my webpack common configuration
https://gist.github.com/eslammostafa/cb042ed9d9d989146f0aa6e80a4b63cf

my webpack production configuration
https://gist.github.com/eslammostafa/8a053184c19909d34f3514d04db416a7

* **Language:** TypeScript X.X

**Comment by sokra** [comment]
use stackoverflow
