### ISSUE TITLE
How to use `webpack` `require.include`?

### ISSUE THREAD

**Issue by mrdulin** [webpack/webpack#2962]
After read the `webpack` doc about `require.include`, I still don't understand what does it mean. I write a demo, get the bundle file like this:

```js
undefined/*! require.include ./a.js */;
__webpack_require__(/*! ./b.js */ 2);
```
As you can see, `require.include('./a.js')` do not execute the `__webpack_require__` function, `require('./b.js')` execute the `__webpack_require__` function. What's the `require.include` meaning ? How to use it in real world? Thanks for answer!

**Comment by sokra** [comment]
It includes the module in the bundle/chunk, but don't execute it.

**Comment by mrdulin** [comment]
@sokra If it don't execute, how do I use it ?
