### ISSUE TITLE
The bundle is not utf-8 encoded

### ISSUE THREAD

**Issue by dalphyx** [webpack/webpack#2963]
I'm submitting a bug report

Webpack version:
2.1.0-beta.21

Please tell us about your environment:
OSX 10.11

Current behavior:
The bundle.js:
```js
console.log('鈾�')
console.log('\u2665')
console.log('鈻�')
```

Expected/desired behavior:
The bundle.js:
```js
console.log('♥')
console.log('\u2665')
console.log('▾')
```

my webpack config: 
[https://gist.github.com/dalphyx/48a6be54f525ee005440091a2373838c](https://gist.github.com/dalphyx/48a6be54f525ee005440091a2373838c)

`main.js`:
```js
console.log('♥')
console.log('\u2665')
console.log('▾')
```

**Comment by sokra** [comment]
https://github.com/webpack/webpack/blob/master/lib/Compiler.js#L295

Is your main.js file utf-8 encoded?

**Comment by dalphyx** [comment]
@sokra  yeah, all my file is utf-8 encoded.

**Comment by sokra** [comment]
``` sh
>cat test.js
console.log('♥')
console.log('\u2665')
console.log('?')

>webpack test.js bundle.js
Hash: 34e4f9c6663a6bbc84fc
Version: webpack 2.1.0-beta.21
Time: 47ms
    Asset     Size  Chunks             Chunk Names
bundle.js  2.49 kB       0  [emitted]  main
   [0] ./test.js 59 bytes {0} [built]

>node bundle.js
♥
♥
?
```

works for me

**Comment by dalphyx** [comment]
Thanks. The behavior of webpack is right. I'm recompiled the files and find it's caused by my browser encoding setting. - -|||

**Comment by peteranny** [comment]
Me the same awkward mistake!! It helps...
