### ISSUE TITLE
dynamic require doesn't work for folders

### ISSUE THREAD

**Issue by MystK** [webpack/webpack#2967]
**I'm submitting a bug report**

**Webpack version:**
2.1.0-beta.21

**Please tell us about your environment:**
OSX 10.11.6

**Current behavior:**
`require('./${theme}')`
throws 
![image](https://cloud.githubusercontent.com/assets/7399140/18334552/4555e50e-752d-11e6-9188-7791114fd3d4.png)

**Expected/desired behavior:**
`require('./${theme}/index.js')` works correctly

Is this a bug or intended behavior?

**Comment by TheLarkInn** [comment]
I'm not sure how this lines up between ContextModule generation vs. Nodes module resolution strategy.
