### ISSUE TITLE
Common chunk 3 times bigger when using webpack 2

### ISSUE THREAD

**Issue by moimael** [webpack/webpack#2968]
**I'm submitting a bug report**

**Webpack version:**
2.1.0-beta.22

**Please tell us about your environment:**
Linux Fedora 24

**Current behavior:**
I recently switched our build system to webpack 2 with tree shaking, and I'm seeing a weird behavior. With webpack 1, our dev chunk size for common was around 3MB. Now with webpack 2 it is around 9.3MB. Even weirder, if i analyze webpack 2 stats.json file, it says that common chunk is 3MB, but the command line output and the file size indicate 9.3MB.

**Expected/desired behavior:**
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.** 

https://gist.github.com/moimael/9eb243fd643d29f84005a38a8ae80356
- **What is the expected behavior?**
  Bundle should be at least the same size as before, ideally smaller since we use tree shaking.
- **What is the motivation / use case for changing the behavior?**
  Huge bundle size regression
- **Browser:**
  All
- **Language:** 
  ES6

**Comment by sokra** [comment]
Could you compare the minimized file sizes?

**Comment by sokra** [comment]
And without `devtool`. i. e. `cheap-module-eval-source-map` inlines source maps into the bundle.

**Comment by moimael** [comment]
Hey, indeed it seems to be a source-map issue.

Trying without devtool and with `BABEL_ENV=client webpack -p` give me a common chunk size of 1.29MB which is way better :) 

We still need source-map in production though, and source maps shouldn't grow the bundle that much, should they ?

**Comment by rohitlodha** [comment]
It appears to me that ES6 import optimization is not applied in Common chunk. When I omit a module in common my app.js increases by 28k but my common.js reduces by 250k

**Comment by th0r** [comment]
@rohitlodha you can try [bundle analyzer](https://github.com/th0r/webpack-bundle-analyzer) to find the difference in these bundles.

**Comment by bebraw** [comment]
@moimael Safe to close?
