### ISSUE TITLE
SyntaxError: Unexpected token: name (xxxxxx) from Uglify plugin

### ISSUE THREAD

**Issue by rohitlodha** [webpack/webpack#2972]
**I'm submitting a bug report**
**Webpack version:**
2.1 beta 22
**Please tell us about your environment:**
Windows 10
**Current behavior:**

Using webpack.optimize.UglifyJsPlugin() in webpack.config throws SyntaxError: Unexpected token: name (xxxxxx) . The code there is unreachable.
if(false)
{
 let xxxx = 

**Expected/desired behavior:**

No errors
 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** 
TypeScript 2.x and ES6 target

**Comment by jhnns** [comment]
Could you setup a minimal example that demonstrates the error?

**Comment by rohitlodha** [comment]
I have created a repo https://github.com/rohitlodha/WebpackBugDemo

**Comment by rohitlodha** [comment]
My mistake. I missed babel the output.

**Comment by jhnns** [comment]
No problem :)

**Comment by id0Sch** [comment]
@jhnns , i've started getting this error for no apparent reason.
```
ERROR in dist/bundle.js from UglifyJs
SyntaxError: Unexpected token: name
```

```
"babel-core": "^6.3.15",
    "babel-loader": "^6.2.0",
    "babel-preset-es2015": "^6.3.13",
```

that's the file that messes everything up:
```
'use strict';
const fs = require('fs');
const path = require('path');
const Promise = require('bluebird');
const mongoose = require('mongoose');

const modelRegex = /\.model\.js$/;
const modelsDirectory = __dirname + '/models';

class Database {
    static getConnection(options){
        return mongoose.createConnection(options.connectionString);
    }
    constructor(options) {
        mongoose.Promise = Promise;
        this.connection = Database.getConnection(options);
    }

    get models() {
        return fs.readdirSync(modelsDirectory)
            .filter((file) => modelRegex.test(file))
            .reduce((models, file) => {
                let schema = require(path.join(modelsDirectory, file));
                let name = file.replace(modelRegex, '');
                models[name] = this.connection.model(name, schema);
                return models;
            }, {})
    }
    disconnect(){
        return mongoose.disconnect();
    }
}
module.exports = Database;
```


would appreciate your help, thanks!

**Comment by balthatrix** [comment]
I'm also getting this issue.  The examples above illustrate it perfectly.  Any updates on this?  Let me know if there's any information in addition to above you need.

**Comment by Kovensky** [comment]
Uglify cannot parse ES6, it will throw you syntax errors. Either set TypeScript to target ES5, post-process your generated JS with babel, or use a different minifier.

**Comment by pavel06081991** [comment]
I have the same issue. I'm using babel-loader. It works great, I get compiled code from es6 to es5. But when I added Uglify plugin I got the error:
`SyntaxError: Unexpected token: name`

**Comment by shisaq** [comment]
I have the same issue: `SyntaxError: Unexpected token: name`. I believe it is because of the keyword `let`. I used babel plugins, like `'react-html-attrs', 'transform-decorators-legacy', 'transform-class-properties'`, but it still couldn't work.

By the way, I met this issue while I was using `SocketProvider`.

**Comment by Kovensky** [comment]
That is correct, and it's a limitation of uglify. If you use Uglify, you _must_ convert your code all the way down to ES5 syntax; no heresy allowed.

To minify anything ES6+-ish, you will need to use closure compiler or babili. Note that closure compiler also does not fully support ES6 (e.g. classes).

**Comment by hellozhangran** [comment]
i have this question : 
```
stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^
Error: offline.js from UglifyJs
SyntaxError: Unexpected token: name (labels) [offline.js:27637,17]
```

my code in offline.js. someone know what happened ? tks

**Comment by zeeshanjan82** [comment]
I am also facing the same issue and am not able to use webpack with ES6 when uglifying the source code.

**Comment by sirLisko** [comment]
@hellozhangran @zeeshanjan82 you probably forgot to install `babel-preset-es2015` and include `"presets": [ "es2015" ]` in your `.babelrc`.

**Comment by pmirandaarias** [comment]
Guys, I need some help. I'm very new with webpack, I need to get my bundle.js minified... and this codes aren't mine! Please. This is the package.json and webpack-prodcution.config.js:

{
  "name": "public",
  "version": "1.0.0",
  "description": "",
  "main": "boot.js",
  "scripts": {
    "start": "webpack",
    "build": "webpack -p --config webpack-production.config.js",
    "dev": "webpack "
  },
  "author": "Adevcom",
  "license": "ISC",
  "devDependencies": {
    "babel-plugin-transform-runtime": "^6.15.0",
    "babel-preset-stage-0": "^6.16.0",
    "babel-preset-stage-1": "^6.16.0",
    "babel-preset-stage-2": "^6.18.0",
    "babel-preset-stage-3": "^6.17.0",
    "webpack": "^1.13.3"
  },
  "dependencies": {
    "babel-core": "^6.18.2",
    "babel-loader": "^6.2.7",
    "babel-polyfill": "^6.16.0",
    "babel-preset-es2016": "^6.16.0",
    "babel-preset-react": "^6.16.0",
    "babel-runtime": "^6.18.0",
    "browserify": "^13.1.1",
    "envify": "^3.4.1",
    "fbjs": "^0.8.5",
    "flux": "^2.1.1",
    "highcharts": "^5.0.7",
    "ion-rangeslider": "^2.1.4",
    "keymirror": "^0.1.1",
    "object-assign": "^4.1.0",
    "react": "^15.3.2",
    "react-cookie": "^0.4.7",
    "react-dom": "^15.3.2",
    "react-dropzone": "^3.7.3",
    "react-dropzone-component": "^1.2.0",
    "react-gemini-scrollbar": "^2.1.5",
    "react-infinite": "^0.10.0",
    "react-maskedinput": "^3.2.0",
    "react-router": "^2.8.1",
    "reactify": "^1.1.1",
    "uglify-js": "^2.7.4",
    "watchify": "^3.7.0"
  },
  "browserify": {
    "transform": [
      "reactify",
      "envify"
    ]
  }
}

--------------------------
webpack-production.config.js
---------------------------

var webpack = require('webpack');
var path = require('path');
module.exports = {
    entry:['babel-polyfill',path.resolve(__dirname, "./boot.js") ] ,
    output: {
        path: __dirname,
        filename: "bundle.js"
    }, 
    plugins: [
		new webpack.DefinePlugin({
			  'process.env':{
			    'NODE_ENV': JSON.stringify('produccion'),
			    'TEMPORAL_PARAM': JSON.stringify('AGREGA AQUI TUS PARAMETROS PRODUCCION')
			  }
			}),
              new webpack.optimize.UglifyJsPlugin({minimize: true})
            ],
    externals: {
        // require("jquery") is external and available
        //  on the global var jQuery
        "jquery": "jQuery"
    },
    devtool: 'source-map',
    module: {
        loaders: [
            { test: /\.css$/, loader: "style!css" },
            {
		        test: /\.js$/,
		        loader: 'babel-loader',
		        include: path.join(__dirname, ''),

		        exclude: /node_modules/,
		         query: {
		          presets: ['es2016', 'react']
		        }
		      }
            
            
                 
        ]
    }
};


What I need to get uglifyed my code with es6 code?

**Comment by QuantumInformation** [comment]
@hellozhangran @zeeshanjan82 you probably forgot to install babel-preset-es2015 and include "presets": [ "es2015" ] in your .babelrc.
fixed it for me

**Comment by qiangzi7723** [comment]
I have the same problem when my code has the syntax class. And then I found it's my fault because I forget to write .babelrc.

**Comment by haydenbr** [comment]
We have been having this issue since upgrading to ionic cli 3 and ionic-angular 3. The fix for us was making the following changes in to `"compilerOptions"` in our tsconfig:

```
"module": "es2015",
"target": "es5"
```

**Comment by sboyd** [comment]
Hi @QuantumInformation @sirLisko 

My Aurelia .babelrc file looks like the following and I'm not sure where I'd put "presets":["es2015"] under the webpack node

{
  "env": {
    "webpack": {
      "plugins": [
        "transform-decorators-legacy",
        "transform-class-properties"
      ],
      "presets": [
        [
          "env",
          {
            "targets": {
              "browsers": [
                "last 2 versions",
                "not ie <= 11"
              ]
            },
            "loose": true,
            "modules": false,
            "whitelist": [
              "transform-es2015-literals",
              "transform-es2015-template-literals"
            ],
            "useBuiltIns": true
          }
        ]
      ]
    },
    "e2e": {
      "plugins": [
        "transform-decorators-legacy",
        "transform-class-properties"
      ],
      "presets": [
        [
          "env",
          {
            "targets": {
              "browsers": [
                "last 2 versions",
                "not ie <= 11"
              ]
            },
            "loose": true,
            "modules": "commonjs",
            "whitelist": [
              "transform-es2015-literals",
              "transform-es2015-template-literals"
            ],
            "useBuiltIns": true
          }
        ]
      ]
    },
    "node": {
      "presets": [
        [
          "env",
          {
            "targets": {
              "node": 4
            },
            "loose": true,
            "modules": "commonjs"
          }
        ]
      ]
    }
  }
}

**Comment by Razenbull** [comment]
#### Had the same error in react-boilerplate with material-components-web


```
ERROR in 0.7cb8593cdf9faca3b95c.chunk.js from UglifyJs
SyntaxError: Unexpected token: name (MDCComponent) [0.7cb8593cdf9faca3b95c.chunk.js:438,6]
...
error Command failed with exit code 2.
```

As @Kovensky mentionned I had to use babili et and I found there is a preset for it.

```yarn add babel-preset-babili```

and in package.json

```
"babel": {
    "presets": [
      ...
      "babili"
    ]
    ...
}
```

**Comment by AlvaroBernalG** [comment]
Had the same error. In my case it was because I forgot to remove a dependency that it was no longer installed but being required by one of  my bundled files.

**Comment by JoeMeeks** [comment]
I had this error also with Ionic 3.5.0+App-Scripts 2.0.1 which uses `"uglify-js": "^3.0.23"` for --prod builds and realized it was due to case sensitivity for @import folder names in my app.module.ts. I corrected the all-caps folder names which fixed this issue.

**Comment by antonyadhiban** [comment]
For the new syntax make sure you set rules instead of loaders/preloaders

**Comment by ramilzakirov** [comment]
You will try remove 'jsnext:main' from resolve.mainFields on your production config.
It looks like:
```
resolve: {
  extensions: ['.js', '.jsx'],
  mainFields: ['browser', 'main']
},
```

**Comment by natterstefan** [comment]
After reading through this issue and [another one](https://github.com/joeeames/WebpackFundamentalsCourse/issues/3) in another project, I got the following two alternative working solutions.

I first installed these packages (Note: [babel-preset-es2015 -> babel-preset-env](https://babeljs.io/env/)):

```
>>  package.json

 npm i babel-loader babel-preset-env --save-dev
```

Then I either modified the `targets` in the `.babelrc` or the rules in the `webpack.config.js`:

```
>> .babelrc

{
  "presets": [
    ["env", {
      "targets": {
        "node": "current",
        "uglify": true // <<< this line
      }
    }],
    "react"
  ],
  // ...
}
```

or add the `options` object to the `babel-loader`.

```
>> webpack.config.js

// ...
module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        exclude: /(node_modules|bower_components)/,
        use: {
          loader: 'babel-loader',
          options: {  // << add options with presets env
            presets: ['env']
          }
        }
      }
    ]
}
```

It also works if you use both together. After that `webpack -p --config webpack.config.js` worked again for me.

**Comment by vladimirkr** [comment]
I solve my issue with https://gist.github.com/nojaf/daf886031072b572bc9a

webpack.config.js
    module: {
        rules: [
            { test: /\.ts(x?)$/, loader: "babel-loader?presets[]=@babel/es2015!ts-loader" }
        ]
    },

tsconfig.js

{
  "compilerOptions": {
    "target": "es6"
  }
}

**Comment by yangxiaolin** [comment]
i has th same error. use webpack-dev-server 2.7.1 fix me

**Comment by ackmanx** [comment]
@yangxiaolin Your fix worked for me also, but I found the below in order to use the current version of webpack-dev-server still.

From [uglifyjs-webpack-plugin](https://github.com/webpack-contrib/uglifyjs-webpack-plugin):

> ℹ️ webpack =< v3.0.0 currently contains v0.4.6 of this plugin under webpack.optimize.UglifyJsPlugin as an alias. For usage of the latest version (v1.0.0), please follow the instructions below. Aliasing v1.0.0 as webpack.optimize.UglifyJsPlugin is scheduled for webpack v4.0.0

The above solved it for me, having the same error "Unexpected token: name (xxxx)". I simply had to explicitly use an updated version of the plugin instead of the aliased one provided by webpack.

**Comment by jonaswindey** [comment]
Error for me came from the striptags package: https://github.com/ericnorris/striptags/issues/25

**Comment by thiagoh** [comment]
// tsconfig.json

`"target": "es6",` -> `"target": "es5",`

**Comment by herrethan** [comment]
after banging my head on this for hours this finally worked for me in getting the .jsx transpiled before uglification along the lines mentioned by @Kovensky, without the use of a separate explicit `uglifyjs-webpack-plugin` or any of the other madness. using webpack 3.11.0.
```
module: {
  rules: [
    {
      test: /\.jsx$/,
      loader: 'babel-loader',
      options: {
        presets: ['env', 'react']
      }
    },
    {
      test: /\.js$/,
      loader: 'babel-loader',
      enforce: 'pre'
    }
  ]
},
resolve: {
  extensions: ['.js', '.jsx']
}
```

**Comment by enzoferey** [comment]
As @ackmanx pointed out, webpack 3.x ships with a non-updated version of UglifyJS. When you specify `-p` flag in CLI you are telling webpack to add the flags `--optimize-minimize` (so the code gets uglified) & `--define process.env.NODE_ENV="'production'"` and to use its bundled version of Uglify. 

If you config both of those in webpack.config.js file you can safely remove the `-p` flag and it works like a charm !

More about how to do that in production: [official productions docs](https://webpack.js.org/guides/production/)

**Comment by sebastiaanluca** [comment]
@enzoferey Have been breaking my head on this for hourssss. Webpack kept uglifying my code, throwing errors when it couldn't read ES2015 modules. Thank you!

For reference: https://github.com/JeffreyWay/laravel-mix/issues/823#issuecomment-385562911

**Comment by moonshineBoy** [comment]
@pavel06081991  then how do you solved your problem?

**Comment by anotherWill** [comment]
just do like this:
//exclude: /(node_modules|bower_components)/,

**Comment by hidaytrahman** [comment]
In short - Don't use ES6

**Comment by lukasz-formela** [comment]
> Uglify cannot parse ES6, it will throw you syntax errors. Either set TypeScript to target ES5, post-process your generated JS with babel, or use a different minifier.

You're a lifesaver! 
I completely forgot about 'don't do ES6' rule in my project 🤷‍♂ . 
Thank you! ~<3

**Comment by HexawareGunasekaranM** [comment]
Hi ,
I am getting following error ,when i build the application.

Unexpected token: name (Geocoder) [./node_modules/@maptiler/geocoder/src/geocoder.js:20,7][main.ddc2f26a.js:244625,6]
 
Please help me to resolve this issues.

"dependencies": {
    "@maptiler/geocoder": "^1.1.0",
    "antd": "^3.5.4",
    "array-compare": "^2.0.0",
    "autoprefixer": "7.1.6",
    "axios": "^0.17.1",
    "babel-eslint": "7.2.3",
    "babel-jest": "20.0.3",
    "babel-polyfill": "^6.26.0",
    "babel-preset-react-app": "^3.1.0",
    "babel-runtime": "6.26.0",
    "bootstrap": "^4.0.0",
    "c3": "^0.4.18",
    "case-sensitive-paths-webpack-plugin": "2.1.1",
    "chalk": "1.1.3",
    "crypto-js": "^3.1.9-1",
    "css-loader": "0.28.7",
    "d3": "4.1.0",
    "d3-cloud": "1.2.5",
    "dotenv": "4.0.0",
    "enzyme-adapter-react-15": "^1.0.5",
    "es6-promise": "^4.2.4",
    "eslint": "4.10.0",
    "eslint-config-react-app": "^2.0.1",
    "eslint-loader": "1.9.0",
    "eslint-plugin-flowtype": "2.39.1",
    "eslint-plugin-import": "2.8.0",
    "eslint-plugin-jsx-a11y": "5.1.1",
    "eslint-plugin-react": "7.4.0",
    "extract-text-webpack-plugin": "3.0.2",
    "file-loader": "1.1.5",
    "filepond": "^4.2.0",
    "filepond-plugin-file-validate-size": "^2.1.1",
    "filepond-plugin-file-validate-type": "^1.2.2",
    "filepond-plugin-image-exif-orientation": "^1.0.4",
    "filepond-plugin-image-preview": "^4.0.3",
    "filepond-polyfill": "^1.0.2",
    "fs-extra": "3.0.1",
    "highcharts": "^4.2.5",
    "html-webpack-plugin": "2.29.0",
    "install": "^0.11.0",
    "jest": "20.0.4",
    "jest-html-reporter": "^1.1.0",
    "jest-localstorage-mock": "^2.2.0",
    "jquery": "^3.2.1",
    "jquery-slimscroll": "^1.3.8",
    "jsdom": "^11.11.0",
    "leaflet": "^1.5.1",
    "leaflet-fullscreen": "^1.0.2",
    "leaflet.heat": "^0.2.0",
    "leaflet.markercluster": "^1.4.1",
    "loadjs": "^3.5.2",
    "lodash": "^4.17.5",
    "lodash.camelcase": "^4.3.0",
    "moment": "^2.20.1",
    "moment-range": "^4.0.1",
    "moment-timezone": "^0.5.17",
    "node-sass-chokidar": "0.0.3",
    "npm": "^5.8.0",
    "npm-run-all": "^4.1.2",
    "object-assign": "4.1.1",
    "postcss-flexbugs-fixes": "3.2.0",
    "postcss-loader": "2.0.8",
    "promise": "8.0.1",
    "promise-polyfill": "8.0.0",
    "prop-types": "^15.6.1",
    "raf": "3.4.0",
    "rc-datetime-picker": "^1.6.1",
    "react-addons-update": "^15.6.2",
    "react-async-script": "^0.9.1",
    "react-bootstrap-table": "^4.3.1",
    "react-circular-progressbar": "^0.8.0",
    "react-css-modules": "^4.7.1",
    "react-datepicker": "^1.5.0",
    "react-dev-utils": "^4.2.1",
    "react-error-overlay": "^1.0.9",
    "react-export-excel": "^0.5.3",
    "react-fast-compare": "^2.0.4",
    "react-filepond": "^7.0.1",
    "react-google-autocomplete": "^1.0.15",
    "react-google-maps": "^9.4.5",
    "react-google-recaptcha": "^1.0.4",
    "react-leaflet": "^2.4.0",
    "react-loadable": "^5.3.1",
    "react-localization": "^0.1.3",
    "react-onclickoutside": "^6.7.1",
    "react-recaptcha": "^2.3.10",
    "react-redux": "^5.0.6",
    "react-router-dom": "^4.2.2",
    "react-select": "^2.0.0",
    "react-select-box": "^3.0.1",
    "react-select-me": "^0.10.3",
    "react-table": "^6.8.6",
    "react-tag-input": "^5.2.3",
    "react-tippy": "^1.2.2",
    "react-websocket": "^2.0.0",
    "react-wordcloud": "1.0.5",
    "recompose": "^0.26.0",
    "redux": "^3.7.2",
    "redux-logger": "^3.0.6",
    "redux-mock-store": "^1.5.1",
    "redux-thunk": "^2.2.0",
    "semantic-ui-react": "^0.82.5",
    "socket.io": "^2.1.1",
    "sockjs-client": "^1.1.5",
    "stomp-client": "^0.9.0",
    "stompjs": "^2.3.3",
    "style-loader": "0.19.0",
    "sw-precache-webpack-plugin": "0.11.4",
    "sync-request": "^5.0.0",
    "tippy.js": "^2.5.2",
    "toastr": "^2.1.2",
    "url-loader": "0.6.2",
    "webpack": "3.8.1",
    "webpack-dev-server": "2.9.3",
    "webpack-manifest-plugin": "1.3.2",
    "webstomp-client": "^1.2.0",
    "whatwg-fetch": "2.0.3",
    "@babel/runtime": "^7.6.2"
  },
"scripts": {
    "build-css": "node-sass-chokidar src/ -o src/",
    "watch-css": "npm run build-css && node-sass-chokidar src/ -o src/ --watch --recursive",
    "start-js": "node scripts/start.js",
    "start": "npm-run-all -p watch-css start-js",
    "build": "npm run build-css && node scripts/build.js",
    "test": "jest"
  },
  "jest": {
    "collectCoverageFrom": [
      "src/**/*.{js,jsx,mjs}"
    ],
    "testResultsProcessor": "./node_modules/jest-html-reporter",
    "setupFiles": [
      "<rootDir>/config/polyfills.js",
      "jest-localstorage-mock"
    ],
    "testMatch": [
      "<rootDir>/src/**/__tests__/**/*.{js,jsx,mjs}",
      "<rootDir>/src/**/?(*.)(spec|test).{js,jsx,mjs}"
    ],
    "testEnvironment": "node",
    "testURL": "http://localhost",
    "transform": {
      "^.+\\.(js|jsx|mjs)$": "<rootDir>/node_modules/babel-jest",
      "^.+\\.css$": "<rootDir>/config/jest/cssTransform.js",
      "^(?!.*\\.(js|jsx|mjs|css|json)$)": "<rootDir>/config/jest/fileTransform.js"
    },
    "transformIgnorePatterns": [
      "[/\\\\]node_modules[/\\\\].+\\.(js|jsx|mjs)$"
    ],
    "moduleNameMapper": {
      "^react-native$": "react-native-web"
    },
    "moduleFileExtensions": [
      "web.js",
      "mjs",
      "js",
      "json",
      "web.jsx",
      "jsx",
      "node"
    ]
  },
  "babel": {
    "presets": [
      "react-app"
    ],
    "env": {
      "test": {
        "presets": [
          "env"
        ]
      }
    }
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-jest": "^20.0.3",
    "babel-loader": "^7.1.2",
    "babel-preset-env": "^1.7.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-register": "^6.26.0",
    "chai": "^4.1.2",
    "enzyme": "^3.3.0",
    "enzyme-adapter-react-16": "^1.12.1",
    "jest": "^20.0.4",
    "mocha": "^5.0.2",
    "react": "^16.8.6",
    "react-addons-test-utils": "^15.6.2",
    "react-dom": "^16.8.6",
    "react-test-renderer": "^16.4.0",
    "sinon": "^4.4.2"
  }

**Comment by quannt** [comment]
Use Terser https://webpack.js.org/plugins/terser-webpack-plugin/ if you want to support es2015+ JS.

**Comment by JimLynchCodes** [comment]
Wow, fresh scaffold of create-react-app doesn't even build bc of this... why is open source so jank? 😢
