### ISSUE TITLE
Detect chunk's build version is out of a date on client

### ISSUE THREAD

**Issue by hotspurs** [webpack/webpack#2976]
**I'm submitting a feature request**
Definetely (with no doubts)

**Webpack version:**
1.10.x

**Please tell us about your environment:**
Linux (doesn't matter in this case)

**Current behavior:**
Webpack don't check if loaded chunk is belong to current build version.

**Expected/desired behavior:**
Webpack checks chunk's build version when it loaded.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.** 

0. Create entry point with require.ensure on any button click for example
1. Compile build for production (we've got `main.js` and `1.chunk.js`)
2. Open main page in browser (and keeps opened for a while)
3. add new dependency to entry point
4. Compile bundle again
5. Return to opened page in browser and click button to load `1.chunk.js`
6. Loaded chunk contain same modules, with new index numbers (because of new dependeny at the entry point) 

**What is the expected behavior?**
Webpack signed each chunk with build version hash.

Each time when webpack loads new chunk it checks build version, if chunks version is out of date, webpack throw new Error('Webpack: loaded chunk is out of a date'), and trigger some event anywhere (with preventDefault and stopPropagation methods).

**What is the motivation / use case for changing the behavior?**
This allow to prevent errors due to outdated chunks, and provide simple interface to handle this exceptions.

**Comment by sokra** [comment]
Use the webpack hashing feature to avoid this problem. We won't add runtime checks.
