### ISSUE TITLE
2.1.0-beta.22 shows an export-not-found warning for an existing, exported class

### ISSUE THREAD

**Issue by Tragetaschen** [webpack/webpack#2977]
**I'm submitting a bug report**

**Webpack version:**
2.1.0-beta.22

**Please tell us about your environment:**
Windows 10

**Current behavior:**
https://github.com/Tragetaschen/webpack-interface-import-warning
When running webpack `beta.22`, two warnings appear:

```
WARNING in ./main.ts
16:51 export 'Bar' was not found in './src'

WARNING in ./main.ts
16:74 export 'Bar' was not found in './src'
```

**Expected/desired behavior:**
`beta.21` doesn't show these.

There are some ways to make the warning go away:
- In `src/index.ts`, replace `export * from './bar'` with `export {Bar} from './bar'`
- In `src/index.ts`, comment out `export * from './foo'` (sic!)

I can see that the awesome-typescript-loader introduces code that references the interface name (although running bare TypeScript erases it successfully), but those two workarounds above make me think something is odd with webpack.

**Comment by sokra** [comment]
typescript transpiles `export interface Bar {}` to nothing. This means there is nothing exported from `bar`. webpack correctly shows a warning that the export was not found.

The problem is that the exported interface is really used in the generated type:

``` js
__decorate([
    metadata(), 
    __metadata('design:type', (typeof (_a = typeof Bar !== 'undefined' && Bar) === 'function' && _a) || Object)
], Main.prototype, "prop", void 0);
```

Note that the code still works, because typescript checks for undefined here, but a ES6 Modules implementation may throw here (webpack displays a warning).

Please report this issue to typescript itself.

It should either generate an export from interface.
Or it should not use the imported variable if it's an interface (which is not generated).

**Comment by Tragetaschen** [comment]
I figured as much for that specific bit, and s-panferov/awesome-typescript-loader#214 already exists. TypeScript on its own is fine and neither generates the import of the interface name reference.

What I don't understand is why the warning goes away when I remove the class re-export of `foo` from the index file.

I'm still trying to reduce from my project an issue where in an `index.ts` I have a couple of `export * from  './...'` together with an `export class` and I get warnings in a consuming module that those classes that are part of the `export *` were not found.

**Comment by sokra** [comment]
Looks like another issue...

**Comment by Tragetaschen** [comment]
Ok, I have been able to to reproduce the other warning not related to the wrongly generated metadata and added a commit to the above repro repository.

I kept the metadata code active for the awesome-typescript-loader bug. You can delete / comment that line from `main.ts` or alternatively use ts-loader, which generates correct code.

Nonetheless, there is now a warning:
```
WARNING in ./main.ts
18:4 export 'Foo' was not found in './src'
```

This warning vanishes when
- in `index.ts` I remove the `Baz` export
- in `index.ts` I reorder the `foo` and `bar` exports (huh?)
- in `index.ts` I say `export {Bar} from './bar'` instead of `*`
- in `index.ts` I say `export {Foo} from './foo'` instead of `*`

**Comment by sokra** [comment]
Sadly when the other issue is fixed this hides the original issue.

---

Here is the behavior for importing empty modules (modules without content like the transpiled version of `export interface X {}`.

Any module without `import` or `export` statement is considered as CommonsJs module.

webpack doesn't know what a CommonJs module exports (could be anything) as only exports for harmony modules are known at compile-time.

When reexporting a commonjs module (`export * from "commonjs"`) webpack also doesn't know what the harmony module exports.

Warnings are only triggered when webpack knows about exports.

**Comment by TheLarkInn** [comment]
//cc @DanielRosenwasser

**Comment by Bretto** [comment]
is there a work around ?

**Comment by r-park** [comment]
I experienced this same issue using `awesome-typescript-loader`. `ts-loader` doesn't seem to have this issue.

**Comment by emilio-martinez** [comment]
I've found this issue also when declaring Typescript string literal types; however, explicitly importing the `interface` or `type` did not get rid of the warning for me, i.e., for both use cases I was using `import { [interface] } from './module'` syntax.

**Comment by gund** [comment]
Same issue with string literal types.

Consider `moduleA.ts`:
```ts
export type AvatarType = 'avatar' | 'storecover';
```

Then import it in `moduleB.ts`:
```ts
import { AvatarType } from './moduleA';

let avatar: AvatarType = 'avatar'; // <-- This line gives warning
```
WARNING: export 'AvatarType' was not found in './moduleA'

**Comment by SimonSchick** [comment]
We also get similar warnings here, in one case a string enum type id not found eg.
`export type Provider = 'twitter' | 'discord' | ...;`

In the other an interface definition is not found.

```
export interface IMessageComponent {
    type: string; // tslint:disable-line
    text: string;
}

export interface IMessageEmoticonComponent extends IMessageComponent {
    type: 'emoticon'; // tslint:disable-line
    pack: string;
    source: string;
    coords: {
        x: number,
        y: number,
        width: number,
        height: number,
    };
}
```

**Comment by TheLarkInn** [comment]
@s-panferov @jbrantly is this an issue with how your respective loaders are treating interfaces?

**Comment by DanielRosenwasser** [comment]
TypeScript should be eliding any imports that aren't used as values. I'm not sure what could be going on here.

**Comment by jbrantly** [comment]
cc @johnnyreilly

**Comment by texel** [comment]
Just ran into this on an angular-cli project which is using Webpack 2.1.0-beta.24 and awesome-typescript-loader 2.2.4. Warning occurs when I export a string literal type from one file and import it in another.

**Comment by SteveStrong** [comment]
I am seeing the same thing.   Stuff still runs but this feels unfinished

**Comment by MrJuliuss** [comment]
Hello, same issue here when i export a type 👎

**Comment by adamrkerr** [comment]
I am still experiencing this issue while following the config example.

```
import { OpaqueToken } from '@angular/core';

export let SKYPE_CONFIG_TOKEN = new OpaqueToken('skype.config');

export interface SkypeConfig {
    ...
}
```

Everything works, but I get this warning:

`105:93-104 "export 'SkypeConfig' was not found in './skype.config'`

**Comment by johnnyreilly** [comment]
Do you experience the same with ts-loader?

**Comment by hccampos** [comment]
Same issue here. Any classes that contain decorators and are using an interface imported from another file trigger the warning. While everything works normally, it would be nice to get rid of the warnings. However, as @sokra said, this is probably a Typescript or loader problem.

**Comment by alexwakeman** [comment]
I noticed this warning occurs when there is more than one `export` in the file where the `interface` is declared... so isolating the interface in one file and moving everything else to it's own file fixes the issue. 

Not sure why this is happening, but thankfully, no more warnings.

**Comment by pavelkornev** [comment]
I face to the same warning by doing following with vanilla ES6...

**moduleA.js**:
```javascript
const f1 = () => {};
export default {
    f1,
};
```

**moduleB.js**:
```javascript
import { f1 } from './moduleA'
...
```

**Resulting with:**
```
WARNING in ./moduleB.js
    91:53-64 "export 'f1' was not found in './moduleA'
```

On the other hand if I do explicit export I have no warnings:
```javascript
export const f1 = () => {};
```

But for some reason we need first approach. Is there any way to overcome such warning in this case?

**Comment by Markus-ipse** [comment]
@pavelkornev 
```
export default {
    f1,
};
```
This exports an object, with the property f1, as a default export, e.g. { f1: f1 }

```
import { f1 } from './moduleA'
```
This syntax is used to import a named export, it looks like object destructuring, but it's not.

So either change moduleA to `export default f1;` or change moduleB to `import f1 from '/moduleA';'

**Comment by pavelkornev** [comment]
@Markus-ipse yes, it's not object destruction, but how does it work then despite the warnings? 

Moreover, it does not throw any warnings when using babel-preset-es2015, but throws when using babel-preset-env. We compared list of plugins included by env preset with list of plugins in es2015 preset and do not see significant difference in our case.

**Comment by istiti** [comment]
same issue here

**Comment by filipesilva** [comment]
Heya all, just wanted to mention I looked into this further from the Angular CLI side and provided a comprehensive answer in https://github.com/angular/angular-cli/issues/2034#issuecomment-302666897.

**Comment by mrchief** [comment]
> This syntax is used to import a named export, it looks like object destructuring, but it's not.

Sorry @Markus-ipse. Will have to call BS on that. What you're saying here makes no sense.  Destructuring or not, `import { f1 } from './moduleA'` is the correct syntax. 

Ref: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export#Using_named_exports

**Comment by Markus-ipse** [comment]
@mrchief Well yes, it's correct syntax, but what I was saying is that you cannot use that syntax for destructuring out a value from an exported object.

From the example you linked to:
```
// module "my-module.js"
function cube(x) {
  return x * x * x;
}
const foo = Math.PI + Math.SQRT2;
export { cube, foo };
```
 Even though the above export statement looks like an object, it is not, it's two named exports. It's equivalent to writing:
```
// module "my-module.js"
export function cube(x) {
  return x * x * x;
}
export const foo = Math.PI + Math.SQRT2;
```
As you can have multiple named exports in a file, we have the following syntax which allow us to pick which exports that we want to import:
```
import { cube, foo } from 'my-module';
``` 

If you are using a default export to export an object, as in Pavel's example:
```
const f1 = () => {};
export default {
    f1,
};

```
Then you must use the default import statement:
```
import whatEverNameIWant from './moduleA';
```
This will give you the exported object on which you can call the f1 function:
```
whatEverNameIWant.f1();
```

So even though the named import statement looks like object destructuring, it is in fact not, and that is what is causing the confusion. 

So for Pavel's example to work without warning, both the import and exports must be either named or default, e.g.
```
//moduleA.js

const f1 = () => {};
export { 
    f1,
};

// or export const f1 = () => {};


//moduleB.js
import { f1 } from './moduleA';
f1();

```
or 
```
//moduleA.js

const f1 = () => {};
export default {
    f1,
};

//moduleB.js

import myModule from './moduleA':
const { f1 } = myModule;
f1();

// or myModule.f1();

```

Hope that make it clearer :)

**Comment by mrchief** [comment]
Now its my turn to apologize @Markus-ipse ! I missed one significant detail earlier - `export default` vs `export {`. Yes I see the confusion now.

Thanks for the detailed response.  Would have not wasted your time if my eyes could read better. :eye:
