### ISSUE TITLE
master/lib/NodeStuffPlugin.js does not work when used in child compiler

### ISSUE THREAD

**Issue by jantimon** [webpack/webpack#2978]
**Bug report**

**Webpack version:**

Bug occours for  **1.10.13** and **webpack@2.1.0-beta.22**

**Current behavior:**
The main compiler sets values which can't be changed in the child compilation.

The root of the issue seems to be here: `__dirname` and `__filename` are set using the `setConstant`: 
https://github.com/webpack/webpack/blob/3df89413e2a1ad7e23aa217ec9fa6bab35c93fd4/lib/NodeStuffPlugin.js#L27-L32

This sets also the value of `__dirname` and `__filename` for all child compilers no matter what configuration you set in the child compiler

**Expected/desired behavior:**

Setting

``` js
new NodeStuffPlugin({
      __dirname: false,
      __filename: false,
});
```

in the child compiler  should allow to use `__dirname` and `__filename` inside the compiled sources.
- **minimal demo of the problem:** 

`entry.js`

``` js
console.log(__dirname, __filename);
```

`webpack.config.js`

``` js
var NodeTemplatePlugin = require('webpack/lib/node/NodeTemplatePlugin');
var NodeTargetPlugin = require('webpack/lib/node/NodeTargetPlugin');
var LoaderTargetPlugin = require('webpack/lib/LoaderTargetPlugin');
var LibraryTemplatePlugin = require('webpack/lib/LibraryTemplatePlugin');
var SingleEntryPlugin = require('webpack/lib/SingleEntryPlugin');
var NodeStuffPlugin = require('webpack/lib/NodeStuffPlugin');

function childCompilation (compilation, callback) {
  var outputOptions = {
    filename: 'child-output.js',
    publicPath: compilation.outputOptions.publicPath
  };
  var childCompiler = compilation.createChildCompiler('demo', outputOptions);
    childCompiler.context = compilation.compiler.context;
    childCompiler.apply(
      new SingleEntryPlugin(this.context, './entry.js'),
      new NodeTemplatePlugin(outputOptions),
      new NodeTargetPlugin(),
      new LoaderTargetPlugin('node'),
      new NodeStuffPlugin({
        __dirname: false,
        __filename: false,
        console: true
      })
    );
  childCompiler.runAsChild(function (err, entries, childCompilation) {
    callback();
  });
}

module.exports = {
  context: __dirname,
  entry: './entry.js',
  output: {
    path: 'dist',
    publicPath: '',
    filename: 'main-output.js'
  },
  plugins: [
    {
      apply: function (compiler) {
        compiler.plugin('make', function (compilation, callback) {
          childCompilation(compilation, callback);
        });
      }
    }
  ]
};
```

Then just run:

``` bash
webpack
```

And you will see that both, the `main-output.js` and the `child-output.js` contain:

``` js
/* WEBPACK VAR INJECTION */(function(__dirname, __filename) {console.log(__dirname, __filename);
/* WEBPACK VAR INJECTION */}.call(exports, "/", "/index.js"))
```

**Comment by sokra** [comment]
This would require bigger architectual changes. We should not expose the parser from the Compiler, but move the creating into a plugin hook of the Compilation.

This is a breaking change that affects many plugins. A fake `compiler.parser.plugin` method could catch the deprecated calls.

**Comment by jantimon** [comment]
@TheLarkInn any updates in this?

**Comment by jantimon** [comment]
Maybe we could come up with a better name for "parser-options" but the following change seems to work.

https://github.com/webpack/webpack/blob/master/lib/NormalModuleFactory.js#L240 
```js
NormalModuleFactory.prototype.createParser = function createParser(parserOptions) {
    var parserOptions = this.applyPluginsWaterfall0("parser-options", parserOptions || {});
    var parser = new Parser();
    this.applyPlugins("parser", parser, parserOptions);
    return parser;
};
```

**Comment by TheLarkInn** [comment]
@jantimon would you like to submit a PR for this?

**Comment by jantimon** [comment]
@TheLarkInn I discussed it with sokra and the outcome was that he didn't want to cache the call.

Name will be: `resolve-settings` and the arguments could be `{ context, request, dependencies, userRequest, rawRequest, loaders, resource, settings }`.

I am moving to a new flat right now so it will take some time to work on this

**Comment by jantimon** [comment]
@sokra was this addressed in the webpack 2 & 3 releases?

**Comment by sokra** [comment]
Yep you can disable/enable i. e. `__dirname` for child compilations with this syntax:

``` js
rules: [
  {
    compiler: "html-webpack-plugin", // <- child compiler name starts with
    parser: {
      node: {
        __dirname: false
      }
    }
  }
]
```

**Comment by jantimon** [comment]
Cool - would a plugin (like the html-webpack-plugin) be able to set this value somehow or would the user have to configure that?

**Comment by sokra** [comment]
You could but you shouldn't.
