### ISSUE TITLE
Singleton in linked packages does not work

### ISSUE THREAD

**Issue by screendriver** [webpack/webpack#2980]
**I'm submitting a bug report**

**Webpack version:**
1.13.2

**Please tell us about your environment:**
OSX 10.11.6

**Current behavior:**

I have packages `A`, `B` and `C`. `C` is a singleton and at runtime there should be only **one** instance. `A` and `B` has a direct dependency to `C`. `B` is linked and installed in `A` as a linked package. Now if I run the app I can see that `C` is in a different state. I've made a `console.log()` in `A` and `B` that should print the state of `C` and it differs. When I unlink `B` and install it as direct dependency everything works.

**Expected/desired behavior:**

`C` should have **one** state in the whole application.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.** 

I believe that there is already a workaround for this behaviour but I don't find it. I already added following to my `webpack.config.js` but it dos not work:

```js
resolve: {
  fallback: path.join(__dirname, 'node_modules'),
},
resolveLoader: {
  root: path.join(__dirname, 'node_modules'),
  fallback: path.join(__dirname, 'node_modules'),
},
``` 
* **Browser:** [all] 
 
* **Language:** [ES6/7 (Babel 6.*)]

**Comment by sokra** [comment]
The workaround will work with `resolve.root`, or `resolve.alias`. `resolve.symlinks: false` is also possible in webpack 2.

This this the way the node.js resolving works. So it's working as expected. Not pretty but that's how it's speced.

**Comment by screendriver** [comment]
Thank you!

```js
resolve: {
  root: path.join(__dirname, 'node_modules'),
  fallback: path.join(__dirname, 'node_modules'),
},
```

did it 😎
