### ISSUE TITLE
Hot reload triggered multiple times in a row when launching dev server

### ISSUE THREAD

**Issue by geowarin** [webpack/webpack#2983]
Hello!
**I'm submitting a bug report**

I've been using webpack for a long time and I've seen this behaviour on several mac OSX computers.
Sometimes, when launching the dev server (either with `webpack-dev-server` or `webpack-dev-middleware`), webpack enters a loop when it invalidates and reloads my bundle 3 to 12 times in a row.

This is difficult to reproduce because it happens randomly.
It seems to happen more frequently if I kill and restart my server a lot.
It looks like a race condition or an FS event bug.

I got this bug with webpack 1 as well as webpack 2 so all versions I used seem to have the same bug.

It's not a dramatic issue but it's quite annoying when it happens. I just wanted to make sure that you guys were aware of it and see if other people are experiencing this issue as well.

![demo](http://i.imgur.com/wmEHeBb.png)

**Webpack version:**
1 and 2

**Please tell us about your environment:**
OSX 10.11.6

**Current behavior:**
Webpack sometimes hot reloads multiple times in a row on first start.

**Expected/desired behavior:**
Webpack does not hot reloads on first start.

**steps to reproduce** 

You can randomly see this behaviour with a simple boilerplate like [this one](https://github.com/gaearon/react-hot-boilerplate).
I have seen it happen with isin/nwb, facebookincubator/create-react-app, etc...

**Comment by SpaceK33z** [comment]
I can confirm this bug. It happens about 1 of 5 times in the examples in `webpack-dev-server`, which use an extremely minimal config. I'm using OSX too.

**Comment by Kovensky** [comment]
This is most likely the cause: https://github.com/webpack/watchpack/issues/25

**Comment by SpaceK33z** [comment]
@Kovensky, ah thanks, that looks like the same problem.

**Comment by avesus** [comment]
@sokra please fix it.

**Comment by jmlivingston** [comment]
I am seeing this problem as well and assumed it was just me. This only happens on startup and probably 1/5 times I start. I tried playing with the watchOptions, but they didn't appear to help.

I have a very minimal setup to just test future ES features without any special plugins other than babel.

### webpack.config.js

`javascript
const { resolve } = require("path");

module.exports = {
  entry: [
    "./index.js"
  ],
  output: {
    filename: "bundle.js",
    path: resolve(__dirname, "public"),
    publicPath: "/"
  },
  context: resolve(__dirname, "src"),
  devtool: "inline-source-map",
  devServer: {
    contentBase: [resolve(__dirname, "src")],
    publicPath: "/"
  },
  module: {
    rules: [
      {
        test: /\.(js)$/,
        exclude: /node_modules/
      }
    ]
  },
  watchOptions: {
    aggregateTimeout: 300,
    poll: 300
  }
}
`

### .babelrc

`javascript
{
  "presets": [
    [
      "env",
      {
        "modules": false
      }
    ]
  ]
}
`

### package.json

`javascript
{
  "name": "temp",
  "version": "1.0.0",
  "author": "",
  "license": "ISC",
  "scripts": {
    "start": "webpack-dev-server"
  },
  "description": "",
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.2",
    "babel-preset-env": "^1.6.0",
    "webpack": "^3.5.5",
    "webpack-dev-server": "^2.7.1"
  }
}
`

### src\index.js

`javascript
console.log('foo')
`

### public\index.html

`html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Document</title>
  <script src="../bundle.js"></script>
</head>
<body>
</body>
</html>
`

### Screenshot

This actually shows about 21 times

![image](https://user-images.githubusercontent.com/1093719/29682758-093cc7ba-88c1-11e7-9246-66be2dcb6560.png)

**Comment by wesleymostien** [comment]
Also experiencing this issue. Seems to happen only on a start of the server after a hot reload happened. For example : start server, change a file, reload happens, stop server, then restart server > compiler builds a couple of times...

My setup :  dev server + webpack-hot-middleware via Node API

**Comment by Always-Sunny** [comment]
Experiencing the same issue. 

Using an express server with webpack, webpack-dev-middleware, webpack-hot-middleware, and react-hot-loader

Happens on save changes. Webpack will bundle the same package up to 8 times.

**Comment by NikitaVlaznev** [comment]
Same.
It is stable. Recursion occurs on start if source files were changed after previous start.

**Comment by mcpherson-sa** [comment]
What is the status of this bug. I am seeing on Ubuntu, I only installed webpac yesterday. Why has the issue been closed? There doesn't seem to be any mention of a resolution

**Comment by aaroncass** [comment]
I am also seeing this bug. 

I have a barebones project (following https://webpack.github.io/docs/tutorials/getting-started/), and every time I change a file, the browser reloads the page multiple times. webpack only compiles once. This only happens in chrome/chromium (v 62), not in firefox.

OS: Ubuntu 16.04

**Comment by mcpherson-sa** [comment]
@aaroncass - Your issue might be the same as what I am seeing. I traced it webpack-dev-server and have raised and issue there: https://github.com/webpack/webpack-dev-server/issues/1210. Am also seeing in on and Chrome/Chromium only, not Firefox. Unfortunately the maintainers of webpack-dev-server closed the issue straight away despite the fact that I had done quite a lot debugging work on the issue. Perhaps you can reopen it. They might take it more seriously if they know there is more than one instance.

**Comment by mcpherson-sa** [comment]
To verify the issue the issue I am seeing in webpack-dev-server follow these steps
- run npm install sleep
- in node_modules/webpack-dev-server/lib/Server.js in the function search for the line:
  `this._sendStats([conn], this._stats.toJson(clientStats), true);`
- add the line sleep.msleep(1000); before the line above.

This should make the issue disappear. It seems to be related to sockjs on Chrome. Basically when a reload is triggered the browser connects twice to sockjs server started a loop which triggers more reloads. Putting in a delay allows the first connection to go out of scope.

**Comment by nickmealey** [comment]
+1 Also having an issue with this

**Comment by geotrev** [comment]
Not trying to reanimate the dead, but I'm also having this problem. Even if I reset my default browser to Safari vs. Firefox vs. Chrome. Very strange indeed.

For reference, the command I'm running is simply `webpack-dev-server --config webpack.dev.js --open`

**Comment by kirill-konshin** [comment]
@mcpherson-sa would you like to make a pull request with your proposed change?

**Comment by TX-DSS** [comment]
I found add watchOptions can fix this problem
```json
watchOptions: {
  aggregateTimeout: 10000,
  poll: 5000
}
```

**Comment by yessky** [comment]
it should related to [#webpack/watchpack](https://github.com/webpack/watchpack/issues/25).

here is a workaround to fix it. see [webpack-mild-compile](https://github.com/yessky/webpack-mild-compile), it would help.

**Comment by PerspectivesLab** [comment]
same issue here webpack 4.4

**Comment by paradite** [comment]
Interesting find:
I had this problem with me for a very minimal redux todo app today after creating multiple files and running webpack dev server. Tried lots of options but still getting the same behaviour:

- webpack recompiles
- browser receives socket request

Then after a few hours, I tried to restart my computer to test my luck and this issue magically disappeared (no more recompile and socket requests in browser). So I suspect it might have to do with some other processes/external interference or some internal state which can be reset via a restart of computer. Hope it helps with debugging this issue.

**Comment by hd619953679** [comment]
I think it may be the reason why the disk is slow to read and write, because I will encounter this problem when I turn on the writefileplugin, I can solve it after shutting down

**Comment by LvChengbin** [comment]
Encounter same problem in version 
```
webpack: 5.73.0
webpack-cli: 4.10.0
webpack-dev-server 4.9.2
```

**Comment by vankop** [comment]
@LvChengbin please create separate issue with reproducible repo

**Comment by nathan5x** [comment]
+1 I'm facing the same issue in the Ubuntu Docker container. Any updates on this?
