### ISSUE TITLE
webpack 2 upgrade produces "webpackHotUpdate is not defined"

### ISSUE THREAD

**Issue by cortopy** [webpack/webpack#2985]
**I'm submitting a bug report**

**webpack and webpack-dev-server version:**
webpack: 2.1.0-beta.20 
webpack-dev-server: 1.14.1 and 2.1.0-beta.3

**Please tell us about your environment:**
Linux Fedora 24

**Expected/desired behavior:**
Reloading to work.

I've upgraded to webpack 2 in an angular project. After the upgrade, the exact same configuration works, except for the reloading. webpack-dev-server will always throw the following Uncaught errors when files have changed. There are no errors in the console though:

```
Unexpected token <`
```

And 

```
ReferenceError: webpackHotUpdate is not defined
```

This wouldn't happen with Webpack 1. It now happens with webpack-dev-server both 1 and 2, and independently from whether or not HMR is enabled

**Steps to reproduce**

I have created a repo with my config and a basic angular skeleton.

https://github.com/cortopy/debug-webpack-dev-server
1. npm install
2. npm start
3. Go to http://localhost:3000/
4. Just change the html file `debug-webpack-dev-server/src/app/app.component.html` with anything you want to trigger the reload.
5. On my end, that is enough to get the error.

**What is the expected behavior?**
Webpack-dev-server to reload with and without HMR

**What is the motivation / use case for changing the behavior?**
Please note that even though this is an issue with webpack-dev-server, an issue was already submitted in their repo: https://github.com/webpack/webpack-dev-server/issues/601#issuecomment-246106990

I'm submitting this issue here as instructed by one maintainer of the repo.

Also, the issue doesn't seem to lie with dev-server itself, as error only happens with webpack 2 and any version of dev-server.

**Browser:** [all ] 

**Language:** [TypeScript 2.0.0]

**Comment by TheLarkInn** [comment]
@SpaceK33z Is this related to dev server?

**Comment by SpaceK33z** [comment]
@TheLarkInn, this issue was originally posted in the dev server repo, but I pointed him to here. I am still not 100% sure, but `webpackHotUpdate` is a variable defined by webpack, not the dev server.

The configuration seems to be okay. I could also reproduce the problem with his repo, and debugged it for a while, but couldn't find it.

**Comment by zhaoshengjun** [comment]
Hi guys, I just tried to replicate this issue. Unfortunately, I don't have an Unix computer. But here's something you may try based on my findings.

I found that @cortopy using a `web-animations-next.min.js` file under the vendor folder, but it's not an actual file, more like a linked file.  When I run `npm start`, it warns me the file is not correctly loaded and I get the same error when I change html file. But after I change the linked file to a real file, the error also goes away.

So it's worth a try to replace the linked file with a real file and see if the issue still exists.

**Comment by SpaceK33z** [comment]
@zhaoshengjun, thanks for helping. That file was an error in his test repo. After removing that the problem still persists.

**Comment by cortopy** [comment]
My apologies for keeping the symlink. I should have removed it. I've now updated repo without symbolic link. Error persists

**Comment by cortopy** [comment]
After a while, I just tried with latest version and it is working now. Thank you everybody!

**Comment by voxmatt** [comment]
@cortopy I'm seeing the exact same thing and I'm pretty sure I have the absolute latest. Any insights as to what fixed this would be incredibly helpful.

**Comment by cortopy** [comment]
@voxmatt Unfortunately last weekend I, too, started having problems with this again. 

This time it only happened with a module which is npm-linked to the project. Installing rather than linking the module, made the issue go away. I'm just wondering if this issue has something to do with module resolution. The frustrating part is that it only affects the webpack dev server, as restarting webpack works fine regardless.

**Comment by jwickens** [comment]
Any update on this? I'm getting this bug with 

- webpack@2.1.0-beta.27
- webpack-dev-server@2.1.0-beta.11

I'm using JSX, but no typescript (So a react app, not angular). Reloading the page manually is my workaround.

**Comment by bebraw** [comment]
Confirmed on a separate project (React, babel-loader) as I was setting up HMR. I have to see if I can simplify this somehow to understand better what's causing it.

**Comment by bebraw** [comment]
I set up a [minimal React example](https://github.com/survivejs-demos/webpack-demo/tree/webpack2-react) to debug. Note that I go through Babel there whereas the original issue was about TypeScript.

**Comment by SpaceK33z** [comment]
@bebraw I couldn't reproduce it with your example. I did a git clone, `git checkout webpack2-react`, `npm i && npm start` and edited `app/component.js`. It couldn't do a hot reload, but did a full reload instead.

**Comment by bebraw** [comment]
@SpaceK33z Could this have to do with Node version? I'm running on Node v7.2.0 in macOS Sierra (10.12.1). I can try running it with the same version of Node as you.

**Comment by SpaceK33z** [comment]
@bebraw, ah, I run node v6. Unfortunately there are a lot of issues with node v7 (which is why I put a warning in the readme of webpack-dev-server, also see https://github.com/webpack/webpack-dev-server/commit/7eb7a921d6d95328c30783ed0a172906b0fface3). I'm very curious if this also happens with node v6 though!!

**Comment by bebraw** [comment]
@SpaceK33z It's the same with v6.9.1. I re-installed `node_modules` just in case. I wonder what's the difference here. Note that I'm modifying `element.innerHTML = 'Hello world again';` at `app/component.js` but that shouldn't make a difference.

**Comment by bebraw** [comment]
It looks like this has something to do with html-webpack-plugin. I updated my branch to skip it (just static index.html) and that fixed it.

@cortopy I noticed your repository uses html-webpack-plugin too. That would explain the behavior.

To quote Tobias:

> the hot update chunks are also "chunk assets" and it looks like that the html-plugin generates a script tag for them.
> html-plugin should use the new `stats.entrypoints` data to generate the script tags. This contains all needed files for an entrypoint in correct order.

CC @jantimon. Looks like we need to fix this at html-webpack-plugin.

**Comment by voxmatt** [comment]
Super interesting. I hacked away at this for a number of days and I honestly can't recall what fixed it. I'm still using html-webpack-plugin as well, so that is the likely source but it must be in combination with something else because I'm not seeing this anymore. I ended up disabling multi-pass, which made a difference, but the way I solved this was reverting my entire branch and meticulously updating incrementally, testing, rolling back, etc... until I had something workable.

Sorry I can't be more help in diagnosing, but I do use html-webpack-plugin.

**Comment by bebraw** [comment]
@voxmatt Thanks! Removing `multiStep: true` from `HotModuleReplacementPlugin` fixed the behavior for me. I guess it's that specific mode that's broken when html-webpack-plugin is used.

**Comment by cortopy** [comment]
Like @voxmatt I can't say what fixed it for me either. I downgraded when this started happening, then I retried with newer versions weeks after. It's not happened again since.

@bebraw yes, I use html-webpack-plugin and I'm still using it with no issue on my part (fingers crossed!!)

**Comment by gavindoughtie** [comment]
@bebraw Removing multistep: true from HotModuleReplacementPlugin fixed my webpack2 hot-reload issue as well. (I also had upgraded to node 7.3, but was having the same issue until I removed multistep)
