### ISSUE TITLE
Require and parse webpack bundles

### ISSUE THREAD

**Issue by pvieira91** [webpack/webpack#2987]
**I'm submitting a feature request**

I have several internal libraries which I want to bundle separately. Some of them are 5/6 years old. Now, let's imagine I have a main product which includes those libraries (already bundled). 

I tried to do so, but when the libraries are bundled the require statements are transformed to something like __webpack_require(n) which results in this: 't.exports = image.hash.gif'. 

When compiling the main product (which requires those bundles), webpack does not parse/resolve the 't.exports = image.hash.gif' and therefore, those assets are not consider for the main product bundle. The only solution I see is to transform the assets of the libraries to base64 so that they end up embedded in the code.

Imo, webpack should be capable of parsing those __webpack__require__ and spit another bundle without ignoring the assets referenced on libraries. 

Are you aware of this? Are you planning to support this? Any workaround for now?

**Comment by pvieira91** [comment]
Sorry for insisting, does anyone have an (quick) answer for this?

**Comment by sokra** [comment]
You need to require the unbundled version of your library.

**Comment by pvieira91** [comment]
Thanks @sokra 
That seems the most reasonable think to do. I tried that approach and in fact it was the best option for us. However, it's important to mention that it comes with trade-offs. For example, as we use typescript and babel, we must enforce the same configuration for the main project and library. This might sound ok but when you have libraries 5 years older than the main app it becomes cumbersome. More over, the building time increases considerably. 
I know that webpack is this amazing tool that can perfom several optmizations and requiring libraries which are already bundled kinda beats the purpose but it would be really helpful. 

thank you

**Comment by sokra** [comment]
I know... I have currently no good solution for this. But I know the problem and hope to find a solution in long-term.
