### ISSUE TITLE
2.1.0-beta.22 - build hangs when non-web `target` specified.

### ISSUE THREAD

**Issue by thomb** [webpack/webpack#2990]
**I'm submitting a bug report**

**Webpack version:**
2.1.0-beta.22

**Please tell us about your environment:**
OSX 10.10.5

**Current behavior:**
When `target` is specified as any of `node`, `async-node`, `node-webkit` or `electron` the build never finishes it hangs at:

` 75% advanced module optimization`

This arose while attempting to build for `electron`

**Expected/desired behavior:**
This same config file worked without issues in `1.13.1`, I never even noticed this `advanced module optimization` step before updating to 2.1.0-beta.22

Below is my webpack config:
```
const autoprefixer = require('autoprefixer');
const path = require('path');
const webpack = require('webpack');

module.exports = {
	entry: {
		primary: ['./html/js/main.js']
	},
	module: {
		loaders: [{
			test: /\.js$/,
			include: [
				path.resolve(__dirname, "..", "..", "html"),
				path.resolve(__dirname, "..", "html"),
				path.resolve(__dirname, "..", "tests"),
				path.resolve(__dirname, "..", "node_modules/qs")
			],
			loader: 'babel?cacheDirectory'
		},
		{test: /\.jsx$/, loader: 'babel?cacheDirectory'},
		{test: /\.json/, loader: 'json'},
		{test: /\.less$/, loader: 'style!css?modules!postcss!less'},
		{test: /\.png$/, loader: 'file'},
		{test: /\.jpg$/, loader: 'file'},
		{test: /\.woff$/, loader: 'file'},
		{test: /\.woff2$/, loader: 'file'},
		{test: /\.svg$/, loader: 'file'}
	]},
	output: {
		path: path.resolve('./html/build/'),
		publicPath: '/build/',
		filename: 'bundle.js'
	},
	postcss: [autoprefixer],
	plugins: [
		// Ignore non-English moment.js locales
		// See: http://stackoverflow.com/questions/25384360
		new webpack.ContextReplacementPlugin(/moment[\/\\]locale$/, /en/),
		new webpack.optimize.UglifyJsPlugin({
			mangle: false
		}),
		new webpack.optimize.DedupePlugin(),
		new webpack.DefinePlugin({
			__DEV__: false,

			// Ensures React is running in production mode
			"process.env.NODE_ENV": '"production"'
		}),
		new webpack.NoErrorsPlugin(),
		new webpack.IgnorePlugin(/_deprecated_extensions/)
	],
	resolve: {
		fallback: [
			path.join(__dirname, "node_modules")
		]
	},
	resolveLoader: {
		root: path.join(__dirname, "node_modules")
	},
	target: 'electron'
};
```

And here is the output:
```
[10:26:36] $ npm run build:webp[ack 
NODE_ENV=production webpack --config webpack.config.js --progress

 75% advanced module optimization
^C                               
                                 
[11:11:44] $
```

Until that ` 75% advanced module optimization` I see regular progress.

 Is there anything in my `webpack.config.js` which is going to cause issues when building for the `electron` target? 

I have tried removing the `plugins`, `postcss`, `resolve` and `resolveLoader` to get this config to be as simple as possible, but I've seen no change in behaviour.

Apologies if this is considered a support request, it seemed to me likely to be an issue with the `2.1.0-beta.22` build.

Thanks in advance.

**Comment by bebraw** [comment]
Can you provide a standalone test case? Thanks.

**Comment by thomb** [comment]
Here goes. Its somewhat related to circular imports and the `require.ensure()` or at least that is my impression at this point

I'm willing to call the root issue of the circular imports a problem with this implementation, but I still would expect an error or a warning to be thrown.

[webpack-circular-import.zip](https://github.com/webpack/webpack/files/473718/webpack-circular-import.zip)
``` 
npm install
npm run build:web // Success
npm run build:electron // Hangs forever
```

In addition, I believe the infinite loop is actually in `lib/optimize/EnsureChunkConditionsPlugin.js` which appears to never have the `chunkCondition` satisfied. At the very least if the check of
`this.applyPluginsBailResult("optimize-modules-basic", this.modules)` is removed from the while loop on `lib/Compilation.js:546` the build does not go into an infinite loop

**Comment by thomb** [comment]
I just realized that I did not validate this against the `1.13.1` builld, so this might not be a correct test case. 

Apologies for that over sight, I will double check this test case shortly.

**Comment by EvNaverniouk** [comment]
A couple of additional items of note:

- This issue only occurs when using the `babel-loader`. Using the generic `script-loader` seems to work fine.
- This issue only occurs when using the `require.ensure([], (require) => cb(null, require('something')));` syntax. Using the generic `require()` seems to work fine.

**Comment by thomb** [comment]
Attached is a proper test case, which exhibits all the behaviours of the original issue:

- Builds successfully for both `web` and `electron` targets on `1.13.1`
- Builds successfully for `web` target on `2.1.0-beta.22`
- Build fails for `electron` target on `2.1.0-beta.22`

[webpack-circular-import.zip](https://github.com/webpack/webpack/files/475156/webpack-circular-import.zip)
