### ISSUE TITLE
Store relative path in the compiler stat for ignored modules

### ISSUE THREAD

**Issue by lvv83** [webpack/webpack#2991]
**I'm submitting a feature request**

**Webpack version:**
1.13.2

**Please tell us about your environment:**
Windows 10, Windows 7

**Current behavior:**
After including [es6-promise](https://www.npmjs.com/package/es6-promise) to my project I see absolute path inside comiler state json file. It is looks like

```
...
"node_modules\\es6-promise\\dist\\es6-promise.js": 61,
"node_modules\\webpack\\node_modules\\node-libs-browser\\node_modules\\process\\browser.js": 62,
"node_modules\\webpack\\buildin\\module.js": 63,
"ignored D:\\MyProject\\node_modules\\es6-promise\\dist vertx": 64,
...
```

**Expected/desired behavior:**
Relative path for ignored entry.

```
"ignored node_modules\\es6-promise\\dist vertx": 64,
```

**What is the motivation / use case for changing the behavior?**
It causes some problems with version control.

 #1315
I already implemented [rohitlodha's solution](https://github.com/webpack/webpack/issues/1315#issuecomment-243107287), but the problem still there when chunks collection grows. `manifest` chunk always added last. So dependent chunks like `vendor` get a new hash.

**Comment by lvv83** [comment]
Particular solution with `es6-promise` module is ignoring `vertx` dependency
```js
new webpack.IgnorePlugin(/vertx/)
```

**Comment by sokra** [comment]
yep need to be fixed

**Comment by jamestautges** [comment]
If the problem is just that one behavior and not something larger, #3147 should fix it.
