### ISSUE TITLE
Dynamic require does not support loader with dynamic query value

### ISSUE THREAD

**Issue by kevinlaw91** [webpack/webpack#2992]
**I'm submitting a bug report**
Dynamic require does not support loader with dynamic query value. It throws missing module error.
What I mean is code similar to below will compile into `!(function webpackMissingModule()...`

```js
require("!!someloader?query=" + dynamic_value + "!./path/to/file.ext");
```

In comparison, by giving it a static query value it will work:

```js
require("!!someloader?query=static-value!./path/to/file.ext");

// even dynamic file will work
require("!!someloader?query=static-value!./path/to/" + file);
```

**Webpack version:**
2.1.0-beta.22

**Reproduce**
The loader used is [svg-as-symbol-loader](https://github.com/bhovhannes/svg-as-symbol-loader)

```js
var files = {
	"id01": "./file1.svg",
	"id02": "./file2.svg"
};

for (var id in files) {
	if (files.hasOwnProperty(id)) {
		require("!!svg-as-symbol?id=staticid!" + files[id]);
		// this works
	}
}

for (var id in files) {
	if (files.hasOwnProperty(id)) {
		require("!!svg-as-symbol?id=" + id + "!" + files[id]);
		// Line above was compiled to:
		// !(function webpackMissingModule()...
	}
}
```

**Comment by sokra** [comment]
This doesn't work... only dynamic path values are supported. It must be statically buildable.

**Comment by CLL80** [comment]
I understand that this may not be an easy change but am not understanding why something like a dynamic path would be supported when a query string is not.

With a dynamic query string, the full file location information is available, [which is the stated requirement](https://webpack.js.org/api/module-methods/#import-).
