### ISSUE TITLE
dist files break r.js when dependencies include define() statements

### ISSUE THREAD

**Issue by robertmesserle** [webpack/webpack#2993]
**I'm submitting a bug report**

**Webpack version:**
1.13.2

**Please tell us about your environment:**
OSX 10.11.6

**Current behavior:**
This issue is related to requirejs/r.js and WebPack, and I also opened an issue against r.js here: https://github.com/requirejs/r.js/issues/931

The short version is that our project uses RequireJS.  We are trying to import [Microm](https://github.com/zzarcon/microm) which is built with WebPack.  The problem is that Microm imports its own dependencies, resulting in the dist file including multiple instances of `define()`.  This works fine when just using RequireJS, but breaks in `r.js`.

[This](https://github.com/zzarcon/microm/blob/master/dist/microm.js#L1143) is the part in the resulting file that causes `r.js` to break.

**Expected/desired behavior:**
The resulting code should be valid in RequireJS and r.js.
- **Browser:** all
- **Language:** ES6

**Comment by sokra** [comment]
We could add these `var define = undefined;` to the UMD and AMD library target.

**Comment by wdhorton** [comment]
I can work on this
