### ISSUE TITLE
Watch mode doesn't work in specific folder

### ISSUE THREAD

**Issue by aparshin** [webpack/webpack#2994]
**I'm submitting a bug report**

**Webpack version:**
1.13.2

**Please tell us about your environment:**
Windows 7

**Current behavior:**

Minimal test case.

Consider the following JS file `index.js` (the only file in a folder):

```
var k = 0;
```

I'm trying to start webpack in watch mode:

```
webpack index.js bundle.js --watch
```

When my work folder is `c:\dev\`, everything works as expected. But if I work in folder `c:\Program Files (x86)\Apache Software Foundation\Apache2.2\htdocs\`, webpack doesn't rebuild project after I change `index.js` file.

**Expected/desired behavior:**
Watch mode should work in any folder.

**Notes**
I tried to understand the source of the problem. Looks like npm module `is-glob` (dependency list: `webpack`->`watchpack`->`chokidar`->`is-glob`) thinks that `c:\Program Files (x86)\Apache Software Foundation\Apache2.2\htdocs\` is a glob and `watchpack` tries to listen changes in wrong not existing directory (`c:\Program Files x86\Apache Software Foundation\Apache2.2\htdocs\`?).

Maybe, it will help you to fix this bug!

**Comment by Jorenm** [comment]
I can confirm this. I was having issues getting my project to watch, and moved it into C:\node\myproject from C:\Program Files (x86)\Ampps\www\myproject and it started watching fine with identical configuration.

**Comment by Jorenm** [comment]
Turns out the core of this issue is caused by chokidar. It includes an old version if is-glob. There's a newer version which resolves the issue.

**Comment by bebraw** [comment]
Moved to https://github.com/webpack/webpack-cli/issues/16 .
