### ISSUE TITLE
"/* #sourceMappingURL= ... */" in a JS comment triggers a webpack errors

### ISSUE THREAD

**Issue by vicb** [webpack/webpack#2995]
/ref https://github.com/angular/angular/issues/11584

didn't reproduce the bug myself, sorry.

**I'm submitting a bug report**

**Webpack version:**
webpack: "2.1.0-beta.21",
webpack-dev-server: "2.1.0-beta.2",

**Please tell us about your environment:**
node: 4.4.7,
OSX

**Current behavior:**
`// all comments except inline source mapping ("/* #sourceMappingURL= ... */")` is parser a "real" sourceMappingURL by webpack:

```
WARNING in ./~/@angular/compiler/src/shadow_css.js
Cannot find SourceMap '...': Error: Can't resolve './...' in '/Users/simon/workspace/project/front/node_modules/@angular/compiler/src'
 @ ./~/@angular/compiler/src/style_compiler.js 11:0-41
 @ ./~/@angular/compiler/src/compiler.js
 @ ./~/@angular/compiler/src/index.js
 @ ./~/@angular/compiler/index.js
 @ ./~/@angular/platform-browser-dynamic/src/platform-browser-dynamic.js
 @ ./~/@angular/platform-browser-dynamic/index.js
 @ ./src/main.browser.ts
 @ multi main
```

**Expected/desired behavior:**
no warning
- **What is the expected behavior?**
  _(looks like the same section as above, should I open a bug for updating the issue template ?)_
- **Language:** [TypeScript 2]

**Comment by jhnns** [comment]
I've put the comment in a JS file like this...

```javascript
// all comments except inline source mapping ("/* #sourceMappingURL= ... */")
```

... and gave it to webpack and everything is working fine (webpack 2.1.0-beta.22).

I think we need more information on this.

**Comment by vicb** [comment]
@Simon-Briggs  reported this with angular.

Simon could you please help reproducing the issue in a minimal project ?

Otherwise let's close this issue. Thanks for your help.

**Comment by sokra** [comment]
you probably used the source-map-loader, did you?

**Comment by vicb** [comment]
If @Simon-Briggs does not give more information, I guess we can close the issue...

**Comment by Simon-Briggs** [comment]
@sokra  Yes I used the source-map-loader.

**Comment by sokra** [comment]
the bug is in the source-map-loader

**Comment by schabluk** [comment]
I have it with react-intl

`./~/intl-messageformat/lib/main.js
Cannot find SourceMap 'main.js.map': Error: Cannot resolve 'file' or 'directory' ./main.js.map in /Users/lusch/playground/play-project/node_modules/intl-messageformat/lib`

I'm able to supress it in the terminal, by setting:
```
devServer: {
  stats: {
    warnings: false
  }
}
```
But it's still visible in the browser console.
