### ISSUE TITLE
ES6 support for val-loader / this.exec

### ISSUE THREAD

**Issue by tuures** [webpack/webpack#2996]
**I'm submitting a bug report**

**Webpack version:**
2.1.0-beta.19

**Please tell us about your environment:**
OSX 10.x

**Current behavior:**
Using `val-loader` /  calling `this.exec(es6content, this.resource);` in loader context results in `SyntaxError: Unexpected token import`

**Expected/desired behavior:**
I'd have expected webpack to handle ES6 `import` statements (potentially with tree-shaking etc.) in similar fashion as it does in entry modules.

**What is the motivation / use case for changing the behavior?**

I'm trying to evaluate es6 module at compile time. More specifically render React components into static html files.

**Known workarounds**
I'm using babel loader first to convert `imports` but that eliminates tree-shaking etc.

**Comment by andreypopp** [comment]
I think this is unfair to expect this from `val-loader`: just use more modern Node version which support ES2015 features.

**Comment by tuures** [comment]
@andreypopp node does not yet support ES modules although many other features are supported

**Comment by Kovensky** [comment]
You will still need a babel-loader, maybe with an environment that has nothing but the modules-to-commonjs transform. Alternatively, you will need to webpack2 your file into a standalone module before evaluating it.

Node v6 implements everything ES6 but import/export, as nothing is yet decided on how modules will actually be _loaded_ by import. Webpack2 just does its best guess at what would be the most forward compatible with the real thing.
