### ISSUE TITLE
Error: a dependency to an entry point is not allowed

### ISSUE THREAD

**Issue by speigg** [webpack/webpack#300]
Why not?

I'd like to create one bundle which extends another, both in the same project.

**Comment by mjackson** [comment]
+1 for eliminating this workaround

**Comment by chrisguerrero** [comment]
+1

I have a base module that is included in many of my entry points, but needs to be an entry point itself as a fallback. 

P.S. The workaround works as expected

**Comment by tjwudi** [comment]
+1, Very weird ... I've been confusing about this issue for couple hours :(

**Comment by miljan-aleksic** [comment]
+1, seems every single developer is loosing time with this

**Comment by jonathandion** [comment]
+1

**Comment by tlrobinson** [comment]
+1

**Comment by jhutchins** [comment]
+1

**Comment by sirlancelot** [comment]
Why would you want to `require()` an entry point? Entry point code should only be run once. If you're `export`ing logic in your entry point module, you're probably better off moving that functionality in to a re-usable module.

#not-a-bug

**Comment by cameronjroe** [comment]
+1 this seems odd..

```js
module.exports = {
  entry: {
    'react-star-rating': ['./src/Component.jsx'],
    'demo': './src/demo.jsx'
  },
  output: {
    path: __dirname + '/dist',
    filename: '[name].js'
  },
...
```

**Comment by Jias** [comment]
+1

**Comment by sokra** [comment]
It's fixed in the webpack-2 branch...

**Comment by jaylaw81** [comment]
+1

**Comment by sunny-xue** [comment]
http://webpack.github.io/docs/configuration.html#entry

**Comment by maxmaximov** [comment]
+1

**Comment by dshen-expert360** [comment]
+1 that saves me lots of time, thanks

**Comment by VaJoy** [comment]
+1 huge WEIRD....

**Comment by wjlow** [comment]
+1

**Comment by etkarl** [comment]
+1

**Comment by ace-han** [comment]
+1

**Comment by jpanganiban** [comment]
:+1:

**Comment by designeng** [comment]
+1

**Comment by chenzhihao** [comment]
+1

**Comment by cycold** [comment]
+1

**Comment by sokra** [comment]
> It's fixed in the webpack-2 branch...

As workaround you can specify an array in the entry option: `entry: ["./entry"]`
