### ISSUE TITLE
Using output.library breaking in IE 10

### ISSUE THREAD

**Issue by nodesocket** [webpack/webpack#3004]
Using:

````javascript
output: {
    path: path.join(__dirname, 'dist'),
    filename: 'my-lib.js',
    library: 'MyLib'
}
````

Works in Chrome, FireFox, and Safari latest. However in IE 10 console when trying to reference MyLib:

````javascript
typeof MyLib
   undefined
````

Also, in the JavaScript console of IE 10 seeing:

````
Unable to get property 'MyLib' of undefined or null reference
````

**Comment by nodesocket** [comment]
Hi @sokra, so is this a known problem?

**Comment by sokra** [comment]
Nit known to me. But interessting

**Comment by nodesocket** [comment]
Ok, I figured it out. If I attempt to use `MyLib` in the library itself this causes the error in IE. For some reason Firefox and Chrome don't break.

Example:


````javascript
// lib.js
'use strict';

var utils = require('./utils');

module.exports.setProjectId = function(projectId) {
    this.projectId = projectId;
};

utils.ready(function() {
    // this causes the error in IE 10
    MyLib.setProjectId('foobar');
});
````

**Comment by sokra** [comment]
ok nice... looks like a browser bug
