### ISSUE TITLE
require.ensure with ternary operator not splitting code

### ISSUE THREAD

**Issue by steinbachr** [webpack/webpack#3005]
**I'm submitting a bug report**

**Webpack version:**
1.13.2

**Please tell us about your environment:**
OSX 10.11.1

**Current behavior:**
When using `require.ensure` with a ternary operator, webpack complains that "require function is used in a way in which dependencies cannot be statically extracted" and fails to properly code split.

**Expected/desired behavior:**
webpack properly splits the require.ensure code into two (or more) chunks, one for the positive result of the ternary operator and one for the negative.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.** 
Demo of problem: https://gist.github.com/steinbachr/6d4c9b05c8bbdb049bdfe90febeda199

* **Browser:** all
 
* **Language:** ES5

**Comment by sokra** [comment]
You can rewrite it to `if-else`. `require.ensure` doesn't support dynamic expressions in it's argument. We won't change this, because `require.ensure` eventually become deprecated in favor of ES6 Modules.
