### ISSUE TITLE
UglifyJs needs an upgrade

### ISSUE THREAD

**Issue by Ciantic** [webpack/webpack#3011]
I'm having issues with UglifyJsPlugin in webpack 2.1.0-beta.22, it works without mangling but not with it turned on. However with command line uglifyJs the mangling works, it's newer version.

Could someone upgrade the uglifyjs dependency?

Thanks.

**Comment by sokra** [comment]
Please send a PR

**Comment by SpaceK33z** [comment]
See PR #3016.
