### ISSUE TITLE
Webpack with babel-loader don't process js files from sibling directories

### ISSUE THREAD

**Issue by hyzhak** [webpack/webpack#3014]
**I'm submitting a bug report**

**Webpack version:**
1.13.2 and  2.1.0-beta.22

**Please tell us about your environment:**
OSX 10.x / Linux

**Current behavior:**
doesn't process js files from sibling/parent directories

**Expected/desired behavior:**
process 

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.** 
here is little example project https://github.com/hyzhak/webpack-babel-folder-issue
that has 2 files: 

1. inside of build directory 
2. outside of directory. 

And as you can see from logs 2nd one is not processed correct so it fails on test https://travis-ci.org/hyzhak/webpack-babel-folder-issue/builds/161070751#L250

* **What is the expected behavior?**
both files should be processed by webpack and babel-loader 

* **Browser:** [all] 
 
* **Language:** [all]

**Comment by tuures** [comment]
the `.babelrc` is in `tests-client` so babel is doing it's transformations only there?, see last paragraph https://babeljs.io/docs/usage/babelrc/, try moving it to project root

**Comment by hyzhak** [comment]
@tuures I can't do this in that project. I can only hold front-end files inside of `/test-client` directory.

**Comment by hyzhak** [comment]
@tuures btw thanks for solution. Here is (https://github.com/hyzhak/webpack-babel-folder-issue/tree/feature/babelrc-for-sources) a branch with `.babelrc` inside of `/src` directory with additional `es2015` installed for `/src` directory and it works like charm tests are passed in TravisCI (https://travis-ci.org/hyzhak/webpack-babel-folder-issue/builds/161427867).  So maybe @bebraw you can close this issue if it is correct behaviour for webpack + babel-loader.

**Comment by tuures** [comment]
@hyzhak You're welcome. If you can't place `.babelrc` to project root, an alternative is to give babel config through the loader, something like this:
```
module: {
  loaders: [
    {
      test: /\.js$/,
      exclude: /(node_modules|bower_components)/,
      loader: 'babel',
      query: {
        presets: ['es2015']
      }
    }
  ]
}
```
Remember, the default config for babel is to do nothing. Happy coding!

**Comment by damianobarbati** [comment]
What if I'm locally testing (without `npm link` mess) and I have:
```
dep1
project
      package.json
      webpack.config.js
      index.js <= import dep from '../dep1'
```

**Comment by damianobarbati** [comment]
After one year I got year again looking for the same thing!
