### ISSUE TITLE
configuration.output.devtoolModuleFilenameTemplate schema not working for strings.

### ISSUE THREAD

**Issue by donaldpipowitch** [webpack/webpack#3020]
**I'm submitting a bug report**

**Webpack version:**
2.1.0-beta.23

**Please tell us about your environment:**
OSX 10.x

**Current behavior:**

```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.output.devtoolModuleFilenameTemplate should be one of these:
   string | function
```

```
  output: {
    path: path.join(__dirname, 'dist'),
    filename: 'index.js',
    // don't use webpack:/// protocol for source maps
    devtoolModuleFilenameTemplate: './[resource-path]',
    sourcePrefix: ''  // removes tabs before multiline strings
  },
```

**Expected/desired behavior:**

No error.

I really don't know why this error appears. The error message and schema say that a string is valid and allowed. If I change `devtoolModuleFilenameTemplate`from ` './[resource-path]'` to `() =>  './[resource-path]'` everything works.

**Comment by sokra** [comment]
@gajus

**Comment by Delagen** [comment]
#3019

**Comment by gajus** [comment]
This has been fixed in https://github.com/webpack/webpack/pull/3024
