### ISSUE TITLE
configuration.module has an unknown property 'preLoaders'

### ISSUE THREAD

**Issue by QWp6t** [webpack/webpack#3026]
**I'm submitting a bug report**

**Webpack version:**
2.1.0-beta.23

**Please tell us about your environment:**
Windows 10

**Current behavior:**
When attempting to run webpack, I get told that `preLoaders` is an invalid property on `configuration.module`.

```
 - configuration.module has an unknown property 'preLoaders'. These properties are valid:
   object { rules?, loaders?, noParse?, unknownContextRequest?, unknownContextRegExp?, unknownContextRecursive?, unknownContextCritical?, exprContextRequest?, exprContextRegExp?, exprContextRecursive?, exprContextCritical?, wrappedContextRegExp?, wrappedContextRecursive?, wrappedContextCritical? }
   Options affecting the normal modules (`NormalModuleFactory`).
```

**Expected/desired behavior:**
It does not appear to be documented anywhere that `preLoaders` have been removed or have been modified in some way as to yield these results, so I would expect that it would pass schema validation.

Reduced testcase as follows (change entry/output as needed):

**webpack.config.js**
```js
module.exports = {
  entry: 'src/index.js',
  output: {
    filename: 'dist/bundle.js'
  },
  module: {
    preLoaders: [{
      test: /\.js$/,
      loader: 'eslint'
    }]
  }
};
```

**package.json**
```js
{
  "devDependencies": {
    "eslint": "^3.5.0",
    "eslint-loader": "^1.5.0",
    "webpack": "^2.1.0-beta.23"
  }
}
```

**Comment by TheLarkInn** [comment]
This is documented in our release notes: https://github.com/webpack/webpack/releases

You can also refer to the example PR listed under 'Migration Examples' for more assistance.

**Comment by QWp6t** [comment]
Oh, I'm stupid. I should have known to look there. Thanks for the quick reply. I appreciate it.

**Comment by TheLarkInn** [comment]
No problem.

**Comment by Kielan** [comment]
Maybe I should have known also, I got the same error with postcss for local webfonts.

**Comment by JustinYi922** [comment]
@TheLarkInn I am sorry。Can you tell me the reason.I have the same problem,too.

**Comment by TheLarkInn** [comment]
Ah they should definitely update the guide! See webpack.js.org/guides/migrating to correct your problem.

**Comment by JustinYi922** [comment]
@TheLarkInn Thank you。

**Comment by ngankt2** [comment]
module: {
-   preLoaders: [
+   rules: [
      {
      test: /\.js$/,
      loader: 'eslint'
      }
    ]
  }

**Comment by nyuspc** [comment]
module.loaders migrate to module.rules. If you are using webpack 2+, change your config file.
