### ISSUE TITLE
Error: Refused to execute script from 'xxxx/app.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

### ISSUE THREAD

**Issue by wellyshen** [webpack/webpack#3027]
Hi guys, I update the webpack to beta.23, when I run it in development every thing fine, but once I run it in production, the error occurs:

> Refused to execute script from 'http://127.0.0.1:8080/dist/vendor.30ac4c9b26b20f70918e.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

I don't know why, anyone has idea for this?

Here's my webpack config :
```
/* eslint-disable */

var path = require('path');
var webpack = require('webpack');
var autoprefixer = require('autoprefixer');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var StyleLintPlugin = require('stylelint-webpack-plugin');

var nodeEnv = process.env.NODE_ENV || 'development';
var isDev = nodeEnv !== 'production';

var WebpackIsomorphicToolsPlugin = require('webpack-isomorphic-tools/plugin');
var webpackIsomorphicToolsPlugin = new WebpackIsomorphicToolsPlugin(require('./webpack-isomorphic-tools.config')).development(isDev);

// Setting the plugins for development/prodcution
function getPlugins() {
  var plugins = [];

  plugins.push(
    // Setup global variables for app
    new webpack.DefinePlugin({
      'process.env': { NODE_ENV: JSON.stringify(nodeEnv) },
      __CLIENT__: JSON.stringify(true),
      __SERVER__: JSON.stringify(false),
      __DEV__: JSON.stringify(isDev),
    }),
    // Style lint
    new StyleLintPlugin({
      syntax: 'scss',
      failOnError: styleLintFailOnError,
    }),
    new webpack.NoErrorsPlugin(),
    webpackIsomorphicToolsPlugin
  );

  var eslintFailOnError = true; // Disable js lint error terminating here
  var styleLintFailOnError = true;  // Disable style lint error terminating here
  var postcssParams = [autoprefixer({ browsers: ['last 2 versions'] })];

  if (isDev) {
    plugins.push(
      new webpack.LoaderOptionsPlugin({
        options: {
          eslint: {
            failOnError: eslintFailOnError,
          },
          postcss: postcssParams,
          debug: true,
        }
      }),
      new webpack.IgnorePlugin(/webpack-stats\.json$/),
      new webpack.HotModuleReplacementPlugin()
    );
  } else {
    plugins.push(
      new webpack.LoaderOptionsPlugin({
        options: {
          eslint: {
            failOnError: eslintFailOnError,
          },
          postcss: postcssParams,
          debug: false,
          minimize: true,
        }
      }),
      new webpack.optimize.CommonsChunkPlugin({
        name: 'vendor',
        filename: '[name].[chunkhash].js',
        minChunks: Infinity,
      }),
      new ExtractTextPlugin({ filename: '[name].[chunkhash].css', allChunks: true }),
      new webpack.optimize.UglifyJsPlugin({
        compress: { screw_ie8: true, warnings: false },
        output: { comments: false },
        sourceMap: false,
      }),
      new webpack.optimize.OccurrenceOrderPlugin(true),
      new webpack.optimize.DedupePlugin()
    );
  }

  return plugins;
}

// Setting  the entry for development/prodcution
function getEntry() {
  var entry;

  if (isDev) {
    entry = {
      app: [
        'webpack-hot-middleware/client',
        'react-hot-loader/patch',
        './src/client.js',
      ],
    };
  } else {
    entry = {
      app: './src/client.js',
      // Register vendors here
      vendor: [
        'babel-polyfill',
        'react', 'react-dom', 'react-addons-shallow-compare',
        'redux', 'react-redux',
        'redux-thunk',
        'immutable',
        'redux-immutable',
        'react-router',
        'react-router-redux',
        'react-helmet',
        'axios',
      ],
    };
  }

  return entry;
}

// Setting webpack settings
module.exports = function (CSSModules) {
  return {
    cache: isDev,
    // debug: isDev,
    devtool: isDev ? 'cheap-module-eval-source-map' : 'hidden-source-map',
    context: path.join(__dirname, '../..'),
    entry: getEntry(),
    output: {
      path: path.join(__dirname, '../../public/dist'),
      publicPath: '/dist/',
      filename: isDev ? '[name].[hash].js' : '[name].[chunkhash].js',
      chunkFilename: '[name].[chunkhash].js',
    },
    module: {
      rules: [
        {
          test: /\.jsx?$/,
          exclude: /node_modules/,
          loaders: ['babel', 'eslint'],
          query: {
            cacheDirectory: isDev,
          },
        },
        { test: /\.json$/, loader: 'json' },
        {
          test: /\.css$/,
          loader: isDev ?
            'style!css?localIdentName=[name]__[local].[hash:base64:5]&' + (CSSModules ? 'modules' : '') + '&sourceMap&-minimize&importLoaders=1!postcss'
            : ExtractTextPlugin.extract({ fallbackLoader: 'style', loader: 'css?' + (CSSModules ? 'modules' : '') + '&sourceMap&importLoaders=1!postcss' }),
        },
        {
          test: /\.scss$/,
          loader: isDev ?
            'style!css?localIdentName=[name]__[local].[hash:base64:5]&' + (CSSModules ? 'modules' : '') + '&sourceMap&-minimize&importLoaders=2!postcss!sass?outputStyle=expanded&sourceMap'
            : ExtractTextPlugin.extract({ fallbackLoader: 'style', loader: 'css?' + (CSSModules ? 'modules' : '') + '&sourceMap&importLoaders=2!postcss!sass?outputStyle=expanded&sourceMap&sourceMapContents' }),
        },
        { test: /\.woff(2)?(\?v=\d+\.\d+\.\d+)?$/, loader: 'url?limit=10000&mimetype=application/font-woff' },
        { test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/, loader: 'url?limit=10000&mimetype=application/octet-stream' },
        { test: /\.eot(\?v=\d+\.\d+\.\d+)?$/, loader: 'file' },
        { test: /\.svg(\?v=\d+\.\d+\.\d+)?$/, loader: 'url?limit=10000&mimetype=image/svg+xml' },
        {
          test: webpackIsomorphicToolsPlugin.regular_expression('images'),
          // Any image below or equal to 10K will be converted to inline base64 instead
          loaders: [
            'url?limit=10240',
            'image-webpack?bypassOnDebug',  // Using for image optimization
          ],
        },
      ],
    },
    resolve: {
      extensions: ['.js', '.jsx', '.json'],
      modules: [
        'src',
        'node_modules',
      ],
    },
    plugins: getPlugins(),
  };
};

```

**Comment by sokra** [comment]
Does the file exists at this location? If yes, it's a server configuration issue. If no, where is the file?

**Comment by wellyshen** [comment]
Yes the file exist at the location, and the error won't happened on webpack2-beta.21

**Comment by sokra** [comment]
the server respond with the wrong mimetype...

**Comment by wellyshen** [comment]
@sokra,

Have you tried my repo? I can run it without the error occurs on beta.21, but on beta.23 the error will occur

**Comment by wellyshen** [comment]
Hello @sokra,

I fixing it by remove the 'eslint-loader' from my config, close this issue.

**Comment by etimoyoita** [comment]
Simple thing I tried...

in calling this file within a view, **add a trailing slash, _like this:**_

`<script src="**/**filename"></script>`

**Comment by Aftabnack** [comment]
Same issue with Webpack 4 based output.
It works when I do hard reload, it fails I just refresh.

@sokra, any pointers?

I don't suppose `eslint-loader` should be causing this problem right?

**Comment by Aftabnack** [comment]
Never mind. It is because I have multiple instances of servers serving the app.

All of them are built separately, and for some reason, using `contentHash` is not giving same output on both of them.

**Comment by kannancet** [comment]
Spend several hours on this. Realised that there was a service open on `8080` port and `npm run start-hot-dev` didn't throw any errors, but silenced and showed compile was successful. I killed the service and it worked!

**Comment by shenst1** [comment]
same as @kannancet, I had two rails applications running a webpack service at 8080 and they conflicted causing that MIME type error

**Comment by kannancet** [comment]
@udahari - `lsof -i :80 -S` get the PID and then `kill -9 PID` and restart your webpack process.

**Comment by Aftabnack** [comment]
@udahari In my case the issue was the file that was requested didn't exist for the server to serve. And my server had a fallback to serve `index.html` which caused this error.

**Comment by Aftabnack** [comment]
@udahari For me the issue was that the file that was requested didn't exist on the server. And it was serving the fallback `index.html` instead. I mistook it to think the contentHash wasn't consistent across multiple rebuilds.

**Comment by udahari** [comment]
@Aftabnack I think I have the same problem, So how do you solve the issue ? I have restart the webpack but still have the issue.

**Comment by Aftabnack** [comment]
@udahari For me it happened since I have two different set of servers load balancing my request. And they didn't have same files.

I think we are unnecessarily disturbing others on this thread. You mind taking this conversation somewhere else?

**Comment by iamawaisakram** [comment]
My solution to this problem is to set 
--> cache_manifest: false 
in your webpacker.yml file! 
By default it is true!

**Comment by iamawaisakram** [comment]
My solution to this problem is to set 
--> cache_manifest: false 
in your webpacker.yml file! 
By default it is true!

**Comment by daschi** [comment]
I also got this issue and restarting the server was not changing the result. Only after I restarted my server and opened it in a new tab and also in incognito mode, I eventually saw the actual error which was a ReferenceError.

**Comment by BonBonSlick** [comment]
Same issue

**Comment by saanderson1987** [comment]
This was my issue, not sure why I didn't need this in my other app: https://stackoverflow.com/questions/48157632/loading-a-bundle-js-file-from-webpack-changes-mime-type-to-text-html

**Comment by Rudra51299** [comment]
> @udahari For me the issue was that the file that was requested didn't exist on the server. And it was serving the fallback `index.html` instead. I mistook it to think the contentHash wasn't consistent across multiple rebuilds.

@Aftabnack , So how did you resolved this issue then. In my case, let say I have one change in my js file. Now when I deploy my changes in only 1 host and not 2 other, there are 404 when requesting js files because they are not found. I believe this is due to the fact that 1 host has different contenthash and other 2 have different. But how can we resolve this issue then ?

**Comment by skyshy0707** [comment]
same issue. I rebuild many times but main.js (in my case) could not be loaded at the page. If i redirect at url which are not matched with router paths i see only vue warning in console, not errors. I use webpack 5.103.0

**Comment by alexander-akait** [comment]
@skyshy0707 Check your publish path, mostly you have invalid value - not the same as in your browser, or `script`/`link` tags have wrong URLs

**Comment by skyshy0707** [comment]
@alexander-akait i have not set publicPath do you mean , right ? But now, I have set output as:

```
const path = require('path-browserify')
const dist = path.resolve(__dirname, '../src/static')

module.exports = {
  //..
  output: {
      publicPath: dist,
  }
  //...
}
```

... And it solve 404 error of non found script, but in my pages nothing render beside index.html

**Comment by alexander-akait** [comment]
I mean you have problems between `dist` and URLs in `script`/`link` tag, `text/html` means you got 404 and dev middleware render html, check your code in dev tools

**Comment by skyshy0707** [comment]
@alexander-akait I suppose that script have wrong url due to something missed in webpack config. But i did set static where the main.js are located:


```
const path = require('path-browserify')
const dist = path.resolve(__dirname, '../src/static')

module.exports = {
  //..
  static: [
        {
          directory: path.resolve(__dirname, '../src')
        },
        {
          directory: dist
        }
      ],
  //...
}

```

main.js is located in ../src relatively to webpack config file.

What i shoould do next i don't know, Usually if some file are not found at the browser request then it is sooner related to the wrong static settings.

**Comment by alexander-akait** [comment]
@skyshy0707 Usually server returns 404, your should not to set to `src` static files (you have source files there, source files should not be exposed to public scope), by default all webpack assets are storing in `dist` and you don't need to add `dist` to static, webpack-dev-server handle them by `publicPath` (if it is not provided they are relative to `dist`), shortly:

1. Static assets for static assets, which already generated, like favicon.png, manifest files, robots.txt and etc
2. By default all generated files by webpack storing in `dist`, i.e. you should use `script src="/dist/main.js"` to get them
3. If you want to use custom directory, please set `output.path` to your directory name, webpack-dev-server handle them automatically

**Comment by skyshy0707** [comment]
I did used this before and have same issue:

> 3\. If you want to use custom directory, please set `output.path` to your directory name, webpack-dev-server handle them automatically

Problem only with endpoints of type '/[\s]?/:someParam' with the path param and they are differ from main '/'

```
const routes = [
    { path: '/', component: Dashboard, name: 'dashboard' },
    { path: '/lesson/:id', component: Lesson, name: 'lesson'  //problem endpoint
]
```

**Comment by skyshy0707** [comment]
Hell! I need to add publicPath at all: 

```

const path = require('path-browserify')
const dist = path.resolve(__dirname, '../src/static')

module.exports = {
  //..
  output: {
      publicPath: dist,
      publicPath: '/',
  }
  //...
}
```

... and it's my main route. It works.
