### ISSUE TITLE
ERROR in unknown runtime environment

### ISSUE THREAD

**Issue by oojacoboo** [webpack/webpack#3028]
**I'm submitting a bug report**

**Webpack version:**
1.13.2

**Please tell us about your environment:**
OSX 10.12

While running webpack-dev-server, I get the following error...

'ERROR in unknown runtime environment'

This is happening on the CLI
- **Language:**
  ES6

**Comment by bebraw** [comment]
Can you set up a standalone project illustrating this? There's not enough information to debug.
