### ISSUE TITLE
Cannot resolve module 'fs'

### ISSUE THREAD

**Issue by oojacoboo** [webpack/webpack#3029]
**I'm submitting a bug report**

**Webpack version:**
1.13.2

**Please tell us about your environment:**
OSX 10.12

Having the exact same issue as #689 and was requested to open a new issue.
 
* **Language:**
ES6

**Comment by bebraw** [comment]
Can you set up a standalone project so it's possible to debug this? Thanks.

**Comment by sokra** [comment]
Trying to use the filesystem in the browser is a hint that one of your dependency is not suited for in browser usage. You may file a issue on this dependency.

**Comment by oojacoboo** [comment]
Assumption that it was trying to be used in the browser was incorrect.  I did need to register the externals for `winston` and `fs` within the webpack config.  Thanks.
