### ISSUE TITLE
Add -r (require) option to webpack cli

### ISSUE THREAD

**Issue by whitecolor** [webpack/webpack#3030]
Why not add `-r (require)` option that would take the list of modules that will be required before requiring config file? (actually this would be passed to `node -r`). That would allow to use config in different formats more easily.

``` bash
> webpack -r ts-node/register  ...
```

``` bash
> webpack -r babel-register ...
```

The same thing would be useful for webpack-dev-server.

**Comment by TheLarkInn** [comment]
Would be a useful feature. I think a PR for this would be happily accepted.

**Comment by whitecolor** [comment]
I've mad a PR for this https://github.com/webpack/webpack/pull/3290

**Comment by sokra** [comment]
Different config formats are already supported. Just name the config file `webpack.config.ts` or `webpack.config.babel.js`

**Comment by whitecolor** [comment]
@sokra and who will compile `webpack.config.ts`?
If I start `webpack` in folder with `webpack.config.ts` it just gives an error on TS syntax.

**Comment by whitecolor** [comment]
@sokra could you elaborate on this? and who will compile webpack.config.ts?
If I start webpack in folder with webpack.config.ts it just gives an error on TS syntax.
