### ISSUE TITLE
Schema regards `debug` as invalid

### ISSUE THREAD

**Issue by mAAdhaTTah** [webpack/webpack#3032]
**I'm submitting a bug report**

**Webpack version:**
2.1.0-beta.22

**Please tell us about your environment:**
OSX 10.x

**Current behavior:**
`debug` as a key in the config is regarded as invalid by the new schema validation.

**Expected/desired behavior:**
Either this is deprecated configuration or should be regarded as valid by the schema.

**Comment by sokra** [comment]
https://github.com/webpack/webpack.js.org/blob/develop/content/how-to/upgrade-from-webpack-1.md#debug
