### ISSUE TITLE
DllReferencePlugin [HMR] Nothing hot updated. 

### ISSUE THREAD

**Issue by baizn** [webpack/webpack#3035]
when I use DllReferencePlugin , HotModuleReplacementPlugin and react-hmre doesn't work, but use CommonsChunkPlugin, that is wroking fine. why ?   what should I do that use DllReferencePlugin  and HotModuleReplacementPlugin  & react-hmre is working fine.
![Uploading image.png…]()

**Comment by baizn** [comment]
ok, detail information is here.
First: 
![image](https://cloud.githubusercontent.com/assets/9443867/18698324/c3dc53c6-7ffb-11e6-93ae-a5be3bbedf7f.png)

second:
![image](https://cloud.githubusercontent.com/assets/9443867/18698340/e1fc840c-7ffb-11e6-9d1a-d2bea12604bd.png)

now, when I change some files, HotModuleReplacementPlugin and react-hmre is not working, Look
![image](https://cloud.githubusercontent.com/assets/9443867/18698352/0fbf4a14-7ffc-11e6-9935-21fc80747efb.png)

server already reloaded.
![image](https://cloud.githubusercontent.com/assets/9443867/18698361/2f17ac9e-7ffc-11e6-89c0-71e8477ccede.png)

what should I do that use DllReferencePlugin and HotModuleReplacementPlugin & react-hmre is working fine.

**Comment by sokra** [comment]
Did you include both entry points (app.js and dev.js) in the HTML? (There must only be a single entry point per page).

**Comment by baizn** [comment]
yes，include them。

**Comment by baizn** [comment]
what should I do that use DllReferencePlugin and HotModuleReplacementPlugin & react-hmre is working fine？
