### ISSUE TITLE
problem about webpack with sequelize

### ISSUE THREAD

**Issue by keyiis** [webpack/webpack#3036]
Has somebody try use webpack with sequelize and sqlite3(nodejs orm framework),i tried for a long time without success :disappointed: 
below is my question link
https://github.com/sequelize/sequelize/issues/6142

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. 

Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md).
