### ISSUE TITLE
LoaderOptionsPlugin makes my config unusable

### ISSUE THREAD

**Issue by Martin-Wegner** [webpack/webpack#3038]
**I'm submitting a bug report**

**Webpack version:**
2.1.0-beta.24

**Please tell us about your environment:**
Linux

**Current behavior:**
This config runs without any problem and warning:

```
module: {
  rules: [
    {
      test: /\.ts$/,
      include: helpers.root('src', 'app'),
      loader: 'tslint',
      enforce: 'pre',
      options: {
        failOnHint: true
      }
    }, {
```

But when using this config:

```
  module: {
    rules: [
      {
        test: /\.ts$/,
        include: helpers.root('src', 'app'),
        loader: 'tslint',
        enforce: 'pre'
      }, {
...
    new webpack.LoaderOptionsPlugin({
      options: {
        tslint: {
          failOnHint: true
        }
      }
    }),
```

I get those errors:

> ERROR in ./~/css-loader?{"sourceMap":true}!./~/font-awesome/css/font-awesome.css
> Module build failed: TypeError: Path must be a string. Received undefined
> 
> ERROR in ./~/css-loader?{"sourceMap":true}!./~/bootstrap/dist/css/bootstrap.css
> Module build failed: TypeError: Path must be a string. Received undefined
> 
> ERROR in ./~/bootstrap/dist/css/bootstrap.css
> Module build failed: ModuleBuildError: Module build failed: TypeError: Path must be a string. Received undefined
> 
> ERROR in /work/zst/client/node_modules/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!/work/zst/client/node_modules/style-loader/index.js!/work/zst/client/node_modules/css-loader/index.js?{"sourceMap":true}!/work/zst/client/node_modules/bootstrap/dist/css/bootstrap.css doesn't export content
> 
> ERROR in ./~/font-awesome/css/font-awesome.css
> Module build failed: ModuleBuildError: Module build failed: TypeError: Path must be a string. Received undefined
> 
> ERROR in /work/zst/client/node_modules/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!/work/zst/client/node_modules/style-loader/index.js!/work/zst/client/node_modules/css-loader/index.js?{"sourceMap":true}!/work/zst/client/node_modules/font-awesome/css/font-awesome.css doesn't export content

FYI: In my vendor.ts I import this:

```
import 'font-awesome/css/font-awesome.css';
import 'ng2-bootstrap/ng2-bootstrap';
```

**Expected/desired behavior:**

Using the LoaderOptionsPlugin instead of the rule option property should not make any difference?!?

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.** 

Use the LoaderOptionsPlugin and import a plain CSS file.

* **What is the expected behavior?**

No error and the same behaviour.

* **What is the motivation / use case for changing the behavior?**

No error.

* **Browser:** Chrome 53.0.2785.116 (64-bit)
 
* **Language:** TypeScript 2.2

**Comment by sokra** [comment]
``` js
    new webpack.LoaderOptionsPlugin({
      options: {
        context: __dirname,
        tslint: {
          failOnHint: true
        }
      }
    })
```

or

``` js
    new webpack.LoaderOptionsPlugin({
      test: /\.ts$/,
      options: {
        tslint: {
          failOnHint: true
        }
      }
    })
```

**Comment by Martin-Wegner** [comment]
My production config has this:

```
  plugins: [
    new webpack.LoaderOptionsPlugin({
      context: __dirname,
      options: {
        htmlLoader: {
          minimize: false // workaround for ng2
        }
      }
    }),
```

But it fails with the same errors :(

**Comment by sokra** [comment]
context should be inside the `options` option.

**Comment by Martin-Wegner** [comment]
Ah now it works. Thanks! What is the difference between both possibilities? And should I use the plugin or the options property?

**Comment by sokra** [comment]
With `test` you only apply the plugin to a part for the modules. This is better.
