### ISSUE TITLE
Empty file extensions aren't allowed in Webpack 2 beta.23?

### ISSUE THREAD

**Issue by asadsahi** [webpack/webpack#3039]
**I'm submitting a bug report**

Here is the environment
2.x beta 23
Windows 10

Until webpack beta 22, empty files were allowed

```
    resolve: {
        extensions: ['', '.js', '.ts']
    },

```

Since beta 23 upgrade we are getting validation errors, After removing the empty file exteions, webpack 2 builds successfully.

```
    resolve: {
        extensions: ['.js', '.ts']
    },

```

Not sure if this is an intentional change or there is a different way to handle empty file extensions.

Thanks guys, good work :+1:

**Comment by sokra** [comment]
https://github.com/webpack/webpack.js.org/blob/develop/content/how-to/upgrade-from-webpack-1.md#resolveextensions

**Comment by asadsahi** [comment]
Hidden gems of course :)

@sokra from the link you mentioned above, its not clear how we are handling the empty files? link is broken, Would you mind explaining how do we handle empty files now?
