### ISSUE TITLE
Sinon causing issues again

### ISSUE THREAD

**Issue by altano** [webpack/webpack#304]
The new version of Sinon is throwing webpack for a loop again.  This code:

```javascript
    function makePublicAPI(require, exports, module) {
        module.exports = sinon;
        sinon.spy = require("./sinon/spy");
        sinon.spyCall = require("./sinon/call");
        sinon.behavior = require("./sinon/behavior");
        sinon.stub = require("./sinon/stub");
        sinon.mock = require("./sinon/mock");
        sinon.collection = require("./sinon/collection");
        sinon.assert = require("./sinon/assert");
        sinon.sandbox = require("./sinon/sandbox");
        sinon.test = require("./sinon/test");
        sinon.testCase = require("./sinon/test_case");
        sinon.match = require("./sinon/match");
    }

    if (isAMD) {
        define(makePublicAPI);
    } else if (isNode) {
        try {
            formatio = require("formatio");
        } catch (e) {}
        makePublicAPI(require, exports, module);         <========
    }
```

Is causing this warning:
```
WARNING in ./~/sinon/lib/sinon.js
Critical dependencies:
365:22-29 require function is used in a way, in which dependencies cannot be statically extracted
 @ ./~/sinon/lib/sinon.js 365:22-29
```

It's not obvious to me how to work around this.  Any of you have any bright ideas?

(the line number indicated in the error, 365, is clearly wrong, and the line with the arrow is actually the offending code)

**Comment by binarykitchen** [comment]
Any news on this one?

@mzgoddard Would you mind to share your script-loader here?

**Comment by elsigh** [comment]
Want.

**Comment by altano** [comment]
I'll leave this here for others... if you're depending on libraries for testing that use Sinon, you can't control what version of Sinon the library uses.  So you might run into a problem where the version it uses can't even be used with script-loader.  To deal with this:

- Download a release version of Sinon, e.g. http://sinonjs.org/releases/sinon-1.14.1.js
- Turn on noParse for sinon: that means webpack will not parse the file, it won't be minified, require will not work in the file, etc.
- Use NormalModuleReplacementPlugin to point require("sinon") to your local file instead of the NPM package.

Like so:

```javascript
module: {
    noParse: [
        /sinon/
    ]
},
plugins: [
    new webpack.NormalModuleReplacementPlugin(/sinon/, __dirname + "/TestRunner/vendor/sinon-1.14.1.js")
]
```

You should not normally do this because the library you depend on might upgrade to a version of Sinon that isn't API compatible with your local copy, or you might depend on multiple packages that depend on varying versions of Sinon.  This approach is totally circumventing both NPM and webpack.  And for sure, NEVER use this approach in releasing code, only tests.

Perhaps once Sinon 2 is more prevalent, these issues will go away, but in the mean time...

**Comment by tomatau** [comment]
Right now I'm running webpack mocha tests over a babel loader and `import sinon from 'sinon'` works only when used in conjunction with sinon-2.0 in my packages.json:

```
"sinon": "git://github.com/cjohansen/Sinon.JS#sinon-2.0",
```

However this doesn't support sinon.useFakeTimers() which is very unfortunate.

Thanks @altano for your alternative although it looks like it may throw up a bunch of problems of it's own!

**Comment by kpdecker** [comment]
For my own setup (babel, sinon, chai, sinon-chai) I had to make a few alterations to @altano's local copy solution:

For useFakeTimers (I have only tested that the thing doesn't throw on init, not that fake timers actually work...):
```
import 'expose?lolex!lolex';
```

Also need to make sure that this is excluded from the babel loader as noParse doesn't seem to impact loader execution.

For the final bit, needed to make sure that sinon-chai was treated as normal, meaning slight modification to @altano's regexs:

```
  module: {
    noParse: [
      /\/sinon.js/
    ]
  },
  plugins: [
    new webpack.NormalModuleReplacementPlugin(/^sinon$/, __dirname + '/vendor/sinon.js'),
  ]
```

This is multiple levels of yuck but it seems to work for now :(

**Comment by FredyC** [comment]
How comes that sinon is working with browserify just perfectly? I just started using webpack for a new project (gulp, webpack, babel, mocha, karma), but issues like this are giving me a second thoughts if it's mature enough for a development.

For the record, I am not using sinon for any mocking or spying. I love its convenient anonymous spy which can be simply passed as a callback to my methods and then evaluate results with couple of assertions instead of making ugly function like this.

    it('should...', () => {
        let called = 0;
        myMethod((data) => {
            if (called === 0) {
                expect(data.whatever).to.equal('test');
            }
            called += 1;
        });
    });

With sinon I can it simply like this. It's much more readable with less hassle (and possible mistakes).

    it('should..., () => {
        const spy = sinon.spy();
        myMethod(spy);
        expect(spy.firstCall).calledWithMatch({ whatever: 'test '});
    });

Can you perhaps recommend me some other library that can do this?

**Comment by andrei-picus-hs** [comment]
I've created a fork of Sinon over at [uberVU/Sinon.JS](https://github.com/uberVU/Sinon.JS) that doesn't include the AMD logic. Works perfectly with webpack.

**Comment by maikdiepenbroek** [comment]
@andrei-picus-hs You sir, are my hero!

**Comment by ScreenDriver** [comment]
Same here. Is there an **easy** way to get Babel, Mocha, Chai, Sinon and Sinon-Chai running with webpack? I can't directly reference GitHub dependencies here so I can't use the @andrei-picus-hs repository unless it's deployed to npm. As well I am afraid that it will always behind the official Sinon Repo.

The Sinon 2.0 branch seems dead by the way.

**Comment by melbourne2991** [comment]
@screendriver I searched far and wide, doesn't seem like it - @andrei-picus-hs solution is your best bet:

```
devDependencies: {
    "sinon": "git+https://github.com/uberVU/Sinon.JS"
}
```

**Comment by screendriver** [comment]
Unfortunately as I mentioned earlier: I can't directly reference GitHub dependencies here in my company.

In the meantime I switched away from webpack to [SystemJS](https://github.com/systemjs/systemjs) and [jspm](http://jspm.io).

**Comment by heldr** [comment]
It works for me just adding ``noParse`` rule on webpack and requiring the dist version instead.

Example:

```js
import sinon from 'sinon/pkg/sinon';
```

**Comment by SpaceK33z** [comment]
Thanks @heldr, that seems to work! In my webpack.config.js, I added this:

````js
{
    module: {
        noParse: [
            /node_modules\/sinon/,
        ],
    }
}
```

**Comment by realisation** [comment]
Is there a version of that workaround for those using sinon-chai?

**Comment by dtinth** [comment]
@realisation My `noParse` looks like this:

```js
    noParse: [
      /node_modules\/sinon\//,
    ],
```

It’s almost like @SpaceK33z’s version but with an added `\/` at the end to prevent the rule from matching `node_modules/sinon-chai`.

**Comment by heldr** [comment]
@dtinth you can also create an alias for sinon

```js
  resolve: {
    alias: {
      sinon: 'sinon/pkg/sinon.js'
    }
  },
```

then import goes easier :tea: 

```js
import sinon from 'sinon';
```

**Comment by vitalets** [comment]
That's how we are requiring sinon manually in our tests:
```js
require('imports?this=>window!' +
    'imports?define=>false!' +
    'imports?exports=>false!' +
    'imports?module=>false!' +
    'imports?require=>false!' +
    '../node_modules/sinon/pkg/sinon-1.15.4.js'
);
````

**Comment by sokra** [comment]
@vitalets The imports-loader can import multiple symbols at once...

``` js
require('imports?this=>window,' +
    'define=>false,' +
    'exports=>false,' +
    'module=>false,' +
    'require=>false!' +
    '../node_modules/sinon/pkg/sinon-1.15.4.js'
);
```

**Comment by wmadden** [comment]
Thanks very much @vitalets and @sokra! That works for me too

**Comment by dtuite** [comment]
I found that the solution provided by @solcik and @vitalets was close but raised errors with sinon `1.17.2` and webpack `1.12.9`.

Eventually I got it working with

```js
import sinon from 'imports?define=>false,require=>false!sinon/pkg/sinon.js';
```

when sinon is installed into `./node_modules` in the regular way with `npm install sinon`.

You can clean it up a little by taking advantage of the webpack config:

```js
  module: {
    loaders: [
      { test: /sinon\/pkg\/sinon\.js/, loader: 'imports?define=>false,require=>false' }
    ],
  },
```

and then

```js
import sinon from 'sinon/pkg/sinon.js';
```

**Comment by dmitry** [comment]
@dtuite nice solution! Thanks! :+1:

**Comment by bebraw** [comment]
Closing given @dtuite found a good solution.

**Comment by alexgorbatchev** [comment]
To chip in more on this, I found the combination of two solutions above works seamlessly:

```javascript
entry = {
  test: [
    'sinon/pkg/sinon.js',
  ],
}
...
loaders: [
  {
    test: /sinon/,
    loader: 'imports?define=>false,require=>false',
  },
]
...
resolve = {
  alias: {
    sinon: 'sinon/pkg/sinon.js',
  },
}
```

**Comment by heldr** [comment]
@alexgorbatchev yeah! The **alias** can also be combined with `noParse` instead of creating a loader and entry.

```js
module: {
  noParse: [
    /\/sinon\.js/,
  ],
}
```

"works on my machine!" :laughing:

**Comment by ngerritsen** [comment]
@heldr +1, works on my machine too

**Comment by graingert** [comment]
I'm using:

```js
entry = {
  test: [
    'tests/tests.js',
  ],
}
...
loaders: [
  {
    test: /sinon\/pkg\/sinon\.js/,
    loader: 'imports?define=>false,require=>false',
  },
]
...
resolve = {
  alias: {
    sinon: 'sinon/pkg/sinon',
  },
}
```

**Comment by graingert** [comment]
Because of https://github.com/peerigon/legacy-loader/issues/1 I've actually switched to using:

`npm install --save-dev sinon@next`

**Comment by ericdfields** [comment]
using @heldr's technique

**Comment by jbcpollak** [comment]
I tried this:

```
module: {
  noParse: [
     /\/sinon\.js/,
  ],
  resolve = {
    alias: {
      sinon: 'sinon/pkg/sinon',
    },
  }
}
```

But I get errors like this:

```
ERROR in ./~/sinon/pkg/sinon-1.7.3.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./buster-event-emitter in ..../node_modules/sinon/pkg
 @ ./~/sinon/pkg/sinon-1.7.3.js 248:30-63

ERROR in ./~/sinon/pkg/sinon-1.6.0.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./buster-event-emitter in ..../node_modules/sinon/pkg
 @ ./~/sinon/pkg/sinon-1.6.0.js 250:30-63

ERROR in ./~/sinon/pkg/sinon-1.7.3.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./define-version-getter in ..../node_modules/sinon/pkg
 @ ./~/sinon/pkg/sinon-1.7.3.js 251:23-57

ERROR in ./~/sinon/pkg/sinon-1.6.0.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./define-version-getter in ..../node_modules/sinon/pkg
 @ ./~/sinon/pkg/sinon-1.6.0.js 253:23-57

ERROR in ./~/sinon/pkg/sinon-1.7.3.js
Module not found: Error: Cannot resolve module 'buster-core' in ..../node_modules/sinon/pkg
 @ ./~/sinon/pkg/sinon-1.7.3.js 263:13-35
```

I only depended on sinon 1.7.3, so I'm not sure where the references to 1.6.0 come from.

**Comment by ericdfields** [comment]
@jbcpollak move resolve outside of module:

```javascript
{
  module: {},
  resolve: {}
}
```

**Comment by bcowgill** [comment]
+1 for @graingert 

thanks, that's the only thing that has worked for me. I was getting out of memory garbage collection errors I've never seen before with the other methods!

**Comment by aaronjensen** [comment]
fwiw, we had better luck using:

```js
import 'expose?lolex!lolex'
import 'script!sinon/pkg/sinon'
```

(replace with require/webpack aliases/loader config/etc if you want)

**Comment by slavik57** [comment]
@heldr solution worked =] you are the man!

**Comment by demoritik** [comment]
thanks @graingert , only ur solution with `npm install --save-dev sinon@next` works for me

**Comment by ecrona** [comment]
I initially attempted to import sinon manually (evidently not needed) which caused this problem, so I just removed the import line at the top of the script and used it globally, and it seemed to work.

**Comment by timmyLan** [comment]
@heldr +1, works for me,THX

**Comment by graingert** [comment]
FYI sinon@next is very close to release: https://github.com/sinonjs/sinon/issues/966

**Comment by shults** [comment]
```
  resolve: {
    root: [ path.resolve(__dirname) ],
    extensions: ['', '.ts', '.js'],
    alias: {
      sinon: `${__dirname}/node_modules/sinon/pkg/sinon.js`
    }
  },
  module: {
    noParse: [ /sinon\.js/ ],
    // ...
  }
```

```
import * as sinon from 'sinon';
```

**Comment by graingert** [comment]
@shults just use sinon@next

**Comment by aweiher** [comment]
If anyone comes here for this error in combination with `karma` and `phantomjs`:

```
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
  ReferenceError: Can't find variable: require
```

Add Sinon as external in webpack config: 

```
externals: ["sinon"]
```

(currently webpack 1.x for me)
