### ISSUE TITLE
configuration.entry error (passing an Array of paths)

### ISSUE THREAD

**Issue by duivvv** [webpack/webpack#3042]
**I'm submitting a bug report**

passing an Array of paths causes a webpack validation error

**Webpack version:**
2.1.0-beta.25

**Please tell us about your environment:**
macOS Sierra

**Current behavior:**

passing an Array of paths outputs a WebpackOptionsValidationError

``` js

  entry: [
    'webpack/hot/dev-server',
    `webpack-dev-server/client?http://127.0.0.1:${port}`,
    './src/js/script.js',
    './src/css/style.css',
    './src/index.html'
  ],

```

```
configuration.entry should be one of these:
   object { <key>: string | [string] } | string | [string]
```

**Expected/desired behavior:**

passing an Array of strings should work? ([string])

**Comment by duivvv** [comment]
update:

When I remove the dev-server lines it works. 
Seems to originate from webpack-dev-server

**Comment by duivvv** [comment]
Seems to be originating from 'webpack/hot/dev-server'
When I remove this line, it validates.

**Comment by TheLarkInn** [comment]
I see you're using back ticks in that line. Can you switch it to normal strings?

**Comment by duivvv** [comment]
tried that, no difference. 

If I remove the two lines (webpack/hot/... and webpack-dev-server...) everything seems to work perfectly (even hot reloading, is this normal?)

**Comment by sokra** [comment]
@gajus looks like the same bug as the other issue...

**Comment by gajus** [comment]
Looking into it.

**Comment by derkjn** [comment]
Experiencing the same issue, but only when running webpack with the `--watch` option.
My entry points are as follows:

```
"entry": {
    "main": [
      "./scripts/main.js",
      "./styles/main.scss",
      "./images/logo.png"
    ]
  },
```

**Comment by tomascharad** [comment]
+1

**Comment by EvNaverniouk** [comment]
For me, I discovered that the culprit is `'webpack/hot/dev-server'`. If I remove that item from the entry list, the rest of the array items work fine.

**Comment by Skilgarriff** [comment]
Having this issue as well :/

**Comment by gajus** [comment]
The last time this issue has been reported is 12 days ago. I was on vacation. Does anyone still have this issue?

**Comment by derkjn** [comment]
Hi @gajus ,

Yes this is still happening with `webpack@2.1.0-beta.25`.

Thank you!

**Comment by rafabernad** [comment]
Hi,

I'm having this issue with múltiple entry points and _without_ dev server, in a production build.

With just one entry points It works fine.

**Comment by jlabaj** [comment]
+1

**Comment by gajus** [comment]
Sorry, I was never able to reproduce this.

I would need someone to create a demo repository.

**Comment by jlabaj** [comment]
here you are: https://github.com/jlabaj/configuration.entry

**Comment by hpawe01** [comment]
@jlabaj This repo is not working for me as I am on a linux machine. First I had to remove `.npmrc` to perfom the installation. Then the postinstallation script failed because of the missing `copy`. So I had to replace `copy` by `cp`. And of course `\\` with `/`.

When I finally managed to get to `npm run start` it tells me, that the webpack config file is missing. And indeed, there is neither the defined `config/webpack.dev.WDS.js` nor any other `webpack.config.js` file.

So I think with this repo it is hard to reproduce this issue.

**Comment by jlabaj** [comment]
@hpawe01 sorry for that, I've added the configs, deleted the .npmrc and removed the postinstall, that is not necessary for the recreation, and also replaced the backslashes with forward slashes. 
I've cloned the repository new afterwords and tested it.

Please retry whenever you have time.

**Comment by hpawe01** [comment]
@jlabaj Alright, the issue is reproducible with your repo (for me). As @duivvv  and @EvNaverniouk pointed out, the problem seems this string `'webpack/hot/dev-server'`. If you remove it from the list this issue does not occur.

So I thought, maybe webpack tries to add `'webpack/hot/dev-server'` to the entry points again because you specified `--hot` (as described in [Docs](https://webpack.github.io/docs/webpack-dev-server.html#hot-module-replacement) and [this GitHub-Issue](https://github.com/webpack/webpack-dev-server/issues/97#issuecomment-69726201)) and this causes some broken config array. But even without this parameter the same error message occurs.

Maybe @gajus can help us?

**Comment by jeerbl** [comment]
Hello,

Any news on this issue?

Reproducing with:
webpack 2.2.1
webpack-dev-server 2.3.0

Cheers
Jerome

**Comment by gajus** [comment]
I am sorry guys, I am working on a project with tight deadlines. I cannot have a look at this now.

**Comment by jeerbl** [comment]
Don't know why but running `webpack-dev-server` via a `npm` script works.

**Comment by johnpapa** [comment]
I get this when using wallaby as shown here too (on an angular cli app) 

https://github.com/wallabyjs/ngCliWebpackSample/blob/master/wallaby.js#L4-L7

cc @TheLarkInn

**Comment by TheLarkInn** [comment]
@jeerbl @johnpapa 

If you are reproducing this, would you please create a tiny reproducible example repo. Then I can create the tests and fixtures based on it, and either fix this myself or hand off to someone on our contirbutor team to tackle.

@timse @NejcZdovc @naknode have interest in tackling this?

**Comment by vijayst** [comment]
I get duplicate entries in the array. And so, webpack-dev-server is failing.
```
"data": [
          "/Users/vijayst/Documents/react/sam/samwise/node_modules/webpack-dev-server/client/index.js?http://localhost:8080",
          "webpack/hot/dev-server",
          "react-hot-loader/patch",
          "webpack-dev-server/client?http://127.0.0.1:8080",
          "webpack/hot/dev-server",
          "./src/app"
        ]
```

**Comment by MilosRasic** [comment]
Trying to start a project on windows after a long time, webpack 2.7.0, webpack-dev-server 2.9.1, with entry like:

`['react-hot-loader/patch', './src/index.jsx']`

Getting the following reported as cause of error:

```
        "data": [
          "c:\\node\\GGS\\platform\\node_modules\\webpack-dev-server\\client\\index.js?http://localhost:8081",
          "webpack/hot/dev-server",
          "C:\\node\\GGS\\platform\\node_modules\\webpack-dev-server\\client\\index.js?http://localhost:8080",
          "webpack/hot/dev-server",
          "./src/index.jsx"
        ]
```

literally unplayable

**Comment by mokkymiah** [comment]
Still same issue with 3.12.

**Comment by get6** [comment]
In my case i chaged VUE_TRAGET_PAGE in .env file.
my main.js path was wrong
