### ISSUE TITLE
Getting error: configuration.resolve.extensions[0] should not be empty

### ISSUE THREAD

**Issue by QuantumInformation** [webpack/webpack#3043]
**I'm submitting a bug report**

beta 25 breaks my build with: configuration.resolve.extensions[0] should not be empty, even though I have it

**Webpack version:**
webpack@2.1.0-beta.25

**Please tell us about your environment:**
OSX 10.x

You can demo this here:
https://github.com/QuantumInformation/femptoCSS/commit/35ebcee673260ca1b703db166d2aaeed9d6bdc47

**Comment by duivvv** [comment]
Remove '' from the array, had the same problem.

**Comment by MoOx** [comment]
It's not a bug, it's a feature. Just remote it and it works the same (since beta.23).

**Comment by QuantumInformation** [comment]
Great it works thanks.

**Comment by jusefb** [comment]
If I remove the blank extension option the configuration error goes away but now none of my modules will load as they are all loaded without an extension. Is there some specific way I should be specifying blank extension in this new version?

**Comment by duivvv** [comment]
@jusefb is the Array empty now?

**Comment by jusefb** [comment]
I have tried the following options:

extensions: ['','.ts', '.js'] - throws the above error
extensions: ['.ts', '.js'] - doesn't load any modules without an extension
extensions: [] - does not load any options

**Comment by jusefb** [comment]
I am not sure that this is correct but after a few series of trial an error I have tried using the * symbol instead of an empty string. This seems to have fixed the problem.So final syntax for the extensions attribute:

extensions: ['*', 'js', 'ts']

Hope this is the intended way to do it

**Comment by QuantumInformation** [comment]
Should this be reopened?

**Comment by telekid** [comment]
Preventing an empty string seems to run contrary to practices recommended by the new webpack documentation:

https://webpack.js.org/configuration/resolve/#resolve-extensions

Is the documentation outdated?

**Comment by xtianus79** [comment]
@QuantumInformation lol on Os X... /slight-troll

**Comment by QuantumInformation** [comment]
??

**Comment by xtianus79** [comment]
@QuantumInformation im kidding... i think environment means what are you using for webpack node, angular 2, reactjs, etc... 

perhaps I am wrong.

**Comment by jeremejevs** [comment]
@xtianus79

![](http://i.imgur.com/yLMkCLo.png)

**Comment by xtianus79** [comment]
@jeremejevs lol fair enough... to me it seems like an odd qualifier.

**Comment by HyperSimon** [comment]
+1

**Comment by JD-Robbs** [comment]
Same issue here:  I need to use the `''` extension in order to be able to load modules without extensions.  Using the `'*'` syntax mentioned above doesn't work (v2.2.0).

**Comment by erik-sn** [comment]
Using TypeScript if it makes any difference, but the "*" **does** work for me to fix this error. Although after some searching I found I didn't need to resolve all extensions and just removed it.

**Comment by JD-Robbs** [comment]
Strangely, not for me - I'm envious.  Perhaps, the reason is that I use a `glob` pattern as entry point (it bundles all my `.test.ts` files).

**Comment by dingxiaoming521** [comment]
the same problem.  
try to use "webpack": "^1.13.2", not 2.x.x

**Comment by birjitningomba** [comment]
I got the same problem with the 
extensions: ["", ".ts", ".js"]
but when I change to the below, the error is not reported. 
extensions: ['', '.ts', '.js']

Here is my webpack version
 "webpack": "^2.2.1"

**Comment by MFry** [comment]
The error
```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration[0].resolve.extensions[0] should not be empty.
```
Shows up in 
```
-- webpack@2.3.2
```
Changing the quotation marks from "" to '' does not fix the issue

**Comment by dantesolis** [comment]
@MFry I'm using `webpack` with `react` for me error to disappear you need to pass

```
... omitted code
resolve: {
  extensions: ['*', 'js', 'jsx']
},
... omitted code
```

**Comment by LucaColonnello** [comment]
It sounds odd, but form me `webpack@2.3.3` with `react` isn't working with the following:

```js
resolve: {
   extensions: ['*', 'js', 'jsx'],
},
```


I had to add the dot in front of extensions to make it works!

```js
resolve: {
   extensions: ['*', '.js', '.jsx'],
},
```

**Comment by MFry** [comment]
@LucaColonnello I have only ever matched the extensions with the dots. I wasn't even aware you could do it another way!

@dantesolis Thank you I will test that! Although I found that omitting it entirely has not affected me.

**Comment by LucaColonnello** [comment]
Mmmm... ok, anyway it's working with dots, so it's fine! :)

**Comment by noahehall** [comment]
used this for `webpack 2.2.1`
`path.resolve(`${__dirname}/../..`)`

**Comment by cl4pper** [comment]
Problem solved using this syntax bellow:
	resolve: {
		extensions: [ '*', '.js', '.jsx' ],
	},

**Comment by nickcorin** [comment]
I have attempted to use:

```
resolve: {
    extensions: [ '*', '.js', '.jsx' ],
},
```

Although, I am still getting errors with files with no extension for example a file in one of my external libraries is failing to load.

> ./lib/config

**Comment by Goran7777** [comment]
Seems to me webpack is a bad tool,must find other solution for react,have the same problem with emty extension and  DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
