### ISSUE TITLE
Latest beta was mistakenly published as latest

### ISSUE THREAD

**Issue by billyjanitsch** [webpack/webpack#3044]
**I'm submitting a bug report**

**Webpack version:**
1.10.x/2.x

**Please tell us about your environment:**
OSX 10.x

**Current behavior:**
`npm view webpack` yields:
```
{ ...
  'dist-tags': { latest: '2.1.0-beta.25', beta: '2.1.0-beta.24' },
  ...
}
```

**Expected/desired behavior:**

`2.1.0-beta.25` should have been published with the `beta` tag instead of `latest`. `latest` should remain at `1.13.2`.

Could you please fix the tags so that `npm install webpack` doesn't install 2.x?

**Comment by DJviolin** [comment]
+1 for this. Now everything broken and v2 examples lacking.

**Comment by TheLarkInn** [comment]
Am on this right now. Thank you very much for reporting. I don't think this was intentional.

**Comment by TheLarkInn** [comment]
CC @webpack/collab-team

**Comment by billyjanitsch** [comment]
> Now everything broken

@DJviolin let's be constructive. It's just a small tag mistake; you can always run `npm install webpack@1` until it gets fixed.

@TheLarkInn thanks for the quick reply. You just need someone with npm privs to run:
```
$ npm dist-tag add webpack@1.13.2 latest
$ npm dist-tag add webpack@2.1.0-beta.25 beta
```

**Comment by TheLarkInn** [comment]
Alright I fixed it! :-D

**Comment by LearnWebCode** [comment]
@TheLarkInn thanks so much for the quick NPM adjustment, you're my hero! I know the beta is obviously the future, so on a slightly unrelated note, do you know of any good examples / tutorials showing how to config something like the Babel loader with Webpack@V2?

**Comment by TheLarkInn** [comment]
http://webpack.js.org/how-to/set-up-hmr-with-react/ This may assist from our new docs page. Some of the versions in the npm install script need to be updated, (maybe you can submit a pr :smirk:)
