### ISSUE TITLE
[Help Wanted] Create Typescript typings file from new validation schema

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack#3045]
Now that we have validation [schema.json](https://github.com/webpack/webpack/blob/master/schemas/webpackOptionsSchema.json) file for our configuration values. We should now generate a typescript typings file based on it. We would like help from anyone in the community willing to do so. 

If you are already working on this, please open a PR, and then mark [WIP] so that we know now to review it yet. This will allow others to help you through this process. 

Ideally we would need two things: 
- `webpack.d.ts` file with correct typings based on schema
- (really ideal) PR should include a script that converts the schema to typescript typings, so that this process could be generative.

**Comment by NejcZdovc** [comment]
I can take over this issue. Will create PR when I will have something to show.

**Comment by sokra** [comment]
Thanks

**Comment by NejcZdovc** [comment]
@TheLarkInn I notice that your ideal PR would be schema converter. I found [this library](https://github.com/bcherny/json-schema-to-typescript) for conversion, but I am getting error described [here](https://github.com/bcherny/json-schema-to-typescript/issues/35). What do you suggest? Should we wait for bugfix or create it manually? I think this library can help us make this process automated and I don't see any point to create new one.

**Comment by NejcZdovc** [comment]
I just found out that @donaldpipowitch is also working on this. I referenced it in this issue.

**Comment by donaldpipowitch** [comment]
I personally would wait for https://github.com/bcherny/json-schema-to-typescript/issues/35 to become solved (or help there to make this happen faster). The other bug which blocked this was already solved (https://github.com/bcherny/json-schema-to-typescript/issues/34).

**Comment by NejcZdovc** [comment]
Yes I agree with you

**Comment by TheLarkInn** [comment]
I would say its more important overall to get the typings, we could create a separate issue for the generator. 

The benefit is that the PR workflow is much easier because typings can be generative when changes are made in the codebase

**Comment by TheLarkInn** [comment]
@bcherny is there a way we can assist with your tool

**Comment by cspotcode** [comment]
Whoever decides to go the programmatic route will need to add more information to the schema.  For example, JSON schema doesn't say anything about the types of arguments to a function.

[bcherney/json-schema-to-typescript](https://github.com/bcherney/json-schema-to-typescript), as far as I know, won't generate function signatures either, so a schema generated by that tool would still need some human modification.

**Comment by NejcZdovc** [comment]
@TheLarkInn ok, so should I create typings by hand for now?

**Comment by TheLarkInn** [comment]
I think that would be a viable solution for now.

**Comment by donaldpipowitch** [comment]
Sounds good!

**Comment by bcherny** [comment]
@TheLarkInn I'm working through a backlog of bugs/missing features, no ETA yet. Help would be appreciated.

@cspotcode If there's a standard JSON-schema extension for function signatures (or if you want to propose a custom one), we can potentially support it in json-schema-to-ts. A quick google search turns up https://github.com/yinso/schemalet#functionprocedure-contracts as one option.

**Comment by TheLarkInn** [comment]
@danielrosenwasser do you know any awesome people who might be able to help @bcherny in regards to some schema-to-ts related things?

**Comment by bcherny** [comment]
@TheLarkInn Almost there actually, we've been making decent progress. I think https://github.com/bcherny/json-schema-to-typescript/issues/44 is the last blocker, I'll tackle it this week.

**Comment by zhaoshengjun** [comment]
Hi @TheLarkInn, I have a WIP typings file for `schema.json`.

If you and @NejcZdovc like, I canl create a repo so you guys can have a look.

**Comment by NejcZdovc** [comment]
@zhaoshengjun I am almost finished with this and will create PR today/tomorrow. If you would please give a feedback on my PR, any suggestions or improvements are very welcome.

**Comment by zhaoshengjun** [comment]
@NejcZdovc . Awesome! Will check once it's available.

**Comment by NejcZdovc** [comment]
@TheLarkInn hi, are there any plans for TS support or should we close this one?

**Comment by TheLarkInn** [comment]
I'm very much for supporting the types still, but I was told that it had moved to DefinitelyTyped. I'm going to close this with the notion that further support (for now) can belong there. I'm working with the TS team behind the scenes on other webpack related stuff and I'll make sure to pull both you and @zhaoshengjun into the issue when its time. Sorry for all the lag on this.
