### ISSUE TITLE
b23+ resolve.modulesDirectories not in schema

### ISSUE THREAD

**Issue by bfricka** [webpack/webpack#3047]
**I'm submitting a bug report**
As of b23+, the new schema enforcement doesn't contain an entry for `resolve.modulesDirectories`. I thought this might be an oversight since nothing was specifically mentioned about it in any of the release notes, and like any schema validation issue, it breaks builds.

*NOTE:* This also breaks [Wallaby](http://wallabyjs.com/)

**Webpack version:**
2.1.0-beta.23 - 2.1.0-beta.25
OSX 10.11.6

**Comment by sokra** [comment]
http://webpack.js.org/how-to/upgrade-from-webpack-1/

**Comment by bfricka** [comment]
Thanks. This is the first time I've seen this documentation for webpack 2. I'll file an issue over at Wallaby for this one.

**Comment by sokra** [comment]
It's new :smile:

**Comment by bfricka** [comment]
It's awesome! Also, Wallaby just patched for 2.x schema!
