### ISSUE TITLE
b23+ watchOptions.poll does not match the API schema

### ISSUE THREAD

**Issue by dreyks** [webpack/webpack#3048]
**I'm submitting a bug report**
i have
```js
webpackConfig.watchOptions = {
  poll: process.env.FORCE_POLL
}
```
in webpack config
WSL on Windows 10 does not implement fd, so no inotify for me, I have to use polling

the error I get is
```
- configuration.watchOptions.poll should be one of these:
  boolean | {
    "description": "`number`: use polling with specified interval.",
    "type": "number"
  }
```

`console.log(process.env.FORCE_POLL)` resolves to `true`

**Webpack version:**
2.1.0-beta.25

**Please tell us about your environment:**
WSL on Windows 10

**Comment by sokra** [comment]
It must be a boolean or number.

**Comment by dreyks** [comment]
`process.env.FORCE_POLL` is set to `true`. What is more boolean than that?

**Comment by dreyks** [comment]
Or do env variables resolve to strings? How then can it be used in such situation?

**Comment by sokra** [comment]
They are strings.
