### ISSUE TITLE
Click 4 router-links in turn, router-view can render all the pages first time, but click all the links again it router-view does not render.

### ISSUE THREAD

**Issue by kcheng-mvp** [webpack/webpack#3049]
## **BEFORE YOU SUBMIT** please read the following:
If you have a support request or question please 
submit them to [StackOverflow](http://stackoverflow.com/questions/tagged/webpack) using the tag `[webpack]` or the [webpack Gitter](https://gitter.im/webpack/webpack). Future support requests will be closed.
(remove this from issue)

**I'm submitting a bug report**
**I'm submitting a feature request**
**I'm submitting a support request** => Please do not submit support request here, see note at the top of this template.
(remove inappropriate sentences)

**Webpack version:**
2.x
vuejs 2.x

**Please tell us about your environment:**
OSX 10.x / Linux / Windows 10

**Current behavior:**

please see the issue from here https://github.com/vuejs/vue-router/issues/673

**Expected/desired behavior:**

page should be rendered.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.** 

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart | ...]

**Comment by kcheng-mvp** [comment]
![22](https://cloud.githubusercontent.com/assets/7655276/18773320/a7555d70-8180-11e6-9f4f-2b2259c11276.png)

**Comment by MoOx** [comment]
You didn't read and fill the template correctly. This issue completely lack of accurate information.

**Comment by sokra** [comment]
It's totally unclear how webpack should cause this. Please investigate deeper and come back with more detailed information. I doubt webpack causes this issue.
