### ISSUE TITLE
Better control over the location of source maps

### ISSUE THREAD

**Issue by fresheneesz** [webpack/webpack#305]
I'm  having an issue where my sourcemap is often not loading correctly. The soruceMappingURL seems to be relative (doesn't start with a slash), which normally would be good, because it'll be loaded relative to whatever url the bundle is loaded from. However, in my case, I'm embedding the bundle in a base-file that can be loaded from many URLs, while the sourcemap file is obviously only in one location. Is there a way I can tell webpack a different sourcemap location to write in the bundle? 

Really this problem comes from the fact that I'm embedding the bundle into an html file (to save an http request). There are a couple problems with the way I'm doing it:

A. The column numbers for the first line aren't correct
B. The sourceMapURL issue above ^

Is there a better way to embed the bundle in an html file?

**Comment by adammlr** [comment]
I know this is a closed issue, but I couldn't find a better place to post... if I try using SourceMapDevToolPlugin with UglifyJsPlugin I end up with 2 sourceMapUrls in my js file.  Any way around this?
