### ISSUE TITLE
Cannot find module 'highlight.js'

### ISSUE THREAD

**Issue by jpzwarte** [webpack/webpack#3051]
**I'm submitting a bug report**
**Webpack version:**
2.1.0-beta-25
**Please tell us about your environment:**
OSX 10.12

**Current behavior:**
ERROR in [default] example.component.ts:2:22 
Cannot find module 'highlight.js'.

**Expected/desired behavior:**
No error.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.** 

```npm i -D highlight.js @types/highlight.js```

Then in typescript:
```import * as hljs from 'highlight.js';```

When compiled using ```tsc``` there are no errors. When compiled with webpack it gives the cannot find module error.

I'm guessing the '.js' part of 'highlight.js' is the problem here?
 
* **Language:**
Typescript 2.0 final (2.0.3)

**Comment by jpzwarte** [comment]
To be clear: all other imports from node_modules work fine. Only this one triggers the error. It's also the only one with '.js' in the module name.

**Comment by sokra** [comment]
`--display-error-details`

**Comment by jpzwarte** [comment]
Doesn't yield any additional info. Could this perhaps be an issue with awesome-typescript-loader, or is this pure webpack?

**Comment by jpzwarte** [comment]
Here's a screenshot: https://www.dropbox.com/s/edi9xhfd4vwanum/Screenshot%202016-09-23%2014.56.20.png?dl=0

**Comment by jpzwarte** [comment]
I'm closing this since i'm pretty sure the error comes from awesome-typescript-loader.
