### ISSUE TITLE
DllReferencePlugin manifest specified as a path causes webpack-dev-server to recompile bundle repeatedly

### ISSUE THREAD

**Issue by wagerfield** [webpack/webpack#3052]
webpack@2.1.0-beta.25
OSX 10.11.6

Following the release notes for [v2.1.0-beta.23](https://github.com/webpack/webpack/releases/tag/v2.1.0-beta.23), I replaced `manifest: require(manifestPath)` with `manifest: manifestPath` in the `DllReferencePlugin`:

``` js
// OLD webpack.config.js
module.exports = {
  ...
  plugins: [
    new webpack.DllReferencePlugin({
      manifest: require('path/to/manifest.json'),
      context: 'some/context/path'
    })
  ]
}

// NEW webpack.config.js
module.exports = {
  ...
  plugins: [
    new webpack.DllReferencePlugin({
      manifest: 'path/to/manifest.json',
      context: 'some/context/path'
    })
  ]
}
```

For single builds using `webpack`, both of these config files works fine.

However, when I use the 'NEW config file' (specifying the manifest as a string path, rather than wrapping it in require call) WITH `webpack-dev-server@2.1.0-beta.5`, the bundle is compiled 15-20 times before it 'settles down'.

This happens regardless of whether I have hot module reloading enabled. In my configuration I get the following outputted to the console:

![screen shot 2016-09-23 at 11 24 07](https://cloud.githubusercontent.com/assets/412747/18782869/88e7e272-8180-11e6-8fc3-816425f6ec51.png)

I _expect_ this is happening because the manifest file is being read asynchronously and causing the compiler to recompile each time a new chunk of data is received from the manifest file—though I could be totally wrong!

**Comment by SpaceK33z** [comment]
This could be related to #2983.
