### ISSUE TITLE
Wrong main-entry from package.json used when there is a jam-section present

### ISSUE THREAD

**Issue by atlefren** [webpack/webpack#3054]
**I'm submitting a bug report**

**Webpack version:**
1.13.2

**Please tell us about your environment:**
Linux

**Current behavior:**
Install an npm-package with a [jam](https://github.com/caolan/jam) config-block in package.json (for example proj4@2.3.15 )

import the package in a file

```
import proj4 from 'proj4';
```

Get a warning:

```
WARNING in ./~/proj4/dist/proj4.js
Critical dependencies:
1:407-414 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/proj4/dist/proj4.js 1:407-414
```

This is beacaue the jam-config in package.json has a main-entry pointing to a minified file, but the top-level main-entry points to the correct file.

**Expected/desired behavior:**
No warning given, package should be imported from correct main-entry (i.e. not the jam-config specific one)
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.** 
  see above
- **What is the expected behavior?**
  see above, also see the issue filed at proj4 https://github.com/proj4js/proj4js/issues/208
- **What is the motivation / use case for changing the behavior?**
  In the rare cases where a dependency has a jam-config this will confuse users. Node imports does not suffer from this bug.
- **Browser:** all
- **Language:** all

**Comment by sokra** [comment]
We should remove the jam.main resolving in webpack 2. Do you want to do a PR?

**Comment by atlefren** [comment]
@sokra Ah, so webpack has logic to handle jam? Makes sense to remove it, as jam seems to be discontinued.

I can give it a try at least, will report back if I'm stuck

**Comment by sokra** [comment]
> Makes sense to remove it, as jam seems to be discontinued.

yep.

> I can give it a try at least, will report back if I'm stuck

look at `lib/WebpackOptionsDefaulter`

**Comment by atlefren** [comment]
I'm sorry, I cannot figure out how the Jam-config is read in ```lib/WebpackOptionsDefaulter```, I've found some references to it in ´´´bin/webpack.js´´´.

However, I cannot find any tests for this resolving, nor do I know how to add apropriate tests. On top of that, npm test fails on my checkout:

```
1) ConfigTestCases extract-text issue-14 should compile:
     Error: global leak detected: addresses
```
`
So, I guess it's easier for someone with knowledge of the code to fix this. Sorry
