### ISSUE TITLE
Make node-libs-browser optional

### ISSUE THREAD

**Issue by baderbuddy** [webpack/webpack#3058]
## **BEFORE YOU SUBMIT** please read the following:

If you have a support request or question please 
submit them to [StackOverflow](http://stackoverflow.com/questions/tagged/webpack) using the tag `[webpack]` or the [webpack Gitter](https://gitter.im/webpack/webpack). Future support requests will be closed.
(remove this from issue)

**I'm submitting a feature request**

**Webpack version:**
2.x

**Please tell us about your environment:**
OSX 10.11

**Current behavior:**
node-libs-browser is a required dependency

**Expected/desired behavior:**
node-libs-browser being optional dependency
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.** 
- **What is the expected behavior?**
  node-libs-browser being made an optional dependency
- **What is the motivation / use case for changing the behavior?**
  node-libs-browser isn't needed for my application but the ability for things like md5 to make it into the final code has caused some false positives with security reviews. It would slim down web pack to make this dependency optional (maybe there are other dependencies that could be optional too), and give users the ability to not have any md5 in their build process/environment.
- **Browser:** all
- **Language:** Typescript

**Comment by laco0416** [comment]
Is this reason of `elliptic` and `browserify-sign` and `readable-stream` and... more modules which is not required by source code are bundled together?
