### ISSUE TITLE
add the google map script to angular-cli scripts array does not work

### ISSUE THREAD

**Issue by daBishMan** [webpack/webpack#3059]
1. OS?  Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)
Windows 10 x64

2. Versions. Please run `ng --version`. If there's nothing outputted, please run
in a Terminal: `node --version` and paste the result here:
angular-cli: 1.0.0-beta.15
node: 6.5.0
os: win32 x64

3. Repro steps. Was this an app that wasn't created using the CLI? What change did you
   do on your code? 
In our application before switching to the CLI and webpack, we were able to add this script in our index.html like this.
<script src="//maps.googleapis.com/maps/api/js?v=3.exp&libraries=places"></script>

I added the same script to the the angular-cli.json scripts like this:
 "scripts": [
                "//maps.googleapis.com/maps/api/js?v=3.exp&libraries=places"
            ],
but that does not work, any ideas?

**Comment by bebraw** [comment]
Can you try asking at angular-cli? This feels like an upstream issue. I'm not sure if there's much we can do about it in the core.
