### ISSUE TITLE
can not require file with async/await syntax without bebel-loader

### ISSUE THREAD

**Issue by alexey2baranov** [webpack/webpack#3061]
hello! 
Async/await syntax is available in Microsoft Edge (stable) and Google Chrome (by the Experimental Javascript flag) and very close in Firefox at the date of writing this. So I do not want use babel for this feature anymore. How can I webpack async/await'ed files without babel?

**Comment by MoOx** [comment]
I guess you cannot. The webpack parser probably does not handle it yet.

**Comment by bebraw** [comment]
Closing in favor of #2872. Subscribe there. 👍
