### ISSUE TITLE
System.import w/ expression within a target=node bundle

### ISSUE THREAD

**Issue by ctrlplusb** [webpack/webpack#3065]
**I'm submitting a bug report**

**Background**
I used Webpack 2 to bundle my SSR React app.  I bundle both the client and the server (i.e. target=web|node).

Within my configuration I am trying to use the dynamic module imports feature to do code splitting on my routes (i.e. `System.import('../components/App/views/' + viewName + '/index.js')`) .  This code will get run my the `node` bundle, which fails.

**Webpack version:**
2.1.0-beta.25

**Please tell us about your environment:**
Mac OS 10.11.6 || Windows 7
Node 6.6.0

**Current behavior:**
I get the following error when running my app:

```
TypeError: __webpack_require__.e is not a function
    at webpackAsyncContext (C:\Projects\ctrlplusb\react-universally\build\server\webpack:\src\shared\components\App\views async ^\.[\](\w|\s|-|_)*[\]index\.js$:14:1)
    at Object.getComponent (C:\Projects\ctrlplusb\react-universally\build\server\webpack:\src\shared\routes\index.js:35:5)
    at getComponentsForRoute (C:\Projects\ctrlplusb\react-universally\node_modules\react-router\lib\getComponents.js:29:16)
    at C:\Projects\ctrlplusb\react-universally\node_modules\react-router\lib\getComponents.js:41:5
    at C:\Projects\ctrlplusb\react-universally\node_modules\react-router\lib\AsyncUtils.js:84:5
    at Array.forEach (native)
```

**Expected/desired behavior:**
The System.import should resolve without an error.

**Steps to reproduce:** 
I don't have a "minimal" example, however I have a fairly minimal example in my boilerplate app:
https://github.com/ctrlplusb/react-universally

Run the following commands:
```
git clone https://github.com/ctrlplusb/react-universally
cd react-universally
git checkout tags/v4.1.0
cp .env_example .env
npm install
npm run development
```

Then open your browser, the default location is `http://localhost:1337`.  You should see the error message I described above.

Here is the System.import expression:

```javascript
      new webpack.ContextReplacementPlugin(
        /components[\/\\]App[\/\\]views$/,
        new RegExp(String.raw`^\.[\\\/](\w|\s|-|_)*[\\\/]index\.js$`)
      ),
```

**Research I performed**
 - It fails on a unix/windows machine.
 - I am running a ContextReplacementPlugin instance on the dynamic path to make the regex matching less greedy.  I removed this thinking it may be causing the error but it had no effect.
 - When I introduced `System.import` statements that contained full paths, rather than a dynamic one (e.g. `System.import('../components/App/views/Home/index.js')` the application ran without errors on a Window system.
 - I created a simple client side only (i.e. target=web) app and placed a System.import containing a dynamic expression within this app.  This also ran with no problem. 

**Language:**
ES6/7

**Comment by ctrlplusb** [comment]
Apologies, did further investigation.  This is not a windows only issue.  It's happens on any server (i.e. target node) bundle.  I had a misconfiguration on my unix clone of my app which meant the code in question wasn't being hit.

**Comment by sokra** [comment]
Could you paste the regexp used with the ContextReplacementPlugin?

**Comment by ctrlplusb** [comment]
@sokra I have updated my original post to be more reflective of my latest findings. i.e. it's a cross platform issue.  Occurs when executing a target=node webpack bundle that includes System.imports with expressions within.

I have included the regex I use for the ContextPlugin in the post, but here it is again:

```javascript
      new webpack.ContextReplacementPlugin(
        /components[\/\\]App[\/\\]views$/,
        new RegExp(String.raw`^\.[\\\/](\w|\s|-|_)*[\\\/]index\.js$`)
      ),
```

**Comment by ctrlplusb** [comment]
@sokra please hold off investigating this.  I don't want to waste your time.  I am trying to create a minimal repo that can represent the error.

**Comment by ctrlplusb** [comment]
I managed to create a minimal example where the system.import statement actually works!  I don't think this is an issue with with webpack anymore.  I did some digging and think the issue may be with react-router.

In my application I create a function and then provide it to a react-router configuration.

Here is a cut down brief example:

```javascript
const resolveAsyncView = (viewName: string) => {
  return (nextState, cb) => {
    System.import('../components/App/views/' + viewName + '/index.js')
      .then(module => cb(null, module.default))
      .catch(err => console.log(err));
  };
};

const routes = (
  <Route path="/" component={App}>
    <IndexRoute getComponent={resolveAsyncView('Home')} />
    <Route path="about" getComponent={resolveAsyncView('Index')} />
  </Route>
);

export default routes
```

I checked the call stack for the error, and found the place where react-router makes the `getComponent` call to the function I provided.

It does the following: 

```javascript
getComponent.call(route, nextStateWithLocation, callback);
```

Ouch!  So it looks like it is switching out the scope, which is making the webpack dynamic require go out of scope and hence the error?  

This is my current guess. Will report with final feedback.

**Comment by ctrlplusb** [comment]
When I get time I will try create another minimal example that illustrates the issue.

**Comment by ctrlplusb** [comment]
Egg on my face!!!

I am so sorry @sokra and @bebraw this is completely my fail.

Erroneous webpack configuration causing the issue:

```
new webpack.optimize.LimitChunkCountPlugin({ maxChunks: 1 }),
```

Doh!  Looks like this will override any attempt for a System.import to do dynamic chunking.
