### ISSUE TITLE
Custom loaders directory aka resolveLoader for webpack2?

### ISSUE THREAD

**Issue by IAMtheIAM** [webpack/webpack#3066]
QUESTION:

How do we reference custom loaders in webpack 2? 
We used to use the `resolveLoader` option from webpack 1, but in webpack 2 that property is not allowed on the schema.  

For example, my custom loaders are in `/node_modules_custom`

Thank you.

**Comment by TheLarkInn** [comment]
Are you sure this is not allowed on the schema. Can you please provide the error message and the version of webpack 2 you were running?

**Comment by IAMtheIAM** [comment]
the resolveLoader option is allowed, but the `moduleDirectories` was removed, so I don't understand how to resolve modules from a directory other than the default node_modules.

```WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.```

**Comment by IAMtheIAM** [comment]
Actually, I figured it out. We have to use 

```
   resolve: {
      // An array of directory names to be resolved to the current directory
      modules: ['node_modules', 'node_modules_custom', helpers.root('src')],
}
```
And then it resolves them just fine.

**Comment by IAMtheIAM** [comment]
I tried resolve.modules, but no success.
```
   resolve: {
      // An array of directory names to be resolved to the current directory
      modules: ['node_modules', 'node_modules_custom', helpers.root('src')],
   },
```

~\node_modules\@epegzz\sass-vars-loader doesn't exist

**Comment by Kovensky** [comment]
Use `resolveLoader.modules`.

**Comment by IAMtheIAM** [comment]
@Kovensky Thanks man! That fixed it/

```
   resolveLoader: {
      // An array of directory names to be resolved to the current directory
      modules: ['node_modules', 'node_modules_custom', helpers.root('src')],
   },
```

**Comment by IAMtheIAM** [comment]
One more Question: When should we use resolve.modules vs resolveLoader.modules?

**Comment by dsebastien** [comment]
Just to make sure I understand correctly, was the resolveLoader > modulesDirectories renamed to resolveLoader > modules?

**Comment by Kovensky** [comment]
Not exactly; it's the same change that happened to `resolve`.

**Comment by cusxio** [comment]
@Kovensky may I know specifically what do you mean by that? Isn't it the same, i.e. isn't the rename of options in `resolveLoaders` the same as `resolve` ? 

Webpack 1


```js
config.resolve = {
    modulesDirectories: [
        nodeModulesDir,
    ],
};
```

Webpack 2

```js
config.resolve = {
    modules: [
        nodeModulesDir,
    ],
};
```

**Comment by SpaceK33z** [comment]
Closing since question has been answered.

The [resolve documentation](https://webpack.js.org/configuration/resolve/) for webpack v2 is fairly good, this is all documented there.

**Comment by balazserdos** [comment]
If the following line is not added to the config, webpack 2.2.1. cannot find my custom loader. 
```
resolveLoader: {
        modules: ["web_loaders", "web_modules", "node_loaders", "node_modules"],
    }
```
The docuementation sais 

> resolveLoader
> This set of options is identical to the resolve property set above but is used only to resolve webpack's loader packages. Default:

Are you sure it works well as default?

**Comment by kartiklad** [comment]
I am facing the same issue as @balazserdos. I can't get webpack v2 to resolve the loaders from a directory other than app/node_modules. I thought it would allow me to resolve loaders from app2/node_modules (using lerna hence app and app2 live in the same repo and can reference each other)

**Comment by thecodejack** [comment]
is there anyway i can load multiple loaders from a node module??... Like use case mentioned here...

http://stackoverflow.com/questions/43886346/how-to-load-resolve-multiple-loaders-of-a-node-module
