### ISSUE TITLE
Split asynchronous loaded chunks using a regular expression

### ISSUE THREAD

**Issue by juan-ferrer-toribio** [webpack/webpack#3067]
Consider i have the following directory tree in my application:

```
 - app.js
 - locale/
  - es/
    - module1/
       - form1.json
       - form2.json
    - module2/
       - form3.json
       - form4.json
  - en/
    - module1/
       - form1.json
       - form2.json
    - module2/
       - form3.json
       - form4.json
```

And app.js has this content:

```
/* ... */
function loadLazyModule (moduleName)
{
	require.ensure ([], function ()
	{
		var lang = /* Browser language */;		
		var forms = ['form1', 'form2'] /* Get dynamically the array of forms? */
		
		for (var i = 0; i < forms.length; i++)
		{
			var translations = require (
				'locale/'+ lang +'/'+ moduleName +'/'+ form[i] +'.json');
			registerTranslations (translations);
		}
	});
}
/* ... */
```

I need a main chunk with the core of my app, but i need to split every language translations of every module in diferent chunks and load them only when requested from the user. Im already using the json-loader for json files and the 'split-by-name-webpack-plugin' but it doesn't works with dynamic loading (require.ensure).

The output should be as follows:

- myApp.js
- locale.module1.es.js
- locale.module2.es.js
- locale.module1.en.js
- locale.module2.en.js

Thanks.

**Comment by sokra** [comment]
Possible in webpack 2 with System.import

**Comment by jharris4** [comment]
FYI, this seems like the same issue: #3364

**Comment by juan-ferrer-toribio** [comment]
I've tried webpack 2.2.0 with System.import but it puts every json file in its own bundle.

There is any way to tell the webpack (via config) to put each file in a specific package using a unique dynamic import? Ej:

```
function loadModuleLocales (module, callback)
{
	var lang = navigator.languages[0].substr (0, 2);
	var forms = ['form1', 'form2']
	var imports = [];

	for (var i = 0; i < forms.length; i++)
	{
		var url = '/locale/'+ lang +'/'+ module +'/'+ forms[i] +'.json';
		imports.push (System.import (url));
	}
	
	Promise.all (imports).then (function(translations)
	{
		for (var i = 0; i < translations.len; i++)
			addTranslation (translations[i]);

		callback ();
	});
}
```
Wich should result in the following bundles:

- locale.module1.es.js <- es/module1/form1.json, es/module1/form2.json
- locale.module2.es.js <- es/module2/form1.json, es/module2/form2.json
- locale.module1.en.js <- en/module1/form1.json, en/module1/form2.json
- locale.module2.en.js <- en/module2/form1.json, en/module2/form2.json

**Comment by zhenyong** [comment]
@juan-ferrer-toribio 

There is no option to make it sense. What you can do is write code split every place like

```
require.ensure([], function(require)) {
    require('locale.module1.es.js')
    require('es/module1/form1.json')
...
}

require.ensure([], function(require)) {
    require('locale.module2.es.js')
    require('es/module1/form2.json')
...
}
```


If you think it's clumsy with duplicate codes. You can make your owner webpack loader to generate codes.
