### ISSUE TITLE
Webpack doesn't transpile 'require' calls in files with 'context' in the name

### ISSUE THREAD

**Issue by markrendle** [webpack/webpack#3068]
**I'm submitting a bug report**

**Webpack version:**
1.13.1

**Please tell us about your environment:**
Windows 7, Node 6.6

**Current behavior:**
I have a TypeScript file called 'contextualDataService.ts', being compiled with the AwesomeTypescriptLoader. That step works OK, but when the resulting JavaScript is passed through to Webpack for bundling, the `require` calls don't get transpiled to `__webpack__require`, they're just left as `require('xyz')`

It took me a while to track this down, but if I rename the file in question so it doesn't have 'context' anywhere in its name, it works.

**Expected/desired behavior:**

Webpack should work with _all_ files, even if they have got 'context' in their name.

**Comment by sokra** [comment]
Could you include your configuration? `module.noParse`?
