### ISSUE TITLE
Module not found: Error: Can't resolve 'Hammer'

### ISSUE THREAD

**Issue by jdellaria** [webpack/webpack#3069]
## **BEFORE YOU SUBMIT** please read the following:
If you have a support request or question please 
submit them to [StackOverflow](http://stackoverflow.com/questions/tagged/webpack) using the tag `[webpack]` or the [webpack Gitter](https://gitter.im/webpack/webpack). Future support requests will be closed.
(remove this from issue)

**I'm submitting a bug report**

**Webpack version:**
2.1.0-beta.25

**Please tell us about your environment:**
Ubuntu Linux 16.04 LTS

**Current behavior:**
ERROR in ./~/sequencejs/scripts/sequence.min.js
Module not found: Error: Can't resolve 'Hammer' in '/home/jdellaria/Desktop/Musicpack/node_modules/sequencejs/scripts'
 @ ./~/sequencejs/scripts/sequence.min.js 14:15212-15260
 @ ./src/index.js

**Expected/desired behavior:**

This should compile with no errors

// webpack.config.js
var path = require('path');
var config = {
    entry: './src',
    output: {
        path: './dist',
        filename: 'my-app.js'
    },
    module: 
    {
      loaders: 
      [
        { test: /\.css$/, loaders: ['style', 'css'] }, // Note that the order is important here, it means that 'style-loader' will be applied to the ouput of 'css-loader'
        { test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/,  loader: "url-loader?limit=10000&minetype=application/font-woff" },
        { test: /\.(jpe?g|png|gif|svg)$/, loader: 'url-loader?limit=10000&name=[path][name].[ext]'},
        { test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: "file-loader" },
        { test: /jquery/, loader: 'exports?$'}
      ]
    }
}
module.exports = config;

//package.json
{
  "name": "webpack",
  "version": "1.0.0",
  "description": "Jons webpack",
  "main": "index.js",
  "scripts": {
    "build": "webpack"
  },
  "babel": {
    "presets": [
      "es2015",
      "stage-0"
    ]
  },
  "author": "Jon Dellaria",
  "license": "ISC",
  "devDependencies": {
    "babel-loader": "^6.2.5",
    "html-loader": "^0.4.4",
    "img-loader": "^1.3.1"
  },
  "dependencies": {
    "hammer": "0.0.5",
    "hammerjs": "^2.0.8",
    "jquery": "^3.1.1",
    "slick-carousel": "^1.6.0",
    "ts-loader": "^0.8.2"
  }
}

<html>
    <head>
        <script type="text/javascript" src="./dist/my-app.js"></script>
    </head>
    <body>
    </body>
</html>

// src/index.js
require("!style!css!./css/styley.css");
require("sequencejs");
console.log('Hello Webpack!');
document.write("It works.");
greet('Webpack Jon');

// src/greet.js
function greet(who) {
    console.log('Hello ' + who + ', it\'s '+ '!');
    document.write('Hello ' + who + ', it\'s '+ '!');
    console.log('Hello ' + who + '!');
    document.write('Hello ' + who + '!');
};
module.exports = greet;       // Exposes the greet function to a require in another file

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.** 

* **What is the expected behavior?**
This should compile with no errors

* **What is the motivation / use case for changing the behavior?**

 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart | ...]

**Comment by jdellaria** [comment]
This should compile... I believe these files are configured correctly.

Thank You!!

Jon Dellaria
[Uploading webpackHammerError.zip…]()

**Comment by jdellaria** [comment]
I didn't mean to close this issue

Jon

**Comment by jhnns** [comment]
Sorry, this is no bug report. It looks like there is an error in your setup. Please file a stackoverflow question.

---

I know that it might be confusing to read error messages, but the error message is actually totally clear about the problem:

1. `ERROR in ./~/sequencejs/scripts/sequence.min.js`

= The problem comes from this file

2. `Module not found`

= A module, that was required in `sequence.min.js`, cannot be found

3. `Can't resolve 'Hammer' in '/home/jdellaria/Desktop/Musicpack/node_modules/sequencejs/scripts'`

= A module with the name `Hammer` cannot be resolved within the directory `/home/jdellaria/Desktop/Musicpack/node_modules/sequencejs/scripts`

Seems like Sequence.js is requiring Hammer, but it cannot be found.
