### ISSUE TITLE
Require.ensure + Require.context to have multiple dynamic loaded chunks

### ISSUE THREAD

**Issue by fkrauthan** [webpack/webpack#3072]
I was wondering if something like the following is possible.

Given the data structure:
- docs
  - doc1.json
  - doc2.json

And the following code:

``` js
function loadDoc(name, cb) {
    require.ensure([], function (require) {
        cb(require("./docs/" + name));
    });
} 
```

If I understand the current behaviour would be that doc1.json and doc2.json both end up in one chunk together (one external JS file that will be loaded dynamic). But is there any way to change the code so that doc1.json and doc2.json get there individual bundle without having to hardcode for each file a require.ensure?

**Comment by sokra** [comment]
System.import in webpack 2 will have the expected semantic. `System.import("./docs/" + name)`

**Comment by fkrauthan** [comment]
Unfortunately webpack2 will not work for me as I need the ability of (custom) named chunks which is currently not possible with webpack2

**Comment by fkrauthan** [comment]
Any news on this? It seems like based on @sokra answer that it is not possible at all with webpack1 and with webpack2 it would work like that but I would not be able to name my chunks (and in some cases merge chunks with the same name). So both webpack versions wouldn't really work for me...

**Comment by jharris4** [comment]
FYI, this seems like the same issue: #3364

**Comment by bebraw** [comment]
Closing as a duplicate.

**Comment by fkrauthan** [comment]
Why do you close the original ticket as duplicate and not the newer one?

**Comment by bebraw** [comment]
That thread is more complete, but I can reverse the decision if you insist.

**Comment by fkrauthan** [comment]
No it's ok. I was just curious. I really love webpack. It helped me a lot. Thank you for all the work.
