### ISSUE TITLE
RecordIdsPlugin slows incremental build with lots of modules

### ISSUE THREAD

**Issue by MagicDuck** [webpack/webpack#3073]
**I'm submitting a bug report**
**Webpack version:**
1.10.x/2.x

**Please tell us about your environment:**
OSX 10.x / Linux / Windows 10

**Current behavior:**
Our project has around 5000 modules. Profiling webpack told us that the makeRe
ative() function in RecordIdsPlugin takes 2s during each incremental build. If we remove it and use straight module.identifier(), the time taken becomes insignificant. 

**Expected/desired behavior:**
I believe makeRelative() is only necessary to make the records file portable. So maybe we can turn it off in watch mode or have a config option to disable it.
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.** 
  simply use console .time()/.timeEnd() in the plugin and you will see...
- **What is the expected behavior?**
  fast incremental build and scalable
- **What is the motivation / use case for changing the behavior?**
  performance

**Comment by TheLarkInn** [comment]
I think we would certainly welcome a PR for this.

**Comment by jamestautges** [comment]
I have a fix for watch mode, but I'd like to wait until Saturday for the PR if that's alright

**Comment by sokra** [comment]
The records should stay portable. We could cache the portable identifier on the module instance.

**Comment by jamestautges** [comment]
And portable ids also have to be cached on each chunk, yes?

**Comment by LukasLSC** [comment]
h
