### ISSUE TITLE
Normalize property names in schema

### ISSUE THREAD

**Issue by zhaoshengjun** [webpack/webpack#3076]
**I'm submitting a feature request**

**Webpack version:**
2.1.0-beta.25

**Please tell us about your environment:**
OSX 10.x (but it doesn't matter)

**Current behavior:**
In the [schema.json](https://github.com/webpack/webpack/blob/master/schemas/webpackOptionsSchema.json) file, part `node` has two interesting properties: `__dirname` and `__filename`. These property names are inconsistant with others.

**Expected/desired behavior:**
Change the property name to `dirname` and `filename`.
- **What is the motivation / use case for changing the behavior?**
  Make webpack better!

**Comment by sokra** [comment]
The properties are named like the variable names.
