### ISSUE TITLE
Serve error after upgrading to newest version of angular-cli

### ISSUE THREAD

**Issue by chozzz** [webpack/webpack#3079]
**Webpack version:**
2.1.0-beta.25

**Please tell us about your environment:**
Linux

**Current behavior:**
Ng serve failing with errors

**Expected/desired behavior:**
No errors given

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.** 
I am currently using `npm link` for my `angular-cli`, The error just comes after I run `ng server` like,
**./node_modules/angular-cli/bin/ng serve**

* **What is the expected behavior?**
No errors whatsoever

**Log**

> ** NG Live Development Server is running on http://0.0.0.0:9002. **
>  10% building modules 8/14 modules 6 active ...de_modules/script-loader/addScript.jsError: parseQuery should get a string as first argument
>     at Object.parseQuery (/home/vadi/dev/gits/angular-cli/node_modules/loader-utils/index.js:68:9)
>     at compiler (/home/vadi/dev/gits/angular-cli/node_modules/awesome-typescript-loader/src/index.ts:35:45)
>     at Object.loader (/home/vadi/dev/gits/angular-cli/node_modules/awesome-typescript-loader/src/index.ts:18:18)
>     at LOADER_EXECUTION (/home/vadi/dev/gits/angular-cli/node_modules/loader-runner/lib/LoaderRunner.js:114:14)
>     at runSyncOrAsync (/home/vadi/dev/gits/angular-cli/node_modules/loader-runner/lib/LoaderRunner.js:115:4)
>     at iterateNormalLoaders (/home/vadi/dev/gits/angular-cli/node_modules/loader-runner/lib/LoaderRunner.js:224:2)
>     at iterateNormalLoaders (/home/vadi/dev/gits/angular-cli/node_modules/loader-runner/lib/LoaderRunner.js:213:10)
>     at /home/vadi/dev/gits/angular-cli/node_modules/loader-runner/lib/LoaderRunner.js:228:3
>     at Object.context.callback (/home/vadi/dev/gits/angular-cli/node_modules/loader-runner/lib/LoaderRunner.js:106:13)
>     at Object.module.exports (/home/vadi/dev/gits/angular-cli/node_modules/angular2-template-loader/index.js:32:10)
>     at LOADER_EXECUTION (/home/vadi/dev/gits/angular-cli/node_modules/loader-runner/lib/LoaderRunner.js:114:14)
>     at runSyncOrAsync (/home/vadi/dev/gits/angular-cli/node_modules/loader-runner/lib/LoaderRunner.js:115:4)
>     at iterateNormalLoaders (/home/vadi/dev/gits/angular-cli/node_modules/loader-runner/lib/LoaderRunner.js:224:2)
>     at /home/vadi/dev/gits/angular-cli/node_modules/loader-runner/lib/LoaderRunner.js:197:4
>     at Storage.finished (/home/vadi/dev/gits/angular-cli/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:39:16)
>     at /home/vadi/dev/gits/angular-cli/node_modules/enhanced-resolve/node_modules/graceful-fs/graceful-fs.js:78:16
>     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3) 'Error: parseQuery should get a string as first argument\n    at Object.parseQuery (/home/vadi/dev/gits/angular-cli/node_modules/loader-utils/index.js:68:9)\n    at compiler (/home/vadi/dev/gits/angular-cli/node_modules/awesome-typescript-loader/src/index.ts:35:45)\n    at Object.loader (/home/vadi/dev/gits/angular-cli/node_modules/awesome-typescript-loader/src/index.ts:18:18)\n    at LOADER_EXECUTION (/home/vadi/dev/gits/angular-cli/node_modules/loader-runner/lib/LoaderRunner.js:114:14)\n    at runSyncOrAsync (/home/vadi/dev/gits/angular-cli/node_modules/loader-runner/lib/LoaderRunner.js:115:4)\n    at iterateNormalLoaders (/home/vadi/dev/gits/angular-cli/node_modules/loader-runner/lib/LoaderRunner.js:224:2)\n    at iterateNormalLoaders (/home/vadi/dev/gits/angular-cli/node_modules/loader-runner/lib/LoaderRunner.js:213:10)\n    at /home/vadi/dev/gits/angular-cli/node_modules/loader-runner/lib/LoaderRunner.js:228:3\n    at Object.context.callback (/home/vadi/dev/gits/angular-cli/node_modules/loader-runner/lib/LoaderRunner.js:106:13)\n    at Object.module.exports (/home/vadi/dev/gits/angular-cli/node_modules/angular2-template-loader/index.js:32:10)\n    at LOADER_EXECUTION (/home/vadi/dev/gits/angular-cli/node_modules/loader-runner/lib/LoaderRunner.js:114:14)\n    at runSyncOrAsync (/home/vadi/dev/gits/angular-cli/node_modules/loader-runner/lib/LoaderRunner.js:115:4)\n    at iterateNormalLoaders (/home/vadi/dev/gits/angular-cli/node_modules/loader-runner/lib/LoaderRunner.js:224:2)\n    at /home/vadi/dev/gits/angular-cli/node_modules/loader-runner/lib/LoaderRunner.js:197:4\n    at Storage.finished (/home/vadi/dev/gits/angular-cli/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:39:16)\n    at /home/vadi/dev/gits/angular-cli/node_modules/enhanced-resolve/node_modules/graceful-fs/graceful-fs.js:78:16\n    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:445:3)'

_Note: I am sure that this happens after the newest version of `angular-cli` because I just pull the newest version for my `angular-cli` repo and this issue happened. The last time I pulled was like a week or so ago._

**Comment by TheLarkInn** [comment]
@sokra do we need to cut a new release of loaderUtils or is this just stale nested dep?

**Comment by chozzz** [comment]
I can confirm this issue does not happen in `beta.15` version.

**Comment by sokra** [comment]
Stale nested
