### ISSUE TITLE
setting resolve.plugins option breaks context resolver

### ISSUE THREAD

**Issue by also** [webpack/webpack#3082]
**I'm submitting a bug report**

**Webpack version:**
2.1.0-beta.25

**Please tell us about your environment:**
OS X 10.11.6

**Current behavior:**

Including `resolve: {plugins: []}` in `webpack.config.js` can cause the context resolver to resolve files instead of directories, resulting in build failures like

```
ERROR in ENOTDIR: not a directory, scandir '/Users/rberdeen/work/webpack-require-context/index.js'
```

`enhanced-resolve` modifies the plugins array that it is passed.
- https://github.com/webpack/enhanced-resolve/blob/v2.3.0/lib/ResolverFactory.js#L49
- https://github.com/webpack/enhanced-resolve/blob/v2.3.0/lib/ResolverFactory.js#L203

webpack passes the same options to the normal, context, and loader resolvers.
- https://github.com/webpack/webpack/blob/v2.1.0-beta.25/lib/WebpackOptionsApply.js#L277-L286

This results in the context resolver using the normal resolver plugins.

Here's a complete test: https://gist.github.com/also/5cc6c7aedd976260e07d8a48b26cce81

**Expected/desired behavior:**
- Setting plugins to an empty array should have no effect.
- `ResolverFactory` should not mutate the passed options.
- The normal resolver's plugins should not be used by the context and loader resolvers.

**Comment by dsebastien** [comment]
I encountered the same issue, I had an empty resolve.plugins section and started getting those errors. Thanks @also for finding this one out :p
