### ISSUE TITLE
Loaded added via plugin is not used in webpack beta 23+

### ISSUE THREAD

**Issue by AndrewMorsillo** [webpack/webpack#3084]
**I'm submitting a bug report**

**Webpack version:**
2.1.0-beta.23 and higher

**Please tell us about your environment:**
Linux

**Current behavior:**
Plugin adds a loader to override the contents of a file. The added loader never resolves for the file causing a missing loader error on build.

Ex of added loader:

```
compiler.options.module.loaders.push({
      test: /my-config/,
      loader: 'json-string-loader?json=' + JSON.stringify({foo: 'bar'})
 });
```

`require('./my-config.json')` results in

> ERROR in ./~/my-plugin/my-config.json
> Module parse failed: /path/to/my-config.json Unexpected token (1:8)
> You may need an appropriate loader to handle this file type.

**Expected/desired behavior:**
`require('./my-config.json')` should contain the JSON object {foo: 'bar'}

This works correctly in beta 22 and lower as well as webpack 1.x.

The plugin exhibiting this problem is here: https://github.com/luisherranz/meteor-imports-webpack-plugin/tree/webpack2
- **Language:** [all]

**Comment by jedwards1211** [comment]
That should be `compiler.options.module.rules.push`.  But even with that change it still doesn't work.
@bebraw any idea why this isn't working?

**Comment by bebraw** [comment]
@jedwards1211 Given it has worked before, this feels like a regression. Something has changed internally preventing the feature from working correctly.

**Comment by jedwards1211** [comment]
@bebraw I'm not sure how it used to work, but I read the code yesterday and determined that once it's created a `NormalModuleFactory` with `compiler.options.module.rules`, any change to `compiler.options.module.rules` won't affect the `NormalModuleFactory`.  I fixed my plugin by updating the `ruleSet` on the `NormalModuleFactory` instead of `compiler.options.module.rules`.
