### ISSUE TITLE
console.warn is not a function

### ISSUE THREAD

**Issue by rubencodes** [webpack/webpack#3097]
**I'm submitting a bug report**

**Webpack version:**
1.13.2

**Please tell us about your environment:**
macOS Sierra

**Current behavior:**
log-apply-result.js: Uncaught TypeError: console.warn is not a function

**Expected/desired behavior:**
Webpack should either use console.error/console.log, or polyfill console.warn when not available. Or Google Chrome should implement console.warn [as their documentation describes](https://developers.google.com/web/tools/chrome-devtools/console/console-reference?hl=en#warn).

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.** 
This happened whenever the condition on line 10 of [log-apply-result.js](https://github.com/webpack/webpack/blob/master/hot/log-apply-result.js) was hit. In practice, it happened whenever hot reloading didn't work for some reason.

* **Browser:**  Google Chrome 53

**Comment by hkrutzer** [comment]
[Chrome does have console.warn](https://developer.mozilla.org/en-US/docs/Web/API/Console/warn)

**Comment by rubencodes** [comment]
So this is weird, I was able to use console.warn outside of my localhost but not in. Looks like this might be a Chrome issue...
