### ISSUE TITLE
`import()` support in webpack 2

### ISSUE THREAD

**Issue by Kovensky** [webpack/webpack#3098]
Domenic's [`import()` proposal](https://github.com/domenic/proposal-import-function) is, as of last week, [stage-2](https://github.com/tc39/proposals/commit/0a134c8), and it seems it is more promising to support that than to support the already replaced `System.import`.

The problem, though, is that that requires parser support. Having `import` followed by a `(` token is an early error in acorn... 😕

**Comment by TheLarkInn** [comment]
@domenic

Have any of the parsers started working on this that you are aware of? Either that, or maybe I can work with @RReverser and friends to create an extension or grammar plugin (if even possible).

**Comment by domenic** [comment]
I am not aware of any parser support, no.

**Comment by TheLarkInn** [comment]
Alright, thanks. I'm going to at-least file an issue with ternjs/acorn and then see if I can get the momentum support for the `grammar` type.

**Comment by TheLarkInn** [comment]
https://github.com/ternjs/acorn/issues/441

Okay it appears that we cannot implement this as acorn will wait until stage-4.

**Comment by Kovensky** [comment]
A possible hack could be to have a separate parser (even if custom) that runs first, then only looks for function-like imports and replaces them with, say, a `__webpack_import__` token that can then be looked for in the acorn step.

Function-like import will not move to stage-4 on its own without browsers or build systems like rollup and webpack actually supporting it.

**Comment by TheLarkInn** [comment]
That would work.

**Comment by TheLarkInn** [comment]
I suppose we would definitely want that to be a post loader wouldn't we.

**Comment by kesne** [comment]
I'm working on implementing a simple version of this that transforms import function calls to the require.ensure equivalent.

The issue I'm having now is linting syntax errors. So from what I can tell it'll require a PR to Babylon, a babel plugin to enable the new syntax, and requiring usage of babel-eslint.

**Comment by sokra** [comment]
If it's possible I would like to have the `import()` instead of `System.import` in the webpack 2 release.

**Comment by kesne** [comment]
I have PRs up to add `import()` syntax support to babylon, so it'll be possible to get linters working soon. Acorn still blocks the webpack parser though.

**Comment by kesne** [comment]
Would it at all be possible to change the parser from acorn to babylon? That would also be a way to solve this.

**Comment by TheLarkInn** [comment]
I know it can with esprima (thanks to a patch I tested from @ariya but I believe esprima follows similar rules for adoption. You can look at Parser.js to try. Keep in mind async import hasn't even been finalized yet and that would also be another similar change.

**Comment by hzoo** [comment]
We landed @kesne's PR so this is in Babylon now

**Comment by sokra** [comment]
I think acorn has an plugin system. Is it possible to write an plugin for this? Could someone ask the acorn author?

**Comment by sokra** [comment]
Babylon isn't possible because it has a different ast format as far as I know...

**Comment by TheLarkInn** [comment]
@sokra https://github.com/ternjs/acorn/issues/477 I did ask about this implementation. Acorn does plugins doesn't it? Could a transform plugin be written?

**Comment by RReverser** [comment]
@TheLarkInn Yes, you can totally create a plugin for this.

**Comment by ariya** [comment]
Rather than having an individual discussion regarding every future/ES.Next features, IMO it will be wise if there is a consistent policy regarding this. For instance, it could be as simple as "webpack only supports stable syntax and run-time features finalized in the most recent ECMA-262 specifications".

**Comment by karlhorky** [comment]
@ariya I think this feature may be different since it's about getting in syntax support for the 2.0 launch. Would be nice to release with something that is the current proposal.

**Comment by TheLarkInn** [comment]
I agree with @ariya that it would be wise to set a rule for all new syntax grammars across the board so our users have a unified expectation of when we will be adding new grammar support (if needed and not already provided through acorn).

**Comment by ariya** [comment]
@karlhorky Not sure I understand what is _different_ about this one.

The illustrative policy I gave was an _example_. If @TheLarkInn and the webpack folks decide that supporting Stage-4 (or even Stage-3 or Stage-2) is the policy, it's fine as long as it's consistent. But then, everyone needs to be ready with all possible consequences (e.g. when the final spec is different than the proposal because a tweak is necessary during Stage-4 discussion).

**Comment by Kovensky** [comment]
Harmony modules themselves are not finalized (that's up to a WHATWG spec, not ECMA), so implementing them at all is already a gray area. As ljharb likes to put it, "modules don't exist" (yet).

**Comment by karlhorky** [comment]
Yeah I think my point was something along the lines of what @Kovensky said. Since `import()` is the closest thing we have to something finalized, launching webpack 2 with that seems like a good idea.

I think the proposal for a support policy is also good, but probably doesn't apply to this specific thing as much.

**Comment by domenic** [comment]
In particular, `import()` is a lot more finalized (i.e. accepted by browsers) than `System.import()`, which I am told webpack currently uses.

**Comment by TheLarkInn** [comment]
So just to confirm, the implementation path appears to be one of two ways: 

- Use a loader based transform from `import()` 

- Add a temporary acorn plugin which supports the import() spec.

I feel that going the acorn plugin route. @RReverser do you think you could offer a bit of guidance on what kind of grammar symbol this is (ie keyword? etc?). Or a good example of another plugin doing the same?

**Comment by hzoo** [comment]
The babylon pr is https://github.com/babel/babylon/pull/163

**Comment by jhnns** [comment]
For every other ES next feature, webpack should not extend the parser. We should stick to the feature/syntax set that comes with our parser (currently acorn). 

This feature is a little bit different, because we need a ES2015 syntax to mark split points for webpack 2 anyway. And `import()` is definitely a better choice than `System.import()` (see https://github.com/webpack/webpack/issues/2163#issuecomment-254859208).

**Comment by TheLarkInn** [comment]
So before this is implemented we should ensure that we support System.import() still but provide deprecation warnings saying that it would be deprecated in a subsequent release. It kills me to consider dropping any more breaking changes especially in regards to this feature.

**Comment by jhnns** [comment]
Are you talking about beta releases or would you also keep `System.import()` for webpack 2? I'm ok with that (as long as there's a deprecation warning).

**Comment by TheLarkInn** [comment]
Yes. We should keep System.import() recognize import() as a new feature. And provide deprecation warning for the aforementioned.

**Comment by RReverser** [comment]
@TheLarkInn `import` is already tokenized as keyword, you just need to allow it in expression position.

**Comment by RReverser** [comment]
@TheLarkInn For now raised an issue on ESTree repo for representation. https://github.com/estree/estree/pull/137

**Comment by TheLarkInn** [comment]
Thank you very much @RReverser!!!

**Comment by kesne** [comment]
We just released a babel plugin that transpiles import() calls into webpack-1 compatible code: https://github.com/airbnb/babel-plugin-dynamic-import-webpack

**Comment by kesne** [comment]
@sokra I wrote an acorn plugin that adds dynamic import support to acorn. https://www.npmjs.com/package/acorn-dynamic-import

Hopefully this can be used to land `import()` in webpack 2.

**Comment by TheLarkInn** [comment]
@domenic just to double check are there any things behind the scenes that may change that would be advantageous for us to know about for import()

**Comment by domenic** [comment]
There is a discussion of changing from a function-like form to a unary operator. You can check the proposal repo for details. I personally would guess that change won't happen but we'll see what the committee says next week. The decision made next week should be final and should take things to stage 3 at which point browsers will start implementing.

**Comment by TheLarkInn** [comment]
Thanks I was just perusing the repo/spec a bit but I didn't see that yet. Ill take a look. Thanks.

**Comment by jhnns** [comment]
> I personally would guess that change won't happen but we'll see what the committee says next week. The decision made next week should be final and should take things to stage 3 at which point browsers will start implementing.

That would be right on time 👍

**Comment by mgcrea** [comment]
@domenic any updates regarding reaching stage 3?

**Comment by domenic** [comment]
We are stalled on some... interesting... issues. I hope we can work through them tomorrow. We did get consensus not to change the syntax, at least.

**Comment by Kovensky** [comment]
`import()` [reached stage-3](https://github.com/tc39/proposals/commit/ab0c049f7ef87a69d7fa3478e8e7a1ed035e9838) :tada:

**Comment by yuhenabc** [comment]
If you use `babel` and `webpack`, you may need [syntax-dynamic-import](http://babeljs.io/docs/plugins/syntax-dynamic-import/) plugin by official.
