### ISSUE TITLE
Include line and loc for configuration validation

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack#3101]
**I'm submitting a feature request**

**Webpack version:**
1.10.x/2.x

**Current behavior:**
We currently don't pass line numbers in the config validations errors.

**Expected/desired behavior:**
 I observed a colleague struggle to find the properties, and suggested this as a feature. I think this would be pretty nice to have. 

Would make a great "Help Wanted" PR

**Comment by gyandeeps** [comment]
I have never worked on webpack before, can you please provide/guidance on where to start for this particular issue? This would help me to get started.

**Comment by TheLarkInn** [comment]
Sure absolutely!!! 

@gajus @andreypopp would you also be willing to assist and provide guidance?

**Comment by TheLarkInn** [comment]
So I haven't personally worked on this part of the code but filename alone appears to be highly relevant. https://github.com/webpack/webpack/blob/master/lib/WebpackOptionsValidationError.js

**Comment by TheLarkInn** [comment]
@gyandeeps let me know if you get stuck anywhere, and I'd this like you can open the PR if you get stuck and we can help just ping us.

**Comment by gyandeeps** [comment]
I started looking into this. What i found was inside `validateWebpackOptions` module we use `ajv` module to validate the options. Based on quick investigation, I dont see any line numbers returned by `ajv` module.

@gajus Do you have any idea on how to get the line numbers of the error or its not possible as of now?

**Comment by sokra** [comment]
It's not possible. We validate an object not a file. There are no line information.

**Comment by TheLarkInn** [comment]
I was referring to situations where the config file is read (most common occurrence).
