### ISSUE TITLE
Consecutive SyntaxErrors are not reported by webpack --watch

### ISSUE THREAD

**Issue by p-decoraid** [webpack/webpack#3106]
**I'm submitting a bug report**

**Webpack version:**
1.13.2

**Please tell us about your environment:**
Linux

**Current behavior:**
1. Run  `webpack --watch`
2. Put a syntax error in a source file. Webpack will report that error.
3. Change the source file to have different content, but still have a syntax error. Webpack will not report the new error.
4. Fix all syntax errors in the file. Webpack compiles it and shows a successful compilation.

It seems to me that webpack tries to compile every version of the file (based on the fact that once the syntax is fixed, the bundle is built and `--progress` shows output when changing the contents of the file while it still has syntax error(s) in it), but does not report subsequent syntax errors.
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo 
  of the problem along with a gist/jsbin of your webpack configuration.** 

I created a sample repository here: https://github.com/Decor-Aid/webpack-rebuild-repro showing the problem.
- **What is the expected behavior?**

Webpack should report errors in each version of the source file as these are saved to disk.
- **What is the motivation / use case for changing the behavior?**

If a source file has multiple syntax errors, `webpack --watch` needs to be manually restarted until all errors are fixed. A situation that results in multiple syntax errors is for example trying to convert an Angular app to a React app - copy-pasting Angular code or templates into a .jsx file will produce tons of errors.
- **Browser:** 

not applicable
- **Language:** 

JS is sufficient

**Comment by p-decoraid** [comment]
Enhancement?

**Comment by sokra** [comment]
Seem to be fixed in webpack 2
