### ISSUE TITLE
Question: How do we create automated webpack build tests?

### ISSUE THREAD

**Issue by IAMtheIAM** [webpack/webpack#3107]
I hope this is the right place for this question. Basically I'm wondering how can we automate the testing of our webpack builds, for both `webpack-dev-server` (dev mode) and `webpack` (production mode)?

I figure there should be some way to run a script, which then executes all specified wds/webpack builds, and checks for "exit code 0" - then it will say "all builds passed".

The reason is because I frequently need to test my dev build and my production build before committing, and currently I have to manually run it and check for exit code 0.

**Comment by zhaoshengjun** [comment]
If you simply just want to check if the npm script runs without error, that should be easy. It's link linting before you commit the changes. You can use git hook  `pre-commit` to run the npm script for you. Here's a article you can reference: http://elijahmanor.com/npm-precommit-scripts/

If you want to make sure the result of the builds are all functioning as expected, that's totally another level of testing. You need a test suite to support that.

**Comment by IAMtheIAM** [comment]
Thanks, I'll check out that pre-commit idea. I just want to see if the script completes successfully, not test the functionality in the browser. I figured it should be pretty easy.

**Comment by IAMtheIAM** [comment]
Thank you, @zhaoshengjun git `pre-commit` works exactly as I expected and needed. Perfect.
