### ISSUE TITLE
webpack_amd_define_arr is not defined

### ISSUE THREAD

**Issue by fengxinming** [webpack/webpack#3108]
Put jquery3 and other Javascript to make one of Javascript file，then I wrote its path to HTML file and opened it in Android before I catch code exception，It show me "webpack_amd_define_arr is not defined"

**Comment by fengxinming** [comment]
I have found a reason probably about strict mode，For example:
jQuery3:
// Edge <= 12 - 13+, Firefox <=18 - 45+, IE 10 - 11, Safari 5.1 - 9+, iOS 6 - 9.1
// throw exceptions when non-strict code (e.g., ASP.NET 4.5) accesses strict mode
// arguments.callee.caller (trac-13335). But as of jQuery 3.0 (2016), strict mode should be common
// enough that all such attempts are guarded in a try block.
"use strict";

jQuery2:
// Support: Firefox 18+
// Can't be in strict mode, several libs including ASP.NET trace
// the stack via arguments.caller.callee and Firefox dies if
// you try to trace through "use strict" call chains. (#13335)
//"use strict";

**Comment by fengxinming** [comment]
@bebraw Have you fixed that bug?

**Comment by bebraw** [comment]
@fengxinming Can you provide a standalone example? Are you using webpack 1 or webpack 2?

**Comment by zhaozhe0831** [comment]
this is demo。
https://github.com/zhaozhe0831/WechatBug

`npm install`

**Comment by dawnwish** [comment]
Wechat(6.3) for Android has same question.
This question only exist in dev mode (`npm run serve`), we deploy the application on a dev server, which is build by express(4.14.0), webpack-dev-middleware(1.8.4) and webpack-hot-middleware(2.13.0)

**Comment by bebraw** [comment]
@zhaozhe0831 Can you try against webpack 2? Do you get the same result there?

**Comment by zhaozhe0831** [comment]
@bebraw I am trying.
