### ISSUE TITLE
Better error message for missing loader

### ISSUE THREAD

**Issue by tj** [webpack/webpack#3109]
## Current behavior

Attempting to get webpack to work with Electron, but when you have a missing loader instead of saying it can't load "json-loader", you get:

Cannot resolve module 'json'

Which makes you think something is doing `require('json')` or similar, which is confusing.

## Expected/desired behavior

Some explicit message referring to a loader.

👊

**Comment by andreypopp** [comment]
I think this is fixed in webpack 2 as `-loader` prefix was removed from there.

**Comment by tj** [comment]
oh shit I thought I was on 2.x, I'll close and re-open if it pops up again
