### ISSUE TITLE
How to lazy load a DLL bundle?

### ISSUE THREAD

**Issue by IAMtheIAM** [webpack/webpack#3115]
Require.ensure is awesome. But when I lazy load a huge javascript library, such as `Kendo UI` which is 3MB itself, it adds 10 seconds to my build time.

What I would like is to require.ensure a DLL bundle. I got my DLL bundle working fine, but webpack seems to expect to load it at runtime, and I havent figured out how to lazy load a DLL bundle.

I tried loading with `script-loader`

```
       require('script!../../../wwwroot/js/dlls/kendo.dll.bundle.js');
      SubscriberComponent.prototype.loadKendoUIGrid();
```

But `kendo` is undefined (which is normally set in the bundle)
I also tried `scriptjs`, which just appends the given script to the head at execution.

```
const loadScript = require('scriptjs');

      loadScript('/dlls/kendo_jquery.dll.bundle.js', () => {
        SubscriberComponent.prototype.loadKendoUIGrid();
    });
```

But `kendo` is still undefined.

If I do a normal require.ensure, it works perfectly

```
      // Async load KendoUI for jQeury, with webpack require.ensure
      require.ensure(['jquery'], function(require) {


         /** These are for the jQuery version of Kendo UI */
         // require('lib/kendoui/styles/kendo.material.min.css');
         require('../../lib/kendoui/styles/kendo.common.min.css');
         require('../../lib/kendoui/styles/kendo.default.min.css');
         require('../../lib/kendoui/js/kendo.web.min.js');
         require('../../lib/kendoui/js/kendo.core.min.js');
         require('script!../../lib/kendoui/js/kendo.grid.min.js'); // must pass through "script-loader"

         // Must call the prototype function, because 'this' is undefined inside the require.ensure during runtime
           HomeComponent.prototype.loadKendoUIGrid();

      }, "kendo.for.jquery") // 3rd parameter is the name of the chunk during compilation output - chunk.name.js
```

But again, it forces webpack to rebuild the same library every time.

So how can I lazy load a DLL bundle correctly at runtime?

**Comment by sokra** [comment]
Use the scriptjs approach. Try a different output.libraryTarget.

**Comment by IAMtheIAM** [comment]
I tried all 6 of the [options listed here](https://webpack.github.io/docs/configuration.html#output-librarytarget) and they didn't work for me. I got, "define is not defined", "module is not defined", "exports is not defined", or the same result as using default var "kendo is not defined".

Can you elaborate a little more about how to configure this correctly?

**Comment by sokra** [comment]
If that's the content of your dll bundle there is something incorrect with you dll build. The dll bundle should contain the webpack runtime.

**Comment by gaganjakhotiya** [comment]
I've been trying to do something similar. After digging a bit inside the bundled DLL file, I've come to understand that DLL bundles do not execute any modules by themselves. The execution of the first module in DLL bundle is being done (in my case) inside a progressive bundle.

I tried a diff of the bundle w/o DLL and with DLL. Here's what I found:

**Bundle in normal build:**
```
/* 0 */
/***/ function(module, exports, __webpack_require__) {

	__webpack_require__(1);
	module.exports = __webpack_require__(337);


/***/ },
/* 1 */
```

**Same code in DLL bundled - manifest build:**
```
/* 0 */
/***/ function(module, exports, __webpack_require__) {

	module.exports = __webpack_require__;

/***/ },
/* 1 */
```

**And, somewhere in a progressively built bundle, I find this:**
`__webpack_require__(1)`

I've some code in module 1 that helps me dynamically load different assets for my website. But, due to this, I've implemented a nasty workaround -- to load module 1 -- that I don't like at all.

**Comment by IAMtheIAM** [comment]
> If that's the content of your dll bundle there is something incorrect with you dll build. The dll bundle should contain the webpack runtime.

I separated the webpack runtime out of dll bundle into commons.bundle.js which is loaded before any dlls. Like this:

```
   <script type="text/javascript" src="js/commons.bundle.js.gz?8609335d43fa570a3897"></script> <--- (webpack runtime is here)
   <script type="text/javascript" src="dlls/polyfills.dll.bundle.js.gz?8609335d43fa570a3897"></script>
   <script type="text/javascript" src="dlls/vendors.dll.bundle.js.gz?8609335d43fa570a3897"></script>
   <script type="text/javascript" src="js/app.bundle.js.gz?8609335d43fa570a3897"></script>
```

**Comment by mnzaki** [comment]
How did you go about solving this? I'm facing a related (but fairly different) issue.
Have you tried placing your module imports, that are supposed to be resolved by the `DllReference`, inside a `require.ensure` block?

**Comment by IAMtheIAM** [comment]
I have yet to solve this, and I do not know how to proceed at the moment. I'm hoping we can get some more input from a webpack wizard who can shine some light on this. Hint hint @sokra :-)

**Comment by mnzaki** [comment]
Related issue: #2592

**Comment by pstephenwille** [comment]
I had the same basic problem which was due to loading order. Once I moved require.js, which defines 'define' and 'require', into the header I was able to require my modules using Webpacks libraryTarget of 'amd'.
