### ISSUE TITLE
Problems with IMG loading

### ISSUE THREAD

**Issue by prsolucoes** [webpack/webpack#3117]
I'm submitting a bug report, i think.

Im trying loading images inside <img src""> tag, but the content of src attribute not change after bundle.js generated.

2.1.0-beta.25

Project:
https://github.com/prsolucoes/goci/tree/ng2-aot/web-app

File with correct image tag:
https://github.com/prsolucoes/goci/blob/ng2-aot/web-app/src/app/home/home.component.html

Generated bundle with path:
https://github.com/prsolucoes/goci/blob/ng2-aot/resources/web-app/app.bundle.js
[search for: logo.png]

Path that image need have to work:
"/web-app/assets/logo.png"

What bundle.js have now:
.setElementAttribute(this._el_9,"src","../../static/images/logo.png"

Can anyone help me?

**Comment by prsolucoes** [comment]
I have the same problem here:
https://github.com/prsolucoes/angular2-webpack2-starter/issues/1

I have created this starter project and the issue with images/screenshots to understand better.

**Comment by Kovensky** [comment]
Your `root` option given to the `htmlLoader` looks wrong; the `root` there is for URL generation, not for resolving, so it's not a filesystem path.

I am not sure why the result is as it is, though; I would've expected a different kind of nonsense, like `/the/absolute/path/to/your/sources/../../static/images/logo.png`.

**Comment by prsolucoes** [comment]
I think you are wrong. See here:
https://github.com/webpack/html-loader

```
htmlLoader: {
    ignoreCustomFragments: [/\{\{.*?}}/],
    root: path.resolve(__dirname, 'assets'),
    attrs: ['img:src', 'link:href']
}
```

**Comment by prsolucoes** [comment]
After check i understand that if i use "/" on image "src" it will concat with "options.htmlLoader.root". So i change "root" directory to check if it will throw error and it happens OK. The problem is only with the "src" attribute that dont change:

https://www.dropbox.com/s/534rhrvceifow4f/Screenshot%202016-10-11%2016.43.24.png?dl=0
