### ISSUE TITLE
UglifyJS breaks with new module syntax

### ISSUE THREAD

**Issue by dlong500** [webpack/webpack#3118]
**I'm submitting a bug report**

**Webpack version:**
 2.1.0-beta.25

**Please tell us about your environment:**
Linux x64

**Current behavior:**
I took a working project using the old module syntax (loaders/loader/query) and replaced it with the new syntax (rules/use/options) and I get the following error:
`SyntaxError: Unexpected character '`' [main.min.js:5429,52]`
Note that replacing the syntax (only those three words) is the ONLY change made.  Using the old syntax does not yield this error.

**Expected/desired behavior:**
The bundle would be generated and minified as it is using the old syntax.
- **Language:** [ES6/7 | ES5]

**Comment by Kovensky** [comment]
Some plugins look in the wrong place for their options, especially if they were using the wrong API that just happened to work. You might need to use `{ loader: 'loader-name-loader', query: JSON.stringify({ your: 'options' }) }` in some cases :(

**Comment by dlong500** [comment]
I'm not sure that I follow.  If I'm trying to use the new module syntax can you give me an example of a working UglifyJS configuration?

The relevant parts of my webpack configuration (using the new syntax) are as follows:
```js
module: {
  rules: [
    {
      test: /\.jsx?$/,
      include: path.join(__dirname, 'src'),
      exclude: /node_modules/,
      use: 'babel',
      options: {
        babelrc: false,
        cacheDirectory: PLATFORM === 'win32' ? true : '/tmp/',
        "presets": [
          "react",
          ["es2015", { "modules": false }],
          "stage-0",
        ],
        env: {
          development: {
            "plugins": [
              ["react-transform", {
                "transforms": [{
                  "transform": "react-transform-hmr",
                  "imports": ["react"],
                  "locals": ["module"]
                }, {
                  "transform": "react-transform-catch-errors",
                  "imports": ["react", "redbox-react"]
                }]
              }],
              "transform-runtime",
              "add-module-exports",
              "transform-class-properties"
            ]
          },
          production: {
            "plugins": [
              "transform-runtime",
              "add-module-exports",
              "transform-class-properties"
            ]
          }
        }
      }
    }
  ]
},
plugins: [
  new webpack.LoaderOptionsPlugin({ minimize: true, debug: false }),
  new webpack.optimize.DedupePlugin(),
  new webpack.optimize.UglifyJsPlugin({
    compress: {
      warnings: false,
    },
    output: {
      comments: false,
    }
  })
]
```

**Comment by TheLarkInn** [comment]
Just to make sure, works you need able to provide an example of the previous loader syntax you were using?

**Comment by dlong500** [comment]
The only changes were using the new syntax (loaders -> rules, loader -> use, and query -> options).  Once I change it back to the following everything works again:
```js
module: {
  loaders: [
    {
      test: /\.jsx?$/,
      include: path.join(__dirname, 'src'),
      exclude: /node_modules/,
      loader: 'babel',
      query: {
        babelrc: false,
        cacheDirectory: PLATFORM === 'win32' ? true : '/tmp/',
        "presets": [
          "react",
          ["es2015", { "modules": false }],
          "stage-0",
        ],
        env: {
          development: {
            "plugins": [
              ["react-transform", {
                "transforms": [{
                  "transform": "react-transform-hmr",
                  "imports": ["react"],
                  "locals": ["module"]
                }, {
                  "transform": "react-transform-catch-errors",
                  "imports": ["react", "redbox-react"]
                }]
              }],
              "transform-runtime",
              "add-module-exports",
              "transform-class-properties"
            ]
          },
          production: {
            "plugins": [
              "transform-runtime",
              "add-module-exports",
              "transform-class-properties"
            ]
          }
        }
      }
    }
  ]
},
plugins: [
  new webpack.LoaderOptionsPlugin({ minimize: true, debug: false }),
  new webpack.optimize.DedupePlugin(),
  new webpack.optimize.UglifyJsPlugin({
    compress: {
      warnings: false,
    },
    output: {
      comments: false,
    }
  })
]
```

**Comment by TheLarkInn** [comment]
Thank you very much. This should help me narrow down where this big may be hiding. cc @hzoo

**Comment by TheLarkInn** [comment]
@Kovensky are you thinking babel-loader is the problem here? Maybe just a bump in loader-utils I'll check the version for that package.

**Comment by Kovensky** [comment]
@TheLarkInn tried using `options` instead of `query: JSON.stringify` everywhere in my config -- at least `svg-url-loader` ("parseQuery should get a string as first argument") still crashes, but I couldn't reproduce it with my other loaders (`eslint-loader`, `babel-loader`, `svgo-loader`, `style-loader`, `css-loader`).

I should note that the _only_ loader that behaved correctly in the beta.23 flag day was `css-loader`. Everyone else would crash if I didn't provide settings as `query: JSON.stringify(options)`. They are probably working better now because I have nuked my `node_modules` since then, but it's a good idea to bump the minimum `loader-utils` version everywhere. `npm` won't know it needs to update the `loader-utils` sub-dependency if the current version still satisfies semver.

**Comment by abouthiroppy** [comment]
Could you show us your repository?

**Comment by dlong500** [comment]
@abouthiroppy Is that question directed to me?  If so, this particular repo is a private project for a client that I can't share, but I might be able to put together a test repo at some point.

**Comment by abouthiroppy** [comment]
@dlong500 Yes.
OK,  I investigated this problem but couldn't cause an error so will write test codes.
FYI: https://github.com/issue-verifier/webpack2.1.0-verification

> I might be able to put together a test repo at some point.

Thank you.  I will try to write a test code:)
I may ask you some questions if I cannot cause a problem :bow:

**Comment by dlong500** [comment]
I don't know if it has any significance, but as mentioned in my original post the syntax error references a backtick.  I am using backticks (ES6 template literals) in a few places, so it might be good to add them to a test.

**Comment by abouthiroppy** [comment]
I got it. Thanks.

**Comment by abouthiroppy** [comment]
@dlong500 Would you try this code?

```
    new webpack.LoaderOptionsPlugin({
      minimize: true,
      debug: false,
      options: {
        babel: {
          babelrc: false,
          cacheDirectory: PLATFORM === 'win32' ? true : '/tmp/',
          "presets": [
            "react",
            ["es2015", { "modules": false }],
            "stage-0",
          ],
          env: {
            development: {
              "plugins": [
                ["react-transform", {
                  "transforms": [{
                    "transform": "react-transform-hmr",
                    "imports": ["react"],
                    "locals": ["module"]
                  }, {
                    "transform": "react-transform-catch-errors",
                    "imports": ["react", "redbox-react"]
                  }]
                }],
                "transform-runtime",
                "add-module-exports",
                "transform-class-properties"
              ]
            },
            production: {
              "plugins": [
                "transform-runtime",
                "add-module-exports",
                "transform-class-properties"
              ]
            }
          }
        }
      }
    }),
```

**Comment by dlong500** [comment]
Are you saying to move the entire options tree to the `LoaderOptionsPlugin` like as below?
```js
module: {
  rules: [
    {
      test: /\.jsx?$/,
      include: path.join(__dirname, 'src'),
      exclude: /node_modules/,
      use: 'babel'
    }
  ]
},
plugins: [
  new webpack.LoaderOptionsPlugin({
    minimize: true,
    debug: false,
    options: {
      babel: {
        babelrc: false,
        cacheDirectory: PLATFORM === 'win32' ? true : '/tmp/',
        "presets": [
          "react",
          ["es2015", { "modules": false }],
          "stage-0",
        ],
        env: {
          development: {
            "plugins": [
              ["react-transform", {
                "transforms": [{
                  "transform": "react-transform-hmr",
                  "imports": ["react"],
                  "locals": ["module"]
                }, {
                  "transform": "react-transform-catch-errors",
                  "imports": ["react", "redbox-react"]
                }]
              }],
              "transform-runtime",
              "add-module-exports",
              "transform-class-properties"
            ]
          },
          production: {
            "plugins": [
              "transform-runtime",
              "add-module-exports",
              "transform-class-properties"
            ]
          }
        }
      }
    }
  }),
  new webpack.optimize.DedupePlugin(),
  new webpack.optimize.UglifyJsPlugin({
    compress: {
      warnings: false,
      unused: true,
      dead_code: true,
      drop_console: true,
    },
    output: {
      comments: false,
    }
  })
]
```
Because I tried that and it worked.  I'm still a bit confused about the whole `LoaderOptionsPlugin` in general.  I think it's supposed to allow us to pass certain options to multiple loaders, right?  But it isn't supposed to replace the ability to pass options within the module tree, right?

**Comment by dlong500** [comment]
Did I provide what you needed?  Do you need me to do any other tests?

**Comment by leongaban** [comment]
I'm getting this error as well :( http://stackoverflow.com/questions/43683156/error-in-app-bundle-js-from-uglifyjs-unexpected-token-punc

I'm using es6 import/export and only `webpack-dev-server` or `webpack -d --watch` will work.

As soon as I try to minify the code using `webpack -p` it errors out.

<img width="697" alt="screen shot 2017-04-28 at 10 24 30 am" src="https://cloud.githubusercontent.com/assets/191636/25535465/c3a462e2-2bfc-11e7-9f2f-bf21146c75e3.png">

**Comment by bradennapier** [comment]
Also getting this - although just started looking into it

**Comment by thoughtassassin** [comment]
I am getting this error as well. This just started today (6/7/2017): 
![screen shot 2017-06-07 at 7 37 11 pm](https://user-images.githubusercontent.com/1539057/26907359-c29d1e58-4bb8-11e7-8207-42afb9b7f97e.png)

**Comment by abhinav-singi** [comment]
@thoughtassassin - Did you find any solution to above error?

**Comment by johannessjoberg** [comment]
@thoughtassassin @abhinav-singi I have the same issue. Any news on your front?

**Comment by damsorian** [comment]
I have a similar issue with UglifyJs and some postcss plugins  .. :(

**Comment by ooflorent** [comment]
UglifyJS does not support ES2015+ syntax. You must migrate to the latest version of `UglifyJSPlugin` in order to minify your code.

First you need to add (or update) the plugin dependency:

```
npm install -D "uglifyjs-webpack-plugin@^1.1.0"
```

Then _require_ the plugin:

```diff
  const webpack = require("webpack")
+ const UglifyJSPlugin = require("uglifyjs-webpack-plugin")
```

And update your build configuration:

```diff
  plugins: [
-   new webpack.optimize.UglifyJSPlugin({
+   new UglifyJSPlugin({
      sourceMap: true,
-     compress: {
-       warnings: false
+     uglifyOptions: {
+       compress: {
+         warnings: false
+       }
      }
   }),
  ]
```

**Comment by fcastilloec** [comment]
@ooflorent I'm using the version `uglifyjs-webpack-plugin@1.1.8` and I've imported it into my `webpack.config.js`
```js
const UglifyJsPlugin = require('uglifyjs-webpack-plugin');
```
The plugin section looks like this:
```js
plugins: [
  new UglifyJsPlugin(),
]
```

I'm still getting the error about back ticks: ```ERROR in bundle.js from UglifyJs Unexpected character '`' ```
If using `webpack-dev-server` there's no problem, but `webpack -p` always shows the error.
I have also tried using the same `uglifyOptions` as you mentioned previously (`warnings: false`) but still errors

**Comment by evilebottnawi** [comment]
@fcastilloec `webpack -p` add to configuration build-in `uglify` plugin in webpack with old version

**Comment by dlong500** [comment]
The posts here after the year 2016 aren't related to the original bug report (which specifically dealt with changes in webpack 2 syntax that broke some things under certain conditions).  However, that specific issue is resolved now.  Please open a new bug report if you are getting errors as they aren't related to this very specific bug report.
