### ISSUE TITLE
Define module name for AMD when output as UMD

### ISSUE THREAD

**Issue by PertapaCode** [webpack/webpack#3119]
**I'm submitting a feature request**

Possibility to have a custom name for the AMD module when output the library as UMD.

**Current behavior:**

Now with a configuration like this, only the entry name is set in the module name.

``` js
module.exports = {
  context: __dirname + '/src',

  entry: {
    text: 'componentA/text',
    button: 'componentB/button',
  },

  output: {
    path: 'dist/',
    filename: '[name].js',
    libraryTarget: 'umd',
    library: ['mylib', '[name]'],
    umdNamedDefine: true
  },

  resolve: {
    modulesDirectories: ['src']
  }
};
```

The output looks like this:

``` js
    if(typeof exports === 'object' && typeof module === 'object')
        module.exports = factory();
    else if(typeof define === 'function' && define.amd)
        define("button", [], factory);
    else if(typeof exports === 'object')
        exports["button"] = factory();
    else
        root["mylib"] = root["mylib"] || {}, root["mylib"]["button"] = factory();
```

**Expected/desired behavior:**

I think it might be interesting be possible to pass a string in **umdNamedDefine** and use this string as a name for the AMD module.

So in the above config instead of **umdNamedDefine: true** it would be possible to write **umdNamedDefine: 'mylib/[name]'** and this would output this:

``` js
    if(typeof exports === 'object' && typeof module === 'object')
        module.exports = factory();
    else if(typeof define === 'function' && define.amd)
        define("mylib/button", [], factory);
    else if(typeof exports === 'object')
        exports["button"] = factory();
    else
        root["mylib"] = root["mylib"] || {}, root["mylib"]["button"] = factory();
```
- **What is the motivation / use case for changing the behavior?**

I have been using require.js for a long time, and for most of my libraries I set the module name, to be able to request modules by name.

Now I'm trying to use webpack and looks like webpack lacks this feature.

I post a question [here](http://stackoverflow.com/questions/39955044/webpack-bundle-multiple-entry-with-module-id-to-one-file) related to this subject, but I think the question is not clear.

**Comment by sokra** [comment]
I think output.library can be an object. output.library.amd is the name.

**Comment by PertapaCode** [comment]
I'm sorry @sokra but I think output.library can not be a object, at least using libraryTarget: umd, I test and doesn't work.

I will have a look at this when I have some time, I will start from [here](https://github.com/webpack/webpack/blob/54aa3cd0d6167943713491fd5e1110b777336be6/lib/UmdMainTemplatePlugin.js#L129-L139) I think.

**Comment by glena** [comment]
This would be really helpful to have baked in WebPack. I wrote this ~~hack~~ plugin to allow you to set a different module name for VAR `libraryTarget` while using `umd`. To archive something like what rollup allows https://github.com/rollup/rollup/wiki/JavaScript-API#moduleid.

https://github.com/glena/webpack-custom-var-library-name-plugin

The main issue with the implementation is that there is no way to actually know which one is being processed (amd, commonjs or standalone) so it check for a string starting with `root[` (not proud of).

**Comment by PertapaCode** [comment]
Thank you @glena

**Comment by spatialillusions** [comment]
I will try out your plugin @glena, but I agree with that it would be wonderful if this was built into webpack

**Comment by PertapaCode** [comment]
Thank you @glena and @spatialillusions
