### ISSUE TITLE
Loading large remote library from within a bundle using requirejs?

### ISSUE THREAD

**Issue by KingScooty** [webpack/webpack#312]
So i've got everything bundling up nicely with webpack. However, one of the bundled modules requires loading in a large library from a remote CDN all written to be used with used requirejs.

Is it possible to use requirejs from within a bundled file to asynchronously load the library in?

I've got something similar to this (see below) so far, but it's throwing `undefined is not a function`. Requirejs seems to be to blame.

``` javascript
var requirejs = require('requirejs');

requirejs.config({
    paths: {
      'libraryfile1':'url',
      'libraryfile2':'url'
      [...]
    }
});

requirejs(['libraryfile2'], function ($) {
  [..]
});
```

I need to add that the `libraryfile2` in this example has more dependencies, so needs to be asynchronously loaded in with requirejs - i can't copy all the assets to my local environment.

**Comment by MazheM** [comment]
After 2 years i have same problem as a cliren. Can someone help?

**Comment by vincent-pli** [comment]
Ha. after 3 years I have same problem ^_^
