### ISSUE TITLE
Creating multiple language bundles from one source module

### ISSUE THREAD

**Issue by peterjuras** [webpack/webpack#3120]
I'm wondering whether and how webpack can be used to create multiple outputs from a single module.
# Scenario

Our packages have resource files and we are importing them directly:

``` js
import strings from './resources.json'
```

The files within the packages are in a default language (english) and will be overriden depending on the loaded language. We only want to load the language that is required, therefore we would want `resources.json` to be the same JSON object, but with the correct translated resources when we import the strings. All language resources should be built at build time.
# Current implementation

Right now, we have a quite hacky solution, which results in parallel builds per language:
- There are two entries, which point to the same entry point:

``` js
entries: {
  code: './index.js',
  en: './index.js',
}
```
- A custom loader for resource files loads the correct resources for a file from an external resource. The language is set as a loader option.
- A custom plugin removes the language resources from the chunk that is named 'code', they will now only exist in the 'en' chunk.
- A CommonsChunkPlugin instance is ran on top of the two chunks. This leads to the code chunk containing all code except the language resources and the 'en' chunk only containing the language resources.

These steps are repeated with parallel builds for various languages, which means we end up with the following structure:

```
code.js (Bundle with all code, no language resources)
en.js (Language resources for English)
de.js (Language resources for German)
...
```

The language resources are then loaded dynamically through scriptjs during the app initialization.
# Question

The current implementation works but it seems very hacky and wasteful, since supporting 8 languages triggers 8 parallel builds.

Is there a better way to solve this problem?

**Comment by donaldpipowitch** [comment]
> The current implementation works but it seems very hacky and wasteful, since supporting 8 languages triggers 8 parallel builds.

I investigated a lot in this. The best thing I could came up with is currently this: https://twitter.com/PipoPeperoni/status/795970420939821056

**Comment by zhaoshengjun** [comment]
Use `i18n-webpack-plugin`. 

Your `webpack.config.js` should looks like this:

```
var path = require("path");
var I18nPlugin = require("i18n-webpack-plugin");
var languages = {
	"en": null,
	"de": require("./de.json")
};
module.exports = Object.keys(languages).map(function(language) {
	return {
		name: language,
		entry: "./index.js",
		output: {
			path: path.join(__dirname, "js"),
			filename: language + ".output.js"
		},
		plugins: [
			new I18nPlugin(
				languages[language],
				{
					functionName:'TRS',
				}
			)
		]
	};
});

```

And in your `js` file, whenever you want to do a translation, put `TRS` in front. Something like this:
`console.log(TRS("Hello world!"))`.

Also you need to put the translation into a file, e.g.`de.json` in this example.

It will do the trick.

ps: the above example is taken from the example folder in webpack repo.

**Comment by donaldpipowitch** [comment]
`module.exports = Object.keys(languages).map(function(language) {` create multiple configs. I guess the point here is to _not_ have multiple configs.

**Comment by piyaa** [comment]
@zhaoshengjun : I tried using your example language chunks and I get this:

`Module not found: Error: Cannot resolve 'file' or 'directory' ./src/languages in /Users/..`

here is how im using: 

```
module.exports = [{(Object.keys(languages).map(function(language) {
    return {
        name: language,
        entry:"./src/languages",
        output: {
            path: path.join(__dirname, "js"),
            filename: language + ".output.js"
        },
         plugins: [
            new I18nPlugin(
                languages[language]
            )
        ]
    };
}]}
```

I see its failing at the entry the point, not able to recognize the path correctly, though I verified the path and it seems to be right! any ideas what is wrong?

**Comment by zhaoshengjun** [comment]
The configuration is used to generate multiple instances of `webpack` with slightly different configuration. But each configuration should be workable, which means the `entry`, `output` should be just the same as a single configuration.

The difference is `i18n-webpack-plugin` will generate the `output.js` based on the language, by replacing the string with the translation file (`.json` file).

So make sure the `entry` points to the `index.js`, which should be the one you defined as
```
entries: {
  code: './index.js',   //<----this one should be the entry point in the new configuration file.
  en: './index.js',
}
```

In your `index.js`, you should put `TRS` in front of the string you need to translate. Something like this:
```
console.log(TRS("Hello World"));
```

In your `.json` file, it should map the `Hello World` to the correct translation:
```json
{
	"Hello World": "Hallo Welt"
}
```

Let me know if you have any question.

**Comment by peterjuras** [comment]
I think the `i18n-plugin` does a great job in solving basic localization use cases.

For our purpose however I see two shortcomings:

- Having string resources in the code directly makes it harder to extract them and centralize them compared to having them in separate files. We need this to pass a collection of all resources to translation agencies/departments.
- Sometimes a value that is represented in the same string in English has different representations in different languages. (E.g. in English you can put "OK" in two different places, but in another language they strings should be two different words because of context and meaning). This leads to approaches where each resource has a unique identifier, regardless of whether it coincidentally has the same English value. I don't see how the i18n plugin can cover this case.

**Comment by zhaoshengjun** [comment]
Yes, that's true. `i18n-webpack-plugin` has many shortcomings. It's just a simple plugin to do easy translation.

You can post your request as issue on that repo. I think someone will take look at it. And we sure can make it better :smile:

**Comment by m-lautenbach** [comment]
You don't need to have English as keys, you can have generic tags. And you can still have all your translations in separate files. Just don't use any 'null'. In the configuration.
The plugin will even warn you if there is no translation for a tag.
