### ISSUE TITLE
Target `electron-main` loads the "browser" version of `bluebird` instead of the "release" version

### ISSUE THREAD

**Issue by scottrippey** [webpack/webpack#3121]
**I'm submitting a bug report**

**Webpack version:**
1.10.x

**Please tell us about your environment:**
OSX 10.x

**Current behavior:**
I have my webpack target set to `electron-main`
I am requiring `bluebird@3`, which has both `main` and `browser` fields listed in `package.json`. 
I expect the `electron-main` target to load the `main` source, but it loads the `browser` source instead, which causes many runtime errors.
It's possible that this issue is affecting other packages that have `browser` options as well.

```
import bluebird from 'bluebird';
import fs from 'fs';
bluebird.promisifyAll(fs); // Fails with error "k is not a function"
```
### Workaround:

Here is a workaround that works as expected:

```
import bluebird from 'bluebird/js/release/bluebird`;
import fs from 'fs';
bluebird.promisifyAll(fs); // Successful
```

**Comment by TheLarkInn** [comment]
Would you be willing to test this on webpack v2

**Comment by TheLarkInn** [comment]
In [webpack@2.1.0-beta / master](https://github.com/webpack/webpack/blob/master/lib/WebpackOptionsDefaulter.js#L81-L86): 

```javascript
this.set("resolve.mainFields", "make", function(options) {
        // start in browser field first, then look in module, then main
	if(options.target === "web" || options.target === "webworker") 
		return ["browser", "module", "main"];
	else
        // if target: node, or anything else, look at module then main
	return ["module", "main"]; 
});
```

**Comment by scottrippey** [comment]
Sorry, I'm fairly new to webpack and I'm working on a huge project with a very complicated webpack config.  I tried naïvely to upgrade to webpack@2 and build, but I'm met with countless config errors.
Clearly, by the look of that `WebPackOptionsDefaulter.js` code, I'd expect it to work correctly.  I'll see if I can find the webpack@1 equivalent of that code, to see if that's where the issue lies.
