### ISSUE TITLE
npm@latest points to beta

### ISSUE THREAD

**Issue by mariotacke** [webpack/webpack#3122]
New webpack installs install webpack 2 (beta) by default. Is there a reason why the `latest` does not point to `1`? We could utilize the `next` tag to specify 2 until officially released.

`npm view webpack dist-tags` => `{ latest: '2.0.6-beta', beta: '2.1.0-beta.25' }`. Both are `beta` releases.

**EDIT: SOLUTION**
It turned out to be a caching issue with our private `sinopia` server which listed the incorrect version.

**Comment by TheLarkInn** [comment]
What specifically are you running in npm when you install?

**Comment by mariotacke** [comment]
`npm install --save-dev webpack`

**Comment by TheLarkInn** [comment]
😳 I just fixed this a couple weeks ago. I'm away from a computer for about 30-50min but I'll check this and correct it.

**Comment by mariotacke** [comment]
No worries. My team and I appreciate it!

**Comment by TheLarkInn** [comment]
<img width="1143" alt="screen shot 2016-10-11 at 8 02 12 pm" src="https://cloud.githubusercontent.com/assets/3408176/19293867/9dd8cc84-8fed-11e6-9f6b-a71806a2cabf.png">

Okay here is the attached console response from me running that command. (I haven't made any changes etc.) Timestamp is included to show you this is as of just now (CST). 

Would you double check and confirm, could this be a npm cache issue?

**Comment by mariotacke** [comment]
Totally a caching issue. We are running a `sinopia` server at work which apparently had this cached. Sorry about the confusion. I cleared my sinopia token in my `.npmrc` and it now resolves fine. Thanks for your help.
