### ISSUE TITLE
An empty Array is not considered a valid entrypoint (configuration validator edge case)

### ISSUE THREAD

**Issue by niieani** [webpack/webpack#3123]
**I'm submitting a bug report**

**Webpack version:**
    >=2.1.beta.25

**Current behavior:**
Empty Array does not validate as a valid entrypoint. This used to work before validation was introduced. 

**Expected/desired behavior:**
An empty Array should be considered valid by the configuration validator, since its contents can be filled programmatically by a plugin.

**Problematic configuration**:

``` js
entry: {
  app: [], // <-- this entrypoint will be filled programmatically by the aurelia-webpack-plugin
  another: ['some-package', 'some-other-package']
},
```

**Error**

``` js
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.entry['app'] should be one of these:
   string | [string]
   The entry point for one output file.
 - configuration.entry should be one of these:
   object { <key>: string | [string] } | string | [string]
   The entry point(s) of the compilation.
```

Related issue: https://github.com/aurelia/framework/pull/626#issuecomment-253002800

**Comment by TheLarkInn** [comment]
🤔, interesting find. Is this via an Aurelia webpack plugin? What's the reasoning behind leaving there entry blank?

**Comment by niieani** [comment]
@TheLarkInn the idea is the user CAN set up an empty `app` entry point which is then filled in with dependencies from a named chunk, both via a `require.resolve` or via the `aurelia-webpack-plugin`, but one does not have to specify it, in which case the chunk will be merged with whichever entrypoint required that dependency.

In simple terms, it's about programmatically filling an entrypoint, which I believe should be totally doable. I'd love for this to get fixed ASAP cause it's causing headaches and stopping migration to latest Webpack betas within the Aurelia community.

**Comment by sokra** [comment]
Plugins should not modify the configuration. They can add an entry via plugin hooks. See MultiEntryPlugin or apply the MultiEntryPlugin inside of the Plugin.

**Comment by niieani** [comment]
@sokra the plugin **does not modify configuration**, perhaps you misunderstood. It only enforces files are present in a specific chunk with the name `app`, just as if you did `require.ensure(..., 'app')`.

**Comment by niieani** [comment]
Probably still nice to have, so bump.

**Comment by sokra** [comment]
No empty entries are not valid. No entries (`entry: {}`) are valid. Plugins could create entries.

**Comment by sokra** [comment]
On demand chunks referencing entrypoints are invalid and will lead to errors.
