### ISSUE TITLE
How to use material icons in webpack from local folder/path of project??

### ISSUE THREAD

**Issue by kushwahashiv** [webpack/webpack#3124]
How to configure wepack.config to use [material icons](https://design.google.com/icons/) from assets/local foder of project??

**Comment by michelgotta** [comment]
You can install `material-design-icons` via npm. Use the `svg-url-loader` and following config:
```
module.exports = {
    module: {
        loaders: [
            {test: /\.svg$/, loader: 'svg-url-loader'}
        ]
    }
};
```

In your `script.js` for example:
`require("svg-url!material-design-icons/editor/svg/production/ic_attach_file_18px.svg");`
