### ISSUE TITLE
Invalid configuration object

### ISSUE THREAD

**Issue by vanthiyathevan** [webpack/webpack#3134]
**I'm submitting a bug report**

**Webpack version:**
2.x

**Please tell us about your environment:**
Linux:Arch

**Current behavior:**
Trying out weback 2 beta 25, Validation keeps failing for `entry` section of config. But getting this error
```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.entry['app-vendors'] should be one of these:
   string | [string]
   The entry point for one output file.
 - configuration.entry should be one of these:
   object { <key>: string | [string] } | string | [string]
   The entry point(s) of the compilation.

```

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.** 
```js
 entry: 
   { 'react-app': [ './src/main.jsx' ],
     vendors: 
      [ 'babel-polyfill',
        'react',
        'reselect',
        'axios',
        'material-ui',
        'numbro',
        'moment',
        'redux/es',
        'reselect',
        'recompose',
        'recharts/es6',
        'lodash/fp' ] }

```

Why is this config for `vendors` not valid? This is working with 2.0 beta 22.

**Comment by bebraw** [comment]
There's not enough info to debug. Can you add that `app-vendors` related bit to your issue as it fails there?

**Comment by vanthiyathevan** [comment]
Closing this because this is working. When I removed `reselect` in the vendor it started working.
