### ISSUE TITLE
Loader query is string if style-loader is in loader chain

### ISSUE THREAD

**Issue by farwayer** [webpack/webpack#3136]
```
...
rules: [
      {
        test: /\.css$/,
        use: [
          'style',
          {
            loader: 'css',
            options: {modules: true, localIdentName: '[path][local]'}
          }
        ]
      }
```

`query` passed to `css-loader` will be string instead object.

Bug is in [`NormalModuleFactory`](https://github.com/webpack/webpack/blob/master/lib/NormalModuleFactory.js#L81)

**Comment by andreiglingeanu** [comment]
Is this already fixed by chance? I'm still experiencing it in `v2.2.0-rc.1`.

**Comment by mrkev** [comment]
Can someone confirm if this has been fixed?

**Comment by Kovensky** [comment]
I'm not sure I understand the whole issue _but_ I believe it's a design issue in the pitching loader API (the API that style-loader uses). In order for the other loaders to still see the file and not just think that everything was handled by `style-loader`, `style-loader` needs to inject a loader request that looks like `css-loader?{"css-loader-options":"here"}!./requested/file`, which stringifies the request.

This is not a solution or workaround or anything, but just trying to explain why fixing this will not be easy.
