### ISSUE TITLE
System.load support?

### ISSUE THREAD

**Issue by taion** [webpack/webpack#3141]
**I'm submitting a feature request**

**Webpack version:**
2.x
- **Language:** ES6/7

We've been migrating from using `require.ensure` to `System.import`. We've run into an interesting problem. To polyfill `window.Intl`, previously we did:

``` js
if (global.Intl) {
  runApp();
} else {
  // TODO: Use System.import.
  require.ensure([], require => {
    require('intl');
    require('intl/locale-data/jsonp/en');

    runApp();
  });
}
```

Now we do:

``` js
if (global.Intl) {
  runApp();
} else {
  Promise.all([
    System.import('intl'),
    System.import('intl/locale-data/jsonp/en'),
  ])
    .then(() => runApp());
}
```

The problem is that this doesn't quite work – the code in `intl/locale-data/jsonp-en` needs to be executed after the code in `intl`.

What we want to do here is to load both modules in parallel, but control the order of execution of those modules.

For this use case, `System.import` is not enough – we actually need `System.load`.

**Comment by TheLarkInn** [comment]
Is it possible to import these two in the correct order into a separate file and then `System.import()` that file as a workaround?

**Comment by taion** [comment]
Yeah – actually @ljharb recommended that to me as well. It feels a little silly to make a separate module just to get two split-out modules to evaluate in the right order, though.

**Comment by ljharb** [comment]
fwiw, I filed https://github.com/domenic/proposal-dynamic-import/issues/16 to see if this is a problem that `import()` could or should solve.

**Comment by taion** [comment]
Or yeah `import()` taking multiple arguments would be even better. Wonder why SystemJS didn't have that.

**Comment by ljharb** [comment]
Looks like the best solution is: 'paths.map(x => (fetch(x), x)).reduce((p, x) => p.then(() => import(x)), Promise.resolve())` which will give you parallel loading but serial execution.

**Comment by Kovensky** [comment]
Unfortunately, that snippet is too dynamic for webpack to parse.

But anyway, even if you spell it out as straightforward as possible to webpack's parser, the problem is that a System.import does not correspond to a split chunk. You can't just write `fetch` calls as you don't know the output file at build time. There are plugins in webpack.optimize that may combine chunks, and some other plugins may move files to other chunks still, or a chunk may consist of multiple files with aggressive splitting, the filename might have a hash, etc.

webpack would need a System.load, or some other ad-hoc way of signalling to webpack that you want to load the code for the given modules without executing them. Overloading fetch would cause conflicts with code that actually want to use it for requests. require.ensure does it, but it uses commonjs requires that block tree shaking.

Hm, would `require.ensure(['a', 'b'], async () => { await System.import('a'); await System.import('b'); main() })` DWIM, or would it still create a commonjs dependency?

**Comment by taion** [comment]
BTW, it looks like the original `System.import` code I had above was also creating two separate chunks, so maybe lacking `System.load` isn't the only problem here.

**Comment by sokra** [comment]
Seems like intl/locale-data/jsonp... has an implicit dependency to intl. Make it explicit with theach imports-loader.

Can't go into detail as I'm writing from mobile, but maybe someone else can jump in. (test intl/locale-data/jsonp, loader imports-loader?Intl=intl)

**Comment by ljharb** [comment]
@Kovensky obv you'd transpile `import()` to something similar to my snippet, but using `require.ensure` and a static path, such that webpack could parse it.

**Comment by taion** [comment]
Closing this as irrelevant given resolution of https://github.com/tc39/proposal-dynamic-import/issues/16

**Comment by rosenfeld** [comment]
Could this issue be reopened please? Consider something like this:

```javascript
// dynamic-polyfills.js
const promises = [];
if (!Object.values) promises.push(import('object.values'));
if (!Object.assign) promises.push(import('es6-object-assign/auto'));
if (!(window.URLSearchParams && window.fetch))
  promises.push(import('./url-search-params-and-fetch-polyfills'))
else {
  if (!window.URLSearchParams) promises.push(import('url-search-params-polyfill'));
  if (!window.fetch) promises.push(import('whatwg-fetch'));
}
if (!window.HTMLDialogElement) {
  promises.push(import('dialog-polyfill'));
  promises.push(import('dialog-polyfill/dialog-polyfill.css'));
}
export default Promise.all(promises);
```

So, what is the problem with such approach? Suppose the 'dialog-polyfill' package requires "Object.assign". Then it will raise if the dialog polyfill is executed before es6-object-assign. System.load would allow us to just starting downloading all required polyfills in parallel while allowing us to specify the order when they should be executed.

Could you please reconsider this feature? Or at least stop calling require.ensure a legacy method if you don't provide another one to solve this problem.

**Comment by ljharb** [comment]
@rosenfeld polyfills can never be loaded asynchronously; that's just unavoidable.

**Comment by rosenfeld** [comment]
That's not true. I actually use the approach I mentioned. I have two configurations in my webpack build, one for legacy browsers (IE11 mostly) with babel targetting ES5 basically and including the Promise polyfill and another one targetting modern browsers. Some polyfills are missing in some of those "modern" browsers, so I load them on demand. It's an SPA with a single point of entry, our client-side router. It's loaded like this:

```javascript
import('dynamic-polyfills').then(() => render(<MyRouter/>, document.body))
```

That works fine, and only the required polyfills are loaded on demand and they should stay cached in the browser anyway.

However some polyfills might rely on other polyfills, so it would still be interesting to be able to control the order in which the polyfills are loaded while allowing them to be downloaded in parallel.

**Comment by ljharb** [comment]
I believe the way to do *that* is to create an entry point that synchronously imports them, and `import()` that entry point instead.

**Comment by rosenfeld** [comment]
This way you end up loading 10 polyfills when the browser only needs one. Even worse, once your application requires a new polyfill it will invalidate the cache.

**Comment by ljharb** [comment]
Neither of those is a problem on many major high traffic websites ¯\\\_(ツ)_/¯

Separately, “the method is present” doesn’t ensure its correct, especially for Object.assign - the shim, not your code, should be in charge of whether it’s applied or not.

**Comment by rosenfeld** [comment]
I'm talking about bundle size and parsing time, which impact in the initial load. Whether or not the polyfills are conditionally applied is not important. I don't want my clients to download and parse more code than required. Anyway, the technique I described is not something really new, it's just best practice.

**Comment by ljharb** [comment]
Right - I’m saying that you can’t know whether it’s required until you download and parse the shim.

It is not a best practice to do what you’re suggesting; the best practice is to unconditionally and synchronously send down all possible shims and let them sort out in-browser if they need to be applied or not.

**Comment by rosenfeld** [comment]
Well, there are trade-offs. When you send all shims in a single request, it could be faster in HTTP/1, but you're sending more data than needed, which is specially bad for low limit 3G plans for example. When serving over HTTP/2 the impact of the extra requests is not that high. Also, the way I used in the example has better caching for the polyfills and ideally would only load the polyfills in the first access. If a new shim is required later, only that new shim would be downloaded. And I don't need the polyfills in place to know whether a polyfill is missing or not, as I demonstrated in the example above.

**Comment by ljharb** [comment]
You demonstrated it incorrectly; Object.assign is present but broken in a number of environments. This is a common mistake, and is easily resolved by unconditionally loading every shim.

**Comment by rosenfeld** [comment]
The basics seems to work well in all supported browsers in our app, so I'm not worried about that. Luckily an application should have their tests run against all supported browsers so we would know if we're using a feature that is missimplemented in some browsers. I don't think this is a compelling reason to deliver much more code to modern browsers than required... When you add all polyfills the change can be significant.
