### ISSUE TITLE
Uncaught Error: Received packet in the wrong sequence if config.devtool = ''

### ISSUE THREAD

**Issue by vedtam** [webpack/webpack#3150]
Hi ,

I were using for quite some time the [mysql](https://www.npmjs.com/package/mysql) node driver in my Electron projects which works fine. But now while using Webpack, my production builds throw:

`Uncaught Error: Received packet in the wrong sequence.`

After some testing I have realised that the error goes away if I keep config.devtool = 'eval' in my webpack.conf.js file, otherwise it crashes:

```
if (process.env.NODE_ENV === 'production') {
  config.devtool = '' // <----- this will throw Uncaught Error if I omit 'eval'

  config.plugins.push(
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': '"production"'
    }),
    new webpack.optimize.OccurenceOrderPlugin(),
    new webpack.optimize.UglifyJsPlugin({
      compress: {
        warnings: false
      }
    })
  )
}
```

home.js:

```
<script>
  var mysql = require('mysql')
  var connection = mysql.createConnection({
    host: 'localhost',
    user: 'root',
    password: 'password',
    database: 'EONIC'
  })

  connection.connect()
  connection.query('SELECT * from products', function (err, rows, fields) {
    if (err) throw err <---- here will the error happen
    console.log(rows)
  })

  connection.end()

</script>
```

error happening in mysql/lib/protocol/Protocol.js at line 272:

```
 if (!sequence[packetName]) {
    var err   = new Error('Received packet in the wrong sequence.');
    err.code  = 'PROTOCOL_INCORRECT_PACKET_SEQUENCE';
    err.fatal = true;

    this._delegateError(err);
    return;
  }

```

I understand that the error is reflected on the mysql driver's side, but this happens only in the projects in which I use Webpack. Why does it crashes without **eval**??

Keeping **config.devtool = 'eval'** solves the problem but this way my project slows down and increases in size..

**Webpack version:**
webpack: 1.13.0
webpack-dev-server: 1.14.1

**Please tell us about your environment:**
OSX 10.11 / Windows 7

**Comment by SpaceK33z** [comment]
I don't know why it crashes precisely, but I do know that webpack v2 does not allow this.

**Comment by vedtam** [comment]
Does not allow what?

**Comment by SpaceK33z** [comment]
Ah never mind, apparently it does allow an empty string in v2. In webpack v2 there is more configuration validation, and I thought it also checked if you had an incorrect value in `devtool`. I just tested this, but it apparently it only checks if `devtool` is a `string` or is `false`.

**Comment by vedtam** [comment]
@bebraw I have figured it out that this problem arises only when an imported module (mysql.js) is placed inside a renderer process and goes trough Wbpack while bundling up. The error is gone if I keep this module in the main process.

I would like to help (too curious) I only need a clue where I can look for issues. So why does the production build throw this exception if config.devtool=""? Maybe #eval-source-map only surpresses warnings which are immediately thrown in production builds without eval ()?

**Comment by lukaszkukawski** [comment]
Hi,
What is the status of this task?
I have this same error, and i don't want to use devtool = "eval" on production

**Comment by kuldeepkeshwar** [comment]
Hi, I'm also facing same issue with webpack 2 

@vedtam

**Comment by bluepeter** [comment]
I haven't looked deeply into this but fixed it in my situation by `UglifyJsPlugin` setting `mangle` to `false`. Not ideal, but works in a pinch.
