### ISSUE TITLE
DepBlockHelpers won't bind callback to context if several chunks should be loaded

### ISSUE THREAD

**Issue by betalb** [webpack/webpack#3151]
Generated code may change context of executing code in some cases

**Current behavior:**
When DepBlockHelpers.getLoadDepBlockWrapper is called with more than one chunk, wrapper is generated that will change `this` context of wrapped code

**Expected/desired behavior:**
Context should not be changed

Example can be found here: https://github.com/betalb/webpack-DepBlockHelpers-issue

`alert` call in `src/app.js` should produce `true`, but `false` is produced

**Webpack version:**
1.13.2

**Please tell us about your environment:**
Windows 10

**Comment by betalb** [comment]
Possible fix: https://github.com/betalb/webpack/commit/59db356cfef1d3ff1fb0af23071ac1b5b923342c

**Comment by sokra** [comment]
This was fixed
