### ISSUE TITLE
Watch for config changes

### ISSUE THREAD

**Issue by alexfedoseev** [webpack/webpack#3153]
**I'm submitting a feature request**

**Webpack version:**
2.x

**Please tell us about your environment:**
OSX 10.x

**Current behavior:**
I'm not sure if this was discussed before, but it's one of the pain point for me in webpack workflow.

When config / config's dep is updated — hot reloadable server (or watch mode) must be restarted manually. Usually this hot reloadable server is not stand-alone process, but part of the bigger task or even lives inside docker container. And in case of config related change — the only way to pick this up is to restart everything. 

**Expected/desired behavior:**

It'd be cool if webpack could track such changes and rebuild everything from scratch w/o killing current process.

**What is the motivation / use case for changing the behavior?**

It'll make easier:
- work on webpack config setup
- work w/ loader's configs, eg postcss plugin's options (js vars etc)

**Comment by Kovensky** [comment]
Unfortunately, a webpack config file is not necessarily pure. Automatically reloading impure config files can result in pain and suffering.

Plugins may also want to run at hook points that happen before the `watch-run` loop, so if _those_ plugins need reloading, they will never be called again, unless webpack destroys and re-creates the compiler every time.

Even if you write things as "pure"ly as possible for your export, if you `require` anything at all besides `require('webpack')` inside the config, it's no longer reloadable.

**Comment by alexfedoseev** [comment]
@Kovensky Agreed. The case when webpack destroys and recreates everything from scratch on change in config / its dep is the behaviour that solves all the issues w/ min pain and this is what I meant initially. I guess this part was confusing:

```
... and reload config in the same manner as it tracks app deps in watch mode.
```

Not in the same manner, but just tracks changes and rebuilds everything from scratch. I'll update the issue.

Personally I don't care if it'll take time, restarting global task or docker will take even more time. If I changed something in config — well it means that I want to see the result of this change and next thing that I'll do is restart, so it might make sense to do this internally.

**Comment by bebraw** [comment]
FWIW, it's fairly simple to patch something together yourself using Chokidar. Here's [my go at it](https://gist.github.com/bebraw/a990a206d9b66b14b8e6). That's for webpack 1 so it webpack-dev-server may need a little patching to work around a bug, but it works.

**Comment by Kovensky** [comment]
@bebraw that would deal with the webpack.config.js itself, but the wishlist includes the dependencies

**Comment by bebraw** [comment]
@Kovensky Yeah, that's a harder problem for sure. [npm-install-webpack-plugin](https://github.com/ericclemmons/npm-install-webpack-plugin) might be worth studying in detail.

**Comment by bebraw** [comment]
The problem with configuration dependencies is that some of those are implicit (think loaders). It would be an easier problem with explicit imports. Now it's going to get kind of tricky to figure out what changed if I'm understanding right.

**Comment by jzaefferer** [comment]
Another workaround, using nodemon, is described in https://github.com/webpack/webpack-dev-server/issues/440#issuecomment-205757892

**Comment by bebraw** [comment]
The nodemon trick works great. You can make it work with webpack 2 env like this ´  "start": "nodemon --watch webpack.config.js --exec \"webpack-dev-server --env development\"",`.

The browser will still cache some bits like **html-webpack-plugin** title, but it works well enough for it to be worthwhile.

I guess ideally WDS should force a hard refresh if this functionality is implemented there.

**Comment by bebraw** [comment]
Moved to https://github.com/webpack/webpack-cli/issues/15.

**Comment by owenstrevor** [comment]
I'm curious why this was moved to webpack/webpack-cli#15

Isn't in the right place and it should actually be a part of webpack or maybe even webpack/watchpack?

This idea has been request in multiple threads and just tracking down a solution is like Alice falling down the rabbit hole into wonderland. It appears to eventually have been added to the webpack-cli but then removed as of a few weeks ago. Then re-added, but with the wrong implementation spec so that it no longer accomplished the same thing as the nodemon hack.

I am trying to implement the nodemon hack with a Phoenix app... wish me luck.

**Comment by bebraw** [comment]
@owenstrevor Webpack doesn't come with a cli as it was separated from the core. That said, you could be right in that it's a core feature (esp. watchpack) and likely it requires core level tweaks in webpack itself (reactive config). It could be a potentially big change. That's why the external hacks (i.e. nodemon) as they don't have to change webpack itself fundamentally.

**Comment by owenstrevor** [comment]
Thanks for the quick reply @bebraw.

I totally understand what you are saying, and how it could be a potentially big change. My confusion is more around how the request got moved around from one place to another, to an absurd degree.

Took me a little while but I got it nodemon working and it does the job well. Thanks again.
