### ISSUE TITLE
How to config multiple publicPath for my multiple `CDN` and `server domain`?

### ISSUE THREAD

**Issue by mrdulin** [webpack/webpack#3155]
I put my `bundle` file and `index.html` to `www.domain1.com`

so, when NODE_ENV is `production`, I set publicPath to `www.domain1.com`

But, my images put to a third-party site. `www.domain2.com`

when NODE_ENV is  `development`, I put these images to my local directory and use them by `require(relativePath)`.

How  to config this case?

**Comment by Kovensky** [comment]
Not quite sure what you are trying to do, but the answer probably involves setting `__webpack_public_path__` inside the bundled code.

**Comment by mrdulin** [comment]
@Kovensky  I want my images prefix-path, replace with `www.domain2.com` in production.

In development, I use them by `require('../../images/avatar.png')`. But In production the relative path will be replace with `publicPath`. But my publicPath is `www.domain1.com`, not `www.domain2.com`.
 
Sorry for my English is not good.

**Comment by jzzj** [comment]
I guess you would want to use cdn in production.  
I've done this, see [boilerplate](https://github.com/jzzj/boilerplate) and try on it.

**Comment by Wesitos** [comment]
I think that the question is: How to use different a publicPath for some files? (Ie. Request the images to images.mydomain.com and the rest of files from my domain.com).

**Comment by mrdulin** [comment]
@Wesitos yeah. thanks. that's what i want.
