### ISSUE TITLE
Better error message when rule fails normalization

### ISSUE THREAD

**Issue by BrainCrumbz** [webpack/webpack#3156]
**I'm submitting a feature request**

A `module\loaders` rule has an `exclude` array property. One of array items is (by mistake) `undefined`, instead of being an actual string with a path. The error shown in console does not make it easy to figure out what was wrong.
BTW me/our team would be available to prepare a PR, at least one local to this area. I noticed that error message for this case improved since beta.22, so maybe there's a bigger effort going on with error messages that we're not aware of.

**Webpack version:**
2.1.0-beta.25

**Please tell us about your environment:**
Windows 10

**Current behavior:**

Webpack throws an error, so in console one sees:

> Error: Expected condition but got falsy value
>     at Function.normalizeCondition (<myproj>\node_modules\webpack\lib\RuleSet.js:236:9)
>     ... and so on with stacktrace, with several recursions into normalizeCondition

**Expected/desired behavior:**
- **What is the expected behavior?**

Console could show more context, e.g.:

> Error: Expected condition but got falsy value in {
>   test: ....
>   include: [
>     ...,
>   ],
>   exclude: [
>    ...,
>    undefined,
>    ...
>   ]
> }
>     at Function.normalizeCondition (<myproj>\node_modules\webpack\lib\RuleSet.js:236:9)
>     ... and so on with stacktrace, with several recursions into normalizeCondition
- **What is the motivation / use case for changing the behavior?**

To help identify the offending rule and its wrong property, among the multitude of options set in a config file.
- **Browser:** all 
- **Language:** all

**Comment by BrainCrumbz** [comment]
@bebraw: trying to contribute, is it ok to start off of master branch, or what? Thanks!

**Comment by bebraw** [comment]
@BrainCrumbz Cool. PR against `master`. [More info](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md).

**Comment by BrainCrumbz** [comment]
Yep, couldn't find that info in CONTRIBUTING! Thanks

**Comment by BrainCrumbz** [comment]
OT, not wanting to derail the issue, but starting on a Windows 10 x64 machine with a clean clone, setting up etc., running tests returns:

>   6070 passing (8m)
  32 pending
  1 failing

>  1) ConfigTestCases extract-text issue-14 should compile:
     Error: global leak detected: addresses
      at Runner.checkGlobals (D:\WS\JS\webpack\node_modules\mocha\lib\runner.js:210:21)
      at Runner.<anonymous> (D:\WS\JS\webpack\node_modules\mocha\lib\runner.js:73:10)
      at emitOne (events.js:101:20)
      at Runner.emit (events.js:188:7)
      at D:\WS\JS\webpack\node_modules\mocha\lib\runner.js:557:14
      at done (D:\WS\JS\webpack\node_modules\mocha\lib\runnable.js:287:5)
      at D:\WS\JS\webpack\node_modules\mocha\lib\runnable.js:360:7
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)

which we'll ignore for the purposes of this issue.

**Comment by bebraw** [comment]
@BrainCrumbz Can you open a separate issue on that so someone with a windows box can take a better look?

**Comment by SpaceK33z** [comment]
Closing since PR #3175 was merged.
