### ISSUE TITLE
Loading a library chunk used by multiple async chunks in parallel

### ISSUE THREAD

**Issue by hkrutzer** [webpack/webpack#3157]
**I'm submitting a feature request**

**Webpack version:**
1.10.x

**Expected/desired behavior:**
I have two pages (P1 and P2), loading two different SPA's. Both use the same library. A user may or may not load both pages, so for caching purposes I'd like to load the chunk for P1 in parallel with a separate chunk (L) containing the library, then if/when the user goes to P2,  L is cached and only the P1 chunk needs to be loaded.

I do not know what page I am on (P1 or P2) before executing Javascript (meaning I cannot add L as a scripttag from a normal commons chunk (I might actually be on P3 and not need L at all)).

So:
- I visit P1, P1 chunk and L are loaded in parallel (and executed when both are loaded).
- I visit P2, P2 chunk is loaded, L is already in cache.

I am unsure if this is possible right now, and if it is, I have not seen it described anywhere.

**Comment by sokra** [comment]
CommonsChunkPlugin in async mode

**Comment by hkrutzer** [comment]
I want to explicitly configure which modules are inserted into the commons chunk, is that possible with CommonsChunkPlugin?
