### ISSUE TITLE
TypeError when `file-loader` is used yet not installed 

### ISSUE THREAD

**Issue by SteveVanOpstal** [webpack/webpack#3162]
**I'm submitting a bug report**

**Webpack version:**
2.1.0-beta.25

**Please tell us about your environment:**
Windows 10

**Current behavior:**
When using `file-loader` while it is not installed, the following error occurs in Webpack:

> Compilation.js:197
> _this.errors.push(err);
>         ^
> TypeError: Cannot read property 'errors' of null

Relevant part of my configuration:

```
...
  module: {
    rules: [
      {test: /\.svg$/, loaders: ['file-loader', 'some-other-loader']}
    ]
  },
...
```

**Expected/desired behavior:**
The error should not occur.
1. ensure `file-loader` is not installed
2. run a test configuration which uses the `file-loader`
- **Browser:** all
- **Language:** TypeScript 2.0.3

**Comment by Kovensky** [comment]
Your `loaders` config looks invalid -- `loaders` expects an array, not a string.

Though I'm not sure if the rule parsing changes in beta.23 changed that; maybe they're both aliases to `use`, and `use` can take either...

**Comment by SteveVanOpstal** [comment]
Indeed, the error occurred in `loaders` though. I've updated my original comment so it more accurately represents the issue.

I'm not sure if this also occurs in `loader`, but it breaks webpack at quite a generic area so I suppose it will.
