### ISSUE TITLE
Error: EMFILE: too many open files, open..

### ISSUE THREAD

**Issue by McPo** [webpack/webpack#3164]
**I'm submitting a bug report**

**Webpack version:**
1.10.x/2.x

**Please tell us about your environment:**
OSX 10.x / Linux / Windows 10

**Current behavior:**
Obtaining too many open files when using the copy-webpack-plugin. 

**Expected/desired behavior:**
Not to reach the limit of open files and therefore have the build succeed.

@tallaxes suggested a fix which lies within Compiler.js. https://github.com/kevlened/copy-webpack-plugin/issues/59

```
require("async").forEach(Object.keys(compilation.assets), function(file, callback) {
```

to

```
require("async").forEachLimit(Object.keys(compilation.assets), 2000,
  require("async").ensureAsync(function(file, callback) {
```

One issue with this fix is the number is different per machine and depending on what else is running on the machine. One possible solution is to use an environment variable and fall back to a default value anyway.

```
require("async").forEachLimit(Object.keys(compilation.assets), process.env.WEBPACK_FILE_LIMIT || 100,
  require("async").ensureAsync(function(file, callback) {
```

There has also been mentions about using graceful-fs. However I had no luck when monkey patching it. This was the only thing that solved the issue for me. https://github.com/webpack/webpack/issues/250
- **Browser:** 
  Electron

**Comment by McPo** [comment]
Ive created a PR. for those suffering from this issue you can use it right away by setting your package.json to 

> "webpack": "McPo/webpack#1.13.2-file-limit"

Ive limited to 1000, but perhaps 500 is more reasonable.
You should be able to set it to a user defined value using the environment variable WEBPACK_FILE_LIMIT

**Comment by MagicDuck** [comment]
We're encountering the exact same issue on our side.... I spent like a day messing with graceful-fs and happypack. In the end I had to disable happypack, but the error still appears, albeit less frequently than with happypack.

**Comment by dmichon-msft** [comment]
This still repros any time a loader adds a large number of assets to the compilation. The parallel modules work fine, but the asset emitting step crashes due to too many open file handles.
