### ISSUE TITLE
Webpack should set the __esModules flag to true when handling ES6 modules

### ISSUE THREAD

**Issue by k15a** [webpack/webpack#3168]
**I'm submitting a bug report**

**Webpack version:**
2.1.0-beta.25

**Please tell us about your environment:**
OSX 10.12 (16A323)

**Current behavior:**
When I use webpack with babel and the the `babel-plugin-transform-es2015-modules-commonjs` transform I can't import a ES6 module anymore which is not transpiled by babel.

Babel handles the module like an CommonJS module because webpack doesn't set the `__esModules` flag to `true`.

**Expected/desired behavior:**
I should be able to import the module.
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.** 
  https://github.com/k15a/webpack2-babel-bug
- **What is the motivation / use case for changing the behavior?**
  https://github.com/styled-components/styled-components/issues/115
- **Language:** 
  ES6/7

**Comment by sokra** [comment]
I agree that this could be considered as bug. But why trying to do this. Just disable the babel-commonjs plugin as webpack can handle the imports better.

**Comment by sokra** [comment]
Note to myself: add `__esModule` when importing an harmony module via CommonJs.

**Comment by zhaoshengjun** [comment]
The reason is Webpack and Babel handle the module differently. 

You can use either for **all** your files, but cannot mix them together.

Hi @sokra , is this worth to fix?

**Comment by sokra** [comment]
We only need to add `__esModule` to harmony files when they are referenced from a non-harmony (babel files look like CommonJS from webpacks perspective).

**Comment by zhaoshengjun** [comment]
OK. I will send a PR to fix this soon.

**Comment by zhaoshengjun** [comment]
I created a plugin for this(temporary solution).  [npm link](https://www.npmjs.com/package/harmonymodule-webpack-plugin)
