### ISSUE TITLE
Feature request: 1.13.2

### ISSUE THREAD

**Issue by colepatrickturner** [webpack/webpack#3169]
Could not figure out why webpack was not stopping after build, until I realized I still had `watch: true` in my config.js. I think it would be nice to know if Webpack is running in watch mode, regardless if it was specified by flag or config.

Maybe the following?

"Webpack is now watching entry for changes..."

**Comment by sokra** [comment]
https://github.com/webpack/webpack/blob/master/bin/webpack.js#L333
