### ISSUE TITLE
Webpack process doesn't exit (not in watch mode)

### ISSUE THREAD

**Issue by klinki** [webpack/webpack#3170]
**I'm submitting a bug report**
**Webpack version:**
2.1.0-beta.25
Linux - Fedora 24

**Current behavior:**
Webpack process doesn't exit when packing is completed. It doesn't even show any error. Please note webpack <s>is not</s> should not be running in watch mode. It is not executed in watch mode and it doesn't do anything when files get changed. 

**Expected/desired behavior:**
Webpack process should exit either with success status code or error code in case of error.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.** 
Webpack configuration: https://gist.github.com/klinki/e1d3078dd0b5c70bfc56360ddb567dac
* **Language:** TypeScript 2.0.2

**Comment by sokra** [comment]
probably related to webpack-dashboard...

**Comment by SpaceK33z** [comment]
Found the issue on webpack-dashboard: https://github.com/FormidableLabs/webpack-dashboard/issues/96. As said above, it's not an issue in webpack v2.
