### ISSUE TITLE
Change naming convention

### ISSUE THREAD

**Issue by monolithed** [webpack/webpack#3171]
Due to the current name system is not specified  I propose to use the following rules:

`webpack-<name>-plugin`
`webpack-<name>-loader`
`webpack-<name>-config`

### Motivation

`css-loader` what does it mean? `loader` is not reserved word for webpack packages. It's a common postfix for many projects. So, it would be nice to set a naming convention.

### Before

``` js
{
        "webpack": "^1.13.2",
        "webpack-bundle-size-analyzer": "2.2.0",
        "webpack-visualizer-plugin": "0.1.5",
        "clean-webpack-plugin": "^0.1.13",
        "json-loader": "0.5.4",
        "postcss-loader": "^0.9.1"
}
```

### After

``` js
{
        "webpack": "^1.13.2",
        "webpack-bundle-size-analyzer-plugin": "2.2.0",
        "webpack-visualizer-plugin": "0.1.5",
        "webpack-clean-plugin": "^0.1.13",
        "webpack-json-loader": "0.5.4",
        "webpack-postcss-loader": "^0.9.1"
}
```

**Comment by wtgtybhertgeghgtwtg** [comment]
Maybe for loaders, but I'm not sure if you could enforce this for plugins.

**Comment by TheLarkInn** [comment]
I actually really like adding a naming convention to the loaders, but I do still prefer the naming to be after the descriptor information. IE: `json-webpack-loader`

**Comment by monolithed** [comment]
@TheLarkInn, why? it would be nice if you can explain your position

**Comment by TheLarkInn** [comment]
Personally it's let's infra changes for 3rd party plugin authors who already follow (for the most part) `x-webpack-plugin`,

**Comment by jhnns** [comment]
This would definitely be nice, but I don't think that it's worth the effort.

**Comment by fhelwanger** [comment]
I like `webpack-` being the prefix for all webpack related packages, because this way the `package.json` file can be organized more easily and it's consistent with other commonly used devDependencies, like `babel` and `eslint`.

But I get it that it can be hard to make all 3rd party plugins to follow that.

**Comment by surfaceowl** [comment]
+1 for @[monolithed](/monolithed)'s suggestion!  

I prefer `webpack-` prefix and grouping as well -- much easier to see all the components at once, and saved devs from hunting through a long list of packages.  The **before** example above has **only** webpack related entries and it is messy -- the effect is even worse in projects with many dependencies.

Also agree with @[fhelwanger](/fhelwanger) -- it would be difficult to _make_ all 3rd party plugins follow a standard.  However, if a standard like this were stated as the preferred by webpack and implemented for core packages - it would create a pattern for people to follow and they may be more likely to adopt it voluntarily.  Today, there is no guidance, so naming patterns are all over the place.

**Comment by surfaceowl** [comment]
@sokra -- what is your perspective on this?  Would you support stating a preference for this naming convention?

**Comment by alexander-akait** [comment]
@surfaceowl In fact, this is a good idea, but for historical reasons it was difficult to implement, this will require deprecate a lot of loaders/plugins and will negatively affect the search for frequent problems, I think there will be more minuses now than pluses, so I preferred keep as it

**Comment by monolithed** [comment]
@alexander-akait,  this problem is pretty much solved by using scopes and prefixes. For example:

* `ts-loader` -> `webpack-ts-loader` or `@TypeStrong/webpack-ts-loader`
* `json-loader` -> `@webpack/json-loader`
* `less-loader` -> `@webpack-contrib/less-loader` 
  
Also it's possible to notify all package owners to mark old packages as deprecated using the `npm deprecate` command.

**Comment by sokra** [comment]
> Also it's possible to notify all package owners to mark old packages as deprecated using the `npm deprecate` command.

Best way to make all users angry...

I don't see much benefit in changing the naming convention...

**Comment by monolithed** [comment]
> Best way to make all users angry...

These changes should have been made 4 years ago. To hold water now, we need to wait for the moment of major breaking change.

**Comment by alexander-akait** [comment]
@monolithed I am afraid that this could create certain problems for many developers, so let's leave everything as it is, perhaps in the future we will return to this question, especial after HTML and CSS will be part of core (less loader need to be migrate and it will be easy for us)

**Comment by goerwin** [comment]
This has been always my issue with webpack. Good luck finding all the webpack related plugins/loaders when you have tens of devDependencies. Most of the loaders omit webpack in their names so it is a nightmare to find them

**Comment by alexander-akait** [comment]
@goerwin 

> Most of the loaders omit webpack in their names so it is a nightmare to find them

Can you provide list?
