### ISSUE TITLE
bitHound instead of VersionEye

### ISSUE THREAD

**Issue by shehi** [webpack/webpack#3177]
It's just a small heads-up: I recently started using bitHound and dropped VersionEye support on my packages. bitHound not only tracks versions of deps, but also provides linting related, security related insights about the project. Worth to take a look. Have a good day and thanks for Webpack!

**Comment by bebraw** [comment]
We've been experimenting with bitHound at **webpack-contrib**. The results have been a little mixed (just doesn't work sometimes). Thanks for the heads up, though.
