### ISSUE TITLE
Inline Loader Definitions

### ISSUE THREAD

**Issue by ChristopherBiscardi** [webpack/webpack#3178]
**I'm submitting a feature request**

**Current behavior:**
loaders can only be specified by string ala:

``` javascript
{ loader: 'babel', ... }
```

**Expected/desired behavior:**
- **What is the expected behavior?**

loaders can be specified inline with a name, which can then operate the same as any other loader:

``` javascript
{
  loader: function something(content, map) {
    return 'module.exports = {}';
  }
}
```

a file could then require as normal or use the loader in an entrypoint as usual:

``` javascript
const obj = require('something!');
...
{ entry: 'something!', ...}
```
- **What is the motivation / use case for changing the behavior?**

I'm extracting a package from one of my libs that renders a GraphQL schema/database from a folder of files. I would like to limit the effects of the environment on the webpack config that is used to load the files. Currently my config looks something like this, which enables a sidecar `database-loader` file to be shipped with the package. (I'm using the node.js webpack API)

``` javascript
{
  entry: 'database-loader!',
  resolveLoader: {
    modulesDirectories: [
      'node_modules',
      resolve(__dirname, '../loaders')
    ]
 },
}
```

Ideally, I would be able to specify loaders in such a way that does not require filesystem access, thus removing a potential failure mode from not being able to find the `database-loader` file.
- **Browser:** all
- **Language:** all

**Comment by TheLarkInn** [comment]
This would be nice!! Although I see the benefit of it for helping create loaders,

**Comment by ChristopherBiscardi** [comment]
@TheLarkInn Did your comment get chopped off? 😄

**Comment by wtgtybhertgeghgtwtg** [comment]
This would make loaders, or at least getting loaders, synchronous, wouldn't it?

**Comment by hh9527** [comment]
I think the module.rules should stay serialuzable. however
 create loaders on the fly is very useful. so my suggestion is create a new section in config to register these file-less-loaders. 

```js
module.exports = {
  module: {
    rules: [
      { test: /\.foo$/, loader: 'foo-loader' }
    ]
  },
  buildInLoaders: {
    foo: require("./my-loarders").fooLoader,
  }
}
```
