### ISSUE TITLE
Consider renaming NoErrorsPlugin to something clearer like NoEmitOnErrorsPlugin

### ISSUE THREAD

**Issue by niieani** [webpack/webpack#3179]
**I'm submitting a feature request**

The name of the `NoErrorsPlugin` is quite confusing. By name alone, I thought `NoErrorsPlugin` is a plugin which _silences_ the display of any errors (no errors = don't show errors), while in fact, it's job is to [skip the asset emit](https://webpack.github.io/docs/list-of-plugins.html#noerrorsplugin) in case any errors are detected during the build stage.

I suggest `NoEmitOnErrorsPlugin` or `SkipEmittingAssetsOnErrorsPlugin`, but if you have better ideas, go for it.

**Comment by TheLarkInn** [comment]
I would accept a PR for this but it would need to be a graceful degradation:

1. Add new Plugin with new name (identical functionality)

2. When attempted use for old plugin need to provide deprecation warning explaining that the new named plugin should be used.

3. Update tests to run against both plugins and then extra cases to verify deprecation warnings are emitted.

**Comment by niieani** [comment]
I might do the PR during a slow afternoon. Which new name should we settle for?

**Comment by TheLarkInn** [comment]
NoEmitOnErrorsPlugin sounds good to me.

**Comment by akre54** [comment]
How about SuppressErrorsPlugin?

**Comment by TheLarkInn** [comment]
Well the plugins purpose is to not emit files if errors exist.

**Comment by TheLarkInn** [comment]
But the examples above are we we want to change the name because it can be confusing.

**Comment by TheLarkInn** [comment]
Fixed by #3570 Thanks @elodszopos I didn't even know this got tackled!

**Comment by whitelynx** [comment]
`NoEmitOnErrorsPlugin` still sounds like something that should prevent it from emitting an `error` event when an error occurs... I personally think `SkipEmittingAssetsOnErrorsPlugin` would have been much less confusing.
