### ISSUE TITLE
Webpack 2 & CommonsChunkPlugin chunks filenames

### ISSUE THREAD

**Issue by Alex-Sokolov** [webpack/webpack#3182]
**I'm submitting a bug report**

**Webpack version:**
2.1.0-beta.25

**Please tell us about your environment:**
Windows 8.1

**Current behavior:**
In `webpack.config.js` set filename for CommonsChunkPlugin:
```js
new webpack.optimize.CommonsChunkPlugin({
	filename: 'commons.[chunkhash:8].js',
	children: true,
	async: true,
	minChunks: 2
})
```
After this I found option to set chunk names globally:
```js
output: {
	path: path.join(__dirname, 'public', 'frontend'),
	publicPath: '/frontend/',
	filename: '[name].js',
	chunkFilename: 'chunk.[id].[chunkhash:8].js'
},
```
Webpack build ok. Commons chunk have its own name, others contains id:
![common_chunks_webpack](https://cloud.githubusercontent.com/assets/4497128/19676020/869dd3ae-9a9a-11e6-9ae9-d600af2fb77a.png)

But if open page, there is console error
![common_chunks_devtool](https://cloud.githubusercontent.com/assets/4497128/19676022/89718616-9a9a-11e6-8682-a3a45b662989.png)

Looks like webpack trying to search file which contains id `0`, and not file `commons` from CommonsChunkPlugin settings

**Expected/desired behavior:**
Warning\error when validating webpack config that output section has higher priority or use correct filename from CommonsChunkPlugin options

**Comment by sokra** [comment]
Settings `filename` for `CommonsChunkPlugin` with `async` is not supported.
