### ISSUE TITLE
Add define for used/unused exports

### ISSUE THREAD

**Issue by sokra** [webpack/webpack#3183]
**I'm submitting a feature request**

**Webpack version:**
2.x

**Expected/desired behavior:**
webpack should support some special syntax to check if exports are used or not.

Some syntax ideas:

``` js
export var foo = 1;
if(typeof foo_EXPORT !== "unused") {
  // export foo is used
}
```

or

``` js
export var foo = 1;
if(typeof __EXPORTS__ !== "object" || __EXPORTS__.foo) {
  // export foo is used
}
```

or

``` js
export var foo = 1;
if(typeof foo_EXPORT_USED !== "boolean" || foo_EXPORT_USED) {
  // export foo is used
}
```
- **What is the motivation / use case for changing the behavior?**

loaders should be able to generate code that is removed when exports are unused.

Example: the css-loader should be able to generate tree-shakable CSS Modules, where styles are removed when the class name is not used.

**Comment by jhnns** [comment]
In your example: Are the `export` and `if` statement within the same module? If yes, why aren't these exports removed when the export is not used anywhere else? Maybe we need to improve the "usage detection" that is applied during tree-shaking. I would definitely try to avoid these webpack-specific syntax extensions.

If we need these extensions at all costs, I would definitely not do the first one as it introduces a completely new behavior of the `typeof` operator (I know, this will never be executed, but it's still not good to extend the language that way).

What about:

```javascript
if ("foo" in __exports) { ... }
```

`__exports` uses the same naming convention as `__filename` and `__dirname` in CommonJS. Does anyone know if these reflection use-cases are provided by ES2015 modules? Is there a proposal?

**Comment by sokra** [comment]
Here is an example of an module using it:

``` js
// expoert the class names
export const button = "button_6d6e7a";
export const inner = "inner_10ab42";

// export the css code
export default "body { background: red; }" +
  (typeof button_EXPORT !== "unused" ? ".button_6d6e7a { color: green; }" : "") +
  (typeof inner_EXPORT !== "unused" ? ".inner_10ab42 { background: blue; }": "");
```

---

I like the typeof operator because it doesn't throw a reference error when the identifier is not defined. The code should not crash when these specific stuff is not supported. i. e. `typeof button_EXPORT` returns `"undefined"` when this syntax is not supported.

``` js
export var foo = 1;
if(typeof __used_exports !== "object" || "foo" in __used_exports) {
  // export foo is used
}
```

or


``` js
export var foo = 1;
if(typeof __exports !== "object" || __exports.foo) {
  // export foo is used
}
// __exports is { foo: true, bar: false } when foo is used and bar not
```

**Comment by TheLarkInn** [comment]
//cc @mxstbr @geelen

Potentially relevant to you both. Wanted input, insight, etc.

**Comment by Kovensky** [comment]
How about a `__webpack_used__('exportName')` meta-function?
