### ISSUE TITLE
why does tree shaking must work on one chunk?

### ISSUE THREAD

**Issue by zhancheng** [webpack/webpack#3184]
## src/main.js

``` javascript

function getUserInfo() {
    console.log('I,m smith')
}

function getGps() {
    console.log('116.222,90.233')
}

export {
    getUserInfo,
    getGps
}
```
## src/index.js

``` javascript
import {
    getGps
}
from 'main.js'

getGps();
```
## webpack.config.js

``` javascript
module.exports = {
     entry: {
           index: 'src/index.js',
           main: 'src/main.js'
     },
     plugins: [{
            new HtmlWebpackPlugin({
                  template: 'src/index',
                  filename:  'index.html',
                  chunks: ['index','main']
           })
     }]
})
```

why I  split index & main with two chunks , the tree shaking does not work, when I put them in one only entry, it works. 

it takes me much time to find the problem, the webpack docs does not reflect it.

**Comment by davyrolink** [comment]
I experience the same behaviour, also someone on stackoverflow with the same issue http://stackoverflow.com/questions/38053664/webpack-2-is-it-bad-practice-to-use-vendors-bundle

**Comment by zhancheng** [comment]
@davyrolink Thanks! guy!
