### ISSUE TITLE
[2.x]Webpack dev server respond 404 if set entry name or output.fileName with prefix ‘/’.

### ISSUE THREAD

**Issue by ibufu** [webpack/webpack#3189]
**I'm submitting a bug report**

**Webpack version:**
2.1.0-beta.25
webpack-dev-server@2.1.0-beta.9
**Please tell us about your environment:**
Linux 

**Current behavior:**
If set entry name or output.fileName with prefix ‘/’，the entry file will be responded as 404.

**Expected/desired behavior:**
- **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.** 

``` js
const webpack = require('webpack');
const path = require('path');

module.exports = {
    entry: {
        '/app': './src/index.js',
    },

    output: {
        path: path.resolve(__dirname, "dist"),
        filename: '[name].js'
    },

    devServer: {
        historyApiFallback: true,
        port: 3000,
        watchOptions: {
            aggregateTimeout: 300,
            poll: 1000
        }
    }
};
```

OR

``` js
output: {
        path: path.resolve(__dirname, "dist"),
        filename: '/[name].js'
 },
```
- **What is the expected behavior?**
- **What is the motivation / use case for changing the behavior?**
- **Browser:** all
- **Language:** all

**Comment by SpaceK33z** [comment]
I created https://github.com/webpack/webpack-dev-middleware/issues/145 for this, since it is *probably* a bug in webpack-dev-middleware. We can leave this open till I know for sure though.
