### ISSUE TITLE
cannot use nodejs for backend server with webpack-dev-server

### ISSUE THREAD

**Issue by abbymrs** [webpack/webpack#3192]
i use webpack-dev-server to config backend server, but failed, below is my devSever config and app.js(nodejs);

> webpack-dev-server:

```
....
 devServer: {
    	port: 5000,
    	host: 'localhost',
        historyApiFallback: true,
        watchOptions: {
            aggregateTimeout: 300,
            poll: 1000
        },
        outputPath: '/',
        proxy: {
            '/api/*': 'http://localhost:8000'
        }
    },
....

```

> app.js

```
const express = require('express');
const bodyParser = require('body-parser');
const fs = require('fs');
const utils = require('utility');

var app = express();

app.use(bodyParser.json());
app.use(bodyParser.urlencoded({
    extended: true
}));
app.use(express.static('./public'));
app.use(express.static('./node_modules'));

var PORT = process.env.PORT || 8000;

app.listen(PORT, () => {
    console.log('server running on port: ' + PORT);
});
app.get('/md5', (req, res) => {
    let queryKey = req.query.name;
    let md5 = utils.md5(queryKey);
    console.log(utils.logDate());
    utils.setImmediate(() => console.log('hello'));

    res.send(md5).end();
});
app.get('api/getInfo', (req, res) => {
    var obj = fs.readFileSync('./public/js/data.json');
    res.send(obj).end();
});
app.get('api/query', (req, res) => {
    console.log(req.query);
    res.send(req.query).end();
});

app.post('api/uploadImg', (req, res) => {
    console.log('received');
    res.end();
});
app.get('api/process', (req, res) => {
    console.log(process);
    res.send(process.env).end();
});
```

when i click a button to request datas from node,  the request should be from `http://localhost:8000` , but i got `http://localhost:5000
`
Appreciated for any helps~

**Comment by imvetri** [comment]
Can you try at port 5000. It may work

**Comment by imvetri** [comment]
At http://localhost:5000, since the web pack is listening to 5000 as per the config the site will be available at 5000. Not 8000

**Comment by abbymrs** [comment]
@imvetri thanks for anwser.
But what i need is the port from node, because i need to use webpack for listening static files, and need node port for providing datas as backend.
angular 2.0.0 works the same config, so wonder why it cannot work in angular 1.5, really confused....

**Comment by imvetri** [comment]
Could you share any repo where I could reproduce the issue?

**Comment by abbymrs** [comment]
NG2 project link: https://github.com/abbymrs/ng2-webpack-nodejs
NG1 link: https://github.com/abbymrs/ng1-webpack

**Comment by abbymrs** [comment]
Hi @imvetri ,
I know what's the problem that leads to backend server not work, it was my mistake that forgot to add '/api/' in my front end codes when make requests from backend.
Thanks anyway.

**Comment by imvetri** [comment]
Cool.. Thanks :)
