### ISSUE TITLE
add "chunkName" to opts object callback of NormalModuleReplacementPlugin

### ISSUE THREAD

**Issue by kamekazemaster** [webpack/webpack#3196]
**I'm submitting a feature request**
- **What is the motivation / use case for changing the behavior?**

I am building multiple bundles with the same entry point varying certain files in the bundle, replacing them with the `NormalModuleReplacementPlugin` based on the desired target platform I am bundling for. In the plugin I am replacing the placeholder `$platform` in the require calls. So based on which target the specific bundle is produced for, the aliases are varying.

There are two different solutions for this problem:
1. choose for each entry point which aliases should be used for `resolve.alias`
2. pass the `chunkName` from the `entry` object as an attribute (or even more info?) down to the `opts` object passed to the callback of the `NormalModuleReplacementPlugin`

One of these (or both :) ) would be very helpful to be more dynamic in aliasing/replacing require paths.

**Comment by kamekazemaster** [comment]
As I need this feature (the second one) in order to integrate webpack into my project, I want to monkey patch it in a fork. For now I would be happy to just modify the NormalModuleReplacementPlugin.js to pass information of the `compiler`(?) object down to the `opts` object. 
@sokra Could you give me a hint where to look for the information which chunk webpack is building when calling the NormalModuleReplacementPlugin?

@bebraw I would love to discuss this feature(s). Maybe I should split my feature request into two issues? As I read my post again, it seems like I am suggesting two different features for webpack. I think the first one (different alias objects for different entry point) is a feature potentially affecting a greater amount of users. The second one is very specific and maybe only "nice to have".

**Comment by bebraw** [comment]
@kamekazemaster Splitting into two issues sounds reasonable.
