### ISSUE TITLE
Drop resolve.enforceModuleExtension and resolve.moduleExtensions from schema

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack#3197]
**I'm submitting a bug report**

**Webpack version:**
2.x

**Current behavior:**

The schema accepts `resolve.enforceModuleExtension` and `resolve.moduleExtensions` although those shouldn't work anymore (`-loader` extension is forced).

**Expected/desired behavior:**

Validation should fail if either is provided.

**Comment by sokra** [comment]
the `-loader` change only changes the default value. You can still override it.
