### ISSUE TITLE
Developer UX, codebase callback hell mitigation, mutability - discussion

### ISSUE THREAD

**Issue by niieani** [webpack/webpack#3213]
**I'm submitting a feature request**

I'm currently writing a couple of loaders and plugins for Webpack. Since the code lacks any comments and the developer docs only cover the basics (if that), I find myself browsing the codebase and stepping through various parts. @TheLarkInn's developer kit helps, but it's a really tedious and a mind-boggling job. 

Two main reasons why understanding the code is difficult:
1. mutability - internal plugins modify the objects all the time so without stepping-through/tracing every single Tapable plugin/callback, you have no any idea about the contents of a given object at any single point in the code; there are no "code-contracts" so to speak -- anything goes.
2. callback hell. The Tapable plugin system is both a blessing and a curse, but its main problem is you can never see the dataflow. I'm just constantly thinking in the lines of: That goes... where and when, invoked by what... oh, invoked what next?

I'd like to propose a gradual rewrite of all the callback code - either to Promises or a stream library (like RxJS). A stream/observable library might be better suited to tapable's multi-output callback chains, but given that the Promise-enhancing await-async proposal is stage-3 and Node 7 already shipped support for it (behind a flag), either option would make understanding everything so much easier. By _gradual rewrite_, I really mean _gradual_ - one method at a time. Since it's all callbacks, the code could be in a mixed state for some time, until all of it is rewritten.

Mutability / lack of contracts is a harder problem to tackle. I guess a good start would be either to stop passing/binding `this` around, or at least ensure `this` isn't modified outside of the method, and instead have those callbacks actually return the pure changes that need to be applied to the original object. So the actual changes to `this` would be done AFTER the callback, in the method that called it using something like `Object.assign`. In other words, have a rule that **any tapable plugin can only mutate its own objects, while the callback-caller handles the mutation of _its_ own objects based on the values returned from the callback**.

This way it will be much easier to debug and understand what modifications were made by which plugin and at which point in the code. You'd set a breakpoint in the "higher-up" method that invokes the callbacks and simply see what it returns, instead of stepping through ALL the callbacks (which can get really tedious, like when debugging `enhanced-resolve` where the number of callbacks for a single resolve can be 30 or more).

I'm not saying these are the only options, or that this is exactly what has to be done. Just wanted to start a discussion regarding the Developer Experience. 

I think good, self-documenting code is much better than a good documentation. Mainly because when you've got clear code, anybody can write great docs for it! I often see Sean trying to motivate people to write Webpack docs, and I'm always thinking like... I'd love to help out, but can't dig into the more advanced concepts, because the big-picture of the code is just so damn hard to read.

But please treat the above simply as some of my thoughts after digging through the codebase. In a recent Medium post I saw a TypeScript rewrite is planned - I guess that will help with the contract part too.

**Comment by bebraw** [comment]
See #824 for a related issue.

**Comment by TheLarkInn** [comment]
Another change we are planning on making is reorganizing the file structure for the repo. And exporting all plugins in core instead of a select few.

**Comment by bebraw** [comment]
Reorganizing would be tricky as sometimes 3rd party points below `webpack/lib`. I guess you can't make an omelette without breaking an egg, though, so we had better do that in the next major bump.

I definitely agree with your concerns. Pushing code to an easier to understand form would be a great win.

I'll close this in favor of #824 so we have the discussion in one place. So feel free to pop in there.
