### ISSUE TITLE
Using Webpack with Grunt, Testem and Mocha?

### ISSUE THREAD

**Issue by KingScooty** [webpack/webpack#322]
I've got Webpack setup nicely with Grunt so it watches for JS changes, and compiles a new bundle before reloading the page.

But i'm now confused how to write tests for the individual JS files. I want to use Testem and Mocha, but i can't figure out how to load the bundled/unbundled JS files in and test them in the browser spec runner.

Is there an easy way to get this setup?

**Comment by bebraw** [comment]
@KingScooty Any luck with this?
