### ISSUE TITLE
What arguments async pitching loader should call the callback with? 

### ISSUE THREAD

**Issue by mohsen1** [webpack/webpack#3220]
Following from https://github.com/olegstepura/typed-css-modules-loader/pull/8

We're trying to make a loader that only produces side effects and does nothing else. It generates some `.d.ts` that later in process is used by TypeScript compiler. 

I'm trying to use a pitching loader for this:

```js
module.exports.pitch = function(fullpath) {
  this.cacheable && this.cacheable();
  debugger;
  var parts = fullpath.split('!');
  var name = parts[parts.length - 1];
  var callback = this.async();

  var creator = new DtsCreator();
  creator.create(name).then((content) => {
        content.writeFile().then(() => {
            callback(null, undefined); // what this callback expect?
        });
  });
};
```

I'm not sure how to call the callback.

**Comment by TheLarkInn** [comment]
@sokra do you think you can answer this. My knowledge is limited with pitching loaders.

**Comment by mohsen1** [comment]
I kind of figured out that the arguments don't matter as long as first argument (error) is falsy

But I'm still struggling to make this loader work as we expect. Please read [this comment](https://github.com/olegstepura/typed-css-modules-loader/pull/8#issuecomment-257966597) for more details.

**Comment by mohsen1** [comment]
@sokra do you have any recommendations for the linked loader?

We don't know how to make our pitching loader add new files to memory fs (or real fs) the way that next loaders see them.
