### ISSUE TITLE
Visual Studio 2015 debugging doesn't work after updating from 1.13.2 to 1.13.3

### ISSUE THREAD

**Issue by mmercan** [webpack/webpack#3222]
**I'm submitting a bug report**

**Webpack version:**
1.13.3
**Please tell us about your environment:**
 Windows 10 
Visual Studio 2015 Update 3
Node v7.0.0
Npm v3.10.9

**Current behavior:**
Visual studio debugger opens typescript in "dynamic mode"

**Expected/desired behavior:**
Visual studio debugger opens typescript from the typescript file

* **update package.json to "webpack": "1.13.3" on any project (I tested with dozens) which could be debugged normally.
* ** run webpack to bundle 
* **run asp.net app (I use  ASP.Core) with Visual Studio 2015 Update 3 (latest)
* **dobule click any ts/js from
it was working just fine till I update  "webpack": "1.13.2" to "webpack": "1.13.3"
and it is still working fine when I downgrade to 1.13.2 and bundle.
I haven't change any config or other NPM packages 
I isolated the problem with creating a sample app

webpack.config.js
var path = require('path');
var webpack = require('webpack');
module.exports = {
    debug: true,
    devtool: 'eval-source-map',
    entry: {
        'utils': './src/utils.js',
        'app': './src/app.ts'
    },
    output: {
        path: "./wwwroot/",
        filename: 'dist/[name].bundle.js',
        publicPath: "/"
    },
    resolve: {
        extensions: ['', '.ts', '.js', '.json', '.css', '.scss', '.html']
    },
    module: {
        loaders: [
            {
                test: /\.ts$/,
                loader: 'ts',
            }
        ]
    },
    plugins: [
    ]
};

tsconfig.json
{
  "compilerOptions": {
    "noImplicitAny": false,
    "noEmitOnError": true,
    "removeComments": false,
    "sourceMap": true,
    "target": "es5"
  },
  "exclude": [
    "node_modules",
    "wwwroot"
  ]
}

package.json
{
  "name": "webpack-demo",
  "version": "1.0.0",
  "description": "Webpack demo",
  "main": "app.js",
  "scripts": {
    "start": "webpack-dev-server"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "typescript": "^2.0.6",
    "ts-loader": "^0.9.5",
    "ts-helpers": "^1.1.2",
    "webpack": "1.13.2"
  }
}

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**
updating the webpack version

map file on 1.13.2 (works)
`{"version":3,"sources":["webpack:///webpack/bootstrap 39922733453a6e6596e0?e6dc","webpack:///./src/utils.js"],"names":[],"mappings":";AAAA;AACA;;AAEA;AACA;;AAEA;AACA;AACA;;AAEA;AACA;AACA,uBAAe;AACf;AACA;AACA;;AAEA;AACA;;AAEA;AACA;;AAEA;AACA;AACA;;;AAGA;AACA;;AAEA;AACA;;AAEA;AACA;;AAEA;AACA;;;;;;;;;;ACtCA;AACA","file":"dist/utils.bundle.js","sourcesContent":[" \t// The module cache\n \tvar installedModules = {};\n\n \t// The require function\n \tfunction __webpack_require__(moduleId) {\n\n \t\t// Check if module is in cache\n \t\tif(installedModules[moduleId])\n \t\t\treturn installedModules[moduleId].exports;\n\n \t\t// Create a new module (and put it into the cache)\n \t\tvar module = installedModules[moduleId] = {\n \t\t\texports: {},\n \t\t\tid: moduleId,\n \t\t\tloaded: false\n \t\t};\n\n \t\t// Execute the module function\n \t\tmodules[moduleId].call(module.exports, module, module.exports, __webpack_require__);\n\n \t\t// Flag the module as loaded\n \t\tmodule.loaded = true;\n\n \t\t// Return the exports of the module\n \t\treturn module.exports;\n \t}\n\n\n \t// expose the modules object (__webpack_modules__)\n \t__webpack_require__.m = modules;\n\n \t// expose the module cache\n \t__webpack_require__.c = installedModules;\n\n \t// __webpack_public_path__\n \t__webpack_require__.p = \"/\";\n\n \t// Load entry module and return exports\n \treturn __webpack_require__(0);\n\n\n\n// WEBPACK FOOTER //\n// webpack/bootstrap 39922733453a6e6596e0","// This is global JS provided to all apps.\r\nconsole.log('logging from the utils.js file...');\r\n\r\n\r\n\n\n\n//////////////////\n// WEBPACK FOOTER\n// ./src/utils.js\n// module id = 0\n// module chunks = 1"],"sourceRoot":""}`

map file on 1.13.3  (doesn't work, opens in dynamic mode)
`{"version":3,"sources":["webpack:///webpack/bootstrap 39922733453a6e6596e0?e6dc","webpack:///./src/utils.js"],"names":[],"mappings":";AAAA;AACA;;AAEA;AACA;;AAEA;AACA;AACA;;AAEA;AACA;AACA,uBAAe;AACf;AACA;AACA;;AAEA;AACA;;AAEA;AACA;;AAEA;AACA;AACA;;;AAGA;AACA;;AAEA;AACA;;AAEA;AACA;;AAEA;AACA;;;;;;;;;;ACtCA;AACA","file":"dist/utils.bundle.js","sourcesContent":[" \t// The module cache\n \tvar installedModules = {};\n\n \t// The require function\n \tfunction __webpack_require__(moduleId) {\n\n \t\t// Check if module is in cache\n \t\tif(installedModules[moduleId])\n \t\t\treturn installedModules[moduleId].exports;\n\n \t\t// Create a new module (and put it into the cache)\n \t\tvar module = installedModules[moduleId] = {\n \t\t\texports: {},\n \t\t\tid: moduleId,\n \t\t\tloaded: false\n \t\t};\n\n \t\t// Execute the module function\n \t\tmodules[moduleId].call(module.exports, module, module.exports, __webpack_require__);\n\n \t\t// Flag the module as loaded\n \t\tmodule.loaded = true;\n\n \t\t// Return the exports of the module\n \t\treturn module.exports;\n \t}\n\n\n \t// expose the modules object (__webpack_modules__)\n \t__webpack_require__.m = modules;\n\n \t// expose the module cache\n \t__webpack_require__.c = installedModules;\n\n \t// __webpack_public_path__\n \t__webpack_require__.p = \"/\";\n\n \t// Load entry module and return exports\n \treturn __webpack_require__(0);\n\n\n\n/** WEBPACK FOOTER **\n ** webpack/bootstrap 39922733453a6e6596e0\n **/","// This is global JS provided to all apps.\r\nconsole.log('logging from the utils.js file...');\r\n\r\n\r\n\n\n\n/*****************\n ** WEBPACK FOOTER\n ** ./src/utils.js\n ** module id = 0\n ** module chunks = 1\n **/"],"sourceRoot":""}`
 

only differences I can see are * instead of /
* **Browser:** [all] 
 
* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart | ...]

**Comment by sokra** [comment]
maybe visual studio does something magic with the footer comment...

**Comment by sokra** [comment]
If someone can confirm this, we need to revert the change and fix it in another way.

**Comment by mmercan** [comment]
I tested on a VM I just build, I am getting the same error, till I change the version  to 1.13.2 and run npm install again, is there anybody else can confirm this

**Comment by bebraw** [comment]
Can someone try this against webpack 2?

**Comment by jayars** [comment]
Just tried with 2.2.1 and VS2015 Update 3, and `devtool: "source-map"`.
When putting breakpoints in VS, switches to "dynamic mode".

![image](https://cloud.githubusercontent.com/assets/28939507/26431754/8187a4ae-4129-11e7-82f6-ded36fa62d66.png)

I think this has to do with 
 1. the appended WEBPACK FOOTER,
 1. the `output.devtoolModuleFilenameTemplate` setting.

If I manually modify SourceMapDevToolPlugin.js(:122):
```
sourceMap.sourcesContent = sourceMap.sourcesContent.map((content, i) => sourceMap.sourcesContent = sourceMap.sourcesContent.map((content, i) => `${content}\n\n\n${ModuleFilenameHelpers.createFooter(modules[i], requestShortener)}`);
```
to just

```
sourceMap.sourcesContent = sourceMap.sourcesContent;
```

and set the webpack config: 

```
output: {
    devtoolModuleFilenameTemplate :"[absolute-resource-path]",
}
```

then it fixes the problem.
![image](https://cloud.githubusercontent.com/assets/28939507/26431727/4e941578-4129-11e7-8a8a-05ff0dcccb9c.png)

**Comment by evilebottnawi** [comment]
@mmercan @jayars Problem still exists?

**Comment by mmercan** [comment]
it works with @jayars methods (  devtoolModuleFilenameTemplate :"[absolute-resource-path]",)
I moved to vs 2017

**Comment by evilebottnawi** [comment]
@mmercan Thanks. Feel free to open new issue if you have problem again
