### ISSUE TITLE
Loader compiler initialization step

### ISSUE THREAD

**Issue by oklas** [webpack/webpack#3223]
Consider possibility to add `initialize` export method in loader package.

**Expected/desired behavior:**

Webpack have set of loaders and set of apply configulations (request string) associated with each loader. That sets available after analysis of main configuration file.

Webpack check each loader for existence method `initialize` in exports. Webpack call method `initialize` for each loader configuraton. As soon as possible after set of loaders configurations is avalable.

**Motivation / use case**

Simplify to write configuration file and loader/plugin usage instructions for users. Loader may add plugins into webpack configuration per each loader apply rule.

```js
module.exports = function(source) {
  ...
}
module.exports.initialize = function(compiler) {
  ...
}
```

Loader configuration (request string) may be available at param or as `this.request`. The `initialize` method may be like `apply` method of plugin or some like that.

**Comment by TheLarkInn** [comment]
@sokra Does this align with some of the API changes we want to make for loaders?

**Comment by sokra** [comment]
no.

Loaders shouldn't know about webpack.

You may solve your use case with a plugin/loader hybrid.
