### ISSUE TITLE
paths in resolve.modulesDirectories

### ISSUE THREAD

**Issue by uMaxmaxmaximus** [webpack/webpack#3229]
I have custom modules in project. I want to store them is in this directory, and no other.
I'm ready to spit on optimization, in order to achieve the goal.
How i can set paths in resolve.modulesDirectories?

```coffeescript
resolve:
  modulesDirectories: ['./build/modules','node_modules']
```

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template, or open a new issue.
