### ISSUE TITLE
Issue loading packages with filename similar dirs

### ISSUE THREAD

**Issue by th3fallen** [webpack/webpack#3233]
**I'm submitting a bug report**

**Webpack version:**
1.13.2

**Please tell us about your environment:**
OSX 10.12

**Current behavior:**
attempts to import as file not dir

**Expected/desired behavior:**
see that it's a dir not a file

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.** 

1. setup app/vendor splitting from package.json
2. run `npm i hint.css -S`
3. attempt to run your dev server
Config:
https://gist.github.com/th3fallen/9d360e80a6b0b7cadb709aa8b796a63c

* **What is the expected behavior?**
hint.css should be loaded just as any other dependancy in that list

* **What is the motivation / use case for changing the behavior?**
Error with file name similar packages
 
* **Browser:** all
 
* **Language:** ES6/7

**Comment by sokra** [comment]
hint.css has no main field in package.json.
