### ISSUE TITLE
Improve dead code branch detection

### ISSUE THREAD

**Issue by jhnns** [webpack/webpack#3235]
**I'm submitting a feature request**

**Webpack version:**
1.10.x and 2.x

**Please tell us about your environment:**
OSX 10.x

**Current behavior:**
Starting with React, it has become increasingly popular to check for a development env with an if clause like this:

```javascript
if (process.env.NODE_ENV === "development") { ... }
```

In combination with the `DefinePlugin`, this statement is replaced with `"development" === "development"`. Unfortunately, this code branch is not detected by webpack as dead code branch. Any dynamic imports (or `require()`) that happen to be inside the if-block are still included into the bundle.

With simple checks like

```javascript
if (IS_DEVELOPMENT) { ... }
```

which is turned into

```javascript
if (false) { ... }
```

webpack is already able to ignore the if-block.

**Expected/desired behavior:**
webpack should not include any modules that are required or dynamically imported within this if-block. It would also make sense to remove this code *before tree-shaking*.

**What is the motivation / use case for changing the behavior?**
Smaller bundles 🎉

**Comment by sokra** [comment]
It seems to work correctly. I added some test cases.
