### ISSUE TITLE
Using RegExp Object instead of literal as pattern for require.context causes dependency analysis failure

### ISSUE THREAD

**Issue by steinbachr** [webpack/webpack#3237]
**I'm submitting a bug report**

**Webpack version:**
1.13.3

**Please tell us about your environment:**
OSX 10.12.1

**Current behavior:**
Using a `RegExp` object as the `require.context` pattern causes a warning `Critical dependencies:
23:18-25 require function is used in a way in which dependencies cannot be statically extracted` (and subsequent page error `Uncaught TypeError: __webpack_require__(...).context is not a function(…)`)

**Expected/desired behavior:**
Using a `RegExp` object versus literal should have equal results

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.** 
this works: `require.context('styles/pages', false, /desktop\.(less|css)/);`
this fails: `require.context('styles/pages', false, new RegExp('desktop\.(less|css)'));`
 
**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
all
 
**Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart | ...] 
all

**Comment by TheLarkInn** [comment]
@sokra is this just because of the parser looking for literal vs object vs both? 

This could fall in the `easy` column for contribs if so, right?

**Comment by Kovensky** [comment]
To tell if this is the object, the parser would need to look for a new expression, see if what it calls is RegExp, see if the RegExp in scope is the global RegExp, then evaluate the first argument as the regexp contents with the second argument as the modifiers... /o\

I don't see any reason to not use a regexp literal, which was added to the language way back in the 90s, unless you are using a dynamic regexp, which webpack probably can't support. It also requires extra escaping in the string -- your `new RegExp('desktop\.(less|css)')` actually matches `/desktop.(less|css)/` as you need to escape the `\` with a `\`.

**Comment by shcallaway** [comment]
Is there any update on this feature? I need it. Hehe 👍
