### ISSUE TITLE
variables and vuejs is always undefined

### ISSUE THREAD

**Issue by NikosEfthias** [webpack/webpack#3239]
**I'm submitting a bug report**

**Webpack version:**
1.13x

**Please tell us about your environment:**
Ubuntu 16.4

**Current behavior:**
impossible to use variables defined in packages

**Expected/desired behavior:**
using variables

-----

[here](https://imgur.com/a/HsVoT) you can see i am importing both Vue and error.js files but in the page errors  and Vue variables are undefined

here's my config file 
```js
const webpack = require("webpack");
module.exports = {
	entry: "./webpack.js",
	output: {
		path: __dirname,
		filename: "bundle.js"
	},
	module: {
		loaders: [
			{ test: /\.less$/, loader: "style!css!less!" },
			{ test: /\.css$/, loader: "style!css!" },
			{
				test: /\.(woff|woff2|ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
				loader: 'base64-font-loader'
			}
		],
		plugins: [
			new webpack.optimize.OccurrenceOrderPlugin(),
			new webpack.optimize.UglifyJsPlugin(),
			new webpack.optimize.DedupePlugin()
		]
	}

}
```
 
* **Browser:** all
 
* **Language:** all

**Comment by SpaceK33z** [comment]
This is not a bug, you can't access variables from another file without exporting them. In the `errors.js` file, add `module.exports = errors;` on the last line. To use Vue.js, use `var Vue = require('./bower_components/vue/dist/vue.min.js');`.

Note that I would recommend not to use Bower if possible; with npm you can do do `var Vue = require('vue');`.

**Comment by NikosEfthias** [comment]
thank you and can i use const let as i do in nodejs or this is not compiled so i can have browser compatibility issues ?

**Comment by friedemannsommer** [comment]
If you dont use any precompiler like BabelJS i would recommend you to not use ES2015+. (If you want your JavaScript run cross-browser.
