### ISSUE TITLE
Unable to disable comment preserving in uglifyjs plugin

### ISSUE THREAD

**Issue by dashed** [webpack/webpack#324]
Trying to do this: `new webpack.optimize.UglifyJsPlugin({ comments: false })`

Setting will be overwritten because of this: 
https://github.com/webpack/webpack/blob/master/lib/optimize/UglifyJsPlugin.js#L79

Other reference:
https://github.com/mishoo/UglifyJS2/blob/master/lib/output.js#L62

**Comment by firstdoit** [comment]
I have the inverse problem. Uglify is removing comments inside an HTML string and `"comments":"all"` is having no effect. Any idea when I'll be able to configure this properly?

**Comment by firstdoit** [comment]
Oops, apparently it was the html loader who was realizing there was minification going on and turned it's own minification processes on. I have manually disabled it and everything works.

**Comment by tleunen** [comment]
Found this post while searching for the same issue.

@sokra gave a workaround, which still works. Does it mean it's the right way now and it's not a bug?

**Comment by Dashed** [comment]
@tleunen Should be resolved with https://github.com/webpack/webpack/pull/1298.

**Comment by WickyNilliams** [comment]
I'm still seeing this issue in latest version of webpack. @sokra's workaround does the trick

**Comment by NomNomCameron** [comment]
Can confirm that @sokra's workaround is still required for this

**Comment by sokra** [comment]
btw. it's intended that webpack preserves some comment. This is for legal reasons. By default comments with `@license`, `@preserve` or starting with `/*!` are preserved.

**Comment by Dashed** [comment]
@WickyNilliams @NomNomCameron  I tested using `v1.12.6` on jquery source, and it seems to work just fine (with or without the workaround). The test I provided in my PR (https://github.com/webpack/webpack/pull/1298) didn't fail. 

Are you sure you're using latest webpack version for both local and global?

**Comment by ccorcos** [comment]
@sokra intersting! what legal reasons?

**Comment by dashed** [comment]
@ccorcos you typically want to preserve licenses which are usually at the top as a multi-line comment.

**Comment by ccorcos** [comment]
That's what I'm reading here, but why is that?

**Comment by dashed** [comment]
@ccorcos some licenses require it.

**Comment by ccorcos** [comment]
Look at this mess:

```
!function(e){function t(n){if(r[n])return r[n].exports;var o=r[n]={i:n,l:!1,exports:{}};return e[n].call(o.exports,o,o.exports,t),o.l
  !*** ./~/lodash/lodash.js ***!
  \****************************/
function(e,t,n){(function(e,r){var o;(function(){function i(e,t){return e.set(t[0],t[1]),e}function a(e,t){return e.add(t),e}function
  !*** ./src/client/environment.ts ***!
  \***********************************/
function(e,t,n){"use strict";Object.defineProperty(t,"__esModule",{value:!0}),t.default=null},/*!************************************
  !*** ./src/client/components/Component.ts ***!
  \********************************************/
function(e,t,n){"use strict";var r=this&&this.__extends||function(){var e=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&func
  !*** ./~/react/react.js ***!
  \**************************/
```

So many comments that I dont need!

**Comment by chestozo** [comment]
Comments in bundle can result in issue like this one when wrong line number is reported in tools like Sentry
https://github.com/getsentry/sentry-javascript/issues/2550#issuecomment-769909629
