### ISSUE TITLE
Publish 2.x as webpack@next

### ISSUE THREAD

**Issue by caseyWebb** [webpack/webpack#3241]
Would help a lot for installing the latest beta (e.g. `npm install webpack@next`) and package.json dependencies (e.g. `{ "webpack": "webpack@next" )`)

The command to do so is:
`npm publish --tag next`, this command should be ran whenever there is a new release

**Comment by SpaceK33z** [comment]
We already publish it with a beta tag (`npm publish --tag beta`). You can do `npm install webpack@2.1.0-beta` and it will follow new beta versions.

**Comment by caseyWebb** [comment]
👍 sorry, didn't see that on npm
