### ISSUE TITLE
Loader include option is case-sensitive

### ISSUE THREAD

**Issue by ilya-git** [webpack/webpack#3243]
**I'm submitting a bug report**

**Webpack version:**
1.13.3

**Please tell us about your environment:**
Windows 8

**Current behavior:**

Include (and probably exclude) are case-sensitive.

**Expected/desired behavior:**

Both include and exclude should be case insensitive since folder names are case insensitive in Windows. It was very frustrating experience to find out what was wrong, so I suppose it should be case insensitive by default (I am not sure how it should work on Linux/OS X)

**Steps to reproduce** 

Create an include section for a loader with a lower-case folder, example:
`include: "C:\test\css"`

While in Windows folder structure have the name like this:

`C:\Test\css`

It appears to be that when the file C:\Test\css\example.css was used it was not matched against the loader and I got an error "You may need an appropriate loader to handle this file type.". After I fixed include to be exactly the same, it worked.

**Comment by TheLarkInn** [comment]
Do you know if this behavior persists for webpack v2? Would be something we'd want to fix if so.

**Comment by ilya-git** [comment]
I have no idea if it's still in webpack2, but if it is it better be fixed there as well :)

**Comment by sokra** [comment]
You better always assume everything is case-sensitive (even while on windows/osx fs it's not). Modules are case-sensitive. Using the incorrect casing will lead to bugs.

**Comment by ilya-git** [comment]
I cannot quite understand why do you close this? There is nothing about the modules, but pure paths in there and the matcher does not understand that "C:\Test" and "C:\test" is really the same folder when it tries to match it.
