### ISSUE TITLE
No require.main.filename on nodejs

### ISSUE THREAD

**Issue by apsavin** [webpack/webpack#3244]
**I'm submitting a bug report**
No `require.main.filename` on nodejs

**Webpack version:**
1.10.5

**Please tell us about your environment:**
OSX 10.12

**Current behavior:**
`require.main.filename` is undefined after webpack compilation

**Expected/desired behavior:**
`require.main.filename` is a string - see [nodejs docs](https://nodejs.org/api/all.html#modules_accessing_the_main_module)

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.** 
It seems that any build of node app with webpack is affected
Sample [conf](https://gist.github.com/apsavin/3e734043ed7da2a89f55cb8f62510753)

* **What is the motivation / use case for changing the behavior?**
Node.js features must not be broken after build
 
* **Language:** [all]

**Comment by sokra** [comment]
Sorry, `filename` is not supported by webpack. It tries to hide all path details.

**Comment by felipenmoura** [comment]
I don't get it...is it for safety reasons?
I got frustrated now because of this missing data...specially because require.main.filename is official and all.
Why does webpack try to hide all paths? Maybe we could use a flag to allow this information being passed along?

**Comment by TechStudent10** [comment]
Why is this?

**Comment by mrrishimeena** [comment]
Why is this issue closed? Is it fixed? I am still facing this issue with the latest Webpack version. Even `require` is undefined in the bundle.
