### ISSUE TITLE
update dep watchpack and allow use of watchOptions.ignored

### ISSUE THREAD

**Issue by yinghaochan** [webpack/webpack#3245]
**I'm submitting a feature request**

**Webpack version:**
1.10.x/2.x

**Please tell us about your environment:**
OSX 10.x / Linux / Windows 10

**Current behavior:**
watchpack uses version ^1.0.0

**Expected/desired behavior:**
use version ^1.1.0

* **What is the motivation / use case for changing the behavior?**
allow `config.watchOptions.ignored = [/node_modules/] `

**Comment by sokra** [comment]
`^1.0.0` includes all versions `< 2`

**Comment by yinghaochan** [comment]
I'm sorry! typed that wayy too fast. `v1.13.x` of webpack uses `watchpack: "^0.2.1"`

https://github.com/webpack/webpack/blob/v1.13.2/package.json

**Comment by idangozlan** [comment]
It's really necessary, please merge it asap.

**Comment by yinghaochan** [comment]
@idangozlan  just fork it and change the version number in package.json 

`"watchpack": "^1.1.0",`
