### ISSUE TITLE
cannot get a common chunk for the code splitting required on demand

### ISSUE THREAD

**Issue by bupthly** [webpack/webpack#3251]
I use webpack 1.13.1, es6 and use babel to transfer it to es5.
I use code splitting to let the code be required on demand. And I meet two problems as below.
* problem 1 * :
a.js (on demand) 
      import c;
      import d;
      import e;
b.js(on demand)
      import c;
      import d;
      import f;

I want to get the c and d in a common chunk and only be loaded once.

I use ComonsChunkPlugin like this:
new webpack.optimize.CommonsChunkPlugin({
      async: true
}),

And it do give a common chunk, but only the content of c is in the common chunk, without d.

* problem 2 *
As the file size if really small after code splitting, I use AggressiveMergingPlugin() to merge the small files. But if I use AggressiveMergingPlugin() and CommonsChunkPlugin() at the same time, AggressiveMergingPlugin doesn't work. 

So is webpack possible to do these two things:
1, get the common chunk for the code required on demand and only be loaded once.
2, merge the small files and keep the common part a separate chunk.

thanks.

**Comment by sokra** [comment]
Could you prepare minimal examples for the issues?

**Comment by jharris4** [comment]
I'm curious about this issue as well. I posted a comment about how require.ensure seems to automatically create a common chunk, whereas System.import does not:

https://github.com/webpack/webpack/issues/3364#issuecomment-273983958

I'm currently using the CommonsChunkPlugin like this:

`new webpack.optimize.CommonsChunkPlugin({ name: 'vendors', filename: '[name]-bundle.js' })`

Is there some option I could add to make System.import behave the same way that require.ensure does?
