### ISSUE TITLE
Webpack is not replacing default argument values with __WEBPACK_IMPORTED_MODULE_ value 

### ISSUE THREAD

**Issue by mohsen1** [webpack/webpack#3252]
To reproduce this error clone [https://github.com/blacksonic/typescript-webpack-tree-shaking](https://github.com/blacksonic/typescript-webpack-tree-shaking) and modify `car.ts` to: 

```ts
import * as E from './engine';


function fooBar({some, bar = E.V6Engine}) {
  console.log('FooBarBaz');
}
```

And run `npm run webpack-es2015`

The output file at `dist/car.es2015.bundle.js` has following content at the end:

```js
/***/ },
/* 1 */
/***/ function(module, exports, __webpack_require__) {

"use strict";
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__engine__ = __webpack_require__(0);

function fooBar({ some, bar = E.V6Engine }) {
    console.log('FooBarBaz');
}

```

**Webpack version:**
2.1.0-beta-25

**Please tell us about your environment:**
OSX 

**Current behavior:**

function default argument value is  not `__WEBPACK_IMPORTED_MODULE_0__engine_.V6Engine`

**Expected/desired behavior:**
function default argument should be `__WEBPACK_IMPORTED_MODULE_0__engine_.V6Engine`

* **Language:** TypeScript 

I believe this is not specific to TypeScript and is a general behavior for ES2015 modules.

**Comment by sokra** [comment]
cc @Kovensky

**Comment by zhaoshengjun** [comment]
I just fixed this. PR will coming shortly.

**Comment by zhaoshengjun** [comment]
@mohsen1 Will you please verify this?

**Comment by mohsen1** [comment]
Hey sorry I got busy. Steps to reproduce is pretty clear. I'll try checking it out today

**Comment by mohsen1** [comment]
Yup it's fixed at beta 27

```js

/***/ },
/* 1 */
/***/ function(module, exports, __webpack_require__) {

"use strict";
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__engine__ = __webpack_require__(0);

function fooBar({ some, bar = __WEBPACK_IMPORTED_MODULE_0__engine__["a" /* V6Engine */] }) {
    console.log('FooBarBaz');
}


/***/ }
/******/ ]);⏎
```
