### ISSUE TITLE
Package missing file

### ISSUE THREAD

**Issue by chenxuangou** [webpack/webpack#3253]
**I'm submitting a bug report**

**Webpack version:**
1.13.3

**Please tell us about your environment:**
Windows 10

**Current behavior:**

* **Package two files**

//////////////////////////////////////
**1.test.component.ts**
import {Component} from '@angular/core';
import { Router }         from '@angular/router';

@Component({
    selector : 'test',
    moduleId: 'test',
    styleUrls: ['test.component.css'],
    templateUrl : 'test.component.html',
})
///////////////////////////////////
**2.app.component.ts**
import {Component} from '@angular/core';

@Component({
    moduleId: 'my-app',
    selector : 'my-app',
    templateUrl: 'app.component.html',
    styleUrls : ['app/App/app.component.css'],
})
//////////////////////////////////////////

* **Package results**

//////////////////
**test.component Part**
 selector: 'test',\r\n      styles: [__webpack_require__(160)],\r\n            templateUrl: 'test.component.html',\r\n 
//////////////////
**app.component Part**
 selector: 'my-app',\r\n            template: __webpack_require__(116),\r\n            styleUrls: ['app.component.css'],\r\n        }), \r\n
/////////////////

* **why**  ‘test.component.htm’ and ‘app.component.css’ have not compile???!!!!!!

* **Browser:** [ Chrome ] 
 
* **Language:** [ TypeScript | ES6]

**Comment by sokra** [comment]
They are not required/imported...

`templateUrl: require('./app.component.html')`
