### ISSUE TITLE
Webpack watch CLI output the same error message when continuously encounter different syntax error

### ISSUE THREAD

**Issue by kerryChen95** [webpack/webpack#3254]
**I'm submitting a bug report**

**Webpack version:**
1.13.3

**Please tell us about your environment:**
Windows 10

**Current behavior:**

I use webpack to watch my souce code and compile, if there are two or more syntax error in my code, webpack CLI output error messages about the first syntax error, after I fix the first one, webpack still display error message of the first one.

**Expected/desired behavior:**

Webpack output messages about the error encountered at the last compile.

**Comment by kerryChen95** [comment]
If continuously encounter different error at compiling, I think webpack should generate a different `stats.hash`, or just NOT check `lastHash` before output `stats`.

```
break in path\to\my\project\node_modules\webpack\bin\webpack.js:173
 171            if(outputOptions.json) {
 172                    process.stdout.write(JSON.stringify(stats.toJson(outputOptions), null, 2) + "\n");
>173            } else if(stats.hash !== lastHash) {
 174                    lastHash = stats.hash;
 175                    process.stdout.write(stats.toString(outputOptions) + "\n");
repl
Press Ctrl + C to leave debug repl
> stats.hash
'41e302d8959cdc6b1b3f'
> lastHash
'41e302d8959cdc6b1b3f'
```

**Comment by sokra** [comment]
That's probably the issue: hash is equal no matter which syntax error is in the file. It's because the file is not included in the bundle when it contains a syntax error.

**Comment by kerryChen95** [comment]
Can webpack CLI output `stats` when `stats.hash !== lastHash || stats.hasErrors()` return `true`? If can, I will make a PR.

**Comment by tuures** [comment]
#3023 would fix this issue. Checking just for `stats.hasErrors() || stats.hasWarnings()` does not cover all cases: e.g. when last error/warning is removed.

An alternative would be to save error+warning count and check for something like `stats.hash !== lastHash || notDeepEqual(lastErrorsAndWarnings, errorsAndWarnings)` to show stats only when errors or warnings have actually changed.

**Comment by sokra** [comment]
An option to fix this issue is to make warnings and error to contribute to the build hash (but not to the chunk hash).
