### ISSUE TITLE
Horizontal scrollbar on webpack.github.io

### ISSUE THREAD

**Issue by tobireif** [webpack/webpack#3257]
For example in Chrome, the page https://webpack.github.io/ can be scrolled horizontally by 100% -> blank screen.

Here's a quick fix: Change

```
<div class="logo" style="-webkit-transform:scale(3);
-ms-transform:scale(3);transform:scale(3);height:660px;
z-index:-1">
```
to
```
<div class="logo" style="-webkit-transform:scale(3);
-ms-transform:scale(3);transform:scale(3);height:660px;
z-index:-1;width:33.33%;margin-left:33.33%">
```

But I think it would be better to eg avoid the upscaling completely.

**Comment by imvetri** [comment]
Good observation

**Comment by Kovensky** [comment]
`width:220px;height:220px;margin:220px auto;` also should work instead of relying on percentages and rounding.

The scaling needs to be done because the animation itself is built with CSS, but I don't know why the scale affects width/height but not the bounding box in the parents' flow.

**Comment by sokra** [comment]
@TheLarkInn @patrickkettner Could you take care of this?
