### ISSUE TITLE
Livereloading assets as well as webpack on webpack-dev-server

### ISSUE THREAD

**Issue by Madgvox** [webpack/webpack#326]
I've been working with webpack-dev-server for a couple weeks now, and I love the way it operates. However, it only watches/updates webpack, not any other assets (like external css/html not loaded with webpack). I don't really expect it to, but I'm finding trying to combine it with my own livereload server all but impossible. 

I've stared at the 'Combining with an existing server' section of the documentation plenty, but it's such a bare-bones documentation I'm not even sure if it's what I'm looking for. Is there an easy/any way to do this?

**Comment by bebraw** [comment]
@Madgvox Did you figure this out?

**Comment by SpaceK33z** [comment]
Closing this very old ticket because this is now a feature request for WDS: https://github.com/webpack/webpack-dev-server/issues/350.
