### ISSUE TITLE
Better support for bundling vendor scripts that aren't packaged as modules

### ISSUE THREAD

**Issue by jpfranco** [webpack/webpack#3264]
**Webpack version:**
1.10.x

**Please tell us about your environment:**
OSX 10.x

**Current behavior:**
Currently I have a few options if in my bundle I want to include raw vendor scripts that are not packaged as modules. I can match them with `noParse` or use the [script-loader](https://github.com/webpack/script-loader). These solutions work in some cases, but since it's common for these scripts to assume that they will be loaded in a global context, some additional setup is usually required such as shimming with `imports-loader`, `exports-loader`, etc.

**Expected/desired behavior:**
It would be useful to have a way to simply concatenate raw scripts to a bundle, without having them wrapped around with `function(module, exports) {}` or included as a string and then executed with `eval()` (when using `script-loader`). I don't know if there's a performance penalty when using `eval()` in modern browsers, but I still think it would be preferable to just run the script without it.

**What is the motivation / use case for changing the behavior?**
I realize that Webpack is not Grunt or Gulp, and that it's main use case is not file concatenation, but I assume that it will be common for people to want to include third-party scripts along with their newer, module-friendly code. 

I feel that there is little benefit in forcing these vendor scripts to behave as modules, specially for cases in which it is necessary to export values to the global context in order for these libraries to run. I think it would be much cleaner and easier if these scripts could just be concatenated as they are. [There are some cases](http://stackoverflow.com/questions/40497794/concatenating-raw-javascript-to-a-webpack-bundle) in which some libraries simply break when wrapped around a function and the usual imports/exports loader fixes don't work. *

In my particular use case I don't want to have a separate file for vendor scripts, so `CommonsChunkPlugin` is not an option for me. AFAIK this also wraps the code inside a function, so this would also have the problems described above.

\* **EDIT**: this seems to work correctly with `script-loader`, after properly matching the files

**Comment by sokra** [comment]
The best practice is to NOT use the script-loader. Instead of just adding the script you should use `import/export-loader` to "fix" the script to be a CommonJS Module, which can be use as that than.

Bad:

``` js
require("script!underscore");

_.map(...);
```

Good:

``` js
var _ = require("underscore");

_.map(...);
```

``` js
{test: require.resolve("underscore"), loader: "import-loader?window=>{}!export-loader?window._"}
```

The differences:

* `_` is not a implicit global/dependency
* Configuration is in config file
* Code is cleaner

**Comment by jpfranco** [comment]
Thanks @sokra, I agree that the above example is handled better that way. My concern is mostly with other types of libraries that are harder to shim. I'm thinking about closed-source, third-party stuff that is shipped minified and is treated as a black box for the most part. 

Sometimes these libraries will have several objects that need to be exported (not all of them will necessarily be documented in their API's), and I feel like it's easy to botch the shimming because in order to do it properly you might need more intimate knowledge about the internals.

Now that you mention `script-loader` as not being the best practice, do you know if there are significant drawbacks to running these scripts with `eval()`?

**Comment by TheLarkInn** [comment]
@jpfranco these closed third party scripts, are they services or companies we can try and reach out to or have them reach out to us to find a better solution? 

You run into the potential of web perf problems lack of tree shaking hard to debug problems with this method and I think we should work together with these folks to find a solution.
