### ISSUE TITLE
[WebPack 2] URL based WebPack

### ISSUE THREAD

**Issue by gunta** [webpack/webpack#327]
While thinking about what features would be great for **WebPack 2**, I just found this:
[normalize.io](http://normalize.github.io/)

It has some very cool features like not needing an "asset building" step, being CDN friendly (perfect for sharing between projects), package manager agnostic, flat dependency tree (no de-duping needed), normalized entry points, etc.

Also I just found something released this week, [OpenRoss](http://developers.lyst.com/data/images/2014/06/23/openross/), which is a on-demand URL based image resizer.

I'm inclined to think that **on-demand, url based transformation, caching asset building** can be one of the big **WebPack 2** features.

What is your thought on the matter?

**Comment by bebraw** [comment]
normalize.io seems to be defunct. Perhaps the functionality is better handled in user space?

**Comment by bebraw** [comment]
If you are still interested, could you open a RFC issue describing exact details of how this would work out?
