### ISSUE TITLE
Documentation on how to use hidden-source-maps

### ISSUE THREAD

**Issue by viridia** [webpack/webpack#3270]
Documentation request:

Webpack allows generation of hidden source maps, but doesn't explain what they are or how to use them. A google search for the term 'hidden-source-map' turns up nothing useful. It would be good if the webpack documentation would contain some clue as to how these are supposed to work.

**Comment by rafde** [comment]
I think this issue belongs in https://github.com/webpack/webpack.js.org/issues

**Comment by sokra** [comment]
https://webpack.js.org/configuration/devtool/#devtool

**Comment by Kovensky** [comment]
@sokra that explains what the "hidden" option does, but not how to make practical use of it 😕

**Comment by sokra** [comment]
Example use case: Build with SourceMaps but don't expose the SourceMap for the browser dev tools, and only use it to map error stack traces from error reports.
