### ISSUE TITLE
Typescriptify Webpack

### ISSUE THREAD

**Issue by e-cloud** [webpack/webpack#3277]
Webpack has been incredibly popular around the JS world. Its design philosophy wins trustment of the community.

To further envolvement, it's very important that webpack has solid codebase to embrace the rapidly changing world.

However, as code grows, without great test suite and other devtool, code can be gross. For now, webpack's source is written in ES5. And as you know, there isn't much documentation in the source. It's hard for incoming contributors to understand the codebase. Thus, it's harder to make webpack real-better.

Typescript is a great tool to help webpack to achieve greater goal.

#### SO, you can see https://github.com/ts-webpack/webpack/tree/feature/tsify is out!

---

#### done
* the core dependency tree of webpack have been converted into typescript mostly(*except watchpack*).

* types of those sorrounding modules have been submitted to DefinintelyTyped. This is for more accurate type checking for webpack eventually.

* the source code of webpack has been converted into typescript catching up with the recent commits(needs further synchronization)

* its fully compatibility with current test suite. (There is one bug of the latest typescript which will causes test error)

#### missing
* **enable `strictNullChecks` and make the source fully type-checked.**

* a new set of build-tool to support and guard the new source code.

* refactoring to make some code more clear to be understood.

* adopt ES6 module system to fix the reference error as some module's structure is incompatitble with  the type system(at least for now there is no easy way to solve that).

* responses from the webpack core-team and the community :smile:

**Comment by Kovensky** [comment]
😮 

It's unfortunate that the code is not `"strictNullChecks": true`; this could make it harder to use the type information e.g. when writing a plugin that does use it. But I understand that it could generate a huge amount of type errors if it's "just" enabled on such a big project.

But even non-strict types would definitely be better than no types; just today I experimented with writing a `webpack.config.ts`, and I sure had to write a lot of `(webpack as any)`. 😇

**Comment by e-cloud** [comment]
@Kovensky , yes, the source of webpack haven been enabled `strictNullChecks`. That's one thing i forgot to mention in missing. In fact, all the other surrounding modules have been enabled.

There is one reason I haven't done such config. Webpack has a  large codebase. Even without `strictNullChecks`, current converted code still has some type conflicts(I have written a lot of type guards). And a lot of functions and variables and somethings else have no type information somehow, you have to infer the types manually. That's a bigger job need to be done.

So, I push it out, let the community knows and want to cooperate with **other volunteers** to make the typescript-version source fully type-checked under higher speed.

### YES, I want help from you guys.

**Comment by dcworldwide** [comment]
It's a good idea. Have you had any feedback from the core maintainers?

**Comment by e-cloud** [comment]
Not yet

**Comment by donaldpipowitch** [comment]
FYI: It looks like the core maintainers actually want to use TypeScript as well. Here is a [paragraph about it](https://medium.com/webpack/sustaining-webpack-for-the-future-part-1-32bea7f9e8a2#.uzoagqi4t).

That would be really great.

**Comment by TheLarkInn** [comment]
I think this is a great idea but there are two concerns: 

* Community split
* Graceful transition. 

The first initiative if you would entertain the idea is to have long term branches (until Dec 1) where we convert the entire codebase to es6 first, even though it's not an exact transition from Flow or TS, it's an irritable step that will increase contibute-ability. Going right to TS may raise the barrier of entry at first.

**Comment by TheLarkInn** [comment]
Then once we drop node .12 support we can then start merging those changes in and start a class by class file by file transition. I think once this is accomplished we can then start exploring the possibilities with TS or Flow there are benefits to either that we should heavily weigh before deciding.

**Comment by dcworldwide** [comment]
@TheLarkInn that will take forever. Such an approach is way too conservative.

Ts is awesome and perfect for simplifying community projects and is incrementally adoptable.

You can apply the same class by class strategy with Ts, it still emits js after all. It also plays nice with babel.

**Comment by TheLarkInn** [comment]
> @TheLarkInn that will take forever. Such an approach is way too conservative.

Out of experience at least using both and having a pretty intimate understanding of the code base, I cannot share this sentiment. 

> Ts is awesome and perfect for simplifying community projects and is incrementally adoptable. 

This is slightly objective but I agree and disagree. TS and Flow are not complete supersets of JS, and because of this, there are some concerns regarding our plugin system (webpack/tapable) which has some big challenges with a migration to TS/Flow. 

In regards to time, the benefits such as interfacing, typing and type guarding, which are what make using TS/Flow justifiable are the real time consumers (again thats still objective on my part as well). 

As I agree that we could work incrementally, we need to make this move as a community as a whole. In the end we want to be able to support and help a joint endeavor and by splitting into two repos we limit our ability to do this.

**Comment by e-cloud** [comment]
The repo is separate because I have got no response from you the core-team. Splitting the community is not what i want.

In fact, before, I thought it may act as a branch of the origin repo once it's accepted. And when it comes to a proper time, with enough tests by the ecosystem and community, we can easily migrate to it.

---

> entire codebase to es6 first

> once we drop node .12 support

Even node v4 is not es6 fully-featured. Converting to es6 means using Babel to produce production code?

> start a class by class file by file transition.

Sorry, have you check out my repo? The fact is this job have been done mostly. But the current webpack implementation is not fully es6-convertable(class mainly). Thus, it's **mostly**. Converting to es6 is easy that you only have to change the typescript compile target to `es6`.

At least, **passing the test suit means its compatibility**. However, it may be not compatible with customized usage.

**Comment by e-cloud** [comment]
> Out of experience at least using both and having a pretty intimate understanding of the code base, I cannot share this sentiment.

I understand your concern.

One thing should mention that I just start learning Typescript about a month ago. The hard part is its type system. It's not hard to learn Typescript with Javascript knowledge base, somehow. 

If, a contributor wants to contribute without knowing Typescript, he/she can simply ignore the typings and continue his/her job. And we can give some guidance to let them know that.

> TS and Flow are not complete supersets of JS, and because of this, there are some concerns regarding our plugin system (webpack/tapable) which has some big challenges with a migration to TS/Flow.

@TheLarkInn what concerns are you refer to?

> In regards to time, the benefits such as interfacing, typing and type guarding, which are what make using TS/Flow justifiable are the real time consumers (again thats still objective on my part as well).

I don't agree with this point. **The biggest benifit is for the developers of webpack itself**.

Webpack now has a large code base with little documentation. Actually, it's one of the main barriers keeping contributors from getting wet. With type system, even without detail documentation, developers can be easier to track down to do real enhancement. (I've seem some minor commits, and repect them and the effort, but it is just not the right way to do it)

Another concern is, you know, there is no much unit test for the sources. Most of them are integration tests like e2e test in the browser. IMHO, sometime some code is just like a black box but passes the tests. Typescript can help reduce those ambiguities.

**Comment by Kovensky** [comment]
> there are some concerns regarding our plugin system (webpack/tapable) which has some big challenges with a migration to TS/Flow.

It is unfortunate that it's not possible to know the type of the callback, or the arguments that the callback receives, so some degree of type assertions will still be needed.

While that would make typing weaker, it would not be the kind of thing that prevents projects from working; it's why both type systems have an `any` type. (actually, I wonder if it would be possible to declare subclass overloads where the first arg has a string constant type)

**Comment by TheLarkInn** [comment]
I agree with all of these points. My only concern is that we take the migration at a more steady and controlled path. A effort of this size requires considerable planning, consideration, and public communication with the community of users and loader and plugin authors/maintainers. 

Of course I can't control what you decide to do, that's one of the beauties of open source, but what I can tell you is that as an organization and a core team, we have discussed this deciding that it makes sense to first migrate the code to ES6 first (where applicable for node 4.x). 

Once documentation is finished it is _vital_ to the success and progress of the project to implement key features for output optimization.

Im not saying stop this work, just that it may take much longer to merge this back to master than it would if you started working on ES6 syntax conversions piece by piece.

**Comment by e-cloud** [comment]
@TheLarkInn if you guys start to working on ES6 Syntax, I would not suggest converting piece by piece.
We can use the ts-version to generate ES6 version. Yesterday I give a try and have some fixes and it turns out that the generated ES6 code pass the tests.

**Comment by jhnns** [comment]
First of all: thx @e-cloud for that suggestion and your tremendous work. I don't really see how many parts of webpack you've already translated but it was surely already a lot of work. I really appreciate that 👍 

Personally, I'm not Anti-TypeScript and I totally see the benefits of defining types for other developers (for auto-completion and validation for instance), but I see a huge trade-off in terms of accessibility for other developers. We've seen this problem already with CoffeeScript, although I must admit that TS is closer to JS than CS was.

If we want to improve the developer experience (and I agree with you in regards to the current code base), I think Flow would be a more lightweight approach, where we have type checking but without actually using another language. But I have no practical experience with Flow so I'm a little bit clueless here.

That being said: I'm not totally against this, but I'm not convinced that the benefits outweigh the effort.

**Comment by donaldpipowitch** [comment]
@jhnns My 2 cents: TypeScript is as much "type checking but without actually using another language" as flow. IMHO there is practically not a big difference in terms of usage between them. They only differ slightly in some details about typings or code analysis. I also think flow is as much a "different language" to JavaScript as TypeScript is. They _are_ just JavaScript with types. In flow you have to add `/* @flow */` on top of your files to (initially) start type checking, in TypeScript you would rename your `.js` file to `.ts`. I wouldn't say this makes TypeScript more of a different language.

Yes, not all valid JavaScript code is valid TypeScript code. But as far as I can see only error prone code is rejected - which I think is a good thing.

I think neither flow nor TypeScript can be compared to CoffeeScript here. In my experience flow/TypeScript is not a "huge trade-off in terms of accessibility", but can help others accessing your code _a lot_, because the types help people explain your code and they help navigating inside your project.

But it's try that flow _can_ be more "lightweight" to add and use, if you already have a Babel-based build pipeline in place.

Comparing both flow and TypeScript, I don't prefer any solution really much in points of features, but I slightly prefer TypeScript a little bit more, because in my experience there are a little bit more popular, so you find more typings of 3rd party code, its community supports more different frameworks (flow is most popular in the React community) and tooling in IDEs is better (thanks to TypeScripts great language server).

**Comment by dcworldwide** [comment]
Ts is a superset that follows the ecmascript spec with optional types. Its developed by m$ and the same team that wrote c#. So for many reasons, it isnt fair to compare it to cs. Its benefits are clear to me but if you haven't used it I can understand the trepidation. As it is incrementally adoptable, imo it makes complete sense to rewrite Web pack in es6 from the start. You won't regret it. That's just my 2c.

**Comment by e-cloud** [comment]
### current status
For the last days, I've been adding typings for the source and sync with the upstream repo.
Most of source code have been typed. What's left is to adjust unmatched types, and to enable `strictNullCheck` and then fix improper types.

### about bugs
And in that period, with Typescript's check, I've found out several dead code and a bunch of bugs. Some small bugs are small enough to fix out during the typing work. The other are left to discuss and then have fixes.

### Ad again
In **current typescriptified webpack source**, there are not much advanced Typescript features used. That's to say, if the team are willing to change, the migration should be less painful and easy to maintain and envolve. The Typescript features used now are nothing more than **ES6 + basic type system**( and a little ES7 ). IMHO, it's the same when using ES6(not 5) + Flow.

I can announce, with Typescript, the quality of source will be much more solid. :relieved:

**Comment by donaldpipowitch** [comment]
Would still like to see it 👍  It would help me when I use the Node API of webpack (especially for prereleases or stuff like that, which is usually don't covered by `@types/webpack`).

**Comment by whitecolor** [comment]
@sokra so is webpack 4 going to be ported/rewrited using TypeScript?

**Comment by ooflorent** [comment]
@whitecolor webpack 4 is written in plain JavaScript. However `webpack-cli` (introduced in webpack 4) is using Flow.

**Comment by glen-84** [comment]
[Oct 15, 2016](https://medium.com/webpack/sustaining-webpack-for-the-future-part-1-32bea7f9e8a2)

> Support for taking the time to convert the entire project to TypeScript. We believe that TypeScript allows users to better write scaled and complex code with rich APIs (like webpack). If we can make code easier for you to write, then its worth our time to invest in for your contributions.

[Apr 20, 2018](https://github.com/webpack/webpack/pull/7046#discussion_r182945619)

> We have talked about this at length in many threads and if it really is needed we can provide a document. The short of it is we do not want anything except JavaScript.

What changed? 😕 

If you really don't want the goodness that is TypeScript, then you might as well close this issue.

**Comment by ZuBB** [comment]
+1 to hear/read an answer on this question from core team. especially taking into account recent changes brought by @mohsen1 -- https://github.com/webpack/webpack/pulls?q=is%3Apr+author%3Amohsen1+is%3Aclosed

**Comment by reduckted** [comment]
@TheLarkInn @sokra Since this is the only issue about using TypeScript in webpack, can we get an official update on the state of things? It seems that there's some use of TypeScript in webpack (#6862), but it's not really clear as to what level it's permitted.

As @glen-84 pointed out above:

[Apr 20, 2018](https://github.com/webpack/webpack/pull/7046#discussion_r182945619)

> The short of it is we do not want anything except JavaScript.

But [seven days earlier](https://github.com/webpack/webpack/pull/6862#issuecomment-380877669), PR #6862 was merged, which adds TypeScript type checking. 😕

**Comment by montogeek** [comment]
Check source code, there is no .ts files, only JSDocs that happen to be compatible with TypeScript.

**Comment by MLoughry** [comment]
@TheLarkInn @sokra With more projects (including `jest`) moving towards Typescript, is there any reconsideration of this position? I could not find the document promised in [this comment](https://github.com/webpack/webpack/pull/7046#discussion_r) that would explain the rationale.

I don't necessarily work *in* webpack much, but I do work on plugins and loaders against the API, and even @TheLarkInn has mentioned how bad the DefinitelyTyped definitions for webpack are. However, if webpack were in Typescript, then it could emit authoritative typings that are updated with every version.

**Comment by vankop** [comment]
linking... https://github.com/webpack/webpack/pull/10599

**Comment by vankop** [comment]
Latest beta provide Typescript definitions builded from webpack source code, so you don't need to use `@types/webpack` anymore. If you will encounter any issues with types feel free to open issues.

@evilebottnawi @sokra I think this could be closed all work is done in `webpack@5`

**Comment by evilebottnawi** [comment]
Agree

> If you will encounter any issues with types feel free to open issues.

:+1:
