### ISSUE TITLE
Document meaning of output from --profile

### ISSUE THREAD

**Issue by abierbaum** [webpack/webpack#3278]
**I'm submitting a feature request**

**Webpack version:**
2.x

**Please tell us about your environment:**
Linux

**Current behavior:**

Use --profile when running webpack provide detailed and interesting output:

```
26810ms building modules                                                                   
120ms sealing
0ms optimizing 
0ms basic module optimization 
139ms module optimization
0ms advanced module optimization 
61ms basic chunk optimization       
0ms chunk optimization 
15ms advanced chunk optimization
0ms module and chunk tree optimization 
232ms module reviving
16ms module order optimization
5ms module id optimization 
4ms chunk reviving 
0ms chunk order optimization 
39ms chunk id optimization
71ms hashing
1ms module assets processing 
281ms chunk assets processing
24ms additional chunk assets processing
0ms recording 
0ms additional asset processing 
4157ms chunk asset optimization
2817ms asset optimization
81ms emitting
Hash: 61828cc0efa75652f957
Version: webpack 2.1.0-beta.25
Time: 34898ms
```

By adjusting settings in your webpack config you can have big impacts on some of these items.  I have seen many issue / reports asking about how to optimize builds, but I haven't found any documentation that says what each of these areas of the profile mean.

For example I found that when doing an incremental build, you can dramatically take down the time spent in "chunk asset optimization" by reducing the size of the asset output from a given change.  (for example by moving more code into a common vendor chunk)

**Desired documentation:**

I would be very appreciative of a simple document with a bulletted list of the items in the profile and what each of them means to an end user.  For example what does "module reviving" mean and what could be done to reduce the time spent there?

I think this type of documentation would be *very* helpful for people like myself looking to optimize builds.

**Comment by bebraw** [comment]
Can you re-open this at the [documentation repo](https://github.com/webpack/webpack.js.org/issues)? Thanks.
