### ISSUE TITLE
cacheDirectory error

### ISSUE THREAD

**Issue by EasonWang01** [webpack/webpack#3282]
`'babel?cacheDirectory=true',`

will cause error,only write in query works like below.

but in another project,if I write querystring it works,why?
```
var webpack = require('webpack');

module.exports = {
  devtool: 'cheap-eval-source-map',
  entry: {
    app:[
    'react-hot-loader/patch',
    'webpack-hot-middleware/client',
    './src/client/client.js'
  ],
  vendor:['react','react-dom']
},

  output: {
    path: require("path").resolve("./src/dist"),
    filename: 'bundle.js',
    publicPath: '/'
  },
  plugins: [
    new webpack.optimize.OccurrenceOrderPlugin(),
    new webpack.HotModuleReplacementPlugin(),
    new webpack.optimize.CommonsChunkPlugin("vendor", "vendor.bundle.js"),
  ],
  module: {
    loaders: [
      {
        test: /\.js$/,
        loader: 'babel',
        exclude: /node_modules/,
        query: {
          presets: ['react', 'es2015','stage-0', 'react-hmre'],
          cacheDirectory: true
        },
      }
    ]
  }
}

```

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template, or open a new issue.

**Comment by EasonWang01** [comment]
Thanks for reply.

## **BEFORE YOU SUBMIT** please read the following:
If you have a support request or question please 
submit them to [StackOverflow](http://stackoverflow.com/questions/tagged/webpack) using the tag `[webpack]` or the [webpack Gitter](https://gitter.im/webpack/webpack). Future support requests will be closed.
(remove this from issue)


**Webpack version:**
1.12.13


**Please tell us about your environment:**
OSX 


**Current behavior:**
1
```
var webpack = require('webpack');

module.exports = {
  devtool: 'cheap-eval-source-map',
  entry: {
    app:[
    'webpack-hot-middleware/client',
    './src/client/client.js'
  ],
  vendor:['react','react-dom']
},

  output: {
    path: require("path").resolve("./src/dist"),
    filename: 'bundle.js',
    publicPath: '/'
  },
  plugins: [
    new webpack.optimize.OccurrenceOrderPlugin(),
    new webpack.HotModuleReplacementPlugin(),
    new webpack.optimize.CommonsChunkPlugin("vendor", "vendor.bundle.js"),
  ],
  module: {
    loaders: [
      {
        test: /\.js$/,
        loader: 'babel',
        exclude: /node_modules/,
        query: {
          presets: ['react', 'es2015','stage-0', 'react-hmre'],
          cacheDirectory: true
        },
      }
    ]
  }
}

```
2
```
import path from 'path';
import webpack from 'webpack';
import webpackDevMiddleware from 'webpack-dev-middleware';
import webpackHotMiddleware from 'webpack-hot-middleware';
import express from 'express';
import debug from 'debug';
import opn from 'opn';
// import proxy from 'http-proxy-middleware';

const debugServer = debug('Redux-Bolierplate:DevServer');

const PORT = process.env.DEV_PORT || process.env.PORT || 8300;
// const DEV_API_HOST = process.env.DEV_API_HOST || 'http://localhost:8200';
const app = express();

const webpackConfig = webpack({
  devtool: 'cheap-eval-source-map',
  entry: [
    'webpack-hot-middleware/client',
    'babel-polyfill',
    path.join(__dirname, 'entry.js'),
  ],
  output: {
    path: __dirname,
    filename: 'bundle.js',
    publicPath: '/',
  },
  plugins: [
    new webpack.DefinePlugin({
      API_HOST: `"${process.env.API_HOST || '/api'}"`,
      API_VERSION: `"${process.env.API_VERSION || '0.0.0'}"`,
    }),
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoErrorsPlugin(),
  ],
  module: {
    loaders: [{
      test: /\.js$/,
      loaders: [
        'react-hot',
        'babel-loader?cacheDirectory=true',
      ],
      exclude: /node_modules/,
      include: __dirname,
    }, {
      test: /\.(jpe?g|png|gif|svg)$/i,
      loaders: [
        'file?hash=sha512&digest=hex&name=[hash].[ext]',
        'image-webpack?bypassOnDebug&optimizationLevel=7&interlaced=false',
      ],
      exclude: /node_modules/,
    }, {
      test: /\.css$/,
      loader: 'style-loader!css-loader'
    }],
  },
});

app.use(webpackDevMiddleware(webpackConfig, {
  publicPath: '/',
  noInfo: true,
  compress: true,
  historyApiFallback: true,
  stats: {
    colors: true,
  },
}));
app.use(webpackHotMiddleware(webpackConfig));

// Proxy for API
// app.use('/api', proxy({
//   target: DEV_API_HOST,
//   changeOrigin: true,
//   pathRewrite: {
//     '^/api': '',
//   },
// }));

app.use((req, res) => {
  res.sendFile(path.join(__dirname, 'index.html'));
});

app.listen(PORT, (err) => {
  if (err) {
    debug(err);
  } else {
    debugServer(`Client Dev Server running on port: ${PORT}`);

    opn(`http://localhost:${PORT}`);
  }
});
```
1.
'babel?cacheDirectory=true'  for `1`  will cause error,only write in query works.

2.
but in `2`,if I write querystring it works,

3.
Is webpack  'react-hmre' support hot reload and not lost state in react now? Because in `1` I don't using `react hot loader` but when I update component  it can still keep the state.

**Expected/desired behavior:**
decrease bundle time

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.** 


* **What is the expected behavior?**


* **What is the motivation / use case for changing the behavior?**

 
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ] 
 Chrome

* **Language:** [all | TypeScript X.X | ES6/7 | ES5 | Dart | ...] 
 ES6/7

**Comment by sokra** [comment]
> will cause error

Which kind of error?

**Comment by sokra** [comment]
Check if it's related to webpack or `babel-loader`/`react-hot-loader`. May ask there.

For questions use StackOverflow.

**Comment by EasonWang01** [comment]
https://github.com/EasonWang01/React-router-Redux-isomorphic-Boilerplate/tree/forum1

full code above.

It says about query presets.

**Comment by EasonWang01** [comment]
It's about query presets, the code here

https://github.com/EasonWang01/React-router-Redux-isomorphic-Boilerplate/tree/forum1

**Comment by sokra** [comment]
I don't understand the problem, could you describe it with more details. What are `query presets`? If it's related to the `presets` option in the babel-loader, please ask in the repo of this loader: https://github.com/babel/babel-loader

**Comment by EasonWang01** [comment]
it says 
```
A common cause of this error is the presence of a configuration options object without the corresponding preset name. Example:

Invalid:
  `{ presets: [{option: value}] }`
Valid:
  `{ presets: ['pluginName', {option: value}] }`
```

so I try to move the query section below
```
        query: {
          presets: ['react', 'es2015','stage-0', 'react-hmre'],
        },
```

it works but not hot reload,then I add some plugin to .babelrc

```
{
    "presets": ["es2015", "react", "stage-0"],
    "plugin": ["react-hot-loader/babel"]
}

```
but in browser it will say the hot reload not config will.
