### ISSUE TITLE
[2.1.0-beta.26] "-loader" suffix is no longer automatically appended

### ISSUE THREAD

**Issue by ide** [webpack/webpack#3283]
**I'm submitting a bug report**
**Webpack version:**
2.1.0-beta.26

**Please tell us about your environment:**
macOS 10.12.1
Node 7.0.0

**Current behavior:**
Loader configs that use the shorthand naming (ex: "css" instead of "css-loader") no longer work -> there is an error about not being able to find a module named "css". This used to work in beta 25.

**Expected/desired behavior:**
Webpack should suffix "-loader" if the module couldn't be found.

**Repro snippet:**
```js
    loaders: [
      {
        test: /\.js$/,
        loader: 'babel',  // needs to be babel-loader
      },
      {
        test: /\.css$/,
        loader: ExtractTextPlugin.extract('css'), // css-loader
      },
```

**Comment by xomyaq** [comment]
#3102

**Comment by ide** [comment]
@xomyaq Thanks, that's helpful. I'll close this then.
