### ISSUE TITLE
Schema Validation Fails for +1 noParse

### ISSUE THREAD

**Issue by MichaReiser** [webpack/webpack#3284]
**I'm submitting a bug report**
Webpack 2 Beta 25 fails if more than one noParse RegEx is used:

```js
module.exports = {
    ... 
    module: {
        noParse: [
            /benchmark\/benchmark\.js/,
            /paralleljs\/lib\/parallel\.js/
        ]
    }
};
```

**Webpack version:**
2.x

**Please tell us about your environment:**
OSX 10.12.1

**Current behavior:**
```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module.noParse should be one of these:
   [RegExp] | RegExp
   Don't parse files matching. It's matched against the full resolved request.
```

**Expected/desired behavior:**
Validates without errors

**Remarks**
The validation does not fail if uniqueItems is removed from the validation schema. From my point it is questionable if unique items makes sense at all for regex expressions (regex literals are never equal anyway)

**Comment by Kovensky** [comment]
For now you can work around with `/benchmark\/benchmark\.js|paralleljs\/lib\/parallel.js/`

**Comment by MichaReiser** [comment]
Jup, thanks... that what i'm doing for the moment...

**Comment by sokra** [comment]
@MichaReiser Do you want to do a PR?
