### ISSUE TITLE
ERROR Module not found with version 2.1.0 beta 26

### ISSUE THREAD

**Issue by LM-G** [webpack/webpack#3286]
**I'm submitting a bug report**
Webpack 2.1.0 Beta 26 fails to bundle ALL my .ts files and generate errors.

**Webpack version:**
2.1.0-beta.26

**Please tell us about your environment:**
Windows 10

**Current behavior:**

`
ERROR in ./src/main.ts
Module not found: Error: Can't resolve 'css' in 'C:\Users\XXX\Documents\GitHub\genesis\client'
 @ ./src/main.ts 5:0-33
 @ multi main

ERROR in ./src/app/app.component.ts
Module not found: Error: Can't resolve 'raw' in 'C:\Users\XXX\Documents\GitHub\genesis\client'
 @ ./src/app/app.component.ts 10:22-53
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./src/app/app.component.ts
Module not found: Error: Can't resolve 'raw' in 'C:\Users\XXX\Documents\GitHub\genesis\client'
 @ ./src/app/app.component.ts 11:21-51
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./src/app/home/home.component.ts
Module not found: Error: Can't resolve 'raw' in 'C:\Users\XXX\Documents\GitHub\genesis\client'
 @ ./src/app/home/home.component.ts 10:22-54
 @ ./src/app/home/home.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./src/app/home/home.component.ts
Module not found: Error: Can't resolve 'raw' in 'C:\Users\XXX\Documents\GitHub\genesis\client'
 @ ./src/app/home/home.component.ts 11:21-52
 @ ./src/app/home/home.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./src/app/core/login/login.component.ts
Module not found: Error: Can't resolve 'raw' in 'C:\Users\XXX\Documents\GitHub\genesis\client'
 @ ./src/app/core/login/login.component.ts 41:22-55
 @ ./src/app/core/login/index.ts
 @ ./src/app/core/core.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./src/app/core/login/login.component.ts
Module not found: Error: Can't resolve 'raw' in 'C:\Users\XXX\Documents\GitHub\genesis\client'
 @ ./src/app/core/login/login.component.ts 42:21-53
 @ ./src/app/core/login/index.ts
 @ ./src/app/core/core.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main

ERROR in ./src/app/core/nav/nav.component.ts
Module not found: Error: Can't resolve 'raw' in 'C:\Users\XXX\Documents\GitHub\genesis\client'
 @ ./src/app/core/nav/nav.component.ts 22:22-53
 @ ./src/app/core/nav/index.ts
 @ ./src/app/core/core.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main
`

**Expected/desired behavior:**
Bundles correctly my app.

**Remark**
Works fine with Beta 25
 
* **Language:** [TypeScript 2.0.6 ...]

**Comment by dkozma** [comment]
I had to append `-loader` (e.g. `css` to `css-loader`) to all of my loader strings for this to work in beta 26 (didn't read the CHANGELOG for this so I'm not sure if this was expected, if there is a better way to solve this, or if this is a bug.

**Comment by dkozma** [comment]
Well actually there it is on the release notes in big bold text, which I should have looked at when I initially noticed the problem.

> -loader is no longer automatically added when resolving loaders
This was removed because it often lead to problems.
You can still opt-in to the old behavior with the resolveLoader.moduleExtensions configuration option.

**Comment by icflorescu** [comment]
@dkozma 
Had the same unexpected issue and incidentally found the same solution while upgrading from beta 25 to beta 26.
Can you please provide a link to the release notes you've mentioned?

**Comment by dkozma** [comment]
@icflorescu Sure - https://github.com/webpack/webpack/releases/tag/v2.1.0-beta.26

**Comment by sokra** [comment]
We will add a breaking change notice in the error text.

**Comment by mattdemps** [comment]
Since the release notes don't have an explicit example of the **resolveLoader.moduleExtensions** config, this might help others searching on this.

Adding this to your config will allow loaders to continue resolving -loader as it worked before:

```
resolveLoader.moduleExtensions = ['-loader']
```

**Comment by Judahmeek** [comment]
Can someone provide me with some examples of the problems that automatically appending `-loader` led to?
