### ISSUE TITLE
Typing "-display-error-details" instead of "--display-error-details" causes weirdness

### ISSUE THREAD

**Issue by gpascale** [webpack/webpack#3291]
**I'm submitting a bug report**

**Webpack version:**
1.13.3

**Please tell us about your environment:**
OSX 10.10

**Current behavior:**
Somehow, using the invalid flag "-display-error-details" (single dash) causes (perhaps among other things), the optimize-minimize flag to be set to true. I was tearing my hair out trying to figure out why UglifyJS kept running on my code despite my never including that plugin

**Expected/desired behavior:**
The flag should do nothing or produce a warning/error that it is an invalid option.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.** 
"webpack --config <your config file> -display-error-details"

* **What is the expected behavior?**
Do nothing or produce an error message

* **What is the motivation / use case for changing the behavior?**
This is an easy mistake to make and the results are very confusing. I spent hours figuring out why Uglify was running.
 
* **Browser:**
N/A
 
* **Language:**
ES6

**Comment by Kovensky** [comment]
`yargs` is probably parsing `-display` as `-d -i -s -p -l -a -y` (getopt does it too) 😄

**Comment by SpaceK33z** [comment]
Note that he uses webpack v1, which doesn't use yargs. I'm pretty sure the problem has been fixed in webpack v2 when we switched to yargs. yargs is way more strict with invalid parameters.
