### ISSUE TITLE
npm linked dependencies do not get filtered through loaders correctly

### ISSUE THREAD

**Issue by jbcpollak** [webpack/webpack#3292]
**I'm submitting a bug report**

**Webpack version:**

    "webpack": "1.13.3",

**Please tell us about your environment:**
OSX 10.12.1
Node 6.2.1
NPM 3.10.5

**Current behavior:**

NPM linked node_modules do not get filtered through loaders correctly, but when `installed` they do.

**Expected/desired behavior:**

linked modules should be processed as if they were normally installed

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.** 

Have a webpack project, say `project_a`
Have a `project_b`

Both projects use ES6 syntax.

In webpack.config.js have this loader configured:

```js
{
	test: /\.js$/,
	include: [
		libPath,
		path.join(nodeModulesPath, 'project_b', 'lib')
	],
	loader: 'ng-annotate?add=true!babel?' +
	JSON.stringify(babelSettings) // eslint-disable-line angular/json-functions
}
```

This setup will work fine when you do:

`npm install project_b`

but will fail with:

`npm link ../project_b`

because babel doesn't get run on project_b.

I suspect the problem is that somewhere the symlink is being unwound to a relative path, which doesn't match `path.join(nodeModulesPath, 'project_b', 'lib')`.

For example, I see the following path in my list of modules when I run webpack while linked:

`   [15] ../project_b/lib/index.js 1.54 kB {0} [built]`

Compared to when installed:

`   [15] ./~/project_b/lib/index.js 2.43 kB {0} [built]

* **What is the expected behavior?**

Behavior should be the same regardless of how a module is installed.

**Comment by sokra** [comment]
> I suspect the problem is that somewhere the symlink is being unwound to a relative path, which doesn't match path.join(nodeModulesPath, 'project_b', 'lib').

Yep. You could try `fs.realpath`, or disable symlink resolving with `resolve.symlinks = false`

**Comment by jbcpollak** [comment]
@sokra shouldn't resolving symlinks be off by default for node_modules? (To avoid this problem?)

@tonygaetani can you try that ^^^ ?

**Comment by sokra** [comment]
webpack do follow the Node.js resolving spec. So it behaves like Node.js here.

**Comment by jbcpollak** [comment]
Ok, that makes sense I guess. Still seems awkward to have this type of
unexpected result but I guess it's an edge case.

We will try the work around.

On Tue, Nov 15, 2016, 3:14 AM Tobias Koppers <notifications@github.com>
wrote:

webpack do follow the Node.js resolving spec. So it behaves like Node.js
here.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/webpack/webpack/issues/3292#issuecomment-260575524>,
or mute
the thread

**Comment by tonygaetani** [comment]
@sokra the workaround works:

`fs.realpathSync(path.join(nodeModulesPath, 'project_b', 'lib'))`
