### ISSUE TITLE
__webpack_require__(...) is not a function, when use with extract-text-webpack-plugin and happypack

### ISSUE THREAD

**Issue by frankLife** [webpack/webpack#3295]
**cli screenshot:**

[![](https://camo.githubusercontent.com/52ec0e97b0e179a7b35e63c213bad236079b5035/687474703a2f2f67772e616c6963646e2e636f6d2f7466732f5442315277614f4e705858585858525870585858585858585858582d313138302d3238322e706e67)](https://camo.githubusercontent.com/52ec0e97b0e179a7b35e63c213bad236079b5035/687474703a2f2f67772e616c6963646e2e636f6d2f7466732f5442315277614f4e705858585858525870585858585858585858582d313138302d3238322e706e67)

**source screenshot:**

[![](https://camo.githubusercontent.com/f83917920a6cf8c7c76e5982333d99c3589c4a92/687474703a2f2f67772e616c6963646e2e636f6d2f7466732f5442316d326b764f5858585858614b6170585858585858585858582d313438302d3433332e706e67)](https://camo.githubusercontent.com/f83917920a6cf8c7c76e5982333d99c3589c4a92/687474703a2f2f67772e616c6963646e2e636f6d2f7466732f5442316d326b764f5858585858614b6170585858585858585858582d313438302d3433332e706e67)

In the callback of `runAsChild`,  the content of css-loader's css-base.js moduele  is empty, So it would fail.

**Webpack version:**
1.10.x

**Please tell us about your environment:**
 Linux 

**Current behavior:**
build fail

**Expected/desired behavior:**
build success

**Comment by SpaceK33z** [comment]
And this only happens with happypack? If so, I don't think we can do much about this here...

**Comment by bebraw** [comment]
Can you report this to the happypack project? You can likely isolate the issue there and then come with a more specific report if it's a webpack core bug. Thanks.
