### ISSUE TITLE
To optimize loading of locale data files so that these files can be bundles separately in chunks(webpack)

### ISSUE THREAD

**Issue by piyaa** [webpack/webpack#3300]
I'm trying to load the translation of the lang that the user selected(i.e-japanese).I'm using the require.ensure to optimize loading of locale data files so that these files can be bundles separately in chunks in webpack instead of one big bundle. I had something like:

```js
require.ensure([], function() {
       let a = (require("react-intl/locale-data/"+locale));
       addLocaleData([...a]);
});
```
but this gives me error:
`[React Intl] Missing locale data for locale: "ja". Using default locale: "en" as fallback`.

However if I do:

```js
let a = (require("react-intl/locale-data/"+locale));
require.ensure([], function() {
       addLocaleData([...a]);
});
```
it works and no error.Any idea what could be going on?

**Webpack version:**
1.10.x/2.x

**Please tell us about your environment:**
OSX 10.x

**Comment by Kovensky** [comment]
When you use `require.ensure`, you need to use the function that the callback receives to require:

```js
require.ensure([], function(req/*uire*/) {
  let a = req/*uire*/("react-intl/locale-data/" + locale)
})
```

**Comment by piyaa** [comment]
So this what i tried with no luck:(
```
require.ensure([], function(require) {
    addLocaleData(require("react-intl/locale-data/"+ locale));
  });
```
still throws same error
