### ISSUE TITLE
Cannot find loader module when using module loaders(plural) vs loader syntax

### ISSUE THREAD

**Issue by oste** [webpack/webpack#3309]
**I'm submitting a bug report**

**Webpack version:**
1.10.x

**Please tell us about your environment:**
OSX 10.x

**Current behavior:**
When using the following module loaders config

```
    module: {
        loaders: [
            {
                test: /\.scss$/,
                loaders: ["style", "css", "sass"]
            }
        ]
    }
```

I am getting this error

```style.scss:4Uncaught Error: Cannot find module "!!./../js/node_modules/css/index.js!./../../node_modules/sass-loader/index.js!./style.scss"```

**Expected/desired behavior:**

If I use the following syntax things work as expected:
```loader: "style-loader!css-loader!sass-loader"```

* **Browser:** all
 
* **Language:** ES6

**Comment by oste** [comment]
It is interesting that removing ```-loader``` also provides the same error. For example: 
```loader: "styler!css!sass"```

**Comment by sokra** [comment]
The problem is `css` vs. `css-loader`. Use the later one.

**Comment by oste** [comment]
Thanks @sokra I thought i tried that. This works: ```loaders: ["style-loader", "css-loader", "sass-loader"]``` as does this ```loaders: ["style", "css-loader", "sass"]```
