### ISSUE TITLE
Best practices for the Provide Plugin

### ISSUE THREAD

**Issue by dschissler** [webpack/webpack#331]
I'm considering adding Backbone and Marionette to the provide plugin configuration.  Has anyone gone done this route and are there any major issues involved in that?  I'm thinking that Backbone and Marionette will be used in nearly every single file (currently 116) and that it will be nice to not need to look at the requires at the top.

**Comment by mpoisot** [comment]
Is there a way to limit the abuse of provide_plugin to certain folders? I'd like to have Marionette and Backbone be available to everything in the models and views folders, for example.
