### ISSUE TITLE
How to make a Webpack pitching loader that adds files next to source files? 

### ISSUE THREAD

**Issue by mohsen1** [webpack/webpack#3311]
[Typed CSS Modules](https://github.com/Quramy/typed-css-modules) makes a `.d.ts` file next to CSS files so when you import that CSS file using `import` syntax in TypeScript, you get class names that are statically typed.

I'm trying to make a loader that uses this module and generated those `.d.ts` files right before TypeScript compiler is collecting files. I figured this should be done in pitching phase but don't know how to add a new file to memory-fs or actual fs so the TypeScript compiler sees them. Emitting those files in pitching phase doesn't work because those files are written **after** compilation is done. 

How can a pitching loader add new files to memory-fs the way next loaders see them?

**Comment by mohsen1** [comment]
This is what I came up with: in a pitching loader, create the `css.d.ts` file and add it to dependencies. Sadly it crashes the webpack process. 

```js
var DtsCreator = require('typed-css-modules');

module.exports = function () { };

module.exports.pitch = function () {
    var callback = this.async();

    var creator = new DtsCreator();

    creator.create(this.resourcePath).then(content => {

        // Write to disk
        content.writeFile().then(() => {
            this.addDependency(this.resourcePath);
            this.addDependency(this.resourcePath + '.d.ts');
            callback(null);
        });
    });
};
```

Any recommendation is appreciated.

**Comment by zhaoshengjun** [comment]
I am not familiar with `typed css module`. Could you make a simplest repo so I can take a look at it?

Thanks!

**Comment by mohsen1** [comment]
There is a loader for it and we are trying to make it work like I described:

https://github.com/olegstepura/typed-css-modules-loader/pull/8

**Comment by TheLarkInn** [comment]
@sokra is this a feature not yet created for Pitching loaders?

**Comment by sokra** [comment]
The loader phases are per module. So this won't work.

Assuming a.ts imports b.css:

a.ts pitch -> a.ts normal -> a.ts parsing -> dependency to b.css detected -> b.css pitch -> b.css normal -> ...

**Comment by mohsen1** [comment]
Is it possible for a loader to create new files in Webpack?
