### ISSUE TITLE
[Help Wanted][RFC] Spike research on Splittable 

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack#3313]
After webpack v2 releases from beta, one of our first priorities is introducing optimizations that include techniques like rollup as well as general purpose optimizer similar to babili (using program flow analysis except supporting nth level depth in commonjs, and, and es6 tree shaking and dead code elimination).

@cramforce just created a library called [splittable](http://github.com/Cramforce/splittable) which uses Google Closure Compiler to perform this program flow analysis based on a dependency graph created via wrapping browserify. 

On paper he claims the optimization wins are huge. 

## Idea
Can we "kill two birds with one stone" by implementing this kind of optimization tool to webpack.

## Challenges
* Since this tool wraps browserify, we would want to take and either contribute to splittable to decouple the logic so that it could take any dep graph (such as a custom one created from webpack) and perform these optimizations. 

* the tool leverages the Java based gcc and not the JavaScript closure compiler, we would also need to ensure feature parity with the JS based one so that the tool could perform without the user needing the Java runtime installed. 

* it appears that there is mention of a native closure compiler code splitting which I do not know much about, however I would imagine we would not need the native splitting feature? Or at least determine the benefits.

**Comment by cramforce** [comment]
I'm working with the CC team to get the JS version working (and when it does I'm just planning to switch to it).

Switching to a different dep graph source should be easy.

"Native code splitting" refers to the fact that CC is aware of bundles and bundle boundaries. This is essential for full program analysis to work in the presence of code splitting. 

I'd like to make a few points:

- Dead code elimination (sometimes called tree shaking) is in no way limited to ES6 modules. It also works with CommonJS modules and it works with non-exported functions, variables and other statements.
- It also supports property renaming and many, many other optimizations such as inlining and de-virtualization of methods (the list is super, super long).
- This also supports "cross bundle code motion". This is similar to dead code elimination but aware of code splitting. Imaging module A exports functions X and Y. Modules B and C import A. A calls X and B calls Y. With closure compiler, function X gets moved into the bundle of A, while function Y gets moved into the bundle of B.

**Comment by TheLarkInn** [comment]
> This also supports "cross bundle code motion". This is similar to dead code elimination but aware of code splitting. Imaging module A exports functions X and Y. Modules B and C import A. A calls X and B calls Y. With closure compiler, function X gets moved into the bundle of A, while function Y gets moved into the bundle of B.

Wow super interesting. So let's say webpack splits code and creates n bundles do you pass the n bundles to the tool to utilize this feature?

**Comment by cramforce** [comment]
Yeah, closure compiler supports compiling N bundles as one compilation unit, but it doesn't support code splitting itself (or rather it doesn't know how to make N bundles from 1 big one). The API is simply "Put these files in this order into this bundle. This bundles depends on X", "Put these files in this order into this bundle. This bundles depends on Y", and so forth.

The closure compiler docs themselves call this `–module`. This was named long before CommonJS modules were a thing. Whenever you read their docs do `s/module/bundle` :)

**Comment by TheLarkInn** [comment]
So since webpack build chunks already out of these files and uses is module wrapper, we could simple pass these chunks to cc to optimize with -module

**Comment by Kovensky** [comment]
The part that, I believe, will trip up any static code analysis is that webpack's bundling works by putting module exports in a big object (`__webpack_require__.c = installedModules`), and requesting modules by indirectly reading from the big object (or running the module, also found by looking in a big object `__webpack_require__.m = modules`, to produce the exports).

If, say, a module has a `__webpack_require__(3)`, how can a static analyzer tell which of the modules in the bundle will be called? Even harder would be `__webpack_require__(5)('./' + str)` as generated by the context template. What about `__webpack_require__.e(1).then(__webpack_require__.bind(null, 9))`, generated by `System.import`?
