### ISSUE TITLE
require.ensure with callback generates bad code after compilation

### ISSUE THREAD

**Issue by jkanczler** [webpack/webpack#3315]
**I'm submitting a bug report**
**Webpack version:**
1.13.2

**Please tell us about your environment:**
Windows 7

**Current behavior:**
For the following code snippet
```
        require.ensure(
            ['./module'],
            (syncedRequire) => {
                doSomething(syncedRequire('./module'));
            },
            'module');
```
webpack generates this:
```
	        __webpack_require__.e/* nsure */(1, function (syncedRequire) {
	            doSomething(syncedRequire('./module'));
	        });
```

This is invalid, because syncedRequire will be the __webpack_require__ function, and that function expects a number instead of a string. For the string it'll fail.

**Expected/desired behavior:**
One solution is to remove the callback argument that won't be required anyway, if you're implementing the following code:
```
        require.ensure(
            ['./module'],
            () => {
                doSomething(require('./module'));
            },
            'module');
```
Webpack generates this:
```
	        __webpack_require__.e/* nsure */(1, function () {
	            doSomething(__webpack_require__(2));
	        });
```

You can see, the require('./module') call is now compiled into __webpack_require__(2) and now everything will work correctly.

Other solution is that the callback will receive a function that can handle the string as an input parameter. That means:
```
	        __webpack_require__.e/* nsure */(1, function (syncedRequire) {
	            doSomething(syncedRequire('./module'));
	        });
```
in this code webpack has to pass a different function than __webpack_require__ into this callback. So the syncedRequire shouldn't be the __webpack_require__ function. Instead of that it has to be capable to handle the string input parameter.

* **Browser:** [all]
* **Language:** [all] 

Feel free to close this bug anyway, if it's fixed in webpack version 2, as the workaround basically just to write require inside the function and not expecting any parameter in the callback function.

So workaround again:
```
        require.ensure(
            ['./module'],
            () => {
                doSomething(require('./module'));
            },
            'module');
```

**Comment by sokra** [comment]
Seem like arrow functions are not handled properly...

**Comment by Kovensky** [comment]
This seems to affect regular functions too -- it seems that the argument is not treated as a rename (or shadow) of `require`?

**Comment by jkanczler** [comment]
Yes, @Kovensky is right. It happens with regular functions too. I've created a [git repository](https://github.com/jkanczler/webpack-require-ensure-bug) to show this. Webpack won't handle require as a shadow inside the callback, but actually that's why it is working. If you're using different parameter name, then it'll start work as designed, but then `__webpack_require__` function will fail, as it just can handle numbers as arguments, and can't do anything with a string parameter.

```
// This is not working, generating wrong code, as syncedRequire will be compiled into the same.
require.ensure(
    ['./module'],
    function (syncedRequire) {
        syncedRequire('./module').sayHello();
    });
```
compiled to
```
	// This is not working, generating wrong code, as syncedRequire will be compiled into the same.
	__webpack_require__.e/* nsure */(1/* duplicate */, function (syncedRequire) {
	        syncedRequire('./module').sayHello();
	    });
```
will fail because:
```
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
```
require function expects a moduleId as number, and not as a string.

**Comment by TheLarkInn** [comment]
Would you be willing to reproduce this in webpack@2.1.0-beat.27? We'd like to confirm if its an issue and if it is then we can get a fix in.

**Comment by Kovensky** [comment]
@TheLarkInn I encountered this while writing the tests for #3297 (```function (req) { req(`./abc/${"abc"}Test`) }``` would call `__webpack_require__` with the full string as argument instead of calling the context's require with `./${"abc"}Test`)

**Comment by sokra** [comment]
Ok it looks like a real bug. But as the workaround is simple, it's rar and `require.ensure` is superseeded anyway, it's low prioritity
