### ISSUE TITLE
LoaderOptionsPlugin not found

### ISSUE THREAD

**Issue by jeusdi** [webpack/webpack#3318]
**I'm submitting a bug report**

I'm using this configuration:

    new LoaderOptionsPlugin({
          options: {
            /**
            * Static analysis linter for TypeScript advanced options configuration
            * Description: An extensible linter for the TypeScript language.
            *
            * See: https://github.com/wbuchwalter/tslint-loader
            */
            tslint: {
              emitErrors: false,
              failOnHint: false,
              resourcePath: 'src'
            },
          }
       })

`webpack` is telling me that: 

    new LoaderOptionsPlugin({
    ^
    ReferenceError: LoaderOptionsPlugin is not defined

I'm using webpack 2.1.0-beta.27 version and I've checked LoaderOptionsPlugin is under `node_modules/webpack...`

**Webpack version:**
2.1.0-beta.27

**Please tell us about your environment:**
Windows 10

**Comment by Kovensky** [comment]
`new webpack.LoaderOptionsPlugin`.

You should be able to give options to `tslint` with `options`, though. See https://webpack.js.org/configuration/module/#rule-options-rule-query

**Comment by SpaceK33z** [comment]
As @Kovensky said ^^.
