### ISSUE TITLE
string-replace-loader on postLoaders invalid on last version

### ISSUE THREAD

**Issue by jeusdi** [webpack/webpack#3319]
Up to now, I was using this configuration on my `webpack@2.1.0-beta.22`.

    postLoaders: [
        {
          test: /\.js$/,
          loader: 'string-replace-loader',
          query: {
            search: 'var sourceMappingUrl = extractSourceMappingUrl\\(cssText\\);',
            replace: 'var sourceMappingUrl = "";',
            flags: 'g'
          }
        }
      ]

 Now I've updated `webpack to 2.1.0-beta.27 and its `postLoaders` is not valit from now on.

Is there some guide to move this?

**Comment by Kovensky** [comment]
This was part of the big loaders change in `beta.23` and `beta.24`.

See https://github.com/webpack/webpack/releases/tag/v2.1.0-beta.23 for a summary; `beta.24` renamed the `"left"` / `"right"` options to `"pre"` / `"post"`.

**Comment by SpaceK33z** [comment]
Also checkout the [upgrade guide](https://webpack.js.org/guides/migrating/).
