### ISSUE TITLE
resolveLoader.alias does not handle loader query properly.

### ISSUE THREAD

**Issue by Strate** [webpack/webpack#3320]
**I'm submitting a bug report**

**Webpack version:**
2.1.0-beta.27 

**Please tell us about your environment:**
Linux

**Current behavior:**
Trying to alias from `loader` to `loader?query` broken

**Expected/desired behavior:**
If i `require('loader!resource')`, when `loader` is aliased to `loader?query`, then require should be transformed to `require('loader?query!resource')`. As for now, webpack tries to resolve `loader?query` as path to js file with loader.

It is working in webpack 1.x branch. Is there any workarounds available?

**Comment by vladimir-tikhonov** [comment]
`loader?query` aliases work with webpack <= `2.1.0-beta.22`. It's broken in `2.1.0-beta.23` and above

**Comment by sokra** [comment]
make https://github.com/webpack/enhanced-resolve/blob/master/lib/AliasPlugin.js like https://github.com/webpack/enhanced-resolve/blob/v0.9.1/lib/ModuleAliasPlugin.js

**Comment by khagesh** [comment]
@sokra After going through files that you mentioned, I think I understand what needs to be done. My understanding is that we need to take `query` out from `alias` and also from `name` and then form a new request which explicitly passes `query` in new request that we create at [line #30](https://github.com/webpack/enhanced-resolve/blob/master/lib/AliasPlugin.js#L30) which should satisfy the requirements that you mentioned in comment [here](https://github.com/webpack/webpack/issues/1513#issuecomment-162828395) 

@TheLarkInn and @sokra If my understanding is correct, can I stab at it and come back with a PR, if no one else is working on it right now?

**Comment by sokra** [comment]
@TheLarkInn wanted to work on this.

**Comment by khagesh** [comment]
ok, let me know if you need any help on it. Thanks!

**Comment by TheLarkInn** [comment]
By all means feel free to open a PR. enhanced-resolve is my weakest lib for webpack so I wanted to tackle it but I struggled with some of the recursion I was seeing locally. If you can fix it before I can then I should learn enough out of seeing the fix.

**Comment by khagesh** [comment]
Sure, I will start work on it. I should have it ready in next 2 days. If it
fixes the issue, it will be my first open source project PR :). So, it will
be I who get to learn a lot.

**Comment by TheLarkInn** [comment]
@khagesh Sorry I beat you to it, (this is one of our last remaining issues for our RC Blocking release).

**Comment by TheLarkInn** [comment]
Relies first on webpack/enhnaced-resolve#51 merged, then #3445 merging.
