### ISSUE TITLE
Merge information from common.js to dev.js and prod.js

### ISSUE THREAD

**Issue by jeusdi** [webpack/webpack#3321]
I'm using webpack last version (2.1.0-beta.27). I've need to change some configuration parameters in order for ``webpack` to be able build artifacts.

After that, I would need to know to deal with an issue I had solved before (on previous versions).

I've three configuration files: 

* [webpack.common.js](https://gist.github.com/jeusdi/134e19006a6f8da06bf4123c35d8a8a7)
* [webpack.dev.js](https://gist.github.com/jeusdi/365e8cc433ef629d6246776dce0e3092)
* [webpack.prod.js](https://gist.github.com/jeusdi/919e6228b753cbe67f72edfd613a8c99)

I've defined a `METADATA` structure in order to store some information and it's feed on each configuration file (on [webpack.common.js](https://gist.github.com/jeusdi/134e19006a6f8da06bf4123c35d8a8a7), [webpack.dev.js](https://gist.github.com/jeusdi/365e8cc433ef629d6246776dce0e3092) and [webpack.prod.js](https://gist.github.com/jeusdi/919e6228b753cbe67f72edfd613a8c99)).

On [webpack.common.js](https://gist.github.com/jeusdi/134e19006a6f8da06bf4123c35d8a8a7) I initialize it:

    const METADATA = {
      title: 'User Platform',
      baseUrl: '/',
      isDevServer: helpers.isWebpackDevServer()
      ...
    };

Before having upgraded to `webpack` last version I used to set `METADATA` as a field on global configuration object on `webpack.common.js` file:

    module.exports = function(options) {
      return {
        metadata: METADATA,
        ...
      }
    }

From `webpack@2.1.0-beta.27` it's not allowed and I need to use `LoaderOptionsPlugin`:
    
    plugins: [
        new webpack.LoaderOptionsPlugin({
          options: {
            metadata: METADATA
          }
       })
    ]

The way I used to merge this `"metainfo"` structure information on [webpack.dev.js](https://gist.github.com/jeusdi/365e8cc433ef629d6246776dce0e3092) and [webpack.prod.js](https://gist.github.com/jeusdi/919e6228b753cbe67f72edfd613a8c99)) was:

    const ENV = process.env.ENV = process.env.NODE_ENV = 'development';
    const HOST = process.env.HOST || 'localhost';
    const PORT = process.env.PORT || 3000;
    const HMR = helpers.hasProcessFlag('hot');
    const METADATA = webpackMerge(commonConfig({env: ENV}).metadata, {
      host: HOST,
      port: PORT,
      ENV: ENV,
      HMR: HMR
    });

From now on, I don't quite figure out how to do this merge of information.

I hope I've explained so well.

**Comment by SpaceK33z** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template, or open a new issue.
