### ISSUE TITLE
HtmlWebPackPlugin is unable to resolve fields

### ISSUE THREAD

**Issue by jeusdi** [webpack/webpack#3322]
I've changed my configuration files in order to be able to use `webpack@2.1.0-beta.27`. After having changed some issues according to migration between `webpack@2.1.0-beta.22` and the last one something goes wrong according to something related to `HtmlWebPackPlugin`:

    plugins: [
        new HtmlWebpackPlugin({
            template: 'src/index.html',
            chunksSortMode: 'dependency'
        })
    ]

After having performed `webpack` command it seems that `HtmlWebPackPlugin` is unable to resolve some fields. `index.html` file:

    Html Webpack Plugin:
    <pre>
      TypeError: Cannot read property 'title' of undefined
      
      - index.html:77 
        D:/projects/living/user-platform/project/src/index.html:77:33
      
      - index.html:94 module.exports
        D:/projects/living/user-platform/project/src/index.html:94:3
      
      - index.js:255 
        [project]/[html-webpack-plugin]/index.js:255:16
      
      - util.js:16 tryCatcher
        [project]/[html-webpack-plugin]/[bluebird]/js/release/util.js:16:23
      
      - promise.js:510 Promise._settlePromiseFromHandler
        [project]/[html-webpack-plugin]/[bluebird]/js/release/promise.js:510:31
      
      - promise.js:567 Promise._settlePromise
        [project]/[html-webpack-plugin]/[bluebird]/js/release/promise.js:567:18
      
      - promise.js:604 Promise._settlePromiseCtx
        [project]/[html-webpack-plugin]/[bluebird]/js/release/promise.js:604:10
      
      - async.js:143 Async._drainQueue
        [project]/[html-webpack-plugin]/[bluebird]/js/release/async.js:143:12
      
      - async.js:148 Async._drainQueues
        [project]/[html-webpack-plugin]/[bluebird]/js/release/async.js:148:10
      
      - async.js:17 Immediate.Async.drainQueues
        [project]/[html-webpack-plugin]/[bluebird]/js/release/async.js:17:14
      
    </pre>

 * [src/index.html](https://gist.github.com/jeusdi/8a5b2d0892c808e9a31793fbe42dcb0d)
 * [webpack.common.js](https://gist.github.com/jeusdi/134e19006a6f8da06bf4123c35d8a8a7)
 * [webpack.dev.js](https://gist.github.com/jeusdi/365e8cc433ef629d6246776dce0e3092)
 * [webpack.prod.js](https://gist.github.com/jeusdi/919e6228b753cbe67f72edfd613a8c99)

**Comment by SpaceK33z** [comment]
This isn't at all related to the `webpack` package, but anyway: 

You're using `htmlWebpackPlugin.metadata`, but you should use `htmlWebpackPlugin.options`, like this: `<%-htmlWebpackPlugin.options.title%>`.

**Comment by SpaceK33z** [comment]
Closing this since it doesn't belong here. For further help, please ask on StackOverflow.

**Comment by jeusdi** [comment]
Sorry if I keep writting here. I posted a question on Stackoverflow and it's not been answered yet.

I keep failing to understand why are you suggesting me to get `tittle` field appending `options`.
Could you tell me where I've set the `options` parent?

**Comment by SpaceK33z** [comment]
The `options` parent is automatically added by htmlWebpackPlugin. It contains all properties from the `new HtmlWebpackPlugin({ ... })` object. In some of my projects I also set the title via the plugin, and `new HtmlWebpackPlugin({ title: 'foobar' })` in combination with `<%-htmlWebpackPlugin.options.title%>` works.

**Comment by jeusdi** [comment]
Yes it works now. I only wanted to know a bit about `options` parent field.
Thanks.
