### ISSUE TITLE
Webpack Angular2 does not work with node_modules

### ISSUE THREAD

**Issue by lukemadera** [webpack/webpack#3326]
**I'm submitting a bug report**
Webpack builds fine but Angular 2 throws an error in the browser. I've been working on this issue for days and there are numerous other similar reports. I can run the import fine if in the same repository but if packaged into a node_module dependency, it (sporadically) does not work. This is huge blocker, making any 3rd party Angular2 components unusuable.

`Uncaught Error: Unexpected value 'PLIconModule' imported by the module 'AppModule'(…)`

**Webpack version:**
1.10.x/2.x

**Please tell us about your environment:**
OSX 10.x

**Current behavior:**
Can not run app due to browser error.

**Expected/desired behavior:**
No error.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem along with a gist/jsbin of your webpack configuration.** 
Build an angular 2 component and try to import it from npm and build with webpack.

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**

 
* **Browser:** [all] 
 
* **Language:** [TypeScript X.X]

**Comment by Kovensky** [comment]
There's not much information to work with here, but from what I could tell by searching, most people having this issue are using either the default value of `resolve.modules`, or one with only `'node_modules'` in it.

The solution appears to be adding an entry at the end of `resolve.modules` with the `path.resolve()`d path to your project's `node_modules` folder, like [angular-cli does](https://github.com/angular/angular-cli/blob/master/packages/angular-cli/models/webpack-build-common.ts#L39), though it's not a great example as it also disables the regular `'node_modules'` resolution at the same time.

**Comment by lukemadera** [comment]
Thanks @Kovensky  - I've seen that advice and tried that (and many other proposed solutions). Perhaps I have the path wrong as it breaks things for me if I add it in..

Here's a demo project to clone and reproduce the issue.
https://github.com/lukemadera/ng2-webpack

Clone it, then `npm install` then `npm start` then load up `http://localhost:8091` in a browser.
You should see the issue I can't seem to get by..
`Uncaught Error: Unexpected value 'MyIconModule' imported by the module 'AppModule'(…)`

But if the library is in the same repository (rather than included by npm), it works fine:
https://github.com/lukemadera/ng2-component1

You can clone that one too and run `npm install`, `npm start` and go to `http://localhost:8090` and no error.

**Comment by nlubin-lv** [comment]
I am having the same issue here.

**Comment by meninjanho4788** [comment]
@lukemadera i see this project can setup webpack 2 + angular 2. It run very well
You can read it https://github.com/asadsahi/AspNetCoreSpa

**Comment by lukemadera** [comment]
Thanks @meninjanho4788 but my issue is with including another angular 2 repository, not with webpack 2 and angular 2 (I've got that working just fine).
