### ISSUE TITLE
Webpack's style loader extracts css file into inline style tag

### ISSUE THREAD

**Issue by folmert** [webpack/webpack#3329]
I've switched from including stylesheets the oldschool way:

    <link rel="stylesheet" href="./../css/main.css">

to Webpack approach:

    var css = require('./../css/main.css');
	
It works, but I don't like that it extracts the css from this file into inline <style> tag, because then it's harder to debug it in Dev Tools. For example I have no idea from which file and line these attributes are coming from:	
[![enter image description here][1]][1]

It doesn't matter if I use style-loader, css-loader or postcss-loader, result is always the same.
How can I move it to separate file or generate a source map that would point me to the source file? So when I inspect it Dev Tools it will look like this:

[![enter image description here][2]][2]

My `webpack.config.js`:

    var autoprefixer = require('autoprefixer');
    
    module.exports = {
        devtool: "css-loader?sourceMap",
        module:  {
            loaders: [
                {test: /\.(png|woff|woff2|eot|ttf|svg)$/, loader: 'url-loader?limit=100000'},
                {
                    test:   /\.css$/,
                    loader: "style-loader!css-loader!postcss-loader"
                }
            ]
        },
        entry:   [
            './static/js/app.js'
        ],
        output:  {
            filename: './static/js/bundle.js'
        },
        watch:   false,
        postcss: function () {
            return [autoprefixer];
        }
    };

My `app.js`:

    var $ = require('jquery');
    window.jQuery = $;
    window.$ = $;
    require('bootstrap-loader');
    
    module.exports = (function () {
        alert('IT WORKS!');
    });
    
    window.app = module.exports;
    var css = require('./../css/main.css');

  [1]: https://i.stack.imgur.com/zIizI.jpg
  [2]: https://i.stack.imgur.com/TkoYg.jpg

**Comment by SpaceK33z** [comment]
Our [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md) states that questions should be asked on [StackOverflow](https://stackoverflow.com/).

Also, if you Google a bit there are many articles about this. SurviveJS explains it well: http://survivejs.com/webpack/building-with-webpack/separating-css/

**Comment by gghnisan** [comment]
Hello.
I know that a lot of time has passed.
For a long time I could not find a solution to this problem.

[https://github.com/webpack-contrib/style-loader#source-maps](url)

![foto](https://user-images.githubusercontent.com/49828972/76150244-402b0980-60b9-11ea-9af5-4d777a561fa5.png)
