### ISSUE TITLE
Is it possible to reload the webpack,when I changed one of my required modules ?

### ISSUE THREAD

**Issue by mertyesin** [webpack/webpack#3330]
For example, I have 'A' folder in my root directory and I am requiring this A from another folder, let say B. Entering 'npm install' command in B. Folder A is coming to B's node_modules,as expected. I want also reload my webpack,when ı changed A folder files under the root, **not B's node_modules's A**. Thanks****

**Comment by SpaceK33z** [comment]
Our [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md) states that questions should be asked on [StackOverflow](https://stackoverflow.com/).
