### ISSUE TITLE
Don't work with Chrome Version 38 ._.

### ISSUE THREAD

**Issue by pierreneter** [webpack/webpack#3335]

**Comment by SpaceK33z** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template, or open a new issue.
