### ISSUE TITLE
mongoose can configure on dev-server?

### ISSUE THREAD

**Issue by wizardnet972** [webpack/webpack#3338]
Hi, can I configure mongoose with webpack-dev-server? if so where can i see an example please?
`mongoose.connect('mongodb://127.0.0.1:27017/chat');`

**Comment by jamesjieye** [comment]
I have an example with `webpack-dev-middleware` and `express`, not with `webpack-dev-server` directly. You can find it [here](https://github.com/jamesjieye/vue2-example/blob/master/build/dev-server.js).

**Comment by SpaceK33z** [comment]
Our [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md) states that questions should be asked on [StackOverflow](https://stackoverflow.com/).
