### ISSUE TITLE
Babel-loader doesn't work if parent folder is node_modules. Unexpected token (27:12) You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by cenkce** [webpack/webpack#3345]
Gives error : Unexpected token (27:12) You may need an appropriate loader to handle this file type.

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template, or open a new issue.

Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md).

**Comment by cenkce** [comment]
ok, sorry

**Comment by cenkce** [comment]
i solved with :

exclude: path.join(__dirname, '/node_modules'),
