### ISSUE TITLE
_webpack_require return an empty module object

### ISSUE THREAD

**Issue by MJ111** [webpack/webpack#3346]
**What is the current behavior?**
_webpack_require return an empty module object

**If the current behavior is a bug, please provide the steps to reproduce.**
https://gist.github.com/MJ111/28fcd66081f03cc52f87301e04cf1bbb

1. build with webpack.config.js
2. open index.html with browser

**What is the expected behavior?**
should return the 'a.js' object

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**

I'm using webpack 1.13.3

**Comment by sokra** [comment]
Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md).

**Comment by MJ111** [comment]
I thought it was bug.. sorry
