### ISSUE TITLE
pre loader incrementally parsing files to ts-loader, decreasing performance drastically

### ISSUE THREAD

**Issue by wpitallo** [webpack/webpack#3347]
Hi,

We have a project with the following stack, webpack 2.1.0-beta.27, ts-loader 1.2.2, typescript 2.0.10. and and we are also using string-replace-loader. 

The project has got quite large and since implementing typescript it has become paralyzingly slow. Vladimir Matveev from Microsoft (Typescript) was very helpful and had a look at the project and he reported the following:

At glance I’d say that problem is not in TypeScript compiler but rather in interaction between ts-loader and TypeScript language service and a few unfortunate details in implementation of ts-loader

From the high level TypeScript language service works in the following way:

First it asks the host to provide a list of root files that should be included in the program. Then it will built the program by building transitive closure of all files accessible from root files (via imports, tripleslash references etc). Result program can be used to asked semantic questions, get emit output etc and this program is valid as long as all files that contributed to the program remains unchanged. Once some file is modified language service will try to incrementally parse it and rebuild the program.

What is happening in this case:

ts-loader creates language service and populates it with the initial set of files read from disk. Here there will be plenty of files with placeholders in them that should be substituted by the string-replace-loader and based on this files language service will create initial version of the program. Then once string-replace-loader processes files they are fed to ts-loader. Since content of file after substitution does not match the initial content language service will drop existing program and will build a new one by walking all files and resolving modules and doing other things that don’t make process any faster. What is worse – every file that has placeholders in it will cause re-creation of the program (and this project plenty of them).

In addition to that it seems that ts-loader does not attempt to cache results of module resolution meaning that every time program is rebuild compiler has to repeat module resolution process for every file which is quite expensive.

So the question i guess is why does the string replace loader feed to the ts-loader in the pipe when the string-replace-loader is set as a pre loader? I would expect the string-replace-loader to process all the files before passing it to the ts-loader to create the language service and start the typescript compiler. Is there a way to force the string-replace-loader to fully process all files before feeding to the ts-loader?

My webpack config file looks as follows:

``` js
var config = {

  entry: {
    system: `./CodeScience.Client.Global/init/system.init.js`,
    systemMobile: `./references/references.styles.mobile.js`
  },
  devtool: '#eval-source-maps',
  output: {
    path: path.join(wwwPath),
    filename: '[name].[hash:6].js',
    chunkFilename: "[id].[hash:6].js"
  },
  devServer: {
    outputPath: path.join(wwwPath)
  },
  resolve: {
    modules: [
      path.resolve('./'),
      path.resolve('./node_modules'),
      path.resolve('./CodeScience.Client.Global/node_modules'),
      path.resolve('./CodeScience.Client.Global')
    ],
    extensions: ['.js', '.ts', '.html', '.scss']
  },
  module: {
    loaders: [
      {
        test: /\.(js|html|json|ts)$/,
        loader: 'string-replace-loader',
        enforce: 'pre',
        query: {
          multiple: [
            {search: "{{rootPath}}", replace: '', flags: 'g'},
            {search: "{{customHash}}", replace: customHash, flags: 'g'},
            {search: "{{imagePath}}", replace: systemConfig.imagePath, flags: 'g'},
            {search: "{{systemName}}", replace: systemConfig.systemName, flags: 'g'},
            {search: "{{SystemName}}", replace: systemConfig.SystemName, flags: 'g'},
            {search: "{{apiServiceBaseUri}}", replace: systemConfig.apiServiceBaseUri, flags: 'g'},
            {search: "{{apiService}}", replace: systemConfig.apiService, flags: 'g'},
            {search: "{{landingState}}", replace: systemConfig.landingState, flags: 'g'},
            {search: "{{notFoundRedirect}}", replace: systemConfig.notFoundRedirect, flags: 'g'},
            {search: "{{pageTitle}}", replace: systemConfig.pageTitle, flags: 'g'}
          ]
        }
      },{
        test: /\.(js)$/,
        exclude: /(node_modules|temp_scrips)/,
        loader: "babel-loader?presets[]=es2015"
      }, {
        test: /\.ts(x?)$/,
        exclude: /(node_modules|temp_scrips)/,
        loader: 'babel-loader?presets[]=es2015!ts-loader'
      }, {
        test: /\.(png|jpg|gif)$/,
        loader: 'file-loader?name=[path][name]-[hash:6].[ext]' // inline base64 URLs for <=10kb images, direct URLs for the rest*/
      }, {
        test: /\.(html|md)$/,
        loaders: ["html-loader?" + JSON.stringify({attrs: ["img:src", "img:ng-src"]})]
      }, {
        test: /\.(svg|woff|woff2|ttf|eot|ico|otf)?(\?v=[0-9]\.[0-9]\.[0-9])?$/,
        loader: 'file-loader?name=[path][name].[ext]'
        /*}, {
         test: /\.(png|jpg)$/,
         loader: 'file?name=[path][name]-[hash:6].[ext]' // inline base64 URLs for <=10kb images, direct URLs for the rest*/
      }, {
        test: /\.css$/,
        loader: extractTestPlugin.extract({ fallbackLoader: "style-loader", loader: "css-loader!autoprefixer"})
      }, {
        test: /\.scss$/,
        exclude: [/\.global\.scss$/],
        loaders: ['raw-loader', 'sass-loader']
      }, {
        test: /\.global\.scss$/,
        loaders: ['style-loader', 'css-loader', 'sass-loader']
      }, {
        test: /\.sass$/,
        loader: extractCSS.extract({ fallbackLoader:"style-loader", loader:"css-loader!sass-loader!autoprefixer"})
      }, {
        test: /\.less$/,
        loader: extractCSS.extract({ fallbackLoader:"style-loader", loader:"css-loader!less-loader"})
      }, {
        test: /\.json$/,
        exclude: /(node_modules)/,
        loader: "json-loader"
      }]
  },
  plugins: [
    // HtmlWebpackPlugin: Simplifies creation of HTML files to serve your webpack bundles : https://www.npmjs.com/package/html-webpack-plugin
    new BrowserSyncPlugin(
      // BrowserSync options
      {
        files: ["./**/*.html"],
        // browse to http://localhost:3000/ during development
        host: 'localhost',
        port: 3000,
        // proxy the Webpack Dev Server endpoint
        // (which should be serving on http://localhost:3100/)
        // through BrowserSync
        https: true,
        proxy: 'https://localhost:3100/'
      },
      // plugin options
      {
        // prevent BrowserSync from reloading the page
        // and let Webpack Dev Server take care of this
        reload: true
      }
    ),
    new HtmlWebpackPlugin({
      chunks: ['system'],
      filename: 'index.html',
      package: pkg,
      template: `./CodeScience.Client.Global/init/system.html`,
      commonFileName: '',
      systemConfig: systemConfig
    }),
    new ngAnnotatePlugin({
      add: true
      // other ng-annotate options here
    }),
    new extractCSS({ filename: "[name]." + customHash + ".css", disable: false, allChunks: true }),
    new copyWebpackPlugin([
      {
        from: 'global.distributions',
        to: 'distributions'
      }
    ])
  ]
};
```

**Comment by Kovensky** [comment]
Hm... webpack only sees the import requests (and thus the dependencies) after a file has gone through _all_ the loaders. This sounds tricky 😕

If the typescript service requested files through the webpack loading process, then webpack would certainly apply the string replace loader beforehand, but it also would apply the `ts-loader`, so the service would see the result javascript instead of typescript. This is kind of a similar situation as `css-loader` w.r.t. `@import` -- maybe the solution @sokra is working on in https://github.com/webpack/css-loader/pull/287#issuecomment-261269199 is applicable here.

**Comment by wpitallo** [comment]
shot thanks going to look into it

**Comment by wpitallo** [comment]
I tried adding pitch to the string-replace-loader, but it throws an error.

var _ = require('lodash');
var utils = require('loader-utils');

function processQuery(source, query) {
  if (!_.isUndefined(query.search) && !_.isUndefined(query.replace)) {
    if (!_.isUndefined(query.flags)) {
      if(query.search.toString().indexOf('/g') == -1) {
       //console.log(query.search + ':not found');
       query.search = new RegExp(query.search, query.flags);
      } else {
        //console.log(query.search);
        query.search = new RegExp(query.search);
      }
    }
    //console.log(source,query.search, query.replace);
    source = source.replace(query.search, query.replace);
  }
  return source;
}

module.exports = function (source) {
  this.cacheable();
  var query = utils.parseQuery(this.query);
  if (_.isArray(query.multiple)) {
    query.multiple.forEach(function (subquery) {
      source = processQuery(source, subquery);
    });
  } else {
    source = processQuery(source, query);
  }
  return source;
};

**Comment by wpitallo** [comment]
In webpack and webpack-dev-server is there a way to access the files (not at the source) but hopefully a cached copy before they enter the webpack pipe? This way i may be possible to run the string-replace just on these files and then remove the string replace loader from webpack?

**Comment by TheLarkInn** [comment]
any reason for not trying out awesome-typescript-loader? It has some speed enhancements like deferring type checking until transpile is finished from loader step.

**Comment by wpitallo** [comment]
I found this code below in the ts-loader, and setting the option transpileOnly: true seems to have fixed the issue :) , not sure what are the implications of setting transpileOnly to true is though?

function makeOptions(loader) {
var queryOptions = loaderUtils.parseQuery(loader.query);
var configFileOptions = loader.options.ts || {};
var options = objectAssign({}, {
silent: false,
logLevel: 'INFO',
logInfoToStdOut: false,
instance: 'default',
compiler: 'typescript',
configFileName: 'tsconfig.json',
transpileOnly: true,
visualStudioErrorFormat: false,
compilerOptions: {},
appendTsSuffixTo: []
}, configFileOptions, queryOptions);
options.ignoreDiagnostics = arrify(options.ignoreDiagnostics).map(Number);
options.logLevel = options.logLevel.toUpperCase();
// differentiate the TypeScript instance based on the webpack instance
var webpackIndex = webpackInstances.indexOf(loader._compiler);
if (webpackIndex === -1) {
webpackIndex = webpackInstances.push(loader.compiler) - 1;
}
options.instance = webpackIndex + '' + options.instance;
return options;
}
