### ISSUE TITLE
Source map files missing from webpack:// after a save and watch kicking in.

### ISSUE THREAD

**Issue by richtera** [webpack/webpack#3353]
Just upgraded. It could be a settings thing, but it just started.

**Do you want to request a *feature* or report a *bug*?**
Seems to be a bug

**What is the current behavior?**
Initial startup the webpack-dev-server and loading the system everything works fine. The webpack:// shows all the sources and I can debug.
Then updating a file and causing hmr to kick in results on just the uploaded file to show in webpack://.

**If the current behavior is a bug, please provide the steps to reproduce.**
See above.

**What is the expected behavior?**
It used to replace the new file but keep all the other files in webpack://

**If this is a feature request, what is motivation or use case for changing the behavior?**
Something changed and I don't know what. Restarting the server each time a file is modified will make it work one more time.

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**
I am using node 6.7 and have not changed this between the time this was working and is now broken.

**Comment by richtera** [comment]
This might shed some light.... I see this every single time a file updates now where I only saw it sometimes previously:
```javascript
[WDS] App updated. Recompiling...
raven.js:80 [WDS] App updated. Recompiling...
raven.js:80 [WDS] App updated. Recompiling...
raven.js:80 [WDS] App hot update...
raven.js:80 [WDS] App hot update...
raven.js:80 [HMR] Checking for updates on the server...
raven.js:80 [HMR] Cannot apply update. Need to do a full reload!a.(anonymous function) @ raven.js:80(anonymous function) @ dev-server.js:18hotApply @ bootstrap 87416e5…:388hotUpdateDownloaded @ bootstrap 87416e5…:301hotAddUpdateChunk @ bootstrap 87416e5…:281webpackHotUpdateCallback @ bootstrap 87416e5…:3(anonymous function) @ 0.87416e5….hot-update.js:1
raven.js:80 [HMR] Error: Aborted because 1154 is not accepted
    at hotApply (http://localhost:3000/scripts/app.js:389:31)
    at hotUpdateDownloaded (http://localhost:3000/scripts/app.js:302:13)
    at hotAddUpdateChunk (http://localhost:3000/scripts/app.js:282:13)
    at webpackHotUpdateCallback (http://localhost:3000/scripts/app.js:4:12)
    at http://localhost:3000/0.87416e5dbdfd8c3a3127.hot-update.js:1:1a.(anonymous function) @ raven.js:80(anonymous function) @ dev-server.js:19hotApply @ bootstrap 87416e5…:388hotUpdateDownloaded @ bootstrap 87416e5…:301hotAddUpdateChunk @ bootstrap 87416e5…:281webpackHotUpdateCallback @ bootstrap 87416e5…:3(anonymous function) @ 0.87416e5….hot-update.js:1
app.js:8380[HMR] Waiting for update signal from WDS...
```

**Comment by richtera** [comment]
Just in case I re-tested removing raven but it's behaving the same way.

**Comment by richtera** [comment]
Ah never mind.. Got it. When compiling source maps to one file in the build step you need to special case not to include sourceMapFilename in the debug case. This is almost like a bug then; I think webpack-dev-server should ignore this key.

**Comment by SpaceK33z** [comment]
What do you mean with "compiling source maps to one file"? How do you do this?

Note that webpack-dev-server doesn't even "know" about source maps, so it is certainly not at fault here.

**Comment by richtera** [comment]
If you set the sourceMapFilename in the output section then it will cause webpack-dev-server to send all it's sourcemaps as one file and attempt to replace that one file during an update. This will leave all the other sourcemaps deleted. Removing sourceMapFilename property it reverted back to function normally.

**Comment by richtera** [comment]
Closing. It was a long time ago and I have not seen this again. It was some kind of problem with the hot reload pipeline.
