### ISSUE TITLE
Show warning when loader is applied multiple times

### ISSUE THREAD

**Issue by SpaceK33z** [webpack/webpack#3359]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**

When a loader is applied multiple times, you'll often get a really cryptic error message.

**If the current behavior is a bug, please provide the steps to reproduce.**

For instance, with json-loader. Configure it with require: `require('json-loader!./foo.json')`, then also configure it in your webpack config:

```js
test: /\.json$/,
loader: 'json-loader'
```

If you configure json-loader twice as above, you'll get the following error message:

```
Module build failed: SyntaxError: Unexpected token m
    at Object.parse (native)
    at Object.module.exports (/Users/me/my-project/node_modules/json-loader/index.js:7:48)
```

**What is the expected behavior?**

I would expect webpack to give a clear warning or error message saying "hey, you're applying a loader multiple times, don't do that man!"

**If this is a feature request, what is motivation or use case for changing the behavior?**

The current exception is very unclear, and users don't know what they should do if they get the exception. As a result, we need to explain this again and again in the loader repo's.

See https://github.com/webpack/json-loader/issues/10, https://github.com/webpack/json-loader/issues/13, https://github.com/webpack/json-loader/issues/33#issuecomment-261766974, https://github.com/webpack/json-loader/issues/33#issuecomment-262465391

**Comment by jhnns** [comment]
That makes sense 👍

**Comment by jdmota** [comment]
Just ran into this issue. A warning would be very useful.

**Comment by abhishek71994** [comment]
Ummm.. Shall I take this up as a first-time-contributor to this repo?

**Comment by evilebottnawi** [comment]
@abaracedo PR welcome!

**Comment by raydot** [comment]
I'm looking right at the source code with this exact same problem... when I'll finish my project I'll circle back and try to contribute too.

**Comment by edmorley** [comment]
Two PRs that attempted this have been closed (#3572 and #4106) - does that mean this issue is wontfix? If so, perhaps it would be best to close this issue so more people don't continue to spend time on it?

**Comment by abhinavsingi** [comment]
According to @sokra on both the prs that were closed (https://github.com/webpack/webpack/pull/3572 and https://github.com/webpack/webpack/pull/4106):

1. It may sometime be desirable to have same loader applied more than once
2. It's not that big a problem

**Comment by SpaceK33z** [comment]
Thanks for clarifying @abhinavsingi, closing the issue.
