### ISSUE TITLE
Feature Request: "forked outputs"/"Multi Define"

### ISSUE THREAD

**Issue by donaldpipowitch** [webpack/webpack#3366]
**Do you want to request a *feature* or report a *bug*?**

A *feature*.

**What is the current behavior?**

Say I'm a library author. I use TypeScript 2.0 and eventually need to process my compiled TS files with Babel to get `async/await` and I also have some custom loader, because I need to replace some strings or something else in my scripts. My loader pipeline looks like this:

```
{entry} → typescript-loader → babel-loader → some-custom-loader → {output}
```

Now I want to create a development and a production build. Currently I'd need to compile it twice (either _manually_ or as a `multi-compiler` config).

```
{entry} → [define plugin: development] → typescript-loader → babel-loader → some-custom-loader → {output}
{entry} → [define plugin: production] → typescript-loader → babel-loader → some-custom-loader → [uglify plugin] → {output}
```

Both compile steps are nearly identical. I only change some string from `'development'` to `'production'` and _after_ everything I minify my production build.

Imagine I do something similar for translations. Say my application needs to be internationalised for 30 languages. Now I have 30 builds and if I use development and productions builds I have 60 builds.

```
{entry} → [define plugin: development, de] → typescript-loader → babel-loader → some-custom-loader → {output}
{entry} → [define plugin: development, en] → typescript-loader → babel-loader → some-custom-loader → {output}
{entry} → [define plugin: development, fr] → typescript-loader → babel-loader → some-custom-loader → {output}
{entry} → [define plugin: production, de] → typescript-loader → babel-loader → some-custom-loader → [uglify plugin] → {output}
{entry} → [define plugin: production, en] → typescript-loader → babel-loader → some-custom-loader → [uglify plugin] → {output}
{entry} → [define plugin: production, fr] → typescript-loader → babel-loader → some-custom-loader → [uglify plugin] → {output}
...
```

Note that in both cases only _strings_ are changed. No logic or code is changed (given I don't use something like `import './foo/' + process.env.FOO`)). Only _after_ everything has run my minifying process removes code which is not necessary for production or maybe for a certain locale. But my source code runs through _all loaders_.

It would be nice, if we could have a define behaviour which _forks_ the build pipeline _just_ before the minifying process would do its job. It could look like this:

```
{entry} → typescript-loader → babel-loader → some-custom-loader → [multi define plugin: development, production]
   ...for development → {output}
   ...for production → [uglify plugin] → {output}
```

```
{entry} → typescript-loader → babel-loader → some-custom-loader → [multi define plugin: [development, production], [de, en]]
   ...for development and de → {output}
   ...for development and en → {output}
   ...for production and de → [uglify plugin] → {output}
   ...for production and en → [uglify plugin] → {output}
```

The configuration could look like this (pseudo code):

```
new MultiDefinePlugin({
  definitions: {
    'process.env.NODE_ENV': [ 'development', 'production' ],
    'process.env.LOCALE': [ 'de', 'en' ]
  },
  output: {
    // e.g. 'development/index.de.js', 'production/index.de.js' ...
    filename: '[process.env.NODE_ENV]/[name].[process.env.LOCALE].js'
  }
});
```

Note: As recommended here https://github.com/webpack/webpack/issues/1189#issuecomment-259919350 for "multi outputs", maybe `output` could be a callback returning an object instead of _just_ an object. It could look like this:

```
new MultiDefinePlugin({
  definitions: {
    'process.env.NODE_ENV': [ 'development', 'production' ],
    'process.env.LOCALE': [ 'de', 'en' ]
  },
  output(definition) {
    const isProduction = process.env.NODE_ENV === 'production';
    const minSuffix = isProduction ? '.min' : '';
    return {
      // e.g. 'index.de.js', 'index.de.min.js' ...
      filename: `[name].${definition.process.env.LOCALE}${minSuffix}.js`
    };
  }
});
```

**If this is a feature request, what is motivation or use case for changing the behavior?**

This isn't a big problem with generating just a development and a production build (I only added it for illustration, because it is more common), but if you create a lot of builds which just contain slightly different strings (e.g. for translations) this can become a real problem with performance, but especially for memory usage. **We currently hit a lot of out of memory issues in V8** when we try to build our projects with current solutions (mostly `multi-compiler` config). Examples and related discussions can be found here https://github.com/webpack/webpack/issues/1189#issuecomment-259129473, here https://github.com/webpack/webpack/issues/3294 and and it seems others want to use something similar to which can be found here https://github.com/facebookincubator/create-react-app/issues/1091.

**Comment by sokra** [comment]
Currently not so easy. You can try [parallel-webpack](https://github.com/trivago/parallel-webpack) as workaround. It also helps generating the combinations.
