### ISSUE TITLE
Why there is __webpack_require__ (null)

### ISSUE THREAD

**Issue by skiny2016** [webpack/webpack#3367]
**I use the webpack-dev-middleware plug-in package files can not run, the file has *__webpack_require__ (null)*. What is the cause of this problem?**

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template, or open a new issue.
