### ISSUE TITLE
Multiple entry  add a file all the files of the hash are changed

### ISSUE THREAD

**Issue by 3Q-** [webpack/webpack#3369]
my entry 
 entry: {
        'vendor': ['jquery', path.resolve(__dirname, 'common.js')],
        'scripts/index': [path.resolve(__dirname, 'demo.js')],
        'scripts/index1': [path.resolve(__dirname, 'demo.js')],
        'scripts/aest': ['scripts/aest']
    }

plugins :[
     new webpack.optimize.CommonsChunkPlugin({
        names: ['vendor', 'manifest'],
        minChunks: Infinity
    })
]

After compile
index1: webpackJsonp([1,0]
index : webpackJsonp([2,0]
vendor : webpackJsonp([3,0]
aest: webpackJsonp([4,0]

when  add a new entry    
 'scripts/index2': [path.resolve(__dirname, 'demo.js')],
index2: webpackJsonp([1,0]
index1 : webpackJsonp([2,0]
index : webpackJsonp([3,0]
vendor : webpackJsonp([4,0]
aest: webpackJsonp([5,0]
All the files of the chunkid have changed, the  file hash is also changed, the browser cache is not used now;
 How can i do now

**Comment by zhaoshengjun** [comment]
Try  `webpack-md5-hash` plugin.

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template, or open a new issue.

**Comment by AndrejsAbrickis** [comment]
Thanks @zhaoshengjun for advice to use webpack-md5-hash plugin. It took us some time to find out that Webpack generated different chunkhash on Mac OS vs Ubuntu. This plugin solved our issue.
