### ISSUE TITLE
How to compile symlink module

### ISSUE THREAD

**Issue by Tsouef** [webpack/webpack#3377]
Actually, I'm working with npm module. After symlink my custom module in my project, i can not compile it. 

This is my _webpack.config.js_: 

```
const PATHS = {
    app: path.join(__dirname, 'app'),
    style: path.join(__dirname, 'app', 'main.css'),
    build: path.join(__dirname, 'build')
};


const common = {
    entry: {
        app: PATHS.app,
        style: PATHS.style
    },
    output: {
        path: PATHS.build,
        filename: '[name].js',
        sourceMapFilename: '[file].map',
        devtoolModuleFilenameTemplate: 'webpack:///[resource-path]?[loaders]'
    },
    plugins: [
        new HtmlWebpackPlugin({
            title: 'Webpack Demo'
        })
    ],
    eslint: {
        failOnError: true
    },
    module: {
        preLoaders: [
            {
                test: /\.jsx?$/,
                loaders: [ 'eslint-loader' ],
                // Define an include so we check just the files we need
                include: PATHS.app
            }
        ],
        loaders: [
            {
                test: /\.js$/,
                exclude: /node_modules\/(?!my-modules)/,
                loader: 'babel-loader',
                query: {
                    cacheDirectory: true,
                    presets: [require.resolve('babel-preset-es2015')],
                }
            },
            {
                test: /\.json$/,
                loader: "json-loader"
            },
            {
                test: /\.scss$/,
                loaders: [ 'style', 'css', 'sass' ],
                include: PATHS.style
            }
        ]
    },
    resolve: {
        extensions: [ '', '.js', '.jsx', '.es6' ],
        fallback: path.join(__dirname, "node_modules")
    },
    resolveLoader: {
        fallback: path.join(__dirname, "node_modules")
    },
};

```

In my project's package.json, i have: 
```
{
  "name": "webpack-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "webpack-dev-server",
    "stats": "webpack --profile --json > stats.json",
    "test:lint": "eslint . --ext .js --ext .jsx || true",
    "build": "webpack"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "babel-core": "^6.18.2",
    "babel-eslint": "^7.1.1",
    "babel-loader": "^6.2.8",
    "babel-plugin-object-assign": "^1.2.1",
    "babel-plugin-transform-runtime": "^6.15.0",
    "babel-preset-es2015": "^6.18.0",
    "clean-webpack-plugin": "^0.1.14",
    "css-loader": "^0.25.0",
    "eslint": "^3.10.2",
    "eslint-loader": "^1.6.1",
    "eslint-plugin-react": "^6.7.1",
    "extract-text-webpack-plugin": "^1.0.1",
    "html-webpack-plugin": "^2.24.1",
    "json-loader": "^0.5.4",
    "markdown-loader": "^0.1.7",
    "purifycss-webpack-plugin": "^2.0.3",
    "style-loader": "^0.13.1",
    "webpack": "^1.13.3",
    "webpack-dev-server": "^1.16.2",
    "webpack-merge": "^0.15.0",
    "webpack-validator": "^2.2.9"
  },
  "dependencies": {
    "babel-polyfill": "^6.16.0",
    "babel-runtime": "^6.18.0",
    "stats-webpack-plugin": "^0.4.2"
  },
  "babel": {
    "presets": [
      "es2015"
    ]
  }
}

```

And in my module : 

```
{
  "name": "my-module",
  "version": "10.0",
  "main": "./dist/app.js",
  "description": "",
  "scripts": {
    "build": "babel src -d dist  --source-maps inline",
    "prepublish": "npm run build"
  },
  "dependencies": {
    "bean": "^1.0.15",
    "bonzo": "^2.0.0",
    "core-js": "^2.1.1",
    "domify": "^1.4.0"
  },
  "devDependencies": {
    "babel-cli": "^6.18.0",
    "babel-preset-es2015": "^6.18.0"
  },
  "babel": {
    "presets": [
      "es2015"
    ]
  }
}
```

Today, i have two builder, one for my project and the second for modules. 

So, if i compile my module, by npm run build, Webpack see the changement but if I change something in my src files, Webpack does nothing.

How can I watch my symlink module and compile it in my dist folder?

Thanks,

**Comment by Tsouef** [comment]
More information, so: 

I have my project and multiple npm modules.
```
|--Project
|  |--src
|  |--node_modules
|     |--moduleA
|     |-- jQuery
|     |-- loadash
|     |-- ...
|  |--webpack.config.js

|--MyModules
| |--ModuleA
    |--src
    |--dist
| |--ModuleB
| |-- ...
```

1- I do npm install on my project. 
2- npm goes to sinopia to download my module. 
3- I want to work on my module, I symlink ModuleA in my project: 

My module:
> npm link

My project:
> npm link ModuleA

4- I launch my webpack dev server

> npm run start

5- If I do a change in ModuleA. Nothing happens in my builder.   But if I do : 

> babel src -d dist  --source-maps inline

Webpack will see the change. Is it possible for Webpack to watch directly my src in my symlink module? 

Thanks,

**Comment by neronmoon** [comment]
+1 here!

**Comment by zeachco** [comment]
+1

**Comment by mgmorcos** [comment]
+1

**Comment by mike88ua** [comment]
+1

**Comment by Igor4uk** [comment]
+1

**Comment by prihodkoserzh** [comment]
+1

**Comment by ArTefT** [comment]
+1

**Comment by gotis83** [comment]
+1

**Comment by aivko** [comment]
+1

**Comment by zeachco** [comment]
since I had the same situations as you but with many linked modules, I ended up with using `include: ['src', 'my-moduleA', 'my-moduleB', ...]` something you could do to automate this is create an array containing your webpack entries, then push the list of your package dependencies filtered with the ones that are symlinks (haven't tested on windows but works on *nix systems)
quickly it could look like this:
```javascript
const pkg = require('../package.json');
const getSymLinks = dep => fs.lstatSync(path.join(process.cwd(), 'node_modules', dep).isSymbolicLink();
const linkedDependencies = pkg.devDependencies.concat(pkg.dependencies).filter(getSymLinks);
// ... and in your loader ...
   includes: ['src', 'assets', ...linkedDependencies],
```
// dependencies now contains the list of all symlink in node_modules

**Comment by songer8** [comment]
+1

**Comment by joaoreynolds** [comment]
+1

**Comment by cristian-eriomenco** [comment]
In your dependency you have the entry point being under **dist**:
`{
  "name": "my-module",
  "version": "10.0",
  "main": "./**dist**/app.js",`

But **dist** is missing of course because it will be created after the transpilation step. So your options are either to point at source (but then change it back...) which is not ideal.
Or you could use webpack `resolve.alias` like this:
`
  resolve: {
       .......
       alias: {
            "my-module": helpers.root("node_modules/my-module/**src/index.js**")
        }`

helpers.root just gets the root directory, otherwise you might resolve from the wrong folder.

This will essentially bypass the entry point of your library defined in package.json, and will use the one defined in alias instead.

**Comment by uptickr** [comment]
@cristian-eriomenco could you share the **helpers.root** function? Thanks.

**Comment by cleverettgirl** [comment]
+1

**Comment by mokus** [comment]
+1

**Comment by vankop** [comment]
Should work with `webpack@latest` (see https://webpack.js.org/configuration/resolve/#resolvesymlinks). Feel free to report new issue with reproducible repo.
