### ISSUE TITLE
Circular dependencies in v2

### ISSUE THREAD

**Issue by gustavohenke** [webpack/webpack#3382]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
Modules have no exports when they are circularly imported.

In the example given below, `b.js` can't access the exported variable `a` of `index.js`.

**If the current behavior is a bug, please provide the steps to reproduce.**

Use the code from this gist:
https://gist.github.com/gustavohenke/835d64b4049b2c71eeba811fceb8c481

then:
```
webpack
node bundle.js
// will print undefined
```

**What is the expected behavior?**
The currently exported variables should be available, even though there's a circular dependency,
just like plain CommonJS does.

In the above example, running the bundle file should print `123`.

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**
Using Windows 10 and Node v6.7.0, with plain JavaScript.
No browser used.

**Comment by gustavohenke** [comment]
I should also note that when using commonjs modules this is not a problem.

**Comment by sokra** [comment]
You are right.

``` js
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__a__ = __webpack_require__(0);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_1__b__ = __webpack_require__(1);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_1__b___default = __webpack_require__.n(__WEBPACK_IMPORTED_MODULE_1__b__);
/* harmony namespace reexport (by provided) */ __webpack_require__.d(exports, "a", function() { return __WEBPACK_IMPORTED_MODULE_0__a__["a"]; });
/* harmony namespace reexport (unknown) */ for(var __WEBPACK_IMPORT_KEY__ in __WEBPACK_IMPORTED_MODULE_1__b__) if(__WEBPACK_IMPORT_KEY__ !== 'default') (function(key) { __webpack_require__.d(exports, key, function() { return __WEBPACK_IMPORTED_MODULE_1__b__[key]; }) }(__WEBPACK_IMPORT_KEY__));
```

should be emitted as 

``` js
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__a__ = __webpack_require__(0);
/* harmony namespace reexport (by provided) */ __webpack_require__.d(exports, "a", function() { return __WEBPACK_IMPORTED_MODULE_0__a__["a"]; });
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_1__b__ = __webpack_require__(1);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_1__b___default = __webpack_require__.n(__WEBPACK_IMPORTED_MODULE_1__b__);
/* harmony namespace reexport (unknown) */ for(var __WEBPACK_IMPORT_KEY__ in __WEBPACK_IMPORTED_MODULE_1__b__) if(__WEBPACK_IMPORT_KEY__ !== 'default') (function(key) { __webpack_require__.d(exports, key, function() { return __WEBPACK_IMPORTED_MODULE_1__b__[key]; }) }(__WEBPACK_IMPORT_KEY__));

```

So the order is incorrect. Thanks for reporting.
