### ISSUE TITLE
Debug statements in loaders are stripped

### ISSUE THREAD

**Issue by Blitz2145** [webpack/webpack#3383]
**Do you want to request a *feature* or report a *bug*?**

Report a bug.

**What is the current behavior?**
`debugger;` statements in loaders are stripped.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Create a loader called `test_loader.js`
```
// Identity loader
module.exports = function(source) {
  console.log('Ran on:', source);
  debugger;

  return source;
};
```
2. Set `resolveLoader` to resolve this particular loader.
3. Run webpack using `node --inspect node_modules/webpack/bin/webpack.js --colors --env.env dev`
4. Debugger never hits breakpoint.

**What is the expected behavior?**
The debugger should hit the breakpoint inside the `test_loader.js` so that debugging loaders is possible.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**
OS: OSX
Browser: Chrome V54
Node.js Versions Tried: v6.9.1, v7.20
Webpack Version: 2.1.0-beta.27

How did I figure out the statements were stripped? Here's the output from the nodejs debug repl.
```
break in web_loaders/test_loader.js:3
  1 // Identity loader
  2 module.exports = function(source) {
> 3   console.log('Ran on:', source);
  4
  5   return source;
```
Notice, that the `debugger;` statement is gone.

If anyone else is trying to debug loaders, the following workaround might help. Use `node debug node_modules/webpack/bin/webpack.js --colors --env.env dev` to run your build and then when you're dropped into the node debugger repl, use `debug> sb('test_loader.js', 3)` to set the breakpoint on the loader module you'd like to debug. More documentation here: https://nodejs.org/api/debugger.html#debugger_breakpoints

**Comment by zhaoshengjun** [comment]
Try `node --inspect --debug-brk node_modules/webpack/bin/webpack.js --colors --env.env dev`. Then copy the url to `chrome`.

**Comment by Blitz2145** [comment]
Yup, I did that but it doesn't solve the problem. That would just break at
the first line of execution.

**Comment by zhaoshengjun** [comment]
Yes, it will stop the execution at the first line of `webpack.js`. But if you keep running it, it will stop at your `debugger` line of code.

**Comment by Blitz2145** [comment]
@zhaoshengjun Nope, it doesn't stop on the `debugger;` line of code. It does stop at the first line of `webpack.js`, but once I hit continue, it runs past the debugger line in my loader.

**Comment by Blitz2145** [comment]
@zhaoshengjun Argh, completely my fault, I was loading the wrong code that didn't actually have the `debugger;` statement in it. I'm gonna close this issue, not a bug heh, just user error! Thanks!
