### ISSUE TITLE
Checking for existence of require.resolve throws

### ISSUE THREAD

**Issue by matthewp** [webpack/webpack#3387]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

This file raises an error:

```js
var require('./bar.js');

var foo = {};

if(typeof window !== "undefined" && !require.resolve) {
  window.foo = foo;
}
```

```
ERROR in ./index.js
Module parse failed: /Users/matthew/Downloads/proj/index.js Unexpected token (1:11)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (1:11)
```

**What is the expected behavior?**

It should ignore this, as its not using `require.resolve()`, just checking if it exists.

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**

Node: v6.3.1
npm: 3.10.3

**Comment by andreypopp** [comment]
Syntax error is reported at line 1:
```
var require('./bar.js');
```
It should be
```
var bar  = require('./bar.js');
```
or something like that.

**Comment by matthewp** [comment]
Oh sorry, I feel so stupid.

**Comment by matthewp** [comment]
You do get a warning which is a false positive:

```
WARNING in ./index.js
Critical dependencies:
5:37-44 require function is used in a way in which dependencies cannot be statically extracted
 @ ./index.js 5:37-44
```

Not sure if this is worth opening a new issue for though, I had mistakenly thought it was throwing because of this.
