### ISSUE TITLE
webpack compiler errors with string instance, vs Error

### ISSUE THREAD

**Issue by cdaringe** [webpack/webpack#3388]
## What is the current behavior?

- webpack is throwing a `string`
  -  `"Unexpected module version: ./~/babel-polyfill/~/core-js/modules/_export.js@2.4.1"`
  - this only occurs when `NODE_ENV=production`. when unspecified or in `development`... no problem!
  - it occurs [similarly to here](https://github.com/cdaringe/bogus-wp-build/blob/master/bug-demo.js#L6).  **note**, i can't get it to replicate in this open source projec (_yet_)... my package is closed source, and i'm yet to determine the env difference

## What is the expected behavior?

- throw an `Error`.  or rather... don't error at all 😃 

## discussion

- i am trying eagerly to reproduce this error independently of my own project, which i am not permitted to share (closed source ☹️ ) . i am yet to succeed, but the attempt is here: https://github.com/cdaringe/bogus-wp-build
- i've looked through the webpack source, and it's not evident where the error is coming from--I don't see the `Unexpected module version` text.  What's interesting is that I _do_ see the _npm gauge_ before it errors out, which is bizarre.
- the only thing i'm sure of is that the error is sourcing from within webpack itself (which isn't surprising, given the error message)

**Comment by sokra** [comment]
We always throw errors. Probably caused by a loader or plugin. You can run node.js with debugger attached and halt on exceptions.

Please reopen if you know more details, or open an issue on the loader/plugin repo.

**Comment by cdaringe** [comment]
yea, debugging can be... a pain because of all of the node internals.  i did end up tracing it to a plugin anyway.

it may be nice in the plugin loader to do an assertion that the error is an `Error`, otherwise report the naughty plugin to the user!

thanks!
