### ISSUE TITLE
Optional externals

### ISSUE THREAD

**Issue by kmalakoff** [webpack/webpack#339]
Hello,

I'm moving over my libraries to use webpack for a universal loader for the browser and Node.js. It's really great!

I have been scouring to find our how to make a dependency optional in webpack. Two cases:

1) jquery - it is optional on the server
2) stream (well, readable stream) - it is so large so I want it to be optional on the browser

If I require either, they get pulled into my build or if I use externals, they are added to the factory call like:

```
exports["kb"] = factory(require("underscore"), require("backbone"), require("moment"), require("stream"));
```

Is there a way to require these libraries in my library, but not make them a hard dependency?

**Comment by mcroba** [comment]
How do you use this optional flag?

externals : {      
       "react": "React",      
       "react-dom": "ReactDOM",
       "app1/dist/component1": "Component1",
       "app2/dist/component2": "Component2"
 }

and I would like to make the component1 or component2 dependencies optional

Thank you in advance for your help

**Comment by bb1** [comment]
> How do you use this optional flag?
> and I would like to make the component1 or component2 dependencies optional

optionalDependenciesis a field in the package.json see: https://docs.npmjs.com/cli/v7/configuring-npm/package-json#optionaldependencies
