### ISSUE TITLE
what is the purpose of './example' file in this repo?

### ISSUE THREAD

**Issue by piyaa** [webpack/webpack#3390]
Can someone please explain the whole point of "./example" file here? In this https://github.com/webpack/webpack/blob/master/examples/i18n/example.js
I see its capturing the occurrence of every key in the translation file? why is that required?

**Comment by TheLarkInn** [comment]
Not to make any assumptions, but did you read the readme found here? https://github.com/webpack/webpack/tree/master/examples/i18n
