### ISSUE TITLE
Why I can't debug scripts in browser when I use handlebar-loader and webpack-dev-server hot mode 

### ISSUE THREAD

**Issue by jyjin** [webpack/webpack#3395]
The problem upsetting me for a long time:  If I don't use the handlerbar-loader, the dev server run perfect, I can also debug script in browser, and get the auto-refresh for writting styles,scripts.

But when I used handler-loader for my html, the page auto-refresh worked as usual, but any debugger didn't work which in my script or the breaking point in browser's develop tool .

All the debugger jumps to a no-conflict.js, I can't get any information, Obviously, I can't debug my script code neither.

 webpack.config like this:
![aaa](https://cloud.githubusercontent.com/assets/8912548/20740689/1dcdcf32-b700-11e6-9c74-4d63b1ea7284.png)
![bbbbb](https://cloud.githubusercontent.com/assets/8912548/20740702/2f0ac278-b700-11e6-90b2-ad69fd0bd0eb.png)

and all the debugger will jumps to here:
![ccccccc](https://cloud.githubusercontent.com/assets/8912548/20740728/7bfa0d1e-b700-11e6-8040-57b78d13f702.png)

**Comment by TheLarkInn** [comment]
What do you have set as your `devtool` property on your config. It looks like it is related to sourcemaps, but not 100% sure. In fact, could you provide your entire config?

**Comment by jyjin** [comment]
@TheLarkInn  thanks for your answering, my config like this:
```
var webpack = require('webpack');
var webpackDevServer = require('webpack-dev-server');
var ExtractTextPlugin = require("extract-text-webpack-plugin");
var path = require('path');
var log = function(s) {
    console.log(s + '\n+------------------------------------+')
}

var ENV = process.env.NODE_ENV;
var port = '10101';

var config = {
    vendor: path.resolve(__dirname + '/script/common/common.js'),
    entry: {
        app: './script/app',
        server: 'webpack-dev-server/client?http://localhost:' + port + '/'
    },
    output: {
        sourceMap: true,
        path: path.join(__dirname, '/wds'),
        filename: '[name].bundle.js',
        publicPath: '/wds/'
    },
    module: {
        loaders: [
            {
                test: /\.js$/,
                exclude: /node_modules/,
                loader: 'babel-loader'
            }, {
                test: /\.css$/,
                loader: ExtractTextPlugin.extract("style-loader", "css-loader")
            }, {
                test: /\.less$/,
                loader: ExtractTextPlugin.extract("style-loader", "css-loader!less-loader")
            },
            {
                test: /\.html$/,
                loader: "handlebars-loader?helperDirs[]=" + __dirname + "/script/helpers"
            }
        ]
    },
    plugins: [
        new ExtractTextPlugin('[name].bundle.css'),
        new webpack.optimize.CommonsChunkPlugin({
            name: "vendor", filename: "vendor.js",
            // minChunks: Infinity,
        })
    ],
    resolve: {
        extensions: ['', '.js']
    },
    node: {
        process: true
    }
}

var compiler = webpack(config);
var server = new webpackDevServer(compiler, {
    // hot: true, //打开这个就不自动刷新
    publicPath: '/wds/', //hot模式资源打包的虚拟地址
});
server.listen(port);

module.exports = config;
```
