### ISSUE TITLE
stats.json undefined

### ISSUE THREAD

**Issue by guypaskar** [webpack/webpack#3396]
When compiling with webpack I get this error

/bin/compile.js:13
const jsonStats = stats.toJson();                     
TypeError: Cannot read property 'toJson' of undefined

Can anyone please help?

**Comment by bebraw** [comment]
Can you provide more information? There's not enough to work with. A standalone project would be ideal.

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template, or open a new issue.
