### ISSUE TITLE
[webpack2]import not work well for special case

### ISSUE THREAD

**Issue by yyjdelete** [webpack/webpack#3398]
>`2.1.0-beta.27`

**Do you want to request a *feature* or report a *bug*?**

>Maybe a bug(There is also something wrong with the .js)

**What is the current behavior?**
> console out `1` with the below code

**If the current behavior is a bug, please provide the steps to reproduce.**

1. 
Files
x1.js
```javascript
import x2 from './x2'

console.log(x2);
```
x2.js
```javascript
var a = { a : 1 };

export default a;
module.exports = a;
```
Cfg
```javascript
var webpack = require('webpack');
var path = require('path');

module.exports = {
    entry: {
        x1: './x1.js',
    },
    module: {
        rules: [
            //in fact no need of babel, found this while try webpack2 with `{ "modules": false }`
            {
                test: /\.jsx?$/,
                exclude: /(node_modules)/,
                loader: 'babel-loader',
                options: {
                    presets: [["es2015", { "modules": false }]],
                }
            },
        ]
    },
    output: {
        path: path.join(__dirname, 'build'),
        filename: `[name].js`,
    }
}
```
2. pack it with webpack and run.

**What is the expected behavior?**
> console out `{ a: 1 }`, at least give an error or warn instead of product unpredictable result.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**
>`node v7.2.0`

**Comment by sokra** [comment]
> export default a;
> module.exports = a;

You can't mix ES2015 modules with CommonJs, that doesn't make sense.
