### ISSUE TITLE
webpack loader test undefined behaviour

### ISSUE THREAD

**Issue by stonexer** [webpack/webpack#3399]
When `loader.test` is undefined,  webpack just pass the loader's matchObject check. When I made some mistakes about 'test' itself, like spelling it to 'text' :) . Then all the files will pass this loader and something strange will happened without waring.

So could I have some restriction on `loader.test`. As far as I am concerned, most of the cases we use will need to set the `test`. So could we get warning when some element of loaders list don't have test attribute?

**Comment by sokra** [comment]
It's allowed to omit the `test` property. webpack 2 validates the configuration and will tell you that `text` is not allowed.
