### ISSUE TITLE
Babel plugin doesn't get applied to `System.import` ed resources 

### ISSUE THREAD

**Issue by pastelsky** [webpack/webpack#3401]
**What is the current behavior?**
I'm on `webpack 2.1.0-beta.27` and trying to use `System.import` for code splitting of routes along with react router 3.

I'm using babel transforms to strip prop types from the built result —
```javascript
      {
        test: /\.(js|jsx)$/,
        loader: 'babel-loader',
        exclude: /(node_modules)/,
        query: {
          presets: ['react', 'stage-2'],
          plugins: [
            'transform-react-remove-prop-types',
            ['transform-runtime', {
              polyfill: false,
              regenerator: true,
            }],
          ],
          babelrc: false,
        },
      },
```

Consider the following routes file samples:

## 1.Normal(Static) Routes

```javascript
// routes.js
export default  [{
      name: 'Home',
      path: '/',
      component: require('./HomePage')
  }]
```
**Result:** As expected single `client.js` is outputed **with proptypes removed**.

## 2. Dynamic routes
```javascript
// routes.js
export default  [{
      name: 'Home',
      path: '/',
     //`__CLIENT__`  is a DefinePlugin constant
      getComponent: () => __CLIENT__ ? System.import('./HomePage') : Promise.resolve(require('./HomePage'))
  }]
```

**Result**: A `client.js` and a new split called `0.[hash].js` is created. `client.js` does not have proptypes but the proptypes are **still** embedded in the split, `0.[hash].js`.

**What is the expected behavior?**
Proptypes should be stripped from `System.import`ed resources too.

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**
Mac OS X 10.10
Node v7.1.0

**Comment by TheLarkInn** [comment]
Would you be able to create a small reproducible repo that we could use to troubleshoot this. This will help identify if this is core bug or just a configuration/implementation detail.
