### ISSUE TITLE
How to set an ignore / exclude entry list for webpack.DllPlugin?

### ISSUE THREAD

**Issue by unknown-coder** [webpack/webpack#3405]
When using webpack.DllPlugin, it will Automatically handles all the entries.

So, How to set an ignore / exclude entry list for webpack.DllPlugin?

```javascript
{
    entry: {
        ignore: ["ignore.js"], // ignore this entry
        vendor: ["vendor.js"]
    },
    plugins: [
        new webpack.DllPlugin({
            path: "manifest.json",
            name: "[name]_[chunkhash:8]",
            context: __dirname,
        })
    ]
}
```

**Comment by causer** [comment]
Yes, i have same question. It is so important when you add jquery plugins into bundle.

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template, or open a new issue.

**Comment by unknown-coder** [comment]
@sokra 
I have updated my issue, please reopen this.
