### ISSUE TITLE
webpack 2.1.0-beat.27 use webpack.ProvidePlugin wechat browser display error __WEBPACK_AMD_DEFINE_ARRAY__ is not defined

### ISSUE THREAD

**Issue by stevieyu** [webpack/webpack#3406]
```js
[
        new webpack.ProvidePlugin({
            $: 'jquery',
            jQuery: 'jquery',
            "window.jQuery": 'jquery',
        }),
]
```

webpack 2.1.0-beat.27 use webpack.ProvidePlugin wechat browser display error 

```
__WEBPACK_AMD_DEFINE_ARRAY__ is not defined
```

webpack config : https://github.com/stevieyu/vue2-blog/blob/master/webpack.config.babel.js

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template, or open a new issue.
