### ISSUE TITLE
Cannot read property 'a' of undefined

### ISSUE THREAD

**Issue by mmahalwy** [webpack/webpack#3407]
Running `"webpack": "2.1.0-beta.20"` on Node v7. After activating code splitting via `System.import` I am getting error

```
Cannot read property 'a' of undefined
```
for code:
```
const metricsApp = metrics(metricsConfig)(App);
```

More specifically, the compiled code:
```
var metricsApp = __webpack_require__.i(__WEBPACK_IMPORTED_MODULE_9_react_metrics__["metrics"])(__WEBPACK_IMPORTED_MODULE_16_helpers_metrics__["a" /* default */])(App);
```

If I turn off code splitting, it works fine with no errors. Thoughts on how to debug this? Updating to the latest beta.27 results in error
```
		throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
```

Update:
Seems that the problem is with `metricsConfig` specifically, which when I either remove or import through `require('helpers/metrics')` it works fine and I get the same above error for a different file.

**Comment by mmahalwy** [comment]
Found the cause:
```
presets: ['react', ['es2015', {modules: false}], 'stage-0', 'react-hmre'],
```

More specifically: `['es2015', {modules: false}]` should be `es2015`

**Comment by Kovensky** [comment]
That is not the cause, it's a workaround. That just uses babel's modules implementation to generate commonjs, and webpack thus only sees commonjs code.

How are you `import`ing `metrics` and `metricsConfig`? From the generated code, it looks like `import metricsConfig, { metrics } from './metrics'`, and for some reason the `metrics` import name is not minified like the default is?

**Comment by sokra** [comment]
Upgrate the lastest webpack version. It could be already fixed. If it's still an issue open a new issue and fill the issue template!!!

**Comment by elodszopos** [comment]
Hey guys. I ran into this as well in the above issue that I created in Nikolay's repo. For me the issue was that I still left in the `add-module-exports` plugin.

As soon as I removed it `Cannot read property 'a' of undefined` disappeared along with it.

Lesson learned: 

`['es2015', {modules: false}]`
and adding module exports using babel are a no-go. Not really WebPack related.

**Comment by Kovensky** [comment]
_Please_ don't use add-module-exports, regardless of webpack 2. Its only purpose is keeping API compatibility with Babel 5's modules implementation.

Furthermore, using it means that adding any export other than `default` to a module, normally harmless, becomes a _breaking_ change.

Removing it is also a breaking change for commonjs consumers, but at least you only have to remove it once.

**Comment by elodszopos** [comment]
Thanks for the detailed answer @Kovensky. Appreciate it!

**Comment by kavykun** [comment]
I am having this issue with:

// .babelrc
{
  "plugins": ["react-hot-loader/babel"]
}

removing this break production build
