### ISSUE TITLE
About NormalModuleReplacementPlugin and IgnorePlugin

### ISSUE THREAD

**Issue by huangyuesong** [webpack/webpack#3412]
I moved my css files into a sub-directory, so I want to use NormalModuleReplacementPlugin to replace the reference "../images" with "../../images".

However, there are some images absent from my images directory but I cannot change my css code. So I want to use IgnorePlugin to ignore these requests.

When using both of them, it comes out that a request called "../images/question.png" cannot be resolved. This request is neither be replaced nor ignored. How strange!

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template, or open a new issue.
