### ISSUE TITLE
"Cannot Redefine property" error when importing

### ISSUE THREAD

**Issue by christianacca** [webpack/webpack#3415]
**Do you want to request a *feature* or report a *bug*?**
Bug report

**What is the current behavior?**

The following import statement:

```js
import { NgTableParams } from 'ng-table';
```

produces the following error logged to the console:

```cmd
Cannot redefine property: NgTableParams
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Run the demo-app in ng-table where the above import is attempted:

1. git clone -b webpack-problem https://github.com/esvit/ng-table.git
2. npm i
3. npm run setup:ci
4. cd demo-apps/es6-webpack
5. npm start

The last command will use `webpack-dev-server` to launch the demo-app in your default browser.

In chrome this produces the error logged to the console.

**What is the expected behavior?**

The import of `NgTableParams` should work

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**

Possible related to: https://github.com/webpack/webpack/issues/2953

**Environment details**

* Chrome: 54.0.2840.99
* OS: Windows 10
* Node: 6.2.2
* npm: 3.10.9
* webpack: 2.1.0-beta.27
* typescript@2.0.3 used to compile the library
* babel used to compile the demo-app that is failing

**Comment by TheLarkInn** [comment]
This doesn't appear to be a webpack related error. Is this an issue with typescript seeing a reimport or redefine of this property?

**Comment by christianacca** [comment]
Hi @TheLarkInn,

What make you think it's a typescript issue? I'm suspect webpack because:

* `tsc` compiles the ng-table library code without complaint
* this problem only occurs at runtime, and only in the demo app that is NOT compiled using typescript

**Comment by christianacca** [comment]
Did a slightly deeper dive into the problem.

I can stop the error from occurring by not **re-**exporting `NgTableParams`.

Let me explain by briefly showing the directory tree where `NgTableParams` module lives:

<pre>
ng-table (root directory)
  index.ts
  +- src
    +- core
       index.ts
       ngTableParams.ts 
</pre>

Here are the relevant exports that collectively are causing the problem it would seem:

```ts
// src/core/ngTableParams.ts
export class NgTableParams<T> { }
```
```ts
// src/core/index.ts
export * from './ngTableParams';
```
```ts
// index.ts (at the root of the package)
export * from './src/core';
```

To "fix" things I have to stop re-exporting `NgTableParams`, thusly:

```ts
// src/core/ngTableParams.ts
export class NgTableParams<T> { }
```
```ts
// src/core/index.ts
export { NgTableParams } from './ngTableParams';
```
```ts
// index.ts (at the root of the package)
export { NgTableParams } from './src/core/ngTableParams';
```

With the above in place the demo-app runs without error. I have committed the above change to another [ng-table branch](https://github.com/esvit/ng-table/tree/webpack-problem-workaround) for comparison (here's the exact: [commit](https://github.com/esvit/ng-table/commit/317475e50c877119cbf2ea03d8e1b3e79d1d3735))

---

## Even more details

Below is a screenshot of the relevant portion of the webpack bundle that fails. The line of code that is throwing is shown highlighted in blue:

![image](https://cloud.githubusercontent.com/assets/886590/20866732/b704c092-ba2b-11e6-8114-e61ea831fc2c.png)

Below is a screenshot of the same portion of the webpack bundle after applying the workaround of not re-exporting as explained above:

![image](https://cloud.githubusercontent.com/assets/886590/20866743/22ce890c-ba2c-11e6-867a-2037ec719964.png)

**Comment by christianacca** [comment]
I have been able to reduce the problem down further. 

The problem occurs even with a single `export *` involved.

Here's are the relevant changes:

```ts
// src/core/ngTableParams.ts
export class NgTableParams<T> { }
```
```ts
// src/core/index.ts
export * from './ngTableParams';
```
```js
// demo-app
// this fails at runtime with error "Cannot redefine property: NgTableParams"
import { NgTableParams } from 'ng-table/src/core';
```

The commit with the simplified code: https://github.com/esvit/ng-table/commit/a992e82a41864adcde81ab5e14c6b8efa63af70f

**Comment by sokra** [comment]
Ah I see the issue. I need the check the spec to see if the app or webpack is wrong here...

**Comment by sokra** [comment]
Looks like webpack is wrong here.

`export *` doesn't export a name that is already exported.

**Comment by christianacca** [comment]
OK thanks Tobias for check the problem out.

**Comment by TheLarkInn** [comment]
Thank you for the detailed report. Made this much easier to fix!!

**Comment by Kovensky** [comment]
To add to it: explicit exports take precedence over reexports (e.g. `export const X = ''` will take precedence over any `X` coming from an `export * from`); duplicate reexports of the same symbol (via `export * from` of different modules) are not allowed (at least by typescript) or must be overridden with an explicit `export { theDuplicateName }`.

**Comment by sokra** [comment]
> duplicate reexports of the same symbol (via export * from of different modules) are not allowed

Correction: They are only allowed when they resolve to the same binding.

**Comment by christianacca** [comment]
Thanks for the very quick turnaround @sokra.

Do you know when you're intending to publish the next release?

**Comment by TheLarkInn** [comment]
We are waiting on a few things to merge before we release. The next release is potentially looking to be an RC.

**Comment by christianacca** [comment]
OK thanks for the heads up
