### ISSUE TITLE
Proposal (my thoughts): Externalize tree shaking from the core to separate package/lib/tool

### ISSUE THREAD

**Issue by charlike** [webpack/webpack#3416]
What about `tree-shaker` or `tree-shaking`? Why not `frog` - free, short, animal, cool?
***

Hi there. Just playing around more deeply last few days with Rollup and Webpack.

Rollup is extremely focused, small, fast and awesome. And his idea for tree shaking is unique, moved tooling years forward, saves million bytes. That's great, but it seems that it has much problems with the tree shaking, just for few hours found couple of cases that seems easy.

So I ended up with thought that Webpack has good support for tree shaking, but is awful when it comes to "getting started", "up and running", "setup/config". Okey, it easy to "get started", but these configs reminds me to Grunt times or something worst (i'm step into the community around when gulp pops up, or a bit later after it). Never touched gruntfile and never worked with grunt, and even can't imagine to work with - it is total mess even in to moment you just look its config. Nevermind. That's not some hate, rant or etc. That's my 2c about "configuration style".

***

**In short:** We need just tree-shaking package, which deals with only es6 modules. Just gets entry then returns a bundle. Period. Nothing more, nothing less. Actually `babylon` is great, so I think it should be used in that tree-shaking package as a base. So babel-based? This allow more and more advanced things to be built on top of it?

**In short 2:** If we have such package, both rollup and webpack would be more stable, built with one core with joined forces (+ babel ecosystem and its users). Rollup will still be the same thing, Webpack too. If someone just don't want to use webpack (in some cases and small projects it not worth), or rollup (because some reason) - actually it has 180 issues currently, or it just want to built another bundle tool/service, will just use that package.

***

2. Another thing is that both Rollup and Webpack can't load config from `package.json`? Or I'm missing something? hm

3. Webpack "activates" its tree shaking only when "optimize minimize" thing is enabled, meaning you can't get tree shaked bundle without it to be minified?

4. Webpack must use babel-loader to get tree-shaked bundle (because the minify-ing stuff) because uglifyjs. (yea we have some harmony branch out there but..) And `babili` is too young, but i believe we should use it as base.

***

**In short 3:** We just don't need another features. We want stable tree shaking and optimized bundles, no painful config and boilerplate. We don't want more and more config files into repo root. I, specifically, hate to mix tools inside another tools (i mean with "plugins" or no matter how you'll call it) - most of them are totally focused and does its job great. We as developers should think in this way.

If we build just a tool that deals with that job, then we can just pass that bundle to babel. One scenario can be: you are user, you write packages that are mostly ES5 but you use es6 modules because the minify-ing and tree shaking stuff. You pass your code to that tool, gets final cool es5 bundle without import/exports. Second scenario: you are writing ES6 with more features than just es6modules, pass your code to such tool that does not deal with another ES6 features but only with the ES6 modules, gets a bundle, pass that bundle to babel and you get final es5 code again. Minifying is totally another story and we should not deal with it in these tools - we can use `babili`/babel ecosystem, i believe it will explode in some point in future.

*** 

5. I'm playing with `babylon` to get import and exports, and thinking for object structure that will contain the things.

**Comment by bebraw** [comment]
> Another thing is that both Rollup and Webpack can't load config from package.json? Or I'm missing something? hm

It's not feasible to build an automatic mapping between JSON and webpack's configuration format as far as I'm aware of. You'll run into issues with plugins in particular.

I don't know how feasible it would be to extract the tree shaking related functionality to package of its own. It's quite possible it's somewhat tied to webpack's internal implementation making it difficult.

That said, I agree pushing features to packages is a good way to go as that enables collaboration across projects, but it can also limit (stable API needed, more communication required). Sometimes those limitations can be good, though, and foster quality.

**Comment by tunnckoCore** [comment]
:+1: 

> It's not feasible to build an automatic mapping between JSON and webpack's configuration format as far as I'm aware of. You'll run into issues with plugins in particular.

I don't get what problems you'll have when you just want to use babel and some preset. For example such things are totally JSON valid

```js
module.exports = {
  entry: './index.js',
  output: {
    path: __dirname,
    filename: 'bundle.min.js'
  },
  module: {
    loaders: [{
      test: /\.js$/,
      exclude: /(node_modules|bower_components)/,
      loader: 'babel-loader'
    }]
  }
}

```

of course, regex/patterns can be `nanomatch` or `micromatch`.

AVA, ESLint, Standard, Verb, PostCSS are good examples too. They can accept pretty complex config through package.json. And really, worth nothing, just some cool config loader package (i'm not talking for webpack package), like [my idea for `load-cfg` (tunnckoCore/ideas)](https://github.com/tunnckoCore/ideas/issues/46)

**Comment by bebraw** [comment]
@tunnckoCore A plugin definition could look like this:

```javascript
plugins: [
  new webpack.HotModuleReplacementPlugin({
    multiPass: true
  })
]
```

I've tried the JSON approach myself and I got it working, but it got very frustrating with plugins for this reason. Especially third party ones are painful.

That said, if you know how to solve it, please show me how to do it.

**Comment by michael-ciniawsky** [comment]
@bebraw @tunnckoCore 

**package.json**
```js
"webpack": {
  "plugins": {
     "html-webpack-plugin":  {..options}
  }
}
```

**plugins.js**
```js
const load = (Plugin, options) => {
  if (Object.keys(options).length === 0) {
    try {
      Plugin = require(Plugin)

      return new Plugin()
    } catch (err) {
      console.log(err)
    }
  } 
  try {
    Plugin = require(plugin)

    return new Plugin(options)
   } catch (err) {
     console.log(err)
   }
 }
}

if (typeof webpack.plugins === 'object') {
    Object.keys(webpack.plugins).forEach((Plugin) => {
        Plugin = load(Plugin, wepack.plugins[Plugin])
        
        config.plugins.push(Plugin)
    })
}
```

But please don't 😛

**Comment by tunnckoCore** [comment]
It's absolutely understandable that one JSON config won't support fully what user can do through js file config, but it not mean that the tool should not support JSON config and that it should not try to load config from couple of places and finally merge them in one.

edit: I'm not talking for `plugins` especially. It's totally normal to not be able to accomplish what we can with js file. I'm talking for most of other things.

**Comment by michael-ciniawsky** [comment]
@tunnckoCore Plugins are the bread and butter of webpack, even internally most of the logic is implemented as a plugin ([tapable](https://github.com/webpack/tapable) instance), being unable to use plugins would not just limiting 'advanced' usecases to some point, you would lose the ability to configure and use Core Plugins (UglifyJS, CommonChunks etc..) aswell.

**Comment by tunnckoCore** [comment]
@michael-ciniawsky omg :laughing: core will still work with plugins, config has nothing to mess with that. Worth nothing to support package.json as config for simple things that in some cases are totally enough and the user just don't adds dozens of config and dot files.

**Comment by ejdelmonico** [comment]
@tunnckoCore This issue is a good conversation, but I do not feel that it is an issue. Maybe a feature request is a good label for this thread.

**Comment by charlike** [comment]
Valid.
