### ISSUE TITLE
Loading-order independent library bundles

### ISSUE THREAD

**Issue by drywolf** [webpack/webpack#3422]
**If this is a feature request, what is motivation or use case for changing the behavior?**

Hi,

the usecase that I'm trying to achieve is to have multiple library bundles built with webpack and the `libraryTarget: 'var'` setting and the outputs should be combined in a hierarchical namespace structure in which the bundle contents are placed properly.

For example:

BaseLib webpack.config:

    libraryTarget: 'var',
    library: ['Company', 'Base'],

AdvancedLib webpack.config:

    libraryTarget: 'var',
    library: ['Company', 'Base', 'Advanced'],

Which generates the following code in the bundles:

BaseLib.bundle.js:

    var Company = Company || {}; Company["Base"] = /* the module content */

AdvancedLib.bundle.js:

    var Company = Company || {}; Company["Base"] = Company["Base"] || {}; Company["Base"]["Advanced"] = /* the module content */

This works fine when the two bundles are loaded in the order

- <script src="BaseLib.bundle.js">
- <script src="AdvancedLib.bundle.js">

... but if the bundles are loaded in reverse order, then the `Company.Base` object will never contain the exports from the BaseLib bundle, because the merging of the objects does only account for intersections at the namespace level, but not individual members of a certain sub-namespace/module-namespace.

To make the loading order of the bundles independent from each other, the library object hierarchies would have to be merged on the property-level of the generated objects e.g. ala `Object.assign(oldModuleExports, newModuleExports)`.

Would this be a usecase/feature that webpack should support ? What are workarrounds or solutions that can be used to make sure to not run into this problem when using multiple library modules which have dependencies amongst each other ?

Thanks

**Comment by sokra** [comment]
Sounds like a idea for a new `libraryTarget` i. e. `"var-merge"`. Feel free to start a PR adding it.

**Comment by drywolf** [comment]
cool, I will look into it
