### ISSUE TITLE
ERROR in ../static/js/vendor.e64b61ec57c2a4f1894b.js from UglifyJs

### ISSUE THREAD

**Issue by BusyHe** [webpack/webpack#3423]
SyntaxError: Unexpected token punc «(», expected punc «:» [./~/vue-cropperjs/VueCropper.js:140,0]

**Comment by SpaceK33z** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template, or open a new issue.

**Comment by talha08** [comment]
Just Edit the _build/wbpack.base.conf.js_ file

`{
        test: /\.js$/,
        loader: 'babel-loader',
        include: [resolve('src'),
          resolve('test'),
          resolve('node_modules/webpack-dev-server/client'),
          resolve("node_modules/vue-particles")
        ]
      },`
