### ISSUE TITLE
Load modules from Bundles hosted remotely (Angular2, Webpack2)

### ISSUE THREAD

**Issue by VivekPMenon** [webpack/webpack#3430]
Webpack Version: 2.1.0-beta.25
Npm: 3.10.9
Node: 4.4.7 

This is not a bug and we are looking for a feature. It's a long narration. Please bear with me.

We develop Angular 2 widgets and bundle them using multiple entry points so that main.bundle.js has only widget specific code (no Angular2 code). Our Widget bundles are remotely hosted (like CDN) and Consuming App downloads/executes these bundles at runtime. 

Since the widgets created and **webpacked** in separate projects by separate teams, _webpack_require_() collides when it looks up for the vendor dependencies as each widget bundle may have different identifier assigned for the same vendor dependencies (in our case angular2) and it could be different from the identifier assigned for angular2  in the Main App Bundle itself. 

This ends up in widgets not having their vendor dependencies resolved. We would like to check if there is any way to get this use case working. 

For instance, we were using SystemJs earlier and it uses package name itself as the identifier in the bundle (like @angular/core instead of an integer) and hence widgets are able to resolve their vendor deps if it is present in Consumer App Bundle.

Any suggestion will be really appreciated.

**Comment by Kovensky** [comment]
This sounds like a job for `DllPlugin` + `DllReferencePlugin`.

**Comment by VivekPMenon** [comment]
Thanks much @kovensky for the tip.

DLL reference plugin seems to be what I am looking for. I will try it out and see if it meets the requirements.

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template, or open a new issue.

**Comment by VivekPMenon** [comment]
I have updated the issue description using the template provided for future references although I seem to have got the answer that i am looking for. I will try it out and if still a blocker I will reopen this issue.

Thanks much folks.
