### ISSUE TITLE
[v2.1.0-beta.27] Can't resolve 'browserify-aes/browser'

### ISSUE THREAD

**Issue by npasquet** [webpack/webpack#3437]
Hello,

I'm getting an error when building my project with webpack 2 and this [configuration](https://gist.github.com/npasquet/cd526ed356b0ec3a4b840695820a763f)

> ERROR in ./\~/browserify-cipher/browser.js
Module not found: Error: Can't resolve 'browserify-aes/browser' in '/app/node_modules/browserify-cipher'
@ ./\~/browserify-cipher/browser.js 2:10-43
@ (webpack)/~/crypto-browserify/index.js
@ ./\~/jwa/index.js
@ ./\~/jws/lib/sign-stream.js
@ ./\~/jws/index.js

The terminal output when looking for the package

> $ npm ls browserify-aes
> dashboard-ng@1.5.35 /Users/lapasque/Webstorm/dashboard
> ├─┬ favicons-webpack-plugin@0.0.7
> │ └─┬ webpack@1.14.0
> │   └─┬ node-libs-browser@0.7.0
> │     └─┬ crypto-browserify@3.3.0
> │       └── browserify-aes@0.4.0
> └─┬ webpack@2.1.0-beta.27
>   └─┬ node-libs-browser@1.1.1
>     └─┬ crypto-browserify@3.11.0
>       ├─┬ browserify-cipher@1.0.0
>       │ └── browserify-aes@1.0.6
>       └─┬ browserify-sign@4.0.0
>         └─┬ parse-asn1@5.0.0
>           └── browserify-aes@1.0.6
> 

I'm using nodejs@v7.2.0 on macOS sierra@v10.12.1

Thanks,

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template, or open a new issue.

**Comment by npasquet** [comment]
@sokra I updated the issue.

**Comment by sokra** [comment]
`--display-error-details`

Is `"node_modules"` in `resolve.extensions`? The exact string not the absolute path to the root node_modules folder.

**Comment by npasquet** [comment]
@sokra thank you I was using absolute path in resolve.modules
