### ISSUE TITLE
Add parallel loading/compression with Babel/TypeScript/PostCSS + Uglify/Babili/CSS-O

### ISSUE THREAD

**Issue by swernerx** [webpack/webpack#3438]
There are coming more and more solutions offering parallel execution of core tasks in Webpack. 

- [HappyPack](https://github.com/amireh/happypack): Execute loaders in parallel
- [Parallel Webpack](https://github.com/trivago/parallel-webpack): Executing multiple configurations in parallel
- [Parallel Uglify](https://github.com/gdborton/webpack-parallel-uglify-plugin): Compress multiple chunks in parallel with Uglify

I think it would make sense to generally change the infrastructure so that loaders and compressors could be executed in parallel on multiple threads. Currently all of the listed solutions have a pretty narrow scope and feature set. Some have bugs and are not very well documented.

I figure we should all join forces to not add another half-baken solution, but doing some infrastructure work to support all loaders/compressors at once.

These would be the major areas I see for parallel execution in Webpack:

1. Loaders
2. Optimizing Assets
3. Overall builds (Build an array of Webpack configs)

Biggest "end points" for making parallel work:

- Babel
- TypeScript
- PostCSS
- Uglify
- Babili
- CSS-O

Let's work on this together. I figure making Webpack v3 fully multi core ready would be an amazing goal.

**Comment by SpaceK33z** [comment]
Related: #3366, #2975

**Comment by adamhooper** [comment]
Don't bother with Parallel Uglify: make uglify a loader instead. The output file size is the same, but it plays better with the development cache, and you can load in parallel.

I ran across this issue while writing a blog post on the topic: [Make UglifyJS way faster by using it sooner](https://medium.com/@adamhooper/make-uglifyjs-way-faster-by-using-it-sooner-c2c39a9ad27e)

**Comment by evilebottnawi** [comment]
active for tracking

**Comment by evilebottnawi** [comment]
Should be implement inside plugins/loaders
