### ISSUE TITLE
QUESTION: Why is webpack having trouble resolving a nested node_module

### ISSUE THREAD

**Issue by varunjayaraman** [webpack/webpack#3439]
"typescript": "^2.0.10"
"webpack": "2.1.0-beta.27"

I am using module resolution in webpack to avoid using `../../` on the client to import certain modules. My  directory structure looks like this
```
- dist (transpiled assets)
- node_modules
- lib
   - client
       - typescript
          - some-component
             - some-component.ts
          - some-service
             - some-service.ts
   - server
   - shared
- webpack.config.js
- tsconfig.client.json
```

In `some-component.ts`, i want to import from `some-service.ts`, so I have configured webpack to allow the following module resolution:

```
const rootDir = __dirname;

const clientPathMappings = [
  path.resolve(rootDir, 'lib/client/typescript'),
  path.resolve(rootDir, 'node_modules')
  ];
......

(inside the config object)
resolve: {
      extensions: ['.ts', '.jade', '.js'],
      modules: clientPathMappings
    }
```

I can then do this:
```
import { SomeService } from 'some-service';
```

When i run webpack, it complains:

```

ERROR in multi app
Module not found: Error: Can't resolve '/Users/varun/project/api-server/node_modules' in '/Users/varun/project/api-server'
 @ multi app

ERROR in ./~/mongoose/lib/schema.js
Module not found: Error: Can't resolve 'async/each' in '/Users/varun/project/api-server/node_modules/mongoose/lib'
 @ ./~/mongoose/lib/schema.js 11:11-32
 @ ./~/mongoose/lib/browser.js
 @ ./lib/client/typescript/index.ts
 @ multi app
```

This is definitely a webpack error and not a typescript error, but I've pasted my `tsconfig` below just in case:

```
{
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "noImplicitAny": false,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
    "moduleResolution": "node",
    "removeComments": true,
    "sourceMap": true,
    "lib": [
      "es6",
      "dom"
    ],
    "baseUrl": ".",
    "paths": {
      "*": [
        "lib/client/typescript/*"
      ]
    }
  },
  "exclude": [
    "node_modules"
  ],
  "include": [
    "lib/client/typescript/**/*"
  ]
}
```

Why can't webpack resolve `async/each` from within mongoose? And what is webpack's complaint about trying to resolve node_modules as if it were a file and not a folder within which modules I would want to resolve live in?

**Comment by varunjayaraman** [comment]
I was able to get mongoose's complaint about `async/each` to go away by removing `path.resolve` from the node_modules path (not sure why that worked):

```
[
  path.resolve(rootDir, 'lib/client/typescript'),
  'node_modules'
  ];
```

I'm still getting the issue about resolving node_modules though:

```
ERROR in multi app
Module not found: Error: Can't resolve '/Users/varun/project/api-server/node_modules' in '/Users/varun/project/api-server'
 @ multi app
```

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template, or open a new issue.

**Comment by varunjayaraman** [comment]
Yeah sorry about that, i ended up figuring the problem out anyway.

**Comment by myufa** [comment]
> Yeah sorry about that, i ended up figuring the problem out anyway.

Could you please share the solution?
