### ISSUE TITLE
Provide Plugin & rivets

### ISSUE THREAD

**Issue by jbrumwell** [webpack/webpack#344]
I have the following definition in my config;

```
new webpack.ProvidePlugin({                
                jQuery: "jquery",
                $: "jquery"
            })
```
which hasn't been a problem until now, when trying to;

```
require('rivets'); //after npm install rivets
```

it returns an error on compiling:

```
ERROR in ./~/rivets/dist/rivets.js
Module not found: Error: Cannot resolve module jquery in node_modules\rivets\dist
 @ ./~/rivets/dist/rivets.js 1:0-17
```

The generated file has the following;

```
/* WEBPACK VAR INJECTION */}.call(exports, __webpack_require__(!(function webpackMissingModule() { var e = new Error("Cannot find module \"jquery\""); e.code = 'MODULE_NOT_FOUND'; throw e; }()))))
```

instead of the regular:

```
/* WEBPACK VAR INJECTION */}.call(exports, __webpack_require__(7)))
```

removing the provide plugin results in module being loaded correctly also forcing the script loader allows it compile. Any ideas?

**Comment by bebraw** [comment]
@jbrumwell Can you still see the problem?

**Comment by jbrumwell** [comment]
I no longer use rivets so can't say

**Comment by bebraw** [comment]
Ok, I'm closing this. If some rivets issue comes up, we'll know.
