### ISSUE TITLE
devtoolModuleFilenameTemplate should allow to be derived from the entry name

### ISSUE THREAD

**Issue by pgn-vole** [webpack/webpack#3444]
It would be good to be able to configure the sourcemap filename depending on the entry name.

Usage:

```javascript
  entry: {
    'module1': './src/module1.js',
    'module2': './src/module2.js'
  },
  devtool: "source-map",
  output: {
    filename: 'dist/[name].js',   
    devtoolModuleFilenameTemplate: './[entry]/[resource]'
  },
```

In this particular case right now both modules that are within the distribution cannot have properly named source maps because of this limitation.

**Comment by TheLarkInn** [comment]
Does `[name]` not work?

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template, or open a new issue.
