### ISSUE TITLE
ERROR in multi vendor Module not found

### ISSUE THREAD

**Issue by JamieVGroupClaes** [webpack/webpack#3446]
I get the following error when i try to do 'gulp build'

![image](https://cloud.githubusercontent.com/assets/24246168/21008005/00eeff62-bd40-11e6-8488-cf371799ca2f.png)

gulp serve runs fine
I am creating a teplate for myself and other to use ionic/cordova/angular etc with es6
repo => https://bitbucket.org/JamieVangeysel/repo_ionic-angular-template

just do an npm i and then gulp build and this guy pops up
ps: u need newest gulp cli and npm globally installed

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template, or open a new issue.
