### ISSUE TITLE
IE Browser problem, map files return 404 for webpack -d

### ISSUE THREAD

**Issue by damienbod** [webpack/webpack#3450]
Hi I'm having problems with the -d build, it creates an inline .map file and when running in IE, I receive lots of 404s for my original map files. (Not in Firefox or Chrome) Is there a way to fix this? Or is it a bug?

webpack: 2.1.0-beta.27

npm file:

https://github.com/damienbod/Angular2WebpackVisualStudio/blob/master/Angular2WebpackVisualStudio/src/Angular2WebpackVisualStudio/package.json

reproduce command:

SET NODE_ENV=development&& webpack -d --color

Project:

https://github.com/damienbod/Angular2WebpackVisualStudio/tree/master/Angular2WebpackVisualStudio/src/Angular2WebpackVisualStudio

Greetings Damien, grateful for any help.

related issue:
https://github.com/damienbod/Angular2WebpackVisualStudio/issues/29

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template, or open a new issue.

**Comment by damienbod** [comment]
@sokra updated
