### ISSUE TITLE
[webpack 2] module.rules is invalid

### ISSUE THREAD

**Issue by junhwong** [webpack/webpack#3451]
package.js:
```
"webpack": "^2.1.0-beta.27"
```
webpack.config.js:
```js
module: {
    rules: [
      {
        test: /\.js?$/,
        loader: 'babel-loader'
      },
    ]
```

This above configuration is ineffective, change **rules** to  **loaders** it be work.

**Comment by SpaceK33z** [comment]
Can you run `node_modules/.bin/webpack --version`? I'm 100% sure that this *does* work, people would be all over us if we would break this...

**Comment by junhwong** [comment]
Thanks, I tried again, it could work.
But I can't run `node_modules/.bin/webpack --version`. Windows?
at node_modules there are two versions of 1.x and 2.x(this time i removed 1.x), so that's wrong, node's bug ?
