### ISSUE TITLE
Error due to change in uglify js

### ISSUE THREAD

**Issue by terencechow** [webpack/webpack#3453]
Confirmed. On the latest version of webpack 2 beta 27. 

**Do you want to request a *feature* or report a *bug*?**
Bug. 

**What is the current behavior?**
Get the following UglifyJS error: 
Unexpected token: punc()) 

**If the current behavior is a bug, please provide the steps to reproduce.**
I can't reproduce it unfortunately because I dont know where in my code uglify js is causing a break but I can give direction / solutions which I leave below.

**What is the expected behavior?**
Expected behaviour is no error

**If this is a feature request, what is motivation or use case for changing the behavior?**
not a feature

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**

browser, os, node js version aren't relevant here. The issue seems to be related to Uglify JS which has upgraded their github code to 2.7.5, 10 days ago. This resulted in webpack which does not pin uglify js, to upgrade to 2.7.5 and this causes the error i'm experiencing. Currently a solution has been to fork webpack's current version and change the package.json to point to the uglify-js#harmony branch because it seems this may be related to uglifying ES6 code. Not all ES6 code has this problem but some of it does. I wonder if there could be a configuration in webpack that determines if a user wants to use uglify-js or uglify-js#harmony?

**Comment by terencechow** [comment]
After some investigation this error was caused due to using [react-measure](https://github.com/souporserious/react-measure/issues/29) which had just changed their dom  measuring library to resize-observer-polyfill a few days ago (version 1.30 vs version 1.44). Looks like that polyfill causes errors with uglify js.

**Comment by SpaceK33z** [comment]
Okay, so is there anything left in this ticket that we can change in webpack? About the switching to uglify-js#hamony thing, we are aware of that issue and looking into possibilities of removing the uglify-js plugin from the webpack core (nothing sure yet).

**Comment by terencechow** [comment]
No, we can close this ticket. This was mostly for documentation purposes
for future people who come across this error. I didn't want to close it in
case you were not aware of the uglify js harmony concerns.
