### ISSUE TITLE
webpack2 css hash code not change

### ISSUE THREAD

**Issue by lqzerogg** [webpack/webpack#3456]
I upgrade webpack 1 to webpack 2, but I got a problem.
No matter how I change my css source file, my built css files' hash code don't change at all. However, my js files' are all right.
what's the problem? Is it because I use ExtractTextPlugin? 
Can anybody tell me why?

Here's some of my configs:
//I take css file as an entry
entry[`css/${page}`] = path.join(PATH.src, `view/pages/${page}/index.scss`)
//output config
filename: BUILD || ADJUST ? '[name].[chunkhash].js' : '[name].bundle.js',
chunkFilename: BUILD || ADJUST ? 'js/[name].[chunkhash].js' : 'js/[name].bundle.js'
//extract text plugin config
new ExtractTextPlugin({
                filename: notHash ? '[name].bundle.css' : '[name].[chuxnkhash].css',
                allChunks: true
            })

**Comment by matti142** [comment]
Did you really copied your configuration? Because you made a typo in the filename option in ExtractTextPlugin: "chuxnkhash" instead of "chunkhash".

But I also upgraded to webpack 2 and the CSS/SASS doesn't compiling in watch mode any more. JS works fine. I downgraded back, because I couldn't find a solution...

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
