### ISSUE TITLE
Resolve: Unexpected token export

### ISSUE THREAD

**Issue by webmarkelov** [webpack/webpack#3457]
How resolve this error: `Unexpected token export` ?
```
module: {
  loaders: [
    {
      test: /\.js$/,
      exclude: /(node_modules|bower_components)/,
      loader: 'babel-loader?presets[]=es2015'
    }
  ]
}
```
src file:  `import {PerspectiveCamera} from 'three/build/three.modules';`

**Comment by bebraw** [comment]
There's not enough information. Can you check the issue template for instructions?

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template, or open a new issue.
