### ISSUE TITLE
Chunkhash and sourcemap link

### ISSUE THREAD

**Issue by salzhrani** [webpack/webpack#3458]
**Do you want to request a *feature* or report a *bug*?**

bug
**What is the current behavior?**
when building assets with chunkhash in the name for long term caching, changing `output.sourceMapFilename` for example will generate a different sourcemap link in the footer but the chunkhash stays the same
**If the current behavior is a bug, please provide the steps to reproduce.**

+ set `output.chunkFilename` and  `output.sourceMapFilename` to contain `chunkhash` (eg: `[name].[chunkhash:8].chunk.js`)
+ generate the bundles and note the output file names
+ without changing the contents of a source files just change the `output.sourceMapFilename`
+ rebuild
+ although the output file has different content ( different link ) the chunkhash is the same
**What is the expected behavior?**
a different chunkhash since the output file has changed.
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**

**Comment by bebraw** [comment]
Can you try this against webpack 2? Standalone repository would help.
