### ISSUE TITLE
v2: There's no bundling + tree shaking without minify-ing?

### ISSUE THREAD

**Issue by tunnckoCore** [webpack/webpack#3459]
As far as I understand last weeks.. There's no way to make a bundle that will have "tree shaking" enabled without the minifying? It not looks cool to me. I tried bundling without minifying and it seems it is not tree-shaked.

Or if it is possible, how? Some examples? I'm talking for v2.

**Comment by zhaoshengjun** [comment]
As far as I know, the tree shaking only happens in minifying. In normal bundle, you can see the part of code has been marked as `unused harmony export`, but it is still there.

Technically it can be done.

**Comment by tunnckoCore** [comment]
> As far as I know, the tree shaking only happens in minifying.

Exactly.

> In normal bundle, you can see the part of code 

Yea, seen that.

**Comment by ematipico** [comment]
Yeah I confirm, tree shaking results can be seen during final build for production.
In development, to see if three shaking is working, what I usually is to try to export a fake function from a module that you are already using:

`import { fakeFunc } from './myModule' 
console.log(fakeFunc)
`
And you should get a warning from webpack inside the console

**Comment by sokra** [comment]
You could also use `--display-used-exports`, which display information about tree shaking in the output

**Comment by tunnckoCore** [comment]
Omg, seriously. I know it is wokring, that's not the case. The case is that I want tree-shaked bundles without minifying - intentionally.

@sokra 

> display information about

What information? First it seems it does nothing for me, output is absolutely the same; Second don't want "information", I want real working bundle :D 


```zsh
~/code/foobar master ✓ ✗  
% ❯ webpack --entry ./index.js --output-filename bundle.js --target node                               December 13, 16:58:04
Hash: 9567831ddc533348d9a4
Version: webpack 2.1.0-beta.27
Time: 307ms
    Asset     Size  Chunks             Chunk Names
bundle.js  29.7 kB       0  [emitted]  null
  [15] ./index.js 2.73 kB {0} [built]
    + 15 hidden modules
~/code/foobar master ✓ ✗  
% ❯ webpack --entry ./index.js --output-filename bundle.js --target node --display-used-exports        December 13, 16:58:38
Hash: 9567831ddc533348d9a4
Version: webpack 2.1.0-beta.27
Time: 303ms
    Asset     Size  Chunks             Chunk Names
bundle.js  29.7 kB       0  [emitted]  null
  [15] ./index.js 2.73 kB {0} [built]
    + 15 hidden modules
~/code/foobar master ✓ ✗  
% ❯
```

**Comment by paztis** [comment]
I'd like to do the same. 
As the tree shaking cleanup is only done by the uglify-webpack-plugin, is there a way to let the build in dev mode, manually add the ugluify plugin and configure it to only do dead code cleanup (no mangling, no compress) ?

I search how uglify is configured in prod mode (or at least with the --optimize-minify option) and it seams to be all the default options only source-map is updated.
