### ISSUE TITLE
externals set amd not work

### ISSUE THREAD

**Issue by westfalenxqq** [webpack/webpack#3462]
config:
![image](https://cloud.githubusercontent.com/assets/8254415/21080065/4e20dfec-bfe0-11e6-9eb6-9ca73c0864f0.png)
but bundle:
![image](https://cloud.githubusercontent.com/assets/8254415/21080071/6a822092-bfe0-11e6-8830-6a5664107143.png)
expected:
![image](https://cloud.githubusercontent.com/assets/8254415/21080073/7dc06ad8-bfe0-11e6-9414-863ebc1a3142.png)

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template, or open a new issue.
