### ISSUE TITLE
Schema documentation for stats.json

### ISSUE THREAD

**Issue by walfly** [webpack/webpack#3465]
I'm working on some tools to help my company find areas to optimize our builds. I'm doing this primarily through traversing the stats file.  There's documentation on the options I can toggle on my builds, but I haven't found any good descriptions of the structure of the json itself.  For the most part it seems pretty straight forward, I imagine reasons is a list of modules that include a given module, but I'm seeing some unexpected results when I try to use moduleId and the modules array to filter reasons by chunk.  It would be very helpful to have a reference for this information.  Does this exist anywhere? If so, can it be made public?

**Comment by sokra** [comment]
Please file an issue in the documentation repo: https://github.com/webpack/webpack.js.org
