### ISSUE TITLE
webpack CLI

### ISSUE THREAD

**Issue by ev1stensberg** [webpack/webpack#3466]
# webpack CLI

## Summary 

It's no surprise that getting webpack up and running is hard. Especially for beginners. The problem often starts due lack of understanding either JS or too much configuration needed. A CLI for webpack could be a preventive action to include the ability to quickstart and to get a boilerplate up and running. 

### Acorn / AST parsers
Been discussing this with @TheLarkInn previously and the suggestion that got brought up is to make use of AST parsing. [Acorn](https://github.com/ternjs/acorn) is a good starting point. Check out [ESprima](http://esprima.org/) too, for more ways to extend Acorn. 

As mentioned, Acorn allows webpack configurations to be fine-grained and fully customizable. This is a powerful way to make sure we do not hazzle with `Readline` or `streams` in Node every time we need to make or transform webpack configurations. From [Mink](https://github.com/ev1stensberg/mink) I've learnt that if you need to make a addition to a webpack configuration you are in deep trouble. Source Code is getting more messy as well as [it doesn't work at all as expected output would be](https://github.com/nodejs/help/issues/403).

>>AST tools is therefore a big win. Dealing with direct analysis prevents development issues. 

### CLI Interface 

There's a few choices out there. [Blessed](https://github.com/chjj/blessed) and [Inquirer](https://github.com/SBoudrias/Inquirer.js) are the most proficient ones. I would suggest Inquirer. Blessed has an advanced and clutty interface and its not that pretty. Inquirer serves our need well. 

### NodeJS

This is rather obvious. NodeJS has built in support for terminal prompts, allowing us to create a custom interface with webpack goodies. Bad thing is that it takes time to do this compared against a direct usage of parity libraries.

### Organizing, Discussion and Questions 

This is definitely doable. However, webpack has a lot on their hands, it could take time, but if we as an open source community do this together (and right) we could come up with a great tool. If you have questions about the suggestion, post them. Discussion is free, keep it at a technical and relative level. 

### References 

- [Yeoman](http://yeoman.io/) - Have a look at the interface and source code
- [Webpack](https://github.com/webpack/webpack/blob/c07847dbd40967a5599ad7133600d5b5122b02e2/lib/Parser.js) - Using this internally, could be a good coherent implementation 
- [ESlint](https://github.com/eslint/eslint) - Uses espree to transform JS to AST 
- [Babylon](https://github.com/babel/babylon) - relatively similar implementation 
- [Escodegen](https://github.com/estools/escodegen) - Generate code from AST? 
- [Uglify](https://github.com/mishoo/UglifyJS) - JavaScript parser

<hr>

![skjermbilde 2016-12-12 kl 19 19 49](https://cloud.githubusercontent.com/assets/16735925/21111054/0a2a6676-c0a0-11e6-8f51-2ffd825c92d5.png)

</hr>

>>From Gitter Discussion with Kevin Partington

### Suggestion to features 

- Transform a webpack configuration v.1.x to v.2.x
- Create boilerplate setup with customizable implementation
- Add loaders and similar "high-level" features such as entry points

### Design Scheme 

- [Estree](https://github.com/estree/estree)

**Comment by TheLarkInn** [comment]
CC @pksjce @kenwheeler @webpack/contributor-team for anyone else who is interested in this. I'm marking this as a Proposal as I do believe this is something vital to improving developer experience. It wouldn't be [as a core team] our primary TO-DO item, but I believe this is a pretty important one.

**Comment by wtgtybhertgeghgtwtg** [comment]
Would it be part of  `webpack`, or another package, like `webpack-cli`?

**Comment by DanielaValero** [comment]
I'd tend to think that it would be part of a `webpack-cli` package, as the usage of it is on the cli. I'd expect that the `webpack` package contains only code that is required by webpack to work

**Comment by carlos-** [comment]
What is the main goal? bootstraping/teaching beginners or maintaining existing configurations?

For beginners some use cases:
* init - create an empty configuration (similar to `npm init` or `git init`) 
* setups - create predefined configurations and some files (similar to Yeoman)

For the second use case:
* loaders - test loaders configuration (i.e. from an entry point, list files being tested by loader X)
* validator - use the built in validation
* hints - recommend non-used features/plugins

**Comment by TheLarkInn** [comment]
We would treat this as a separate repo in webpack when the design for this proposal is complete.

**Comment by ev1stensberg** [comment]
@sokra Got any input on what you'd expect the CLI to do? 

@carlos Could have multiple benefits just not one use case. (Options)

**Comment by hemanth** [comment]
Quickly cooking up `webpack` config on the fly would be a big win!

Adding to @carlos- something like `$ webpack init --basic | --code-split | --loader=<loader>` would be a good start.

**Comment by sokra** [comment]
* https://www.npmjs.com/package/webpack-init
* https://www.npmjs.com/package/generator-react-webpack
* https://www.npmjs.com/package/generator-react-webpack-redux
* https://www.npmjs.com/package/generator-react-webpack-scaffold
* https://www.npmjs.com/package/generator-fountain-webpack
* https://www.npmjs.com/package/generator-react-webpack-alt
* https://www.npmjs.com/package/generator-webpack-versatile
* https://www.npmjs.com/package/generator-webpack-es6-cssnext
* https://www.npmjs.com/package/generator-webpack-2-typescript
* https://www.npmjs.com/package/generator-express-webpack
* https://www.npmjs.com/package/generator-react-webpack-transmit
* https://www.npmjs.com/package/generator-webpack-js-module
* https://www.npmjs.com/package/generator-webpack-library
* https://www.npmjs.com/package/generator-webpack-starter

**Comment by ev1stensberg** [comment]
Yeoman seems to have a pretty good solution. Alternatives could be to have an umbrella solution like they have. 

This is a personal que, but `webpack-cli` should only be concerned about core traits. Loaders, entry points and what you'll get from `webpack-init`. Generalizing, a webpack config should at most; reflect a "get started" experience, such as "create-react-app". One of the challenges would be flexibility, but also limit to what webpack has a responsibility to do explicitly. If that's somewhat unclear, I'd be happy to rephrase 👍

**Comment by pksjce** [comment]
I think this is a great idea! `webpack`'s current CLI is very limited and is a green avenue for improvement of dev experience!

### Features
Other than the standard configuration options,
set of features that `webpack-cli` should have are 

#### `init`

A way to build a basic `webpack` configuration. Exactly like [`webpack-init`](https://www.npmjs.com/package/webpack-init). We need to cover the following.
1. Add entry point and output path.
2. Add prewritten configs to add babel support, css/scss/less support, hmr and so on.
3. Allow to add DEV and PROD configurations. 

This should build an annotated webpack configuration file.

#### `add <setup-name>`

Adds prewritten config setup to add new loaders, plugins

#### `generate <plugin|loader|setup> <options>`

Like `ember generate` where it can add scaffold for the user to fill up functionality.

#### `<multiple config options> --save <config-name>`

Save the working config options to the existing `webpack` config file or create a new config file. Need also an override to rewrite configs.

#### `validate <config-name>`

Validate existing configuration using webpack's schema validator, give meaningful error messages. Nice to have would be to give helpful improvement hints.

#### `help <option>`

Kickass help with elaborate examples.

### Implementation

@ev1stensberg - However I don't understand why we need to use an AST parser in the CLI? Maybe I'm missing something.

I think `inquirer` only gives an interface for interactive CLI.
Current webpack CLI, uses `yargs` to handle CLI specific features like parsing the options and providing help information. We can use the same too. I don't know about viable alternatives though.

I think the CLI can actually tap into `WebpackOptionsApply` and start a webpack `Compiler` directly. This way we can have maximum flexibility in the input and output formats.

**Comment by ev1stensberg** [comment]
@pksjce Nice walkthrough! 

**AST parsing would be behind the scenes to validate configuration files. AST parsing allows us to transform files better and more accurately than using streams or similar in Node.**

>> Current CLI, uses `yargs`...

Could look into `Babel-CLI`, `Babylon` or `Yarn` to see what they've done. 

We could indeed use that, gives us the possibility to do something like creating a temp folder similar to how`create-react-app` is built.

**Comment by SpaceK33z** [comment]
@ev1stensberg could you explain why we need AST parsing when we already have a built-in validator with [ajv](https://github.com/epoberezkin/ajv)?

**Comment by pksjce** [comment]
^ +1

Also yes, `yarn` uses [`commander`](https://www.npmjs.com/package/commander), so we can have pros and cons between `commander` and `yargs` to pick one for implementation.

**Comment by ev1stensberg** [comment]
Right, I was thinking about the transformation, to support conversion from v.1.x to v.2.x. @TheLarkInn told me that the implementation in webpack is heavily using Acorn. My main concern is how we change/add/remove config items so we could build upon existing webpack configurations. This may due my lack of understanding, if there's a better way, then elaborate 💯 

1. Acorn for AST parsing
2. [JScodeshift](https://github.com/facebook/jscodeshift) to transform back to JS after modding. 

I was looking at the acorn documentation, but found no method on converting back to javascript. 

Ajv would work for validating configurations, but the AST parsing was more meant to target how we can change existing webpack configurations. (Me missing a key point there, context)

**Comment by kenwheeler** [comment]
If the tool was strictly `init`, I would say put it in core. For the config upgrades and scaffolding, `webpack-cli` would definitely make sense. I have a strong preference for `commander` and `inquirer` but with `yargs` already in place it might makes sense to use that instead of `commander`. 

I feel like 99% of the value add here would be the initial config dump. A lot of the 'fatigue' is from people trying to roll their own, or pasting someone else's config without understanding it. I rarely start a package.json from scratch, but build upon the one provided by `npm init`. I think there is an opportunity here to spit out a valid base config that people could then hit the docs and customize to their liking.

Another fun piece might be, based upon selected options, installing selected loaders and adding an idiomatic loader entry for each.

**Comment by TheLarkInn** [comment]
> @ev1stensberg could you explain why we need AST parsing when we already have a built-in validator with ajv?

@SpaceK33z I suggested this so that the tool wouldn't update, modify existing configs just using string replacement, rather since it is JS/Code for these configs that we leverage an AST tool like acorn to find pieces that need to be modified etc.

**Comment by pksjce** [comment]
Oh! I get it. Because different config setups can overlap, we can parse the
existing webpack config with an ast parser and handle changes.

**Comment by ev1stensberg** [comment]
# Questions that needs to be resolved
###### Some of which has already been mentioned (anything that needs to be added?)

### Parity

- [ ] What's good to include in this project, what is not? 
- [ ] Is the project worth pursuing? Why, and how does this differ from Yeoman?
- [ ] What to expect from this tool and the opposite
- [ ] Additional Questions(?)
### Tools

- [ ] What tools are we going to use?
- [ ] Why those tools?
- [ ] Project structure relative to estree spec(?) 
- [ ] `Yargs` or `Commander`
- [ ] User Interface 

### AST Parsing

- [ ] Is AST parsing show legit tradeoffs? 
- [ ] Tooling Decisions has to be resolved

### Planning

- [ ] How to utilize tradeoffs 
- [ ] Code Reusability ( Webpack Compiler and Ajv was mentioned )
- [ ] Project Structure and Future Planning

**Comment by wtgtybhertgeghgtwtg** [comment]
One argument for `commander` over `yargs` is the dependency graph.
`yargs`: http://npm.anvaka.com/#/view/2d/yargs
`commander`: http://npm.anvaka.com/#/view/2d/commander
`uglify-js` actually uses an older version of `yargs` [because the newer version has tripled in size](https://github.com/mishoo/UglifyJS2/pull/1302#issuecomment-248611354).

**Comment by michael-ciniawsky** [comment]
```bash
webpack init
```

Inits a basic webpack.config.js similiar to `npm init`

```bash
webpack init --config vue
```

Where `vue` refers to a npm package `webpack-config-vue` , which is a common webpack config template the CLI can scaffold and **manage** afterwards.

**Comment by wtgtybhertgeghgtwtg** [comment]
If `webpack` and `webpack-cli` will be separate packages, does that mean that the existing CLI in `webpack` will be removed?  It would reduce the number of packages required for people who use `webpack` without the CLI, but it would be breaking, so it would have to go in before `webpack@2.0.0` is published or wait until `webpack@3.0.0`.
One project of note that could benefit from this would be [`create-react-app`](https://github.com/facebookincubator/create-react-app), which does not use the CLI.

**Comment by TheLarkInn** [comment]
Also some things to consider:

### Env Configs:
Taking into consideration that many people will likely want to create configs for any env, however env's have to be not just boiled down to prod and dev and test, but whatever they would like.

This to me feels like the greatest challenge in terms of complexity. Should a `webpack --init` create 3 configs that default to base/common, dev and prod? 

Something to think about at least.

**Comment by pksjce** [comment]
`init` is a beginners only option and should stick to PROD and DEV env variables and make the distinction only where necessary. For eg - for output filename, the PROD behaviour should be a good hash name but for DEV mode it should be the chunk name. For sourcemaps, the setup config will only add `devtool` option to DEV mode.

We can develop general scaffolding capabilities to cover complex cases in `generate` mode? The plan is to anyway provide for accepted best practices as prewritten setup config. Generating env specific config should be moved there.

**Comment by michael-ciniawsky** [comment]
```
| – .webpack
|    | – modules
|    | – plugins
|    | – server.js
|    | – [common || template].js
|    | – production.js (NODE_ENV=production || webpack --production)
|    | – development.js (NODE_ENV=development || webpack)
| – ...
|- webpack.config.js (generated)
```

**Comment by pksjce** [comment]
Shouldn't the generated webpack config be human friendly as we are advocating consumers to tweak and hack on the base we provide?

**Comment by ev1stensberg** [comment]
@wtgtybhertgeghgtwtg Good point. I know babel is doing this at [`core`](https://github.com/babel/babel/tree/master/packages/babel-cli).

>> Should a webpack --init create 3 configs that default to base/common, dev and prod?

I agree with @pksjce and @kenwheeler. We should primarily care about creating the config, and the rest is optional. ( Could Introduce more complexity through flags or a `.rc` template?)

**Comment by aight8** [comment]
I have additional ideas for webpack CLI.

## webpack resolve <request>

Could output the resolve stack:

```js
webpack resolve xyz
Resolve for requested query ""
1. /app/to/path/src/xyz (not exists)
2. /app/to/path/src/xyz.js (not exists)
3. /app/to/path/src/xyz.jsx (not exists)
4. /app/to/path/src/node_modules/xyz (not exists)
5. /app/to/path/node_modules/xyz (found)
```

Reason:
- Debugging
- Understanding how the resolver works
- Performance optimization

Changes:
- Could be hard to implement because the resolver must log every try. Custom resolver must log tries too otherwise it's not listed here.

**Comment by pksjce** [comment]
@aight8 - We might be able to log this because `enhance-resolve` definitely has some kind of internal logging for every try it makes. Though, I'm not sure whether it can be exported out of the package easily. Custome resolvers may not be supported here.

Overall good idea though! 👍

**Comment by sokra** [comment]
yes you can use the enhanced-resolve logging for this.
