### ISSUE TITLE
Initialize bundle using requestIdleCallback

### ISSUE THREAD

**Issue by klimashkin** [webpack/webpack#3467]
Hi there!

Now, if you have pretty big application (thousands modules) and therefore bundle size, it takes significant amount of time to evaluate this bundle in browser.
For example, our application is being evaluated for about 400-600ms on every page load.
Of course, we can split bundle into chunks, but anyway, because of a lot of core modules inside it (own and npm dependencies) we ended up with about 300-400ms of evaluation time.

It is pretty annoying for user, for these time webpage is frozen for him - TTI is big even if SSR is used.

What if try evaluating bundle (each module in it) using [requestIdleCallback](https://developer.mozilla.org/en-US/docs/Web/API/Window/requestIdleCallback)?

There are a lot of question about safety, though, for example how to say module that other modules, which it depends on, is ready and so on.

**Comment by sokra** [comment]
Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md).
