### ISSUE TITLE
[Question] Is it possible to enable quiet mode with a multi compiler config?

### ISSUE THREAD

**Issue by DylanPiercey** [webpack/webpack#3468]
I use webpack with gulp so I typically set the `quiet` option to true to avoid multiple logs.

I am looking to use the multi compiler config (config as an array) but would like to keep this option.
By default it seems that using the multi compiler config does not allow for me to enable quiet mode.

Is there a way to enable quiet mode while working with a multi compiler config?

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
