### ISSUE TITLE
Add option to exclude files from performance check

### ISSUE THREAD

**Issue by egoist** [webpack/webpack#3469]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
webpack throws warning when generated sourcemaps file exceeds max file size.

**What is the expected behavior?**
Add an option to exclude sourcemaps from performance check or exclude them by default.

**If this is a feature request, what is motivation or use case for changing the behavior?**
sourcemaps files would not impact web performance.

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**
webpack@2.1.0-beta.28

**Comment by TheLarkInn** [comment]
Certainly. I'm going to start by just filtering .map files out of the equation, but I think down the road we may want to let the user control what kind of files they filter out with maybe `/\.map$/` being the default.

**Comment by TheLarkInn** [comment]
Once I merge the tied PR, let's sketch out a good idea that makes it easy for the user to configure meanwhile still having a reasonable default.
