### ISSUE TITLE
Update webpack performance recommendations message to suggest using `import()`

### ISSUE THREAD

**Issue by danhayden** [webpack/webpack#3470]
version v2.1.0-beta.28 [release notes](https://github.com/webpack/webpack/releases/tag/v2.1.0-beta.28) suggest using `import()` for  code splitting instead of `System.import`

> add import() as Code Splitting construct. It should be used instead of System.import when possible. System.import will be deprecated in webpack 2 release (removed in webpack 3) as it's behavior is incorrect according to the spec.

 however the performance recommendations message currently suggest using `System.import`

![image](https://cloud.githubusercontent.com/assets/1385253/21143679/8e9fcadc-c13f-11e6-9e86-096d6bb1a211.png)

**Comment by TheLarkInn** [comment]
Didn't expect `import()` to land at the same time as this, so yes I can certainly add that.

**Comment by Chrazy** [comment]
The 'performance.hints' option needs to be documented. Took me a while to find it in the release notes.

**Comment by ij-ami** [comment]
@Chrazy Agreed, I couldn't even find it in the release notes. Started getting performance warnings in my build output and had no idea how to turn them off. Performance is not a concern for the app in question so I'd prefer to do without them.

For anybody else who lands on this page and is looking for it... Set the following in your webpack config:
```
performance {
    hints: false
}
```

**Comment by foxxyz** [comment]
@Chrazy Agreed, I couldn't even find it in the release notes. Started getting performance warnings in my build output and had no idea how to turn them off. Performance is not a concern for the app in question so I'd prefer to do without them.

For anybody else who lands on this page and is looking for it... Set the following in your webpack config:
```
performance {
    hints: false
}
```
