### ISSUE TITLE
Webpack2-React Code Splitting with multiple levels of child links does not work

### ISSUE THREAD

**Issue by sandye** [webpack/webpack#3473]
Hello everyone, I am facing some issue with code-splitting in one of my react application, I put the details here
http://stackoverflow.com/questions/41087142/reactjs-webpack2-code-splitting-with-nested-routes

it would be great if someone can let me know if I am making anything wrong here, or its something wrong with the webpack building

I am using  "webpack": "^2.1.0-beta.26",

Please let me know if you need anymore information.

**Comment by stevewillard** [comment]
getComponent returns a promise. You don't need the callback from react-router. I think you want something like this:
```
getComponent: () =>
    System.import('pages/LoginPage/LoginPage')
          .then((module) => module.default)
```

**Comment by sokra** [comment]
Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md).
