### ISSUE TITLE
Default to use NamedModulesPlugin when not building for production

### ISSUE THREAD

**Issue by SimenB** [webpack/webpack#3476]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Module ids are numbers, making it unusable in HMR, and less useful than it could be when stepping though the code in the browser.

**If this is a feature request, what is motivation or use case for changing the behavior?**
I know there's a warning printed when using HMR and not the named plugin (https://github.com/webpack/webpack/commit/6b4ced42ad5394c32c900e09695876c9559d063c), but it's useful also for bundles in the browser. The only time you might _not_ want it is in production builds, because numbers take up fewer bytes, but then I think `NamedModulesPlugin` should just check for `minimize`-mode, and noop in that case.

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**
N/A

Ref: facebookincubator/create-react-app#1228

**Comment by ArcEglos** [comment]
I tried to implement this but stumbled on the problem that i couldn't find any reliable way to detect if we are doing a production build.
I suppose adding an additional flag in the config to disable naming the modules by name is no option, so it would be nice if somebody could give me some guidance what the behavior should be.

**Comment by syndbg** [comment]
@ArcEglos Isn't `process.NODE_ENV === 'production'` the de facto standard way to go?

**Comment by ArcEglos** [comment]
I thought so, too. But as process.NODE_ENV isn't used anywhere in the codebase I guess that's not the way to go.

**Comment by SimenB** [comment]
Can you check for `minimize` mode? Although I seem to recall reading somewhere that globally turning on minimize is going to disappear.

**Comment by timse** [comment]
i dont think this will happen, and it is fairly simple to achieve yourself by adding `new webpack.NamedModulesPlugin()` to your plugins :).
Will close for now.

**Comment by SimenB** [comment]
The point isn't that it's easy to do yourself, the point is that webpack has a bajillion options and plugins, and making the default experience better should be done whenever possible.
If anything, it should be the default all over, and you can switch to using numbers manually if you want to for production

**Comment by timse** [comment]
I did have discussions about this before, (and I admit I am completly on your side :) ).
Feel free to reopen, I just try to clean up a bit :)

**Comment by SimenB** [comment]
I'm not allowed to reopen, probably because it was closed by a mod.

And it's completely fair to clean up! 😄

**Comment by alexilyaev** [comment]
I'd like to second @SimenB on this, would be great to have 1 less thing to worry about in our Webpack config.
I think that `--optimize-minimize` and/or `process.env.NODE_ENV=production` are safe to rely upon, as `-p` already enables them.

**Comment by danny-andrews** [comment]
@syndbg I think `process.env.NODE_ENV=production` is what you were looking for, not `process.NODE_ENV=production`.

**Comment by PixnBits** [comment]
@ArcEglos FWIW docs mention [`--env.production` etc options](https://webpack.js.org/configuration/configuration-types/#exporting-a-function-to-use-env)

**Comment by SimenB** [comment]
FWIW, according to the release notes of webpack 4 `NamedModulesPlugin` is now enabled by default for development
