### ISSUE TITLE
Webpack 2 performance regression for dev builds

### ISSUE THREAD

**Issue by skovhus** [webpack/webpack#3480]
First, thanks for a great project! 

I'm not sure you are aware of this issue, but I wanted to let you know. When trying out 2.1.0-beta.2x on a larger project I saw a rather severe performance regression for development builds. (Production builds are faster in webpack 2). 

Consecutive development builds were 2x slower than webpack 1.13.3. First time build with a cold cache is also rather slow compared to version 1.

I've tried running `--profile` but don't know what to look for. 

So I've demonstrated this here https://github.com/skovhus/webpack-2-slowness 

OS: Max OS X 10.10.5 
Node: v7.0.0
Yarn: 0.17.9

Is this expected behaviour? 

Let me know if I can help.

**Comment by sokra** [comment]
see also #3428

**Comment by gustavohenke** [comment]
That was a serious performance improvement @sokra. Nice! 👍 

I was experimenting with webpack 2.1.0-beta.28 yesterday using an existing project and the same config, and the compilation time went from 300 ms to 1 second.

With 2.2.0-rc.0, the compilation time went back to 300 ms.

**Comment by skovhus** [comment]
I've updated my performance metrics in https://github.com/skovhus/webpack-2-slowness

2.2.0-rc.0 looks good, specially the rebuilds.

#### Webpack 1.14.0

First/cold: 4.1 s
Consecutive builds: 2.1 s
Watch mode rebuilds: ~180 ms.


#### Webpack 2.1.0-beta.28

First/cold: 5.1 s
Consecutive builds: 4.0 s
Watch mode rebuilds: ~250-320 ms.

#### Webpack 2.2.0-rc.0

First/cold: 3.8 s
Consecutive builds: 2.7 s
Watch mode rebuilds: ~110 ms.


OT @sokra was it a deliberate decision to show performance hints when running in watch mode?

**Comment by yerol** [comment]
Just an FYI @sokra, using webpack 2.5.1 currently and my watch reload was around 400msec. After upgrading babel-core from 6.23.1 to 6.24.1 with exactly the same setup/code, I have seen watch reloads spiking up to 14secs! I had to downgrade again..
