### ISSUE TITLE
[Bug] A syntax error causes the module always build failed even after fixed the error

### ISSUE THREAD

**Issue by XuJinNet** [webpack/webpack#3487]
there is a simple demo:
https://github.com/XuJinNet/webpack-test

main.js, make a syntax error:
```javascript
class A {
	constructor() {

	}

	func1() {
		console.log('money 💰😊');
	}
}

const a = new A();
a sdfsd .func1();
```
then get the error from webpack:
![a3878e5c-42f4-4cc2-af72-4951aea96345](https://cloud.githubusercontent.com/assets/442382/21215229/ce36389c-c2da-11e6-92be-d2a8bc1f5fad.png)

after fixed the error, refresh the page then get the error the same as above.

WebPack: 2.2.0-rc.0
webpack-dev-server: 2.1.0-beta.12
babel-loader: 6.2.9

**Comment by uncleyo** [comment]
I experience the same without webpack-dev-server: webpack cannot forget errors in watch mode.

This seems to be a regression in `rc.0` as I cannot reproduce this in `beta.28`.

**Comment by gunn** [comment]
Can confirm this being a new problem in `2.2.0-rc.0`. I now need to restart the process after every caught syntax error.

**Comment by uncleyo** [comment]
Apparently, this was fixed in `rc.1` by https://github.com/webpack/webpack/commit/ea3b2303a87a33a0430a6ed2ff0d6ffb0a70afbd

**Comment by gunn** [comment]
`2.2.0-rc.1` has fixed it for me. Thanks @sokra!

**Comment by bebraw** [comment]
Closing as this was fixed.
