### ISSUE TITLE
DllReferencePlugin can't find the correct path when node_modules use softlink

### ISSUE THREAD

**Issue by starInEcust** [webpack/webpack#3489]
**What is the current behavior?**
I have a project that uses the DllReferencePlugin to build locally without problems. However, when building on the server, because node_modules is not in the project root directory, but with a soft link to use. This causes DllReferencePlugin to not find the correct path for the module.

```
// vendor folder in the root directory
// plugin config
new webpack.DllReferencePlugin({
    context: '../vendor',
    manifest: require('./vendor/vendor.manifest.prod.json'),
}),
```

```
// vendor.manifest.json just like this
{
  "name": "vendor_library",
  "content": {
    "../node_modules/redux-router/lib/isActive.js": "9dd92fd3",
    "../node_modules/react/lib/React.js": "f8ea68d2",
    "../node_modules/react/node_modules/object-assign/index.js": "355e2776",
    "../node_modules/react/lib/ReactChildren.js": "a0328d9b",

```
**What is the expected behavior?**
I can not figure out the dll module has been in the vendor.js, why DllReferencePlugin also need to find the local node_modules. Is there any way not to find the local module, or it can find the soft link node_modules

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**
node_version: 6.9.1
webpack_version: 1.13.0

**Comment by zhiyan** [comment]
I have the same problem,  i must change the context config of DllReferPlugin with the absolute path of the source node_modules' parent directory to make it work normally
