### ISSUE TITLE
With bail: true, an error in one module should abort building all other modules too

### ISSUE THREAD

**Issue by gaearon** [webpack/webpack#349]
With current behavior, when error occurs with `bail: true`, callback is immediately invoked but other modules are still being built.

This is a problem when wepback is part of a build script (or a Gulp/Grunt task) because, if you use `ProgressPlugin` to report module build status, the error message gets buried above progress messages from successfully built modules. It also paralyzes the prompt until all modules are built.

Ideally, an error occuring with `bail: true` should abort all other modules as well.

**Comment by TheLarkInn** [comment]
@gaearon: Dan, is this actually still an issue (boy this is an oldie). We are cleaning house on the issues list, and wanted to make sure. 

@sokra do we want to feature this into our backlog?
