### ISSUE TITLE
*feature* Throw Error with missing module name instead of "Cannot read property 'call' of undefined"

### ISSUE THREAD

**Issue by crucialfelix** [webpack/webpack#3490]
webpack 2.2.0.rc.0 and earlier

We've all gotten missing module errors due to various mis-configurations, commons chunks juggling etc. ( See https://github.com/webpack/webpack/issues/959 for many of them )

The problem is that we don't know which module is missing, just moduleId=47

This line is a common failure point:

```js
      // Execute the module function
        /******/
        modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
```

In development mode I think it would be worthwhile to include a map of module ids to names so that an error can be thrown here with the name of the missing module.

I can open http://localhost:3000/__webpack_hmr and look it up `"47":"./~/jquery/dist/jquery.js"` but it took me a long time to figure that out.

**Comment by Kovensky** [comment]
In the meanwhile, `NamedModulesPlugin` can help with debugging in development.

**Comment by crucialfelix** [comment]
That definitely helps ! Thanks.

![screen shot 2016-12-15 at 12 02 49](https://cloud.githubusercontent.com/assets/218738/21221680/ac062c8a-c2be-11e6-9864-16f6454f188d.png)


But still an Error isn't thrown when `modules[moduleId]` is `undefined`.

I still get:

```
webpack-inline-manifest.js:1153 Uncaught TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (webpack-inline-manifest.js:1153)
    at fn (webpack-inline-manifest.js:194)
    at Object.6 (vendor.js:3960)
    at __webpack_require__ (webpack-inline-manifest.js:1153)
    at webpackJsonpCallback (webpack-inline-manifest.js:43)
    at vendor.js:1
__webpack_require__ @ webpack-inline-manifest.js:1153
fn @ webpack-inline-manifest.js:194
6 @ vendor.js:3960
__webpack_require__ @ webpack-inline-manifest.js:1153
webpackJsonpCallback @ webpack-inline-manifest.js:43
(anonymous) @ vendor.js:1
```

Which means many more steps to figure out what went wrong. The noob still doesn't know what the problem is.

**Comment by crucialfelix** [comment]
Something like:

```js
var m = modules[moduleId];
if (typeof m === 'undefined') {
 throw new Error(`Module ${moduleId} not found`);
}
m.call(module.exports, ... )
```
