### ISSUE TITLE
Webpack2 UglifyJsPlugin not working.

### ISSUE THREAD

**Issue by huyaxiong** [webpack/webpack#3492]
webpack.config.js
```
var path = require('path');
var webpack = require('webpack');
var autoprefixer = require('autoprefixer');
var HtmlWebpackPlugin = require('html-webpack-plugin');


module.exports = {

    entry: {
        vendor: ["pixi", 'pixi-particles'],
        app: ['./scss/main.scss', './js/main.js']
    },
    output: {
        path: path.resolve(__dirname, './dist'),
        publicPath: '/dist/',
        filename: 'app.js'
    },
    module: {
        rules: [
            {
                test: /\.vue$/,
                loader: 'vue-loader'
            },
            {
                test: /\.js$/,
                loader: 'babel-loader',
                options: {
                    "presets": [
                        "es2015"
                    ]
                },
                include: [
                    "./js"
                ]
            },
            {
                test: /\.css$/,
                use: [
                    "style-loader", "css-loader"
                ]
            },
            {
                test: /\.(png|jpg|gif|svg|ttf)$/,
                loader: 'file-loader',
                options: {
                    name: '[name].[ext]?[hash]'
                }
            },
            {
                test: /\.scss$/,
                use: [
                    "style-loader", "css-loader", 'postcss-loader', "sass-loader"
                ]
            }
        ]
    },
    resolve: {
        alias: {
            'pixi': 'pixi.js/dist/pixi.min.js',
            'pixi-particles': 'pixi-particles/dist/pixi-particles.min.js'
        }
    },
    devtool: 'cheap-module-eval-source-map',
    plugins: [
        new webpack.optimize.CommonsChunkPlugin({
            name: "vendor",
            filename: "vendor.js",
            minChunks: Infinity
        }),
        new webpack.optimize.OccurrenceOrderPlugin(),
        new HtmlWebpackPlugin({
            template: 'index.html',
            inject: 'head'
        })
    ]
};

if (process.env.NODE_ENV === 'prod') {

    module.exports.devtool = false;
    module.exports.plugins = (module.exports.plugins || []).concat([
        new webpack.optimize.UglifyJsPlugin({
            compress: {
                warnings: false,
                pure_funcs: ['console.log', 'window.console.log.apply']
            },
        }),
    ])
}
```

package.json
   "build": "cross-env NODE_ENV=prod webpack --progress -p"

And after I run command npm run build.

![image](https://cloud.githubusercontent.com/assets/6245250/21226073/e60801ec-c30e-11e6-85f7-02188a1953bf.png)

Codes didnt compressed.

**Comment by bebraw** [comment]
Which version of webpack 2 are you using? Can you provide a standalone project to test? Thanks.

**Comment by huyaxiong** [comment]
Hey,I am using the newest version of webpack2, And Also I found the reason why caused this is because of the two dependencies in my project which are pixi.min.js & pixi-particles.min.js.And the pixi.min.js has AMD support which will export a PIXI object,but "pixi-particles" file just an IFFE,which after it executed it will add a property "particles" in PIXI object.
And if I put these two files in CommonsChunk it will not compress the code but works fine in the browser but if I dont do it like this way,for example only output one file app.js but not to separate them into vendor.js and app.js,it will throw me an error 

    "Uncaught TypeError: __WEBPACK_IMPORTED_MODULE_0_pixi__.particles.Emitter is not a constructor"

So how can I handle the situation like this?

**Comment by huyaxiong** [comment]
Hi,I changed some files like this

webpack.config.js
```
 entry: {
        // vendor: ["pixi", 'pixi-particles'],
        app: ['./scss/main.scss', './js/main.js']
    },

  new webpack.ProvidePlugin({
            PIXI: 'pixi',
        }),
        // new webpack.optimize.CommonsChunkPlugin({
        //     name: "vendor",
        //     filename: "vendor.js",
        //     minChunks: Infinity
        // }),
```

main.js
```
import * as p from 'pixi-particles';
import {loader, Texture, Container, particles} from "pixi";
```

And finally it also works fine through webpack-dev-server,but when I try to build with UglifyJsPlugin,it will throw me an error like this:
```    
ERROR in app.js from UglifyJs
SyntaxError: Unexpected token: name (emitter) [app.js:17446,4]
```
also the file is super big 4.1MB,so how can I do it in the right way?

**Comment by SpaceK33z** [comment]
Does the issue also happen if you change `devtool: 'cheap-module-eval-source-map'` to `devtool: false`?

**Comment by huyaxiong** [comment]
@SpaceK33z 4.1MB runs well by webpack-dev-server in the browser,but after added this configuration parameters

```
    module.exports.devtool = false;
    module.exports.plugins = (module.exports.plugins || []).concat([
        new webpack.optimize.UglifyJsPlugin({
            compress: {
                warnings: false,
                pure_funcs: ['console.log', 'window.console.log.apply']
            },
        }),
    ])
```

the file size will reduce to 1.7MB but it will throw an error and not working anymore.
```
ERROR in app.js from UglifyJs
SyntaxError: Unexpected token: name (emitter) [app.js:17446,4]
```
I think its UglifyJsPlugin caused this or may there is another way to process this situation but I dont know how,I searched stackoverflow for several hours this afternoon but still cant work it out.

**Comment by SpaceK33z** [comment]
I can't reproduce this, so you'll need to provide a demo repo. Note that this is probably not webpack's fault.

**Comment by sokra** [comment]
Please see `app.js` line `17446`. There is probably some ES2015 stuff that's not supported by uglifyjs.

**Comment by huyaxiong** [comment]
@sokra its not, emitter is represented "let emitter =  new PIXI.particles.Emitter" from "pixi-particles.js" file.

pixi.js file export PIXI object(with amd support)
pixi-particles.js file is an IFFE add particles property to the PIXI object(without amd support)

please read whole dialogue carefully...its the question about how to use webpack load a amd supported file and a file without amd supported but is a "plugin" of previous one.When I try to using these two files in the way I paste above,webpack-dev-server runs it fine,but UglifyJsPlugin cannot handle it.

**Comment by huyaxiong** [comment]
@SpaceK33z  https://github.com/huyaxiong/test2
after installed dependencies, open like http://localhost:8080/dist/

**Comment by lilonghe** [comment]
` webpack -p ` also dosn't work.
i got this
```
ERROR in bundle.js from UglifyJs
SyntaxError: Unexpected token: name (courseList) [./app/main.js:1,0]
```
main.js
```
import courseList from './modules/course/course-list';
```
courseList.js
```
class CourseList {
	constructor() {
		console.log('Hello');
	}
}
var courseList = new CourseList();
export default courseList;
```

**Comment by huyaxiong** [comment]
any news?

**Comment by huyaxiong** [comment]
Alright,I solved it single-handedly.Because I missed one .babelrc file,so babel-loader didnt work.
```
{
  "presets": ["es2015"],
  "plugins": ["transform-runtime"],
  "comments": false
}
```

**Comment by elfoak** [comment]
It seems webpack@2.2.0-rc.1 doesn't read

```
   options: {
       "presets": ["es2015"],
   },
```

Appending `presets` param directly works fine:
```
{
        test: /\.(js|jsx)$/,
        use: 'babel-loader?presets[]=es2015',
        exclude: /(node_modules|bower_components)/,
      },
```

https://github.com/joeeames/WebpackFundamentalsCourse/issues/3#issuecomment-268825328

**Comment by sokra** [comment]
#3556

**Comment by codelegant** [comment]
You should install `uglifyjs-webpack-plugin`, https://webpack.js.org/plugins/uglifyjs-webpack-plugin/
