### ISSUE TITLE
Rule with resourceQuery when there's no query

### ISSUE THREAD

**Issue by daltones** [webpack/webpack#3497]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
It's impossible to perform a rule based on `resourceQuery` condition if a module has no query at all. That module won't pass directly.

**If the current behavior is a bug, please provide the steps to reproduce.**
I have this case where there are resources of the same extension that some are loaded in a certain way an some in another. I can reach it using resource queries.

So I can write some config like this:
```js
{
  module: {
    rules: {
      {
        test: /\.ext$/i,
        resourceQuery: {
          exclude: /\?another/i,
        },
        loader: 'normal-loader'
      },
      {
        test: /\.ext$/i,
        resourceQuery: /\?another/i,
        loader: 'another-loader'
      }
    }
  }
}
```

So I want that `.ext` files get loaded with `normal-loader`. _Except_ the ones with `?another` query, these will load with `another-loader`.

But here's the result:
* `path/to/module.ext?another`: loaded with `another-loader`
* `path/to/module.ext?asdfg`: loaded with `normal-loader`
* `path/to/module.ext`: **none**, but we were naturally expecting `normal-loader`

I guess there's a problem with the logic around here:
https://github.com/webpack/webpack/blob/v2.2.0-rc.0/lib/RuleSet.js#L361
It's skipping the condition and rejecting directly if `resourceQuery` is empty and there's a condition.

**What is the expected behavior?**
It must be able to test a `resourceQuery` condition in an empty query.

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**
Node.js: v7.2.1
Webpack: v2.2.0-rc.0

**Comment by sokra** [comment]
You can workaround this with a `oneOf` rule.

**Comment by satazor** [comment]
I also find this not very intuitive and using `oneOf` adds a lot of duplication to rules in this scenario. 
My use case was to support `foo.svg`, `foo.svg?` on rule X and `foo.svg?inline` on rule Y.

To avoid duplication I used `babel-plugin-transform-rename-import` like so:

```
                    [require.resolve('babel-plugin-transform-rename-import'), {
                        original: '^(.+)\\.svg$', replacement: '$1.svg?',
                    }],
```

**Comment by adrianmarinica** [comment]
I ended up doing something like this for a similar issue I had. The fact that I had to move the specific files to a different folder didn't really help, but hey, at least it works.

```javascript
          {
                test: /\.svg$/,
                oneOf: [
                    {
                        exclude: path.resolve(__dirname, 'images/svg/css-icons/'),
                        use: 'svg-inline-loader'
                    },
                    {
                        include: path.resolve(__dirname, 'images/svg/css-icons/'),
                        use: 'file-loader'
                    },
                ],
            },
```

**Comment by calledT** [comment]
```js
{
  test: /\.(png|jpe?g|gif|svg)$/,
  oneOf: [
    {
      resourceQuery: /inline/, 
      loader: 'url-loader',
      options: {
        limit: 10000,
        name: 'img/[name].[hash:7].[ext]'
      }
    },
    {
      loader: 'file-loader',
      options: {
        name: 'img/[name].[hash:7].[ext]'
      }
    }
  ]
}
```
> An array of Rules from which only the first matching Rule is used when the Rule matches.

May this config help you

* path/to/foo.png?inline:  loaded with url-loader
* path/to/foo.png?other:  loaded with file-loader
* path/to/foo.png:  loaded with file-loader

**Comment by dooks** [comment]
It was requested I address this issue in #5906 https://github.com/webpack/webpack/issues/5906

**Comment by qhxin** [comment]
same problem

**Comment by evilebottnawi** [comment]
PR welcome

**Comment by vankop** [comment]
@sokra Is this issue relevant to `webpack@5` (since `RuleSet` is reworked in `webpack@5`)? I could take a look on it, if it is relevant.

**Comment by evilebottnawi** [comment]
bump

**Comment by maciej-gurban** [comment]
In case somebody else stumbles upon this looking to **apply different loaders based on import path**, the solution is pretty much what @calledT showcases in his [answer](https://github.com/webpack/webpack/issues/3497#issuecomment-331463800).

What's important though, is that you're not limited to using `resourceQuery` to apply different rules - you can use `test`, `include` etc. - all the same API surface that each regular rule inside `module.rules` allows for.

**Comment by vankop** [comment]
@evilebottnawi such syntax is not possible with `webpack@5`, so I think this can be closed.
