### ISSUE TITLE
Watch mode not working in 2.2.0-rc.0

### ISSUE THREAD

**Issue by skovhus** [webpack/webpack#3500]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Watch mode is not able to recover after an error in a file (at least for JSX errors).

**If the current behavior is a bug, please provide the steps to reproduce.**
See simple example application of how to reproduce it here https://github.com/skovhus/webpack-2-slowness/tree/watch-mode

**What is the expected behavior?**
Watch mode should work, i.e. rebuild the file after the error in the source code is fixed.

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**
- OS: Max OS X 10.10.5
- Node: v7.0.0
- Yarn: 0.17.9
- Webpack: 2.2.0-rc.0

**Comment by SpaceK33z** [comment]
Two questions:

- Was this working in the latest 2.1.0 beta?
- Could you try if this does work in Node v6? There are some weird issues with watching Node v7.

**Comment by skovhus** [comment]
> Was this working in the latest 2.1.0 beta?

Yes. It work in webpack@2.1.0-beta.28

**Comment by skovhus** [comment]
> Could you try if this does work in Node v6? There are some weird issues with watching Node v7.

Watch mode for 2.2.0-rc.0 doesn't work in node v6.9.2

**Comment by SpaceK33z** [comment]
Okay, thanks, that helps narrowing down the issue. Possibly #3479 has caused this.

**Comment by skovhus** [comment]
@SpaceK33z I can try reverting https://github.com/webpack/webpack/pull/3479/files locally and see if it solves it.

**Comment by phaistonian** [comment]
Setting `cache` to false did the trick - but that's far from ideal, I think.

**Comment by SpaceK33z** [comment]
@skovhus yes please!

**Comment by skovhus** [comment]
> Okay, thanks, that helps narrowing down the issue. Possibly #3479 has caused this.

I can confirm  #3479 is not the cause.

**Comment by skovhus** [comment]
Might be some of the caching/performance fixes in https://github.com/webpack/webpack/pull/3428

Although those helped with speed, it might have killed watch mode.
https://github.com/webpack/webpack/issues/3480

**Comment by phaistonian** [comment]
It's not just the watch mode.

HMR is not working properly when an error is spawned.

**Comment by sokra** [comment]
I've got a fix. But writting a test case is difficult...

**Comment by phaistonian** [comment]
@sokra ETA for pushing the fix to a new release?

**Comment by sokra** [comment]
today
