### ISSUE TITLE
Unreachable code - error

### ISSUE THREAD

**Issue by vlio20** [webpack/webpack#3501]
I have this code:  
```
  private getTrafficData(trafficPromise: IPromise<ITotalsData>): IPromise<ITotalsData> {
    return this.$q.all([trafficPromise, this.getMainTotalsData()])
      .then((response: [ITotalsData, IMainTotalsData]) => {
        const [trafficData, totalData] = response; // this is line 91
        
        return {
          revenue: trafficData.revenue,
          rpm: trafficData.rpm,
          rate: totalData.advertisingPvs ? (trafficData.pageViews / totalData.advertisingPvs) * 100 : 0
        };
      });
  }
```

It's written in TypeScript as you can see. In my webpack (1.14.0) config I am using the `UglifyJsPlugin` plugin.  

I am getting this warning in my terminal:
```  
Dropping unreachable code [./~/ts-loader!./...summary.srv.ts:91,0]
Declarations in unreachable code! [./~/ts-loader!./.../summary.srv.ts:91,0]
```

The code is very reachable, so what is the issue?

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
