### ISSUE TITLE
Webpack @import sass error

### ISSUE THREAD

**Issue by artnova-david** [webpack/webpack#3502]
Hi,
I'm not sure if this is a bug in webpack or a defined loader (ExtractTextPlugin, ...). I'm also not sure if this is the right place to ask, but the error/behavior is quite strange and after several hours en various config trials i always end up with the same error: 

**ModuleBuildError: Module build failed: 
@import 'path/to/my/_partial.scss';
File to import not found or unreadable ...**

Whenever i do a first run with 'npm run dev ' and the below configurations  everything builds fine and all .**scss** files are compiled nicely into one **.css** file in the correct folder. 
But when i modify or add some scss markup in one of the scss files the above error is thrown. But, and this is the strange part, when i save again without modifications the build passes again and in most cases the console does not show a build log but the css is rebuild correctly.
At first I was looking for wrong path configurations, but the first run builds correctly so the files are found... .  I've been searching quite a while for a solution but didn't find anything,
Below my installed packages, webpack config and folder structure

**My installed packages are:**
`"scripts": {
    "dev": "set NODE_ENV=development && webpack --watch"
  }
"webpack": "^2.1.0-beta.22"
"resolve-url": "^0.2.1",
"resolve-url-loader": "^1.6.1",
"sass-loader": "^4.0.2",
"style-loader": "^0.13.1",
"css-loader": "^0.23.1",
"node-sass": "^4.0.0",
"extract-text-webpack-plugin": "^2.0.0-beta.4",
"file-loader": "^0.9.0",
"glob": "^7.1.1",
"node-sass": "^4.0.0",
"path": "^0.12.7",
"postcss-cssnext": "^2.9.0",
"postcss-import": "^9.0.0",
"postcss-loader": "^1.2.1",
 "autoprefixer-loader": "^3.2.0",`

My webpack.config.js is quite simple and is as follows:
```
    entry: {
        styles: ['app.scss'],
    },

    output: {
        filename: '[name].css',
        path: __dirname + '/app/styles'
    },

    resolve: {
        modules: [
            path.resolve(__dirname, 'dev'),
            'node_modules'
        ],
        extensions: ['', '.css', '.scss', '.sass']
    },

    module: {
        loaders: [

            // SASS
            {
                test: /\.scss$/,
                loader: extractTextPlugin.extract({
                    fallbackLoader: "style-loader",
                    loader: "css-loader?modules&sourceMap&importLoaders=1&localIdentName=[local]!resolve-url!sass-loader?sourceMap"
                })
            }
        ]
    },
    
    plugins: [
        new extractTextPlugin({ filename: '[name].css', allChunks: true })
    ]
}
```

The folder structure contains one app.scss file in the root ./dev from where alle other .scss files are included:
```
@import 'assets/styles/_variables.scss';
@import 'assets/styles/_mixins.scss';

@import 'assets/styles/_base.scss';
@import 'assets/styles/_motion.scss';

@import 'components/form/UiButton/_UiButton.scss';
@import 'components/router/UiSideBar/_SideBar.scss';
@import 'components/router/UiTopMenu/_TopMenu.scss';
@import 'components/router/UiSubMenu/_SubMenu.scss';
@import 'components/router/UiToolBar/_ToolBar.scss';
@import 'components/popup/UiModal/_UiModal.scss';
@import 'components/media/UiSpinner/_UiSpinner.scss';
```

so the first build always succeeds, the next builds throw an error like above mentioned but succeed after double save without modifications.
Has anyone encountered this problem/behavior? Or is this a wrong configuration?

**Comment by xyyjk** [comment]
I have the same situation

**Comment by ev1stensberg** [comment]
@artnova-david Got a repro/repository I could check out?

**Comment by artnova-david** [comment]
@ev1stensberg currently i don't have a repository for this cause i'm playing around with some code.
I'm not convinced this is a webpack bug though. Webpack was always giving me the same error and so I tried to compile my sass with gulp to see what this would result in. After the first 5 saves or so, ...bam same error as I received from webapck. 
So this problem was no so obvious and this got me thinking maybe it is not the transpiler thats causing the error. The next in line that could cause this error was or **npm** itself, **my editor** (vscode) or my **OS** (windows 10). With these options I found this posts: [https://github.com/dlmanning/gulp-sass/issues/235](url). So I tried to compile with **Sublime** and **Atom**. Sublime gave me the same error until I set **atomic_save: true** and then it stopped giving me the error. Atomic editor never gave me the error neither with gulp nor webpack. And when I added a timeout of 1sec to my gulp task I also stopped getting the error when compiling with vscode.

So I guess some editors seem to temporary remove a file when it is saved and webpack --watch and gulp --watch kick in before the editor has put the file back causing a "not found error" for that sepecific file. I must add, the error only happens with .scss files not with .js files.

**note:** Webpack does seem to have an issue when one uses a .scss file as entry and the --watch option. When compiling with gulp --watch i get an output in the console with every save I do, when I compile with wepack I only get the console output once but the .css file does get rebuild with every save.

**Comment by ev1stensberg** [comment]
@artnova-david That's weird. Would need a repro to check what is going on. Try the `--save` option once that PR has been added to check if it's any different. A theory of mine would be that webpack first needs to compile to javascript from sass and the watch mode can't pick up the change. 

Is your issue solved?

**Comment by artnova-david** [comment]
@ev1stensberg well, my issue is kinda solved, because now I use webpack to compile my javascript and component files and use gulp to compile my sass files. I don't find this a huge problem and can live with that. I must state that webpack **does** pick up the changes in my main.scss and the imported child.scss files, because the resulting .css file contains the changes. Its only that webpack does not output the change log for .scss files to the console in contrast to changes in .js files which are always outputted to the console. And this only happens when I use a .scss file as entry in webpack it does output the logs when I include my .sccs files in the app.js file like (import styles from './app.js')
I will attach the project files asap as a .zip

**Comment by ev1stensberg** [comment]
Could be that `scss` are being seen as static files. Should output anyway. You should use webpack for your sass as well. Removes a big dependency hole with both webpack and gulp in one project. Your entry should be plain javascript. If you import the scss through an `index.js` first, and specify it to be the entry point, it should work. Issue is that webpack has to compile down  to js, making it async would delay stats output and make sure the compilation makes it in time. 

As for you editor issues, I cannot really comment on that, try putting up a issue on their discord or their chat group if they have any. 

Hope this helps! Issue should be closed now. Happy holidays!

**Comment by artnova-david** [comment]
@ev1stensberg I tried including my app.scss file into my app.js true `import styles from 'app.scss'` and in my app.scss @importing all partials and this didn't work either (= no console output but webpack does add the changes to my .css file.) . The only way it works is when I import the .scss partial individual in my .jsx or .vue components and thus my .scss files are compiled on .js changes (I gues this would make them async), but I would like one main .scss file with all my imports to keep things organised. Could you specify on how to make on on main.scss file async in webpack?

I included a reduced example of the current structure and commented out irrelevant code.
Please ignore the 'modules' section in the webpack.config.
[MyApp.zip](https://github.com/webpack/webpack/files/673271/MyApp.zip)

Happy holidays!!!

**Comment by ev1stensberg** [comment]
You need to change your webpack command in package.json to use [this](https://webpack.github.io/docs/cli.html#display-modules)

**Comment by artnova-david** [comment]
when I just type --webpack into the console the all modules (paths, ...) are logged only for the first time and only for .js file watches, after that, all changes are logged for .js files but not for .scss files. When i turn on --progress, I do see a blink of the progress appear when a .scss files changes so the watch does occur but nothing is logged/outputted to the console for .scss files.

**Comment by ev1stensberg** [comment]
Can you screenshot your unexpected output?

**Comment by artnova-david** [comment]
Sorry for the late response. Here is a screenshot.
As you can see, de sass is compiled to a .css (styles.css) file and the first time the output is logged in the CLI. When this screenshot was taken I modified 5 .scss files that were imported into app.scss, all modifications are visible in the styles.css file but the watch of webpack does not output changes to the CLI.

![2016-12-29_21-34-57](https://cloud.githubusercontent.com/assets/21141231/21554424/b0c3cd3e-ce0f-11e6-9d3b-f3b86e9e2dcc.jpg)

**Comment by xyyjk** [comment]
@artnova-david 

Because you are using the new version of `extract-text-webpack-plugin` "^2.0.0-beta.4"
Need to be modified into this way: 

before:
```
{
    test : /\.scss$/,
    exclude: /node_modules/,
    loader: extractTextPlugin.extract(['css-loader', 'sass-loader'])
}
```
after: 
```
{
    test : /\.scss$/,
    exclude: /node_modules/,
    loader: extractTextPlugin.extract({
        loader: ['css-loader', 'sass-loader']
    })
}
```

See details : https://github.com/webpack/extract-text-webpack-plugin#usage-example-with-css

**Comment by artnova-david** [comment]
@xyyjk 
I tried this before but same result. First log is outputted to the CLI and thats it.

**Comment by denisinla** [comment]
Are you using a webpack.config.dev.js file at all? I had a similar issue but when using webpack as part of create-react-app. My dev environment would work properly after editing webpack.config.dev.js by adding .scss to the loaders' exclude but when running npm run build would get the same @import error when scss files. Turns out I needed to define it in webpack.config.prod.js as well so the build.js script would find the necessary files.

**Comment by artnova-david** [comment]
@denisinla yes, i'm definitly using webpack.config

**Comment by iSanchezDev** [comment]
Importing scss file on webpack, easiest way. It worked for me!

**Install**
npm install sass-loader node-sass webpack --save-dev

import 'file''

**Webpack file**
... {test: /\.scss$/, loaders: ["style", "css", "sass"]}

**Comment by matteocollina** [comment]
It works for me with 
"webpack": "^4.42.0",
 "webpack-cli": "^3.3.11"
 
`
 {test: /.scss$/, loaders: ["style-loader", "css-loader", "sass-loader"]}
`
