### ISSUE TITLE
Webpack 2.1.0 size limit for source maps

### ISSUE THREAD

**Issue by JasonTheAdams** [webpack/webpack#3503]
I'm getting the same size limit warning as described in #3486 and I see it can be turned off with `{ hint: false }`, which is great. Still, I'm only getting the warning because it's saying the source maps are big. Since sourcemaps are only intended for use on dev, it seems like there should be an exception where they're ignored by this?

**Comment by TheLarkInn** [comment]
For webpack 2.2.0-rc.0, we filter .map files by default. 

However you can look at the following PR to see the options that will be available (like passing a filter function to filter out specific file types). webpack/webpack.js.org#500

**Comment by JasonTheAdams** [comment]
Great! As soon as #3500 is resolved I'll switch over to 2.2! Thanks @TheLarkInn!
