### ISSUE TITLE
Error in list-of-plugins.html docs (NormalModuleReplacementPlugin section)

### ISSUE THREAD

**Issue by mateuszmazurek** [webpack/webpack#3506]
**EDIT:**

I found that my `newResource` function is called twice - on `before-resolve` and `after-resolve` events. At first time this function should modify `request`, but at second one `resource` attribute.

[Docs](http://webpack.github.io/docs/list-of-plugins.html#normalmodulereplacementplugin) says only about `request`:
> If `newResource` is a function, it is expected to overwrite the ‘request’ attribute of the supplied object.

I changed title of this issue from
`NormalModuleReplacementPlugin not working in 2.2.0-rc.0`
to
`Error in list-of-plugins.html docs (NormalModuleReplacementPlugin section)`

--------------

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Webpack still use original module instead of replacement one.

**If the current behavior is a bug, please provide the steps to reproduce.**
Add any valid instance of `webpack.NormalModuleReplacementPlugin` to `plugins` inside your webpack config file and check if your replacement module is used.

Example: instead of `any-module` package from `node_modules` we want to use replacement from our `app` directory. Let's write our config file:

```js
// ...
plugins: [
  new webpack.NormalModuleReplacementPlugin(
    new RegExp(`^${PATHS.vendor}/any-module/lib/index.js`), // PATHS.vendor is absolute path to package node_modules directory
    function(result) {
      const appModulePath = path.join(PATHS.app, './any-module/lib/index.js');
      if(fs.existsSync(appModulePath)) {
        result.request = appModulePath;
      }
    }
  )
]
// ...
```

And then use it somewhere in our code:

```js
const anyModule = require('any-module');
```

**What is the expected behavior?**
Webpack should resolve module from `newResource` specified to `NormalModuleReplacementPlugin` constructor.

**Comment by mateuszmazurek** [comment]
I have additional question about `NormalModuleReplacementPlugin`. When I change `request` and `resource` attributes of `result` object should loaders from webpack config `module`.`rules` array be aplied to replacement module?

```js
{
  test: /\.jsx$/,
  loaders: ['babel-loader?cacheDirectory', 'preprocess-loader'],
  include: PATHS.app
}
```

Now I have this error (source is not passed through Babel and Webpack can't understand JSX syntax):

![image](https://cloud.githubusercontent.com/assets/5048182/21281596/70c33e3e-c3ee-11e6-8fdb-2609451fd93c.png)

Is it expected behaviour?

**Comment by TheLarkInn** [comment]
To ensure we can fix this, could I twist your 💪 into creating a minimal reproducible example repo that we can test against? It will considerably expedite the troubleshooting process 🙏 🙏 .

**Comment by mateuszmazurek** [comment]
@TheLarkInn

```
git clone https://github.com/mateuszmazurek/NormalModuleReplacementPlugin-test.git
cd NormalModuleReplacementPlugin-test
npm install
npm test
```

How about my question in comment? When i use `NormalModuleReplacementPlugin` correctly should loaders be applied to replacement module? I don't know if I should open dedicated issue.
