### ISSUE TITLE
Chunkhash changes in every build even there is no change at all.

### ISSUE THREAD

**Issue by JounQin** [webpack/webpack#3508]
**Do you want to request a *feature* or report a *bug*?**

 *bug*

**What is the current behavior?**

As the title

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/Raiyee/EasyHi/commit/9a5287bdda3535ae1688d1b0beb6c7a77e9aef04
https://github.com/Raiyee/EasyHi/commit/992b8778ee59d938acd1bda77edd32d3b3937734

**What is the expected behavior?**

The two commits are both built with Travis CI, https://travis-ci.org/Raiyee/EasyHi/builds/184699463

I just `restart build`, and then the file names change!

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**

More detail you can see in Travis CI.

**Comment by JounQin** [comment]
I can reproduce it on my own computer.

**Comment by JounQin** [comment]
Finally I find out it is an issue of [vue-template-es2015-loader](https://www.npmjs.com/package/vue-template-es2015-loader), which generate id incrementally rather than using hash of file (fixed now).

**Comment by JounQin** [comment]
Rethink about, look through the original code:

``` js
let uid = 0
const uidRegistry = Object.create(null)

module.exports = function genId(filePath) {
  return uidRegistry[filePath] || (uidRegistry[filePath] = ++uid)
}
```

`uid` will increment when a new filePath passed, what means the order of path passed by webpack is non-deterministic?

The name-changed files are all loaded dynamically, is that seems to be a bug of code splitting?

**Comment by TheLarkInn** [comment]
Would you be able to provide a full configuration? And let us know what version of webpack you are running this against?

**Comment by JounQin** [comment]
Configuration: https://github.com/Raiyee/EasyHi/blob/master/build/webpack/index.js

code splitting files: https://github.com/Raiyee/EasyHi/blob/master/src/router/routes.js

I'm using the latest version (2.2.0-rc.0).

**Comment by sokra** [comment]
Yes the order in which loader are processed is non-determistic. Loaders should not keep a global state.
The loader behaves incorrect.

If it needs a unique id there is `module.id` available at runtime.

**Comment by JounQin** [comment]
Thanks for your reply! @sokra

**Comment by JounQin** [comment]
Actually I want a unique id of file rather than the loader module, I just find out `module.id` is the file path of loader module rather then the file's, so it works incorrectly neither when using `module.id`.

So I should use `this.resourcePath` or its hash instead.

It's so sad that I find it so late…… :(
