### ISSUE TITLE
[load image] can webpack auto resolve @2x or @3x like react-native?

### ISSUE THREAD

**Issue by playing** [webpack/webpack#3516]
I have an image folder, like this.
```
.
├── error-icon@2x.png
├── error-icon@3x.png
├── home-bg@2x.png
├── home-bg@3x.png
├── logo-text@2x.png
├── logo-text@3x.png
└── user@2x.png
```
in react-native, I can import image like
```javascript
import HomeBg from 'img/home-bg.png';
```
but now I use webpack to build web version, and use `url-loader` in image load. I must write import like
```javascript
import HomeBg from 'img/home-bg@2x.png';
```
I try some methods, but can`t work...

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
