### ISSUE TITLE
Watch Mode stops functioning if emitted file is busy or locked

### ISSUE THREAD

**Issue by donnieddd** [webpack/webpack#3523]
**Do you want to request a *feature* or report a *bug*?**
A bug

**What is the current behavior?**
When in watch mode, if a file is busy when attempting to emit to it, watch stops functioning. The following error is appropriately logged: 
```
Error: EBUSY: resource busy or locked, open '..\js\bundle.js'
    at Error (native)
```
**If the current behavior is a bug, please provide the steps to reproduce.**
run webpack --watch
save a watched file
output to a file which is currently being used by another process

**What is the expected behavior?**
An error is logged to the console but watch mode continues to function. This is the behavior of Grunt and Gulp watchers.

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**
A valid reason why a file could be momentarily busy is if it is being synced to a server directory.

**Comment by TheLarkInn** [comment]
Congratulations on your first ever github issue on this repo and ever!!! (On this account)!!! And welcome to the community!!!! ❤️ ❤️ ❤️ ❤️ 🙇 🤗 

> A valid reason why a file could be momentarily busy is if it is being synced to a server directory.

I think you misunderstood this as valid explanation to you. Rather, this statement is our way of probing you for important details for us to accurately triage your problem. These details include: 
* webpack version
* node version.

**Comment by donnieddd** [comment]
Ahaha thanks @TheLarkInn! It's good to be here. :octocat:

Here are the details of my setup:
* webpack version: 2.1.0-beta.25
* node version: 6.9.1
* os: windows 10
* browser: chrome 55

**Comment by bebraw** [comment]
Moved to https://github.com/webpack/webpack-cli/issues/14 .
