### ISSUE TITLE
CLI tool for migrating webpack 1 config file to webpack 2

### ISSUE THREAD

**Issue by egoist** [webpack/webpack#3526]
**Do you want to request a *feature* or report a *bug*?**
technically not feature for webpack but an independent cli tool

**What is the current behavior?**
we need to update each webpack.config.js manually

**What is the expected behavior?**
something like `eslint --fix` but `webpack-migrate webpack.config.js` would make it webpack 2 compatible.

**If this is a feature request, what is motivation or use case for changing the behavior?**
it hurts if we have to migrate many webpack 1 projects

**Comment by bebraw** [comment]
Could you re-open this at [webpack-cli](https://github.com/webpack/webpack-cli/issues) repo? Thanks.

**Comment by DanielaValero** [comment]
Issue is now open in the webpack-cli repo: webpack/webpack-cli#6
