### ISSUE TITLE
webpack2 css hash problem

### ISSUE THREAD

**Issue by lqzerogg** [webpack/webpack#3527]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
No matter how I change my css source file, my built css files' hash code don't change at all. However, my js files' are all right.

**If the current behavior is a bug, please provide the steps to reproduce.**
``` js
//I take css file as an entry
entry[css/${page}] = path.join(PATH.src, view/pages/${page}/index.scss)
//output config
filename: BUILD || ADJUST ? '[name].[chunkhash].js' : '[name].bundle.js',
chunkFilename: BUILD || ADJUST ? 'js/[name].[chunkhash].js' : 'js/[name].bundle.js'
//extract text plugin config
new ExtractTextPlugin({
    filename: notHash ? '[name].bundle.css' : '[name].[chunkhash].css',
    allChunks: true
})
```

**What is the expected behavior?**
css files' hash should be changed

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**
webpack: 2.1.0-beta
node: 7.0.0
npm: 3.10.8
extract-text-webpack-plugin: 2.0.0-beta.4

**Comment by bebraw** [comment]
Can you set up a standalone example? Thanks.

**Comment by lqzerogg** [comment]
how to provide you a standalone example? Does it means create a project to let you run? Or just provide you some information?

**Comment by lqzerogg** [comment]
If for information. then for example, the first time I built my app, here the files:
                              js/app.7e58bfe34b9e1210f56c.js     147 kB   7, 12  [emitted]  
                             css/app.360d32f29a4b5abd7322.js  103 bytes  10, 12  [emitted]  
                            css/app.360d32f29a4b5abd7322.css     169 kB  10, 12  [emitted]                         

Then I changed my app/index.js file, and built my app:
                              js/app.fef9476ea1583151a279.js     147 kB   7, 12  [emitted]  js/app
                             css/app.360d32f29a4b5abd7322.js  103 bytes  10, 12  [emitted]  css/app
                           css/app.360d32f29a4b5abd7322.css     169 kB  10, 12  [emitted]  css/app
                        
Then I canceled my modifications in js file, changed my app/index.scss file and built my app : 
                              js/app.7e58bfe34b9e1210f56c.js     147 kB   7, 12  [emitted]  js/app
                             css/app.360d32f29a4b5abd7322.js  103 bytes  10, 12  [emitted]  css/app
                             css/app.360d32f29a4b5abd7322.css     169 kB  10, 12  [emitted]  css/app
                         
You can see that when changing js file, js file's hash is changed. But no matter how I modify my css file, css file's hash cannot be changed.

**Comment by bebraw** [comment]
> how to provide you a standalone example? Does it means create a project to let you run? Or just provide you some information?

A project to run, yeah.

**Comment by lqzerogg** [comment]
here is my project. After install, run 'npm run online' will compile the files.

https://github.com/lqzerogg/webpack2hashtest

**Comment by sokra** [comment]
use `[contenthash]` instead of `[chunkhash]` in the ExtractTextPlugin.
