### ISSUE TITLE
Webpack2 build more than twice when entry file changed once

### ISSUE THREAD

**Issue by guox191** [webpack/webpack#3528]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
![image](https://cloud.githubusercontent.com/assets/9742995/21344702/0be139d4-c6d8-11e6-8dc2-a82d4941f378.png)
Run webpack dev-server after change one entry file, it will build many times with the same hash.
And followed by this message: 
```
webpack: bundle is now VALID.
webpack: bundle is now INVALID.
```

Then I switch to webpack1, it works and only build twice.(Only one `bundle is now INVALID.`)

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**
1. Change one entry file
2. Run webpack2 dev-server instantly

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**
webpack: 2.1.0-beta.28
node: 6.9.1
npm: 3.10.8

**Comment by bebraw** [comment]
Can you set up a standalone example so it's easier to debug?

**Comment by TheLarkInn** [comment]
Also do you exhibit this behavior in webpack 2.2.0-RC.1

**Comment by duivvv** [comment]
having the same problem here https://github.com/devinehowest/generator-devine-boilerplate
... with 2.2.0-RC.1

**Comment by guox191** [comment]
@bebraw 
Here is an example: https://github.com/guox191/react-webpack2-demo
run `make dev` to reproduce it

**Comment by Kovensky** [comment]
This is https://github.com/webpack/watchpack/issues/25 again

**Comment by bebraw** [comment]
@Kovensky Thanks. Closing.
