### ISSUE TITLE
ProvidePlugin: Array of modules

### ISSUE THREAD

**Issue by shellscape** [webpack/webpack#3529]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**

```js
    new webpack.ProvidePlugin({
      'varName': 'module.name'
    }),
```

**What is the desired behavior?**

```js
    new webpack.ProvidePlugin({
      'varName': [ 'module.one', 'module.two' ]
    }),
```

**If this is a feature request, what is motivation or use case for changing the behavior?**

We have several wrapper libraries that are contained within individual modules. When using our old concat-bundler, this wasn't an issue and made for easy maintainability of the related and non-related wrapper modules. However, since they are not directly or explicitly `require`d in target code for bundling, we need an alternative means to include them in the bundle. We can target specific variables uses, but a single call to a particular object or variable name required several modules to be used. The ProvidePlugin doesn't seem to allow multiple definitions with the same key.

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**

webpack 2.2.0-rc.1
Node 7.1

**Comment by sokra** [comment]
This is not support (and not needed). You can point the ProvidePlugin to a small module like this:

``` js
// varNameModule.js
export * from "module.one";
export * from "module.two";
```

``` js
    new webpack.ProvidePlugin({
      'varName': path.resolve(__dirname, "varNameModule.js")
    })
```

**Comment by shellscape** [comment]
@sokra that's a rather premature closing. I've been talking with @TheLarkInn on a use case which outlines the need for this. We're attempting to move from a concat-bundle system to webpack, and including a small module in the bundle with those imports isn't an option for us.

**Comment by TheLarkInn** [comment]
If you could describe the scenario a bit more, and even a reproducible example.

**Comment by shellscape** [comment]
Surely. We're using webpack to produce a flat, non-wrapped bundle in preparation for a shift in development ideology. Preparing our tooling is the first step, so we're moving from a gulp-concat system to webpack to get familiar with the tool. From what I've seen, there's no reason webpack can't be adapted for this purpose.

I've put together a gist with a few small files and the accompanying plugins we're using which should convey how we're using webpack to supplant gulp-concat. It also show how and why we'd need a means to specify multiple additional dependencies for a particular bundle. We can target the `gilt` global variable as it's specific to our ecosystem. We'd tried exploring `addDependency` but the docs are cryptic and it appears as if that's not available on `this` within loaders in 2.2.0 betas.

https://gist.github.com/shellscape/a6d9a3c0b105844963cdb00b60850ba5

**Comment by shellscape** [comment]
per @TheLarkInn 's request, I recreated the ProvidePlugin and added only a few lines to achieve the desired functionality. I couldn't find any side effects, but I'm sure this would have to be run through webpack's test suite to be sure. Given the minor nature of the changes, I'm sure it'd be a benefit https://gist.github.com/shellscape/a7461022503f019598be93a512a1901a

**Comment by jonnybot0** [comment]
@shellscape - that would be a useful feature. Why not submit your gist as a PR?

**Comment by shellscape** [comment]
@jonnybot0 that was waaaaaaaaay back in the day before I was invited onto the team. I actually had to re-read the thread because it'd been so long (Dec 2016!) since I posted it I couldn't remember what it was for 😆  Still think it's useful, but there's been zero demand (from what I can tell) for it since I posted this all those moons ago, and the gist works (worked?) well as a local workaround.

**Comment by jonnybot0** [comment]
:crying_cat_face: Fair enough.
