### ISSUE TITLE
Value provided via "webpack.DefinePlugin" not updated upon "--watch" rebuilds

### ISSUE THREAD

**Issue by ArturBaybulatov** [webpack/webpack#3530]
I've got a following setup:

```javascript
// webpack.config.js

var webpack = require('webpack')

module.exports = {
    entry: './source.js',
    output: {path: '.', filename: 'bundle.js'},
    plugins: [new webpack.DefinePlugin({VERSION: JSON.stringify(timestamp())})],
}

function timestamp() {
    return (new Date()).toISOString()
}
```

```javascript
// source.js

console.log(VERSION)
```

When i build and rebuild manually `VERSION` value updated fine, but if i startup the Webpack with `--watch` option, the value stays the same between rebuilds. I expect it to be updated on every rebuild

I've got Webpack version 1.14.0, Node version 7.0.0, Windows 10 Pro

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by ArturBaybulatov** [comment]
@sokra I've updated the issue, could it be reopened, please?

**Comment by Cuel** [comment]
I'm also interested in this. Had this weird idea that this would work:

```javascript
        plugins: [
            function() {
                this.plugin('compilation', function (data) {
                    const value = Math.random();
                    data.options.plugins.push(new webpack.DefinePlugin({
                        __TEST__: JSON.stringify(value)
                    }));
                })
            },

```

But __TEST__ is always undefined

**Comment by Cuel** [comment]
config
```
plugins: [new MyPlugin()]
```
class MyPlugin {
    apply(compiler) {
        compiler.apply(new webpack.DefinePlugin({
            // values
        }));
    }
}
```

**Comment by ArturBaybulatov** [comment]
@Cuel Sorry, `compiler.apply(...)` still gets called only on first compilation. You can test it with:

```javascript
var webpack = require('webpack')

class MyPlugin {
    apply(compiler) {
        console.log('Hello there')
        
        compiler.apply(function() {
            console.log('Bla bla bla')
        })
    }
}

module.exports = {
    entry: './source.js',
    output: {path: '.', filename: 'bundle.js'},
    plugins: [new MyPlugin()],
}
```

Start webpack in watch mode

**Comment by Cuel** [comment]
Yeah noticed that, forgot to update the comment

**Comment by joncraig** [comment]
Trying to work this out myself... Looks like compiler runs only on the initial launch... If you then listen for "compilation", it runs on each update. That is as far as I got...
See: [https://webpack.js.org/api/plugins/](https://webpack.js.org/api/plugins/)
``` js
class MyPlugin {
  apply(compiler) {
    console.log('\n--- Compiler ---');
    compiler.plugin("compilation", function(compilation) {
      console.log('\n--- Compilation ---');
    });
  }
}

```
