### ISSUE TITLE
__webpack_require__.i(...) is not a function

### ISSUE THREAD

**Issue by jknight12882** [webpack/webpack#3532]
**Do you want to request a *feature* or report a *bug*?** 
Bug

**What is the current behavior?**
The following exception is thrown when launching the script client side

```
Uncaught TypeError: __webpack_require__.i(...) is not a function
    at Object../src/client/entries/start.js (:8000/js/webpack:/src/client/entries/start.js:17)
    at __webpack_require__ (:8000/js/webpack:/webpack/bootstrap b13dc1db3d58c4638f23?ce79:19)
    at initialize (:8000/js/webpack:/src/client/bootstrap_start.js:3)
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Build the client script using any of the latest RC releases (currently using `2.2.0-rc.1`

**What is the expected behavior?**
No exception should be thrown

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**
Node.js@v6.9.1
OSX 10.11.6

**Comment by stevewillard** [comment]
Can you provide some more context, and possible a repo to reproduce the issue?

Showing your `start.js` code, `package.json` and `webpack.config.js` would help.

**Comment by jknight12882** [comment]
@stevewillard gist sent to your email

**Comment by stevewillard** [comment]
Check your line 17
```
const store = createStore(rootReducer, ({ locale }) => ({
```

What does this module export?
`import createStore from 'client/utils/create-store';`

It looks like this create-store doesn't have a `default` export of a function.

**Comment by jknight12882** [comment]
You're right, it doesn't (intentionally). What changed between the beta releases and the RC releases which causes this to no longer work?

**Comment by stevewillard** [comment]
I'm not sure. I'm not a contributor 😄

**Comment by Kovensky** [comment]
The only thing I can think of is if you had mixed ES6 import/export with `module.exports` in `client/utils/create-store`. Don't do that, either make a file pure commonjs (`require` / `module.exports`) or pure ES6 (`import`/`export`).

**Comment by jknight12882** [comment]
Got it, closing

**Comment by aryzing** [comment]
@Kovensky I have the same issue with pure ES6 import/export. I'm not sure what's going on...

Repo: https://github.com/aryzing/anccre
```
git clone git@github.com:aryzing/anccre.git
cd ./anccre
yarn
yarn build # <-- watch turned on, so will block terminal
yarn start
```

Open localhost:6121
