### ISSUE TITLE
If entry[bundle] = [] then config validation is inaccurate - v2.2 beta

### ISSUE THREAD

**Issue by aight8** [webpack/webpack#3534]
**Do you want to request a *feature* or report a *bug*?**
In my eyes a bug. But it's both.

**What is the current behavior?**

When the webpack config contains an entry with a empty array the config validation message is to inaccurate. (MPA setup, SPA not tested currently)

Exception:
```
/path/to/app/node_modules/webpack/lib/webpack.js:17
		throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
		^
Error
    at webpack (/path/to/app/node_modules/webpack/lib/webpack.js:17:9)
    at Object.<anonymous> (/path/to/app/run-webpack.js:25:16)
    at Module._compile (module.js:571:32)
    at loader (/path/to/app/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/path/to/app/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Function.Module.runMain (module.js:605:10)
    at /path/to/app/node_modules/babel-cli/lib/_babel-node.js:159:24
````

The exception message is just: Error - there is no conclusion that a bundle have no entries.

**If the current behavior is a bug, please provide the steps to reproduce.**

Example:
```
....
{
   entry: {
      vendor: []
   }
}
....
```

**What is the expected behavior?**

There are various solutions:
a) Message like: The entry "vendor" must have at least one file(s) defined.
b) Skip bundle with no entry files
c) Output a bundle with no modules (?)

Because of strictness of the webpack config I think solution a) is preferred by the community.

**If this is a feature request, what is motivation or use case for changing the behavior?**

Just "Error" is not an error message only on windows.
In lot of setups today webpack configs are generated, so it can happen that an entries are empty (even when a good setup clear empty values by a function).
The goal is that users of webpack can identify also uncommon issues more quickly (I spend a half hour on that on a large setup - could be avoided easily).

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**
webpack version 2.2 beta (older versions are not tested)
nodejs version 7

**Comment by SpaceK33z** [comment]
@aight8, would you like to do a PR? It should be possible to add this to [the schema](https://github.com/webpack/webpack/blob/master/schemas/webpackOptionsSchema.json). We're using [ajv](https://github.com/epoberezkin/ajv), which has the possibility to require an array to have at minimum one entry.

**Comment by halfzebra** [comment]
@SpaceK33z Gave a shot at fixing this, should I add tests?

**Comment by TheLarkInn** [comment]
Thanks for this!!!!! Closing with #3567
