### ISSUE TITLE
92%

### ISSUE THREAD

**Issue by istiti** [webpack/webpack#3537]
I'm using angular-cli v22-1.

I know I don't make me friends by saying that, because maybe already discussed but I can't find something avout.
So I write on angular-cli issue that: 

_I will have Angular big project with angular-cli. actually I have lazyloading for 20 or 30 modules... when I do ng serve or ng build with --aot option ... the cli take a long until finish, it wait at 92%
I think chunks generating (it takes 5mn) ...
My project will be more bigger 100-200lazyloading modules and I'm scared if this will take 2 hours to generate project...._

_When cli finish generating with AOT, my project works without error... and I wonder if this is normal or how can I know if something in my code is blocking this step ?_

**Comment by cesarandreu** [comment]
Please post a question to [StackOverflow with the webpack tag](https://stackoverflow.com/tags/webpack).

Maybe you could try using [parallel-webpack](https://github.com/trivago/parallel-webpack).

**Comment by SpaceK33z** [comment]
^
