### ISSUE TITLE
feature: DLLPlugin support upgrade without rebuild bundle using this dll

### ISSUE THREAD

**Issue by sskyy** [webpack/webpack#3538]
# Scenario

I have a dll bundle called `vendor` contains common libraries `a`,`b` and `c`, and several app bundles using this vendor. Now library `a` released a new version

# Question

How can I only rebuild the dll bundle so I can use the new version of `a`, and not rebuild all app bundles using this bundle? I checked the `manifest.json` generated for dll bundle,  the main problem is that module id of `b` and `c` may change if module `a` increased or reduced its dependencies in new version, cause module id of `b` and `c` is generated after all dependencies of `a` have been resolved. Is it possible to generate all module id before resolve its dependencies? The problem can be solved by that way.

Thx.

**Comment by superRaytin** [comment]
Same problem here.

**Comment by ywmail** [comment]
can anyone reopen this issue?
I'm facing the same problem.

**Comment by ywmail** [comment]
I think `HashedModuleIdsPlugin` solved my problem.
