### ISSUE TITLE
Feature - Validate schema paths

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack#3539]
**Do you want to request a *feature* or report a *bug*?**

Feature.

**What is the current behavior?**

It's possible to pass paths that aren't valid to webpack.

**What is the expected behavior?**

webpack should validate any paths passed to it and fail **loudly**. This includes `include` and `exclude` fields at least.

**If this is a feature request, what is motivation or use case for changing the behavior?**

The current behavior hides user errors. Implementing this would reduce the amount of support need as then people could debug path related problems on their own.

**Comment by sokra** [comment]
This could be done by a custom schema validator.

What happens if user uses a custom filesystem? (you could override the `inputFilesystem`)

**Comment by bebraw** [comment]
> What happens if user uses a custom filesystem? (you could override the inputFilesystem)

That's a good question. Most of the value would be gained against a real file system. I don't know how it would work elsewhere. Perhaps this would mean some kind of adapter would be needed for `fs.existsSync` or so. You would plug in a suitable check based on the system.

**Comment by neeharv** [comment]
@sokra @TheLarkInn I'd like to take a crack at this. Any pointers on where to get started? Thanks!
