### ISSUE TITLE
Add module dependency "path" to module processing errors

### ISSUE THREAD

**Issue by fresheneesz** [webpack/webpack#354]
So the verbose output when webpack can't process a module is super nice. But what would be great is if it added the dependency path of how that module got there in the first place. I'm sharing lots of code between my front and backends, and sometimes i accidentally add in a module I shouldn't to the frontend dependency tree. It can be pretty hard for me to figure out how it got in there.

It would be nice if, say, you had Module A requiring Module B, which requires Module C, that if Module C has some stuff that can't be bundled, webpack would output something like:

moduleA:23:10 "require('moduleB')"
moduleB:2:0 "require('moduleC')"
<the usual verbose output...>

**Comment by fresheneesz** [comment]
@TheLarkInn Could you comment on why  you closed this?

**Comment by TheLarkInn** [comment]
Ah yes!!! We are starting to clean out our queues. In this case, 6mo old from last update.

**Comment by TheLarkInn** [comment]
Sorry for not clarifying, actually if you love this feature, lets get a new issue with all the information from our issue template so we can discuss implementation of a formal RFC!
