### ISSUE TITLE
Show a maximum of 10 modules in the stats output by default

### ISSUE THREAD

**Issue by sokra** [webpack/webpack#3540]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
many modules are shown, node_modules are excluded by default
big code bases result in many output lines
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
only the first 10 modules (meassured by distance to entry point) should be shown by default

**If this is a feature request, what is motivation or use case for changing the behavior?**
less output

**Comment by andynoelker** [comment]
Could this be a configurable option in our webpack config?

**Comment by sokra** [comment]
Sure, everything is configurable...
