### ISSUE TITLE
Webpack doesn't emit sourcemap on the output.fileName when using typescript

### ISSUE THREAD

**Issue by DOMZE** [webpack/webpack#3548]
**Do you want to request a *feature* or report a *bug*?**
seems to be a bug

**What is the current behavior?**
source files for the modules

**If the current behavior is a bug, please provide the steps to reproduce.**
StackOverflow link: http://stackoverflow.com/questions/41269411/webpack-doesnt-emit-sourcemap-using-typescript

**What is the expected behavior?**
The ts files in the root directory of the entry file transpile to JS and MAP files, however, the bundling of all of those js files into the output.fileName doesn't create the sourcemap (MAP) files

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**
Windows 7
node.js: 4.6.0
Typescript: 2.0.10
webpack: 2.1.0-beta.28

**Comment by sokra** [comment]
Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md).

**Comment by DOMZE** [comment]
Hello,

The bug was caused by using webpack -d
running the bug without the -d parameter fixed the problem
