### ISSUE TITLE
Error: Cannot resolve module \'source-map-loader\' in cwd()

### ISSUE THREAD

**Issue by unional** [webpack/webpack#3549]
Bug report for webpack 1.14.0

**What is the current behavior?**
I'm working on https://github.com/unional/globalify/tree/externals when I encounter this issue.

`globalify` is a cli tool to download npm package and create a global namespace version of it.
I'm able to get it to work with `webpack`, but when I add `source-map-loader` (and probably any loader or plugin), it fails with the following `stats.toJson()`:

```sh
{ errors: [ 'Entry module not found: Error: Cannot resolve module \'source-map-loader\' in /Users/hwong/github/x\nresolve module source-map-loader in /Users/hwong/github/x' ],
  warnings: [],
  version: '1.14.0',
  hash: '56922e837573a73d11a6',
  time: 40,
  publicPath: '',
  assetsByChunkName: {},
  assets: [],
  chunks: [],
  modules: [],
  filteredModules: 0,
  children: [] }
```

From the message, it seems like `webpack` is trying to get the loader in the wrong folder.
`__dirname`: `/Users/hwong/github/unional/globalify`, where the `globalify` code is and has `source-map-loader` installed.
`process.cwd()`: `/Users/hwong/github/x`, my current directory to test the code.

My guess is `webpack` should be getting the loaders (and plugins) from `process.cwd()` instead of `__dirname`.

Feel free to check out the code and try it out.

If you comment out the following it will work:
https://github.com/unional/globalify/blob/externals/globalify.js#L50-L55

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**
node: 7.3.0

**Comment by sokra** [comment]
In webpack 1: Loaders in configuration are resolved relative to the require call they are matched to.
In webpack 2: Loaders in configuration are resolved relative to the `context` option in the configuration, which defaults to the current directory.

So using webpack 2 probably solves your problem.

**Comment by unional** [comment]
Tested with webpack 2 using `context` solves the problem. Thanks. 🌷
