### ISSUE TITLE
Dependences problem with lazy loading js module (file)

### ISSUE THREAD

**Issue by m1neral** [webpack/webpack#3553]
How to solve the definition of dependences with lazy loading js module (file)?

I have TypeScript with External modules (ES6 modules), that is resolved and compiled by the webpack and ts-loader in es5 bundle.

And also I have separate modules (usually it's file with class), which may extend, patch and add functionality to main bundle, so these separate modules import dependencies from main bundle. 

BUT, **these separate modules can be created anytime and get to the server anytime (compiled .js --> upload --> server)** so main bundle doesn't know anything about them.

**How to implement this?** Maybe some constant instead of `moduleId`?
Require.ensure unsuitable, forwarding all the dependencies from **window** very uncomfortable, including for developing.

P.S.: Previously, the problem was solved very simply by Internal modules (global namespaces) and concatenating files in bundle. Any module(object) was available from the **window**, so by native lazy loading (ajax script) could extend, patch and add functionality to bundle.

**Comment by sokra** [comment]
This is outside the scope of webpack. Expose a defined interface (which allows access to the inner components) from the main bundle, which is used by the separate modules (plugins?`).

Or you can hack it with the DllPlugin, but I won't recommend this!
