### ISSUE TITLE
[HMR] webpack/dev/signal does not work

### ISSUE THREAD

**Issue by laszbalo** [webpack/webpack#3558]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
when using '/webpack/hot/signal' in my entry point array, HMR is not working; once I swap it with 'webpack/hot/poll?1000', it works

**If the current behavior is a bug, please provide the steps to reproduce.**
```javascript
{
    entry: [
        'webpack/hot/signal',  // does not work
        //'webpack/hot/poll?1000',
        path.resolve(__dirname, 'src', 'server', 'server.js')
    ],
    target: 'node',
    devtool: 'source-map',
    output: {
        path: path.resolve(__dirname, 'dist', 'server'),
        publicPath: 'http://localhost:8080/server/',
        filename: 'index.js'
    },
    plugins: [
        new webpack.BannerPlugin({
            banner: 'require("source-map-support").install();',
            raw: true,
            entryOnly: false
        }),
        new webpack.NamedModulesPlugin(),
        new webpack.HotModuleReplacementPlugin()
    ],
    module: {
        rules: [{
            test: /\.js$/,
            exclude: /node_modules/,
            use: [{
                loader: 'babel-loader',
                options: {
                    presets: [
                        ['env', {
                            node: 'current',
                            exclude: ['transform-regenerator']
                        }]
                    ]
                }
            }]
        }]
    }
}
```
**What is the expected behavior?**
The same behaviour what I get when using 'webpack/hot/poll?1000'.

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**
Xubuntu Linux 64bit
Node v7.3.10
webpack@2.2.0-rc.2

Is it something to do with transpilation?
With thanks,
Laszlo

**Comment by sokra** [comment]
How do you send the signal?

**Comment by laszbalo** [comment]
I thought that webpack watches my files for changes and, when it happens, takes care of sending the right signal to my bundle. Is that not right?

**Comment by sokra** [comment]
`webpack/hot/signal` is only the handler for the signal. You need to take care of sending the signal too.

You could send it manually via key combination in the terminal.

You could use a webpack plugin that starts the bundle and sends the signal on update.

You could write a CLI tool that is similar to the webpack-dev-server but for server-side. i. e. webpack-dev-runner.

**Comment by laszbalo** [comment]
I see. Thanks for your explanation. Tried what you suggested, and it is indeed working fine. Because this is not a bug, then I will just close the issue. Although, It might worth to put what you just wrote into the documentation, if it has been already documented somewhere.

**Comment by tvrcgo** [comment]
@laszbalo  How to send signal in webpack plugin ?

**Comment by laszbalo** [comment]
@tvrcgo You mean how do you send a signal the the webpack dev server? Just find out its process id and use the kill command.

**Comment by tvrcgo** [comment]
@laszbalo I use my own server instead of webpack dev server and just want to implement HMR on client.
