### ISSUE TITLE
Invalid configuration with libraryTarget as umd-module

### ISSUE THREAD

**Issue by egoroof** [webpack/webpack#3559]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

When I set config `output.libraryTarget` to `umd-module` as mentioned here https://webpack.js.org/configuration/ then I get an error during build process:
```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.output.libraryTarget should be one of these:
   "var" | "assign" | "this" | "window" | "global" | "commonjs" | "commonjs2" | "commonjs-module" | "amd" | "umd" | "umd2" | "jsonp"
```

Then I thought that `umd2` is `umd-module` but it's result the same as `umd`.

**What is the expected behavior?**

I want to wrap my ES2015 module into UMD but without access via `.default`.

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**

```
Nodejs 7.3.0
OS windows 10
webpack 2.2.0-rc.2
```

**Comment by sokra** [comment]
If your entry point is a ES2015 module it's exported as ES2015 module.

If you don't want this wrap your entrypoint in a commonjs module. It's than exported as commonjs module.

``` js
module.exports = require("./es2015-module").default;
```

**Comment by sokra** [comment]
`umd-module` doesn't exist. `commonjs-module` is equal to `commonjs2`. It's has no longer a special behavior. It's automatic.
