### ISSUE TITLE
Loader Options Plugin overwrite all options

### ISSUE THREAD

**Issue by botika** [webpack/webpack#3564]
**Do you want to request a *feature* or report a *bug*?**
Report a bug.

**What is the current behavior?**
Webpack@2.2.0-rc.2

**If the current behavior is a bug, please provide the steps to reproduce.**
*custom-loader*
```javascript
function processQuery(content, options) {
    console.log(options);
    return content
}

module.exports = function (content) {
  let options = utils.parseQuery(this.options);

  content = processQuery(content, options);
 
  return content;
};
```
*Module config*
```javascript
module: {
      rules: [{
        test: /\.ts$/,
        use:  {
            loader: 'custom-loader',
            options: {
                anyOption: anyValue
            }
    }
}
```
*Loader Options Plugin config*
```javascript
options: { debug: false }
```
**What is the expected behavior?**
The expected console output is:
```bash
{
debug: false,
anyOption: anyValue
}
```
But console output is:
```bash
{
debug: false
}
```
**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**
`node --version`: `v7.2.1`
`Windows 10`
`Typescript 2.0.10`

**Comment by sokra** [comment]
It should be `utils.parseQuery(this.query);` instead of `utils.parseQuery(this.options);`
