### ISSUE TITLE
Cheap source maps for ES2015 modules have incorrect line mappings

### ISSUE THREAD

**Issue by nwoltman** [webpack/webpack#3579]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
**If the current behavior is a bug, please provide the steps to reproduce.**

When any of the cheap source map [devtools](https://webpack.js.org/configuration/devtool/) are used, files that are considered ES2015 modules have incorrect lines mappings. For `cheap-module-*` source maps, the mappings are off by 2 for every `import` statement used.

One import:

```js
import a from 'a';

throw new Error();
// 1
// 2 (source map says `throw new Error();` is on this line
```

Two imports:

```js
import a from 'a';
import b from 'b';

throw new Error();
// 1
// 2
// 3
// 4 (source map says `throw new Error();` is on this line
```

If you change all of the `import` statements to `require` statements, the line mappings are correct (probably since in that case, Webpack will treat the file as a regular CommonJS module).

I am using Babel, but I'm not using it to transform ES2015 modules:

```js
module.exports = {
  // ...
  module: {
    rules: [
      {
        test: /\.js$/,
        loader: 'babel-loader',
        exclude: /node_modules/,
        options: {
          presets: [
            ['latest', {
              es2015: {
                modules: false
              }
            }],
            'stage-2',
            'react'
          ]
        }
      }
    ]
  },
  // ...
};
```

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**

webpack 2.2.0-rc.2
Node.js 6.9.2
Chrome 55 on Windows 10

**Comment by sokra** [comment]
Looks like a bug in the `ReplaceSource`, it seem to handle replacements with newlines incorrectly.

**Comment by jjinux** [comment]
This bug is biting me too. I have a fairly complicated .babelrc file, but this patch is a workaround for the problem:

```
-        // This plugin places a "use strict"; directive at the top of all files.
-        ["transform-strict-mode"],
+        // ES2015 modules syntax to commonjs + "use strict"
+        // We don't use loose mode here because we don't need support ES3 browsers.
+        ["transform-es2015-modules-commonjs"],
```

This transforms ES6 modules into CommonJS syntax, which nullifies some of the advantages of Webpack 2, but it does fix the sourcemaps :-/

**Comment by Vanuan** [comment]
Is it because of `{ "modules": false }`?

**Comment by Vanuan** [comment]
I've also notices that it shows incorrect stacktraces when there's an error in import. E.g.:

```
import {a} from './foo'; // non-existent import

a(); // should show that 'a' is not a function
```

The error message is quite cryptic in this case.

**Comment by SpaceK33z** [comment]
Could you try again with [v2.3.2](https://github.com/webpack/webpack/releases/tag/v2.3.2)? This should be fixed now.

**Comment by nwoltman** [comment]
Yes, v2.3.2 fixes this 👍
