### ISSUE TITLE
Webpack 2 is not able to handle files with no exports

### ISSUE THREAD

**Issue by DevVersion** [webpack/webpack#3584]
**Do you want to request a *feature* or report a *bug*?**
- Bug

**What is the current behavior?**

- Webpack is not able to proceed when a file does not contain any `export`'s but the file is re-exported by another file.

```js
export * from './file-with-no-exports.js';
```

**If the current behavior is a bug, please provide the steps to reproduce.**

- I've created a small repository to reproduce the issue. Please take a look at it
  See https://github.com/DevVersion/webpack2-bug-no-exports

**What is the expected behavior?**
- Webpack 2 should be still able to handle exports from other files

Referencing https://github.com/angular/material2/issues/2401

**Comment by Kovensky** [comment]
Add `export {}` (exports nothing, not empty object) as a workaround.

Webpack still has to be able to support commonjs modules so the lack of `import` or `export` cannot be made into an error, like TypeScript's `isolatedModules` option...

`export * from` also can't just reject modules webpack thinks are commonjs as they may be babelmodules

**Comment by shlomiassaf** [comment]
@Kovensky Unless exporting an empty file is defined as invalid by the modules spec this is a bug.

In the `@angular/material` case its a third party lib so if the author won't fix it it won't work...

**Comment by DevVersion** [comment]
Can we get some feedback on this @d3viant0ne @TheLarkInn?

**Comment by sokra** [comment]
This is a bug that happens in this combination of exports:

`export { x } from "a"` -> `export * from "b"` -> `export * from "c"` -> c is a commonjs module not exporting x.

In this case `a` incorrectly exports `x = undefined` which overrides/hiddes other exports of `x` in `a`.

**Comment by d3viant0ne** [comment]
@DevVersion - Looks like you got one better ^^ :)

**Comment by sokra** [comment]
Note that an empty module (or any module without `import` or `export` statement) is threaded as commonjs module and disables tree shaking and other harmony optimizations for all module reexporting all exports (`export *`).

We cannot say anything about the exports of a commonjs module, so we cannot say anything about the exports of a module reexporting all exports of the commonjs module.

**Comment by d3viant0ne** [comment]
@sokra - Cheers for the quick turn around on this one :) All us Material junkies thank you in advance

**Comment by shlomiassaf** [comment]
@sokra RC3!!! so soon! THANK YOU!
