### ISSUE TITLE
Webpack [url/file-loader] is not resolving the Relative Path of URL

### ISSUE THREAD

**Issue by raviroshan** [webpack/webpack#3585]
I am facing a weird problem in Webpack regarding Relative Path. Let me try to explain the scenario :

I have 2 separate project in XZY directory :

1. Project-A [Bundling using Gulp] : **Stable, working and old project**
2. Project-B [Bundling using Webpack] : **New project**

As both the projects are using same Styling, so I wanted to reuse the SCSS files [consisting of standard variables, predefined layouts, modals, classes etc] of Project A into Project B.

![md57w](https://cloud.githubusercontent.com/assets/5485092/21486753/215864f6-cbe0-11e6-983b-adeaf12ca69b.png)

Now, if I am trying to "@import '../../../Project-A/Project A/Stylesheets/index.scss' in Project-B's index.scss as another partial it is working and webpack is generating the required CSS output file.

But as Project-A's index.scss is further referring background images, and @font-face src : url('../Fonts-arial.eot) from the respective Relative-Path, the webpack build is throwing error

> 'File / dir not found in XYZ/Project-B/Source/Stylesheets'.

I am not sure, why Webpack is not able to resolve the Relative path of assets inside Project-A and still looking inside 'Project B'.

**Comment by sokra** [comment]
`--display-error-details` should show more info

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by raviroshan** [comment]
@sokra : I have updated the ticket with the issue template. Also provided the Stackoverflow and Code Repo URL for further details. 
You can open the ticket now.

**Comment by Kovensky** [comment]
The problem seems to be related to how SCSS concatenates partials. It assumes urls point to paths in a server, but webpack expects them to point to real files.

I don't know if there is a way to make SCSS transform relative path in the URLs, but other solutions are to use paths starting with `/` (always treated as being a server path), or to [disable `url` handling](https://github.com/webpack/css-loader#disable-behavior) in `css-loader`.

**Comment by raviroshan** [comment]
@Kovensky : Thank you for your inputs. As  suggested by you, using a path starting with / is not breaking the build BUT **not solving the issue** either.
Basically  '/'  is ignoring the respective image and further url-loading or file-loader is not acting on it. [Not able to copy the file to the output folder].

Looking for a solution where the Image/Fonts/other assets can be copied instead of just solving the webpack build issue.
