### ISSUE TITLE
Binding exports / reexports are defined in the wrong order compared to imports

### ISSUE THREAD

**Issue by Kovensky** [webpack/webpack#3588]
```js
export * from './core';
export * from './modules';

export { default } from './core';
// disambiguate export
export { api } from './modules';
```

**What is the current behavior?**

The modules reexported from `./modules` itself, which have a circular dependency on the top level module above, do not see the `default` or the `api` export. The `api` export could be filed as a corner case, but the `default` export should definitely be available.

Reordering the `export { default } from './core'` to be above the `export * from './modules'` works around the problem.

---

To expand on this, the generated code currently looks like:

```js
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__core__ = __webpack_require__(/*! ./core */ "./src/core.js");
Object.defineProperty(exports, "__esModule", { value: true });
/* harmony namespace reexport (by provided) */ __webpack_require__.d(exports, "ready", function() { return __WEBPACK_IMPORTED_MODULE_0__core__["a"]; });
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_1__modules__ = __webpack_require__(/*! ./modules */ "./src/modules/index.js");
/* harmony namespace reexport (by provided) */ __webpack_require__.d(exports, "message", function() { return __WEBPACK_IMPORTED_MODULE_1__modules__["a"]; });
/* harmony reexport (binding) */ __webpack_require__.d(exports, "default", function() { return __WEBPACK_IMPORTED_MODULE_0__core__["b"]; });
/* harmony reexport (binding) */ __webpack_require__.d(exports, "api", function() { return __WEBPACK_IMPORTED_MODULE_1__modules__["b"]; });
```

It should look like:

```js
Object.defineProperty(exports, "__esModule", { value: true });
/* harmony namespace reexport (by provided) */ __webpack_require__.d(exports, "ready", function() { return __WEBPACK_IMPORTED_MODULE_0__core__["a"]; });
/* harmony namespace reexport (by provided) */ __webpack_require__.d(exports, "message", function() { return __WEBPACK_IMPORTED_MODULE_1__modules__["a"]; });
/* harmony reexport (binding) */ __webpack_require__.d(exports, "default", function() { return __WEBPACK_IMPORTED_MODULE_0__core__["b"]; });
/* harmony reexport (binding) */ __webpack_require__.d(exports, "api", function() { return __WEBPACK_IMPORTED_MODULE_1__modules__["b"]; });
Object.freeze(exports); // please ;)
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__core__ = __webpack_require__(/*! ./core */ "./src/core.js");
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_1__modules__ = __webpack_require__(/*! ./modules */ "./src/modules/index.js");
```

Circular references should be able to see the entire set of exports in the `Object.keys` of the module namespace. Actually accessing exports that depend on imports that have not yet initialized (e.g. if `core` had a circular reference that depended on `message`) should be a TDZ error. Hoisting all getters above all imports satisfies both conditions (only, due to `var`, any "TDZ" error will be a `TypeError` instead of `ReferenceError`, but that probably doesn't matter :wink:).

Circular references also should be able to see the `__esModule`. Note that `core` would not be able to see it (not that important as it's a webpack ES module anyway).

The prototype of the `exports` also should be `null`, and they should have a `Symbol.toStringTag` of `"Module"`, but implementing those might be difficult while keeping e.g. IE9 compatibility. The `exports` also should be frozen (`[[Set]]` should be a noop).

**Comment by sokra** [comment]
This was fixed.

> The prototype of the exports also should be null, and they should have a Symbol.toStringTag of "Module", but implementing those might be difficult while keeping e.g. IE9 compatibility. The exports also should be frozen ([[Set]] should be a noop).

We are not going to implement this for performance and size reasons.
