### ISSUE TITLE
webpack2 with less-loader: ERROR:  "is not a loader (must have normal or pitch function)"

### ISSUE THREAD

**Issue by ApolloTang** [webpack/webpack#3595]
Hello, 
I would like to report a problem of webpack2 when using less-loader.
I get a message:
```
"is not a loader (must have normal or pitch function)"
```

I think this is related to:
https://github.com/webpack/webpack/issues/3180
https://github.com/webpack/loader-runner/issues/9

I am using
```
node: v6.9.1
webpack: 2.2.0-rc.2
less-loader: 2.2.3
```

reproduce able via: 

> [https://github.com/ApolloTang/webpack2-setup/tree/master/30-less-loader](https://github.com/ApolloTang/webpack2-setup/tree/master/30-less-loader)

<img width="1096" alt="screen shot 2016-12-27 at 3 06 22 pm" src="https://cloud.githubusercontent.com/assets/1150961/21507456/64ba453c-cc46-11e6-801f-afab1bb08003.png">

**Comment by bebraw** [comment]
You should use `less-loader` over `less` at your loader definition. Otherwise it won't match the loader correctly as it requires full names now by default.

**Comment by ApolloTang** [comment]
yes, I forgot! "-loader" is now mandatory.

thanks for marking this urgent.

**Comment by ApolloTang** [comment]
is working now. Thanks
