### ISSUE TITLE
Deletion of compilation assets in 2.2.0-rc.2 fails in SizeLimitsPlugin

### ISSUE THREAD

**Issue by jdb8** [webpack/webpack#3596]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

A plugin which deletes assets during the `emit` step via `delete compilation.assets[filename]` causes the SizeLimitsPlugin to fail with the following traceback:

```bash
$ webpack
/Users/jb/code/webpack/lib/performance/SizeLimitsPlugin.js:37
					return compilation.assets[file].size()
					                               ^

TypeError: Cannot read property 'size' of undefined
    at /Users/jb/code/webpack/lib/performance/SizeLimitsPlugin.js:37:37
    at Array.map (native)
    at getEntrypointSize (/Users/jb/code/webpack/lib/performance/SizeLimitsPlugin.js:36:6)
    at /Users/jb/code/webpack/lib/performance/SizeLimitsPlugin.js:64:16
    at Array.forEach (native)
    at Compiler.<anonymous> (/Users/jb/code/webpack/lib/performance/SizeLimitsPlugin.js:62:5)
    at Compiler.applyPluginsAsyncSeries1 (/Users/jb/code/webpack/node_modules/tapable/lib/Tapable.js:122:13)
    at Compiler.afterEmit (/Users/jb/code/webpack/lib/Compiler.js:340:8)
    at Compiler.<anonymous> (/Users/jb/code/webpack/lib/Compiler.js:335:14)
    at /Users/jb/code/webpack/node_modules/async/dist/async.js:356:16
    at eachOfArrayLike (/Users/jb/code/webpack/node_modules/async/dist/async.js:929:9)
    at eachOf (/Users/jb/code/webpack/node_modules/async/dist/async.js:991:5)
    at Object.eachLimit (/Users/jb/code/webpack/node_modules/async/dist/async.js:3089:3)
    at Compiler.emitFiles (/Users/jb/code/webpack/lib/Compiler.js:303:20)
    at /Users/jb/code/webpack/node_modules/mkdirp/index.js:48:26
    at FSReqWrap.oncomplete (fs.js:123:15)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Gist with simple repro: https://gist.github.com/jdb8/41f3c0394b8af8652b2528aa20fd883f

Essentially, plugins which previously worked via deletion of compilation assets will fail in the latest version of webpack due to a change introduced to SizeLimitsPlugin here: https://github.com/webpack/webpack/commit/37b7474651d4cf68f5d14fae8b35f8fd45d51672. 

**What is the expected behavior?**

The deleted asset should be successfully removed and not emitted. This is the behaviour in previous versions of webpack (including 1.x.x and 2.1.0-beta.27).

**If this is a feature request, what is motivation or use case for changing the behavior?**

Some existing plugins rely on this behaviour. See https://github.com/numical/style-ext-html-webpack-plugin/issues/11 for example. It's unclear whether deletion of compilation assets *should* be supported (perhaps not?) but if not, something clearer should likely be shown to make it obvious that plugins shouldn't be doing this. I couldn't find any documentation outlining this when looking so far.

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**

Proposed diff to fix the issue, which appears to be equivalent, passes in the test suite, and works in my toy example:

```diff
--- a/lib/performance/SizeLimitsPlugin.js
+++ b/lib/performance/SizeLimitsPlugin.js
@@ -32,6 +32,9 @@ SizeLimitsPlugin.prototype.apply = function(compiler) {
                        var files = entrypoint.getFiles();

                        return files
+                               .filter(function(file) {
+                                       return compilation.assets.hasOwnProperty(file)
+                               })
                                .filter(assetFilter)
                                .map(function(file) {
                                        return compilation.assets[file].size()
```

I haven't created a PR for this (yet) since a) I'm unsure whether this is supported behaviour for plugins and b) I'd like some advice on a good location for a regression test. As stated, the existing tests all pass with this patch applied.

**Comment by TheLarkInn** [comment]
@jdb8 Would you be willing to submit a PR for this? This _appears_ like it might be a good solution. We can work on this together.

**Comment by sokra** [comment]
This happens because the Chunk still has a reference to the asset. Ignoring these assets seem to be a good idea.

**Comment by jdb8** [comment]
@sokra your solution looks great! Thanks for quickly triaging and fixing 👍
