### ISSUE TITLE
Documentation for pitch vs normal loader isn't very clear

### ISSUE THREAD

**Issue by gaearon** [webpack/webpack#360]
I'd submit a PR but honestly, having written two loaders, I'm not sure I really understand what a pitch loader is.

Is my understanding correct here:

- normal loaders always transform the source and thus rely on previous loader's output
- pitch loaders don't depend on the source itself and are happy with being given just a module name (that they can require), thus they are cacheable even if module's content changes
- everything that can be implemented as a pitch loader, can also be implemented as a normal loader, but pitch loaders are faster (cacheable with no regards to module output, may be run in parallel, etc)

?

**Comment by adjavaherian** [comment]
I've been writing a plugin and a loader and its nearly impossible to understand how to do this given the current documentation, that's probably why there around 10x as many browserify plugins in comparison.  It took me a day to write a meaningful browserify plugin and a week to do the same in weback, and I'm still stuck.  I've literally been writing the plugin docs myself as I find more information about them.  I think weback does a few things really well,  The plugin, compiler and the compilation and chunks are all really fantastic and well thought out, but its a total gray box.  There's little to no documentation on the interfaces.  Those APIs should be well documented with examples.  

The loaders have pre-loaders, pitching loaders, post loaders, and who knows what else?  And its the same story regarding documentation, but perhaps a little less complicated to suss out from reading the source of other loaders.

But my biggest frustrations so far are not having an inkling of an idea of how to simply inject a module into the compilation.  Or for example, if you instantiate webpack with the node api, how do you get access to the compilation object or simply return an object as opposed to writing json to the file system?  This is the kind of thing that should be easy. You've got this amazing machinery that basically says here I am, good luck writing a plugin for me.  

The documentation for developers is slim to none.  I'm a little bitter about it, but not giving up. I want to help make the documentation stellar.

**Comment by mik01aj** [comment]
+1 +1 +1. Have the same experience. I would love to read some better documentation about it.

**Comment by IngwiePhoenix** [comment]
Yup. The docs are usually what people actually leads into mislead information. I have been doing a lot of supportive work on Gitter lately - and i would find myself grabbing paragraphs of docs and link these specific paragraphs, and the uses would be like "Oh! I _totally_ oversaw that."

Loaders are generally OK with their explanation, but the deeper-down details seem lacking. Especially for devs.

- When should I make a pre-loader?
- When should I make a post-loader?
- What is a pitch-loader and how can they be used?
- How do I combine the use of a Plugin and Loader?

For instance, say you have your new scripting language that has a runtime. You could prepend a require statement to all the sources through a loader, OR provide an entry through the ProviderPlugin. Or, something else entirely. It's unclear.

I really like WebPack and I am totally set on it for many codeworks to come. But I really wish it would clarify a few terms and things.

Finally I had seen the "How to write a plugin" page having gotten an update, I am grateful for that. But there are still many common usecases that people usually have to dig up from other sources... or, other source codes entirely.

Just leaving these two cents here, in hope that we may be able to get better webpack docs.

I would gladly help. I mean, I have a good general understanding of it now, and even have had read the source at a few places.  So all I can do is suggest and think, for now.

**Comment by jhnns** [comment]
I totally agree :+1:

**Comment by amireh** [comment]
Sorry to resurrect an old thread. Sokra's comment in this thread on how the pitch phase works is invaluable and I believe should be added to the docs!

I'm trying to add support for pitching loaders in happypack (see https://github.com/amireh/happypack/pull/15) and now I realize after reading this thread and receiving some comments that there are also `preLoaders` / `postLoaders` in the loader application process.

**Is there any chance we can formally specify the loader application process?**

My second question is: by chance I happened to land upon https://github.com/webpack/loader-runner which is basically another version of what I had to write in https://github.com/amireh/happypack/blob/pitch-loaders/lib/applyLoaders.js to apply the loaders outside of a webpack compilation context.

**Can we please consolidate the efforts?**

It would be hard to maintain something like happypack when it relies on webpack's implementation details that could change between versions as I need to stay on top of it. However, the implementation in `loader-runner` makes assumptions that wouldn't work for happypack (like all the APIs that need to run *within* the compilation context).

**Comment by pksjce** [comment]
This issue was moved to webpack/webpack.io#116

**Comment by MRLuowen** [comment]
I found a problem when i use expose-loader. the right use way is "expose-loader!babel-loader"。
as you say, if expose-loader has return something in pitch func. the next babel-loader will not work,

but actually,when the pitch function is the first loader, even if the pitch has return, the next loader is still work.i don't know why, this is my test;

a!b!c!resource
a is the first loader
pitch a (return sth.)
       pitch b  (return sth.)
             pitch c (return sth.)
                 read file resource (adds resource to dependencies)
             run c  (not work)
       run b   (not work)
run a  (not work)
When a loader return something in the pitch phase the process continues with the normal phase of the next loader... Example:

pitch a
     pitch b (returns something)
            pitch c(not work)
            run c (not work)
     run b(not work)
run a  

so, i'm not sure am i right.any body can give me a confirm,thanks
