### ISSUE TITLE
Revisit including yarn.lock file

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack#3606]
Now that [Travis supports yarn out of the box](https://blog.travis-ci.com/2016-11-21-travis-ci-now-supports-yarn), the catch is that it uses `yarn.lock` to trigger the build. This is an open discussion to determine if we want to use `yarn.lock`. 

@thejameskyle @kittens Just to make sure because I feel like I never got an official answer: Does having a `yarn.lock` prevent you from getting upstream patch changes from dependencies when doing yarn install?

**Comment by SpaceK33z** [comment]
There is a nice blog post on the [yarn site about this](https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all). The tl;dr is at the bottom: "Please commit your yarn.lock files." [even in libraries].

**Comment by TheLarkInn** [comment]
Okay this answers my question a bit. I'm on board.
