### ISSUE TITLE
RFC: Performance Budgets v2 

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack#3611]
Placeholder fo new ideas and ways to make perf budgets smarter, and able to detect environments and "just work" only when "it's supposed to". Ref #3604 #3216

**Comment by TheLarkInn** [comment]
Subscribing @addyosmani for when the ball gets rolling on this.

**Comment by vigneshshanmugam** [comment]
Some of the ideas that comes to my mind
+ Find the Parse/Compile times by using the v8 stats (Lighthouse? / Headless browser testing?... )
+ Provide warnings for sizes to the CSS files as well
+ Can easily detect unused CSS on the page if we are going via lighthouse or headless browser

I also feel adding more ideas to Perf will make build really slower and diverges from webpack's core value as a bundler.

**Comment by addyosmani** [comment]
I think ultimately there are going to be performance audits that Webpack can only do and ones which it could do but would take sufficiently long to complete that I'd suggest we defer them out to Lighthouse. Wrt Webpack itself, I'd love to get smarter about validating folks configs and flagging where they could make tweaks for:

* Smarter vendor chunk loading
* Ensure folks have minification, compression etc setup
* Smarter tree-shaking suggestions (e.g workarounds for the 2.x issues)
* Preloading? or prefetching when possible 

Other ideas:

* Solve not knowing what ENV folks have setup that resulted in https://github.com/webpack/webpack/pull/3604 (do we have an issue to track that? :))
* Start-up time as @vigneshshanmugam notes. I have a PR to start this in Lighthouse over at https://github.com/GoogleChrome/lighthouse/pull/1695 which could be expanded to include V8's Runtime Call Stats for parse times
* Detect what JavaScript hasn't been used and can be used as a signal for code-splitting- Lighthouse x-ref here: https://github.com/GoogleChrome/lighthouse/pull/1871 (we're going to chill on this until after Google I/O)
