### ISSUE TITLE
Support `--support-ie8` option for UglifyJS plugin

### ISSUE THREAD

**Issue by everedifice** [webpack/webpack#3614]
UglifyJS plugin of webpack compress source in this manner.

src
```js
function test() {
  var o = {'default': true};
}
```

compressed
```js
function test(){var o={default:true};}
// throw `Expected identifier` error on IE8
```

When i compress source by UglifyJS2 Command line API. single quote is not disappear.

```sh
$uglifyjs bundle.js --support-ie8 -c -m -o bundle.min.js
```

```js
function test(){var o={'default':true};}
```

So i need to pass `support-ie8` option to UglifyJS plugin in webpack project.

Is there way to pass this option?

**Comment by sokra** [comment]
Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md).
