### ISSUE TITLE
Repo description points to 1.x docs

### ISSUE THREAD

**Issue by gitanupam** [webpack/webpack#3616]
I know 2.x docs are WIP but the repo [description](https://github.com/webpack/webpack) points to 1.x docs whereas README points to the 2.x web site everywhere (except an explicit mention to 1.x docs at one place). Not sure if that is intentional but seems like it would be good to make it consistent with the repo description (or maybe just have both links in repo description for now?)

**Comment by sokra** [comment]
The repo description points to the base site, which points to both webpack 1 and 2 doc
