### ISSUE TITLE
A bug with configs

### ISSUE THREAD

**Issue by botezatpv** [webpack/webpack#3628]
Im using Webpack@2 and it rise me an error: 

> Unexpected character '@' (19:0)
You may need an appropriate loader to handle this file type.
|  */
| 
| @import url("font_awesome/css/font-awesome.min.css");
| @import url("ionicons/css/ionicons.min.css");
| @import url("material-design-iconic-font/css/material-design-iconic-font.min.css");

My package.json is:

>   "dependencies": {
    "babel": "^6.5.2",
    "babel-es6-polyfill": "^1.1.0",
    "babel-runtime": "^6.20.0",
    "moment": "^2.17.1",
    "onsenui": "^2.0.0",
    "react": "^15.3.0",
    "react-dom": "^15.3.0",
    "redux": "^3.6.0",
    "stylus": "^0.54.5",
    "webpack": "^2.2.0-rc.2",
    "webpack-dev-server": "^1.16.1"
  },
  "devDependencies": {
    "autoprefixer": "^6.5.0",
    "aws-sdk": "^2.6.7",
    "babel": "^6.5.2",
    "babel-core": "^6.13.2",
    "babel-loader": "^6.2.4",
    "babel-plugin-transform-decorators-legacy": "^1.3.4",
    "babel-plugin-transform-es2015-for-of": "^6.18.0",
    "babel-plugin-transform-es2015-modules-commonjs": "^6.18.0",
    "babel-plugin-transform-runtime": "^6.15.0",
    "babel-polyfill": "^6.20.0",
    "babel-preset-es2015": "^6.13.2",
    "babel-preset-es2015-native-modules": "^6.9.4",
    "babel-preset-es2015-webpack-patch": "^6.4.1",
    "babel-preset-latest": "^6.16.0",
    "babel-preset-react": "^6.11.1",
    "babel-preset-stage-0": "^6.3.13",
    "babel-preset-stage-2": "^6.13.0",
    "babel-register": "^6.18.0",
    "brfs": "^1.4.3",
    "chai": "^3.5.0",
    "chai-as-promised": "^6.0.0",
    "chalk": "^1.1.3",
    "child-process": "^1.0.2",
    "cordova-sqlite-storage": "^1.4.7",
    "cordova-sqlite-storage-dependencies": "^1.0.0",
    "core-js": "^2.4.1",
    "css-loader": "^0.26.1",
    "detect-newline": "^2.1.0",
    "document-register-element": "^1.3.0",
    "enzyme": "^2.6.0",
    "esdoc": "^0.4.8",
    "esdoc-es7-plugin": "0.0.3",
    "eslint": "^3.8.1",
    "eslint-loader": "^1.6.0",
    "eslint-plugin-promise": "^3.0.0",
    "eslint-plugin-react": "^6.4.1",
    "eslint-plugin-standard": "^2.0.1",
    "extract-text-webpack-plugin": "^2.0.0-beta.4",
    "file-loader": "^0.9.0",
    "fs": "0.0.1-security",
    "install": "^0.8.4",
    "json-loader": "^0.5.4",
    "material-ui": "^0.16.1",
    "mocha": "^3.1.0",
    "mocha-jsdom": "^1.1.0",
    "mutationobserver-shim": "^0.3.2",
    "net": "^1.0.2",
    "node-uuid": "^1.4.7",
    "npm-check-updates": "^2.8.5",
    "onsenui": "^2.0.5",
    "opendatabase": "^0.2.1",
    "phantomjs-prebuilt": "^2.1.13",
    "postcss-loader": "^1.2.1",
    "progress-bar-webpack-plugin": "^1.9.1",
    "promise": "^7.1.1",
    "react": "^15.4.1",
    "react-addons-test-utils": "^15.4.1",
    "react-hot-loader": "^3.0.0-beta.6",
    "react-onsenui": "^1.1.0",
    "react-redux": "^4.4.5",
    "react-tap-event-plugin": "^2.0.1",
    "redux-logger": "^2.6.1",
    "redux-mock-store": "^1.2.1",
    "redux-promise-middleware": "^4.1.0",
    "redux-thunk": "^2.1.0",
    "sqlite": "^2.2.0",
    "style-loader": "^0.13.1",
    "stylus": "^0.54.5",
    "stylus-loader": "^2.4.0",
    "transform-loader": "^0.2.3",
    "url-loader": "^0.5.7",
    "webpack": "^2.1.0-beta.20",
    "webpack-dev-server": "^1.16.2",
    "websql": "^0.4.4"
  },

and [webpack.config.txt](https://github.com/webpack/webpack/files/677005/webpack.config.txt)

**Comment by SpaceK33z** [comment]
This is not a bug, it's a usage question.

You seem to be trying to include css from a node_module, but in your webpack config you specfically exclude the css-loader from applying on `node_modules`.

If this doesn't fix your issue, please ask on StackOverflow.
