### ISSUE TITLE
Unable to run tests locally on Node v6.7.0 & npm v3.10.3

### ISSUE THREAD

**Issue by neeharv** [webpack/webpack#3630]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
Cloned webpack, did `npm `i, ran `npm t`, errors out with 
```sh
Error: Cannot find module 'webpack/lib/removeAndDo'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/neeharvenugopal/Development/javascript/webpack/node_modules/extract-text-webpack-plugin/ExtractedModule.js:30:42)
```

**If the current behavior is a bug, please provide the steps to reproduce.**
With Node v6.7.0 and npm v3.10.3
```sh
git clone git@github.com:webpack/webpack.git
cd webpack
npm i
npm t
```

**What is the expected behavior?**
Should run tests!

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**
Looks like webpack has a `devDependency` on `"extract-text-webpack-plugin": "^2.0.0-beta"`, which loads a lib from webpack [here](https://github.com/webpack/extract-text-webpack-plugin/blob/master/ExtractedModule.js#L30)

This seems to be okay when using the plugin + webpack externally in other projects, but the plugin is also used for testing webpack itself. Hence the path `webpack/lib/removeAndDo` is broken when testing webpack locally.

**Comment by TheLarkInn** [comment]
Did you forget to run npm link && npm link webpack?

**Comment by neeharv** [comment]
@TheLarkInn ah hah! That was a bit idiotic of me. Thanks for helping correct the noob mistake 🍻
