### ISSUE TITLE
Cannot assign a scoped module to a specific entry point

### ISSUE THREAD

**Issue by rosskevin** [webpack/webpack#3631]
version: `webpack@2.2.0-rc.3`

**What is the current behavior?**
I'm following the [Code Splitting - Libraries guide](https://webpack.js.org/guides/code-splitting-libraries/) to split the `application` vs `vendor` bundle entry points.  All is well **except** a private scoped module; it is _not_ being placed in the `vendor` bundle as expected with the other packages.

**If the current behavior is a bug, please provide the steps to reproduce.**
[Here is a gist of my actual config](https://gist.github.com/rosskevin/dbc63c96d5e0c00777a72639bae2ee75).

This is likely more succinctly illustrated by slightly modifying the code from the [Code Splitting - Libraries guide](https://webpack.js.org/guides/code-splitting-libraries/):

```javascript
var webpack = require('webpack');
module.exports = function(env) {
    return {
        entry: {
            main: './index.js',
            vendor: ['moment', '@acme/foo'] // MODIFICATION: add any scoped package
        },
        output: {
            filename: '[chunkhash].[name].js',
            path: './dist'
        },
        plugins: [
            new webpack.optimize.CommonsChunkPlugin({
                names: ['vendor', 'manifest'] // Specify the common bundle's name.
            })
        ]
    }
};
```

**What is the expected behavior?**

In the test case above, the `@acme/foo` should be placed in the assigned `vendor` bundle, but it is instead placed in the `main` entry bundle.

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**

```
❯❯❯ node --version                                                                                                                               ⏎ feature/entry-point-split ✱
v7.2.0

❯❯❯ sw_vers                                                                                                                                        feature/entry-point-split ✱
ProductName:	Mac OS X
ProductVersion:	10.12.1
BuildVersion:	16B2659
```

**Comment by blade254353074** [comment]
Enviroment:

* webpack 2.2.0-rc.3
* node 6.7.0
* Mac OS X 10.11.6

---

I have same problem with webpack 2 and the same config:

```javascript
const entry = {
  libs: [
    'es6-promise/auto',
    'whatwg-fetch',
    'vue',
    'vue-router'
  ],
  vendor: [
    'assets/libs/fastclick',
    'components/request',
    'components/ui',
    urls.bootstrap, // bootstrap
  ]
}
// ...
new webpack.optimize.CommonsChunkPlugin({
  names: ['vendor', 'libs', 'manifest']
})
```

When `System.import('./component')` or `import('./component')`,
the `__webpack_require__ ` function will get the error: `TypeError: Cannot read property 'call' of undefined`

![image](https://cloud.githubusercontent.com/assets/9346008/21613575/c4a1d436-d210-11e6-998f-1e11296c49cd.png)

**BUT** when I using webpack-dev-server with the same config, `System.import` success and with out errors.

SO I must using this config for production build:

```javascript
new webpack.optimize.CommonsChunkPlugin({
  names: ['vendor', 'libs', 'manifest'],
  minChunks: Infinity
})
```

**Comment by sokra** [comment]
Could you go up one level in stack trace and show us the generated code in the `2.82554519.js` file? In addition to this I like to see the stats output for the compilation. Is `manifest.e2d728.js` and `2.82554519.js` part of the same compilation?

**Comment by blade254353074** [comment]
@sokra 

### [stats with bug](https://gist.githubusercontent.com/blade254353074/be2f9de36579e823ee68911870e8edfd/raw/c2b3de21e668d26b139456f71e7e3cee7f1e44aa/stats_with_bug.json)

```javascript
new webpack.optimize.CommonsChunkPlugin({
  names: ['vendor', 'libs', 'manifest']
})
```

![image](https://cloud.githubusercontent.com/assets/9346008/21632538/651cf848-d282-11e6-8600-f66406b2697e.png)

### [stats without bug](https://gist.githubusercontent.com/blade254353074/86e6e237e205fc516039aa97eeef861e/raw/a60dcb1697028c3e995f5e935998b8c40adfb642/stats_without_bug.json)

```javascript
new webpack.optimize.CommonsChunkPlugin({
  names: ['vendor', 'libs', 'manifest'],
  minChunks: Infinity
})
```

![image](https://cloud.githubusercontent.com/assets/9346008/21632515/36067b7e-d282-11e6-9f77-12e14b62b747.png)

I don't know if my commonsChunkConfig is correct.
The CommonsChunkPlugin document can't meet my needs.

**Comment by TheLarkInn** [comment]
Hey @rosskevin. 
Does this issue still happen if you change 
```
        entry: {
            main: './index.js',
            vendor: ['moment', '@acme/foo'] // MODIFICATION: add any scoped package
        },
```

to 

```
        entry: {
            main: './index.js',
            vendor: './vendor' // MODIFICATION: add any scoped package
        },
```

and inside vendor you do the following: 

```
import 'moment';
import '@acme/foo';
```

Curious whether there is some sort of resolver snafu or this is related to plugins itself. Or something different. Or even better, could I convince you to make a small reproducible repo in which this happens?

**Comment by sokra** [comment]
@blade254353074 Are you using the extract-text-plugin? Could you try to disable it and check if this affects the bug?

**Comment by blade254353074** [comment]
@sokra ...You are right. After disable extract-text-plugin, the builds are correct.

**Comment by blade254353074** [comment]
@sokra Is that a bug caused by  extract-text-plugin?

**Comment by sokra** [comment]
> @sokra Is that a bug caused by extract-text-plugin?

yes
