### ISSUE TITLE
Is it possible to load a non-existent file?

### ISSUE THREAD

**Issue by gkostov** [webpack/webpack#3633]
My use-case is that I need to load a type of file which does not exist but can be generated on-the-fly.

Imagine a file giving the current directory listing and I'd like to import that as `./some/path/dir.json`. Obviously I don't want to create those files in every directory and to maintain them so I wrote a loader to provide the content of the file when it is needed. The problem is that the loader will not be invoked because webpack tries to read the file itself from the system and not finding it breaks the entire chain. I even went on with NormalModuleReplacementPlugin to direct webpack to a file that exists hoping that it will be happy if it loads something but it turned that it actually replaced all references with just one - that dummy file.

Somewhere I read that pitching loaders are able to short-circuit the processing chain when the file content does not matter (as is my case) and tried that but still webpack insists on having a real file or it will not bother to run any loader.

I wonder if there are other options left to get webpack to load such a "virtual" file by passing the import request through my generator and to accept the output of the generator as the content which to be further processed as usual? I may need babel or some CSS stuff run on that content just like one would do with a normal file written to the file system.

Thanks

**Comment by ChristopherBiscardi** [comment]
You can load "non-files" by using a require statement that specifies the loader as such:

```javascript
require('mything-loader!')
```

or as an entry point: 

```javascript
entry: 'mything-loader!',
```

then write `mything-loader` to do whatever you need it to and return whatever code you want.

**Comment by gkostov** [comment]
Your suggestion appears equivalent to what I already have (but setup differently)
```
module:{
    loaders:[{
        test: /my-thing/,
        loader: 'mything-loader'
    }]
}
```
and it works well for files that exist but not for ones that don't.

Specifying the loader in the `requre()` call is not supposed to do anything different from an entry in the `loaders` block, right? Or am I missing something particular?

**Comment by sokra** [comment]
He proposed calling the loader without file.

---

It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by gkostov** [comment]
Oh, I see - to call `require()` but only specify a loader and no file - didn't expect that but will give it a try. Thanks

**Comment by whitecolor** [comment]
is it possible do accomplish this using some or custom resolver plugin?

**Comment by aleen42** [comment]
Is there any loader implemented for this use case?

**Comment by gkostov** [comment]
Not sure what you mean to use a loader for.

The problem described here was not the loader itself but that it wouldn't get invoked if the target file does not exist. But this got solved if the file was not specified in the import statement as usual but was provided as the query parameter instead. Now my loader gets called as expected but that's not a general purpose loader - it gets called when one of those special files is requested (certain JSON files in my case) and produces the respective ES6 source code.

Cheers

**Comment by aleen42** [comment]
I have created a loader like this, in which I can temporarily load JSON file during runtime, and this file can be non-existent during webpack compiling time.

```js
require('fileloader!?path=file&type=run')(function (content) {
    /** handle with content */
});
```

```js
/** custom-loader */
var loaderUtils = require('loader-utils');
var path = require('path');
var fs = require('fs');

module.exports = function () {
    this.cacheable && this.cacheable();

    var params = loaderUtils.parseQuery(this.resourceQuery);

    /** compile time */
    if (params.type === 'compile') {
        var root = this._compiler.options.resolve.root;
        var exportWhenExisted = function (dir, filePath) {
            return fs.existsSync(path.resolve(dir, filePath)) ? `module.exports = require('${filePath}')` : '';
        };

        if (typeof root === 'string') {
            /** string type */
            return exportWhenExisted(root, params.path);
        }  else {
            /** array type */
            var len = root.length;
            for (var i = 0; i < len; i++) {
                var result = exportWhenExisted(root[i], params.path);
                if (result) {
                    return result;
                }
            }
        }

        return '';
    }

    /** run time */
    if (params.type === 'run') {
        return `
            module.exports = function (callback) {
                var xhr = new XMLHttpRequest();
                xhr.onreadystatechange = function () {
                    if (xhr.readyState === 4) {
                        if (xhr.status === 200 || xhr.status === 304 || xhr.status === 202) {
                            if (/\\.json$/gi.test('${params.path}')) {
                                callback(JSON.parse(
                                        xhr.responseText
                                            .replace(/\\u2028/g, '\\\\u2028')
                                            .replace(/\\u2029/g, '\\\\u2029')
                                    )
                                )
                            }
                        }
                    }
                }
                
                xhr.open('GET', '${params.path}', true);
                xhr.send();
            };
        `;
    }
};
```

However, I haven't find a solution for requiring files using loader during runtime

**Comment by gkostov** [comment]
Could it be even possible? That would mean to bundle the loader so it can run and produce its output at runtime.

**Comment by aleen42** [comment]
Maybe not possible, but with using such a loader, I don't need to worry about non-existent files during compiling time at all. Especially in the case when I need to require a file, which may be created in the future.
