### ISSUE TITLE
Different loaders for same extension files

### ISSUE THREAD

**Issue by pvieira91** [webpack/webpack#3635]
I searched over several sites and did not find any answer for this which I think is a very common use case.

Is it possible to have multiple loaders for same extension? 
For example, I have two folders with svgs. 
- client/images 
- client/images/svgsprites

I would like to have different loaders being applied to those folders.

 {
      extensions: ['ttf', 'eot', 'svg', 'cur'],
      test: /\.(ttf|svg|eot|cur)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
      loader: 'file-loader?name=[name].[md5:hash:hex:20].[ext]'
    },
    {
      extensions: ['svg'],
      test: /svgsprite/.*\.svg(\?v=[0-9]\.[0-9]\.[0-9])?$/,
      loader: 'svg-sprite?name=[name].[md5:hash:hex:20].[ext]'
    }

Something like that. Is that possible? Thanks

**Comment by sqal** [comment]
i believe it should work if you use exclude/include in those two loaders. E.g.

```.js
const SVG_SPRITES_PATH = path.resolve('client/images/svgsprites');

// images loader
exclude: [
  SVG_SPRITES_PATH 
]

// sprite-loader
include: [
  SVG_SPRITES_PATH 
]
```

**Comment by pvieira91** [comment]
It worked perfectly. thanks
