### ISSUE TITLE
Option to disable code splitting completely

### ISSUE THREAD

**Issue by Strate** [webpack/webpack#3637]
As for now, there is no way to disable code splitting feature with some option.

Build & rebuild time is more with code splitting, so, it is useful from developer experience point of view to disable it in development mode. https://www.npmjs.com/package/babel-plugin-remove-webpack could handle some of cases, excluding modern `import()` signature.

**Comment by TheLarkInn** [comment]
Have you profiled and confirmed that code splitting is a main cost. I'd need to see it to believe it. Chrome Dev tools JS Profile Heap snapshots, etc.

**Comment by Strate** [comment]
@TheLarkInn I've not profiled this deeply, but I have simple test case for my project:
without babel-plugin-remove-webpack rebuild time ~10-12s
with babel-plugin-remove-webpack rebuild time ~4-5s

The biggest difference in webpack builtin profiler output is "sealing" operation: 100-300msec without splitting (with babel plugin enabled) and 4-5 sec with it.

**Comment by TheLarkInn** [comment]
Could you make a small example repo that I could clone to test locally?

**Comment by Strate** [comment]
Notable performance difference would be only on big repo.

**Comment by gustavohenke** [comment]
I'm interested in this feature, but not because of performance.
I have a config to bundle my tests... additional files in this case present no advantage for me.

**Comment by sokra** [comment]
`LimitChunkCountPlugin` with 0 chunks

**Comment by Yugloocamai** [comment]
using LimitChunkCountPlugin with 0 chunks produces 

`TypeError: content.indexOf is not a function`

**Comment by johnloven** [comment]
Webpack 4. Use 1 as the limit, as the single bundle also counts as a chunk.
```
plugins: [
    new webpack.optimize.LimitChunkCountPlugin({
         maxChunks: 1
     })
 ]
```

**Comment by tihuan** [comment]
Just tried `webpack.optimize.LimitChunkCountPlugin` and it actually added 7 seconds to build time, probably because `LimitChunkCountPlugin` merges chunks post processing?

> LimitChunkCountPlugin can post-process your chunks by merging them. 
[source](https://webpack.js.org/plugins/limit-chunk-count-plugin/)

**Comment by kwasimensah** [comment]
Also LimitChunkCountPlugin doesn;t play nicely with optimization.concatenateModules. I think their might be an order of operations issue?

I have multiple entries in my webpack.config.json, but it's for a chrome extension where they will run in different processes. So I don't mind duplicating code.

**Comment by trusktr** [comment]
Seems a bit of a performance waste to add a plugin just for this (that merges the chunks). Shouldn't there be a built-in option for this?

**Comment by Mythli** [comment]
Also in webpack 5 I believe, the plugin is changed making this option infeasable.

```
[webpack-cli] Failed to load '/Users/tobiasanhalt/Development/bamboo/blueprint-nodejs/sample/webpack.config.js' config
[webpack-cli] Invalid options object. Limit Chunk Count Plugin has been initialized using an options object that does not match the API schema.
 - options.maxChunks should be >= 1.
   -> Limit the maximum number of chunks using a value greater greater than or equal to 1.

```

**Comment by nl-brett-stime** [comment]
How to disable code chunks / splitting in Webpack 5... Use the `output` section of the config, not the `optimization` section:

```
{
  output: {
    chunkFormat: false
  }
}
```

**Comment by laggage** [comment]
> How to disable code chunks / splitting in Webpack 5... Use the `output` section of the config, not the `optimization` section:
> 
> ```
> {
>   output: {
>     chunkFormat: false
>   }
> }
> ```

For webpack5, this is the proper way, thx @nl-brett-stime ~

**Comment by ballidev** [comment]
quite sad how hard this was to figure out
