### ISSUE TITLE
2.2.0rc3: when installed locally, global version is used instead

### ISSUE THREAD

**Issue by nicois** [webpack/webpack#3639]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
with 2.2.0rc2: my webpack builds. With rc3 installed locally, I get errors as it uses the (old) global webpack.

**If the current behavior is a bug, please provide the steps to reproduce.**
webpack: https://gist.github.com/nicois/ddf218a56bf98475138ca561d656c134

**What is the expected behavior?**
webpack compiles

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**
When I explicitly enter webpack@2.2.0-rc.3 in package.json it appears to load, but when I execute webpack it picks up the global version instead, which rc2 doesn't do.

**Comment by arturparkhisenko** [comment]
@nicois maybe related to the https://github.com/webpack/webpack/issues/1740 ? already opened PR for this https://github.com/webpack/webpack/pull/3830
