### ISSUE TITLE
Plugins should warn about invalid options

### ISSUE THREAD

**Issue by gaearon** [webpack/webpack#364]
For instance, I repeatedly tried doing `new webpack.optimize.LimitChunkCountPlugin(n)` instead of `new webpack.optimize.LimitChunkCountPlugin({ maxChunks: n })`, and the plugin just no-oped.

**Comment by TheLarkInn** [comment]
This is a pretty good feature to have. Extract Text Plugin uses a schema validation as part of the webpack schema validation system. I'd imagine we could leverage this info.

**Comment by buoyantair** [comment]
Is this issue fixed? It looks like the PR got merged.. 🤔

**Comment by buoyantair** [comment]
@TheLarkInn Hi, is this issue fixed?

**Comment by sokra** [comment]
fixed
