### ISSUE TITLE
Support __dirname __filename properly for NodeJS

### ISSUE THREAD

**Issue by lygstate** [webpack/webpack#3642]
index.ts or index.js

The __dirname __filename should be as is.
The imported moduble by index.ts should dynamically 
create the new index.ts & index.js properly.

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
