### ISSUE TITLE
import scss files, there is  no outputs and no error log when using webpack

### ISSUE THREAD

**Issue by litinghh** [webpack/webpack#3644]
If i import css file, It's ok.
But if i import scss file, then there is no error log and no outputs

I have install webpack 1.14.0, node-sass 4.1.1
the config file for scss is:
{test: /\.scss$/,loaders: ["style", "css", "sass"]}

When I write scss with error, there will show error logs to  tell me where the error is.

Have you ever met this problem before? Or any suggestion for this problem？

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
