### ISSUE TITLE
Documentation on recordsPath

### ISSUE THREAD

**Issue by nmaves** [webpack/webpack#3653]
I am looking for a bit of insight on how to use the recordsPath file.

We are using code splitting and the commons chunk plugin and we would love to have long term caching of our bundles.

What we don't know or understand is how we get this with our recordsPath file.  We would like to know when/if we should be persisting this file.  Should it change for each developer on each build?  Does the webpack-dev server use/modify it?  We have different build commands for each ENV that we support (DEV, TEST, PROD).  Should that file change after each build and should we commit that to our SCM?

**Comment by bebraw** [comment]
Moved to https://github.com/webpack/webpack.js.org/issues/577. Please track there.
