### ISSUE TITLE
AgressiveSplittingPlugin with UglifyJsPlugin

### ISSUE THREAD

**Issue by nasushkov** [webpack/webpack#3656]
When I use AgressiveSplittingPlugin with UglifyJsPlugin I've got the following error:

> ERROR in 1_66dccb3f9724fc8bdde5.js from UglifyJs
> SyntaxError: Name expected [1_66dccb3f9724fc8bdde5.js:1,4]

My current config for these two plugins is pretty simple:

```
new webpack.optimize.AggressiveSplittingPlugin({
            minSize: 30000,
            maxSize: 50000
        }),
        new webpack.optimize.UglifyJsPlugin({
            compress: {
                screw_ie8: true,
                warnings: false
            }
        })
```

So what is the right way to use AgressiveSplittingPlugin with applied minification?

**Comment by TheLarkInn** [comment]
Thanks for submitting your first webpack issue!!!! Do you think that I could twist your arm into creating a tiny repo that I could reproduce this error? If you'd like, we could even create some tests inside of "configCases" and assert that errors don't occur.

**Comment by nasushkov** [comment]
Hi Sean,
Thank you for a fast response. 
`Do you think that I could twist your arm into creating a tiny repo that I could reproduce this error? `
Sure, here you go [https://github.com/nasushkov/aggressive-split-test](https://github.com/nasushkov/aggressive-split-test)

This small repository resembles, what I've got for my project.  This configuration is for DllPlugin part, so when I run build:dll, I see the error mentioned above.

**Comment by nasushkov** [comment]
Hi @TheLarkInn ,  did you manage to reproduce this in your environment?

**Comment by TheLarkInn** [comment]
I have not looked into this yet. Thank you for the follow up.
