### ISSUE TITLE
Should throw if not absolute output path 

### ISSUE THREAD

**Issue by jouni-kantola** [webpack/webpack#3660]
**Do you want to request a *feature* or report a *bug*?**
I guess it's a feature, since things do work now. However with words like "must be an absolute path", I'd call it a bug 😉 

**What is the current behavior?**
[Docs](https://github.com/webpack/webpack.js.org/blob/develop/content/configuration/index.md) and webpack-dev-server (v2.2.0-rc.0) requires `output.path` to be absolute (or `/`), however Webpack 2 (v2.2.0-rc.3) itself does not. This should probably be aligned.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Install webpack@v2.2.0-rc.3
2. Install webpack-dev-server@v2.2.0-rc.0
3. Set output config to `output: { path: 'dist' }`
4. Run webpack, it'll output fine to dist folder, however when served with webpack-dev-server you'll be presented with this message (which align with docs):
```Error: `output.path` needs to be an absolute path or `/`.```

**What is the expected behavior?**
Require absolute path for webpack for `output.path` property.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Consistent way of configuring Webpack, especially since docs mention an absolute path is required.

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**
- MacOS Sierra (10.12.1)
- node v6.8.0

**Comment by TheLarkInn** [comment]
I agree this is a great idea to add this kind of validation. In a perfect world I would love to bake this into our validation schema, but I don't think it's possible. Can we adapt the logic in WDS @SpaceK33z

**Comment by Kurtz1993** [comment]
Hey guys, I'm using webpack@2.3.1 and this validation breaks my Continuous Integration build 😢 
I'm using VSTS and the build server has:

Node: v6.9.1
npm: v4.3.0

**Comment by timse** [comment]
fixed by #4149
