### ISSUE TITLE
Uncaught TypeError after build with OccurrenceOrderPlugin in webpack@1.14.0

### ISSUE THREAD

**Issue by blade254353074** [webpack/webpack#3666]
Enviroment:
Chrome 55
Node 6.7
webpack@1.14.0

I found manifest throw a TypeError when using **OccurrenceOrderPlugin** to optimize build:

```javascript
new webpack.optimize.OccurrenceOrderPlugin(true)
```
```
Uncaught TypeError: Cannot read property 'call' of undefined   manifest.4cf9fa68.js:51
```
<img width="447" alt="2017-01-01 19 48 05" src="https://cloud.githubusercontent.com/assets/9346008/21581070/5493e032-d05b-11e6-9940-65186733dab5.png">

I created a [minimized webpack build project](https://github.com/blade254353074/webpack1-long-term-cache) to reproduce the OccurrenceOrderPlugin bug.
Just do:

```bash
git clone https://github.com/blade254353074/webpack1-long-term-cache.git && cd webpack1-long-term-cache
yarn
npm run build:occurrence
```

and then open the `occurrence/build/index.html`, you can see what's going on there.

As comparation, you can run `npm run build:1` to get the nonOccurrenceOrderPlugin build.

**Comment by bebraw** [comment]
Can you test against webpack 2 (release candidate atm)?

**Comment by blade254353074** [comment]
@bebraw I can test webpack 2 tomorrow, it's too late (2017-01-02 01:15:09)...

**Comment by blade254353074** [comment]
I've just found that the builds can be broken with or without OccurrenceOrderPlugin.
It seems that the webpack build results are related to the entry name "vendor".

### Case 1:

```javascript
{
  entry: {
    libs: ['es6-promise/auto', 'whatwg-fetch'],
    vendor: urls.index, // index is the entry
  },
  // ...
  plugins: [
    new HtmlWebpackPlugin({
      template: urls.html,
      chunks: ['manifest', 'libs', 'vendor']
    }),
    new webpack.optimize.CommonsChunkPlugin({
      name: ['vendor', 'libs', 'manifest'],
      minChunks: Infinity
    })
  ]
}
```

|Original|+OccurrenceOrderPlugin|
|---|---|
|![image](https://cloud.githubusercontent.com/assets/9346008/21582361/fb0fcbd2-d08e-11e6-96e9-7c04a6fcf537.png)|![image](https://cloud.githubusercontent.com/assets/9346008/21582357/e961ca34-d08e-11e6-85fd-bb6d7da2fd30.png)|

### Case 2:

```javascript
{
  entry: {
    vendor: ['es6-promise/auto', 'whatwg-fetch'],
    entry: urls.index, // index is the entry
  },
  // ...
  plugins: [
    new HtmlWebpackPlugin({
      template: urls.html,
      chunks: ['manifest', 'vendor', 'entry']
    }),
    new webpack.optimize.CommonsChunkPlugin({
      name: ['entry', 'vendor', 'manifest'],
      minChunks: Infinity
    })
  ]
}
```

|Original|+OccurrenceOrderPlugin|
|---|---|
|![image](https://cloud.githubusercontent.com/assets/9346008/21582352/be7b07d6-d08e-11e6-809f-dffe9c1053a7.png)|![image](https://cloud.githubusercontent.com/assets/9346008/21582348/9502bcf0-d08e-11e6-982b-a376014522d5.png)|

Now I'm confused...

You can reproduce it by doing this:

```bash
git clone https://github.com/blade254353074/webpack1-long-term-cache.git && cd webpack1-long-term-cache
yarn
npm run build:1
npm run build:occurrence
# Checkout the `example1/build/index.html` and `occurrence/build/index.html`
# Modify `webpack.config.js` to case 1
npm run build:1
npm run build:occurrence
# Checkout the `example1/build/index.html` and `occurrence/build/index.html`
```

**Comment by blade254353074** [comment]
@bebraw I tested with webpack 2.
https://github.com/blade254353074/webpack2-long-term-cache
I know that webpack 2 has already enabled OccurrenceOrderPlugin by default.
So... There is no problem with webpack 2.

**Comment by bebraw** [comment]
@blade254353074 Alright. So do you think it would be safe to close this issue based on that? webpack 1 won't receive fixes anymore.

**Comment by blade254353074** [comment]
@bebraw I think so.
People should move on, and webpack 2 feels more powerful than 1.
You guys did very good job! Thanks
