### ISSUE TITLE
Refactor Abstract Plugin `this._plugins` object to `Map`. 

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack#3674]
Per notes from @Kovensky. We could refactor [`this._plugins`](https://github.com/webpack/webpack/pull/3669/files#diff-98d86f85810fbbe76e0d3d0ec2843a5eR17) to use `Map` instead of an object. However, this plugin is used in a bunch of places and would be a larger refactoring job. Will link this to existing PR where noted but this is an open opportunity for anyone to submit a PR for. 

 https://github.com/webpack/webpack/pull/3669#discussion_r94292340

**Comment by sokra** [comment]
AbstractPlugin is only a helper used for shorter way writing plugins.

Maybe we should remove AbstractPlugin and write all plugins in a consistent way:

``` js
module.exports = class AbcPlugin {
  apply(compiler) {
    compiler.plugin("xyz", () => {});
  }
}
```

The class syntax is shorter anyway. AbstractPlugin doesn't bring much benefit here.

``` js
const AbstractPlugin = require("./AbstractPlugin");
module.exports = AbstractPlugins.create({
  "xyz": () => {}
});
```

**Comment by chicoxyzzy** [comment]
I'll file a PR

**Comment by chicoxyzzy** [comment]
I need some help with this.

lib/dependencies/RequireIncludeDependencyParserPlugin.js
```js
var AbstractPlugin = require("../AbstractPlugin");
var RequireIncludeDependency = require("./RequireIncludeDependency");

module.exports = AbstractPlugin.create({
	"call require.include": function(expr) {
		if(expr.arguments.length !== 1) return;
		var param = this.evaluateExpression(expr.arguments[0]);
		if(!param.isString()) return;
		var dep = new RequireIncludeDependency(param.string, expr.range);
		dep.loc = expr.loc;
		this.state.current.addDependency(dep);
		return true;
	}
});
```

How should it be rewritten as class and without Abstract plugin?

**Comment by sokra** [comment]
``` js
module.exports = class RequireIncludeDependencyParserPlugin {
  apply(parser) {
    parser.plugin("call require.include", expr => {

    });
  }
}
```

**Comment by chicoxyzzy** [comment]
This is exactly what I tried but tests failed

**Comment by chicoxyzzy** [comment]
Also I've tried to wrap code into this
```
module.exports = class RequireIncludeDependencyParserPlugin {
	apply(compiler) {
		compiler.plugin("compilation", (compilation, data) => {
			data.normalModuleFactory.plugin("parser", parser => {
				parser.plugin("call require.include", expr => {
					...
				})
			});
		});
	}
};
```

But tests fail in that case too

**Comment by sokra** [comment]
It's a **parser** plugin, so it's `apply(parser)`. See my code example. It's applied to the parser instance instead of the compiler instance.

**Comment by TheLarkInn** [comment]
This is because context is lost for `parser` because this is node 4.7 arrow functions. When you go multiple deep `this` still is `RequireIncludeDependencyParserPlugin` class, rather than this of function scope. 

Easy solution is to do. 

```javascript
module.exports = class RequireIncludeDependencyParserPlugin {
	apply(compiler) {
		compiler.plugin("compilation", (compilation, data) => {
			data.normalModuleFactory.plugin("parser", parser => {
                                const parserInstance = parser; 
				parserInstance.plugin("call require.include", expr => {
					...
				})
			});
		});
	}
};
```

**Comment by sokra** [comment]
``` js
module.exports = class RequireIncludeDependencyParserPlugin {
    apply(parser) {
          parser.plugin("call require.include", expr => {
		if(expr.arguments.length !== 1) return;
		var param = parser.evaluateExpression(expr.arguments[0]);
		if(!param.isString()) return;
		var dep = new RequireIncludeDependency(param.string, expr.range);
		dep.loc = expr.loc;
		parser.state.current.addDependency(dep);
		return true;
          });
    }
}
```

**Comment by chicoxyzzy** [comment]
#3683
