### ISSUE TITLE
How to enable sourcemaps generated from modules

### ISSUE THREAD

**Issue by borela** [webpack/webpack#3678]
Consider this structure:

```
Foo.js
Bar.js
node_modules
   Module A
      build
         qux.js
         qux.js.map
      src
         qux.js
   Module B
```

The `Modules A` and `Module B` are pre compiled and each has their source maps generated in the `build` dir. When I bundle the files with webpack `target: web`, the final source map generated looks for the `.js` files in the `build` directory instead of the original source in the `src` directory.

It looks like it is ignoring the `qux.js.map` and generating its own source map based on the build files, how can I configure webpack to use the pre compiled source maps from modules under the `node_modules` dir?

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
