### ISSUE TITLE
"At this point the application starts executing..." Where does it start?

### ISSUE THREAD

**Issue by wzup** [webpack/webpack#3679]
A screenshot:

![entry and context - google chrome 2017-01-02 19 51 24](https://cloud.githubusercontent.com/assets/3880497/21588835/9b49012c-d125-11e6-89df-9e1b2a1d6218.png)

It is not clear what you mean. Please improve the docs, add explanation.
Specifically,
* when does it start executing? When Webpack starts parsing it or when I plug in a parsed bundle in the page? `<script src="bundle.js"></script>`?

**Comment by sokra** [comment]
Please file this issue on the documentation repo. webpack/webpack.js.org

cc @bebraw
