### ISSUE TITLE
"every property of the exported object is copied..." Copied how? Where to?

### ISSUE THREAD

**Issue by wzup** [webpack/webpack#3681]
A screenshot:

![output - google chrome 2017-01-02 20 52 39](https://cloud.githubusercontent.com/assets/3880497/21589511/74f4e79a-d12d-11e6-8187-4c6fb1699dcf.png)

It is not clear what you mean. Please improve the docs, add explanation.
Specifically,
* What do you mean by `copied`? 
* Where is it `copied` to?
* Does it have any impact on performance? What exactly? During WP parse or in production code?

**Comment by sokra** [comment]
Please file this issue on the documentation repo. webpack/webpack.js.org

cc @bebraw
