### ISSUE TITLE
How to update WP? What version to use?

### ISSUE THREAD

**Issue by wzup** [webpack/webpack#3686]
I have `webpack 1.13.1` globally and locally
How to update each one to `2.x`. Seems your docs miss it

This doesn't work. I get `"webpack": "^1.14.0"`, not `2.x`
```
$ npm update webpack --save-dev
```

What is your current version to use whatsoever? Stable? recommended? LTS? How can I know what to use? No info about that

![webpack - google chrome 2017-01-03 03 47 22](https://cloud.githubusercontent.com/assets/3880497/21595304/81f5cf4c-d167-11e6-9bc4-82b5bd426163.png)
![webpack module bundler - google chrome 2017-01-03 03 47 53](https://cloud.githubusercontent.com/assets/3880497/21595307/84f29cc0-d167-11e6-8b11-264840e676fc.png)

**Comment by ludovicofischer** [comment]
I suspect you’re hitting this bug https://github.com/webpack/webpack/issues/3639

**Comment by TheLarkInn** [comment]
@wzup Correct. We are in Release Candidate right now, so latest stable on npm is still 1.14.X. 

If you'd like to update to webpack 2 you can use `npm install webpack@beta`
