### ISSUE TITLE
Consider using `lodash`.

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [webpack/webpack#3690]
There are more than a few places where it would certainly be useful.  More importantly, it's [already a dependency](https://github.com/webpack/webpack/blob/master/yarn.lock#L206), since `async` depends on it.
Admittedly, not the best argument.

**Comment by jhnns** [comment]
Could you provide some examples where you think it could be useful?

**Comment by TheLarkInn** [comment]
@jdalton You've mentioned a few times in the past that using lodash can help improve runtime and node engine performance. 

Trying to set your bias aside what kind of wins in build times would we see by using lodash?

**Comment by chicoxyzzy** [comment]
In most cases lodash is faster because it doesn't consider edge cases and is written the way JIT compilers can optimize code earlier and better. We won't use weird edge cases in Webpack codebase, rigth? :) So I think it's worth it because performance matters 👍

**Comment by chicoxyzzy** [comment]
What's most important here is that we need some example app and webpack config to run benchmarks against to measure performance advancements / regressions.

**Comment by wtgtybhertgeghgtwtg** [comment]
>Could you provide some examples where you think it could be useful?

The most obvious place would be cases like [this](https://github.com/webpack/webpack/blob/master/lib/DllPlugin.js#L22-L24)
```
Object.keys(entry).forEach(function(name) {
	compiler.apply(itemToPlugin(entry[name], name));
});
```
which could be rewritten as
```
_.forIn(entry, function(value, name) {
	compiler.apply(itemToPlugin(value, name));
});
```
[Type comparison](https://github.com/webpack/webpack/blob/master/lib/DefinePlugin.js#L43-L50) could also be simplified a bit, from
```
function toCode(code) {
	if(code === null) return "null";
	else if(code === undefined) return "undefined";
	else if(code instanceof RegExp && code.toString) return code.toString();
	else if(typeof code === "function" && code.toString) return "(" + code.toString() + ")";
	else if(typeof code === "object") return stringifyObj(code);
	else return code + "";
}
```
to
```
function toCode(code) {
	if(_.isNull(code)) return "null";
	else if(_.isUndefined(code)) return "undefined";
	else if(_.isRegExp(code) && code.toString) return code.toString();
	else if(_.isFunction(code) && code.toString) return "(" + code.toString() + ")";
	else if(_.isObject(code)) return stringifyObj(code);
	else return code + "";
}
```
but that's a more opinionated change.
I'll admit that these aren't particularly great arguments, and I wouldn't be making them if `lodash` wasn't already in the dependency tree.

**Comment by jdalton** [comment]
@TheLarkInn 
> You've mentioned a few times in the past that using lodash can help improve runtime and node engine performance.

I wouldn't worry about the perf angle unless you're dealing with uniqing, intersecting, or unioning arrays.

@wtgtybhertgeghgtwtg
> The most obvious place would be cases like this

Yep. Once you start using it places will jump out all over that can be simplified or streamlined.

**Comment by jdalton** [comment]
Btw. I'm taking Lodash in a different direction for v5 *(just started working on it)*. it won't ship with a monolithic package. Instead it'll enforce the cherry-picked form,`require('lodash/forOwn')`, as the default letting folks opt-in to the monolithic syntax, `_.forOwn`, by way of the `babel-plugin-lodash`.

**Comment by wtgtybhertgeghgtwtg** [comment]
Another use case that came up when looking into #3213.  A lot of `webpack` is dealing with arrays; consequently, a lot of `webpack` is dealing with for loops.
[An example](https://github.com/webpack/webpack/blob/master/lib/Entrypoint.js#L28-L40) from `Entrypoint.js`
```
getFiles() {
	let files = [];

	for(let chunkIdx = 0; chunkIdx < this.chunks.length; chunkIdx++) {
		for(let fileIdx = 0; fileIdx < this.chunks[chunkIdx].files.length; fileIdx++) {
			if(files.indexOf(this.chunks[chunkIdx].files[fileIdx]) === -1) {
				files.push(this.chunks[chunkIdx].files[fileIdx]);
			}
		}
	}

	return files;
}
```
could be rewritten as
```
getFiles() {
  const files = _flatMap(this.chunks, chunk => chunk.files);
  return _.uniq(files);
}
```

**Comment by jdalton** [comment]
or
```js
getFiles() {
  const files = _.flatMap(this.chunks, 'files');
  return _.uniq(files);
}
```

**Comment by wtgtybhertgeghgtwtg** [comment]
I wanted to avoid things that might not work in the next version.  `_.property` shorthand is getting removed in the next version, isn't it?

**Comment by jdalton** [comment]
@wtgtybhertgeghgtwtg Ah ok. It's still some time out but I plan on having shorthands usable via a babel plugin.

**Comment by aikar** [comment]
i would love to see benchmark proof that lodash's version is some how faster than simple basic constructs....

That entrypoint code for example, is pretty much the simplest form of the logic you can get.

I don't see how changing that just to reduce it to 2 lines is worth anything.

**Comment by imvetri** [comment]
Sharing my opinion. I'm neither a webpack nor lodash user. As per above conversation, I see the code readability is better with lodash.

**Comment by aikar** [comment]
Readability yes, but performance was mentioned as one reason for justification

**Comment by wtgtybhertgeghgtwtg** [comment]
I'm not going to make any arguments for `lodash` on the basis of performance.  Performance should not be the reason for its adoption.

**Comment by sokra** [comment]
ok, do your PRs...

**Comment by wtgtybhertgeghgtwtg** [comment]
I'm sorry, does that mean I should submit a PR to use `lodash`?
