### ISSUE TITLE
webpack@2.2.0-rc.2 cannot be used together with happypack

### ISSUE THREAD

**Issue by w567675** [webpack/webpack#3692]
## versions:  
    node@v6.9.1
    webpack@2.2.0-rc.2
    happypack@3.0.2
## code:   
  ```js

  module:{
     rules: [
         {
            test: /\.jsx?$/,
            loader: 'babel-loader',
            exclude(path) {
                return !!path.match(/\\plugins\\/);
            },
            happy: {
                id: 'jsx'
            },
        }
     ]
  } 
```
   
 

## errors:
   ```WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match
the API schema.
 - configuration.module.rules[0] has an unknown property 'happy'. These properties are valid:
   object { enforce?, exclude?, include?, issuer?, loader?, loaders?, oneOf?, options?, parser?, query?, resource?, resourceQuery?, rules?,
 test?, use? }

```

## why?
why can't use the custom property ?

**Comment by bebraw** [comment]
Webpack 2 schema doesn't support custom properties. There's something known as `LoaderOptionsPlugin`. I'm not sure if it would help in this particular case, though.

**Comment by jhnns** [comment]
This is clearly a happypack issue and should be reported there. webpack 2 is much stricter in regards of the config object's shape. Maybe @amireh can shed some light on it.

**Comment by w567675** [comment]
thanks @bebraw @jhnns

**Comment by amireh** [comment]
That notation for wiring up happypack was meant as a convenience but brought along too many issues so it was dropped in [v3.0](https://github.com/amireh/happypack/blob/master/CHANGELOG.md#300). It should not cause a problem when configured as shown in the readme.
