### ISSUE TITLE
Wildcards in entry points

### ISSUE THREAD

**Issue by ampedandwired** [webpack/webpack#370]
I think it would be really useful to support wildcards in webpack entry points, like this:

``` javascript
entry: "test/**/*Spec.js"
```

My use case here is to be able to find all tests in a directory without having to add them to a master index.js. This should work with watch mode as well so that new/removed/changed files in matching the glob would be automatically picked up.

I can work around this by using gulp or grunt to watch for the glob and pipe them into webpack, but it feels a bit awkward.

**Comment by wmertens** [comment]
@sokra could this be reopened? If wildcards are supported out of the box more people will know how to use them, and the watch functionality can detect new files...

**Comment by SgtPooki** [comment]
+1 for wildcard support. 

wildcard support would allow config file to be json, or put into package.json

**Comment by Phoenixmatrix** [comment]
@sokra there's another use case for wildcard entry points: not needing to restart webpack -watch when a new file is added. We have a lot of entry points for various reasons (eg: being able to run unit tests on a smaller subset of the files during development), and whenever someone adds a new test file, they'd have to restart webpack for it to get picked up, while everything else is handled by -watch.

**Comment by adamkdean** [comment]
+1

**Comment by kilianc** [comment]
+1

**Comment by kilianc** [comment]
@sokra this is mostly for the CLI not the config file, as you said the config file is fine and using `glob.sync` just works.

**Comment by tinirlove** [comment]
+1

**Comment by stevenjlho** [comment]
+1

**Comment by ixisio** [comment]
+1

**Comment by cspotcode** [comment]
A possible workaround is to use `require.context`:

```javascript
// webpack.config.js
entry: "test/all.js"
```

```javascript
// test/all.js
var req = require.context('./', true, /Spec\.js$/);
req.keys().forEach(req);
```

**Comment by jrhorn424** [comment]
Thanks @cspotcode. :+1: :star2:

**Comment by HaNdTriX** [comment]
Just in case someone is looking for a nice solution:
Check out: https://www.npmjs.com/package/webpack-glob-entries

**Comment by paulomunoz** [comment]
I prefer @sokra suggestion, just tested, and it works fine. It returns an array so I had to concat the extra items in my list, something like this:

```javascript
{
  main: ['./Development/index.js'].concat(glob.sync('./Shared/Legacy/**/*.js'))
}
```

**Comment by Phoenixmatrix** [comment]
@paulomunoz but that wont pick up new entries that get created while in watch mode. You can do some interesting things with require.context in some cases though.

**Comment by paulomunoz** [comment]
@Phoenixmatrix That's a good point, I'll keep that in mind if I have this kind of issue in the future, but I usually take the approach of setting one entry point and if a module is not referenced to somewhere in the 'dependency tree', there is no point for it to be included.

The only reason I wanted glob for this case was to automatically load a bunch of legacy crap code that doesn't really follow a very modularised approach, and I didn't want to pollute my config with each entry point. 

Does that make sense? But thank you again for pointing this out, it does indeed have this limitation.

**Comment by TheLarkInn** [comment]
Also entry takes a function that returns an object of entries so you could also this for dynamic entry creation and watching

**Comment by stereobooster** [comment]
@TheLarkInn can you give example of code? Thanks

**Comment by TheLarkInn** [comment]
https://github.com/zeit/next.js/blob/v3-beta/server/build/webpack.js#L42-L75

**Comment by wmertens** [comment]
@TheLarkInn how would WebPack know when to run the function again to get new entries in watch mode? Or is that not possible?

**Comment by kaankucukx** [comment]
+1

**Comment by wmertens** [comment]
@kaankucukx please don't use comments to only upvote, use the emoticon reactions instead. Everybody gets notified when you do and it won't change anything.

To add content to my comment: I think right now the only way to dynamically add/remove entries is to use the Webpack API directly, and stop/start the compiler with the new configuration every time the entries change.

**Comment by TrySound** [comment]
If you wish dynamic glob loading try this
https://github.com/TrySound/multi-entry-loader

**Comment by mac2000** [comment]
JFYI: just went back from my _dynamic entry point_ journey with some results https://github.com/mac2000/webpack-dynamic-entry-demo

hope it will help someone else also, in our case idea is that we have always running IIS web site which compiles requested file on the fly, so developer do not need to start and/or restart anything, just turn on PC and start coding and having fun

**Comment by zwwtj2014** [comment]
@wmertens Is there a good idea about this situation ( [WebPack know when to run the function again to get new entries in watch mode](https://github.com/webpack/webpack/issues/370#issuecomment-306124483) )?

---

In watch mode, a file corresponds to an watcher, and I have no idea to tell Webpack add a new watcher for new file and run compiler ...
```js
 Watcher {
    domain: null,
    _events:
     { closed: [Function: bound ],
       change: [Function: bound ],
       remove: [Function: bound ] },
    _eventsCount: 3,
    _maxListeners: undefined,
    directoryWatcher:
     DirectoryWatcher {
       domain: null,
       _events: [Object],
       _eventsCount: 1,
       _maxListeners: undefined,
       options: [Object],
       path: 'D:\\zww\\dyn',
       files: [Object],
       directories: {},
       watcher: [Object],
       initialScan: false,
       nestedWatching: false,
       initialScanRemoved: null,
       watchers: [Object],
       refs: 2 },
    path: 'D:\\zww\\dyn\\1.ts',
    startTime: 1501329677983,
    data: 0 }
```

**Comment by wmertens** [comment]
I guess the only real way forward is to have a way to add entry points to a
running compiler instance. I don't know how hard that would be.

**Comment by zwwtj2014** [comment]
@wmertens I think so. 
And I new a issue about this #5407 . Maybe webpack can watch a dir, and create dependency graph automatically... :laughing:

**Comment by dietergeerts** [comment]
It is possible to use a glob as your entry string. I'm playing with https://github.com/singapore/webpack-entries-plugin, and though I can't get it to work as is, while changing it, I can clearly see it working to have a glob as entry while all entry files are being watch....

**Comment by mac2000** [comment]
@dietergeerts you definitely can use globs with WebPack, it will work, the only thing you should watch for - it wont detect new files, here is possible workaround

**webpack.config.js**

```
const glob = require('glob')

module.exports = {
    entry: glob.sync('./src/**/*.js').reduce((entries, entry) => Object.assign(entries, {[entry.replace('./src/', '').replace('.js', '')]: entry}), {}),
    output: {
        path: __dirname + '/dist',
		filename: '[name].js',
		publicPath: '/'
    }
}
```

here we have glob entry point pointing to all found files

instead of build in webpack watch we are going to use webpack dev middleware

**server.js**

```
const fs = require('fs')
const express = require('express')
const webpackDevMiddleware = require('webpack-dev-middleware')
const webpack = require('webpack')

const app = express()

let options = {lazy: true}
let config = require('./webpack.config')
let compiler = webpack(config)
let middleware = webpackDevMiddleware(compiler, options)

app.use((req, res, next) => {
    const entry = req.path.substring(1).replace('.js', '')
    const target = `./src${req.path}`
    const exists = Object.keys(config.entry).indexOf(entry) !== -1
    if(!exists && fs.existsSync(target)) {
        config.entry[entry] = target
        compiler = webpack(config)
        middleware = webpackDevMiddleware(compiler, options)
    }
    middleware(req, res, next)
})

app.listen(process.env.PORT || 3000)
```

once started, webpack config will read all available files, then, while requesting for file, if it is not listed in entries - it is new one, so we are adding it to entries and reinstantiate webpack instance

**Comment by dietergeerts** [comment]
You don't neet to reinstantiate webpack, with the entries-plugin, which I got to work after some changes, you can just put a space in a watched file, and see the new one added. Currently, I'm looking into doing this automatically, but for the moment, it's faster to edit an already watched file to add the new ones then needing to re-instantiate webpack

**Comment by TrySound** [comment]
@dietergeerts It's possible to watch directories.
https://github.com/TrySound/multi-entry-loader

**Comment by LumpySpace** [comment]
@mac2000, thank you for your solution, it works for me.
But I didn't get how to put all scripts in one output folder if they were in different directories before. 
If I do this: 
` entry: glob.sync('./source/scripts/**/*.js').reduce((entries, entry) => Object.assign(entries, {[entry.replace('./source/scripts/', '').replace('.js', '')]: entry}), {}),
    output: {
        path      : static_root,
        publicPath: '../',
        filename  : `${structure.outputJs}[name].js`
    },`
it put js files like this:  "../js/folder1/file1.js, ",  "../js/folder2/file2.js" 
but I need 'file1.js' and 'file2.js' in one 'js' folder
if I'm replacing the path in entry like this:
`entry: glob.sync('./source/scripts/**/*.js').reduce((entries, entry) => Object.assign(entries, {[entry.replace('./source/scripts/**/', '').replace('.js', '')]: entry}), {})`
it builds a stucture in output like this: '../js/source/scripts/**/*.js'
I thought to use some another plugin just for copying js files from this folders in output, but if there are any solution for glob.sync?

**Comment by LumpySpace** [comment]
pff, it was so easy))
```
entry: glob.sync('./source/scripts/**/*.js').reduce((entries, entry) => Object.assign(entries, {[entry.split('/').pop().replace('.js', '')]: entry}), {}),
```

**Comment by 8427003** [comment]
i think who using "entry: glob.sync" is not considering the watch mode, in development environment with the watch mode，you must restart webpack.

**Comment by mac2000** [comment]
@8427003 look for comments and solutions, you do not need to restart webpack, new files will be added after first request to them 

https://github.com/webpack/webpack/issues/370#issuecomment-326872689

**Comment by 8427003** [comment]
@mac2000  you means "reinstantiate webpack instance" ，it equal to “restart webpack”。webpack is very slow when compiling a big project as you restart！

**Comment by 8427003** [comment]
i write a plugin, https://github.com/8427003/wildcards-entry-webpack-plugin

**Comment by wmertens** [comment]
Woohoo, well done!

**Comment by dietergeerts** [comment]
@mac2000 , yes, you need to restart if these files are never requested and you want them to be the entry points......

**Comment by msangel** [comment]
-1
I really don't need this. If I would, I will use `glob`.

**Comment by RiZKiT** [comment]
There is also: https://github.com/thecotne/webpack-glob-entry

**Comment by Milanzor** [comment]
I also wrote a plugin for this, which adds new entries in watch mode: https://github.com/Milanzor/webpack-watched-glob-entries-plugin => https://www.npmjs.com/package/webpack-watched-glob-entries-plugin

**Comment by thecotne** [comment]
so there is:

1. [webpack-glob-entries](https://github.com/aurimasniekis/webpack-glob-entries) by @aurimasniekis
2. [webpack-entries-plugin](https://github.com/singapore/webpack-entries-plugin) by @singapore
3. [multi-entry-loader](https://github.com/TrySound/multi-entry-loader) by @TrySound
4. [wildcards-entry-webpack-plugin](https://github.com/8427003/wildcards-entry-webpack-plugin) by @8427003
5. [webpack-glob-folder-entries](https://github.com/abrahamjagadeesh/webpack-glob-folder-entries) by @abrahamjagadeesh
6. [webpack-watched-glob-entries-plugin](https://github.com/Milanzor/webpack-watched-glob-entries-plugin) by @Milanzor
7. [webpack-glob-entry](https://github.com/thecotne/webpack-glob-entry) by me (@thecotne)

this is what's wrong with js community

**Comment by wmertens** [comment]
You mean, this is what's right with the JS community :) But it does point
to it being nice if webpack has this feature natively…

**Comment by Milanzor** [comment]
@thecotne If you look closer, the packages you listed are not at all the same. I made my plugin because when I needed it, Webpack didn't support my use-case (watch mode with globbed entries, still doesn't AFAIK). At that time I found 1 repo which got close to what I wanted, but the code and repo looked messy so created my own. 

Most of the packages you listed do not support watch mode.

Then there's the return question: Why did you create a new package when you feel that 'that is what is wrong with the js community'?

**Comment by thecotne** [comment]
@Milanzor i created my package because At that time I found 2-3 repo which got close to what I wanted, but the code and repo looked messy so created my own.

problem that thous packages try to solve are very similar (nearly same) 

for example: watch mode is added feature not completely other use case

i don\t quite remember what was special to my use case compered to others but i do remember that there was something missing and i did not like others code so i created mine from scratch

**Comment by Milanzor** [comment]
@thecotne So what's the problem in having 8 packages do all have something in common but also all do something different next to that common thing? I'm just trying to understand where your 'this is what is wrong with the js community' comes from and wether it is a valid point for me to do something with my package.

**Comment by thecotne** [comment]
i think creating one package under webpack-contrib or something like that 

and putting all features together with good documentation of all features will help community more than 8 different packages

as it's very confusing for other js devs when you want something and there are 8 packages that have nearly same name and do nearly same thing 

i feel same way about webpack and it's alternatives but that's another story

**Comment by dietergeerts** [comment]
I must agree with @thecotne , sometimes there are too many packages that does some things the same, but then other things different, and if you are not familiar with them, it's hard to pick the right one for your use-case. Sometimes it would be better to add the missing feature you want to an existing package. But then I can find myself with the others, that the code can be very messy and there isn't a lot of developer documentation in it, making it hard to add features, and making a new package is way easier. 

Imho, we should all try to create packages that are easy for others to contribute to so there isn't this wildgrow of packages. Also, sometimes a solution can be to come together and create a new package that combines all others.

I just wanted to share my thoughts, and yes, I also thing Webpack should have this feature out-of-the-box.

**Comment by thecotne** [comment]
i am going add this to my point

https://www.quora.com/What-is-JavaScript-fatigue

**Comment by Nettsentrisk** [comment]
> so there is:
> 
> webpack-glob-entries by @aurimasniekis
> webpack-entries-plugin by @singapore
> multi-entry-loader by @TrySound
> wildcards-entry-webpack-plugin by @8427003
> webpack-glob-folder-entries by @abrahamjagadeesh
> webpack-watched-glob-entries-plugin by @Milanzor
> webpack-glob-entry by me (@thecotne)
> glob-entry-webpack-plugin by @nricardo

So, any tips on which one of these solves the problem best? Maybe all the involved parties should combine forces and cooperate on one package that solves it the best? :)

**Comment by dietergeerts** [comment]
You can also use the spawn loader, depending on your needs.

**Comment by jaclyntan** [comment]
I've just started trying to make sense of how to use Webpack in my process and tbh I am reaaalllly surprised at how limiting the config is. I feel like this is something that should be default because as someone above mentioned, now it's like I'm opening a blind box of modules in order to incorporate this functionality-making something I thought would have been pretty straightforward that much more cumbersome and annoying to use...

**Comment by RiZKiT** [comment]
After quickly crawling through the list of plugins we decided to switch to [webpack-watched-glob-entries-plugin](https://github.com/Milanzor/webpack-watched-glob-entries-plugin) from @Milanzor, because it:

- preserves the input tree in the output!
- works with watch mode!
- allows easy exclusions (we needed that for our spec files)
- is small and has only two dependencies

Thnx @Milanzor!

**Comment by evilebottnawi** [comment]
One of the main problem - we need `node-glob` to do this, but `node-glob` (or other implementations) doesn't have ability to pass own `fs` (webpack use difference implementations for difference purpose - `memory`, `node` and other). It is big problem integrate `glob` into `webpack`. it also does not allow us to implement `clean` plugin and other whats need work with `fs` and use `glob`.

**Comment by Milanzor** [comment]
@RiZKiT No problem! If you need anything added, hit me up in an issue on my repo.

**Comment by cheapsteak** [comment]
> > webpack-glob-entries by @aurimasniekis
> > webpack-entries-plugin by @singapore
> > multi-entry-loader by @TrySound
> > wildcards-entry-webpack-plugin by @8427003
> > webpack-glob-folder-entries by @abrahamjagadeesh
> > webpack-watched-glob-entries-plugin by @Milanzor
> > webpack-glob-entry by me (@thecotne)
> > glob-entry-webpack-plugin by @nricardo

Not exactly the same thing, but hope this might somewhat help people finding this thread from google

![image](https://user-images.githubusercontent.com/743976/47621743-a1f55f80-dad2-11e8-9669-2476cf1ef696.png)

Chart from https://npmcharts.com/compare/webpack-glob-entries,webpack-entries-plugin,multi-entry-loader,wildcards-entry-webpack-plugin,webpack-glob-folder-entries,webpack-watched-glob-entries-plugin,webpack-glob-entry,glob-entry-webpack-plugin?minimal=true

Would also love if this were something provided by default by webpack

**Comment by aurimasniekis** [comment]
The moment, when you find out that your "once" used library is now pretty popular and still working 3 years later 😆

**Comment by mykt0ngc0** [comment]
@TrySound's  [**multi-entry-loader**](https://www.npmjs.com/package/multi-entry-loader)  still works well to this day, on v4.42.0.

Here's how I'm using it:
```
  entry: {
    frontend: ['multi-entry-loader?include=./src/js/*.js!', './src/sass/style.scss'],
    backend: './src/backend/index.js'
  }
```

**Comment by smarteist** [comment]
It works well to me: 
```js
entry: {
            ...glob.sync("./src/Assets/js/*.js").reduce((acc, curr) => {
                return {...acc, [path.basename(curr, ".js")]: curr}
            }, {}),
            ...glob.sync("./src/Assets/scss/*.scss").reduce((acc, curr) => {
                return {...acc, [path.basename(curr, ".scss")]: curr}
            }, {}),
        },
```
