### ISSUE TITLE
Increase Coverage for `AutomaticPrefetchPlugin`. 

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack#3712]
"As the `AutomaticPrefetchPlugin` depends on being in watch mode I would go with writing a test/watchCases test. After doing this you can take a look at the coverage and check what's missing." 

From #3682

**Comment by cynicaldevil** [comment]
I'll take this one!

**Comment by TheLarkInn** [comment]
All yours.

**Comment by TheLarkInn** [comment]
Make sure you tie the issue from your PR. So we can make sure this gets closed.

**Comment by SteveMieskoski** [comment]
I don't want to step on anyone's toes, but If this is still up in the air I'll take a go at it.

**Comment by cynicaldevil** [comment]
Go for it, I really can't come back to this one.

**Comment by SteveMieskoski** [comment]
Ok, I'll dive in.

**Comment by thatbraxguy** [comment]
Can this be closed now that https://github.com/webpack/webpack/pull/4471 is merged?

**Comment by esbenp** [comment]
@TheLarkInn `AutomaticPrefetchPlugin.js` has 95% coverage now :-)
