### ISSUE TITLE
Config loader chaining with ! in Webpack 2

### ISSUE THREAD

**Issue by jouni-kantola** [webpack/webpack#3713]
**Do you want to request a *feature* or report a *bug*?**
Bug, I guess?

**What is the current behavior?** 
Chaining loaders with `!` results in `Module not found: Error: Can't resolve 'style-loader!css-loader!less-loader'` (i.e: `use: 'style-loader!css-loader!less-loader'`).

This issue started out in a [tweet from me to @TheLarkInn](https://twitter.com/jouni_kantola/status/816337476566609924) and was followed by a
[gist with examples](https://gist.github.com/jouni-kantola/9a3466d900f78a3d7d81f571f76ce55e) where I asked if `!` loader chaining should work in Webpack 2. I'm under the impression it should still work.

**If the current behavior is a bug, please provide the steps to reproduce.**
I've setup a quite stripped branch, with two commits where one example works and the other does not. Both are discussed in the gist linked above. Should both work in Webpack 2?
Working (other working examples are mentioned in the gist):
https://github.com/jouni-kantola/webpack-output-by-build-type/commit/73b5473b85d5867e27511d80943e37a1c43776f7

Broke (other broke examples are mentioned in the gist):
https://github.com/jouni-kantola/webpack-output-by-build-type/commit/4844e85b0c3f283b11f771e4ce71753fe18921bb

**What is the expected behavior?**
I'm not sure, as I don't know if `!` should work when using:
```
module: {
    rules: [
      {
        test: /\.less$/,
        use: 'style-loader!css-loader!less-loader'
      }
    ]
  }
```
I guess that is a part of this issue, whether `!` chaining should work when configured in `webpack.config.js`. I can't find any references to this in the new docs.
 
**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**
OS: MacOS Sierra (10.12.1)
Node: v6.8.0
Deps:
```
"devDependencies": {
    "html-webpack-plugin": "^2.24.1",
    "inline-manifest-webpack-plugin": "^3.0.1",
    "webpack": "^2.2.0-rc.3",
    "webpack-dev-server": "^2.2.0-rc.0",
    "webpack-manifest-plugin": "^1.1.0",
    "style-loader": "^0.13.1",
    "css-loader": "^0.26.1",
    "less": "^2.7.1",
    "less-loader": "^2.2.3"
  }
```

**Comment by sokra** [comment]
`use: 'style-loader!css-loader!less-loader'` should not work.
`loaders: 'style-loader!css-loader!less-loader'` should work but is deprecated.

**Comment by bebraw** [comment]
`use: 'style-loader!css-loader!less-loader'` could result in a warning.

**Comment by jouni-kantola** [comment]
@sokra and @bebraw: So what is the correct way of configuring according to the new rules config? In the gist I explained how I tried a lot of different ways, and only deprecated `loaders: 'style-loader!css-loader!less-loader'` worked with `!` chaining.

**Comment by bebraw** [comment]
@jouni-kantola I have covered the basic variants [here](http://survivejs.com/webpack/understanding-loaders/loader-definitions/).

**Comment by bebraw** [comment]
@jouni-kantola That's my understanding, yeah. It's still useful for special usage (i.e. chaining within an `import`), but it's better to avoid it in loader definitions and use the other ways instead.

**Comment by jouni-kantola** [comment]
The reason why I post issues related to the config (like this one, as well: https://github.com/webpack/webpack/issues/3660), is because a lot of time for me while learning Webpack 1, was finding examples that differed a little in about a gazillion ways.

The description you made, @bebraw, is really good, imo; `It is good to keep in mind that webpack's loaders are always evaluated from right to left and from bottom to top (separate definitions). The right to left rule is easier to remember when you think about it in terms of functions.`.

A chaining section, should maybe be added to https://webpack.js.org/guides/migrating/ and to https://webpack.js.org/configuration/module/#rule-use. What do you think?

**Comment by bebraw** [comment]
> A chaining section, should maybe be added to https://webpack.js.org/guides/migrating/ and to https://webpack.js.org/configuration/module/#rule-use. What do you think?

Sure. [Open an issue at the docs repo](https://github.com/webpack/webpack.js.org/issues) or PR as you see fit. 👍
