### ISSUE TITLE
npm linked modules resolve ProvidePlugin dependencies wrong

### ISSUE THREAD

**Issue by Munter** [webpack/webpack#3733]
I have `Project`, which depends on a node module `Dep`. `Dep` uses `fetch` in its source code, but doesn't provide a polyfill. `Project` provides a polyfill for `fetch` like so:

```js
  plugins: [
    new webpack.ProvidePlugin({
      fetch: 'isomorphic-fetch'
    })
  ]
```

I'm making changes to `Dep`, so I linked it in using `npm link`. `Dep` is now a symlink in my `node_modules`.

When I run a build webpack tries to resolve `isomorphic-fetch` from  `Dep/node_modules` instead of `Project/node_modules`, which throws an error because `isomorphic-fetch` doesn't exist there.

Webpack version: 1.13.0
Node version: 6.9.2

**Temporary fix**

I've added the following to my config to override the module resolution:

```js
  resolve: {
    alias: {
      'isomorphic-fetch': path.join(__dirname, 'node_modules', 'isomorphic-fetch')
    }
  }
```

**Comment by sokra** [comment]
The provided module resolves relative to the injected file.

``` js
  plugins: [
    new webpack.ProvidePlugin({
      fetch: path.join(__dirname, 'node_modules', 'isomorphic-fetch')
    })
  ]
```

**Comment by blachawk** [comment]
@sokra, how can I use your technique to connect to a specific javascript file in my node_modules directory?

**Comment by alirezamirian** [comment]
Another solution is to use `resolve.symlinks: false` in your webpack config. 

This prevents module resolution of symlinked packages from being relative to their actual location.
