### ISSUE TITLE
Two DllReferencePlugin can't exist together

### ISSUE THREAD

**Issue by martinko2009** [webpack/webpack#3740]
[several DllReferencePlugin & import one js in html,throw ReferenceError: dll2 is not defined #3735](https://github.com/webpack/webpack/issues/3735)

project root
```
-example
     |-example.js
     |-example.html
-thirdparty
     |-jquery.cookie.min.js
-build
    |-dll1-min.js
    |-manifest_dll1.json
    |-dll2-min.js
    |-manifest_dll2.json
-webpack.config.js
-node_modules
```

webpack.config.js
```
var conf = {
    filename: './example/example.html', 
    template:  './example/example.html',
    inject: true,
    minify: {
      removeComments: true,
      collapseWhitespace: false
    },
    chunks:[ './example'],
    hash:false
  };
  module.exports.plugins.push(new HtmlWebpackPlugin(conf));
```

In that issues,When I delete 'scope' in the second DllReferencePlugin.Then I use 
<script src="../build/dll1-min.js"></script>
<script src="../build/dll2-min.js"></script>
```
in the dll1-min.js I bundle jquery-ui.js，in the dll2-min.js I bundle jquery.cookie.min.js
```
in the example.html, 
then I use $.cookie("name") in the example.js,
```
require("../thirdparty/jquery.cookie.min.js");
console.log($.cookie("name"));
```

 it has an error.
![image](https://cloud.githubusercontent.com/assets/3345987/21642565/15510962-d2be-11e6-8b43-b371b574d342.png)

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by martinko2009** [comment]
I have add issue template
