### ISSUE TITLE
performance hint does not work on windows 10

### ISSUE THREAD

**Issue by sylhero** [webpack/webpack#3748]
on windows it needs to be
`plugins: [
       new webpack.LoaderOptionsPlugin({
         // test: /\.xxx$/, // may apply this only for some modules
         options: {
           performance: ...
         }
       })
     ]
`
but on linux it needs to be
`
performance: {
  hints: false
}
`

webpack version: 2.1.0-beta.27

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
