### ISSUE TITLE
webpack indicates success for rejected config promise

### ISSUE THREAD

**Issue by also** [webpack/webpack#3759]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

If `webpack.config.js` returns a Promise that is rejected, the `webpack` command exits successfully with 0.

[This line](https://github.com/webpack/webpack/blob/8fd29574178527fdade0325d4f3d63ce8af1e8af/bin/webpack.js#L169) in `bin/webpack.js` does not set an exit code.

**If the current behavior is a bug, please provide the steps to reproduce.**

Run `webpack` with this [`webpack.config.js`](https://gist.github.com/also/680789fac8395908d9fa2bf81dcb96d7)

```javascript
module.exports = () => Promise.reject(new Error('invalid config'));
```

**What is the expected behavior?**

`webpack` should exit with an error on a rejected promise. It shouldn't indicate success if nothing is built.

**Comment by sokra** [comment]
You are right. Do you want to submit a PR?
