### ISSUE TITLE
performance hint does not work on windows 10

### ISSUE THREAD

**Issue by sylhero** [webpack/webpack#3761]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
require different configuration for windows and linux

**If the current behavior is a bug, please provide the steps to reproduce.**
pack something over the size limit and you will see the performance hint message

**What is the expected behavior?**

should be either 
``` js
plugins: [
       new webpack.LoaderOptionsPlugin({
         // test: /\.xxx$/, // may apply this only for some modules
         options: {
           performance: ...
         }
       })
     ]
``` 
or
``` js
performance: {
  hints: false
}
``` 
**If this is a feature request, what is motivation or use case for changing the behavior?**
no it's a bug

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**
windows 10  webpack version: 2.1.0-beta.27

on windows it needs to be
``` js
plugins: [
       new webpack.LoaderOptionsPlugin({
         // test: /\.xxx$/, // may apply this only for some modules
         options: {
           performance: ...
         }
       })
     ]
```
but on linux it needs to be
``` js
performance: {
  hints: false
}
```

webpack version: 2.1.0-beta.27

**Comment by sokra** [comment]
It's always

``` js
performance: {
  hints: false
}
```

Using `LoaderOptionsPlugin` is not correct here.

I'm also using windows 10 and it's working for me.

Try to use to latest version `^2.2.0-rc.3`

**Comment by sylhero** [comment]
with webpack 2.1.0-beta.27 it prints out that error message on the screen

**Comment by sokra** [comment]
performance hints were introduced on v2.1.0-beta.28: https://github.com/webpack/webpack/releases/tag/v2.1.0-beta.28
