### ISSUE TITLE
webpack --watch crashes npm cli?

### ISSUE THREAD

**Issue by artnova-david** [webpack/webpack#3764]
Hi,
I recently posted this issue [https://github.com/npm/npm/issues/15275](url) in the npm repo and there someone indicated this could be a webpack (watch) related issue. Has anyone encountered this problem on windows 10?

Thanks.

**Comment by sokra** [comment]
As it works fine without `npm` I guess it's not a webpack issue.

It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by artnova-david** [comment]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
CLI crashes when using --watch in custom script in package.json

**If the current behavior is a bug, please provide the steps to reproduce.**
Hi,
I recently posted this issue [https://github.com/npm/npm/issues/15275](url) in the npm repo and there someone indicated this could be a webpack (watch) related issue. Has anyone encountered this problem on windows 10?

[npm-debug.txt](https://github.com/webpack/webpack/files/688059/npm-debug.txt)

**What is the expected behavior?**
Not to crash when closing the CLI
