### ISSUE TITLE
[Docs] Babel now seems to support dynamic imports

### ISSUE THREAD

**Issue by halt-hammerzeit** [webpack/webpack#3777]
The [migration guide](https://webpack.js.org/guides/migrating/) says:

> If you want to use import with Babel, you'll need to install/add the dynamic-import syntax plugin while it's still Stage 3 to get around the parser error. When the proposal is added to the spec this won't be necessary anymore.

At the same time, seems that it has been added recently:
https://github.com/babel/babel/issues/4944

I'm now running my project without that babel syntax plugin and it seems to work.
So maybe reflect that in the migration guide, that the syntax plugin is not needed for the newest babel (or that developers should update their babel, though I'm not sure which package exactly, I just reinstalled all `node_modules` from scratch and it worked).

**Comment by sokra** [comment]
Please file this issue on the documentation repo: webpack/webpack.js.org

cc @bebraw
