### ISSUE TITLE
two DllReferencePlugin doesn't work

### ISSUE THREAD

**Issue by martinko2009** [webpack/webpack#3783]
Because the wepack 2.0 is still beta version,so I use wepack 1.13.1 and 1.14.0

**Do you want to request a *feature* or report a *bug*?**
I want to report a bug

**What is the current behavior?**
when I bundle two jquery component by two DllPlugins, I use two of them in html by DllReferencePlugin in webpack.config.js
the second plugin doesn't work.I can not use the method in them.
but When I  use only one of two,it works.
**If the current behavior is a bug, please provide the steps to reproduce.**

I don't know how to deal with it
**What is the expected behavior?**
I expect those can works
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**
Window7, firefox 47, chrome 52, node v4.4.5

project root
```
-build
-example
    |--example.html
    |--example.js
-dll
    |--dll1.config.js
    |--manifest_dll1.json
    |--dll2.config.js
    |--manifest_dll2.json
-thirdparty
    |--jquery.cookie.min.js
-node_modules
-webpack.config.js
```
**dll1.config.js**
```
var webpack = require('webpack');
var path = require('path');
var glob = require('glob');

var entries = ['jquery',"jquery-ui"];
var jqueryuis = [];
glob.sync("../node_modules/jquery-ui/ui/widgets/*.js").forEach(function (entry) {
    jqueryuis.push("jquery-ui/ui/widgets/"+path.basename(entry));
});
entries = entries.concat(jqueryuis);
module.exports = {
    entry:{
       "dll1":entries
    },
    output: {
        path: 'build',
        filename: '[name]-min.js',
        library: '[name]',
    },
    plugins: [
        new webpack.ProvidePlugin({
                "$": 'jquery',
                "jQuery": 'jquery',
        }),
        new webpack.DllPlugin({
            path: path.resolve( __dirname,'./manifest_[name].json'),
            name: '[name]',
            context: path.resolve(__dirname,"../"),
        })
    ]
};
```
**dll2.config.js**
```
var webpack = require('webpack');
var path = require('path');

var entries = [
    path.resolve( __dirname,'../thirdparty/jquery.cookie.min.js'),
];
module.exports = {
    entry:{
       "dll2":entries
    },
    output: {
        path: 'build',
        filename: '[name]-min.js',
        library: '[name]',
    },
    plugins: [
        new webpack.ProvidePlugin({
                "$": 'jquery',
                "jQuery": 'jquery'
        }),
        new webpack.DllPlugin({
            path: path.resolve( __dirname,'./manifest_[name].json'),
            name: '[name]',
            context: path.resolve(__dirname,"../"),
        })
    ]
};
```
**webpack.config.js**
```
new webpack.DllReferencePlugin({
    context: __dirname,
    manifest: require('./dll/manifest_dll1.json'),
}),
new webpack.DllReferencePlugin({
    context: __dirname,
    manifest: require('./dll/manifest_dll2.json')
}),
```
**example.html**
```
<script src="./dll/dll1-min.js"></script>
<script src="./dll/dll2-min.js"></script>
```
**example.js**
```
require("../thirdparty/jquery.cookie.min.js");
$.cookie("dll","dllall");
```

I found require("../thirdparty/jquery.cookie.min.js"); is back a empty object

![image](https://cloud.githubusercontent.com/assets/3345987/21681378/e9e5145e-d389-11e6-8fbc-8227116b8940.png)

**Comment by sokra** [comment]
both dlls contain the jquery module. So you get two different instances of jquery.

It's not a webpack bug, but a problem with your setup. Make sure that the dlls doesn't share modules. Or use the CommonsChunkPlugin to create one root dll which hoists shared modules.

**Comment by martinko2009** [comment]
what is the share modules?
Could you tell  me how to make share modules.
 How to create one root dll and how to share the modules?
I have no idea about this.Please tell me more.Thank you.

**Comment by martinko2009** [comment]
@sokra,hello,I still am not able to understand what you said.
like,
1.Make sure that the dlls doesn't share modules, what is that the dlls share modules.
2.how to use the CommonsChunkPlugin to create one root dll which hoists shared modules.May you give some examples about the second problem.
thank you.

**Comment by martinko2009** [comment]
@sokra 
the dlls do shared some modules.
1.dll1 has included vue.js.dll2 has a js file about custom directive code.
2.In dll2.js ,it has require("jquery") code,so like you said maybe there is two diference jquery instance,How can i deal with it.
