### ISSUE TITLE
webpack 1.13.3  bug  ?

### ISSUE THREAD

**Issue by sundaesfruit** [webpack/webpack#3788]
when i  used  webpack to package my javascript  file, whose  **version  is 1.13.3** , i found the default could not be change "default" .  i sent a lot of time to found  bug that i came across.  when i  checked  the file that was packaged **,i  saw  the default could not  be changed "default".**

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
