### ISSUE TITLE
Dynamic require breaks when using more than one webpack bundle at the same time

### ISSUE THREAD

**Issue by folmert** [webpack/webpack#3791]
I've run into this issue several times, and it seems the reason behind it lies in conflict between multiple webpack bundles.

While it's possible to generate multiple bundles like this:
```
    var path = require('path');
    
    module.exports = function () {
        return [
            // APP:
            {
                resolve: {
                    modules: [
                        path.resolve('./modules/')
                    ]
                },
                entry:   './app.js',
                output:  {
                    filename: 'app.dist.js',
                }
            },
    
            // CHARTS:
            {
                resolve: {
                    modules: [
                        path.resolve('./modules/')
                    ]
                },
                entry:   './charts.js',
                output:  {
                    filename: 'charts.dist.js',
                }
            }
        ];
    };
```

it's impossible to use them both at the same time (on same page), because if  I use `System.import` (or `require.ensure`) both bundles will share one `modules` array.
In effect, we end up with namespace conflict and some chunks might not load. This can be easily tested by inspecting `__webpack_require__ function`:

```
console.log(modules);
/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
```

this showed me that app.dist.js and charts.dist.js both share same `modules` array. So if I had 3 dynamically loaded chunks (1 coming from charts.dist.js, 2 from app.dist.js), one of them was not added to modules array and [couldn't be dynamically loaded](http://stackoverflow.com/questions/41487906/system-import-fails-at-first-attempt-modulesmoduleid-is-undefined).

Correct me if I'm wrong, but it must be a bug, because when I combined app.dist.js and charts.dist.js into one bundle, all 3 chunks where loaded correctly.

**Comment by sokra** [comment]
If using multiple webpack runtimes with JSONP chunk loading on the same page you need to specify different jsonp functions for each one. `output.jsonpFunctionName`

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template.

**Comment by LinBoLen** [comment]
maybe related to #2112

**Comment by PunkHaz4rd** [comment]
@sokra How do you change output.jsonpFunctionName in angular 6 ? Is it in angular.json file ?
Thx

**Comment by GIOkafor** [comment]
> If using multiple webpack runtimes with JSONP chunk loading on the same page you need to specify different jsonp functions for each one. `output.jsonpFunctionName`

What file do you have to edit to get this effect?

**Comment by lukemwillis** [comment]
The webpack config key for this is now called [output.jsonpFunction](https://webpack.js.org/configuration/output/#outputjsonpfunction).

**Comment by wegry** [comment]
@PunkHaz4rd you can take a look at [@angular-builders/custom-webpack](https://github.com/just-jeb/angular-builders/tree/master/packages/custom-webpack) for changing webpack config underneath Angular. We use it currently with Angular 8.
