### ISSUE TITLE
Following "Getting started" guide shows a very different output and huge warnings

### ISSUE THREAD

**Issue by ntrrgc** [webpack/webpack#3794]
I'm trying to learn webpack, so first I read the [Getting started](https://webpack.js.org/get-started/#creating-a-bundle) tutorial prominently advertised in the front page and followed it step by step.

At the end of the **Creating a bundle** section this is the output from webpack that, according to the tutorial, I should expect:

```
webpack app/index.js dist/bundle.js

Hash: a3c861a7d42fc8944524
Version: webpack 2.2.0
Time: 90ms
   Asset     Size  Chunks             Chunk Names
index.js  1.56 kB       0  [emitted]  main
   [0] ./app/index.js 170 bytes {0} [built]
```

But I get this instead:

```
.\node_modules\.bin\webpack app\index.js dist\bundle.js
Hash: fb6ce4ce46193cb98744
Version: webpack 2.2.0-rc.3
Time: 621ms
    Asset    Size  Chunks                    Chunk Names
bundle.js  544 kB       0  [emitted]  [big]  main
   [0] ./~/lodash/lodash.js 540 kB {0} [built]
   [1] (webpack)/buildin/global.js 506 bytes {0} [built]
   [2] (webpack)/buildin/module.js 548 bytes {0} [built]
   [3] ./app/index.js 318 bytes {0} [built]

WARNING in asset size limit: The following asset(s) exceed the recommended size limit (250 kB).
This can impact web performance.
Assets:
  bundle.js (544 kB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (250 kB). This can impact web performance.
Entrypoints:
  main (544 kB)
      bundle.js


WARNING in webpack performance recommendations:
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/
```

There are many confusing aspects on these messages:

1. There is a version mismatch: The tutorial shows version: 2.2.0 while my installed version is 2.2.0-rc3... but at the time of writing 2.2.0 has not been released! Seemingly the tutorial comes from the future, even if not a far away one.

2. There are three big warnings, never shown and never mentioned in the tutorial... Certainly not the smoothest introduction.

3. Even if scary, the actual output of webpack kind of makes sense: I imported lodash and lodash is bundled, resulting in a bundle as huge as lodash. On the other hand the output from the tutorial is quite strange:

    * It does not even mention lodash. How is it supposed to work? Is it really bundled?
    * Judging from the output from my actual webpack build, the output file is written in the first line (Asset: `bundle.js`). But the output from the tutorial shows *Asset: `index.js`*. How come that both were given the same arguments in the same order but the one from webpack is seemingly writing in a different file, moreover one named exactly like its input main file?
    * How come ` ./app/index.js` is 170 bytes only in the tutorial output? Copying the source code from the page yields a 305 bytes in ASCII with LF endings, almost twice as much.
    * The bundle from the tutorial output is only 1.56 kB, quite impressive if it's actually bundling part of lodash! Unfortunately, when I run webpack in my machine, compiling a single empty file with no dependencies creates a bundle of 2.51 kB in ASCII with LF endings. That's 60% more for literally nothing, how unfair!

**Comment by jouni-kantola** [comment]
@ntrrgc: This issue probably is more suitable in https://github.com/webpack/webpack.js.org/issues

**Comment by chrisVillanueva** [comment]
@ntrrgc : please contribute your thoughts here:

https://github.com/webpack/webpack.js.org/issues/486

We can combine issues there to improve docs.

**Comment by bebraw** [comment]
Yup. Better continue at the docs tracker. 👍
