### ISSUE TITLE
Add watch php files to execute phpunit tests

### ISSUE THREAD

**Issue by cmosguy** [webpack/webpack#3798]
Hey @TheLarkInn,

Thanks for getting back to me on [twitter](https://twitter.com/TheLarkInn/status/817141858958712833).

What I was looking for was some type of webpack snippet that I could place in my config file so that I could add the ability to do a `npm run tdd` from my `package.json`.  In there I would call webpack with some argument that would run the task to sit and watch like `webpack --watch --progress --hide-modules tdd` and run the task so that I could do the following:

1.  Watch for `*.php` files in my directory tree of my choosing.
2.  When any file changes, execute the `./vendor/bin/phpunit` command
3.  Bonus:  If it is also possible to do something where I do webpack --watch --progress --hide-modules tdd --filter=sometest`, that would be cool too so that I can run the `./vendor/bin/phpunit --filter=somtest` command.

The motivation here is that @jefferyway has come out with [laravel-mix](https://github.com/JeffreyWay/laravel-mix).  But currently it lacks the ability to do this, so I was hoping to figure out the `webpack.config.js` tricks to add this in so I could contribute to that other project.

Cheers!
Adam

**Comment by TheLarkInn** [comment]
@sokra can we synthetically tie watchers? Wasn't unsure if the api was exposed from watchpack inside a plugin hook.

**Comment by bebraw** [comment]
@cmosguy Would it work if you set up a dummy entry pointing at the php files and then processed them through a noop-loader (avoids crash)?

**Comment by sokra** [comment]
There are other tools to watch files and run a command on change. You don't have use webpack for this.

It's like you want "webpack" without the "web" part and without the "pack" part + the ability to run custom commands. There is nothing left from webpack that you need.

**Comment by cmosguy** [comment]
Hey @sokra,

Thanks for the feedback.  Unfortunately, I have not found any good watch tools that did not look at all directories for a change then run phpunit command upon a change.  In fact, I like having a watch command for my php files and the html/css files in parallel with a single tool.  If webpack can do it, I am assuming that it could do it for other use cases as part of the build chain.

Previously, I was using gulp to do this, which I can do, but I was hoping to scrap gulp altogether and stick with just a webpack-all-in-one solution.  I know you closed this issue, but if there are any recommended snippets or ideas where I could leverage the watchers for my TDD test running tasks it would be super awesome.  Thanks for you time.

Cheers!
Adam

**Comment by cmosguy** [comment]
@bebraw I am totally new to webpack, so I am googling `noop-loader` and trying to figure out how to build an entry point to this.  All I want to do is leverage the watch mechanism in webpack, see a change in files with extension `*.php` then if so execute phpunit in the command shell.

**Comment by ChrisAndrew** [comment]
@cmosguy Woking "TDD" solution (not a elegant one) for Laravel 5.4 using Webpack and Mix:

```
//webpack.mix.js

const { mix } = require('laravel-mix');

mix.js('resources/assets/js/app.js', 'public/js')
   .sass('resources/assets/sass/app.scss', 'public/css');

mix.webpackConfig({
    plugins: [
        new mix.plugins.BrowserSyncPlugin(Object.assign({
            host: 'localhost',
            port: 3000,
            proxy: 'app.dev',
            files: [{
                match: [
                    'app/**/*.php',
                    'resources/views/**/*.php',
                    'public/mix-manifest.json',
                    'public/css/**/*.css',
                    'public/js/**/*.js'
                ],
                fn: function(event, file) {
                    if (event === 'change') {
                        var bs = require("browser-sync").get('bs-webpack-plugin');
                        bs.reload();
                        if (process.env.NODE_ENV === 'testing') {
                            const exec = require('child_process').exec;
                            exec('php vendor/bin/phpunit', (error, stdout, stderr) => {
                                if (error) {
                                    console.error(`exec error: ${error}`);
                                    return;
                                }
                                console.log(`${stdout}`);
                                console.log(`${stderr}`);
                            })
                        }
                    }
                }
            }]
        }, {name: "bs-webpack-plugin"}))
    ]
});
```

**Comment by kharysharpe** [comment]
+1 Please bring back tdd, especially using Laravel Dusk.

**Comment by magusd** [comment]
https://github.com/spatie/phpunit-watcher
