### ISSUE TITLE
Another request for `require.context(./somedir)`

### ISSUE THREAD

**Issue by rdrey** [webpack/webpack#38]
Hi @sokra 

With a components directory that looks like this:

```
A.js
B.js
B.web.js
C.js
```

And my ComponentLoader that requires it like this:

```
var ComponentLoader = {
  get: function(name) {
    return require('../components/' + name);
  },
  available: function() {
    var components = require.context('../components').keys();

    return components.map(function(fileName) {
      return fileName.replace('./', '').replace('.js', '');
    });
  }
};
```

It would be super cool if the context included only 

```
A.js
B.web.js
C.js
```

in the browser, and

```
A.js
B.js
C.js
```

in node.

Currently the context includes all files in the browser and node. (And webpack throws a little error, because `B.js` includes `net`.)

**Comment by FezVrasta** [comment]
@sokra sorry if I'm writing in a so old issue but I'm facing issues with the proposed syntax of the post above.

I thought I could be able to do `require.context('.../.../app', name => ['app.js', 'reducers.js', 'routes.js', 'store.js'].indexOf(name) !== -1)` to exclude the files listed in the array, but it doesn't seem to work at all.

Am I missing something or this feature has been removed?

**Comment by sontek** [comment]
I'm with @FezVrasta, is this not supported anymore?
