### ISSUE TITLE
Question: Compile only the changed bundles

### ISSUE THREAD

**Issue by lmartins** [webpack/webpack#380]
Im using gulp to build my projects, my typical gulpfile looks like this:

```
// WEBPACK --------------------------------------------------------------------
gulp.task('webpack', function(callback) {
  webpackCompiler.run(function(err, stats) {
    if (err) {
      throw new plugins.util.PluginError('webpack', err);
    }
    plugins.util.log('webpack', stats.toString({
      colors: true,
    }));
    callback();
  });
});

var webpackConfig = {
  cache: true,
  debug: true,
  progress: true,
  colors: true,
  devtool: 'source-map',
  entry: {
    main: './src/js/app.js',
    vendor: ['angular', 'angular-resource', 'angular-route', 'angular-sanitize',  'locale']
  },
  output: {
    path: config.JS.build ,
    filename: '[name].bundle.js',
    chunkFilename: '[id].chunk.js',
    publicPath: '/app/js/',
  },
  module:{
    loaders: [
      { test: /\.html$/, loader: "html" },
      { test: /\.css$/, loader: "css" }
    ]
  },
  resolve: {
    modulesDirectories: ['node_modules', 'bower_components'],
    alias: {
      'firebase'     : 'firebase/firebase.js',
      'angular-fire' : 'angularfire/angularfire.js',
      'locale'       : 'ngLocale/angular-locale_pt-pt.js'
    }
  },
  externals: {
    // require("jquery") is external and available
    //  on the global var jQuery
    // "angular": "angular",
    "jquery": "jQuery"
  }

};

gulp.task('set-env-dev', function() {
  webpackConfig.plugins = [
    new webpack.optimize.CommonsChunkPlugin(/* chunkName= */"vendor", /* filename= */"vendor.bundle.js"),
    new webpack.BannerPlugin(info.name + '\n' + info.version + ':' + Date.now() + ' [development build]'),
    new ComponentPlugin(),
    new webpack.ResolverPlugin(
      new webpack.ResolverPlugin.DirectoryDescriptionFilePlugin("bower.json", ["main"])
    )
  ];
  webpackCompiler = webpack( webpackConfig );
});

gulp.task('set-env-prod', function() {
  webpackConfig.debug = false;
  webpackConfig.devtool = "";
  webpackConfig.plugins = [
    new webpack.optimize.CommonsChunkPlugin(/* chunkName= */"vendor", /* filename= */"vendor.bundle.js"),
    new ngminPlugin(),
    new webpack.optimize.UglifyJsPlugin({
      mangle: false
    }),
    new ComponentPlugin(),
    new webpack.ResolverPlugin(
      new webpack.ResolverPlugin.DirectoryDescriptionFilePlugin("bower.json", ["main"])
    )
  ];
  webpackCompiler = webpack( webpackConfig );
});
```

Is there a way to avoid the compilation of the vendor bundle when changes happen only on project code?

The vendor stuff tends to be heavy, so it slows the process down unnecessarily.

**Comment by Synturas** [comment]
I have the exact same issue with this configuration:

**var webpack = require('webpack');
var path = require('path');
var glob = require('glob');
var css_loader = require('postcss-loader');
var autoprefixer = require('autoprefixer');
var comments = require("postcss-discard-comments");
var WebpackMd5Hash = require('webpack-md5-hash');
var ExtractTextPlugin = require('extract-text-webpack-plugin');

module.exports = {
  entry: {
    app: glob.sync('./src/main/webapp/modules/**/*.js'),
    vendor: [
      'angular',
      'lodash',
      'angular-ui-router',
      'angular-ui-router-styles/ui-router-styles',
      'angular-material-data-table',
      'angular-aria',
      'angular-animate',
      'angular-material',
      'angular-resource'
    ]
  },
  output: {
    filename: 'app.bundle.min.js'
  },
  plugins: [
    new webpack.optimize.CommonsChunkPlugin(/* chunkName= */'[chunkhash].[id].vendor'),
    new WebpackMd5Hash()
    //new ExtractTextPlugin(path.join('../', 'css', 'styles.min.css'))
  ]
  /*module: {
    loaders: [
      {
        test: /\.scss$/,
        loader: ExtractTextPlugin.extract('style', ['css', 'sass', 'postcss-loader'])
      },
      {
        test: /\.css/,
        loader: ExtractTextPlugin.extract('style', ['css', 'postcss-loader'])
      },
      /!*{
       test: /\.(png|woff|woff2|eot|ttf|svg)$/,
       loader: ExtractTextPlugin.extract('url-loader?limit=100000')
       },*!/
      {
        test: /\.jpe?g$|\.gif$|\.png$|\.svg$|\.woff$|\.woff2$|\.eot$|\.ttf$|\.wav$|\.mp3$/,
        loader: require.resolve('file-loader') + '?name=../[path][name].[ext]'
      }

    ]
  },
  postcss: [

    comments({
      removeAll: true
    })
  ]*/
};**
