### ISSUE TITLE
webpackJsonp is not defined with webpack2 and split-by-path plugin

### ISSUE THREAD

**Issue by TitanNano** [webpack/webpack#3804]
We are using webpack2 and the [split-by-path-webpack-plugin](https://github.com/fabiandev/split-by-path-webpack-plugin). We had to patch the plugin in order to use it with webpack2, but after building the bundle, it seems that there is still something wrong.
This is our configuration:
```JavaScript
module.exports = {
    context: APP,
    target: 'web',
    entry: {
        bundle: './.caches/jsClient/Admin/App.js',
    },
    output: {
        path: path.join(__dirname, 'dist'),
        filename: "[name]_[chunkhash].js",
        chunkFilename: "[name]_[chunkhash].js",
        publicPath: '../dist/',
    },

    devtool: 'source-map',
    resolve: {
        extensions: ['.webpack.js', '.web.js', '.ts', '.js'],
    },
    performance: {
        hints: false,
    },

    module: {
        rules: [
//            { test: /(?!\.min)\.js$/, enforce: 'pre', loader: "source-map-loader" }
            { test: /\.css$/, loader: "style-loader!css-loader" },
            {
                test: /\.html$/, // Only .html files
                loader: 'html-loader' // Run html loader
            },
            { test: /.(png|woff(2)?|eot|ttf|svg)(\?[a-z0-9=\.]+)?$/, loader: 'file-loader?name=[name].[ext]' },
        ]
    },
    plugins: [
        new Md5Hash(),
        new AssetsPlugin({update: true}),
        new ChunkManifestPlugin({
            filename: "chunk-manifest.json",
            manifestVariable: "webpackManifest"
        }),
        new SplitByPathPlugin({
            buckets: [{
                name: 'vendor',
                regex: /node_modules/,
            }]
        }),
        new WebpackCleanupPlugin({
            quiet: true,
            exclude: ["chunk-manifest.json", "Fonts/**/*"]
        })
    ]
};
```
Both bundle and vendor files are created and we load the bundle file first, but they don't get executed as intended. 
```
TypeError: modules[moduleId] is undefined (bundle.js)
ReferenceError: webpackJsonp is not defined (vendor.js)
```
When I look at our resulting bundle, I'm unable to find any definition of the jsonp function. Does the split-by-path plugin need to do anything so the method gets defined?
This current behavior is quite confusing from a users standpoint.

**Comment by ev1stensberg** [comment]
Do you have a reproduction of your repo?

**Comment by sokra** [comment]
Better file this issue on the plugins repo.

**Comment by TitanNano** [comment]
@sokra but can you give us any hint why webpack is not adding the jsonp function to the first chunk?

**Comment by sokra** [comment]
splitted chunks need to be children of the entry chunk.

**Comment by TitanNano** [comment]
@sokra we now set the new chunks as children of the entry chunk, but for some reason the entry chunk doesn't wait for the child chunk to get loaded. The entry module is executed synchronously and the bootstrapping fails when the first required module isn't available. The bootstrapping doesn't wait for the `jsonpFunction` to be called first.

**Comment by TitanNano** [comment]
okay, I figured it out!

**Comment by yabasha** [comment]
How did you solve jsonpFunction?

**Comment by TitanNano** [comment]
@yabasha sorry for that. have a look at this:
https://github.com/fabiandev/split-by-path-webpack-plugin/pull/1/files
you have to update the entry points
