### ISSUE TITLE
Feature request: modular "process" module

### ISSUE THREAD

**Issue by nolanlawson** [webpack/webpack#3819]
Currently if you use Webpack to build the following code:

```js
if (process.env.NODE_ENV === 'production') {
  console.log('production!')
}
```

or

```js
if (process.browser) {
  console.log('browser!')
}
```

Then by default it will include all of [node-process](https://github.com/defunctzombie/node-process) which is  803 bytes min+gz (2.5KB bytes min), most of which contains a `nextTick` polyfill designed to work around old IE bugs and frameworks that modify the global `setTimeout` function.

Note that Browserify does this too, as does Rollup if you use [rollup-plugin-node-globals](https://github.com/calvinmetcalf/rollup-plugin-node-globals). So this isn't strictly a Webpack issue.

Since for compatibility reasons I don't see `process.env` or `process.browser` going away anytime soon, it would be really nice if module bundlers like Webpack could be aware of which *method* on `process` the user is calling, and only include that. For instance, an explicit `process.nextTick` call would include the `nextTick` polyfill, but a call to `process.browser` would not. This would have the additional benefit that APIs like `process.hrtime()` could be reasonably polyfilled (e.g. using `performance.now()`) without impacting other uses of `process` (currently `process.hrtime()` is unsupported).

I'd also like to see `process.browser` automatically resolve to `true` and `process.env.FOO` automatically pull `FOO` from the environment variables, but that may be a lot to ask and may step on the toes of various plugins that already do that. :smiley:

**Comment by nolanlawson** [comment]
BTW this might technically be a feature request on [node-process](https://github.com/defunctzombie/node-process) since it will require coordination with that project (and maybe coordination with Browserify/Rollup too...). /cc @calvinmetcalf

**Comment by nolanlawson** [comment]
Hm so I guess a good first step would be to refactor node-process to have:
- index.js for cjs consumers (classic)
- index.es.js for ES6 consumers (Rollup, Webpack 2)
- nextTick.js, browser.js, env.js etc. for modular CJS consumers (e.g. `require('process/nextTick')`

Then once it's *possible* to consume `process` modularly, Webpack can move on to solving the parsing/dependency graph problem.

**Comment by calvinmetcalf** [comment]
I'm not sure I agree, the es6 and cjs ones would end up filling some slightly different niches so we probably don't need to merge them, just use the es6 one when you need es6 and the classic when you need classic.

probably the better next step is a focus on *inlining* of process.browser and envs as those are static values, once that low hanging fruit is done we can figure out if we need modularity beyond es6 named imports and tree shaking.

**Comment by nolanlawson** [comment]
Fair enough, but I think it would be fairly simple to add a `prepublish` to `node-process` to simply Rollup the ES6 source into separate CJS packages. But yeah it's purely a code organization thing and as-is it's perfectly usable in either ES6 or CJS.

Question for Webpack folks is whether this is sufficient for them, or if they need something else.

**Comment by calvinmetcalf** [comment]
doing the equivalent of inline-process-browser and envify are probably like 99% of all real world code gains that we are likely to make so I'd really suggest focusing on those 2 special cases first

**Comment by calvinmetcalf** [comment]
@nolanlawson I pinged you on the pouchdb slack if you want to try to get on the same page
