### ISSUE TITLE
Warning "There is another module with a equal name when case is ignored."

### ISSUE THREAD

**Issue by byelims** [webpack/webpack#382]
Today when I build my project, webpack warns me a lot like this:

> WARNING in ./~/fluxxor/~/lodash-node/modern/internals/baseCreate.js
> There is another module with a equal name when case is ignored.
> This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
> Rename module if multiple modules are expected or use equal casing if one module is expected.
> 
> WARNING in ./~/Fluxxor/~/lodash-node/modern/internals/baseCreate.js
> There is another module with a equal name when case is ignored.
> This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
> Rename module if multiple modules are expected or use equal casing if one module is expected.

It was fine yesterday. I don't know what is wrong. There is only `fluxxor` in `node_modules`. I have tried to remove `node_modules` directory completely and then re-install. But it doesn't help.

I'm on OS X 10.9.4. Any ideas?

**Comment by danderu** [comment]
thanks for sharing! I was having the same issue :) :+1:

**Comment by brandonaaskov** [comment]
:+1: thanks for sharing

**Comment by jakoblind** [comment]
Thanks for sharing! Had the same issue!

**Comment by Vall3y** [comment]
+1 :+1:

**Comment by mrblackus** [comment]
:+1:

**Comment by arcseldon** [comment]
(y)  thanks for sharing.

**Comment by gitdarin** [comment]
awesome. thank you!

**Comment by anhhh11** [comment]
:+1:

**Comment by arcarson** [comment]
+1

**Comment by shenlq** [comment]
+1

**Comment by shenlq** [comment]
叼叼叼

**Comment by feit** [comment]
:+1:

**Comment by Pradeep-Kumar-S-M** [comment]
I had the same issue. Thank you.

**Comment by robatron** [comment]
:+1:

**Comment by dazziola** [comment]
+1 Thanks!

**Comment by Axighi** [comment]
+1 Thanks!

**Comment by PeteDuncanson** [comment]
quick search through all my files for each version of the file it reports but in lowercase (it was reporting it in a file as Uppercase found the two references where I'd got the wrong case. Luckily I'm on windows (although some of you will laugh at the lucky part) so its not case sensitive but I wanted the warning message to disappear :)

Example:

Filename is actually: Price.jsx

searched for: price.jsx to find the references it was complaining about.

**Comment by Dhaval8087** [comment]
Thank you so much

**Comment by olegdizus** [comment]
Thanks! That was useful!

**Comment by wb-yangxing** [comment]
nice sharing

**Comment by EmrysMyrddin** [comment]
This warning should be very much explicit for a simple problem like that. It lacks the file where the problem have been found...

**Comment by ghoshabhi** [comment]
Useful info! :+1:

**Comment by fristys** [comment]
Thanks for the help, this fixed my problem...after a lot of searching. This warning message should be a lot smarter and should actually point to the problematic line in question, enough with this guessing wizardry shit...

**Comment by salewan** [comment]
thanks!

**Comment by suyunxue** [comment]
确实是这样的，我用的是import，把后面要引入的模块改为小写就行了

**Comment by courese-jason** [comment]
nice:) thanks
同上，用的是import，把后面引入的模块名改为小写就可以了。

**Comment by deadZedd** [comment]
Is there any way to supress this error? Being aware of the cause and accepting it - is there a way to avoid having these messages? It spits out over 10k characters in my browser / prompts and drowns important information

**Comment by DaWoody** [comment]
Yepp having the same issue with another module, thanks for sharing :)

**Comment by sondreb** [comment]
As others have mentioned, please improve the error message and make it possible to suppress the warning to avoid huge log outputs of file path to every single source file.

**Comment by sudkumar** [comment]
**(y)** Had the same issue. Thanks.

**Comment by ahmad2smile** [comment]
ty!!

**Comment by StokeMasterJack** [comment]
I had this warning also. It took me two hours to find it. I am on a Mac. What I did, was delete the module in question. Empty my trash. Re-create the module from scratch. 

Then I ran flow, which took me straight to the actual error. 

Before this "delete the file and empty the trash" exercise, Flow was not reporting the bug. Only webpack was reporting the error. But webpack's error was not helpful.

So it sounds like some kind of file system issue?

**Comment by xzjcool** [comment]
Thank you +1

**Comment by adamkdean** [comment]
Having this too but no way of knowing where the issue is. No changes but now it starts spitting this out? Perhaps it is some sort of FS issue.

**Comment by zhangolve** [comment]
oh,help me a lot ,thank you.

**Comment by saman** [comment]
Thanks for sharing.

**Comment by chvin** [comment]
Thanks for sharing.

**Comment by littlelake** [comment]
ty!

**Comment by MartinDawson** [comment]
This error also happens when you forget to export anything from the file but try and import it.

**Comment by jjtfsalgado** [comment]
thanks ;)

**Comment by andrewpurcell** [comment]
👍

**Comment by xavibonell** [comment]
thanks, same issue here

**Comment by Yass1408** [comment]
👍

**Comment by pyotruk** [comment]
+1 the same issue

**Comment by 1003865572** [comment]
文件夹名为 fluxxor
进入的 时候 却以 Fluxxor 引入，
var fluxxor = require('Fluxxor');    //should be require('fluxxor')

**Comment by JackDan9** [comment]
problem(Error case): 
WARNING in ./components/common/NoData.jsx
There is another module with an equal name when case is ignored.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Rename module if multiple modules are expected or use equal casing if one module is expected.
Answer:
It is a kind of Warning, Remind us of right writing.
Answer(Right case):
./component/Common/NoData.jsx.

**Comment by chengkj99** [comment]
@byelims just this error, thank  you !

**Comment by vizFlux** [comment]
Thank you so much for sharing.

In my case, I did

```JavaScript
import React from 'React';
```
:(

**Comment by mohitbhatia1994** [comment]
Thanks a lot for sharing.

**Comment by cunjieliu** [comment]
Good! Thanks for sharing!

**Comment by cemarguvanli** [comment]
thanks for sharing!

**Comment by G1anpierre** [comment]
Thanks for sharing! have had the same issue! haha

**Comment by melkishengue** [comment]
(y)

**Comment by melkishengue** [comment]
👍cool, thanks

**Comment by shanghaiese** [comment]
Thanks !!!
