### ISSUE TITLE
Proposal: SpawnPlugin

### ISSUE THREAD

**Issue by shlomiassaf** [webpack/webpack#3822]
A Plugin that allows running spawn before webpack starting the compilation and after it's done.

This will allow a lot of freedom but for me the main reason is to simplify the work with **npm scripts**. Since a lot of tasks do the same thing with minor changes you get a long list of scripts referencing other scripts with a changed flag or arg.

Consider the `UglifyJS`, `Copy` etc... Webpack plugins, they can all run from the cli.
In these cases a plugin is appropriate since CLI is complicated and sometimes you need to change the tree but there are a lot of cases that a plugin isn't really needed just a simple command line hooks will do the job.

It make Webpack more powerful, remove the need for npm script and more approachable to non-webpack devop guys that just need that command before or after

## API
The first release should be simple, we can extend the use cases later.

```
new SpawnPlugin({
  before: [
     'myScript --param1 value --param2 value'
  ],
  after: [
      'myScript --param1 value --param2 value'
  ]
})
```

This is the **default** implementation, the plugin with convert the string into a command and params array and invoke a spawn attached to the console.

```ts
export class SimplePlugin {

  constructor(options: SimplePluginOptions) {
  }

  apply(compiler: any): void {
    compiler.plugin('run', (compiler, next) => this.run(next) );
    compiler.plugin('watch-run', (compiler, next) => this.run(next) );
    compiler.plugin('done', (stats) => this.done(stats) );
  }

  run(next: (err?: Error) => any): void {
    // for each BEFORE script.
    spawn('..'}
      .catch( err => err) )
      .then( err => next(err as any) );
  }

  done(stats: any): void {
      // for each AFTER script.
      spawnSync(`..`);
  }
}
```

This is TS code...

An alternate API will be 2 plugins `SpawnBeforePlugin` & `SpwnAfterPlugin` that accept a single command, the user will add multiple instances to get multiple scripts running.
I think it's better and will save implementation of the async flow since Webpack takes care of that...

`spawn` and `spawnSync` are wrappers around node `spawn/spawnSync` that returns a promise and also parse the string into a command and args.
It also implements `{stdio: "inherit"}` by default so all communication goes to the console.

If this is approved, the next versions can include more control over spawn but supplying an object instead of a string that can change the default behaviour. An object like this is actually a configuration per spawn object... but again after first release and if approved.

**Comment by shlomiassaf** [comment]
I approved i'll post a PR

**Comment by sokra** [comment]
Feel free to publish the plugin as separate plugin.

**Comment by shlomiassaf** [comment]
@sokra Makes sense.

Where can I find the current tags? do you have a link?
