### ISSUE TITLE
how to compress the modules chuck of  require.ensure 

### ISSUE THREAD

**Issue by martinko2009** [webpack/webpack#3824]
I use wepack 1.13.1 and 1.14.0

**Do you want to request a *feature* or report a *bug*?**
I want to report a bug, or there is a solution I won't find out.

**What is the current behavior?**
When I use require.ensure echarts modules,it makes a chunk of that,but this chunk is not compressed.
so this chunk is too big.

![image](https://cloud.githubusercontent.com/assets/3345987/21738035/663e1484-d4ba-11e6-81e9-6ee61e3d3366.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
```
require.ensure([
    "echarts/echarts.js",
    "echarts/chart/pie.js",
    "echarts/chart/radar.js",
    "echarts/chart/line.js"	
],function(){
    require("echarts/echarts.js");
    require("echarts/chart/pie.js");
    require("echarts/chart/radar.js");
    require("echarts/chart/line.js");
},"echartscomponent");
```
**What is the expected behavior?**
I want to compress the chunk made by require.ensure.
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**
Window7, firefox 47, chrome 52, node v4.4.5

**Comment by TheLarkInn** [comment]
Have you tried this in webpack 2 yet?

**Comment by martinko2009** [comment]
I won't try webpack 2 until now.because webpack2 is still beta version.It is not stable version.

**Comment by sokra** [comment]
With `compress` you mean minimize?

Run `webpack -p`

**Comment by martinko2009** [comment]
I have Run webpack -p，but still not compress
