### ISSUE TITLE
Webpack build process - module not found: Error: Cannot resolve module *

### ISSUE THREAD

**Issue by joetidee** [webpack/webpack#3825]
Please see the following S.O. question. I imagine that it is a simple fix, but I have found it difficult to understand what the next step is from the Webpack documentation.

http://stackoverflow.com/questions/41516931/webpack-build-process-module-not-found-error-cannot-resolve-module

**Comment by a-r-d** [comment]
@joetidee take at look at your "resolve" entry. Specifically the "root". I would remove it and use "context" instead.

Here are docs on context: https://webpack.github.io/docs/context.html
Here are docs on resolve: https://webpack.github.io/docs/resolving.html
