### ISSUE TITLE
Comparison to jspm

### ISSUE THREAD

**Issue by OliverJAsh** [webpack/webpack#383]
It would be good to see a comparison to jspm on here: http://webpack.github.io/docs/comparison.html

**Comment by jedwards1211** [comment]
@Dashed you can `npm install` packages straight from GitHub, you know.  I don't think you can install just part of them like with jspm, but that require syntax is never going to become standard anyway

**Comment by Dashed** [comment]
@jedwards1211 Yes I'm fully aware. This hasn't hindered my usage of webpack ever since I've suggested it.

**Comment by bebraw** [comment]
@OliverJAsh Given there's [jspm comparison](https://webpack.github.io/docs/comparison.html) now, it's likely safe to close this.
