### ISSUE TITLE
Documentation and Guides Feedback

### ISSUE THREAD

**Issue by yegnyg** [webpack/webpack#3836]
I'm really happy with the step forward that Webpack has taken in making sure the documentation is easily found and accessible for Webpack 2.

I just wanted to give feedback on my experience with the guides. The react hot reloading guide is phenomenal and just works and explains everything really well. However the code-splitting guides (library code-splitting & css code-splitting) aren't good. I've gone through each of them several times and still cannot get them working. It is extremely frustrating for this to happen and spend so much time trying to get these working and to Webpack and up throwing errors and not work. The guides should just work.

As the rise of PWA it would be awesome if there we're guides for how to get Webpack to generate service worker files and configuration based on everything Webpack knows about our apps by default or through plugins. I'm not sure if any of the plugins are made for Webpack 2. 

The guide for setting up Production vs. Development Webpack builds explain how to do this. However it is really frustrating that the process to do this is so convoluted and overcomplicated. I tried to get this working and it is such a hassle and pain. It makes setting this up for apps such a task that once you get this done you just want to call it a day. Seriously. It would be great if Webpack could follow babels lead and make this simple by defining fields for this and automatically merging them like babel config allows us to do:
```js
{
  ... base setup
  "env": {
    "development": {
        development setup....
    },
    "production": {
       production setup...
    }
  }
}
```
Instead of having to manage 3 separate files and have to manage a build script and Webpack function file to determine how to combine the Webpack setup with a Webpack merge dependency.
It is just frustrating that Webpack doesn't have sane defaults or at least worked on making features that already landed easier to use before adding more features.

For long term caching guide it is absurdly complicated to get working. It is very unwieldy and requires a combination of 3-4 plugins to get working based on the guide. I went through this guide end-to-end 6 times. 6 times. Still could not get it working. 

I'm sorry if I come off as an asshole but i'm not trying to be. A library/build to with the scope of Webpack must be difficult to manage. Webpack is a tool that with a codebase that is inherently complex to manage for maintainers and  authors. However it is the maintainers duty to make sure that the tools complexity doesn't leak to the end user that is utilizing the tool. 
like a react maintainer once said: 
> Reacts code is complex so that your code can be simple.

No one forces me to use Webpack. I want to use Webpack because it is the best at what it does, but every time I use it I get the feeling that i'm burning out 😞 .

**Comment by rafde** [comment]
I think this issue is better suited for https://github.com/webpack/webpack.js.org/issues

**Comment by TheLarkInn** [comment]
@bebraw would you or @pksjce mind moving this over to webpack/webpack.js.org

**Comment by bebraw** [comment]
It's better if @yegnyg does that since it's his/her feedback.

**Comment by TheLarkInn** [comment]
Agreed. @yegnyg Would you mind?

**Comment by bebraw** [comment]
Please split this up into smaller issues and push the doc bits to the doc repo. Thanks.

About the "base setup" idea, you can achieve something like that with user space tools and by exporting a function from configuration (accepts env). There are tons of approaches to choose from to suit your purposes.
