### ISSUE TITLE
Order of execution for multiple entries

### ISSUE THREAD

**Issue by ArunMichaelDsouza** [webpack/webpack#3838]
Hi,

I have a webpack config with multiple entries that generates some js and css files. 
The first entry generates a file that is required by the second entry, since these two processes run in parallel I have no control over the order in which they are executed. 

The second entry ends up running first and exits with an error as it is not able to find the module which the first entry builds (which is required by the second entry).

Is there a way I can run these multiple processes sequentially ? I am using webpack `v1.14.0`

Any help would be appreciated, thanks!

**Comment by TheLarkInn** [comment]
Would you be able to provide a small example of what your config looks like? Thank you.

**Comment by ArunMichaelDsouza** [comment]
Hey @TheLarkInn,

Here's an example config file - 
```javascript
var ExtractTextPlugin = require('extract-text-webpack-plugin'),
    OptimizeCssAssetsPlugin = require('optimize-css-assets-webpack-plugin');

module.exports = [{
    // Sass build process
    entry: {
        website: './public/assets/scss/website.style.scss',
        editor: './public/assets/scss/editor.style.scss'
    },
    output: {
        filename: './main-webpack-bundle.js'
    },
    module: {
        loaders: [{
            test: /\.scss$/,
            loader: ExtractTextPlugin.extract('style', 'css!sass')
        }]
    },
    plugins: [
        new ExtractTextPlugin(
            './public/assets/css/libs/[name].style.css'
        )
    ]
}, {
    // Production build process
    entry: {
        website: ['./public/assets/css/libs/website.style.css',
            './public/assets/css/libs/editor.style.css',
            './public/assets/css/third-party/vendor.css']
    },
    output: {
        filename: './prod-webpack-bundle.js'
    },
    module: {
        loaders: [
            {
                test: /\.woff($|\?)|\.woff2($|\?)|\.ttf($|\?)|\.eot($|\?)|\.svg($|\?)|\.png($|\?)/,
                loader: 'url-loader'
            },
            { test: /\.css$/, loader: ExtractTextPlugin.extract("style-loader", "css-loader?-url") }
        ]
    },
    plugins: [
        new ExtractTextPlugin("./public/assets/css/builds/[name].min.css"),
        new OptimizeCssAssetsPlugin()
    ]
}];
```

The first process converts the `.scss` files and creates two files - `website.style.css` and `editor.style.css`. Now these two files are required by the second process to output the final minified build file `website.min.css`. In this case, the second process starts first and exits with an error as it is not able to find the requried files.

**Comment by krayush** [comment]
@ArunMichaelDsouza Have you been able to resolve this issue?

**Comment by ArunMichaelDsouza** [comment]
@krayush I have been using ``npm scripts`` along with ``webpack cli`` to achieve this.

**Comment by efatsi** [comment]
In case anyone else finds this looking for ways to run multiple configs in sequence, I found a way to get this working in a single build by waiting for the products of one build before starting the other:

```js
const WebpackBeforeBuildPlugin = require('before-build-webpack')
const fs = require('fs')

class WaitPlugin extends WebpackBeforeBuildPlugin {
  constructor(file, interval = 100, timeout = 10000) {
    super(function(stats, callback) {
      let start = Date.now()

      function poll() {
        if (fs.existsSync(file)) {
          callback()
        } else if (Date.now() - start > timeout) {
          throw Error("Maybe it just wasn't meant to be.")
        } else {
          setTimeout(poll, interval)
        }
      }

      poll()
    })
  }
}

const serverConfig = {
  entry: './src/server/index.js',
  plugins: [
    new WaitPlugin('file/the/build/depends/on.js')
  ]
}
```
Can read a full write-up about the solution here - https://www.viget.com/articles/run-multiple-webpack-configs-sequentially/

**Comment by atdiff** [comment]
@TheLarkInn and @sokra is there a workaround for webpack to follow a specific order for multiple entries (other than npm scripts)? Or an enhancement that might still be considered?

**Comment by rjgotten** [comment]
@atdiff 
I'm not entirely sure, but from a quick look at the webpack source code a `MultiCompiler` seems to track dependencies of its constituent child compilers and has some logic which appears to not start them until all their dependencies are fullfilled.

If that's the case, then you should probably be able to cobble together a plugin that, given a multi-compiler configuration `[{ a }, { b }]` turns `a` into a dependency for `b`.

**Comment by djamshed** [comment]
Ran into the same issue, was able to resolve with https://webpack.js.org/configuration/configuration-types/#dependencies
