### ISSUE TITLE
Show `V1` on every page of webpack.github.io

### ISSUE THREAD

**Issue by IanVS** [webpack/webpack#3841]
**Do you want to request a *feature* or report a *bug*?**
Documentation Suggestion

**What is the current behavior?**
When searching Google (or my favorite, DuckDuckGo) for Webpack, many links point to `webpack.github.io`.  However, it can be unclear from looking at those pages that the docs are for V1.  For example, nowhere can a version number be seen on https://webpack.github.io/docs/configuration.html.  A new user might be trying to set up one of the new release candidates for webpack 2, search how to do something, find one of those pages, and not realize that it applies to version 1 and there is a whole other website for V2 docs.

https://github.com/webpack/webpack/pull/3293/files#diff-04c6e90faac2675aa89e2176d2eec7d8R20 helped to clarify on the home page, but that is not visible from every page.  

**What is the expected behavior?**
I suggest adding a `V1` version number under the webpack logo in the top-left, and perhaps a hyperlink for `V2`, so that users can discover the new docs site.

**Comment by TheLarkInn** [comment]
Thanks for submitting your first webpack issue! I think this is a pretty worthwhile idea.

**Comment by Somrlik** [comment]
Possible inspiration from [Python docs](https://docs.python.org/3/) ?

**Comment by bebraw** [comment]
There's a heavy "webpack v1 is deprecated. We encourage all developers to upgrade to webpack 2." note now.
