### ISSUE TITLE
AggressiveSplittingPlugin chunks don't include Webpack runtime

### ISSUE THREAD

**Issue by buu700** [webpack/webpack#3851]
**Do you want to request a *feature* or report a *bug*?**

Report a (probable?) bug.

**What is the current behavior?**

Using the most minimal configuration I could come up with (see config 1 below), the output of this plugin appears to be unusable for a variety of reasons:

1. There's no main.js in the output; instead, the Webpack runtime seems to be arbitrarily added to one of the chunks (in this case, 27.js). Putting a pin in minification for now, grepping for `webpackBootstrap` and moving the chunk that contains it to main.js works around this.

2. Every chunk other than 27.js begins with a call to `webpackJsonp`, a function that does not exist in any of the generated files. If I only include 27.js (renamed to main.js), nothing else is loaded; if I include all of them in script tags after main.js, they each throw `Uncaught ReferenceError: webpackJsonp is not defined`.

3. Adding `new webpack.optimize.CommonsChunkPlugin({name: 'init', minChunks: Infinity})` to the plugin list, an init.js with `webpackJsonp` is generated, which I can move to main.js without the grep hack. However, as before, loading main.js alone does nothing. This time, adding the others in script tags generates a new error: `Uncaught TypeError: Cannot read property 'call' of undefined`. (Is there some particular order the files need to be included in, and if so, where would I find that order?)

4. Even if the JSONP logic were working as intended, for our use case it isn't an option (the reasons are out of scope of this discussion, but it's related to @cyph's in-browser code signing layer). Ideally, our build script could just append an async script tag for each chunk to the html body, and the runtime would sort the rest out.

5. Trying to achieve a similar effect without AggressiveSplittingPlugin, I generated a configuration to split out all our dependencies and large individual modules within our project as commons chunks (see config 2 below). However, this led to more or less the same set of issues mentioned above (same errors; main.js is generated this time, but still has no runtime without the init commons chunk).

**If the current behavior is a bug, please provide the steps to reproduce.**

Config 1:
```
const webpack	= require('webpack');

module.exports	= {
	entry: {
		main: './cyph.com/main'
	},
	output: {
		filename: '[name].js',
		chunkFilename: '[name].js',
		path: '/cyph/shared/js/cyph.com/pack'
	},
	plugins: [
		new webpack.optimize.AggressiveSplittingPlugin({
			minSize: 30000,
			maxSize: 50000
		})
	],
	recordsOutputPath: '/cyph/cyph.com/webpack.json'
};
```

Config 2:
```
const webpack	= require('webpack');

module.exports	= {
	entry: {
		'@angular_common_src_common_module': '@angular/common/src/common_module',
		'@angular_common_src_directives_ng_for': '@angular/common/src/directives/ng_for',
		...
		'zone.js': 'zone.js',
		...
		'._cyph.com_app.module.ngfactory': './cyph.com/app.module.ngfactory',
		'._cyph_thread': './cyph/thread',
		main: './cyph.com/main'
	},
	output: {
		filename: '[name].js',
		chunkFilename: '[name].js',
		path: '/cyph/shared/js/cyph.com/pack'
	},
	plugins: [
		new webpack.optimize.CommonsChunkPlugin({
			name: 'commons__@angular_common_src_common_module',
			chunks: ['main', '@angular_common_src_common_module']
		}),
		new webpack.optimize.CommonsChunkPlugin({
			name: 'commons__@angular_common_src_directives_ng_for',
			chunks: ['main', '@angular_common_src_directives_ng_for']
		}),
		...
		new webpack.optimize.CommonsChunkPlugin({
			name: 'commons__zone.js',
			chunks: ['main', 'zone.js']
		}),
		...
		new webpack.optimize.CommonsChunkPlugin({
			name: 'commons__._cyph.com_app.module.ngfactory',
			chunks: ['main', '._cyph.com_app.module.ngfactory']
		}),
		new webpack.optimize.CommonsChunkPlugin({
			name: 'commons__._cyph_thread',
			chunks: ['main', '._cyph_thread']
		})
	]
};
```

**What is the expected behavior?**

I'm not very experienced in using Webpack, but my expectations were that 1) main.js would be generated with the base runtime included, and 2) every module that requires another module would wait for it to be included rather than immediately throw an error.

Documentation seems fairly sparse on some things and in a state of flux at the moment with the Webpack 2 transition though, so it's possible that I'm just doing this completely wrong.

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**

Webpack: 2.2.0-rc.3
Browser: Chrome 55.0.2883.95
Node.js: 6.9.3
Operating system: Debian Jessie in a Docker container on OS X El Capitan
Programming language: JavaScript/TypeScript

**Comment by sokra** [comment]
> 1) main.js would be generated with the base runtime included

This looks like a bug.

> 2) every module that requires another module would wait for it to be included rather than immediately throw an error

This is planned for webpack 3. Currently scripts need to be in correct order. You need to include all script for an entrypoint. The order is in the stats. There is a `entrypoints` property. You can also show it with `--display-entrypoints`.

**Comment by buu700** [comment]
Thanks a lot for the help! Using the AggressiveSplittingPlugin config with the init.js commons chunk and appending script tags in the order from `stats.compilation.entrypoints.main.chunks` did the trick.

Two related unimportant questions:

1. Is it possible to use the compiler API with the CLI command or otherwise still get the output produced by the CLI when using the Node.js compiler API? (It's nice to have while working in my local env, but not a big deal.)

2. Would there be any benefit to providing some mechanism to give AggressiveSplittingPlugin hints about which files should and shouldn't be chunked together? I know it already sorts before chunking and tries to group files in the same directories together, but one thing I noticed in the records output is that certain modules within my code that aren't expected to change very often (if ever again) are being split and grouped with other parts of the code that change more regularly; intuitively I expect it would improve the caching success if I could say "only group files from module X with other files from module X".

**Comment by glebivanov816** [comment]
Had same problem using webpack2 in one of my projects. Probably, this snippet will be helpful.
https://gist.github.com/glebivanov816/8e33fe93f2780df36f5bd1b364bb7014

**Comment by TheLarkInn** [comment]
> Is it possible to use the compiler API with the CLI command or otherwise still get the output produced by the CLI when using the Node.js compiler API? (Not a big deal, just curious.)

https://github.com/webpack/webpack/blob/839915ccf7373aead6471f8c8bc7eec09aa9dbb5/bin/webpack.js#L316-L387

Our CLI simply leverages the Node API. 😄

Going to close this now! 👍
