### ISSUE TITLE
How are the type files loaded ?

### ISSUE THREAD

**Issue by sreyan32** [webpack/webpack#3854]
I am unable to understand how the type files are loaded for an angular2 application. I have loaded jquery globally by the use of the angular-cli.json file. But then how am I getting intellisense in VSCode without including the typings file anywhere ?

Whats more weird is that if I use jquery plugins like typeahead.js I don't have to include the typings file in the project. (I have to download them of course from DefinetlyTyped) But I am getting intellisense for hat as well.

Whats going on here ? How does angular-cli find the typings for it ?

I am using VSCode as my IDE.

**Comment by sokra** [comment]
Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md).
