### ISSUE TITLE
Proposal: check stats hash before calling handler

### ISSUE THREAD

**Issue by uncleyo** [webpack/webpack#3857]
**Do you want to request a *feature* or report a *bug*?**
potential bug

**What is the current behavior?**
webpack only suppressess stats with identical hash in CLI mode

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
output behavior is the same whether webpack is used through CLI or node API

**If this is a feature request, what is motivation or use case for changing the behavior?**
There is a hash check in CLI code [here](https://github.com/webpack/webpack/blob/054b37f978c2ce752f0ee8900831e266c371f023/bin/webpack.js#L332) and in tests [here](https://github.com/webpack/webpack/blob/054b37f978c2ce752f0ee8900831e266c371f023/test/WatchTestCases.test.js#L115).

Shouldn't this check be performed before calling handler? Am I missing anything?

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**
webpack@2.2.0-rc.3

**Comment by TheLarkInn** [comment]
I'm going to close this as this was from webpack 2rc.  
If this is still an issue in webpack 3@latest, please resubmit a new issue with the information listed in our issue template (version, repro repo, etc.)
