### ISSUE TITLE
Synchronus loading of bundles like RequireJS

### ISSUE THREAD

**Issue by yelodia** [webpack/webpack#3861]
I am trying to migrate my big single page application from Require.js to webpack and there is some troubles with code splitting. My application has structure:
```
    js --|
    |    |-- entry.js
    |    |-- components --|
    |			  |-- component_1.js
    |			  |-- component_2.js
    |			  ... // many components 
    |		          |-- component_n.js
    |    |-- pages --|
    |		     |-- page_1.js
    |		     |-- page_2.js
    |		     ... // many pages
    |		     |-- page_n.js
    |    |-- routers --|
    |		       |-- router.js
```
So I want to create a separate bundle for every page. I'm using bundle-loader in my router.js to do this:
```
require('bundle!pages/' + pageName)(function (result) {
      //... to do something in callback when the page is loaded
});
```
It's OK. Also every page has define section with some components (not all) that it needs. For example: 
```
define([
    'components/component_1',
    'components/component_7',
    'components/component_29'
], function (c1, c2, c3) { 
   // ... to do something with OBJECTS c1, c2, c3.
});
```
Webpack puts code of these components on bundle with page. But there are many pages which use same components and components may be big, so I have duplicated code. ( DedupePlugin don't work with bundle-loader ). Also I don't want to create common big bundle with all components. I want to have isolated components and load each of them synchronously with page.
RequireJS solved this problem. First it loaded every component.js file (if it was not loaded before) and after loaded page.js. Of course, I can use bundle-loader for components in webpack:
```
define([
    'bundle!components/component_1',
    'bundle!components/component_7',
    'bundle!components/component_29'
], function (c1, c2, c3) { 
   // ??? what to do with CALLBACKS c1, c2, c3 ?
});
```
Then components are loading asynchronously with page, i.e. after the page is loaded. And c1, c2, c3 are callbacks, but i need to use them as objects. Or I need to rework my big app totally. It's so hard and long.
I try to write custom loader based on bundle-loader. It's [here](https://github.com/yelodia/bundle-amd-loader). How to use it with callback:
```
require('bundle-amd!pages/' + pageName)(function (result) {
      //... to do something in callback when the page is loaded
});
```
How to use it in define section (with define parameter):
```
define([
    'bundle-amd?define!components/component_1',
    'bundle-amd?define!components/component_7'
], function (c1, c2) { 
   // ... to do something with OBJECTS c1, c2
});
```
My code is bad, because I am not nodejs developer, it's my first experience. But loader works and there are no duplicated code in bundles. I appeal to the experienced developer. Please, if you have the opportunity, create this loader (or plugin) for mass use. I think, I'm not the only one who needs the ability to synchronus loading of bundles. Hope you help me. Thanks!

**Comment by 3axap4eHko** [comment]
did you try to use this approach?
``` javascript
// webpack.conf.js
module.exports = {
    //...
    entry: {
        'index' : './src/app/index.jsx',
        'react-stuff': ['react', 'react-dom', 'react-router', 'react-helpful', 'react-intl'],
        'redux-stuff': ['redux', 'reselect', 'react-redux', 'redux-thunk', 'immutable']
    },
    output: {
        path: '/build',
        filename: '/js/[name].js',
        chunkFilename: '/js/[id].js'
    },
    //...
    plugins: [
       //...
        new optimize.CommonsChunkPlugin('react-stuff', 'js/react-stuff.js'),
        new optimize.CommonsChunkPlugin('redux-stuff', 'js/redux-stuff.js'),
      //...
    ]
};
```
in output folder you will have 1 "stuff" files with grouped modules

**Comment by sokra** [comment]
Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md).

**Comment by yelodia** [comment]
@3axap4eHko Yes, I tried, but it is not what I need. CommonsChunkPlugin groups components, but I need to split each component.

**Comment by rafde** [comment]
This issue is similar to http://stackoverflow.com/questions/38707267/how-to-disable-bundling-in-webpack-for-development
