### ISSUE TITLE
dependency does not move to common chunk

### ISSUE THREAD

**Issue by rasentry** [webpack/webpack#3872]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
class ReusableComponent doesn move to common chunk despite I set 
minChunks: 2,
children: true

**If the current behavior is a bug, please provide the steps to reproduce.**
https://github.com/rasentry/webpack-chunks

**What is the expected behavior?**
It should move to main chunk

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**
Node.js 7.2.1
Windows 10

**Comment by sokra** [comment]
In your example you didn't require ClassC and ClassA doesn't use the component.

**Comment by rasentry** [comment]
ClassC is using in ClassB
```
export class ClassB {
    constructor() {
        console.log('ClassB');
        new ReusableComponent();
        require.ensure([], ()=>{
            const Cls = require('./ClassC'); //here usage of ClassC
            new Cls();
        });
    }
}
```
