### ISSUE TITLE
Webpack 2 dynamic async imports resolve subdirs incorrectly

### ISSUE THREAD

**Issue by Swizec** [webpack/webpack#3873]
**Do you want to request a *feature* or report a *bug*?**
I wish to report a bug.

**What is the current behavior?**

When you run 

```
const dirname = 'MyModule';
System.import(`./subdir/${dirname}`)
```

It resolves the file path to `./MyModule` and says the module cannot be found.

**If the current behavior is a bug, please provide the steps to reproduce.**

Here is a repository that reproduces this behavior. It also shows that the dynamic path resolution does work when subdirs and implicit index.js are not involved.

https://github.com/Swizec/webpack-bug-showcase/blob/dynamic-async-path-bug/src/index.js

**What is the expected behavior?**

Webpack loads `./subdir/MyModule/index.js`

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**

Webpack 2.2.0.rc.3
node 6.9.1
Chrome 55.0.2883.95 (stable)
Babel 6.12

**Comment by jouni-kantola** [comment]
If it's of any help, both these options work:
- `System.import('modules/Change')`
- `System.import('modules/Change/index.js')`

**Comment by Swizec** [comment]
@jouni-kantola thanks. That might work when paired with a very large switch statement.

Would be really great if this worked with a variable. Maybe I'm wrong and it was never meant to?

**Comment by jouni-kantola** [comment]
It's the same with `import()`:
```javascript
const sameModule = await import('./deps/a-module');
sameModule.subModule(); // outputs 'now in sub module'
    
const sameModuleName = 'a-module';
const { subModule } = await import(`./deps/${name}`);  // throws Uncaught (in promise) Error: Cannot find module './'.
subModule();
````

**Comment by Swizec** [comment]
Yes, and it works without the subpath.

```javascript
const sameModule = await import('./a-module');
sameModule.subModule(); // outputs 'now in sub module'
    
const sameModuleName = 'a-module';
const sameModule = await import(`./${name}`);  
sameModule.subModule(); // outputs 'now in sub module'
```

Which leads me to believe it should work with paths more complex than `./` too.

**Comment by Swizec** [comment]
Surely a better fix must exist for this issue than doing something like this:

```javascript

    _loadPage(name) {
        const page = PageComponents[this.currentPage.name];

        let load = {
            HomePage: System.import('../components/HomePage'),
            ErrorPage: System.import('../components/ErrorPage'),
            EssentialKnowledgePage: System.import('../components/EssentialKnowledgePage'),
            SubjectExamPage: System.import('../components/SubjectExamPage'),
            TeachingExamPage: System.import('../components/TeachingExamPage'),
            ContractPage: System.import('../components/ContractPage'),
            BackgroundPage: System.import('../components/BackgroundPage'),
            SchedulePage: System.import('../components/SchedulePage')
        }[page];

        load
              .then(action(module => this.currentPage.component = module.default))
              .catch(err => this.showAlert({message: 'Error loading page component'}));
    }
```

**Comment by jouni-kantola** [comment]
This works:
```javascript
function systemImportLoad(subModule) {
    return System.import('./deps/modules/' + subModule + '/index.js');
}

function importLoad(subModule) {
    return import('./deps/modules/' + subModule + '/index.js');
}

systemImportLoad('sub-folder-module-a').then(module => module.default());
systemImportLoad('sub-folder-module-b').then(module => module.default());

importLoad('sub-folder-module-a').then(module => module.default());
importLoad('sub-folder-module-b').then(module => module.default());

// >
in sub folder module a
in sub folder module a
in sub folder module b
in sub folder module b
```

**Comment by jouni-kantola** [comment]
As a final test I disabled `babel-loader`and created a small config, to try it out as much out-of-the-box as possible. Same results.

Gist with all code:
https://gist.github.com/jouni-kantola/26f211781956e6d2a1aec8054e0415d8

Code:
```javascript
// module-a/index.js
module.exports = function() {
    console.log('in module a');
}

// index.js
function load(subModule) {
    return System.import('./modules/' + subModule);
}

// works
load('module-a/index.js').then(a => {
    console.log('module-a/index.js');
    a();
});

// throws
load('module-a/').then(a => {
    console.log('module-a/');
    a();
});

// throws
load('module-a').then(a => {
    console.log('module-a');
    a();
});
```

**Comment by sokra** [comment]
It's a known bug...

**Comment by Swizec** [comment]
@sokra is there a list of known bugs I could have referenced? I tried searching and it didn't look like anyone else had run into the problem. (my search-fu is probably bad)

**Comment by sokra** [comment]
Here is a list: https://github.com/webpack/webpack/issues?q=is%3Aissue+is%3Aopen+label%3Abug
;)

**Comment by zackify** [comment]
Yep, just ran into this myself :)

**Comment by sokra** [comment]
need to add support for `index` here: https://github.com/webpack/webpack/blob/dcdd9dd7de590c111c95402b5265bb095debf332/lib/dependencies/RequireContextPlugin.js#L42-L73

**Comment by Legends** [comment]
For guys who are working with `ESNEXT` and experience the "**Cannot find module**" issue, when using  **dynamic module loading**,
you have to add `  "moduleResolution": "node"` to your `tsconfig.json`.
