### ISSUE TITLE
Add the option to output the bell character on error when watching

### ISSUE THREAD

**Issue by JannesMeyer** [webpack/webpack#388]
When I'm starting webpack like this

``` bash
webpack --watch
```

it's difficult to see when a compilation error happens after I save a file.

It would be very helpful to have a configuration option to output the [bell character](http://en.wikipedia.org/wiki/Bell_character) everytime an error happens.

``` js
process.stdout.write('\x07');
```

The OSX Terminal.app will automatically show a little notification in the dock when the app is in the background or minimized and you can configure it to play sound, too (I think it's off by default.)

![image](https://cloud.githubusercontent.com/assets/704336/3778719/5562986a-1978-11e4-8772-3995c5c547ef.png)

The behavior depends on your terminal emulator, of course, but iTerm 2 also supports this.

Having this option would help spotting errors much earlier, because I often find myself having the terminal window in the background. Especially when developing on a laptop with only one screen.

**Comment by bebraw** [comment]
@JannesMeyer Any chance you could publish a version of your beep plugin with reasonable defaults?

**Comment by rattrayalex** [comment]
+1 would love this as a package (or built-in option)

**Comment by JannesMeyer** [comment]
@bebraw  @rattrayalex  Sorry for the late reply, but I have finally made a plugin out of this: https://www.npmjs.com/package/system-bell-webpack-plugin

Initially I had given up on it because of the bug that was causing the error handler to be called mulitple times, but that bug was gone when I checked today! So I decided to package it. Let me know if it works for you!

**Comment by scottburch** [comment]
I had also created a plugin for this as well.  https://www.npmjs.com/package/webpack-beep-plugin

**Comment by rattrayalex** [comment]
@JannesMeyer Sorry for the even later reply, but was finally able to install this and it looks great! Working for me, will update you if colleagues find problems. Thanks so much & well done!

**Comment by scottbarrow** [comment]
https://www.npmjs.com/package/webpack-notifier offers similar capabilities, but integrates with OSX notifications

**Comment by No0Vad** [comment]
To those who find this page while searching for a solution on Google, this is what I ended up with for Webpack 5.34.0.

Paste this somewhere in your webpack.config.js file
```
class SystemBellPlugin
{
    pluginName = 'SystemBellPlugin';

    apply(compiler)
    {
        compiler.hooks.done.tap(this.pluginName, (stats) =>
        {
            if (stats.compilation.errors.length > 0)
            {
                process.stdout.write('\x07');
            }
        });
    }
}
```

Then add it to the plugins array of your config.
`plugins: [
    new SystemBellPlugin()
]`
