### ISSUE TITLE
Webpack2 is inserting invisible characters into bundle (visible in chrome devtools)

### ISSUE THREAD

**Issue by akatechis** [webpack/webpack#3893]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
Bundling a bunch of JS into a single file creates a bundle, where the last bundle in the file has some strange characters in its eval source. Best way for me to demonstrate is to show images of the bundle in editor

![image](https://cloud.githubusercontent.com/assets/1058931/21828576/34da023e-d75f-11e6-87d3-3f1352ebc09d.png)

![image](https://cloud.githubusercontent.com/assets/1058931/21828592/4e57acb6-d75f-11e6-8657-3beb232a7d73.png)

The relevant characters are between the semicolon and the bang, on the highlighted line in the devtools screenshot which do not exist in the bundle when I'm opening in a text editor.

I can "work around" this issue if I manually delete the semicolon and bang, and manually type them into the eval string.

**If the current behavior is a bug, please provide the steps to reproduce.**
webpack config @ https://gist.github.com/akatechis/a5e0f99e8a7f828df02ef398c61b0a1f

**What is the expected behavior?**
To not insert the invisible characters

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**
Chrome version 55
Node version 7.3.0
NPM version 4.0.5
Yarn version 0.18.1

Relevant modules from package.json devDependencies:
```
    "css-loader": "^0.26.1",
    "file-loader": "^0.9.0",
    "html-loader": "^0.4.4",
    "html-webpack-plugin": "^2.26.0",
    "less": "^2.7.2",
    "less-loader": "^2.2.3",
    "style-loader": "^0.13.1",
    "webpack": "^2.2.0-rc.3",
    "webpack-bundle-analyzer": "^2.2.1"
```

**Comment by sokra** [comment]
Save the source file as UTF-8 without BOM, instead of UTF-8 with BOM
