### ISSUE TITLE
\node_modules\source-map\source-map.js didn't return a function

### ISSUE THREAD

**Issue by tracker1** [webpack/webpack#3894]
**What is the current behavior?**

After updating my project dependencies (determined via `yarn outdated`), I'm getting the following error when trying to run webpack on my project...  

    ERROR in Loader C:\src\ea-git\ea-portal2\node_modules\source-map\source-map.js didn't return a function
 @ multi app

I'm running on Windows 10, using the latest stable yarn, and the latest LTS node version.

Unfortunately the error itself doesn't tell me which loader is having the issue, or what I can/should do here... help/guidance on finding the underlying issue would be appreciated... will try to create a minimal recreation.

**Comment by sokra** [comment]
Read the migration guide -> `-loader`

**Comment by tracker1** [comment]
@sokra could you be a little more specific?  It was working about a month and a half ago...

[react-redux-materialui-boilerplate](https://github.com/tracker1/react-redux-materialui-boilerplate/)

I'm not seeing any 1.13 to 1.14 migration guide.. let alone a -loader?

**Comment by sokra** [comment]
Oh sorry you deleted the issue template so I didn't know what version you are using.

**Comment by tracker1** [comment]
Okay, I'm a dumbass...  was missing the source-map-loader from the package.json ... probably one of the last things I'd worked on.
