### ISSUE TITLE
[Safari] Unexpected keyword 'const'. Const declarations are not supported in strict mode.

### ISSUE THREAD

**Issue by halt-hammerzeit** [webpack/webpack#3928]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

In Safari 9 it outputs the error

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**

This is the line at which the error is thrown:

```js

const parse  = __WEBPACK_IMPORTED_MODULE_1__custom_es6__["parse"].bind({ metadata: __WEBPACK_IMPORTED_MODULE_0__metadata_min___default.a })
/* harmony export (immutable) */ exports["parse"] = parse;
```

Is it ok for Webpack to use `const` in the output files?
I'm using `["es2015", { modules: false }]`

**Comment by halt-hammerzeit** [comment]
The relevant compiled file (an `npm` dependency package) is:

```js

import metadata from './metadata.min'

import
{
	parse as _parse,
	format as _format,
	is_valid_number as _is_valid_number,
	as_you_type as _as_you_type
}
from './custom.es6'

export const parse  = _parse.bind({ metadata })
export const format = _format.bind({ metadata })

export const is_valid_number = _is_valid_number.bind({ metadata })
export const isValidNumber   = is_valid_number

export const as_you_type = _as_you_type(metadata)
export const asYouType   = as_you_type
```

**Comment by halt-hammerzeit** [comment]
Ok, I get it now: this `index.es6.js` file isn't transpiled with Babel, and so the library author should just add `'use strict'` at the top.
Webpack 2 only handles `import`s, it doesn't do any transpilation.

**Comment by ollejah** [comment]
https://github.com/webpack/webpack-dev-server#caveats
* Version 2.8.0 introduced a change which included ES6 keywords const and let
* Those wishing to support oldIE should stick with version 2.7.1

**Comment by conceptdeluxe** [comment]
Makes sense to rely on something with ES6 syntax when having transpiled to to ES5 before. WTF @webpack 👎
