### ISSUE TITLE
Ability to export only module's default when building a library

### ISSUE THREAD

**Issue by QuentinRoy** [webpack/webpack#3929]
**Do you want to request a *feature* or report a *bug*?**
Feature.

**What is the current behavior?**
Currently, library always exports the module itself when using es2015+ (there is an exception when library is `undefined` for global export, but it does not help much).
For example:

*lib/mylib.js*
```js
export default "foo";
```

*webpack.config.js*
```js
{
    entry: 'lib/mylib',
    output: {
        filename: 'mylib.js',
        library: 'mylib',
        libraryTarget: 'umd'
    }
}
```

When importing  using commonjs a consumer will actually get the js module description (even though it is using commonjs' `require` and not js `import`). Same goes with global. Hence one has to write:
```js
const mylib = require('mylib').default;
console.log(mylib);
```
or
```html
<script src="mylib.js"></script>
<script>
    console.log(mylib.default);
</script>
```

A [workaround](http://stackoverflow.com/questions/33678869/make-webpacks-library-output-compatible-with-babel6/40924882#40924882) since babel 6 is to use a commonJS entry point to bypass the es module. It leverages the fact that commonJS export is handled directly by babel or webpack (only one export value so there is no need for a module object):
 
```js
module.exports = require('./mylib').default;
```
I think this is hacky and not desirable. In my opinion this is a compilation matter and one should not have to write such "adapter", or to rely on commonJS if he/she chose to use js modules for the development of his/her library.

Similar issues have been posted previously (#3560), but no proper solutions have been given (IMHO).

**What is the expected behavior?**

Instead, library developers usually want their consumers to be able to use the library directly with their own module system. A consumer should indeed get an es6 module when he is using js modules:

```js
import mylib from 'mylib';
console.log(mylib);
```

but also being able to write with commonjs:

```js
const mylib = require('mylib');
console.log(mylib);
```

or in the browsers

```html
<script src="mylib.js"></script>
<script>
    console.log(mylib);
</script>
```

or with requirejs

```js
define(['mylib'], function(mylib){
  console.log(mylib);
});
```

The whole idea of course is that these 4 behaviours should not require different builds (this is the whole point of a UMD wrapper).

As a suggestion, this behaviour could be triggered by a new property in output. Maybe something like `output.libraryExport` (`'module'|'default'`). An other way could be to create a new `libraryTarget`, e.g. `'umd-default'`.

It may be desirable that even when specifying default as export, non default values remain available when using js modules (if it is technically possible).

**If this is a feature request, what is motivation or use case for changing the behavior?**

Support the behaviour one usually expects from a good library.
In my humble opinion "naively" wrapping a module does not make much sense for a UMD wrapper. When one is using commonjs, one does not expect to get a js module description object. When one is importing a script in the browser, one is not expecting a js module description object. I think the UMD wrapper should adapt the underlying module so that it can be properly consumed depending on the way the library is used.

I would like to add that the issue is different from commonjs's ability to consume js modules (or ESM if you prefer). This is normal that when *directly* requiring a JS module (e.g. #4082), one has to use `default` (this is how JS works and there is no other way to support both default and named exports). But UMD wrappers are adapters and the point in using an adapter is that... well... it adapts things.

**Comment by andrebautista** [comment]
Running into something similar with `providePlugin`
```
plugins: [
        new webpack.ProvidePlugin({
            $: "jquery",
            siteConfig: path.resolve("./src/js/site_configs/" + partner + "/" + partner + "Core.config.js"),
            siteMatchers: path.resolve("./src/js/site_configs/" + partner + "/" + partner + "Matchers.config.js")
        })
    ]
```

In the files that reference `siteConfig` (es6 module) I now have to use `siteConfig.default` to access methods of that class.

**Comment by kevinokerlund** [comment]
I am currently getting around this issue (in webpack 1, and 2) by using the `babel-plugin-add-module-exports` plugin. Then, in my entry file, all I have to do for example is:
```javascript
export default class Test {
    ...
}
```
Of course, I still have to set the following in my webpack config:
```
library: 'mylib',
libraryTarget: 'umd'
```
But it does allow me to use mylib as expected in any environment without having to reference `default`:
```javascript
let instance = new mylib();
```

**Comment by QuentinRoy** [comment]
@kevinokerlund, the problem with this plugin is that it modifies the behavior of es modules in a non standard way.
Also, because webpack ends up consuming commonjs modules, it cannot perform tree-shaking optimizations anymore (even though tree-shaking is only partially working so far)..

**Comment by nghuuphuoc** [comment]
+1 for this.

**Comment by ericcirone** [comment]
So any other way to fix this? I did see that I can fix it by editing the webpack complied UMD file with where it says factory() to say factory().default.

**Comment by kevinokerlund** [comment]
@QuentinRoy, I found out the following works after searching for another way to do this without the plugin I suggested previously. Instead of using ES6 exports, set the `module.exports` to your module.
```javascript
// replaces export default Foo;
module.exports = Foo;
```

**Comment by QuentinRoy** [comment]
@kevinokerlund, yes the problem is only for es modules, there is no problem with commonjs.
Currently, the best solution I have is to use a commonjs entry point (c.f. above). The rest can be es modules, but the main export must be commonjs. This is a workaround rather than a solution, but it works and I have no better ways.
Another working solution would be to use babel-plugin-add-module-exports (as you suggested), but to apply it only the main entry point. Doing this allows to not touch the source code, but I find the treatment worse than the disease.

**Comment by benwiley4000** [comment]
@sokra Could you explain a bit how commit de8fc51 solves this issue? I had a few questions looking at that code:
1. Do I have to specify a `libraryExport` in my library code?
2. Does `libraryExport: 'default'` still let me import named exports as well?
3. Is `resolve.alias.external: "./non-external"` important also?
4. Is the `webpack.DefinePlugin` instance required by consumers of the library?

I may have totally misunderstood, but it would be great if you could provide some clarification. 😄

**Comment by creeperyang** [comment]
Thanks @sokra @QuentinRoy . `libraryExport` is definitely what I need. And it's nice if we can update docs correspondingly.

However, what about other exports if I use `libraryExport`?

```js
const all = {a: 1, b:2}
export const other = {};
export const a = 10;
export default all;

// is `other` ignored? 
// how to import the same name `a` (10)?
```

**Comment by flyyang** [comment]
I think it's better do this way:

* if  only one exports.default, use the default.
* if mixed exports use the default
* if no exports default, exports all.

**Comment by Flamenco** [comment]
Is seems this issue was solved by the `libraryExport` setting and should be closed.
```js
{
  library: 'mylib',
  libraryExport: "default" ,
  libraryTarget: 'umd'
}
```

**Comment by DirtyWhite** [comment]
It works fine when using 
```
{
  library: 'mylib',
  libraryExport: "default" ,
  libraryTarget: 'umd'
}
```
But when combining with externals option
```
externals: {
        'vue': 'Vue',
        'vue-router': 'VueRouter',
        'vuex': 'Vuex'
    }
```
Vue.default can't exists in  
`<script src="http://m.img4399.com/rds/base/js/vue-2.5.16.min.js"></script>`
Is there any way to deal with it?

**Comment by minhchu** [comment]
This works for me:
```
output: {
    path: path.join(__dirname, "./dist"),
    filename: "notification.js",
    library: "Notification",
    libraryExport: "default",
    libraryTarget: "var"
}
```
