### ISSUE TITLE
[2.2.0-rc.4] utf8 is not a function

### ISSUE THREAD

**Issue by halt-hammerzeit** [webpack/webpack#3930]
This is a bug in Node.js `4.0.0` (during a Travis CI build).
Introduced by @TheLarkInn 
https://github.com/webpack/webpack/commit/7327ee608a040ec784cc251663be85c2aedac44c#diff-7a14ca420cc4fa7cf55f788246117e7cL324
Don't you have a CI test for Node.js `4.0.0`? Or doesn't Webpack support it now?

**Comment by egoroof** [comment]
update to 4.5+ should help and you won't have any breaking changes in nodejs

**Comment by halt-hammerzeit** [comment]
Ah, ok, I see:

```js
  "engines": {
    "node": ">=4.7"
  },
```

Well, ok, Webpack supports `4.7` then

**Comment by TheLarkInn** [comment]
Am open to PRs for node validation if you'd like

**Comment by halt-hammerzeit** [comment]
@TheLarkInn No, if it says `4.7` then `4.7` that is.
"node validation" is not a "PR".
In a sane CI system it's simply adding a string.
You might want to learn about Travis CI:
https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Choosing-Node-versions-to-test-against

**Comment by TheLarkInn** [comment]
We test against those versions. What I am trying to say is having a friendly warning to prevent folks from having to submit an issue without realizing the minimum version of node required to run the library.

**Comment by halt-hammerzeit** [comment]
Oh, I see.
Yeah, maybe something like this could be used:
http://stackoverflow.com/a/41620850/970769
Not willing to do that myself though.
Maybe someone else from Google will try.

**Comment by griffinmichl** [comment]
Thanks for the warning @TheLarkInn. You prevented me from opening an issue =). And maybe helped me convince our ops team to upgrade to 6.9 ;)
