### ISSUE TITLE
Increase or decrease entry causes hash changed

### ISSUE THREAD

**Issue by xwenliang** [webpack/webpack#3931]
I have five entries, part of my webpack.config.js:
```javascript
entry: {
    page1: './src/page1/page1',
    page2: './src/page2/page2',
    page3: './src/page3/page3',
    page4: './src/page4/page4',
    common: [
        './src/vendor/vendor1',
        './src/vendor/vendor2',
        './src/vendor/vendor3',
        'lodash'
    ]
},
output: {
    filename: '[name]_[chunkhash:10].js',
    path: path.join(__dirname, 'build')
},
plugins: [
    new webpack.optimize.CommonsChunkPlugin({
        names: ['common']
    })
]
```
run the project, then i get a manifest from `common` like this:
```javascript
{"0":"4e5ba11a0d","1":"7235172f9f","2":"432fa67e7e","3":"2bb4ca2a89"}[chunkId] + ".js"
```
and i also get five files:
```javascript
page1_4e5ba11a0d.js
page2_432fa67e7e.js
page3_7235172f9f.js
page4_2bb4ca2a89.js
common_f1ff70a57f.js
```
Notice that "0"->page1 "1"->page3 "2"->page2 "3"->page4

part of `page2_432fa67e7e.js`
```javascript
webpackJsonp([2],{
....
}
```
then i delete page1 from entry, and run the project again, like this:
```javascript
entry: {
    page2: './src/page2/page2',
    page3: './src/page3/page3',
    page4: './src/page4/page4',
    common: [
        './src/vendor/vendor1',
        './src/vendor/vendor2',
        './src/vendor/vendor3',
        'lodash'
    ]
```
part of new common:
```javascript
{"0":"8c8b74c88a","1":"af23ae09d9","2":"70fddd2794"}[chunkId] + ".js";
//this is old 
{"0":"4e5ba11a0d","1":"7235172f9f","2":"432fa67e7e","3":"2bb4ca2a89"}[chunkId] + ".js"
```

part of `page2_af23ae09d9.js`
```javascript
webpackJsonp([1],{
...
}
// this is old, and the only difference between them was 1 -> 2
webpackJsonp([2],{
...
}
```

alll the hash of other three files changed, and then i get three different files, but i only removed one entry... should this happen or i mistake something?

`"webpack": "^2.2.0-rc.3",`

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
