### ISSUE TITLE
Code splitting and caching documentation needs improvement

### ISSUE THREAD

**Issue by Kitanotori** [webpack/webpack#3932]
I've been now trying the past few days to figure out "the correct approach" for splitting my app into meaningful minified bundles, and have come to the conclusion that the documentation is either out-of-date or insufficient. I of course understand that development has higher priority than documentation, but I think code splitting is one of the great core features of Webpack, and deserves documentation that enables also ordinary developers to benefit from it. Therefore, I would like to share some thoughts on how to improve the documentation.

In order to improve the documentation, I believe that first a basic use case should be defined. Based on my own projects and experience, I propose following basic case:

# Code splitting: the basic case

> A meaningful basic code splitting case is separating an app into two bundles: application bundle containing the internal project code, and vendor bundle containing all the external dependencies. No server-side framework used, and HMR support should be enabled.

Because there are so many different ways of handling styles, I think CSS splitting can be excluded from the basic case. Tutorial that was the most helpful for me was by @okonet [in his blog](https://medium.com/@okonetchnikov/long-term-caching-of-static-assets-with-webpack-1ecb139adb95#.vedtt18pu). Other related tutorials were also found [here](http://moduscreate.com/code-splitting-for-react-router-with-es6-imports/) and [here](https://medium.com/@puppybits/webpack-code-splitting-by-routes-92f96cf733f2#.t91na5fw4). And some relevant documentation:

https://webpack.js.org/plugins/commons-chunk-plugin/
https://webpack.js.org/guides/caching/
https://webpack.js.org/guides/code-splitting-libraries/

## The main issues with the existing documentation and the tutorials:

1. Unclear how to get all external dependencies into the vendor bundle without having to specify them individually (currently needs some hacking - possibly using imported package.json(?) - that is not obvious from the docs).
2. Unclear how to handle script tags for the generated bundles with the changing hashes in their filenames (has naturally a lot to do with the particular server environment, but nevertheless needs more clarification; in the basic case, should be assumed that there is no server-side framework/templating available)
3. Unclear how to make code splitting play nicely with HMR (what needs to be taken into account, effect on various plugins related to code splitting, etc.)

Particularly I'm curious on 2., as I can't seem to think of a way on how to keep the src attribute of the scripts up-to-date with the filenames of the generated cache-friendly bundles, while having HMR working. How have people solved this without using server-side tricks? Or, how to solve this using server-side tricks but still have HMR working?

I'm using React and the latest version of Webpack. When I have time and more clear understanding of code splitting, I'm planning to update [this example project](https://github.com/Kitanotori/react-webpack-babel-hotreload-example) with code splitting.

**Comment by bebraw** [comment]
Could you re-open at the [docs repo](https://github.com/webpack/webpack.js.org/issues)? Thanks.

**Comment by r01010010** [comment]
This is totally required, i'm having lot of trouble trying to make code splitting with script-loader

**Comment by Kitanotori** [comment]
I should mention that I have since got everything working. Maybe I should contribute to the documentation..
