### ISSUE TITLE
rules.use.options doesn't support functions

### ISSUE THREAD

**Issue by michael-ciniawsky** [webpack/webpack#3936]
webpack@2.2.0-rc.4

**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

**webpack.config.js**
```js
{
          loader: 'postcss-loader',
          options: {
            parser: () => 'sugarss', // functions => undefined
            plugins: [ require('postcss-import')() ] // requires => null
          }
}
```

**postcss-loader/index.js**

console.log( utils.parseQuery( this.query ) )

  => `{} || { key: null }`

**If the current behavior is a bug, please provide the steps to reproduce.**

**webpack.config.js**
```js
{
          loader: 'postcss-loader',
          options: {
            parser: () => 'sugarss', // functions => undefined
            plugins: [ require('postcss-import')() ] // requires => null
          }
}
```

  => `{} || {/* missing parser: '' */, plugins: [null] }`

`cd node_modules/postcss-loader`
`editor index.js`
`console.log(loader.query)` (L49)

**What is the expected behavior?**

Functions inside `rules.use[index].options` are recognised and requires are loaded.

**Comment by TheLarkInn** [comment]
@michael-ciniawsky Would you be able to make a repo which reproduces this so we can test against?

**Comment by michael-ciniawsky** [comment]
@TheLarkInn Yep of course 😛

**Comment by sokra** [comment]
see https://webpack.js.org/guides/migrating/#complex-options

**Comment by michael-ciniawsky** [comment]
@sokra thx, `{ ident: 'postcss' }` works, but why is that identifier needed ? Would it be changeable without to much effort :) ?
