### ISSUE TITLE
Buffer.from in source map plugin doesn't work in node4

### ISSUE THREAD

**Issue by TrySound** [webpack/webpack#3944]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**
```
.../node_modules/webpack/lib/SourceMapDevToolPlugin.js:158
Buffer.from(JSON.stringify(sourceMap)).toString("base64");
 TypeError: this is not a typed array
```

this breaks my deploy

**If the current behavior is a bug, please provide the steps to reproduce.**

`devtool: '#inline-source-map'` in node4?

**If this is a feature request, what is motivation or use case for changing the behavior?**

In this commit `Buffer.from` is used, but it was introduced in node6
https://github.com/webpack/webpack/commit/7327ee608a040ec784cc251663be85c2aedac44c

Maybe create some ponyfill for that?

**Comment by sokra** [comment]
@TheLarkInn Could you fix it?

**Comment by egoroof** [comment]
> it was introduced in node6

but it was backported in 4.5.0 so update Nodejs to 4.5+

**Comment by TheLarkInn** [comment]
Yup can fix

**Comment by TheLarkInn** [comment]
But first is this being reported in node 4.7?

**Comment by TheLarkInn** [comment]
I'm think maybe we should have cli command that asserts on minimum version of webpack.

**Comment by timse** [comment]
I could do that :)

**Comment by sokra** [comment]
Summary from other issue: node 5 is also affected. node 5 is no longer supported.

**Comment by TheLarkInn** [comment]
So more 5 isn't supported but node 4.7, 6 and 7 are?

**Comment by sokra** [comment]
yep: https://github.com/nodejs/LTS#lts-schedule

We should update the `engine` to reflect this.

**Comment by sokra** [comment]
`engine` in package.json now reflects this restriction
