### ISSUE TITLE
Error about module.exports when not using ES import/export

### ISSUE THREAD

**Issue by mikecao** [webpack/webpack#3945]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Getting errors about `module.exports` not being allowed, yet my code does not use any import/export syntax. Here is an example file:

```javascript
const React = require('react');

class UIComponent extends React.Component {
    constructor(props) {
        super(props);
    }
}

module.exports = UIComponent;
```
And this is the error:
```
ERROR in ./src/js/ui/UIComponent.js
18:0-14 module.exports is not allowed in EcmaScript module: This module was detected as EcmaScript module (import or export syntax was used). In such a module using 'module.exports' is not allowed.
```
I am using Babel so the transpiled code looks like this:
```javascript
/***/ (function(module, exports, __webpack_require__) {

"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0_babel_runtime_helpers_classCallCheck__ = __webpack_require__(0);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0_babel_runtime_helpers_classCallCheck___default = __webpack_require__.n(__WEBPACK_IMPORTED_MODULE_0_babel_runtime_helpers_classCallCheck__);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_1_babel_runtime_helpers_possibleConstructorReturn__ = __webpack_require__(3);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_1_babel_runtime_helpers_possibleConstructorReturn___default = __webpack_require__.n(__WEBPACK_IMPORTED_MODULE_1_babel_runtime_helpers_possibleConstructorReturn__);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_2_babel_runtime_helpers_inherits__ = __webpack_require__(2);
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_2_babel_runtime_helpers_inherits___default = __webpack_require__.n(__WEBPACK_IMPORTED_MODULE_2_babel_runtime_helpers_inherits__);



var React = __webpack_require__(4);

var UIComponent = function (_React$Component) {
    __WEBPACK_IMPORTED_MODULE_2_babel_runtime_helpers_inherits___default()(UIComponent, _React$Component);

    function UIComponent(props) {
        __WEBPACK_IMPORTED_MODULE_0_babel_runtime_helpers_classCallCheck___default()(this, UIComponent);

        return __WEBPACK_IMPORTED_MODULE_1_babel_runtime_helpers_possibleConstructorReturn___default()(this, (UIComponent.__proto__ || Object.getPrototypeOf(UIComponent)).call(this, props));
    }

    return UIComponent;
}(React.Component);

module.exports = UIComponent;

/***/ })
```

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Use webpack 2.2.0-rc.4
2. Bundle the above code.

**What is the expected behavior?**

No errors should be emitted if file is not an EcmaScript module.

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**

NodeJS 7.4.0
Win10 x64
webpack 2.2.0-rc.4
target: electron-renderer
libraryTarget: umd

**Comment by sokra** [comment]
Looks like Babel emits ES2015 module imports.

**Comment by TheLarkInn** [comment]
@hzoo can you confirm?

**Comment by TheLarkInn** [comment]
Thank you so much @mikecao for reporting your first webpack issue.

**Comment by sokra** [comment]
related to the babel-runtime transform.

https://babeljs.io/docs/plugins/transform-runtime/

**Comment by hzoo** [comment]
Can you post your babelrc @mikecao? otherwise it's hard to know whats happening just from the output

**Comment by hzoo** [comment]
But if it is transform-runtime, yes they create imports

**Comment by loganfsmyth** [comment]
`transform-runtime` inserts `import` statements, so if you're using `modules: false` on your Babel presets, your output code from Babel will be an ES6 module, meaning you can't use `module.exports`.

Unless we wanted to update `transform-runtime` to be able to output different module formats, this seems like an unavoidable side-effect. Seems like the right fix would be to avoid `module.exports` when using `transform-runtime`.

**Comment by mikecao** [comment]
@hzoo My .babelrc

```
{
  "presets": [
    ["es2015", {"modules":false}],
    "react"
  ],
  "plugins": [
    ["transform-runtime", {"polyfill": false}]
  ]
}
```

**Comment by loganfsmyth** [comment]
@mikecao Are you using ES6 modules in your own code? If so, why are you using `module.exports` for this example? If you aren't, the easiest option would be to remove `{modules: false}`.

**Comment by mikecao** [comment]
@loganfsmyth I'm using a mix of ES6 and CJS modules. Since webpack understands import/export syntax I was trying to save a conversion step. But you're right that removing `{modules:false}` does resolve the issue and webpack is still able bundle both types of modules together.

**Comment by mikecao** [comment]
After converting all CJS modules to ES6, I can use the `{modules:false}` without issue now. Closing.
