### ISSUE TITLE
webpack@2.2.0-rc.4: maxModules option not working

### ISSUE THREAD

**Issue by sanex3339** [webpack/webpack#3946]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

`stats.modules: false` and `stats.maxModules: 0` doesn't work.

**If the current behavior is a bug, please provide the steps to reproduce.**

webpack.config.js
https://github.com/javascript-obfuscator/javascript-obfuscator/blob/master/webpack.config.js

**What is the expected behavior?**

`stats.modules: false` and `stats.maxModules: 0` should hide modules output to console

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**

webpack@2.2.0-rc.4
node@6.0.0

With `stats.maxModules: 0` webpack still display 15 modules in terminal.
![image](https://cloud.githubusercontent.com/assets/9210534/21925939/b4e4abc2-d990-11e6-9766-ff728b548d95.png)

With rc.3 option worked as expected.

**Comment by sokra** [comment]
If you want to hide the modules try `stats.modules: false`. I investigate why maxModules: 0 isn't working.

It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by sanex3339** [comment]
`stats.modules: false` doesn't work

![image](https://cloud.githubusercontent.com/assets/9210534/21935209/bdcb3da0-d9bd-11e6-84bb-4470d0205925.png)

**Comment by jbruni** [comment]
What happens if you set `showChunkModules` to `false`?

**Comment by sanex3339** [comment]
![image](https://cloud.githubusercontent.com/assets/9210534/21957651/52cfbfea-daac-11e6-84f5-efed4b0f880a.png)

**Comment by sanex3339** [comment]
![image](https://cloud.githubusercontent.com/assets/9210534/21957655/79c2e528-daac-11e6-9544-58b77b971c23.png)

**Comment by jbruni** [comment]
Hmmm... none of the stats options from `webpack.config.js` are not arriving [at Stats.js](https://github.com/webpack/webpack/blob/master/lib/Stats.js#L346)...

**Comment by jbruni** [comment]
Oh, yes! This is simply killing the stats options informed at `webpack.config.js`: https://github.com/webpack/webpack/blob/v2.2.0-rc.4/bin/webpack.js#L178-L181

**Comment by sanex3339** [comment]
thank you!

**Comment by saurgoel** [comment]
Facing the same issue on webpack 2.4.1

**Comment by fsarron-nexway** [comment]
Webpack 4.5.0 same issue

**Comment by sokra** [comment]
Please open a new issue
