### ISSUE TITLE
webpack@2.2.0-rc.4: `stats.maxModules: 0` and `stats.modules: false` options are doesn't work

### ISSUE THREAD

**Issue by sanex3339** [webpack/webpack#3949]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

`stats.modules: false` and `stats.maxModules: 0` doesn't work.

**If the current behavior is a bug, please provide the steps to reproduce.**

webpack.config.js
https://github.com/javascript-obfuscator/javascript-obfuscator/blob/dev/webpack.config.js

package.json
https://github.com/javascript-obfuscator/javascript-obfuscator/blob/dev/package.json

**What is the expected behavior?**

`stats.modules: false` and `stats.maxModules: 0` should hide modules output to console

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**

webpack@2.2.0-rc.4
node@6.0.0

With `stats.maxModules: 0` webpack still display 15 modules in terminal.
![image](https://cloud.githubusercontent.com/assets/9210534/21925939/b4e4abc2-d990-11e6-9766-ff728b548d95.png)

![image](https://cloud.githubusercontent.com/assets/9210534/21935209/bdcb3da0-d9bd-11e6-84bb-4470d0205925.png)

With rc.3 options worked as expected.

**Comment by sokra** [comment]
fixed
