### ISSUE TITLE
Copy static assets while keeping directory structure

### ISSUE THREAD

**Issue by markmarijnissen** [webpack/webpack#395]
I have a structure like this:

```
/app1/img1.png
/app1/main.js
/app2/img2.png
/app2/main.js
```

With the `output.file` option I can output the `js` bundle to the correct directory (e.g. `app1`). But how can I output the `img1.png` as `app1/img1.png`?

One option it to use `require('file!name=app/img1.png!./img1.png')`, but then I have to specify the loader manually each time. I'd like to specify this in config, i.e.

`{ test: /([a-z0-9]+)\/([a-z0-9]+\.png)$/,    loader: "url-loader?name=$1/$2 },`

Now the image filename gets hashed and outputted at root.

**Comment by minwe** [comment]
![2015-12-24 4 23 47](https://cloud.githubusercontent.com/assets/4370770/11991919/c073e216-aa5a-11e5-92bf-8bcb23ac59de.png)

@sokra

Hi, I use `file-loader` to images, the images are copied, but can't open by both browser and Mac Find, show `format error` as above.

What's problem? Could you help me? Thanks.

**Comment by minwe** [comment]
@sokra 

Sorry. It seems caused by webpack-stream.
