### ISSUE TITLE
Promise.all creates multiple chunks

### ISSUE THREAD

**Issue by edwardaa** [webpack/webpack#3950]
**What is the current behavior?**

I'm using webpack 2.2.0-rc.4,  following code creates two separate chunks.
```
Promise.all([
  import('./routes/Home'),
  import('./routes/Home/reducers'),
]).then(...)
```
**What is the expected behavior?**

Only create one chunk like what `require.ensure(['./routes/Home', './routes/Home/reducers'])` does.

How to achieve that using `import`?

**Comment by TheLarkInn** [comment]
Best advice would be to create a module which imports them both, and then import that file. That way they can be imported together from one file in one chunk.

**Comment by bebraw** [comment]
Answered, closing.

**Comment by chrisdeely** [comment]
As of 2.4.0 this can also be accomplished by using a "magic comment" in the ```import()```
https://webpack.js.org/guides/code-splitting-async/#chunk-names
https://github.com/webpack/webpack/pull/4573
