### ISSUE TITLE
Towards in-memory hot-reloading server code

### ISSUE THREAD

**Issue by wmertens** [webpack/webpack#3952]
**Do you want to request a *feature* or report a *bug*?**

A *Feature*: I would like webpack to have reliable and fast HMR on the server side including process starting, so you can run a server in dev mode and e.g. iterate on endpoints quickly.

**What is the current behavior?**

I currently use https://github.com/ericclemmons/start-server-webpack-plugin/ for this purpose, with building to file and polling for HMR. Unfortunately, the polling is unreliable, not always detecting an update. Signaling doesn't seem to work at all.

**What is the expected behavior?**

Probably some module under `hot/` that handles running the bundle in another process, including a mechanism to get the built files from the memory fs in the webpack server.

**Comment by sokra** [comment]
This better live in a separate repo.

Best file an issue on the start server webpack plugin to add signaling on update.

**Comment by sokra** [comment]
Closing doesn't mean that I dislike the idea.

a `webpack-dev-runner` project would be great.
