### ISSUE TITLE
Property resolveToContext is present in docs, but missing in webpackOptionsSchema.json. 

### ISSUE THREAD

**Issue by stsiarzhanau** [webpack/webpack#3954]
**Do you want to request a *feature* or report a *bug*?**
bug probably

**What is the current behavior?**
Property `resolveToContext` is present in webpack 2 docs, but missing in webpackOptionsSchema.json. 
When I try to use it I get a WebpackOptionsValidationError: **configuration.resolve has an unknown property 'resolveToContext'**.

**If the current behavior is a bug, please provide the steps to reproduce.**
Just add this prop to resolve key of configuration object and try to bundle some stuff.

**What is the expected behavior?**
If webpack doesn't use this prop, related info should be removed from docs.
Otherwise property should be added to webpackOptionsSchema.json.

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**

webpack v2.0.0-rc.4

**Comment by sokra** [comment]
Should be removed from the doc. Could you file an issue in the docs? Or better submit a PR.
