### ISSUE TITLE
Add runtime switch to name anonymous functions

### ISSUE THREAD

**Issue by aaronfrost** [webpack/webpack#3961]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
This week a friend of mine ( @Timehat ) hacked together something amazing. Something that allowed us to read the Chrome timeline in a way that we had never been able to before. We modified the `FunctionModuleTemplatePlugin` to name the anonymous function to be the full path of the file being included. With this, we were able to use the Chrome Devtools Timeline feature to completely understand what was happening when the app was bootstrapping. We were able to see which pieces of the app took the longest time to init, and we were able to target those pieces first for lazyloading. Naming the anonymous functions corrected the course of action that we were going to take. We can now attack the slowest pieces of code, rather than simply looking at the full gzipped size of each file. The app init time takes around 2.6 seconds. With the aforementioned change, we could absolutely see which pieces were the slowest and were able to lazyload the files that took up 20% of the time with just a few minutes of effort. Now we can spend the next few weeks to lazy load another 20-30% of effort, reducing the total init time by 50%. Without the named anon functions and without Webpack, this would have been something that would have taken us months to figure out. Webpack really knocked this out of the park. 

It would be nice if this feature was in webpack by default, behind a runtime switch that we could set.  We want our build machines to log the times of each of these so that we can add some monitoring around them so that if they ever go off the reservation, we could know about it. I would like to submit this PR, but had a few questions. 

Question was... we were able to easily get the name of the directory that we were in by using `module.context`, but getting the name of the current file was actually kind of tough. The file @timehat and I were working on was [FunctionModuleTemplatePlugin](https://github.com/webpack/webpack/blob/master/lib/FunctionModuleTemplatePlugin.js#L17). Can anyone give some guidance on how to get the full name of the file in there? Or if I am even in a call about a specific file or not?

Second question... is enabling a feature like this behind a command switch something that is likely to get approved/rejected? Please provide guidance on the best way for us to get this feature implemented. And thank you ahead of time for all help. 

**If this is a feature request, what is motivation or use case for changing the behavior?**
The motivation is to give people better insight into what is happening when a webpack-enabled app inits.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by TheLarkInn** [comment]
@timehat @aaronfrost 

What method did you use to make the function names unique. Are you normalizing `module.resource` to a string and making it to be unique?

**Comment by timehat** [comment]
@TheLarkInn I'm currently using `module.userRequest`. Turning it into a string like this: `module.userRequest.replace(/[^a-zA-Z0-9]/g, '_')`. Not doing anything to ensure names are unique. Assumption was that the request includes the module's path, which should be unique.

**Comment by timse** [comment]
any progress on this? sounds very exciting!

**Comment by malcolmredheron** [comment]
This is described as being about helping people understand initialization. I think that it would also help when working with promises. It's common to pass a lambda function to `promise.then` and the result is that stack traces are harder to read and profiling is almost impossible, because even if we replace `.then` on `Promise`, we can't identify each function.

Does anyone have suggestions on how to push this forward?
