### ISSUE TITLE
how could i debug the source code in vscode?

### ISSUE THREAD

**Issue by zzzgit** [webpack/webpack#3962]
how could i debug the source code in vscode?

**Comment by sokra** [comment]
Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md).
