### ISSUE TITLE
The migration guide v1->v2 does not specify the change in BannerPlugin

### ISSUE THREAD

**Issue by doberkofler** [webpack/webpack#3963]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
n.a.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
The migration (https://webpack.js.org/guides/migrating) guide v1->v2 does not specify the change in BannerPlugin and the documentation of the plugin still shows two arguments.
I was also unable to find an example for the new BannerPlugin arguments syntax.

the example:
```
new webpack.BannerPlugin('banner' , {raw: true, entryOnly: true});
```
must be changed to:
```
new webpack.BannerPlugin({banner: 'banner', raw: true, entryOnly: true});
```

**If this is a feature request, what is motivation or use case for changing the behavior?**
might be helpful to others

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
webpack 2.2.0-rc.4

**Comment by sokra** [comment]
Jop, send a PR to the webpack/webpack.js.org repo

**Comment by doberkofler** [comment]
@sokra PR #644

**Comment by sokra** [comment]
Great
