### ISSUE TITLE
resolve.extensions ignored

### ISSUE THREAD

**Issue by hitmands** [webpack/webpack#3966]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
Ignores `resolve.extensions` option

**If the current behavior is a bug, please provide the steps to reproduce.**
```javascript
// webpack.config.js

module.exports = {
  resolve: {
    extensions: ['.js']
  }
}
```

1. Create a dir `Test`
2. Put into `Test` dir these files: `Test.scss` and `Test.js`
3. `import Test from 'Test/Test'; // bundle.js` 

**Output**
```javascript
WARNING in ./Routes/Home/Home.scss
    Module parse failed: Test/Test.scss Unexpected token (1:5)
    You may need an appropriate loader to handle this file type.
    | html {
    |   background: red;
    | }
```
**What is the expected behavior?**
Ignore files with non white-listed extensions

**If this is a feature request, what is motivation or use case for changing the behavior?**
It is a bug

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
- Node: **6**
- WebPack: **2.2.0-rc.4**

**Comment by sokra** [comment]
Could you tell me whats in your `Home/Home.scss` file, and with which loader it's loaded?

**Comment by hitmands** [comment]
I don't want to load that file, 
I manage css outside from webpack.

`import Test from 'Test/Test'` should import `Test.js` and ignore the rest, but, it tries to load both `js` and `scss` and it breaks because there is no `scss loader`.

**Comment by sokra** [comment]
`WARNING in ./Routes/Home/Home.scss`

The warnings origins from `Home/Home.scss`. There is propably a `@import` there.

**Comment by hitmands** [comment]
hi @sokra, there is no import for `Home.scss`... there is just the `import Home from 'Home/Home'` which is without extension and is indendeed for es module but webpack tries to load both js and scss.

**Comment by SpaceK33z** [comment]
@hitmands, I tried to reproduce your example, but it correctly imported `Test/Test.js` for me. If you still have this issue, please create a repository that reproduces your issue.
