### ISSUE TITLE
Cannot find module - Forked GitHub package

### ISSUE THREAD

**Issue by jspizziri** [webpack/webpack#3979]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Installing forked packages results in an error resolving the module

**If the current behavior is a bug, please provide the steps to reproduce.**
Working on an angular2 project, I installed a npm package `angular2-swiper`. There were some changes I desired to make to that package [so I forked it](https://github.com/5-stones/angular2-swiper/tree/init-emitter). I then installed the forked package as standard per npm `"angular2-swiper": "git://github.com/5-stones/angular2-swiper.git#init-emitter"`. The result is that when I build my code I get the following error when I don't when installed via the npmjs.org hosted package.

```
error TS2307: Cannot find module 'angular2-swiper'.
```

**What is the expected behavior?**
The expected behavior is that the package be resolved and run the same way as the npmjs.org package.

**If this is a feature request, what is motivation or use case for changing the behavior?**
N/A

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

- node: v6.7
- OS: macOS Sierra
- webpack: 2.2.0-rc.6

**Comment by SpaceK33z** [comment]
This is not a webpack issue at all. It's because the repository of `angular2-swiper` doesn't include the `dist/` files. They only seem to include that in the npm published version.

**Comment by jspizziri** [comment]
@SpaceK33z, wow... thanks for noticing that, I completely glossed it over!

**Comment by michael-ciniawsky** [comment]
@jspizziri ```npm i 5-stones/angular2-swiper#init-emitter```
