### ISSUE TITLE
ReferenceError: __webpack_exports__ is not defined

### ISSUE THREAD

**Issue by ooade** [webpack/webpack#3980]
### Bug (webpack version 2.2.0-rc.7)

It shows up `Uncaught ReferenceError: __webpack_exports__ is not defined` in the console. This issue persist not only on the specified version but also on 2.2.0-rc.6 and 2.2.0-rc.5.

After starting up devServer as usual, i tried to load my preact app in the browser then that error occurred on those versions specified; rc.4 works fine

- [Webpack config](https://github.com/ooade/PreactSimpleStarter/blob/master/webpack.config.babel.js)
- Node version: 6.3.0
- OS: Ubuntu 16.04 LTS
- Browser: v55

**Comment by sokra** [comment]
Stack trace?

**Comment by sokra** [comment]
This is caused by the LazyParseWebpackPlugin. It's not compatible. But as it's now enabled by default you don't need it anymore.
cc @TheLarkInn

**Comment by ilyaigpetrov** [comment]
Happens to me if I set `devtool: 'eval-source-map'` on webpack 3.0.0.
Environment: chrome web-extension, `env === 'prod'`.
<details>
<summary>webpack.config.js</summary>

```js
'use strict';

const path = require('path');
const BabiliPlugin = require('babili-webpack-plugin');

module.exports = (env, ...flags) => ({
  entry: {
    './debug/':              './src/index.js',
    './debug/injects':        './src/injects/index.js',
    './debug/injects/iframe': './src/injects/iframe/index.js'
  },
  devtool: 'eval-source-map',
  output: {
    path: __dirname,
    //sourceMapFilename: './[name]/index.map',
    filename: '[name]/index.js',
  },
  module: {
    rules: [
      {
        test: /\.jsx?$/,
        include: path.join(__dirname, 'src'),
        use: [{
          loader: 'babel-loader',
          options: { presets: ['react', 'flow'] },
        }],
      }
    ],
  },
  plugins:
    env === 'prod'
      ? [
          /* Production */
          new BabiliPlugin(),
        ]
      : [
          /* Development */
        ],
});
```

</details>
