### ISSUE TITLE
No build file being outputted when using webpack. I am not using webpack dev server, I am creating the build by running a script --> npm run build. Anyone have an idea what might be going on?

### ISSUE THREAD

**Issue by Jzucca** [webpack/webpack#3985]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
![screen shot 2017-01-17 at 12 17 25 am](https://cloud.githubusercontent.com/assets/11687425/22008571/73b7fa5c-dc4a-11e6-9bbb-b397bc9dce70.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
The above screen shot shows that the two js files were successfully "built" but for some reason no Build directory is outputted in my project

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Version: webpack 2.2.0-rc.0
Node Version: v6.9.2

**Comment by bebraw** [comment]
Hi,

Could you please fill in the fields? There's not enough information to help.

**Comment by Jzucca** [comment]
@bebraw I updated it, if there is any further information you need let me know

**Comment by bebraw** [comment]
Looks like it probably emits to your project root. Could you include a link to the project or configuration at least?

**Comment by Jzucca** [comment]
This is a very simple project I made in WebStorm just following a tutorial. This is the entire thing
![screen shot 2017-01-17 at 12 41 23 am](https://cloud.githubusercontent.com/assets/11687425/22008963/b8d233e8-dc4d-11e6-8cb0-84b540d1c559.png)

**Comment by bebraw** [comment]
I would need something to run or configuration to say anything more.

**Comment by Jzucca** [comment]
Ok I will put it online and send you a link

**Comment by sokra** [comment]
`path.resolve(__dirname + 'build')` -> `path.resolve(__dirname, 'build')`

**Comment by Jzucca** [comment]
@sokra @bebraw WOW im an idiot, thank you for your help!
