### ISSUE TITLE
The webpack.js.org/guides/production-build document's example have syntax error. 

### ISSUE THREAD

**Issue by kisnows** [webpack/webpack#3987]
**Do you want to request a *feature* or report a *bug*?**
[The manual way: Configuring webpack for multiple environments](https://webpack.js.org/guides/production-build/#the-manual-way-configuring-webpack-for-multiple-environments) example have syntax error.
This is  what the page show:
**dev.js**
```javascript
module.exports = function (env) {
    devtool: 'cheap-module-source-map',
    output: {
        path: path.join(__dirname, '/../dist/assets'),
        filename: '[name].bundle.js',
        publicPath: publicPath,
        sourceMapFilename: '[name].map'
    },
    devServer: {
        port: 7777,
        host: 'localhost',
        historyApiFallback: true,
        noInfo: false,
        stats: 'minimal',
        publicPath: publicPath
    }
}
```
It should be like this as i think:
**dev.js**
```javascript
module.exports = function (env) {
  return {
    devtool: 'cheap-module-source-map',
    output: {
      path: path.join(__dirname, '/../dist/assets'),
      filename: '[name].bundle.js',
      publicPath: publicPath,
      sourceMapFilename: '[name].map'
    },
    devServer: {
      port: 7777,
      host: 'localhost',
      historyApiFallback: true,
      noInfo: false,
      stats: 'minimal',
      publicPath: publicPath
    }
  }
}
```
Also the **prod.js** is wrong.

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by bebraw** [comment]
Can you re-open at the [docs repo](https://github.com/webpack/webpack.js.org/issues)? PR would be even better. 👍

**Comment by kisnows** [comment]
@bebraw sure.
