### ISSUE TITLE
watch doesn't work since 2.2.0-rc.7

### ISSUE THREAD

**Issue by benneq** [webpack/webpack#3989]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When using webpack --watch --config my.config.js with webpack 2.2.0 rc7 it processes all files, then terminates without an error. It just behaves like running without the --watch option. Last working version was 2.2.0 rc6

**If the current behavior is a bug, please provide the steps to reproduce.**
Here's the complete webpack.config.js : http://pastebin.com/xpZ4eGnA

**What is the expected behavior?**
It's expected to behave just like in version 2.2.0 rc6. This means: Don't terminate, but instead keep watching for file changes.

**If this is a feature request, what is motivation or use case for changing the behavior?**
It's a bug

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Ubuntu 16.10 , Node.js 7.4.0 , webpack 2.2.0 rc7

**Comment by thomasklein** [comment]
+1

**Comment by sokra** [comment]
Could you try again with 2.2.0-rc.8?

**Comment by microdou** [comment]
@benneq
No such problem for me on `rc7` or `rc8`.
You might have reached the Kernel inotify watch limit. Check [this](http://unix.stackexchange.com/questions/13751/kernel-inotify-watch-limit-reached).

**Comment by sokra** [comment]
Great

**Comment by sokra** [comment]
No it was a bug in the RC. We should have it fixed. I just want to have a confirmation from @benneq to close it.

**Comment by jaydenseric** [comment]
Tested on `2.2.0` it works fine again, this can be closed. Here is the issue: https://github.com/webpack/webpack/issues/2664.

**Comment by benneq** [comment]
Tested on rc8 and final. WORKS! :+1:
