### ISSUE TITLE
webpack2 very slow with PhantomJS prebuilt

### ISSUE THREAD

**Issue by CSchulz** [webpack/webpack#3990]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Extremely higher build times, it increased from 9 to 24 minutes.

**If the current behavior is a bug, please provide the steps to reproduce.**
I will attach the configuration soon. Gist is blocked by firewall.

**What is the expected behavior?**
Faster build than with webpack 1.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
npm 3.10.3
weppack 2.2.0-rc.6
Windows 7

**Comment by TheLarkInn** [comment]
Would you mind trying the latest release?

**Comment by CSchulz** [comment]
Tested it, but not faster.
Can I enable a log which contains helpful information to debug this?

**Comment by fxmaxvl** [comment]
got the same problem after migrating to webpack 2

**Comment by CSchulz** [comment]
@TheLarkInn do you have another advice for us?

**Comment by TheLarkInn** [comment]
Hard for me to speculate without a bit more information like config and etc.

**Comment by CSchulz** [comment]
I have created a showcase https://github.com/CSchulz/webpack2-phantomjs-showcase

You need to copy some application and test code

**Comment by timse** [comment]
is this only on phantom or generally for your build with webpack 2?

**Comment by CSchulz** [comment]
As far as I have noticed it is only related to phantomjs.

**Comment by CandySunPlus** [comment]
+1

**Comment by ChrisShen93** [comment]
Does anyone resolve the problem?
