### ISSUE TITLE
Webpack 2 vs Webpack 1 build size bug

### ISSUE THREAD

**Issue by inertum** [webpack/webpack#3994]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
I have webpack 2 and webpack 1 with identical configs (except version specific config)
building with webpack2 and webpack1 produces significantly different build sizes (in favor of webpack1). I cleaned the projects to bare minimum as it wasn't enough to use one library to reproduce this problem

**If the current behavior is a bug, please provide the steps to reproduce.**
[Webpack 1 vs Webpack 2.zip](https://github.com/webpack/webpack/files/713191/Webpack.1.vs.Webpack.2.zip)

unzip
cd webpack1 / cd webpack 2
yarn
npm run build

**What is the expected behavior?**
Initially tried to migrate a small project and use treeshaking/dead code elimination but noticed that webpack 2 build sizes were constantly bigger

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Node: 6.9.1
Webpack versions 1.12.9 and 2.1.0-beta.27
Yarn: 0.18.1
npm: 3.10.8
OS: OSX Sierra 10.12.2

**Comment by bebraw** [comment]
I investigated this. The biggest difference to my eye was that webpack 2 picks more Axios dependencies for some reason. This covers most of the size difference.

**Comment by sokra** [comment]
the webpack 1 build uses `"axios": "^0.9.1"`
the webpack 2 build uses `"axios": "^0.15.3"`
