### ISSUE TITLE
Feature - Better logging for loaders/plugins - compiler.messages

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack#3996]
**Do you want to request a *feature* or report a *bug*?**

Feature.

**What is the current behavior?**

There's no standard for providing loader/plugin diagnostics so people have to use ad hoc solutions.

**What is the expected behavior?**

There should be a pipe like `compiler.warnings` for generic diagnostic messages. Maybe call it `compiler.messages` or so. One option would be to refactor the current API behind a single call that would accept message type, priority, message for filtering.

**If this is a feature request, what is motivation or use case for changing the behavior?**

The current behavior is confusing.

**Comment by evilebottnawi** [comment]
Done, https://webpack.js.org/api/logging/
