### ISSUE TITLE
Webpack2 - can't use module.exports

### ISSUE THREAD

**Issue by vishalvisd** [webpack/webpack#3997]
**What is the current behavior?**
After converting my webpack.config as per webpack 1 -> 2 migration guide, I was able to bundle successfully. But when I open the app on browser, getting this error -

**Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'**

If I change module.exports to export default, it works, but that would mean I have change large number of files. 

Here is my js loader config

 ```
module: {
    rules: [
      {
        test: /.jsx?$/,
        exclude: /node_modules/,
        use: [{
          loader: "babel-loader",
          options: {
            presets: [
              ["es2015", { loose: true, modules: false }],
              ["react"],
              ["stage-0"]
            ],
            plugins: [
              ["transform-object-rest-spread"]
            ]
          }
        }, {
          loader: "if-loader"
        }]
      },...
```

**What is the expected behavior?**
Should run on browser after successful bundle creation.

**Comment by dlindenkreuz** [comment]
Looks like this breaking change was introduced [in v2.2.0-rc.5](https://github.com/webpack/webpack/releases/tag/v2.2.0-rc.5):

> `module.exports` is read-only and undefined

**Comment by jaredlunde** [comment]
As @dlindenkreuz mentioned, as of the breaking change you can only use ES6 exports with ES6 modules. There's no more mixing ES5/ES6 syntax. From the sounds, you WILL have to change a large number of files.

Anyone else running in to this problem and not understanding how to solve it should look at: 
http://www.2ality.com/2014/09/es6-modules-final.html

**Comment by sokra** [comment]
yep.

If you use `import` in a file you must also use `export`.

**Comment by wildeyes** [comment]
Does that mean, project wide, only es6 modules are acceptable, or that within a single file, it's either es5 or es6 syntax?

**Comment by carlos-** [comment]
@wildeyes, it only applies to files: 
* If a file has es6 module `import`, then you cannot use `export` in the same file. You can use `require` in the same file though.
* In the project wide, you can use some files that use `export` and other files with `import`

**Comment by Shuliyey** [comment]
This file has no `import` and only have module.exports

https://github.com/schmich/instascan/blob/master/src/scanner.js

i still get this error, when running the application

```
Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
    at Object.eval (scanner.js?f767:373)
    at eval (326:564)
    at Object.<anonymous> (app.js:2837)
    at __webpack_require__ (app.js:689)
    at fn (app.js:110)
    at eval (index.js?9777:5)
    at Object.<anonymous> (app.js:5115)
    at __webpack_require__ (app.js:689)
    at fn (app.js:110)
    at eval (webpack-internal:///338:2)
```

**Comment by lingo** [comment]
@pkit I had a problem with this that turned up suddenly, and I tracked it to the use of core-js with babel. 

It seems that if I allow babel to include parts of `core-js`, via the `@babel/preset-env` setting of `useBuiltins: usage`, then I get problems in the browser from my other source files (which use `require` and `module.exports`). 

I assume that the babel plugin is adding "import" statements to my code, rather than `require`s.

**Comment by pkit** [comment]
@lingo it seems like the solution posted in babel/babel#6980 indeed works
My case is very similar: I want to share some client functionality between cli client (node js) and a browser client.
