### ISSUE TITLE
Webpack 2 - eval can cause bug with process.env

### ISSUE THREAD

**Issue by kagawagao** [webpack/webpack#4000]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
`webpack` transform `process.env` to a real object like 
```javascript
{
  "NODE_ENV": "development"
}
```
but when a module which use `process.env` in this way

```javascript

process.env.DEBUG = false

```
it will cause a syntax error: `unexpected token : `, ie: [visionmedia/debug](https://github.com/visionmedia/debug/blob/master/src/node.js#L142)
```javascript
function save(namespaces) {
  if (null == namespaces) {
    // If you set a process.env field to null or undefined, it gets cast to the
    // string 'null' or 'undefined'. Just delete instead.
    delete process.env.DEBUG;
  } else {
    process.env.DEBUG = namespaces;
  }
}
```
because `webpack` use `eval` to load this module, and the code above will be transformed to
```javascript
eval("{\"NODE_ENV\": \"development\"}.DEBUG = namespace")
``` 
but in this situation, `{\"NODE_ENV\": \"development\"}` will be a **block**, but not a **Object**, the correct way is
```javascript
eval("({\"NODE_ENV\": \"development\"}).DEBUG = namespace")
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

- `webpack`: `2.1.0-beta.28`
- `Node.js`:  `v7.2.1`
- `OS`:  `macOS Sierra 10.12.2 (16C67)`
- `Chrome Canary`: `57.0.2972.0`

**Comment by kagawagao** [comment]
maybe it can be solved by this way
```javascript
function stringifyObj(obj) {
  return "({" + Object.keys(obj).map((key) => {
    let code = obj[key];
    return JSON.stringify(key) + ":" + toCode(code);
  }).join(",") + "})";
}
```
code can be found in `DefinePlugin.js`

**Comment by sokra** [comment]
As workaround use:

``` js
new DefinePlugin({
  "process.env.NODE_ENV": JSON.stringify("development")
});
```

or 


``` js
new DefinePlugin({
  "process.env": {
    "NODE_ENV": JSON.stringify("development"),
    "DEBUG": "window.envDEBUG"
  }
});
```

**Comment by sokra** [comment]
Do you want to send a PR?

**Comment by kagawagao** [comment]
It's my pleasure
