### ISSUE TITLE
Need to pack one entry as library and second entry not as library

### ISSUE THREAD

**Issue by nkovalenko-sc** [webpack/webpack#4002]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Hello. I need to pack one entry as library and other entry not as library.
```
entry: {
    bundle: './src/client/components/ReactRouter.js',
    'selection': './src/client/components/CertificationSelection/CertificationSelection.js'
  },
  output: {
    path: path.resolve(__dirname, 'build/client'),
    filename: '[name].js',
    chunkFilename: '[id].chunk.js',
    publicPath: '/static/',
    /* I wanna use the following configurations for 'selection' entry only */
    library: '[name]',
    libraryTarget: 'umd',
    umdNamedDefine: true
  }
```
I don't wanna pack 'bundle' entry as a library. Is it possible now?

**Comment by prophe05** [comment]
+ 1
Any ideas?
Why this issue is closed?

**Comment by nkovalenko-sc** [comment]
Webpack allows to export multiple configurations. Instead of exporting one configuration I export array of configurations:
```
module.exports = [
  {
    entry: : './src/...',
    output: {
      path: path.resolve(__dirname, 'build/client'),
      filename: 'bundle.js',
      chunkFilename: '[id].chunk.js',
      publicPath: '/static/'
    },
  },
  {
     entry: {
      'lib': './src/...'
    },
    output: {
      path: path.resolve(__dirname, 'build/client'),
      filename: '[name].js',
      publicPath: '/static/',
      library: '[name]',
      libraryTarget: 'umd',
      umdNamedDefine: true
    },
  }
]
```

**Comment by zhangyanwei** [comment]
I don't think the multiple configurations make sense, is there any other choice?

**Comment by thewasta** [comment]
I want to use `bundle` and `selection` on `window` object.
For example:

`window.LIBRARYNAME.bundle` & `window.LIBRARYNAME.selection`
both on the same `LIBRARYNAME` object. I tried this:

```
entry: {
    'bundle': './src/client/components/ReactRouter.js',
    'selection': './src/client/components/CertificationSelection/CertificationSelection.js'
  },
  output: {
    path: path.resolve(__dirname, 'build/client'),
    filename: '[name].js',
    library: "MYLIBRARY",
    libraryTarget: 'window',
  }
```
If I use both file on the same HTML, the last `script file` override the previous.


For example, if I write on my html this:
```
    <script src="bundle.js"></script>
    <script src="selection.js"></script>
```

My window object is `window.MYLIBRARY.Selection`, and `window.MYLIBRARY.Bundle` doesn't exist. How can I use both? Is possible?
