### ISSUE TITLE
Reduce bundle parse time with JS comments?

### ISSUE THREAD

**Issue by petehunt** [webpack/webpack#403]
I had an interesting conversation with some folks from the Firefox OS team. Their initial evaluation of React seemed to indicate that their device profile simply cannot parse 30kb of JS quickly enough. Gmail was using an interesting trick in 2009 to avoid this: shipping JS down the wire with comments and only removing the comments when the code is actually evaluated: http://googlecode.blogspot.com/2009/09/gmail-for-mobile-html5-series-reducing.html

I'm not 100% convinced that this would be a perf win for every use case, but it would be an interesting thing for webpack to support.

**Comment by SpaceK33z** [comment]
Is this still relevant? And if so, perhaps this should be fixed in an external plugin?

**Comment by jhnns** [comment]
I think, we should leave that optimization to the JS engines. I know from our previous meetings with the v8 parsing team that these kind of optimizations are tricky to get right. And they are already lazy-parsing parts of the code.

I'll close it for now.
