### ISSUE TITLE
Consistently getting "Module not found: Error: Can't resolve [some lodash library]" for velocity-react.

### ISSUE THREAD

**Issue by AlexFrazer** [webpack/webpack#4030]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When I load the velocity-react component, it outputs many errors for the following libraries:

- lodash/object/extend
- lodash/object/omit
- lodash/object/keys
- lodash/lang/isObject
- lodash/lang/isEqual
- lodash/collection/pluck
- lodash/collection/forEach

**If the current behavior is a bug, please provide the steps to reproduce.**
Add this to `module.rules`:
```
{
  test: /\.(js|jsx)$/,
  exclude: /node_modules/,
  use: [
    'babel-loader',
  ],
}
```
Install lodash and velocity-react

Try importing velocity-react in anything built by the config.

**What is the expected behavior?**
Should load it correctly, as I have lodash installed already.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Webpack@2.2.0

**Comment by sokra** [comment]
Not webpack related.

**Comment by ryanwild** [comment]
@AlexFrazer I had the same problem after upgrading to Webpack 2 my `resolve` configuration was incorrect I changed:

```
resolve: {
        modules: [
            path.resolve(__dirname, "node_modules"),
        ],
        extensions: [".js", ".jsx"],
    },
```
to:

```
resolve: {
        modules: [
            "node_modules",
        ],
        extensions: [".js", ".jsx"],
    },
```
And velocity-react was able to compile with Lodash, see this thread for more info: https://github.com/twitter-fabric/velocity-react/pull/134

**Comment by cjromberger** [comment]
Changing the resolve to match what @ryanwild suggested doesn't fix the issue for me.

**Comment by damiangreen** [comment]
Nor me either. We're getting with on our bamboo build server with a React Starter Kit app, and it seems pretty non deterministic. The config is already as ryan described. Here's a full stack trace


```
ModuleNotFoundError: Module not found: Error: Can't resolve './_copyArray' in '/buildPath//src1/node_modules/rc-editor-core/node_modules/lodash'
--
06-Jun-2018 18:07:48 | at factory.create (/buildPath//src1/node_modules/webpack/lib/Compilation.js:511:10)
06-Jun-2018 18:07:48 | at factory (/buildPath//src1/node_modules/webpack/lib/NormalModuleFactory.js:358:22)
06-Jun-2018 18:07:48 | at resolver (/buildPath//src1/node_modules/webpack/lib/NormalModuleFactory.js:118:21)
06-Jun-2018 18:07:48 | at asyncLib.parallel (/buildPath//src1/node_modules/webpack/lib/NormalModuleFactory.js:198:22)
06-Jun-2018 18:07:48 | at /buildPath//src1/node_modules/neo-async/async.js:2772:7
06-Jun-2018 18:07:48 | at /buildPath//src1/node_modules/neo-async/async.js:6730:13
06-Jun-2018 18:07:48 | at normalResolver.resolve (/buildPath//src1/node_modules/webpack/lib/NormalModuleFactory.js:188:25)
06-Jun-2018 18:07:48 | at doResolve (/buildPath//src1/node_modules/enhanced-resolve/lib/Resolver.js:181:12)
06-Jun-2018 18:07:48 | at hook.callAsync (/buildPath//src1/node_modules/enhanced-resolve/lib/Resolver.js:232:5)
06-Jun-2018 18:07:48 | at _fn0 (eval at create (/buildPath//src1/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:15:1)
06-Jun-2018 18:07:48 | at resolver.doResolve (/buildPath//src1/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
06-Jun-2018 18:07:48 | at hook.callAsync (/buildPath//src1/node_modules/enhanced-resolve/lib/Resolver.js:232:5)
06-Jun-2018 18:07:48 | at _fn0 (eval at create (/buildPath//src1/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:15:1)
06-Jun-2018 18:07:48 | at hook.callAsync (/buildPath//src1/node_modules/enhanced-resolve/lib/Resolver.js:232:5)
06-Jun-2018 18:07:48 | at _fn0 (eval at create (/buildPath//src1/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:12:1)
06-Jun-2018 18:07:48 | at resolver.doResolve (/buildPath//src1/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
06-Jun-2018 18:07:49 | error Command failed with exit code 1.
```



--

**Comment by ryanwild** [comment]
I'm not sure how your build server is configured and this does not seem related to Webpack, @damiangreen you seem to have a double slash in your path: `/buildPath//src1/`
