### ISSUE TITLE
Refactor use of forEach to for -- provides 10x performance

### ISSUE THREAD

**Issue by mikeerickson** [webpack/webpack#4031]
**Do you want to request a *feature* or report a *bug*?**

As per @TheLarkInn tweet (https://twitter.com/thelarkinn/status/821879942552154112) it has been brought to attention that there are some rather obvious performance gains (upwards of 10x) when using `for` over `for-of` and `forEach`

**What is the current behavior?**

Currently, `forEach` is being used throughout project. 

**If the current behavior is a bug, please provide the steps to reproduce.**

N/A

**What is the expected behavior?**

Well, I expect it to be as fast and optimized as possible :-)

**If this is a feature request, what is motivation or use case for changing the behavior?**

It is always better when things are faster!

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

As per this sample gist

https://gist.github.com/vsemozhetbyt/7f6db3f73dfec8ac08bcfc81b1b11cbb

Local Results 
```
  // v8 5.1.281.84 (Node.js 6.8.1)

for    : 1.113ms
for-of : 35.201ms
forEach: 24.478ms
```

**Comment by TheLarkInn** [comment]
Thank you very much for this. I'm going to take on webpack/tapable as it has quite a few other facelifts that need done to it.

Anyone interested in taking on a piece should name the file you are tackling and list it here. This will ensure no duplicate PRs.

**Comment by mikeerickson** [comment]
I am going to tackle [enhanced-resolve](https://github.com/mikeerickson/enhanced-resolve)

**Comment by jouni-kantola** [comment]
Perhaps out of interest:
https://jsperf.com/fastest-array-loops-in-javascript

**Comment by vsemozhetbyt** [comment]
FWIW, [a new resumptive benchmark](https://gist.github.com/vsemozhetbyt/396eb4b7713accf60ead2fe164e47306) with some results in the comments there for some v8 / Node.js versions.

**Comment by mikeerickson** [comment]
@vsemozhetbyt  Thanks for reference, this is an updated version of what I was using.

**Comment by TheLarkInn** [comment]
@vecmezoni thank you very much.

**Comment by TheLarkInn** [comment]
@vsemozhetbyt thank you very much

**Comment by wtgtybhertgeghgtwtg** [comment]
I'm not sure this is a great idea.  It can make things hard to read, really quickly.  [For example](https://github.com/webpack/webpack/blob/900fa0b68e1f307ef63ec10b3d35b178616e7b2c/lib/MultiWatching.js#L15), changing
```
this.watchings.forEach((watching) => watching.invalidate());
```
to
```
const watchings = this.watchings;
for (let i = 0, len = watchings.length; i < len; ++i) {
  const watching = watchings[i];
  watching.invalidate();
}
```
is just ugly.  And unless `this.watchings` is really big, it's not going to save you any noticeable amount of time.

**Comment by TheLarkInn** [comment]
Could we function wrap it for readability?

**Comment by wtgtybhertgeghgtwtg** [comment]
Sure.  In fact, if #3690 passes, you could just use `_.forEach`, which uses a loop under the hood ([although it's a while-loop](https://github.com/lodash/lodash/blob/4.17.4/lodash.js#L536-L540)).
But I wouldn't recommend it.  It's duplicating native functionality and adding complexity for performance benefits that may or may not be negligible.

**Comment by markerikson** [comment]
I'd have to say this really ought to be benchmarked before embarking on a mass refactoring.  Yeah, at a micro-level `for` is faster than `forEach`, but are the uses actually a major perf issue?

**Comment by hccampos** [comment]
Agree that we should benchmark it. But taking into consideration how many times some stuff is called (e.g. webpack-sources maps and does forEach over the lines of each file) I would be very very surprised if this didn't make a hefty difference for large projects.

My current angular-cli build takes 1 minute in dev mode. Rebuild is 15 seconds. Granted that most of it is due to bad caching in TS and the TS loader, but still, any extra bit of performance I can get, I will be happy.

**Comment by bebraw** [comment]
Could this type of change be implemented through a codemod?

**Comment by wtgtybhertgeghgtwtg** [comment]
I think this should be discussed as specific instances of `forEach`, not just as a whole.  There are loops that iterate a few times and loops that iterate more than a few times.  Going by the benchmarks in the opening post, the benefit for smaller loops (a few hundred iterations) would have to be measured in microseconds.
