### ISSUE TITLE
Unknown argument:xx  when using webpack 2.x

### ISSUE THREAD

**Issue by kimown** [webpack/webpack#4035]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
webpack1 can pass arguments like this
```
webpack --config webpack.config.js --module=firstmodule
```
but when I upgrade to webpack 2.x , the error occurs, log like this,
```
Unknown argument: module
```

**If the current behavior is a bug, please provide the steps to reproduce.**

[webpackdemo.zip](https://github.com/webpack/webpack/files/715733/webpackdemo.zip)
```
cd webpack2/
npm i
npm run demo
```

**What is the expected behavior?**
when I upgrade to webpack 2.x, I can pass my own arguments from cli.If not, how can I pass my argument? Should I use `env module=firstmodule webpack --config webpack.config.js` instead of `webpack --config webpack.config.js --module=firstmodule`?

**Comment by sokra** [comment]
You can use `webpack --env.module=firstmodule` with

``` js
module.exports = function(env) {
  // use "env.module"
  return /* webpack configuration */;
}
```
