### ISSUE TITLE
webpack UglifyJsPlugin show progress

### ISSUE THREAD

**Issue by fanjunzhi** [webpack/webpack#4037]
webpack UglifyJsPlugin is show '78% additional chunk assets',can is get the progress of uglify? or what the file Is being processed

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
