### ISSUE TITLE
How to bundle a concatenated file with unordered AMD modules?

### ISSUE THREAD

**Issue by techmet** [webpack/webpack#4038]
We have a script file which was generated by concatenating the multiple files from a folder. Webpack is unabled to bundle it since it contains unordered amd modules.

**Src folder structure**
**+-- file1.js
+-- folder1
|   +-- file2.js
|   +-- file3.js**

Modules defined in the files are like below 
**file1.js**

```
define('file1.js',['folder1/file2.js','folder1/file3.js'], function(file2, file3){
// file1 content
});

```
**file2.js**

```
define('folder1/file2.js',[], function(){
// file2 content
});

```
**file3.js**

```
define('folder1/file3.js',[], function(){
// file3 content
});

```
And the concatenated file 

app.combined.js

```
define('file1.js',['folder1/file2.js','folder1/file3.js'], function(file2, file3){
// file1 content
});

define('folder1/file2.js',[], function(){
// file2 content
});

define('folder1/file3.js',[], function(){
// file3 content
});

```

We are using this app.combined.js in another file in a define block

**main.js**
```
define(['./app.combined.js'],function(){
});
```
When we try to bundle main.js, webpack is throwing error saying **unable to find modules 'folder1/file2.js', 'folder1/file3.js'**

Is there any way to bundle app with out modifing the order of concatenated file?

**Comment by sokra** [comment]
No currently not.

Maybe this is an opportunity to update your app to ES Modules...
