### ISSUE TITLE
Webpack optimization is getting rid of @media all

### ISSUE THREAD

**Issue by asotog** [webpack/webpack#4059]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
i'm loading styles via `sassLoader` featherlight sources from `node_modules` like `@import "featherlight/src/featherlight";`

the featherlight styles sources are wrapped as:
```
@media all {
...
}
```

when running webpack server without optimization, styles look fine on IE 10, but when running the optimization via `--p` flag styles are ignored by IE, checked, and seems `@media all {` is transformed into only `@media {`

**If the current behavior is a bug, please provide the steps to reproduce.**
Yes it is a bug. You can follow description above

**What is the expected behavior?**
optimization i think should keep `@media all` 
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
webpack 1.14.0
npm 3.10.9
node 6.9.2

**Comment by sokra** [comment]
The css-loader uses cssnano to minimize the files. You can file an issue there. (test it with pure cssnano first)
