### ISSUE TITLE
Hot Module Replacement not working

### ISSUE THREAD

**Issue by appsforartists** [webpack/webpack#406]
I tried following [this tutorial](http://gaearon.github.io/react-hot-loader/) to get Hot Module Replacement working in my app.  Everything appears to be working in the console, except the update never happens.  For instance, if I change a file, I'll see these logs:

```
    webpack-dev-server: Hot Module Replacement enabled. jsx.js:481
(2) webpack-dev-server: App updated. Recompiling... jsx.js:485
    webpack-dev-server: App hot update... jsx.js:515
```

But never anything like:

```
***** Updated Main.scss ***** jsx.js 
Updated modules: jsx.js
```

[Here's a repo](https://github.com/appsforartists/isomorphic-react-test) demonstrating the issue.  I've tried changing both script files and stylesheets; however, neither triggers a complete update.

How do I get HMR working?

**Comment by ivan-kleshnin** [comment]
Don't want to raise new issue, because it's probably some stupid syntax error, but can't figure it out.

I'm getting 
```
[HMR] Cannot apply update. Need to do a full reload!
dev-server.js:15 [HMR] Error: Aborted because 1 is not accepted
    at hotApply (http://localhost:8080/static/bundle.js:340:31)
    at hotUpdateDownloaded (http://localhost:8080/static/bundle.js:258:13)
    at hotAddUpdateChunk (http://localhost:8080/static/bundle.js:238:13)
    at webpackHotUpdateCallback (http://localhost:8080/static/bundle.js:5:14)
    at http://localhost:8080/static/0.0c93cd978f704d750475.hot-update.js:1:1
```
on simplest case.

---

**./webpack.config.js**
```javascript
module.exports = {
  entry: {
    app: ["webpack/hot/dev-server", "./frontend/app"],
  },
  output: {
    path: "./static",
    publicPath: "/static/",
    filename: "bundle.js",
  },
};
```

**frontend/app.js**
```
console.log("abcdeszz"); // any change reloads page and emits warning
```

Running with:
```
webpack-dev-server --progress --colors --devtool eval --hot --content-base .
```

Access
```
http://localhost:8080/webpack-dev-server/
```

Tried different variations of the above, always getting something like `Error: Aborted because 1 is not accepted` at **app.js** change.

**Comment by liyaodong** [comment]
I have same problem too. I'm using command-line tool start webpack-dev-server:
`$ webpack-dev-server --hot --inline`

Here is my webpack config:
https://gist.github.com/liyaodong/0856d498e88038ebeb2e

When I edited my js, console log:
```
[WDS] App updated. Recompiling...
home.js:646 [WDS] App hot update...
home.js:7961 [HMR] Checking for updates on the server...
home.js:7924 [HMR] Cannot apply update. Need to do a full reload!
home.js:7925 [HMR] Error: Aborted because 76 is not accepted
    at hotApply (http://lh:8080/dist/home.js:356:31)
    at hotUpdateDownloaded (http://lh:8080/dist/home.js:269:13)
    at hotAddUpdateChunk (http://lh:8080/dist/home.js:249:13)
    at webpackHotUpdateCallback (http://lh:8080/dist/home.js:5:12)
    at http://lh:8080/dist/0.1c8a03725401756ddbbb.hot-update.js:1:1
```

`http://lh:8080/dist/0.1c8a03725401756ddbbb.hot-update.js` content:
```javascript
webpackHotUpdate(0,{

/***/ 76:
/***/ function(module, exports, __webpack_require__) {

	'use strict';

	function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { 'default': obj }; }

	var _shareHeader = __webpack_require__(77);

	var _shareHeader2 = _interopRequireDefault(_shareHeader);

	// $(function () {
	//   header();
	//   $('#test').html('09');
	// });

	console.log(2);

/***/ }

})
```
I trigger [this error](https://github.com/webpack/webpack/blob/72e8dd01475841b5123607efd8b3c7b892c1a32a/lib/HotModuleReplacement.runtime.js#L293), but I can't find the reason, I'm using command line by add `--hot --inline`, and no `HotModuleReplacementPlugin` in webpack config. It's a bug ? or my config error ?

**Comment by Download** [comment]
The problem is, there are many different ways to configure this all. So you end up reading tutorials and one tells you to add the `HotModuleReplacementPlugin` and the other tells you to add the `--hot` flag and somehow you end up having both.

I think it's very unexpected behavior. Normally, command line flags override global settings i.s.o. appending to them... especially when doing so actually breaks the setup.

**Comment by Download** [comment]
I made a small edit to the docs. In hindsight, there already was a note in the docs telling you not to add HMR plugin if you use the `--hot` flag, but it's wording was a bit vague and it didn't explicitly warn about breaking the setup. Also I added a small introduction just before the more detailed explanation that views the process from all sides (app view, compiler view, module view etc).

I hope I'm not stepping out of bounds with that, just trying to help. :+1:

**Comment by SrivathsaRaoI** [comment]
I use the following version :
"webpack": "~1.12.14"
 "webpack-hot-middleware": "^2.10.0"
"webpack-dev-middleware": "^1.6.1"

And I use following code in app.js in my react.js project.

        var webpackconfig =require('./webpack.config');
        var webpack = require('webpack');
        var webpackMiddleware = require('webpack-dev-middleware');
        var webpackHotMiddleware = require('webpack-hot-middleware');

        var http = require('http');
        var express = require('express');
        var app = require('express')();
        var isDeveloping = process.env.NODE_ENV != 'production';
        // var isDeveloping = false;
         console.log("IS developing ",isDeveloping);
       var serverConfig = require('./globalconfig.js')

       var serverPort = serverConfig.port

       app.get('/css/bootstrap.min.css', function (req, res) {
       res.sendFile(path.join(__dirname,           'public/lib/bootstrap/css/bootstrap.min.css'));
       });



         // swaggerRouter configuration
         var options = {
	     controllers: './controllers',
	     useStubs: process.env.NODE_ENV === 'development' ? true : false    // Conditionally turn on stubs (mock mode)
         }

         var config = {
	      appRoot: __dirname // required config
          }


	     // Start the server
	     app.listen(serverPort, function () {
		   console.log('Your server is listening * on port %d        (http://localhost:%d)', serverPort, serverPort);
	});
	

         if (isDeveloping) {
	        app.use('/node_modules', express.static('/node_modules'));
	        app.use(express.static('src/web-ui/public/'));
	        app.use(express.static('src/web-ui/public/'));
	        const compiler = webpack(webpackconfig);
	        const middleware = webpackMiddleware(compiler,{
		     publicPath: webpackconfig.output.publicPath,
		    headers: {
			  "Cache-Control" : "public, max-age=604800"
		    },
		   constentBase:'dist',
		   stats:{
			 color:true,
			 hash:false,
			 timings:true,
			  chunks:false,
			 chunkModules:false,
			 modules:false
		   }

	      });
	      app.use(middleware);
	      app.use(webpackHotMiddleware(compiler));
	      app.get('/',function response(req,res){
		                     res.write(middleware.fileSystem.readFileSync(path.join(_dirname,'dist/index.html')));
		   res.end();
	       });
        } else {
  	       app.use('/node_modules', express.static('/node_modules'));
  	       app.use(express.static('dist/public'));
  	       app.use(express.static('dist'));

           app.get('/', function response(req, res,next) {
        	 console.log("Processing req");
		     var entryFile = path.join(__dirname, 'dist', 'index.html');
       	      console.log("Hitting the Root",entryFile);
              res.sendFile(entryFile);
	        });
           }


Same code get hot replaced on other employees computer,but not always,but many times hot replace won't work in my computer.

**Comment by sally2015** [comment]
@Download I can't agree more with you. Just use webpack-dev-server --hot --inline and remove others, e.g
new webpack.HotModuleReplacementPlugin() or devServer: {
	    hotOnly: true,
    	inline: true
}, it is successful

**Comment by nojvek** [comment]
`webpack-dev-server --hot --inline` does not work. Just refreshes the page. I have spent almost 2 hours pulling my hair over this. Incredibly complex to get it right.
