### ISSUE TITLE
The class name HarmonyCompatiblilityDependency should be HarmonyCompatibilityDependency 

### ISSUE THREAD

**Issue by mzgoddard** [webpack/webpack#4060]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
The class name `HarmonyCompatiblilityDependency` is typoed with one extra `l` in it.

**What is the expected behavior?**
`HarmonyCompatiblilityDependency` should be `HarmonyCompatibilityDependency`.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
This is in webpack version 2.2.0.

**Comment by montogeek** [comment]
Can I work on this?

**Comment by TheLarkInn** [comment]
Go ahead!
