### ISSUE TITLE
"devtool" option causes functions to be undefined

### ISSUE THREAD

**Issue by mnpenner** [webpack/webpack#4062]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Adding `devtool: 'cheap-eval-source-map'` or `devtool: 'cheap-module-eval-source-map'` to webpack.config causes functions to not be defined. Possibly other devtool options as well, I didn't test them all.

**If the current behavior is a bug, please provide the steps to reproduce.**

Here's my full [webpack.config.js](https://gist.github.com/mnpenner/e1fb8b3dc1e2cfb93dd6d6ddacfbaf0f)

If I try to compile a module like this:

```
function isFilled(value) {
    return !isEmpty(value);
}

exports.required = function required(value) {
    return isFilled(value) ? OK : 'This field is required.';
};
```

I get an error in Chrome saying `isFilled` is not defined. N.B. that the function is literally defined right above it in the same file, just like that.

If I rewrite it to look like this:

```
const isFilled = function isFilled(value) {
    return !isEmpty(value);
}
```

Then the error goes away. I think webpack is doing something weird with the function -- maybe moving it out of scope?

**What is the expected behavior?**

Functions are defined like normal, without `devtool`.

**If this is a feature request, what is motivation or use case for changing the behavior?**

n/a

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

webpack: 2.2.0
node: v6.9.4
os: ubuntu 16.04

**Comment by sokra** [comment]
Could you take a look at the output for the module?

**Comment by mnpenner** [comment]
@sokra You mean the generated bundle?

I did take a look at the bundle, but I couldn't figure out what the problem was. It's got these big blocks of code like

```
eval("const _ = __webpack_require__(1);\n ... ");
````

Printing that eval string back out so it's legible, it looks pretty much just like my original source code but with the `require` line changed. Everything looks proper.

I did manage to reproduce the issue in a smaller project, [here's the gist](https://gist.github.com/mnpenner/f3b8c3c2deff394099b59d1bc5a24897).

I couldn't attach the generated bundle -- it's too big for Github gists and Pastebin.

**Comment by mnpenner** [comment]
The error happens in Chrome but not Firefox. Something strange going on.

![image](https://cloud.githubusercontent.com/assets/1112998/22572796/a5b99aa2-e95a-11e6-8b0f-779dd551e9ec.png)

You can see in this screenshot that it says,

> ReferenceError: OK is not defined

But on line 3, it clearly is defined.

**Comment by timse** [comment]
so this was purely an issue with chrome not knowing how to handle `const`?
closing then :)

**Comment by mnpenner** [comment]
Fair enough. If someone else comes across this, all they have to do is add `"use strict";`.
