### ISSUE TITLE
Webpack 2.2.0 is still 'beta' in npm.js and 1.14.0 is 'latest'

### ISSUE THREAD

**Issue by ArturDorochowicz** [webpack/webpack#4063]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

Webpack 1.14.0 is listed as _latest_ in npm.js, Webpack 2.2.0 is listed as _beta_. 

**If the current behavior is a bug, please provide the steps to reproduce.**

Run `npm install webpack` or equivalent `npm install webpack@latest`. This installs 1.14.0.

Alternatively, inspect `npm info webpack`. It returns:
``` 
{ name: 'webpack',
  description: 'Packs CommonJs/AMD modules for the browser. Allows to split your codebase into multiple bundles, which can be loaded on demand. Support loaders to preprocess files, i.e. json, jade, coffee, css, less, ... and your custom stuff.',
  'dist-tags': { latest: '1.14.0', beta: '2.2.0' },
...
```

Alternatively, visit https://www.npmjs.com/package/webpack, information for 1.14.0 is displayed.

**What is the expected behavior?**

Since 2.2.0 is now released, it should be _latest_.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by mihaibogdan10** [comment]
Looking at their blog post, it looks like intended behavior for ~5 more days:
https://medium.com/webpack/webpack-2-2-the-final-release-76c3d43bf144#.q9w94f1k6

**Comment by ArturDorochowicz** [comment]
I see, I was kind of suspecting something like that to be the case. Haven't seen this article yet, thanks for the link.

Closing then.

**Comment by TheLarkInn** [comment]
Yup that is correct!! Thanks for clarifying this to @ArturDorochowicz
