### ISSUE TITLE
npm latest tag is still 1.x 

### ISSUE THREAD

**Issue by jdalton** [webpack/webpack#4064]
I noticed when I installed webpack via npm that 1.x installed instead of 2.x.
```shell
$ npm dist-tag ls webpack
beta: 2.2.0
latest: 1.14.0
```

To fix this you all need to set the [dist-tag](https://docs.npmjs.com/cli/dist-tag) of the latest release, 2.2.0, to latest.
```shell
$ npm dist-tag rm webpack beta
$ npm dist-tag add webpack@2.2.0 latest
```

**Comment by TheLarkInn** [comment]
On purpose still for the next 5 days. See #4063

**Comment by TheLarkInn** [comment]
Let's leave this open until we transfer to latest for visibility.

**Comment by jdalton** [comment]
Ah, ok. Kinda odd though. The release in github isn't marked as beta or RC. It's a bit of a mixed signal. If it was meant to be another RC release it could have been named as the previous ones. Without the `latest` tag automation like [greenkeeper](https://github.com/integration/greenkeeper) aren't triggered.

**Comment by TheLarkInn** [comment]
Yeah we just wanted to be safe and announce and let the anxious folks grab it and then that way the community can help those who end up with a webpack 2 automagically from an install and are confused. 

Next releases we will plan to treat like conventional ones on the latest tag.

**Comment by jdalton** [comment]
Btw, I don't think I've said it enough but you all have totally improved the way I develop. As a lib author y'all are simply magic ✨  and give me so many more options to cater to the various consumption needs of my users 👏

**Comment by MartinJohns** [comment]
@TheLarkInn Any update on this?

**Comment by dmitriid** [comment]
@MartinJohns it's coming, https://github.com/webpack/webpack.js.org/issues/670, namely https://github.com/webpack/webpack.js.org/issues/670#issuecomment-275715394 and https://github.com/webpack/webpack.js.org/issues/670#issuecomment-275743801
