### ISSUE TITLE
AggressiveSplittingPlugin breaks when using externals

### ISSUE THREAD

**Issue by buu700** [webpack/webpack#4065]
**Do you want to request a *feature* or report a *bug*?**

Report a bug.

**What is the current behavior?**

When using a configuration that includes both externals and AggressiveSplittingPlugin, the run-time error `Uncaught TypeError: Cannot read property 'call' of undefined` is produced. It looks like, while the expected output of `externals` does appear within the generated chunks, `stats.compilation.entrypoints.main.chunks` is populated with an incorrect order.

Confirmed workarounds:

1. Remove AggressiveSplittingPlugin

2. Create a file `externals/jquery.js` with the content `module.exports = self.jQuery;` and replace `externals: {jquery: 'self.jQuery'}` with `resolve: {alias: {jquery: '/path/to/externals/jquery.js'}}`

**If the current behavior is a bug, please provide the steps to reproduce.**

```
const cheerio	= require('cheerio');
const webpack	= require('webpack');

webpack({
	entry: {
		main: './cyph.com/main'
	},
	externals: {
		jquery: 'self.jQuery'
	},
	output: {
		filename: '[chunkhash].js',
		chunkFilename: '[chunkhash].js',
		path: '/cyph/shared/js/cyph.com/pack'
	},
	plugins: [
		new webpack.optimize.AggressiveSplittingPlugin({
			minSize: 30000,
			maxSize: 50000
		}),
		/* Workaround for issue #3851 */
		new webpack.optimize.CommonsChunkPlugin({
			name: 'init',
			minChunks: Infinity
		})
	],
	recordsOutputPath: '/cyph/cyph.com/webpack.json'
}, (err, stats) => {
	if (err) {
		throw err;
	}

	const $	= cheerio.load(fs.readFileSync('/cyph/cyph.com/index.html').toString());

	$('script[src="/js/cyph.com/main.js"]').remove();

	for (const chunk of stats.compilation.entrypoints.main.chunks) {
		for (const file of chunk.files) {
			$('body').append(`<script src='/js/cyph.com/pack/${file}'></script>`);
		}
	}

	fs.writeFileSync('/cyph/cyph.com/.index.html', $.html().trim());
}));
```

**What is the expected behavior?**

`stats.compilation.entrypoints.main.chunks` should contain the correct order.

Maybe the externals implementation could be changed to just do the same thing as workaround 2? (I'm not very familiar with Webpack, but I don't see any obvious difference between externals' intended/documented behaviour and what this method correctly accomplishes.)

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**

Webpack: 2.2.0 (also reproduced with rc.4)
Browser: Chrome 55.0.2883.95
Node.js: 6.9.4
Operating system: Debian Jessie in a Docker container on OS X El Capitan
Programming language: JavaScript/TypeScript

**Comment by sokra** [comment]
I assume this was fixed. If not open a new issue.
