### ISSUE TITLE
UglifyJsPlugin translate css cause problem

### ISSUE THREAD

**Issue by petrelselina** [webpack/webpack#4067]
my css keyframes are like below:
`@keyframes drive {
  0% {
    transform: rotate(0deg) translate3d(-200%,0,100%);
    opacity: 0;
  }
  33.33% {
    transform: rotate(0deg) translate3d(0,0,0);
    opacity: 1;
  }
  66.66% {
    transform: rotate(-360deg) translate3d(0,0,0);
    opacity: 1;
  }
  100% {
    transform: rotate(-360deg) translate3d(200%,0,100%);
    opacity: 0;
  }
}`
and the UglifyJsPlugin translate it to:
`@keyframes drive {
  0% {
    transform: rotate(0deg) translate3d(-200%,0,100%);
    opacity: 0;
  }
  33.33% {
    transform: rotate(0deg) translateZ(0);
    opacity: 1;
  }
  66.66% {
    transform: rotate(-360deg) translateZ(0);
    opacity: 1;
  }
  100% {
    transform: rotate(-360deg) translate3d(200%,0,100%);
    opacity: 0;
  }
}`
it parse "translate3d(0,0,0)" to translateZ(0), and it will make the annimation broken in safari

**Comment by bebraw** [comment]
Can you follow the issue template? Thanks.

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
