### ISSUE TITLE
Feature: Better documentation for require.ensure

### ISSUE THREAD

**Issue by ccorcos** [webpack/webpack#4070]
**Do you want to request a *feature* or report a *bug*?**

Its unclear from the documentation and example how exactly `require.ensure` is supposed to work

- https://webpack.github.io/docs/code-splitting.html
- https://github.com/webpack/webpack/tree/webpack-1/examples

I've seen it used three different ways.

```js
require.ensure(["module-a", "module-b"], function() {
  var a = require("module-a");
  var a = require("module-b");
  // ...
});

require.ensure(["module-a", "module-b"], function(a, b) {
  // ...
});

require.ensure([], function(require) {
  var a = require("module-a");
  var a = require("module-b");
  // ...
});
```

Are these all supported? Are some recommended and others not?

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by bebraw** [comment]
Can you [re-open the issue at the docs repo](https://github.com/webpack/webpack.js.org/issues)?

**Comment by SpaceK33z** [comment]
Also, have you read the page about it in the [new docs](https://webpack.js.org/guides/code-splitting-require/)?

**Comment by ccorcos** [comment]
Sorry, I was on vacation. New docs look to be much more helpful!
