### ISSUE TITLE
exports is not defined 

### ISSUE THREAD

**Issue by BoryaMogila** [webpack/webpack#4076]
Exports is not defined if use in some modules module.exports,  in some export and disable Babel modules

**Comment by bebraw** [comment]
Hi,

There's not enough info. Can you follow the issue template?

**Comment by BoryaMogila** [comment]
Hi,
//my webpack config
const webpack       = require('webpack'),
      config        = require('config'),
      NODE_ENV      = process.env.NODE_ENV || 'development',
      UNALIZE_SIZE  = process.env.UNALIZE_SIZE,
      isDevelopment = NODE_ENV === 'development',
      CompressionPlugin = require("compression-webpack-plugin"),
      WebpackShellPlugin = require('webpack-shell-plugin');

var  plugins = [
    new webpack.EnvironmentPlugin(Object.keys(process.env)),
    //експортить константи
    new webpack.DefinePlugin({
        cutCode: JSON.stringify(true)
    }),
    new webpack.optimize.CommonsChunkPlugin({
        children: true,
        async: true,
        minChunks: 2,
    }),
    new webpack.ContextReplacementPlugin(/moment[\\\/]locale$/, /^\.\/(uk|ru)$/),
];
var babelPlugins = ['transform-runtime'];
var presets = ['es2015-webpack', 'stage-0', 'react'];
if(!isDevelopment){
    plugins.push(new webpack.optimize.UglifyJsPlugin({
        beautify: false,
        comments: false,
        compress: {
            sequences     : true,
            booleans      : true,
            loops         : true,
            unused      : true,
            warnings    : false,
            //drop_console: true,
            unsafe      : true
        }
    }));
    plugins.push(new CompressionPlugin({
        asset: "[path].gz[query]",
        algorithm: "gzip",
        test: /\.js$|\.html$/,
        threshold: 10240,
        minRatio: 0.8
    }));
    plugins.push(new WebpackShellPlugin({
        onBuildStart:['echo "Webpack Start"'],
        onBuildEnd:[
            'echo "Webpack End"'
        ]
    }));
}

const wpConfig = {
    entry       : {
        app: './src/index.js'
    },
    output      : {
        path      : __dirname + '/public/js/build',
        publicPath: `${config.js_domain}/react/js/build/`,
        filename  : `bundle_${config.jsVersion}.js`,
        chunkFilename: 'chunks/[chunkhash].js'
    },
    watch       : isDevelopment,
    watchOptions: {
        aggregateTimeout: 100
    },
    module      : {
        rules: [
            {
                loader : 'babel-loader',
                exclude: /node_modules(?!(\/newbuild_library|\/redux-promise-middleware))/,
                query: {
                    plugins: babelPlugins,
                    presets: presets,
                }
            },
            {
                test: /\.css$/, loader: "style-loader!css-loader"
            },
        ]
    },
    resolve     : {
        extensions: ['.js', '.jsx']
    },
    devtool     : isDevelopment ? 'eval-source-map' : false,
    plugins : plugins,
    externals   : {config: require('config')}
};

module.exports = wpConfig;

if in project exists files with code like:

const myModule =  {
    bla: 'bla-bla'
}
module.exports = myModule;

after building in browser i have error (exports is not defined).

**Comment by bebraw** [comment]
A standalone project would be better as then I could verify locally. 👍

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
