### ISSUE TITLE
resolve.packageAlias not working on webpack2

### ISSUE THREAD

**Issue by unional** [webpack/webpack#4078]
webpack: 2.2.0

error:
```sh
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.resolve has an unknown property 'packageAlias'. These properties are valid:
   object { alias?, aliasFields?, cachePredicate?, descriptionFiles?, enforceExtension?, enforceModuleExtension?, extensions?, fileSystem?, mainFields?, mainFiles
?, moduleExtensions?, modules?, plugins?, resolver?, symlinks?, unsafeCache?, useSyncFileSystemCalls? }
```

**Comment by bebraw** [comment]
Can you follow the issue template? What are you trying to do? Configuration changed quite a bit in webpack 2 and it's likely that field is elsewhere now (migration docs might cover that).

**Comment by timse** [comment]
looking at the git history this options is now : "aliasFields"

otherwise i agree to what @bebraw said :)

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
