### ISSUE TITLE
Error trying to build ContextModule with cash when delete a file

### ISSUE THREAD

**Issue by tranotheron** [webpack/webpack#4079]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When I remove a file required by context (like src/components/o.scss) with cache I'm receiveing an error
**If the current behavior is a bug, please provide the steps to reproduce.**
clone repo: https://github.com/tranotheron/The-Fog-Boilerplate---React-Redux
npm/yarn start
remove file src/components/o.scss

**What is the expected behavior?**
when cache is on, and you remove file build webpack should build module without this file
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
OS: macOS Sierra 10.12.22
Node.js version: 7.3
webpack version: 2.2.0

Hi.

I want to dynamically build my scss/css scripts with hot reload without declare exact file paths in one file by hand, so I tried to create one file with context.require: https://github.com/tranotheron/The-Fog-Boilerplate---React-Redux/blob/master/src/style.js
Build speed is very important so I'm using caching, dll, and hot reload but when cache is on when I remove a .scss file from I'm receiving an error:

```
ERROR in ./~/css-loader!./~/sass-loader!./src/components/o.scss
Module build failed: Error: ENOENT: no such file or directory, open '/Users/bartlomiejsmykla/Projects/fog---react-redux-boilerplate/src/components/o.scss'
 @ ./src/components/o.scss 4:14-118 13:2-17:4 14:20-124
 @ ./src/components \.scss$
 @ ./src/style.js
 @ multi react-hot-loader/patch webpack-dev-server/client?http://localhost:7777 webpack/hot/only-dev-server react-hot-loader ./app.jsx ./index.html ./style.js
```
When I disable cache just for ContextModule here: https://github.com/webpack/webpack/blob/028c51301733836abbedc88be7483af2623f5943/lib/ContextModule.js
everything is working. Is there a way to somehow work around this problem. I spent a lot of time trying to write some plugin and I figured out, that when on compilation phase I remove from style.js entry this dependency (if it's not exist on filesystem) it's working, when this file was not present on first compilation (when you create file after webpack dev server fired up and after that remove a file), but when file is present in build on firing up dev server, and then you will try to remove a file even removing it from style.js entry on compilation phase you will receive this error too.

To reproduce this error I created a repository: https://github.com/tranotheron/The-Fog-Boilerplate---React-Redux

**Comment by sokra** [comment]
Could you paste the error with `--display-error-details` (for the stacktrace)?

**Comment by tranotheron** [comment]
This is the error with error details :-(
![WebpackDevServer config](https://d3vv6lp55qjaqc.cloudfront.net/items/153e0o281O130w1l260w/Image%202017-01-23%20at%2010.55.12%20AM.png?X-CloudApp-Visitor-Id=2483191&v=bcc06660)

**Comment by tranotheron** [comment]
I will do my best to resolve this issue, but maybe someone had this issue too?

**Comment by chrisvariety** [comment]
I'm seeing this same issue using https://github.com/thoughtindustries/ember-webpack-resolver/blob/master/index.js

OS: macOS Sierra 10.12.2 (16C67)
Node.js version: 4.5.0
webpack version: 2.2.0

I did manage to capture this stacktrace...

```
    at new ModuleBuildError (/Users/chrismcc/workspace/ti/node_modules/webpack/lib/ModuleBuildError.js:11:10)
    at /Users/chrismcc/workspace/ti/node_modules/webpack/lib/NormalModule.js:141:35
    at /Users/chrismcc/workspace/ti/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at Array.<anonymous> (/Users/chrismcc/workspace/ti/node_modules/loader-runner/lib/LoaderRunner.js:200:19)
    at Storage.finished (/Users/chrismcc/workspace/ti/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:15)
    at ReadFileContext.<anonymous> (/Users/chrismcc/workspace/ti/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:69:9)
    at ReadFileContext.callback (/Users/chrismcc/workspace/ti/node_modules/graceful-fs/graceful-fs.js:78:16)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:303:13)
Error: ENOENT: no such file or directory, open '/Users/chrismcc/workspace/ti/assets/javascripts/lms/templates/manager/course.hbs'
    at Error (native)
```
