### ISSUE TITLE
classes not tree-shaked

### ISSUE THREAD

**Issue by jouni-kantola** [webpack/webpack#4080]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I've got a module with a couple of classes and a constant.
- With multiple exports: When I only import the constant, classes are not tree shaked.
- With single export: When I only export the constant, the classes are not tree shaked.
- The only way I get the classes tree shaked is by not importing the module at all.

**If the current behavior is a bug, please provide the steps to reproduce.**

I've setup a repro branch here:
https://github.com/jouni-kantola/webpack-output-by-build-type/tree/class-tree-shaking

1. Clone the repo https://github.com/jouni-kantola/webpack-output-by-build-type and switch to branch `class-tree-shaking`
2. `yarn`
3. `npm run build` to build without UglifyJsPlugin or `npm run build -- --env=production` to include UglifyJsPlugin

**What is the expected behavior?**
If not importing an module's exported class, I expect the class to be tree shaked.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
OS: MacOS Sierra (10.12.1)
Node.js: v6.8.0
Deps:
```
"devDependencies": {
    "babel-core": "^6.21.0",
    "babel-loader": "^6.2.10",
    "babel-preset-env": "^1.1.4",
    "html-webpack-plugin": "2.26.0",
    "inline-manifest-webpack-plugin": "^3.0.1",
    "webpack": "2.2.0",
    "webpack-dev-server": "^2.2.0-rc.0"
  }
```

**Comment by jouni-kantola** [comment]
Below are diff's when imports are changed, but output for classes stays the same:
```diff
// index.js
- import { OneNumber } from './class-tree-shaking.js';
- console.log(OneNumber);
+ import { aNumber } from './class-tree-shaking.js';
+ console.log(aNumber);
```

```diff
// output
-        }())
+        }(), 2)
```

**Comment by timse** [comment]
you are exporting an unnamed object

can you try again when you do this:
```
export class OneNumber {...
export class TwoNumbers {...
```

instead of this:

```
export { OneNumber, TwoNumbers };
```

**Comment by jouni-kantola** [comment]
Using the unnamed object literal seems to run just fine:
```javascript
import { OneNumber } from './class-tree-shaking.js';
const oneNumber = new OneNumber(12345);
console.log(oneNumber.a)  // output: 12345
```

Anyways, when changing to exporting `OneNumber` and `TwoNumbers` separately, and still only importing `aNumber`, like so:
```javascript
import { aNumber } from './class-tree-shaking.js';
console.log(aNumber);
```

The following extract is till included in outputted bundle:
```javascript
/* ... */
c = function() {
    function t() {
        u(this, t)
    }
    return i(t, [{
        key: "_subtract",
        value: function(t, e) {
            return t - e
        }
    }, {
        key: "sum",
        get: function() {
            return this.first + this.second
        }
    }], [{
        key: "multiply",
        value: function(t, e) {
            return t * e
        }
    }]), t
}(),
/* ... */
```

**Comment by jouni-kantola** [comment]
I updated the branch, so now both cases are covered.
This commit is with object literal exported:
https://github.com/jouni-kantola/webpack-output-by-build-type/commit/a50c163b657977e2e6847b356b18b29ef787dbee

This commit is with the classes exported separately:
https://github.com/jouni-kantola/webpack-output-by-build-type/commit/87b5f19b70fa40074df526b30b24b08d44403a15

**Comment by timse** [comment]
well the problem is the polyfill of the class...
its a selfexecutable function therefore it could have sideeffects and uglifyjs does not remove it.

this has nothing to do with webpack, it perfectly fine only exports the `aNumber`.

**Comment by jouni-kantola** [comment]
@timse: Thank you for your input. So, it's rather related to how Babel transpiles the code.

But then I can't see how I this can be fixed, using Uglify for dead code elimination. Just for the sake of testing, if I remove `babel-loader` I get the following error, :
`SyntaxError: Unexpected token: name (Math) [./src/class-tree-shaking.js:1,0][app.5cc25d11d4824e0083ed.prod.js:6,6]`

**Comment by timse** [comment]
i dont think there is currently any way to fix this tbh.

**Comment by sokra** [comment]
There is an issue in UglifyJs to adress this. It's a known problem and already reported.

**Comment by ysangkok** [comment]
This seems to be the issue in UglifyJs: https://github.com/mishoo/UglifyJS2/issues/1261

**Comment by dzearing** [comment]
@sokra Question on this issue; I have an `index` file which exports { SomeClass } from './SomeClass', and { someFunction } from './someFunction'; If i `import { someFunction }` from this index, I still see the class defined in the pre-minified bundle. Thus the uglify issue comes into play.

Is it possible for webpack to simply not include files which contain no explicitly imported modules? I never explicitly imported the class, yet webpack still wants to include the file, and uglify throws up. I think the tree shaking problem could be mostly avoided here at the webpack layer. You might still have non-optimization issues where the file contains multiple exports, but as of now AFAIK there is no way to get tree shaking working with classes.
