### ISSUE TITLE
Error when update version webpack

### ISSUE THREAD

**Issue by haisaco** [webpack/webpack#4081]
For angular2
When I update new version webpack I have new Issue this:
http://imgur.com/nEJN9oT
I don't no why  my web runing normal, but when I reinstall --npm install webpack-- then  run --npm run build-- and run again web have issuse!
Please help me!

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
