### ISSUE TITLE
Webpack 2: Requests with no extension resolve to node_modules before local resources

### ISSUE THREAD

**Issue by WearyMonkey** [webpack/webpack#4083]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Even though my `resolve.modules = [path.resolve(__dirname, 'src'), 'node_modules']`, requests without an extension are resolving to `node_modules` before `src` resources.

**If the current behavior is a bug, please provide the steps to reproduce.**

```
git clone https://github.com/WearyMonkey/webpack-resolve-bug
cd webpack-resolve-bug
npm i
$(npm bin)/webpack
...
out.js  10.9 kB       0  [emitted]  main
   [0] ./~/events/events.js 8.33 kB {0} [built]
   [1] ./src/entry.js 18 bytes {0} [built]
```

**What is the expected behavior?**

https://webpack.js.org/configuration/resolve/#resolve-modules

`require('events')` should resolve to `src/events.js`.

```
out.js  10.9 kB       0  [emitted]  main
   [0] ./src/events.js 8.33 kB {0} [built]
   [1] ./src/entry.js 18 bytes {0} [built]
```

**If this is a feature request, what is motivation or use case for changing the behavior?**

Nope.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Webpack 2.2.0
Node v7.2.1
OSX Sierra 10.12.1

Resources resolve to `node_modules` even after removing `node_modules` from `resolve.modules` entirely.

`require('events.js')` resolves to `./src/events.js` correctly.

**Comment by sokra** [comment]
`events` is special, because it's a native node.js module. Does it behave correctly if you rename the files? i. e. `events1`?

**Comment by WearyMonkey** [comment]
You're right, it does seem specific to `events`. I could not reproduce the same results with the `left-pad` npm module.

I would not be expecting my web site `imports` to resolve to native node modules though. Any fix in site?

**Comment by sokra** [comment]
you can disable this behavior with `node: { events: false }` (disable only the events polyfill) or `node: false` (disable all node.js specific behavior).

**Comment by WearyMonkey** [comment]
`node: { events: false }` works but are there any other polyfills I need to disable?
`node: false` gives the validation error: `- configuration.node should be an object.`
