### ISSUE TITLE
function __webpack_require__ does not properly check for existence of module

### ISSUE THREAD

**Issue by Stephn-R** [webpack/webpack#4087]
**Do you want to request a *feature* or report a *bug*?**

- Reporting a bug

**What is the current behavior?**

- I am recognizing the following error when constructing a simple bundle using require.ensure()

![image](https://cloud.githubusercontent.com/assets/5117415/22214427/8bb42a34-e165-11e6-816d-c85f6d04481e.png)
![image](https://cloud.githubusercontent.com/assets/5117415/22214481/b5558446-e165-11e6-837c-20cce74ccf8c.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

In order to reproduce the error, download the following modules + versions:

```
- Node @ 7.1.0
- Webpack @ 2.2.0
```

Create a simple bundle using rquireAll to do deep requires

```js
function requireAll(r) { r.keys().forEach(r); }

require.ensure([
  // required modules
], require => {
  // additional modules
}, 'vendor');
```

**What is the expected behavior?**

It should not crash if a module does not exist or cannot be found. Instead, it should report that the requested module was missing.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Please see above for version numbers

**Comment by timse** [comment]
you can set `output.strictModuleExceptionHandling`.
this will however swallow the error instead of reporting

**Comment by Stephn-R** [comment]
Correction, after some digging, this is a simpler issue. During the callback function of ensure, relative paths to asset files (i.e. JS, CSS) did not work. That was what caused the error for me

**Comment by sokra** [comment]
Could you create a simple repro repo?

**Comment by Stephn-R** [comment]
Please see this project >> https://github.com/Stephn-R/webpack-ensure-issue

There are two `Cases` in the `index.js` file. Case A fails to source the `angular` module but Case B works perfectly fine.

**Comment by timse** [comment]
it works perfectly fine on my machine.

what should happen?

**Comment by Stephn-R** [comment]
Are you running Case A and looking in the console for errors? Also, what are you OS settings?

**Comment by timse** [comment]
Yes i did have to fix the public path and the characters that are leftover in the code. But after that it just worked

**Comment by Stephn-R** [comment]
Ok but thats my point. You had to fix it otherwise after the build rather than the build just working.

**Comment by timse** [comment]
Well if you do not have a proper configuration what do you expect?

**Comment by Stephn-R** [comment]
This is a proper configuration but it causes the issue that I mentioned. You having to "fix" the config is not the issue, the issue is that based on the tutorial docs, the ensure function does not work as expected.

@timse can you share the changes you made to make this work?
