### ISSUE TITLE
Investigate Feature Parity with react-packager (for React Native)

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack#4088]
Wanted to list a set of ideas, concepts that could be inspiration for webpack to implement to have feature parity with [react-packager](https://github.com/facebook/react-native/tree/master/packager) (for React Native). 

Speaking with @nathonhammond I was explained a concept of `provideModules`.

It appears as if it declaratively (via pragma comments in files), declare the exact exports and imports used. Apparently then their compiler generates the minimum AST needed to compile that module increasing speed, etc. Maybe this is worth experimenting? Would require some strange Parser configurations.

**Comment by aikar** [comment]
They were discussing threads-a-go-go on the discussion too about webpack.

Thoughts on Webpack using real threads to speed up compilation?
