### ISSUE TITLE
sourceMap variation - Documentation improvements

### ISSUE THREAD

**Issue by aight8** [webpack/webpack#4093]
There is:

```
webpack.optimize.UglifyJsPlugin({
   sourceMap: false, <-
}),
```

Then **css loader**, **scss loader**, **postcss loader** have all their own sourceMap property.
Finally we have **devtool** under the webpack config root.
Babel too?

So this is extremely confusing, the source map often not works correctly (bad line number etc.), so I don't know if it's based on misconfiguration or because of the limitation of some **devtool** source map types.

I'm sure that there is a logical description how to configure this correctly and why you can configure the sourcemap on all this levels.

It would be very nice when the webpack documentation give a deep look about the source map topic and what is important to know when configuring - especially when using webpack loaders which supports source map.

By the side: The configuration name **devtool** is soo confusing confusing, why "devtool" at all? Why not change it in webpack 3 just to something more descriptive - like sourceMapType or whatever? (Yes it's then not so super sexy short but the people understand what the configuration is about! this is 100times more worthful.)

All kind of options for devtool is confusing too. I see the performance table in the docs yes, but why so complicated? The most users outside there have no clue what the different types affects exactly - really.

**Comment by bebraw** [comment]
Can you re-open the doc part of the issue at the [docs tracker](https://github.com/webpack/webpack.js.org/issues)? Thanks.

I agree it's a confusing setup. Miss one flag and it simply won't work as you might expect. If it were up to me, I would deprecate `devtool` and have people use the plugin option instead. You could still write a user space alias to achieve `devtool` kind of functionality, but I would rather drop it from the core as it feels too opinionated to have there. I understand the convenience it tries to provide, though.
