### ISSUE TITLE
Webpack 2 and CSP

### ISSUE THREAD

**Issue by Hanterdro** [webpack/webpack#4094]
Hey,

it seems that Webpack 2 uses the `eval` method when building on dev-mode.
`eval` causes a CSP (Content Security Policy) violation. This is no showstopper for us, but it's really disturbing while developing, because we will start ignoring the CSP violations caused by the webpack dev mode and overlook real CSP violations in the development phase.

**Comment by timse** [comment]
is this related to using an "eval" devtool?
https://webpack.js.org/configuration/devtool/#devtool
could a change of use help out?

**Comment by Hanterdro** [comment]
Hey,

thank you for the hint.
Yeah, it was the devtool setting. But setting it in my webpack.config didn't fixed it, because I'm used webpack in dev mode with the cli argument `-d`. In Webpack 1 `-d` executed `--debug --devtool source-map --output-pathinfo`. But in Webpack 2 its `--debug --devtool eval-cheap-module-source-map --output-pathinfo` :-)

This is a change which should be mentioned at
https://webpack.js.org/guides/migrating/

**Comment by sokra** [comment]
Yep, file an issue on the documentation repo webpack/webpack.js.org, or submit a PR.
