### ISSUE TITLE
Issues with workers vendor files and closure compiler

### ISSUE THREAD

**Issue by Pieter-Jan** [webpack/webpack#4097]
Hello,

I've been using webpack for over a year now and overall I am happy with the results I am getting.

Recently I also included a few web-workers in my build. What I have noticed is that webpack includes some important header into the first file you that loads. Because my main code is being obfuscated, this header is included in my "vendor.js" file, where external code is put, making sure it does not get obfuscated. For the worker, I could not use a vendor.js file for this reason as a worker needs to consist of one file.

Now my project has grown the the size that I NEED to split the vendor part out of the worker. Is there any good way to achieve this, or the circumvent the header problem that webpack creates here?

Thanks

**Comment by sokra** [comment]
`import("./worker")` in the worker entry point.

Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md).
