### ISSUE TITLE
ES6 Refactor

### ISSUE THREAD

**Issue by wtgtybhertgeghgtwtg** [webpack/webpack#4099]
**Do you want to request a *feature* or report a *bug*?**
Feature.

**What is the current behavior?**
Not all `webpack@2` things use ES6 syntax as appropriate.
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
`webpack@2` things should use ES6 as appropriate.
**If this is a feature request, what is motivation or use case for changing the behavior?**
Consistent code base.
**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
N/A

There's been [a lot of refactoring](https://github.com/webpack/webpack/pulls?utf8=%E2%9C%93&q=is%3Apr%20refactor(ES6)) but I didn't see an issue for it.  Should there be an umbrella issue?  Should it cover other Webpack projects (`css-loader`, `loader-utils`, et cetera)?

**Comment by bebraw** [comment]
It's probably better to handle it per project. There's simply so much code the issue would become huge.

**Comment by wtgtybhertgeghgtwtg** [comment]
It'd be huge, but there would be less of a chance to miss things.

**Comment by TheLarkInn** [comment]
I mean, _thats a lot of stuff_ I do agree though it would be good for people to see what remains on the list etc. But _THATS ALOT OF STUFF_ to put in an issue :joy:. I cant spend the time myself to document it all, but I'll mark this for contribs to see.

**Comment by rafde** [comment]
A lot of refactors but no merges. Feel a bit discouraging for those considering wanting to help.

**Comment by TheLarkInn** [comment]
Hey!! We have been sorting out some CI stuff. This is my number one priority at the moment to jump back in and review and merge these. I appreciate your patience.

**Comment by krsjoseph** [comment]
Hey @TheLarkInn I'll take some of these on.

**Comment by tarang9211** [comment]
@TheLarkInn @bebraw do we have a list of what is remaining to refactor?

**Comment by bebraw** [comment]
@tarang9211 I don't think there's an official list. I agree that makes it a little tough to coordinate PR work. Maybe it's better to help with reviews instead?

**Comment by tarang9211** [comment]
@bebraw hmm, that's one way to help, sure. What exactly should I be looking for when I review?

**Comment by bebraw** [comment]
@tarang9211 I don't think we have official guidelines for reviews yet. I would look into the code very cafefully to make sure the port is complete. It's easy to miss some subtle behavior or improvement. Then comment at a PR after the review. Thanks. 👍 

@TheLarkInn Official PR review guidelines would be handy.

**Comment by neelbommisetty** [comment]
Hi i am a new here and would love to help. Please let me know what files are left to refactor.

Thanks

**Comment by rafde** [comment]
@neelbommisetty I suggest looking at what PRs aren't already up.

This issue may be easy to close using [5to6 codemods](https://github.com/5to6/5to6-codemod)

**Comment by thescientist13** [comment]
Hey everyone, trying to help out and refactor _HotModuleReplacementPlugin.js` and when running `yarn test`, I'm getting this error, but have no idea what it is trying to tell me :/
```bash
$ yarn test
yarn test v0.21.3
$ npm run lint-files

> webpack@2.3.3 lint-files /Users/obuckley/Workspace/github/webpack
> npm run lint && npm run beautify-lint


> webpack@2.3.3 lint /Users/obuckley/Workspace/github/webpack
> eslint lib bin hot buildin test/**/webpack.config.js test/binCases/**/test.js examples/**/webpack.config.js


> webpack@2.3.3 beautify-lint /Users/obuckley/Workspace/github/webpack
> beautify-lint 'lib/**/*.js' 'hot/**/*.js' 'bin/**/*.js' 'benchmark/*.js' 'test/*.js'

Index: lib/HotModuleReplacementPlugin.js
===================================================================
--- lib/HotModuleReplacementPlugin.js
+++ lib/HotModuleReplacementPlugin.js
@@ -166,12 +166,12 @@
 				return this.asString([
 					source,
 					"",
 					hotInitCode
-						.replace(/\$require\$/g, this.requireFn)
-						.replace(/\$hash\$/g, JSON.stringify(hash))
-						.replace(/\/\*foreachInstalledChunks\*\//g, chunk.chunks.length > 0 ?
-							"for(let chunkId in installedChunks)" : "let chunkId = " + JSON.stringify(chunk.id) + ";")
+					.replace(/\$require\$/g, this.requireFn)
+					.replace(/\$hash\$/g, JSON.stringify(hash))
+					.replace(/\/\*foreachInstalledChunks\*\//g, chunk.chunks.length > 0 ?
+						"for(let chunkId in installedChunks)" : "let chunkId = " + JSON.stringify(chunk.id) + ";")
 				]);
 			});

 			compilation.mainTemplate.plugin("global-hash", function() {


1 Errors. (311 files checked)

npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "beautify-lint"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! webpack@2.3.3 beautify-lint: `beautify-lint 'lib/**/*.js' 'hot/**/*.js' 'bin/**/*.js' 'benchmark/*.js' 'test/*.js'`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webpack@2.3.3 beautify-lint script 'beautify-lint 'lib/**/*.js' 'hot/**/*.js' 'bin/**/*.js' 'benchmark/*.js' 'test/*.js''.
```

**Comment by ismail-syed** [comment]
Is this being worked on, can I take a stab at it?
