### ISSUE TITLE
Why does require return an empty object?

### ISSUE THREAD

**Issue by janhancic** [webpack/webpack#411]
I was trying to use [showdown](https://github.com/coreyti/showdown) with webpack.

Showdown has [this node specific code](https://github.com/coreyti/showdown/blob/master/src/showdown.js#L120:L136), and it failed as webpack returned an empty object for the `var fs = require('fs');` call. Why is that so? Shouldn't it return null or undefined?

I can appreciate that Showdown wasn't written with webpack in mind, but I imagine there is lot's of code out there, doing the same exact thing.

So, do I need to patch showdown, or is there some change in webpack that will solve this? Thanks!

**Comment by dqdinh** [comment]
FWIW: I've tried all the workarounds including setting `"browser": { "fs": false }` in package.json but without success.

Found a [SO post](http://stackoverflow.com/questions/25565558/how-have-webpack-skip-a-module-if-it-doesnt-exist) that suggested switching to Marked and now everything just works.
