### ISSUE TITLE
[feature request] Loading AMD modules via network.

### ISSUE THREAD

**Issue by trusktr** [webpack/webpack#4110]
**Do you want to request a *feature* or report a *bug*?**

feature: 
http://stackoverflow.com/questions/41860191/is-there-a-way-to-load-amd-modules-from-modules-compiled-with-webpack-at-runtim/41861841?noredirect=1#comment70911971_41861841

**If this is a feature request, what is motivation or use case for changing the behavior?**

It would be amazing for Webpack to be truly "AMD compatible" by being able to load and execute network modules when those modules are AMD modules, with a simple configuration that can optionally detect the AMD module during build time and just not include it in the bundle (but optionally move it to the output dir).

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

N/A

It seems like the only option at the moment is to transpile AMD modules into the bundle. However, I'd don't have access to the bundles, they are on CDN, and they need to stay on CDN and be accessed through CDN as a requirement. It would be awesome to make Webpack selectively ignore those modules (like the IgnorePlugin) but then be able to load them.

Is there some way to do this with a plugin perhaps?

**Comment by trusktr** [comment]
To clarify, I want to write

```js
// a.js
import B from './b'
new B
```

```js
// b.js
import Foo from 'network-location-alias-or-similar/Foo' // AMD module.

export default
class B extends Foo {}
```

and compile that in Webpack.

I would also like to write 

```js
// a.js
import B from './b'
new B
```

```js
// b.js
import Foo from './Foo' // local AMD module.

export default
class B extends Foo {}
```

and have Webpack move the Foo asset to the output dir where I will serve it over HTTP and expect it to be loaded over the network.

**Comment by trusktr** [comment]
As a side note, I'd also like to have the default import be simply the thing returned from the AMD module. That's way easier than having to deal with `.default` access.

**Comment by sokra** [comment]
webpack will not load stuff from network. It's a compile-time tool.

But you can use webpack side-by-side with a AMD loader. Just add the modules to `externals` and set `output.libraryTarget: "amd"`.

**Comment by trusktr** [comment]
@sokra 

> But you can use webpack side-by-side with a AMD loader. Just add the modules to externals and set output.libraryTarget: "amd".

I tried that, so mine looks like

```js
module.exports = {
    entry: "./src/app.ts",
    output: {
        path: path.resolve(__dirname, 'public'),
        filename: "app.js",
        libraryTarget: 'amd',
    },
    externals: {
        jquery: 'jQuery',
    },
    // ...
}
```

and then in `app.ts` I have

```
import $ from 'jquery'
```

then the output looks like 

```js
define(function() { return /******/ (function(modules) { // webpackBootstrap
 // ...
/******/ ])});;
```

but I don't see `jQuery` in the `define()` call. I was expecting something like

```js
define('jQuery', function(jquery) { return /******/ (function(modules) { // webpackBootstrap
 // ...
/******/ ])});;
```

so that `jQuery` can be gotten via requirejs, then given to the webpack build. What am I missing? The docs aren't clear on this part. (and would be glad to contribute an update if it can work).

**Comment by trusktr** [comment]
Oh, nvm! For some reason my editor cached the old file. I see

```
define(["jQuery"], function(__WEBPACK_EXTERNAL_MODULE_67__) { return /******/ (function(modules) { // webpackBootstrap
```

which means I can get that via requirejs!! Woo. Thanks!!

**Comment by trusktr** [comment]
@sokra We should update the docs to mention `libraryTarget` when used alongside `externals`. The docs imply that `externals` works with globals, but doesn't really mention how we can use `libraryTarget` to output an AMD `define()` module and load externals via RequreJS. That would be great to include!

**Comment by sokra** [comment]
Sure great idea. Just create a PR to webpack/webpack.js.org
