### ISSUE TITLE
Webpack 2 regression: CLI stats no longer excludes modules from node_modules, etc.

### ISSUE THREAD

**Issue by SteveSandersonMS** [webpack/webpack#4113]
**Do you want to request a *feature* or report a *bug*?**

A bug

**What is the current behavior?**

The CLI's stats output isn't supposed to list modules from `node_modules`, etc. This is specified in the docs (https://github.com/webpack/docs/wiki/cli):

> Modules are hidden from output by default when they live inside directories called `["node_modules", "bower_components", "jam", "components"]`

This works correctly in Webpack 1.x. However, in Webpack 2.2.0, the CLI does incorrectly list entries from `node_modules`.

*REPRO STEPS:*

* In an empty directory, make a new project by running `npm init -y`, then `npm install --save webpack@beta jquery`.
* Add a `webpack.config.js` file containing this minimal build setup that just includes jQuery:

```javascript
module.exports = {
    output: { filename: '[name].js' },
    entry: 'jquery'
};
```

* Execute `webpack`

**What is the expected behavior?**

Expected output:

```
Hash: 9948f695646693810f81
Version: webpack 2.2.0
Time: 424ms
  Asset    Size  Chunks                    Chunk Names
main.js  270 kB       0  [emitted]  [big]  main
```

Actual output:

```
Hash: 9948f695646693810f81
Version: webpack 2.2.0
Time: 424ms
  Asset    Size  Chunks                    Chunk Names
main.js  270 kB       0  [emitted]  [big]  main
   [0] ./~/jquery/dist/jquery.js 267 kB {0} [built]
```

It doesn't look like a big deal in this minimal repro case, but in a large project where you reference something like Angular 2 that consists of hundreds of modules, having them all listed completely floods the stats output and prevents you from noticing your own modules among the deluge.

**Underlying cause**

It looks like this bug was introduced in commit 4220556089e0ed5b601ac523600480afe6b9c111 on this line: https://github.com/webpack/webpack/blame/4220556089e0ed5b601ac523600480afe6b9c111/lib/Stats.js#L72

As you see on that line, it uses `requestShortener` to change the identity of the module before checking it against `excludeModules`. But `requestShortener` replaces `/node_modules/` with `/~/`, so it no longer matches the regexes.

Suggested fix: Remove that line, and check `module.resource` against `excludeModules` instead.

**Comment by sokra** [comment]
see also #4144

**Comment by sokra** [comment]
see https://github.com/webpack/webpack/pull/4143

**Comment by sokra** [comment]
fixed in next branch
