### ISSUE TITLE
Webpack-dev-server on Windows consumes ~15% of CPU just watching for file changes

### ISSUE THREAD

**Issue by romanzenka** [webpack/webpack#4114]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
On a large-ish project, webpack keeps consistently burning large percentage of my CPU actively polling for file changes. My project is on a local SSD drive, yet I see 15% of all 4 cores being eaten up constantly.

**If the current behavior is a bug, please provide the steps to reproduce.**
Simply run webpack on Windows, do nothing and observe how much CPU it takes.

**What is the expected behavior?**
Use better filesystem watching APIs that does not require active polling when it is not strictly needed.
Possibly give me an option to switch polling off when I know it is safe to use filesystem events.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Webpack is trashing my disk and slowing my machine down doing work that only becomes useful when I save a file. It's too high price to pay.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Webpack; 1.14.1
Node: v6.9.4
OS: Windows 7 Professional SP1

**Comment by bebraw** [comment]
Here's a related PR: https://github.com/webpack/watchpack/pull/41 (chokidar -> sane).

**Comment by romanzenka** [comment]
This is what I found in our config:

`  hot: true,
    inline: true,
    progress: true,
    // Added watch options to get webpack-dev-server to pick up code changes on
    // windows.  Without this the hot: true, inline: true didn't reliable work on
    // windows and we had to restart to see changes.
    watchOptions: {
      aggregateTimeout: 300,
      poll: 1000
    },`

**Comment by bebraw** [comment]
Alright. So it's basically polling and that's very intensive.

I'm not sure if the situation is much better in webpack 2, but it's worth upgrading.

@SpaceK33z Any thoughts on this? Maybe we should move this issue elsewhere?

**Comment by romanzenka** [comment]
@bebraw I'm fine with just adding "me too" under the global "monitoring filesystem sucks in webpack".

Frankly, chokidar should not even have to exist, this is something Node.js should do on its own, maybe that's where we need to go?

**Comment by SpaceK33z** [comment]
@romanzenka chokidar *should* not have to exist, but it has to. The (Node.js) world isn't perfect unfortunately. The Node.js watch API's are very broken and have huge differences between operating systems.

The PR @bebraw mentioned will fix a lot of issues people are having.

You can reduce a lot of your CPU usage by ignoring the `node_modules` folder. [Checkout the docs about that](https://webpack.js.org/configuration/watch/#watchoptions-ignored).

**Comment by SpaceK33z** [comment]
Btw, it would be really cool if you could try out https://github.com/webpack/watchpack/pull/41 and let us know if it improves things for you. That will speed up the process to getting it merged.
