### ISSUE TITLE
Webpack 2 treats 'stats' option inconsistently

### ISSUE THREAD

**Issue by SteveSandersonMS** [webpack/webpack#4118]
**Do you want to request a *feature* or report a *bug*?**

A bug

**What is the current behavior?**

If you have a config like this:

```
module.exports = {
    stats: { modules: false },
    ... other config ...
};
```

... then Webpack 2 completely ignores the `modules: false` setting, and displays modules in stats (which it should not).

However, if you change your config to this:

```
module.exports = [{
    stats: { modules: false },
    ... other config ...
}];
```

... then it correctly honours the `modules: false` setting. I don't think this is by design - you shouldn't have to declare your config as a single-element array just to make it work, should you?

**What is the expected behavior?**

Consistency between `module.exports = { ... };` and `module.exports = [{ ... }];` styles.

**Comment by sokra** [comment]
Looks like a bug

**Comment by TheLarkInn** [comment]
presetsToOptions?

**Comment by sokra** [comment]
@SteveSandersonMS Which webpack version do you use?

**Comment by SteveSandersonMS** [comment]
@sokra Whatever version is latest (currently 2.2.1). Thanks for the fix!

**Comment by TheLarkInn** [comment]
@SteveSandersonMS Is this fixed now for you?

**Comment by TheLarkInn** [comment]
oh this is in master disregard,

**Comment by derpoho** [comment]
Just confirming, this is still present on Version 2.2.1.

**Comment by jbreckel** [comment]
is there any ETA for this fix?

**Comment by sokra** [comment]
fixed in next branch
