### ISSUE TITLE
why config sourcemap out of uglify?

### ISSUE THREAD

**Issue by zzzgit** [webpack/webpack#4119]
```javascript
{
plugins: [
        new webpack.optimize.UglifyJsPlugin({
            compress: true,
        })
    ],
devtool: 'cheap-source-map'
}
```
why not write the key `devtool` inside the `UglifyJsPlugin` config JSON literal?
according to the documentation of [uglify](https://www.npmjs.com/package/uglify-js),it does

**Comment by bebraw** [comment]
`devtool` is actually an alias to `SourceMapDevToolPlugin`. Note that loaders like `css-loader` implement sourcemaps too.

My understanding is that webpack needs to control the entire process. If you went only with Uglify sourcemaps, you would miss out the rest or might have to configure them anyway. In case you check out the uglify plugin source, you can see how webpack connects to it.
