### ISSUE TITLE
AggressiveSplittingPlugin breaks with recordsInputPath

### ISSUE THREAD

**Issue by buu700** [webpack/webpack#4121]
**Do you want to request a *feature* or report a *bug*?**

Report a bug.

**What is the current behavior?**

Using just recordsOutputPath works as expected, but specifying recordsPath or recordsInputPath causes AggressiveSplittingPlugin to hang at 100% CPU for about four hours on my machine before throwing the following exception:

```
path.js:78
function normalizeStringPosix(path, allowAboveRoot) {
                             ^

RangeError: Maximum call stack size exceeded
    at normalizeStringPosix (path.js:78:30)
    at Object.resolve (path.js:1161:20)
    at Object.relative (path.js:1232:18)
    at str.split.map (/node_modules/webpack/lib/optimize/AggressiveSplittingPlugin.js:14:17)
    at Array.map (native)
    at identifier.split.map (/node_modules/webpack/lib/optimize/AggressiveSplittingPlugin.js:13:26)
    at Array.map (native)
    at /node_modules/webpack/lib/optimize/AggressiveSplittingPlugin.js:12:32
    at Array.map (native)
    at Compilation.compilation.plugin (/node_modules/webpack/lib/optimize/AggressiveSplittingPlugin.js:77:46)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

```
const cheerio	= require('cheerio');
const webpack	= require('webpack');

webpack({
	entry: {
		main: './cyph.com/main'
	},
	output: {
		filename: '[name].js',
		chunkFilename: '[name].js',
		path: '/home/gibson/.build/shared/js/cyph.com/pack'
	},
	plugins: [
		new webpack.optimize.AggressiveSplittingPlugin({
			minSize: 30000,
			maxSize: 50000
		}),
		/* Workaround for issue #3851 */
		new webpack.optimize.CommonsChunkPlugin({
			name: 'init',
			minChunks: Infinity
		})
	],
	recordsPath: '/home/gibson/.build/cyph.com/webpack.json'
}, (err, stats) => {
	if (err) {
		throw err;
	}

	const $	= cheerio.load(
		fs.readFileSync('/home/gibson/.build/cyph.com/index.html').toString()
	);

	$('script[src="/js/cyph.com/main.js"]').remove();

	for (const chunk of stats.compilation.entrypoints.main.chunks) {
		for (const file of chunk.files) {
			$('body').append(`<script src='/js/cyph.com/pack/${file}'></script>`);
		}
	}

	fs.writeFileSync('/home/gibson/.build/cyph.com/.index.html', $.html().trim());
});
```

Related records file: https://github.com/cyph/cyph/blob/master/cyph.com/webpack.json

**What is the expected behavior?**

Webpack should run successfully with no exceptions.

**Please mention other relevant information such as the browser version, Node.js version, Operating System and programming language.**

Webpack: 2.2.0
Browser: Chrome 56.0.2924.76
Node.js: 6.9.4
Operating system: Debian Jessie in a Docker container on OS X El Capitan
Programming language: JavaScript/TypeScript

**Comment by buu700** [comment]
Just did a little bit of debugging in a repl to see if I could spot any obvious issues with the code from the stack trace.

```
const path = require('path');

/* Copied from AggressiveSplittingPlugin.js */
function makeRelative(context) {
	return function(module) {
		let identifier = module.identifier();
		return identifier.split("|").map((str) => {
			return str.split("!").map((str) => {
				return path.relative(context, str);
			}).join("!");
		}).join("|");
	};
}

const records = JSON.parse(fs.readFileSync('/cyph/cyph.com/webpack.json').toString())

for (const chunk of records.aggressiveSplits) {
	for (const id of chunk.modules) {
		console.log(
			makeRelative('/home/gibson/.build/shared/js')({identifier: () => id})
		);
	}
}
```

Worked as expected with no errors, so I'm not sure what Webpack is doing differently that would cause this.

**Comment by buu700** [comment]
Some more debugging: no idea whether this is expected or not, but I threw in some console logs and found that the function that starts on line 64 of AggressiveSplittingPlugin.js is being invoked repeatedly at some point within both the loop from line 73 and the loop from line 109.

Some output from my logs:
```
loop 1
splitData 0
chunk 0:0
loop 1
splitData 0
chunk 0:0
chunk 0:1
chunk 0:2
splitData 1
chunk 1:0
loop 1
splitData 0
chunk 0:0
chunk 0:1
chunk 0:2
chunk 0:3
splitData 1
chunk 1:0
chunk 1:1
chunk 1:2
chunk 1:3
splitData 2
chunk 2:0
loop 1
splitData 0
chunk 0:0
chunk 0:1
chunk 0:2
chunk 0:3
chunk 0:4
splitData 1
chunk 1:0
chunk 1:1
chunk 1:2
chunk 1:3
chunk 1:4
splitData 2
chunk 2:0
chunk 2:1
chunk 2:2
chunk 2:3
chunk 2:4
splitData 3
chunk 3:0
loop 1
splitData 0
chunk 0:0
chunk 0:1
chunk 0:2
chunk 0:3
chunk 0:4
chunk 0:5
...
splitData 69
chunk 69:0
chunk 69:1
chunk 69:2
chunk 69:3
chunk 69:4
chunk 69:5
chunk 69:6
chunk 69:7
chunk 69:8
chunk 69:9
chunk 69:10
chunk 69:11
chunk 69:12
chunk 69:13
chunk 69:14
chunk 69:15
chunk 69:16
chunk 69:17
chunk 69:18
chunk 69:19
chunk 69:20
chunk 69:21
chunk 69:22
chunk 69:23
chunk 69:24
chunk 69:25
chunk 69:26
chunk 69:27
chunk 69:28
chunk 69:29
chunk 69:30
chunk 69:31
chunk 69:32
chunk 69:33
chunk 69:34
chunk 69:35
chunk 69:36
chunk 69:37
chunk 69:38
chunk 69:39
chunk 69:40
chunk 69:41
chunk 69:42
chunk 69:43
chunk 69:44
chunk 69:45
chunk 69:46
chunk 69:47
chunk 69:48
chunk 69:49
chunk 69:50
chunk 69:51
chunk 69:52
chunk 69:53
chunk 69:54
chunk 69:55
chunk 69:56
chunk 69:57
chunk 69:58
chunk 69:59
chunk 69:60
chunk 69:61
chunk 69:62
chunk 69:63
chunk 69:64
chunk 69:65
chunk 69:66
chunk 69:67
chunk 69:68
chunk 69:69
loop 2
loop 1
splitData 0
chunk 0:0
chunk 0:1
chunk 0:2
chunk 0:3
chunk 0:4
chunk 0:5
chunk 0:6
chunk 0:7
chunk 0:8
chunk 0:9
chunk 0:10
chunk 0:11
chunk 0:12
chunk 0:13
chunk 0:14
chunk 0:15
chunk 0:16
chunk 0:17
chunk 0:18
chunk 0:19
chunk 0:20
chunk 0:21
chunk 0:22
chunk 0:23
chunk 0:24
chunk 0:25
chunk 0:26
chunk 0:27
chunk 0:28
chunk 0:29
chunk 0:30
chunk 0:31
chunk 0:32
chunk 0:33
chunk 0:34
chunk 0:35
chunk 0:36
chunk 0:37
chunk 0:38
chunk 0:39
chunk 0:40
chunk 0:41
chunk 0:42
chunk 0:43
chunk 0:44
chunk 0:45
chunk 0:46
chunk 0:47
chunk 0:48
chunk 0:49
chunk 0:50
chunk 0:51
chunk 0:52
chunk 0:53
chunk 0:54
chunk 0:55
chunk 0:56
chunk 0:57
chunk 0:58
chunk 0:59
chunk 0:60
chunk 0:61
chunk 0:62
chunk 0:63
chunk 0:64
chunk 0:65
chunk 0:66
chunk 0:67
chunk 0:68
chunk 0:69
chunk 0:70
splitData 1
chunk 1:0
chunk 1:1
...
chunk 70:67
chunk 70:68
chunk 70:69
chunk 70:70
loop 2
loop 1
splitData 0
chunk 0:0
chunk 0:1
chunk 0:2
chunk 0:3
chunk 0:4
chunk 0:5
chunk 0:6
chunk 0:7
...
```

**Comment by sokra** [comment]
This looks like a bug in the Plugin. I probably will be difficult to reproduce.

Could you prepare a repo or branch with all the relavant files and the records to reproduce?

**Comment by buu700** [comment]
Sure, I'll try to get a minimal repro set up today.

**Comment by buu700** [comment]
Minimal repro:

```
git clone https://github.com/buu700/webpack-4121
cd webpack-4121
./webpack.js
```

If I delete records.json and then run webpack.js, it finishes successfully in about 45 seconds. If I run webpack.js with records.json intact, it seems to hang as reported above.

The main precondition for reproduction, as far as I can tell, is that the records input be different from what the records output would have been if it were generated from scratch by packing the same code. In this case, I generated records.json by deleting an arbitrary subset of the import statements in main.js (lines 18 - 41) and running webpack.js. If I delete those same lines again and run webpack.js with records.json present, it finishes successfully in 12 seconds.

**Comment by buu700** [comment]
Update: tested and confirmed that it's still reproducible with webpack 2.3.

Any thoughts on what the general timeline might look like for resolving this issue? AggressiveSplittingPlugin is great in theory with the proliferation of HTTP/2, but would be much more useful if it also supported this feature to take better advantage of client caches.

**Comment by evilebottnawi** [comment]
I think still valid :disappointed:

**Comment by evilebottnawi** [comment]
@buu700 Can you provide simple reproducible test repo?

**Comment by alexander-akait** [comment]
bump

**Comment by alexander-akait** [comment]
`AggressiveSplittingPlugin` is deprecated in favor `SplitChunksPlugin` for webpack v5, I don't think we should fix this given that it will be removed in the future and deprecated now, please avoid using `AggressiveSplittingPlugin`, also I can't reproduce... Sorry for delay
