### ISSUE TITLE
ES6 import of AMD (jQuery) in webpack2 throws TypeError: __webpack_require__.i(...) is not a function exception

### ISSUE THREAD

**Issue by doberkofler** [webpack/webpack#4126]
**Do you want to request a *feature* or report a *bug*?**
a possible bug

**What is the current behavior?**
I have a problem in the latest (and greatest) webpack 2 release when trying to import jQuery 3.1.1 as a dependency. It is my understanding that with webpack 2 I'm allowed to use es6 imports with a AMD style library. I simply use `import {$} from 'jquery';` to import but the resulting bundle generated an exception `TypeError: __webpack_require__.i(...) is not a function` when executed. Using `const $ = require('jquery');` works as expected.

webpack.config.js:
```
'use strict';

const path = require('path');
const webpack = require('webpack');

function config(env) {
    const PRODUCTION = env && typeof env.production !== 'undefined';

    const PLUGINS = [
        new webpack.DefinePlugin({
            DEVELOPMENT: JSON.stringify(!PRODUCTION),
            PRODUCTION: JSON.stringify(PRODUCTION)
        })
    ];

    if (PRODUCTION) {
        PLUGINS.push(new webpack.optimize.UglifyJsPlugin({
            sourceMap: true,
            compress: {
                dead_code: true,
                unused: true,
            }
        }));
    }

    return {
        entry: {
            index: './src/index.js'
        },
        output: {
            path: path.resolve(__dirname, 'dist'),
            filename: '[name].js'
        },
        module: {
            rules: [
                {
                    test: /\.js$/i,
                    include: /src/,
                    exclude: /node_modules/,
                    use: [
                        {
                            loader: 'babel-loader',
                            options: {
                                compact: false,
                                presets: [['es2015', {modules: false}]]
                            }
                        }
                    ]
                }
            ]
        },
        plugins: PLUGINS,
        devtool: 'source-map'
    };
}

module.exports = config;
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
* Is this a bug or just not intended to work as I would expect it?
* What error does the exception TypeError: __webpack_require__.i(...) is not a function generally indicate?

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
"webpack": "2.2.0"
"babel-core": "6.22.1",
"babel-loader": "6.2.10",
"babel-preset-es2015": "6.22.0",
"jquery": "3.1.1"

**Comment by bebraw** [comment]
I think you may want `import $ from 'jquery';` or `import * as $ from 'jquery';` if I'm interpreting right.

**Comment by doberkofler** [comment]
@bebraw Absolutely correct. Tank you!
