### ISSUE TITLE
webpack.js.org - I'm is getting 404

### ISSUE THREAD

**Issue by platedodev** [webpack/webpack#4129]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Getting GitHub Pages default error 404 page not found.
**If the current behavior is a bug, please provide the steps to reproduce.**
Go to https://webpack.js.org/

**What is the expected behavior?**
Show docs / introduction and stuff
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by bebraw** [comment]
Should be fixed now. preact-compat patch release broke things. 👍
