### ISSUE TITLE
can not use webpack.optimize.UglifyJsPlugin and devtool together?

### ISSUE THREAD

**Issue by zzzgit** [webpack/webpack#4130]
```javascript
{
plugins: [
        new webpack.optimize.UglifyJsPlugin({
            // some thing
        })
    ],
devtool: 'cheap-source-map'
}
```
i config `webpack` like this
but actually  no map file will be generated
if i remove the `UglifyJsPlugin`,it does
why?

**Comment by bebraw** [comment]
I think you may want to set `sourceMap: true` for uglify as instructed in the documentation.

**Comment by zzzgit** [comment]
yes,it works
thanks
the documentation says that the default value of this key is true

**Comment by bebraw** [comment]
Which documentation are you reading? The [official one](https://webpack.js.org/plugins/uglifyjs-webpack-plugin/#options) says it's false.
