### ISSUE TITLE
why there are webpack protocol in the product result?

### ISSUE THREAD

**Issue by zzzgit** [webpack/webpack#4131]
![image](https://cloud.githubusercontent.com/assets/1060733/22403184/6cedd548-e64a-11e6-83cf-c0fd3811dd0c.png)

as you can see,there are URIs which use `webpack` protocol in the map file
is it supported by browsers?
is there some articles for the detail of this protocol?

**Comment by zzzgit** [comment]
now i know that it is just a URI which makes browser can not find the original code file
and then,the browser will use `sourceCountent`
and,the name be shown in the left panel will be the same as the value in `sources`

**Comment by unindented** [comment]
@zzzgit maybe you can close this non-issue then?
