### ISSUE TITLE
how could webpack2 support ES2015?

### ISSUE THREAD

**Issue by zzzgit** [webpack/webpack#4132]
by default,webpack2 can parse js code in ES2015
such as:arrow function,`import`
as if there is no `babel-loader` installed in the project
so i wonder how could webpack2 parse the code?

**Comment by zzzgit** [comment]
maybe because of the presence of `acorn` which is a dependacy of `webpack2`

**Comment by SpaceK33z** [comment]
Yes, partially that. There was also a bit of code added in webpack itself to enable support for e.g. arrow functions if I remember correctly. webpack doesn't transpile it like babel(-loader) does, but it lets it pass through in its original (es2015) form. When using these es2015 without babel, you need to be sure you only want to support browsers which support es2015 features.
