### ISSUE TITLE
Webpack with Electron

### ISSUE THREAD

**Issue by Nikki1993** [webpack/webpack#4136]
Hello everyone,

I've been browsing Google for a while now but still can't find a reliable guide that explains how (if even possible) to "teach" webpack not to bundle main.ts & renderer.ts but rather parse them to JS separately and leave them like that? 

Electron requires main and renderer processes to be separated and I do not wish to bundle them together. Only imports listed inside renderer.ts should be combined with renderer and so on. 

Anybody has a webpack.config.js template they could share with an explanation? 

(here is the GitHub project I am using to learn Electron and _try to build smth remotely cool :P_ for reference how things look like atm https://github.com/Nikki1993/yarn-electron-gui **without webpack**)  if that helps.

**Comment by michael-ciniawsky** [comment]
@Nikki1993 Just setup an entry 2+ entry points and you will get a bundle foreach.

**webpack.config.js**
```js
context: 'path/to/src' // e.g main.ts, renderer.ts
entry: {
  main: './main.ts',
  renderer: './renderer.ts',
  vendor: ['lib1', 'lib2']
}
output: {
  path: 'path/to/dest/',
  filename: '[name].js'
}
```

These questions are better suited for StackOverflow, so everyone with an similiar problem can discover them.

**Comment by Nikki1993** [comment]
Thanks and yea you are right, should have posted it on StackOverflow. I will post a question there and quote your answer with the link to here.
