### ISSUE TITLE
Synchronous Node API

### ISSUE THREAD

**Issue by joezimjs** [webpack/webpack#4138]
**Do you want to request a *feature* or report a *bug*?** 
Feature

**What is the current behavior?** 
Node API is only Asynchronous (I believe)

**What is the expected behavior?**
```js
const webpack = require("webpack");

const compiler = webpack({
  // Configuration Object
});

compiler.run((err, stats) => {
  // ...
});
```
This is the current Node API. I'd like a version that runs synchronously and returns an object `{err, stats}` or just `stats` and throws an error when an error occurs.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Jest allows for transformations to be done on files that are imported and instead of creating separate transformation configuration, I think the simplest thing to do would be to re-use my webpack configuration and just change the entry file to be the individual file I'm trying to compile and give the results to Jest. Unfortunately, the transformations for Jest need to be synchronous and I don't see a way to run webpack synchronously via the Node API.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
N/A

**Comment by michael-ciniawsky** [comment]
Could you show an example of that possible setup with Jest please ? :)

**Comment by sokra** [comment]
No this is very difficult, slow and probably impossible.

/wontfix

**Comment by okonet** [comment]
I actually did it on one of the projects. It's definitively not the cleanest solution but it worked.

Here is one repo: https://github.com/ColCh/jest-webpack and here is the gist what I've modified and re-used: https://gist.github.com/ninjapanzer/70b55f90edcb69c74e52

Please note that it's a hack and will probably slow down your tests significantly. Depending on what your webpack config looks like and what features you want to re-use in Jest, I'd recommend to filter out files what require the webpack pre-processor. For example, using of shims or similar.

For aliases you can use https://github.com/webpack/enhanced-resolve and write your own transformation or use https://github.com/papermana/jest-alias-preprocessor (doesn't work with webpack2 yet) or just use babel plugin: https://www.npmjs.com/package/babel-plugin-webpack-alias.

I haven't tried it yet but https://github.com/webpack/loader-runner also looks like a good direction. You still need to deasync it somehow though. @sokra do you think a sync API for this one could be possible?

**Comment by joezimjs** [comment]
@okonet Interesting. I've never heard of deasync before. I'm sure it would slow tests down considerably, but considering vue-loader seems to be the only way to get CSS Modules to work inside .vue files, it may be my only option at the moment.

Thanks a lot.
