### ISSUE TITLE
Code splitting problem with nested require.ensure

### ISSUE THREAD

**Issue by apocalyp0sys** [webpack/webpack#4142]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
Code splitting problem when using nested require.ensure. 3 split points defined, A, B - independent chunks and C depends from A & B. WIth split config below module A is included in C (but not B).

**If the current behavior is a bug, please provide the steps to reproduce.**
[Minimal repo reproducing the problem](https://github.com/apocalyp0sys/webpack-test)

Entry point script
```js
console.log('Index entry loaded');

load("C");

function load(chunk) {
    switch (chunk) {
        case "A":
            require.ensure([], () => {
                require('./A');
            }, "A");
        case "B":
            require.ensure([], () => {
                require('./B');
            }, "B");
        case "C":
            require.ensure([], () => {
                require('./A');
                require.ensure([], () => {
                    require('./B');
                    require.ensure([], () => {
                        let C = require('./C');
                        C.C();
                    }, "C")
                }, "B");
            }, "A");
    }
}

```

**What is the expected behavior?**
Module A should not be included into the C chunk

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Node v6.9.0
Webpack 2.2.1
Windows 10

**Comment by apocalyp0sys** [comment]
Looks like this problem can be worked around with CommonsChunkPlugin by adding this code to the webpack config:


```js

plugins:[
    new webpack.optimize.CommonsChunkPlugin({
        chunks: ["C","A"],
        async: "A",
    })
]
```

Not sure if it is ok to use existing chunk's name as value for async property though.

With this approach it is possible to drop nested require ensure and describe dependencies with CommonsChunkPlugin.

**Comment by kzc** [comment]
This is not specific to this particular issue...

Confirmed bugs will be closed by webpack-bot just because of inactivity? What's the sense in that?
