### ISSUE TITLE
preserved "require" and "import"

### ISSUE THREAD

**Issue by zzzgit** [webpack/webpack#4145]
webpack2
if i use import to import another module in the source code,it will be complied to __webpack_require__
but,if i use require in the source code,it will remain require after compilation
why?

**Comment by zzzgit** [comment]
```javascript
var m=require("./another.js");
//module.exports={m:m}; this will get a right result
export {m:m}  // this,will make require couldn't  be compiled to __webpack_require__
```

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
