### ISSUE TITLE
method _interopRequireDefault duplicated 

### ISSUE THREAD

**Issue by zzzgit** [webpack/webpack#4146]
```javascript
var _m = __webpack_require__(2);
var _m2 = _interopRequireDefault(_m);
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
```
if there is a `require` in the source code,there will be a corresponding `_interopRequireDefault` in the compiled code
so,they are duplicated
one is enough in the compiled code

**Comment by zzzgit** [comment]
and,i even think that `_interopRequireDefault` is not necessary,if `__webpack_require__` have correctly parse this source code and add property `__esModule` to the module object if nessary

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
