### ISSUE TITLE
passed the wrong parameter in __webpack-require__.n

### ISSUE THREAD

**Issue by zzzgit** [webpack/webpack#4147]
![image](https://cloud.githubusercontent.com/assets/1060733/22456803/a3f629e2-e7cf-11e6-882b-208e498489ff.png)

i'm using webpack 2.2.0-rc.3
in what situation these methods will be invoked?
and i found that maybe the parameter should be `module` or `getter()` in line 55

**Comment by xtuc** [comment]
Could you please use the issue template and a more explicit issue title?

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
