### ISSUE TITLE
An option to mute console logging for hot module replacement

### ISSUE THREAD

**Issue by syranide** [webpack/webpack#415]
Hot module replacement is relatively chatty in the console, which pushes away useful error messages. A way to silence the less important ones would be nice.

```
webpack-dev-server: App updated. Recompiling...
webpack-dev-server: App hot update...
Updated modules:
 - 179
XMLHttpRequest cannot load https://dev-server.../ba8920d0595009ee5d67.hot-update.json. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://login-...' is therefore not allowed access.
No Update found. 
```

Half-related, I keep getting the weird XMLHttpRequest error you see in the log above. I know that particular error is because of my patchy HTTPS tunneling, but that file seems to genuinely never exist and it doesn't seem to matter either as it works just fine despite that error? Do you have any idea what's going on? @gaearon who helped me get started with `react-hot-loader` seemed to have the "same" issue.

PS. Being able to turn off the auto-reload would be nice too (so that I can use `react-hot-loader` and still make changes to non-components without it reloading).

**Comment by victorwpbastos** [comment]
+1
