### ISSUE TITLE
Dynamic import, change function name

### ISSUE THREAD

**Issue by arshtepe** [webpack/webpack#4151]
**Do you want to request a *feature* or report a *bug*?**

Feature request

**What is the current behavior?**
Webpack 2 uses for dynamic import syntax:
```js
import(`./routes/${path}/route`)
```
But it has broken syntax highlighting in some IDE 

**What is the expected behavior?**
Change function name, for example : 
```js
_import(`./routes/${path}/route`)
```
**If this is a feature request, what is motivation or use case for changing the behavior?**
Fix syntax highlighting in IDE 

P.s I know about require.ensure, but with promises better :)

**Comment by bebraw** [comment]
I don't expect the function name to change as that's literally [the proposed standard](https://github.com/tc39/proposal-dynamic-import). The standard would have to change before webpack changes that I think.

**Comment by arshtepe** [comment]
@bebraw Thanks for info.
