### ISSUE TITLE
Mismatched options.watchOptions in main webpack function

### ISSUE THREAD

**Issue by kball** [webpack/webpack#4156]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
When options is an array, the check for options.watchOptions looks at all elements in the array, but then the internal logic only references the first element in the array.

(see https://github.com/webpack/webpack/blob/master/lib/webpack.js#L42 as compared to line 43.

**If the current behavior is a bug, please provide the steps to reproduce.**
To reproduce bug: Call webpack with an options array where the second or later object contains watchOptions, while the first does not.

**What is the expected behavior?**
compiler.watch should be called with the correct watchOptions

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Found during code review.

**Comment by kball** [comment]
(cc @zokioki)

**Comment by sokra** [comment]
Yep, this could be solved in a better way. Do you want to do a PR?

`MultiCompiler.watch` should also accept an array of watch options which are than passed to the Compilers.

`bin/webpack` should pass all watchOptions to the `MultiCompiler.watch` call.

**Comment by kball** [comment]
Sure, either @zokioki or I will take a pass on this.
