### ISSUE TITLE
Webpack 2: Director router is not working after compilation process

### ISSUE THREAD

**Issue by marcalexiei** [webpack/webpack#4157]
**Do you want to request a *feature* or report a *bug*?**
Report a bug.

**What is the current behavior?**
It seems that some parts of director router constructor function are removed causing an unexpected error. 

**NOTE**: This issue was not present in version 1.14.1.

**If the current behavior is a bug, please provide the steps to reproduce.**
https://github.com/marcalexiei/director-webpack-issue

Instructions in the readme.

**What is the expected behavior?**
No errors are generated and router init is a function.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

- Chrome 55.0.2883.95
- Safari 10.0.3
- Node 6.3.1
- Webpack 2.2.1
- MacOS 10.12.3

**Comment by sokra** [comment]
Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md).

**Comment by scinos** [comment]
For anybody looking for this issue, the StackOverflow question and answer are in http://stackoverflow.com/questions/41981735/webpack-2-director-router-is-not-working-after-compilation-process
