### ISSUE TITLE
Wrong constants.js module required into a bundle

### ISSUE THREAD

**Issue by valerybugakov** [webpack/webpack#4159]
**Do you want to request a *feature* or report a *bug*?**
Report a bug.

**What is the current behavior?**
Instead of requiring local `constants.js` Webpack requires `./node_modules/constants-browserify/constants.json`

**If the current behavior is a bug, please provide the steps to reproduce.**
Check out [example repo](https://github.com/valerybugakov/webpack-constants-bug), especially `bundle.js` file.

**What is the expected behavior?**
`src/constants.js` should be included into `bundle.js` instead of `./node_modules/constants-browserify/constants.json`

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Already discussed here https://github.com/webpack/webpack/issues/2119

**Comment by sokra** [comment]
`constants` is a node.js build-in module. node.js built-in modules have higher priority than your own modules (according to the node.js resolving algorithm).
Either rename the module or disable the built-in one (`node.constants: false`).

**Comment by valerybugakov** [comment]
@sokra Trying to google more info about `node.constants` but nothing showing up. Where `node.constants: false` should be placed to resolve this issue or where more info could be found?

**Comment by sokra** [comment]
https://webpack.js.org/configuration/node/

**Comment by valerybugakov** [comment]
@sokra thanks!
