### ISSUE TITLE
Webpack freezes if exist a tag with "<" into template in a component.

### ISSUE THREAD

**Issue by DWeikis** [webpack/webpack#4161]
**Do you want to request a *feature* or report a *bug*?**

BUG

**What is the current behavior?**

When in template of a webpack component (.vue) exist a tag with "<", webpack freezes.

**If the current behavior is a bug, please provide the steps to reproduce.**

In webpack template: `<div><</div>` or `<button><</button>`

**What is the expected behavior?**

Terminal freezing

**If this is a feature request, what is motivation or use case for changing the behavior?**

--

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Windows 10 Pro. Chrome 55.0.2883.87 m (64-bit). Node v7.4.0. Webpack 2.2.1.

PD: With ">" work.

**Comment by bebraw** [comment]
Can you set up a small repository we can run to confirm the issue?

**Comment by sokra** [comment]
Report this to the vue-loader.
