### ISSUE TITLE
Deleted modules with hmr stay cached forever

### ISSUE THREAD

**Issue by GianlucaGuarini** [webpack/webpack#4162]
**Do you want to request a *feature* or report a *bug*?**

It looks like a __bug__

**What is the current behavior?**

I am using  hrm as recommended on the [webpack site](https://webpack.js.org/guides/hmr-react/)
It seems that if a file gets deleted it still exists in the other modules where it was previously imported. No import error gets thrown.

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/GianlucaGuarini/webpack2-hmr-test

**What is the expected behavior?**

Webpack should throw an error telling the user that the imported file doesn't exist.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

webpack@2.2.1
webpack-dev-server@2.2.0
node v6.3.0

**Comment by GianlucaGuarini** [comment]
I just was able to check the @sokra patch and now everything seems to work fine this bug was fixed. Thank you so much looking to installing the new webpack release

**Comment by sokra** [comment]
Great now I only have to force the CI to accept my changes...

**Comment by GianlucaGuarini** [comment]
@sokra unfortunately the issue persists if instead o deleting files you try to delete a folder containing your import :(

**Comment by GianlucaGuarini** [comment]
ok so @sokra you patch + updating chokidar to the latest version (1.6.1) [here](https://github.com/webpack/watchpack/blob/08d4759606262c4216bf3b966163debb08553189/package.json#L41) mitigates the `unlinkDir` problem
