### ISSUE TITLE
Webpack bundles wrong dependency ID

### ISSUE THREAD

**Issue by andreyluiz** [webpack/webpack#4163]
I don't know how exactly to explain that but, in my production build, webpack is requiring the wrong dependency ID for a library I use called jumpstate.

In my component I import code from the library:

**Root.js**
```javascript
import { CreateJumpstateMiddleware } from 'jumpstate';
```

In webpack config I put this library in the vendor chunk.

**webpack.config.prod.js**
```javascript
entry: {
    app: path.resolve(SRC_PATH, './client/index.js'), // index.js imports Root.js
    vendor: [
        'jumpstate',
        // [...]
    ]
},

output: {
    path: DIST_PATH,
    chunkFilename: '[name].[chunkhash].js',
    filename: '[name].[chunkhash].js'
},

plugins: [
    new webpack.optimize.CommonsChunkPlugin('vendor', '[name].[chunkhash].js'),
],
```

This generates two files in my `dist` directory: `app.[hash].js` and `vendor.[hash].js`.

When I run this code, my browser points an error:

```
Uncaught TypeError: (0 , _jumpstate.CreateJumpstateMiddleware) is not a function
```

Looking in the generated code, webpack generates this for the `jumpstate` import:

```
var _jumpstate = __webpack_require__(313);
```

If I am right, the number corresponds to the resource ID in webpack's output, am I right?

In this case, 313 is not jumpstate. It's another library:

```
[313] ./~/react-dom/lib/ReactComponentEnvironment.js 1.3 kB {6} {6} [built]
```

What is going wrong? Why webpack is importing the wrong resource?

**EDIT (IMPORTANT):**
I found out what is happening but I don't know why. Webpack is not generating a single `app.[hash].js` file. It is generating two files. The first one imports jumpstate correctly. The second one does not, and my manifest file is pointing to the second one. Does someone knows why?

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by andreyluiz** [comment]
Okay! I will dig a little more. If I still got stuck I create a simulation.

Thank you. :)

**Comment by seuck** [comment]
Any update on this issue?
I have the same error.

Here some extracts of my web pack.config.js:

`const entryConfig = {}

const babelConfig = JSON.parse(
  JSON.stringify(babel)
    // note that `"env",` (with comma) is replaced as it is uniquely pointing
    // to the babel-preset-env-plugin whereas as only `"env"` could also be
    // the node environment configuration key
    .replace(new RegExp(`"env",`, `g`), `"${pathBabelPresetEnv}",`)
    .replace(
      new RegExp(`"module-resolver"`, `g`),
      `"${require.resolve(`babel-plugin-module-resolver`)}"`
    )
)

glob.sync(`${paths.entry_files_root}/**/*${values.entry_filename_ending}.js`)
  .forEach((entryFilePath) => {
    // e.g. entryFilePath:
    //  '../src/main/jcr_root/apps/mam/web/components/mycomponent/mycomponent.entry.js'

    const key = path.dirname(path.relative(paths.project_root, entryFilePath))
    // key will then contain the file path with paths.project_root as the base directory.
    // e.g. 'mamcom-web-components/mamcom-web-components-package/src/main/jcr_root/
    //      apps/mam/web/components/mycomponent'

    entryConfig[key] = entryFilePath
  })

module.exports = {
  entry: entryConfig,
  module: {
    rules: [
      {
        // do not transpile the listed libraries with babel as they do not need it
        include: [
          absolutePathToFrontend,
          `${absolutePathToNodeModules}/@nc/extend`,
          `${absolutePathToNodeModules}/@nc/pubsub`,
          `${absolutePathToNodeModules}/material-components-web`,
          absolutePathToEntryFilesRoot
        ],
        test: /\.js$/,
        use: {
          loader: pathBabelLoader,
          options: babelConfig
        }
      },
      ...
    ]
  },
  output: {
    filename: `[name]/${values.bundle_filename_ending}.js`,
    path: absolutePathToProjectRoot
  },
  ...`
