### ISSUE TITLE
[bug] [2.0] Unable to append paths to externals.

### ISSUE THREAD

**Issue by trusktr** [webpack/webpack#4167]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Setting an external, f.e.

```js
    externals: [
        '@common',
    ],
```

then trying to import something like

```js
import Foo from '@common/path/to/Foo'
```

fails because webpack seems to ignore the fact that `@common` is external, and tries to resolve the module `@common/path/to/Foo` but obviously it can't find it because I'm expecting it to be loaded by RequireJS when Webpack's `libraryTarget` is set to AMD. I.e., I'm expecting Webpack to leave it alone and wrap the bundle so it starts with something like

```js
define(["@common/path/to/Foo"], function(__WEBPACK_EXTERNAL_MODULE_88__) { return /******/ (function(modules) { // webpackBootstrap
```

where `@common/path/to/Foo` is something that RequireJS knows how to handle perfectly fine.

I can work around the problem by setting the externals in Webpack to be

```js
    externals: [
        '@Foo',
    ],
```

then I can configure RequireJS to resolve `@Foo` by configuring the path that I need:

```js
require.config({
    paths: {
        @Foo: '/common/path/to/Foo'
    }
})
```

but this is not ideal because now I have to go and hard code each file that I need to import as an external from a common place, as in

```js
require.config({
    baseUrl: '/anything/blah/blah', // this value does not matter because the following paths are not relative to this
    paths: {
        @Foo: '/common/path/to/Foo',
        @Bar: '/common/path/to/Bar',
        @Baz: '/common/path/to/something/Baz',
        @Lorem: '/common/there/is/Lorem',
    }
})
```

Another way to work around this is to instead set only a single path in require config, and then hard code all the files in webpack config, which is also tedious and redundant:

```js
// require config
require.config({
    paths: {
        @common: '/path/to/common/js'
    }
})
```

```js
    // webpack config
    externals: [
        '@common/path/to/Foo',
        '@common/path/to/Bar',
        '@common/path/to/something/Baz',
        '@common/there/is/Lorem',
    ],
```

**If the current behavior is a bug, please provide the steps to reproduce.**

I think you get the idea from my examples.

**What is the expected behavior?**

Webpack should understand that when an external `@common` is specified, that it should not need to resolve modules like `@common/path/to/Foo` from source files, so that an external handler can load the needed dependencies, and in the configuration we only need to simply write

```js
// require config
require.config({
    paths: {
        @common: '/path/to/common/js'
    }
})
```
```js
    // webpack config
    externals: [
        '@common'
    ],
```

and the rest is inside source file module import statements as in

```js
import Foo from '@common/path/to/Foo'
```

**If this is a feature request, what is motivation or use case for changing the behavior?**
n/a?

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

webpack 2.2.1

**Comment by trusktr** [comment]
Or did I just miss how to do this?

**Comment by TheLarkInn** [comment]
Is this supposed to be `resolve.alias` instead?

**Comment by trusktr** [comment]
@TheLarkInn No, these are externals, not to be bundled by Webpack. `resolve.alias` is for files that will be bundled by Webpack, right?

**Comment by GGAlanSmithee** [comment]
@TheLarkInn there might be a similar but with `alias`. I am experiencing https://github.com/webpack/webpack/issues/4160 too.

**Comment by sokra** [comment]
``` js
externals: /^@common($|\/)/
```

**Comment by trusktr** [comment]
I solved it by using a function and `callback()`, matching to a regex. Didn't know I could also supply a regex directly. Thanks!
