### ISSUE TITLE
[feature request] Ability to add custom `libraryTarget`s.

### ISSUE THREAD

**Issue by trusktr** [webpack/webpack#4171]
**Do you want to request a *feature* or report a *bug*?** Feature

**What is the current behavior?**

We can specify `libraryTarget`s to, for example, output AMD modules when it is set to `amd`. I'd like to set it to [`imvu`](http://github.com/imvu/imvujs) which is a custom module format with accompanying module loader that is similar to `RequireJS`.

f.e. 

```
module({Foo: './Foo'}, function(imports) {
  console.log(imports.Foo) // imports object contains request imports.
})
```

The only difference really is a depency map rather than list, and the body function receives an object with the dependencies.

**If the current behavior is a bug, please provide the steps to reproduce.** n/a

**What is the expected behavior?** n/a

**If this is a feature request, what is motivation or use case for changing the behavior?**

It'd be nice to define a custom library target to allow webpack bundles to work under a custom system like the one I mentioned.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Webpack 2.2.1

**Comment by trusktr** [comment]
As a workaround, I can set libraryTarget to amd, then run a post-build transform from to convert define() to module().

But this doesn't work in watch mode. Is there a way to hook into it?

**Comment by sokra** [comment]
Copy the AMD Library plugin and tune it to your needs. Leave libraryTarget empty and use your plugin instead.

**Comment by trusktr** [comment]
I see!

Is there a way to get the AST before the asset is made?

I'm currently pugging into `emit` and making an AST from the asset then reassigning the asset on `compilation.assets`, but I would think there's a better way than having to make new ASTs?
