### ISSUE TITLE
Unexpected token stopped deploying wepback.js 

### ISSUE THREAD

**Issue by EdwOK** [webpack/webpack#4174]
**Do you want to request a *feature* or report a *bug*?** Bug 

**Link:** [Stackoverflow question](http://stackoverflow.com/questions/41987472/webpack-aws-recently-stopped-deploying-errors-in-webpack-js)

**What is the current behavior?** Yes

**If the current behavior is a bug, please provide the steps to reproduce.** Deployment

_SyntaxError: Unexpected token >_ `webpack.js:186 outputOptions.children = options.map(o => o.stats);`

**What is the expected behavior?** Successful deployment

**If this is a feature request, what is motivation or use case for changing the behavior?** Will be fixed now!

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.** Node 6.5, Webpack 2.2.1

**Comment by sokra** [comment]
Update node.js

**Comment by tsv2013** [comment]
I've updated node to 7.5 and still have the error on travis. So what's the solution?

**Comment by dmitrykurmanov** [comment]
And why in bin/webpack.js we have arrow function? 

`	if(Array.isArray(options) && !outputOptions.children) {
		outputOptions.children = options.map(o => o.stats);
	}`

This is only one place with es6. Is it ok ?

**Comment by EdwOK** [comment]
I think that webpack.js implemented with ES6 and also that the other places doesn't can reach (when build),
why is it?

**Comment by tsv2013** [comment]
It works locally with node > 4, and webpack 2.2.0 but fails on travis ci :(

**Comment by tsv2013** [comment]
@sokra can you please ensure webpack works ok with Travis CI?

**Comment by dmitrykurmanov** [comment]
@EdwOK with webpack 2.2.0-rc.3 I have another error:

/home/travis/build/surveyjs/surveyjs/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:6
 const createInnerCallback = require("./createInnerCallback");
^^^^^
SyntaxError: Use of const in strict mode.

**Comment by EdwOK** [comment]
@dmitrykurmanov 
I have also had this error, after update node.js didn't work :( 
(fallback to webpack v1)
Why issue is closed?

**Comment by tsv2013** [comment]
@EdwOK  - we (with @dmitrykurmanov) have fixed our problem: the thing was that we use "concurrently" on TravisCI. After we've got rid of it, the error has gone.

**Comment by fesaza** [comment]
Did you loaded the babel-core module on web pack file?

**Comment by EdwOK** [comment]
Ofc, but I can used reactjs and some feature of ES-7

**Comment by ajritch** [comment]
@tsv2013 @dmitrykurmanov 
Why has this issue been closed? The original error posted by @EdwOK still seems to be an issue.
Using node v7.6.0, webpack v2.2.1 (also tried v2.4.1), I'm still getting the same error during deployment:
```
/srv/www/omg_ladi_staging/releases/20170425212105/node_modules/webpack/bin/webpack.js:186
outputOptions.children = options.map(o => o.stats);
^^
SyntaxError: Unexpected token =>
```

Everything works just fine locally. Please advise.

**Comment by tsv2013** [comment]
@ajritch I don't know - why this issue was closed. I and @dmitrykurmanov are not maintainers of this repo. You should address this question to @sokra

**Comment by EdwOK** [comment]
@ajritch This problem was fixed, the solution is to remove the cache of package npm, upgrade to node >=7.5 && npm >= 4.1, also for build I use Visual Studio (configure Visual Studio to use the global external web tools instead of the tools that ship, go to [cookbok](https://angular.io/docs/ts/latest/cookbook/visual-studio-2015.html)
