### ISSUE TITLE
cheap-module-source-map doesn't generate sourcesContent

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack#4176]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

No `sourcesContent` is generated in the source map if `UglifyJsPlugin({ sourceMap: true })` is enabled and `devtool: 'cheap-module-source-map'` is used. `cheap-source-map` works.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Clone https://github.com/survivejs-demos/webpack-demo
2. Check out `source-map-bug`
3. `npm i`
4. `npm run build`
5. Examine `build/app.js.map`, note above.
6. Tweak `webpack.config.js` (contains comments how).

**What is the expected behavior?**

It should generate `sourcesContent` like `cheap-source-map` option.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Webpack ^2.2.0. Node 6, macOS.

**Comment by Freddie-Pike** [comment]
Is this still broken?

**Comment by sokra** [comment]
This is webpack 2. Probably this is already fixed. If not, open a new issue.

**Comment by sokra** [comment]
@Freddie-Pike If you still see this issue, please create a new issue with repro repo :)

**Comment by sokra** [comment]
@alexander-akait may have a repro too?

**Comment by sokra** [comment]
Ok Update: This is expected behavior. `cheap-` devtools can't be used in `production` mode, as they only map lines and do not do column mapping. When minimizers optimize the code they usually emit only a single line. This can't be mapped by `cheap-` devtools.
