### ISSUE TITLE
Feature Request: Build Time Rendering

### ISSUE THREAD

**Issue by jantimon** [webpack/webpack#4177]
It would be nice to improve the current state of BTR (https://github.com/jantimon/html-webpack-plugin/issues/579)

Right now there a following open issues:

1. Extract Text Plugin does not work in child compilations (https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/389)
2. `__dirname` does not work (https://github.com/webpack/webpack/issues/2978)
3. `__file` does not work (https://github.com/webpack/webpack/issues/2978)
4. no way to define different globals for browser and build time rendering  (https://github.com/webpack/webpack/issues/2979)

**Comment by sokra** [comment]
Could you take a look at the PR?

**Comment by jantimon** [comment]
Wow this might fix #2979 and maybe also #2978 right?

**Comment by sokra** [comment]
And you can match different loaders on the modules in the child compilation. I.e. for the html plugin. style-loader -> null-loader

**Comment by jantimon** [comment]
Wow that would be awesome - I'll give it a try asap I'm done with the webpack 1 to webpack 2 upgrade.
