### ISSUE TITLE
LimitChunkCountPlugin ignores possibly wrong maxChunks value

### ISSUE THREAD

**Issue by swernerx** [webpack/webpack#4178]
For my local application I tried setting up webpack to only produce the main chunk when bundling the NodeJS part of my application.

Interestingly I assumed that `LimitChunkCountPlugin` accepts `maxChunks: 0` as a value for not adding additional chunks. I think I misinterpreted the concept behind it because what I desire works exactly like this when using `maxChunks: 1`. Ignoring the `0` value though lead me to the conclusion that there must be a bug in Webpack for not correctly supporting the new dynamic `import()` together with `LimitChunkCountPlugin`.

I have two suggestions here:

- Document the concept and value value range of `LimitChunkCountPlugin`.
- Explain that even the main (or entry) chunk is regarded as a chunk. I assumed chunks are the name of everything splitted out of main (excluding main).
- Throw an error when `maxChunks` is missing or could not be dealt with correctly. At least throw for any value smaller than `1`.

Thanks!

**Comment by sokra** [comment]
yep, send PRs.

**Comment by TheLarkInn** [comment]
<img width="1652" alt="screen shot 2017-02-03 at 11 51 02 pm" src="https://cloud.githubusercontent.com/assets/3408176/22616096/a94de170-ea6b-11e6-8eb5-9b43745e7a34.png">
Yup looks like they all just simple return. 

@sokra lets just jot down best way to handle each case. 

maxChunks < 1: Throw Error? 
maxChunks: undefined: Default to 1?
