### ISSUE TITLE
Opt-in to disable page reload when using HMR

### ISSUE THREAD

**Issue by gaearon** [webpack/webpack#418]
When HMR update fails, it forces a page reload.

This may be desirable for consistency, but most of the time this is caused by a simple syntax error, and I'd like to error to just appear in console. When I fix the error, another HMR update will come and "fix" the system anyway.

When [react-hot-loader](https://github.com/gaearon/react-hot-loader) used a pitch loader, it just [put HMR-updated require inside a try-catch](https://github.com/gaearon/react-hot-loader/blob/37edb096e0570491a7cbebcbe35add9b64010bf2/index.js#L24).

Now that I [refactored it](https://github.com/gaearon/react-hot-loader/blob/02c971305360b81e23d43170162f59b8658113e3/index.js#L20) to be a simple loader (no pitching), I no longer have the ability to `catch` syntax errors in the breaking module.

Can we have a way to disable page reloads altogether? I guess making it opt-in and logging something like "The system is in inconsistent state" is fine with me.

cc @syranide

**Comment by gaearon** [comment]
It seems like I've been doing a silly thing for a long time. If you use React Hot Loader with `hot/only-dev-server`, there's no need for `NoErrorsPlugin`. If you make a syntax error, it'll print it in the console, but the next reload will still work:

![screen shot 2015-05-23 at 1 23 05](https://cloud.githubusercontent.com/assets/810438/7781063/58b5ab46-00f0-11e5-9f22-380027d1457f.png)

Which is awesome because with `NoErrorsPlugin` it just prints "Nothing hot updated." which can be misleading when you have an error. (Yeah I know I was misusing it, sorry!)

**Comment by gaearon** [comment]
Oh well, I was wrong. HMR breaks if you don't use NoErrorsPlugin *and* misspell a dependency name. Bummer. I'll probably create an issue because I'm not sure why it happens this way.

**Comment by sdtsui** [comment]
Just wanted to say this discussion is awesome, helped me understand webpack better, and saved me a few hours at work.   Thanks all.

**Comment by koddo** [comment]
The `NoErrorsPlugin` doesn't work for me. When I have an error in my code, the webpack still tries to send something to the browser, like `http://localhost:3000/b206461c30a0ae51ec9c.hot-update.json`.
But this file doesn't exist and I have `historyApiFallback=true`, so the server just sends the index.html, then the browser says `Update check failed: SyntaxError: Unexpected token < in JSON at position 0 at XMLHttpRequest.request.onreadystatechange`.
And after that the HMR stops working.
Any way to make `NoErrorsPlugin` to only send updates when there are no errors and warnings?

**Comment by koddo** [comment]
I'm not alone having the issue with the noErrorsPlugin: https://github.com/webpack/webpack-dev-server/issues/655

When using the noErrorsPlugin, after making an error and then fixing it, module.hot.status() returns "check", when it should return "idle". So, basically it gets stuck somewhere, I can't figure out.

**Comment by mikeengland** [comment]
@koddo sadly the fix for this issue only went into Webpack 2 beta. I do understand bug fixes going into 2 so it gets out the door more quickly but I am reliant on webpack v1 and so are a lot of people who feel more comfortable on a stable version.

**Comment by mikeengland** [comment]
I haven't looked at the commit that fixes it in version 2, so I'm not sure how complex backporting the fix would be.

**Comment by koddo** [comment]
@mikeengland, I've seen it, and that would be hard, for sure. But my monkey patch works for me. Will use it until v2.

**Comment by wallflips** [comment]
I know it's immature but I temporarily solved it by placing a return in the beginning of reloadApp() :P

**Comment by gaearon** [comment]
Four years later, @sokra showed me a solution that seems to do exactly what I wanted:

```js
function hotErrorHandler(err) {
  require.cache[module.id].hot.accept(hotErrorHandler);
}
module.hot.accept(hotErrorHandler);
```

😄

**Comment by gaearon** [comment]
https://mobile.twitter.com/dan_abramov/status/1125926905331552263

**Comment by sokra** [comment]
It's never too late...

**Comment by Axxxx0n** [comment]
> For posterity, this is what I use for the moment:
> 
> ```
> function check() {
>   module.hot.check(function(err, updatedModules) {
>     if (updatedModules) {
>       check();
>     }
>   });
> }
> window.onmessage = function(event) {
>   if (event.data === 'webpackHotUpdate' && module.hot.status() === 'idle') {
>     check();
>   }
> };
> ```

@syranide where to actually put this code? If I put it inside entypoint,  code from [dev-server.js] (https://github.com/webpack/webpack/blob/master/hot/dev-server.js) interferes and `module.hot.status()` is never idle.

I came to this (module.hot.status() is always "check"):
```
if (module.hot) {
    module.hot.accept()
    function ch() {
        module.hot
            .check()
            .then((updatedModules) => {
                console.log('updated')
            })
            .catch((e) => {
                console.log('err: ', e)
            })
    }

    window.onmessage = function (event) {
        if (typeof event.data === 'string' && event.data.indexOf('webpackHotUpdate') === 0) {
            console.log('message received', module.hot.status())
            ch()
        }
    }

```

**Comment by nealoke** [comment]
@gaearon I've been trying for a couple of hours to get this working but I can't. Is there no way to have an `onError` handler for the code below?

```js
if (module.hot) {
	module.hot.accept("./server", () => {
		serverInstance.close();
		serverInstance = createServer();
		return serverInstance;
	});
}
```

**Comment by nealoke** [comment]
For people trying to figure out how to correctly `catch` the error on a `node` server. It basically tries to import the updated file and when it doesn't work simply logs the error and carries on like normal.

```js
let serverInstance = require("./server").createServer();

if (module.hot) {
	module.hot.accept("./server", () => {
		try {
			const updatedImport = require("./server");
			serverInstance.close();
			serverInstance = updatedImport.createServer();
		}
		catch (err) {
			console.log(err);
		}
	});
}

```
