### ISSUE TITLE
Tree Shaking with require.context

### ISSUE THREAD

**Issue by pedronauck** [webpack/webpack#4181]
Hy Guys,

I have just a simple question. If I use `require.context` to automatic import my files liked that:

```js
const exportFile = (path, req) => {
  const [, componentName] = path.match(/\.\/(.*)\/index.js?$/i);
  const component = req(path);

  module.exports[componentName] = component.default || component;
};

const requireAll = (ctx) =>
  ctx.keys().forEach(path => exportFile(path, ctx));

requireAll(require.context('./', true, /\.\/(.*)\/index.js?$/i));
```

Webpack will make Tree Shaking as well?

Thanks!

**Comment by sokra** [comment]
tree shaking only works with ES `import` and `export`. `require.context` != `import`

**Comment by pedronauck** [comment]
thanks @sokra :)

**Comment by andy3520** [comment]
is there any workaround to archive this? require.context is really useful but cannot use tree shaking is a big disadvantage.
