### ISSUE TITLE
Using webpack in combination with gulp

### ISSUE THREAD

**Issue by stephan-v** [webpack/webpack#4182]
I was wondering if anybody has a good way to combine webpack with Gulp. 

The reason I ask here because there seems to be an underwhelming amount of knowledge of the regular communities like gitter and stackoverflow. 

I would preferably run webpack with something like `npm run dev` while calling webpack and gulp from there. The problem that arises with this kind of workflow is that I would double the output that I would get. Output from gulp and webpack on top of eachother.

Is there a way to merge these outputs so I could run them side-by-side and a decent manner?

**Comment by rafde** [comment]
It looks like you forgot to read
> Please ask questions on StackOverflow or the webpack Gitter (https://gitter.im/webpack/webpack).

as you posted this issue.

**Comment by bebraw** [comment]
Maybe https://www.npmjs.com/package/webpack-stream helps.

**Comment by stephan-v** [comment]
@rafde Except for the fact that the knowledge of webpack on stackoverflow boils down to a bare minimum. I would love to ask my question there but I see way too many open webpack questions so I don't know what to do here. Besides I feel this might be a valid place since a lot of other developers might want to see this answered here.

**Comment by bebraw** [comment]
It's simply the current policy. The tracker is overflowing with technical issues and adding support to that would make it even worse.

There's also an active [Gitter channel](https://gitter.im/webpack/webpack) you can try for more immediate feedback and likely some other forums, like Reactiflux, too.
