### ISSUE TITLE
Error when importing constants.js from parent, in a folder with a package.json

### ISSUE THREAD

**Issue by ehtb** [webpack/webpack#4183]
bug

Requiring `constants.js` from a parent directory when the child directory contains a `package.json` return an object containing: 
```
DH_CHECK_P_NOT_PRIME:1
DH_CHECK_P_NOT_SAFE_PRIME:2
DH_NOT_SUITABLE_GENERATOR:8
DH_UNABLE_TO_CHECK_GENERATOR:4
E2BIG:7
EACCES:13
EADDRINUSE:48
...
```

On the server this works fine (env = node).

**If the current behavior is a bug, please provide the steps to reproduce.**

Github repo with error: https://github.com/ehtb/webpack-constants-import-bug
Main gist: https://gist.github.com/ehtb/ab77e08a92eb4cf38f83c74ff067e0db

**What is the expected behavior?**

import the constants normally

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Webpack: 2.2.1
Node: 7.4.0

#4159 reports a similar problem with loading constants, but with an implicit path `require('constants')`. The difference here is that the path is explicit `require('../constants')`.

**Comment by sokra** [comment]
It's a bug.
