### ISSUE TITLE
Webpack 2 hangs on all projects after update

### ISSUE THREAD

**Issue by benduran** [webpack/webpack#4184]
# Bug

As the title suggests, I've just recently cleaned out my `node_modules` folders in a number of different projects as I update my dependencies. I've been using Webpack2 for several weeks now with good results.

After doing a fresh install of Webpack, literally every single one of my project builds hangs on a random file in the project. Sometimes it hangs when importing a library, other times it hangs on a file I've written.

This is typically what my CMD ends up looking like:
![image](https://cloud.githubusercontent.com/assets/6392223/22570912/4df7b054-e952-11e6-8ec4-a89cee378dcf.png)

I can provide webpack config details, if required. 

## Steps to repro:
1. Already have a `webpack.config.js` defined with the new V2 syntax
2. Clean out your `node_modules` folder (`rm -rf node_modules`)
3. `npm install`
4. Build your project with webpack. Watch the CLI as it hangs arbitrarily.

## Additional Information:
- OS: Windows 10 Enterprise on my Desktop, Windows 10 Pro on my Laptop.
- Node: 7.5.0
- Webpack: 2.2.0

**Comment by dcai-medallia** [comment]
Have the same issue here -- webpack starts to hang after re-install node modules in my repo.

**Comment by moodysalem** [comment]
![image](https://cloud.githubusercontent.com/assets/7897876/22571946/a892138c-e967-11e6-822d-18eb10846593.png)

**Comment by TheLarkInn** [comment]
Just out of curiosity, what does "clean up my node modules mean?"

**Comment by moodysalem** [comment]
@TheLarkInn I'd think `rm -rf node_modules`

**Comment by insin** [comment]
See https://github.com/ternjs/acorn/issues/499

**Comment by tricoder42** [comment]
@insin Indeed, installing `acorn@4.0.4` instead of `4.0.5` fixes this problem even when I don't use `acorn` directly.

**Comment by oieduardorabelo** [comment]
core-js is broken too, https://github.com/zloirock/core-js/issues/277

another #leftpad ? ahahah

**Comment by benduran** [comment]
@TheLarkInn Updated the original issue to be clearer. Thanks for sort of pointing that out :)

**Comment by TheLarkInn** [comment]
No prob. So I assume we leave our acorn dep unpinned and patch should fix right?

**Comment by madaz** [comment]
`webpack@2.2.1`

@oieduardorabelo I was also getting a "Parenthesized pattern" with a project file `/core-js/library/modules/_export.js` dependency.

I installed acorn@4.0.7 and it fixed my build.

**Comment by oieduardorabelo** [comment]
yrp, fixed on acorn@4.0.7, last release

**Comment by TheLarkInn** [comment]
Alright going to close this. Reason we didn't see this is because we are using yarn to lock deps (is my hypothesis).
