### ISSUE TITLE
:q

### ISSUE THREAD

**Issue by rodolfospalenza** [webpack/webpack#4185]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by rodolfospalenza** [comment]
Sorry for this issue.
It was opened unintentionally. :/

**Comment by bebraw** [comment]
No worries. I figured that much. Vim. 👍
