### ISSUE TITLE
cheap-module-eval-source-map causing reference errors related to module.export

### ISSUE THREAD

**Issue by laggingreflex** [webpack/webpack#4186]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

When using `cheap-module-eval-source-map`, and require modules that are defined like this:

**`app/node_modules/my-module/index.js`**:

```
module.exports = myFun // << Uncaught ReferenceError: myFun is not defined
function myFun(){...}
// or 
function myFun(){...}
module.exports = myFun // << Uncaught ReferenceError: myFun is not defined
```

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/laggingreflex/webpack-4186

**What is the expected behavior?**

these modules should work

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

webapck 2.2 node 7.4 win10

**Comment by laggingreflex** [comment]
Sorry, couldn't repro myself in another project. Must be related to something else. Closing.

**Comment by laggingreflex** [comment]
It was due to `cheap-module-eval-source-map`. Reopening. Created a repro: https://github.com/laggingreflex/webpack-4186

**Comment by bebraw** [comment]
#4176 has to do with cheap source maps too. I wonder if these two are related somehow.

**Comment by laggingreflex** [comment]
@bebraw `cheap-module-source-map`  actually works in my case.

**Comment by bebraw** [comment]
@laggingreflex Ok, "cool". It sounds like a different problem then. 👍

**Comment by sokra** [comment]
https://twitter.com/wSokra/status/827431479206670336

working on it. it's a browser bug.

**Comment by sokra** [comment]
chrome bug, fixed in chrome 57
