### ISSUE TITLE
Provide possibility to configure `externals` using root module/package

### ISSUE THREAD

**Issue by maximusk** [webpack/webpack#4195]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**

At the moment, if I want to add named module into `externals`, I have to specify full path:

```
externals: {
    'lib/@angular/core': 'common lib/@angular/core',
    'lib/@angular/platform-browser': 'common lib/@angular/platform-browser',
    'lib/@angular/platform-browser-dynamic': 'common lib/@angular/platform-browser-dynamic'
},
```

**What is the expected behavior?**

It would be great if I could specify a "package", and all modules inside of it would be added automatically to externals. So that the example above could be shortened to:

```
externals: {
    'lib/*': 'common lib/*',
},
```

**If this is a feature request, what is motivation or use case for changing the behavior?**
This may be required if:
- I've got a lot of named modules inside a "package"
- I don't know all named modules used in the script but I know that they all live inside a "package"

**Comment by sokra** [comment]
You can use a regular expression or function as argument to externals.

**Comment by maximusk** [comment]
Thanks for your answer. I've checked [this documentation page](https://webpack.js.org/configuration/externals/#regex) on externals with regexes, but it says:

>  TODO - I think its overkill to list externals as regex.
Can you please show here how regexes can be applied to the use case I showed in my original post? I then can update the docs

**Comment by sokra** [comment]
if the regex matches with original request is used as external. `output.libraryTarget` is used as type (as always if no type is specified.

``` js
output: { libraryTarget: "commonjs2" },
externals: [
  /abc/,
  /^xyz\//
]
```

```
import "abc" -> require("abc")
import "ccc/abc/def" -> require("ccc/abc/def")
import "xyz/one" -> require("xyz/one")
import "xyz" -> not external
```

**Comment by maximusk** [comment]
Great, thanks. Any chance to use to capturing groups to get only part of module name? This would allow to reconfigure the module, something like this:

externals: [
  /xyz\/(.*)/:'something/$1'
]

import "xyz/one" -> require("something/one")
