### ISSUE TITLE
BenchmarTestCases: Reduce variance by running tests against both commits to compare

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack#4198]
As I was sharing our BenchmarkTestCases with @developit, he suggested that we could increase our comparison accuracy by running tests against both "original" commit, and "current" commit during CI.

In theory, could reduce the amount of variance between when original ran and current ran.

**Comment by developit** [comment]
Would be a pretty robust comparison mechanism. You can also/alternatively use a common (3rd) baseline to compute a tick value for each run and then normalize all runs against their tick values to offset variance between runs.

**Comment by TheLarkInn** [comment]
![screen shot 2017-02-03 at 10 52 41 pm](https://cloud.githubusercontent.com/assets/3408176/22615830/865bf790-ea63-11e6-86c6-85440a5159d1.png)
Okay I was doing a little bit poking and maybe we were incorrect, it looks like it pulls down each and runs the benchmark against them

**Comment by TheLarkInn** [comment]
I'll leave open for when @sokra wakes up a bit later.

**Comment by developit** [comment]
Looks like it's already doing the best thing. Hat tip to @sokra there for sure, this is really well thought out.

**Comment by TheLarkInn** [comment]
We could modify this issue to instead make this a reusable package.

**Comment by developit** [comment]
Good idea. I think the git stuff is actually pretty workable for most people.

**Comment by sokra** [comment]
It already runs against HEAD, PR base and latest tag.

I would really like this to be a separate package. The mocha intergration is more a hack. Also it would be great to interleave test runs because CI performance seem to vary over time.

**Comment by developit** [comment]
@sokra any thoughts on using a noop-like test to calculate a "tick" value? It'd provide a way to track speed variance across runs.
