### ISSUE TITLE
import() breaks SSR with react

### ISSUE THREAD

**Issue by threepointone** [webpack/webpack#4199]
**Do you want to request a *feature* or report a *bug*?**
A bug

**What is the current behavior?**
a combination of import() promises, webpack dependency resolution, and SPA architectures breaks SSR for react in webpack 2. 

**If the current behavior is a bug, please provide the steps to reproduce.**

this is the scenario. 

I'm writing a server that serves 2 routes, `/a`, and `/b`, rendering components `<A/>` and `<B/>` from files `./a.js` and `./b/js`. 

On the server, for both routes, I'd like to render the html beforehand. 

On the front end, I'd like to load bundles such that the server rendered page has its javascript available to pick up from server rendered html, but dynamically load the other chunk when it navigates to the otehr route. 

That's all. My contention is that this is broken with `import()/require.ensure()` being a promise.

Let's dive into some code. First, the html 'templates' that's hosting these scripts, `a.html` and `b.html`. 

```html
<!DOCTYPE html>
<html>
<body>
  {{ html }}
  <script src='a.chunk.js'></script>
  <script src='bundle.js'></script>
</body>
</html>
```
```html
<!DOCTYPE html>
<html>
<body>
  {{ html }}
  <script src='b.chunk.js'></script>
  <script src='bundle.js'></script>
</body>
</html>
```

Simple enough. Here, we're assuming a template system that uses handlebar style curlies, but you could substitute your own. 

Of note, we preload the chunks matching the route, hoping they're available 'instantly'. This is key for react to 'pick up where it left off' when rendering over SSR output. We'll talk about how those chunks are made in a bit.

Let's look at the components
```jsx
// a.js
export default class A extends React.Component {
  render() {
    return <div>
      we on page A! <br/>
      <Link href='/b'>go to page B</Link>
    </div>
  }
}

// b.js
export default class B extends React.Component {
  render() {
    return <div>
      we on page B! <br/>
      <Link href='/a'>go to page A</Link>
    </div>
  }
}
```

we're assuming the use of react-router@4 here, but you could setup your own pushState based system.

Now let's look at our root component. We're using [react-modules](https://github.com/threepointone/react-modules) to simplify the boilerplate.  
```jsx
class App extends React.Component {  
  render() {
    return <div>
      <Match pattern='/a' chunkName='a' render={() => 
        <Modules load={require('./a')}>{
            A => A ? 
              <A.default/> : 
              <div> loading... </div>
          }</Modules>
      } />
      <Match pattern='/b' chunkName='b' render={() => 
        <Modules load={require('./b')}>{
            B => B ? 
              <B.default/> : 
              <div> loading... </div>
          }</Modules>
      } />
    </div>
  }
}
```

Alright, now let's talk about the mechanics. Assume we make a request for `/a`.

- On the server-side, we use a sync require to get and render `<A/>`. 
- On the client side, to be able for pick up where the server left off, we need to have the `A` available immediately. So we first load `a.chunk.js`, and then the entry script.
- With webpack 1, require.ensure would then resolve *immediately*, and render the content as expected. 
- However in webpack 2, because of the "always async" nature of promises, the module will not be availble for one tick. This leads to a mismatch, and it'll try to render 'loading' for one frame, breaking SSR. 
- Workaround become further complicated, because unlike other async functions, the `import` callsite is semantically significant to webpack, which means we can't just "hide" the machinery in a separate file. You'll have to manually maintain a mapping of url patterns to modules. Sorta ick. 

Here's some pseudocode for the workaround. https://gist.github.com/threepointone/91670a9b5cf7dab254cc38ee983b3308

This is the commit that changed how require.ensure works in the background, making the promise unavoidable https://t.co/QLglJVC2Li If this went back to the previous behavior with regular callbacks, this issue can be considered fixed :) 

I'm working on a repo with working example of the above situation, made this issue to quickly share with you folks though. 

**What is the expected behavior?**

require.ensure resolves synchronously if possible.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

webpack 2

**Comment by threepointone** [comment]
the same bug was discussed on this twitter thread https://twitter.com/ken_wheeler/status/827252659409260544

**Comment by sokra** [comment]
I see the problem, but don't know a good solution for this currently.

`import()` returns a Promise by spec, which is always async.

React expect the initial rendering to by sync.

---

A good solution would require changes on React level. Allowing async stuff.

---

A webpack hack: `__webpack_require__(require.resolveWeak("./page"))`

This loads a module without adding it to the dependency tree. You need to make sure that it's available while runtime. i. e. by adding it chunk as script tag, or `import()` it anywhere else.

---

A react hack:

When loading a module on demand wrap it in `ReactAsync.dependency(import("./page"))`.

``` js
ReactAsyncDOM.render(<App />, element);
```

Write ReactAsyncDOM in a way that it renders your app into the trash until all `dependencies` are resolved. Than it continues rendering with the normal ReactDOM impl.

This could make a great module as you could also use it for data fetching in SSR.

This is difficult because react tree must be kept when continue rendering with ReactDOM.

**Comment by threepointone** [comment]
the react options will be viable once the fiber rewrite happens, so I'll hold off until that. The webpack hack is a good option! I'll give it a spin and get back to you. 
/cc @kenwheeler

**Comment by threepointone** [comment]
quick question: will the require.ensure api remain / not be deprecated? alternately, is there a way to specify chunk names with the `import` api?

**Comment by sokra** [comment]
It will remain. Chunk name option to `import()` will be added soon.

**Comment by threepointone** [comment]
It appears that the presence of the `resolveWeak` expression breaks `require.ensure`, and the imported module is just a plain object. 

the following sample is ok 
```jsx
(() => {
let Module

require.ensure([], require => {
  let ret, error
  try{
    Module = require('./x.js')  
  }
  catch(err) {
    error = err
  }
  console.log({ error, Module }) 
})
})()
```

but the following code 'breaks', and `Module` is simply `{}`
```jsx
(() => {
let Module
try{
  Module = __webpack_require__(require.resolveWeak('./x.js')) 
  console.log({ Module })
  return 
}
catch(err) {
  // silent
}

require.ensure([], require => {
  let ret, error
  try{
    Module = require('./x.js')  
  }
  catch(err) {
    error = err
  }
  console.log({ error, Module }) 
})
})()
```

**Comment by threepointone** [comment]
I worked around it by first testing `__webpack_modules__[resolveWeak(...)]` before calling `__webpack_require__`, cheers

**Comment by TongDaDa** [comment]
You require ('/a ') is asynchronous, for lazy loading weback official in the import () the grammar is not particularly understand, can use it

**Comment by threepointone** [comment]
This is a sketch of the solution I'm currently using. https://gist.github.com/threepointone/d01eabcdc2485c234e9303b8424df556

**Comment by sokra** [comment]
Here is a solution: https://github.com/ctrlplusb/react-async-component

**Comment by abirbasu10** [comment]
> This is a sketch of the solution I'm currently using. https://gist.github.com/threepointone/d01eabcdc2485c234e9303b8424df556


> This is a sketch of the solution I'm currently using. https://gist.github.com/threepointone/d01eabcdc2485c234e9303b8424df556


> This is a sketch of the solution I'm currently using. https://gist.github.com/threepointone/d01eabcdc2485c234e9303b8424df556


> This is a sketch of the solution I'm currently using. https://gist.github.com/threepointone/d01eabcdc2485c234e9303b8424df556

**Comment by abirbasu10** [comment]
> This is a sketch of the solution I'm currently using. https://gist.github.com/threepointone/d01eabcdc2485c234e9303b8424df556


> This is a sketch of the solution I'm currently using. https://gist.github.com/threepointone/d01eabcdc2485c234e9303b8424df556


> This is a sketch of the solution I'm currently using. https://gist.github.com/threepointone/d01eabcdc2485c234e9303b8424df556


> This is a sketch of the solution I'm currently using. https://gist.github.com/threepointone/d01eabcdc2485c234e9303b8424df556


> This is a sketch of the solution I'm currently using. https://gist.github.com/threepointone/d01eabcdc2485c234e9303b8424df556

**Comment by abirbasu10** [comment]
Test

**Comment by abirbasu10** [comment]
Hello Github..
