### ISSUE TITLE
A bundle should be a module

### ISSUE THREAD

**Issue by paleo** [webpack/webpack#4202]
**What is the current behavior?**

A bundle generated by Webpack cannot be used as a module.

**What is the expected behavior?**

We should have the ability to make bundled modules.

For example:

	// libA.js
	export let a = "Hello"
	
	// libB.js
	export let b = "World"
	
	// entry.js
	import {a} from "./libA"
	import {b} from "./libB"
	
	export let message = `${a}, ${b}!`

Then the webpack bundling would generate a single file:

	// bundle.js
	/*
	 * Here all the usual Webpack stuff,
	 * then:
	 */
	export {message}

The modules `libA` and `libB` are not accessible from outside the bundle. But I suggest that all exported members of `entry` (the entry point defined in `webpack.config.js`) could be exported by the bundle.

***Use cases***

Native support for ES6 modules [is coming](https://blog.hospodarets.com/native-ecmascript-modules-the-first-overview#browsers-support) in browsers. We should be able to use Webpack bundles as native modules.

Even now. I currently generates my bundled libraries without Webpack by concatenating files and append exports because I didn't find how to export something from a bundle.

**Comment by timse** [comment]
how should those bundles be consumed if the browser does not have native support for es6? :)

**Comment by paleo** [comment]
By Webpack or SystemJS.

**Comment by gbakernet** [comment]
@paleo There is [libraryTarget](https://webpack.js.org/configuration/output/#output-librarytarget) config option that does what you are suggesting a `exportFormat` could do. **amd**, **commonjs** and **umd** are supported.

I see there is some discussion around supporting **es2015** modules (formerly **es6**). https://github.com/webpack/webpack/issues/2933.

**Comment by paleo** [comment]
@gbakernet Thank you. :)
