### ISSUE TITLE
bootstrap requires jQuery

### ISSUE THREAD

**Issue by krackmoe** [webpack/webpack#4208]
I tried to include jquery in my webpack.config.js and therefore i created a new ProviderPlugin. My webpackconfig.js looks like this:
```
var webpack = require('webpack');
var path = require('path');

module.exports = {
    entry: './static/js/main.js',
    output: {
        filename: 'bundle.js',
        path: path.resolve(__dirname, './static/dist')
    },
    plugins: [
        new webpack.ProvidePlugin({
            "$": "jquery",
            "jquery": "jquery",
            "jQuery": "jquery",
            "window.jQuery": "jquery"
        })
    ]
};
```

And my index.html has the following ending:
```
</div>
        <script src="dist/bundle.js"></script>
        <script src="js/bootstrap.min.js"></script>
    </body>
```

As i can see in the resulting bundle.js, jquery is inserted in the bundle.js file.
But as soon as i go on my index.html it tells me this error msg from bootstrap: "**bootstrap.min.js:6 Uncaught Error: Bootstrap's JavaScript requires jQuery
    at bootstrap.min.js:6**"

Why is this happening? Is this a bug, or am i doing something wrong?

I am using the latest chrome version and webpack 2.2.1

**Comment by Odrin** [comment]
@krackmoe You doing something wrong. Webpack knew nothing about bootstrap, and bootstrap can't get jQuery from bundle because modules are scoped inside bundle. You need to include bs to your config as a second entry or include it to bundle.

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
