### ISSUE TITLE
Multiconfig watch - callback called 1x initially, then for each config

### ISSUE THREAD

**Issue by ndreckshage** [webpack/webpack#4209]
**Do you want to request a *feature* or report a *bug*?**

A bug

**What is the current behavior?**

Running watch with multi configs results in cb being called once initially with array of stats (expected). And then when a file changes, the callback is hit once for each config, with an array of 1. This was introduced with **2.2.0-rc.4**.

**If the current behavior is a bug, please provide the steps to reproduce.**

```
webpack([config1, config2]).watch({}, (err, statsArr) => {
  console.log('cb hit', statsArr) 
});

// initial
// a, [stats1, stats2]

// change file
// a, [stats1]
// a, [stats2]
```

**What is the expected behavior?**

```
webpack([config1, config2]).watch({}, (err, statsArr) => {
  console.log('cb hit', statsArr) 
});

// initial
// a, [stats1, stats2]

// change file
// a, [stats1, stats2]
```

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by sokra** [comment]
Each compilation is separate. This is the expected behavior. You get an array of all stats that changed.

**Comment by bebraw** [comment]
Ok, it's by design. Time to close.

**Comment by ndreckshage** [comment]
@sokra / @beauroberts not sure I understand why it makes sense for it to happen differently for the initial compilation vs subsequent builds?
