### ISSUE TITLE
createChildCompiler does not remember target

### ISSUE THREAD

**Issue by samvv** [webpack/webpack#4212]
This is related to webpack-contrib/worker-loader#44 but if I'm correct this is an issue with webpack itself rather than the loader. The basic issue is that [`createChildCompiler`](https://github.com/webpack/webpack/blob/master/lib/Compiler.js#L394) does not take into account the target (in my case 'node-webkit') when creating a subcompiler. The reason seems to be that `compile`-plugins are filtered out.

A quick hack fix was to include the `compile`-plugins in the child compiler, but, as I'm unfamiliar with the code base, I don't know of the unwanted side-effects (which I presume are plenty).

I've tested this on `master` release as well as the latest release (`2.2.1`). It also seems to be an issue in `v1` as that's what the project I'm working on which spawned the error was using.

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by samvv** [comment]
I'm sorry, I deleted it because [the other issue](https://github.com/webpack-contrib/worker-loader/issues/44) describes it in more detail. Will update it now.
