### ISSUE TITLE
[Docs] Uglifyjs webpack plugin docs ambiguous

### ISSUE THREAD

**Issue by sagiavinash** [webpack/webpack#4213]
**Need Clarity**
In the docs for UglifyjsWebpackPlugin
https://webpack.js.org/plugins/uglifyjs-webpack-plugin/

The top **Usage** section asks us to do 
```

const UglifyJSPlugin = require('uglifyjs-webpack-plugin');

module.exports = {
  entry: {...},
  output: {...},
  module: {...},
  plugins: [
    new UglifyJSPlugin()
  ]
};
```
and in the **Mangling** section 
```
new webpack.optimize.UglifyJsPlugin({
  mangle: {
    // Skip mangling these
    except: ['$super', '$', 'exports', 'require']
  }
})
```

So should I use `new UglifyJSPlugin()` or `new webpack.optimize.UglifyJsPlugin`
if whats mentioned in docs is correct. Could you please explain why this difference?

**Comment by ajfuller** [comment]
Per the docs: 
"Note that webpack contains the same plugin under webpack.optimize.UglifyJsPlugin. This is a standalone version for those that want to control the version of UglifyJS. The documentation is valid apart from the installation instructions in that case."

It's the same plugin as what is included so usage can be handled the same for configuration. If you were using the externalized one it would be:
```
new UglifyJsPlugin({
  mangle: {
    // Skip mangling these
    except: ['$super', '$', 'exports', 'require']
  }
})
```

I agree the way it's set up is a bit confusing at first glance. I personally use the included `webpack.optimize.UglifyJsPlugin` for most of my projects and have not found a need for the standalone version. If that's the case for other people as well then we should probably reference `webpack.optimize.UglifyJsPlugin` by default for all examples and mention that there is a standalone plugin if needed.

**Comment by sagiavinash** [comment]
@ajfuller thanks for your patience. closing the PR

**Comment by sagiavinash** [comment]
@ajfuller I completely agree that its my negligence.
but do you think its better to add these important notes in snippet comments?
as people do hasty search for solutions and only see snippets.

**Comment by sagiavinash** [comment]
@bebraw i see a change in the docs that make them consistent in both the places
Thanks to whoever pushed the change. closing the issue
