### ISSUE TITLE
HMR with react-hot-loader doesn't hot update for react functional components

### ISSUE THREAD

**Issue by fijiwebdesign** [webpack/webpack#4214]
**Bug report**

**What is the current behavior?**

I'm using the react-hot-boilerplate 
https://github.com/gaearon/react-hot-boilerplate

Changed the App.js to 

```
export default () => (
  <div>
    <h1>Hello world!</h1>
  </div>
)
```

HMR doesn't work anymore. It gives the message: 

> [HMR] The following modules couldn't be hot updated: (Full reload needed)
> This is usually because the modules which have changed (and their parents) do not know how to hot reload themselves. See http://webpack.github.io/docs/hot-module-replacement-with-webpack.html for more details.

**What is the expected behavior?**

The App.js should HMR as it does with an ES6 class component. 

**OS and versions.**

Using the same npm versions on: 
https://github.com/gaearon/react-hot-boilerplate/blob/master/package.json

Node: v5.5.0
OS: Max OSX Yosemite 10.10.5 
Browser: Chrome  55.0.2883.95 (64-bit)

**Comment by bebraw** [comment]
Can you report this to react-hot-loader? There's not much we can do about the issue here.
