### ISSUE TITLE
[v2] Query parameters passed to filename are removed when passed to rule test function.

### ISSUE THREAD

**Issue by caccialdo** [webpack/webpack#4217]
**Do you want to request a *feature* or report a *bug*?**
*feature*

**What is the current behavior?**
Requiring a file with a query parameter appended at the end works but the querystring parameter gets removed.

**If the current behavior is a bug, please provide the steps to reproduce.**
```js
import './my-styles.css?module';
```
In webpack config:
```
...rules: [{
  test: path => {
    console.log(path); // /full/path/to/my-styles.css
    ....
  },
  loader: 'css-loader?...!...'
}, ...],
...
```

**What is the expected behavior?**
In webpack 1, the absolute path passed to the test function still contained the query parameter.

**If this is a feature request, what is motivation or use case for changing the behavior?**
This feature used to allow further customization of the loader chain instead of only relying on the extension. For e.g. we used it to force a CSS file as a CSS module by passing a `?module` query parameter to the file name.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Node.js 6+

**Comment by sokra** [comment]
This was changed for webpack 2.
You can match the resource query by using `resourceQuery: condition` in the rule.

**Comment by caccialdo** [comment]
@sokra Thanks for pointing me in the right direction 👍
