### ISSUE TITLE
Webpack behaves weird with npm config arguments. 

### ISSUE THREAD

**Issue by michaeljota** [webpack/webpack#4221]
**Do you want to request a *feature* or report a *bug*?**

*bug*

**What is the current behavior?**

When running Webpack cli with an npm config argument, it will try to parse (and fail, cause the new "strict" mode about env variables). 

**If the current behavior is a bug, please provide the steps to reproduce.**

Using a `package.json` file that uses config properties and arguments. 
```json
{
  "name": "test-package",
  "config": {
    "mode": "development"
  },
  "scripts": {
    "build": "webpack --progress --profile",
    "build:prod": "webpack --progress --profile --bail --test-package:mode=\"production\"",
    "build:config": "webpack --config webpack.config.js --progress --profile --bail --test-package:mode=\"production\""
  },
  "dependencies": {
  },
  "devDependencies": {
    "webpack": "2.2.0"
  }
}
```
When trying to run `npm run build:prod` or `npm run build:config` throw:
```cmd
webpack 2.2.0
Usage: https://webpack.github.io/docs/cli.html
Usage without config file: webpack <entry> [<entry>] <output>
Usage with config file: webpack
[ ... ]
Unknown argument: angular2-webpack-starter:mode
```

**What is the expected behavior?**

Webpack should ignore npm config arguments.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

SO: Windows 10 AU
Node: 6.9.4 LTS
webpack: 2.2.0

**Comment by bebraw** [comment]
How are you using `--test-package:mode`? Could you use `--env` instead to pass the same information? You can then access it like this:

**webpack.config.js**

```javascript
...

module.exports = function(env) {
  // ... do something with env now
};
```

**Comment by michaeljota** [comment]
I know `env` variable, and how to use it. I just wanted to "migrate" to npm config instead.

(However, I think that both of them changes only in the current line (or next one) and neither allows for deeply transfer arguments between `npm run`s)

However, the use of npm `config` arguments shouldn't break the webpack run.

**Comment by bebraw** [comment]
I guess we'll have to wait on Tobias on this. My understanding is that it's "broken" by design.

**Comment by sokra** [comment]
What is a npm config argument? What should `--test-package:mode` do?

**Comment by michaeljota** [comment]
See `config` field in the example `package.json`. 

```json
  "config": {
    "mode": "development"
  }
```

This can be used in scripts like
```js
console.log("Mode: " + process.env.npm_package_config_mode);
```

And can be changed in npm scripts run sending an argument like this
```
--{the name of the package}:{the name of the setting}={value of the setting}
```

Also, it can be used in other ways.
Source: [link](http://www.marcusoft.net/2015/08/npm-scripting-configs-and-arguments.html)

**Comment by about-code** [comment]
Failing with an unknown properties error is a *yargs* validation option applied in `bin/config-yargs.js` where webpack calls `strict()` at the end of the file. Maybe the best option were to ask *yargs* for a feature to ignore config-mode arguments or a switch to print a warning rather than failing.

In turn you may team up with *yargs* on yargs/yargs/issues/781 :handshake:
