### ISSUE TITLE
Expected 'styles' to be an array of strings. How can we analyze errors in Webpack 2?

### ISSUE THREAD

**Issue by j-nord** [webpack/webpack#4227]
Since webpack 2 runs nothing. The message comes with all solutions. Finding the error in large projects is futile, because Webpack 2 simply does not issue a proper error message.

How can you really find the error. The existing solutions do not help any further. We have now found over 20 such alleged solutions. We look for 2 days the error but always the same error message:

"Expected 'styles' to be an array of strings "

Is there a real solution or it is possible to analyze errors in Webpack 2 ????

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.

**Comment by j-nord** [comment]
My Question is very easy !!

How can we find an error in webpack.? Is there as diagnostic tool by all the loaders and so many errors???

We would not spend weeks with searching bugs or wrong version or wrong loader.
