### ISSUE TITLE
{stats: {chunks: false}} didn't work

### ISSUE THREAD

**Issue by foisonocean** [webpack/webpack#4229]
```javascript
// webpack.config.js
module.exports = {
  ...
  stats: {
    chunks: false
  }
}
```

This didn't work.

Webpack Version: 2.2.1
Node.js Version: v7.5.0

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
