### ISSUE TITLE
{stats: {chunks: false}} didn't work

### ISSUE THREAD

**Issue by foisonocean** [webpack/webpack#4230]
**What is the current behavior?**
When i set `chunks: false`, webpack still print chunks info in the screen.

**If the current behavior is a bug, please provide the steps to reproduce.**
This is my config file.
```javascript
// webpack.config.js
module.exports = {
  ...
  stats: {
    chunks: false
  }
}
```

**What is the expected behavior?**
Webpack should not print chunks info.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Node.js: v7.5.0
webpack: 2.2.1
Operating System: macOS 10.12.3

**Comment by TheLarkInn** [comment]
Can you please paste what you do receive as your output? Or even better, would you be able to provide a small repro repo?

**Comment by jbreckel** [comment]
also `stats: 'none'` print the chunks

**Comment by jbreckel** [comment]
Ok I did dig into the `Stats.js` script, and found, the `stats.modules` option is ignored:
`lib/Stats.js#L45`
```
const showModules = d(options.modules, !forToString);
console.log('showModules', showModules);
```
prints always true, no matter what is defined in stats.
Even `minimal` and `none` have `modules = true`

**Comment by jbreckel** [comment]
after further digging, this line throws the options around:
https://github.com/webpack/webpack/blob/master/bin/webpack.js#L221

You either have to display `chunks` or `modules`, and there is currently no way around. 
Is this intentional?

**Comment by jbreckel** [comment]
@TheLarkInn can you help us here?
Do you need more information?

I would like to help on this one, but the question is: is this behavior intentional?

**Comment by gluons** [comment]
I also can't disable message. Is it relate to this issue?
@TheLarkInn Am I right? Or it isn't right?

![selection_001](https://cloud.githubusercontent.com/assets/4688092/23864570/8852bb06-0845-11e7-899d-c3359d3a1b02.png)

**Comment by jbreckel** [comment]
this is exactly what this issue is about.

As I said before in `bin/webpack` there is this part:
```
ifArg("display-chunks", function(bool) {
  outputOptions.modules = !bool;
  outputOptions.chunks = bool;
});
```
which sets `modules: true` and `chunks: false` in every case except when `display-chunks` is set, then you get `modules: false` and `chunks: true` no matter what you configured.

**Comment by jbreckel** [comment]
https://github.com/webpack/webpack/issues/4118 this is related and seems to be fixed on master

**Comment by sod** [comment]
No, wasn't fixed. As `yargs` defaults all boolean settings to false, the code block

```typescript
ifArg("display-chunks", function(bool) {
  outputOptions.modules = !bool;
  outputOptions.chunks = bool;
});
```

is always being executed because `display-chunks` is defined as boolean in [bin/webpack.js#L82-L86](https://github.com/webpack/webpack/blob/073d783ed4078d49c7db3a4c4dd1b47bb5ac44d9/bin/webpack.js#L82-L86)

**Comment by sod** [comment]
Changing 

```typescript
	"display-chunks": {
		type: "boolean",
		group: DISPLAY_GROUP,
		describe: "Display chunks in the output"
	},
```

in [bin/webpack.js#L82-L86](https://github.com/webpack/webpack/blob/073d783ed4078d49c7db3a4c4dd1b47bb5ac44d9/bin/webpack.js#L82-L86) to

```typescript
	"display-chunks": {
		type: "boolean",
                default: undefined,
		group: DISPLAY_GROUP,
		describe: "Display chunks in the output"
	},
```

fixes it.

**Comment by jbreckel** [comment]
the fix I was talking about is still in a beta branch and was moved to webpack@2.4.

I think the fix @sokra is working on changes a lot of stuff in this area.

**Comment by gluons** [comment]
I am activity. 😛

**Comment by mishelen** [comment]
webpack 3.10.0 stats options (not only chunk) are still broken. Of course, some things works for example colors ))

**Comment by qiming-kooboo** [comment]
@mishelen I have the same issue with you, Did you get any solution for this?

**Comment by jrpomeroy** [comment]
Still broken in 3.11.0 =[

**Comment by evilebottnawi** [comment]
Somebody can test this in webpack@4?

**Comment by gluons** [comment]
@evilebottnawi I've been using `stats: 'none'` with [webpack-stylish](https://github.com/webpack-contrib/webpack-stylish) in webpack 4.

It actually works for me now.

**Comment by evilebottnawi** [comment]
@gluons Thanks! 
/cc @jrpomeroy @mishelen @jbellenger

**Comment by vreality64** [comment]
I've had the same problem. Please refer to the quotation below to correct the setting and fix it. Problem is the `stats` option in `webpack.config.js` is ignored when the `devServer` option is present. I wish it help you.

> [For webpack-dev-server, this property needs to be in the `devServer` object.](https://webpack.js.org/configuration/stats/)

```js
// before
module.exports = {
    stats: false
}

// changed
module.exports = {
    devServer: {
        stats: false
    }
}
```

**Comment by MartinCerny-awin** [comment]
I am using webpack-dev-middleware and @vreality64 answer help me to figure out solution for my problem. https://github.com/webpack/webpack-dev-middleware#stats

**Comment by evilebottnawi** [comment]
Issue about webpack-dev-server and stats https://github.com/webpack/webpack-dev-server/issues/1557 (will be solved in near future). Closing PR due original problem solved. Anyway feel free to open new issue if you faced again
