### ISSUE TITLE
Cannot Import react, react-dom, redux or react-redux on electron-renderer target

### ISSUE THREAD

**Issue by holywyvern** [webpack/webpack#4232]
I'm having a bug here. Loading react fails on electron-renderer target.

React, redux and many cannot be loaded on electron.

Reproducing the error is complex, so I just provide an npm module to test it using `npm install && electron .`

But the idea is simple, I compile webpack when I startup my electron application, and then I open an html file with that script, but react redux and many others just fail. Yet extend, shallow-copy or electron doesn't.

[Here it's the repository](https://github.com/holywyvern/webpack-bug)

Of course, changing the target to web or node "solves" the issue, except when doing `import { X } from 'electron'` doesn't work anymore.

The code is commented everywhere, hope it helps.

My Operative system is: Windows 10 x64
My Node Version is: 6.9.4
My NPM Version is: 3.10.10
My Webpack Version is: 2.2.1

**Comment by michael-ciniawsky** [comment]
```diff
context: path.resolve(__dirname, '..'),
- entry: path.resolve(__dirname, '..', 'src', 'renderer', 'main.js'),
+ entry:  './src/renderer/main.js', 
// you already set the app root via context
options: {
-  presets: [ 'latest' ] 
+  presets: [ ['latest', { modules: false }] ] 
  // disables babel transpiling ES2015 Modules => CJS
}
```

**Comment by holywyvern** [comment]
Ok, I changed those parts on the renderer on the repository, but the error is still there.

I also changed in webpack/renderer.js:

```diff
-    target: 'electron',
+    target: 'electron-renderer',
```

And removed electron as a dependency on package.json (it shoudn't be needed):

```diff
-    "electron": "^1.4.15"
```

**Comment by holywyvern** [comment]
Found a solution:

```diff
-         descriptionFiles: [path.resolve(__dirname, '..', 'package.json')],
```

It seems than description files option doesn't go well as an absolute path.

**Comment by michael-ciniawsky** [comment]
@holywyvern Does it work now ? :)

**Comment by holywyvern** [comment]
Yup, it does, the solution was to remove the descriptionFiles option and let webpack choose the default option.

**Comment by michael-ciniawsky** [comment]
kk :), can please close the issue then?
