### ISSUE TITLE
importScripts inside web worker loses context when using worker-loader

### ISSUE THREAD

**Issue by rahulgandhi** [webpack/webpack#4234]
I'm facing a bug here. 
I'm using worker-loader to load webworkers in my project. My web worker script uses importScripts to download other scripts and execute them. According to [](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers) 

> The browser loads each listed script and executes it. Any global objects from each script may then be used by the worker.

However, this is not what happens when I use worker-loader. 

This is what happens.

```
var Worker = require("worker-loader!./myWorker.js");
var worker = new Worker;

// myWorker.js
var x = x || {};
importScripts("a.js");
x.name // "undefined"


//a.js
var x = x || {};
x.name = "hello";
```

This is what happens (expected) when I don't use a worker-loader

```
var worker = window.Worker("myWorker.js");

// myWorker.js
var x = x || {};
importScripts("a.js");
x.name // "hello"


//a.js
var x = x || {};
x.name = "hello";
```

I've created a test repo in case you want to reproduce it.
[worker-loader](https://github.com/rahulgandhi/webpack_webworker)

webpack version: 2.2.1
worker-loader version 0.7.1
node version 6.9.5

**Comment by bmayen** [comment]
Is this still an issue in v3?

**Comment by schorfES** [comment]
Yes, I ran into this issue while setting up [openpgpjs](https://github.com/openpgpjs/openpgpjs). The bundled webworker uses `importScripts('openpgp.js');`, but `openpgp.js` is not located in webpacks output path.

**Comment by caitlin615** [comment]
This is still an issue in v4

**Comment by montogeek** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by rahulgandhi** [comment]
@montogeek I have already given the link to a github repo and it also has the steps to reproduce it.
Here is the link: https://github.com/rahulgandhi/webpack_webworker

Thanks :)

**Comment by evilebottnawi** [comment]
@webpack-bot move to webpack-contrib/worker-loader

**Comment by yangsibai** [comment]
Replace `importScripts("a.js");` with `require("a.js")`.
