### ISSUE TITLE
hyphenated names

### ISSUE THREAD

**Issue by escKeyStroke** [webpack/webpack#4238]
**Do you want to request a *feature* or report a *bug*?** bug

**What is the current behavior?** 
When setting any dependency with hyphenated name such as *html-minifier* or *react-dom* to *external*, the build is produced with the line (example)
`module.exports = react-dom`
where `react-dom` is not a valid javascript identifier, but is interpreted as the `-` operator being applied to two identifiers.

**If the current behavior is a bug, please provide the steps to reproduce.**
Follow the steps in #4237, except for adding the line `, externals: 'html-minifier` under `, target: 'node'` in webpack.config.js

**What is the expected behavior?** Some other kind of reference should be made to the externalized module, so that the build works.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.** Again, see #4237

**Comment by timse** [comment]
not sure what you are trying to achieve.

have you read the docs? https://webpack.js.org/configuration/externals/

**Comment by escKeyStroke** [comment]
Yes timse, I have read the docs.  Why do you ask me that?

I'm trying to produce something that contains html-minifier as a dependency for another person to execute without worries.  So I was trying to bundle it, but the bundle doesn't work (#4237), so I tried again, this time having html-minifier requested as a dependency from inside the bundle.  Again, it doesn't work because of a different bug:

The OUTPUT FILE, generated with html-minifier as external, contains the line `module.exports = html-minifier` (which makes no sense) and it **should be** `module.exports = require('html-minifier')`  (when I change it manually, it works as intended).

**Comment by timse** [comment]
can you give an example code?

the one mentioned in #4237 does not contain any external definition

but from what you write you have something like this:

```
...
externals: {
  'html-minifier': 'html-minifier'
}
```

which tells webpack to look for a global variable called `html-minifier` if you require `html-minifier` which as you mention makes no sense as it is not even a valid variable name. (But kind of not webpacks problem, as you tell it to look for that).

what may be more interesting for you is probably something as described here: https://webpack.js.org/configuration/externals/#function

so you can say

```
...
externals: {
  'html-minifier': 'commonjs html-minifier'
}
```

to tell webpack to load html-minifier as a common.js rather than a global variable.

(did not test the code so use at your own risk).

**Comment by escKeyStroke** [comment]
That solution makes Webpack bundle the dependency with the output, instead of producing an output that requires the dependency.

I will put the code here again for convenience.

node 6.9.1, webpack 2.2.1, Windows 10
All in the same directory:
*package.json*
``` json
{
  "scripts": {
    "build": "webpack"
  },
  "dependencies": {
    "html-minifier": "^3.3.1",
    "webpack": "^2.2.1"
  }
}
```
*webpack.config.js*
``` javascript
module.exports = {
  entry: __dirname+'/index.js',
  output: {
    path: __dirname,
    filename: 'output.js'
  }
  , target: 'node'
  // ,externals: 'html-minifier' // output.js line 58: `module.exports = html-minifier` (I want module.exports = require('html-minifier'))
  // ,externals: 'commonjs html-minifier' // bundles html-minifier in output.js (I want html-minifier outside the bundle)
  // ,externals: {'html-minifier': {commonjs: 'html-minifier'}} // output.js line 58: `module.exports = undefined` (I want module.exports = require('html-minifier'))
}
```
*index.js*
```javascript
const minify = require('html-minifier').minify
const fs = require('fs')

const filestring = fs.readFileSync('./tominify.html').toString()
console.log(minify(filestring))
```
*tominify.html*
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>File to minify</title>
  </head>
  <body>
    Will pass through output.js to see if it works.
  </body>
</html>
```
In the command line, the following should work:
`$ npm i`
`$ npm run build`
`$ node output.js`

**Comment by timse** [comment]
i dont want to be rude, but it would be extremly helpfull if you could read more carefull.

i posted 
```
externals: {
  'html-minifier': 'commonjs html-minifier'
}
```

instead you tried 3 weird whatevers in your syntax.

i just checked what i proposed and it works perfectly fine.

again it was written in the documentation.

again no offence, but this is kind of wasting peoples time.

**Comment by escKeyStroke** [comment]
Right, that works.  I was sloppy reading your solution at first.
Well, I couldn't connect the dots from the docs, and of course I'll keep it in mind; if I become familiar with the behavior of webpack I may try to improve the docs.
Thank you for your time!

**Comment by jlebras** [comment]
I don't know if the doc is unclear or if I don't understand it correctly but using
```javascript
externals: {'hyphen-separated': {commonjs: 'hyphen-separated'}}
```
results in `module.exports = undefined` in the bundle which of course does not work, like stated above.

The solution you provided works (thank you!) but is not documented (or that's the point I'm missing).
I'm using `webpack@4.5.0` (and `webpack-cli@2.0.14`).

**Comment by ryan-codingintrigue** [comment]
@jlebras Seeing the same behavior in `webpack@4.6.0`. The object syntax used to work fine for me in `3.x` but as of `4.x` I must use the string `"commonjs hyphen-separated"`

Looks like either a bug, or an issue with the docs.

**Comment by newien33** [comment]
Hi,

Can you look into this? I am trying to do the same, and run into exactly the same issue:
 the config in question is:

  externals: {
   'element-ui': 'ElementUI'
  }

https://stackoverflow.com/questions/49820973/vue-elementui-webpack-externals-using-cdn

 Thanks.

**Comment by arve0** [comment]
For others depending on UMD-builds with dash `-` in exported name, like material-ui, one could use the global variable `window[exported_name]`:

```
webpackConfig.externals = [
    {
        'react': 'React',
        'react-dom': 'ReactDOM',
    },
    externalMaterialUI
];

/** Callbacks with global UMD-name of material-ui imports */
function externalMaterialUI (_, module, callback) {
    var isMaterialUIComponent = /^@material-ui\/core\/([^/]+)$/;
    var match = isMaterialUIComponent.exec(module);
    if (match !== null) {
        var component = match[1];
        return callback(null, `window["material-ui"].${component}`);
    }
    callback();
}
```
