### ISSUE TITLE
Plugin API done() is called to often - in this case before additional compiler passes

### ISSUE THREAD

**Issue by swernerx** [webpack/webpack#4243]
We use Webpack in an SSR React application. We have a build dependency between our client and server. The client has to be build before starting building the server. In our current code base we experienced something new... which was probably introduced during recent Webpack v2 development:

- The client part is building code and completed.
- The server part is building.
- The client is building again.
- The server is building again.

This first felt like some kind of race condition. I spend some more time debugging it and I break it down to this section in `Compiler.js` inside `emitAssets()`:

```js
var stats = compilation.getStats();
stats.startTime = startTime;
stats.endTime = new Date().getTime();
self.applyPlugins("done", stats);
```

Our current code based looks like this:

```js
compiler.plugin("done", (stats) =>
{
  if (!stats.hasErrors()) {
    console.log("Done")
    resolve(compiler)
  }
})
```

`resolve()` is the promise method which leads to the execution of the server method.

So in a abstract way the execution flow looks like:

- Start Client 1
- Done Client 1 (in additional pass handling)
- Start Server 1
- Start Client 2 (from additional pass handling)
- Done Server 1
- Done Client 2
- Start Server 2
- Done Server 2

Even if rebuilding the client is required... which is another bug I investigate, it should most definitely not rebuild the server two times as well. Running these two processes in parallel is also problematic because of some possible conflicts during runtime (they use different webpack configs).

The questions would be:

- Is the current behavior what you intend with calling `done()` two times?
- Is there a way to detect whether this is really the last `done()`
- Is there probably another API available which better fits a kind of "complete" requirement?

**Comment by swernerx** [comment]
This is the interesting line:
https://github.com/webpack/webpack/blob/master/lib/Compiler.js#L66

**Comment by swernerx** [comment]
It seems that, looking at the current code base, I do not have access to the `needAdditionalPass` flag which is being set during the process.

**Comment by swernerx** [comment]
This issue also transports through other plugins like [DevMiddleware](https://github.com/webpack/webpack-dev-middleware) as this middleware also listens to `done` hooks for updating the client etc. I can't think of a reason why it would make sense to send updates to the client when the bundle is regarded as not yet valid by Webpack.

Have a look here:
https://github.com/webpack/webpack-dev-middleware/blob/master/lib/Shared.js#L101

**Comment by swernerx** [comment]
The current implementation with calling `done()` earlier = just before an additional pass is probably also [wrongly documented](https://webpack.js.org/api/plugins/#done-stats-stats-): "All is done."

**Comment by sokra** [comment]
Because of filesystem accuracy it can happen that webpack compiles twices (it's unsure if files were changed). You can filter these build by comparing the build hash with the last one.

**Comment by swernerx** [comment]
Can you explain this further? How would such code look like?

I think we have to implement this in the webpack-dev-middleware as well, as it currently seems to report being ready, when it's actually still compiling the additional pass.

**Comment by swernerx** [comment]
What I came up with as a quick fix is to replace the usage of `compiler.plugin("done", ...)` calls in my application with a StatusPlugin:
https://gist.github.com/swernerx/1f1c0ff09ee393e7cd831e60c2c2b01a
