### ISSUE TITLE
Module attribute usedExports is always true when importing ES modules

### ISSUE THREAD

**Issue by swernerx** [webpack/webpack#4244]
I am currently investigating an issue where when enabling the HardSource Plugin the `usedExports` field is always `true` for ES modules. 

It seems to work okay for normal CJS modules. The issue I experience happens when combining ES modules via `resolve: { mainFields: [ "web", "browser", "style", "module", "jsnext:main", "main" ] }` in the config with the HardSource Webpack Plugin. The plugin is comparing the `usedExports` field with the field value from the cache entry.

To fix the issue I have I have two options. Either removing HardSourcePlugin or disabling ES modules. I would like to get some better understanding if there is really some specific handling for ES modules in Webkit (probably to implement tree shaking) which have side effects on the `usedExports` field. 

Maybe someone more aware of the internals of Webpack can explain the current behavior.

See also the issue I reported for the HardSource plugin: https://github.com/mzgoddard/hard-source-webpack-plugin/issues/95

**Comment by swernerx** [comment]
HardSource is accessing the `usedExports` in the `after-seal` phase.

During this phase it seems to check the `used` and `usedExports` value of its module cache.

It remembers the difference in `usedExports` and reports back that it needs an additional pass via the `need-additional-pass` plugin API.

**Comment by sokra** [comment]
This is better discuss in the hard-source-webpack-plugin issue

**Comment by swernerx** [comment]
That's not very helpful. The issue here at hand is that the traversal of `usedExports` from some kind of array to a simple boolean value like `true`. This behavior is still unclear for me after spending some hours on the webpack code. Can you at least clarify the details on what this attribute of modules should track and give us an idea why it changes over to `true`.

**Comment by swernerx** [comment]
When looking at the command line argument for `--display-used-exports` it mentions "display info about which exports are used in a module". Which, in my opinion, should be always an array. @sokra any feedback on this?

**Comment by sokra** [comment]
`usedExports = true` all exports used, export should have real name.

`usedExports = ["abc", "def"]` these exports used, they will be mangled to `a` and `b`.

`usedExports = false` no exports used.
