### ISSUE TITLE
Errors in the webpack2 System. In the import ()

### ISSUE THREAD

**Issue by TongDaDa** [webpack/webpack#4245]
Using webpack2 System. In the import of routing getComponent = {} encapsulated into a function, then the external responsible for according to the path to return to, this way will appear in the compilation errors

```
    const getComponentLazily = (url,name = "default")=>{
            return (location, cb)=> {
                System.import(url)
                    .then((module)=>{ cb(null,module[name]) })
                    .catch(errorLoading);
            }
        }

render(){
  ...
        <Route path="people" getComponent=     {getComponentLazily('./components/people/people.jsx')}/>
 ...
}

```
My mistake is WARNING in. / js/SRC/Unique_main JSX
316-16-34 Critical dependency: the request of a dependency is an expression

**Comment by sokra** [comment]
Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md).

**Comment by TongDaDa** [comment]
它为什么会不支持这种写法呢？难道我要在Route每次都写重复的代码吗
