### ISSUE TITLE
Relative paths to images in css

### ISSUE THREAD

**Issue by demyan1411** [webpack/webpack#4246]
Hello!

I wont to get in production next directories
|-dist
|----assets
|---------js
|---------css
|---------images
|----index.html

`{
            test: /\.scss$/,
            loader: ExtractTextPlugin.extract('style-loader', 'css-loader!postcss-loader!resolve-url-loader!sass-loader?sourceMap', {
                publicPath: '../'
            })
        },`

`{
        test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
        loader: 'file',
        query: {
          limit: 10000,
          name: 'assets/images/[name].[ext]'
        }
      },`

`new ExtractTextPlugin('assets/css/[name].css', {
        allChunks: true
    }),`

and it all ok, but in css i have as result 
`background('../assets/images...')`
BUT! i need 
`background('../images...')`

How can i get it?

**Comment by michael-ciniawsky** [comment]
@demyan1411 

- wepack version
- `webpack.config.js`
- did you try with `url-loader` instead of 'file-loader`
- `{ publicPath: '../assets' }` ?


This question is also better suited for StackOverflow :stuck_out_tongue:

**Comment by sokra** [comment]
Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md).
