### ISSUE TITLE
watch does not trigger on file changes when path includes brackets "( )"

### ISSUE THREAD

**Issue by ak99372** [webpack/webpack#4250]
**Bug**

**What is the current behavior?**

runing: webpack -w 

-> initially runs without any warning or error and compiles but does not trigger any consecutive recompile on file changes
-> also process cannot be cancelled with [Ctrl+C] and the webpack becomes unresponsive 

**Problem**

The behavior is related to the directory path that in name includes the brackets "()".
(e.g.  C:\Work\_projects\.NET\FWK\FWK.2016.Q3\5. User Interface (UI)\Application.UI.Web)
Removing the bracket fixes the (not so obvious) issue.

**What is the expected behavior?**

Either throw an error and complain or allow brackets "()" in the path

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

webpack: 2.2.1
Node version: 6.9.5
Window 10 (x64)

**Comment by coolguy001tv** [comment]
My colleague meets the same problem. Actually, it exists in webpack1/node 5/win 7. When I update to webpack2/node 7/win 7 , it exists too.

**Comment by cmchap** [comment]
Same issue here. 

My file path contained `Dropbox (Personal)` as a parent directory. 

OS: Mac OSX 10.11.4
Browser: Chrome 56.0.2924.87 (64-bit)
Node: 7.7.3
Webpack: 1.14.0

**Comment by jdiaz5513** [comment]
Same exact situation as cmchap; I'm able to repro on OSX 10.11.4 and Win 10.

**Comment by willprice** [comment]
Ah, watch wasn't working for me either, and turns out I too was affected by this issue (Linux, v2.4.1), moved my project to a folder without spaces or parentheses and watch is now working.
