### ISSUE TITLE
Confirmed that export * as x from 'x'; produce this exact set of errors. Closing since this is a valid error for a real code issue

### ISSUE THREAD

**Issue by lzxb** [webpack/webpack#4251]
Problem address https://github.com/Microsoft/vscode/issues/20257#event-956595304

webpack2 Compile to achieve the desired value

**Comment by sokra** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please either update the issue with the template and reopen, or open a new issue.
