### ISSUE TITLE
Uncaught ReferenceError: __WEBPACK_AMD_DEFINE_ARRAY__ is not defined

### ISSUE THREAD

**Issue by syranide** [webpack/webpack#426]
I just updated to 1.3.4 and I started getting the above error from `es5-shim` at run-time... I assume because it has a universal wrapper.

Not sure what else you need to know (or if I've done something wrong).

PS. Everything works as usual with `1.3.2-beta9`.

**Comment by quangrau** [comment]
I'm using version `1.13.3`, and still got this error, but only on Android native browser.

**Comment by jinkin1995** [comment]
has a same question, on WeChat built-in browser

**Comment by shineirvin** [comment]
has a same problem. But it rarely happen.

**Comment by HJianfeng** [comment]
Does anyone know why

**Comment by markspolakovs** [comment]
I've also been seeing this issue, probably caused by jQuery. Airbrake reports that in almost all cases this is on Android. Would be interested in a resolution.

**Comment by adailey14** [comment]
I am running into this on Android browser as well. Strangely if I connect a remote debug session to the browser, the error stops happening.

**Comment by galziv** [comment]
occured to me on android native browser (lg g3) only. My devtoll was set to: "#eval-source-map".
once I changed to "#source-map" it worked.
I came to this solution as I've noticed webpack output is very different when changing the devtool option

**Comment by galziv** [comment]
I had this issue with android native browser (lg g3) only. I changed the devtool option to "#source-map" from "#eval-source-map" and it worked.
I came to this solution as I've noticed webpack's output files are very different when changing devtool option

**Comment by adailey14** [comment]
@galziv very interesting.

Just to add another datapoint - I removed jQuery from my project and was able to get rid of this error on the android browser I was testing with. So at least in my project it was tied directly to importing jQuery. Also, my devtool has been set to "eval" when experiencing the error.

**Comment by aboodz** [comment]
I was getting this error whenever I try to run my web application on Android browser (Galaxy S7). The same issue happens in both Webpack 1.13 and Webpack 2.2. 

I was able to fix this error by using `devtool: 'cheap-module-source-map'` instead of `cheap-module-eval-source-map`. I think Any `devtool` that doesn't use `eval` will fix the issue. It seems Android browser has some difficulties running eval codes.

**Comment by PopkornKevin** [comment]
Running into the same issue here.

**Comment by FlorianBurgevin** [comment]
new webpack.ProvidePlugin({
        "window.jQuery": "jquery"
     }),

Same error even in production for old mobile devices. Ex: Android 4.4.4
So it's not only the devtool.

Do you have a solution?

**Comment by adailey14** [comment]
I ended up removing jQuery from my project to get around this. Sorry not the best answer, wish I knew what caused the problem exactly.

**Comment by MaggieLMJ** [comment]
It worked in android devices when i removed jQuery and object.assign  from my project

**Comment by codefacts** [comment]
I am facing the same problem with android browser. Is there any solution to this problem?

**Comment by crtlf** [comment]
Running the same error with the Symfony Webpack Encore plugin _with the dev environment_.

Works fine when using with the production environment
`./node_modules/.bin/encore production --watch`

**Comment by andreyvolokitin** [comment]
This worked with `jquery@2.1.4`, and not worked with`jquery@3.4.1`. I have both: using jquery via `webpack.ProvidePlugin` and `cheap-module-eval-source-map` in dev mode
