### ISSUE TITLE
Order of precedence between command line argument and config files is inconsistent

### ISSUE THREAD

**Issue by tbassetto** [webpack/webpack#4260]
**Do you want to request a *feature* or report a *bug*?**

I believe it's a bug.

**If the current behavior is a bug, please provide the steps to reproduce.**

I have 2 very simple test cases, sharing the same `package.json` (relevant only to use the latest webpack version) and the same `app.js`. Only differs the webpack config and the CLI arguments:
* https://gist.github.com/tbassetto/048524ef16a1a30ca293ad1c9b7e69bd
* https://gist.github.com/tbassetto/4a4aefdae71333519bdb62debcdf8379

In one example, the CLI has higher priority then the config file, in the other example it's the opposite.

**What is the expected behavior?**

Consistency (not sure which one is better).

**If this is a feature request, what is motivation or use case for changing the behavior?**

N/A

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Latest macOS Sierra, webpack 2.2.1, Node.js 6.9.5 (latest LTS).

**Comment by sokra** [comment]
This is a problem with plugins added by the CLI. The are appended to the config, but should be prepended.

**Comment by sokra** [comment]
Do you want to do a PR?

**Comment by tbassetto** [comment]
Sure, I can have a look. I am confused by the fact that `DefinePlugin` and `optimize.UglifyJsPlugin` have a different priority when they are used both with a configuration file and their respective command line argument. I guess reading the source code will tell me what's happening 😅
