### ISSUE TITLE
Provide a way to mute warnings that can only be fixed with access to configuration

### ISSUE THREAD

**Issue by gaearon** [webpack/webpack#4263]
Create React App doesn't expose Webpack configuration to the users, so any Webpack warnings that require fixes in config are non-actionable for our users. Unless they are critical (but in this case they should be errors), I would like to have an option to mute them.

https://github.com/webpack/webpack/issues/1617 is a good example of such warning. Create React App users have no control over it (when caused by third party libraries shipping a pre-built file). [Just adding a `noParse` option](https://github.com/webpack/webpack/issues/1617#issuecomment-274342449) wouldn't work for them because they can't change the config. For this warning specifically, there are also some users who consciously choose to use precompiled files (e.g. for build speed), so I'm not sure it's entirely relevant in all cases.

Another example of this being inconvenient is that this warning causes CI to fail for our users. We use `eslint-loader` and due to popular demand configured CI script to treat ESLint warnings as errors on CI. Unfortunately this also means unactionable Webpack warnings break the build. (https://github.com/facebookincubator/create-react-app/issues/1150)

Would you consider a feature request of muting warnings that are only actionable for people with access to the config?

**Comment by sokra** [comment]
A option to suppress warnings make sense.

**Comment by sokra** [comment]
Maybe:

``` js
suppressWarnings: [
  /prebuild/
]
```

**Comment by bebraw** [comment]
I might put it below `output` so that you would end up with `output.supressWarnings`.

**Comment by justsml** [comment]
@sokra 👍 
I really like this pattern. 
 
@bebraw  However, don't add it to `output` - it confuses the purpose of that configuration object.

While it sounds right at first, on second thought I feel this feature deals more with console output - not chunking/hashing/building `output`.

**Comment by justsml** [comment]
And as @gaearon points out, it'd need to be external to the normal build configuration...

An environment value to optionally turn ON debug warnings would be ideal for my uses; however supporting this kind of config in the `package.json` would be awesome as well.  

@sokra is that kinda what you were thinking?

**Comment by gaearon** [comment]
In my case, I'm fine with this being in configuration because I as a tool-maker can set it up.

**Comment by justsml** [comment]
@gaearon - I guess I should clarify - which configuration?
webpack.js or package.json or?

**Comment by gaearon** [comment]
I have full access to Webpack config, but people using my package (that builds on top of Webpack) don't.

**Comment by justsml** [comment]
Webpack config is an executed `.js` - so it doesn't lend itself to fitting neatly in other toolchains.

Environment variables however would allow for more freedom to control the output when running in a Continuous Integration server, in 3rd party tools, or docker-based build chains.

**Comment by justsml** [comment]
In the case described regarding Create React App, could this case be solved by letting you define a `webpack` overrides key in package.json?
So you could access `noParse` and possibly other needed overrides?

Has this been discussed?

**Comment by sokra** [comment]
It will be in configuration. CRA can decide if they expose it as environment variable. I don't think this is needed but feel free to expose it.
