### ISSUE TITLE
Unable to build a project targeting node that requires uglifyJS2 without excluding node_modules

### ISSUE THREAD

**Issue by acusti** [webpack/webpack#4266]
**Do you want to request a *feature* or report a *bug*?**

A feature that looks like a bug for those hoping to build with `{ target: 'node' }`

**What is the current behavior?**

If I try to use webpack to build a script for the node target, and any of my functionality requires uglify-js (in my case, I was using [purifycss](https://github.com/purifycss/purifycss)), when I run `node built-script.js`, I get the following error:

```
fs.js:982
  return binding.lstat(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, lstat '/lib'
    at Error (native)
    at Object.fs.lstatSync (fs.js:982:18)
    at Object.realpathSync (fs.js:1662:21)
    at ~/Projects/webpack-uglify/build/index.js:20288:15
    at Array.map (native)
```

The problem stems from uglifyJS2’s [tools/node.js](https://github.com/mishoo/UglifyJS2/blob/master/tools/node.js#L23) file, which executes `fs.realpathSync(path.join(path.dirname(__filename), file));` for an array of paths to files in `../lib`. I tried using `node: { fs: 'empty' }`, `node: { fs: 'empty' }`, and `node: { fs: true }`, all to no avail.

I read through a number of issues, including #839, where @sokra recommends using `externals` to ignore all of `node_modules`. I tried that, and it solved the problem, so we can close this issue if it seems like a bad idea to try to make webpack able to handle this kind of a situation. I’ve been trying to figure out how to get around it, however, because in the actual app where I ran into this issue, we have some dependencies that require babel compilation (and therefore must go through the webpack build process), while others, like uglify, will only work if required from node_modules as they are. It also means I don’t have to worry about regular dependencies vs devDependencies and what will be present on the production boxes where the built code is running. Related to that, it would be nice to be able to build the server app on one machine and then transfer it to a bunch of boxes that can have their node process restarted and will be running the exact same code without any need to worry about dependency resolution or shrink-wrapping or `rm -rf node_modules && npm i`.

**If the current behavior is a bug, please provide the steps to reproduce.**

Minimal reproduceable repo: https://github.com/acusti/webpack-uglify

**What is the expected behavior?**

I expected webpack to successfully output the script with dependencies reconciled and built in.

**If this is a feature request, what is motivation or use case for changing the behavior?**

See **What is the current behavior?**, above

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Node.js version: 6.9.4
Webpack version: 2.2.1
OS: macOS 10.12.3

**Comment by sokra** [comment]
UglifyJs has a weird way of loading itself in node.js. You can't webpack it.

read this https://github.com/mishoo/UglifyJS2/blob/master/tools/node.js#L10-L34 and you'll understand way.
