### ISSUE TITLE
In memory hot reloading for server side bundles.

### ISSUE THREAD

**Issue by DylanPiercey** [webpack/webpack#4267]
**Do you want to request a *feature* or report a *bug*?**
Feature.

**What is the current behavior?**
Currently there is no way to use memory-fs with a node compilation target while using hot module reloading.

**If the current behavior is a bug, please provide the steps to reproduce.**
Not a bug.

**What is the expected behavior?**
Ideally there would be a way to for webpack to automatically emit hot reload events if the bundle is running in the same process. Or provide a way to hook into webpack to provide the hot reload files to another process running the bundle.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Currently I am stuck manually killing and reloading my node process. Ideally I would hot reload this as well since I am doing that for my browser build. The main issue with the current implementation (as far as I understand) with the node hot module reloading is that it is intrinsically tied to the actual file system which means my folder quickly fills up with hot reload files.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
webpack 2.x, node 7.x

**Comment by DylanPiercey** [comment]
I'm currently trying to find a work around for this and have been digging heavily through the webpack code base to see if there is a way I can monkey patch the api. Could any one point me in the direction of where (in node) webpack actually triggers a hot reload? I know it must be watching the file system for the hot-reload files but can't seem to find where this watching is actually taking place.

**Comment by hulkish** [comment]
+1
