### ISSUE TITLE
multiple loader/use in RC-3 with Array are not possible

### ISSUE THREAD

**Issue by squadwuschel** [webpack/webpack#4268]
**Do you want to request a *feature* or report a *bug*?**

bugreport

**What is the current behavior?**

I was using Beta.4 bevore I upgraded to Rc-3 and in Beta.4 the following loader for scss was possible in for my Angular 2 app

      {
             test: /\.scss$/,
              loader: [
                    ExtractTextPlugin.extract({ fallbackLoader: 'style-loader', loader: ['css-loader'] }),
                        'to-string-loader',
                        'css-loader',
                        'sass-loader'
                    ],
                    exclude: [helpers.root('Content')],
                    include: [helpers.root('App')
        }

when I try this in Rc-4 I got a error message schown

    Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
     - configuration.module.rules[6].use should be one of these:
       non-empty string | function | object { loader?, options?, query? } | function | [non-empty string | function | object { loader?, options?, query? }]

but when I read the error Message right, the Array should also work, but its not working.

**If the current behavior is a bug, please provide the steps to reproduce.**

 -

**What is the expected behavior?**

that I can pass a array of Loaders to the loader/use Property 

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

    "sass-loader": "5.0.0",
    "style-loader": "0.13.1",
    "css-loader": "0.26.1",
    "css-to-string-loader": "0.1.2",

**Comment by bebraw** [comment]
`loader` does not accept an array.

**Comment by squadwuschel** [comment]
then the Error Message schown is wrong or I am missunderstanding the 
   
    [non-empty string | function | object { loader?, options?, query? }]

brackets as optional?

is there a new way in RC-3 how to handle the behavior I mentoined above?

**Comment by bebraw** [comment]
Based on the error, you can pass either a non-empty string (loader name), function, or an object containing optional fields `loader`, `options`, `query`.

I would probably replace `loader` with `use` since it accepts an array like that.

**Comment by sokra** [comment]
Please upgrade to the latest version first.

**Comment by squadwuschel** [comment]
@sokra I've testet it 12hours ago with the newest Version Visual Studio Intellisense package.json showed me für webpack RC-3

I've tried to replace "loader" with "use" but that was also not working with the complete "new" Syntax its showing the same error:

    {
         test: /\.scss$/,
          use [
                ExtractTextPlugin.extract({ fallback: 'style-loader', use: ['css-loader'] }),
                    'to-string-loader',
                    'css-loader',
                    'sass-loader'
                ],
                exclude: [helpers.root('Content')],
                include: [helpers.root('App')
     }

**Comment by bebraw** [comment]
There is not enough info to say more. I would have to know extract-text-webpack-plugin version etc.

**Comment by bebraw** [comment]
Why to run `sass-loader` etc. before `extract`? Why not to push those within the `extract` call? Do you have a specific reason for that processing order?

**Comment by squadwuschel** [comment]
@bebraw and @sokra sorry about the Versions I am using webpack with Version 2.2.1 now and before that I was using 2.1.0-beta.27 and there the array notation was working fine. Now I've upgraded the extractTextPlugin to the newest RC-3 release and Its not working any more because I can't use the Array Notation. I am using an Angular 2 Setup with styleUrls and with the Array Notation was the only way I got my Styles working with Angular 2 and Webpack and ExtractText Plugin.

My current Versions I am using

    "angular2-template-loader": "0.6.2",
    "awesome-typescript-loader": "3.0.3",
    "css-loader": "0.26.1",
    "css-to-string-loader": "0.1.2",
    "file-loader": "0.10.0",
    "url-loader": "0.5.7",
    "html-loader": "0.4.4",
    "svg-url-loader": "2.0.1",
    "less": "2.7.2",
    "less-loader": "2.2.3",
    "node-sass": "4.5.0",
    "sass-loader": "5.0.0",
    "style-loader": "0.13.1",
    "raw-loader": "0.5.1",
    "to-string-loader": "1.1.5",
    "clean-webpack-plugin": "0.1.15",
    "extract-text-webpack-plugin": "2.0.0-rc.3",

**Comment by bebraw** [comment]
Both `loaders` and `use` fail over `loader`? I can't say anything more without having a project to run.

**Comment by squadwuschel** [comment]
I will create a small sample project tonight and I will post it here

**Comment by sokra** [comment]
It probably complains because your syntax is incorrect. Correct would be:

``` js
use: ExtractTextPlugin.extract({
  fallback: 'style-loader',
  use: [
    'css-loader',
    'sass-loader'
  ]
}),
```

**Comment by squadwuschel** [comment]
@sokra yes thats compiling, but not working with Angular 2 when I use this then I get a angular 2 error when loading the styles. I only got this to work with the three loaders 

     'to-string-loader',
     'css-loader',
     'sass-loader'

outside the extracttext plugin.

**Comment by sokra** [comment]
``` js
use: ExtractTextPlugin.extract({
  fallback: 'style-loader',
  use: [
    'css-loader'
  ]
}).concat([
 'to-string-loader',
 'css-loader',
 'sass-loader'
]),
```

**Comment by squadwuschel** [comment]
@sokra that also not working getting compile errors.

@bebraw sorry seems to be my fault I think its a "ExtractTextPlugin" Problem. I' am at home now and tried to reproduce my problems. And I've already running "webpack" 2.2.1 with "extract-text-webpack-plugin" 2.0.0-beta3.0 and here I am using the array Syntax shown above and that works fine. When I now upgrade the "extract-text-webpack-plugin" to "2.0.0-rc.3" then I got the error shown above. So I think its a extract-text-webpack-plugin problem and not a webpack I hope so :-)

that are my current devendencies that are not working, when I only change the "extract-text-webpack-plugin" to version 2.0.0-beta3 its working.

     "devDependencies": {
      "@types/node": "6.0.51",
      "angular2-template-loader": "0.6.2",
      "awesome-typescript-loader": "3.0.3",
      "css-loader": "0.26.1",
      "css-to-string-loader": "0.1.2",
      "file-loader": "0.10.0",
      "url-loader": "0.5.7",
      "html-loader": "0.4.4",
      "svg-url-loader": "2.0.1",
      "less": "2.7.2",
      "less-loader": "2.2.3",
      "node-sass": "4.5.0",
      "sass-loader": "5.0.0",
      "style-loader": "0.13.1",
      "raw-loader": "0.5.1",
      "to-string-loader": "1.1.5",
      "clean-webpack-plugin": "0.1.4",
      "extract-text-webpack-plugin": "2.0.0-rc.3",
      "html-webpack-plugin": "2.21.0",
      "webpack-notifier": "1.5.0",
      "webpack": "2.2.1",
      "webpack-dev-middleware": "1.10.0",
      "webpack-dev-server": "2.3.0",
      "webpack-md5-hash": "0.0.5",
      "webpack-merge": "2.3.0",
      "typescript": "2.0.10",
      "typings": "2.0.0"
    }

**Comment by stereobooster** [comment]
@squadwuschel did you manage to fix this? Or cross posted this issue in another place?

I have the same issue. Reproducible demo https://github.com/stereobooster/razzle-cssmodules
