### ISSUE TITLE
Contexts created using `import()` are called `System.import context`

### ISSUE THREAD

**Issue by simon04** [webpack/webpack#4270]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Contexts created using `import()` are called `System.import context` when running `webpack --display-reasons`.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. `cd examples/code-splitting-native-import-context outputs` (https://github.com/webpack/webpack/tree/master/examples/code-splitting-native-import-context)
2. `node build.js`
3. webpack outputs (to the console, and to [`README.md`](https://github.com/webpack/webpack/blob/master/examples/code-splitting-native-import-context/README.md)) `System.import context ./templates [4] ./example.js 3:23-60`

**What is the expected behavior?**
Since no `System.import` is used in this example, no `System.import context` should be mentioned. It should be called `import() context` or similar.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
webpack 2.2.1, node 7.5.0

**Comment by sokra** [comment]
yep, that's wrong. Please send a PR.

It's controlled by a static `type` property on the Dependency. -> lib/dependencies/ImportDependency
