### ISSUE TITLE
Allow pre/post plugin configuration for multi-page setups

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack#4271]
**Do you want to request a *feature* or report a *bug*?**

Feature.

**What is the current behavior?**

It is possible to run multiple compilations by returning an array of configurations, but there's no clear cut way to run plugins before/after them. Clean plugin is a good example of a pre-process. Deployment plugin would work post-process.

**What is the expected behavior?**

There should be hooks for running plugins before and/or after the main configuration.

**If this is a feature request, what is motivation or use case for changing the behavior?**

Having an opinion on this would make it clearer to deal with the use case (clean, compile, deploy) when using a multi-page setup.

A good way to implement could be to allow configuration like this:

```javascript
module.exports = [
  { // pre-process
    plugins: [
      ...
    ]
  },
  { ... }, // regular config
  { // post-process
    plugins: [
      ..
    ]
  }
];
```

Pre/post-process could be detected based on configuration shape.

**Comment by bebraw** [comment]
This could get a little tricky with tools like `parallel-webpack`. Exporting an object like `{ preProcess: { ... }, process: [ ... ], postProcess: { ... } }` could be a better option considering that.

**Comment by sokra** [comment]
webpack describe the build process in a declarative way. Clean, Deployment, Preprocess and Postprocess are imperative steps. webpack is not a taskrunner like gulp, grunt, npm scripts. These describe a process in an imperative way.

The recommended way to use preprocessing and postprocessing is to use a task runner. I. e. 

``` js
"scripts": {
  "build": "rm -rf build && webpack && npm run deploy"
}
```

**Comment by bebraw** [comment]
Yeah, I actually recommend using `prebuild`, `postbuild` like that. It's pretty clean.

The problem is that you already have a large set of pre/postprocess plugins (clean, deployment plugins, etc.). It gets problematic if you run webpack in a multi-compiler mode. Single config isn't a problem.
