### ISSUE TITLE
Website SSL Cert expired

### ISSUE THREAD

**Issue by dqfan2012** [webpack/webpack#4275]
**Do you want to request a *feature* or report a *bug*?**

I'm not requesting a new feature for webpack or reporting a bug with webpack. I'm just reporting the SSL certificate for the website has expired.

**What is the current behavior?**

The SSL certificate on your website has expired.

**If the current behavior is a bug, please provide the steps to reproduce.**

Just visit [webpack](https://webpack.js.org/)

**What is the expected behavior?**

When visiting the website, we see the green lock that shows the site is secure and the SSL certificate is valid.

**If this is a feature request, what is motivation or use case for changing the behavior?**

NA

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

NA

**Comment by bebraw** [comment]
Closing in favor of https://github.com/webpack/webpack.js.org/issues/882 . See also https://github.com/js-org/js.org/issues/14 to track the status.
