### ISSUE TITLE
Sourcemaps not updated - package from url

### ISSUE THREAD

**Issue by refaelos** [webpack/webpack#4279]
**Do you want to request a *feature* or report a *bug*?**
It's a bug

**What is the current behavior?**
Sourcemaps are not updated when using a direct url+branch in package.json

**If the current behavior is a bug, please provide the steps to reproduce.**
Here's how I define the library in package.json:
```
{
  dependencies: {
    ...
    "react-click-outside": "git://github.com/soomla/react-click-outside.git#master"
  }
}
```

My source maps are set as:
```
config.devtool = 'eval';
```

1. I make changes to the repo and commit+push.
2. I pull the changes using `npm install`.
3. Make sure the changes are updated in `node_modules`.
4. Restart and refresh the browser. The file with the previous changes is in the source maps.

**What is the expected behavior?**
The source maps file will be updated with the changes in master

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Node: 7.1.0
Browser: Chrome 55.0.2883.95
Webpack: 2.2.1
OS: osx 10.12

**Comment by tsaiDavid** [comment]
@refaelos I thought the key was `devTool` (camelcase)

**Comment by refaelos** [comment]
A lot has changed since then ... Closing.
