### ISSUE TITLE
Error message under Angular2: Cannot find module 'engine.io-client'

### ISSUE THREAD

**Issue by snics** [webpack/webpack#4288]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

```
ERROR in ./src/app/campaign/campaign.component.ts
Module build failed: Error: /Users/Max/Development/bmt/bmt-ui/angular/src/app/campaign/campaign.component.ts (6,22): Cannot find module 'engine.io-client'.)
    at _checkDiagnostics (/Users/Max/Development/bmt/bmt-ui/angular/node_modules/@ngtools/webpack/src/loader.js:145:15)
    at /Users/Max/Development/bmt/bmt-ui/angular/node_modules/@ngtools/webpack/src/loader.js:173:17
 @ ./src/app/campaign/campaign.module.ts 12:0-57
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi main
```

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Created an Angular 2 project with angular-cli
   - angular-cli: 1.0.0-beta.25.5
   - node: 6.9.1
   - os: darwin x64
   - @angular/common: 2.4.4
   - @angular/compiler: 2.4.4
   - @angular/core: 2.4.4
   - @angular/forms: 2.4.4
   - @angular/http: 2.4.4
   - @angular/platform-browser: 2.4.4
   - @angular/platform-browser-dynamic: 2.4.4
   - @angular/router: 3.4.4
   - @angular/compiler-cli: 2.4.4
2. Install engine.io-client module with npm
3.Import engine.io-client in angular component (```import * as eio from 'engine.io-client';```)
4. Add engine.io-client.js file to Scripts area in angular-cli.json
 ```
"scripts": [
        "../node_modules/engine.io-client/engine.io.js"
      ]
```

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by sokra** [comment]
Report this to @ngtools/webpack
