### ISSUE TITLE
require (as obj) being seen as a require call instead of object reference

### ISSUE THREAD

**Issue by ewrogers** [webpack/webpack#4290]
**Do you want to request a *feature* or report a *bug*?**

BUG

**What is the current behavior?**

Webpack2 is considering the following a `require` statement:
```
    {
      require: options.require || require,
      ...
    }
```

This will raise a `WARNING! Critical dependency: require function is used in a way in which dependencies cannot be statically extracted`

Followed by a webpack error: `Cannot find module "."` when trying to build.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Add the above code to any webpacked code.
2. Try to build.

**What is the expected behavior?**

It should replace `require` with `__webpack_require__` instead of treating it as a require statement.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Node 6.9.4, Webpack 2.2.1, Windows 7 x64.

**Comment by TheLarkInn** [comment]
@ewrogers DO you know if this would still happen on webpack@latest

**Comment by ewrogers** [comment]
I've stopped building on the backend portions so this no longer affects my daily use. Haven't tried on latest, sorry!

**Comment by Aaronius** [comment]
This causes unnecessary warnings in libs like HTMLHint: https://github.com/yaniswang/HTMLHint/issues/217

**Comment by Aaronius** [comment]
I'd really like to know how to work around this by suppressing the warning (only this one though--others are helpful) without modifying the third-party code that's triggering it.
