### ISSUE TITLE
Dynamic expressions for import() are broken

### ISSUE THREAD

**Issue by joefraley** [webpack/webpack#4292]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
Per this doc I expect the following code to work, but it throws an error: https://webpack.js.org/guides/migrating/#dynamic-expressions

```javascript
const withIndex = (base) => `${base}/index`
import(withIndex('./somePath'))
// Uncaught (in promise) Error: Cannot find module './somePath/index'.
```

And yet, adding an empty string resolves the problem:
```javascript
const withIndex = (base) => `${base}/index`
import('' + withIndex('./somePath')) // concat an empty string, tada
```

This makes no sense.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. `import()` a file using a string path to prove you can
2. save string path to `variable` and try to import using `variable`, doesn't work
3. try again by passing `'' + variable` into import() to see the bug  

MVP Repo: https://github.com/joefraley/lazy-loading-rr4-example/tree/MVP-broken-imports

```bash
git clone https://github.com/joefraley/lazy-loading-rr4-example/tree/MVP-broken-imports && cd lazy-loading-rr4-example && npm i && npm start
```

> You can see the MVP working by opening your browser console while running the example. You can play with goofy errors by opening [`source/parent-dir/child-dir/index.js`](https://github.com/joefraley/lazy-loading-rr4-example/blob/MVP-broken-imports/source/parent-dir/child-dir/index.js) and commenting/uncommenting different import statements listed there.

**What is the expected behavior?**
`import()` should ideally accept real variables, but should _definitely_ be consistent between its treatment of `import(var)` and `import('' + var)`

**If this is a feature request, what is motivation or use case for changing the behavior?**
want to use centrally defined functions like `const getComponent = (path) => import(path)` when lazy loading react components

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
node 5.5
macOS
webpack 2.2.0

**Comment by joefraley** [comment]
There also seem to be problems resolving index in some cases and not others.

import('child-dir') // knows that i want child-dir/index.js
import('../../child-dir') // doesn't know how to find index.js
import('../../child-dir/index.js') // works fine

**Comment by Kovensky** [comment]
`import()` can resolve _certain kinds_ of dynamic expressions.

Your `import()` example is, from the point of view of the `import()` analyzer, just `import(randomFunctionCall(randomArguments))`. webpack doesn't know that the function you are calling is pure and does nothing but return a string.

Also, `import('' + anything)` will work by bundling literally everything webpack can find, as it has no idea if `anything` starts with a `.` or `..` or whatever else.

**Comment by joefraley** [comment]
@Kovensky are the abilities/limitations of that import API documented? How does one know what it understands and what it doesn't? For example, how do you know this:

> Also, import('' + anything) will work by bundling literally everything webpack can find, as it has no idea if anything starts with a . or .. or whatever else

**Comment by joefraley** [comment]
Also it might be outside the scope of this issue to explain the API to me, but I don't understand at all how this works. The error message suggests that webpack evaluates the function call to a valid string, pointing to the correct module path.

```javascript
// Uncaught (in promise) Error: Cannot find module './somePath/index
``` 

So at best the error is very misleading

**Comment by Kovensky** [comment]
I'm not sure if it is documented, but it is limited by what is supported by https://github.com/webpack/webpack/blob/master/lib/BasicEvaluatedExpression.js .

I'm not completely sure on `import('' + anything)` but it uses the same path resolution as `require.ensure`, and it was a well known trap with `require.ensure` to give a string without enough context to limit the possible modules -- it would just bundle everything.

**Comment by ng-hai** [comment]
I have some trouble because of `dynamic require`. Reference [#630](https://github.com/jantimon/html-webpack-plugin/issues/630)

**Comment by evilebottnawi** [comment]
Problem still exists? If yes please create minimum reproducible test repo, thanks!

**Comment by outofthisworld** [comment]
I'm having a similar problem using create-react-app version 16.4.1

Trying to create an AsyncRoute component to make it easier for code splitting and came across an issue where a variable string passed to `import` reports an error of Unhandled Rejection (Error): `Cannot find module './../Site/Site.js'.`, though the same path resolves correctly as a normal static import.

Heres example code:

```
const AsyncComponent = (imp, namedExport='default')=>{
    return class AsyncComp extends React.Component{
        state = {}

        componentDidMount(){
            imp().then(comp=>{
                this.setState({component:comp})
            })
        }

        render(){
            return (this.state.component && this.state.component[namedExport]) || null;
        }
    }
}
class AsyncRoute extends React.Component{
    render(){
        return <Route path={this.props.path} exact={this.props.exact} component={AsyncComponent(()=>import(''+this.props.componentPath))}/>
    } 
}
```

Is this a bug or expected behaviour?

**Comment by mqliutie** [comment]
Thanks @Kovensky  you save my day

**Comment by navono** [comment]
@outofthisworld you must specify the relative path in `import`. For example the file layout:
![dynamicimport2](https://user-images.githubusercontent.com/3746639/46241299-24fa9b80-c3e9-11e8-842d-771e04c26e35.PNG)

I have demo [repo](https://github.com/navono/import-external-lib-to-react.git) to represent this. I hope this helps.

**Comment by sulymkaa** [comment]
right now I am using @nativescript/schematics to combine NS + Angular web apps and my case for this error is:

let pathVar = 'some-nativescript-path-string';
import('some-nativescript-path-string') is working fine 
import(pathVar) Error: Cannot find module 'some-nativescript-path-string'

**Comment by matowang** [comment]
> @outofthisworld you must specify the relative path in `import`. For example the file layout:
> ![dynamicimport2](https://user-images.githubusercontent.com/3746639/46241299-24fa9b80-c3e9-11e8-842d-771e04c26e35.PNG)
> 
> I have demo [repo](https://github.com/navono/import-external-lib-to-react.git) to represent this. I hope this helps.

wow thanks for solving my problem. Why does the relative path have to be in strings?

**Comment by navono** [comment]
@matowang in [webpack](https://webpack.js.org/api/module-methods/#import), there is no exact statement to describe this path, or maybe I didn't find it. 
I just read a [blog](https://segmentfault.com/a/1190000015648036)(only have Chinese version) and try some special case to test it.

Another alternative way is use [loadjs](https://github.com/muicss/loadjs).

**Comment by matowang** [comment]
@navono I meant that something like this works
```javascript
const path = "assets/image1.png";
import("../" + path);
```
but this doesn't work
```javascript
const path = "../assets/image1.png";
import(path);
```
I thought this was what you meant. Does the outside file reference need to be written in the import statement? My app only worked until I used import("../" + path);

**Comment by navono** [comment]
@matowang 
![webpack](https://user-images.githubusercontent.com/3746639/50619827-b45aa200-0f36-11e9-82c1-4341c0eb5b9f.png)

Webpack will collects all the dependencies, then check the `import` statement, parse the params to a reg statement, like this:
```
import('./app'+path+'/util') => /^\.\/app.*\/util$/
```

Webpack look for modules that meet the criteria based on reg. So if the param is a variable, Webpack will use the wrong reg statement to look for modules, in other words, will look for modules globally.

You can examine the reg in Dev Tools.

**Comment by sokra** [comment]
This is working as intended. There is no technical problem with `import(expr)` and this used to work in I think webpack 1 and 2 or so, but we disabled this behavior as this is in 99% not the behavior you want. A fully dynamic expression includes many many modules and blow up your bundle. So we only handle partially dynamic imports by default.

But hey if you want to enable webpack handling unknown expressions too set: `module.unknownContextRegExp: /^\.\/.*$/`
