### ISSUE TITLE
Signature changed: context parameter added

### ISSUE THREAD

**Issue by DeliciousFishCYY** [webpack/webpack#4293]
Hi ,I have a problem of webpack,
the error is below:
**node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:32
		throw new Error("Signature changed: context parameter added");
		^

Error: Signature changed: context parameter added**

and Resolve.js is:
Resolver.prototype.resolve = function resolve(context, path, request, callback) {
	if(arguments.length === 3) {
		throw new Error("Signature changed: context parameter added");
	}

I didn't change my project code but when I run 'npm start'or 'npm run dist'to start my project ,this error was thrown,
anyone know how to solve this error?

**Comment by bebraw** [comment]
Any chance for a little project to study or a full trace? There's not enough information to tell what broke it.

**Comment by DeliciousFishCYY** [comment]
Hi @bebraw ,I have reinstalled webpack and the error was resolved.. if the error shows again ,I would reopen it ..

**Comment by bebraw** [comment]
Sure, thanks.
