### ISSUE TITLE
Webpack 2 entry doesn't allow array of object?

### ISSUE THREAD

**Issue by eldyvoon** [webpack/webpack#4294]
I used this and it work in webpack 1

```
entry: {
	vendor 	: ['react', 'react-dom', 'react-router', 'classnames', 'lodash', 'alt'],
	app 	: ['webpack-dev-server/client?http://localhost:8080',
                'webpack/hot/only-dev-server',
                path.resolve(__dirname, PATHS.app, 'entries', 'app.js')],
         otherFile : ['webpack-dev-server/client?http://localhost:8080',
                'webpack/hot/only-dev-server',
                path.resolve(__dirname, PATHS.app, 'entries', 'otherFile.js')]
}
```

But this won't work in webpack 2, it worked when I removed the otherFile` property. How do I use HMR and multiple entires? in this guide https://webpack.js.org/guides/hmr-react/ it used array but in my case I'm also using multiple entries.

**Comment by bebraw** [comment]
Hi,

I don't see the `landing` property you mentioned in your example. How does it fail exactly? Please see the issue template for the information that's needed.

**Comment by eldyvoon** [comment]
@bebraw updated my question

**Comment by bebraw** [comment]
Ah, I understand better now. Maybe you could drop the HMR related entries altogether and use webpack-dev-server inline mode instead? There are some limitations to that so I guess that's why you avoided it.

It's hard for me to say anything more without extra information. Maybe someone else has more ideas.

**Comment by eldyvoon** [comment]
@bebraw, I just want to verify webpack 2 has dropped the support for array of object? Because it used to worked in webpack 1.

**Comment by bebraw** [comment]
Any ideas @SpaceK33z? Should the array of objects format work with webpack 2 still?

**Comment by SpaceK33z** [comment]
Yes the format @eldyvoon is using should still work. What exactly do you see / is not working?

**Comment by eldyvoon** [comment]
@SpaceK33z  I think it's caused by loader issue. I really need need help on this https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/412#issuecomment-280606217
