### ISSUE TITLE
webpack.optimize.UglifyJsPlugin doesn't work on OSX but does on Windows.

### ISSUE THREAD

**Issue by Bram-Zijp** [webpack/webpack#4296]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
webpack.optimize.UglifyJsPlugin plugin doesn't work on OSX but does on Windows

**If the current behavior is a bug, please provide the steps to reproduce.**
            new webpack.optimize.UglifyJsPlugin({
                mangle: true,
                minimize: true,
                comments: false,
                compress: {
                    warnings: false,
                },
            }),
            errored on '{': /* harmony default export */ __webpack_exports__["default"] = class {

**What is the expected behavior?**
Work on both platforms.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Node 7.4.0 npm 4.05     "webpack": "^2.2.0-rc.0",

**Comment by bebraw** [comment]
Can you try upgrading to the newest version of webpack? If it still fails, please set up a small project to study.

**Comment by Bram-Zijp** [comment]
I had an es6 node_module which was excluded from babel compilation.

Got the [answer](http://stackoverflow.com/questions/42278587/webpack-uglifyjsplugin-doesnt-work-on-osx-but-does-on-windows/42279257?noredirect=1#comment71716204_42279257) from Stackoverflow

If you're using webpack 2, chances are that you have a dependency to some module that has the jsnext:main configuration option to provide its code as ES6 modules. In these cases, webpack 2 uses them, which works fine, until you try to use Uglify, which can't deal with ES6 code.

You're probably excluding your node_modules from Babel loading, as well you should, but for this to work, you need to tell webpack explicitly to include this jsnext:main module.

I had this problem with preact-compat and solved it like this:

```
module: {
    rules: [
        {
            test: /\.js$/,
            loader: 'babel-loader',
            include: [
                path.resolve(__dirname, './src'),
                path.resolve(__dirname, './node_modules/preact-compat/src')
            ]
        }
    ]
}
```

**Comment by bebraw** [comment]
Ok, cool. Time to close.
