### ISSUE TITLE
Outputting compiled html to file?

### ISSUE THREAD

**Issue by syranide** [webpack/webpack#430]
I intend to use hashes everywhere I can with webpack, because it solves so many problems. However, we want to serve the root `html` as a static file (not by node).

I looked around a bit and found the `html-loader` and it's exactly what I want when paired with the `file-loader`, but it outputs code that has to be evaluated to resolve requires to the final URLs (to images, scripts, etc). Just thinking out loud, would it be possible to have some kind of `eval-loader` that would evaluate the code and return the result?

(I apologize if I overlooked something, it's hard to get a great overview of the endless possibilities :))

**Comment by mogelbrod** [comment]
I'm looking for a solution to this use case as well, did you come up with anything @syranide?
See #536 for my current progress.

**Comment by wmertens** [comment]
This sounds exactly like what [val-loader](https://github.com/webpack/val-loader) does. For example, `'file!val!html!foo.html'` will parse the html for requirements and store it in a file.

**Comment by bebraw** [comment]
@syranide Did val-loader work for you?
