### ISSUE TITLE
fix .npmignore / published package contents

### ISSUE THREAD

**Issue by necolas** [webpack/webpack#431]
Installing 1.3.7 still includes the entire repo and nothing is ignored. I think you'll need to either drop the leading `/` in the paths, or make it `./`.

**Comment by dandv** [comment]
I see `.npmignore` is no longer used; instead there's a [`files` section in package.json](https://github.com/webpack/webpack/blob/next/package.json#L81).

However, after ` yarn add webpack@webpack/webpack#next --dev` I ended up with irrelevant files and directories installed, like .travis.yml or `.github`:

![image](https://user-images.githubusercontent.com/33569/35184020-7a3aaa24-fda4-11e7-87ef-230afb1d5b6b.png)

**Comment by sokra** [comment]
This happens because you install from git. This won't occure in the published package on npm.

**Comment by dandv** [comment]
@sokra: I did install using `yarn add webpack@webpack/webpack#next`.
