### ISSUE TITLE
Different error, based only on devtool setting.

### ISSUE THREAD

**Issue by aocenas** [webpack/webpack#4312]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
With same code that has a bug, there is different error reported based on what kind of devtool is setup.

**If the current behavior is a bug, please provide the steps to reproduce.**

Code:
```
const React = require('react');

module.exports = (props) => {
    return (
      <div>
        <h1>App</h1>
        <ul>
          <li><Link to="/about">About</Link></li>
          <li><Link to="/inbox">Inbox</Link></li>
        </ul>
        {props.children}
      </div>
    )
};
```

With `devtool: 'cheap-module-eval-source-map'`:
`Uncaught ReferenceError: React is not defined`

With `devtool: 'inline-source-mapp'`, correct error is reported:
`Uncaught ReferenceError: Link is not defined`

**What is the expected behavior?**
Both devtools report the same error

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Webpack: 2.2.1
node: v6.9.1

Maybe related to this issue https://github.com/webpack/webpack/issues/954

**Comment by sokra** [comment]
fixed in Chrome 57
