### ISSUE TITLE
SyntaxError: Unexpected character '`' [0.0972f70db899961b2a15.hot-update.js:16,9]

### ISSUE THREAD

**Issue by sebfindling** [webpack/webpack#4318]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When I try to pack using `--optimize-minimize` it fails if I have strings written with `grave accent` character (template string)

**If the current behavior is a bug, please provide the steps to reproduce.**
Try to print a string using template characters instead of regular string characters
```javascript
alert('regular string, works')
alert(`template string containing ${variables} wont work`)
```

**What is the expected behavior?**
It should pack normally

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
NodeJS v6.9.5
Windows 10.0.14393
Webpack 2.2.1

**Comment by sokra** [comment]
UglifyJs2 doesn't support ES5 yet.

As workaround run `npm install https://github.com/mishoo/UglifyJS2#harmony` to get the harmony branch. Or transpile with babel.
