### ISSUE TITLE
Performance hints output contains excess commas

### ISSUE THREAD

**Issue by gribnoysup** [webpack/webpack#4324]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Performance hints output contains excess commas

```
WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (250 kB). This can impact web performance.
Entrypoints:
  entry0 (725 kB)
      ./build/entry0.js
,
  entry1 (725 kB)
      ./build/entry1.js
```

**If the current behavior is a bug, please provide the steps to reproduce.**

I created a repo with reproduction https://github.com/gribnoysup/webpack-perf-output.git

```
git clone https://github.com/gribnoysup/webpack-perf-output.git
cd webpack-perf-output
npm i
npm run build
```

**What is the expected behavior?**

No excess commas in output

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

```
node 6.9.4
npm 3.10.10
webpack 2.2.1
```

This happens because of a small bug in this file https://github.com/webpack/webpack/blob/ecc2adbbfac51776355add90c24481a42f0cb519/lib/performance/EntrypointsOverSizeLimitWarning.js#L18, `entrypointList` and `entrypoint.files` are joined without parameter.

I know this is small, but so annoying 😭  I can submit a pull request with a fix if you want

**Comment by Dean-Coakley** [comment]
Might have fixed this but I don't know how to test.

Can you tell me how to test or what my code should look like.
Sorry, it is my first contribution and I don't even know too much js.

Thanks.

**Comment by sokra** [comment]
test it with `test\statsTests`

**Comment by Dean-Coakley** [comment]
Tests pass but how do I test against the webpack-perf-output?

**Comment by sokra** [comment]
Do you want to add a new test scenario or do you want to test your version against the webpack-perf-output repo?

**Comment by Dean-Coakley** [comment]
I am hoping to test my version against the webpack-perf-output repo.
