### ISSUE TITLE
compiler fails and stops if a plugin calls callback with error

### ISSUE THREAD

**Issue by jchip** [webpack/webpack#4326]
**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**

Compiler stops if a plugin calls callback with error.

**If the current behavior is a bug, please provide the steps to reproduce.**

`webpack.config.js`:

```js
class Foo {
  constructor() {
    console.log("Foo");
  }

  apply(compiler) {
    compiler.plugin("after-emit", (compileation, callback) => {
      callback(new Error("foo"));
    });
  }
}


class Bar {
  constructor() {
    console.log("Bar");
  }

  apply(compiler) {
    compiler.plugin("done", (stats) => {
      console.log("Bar done");
    });

    compiler.plugin("fail", (error) => {
      console.log("Bar fail");
    });
  }
}


module.exports = {
  entry: "./app.js",
  output: {
    filename: "bundle.js"
  },
  plugins: [
    new Foo(),
    new Bar()
  ]
};
```

`app.js`:

```js
console.log("hello");
```

**What is the expected behavior?**

`done` and/or `fail` in `Bar` called.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

```
$ node -v
v6.9.2
$ node_modules/.bin/webpack -v
2.2.1
$ npm -v
3.10.10
$ uname -a
Darwin L-SB8H1M2G8W-M.local 16.0.0 Darwin Kernel Version 16.0.0: Mon Aug 29 17:56:20 PDT 2016; root:xnu-3789.1.32~3/RELEASE_X86_64 x86_64
```

**Comment by sokra** [comment]
While watching the `failed` plugin is called.

When calling `run` or `compile` the error is passed in the callback.

**Comment by satazor** [comment]
@sokra is there any reason to not be consistent?

**Comment by satazor** [comment]
I guess this is intended @jchip, see: https://github.com/webpack/docs/wiki/plugins/ad6ef7e44bec0c2f1a545a5d983a0938966ccaee#failederr-error

**Comment by sokra** [comment]
while watching `failed` could be called multiple times. `watch` just starts the watching.

`run` and `compile` are one-time operations, which "return" with success or error.
