### ISSUE TITLE
custom module/loader resolution - callbacks in resolve.modules?

### ISSUE THREAD

**Issue by jchip** [webpack/webpack#4327]
**Do you want to request a *feature* or report a *bug*?**

Not sure yet, probably request a feature.  
I've been looking at this doc here and it seems I can only provide array of paths for webpack to resolve modules, but please correct me if I am wrong.  I'd like to be able to provide a callback that can do custom module resolution.

https://webpack.js.org/configuration/resolve/#resolve-modules

**What is the current behavior?**

Only paths in `resolve.modules` array.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

Allow user to provide custom modules/loaders resolve logics.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

webpack 2.2.1

**Comment by sokra** [comment]
You can write a resolver plugin for this. `resolve.modules` is translated into plugins here: https://github.com/webpack/enhanced-resolve/blob/master/lib/ResolverFactory.js#L177-L182

Write a similar plugin for your own needs. You can pass it to `resolve.plugins`.

**Comment by jchip** [comment]
awesome! thank you so much.

created a sample here https://github.com/jchip/webpack-resolve-plugins-sample
