### ISSUE TITLE
tree shaking  broken

### ISSUE THREAD

**Issue by githoniel** [webpack/webpack#4328]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
tree shake broken when a nouse export using another module
**If the current behavior is a bug, please provide the steps to reproduce.**
Repo here
https://github.com/githoniel/tree-shake-bug
```js
//main.js  use as entry 
import { cell } from './index
console.dir(cell)
```
```javascript
//index.js
import { default as cell } from './posUI/cell'
import { default as scroll } from './posUI/scroll'
export {
    cell,
    scroll
}
```
when scroll is like below，tree shake function well，it will remove 'asdasdasd'
```javascript
//scroll.js
var a ='asdasdasd'
export default a
```
But if change to 
```javascript
//scroll.js
import a from './scrollData'
export default a
```

```javascript
//scrollData.js
export default 'aaaaa'
```
tree shake no effect now，'aaaa' still in bundle file

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Webpack 2.2.1
Node 6.9.2
OS win10 x64

**Comment by Kovensky** [comment]
```js
import a from './scrollData'
export default a
```

This actually exports the _current value_ of `a` as the value of the default export of this module.

If you actually want to reexport `./scrollData`'s `default` as the default export of `scroll.js`, you need to do one of these:

```js
export { default } from './scrollData'
```

```js
import  a from './scrollData'
export { a as default }
```

**Comment by githoniel** [comment]
@Kovensky  it work now, thank you very much~~~~
