### ISSUE TITLE
`System` compiled into object literal causing syntax error

### ISSUE THREAD

**Issue by MadLittleMods** [webpack/webpack#4329]
Webpack is compiling `System.global = { foo: 'bar' };` into `{}.global = { foo: 'bar' };` which throws a syntax error,
```
Uncaught SyntaxError: Unexpected token .
```

This affects the [`system.global@1.0.0` package](https://github.com/ljharb/System.global/blob/a2b8b5b01a82dd305ff2fe594512b03580a5c1fa/shim.js) which is depended on by the [`array.from` polyfill](https://github.com/mathiasbynens/Array.from/issues/48) for example.

### Reproduction

Standalone demo, https://gist.github.com/MadLittleMods/fd23fe19d287047ceb70f325f2fcd25a

`webpack@2.2.1`

`webpack.config.js`
```js
const config = {
  devtool: 'inline-source-map',
  entry: './entry1.js',
  output: {
    path: './build/',
    filename: '[name].js'
  }
};

module.exports = config;
```

`entry1.js`
```js
System.global = { foo: 'bar' };
```

Output `main.js` build snippet:
```js
{}.global = { foo: 'bar' };
```

```
Uncaught SyntaxError: Unexpected token .
```

**What is the expected behavior?**

Output `main.js` build snippet:
```js
System.global = { foo: 'bar' };
```

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

 - node@6.7.0
 - webpack@2.2.1
 - Windows 10

**Comment by ljharb** [comment]
This is very critical, since the `System` object will need to be polyfilled by multiple things over the years.

**Comment by timse** [comment]
whats the appropriate way to access or check for `System` ?

**Comment by bebraw** [comment]
I think this might go wrong at `lib/dependencies/SystemPlugin.js`. That's where I would start to investigate.

**Comment by timse** [comment]
Yes thats where it fails. The question is what to do with System? Is that even a thing anymore?

**Comment by ljharb** [comment]
`System.import` is not, but there are other proposals that will want to attach to a `System` object.

**Comment by timse** [comment]
so basically a global polyfill would be required, that makes sure `System` is kind of a singleton, that can be shared right?
A simple injection of a `{}` as `System` into modules that use it would not fix that? @ljharb

**Comment by ljharb** [comment]
@timse i'm confused - if webpack wants to `if (typeof System === 'undefined') { System = {}; }` that's fine, but if code references `System` it should not be touched, ever.

**Comment by timse** [comment]
well currently webpack handles`System` by preevaluating things like `if (typeof System === 'undefined') { System = {}; }` to `if (false) { System = {}; }`. (see https://github.com/webpack/webpack/blob/master/lib/dependencies/SystemPlugin.js#L28-L33)
This means you basically cant do the above thing as of now. 
The question therefore is how to solve this to make it make the most sense :).

**Comment by ljharb** [comment]
You should never have been able to do that. Users could always have created their own global called "System".

I'd simply remove that invalid "optimization".

**Comment by ljharb** [comment]
Ah wait - actually the typeof optimization is perfectly fine. The bug here is ever replacing `System` itself.
