### ISSUE TITLE
Feature - Validate resolve.alias paths

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack#4335]
**Do you want to request a *feature* or report a *bug*?**

Feature.

**What is the current behavior?**

`resolve.alias` paths aren't validated. This can lead to runtime errors.

**What is the expected behavior?**

Webpack should validate `resolve.alias` (and `resolveLoader` too?) to catch issues early on.

**If this is a feature request, what is motivation or use case for changing the behavior?**

It would lead to easier to understand errors for the users.

**Comment by sergiorojasa** [comment]
I would like to work on this and I need some guidance

**Comment by bebraw** [comment]
@sergiorojasa See the [schemas](https://github.com/webpack/webpack/tree/master/schemas) and how they are used from the source. I expect this might require custom logic.

One direction would be  to extend [ajv](https://www.npmjs.com/package/ajv) with a path type that would handle the path validation. See ajv documentation on how to achieve this.

**Comment by aight8** [comment]
This is not so easy as I assumed. The **alias** and the **alias target** are very flexible, almost so flexible that it confuse lot of people.
See: https://webpack.js.org/configuration/resolve/#resolve-alias
There is a very nice table about the resolution strategy but I never can memorise every case.

The difficult thing is that **alias target** can be lot of thing:
- an absolute path (/absolute/path)
- a relative path (./relative/path)
- a module (module)

Paths to folder which not contains a **mainFile** or not resolved by any **resolver plugin** are only resolvable with a concrete request.

So the validation must implement a custom logic. But instead of implement this analyser in webpack directly, it were better if **enhanced-resolve** provide such this functionality. Then this logic could be used for example by a **config analyser** or a **cli resolver** for debugging.

I just paste here some code I am currently working on to output some useful information about the passed webpack config. (no tests)

So what I want to show is this code return a debugging structure which can be processed for lot of use cases.

```TS
import {
    ResolverFactory
} from 'enhanced-resolve'
import path from 'path'
import fs from 'fs'
import Resolver from 'enhanced-resolve/lib/Resolver'

type AliasResolveResult = {
    aliasDefinition: string,
    testAlias: string,
    type: 'module' | 'directory' | 'directory-with-default' | 'file',
    warning: string,
    target: string,
}

type ResolverInfo = {
    alias: AliasResolveResult[],
}

export default class ResolverTester {
    resolver: Resolver;
    context: string;
    resolverConfig: ResolverFactory.ResolverOption;

    constructor(webpackInstance: any, resolverConfig: ResolverFactory.ResolverOption) {
        this.context = webpackInstance.options.context;
        this.resolverConfig = resolverConfig;

        const resolverOptions = Object.assign({
		  fileSystem: webpackInstance.inputFileSystem,
	    }, resolverConfig) as ResolverFactory.ResolverOption;

        const normalModuleResolver = ResolverFactory.createResolver(resolverOptions);

        this.resolver = webpackInstance.resolvers.normal;
    }

    private resolve(request: string) {
        return new Promise((resolve, reject) => {
            this.resolver.resolve(this.context, this.context, request, (err, res) => {
                if (err) {
                    reject(err);
                } else {
                    resolve(res);
                }
            });
        });
    }

    private checkAbsoluteFolder(request: string) {
        if (path.isAbsolute(request)) {
            if (!fs.existsSync(request)) {
                throw new Error('absolute path not exists'); // absolute path not exists at all
            }
            if (!fs.statSync(request).isDirectory()) {
                return false; // absolute path points to a file
            }
            try {
                fs.accessSync(request, fs.constants.R_OK)
            } catch(ex) {
                throw new Error('absolte path is not readable'); // absolute path is not readable
            }
            return true;
        }
        return false;
    }

    public async getInfo(): Promise<ResolverInfo> {
        let aliasInfos = [];

        for (let alias in this.resolverConfig.alias) {
            let aliasTarget = this.resolverConfig.alias[alias];
            let type = null;
            let warning = null;
            let resolvedPath = null;
            let aliasUsage = null;
            let defaultModule = null;

            try {
                if (alias.endsWith('$')) {
                    aliasUsage = alias.substr(0, alias.length - 1);
                } else {
                    aliasUsage = alias;
                }

                let isAbsoluteFolder = this.checkAbsoluteFolder(aliasTarget);
                if (isAbsoluteFolder) {
                    try {
                        defaultModule = await this.resolve(aliasUsage);
                        type = 'directory-with-default';
                    } catch(ex) {
                        type = 'directory';
                    }
                } else {
                    let resolveResult = await this.resolve(aliasUsage);
                    type = 'module';
                    resolvedPath = resolveResult;
                }
            } catch(ex) {
                warning = ex.message;
            }

            aliasInfos.push({
                aliasDefinition: alias, // the original alias definition (can contain $ at the end)
                aliasUsage, // the alias without the optional trailing $
                type,
                target: aliasTarget,
                resolvedPath,
                warning,
                defaultModule,
            });
        }

        return {
            alias: aliasInfos,
        };
    }
}
```

**Comment by bebraw** [comment]
@aight8 Great research. I agree completely that pushing the logic to one place (enhanced-resolve) is the way to go. Doing this right would make it far easier to work with aliasing. 👍
