### ISSUE TITLE
webpack 3: Isolate webpack CLI config | change request

### ISSUE THREAD

**Issue by aight8** [webpack/webpack#4340]
It seems not so clean that **webpack cli only configuration** are mixed with **webpack internal one**. Like stats etc.
Online in the docs there are mostly noted, but when you just in the source code, this is confusing.

So I think it's essential to split the config as soon as possible and put the cli related configs under the webpack config prop "cli", **same like the configs for the devServer**. This is consistent than.

webpack config Brainstorming:
```
{
   cli: {
      watch: bool,
      watchOptions: WatchOptions,
      stats: {},
   }
}
```

When using the webpack CLI, it's just set the config keys under the ```cli``` prop (much how it is already). Primary just the location changes.

I don't think the nesting in another prop hurts anyone. It will become even more clearer.

webpack cli will be become another package sometimes anyway (https://github.com/webpack/webpack-cli) - so maybe this was already discussed by the webpack team.

----
Let's discuss, however I feel free to edit this issue when I came up with new ideas.

**Comment by sokra** [comment]
`watch` and `watchOptions` are webpack options and not CLI options.

It's true for `stats`. But it's only a single property.
