### ISSUE TITLE
webpack 3: Use config factories for plugins / other config related improvements

### ISSUE THREAD

**Issue by aight8** [webpack/webpack#4342]
This issue is addressing the major weakness of the webpack configuration.
Webpacks config is notorious of it's complexity - however I know so much configuration of other apps which are way bigger but **way** easier to learn.

So let's clean the flaws like apple and don't keep the registry of 1990 like windows. Skip the crap. 

- **Serialisable configuration** (Totally no stable solution today because the Plugin objects cannot be deserialised to the initial options argument. This is the biggest pain!)
   - Cannot be **formatted nicely and printed** to the console without any heavy formatting algorithms - at the end of the day I have no clue how the generated webpack config looks like which are applied to webpack - I just trust the generation code / BTW: the same problem for webpack cli flag user.
   - Cannot be **cached / persisted** (mainly for logging / process-later purposes)
   - Cannot be **shared good** (for example I write lot of issues, but I never could post the webpack config because it is generated - and those output is not only verbose but it contains sensible data.)
- **Merging**
   - There are so many config-merging-like libraries. This really should be a standard feature. It must be flexible but not so complex to confuse people. (In this PR I introduce presets)
   - Common use cases:
      - Config based on environment variable
      - Config based on cli input variable
      - (new concept) Config based on a custom json file (which contains only high level configs)
      - Config for **development** / **production** build
      - Config for **client** / **server** build
      - Config for different modes: **compile-once** / **watch** / **dev-server**
   - Some functionalities are difficult to setup because It need different adjustments in the configuration (one example: webpack-dev-server) - presets can solve that issue
- **Configuration key meaning**
   - The config key naming could be improved. The initial idea to have flat and short config keys which user can remember, pulled too much on the meaningfulness. This is **really** a big problem.
   - webpack cli only configuration are mixed with the rest of the webpack config

---

I came up with so much ideas while writing this issue, so I added "/ other config related improvements" to the issue name. Happy discussion!*

The issue #4340 (webpack 3: Isolate webpack CLI config | change request) which I created before contains some cli config related requests - but it's also a part of the configuration idea.

The problem currently of the webpack config is that it's not serialisable.

So just image you register a plugin at the beginning of the webpack config generator like:
```JS
const ExtractTextPlugin = require("extract-text-webpack-plugin");
webpack.registerPlugin(ExtractTextPlugin);
```
- ExtractTextPlugin would be interpolated to extract-text-plugin (lookup the constructor name)
- The other variant is that it search for installed modules and you can skip the register step - same like loaders do.

Then you enable and configure the plugin in the webpack config like:
```JS
{
   plugins: [
      {
          use: 'extract-text-plugin',
          options: {
              ....
          }
      }
   ]
}
```

This is similar how resolvers work. Benefits:
- better shareability
- persistent of a specific webpack config (for later analyse / debug)
- plain json configuration is much more a configuration - **readability**
- **consistence** - they configuration could be similar to the module loaders config (like in the demonstration) - it's easier to learn it then
- webpack configuration could be written in none-js formats entirely (however it's common to generate the config)
- if somebody use TypeScript (maybe flow soon), you can add plugins with autocompletion! after you defined the plugin name, there is full autocompletion for the options, too.
- Output the final merged configuration (by the new preset system or whatever merging strategy you have today) to the console (format it not only json) - but you must not care about javascript Objects which create verbose output

---

Further ideas:

```JS
plugins: [
   // (1) string style (no options, like in loaders)
   'webpack-md5-hash',
   
   // (2) object style (options will passed to the plugin constructor)
   { plugin: 'limit-chunk-count-plugin', options: { maxChunks: 1, }, },
   { plugin: 'webpack-cleanup-plugin', options: { exclude: ['assets.json'], },

   // (3) object style - with plugin short name (like babel presets/plugins or the old webpack loader config)
   { plugin: 'cleanup', options: { exclude: ['assets.json'], },

   // (4) array thunk syntax (like babel options)
   ['cleanup', { exclude: ['assets.json'], }]

   // let create some more... (with short syntax)
   ['common-chunks', { name: 'vendor', }],
   ['define', { PRODUCTION: '"true"', DEVELOPMENT: '"false"' }],
   ['environment', ['NODE_ENV', DEBUG]],
   ['extract-text', { fallback: 'style', use: ['css-loader', 'scss-loader'] }],
   ['uglifyjs'], // without options, same as 'uglifyjs' only

   // it's very comfortable and fast to write though
   // it's very compact
   // you can read the line fluently
],
```

The variant (3) with the short name must be discussed. Webpack skipped the name resolve without "-loader" but allow it to configure the old behaviour again. Maybe a plugin resolver strategy could be defined.

The last variant (4) is based on the babel preset/plugin options style - but I listed it - as an additional style for discussion. However the **disadvantage** of this style is:
- One additional style people have to know and split up the preference of the community
- Not consistent with loader config style
For the advantages:
- The plugin name is straight at the beginning without any ```{ plugin: '``` - it's easier to read.
- Maybe in yaml and other formats this would end up in a even better configuration appearance

**Some special use cases:**
```JS
{
   plugins: {
      // consume a dll manifest
      ['dll-reference', { manifest: '/path/to/dll/output/dll.manifest.js'), }],

      // some more
      ['no-emit-on-errors'],
   }
}

{
   presets: {
      // * dll library creator preset *
      // sets output.filename (ex: dll.js)
      // sets output.library (ex: dll)
      // adds plugin DllPlugin { path: 'dll.manifest.js', name: 'dll' }
      ['dll', { name: 'dll', }],
     
      // * create hot replacement feature to the build *
      // adds plugin HotModuleReplacementPlugin
      // adds 'webpack/hot/dev-server' to every entry (because this is a dynamical process there must be a new webpack config which allows to add a module to every entry!)
      // adds 'webpack-dev-webpack/client?http://localhost:8080' to every entry
      // the last step "devServer: { hot: true }" is not build related however it adds this to the current config (webpack config must be started then with webpack-dev-server)

      // source: https://github.com/webpack/webpack-dev-server/issues/97#issuecomment-69726201
      'hot-module-replacement',

      // now something more complex (preset provided than for example by happypack)
      // now something very cool - happypack! (until webpack lacking off parallel compilation)
      // adds plugin new HappyPlugin ( id: <id>, loaders: <loaders> )
      //    (in the new manner it adds it in the configuration format not as object!!!)
      // adds module rule { test: <ruleTest>, loader: 'happypack/loader', options: { id: <id>, } }
      {
         preset: 'happy-pack',
         options: {
            id: 'js',
            loaders: [{ loader: 'babel-loader', options: { /* babel options */ },},],
            ruleTest: '\.jsx?$',
            // rule... - the other rule configuration (this however can be solved in other way)
         }
      }

      // node preset (a part of it)
      // set target.node = node
      // adds 'source-map-support/register' to all entries
      // use webpack-node-externals/nodeExternals to set externals config key - push item "source-map-support/register" to it
      // set node config key to (__dirname: false, __filename: false) as default
      // add plugin { plugin: 'limit-chunk-count-plugin', options: { maxChunks: 1, }, }, as default
      {
         preset: 'node',
         options: {
            nodeExternalsWhitelist: [],
            oneFile: true, // default
         }
      }
      
      // a nice example of the usage of a custom preset (or a preset someone created)
      // adds loader rule { test: <ruleTest>, loader: 'babel-loader', options: {} }
      // babel options are set dynamically:
      //   - always: transform-runtime, etc.
      //   - if target = web: use latest-preset
      //   - if target = node: use env-preset
      //   - if target = web && isDev: react-hot-loader/babel
      // useHappyPack: alternatively this preset could use optionally the happy-pack preset
      {
          preset: 'babel',
          options: {
             ruleTest: '\.jsx?$',
             target: 'web' | 'node', // because presets are predictable only by it's options and have no access to the merging webpack config this option must be set again. maybe there is another solution.
             isDev: true, // default
             useHappyPack: true, // default
          },
      }
   }
}
```
---

# More config improvements

It were interesting, if webpack config could be environment variable aware. Then it merges a environment specific config to the root webpack config. This would solve the webpack config management for lot of persons - WITHOUT using any plugin and custom code.

# Plugin enable / disable by property

This could be handy if implement environment based merging.

```JS
let plugins = {
   {
      plugin: 'limit-chunk-count-plugin',
      enable: false, // <-- enable the plugin
      options: {
          maxChunks: 1,
      },
   },
}
```

# Plugin instance ID / merge options

**id**: This could be handy for the merging process. If **id** is present, it uses the selected strategy under ```mergeStrategy``` to merge the options.

**mergeOptions**: How two options object should be merged.

**constructorArgs**: This could be a solution for backward compatibility - so a plugin can compatible to older webpack too. **I don't like it**, but it's an option.

constructorArgs: [{ maxChunks: 1, }]
same as:
options: { maxChunks: 1, }

```JS
let plugins = {
   {
      plugin: 'limit-chunk-count-plugin',
      id: 'instance', // <-- the id of the plugin instance
      mergeStrategy: 'override' | 'deep-merge', // or mergeOptions. the default must be discussed.
      options: {
          maxChunks: 1,
      },
   },
}
```

# More plugin aliases config

I don't have a whole list here, but it would be maybe even better to add additional configuration props for webpack internal plugins.

For example ```LimitChunkCountPlugin``` could be another webpack config prop under a specific config prop. Same for NoEmitOnErrorsPlugin and many others.

It's important to make a meaningful but not to deep config nesting.
webpack have some weekness there - which results that people don't understand configuration at first.

```JS
{
   optimization: {
     // ...
   },
   //entry: {} - existing configuration - just to see the naming similarity - list {name: path}|...
   //module: {} - existing configuration - configuration regarding modules - "how they processed"
   //resolve: {} - existing configuration - configure how modules/loaders are resolved
   chunks: {
     maxCount: 1, // --optimize-max-chunks 15 new webpack.optimize.LimitChunkCountPlugin({maxChunks: 1})
     minChunkSize: 10000, // --optimize-min-chunk-size 10000 new webpack.optimize.MinChunkSizePlugin({minChunkSize: 10000})
     // btw: allow write 500kB etc. - readability!
     filename: '', // the configuration from output.chunkFilename
   },
   bundles: {
     filename: '', // output.filename
   },
   assets: {
       
   },
   compilation: {
      emitErrors: false, // false = use NoEmitOnErrorsPlugin
      pathinfo: '', // output.pathinfo - pathinfo beside output.path was confusing. pathinfo extends the compilation some path information
      sourcePrefix: '\t',
      libraryTarget: '\t',
      library: '', // output.library |  maybe better 'libraryName'
      libraryTarget: '', // output.libraryTarget | Default: "var"
      web: {
         jsonpFunction: '', // output.jsonpFunction
         crossOriginLoading: '', // output.crossOriginLoading
      },
      hotUpdate: {
         chunkFilename: '', // output.hotUpdateChunkFilename
         function: '', // output.hotUpdateFunction
         mainFilename: '',  // output.hotMainFilename
      },
   },
   output: { // (same) - it has only props which are directly the output files related
      path: '',
      publicPath: '',
      //filename: '', // or maybe rename this to bundleFilename - this some extra chars can help users to understand the configuration better - it's not more verbose than
      //chunkFilename: '',
      sourceMapFilename: '',
      // ...
   },
}
```
The above example is work in progress and is just an idea for brainstorming.

# Webpack config presets

Webpack presets are merged in the final webpack config.

- They can be used for **environment variable** based config.
- No more "when use webpack -p or webpack -d" webpack add this and that. It just uses a specific preset, which everybody understand.
- Presets can be shared! We love share don't we?

Webpack use internally some kind of config manipulation for example if using ```target: 'node'```.
This were good examples for presets, too.

**Brainstorming config:**
```JS
// webpack config
{
   // ??definePresets:??
   
   // use presets
   presets: { // use this presets
      {
         name: 'some-preset', // resolved as module (like loaders/plugin factory above)
         enable: true, // <- generated bool
         enableForEnv: 'PRODUCTION', // <- for non-js config solutions, if PRODUCTION is a true value (for safety it is not true if the env var only exists, if it's falsy, it also mean false)
         // ?? options: {}, // this are options for the preset and can alter the output
      }
   }
}
```

# Old config changes

## performance
The ```performance``` webpack config prop is strange somehow.
Maybe better were use ```hints``` directly as root prop key.
Look at the docs:
```
hints: "warning", // enum
hints: "error", // emit errors for perf hints
hints: false, // turn off perf hints
```
It says it already, it "emit" something. So the whole config section could become:
```
- hints
   - emit: 'error' | 'warning' | false // were 'warning is the default
```

## devtool
```devtool: <sourceMapType>``` is one of the config key which is the most confusing one.
Do not take it personal, I understand webpack have a long history since it's revolution.
But shouldn't we rename it finally to ```sourceMap``` ? ;)

## devServer
Just maybe: Maybe a warning when this config key is filled but the config is consumed by webpack api instead of the webpack-dev-server. The warning must be ignorable (--ignoreDevServerConfig)
New users try this out see no effect.

## node
The config key "node" is to abstract

---
more discussion is needed, but I created this issue quickly so I don't forget it.

**Comment by TheLarkInn** [comment]
Hey thank you for this detailed proposal. Would you mind moving this to #2797 and then closing this one. That way there can be discussion amongst all those who would like to be involved.

**Comment by aight8** [comment]
@TheLarkInn  I just looked at the last post from @dmitriid and he came up with exactly the same idea regarding config plugin factories with exactly the same style ;) But that's nice to see! Sure let's discuss there.

**Comment by dmitriid** [comment]
@aight8 Oh wow. Your proposal is AWESOME! Please, please, please move it to #2797 so it doesn't get lost in closed tickets!
