### ISSUE TITLE
Add a loader option to exclude/include files in a module's dependency tree

### ISSUE THREAD

**Issue by philipwalton** [webpack/webpack#4346]
**Do you want to request a *feature* or report a *bug*?**

Request a feature.

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

The current `include` and `exclude` loader options allow developers to include/exclude particular files, but in many cases its far more useful to include/exclude entire branches in the dependency tree.

This will become more and more important (specifically in the case of babel-loader) as more and more browsers begin to natively support ES2015+ features. Right now it's common for module authors to publish the compiled versions of their code, but I don't think that should be considered a best practice going forward.

Consider this scenario: if one or more of my module dependencies publish their source files as ES2015, it's much more complicated than it should be to include them in the transpilation step while _also_ excluding all other modules because it requires intimate knowledge of that module's dependency tree.

You can whitelist (via `include`) certain modules, but this won't always work because you need to know the full module path, which is problematic since npm sometimes installs a module directly under `node_modules` and other times it installs a module in a nested `node_modules` folder.

To solve this issue, I think it'd be nice to add something like an `excludeTree` option. This option would accept an array of npm module names and exclude any files in that module's source as well as any files in the source of any of its dependencies (via `package.json`).

```js
{
  excludeTree: ['react', 'core-js'],
}
```

`excludeTree` is useful for cases where *most* of your dependencies need to be transpiled. Today, however, the norm is that most of your dependencies are published as ES5, so in these cases what you generally want to do is something like the following (which assumes a `matchesExcludeTree()` function exists):

```js
{
  exclude: (absPath) => {
    // Exclude all node modules *unless* they're in the following list
    // of packages (and their dependencies).
    return absPath.includes('node_modules') &&
        !matchesExcludeTree(absPath, ['autotrack']);
  }
}
```

Perhaps in this case it makes sense to have `exclude`/`excludeTree` work in conjunction with `include`/`includeTree`. That way the above imperative logic could be rewritten declaratively like this:

```js
{
  exclude: /node_modules/,
  includeTree: 'autotrack'
}
```

For some additional context as to why this is a problem, see this issue:
https://github.com/googleanalytics/autotrack/issues/137

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by Kovensky** [comment]
I think that's what the `issuer` filter is supposed to allow you to do

**Comment by philipwalton** [comment]
@Kovensky, I don't think the `issuer` option helps here.

In theory you would be able to exclude any resource that wasn't "issued" via one of your source files or one of the known modules that needs transpilation, but in practice this isn't possible.

It could work if the `exclude` option (when taking a function) were passed both the source file and the issuer, but it's not.

I've also tried *just* using the `issuer` option, but that doesn't work either since it doesn't include the entry file.

**Comment by sokra** [comment]
This is not possible in a nice way. Imagine a module is required by two modules. It not clearly defined if it's exclude or not. We could throw on those cases, but that's weird.

**Comment by philipwalton** [comment]
In the case of a transpiler like `babel-loader` I think it's safe to say: *if at least one module requires this file, it should be transpiled.*

This may not be as cut and dry for other types of loaders; I haven't spent as much time thinking about that, but perhaps it should be up to the loader to determine whether to throw or not?

@sokra, what about the suggestion that the `exclude` function be called with not only the file path but also the issuer path as well? I think that would help quite a bit for this case.

**Comment by rmacklin** [comment]
I agree that it shouldn't be considered a best practice to assume all dependencies are already transpiled to ES5 and thus to recommend the exclusion of all `node_modules` for `babel-loader`. If all my users are on ES2015-supported browsers, shipping them ES5 code is an unnecessary deoptimization (since transpiled code is larger, for one). And even if you need to transpile to ES5, the most efficient place for that transpilation to occur is when the application is built (where it can be ensured that babel helpers are not being duplicated, for example), so even developers who must ship ES5 would benefit from depending on libraries that are not pre-transpiled to ES5.

With all that said, the current `include`/`exclude` options for babel-loader have problems, as this issue describes. So I'm adding another voice here - I think this is something webpack could improve.
