### ISSUE TITLE
Profile times for `optimize-chunk-assets` is incorrectly attributed to `additional-assets` plugins.

### ISSUE THREAD

**Issue by gdborton** [webpack/webpack#4351]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Profile times for `optimize-chunk-assets` is incorrectly attributed to `additional-assets` plugins, making it more difficult/confusing to investigate build performance.

**If the current behavior is a bug, please provide the steps to reproduce.**
See the repo here for super boiled down reproduction - https://github.com/gdborton/profile-bug

**What is the expected behavior?**
Should see a higher reported `chunk asset optimization` time and a lower `additional asset processing` time.

**If this is a feature request, what is motivation or use case for changing the behavior?**
N/A

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
I don't think it's relevant, but Node - 4.6.2. Webpack 2.2.0, 2.2.1 and 1.14.0 all have the issue.

**Comment by sokra** [comment]
Looks like a bug. Send a PR.
