### ISSUE TITLE
Webpack2 with mutli-file entry tree-shaking not behave as expected

### ISSUE THREAD

**Issue by x-yao** [webpack/webpack#4353]
**Do you want to request a *feature* or report a *bug*?**
report a bug

**What is the current behavior?**
In Webpack2 when i use mutli-file entry like `foo.js` and `bar.js` and they both import an different function in `util.js`.

**foo.js**
    
       import {foo} from './util'
       const a = foo();

**bar.js**

       import {bar} from './util'
       const a = bar();

**util.js**

        export const foo = function () {
	        return 1
        }

        export const bar = function () {
	        return 2
        }

        export const foobar = function () {
	        return 3
        }

After run webpack and in `foo.js` the function like `bar` is not used in `foo.js` also marked with `harmony export (immutable)`.

**If the current behavior is a bug, please provide the steps to reproduce.**

[demo](https://github.com/x-yao/webpack-tree-shaking-demo)

**What is the expected behavior?**

I think it is should be like sigle entry and shaking unused module.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Node.js : 6.9.5
Webpack Version:2.2.1
Operating System: macOS Sierra

**Comment by sokra** [comment]
This is currently a limitation. You can workaround with multiple configuration.
