### ISSUE TITLE
The current state of support of Labeled Modules in Webpack 2

### ISSUE THREAD

**Issue by myshov** [webpack/webpack#4354]
_First of all, please sorry, that I don't follow required format of the issue, because my "issue" doesn't fit to this format anyway._

I want to ask a question about current state of support of Labeled Modules

The support of labeled modules have been dropped in the new version of webpack. Has it been done intentionally? I ask this question because there are some traces of it in the source code. For example here https://github.com/webpack/webpack/blob/master/bin/config-optimist.js#L42 and here https://github.com/webpack/webpack/tree/master/examples#labeled-modules. But there is no actual implementation of some sort of corresponding plugin.

Yes I've asked this question before in gitter, but there was no answer.

**Comment by sokra** [comment]
Support for Labeled Modules was removed. These snippets can be removed.
