### ISSUE TITLE
Evaluate jest-validate for validating configs

### ISSUE THREAD

**Issue by okonet** [webpack/webpack#4358]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

Right now webpack only issues validation errors.

https://github.com/facebook/jest/blob/master/packages/jest-validate would allow us to display more information about each validation error + deprecate stuff more nicely.

**If this is a feature request, what is motivation or use case for changing the behavior?**

Better UX and more clear error messages from validation.

**Comment by bebraw** [comment]
Better validation messages would be good. I guess ideally the approach would still be driven by JSON schema. The gotcha is that JSON Schema does not have the concept of deprecations or warnings.

Ajv can be extended to include these features. I wrote a little deprecation plugin for it myself just to see if it's feasible and it definitely is. This is likely the route I would take.

A good solution would work across webpack plugins and loaders too. [schema-utils](https://github.com/webpack-contrib/schema-utils) would be a good place to experiment.
