### ISSUE TITLE
Webpack dev server takes up a lot of memory (751.9MB) for GitLab CE

### ISSUE THREAD

**Issue by selfup** [webpack/webpack#4363]
@TheLarkInn @mikegreiling @jschatz1

**Do you want to request a *feature* or report a *bug*?**

Unexpected Behavior

**What is the current behavior?**

We are unsure if this is a combination of both webpack and webpack-dev-server. So posting here first 😄 

The `webpack-dev-server` process is a memory hog.  As of Feb 22nd it is coming in at **751.9MB** for the CE branch.  This is after having removed the `imports-loader` plugin in [Issue 9123](https://gitlab.com/gitlab-org/gitlab-ce/merge_requests/9123) and before this it was often **as high as 850MB**.

**If the current behavior is a bug, please provide the steps to reproduce.**

### GitLab Issue: https://gitlab.com/gitlab-org/gitlab-ce/issues/28557

![webpack-memory](https://gitlab.com/gitlab-org/gitlab-ce/uploads/5ee40614c57d4ecec110817d224d3843/webpack-memory.png)

This seems really excessive and we are trying to ascertain the root cause of it.  This issue will serve as a place to discuss and chronicle our attempts to alleviate this memory footprint.

I think there are a few things worth trying:

- [ ] Try exempting `node_modules` within `devServer.watchOptions` ([suggested by Kees Kluskens](https://twitter.com/keeskluskens/status/830173764092567552))
- [ ] Test out [this webpack PR](https://github.com/webpack/watchpack/pull/41) meant to improve memory use ([suggested by Kees Kluskens](https://twitter.com/keeskluskens/status/830414151025557504))
- [ ] Implement `CommonsChunkPlugin` to prevent multiple copies of Vue from being retained in memory
- [ ] Reduce the number of babel plugins we use by replacing `babel-preset-es2015` with `babel-preset-env` ([#28026](https://gitlab.com/gitlab-org/gitlab-ce/issues/28026))

**What is the expected behavior?**

That our dev server should not have such a large footprint 😂 

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

macOS - `"webpack": "^2.2.1"`

Can ask other people that use the GDK to tell us what their mem footprint is on Linux as well if need be.

**Comment by LukeeeeBennett** [comment]
I also see 250-300MB memory usage for `webpack-dev-server` for projects much smaller than GitLab CE.

**Comment by about-code** [comment]
Might be related to #2157

**Comment by selfup** [comment]
@about-code Thanks for that! I'll read up on it as well

**Comment by sokra** [comment]
Is the memory footprint growing over time or constant regardless how often it rebuilds.

**Comment by selfup** [comment]
Constant. We were able to reduce it by not using CJS and switching to `import` 

Went down from 750MB to 300MB. Switching branches back and forth yielded consistent results.

@mikegreiling can expand more if need be

**Comment by sarkiroka** [comment]
In our project the footprint is 400-500M. In nodejs world I think it is huge. We use only watch & rebuild and javascript files with imports

**Comment by terencechow** [comment]
@selfup can you expand on how you got from 700 mb footprint to 300mb for those of us having problems with webpack high memory usage? Did you just replace all `var a = require('a')` calls with `import a from 'a'`? Or were there other things you did to lower that?

**Comment by selfup** [comment]
The biggest wins for us was removing the `import-loader`, using `import` vs. `require`, as well as utilizing the `CommonsChunkPlugin` 😄

**Comment by selfup** [comment]
Wrong button! Whoops 😂

**Comment by mikegreiling** [comment]
@terencechow at @gitlab we saved a lot of memory by doing the following:

- removing all uses of `require.context()`
- switching to ES module syntax wherever possible (apparently statically analyzed dependencies must require fewer resources)
- utilizing CommonsChunkPlugin to remove redundant copies of vendor modules from our bundles (before this we compiled Vue in 5 or 6 separate bundles and I don't think babel and/or webpack was smart enough to hold this in memory in only one place internally)
- removing any plugins that aren't specifically needed in development mode (CompressionPlugin, HashedModuleIdsPlugin, BundleAnalyzerPlugin, etc)
- making sure to `exclude: /node_modules/` in all of our loaders
- switching away from `inline-source-map` to `cheap-module-eval-source-map`

All that said, it still takes up a good chunk of memory, and the more of webpack/babel's cool features and plugins you want to use, the more memory it will require.  Thankfully when the process has been running a while on macOS, it tends to use compressed memory to reduce this burden a bit.

**Comment by selfup** [comment]
Thank you for the more thought out response @mikegreiling 🎉

**Comment by gillchristian** [comment]
I'm having the same issues. For a big project (but I don't think as big as Gitlab) it's taking around **950mb** to **1gb**.

**Comment by Obooman** [comment]
Same issue,react single-page-application with [antd](https://github.com/ant-design/ant-design),900+M memory has been occupied.

`macOS Sierra 10.12.5 (16F73)` with `8G memory`

```bash
▲ ~ node -v
v7.8.0
▲ ~ npm -v
5.0.3
```

**Comment by MagicDuck** [comment]
Same issue, but on a different scale. For our 7000module project we have to give it 4Gb. It actually uses a bit more than that cause we spawn some subprocesses to speed up babel transpilation. If we build our uni tests together, aboit 16000 modules, we sometimes run out of memory with just 4Gb and have to increase the limit.  Some people with lower spec laptops have trouble doing anything else when webpack is building, lol.

**Comment by abbymrs** [comment]
same here, memory usage from 30% to 98% after running webpack-dev-server

**Comment by about-code** [comment]
@abbymrs Do you use the same config or plugins with webpack-dev-server? Do [recent findings and fixes](https://github.com/webpack/webpack/issues/5992) related to the use of the *ModuleConcatenationPlugin* apply to your situation?

**Comment by abbymrs** [comment]
@about-code I used angular-cli to generate projects, webpack config is integrated with this generation tool, so i am not sure whether ModuleConcatenationPlugin is used or not.

**Comment by about-code** [comment]
I had a quick look at the CLI repo. They are using the plugin in in their production config which you can find [here](https://github.com/angular/angular-cli/blob/4b0c7a35359effc1d93cd3bb5ddc5c441b3cf154/packages/%40angular/cli/models/webpack-configs/production.ts#L138). In the issue of Felipesilva which I linked it sounds like the problem gets more likely the more lazy loaded app routes a project has. Felipe has given an example of 12 chunks in its report.

To rule out ModuleConcatenationPlugin you could *eject* the webpack config used by CLI, put the Plugin in comments and see whether that improves memory consumption. Make sure to be able to revert ejection again.

**Comment by abbymrs** [comment]
@about-code i did not use production mode, so i don't think `ModuleConcatenationPlugin `is used;  but i did use `-aot` option for `ng serve`, and the memory usage increases quickly! However, if i removed -aot option, it seems the memory usage can be hold below 80%, and the computer works without stuck.
Thanks anyway!

**Comment by brodock** [comment]
It exists with GitLab, it actually got a lot worst (1.35GB)

**Comment by brodock** [comment]
<img width="898" alt="webpack" src="https://user-images.githubusercontent.com/20575/43030385-a1341046-8c8f-11e8-9f50-6d12d0091724.png">

this is what two webpack-dev-server for gitlab development look like (I'm running two gitlab instances for some specific development)

**Comment by sergey-dryabzhinsky** [comment]
Well, I got assets compiled with change in `config/webpack.config.js`:
from
```
const devtool = IS_PRODUCTION ? 'source-map' : 'cheap-module-eval-source-map';
```
to
```
const devtool = IS_PRODUCTION ? 'cheap-source-map' : 'cheap-module-eval-source-map';
```

And run command:
```
env NODE_OPTIONS=--max_old_space_size=8192 bundle exec rake gitlab:assets:clean gitlab:assets:compile RAILS_ENV=production NODE_ENV=production
```

Anyway, It's something with webpack/yarn modules.
Gitlab 10.8 assets compiled w/o errors.

**Comment by evilebottnawi** [comment]
@brodock can you create minimum reproducible test repo?

**Comment by psimyn** [comment]
@evilebottnawi I've copied the entire gitlab frontend and webpack config to https://gitlab.com/psimyn/gitlab-webpack-memory

Heap snapshots are around ~1.3GB.  The node-inspect command would OOM error unless I increased `--max_old_space_size`

```sh
git clone https://gitlab.com/psimyn/gitlab-webpack-memory.git
cd gitlab-webpack-memory

yarn
yarn dev-server # this is what we usually run in main repo
yarn node-inspect # runs node with --inspect flag
```

**Comment by Eein** [comment]
removes via https://gabri.me/blog/analyzing-optimizing-your-webpack-bundle
ideally keeps slugs, but removes the unicode dump for arabic and other stuff we dont care about.

**Comment by evilebottnawi** [comment]
@webpack-bot move to weback/webpack-dev-server

**Comment by sarkiroka** [comment]
Is it resolved?

**Comment by evilebottnawi** [comment]
Not it is moved to dev server repo and will be solved in next release

**Comment by mikegreiling** [comment]
@evilebottnawi despite the title of this issue, I don't believe this is actually an issue specific to webpack-dev-server.

webpack _in general_ eats up a ton of memory for GitLab and as illustrated above it will run out of heap memory unless `max_old_space_size` is employed regardless of whether we're using dev-server or not.

could we re-open this issue?

**Comment by evilebottnawi** [comment]
@mikegreiling i will investigate problem in webpack-dev-server repo and if find something bad open new issue in webpack because original problem about webpack-dev-server

**Comment by selfup** [comment]
@mikegreiling You want me to rename this or wait for @evilebottnawi to report back?

**Comment by evilebottnawi** [comment]
I will take care about this

**Comment by evilebottnawi** [comment]
@selfup anyway can you provide link on repo and step to reproduce?

**Comment by h0jeZvgoxFepBQ2C** [comment]
Still a thing :/

**Comment by evilebottnawi** [comment]
@h0jeZvgoxFepBQ2C Please create reproducible test repo
