### ISSUE TITLE
Feature: Is 'import()' for dynamic module loading really the best name?!?

### ISSUE THREAD

**Issue by aanno** [webpack/webpack#4372]
**Do you want to request a *feature* or report a *bug*?**
Feature request.

**What is the current behavior?**
Dynamic module loading is using 'import()'. Alternatives are 'require.ensure()' (non-portable) and 'System.import()' (deprecated). See https://webpack.js.org/guides/code-splitting-import/ for more details.

**If the current behavior is a bug, please provide the steps to reproduce.**
The problem of using 'import()' is that 'import' is a KEYWORD in the TypeScript compiler. Hence TypeScript will not compile 'import()'. In no configuration. And even not if you compile JS with the TypeScript compiler.

**What is the expected behavior?**
You probably should not use an already used keyword for dynamic module loading. 'System.import()' was ways better in this respect.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Could you rename 'import()'? Or at least provide an alias for it?

**Comment by aight8** [comment]
import exists as statement (import ... from ...) and as function (import(..)) for dynamic loading in the javascript ES specs, so it's standard.

There must be a solution in typescript to keep import as it is so webpack can handle it same as babel do with "module: false".

I suggest more to remove the old require.ensure, System.import etc. very soon in webpack 3. Because those confuses so much users.

**Comment by timse** [comment]
as @aight8 mentioned this is a stage 3 (?) proposal, so there is nothing the javascript side of things can do about it.

closing for now. Feel free to reopen if you think it remains a valid issue.

**Comment by aanno** [comment]
Cross reference: As `import()` is a proposal for the next ES standard, I opened a issue at typescript to not treat `import` as key word: https://github.com/Microsoft/TypeScript/issues/14381

**Comment by Kovensky** [comment]
Yes, it's a problem with TypeScript. For now, your best approach is to use `System.import`, which you can easily find/replace with plain `import` once TypeScript gets support for it; they work exactly the same way, only the latter is an official TC39 thing.

```ts
interface System {
  import<T> (request: string): Promise<T>
}
declare var System: System

import * as fooNs from 'foo'
const foo = System.import<typeof fooNs>('foo')
// The `typeof fooNs` thing is a hack to get the Promise to be correctly typed, which leads to
foo.then(foo => {
  // foo has correct typechecking, autocomplete support, etc
})
// because you only referred to fooNs as a type,
// TypeScript will delete the import..from before webpack sees it
```
