### ISSUE TITLE
define named function throws in runtime

### ISSUE THREAD

**Issue by edoardocavazza** [webpack/webpack#4377]
**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?** `define` named function throws in runtime

**If the current behavior is a bug, please provide the steps to reproduce.**

**app/define.js**
```js
export function define() {
    console.log('define');
}
```

**app/index.js**
```js
import { define } from './define';

define();
```

```sh
./node_modules/.bin/webpack app/index.js dist/bundle.js
# or include in html and try in browser
node dist/bundle.js
```

**What is the expected behavior?** Invoking the `define` function does not throw and execs function body.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

* Chrome: 58.0.3018.0
* NodeJS: v7.2.1
* Webpack: 2.2.1

**Comment by timse** [comment]
webpack assumes that by using `define` you mean to use the AMD `define` to specify a module.
I guess this one is tricky (:

**Comment by edoardocavazza** [comment]
thanks @timse! is there any way to exclude this behaviour? I do not treat AMD modules in my projects.

**Comment by timse** [comment]
hmm this may sound a bit weird now, but i just wanted to try a bit around it, and i cant reproduce it anymore.

```
/******/ ([
/* 0 */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
/* harmony export (immutable) */ __webpack_exports__["a"] = define;

function define() {
    console.log('define');
}


/***/ }),
/* 1 */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
Object.defineProperty(__webpack_exports__, "__esModule", { value: true });
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_0__x__ = __webpack_require__(0);


__webpack_require__.i(__WEBPACK_IMPORTED_MODULE_0__x__["a" /* define */])();


/***/ })
/******/ ]);
```

**Comment by edoardocavazza** [comment]
Hi @timse,

I have tried to clear npm cache and reinstall all dependencies and I get the error.

Here is my bundle:
```js
/******/ ([
/* 0 */
/***/ (function(module, exports, __webpack_require__) {

"use strict";


Object.defineProperty(exports, "__esModule", {
    value: true
});
exports.define = __webpack_require__(1);
function define() {
    console.log('we');
}

/***/ }),
/* 1 */
/***/ (function(module, exports) {

module.exports = function() {
	throw new Error("define cannot be used indirect");
};


/***/ }),
/* 2 */
/***/ (function(module, exports, __webpack_require__) {

"use strict";


var _define = __webpack_require__(0);

(0, _define.define)();

/***/ })
/******/ ]);
```
here my `webpack.config.js`:
```js
const path = require('path');
const webpack = require('webpack');

module.exports = {
    context: path.join(__dirname, 'app'),
    module: {
        rules: [
            {
                test: /\.js$/,
                loader: 'babel-loader',
                query: {
                    presets: ['es2015']
                },
            },
        ],
    },
    resolve: {
        modules: [
            path.join(__dirname, 'node_modules'),
        ],
    },
};

```

**Comment by timse** [comment]
you need to make sure babel is not taking care of your imports

**Comment by edoardocavazza** [comment]
You are right!

Editing the preset configuration it worked.
```js
...
presets: [
    ['es2015', { modules: false }],
],
...
```

Really thanks for the support

**Comment by timse** [comment]
no worries :) i close then 👍
