### ISSUE TITLE
--watch doesn't work with multiple compiler configs

### ISSUE THREAD

**Issue by flodiebold** [webpack/webpack#438]
If you have multiple compiler configs, like in the multi-compiler example, the --watch option does nothing. That's because the watch property gets set for each config object, but the webpack function just checks options.watch (even when options is an array).

This can be reproduced by running webpack --watch in the multi-compiler example.

**Comment by govorov** [comment]
Hi!
The problem is still there on v1.14.0. If I use configs array, `watch` options is ignored. I have to hack `configArray.watch = true`, this seems to be quite ugly solution.
