### ISSUE TITLE
SourceMapDevToolPlugin not working with CommonsChunkPlugin and UglifyjsWebpackPlugin

### ISSUE THREAD

**Issue by MilosRasic** [webpack/webpack#4388]
**Do you want to request a *feature* or report a *bug*?**
Reporting a *bug*.

**What is the current behavior?**
SourceMapDevToolPlugin running after CommonsChunkPlugin and UglifyjsWebpackPlugin seems to have no affect.

With devtools: 'source-map' and sourceMap: true in UglifyJsPlugin options webpack will simply output the output of UglifyJsPlugin.

With devtools: false and sourceMap: false in UglifyJsPlugin, webpack outputs sourcemaps for css and a single js bundle that contains only one module.

**If the current behavior is a bug, please provide the steps to reproduce.**

https://gist.github.com/MilosRasic/9d6addc1cccecc8d7006826ead5edd88
Used to work before upgrade to webpack 2. Now outputs only css sourcemaps.
Putting a console.log(sourceMap) at line 64 of lib/SourceMapDevToolPlugin.js shows that sourceMap for a app js chunk is falsey.

https://gist.github.com/MilosRasic/3f95c03fdbb51fd2f6eb26ec25e26003
Generates map files for all output files. SourceMapDevToolPlugin seems to make no difference. Completely removing it doesn't affect output.
Aforementioned console.log at line 64 of lib/SourceMapDevToolPlugin.js is never ran suggesting that the plugin is doing nothing with this configuration.

**What is the expected behavior?**

Sourcemaps generated only for css and the app js chunk.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

node v6.9.1
webpack v2.2.1

**Comment by jeroenbourgois** [comment]
I think the culprit is the uglifyjs plugin, I do not use the commonchunks but have the same issue. Removing Uglifyjs works, then a sourcemap is generated again. Is there an option to run the sourcemap command before the uglifyjs?

**Comment by jeroenbourgois** [comment]
Oops, nevermind! I had 'sourceMaps' set to false in the config :)

**Comment by Vanuan** [comment]
`source-map` works for me, while `cheap-module-source-map` doesn't.
See https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/22 to list all the found issues.

**Comment by rdsedmundo** [comment]
Same here. I use both CommonsChunk and UglifyJS, and can't exclude a file from being source-mapped.

**Comment by rdsedmundo** [comment]
I don't have much knowledge about this source code, but I've noticed that [this ](https://github.com/webpack/webpack/blob/master/lib/WebpackOptionsApply.js#L200) block is completely ignoring the options passed on the plugins part. If I force an `exclude` along with all the other 'hard-coded' options, it works.

@sokra

**Comment by samkelleher** [comment]
+1 this issue.

'devtools' is 'source-map'

```
        new webpack.optimize.CommonsChunkPlugin({
            name: 'vendor',
            minChunks: module => /node_modules/.test(module.resource)
        }),
        new webpack.optimize.UglifyJsPlugin({
            compress: false,
            mangle: false,
            sourceMap: true,
            output: {
                comments: false
            }
        }),
```

The resulting output with this configuration:

- Exceptions stack traces don't show correct lines (continue to show the minified lines).
- Viewing the source file, chrome reports 'source map file found' but doesn't actually use it, continues to show minified code - it seems to know the map doesn't match the minified file correctly.
- when capturing exceptions or using breakpoints, the sourcemap is found but the alignment is off by about 10 lines. ie many lines are 'disabled' and its in this strange state where executing is on one line while the yellow active line where you can highlight variables etc is in another line, often even in a different function.

How to fix:

Removing the commons chunk plugin fixes the sourcemap, but I loose the chunk and have one massive file.

Removing the uglify plugin also fixes the sourcemap, but now the code isn't minified anymore.

By 'fix the sourcemap' I mean an example piece of code i added 'nothingtoseehere.fail()' throws an undefined exception, when it's fixed, I can see the correct names/lines in the stack trace and when I click it into the source file with the correct line highlighted.

So these two plugins are not playing nice with each other.

Using current latest versions as at time of writing.

**Comment by jonesmac** [comment]
I have noticed similar behavior. With commons chunk, source map dev tool plugin, and uglify no maps are generated. Any update on this (or an alternate way to exclude vendor files from having sourcemaps generated) would be appreciated.

**Comment by merraysy** [comment]
Same here, anyone could make those plugins play nicely together ?

**Comment by MilosRasic** [comment]
I'm kinda butthurt webpack 3.0 is coming out soon with things like this still unresolved :(

Anyone try it with the 3.0 RC?

**Comment by sokra** [comment]
* You **must** not provide devtool + SourceMapDevToolPlugin.
* SourceMapDevToolPlugin `include`/`test`/`exclude` filters by output filename not by module.
* UglifyJsPlugin **must** be before SourceMapDevToolPlugin
* UglifyJsPlugin **must** have `sourceMap: true` set to generate source maps

**Comment by pedi** [comment]
it works for me now. After remove the line of `devtool`

I think this might worth highlighting in the docs

**Comment by fwchen** [comment]
remove the line of devtool work for me, too

**Comment by francesco-carrella** [comment]
without devtool seems be the solution.. :/

**Comment by hk144** [comment]
Cool
