### ISSUE TITLE
Cannot use --optimize-minimize without "es2015" preset

### ISSUE THREAD

**Issue by thezanke** [webpack/webpack#4389]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

I am ONLY targeting chrome. I can build my bundle fine without `--optimize-minimize` but when I add that option I require `es2015` or else my build will crash with the following:

> ERROR in scripts/popup.js from UglifyJs
SyntaxError: Unexpected token: name (App) [./src/components/App.js:6,21][scripts/popup.js:16231,6]

Here's where it's choking in `./src/components/App.js`:
```js
4. import AppLayout from './AppLayout';
5. 
6. export default class App extends Component {
                        ^
```

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Use [my webpack config](https://gist.github.com/thezanke/b72bf61bbfdb9c6543eb2b21a2bb8021) or clone [my repo](https://github.com/thezanke/ChromeGif)
2. Run `$ webpack --optimize-minimize` in project

**What is the expected behavior?**

Successfully generate a minimized build without "es2015" preset.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

My package.json:
```json
{
  "name": "ChromeGif",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "dev": "webpack --watch",
    "build": "webpack --optimize-minimize"
  },
  "devDependencies": {
    "babel-core": "^6.23.1",
    "babel-loader": "^6.3.2",
    "babel-plugin-transform-class-properties": "^6.23.0",
    "babel-preset-react": "^6.23.0",
    "clean-webpack-plugin": "^0.1.15",
    "copy-webpack-plugin": "^4.0.1",
    "css-loader": "^0.26.2",
    "html-loader": "^0.4.5",
    "html-webpack-plugin": "^2.28.0",
    "interpolate-html-plugin": "^1.0.1",
    "style-loader": "^0.13.2",
    "url-loader": "^0.5.8",
    "webpack": "^2.2.1"
  },
  "dependencies": {
    "react": "^15.4.2",
    "react-dom": "^15.4.2",
    "rxjs": "^5.2.0"
  }
}
```

**Comment by ypconstante** [comment]
UglifyJS currently doesn't support ECMAScript 6 (https://github.com/mishoo/UglifyJS2/issues/448).

You could use babili (https://github.com/babel/babili), it's a babel preset that does code minification.

**Comment by bebraw** [comment]
Yup. Either preprocess first or try Babili.

**Comment by thezanke** [comment]
Babili seems to be working okay, thanks guys!
