### ISSUE TITLE
AMD external dependencies don't load in chunks

### ISSUE THREAD

**Issue by redfin-sasha-aickin** [webpack/webpack#439]
I'm finding that if module A depends on an external AMD module and ends up in a non-entry chunk, then the AMD module doesn't load, and there is an undefined variable in the code.

To repro:

1) Download the repro code at https://www.dropbox.com/s/1q6qq3vjzxtbz9v/webpackamdbug.tar.gz?dl=0
2) Untar the file.
3) cd into the directory
4) npm install webpack
5) webpack --config webpack.config.js
6) open install.html (if on mac, otherwise just open in a browser)

Expected: every module in the code loads properly and changes its div from "no" to "yes".

Actual: the two modules that end up in chunk 1.1 and have dojo dependencies fail to run. If you look at the console, you can see it's because "Uncaught ReferenceError: **WEBPACK_EXTERNAL_MODULE_8** is not defined". And if you compare the code of build/main.js (which also has AMD dependencies) and build/1.1.js, you'll see that build/main.js wraps the whole file in a define() call, whereas build/1.1.js does not.

**Comment by khaled** [comment]
Any hope for a fix for this?

**Comment by sokra** [comment]
It is fixed in webpack 2

**Comment by westfalenxqq** [comment]
I metthe same problem.So I should wait for webpack2 release

**Comment by dgwaldo** [comment]
Don't really like commenting on closed threads but this is the closest I've come to anyone else summing up the behavior I'm after.  As of Webpack v3.6.0 AMD modules are ending up in my entry bundle, however I'm a little confused.  @sokra Are you saying that with  AMD external dependencies and webpack, they should end up in an entry chunk?  @redfin-sasha-aickin and myself seem to desire the behavior of these ending up in our other dynamically loaded bundles.  

Is it possible to have them included in the dynamically loaded bundles?

If so, how?
