### ISSUE TITLE
webpack.EnvironmentPlugin - WARNING in [object Object] environment variable is undefined.

### ISSUE THREAD

**Issue by mrdulin** [webpack/webpack#4390]
when I pass a `object` parameter, it give me a warining. 
```js
    new webpack.EnvironmentPlugin({
        "NODE_ENV": 'development'
    }),
```

`WARNING in [object Object] environment variable is undefined.`

I take a look the source code, it seems not support `object` parameter.

```js
function EnvironmentPlugin(keys) {
	this.keys = Array.isArray(keys) ? keys : Array.prototype.slice.call(arguments);
}
```

By the way, I use `webpack: ^1.13.2`.

**Comment by bebraw** [comment]
The object format is supported only in webpack 2.

The plugin should work with webpack 1, though, and you can copy it from https://github.com/webpack/webpack/blob/master/lib/EnvironmentPlugin.js . In this case you'll have to maintain a little private version at your project until you upgrade to webpack 2.

**Comment by mrdulin** [comment]
@bebraw Thanks. I see.
