### ISSUE TITLE
CommonChunkPlugin: Feature - Select statically imported modules from chunks that were created from a dynamic import (require.ensure / System.import / import(".."))

### ISSUE THREAD

**Issue by kazazor** [webpack/webpack#4392]
**Do you want to request a *feature* or report a *bug*?**

Feature for `CommonChunkPlugin`.

Support selecting modules from **non-entry** chunks. Meaning, select statically imported modules from chunks that were created from a **dynamic** import (`require.ensure` / `System.import` / `import("..")`)

**What is the current behavior?**

Currently `CommonChunkPlugin` only receives modules imported from **entry** chunks.

**What is the expected behavior?**

`CommonChunkPlugin` should receive also modules from **non-entry** chunks.<br>
Another option will be that the default behavior will be that the plugin won't be getting these modules and only with passing something like `selectAllChunks: true` will enable this behavior.

**If this is a feature request, what is motivation or use case for changing the behavior?**

Most of the examples out there talks about CodeSplitting but not talking about CodeSplitting with lazy loading. For example, load your main page as an entry chunk, and split the rest of your website routes to different chunks and only load those on demand.

You see the important need for this feature when you're trying to make a `vendors` chunk that will include the vendors from ALL the chunks including the ones for the different routes that are being created from a dynamic import as a split point.

In our opinion the best solution to create the `vendors` chunk will be using the `minChunks` function since the other two (specifying hard coded which packages to take / import `package.json`.dependencies) has a lot of issues with and this is the most dynamic way to do it:

```js
    new webpack.optimize.CommonsChunkPlugin({
      name: 'vendors',
      minChunks: ({ resource }) => /node_modules/.test(resource)
    })
```

The problem is that since `CommonsChunkPlugin` only gets modules form the **entry** chunks, so all the vendors from our different split points are not being added to this chunk.

The motivation around this feature request is that others won't need to do the workaround I'll show here.

**Proposed temporary workaround and why it's not that good. Writing it here anyway so who ever needs it will see it and would be able to use it** 

What the lack of this feature forces us to do it for every dynamic import we're doing (using `import("path")`) we're also going and creating an entry chunk for it. Just so the above code will work.

Then, all of these "duplicate" chunks we're excluding from being added to the HTML using the `excludeChunks` of `HtmlWebpackPlugin`

So it basically looks like this:

```js
...

// Why do we need to exclude these entries?
// The entries here are being dynamically loaded per route in the application so we would like to set
// them to be excluded form HtmlWebpackPlugin auto inject of entry chunks.
//
// If they are being dynamically loaded in the system, so why do you need them here at all?
// We're creating a `vendors` chunk automatically from what being imported from `node_modules`, in order for webpack
// to know about what code exists in these route chunks we need to set them as entries here.
// That way we're getting everything we ever wanted! The `vendors` is being created out of ALL the vendors in the system,
// and we're still able to dynamically load these chunks per route without having them injected to index.html at the beginning.
const excludeEntries = {
  main: [path.join(chunksPath, 'main_chunk')],
  A_template_collection: [path.join(pagesPath, 'TemplateCollectionPage')],
  A_template_wizard: [path.join(pagesPath, 'TemplateWizardPage')],
  A_edit_template: [path.join(pagesPath, 'TemplateEditPage')],
  A_create_instance: [path.join(pagesPath, 'CreateInstancePage')],
  B_issues_collection: [path.join(pagesPath, 'IssuesCollectionPage')]
};

const entry = Object.assign({}, excludeEntries, {
  application: [path.join(chunksPath, 'application_chunk')]
});

const config = {
    entry,
    ...
    plugins: [
        new webpack.optimize.CommonsChunkPlugin({
          name: 'vendors',
          minChunks: ({ resource }) => /node_modules/.test(resource)
        }),
        new HtmlWebpackPlugin({
          title: indexHtmlTitle,
          resourceHintsMetaTags,
          inject: true,
          template: indexHtmlPath,
          excludeChunks: Object.keys(excludeEntries)
        }),
    ]
    ...
}

```

The dynamic imports are being used on the same paths as the entry chunks that are being excluded from the html.

This causes some difficulties for us:

1. If you dynamically import something and forget to put it here as well it will not go into the vendors chunks and you'll lose cache
2. This creates for us chunks that we're not actually using. So for the same code I'll have the named entry chunk and I'll also have a chunk from the dynamic import. I'm not using the named entry-chunks but it's just noise to me.
That is even bigger when also using the ExtractTextPlugin.

I looked also here: https://github.com/oieduardorabelo/webpack-commonschunkplugin-dynamic-splitting
But that seems to not be related since in our case the only real entry point (`application: [path.join(chunksPath, 'application_chunk')]`) is basically just loading polyfills + loading the `main` chunk path dynamically. Since all the `application` chunk is doing is mainly dynamically `import()` stuff it has no static imports of files from `node_modules`. So CommonChunkPlugin doesn't catch that..

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

* OS: macOS 10.12.3
* Node.js version: 6.9.10
* Webpack version: 2.2.1
* Browser not relavant

**Comment by sokra** [comment]
There is already an (incomplete) PR adding this feature.

**Comment by kazazor** [comment]
@sokra - do you refer to this PR: https://github.com/webpack/webpack/pull/4255 ?

**Comment by mbrevda** [comment]
For anyone using the workaround of manually specifying all dynamic splits as entries: if you want to then remove those entries and not have them emitted or included in stats, see here: http://stackoverflow.com/a/39401288/747749

**Comment by jagi** [comment]
I've just encountered the same problem when developing an app with dynamic imports. It's the "must have" feature. I'm surprised that it was not implemented yet. Is there something we can do to help with developing this feature? Is someone actively working on that?

**Comment by ljcrapo** [comment]
I've just submitted another PR to fix the issues with https://github.com/webpack/webpack/pull/4255.
you can find it here: https://github.com/webpack/webpack/pull/5764

**Comment by wbern** [comment]
Could someone share a code snippet for making this work after merge of PR #4255?

@ljcrapo

**Comment by jagi** [comment]
@wbern example code is in docs in the PR:

```js
module.exports = {
	entry: {
		main: ["./example.js"]
	},
	plugins: [
		new webpack.optimize.CommonsChunkPlugin({
			name: "main",
			minChunks: 2,
			children: true,
			deepChildren: true,
		})
	]
};
```

**Comment by wbern** [comment]
@jagi I tried that (with minChunks checking if the package is from node modules so not 2 like in your case), and it didn't manage to move anything to that vendor chunk.

I am using dynamic import() with latest webpack version.

**Comment by ljcrapo** [comment]
@wbern, what does your configuration look like? I had to omit `name` from my configuration to get it to do what I wanted.

**Comment by joaovieira** [comment]
Finally found this thread! Works great on latest webpack (3.8.1) for my simple case. Thanks!

**Comment by wbern** [comment]
@ljcrapo @sokra you are right, I had to omit `name`, then it successfully took my dynamic imported controllers and put the vendors in `vendor.bundle.js`.

What worries me here is that if I have not defined either `name` or `filename`, how can I be so sure that the generated bundle will be `vendor.bundle.js`?

And why shouldn't `name` be allowed anyway? You do get an error if you define `filename` which is

```
ERROR in chunk app/file [initial]
vendor.bundle.js
Conflict: Multiple assets emit to the same filename vendor.bundle.js
```,

but there's no error for `name`, just that it plain doesn't work.

**Comment by wbern** [comment]
@sokra @jagi @ljcrapo Can anyone reflect on the above?? I don't feel safe enough to add this until I know what's happening.

**Comment by lili21** [comment]
@jagi does'n work for me. 

There is no `vendor` bundle, and all `common` stuff bundled in `main` entry. 

[demo repo](https://github.com/lili21/webpack-demo)

![webpack-demo](https://user-images.githubusercontent.com/4456380/32048994-f3e09622-ba10-11e7-85e0-9b8d248d0d11.png)

**Comment by ljcrapo** [comment]
@lili21 
> ...all common stuff bundled in main entry.

The main entry **_is_** the common chunk in this case. I believe if you set `async` to true you'll get a separate chunk with common stuff that gets loaded asynchronously.

**Comment by ljcrapo** [comment]
@wbern I agree that something doesn't add up. It is probably the result of attempting to satisfy multiple inconsistent use cases. I would suggest submitting a new issue explaining exactly what behavior you would expect.

**Comment by wbern** [comment]
@ljcrapo to be honest I'm not sure what to expect, other than for the PR to work as described here. I'm just not sure what else there is to add, except that it doesn't work when you use the specified configuration which inspired the PR.

**Comment by lili21** [comment]
@ljcrapo 

> The main entry *is* the common chunk in this case.

That's not what I expect. only the `node_modules` stuff should be bundled in common chunk.

```
new webpack.optimize.CommonsChunkPlugin({
  // name: 'common',
  minChunks(module) {
    return (
      module.resource &&
      /\.js$/.test(module.resource) &&
      module.resource.indexOf(path.resolve(__dirname, './node_modules')) === 0
    )
  },
  children: true,
  deepChildren: true
}),
`` `

**Comment by lili21** [comment]
@ljcrapo Thanks. one more quetion, is there a way I can set the name of the common chunk ?

**Comment by lili21** [comment]
figure out a better way to do this.

```
new webpack.optimize.CommonsChunkPlugin({
  name: 'app',
  async: 'async-vendor',
  children: true,
  minChunks(module) {
    return (
      module.resource &&
      /node_modules/.test(module.resource)
    );
  },
})
```

**Comment by marcneander** [comment]
I noticed that specifying chunks manually works perfectly.

```
new webpack.optimize.CommonsChunkPlugin({
    name: 'vendor',
    chunks: ['app', 'home', 'about', 'contact'],
    minChunks: module => /node_modules/.test(module.resource)
})
```

How I load my modules dynamically in my routes 

```
const routes = {
    path: '',

    children: [
        {
            path: '',
            load: () => import(/* webpackChunkName: 'home' */ './home')
        },
        {
            path: '/stock',
            load: () => import(/* webpackChunkName: 'about' */ './about')
        },
        {
            path: '/reset',
            load: () => import(/* webpackChunkName: 'contact' */ './contact')
        }
    ]
}
```

**Comment by alexander-akait** [comment]
`CommonsChunkPlugin` was removed in v4 and v5, in favor the `splitChunks` option, I think we can close it, and we have https://github.com/webpack/webpack/pull/5764
