### ISSUE TITLE
Minified files are corrupted, Uncaught ReferenceError: Invalid left-hand side expression in postfix operation

### ISSUE THREAD

**Issue by hinok** [webpack/webpack#4395]
**Edit 3x**
Hard to say for me but it cannot be reproduced by using `uglify-js` cli, only with `uglifyjs-webpack-plugin`.

Please follow the issue https://github.com/mishoo/UglifyJS2/issues/1516

Reproduceable repo: https://github.com/hinok/webpack-uglify-js-bug

**Edit 2x**

Sorry for that. It's not related to webpack, found the same problem on uglify-js github
https://github.com/mishoo/UglifyJS2/issues/1516. I close the issue.

**Edit**

This problem doesn't exist if I downgrade `uglify-js` to `2.7.5` so probably it's just a problem with the latest version of `uglify-js` - `2.8.0`.

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Minified files by `webpack`  and `uglify-webpack-plugin` are corrupted. After build process, this error appears in the console (dev tools).

```
Uncaught ReferenceError: Invalid left-hand side expression in postfix operation                 localhost/:3
```

The problem is with this small fragment `for(var u,i,f,p=[];0<t.length;0++)` and `0++` which appears two times in minified file.

**If the current behavior is a bug, please provide the steps to reproduce.**
Minify code in the gist https://gist.github.com/hinok/7bacb79e5a3c98d7263a853424377fec

webpack configuration

```
{
  plugins: [
      new UglifyJSPlugin(),
  ]
}
```

**Reproduceable repo**

https://github.com/hinok/webpack-uglify-js-bug

**What is the expected behavior?**
Files should be minified without errors.

**If this is a feature request, what is motivation or use case for changing the behavior?**
n/a

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

```
Node: 6.9.1
OS: macOS Sierra 10.12.3

"uglify-js": "^2.8.0",
"uglifyjs-webpack-plugin": "^0.2.1",
"webpack": "^2.2.1",
```

**Comment by sokra** [comment]
uglify-js@2.8.1 fixes it
