### ISSUE TITLE
Group/summarise module stats by packages

### ISSUE THREAD

**Issue by aight8** [webpack/webpack#4397]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
On module level you can output module stats and limit the amount.
Current stats options are: **modules**, **modulesSort**, (**max modules** per cli, for config file there is no doc - default is: max. 15 modules)

**What is the expected behavior?**
Something like:
```
       Asset     Size  Chunks             Chunk Names
    index.js  384 kB       0  [emitted]  index
       3 modules from src 16 kb
       233 modules from package lodash 134 kb
       15 modules from package react 234 kb
          using 3 modules from package xxx 15 kb
          using 15 modules from package xxx 15 kb
```

**If this is a feature request, what is motivation or use case for changing the behavior?**
The stats output overall can be very fine tuned. However on module level it is either very verbose or it is very silent. The module stats could be presented more helpful by group modules by package - to see what was effective bundled without using any clunky plugins.

Additionally it could also show bundle summaries for packages (tree like structure if one package uses other ones)

**Benefits:**
- Fast check which modules are imported from different packages
- Fast check for tree-shaking affects by package
- Fast check for minification affects by package

---

**Important clarifications:**
- Because tree-shaking is currently happens by the JS minifier by mangeling, there is no way to see the modules (it contents) which are effectively are bundled. Is that correct?
- Identification of packages must somehow recognised because node_modules are just another "modules" entry for the enhanced-resolver

**Comment by bebraw** [comment]
You could try to experiment with this based on webpack stats. There might be enough information to pull it off.
