### ISSUE TITLE
Uglify 2.8.x API update required for compress options `reduce_vars` and `passes`

### ISSUE THREAD

**Issue by kzc** [webpack/webpack#4398]
**Do you want to request a *feature* or report a *bug*?**

feature request or bug depending on how you look at it.

**What is the current behavior?**

`webpack` uses an older low level Uglify API which does not support `compress` options `reduce_vars` and `passes`.

**If the current behavior is a bug, please provide the steps to reproduce.**

See: https://github.com/mishoo/UglifyJS2/issues/1516#issuecomment-283102405

**What is the expected behavior?**

To support the uglify `compress` options `reduce_vars` and `passes`.

Illustrative example: https://github.com/mishoo/UglifyJS2/blob/16cd5d57a5cf7f5750104df0e5af246708fd493f/test/compress/reduce_vars.js#L352-L384

**If this is a feature request, what is motivation or use case for changing the behavior?**

To support the uglify `compress` options `reduce_vars` and `passes` to produce smaller minified output.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

All browsers and all platforms.

Recommended one line fix:
```patch
--- a/lib/optimize/UglifyJsPlugin.js
+++ b/lib/optimize/UglifyJsPlugin.js
@@ -87,7 +87,7 @@ class UglifyJsPlugin {
                                                        const compress = uglify.Compressor(options.compress || {
                                                                warnings: false
                                                        }); // eslint-disable-line new-cap
-                                                       ast = ast.transform(compress);
+                                                       ast = compress.compress(ast);
                                                }
                                                if(options.mangle !== false) {
                                                        ast.figure_out_scope(options.mangle || {});
```
as per its use in [`UglifyJS2.minify()`](https://github.com/mishoo/UglifyJS2/blob/cf0951f72635f898ef9dc98ced3c73a1c488cc17/tools/node.js#L123-L124) and the [`uglifyjs CLI`](https://github.com/mishoo/UglifyJS2/blob/cf0951f72635f898ef9dc98ced3c73a1c488cc17/bin/uglifyjs#L457).

/cc @sokra @bebraw

**Comment by sokra** [comment]
done
