### ISSUE TITLE
import() scope/context customization

### ISSUE THREAD

**Issue by probablyup** [webpack/webpack#4399]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Dynamic `import()` in webpack is too eager and will descend recursively, even into `node_modules` with no way to customize that behavior. This isn't a problem in the browser `import()` API because it does not need knowledge of the destination path until import time, but webpack must preemptively create chunks for all possible options.

**If the current behavior is a bug, please provide the steps to reproduce.**
n/a, not a bug per-se

**What is the expected behavior?**
Webpack `import()` should have an option to customize the expansion behavior, either through customizable scope like `require.context()` or the ability to limit recursion.

**If this is a feature request, what is motivation or use case for changing the behavior?**
In the case of a monorepo-style project setup, each folder can have its own `node_modules`. If an `import()` statement is targeted at one of those package folders, the import will eagerly create chunks for any matching file suffix in all of `node_modules`, which can cause the creation of tens of extra chunks that will never be used.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
All, n/a

A potential solution:

```js
import(`../packages/${packageDir}/README.md`, {
    context: /(?!node_modules)/,
}).then(/* ... */)
```

Or perhaps:

```js
import(`../packages/${packageDir}/README.md`, {
    recursive: false,
}).then(/* ... */)
```

**Comment by sokra** [comment]
`import()` doesn't allow additional options (by spec). Currently the only way to configure it is via ContextReplacementPlugin.

**Comment by probablyup** [comment]
@sokra I realize that, but in my explanation I outline why the spec isn't exactly apples-to-apples to what webpack is doing. 

Could you provide an example of how that plugin would leash import() without breaking regular require/import statements?

**Comment by probablyup** [comment]
Ok after studying https://bjacobel.com/2016/12/04/highlight-bundle-size/ I was able to form a strategy using `ContextReplacementPlugin` to handle my use case. I will say the DX of using that plugin is very difficult though... it would be nice to have a simpler mechanism.
