### ISSUE TITLE
when doing code splitting, unused vendor code is included.

### ISSUE THREAD

**Issue by the-xs** [webpack/webpack#4400]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
With react and material-ui as vendors,

Comparing two strategies:
1. Use ```CommonsChunkPlugin``` to split the vendor code. The vendor bundle is ~2M.
2. Just use entry file to bundle everything together, with tree shaking. The total bundle is about ~1M.

**If the current behavior is a bug, please provide the steps to reproduce.**

gist:
https://gist.github.com/the-xs/9ee9383ded0109911c505549786f7030

github:
https://github.com/the-xs/the-diy/tree/master/splitting-vs-shaking

**What is the expected behavior?**
When doing code splitting, vendor bundles should also do the tree shaking.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

webpack 2.2.1
ubuntu 16
node 6.9.5

**Comment by timse** [comment]
well the points of having a vendor bundle is, that it bundles vendor files right?
Therefore it can be used by "whomever" and cached for a long time independent of the rest of the code.
If you treeshake the vendor bundle this bundle is tighly coupled to your actual build each time.

I think you may want to look into "aggressive splitting plugins" and others.
