### ISSUE TITLE
DeprecationWarning should print a call stack

### ISSUE THREAD

**Issue by mohsen1** [webpack/webpack#4401]
It's impossible to know which loader or plugin needs to be updated in order to fix the warning. I usually get an error like this:

```
(node:4475) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
```

**Comment by bebraw** [comment]
Please set `--trace-deprecation` as instructed at [node docs](https://nodejs.org/api/cli.html#cli_trace_deprecation).
