### ISSUE TITLE
Adding a `watch-close` plugin/event

### ISSUE THREAD

**Issue by jameslnewell** [webpack/webpack#4405]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

The only way to know when the watcher stops watching is if you add a callback to `watcher.close()`. If I don't have access to the watcher (e.g. `hot-dev-middleware` created it and I no longer have access to the middleware), then I have no way of knowing that the watcher stopped.

**What is the expected behavior?**

There's already a `watch-run` event.

I would like `webpack.plugin('watch-close', () => console.log('watching closed'))` to be emitted when the watcher has closed and compilation is `done`. 

https://github.com/webpack/webpack/blob/479a0a4b7b22ed9c65c2f3c472a1be56db5ee0f0/lib/Compiler.js#L135

**If this is a feature request, what is motivation or use case for changing the behavior?**

To simplify waiting on a number of compilers to close.

**Comment by jameslnewell** [comment]
I'm can submit a PR if you're happy with the behaviour described above.

**Comment by sokra** [comment]
Sure a PR would be great. Also see MultiCompiler.js
