### ISSUE TITLE
the key name minChunks of CommonsChunkPlugin's configuration should be changed

### ISSUE THREAD

**Issue by zzzgit** [webpack/webpack#4406]
**Do you want to request a *feature* or report a *bug*?**
no
**What is the current behavior?**
In the configuration object of [`CommonsChunkPlugin`](https://webpack.js.org/plugins/commons-chunk-plugin/),there is a key named `minChunks`.
It should be renamed because the usage of this method is to determine whether or not a particular module should be extracted.
You can assign a function to it,with the complex logic  in it,not only the count testing against the number  of chunks the module is in.
Maybe `test` is appropriate.
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Just rename the method
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by bebraw** [comment]
On a related note, if that part is touched I would propose at least the following:

* Validate options. Currently extra fields can fail silently.
* Consider splitting into a couple of plugins. The boolean flags are a clue of where to split. It would be easier to explain as three or more focused plugins.
* `minChunks` accepts too many different values. It might be better to drop values like `Infinite` and re-design a field around its usage.

There may be more, but these are the most important things on the top of my mind.
