### ISSUE TITLE
the confusing concept bundle and chunk

### ISSUE THREAD

**Issue by zzzgit** [webpack/webpack#4409]
**Do you want to request a *feature* or report a *bug*?**
no
**What is the current behavior?**
There is no definite definitions for the concept `bundle` and `chunk` in the documentation of both V1 and V2.
After a learning for several days,I found that they use `bundle` and` chunk` in the documentation alternately.As if there isn't a clear difference between `bundle` and `chunk`.
Am I right?If not,the effort for documentation improvement is needed.
If it is,I have two suggests:

1. use `chunk` instead of `bundle` everywhere,to avoid confusing
2. use `chunk` as a noun while `bundle` as a verb

**If the current behavior is a bug, please provide the steps to reproduce.**
no
**What is the expected behavior?**
no
**If this is a feature request, what is motivation or use case for changing the behavior?**
no
**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
no

**Comment by bebraw** [comment]
Can you re-open this at the [documentation repo](https://github.com/webpack/webpack.js.org/issues)? That's the right place for this.
