### ISSUE TITLE
Dynamic require with code-split per file

### ISSUE THREAD

**Issue by spadgos** [webpack/webpack#441]
Hey,

I'm trying to get something similar to this example working:
https://github.com/webpack/webpack/tree/master/examples/code-splitted-require.context

My problem sounds very similar to that described in #118, however I could not understand the proposed solutions on that thread. My situation is that I have a single page app, and each page has its own 'layout' file which then requires all the components needed for the page. To simplify the directory structure:

```
/layouts
  /one.js
  /two.js
  /three.js
/app.js <-- main entry point
```

`app.js` starts the application and then parses the route to find which layout to load and display. Using the code in the example, `one.js`, `two.js` and `three.js` all end up in the same chunk. Since these layouts do require a significant amount of code unique to each layout, I'd like to have them each be in their own chunk and only loaded when needed.

---

What I've tried so far:
- I've looked at the ContextReplacementPlugin but I could not decipher what the 'default regexp' was or what it actually affects?
- The [bundle loader](https://github.com/webpack/bundle-loader) plugin also seems to not quite address this issue? (Though I could definitely be wrong about that)

**Comment by jonathandion** [comment]
@sokra what is the different between require.ensure vs your code ? It's confusing.

Thanks.

**Comment by SleepWalker** [comment]
@jonathandion the difference is that `bundle-loader` creates an intermediate modules that calls `require.ensure`.

As a result in current chunk we get 3 intermediate modules (for each file from `layouts` directory) in following format:
```js
var cbs = [],
    data;
module.exports = function(cb) {
    if(cbs) cbs.push(cb);
    else cb(data);
}
require.ensure([], function(require) {
    data = require("xxx");
    var callbacks = cbs;
    cbs = null;
    for(var i = 0, l = callbacks.length; i < l; i++) {
        callbacks[i](data);
    }
});
```

Each of this intermediate modules has `require.ensure` and `require` call for one of modules from context pattern, e.g. `require('./one.js')`. In this case we have no dynamic parts in module path, so we will get exactly one new **separate** chunk for each intermediate module.

**Comment by codeofsumit** [comment]
@sokra could you provide an example how this is used when coming from the regular `require.ensure` syntax? 

```
  var lang = navigator.language;
  require.ensure([], function(require) {
    window.setTimeout(function() {
      var translations = require('./countryTranslations/' + lang + '.json');
      console.log(translations);
    }, 3000);
  });
```

Webpack is loading the entire `countryTranslations`-folder. How can I use your solution to only load the json needed?

**Comment by codeofsumit** [comment]
ok I think my usecase is not possible as webpack can't possibly bundle the files I need later when `lang` is defined during runtime. Duh.

**Comment by ilyazub** [comment]
@codeofsumit You can try something like
```javascript
var lang = navigator.language;
var loadCountryTranslations = require('bundle?lazy!./countryTranslations/' + lang + '.json');

window.setTimeout(function() { // just to test if it's loaded async, later
  loadCountryTranslations(function (translations) {
    console.log(translations);
  });
}, 3000);
```

Check out [po-loader documentation](https://github.com/perchlayer/po-loader/blob/8c33ede443fb0d1f0c9f8521535f80c548889336/README.md#coffeescript-async-simple-example) for further explanations.

Or use [I18nPlugin](https://github.com/webpack/webpack/tree/master/examples/i18n) instead.

**Comment by Jatin-Chitkara** [comment]
@sokra Hi in Webpack .. module.export
output.chunkFilename = './enq[name].chunk.js' is like this and it works perfect on localhost.

But on my prod/stage enviornment i want to load chunks dynamically like:

output.chunkFilename = 'https://stg-m.imimg.com/im-lite/[name].chunk.js'

when i do this the root folder gets appended at start ex:
'https://stg-m.indiamart.com/https://stg-m.imimg.com/im-lite/[name].chunk.js'

the point is pls tell how can i  transform this 'https://stg-m.indiamart.com/https://stg-m.imimg.com/im-lite/[name].chunk.js' to 'https://stg-m.imimg.com/im-lite/[name].chunk.js'.
