### ISSUE TITLE
Hot reloading does not trigger refresh if update cannot be applied

### ISSUE THREAD

**Issue by mkalish** [webpack/webpack#4412]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Using `hot: true`, my expectation is that the page will be refreshed, if the update cannot be applied.  However, updates that are not applied do not trigger a refresh.

**If the current behavior is a bug, please provide the steps to reproduce.**
This configuration will cause the problem.
https://gist.github.com/mkalish/c1acffbe2ec349efbbabb076f346d297

**What is the expected behavior?**
My expectation is that when a hot update cannot be applied in the browser, a refresh will be triggerd

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Node: 6.9.1
Webpack: 2.2.1
Browser: Chrome 56.0.2924.87

**Comment by bebraw** [comment]
Hi,

There's not enough information to debug. Any chance you could include the client portion where you implement the HMR interface?

**Comment by sokra** [comment]
`webpack/hot/only-dev-server` -> `webpack/hot/dev-server`?

**Comment by mkalish** [comment]
@bebraw 
Sorry for the delay, shouldn't open tickets around vacations.  I'll pull together client code, but its taking longer than expected to extract code I can post.  

The issue stems from using angular 1 and react in the same application.  The react modules are updated via HMR, but the angular code can't be.  Previously, changes to the angular code would trigger a page refresh and changes to the react modules would get in via HMR.

**Comment by bebraw** [comment]
@mkalish Yeah, give Tobias' suggestion a go. It should be close to what you want. If `webpack/hot/dev-server` doesn't work, there might be something else going on.
