### ISSUE TITLE
Wrong error message details `cannot find module`

### ISSUE THREAD

**Issue by seokirill** [webpack/webpack#4413]
*Bug*

Two crazy nights ago I forgot to install postcss-loader, so all this time I'd tried to use this loader and seen error message like this: 
> Uncaught Error: Cannot find module "./style.scss"

Did you understand? `style.scss`, but not `postcss-loader`!
Unstoppable reading all articles and tutorials, but nothing works.

Some magic helps me, and I saw, that in my `package.json` I cant find `postcss-loader`.
Of course, when I install it - I was happiest tired man of world.

**If the current behavior is a bug, please provide the steps to reproduce.**
Please fix this lie about module name, which webpack2 cannot find.

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

- MacOS Sierra 10.12.3
- NodeJS v6.9.3 - v7.5.0
- Webpack v2.2.1

**Comment by michael-ciniawsky** [comment]
@seokirill Can ypu please post your `webpack.config.js`

**Comment by seokirill** [comment]
[js.task.js.zip](https://github.com/webpack/webpack/files/815842/js.task.js.zip)

**Comment by timse** [comment]
can you create a repo or paste your config here?
not going to download random zip files :)

**Comment by tejasbubane** [comment]
> can you create a repo or paste your config here?

Or create a gist.

**Comment by timse** [comment]
closing for now.
Please provide a gist, a reproducible example repo or at least something so we one can look at the issue.

**Comment by seokirill** [comment]
Look my comment, I attach it:
https://github.com/webpack/webpack/issues/4413#issuecomment-283866020
