### ISSUE TITLE
UglifyJSPlugin breaks alias module (mapbox-gl)

### ISSUE THREAD

**Issue by henningko** [webpack/webpack#4414]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When building for production, UglifyJSPlugin causes Mapbox to throw an `Reference Error: n is not defined`. Compiling/building works fine without UglifyJSPlugin.

**If the current behavior is a bug, please provide the steps to reproduce.**
I am using VueJS with webpack, and load Mapbox via
```javascript
function resolve (dir) {
  return path.join(__dirname, '..', dir)
}
...
alias: {
      'mapbox-gl': resolve('node_modules/mapbox-gl/dist/mapbox-gl.js'),
      'webworkify': 'webworkify-webpack'
}
```
because of this [incompatibility](https://github.com/mapbox/mapbox-gl-js/issues/1649).
In my vue-file, Mapbox is imported as `import mapboxgl from 'mapbox-gl';`.

My build configuration:
Base:
https://gist.github.com/henningko/5a76d12a14e485bfc4dd62c2e50ad08e
Production:
https://gist.github.com/henningko/3387f41a55558af60205ea00bbc6b530

**What is the expected behavior?**
The build should run without Reference Errors produces—or provide a way to leave mapbox-gl untouched.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
OS X 10.12.3
Node v7.6
npm 4.4
webpack 2.2.1

Thanks :)

**Comment by kzc** [comment]
Can you post the version of `uglify-js` used by `webpack` via `npm ls`?

At the time of your report `uglify-js@2.8.5` was released. It had a number of bugs.

Please try the latest unreleased version of webpack on `master` with `uglify-js@2.8.12` and report your findings.

**Comment by matthewheck** [comment]
Thanks for opening this @henningko and your suggestions @kzc.

I was having the same issue and have tried to approach this with the 2.8.12 release of uglify-js in use.

First, I tried using the [Uglify JS Webpack Plugin](https://github.com/webpack-contrib/uglifyjs-webpack-plugin) with the 2.8.12 release of uglify-js as a peer dependency. The same problem @henningko brought up still happened.

I then tried using the webpack `master`. I confirmed that `uglify-js@2.8.12` was installed and, again, had the same problem.

**Comment by kzc** [comment]
`mapbox-gl` fix : https://github.com/mapbox/mapbox-gl-js/issues/4359#issuecomment-315231975

Background:

https://github.com/mishoo/UglifyJS2/issues/2011#issuecomment-304468747

https://github.com/facebookincubator/create-react-app/issues/2376#issuecomment-304699313

**Comment by evilebottnawi** [comment]
@webpack-bot move to webpack-contrib/uglifyjs-webpack-plugin
