### ISSUE TITLE
Ignore plugin missing from webpack 2 docs

### ISSUE THREAD

**Issue by glenjamin** [webpack/webpack#4417]
**Do you want to request a *feature* or report a *bug*?**
Docs bug

**What is the current behavior?**
Webpack v1 docs include a section about [IgnorePlugin](http://webpack.github.io/docs/list-of-plugins.html#ignoreplugin) - although it is a tad cryptic.

**If the current behavior is a bug, please provide the steps to reproduce.**
Go to the webpack v2 docs site

**What is the expected behavior?**
Webpack v2 docs don't mention this plugin at all.

**If this is a feature request, what is motivation or use case for changing the behavior?**
It would be good to add this and provide an explanation of what the second argument does that's easier to understand if you aren't familiar with webpack internal terms.

**Comment by bebraw** [comment]
Can you re-open at [docs repo](https://github.com/webpack/webpack.js.org/issues)? Thanks.

**Comment by umarashfaq** [comment]
https://github.com/webpack/webpack.js.org/issues/1014
