### ISSUE TITLE
Synchronous callback for require.ensure in Webpack 2

### ISSUE THREAD

**Issue by udovenko** [webpack/webpack#4419]
**Do you want to request a *feature* or report a *bug*?**
First of all: thank you so much for a great tool. Webpack is awesome!
I've asked my question on StackOverflow but still did not get an answer. So let's say I want to request a feature.

I have an isomorphic React/React-router project that uses Webpack and its Code Splitting feature. For each route there is a specific handler component that uses require.ensure statement to asynchronously load named chunk with content component if is not loaded yet or synchronously require it if is already available for Webpack runtime:

```
  componentWillMount() {
  ...
    require.ensure([], (require) => {
      this.setState({ contentComponent: require('../../components/PostsLoader').default });
    }, 'posts');
  ...
  }
```
To allow React reuse markup recieved from server (where content component renders without splitting, using regular require statement), when user visits concrete route (in our example, /posts), backend application adds <script src='.../posts-bundle.js'> to page <head>. With Webpack 1, require.ensure function finds required chunk and fires callback function synchronously. Content component loads immediately before first render and React is able to reuse server markup.

**What is the current behavior?**

Webpack 2 has changed behaviour of require.ensure, see https://webpack.js.org/guides/migrating/#require-ensure-and-amd-require-is-asynchronous. Now even if corresponding chunk was added to the page header with <script src='.../posts-bundle.js'>, this.contentComponent === undefined on initial render which causes React warning like:

```
Warning: React attempted to reuse markup in a container but the checksum was invalid...
and so on.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

To run this project with Webpack 2 I need a way to run callback for require.ensure synchronously as it was in Webpack 1. Is it possible to add some kind of fourth bool parameter to require.ensure like <callbackSync: bool>? Or maybe there is another workaround?

**If this is a feature request, what is motivation or use case for changing the behavior?**

Returning a Promise from require.ensure is good approach, but firing callback function allways asynchronously logically seems not very useful. When require.ensure fires callback synchronously it means "ok, our module is here, you can use it right now". When it is allways async, it means "you will get your module soon" no matter whether JSONP request required or not so you can't render immediatly in your app.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by sokra** [comment]
https://github.com/ctrlplusb/react-async-component

**Comment by udovenko** [comment]
@sokra, thanks for suggested workaround. Unfortunatenly it brings a lot of extra code and possible new issues with HMR (https://github.com/ctrlplusb/react-async-component/issues/14) to the project, and seems a big unnecessary complication comparing to clear and straightforward sync callback feature of require.ensure. As many other developers, I allways prefer to reduce a number of dependencies in projects. Moreover, what about projects that do not use React and have no existing solutions like you've suggested?

**Comment by timse** [comment]
you could give this a shot :) 

sounds reasonable to not want to handle all your async loading yourself anyways :).

https://medium.com/@thejameskyle/react-loadable-2674c59de178

**Comment by mastilver** [comment]
If you are using `babel` you can use:
- https://github.com/airbnb/babel-plugin-dynamic-import-node to make `import()` synchronous
- https://github.com/mastilver/babel-preset-when if you need to have different setup for diff env

**Comment by wilbert-abreu** [comment]
@mastilver Can you give an example of how you would use `dynamic-import-node` to solve this? I also have an isomorphic React/React-router project that uses Webpack and its Code Splitting feature and I'm getting the same console error as @udovenko, `Warning: React attempted to reuse markup in a container but the checksum was invalid...`. 

Here's the webpack 1 code that I use for code splitting:
```
const loadModule = callback => (module) => {
  const Component = module.default;
  callback(null, props => <Component {...props} />);
};

require.ensure(['#pages/home'], (require) => {
          loadModule(callback)(require('#pages/home'));
        }, /* chunk name */ 'home');
``` 
and here's my attempt at using `dynamic-import-node` and Webpack 2, but still getting the same error: 
```
const errorLoading = (err) => {
  console.error('Dynamic page loading failed', err);
}

import('#pages/home').then(() => (
          loadModule(callback)(require('#pages/home'))
        )).catch(errorLoading);
```

**Comment by udovenko** [comment]
@mastilver, @wilbert-abreu ```import``` does not allow to provide chunk name (see https://webpack.js.org/guides/code-splitting-import/#import-supersedes-require-ensure-) so you cant't preload named chunk by putting its ```<script>``` tag before bindle ```<script>``` (please correct me if I'm wrong).

https://github.com/ctrlplusb/react-async-component suggested by @sokra is a possible solution for projects that use Node.js as a backend. But I'm using Ruby on Rails with react_on_rails gem and can't use this solution due to some limitations.

For now I ended up adopting ```react-tree-walker``` (https://github.com/ctrlplusb/react-tree-walker) which is a dependency of ```react-async-component```. This is what my code for initial client render looks like:

```
import reactTreeWalker from 'react-tree-walker';
import ReactDOM from 'react-dom';

....

// Store React app tree for further parsing and rendering:
const app = (
  <Provider store={store}>
    <Router history={history} children={routes}/>
  </Provider>
);

// Here we will put promises from Webpack require.ensure calls made by visitor() function:
const loadChunksPromises = [];

// Visitor function for reactTreeWalker. See https://github.com/ctrlplusb/react-tree-walker for details.
// If visited object is a component instance and component constructor has "loadWebpackChunk" function (a static
// method in class definition), function calls it and puts resulting Promise to loadChunksPromises array:
const visitor = (element, instance, context) => {
  if (!instance) return;

  const instancePrototype = (Object.getPrototypeOf(instance));
  const instancePrototypeConstructor = instancePrototype.constructor;

  if (typeof instancePrototypeConstructor.loadWebpackChunk !== 'function') return;

   loadChunksPromises.push(instancePrototypeConstructor.loadWebpackChunk());
};

// Walk React app tree to find Webpack async code chunks start loading them. Render app only when all chunks are loaded:
reactTreeWalker(app, visitor).then(() => {
  return Promise.all(loadChunksPromises);
}).then(() => {
  ReactDOM.render(app, document.getElementById(domNodeId));
});
```
This code iterates over the tree components and calls ```loadWebpackChunk``` static method for each component class. ```loadWebpackChunk``` contains regular ```require.ensure``` statement and returns a ```Promise``` that will be resolved when chunk is loaded.

This solution works for me but it requires a lot of additional code, adds extra complexity and moreover utilizes CPU for traversing React components tree on every initial render.

**Comment by prannayb** [comment]
I have the same issue when migrating from webpack 1 to 2. I used require.ensure to create a separate chunk file for server runtime values. Then I included this chunk in my html, and replaced certain template strings in the chunk at serve time. Earlier the split module's require would resolve synchronously and I could use the chunk to populate flight changes/constants. Now it's async and I'll have to re-arch everything needing the flights to be promise based (after require resolves) even though the chunk gets loaded. It would be great to have sync ability again for perf. Please tell us if this enhancement is something that's gonna happen or does it violate some design?

**Comment by wilbert-abreu** [comment]
@udovenko You are right, now we cannot set chunk names using `import`. But, I noticed there is a PR right now to add this feature (#4573), so hopefully coming soon.

Also, thank you for your example. That's a interesting solution, but as you say it introduces it little to much complexity and I have a large app so would not want to have to traverse the whole react component tree on every initial render.

**Comment by udovenko** [comment]
@wilbert-abreu Looks like ```react-tree-walker``` allows to stop traversing current branch if ```visitor``` function returns something different than ```undefined```. So you could prevent your app from traverse the whole tree and stop early if your components with ```require.ensure``` are not too deep in the hierarchy. Did not try it myself yet though.
This doest not solve an original problem ofcourse. Adding this just FYI...

**Comment by rishmaflipkart** [comment]
@wilbert-abreu Hey I am trying to solve a problem similar to yours. Were you finally able to use import() in code splitting with dynamic-import-node plugin?

**Comment by johnhforrest** [comment]
+1, would love to see a more supported way of doing this. We cannot move to webpack 2 or 3 without having to do massive amounts of refactoring to support loading modules async.
