### ISSUE TITLE
Allowing System.import to import from auto generated module from memory.

### ISSUE THREAD

**Issue by bruk1977** [webpack/webpack#4420]
**Do you want to request a *feature* or report a *bug*?**
Feature request

**What is the current behavior?**
System.import allows to import a module only from a disk. 

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Allowing System.import to import from a module content in memory.

**If this is a feature request, what is motivation or use case for changing the behavior?**
If System.import allows to accept module content instead of a path to a module, it allows to assemble a module at run time.

The scenario I've is, editors configure modules of a page using a CMS. I've a service that will read what is configured by editors and planning to automatically generate module script that will import all the modules configured by editors. If System.import supported importing a module using a content, I would pass auto generated content to System.import instead of saving to a disk and passing a path to system.import. Saving on a disk for lots of users for different configuration of a page will have a performance impact.

Thanks,
Bruk

**Comment by sokra** [comment]
You can use a loader to generate content while compilation:

i. e. `import("./my-loader!")`

Export a function returning a string from `my-loader`.

**Comment by bruk1977** [comment]
@sokra thanks for your suggestion... Actually, I want to generate the bundle at run time... looks like system.import is only a build time thing and can't use. I'm exploring webpack node api to create a Node service and have bundle as a service.

**Comment by lovedota** [comment]
Hi @sokra Is there anyway to `import('http://cdn.bundle1.js')` import at run time from CDN ?

**Comment by montogeek** [comment]
@lovedota Create a new issue.
