### ISSUE TITLE
configuring webpack public path at runtime

### ISSUE THREAD

**Issue by kellyrmilligan** [webpack/webpack#443]
We have slightly different public path urls per environment, which come from a module on the server side. in looking at the config docs, you have a suggested method of doing this, but after trying several combinations, I ended up setting 

`__webpack_require__.p`  

and not 

`__webpack_public_path__`

Is this correct?

**Comment by univerio** [comment]
This breaks down when using CoffeeScript, because assignments to free vars are compiled to `var __webpack_public_path__ = ...`. Perhaps the solution is to allow setting things on a single webpack free variable?

e.g.
```
__webpack__.publicPath = '...'
```

**Comment by loganfsmyth** [comment]
@univerio You can explicitly reference the global scope:

    window.__webpack_public_path__ = '...'

**Comment by univerio** [comment]
@loganfsmyth `__webpack_public_path__` is not on the global scope. It is a free variable which gets rewritten by webpack into `__webpack_require__.p`.

**Comment by loganfsmyth** [comment]
@univerio You are right, my mistake, sorry :(

**Comment by bebraw** [comment]
@kellyrmilligan Safe to close?

**Comment by ssolders** [comment]
Just to add for anyone that runs into the same problem as me.

I had set my webpack publicPath using a const (defined like a free variable outside the scope). This did not work. Changing it into a var worked though.

**Comment by johnculviner** [comment]
Nice summary of how to do it in current documentation and even how to assign at runtime:
https://webpack.js.org/configuration/output/#output-publicpath

**Comment by kiran8910** [comment]
@kellyrmilligan 
Using window.resourceBaseUrl in main.ts is throwing an error as below
**Property 'resourceBaseUrl' does not exist on type 'Window'.**

I've defined resourceBaseUrl in index.html under src/public

**Comment by bring2dip** [comment]
``__webpack_public_path__`` is not working when `runtime` chunk is separated(optimizations). `publicPath` is set from the build time rather than run time. Is anyone having this issue?

**Comment by troch** [comment]
After experimenting with it, it seems `__webpack_public_path__` is not used for JS assets but correctly used for other assets (I've tried with a png file). Dynamic chunks use the `publicPath` variable, which is hardcoded.

Is it intentional, or is it a bug?

The other problem I'm facing in being able to fully dynamically specify `publicPath` is that the runtime doesn't reference entry chunks. And when using `html-webpack-plugin`, `scripts` tags are static. Is there a way to delegate the loading of entry chunks to the runtime chunk?

**Comment by evilebottnawi** [comment]
Please don't write in old issues, fi you have problem feel free to open a new issue with reproducible test repo, thanks
