### ISSUE TITLE
Name spacing libraryTargets...

### ISSUE THREAD

**Issue by pstephenwille** [webpack/webpack#4430]
**Do you want to request a *feature* or report a *bug*?**
*feature*

**What is the current behavior?**
_Custom named objects are not valid libraryTargets_

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
_Add custom named object as the export value for 'libraryTarget'_

**If this is a feature request, what is motivation or use case for changing the behavior?**

_In short, this would prevent name collision when multiple devs are authoring components across shared systems, which are dynamically loaded._

_Specifically, I want to lazy load Vue single file components that are name spaced in a custom named object. 
The resulting bundle would look something like,_
     
`var MyCustomObj[componentName] = webpack([0])....`

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by sokra** [comment]
Pass an array to `library`. This doesn't work with all `libraryTarget`s so check documentation.
