### ISSUE TITLE
webpack hang up when useing code splitting

### ISSUE THREAD

**Issue by zzzgit** [webpack/webpack#4432]
**What is the current behavior?**
webpack will hang up in the flowing situation which using code splitting 
**If the current behavior is a bug, please provide the steps to reproduce.**
1. code like this:
```javascript
import Bar from "./page/bar.vue"; // I forgot to remove this line,and it cause webpack to hang up
var component = function(resolve){
	require(["./page/bar.vue"],resolve)
}
```
2. then run webpack
3. it hang up

**What is the expected behavior?**
throw an error
**If this is a feature request, what is motivation or use case for changing the behavior?**
no
**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
no

**Comment by zzzgit** [comment]
What does S4 X4 mean?

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.
