### ISSUE TITLE
output.filename is required

### ISSUE THREAD

**Issue by sagaratyieldmo** [webpack/webpack#4434]
**Do you want to request a *feature* or report a *bug*?**
I'd like to report a bug

**What is the current behavior?**
this is the error message 
Error: 'output.filename' is required, either in config file or as --output-filename
    at processOptions (/Users/sagardubey/workspace/ts-sdk/node_modules/webpack/bin/convert-argv.js:488:11)
    at processConfiguredOptions (/Users/sagardubey/workspace/ts-sdk/node_modules/webpack/bin/convert-argv.js:141:4)
    at module.exports (/Users/sagardubey/workspace/ts-sdk/node_modules/webpack/bin/convert-argv.js:117:10)
    at Object.<anonymous> (/Users/sagardubey/workspace/ts-sdk/node_modules/webpack/bin/webpack.js:153:40)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:140:18)

**If the current behavior is a bug, please provide the steps to reproduce.**
webpack v 2.2.1

this is my config file. There's no typo in filename or anywhere that I can see 

``` js
var webpack = require("webpack");
var path = require('path')
module.exports = {
  devServer: {
  },
  devtool: 'source-map',
  entry: {
    "ym.min": "./src/bootstrap.ts",
  },
  module: {
    rules: [
      {
        test: /\.ts$/,
        use: [
          {
            loader: "ts-loader"
          },
          {
            loader: "tslint-loader",
            enforce: "pre"
          }
        ]
      }
    ],
    output: {
      filename: '[name].js',
      path: './dist'
    },
    plugins: [],
    resolve: {
      modules: [
        "node_modules",
        path.join(__dirname, 'node_modules')
      ],
      extensions: [".webpack.js", ".web.js", ".ts", ".js", "*"],
      enforceExtension: false,
      alias: {
        'handlebars': 'handlebars/runtime.js'
      }
    }
  }
}
```

If you try to use uglifyJS like so - it says "TypeError: Cannot read property 'unshift' of undefined"

``` js
var config = require('./webpack.config');
var webpack = require('webpack');

config.plugins.unshift(new webpack.optimize.UglifyJsPlugin({
  compress: {
    warnings: false
  },
  output: {
    comments: false,
  },
}));

module.exports = config;
```

**What is the expected behavior?**
It should work as earlier (v < 2.0.0)

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

macOS Sierra, node v5.6.0

**Comment by bebraw** [comment]
Your configuration is correct. How did you name it? How are you calling webpack? If you are using something else than the supported default names, you will have to pass it to webpack through `--config`.

**Comment by sokra** [comment]
Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md).
