### ISSUE TITLE
cli webpack --env.platform=web doesn't work

### ISSUE THREAD

**Issue by zzzgit** [webpack/webpack#4436]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
I can not fetch the environment variable passed from the cli.
**If the current behavior is a bug, please provide the steps to reproduce.**
1. cli: `webpack --env.foo=bar`
2. webpack.config.js: `const foo=process.env.foo`
3. `console.log(foo)`,get `undefined`

**What is the expected behavior?**
"bar" should be got
**If this is a feature request, what is motivation or use case for changing the behavior?**
no
**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
no

**Comment by TheLarkInn** [comment]
Can you please provide a reproducible tiny repo that we could use as basis for our test cases and triage?

**Comment by bebraw** [comment]
Hi,

It does **not** set `process.env`.

You should capture the value by exporting a function from your webpack configuration. If you want to set the env, you would either have to do it there or go some other way.

**Comment by bebraw** [comment]
I'm closing this as what you are seeing is the expected behavior.
