### ISSUE TITLE
FlagIncludedChunksPlugin  bug

### ISSUE THREAD

**Issue by xuqiang2537** [webpack/webpack#4438]
**Do you want to request a *feature* or report a *bug*?**
   report a bug

**What is the current behavior?**
In file: webpack/lib/optimize/FlagIncludedChunksPlugin   
Line 14:   if(chunkA === chunkB) return;
Line 15:  //if chunkB in chunkA?

In this place,  we add chunkB.id into chunkA.ids
Without checking whether chunkB.modules has nothing 
That would make stable source package (like lib ui)   unable to use cache
Because  the chunkhash always change

 Adding this line:  "if (!chunkB.modules.length) return”  
in Line16 might be helpful, we think.
**If the current behavior is a bug, please provide the steps to reproduce.**

demo:https://github.com/xuqiang2537/webpack-chunkhash
1、packing my project
2、Modify ./src/app.js, comment out "return System.import('./module2/index.html');’" in Line31
3、repacking
4、Then I find all files and chunkhash has changed, however, I only want to change app-[chunkhash].js and manifest-[chunkname].js

**What is the expected behavior?**
stable source package(like lib ui ) could use unchangeable chunkhash
**If this is a feature request, what is motivation or use case for changing the behavior?**
not a feature request
**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
we tried webpack@beta and the issue still exists

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by xuqiang2537** [comment]
My demo:https://github.com/xuqiang2537/webpack-chunkhash

1. packing my project
2. Modify ./src/app.js, comment out "return System.import('./module2/index.html');’" in Line29
3. repacking
4. Then I find all files and chunkhash has changed, however, I only want to change app-[chunkhash].js and manifest-[chunkname].js
