### ISSUE TITLE
Errors in console with HMR

### ISSUE THREAD

**Issue by Mangatt** [webpack/webpack#4441]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When using configuration from Guides/Hot Module Replacement - React, webpack does not show errors from inside of components in browser console, but only in red overlay. When you need more info about bug, this is fairly useless. Playing with devServer settings does not affect this issue and errors outside components are correctly shown in console.

**If the current behavior is a bug, please provide the steps to reproduce.**

Follow https://webpack.js.org/guides/hmr-react/, try to insert undefined variable outside component (App.js:3: ```console.log(nonExistentVariable```) and inside component (App.js:5: ```className={nonExistentVariable}```).

**What is the expected behavior?**

These two cases should behave the same.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Same package config as in the guide, Win 10 64bit & Chrome 56.

**Comment by sokra** [comment]
Please file this issue on webpack/webpack.js.org.

**Comment by Mangatt** [comment]
I believe that this is problem with webpack itself, not with guide. I can't see reason for different behavior in different contexts.

**Comment by sokra** [comment]
cc @SpaceK33z

**Comment by AlexKvazos** [comment]
This is an issue with react-hot-loader. It wraps errors and renders a RedBox component instead of doing normal throw to console behaviour.

Source: https://github.com/gaearon/react-hot-loader/issues/462

**Comment by Mangatt** [comment]
Thanks, @AlexKvazos
