### ISSUE TITLE
Manifest when using multiple vendors and commons chunks simultaneously

### ISSUE THREAD

**Issue by MtDalPizzol** [webpack/webpack#4445]
I followed the example in [common-chunk-and-vendor-chunk](https://github.com/webpack/webpack/tree/master/examples/common-chunk-and-vendor-chunk) but I'm also using multiple instances of the CommonsChunkPlugin. Here is the relevant configs:

```javascript
{

  entry: {

    'desktop/index': './js/desktop/index.js',
    'desktop/post': './js/desktop/post.js',
    'desktop/vendor': [
      'jquery'
    ],

    'mobile/index': './js/mobile/index.js',
    'mobile/vendor': [
      'jquery'
    ]

  },

  output: {
    filename: '[name].[chunkhash].js',
    chunkFilename: 'chunk.[chunkhash].js',
    path: path.resolve(__dirname, 'dist')
  },

  plugins: [
    new webpack.optimize.CommonsChunkPlugin({
      names: ['desktop/common', 'desktop/vendor'],
      chunks: ['desktop/index', 'desktop/post'],
      minChunks: 2
    }),
    new webpack.optimize.CommonsChunkPlugin({
      names: ['mobile/common', 'mobile/vendor'],
      chunks: ['mobile/index'],
      minChunks: 2
    })
  ]

};
```

And the build seems to be correct:

```
                                 Asset       Size   Chunks                    Chunk Names
  mobile/index.baa6ab4a4f62f25564ff.js    1.42 kB  0, 5, 6  [emitted]         mobile/index
 desktop/index.236c4e6e375a870d353b.js  887 bytes     1, 6  [emitted]         desktop/index
  desktop/post.7ca5365953dac57d7302.js  524 bytes     2, 6  [emitted]         desktop/post
desktop/vendor.b2e3b72f531e1a0ab842.js     274 kB  3, 4, 6  [emitted]  [big]  desktop/vendor
 mobile/vendor.4330c96ca776ad08e16c.js     274 kB  4, 3, 6  [emitted]  [big]  mobile/vendor
desktop/common.5a885605fc51ff0a90f2.js    5.92 kB     5, 6  [emitted]         desktop/common
 mobile/common.eb6b4a3b2aeb1164ec5f.js    5.75 kB        6  [emitted]         mobile/common

```

I added the files to my pages in the following order:

```
<script src="dist/desktop/vendor.b2e3b72f531e1a0ab842.js" charset="utf-8"></script>
<script src="dist/desktop/common.5a885605fc51ff0a90f2.js" charset="utf-8"></script>
<script src="dist/desktop/index.236c4e6e375a870d353b.js" charset="utf-8"></script>
```

and then I got the following error:

```
Uncaught TypeError: Cannot read property 'call' of undefined     vendor.b2e3b72….js:55 
    at __webpack_require__ (vendor.b2e3b72….js:55)
    at Object.5 (index.236c4e6….js:17)
    at __webpack_require__ (vendor.b2e3b72….js:55)
    at webpackJsonpCallback (vendor.b2e3b72….js:24)
    at webpackJsonpCallback (common.5a88560….js:19)
    at index.236c4e6….js:1
```

Seems like I also need something like a manifest file, but there's none in the example and I'm not sure if this is a bug or the expected behavior. I've [made a repo](https://github.com/MtDalPizzol/webpack-multi-starter) that you guys can clone to reproduce this behavior.

**System info:**

**OS**: Linux Mint 18 Cinnamon 64-bit
**Node version**: 6.10.0
**NPM version**: 4.3.0
**Webpack version**:  2.2.1

**Comment by sokra** [comment]
new webpack.optimize.CommonsChunkPlugin({
      names: ['desktop/common', 'desktop/vendor'],
      chunks: ['desktop/common', 'desktop/index', 'desktop/post'],
      minChunks: 2
    }),
    new webpack.optimize.CommonsChunkPlugin({
      names: ['mobile/common', 'mobile/vendor'],
      chunks: ['mobile/common', 'mobile/index'],
      minChunks: 2
    })

**Comment by MtDalPizzol** [comment]
Awesome! It works! Thanks @sokra. I strugled with this for days, literally.
So, I don't really need a manifest file or it is mandatory for long term caching?

**Comment by arunoda** [comment]
@MtDalPizzol @sokra How did fix the issue.
I'm kind a clueless. 

Any help would be great.

**Comment by MtDalPizzol** [comment]
I think @sokra can explain this in a better way. But what did the trick for me was adding the `common` chunk to the `chunks` arrays property. You can take a look at [this working repo](https://github.com/MtDalPizzol/webpack-multi-starter).

**Comment by arunoda** [comment]
@MtDalPizzol okay. Got it.

**Comment by damianobarbati** [comment]
I can't figure this out.
@MtDalPizzol how do we create multiple bundles with:
. entry file (i.e: apps/admin/index.js)
. vendor file (i.e: lodash, react, whatever)
. manifest file
?
Did you sort this out?

**Comment by MtDalPizzol** [comment]
Hey @damianobarbati ! Just be clear: I'm not a Webpack wizard like other guys around here. I'm absolutely not the best person to explain how the CommonsChunk plugin work, for example. Another thing is that I don't know the status of this since Webpack 2 was released. That said, what I can tell you is to read [this post on StackOverflow to understand how the plugin works](https://stackoverflow.com/questions/39548175/can-someone-explain-webpacks-commonschunkplugin) in a more detailed way. Also, I made a repo using the  the configs described above where I split dekstop and mobile bundles that share plugins. [You can take a look here](https://github.com/MtDalPizzol/webpack-multi-starter).

**Comment by wzup** [comment]
@sokra 
You guys really should do something with `CommonsChunkPlugin` and code splitting practice in Webpack. Rocket science seems easier than code splitting in Webpack now.

**Comment by wzup** [comment]
@MtDalPizzol 

What was your console output after fix? Could you share a screenshot?
That solutions doesn't work for me. `vendors` is always `big`.

**Comment by MtDalPizzol** [comment]
@wzup , Sorry for the delay. It's a long time since I worked on this issue. I'm not sure if something has changed in newer Webpack versions. Bu notice: the [**repo I made**](https://github.com/MtDalPizzol/webpack-multi-starter) only deals with multiple vendors with common chunks. It gives you **big** vendor chunks, but it gives you **multiple** vendor chunks (one for each endpoint I need). You'll have to optimize the code on your own, using other plugins. Here's an output after running `npm run build` on the repo.

```bash
Version: webpack 2.7.0
Time: 766ms
                                 Asset       Size  Chunks                    Chunk Names
  mobile/index.139001604b762995b658.js    1.42 kB    0, 2  [emitted]         mobile/index
 desktop/index.f466d38475c5ec0d93e1.js  885 bytes       1  [emitted]         desktop/index
desktop/common.f155698581328ad65fb1.js  138 bytes       2  [emitted]         desktop/common
  desktop/post.760f239cfe094cf0ecf0.js  522 bytes       3  [emitted]         desktop/post
desktop/vendor.685847226605410d6e37.js     278 kB    4, 5  [emitted]  [big]  desktop/vendor
 mobile/vendor.db44b7492d6d516c4ea9.js     278 kB    5, 4  [emitted]  [big]  mobile/vendor
   [0] ./js/plugins/plugin-2.js 61 bytes {0} {2} [built]
   [1] ./js/plugins/plugin-1.js 39 bytes {0} {1} [built]
   [2] ./~/jquery/dist/jquery.js 272 kB {4} {5} [built]
   [3] multi jquery 28 bytes {4} {5} [built]
   [4] ./js/plugins/plugin-3.js 39 bytes {0} [built]
   [5] ./js/desktop/index.js 88 bytes {1} [built]
   [6] ./js/desktop/post.js 69 bytes {3} [built]
   [7] ./js/mobile/index.js 132 bytes {0} [built]
Done in 1.30s.
```
