### ISSUE TITLE
import() doesn't resolve directories

### ISSUE THREAD

**Issue by smcmurray** [webpack/webpack#4447]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
import ('/some/path') fails to import /some/path/index.js

**If the current behavior is a bug, please provide the steps to reproduce.**
import a directory that contains an index.js

**What is the expected behavior?**

import() should follow the same rules as import for filename resolution

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by smcmurray** [comment]
import('my/lib') doesn't import my/lib/index.js
Both import and node's require do.
