### ISSUE TITLE
Code Splitting import() failed Karma unit testing with Vue.js

### ISSUE THREAD

**Issue by DrakeLeung** [webpack/webpack#4448]
**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**

Error when run unit test with *karma* and *mocha* 😞

```bash
ERROR LOG: '[Vue warn]: Error in render function:
(found in <Root>)'
ERROR LOG: ReferenceError{stack: 'MyLinks@http://localhost:9876/base/index.js?edba283f9d5be64918119d724e1984a43cd326e8:10013:17
resolveAsyncComponent@http://localhost:9876/base/index.js?edba283f9d5be64918119d724e1984a43cd326e8:3190:22
```

However, it works well if I use commonJS or ES6 module syntax , rather than `import()` 😱

**If the current behavior is a bug, please provide the steps to reproduce.**

I made a repo 4 reproduce easily -> [Check it out](https://github.com/DrakeLeung/dynamic-import-with-webpack-karma) 🚀

**What is the expected behavior?**

Unit test works well, no *EORROR LOG* 😌

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

* Node.js: `v7.6.0`
* webpack: `^2.2.1`
* karma: `^1.4.1`,
* karma-webpack": `^2.0.2`
* mocha: `^3.2.0`,
* macOS `10.11.6`

**Comment by timse** [comment]
it fails because you need to provide the test runner with a promise polyfill
see error line 10013 is ->  `return Promise.resolve().then(__webpack_require__.bind(null, 2));`

I will close this for now as it is not webpack related.

Feel free to reopen if you find it actually is a webpack issue.

**Comment by DrakeLeung** [comment]
It works after I add the polyfill. Thank you @timse
