### ISSUE TITLE
import() doesn't honor alias

### ISSUE THREAD

**Issue by smcmurray** [webpack/webpack#4449]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**
import() can't find aliased modules
**If the current behavior is a bug, please provide the steps to reproduce.**

import("AnyAlias/module")
**What is the expected behavior?**
It should locate module under the directory defined for the "AnyAlias" alias
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.
