### ISSUE TITLE
Incorrect line number for module not found errors with Typescript

### ISSUE THREAD

**Issue by brandonwamboldt** [webpack/webpack#4450]
**Do you want to request a *feature* or report a *bug*?**

Report a bug with Webpack 2.2.1.

**What is the current behavior?**

If I import a css file from a TypeScript source file, and the CSS file doesn't exist, I get a module not found error but the line number is wrong.

**If the current behavior is a bug, please provide the steps to reproduce.**

webpack.config.js:

```
const path = require('path');

module.exports = {
  entry: './src/js/index.ts',

  output: {
    filename: 'app.bundle.js',
    path: path.resolve(__dirname, 'build'),
  },

  resolve: {
    extensions: ['css', '.webpack.js', '.web.js', '.ts', '.tsx', '.js'],
  },

  module: {
    rules: [
      {
        test: /\.tsx?$/,
        loader: 'awesome-typescript-loader',
      }
    ],
  },
};
```

index.ts

```
//import * as Foo from 'foobar';
import './../css/main.css';
import './../css/no-such-file.css';
import './../css/main.css';
```

Error message:

```
ERROR in ./src/js/index.ts
Module not found: Error: Can't resolve './../css/no-such-file.css' in 'C:\Users\brandon.wamboldt\Projects\client-core\src\js'
 @ ./src/js/index.ts 5:0-36
```

**What is the expected behavior?**

The error should be on line 3

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Node version: v5.10.1
Webpack version: 2.2.1
NPM version: 3.8.3
OS: Windows 7 x64

**Comment by brandonwamboldt** [comment]
I've fixed the behavior locally by patching [`lib/Compilation.js#L260`](https://github.com/webpack/webpack/blob/master/lib/Compilation.js#L260), to lookup the source map:

```
var sourceMap = new SourceMapConsumer(module._source.map());

var originalStartPosition = sourceMap.originalPositionFor({ line: dependencies[0].loc.start.line, column: dependencies[0].loc.start.column });
var originalEndPosition = sourceMap.originalPositionFor({ line: dependencies[0].loc.end.line, column: dependencies[0].loc.end.column });

dependencies[0].loc.start.line = originalStartPosition.line;
dependencies[0].loc.start.column = originalStartPosition.column;

dependencies[0].loc.end.line = originalEndPosition.line;
dependencies[0].loc.end.column = originalEndPosition.column;
```

And at the top of the file I added:

```
const SourceMapConsumer = require("source-map").SourceMapConsumer;
```

Hopefully someone who knows what they're doing can make a Pull Request as I didn't really understand the context, and my solution may not work for all use cases.

**Comment by sokra** [comment]
This could be added as feature.
