### ISSUE TITLE
Multiple compilation triggered in watch mode

### ISSUE THREAD

**Issue by zjuasmn** [webpack/webpack#4455]
**Do you want to request a *feature* or report a *bug*?**
*Bug*

**What is the current behavior?**
This script trigger compilation multiple times(>20) for several seconds.

```js
const webpack = require('webpack');
const fs = require('fs');
const path = require('path');

fs.writeFileSync(path.resolve(__dirname, 'a.js'), +new Date());
const options = {
  entry: path.resolve(__dirname, 'a.js'),
  output: {
    path: __dirname,
    filename: 'main.js',
  }
};

webpack(options).watch(null, (error, stats) => {
  console.log(stats.toString());
});
```
would output below messages...
```
Hash: 516f1bfca6e6b50fe846
Version: webpack 2.2.0
Time: 45ms
  Asset     Size  Chunks             Chunk Names
main.js  2.64 kB       0  [emitted]  main
chunk    {0} main.js (main) 13 bytes [entry] [rendered]
    [0] ./a.js 13 bytes {0} [built]
Hash: 516f1bfca6e6b50fe846
Version: webpack 2.2.0
Time: 7ms
  Asset     Size  Chunks  Chunk Names
main.js  2.64 kB       0  main
chunk    {0} main.js (main) 13 bytes [entry]
    [0] ./a.js 13 bytes {0} [built]
Hash: 516f1bfca6e6b50fe846
Version: webpack 2.2.0
Time: 4ms
  Asset     Size  Chunks  Chunk Names
main.js  2.64 kB       0  main
chunk    {0} main.js (main) 13 bytes [entry]
    [0] ./a.js 13 bytes {0} [built]
...
...
```
**If the current behavior is a bug, please provide the steps to reproduce.**
 copy the code and run it. or in [runkit](https://runkit.com/zjuasmn/58c2085d9c53450014e85959)

**What is the expected behavior?**
Just trigger compilation once and keep watching.

**If this is a feature request, what is motivation or use case for changing the behavior?**
N/A

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Node.js v6.9.2, webpack v2.2.1, Mac OS

**Comment by timse** [comment]
interesting it has something to do with just writing the file before starting webpack, still shouldnt happen. But its a bug in webpack/watchpack, would you mind reopening the issue there?

**Comment by zjuasmn** [comment]
Thank you. I check watchpack and found that this issue is opened since Apr 2016.
webpack/watchpack#25

**Comment by timse** [comment]
👍 ill close then
