### ISSUE TITLE
should entry support function?

### ISSUE THREAD

**Issue by jerexyz** [webpack/webpack#4456]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
should write array or object
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
entry support function or promise,so can support dynamic entry
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by bebraw** [comment]
It supports a function already. The function should return a path or a Promise that resolves to a path. If you want anything more dynamic than that, point to a custom loader which does the dynamic bit you need (`'!./custom-loader'`).

**Comment by jerexyz** [comment]
can you give a example for this?

**Comment by bebraw** [comment]
```javascript
entry: () => './demo'
```

or

```javascript
entry: () => new Promise((resolve) => resolve('./demo'))
```

**Comment by jdoubleu** [comment]
There's no hint in the docs about providing a function, is it?
Maybe the docs should be updated?

**Comment by bebraw** [comment]
If someone has time to PR a doc tweak, go ahead. 👍

**Comment by jdoubleu** [comment]
I'm trying to use this feature and then I create a PR on this.

I came across the same point yesterday and tried to find this feature in the code. Although there is a spec in the JSON ([webpackOptionsSchema.json](https://github.com/webpack/webpack/blob/master/schemas/webpackOptionsSchema.json#L74))  I couldn't find this functionality in [DynamicEntryPlugin L40-L46](https://github.com/webpack/webpack/blob/master/lib/DynamicEntryPlugin.js#L40-L46).

**Comment by bebraw** [comment]
@jdoubleu You can find the related commit here, https://github.com/webpack/webpack/commit/a22b00e23d44f58932a513084f02d376c75854f7 . Sadly it didn't come with a doc PR.
