### ISSUE TITLE
Create `require.id()` extension to transform to evaluated module id. 

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack#4457]
Special Feature Request: 

Userland Code
`let foo = require.id("./foo");`

Bundled code
`__webpack_require__.id("moduleId");`

Evaluated Code
`let foo = 5`

**Comment by thejameskyle** [comment]
Example transform:
https://astexplorer.net/#/gist/ab79f5422fb01ed1b09344ee3d0dd5de/6647e6843929c675d82e85118d37c17b019d08a1

**Comment by timse** [comment]
is there more context available :D?

**Comment by TheLarkInn** [comment]
Yeah @timse, the implementation I built outside in a custom plugin. See github.com/thelarkinn/require-id-webpack-plugin

**Comment by thejameskyle** [comment]
The use case is for building tools like https://github.com/thejameskyle/react-loadable#example so that I can `import()` asynchronously if I need to or I can grab a module ID and `require()` it if I have it available already.

**Comment by timse** [comment]
Noice

**Comment by TheLarkInn** [comment]
I'm going to close this for now as we have this plugin created externally. `require.ensureWeak` should also be accomplishing a similar task already.
