### ISSUE TITLE
fs cannot be used with loaders in web context

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack#4458]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

Importing `fs` anywhere within a loader will cause a fatal crash (import error) assuming `web` target (default) is used.

**If the current behavior is a bug, please provide the steps to reproduce.**

Set up

```javascript
const fs = require('fs');

module.exports = function() {
  return 'foobar';
};
```

kind of loader and refer to it somewhere.

**What is the expected behavior?**

It should not crash on `require`.

**If this is a feature request, what is motivation or use case for changing the behavior?**

Given there are loaders like [fs-loader](https://github.com/kmalakoff/fs-loader), I assume this has worked in the past.

We got bitten by the issue at https://github.com/webpack-contrib/css-loader/issues/447 .

**Comment by jhnns** [comment]
Can't reproduce this one. I can require `fs` in a loader.

Can you provide a minimal example 😝?

**Comment by timse** [comment]
use the css loader, i dont think this is an actual webpack problem?

it was introduced here: https://github.com/webpack-contrib/css-loader/commit/6da7e90748364fe61231ba71e3d9057c41271f5f

which introduces a dependency to the web that contains FS which doesnt work.

might be im overseeing something though

**Comment by bebraw** [comment]
Here we go: https://github.com/bebraw/fs-demo . Note that now the `require` is in a dep of **css-loader**.

It must be some very specific condition as it was harder to reproduce the issue now than yesterday.

**Comment by timse** [comment]
still, the `css-base` code is injected into the browser.
This can not contain `fs` as there is no `fs` in the browser.

**Comment by bebraw** [comment]
Ok, makes sense. That would explain the crash.

Let's wait a bit for other comments and close as `wontfix`.

**Comment by timse** [comment]
i actually think this is a problem in css-loader, as it will break if this tries to be executed in the browser, except there is some webpack magic that reads the files in statically? But i guess not.
