### ISSUE TITLE
hashing and file-loader publicPath issues

### ISSUE THREAD

**Issue by necolas** [webpack/webpack#446]
All inputs and outputs are in this gist: https://gist.github.com/necolas/70ce242e71af828d7199

The main issues / unexpected results I'm having are:
1. The `hash` and `chunkhash` values don't change if the CSS changes when using the extract-text plugin. Probably tricky to have the `chunkhash` correct once text has been extracted, but I was expecting that the compilation `hash` would at least change.
2. The public path I'm using includes the `hash`, but the path output by `file-loader` contains a different `hash` from the one reported by webpack (and used to create a build dir) and it changes when the CSS changes.

(1) means that you can get the same `hash` for different build output, and the `chunkhash` will also be the same even if non-js assets change.

(2) means that the output css contains incorrect paths to images if you want to use the build `hash` in the public path name.

**Comment by tcurdt** [comment]
Hm. Is there documentation that explains where the "hash" is coming from?

**Comment by dmitry** [comment]
Would be great to see code where is the `[hash]` value generated... I've tried to research for a little, but without success. Any pointers @sokra?

**Comment by resistdesign** [comment]
@dmitry File loader outputs the `[hash]` of the file itself as opposed to the `[hash]` of the current compile from WebPack like you can declare in `output.filename`.

**Comment by dballesteros7** [comment]
I just ran into this problem. The fix from @sokra works but in the css-loader the `publicPath` should be `"./"`.

**Comment by TheLarkInn** [comment]
I'm going to close this as this was from webpack 1. 
If this is still an issue, please resubmit a new issue with the information listed in our issue template (version, repro repo, etc.)
