### ISSUE TITLE
Auto drop null values within entry.point[] and module.rules[]

### ISSUE THREAD

**Issue by kroko** [webpack/webpack#4460]
**Do you want to request a *feature* or report a *bug*?**

Feature.

**What is the current behavior?**

configuration.entry does not allow (does not ignore) null

```sh
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.entry should be one of these:
   object { <key>: non-empty string | [non-empty string] } | non-empty string | [non-empty string] | function
   The entry point(s) of the compilation.
```

This is expected behaviour.

**If the current behavior is a bug, please provide the steps to reproduce.**

N/A

**What is the expected behavior?**

N/A

**If this is a feature request, what is motivation or use case for changing the behavior?**

Consider one webpack config file both for development and production for a small project. The switching is done via `process.env.NODE_ENV` when building. Based on env there should or should not be some entries and/or rules.

Currently there would be need to do something like this

```javascript
// ...
  entry: {
    site: [
      'babel-polyfill',
      development ? 'react-hot-loader/patch' : null,
      development ? './src/mycustomdevinjection.js' : null,
      './src/site.js'
    ].filter((e) => e !== null),
    preflight: path.join(__dirname, 'src/preflight.js')
  },
// ...
```

which works.

`filter()`  could be avoided if webpack automatically would throw out `null` (while warning that such `null` was encountered) array elements, so that it could be written as

```javascript
// ...
  entry: {
    site: [
      'babel-polyfill',
      development ? 'react-hot-loader/patch' : null,
      './src/site.js'
    ],
    preflight: path.join(__dirname, 'src/preflight.js')
  },
// ...
```

Same thing applies to array elements for `module.rules` array
All rules that themselves are `null` or have value for `use` equaling `null` could be auto dropped.

```javascript
config.module = {
  rules: [
    // this is kept within module.rules
    {
      enforce: 'pre',
      test: /xxx$/,
      exclude: [],
      loader: 'some-legit-loader',
      options: {}
    },
    // this is autodropped from module.rules when not in development (element itself is null)
    (development)
    ? {
      test: /xxx/,
      exclude: [xxx],
      use: 'some-legit-loader'
    } : null,
    // this is kept within module.rules
    {
      test: /xxx$/,
      exclude: [],
      use: 'some-legit-loader',
      options: {}
    },
    // this is autodropped from module.rules when not in development (elements use value is null)
    {
      test: /xxx/,
      exclude: [xxx],
      use: (development) ? 'some-legit-loader' : null
    },
    // ExtractTextPlugin is special case and i will approach https://github.com/webpack-contrib/extract-text-webpack-plugin
    {
      test: /\.(scss)$/,
      use: ExtractTextPlugin.extract({
        fallback: 'style-loader',
        use: [
          // this is kept
          {
            loader: 'some-legit-loader'
          },
          // this is auto dropped
          {
            loader: (development) ? 'some-legit-loader' : null
          },
          // this is kept
          {
            loader: 'some-legit-loader'
          }
        ]
      })
    }
  ]
};

```

Of course, at this point I could traverse `config.module.rules` array and filter out all array objects for which `use` key has value of `null` (or for `enforce` type check value for `loader`), same way:

```javascript
rules: [{}, {}, {}].filter(
  // keep if object itself is not null, else drop
  // if object itself is not null (is kept), do second pass, to check
    // if use key exists and use !== null then keep (else drop) or 
    // if loader key exists and loader !== null then keep (else drop) 
)
```
But maybe webpack could do it by itself (or if some config key `removeNulls` is set to true).

What do you think?

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

```
    "webpack": "^2.2.1"
    "react-hot-loader": "^3.0.0-beta.6"
```

**Comment by timse** [comment]
Why should webpack cater for your "laziness" (not ment to be rude).
IMHO webpack already tries too much to cater for all kinds of quirky input and should be even stricter about it.
Why add complexity to webpack that needs to be taken care of, tested and maintained just so you can safe a "filter" call that is as simple as this?

**Comment by bebraw** [comment]
If you look at the implementation of `'react-hot-loader/patch'`, you'll see it detects the environment and returns either an empty or an actual implementation based on it. Once they release beta 7, you'll get this behavior.

You could do the same at `'./src/mycustomdevinjection.js'`. Check environment and return an implementation based on that.

I'm not convinced patching this at webpack level (i.e. checking for `null`) is the way. You can find third party solutions (including my **webpack-merge**) that were designed exactly for this problem. The core does not need to solve everything and we should strive to keep it as simple possible (complex enough already 😢 ).

**Comment by timse** [comment]
I will close this for now.

**Comment by kroko** [comment]
Was OOF. All points legit :) Thanks!
