### ISSUE TITLE
Lodash is exported to window

### ISSUE THREAD

**Issue by Vanuan** [webpack/webpack#4465]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

```
import lodash from 'lodash';
```

Open a page in browser, go to console type `window._`. It is not undefined.

**If the current behavior is a bug, please provide the steps to reproduce.**

The source code is this:

```
  if (typeof define == 'function' && typeof define.amd == 'object' && define.amd) {
    // Expose lodash to the global object when an AMD loader is present to avoid
    // errors in cases where lodash is loaded by a script tag and not intended
    // as an AMD module. See http://requirejs.org/docs/errors.html#mismatch for
    // more details.
    root._ = _;
```

The transpiled code looks like the following:

```
 if (true) {
    // Expose lodash to the global object when an AMD loader is present to avoid
    // errors in cases where lodash is loaded by a script tag and not intended
    // as an AMD module. See http://requirejs.org/docs/errors.html#mismatch for
    // more details.
    root._ = _;
```

**What is the expected behavior?**

`window._` should be `undefined`

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

webpack 2.2.0

**Comment by timse** [comment]
this is more of a lodash issue, as it checks for `AMD` first before it checks for `commonjs` or other patterns. 
As webpack allows `AMD` it accepts the amd define call and a side effect of that is that it is leaked globally.

please make this an issue against lodash :)

**Comment by jdalton** [comment]
This is not a Lodash issue as webpack is performing the source transform here.
Is there an option to not masquerade as an AMD loader? Is this transform something that's ON by default?

**Comment by timse** [comment]
if i understand it correctly you can define here: 
`https://github.com/webpack/webpack/blob/master/lib/WebpackOptionsApply.js#L240`

what will be used as the `typeof` value for `define.amd`, see:
`https://github.com/webpack/webpack/blob/master/lib/dependencies/AMDPlugin.js#L83`

therefore it could be used to prevent it to pass the check in lodash.

but i guess the "bigger" issue here is:

```
    // Expose Lodash on the global object to prevent errors when Lodash is
    // loaded by a script tag in the presence of an AMD loader.
    // See http://requirejs.org/docs/errors.html#mismatch for more details.
    // Use `_.noConflict` to remove Lodash from the global object.
```

which exposes lodash on the global object whenever it is loaded as an `AMD`.

Is there no better way for this? @jdalton

**Comment by timse** [comment]
and webpack kind of needs to pretent to know AMD to be able to handle modules defined as such

**Comment by jdalton** [comment]
> which exposes lodash on the global object whenever it is loaded as an AMD.
> ...
> Is there no better way for this?

Nope. This is the recommended way to handle it. See jQuery [also does this](https://github.com/jquery/jquery/blob/2d4f53416e5f74fa98e0c1d66b6f3c285a12f0ce/src/exports/global.js#L27-L34) (related [#jquery/557](https://github.com/jquery/jquery/pull/557)).

**Comment by timse** [comment]
and any chance to move commonjs ahead of AMD?

other than that, if its a real issue, either use `_.noConflict` @Vanuan 
or check `https://github.com/webpack-contrib/imports-loader` to mock the global object.

**Comment by timse** [comment]
the ultimately best way IIRC (please tell me if i am wrong @jdalton) would be to consume whatever you need from lodash explicitly anyways :P 

`import x from "lodash/x"`

(doesnt fix this issue but helps your code :))

**Comment by jdalton** [comment]
> and any chance to move commonjs ahead of AMD?

Nope. That [was done](https://github.com/lodash/lodash/commit/baa37450ccebeda149dfad834cdc8c314d64efe0) because of [r.js](https://github.com/requirejs/r.js), the RequireJS build optimizer.

**Comment by jdalton** [comment]
These checks aren't new. They've been done years before Webpack was a thing.

**Comment by timse** [comment]
> These checks aren't new. They've been done years before Webpack was a thing.

Not sure what to do with this information.

**Comment by jdalton** [comment]
Maybe let another core handle it. You seem to be at the limit of your usefulness here.

**Comment by timse** [comment]
![well bye](https://cloud.githubusercontent.com/assets/749171/23821448/d9e46e08-0686-11e7-99a4-36d82be7dd81.gif)

good luck adding edgecases for archaic frameworks

**Comment by Vanuan** [comment]
Some modules think they are special: underscore, jquery, some d3 plugins...

`window` is dead. Long live ES modules!

**Comment by jdalton** [comment]
> Some modules think they are special: underscore, jquery, some d3 plugins...
> `window` is dead. Long live ES modules!

This is about some modules thinking they're special. This was the recommended way to handle things to support AMD loaders. The heyday for AMD loaders has passed a bit but if Webpack is trying to support them it should work within the established cowpaths for it.

**Comment by Vanuan** [comment]
@jdalton how come it's an established path to leak globals if you're using RequireJS?

**Comment by jdalton** [comment]
> how come it's an established path to leak globals if you're using RequireJS

There's good reading [here](https://github.com/jquery/jquery/pull/557) and [here](https://github.com/jashkenas/underscore/pull/338). In the case of Lodash it can't be registered [as a named module](https://github.com/requirejs/requirejs/wiki/Updating-existing-libraries#register-as-an-anonymous-module-) so it can be aliased as `underscore` (to support Backbone, etc.).  When Lodash is loaded on a page there's no way to detect if it was loaded by an AMD loader or a traditional script tag so it has to export itself to the global object to handle the case where it's on a page with an AMD loader but not loaded by the loader.

**Comment by jdalton** [comment]
if I recall correctly these paths where done at the time with guidance of @jrburke, the creator of RequireJS and the AMD module format.

**Comment by jdalton** [comment]
Ah yes here it is. See the [Code suggestions section](https://github.com/requirejs/requirejs/wiki/Updating-existing-libraries#code-suggestions-) of the requirejs wiki. It points to [these examples](https://github.com/umdjs/umd/commit/bd963c7aa16e8e498b47ec543bbd2efd2117198a#diff-904f40bfd82b1293b1529aa2c4110ba0R22) *(check out the amdWebGlobal.js example)*
