### ISSUE TITLE
shared-worker-loader not works

### ISSUE THREAD

**Issue by alexey2baranov** [webpack/webpack#4467]
Hello!

i'm trying demo code from shared-worker-loader doc https://github.com/mrtnbroder/shared-worker-loader. Webpack compile successfully but nothing happend when page loaded (No console logs, no errors, no debugger started). What is my mistake and why Shared Worker does not loaded??
```js
var MySharedWorker = require('shared-worker-loader!./file')

var worker = new MySharedWorker()
worker.addEventListener('message', (e) => {console.log("message !!!!!!!!!!!!!!!!!!!1")})
worker.port.onmessage = (e) => {console.log("message ????????????????????????")}
worker.port.start()
```

**file.js**
```js
console.info("i am shared worker!!!")

onconnect = function (e) {
  sadfsadfsdaf.setdsaf().asfsadf()
  debugger
  console.log(e);
}
```

**Comment by bebraw** [comment]
Better wait for an answer at https://github.com/mrtnbroder/shared-worker-loader/issues/2. Thanks. 👍
