### ISSUE TITLE
`import` Promise doesn't resolve when loading cached script in IE10

### ISSUE THREAD

**Issue by mAAdhaTTah** [webpack/webpack#4472]
**Do you want to request a *feature* or report a *bug*?**

Report a bug.

**What is the current behavior?**

Related to #2189.

It appears that the Promise created by `import` to inject the dependent script never resolves in IE10 for scripts that are loaded from the cache.

**If the current behavior is a bug, please provide the steps to reproduce.**

I was able to reproduce this consistently in browserstack. If I loaded up the page, the first time it loads everything correctly. If I navigate to a different page, the scripts aren't loaded, but if I clear the browser cache, navigating to the next page works again.

We are loading a few other scripts on page load through similar mechanisms (injecting `<script>` tags into the `<head>`), but there aren't so many injected that way (6-10 maybe?).

**What is the expected behavior?**

Promise resolves so execution continues.

**If this is a feature request, what is motivation or use case for changing the behavior?**

N/A.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

WebPack 2.2.1

**Comment by sokra** [comment]
I guess `script.src` need to be set after the callbacks are registered. IE is weird here.

Do you want to send a PR?

**Comment by mAAdhaTTah** [comment]
I'd be happy to, with a little guidance. I believe should be looking [here](https://github.com/webpack/webpack/blob/ebe2f371c1a9ed303dd30f0c1ee51cd51718e4bd/lib/JsonpMainTemplatePlugin.js#L29). Is that correct?

**Comment by mAAdhaTTah** [comment]
I hate to say it, but I'm still experiencing this. I cannot for the life of me figure out why...

**Comment by mAAdhaTTah** [comment]
I'll mention I'm using the core-js promise polyfill. Don't know if that's related.

**Comment by MethodenMann** [comment]
I experience a similar behavior with IE10 and Webpack 3.3.0. I use babel-polyfill but tried two other and it also doenst work. Anybody an idea what to do?

**Comment by mAAdhaTTah** [comment]
@MethodenMann we switched to [es6-promise](https://github.com/stefanpenner/es6-promise/) and that seemed to resolve the issue, at least until we can drop IE10 support completely.

**Comment by MethodenMann** [comment]
@mAAdhaTTah and how did you integrate it? I tried to just load the dist/es6-promise.auto.js file and to load it directly with webpack:   

> new webpack.ProvidePlugin({
>     Promise: 'es6-promise-promise'
>   })
> ]

both approaches dont work for me.

**Comment by mAAdhaTTah** [comment]
`import 'es6-promise/auto'` at the top of our entry file.
