### ISSUE TITLE
Webpack seems to want to resolve devDependencies of modules in node_modules when target is "node"

### ISSUE THREAD

**Issue by rossipedia** [webpack/webpack#4474]
**Do you want to request a *feature* or report a *bug*?** _Bug_

**What is the current behavior?** _When attempting to bundle a module from `node_modules`, webpack attempts to resolve the modules listed in that packages `devDependencies`, and since `devDependencies` aren't included when installing a package, the resolution fails_

**If the current behavior is a bug, please provide the steps to reproduce.**

https://gist.github.com/rossipedia/69d434e281cd466a06fbd826d2aa5774

**What is the expected behavior?**

The module and it's runtime dependencies are included in the bundle, but not the devDependencies

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Windows 10
NodeJS v7.7.2
Webpack v2.2.1
Less v2.7.2

**Comment by timse** [comment]
What exactly are you expecting? I dont fully understand I think.
If your bundle needs devDependencies they are no devDependencies?

**Comment by TrySound** [comment]
@rossipedia Node doesn't care where dependency is declared. It looks into node_modules folder. Dependency even can be declared nowhere. Webpack behaves in the same way. Adding restrictions will affect for example test cases which use devDependencies and won't be run on install. It's all developer responsibility.

**Comment by sokra** [comment]
webpack doesn't read `devDependencies` nor `dependencies`. If you don't install your dependencies it doesn't work. Just like node.js.

**Comment by rossipedia** [comment]
That was my understanding as well, but it doesn't explain the behavior. Webpack is failing with an error because a package that is _only_ listed in less's `devDependencies` can't be found.

**Comment by rossipedia** [comment]
This message in particular would lead me to believe some parsing of `package.json` is going on:

```
resolve 'time-grunt' in 'C:\code\scratch\node_modules\less'
  Parsed request is a module
  using description file: C:\code\scratch\node_modules\less\package.json (relative path: .)
  after using description file: C:\code\scratch\node_modules\less\package.json (relative path: .)
    resolve as module
```
