### ISSUE TITLE
IgnorePlugin tries to use .test on array

### ISSUE THREAD

**Issue by danielverejan** [webpack/webpack#4476]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Based on the [documentation](https://webpack.js.org/configuration/plugins/), this is how you use ignore plugin: 
```javascript
new webpack.IgnorePlugin(/^\.\/locale$/, [/moment$/]),
```

however IgnorePlugin is using `.test` method on the second parameter, which is an array in this case and results into an error.

Is the documentation outdated or a plugin issue?

Using latest webpack and node.

**Comment by bebraw** [comment]
Both should be RegExp based on the source. Please [open an issue](https://github.com/webpack/webpack.js.org/issues) there or PR a fix through the web ui (even better). 👍
