### ISSUE TITLE
Very poor build performance when re-exporting a large number of exports

### ISSUE THREAD

**Issue by afarnsworth-valve** [webpack/webpack#4478]
**Do you want to request a *feature* or report a *bug*?**
feature request

**What is the current behavior?**

We are seeing very slow build times when re-exporting a large number of exports from another module.    

In our case, we had a file with about 1500 constants that were re-exported in another file.  This seems to have been adding over 12 seconds to every build, with that time spent in FlagDependencyExportsPlugin.  A node profile shows all the time is spent here, which is doing n^2 iteration on exported members (note the `a` array grows with each iteration):
https://github.com/webpack/webpack/blob/master/lib/FlagDependencyExportsPlugin.js#L91

```javascript
			function addToSet(a, b) {
				let changed = false;
				b.forEach((item) => {
					if(a.indexOf(item) < 0) {
						a.push(item);
						changed = true;
					}
				});
				return changed;
			}

```

**If the current behavior is a bug, please provide the steps to reproduce.**

gist here:
https://gist.github.com/afarnsworth-valve/523ec376f7557623891cf30539de54cb

constants.js
```javascript
export * from './constants_shared';

export const constant_01 = 1;
export const constant_02 = 2;
// etc
```

constants_shared.js
```javascript
export const sharedconstant_0001 = 1;
export const sharedconstant_0002 = 2;
export const sharedconstant_0003 = 3;
export const sharedconstant_0004 = 4;
// etc x 2000
```

index.js
```javascript
import * as constants from './constants';

console.log( constants.constant_01 );
console.log( constants.sharedconstant_0001 );
```

On my machine this takes nearly 2 minutes to build:

> S:\test\webpack_perf>node_modules\.bin\webpack --entry .\index.js --output-filename dist.js
> Hash: e0abeb50ecf078b8cfcc
> Version: webpack 2.2.1
> Time: **118152ms**
>   Asset    Size  Chunks             Chunk Names
> dist.js  170 kB       0  [emitted]  null
>    [0] ./constants.js 648 bytes {0} [built]
>    [1] ./constants_shared.js 80.9 kB {0} [built]
>    [2] ./index.js 131 bytes {0} [built]

Removing the re-export drops build time to less than a second:

> S:\test\webpack_perf>node_modules\.bin\webpack --entry .\norex_index.js --output-filename norex_dist.js
> Hash: 5be774eb4320c9bb5e10
> Version: webpack 2.2.1
> Time: **837ms**
>          Asset    Size  Chunks             Chunk Names
> norex_dist.js  170 kB       0  [emitted]  null
>     [0] ./constants_shared.js 80.9 kB {0} [built]
>     [1] ./norex_constants.js 631 bytes {0} [built]
>     [2] ./norex_index.js 199 bytes {0} [built]

 

**What is the expected behavior?**

Build time shouldn't be so heavily impacted.

**If this is a feature request, what is motivation or use case for changing the behavior?**

While this is easy to work around, discovering the root cause is not easy.  There's nothing to suggest that Webpack would struggle with re-exporting.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Node v6.9.4
Webpack 2.2.1
Windows 10

**Comment by timse** [comment]
thanks for the investigation, ill take a look

**Comment by timse** [comment]
the linked PR reduces the time on my local machine from ~85 secs to ~3 secs.

I guess there are more improvement possible, but not without a complete refactor of several parts.
(also the code is not the nicest but it does solve the issue for now)
