### ISSUE TITLE
Resolve NODE_PATH by default

### ISSUE THREAD

**Issue by ch2ch3** [webpack/webpack#4479]
**Do you want to request a *feature* or report a *bug*?**

Request a feature.

**What is the current behavior?**

~**If the current behavior is a bug, please provide the steps to reproduce.**~

Paths defined in the `NODE_PATH` environment variable are ignored unless manually added in the webpack config under `resolve.modules`.

I made a quick [demo](https://github.com/ch2ch3/node-path-demo) with 3 scripts in the [package.json](https://github.com/ch2ch3/node-path-demo/blob/master/package.json#L5-L7). All of these scripts will have to parse a `require('lib/foo')` statement.

`npm run compile:browserify`: ✅
`npm run compile:webpack`: ❌ errors out, unable to resolve `'lib/foo'`
`npm test`: ✅

**What is the expected behavior?**

By default, webpack should resolve `node_modules` as well as directories in `NODE_PATH`.

**If this is a feature request, what is motivation or use case for changing the behavior?**

* Node supports this ([1](https://nodejs.org/api/cli.html#cli_node_path_path), [2](https://nodejs.org/api/modules.html#modules_loading_from_the_global_folders))
* Other major libraries like browserify and mocha resolve NODE_PATH by default (see [demo repo](https://github.com/ch2ch3/node-path-demo))

This feature was also added to create-react-app (see [discussion](https://github.com/facebookincubator/create-react-app/issues/253), [implementation](https://github.com/facebookincubator/create-react-app/blob/fe7b5c212b5127775287ce444947f4c604c024dd/packages/react-scripts/config/paths.js#L24-L43)) pretty recently. However, that solution only passes `NODE_PATH` to the [generated webpack config](https://github.com/facebookincubator/create-react-app/blob/fe7b5c212b5127775287ce444947f4c604c024dd/packages/react-scripts/config/webpack.config.dev.js#L82-L87). I'd like this to be webpack's default behaviour :)

I've seen a few issues where adding NODE_PATH to `resolve.root` (webpack v1) was suggested as a solution, but haven't come across any discussion about whether this should be supported by default. Apologies if I've missed it, I'd be keen to know if this has been considered before!

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Node v7.4.0
Webpack v2.2.1
macOS Sierra 10.12.3

**Comment by timse** [comment]
thanks for the detailed description :)!

**Comment by sokra** [comment]
NODE_PATH should not be used. Even the node.js documentation discourage usage: https://nodejs.org/api/modules.html#modules_loading_from_the_global_folders

This is omitted by intend.

**Comment by ch2ch3** [comment]
Hey @sokra, from my reading of that documentation it sounds like what they are discouraging is installing dependencies in non-standard locations, and not usage of NODE_PATH.

I followed the discussion from https://github.com/nodejs/node/issues/1627 which states that NODE_PATH will not be deprecated, even though usage is discouraged.

Anyway, I'm happy to work around this in my own code.

**Comment by fritx** [comment]
How can I force node_modules to be a specific path? like

```js
// webpack 2.4.1
{
  resolve: {
    extensions: ['.js', '.vue'],
    modules: [
      // 'node_modules',
      path.resolve(__dirname, '../node_modules')
    ]
  }
}
```

I was bundling an entry outside of the pwd like `pwd/../../src/`, and it keeps printing errors:

```plain
ERROR in /Users/ddd/w/uigen/src/components/ui-form/ui-form.vue
Module not found: Error: Can't resolve 'vue-style-loader' in '/Users/ddd/w/uigen/src/components/ui-form'
 @ /Users/ddd/w/uigen/src/components/ui-form/ui-form.vue 4:2-412
 @ /Users/ddd/w/uigen/src/components/ui-form/index.js
 @ /Users/ddd/w/uigen/docs/bootstrap.js
 @ ./app/main.js
 @ multi webpack-hot-middleware/client?path=/__webpack_hmr&noInfo=true&reload=true ./app/main.js
```

but those modules were in `pwd/node_modules`

**Comment by fritx** [comment]
Just found out and tried `resolveloader` and it works!
https://webpack.js.org/configuration/resolve/#resolveloader

```js
{
  resolveLoader: {
    modules: [
      // 'node_modules',
      path.resolve(__dirname, '../node_modules')
    ]
  }
}
```
