### ISSUE TITLE
Suggestion: use eslint to upgrade vars to es6

### ISSUE THREAD

**Issue by lukeapage** [webpack/webpack#4481]
I see alot of prs to upgrade to es6. Some noise might be reduced if you set eslint to require let and const, then allow eslint to auto fix the errors..

**Comment by lukeapage** [comment]
Feel free to close or disregard, this is a process suggestion, not a webpack issue

**Comment by bebraw** [comment]
No probs.

We set up [defaults for the contrib projects](https://github.com/webpack-contrib/webpack-defaults). If you have time, give it a go and let us know what you think. 👍

**Comment by tarang9211** [comment]
@bebraw is this still up for grabs?

**Comment by bebraw** [comment]
@tarang9211 I'm not sure. Just checking. I hope Tobias comments. 👍

**Comment by tarang9211** [comment]
@bebraw @sokra Sounds good. Looking forward to fixing this.
