### ISSUE TITLE
Move CLI tests to the webpack CLI repository 

### ISSUE THREAD

**Issue by ev1stensberg** [webpack/webpack#4489]
**Do you want to request a *feature* or report a *bug*?**
Improvements 

**What is the current behavior?**
CLI tests are under this folder(?)
**If the current behavior is a bug, please provide the steps to reproduce.**
Not applicable 

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**
I think we should move any test touching the CLI to the CLI repository, considering there indeed are tests for the current CLI in this repository. Thoughts?
**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by TheLarkInn** [comment]
That would be binCases, and BinTestCases.js

**Comment by ev1stensberg** [comment]
How do you feel about this?
