### ISSUE TITLE
Infinite Loop

### ISSUE THREAD

**Issue by KpjComp** [webpack/webpack#4490]
**Do you want to request a *feature* or report a *bug*?**  

Bug

**What is the current behavior?**   

Infinite Loop

**If the current behavior is a bug, please provide the steps to reproduce.**

On windows if you use a full path for the output.filename by accident, eg:  D:\output\ouput.js  webpack will go into a infinite loop inside mkdirp.  The solution is of course to use output.path, & output.filename together.  putting filename only in Webpack 1 worked Ok though.

**What is the expected behavior?**

Either detect the filename is a fullpath filename and automatically split into path & filename, or throw an Error..  Because no error is thrown it took a while for me to find this simple mistake.

**Comment by sokra** [comment]
> Either detect the filename is a fullpath filename

This happens on master branch, not yet released
