### ISSUE TITLE
Source maps were not generated if sourceMapFilename contains chunkhash

### ISSUE THREAD

**Issue by zhaoyao91** [webpack/webpack#4492]
**Do you want to request a *feature* or report a *bug*?**
May be a bug.

**What is the current behavior?**
The console reported that source maps were generated, but I can't find them.
![image](https://cloud.githubusercontent.com/assets/3808838/23962716/fb2289c2-09e9-11e7-9d6a-f8a68cdc97d9.png)
![image](https://cloud.githubusercontent.com/assets/3808838/23962730/045aabfa-09ea-11e7-9b07-e29bbd973d6a.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
- clone this [repo](https://github.com/zhaoyao91/docit/tree/show-source-map-problem), 
- run `npm run build`
- then check the output files

**What is the expected behavior?**
Source maps have been generated after building.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
- OS: windows 10 64bit Family Edition
Something interesting is, if I change sourceMapFilename to `[name].map`, then it works. Seems that if the sourceMapFileName contains chunkhash, then it output nothing.

**Comment by jhnns** [comment]
Notice the gray triangle besides the files? Open it and you'll see the source maps 😁 
This is a WebStorm feature...

**Comment by zhaoyao91** [comment]
@jhnns thanks
