### ISSUE TITLE
Parallellism should be avoided/limited during profiling

### ISSUE THREAD

**Issue by dtinth** [webpack/webpack#4494]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

When running `webpack --profile`, the profiled data also includes the time it takes webpack to build other unrelated modules.

**If the current behavior is a bug, please provide the steps to reproduce.**

On any webpack project, run `webpack --profile --json > output.json`.

**What is the expected behavior?**

The profiled data for each module should only contain the CPU time (and IO time) that webpack uses to build that module (and that module only).

**If this is a feature request, what is motivation or use case for changing the behavior?**

On our project (a React app), running webpack is a CPU bound task. While webpack is running, CPU usage is 100% most of the time.

I am trying to profile the build process to see which module takes the most time to build, so that we can find ways to speed it up.

- Running webpack will build __3,526 modules__.
- Looking at `stats.modules[*].profile.building`, the average time to build each module is 1.6 seconds. Summing them up the result is 99 minutes. 
- Actual build time is 2.5 minutes, that means the profile data also included the time webpack is busy building other modules as well.
- By recording the timestamp when webpack starts and finishes building a module, it appears that __webpack tries to build 338 modules simulateneously__ when only a single core is available to Node.js.

I suspect that this is the reason that the profiled build time inflated from 2.5 minutes to 99 minutes. To verify this, I modified `async.forEach` to only run a single iteratee at a time:

```js
async.forEach = (coll, iteratee, callback) => {
	async.forEachLimit(coll, 1, iteratee, callback);
};
```

- Looking at `stats.modules[*].profile.building`, the average time to build each module reduced to 12 milliseconds. Summing them up the result is 43 seconds, which is reasonable.
- From the numbers, 50% of the build time comes from __1.5%__ of the modules (54 modules are responsible for half of the build time). It was 20% (720 modules) before this change.
- This means the profiled build time inflated __139 times__ as a result of webpack trying to build hundreds of modules at the same time.

Seeing such a drastic change in the result, I’m not sure whether this should be the way it should be.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

webpack 2.2.1
Mac OS X

**Comment by jhnns** [comment]
I understand your use-case, but if you want true CPU time for each module, you'd need to instrument the all the code like code coverage tools do it. I haven't done this so far but I think it could get complicated...

**Comment by dtinth** [comment]
Yeah, that would be very complicated. That’s why I suggest limiting the concurrency instead :)

**Comment by sokra** [comment]
Yes it's a valid issue I also noticed. I also suggest limiting concurrency as solution.

**Comment by eddywashere** [comment]
Is it possible to limit the concurrency? This would be extremely useful for machines with limited resources. I found a similar approach in [Jest](https://facebook.github.io/jest/docs/en/cli.html#runinband) that helped out with the test side of things.

**Comment by sokra** [comment]
Yep there is a `parallism` option now

**Comment by dtinth** [comment]
Thanks! For reference, here is the relevant commit.

https://github.com/webpack/webpack/commit/f9bf8a9085a8e571bb37d9f746b2fdb1fe55ae50
