### ISSUE TITLE
source maps should use `node_modules` rather than `~`

### ISSUE THREAD

**Issue by nojvek** [webpack/webpack#4497]
**What is the current behavior?**

sourcemap sources emitted by webpack have tilda character `~` which corresponds to `node_modules`

```
{
version: 3,
sources: [
"webpack:///webpack/bootstrap 6898e6484b977a8688ff",
"webpack:///(webpack)-dev-server/client",
"webpack:///(webpack)-dev-server/client?cd17",
"webpack:///./~/url/url.js",
"webpack:///./~/url/~/punycode/punycode.js",
```

should actually be

```
{
version: 3,
sources: [
"webpack:///webpack/bootstrap 6898e6484b977a8688ff",
"webpack:///(webpack)-dev-server/client",
"webpack:///(webpack)-dev-server/client?cd17",
"webpack:///./node_modules/url/url.js",
"webpack:///./node_modules/url/node_modules/punycode/punycode.js",
```

This breaks a whole bunch of tools such as chrome devtools and VSCode.

I believe the `~` notation is added to make output readable but it should not be outputted in sourcemaps since its not part of the sourcemap standard.

Happy to submit a PR if someone can guide me.

**Comment by sokra** [comment]
see https://github.com/webpack/webpack/pull/4144

**Comment by dgoldstein0** [comment]
so this is resolved on master then?

**Comment by sokra** [comment]
fixed on next branch
