### ISSUE TITLE
[RFC]: Move to Jest as test runner/library?

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack#4499]
After discussing with @cpojer in the past and [learning more about Jest and its snapshotting capability](https://youtu.be/HAuXJVI_bUs?t=9m28s), I believe that we could simplify a huge amount of test infra that we currently have in place by moving from Mocha to Jest:

### Benefits:

* Simplify a huge amount of boilerplate logic: Currently we have hand written code for collecting stats output and then custom asserting vs expected value in our statsCases, RuleSet.test, binCases. This would be perfect for jests `toMatchSnapshot()` functionality. When any of this changes unexpectedly, the snapshots fail. If it does fail and we expect it to because of updated apis, we only need one command (similar to `./test/statsCases/accept-stats.js`) to update snapshots.

* Speed: Jest leverages worker threads to help speed up the time it takes for tests to run. Our complete suite can take quite a few minutes to finish (and although thats not that much), we could see a considerable decrease by switching. 

### Challenges: 

* `expect()` is the default assertion library and although we could use chai, etc. expect is quite nice , but does propose some work involved to manually switching this over. 

* Might need to make some eslint configurations to handle jest globals

* Some code formatting incompatibilities: A statement like the one seen below is technically an error in jest because jest either expects the return statement to either be false or a promise. In this case the inline arrow function style is evaluated as an inline implicit return:

```js
it("binds one event handler", () => eventBindings.length.should.be.exactly(1));
```

Simply enough we could just wrap these in `{}` and that would solve the error (tested this locally). 

@colevoss a good friend of mine has offered to help make this migration possible if it is something that we, as a @webpack/core-team can agree on, and I think could make a significant impact on our CI/CD times and local dev time as well. I'm sure there are a few more people that even @cpojer could throw our way to assist if this is a direction we should choose. //CC @alistairjcbrown @rogeliog

**Comment by cpojer** [comment]
* To migrate: https://github.com/skovhus/jest-codemods
* Use `eslint-plugin-jest`

Shouldn't be that hard with those tools :)

**Comment by TheLarkInn** [comment]
@cpojer Have already attempted. 

`it("binds one event handler", () => eventBindings.length.should.be.exactly(1));` caused failures for `it/test` and then the use of `.should()` and `this.timeout(x)` was the other one I believe.

**Comment by cpojer** [comment]
Here is an example codemod for that: http://astexplorer.net/#/gist/4836dd31ff329080b8d2a4bdfea19f3b/47851513ee1ccd7c171e0053d13e7a3e7f1992e4

**Comment by TheLarkInn** [comment]
@cpojer You may want to see how we use ConfigCases.test.js for a better idea of how we might handle this in jest if there was a way.

**Comment by colevoss** [comment]
@cpojer @TheLarkInn After looking into the test configuration in this repo, it seems to be a very unique test suite. There is really cool stuff in there but I have a feeling it might hinder use of codemods. If it can be done though, that would be rad.

**Comment by d3viant0ne** [comment]
@TheLarkInn - One thing to add to the benefits list, the development experience is better than anything else available by a huge margin. Between the dev time nirvana, speed & the door that snapshot testing opens up this should happen regardless of the grunt work needed to make it happen.

We have met with limited success using code-mods in the contrib conversions for pretty much the same reason, unique test scenarios though on a different scale than core.

If you need more hands on deck for the grunt work, contrib team has a fair bit of experience converting webpacky things to leverage Jest.

**Comment by zacck** [comment]
If it's agreed upon that the tests need to move to jest I would like to take this one.

**Comment by dhruvdutt** [comment]
Any update on this?

**Comment by dhruvdutt** [comment]
@webpack-bot #5673 :smile: :robot:

**Comment by ooflorent** [comment]
Done \o/
