### ISSUE TITLE
How to read the value of propTypes of my Button component

### ISSUE THREAD

**Issue by kopax** [webpack/webpack#4508]
I need a function that would return the `propTypes` and the `defaultProps` of any React Component in order to display a table like this:

![image](https://cloud.githubusercontent.com/assets/1866564/24073899/99b42746-0c31-11e7-9590-9181e59c523c.png)

I have created the following function to read the `propTypes` and `defaultProps`

    function getInfo(component) {
      console.log('propTypes', component.propTypes)
      console.log('defaultProps', component.defaultProps)
    }

Reproduction
------------

https://www.webpackbin.com/bins/-KfXIWlTGcgSo-GeNAFR

Expected && Result
-----------------

To log the propTypes and defaultProps

How about in webpack 2?
======================

I am trying to reproduce the same thing with components that look like this:    

    export class Button extends React.Component {
      static propTypes = {
        data: PropTypes.object.isRequired,
        onSubmitFormLogin: PropTypes.func.isRequired,
        changeForm: PropTypes.func.isRequired,
        requestError: PropTypes.func.isRequired,
      };
    
      static defaultProps = {
        data: {}
      };
    ...
    }

In order for this to work, you need to use the `static` __keyword__

According to [babel](https://babeljs.io/repl/#?babili=false&evaluate=false&lineWrap=true&presets=es2015%2Creact%2Cstage-0&targets=&browsers=&builtIns=false&code=%20%20class%20Foo%20%7B%0A%20%20%20%20static%20propTypes%20%3D%20%7B%0A%20%20%20%20%20%20data%3A%20%7B%7D%0A%20%20%20%20%7D%3B%0A%20%20%20%20%0A%20%20%20%20static%20defaultProps%20%3D%20%7B%0A%20%20%20%20%20%20data%3A%20%7B%20firstname%3A%20'dka'%20%7D%0A%20%20%20%20%7D%3B%0A%20%20%7D%0A%0A%0Afunction%20getInfo(component)%20%7B%0A%20%20console.log('propTypes'%2C%20component.propTypes)%0A%20%20console.log('defaultProps'%2C%20component.defaultProps)%0A%7D%0AgetInfo(Foo)%0A), It should be the exact same thing, but for some reason, I cannot read the `propTypes` but only the `defaultProps` so where do they go ? 

Is it Webpack/Babel that does remove them ?

Did anyone succeed to read is `propTypes` using this syntax ?

**Comment by sokra** [comment]
Seem to work fine
