### ISSUE TITLE
Invalid character (Â) in bundle

### ISSUE THREAD

**Issue by ibrahimduran** [webpack/webpack#4510]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Webpack produces a invalid character (Â) in bundle file.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Install `nedb` package
2. Run webpack
3. Search for `if (doc[i] !== undefined && util.isDate(doc[i]) &&` in bundled file (or go to line number 18410).

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Windows 10, Node v7.7.1, Webpack 2.2.1, nedb 1.8.0

**Comment by zastavnitskiy** [comment]
Doesn't seem to be reproducible on OSX, node 6.9.1:
```
        if (doc[i] !== undefined && util.isDate(doc[i]) && Date.now() > doc[i].getTime() + self.ttlIndexes[i] * 1000) {
          valid = false;
        }
```

**Comment by ibrahimduran** [comment]
@zastavnitskiy Make sure to check in different text viewers. For example it's not visible in VSCode but I can see it in Chrome and Chrome's inspector.

**Comment by uncleyo** [comment]
Not sure if it's the same issue, but I experienced something similar when bundling TinyMCE. I wrote about the fix here: https://www.tinymce.com/docs/advanced/usage-with-module-loaders/#minificationwithuglifyjs2.

**Comment by jhnns** [comment]
@ibrahimduran could you create a test repository that makes the issue reproducible?

**Comment by ibrahimduran** [comment]
@jhnns https://github.com/ibrahimduran/webpack-html-encoding-issue - run webpack and open test.html, you should see parse error in the console

I've just found out that it works without any parse error when I set charset encoding to UTF-8 in HTML file.

**Comment by sokra** [comment]
webpack emits utf-8 javascript (and read utf-8 javascript). Correct encoding is important.

**Comment by timse** [comment]
I assume this can be closed then. 
Feel free to reopen if this remains an issue.

**Comment by damianobarbati** [comment]
Getting the same even with correct html encoding, but just if I minify with babili

```
SyntaxError: Invalid character '\u2160'
```

```
  Licensed under the MIT License (MIT), see
  http://jedwatson.github.io/classnames
*/ <=== js console report this here

```

**Comment by gerardmrk** [comment]
Getting the same error here. `Invalid character '\u2160'`
```
var $jscomp = $jscomp || {};
```

**Comment by Akdez** [comment]
Got this error when tried to bundle ThreeJS. 

Found this character in one of the lines:
`this.aStartAngle = aStartAngle ||Â 0;`

**Comment by wbobeirne** [comment]
I'm also encountering this error in a babel minified build, and not on the dev build. I'm inclined to believe this isn't a webpack issue, but something in one of the minifiers in babel minify.

**Comment by wbobeirne** [comment]
Pardon my previous comment, I was on the right track but was mistaken by a little bit of Javascript caching that led me to the wrong conclusion.

After some extensive narrowing down, I've discovered that it's a combination of babel-minify-webpack-plugin's `evaluate` and `propertyLiterals` minifiers, on [the following lodash file](https://github.com/lodash/lodash/blob/6cb3460fcefe66cb96e55b82c6febd2153c992cc/.internal/deburrLetter.js#L6) (At least in my case. I'm sure some folks issues will be different.) The property key `'\xc2': 'A'` was getting turned into `Â: 'A'`, which was causing Safari to crap out.

**Comment by sibelius** [comment]
what is the proper fix ?
