### ISSUE TITLE
Commonjs wrapped local modules are not resolved.

### ISSUE THREAD

**Issue by zastavnitskiy** [webpack/webpack#4511]
**What is the current behavior?**
We have a module with no return value wrapped with simplified common js wrapper:
```
define('test', function(require, exports, module){
  exports = 'hello';
});
require('test');
```
Once transpiled by webpack with default settings, the resulting module definition looks like this(`call` returns `undefined`):
```
__WEBPACK_LOCAL_MODULE_0__ = function(require, exports, module){
  exports = 'hello';
}.call(exports, __webpack_require__, exports, module)
```
and _local_ require gets transpiled into`__WEBPACK_LOCAL_MODULE_0__`, which is undefined.

**What is the expected behavior?**
local require calls transpiled into `__webpack_require__(0)` function call, so that the module will be resolved.

**Gist with more details and build output**
https://gist.github.com/zastavnitskiy/a4c8bf691d55ba9f53e7183ad0aabb48
Building with this command: `webpack external.js build.js`
Applies to both webpack 1 and 2.

**Comment by sokra** [comment]
Yeah, it's a bug.

**Comment by zastavnitskiy** [comment]
Here is a fix, please review: https://github.com/webpack/webpack/pull/4529

**Comment by maciej-gurban** [comment]
Possibly related?
https://github.com/webpack/webpack/issues/4894
