### ISSUE TITLE
Failed at the myPROJECT build script 'cross-env NODE_ENV=production webpack -p --colors'.

### ISSUE THREAD

**Issue by secretgspot** [webpack/webpack#4512]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by bebraw** [comment]
Can you re-open with the fields filled?
