### ISSUE TITLE
Failed at the myPROJECT build script 'cross-env NODE_ENV=production webpack -p --colors'.

### ISSUE THREAD

**Issue by secretgspot** [webpack/webpack#4514]
**Do you want to request a *feature* or report a *bug*?**

BUG

**What is the current behavior?**

FAILS WHEN TRYING TO RUN NPM RUN BUILD

**If the current behavior is a bug, please provide the steps to reproduce.**

to reproduce npm run build

**What is the expected behavior?**

compiled and minimized 

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

win10, powershell, latest npm and node and have no issue running npm start to develop

PS S:\PROJECTS\WEB\WEBPACK2\atangualr> npm run build

> sjoPintor@0.1.0 build S:\PROJECTS\WEB\WEBPACK2\atangualr
> cross-env NODE_ENV=production webpack -p --colors

Current Environment:  production
fallbackLoader option has been deprecated - replace with "fallback"
loader option has been deprecated - replace with "use"
clean-webpack-plugin: S:\PROJECTS\WEB\WEBPACK2\atangualr\dist has been removed.
(node:12420) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see http
s://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.

Child extract-text-webpack-plugin:
        + 1 hidden modules

    ERROR in ./~/css-loader?root=S:/PROJECTS/WEB/WEBPACK2/atangualr/src&sourceMap!./~/postcss-loader!./~/sass-loader?out
putStyle=expanded&sourceMap=true&sourceMapContents=true!./src/assets/styles/sass/index.scss
    Module build failed: Error: Cannot find module 'S:\PROJECTS\WEB\WEBPACK2\atangualr\node_modules\css-loader\index.js?
root=S:\PROJECTS\WEB\WEBPACK2\atangualr\src&sourceMap'
        at Function.Module._resolveFilename (module.js:470:15)
        at Function.Module._load (module.js:418:25)
        at Module.require (module.js:498:17)
        at require (internal/module.js:20:19)
        at loadLoader (S:\PROJECTS\WEB\WEBPACK2\atangualr\node_modules\loader-runner\lib\loadLoader.js:13:17)
        at iteratePitchingLoaders (S:\PROJECTS\WEB\WEBPACK2\atangualr\node_modules\loader-runner\lib\LoaderRunner.js:169
:2)
        at runLoaders (S:\PROJECTS\WEB\WEBPACK2\atangualr\node_modules\loader-runner\lib\LoaderRunner.js:362:2)
        at NormalModule.doBuild (S:\PROJECTS\WEB\WEBPACK2\atangualr\node_modules\webpack\lib\NormalModule.js:131:2)
        at NormalModule.build (S:\PROJECTS\WEB\WEBPACK2\atangualr\node_modules\webpack\lib\NormalModule.js:179:15)
        at Compilation.buildModule (S:\PROJECTS\WEB\WEBPACK2\atangualr\node_modules\webpack\lib\Compilation.js:127:9)
        at Compilation.<anonymous> (S:\PROJECTS\WEB\WEBPACK2\atangualr\node_modules\webpack\lib\Compilation.js:404:8)
        at S:\PROJECTS\WEB\WEBPACK2\atangualr\node_modules\webpack\lib\NormalModuleFactory.js:74:13
        at NormalModuleFactory.applyPluginsAsyncWaterfall (S:\PROJECTS\WEB\WEBPACK2\atangualr\node_modules\tapable\lib\T
apable.js:196:70)
        at onDoneResolving (S:\PROJECTS\WEB\WEBPACK2\atangualr\node_modules\webpack\lib\NormalModuleFactory.js:49:11)
        at onDoneResolving (S:\PROJECTS\WEB\WEBPACK2\atangualr\node_modules\webpack\lib\NormalModuleFactory.js:165:6)
        at S:\PROJECTS\WEB\WEBPACK2\atangualr\node_modules\webpack\lib\NormalModuleFactory.js:161:6
        at S:\PROJECTS\WEB\WEBPACK2\atangualr\node_modules\async\lib\async.js:726:13
        at S:\PROJECTS\WEB\WEBPACK2\atangualr\node_modules\async\lib\async.js:52:16
        at async.forEachOf.async.eachOf (S:\PROJECTS\WEB\WEBPACK2\atangualr\node_modules\async\lib\async.js:236:30)
        at _parallel (S:\PROJECTS\WEB\WEBPACK2\atangualr\node_modules\async\lib\async.js:717:9)
        at Object.async.parallel (S:\PROJECTS\WEB\WEBPACK2\atangualr\node_modules\async\lib\async.js:731:9)
        at S:\PROJECTS\WEB\WEBPACK2\atangualr\node_modules\webpack\lib\NormalModuleFactory.js:154:11
        at S:\PROJECTS\WEB\WEBPACK2\atangualr\node_modules\async\lib\async.js:726:13
        at S:\PROJECTS\WEB\WEBPACK2\atangualr\node_modules\async\lib\async.js:52:16
        at async.forEachOf.async.eachOf (S:\PROJECTS\WEB\WEBPACK2\atangualr\node_modules\async\lib\async.js:236:30)
        at _parallel (S:\PROJECTS\WEB\WEBPACK2\atangualr\node_modules\async\lib\async.js:717:9)
        at Object.async.parallel (S:\PROJECTS\WEB\WEBPACK2\atangualr\node_modules\async\lib\async.js:731:9)
        at S:\PROJECTS\WEB\WEBPACK2\atangualr\node_modules\webpack\lib\NormalModuleFactory.js:104:10
        at S:\PROJECTS\WEB\WEBPACK2\atangualr\node_modules\webpack\lib\NormalModuleFactory.js:39:4
        at handleExternal (S:\PROJECTS\WEB\WEBPACK2\atangualr\node_modules\webpack\lib\ExternalModuleFactoryPlugin.js:25
:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! sjoPintor@0.1.0 build: `cross-env NODE_ENV=production webpack -p --colors`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the sjoPintor@0.1.0 build script 'cross-env NODE_ENV=production webpack -p --colors'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sjoPintor package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=production webpack -p --colors
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sjoPintor
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sjoPintor
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\HookerKuzya\AppData\Roaming\npm-cache\_logs\2017-03-19T04_25_42_090Z-debug.log

**Comment by secretgspot** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'E:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\HookerKuzya\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@4.4.1
3 info using node@v7.7.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle sjoPintor@0.1.0~prebuild: sjoPintor@0.1.0
6 silly lifecycle sjoPintor@0.1.0~prebuild: no script for prebuild, continuing
7 info lifecycle sjoPintor@0.1.0~build: sjoPintor@0.1.0
8 verbose lifecycle sjoPintor@0.1.0~build: unsafe-perm in lifecycle true
9 verbose lifecycle sjoPintor@0.1.0~build: PATH: C:\Users\HookerKuzya\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;S:\PROJECTS\WEB\WEBPACK2\atangualr\node_modules\.bin;D:\PORTABLES\PYTHON\Scripts\;D:\PORTABLES\PYTHON\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\ImageMagick-6.9.2-Q16;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;u:\android;E:\Program Files\ATI Technologies\ATI.ACE\Core-Static;E:\Program Files (x86)\Java\bin;U:\processing;C:\Program Files (x86)\AMD\ATI.ACE\Core-Static;C:\mongodb\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;E:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcpackages;C:\Program Files (x86)\GtkSharp\2.12\bin;e:\Program Files\Git\cmd;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\Yarn\bin;E:\Program Files\nodejs\;e:\Program Files (x86)\Git\bin;e:\Program Files (x86)\Git\cmd;C:\Users\HookerKuzya\AppData\Local\Microsoft\WindowsApps;D:\PORTABLES\CMDER;C:\Users\HookerKuzya\AppData\Local\Yarn\.bin;C:\Users\HookerKuzya\AppData\Roaming\npm
10 verbose lifecycle sjoPintor@0.1.0~build: CWD: S:\PROJECTS\WEB\WEBPACK2\atangualr
11 silly lifecycle sjoPintor@0.1.0~build: Args: [ '/d /s /c',
11 silly lifecycle   'cross-env NODE_ENV=production webpack -p --colors' ]
12 silly lifecycle sjoPintor@0.1.0~build: Returned: code: 2  signal: null
13 info lifecycle sjoPintor@0.1.0~build: Failed to exec build script
14 verbose stack Error: sjoPintor@0.1.0 build: `cross-env NODE_ENV=production webpack -p --colors`
14 verbose stack Exit status 2
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\HookerKuzya\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\HookerKuzya\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid sjoPintor@0.1.0
16 verbose cwd S:\PROJECTS\WEB\WEBPACK2\atangualr
17 verbose Windows_NT 10.0.14393
18 verbose argv "E:\\Program Files\\nodejs\\node.exe" "C:\\Users\\HookerKuzya\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
19 verbose node v7.7.3
20 verbose npm  v4.4.1
21 error code ELIFECYCLE
22 error errno 2
23 error sjoPintor@0.1.0 build: `cross-env NODE_ENV=production webpack -p --colors`
23 error Exit status 2
24 error Failed at the sjoPintor@0.1.0 build script 'cross-env NODE_ENV=production webpack -p --colors'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the sjoPintor package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     cross-env NODE_ENV=production webpack -p --colors
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs sjoPintor
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls sjoPintor
24 error There is likely additional logging output above.
25 verbose exit [ 2, true ]

**Comment by timse** [comment]
could you stick to the issue template provided and give a reproducible example of whats happening? From what I see you seam to not have set it up correctly.
Closing for now.

**Comment by secretgspot** [comment]
to me instructions looks pretty clear and it appears you're dodging the issue!  try googling it and it's very common and goes few years back!   so, why don't you stop closing my bugs and answer the question as to why it is happening?!

**Comment by michael-ciniawsky** [comment]
@secretgspot wepack, `css-loader` `extract-text-webpack-plugin` versions + `webpack.config.js` please without it is very difficult to debug your issue, seems a config mismatch somwhere and you get a lot of deprecation warnings already. Also please wrap any code/errors/stacktraces in  markdown code blocks (3 backticks ```) ```..your code here``` for better readability

**Comment by secretgspot** [comment]
@michael-ciniawsky  thanks, I'll refile with missing info and proper format
