### ISSUE TITLE
Source map URLs shouldn't be prefixed with a local path

### ISSUE THREAD

**Issue by japgolly** [webpack/webpack#4518]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

Some libraries (i.e. nearly all created via [Scala.JS](http://www.scala-js.org/)) have URLs in their source maps. However when being used with webpack, webpack is prepending a `./` to all the URLs results in trillions of warnings like this:

```
[info] Cannot find source file 'https://raw.githubusercontent.com/scala/scala/v2.12.1/src/library/scala/collection/immutable/Vector.scala': Error: Can't resolve './https://raw.githubusercontent.com/scala/scala/v2.12.1/src/library/scala/collection/immutable/Vector.scala' in '/home/golly/projects/misc/target/scala-2.12/scalajs-bundler/main'
[info]  @ ./fastopt-launcher.js 1:0-91
[info] 
[info] WARNING in ./demo-fastopt.js
[info] Cannot find source file 'https://raw.githubusercontent.com/scala/scala/v2.12.1/src/library/scala/collection/immutable/List.scala': Error: Can't resolve './https://raw.githubusercontent.com/scala/scala/v2.12.1/src/library/scala/collection/immutable/List.scala' in '/home/golly/projects/misc/target/scala-2.12/scalajs-bundler/main'
[info]  @ ./fastopt-launcher.js 1:0-91
[info] 
[info] WARNING in ./demo-fastopt.js
[info] Cannot find source file 'https://raw.githubusercontent.com/scala/scala/v2.12.1/src/library/scala/collection/immutable/Stream.scala': Error: Can't resolve './https://raw.githubusercontent.com/scala/scala/v2.12.1/src/library/scala/collection/immutable/Stream.scala' in '/home/golly/projects/misc/target/scala-2.12/scalajs-bundler/main'
[info]  @ ./fastopt-launcher.js 1:0-91
[info] 
[info] WARNING in ./demo-fastopt.js
[info] Cannot find source file 'https://raw.githubusercontent.com/scala/scala/v2.12.1/src/library/scala/collection/immutable/StringOps.scala': Error: Can't resolve './https://raw.githubusercontent.com/scala/scala/v2.12.1/src/library/scala/collection/immutable/StringOps.scala' in '/home/golly/projects/misc/target/scala-2.12/scalajs-bundler/main'
[info]  @ ./fastopt-launcher.js 1:0-91
[info] 
[info] WARNING in ./demo-fastopt.js
[info] Cannot find source file 'https://raw.githubusercontent.com/scala/scala/v2.12.1/src/library/scala/collection/immutable/WrappedString.scala': Error: Can't resolve './https://raw.githubusercontent.com/scala/scala/v2.12.1/src/library/scala/collection/immutable/WrappedString.scala' in '/home/golly/projects/misc/target/scala-2.12/scalajs-bundler/main'
[info]  @ ./fastopt-launcher.js 1:0-91
```

And resulting in a final source map that no longer works for those libraries.

**If the current behavior is a bug, please provide the steps to reproduce.**

Setup any dummy project with [Scala.JS](http://www.scala-js.org/) and [scalajs-bundler](https://scalacenter.github.io/scalajs-bundler/getting-started.html) which runs everything through webpack.

**What is the expected behavior?**

Source map links that can be identified as absolute URLs should be used as is, without modification.

I believe the fix would be a very simple test like this before prepending:
https://github.com/jantimon/html-webpack-plugin/pull/619/files

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Using webpack 2.2.1, Node.JS 7.7.3.

**Comment by sokra** [comment]
I wonder where this message origin in `Cannot find source file ...`

Could you run it with `--display-error-details` (`errorDetails: true` in stats)?

**Comment by japgolly** [comment]
Hi @sokra, I tried with `errorDetails: true` and the output was the same as before. I set `stats: "verbose"` and still didn't get any additional, useful info (snippet below). I also set `stats: "none"` to confirm my settings we being detected and they were.

```
[info] WARNING in ./demo-fastopt.js
[info] Cannot find source file 'https://raw.githubusercontent.com/japgolly/scalajs-react/v1.0.0-RC1/core/src/main/scala/japgolly/scalajs/react/CtorType.scala': Error: Can't resolve './https://raw.githubusercontent.com/japgolly/scalajs-react/v1.0.0-RC1/core/src/main/scala/japgolly/scalajs/react/CtorType.scala' in '/home/golly/projects/misc/target/scala-2.12/scalajs-bundler/main'
[info]  @ ./fastopt-launcher.js 1:0-91
[info] 
[info] WARNING in ./demo-fastopt.js
[info] Cannot find source file 'https://raw.githubusercontent.com/japgolly/scalajs-react/v1.0.0-RC1/core/src/main/scala/japgolly/scalajs/react/Callback.scala': Error: Can't resolve './https://raw.githubusercontent.com/japgolly/scalajs-react/v1.0.0-RC1/core/src/main/scala/japgolly/scalajs/react/Callback.scala' in '/home/golly/projects/misc/target/scala-2.12/scalajs-bundler/main'
[info]  @ ./fastopt-launcher.js 1:0-91
[info] 
[info] WARNING in ./demo-fastopt.js
[info] Cannot find source file 'https://raw.githubusercontent.com/japgolly/scalajs-react/v1.0.0-RC1/core/src/main/scala/japgolly/scalajs/react/package.scala': Error: Can't resolve './https://raw.githubusercontent.com/japgolly/scalajs-react/v1.0.0-RC1/core/src/main/scala/japgolly/scalajs/react/package.scala' in '/home/golly/projects/misc/target/scala-2.12/scalajs-bundler/main'
[info]  @ ./fastopt-launcher.js 1:0-91
[info] 
[info] WARNING in ./demo-fastopt.js
[info] Cannot find source file 'https://raw.githubusercontent.com/japgolly/scalajs-react/v1.0.0-RC1/core/src/main/scala/japgolly/scalajs/react/component/ScalaBuilder.scala': Error: Can't resolve './https://raw.githubusercontent.com/japgolly/scalajs-react/v1.0.0-RC1/core/src/main/scala/japgolly/scalajs/react/component/ScalaBuilder.scala' in '/home/golly/projects/misc/target/scala-2.12/scalajs-bundler/main'
[info]  @ ./fastopt-launcher.js 1:0-91
[info] 
[info] WARNING in ./demo-fastopt.js
```

**Comment by japgolly** [comment]
`Cannot find source file` seems to be coming from here:
https://github.com/webpack-contrib/source-map-loader/blob/v0.2.0/index.js#L65

I'm not to worried about that though because it just seems to be wrapping the underlying error which is:
```
Error: Can't resolve './https://raw.githubusercontent.com/japgolly/scalajs-react/v1.0.0-RC1/core/src/main/scala/japgolly/scalajs/react/CtorType.scala' in '/home/golly/projects/misc/target/scala-2.12/scalajs-bundler/main'
```

I submitted a PR to loader-utils to stop the prefixing, that's where that was happening:
https://github.com/webpack/loader-utils/pull/79

Unfortunately I'm still getting the same errors, just the prefix has been correctly removed:
```
Error: Can't resolve 'https://raw.githubusercontent.com/japgolly/scalajs-react/v1.0.0-RC1/core/src/main/scala/japgolly/scalajs/react/internal/Semigroup.scala' in '/home/golly/projects/misc/target/scala-2.12/scalajs-bundler/main'
 @ ./target/scala-2.12/scalajs-bundler/main/fastopt-launcher.js 1:0-91
```

**Comment by jhnns** [comment]
Looks like [scalajs-bundler is using the source-map-loader](https://github.com/scalacenter/scalajs-bundler/search?utf8=%E2%9C%93&q=source-map-loader&type=). The source-map-loader uses webpack's resolver to resolve the source-map. webpack's resolver, however, cannot resolve remote resources via http and such.

So, why are they using the source-map-loader at all?

And: I'm also not sure if it's a good idea to point the `sourceMappingURL` to `raw.githubusercontent.com`...

**Comment by julienrf** [comment]
> So, why are they using the source-map-loader at all?

We use source-map-loader to preserve (as most as possible) source-map continuity across libraries.

**Comment by nartamonov** [comment]
Any update on this, guys?

**Comment by evilebottnawi** [comment]
@webpack-bot move to webpack-contrib/source-map-loader
