### ISSUE TITLE
array entry point with objects

### ISSUE THREAD

**Issue by svipben** [webpack/webpack#4519]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
You can only use `entry: []` or `entry: {}`

**What is the expected behavior?**
To use
```
entry: [
'react-hot-loader/patch',
'webpack-hot-middleware/client,
{
  vendor: [
    'react',
    'react-dom'
  ],
  main: ./client.js
}
]
```

**If this is a feature request, what is motivation or use case for changing the behavior?**
This will makes build MUCH faster for dev and alows to use react-hot-loader with webpack-hot-middleware and as you can see builds vendor.js with main.js. It drops down from ~700ms to ~200ms.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Node: Latest
Webpack: Latest
OS: Linux Ubuntu 16.04

**As I know I can use externals to drop react with react-dom from my app and add them directly in index.html, but maybe it's possible to edit current function as I said or maybe there are other ways how to do that?**

**Comment by sokra** [comment]
``` js
entry: {
  vendor: [
    'react-hot-loader/patch',
    'webpack-hot-middleware/client',
    'react',
    'react-dom'
  ],
  main: './client.js'
}
```
