### ISSUE TITLE
Unresolved circular dependencies

### ISSUE THREAD

**Issue by jsayol** [webpack/webpack#4520]
**Do you want to request a *feature* or report a *bug*?**
Bug report.

**What is the current behavior?**
An exception gets thrown when trying to extend a class with circular dependencies:
```text
tslib.es6.js:22 Uncaught TypeError: Object prototype may only be an Object or null: undefined
    at setPrototypeOf (<anonymous>)
    at Object.__extends [as a] (tslib.es6.js:22)
    at b.js:4
    at Object.__webpack_exports__.a (b.js:11)
    at __webpack_require__ (bootstrap 4672cf4…:19)
    at Object.defineProperty.value (bootstrap 4672cf4…:65)
    at __webpack_require__ (bootstrap 4672cf4…:19)
    at Object.<anonymous> (bundle.umd.js:108)
    at __webpack_require__ (bootstrap 4672cf4…:19)
    at Object.<anonymous> (bundle.umd.js:321)
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Here's a repo to easily reproduce this: https://github.com/jsayol/typescript-issue-14734
```
$ git clone https://github.com/jsayol/typescript-issue-14734.git
$ cd typescript-issue-14734
$ npm install
$ npm run build
```
And load index.html in the browser.

This reproduction consists of 3 files:
##### a.ts:
```ts
import { B } from './b';

export class A {
  constructor(public prop: string) {
  }

  b(): B {
    return new B(this.prop, 123);
  }

  log() {
    console.log(`Prop: ${this.prop}`);
  }
}
```

##### b.ts
```ts
import { A } from './a';

export class B extends A {
  constructor(prop: string, public otherStuff: number) {
    super(`B ${prop}`);
  }
}
```

##### index.ts
```ts
import { A } from './a';
import { B } from './b';

const a = new A('hello');
const b: B = a.b();
b.log();
```

**What is the expected behavior?**
Seeing "B hello" logged in the console.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
OS: Linux
Webpack: 2.2.1
Node.js: 7.7.0

**Comment by jsayol** [comment]
I initially reported this to TypeScript but someone pointed out this was probably a Webpack issue: https://github.com/Microsoft/TypeScript/issues/14734

**Comment by timse** [comment]
related to #1788

maybe you find an answer there? Not sure if there is a satisfying solution

**Comment by jsayol** [comment]
Hey @timse. I thought that issue was only about default exports but I took a better look and you might be right, it seems like the same underlying issue.

There's really no solution per se, but as a workaround for now I'm putting both classes A and B in the same file.

Let me know if I should close this issue in favor of the referenced one, or if I should add a comment there with the reproduction I provided here.

**Comment by sokra** [comment]
This is neither a webpack nor a typescript issue. The behavior is correct according to the spec.

Note that `class` declarations are not hoisted in ES6.

The execution order is: `b.ts` `a.ts` `index.ts`.

As "fix" switch `import { A } from './a'; import { B } from './b';` to `import { B } from './b'; import { A } from './a';` in `index.ts`

This changes the execution order to: `a.ts` `b.ts` `index.ts`.

**Comment by jsayol** [comment]
Thanks for looking into it @sokra. Moving `import { B } from './b';` in `index.ts` doesn't really make a difference since the TypeScript compiller actually drops that line from the generated `index.js`, as B is only being used as a type.

For reference, the `index.js` generated by TypeScript and used as an entry point with Webpack is this:
```js
import { A } from './a';
var a = new A('hello');
var b = a.b();
b.log();
//# sourceMappingURL=index.js.map
```

Following your suggestion, if I manually add `import { B } from './b';` at the top of the generated `index.js` before running Webpack then everything works as expected.

I think TypeScript is correct in dropping that import, so this still feels like something Webpack should be able to detect.

Any thoughts?

**Comment by sokra** [comment]
TypeScript is not correct in dropping `import { B } from './b';`. An `import` may have side-effects and can't be dropped easily. It may optimize it to `import './b';` if it's only used for its types.

Your case is a good example for this behavior. Dropping the import breaks the build.

A simpler example:

``` js
// a.ts
export class A {}
console.log("test");
```

``` js
// index.ts
import { A } from "./a";
var a: A = null;
```

**Comment by jsayol** [comment]
Your're absolutely right, @sokra. I just did some googling and it seems that by default [TypeScript assumes imported modules imports have no side effects](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-are-imports-being-elided-in-my-emit).

So in my initial example, the "correct" way to do it would be:
```ts
// index.ts
import './b';
import { B } from './b';
import { A } from './a';

const a = new A('hello!');
const b: B = a.b();
b.log();
```

Which, when transpiled, generates:
```ts
// index.js
import './b';
import { A } from './a';
var a = new A('hello!');
var b = a.b();
b.log();
```

A bit redundant, but that's what TypeScript expects. I'm just leaving all this here in case anyone else stumbles upon the same problem.

Thanks for your help, @sokra, and sorry for wasting your time :upside_down_face:

**Comment by joelharkes** [comment]
Im having the exact same error but in my electron react startup app

All I did was (index.tsx):
```
import * as React from 'react';
import * as ReactDom from 'react-dom';

export class Test extends React.Component() {
    render() {
        return <h1>helloWorld</h1>
    }
}

ReactDom.render(
    <Test />,
    document.getElementById("main")
);
```

How can this be? did i forget to import something?

**Comment by joelharkes** [comment]
Ugh freaking obvious but took me ages -.-

``` React.Component() {```

should be without () ofcourse:
```
 React.Component {
```
