### ISSUE TITLE
simple config

### ISSUE THREAD

**Issue by mrMasly** [webpack/webpack#4524]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by langpavel** [comment]
@mrMasly I want to be a bot that kill issues like this. **F**ree **U**niverse **C**ooling **K**idz
