### ISSUE TITLE
Access to a module original source code

### ISSUE THREAD

**Issue by smelukov** [webpack/webpack#4526]
**Do you want to request a *feature* or report a *bug*?**

Request a feature

**What is the current behavior?**

I want to get an original source code of a module.

There are some ways to get it:

- `someModule.source().source()`, but it returns a generated code (where `require` -> `__webpack_require__`)

- `someModule._source.source()` or `someModule.source()._source.source()`, but `_source` looks like a "protected" field and not guarantee that it will remain in feature versions of webpack.

- `someModule.source().map().sourcesContent[0]`, but why `sourcesContent` is array? Can it contain more than 1 element?

- `someModule.source().listMap().children[0].originalSource`, but there is the same question: `why children is array? Can it contain more than 1 element?`

**What is the expected behavior?**

I expect to have some public method like `someModule.originalSource()` or `someModule.source().original()` that uses `someModule._source` property.

**If this is a feature request, what is motivation or use case for changing the behavior?**

I'm developing [Webpack Runtime Analyzer](https://github.com/smelukov/webpack-runtime-analyzer) - a tool for analyzing webpack runtime with integration to code editors, browser plugins, mobile application, etc... to everywhere when having an access to a web-view.
And the next feature that I want to add to it - show info about places when some module is required.
I have `dep.loc` and `dep.range`, but I haven't an access to module original source for slicing a chunk by specified range.
I can't use `fs.readFile` because there are some modules, that generates from the loaders and have not a physical file.

**Comment by sokra** [comment]
Currently there is no "public" method to access the original source.

Using the SourceMap is not appropriate as it could point to the source before loader processing. And this is not the source code `dep.loc` is pointing to.

Best solution is `module._source`, which is only available on `NormalModules`, but other modules don't have a original source anyway.

You can do a PR adding `originalSource()` to `NormalModule` that makes most sense.
