### ISSUE TITLE
2.3.0 breaks path resolution on Windows

### ISSUE THREAD

**Issue by denniskim** [webpack/webpack#4530]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Webpack fails with error on any path, e.g.:
configuration.context: The provided value “d:\\projects\\project\\src” is not an absolute path!

**If the current behavior is a bug, please provide the steps to reproduce.**
Windows 10
Git Bash
Node v6.9.1
npm v4.0.0

Create a webpack project and specify a context path, e.g. `context: path.resolve(__dirname, 'src')`

run webpack with the specified config.

**What is the expected behavior?**
Webpack uses the path as specified.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Windows 10
Git Bash
Node v6.9.1
npm v4.0.0

**Comment by denniskim** [comment]
The problem seems to lie in the new validation schema for paths in config: schemas/ajv.absolutePath.js

The regex at https://github.com/webpack/webpack/blob/v2.3.0/schemas/ajv.absolutePath.js#L20 fails for absolute windows paths that start with a lowercase letter.

"D:\\Projects\\project\src" passes, but "d:\\Projects\\project\src" does not.

**Comment by hustcer** [comment]
Same here.

**Comment by sokra** [comment]
This is caused by a shell launched with a **lowercase** drive letter. As this will cause problems (i. e. https://github.com/webpack/webpack/issues/2815) the validation prevents it.

How did you launch your shell?

**Comment by michael-ciniawsky** [comment]
> If the current behavior is a bug, please provide the steps to reproduce.

Windows 10
Git Bash <=
Node v6.9.1
npm v4.0.0

@sokra 😛

**Comment by pekkah** [comment]
Does it matter how you launch the command prompt as the problem happens with path.resolve paths? Currently cannot use webpack 2.3.0 due to this issue.

**Comment by sokra** [comment]
more info here: https://github.com/nodejs/node/issues/6624

Use uppercase drive letters in shell.

Run this in shell the change the drive letter: `cd .. && cd C%cd:~1%` (when on the `C:` drive)

Check your link to `git bash` for correct drive letter.

**Comment by pekkah** [comment]
This happens in standard out of the box windows 10 command prompt.

**Comment by pleunv** [comment]
As paths and drive letters are case insensitive by default on Windows, does it make sense to change this behavior here? Or will this eventually sort itself out with a fix in the node core module?

**Comment by sokra** [comment]
> This happens in standard out of the box windows 10 command prompt.

hmm... not for my win10 installation...

**Comment by pekkah** [comment]
@sokra Hmm. I have another Win 10 machine at home. I'll try the same when I get home. What version of node are you running?

**Comment by pleunv** [comment]
Well, default prompt (any prompt) does happily switch between lowercase and uppercase when instructed to... The main problem is that tab-completion fixes casing of directories but not of the drive letters. Because of this I tend to usually be working in a lowercase drive letter path (in ConEmu) as well.

![image](https://cloud.githubusercontent.com/assets/182021/24198511/7e3f3406-0f06-11e7-925a-78f0475e8c06.png)

**Comment by pekkah** [comment]
Yep, it seems to be more of an "user error" popping up now as the validation was added. First I couldn't reproduce it at home but then I noticed that I had switched to drive D by cd D:\path. Everything worked but if I used cd d:\path the lower case would blow the validation. In any case this is a breaking change in my opinion. How many people have windows build scripts doing path changes with lower case letters for drives etc..

**Comment by wenzi0github** [comment]
same the problem
```
window10
node v6.9.5
npm 4.2.0
webpack 2.3.0
```
when I run any `webpack`, the problem happended: 
```
$ webpack
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.context: The provided value "d:\\www\\myproject" is not an absolute path!

 - configuration.output.path: The provided value "d:\\www\\myproject/build" is not an absolute path!
```

`cd D:\www` not work, alse into `d:\www`.

**Comment by sokra** [comment]
`cd .. && cd D:\www`

**Comment by RIAstar** [comment]
Same here :(
Windows 7
Git Bash
Node v6.2.2

Rolling back to 2.2.1 for the time being

**Comment by benneq** [comment]
I'm getting `is not an absolute path` too for `configuration.output.path`

But I'm using this value: `../../../../target/`

**Comment by nblackburn** [comment]
Same issue for me

**Comment by MattKunze** [comment]
Running into this issue with commands launched through Jenkins - works fine on the command prompt, but jobs fail from Jenkins

**Comment by ricardoschullerSL** [comment]
Same bug for me:
Windows 10
Cmder
node v6.9.5
npm 4.4.1

**Comment by MattKunze** [comment]
Yep, changed the global workspace path from 'c:\JenkinsWorkspace' to 'C:\JenkinsWorkspace' and it's building again, thanks for pointing in the right direction. Was pulling my hair out earlier (actually just yelling profanity at Jenkins because I couldn't figure out why it kept failing :)

**Comment by gyandeeps** [comment]
@MattKunze facing same issue. Can you explain where did you go inside jenkins to change that. I am a rookie in jenkins world. Thanks for help.

**Comment by MattKunze** [comment]
@gyandeeps - Yeah, it was a little tricky to find. Go to 'Manage Jenkins', then select 'Configure System' and finally click the 'Advanced' button near the home directory setting. Then you should see the path for the workspace:

![image](https://cloud.githubusercontent.com/assets/421270/24214393/f2882c84-0efa-11e7-9b25-d624218412bc.png)

**Comment by astericky** [comment]
I am facing the same issue in our QA Linux environment and in our Mac OSX environment.

**Comment by theodorejb** [comment]
I'm also having this issue after upgrading to v2.3.1. The output path is set to "./app" in my Webpack config file, which now seems to be causing this error:

> Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
> \- configuration[0].output.path: The provided value "./app" is not an absolute path!

BTW, there's a typo on this line: https://github.com/webpack/webpack/blob/ecc2adbbfac51776355add90c24481a42f0cb519/lib/WebpackOptionsValidationError.js#L57. "Initialized" is spelled with a z, not an s. :smile:

**Comment by sokra** [comment]
@theodorejb for the typo you can do a PR.

@theodorejb yes `./app` is not an absolute path and invalid for output.path

@benneq `../../../../target/` is invalid for output.path

**Comment by estorski** [comment]
It definitely IS a breaking change, I'd wish to see some graceful introduction of this change (with a warning message?), not a revolutionary one like it just happened. 
So many tools set up by default to use a lower case drive letter...

**Comment by skolmer** [comment]
I just want to add that windows file systems are typically [not case-sensitive](https://en.wikipedia.org/wiki/Filename#Comparison_of_filename_limitations). As @estorski already said, this is a breaking change and not expected in a minor version. Please rethink this decision.

**Comment by gyandeeps** [comment]
Some of the ancient build systems inside company which i dont control and difficult to change. Meanwhile i came out with a solution (if you dont want to pin webpack) then just use a postinstall script.
https://gist.github.com/gyandeeps/4bea1f400aacb3eae94daf51143f5f9a

**Comment by theodorejb** [comment]
> yes ./app is not an absolute path and invalid for output.path

@sokra Our Webpack config needs to run both on local development machines and as part of a CI service (where the absolute output path won't be the same). What's the right way to do this if a relative path can't be used?

**Comment by CrOrc** [comment]
@theodorejb use path.resolve(__dirname,"./app")

**Comment by sokra** [comment]
I'll look into downgrading this error into a warning.

**Comment by moaead** [comment]
for now, simply replaced first letter to capital and all worked

`const capitalizeFirstLetter = (string) => string.charAt(0).toUpperCase() + string.slice(1);`
`output: { path: capitalizeFirstLetter(path.join(__dirname, clientBundleOutputDir)) },`
`path: capitalizeFirstLetter(path.join(__dirname, './ClientApp/dist'))`

**Comment by pleunv** [comment]
That does get webpack to run but, when started from an incorrectly cased drive-letter commandline, might or will give you lots of warnings like these:

```
WARNING in C:/Projects/project/~/react-dom/lib/getIteratorFn.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\Projects\project\node_modules\react-dom\lib\getIteratorFn.js
    Used by 1 module(s), i. e.
    C:\Projects\project\node_modules\react-dom\lib\traverseAllChildren.js
* c:\Projects\project\node_modules\react-dom\lib\getIteratorFn.js
    Used by 1 module(s), i. e.
    c:\Projects\project\node_modules\react-dom\lib\traverseAllChildren.js
```

Any way around this?

**Comment by DanHarman** [comment]
I'm puzzled that people are referring to an 'incorrectly cased drive-letter' on Windows as that is not a possibility. Regardless of the reason for the change, on windows `c:\` is definitely an absolute path.

**Comment by pleunv** [comment]
In the context of this issue it's incorrectly cased as webpack/nodejs treats `c:\` and `C:\` differently.

**Comment by pekkah** [comment]
Isn't the point of the validation to check if the path is absolute? In windows C:\ and c:\ are both absolute paths. How webpack/nodejs treats the difference between the paths shouldn't be concern of the validation?

**Comment by httpdigest** [comment]
So this?
```JavaScript
if (require('path').isAbsolute(thePath)) ...
```

**Comment by wenzi0github** [comment]
success!
before I use the `git-for-windows`, but `cd D:\www` isn't worked, it will be changed `cd d:\www`. When I use the `Git Shell`(in github for windows), success!

**Comment by Ciantic** [comment]
It should not capitalize it, it causes other issues. It should not just care about casing. If you start capitalizing it errors with this: https://github.com/webpack/webpack/issues/2362 - both of these should be made to not care about casing of drive paths.

**Comment by spyter** [comment]
This is a TOTAL hack, but it works for me as a short term solution so I can continue using my webpack configurations w/2.3.1. I just wanted to share in case it helps anyone else.

I added a function to my webpack file:
```
//to be removed upon webpack fix
const pathHack = (_path) => {
    return _path.charAt(0).toUpperCase() + _path.slice(1).toLowerCase();
};
```

Inside my webpack file, I use that function in my paths so it capitalizes the drive letter:

```
module.exports = {
    context: pathHack(path.join(__dirname, "source")),
    entry: {
        "server": pathHack(path.join(__dirname, "source/server"))
    },
    output: {
        path: pathHack(path.join(__dirname, "build")),
        filename: "server.js"
    }
}
```

Hope this helps :)

**Comment by httpdigest** [comment]
@moaead [already suggested this](https://github.com/webpack/webpack/issues/4530#issuecomment-288643454)

**Comment by spyter** [comment]
Sorry @moaead, I didn't see your comment.

**Comment by sgehrman** [comment]
When can we expect an update that fixes this problem?

**Comment by kisakul** [comment]
Is the issue supposed to be fixed already? On webpack 2.3.2 I'm still seeing the "...is not an absolute path" error.

**Comment by gustavohenke** [comment]
Yeah, it seems like this breaking change will stay.
However the main problem reported here (Windows paths not properly recognized as absolute) seems to be fixed.

**Comment by RomkaLTU** [comment]
What about this (webpack.config.js):

```
const path = require('path');
path: path.resolve(__dirname, './dist'),
```

__dirname refers to the directory where this webpack.config.js lives

**Comment by ng-rupesh** [comment]
Hi guys,
For the time being i have resolved this issue by using-
path: path.resolve(__dirname, './dist'),

hope it helps.

Cheers

**Comment by fullstackdvlper** [comment]
const path = require('path');
path: path.resolve(__dirname, './dist'), 
resolved the problem for me
thanks @RomkaLTU

**Comment by kelleysy** [comment]
Used @RomkaLTU tips and worked for me. Thanks!

**Comment by smithkl42** [comment]
Yeah, the suggested workaround does work:

```
const path = require('path');
path: path.resolve(__dirname, './dist'),
```

But you shouldn't have to do that. And FWIW, I'm *not* launching this from a shell that has a lower-cased first drive letter. I'm using Hyper with Powershell, and my prompt looks like this:

```
PS C:\source\Swyfft\Swyfft.Web>
```

**Comment by jamietre** [comment]
@spyter consider revising your comment  - 

`return _path.charAt(0).toUpperCase() + _path.slice(1).toLowerCase();`

may fix things on windows, but it breaks them on linux. The `toLowerCase()` in the 2nd part isn't needed and breaks xplat compatibility.

**Comment by zhekaus** [comment]
`path: __dirname + '/dist',` works fine for me

**Comment by JasonKleban** [comment]
So was this whole issue supposedly fixed with https://github.com/webpack/webpack/pull/4533 ?  That's what is listed here as Closing it.  But then there's talk of workarounds, and not explicit mention of it being fully fixed.

I'm still getting two warnings like this one (but I'm surprised that it is only two based on how many hundreds of modules this project has!!) at the end of my webpacking:

```
WARNING in C:/Users/jkleban/Repos/MyRepos/My/~/process/browser.js
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* c:\Users\jkleban\Repos\MyRepos\My\node_modules\source-map-loader\index.js!C:\Users\jkleban\Repos\MyRepos\My\node_modules\process\browser.js
    Used by 19 module(s), i. e.
    c:\Users\jkleban\Repos\MyRepos\My\node_modules\source-map-loader\index.js!C:\Users\jkleban\Repos\MyRepos\form-validation\node_modules\react\lib\React.js
* c:\Users\jkleban\Repos\MyRepos\My\node_modules\source-map-loader\index.js!c:\Users\jkleban\Repos\MyRepos\My\node_modules\process\browser.js
    Used by 150 module(s), i. e.
    c:\Users\jkleban\Repos\MyRepos\My\node_modules\source-map-loader\index.js!c:\Users\jkleban\Repos\MyRepos\My\node_modules\react-router\lib\match.js
```

Both of the two warnings I get (one shown) mention source-map-loader, which is the loader for all `/\.js$/` files, `enforce: "pre"`.

I'm using a VSCode build task to invoke webpack .  It is only happening for _me_ when I use the VSCode build task to invoke webpack - but I don't have any reason to believe that it is specific to VSCode -
 perhaps on a different developer's Windows machine it could be the other way around where it ONLY warns in Powershell, or warns in every shell or whatever.

It doesn't occur when I run from the VCCode embedded powershell terminal, however.  One difference I notice between them is that if I instead make the build task run `node -e "console.log(require('path').resolve(__dirname))", then it spits out lowercase `c:\ ...` whereas if I run that same command in Powershell terminal, I get uppercase `C:\`.  I've tried .`toUpper()` or `.toLower()` of the drive-letter in the path in my webpack.config.js `config.output.path`  but those make no difference in behavior now in Webpack 2.5.1 (on this Windows machine).  I don't know that this is relevant anymore.

`node -e "console.log(process.cwd())"` gives uppercase `C:\ ...` in powershell and `/c/...` in the VSCode output as a build task.  Maybe the fix in place is looking for windows-style absolute paths?  But still, why am I only getting two such warnings??

Thanks!

**Comment by allanroberto18** [comment]
`module.exports = function() {
    return {
        entry: __dirname + '/src/app.js',
        output: {
            path: __dirname + '/bin',
            filename: 'app.bundle.js'
        }
    }
};`

"Hint: Keep in mind that you don’t need to write pure JSON into the configuration. Use any JavaScript you want. It’s just a node.js module…"

**Comment by kuhlschrank** [comment]
I'm still having trouble with this issue.

In my angular/typescript project I included
`"compilerOptions": {
    "baseUrl": "./",
    "paths": {
      "app/*": ["./src/app/*"]
    },
  ...
}`

in my tsconfig.json so I can import ts-modules absolutely by

`import { ... } from 'app/counter';`

instead of

`import { ... } from './../counter';`

Problem is, when my folder structure has *any* uppercase letter, both of those import paths get resolved differently and I get the warning:

> WARNING in ./src/app/counter.ts
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
> - c:\Angular\ngrx-test\node_modules\@ngtools\webpack\src\index.js!c:\Angular\ngrx-test\src\app\counter.ts
    Used by 1 module(s), i. e.
    c:\Angular\ngrx-test\node_modules\@ngtools\webpack\src\index.js!c:\Angular\ngrx-test\src\app\first\first.component.ts
> - c:\Angular\ngrx-test\node_modules\@ngtools\webpack\src\index.js!c:\angular\ngrx-test\src\app\counter.ts
    Used by 1 module(s), i. e.
    c:\Angular\ngrx-test\node_modules\@ngtools\webpack\src\index.js!c:\Angular\ngrx-test\src\app\app.module.ts

The capital "A" in "Angular" gets reduced to a lower case "a". I also had the drive letter issue with "C:\" vs "d:\" before...

I tried the workarounds mentioned here and the only conclusion for me is to apply 2 dirty hacks:
- use cmd over powershell, because it allows me to "change" the drive letter case (powershell doesn't?!)
- use all kebab-case in my folder structure

These hacks are very disappointing and I'd love to get rid of them. Is there any progress on the topic that I'm might have missed? I'm pretty new to javascript, node, webpack, angular, etc. so I really are not aware what software really is responsible for my issue now...

ps: please mind that the counter example is just an example for my problem. My production app throws hundrets of those warnings since I introduced the alternative path importing.
