### ISSUE TITLE
alias failed in linux task

### ISSUE THREAD

**Issue by zodana** [webpack/webpack#4531]
**Do you want to request a *feature* or report a *bug*?**

the same unit success in windows , but faild in linux .

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

resolve: {
        extensions: ['.js', '.vue', '.json'],
        modules: [
            resolve('src'),
            resolve('node_modules')
        ],
        alias: {
            'vue$': 'vue/dist/vue.common.js',
            'src': resolve('src'),
            'assets': resolve('src/assets'),
            'components': resolve('src/components'),
            'store': resolve('src/vuex')
        }
    },

this task success from windows .
but faild from linux 
tell me .
some module can not found  from components ..
so I think  whether alias can use in linux ?

**Comment by zodana** [comment]
because Linux case sensitive  but my path in my code not care that !

**Comment by unlimitD** [comment]
do you solved it? i have the exact same issue
