### ISSUE TITLE
js import bootstrap css error

### ISSUE THREAD

**Issue by yoyo837** [webpack/webpack#4535]
First of all, I am sorry that my English may be very poor, so I use google translate to describe my problem!
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When I import bootstrap css(node_modules/↓) in xxx,js file, webpack css-loader? report error like this 
"Possibly missing opening '{' ". 
**If the current behavior is a bug, please provide the steps to reproduce.**
After my analysis, I suspect that the cause of the problem is due to the csshack in the file.(bootstrap.css v3.3.7 line:3627 'border-bottom: 4px solid \9') ,delete '\9' or add new line anyone css property key and value, It's work good;

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
windows 10 x64, node.js x64 6.10 webpack 2.3

Looking forward to your reply, thanks!

**Comment by michael-ciniawsky** [comment]
@yoyo837 Can you should the full StackTrace (Error) please and your `webpack.config.js`, I also recommend to statically reference frameworks like boostrap in your `index.html` as long as you don't need anything at build time from that particular framework (e.g like with JS Libs/Frameworks)

**Comment by yoyo837** [comment]
StackTrace：
[
ERROR in ./~/css-loader!./~/postcss-loader!./~/less-loader/lib/loader.js!./~/sass-loader/lib/loader.js!./~/admin-lte/bootstrap/css/bootstrap.min.css

Module build failed: Unrecognised input. Possibly missing opening '{' 

@ F:\source-control\svn\vipboss2.0\node_modules\admin-lte\bootstrap\css\bootstrap.min.css (line 5, column 56897)    
]

Thank you for your reply.

You are right, statically reference  bootstrap in index.html, it's work. But i would like to use import module only in one place. This error does not occur in the dev environment.

The cause of the problem may be because the css file is merged and compressed.

My `webpack.config.js`:

`const path = require('path');
const webpack = require('webpack');
const ExtractTextPlugin = require('extract-text-webpack-plugin');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const OpenBrowserPlugin = require('open-browser-webpack-plugin');
const CleanWebpackPlugin = require('clean-webpack-plugin');
//webpack-merge
const _ = require('lodash');
const pagesCfg = require('./config/page');

const publicPath = '/static';
var isProd = false; //生产环境
process.argv.some((item) => {
    if (item === '-p' || item === '--production') {
        isProd = !0;
    }
});

module.exports = {
    context: __dirname,
    entry: { //TODO 第三方独立打包
        adminlteCss: [ //
            //TODO 直接引入模块种的bootstrap报错
            // Module build failed: Unrecognised input. Possibly missing opening '{'
            // @ F:\source-control\svn\vipboss2.0\node_modules\admin-lte\bootstrap\css\bootstrap.css (line 1, column 57005)
            // './node_modules/admin-lte/bootstrap/css/bootstrap.min.css', //
            // TODO 外部资源引用
            // 'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css', //
            // 'https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css', //
            './node_modules/admin-lte/dist/css/AdminLTE.min.css', //
            // './node_modules/admin-lte/dist/css/skins/_all-skins.min.css,'//
            './node_modules/admin-lte/dist/css/skins/skin-blue.min.css'
        ],
        adminlteJs: [ //
            // './node_modules/admin-lte/bootstrap/js/bootstrap.min.js', //
            './node_modules/admin-lte/dist/js/app.min.js' //
        ],
        // vendor: ['jquery'],
        app: ['babel-polyfill', './src/script/index.js']
    },
    output: {
        path: path.resolve(__dirname, './dist'),
        filename: 'js/entry/[name].[hash:6].js',
        // library: '[name].[hash:6]',
        publicPath: publicPath
    },
    devServer: {
        contentBase: path.resolve(__dirname, './src'),
        inline: true,
        historyApiFallback: true
    },
    module: {
        rules: [{
            test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/,
            use: [{
                loader: 'url-loader?limit=10000&mimetype=application/font-woff&name=images/[path][name].[hash:6].[ext]'
            }]
        }, {
            test: /\.ttf$/,
            use: [{
                loader: 'url-loader?limit=10000&mimetype=application/octet-stream&name=images/[path][name].[hash:6].[ext]'
            }]
        }, {
            test: /\.eot$/,
            use: [{
                loader: 'file-loader?name=images/[path][name].[hash:6].[ext]'
            }]
        }, {
            test: /\.svg$/,
            use: [{
                loader: 'url-loader?limit=10000&mimetype=image/svg+xml&name=images/[path][name].[hash:6].[ext]'
            }]
        }, {
            test: /\.(png|jpg|gif)$/,
            use: [{
                loader: 'url-loader?limit=8192&name=images/[path][name].[hash:6].[ext]'
            }, {
                loader: 'image-webpack-loader'
            }]
        }, {
            test: /\.(css|less|scss|sass)$/,
            use: ExtractTextPlugin.extract({
                fallback: 'style-loader',
                use: ['css-loader', 'postcss-loader', 'less-loader', 'sass-loader'],
                publicPath: `${publicPath}/`
            })
        }, {
            test: /\.ts$/,
            exclude: /node_modules/,
            use: [{
                loader: 'ts-loader'
            }]
        }, {
            test: /\.js$/,
            exclude: /node_modules/,
            loader: 'babel-loader',
            query: {
                presets: ['es2015']
            }
            // }, {
            //     test: /\.html$/,
            //     use: [{
            //         loader: 'html-withimg-loader'
            //     }]
        }]
    },
    devtool: isProd ? 'cheap-module-source-map' : 'cheap-module-eval-source-map',
    plugins: (() => {
        var array = [
            new webpack.optimize.CommonsChunkPlugin({
                name: 'commons',
                filename: 'js/[name].[hash:6].js',
                minChunks: Infinity
            }),
            new ExtractTextPlugin({
                filename: 'css/[name].[hash:6].css',
                disable: false,
                allChunks: false
            }),
            new webpack.HotModuleReplacementPlugin(),
            new OpenBrowserPlugin({
                url: `http://localhost:8080${publicPath}`
                // }),
                // new webpack.DllPlugin({
                //     path: path.resolve(__dirname, 'dist', '[name]-manifest.json'),
                //     name: '[name].[hash:6]'
                // }),
                // new webpack.DllReferencePlugin({
                //     context: __dirname,
                //     manifest: require('dist/vender-manifest.json')
            })
        ];
        //页面配置
        let prodCfg = {
            minify: { //内部使用的是https://github.com/kangax/html-minifier
                removeAttributeQuotes: false,
                removeComments: true,
                removeEmptyAttributes: true,
                collapseWhitespace: true, //压缩空白区域
                collapseInlineTagWhitespace: true, //压缩标签属性值内的空白区域，
                minifyCSS: true, //压缩内嵌样式
                minifyJS: true //压缩内嵌脚本
            }
        };
        const resolvePagesCfg = (refer, root) => {
            root = root || '';
            if (_.isObject(refer)) {
                refer.name = _.toString(refer.name) || '';
                if (refer.name.length == 0) {
                    refer.children = refer.children || [];
                }
                if (_.isArray(refer.children)) { //视为目录
                    refer.children.forEach((subrefer) => {
                        resolvePagesCfg(subrefer, `${root}${refer.name}/`);
                    });
                } else { //视为文件
                    let opt = _.cloneDeep(pagesCfg.defaultOptions || {});
                    refer.optins = refer.optins || {};

                    var filename = `${root}${refer.name}.html`;
                    if (filename.startsWith('/')) {
                        filename = filename.substr(1);
                    }

                    _.merge(opt, refer.optins, {
                        filename: filename
                    });

                    _.merge(opt, {
                        template: path.resolve(__dirname, `config/page/${opt.template}`)
                    });
                    if (isProd) {
                        _.merge(opt, prodCfg);
                    }
                    array.push(new HtmlWebpackPlugin(opt));
                }
            }
        };

        resolvePagesCfg(pagesCfg.pages);

        if (isProd) {
            array.push(
                new webpack.optimize.UglifyJsPlugin({
                    sourceMap: true,
                    compress: {
                        warnings: false,
                        drop_console: true
                    },
                    comments: false,
                    beautify: false
                }),
                new CleanWebpackPlugin(['dist'], {
                    verbose: true,
                    dry: false
                }));
        }
        return array;
    })(),
    resolve: {
        extensions: ['.ts', '.js'],
        modules: [path.resolve(__dirname, './src'), 'node_modules']
    }
};
`

**Comment by michael-ciniawsky** [comment]
Please add backticks around the code and sanitize unrelevant parts of the config (other loaders) 😛 

```js
{
  test: /.(css|less|scss|sass)$/,
  use: ExtractTextPlugin.extract({
    fallback: 'style-loader',
    use: ['css-loader', 'postcss-loader', 'less-loader', 'sass-loader'], // This doesn't work
    publicPath: ${publicPath}/
  })
}
```

Your will need to split it up, you can't pass `.less`to `sass-loader` (node-sass) first or the other way around. CSS maybe accepted by the LESS/SCSS Parser you need to look that up, but LESS in SASS or otherwise will break the build sooner or later

**webpack.js**
```js
const ExtractTextPlugin = require('extract-text-webpack-plugin')
// Instances 
const extractCSS = new ExtractTextPlugin('vendor.css')
const extractSCSS = new ExtractTextPlugin('styles_1.css')
const extractLESS = new ExtractTextPlugin('styles_2.css')

{
  test: /.(css)$/,
  use: extractCSS.extract({
    fallback: 'style-loader',
    use: [ 'css-loader', 'postcss-loader' ]
    publicPath: ${publicPath}/
  })
},
{
  test: /.(sass|scss)$/,
  use: extractSCSS.extract({
    fallback: 'style-loader',
    use: [ 'css-loader', 'postcss-loader', 'sass-loader' ]
    publicPath: ${publicPath}/
  })
},
{
  test: /.(less)$/,
  use: extractLESS.extract({
    fallback: 'style-loader',
    use: [ 'css-loader', 'postcss-loader', 'less-loader' ]
    publicPath: ${publicPath}/
  })
}
```

Both LESS and SASS in one code base is not a good idea 😛

**Comment by yoyo837** [comment]
I agree with you(only less or sass).

This is just a demo template that tells the dev-er what you can choose.

Thank you very much for your patience.

Thanks!

**Comment by michael-ciniawsky** [comment]
@yoyo837 Those this resolve your issue ?

**Comment by yoyo837** [comment]
Yes, well, the unreasonable use of loader causes this problem.

**Comment by michael-ciniawsky** [comment]
@yoyo837 kk if there are any other regressions [Official Docs](https://webpack.js.org) / StackOverFlow (webpack) / Gitter(webpack/webpack) are great resources or open a new issue, but please close this one then 😛

**Comment by yoyo837** [comment]
@michael-ciniawsky You're right! I did that. But still your help eventually solved the problem.

Close the issue and comment.

**Comment by Jeff-Tian** [comment]
I met a same error and fixed it by separate `(less|css)` to `less` and `css` individually. Thanks for the information @michael-ciniawsky provided.
