### ISSUE TITLE
Warn when trying to import a module with an empty string request

### ISSUE THREAD

**Issue by darrenscerri** [webpack/webpack#4541]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

Webpack doesn't warn when a loader tries to import an empty string (`''`). This is similar to https://github.com/webpack/webpack/issues/2006 but somehow, loaders can still require (`''`).

**If the current behavior is a bug, please provide the steps to reproduce.**
See this repo for more information: https://github.com/darrenscerri/webpack-extract-text-plugin-empty-require-error.

**What is the expected behavior?**
Webpack should warn when trying to import a module from a loader with an empty string request.

node v7.7.1
webpack v2.3.1

Related issues:
https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/465
https://github.com/webpack-contrib/css-loader/issues/462

**Comment by sokra** [comment]
`url("")` is rewritten to `require("./")`. So this is not a webpack issue, but a css-loader issue.
