### ISSUE TITLE
Documentation: Clarify speed column in devtool chart

### ISSUE THREAD

**Issue by panozzaj** [webpack/webpack#4543]
**Do you want to request a *feature* or report a *bug*?**

report a bug in the documentation

**What is the current behavior?**

Currently the documentation for [devtool configuration](https://webpack.github.io/docs/configuration.html#devtool) is unclear to me, at least for the speed section. It seems like plusses mean that it runs faster. But maybe it means it takes more time? What does `o` mean? What does `-` mean?

**What is the expected behavior?**

It seems like one or more of the following would help:

 - a legend describing what the speed symbols mean
 - using different symbols (maybe "N/A" or "not applicable" if it is not applicable to that feature)

Crazy idea:

 - using a static [gauge image](https://www.google.com/search?q=gauge&espv=2&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjDjtbe0erSAhXnzlQKHQ1fBUsQ_AUIBigB&biw=1530&bih=934) of some sort to show the relative speeds for each section

Thanks!

**Comment by bebraw** [comment]
Can you re-open this at the [docs repo](https://github.com/webpack/webpack.js.org/issues)? Thanks.

**Comment by panozzaj** [comment]
Sounds good, sorry I put in the wrong place!
