### ISSUE TITLE
Code Splitting incorrectly merging chunks

### ISSUE THREAD

**Issue by aikar** [webpack/webpack#4546]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I have sections on a page. Only 1 will be showing at a time. I want to Code split so the chunk loads when the panel is active (react component mounts)

Take the following example:
```javascript
<panel id="foo">
  <lazy>{() => import("foo.js")}</lazy>
</panel>
<panel id="bar">
  <lazy>{() => import("bar.js")}</lazy>
</panel>
```
Lazy is a wrapper that only executes the callback when the component mounts. 
I expect this to generate 2 chunks, however webpack is generating foo and bar into the same chunk file.

I assume that webpack is incorrectly assuming that because it is in the same file, it must be loaded at the same time.
This assumption is wrong. Webpack should treat any code split separately when they are in callbacks.

I tried to use require.ensure too and give different names:
```javascript
<panel id="foo">
  <lazy>{(load) => require.ensure([], (require) => {
                        load(require("foo.js"));
                    }, "foo")}</lazy>
</panel>
<panel id="bar">
  <lazy>{(load) => require.ensure([], (require) => {
                        load(require("bar.js"));
                    }, "bar")}</lazy>
</panel>
```

This was a less clean approach, but let me name my chunks, so that was nice, but it still has the same problem, they go into foo

Copy of the lazy load logic can be found here in the require.ensure form: https://gist.github.com/aikar/cc61d652c0d24aad4fc1fa5987abc6d2

**What is the expected behavior?**

I expect that the code is split into multiple parts.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Improve code splitting

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Webpack 2.3.1.

**Comment by aikar** [comment]
Nevermind. It looks like the dependencies of these views were simply shared too much that was the ultimate cause as using it in other places I was able to get multiple splits.

**Comment by Dictory** [comment]
@aikar can u show how u create dynamic import for chunks? 
[My question on SO](https://stackoverflow.com/questions/44450307/how-do-dynamic-import-for-code-splitting-use-webpack-2)
