### ISSUE TITLE
Issue with Inferno loader for JSX using Webpack API

### ISSUE THREAD

**Issue by ddibiase** [webpack/webpack#4547]
**What is the current behavior?**

Getting an error in the console about unrecognized token to do bad JSX parsing.

**If the current behavior is a bug, please provide the steps to reproduce.**

This is my configuration using webpack API:

```
const compiler = webpack({
  entry: files.reduce(
    (memo, file) => {
      memo[file] = path.resolve(__dirname, `../${file}`);
      return memo;
    },
    {}
  ),
  target: 'web',
  output: {
    path: path.resolve(__dirname, `../${this.publicDir}`),
    filename: 'app.js',
    library: 'Site',
    libraryTarget: 'window'
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        issuer: { exclude: [
          path.resolve(__dirname, '../node_modules')
        ] },
        loader: 'babel-loader',
        options: {
          presets: ['es2015'],
          plugins: ['inferno' ]
        }
      }
    ]
  }
}, (err, stats) => {
  if (err || stats.hasErrors()) {
    const info = stats.toJson();
    console.error(info.errors, err);
    return;
  }
  console.log('DONE');
});
```

Receiving this error: ``` Unexpected token (5:2)\nYou may need an appropriate loader to handle this file type.```

**What is the expected behavior?**

Webpack should load the `babel-plugin-inferno` plugin and parse the JSX contained in the file being loaded.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

I'm using Webpack 2.3.0. I've reached out to my core team members at InfernoJS and they don't see any issues and suppose it might be a minor issue in Webpack.

**Comment by sokra** [comment]
Please include the full error message.

Your issuer configuration is weird, but I guess that's not an issue here.

**Comment by ddibiase** [comment]
Ah yes sorry, here's the error: `Unexpected token (5:2)\nYou may need an appropriate loader to handle this file type.`

It's failing on an Inferno component where the JSX portion starts:

```
import Inferno from 'inferno';
export const SampleStatelessComponent = () => (
  <div>
    This is the div section
  </div>
);
```

So it seems that the `babel-plugin-inferno` plugin hasn't been loaded.

Regarding the issuer configuration, I attempted placing the exclude property outside the issuer but it wasn't reading it, I had to embed the value directly in issuer.

**Comment by ddibiase** [comment]
Hmmm, so diving into this further I was given a suggestion to use `babel-presets-env` which handles the transforms differently. Here's my new config:

```
const compiler = webpack({
  entry: files.reduce(
    (memo, file) => {
      memo[file] = path.resolve(__dirname, `../${file}`);
      return memo;
    },
    {}
  ),
  target: 'web',
  output: {
    path: path.resolve(__dirname, `../${this.publicDir}`),
    filename: 'app.js',
    library: 'Site',
    libraryTarget: 'window'
  },
  module: {
    rules: [
      {
        test: /\.js?$/,
        use: [
          {
            loader: 'babel-loader',
            options: {
              babelrc: false,
              presets: [['env', { 'targets': { 'browsers': ['> 1%', 'ie >= 10'] } }]],
              plugins: ['syntax-jsx', 'inferno', { import: true }]
            }
          }
        ]
      }
    ]
  }
}, (err, stats) => {
  if (err || stats.hasErrors()) {
    const info = stats.toJson();
    console.error(info.errors, err);
    return;
  }
  console.log('DONE');
});
```

Seeing the error: `Module build failed: Error: Plugin 2 specified in "base" provided an invalid property of "import"\n    at Plugin.init`

**Comment by sokra** [comment]
could you log `stats.toString()` which gives the full error message?
