### ISSUE TITLE
Breaking change introduced between 2.2.1 and 2.3.0 - relative/absolute paths

### ISSUE THREAD

**Issue by pghalliday** [webpack/webpack#4549]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

The current NPM semantic version standards state that changes between minor versions should be non-breaking.

https://docs.npmjs.com/getting-started/semantic-versioning

However the treatment of configuration between 2.2.1 and 2.3.1 has introduced a breaking change.

```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.output.path: The provided value "./ui/app" is not an absolute path!
```
I guess this is done now and I doubt you'll want to fix it, but I thought you should know, as you use NPM for distribution, that you're not applying their versioning standards, which are required for the correct use of version specification in `package.json`. ie. `^2.2.1` will currently resolve to `2.3.1`

**If the current behavior is a bug, please provide the steps to reproduce.**

- Using webpack 2.2.1 configure a relative output path
- Upgrade to webpack 2.3.1 and observe the failure

**What is the expected behavior?**

Minor version changes should not introduce breaking changes

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by pghalliday** [comment]
Actually was this change intended? Maybe it's a bug :s

**Comment by davetron5000** [comment]
It's #4149 that introduced this.  It says it was created to fix #899 but I can't understand the issue enough to know how or if changing `output.path` to require being absolute is required to fix that issue.

The description of output path does clearly indicate it should be absolute, even though it obviously didn't need to be before the latest release.  Also [the docs](https://webpack.js.org/concepts/#output) do show using a full path like so:

```javascript
const path = require('path');

module.exports = {
  entry: './path/to/my/entry/file.js',
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'my-first-webpack.bundle.js'
  }
};
```

So, for my uses, I've just switched to that.

**Comment by pghalliday** [comment]
Yeah i've been going through my projects, changing it and agreed the specific docs do say it should be absolute, whereas the quick start stuff does not (although it does demonstrate use of an absolute path).

TBH I'm not sure this is the right side of [the principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) though

**Comment by sokra** [comment]
since webpack 1 webpack requires `output.path` to be an absolute path. This hasn't changed. It's just validated now.

**Comment by vpmedia** [comment]
Hi,
I'm on windows and getting the following error messages:
    Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
     - configuration.context: The provided value "c:\\MyDir\\ProjectDir" is not an absolute path!
     - configuration.output.path: The provided value "c:\\MyDir\\ProjectDir\\dist\\js" is not an absolute path!
The paths are absolute and output.path is generated using `path.resolve(__dirname, 'dist/js')`. Any tip why it is failing?

**Comment by waywaaard** [comment]
@vpmedia The problem is the lower case drive letter: Use `C:\MyDir\ProjectDir\dist\js`

**Comment by vpmedia** [comment]
Yes it's working, thank you!

**Comment by javigarcia1989** [comment]
Hi,
I'm on windows and getting the following error messages when i start proyect:
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.output.path: The provided value "./" is not an absolute path!

What can i do?

**Comment by tinchou** [comment]
https://github.com/aspnet/JavaScriptServices/issues/782 has some possible fixes.

E.g. adding the following at the start of `webpack.config.js` works for me:

```
__dirname = __dirname.charAt(0).toUpperCase() + __dirname.slice(1);
```

**Comment by bneumann** [comment]
I have sort of the same error now. Webpack seems to evaluate relative/absolute paths now as @sokra said. Problem is, that is not at all consistent. configuration.output.filename has to be relative where configuration.output.path has to be absolute. In my case I am building my paths at the beginning of the script like so:

```javascript  const BASE_DIR = __dirname;
  const BUILD_DIR = path.join(BASE_DIR, 'build');
  const DOC_DIR = path.join(BASE_DIR, 'doc');
  // const RELEASE_DIR = path.join(BASE_DIR, 'releases');
  const MODULE_ENTRY = path.join(BASE_DIR, 'src/MusicXml.js');
  const ALL_ENTRIES = path.join(BASE_DIR, 'src/index.js');
  const TARGET_RAW = path.join(BUILD_DIR, 'vexflow-musicxml.js');
  const TARGET_MIN = path.join(BUILD_DIR, 'vexflow-musicxml-min.js');
  const TARGET_TESTS = path.join(BUILD_DIR, 'vexflow-musicxml-tests.js');```

So to please the webpack config I have to check which path should be absolute an which relative. Does it relly have to be this hard? I am using these paths throughout the script and I would have to double check every piece of it

**Comment by gregbown** [comment]
The solution I arrived at was to use the __dirname variable as it is an absolute path to the build script location.  This allows it to be more portable among the dev team because they don't all end up with a unique URL in there local build script.

**use the __dirname variable***
``
path:  __dirname.replace('config', 'dist'),
``

**For the fileName and chunkFileName**
merely adding ./ to the path flips it to a relative path.
```
filename: './scripts/app/[name].bundle.js',
```

**Comment by mshivkumar** [comment]
@davetron5000 Hey, your solution worked for me.Thanks a ton.

**Comment by jidemobell** [comment]
@davetron5000  Thanks a lot

**Comment by iampaa** [comment]
@davetron5000 Thanks

**Comment by bradisbell** [comment]
> since webpack 1 webpack requires output.path to be an absolute path. This hasn't changed. It's just validated now.

@sokra I don't have an absolute path in a single one of my WebPack projects, and they've all worked fine until I upgraded.  This is definitely a change.

... and a frustrating one at that.

**Comment by abazudosen** [comment]
thank you @davetron5000

**Comment by EugeneDae** [comment]
...and why does the path have to be absolute?!

**Comment by dcu-sharepoint** [comment]
@tinchou    __dirname = __dirname.charAt(0).toUpperCase() + __dirname.slice(1);
this line didn't work for me, I put it as the first line in the config file, is that the right plate to put it?

**Comment by tinchou** [comment]
Yup, after all my `require`s.

**Comment by coolzyte** [comment]
This is the solution

const path = require('path');

module.exports = {
  entry: './path/to/my/entry/file.js',
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'my-first-webpack.bundle.js'
  }
}; 


This is how to use it

const path = require('path');

module.exports = {
	entry: './app/assets/scripts/App.js',
	output: {
		path: path.resolve(__dirname, './app/temp/scripts'),
		filename: 'App.js'
	}
};

working for me

**Comment by pavlovt** [comment]
I just added to my dev dependencies:
"webpack": "2.2.0",
"webpack-dev-server": "2.3.0"
and it worked.

By the way great work guys from the webpack project - you managed to break probably 90% of the projects which are using your package...
