### ISSUE TITLE
Add support for `nonce` attribute (CSP)

### ISSUE THREAD

**Issue by necolas** [webpack/webpack#455]
New part of CSP and shipped in Chrome 36. Applies to `<script>` and `<style>` tags: https://w3c.github.io/webappsec/specs/content-security-policy/#script-src-the-nonce-attribute

AFAICT, you can't yet add attributes to the `script` and `style` tags that webpack creates.

(Not familiar with this; saw it in a patch from our security team and thought people using webpack will eventually want this feature.)

**Comment by bebraw** [comment]
@necolas Maybe this would be more relevant for [html-webpack-plugin](https://www.npmjs.com/package/html-webpack-plugin) since it generates those tags for each bundle?

**Comment by necolas** [comment]
I don't think so. Webpack is responsible for code-splitting and injecting scripts/styles for async chunks. The `style-loader` might be the place for `style` nonce though.

**Comment by bebraw** [comment]
@necolas Ok, cool. Thanks for clearing that up. 👍
