### ISSUE TITLE
UglifyJsPlugin compress `with:0%` to `width:0` , that cause some style problems

### ISSUE THREAD

**Issue by haoranw** [webpack/webpack#4556]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
i'm using UglifyJsPlugin to compress css files,
and add width:0% in the style of flexbox ,to compatible with some old browsers(that only support older version of flexbox )
But UglifyJsPlugin compress width:0% to width:0 , that cause some style problems

**If the current behavior is a bug, please provide the steps to reproduce.**
use UglifyJsPlugin to compress the css file that contain `width:0%`

**What is the expected behavior?**
remain width:0% in the css files
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

webpack:v2.2.1

**Comment by timse** [comment]
this does not sound like webpack can do anything about it, as UglifyJs is an external dependency of webpack.
Can you check what causes this transformation and open an issue at the appropriate repository? :)

closing for now as we can not fix this here.
