### ISSUE TITLE
Broken docs with <details> and <summary> tags

### ISSUE THREAD

**Issue by marcin-mazurek** [webpack/webpack#4559]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
![screen shot 2017-03-24 at 12 14 54](https://cloud.githubusercontent.com/assets/6684554/24291975/8465f7a8-108b-11e7-9f36-9f001878ea3e.png)

![screen shot 2017-03-24 at 12 14 21](https://cloud.githubusercontent.com/assets/6684554/24291955/73c62ac6-108b-11e7-938e-453c396297c4.png)

Documentation files that contain expandable/collapsible text are not being displayed properly.
There's no code formatting, syntax highlighting and `</details>` closing tag is being ignored - the text from the opening tag to the end of the file is collapsed.

It looks like an undocumented GitHub feature that was removed/is broken. The only info I found about it is a Gist file and the example there isn't working either: https://gist.github.com/ericclemmons/b146fe5da72ca1f706b2ef72a20ac39d

The latest comment there suggests that Markdown is no longer parsed inside the `<details>` tag.

**If the current behavior is a bug, please provide the steps to reproduce.**
Open a document that contains `<details>` and `<summary>` tags, eg. https://github.com/webpack/webpack/blob/master/examples/i18n/README.md

Look for ▶ symbol and expand it. You'll notice a `</details>` tag at the beginning of a code block and more content that should be displayed even if the details are collapsed.

**What is the expected behavior?**
The content is formatted and only unnecessary details are hidden, or everything is displayed.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Checked in the latest Chrome and Firefox.

**Comment by marcin-mazurek** [comment]
I'm happy to submit a pull request if you let me know how you'd like to handle it.

**Comment by sokra** [comment]
The new github-flavored-markdown parser...

**Comment by marcin-mazurek** [comment]
@sokra @bebraw I'd like to submit a fix. I did some research - looks like there's no other solution for collapsing/expanding with GitHub Markdown. So, I think we've got two options:

1. Replace collapsed (non-essential) code with a comment, eg. `// Webpack require mechanism - ommited for brevity`.
2. Keep the whole listing - just remove `<details>` and `<summary>` tags.

Which one do you guys prefer?

**Comment by bebraw** [comment]
Both have their sides. 1. would be neater but lead to more maintenance perhaps. 2. would be easier.

Maybe 3. would be possible. What if we hid the output within HTML comments and render them through the site so that they fold?

**Comment by marcin-mazurek** [comment]
Regarding the first option - there shouldn't be more maintenance required. There's an examples parser (https://github.com/webpack/webpack/blob/master/examples/template-common.js#L46) that adds the `<summary>` and `<details>` tags - it should be pretty straightforward to replace those with a comment.

In terms of option 3 - at the moment the listings are not rendered to the page (checked both v1 and v2):

![screen shot 2017-03-27 at 22 35 22](https://cloud.githubusercontent.com/assets/6684554/24376983/0f432846-133e-11e7-84db-fe875d6b77e6.png)

They are just links to the `examples/` folder on GitHub. Are you suggesting that we render the examples to the page instead?

**Comment by bebraw** [comment]
> They are just links to the examples/ folder on GitHub. Are you suggesting that we render the examples to the page instead?

If it's useful, the site could pick up the examples too so you get `<plugin>/examples/<example>`.

Let's wait for Tobias on final decision.

**Comment by sokra** [comment]
fixed
