### ISSUE TITLE
webpack sourcemaps do not work well with ES6 imports

### ISSUE THREAD

**Issue by sherzinger** [webpack/webpack#4560]
**Do you want to request a *feature* or report a *bug*?**
Report a bug.

**What is the current behavior?**
Sourcemaps do not work for ES6 imports
Example: `import foo from '../src/fooProvider'` will be visible as `__WEBPACK_IMPORTED_MODULE_0__src__fooProvider__.a`

Using `require` and `module.exports` will correctly make `foo` available in the debugger scope.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Clone minimal project: https://git-r3lab.uni.lu/sascha.herzinger/debugger-bug.git
2. npm install
3. run karma to see if everything works
4. run karma with breakpoint in test/foo-test.js line 6
5. See messed up scope as shown here:
<img width="473" alt="es6" src="https://cloud.githubusercontent.com/assets/11333940/24293228/f9e82e2e-1090-11e7-871e-8bbef8781c88.png">

**What is the expected behavior?**
being able to inspect `foo` instead of `__WEBPACK_IMPORTED_MODULE_0__src__fooProvider__.a`
when using ES6 imports.
I want to see this, but with ES6 imports:
<img width="359" alt="commonjs" src="https://cloud.githubusercontent.com/assets/11333940/24293227/f9e525bc-1090-11e7-9e4d-69ae7929c870.png">

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Chrome 56,
node 7.7.1,
webpack (s. package.json)
Webstorm 2017.1
macOS 10.12.3

**Comment by Vanuan** [comment]
Yeah, sourcemap doesn't seem to hide stacktrace:

![screenshot from 2017-04-01 02 40 39](https://cloud.githubusercontent.com/assets/361985/24590711/a49f003e-17fa-11e7-9faa-7d6df70c62a7.png)

Also you have to do multiple steps for one line, since it uses lookup search for each imported function.

**Comment by sherzinger** [comment]
@Vanuan using named imports makes it even worse for me:

![screen shot 2017-04-03 at 13 58 54](https://cloud.githubusercontent.com/assets/11333940/24608199/e0de3bc0-1875-11e7-9dbf-7ce85c733304.png)


Also, do you know if this issue is related to the incorrect line numbers mappings?
A test with 10 LOC, designed to fail, shows me this:

![screen shot 2017-04-03 at 14 06 34](https://cloud.githubusercontent.com/assets/11333940/24608407/c2c0384a-1876-11e7-9afc-5816c7b45e7f.png)

**Comment by Vanuan** [comment]
@sherzinger No, this is related to disabling babel ES6 module transform (`{modules:false}`).

I.e. webpack adds `__WEBPACK_IMPORTED_MODULE_...` to global namespace but doesn't add corresponding local variables.

**Comment by sherzinger** [comment]
@Vanuan I also thought it was babel at first, but if you check my sample project I completely removed babel from it and still get this behaviour.

**Comment by Vanuan** [comment]
@sherzinger I'm saying that if you'd use `babel` for module tranformation the problem would gone

**Comment by abirmingham** [comment]
I'm running into this as well. I'd like to avoid adding Babel because it adds 30 seconds to my build.

**Comment by the-spyke** [comment]
Same issue with `Webpack 3.x`. Is this fixed in `4.x` or at least going to be fixed?

**Comment by evilebottnawi** [comment]
@the-spyke need test, can you tests this with `webpack@4`?

**Comment by sherzinger** [comment]
I did, it's still not fixed...

**Comment by the-spyke** [comment]
@Vanuan As I understand, transforming imports with Babel not just makes your build slower, it removes all useful features that ES Modules give (static checks, tree shaking, concatenation, etc.).

**Comment by morsdyce** [comment]
I'm interested in working on this and willing to commit time to it, I'd love if I could get some pointers on where I could get started solving this.

@sokra @bebraw

@sherzinger I wasn't able to open the minimal reproduction case, could you make sure it's public?

**Comment by sherzinger** [comment]
@morsdyce thank you for doing this!

I'm afraid the repo fell victim to a cleanup I did some time ago. I'll see if I find some backups or re-create it otherwise.

**Comment by sherzinger** [comment]
Here you go: https://github.com/sherzinger/webpack-issue-4560

Unlike the example in the first post this code does not use karma/jasmine to include the bundle.
Instead you run `npm run devServer` and open `foo.html`, so you can use your browser dev tools.
I thought that might be a bit more light weight.

**Comment by morsdyce** [comment]
Awesome, thanks!

**Comment by bloody-ux** [comment]
Any update?

**Comment by morsdyce** [comment]
Not yet, got caught up with a few things on the way. Still researching some approaches to handle this.

**Comment by abirmingham** [comment]
I'm a little bewildered as to why there is such little activity on this issue. Sourcemaps should work. I can only think of a few explanations:

1. In general people don't use the debugger as much as I do.
2. People have discovered a workaround that I don't know about :)
3. There is another issue that describes the same behavior that is more active.

Anyone know which of the above is true, if any? Thanks!

**Comment by the-spyke** [comment]
@abirmingham 
4. People have lost hope.

**Comment by komali2** [comment]
Still not working :(

**Comment by evilebottnawi** [comment]
If somebody still have problem please open new issue with reproducible test repo, thanks

**Comment by abirmingham** [comment]
New issue created: #9461

**Comment by aabuhijleh** [comment]
> @sherzinger I'm saying that if you'd use `babel` for module tranformation the problem would gone

I'm using `babel` in my project but not sure how to do this. Can someone please show me how exactly to use `babel` for module transformation?

This is how my `.babelrc` looks like

```
{
  "presets": ["@babel/env", "@babel/react", "@babel/typescript"]
}
```

and I'm using `babel-loader` in my webpack configuration file
