### ISSUE TITLE
Feature: Reuse DLL bundles for production rebuild - export tree-shakable es2015 module format

### ISSUE THREAD

**Issue by Phoscur** [webpack/webpack#4561]
**Do you want to request a *feature* or report a *bug*?**
A feature for build time optimization, extending the Webpack DLL functionality

**What is the current behavior?**
Wepack DLLs speed up development builds. Production builds do not (re)use DLLs

**What is the expected behavior?**
Webpack Production Dynamically Linked Libraries could
- speed up production builds
- provide a versioned bundle for local production build development reproduction
- need a new es2015 module DLL format (which would currently only be reusable for development builds in the Edge browser)

## Encapsulation of Development & Angular dependencies
**If this is a feature request, what is motivation or use case for changing the behavior?**
As I'm trying different starter projects for webpack2 with angular, trying to refactor them a bit, to create a cluster of dependencies, making an extended framework for reuse in multiple projects. 
I'm wondering, if those DLL bundles, that speed up development build time, could be reused long term for production builds, which still want to get tree-shaken. That's why I would expect a new DLL bundle export format to be needed, which can be tree shaken.

Maintaining a full development environment for Angular with Wepack over multiple product projects with shared codebase requires control over most of the npm dependencies: Angular, most specifically, is overlapping both production and development dependencies.

I want to provide these development artifacts, generated for every project:
- Shared Webpack Installation 
- Webpack Configuration (prod, dev, production-debug)
- Webpack DLL for development build
- Webpack Production DLL
as Angular versioning has to be synced over all of these

Any opinions on this are welcome!

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
I don't think platform information is relevant here.
Node 6 LTS
Wepack 2
Chrome, Firefox, Edge
Windows
Looking for Visual Studio 2017 integration too

**Comment by sokra** [comment]
You are talking about a library-target and not about a DLL format.

DLLs can not be tree-shaking by definition because they are built outside of the app build.
Note that DLLs can be used in production and developement. It's not a development feature.

ESM libraryTarget is on the roadmap, but require Scope Hoisting to be efficient.

**Comment by Phoscur** [comment]
Can you please explain how Wepack DLLs can be used in production? I could only come up with this related issue:
http://stackoverflow.com/questions/42337180/is-it-safe-to-use-webpack-dllplugin-in-production

**Comment by Phoscur** [comment]
And yes @sokra, I will study the "library target" some more for split off component project builds

**Comment by sokra** [comment]
There is no difference in usage of DLLs in production and development.

Compared to a vendor chunk:

* Faster app build
* Better caching (stays longer equal)
* No tree shaking
* Slightly bigger app
