### ISSUE TITLE
webpack 2.3 source map breaks ES2015 package imports

### ISSUE THREAD

**Issue by billyjanitsch** [webpack/webpack#4563]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

In webpack 2.3.1, enabling `devtool: 'cheap-module-source-map'` causes imports of ES2015-built packages to return empty files.

**If the current behavior is a bug, please provide the steps to reproduce.**

See [this minimal example repo](https://github.com/billyjanitsch/webpack-imports).

In short: d3-time [includes an ES build](https://github.com/d3/d3-time/blob/master/package.json#L19). `import {timeYear} from 'd3-time'` incorrectly yields `undefined` in webpack 2.3.1, but correctly yields an object in webpack 2.2.1. Removing `devtool: 'cheap-module-source-map'` fixes the problem.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

node 7.7.1, npm 4.4.4, webpack 2.3.1, macOS 10.12.3

**Comment by sokra** [comment]
Should be fixed. Could you try to update webpack-sources to the latest version?

**Comment by billyjanitsch** [comment]
Yeah, lgtm 🙃
