### ISSUE TITLE
error:'output.filename' is required, either in config file or as --output-filename"

### ISSUE THREAD

**Issue by zzzgit** [webpack/webpack#4569]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
![image](https://cloud.githubusercontent.com/assets/1060733/24318815/e800acb6-1146-11e7-83a2-7f859be2b025.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
1.config webpack like this:
![image](https://cloud.githubusercontent.com/assets/1060733/24318824/0f026930-1147-11e7-9ae2-cd157d9c5932.png)

2.run webpack
3.it got an error like above
**What is the expected behavior?**
no error thrown
**If this is a feature request, what is motivation or use case for changing the behavior?**
no

**Comment by zzzgit** [comment]
`exports` not `exxport`,that is the reason.

**Comment by monkindey** [comment]
Thanks. yeah, you are right. But I also think that we maybe can give a `the config not a object` error rather than the `'output.filename' is required`, because I always doubt whether my output.filename misspelling. Any thought about it?

**Comment by baruchvlz** [comment]
@monkindey What about this scenario:

```
const rootPath = path.join(__dirname, '..');

module.exports = {
  entry: {
    main: `${rootPath}/src/main.js`,
  },

  output: {
    filename: '[name].[hash].js',
    path: `${rootPath}/dist`,
  },

  module: {
    rules: [
      {
        test: /\.js$/,
        use: {
          loader: ['babel-loader']
        }
      }
    ]
  },
};
```

Getting OP's error using webpack 3.5.4.

**Comment by monkindey** [comment]
hi, @baruchvlz ,what error did you get?

**Comment by baruchvlz** [comment]
The same one OP got.` 'output.filename' is required, either in config file or as --output-filename`

**Comment by monkindey** [comment]
oh, I didn't find out something wrong with your config as above, maybe you can provide reproduction repo.

**Comment by avalan4e57** [comment]
Why the feature is closed if the problem isn't solved? I have just the same problem. And yes I do use  `exports` with `s` at the end

**Comment by avalan4e57** [comment]
I don't know why, but it suddenly just appeared to be working. It's a kind of magic I suppose. Or, maybe the reason is that I forgot to save something and then did it unconsciously. A big loss in solving the problem..

**Comment by harshan89** [comment]
I do this all the time

**Comment by Siyanda-Mzam** [comment]
@akshayjai1 Why does having two `module.exports` in one config file causes an error?

**Comment by ankitanaik471** [comment]
i got same error 'output.filename' is required, either in config file or as --output-filename. how to resolve this

**Comment by akshayjai1** [comment]
@Siyanda-Mzam It must be how, ES6+ has defined it, in my guess

**Comment by AyushAgrawal104** [comment]
I find the same error and I resolved it but still confuse why its work

module.exports.config = {
.....
}

gives error

var config = {
...}

module.exports = config;

works

**Comment by deepakbhattmits** [comment]
i got same error 'output.filename' is required, either in config file or as --output-filename. how to resolve this
