### ISSUE TITLE
CommonsChunkPlugin: Split common async chunk issue

### ISSUE THREAD

**Issue by gyandeeps** [webpack/webpack#4572]
**Do you want to request a *feature* or report a *bug*?**

Not sure

**What is the current behavior?**

common shared code between 2 async code path doesnt create a common js code file rather it repeats the code in 2 bundles.

**What is the expected behavior?**

Expect to put the common code in common file.

Above questions are answered and better explained in readme of the reproducible case repo: https://github.com/gyandeeps/webpack-split-dynamic-common

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Webpack: 2.2.0
OS: Windows
NodeJS: 6 and 7

**Comment by timse** [comment]
first of all your example repo does not compile :). Webpack even tells you you can not use a filename if you use the async option.

Also you should not use a name here, as there is no chunk with the name specified.

If you dont do this, and just use:

```
new webpack.optimize.CommonsChunkPlugin({
                async: true,
                children: true
            })
```

everything works as expected :)

**Comment by timse** [comment]
if you are happy with the answer, please close the ticket :

**Comment by gyandeeps** [comment]
>first of all your example repo does not compile :). Webpack even tells you you can not use a filename if you use the async option.

First of all my issue says I am using webpack `2.2.0`. It compiles fine with that version and there is no error/warning message. With `2.3.1`, it started throwing filename error (so technically its a breaking change between these 2 version).

By removing, `name` prop it works as i expect. But if i include name then it doesnt work. I am not sure it would be good to let user know when they use `name` while using `async` and `children` prop.  

Thanks for help. Feel free to close if above suggestion doesn't make sense.
