### ISSUE TITLE
 configuration.output.filename: A relative path is expected

### ISSUE THREAD

**Issue by linaspasv** [webpack/webpack#4575]
**What is the current behavior?**

When trying to run my webpack configuration, getting the following error in the console:
``` 
configuration.output.filename: A relative path is expected. However the provided value "/js/[name].js" is an absolute path! Please use output.path to specify absolute path and output.filename for the file name.
```
**If the current behavior is a bug, please provide the steps to reproduce.**

This is my webpack configuration:

```js

const webpack = require('webpack');

const ExtractTextPlugin = require('extract-text-webpack-plugin');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const ProgressBarPlugin = require('progress-bar-webpack-plugin');
const BowerResolvePlugin = require('bower-resolve-webpack-plugin');

const sourcePath = __dirname + '/resources/assets';
const destinationPath = __dirname + '/public/dist';
const bowerPackagesPath = __dirname + '/bower_components';
const nodePackagesPath = __dirname + '/node_modules';

// detect if webpack bundle is being processed in a production or development env
var isDevelopmentMode = !(require('yargs').argv.p || false);

module.exports = {
    context: sourcePath + '/js/app',
    entry: {
        front: sourcePath + '/front.entry',
        admin: sourcePath + '/admin.entry'
    },
    output: {
        path: destinationPath,
        filename: '/js/[name].js'
    },

    module: {
        rules: [
            {
                test: /\.css$/,
                use: ExtractTextPlugin.extract({
                    fallback: 'style-loader',
                    use: 'css-loader'
                }),
            },
            {
                test: /\.less$/,
                use: ExtractTextPlugin.extract({
                    fallback: 'style-loader',
                    use: 'css-loader!less-loader'
                }),
            },
            {
                test: /\.(scss|sass)$/,
                use: ExtractTextPlugin.extract({
                    fallback: 'style-loader',
                    use: 'css-loader!sass-loader'
                }),
            },
            {
                test: /\.(png|jpg|gif)$/,
                loader: 'file-loader',
                query: {
                    name: '/images/[name].[ext]'
                }
            },
            {
                test: /\.(ttf|eot|svg|woff(2)?)(\?v=[0-9]\.[0-9]\.[0-9])?(\?[a-z0-9]+)?$/,
                loader: 'file-loader',
                query: {
                    name: '/fonts/[name].[ext]'
                }
            },
            {
                test: /\.jsx$/,
                loader: 'babel',
                include: [],
                query: {
                    cacheDirectory: true, //important for performance
                    plugins: ['transform-regenerator'],
                    presets: ['react', 'es2015', 'stage-0']
                }
            },
            /**
             * expose jQuery to a global namespace
             */
            {
                test: /jquery\.js$/,
                use: [
                    {
                        loader: 'expose-loader',
                        query: 'jQuery'
                    },
                    {
                        loader: 'expose-loader',
                        query: '$'
                    }
                ]
            }
        ]
    },

    plugins: [
        new webpack.DefinePlugin({
            __DEBUG__: JSON.stringify(isDevelopmentMode)
        }),

        new ProgressBarPlugin(),

        new ExtractTextPlugin('/css/[name].css'),

        new CopyWebpackPlugin([
            { from: sourcePath + '/images', to: '/images', toType: 'dir', force: true }
        ]),

        new webpack.ProvidePlugin({
            $: 'jquery',
            jQuery: 'jquery',
            'window.jQuery': 'jquery'
        }),

        new webpack.optimize.CommonsChunkPlugin({
            name: 'common',
            filename: '/js/common.js'
        })
    ],

    resolve: {
        plugins: [
            new BowerResolvePlugin()
        ],

        modules: [
            sourcePath + '/js',
            sourcePath + '/js/vendor',
            bowerPackagesPath,
            nodePackagesPath
        ],
        descriptionFiles: ['bower.json', 'package.json'],
        mainFields: ['main'],
        alias: {
            app: sourcePath + '/js/app',
            system: sourcePath + '/js/system',
            components: sourcePath + '/js/system/components',
            plugins: sourcePath + '/js/system/plugins',
            utils: sourcePath + '/js/system/utils',
            style: sourcePath + '/css',

            '__bower': bowerPackagesPath,
            '__node' : nodePackagesPath
        }
    },

    cache: true
}

```

**What is the expected behavior?**

Specified configuration was working correctly in webpack v2.2.1 . Once the ``output.filename`` attribute is being changed to relative path, the generated files structure looks like:

![image](https://cloud.githubusercontent.com/assets/1407067/24332490/1cb765a8-1250-11e7-99e2-36f8b3186a9e.png)

Originally ``admin.js``, ``extension.js`` and ``front.js`` files were placed in the ``js`` directory (using webpack v2.2.1). 

[documentation source](https://webpack.js.org/configuration/output/#output-filename): ``Note this option is called filename but you are still allowed to something like "js/[name]/bundle.js" to create a folder structure.``

I am not sure why feature of ``create a folder structure`` was dropped and relative name for ``output.filename`` is being forced in webpack v2.3 . Please re-consider to bring the feature back or add an additional parameter where we could specify an additional subdirectory for output js files only because ``output.path`` alone is being used by other plugins while resolving output paths for css, fonts, etc...

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.** node v6.2.2, webpack v2.3.2

**Comment by timse** [comment]
well `filename: '/js/[name].js'` is an absolute path, make it `js/[name].js'` and all should be fine

**Comment by linaspasv** [comment]
@timse thank you! My bad, looks like I was using this incorrectly.

**Comment by rrfaria** [comment]
@linaspasv could you share your webpack and basic config with us?
I'm trying use extract text plugin but it doesn't export my css correctly...

**Comment by linaspasv** [comment]
@rrfaria here is how my configuration looks like - [see gist](https://gist.github.com/linaspasv/c757119d23ab708e646f0384f2f5354d) . What's the problem for you?

**Comment by rrfaria** [comment]
@linaspasv I solved the issue with the extract plugin hahah .. but now I can't use bower hahaha ...
I tried use your code but I can't see how to setup like I want.
My structure is 
bower_components
--pe-icon-7-filled
-----css
-----fonts
dist
--assets
-----fonts
-----css
----------bundle.css
-----js
----------bundle.js

src
---components

I would like to copy pe-icon css to dist folder into bundle.css  and fonts to font folder and also if I use any bower dependence with js I insert into bundle.js.

I tried use your code with file-loader and copy images and fonts to dist but I think it is wrong.


Look My webpack config:

`const HtmlWebpackPlugin = require('html-webpack-plugin');
const ExtractTextPlugin = require("extract-text-webpack-plugin");
const webpack = require('webpack');
const autoprefixer = require('autoprefixer');
const path = require("path");
const BowerResolvePlugin = require('bower-resolve-webpack-plugin');

let isProd = process.env.NODE_ENV === 'production'; //true or false



module.exports = {
    entry: {
        app: './src/index.js'
    },
    output: {
        path: path.resolve(__dirname, "dist/"),
        filename: 'assets/js/[name].bundle.js'
    },
    module: {
        rules: [
            {
                test: /\.(css|scss|sass)$/,
                use: ExtractTextPlugin.extract({
                    fallback: 'style-loader',
                    use: 'css-loader!sass-loader!postcss-loader'
                }),
            },
            {
                test: /\.jsx?$/,
                exclude: /(node_modules|bower_components)/,
                use: 'babel-loader'
            },
            {
                test: /\.(png|jpg|gif)$/,
                loader: 'file-loader',
                query: {
                    name: '/images/[name].[ext]'
                }
            },
            {
                test: /\.(ttf|eot|svg|woff(2)?)(\?v=[0-9]\.[0-9]\.[0-9])?(\?[a-z0-9]+)?$/,
                loader: 'file-loader',
                query: {
                    name: '/fonts/[name].[ext]'
                }
            },
            {
                test: /\.pug$/,
                use: ['pug-loader']
            }
        ]
    },
    devServer: {
        contentBase: path.join(__dirname, "dist"),
        compress: true,
        hot: true,
        open: true
    },
    plugins: [
        new HtmlWebpackPlugin({
            title: 'Crud',
            hash: true,
            template: './src/index.pug'
        }),
        new ExtractTextPlugin('assets/css/[name].css'),
        new webpack.HotModuleReplacementPlugin(),
        new webpack.LoaderOptionsPlugin({
            options: {
                postcss: [autoprefixer]
            }
        })
    ]
};`

**Comment by linaspasv** [comment]
@rrfaria where is your resolve configuration?

**Comment by TopDev10** [comment]
> well `filename: '/js/[name].js'` is an absolute path, make it `js/[name].js'` and all should be fine

It's working fine but I have an issue when I deployed to AWS EC2 instance.
I am gonna use deep routing for email verification but at that time I am getting an issue because of js folder directory.
I need to get js file from build/name.js but I am getting build/[pages, auth, ect]/name.js.
Can you let me know how can I resolve this issue?
Thank you

**Comment by selfdestruction** [comment]
@topdev10 output.publicPath: '/' - work for me
