### ISSUE TITLE
[BUG] require as a variable

### ISSUE THREAD

**Issue by fazouane-marouane** [webpack/webpack#4576]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When build the following
```js
var r = require, e = 'extensions'
console.log(r[e])
```

yields
```js
//...
(function(module, exports, __webpack_require__) {

var require;var r = require, e = 'extensions'
console.log(!(function webpackMissingModule() { var e = new Error("Cannot find module \".\""); e.code = 'MODULE_NOT_FOUND'; throw e; }())[e])
})
//...
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Compile with the following
```js
{
target: 'node',
  node: {
    __dirname: false,
    __filename: false,
  }
}
```

**What is the expected behavior?**
It should yield something along the lines of
```js
//...
(function(module, exports, __webpack_require__) {

var r = __webpack_require__, e = 'extensions'
console.log(r[e])
})
//...
```

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
OSX, node v7.7.4, webpack 2.3.2

**Comment by michael-ciniawsky** [comment]
First of all, why ? 😛 webpack uses 'enhanced-require', so maybe `var r = require('enhanced-require')`? Also `require` in node context is always available, there is not need to assign it to variable, does this even work without webpack e.g 

```js 
var r = require 

module.exports = r
```

?

**Comment by fazouane-marouane** [comment]
Hi

I came across this code while trying to bundle npm with webpack. There was certain patterns apparently where some requires are used as variables (for example to achieve lazy requires).

**Comment by timse** [comment]
- the second one just passes it as a reference what shouldnt be a problem, just that webpack wouldnt be able to bundle things anymore, which is not planned as lazy-req is supposed to be for node in the first place, if I see that correctly.
- in the first example the indirection just makes absolutely no sense. (at least i cant see any)

while this doesnt really help, i am not sure if webpack allows for indirections to require, as after all it needs to be able to statically analyze what resources are required to be able to resolve them.

**Comment by sokra** [comment]
Sorry such code is not supported. webpack requires statically analyseable usage of require. `require.extensions` is also not supported. Check the webpack output, which will tell you that for your code.

**Comment by fazouane-marouane** [comment]
@sokra I believe that you closed the issue a little too fast.
I'm not asking for a support for a more advanced analysis of `require` usages. The links I gave were to explain the weirness of the code I gave in the example.

I cale across many situations where a simple `require` used as variable was replace by a webpackMissingModule while it shouldn't.

**Comment by fazouane-marouane** [comment]
@timse Actually, it's the same issue with the second example (lazy-req). It's replaced with `!(function webpackMissingModule() ... `

`require` as variable seems to be used in many packages in the npm community. I think that the code generated by webpack when I bundle a lib that references such code it yields an incorrect output.

@sokra This issue needs to be reopened so we can have views of other members, and preferably someone familiar with how requires are implemented in webpack.
