### ISSUE TITLE
DLL modules do not work with hot reload

### ISSUE THREAD

**Issue by wmertens** [webpack/webpack#4581]
**Do you want to request a *feature* or report a *bug*?**

Unexpected behavior / maybe bug / maybe feature request

**What is the current behavior?**

I'm using DLLPlugin to pre-bundle all my node modules used in the frontend code. I noticed issues with hot reload, and it turns out that modules that have e.g. `if (!module.hot)` get emitted as `if (true)`.

I tried getting around this by using the DefinePlugin to replace `module.hot` with `(0, module.hot)`, which does sidestep that issue, but when loading the module, it turns out that `module.hot` is indeed undefined for these modules. This means that e.g. react-hot-loader can't be included in the dll bundle.

**If the current behavior is a bug, please provide the steps to reproduce.**

I am willing to do this if the above description is not clear.

**What is the expected behavior?**

Either:
* DLLPlugin build should warn when encountering `module.hot`, so that users know to exclude the module from the bundle, or
* Bundle code should also get `module.hot` set, so they can participate in the process (even if they themselves will never change)

**If this is a feature request, what is motivation or use case for changing the behavior?**

I spent quite some time finding out why this didn't work and I would like to help future me and other users avoid this problem, using one of the two expected behaviors.

It would be nicest if it would just work (option 2), so that dll bundles could be auto-generated based on a first build. Using DLL bundles makes my builds 2.5x faster, which is a big deal for me.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Webpack v2.3.2

**Comment by sokra** [comment]
I don't understand your description.

`module.hot` is replaced with `true` or `false` depending on the activation of HMR in the DllPlugin. As you usually don't have HMR enabled in the Dll bundle `if(!module.hot)` is replaced with `if(true)` in your case.

Activation of HMR is separate for each compilation. So you could have HMR enabled in your app bundle and disabled in your dll bundle.

Could you include a repo where you demonstrate the problem?

**Comment by wmertens** [comment]
Aha! Adding `new webpack.HotModuleReplacementPlugin()` to the dll build plugins indeed fixes my problem, so I suppose this is not an issue.

I will check if I can adjust the DllPlugin documentation so that that is clear.
