### ISSUE TITLE
Dynamically adding 'import' to Angular 4 TypeScript source code causes very very slow build (10x slower)

### ISSUE THREAD

**Issue by feng-xiao** [webpack/webpack#4582]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
Extremely slow build when dynamically adding 'import' (e.g. import { Component } from '@angular/core';)

**Project size**
TypeScript files: 255
Html files: 26
Scss files: 44

**Adding 'import' dynamically**

> 576661ms building modules
> 75ms sealing
> 0ms optimizing
> 0ms basic module optimization
> 37ms module optimization
> 2ms advanced module optimization
> 13ms basic chunk optimization
> 0ms chunk optimization
> 1ms advanced chunk optimization
> 0ms module and chunk tree optimization
> 25ms module reviving
> 17ms module order optimization
> 23ms module id optimization
> 22ms chunk reviving
> 1ms chunk order optimization
> 92ms chunk id optimization
> 64ms hashing
> 5ms module assets processing
> 149ms chunk assets processing
> 208ms additional chunk assets processing
> 1ms recording
> 6ms additional asset processing
> 292ms chunk asset optimization
>  94% asset optimization
> [at-loader] Checking started in a separate process...
> 
> [at-loader] Checking finished with 151 errors
> 1191ms asset optimization
> 918ms emitting
> Hash: 6b931d385d4dbac813af
> Version: webpack 2.3.2
> Time: 580267ms

**Without adding 'import' dynamically**
> 38328ms building modules
> 113ms sealing
> 0ms optimizing
> 0ms basic module optimization
> 70ms module optimization
> 10ms advanced module optimization
> 106ms basic chunk optimization
> 1ms chunk optimization
> 3ms advanced chunk optimization
> 4ms module and chunk tree optimization
> 123ms module reviving
> 59ms module order optimization
> 7ms module id optimization
> 48ms chunk reviving
> 1ms chunk order optimization
> 47ms chunk id optimization
> 61ms hashing
> 8ms module assets processing
> 283ms chunk assets processing
> 237ms additional chunk assets processing
> 1ms recording
> 0ms additional asset processing
> 224ms chunk asset optimization
>  94% asset optimization
> [at-loader] Checking started in a separate process...
> 
> [at-loader] Checking finished with 93 errors
> 1296ms asset optimization
> 904ms emitting
> Hash: 5a81fdcff97e66a09525
> Version: webpack 2.3.2
> Time: 42163ms

**If the current behavior is a bug, please provide the steps to reproduce.**
**Using custom loader - ts-loader**
```javascript
"use strict";
module.exports = function (source, sourceMap) {
    // Not cacheable during unit tests;
    this.cacheable && this.cacheable();

    source = `import { Component } from '@angular/core';\nconsole.log(Component);\n` + source;

    // Support for tests
    if (this.callback) {
        this.callback(null, source, sourceMap)
    } else {
        return source;
    }
}
```

**Config files**
[webpack.common.zip](https://github.com/webpack/webpack/files/872995/webpack.common.zip)

**What is the expected behavior?**
No much differences on build speed

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Webpack: 2.3.2
OS: Windows 10
Node: 6.9.4

**Comment by timse** [comment]
can you add the files as a gist or link to an example repo instead of a zip file?:)

**Comment by feng-xiao** [comment]
I uploaded the sample code to [https://github.com/feng-xiao/webpack-build-issues](https://github.com/feng-xiao/webpack-build-issues). You just need to change [line 7](https://github.com/feng-xiao/webpack-build-issues/blob/master/config/ts-loader.js#L7) by commenting or uncommenting it to see the build time differences.

With this sample application from Angular Class template it's about 5 times slower, in my own angular 4 template, it's **10** times slower.

**Build command**
```npm
npm run build:dev
```
**Without commenting**
> 38072ms building modules
> 22ms sealing
> 0ms optimizing
> 0ms basic module optimization
> 15ms module optimization
> 11ms advanced module optimization
> 18ms basic chunk optimization
> 1ms chunk optimization
> 2ms advanced chunk optimization
> 1ms module and chunk tree optimization
> 5ms module reviving
> 1ms module order optimization
> 1ms module id optimization
> 6ms chunk reviving
> 0ms chunk order optimization
> 5ms chunk id optimization
> 24ms hashing
> 0ms module assets processing
> 33ms chunk assets processing
> 37ms additional chunk assets processing
> 0ms recording
> 1ms additional asset processing
> 76ms chunk asset optimization
>  94% asset optimization
> [at-loader] Checking started in a separate process...
> 
> [at-loader] Ok, 0.647 sec.
> 877ms asset optimization
> 498ms emitting
> Hash: b7ef9ceeaee86e8f686f
> Version: webpack 2.3.1
> Time: 47407ms

**Commenting line 7**
> 9624ms building modules
> 16ms sealing
> 1ms optimizing
> 1ms basic module optimization
> 13ms module optimization
> 5ms advanced module optimization
> 4ms basic chunk optimization
> 0ms chunk optimization
> 1ms advanced chunk optimization
> 0ms module and chunk tree optimization
> 7ms module reviving
> 1ms module order optimization
> 2ms module id optimization
> 5ms chunk reviving
> 0ms chunk order optimization
> 8ms chunk id optimization
> 12ms hashing
> 0ms module assets processing
> 30ms chunk assets processing
> 77ms additional chunk assets processing
> 22ms recording
> 16ms additional asset processing
> 73ms chunk asset optimization
>  94% asset optimization
> [at-loader] Checking started in a separate process...
> 
> [at-loader] Ok, 0.687 sec.
> 882ms asset optimization
> 589ms emitting
> Hash: e8e2cff100adc14db6c9
> Version: webpack 2.3.1
> Time: 11914ms

**Comment by sokra** [comment]
The repo is too complex. Could you strip it down to a minimal repo?

**Comment by feng-xiao** [comment]
Hi Sokra,

I already removed files as much as I can

**Comment by feng-xiao** [comment]
any updates on this issues? it's very annoying. Basically, I have a custom loader to do typescript code generation, this problem gave me headache now. I need to think how to get around it... It would be much appreciated if someone can fix it ASAP
