### ISSUE TITLE
acorn 4.0.12 looks like it may have broken webpack

### ISSUE THREAD

**Issue by johnnyreilly** [webpack/webpack#4585]
Just wanted to give you a heads up.  I've found that pinning to 4.0.11 seems to work.

https://github.com/ternjs/acorn/issues/527

**Comment by roderik** [comment]
Thx m8!

**Comment by johnnyreilly** [comment]
Yup - confirmed.  See linked issue for details.

**Comment by bebraw** [comment]
Based on the issue this should be fixed. Can you confirm and close?
