### ISSUE TITLE
module order in bundle

### ISSUE THREAD

**Issue by MikailBag** [webpack/webpack#4588]
**Do you want to request a *feature* or report a *bug*?** feature

**What is the current behavior?**
webpack orders modules in bundle, as he wants

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

I think it would be better to put all modules from `node_modules` and etc. into the end of bundle.

**If this is a feature request, what is motivation or use case for changing the behavior?**

Now, when I get some error and lool at bundle.js, I see mix of my code and some dependencies, so
I need to scroll to find module I need

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Windows 10, 32bit
webpack 1.13.2
nodejs 7.7.2

**Comment by sokra** [comment]
It sort modules in a way so it generates the smallest module ids for often used modules.

**Comment by sokra** [comment]
We can add a sorting mode with a better DX.

**Comment by MikailBag** [comment]
Current way is good for production.
But in development suggested sorting will be more comfortable.
It won't break API.

**Comment by sokra** [comment]
In dev you probably use a devtool anyway which shows the modules in the devtool tree.

**Comment by sokra** [comment]
Not worth it.
