### ISSUE TITLE
--watch-poll not working on Docker under Windows 10

### ISSUE THREAD

**Issue by raphaklaus** [webpack/webpack#4594]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Since Windows can't use inotify to send changes from the host to the guest, I use polling technique.

Using this configuration in webpack.config.js
```javascript
  watch: true,
    watchOptions: {
      poll: 1000
  }
```

the polling **works normally**. But if I use this same configuration in the command line, like:

`webpack --watch --watch-poll 100` or just `webpack --watch --watch-poll`

It doesn't rebuild after file change.

**If the current behavior is a bug, please provide the steps to reproduce.**
Create a node application using webpack to bundle everything.

**What is the expected behavior?**

Expect webpack rebuild with the new files.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Webpack: 1.14
Docker: 17.03.1-ce
Windows 10 using Hyper-V.
Node: 6.9.2

**Comment by bebraw** [comment]
Can you confirm the behavior in webpack 2?

**Comment by raphaklaus** [comment]
@bebraw I've made some tests. This situation occurs in webpack 2 too. For versions 1 and 2 this issue only happens if you export the webpack config module as an array (plus using Docker on Windows), like this:

```javascript
module.exports = [{
    entry: {
        app: './app/app.js'
    },
    output: {
        filename: '[hash].bundle.js',
        path: path.join(__dirname, 'dist')
    },
    module: {
        loaders: [
            {
                test: /\.js$/,
                loader: 'babel-loader',
                exclude: /node_modules/,
            }
        ]
    }
}];
```

If you export it as an object, the problem doesn't occur. 
Since webpack supports array bundling, watch-poll argument should work.

**Comment by flip111** [comment]
I have the same problem with CentOS on a NFS share.

**Comment by Lutger** [comment]
@raphaklaus: thanks for this tip, enabled me to solve the same problem I had. What also works is using `--config-name` with `--watch-poll.` Seems that having multiple configurations is the condition under which this bug occurs. This is a bit simpler if you don't want to alter the webpack.config.js.

>  If you export it as an object, the problem doesn't occur.
> Since webpack supports array bundling, watch-poll argument should work.
