### ISSUE TITLE
Failure to load split chunks should provide a failure reason or code in the resulting error

### ISSUE THREAD

**Issue by rsolomon** [webpack/webpack#4595]
**Do you want to request a *feature* or report a *bug*?**

Request a feature

**What is the current behavior?**

When a chunk (created via code splitting) fails to load, it's not possible to distinguish if the failure was caused by a timeout or a 404.

**If the current behavior is a bug, please provide the steps to reproduce.**

N/A

**What is the expected behavior?**

It would be great if the `error` object (The one that currently contains the message, `/^Loading chunk \d failed.$/`, would also provide the code that caused the failure. Ex: 404, 504, etc.

**If this is a feature request, what is motivation or use case for changing the behavior?**

It's important to handle the failure based on why the failure happened. If the chunk is actually missing, obviously there's something wrong that should be handled. If the chunk simply failed to load due to a timeout, it may be of less concern due to the user's connection.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Latest Webpack (`2.3.2`) using `System.import`.

**Comment by rsolomon** [comment]
As an aside, it looks like this can be taken care of here:  https://github.com/webpack/webpack/blob/01c06debeeb1099218466ccda7c663d25076fe74/lib/JsonpMainTemplatePlugin.js

By either changing line 65 to handle onerror separately, or to check for the existence of an error object in `onScriptComplete`.

**Comment by rsolomon** [comment]
Aannd... upon further inspection, it seems impossible to get an error code out of a <script> tag async loading failure. I'll leave this open if someone else is more creative than me, but it seems like this one might be impossible.

**Comment by sokra** [comment]
It's pretty difficult to make it consistent cross-browser. Probably require all lot runtime code which is expensive for all users... 

If somebody want to tackle this in a PR:  I would expect minimal runtime code even if this would not work for all browser perfectly. Timeout should be able to be detected easily as we own it. see lib/JsonpMainTemplatePlugin.js

**Comment by jdbevan** [comment]
Actually, having had a quick read through [the spec](https://www.w3.org/TR/html5/scripting-1.html), I think I'm wrong - the onload event should execute AFTER the chunk has executed...
