### ISSUE TITLE
Can't import jsdom with Webpack 2

### ISSUE THREAD

**Issue by astashov** [webpack/webpack#4596]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When you try to import `jsdom`, it compiles with warnings, and when you try to run the compiled output, it breaks with the exception `Error: Cannot find module "."`. Only happens with Webpack 2.3.2/beta, not Webpack 1.13.1, so I created the issue here, and not in jsdom.

**If the current behavior is a bug, please provide the steps to reproduce.**

Create a project with those files:

`package.json`
```json
{
  "devDependencies": {
    "jsdom": "^9.12.0",
    "webpack": "^2.3.2"
  },
  "scripts": {
    "build": "webpack --config webpack.config.js"
  }
}
```

`webpack.config.js`
```js
module.exports = {
  entry: "./input.js",
  target: "node",
  output: {filename: "output.js"},
};
```

`input.js`
```js
import * as jsdom from "jsdom";
console.log(jsdom);
```

Run:

```bash
$ npm install
$ npm run build
$ node ./output.js
```

It will crash.

```
const syncWorkerFile = !(function webpackMissingModule() { var e = new Error("Cannot find module \".\""); e.code = 'MODULE_NOT_FOUND'; throw e; }()).resolve ? /*require.resolve*/(545) : null;
                                                                                                                                       ^

Error: Cannot find module "."
    at webpackMissingModule (/Users/anton/projects/mixbook/jsdom-ex/output.js:98684:68)
    at Object.<anonymous> (/Users/anton/projects/mixbook/jsdom-ex/output.js:98684:146)
    at __webpack_require__ (/Users/anton/projects/mixbook/jsdom-ex/output.js:20:30)
    at Object.module.exports (/Users/anton/projects/mixbook/jsdom-ex/output.js:75859:30)
    at __webpack_require__ (/Users/anton/projects/mixbook/jsdom-ex/output.js:20:30)
    at Object.<anonymous> (/Users/anton/projects/mixbook/jsdom-ex/output.js:33601:16)
    at __webpack_require__ (/Users/anton/projects/mixbook/jsdom-ex/output.js:20:30)
    at Object.module.exports (/Users/anton/projects/mixbook/jsdom-ex/output.js:50784:64)
    at __webpack_require__ (/Users/anton/projects/mixbook/jsdom-ex/output.js:20:30)
    at /Users/anton/projects/mixbook/jsdom-ex/output.js:66:18
```

It seems like it happens because at this line:
https://github.com/tmpvar/jsdom/blob/e0687795456773058755867e53c487aa3fe80e5b/lib/jsdom/living/xmlhttprequest.js#L20

it replaces `require.resolve` with `!(function webpackMissingModule() { var e = new Error("Cannot find module \".\""); e.code = 'MODULE_NOT_FOUND'; throw e; }()).resolve`.

In webpack 1.13.1, it used to replace it to something like `__webpack_require__(389).resolve`, and it worked fine.

**What is the expected behavior?**

The program outputs the imported `jsdom` library, and doesn't crash. 

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Tried both on Webpack 2.3.2 and Beta. Node version is v7.6.0. OS: macOS 10.12.3

**Comment by sokra** [comment]
We can fix this. Parser should evaluate `resolve.resolve` as truthy value.

**Comment by coreyleelarson** [comment]
My team is eagerly waiting for this fix in order to complete our migration to Webpack 2.

**Comment by coreyleelarson** [comment]
Any updates on this issue?

**Comment by polco** [comment]
+1

**Comment by coreyleelarson** [comment]
So, after countless hours of investigation(and pounding my head against the keyboard in trial and error), it appears this was broken with the removal of dynamic imports by default.

You need to set ```module.unknownContextRegExp``` and ```module.exprContextRegExp``` in your Webpack config to enable dynamic imports.

**webpack.config.babel.js**
```
export default {
    ...
    module: {
        exprContextRegExp: /^\.\/.*$/,
        unknownContextRegExp: /^\.\/.*$/,
        rules: [...]
    }
    ...
};
```

## Summary (For those who care)

**lib/WebpackOptionsDefaulter.js** v2+
```
this.set("module.exprContextRegExp", false);
this.set("module.unknownContextRegExp", false);
```

**lib/WebpackOptionsDefaulter.js** v1.15
```
this.set("module.exprContextRegExp",  /^\.\/.*$/);
this.set("module.unknownContextRegExp", /^\.\/.*$/);
```

These values are passed around in many places and used during dependency creation, which ultimately causes the ```require.resolve``` expression to yield no dependencies, thus falling into the following else block:

**lib/dependencies/ContextDependencyTemplateAsRequireCall.js**
```
const containsDeps = dep.module && dep.module.dependencies && dep.module.dependencies.length > 0;

const isAsync = dep.module && dep.module.async;
if(dep.module && (isAsync || containsDeps)) {
    if(dep.valueRange) {
        if(Array.isArray(dep.replaces)) {
            for(let i = 0; i < dep.replaces.length; i++) {
                const rep = dep.replaces[i];
                 source.replace(rep.range[0], rep.range[1] - 1, rep.value);
            }
        }
        source.replace(dep.valueRange[1], dep.range[1] - 1, ")");
        source.replace(dep.range[0], dep.valueRange[0] - 1, "__webpack_require__(" + comment + JSON.stringify(dep.module.id) + ")(" + (typeof dep.prepend === "string" ? JSON.stringify(dep.prepend) : "") + "");
    } else {
        source.replace(dep.range[0], dep.range[1] - 1, "__webpack_require__(" + comment + JSON.stringify(dep.module.id) + ")");
    }
} else {
    const content = require("./WebpackMissingModule").module(dep.request);
    source.replace(dep.range[0], dep.range[1] - 1, content);
}
```

Not sure exactly what the actual solution is at this point in time, but I managed to bypass this bug for now.

Nevertheless, I hope this helps someone.

¯\\_(ツ)_/¯

**Comment by polco** [comment]
Works for me! Many thanks for the time spent. I hope both your head and keyboard are fine ;)

**Comment by lnwdr** [comment]
Tried the suggestions here and also [this one](https://github.com/webpack/webpack/issues/718#issuecomment-84936730).

The only thing that eventually worked to trick web pack into ignoring the jsdom require was this:
```js
const jsdom = eval("require('jsdom')");
```

**Comment by SerenityInAllThings** [comment]
@coreyleelarson This helped me greatly. Many thanks.
