### ISSUE TITLE
cannot evaluate module correctly when using CommonsChunkPlugins in node

### ISSUE THREAD

**Issue by luckydrq** [webpack/webpack#4604]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

I'm investigating ssr in `node` using modules built by webpack. If i use `CommonsChunkPlugin` then the entry module cannot be evaluated correctly. If i remove the `CommonsChunkPlugin` section, it works as expected.

**If the current behavior is a bug, please provide the steps to reproduce.**
[This demo](https://github.com/luckydrq/webpack-ssr-demo) shows exactly the case.

**What is the expected behavior?**
Can evaluate entry correctly in `node`
**If this is a feature request, what is motivation or use case for changing the behavior?**
none

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

- Operating System: OSX Sierra 10.12.3
- node: 6.9.4 
- webpack: 2.3.2

**Comment by sokra** [comment]
CommonsChunkPlugin only works with `web` target.

**Comment by sokra** [comment]
The CommonsChunkPlugin is a caching optimization for the browser. Caching is not relevant in node.js context.

If you are using the CommonsChunkPlugin for build performance, consider the DllPlugin in this case.

**Comment by bebraw** [comment]
Maybe CommonsChunkPlugin should fail hard if some other target than `web` is used.

**Comment by luckydrq** [comment]
@sokra thanks! BTW, why DLLPlugin is not mentioned in [webpack2 plugin list](https://webpack.js.org/plugins/) ?

**Comment by bebraw** [comment]
@luckydrq Looks like an oversight. Can you [open an issue](https://github.com/webpack/webpack.js.org/issues) at the doc site?

**Comment by luckydrq** [comment]
>@luckydrq Looks like an oversight. Can you open an issue at the doc site?

@bebraw thanks. There is already a related [issue](https://github.com/webpack/webpack.js.org/issues/944)
