### ISSUE TITLE
compiler.options.watch is undefined with webpack-dev-server

### ISSUE THREAD

**Issue by smelukov** [webpack/webpack#4606]
**Do you want to request a *feature* or report a *bug*?**

Report a bug.

**What is the current behavior?**

`compiler.options.watch` is `undefined` with webpack-dev-server

**If the current behavior is a bug, please provide the steps to reproduce.**

We have a simple plugin:
```js
SomePlugin.prototype.apply = function(compiler) {
    compiler.plugin('watch-run', function(watching, done) {
        console.log(compiler.options.watch);
        done();
    });
};
```

If build with `webpack -w` then `compiler.options.watch` is `true`
But if build with `webpack-dev-server` then `compiler.options.watch` is `undefined`

**What is the expected behavior?**

`compiler.options.watch` always is `true` in `watch-run`

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

OSX 10.12.1
node 6.9.5
webpack-dev-server 2.4.2
webpack 2.3.2

**Comment by sokra** [comment]
This is expected. `watch` is not part of the options object for the compiler. It's part of the `webpack` node.js fasade. You can watch without setting `watch: true`

Example:

``` js
const compiler = webpack({ ... });
compiler.watch(...);
```

**Comment by smelukov** [comment]
I meant another ... I just want to detect is the compiler in watch mode or not.
For example:
```js
SomePlugin.prototype.apply = function(compiler) {
    compiler.plugin(['run', 'watch-run'], function(watching, done) {
        // >>> detecting watch mode <<<
        done();
    });
};
```
