### ISSUE TITLE
Webpack can not handle a folder named `*`

### ISSUE THREAD

**Issue by Timer** [webpack/webpack#4611]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When bundling a file within a directory named `*`, the path is not escaped in the original location comment. This causes the comment to be terminated early.

**If the current behavior is a bug, please provide the steps to reproduce.**
Simply bundle anything in a path with `/*/`

**What is the expected behavior?**
Paths should be escaped.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

This is webpack 1.x.

![](https://puu.sh/v4GAr/38e7b909ae.png)

x-ref: https://github.com/facebookincubator/create-react-app/issues/1915

**Comment by TheLarkInn** [comment]
Can you reproduce this on webpack 2?

**Comment by sokra** [comment]
Why did you name your folder `*`?

**Comment by Timer** [comment]
@TheLarkInn yes this reproduces on webpack 2:
```
__webpack_require__(/*! /Users/joe/Desktop/*/test/node_modules/react-dev-utils/webpackHotDevClient.js */129);
__webpack_require__(/*! /Users/joe/Desktop/*/test/node_modules/react-scripts/config/polyfills.js */130);
__webpack_require__(/*! /Users/joe/Desktop/*/test/node_modules/react-dev-utils/crashOverlay.js */128);
module.exports = __webpack_require__(/*! /Users/joe/Desktop/*/test/src/index.js */127);
```

@sokra I did not name my folder `*`, this is a bug report filed on behalf of a CRA user. 😅

**Comment by sokra** [comment]
I guess `*` as foldername breaks more stuff... Watching is probably broken too.

Nevertheless we can fix the comment issue by adding a space between `*/` or something else.

**Comment by Timer** [comment]
I doubt any user will *ever* run into this again, having a star as a folder name seems so rare ...
Since other libs might interpret it as globbing, maybe a warning / fail to start would be more appropriate.

`Due to underlying dependency restrictions, please do not use directories which contain the * character.`
