### ISSUE TITLE
Lookup translate  

### ISSUE THREAD

**Issue by saadaouad** [webpack/webpack#4618]
Please any recommendation about using a lookup translate with a loader of webpack, and any type of file should be use it (`.po`, `.mo` or `.js`) ?
I'm working with React library

**Comment by sokra** [comment]
Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md).
