### ISSUE TITLE
Create Outreach Communities

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack#4619]
Successfully we were able to help start and perpetuate a community for China for webpack. It's been extremely successful and we continue to see their traffic as 2nd to USA in docs, and repo page visitors. 

However [it came to our attention on twitter](https://twitter.com/truth2_truth/status/848567713798791169) that we could maybe be doing more. I'm all for equality as access to opportunity, and furthermore since all of us have little to no bandwidth, we'd want to find a group of developers/advocates who are willing to lead the initiative. First step would simply be to create the guidelines for how one would approach this outreach. 

https://twitter.com/truth2_truth/status/848567713798791169 <== this twitter account nominated themselves to write this guideline, or seems to have experience in it.

**Comment by IAMtheIAM** [comment]
It sounds cool. However what does an outreach community do/accomplish? You mean trying to help more people learn about webpack?

**Comment by dantesolis** [comment]
@TheLarkInn  I would like to take this if no one has taken it, but as @IAMtheIAM pointed out what should  an "outreach community do/accomplish" ? Thanks

**Comment by TheLarkInn** [comment]
Ahhh sorry for the delay on this. Okay so this is about working to help elevate the opportunities of those who might not feel they are worthy or equipped to contribute, and to help them on board.

What's great is that if you have less experience it's a really great way to learn through teaching. I'll try and follow up with this some more.

**Comment by Acemanu412** [comment]
Is this still active? I would love to know more about this, if it is still an issue!

**Comment by TheG0dfath3r** [comment]
I think we can do the same for India as well, I can see many Indian developers around.
