### ISSUE TITLE
HMR incorrectly accepts change in module

### ISSUE THREAD

**Issue by ricmatsui** [webpack/webpack#4621]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When editing a module that is part of a multi entry along with other entries which have a common module and a commons chunk, HMR will accept the change even though the edited module and its parents do not have an accept handler.

**If the current behavior is a bug, please provide the steps to reproduce.**

I have created a test case which reproduces the issue along with a proposed fix here: https://github.com/webpack/webpack/pull/4617/commits/fb93f626e45b444630bed0e7cd880d7a6cfe266d

**What is the expected behavior?**

The entry for the module should be marked as unaccepted by HMR.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Node.js 6.6.0
Webpack 2.3.2 & master
Ubuntu 16.04

**Comment by timse** [comment]
ill close this, as the fix is merged :)
