### ISSUE TITLE
UglifyJSPlugin adding an extra source map for the entire file?

### ISSUE THREAD

**Issue by AlexanderOMara** [webpack/webpack#4623]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When using the built-in UglifyJSPlugin and source maps, a strange extra source map entry is added with the contents of the whole file. This extra source map is not added when not using UglifyJSPlugin, and is not added when created by the uglifyjs command line utility.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Download [Github Gist](https://gist.github.com/AlexanderOMara/5ecff5344bc3c85afff2c67cd14757d3) or create these files:

package.json:
```json
{
  "name": "webpack-sourcemap-extra",
  "version": "1.0.0",
  "description": "example",
  "scripts": {
    "make": "npm run webpack && npm run uglify",
    "webpack": "webpack",
    "uglify": "uglifyjs -c -m --in-source-map dist/example.js.map dist/example.js --source-map dist/example.ugly.js.map -o dist/example.ugly.js"
  },
  "author": "example",
  "license": "example",
  "devDependencies": {
    "uglify-js": "^2.8.20",
    "uglifyjs-webpack-plugin": "^0.4.0",
    "webpack": "^2.3.2"
  }
}
```

webpack.config.js:
```js
const UglifyJSPlugin = require('webpack').optimize.UglifyJsPlugin;

module.exports = [
	{
		entry: './example',
		output: {
			filename: 'example.js',
			path: __dirname + '/dist'
		},
		devtool: 'source-map'
	},
	{
		entry: './example',
		output: {
			filename: 'example.min.js',
			path: __dirname + '/dist'
		},
		devtool: 'source-map',
		plugins: [
			new UglifyJSPlugin({
				sourceMap: true
			})
		]
	}
];
```

 example.js:
```js
console.log('testing123');
```

2. Run:

```bash
npm install
npm run make
```

3. Compare the 3 `dist/*.map` files. The one created by webpack with UglifyJSPlugin, `example.min.js.map`, will have an extra `"source"` entry for `"webpack:///example.min.js"` which actually contains a non-minified copy of the entire bundle under `"sourcesContent"`.

**What is the expected behavior?**

Expected not to have this extra source map, as there is already individual source maps for the parts of the bundle, so having one for the whole file seems redundant and may confuse software trying to use the map. Using the uglifyjs command line utility does not add this extra map, so I suspect this is caused by this plugin somehow.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Node: v7.7.2
Webpack: 2.3.2 (also tried beta, same result)
Uglifyjs: 2.8.21
OS: macOS Sierra 10.12.4

**Comment by Vanuan** [comment]
I think that extra source map actually helps to debug issues with it.
There are actually 2 sourcemaps:
1. ES6 code -> ES5 code (babel transformation)
2. ES5 code -> uglified ES5 code
