### ISSUE TITLE
multiple usage of the CommonsChunkPlugin, only first works

### ISSUE THREAD

**Issue by PavelPolyakov** [webpack/webpack#4638]
**Do you want to request a *feature* or report a *bug*?**
It's either a bug or the [documentation](https://webpack.js.org/plugins/commons-chunk-plugin/) is not clear.

**What is the current behavior?**
Trying to solve this [stackoverflow question](http://stackoverflow.com/questions/43210152/webpack-2-splitting-libraries-vendor-and-app-into-different-files?noredirect=1#comment73503668_43210152).
I use `webpack.optimize.CommonsChunkPlugin` twice, but only first `minChunks` function is applied.

**If the current behavior is a bug, please provide the steps to reproduce.**
Here is the example repo:
https://github.com/PavelPolyakov/webpack-react-bundles/tree/feature/advanced-CommonsChunkPlugin

**What is the expected behavior?**
With [this code](https://github.com/PavelPolyakov/webpack-react-bundles/blob/feature/advanced-CommonsChunkPlugin/conf/webpack.production.config.js):
```javascript
plugins: [
        // put lodash and moment in one file
        new webpack.optimize.CommonsChunkPlugin({
            name: 'lodash+moment',
            minChunks: function (module) {
                let result = module.context && _.reduce(['lodash', 'moment'], (result, record) => result || _(module.context).includes(`node_modules/${record}`), false);
                if (result) {
                    console.log('+++', module.context);
                }
                return result;
            }
        }),
        // put everything else in the other file
        new webpack.optimize.CommonsChunkPlugin({
            name: 'vendor',
            minChunks: function (module) {
                let result = module.context && _(module.context).includes(`node_modules`) && !_.reduce(['lodash', 'moment'], (result, record) => result || _(module.context).includes(`node_modules/${record}`), false);
                console.log('attempt', module.context);
                if (result) {
                    console.log('---', module.context);
                }
                return result;
            }
        })
    ]
```

I want to filter `lodash` and `moment` to one file and the other `node_modules` to the other.

I also did another attempt, like the one from the documentation:
https://github.com/webpack/webpack/tree/master/examples/multiple-commons-chunks

Here is the attempt, it doesn't work:
https://github.com/PavelPolyakov/webpack-react-bundles/blob/feature/separate-entries/conf/webpack.production.config.js

I would appreciate any suggestion how to solve my issue. PR into the example repository is appreciated the most :)

Webpack version 2.2.1.

Regards,

**Comment by timse** [comment]
can you make your config less complicated?
there are tons of unnecessary abstractions and the whole thing is extremly big.
also it seams as if your filter function in the second commonsChunkPlugin doesnt work, what is that thing supposed to do anyways? is that a very complicated way to check something is a node module and not lodash/moment?

also, why do you want to have lodash/moment in a commonschunk but add them both as entry points?

**Comment by PavelPolyakov** [comment]
@timse 
Thanks for looking into.

The repository is a clone of the real project where I removed all the react stuff, so it looks this way.  I'll try to put more minimalistic copy today.

> also it seams as if your filter function in the second commonsChunkPlugin doesnt work, what is that thing supposed to do anyways? is that a very complicated way to check something is a node module and not lodash/moment?

you are right, in the first `CommonsChunkPlugin` usage I try to filter out lodash + moment, in the 2nd I try to filter out everything which is not lodash or moment. But the values which are getting there - are actually only `lodash` and `moment` entries.

> also, why do you want to have lodash/moment in a commonschunk but add them both as entry points?

Because I found that approach in this example:
https://github.com/webpack/webpack/tree/master/examples/multiple-commons-chunks

Regards,

**Comment by timse** [comment]
try to remove the `lodash`, `moment` entries.
also can you check if `module.context` is really what you are after? not `module.request`?
that yielded quite ok results for me, also remove uglifyjs to check if it looks like what you are looking for.

**Comment by PavelPolyakov** [comment]
> try to remove the `lodash`, `moment` entries.
I tried that as well.

Here is the clean version:
https://github.com/PavelPolyakov/webpack-react-bundles/tree/feature/clean-version

webpack config: https://github.com/PavelPolyakov/webpack-react-bundles/blob/feature/clean-version/webpack.config.js 

After you do the build, we receive the next:
1. `lodash+moment.bundle.js` // lodash + moment indeed
2. `vendor.bundle.js` // empty
3. `app.bundle.js` // application + all the modules from node_modules (expected to be in vendor)

**Comment by PavelPolyakov** [comment]
@timse 
does new clean example allow you to understand is it a bug or expected behavior and if it's possible to receive the desired result in some way?

Regards,

**Comment by timse** [comment]
what is this supposed to be besides being unreadable? `module.context && _(module.context).includes(`node_modules`) && !_.reduce(['lodash', 'moment'], (result, record) => result || _(module.context).includes(`node_modules/${record}`), false);`

**Comment by timse** [comment]
use
```
new webpack.optimize.CommonsChunkPlugin({
    name: 'vendor',
    minChunks: (m) => /node_modules/.test(m.context)
}),
new webpack.optimize.CommonsChunkPlugin({
    name: 'lodash+moment',
    minChunks: (m) => /node_modules\/(?:lodash|moment)/.test(m.context)
}),
```

should do what you want

**Comment by PavelPolyakov** [comment]
@timse 
Thanks, indeed my example mess was producing the wrong result for some reason.

Very good that your example works. 

I would be very happy if you explain me the extended example doesn't work:
```javascript
new webpack.optimize.CommonsChunkPlugin({
            name: 'vendor',
            minChunks: (m) => /node_modules/.test(m.context)
        }),
        new webpack.optimize.CommonsChunkPlugin({
            name: 'lodash',
            minChunks: (m) => /node_modules\/(?:lodash)/.test(m.context)
        }),
        new webpack.optimize.CommonsChunkPlugin({
            name: 'moment',
            minChunks: (m) => /node_modules\/(?:moment)/.test(m.context)
        })
```

in which I want to have `lodash`, `moment` and `vendor` separately.

What I receive is:
![image](https://cloud.githubusercontent.com/assets/839290/24805941/8cbe7b2c-1bb3-11e7-96c5-b56392a78cad.png)

Where `moment` one is empty (moment was put into the `vendor` bundle).
Actually this setup was my initial question on stackoverflow.

Here is the branch: https://github.com/PavelPolyakov/webpack-react-bundles/tree/feature/clean-version-lodash-moment-separately .

Thank you in advance.

Regards,

**Comment by sokra** [comment]
The CommonsChunkPlugin selects only entry chunks. After the CCP processed the modules it creates a new entry chunk (the commons chunk) and make the used chunks non-entries.

So when using multiple CCPs they only extract modules from the last CCP.

So this will work:

``` js
       new webpack.optimize.CommonsChunkPlugin({
            name: 'vendor',
            minChunks: (m) => /node_modules/.test(m.context)
        }),
        new webpack.optimize.CommonsChunkPlugin({
            name: 'lodash',
            minChunks: (m) => /node_modules\/(?:lodash|moment)/.test(m.context)
        }),
        new webpack.optimize.CommonsChunkPlugin({
            name: 'moment',
            minChunks: (m) => /node_modules\/(?:moment)/.test(m.context)
        })
```

**Comment by PavelPolyakov** [comment]
@sokra 
Thank you very much, now all makes sense.

For those who'll find this issue, here is the complete webpack config which correctly separates app, the modules you like, vendor file and manifest:

```javascript
const webpack = require('webpack');
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const _ = require('lodash');

module.exports = {
    entry: {
        app: ['./app/index.js']
    },
    output: {
        filename: '[name].bundle.js',
        sourceMapFilename: '[name].bundle.map',
        path: path.resolve(__dirname, './dist')
    },
    devServer: {
        port: 3001,
        contentBase: path.resolve(__dirname, './dist'),
        historyApiFallback: true
    },
    module: {
        rules: [
            {
                test: /\.(js|jsx)$/,
                exclude: /node_modules/,
                use: [
                    {
                        loader: 'babel-loader',
                        options: {
                            presets: [['es2015', { 'modules': false }], 'react'],
                            plugins: ['transform-async-to-generator',
                                'transform-decorators-legacy',
                                'transform-runtime',
                                'react-html-attrs',
                                'react-hot-loader/babel'],
                        }
                    }
                ]
            },
            {
                test: /\.css/,
                use: ['style-loader', 'css-loader', 'postcss-loader']
            },
            {
                test: /\.(eot|svg|ttf|woff|woff2|gif|jpg|png)$/,
                use: 'file-loader'
            }
        ]
    },
    plugins: [
        new HtmlWebpackPlugin({
            template: './index.html',
            inject: "body"
        }),
        new webpack.optimize.UglifyJsPlugin({
            minimize: true,
            compress: {
                warnings: true
            }
        }),
        new webpack.optimize.CommonsChunkPlugin({
            name: 'vendor',
            minChunks: (m) => /node_modules/.test(m.context)
        }),
        new webpack.optimize.CommonsChunkPlugin({
            name: 'lodash',
            minChunks: (m) => /node_modules\/(?:lodash|moment)/.test(m.context)
        }),
        new webpack.optimize.CommonsChunkPlugin({
            name: 'moment',
            minChunks: (m) => /node_modules\/(?:moment)/.test(m.context)
        }),
        new webpack.optimize.CommonsChunkPlugin({
            name: "manifest",
            minChunks: Infinity
        })
    ],
    resolve: {
        extensions: ['.js', '.jsx']
    },
    devtool: 'source-map'
}
```

Regards,

**Comment by ismay** [comment]
I've been looking all over trying to figure out how to do this. I've been trying to split my vendor bundle into more manageable chunks, and this is exactly what I need. I'd add a PR to add this to the docs/examples if I had time but I don't have any at the moment.

Still, as an end user I think that this is something that quite difficult to figure out on your own with just the docs and examples. I'd highly recommend adding this specific usecase to the docs.

**Comment by carlosagsmendes** [comment]
@PavelPolyakov do you have a working repo with the final version that you can share? Thanks in advance

**Comment by Ricardo-Marques** [comment]
@sokra What if I wanted to split our project into multiple vendor chunks, for example,
```
  'vendor/other': [
      'twix',
      'axios',
      'js-base64',
      'promise'
    ]
    ,'vendor/reactCommon': [
      'react-router',
      'react-router-dom'
      ,'react-dom'
      ,'material-ui'
    ]
    ,'vendor/react': [
      'react'
    ]
    ,'vendor/reduxCommon': [
      'react-redux'
      ,'redux-thunk'
      ,'redux-form'
    ]
    ,'vendor/redux': [
      'redux'
    ]
```
where keys are the output file name and each item in the array is a dependency to be potentially included, if the entry point depends on it. Is there a way to accomplish this without aggregating all of the vendors into a giant array and removing dependency names from the `minChunks` test in each subsequent CommonsChunkPlugin constructor? Would that way even work?

**Comment by carlosagsmendes** [comment]
@Ricardo-Marques, did you try the solution presented by @PavelPolyakov?

Something like the following, considering the ´reduxCommon´ and ´reactCommon´ bundles from your example:

```
new webpack.optimize.CommonsChunkPlugin({
    name: 'reduxCommon',
    minChunks: (m) => /node_modules\/(?:react-redux|redux-thunk|redux-form)/.test(m.context)
}),
new webpack.optimize.CommonsChunkPlugin({
    name: 'reactCommon',
    minChunks: (m) => /node_modules\/(?:react-router|react-router-dom|react-dom|material-ui)/.test(m.context)
}),
new webpack.optimize.CommonsChunkPlugin({
    name: "manifest",
    minChunks: Infinity
})
```
Actually, I'm struggling with something related to your scenario. But in my case, I want to build the bundles and get webpack to load them asynchronously when I request one or more of the items from each bundle. 

For example, when importing `react-redux` I want webpack to load `reduxCommon`, without having to include the bundle manually in the page.

I'm using the `async` property for the bundle name: 

```
new webpack.optimize.CommonsChunkPlugin({
    async: 'reduxCommon',
    minChunks: (m) => /node_modules\/(?:react-redux|redux-thunk|redux-form)/.test(m.context)
}),
new webpack.optimize.CommonsChunkPlugin({
    async: 'reactCommon',
    minChunks: (m) => /node_modules\/(?:react-router|react-router-dom|react-dom|material-ui)/.test(m.context)
}),
new webpack.optimize.CommonsChunkPlugin({
    name: "manifest",
    minChunks: Infinity
})
```

**Comment by Ricardo-Marques** [comment]
@carlosagsmendes According to what @sokra said
>... when using multiple CCPs they only extract modules from the last CCP.

Which means the first `reduxCommon` chunk would include `react-redux`, `redux-thunk` and `redux-form` and the second bundle would include nothing, since none of those dependencies occur in the reduxCommon chunk.

**Comment by carlosagsmendes** [comment]
Thanks for the clarification @Ricardo-Marques and for sharing your solution.

Do you know how I can use the bundles in an async fashion, with the behaviour that I described above? 

"For example, when importing react-redux, I want webpack to load the reduxCommon bundle, without having to include the bundle manually on the page."

**Comment by Ricardo-Marques** [comment]
@carlosagsmendes Not sure. What I can say is that changing the 'name' property to 'async' instead simply puts all of the vendor code in the main `app.js` file and does not create any vendor bundles.

**Comment by Ricardo-Marques** [comment]
@carlosagsmendes follow up on this. I figured out how to split the async modules.

This method has the advantage of creating a separate async module only if no synchronous chunks require it.

```javascript
// commonsChunkPluggins.js
const webpack = require('webpack');
const path = require('path');
const flatten = require('lodash.flatten');
let bundleConfig = require('./bundle.config');

// for each bundle create a <bundle-name>.dependencies file with all the dependencies
// for every module in that vendor file
Object.keys(bundleConfig.bundles).forEach(bundleFile => {
  bundleConfig.bundles[`${bundleFile}.dependencies`] = bundleConfig.bundles[bundleFile].reduce(
    (childDependencySum, dependency) => childDependencySum.concat(getChildDependencies(dependency)),
    []
  )
});

// CommonsChunkPlugin works top to bottom. If I have 2 CommonsChunkPlugin invocations, the second one
// will only extract common chunks from the first one.
// This means that we have to start by checking every dependency that we need and get progressively
// more granular until each file ends up with just the dependencies it should have
const allDependencies = Object.keys(bundleConfig.bundles).reduce((dependencySum, bundleFile) => {
  return dependencySum.concat(bundleConfig.bundles[bundleFile]);
}, []);
let currentlyChecking = allDependencies;
let lastParsedVendorFile = null;

module.exports = (
  [
    // dependencies being required that don't match any single bundle config
    // will end up in this file. You can then make a decision of wether to leave it
    // or include it in some specific bundle
    new webpack.optimize.CommonsChunkPlugin({
      name: 'vendor/non-determined',
      minChunks: (module) => {
        return module.resource && /node_modules/.test(module.resource);
      }
    })
  ]
  .concat(
    flatten(['name', 'async'].map(type => {
      return (
        flatten(Object.keys(bundleConfig.bundles)
          .map((bundleFile, i, bundleFiles) => {
            return new webpack.optimize.CommonsChunkPlugin({
              [type]: bundleFile + (type === 'async' ? '.async' : ''),
              minChunks: (module) => {
                if (i === 0) {
                  currentlyChecking = allDependencies;
                  lastParsedVendorFile = bundleFile;
                }

                if (lastParsedVendorFile !== bundleFile) {
                  // if we've moved on to parsing the next bundle, start looking for only dependencies that should not
                  // remain in any of the previous bundles
                  const numberOfDependenciesOnPreviousVendorFile = bundleConfig.bundles[bundleFiles[i - 1]].length;
                  currentlyChecking = currentlyChecking.slice(numberOfDependenciesOnPreviousVendorFile);
                  lastParsedVendorFile = bundleFile;
                }


                return (
                  module.resource && currentlyChecking.some(dependency => module.resource.indexOf(`node_modules/${dependency}/`) > -1)
                );
              }
            })
          }))
      );
    }))
  )
  // create a separate runtime manifest for async chunks
  // webpack needs these manifests to map require/import statements to bundles
  .concat([
    new webpack.optimize.CommonsChunkPlugin({
      async: 'async-manifest'
    })
  ])
  // create a separate runtime manifest for sync chunks
  .concat([
    new webpack.optimize.CommonsChunkPlugin({
      name: 'manifest'
    })
  ])
);

function getChildDependencies (dependency) {
  return Object.keys(
    require(path.resolve(`./node_modules/${dependency}/package.json`)).dependencies || {}
  );
}
```

**Comment by maciej-gurban** [comment]
@sokra 
> So when using multiple CCPs they only extract modules from the last CCP.

Why not let the user be in control of deciding what modules go into what chunk? It would require a bit more coding on our end, but would be so much less counter-intuitive.

One could then specify in any order:
``` 
{ name: 'foo',
  minChunks: // match packages staring with foo-
}, {
 name: 'bar',
  minChunks: // match packages staring with bar-
}
```
And everything that would not be picked up by either CommonsChunkPlugin plugin instance, would get bundled into the main bundle file.

**Comment by carlosagsmendes** [comment]
@Ricardo-Marques thank you so much for sharing this. 

I was trying something similar but was missing the need to create the `separate runtime manifest for async chunks`

I will give it a try tomorrow.

Best,

Carlos

**Comment by carlosagsmendes** [comment]
Hi @Ricardo-Marques, just want to say thanks for the code you've shared.

I'm still struggling with _"This method has the advantage of creating a separate async module only if no synchronous chunks require it."_  since I would rather be in control depending on the situation but I guess this is the way that WebPack works. 

Best regards,
Carlos

**Comment by JacobWay** [comment]
This solution is far too weird, not configurable.

**Comment by Ricardo-Marques** [comment]
Agreed. Not so much a solution as it is a hacky way around the problem.

**Comment by mmiller42** [comment]
Let's say that my app has a "core" which contains some application framework source code and one or more "sites." When the page is rendered, the core bundle is always loaded, then one of the "site" bundles.

If a module is imported by core, it should stay in the core chunk. If a module is imported in both a core and at least one site, it also should be added to the core chunk so the site doesn't have to have a second copy of the same module. However, sites are mutually exclusive, so if two sites import the same module, I don't want them to end up in the core chunk -- it's okay to have those modules be duplicated in both site chunks.

I think I managed to get all that working via:

```js
const coreEntryPath = path.resolve(__dirname, 'src', 'core.js');
const isModuleImportedByCore = module => {
    let currentModule = module;
    do {
        if (currentModule.resource === coreEntryPath) {
            return true;
        }
        currentModule = currentModule.issuer;
    } while (currentModule);
    return false;
};

module.exports = {
  entry: {
    core: './src/core',
    site1: './src/sites/site-1',
    site2: './src/sites/site-2'
  },
  plugins: [
    new CommonsChunkPlugin({
      name: 'core',
      minChunks: module => isModuleImportedByCore(module)
    })
  ]
};
```

And because of how `CommonsChunkPlugin` works as described above, I can also extract `node_modules` from the core chunk and put them into a vendor chunk:

```js
  plugins: [
    new CommonsChunkPlugin({
      name: 'core',
      minChunks: module => isModuleImportedByCore(module)
    }),
    new CommonsChunkPlugin({
      name: 'core~vendor',
      minChunks: module => /\/node_modules\//.test(module.context)
    })
  ]
```

Unfortunately, I *cannot* make vendor modules for each site chunk, because a successive `CommonsChunkPlugin` instance can *only* process modules from the previous instance of `CommonsChunkPlugin`. This means I don't think there is a way to create a `site1~vendor` commons chunk that contains all modules imported by site 1 that exist in `node_modules` and are not also imported by the core.

Does anyone know of any workarounds for this?

**Comment by maciej-gurban** [comment]
You could use Yarn workspaces and a package.json each `site`. Doing yarn
install would then resolve the dependencies the way you'd expect. Your
webpack config and imports would remain unchanged
