### ISSUE TITLE
 Cannot find module 'D:\nodejs\node_modules\webpack\bin\webpack.js'

### ISSUE THREAD

**Issue by dogLin** [webpack/webpack#4642]
When I run 'webpack' in cmd the result tell me ' Cannot find module 'D:\nodejs\node_modules\webpack\bin\webpack.js'',but i get correct result when i run it in Git Bash.
I have set the NODE_PATH and install webpack global
![Markdown](http://i1.piimg.com/587193/302b3ddcbdb357e7.png)
![Markdown](http://i2.muimg.com/587193/2ac81877b7627ef8.png)
![Markdown](http://i1.piimg.com/587193/185d53a784dc1d25.png)

**Comment by sokra** [comment]
Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md).
