### ISSUE TITLE
FR: Additional substitution variable for "project path"

### ISSUE THREAD

**Issue by aight8** [webpack/webpack#4648]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the expected behavior?**
see: https://webpack.js.org/configuration/output/#output-filename
There are many variables you can use, additionally it were nice there were a variable for the absolute path to the **FOLDER** of the used web pack config. like: ```[projectpath]```

If no config is given (called webpack programatically) then an error should be thrown.
If a javascript file is given (which generates the config), the variable is related to this js file's folder.

Other ideas: ```[context]``` - to just substitute the path of the given context path. If context is not given, throw an exception.

---

HOWEVER, currently it vary very which of the following syntax you can use on the different config properties, it should be more consistent. So in most cases the ```[projectpath]```/```[context]``` variable can be spared.
```
/absolute/path
./relative/path
without/prefix/path
```

I think every type should be allowed whenever it's possible.

**If this is a feature request, what is motivation or use case for changing the behavior?**

- A further step to write plain json webpack configuration.
- Don't require to use the path module all the time.

**Comment by sokra** [comment]
output.filename doesn't accept absolute paths. where do you want to use [context]?
