### ISSUE TITLE
module.loaders potentially not working anymore in webpack 2

### ISSUE THREAD

**Issue by marlon-tucker** [webpack/webpack#4652]
**Do you want to request a *feature* or report a *bug*?**
Potentially a bug, but might be intended behavior.

**What is the current behavior?**
When I define a typescript-loader (either ts-loader or awesome-typescript-loader) under the module.loaders config section, Webpack does not appear to use them in it's pipeline.

**If the current behavior is a bug, please provide the steps to reproduce.**
Steps are detailed [in my SO question here](https://stackoverflow.com/questions/43241404/webpack-typescript-getting-module-parse-failed-why)

**What is the expected behavior?**

The Webpack docs say the module.loaders section should be parsed for backwards compatibility.  

If this is no longer the case, I'll submit issues to the typescript loaders.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, Webpack version and Operating System.**

Webpack: 2.3.3 
Node: 7.8 
OS: Windows 10

**Comment by sokra** [comment]
You can't use both `module.rules` and `module.loaders`.
