### ISSUE TITLE
More Clarity In Docs Needed on Limitations of Dynamic Imports in Webpack 2

### ISSUE THREAD

**Issue by bdwain** [webpack/webpack#4658]
**Do you want to request a *feature* or report a *bug*?**

Request more documentation. I'm happy to make the PR to the docs, but I don't know what to write yet. 

**What is the current behavior?**

[This page in the docs](https://webpack.js.org/guides/code-splitting-import/) only has a quick sentence about how import statements cannot be "fully" dynamic, but can be partly.

>  Keep in mind that import() path cannot be fully dynamic (e.g., import(Math.random())). Rather either completely static (e.g., import('./locale/de.json')) or partially static (e.g., import('./locale/' + language + '.json')).

**What is the expected behavior?**

Ideally the docs would provide details on when and how variable names can be used in import statements.  For example, something like this doesn't work.

```js
export function foo(deps){
  deps.forEach(dep => import(dep).then(doSomething))
}
//usage:
foo(['bar', 'baz']);
```

but this does (according to the docs at least)

```js
import('./locale/' + language + '.json')).
```

it would be helpful if there was more detail about when dynamic import paths are allowed and what parts of them can be dynamic (it seems like the beginning needs to be static?). 

Thanks for the help! I appreciate all of the work you all do on this.

**Comment by bebraw** [comment]
Can you re-open at the [docs repo](https://github.com/webpack/webpack.js.org/issues)? Thanks.

**Comment by bebraw** [comment]
About `import('./locale/' + language + '.json'))`. It sets up a *context* (see `require.context`) internally so that the lookup works against the file system.

**Comment by bdwain** [comment]
yup thank you!

**Comment by sokra** [comment]
@webpack-bot move to webpack/webpack.js.org
