### ISSUE TITLE
[chunkhash] doesn't change if Uglify output changes

### ISSUE THREAD

**Issue by STRML** [webpack/webpack#4659]
> @scinos and I have collaborated on [webpack-plugin-hash-output](https://www.npmjs.com/package/webpack-plugin-hash-output), which is working in our production environment without issues. See the discussion below for more details.

#### Original Ticket

This is a bug affecting long-term caching with CDNs.

During a recent dependency upgrade, webpack's Uglify dependency moved from `2.8.10` to `2.8.25`, which produces slightly different output.

The issue is that `[chunkhash]` doesn't appear to actually hash the final file:

```bash
# Uglify 2.8.25
$ cat 4-c1bcb6390594024c54d3.js | md5
480d9646348a0cca88088c3755c54fd4
$ head -c 100 4-c1bcb6390594024c54d3.js
webpackJsonp([4],{963:function(e,a,n){!function(a,n){e.exports=n()}(0,function(){"use strict";return
```

Now, before the upgrade:

```bash
# Produced using Uglify 2.8.10 - manually appended `-old` to name
$ cat 4-c1bcb6390594024c54d3-old.js | md5
0103f905d3620c8af106ab46b50f9ab9  # Different hash, same chunkhash!
$ head -c 100 4-c1bcb6390594024c54d3-old.js
webpackJsonp([4],{963:function(e,a,n){!function(a,n){e.exports=n()}(this,function(){"use strict";ret
```

Notice the two bundles have the same `[chunkhash]` but different contents; specifically, uglify 2.3.25 uses `(0,function` rather than `(this,function`.

This caused a production application to load an outdated file from a CDN which then did not match subresource integrity and failed to load.

This is Node 6.10.2, Webpack 2.3.3, Uglify versions as above. I was not using `NamedModulesPlugin` or `ChunkManifestPlugin`, but I am using `UglifyJsPlugin` and `CommonsChunkPlugin`.

#### Resolution

The crux of the issue is that [webpack/lib/Compilation.js](https://github.com/webpack/webpack/blob/b2a6085d9684cb8bb3c47cbcb778413844d70d53/lib/Compilation.js#L609) runs hashing *before* optimization, which means that two different-optimized files will have the same hash.

After some work with this issue, I've discovered two major reasons why it's difficult for `[chunkhash]` to actually equal the hash of the file:

1. Appending a `//# sourceMappingURL` changes the hash, but requires the hash to determine the name of the sourceMap file (this is not a huge deal), and
2. Chunking requires the name of the module. For this reason, the main chunk (with the manifest) must be processed after all other files so that its manifest is correct, then optimized, then hashed.

I have a work-in-progress plugin at https://gist.github.com/STRML/a9c393c9b43d726663d212600fd81320

Update: (19/5/2017): If you've read this far, use https://www.npmjs.com/package/webpack-plugin-hash-output which fixes this issue.

**Comment by STRML** [comment]
The issue is in `Compilation.js`, where the has is computed before optimization:

https://github.com/webpack/webpack/blob/b2a6085d9684cb8bb3c47cbcb778413844d70d53/lib/Compilation.js#L609

**Comment by STRML** [comment]
I've completed a plugin that fixes this, that I'll release as a separate module. The only part I don't feel good about is having to use a `process.nextTick` in a synchronous plugin to ensure we run after `SourceMapDevToolPlugin`. But the results are excellent:

```bash
# filename md5
ui/webroot/0-ac07c5d6ef3b11ca0459.js ac07c5d6ef3b11ca0459d76190316c22
ui/webroot/1-41ab7e65353eca3441ec.js 41ab7e65353eca3441ec7fcf6123d7a3
ui/webroot/2-b757fcc6817d22fb140a.js b757fcc6817d22fb140a20509721d367
ui/webroot/3-4149152f6f9ab7e3bf58.js 4149152f6f9ab7e3bf58b90a0b74644d
ui/webroot/4-480d9646348a0cca8808.js 480d9646348a0cca88088c3755c54fd4
ui/webroot/5-4c468892b786373b4bcc.js 4c468892b786373b4bcc207c98507f3d
ui/webroot/6-b7f97cc6c0b65cd210d6.js b7f97cc6c0b65cd210d6e1feec9644a1
ui/webroot/7-76daa157b74c1604efb7.js 76daa157b74c1604efb78e5bc2b9d0c5
ui/webroot/8-b46b94e24e86d8d3276d.js b46b94e24e86d8d3276dc992010fb842
ui/webroot/app-6d51a4a2a7f8528b6fcd.js 6d51a4a2a7f8528b6fcd4c0ed5e548a8
ui/webroot/commons-635bf09b3c02e50f14b3.js 635bf09b3c02e50f14b32bca4bfb2ced
ui/webroot/login-2253baa695045f3ad867.js 2253baa695045f3ad8677b205b887c70
```

Each file is hashing correctly, even with the `sourceMappingURI` comment and uglification.

The plugin: https://gist.github.com/STRML/a9c393c9b43d726663d212600fd81320

**Comment by scinos** [comment]
I wrote https://www.npmjs.com/package/webpack-plugin-hash-output to solve that problem. As your gist, is a plugin that runs at the end of the compilation cycle and computes the hash based on the content of the final content of the chunks.

**Comment by STRML** [comment]
Thanks. I've taken a look but it appears hashes aren't lining up in my application. It may have something to do with source maps as I've mentioned above. I like your solution better than mine, though, so let's work with it moving forward.

**Comment by scinos** [comment]
Wow, many thanks for your contributions @STRML!

**Comment by STRML** [comment]
Just a note to the maintainers that https://www.npmjs.com/package/webpack-plugin-hash-output is working quite well now and we use it in production without issue.

**Comment by jsgoupil** [comment]
Wow... this is a big deal.
I have been using [chunkHash] without this plugin with Angular 2/4 and sometimes all indexes were changed but the hashes stayed exactly the same.

I was debugging why the chunks were loading successfully but the `loadChildren` mechanism in the router was crashing in Angular code.

CDN or no CDN, this is a major issue to me. The patch is the key.

**Comment by z827101859** [comment]
@STRML I use that plugin （webpack-plugin-hash-output）in my project，but it seems dont work。
after that plugin，webpack change hash again。
---------------------------------------------------
webpack version is "3.6.0"

**Comment by constfun** [comment]
This just bit us in production too. A rollback failed as files with different contents looked the same to the CDN. Big deal indeed, anyone using minification and chunking (ie. almost everyone?) is susceptible to this issue.

**Comment by constfun** [comment]
In our case this turned out to be an issue with the `webpack-md5-hash` plugin. See https://github.com/erm0l0v/webpack-md5-hash/issues/7 Pulling the plugin out means pretty much nothing gets cashed, but that's a separate issue and a lesser of two evils. 

I could not reproduce the issue with plain webpack (version 2.4.1 here)

**Comment by evilebottnawi** [comment]
Looks like stale issue. Close due stale. Feel free to open new issue if somebody faces with this problem in `webpack@3` and `webpack@4`. Also i use latest uglify plugin and using long term cache and all works fine. Maybe problem can be in other plugins. Thanks

**Comment by STRML** [comment]
This is still a bug.

To reproduce, simply twiddle `global_defs`, like so:

```js
new UglifyJsPlugin({
  uglifyOptions: {
    compress: {
      global_defs: {
        DEBUG: 'foobarbaz',
      }
    }
  },
}
```

Then compile a module:

```js
console.log(DEBUG);
```

Notice that no matter what you change the value of the global to, the hash of the chunk is the same.

**Comment by rtsao** [comment]
Indeed, I think this issue should be re-opened.

Perhaps an even more obvious example:

Run a two builds:
```js
let one = {
  output: {filename: "[chunkhash].js"},
  optimization: {minimize: true}
};

let two = {
  output: {filename: "[chunkhash].js"},
  optimization: {minimize: true}
};
```
Both builds will output the exact same hashed filenames, even though the content is radically different (i.e. one build is minified, the other is not)

**Comment by montogeek** [comment]
Feel free to open a new issue with a reproducible example.

**Comment by doudounannan** [comment]
> I wrote https://www.npmjs.com/package/webpack-plugin-hash-output to solve that problem. As your gist, is a plugin that runs at the end of the compilation cycle and computes the hash based on the content of the final content of the chunks.

I use your plugin, but it doesn't work, can't change the assets hash.
