### ISSUE TITLE
Option to disable writing output file in error condition

### ISSUE THREAD

**Issue by zachmullen** [webpack/webpack#4660]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

If an error occurs during build, the output file is still written, but it contains an error message.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

I'd love to have an option like `writeOnError: false` that would disable this behavior and cause no output file to be written if an error occurs.

**If this is a feature request, what is motivation or use case for changing the behavior?**

When rebuilding our web code, if an unexpected error occurs, it would be preferable to leave the old version of the bundle in place rather than overwrite it with a new bundle that just displays an error in the browser.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by sokra** [comment]
See NoEmitOnErrorPlugin

**Comment by zachmullen** [comment]
Thanks @sokra !

**Comment by zachmullen** [comment]
For posterity, since this plugin doesn't appear in any documentation I could find, it lives [here](https://github.com/webpack/webpack/blob/master/lib/NoEmitOnErrorsPlugin.js) and the following usage worked for me: `new webpack.NoEmitOnErrorsPlugin()` in the plugins list.
