### ISSUE TITLE
Running webpack's script inside Rails project in Windows 10 x64 doesn't work

### ISSUE THREAD

**Issue by jarrieta86** [webpack/webpack#4661]
**Do you want to request a *feature* or report a *bug*?**

BUG

**What is the current behavior?**

Running webpack's script inside Rails project in Windows 10 x64 doesn't work properly. Same goes for rake webpacker:compile or webpack-watcher. To fix the first issue (bin/webpack) I deleted NODE_PATH=#{NODE_MODULES_PATH} from the exec (line 38)

It seems that the environment must be set before the exec for Windows

**If the current behavior is a bug, please provide the steps to reproduce.**

For first one:
```
$ ./bin/webpack
./bin/webpack:38:in `exec': Invalid argument - NODE_PATH=E:/buk/node_modules E:/buk/node_modules/.bin/webpack --config E:/buk/config/webpack/development.js  (Errno::EINVAL)
        from ./bin/webpack:38:in `block in <main>'
        from ./bin/webpack:37:in `chdir'
        from ./bin/webpack:37:in `<main>'
```

Second one:
```
$ rake webpacker:compile
Webpacker is installed 🎉 🍰
Using E:/buk/config/webpack/paths.yml file for setting up webpack paths
Compiling webpacker assets 🎉
C:/RailsInstaller/Ruby2.3.0/bin/rake: No such file or directory - NODE_ENV=production ./bin/webpack
rake aborted!
NoMethodError: undefined method `success?' for nil:NilClass
```

Third one:
```
$ bin/webpack-watcher
bin/webpack-watcher:9:in `exec': Exec format error - ./webpack --watch --progress --color  (Errno::ENOEXEC)
        from bin/webpack-watcher:9:in `block in <main>'
        from bin/webpack-watcher:8:in `chdir'
        from bin/webpack-watcher:8:in `<main>'
```
Tasks: TOP => webpacker:compile
(See full trace by running task with --trace)

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Node.js version: 7.8
Webpack version:  2.3.2
Windows 10 x64

**Comment by sokra** [comment]
This looks like a problem in the webpacker package.

@webpack-bot move to rails/webpacker
