### ISSUE TITLE
Load webpack 2 external library with dot notation

### ISSUE THREAD

**Issue by todudotivu27** [webpack/webpack#4665]
**Do you want to request a *feature* or report a *bug*?**
I believe this is a feature

**What is the current behavior?**

I have the following webpack 2 config set for an external library:

```
externals: {
    "importnameoflibrary": { root: "library.component" }
    ...
}
```

This attempts to load the following (which doesnt work because of the dot notation:

`root["library.component"]`

**What is the expected behavior?**

What I need it to do is this (which works):

root["library"]["component"] or root.library.component

**If this is a feature request, what is motivation or use case for changing the behavior?**

I need to load items that are in the global scope but are hierarchical in nature.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Node: v5.8.0
Webpack: 2.2.0
OS: Windows 10

**Comment by sokra** [comment]
`{ root: ["library", "component"] }`
