### ISSUE TITLE
require('constants') in webpack@2 requires nodejs native constants

### ISSUE THREAD

**Issue by isqua** [webpack/webpack#4666]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

1. Setup in webpack.config.js `module.resolver: [ path.resolve(__dirname, 'src'), 'node_modules' ]`.
2. Create file `src/constants/index.js` with content, e.g. `module.exports = { SOME_CONST:  SOME_CONST' };`
3. Require this file as `require('constants')`.
4. Get nodejs constants object contains `EEXIST` and `SIGTERM`.

The same with `import`.

**If the current behavior is a bug, please provide the steps to reproduce.**

You may clone [webpack-require-constants](https://github.com/isqua/webpack-require-constants) and do following:

1. `cd webpack2`
2. `npm install`
3. `npm run build`
4. Open public/index.html file.

**What is the expected behavior?**

I’m not really sure is it a bug in webpack2 or webpack1. Webpack1 requires `src/constants`. You can see it in the same repo in directory [webpack1](https://github.com/isqua/webpack-require-constants/tree/master/webpack1).

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

- nodejs v7.1.0
- webpack@2.3.3 — requires nodejs constants
- webpack@1.14.0 — requires `src/constants`
- mac os 10.10.5

**Comment by korve** [comment]
For it resolves to the data in `~/constants-browserify/constants.json`.

```
Hash: cd9ef91edb3ace6bc089
Version: webpack 2.3.3
Time: 104ms
  Asset     Size  Chunks             Chunk Names
main.js  7.33 kB       0  [emitted]  main
   [0] ./src/index.js 72 bytes {0} [built]
   [1] ./~/constants-browserify/constants.json 4.43 kB {0} [built]
   [2] multi ./src/index.js 28 bytes {0} [built]
```

If you use `const consts = require('./constants');` it will work.

**Comment by isqua** [comment]
@korve, show please your section `module.resolver` from webpack config?

> If you use `const consts = require('./constants');` it will work.

Yeah, I know, but I want to use all paths from `src` directory to avoid shit like this `../../../constants`.

**Comment by korve** [comment]
@isqua Oh right, but isn't the problem that webpack is resolving constants to a library inside node_modules?

**Comment by isqua** [comment]
@korve, no, there are no constants library inside node_modules. Try to stat node in interactive mode:
```
node
```
And try to require constants:
```js
const constants = require('constants');
constants;
```
You’ll get the same as in my example.

Try to clone [webpack-require-constants](https://github.com/isqua/webpack-require-constants) and you’ll see the problem. It is pure example of problem, not real project.

I’m not really sure is it a problem of webpack@2 or webpack@1, but the behaviour of these two is different :)

And I expect some people will be surprised, when their react-and-other applications will break because of webpack update.

**Comment by sokra** [comment]
This is expected, as the builtin node.js modules take precedence over the normal modules. `constants` was added as node.js module, so here your are. You can disable this with `node.constants: false` in configuration.

> I’m not really sure is it a problem of webpack@2 or webpack@1, but the behaviour of these two is different :)

> And I expect some people will be surprised, when their react-and-other applications will break because of webpack update (as me)

That's why it's a major version number.

**Comment by oliverbenns** [comment]
I added an alias to the `resolve` object which fixed this:
```
alias: {
    constants: path.resolve(__dirname, 'src/constants'),
},
```
