### ISSUE TITLE
Can't import a chunk from dll

### ISSUE THREAD

**Issue by creage** [webpack/webpack#4676]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
I get an error "Module not found: Error: Can't resolve..." while trying to build my code.

**If the current behavior is a bug, please provide the steps to reproduce.**

Here is a test repo https://github.com/creage/dll-broken

1. npm run build:dll
2. npm run build:app

I have a simple dll [a](https://github.com/creage/dll-broken/blob/master/a.js), importing 2 modules - [b](https://github.com/creage/dll-broken/blob/master/b.js), and [c](https://github.com/creage/dll-broken/blob/master/c.js). Module **b** is imported [directly](https://github.com/creage/dll-broken/blob/master/a.js#L1), while module **c** is [chunked](https://github.com/creage/dll-broken/blob/master/a.js#L10) out. All of these gets build into a dll, using webpack.DllPlugin.

Next, I have a simple [app](https://github.com/creage/dll-broken/blob/master/app.js), consuming this dll we built before, scoped under the **LIB** namespace. [Importing](https://github.com/creage/dll-broken/blob/master/app.js#L1) module **b** from the dll works fine, but [trying to import](https://github.com/creage/dll-broken/blob/master/app.js#L2) module **c** ends up with error:

```Module not found: Error: Can't resolve 'LIB/c' in 'E:\Dev\dll-broken'```

**What is the expected behavior?**
I'd expect all of dll modules to be consumable by my app.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Node 7.8.0
Webpack 2.3.3
Windows 10

P.S. Analyzing manifest.json created by DllPlugin shows no reference to module **c**. But, if you run a method of the dll [which actually consumes that module](https://github.com/creage/dll-broken/blob/master/a.js#L4) - it works fine, meaning that our library is able to load it's chunked part, but for some reason it does not expose it to library consumers, which is unexpected.

**Comment by sokra** [comment]
The dll exposes only modules from the initial chunk. Modules in on-demand chunks are not exposed.

**Comment by creage** [comment]
@sokra I know that now, and was really surprised by that behavior. We have a really big library of code we share with our different projects, and, from performance perspective, we can't ship whole library as initial chunk - we do a lot of code splitting, and load the stuff on-demand. And, I can't really understand why can't we have our chunked modules exposed as initials do? Dll has all of knowledge about it's chunks, so why can't it just provide a facade around them, and make available for consumers as well?

**Comment by creage** [comment]
@sokra I've updated the repo with more interesting scenarios. I figured out, that calling a "loader" function from the initial chunk, is possible by Dll consumers, which puzzles me even more!

I've added a ["loader" method](https://github.com/creage/dll-broken/blob/master/b.js#L7) into the initial Dll chunk, which returns a Promise, resolving with the [require-d chunked dependency](https://github.com/creage/dll-broken/blob/master/b.js#L13). Later, in my app, I [call that method](https://github.com/creage/dll-broken/blob/master/app.js#L6), and successfully consume chunked out module.

So, it seems, that technically it is very possible to "expose" chunked modules, but requires some wrapper around. It's OK for some small number of chunks, but when you have a hundreds of chunks (we have more than 600) - it becomes a challenge, adding a lot of redundant, manual complexity, which **should** be handled by webpack automatically, I believe.

**Comment by niieani** [comment]
I was about to start implementing DLL in our setup, but (fortunately) I've read this first... As I understand, this basically makes DLLs useless when most of the code is "hidden" behind an async chunk (doesn't load upfront)? For large apps, this is a must-have.

**Comment by creage** [comment]
@sokra any progress on this issue? Or, maybe ideas on how can we workaround the lack of async chunks in the manifest? As currently we have to inject these async chunks into the main entry just for the reason that __sometimes someone might need them__. This blows our initial chunk with a good number of MBs our application __does not need__ to start.

**Comment by evilebottnawi** [comment]
Sorry for delay, problem still exists?

**Comment by creage** [comment]
@evilebottnawi it still does. I'm looking forward for Federated modules coming in webpack 5, so this issue might become obsolete.
