### ISSUE TITLE
JSON wrapper fails - $JSON.stringify.apply is not a function

### ISSUE THREAD

**Issue by pritok** [webpack/webpack#4677]
**Do you want to request a *feature* or report a *bug*?**

Report a bug.

**What is the current behavior?**

When using JSON.stringify on a webpack bundle it throws the exception $JSON.stringify.apply is not a function. Fails building for node targets. It's something about the way JSON is wrapped into $JSON, because when I use eval('JSON').stringify then I can successfully use JSON features. Tested in Node 6 and 7. 

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

I expect to be able to use JSON normally.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by pritok** [comment]
Hi Tobias,

Thanks for answering. Sure. It happens to me with this code:

```
s3.getObject(params, (err, data) => {
        if (err) {
            console.log(err);
            const message = `Error getting object ${key} from bucket ${bucket}. Make sure they exist and your bucket is in the same region as this function.`;
            console.log(message);
            callback(message);
        } else {
            const Data = data.Body.toString('utf8');
            const Input = { Data };
            const input = JSON.stringify(Input);
```

And building with webpack with this config:

```
var webpack = require('webpack');
var path = require('path');
var fs = require('fs');

module.exports = {
    entry: fs.readdirSync(path.join(__dirname, "/.."))
        .filter(filename => {
            const filePath = path.join(__dirname, '/../', filename);
            const isDir = fs.statSync(filePath).isDirectory();
            const ignore = fs.existsSync(filePath + '/.lambdaignore');
            const exists = fs.existsSync(filePath + '/src/index.js');

            return isDir && !ignore && exists;
        })
        .map(filename => {
            var entry = {};
            entry[filename] = './' + path.join(
                filename,
                "/src/index.js"
            );
            return entry;
        })
        .reduce((final, current) => Object.assign(final, current)),
    target: 'node',
    module: {
        loaders: [
        {
            test: /\.js$/,
            // exclude: /node_modules/,
            loader: 'babel-loader'
        },
        {
            test: /\.json$/,
            loader: 'json-loader'
        }]
    },
    resolve: {
        extensions: ['.js', '.json']
    },
    output: {
        path: __dirname + '/../.build',
        library: '[name]',
        libraryTarget: 'commonjs2',
        publicPath: '/',
        filename: '[name].js'
    },
    devServer: {
        hot: true,
        port: 8080
    },
    plugins: [
        // Reference: http://webpack.github.io/docs/list-of-plugins.html#noerrorsplugin
        // Only emit files when there are no errors
        new webpack.NoErrorsPlugin(),

        // Reference: http://webpack.github.io/docs/list-of-plugins.html#dedupeplugin
        // Dedupe modules in the output
        // new webpack.optimize.DedupePlugin(),

        // new webpack.optimize.UglifyJsPlugin()
    ],
    externals: {
        'aws-sdk': true
    }
};
```

_NOTE:_ This builds many functions at the same time. 

I am executing this on AWS Lambda, with Node 6, and on the last line of the aforementioned code, it throws the exception `$JSON.stringify.apply is not a function`. This $JSON wrapper is part of the webpack bundle: 

```
var core = __webpack_require__(0),
    $JSON = core.JSON || (core.JSON = { stringify: _stringify2.default });
module.exports = function stringify(it) {
  // eslint-disable-line no-unused-vars
  return $JSON.stringify.apply($JSON, arguments);
};
``` 

I use JSON very often and webpack as well, and I'd never jumped into this error before. Normally I use webpack for browser-target bundles and I'd swear I used JSON somewhere there - with no errors. 

I tried yesterday to find this on the webpack repo - to fork and test - but didn't find this JSON wrapping on neither webpack's repo nor the babel or json loaders.

Hope this helps. Please tell me if I can elaborate more somewhere.

Thanks Tobias.

**Comment by pritok** [comment]
I'm closing the issue myself, as removing the comment line on `exclude: /node_modules/` fixes the issue. Dunno why happened though, but having that commented was a mistake anyways.

Thanks!
