### ISSUE TITLE
Config: Rule test should respect module alias

### ISSUE THREAD

**Issue by mattslocum** [webpack/webpack#4678]
**Do you want to request a *feature* or report a *bug*?**
Bug. I think it is a bug because both aliases and rules are represented as core features, but aren't compatible with each other. 

**What is the current behavior?**
Rules don't respect aliases. 

**If the current behavior is a bug, please provide the steps to reproduce.**
```
...
    resolve: {
        alias: {
            "my_cool_lib": "src/cool-lib"
        }
    },
    module: {
        rules: [{
            test: /my_cool_lib/,
            // test: /cool-lib/, // works with this one, but it should use the alias
            ...
        }]
    }
...
```
Working example of the bug: https://github.com/mattslocum/webpack-alias-rules

**What is the expected behavior?**
I believe that since resolve.alias and module.rule.test are both core features, then they should be compatible with each other. I should be able to do `test: /my_alias_name` within my module.rule.test. One reason that people use alias is so they don't have to have version numbers in the required file, and the same concept needs to be supported in rules.test

**If this is a feature request, what is motivation or use case for changing the behavior?**
This might be viewed as a missing feature by some people. I'm fairly new webpack, but it seems like AMDPlugin.js might need alias support in the `after-resolvers` section. I generally call this type of missing feature a defect, but it could be splitting hairs.

**Possible solutions:**
1. Add alias support to AMDPlugin.js. I'm not sure it is needed outside of AMDs.
2. A helper/utility module/function that could be used in the webpack.config similarly to `test: require.resolve('jquery')`. It might resemble `test: util.alias('my_alias')`. I'm new to webpack, so I'm not sure the best practices rule on this.

I'm very willing to do a pull request if someone can give some guidance to the solution so I don't pick the wrong style. I'm guessing adding alias support to AMDPlugin is the best, but I'm concerned that it could introduce a breaking change.

**Comment by TheLarkInn** [comment]
Looking into this deeper, I fear what impact this would have if loaders triggered off of raw requests and not resolved resource paths (IE, would this be a sneaky breaking/unexpected change for everyone else. Thoughts maybe?). @sokra what do you think?

**Comment by sokra** [comment]
Resolving runs before loaders.

**Comment by mattslocum** [comment]
Ignore my first idea. Alias rules shouldn't be only for AMDPlugin.

To prevent a "sneaking breaking/unexpected change," maybe we could introduce something explicit. What do you think about a new plugin? If later it is deemed safe, you could make this plugin run automatically instead of explicitly. 

https://github.com/mattslocum/webpack-alias-rules/blob/plugin/webpack.config.js

Would you want this to be part of wepback's enhanced-resolve library?

**Comment by mattslocum** [comment]
Alternatively, I could add this same alias support to webpack/lib/RuleSet.js:normalizeCondition. Thoughts?

**Comment by TheLarkInn** [comment]
Well the problem (that @sokra mentioned) is that the resolved path is already mapped to alias by the time loaders run. Is your use case the version numbers (trying to remember specifically your setup when we met), however since test is regex could there be a more creative regex that you use?

**Comment by mattslocum** [comment]
@TheLarkInn We use requireJS and trying to transition to webpack. We use paths/aliases for versioning primarily. Each app we have has different requireJS config and sometimes different versions between apps, and paths/aliases make it not matter. I'm trying to transition to webpack with a slow rollout so we need webpack and requireJS to live side-by-side if possible.

I might have not been clear enough a couple comments ago. I fixed the bug with a plugin, but I want to know if you guys think the style is acceptable. It shouldn't introduce any breaking changes since it is a new, explicit implementation.

**FIX**
https://github.com/mattslocum/webpack-alias-rules/commit/ce4a954b974ae76e8e3f2ee7be24aa8f862a03a2

I'm not sure I've seen this pattern where the plugin is instantiated outside the plugins array and used in multiple places within the config. It does work though. Thoughts?

**Comment by TheLarkInn** [comment]
Interesting. I've never used a plugin in this way before but it seems to remedy things for you.

**Comment by mattslocum** [comment]
@TheLarkInn Would you guys be willing to take this plugin in one of your repos like https://github.com/webpack-contrib or https://github.com/webpack/enhanced-resolve

Alternatively, we could figure out a way to make this not an explicit plugin since both aliases and rules are core features, but they aren't 100% compatible with each other. This probably is still worth an explicit plugin though.

I can write up some docs and examples.
