### ISSUE TITLE
Critical dependency warning on a require.resolve

### ISSUE THREAD

**Issue by dkfiresky** [webpack/webpack#4681]
**Do you want to request a *feature* or report a *bug*?**

> bug

**What is the current behavior?**

> Critical dependency warning on `require.resolve` call.

**If the current behavior is a bug, please provide the steps to reproduce.**

> Create a file with following contents and process it with default webpack config:
> 
> ```
> let resolvedPath = require.resolve('somepath');
> ```

**What is the expected behavior?**

> No warnings expected due to this is not a `require` statement and no external modules are loaded.

**If this is a feature request, what is motivation or use case for changing the behavior?**

–

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

> macOS 10.12.4 (16E195)
> nodeJS v7.7.2
> webpack v2.3.3

**Comment by TheLarkInn** [comment]
Could you please include a small reproducible example repo?

**Comment by dkfiresky** [comment]
@TheLarkInn please take a look at this repo: https://github.com/dkfiresky/require.resolve-webpack

Also I've noticed a different behavior:
- when wrapping the `path` argument into a template, it will not throw any warnings:
```
let resolvedPath = require.resolve(`${somepath}`);
```

**Comment by sokra** [comment]
@webpack-bot move to webpack/webpack.js.org

Document behavior for dynamic expressions.

webpack is a static bundler and requires statically analysable expressions.
