### ISSUE TITLE
Webpack.watch before the file write to webpack.watch callback will be triggered several times

### ISSUE THREAD

**Issue by chaiyining007** [webpack/webpack#4686]
**Do you want to request a *feature* or report a *bug*?**
 *bug*

**What is the current behavior?**

Webpack.watch before the file write to webpack.watch callback will be triggered several times

**If the current behavior is a bug, please provide the steps to reproduce.**

main.js //Only one line of code，Files are not present
`import * as files from "./files.js"`

start_packing.js //Start packing

```
const webpack = require("webpack");
const fs = require("fs");


fs.writeFileSync(`${__dirname}/files.js`, "Any content");


const compiler = webpack({
    entry: `${__dirname}/main.js`,
    output: {
        filename: `build/app.js`,
        path: `${__dirname}`
    },
    module: {
        rules: [{
            test: /\.(js)$/,
            exclude: /node_modules/,
            loader: 'babel-loader',
            query: {
                presets: ['es2015']
            },
        }]
    },
    resolve: {
        alias: {

        }
    }
});
compiler.watch({}, (err, stats) => {
    console.log(stats.toString({
        colors: true,
        modules: false,
        children: false,
        chunks: false,
        chunkModules: false
    }));

});
```

**What is the expected behavior?**
console.log Only trigger once
**If this is a feature request, what is motivation or use case for changing the behavior?**
Quote is not a webpack package file
**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
macos：10.12.3 (16D32)
node: v7.8.0
webpack: v2.3.3

**Comment by sokra** [comment]
@webpack-bot move to webpack/webpack.js.org

Document that this behavior is expected, as filesystem inaccuracy may trigger multiple build for a single change (webpack can't detect that file hasn't changed from timestamp). Users should expected this and may check `stats.hash` for equal hash (this is what the CLI does).
