### ISSUE TITLE
require.resolve() should not circumvent bundle splitting

### ISSUE THREAD

**Issue by sebmarkbage** [webpack/webpack#4688]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

`require.resolve` causes a strong dependency when one is not needed.

**If the current behavior is a bug, please provide the steps to reproduce.**

`require.resolve('./foo'); import('./foo');` causes the `./foo` file to be included in my bundle even though I have no hard (synchronous) dependency on its code.

**What is the expected behavior?**

Without the `require.resolve` call `./foo` gets put into its own chunk so that bundle splitting works as expected. I expect this behavior to be maintained even when I add a `require.resolve` call.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Webpack 1.14.0.

**Comment by sokra** [comment]
There is a `require.resolveWeak` for a weak reference.

`require.resolve` creates a strong reference because it could be used to access the modules.

``` js
const id = require.resolve("module");
const fn = __webpack_modules__[id]; // <- must be available!

// my own module system
const m = { id, exports: {} }
fn(m, m.exports, __webpack_require__); 
```

**Comment by sebmarkbage** [comment]
I see. That's unfortunate because in Node there is no `require.resolveWeak` so there's no way to express it in a concise way cross-environment. I guess that's just an ecosystem issue and not a bug.
