### ISSUE TITLE
Why does the tutorial not work? I

### ISSUE THREAD

**Issue by jackharter** [webpack/webpack#4689]
Why does the tutorial at https://webpack.github.io/docs/tutorials/getting-started/ not work? It never sees the style sheet and I fixed the css-loader issue?

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by michael-ciniawsky** [comment]
https://webpack.github.io/docs/tutorials/getting-started/  => webpack v1 (legacy)
https://webpack.js.org => webpack v2 (recommended)

**Comment by jackharter** [comment]
Here's another tutorial that does not work:
https://www.sitepoint.com/beginners-guide-to-webpack-2-and-module-bundling/.

It breaks at the point where lodash is installed and a javascript is
changed.

Undoubtedly terrible documentation for webpack. Should you ever find a
tutorial that works, please publish that information.

Here at Disney we are passing on webpack.
