### ISSUE TITLE
Is there a forum for webpack?

### ISSUE THREAD

**Issue by jackharter** [webpack/webpack#4690]
I have tried 3 of the webpack tutorials and none of them work. Does anyone know where to get help or get better tutorials?

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by michael-ciniawsky** [comment]
@jackharter :) Please provide at least some info about

- which tutorials e.g fromOfficial Docs? (Links etc...)
- what didn't work (Error Stacktraces, Logs etc...)

[Docs](https://webpack.js.org)
[Chat]: (https://gitter.im/webpack/webpack)
['Forum'](https://stackoverflow.com/webpack)

**Comment by jackharter** [comment]
https://webpack.github.io/docs/tutorials/getting-started/ - style sheet never loads. And yes, i fied the css-loader issue. There are no errors. The display of the page has the component text but the stylesheet never is picked up. I checked resources in Chrome Developer.

I will be good if i can just get the fundamentals working. It gets confusing because of the webpack versions and alternate documents and javascript incompatibility. 

Just point me to a working tutorial that does not require the use of other new tools that completely obscure issues because of too many unknowns. 

Thanks.

**Comment by michael-ciniawsky** [comment]
@jackharter Post your current `package.json` and `webpack.config.js` 😛 webpack 1/2 ? Use webpack v2 at any cost, if your getting started since webpack v1 is deprecated

**Comment by jackharter** [comment]
I am going to make sure I do right this tutorial you gave me. I did try
this and had a problem. I will try again. Thanks.

On Mon, Apr 10, 2017 at 4:56 PM, Michael Ciniawsky <notifications@github.com

**Comment by jackharter** [comment]
Did the tutorial up until first loading of html. "Failed to load resource:
net::ERR_FILE_NOT_FOUND" bundle.js. Bundle.js is in the app directory. I
ran webpack from app. I ran webpack from the directory above it. It does
not matter. No "Hello Webpack ever displays. Am I broken or is this
tutorial broken or incomplete?

**Comment by jackharter** [comment]
The tutorial tells me there is a dist directory but there isn't. Who knows
where these files should be?

**Comment by michael-ciniawsky** [comment]
I need your config 😛

**Comment by jackharter** [comment]
No config file was generated. Thanks for your help Michael. Apparently this
is not a place to get help or support. It is where you make development
suggestions. As I told Tobias, my suggestion is that you make sure all your
tutorials work and that your documentation is complete.

Thanks, johnh

On Mon, Apr 10, 2017 at 6:10 PM, Michael Ciniawsky <notifications@github.com

**Comment by pksjce** [comment]
@jackharter - You are looking at our old documentation which has since been deprecated. 
Please have a look at [https://webpack.js.org/](https://webpack.js.org/). We appreciate any feedback on the docs repo at [https://github.com/webpack/webpack.js.org](https://github.com/webpack/webpack.js.org). We also appreciate [Pull Requests](http://makeapullrequest.com/)

**Comment by bebraw** [comment]
Time to close. Please refer to the new documentation over the old.
