### ISSUE TITLE
Windows Defender says node_modules\hash.js\lib\hash\sha.js is a trojan

### ISSUE THREAD

**Issue by GraemeWilde** [webpack/webpack#4692]
**Do you want to request a *feature* or report a *bug*?**
Issue, not specifically a bug

**What is the current behavior?**
Windows Defender is reporting `node_modules\hash.js\lib\hash\sha.js` as a trojan.
Also `node_modules\.staging\hash.js-8029e2af\lib\hash\sha.js` (which I'm guessing was just temporary while npm was installing webpack.

**If the current behavior is a bug, please provide the steps to reproduce.**
Well all I did was `npm install --save-dev webpack`.

**What is the expected behavior?**
Windows Defender shouldn't report it as a trojan

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by third774** [comment]
Also running into this.

**Comment by sokra** [comment]
@webpack-bot move to indutny/hash.js
