### ISSUE TITLE
auto suggestion wrong webpack config

### ISSUE THREAD

**Issue by monkindey** [webpack/webpack#4694]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**

When I play with the webpack1, and input `moduleDirectories` carelessly rather than `modulesDirectories`, just missed one letter. It took me a lot of time to debug.

**If the current behavior is a bug, please provide the steps to reproduce.**

No

**What is the expected behavior?**

Would be awesome If webpack can figure out the most similar config, and give the suggestion like git.
When I type git pust, and the git gave me the suggestion:
Did you mean this? push

**If this is a feature request, what is motivation or use case for changing the behavior?**

It may be save someone's day.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

No

Thanks

**Comment by sokra** [comment]
webpack2 does this.

**Comment by monkindey** [comment]
Thanks for your awesome work.
