### ISSUE TITLE
unexpected node polyfill included

### ISSUE THREAD

**Issue by sixmen** [webpack/webpack#4695]
**Do you want to request a *feature* or report a *bug*?**
I think this is a feature, but it maybe a bug.

**What is the current behavior?**
When I require [Mithril](https://github.com/lhorie/mithril.js), webpack includes 'global' and 'setImmediate' polyfills.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
'global', 'setImmediate' polyfills are not included in the output.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Mithril has code like this.

```
var callAsync = typeof setImmediate === "function" ? setImmediate : setTimeout
...
} else if (typeof global !== "undefined") {
	if (typeof global.Promise === "undefined") global.Promise = PromisePolyfill
var PromisePolyfill = global.Promise
```

So, it is ok without global, setImmediate, but webpack does not detect this code.
I think there are libraries that have similar logic.
If webpack can detect this, output size may be decreased.
(Or give a guideline to library developers to avoid this situation)

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by sokra** [comment]
webpack tries to provide an environment similar to node.js. In node.js these things are defined. If you don't want to have this kind of environment you can disable it with the `node` config. i. e. `node.setImmediate: false` or `node: false`

**Comment by sixmen** [comment]
Yes, I know the `node` config.

Libraries for natural browser target like Mithril, do not need node polyfills. So I may use the node config.
But if I add a library for node environment after that, I must know it and remove the node config.

So I thought it would be better if webpack detects that node polyfill is really needed.

If you think it is unnecessary, it is ok. I will just go with the node config.
