### ISSUE TITLE
Webpack 2 resolve.descriptionFiles uses only first found file

### ISSUE THREAD

**Issue by shrpne** [webpack/webpack#4697]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Used only first found file from resolve.descriptionFiles even if this file does not have mainFields.

So for example if it find package.json, but there will be no "main" or "browser" fileds it will not try to find bower.json and will throw error, that module can not be loaded, however bower.json has specified "main" field

**If the current behavior is a bug, please provide the steps to reproduce.**
My config:
```
resolve: {
        modules: ['node_modules', 'bower_components'],
        descriptionFiles: ['package.json', 'bower.json'],
    },
```
I try to load bower module with package.json in it. It fails to load.
If i remove 'package.json', from descriptionFiles config, it will looks for bower.json first and loads bower module succesfully, but now it will not load npm modules

**What is the expected behavior?**
I expect webpack to look for other descriptionFiles if it can't load module from first description file

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
webpack: 2.3.3
node: 6.10.0
OS: macOS 10.12.4

**Comment by sokra** [comment]
It only uses the first description file found.

**Comment by shrpne** [comment]
Yes, and why not to try another description file if first not working?
This is the way how webpack search modules, it iterates from one possible place to another, until find module or until it run out of places list.
Looks like resolve.descriptionFiles should be iterated through

**Comment by sokra** [comment]
If the package.json exists and contains valid json it's "working".

It looks like your package.json doesn't point to a main file. This probably means the package.json is incorrect. It's not webpack's job to validate your package.json. If a package is published with a incorrect package.json, it's an issue of the package.
