### ISSUE TITLE
Entry chunks not being re-evaluated when script is re-run

### ISSUE THREAD

**Issue by jakepusateri** [webpack/webpack#4699]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Entry modules are not being re-evaluated when the script they are in is re-run
**If the current behavior is a bug, please provide the steps to reproduce.**
I've prepared a gist with a running demo of the behavior.
https://gist.github.com/jakepusateri/51074ab06fd96b96dbf677bcb9165162

**What is the expected behavior?**
Entry modules should be re-run when the script is reloaded as they often have important side effects, such as rendering a React component. This was the case in webpack 1.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
webpack@2.3.3
node@7.4.0
Ubuntu 16.04

**Comment by sokra** [comment]
webpack requires you to only include a script tag once. Reloading script tags is not supported. Expose a function from your script if your want to execute something multiple times.

**Comment by jakepusateri** [comment]
Good to know, thanks. I guess it worked by accident in webpack 1. Is there
a place in the docs for this requirement? Maybe a mention in the 1->2
migration guide?

**Comment by sokra** [comment]
It worked the same way in webpack 1. It depends on usage of the CommonsChunkPlugin. Omit it and the entry chunks will reload.

**Comment by jakepusateri** [comment]
The same demo linked from above with webpack@1.14.0 being used: https://gist.github.com/jakepusateri/584baa0d5fc5025a4784b667de231256

With no configuration difference, the first module is being reevaluated when the script reloads.
It appears to be special cased here
https://gist.github.com/jakepusateri/584baa0d5fc5025a4784b667de231256#file-commons-js-L21 with the first entry in the array being cleared from the module cache and then required.

**Comment by sokra** [comment]
ah ok, you are right. webpack 1 used this hack, because it always used id 0 for the entry point. webpack 2's behavior is correct here. A module should only be executed once (like with `require`).

**Comment by Herz3h** [comment]
This seems to apply to including entrypoints multiple times on the same page (ajax request fetching html with same script tag). Is there a way to force reevaluate of the entrypoint ?
