### ISSUE TITLE
override file with one at specified location while bundling

### ISSUE THREAD

**Issue by satya23k** [webpack/webpack#4701]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
routes are replaced through regex the ones matching it. But i want to override a file with another one present in a specific folder. Better explain below with the example.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Lets say I have a file inside my _src/ui/folder/_. I have another file similar to the aforementioned file at the  path _src/CUSTOM_TAG/ui/folder/_. I would like webpack to replace the first file with the second one while making the bundles. The CUSTOM_TAG will be passed to webpack before compilation. 
That is I want the webpack to see if the file exists in the path with CUSTOM_TAG , if it's not available serve the normal file else override it.

**Comment by sokra** [comment]
Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md).

-> NormalModuleReplacementPlugin or resolve.alias

**Comment by ollie101** [comment]
@satya23k I have a similar use case. I've found this plugin but not managed to get it working properly yet so not an endorsement but thought it might be worth a mention https://github.com/thaerlabs/alias-regex-webpack-plugin

**Comment by satya23k** [comment]
@ollie101 Thank you, seems promising. 
But I already implemented it using webpack-alias and node-glob(as I want the aliases to build automatically as and when a new file is added into the directory)
