### ISSUE TITLE
Dynamic import and Require ensure

### ISSUE THREAD

**Issue by V-Tom** [webpack/webpack#4702]
**Do you want to request a *feature* or report a *bug*?**
feature.And the webpack verison is **2.3.2**

**What is the current behavior?**
when i use `dynamic import` or `require ensure` get some issues.
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

I want to do code splitting. So first i use the dynamic import like `import()`.But it can't custom chunk file name.

I know the `require.ensure` can do this. But can't handle error. i had searched the issues find a deprecated solution:[System.import](https://github.com/webpack/webpack/issues/758)

I see the [PR](https://github.com/webpack/webpack/pull/4069) sad had been support it. 

Is it release?

And because the `import()` module loading syntax proposal is on the way into ECMAScript. So some people would like to use that rather than `require.ensure`. 

Is there a feature to supposed custom chunk file name ? may be just like `import('./Main?chunkname=Main')`.

Thanks!

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by sokra** [comment]
next release include both, chunk name for `import()` and error handler for `require.ensure`

**Comment by V-Tom** [comment]
[2.4.0](https://github.com/webpack/webpack/releases/tag/v2.4.0) release resolve both of them .
Thanks
