### ISSUE TITLE
Using a string variable in a require from a JSON file returns an error.

### ISSUE THREAD

**Issue by Elliot-Evans-95** [webpack/webpack#4705]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Able to pass a string into require
**If the current behavior is a bug, please provide the steps to reproduce.**
1. use a $http angular service to GET a JSON file.
2. reference a string value within that JSON file and assign it to a variable.
3. use require to require the string so it can be used to hash an image.
E.G: var test = './image.png'; $scope.image = require(test);
4. an error will appear: Error: Cannot find module "." at webpackMissingModule

**What is the expected behavior?**
To be able to load that image referance and hash the image on the html
**If this is a feature request, what is motivation or use case for changing the behavior?**
not a feature request
**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
node - v7.7.2
webpack - 2.3.3
OS - OSX El Capitan

**Comment by Radi123** [comment]
Hello, @Elliot-Evans-95 !

I tested it without angular, and it worked... 
I use node on Win7, but I had similar error on mac, a week ago.
I think something crash with webpack on OSX... 
I can't help for now, but I will try to find the problem, soon.

Goodbye!

**Comment by aegisho** [comment]
same problem with webpack2 on mac  
```
cont img = require('./xx.png') 
error cannot find module "."
```
my config
```
    {
        oneOf: [
          {
            test: /\.(png|gif|jpg|jpeg|svg|woff|ttf|eot)$/,
            resourceQuery: /\?.*/,
            loader: 'url-loader'
          },
          {
            test: /\.(png|gif|jpg|jpeg|svg|woff|ttf|eot)$/,
            loader: 'file-loader',
            options: {
              name: '[path][name].[ext]'
            }
          }
        ]
      },
```
it‘s work fine on webpack1
anyone can help me ?
