### ISSUE TITLE
TypeError in manifest.js on Android with Chrome 28

### ISSUE THREAD

**Issue by justincy** [webpack/webpack#4711]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

This error is thrown:

```
TypeError: Cannot call method 'call' of undefined
1
File https://rootssearch.io/assets/js/manifest.4d446d350c0a3f09a673.js line 1 in [anonymous]
```

I'm only seeing it on Android with Chrome 28. I don't have access to that old of an environment. It's being reported via error tracking on my website.

**If the current behavior is a bug, please provide the steps to reproduce.**

https://gist.github.com/justincy/2b225d2f15429ccbfeb03a34c2e4f61e

**What is the expected behavior?**

No TypeError

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Chrome 28 on Android

**Comment by sokra** [comment]
This error happens if a module is missing in the list of loaded modules, but requested from the code.

I can't say why this happens here. Should not happen.

It could happen when i. e. vendor chunk fails to load but app chunk loads fine. In this case modules from vendor chunk are not available...

**Comment by sokra** [comment]
Open a new issue if you have more information.
