### ISSUE TITLE
Can we have a 'webpack init'?

### ISSUE THREAD

**Issue by FateRiddle** [webpack/webpack#4712]
**Do you want to request a *feature* or report a *bug*?**

feature.

**Content:**

I'm requesting a webpack init command, just like npm init, that generates a webpack.config.js file with couple of questions.
I'm using React.js, and setting up a webpack.config.js for the first time is painful to say the least. I understand we let the webpack be as unopinionated as possible, but we could also introduce some opinionated way to build/do things much much easily:

Prettier, it doesn't ask how you want to formate.
create-react-app, it doesn't ask you anything. 

They are great starting point. 

For me, the minimum webpack should know is my entry/output and what loaders I use and whether it is for development or production. Then it should fill the gap with opinionated setup, generate the file and let me tweak it just later.

we can even go further, like webpack init --react/--vue/--node. 

That is just my opinion, a missing part of a fine map.

**If this is a feature request, what is motivation or use case for changing the behavior?**

Too much configuration, too many fragments.

**Comment by michael-ciniawsky** [comment]
@FateRiddle Maybe better open this at webpack/webpack-cli

**Comment by sokra** [comment]
@webpack-bot move to webpack/webpack-cli

**Comment by ev1stensberg** [comment]
@FateRiddle Working on this, expecting to release within the month.
