### ISSUE TITLE
When using `--optimize-minimize`, webpack ignores uglifyPlugin's `mangle: false` option.

### ISSUE THREAD

**Issue by blackChef** [webpack/webpack#4713]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
When using `--optimize-minimize`, webpack ignores uglifyPlugin's `mangle: false` option.

**If the current behavior is a bug, please provide the steps to reproduce.**

    let uglifyPlugin = new UglifyJSPlugin({
       mangle: false, // not working
       output: { comments: false } // working 
    });
    //  Comments are striped out, but variables are mangled
    webpack --optimize-minimize
   

**What is the expected behavior?**
Webpack respects uglifyPlugin's options.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by ericnewton76** [comment]
Also the uglifyjs compressor options need to be respected.  Havent checked that they arent.

**Comment by mitchellnemitz** [comment]
Can confirm this issue.

webpack.config.js:

```
var path = require('path');
var webpack = require('webpack');

module.exports = exports = {
    entry: __dirname + "/client/index.js",
    output: {
        path: __dirname + "/public/app",
        filename: "client.min.js"
    },
    resolve: {
        extensions: ["*", ".js", ".json"],
        modules: [path.resolve('./client'), 'node_modules']
    },
    module: {
        rules: [{
            test: /\.js$/,
            exclude: /(node_modules)/,
            use: {
                loader: 'babel-loader',
                options: {
                    presets: ['env']
                }
            }
        }]
    },
    plugins: [
        new webpack.optimize.UglifyJsPlugin({ mangle: false })
    ]
};
```

Everything else seems to be working, save for mangling.

**Comment by thomasgwatson** [comment]
Wait, isn't adding `--optimize-minimize` and the UglifyPlugin the same thing?

**Comment by mitchellnemitz** [comment]
They are the same thing yes, which is why you would expect the options in your config file to override the defaults.

**Comment by thomasgwatson** [comment]
So why not remove the CLI `--optimize-minimize`?

https://github.com/webpack/webpack/issues/1385

From Sokra in the above thread "when using new UglifyJsPlugin and `--opimize-minimize` (or -p) you are adding the UglifyJsPlugin twice. Omit the CLI option."

**Comment by blackChef** [comment]
@thomasgwatson Because using `--optimize-minimize` is the way to enable tree shaking feature.

**Comment by thomasgwatson** [comment]
@blackChef have you tried comparing bundle sizes when removing --optimize-minimize and not? I suspect they will be the same.

**Comment by esbenp** [comment]
@blackChef As you can see here https://github.com/webpack/webpack/blob/master/bin/convert-argv.js#L460 the `--optimize-minimize` flag will simply add the UglifyJsPlugin plugin to the configuration (optionally with the sourceMap parameter). Notice how it omits the `mangle` option. If you want `mangle: false` you should omit the CLI parameter and use a config file instead :-)

**Comment by blackChef** [comment]
@esbenp Yes, I could simply don't use `optimize-minimize`,  but then I loose the tree shaking feature.
According to https://webpack.js.org/guides/tree-shaking/
> When running a production build, node_modules/.bin/webpack --optimize-minimize main.js dist.min.js, only the minimized version of cube but not square remains in the build:

Unless there is a standalone "tree shaking" plugin, there's no way to customize uglify plugin while tree shaking is enabled.

**Comment by esbenp** [comment]
Alright, lets test this :-)
Using the example from the guide i define

`functions.js`
```
// This function isn't used anywhere
export function somefunc() {
    return 'somestring';
}

// This function gets included
export function cube(x) {
    return x * x * x;
}
```

I have changed `square` into `somefunc` that returns a string, since a string is easier to spot in the minified build.

I add my entry file

`main.js`
```
import {cube,somefunc} from './functions.js';
console.log(cube(5),somefunc()); // 125
```

Now I create a webpack config

`webpack.config.js`
```
var webpack = require('webpack');

module.exports = {
  entry: './main.js',
  plugins: [
    new webpack.DefinePlugin({
        'process.env.NODE_ENV': JSON.stringify('production')
    }),
    new webpack.optimize.UglifyJsPlugin()
  ]
};
```

and run `webpack dist.js`

Now, because I have imported *and used* `somefunc` in main.js we can see the string `somestring` is included in the minified build below (it is at the very end).

`dist.js`
```
!function(e){function t(r){if(n[r])return n[r].exports;var o=n[r]={i:r,l:!1,exports:{}};return e[r].call(o.exports,o,o.exports,t),o.l=!0,o.exports}var n={};t.m=e,t.c=n,t.d=function(e,n,r){t.o(e,n)||Object.defineProperty(e,n,{configurable:!1,enumerable:!0,get:r})},t.n=function(e){var n=e&&e.__esModule?function(){return e.default}:function(){return e};return t.d(n,"a",n),n},t.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},t.p="",t(t.s=0)}([function(e,t,n){"use strict";Object.defineProperty(t,"__esModule",{value:!0});var r=n(1);console.log(Object(r.a)(5),Object(r.b)())},function(e,t,n){"use strict";function r(){return"somestring"}function o(e){return e*e*e}t.b=r,t.a=o}]);
```

So let us change `main.js` and remove `somefunc` entirely

`main.js`
```
import {cube} from './functions.js';
console.log(cube(5)); // 125
```

So now `somefunc` should be omitted entirely from our production build using tree-shaking. Running `webpack dist.js` again and we see that the string `somestring` is not there anymore.

`dist.js`
```
!function(e){function t(r){if(n[r])return n[r].exports;var o=n[r]={i:r,l:!1,exports:{}};return e[r].call(o.exports,o,o.exports,t),o.l=!0,o.exports}var n={};t.m=e,t.c=n,t.d=function(e,n,r){t.o(e,n)||Object.defineProperty(e,n,{configurable:!1,enumerable:!0,get:r})},t.n=function(e){var n=e&&e.__esModule?function(){return e.default}:function(){return e};return t.d(n,"a",n),n},t.o=function(e,t){return Object.prototype.hasOwnProperty.call(e,t)},t.p="",t(t.s=0)}([function(e,t,n){"use strict";Object.defineProperty(t,"__esModule",{value:!0});var r=n(1);console.log(Object(r.a)(5))},function(e,t,n){"use strict";function r(e){return e*e*e}t.a=r}]);
```

We can also create a build with `mangle:false`
```
!function(modules){function __webpack_require__(moduleId){if(installedModules[moduleId])return installedModules[moduleId].exports;var module=installedModules[moduleId]={i:moduleId,l:!1,exports:{}};return modules[moduleId].call(module.exports,module,module.exports,__webpack_require__),module.l=!0,module.exports}var installedModules={};__webpack_require__.m=modules,__webpack_require__.c=installedModules,__webpack_require__.d=function(exports,name,getter){__webpack_require__.o(exports,name)||Object.defineProperty(exports,name,{configurable:!1,enumerable:!0,get:getter})},__webpack_require__.n=function(module){var getter=module&&module.__esModule?function(){return module.default}:function(){return module};return __webpack_require__.d(getter,"a",getter),getter},__webpack_require__.o=function(object,property){return Object.prototype.hasOwnProperty.call(object,property)},__webpack_require__.p="",__webpack_require__(__webpack_require__.s=0)}([function(module,__webpack_exports__,__webpack_require__){"use strict";Object.defineProperty(__webpack_exports__,"__esModule",{value:!0});var __WEBPACK_IMPORTED_MODULE_0__functions_js__=__webpack_require__(1);console.log(Object(__WEBPACK_IMPORTED_MODULE_0__functions_js__.a)(5))},function(module,__webpack_exports__,__webpack_require__){"use strict";function cube(x){return x*x*x}__webpack_exports__.a=cube}]);
```

Again, `somestring` is no where to be found.

The flag `--optimize-minimize` is merely a shortcut that will add two things: (1) it will add the `UglifyJsPlugin` and (2) it will add a `LoaderOptionsPlugin` with `minimize=true`

**Comment by blackChef** [comment]
@esbenp So I create a simple test repo [here](https://github.com/blackChef/webpack_test/tree/master). I'm using local installed latest version of webpack, and I can't get tree shaking feature without `--optimize-minimize`.

**Comment by esbenp** [comment]
That is because you are not adding any optimization to your config file. You need to add the same plugins the `--optimize-minimze` flag gives you (DefinePlugin and UglifyJsPlugin). I have added them to your test here: https://github.com/esbenp/webpack_test/commit/215c92126f2a1de2a14d28bf1d591f0af4550f53

If you run `npm run normal` now it will have removed `this should be removed by tree shaking` from your build :-)

**Comment by blackChef** [comment]
@esbenp Yes, you are right. Both `webpack.optimize.UglifyJsPlugin` and standalone `uglifyjs-webpack-plugin` can enable tree shaking. Setting `NODE_ENV` to `production` doesn't seems to have relevance to tree shaking. I removed it, tree shaking still works. 
So I think there are 3 problems:
1.webpack's documentation doesn't make it clear that how we can enable tree shaking.
2.webpack's documentation doesn't make it clear that how do CLI shortcut and config file work together.
3.uglifyPlugin's documentation doesn't say it can also do tree shaking. And in my opinion, a standalone "tree shaking" plugin is better than an uglify plugin with extra tree shaking feature.

**Comment by esbenp** [comment]
Glad we figured it out @blackChef :-)

I have opened #5363 which touches upon the ambiguity of CLI plugins vs config plugins.

**Comment by turnerhayes** [comment]
Is `--optimize-minimize/-p` always going to be a synonym for "run Uglify"? That is, if I leave `-p` out of my prod build script (instead using babel minify in a prod webpack config), I won't be missing out on anything/there aren't plans to add additional optimizations under that flag?
