### ISSUE TITLE
[feature request] add "build at" info to console

### ISSUE THREAD

**Issue by flashios09** [webpack/webpack#4718]
Hi,
What about adding a **Build at** info to console output:
![image](https://cloud.githubusercontent.com/assets/1313482/25066256/1c3351a4-2219-11e7-83bb-d08c8771a6e1.png)
We can know when the last time we build(save), many times i forget to save my file after doing some changes and waited on my web pages to be updated but nothing happened :p

I have just updated **webpack/lib/Stats.js**:
```js
        if(typeof obj.time === "number") {
            colors.normal("Build at: ");
            colors.bold(new Date);
            newline();
            colors.normal("Took: ");
            colors.bold(obj.time);
            colors.normal("ms");
            newline();
        }
```

Thanks

**Comment by yeskunall** [comment]
I'd like to take this up as my first PR to `webpack`, if I have the go-to! 👍

**Comment by bebraw** [comment]
@yeskunall Sure. 👍

**Comment by sokra** [comment]
If you want to do a PR, please use the build time and not the time when the stats are generated.
Timestamp should be added to the stats json object before written as string.

hint: https://github.com/webpack/webpack/blob/master/lib/Stats.js#L206-L208

**Comment by yeskunall** [comment]
So I think I have a solution, but I'm sorry I have to ask: how do I test my additions? A link to an article, or any info would help! @sokra @bebraw

**Comment by naknode** [comment]
I have been thinking about this and if we really wanted to flesh this out, we could do this something like this:

1. Add `momentjs` to give the user the ability format their date
2. Add an option to insert said format inside the `stats` object in the `webpack.config.js` file so the user can see the date however their wish and see when the build was finished like so:
```json
{
  ...
  buildTime: 'dddd, MMMM Do YYYY, h:mm:ss a'
}
```
3. Add the `build-time` argument inside the `--verbose` flag as well

Feel free to critique anything I may have missed or could be changed.

**Comment by yeskunall** [comment]
I feel like allowing the user to format the date might be pushing it too far.

Update: I think I have this feature working @bebraw @sokra, but the tests seem to be failing, for obvious reasons: the build time varies each time you run the tests. How can I make the tests pass, in this case?

**Comment by naknode** [comment]
@yeskunall makes sense. I guess there might be a thing as too much in terms of extensibility. 

As for momentjs, might be so but I didn't think it would be too much but once again - yes.

Anyway, hope you get those tests resolved!

**Comment by bebraw** [comment]
@yeskunall Can you link to your PR? It might take some injection approach to fix.

**Comment by filipesilva** [comment]
Heya @yeskunall, did you get around to making a PR?

**Comment by yeskunall** [comment]
@filipesilva not yet, but I think I can make some time for this.

**Comment by yeskunall** [comment]
Hey @bebraw, so I tried fixing this on my own, but the test cases are still failing. I might need your help with this, after all! 😓 PR is up on my [`master`](https://github.com/yeskunall/webpack/pull/1) branch, but if you'd like, I can make a PR here too, saying it's a WIP! Let me know what works for you.
