### ISSUE TITLE
resolve.root vs moduleDirectories

### ISSUE THREAD

**Issue by necolas** [webpack/webpack#472]
What's the practical difference between these options? If I have a project structure like this:

```
|-- webpack.config.js
|-- src
    |-- node_modules
    |-- web_modules
```

I was expecting to be able to set a root to `/absolute-path/etc/src` and have webpack use that as the base to search for `web_modules` and `node_modules`. But instead I had to do either:

``` js
resolve.root = [ 'src/node_modules', 'src/web_moodules' ]
```

or

``` js
resolve.moduleDirectories = [ 'src/node_modules', 'src/web_moodules' ]
```

What's the benefit of `root`? Is it possible to set some kind of base path in the way I was looking for?

**Comment by Targun** [comment]
This wasn't working for me:

```javascript
resolve: {
    root: path.resolve('src'),
    modulesDirectories: ['node_modules'],
    extensions: ['', '.js', '.jsx']
},
```

How should the resolve look to work with both node_modules and everything inside of the public folder?

**Comment by jhnns** [comment]
@Targun sorry, that's not enough information to solve your issue. You need to provide us with examples, your folder structure, your specific error.

**Comment by Targun** [comment]
Sorry for the lack of details.  This is what ended up working for me:

```javascript
resolve: {
    modulesDirectories: ['node_modules', './src'],
    extensions: ['', '.js', '.jsx']
},
```

Now I am able to import files from the root of my src folder rather then needing "../../.."

**Comment by jhnns** [comment]
Mhmmm this config could have an impact on your bundling performance. It causes webpack to prepend `./src` to every folder. So when you write `require("a")` it will try to look up:

```
/some/folder/structure/node_modules/a
/some/folder/structure/src/a
/some/folder/node_modules/a
/some/folder/src/a
/some/node_modules/a
/some/src/a
/node_modules/a
/src/a
```

`resolve.root` should work as expected. I think there is another problem in your config.

**Comment by Targun** [comment]
Thanks for your help!

**Comment by pigcan** [comment]
@jhnns  

```
resolveLoader: {
  modulesDirectories: [ path.resolve(__dirname, '../node_modules'), 'node_modules' ],
  extensions: [".loader.js", ".js"]
},
```

So when I write `css!postcss!less`  how to look up postcss-loader

Thanks

**Comment by IAMtheIAM** [comment]
How do we do this in webpack 2? It doesnt allow `resolveLoader.modulesDirectories`

**Comment by alex88** [comment]
@IAMtheIAM use `resolve.modules`

**Comment by dragosrusu** [comment]
@alex88 : doesn't seem to work - can you provide a sample?
Tried with: "resolve: { modules: "../devtools/node_modules" } and it did not work out.

**Comment by evenfrost** [comment]
@dragosrusu
`resolve.modules` [should be an array](https://webpack.js.org/configuration/resolve/#resolve-modules), so try `resolve: { modules: ["../devtools/node_modules"]  }` instead.

**Comment by shirakaba** [comment]
Using webpack 2.1.0-beta.22, I found that `webpack` appeared to be ignoring my settings in `resolve.modulesDirectories` and, as far as I could understand, also `resolve.root`.

As @alex88 suggested, adding a `resolve.modules` configuration instead of `resolve.modulesDirectories` and `resolve.root` allowed me to use paths relative to a root rather than relative to the module (exactly as [this StackOverflow poster](http://stackoverflow.com/questions/27502608/resolving-require-paths-with-webpack) desired): 

```
resolve: {
	modules: ["."]
},
```
