### ISSUE TITLE
Typo in README

### ISSUE THREAD

**Issue by yeskunall** [webpack/webpack#4724]
**Do you want to request a *feature* or report a *bug*?**
N/A

**What is the current behavior?**
N/A
**If the current behavior is a bug, please provide the steps to reproduce.**
N/A

**What is the expected behavior?**
N/A
**If this is a feature request, what is motivation or use case for changing the behavior?**
N/A
**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
N/A

I think there might be a small typo under the Other Backers and Sponsors section of the README.

> We want to acknowledge these sponsors and backers, but donations were not public and we are not sure of donors want to stay anonymous

... should instead read, "... and we are not sure _if_ donors want to stay anonymous."

Just something that caught my eye. If it's too trivial, I can send in a PR and you guys can merge it at a later date along with other minor updates.

/cc @bebraw (because I think you're in charge of documentation)

**Comment by bebraw** [comment]
Yeah, PR please. 👍

**Comment by yeskunall** [comment]
I will submit a PR as soon as I get off work!

Another thing that I noticed is that the links to the backers are a bit-off. For eg., Addy Osmani's picture redirects you to Cory House's profile. Just thought I should give you a heads-up for that as well.

**Comment by bebraw** [comment]
@yeskunall I wonder if that's fixable too... The problem might be on Open Collective's side.

**Comment by yeskunall** [comment]
@bebraw you are right, it looks like it's a fault on OpenCollective's end. I think it'd be wise to let the guys at OpenCollective know about this. Maybe open up an issue on their repo?

**Comment by bebraw** [comment]
@yeskunall Please do that. https://github.com/OpenCollective/opencollective-website might be the right place. 👍

**Comment by yeskunall** [comment]
Will do, @bebraw. As for the grammatical fix, like I said, the PR will be in ASAP. ❤️

**Comment by yeskunall** [comment]
Hey @bebraw, so the PR is in. #4728. ❤️
