### ISSUE TITLE
Lint errors in cloned webpack repo

### ISSUE THREAD

**Issue by ndresx** [webpack/webpack#4725]
**Do you want to request a *feature* or report a *bug*?**
Lint errors ~_bug_

**What is the current behavior?**
When running `yarn test` on a local machine (Windows), ESLint is reporting several errors, where at least 1 error seems to be legitimate. However, this was also tested on another machine (Mac), where no errors were shown during linting. _Could there be a reason for this behavior?_

**If the current behavior is a bug, please provide the steps to reproduce.**
Execute `yarn test` in the cloned webpack repository.

Environment:
**OS:** `Windows 10`
**Node:** `v6.10.2`
**yarn:** `v0.23.2`
**ESLint:** `v3.19.0`

Example file where the lint fails:
`test\configCases\parsing\extended-api\webpack.config.js`
`other: './index'` => Rule: Strings must use doublequote  quotes

This report seems to be correct?

**What is the expected behavior?**
No lint errors should be shown.

**If this is a feature request, what is motivation or use case for changing the behavior?**
I was about to create a PR for changing something else and was then more or less blocked by finding out what is causing these errors and how they can be fixed. Since this only occurred on one of my machines, it could be a configuration problem, on the other side, the aforementioned example doesn't seem to be wrong.

I have already changed a couple of files (6 in total) and could create a PR for this (if desired).

**Comment by ndresx** [comment]
Was now able to test this on another Windows 10 machine in a different environment with Node `v7.9.0`. The same errors occurred on this one, so it seems to be Windows related.

**Comment by sokra** [comment]
Yes I noticed this too. windows seem to be correct here. Could be related to `**` in the npm scripts. It would be great if you can locate the issue, fix the linting issues and send a PR.
