### ISSUE TITLE
Naming imported chunks causes all chunks to download

### ISSUE THREAD

**Issue by corbanbrook** [webpack/webpack#4726]
When using the new chunk naming feature introduced in Webpack 2.4.0 it causes all imports to run immediately instead of when the system import is lazily loaded.

Used to lazy load account-settings module within a react project with react-router:
```
 getComponent: (state: Object, cb: Function) => (
   System.import(/* webpackChunkName: "account-settings" */ 'src/modules/account/settings')
   ..
 )
```

The comment successful names the chunk but it causes it to download the chunk immediately. By removing the webpackChunkName comment it will allow this module to lazy load again.

**Comment by corbanbrook** [comment]
I am noticing that there is a difference between `System.import` and `import` here.

System.import correctly names all the chunks but causes the lazy loaded chunks to fetch immediately. 

import correctly names the first chunk that is loaded and does NOT cause lazy chunks to fetch immediately but when the chunks are fetched they are not named.

![screen shot 2017-04-18 at 10 03 49 am](https://cloud.githubusercontent.com/assets/62406/25134852/b1135fe2-241e-11e7-8957-c9ac68284e81.png)

**Comment by corbanbrook** [comment]
This featured was added in #4573

**Comment by mc-zone** [comment]
Did not notice this, I will try to fix it if I can.

**Comment by huy-nguyen** [comment]
I had a similar problem but with `react-router` v4. The default/index route was always loaded even though I navigated to a sibling route. I fixed it by having no index route (kind of a pain I know). Not sure how relevant it is.

**Comment by mc-zone** [comment]
@huy-nguyen Could you please provide a reproduceable repo or gist to help us figure out it? Thanks :)

**Comment by mc-zone** [comment]
> The default/index route was always loaded even though I navigated to a sibling route.

@huy-nguyen Did you set the [`exact` property](https://reacttraining.com/react-router/web/api/Route/exact-bool) to your index route ? If you didn't set it, this is a feature in react-router v4 AFAIK.

And I've make a v4 Demo today. It looks ok. 

You can try https://mc-zone.github.io/Demo_react_router_lazy_load_with_webpack_import_named_chunk/v4/index.html#/bar

and the source code is [here](https://github.com/mc-zone/Demo_react_router_lazy_load_with_webpack_import_named_chunk/blob/v4/index.js#L73).
