### ISSUE TITLE
heavy memory usage when generating sourcemaps

### ISSUE THREAD

**Issue by MagicDuck** [webpack/webpack#4727]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Heavy memory usage when generating sourcemaps resulting in lots of garbage collection, resulting in slow builds.

**If the current behavior is a bug, please provide the steps to reproduce.**

Run a larger webpack build and profile it using the chrome dev tools. Use "Record Allocation Profile" when it gets to the phase of generating sourcemaps (the SourceMapDevToolPlugin, you might need to add a console.log in it so you can tell when you are there) 

**What is the expected behavior?**
reasonable memory usage

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
you need nodejs 6.9 to use the --inspect flag.

We have a large project that is build using webpack, which uses source-map to generate the sourcemaps.
There are issues with performance of the phase that generates the sourcemaps so we did some profiling.  We are at the point where we already have to give nodejs 8Gb of memory when running with devtool: "source-map", which is getting a bit ridiculous considering that the total size of our code does not exceed 200Mb. One thing we noticed right off the bat is the sharp sawtooth shape of the memory usage graph of the node process. This basically means that a lot of the time is spent garbage collecting. 
From my personal profiling using the chrome developer tools, there are some easy pickings:
* source-maps array-set: I've already filed an issue here: https://github.com/mozilla/source-map/issues/259
* PrefixSource: I know it's fancy, but it's a huge cost to pay in terms of performance as it allocates a lot or memory. For us we just monkey-patched it to basically do nothing and be transparent:
```js
const PrefixSource = require("webpack-core/lib/PrefixSource");
PrefixSource.prototype.source = function() {
    return (typeof this._source === "string") ? this._source : this._source.source();
};

PrefixSource.prototype.node = function(options) {
    return this._source.node(options);
};

PrefixSource.prototype.listMap = function(options) {
    return this._source.listMap(options);
};

PrefixSource.prototype.updateHash = function(hash) {
    if (typeof this._source === "string") {
        hash.update(this._source);
    } else {
        this._source.updateHash(hash);
    }
};
```
Some of the other ones that could be difficult to change:
* ReplaceSource - the node splitting code creates a separate subtree for the stuff to be replaced only to throw it away after the replacement...
* OriginalSource.node() (all that splitting on "\n")
* possibly more source-map internals, I can't remember now...

**Comment by sokra** [comment]
Are you using webpack 1 or webpack 2?

**Comment by MagicDuck** [comment]
still on webpack 1 here. Haven't had a chance to switch yet... but am guessing the same issue would be visible with 2, unless I am mistaken.
Is webpack 2 not using https://github.com/webpack/webpack-sources anymore? 
That code doesn't look to have changed in significant ways since webpack 1.

**Comment by sokra** [comment]
PrefixSource is no longer used by default.

**Comment by sokra** [comment]
Better check again with webpack 2. I guess something changed here...

Also try to use the `cheap-module-source-map`, which is more performant but doesn't provide column mapping.

**Comment by MagicDuck** [comment]
Have to use `source-map` for the code coverage stuff to work, but will try again when we switch to webpack 2.

**Comment by MagicDuck** [comment]
Fyi, the source-map issue mentioned above has been fixed here: https://github.com/mozilla/source-map/pull/260. Not sure if the version needs to be upped inwebpack's package.json

**Comment by about-code** [comment]
See #2157

**Comment by evilebottnawi** [comment]
Solved in latest `source-map` version(s), please update webpack as possible to the stable highest version. Thanks!
