### ISSUE TITLE
Make --hide-modules to be the default behaviour

### ISSUE THREAD

**Issue by andreypopp** [webpack/webpack#473]
Even small apps which use libraries like React (around 100 CommonJS modules) result in webpack output to be unreasonable long:

```
% webpack  | wc -l
170
```

Because of every CommonJS module is listed in the output.

What do you think if `--hide-modules` will be the default behaviour for webpack? Instead `--display-modules` will be introduced which returns old behaviour back.

**Comment by Strate** [comment]
I've found this issue because after switching to 2.2-rc versions, webpack shows every required module in standard output. Is it desired behaviour or regression?

**Comment by sokra** [comment]
see #3540
