### ISSUE TITLE
Node API doesn't emit error

### ISSUE THREAD

**Issue by mochini** [webpack/webpack#4733]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
I'm having a problem with the webpack node api, heres my code:
```
  const compiler = webpack({
    entry: {
      admin: path.resolve(__dirname,'..','src','admin','index.js')
    },
    output: {
      path: path.resolve('.','public','js'),
      filename: path.join('[name]-[hash].min.js')
    }
  })

  compiler.plugin('make', (compilation)=> {
    console.log('gets here')
  })

  compiler.plugin('after-compile', (compilation)=> {
    console.log('never gets here')
  })

  compiler.run((err, stats) => {
    console.log('never gets here')
  })
```
it looks like my run is getting swallowed after the `make` step and i never see an `err` in the run callback, so i have no idea why its not completing...

**If the current behavior is a bug, please provide the steps to reproduce.**
See above

**What is the expected behavior?**
I expect to see some sort of error or indication why it didn't complete...

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Mac OSX 10.12.3
Node 7.2.1
Webpack 2.4.1

**Comment by sokra** [comment]
The plugin hooks you are using are async. The give you a callback argument, which is not being called by you.

See http://webpack.github.io/docs/plugins.html
