### ISSUE TITLE
FEAT: Create a messages.json file for all kinds of messages emitted by webpack

### ISSUE THREAD

**Issue by yeskunall** [webpack/webpack#4735]
**Do you want to request a *feature* or report a *bug*?**
I'd say it's a feature.

**What is the current behavior?**
Currently, all messages (be it warnings, errors, etcetera) are hard-coded, which reduces maintainability.

**If the current behavior is a bug, please provide the steps to reproduce.**
N/A

**What is the expected behavior?**
N/A

**If this is a feature request, what is motivation or use case for changing the behavior?**
I suggest we create a `messages.json` (or of any format for that matter, as long as one can parse it fairly easily) that defines all the different types of messages. This
- enhances maintainability
- improves readability
- reduces the headache of searching through a large code base for the particular message, and *then* updating it (imagine if the same error message is used in multiple files 😱)

For example,

```js
...
{
  expectsAnArray: '... expects an array',
  genericWarning: 'Warning: ... generic warning',
  unfathomableError: '... look into this immediately!',
  ...
},
```

... and in some file

```js
const msgs = require('path/to/messages.json');

fn(...args) {
  if(allGood) { ... }
  throw new Error(msgs.unfathomableError);
}

```

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
N/A

**Comment by sokra** [comment]
Feel free to send a PR.

**Comment by yeskunall** [comment]
Awesome. I'll get started on it ASAP. This might take a while, considering the large codebase of `webpack`, but I'll keep you guys updated here. 👍

**Comment by TheLarkInn** [comment]
Let us know if you need any assistance along the way!

**Comment by yeskunall** [comment]
Thanks @TheLarkInn! 😄

I've been going over the codebase, and it seems to me like the different logs emitted by `webpack` can be categorized into messages, warnings, and errors. Based on that, I think we should have three separate files to further increase modularity. So, something like...

```js
// messages.json

{
  webpack: {
    update: `webpack update available!`,
    version: `${version}`,
  },
}
```

```js
// warnings.json

{
  compiler: {
    parse: `webpack: Using compiler.parser is deprecated.\nUse compiler.plugin(\"compilation\", function(compilation, data) {\n  data.normalModuleFactory.plugin(\"parser\", function(parser, options) { parser.plugin(/* ... */); });\n}); instead. `,
  },
}
```

```js
// errors.json

{
  chunk: {
    entry: `Chunk.entry was removed. Use hasRuntime()`,
    initial: `Chunk.initial was removed. Use isInitial()`,
    checkConstraints: {
       duplicate: {
          child: `duplicate child in chunk`,
          parent: `child missing parent`,
       },
    },
  },
}
```

Do you guys see the benefit to this method? Do you like this approach?

**Comment by sokra** [comment]
separate files: yes.

Parameters could be passed by using an arrow function:

``` js
module.exports = {
  newVersionAvailable: (old, new) => `The new webpack version ${new} is available. You are currently using ${old}.`
}
```

**Comment by yeskunall** [comment]
Yes, wonderful. I hadn't given much thought to `params` that needed to be passed into the message. Your solution is simple and it should work brilliantly.

I will setup a topic branch and hopefully make a PR with some ground-work done soon enough. Thanks again! ❤️

**Comment by ksvitkovsky** [comment]
@yeskunall how is it going? If you're not working on the issue, I'd like to take it 😊

**Comment by yeskunall** [comment]
I've been a little busy, but I should be able to give this some time. I'll
let you know if you can help me with this somehow! 👍
-- 

Kunall Banerjee
