### ISSUE TITLE
hidden-source-map (correct file names and lines)

### ISSUE THREAD

**Issue by svipben** [webpack/webpack#4736]
**Do you want to request a *feature* or report a *bug*?**
I don't know if it's bug so it can be a feature request or bug.

**What is the current behavior?**
I'm using `hidden-source-map` to hide source code and project structure from browser, this feature hides source map pragma which is `webpack://`, but it produces very bad errors, I mean they are not correct and it's same as not using any source maps at all. `nosources-source-map` works perfectly, because it shows errors good with correct file names and lines, but you can't hide source map pragma which shows all your project structure. It's possible to have source maps enabled if any error occurs to have correct file name and lines without showing source map pragma (project structure), I mean somehow disable `webpack://` in sources and enable correct file names and lines.

**What is the expected behavior?**
Hide source map pragma (`webpack://` in sources) and show correct names with lines for e.g.

THIS:
```
Uncaught ReferenceError: React is not defined
    at Object.8npJ (client.js:16)
```

INSTEAD OF:
```
Uncaught ReferenceError: React is not defined
    at Object.8npJ (main.872f6d65.js:1)
``` 

**If this is a feature request, what is motivation or use case for changing the behavior?**
Everything is described above.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
OS: Linux Ubuntu 16.04
Chrome: 57.0.2987.133 (64-bit)
Node: 7.9.0
Webpack: 2.4.1

**P.S. It seems doesn't matter if you use `sourceMap: true` in `new webpack.optimize.UglifyJsPlugin`, because it doesn't works with `hidden-source-map`, it just generates source maps which are not used. Seems it's impossible to hide source code with source code pragma (project structure) and have correct error lines with file names...**

P.S.S. If anybody is interested here is the project with configured webpack: [svipben/react-boilerplate](https://github.com/svipben/react-boilerplate).

**Comment by sokra** [comment]
No this doesn't work.

But you can use the SourceMap to remap these exception stack traces if they include a column.

**Comment by svipben** [comment]
@sokra Can you please give me an example?

**Comment by sokra** [comment]
https://github.com/mozilla/source-map#sourcemapconsumerprototypeoriginalpositionforgeneratedposition

**Comment by svipben** [comment]
@sokra This is only one solution if I want to use `hidden-source-map`?

**Comment by sokra** [comment]
yeah. The SourceMap is hidden from the browser, so it can't map the stack traces.

**Comment by svipben** [comment]
@sokra Thank you for information.
