### ISSUE TITLE
Image map layer not loaded properly

### ISSUE THREAD

**Issue by burnout87** [webpack/webpack#4739]
**Do you want to request a *feature* or report a *bug*?**
I am not entirely sure if it's bug so it can be a my big mistake given my still small knowledge of WebPack.

**What is the current behavior?**
I want to use a png image as a map layer using the imageOverlay func from Leaflet.
I have set up a WebPack dev server, and the i mage is properly loaded as a layer, allowing me to interact with correctly. 
If I then build the self contained war file and deploy it to Tomcat, I don't get any error, but I simply can't see the image over the map, that instead I could see (and flawlessly interact) in the other case.
 I use file-loader as a loader for the png images files.

To give even more info about the misbehavior, using the Chrome dev tool and inspecting the DOM element of the map in the development environment, the img element created is the following:

`<img class="leaflet-image-layer leaflet-zoom-animated" src="http://localhost:9001/floorplan.png" alt="" style="transform: translate3d(-118px, -15px, 0px); width: 990px; height: 540px;">`

While if I run the webApp on Tomcat, the same tag has the following structure:

`<img class="leaflet-image-layer leaflet-zoom-animated" src="http://localhost:8080/dein-web/floorplan.png" alt="" style="transform: translate3d(-5.19045e+08px, -2.83115e+08px, 0px); width: 1.03809e+09px; height: 5.66231e+08px;">`

**What is the expected behavior?**
The png image should be displayed over the map, and the image DOM element should have the appropriate values.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Browser: Google Chrome, version 57.0.2987.133
Node.js version 6.9.1
npm version 3.10.8
OS Windows 7 Ultimate
WebPack version 2.4.1

**Comment by sokra** [comment]
I can't tell you much here. The path is affected by the `output.publicPath` option. Try to check if the file is on the web-server and where. Adjust the publicPath option as needed. Try other images outside of leaflet to see if it is a leaflet specific problem.

If you still have problems you should better ask on StackOverflow with more details.

---

Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md).
