### ISSUE TITLE
Webpack var injection fails on UCBrowser

### ISSUE THREAD

**Issue by JoyceBabu** [webpack/webpack#4743]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
`undefined` is passed as global object on UC Browser

**If the current behavior is a bug, please provide the steps to reproduce.**
`this` is undefined inside an IIFE in UC Browser. `this` is set to `DOMWindow` in global context, but inside an IIFE, it becomes undefined.

The following code fails with message

> TypeError: Cannot set property 'Promise' of undefined 

```
function(module, exports, __webpack_require__) {

	/* WEBPACK VAR INJECTION */(function(global) {var Yaku = __webpack_require__(/*! ./yaku */ 80);

	try {
	    global.Promise = Yaku;
	    window.Promise = Yaku;
	} catch (err) {
	    null;
	}
	/* WEBPACK VAR INJECTION */}.call(exports, (function() { return this; }())))

/***/ }
```

**What is the expected behavior?**
It appears to be a bug in UC Browser.  But webpack modules should work on all browsers nonetheless.

**If this is a feature request, what is motivation or use case for changing the behavior?**
According to StatsCounter, UC Browser has 8.75% market share. In developing countries like China and India, it is much higher.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Tested with UC Browser v11.2.0 on Android

**Comment by sokra** [comment]
Could you try it with webpack 2, as it has a better global polyfill?

**Comment by JoyceBabu** [comment]
Apologies for not testing with webpack 2. I haven't used webpack before this, and wasn't aware that the above project was using webpack 1. The global polyfill is working correctly in webpack 2.

Thank you.
