### ISSUE TITLE
Module.hot.accept() bug

### ISSUE THREAD

**Issue by daviddelusenet** [webpack/webpack#4744]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The following code doesn't work: 
```
if (module.hot) {
  module.hot.accept('./components/TodoApp', () => {
    render(TodoApp)
  });
}
```

But this works:
```
if (module.hot) {
  module.hot.accept();
}
```

**If the current behavior is a bug, please provide the steps to reproduce.**
I also posted a question on StackOverflow, here I've gone into detail: http://stackoverflow.com/questions/43491310/cant-get-webpack-2-hmr-react-to-work

**What is the expected behavior?**
Using the setup from the documentation: https://webpack.js.org/guides/hmr-react/

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

```
"webpack": "^2.4.1",
"webpack-dev-server": "^2.4.2"
"react": "^15.3.2",
"react-dom": "^15.3.2",
"react-hot-loader": "^3.0.0-beta.6",
```

**Comment by sokra** [comment]
It looks like modules: false is missing in babel config. Presets in webpack config override babelrc.

**Comment by sokra** [comment]
I guess the `latest` preset includes `es2015` and you didn't pass modules: false. avoid using both `.babelrc` + `babel-loader` query.

**Comment by pavel06081991** [comment]
I had the same problem when I used relative path, but with absolute path it worked, try this 
'if (module.hot) {
  module.hot.accept('components/TodoApp', () => {
    render(TodoApp)
  });
}'

**Comment by marvinhagemeister** [comment]
Another workaround is to re-import the dependency:

```js
module.hot.accept('./component', () => {
  import('./component').then(() => render(Component));
});
```
