### ISSUE TITLE
Global args for common builds in examples

### ISSUE THREAD

**Issue by aretecode** [webpack/webpack#4751]
Why are there global variables to pass around arguments used for a function call?

https://github.com/webpack/webpack/blob/master/examples/explicit-vendor-chunk/build.js#L1
https://github.com/webpack/webpack/blob/master/examples/build-common.js

**Comment by sokra** [comment]
I would be better if build-common exports a function that is called with an options object.
But I guess I was too lazy an didn't want to change every example build.js file.

Feel free to change this and send a PR.

**Comment by aretecode** [comment]
@sokra ok thanks, I was wondering if there was a reason.

**Comment by ooflorent** [comment]
Fixed by #5387
