### ISSUE TITLE
export function not hoisted

### ISSUE THREAD

**Issue by lukescott** [webpack/webpack#4753]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

`export function foo() {}` is not hoisted above import. With code below, you get:

console.log(foo) -> `undefined`

**If the current behavior is a bug, please provide the steps to reproduce.**

foo.js
```js
import {bar} from "./bar";
export function foo() {}
```

bar.js
```js
import {foo} from "./foo";
console.log(foo);
```

index.js
```js
import "./foo";
```

.babelrc:
```json
{
	"presets": [
		["latest", {"es2015": {"modules": false}}],
	],
}
```

**What is the expected behavior?**

console.log(foo) -> `function foo() {}`

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

- Max OS X 10.11.6
- Chrome 57
- Node 7.8.0
- webpack 2.3.3

When you remove `["latest", {"es2015": {"modules": false}}],` from .babelrc (set modules to true) it works as expected.

Babel produces this for foo.js:

```js
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.foo = foo;

var _bar = require("./bar");

function foo() {}
```

If I change foo.js to this it breaks with babel:

```js
import {bar} from "./bar";
function foo() {}
export {foo}
```

This is what babel produces:

```js
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.foo = undefined;

var _bar = require("./bar");

function foo() {}
exports.foo = foo;
```

It seems that Babel makes a distinction between `export function foo{}` and `function foo() {}; export {foo}` and webpack does not.

**Comment by loganfsmyth** [comment]
Looks like they are both a little wrong.

```
function foo(){}
export {foo};
```
and
```
export function foo(){}
```
should _both_ export `foo` before processing the imported modules. Functions declaration bindings are initialized with their values before evaluating their imported modules.

**Comment by lukescott** [comment]
Is `var` hoisted the same way as `function`? So does this also apply?
```js
import {bar} from "./bar";
export var foo = "foo"
```
I get `undefined` for this case as well.

**Comment by loganfsmyth** [comment]
For var it would be undefined and for let/const it would be a tdz error
