### ISSUE TITLE
Logging / Log Levels

### ISSUE THREAD

**Issue by nmccready** [webpack/webpack#476]
It would be excellent if the library was using (winston) a logger that allowed webpack options to disable all the output to different levels. (NONE,INFO,DEBUG, WARN,ERROR) . I dug through the code a little and I see console.logs everywhere. 

Therefore this seems to be a decent task.

In the end it would be nice.
```
webpack.logLevel =  'NONE';
```

**Comment by bsr203** [comment]
+1

**Comment by newtriks** [comment]
+1

**Comment by ColCh** [comment]
Log levels are simplier than __stats:BOOL_FLAG__, so I "plus one" too

**Comment by simonzack** [comment]
+1

**Comment by nmccready** [comment]
My team is considering taking this on as a techdebt issue. However, I need some guidance as to where to start. I have no desire to do this and have the PR fail to get merged.

**Comment by sokra** [comment]
I would love to hear how log levels should look like when they are implemented. Does they only affect the CLIs? Should they be just a another way to configurate the stats output?

**Comment by nmccready** [comment]
A bare minimum right now is to reduce the stats output (and be able to disable it). A great feature would be to only show stats output of critical and error level items.

**Comment by sloria** [comment]
+1. Would love to see this as well.

**Comment by newtriks** [comment]
@sokra , I agree with @nmccready's response. I personally have little need to monitor anything other than related errors or warnings. A flag to see the full verbose logs would be beneficial but used little personally.

**Comment by edword** [comment]
+1

**Comment by aluksidadi** [comment]
+1

**Comment by jaraquistain** [comment]
+1

**Comment by nmccready** [comment]
I dig farther into the code and the one thing I wanted was suppress the asset output. To do this in your options add 
```
stats:
        assets: false
```

**Comment by nmccready** [comment]
https://github.com/webpack/webpack/blob/master/bin/webpack.js#L68

Here is all the stuff you can hide:

https://github.com/webpack/webpack/blob/master/lib/Stats.js#L26-L40

**Comment by MoOx** [comment]
Cool for sharing this @nmccready !

`chunkModules` might be the key everyone wants to disable ;)

**Comment by tony612** [comment]
@nmccready Thanks for this!

**Comment by karlnp** [comment]
thanks, @nmccready ! adding this to my list of things to add to the documentation in a PR.

**Comment by nmccready** [comment]
Should this be closed? The stats options is sufficient for me.

**Comment by SimenB** [comment]
Having a way of doing this that's the same as most other CLIs (passing `-v` or `-vv` etc.) or programmatically setting `logLevel` would be preferable. While I, and others in this thread, know about `stats`, not requiring domain specific knowledge about Webpack would be preferable, wouldn't it?

**Comment by mathieumg** [comment]
:+1: Is there any way to do that silencing in your `webpack.config.js` currently?

**Comment by MrFusion42** [comment]
PR #1323 implements this, the next release should include the functionality

**Comment by bebraw** [comment]
Merged so closing.

**Comment by Download** [comment]
Is this undocumented? I am having a hard time finding the docs on the relevant settings.

**Comment by bebraw** [comment]
@Download There's a documentation task, https://github.com/webpack/webpack/issues/1660. No official docs yet, though. You'll have to dig it from the PR at https://github.com/webpack/webpack/pull/1323 I'm afraid.

**Comment by Download** [comment]
@bebraw Ok thanks!

**Comment by Download** [comment]
@bebraw With some experimentation I got it to work, thanks! Just one more question: The `stats` option is part of the `devServer` config option right? But how can I influence the logging of the regular `webpack` output?

I am calling webpack twic in my startup script, once for the server-side and once for the client-side:

```js
"watch-server": "webpack --inline --watch --config webpack/development.server.config.js",
"watch-client": "webpack-dev-server --watch --config webpack/development.client.config.js",
```

The ouput for `watch-client` is now exactly as I want it, but for `watch-server` these settings don't seem to have any effect... Any ideas?

**Comment by bebraw** [comment]
@Download Correct. The interface doesn't seem to be consistent with webpack and webpack-dev-server. By the looks of it, you would have to do something like ` stats.toString({chunks:false})` against webpack Node API to reduce the amount of output in the default case. There might be some CLI flags around to help with this but nothing simple on a quick look.

**Comment by Download** [comment]
@bebraw Thanks for your comment. I suspected as much. As you said the CLI does offer a solution. I found that if I add the command line option `--hide-modules` to the call to Webpack, it results in the right amount of logging for me.

However there is an opportunity for improvement here I think. It would be great if it would be possible to specify the logging in the `webpack.config.js`. It essentially is in the wrong place now, because the settings aren't actually dev-server specific (or shouldn't have to be at least) as they mostly deal with the compilation process itself...

**Comment by MegaJsTeam** [comment]
how to disable console log in wev-server
it's a hell
![image](https://cloud.githubusercontent.com/assets/17149958/13075303/247c8cd8-d4bb-11e5-9731-c7d91975f124.png)

**Comment by Download** [comment]
[shameless plug]
Use [picolog](https://github.com/download/picolog), then replace the `console` object with the picolog object. All logging should disappear as picolog's standard log level is `WARN`. Add `?log=info` or `?log=debug` etc to the URL to change log levels, or change them directly in the console by executing `console.level = console.INFO` (assuming you replaced the console with the picolog object)
