### ISSUE TITLE
default exports bug

### ISSUE THREAD

**Issue by jmlopez-rod** [webpack/webpack#4761]
**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?** Default exports seem to make it hard for webpack to do proper tree shaking.

**If the current behavior is a bug, please provide the steps to reproduce.**

Please see https://github.com/jmlopez-rod/lodash-webpack2
This repo contains 3 files: `app.bundle.ts`, `custom.ts` and `random.ts`.

`random.ts` only has one simple function that returns a string which we can look up in our final bundle. `custom.ts` imports a collection of functions that we can use, in this case, it imports and exports `random` as well as `lodash-ts/isArray`.

To see the issue first run `npm install` then `webpack`. This will generate the file `dist/app.js`. In this file you will see

```js
/* 14 */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
/**
 * Checks if `value` is classified as an `Array` object.
 *
 * @static
 * @memberOf _
 * @since 0.1.0
 * @category Lang
 * @param {*} value The value to check.
 * @returns {boolean} Returns `true` if `value` is an array, else `false`.
 * @example
 *
 * _.isArray([1, 2, 3]);
 * // => true
 *
 * _.isArray(document.body.children);
 * // => false
 *
 * _.isArray('abc');
 * // => false
 *
 * _.isArray(_.noop);
 * // => false
 */
var isArray = Array.isArray;

/* harmony default export */ __webpack_exports__["a"] = (isArray);
``` 

And if we search for `from random.ts` you we'll find

```js
/* 54 */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
/* unused harmony export random */
function random() {
    return 'from random.ts';
}



/***/ }),
```

Here we can clearly see how using named exports helped webpack know that we did not use the function. Now, here is where we can see something interesting. Modify the file `node_modules/lodash-es/isArray.js` so that it may do named exports. That is, make it like this:

```js
/**
 * Checks if `value` is classified as an `Array` object.
 *
 * @static
 * @memberOf _
 * @since 0.1.0
 * @category Lang
 * @param {*} value The value to check.
 * @returns {boolean} Returns `true` if `value` is an array, else `false`.
 * @example
 *
 * _.isArray([1, 2, 3]);
 * // => true
 *
 * _.isArray(document.body.children);
 * // => false
 *
 * _.isArray('abc');
 * // => false
 *
 * _.isArray(_.noop);
 * // => false
 */
var isArray = Array.isArray;
// default export isArray;
export { isArray };
```

and modify `custom.ts` to properly import `isArray`:

```
import { default as assign } from 'lodash-es/assign';
import { isArray } from 'lodash-es/isArray';
import { random } from './random';

export {
  assign,
  isArray,
  random,
};
```
After running `webpack` again we should see that `isArray` is now considered an unused function:

```js
/* 14 */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
/* unused harmony export isArray */
/**
 * Checks if `value` is classified as an `Array` object.
 *
 * @static
 * @memberOf _
 * @since 0.1.0
 * @category Lang
 * @param {*} value The value to check.
 * @returns {boolean} Returns `true` if `value` is an array, else `false`.
 * @example
 *
 * _.isArray([1, 2, 3]);
 * // => true
 *
 * _.isArray(document.body.children);
 * // => false
 *
 * _.isArray('abc');
 * // => false
 *
 * _.isArray(_.noop);
 * // => false
 */
var isArray = Array.isArray;
// export default isArray;
```

**What is the expected behavior?**

`export default` should work?  There just seems to be strange behaviours with `export default`, for this reason I just never use them (babel and typescript treat them differently).

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

- node: 6.10.2
- webpack: 2.4.1
- OS: macOSX 10.12

**Comment by sokra** [comment]
In a minimal example the following code is generated:

``` js
export default "a";
```

``` js
"use strict";
/* unused harmony default export */ var _unused_webpack_default_export = ("a");
```

``` js
var b = "b";

export { b };
```

``` js
"use strict";
/* unused harmony export b */
var b = "b";
```

I haven't looked into your example yet, but are you sure that the export is not used?

**Comment by sokra** [comment]
Also try `--display-used-exports` and `--display-reasons`

**Comment by jmlopez-rod** [comment]
I have updated my example. The original one I talked about here with `assign` and `isArray` is not a fair one since `assign` uses `isArray`. Thus, when I removed the default import everything broke. So, that was a bad example. A good one though, is one using `isArray` and `castArray`.

`isArray` doesn't have any dependencies. and `castArray` only depends on `isArray`. If you look at the new example in the master branch you should see what I mentioned in the README. Mainly `castArray` is included in the bundle. Which is not good.

The good news though, is that I made another build of `lodash-es` in the `no-default-exports` branch and everything seems to work fine. Sure, the initial bundle is big because it needs to put everything in there, but the import thing is that it marks it as unused.

I will try the flags next.

**Comment by jmlopez-rod** [comment]
On the `no-default-export` branch I get messages like this:

```
 [260] ./src/custom.js 132 bytes {0} [built]
       [only some exports used: isArray]
       harmony import ./custom [258] ./src/app.bundle.ts 1:0-35
 [488] ./src/lodash-es/lodash.js 13.6 kB {0} [built]
       [only some exports used: isArray]
       harmony import ./lodash-es/lodash [260] ./src/custom.js 1:0-56
 [618] ./src/random.js 70 bytes {0} [built]
       [no exports used]
```

Which is right, I only use `isArray` from `./src/lodash-es/lodash.js`.

Now I'll run the same in master:

```
 [629] ./~/lodash-es/lodash.js 17.2 kB {0} [built]
       [only some exports used: isArray]
```

weirdly enough, this is leading me to believe that I'm only using that, yet, in my app.js bundle I still see the export for castArray.

```js
/* harmony default export */ __webpack_exports__["a"] = (castArray);
```

I would encourage to do some testing on lodash having a build using only name exports as I have done and see if this can give some insights for the root of the problem.

**Comment by sokra** [comment]
castArray is used here:

* lang.default.js uses it in it's default export
* lang.default.js is used in lang.js
* lang.js is used in lodash.default.js (sideeffect of adding it to the lodash wrapper)
* lodash.default.js is imported in lodash.js (the export is not used, but sideeffects are still executed)

---

Note the export in lang.default.js:

``` js
export default {
  castArray, clone, cloneDeep, cloneDeepWith, cloneWith,
  conformsTo, eq, gt, gte, isArguments,
  ...
};
```

Is different from

``` js
export {
  castArray, clone, cloneDeep, cloneDeepWith, cloneWith,
  conformsTo, eq, gt, gte, isArguments,
  ...
};
```

The first one is a simple js object and difficult to tree shake

---

Note the sideeffect in lodash.default.js:

``` js
// Add methods that return wrapped values in chain sequences.
lodash.after = func.after;
lodash.ary = func.ary;
lodash.assign = object.assign;
lodash.assignIn = object.assignIn;
lodash.assignInWith = object.assignInWith;
```

The imported symbols `func`, `object`, etc. are always marked as used, because they are used in a sideeffect and sideeffects are always executed (by spec).

**Comment by jmlopez-rod** [comment]
Very good point on `export default {..` vs `export {`. In `lodash.default.js`. The object `lodash` has a lot of functions, there is nothing we can do about it, they would have to be included if we actually use `lodash`. In my example I don't.

Either way, I think we are on to something here. If you see the branch [`no-default-export`](https://github.com/jmlopez-rod/lodash-webpack2/tree/no-default-export) you can see we are exporting the default object. If I were to import this object in my code then for sure `castArray` would have been included.

I just tried modifying `lang.default.js` to have this:

```js
var defaultExport = {
  castArray, clone, cloneDeep, cloneDeepWith, cloneWith,
  conformsTo, eq, gt, gte, isArguments,
  isArray, isArrayBuffer, isArrayLike, isArrayLikeObject, isBoolean,
  isBuffer, isDate, isElement, isEmpty, isEqual,
  isEqualWith, isError, isFinite, isFunction, isInteger,
  isLength, isMap, isMatch, isMatchWith, isNaN,
  isNative, isNil, isNull, isNumber, isObject,
  isObjectLike, isPlainObject, isRegExp, isSafeInteger, isSet,
  isString, isSymbol, isTypedArray, isUndefined, isWeakMap,
  isWeakSet, lt, lte, toArray, toFinite,
  toInteger, toLength, toNumber, toPlainObject, toSafeInteger,
  toString
};

export { defaultExport };
```

Instead of relying on the `export default`. The only file that references this is `lang.js`so I modified it as well. All seems to be working there.

I should note that I used the custom build I used was inspired by this comment: https://github.com/webpack/webpack/issues/1750#issuecomment-294325350. I had to modify the lodash-cli so that it could generate named imports and exports, thus the result is committed in the `no-default-export` branch. @jdalton I would check out that build and see if something is completely wrong there that allows me to get the results I expect.

In both builds (the one in npm) and the one I made with named exports I am exporting the default lodash object. Yet, the one with named exports only seems to be able to figure out that a lot of the functions are not used.

@obartra mentioned in this comment that he removed the default export and that it didn't seem to matter. In my case, I include everything, the only main change is using named exports. Can someone try making their own custom build of lodash with only named exports and see if it works?

As a final note, I should mention that the following rollup example is very similar to how lodash is build:

[rollup](https://rollupjs.org/repl?version=0.41.6&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMGN1YmUlMjAlN0QlMjBmcm9tJTIwJy4lMkZsb2Rhc2guanMnJTNCJTVDbmNvbnNvbGUubG9nKCUyMGN1YmUoJTIwNSUyMCklMjApJTNCJTIwJTJGJTJGJTIwMTI1JTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMnNxdWFyZS5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjIlMkYlMkYlMjBUaGlzJTIwZnVuY3Rpb24lMjBpc24ndCUyMHVzZWQlMjBhbnl3aGVyZSUyQyUyMHNvJTVDbiUyRiUyRiUyMFJvbGx1cCUyMGV4Y2x1ZGVzJTIwaXQlMjBmcm9tJTIwdGhlJTIwYnVuZGxlLi4uJTVDbmV4cG9ydCUyMGZ1bmN0aW9uJTIwc3F1YXJlJTIwKCUyMHglMjApJTIwJTdCJTVDbiU1Q3RyZXR1cm4lMjB4JTIwKiUyMHglM0IlNUNuJTdEJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmN1YmUuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyJTJGJTJGJTIwVGhpcyUyMGZ1bmN0aW9uJTIwZ2V0cyUyMGluY2x1ZGVkJTVDbmV4cG9ydCUyMGZ1bmN0aW9uJTIwY3ViZSUyMCglMjB4JTIwKSUyMCU3QiU1Q24lNUN0JTJGJTJGJTIwcmV3cml0ZSUyMHRoaXMlMjBhcyUyMCU2MHNxdWFyZSglMjB4JTIwKSUyMColMjB4JTYwJTVDbiU1Q3QlMkYlMkYlMjBhbmQlMjBzZWUlMjB3aGF0JTIwaGFwcGVucyElNUNuJTVDdHJldHVybiUyMHglMjAqJTIweCUyMColMjB4JTNCJTVDbiU3RCUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJsb2Rhc2guanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwJTdCJTIwc3F1YXJlJTIwJTdEJTIwZnJvbSUyMCcuJTJGc3F1YXJlLmpzJyUzQiU1Q25leHBvcnQlMjAlN0IlMjBjdWJlJTIwJTdEJTIwZnJvbSUyMCcuJTJGY3ViZS5qcyclM0IlNUNuJTVDbmNvbnN0JTIwbG9kYXNoJTIwJTNEJTIwJTdCJTIwc3F1YXJlJTJDJTIwY3ViZSUyMCU3RCUzQiU1Q25leHBvcnQlMjAlN0IlMjBsb2Rhc2glMjAlN0QlM0IlMjIlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyY2pzJTIyJTJDJTIybW9kdWxlTmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMm1vZHVsZUlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZXhhbXBsZSUyMiUzQW51bGwlN0Q=)

**Comment by jdalton** [comment]
@jmlopez-rod I'm not super interested in investigating this at this time. We offer the [babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash) that solves the issue across bundlers and other libraries. Lodash v5 (the next major release) won't ship with a monolithic build (so forces folks to cherry-pick) out of the box.

**Comment by jmlopez-rod** [comment]
That's good news about lodash 5 not having the default object. Hopefully we'll be able to do `import { castArray } from 'lodash'` and only bundle `castArray` and `isArray` (given that those definitions stay as they currently are). Any estimated time for its release?

**Comment by jdalton** [comment]
The lib itself won't be exported through `'lodash'` at all. You'll have to specify `import castArray from 'lodash/castArray'`. As for a time, I'm hoping in the next couple of months. There's some ecosystem things I need to get in place first.

**Comment by sheepsteak** [comment]
For reference I've had similar issues with Rollup too. Not with `lodash` but my own module I was writing. I found I could only get tree-shaking working as expected if I used Rollup to place everything in a single file with named exports first.

**Comment by jmlopez-rod** [comment]
Last night I decided to look a bit further into why we cannot tree shake `lodash-es`. It seems more obvious to me now that the problem is **not** webpack. The issue most likely has to do with how lodash is written. At the moment it is not obvious to how to write lodash so that it can be shakable, but I have gathered some tips by playing with rollup.

Consider this short [example](https://rollupjs.org/repl?version=0.41.6&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMGN1YmUlMjAlN0QlMjBmcm9tJTIwJy4lMkZsb2Rhc2guanMnJTNCJTVDbmNvbnNvbGUubG9nKCUyMGN1YmUoJTIwNSUyMCklMjApJTNCJTIwJTJGJTJGJTIwMTI1JTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMnNxdWFyZS5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBkZWZhdWx0JTIwZnVuY3Rpb24lMjBzcXVhcmUoeCklMjAlN0IlMjByZXR1cm4lMjB4JTIwKiUyMHglM0IlMjAlN0QlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyY3ViZS5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBkZWZhdWx0JTIwZnVuY3Rpb24lMjBjdWJlKHgpJTIwJTdCJTIwcmV0dXJuJTIweCUyMColMjB4JTIwKiUyMHglM0IlMjAlN0QlMjIlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIybG9kYXNoLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMCU3QiUyMGRlZmF1bHQlMjBhcyUyMHNxdWFyZSUyMCU3RCUyMGZyb20lMjAnLiUyRnNxdWFyZS5qcyclM0IlNUNuZXhwb3J0JTIwJTdCJTIwZGVmYXVsdCUyMGFzJTIwY3ViZSUyMCU3RCUyMGZyb20lMjAnLiUyRmN1YmUuanMnJTNCJTVDbmV4cG9ydCUyMCU3QiUyMGRlZmF1bHQlMjAlN0QlMjBmcm9tJTIwJy4lMkZsb2Rhc2guZGVmYXVsdC5qcyclM0IlNUNuJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmxvZGFzaC5kZWZhdWx0LmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMGxhbmclMjBmcm9tJTIwJy4lMkZsYW5nLmpzJyUzQiU1Q25pbXBvcnQlMjBsb2Rhc2glMjBmcm9tJTIwJy4lMkZ3cmFwcGVyTG9kYXNoLmpzJyUzQiU1Q25sb2Rhc2guc3F1YXJlJTIwJTNEJTIwbGFuZy5zcXVhcmUlM0IlNUNubG9kYXNoLmN1YmUlMjAlM0QlMjBsYW5nLmN1YmUlM0IlNUNuZXhwb3J0JTIwZGVmYXVsdCUyMGxvZGFzaCUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJsYW5nLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMCU3QiUyMGRlZmF1bHQlMjBhcyUyMHNxdWFyZSUyMCU3RCUyMGZyb20lMjAnLiUyRnNxdWFyZS5qcyclM0IlNUNuZXhwb3J0JTIwJTdCJTIwZGVmYXVsdCUyMGFzJTIwY3ViZSUyMCU3RCUyMGZyb20lMjAnLiUyRmN1YmUuanMnJTNCJTVDbmV4cG9ydCUyMCU3QiUyMGRlZmF1bHQlMjAlN0QlMjBmcm9tJTIwJy4lMkZsYW5nLmRlZmF1bHQuanMnJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMndyYXBwZXJMb2Rhc2guanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIydmFyJTIwbG9kYXNoJTIwJTNEJTIwZnVuY3Rpb24oKSUyMCU3QiU3RCUzQiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwbG9kYXNoJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmxhbmcuZGVmYXVsdC5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjBzcXVhcmUlMjBmcm9tJTIwJy4lMkZzcXVhcmUuanMnJTNCJTVDbmltcG9ydCUyMGN1YmUlMjBmcm9tJTIwJy4lMkZjdWJlLmpzJyUzQiU1Q25leHBvcnQlMjBkZWZhdWx0JTIwJTdCJTIwc3F1YXJlJTJDJTIwY3ViZSUyMCU3RCUzQiUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJjanMlMjIlMkMlMjJtb2R1bGVOYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJnbG9iYWxzJTIyJTNBJTdCJTdEJTJDJTIybW9kdWxlSWQlMjIlM0ElMjIlMjIlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==).

In here I have tried to replicate the feeling of how the main lodash object is created. In this case I have attached the `cube` and `square` functions to the object. Now, in our main file we only use `cube` so we never use the main object. Why then does rollup include the definition for `square`?

In this case I think it is because of how I defined `lodash` in `wrapperLodash.js`. Notice that I have defined it as a variable and then I use this variable to attach `square` and `cube` to it. Because of this rollup thinks that this code must be executed. To be able to shake it simply have the following
in `wrapperLodash.js`:

```
function lodash() {};
export default lodash;
```

I think this tells rollup that the object `lodash` is now 'concrete', that is, we will not be able to reassign something to `lodash`. It is ok to attach things to it, but the object to which `lodash` is pointing to won't change.

The lodash library has many exported objects that are variables that are used while it builds the object. Look at `now.js`, or better yet, `_getTag.js`. In `_getTag.js` the exported object starts being `baseGetTag` but if it meets a certain condition then it changes to another function. I think that this is what makes webpack and rollup think that `_getTag` will need to included.

Here you can see an even shorter example showing how [exporting variables is bad for shaking](https://rollupjs.org/repl?version=0.41.6&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMGN1YmUlMjAlN0QlMjBmcm9tJTIwJy4lMkZsb2Rhc2guanMnJTNCJTVDbmNvbnNvbGUubG9nKCUyMGN1YmUoJTIwNSUyMCklMjApJTNCJTIwJTJGJTJGJTIwMTI1JTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMnNxdWFyZS5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJ2YXIlMjBzcXVhcmUlMjAlM0QlMjBmdW5jdGlvbih4KSUyMCU3QiUyMHJldHVybiUyMHglMjAqJTIweCUzQiUyMCU3RCU1Q25leHBvcnQlMjBkZWZhdWx0JTIwc3F1YXJlJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmN1YmUuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwZGVmYXVsdCUyMGZ1bmN0aW9uJTIwY3ViZSh4KSUyMCU3QiUyMHJldHVybiUyMHglMjAqJTIweCUyMColMjB4JTNCJTIwJTdEJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmxvZGFzaC5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAlN0IlMjBkZWZhdWx0JTIwYXMlMjBzcXVhcmUlMjAlN0QlMjBmcm9tJTIwJy4lMkZzcXVhcmUuanMnJTNCJTVDbmltcG9ydCUyMCU3QiUyMGRlZmF1bHQlMjBhcyUyMGN1YmUlMjAlN0QlMjBmcm9tJTIwJy4lMkZjdWJlLmpzJyUzQiU1Q25zcXVhcmUuYSUyMCUzRCUyMDMlM0IlNUNuJTVDbmV4cG9ydCUyMCU3QiUyMHNxdWFyZSUyQyUyMGN1YmUlMjAlN0QlM0IlNUNuJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm1vZHVsZU5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlMkMlMjJtb2R1bGVJZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE) 

Is there any dos and don'ts on how to write shakable libraries? In my quest I also found out that if you use an undefined reference it can make rollup include everything. Unfortunately I have not been able to create a short example showcasing this.

I think this is enough of me going into the rabbit hole. It has been fun. I hope later I can find some good tips so that my future libraries can be shakable. For now I think it may be best to wait for lodash 5 (that, or lodash-es removes the default object from `lodash.js`).

**Comment by jdalton** [comment]
Was there anything actionable here on Lodash's part?

**Comment by jmlopez-rod** [comment]
I honestly don't know, I tried playing around with the current build of `lodash-es` trying to see if I can make it work but I just don't know enough to pinpoint what can be changed.

That is why I made the examples I provided to get a bit of an insight. I suppose, if you have time to spare I would try to test lodash with only a few functions attached to the main object and try to see when webpack thinks it needs to include everything.

As far as I can tell there are too many `vars` being exported and then modified in lodash, and from the examples I provided, that makes webpack and rollup include that code.

**Comment by jdalton** [comment]
lodash-es is [split out in a way that should be it easier to tree shake](https://github.com/lodash/lodash/blob/es/lodash.js) since the `default` export is isolated. It's easy enough to chip away at. I get the excuse of "but the spec says", but honestly the spec says a lot of things and we get by with close-enough solutions like Babel.

**Comment by Jorybraun** [comment]
I'm dealing with this right now,

**Comment by jmlopez-rod** [comment]
It does, I use it in one of my apps

```
import {
  map,
  find,
  keys,
  filter,
  endsWith,
  startsWith,
} from 'lodash-es';
```

The only issue is that because I'm importing from that index file directly I also get

```
export { default } from './lodash.default.js';
```

which is not shakable for reasons which I do not know. In my case I use typescript so I cannot use the babel plugin to change the imports. Either way, I think that if you remove the `lodash.default.js` from `lodash.js` then things would be shakable. I got a 100K reduction by removing that line and using my imports as I showed above.

I guess all I want to say is that writing shakable libraries is hard. One wrong statement in the code and we can get the everything.

**Comment by hccampos** [comment]
Same experience here. For now we have been cherry-picking everything manually. Until today I realized our bundle was larger than expected. Sure enough a quick search showed that someone had accidentally done `import { remove } from 'lodash-es'` instead of `import remove from 'lodash-es/remove'`

**Comment by jdalton** [comment]
@jmlopez-rod 
>The only issue is that because I'm importing from that index file directly I also get
```js
export { default } from './lodash.default.js';
```

Yep, webpack should be able to detect that you're not importing the `default` and so should be able to exclude it.

**Comment by jmlopez-rod** [comment]
@hccampos The worst part about cherry picking is that even if you are careful choosing what you want and one of your dependencies does `import { remove } from 'lodash-es'` then your bundle will have everything on it.
