### ISSUE TITLE
[Feature Request] Dll reference dependencies changed handling.

### ISSUE THREAD

**Issue by mc-zone** [webpack/webpack#4763]
**Do you want to request a *feature* or report a *bug*?**
# Feature : Dll reference dependencies changed handling 

**What is the current behavior?**

When we referencing a `Dll` bundle for a ` entry`, the deps which has already included into this `Dll` will not be added into the `entry` anywhere. It‘s cool about code/bundle splitting.
But if anyone of the deps has been changed, nothing will happen. This means we should find out the changes, then figure out whether we need rebuild the `Dll` manually before we build the `entry`.

**If this is a feature request, what is motivation or use case for changing the behavior?**

When some deps has changed, maybe it will more friendly if we can throw some hint/warning, or even support fallback to add into the entry (enabled by `DllReferencePlugin` options will elegantly).

Assuming we can add hash/md5 of deps source into Dll's `manifest.json`, and check this when it be referenced in compilation, this feature can be implemented.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

No more env required. Just a suggesttion :)

**Comment by sokra** [comment]
Modules that are part of the DLL are not read in the main compilation.

**Comment by mc-zone** [comment]
Oh, I realized that there are performance consumptions if touch Dll's source files again.

How about just give a option to enable the warning? Save hash in Dll `manifest.json`, check hash in `DllReferencePlugin` after the `Compiler` done, if warning enabled.
