### ISSUE TITLE
Compiled module cache is not shareable/swappable

### ISSUE THREAD

**Issue by oliverwoodings** [webpack/webpack#4765]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

The in-memory compiled module cache used inside webpack is isolated to each compiler instance. This means it is not possible to re-use the cache between instances.

**What is the expected behavior?**

It would be very useful to be able to control/swap the cache implementation, especially if the caching API was async. This would open up the possibility of advanced features such as sharing module caches across machines/networks (e.g. multiple compiler instances running on separate hosts all sharing the same compiled module cache in a redis cluster).

**If this is a feature request, what is motivation or use case for changing the behavior?**

See my recent lightning talk at React London conference about how at Qubit we are running webpack across multiple hosts at scale - https://www.youtube.com/watch?v=mkUK2SZ8moY

Currently whenever a new instance of our compiler service starts up it has a cold compiled module cache, which means upon every deploy or scaling event our builds get a big spike in duration.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

This is continuation of a discussion with @TheLarkInn on twitter earlier today - https://twitter.com/TheLarkInn/status/855373050195456000

**Comment by oliverwoodings** [comment]
Very interesting plugin, @niieani ! Thanks for linking it, i've not seen it before. That's definitely along the lines of what we want to achieve, so its awesome that it might be possible with a plugin instead of needing work done inside webpack itself. I'd need to have a look to see if we could adapt HardSourceWebpackPlugin to support different types of caches (i.e. remote ones like redis) so it would fit into our model.

**Comment by sokra** [comment]
@oliverwoodings you can experiment with the https://github.com/webpack-contrib/cache-loader.

It allow to cache on disk, but you need to make sure that loader configuration is equal or loader options have a unique `ident`.

**Comment by oliverwoodings** [comment]
@sokra ah awesome, thanks! What about if i wanted to share that cache across the network, i.e if the instances are running on separate VMs/entirely different machines? Would you suggest making the cacheing mechanism of `cache-loader` pluggable, or making an entirely separate loader e.g. `redis-cache-loader`?

**Comment by niieani** [comment]
Sometimes you're naughty @webpack-bot, but we still love you ❤️ !

**Comment by sokra** [comment]
btw. there is a PR for making the caching stuff in the cache-loader plugable.
