### ISSUE TITLE
Missing commonjs2 from externals causes require(undefined) in bundle

### ISSUE THREAD

**Issue by richardsimko** [webpack/webpack#4771]
**Do you want to request a *feature* or report a *bug*?**

A bug

**What is the current behavior?**

I'm writing a library which relies on some externals, the library is defined as follows:

    output: {
      path: path.resolve(__dirname, 'lib'),
      filename: 'common-utils.js',
      library: 'common-utils',
      libraryTarget: 'umd'
    }

And I had externals defined like this:

    jquery: {
      commonjs: 'jquery',
      amd: 'jquery',
      root: '$'
    }

The result was a bundle with the following lines at the start

    (function webpackUniversalModuleDefinition(root, factory) {
	if(typeof exports === 'object' && typeof module === 'object')
		module.exports = factory(require(undefined));

These require statements do of course not work and webpack will throw the error `Critical dependency: the request of a dependency is an expression` upon consumption of the lib.

If I add `commonjs2: 'jquery'` to the external definition it works.

**If the current behavior is a bug, please provide the steps to reproduce.**

See above

**What is the expected behavior?**

An error is thrown for the missing option. While I do realize that this is a screwup on my part, debugging it was a pain. The related [docs](https://webpack.js.org/configuration/externals/) also don't mention this as a potential pitfall, nor does the [guide on writing a library](https://webpack.js.org/guides/author-libraries/#add-externals)

**If this is a feature request, what is motivation or use case for changing the behavior?**

N/A

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
webpack: 2.2.1
node: v6.10.0
OS: Mac OS X 10.11.6

**Comment by sokra** [comment]
Yeah this is a great idea. Please send a PR to add an error in this case.

**Comment by richardsimko** [comment]
Is there any preferred place to do this validation? I've found that [`externalsRequireArray`](https://github.com/webpack/webpack/blob/34315db3ffe20b3d7e9a50885ea623fc90ac0861/lib/UmdMainTemplatePlugin.js#L71) iterates over the externals and at that point the request will be `undefined` if the specific definition is missing. Would that be a correct place to error out or is there a validation step done prior to that where I should add this check?
