### ISSUE TITLE
Cannot find module "." When I use require.context

### ISSUE THREAD

**Issue by yleo77** [webpack/webpack#4772]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
The code snippet should work as expected, I think. But in fact, it's not work as expected when i using *Identifier* instead of *Literal*.

```javascript
var regexp = /^\.\/.*\.js$/;
var req = require.context("./templates", false, regexp);   // Uncaught Error

var bool = false;
var req = require.context("./templates", bool, /^\.\/.*\.js$/);   // Uncaught Error

var dir = "./templates";
var req = require.context(dir, false, /^\.\/.*\.js$/);   // Uncaught Error
```

**If the current behavior is a bug, please provide the steps to reproduce.**

main.js (or anywhere in javascript files)

```javascript
var regexp = /^\.\/.*\.js$/;
var req = require.context("./templates", false, regexp);   // Uncaught Error
```

This code above the line can reproduce the bug.

**What is the expected behavior?**
No Error. When i use  *Identifier* instead of *Literal*.

**Please mention other relevant information such as the browser version, Node.js version, webpack 
version and Operating System.**

Max OS X 10.12
Node 7.8.0
webpack 1.x 2.x

FYI, I found the return value at L17 in *lib/dependencies/RequireContextDependencyParserPlugin.js* file is wrong, the expected type is a RegExp, But it's not in fact.

Further info,  something about evaluate in **Parser.js**, for example:

```javascript
this.plugin("evaluate Identifier", function(expr) {
  //...
  if(this.scope.definitions.indexOf(expr.name) === -1) {	
  //...
  } else {
    return this.applyPluginsBailResult1("evaluate defined Identifier " + name, expr);
  }
});
```

But I don't find `this.plugin("evaluate defined Identifier", function(expr) {...});`, am i missing something?

**Comment by sokra** [comment]
It must be statically analyzable... Only literals are supported.

**Comment by sneakyfildy** [comment]
What if someone do not need to require all images from the folder, how we supposed to require only certain images without referencing them one by one with hardcoded set of require calls

**Comment by mcm-ham** [comment]
I needed this behaviour too, a workaround is to use webpack define plugin:

boot-tests.ts
```
require.context(CLIENT_APP_PATH, true, /\.spec\.ts$/);
```

webpack.config.js
```
module.exports = {
  plugins: [new DefinePlugin({ CLIENT_APP_PATH: JSON.stringify('c:/path/to/client') })]
}
```

This works because the DefinePlugin does a find of the name and replaces it with the string on compile.

**Comment by JounQin** [comment]
@sokra The error should be more specific, I wasted a few hours to find out why it throw an error here...

**Comment by vjpr** [comment]
Just to summarize, `require.context`'s arguments must be static and not be variables.

Good:

```
const req = require.context('../stories', true, /.stories.js$/)
```

Bad:

```
const regex = /.stories.js$/
const req = require.context('../stories', true, regex)
```

**Comment by ahettlin** [comment]
Just ran into this issue today. Would be very nice to have. I had everything set up to be able to run a single spec file through karma on-demand via a command line argument, then nope...

**Comment by ricardoribasmrf** [comment]
Hey guys, there is an alternative for this? I believe that making some templating on the file itself would not be the best solution. Unfortunately, i don't see a proper solution for this problem. I've spent a couple of hours preparing a variable-based solution but then i smashed my nose on the door 😂

**Comment by sokra** [comment]
> do you mind elaborating on why these `require.context` vars have to be statically analyzable?

webpack need to determine at build time (before any of your code runs) which files need to be bundled. It doesn't necessarily have to be a static string, it could also be a variable defined with the `DefinePlugin` or basic string operations applied these things.

An alternative is to use `require(variable)` and use the `ContextReplacementPlugin` to provide the "staticness" via config. In this case you need to specify all possible values of `variable` in the arguments of the plugin (or crawl a directory).

**Comment by ricardoribasmrf** [comment]
It worked like a charm 🎉 🥇

**Comment by nickbullock** [comment]
@sokra hi, can we do something with this `require.context` error message? I mean it is a very strange message (`require.context is not a function`) causing people to do a very long way to understand the root of evil (example: [stackoverlow question](https://stackoverflow.com/questions/59809746/how-to-get-require-context-to-work-with-create-react-app-with-withou-craco/59854710#59854710))

**Comment by yoyo837** [comment]
![image](https://user-images.githubusercontent.com/6134547/74098564-bbe67480-4b54-11ea-9263-492f0e307fc2.png)

When I use `load('global')` I get this error, am I missing something? ?
