### ISSUE TITLE
Uncaught TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by stchoukeu** [webpack/webpack#4773]
**Do you want to request a *feature* or report a *bug*?**

A bug

**What is the current behavior?**
(Sorry for asking my question)  I'm there because IONIC team said to me that the problem that i'm facing come from webpack.
when i using app-script 0.0.47 i have no error and my project run very well.
 when using app-script 1.3 or version greater than 0.0.47  i face a white page with error
Uncaught TypeError: Cannot read property 'prototype' of undefined
the problem come when webpack is crying to map a Dexie database class.

**If the current behavior is a bug, please provide the steps to reproduce.**

here is the minimum project where i register this error https://github.com/stchoukeu/IONIC2-RC4-with-DEXIE-Database

**What is the expected behavior?**
the expected behavior is to pass the mapping of the class as it was in the webpack used in app-script 0.0.47

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
npm -version  ===>   3.10.1
i'm in windows 8

**Comment by sokra** [comment]
Please investigate into details of this issue. We don't have time to go into details for specific packages. Create a new issue with a minimal code sample, stack trace and details on what webpack does wrong here.
