### ISSUE TITLE
Runtime Missing module error from UglifyJS plugin.

### ISSUE THREAD

**Issue by vokkal** [webpack/webpack#4786]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I have a Typescript project that I'm trying to bundle with Webpack, but I keep getting a runtime missing module error from what appears to be an issue including UglifyJS.

Also, the log message doesn't include the missing module file name:

```
"errorMessage": "Cannot find module \".\"",
```

**If the current behavior is a bug, please provide the steps to reproduce.**

To repro:

```
git clone https://github.com/vokkal/larynx-sample-highlow.git
cd larynx-sample-highlow
git fetch
git checkout --track -b webpack origin/webpack
npm install
npm run webpack
```

then check `build/larynx_bundle.js` and search for `UglifyJS.FILES`. You should see a bunch of requires for files not included with the bundle as below:

```javascript
var UglifyJS = exports;
var FILES = UglifyJS.FILES = [
    "../lib/utils.js",
    "../lib/ast.js",
    "../lib/parse.js",
    "../lib/transform.js",
    "../lib/scope.js",
    "../lib/output.js",
    "../lib/compress.js",
    "../lib/sourcemap.js",
    "../lib/mozilla-ast.js",
    "../lib/propmangle.js",
    "./exports.js",
].map(function(file){
    return /*require.resolve*/(!(function webpackMissingModule() { var e = new Error("Cannot find module \".\""); e.code = 'MODULE_NOT_FOUND'; throw e; }()));
});
```

**What is the expected behavior?**
Those files should be included in the bundle.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Using Node v6.9.5, Npm 3.10.10, and latest webpack version.

It looks like webpack is looking at the directory structure of the Uglify-js node module.

```
uglify-js
├── LICENSE
├── README.md
├── bin
│   ├── extract-props.js
│   └── uglifyjs
├── lib
│   ├── ast.js
│   ├── compress.js
│   ├── mozilla-ast.js
│   ├── output.js
│   ├── parse.js
│   ├── propmangle.js
│   ├── scope.js
│   ├── sourcemap.js
│   ├── transform.js
│   └── utils.js
├── node_modules
...
```

This is my tsconfig.json

```json
{
  "compilerOptions": {
    "outDir": "build/",
    "sourceMap": true,
    "module": "commonjs",
    "moduleResolution": "node",
    "noEmitOnError": true,
    "target": "es5",
    "types": ["node"],
    "declaration": true,
    "noImplicitAny": true,
    "removeComments": true,
    "rootDir": ".",
    "lib": ["es2015", "es2015.promise", "dom"]
  },
  "include": [
    "./src/index.ts",
    "./src/*/**.ts"
  ],
  "exclude": [
    "lib",
    "build"
  ]
}
```

and my webpack.config.json

```javascript
let path = require('path');
let webpack = require('webpack');
let ZipPlugin = require('zip-webpack-plugin');

module.exports = {
    entry: './src/index.ts',
    output: {
        path: path.join(__dirname, 'build'),
        filename: 'larynx_bundle.js',
        libraryTarget: 'commonjs',
        umdNamedDefine: false
    },
    externals: {
        "aws-sdk": "aws-sdk"
    },
    devtool: 'source-map',
    target: 'node',
    plugins: [
        new ZipPlugin({
            fileOptions: {
                mtime: new Date(),
                mode: 0o100664,
                compress: true,
                forceZip64Format: false,
            },
            pathPrefix: './',
        })
    ],
    resolve: {
        extensions: ['.ts', '.js']
    },
    module: {
        loaders: [
            {
                test: /\.ts$/,
                loader: 'ts-loader',
                exclude: /node_modules/,
            },
            {
                test: /\.js$/,
                loader: 'source-map-loader',
                exclude: /node_modules/,
            }
        ]
    }
};
```

Any advice?

**Comment by calebboyd** [comment]
This seems to be an issue when trying to self host webpack. I have a project where I'm targeting node and the project includes webpack. It turns out webpack can't bundle webpack! UglifyJS is structured such that its source is read in from the file system at runtime, concatenated and eval'd very module bundler unfriendly, and also kindof ironic.

**Comment by deegles** [comment]
What do you mean by self hosting? I'm not including it in my bundle... I tried installing webpack globally but I still got the same behavior.

Any ideas how I could work around this? It's really frustrating.

**Comment by calebboyd** [comment]
No idea, UglifyJS isn't written in a way that allows it to be bundled easily. I was just implying that webpack depends on UglifyJS and therefore you cannot bundle webpack, with wepback (because of UglifyJS).

**Comment by deegles** [comment]
Makes sense. I just don't understand why it's trying to pull uglifyjs into the bundle. I'm hoping it's just a dumb configuration error in my project.

**Comment by tmaslen** [comment]
This issue is happening because uglify-js's dependencies can't be fully resolved via static analysis.

Any idea if webpack or uglify-js will come up with a solution for this?

**Comment by evilebottnawi** [comment]
@webpack-bot move to webpack-contrib/uglifyjs-webpack-plugin
