### ISSUE TITLE
How to deal with dependencies that load css files inside itself modules at node_modules folder?

### ISSUE THREAD

**Issue by jancassio** [webpack/webpack#4787]
Hello guys, sorry if isn't the right place to post this kind of question.

I'm creating a UI lib to serve some projects I'm made for web and mobile (react-native).

Those components has its proper `.css` file. The source structure is something like this:

    |- src
    |-|
      | Component
      |-|
        |- index.js
        |- Component.js
        |- Component.css

The same structure is published in a build folder, with each `.js` file transpiled for a production compatible JavaScript format.

About components. Each component, imports itself styles, so I don't bundle all styles and load globally.

The core concept of each component, is like this

    import React from 'react';
    import { string, func } from 'prop-types';

    import Styles from './Component.css';

    function Component({ label, onClick }) {
      return (
        <div className={Styles.Component} onClick={onClick}>{ label }</div>
      );
    }

    Component.propTypes = {
      label: string.isRequired,
      onClick: func
    };

    Component.defaultProps = {
      label: 'Hello',
      onClick: null
    };

    export default Component;

Ok so, I created a new project to implement an web application with those components loaded as dependency in `node_modules`. If I put any component in my web application and and run `yarn start` or `npm start` to run my app over `webpack-dev-server` for example, I get the following error:

    /Users/someone/myproject/node_modules/mycomponentslib/build/Component/Component.css:1
    (function (exports, require, module, __filename, __dirname) { .Component {
                                                                  ^
    SyntaxError: Unexpected token .
        at createScript (vm.js:53:10)
        at Object.runInThisContext (vm.js:95:10)
        at Module._compile (module.js:543:28)
        at Object.Module._extensions..js (module.js:580:10)
        at Module.load (module.js:488:32)
        at tryModuleLoad (module.js:447:12)
        at Function.Module._load (module.js:439:3)
        at Module.require (module.js:498:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (/Users/someone/myproject/node_modules/mycomponentslib/build/Component/Component.js:13:15)
        at Module._compile (module.js:571:32)
        at Object.Module._extensions..js (module.js:580:10)
        at Module.load (module.js:488:32)
        at tryModuleLoad (module.js:447:12)
        at Function.Module._load (module.js:439:3)
        at Module.require (module.js:498:17)
    /Users/someone/myproject/tools/runServer.js:67
              throw new Error(`Server terminated unexpectedly with code: ${code} signal: ${signal}`);

In other hand, in any project I'm consuming this lib, if I replace....
    
    import Component, { Styles } from '@scope/my-lib'

by

    import Component, { Styles } from './../../node_modules/@scope/my-project'

It works as expected.

In a first instance, my guess was a misconfiguration in my isomorphic app but the same problem happens even with non-universal react app.

I would like to know if someone seen this before and take some adivices about how to configure and fix this kind of problem properly.
 
Thanks.

**Comment by Axnyff** [comment]
What is your webpack config? Could it be possible that your css-loader is not configured to work if they are in node_modules?

**Comment by jancassio** [comment]
@Axnyff I'm using [React Starter Kit](https://reactstarter.com), the configuration is this one:

    /**
    * React Starter Kit (https://www.reactstarterkit.com/)
    *
    * Copyright © 2014-present Kriasoft, LLC. All rights reserved.
    *
    * This source code is licensed under the MIT license found in the
    * LICENSE.txt file in the root directory of this source tree.
    */

    import path from 'path';
    import webpack from 'webpack';
    import AssetsPlugin from 'assets-webpack-plugin';
    import { BundleAnalyzerPlugin } from 'webpack-bundle-analyzer';
    import pkg from '../package.json';

    const isDebug = !process.argv.includes('--release');
    const isVerbose = process.argv.includes('--verbose');
    const isAnalyze = process.argv.includes('--analyze') || process.argv.includes('--analyse');

    //
    // Common configuration chunk to be used for both
    // client-side (client.js) and server-side (server.js) bundles
    // -----------------------------------------------------------------------------

    const config = {
      context: path.resolve(__dirname, '..'),

      output: {
        path: path.resolve(__dirname, '../build/public/assets'),
        publicPath: '/assets/',
        pathinfo: isVerbose,
      },

      module: {
        rules: [
          {
            test: /\.jsx?$/,
            loader: 'babel-loader',
            include: [
              path.resolve(__dirname, '../src'),
            ],
            query: {
              // https://github.com/babel/babel-loader#options
              cacheDirectory: isDebug,

              // https://babeljs.io/docs/usage/options/
              babelrc: false,
              presets: [
                // A Babel preset that can automatically determine the Babel plugins and polyfills
                // https://github.com/babel/babel-preset-env
                ['env', {
                  targets: {
                    browsers: pkg.browserslist,
                  },
                  modules: false,
                  useBuiltIns: false,
                  debug: false,
                }],
                // Experimental ECMAScript proposals
                // https://babeljs.io/docs/plugins/#presets-stage-x-experimental-presets-
                'stage-2',
                // JSX, Flow
                // https://github.com/babel/babel/tree/master/packages/babel-preset-react
                'react',
                // Optimize React code for the production build
                // https://github.com/thejameskyle/babel-react-optimize
                ...isDebug ? [] : ['react-optimize'],
              ],
              plugins: [
                // Adds component stack to warning messages
                // https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-react-jsx-source
                ...isDebug ? ['transform-react-jsx-source'] : [],
                // Adds __self attribute to JSX which React will use for some warnings
                // https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-react-jsx-self
                ...isDebug ? ['transform-react-jsx-self'] : [],
              ],
            },
          },
          {
            test: /\.css/,
            use: [
              {
                loader: 'isomorphic-style-loader',
              },
              {
                loader: 'css-loader',
                options: {
                  // CSS Loader https://github.com/webpack/css-loader
                  importLoaders: 1,
                  sourceMap: isDebug,
                  // CSS Modules https://github.com/css-modules/css-modules
                  modules: true,
                  localIdentName: isDebug ? '[name]-[local]-[hash:base64:5]' : '[hash:base64:5]',
                  // CSS Nano http://cssnano.co/options/
                  minimize: !isDebug,
                  discardComments: { removeAll: true },
                },
              },
              {
                loader: 'postcss-loader',
                options: {
                  config: './tools/postcss.config.js',
                },
              },
            ],
          },
          {
            test: /\.md$/,
            loader: path.resolve(__dirname, './lib/markdown-loader.js'),
          },
          {
            test: /\.txt$/,
            loader: 'raw-loader',
          },
          {
            test: /\.(ico|jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2)(\?.*)?$/,
            loader: 'file-loader',
            query: {
              name: isDebug ? '[path][name].[ext]?[hash:8]' : '[hash:8].[ext]',
            },
          },
          {
            test: /\.(mp4|webm|wav|mp3|m4a|aac|oga)(\?.*)?$/,
            loader: 'url-loader',
            query: {
              name: isDebug ? '[path][name].[ext]?[hash:8]' : '[hash:8].[ext]',
              limit: 10000,
            },
          },
        ],
      },

      // Don't attempt to continue if there are any errors.
      bail: !isDebug,

      cache: isDebug,

      stats: {
        colors: true,
        reasons: isDebug,
        hash: isVerbose,
        version: isVerbose,
        timings: true,
        chunks: isVerbose,
        chunkModules: isVerbose,
        cached: isVerbose,
        cachedAssets: isVerbose,
      },
    };

    //
    // Configuration for the client-side bundle (client.js)
    // -----------------------------------------------------------------------------

    const clientConfig = {
      ...config,

      name: 'client',
      target: 'web',

      entry: {
        client: ['babel-polyfill', './src/client.js'],
      },

      output: {
        ...config.output,
        filename: isDebug ? '[name].js' : '[name].[chunkhash:8].js',
        chunkFilename: isDebug ? '[name].chunk.js' : '[name].[chunkhash:8].chunk.js',
      },

      plugins: [
        // Define free variables
        // https://webpack.github.io/docs/list-of-plugins.html#defineplugin
        new webpack.DefinePlugin({
          'process.env.NODE_ENV': isDebug ? '"development"' : '"production"',
          'process.env.BROWSER': true,
          __DEV__: isDebug,
        }),

        // Emit a file with assets paths
        // https://github.com/sporto/assets-webpack-plugin#options
        new AssetsPlugin({
          path: path.resolve(__dirname, '../build'),
          filename: 'assets.json',
          prettyPrint: true,
        }),

        // Move modules that occur in multiple entry chunks to a new entry chunk (the commons chunk).
        // http://webpack.github.io/docs/list-of-plugins.html#commonschunkplugin
        new webpack.optimize.CommonsChunkPlugin({
          name: 'vendor',
          minChunks: module => /node_modules/.test(module.resource),
        }),

        ...isDebug ? [] : [
          // Minimize all JavaScript output of chunks
          // https://github.com/mishoo/UglifyJS2#compressor-options
          new webpack.optimize.UglifyJsPlugin({
            sourceMap: true,
            compress: {
              screw_ie8: true, // React doesn't support IE8
              warnings: isVerbose,
              unused: true,
              dead_code: true,
            },
            mangle: {
              screw_ie8: true,
            },
            output: {
              comments: false,
              screw_ie8: true,
            },
          }),
        ],

        // Webpack Bundle Analyzer
        // https://github.com/th0r/webpack-bundle-analyzer
        ...isAnalyze ? [new BundleAnalyzerPlugin()] : [],
      ],

      // Choose a developer tool to enhance debugging
      // http://webpack.github.io/docs/configuration.html#devtool
      devtool: isDebug ? 'cheap-module-source-map' : false,

      // Some libraries import Node modules but don't use them in the browser.
      // Tell Webpack to provide empty mocks for them so importing them works.
      // https://webpack.github.io/docs/configuration.html#node
      // https://github.com/webpack/node-libs-browser/tree/master/mock
      node: {
        fs: 'empty',
        net: 'empty',
        tls: 'empty',
      },
    };

    //
    // Configuration for the server-side bundle (server.js)
    // -----------------------------------------------------------------------------

    const serverConfig = {
      ...config,

      name: 'server',
      target: 'node',

      entry: {
        server: ['babel-polyfill', './src/server.js'],
      },

      output: {
        ...config.output,
        filename: '../../server.js',
        libraryTarget: 'commonjs2',
      },

      module: {
        ...config.module,

        // Override babel-preset-env configuration for Node.js
        rules: config.module.rules.map(rule => (rule.loader !== 'babel-loader' ? rule : {
          ...rule,
          query: {
            ...rule.query,
            presets: rule.query.presets.map(preset => (preset[0] !== 'env' ? preset : ['env', {
              targets: {
                node: parseFloat(pkg.engines.node.replace(/^\D+/g, '')),
              },
              modules: false,
              useBuiltIns: false,
              debug: false,
            }])),
          },
        })),
      },

      externals: [
        /^\.\/assets\.json$/,
        (context, request, callback) => {
          const isExternal =
            request.match(/^[@a-z][a-z/.\-0-9]*$/i) &&
            !request.match(/\.(css|less|scss|sss)$/i);
          callback(null, Boolean(isExternal));
        },
      ],

      plugins: [
        // Define free variables
        // https://webpack.github.io/docs/list-of-plugins.html#defineplugin
        new webpack.DefinePlugin({
          'process.env.NODE_ENV': isDebug ? '"development"' : '"production"',
          'process.env.BROWSER': false,
          __DEV__: isDebug,
        }),

        // Do not create separate chunks of the server bundle
        // https://webpack.github.io/docs/list-of-plugins.html#limitchunkcountplugin
        new webpack.optimize.LimitChunkCountPlugin({ maxChunks: 1 }),

        // Adds a banner to the top of each generated chunk
        // https://webpack.github.io/docs/list-of-plugins.html#bannerplugin
        new webpack.BannerPlugin({
          banner: 'require("source-map-support").install();',
          raw: true,
          entryOnly: false,
        }),
      ],

      node: {
        console: false,
        global: false,
        process: false,
        Buffer: false,
        __filename: false,
        __dirname: false,
      },

      devtool: isDebug ? 'cheap-module-source-map' : 'source-map',
    };

    export default [clientConfig, serverConfig];
