### ISSUE TITLE
bare string exports (webpack vs nodejs)

### ISSUE THREAD

**Issue by monte-hayward** [webpack/webpack#4788]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Strings are exported bare, so that contents are interpreted as identifiers.

```
var foo = __webpack_require__(628)({}, __webpack_require__.i({"url":https://api-server.example.com,"headers":__webpack_require__.i({"Authorization":Basic dGVkMzpUSDFuazE3MTA=})}));
```

Uncaught SyntaxError: Unexpected token : 
Unexpected Identifier: Basic dXplcm5hbWU6cHN3ZA==

**If the current behavior is a bug, please provide the steps to reproduce.**

1. expose dynamic strings as exports
2. require and reference module fields
3. run in webpack-dev-server

## module api-config.js

```
var base64 = require('base-64');

var u = process.env.UZER;
var p = process.env.PSWD;
var b64 = 'Basic ';
var raw = [u, ':', p].join('');
b64 += base64.encode(raw);

module.exports = {
  url: process.env.API_URL,
  headers: {
    Authorization: b64,
    'Content-Type': 'application/json'
  }
};
```
## webpack.config.js

```
const API_CONFIG = require('mms-ask-client/lib/api-config');
// ...
  plugins: [
    new webpack.DefinePlugin({
      'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV || 'development'),
      API_CONFIG: API_CONFIG,
  ]
// ...
```

## usage

```
var envOptions = {
    headers: API_CONFIG.headers,
// ...
};
```

**What is the expected behavior?**
Strings will be exported as delimited strings.

**If this is a feature request, what is motivation or use case for changing the behavior?**
n/a 
**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

```
npm ls webpack babel-loader babel-core
my-app@0.0.2 /path/to/my-app
├── babel-core@6.24.1 
├── babel-loader@6.4.1 
└── webpack@2.4.1 
 node -v & npm -v
v6.10.1
3.10.5
```

**Comment by Axnyff** [comment]
It seems that the problem you're having is that you're not JSON.stringify-ing your API_CONFIG. 

It seems to work for me if I change that in your configuration

**Comment by monte-hayward** [comment]
@Axnyff JSON-stringify was my first go-to. Results:
browser: 'the string'
node or webpack-server: '"the string"'
So the double quotes inside the string break the url, password, etc.

As a result, a piece of code that works in browser/webpack-dev-server breaks in unit tests and vice versa.

More description is here: http://stackoverflow.com/questions/43598376/extra-quote-marks-in-node-json-stringify

**Comment by Axnyff** [comment]
Where is your JSON.stringify? In your stackoverflow question, you're stringifying inside of your module. The JSON stringify needs to go in your webpack defineplugin conf. Sorry if I misunderstood your problem though

**Comment by monte-hayward** [comment]
No worries

Stringify-inside-the-module is working in the case of another build, which uses webpack 1:
    "webpack": "1.14.0",
    "webpack-dev-server": "1.16.2"

> The JSON stringify needs to go in your webpack defineplugin conf.
Oh?  What if I want my module to be used in non-webpack environments?

Also, say the module has 4 string fields
- username
- password
- api url
- some token
Would defineplugin have to JSON.stringify each one?
Kind of defies the point of having a module.

After these were written, I discovered webpack.EnvironmentPlugin. Maybe that's the webpack 2 way, but it seems like migration should not break something as simple as exporting a string.

**Comment by Axnyff** [comment]
I'd say there's two way:

Either you do something like

    const api = API_CONFIG;

and

      plugins: [
        new webpack.DefinePlugin({
          'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV || 'development'),
          API_CONFIG: JSON.stringify(API_CONFIG),
      ]

in your webpack config.

Or you can loop through your object in your webpack config to create multiple definition like HEADERS, USERNAME etc..

**Comment by monte-hayward** [comment]
thanks.

If it worked in webpack 1 and broke in webpack 2, isn't that a bug?

**Comment by Axnyff** [comment]
What isn't working in webpack 2?
my webpack config:

    const webpack = require("webpack");
    const API_CONFIG = require("./api.js");
    module.exports = {
        entry: "./app.js",
        output: {
            filename: "live.js"
        },
        plugins: [
            new webpack.DefinePlugin({
                API_CONFIG: JSON.stringify(API_CONFIG)
            })
        ]
    };


my file

    var api = API_CONFIG;
    console.log(api.headers);


gives me 

    var api = {"headers":{"Authorization":"Basic Og==","Content-Type":"application/json"}};

    console.log(api.headers);


with webpack 2.4.1

**Comment by monte-hayward** [comment]
It looks like you've provided a workaround for a breaking change. Yes, that pattern works for me in 2.4.1. 

In webpack 1, it worked with just the `stringify` limited to the module.
The result was a module that was more testable and distributable.

here is what used to work:
```
const webpack = require("webpack");
const API_CONFIG = require("./api.js");
module.exports = {
    entry: "./app.js",
    output: {
        filename: "live.js"
    },
    plugins: [
        new webpack.DefinePlugin({
            API_CONFIG: API_CONFIG
        })
    ]
};
```
