### ISSUE TITLE
DllReferencePlugin should modifyHash when manifest.json file contents changed

### ISSUE THREAD

**Issue by wenbing** [webpack/webpack#4790]
opts.manifest as a filepath, and manifest.json contents changed, but [hash] has no change

**Comment by wenbing** [comment]
My solution:

```diff
      const manifest = this.options.manifest;
      if (typeof manifest === 'string') {
        const results = compiler.inputFileSystem.readFileSync(manifest);
        compilation.plugin('after-hash', () => compilation.modifyHash(results.toString('utf-8')));
      }
```

**Comment by poeschko** [comment]
I just ran into the same (or at least very similar) problem, with rather fatal consequences: The `[chunkhash]` didn't change even though the contents of the chunk did change (due to the DLL variable name changing).

I created a repro repo here: https://github.com/poeschko/webpack-dll-experiment

**Comment by superpig** [comment]
same issue

**Comment by poeschko** [comment]
The [3.7 release notes](https://github.com/webpack/webpack/releases/tag/v3.7.0) mention that "References to dll now contribute correctly to hash". Does that solve this issue by any chance?

**Comment by zhangwilling** [comment]
@poeschko hi bro, i test lateset webpack@3.9.1 has solved this problem. so i guess it was sovled at 3.7release. anyway,use latest version can fix this bug.
