### ISSUE TITLE
app using dll not building without vendor module in apps node modules 

### ISSUE THREAD

**Issue by wpitallo** [webpack/webpack#4796]
Hi 

I am not sure if this is expected behavior but it seems to be a bug.

The example uses webpack 2.2.0 but the behavior is the same in 2.4.1.

I have been trying to get webpack2 dlls working and I found the following example:

https://github.com/codeimpossible/webpack-vendor-dll-example

I managed to get the project building and running while following the example quite easily but then I noticed that in the app-code package.json they have added react and react-dom to the devDependencies. 

So I deleted them from the app-code node modules and ran npm run build. It then fails saying that:

Module not found: Error: Can't resolve 'react' in '..\webpack-vendor-dll-example\src\app-code'.

Surly if this was resolving from the dll it should build regardless of if react and react-dom are in the app-codes node modules? And surly react and react-dom should only be included in the vendor-code package.json?

**Comment by sokra** [comment]
It's intended to work this way. Resolving happens in the app compilation.

**Comment by wpitallo** [comment]
Thanks @sokra 

I am not sure I full understand tho, if its resolving from the dll why does it need to be in the apps node modules as well. Would it not be better if it resolved directly from the dll without requiring the module the apps node modules as well? What is the purpose of having it in both places. 

Thanks for tje hel really appropriate it!

**Comment by wpitallo** [comment]
@sokra surly this is a bud tho,  if the module is included in the dll why is it not resolved from the dll during the app compilation
