### ISSUE TITLE
[concern] Options defaults - node

### ISSUE THREAD

**Issue by Andarist** [webpack/webpack#4797]
Libraries often use `process.env.NODE_ENV` so they can compile conditionally, but they also often try to guard against `process`' absence with some `typeof` check which BY DEFAULT is causing every consumer of the library to include i.e. `process` polyfill. 

I think most webpack-generated code is targeting the browser and auto-polyfilling such things is at least unexpected. Its causing extra-bytes in users' bundles, but whats more troubling it causes it for UMD standalone builds too which causes serious duplication of the code which is not intended to run! And all of that often by accident.

Also while writing isomorphic libraries people often use such lines:
`const asap = typeof setImmediate !== 'undefined' ? setImmediate : setTimeout`
which when bundled by webpack will also include `setImmediate`'s polyfill automatically - again by accident. And even if libraries authors are aware of this (but mostly not), certainly users are not and they do not put configurations like below while targeting browsers only and not thinking about this too much:
```javascript
node: {
  global: false,
  process: false,
  __filename: false,
  __dirname: false,
  Buffer: false,
  setImmediate: false,
}
```

**Comment by sokra** [comment]
webpack has chosen the following priorities:

1. Make sure that the applications works correctly.
2. Make sure that the bundle is small/efficient.

So while you are correct that webpack includes unnecessary polyfills in this cases, it's better that to build a non-functional app where your have to figure out that the magic `node.global: true` is required. Keep in mind that not everyone guards against undefined global objects. These modules would be broken in the default configuration.

**Comment by Andarist** [comment]
Sure, but then its library' s fault that it didnt guard properly and the PR
might be filed to fix it, now its like unneccessary world rescuing.

The best approach for now ive found for this is to reference everything
under global namespace, ie global.setImmediate so the only polyfill which
gets included is the global's one and which is really small. Opting out of
it in the library's space is not possible more than that I think.

While I understand the reasoning I find this brhaviour too implicit and
causing harm as premature 'fixing' the libraries' lack of some checks

**Comment by Andarist** [comment]
With webpack3 `node: false` got introduced and while i still believe that auto-polyfilling node's globals is bad, I guess this needs to suffice for now.
