### ISSUE TITLE
Extra main.js file when using multi-entry config

### ISSUE THREAD

**Issue by edgeadjei** [webpack/webpack#4800]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
when specifying a multi-entry config Webpack generates the specified entry files which is the expected behavior but adds an extra unspecified entry `main.js`. 

*Config*
```js
// Node Modules
const {join} = require("path");
const webpack = require("webpack");

const PRODUCTION_ENV = process.env.NODE_ENV === "production";

const CLIENTCONFIG = {
  devtool: "cheap-eval-source-map",
  context: join(__dirname, "components"),
  entry: {
    account   : join(__dirname, "components","account","account.layout.jsx"),
    instances : join(__dirname, "components","instances","instances.layout.jsx"),
    orders    : join(__dirname, "components","orders","orders.component.jsx"),
    stores    : join(__dirname, "components","stores","stores.component.jsx")
  },
  output: {
    path: join(__dirname, "build"),
    filename: "[name].view.js"
  },
  module: {
    loaders: [
      { test: /\.(js|jsx)$/, loader: 'babel-loader', exclude: /node_modules/},
      { test: /\.yaml$/, loader: 'yml-loader', exclude: /node_modules/}
    ]
  },
  plugins: [
    new webpack.optimize.CommonsChunkPlugin({
      name: 'vendor',
      filename: "shared.view.js",
      minChunks: 3,
      chunks: ["account","instances","orders","stores"]
    })
  ],
  target: "electron-renderer",
  node: {
    __dirname: false
  }
};
```

*Output*
![screen-shot-2017-04-30-at-12 44 52-pm](https://cloud.githubusercontent.com/assets/10477325/25566725/d2b7948a-2da4-11e7-8aab-12e0c73b9022.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
Using the above config run `./node_modules/.bin/webpack . --progress --colors`

**What is the expected behavior?**
As per the config, only the files specified should be generated.
```js
entry: {
    account   : join(__dirname, "components","account","account.layout.jsx"),
    instances : join(__dirname, "components","instances","instances.layout.jsx"),
    orders    : join(__dirname, "components","orders","orders.component.jsx"),
    stores    : join(__dirname, "components","stores","stores.component.jsx")
  }
```
Since i'm creating an electron application, the bundled `main.view.js` file contains native modules and therefore crashes my application.
With that aside, this also increases my overall build size.
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
**OS**: `macOS Sierra v10.12.4`
**Node**: `v6.10.0`
**webpack**: `beta`

**Comment by sokra** [comment]
Omit the `.` in your command line commando...

**Comment by edgeadjei** [comment]
Are you serious after hours of trying to track down the issue its as simple as that.
@sokra Thank You.
