### ISSUE TITLE
If you enable/disable or change source maps, hash will be the same

### ISSUE THREAD

**Issue by svipben** [webpack/webpack#4802]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If you enable source maps in `devtool` or for e.g. change `devtoolModuleFilenameTemplate` the hash will be the same and if you cache your `.js` in browser it's impossible to see source maps if you don't do `CTRL + F5` and this doesn't helps all the time by the way. If hash was for e.g. `8b84asd` it will be the same after you enable/disable, change source maps and so on. I'm using this `[chunkhash:8]`.

**If the current behavior is a bug, please provide the steps to reproduce.**
You can see my project here: https://github.com/svipben/react-boilerplate/tree/master/configs, but everything is explained above.

**What is the expected behavior?**
To create new hash for `.js` file if `devtool` or `devtoolModuleFilenameTemplate` is changed.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Chrome: 58.0.3029.81 (64-bit)
Node.js: 7.9.0
Webpack: 2.4.1
OS: Linux Ubuntu 16.04

**Comment by pksjce** [comment]
Hey, 
Have you tried it with `webpack 3.1`? I can't seem to reproduce it.
