### ISSUE TITLE
Webpack produces no input

### ISSUE THREAD

**Issue by RandomVanGloboii** [webpack/webpack#4809]
I am aware that this is quite a common problem with Webpack, but I am a total newbie and the solutions I've found so far seem to be very specific to the single project. However, the scenario is the same: Webpack compiling the project correctly and then showing a blank page, without reporting any errors.

Here is my webpack.config.js (I made it following tutorials):

```
var webpack = require('webpack');
    var path = require('path');
    
    var config = {
      entry: './src/index.js',
      output: {
        path: __dirname,
        filename: "bundle.js"
      },  
      module: {
        loaders : [
          { test: /\.css$/, loader: "style!css" },
          {
            test: /.jsx?$/,
            loader: 'babel-loader',
            exclude: /node_modules/,
            query: {
              presets: ['es2015', 'react']
            }
          }		
          ]
        }
    };
    
    module.exports = config;
```

Here my package.json:

   ```
 {
      "name": "smart-fit",
      "version": "1.0.0",
      "description": "",
      "main": "src/index.js",
      "dependencies": {
        "babel": "^6.23.0",
        "babel-core": "^6.24.1",
        "babel-loader": "^7.0.0",
        "babel-preset-es2015": "^6.24.1",
        "babel-preset-react": "^6.24.1",
        "chartjs": "^0.3.24",
        "interactjs": "^1.2.8",
        "jquery": "^3.2.1",
        "lodash": "^4.17.4",
        "moment": "^2.18.1",
        "react": "^15.5.4",
        "react-dom": "^15.5.4",
        "react-table": "^5.6.0",
        "webpack": "^2.4.1"
      },
      "devDependencies": {
        "babel-core": "^6.4.5",
        "babel-loader": "^6.2.1",
        "babel-preset-es2015": "^6.3.13",
        "babel-preset-react": "^6.3.13",
        "css-loader": "^0.28.1",
        "style-loader": "^0.17.0",
        "webpack": "^1.12.12"
      },
      "scripts": {
        "test": "echo \"Error: no test specified\" && exit 1"
      },
      "author": "",
      "license": "ISC"
    }
```

Webpack version is the lastest and the project is written using React and ES5. Node.js version is 6.10.0 and OS is Windows 10. I tested it on Chrome 58.

**If the current behavior is a bug, please provide the steps to reproduce.**

**Comment by sokra** [comment]
Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md).
