### ISSUE TITLE
Configuring library as external in webpack does not work like expected with UMD as libraryTarget

### ISSUE THREAD

**Issue by janis91** [webpack/webpack#4824]
**Do you want to request a *feature* or report a *bug*?**
I assume this could be a *bug*.

**What is the current behavior?**
I want to build my own JavaScript library and register it under an already existing namespace ("OCA" - in this particular case). Therefore I use webpack 2 and the libraryTarget: umd to register the output under "OCA.Ocr" (my library is named "Ocr"). This works like intended, but when it comes to the point that I want to use for example underscorejs as a library which will be included in the html later, I cannot get it to work. I followed the webpack configuration documentation and it says that the **externals** configuration option should be the way to go. But if I use it like stated in the documentation, the underscore library in this case is not defined. I also checked, that the library is available in the global namespace and the file gets loaded before my webpack bundle.

**If the current behavior is a bug, please provide the steps to reproduce.**
[my webpack.config.js](https://gist.github.com/janis91/919ffabd0829cdbcb6258e619cf5ccc0)
[my typescript code](https://gist.github.com/janis91/8fc9f9b1ce76fc1f2cea74c684e9fdeb)
[webpack bundle](https://gist.github.com/janis91/eb675f17e25eb87159c1e8b62c2a81da)

Firefox says:

> TypeError: underscore_1.default is undefined

**What is the expected behavior?**
No TypeError should be thrown and the underscorejs (`_`) library should be also available for the library bundled with webpacka as an external. (Like stated in the documentation)

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Webpack Version: 2.5.0
Node: 6.10.2
OS: Debian Jessie
Browser: Firefox ESR 45.9.0

Also related is my [stackoverflow question ](https://stackoverflow.com/questions/43788304/configuring-library-as-external-in-webpack-does-not-work-with-umd-as-librarytarg)as I actually don't know if this is my fault or if this is a bug. (Maybe it would be at least nice to give more information regarding such use case in the documentation)

**Comment by sokra** [comment]
Yep, this looks like a bug. webpack doesn't generate the CJS harmony interop layer for externals.

**Comment by janis91** [comment]
If you give me any hint where to look and how to pass this problem, I could try to fix it and contribute.

**Comment by 82antu** [comment]
Same Issue, Here, (more or less);

I have a custom umd library (_mylib_) made by myself (bundled with webpack, of course); when I try to consume it in my application (bundled also with webpack) as "externals", it simply doesn't work.

The output of application (_app.js_)

> (function webpackUniversalModuleDefinition(root, factory) {
	if(typeof exports === 'object' && typeof module === 'object')
		module.exports = factory(require("mylib"));
	else if(typeof define === 'function' && define.amd)
		define(["mylib"], factory);
	else {
		var a = typeof exports === 'object' ? factory(require("mylib")) : factory(root["mylib"]);
		for(var i in a) (typeof exports === 'object' ? exports : root)[i] = a[i];
	}
})(this, function(__WEBPACK_EXTERNAL_MODULE_364__) {
return /******/ (function(modules) { // webpackBootstrap

always has __WEBPACK_EXTERNAL_MODULE_364__ as undefined

**Comment by pathikdevani** [comment]
Any update?

**Comment by OlegZavrazhin** [comment]
It's one of most important thing (`library:`) I want to use in `webpack 3.12.0`.
Any chance to have it soon?

**Comment by finom** [comment]
Any news?

**Comment by psmadhav** [comment]
I am also stuck here!

**Comment by alexander-akait** [comment]
Fixed in webpack@5, now we use `__importDefault` helper, so `.default` is supported, anyway feel free to feedback
