### ISSUE TITLE
Entry with a hyphen causes a broken bundle.

### ISSUE THREAD

**Issue by nchutchind** [webpack/webpack#4825]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
An entry with a hyphen (ie, entry: { 'my-entry': './my-entry.js' }) will create a bundle called my-entry.bundle.js which starts with `var my-entry = ...`
A variable name cannot have a hyphen in it, so it cannot be processed.

**If the current behavior is a bug, please provide the steps to reproduce.**
Simply create an entry named with a hyphen and build.

**What is the expected behavior?**
I would expect Webpack to through an error and not build. I would NOT expect it to change the name of the entry or the internal variable name (as that could lead to possible collisions).

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Node 6.9.1
Webpack 2.5.0
Windows 10

**Comment by nchutchind** [comment]
This seems to only happen when `output: { library: '[name]', libraryTarget: 'var' }`

Someone configuring like this should probably expect this behavior, but I still think it would be nice to get an error rather than a build that says it's successful yet has no hope of running.

**Comment by sokra** [comment]
We could automatically convert it to an identifier.
