### ISSUE TITLE
Feature: REGEX as string

### ISSUE THREAD

**Issue by aight8** [webpack/webpack#4830]
A further step to make json only configurations, it should be possible to define regex values as a string. Since on a lot of places string is also a valid value type, this makes it more diffucult.
Solutions:
- if value match to "/...regex.../..." it get converted to a regex.
- "REGEX(..regex..)" to explicit convert the value between the braces to regex

Otherwise json only config values will be never possible.

**Comment by sokra** [comment]
Why do you want JSON only configs?

**Comment by aight8** [comment]
JSON has so much benefits regarding serialisation etc.
I previously wrote a detailed issue about the benefits (it was about lot more than this issue)
https://github.com/webpack/webpack/issues/4342
Also the issue **Usability Discussion** (https://github.com/webpack/webpack/issues/2797#issuecomment-277249369) discuss this.

Near **plugins**, **regex config values** are one of few parts in a webpack config which cannot be serialised to JSON.

Maybe this issue could be targeted for future webpack releases.

btw: I currently working on a webpack configurator projects which helps a lot of people to understand and configure webpack configs in any complexity. Currently I need a intermediate webpack configuration format which allows to create objects (like regexp's) later.

**Comment by DanielRuf** [comment]
For such cases I would probably use solutions like https://github.com/yahoo/serialize-javascript.

Also see https://github.com/json5/json5/issues/91
