### ISSUE TITLE
Alias interferes with module namespace

### ISSUE THREAD

**Issue by drcmda** [webpack/webpack#4835]
I have two webpack projects:

    /dev
        /A
        /B

 Project `A` extends the prototype of some dependency, `THREE`, like

    THREE.Object3D.prototype.utilityFunction = function() { ... }

Project `B` uses `A`, and for easier debugging i add it as an alias that points outside of `B`s project directory:

    resolve: {
            modules: [path.resolve('./'), 'node_modules'],
            extensions: ['.js', '.jsx'],
            alias: {
                A: path.resolve(__dirname, '../A'),

For some odd reason the patches are missing when i do it like this. It's like two different namespaces. References to `THREE` in `A` and `B` seem to be two different objects. I debugged the `A` side, and it's got its prototypes just fine, but they're missing in `B`.

    import * as THREE from 'three'
    console.log(THREE.Object3D.utilityFunction) // undefined

It works if i delete the alias, then webpack takes `A` from `node_modules`, which makes me think webpack is resolving `three` a second time in `A`s own `node_modules`, but why would it?

What could cause this?

**Comment by evilebottnawi** [comment]
@drcmda problem still exists?

**Comment by drcmda** [comment]
@evilebottnawi I think either babel 7 or webpack 4 fixed it.
