### ISSUE TITLE
Chunk using DllReferencePlugin does not change `[chunkhash]` of filename When corresponding dll had changed.

### ISSUE THREAD

**Issue by MoonBall** [webpack/webpack#4838]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Chunk using DllReferencePlugin does not change `[chunkhash]` of filename When corresponding dll had changed.

**If the current behavior is a bug, please provide the steps to reproduce.**
I have a example repo: https://github.com/MoonBall/DllReferencePlugin-not-change-chunkhash
There are two cases:
1. `manifest.json` change.
step 1: `npm run webpack`.
step 2: modify `webpack.config.js`: comment 7-th line, uncomment 8-th line.
step 3: `npm run webpack`.
result: conents of two runs is different, but `[chunkhash]` is same.

2. dependencies of dll change
step 1: `git reset --hard && rm -rf js`
step 2: `npm run webpack`.
step 3: modify `vendor2.js`: comment 2-nd line.
step 4: `npm run webpack`.
result: conents of two runs is different, but `[chunkhash]` is same.

**What is the expected behavior?**
`[chunkhash]` change.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
OS: osx 10.11.6
node: 6.6.0

**Comment by superpig** [comment]
same issue

**Comment by superpig** [comment]
when the dll has changed which has led to the change of dll's hash. although the content of bundle has changed, it's chunkhash didn't change，so we can't update the cdn，there is reference error

**Comment by alexander-akait** [comment]
reproducible test repo was removed, so we can't say what is wrong :disappointed: I want to close it, but if you faced with the same problem, please open a new issue with reproducible test repo (maybe it fixed already, just try webpack@5), sorry for delay
