### ISSUE TITLE
Ionic Issue: SyntaxError: D:\Users\tlachgar\AppData\Roaming\npm\node_modules\cordova\package. json: Unexpected token ? in JSON at position 1

### ISSUE THREAD

**Issue by MSeguin7** [webpack/webpack#4839]
**Do you want to request a *feature* or report a *bug*?**
a bug

**What is the current behavior?**
I have a Syntax Error that I don't understand when I try to add a plugin to Ionic for example

SyntaxError: D:\Users\tlachgar\AppData\Roaming\npm\node_modules\cordova\package.
json: Unexpected token ? in JSON at position 1

    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (module.js:588:27)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Users\tlachgar\AppData\Roaming\npm\node_modules\co
rdova\src\cli.js:31:11)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
The expected behavior is that there is no syntax error

**If this is a feature request, what is motivation or use case for changing the behavior?**

Here is my package.json
`{
  "version": "4.2.0",
  "name": "npm",
  "description": "a package manager for JavaScript",
  "keywords": [
    "install",
    "modules",
    "package manager",
    "package.json"
  ],
  "preferGlobal": true,
  "config": {
    "publishtest": false
  },
  "homepage": "https://docs.npmjs.com/",
  "author": "Isaac Z. Schlueter <i@izs.me> (http://blog.izs.me)",
  "repository": {
    "type": "git",
    "url": "https://github.com/npm/npm"
  },
  "bugs": {
    "url": "https://github.com/npm/npm/issues"
  },
  "directories": {
    "bin": "./bin",
    "doc": "./doc",
    "lib": "./lib",
    "man": "./man"
  },
  "main": "./lib/npm.js",
  "bin": "./bin/npm-cli.js",
  "dependencies": {
    "JSONStream": "~1.3.0",
    "abbrev": "~1.0.9",
    "ansi-regex": "~2.1.1",
    "ansicolors": "~0.3.2",
    "ansistyles": "~0.1.3",
    "aproba": "~1.0.4",
    "archy": "~1.0.0",
    "asap": "~2.0.5",
    "chownr": "~1.0.1",
    "cmd-shim": "~2.0.2",
    "columnify": "~1.5.4",
    "config-chain": "~1.1.11",
    "dezalgo": "~1.0.3",
    "editor": "~1.0.0",
    "fs-vacuum": "~1.2.9",
    "fs-write-stream-atomic": "~1.0.8",
    "fstream": "~1.0.10",
    "fstream-npm": "~1.2.0",
    "glob": "~7.1.1",
    "graceful-fs": "~4.1.11",
    "has-unicode": "~2.0.1",
    "hosted-git-info": "~2.1.5",
    "iferr": "~0.1.5",
    "inflight": "~1.0.6",
    "inherits": "~2.0.3",
    "ini": "~1.3.4",
    "init-package-json": "~1.9.4",
    "lockfile": "~1.0.3",
    "lodash._baseuniq": "~4.6.0",
    "lodash.clonedeep": "~4.5.0",
    "lodash.union": "~4.6.0",
    "lodash.uniq": "~4.5.0",
    "lodash.without": "~4.4.0",
    "mississippi": "~1.3.0",
    "mkdirp": "~0.5.1",
    "node-gyp": "~3.5.0",
    "nopt": "~4.0.1",
    "normalize-git-url": "~3.0.2",
    "normalize-package-data": "~2.3.5",
    "npm-cache-filename": "~1.0.2",
    "npm-install-checks": "~3.0.0",
    "npm-package-arg": "~4.2.0",
    "npm-registry-client": "~7.4.5",
    "npm-user-validate": "~0.1.5",
    "npmlog": "~4.0.2",
    "once": "~1.4.0",
    "opener": "~1.4.2",
    "osenv": "~0.1.4",
    "path-is-inside": "~1.0.2",
    "read": "~1.0.7",
    "read-cmd-shim": "~1.0.1",
    "read-installed": "~4.0.3",
    "read-package-json": "~2.0.4",
    "read-package-tree": "~5.1.5",
    "readable-stream": "~2.2.2",
    "realize-package-specifier": "~3.0.3",
    "request": "~2.79.0",
    "retry": "~0.10.1",
    "rimraf": "~2.5.4",
    "semver": "~5.3.0",
    "sha": "~2.0.1",
    "slide": "~1.1.6",
    "sorted-object": "~2.0.1",
    "sorted-union-stream": "~2.1.3",
    "strip-ansi": "~3.0.1",
    "tar": "~2.2.1",
    "text-table": "~0.2.0",
    "uid-number": "0.0.6",
    "umask": "~1.1.0",
    "unique-filename": "~1.1.0",
    "unpipe": "~1.0.0",
    "uuid": "~3.0.1",
    "validate-npm-package-name": "~2.2.2",
    "which": "~1.2.12",
    "wrappy": "~1.0.2",
    "write-file-atomic": "~1.3.1"
  },
  "bundleDependencies": [
    "abbrev",
    "ansi-regex",
    "ansicolors",
    "ansistyles",
    "aproba",
    "archy",
    "asap",
    "chownr",
    "cmd-shim",
    "columnify",
    "config-chain",
    "debuglog",
    "dezalgo",
    "editor",
    "fs-vacuum",
    "fs-write-stream-atomic",
    "fstream",
    "fstream-npm",
    "glob",
    "graceful-fs",
    "has-unicode",
    "hosted-git-info",
    "iferr",
    "imurmurhash",
    "inflight",
    "inherits",
    "ini",
    "init-package-json",
    "JSONStream",
    "lockfile",
    "lodash._baseindexof",
    "lodash._baseuniq",
    "lodash._bindcallback",
    "lodash._cacheindexof",
    "lodash._createcache",
    "lodash._getnative",
    "lodash.clonedeep",
    "lodash.restparam",
    "lodash.union",
    "lodash.uniq",
    "lodash.without",
    "mkdirp",
    "node-gyp",
    "nopt",
    "normalize-git-url",
    "normalize-package-data",
    "npm-cache-filename",
    "npm-install-checks",
    "npm-package-arg",
    "npm-registry-client",
    "npm-user-validate",
    "npmlog",
    "once",
    "opener",
    "osenv",
    "path-is-inside",
    "read",
    "read-cmd-shim",
    "read-installed",
    "read-package-json",
    "read-package-tree",
    "readable-stream",
    "readdir-scoped-modules",
    "realize-package-specifier",
    "request",
    "retry",
    "rimraf",
    "semver",
    "sha",
    "slide",
    "sorted-object",
    "sorted-union-stream",
    "strip-ansi",
    "tar",
    "text-table",
    "uid-number",
    "umask",
    "unique-filename",
    "unpipe",
    "validate-npm-package-license",
    "validate-npm-package-name",
    "which",
    "wrappy",
    "write-file-atomic",
    "mississippi",
    "uuid"
  ],
  "devDependencies": {
    "deep-equal": "~1.0.1",
    "marked": "~0.3.6",
    "marked-man": "~0.2.0",
    "npm-registry-couchapp": "~2.6.12",
    "npm-registry-mock": "~1.0.1",
    "require-inject": "~1.4.0",
    "sprintf-js": "~1.0.3",
    "standard": "~6.0.8",
    "tacks": "~1.2.2",
    "tap": "~9.0.3"
  },
  "scripts": {
    "dumpconf": "env | grep npm | sort | uniq",
    "prepublish": "node bin/npm-cli.js prune --prefix=. --no-global && rimraf test/*/*/node_modules && make doc-clean && make -j4 doc",
    "preversion": "bash scripts/update-authors.sh && git add AUTHORS && git commit -m \"update AUTHORS\" || true",
    "tap": "tap --timeout 300",
    "tap-cover": "tap --nyc-arg='--cache' --coverage --timeout 600",
    "test": "standard && npm run test-tap",
    "test-coverage": "npm run tap-cover -- \"test/tap/*.js\" \"test/network/*.js\" \"test/broken-under-*/*.js\"",
    "test-tap": "npm run tap -- \"test/tap/*.js\" \"test/network/*.js\" \"test/broken-under-*/*.js\"",
    "test-node": "tap --timeout 240 \"test/tap/*.js\" \"test/network/*.js\" \"test/broken-under-nyc*/*.js\""
  },
  "license": "Artistic-2.0"
}
`

Thanks for your help

**Comment by pksjce** [comment]
Have you tried this with `webpack 3.1` ? Can you provide a minimal repository to reproduce this behaviour?

**Comment by TheLarkInn** [comment]
I'm going to close this for now for inactivity. @MSeguin7 would you mind upgrading to latest version of webpack 3 and confirm if this still happens in the future? Thanks @pksjce
