### ISSUE TITLE
Change How Browser Retrieves Hot Module Replacement File

### ISSUE THREAD

**Issue by trisys3** [webpack/webpack#4841]
**Do you want to request a *feature* or report a *bug*?**
*feature*

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

I am sure this has been asked before, but is there any way to change how and when the browser gets the hot module replacement file? Right now, at least with the default `HotModuleReplacementPlugin`, it must be retrieved through the hot module replacement API, which involves a JSONP request. What I am proposing is a way to override that process, relatively easily.

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

I was thinking the bundle served to the client could have listeners attached to it, through something like WebSockets or postMessage, or even Server-Sent Events if your browser is new enough. This would obviously need to be set up by the server. My problem is that to do this right now, you need essentially 2 XHR/JSONP/WebSockets/etc. requests, one for the listener, which listens for the server broadcasting that a module has changed, and one for the hot module, so it can actually be applied. Even the dev middleware and server do this.

I am suggesting an API of some sort that could put this into one request(/SSE/WebSocket...). I know bandwidth is not usually a problem on computers where this replacement is being done, but it is still an extra request that must be made, or an extra socket that needs to stay open.

Firstly, is this possible? If it is possible, I suppose I am asking for a docs change. If not, this is a feature request.

**Comment by evilebottnawi** [comment]
Sorry for delay and is it out of scope webpack, you can use `webpack-dev-middleware` and implement own logic for loading
