### ISSUE TITLE
Debugger breakpoint not hit in Chrome

### ISSUE THREAD

**Issue by stianl** [webpack/webpack#4844]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Debugger breakpoint is only hit in Firefox.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Clone [webpack-source-maps](https://github.com/stianl/webpack-source-maps) (files shamelessly stolen from https://github.com/webpack/webpack/issues/4423#issue-211890851)
2. run `npm install && npm start`
3. Set a breakpoint in browser inspector on line 10 in `webpack://index.js?2645` (the `console.log` statement).

**What is the expected behavior?**

The breakpoint should be hit in Chrome too.

As mentioned in #3165  there are some issues with source maps in Chrome, and this seems to be one of them.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

* Firefox 53
* Chrome 58
* webpack 2.5.1
* node 6.10.1
* Windows 10

**Comment by vankop** [comment]
I don't think that this is a webpack issue..

**Comment by evilebottnawi** [comment]
@vankop Can you clarify?

**Comment by evilebottnawi** [comment]
Looks like it was chrome bug, in `Version 85.0.4183.83 (Official Build) (64-bit)` works fine, let's close issue, anyway if you faced with this issue again feel free to open the new issue with reproducible test repo, feel free to feedback
