### ISSUE TITLE
Re-ordering / Re-naming of vendor chunk modules, despite use of HashedModuleIdsPlugin and CommonsChunkPlugin

### ISSUE THREAD

**Issue by josephliccini** [webpack/webpack#4846]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Previously, in our app, we did not use the `HashedModuleIdsPlugin`.  This caused the vendor chunk's Hash to change each time we added or re-ordered modules. 

To fix this, I hooked up the `HashedModuleIdsPlugin`.  This seems to have fixed the issue at first, but upon inspection, I am seeing some issues where re-ordering is still occurring in the vendor chunk (not nearly as drastic amount of re-ordering as seen previously without `HashedModuleIdsPlugin`).

Here's a screenshot:
![image](https://cloud.githubusercontent.com/assets/7726025/25878129/342a9520-34dd-11e7-8689-5fb2cfb4a49f.png)
![image](https://cloud.githubusercontent.com/assets/7726025/25878268/40dedd52-34de-11e7-8d05-7ba19f07746b.png)

This particular library excerpt is from Angular 4.0.0.

However, no re-naming / ordering should occur if I correctly understand the intended behavior of `HashedModuleIdsPlugin` and `CommonsChunkPlugin`.

**If the current behavior is a bug, please provide the steps to reproduce.**
It seems some code in the `app` chunk is causing the `vendor` chunk to have some type of re-ordering / re-naming.  I am currently trying to pinpoint what change could have done this, but I am able to repro locally.  I can't expose the source code to the app, but I will try to make a simpler example / demo app if I can.

**What is the expected behavior?**
I would expect with `HashedModuleIdsPlugin`, no update to the vendor bundle hash unless a new vendor module was added / removed / modified.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Node 6.9.1
webpack 2.5.1
OS: Windows 10

**Comment by sokra** [comment]
Yep this seem to be an bug. The fix is easy. The properties `usedExports` in `Module` need to be sorted.

**Comment by ssuman** [comment]
@sokra May i work on this issue to provide PR ?

**Comment by sokra** [comment]
yep. that would be great

**Comment by josephliccini** [comment]
Happy to test the fix once it's in review. Thanks guys!

**Comment by restrry** [comment]
I just encountered that issue and _probably_ we have similar problems(There are steps how to re-produce my problem in https://github.com/webpack/webpack/issues/4980)
my local fix was https://github.com/restrry/webpack/tree/issue-4980, probably @ssuman could use it or I can send PR if no one fix that.
Anyway I'm not sure how to test it. seems that we need to build in 2 consecutive steps and then compare their chunkhashes. someone sees how to test it cheaply?

**Comment by ssuman** [comment]
@restrry Sure. please go ahead send the PR.
