### ISSUE TITLE
ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by saisaraswathi** [webpack/webpack#4848]
Error: ReferenceError: exports is not defined
	    at eval (http://localhost:3000/app/products/product-list.component.js:2:23)
	    at eval (<anonymous>)
	    at Object.eval (http://localhost:3000/app/app.component.js:10:32)
	    at eval (http://localhost:3000/app/app.component.js:26:4)
	Evaluating http://localhost:3000/app/products/product-list.component.js
	Evaluating http://localhost:3000/app/app.component.js
	Evaluating http://localhost:3000/app/app.module.js
	Evaluating http://localhost:3000/app/main.js
	Error loading http://localhost:3000/app/main.js
(anonymous) @ localhost/:22
ZoneDelegate.invoke @ zone.js:232
Zone.run @ zone.js:114
(anonymous) @ zone.js:502
ZoneDelegate.invokeTask @ zone.js:265
Zone.runTask @ zone.js:154
drainMicroTaskQueue @ zone.js:401
ZoneTask.invoke @ zone.js:339

**Comment by saisaraswathi** [comment]
I am getting this error when i am trying to load html of another  component in root component

**Comment by coockoo** [comment]
As far as I can remember, it is `export` not `exports`.
You can take a look at es6 modules syntax and stuff [here](http://2ality.com/2014/09/es6-modules-final.html)
You can use http://stackoverflow.com/ for future questions. This is kinda bug tracker and hot helpdesk.
