### ISSUE TITLE
webpack 2.5.1 can't use async CommonsChunkPlugin

### ISSUE THREAD

**Issue by hacke2** [webpack/webpack#4850]
**webpack 2.5.1 can't use async CommonsChunkPlugin**

**What is the current behavior?**

use async CommonsChunkPlugin

```
new webpack.optimize.CommonsChunkPlugin({
      async: 'used-twice',
      minChunks: (module, count) => (
        count >= 2
      ),
})
```

**If the current behavior is a bug, please provide the steps to reproduce.**

see this demo

https://github.com/DrakeLeung/webpack-code-splitting-demo

**What is the expected behavior?**

I expected this 

![image](https://cloud.githubusercontent.com/assets/6399899/25893033/ec46f74a-35a8-11e7-8173-eec579cd9f71.png)

but get this

![image](https://cloud.githubusercontent.com/assets/6399899/25893060/0512f742-35a9-11e7-9c7f-53d95f006923.png)

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

node: v7.6.0
os: mac
webpack: 2.5.1

**but 2.4.1 not this bug**

**Comment by stevewillard** [comment]
Just ran into the same issue. Downgrading to 2.4.1 fixed it for me.

**Comment by MethodenMann** [comment]
Release Note 2.5.0 says: "CommonsChunkPlugin in async mode doesn't extract from initial chunks"

I guess its related to this change. I also had to downgrade to 2.4.1 otherwise my output is about double the size.

**Comment by bbthorntz** [comment]
Any workarounds for this? Is it scheduled to be fixed? We're also downgrading to 2.4.1 or the app size about three times the intended size.

**Comment by iNikNik** [comment]
@bbthorntz take a look at my comment here https://github.com/webpack/webpack/issues/5109#issuecomment-311154920 :

you should specify name option to CommonChunksPlugin same as your entry point (initial chunk)

**Comment by bbthorntz** [comment]
@iNikNik awesome! Very confusing behaviour, but very happy it's working now. Thanks again!

**Comment by hacke2** [comment]
Yes, use the solution @iNikNik  provided, the program can run normally.Finally, we can finally use webpack 3.0 👏

**Comment by pengleelove** [comment]
```
new webpack.optimize.CommonsChunkPlugin({
     name: 'app',
      async: 'used-twice',
      minChunks: (module, count) => (
        count >= 2
      ),
})
```

Specify the dependent module name of CommonsChunkPlugin ,eg: name: 'app', now it's fine
