### ISSUE TITLE
Simplify the naming of bundled library components

### ISSUE THREAD

**Issue by Viatorus** [webpack/webpack#4851]
**Do you want to request a *feature* or report a *bug*?**

A feature request to remove the additional library block naming around a library components.

**What is the current behavior?**

Exporting a single class with libraryTarget: "this" (or "umd") adds another namespace around the class with the same name.
```javascript
src/core/TestLib.js
src/adapter/LocalStorage.js
src/adapter/NativeStorage.js
```

After creating a bundled library for each target, I have to call:
```javascript
new TestLib()
new TestLib.Adapter.NativeStorage.NativeStorage();
new TestLib.Adapter.LocalStorage.LocalStorage();
```

**What is the expected behavior?**

I would like to have the option to bundle the component without additional "object block", so I could use:

```javascript
new TestLib();
new TestLib.Adapter.LocalStorage();
new TestLib.Adapter.NativeStorage();
```

**If this is a feature request, what is motivation or use case for changing the behavior?**

Simplify the call to the exported classes of a library.
Check out this [repository](https://github.com/Viatorus/WebpackTest4Library) for an example project.

**Comment by sokra** [comment]
I guess you could do a PR adding support for a `output.exposeDefault` which only exposes the `default` export instead of the whole ESM.

**Comment by Viatorus** [comment]
I will have a look at the code how to implement this.

But currently I cannot run the tests of webpack.

```
git clone https://github.com/webpack/webpack.git
npm install
npm run test
```
lead to:

> webpack@2.5.1 test /home/toni/projects/webpack
> mocha test/*.test.js --harmony --check-leaks
> 
> module.js:472
>     throw err;
>     ^
> 
> 
> Error: Cannot find module 'webpack/lib/Chunk'
>     at Function.Module._resolveFilename (module.js:470:15)
>     at Function.Module._load (module.js:418:25)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/home/toni/projects/webpack/node_modules/extract-text-webpack-plugin/index.js:9:13)
>     at Module._compile (module.js:571:32)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:488:32)
>     at tryModuleLoad (module.js:447:12)
>     at Function.Module._load (module.js:439:3)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/home/toni/projects/webpack/test/HotTestCases.test.js:8:27)
>     at Module._compile (module.js:571:32)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:488:32)
>     at tryModuleLoad (module.js:447:12)
>     at Function.Module._load (module.js:439:3)
>     at Module.runMain (module.js:605:10)
>     at run (bootstrap_node.js:423:7)
>     at startup (bootstrap_node.js:147:9)
>     at bootstrap_node.js:538:3

**Comment by pksjce** [comment]
@Viatorus - Did you run `npm link && npm link webpack` on the repo? This will fix the error you are seeing with the tests.
