### ISSUE TITLE
dynamic import naming doesn't work

### ISSUE THREAD

**Issue by MarvinXu** [webpack/webpack#4861]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
I used comment to define chunkname as follows:
```javascript
import(/* webpackChunkName: "chunk1" */'@/components/chunk1.js')
```
But in build report there is no chunk name specified and still generate filename as 1.[hash].js

**If the current behavior is a bug, please provide the steps to reproduce.**
https://github.com/MarvinXu/webpack-chunkname-test
```
npm install
npm run build
```

**Comment by stevewillard** [comment]
Try with an '='
```
import(/* webpackChunkName="chunk1" */'@/components/chunk1.js')
```

**Comment by MarvinXu** [comment]
> Try with an '='
> 
> import(/* webpackChunkName="chunk1" */'@/components/chunk1.js')

doesn't work.

**Comment by maelon** [comment]
Same problem.
I had to used webpack 1. The old api `require.ensure` works perfectly in webpack 1.

**Comment by MarvinXu** [comment]
To be clear, I use the latest webpack(2.5.1) in my project. The `require.ensure` method works fine with the chunkname, it's just comment definition in `import()` doesn't work. I don't know where went wrong.

I added `require.ensure` test in my project:
[https://github.com/MarvinXu/webpack-chunkname-test](https://github.com/MarvinXu/webpack-chunkname-test)

**Comment by ematipico** [comment]
I use this feature (2.5.1) and it works fine to me. The only difference is that I don't have the '@' inside the path of my dynamic module; instead I have a relative path.

**Comment by MarvinXu** [comment]
@ematipico '@' is an alias for 'src', I've tested it is not relevant to this.

**Comment by maelon** [comment]
I also set an alias for path, so it fails here?

**Comment by a573367014** [comment]
I have the same problem

**Comment by probablyup** [comment]
It works for me without the `@` - might be something with your setup.

**Comment by SilenY** [comment]
I encountered this and it turned out I had to set [output.chunkFilename](https://webpack.js.org/configuration/output/#output-chunkfilename) in my webpack config

**Comment by MarvinXu** [comment]
> It works for me without the @ - might be something with your setup. (I'm on OS X, for reference.)

Did you test on my project? I removed alias '@' just now. Can you test it for me once more?

**Comment by 6220119** [comment]
This is not related to Webpack as @MarvinXu is using `vue-cli` with `webpack` template to generate the project. This issue should be closed

**Comment by devinRex** [comment]
Same problem. Does someone find the solution？

**Comment by lihaoqi1991** [comment]
I also have this problem, does someone resolve this issue?

**Comment by ematipico** [comment]
The problems were related to bad configuration inside the project. At the moment I am heavily using this feature and I don't have issues. What your problem? Care to share some code of how you use the `import()`?

**Comment by MarvinXu** [comment]
This problem is caused by babel configuration `comment: false` in my project, babel removes the "magic comments" before it takes effect. Check `.babelrc` to see if you have similar configuration, set comment to true or simply remove it and it should work.

More details please see https://github.com/vuejs-templates/webpack/issues/730

**Comment by axe312ger** [comment]
Same issue. Was suspecting babel but even with my .babelrc with `comments: true` it won't work :(

**Comment by axe312ger** [comment]
Okay gotcha: I set `output.filename` to include `[name]` but forgot to configure `output.chunkFilename` to contain `[name]` 💡

**Comment by milewski** [comment]
in my case i was using typescript so 1 it was removed the comments, 2 it was transforming the import to a promise ... setting `module:esnext` worked for me

**Comment by devinRex** [comment]
Set the comment in .babelrc to false.`comments: false `
`  require.ensure([], (require) => resolve(require('@/views/ensureChunk.vue')), networkError, 'ensureChunk');`
   
` import(/* webpackChunkName: "import-chunk" */ '../views/importChunk.vue')`

**Comment by devpascoe** [comment]
A combo of comments: true in .babelrc and webpack config to include chunkFilename = '[name].js' did the trick.

**Comment by toverux** [comment]
**If you are using TypeScript**, please also ensure that you don't have this option in your `tsconfig.json`:

```json
{
  "compilerOptions": {
    "removeComments": true
  }
}
```

Let the removal of the comments to another plugin/loader, like UglifyJS. This option is only useful if you're not using a complex build tool, which is obviously not the case if you're reading this issue :)

**Comment by mikeaustin** [comment]
I'm also having issues with webpackChunkName with a simple test project. I have chunkFilename and don't strip comments. It always generates a 0.bundle.js

module.exports = {
  entry: './src/index.jsx',
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: '[name].bundle.js',
    chunkFilename: '[name].bundle.js'
  },
  ...
}

I feel so close! I'm simply separating the login page from the rest of the app.

**Comment by milewski** [comment]
@mikeaustin you know what.. one of my latest project which was working before out of suddenly started to output 0. 1. bundler names too!  it might be a bug with latest version of webpack.. try downgrading it a bit see if that works for you

**Comment by shlomiassaf** [comment]
Following @milewski,

This works, bundle is split
```
System.import(/* webpackChunkName: "OverviewComponent" */ './__tdm-code__.ts');
```

This does not, one bundle to all imports.
```
import(/* webpackChunkName: "OverviewComponent" */ './__tdm-code__.ts');
```

The issue seems' to be in `import()` only

**Comment by shlomiassaf** [comment]
This is weird because `ImportPlugin` does the same thing for `System.import` and `import-call` so I'm confused...

For now i'm just using `System.import`, which will be easy to port once I move to Webpack 4, I hope it's fixed there.

**Comment by js2me** [comment]
It's very odd so, on typescript and webpack with module esnext dynamic import is worked, and on just JavaScript and webpack dynamic import is not worked , with babel-plugin-dynamic-import too

**Comment by js2me** [comment]
@shlomiassaf r u using Typescript when you write 
```
System.import(/* webpackChunkName: "OverviewComponent" */ './__tdm-code__.ts');
``` ?

**Comment by BlackGlory** [comment]
`System.import` and `import` are different.

In my TypeScript+Webpack case, `{ "module": "commonjs" }` caused the problem. It worked fine on "es5" and "esnext".

**Comment by Armour** [comment]
To sum up, make sure you set:

* `comments: true` in `.babalrc` (this is the default)
* `chunkFilename: '[name].....'` in your webpack config

If you are using typescript, also make sure:
* `removeComments: false` under `compilerOptions` in `tsconfig.json`
* `module: esnext` in `tsconfig.json`

This works for me and here is my [commit](https://github.com/Armour/express-webpack-react-redux-typescript-boilerplate/commit/357d3a0f00cda1d2318244426861605489ff9efb) for adding dynamic import (code split) support to my react-typescript project, hope it helps :)

**Comment by jhernandez5922** [comment]
In case anyone else runs into this issue. I was using `new webpack.optimize.UglifyJsPlugin` and in that config I had `output: { comments: 0 }` and by changing it to `1` fixed it.

**Comment by qiaoqiaowang** [comment]
> To sum up, make sure you set:
> 
> * `comments: true` in `.babalrc` (this is the default)
> * `chunkFilename: '[name].....'` in your webpack config
> 
> If you are using typescript, also make sure:
> 
> * `removeComments: false` under `compilerOptions` in `tsconfig.json`
> * `module: esnext` in `tsconfig.json`
> 
> This works for me and here is my [commit](https://github.com/Armour/express-webpack-react-redux-typescript-boilerplate/commit/357d3a0f00cda1d2318244426861605489ff9efb) for adding dynamic import (code split) support to my react-typescript project, hope it helps :)

I set comments:false, my comments in code is removed, but non-entry module's webpackChunkName is not affected.

**Comment by amaroyche** [comment]
FYI make sure you are not importing desired chunk "directly" somewhere else in code.

**Comment by ericbiewener** [comment]
@Armour's last comment worked for me, but note that [you may need to also add `"moduleResolution": "node"](https://github.com/Microsoft/TypeScript/issues/16820#issuecomment-312033871) to preserve the module resolution approach that `"module": "commonjs"` provides.

**Comment by adjenks** [comment]
Can you make it just dynamically import a file just purely based on the text string and do the chunking yourself instead of having webpack mangle the names for you?

**Comment by rphl** [comment]
Still not working with import(). Works only with `System.import()` for me. But its deprecated?!? :-/

(chunkFilename is set)

`System.import(/* webpackChunkName="chunk1" '../components/chunk1.js')`

**Comment by FreezeSoul** [comment]
mark !!!!

**Comment by mzahidriaz** [comment]
I am also facing trouble with just `import` instead `System.import` is working for dynamic imports.
