### ISSUE TITLE
[Performance] Webpack 2.4.0+ slower than 2.3.x

### ISSUE THREAD

**Issue by NogsMPLS** [webpack/webpack#4863]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Currently getting a ~60 second difference between Webpack 2.4.0 and 2.3.3:

```
Version: webpack 2.4.0
Child
    Hash: a9e44da36f0f1261c351
    Time: 196998ms
```
vs.
```
Version: webpack 2.3.3
Child
    Hash: 603d49f5ab0d93e0c43f
    Time: 137490ms
```

The *only* change made to any config/build/etc  was changing webpack versions in package.json. 

I also tested this with 2.5.1, and had the same results as 2.4.0.

**If the current behavior is a bug, please provide the steps to reproduce.**
Install 2.3.3, build and record time. Up to 2.4.0+ and record time

**What is the expected behavior?**
A similar build-time to previous version of webpack.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Node: 6.9.4
webpack: tested 2.2.1, 2.3.3, 2.4.0, 2.4.1, 2.5.1. All versions 2.4.0 and above were slower than the versions below 2.4.0.

Not sure what would make such a drastic change in build time. Perhaps to acorn update to 5 that happen in 2.4.0? 

I'll see if I can dig a bit into the diffs and see if anything pops out.

**Comment by NogsMPLS** [comment]
well, it's not acorn 5.

I did some messing around with npm installing webpack via github from specific commits, and from what I can tell the culprit is this guy: https://github.com/webpack/webpack/commit/983904cfa354eb00256f44b973a539090a19c7c6

i'll continue looking into this and see if i can get a PR in

**Comment by NogsMPLS** [comment]
I went ahead and manually changed that commit back in my local dependencies, and it got the performance boost back. So I can confirm that the performance regression was introduced in that commit.

The problem with this is, that commit is from this pull request: https://github.com/webpack/webpack/pull/4622

so, reverting that commit looks like it would break using `context.issuer` in custom resolvers.

I'm curious what @sokra was going for with the `resolveContextInfo` in this commit: https://github.com/webpack/webpack/commit/da29d21ae44056ccbd525282300df7184e922d97#diff-1fd8fe07e83988b2301f9bad408cf5c2

Is it possible to keep the context feature, but also speed up performance back to what it was before that commit?

Another angle to investigate is: is this actually webpack? It doesn't seem like this change should create such a performance hit?

**Comment by NogsMPLS** [comment]
Also, just for the heck of it I attempted to use `webpack/webpack#beta` build, and still had the slow performance of 2.4.0+ versions.

**Comment by sokra** [comment]
da29d21 will cause that the resolve cache can used less often.

It passes `issuer` to the resolver. This allows to resolve depending on issuer. Maybe we can add an option to specify the context information passed to the resolver, so you get higher performance if you don't need it.

**Comment by briandipalma** [comment]
We're also seeing this regression

```
14:24 $ node scripts/test-webpack-build.js
Build: 31679.024ms
14:25 $ node scripts/test-webpack-build.js
Build: 33072.790ms
14:26 $ node scripts/test-webpack-build.js
Build: 31929.403ms
14:26 $ rm -rf node_modules/webpack
14:27 $ ni webpack@2.3.3
salestrader@3.0.0-alpha0 /Users/briand/dev/salestrader/apps/salestrader
└─┬ @caplin/build-tasks@4.0.0
  └─┬ webpack@2.3.3
    └── acorn@4.0.11
14:27 $ node scripts/test-webpack-build.js
Build: 16285.997ms
14:28 $ node scripts/test-webpack-build.js
Build: 15049.645ms
14:28 $ node scripts/test-webpack-build.js
Build: 15103.269ms
```

**Comment by lukeapage** [comment]
This change doubles our build time, so we are pinning 2.4.0

**Comment by lencioni** [comment]
I'm not sure if this is useful information, but FWIW at Airbnb, we also noticed this dramatic performance regression when going from v2.3.2 to v2.4.0 (with no other changes). So, we'll be stuck on v2.3.2 until this is fixed. Here are our before and after timings:

v2.3.2: 378644ms
v2.4.0: 751531ms

Let me know if I can provide any more information or if you'd like me to try anything out! Thanks for all of your hard work on this. 🏇

**Comment by lukeapage** [comment]
v2.3.2: 83 seconds
v3.0.0-rc.1: 62 seconds

So I guess other performance improvements have trumped this particular regression ?

**Comment by TheLarkInn** [comment]
cc @mikesherov if interested.

**Comment by awestroke** [comment]
We have stopped at v.2.3.3 until this is resolved.

**Comment by mikesherov** [comment]
Is this still a problem in Webpack 3?

**Comment by rozzzly** [comment]
@sokra I think I'm not alone in wanting a resolution to this, like many have already mentioned, it's keeping me stuck on an older version for one of my (larger) projects. It seems the reason for this pref regression got identified as a result of tighter caches thanks to [`da29d21`](https://github.com/webpack/webpack/commit/da29d21ae44056ccbd525282300df7184e922d97) could we make that behavior _opt-in_ or even if you could just show us how we could change our configs to avoid sending that extra context information, as you mentioned, then we'd be able to enjoy all the benefits of webpack@3

**Comment by mikesherov** [comment]
I'm going to look into this today.

**Comment by mikesherov** [comment]
Because no internal resolvers need the context information, and introducing an option to provide it would be a breaking change, my plan is as follows:

1. Stop passing context information like da29d21 did unless a custom resolve plugin is provided. This will give performance back to the overwhelming majority of folks who don't use resolvePlugins.
2. For Webpack 4.0, require resolve plugins to provide a property called `needsContext` (similar to `cacheable` for loader plugins). Then, when plugins are registered, Webpack can determine if any custom plugins actually need context, and only provide context in the case at least one needs it.

@sokra thoughts?

**Comment by mikesherov** [comment]
OK, I have a potential fix which is different from the ones proposed above. PR coming shortly to the enhanced-resolve repo.

Essentially, there will be a new `resolve` option called `aggressiveCache`, which is on by default, which ignores `request.context` entirely when considering whether a resolved module is cached or not. For users who need to consider context, they can set it to `false`, and that'll allow `context` to be considered for the key.

PR coming in like 10 minutes.

**Comment by mikesherov** [comment]
https://github.com/webpack/enhanced-resolve/pull/92

**Comment by mikesherov** [comment]
https://github.com/webpack/webpack/pull/5178 which leverages https://github.com/webpack/enhanced-resolve/pull/92

Feel free to test it out folks and see if it speeds up your builds again.

**Comment by lukeapage** [comment]
(Cross post)
webpack 3 - 65 seconds
webpack 3 with @mikesherov PR - 34.4 seconds
webpack 2.3.3 - 34.0 seconds

:)

**Comment by mikesherov** [comment]
We managed to sneak even more perf into #5178 thanks to a speedup @gdborton found, so the `master` branch should be even faster than 2.3.3 !

**Comment by filipesilva** [comment]
@mikesherov is there a way to figure out if a given setup has any resolve or resolveLoader plugins, so that we can take them out to avoid performance loss?

**Comment by mikesherov** [comment]
@filipesilva it would be in your resolve.plugins or resolveLoader.plugins configuration setting.

**Comment by filipesilva** [comment]
Ah that's straightforward, cheers!
