### ISSUE TITLE
CommonJS wrapping In AMD Support

### ISSUE THREAD

**Issue by yesvods** [webpack/webpack#4869]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**

```
  define('x', ['a', 'b'],function (a,b) {
      var res = a+b
      exports.action = function () {};
    });
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

```
  define('x', function (require, exports, module) {
      var a = require('a'),
          b = require('b');
      var res = a+b
      exports.action = function () {};
    });
```

**If this is a feature request, what is motivation or use case for changing the behavior?**

compatible with AMD standard.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

chrome, node 7+, webpack2, osx

**Comment by yesvods** [comment]
@bebraw I found that I can modify the ExternalModule in `webpack/lib` to implement that. But how can I do that in normal webpack plugin?

**Comment by bebraw** [comment]
> @bebraw I found that I can modify the ExternalModule in webpack/lib to implement that. But how can I do that in normal webpack plugin?

I think Tobias can answer that better. Let's hope he notices this issue.

**Comment by yesvods** [comment]
@sokra Need ur help, please.

**Comment by sokra** [comment]
Could you go into more details what's the current and expected behavior? Your issue includes just code snippets what what does they do and what do you expect?
