### ISSUE TITLE
Bug: loaders order not respected

### ISSUE THREAD

**Issue by damianobarbati** [webpack/webpack#4871]
Webpack is not respecting defined loaders orders: in the following case the string replace takes place after babel.

Version: ^2.3.2

Example: 
```
    module: {
        rules: [{
            test: [/\.js$/i],
            exclude: /node_modules/,
            use: [{
                loader: 'string-replace-loader',
                query: {
                    search: '.+?//@hide$',
                    flags: 'gim',
                    replace: '',
                },
            },{
                loader: 'babel-loader',
                options: {
//etc etc
```

**Comment by ndresx** [comment]
It's confusing, but not a bug. Loaders are more or less executed in a reversed way, meaning that it starts from the end of the array. That's why `babel-loader` is doing its job first and after that, the `string-replace-loader` kicks in.

**Comment by damianobarbati** [comment]
W-O-W: serious? I could not find this on webpack.js.org.

So should my ESLint config "after" webpack to actually lint my original files?

**Comment by ndresx** [comment]
If you are talking about `eslint-loader`?, yes, this one needs to do its job "before" `babel-loader` is executed, but actually needs to be defined after the `babel-loader` in the `use` array.
```
rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: [
          "babel-loader",
          "eslint-loader",
        ],
      },
    ],
```

**Comment by damianobarbati** [comment]
Got it, thanks!
