### ISSUE TITLE
Buffer module ends up in production build

### ISSUE THREAD

**Issue by davscro** [webpack/webpack#4872]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

I'm not sure is this bug or excepted behaviour but I believe it's a bug. Running ```yarn build``` to generate production build, **buffer** module ends up in production build!

```
 "scripts": {
    "build": "set NODE_ENV=production rimraf build/dist && webpack -p --config webpack/webpack.config.js && npm run bundle_check",
    "bundle_check": "babel-node bundle_check.js"
  },
```

Could someone explain me why this package ends up in production build. Am I missing something?

<img width="697" alt="screen shot 2017-05-13 at 00 43 18" src="https://cloud.githubusercontent.com/assets/1383250/26035181/7afea984-38c8-11e7-8ac8-83aece9af004.png">

```yarn why buffer```

<img width="538" alt="screen shot 2017-05-13 at 00 45 25" src="https://cloud.githubusercontent.com/assets/1383250/26019467/b8e25862-3775-11e7-8785-5fcfe0d7d81b.png">

```yarn why node-libs-browser```
<img width="444" alt="screen shot 2017-05-13 at 00 45 57" src="https://cloud.githubusercontent.com/assets/1383250/26019479/cea28f14-3775-11e7-9fbe-916ce2976fb1.png">

And webpack is specified only as dev dependency.

**What is the expected behavior?**
Buffer module should not be in production build.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Webpack: 2.5.1
Node: 7.8.0
OS: OSX Sierra

Thanks in advance,
Davor

**Comment by bebraw** [comment]
Check Axios. If I remember right, it pulls Buffer to the project and you have to work around it. Check their issue tracker as there might be something.

**Comment by davscro** [comment]
Ok, thank you very much for pointing me out to the right direction. 
Regards,
Davor

**Comment by thibaultchazal** [comment]
Hi @davscro,
Did you find a wait to exclude buffer from production ? Was it pulled from Axios ?
I didn't find anything...
