### ISSUE TITLE
Makefile dependency generation

### ISSUE THREAD

**Issue by bryanlarsen** [webpack/webpack#4875]
**Do you want to request a *feature* or report a *bug*?**

Feature request: automatic Makefile generation like `gcc -MM`

**What is the current behavior?**

I use this hacky script:

```sh
# filter to convert webpack --json to Makefile dependencies

echo -n $*': '
cat - |
    jq -r '.chunks[0].modules[].name' |
    sed "s|/~/|/node_modules/|g" |
    grep -v "^multi " | # filter out entries
    grep -v "^external " | # filter out external
    grep -v "(" | # filter out (ignored) and (webpack)/buildin etc
    grep -v "^template " |
    sed 's/.*!//' | # ignore the loaders
    sed "s|/srv/clara/current/|../../|"  | # we build inside a Docker container and push outside, so make sure all deps are relative
    sed "s/^/\t/"  | # convert to Makefile format (leading tab, end with \)
    sed 's/$/ \\/'
echo
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

If source files haven't changed, we don't want to run Webpack in our build scripts if we don't have to.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by sokra** [comment]
@webpack-bot move to webpack/webpack-cli

This *could* be a feature of the new CLI.

**Comment by evenstensberg** [comment]
Do you see this still being relevant @bryanlarsen ?
