### ISSUE TITLE
Use of `resolve` leads to unexpected resolution

### ISSUE THREAD

**Issue by zpao** [webpack/webpack#4876]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

packages resolve to local files when filename matches.

**If the current behavior is a bug, please provide the steps to reproduce.**

Repro in this repo (along with some more details explanation): https://github.com/zpao/testcases/tree/webpack-resolve

**What is the expected behavior?**

Local modules never clobber node packages.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

This was originally reported as an issue in my own package causing issues elsewhere. We finally determined the root cause being the webpack config. The final comment in the issue (https://github.com/facebook/fbjs/issues/234#issuecomment-301537684) indicates that this might be expected due to the use of `"."` in `resolve.modules`. I don't have enough webpack experience to confidently say this was user error, and it's a footgun regardless, so I wanted to make sure this gets filed. It's definitely edgecasey.

Anyway, thanks for everything!

cc @confiks (who derived the original test case and help narrow this down)

**Comment by sokra** [comment]
The order in the `resolve.modules` array defines the preference. Here `.` is before `node_modules` so local modules are preferred. If you use `resolve.modules: ["node_modules", "."]`, node modules are preferred.

**Comment by sokra** [comment]
`.` in `resolve.modules` is bad anyway.

**Comment by jeremywrowe** [comment]
Thanks so much for following up!
