### ISSUE TITLE
Can't use static methods of angular service (TypeScript)

### ISSUE THREAD

**Issue by dirkvanvugt01** [webpack/webpack#4878]
**Do you want to request a *feature* or report a *bug*?**

A bug

**What is the current behavior?**

I have implemented an angular service to combine methods that are used throughout my app in multiple components. 
I would like to make methods static since they only return data that isn't bound to the service's instance. 
However when I make a method static Webpack seems to miss the reference to the service.

Note: this is all run on my local machine

**If the current behavior is a bug, please provide the steps to reproduce.**

```
module X.Y {
    class Z {
    
        constructor() {
        }
    
        public static sorting(z: any) {
            //do stuff
        
            return z;
        }
    }
}
```

**What is the expected behavior?**

When I want to use this method I'd expect to use it like this:

```
let valuesForSorting = ['a', 'b', 'c'];
let sortedValues = X.Y.Z.sorting(valuesForSorting);
```
However I get a console error saying
ReferenceError: X is not defined

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Chrome, PhpStorm 2017.1.3, Webpack 2.4.1, Angular 1.5.3, TypeScript 2.2.2, Windows 10

[webpack-issue.zip](https://github.com/webpack/webpack/files/1003604/webpack-issue.zip)

**Comment by sokra** [comment]
Looks like your are using typescript namespaces. This is not related to webpack. Don't use them for modular applications.


Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md).
