### ISSUE TITLE
fail to bundle sequelize

### ISSUE THREAD

**Issue by andylpjr** [webpack/webpack#4879]
Hi all,

I just currently working on Express js+typescript with Sequelize ORM and want to bundle using Webpack. The problem is I got warning and fail each time trying to bundle.

Here is my warning/error message:
```
WARNING in ./~/sequelize/lib/dialects/mysql/connection-manager.js
Module not found: Error: Can't resolve 'mysql' in 'D:\Project\MyMe\node_modules\sequelize\lib\dialects\mysql'
 @ ./~/sequelize/lib/dialects/mysql/connection-manager.js 20:17-33
 @ ./~/sequelize/lib/dialects/mysql/index.js
 @ ./~/sequelize/lib/sequelize.js
 @ ./~/sequelize/index.js
 @ ./src/server/models/index.js
 @ ./src/server/controllers/TopUp.ts
 @ ./src/server/controllers/index.ts
 @ ./src/router/router.ts
 @ ./src/App.ts
 @ ./src/index.ts

WARNING in ./~/express/lib/view.js
80:29-41 Critical dependency: the request of a dependency is an expression

WARNING in ./~/sequelize/lib/sequelize.js
686:60-73 Critical dependency: the request of a dependency is an expression

WARNING in ./~/sequelize/lib/dialects/mysql/connection-manager.js
18:17-60 Critical dependency: the request of a dependency is an expression

WARNING in ./~/sequelize/lib/dialects/mssql/connection-manager.js
18:15-71 Critical dependency: the request of a dependency is an expression

WARNING in ./~/sequelize/lib/dialects/postgres/connection-manager.js
20:14-57 Critical dependency: the request of a dependency is an expression

WARNING in ./~/sequelize/lib/dialects/sqlite/connection-manager.js
22:15-71 Critical dependency: the request of a dependency is an expression

ERROR in ./~/pg/lib/native/index.js
Module not found: Error: Can't resolve 'pg-native' in 'D:\Project\MyMe\node_modules\pg\lib\native'
 @ ./~/pg/lib/native/index.js 9:13-33
 @ ./~/pg/lib/index.js
 @ ./~/sequelize/lib/dialects/postgres/connection-manager.js
 @ ./~/sequelize/lib/dialects/postgres/index.js
 @ ./~/sequelize/lib/sequelize.js
 @ ./~/sequelize/index.js
 @ ./src/server/models/index.js
 @ ./src/server/controllers/TopUp.ts
 @ ./src/server/controllers/index.ts
 @ ./src/router/router.ts
 @ ./src/App.ts
 @ ./src/index.ts
```

Here is my package.json:
```
"devDependencies": {
    "@types/body-parser": "^1.16.3",
    "@types/chai": "^3.5.2",
    "@types/chai-http": "0.0.30",
    "@types/debug": "0.0.29",
    "@types/express": "^4.0.35",
    "@types/mocha": "^2.2.41",
    "@types/morgan": "^1.7.32",
    "@types/node": "^7.0.18",
    "chai": "^3.5.0",
    "chai-http": "^3.0.0",
    "mocha": "^3.3.0",
    "ts-loader": "^2.0.3",
    "ts-node": "^3.0.4",
    "typescript": "^2.3.2",
    "webpack": "^2.5.1",
    "webpack-dev-server": "^2.4.5"
  },
  "dependencies": {
    "body-parser": "^1.17.1",
    "debug": "^2.6.6",
    "express": "^4.15.2",
    "morgan": "^1.8.1",
    "pg": "^6.1.5",
    "pg-hstore": "^2.3.2",
    "sequelize": "^3.30.4"
  }
```

Below is my webpack.config.js
```
var path = require('path');
var webpack = require('webpack')
var fs = require('fs')

var nodeModules = {};
fs.readdirSync('node_modules')
  .filter(function(x) {
    return ['.bin'].indexOf(x) === -1;
  })
  .forEach(function(mod) {
    nodeModules[mod] = 'commonjs ' + mod;
  });

module.exports = {
    entry: './src/index.ts',
    output: {
        filename: 'bundle.js',
        path: path.resolve(__dirname, 'dist')
    },
    module: {
        loaders: [
            {
                test: /\.ts?$/,
                loader: 'ts-loader',
                exclude: /node_modules/,
            }
        ]
    },
    resolve: {
        extensions: [".tsx", ".ts", ".js"]
    },
    devServer: {
        port: 3000
    },
    target: 'node'
}

if (process.env.NODE_ENV === 'production') {
  module.exports.devtool = '#source-map'
  module.exports.plugins = (module.exports.plugins || []).concat([
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: '"production"'
      }
    }),
    new webpack.optimize.UglifyJsPlugin({
      sourceMap: true,
      minimize: true,
      compress: {
        warnings: false
      }
    }),
    new webpack.LoaderOptionsPlugin({
      minimize: true
    })
  ])
}
```

Fyi, before I'm adding Sequelize to my project its bundle fine with Express+typescript only. I know there is something I'm missing because I'm still new to webpack env. Thanks.

**Comment by sokra** [comment]
see https://github.com/liady/webpack-node-externals

**Comment by Sujina-Saddival** [comment]
This worked for me. If you want to make webpack config for all sequelize models dynamically check this out.

models/index.js -> should look something like this

const glob = require('glob');
const sequelize = new Sequelize(databaseUrl);

const models = [];
glob.sync(`${__dirname}/*.js`).forEach((model) => {
  const modelname = path.basename(model);
  if (modelname !== 'index.js') {
    models.push(require(`${__dirname}/${modelname}`));
  }

  models.forEach((module) => {
    const sequelizeModel = module(sequelize, Sequelize);
    db[sequelizeModel.name] = sequelizeModel;
  });
});

Object.keys(db).forEach((modelName) => {
  if (db[modelName].associate) {
    db[modelName].associate(db);
  }
});

db.sequelize = sequelize;
db.Sequelize = Sequelize;

module.exports = db;


Webpack.config.js -> should look something like this

const path = require('path');
const nodeExternals = require('webpack-node-externals');
const glob = require('glob');

module.exports = [
  {
    entry: glob.sync('./src/**/*.js').reduce((entries, entry) => Object.assign(entries, { [entry.replace('./src/models', '').replace('.js', '')]: entry }), {}),
    externals: [nodeExternals()],
    output: {
      filename: '[name].js',
      libraryTarget: 'commonjs',
      path: path.resolve(__dirname, 'build/models'),
    },
    module: {
      rules: [
        {
          test: /\.js$/,
          include: path.resolve(__dirname, 'src'),
          exclude: /(node_modules|build)/,
          use: {
            loader: 'babel-loader',
            options: {
              plugins: [
                'babel-plugin-transform-object-rest-spread',
                'transform-runtime',
              ],
              presets: ['env', 'stage-3'],
            },
          },
        },
      ],
    },
    target: 'node',
    node: {
      __dirname: false,
    },
  }];

**Comment by nahumzs** [comment]
The previous approach doesn't work with Postgres, I didn't try it with MySQL, But I followed [this](https://github.com/sequelize/sequelize/issues/9489#issuecomment-493304014) which seem a more elegant solution.

**Comment by soryy708** [comment]
https://github.com/sequelize/sequelize/issues/13169
