### ISSUE TITLE
AggressiveSplittingPlugin does not support child compilations which emit to static asset file paths

### ISSUE THREAD

**Issue by hulkish** [webpack/webpack#4887]
**Do you want to request a *feature* or report a *bug*?**

**bug**

Actually I've tried asking about this in the webpack gitter channel several times now and haven't seen a response yet.

**What is the current behavior?**

`webpack/lib/optimize/AggressiveSplittingPlugin` does not support child compilations which emit to static asset file paths correctly.

Please see https://github.com/jantimon/html-webpack-plugin/pull/670 for more details. This means you cannot use `AggressiveSplittingPlugin` with **any** plugin with creates a child compilation that emits to a static asset file name. This is including (but, not limited to) the following webpack plugins:

- [extract-text-webpack-plugin](https://github.com/webpack-contrib/extract-text-webpack-plugin)
- [html-webpack-plugin](https://github.com/jantimon/html-webpack-plugin)
- [script-ext-html-webpack-plugin](https://github.com/numical/script-ext-html-webpack-plugin)

**If the current behavior is a bug, please provide the steps to reproduce.**

Use `AggressiveSplittingPlugin` with any webpack config which uses one of the plugins listed above. For example:
1.  run:
```bash
git clone https://github.com/simonsmith/github-user-search.git
cd github-user-search
yarn
``` 
2. add `AggressiveSplittingPlugin` to it's webpack config.
3. run:
```bash
yarn build
```

You'll see an error which looks something like this:
```bash
ERROR in chunk 1 [initial]
extract-text-webpack-plugin-output-filename
Conflict: Multiple assets emit to the same filename 'extract-text-webpack-plugin-output-filename'
```

**What is the expected behavior?**
This plugin should support the static asset file name strategy that many plugins use in child compilations.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Versions of node or webpack probably doesn't matter for this, as it's been an issue for a long time.

**Comment by hulkish** [comment]
I am willing to contribute and provide a PR for this issue. I just need some direction on what would be the preferred solution, as I believe a poor solution could result in adding a lot of unnecessary `advanced-optimize-chunks` bundle time..

**Comment by hulkish** [comment]
anyone? @sokra i was told you had some insight on this.

**Comment by sokra** [comment]
change `plugin("compilation", ...` to `plugin("this-compilation", ...` in the Plugin.

**Comment by hulkish** [comment]
@sokra I've tried this. The problem is this breaks the minSize/maxSize functionality. More details here: https://github.com/jantimon/html-webpack-plugin/pull/670#issuecomment-301639384

**Comment by hulkish** [comment]
Well not sure this is going anywhere. I suppose just close?

**Comment by hulkish** [comment]
I see this is fixed via https://github.com/webpack/webpack/commit/3caf4675a0d70a01a93a8747d070e2153b1fca7b - You can close this now, I suppose.

_Sent from my Google Pixel XL using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
