### ISSUE TITLE
Configure import() to use local Promise polyfill

### ISSUE THREAD

**Issue by andyearnshaw** [webpack/webpack#4890]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Currently, `import()` has a dependency on global `Promise` being available.

**If the current behavior is a bug, please provide the steps to reproduce.**
N/A

**What is the expected behavior?**
I should be able to use `import()` by including a promise polyfill local to my package.

**If this is a feature request, what is motivation or use case for changing the behavior?**
I'm rewriting a legacy script to run on 3rd party sites where we can't expect that `Promise` is polyfilled, nor can we apply the polyfill ourselves.  Our script can't touch the globals on the host because that could potentially interfere with things like feature detection (for example, a host is checking to see if Promise is available and making the assumption that another feature is available).

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
N/A

**Comment by mc-zone** [comment]
Did your scripts bundled standalone? Maybe you can bundle your scripts into a library before provided it to  3rd party sites, so that you can  feel free to make your own polyfill.

**Comment by mc-zone** [comment]
The use of Promise only in the [**bootstrap code**](https://github.com/webpack/webpack/blob/master/lib/JsonpMainTemplatePlugin.js) AFAIK. you can insert polyfill into here and define Promise in local scope. 

```javascript
YourPolyfillPlugin.prototype.apply = function(compiler){
  compiler.plugin("compilation", function(compilation){
    compilation.mainTemplate.plugin("bootstrap", function(bootstrapSource) {
      return `
        if(!Promise){
          var Promise = ${require("your-promise-polyfill")};
         }
      ` + bootstrapSource;
    })
  })
};
```

I think it should be work.
 (Btw, I have a [webpack2-polyfill-plugin](https://github.com/mc-zone/webpack2-polyfill-plugin) to do this but already define Promise at global. However you also can use it for reference, or welcome to make a PR :) )

**Comment by andyearnshaw** [comment]
Thanks, I'll take a look into this when our project ramps up :smile:.

**Comment by ooflorent** [comment]
This issue is inactive for more than a year and is likely to be solved. If you still encounter this specific problem, please open a new issue. 

@mc-zone's solution is good. You could also include your `Promise` polyfill in the main chunk.
