### ISSUE TITLE
adding target results in error "require not defined" (Without deleting the template) ;)

### ISSUE THREAD

**Issue by wende60** [webpack/webpack#4891]
**Do you want to request a *feature* or report a *bug*?**
Seems to be a bug

**What is the current behavior?**
adding a target like 'electron' or 'electron-renderer' results in an error, without target everything is fine:
**Uncaught ReferenceError: require is not defined.**

**If the current behavior is a bug, please provide the steps to reproduce.**
My current and simple config can be found here:
https://github.com/wende60/timeTracker/blob/master/webpack.config.js
As mentioned before, just adding a target crashes the app with the error described above

**What is the expected behavior?**
after adding a target i expect that  importing electron to my react components is possible (this was the result of prev. researches)

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Node is the latest Version,
webpack: "^2.5.1",
webpack-dev-server: "^2.4.3"
Mac OSX 10.11

**Comment by wende60** [comment]
used webpack-target-electron-renderer like here now
https://github.com/wende60/webpack-web-and-electron-example, so going to close this one...

**Comment by mihaiconstantin** [comment]
Link is dead. Can you please update?
