### ISSUE TITLE
Ability to add information to stats.toJson()

### ISSUE THREAD

**Issue by jscheid** [webpack/webpack#4892]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

There are currently no hooks that would allow adding data to the output of `stats.toJson()`, and the `toJson` function doesn't support copying "user data" from assets in the `compilation` object.

**What is the expected behavior?**

There is such a hook _or_ there is a way to add user data to assets in the `compilation` object that gets copied over to the JSON output.

**If this is a feature request, what is motivation or use case for changing the behavior?**

As discussed before with @sokra: 
- https://gitter.im/webpack/webpack?at=568fdccc7669220736029bd4
- https://gitter.im/webpack/webpack?at=56917e08ee13050b38a298fa

Beyond what was discussed on Gitter, the serialized stats are a great way to pass information produced by the build to a server process in a "universal" or "hybrid" rendering setup. Without the ability (for plugins) to add data to that object, such data has to be passed around in other ways which means more files are generated, the user has to decide what they are called and where they are placed, and perhaps combine data from separate files. Having a hook or some other extension mechanism would allow solving this more elegantly.

See also https://github.com/waysact/webpack-subresource-integrity/issues/45

**Comment by vankop** [comment]
I think you are looking for something like `Compilation.hooks.statsPrinter`. It is possible with `webpack@5`.

**Comment by jscheid** [comment]
@vankop thanks, yes we're actually already using it in https://github.com/waysact/webpack-subresource-integrity/blob/90542f89093dd75ffae93eb8ada583622c6405dd/index.js#L405

I forgot I had opened this ticket, closing it now. Thanks again.
