### ISSUE TITLE
Module '/node_modules/less/index.js' is not a loader

### ISSUE THREAD

**Issue by SeptemberMaples** [webpack/webpack#4893]
I'm trying to upgrade webpack1.x to webpack2.x.  and find this question like below. 

`Error: Module '/Users/ziseyiliao/projects/node_modules/less/index.js' is not a loader (must have normal or pitch function)`

webpack.config.js

`rules: [
            {
            test: /\.js$/,
            loader: 'babel-loader',
            exclude: /node_modules/
        }, {
            test: /\.less$/,
            use: ExtractTextPlugin.extract({
                fallback: 'style-loader',
                use:[
                    "css-loader",
                    "autoprefixer-loader",
                    "less-loader"
                ]
            })
        }]`

**Comment by sokra** [comment]
Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md).
