### ISSUE TITLE
Overwriting config parameters through CLI

### ISSUE THREAD

**Issue by fera0013** [webpack/webpack#4895]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

According to my understanding and tests, I can use webpack either in combination with a config file which includes the entry and output paths, or I can pass the entry and output path as CLI arguments. But both alternatives are mutually exclusive, i.e. I cannot overwrite the entry and output paths specified in a config file through CLI parameters, while still using the other specifications in the config file. 

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

I want to use a webpack.config.js AND overwrite the entry and output paths of that config file using CLI parameters. 

**If this is a feature request, what is motivation or use case for changing the behavior?**

I need to change entry and output paths dynamically and depending on some context while keeping the other entries of an entry file. 

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by bebraw** [comment]
@webpack-bot move to webpack/webpack-cli
