### ISSUE TITLE
strictExportPresence: true is not enforced for unused modules

### ISSUE THREAD

**Issue by gaearon** [webpack/webpack#4897]
**Do you want to request a *feature* or report a *bug*?**

Depends on what you think about it.

**What is the current behavior?**

With `strictExportPresence: true`, I get errors about missing ES6 exports.
However **if I don't use the import, it doesn't get checked.**

For example:

```js
// Compile error: './module' does not contain an export named 'bad'

import {bad} from './module';
console.log(bad);
```

```js
// No error

import {bad} from './module';
```

**If the current behavior is a bug, please provide the steps to reproduce.**

```js
create-react-app myapp --scripts-version react-scripts@canary
cd myapp
npm start
```

Then do the thing above. But I expect this to be always reproducible with Webpack 2, ES6 modules, and `strictExportPresence: true`.

**What is the expected behavior?**

I would expect the build to fail even if the export is unused, since it likely indicates a mistake anyway.

**If this is a feature request, what is motivation or use case for changing the behavior?**

Finding mistakes earlier.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

webpack 2.5.1

**Comment by jm2242** [comment]
Are there any plans to support this improvement?

**Comment by vankop** [comment]
Should work with `webpack@latest`. Feel free to report new issue with reproducible repo.
