### ISSUE TITLE
How to force webpack not to use eval in production

### ISSUE THREAD

**Issue by alihaghighatkhah** [webpack/webpack#4899]
**Do you want to request a *feature* or report a *bug*?**
Baiscally a *question*, but it might be a bug, I'm not sure.

**What is the current behavior?**

I'm having the [csp](https://github.com/webpack/webpack/issues/4094) error because webpack is using eval in **one** of my bundles.

I've tried to use all the [options available](https://webpack.js.org/configuration/devtool/) for source mapping and canceling devtools.
Also I've tried configuring the compression using `Webpack.optimize.UglifyJsPlugin` in which you can set sourceMap: false. but I'm still getting the same error and I can see there's a line in my bundle:
```
t.exports=function(t){"undefined"!=typeof execScript?execScript(t):eval.call(null,t)}
```
which is calling `eval`.

**If the current behavior is a bug, please provide the steps to reproduce.**
 - In your configuration set devtool to any possible option even `devtool: false`
 - run `webpack -p`
 - Search your bundles for `eval.call`
- You'll find an occurance

**What is the expected behavior?**

I was expecting that we have an option that creates bundles without using `eval`.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

I'm using webpack 2.4.1, on node 6.10.0 and npm 3.10.10 . but I've tried it with differen versions of webpack 2.x.x and on npm 3 and npm 4 on OSX and Ubuntu.

Thank you

**Comment by evilebottnawi** [comment]
@alihaghighatkhah can your provide minimal reproducible test repo? very interesting

**Comment by sokra** [comment]
This is caused by the script-loader. Don't use the script-loader.

**Comment by alihaghighatkhah** [comment]
@sokra exactly. I found the issue and fixed it. Thank you

**Comment by alihaghighatkhah** [comment]
@evilebottnawi As Sokra said I was using script loader, i just removed it and used a combination of exports/imports loaders instead.

**Comment by osher** [comment]
Can you please tell what to use instead of script-loader?

**Comment by dcsaszar** [comment]
There's still an `eval` causing CSP errors: #5627

**Comment by hotrush** [comment]
@reyraa can you show your webpack config please. I tried to use script loader (not babel), but still see evals

**Comment by evilebottnawi** [comment]
@dcsaszar https://github.com/webpack/webpack/issues/5627#issuecomment-362543814

**Comment by nschloe** [comment]
I have the same issue when building a browser extension where `eval()` is not allowed. The config is
```js
const merge = require("webpack-merge");
const common = require("./webpack.common.js");

module.exports = merge(common, {
  // devtool: "inline-source-map"
});
```
When using `"inline-source-map"`, the `eval()`s disappear. Is this the recommended setting?

**Comment by evilebottnawi** [comment]
`inline-source-map` is not for production, please read docs https://webpack.js.org/configuration/devtool/

**Comment by nschloe** [comment]
@evilebottnawi I understand that it isn't meant for production, but unfortunately I couldn't find any other way of removing `eval()` from the output. The link you provide isn't explicit about it either.

**Comment by evilebottnawi** [comment]
Use `devtool: "source-map"`

**Comment by navidshad** [comment]
You can turn off `devtool` at all, it will not generate map for script files.
`devtool: flase`

**Comment by hihabib** [comment]
> You can turn off `devtool` at all, it will not generate map for script files. `devtool: flase`
yes, I tried this. This doesn't create map file and also stops generating bundle with the eval function. Thanks. but I don't know is it a good setting for preventing generating eval();

**Comment by hihabib** [comment]
> You can turn off `devtool` at all, it will not generate map for script files. `devtool: flase`

yes, I tried this. This doesn't create map file and also stops generating bundle with the eval function. Thanks. but I don't know is it a good setting for preventing generating eval();

**Comment by aidev42** [comment]
> You can turn off `devtool` at all, it will not generate map for script files. `devtool: flase`

Sadly, this doesn't work in NextJS - it literally ignores/overrides it to set it back on in the `dev` environment. Anyone find a solution to getting devtools off? Causing a nightmare for CSP for our secure app.

Maybe we simply can't use NextJS as out frontend?

**Comment by owlyowl** [comment]
Experiencing this in Vue 3 using webpack and magic comments.. as webpack require chunks in it uses eval which then throws a CSP error because we don't want to be using unsafe-eval.

I've been hunting around for 2 days trying to correct this:
![image](https://github.com/user-attachments/assets/e64371ec-0c0a-4309-903b-41bdeac8dda0)

I'd really love some insight. My webpack config modifications from the standard vue-cli are like so:
```
const { defineConfig } = require('@vue/cli-service');
const path = require('path');

module.exports = defineConfig({
    publicPath: process.env.ENTRY === 'serve' ? '' : `${process.env.SOME_ENV_VAR}/`,
    transpileDependencies: true,
    filenameHashing: false,
    css: {
        extract: process.env.ENTRY !== 'serve'
    },
    pages: {
        'referrals-app': {
            entry: 'src/main.ts',
            template: 'public/index.html',
            filename: 'index.html',
            chunks: ['xxx-api']
        }
    },
    configureWebpack: {
        mode: 'production',
        devtool: 'source-map',
        entry: {
            'referrals-api': './src/entry.xxxApi.ts'
        },
        optimization: {
            splitChunks: false
        },
        module: {
            rules: [{
                test: /\.scss$/,
                use: ['sass-loader', {
                    loader: 'style-resources-loader',
                    options: {
                        patterns: [
                            path.resolve(__dirname, './src/assets/styles/_variables.scss'),
                            path.resolve(__dirname, './src/assets/styles/_mixin.scss')
                        ]
                    }
                }]
            }]
        }
    }
});

```
