### ISSUE TITLE
Support --quiet on the command-line

### ISSUE THREAD

**Issue by mietek** [webpack/webpack#490]
Currently, `webpack --quiet` ignores the files passed, while still outputting to the console:

```
Hash: 6dbc5ab44333d067d673
Version: webpack 1.4.0-beta6
Time: 11ms
```

It would be nice to have the `--quiet` option work as expected, i.e. silence all non-error messages.

**Comment by jdalton** [comment]
:+1: It looks like there is no `--quiet` option anymore.

**Comment by romeovs** [comment]
will you guys merge this? I kind of need this.

**Comment by bebraw** [comment]
Merged. Closing.

**Comment by LegitTalon** [comment]
The PR looks closed not merged?

**Comment by bebraw** [comment]
Yeah, my mistake. Apologies.

**Comment by LegitTalon** [comment]
No worries. Will be super excited when it does get merged :smile:

**Comment by LegitTalon** [comment]
Please merge! :see_no_evil:

**Comment by bebraw** [comment]
@LegitTalon Looks like the original PR isn't going anywhere. Maybe a new one would be in order.

**Comment by bebraw** [comment]
Moved to https://github.com/webpack/webpack-cli/issues/22.
