### ISSUE TITLE
On Windows if directory contains "!" you get an Error: Can't resolve 'd:\' in 'd:\!\F#\tmp\webpack_bug'

### ISSUE THREAD

**Issue by maestrow** [webpack/webpack#4906]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
ERROR in Entry module not found: Error: Can't resolve 'd:\\' in 'd:\\!\F#\tmp\webpack_bug'

**If the current behavior is a bug, please provide the steps to reproduce.**

1. `mkdir !project` (it is important to include exclamation character in dir name)
2. `cd project`
3. Create an empty `a.js`
4. Create `package.json`:
```
{
  "scripts": {
    "a": "webpack a.js bundle-a.js"
  },
  "dependencies": {
    "webpack": "*"
  }
}
```
5.
```
npm i
npm run a
```

**What is the expected behavior?**
`npm run a` from above case executes with no error.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

- OS: Windows 10
- node v6.10.0
- npm v4.4.1
- webpack v2.5.1

**Comment by sokra** [comment]
yep, this is a limitation. Don't use `!` in folder names for webpack.

**Comment by simonl65** [comment]
Why does webpack have this limitation? It's a perfectly valid folder name (at least on Windows).
