### ISSUE TITLE
Add ability to create chunk per module basis

### ISSUE THREAD

**Issue by wintercounter** [webpack/webpack#4908]
**If this is a feature request, what is motivation or use case for changing the behavior?**

Currently I'm using the dynamic import syntax and WP does a great job. However, I'm facing one issue:
In case I have to use the same module multiple times, it'll be included in all chunks where that module is used. This is a pretty big overhead (to load the the same module multiple times). The current project I'm working on has ~ 190 modules which would result in an equal amount of chunks. In case using HTTP2, I don't think it's an issue to have them separated. In that case Webpack would always know which modules are loaded and which ones to skip.

I know there is the CommonChunksPlugin for such cases but I can't accept it as a solution. I want to prevent the page to load ANY unnecessary code.

**Comment by sokra** [comment]
See AggressiveSplittingPlugin with a low max size configuration. But keep in mind that requests are more expensive than bytes.

**Comment by wintercounter** [comment]
I've checked it already, but there is no way to ensure that it'll generate chunk per module.

**Comment by evilebottnawi** [comment]
You can archive this using https://webpack.js.org/plugins/split-chunks-plugin/, please read docs
