### ISSUE TITLE
Upgrade uglify to v3

### ISSUE THREAD

**Issue by lukeapage** [webpack/webpack#4910]
**Do you want to request a *feature* or report a *bug*?**

Feature

**If this is a feature request, what is motivation or use case for changing the behavior?**

Upgrade uglify to v3. Since it is a breaking change to options that are passed directly to uglify, it would be best done as part of a webpack breaking change, e.g. v3

**Comment by sokra** [comment]
Send a PR.

**Comment by bebraw** [comment]
Related: https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/32 .

Most likely it's better to fix the issue at the other repository and then make webpack point there.

**Comment by plantain-00** [comment]
`uglifyjs-webpack-plugin@1.0.1` released, it has a dependency of `uglify-es@3` rather than `uglify-js@2`
