### ISSUE TITLE
CSS sources in the build file when using postcss

### ISSUE THREAD

**Issue by olegstepura** [webpack/webpack#4911]
**Do you want to request a *feature* or report a *bug*?**

A bug.

**What is the current behavior?**

I use `postcss-loader` together with some other style loaders. If [I enable sourceMaps](https://github.com/olegstepura/postcss-loader-test/commit/11432921ddd9073118ccd161f5e1284a9def3e6a), sources are inside of build file. 

**If the current behavior is a bug, please provide the steps to reproduce.**

Here is the test repo: [olegstepura/postcss-loader-test](https://github.com/olegstepura/postcss-loader-test)
CSS sources are inside of build file. It should be in separate `.map` file
Issue [was reported](https://github.com/postcss/postcss-loader/issues/239) in `postcss-loader`, but it's developers insist it's a wepback issue

* I enable `sourceMap: true` for all loaders in a chain
* I run `npm run build` which triggers `webpack -p` with `process.env.NODE_ENV = 'production'`
* buld file has CSS sources!

**What is the expected behavior?**

CSS sources should be in `[build].js.map` file and no CSS sources in `[build].js`

**Comment by sokra** [comment]
`.js.map` can only store SourceMaps for JS.

**Comment by olegstepura** [comment]
Why? Should the build file contain CSS sources?

**Comment by robatwilliams** [comment]
This is css-loader behaviour. From the documentation of its `sourceMap` option:

> They are not enabled by default because they expose a runtime overhead and increase in bundle size (JS source maps do not).

**Comment by evilebottnawi** [comment]
Works as expected. Also you can use https://github.com/webpack-contrib/mini-css-extract-plugin to extract css in separate file with source maps.
