### ISSUE TITLE
CommonJS modules are served as ES6 modules when run with the TypeScript loader.

### ISSUE THREAD

**Issue by bmustiata** [webpack/webpack#4912]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Having a commonjs module `vue` and requiring as:

```
import * as Vue from 'vue'

Vue.config.productionTip = false
```

Will get the module as a ES6 module with a `default` property instead of its content. Thus `Vue.config` is now undefined, and the application will fail.

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/bmustiata/webpack-bug-report

Run: `npm run dev`

**What is the expected behavior?**

The module should be returned as a classic commonjs module.

**If this is a feature request, what is motivation or use case for changing the behavior?**

N/A

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

browsers: all
node: v6.9.5
webpack: 2.5.1
os: ubuntu 16.04

**Comment by sokra** [comment]
The correct way to import a CommonJS module with ESM is

``` js
import Vue from 'vue';
```

**Comment by bmustiata** [comment]
@sokra Thank you for the reply.

My understanding is that: `import Vue from 'vue';` is actually equivalent to `import { default as Vue }  from Vue` or `var Vue = require('vue')['default'];`. This change in semantic has breaking consequences, since what typescript does now is `var Vue = require('vue');`

I also don't understand where the ESM would come into play since the TypeScript module from the sample is a [commonjs module](https://github.com/bmustiata/webpack-bug-report/blob/master/tsconfig.json), and so is 'vue' in the node_modules. I would expect having a CommonJS module, requiring another CommonJS module to work as expected, without having to change the imports (?!).

Changing the import is also not really an option, because that translates to change also all the definition files, that are actually provided from upsteram 'vue', and this has severe breaking changes on other modules that use 'vue' (eg. vue-router).
