### ISSUE TITLE
latest public website build for webpack lost the css

### ISSUE THREAD

**Issue by jm3** [webpack/webpack#4915]
## Bug:

Production https://webpack.js.org/ site missing its CSS.

main injected CSS in the `<style>` element,
`https://webpack.js.org/b96d3eecd1add4af62f0.css` is 404 😢 

**What is the current behavior?**
main CSS is 404

**If the current behavior is a bug, please provide the steps to reproduce.**
clear cache, load in Chrome or Safari, etc.

**What is the expected behavior?**
CSS should load

**Comment by sokra** [comment]
@webpack-bot move to webpack/webpack.js.org
