### ISSUE TITLE
webpack 2.6.0 can't find variable: Promise on require async

### ISSUE THREAD

**Issue by rogeriochaves** [webpack/webpack#4916]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

Having ReferenceError: Can't find variable: Promise when using `require(['dep'], callback)`

**If the current behavior is a bug, please provide the steps to reproduce.**

So, I'm using karma to run tests on phantomjs with webpack, and phantomjs doesn't have native promises. So, this is why I have this in my webpack.config (also, for older browsers):

```javascript
...
new webpack.ProvidePlugin({
  Promise: 'es6-promise-promise'
}),
...
```

Then, on my code, I could do something like this, and everything worked fine until `webpack@2.5.1` (and under, in fact, since 1.x this worked fine):

```javascript
console.log('promise', Promise);
require(['left-pad'], function (leftpad) {
  // ...
});
```

But then, simply by upgrading to `webpack@2.6.0`, I get the `ReferenceError: Can't find variable: Promise` error now.

I believe this is because webpack uses promises to load the chunks, and somehow stopped replacing variables from ProvidePlugin on its own boilerplate.

**What is the expected behavior?**

Promises should work when defined on ProvidePlugin, even if it is webpack generated code, right?

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

macOS, but also happened on ubuntu. Node 6.9. Webpack 2.6.0

**Comment by dsizomin** [comment]
Experiencing same issue here.
In our case the error it's coming from manifest js: `ReferenceError: Can't find variable: Promise at http://127.0.0.1:42069/unit-manifest-6eed6c926e1a80d7a48c.js:40`.

**Comment by DorianGrey** [comment]
Hm... facing a similar issue (in IE 11) with possibly the same cause, even _without_ any asynchronous loading.

Seems that the generated `webpackBootstrap` (defines `webpackJsonp`) code includes a line like this:
```
var resolvedPromise = new Promise(function(resolve) { resolve(); });
```

This line was / is not present using webpack 2.5.x.

**Comment by davidhenning** [comment]
We just updated from 2.5.1 from 2.6.0 and have the same issue with PhantomJS (local on macOS and remotely with an Ubuntu-based docker container on the CI server).

**Comment by mlandalv** [comment]
Same problem. My Promise polyfill stopped working with 2.6.0. It worked again when I downgraded to 2.5.1.

```
new webpack.ProvidePlugin({
    fetch: 'imports-loader?this=>global!exports-loader?global.fetch!whatwg-fetch',
    Promise: 'core-js/es6/promise',
}),
```

**Comment by alqu** [comment]
Same problem here.

**Comment by cwallervand** [comment]
Yup, exact same issue here

**Comment by johansatge** [comment]
Hi,

same issue here (actually we don't have the same config than OP, but we see the `Promise is undefined` error).

Here is a diff between a broken and working chunk (_left/right_), if that helps:

![pasted image at 2017_05_23 16_08](https://cloud.githubusercontent.com/assets/5699295/26359504/f160fc9e-3fd5-11e7-937e-4d91213e0f96.png)

**Comment by alqu** [comment]
I think those changes only affect <=IE11 if `new Promise()` is executed _before_ the polyfill kicks in.

**Comment by kfeinUI** [comment]
Hit this regression as well in IE <= 11.

**Comment by SuperOleg39** [comment]
+1,  i use babel-polyfill, and it was fine yesterday.

**Comment by kfeinUI** [comment]
Looks to be introduced in 22e7d254ee27e68569ea9718632accc870f52002.

**Comment by HeberLZ** [comment]
Same issue

**Comment by johnnyreilly** [comment]
Also the same issue - ts-loader build now failing due to this 😭

**Comment by andrenarchy** [comment]
@sokra Will there be a bugfix release? It seems to have broken quite a lot of builds.

**Comment by johnnyreilly** [comment]
thanks!

**Comment by vansosnin** [comment]
Still have the problem on webpack 2.6.1. Someone else?

**Comment by m3kka** [comment]
Still erroring on:

```javascript
var resolvedPromise = new Promise(function(resolve) { resolve(); });
```

all IE <= 11 issue not present with `2.5.1`

**Comment by jmlopez-rod** [comment]
The 2.6.1 version seems to fix it. All calls to `Promise` are now done inside a function which gets called at a later time. The first thing I have on my entry file is `import 'core-js';` which provides the `Promise` polyfill.

**Comment by reda-alaoui** [comment]
Is it normal to be forced to add the Promise polyfill ourselves to make webpack work on IE 11?

**Comment by crucialfelix** [comment]
It was a mistake in 2.6.0 where a Promise was used in the bootstrap code that loads your app. So this was being called before any code (your app) that has babel or other polyfills applied to it. It was fixed with 2.6.1

**Comment by reda-alaoui** [comment]
I am currently using webpack 2.6.1. 
I still need a promise polyfill because `System.import` still leads to ES6 Promise creation.

**Comment by crucialfelix** [comment]
Then yes, you do need a polyfill.  See
https://webpack.js.org/guides/code-splitting-async/#promise-polyfill

**Comment by crucialfelix** [comment]
Actually what I do is have this in my html in the head:

window.Promise||document.write('<script src="
https://cdn.polyfill.io/v2/polyfill.min.js"><\/script>');

That polyfills everything for any browser that doesn't have Promise.
That includes all of these features: https://polyfill.io/v2/docs/features/
Even though babel has already transformed all of those to safe es5
production code.

So I don't have any polyfill in my app itself. I don't force every modern
browser to download that.
Only the old browsers have to pay the price of that extra fetch.

https://polyfill.io/v2/docs/

**Comment by kenberkeley** [comment]
I don't want to bother my original Webpack config, so here is a workaround:
```
<script>
window.Promise || document.write(
  '<script src="//cdn.jsdelivr.net/es6-promise/4.1.0/es6-promise.auto.min.js"><\/script>'
)
</script>
<script type="text/javascript" src="js/manifest.15a34c.js"></script><script type="text/javascript" src="js/vendor.ab046a.js"></script><script type="text/javascript" src="js/app.6fa5fc.js"></script>
```
