### ISSUE TITLE
The ---module-bind-pre command-line argument leads to "configuration.module has an unknown property 'preLoaders'" error

### ISSUE THREAD

**Issue by georgir** [webpack/webpack#4917]
The command-line argument --module-bind-pre generates an invalid configuration using the "preLoaders" key instead of "loaders" with "enforce":"pre".
[edit: and while at it, might as well change "loaders" to "rules"]

Likewise for post.

Tested on webpack 2.5.1, but from the code it seems to be the same in current version 2.6.0 as well.

**Comment by sokra** [comment]
Yep, that's wrong. Send a PR changing this to `module.rules` with ènforce: "pre"`

**Comment by georgir** [comment]
Sorry but I'm a bit stumped by the needed testcases for a PR

**Comment by sokra** [comment]
Take a look at the `test/binCases` folder for testcases for the CLI. You'll need a `test.opts` file with your arguments.
