### ISSUE TITLE
Uncaught Error: Cannot find module "."

### ISSUE THREAD

**Issue by shafaqkazmi** [webpack/webpack#4921]
**Do you want to request a *feature* or report a *bug*?** bug

**What is the current behavior?**
Below exception:

```
polyfills.js:1 Error: Cannot find module "."
    at webpackMissingModule (eval at 148 (http://localhost:9000/assets/app.js:1:576363), <anonymous>:8:65) [angular]
    at eval (eval at 148 (http://localhost:9000/assets/app.js:1:576363), <anonymous>:8:144) [angular]
    at Object.onInvoke (eval at <anonymous> (http://localhost:9000/assets/vendor.js:1:92060), <anonymous>:4334:37) [angular]
    at eval (eval at 142 (http://localhost:9000/assets/polyfills.js:1:6901), <anonymous>:758:57) [angular]
    at Object.onInvokeTask (eval at <anonymous> (http://localhost:9000/assets/vendor.js:1:92060), <anonymous>:4325:37) [angular]
    at drainMicroTaskQueue (eval at 142 (http://localhost:9000/assets/polyfills.js:1:6901), <anonymous>:591:35) [<root>]
    at <anonymous> [<root>]
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Configuration files are uploaded on Github gist https://gist.github.com/shafaqkazmi/abbf5b07a70e6d23463d2de7d42f2a53

**What is the expected behavior?**
Application should load all desired modules

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Version details:
```
@angular/cli: 1.0.3
node: 7.0.0
os: win32 x64
@angular/common: 4.1.2
@angular/compiler: 4.1.2
@angular/core: 4.1.2
@angular/forms: 4.1.2
@angular/http: 4.1.2
@angular/platform-browser: 4.1.2
@angular/platform-browser-dynamic: 4.1.2
@angular/router: 4.1.2
@angular/cli: 1.0.3
@angular/compiler-cli: 4.1.2
```

**Comment by sokra** [comment]
Check build for errors.

**Comment by nyrosmith** [comment]
Can you provide a minimal sample repo that shows that issue?

**Comment by danielzlotnik** [comment]
Happened to me as well, turns out it was because i was using require with an expression instead of a value:
```
var path = 'path/to/file.js' 
require(path) // Error: Cannot find module "."
require('path/to/file.js' ) // All good
```

**Comment by FallingSnow** [comment]
@danielzlotnik Same thing here.

**Comment by funcphp** [comment]
@danielzlotnik +1
Is there a solution?

**Comment by devnieL** [comment]
same problem here :(

**Comment by rodrigobacelli** [comment]
I'm having this issue, but with import() :(

**Comment by rawbin-** [comment]
![image](https://user-images.githubusercontent.com/8169783/38533974-34c97a94-3cae-11e8-82e6-6efa2b24955c.png)
same issue
![image](https://user-images.githubusercontent.com/8169783/38533985-41b9ab70-3cae-11e8-879e-7eb3ffa2d2af.png)

**Comment by rawbin-** [comment]
![image](https://user-images.githubusercontent.com/8169783/38534270-ec10495c-3caf-11e8-8bda-82f6bb63e4f4.png)
with webpack@2.6.1

**Comment by huchenme** [comment]
@rawbin- is `@/components/${relativePath}` inside your `node_modules`? I am trying to load a module from `node_modules` and it is not working

**Comment by rawbin-** [comment]
@huchenme  mine is custom component as the '@' is alias of 'src'  for vue project
I posted an issue again
https://github.com/webpack/webpack/issues/7003

**Comment by Kaidanov** [comment]
http://cabanalabs.com/2016/05/04/how-to-fix-webpack-when-it-cant-find-your-modules/

**Comment by jayzyaj** [comment]
I have the same issue using import in ionic. Any suggestions?

**Comment by killian2301** [comment]
I'm getting the same error with Ionic 3 also... @jayzyaj did you get to solve it?
Last time i had to start a new project again...

**Comment by Kaidanov** [comment]
In my case I've removed last pages I've generated and rolled back to previous version.. It worked. Something was messed up when generated the last page..

**Comment by killian2301** [comment]
@Kaidanov that worked for me too last time...only this time the problem didn't appear after generating a page, but renaming it...

**Comment by Kaidanov** [comment]
Rollback.. you at least have local git.. just set copy of what you have right now aside.. then rollback until it works.. Then compare folders and merge what is needed and run serve after each merge just to be sure it still works.

**Comment by killian2301** [comment]
I think i found a solution, at least for Ionic. I have no idea what's causing this, but it appears that i get the error when some imports add "/umd" at the end.
For instance:
`import { IonicApp, IonicModule, IonicErrorHandler } from 'ionic-angular/umd';`
i made a search in the whole project looking for "/umd" and deleted them:
`import { IonicApp, IonicModule, IonicErrorHandler } from 'ionic-angular';
`, and it worked!

I had two projects with the same problem, and i fixed both by doing this...
Again, i don't know if it's VS Code Insiders that's automaticly adding this or a plugin i have installed or something...

Are you all using VS Code?

**Comment by stevepopovich** [comment]
This is exactly what happened to me +1 @killian2301 

Not sure why this happening all of the sudden. Never had this issue until today.

**Comment by math-alexandre** [comment]
Thanks a lot @killian2301 ! I'm also using Ionic and got the same problem. Your tip helped me.

**Comment by toffebjorkskog** [comment]
Yep, Vs Code added `/umd` to import statement. It could be the auto import plugin.

**Comment by archcorsair** [comment]
Ran into the same issue (not using Ionic), unable to use template literals within the require after upgrading to Babel 7. We are currently using webpack 2.x and will be upgrading to 4 soon - I believe this has to do with new babel + older webpack not being friendly in my scenario.

Not Working
```js
config = require(`../inc/${process.env.targetNetwork}.config.json`);
```
Working
```js
config = require('../inc/' + process.env.targetNetwork + '.config.json');
```

This is the temporary fix I've applied that works for me. Hope this helps someone in the future 👍

**Comment by crabbydavis** [comment]
@killian2301 You're the man!! Wish I would've found your answer hours ago!

**Comment by killian2301** [comment]
i'm glad to hear that! :)

**Comment by mkashifwk** [comment]
killian2301, yes  'umd' was the issue, thanks bro

**Comment by ismetsezer** [comment]
@killian2301  perfect. Thank you. Code editor imported AlertController  path as  'ionic-angular/umd' and I deleted like you , it works

**Comment by asad02** [comment]
@killian2301 thanks for pointing out. That's the right answer for ionic project.

**Comment by sitepratico** [comment]
thanks @killian2301 that's the perfect solution, in my case the umd comes when use isUndefined function. ;o)

**Comment by darksapiensman** [comment]
thanks @killian2301 your solution work for me.

**Comment by dimalahbal** [comment]
how can i solve my problem ? can somebody help me

**Comment by darksapiensman** [comment]
I use the solution proposed by @killian2301.   In my case when I did a find/replace in vscode, the postfix /umd was automatically added to the import of the Ionic libraries:

`import {Events, Nav, Platform, Config } from 'ionic-angular/umd';`

I removed the / umd and with that the error was fixed:

`import { Events, Nav, Platform, Config } from 'ionic-angular';`

**Comment by vintots** [comment]
save my day @killian2301  
cheers!!!

**Comment by domske** [comment]
In my case it solved the problem by removing `/umd` from import pathes. 

**Search and replace all occurrences of `ionic-angular/umd` with `ionic-angular`.**

I don't know why is `/umd` set on the pathes. And I'm sure it also working with `/umd`. 
The problem comes suddenly. In my case I renamed a few files in my sources.
But rebuilt incl. clean. Usually it works. This error (cannot find module ".") is rare but persistent.

**Comment by pjc2007** [comment]
I had this problem with "umd" as well.

The other weird thing it seemed to do (if VSCode allows a reference to a renamed file) is change ALL (not just the renamed) import to remove the relative path prefixes..

eg if I had
`import { MyItem } from '../../models/my-item'; `

it changed it to

`import { MyItem } from 'models/my-item'; `

So it remove the `../../`

It still looked ok in VSCode editor, and compiled ok,. but I would get the runtime error until I added back this relative prefix. I need to investigate this.

**Comment by VerSo930** [comment]
Thanks guys!! For me also was a VScode issue.
Replacing '/umd' on entire project did the trick.

**Comment by rihlsul** [comment]
Sounds like it's coming from this:  https://github.com/Microsoft/TypeScript/issues/25204

However, when I did replace all on my project to remove all /umd instances, my UI is now borked.  Completely unstyled.  Will report back if I can figure out what the heck I did.

**Comment by domske** [comment]
@rihlsul Just recompile / restart the app and the styles comes back. I had the same problem. After removing all umd from imports, the html of my app (ionic) was naked. But a rebuild fixed this issue.

**Comment by rihlsul** [comment]
Confirmed that did resolve it.  Bizarro.  Thanks!

**Comment by SebastianJordan** [comment]
@killian2301  thanks I did what you wrote with vs and it worked.

**Comment by k1dbl4ck** [comment]
Happened to me. I copied a page for a slightly different use case and accidentally set VSCode to update dependencies. The shitshow that ensued was 149 changed files - a lot of which had /umd tacked on to some imports. 

Checking my settings I noticed : 

` "typescript.updateImportsOnFileMove.enabled": "always" `

And removed it. Problem solved.

**Comment by jorsaldo** [comment]
@killian2301 it works for me. After hours looking for the problem, I solved it remoming all "/umd" statements from all imports that was added when I created a new Page.

**Comment by gotters** [comment]
Have the same issue (ionic 3). Found all the /umd/s and removed them. Restarted with ionic serve, even tried an ionic build but am still getting the same issue.

Anyone help??

**Comment by Kuldeep-Kumar** [comment]
hey @killian2301  what is this /umd

**Comment by killian2301** [comment]
@Kuldeep-Kumar Sorry, i have no idea what it is. I just know it's vscode who is messing things up...

**Comment by Kuldeep-Kumar** [comment]
Okay!Thanks👍
@killian2301 it solved my issue anyway 😅

**Comment by saryuvc** [comment]
Decreasing the version to ~2.6.2 fixed it.

**Comment by RafaelKr** [comment]
`npm i -D typescript@2.8.3` fixed it for me.

**Comment by cpamp** [comment]
In addition to the `/umd` added to some imports, some `@types/` were also removed from imports which caused the same error.

I think it was all due to renaming in VSCode, so try to avoid that if you can.

**Comment by poohia** [comment]
> 
> 
> `npm i -D typescript@2.8.3` fixed it for me.

Me to !! Thank's really 😂

**Comment by JuliaRakitina** [comment]
> `npm i -D typescript@2.8.3` fixed it for me.

+1 that worked for me

**Comment by mynameissujie** [comment]
don't use . 
 help it works、

**Comment by hugomejia** [comment]
This Solution by @padurets actually solved the issue for me (I'm working on a Vue-Cli 3 project), and I'm getting the path from the Store (Vuex) within a Computed function in my component.
> ```js
> require(`${path_to_file}`);
> ```

Thanks a lot @padurets !

**Comment by gangupraveen** [comment]
sometimes in the import ionic-angular is changed as 'ionic-angular/umd'. just remove /umd it should be ok

**Comment by Gautammer** [comment]
**Thanks @pjc2007  you saved my day ...**

**Comment by itlpps** [comment]
I can’t downgrade typescript;
> Error: The Angular Compiler requires TypeScript >=3.4.0 and <3.6.0 but 2.8.3 was found instead.

And, I find "umd" in all solutions but no results.

Any solution?

**Comment by killian2301** [comment]
> I can’t downgrade typescript;
> 
> > Error: The Angular Compiler requires TypeScript >=3.4.0 and <3.6.0 but 2.8.3 was found instead.
> 
> And, I find "umd" in all solutions but no results.
> 
> Any solution?

Are you using Ionic 3? if so, you have to downgrade if you want to get rid of the error. Try to downgrade to 2.6.2 and change your package json to version 6 of rxjs. 

In package.json:

This:
  "rxjs": "6.0.0",
  "rxjs-compat": "6.0.0"
  
Not this:
  "rxjs": "^6.0.0",
  "rxjs-compat": "^6.0.0",
