### ISSUE TITLE
Scope-hoisting: importing two modules that has functions with the same names that are used in objects with property-shorthand fails

### ISSUE THREAD

**Issue by daviderenger** [webpack/webpack#4925]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

Testing the next branch with scope-hoisting.
Importing two modules that has functions with the same names that are used in objects with property-shorthand fails, action is undefined .

**If the current behavior is a bug, please provide the steps to reproduce.**

```
/* Module 1 */
function action() {
  console.log("in module 1");
}

export default {
  action
}

/* Module 2 */
function action() {
  console.log("in module 2");
}

export default {
  action
}

/* Root */
import module1 from './module1';
import module2 from './module2';

module1.action();
module2.action();
```

It is working if I instead exports without shorthand properties:
export default {
  action: action
}

**What is the expected behavior?**

action is defined on both module1 and module2.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Webpack next branch

**Comment by sokra** [comment]
fixed by #4969
