### ISSUE TITLE
UglifyJS: `warningsFilter` does not take effect if `sourceMap` option is false

### ISSUE THREAD

**Issue by christopherthielen** [webpack/webpack#4929]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

`options.warningsFilter` for the UglifyJS plugin only takes effect if `options.sourceMap` is truthy.

**If the current behavior is a bug, please provide the steps to reproduce.**

Add a `warningsFilter` that silences warnings, but set `sourceMap` to `false`.

https://gist.github.com/christopherthielen/5b317e5ef8910ade34694786bf13f703

**What is the expected behavior?**

It seems like `warningsFilter` should take effect regardless of the `sourceMap` option. 

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

└─┬ webpack@2.6.0

**Comment by christopherthielen** [comment]
The [code that uses `warningsFilter`](https://github.com/webpack/webpack/blob/0dd0830478e5f5dd0e36930092e5ce6b6e6d3f39/lib/optimize/UglifyJsPlugin.js#L71) is only applied inside the block starting with:
```js
if(options.sourceMap) {
...
}
```

**Comment by sokra** [comment]
Send a PR

**Comment by ismail-syed** [comment]
Was able to reproduce with `webpack@3.5.3`. 
Gonna take a stab at fixing this.

**Comment by ismail-syed** [comment]
I noticed the current version of webpack is using `v0.4.6` of `uglifyjs-webpack-plugin` but the latest master is on `v1.0.0-beta.2`. 

I presume `v1.0.0` of `uglifyjs-webpack-plugin` has some break changes so it might be difficult to fix this without context around the breaking changes associated with `v1.0.0-beta.2` and how to set it up with local dev copy of webpack.  
Any suggestions?

**Comment by evilebottnawi** [comment]
@webpack-bot move to webpack-contrib/uglifyjs-webpack-plugin
