### ISSUE TITLE
I want dynamic add my js file from a url，while the js file is only for a Specific WebPage，don't used by the other WebPage;  require.js can do it; how webpack to realize it？？？

### ISSUE THREAD

**Issue by zhouweihua** [webpack/webpack#4933]
a file it have been in the web such as “http//www.xxx.com/fdsa/ewre/fds/fff.js”;
when i visit the “www.xxx.com” home page，it doesn't need this “fff.js”
but when  visit the “www.xxx.com/ccc/ddd”; it need this “fff.js”;

how to get it dynamic

**Comment by sokra** [comment]
Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md).
