### ISSUE TITLE
webpack.config entry to html js order is err

### ISSUE THREAD

**Issue by zanjs** [webpack/webpack#4934]
"webpack": "2.5.1",

##  webpack.config.prod.js

```js
entry: {
    vendor: ["react", "react-dom", "react-router-dom"],
    app: paths.appIndexJs,
 },
```

to html

```html
<body><noscript>You need to enable JavaScript to run this app.</noscript>
  <div id="root"></div>
  <script type="text/javascript" src="/static/js/app.bb3b8154.js"></script>
  <script type="text/javascript" src="/static/js/vendor.4be80acf.js"></script>
</body>
```

Order error
![gc](https://cloud.githubusercontent.com/assets/12947276/26489816/7a74529e-423b-11e7-949e-10e671939481.gif)

**Comment by Axnyff** [comment]
It's not really practical to have to watch a gif to see what your problem is...
Anyway, according to the [html webpack plugin doc](https://github.com/jantimon/html-webpack-plugin#configuration), it looks like you can pass a function to actually sort your chunks, did you try that?
