### ISSUE TITLE
DllPlugin: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.

### ISSUE THREAD

**Issue by KulakovSerg** [webpack/webpack#4935]
**bug**

**What is the current behavior?**
Stdout:
```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.output has an unknown property 'chunkLoadTimeout'. These properties are valid:
   object { auxiliaryComment?, chunkFilename?, crossOriginLoading?, devtoolFallbackModuleFilenameTemplate?, devtoolLineToLine?, devtoolModuleFilenameTemplate?, filename?, hashDigest?, hashDigestLength?, hashFunction?, hotUpdateChunkFilename?, hotUpdateFunction?, hotUpdateMainFilename?, jsonpFunction?, library?, libraryTarget?, path?, pathinfo?, publicPath?, sourceMapFilename?, sourcePrefix?, strictModuleExceptionHandling?, umdNamedDefine? }
   Options affecting the output of the compilation. `output` options tell webpack how to write the compiled files to disk.
```

I have inserted code from example:
```
new webpack.DllPlugin({
    path: path.join(__dirname, '[name]-manifest.json'),
    name: '[name]_[hash]',
}),
```

Without plugin config is OK.
There is not any "chunkLoadTimeout" in config - plugin adds it.
DllPlugin is not supported for latest webpack yet?
I use merge.smart()

**If the current behavior is a bug, please provide the steps to reproduce.**
get any working config => add plugin => get problem

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
webpack@2.6.1
npm -v 3.10.10
node -v 6.10.3
Ubuntu 15.10

**Comment by bebraw** [comment]
Can you paste the `output` section of your configuration? Why are you using `output.chunkLoadTimeout`?

**Comment by KulakovSerg** [comment]
```
const publicFolder = process.argv.indexOf('--is_debug') === -1 ? 'public' : 'public_test';
...
output: {
        path: path.resolve(__dirname, `../${publicFolder}/js`),
        publicPath: `/${publicFolder}/js/`,
        filename: 'entry.[name].js',
        chunkFilename: 'chunk.[name].[id].js',
    },
```

Of course I haven't use `chunkLoadTimeout` and everything worked fine, but after plugin is plugged there is error about that field...

**Comment by KulakovSerg** [comment]
@bebraw sorry for offtopic, could you please read about my other problem with webpack?
https://stackoverflow.com/questions/44261208/webpack-module-resolution-depends-on-entry-or-chunk-name

**Comment by KulakovSerg** [comment]
Sorry, this issue was caused by config directory different with context directory...
