### ISSUE TITLE
ERROR in multi main Module not found: Error: Cannot resolve 'file' or 'directory'

### ISSUE THREAD

**Issue by apurvgandhwani** [webpack/webpack#4938]
I am getting this weird error suddenly in my react application. 

```
ERROR in multi main
Module not found: Error: Cannot resolve 'file' or 'directory' /home/apurv/Downloads/Frontend-Master-master/src/client/apurv.js in /home/apurv/Downloads/Frontend-Master-master
 @ multi main

```

I have deleted the apurv.js file. Then too it is showing this error.  I didn't touch webpack file. I didn't make any changes. One of the directories was having index.js file. I renamed it apurv.js. And made anotther index.js file in the same directory.

**Comment by sokra** [comment]
Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md).
