### ISSUE TITLE
Circular dependency creates invalid syntax

### ISSUE THREAD

**Issue by SimenB** [webpack/webpack#4940]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Instead of throwing a useful error on circular dep, a warning is printed during build, and invalid javascript is created.

**If the current behavior is a bug, please provide the steps to reproduce.**
See https://github.com/SimenB/webpack-circular-invalid

Error is:
```
/Users/simen/Development/webpack-circular/bundle.js:39943
  var Parser = new !(function webpackMissingModule() { var e = new Error("Cannot find module \".\""); e.code = 'MODULE_NOT_FOUND'; throw e; }())('../parser')
                   ^
SyntaxError: Unexpected token !
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)
```

Warnings during build, unsure if relevant:

```
WARNING in ./~/stylus/lib/utils.js
132:15-48 Critical dependency: the request of a dependency is an expression

WARNING in ./~/stylus/lib/functions/selector.js
60:19-26 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/stylus/lib/functions/use.js
29:11-39 Critical dependency: the request of a dependency is an expression

WARNING in ./~/source-map/lib/source-map/source-map-generator.js
8:45-52 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/source-map/lib/source-map/source-map-consumer.js
8:45-52 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./~/source-map/lib/source-map/source-node.js
8:45-52 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
```

**What is the expected behavior?**
It should work, like in Node. Barring that, it should produce a useful runtime error, not make the interpreter throw on invalid syntax.

**If this is a feature request, what is motivation or use case for changing the behavior?**
N/A

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Node@7.10, webpack@2.6.1

**Comment by SimenB** [comment]
I added a browserify build to the repro, and it successfully builds a bundle

**Comment by rrharvey** [comment]
It looks to me like the issue  is in one of the files from the _stylus_ project that is included with your sample code. There's a spot in their code that is calling **require** as a constructor like this.

    var Parser = new require('../parser')

That statement is getting parsed as a require context dependency just like this code would.

    require("./template/" + name + ".ejs");

The code that's actually throwing the error is intended to generate a runtime error but since it's to the right of the _new_ operator it's a syntax error and can't be parsed.

This [gist](https://gist.github.com/rrharvey/cd53bae9dcf1e15b7ca58f744a6f5876) reproduces the issue.

**Comment by melitus** [comment]
The project looks for handblebar-loader at the webpack configuration file but couldn't find it . This can be solved by installing ```handlebars-loader```. After the installation, everything should work fine. This works for me
