### ISSUE TITLE
[WASM] - Implementation and first uses complete - User Surface

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack#4945]
This depends on: 
- [x] #4944 
- [x] #4943 
- [x] #4942 
- [x] #4941 

WASM User Surface: 

**entry.js**
```javascript
import(“./abc.js”).then(abc => abc.doIt());
```

**abc.js**
```javascript
import module from “./addition.wasm”;

export function doIt() {
  console.log(module.add(1, 2));
}
```

**addition.wasm**
```wasm
Some binary code for the following wast
(module
  (export "add" 0)
  (func (param i32) (param i32) (result i32)
    (i32.add (get_local 0) (get_local 1))
  )
)
```

**Comment by baptistemanson** [comment]
Hi,

How can I know that I have to import() a module instead of "import ... from"? Do I have to know that my module may use webassembly under the hood?

**Comment by sokra** [comment]
> How can I know that I have to import() a module instead of "import ... from"? Do I have to know that my module may use webassembly under the hood?

Yes, but webpack will also yell at your if you are doing it wrong.

**Comment by sokra** [comment]
done
