### ISSUE TITLE
[WASM] - Implement parallel WASM compilation

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack#4946]
This will replace the initial sequential runtime compilation work for initial WASM bundling from first milestone. 

Rather, we will implement parallel WASM compilation for its final product.

**Comment by wmertens** [comment]
Note that if you use input hashes as I describe at https://medium.com/@wmertens/this-is-excellent-news-bea2da51c9c3, you get automatic splitting in lazy-able parallel chunks (just follow the graph).

**Comment by sokra** [comment]
done
