### ISSUE TITLE
[WASM] - It is possible to import function from other modules from WASM

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack#4949]
Given existing module webpack should be able to understand analyze and import dependencies of WASM modules. Must follow the same resolving rules for modules.

somemodule.wasm (given in .wast format)
```wast
(module
 (import “./math” “random” (func rand (result f32))
 (func
  (export "addRandom")
  (param i32)
  (result i32)
  (i32.add (get_local 0) (call rand))
 )
)
```

**Comment by sokra** [comment]
done
