### ISSUE TITLE
Babel Transform Runtime doesn't seem to work with Webpack

### ISSUE THREAD

**Issue by Apidcloud** [webpack/webpack#4961]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
When using webpack and babel's transform-runtime, I'm unable to use `exports *`.

**If the current behavior is a bug, please provide the steps to reproduce.**
~~Babel's transform runtime plugin doesn't seem to be running, since the class `Symbol` isn't transformed at all.~~ Babel was not running at all before because `include `property as invalid.

Now the problem is with the `exports` - related to #3917

Consider a simple **input file**, the **only entry** (index.js):
`export * from './secondFile'`

**secondFile.js**
```
export let TESTSYMBOL = Symbol('test');

export let TESTSYMBOL2 = Symbol('test2');

```

**webpack.config.js** (only copied the relevant part):
```javascript
module: {
        rules: [
            {
                test: /\.jsx?$/,
                // Skip any files outside of `src` directory
                include: /src/,
                use: {
                    loader: 'babel-loader',
                    options: {
                        presets: ["es2015", "stage-3"],
                        plugins: ['transform-runtime']
                    }
                }
            }
        ]
    }
```

**script**:
`"webpack -d --config config/webpack.config.js"`

**output**: [gist](https://gist.github.com/Apidcloud/2b0e6009c4f6f15b272a6dbf1739c6bc)

**Exception**:
`Uncaught ReferenceError: exports is not defined - at Object.defineProperty(exports, "__esModule", {`

**What is the expected behavior?**

Exports should work, as **they do without transform-runtime plugin**.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
**Node**: v6.10.3

**Dev dependencies**:
"webpack": "2.6.1",
"webpack-dev-server": "2.4.5",
"webpack-notifier": "1.5.0"
"babel-cli": "6.24.1",
"babel-loader": "7.0.0",
"babel-plugin-transform-runtime": "6.23.0",
"babel-preset-es2015": "6.24.1",
"babel-preset-stage-3": "6.24.1"

**Dependencies**:
"babel-runtime": "6.23.0"

Am I missing something?

Thanks for any help!

**Comment by Apidcloud** [comment]
Nevermind. There's a mistake in the configuration. I thought it was possible to use path.resolve or path.join in include and exclude properties.

The following works just fine (part of webpack.config.js):
```javascript
 module: {
    rules: [
        {
            test: /\.js$/,
            include: [
                /src/
            ],
            // or exclude: [/node_modules/],
            use: 
                {
                    loader: 'babel-loader',
                    options: {
                        plugins: ['transform-runtime'],
                        presets: ['es2015', 'stage-3']

                    }
                }

        }
    ]
}```

I'm so sorry for opening a issue reporting a bug, when it was my mistake! Please close it.

**Comment by Vanuan** [comment]
Try setting modules to false:

                                                        presets: [['es2015', { modules: false }], 'stage-3'],

**Comment by Vanuan** [comment]
AFAIK, webpack doesn't have anything to do with ES modules if you don't set modules to false in babel configuration.

**Comment by Apidcloud** [comment]
That solves it, but it also tree shakes right? Removing dead code.

Not sure I should do that, as I want to use this in a library

**Comment by Vanuan** [comment]
AFAIK, tree shaking can't work if you import a module which uses `export *`;

Import is a side effect causing operation. So if you import some module its body must be executed. If that body contains import that one should also be executed and so on. So it's guaranteed that if you import a module which have "export *" you'll have more code than if you use a specific module import.

**Comment by Vanuan** [comment]
Some tools (babili) are better at removing dead code than others (uglify) but I don't see why it's called "tree shaking".

**Comment by Apidcloud** [comment]
Are you saying it's better to always use specific imports?

**Comment by Vanuan** [comment]
For the purpose of dead code elimination, yes. There are some techniques which automatically transform your imports to the specific ones. E.g. https://www.npmjs.com/package/babel-plugin-transform-imports
But since there is no standard naming technique it must be applied on a case by case basis.

**Comment by Vanuan** [comment]
Another alternative would be to try aggressive minification settings, but that way you'll lose an ability to debug your code (source maps will be completely broken).

**Comment by Apidcloud** [comment]
I like the idea of using transform-inputs. I'll take a deeper look at it. Thanks again!

**Comment by sokra** [comment]
`transform-runtime` emits ESM even if babel should transpile ESM to CJS. I guess plugin an preset are in incorrect order. `modules: false` should fix it.

---

Tree Shaking also works with `export *`.

**Comment by Apidcloud** [comment]
I have noticed that this solution doesn't seem to work with **webpack-dev-server**.
The following error is raised:
`Cannot assign to read only property 'exports' of object`

I created a minimal repository to reproduce the problem:
https://github.com/Apidcloud/webpack-babel/

It seems to work with**http-server** though.

Can someone take a look at the repository?

Thanks!

**Comment by Apidcloud** [comment]
Alright...

I was able to fix the issues I mentioned in my previous comment by **excluding** **node_modules** from webpack modules rules. I thought including a folder would basically result in the same thing, but it seems not!

You can check a simple boilerplate at the following repository:
https://github.com/Apidcloud/webpack-babel

It uses Webpack and Babel `transform-runtime`.

**Comment by diachedelic** [comment]
I avoided the `Cannot assign to read only property 'exports' of object` error (when referencing anything babel-runtime intecepts, like `Object.keys`), but removing the `modules: false` in my `.babelrc`

**Comment by Venryx** [comment]
Here is another possible solution (it's what worked for me): https://github.com/webpack/webpack/issues/3974#issuecomment-369260590
