### ISSUE TITLE
webpack 2.6.1 Config did not export an object or a function returning an object.

### ISSUE THREAD

**Issue by nomadus** [webpack/webpack#4964]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
I am following the documentation and split webpack configuration into files https://webpack.js.org/guides/production-build/#advanced-approach
when I run npm run build:dist it returns 
Config did not export an object or a function returning an object.
But if I just define a local variable (var common= whatever in webpack.common.js file), it works OK.
I am on windows 10.
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Node version is 7.5.0
OS Windows 10
webpack 2.6.1

**Comment by Axnyff** [comment]
Can you post your config? I'm having troubles understanding what is your actual problem...

**Comment by nomadus** [comment]
I have simplified config, here it is now
webpack.config.js:
module.exports = function () {
    return require('./webpack.prod.js')
}

webpack.prod.js:
const Merge = require('webpack-merge');
const CommonConfig = require('./webpack.common.js');

module.exports = function(env) {
  return Merge(CommonConfig, {
    plugins: [
      new webpack.LoaderOptionsPlugin({
        minimize: true,
        debug: false
      }),
      new webpack.DefinePlugin({
        'process.env': {
          'NODE_ENV': JSON.stringify('production')
        }
      }),
      new webpack.optimize.UglifyJsPlugin({
        beautify: false,
        mangle: {
          screw_ie8: true,
          keep_fnames: true
        },
        compress: {
          screw_ie8: true
        },
        comments: false
      })
    ]
  })
};

webpack.common.js:
var path = require('path');

module.exports = {
    entry: './src/index.js',
    output: {
        path: path.join(__dirname, '/public'),
        publicPath: path.join(__dirname, '/public'),
        filename: 'bundle.js'
    },
    resolve: {
        modules: ['node_modules'],
        extensions: ['.js', '.jsx', '.json'],
        alias: {
            images: path.join(__dirname, '/public/images')
        }
    },

    module: {
        rules: [{
            test: /\.js|.jsx/,
            exclude: /node_modules/,
            query: {
                presets: ['react', 'es2015', 'stage-0']
            },
            loader: 'babel-loader'
        },
        {
            test: /\.css$/,
            use: ['css-loader']
        },
        {
            test: /\.(woff|woff2|eot|ttf|svg|png)$/,
            use: {
                loader: 'url-loader',
                options: {
                    limit: 100000
                }
            }
        }
        ]
    },
    devtool: 'cheap-module-eval-source-map'
};

In the Windows 10 env, when I run webpack it throws 
Config did not export an object or a function returning an object.

**Comment by bebraw** [comment]
`return require('./webpack.prod.js')` returns a function. You have to invoke it to get configuration so change it to `module.exports = require('./webpack.prod.js')` and drop the surrounding function or tweak some other way.

It would be good if webpack would print out the received type.

**Comment by nomadus** [comment]
Thanks for the answer, here are the changes, which made it work.
webpack.config.js:
module.exports = require('./webpack.prod.js');
webpack.prod.js:
const Merge = require('webpack-merge');
const webpack = require('webpack');
const CommonConfig = require('./webpack.common.js');

module.exports = Merge(CommonConfig, {
    plugins: [
      new webpack.LoaderOptionsPlugin({
        minimize: true,
        debug: false
      }),
      new webpack.DefinePlugin({
        'process.env': {
          'NODE_ENV': JSON.stringify('production')
        }
      }),
      new webpack.optimize.UglifyJsPlugin({
        beautify: false,
        mangle: {
          screw_ie8: true,
          keep_fnames: true
        },
        compress: {
          screw_ie8: true
        },
        comments: false
      })
    ]
  })
webpack.common.js:
var path = require('path');

module.exports = {
    entry: './src/index.js',
    output: {
        path: path.join(__dirname, '/public'),
        publicPath: path.join(__dirname, '/public'),
        filename: 'bundle.js'
    },
    resolve: {
        modules: ['node_modules'],
        extensions: ['.js', '.jsx', '.json'],
        alias: {
            images: path.join(__dirname, '/public/images')
        }
    },

    module: {
        rules: [{
            test: /\.js|.jsx/,
            exclude: /node_modules/,
            query: {
                presets: ['react', 'es2015', 'stage-0']
            },
            loader: 'babel-loader'
        },
        {
            test: /\.css$/,
            use: ['css-loader']
        },
        {
            test: /\.(woff|woff2|eot|ttf|svg|png)$/,
            use: {
                loader: 'url-loader',
                options: {
                    limit: 100000
                }
            }
        }
        ]
    },
    devtool: 'cheap-module-eval-source-map'
};

closing the issue.
