### ISSUE TITLE
How to unpack/extract a bundle.js to it's component and js files.

### ISSUE THREAD

**Issue by johibkhan2** [webpack/webpack#4966]
Hi,

Could you please help on unpacking the bundle.js files to it's component and js files?

Regards,
Johib

**Comment by sokra** [comment]
Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md).

**Comment by johibkhan2** [comment]
here we go

https://stackoverflow.com/questions/44276097/webpack-how-to-extract-bundle-to-respective-components
