### ISSUE TITLE
Feature request: concatenate small modules into a single module

### ISSUE THREAD

**Issue by rosenfeld** [webpack/webpack#4973]
**Do you want to request a *feature* or report a *bug*?**: Feature request
**What is the current behavior?**: each file is a separate module
**What is the expected behavior?**: group specified files in a single module
**What is motivation or use case for changing the behavior?**

Our application has tons of modules and many of them are pretty small ones, so that it's easier for us to understand and test them in isolation. We moved our client-side code base from the Rails Assets Pipeline (Sprockets) to webpack a few years ago as we were interested in lazy loading, source-maps and some other features provided by webpack, and it was a very good choice. However I feel webpack added quite some overhead and I think it could be improved.

Sorry, but I need to explain how Sprockets works, so that you better understand my proposal. Sprockets read some special comments in the beggining of the sources and concatenate required files that haven't been concatenated yet. In our specific case, we use CoffeeScript and it would wrap those codes in anonymous functions, so any declared variables would be contained in this anonymous function. The way we handled `export` is by using a small `namespace` function like this:

```coffeescript
namespace 'app.main', (exports) -> exports.Application = class Application
   constructor: -> # code goes here

# from other source file
# = require app/main/application
app = new app.main.Application()
```

When we converted to webpack, naturally, most of those requires were converted to something like

```coffeescript
# = require app/main/search
# was converted to:
require 'app/main/search.coffee'
# instead of something like:
# search = require 'app/main/search.coffee'
```

So, in most of our sources we are not really using `exports`, but basically organizing the modules in namespaces and exporting a single variable to the global context, such as `app` (it's our application name actually). While I can see how well commonjs regular usage would work, I don't see any major problems with that approach we have been using since we used Sprockets to bundle our assets. It's still well organized.

However, with that approach, it opens the possibility of better optimizing for small modules than what currently Webpack supports only. Webpack adds an overhead to every single required module, which can become quite noticeable when bundling thousands of small modules. We have lots of them which fit in under 1KB for example.

So, there are lots of ways I think this could be improved in webpack through some plugins, although I have no idea on how to implement them. But here's some idea on how I'd like to use them.

**First idea (simpler to setup)**

The simplest way to achieve that would be to tell in webpack.config.js that we want to concatenate `m1.js`, `m2.js`, `m3.js` (and many more, maybe based on some regular expression or paths) as a single module called `common-base.js`. We should also specify the behavior when those modules require values are assigned to some variables. Maybe we'd like to throw an exception in such cases or to treat them as regular commonjs modules.

Here is how I'd expect it to behave:

```javascript
require('m1.js'); // would be converted to require('common-base.js')
// these would be ignored since they are already part of 'common-base.js'
// which have already been included
require('m2.js');
require('m3.js');

var m4 = require('m4.js'); // how about this one?
// depending on the setting it should either:
// - throw an exception
// - consider it as a regular commonjs module
```

**Explicit approach**

Another approach could be something like:

```javascript
require('concat?name=common-base!m1.js')
require('concat?name=common-base!m2.js')
require('concat?name=common-base!m3.js')
var m4 = require('m4.js')
```

I believe this would allow us to save several KB in our main bundles and reduce drastically the performance overhead of loading the bundle by reducing the amount of `webpack_require` calls drastically once we concatenate most of our modules. Do you think this would be a good addition to webpack?

**Comment by sokra** [comment]
> but basically organizing the modules in namespaces and exporting a single variable to the global context

hmm...

---

The next major version will support "Scope Hoisting" for EcmaScript Modules, but not for CommonJs modules.

I don't think it make sense to support it for special commonjs modules without exports but globals. This is a bad practice anyway. Refactor to ESM if you want Scope Hoisting.

**Comment by rosenfeld** [comment]
Hmm, I just searched about it and found what it means here:

https://webpack.js.org/vote/

Yeah, that would be fantastic, thanks :)
