### ISSUE TITLE
bug: externals can produce invalid generated .js

### ISSUE THREAD

**Issue by bbottema** [webpack/webpack#4974]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When including a complex external, the generated javascript isn't valid anymore and produces errors (and webpack's own UglifyJsPlugin crashes).

Here's the configuration I've used (full config [here](https://github.com/better-js-logging/angular2-logger/blob/master/webpack.config.js)):
```javascript
    externals: {
        'moment': 'moment',
        '@angular/core': '@angular/core'
    }
// or externals: ['moment', '@angular/core']
```
Moment works just find but for angular, the following javascript results from a build:

```javascript
module.exports = @angular/core;
```

- webpack 2.6.1
- node 6.10.2
- npm 4.6.1

I have a simple repo with the issue here: https://github.com/better-js-logging/angular2-logger

1. npm install
2. npm run build

**Comment by bbottema** [comment]
I also creates a [SO question](https://stackoverflow.com/questions/44292902/webpack2-externals-for-angular2) to verify if I'm understanding the `externals` concept correctly.

**Comment by sokra** [comment]
Looks like you expecting a `require("@angular/core")`.

You have to specify either `output.libraryTarget: "commonjs2"` 
or `externals: { '@angular/core': 'commonjs @angular/core' }`

**Comment by bbottema** [comment]
Isn't it bad to make assumptions about my user's choice of module system?
