### ISSUE TITLE
Support disabling NodeSourcePlugin for web target

### ISSUE THREAD

**Issue by jchip** [webpack/webpack#4976]
**Do you want to request a *feature* or report a *bug*?**

request a feature

**What is the current behavior?**

The default target `web` automatically apply the internal `NodeSourcePlugin`

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

I just found out that due to some other module we use that has something like this:

```js
var Crypto = canUseDom ? null : require("crypto");
```

This cause the internal `NodeSourcePlugin` to include a few very large files like `asn1.js` and `bn.js`.

To make things like this surface ASAP, I'd like to be able to disable the `NodeSourcePlugin` completely.

First thing I tried was to set target as a function to do custom target, but the internal plugin `FunctionModulePlugin` is not exported.  I could directly require that, but not ideal.

It'd be nice if webpack can provide a new target that's basically `web` without the `NodeSourcePlugin`.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by sokra** [comment]
It's supported. See `node` option

**Comment by jchip** [comment]
In that case, I think the plugin should honor the single kill switch.

I could not get this https://github.com/webpack/webpack/blob/master/lib/node/NodeSourcePlugin.js#L40 to trigger even if I set `config.node.node` to false.

This is looking at each lib https://github.com/webpack/webpack/blob/master/lib/node/NodeSourcePlugin.js#L74

**Comment by jchip** [comment]
would you like me to open a new issue for the plugin?  I am happy to make the changes if we can come to an approach.

**Comment by jchip** [comment]
@sokra would something like this work https://github.com/jchip/webpack/commit/20207220053551c4fe72d1f06716128b768e7eae?
