### ISSUE TITLE
Show more accurate validation information for initial configuration

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack#4977]
**Do you want to request a *feature* or report a *bug*?**

Feature.

**What is the current behavior?**

If you export something else than a function, array, or object from configuration, you'll get

```
Config did not export an object or a function returning an object.
```

> Note that the message doesn't mention that an array is valid! An array of objects is fine. An empty array fails with a cryptic `TypeError: Cannot read property 'context' of undefined` at  `outputOptions.context = firstOptions.context;`.

**What is the expected behavior?**

The validation should probably do a stricter type check and tell what the user passed. There was an issue where the user was passing a function without realizing it.

**If this is a feature request, what is motivation or use case for changing the behavior?**

Better message and validation would make this part of webpack less confusing.

**Comment by korve** [comment]
@bebraw Should it be possible to pass an empty array as a configuration?

**Comment by bebraw** [comment]
@korve That would fail the validation unless certain fields were passed through the CLI instead. Great point, though. Maybe this is something that needs certain finesse.

**Comment by erikfox** [comment]
> There was an issue where the user was passing a function without realizing it.

@bebraw Can you elaborate on this?

Also does existing validation/error messaging include a stacktrace?

**Comment by bebraw** [comment]
@erikfox I recall they tried to return a function from a function and that cannot work by definition.

**Comment by rlucha** [comment]
I got the error mentioned in the issue with webpack v4.17.1 when passing an array with an empty element on it.
``` TypeError: Cannot read property 'context' of undefined at outputOptions.context = firstOptions.context; ```

It is still a cryptic message and it was only solved after finding this issue.

**Comment by ev1stensberg** [comment]
I think that it's something a user will know. If you on purpose pass an empty element it's impossible for us to cover all the cases that could occur if we want to cover all cases. 

Users can send anything they want, but we need to generalize enough for our code to be consise but elaborative
