### ISSUE TITLE
Allow using a function in noParse

### ISSUE THREAD

**Issue by halfzebra** [webpack/webpack#4979]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
`noParse` configuration property accepts only regular expressions, which makes it a little hard to work with. Especially when negative lookbehind is required, which is not supported by JavaScript.

**If the current behavior is a bug, please provide the steps to reproduce.**
N/A

**What is the expected behavior?**
N/A
**If this is a feature request, what is motivation or use case for changing the behavior?**
It would be nice to have more freedom, like in [Condition](https://webpack.js.org/configuration/module/#condition), so it's easy to filter out the files we don't want to be parsed.

Let's say I don't want webpack to parse all files with `/\.elm/` extension, but if the filename is `/Stylesheet.elm/`, I want webpack to be able to parse the file.

This idea is primarily inspired by [elm-css-webpack-loader.](https://github.com/tcoopman/elm-css-webpack-loader#note-about-noparse)

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Unrelated.

**Comment by sokra** [comment]
yep, send a PR adding support for functions

**Comment by ssuman** [comment]
i sent a PR for this change. Please provide me feedback i'll make necessary changes. [4992](https://github.com/webpack/webpack/pull/4992)

**Comment by TheLarkInn** [comment]
Closed with #4992 thank you for the PR
