### ISSUE TITLE
changing importing order for named and default exports affects common chunk chunkhash

### ISSUE THREAD

**Issue by restrry** [webpack/webpack#4980]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
if you move modules into common chunk, sometimes changing in importing order for named and default exports will affect common chunk chunkhash

**If the current behavior is a bug, please provide the steps to reproduce.**
we have one `common` module:

*common.js*
```
export const a = "a";
export const b = "b";
export const c = "c";

export default "def";
```
and we require those constants in different files
*module-1.js*
```
import def, { a } from './common';
...
```
*module-2.js*
```
import { b, c } from './common';
...
```
then we decided to add `a` also in module-2
*module-1.js*
```
import def, { a } from './common';
...
```
*module-2.js*
```
import { a, b, c } from './common';
...
```
common chunk chunkcache  will be invalidated.

*webpack.config.js*
```
var webpack = require('webpack');
var path = require('path');

module.exports = [{
	entry: {
		app: "./index.js"
	},
	output: {
		path: path.join(__dirname, "./build/"),
		filename: "[name].[chunkhash].js"
	},
	plugins: [
            new webpack.NamedModulesPlugin(),
            new webpack.optimize.CommonsChunkPlugin({
                name: "vendor",
                minChunks: m => /common/.test(m.resource)
	    }),
            new webpack.optimize.CommonsChunkPlugin({
                name: "runtime"
            })
	]
}];

```

**What is the expected behavior?**
common chunk chunkhash shouldn't be invalidated if its content hasn't been changed

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
webpack v2.6.1
node v7.6

**Comment by bebraw** [comment]
I think this has to do with default module indexing. It's number based (0, 1, ...).

Have you tried `NamedModulesPlugin`?

**Comment by restrry** [comment]
@bebraw I'm using it. 
the whole configuration seems to be like:
```
output: {
        filename: '[name].[chunkhash].js'
},
...
plugins: [
     ...
      isDebug ? new webpack.NamedModulesPlugin() : new webpack.HashedModuleIdsPlugin(),
      new webpack.NamedChunksPlugin(),
       new webpack.optimize.CommonsChunkPlugin({
            name: 'vendor',
            minChunks: checkIsVendor
        }),
        new webpack.optimize.CommonsChunkPlugin({
            name: 'webpack-runtime'
        })
...
```
