### ISSUE TITLE
No global object available for {target: 'webworker'}|

### ISSUE THREAD

**Issue by haggholm** [webpack/webpack#4998]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When compiling a file using `{target: 'webworker'}`, the `global` object is not shimmed, whereas for the default `{target: 'web'}`, it seems to be set to refer to `window`. This breaks scripts that refer to (e.g.) `global.crypto`, which presumably should refer to the `WebworkerGlobalScope`.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

`global` should refer to the global worker scope.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Webpack 2

**Comment by korve** [comment]
Hi haggholm, i think thats expected behaviour, isnt it? See here: https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers

**Comment by korve** [comment]
I've tested it with webpack 2.6.1. For me global is defined.

index.js
`console.log(global.setTimeout);`

webpack.config.js
```js
module.exports = {
        output: {
                filename: "index.bundle.js",
        },
        target: "webworker"
};
```

node index.bundle.js
`[Function]`

**Comment by haggholm** [comment]
Weird. I guess I was too hasty to open a bug rather than create a smaller test case. I get an error in a 3rd party lib, `pbkdf2` (specifically, [here](https://github.com/crypto-browserify/pbkdf2/blob/v3.0.12/lib/async.js#L7), with `global.crypto` being a lookup on an undefined variable). I’ll see if I can produce a minimal scenario where it still fails, or if it’s only amidst the app build…

**Comment by lutzk** [comment]
i expierence the same error on `global.crypto`
but just when i set `node = false` in my webpack config for webworker
@korve did you run your test in node context? `node index.bundle.js`
i think it needs to be run in a browser?

my env:
```
webpack 3.0.0-rc.0
node8
chrome 59
```

**Comment by lutzk** [comment]
it seems that `node: false`  disables global

with `node: false` set:
```
[0] (webpack)/buildin/module.js 517 bytes {0} {1} [built]
...
```

withouth `node: false` set:
```
[0] (webpack)/buildin/module.js 517 bytes {0} {1} [built]
[1] (webpack)/buildin/global.js 509 bytes {1} [built]
...
```
