### ISSUE TITLE
UglifyJsPlugin: typescript sourcemap not match

### ISSUE THREAD

**Issue by zwwtj2014** [webpack/webpack#5006]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

After use webpack build my project (ts) with UglifyJsPlugin, it worked well, but **sourcemap not match** when debug with chrome.

1. line 81 can not have a breakpoint.
2. Begin,  I at line 80 and item.isCompletion==true, it will jump to line 83 if I single step debugging. 

![image](https://cloud.githubusercontent.com/assets/8098249/26784271/56a3d712-4a2f-11e7-9790-808980b73ccf.png)

```js
// webpack.config

   module: {
        rules: [
            {
                test: /\.ts$/,
                exclude: /node_modules/,
                loader: 'happypack/loader?id=ts'
            }
        ]
    },
    resolve: {
        extensions: ['.ts', '.js']
    },
   output: {
        filename: '[name].js',
        path: __dirname,
        libraryTarget: 'window'
    },
    plugins: [
        new HappyPack({
            id: 'ts',
            threadPool: happyThreadPool,
            loaders: [
                {
                    path: 'ts-loader',
                    query: {
                        happyPackMode: true
                    }
                }
            ]
        }),
        new webpack.optimize.UglifyJsPlugin({
            sourceMap: true,
            mangle: false
        })
    ],
   devtool: 'source-map'
```

**If the current behavior is a bug, please provide the steps to reproduce.**

build with UglifyJsPlugin

**What is the expected behavior?**

debug work well!!!

**If this is a feature request, what is motivation or use case for changing the behavior?**

none

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

browser version: 58.0.3029.110
Node version: v6.9.5
webpack: v2.6.0
OS: win7

**Comment by sokra** [comment]
With minimizing you may loose details in the source map.

Try analysing the source-map with http://sokra.github.io/source-map-visualization/

**Comment by zwwtj2014** [comment]
Thx for your reply! 

With source-map-visualization, it seems to lines all match!

**js & map**
![image](https://cloud.githubusercontent.com/assets/8098249/26818203/51026376-4acc-11e7-8203-0a50c668c09f.png)

**ts**
![image](https://cloud.githubusercontent.com/assets/8098249/26818302/b4543b02-4acc-11e7-86bb-6a38338ee0c7.png)

Or where i am wrong?

**Comment by sokra** [comment]
the `--`and `++` operators seem to point to the incorrect lines

**Comment by zwwtj2014** [comment]
:+1: Yes, You are right!

I build my project without UglifyJs Plugin， debug works for me.

Is there any good solution to the problem? Or I have to study how ts/uglifyjs works together to generate sourcemap ...

**Comment by evilebottnawi** [comment]
@webpack-bot move to webpack-contrib/uglifyjs-webpack-plugin
