### ISSUE TITLE
Module parse failed should show which loaders it applied by default

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack#5008]
**Do you want to request a *feature* or report a *bug*?**

Feature.

**What is the current behavior?**

If file processing fails, you get a message along

```
ERROR in ./index.web.js
Module parse failed: /Users/samuli1/projects/tulka-mobile-app/index.web.js Unexpected token (12:19)
You may need an appropriate loader to handle this file type.
```

**What is the expected behavior?**

Instead of just the error, webpack *should* show also the loaders it applied against the file. This is because often the above error is caused by misconfiguration (a loader not matching as expected or it was missing entirely).

**If this is a feature request, what is motivation or use case for changing the behavior?**

This change would make it easier for users to debug their issues in this particular case.

**Comment by esbenp** [comment]
What do you think of a solution like https://github.com/esbenp/webpack/commit/0117c0c65bdbd724691c1f38b44cf0a3bc4ac8ad @bebraw ?

As far as I can tell there are three cases:
1. Loader cannot be resolved (will cause a resolve error)
2. Error happens in loader
3. File did not match rule test

So I have added two cases to `ModuleParseError`:

2. Error happens in loader
```
Hash: 1cd77dc5f6b317a5627d
Version: webpack 3.3.0
Time: 389ms
 Asset    Size  Chunks             Chunk Names
out.js  5.8 kB       0  [emitted]  null
   [0] ./example.js 204 bytes {0} [built]
   [1] ./loader.js!./file.js 41 bytes {0} [built]
   [2] ./test.css 404 bytes {0} [built] [failed] [1 error]
   [3] (webpack)/node_modules/css-loader!./test.css 203 bytes {0} [built]
    + 1 hidden module

ERROR in ./test.css
Module parse failed: /Users/esben/code/webpack-esben/examples/loader/test-loader.js!/Users/esben/code/webpack-esben/examples/loader/test.css Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
The following loaders were applied to the file:
 - /Users/esben/code/webpack-esben/examples/loader/test-loader.js
| .some-class {
| 	color: hotpink;
| }
 @ ./example.js 5:12-33
```

3. File did not match any rule tests
```
Hash: 22978ab31ac46160c442
Version: webpack 3.3.0
Time: 372ms
 Asset     Size  Chunks             Chunk Names
out.js  5.64 kB       0  [emitted]  null
   [0] ./example.js 204 bytes {0} [built]
   [1] ./loader.js!./file.js 41 bytes {0} [built]
   [2] ./test.css 242 bytes {0} [built] [failed] [1 error]
   [3] (webpack)/node_modules/css-loader!./test.css 203 bytes {0} [built]
    + 1 hidden module

ERROR in ./test.css
Module parse failed: /Users/esben/code/webpack-esben/examples/loader/test.css Unexpected token (1:0)
No loaders were applied to the file. The file did not match any module rules.
| .some-class {
| 	color: hotpink;
| }
 @ ./example.js 5:12-33
```

I am unsure if this is the way to go about it, but at least this can be a launch of a discussion.
