### ISSUE TITLE
Watch finished hook / callback

### ISSUE THREAD

**Issue by MickL** [webpack/webpack#5009]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
I cant hook into when watch-task has finished

**What is the expected behavior?**
Watch task has finished, i can trigger a function (e.g. reload Browsersync)

**If this is a feature request, what is motivation or use case for changing the behavior?**
I like the performance of `watch` but i don't see any callback(watch-finished-hook) to reload my server or may do other tasks. E.g. Browsersync needs to get triggered manually. Example for my styles(using Gulp):

```
    gulp.watch('styles/**/*.scss', function() {
            runSequence('styles', 'server:reload')
    })
```

**Comment by sokra** [comment]
You can hook into "done"
