### ISSUE TITLE
Wrong paths for css source maps

### ISSUE THREAD

**Issue by katzz0** [webpack/webpack#5016]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Source maps for scss files produced by webpack contains duplicate parts like `C:\...C:\...\some-file.scss`.
I'd like to use relative paths but I can't understand why webpack use absolute paths for css files.

**If the current behavior is a bug, please provide the steps to reproduce.**
There is my loaders configuration for scss files:
```
loader: [
    "style-loader",
    {
        loader: "css-loader",
        options: {
            sourceMap: true,
            minimize: true,
            importLoaders: 2
        }
    },
    {
        loader: "postcss-loader",
        options: {
            sourceMap: true,
            plugins: function () {
                return [
                    require("autoprefixer")({
                        browsers: ["last 4 versions"]
                    })
                ];
            }
        }
    },
    {
        loader: "sass-loader",
        options: {
            sourceMap: true
        }
    },
    "sass-bulk-import-loader"
]
```

**What is the expected behavior?**
The source map file have to containe one absolute or relative path to the source file.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
webpack 2.2,1 but I also tested with 2.6.1 and the problem is the same
node.js 7.7.4
"style-loader": "^0.13.1"
"css-loader": "^0.28.4",
"postcss-loader": "^2.0.5",
"autoprefixer": "^7.1.1",
"node-sass": "^4.5.2",
"sass-loader": "^6.0.5"
Windows 7

**Comment by helloyou2012** [comment]
@katzz0 I have the same problem and finally located that: https://github.com/webpack-contrib/css-loader/pull/430

**Comment by evilebottnawi** [comment]
@webpack-bot move to https://github.com/webpack-contrib/css-loader
