### ISSUE TITLE
Webpack 3: * as imports inside index file - output conflicting names. 

### ISSUE THREAD

**Issue by gyandeeps** [webpack/webpack#5020]
**Do you want to request a *feature* or report a *bug*?**

Bug

_Note: I am still trying to create a small reproducable case but I am not able to do it. But i see this issue in my huge code base in my company._

**What is the current behavior?**

* We use a lot of `index.js` files and then we just `import` by specifying the import name till the folder.
* I am using `ModuleConcatenationPlugin`
* Many of my `index.js` files have code in this pattern

```js
import * as svg from "./svg";

export {
    svg
};
```

* I have many `index.js` files scattered in different folder which have the same content pattern.
* With webpack 2 everything works fine
* With webpack 3, I have see a variable named `index_js_namespaceObject` for all the files which have `index.js`.

here is some output:

```js
// CONCATENATED MODULE: ./src/main/js/controls/atomic/icon/svg/index.js
var index_js_namespaceObject = {};
__webpack_require__.d(index_js_namespaceObject, "SvgIcon", function() { return SvgIcon_js_defaultExport; });
__webpack_require__.d(index_js_namespaceObject, "alert", function() { return index_js_alert; });
__webpack_require__.d(index_js_namespaceObject, "clinical", function() { return clinical; });
__webpack_require__.d(index_js_namespaceObject, "communication", function() { return communication; });
__webpack_require__.d(index_js_namespaceObject, "content", function() { return index_js_content; });
__webpack_require__.d(index_js_namespaceObject, "image", function() { return index_js_image; });
__webpack_require__.d(index_js_namespaceObject, "navigation", function() { return navigation; });
__webpack_require__.d(index_js_namespaceObject, "notification", function() { return index_js_notification; });
__webpack_require__.d(index_js_namespaceObject, "status", function() { return status; });


// CONCATENATED MODULE: ./src/main/js/controls/atomic/icon/index.js
var index_js_namespaceObject = {};
__webpack_require__.d(index_js_namespaceObject, "svg", function() { return index_js_namespaceObject; });

// somehere in code
var _svg$clinical = index_js_namespaceObject.clinical,
    ClinicalBadge_js_Abnormal = _svg$clinical.Abnormal //-->>>>> ERROR here

// CONCATENATED MODULE: ./src/main/js/controls/composite/panel/detail-panel/index.js
var index_js_namespaceObject = {};
__webpack_require__.d(index_js_namespaceObject, "DetailPanel", function() { return DetailPanel_js_defaultExport; });
__webpack_require__.d(index_js_namespaceObject, "DetailPanelBanners", function() { return DetailPanelBanners_js_defaultExport; });
__webpack_require__.d(index_js_namespaceObject, "DetailPanelTitle", function() { return DetailPanelTitle_js_defaultExport; });
__webpack_require__.d(index_js_namespaceObject, "DetailPanelData", function() { return DetailPanelData_js_defaultExport; });

```

**If the current behavior is a bug, please provide the steps to reproduce.**

As you can see above that the `index_js_namespaceObject` get redefined everytime and that why i get some errors as pointed out above.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Node: 8
npm: 5
Webpack: beta, 3.x

I am trying to gather more info. Sorry for such a vague issue but i am trying. Thanks for patience

### UPDATE

Reproducible case: https://github.com/gyandeeps/webpack-5020 

I have tried to make it reproduce. I hope this makes sense.

### UPDATE 2

* After poking around, i think their is an issue with `import * as x` pattern in general. In my repocase above, even if you cutout icon1 branch and just keep one branch then also the final export doesnt connect all the way to the svg items.
* You will get infinite chain from svg5 -> svg -> svg -> svg -> ......

**Comment by TheLarkInn** [comment]
Could you test this against master. I believe we may have _just fixed this today_

**Comment by TheLarkInn** [comment]
Ref https://github.com/webpack/webpack/issues/5000

**Comment by gyandeeps** [comment]
Nah, I tested it. it has no impact. I think its unrelated too.
I have added a repro repo to the issue and also i think the issue is [here](https://github.com/webpack/webpack/blob/master/lib/optimize/ConcatenatedModule.js#L352) (based on my lil investigation)

**Comment by TheLarkInn** [comment]
Oh awesome! Sorry it looked related, I'll inspect this further.

**Comment by gyandeeps** [comment]
I have never looked deep into webpack that why my guess is the link above. I think ultimately its the name generation.

**Comment by gyandeeps** [comment]
With limited/no knowledge of Webpack internals, I think I have a solution for this problem.

Make a change here: https://github.com/webpack/webpack/blob/master/lib/optimize/ConcatenatedModule.js#L284

```js
const namespaceObjectName = this.findNewName("namespaceObject", allUsedNames, null, info.module.readableIdentifier(requestShortener));
allUsedNames.add(namespaceObjectName);
```

Not sure if this is the right solution but fixes the problem. :smile:

**Comment by gyandeeps** [comment]
Thanks a lot guys. @TheLarkInn @sokra

**Comment by gyandeeps** [comment]
woops ... webpack `3.0.0-rc.1` got released on `latest` tag on npm and not under `beta` tag.
CC: @sokra

**Comment by OmgImAlexis** [comment]
Getting the same issue here while using default imports.

```
Uncaught TypeError: __WEBPACK_IMPORTED_MODULE_0__utils__.b is not a function
```

`utils/get-meta.js`:
```js
import $ from 'jquery';

const getMeta = pyVar => {
    return $('meta[data-var="' + pyVar + '"]').data('content');
};

export default getMeta;
```

`utils/index.js`
```js
import browser from './browser';
import getMeta from './get-meta';
import getText from './get-text';
import isMeta from './is-meta';
import metaToBool from './meta-to-bool';
import notifyModal from './notify-modal';

export {
    browser,
    getMeta,
    getText,
    isMeta,
    metaToBool,
    notifyModal
};
```

`config/index.js`
```js
import {getMeta} from '../utils';

const config = {};

config.srRoot = getMeta('srRoot'); // <--- this line
config.srDefaultPage = getMeta('srDefaultPage');
config.themeSpinner = getMeta('themeSpinner');
config.anonURL = getMeta('anonURL');
config.srPID = getMeta('srPID');

export default config;
```
