### ISSUE TITLE
3.0.0-rc.1 published as "latest"

### ISSUE THREAD

**Issue by billyjanitsch** [webpack/webpack#5025]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Just wanted to let you know that you have 3.0.0-rc.1 tagged as `latest` rather than `beta` on npm, so `npm install webpack` installs 3.0.0-rc.1. I assume this was unintentional.

This can be fixed by someone with npm privs running:
```sh
$ npm dist-tag add webpack@3.0.0-rc.1 beta
$ npm dist-tag add webpack@2.6.1 latest
```

**If the current behavior is a bug, please provide the steps to reproduce.**

`npm info webpack dist-tags`

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by TheLarkInn** [comment]
Apologize for this, I don't quite have access yet to terminal atm but when I do I'm going to switch dist tag back right away. 

Sorry for the mistake and thank you so much for reporting this.

**Comment by TheLarkInn** [comment]
ETA 20-30 unless @sokra or @jhnnns can beat me to it

**Comment by TheLarkInn** [comment]
Alright I got it. Picture related. Thank you again for reporting this so quickly. Much appreciated. 
<img width="561" alt="screen shot 2017-06-07 at 10 24 25 am" src="https://user-images.githubusercontent.com/3408176/26886652-91525f9a-4b6b-11e7-814f-cd9ac5ab7259.png">

**Comment by TheLarkInn** [comment]
Also bumped the beta to rc-1 

<img width="569" alt="screen shot 2017-06-07 at 10 26 10 am" src="https://user-images.githubusercontent.com/3408176/26886726-be21dece-4b6b-11e7-9f32-ccfb00dfd36c.png">

**Comment by billyjanitsch** [comment]
❤️ Thanks for the quick fix!
