### ISSUE TITLE
moving module to a different chunk incorrectly eager loads async chunk

### ISSUE THREAD

**Issue by arackaf** [webpack/webpack#5030]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Changing an imports()'s webpackChunkName causes an async chunk to load before requested.

**If the current behavior is a bug, please provide the steps to reproduce.**

Pull down this repo / branch

https://github.com/arackaf/booklist/tree/special/webpack-bug

`npm i` in the root folder, and also in react-redux.

run `node app` in root folder.

run `npm start` from within react-redux, which should start webpack-dev-server.

Run  http://localhost:8080/

You should get a page that says "Hello."

Network tab should look like this.

![image](https://user-images.githubusercontent.com/11261266/26909156-9a77917c-4bc4-11e7-8da3-344b17947e5d.png)

In file `react-redux\modules\books\components\bookViewList.tsx` change 

```javascript
const BookSearchModal = Loadable({
    loader: () => System.import(/* webpackChunkName: "book-list-modals" */ './bookSearchModal'),
    LoadingComponent: ComponentLoading,
    delay: 500
});
```

to

```javascript
const BookSearchModal = Loadable({
    loader: () => System.import(/* webpackChunkName: "book-list-modals-X" */ './bookSearchModal'),
    LoadingComponent: ComponentLoading,
    delay: 500
});
```

Note the new chunkName.  

Note that the network tab, after the refresh, looks like this

![image](https://user-images.githubusercontent.com/11261266/26909209-ed19b8e2-4bc4-11e7-8582-362f64b9b6bd.png)

The chunk that used to have `./bookSearchModal` is now loading, for some reason.

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Node 6.10.3
webpack 2.6.1

**Comment by arackaf** [comment]
Per @sokra I tried changing my `asyncBundle` function to spit out a commonsChunk bundle with the name property set to the name passed in, with async: true, as opposed to async: name like I have now.

That caused nothing to work right, but in debugging that I may have found the root problem.  It seems like in *some circumstances* webpack doesn't like it when I create a commonsChunk with async: nameOfExistingChunk.  Sometimes it works fine (the original setup in the issue above) but sometimes it causes problems.

I wish I could be of bigger help here.

**Comment by arackaf** [comment]
One more comment on this.  If the following dependencies exist

A -> B -> C

Q -> R -> S

X -> Y -> Z

(A imports B; B imports C, etc)

If bundle (all are async)

One has (A, Q, X)
Two has (B, C)
and 
Three has (R, S, Y, Z)

if I import('A') is it correct for Two **and** Three to pull down?  Ie, if I load an async bundle, is it correct for webpack to immediately satisfy all the bundles' contents' dependencies immediately, or is webpack supposed to just satisfy whichever module I just requested, which caused the bundle to load?

If in the above Two and Three *are* supposed to load immediately, then just close this case.  That's what's happening here and, I'll just assume, what was happening before, even though it was likely far less obvious. 

Apologies for the time taken up by this and the other case.  It really seemed like a bug, and working my way through this to find that it wasn't was viciously hard (wasn't even looking for the right thing).

Of course if webpack does lazily load async dependencies based on what was imported, as opposed to whatever's in the newly loaded chunk, then it's definitely a bug.

**Comment by arackaf** [comment]
FYI I pushed a commit that further chops down the main `books-module` to have pretty much no external dependencies.  This should make it even clearer that there is some "unnecessary disconnectedness" somewhere, to quote Tobias.

**Comment by sokra** [comment]
unnecessary connectedness

**Comment by arackaf** [comment]
:-| 

It's been a long week :)

**Comment by arackaf** [comment]
Seems this is fixed with webpack 3.  Thanks for the amazing work you all do!
