### ISSUE TITLE
Webpack build dist start to ask about /schema/loader.json (which I don't have)

### ISSUE THREAD

**Issue by mattiLeBlanc** [webpack/webpack#5033]
Apparently one of the Typescript or other packages updated and now when I do a build I am getting an error message 
```
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/Users/matt/www/tests/forms-test/dynamic-form/schema/loader.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at validateOptions (/Users/matt/www/tests/forms-test/dynamic-form/node_modules/schema-utils/dist/validateOptions.js:35:27)

```
I tracked it down to some of the loaders expecting a loader.json file which is new to me. I googled this and I can't find any reference to it.

Is this something package specific or webpack related?

**Comment by michael-ciniawsky** [comment]
https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/534 Bugfix Release underway

**Comment by michael-ciniawsky** [comment]
Please close the issue here :)

**Comment by mattiLeBlanc** [comment]
Wow you are quick! We just narrowed it down to that one too. Thanks.
