### ISSUE TITLE
Break library bundles into pieces

### ISSUE THREAD

**Issue by mstijak** [webpack/webpack#5035]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Libraries usually provide large bundles or exports through index files. Importing bundles breaks webpack's ability to perform optimal code-splitting.

**If the current behavior is a bug, please provide the steps to reproduce.**

Here's a [small repo](https://github.com/mstijak/webpack-treeshake-play) describing the issue.

There is a library (lib) which exports four functions: `a`, `b`, `c`, and `d` and an app with two entry files `entry1.js` (E1) and `entry2.js` (E2). E1 imports functions `a` and `c`. E2 import functions `b` and `c`. Webpack is configured to create a commons chunk (C).

The output is:
E1: 
E2:
C: `a`, `b`, `c`, `d`

Everything is moved into the commons chunk C if functions are imported from a bundle.

**What is the expected behavior?**
E1: `a`
E2: `b`
C: `c`

`d` should be shaken off.

This behavior can be achieved by importing functions from their source files, however, that is not very practical as source files might be in a different language, e.g. TypeScript.

**If this is a feature request, what is motivation or use case for changing the behavior?**
By breaking into pieces, each entry chunk may include specific parts of imported libraries, so the commons chunk doesn't get too big and contains only what's really common across entry points.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
webpack@3.0 RC1

**Comment by sokra** [comment]
reexporting other modules is great, but it also means all modules have to be executed/included. The ESM spec says that a module have to be executed even if none of it's imports is used. The modules could have sideeffects.
