### ISSUE TITLE
Webpack 2.6.1 IgnorePlugin context (this) runtime errors

### ISSUE THREAD

**Issue by sandfox** [webpack/webpack#5038]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Webpack throws "context" related errors when using IgnorePlugin
`this.checkResult is not a function`

The stacktrace and webpack config are in [this gist](https://gist.github.com/sandfox/b7b282f72e50d358bbaa6d52c1e0d88b)

I've tried going threw the plugin and adding more `.bind(this)`, e.g
```
	apply(compiler) {
		compiler.plugin("normal-module-factory", (nmf) => {
			nmf.plugin("before-resolve", this.checkIgnore.bind(this));
		});
		compiler.plugin("context-module-factory", (cmf) => {
			cmf.plugin("before-resolve", this.checkIgnore.bind(this));
		});
```
but every time I do this it just moves the problem to another method call, which is leading me to believe that this problem is being caused by the class/methods are being invoked (wild guess, something like an `async` (the module) method that isn't being supplied with a context.

Part of me believes that maybe my config is the root cause of this as it's basically an upgraded webpack1 one, but I can't see anything obvious. 

If you need any more info, let me know. I'm still trying to make a mini-standalone example but it's a little hard to extract from my current project,

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
- Nodejs 6.9
- Webpack 2.6.1
- OSX

**Comment by sokra** [comment]
checkIgnore is bound in the constructor. So the plugin is fine. Not sure what the issue. Try to provide a minimal example

**Comment by sandfox** [comment]
ok, whilst creating the example app I discovered (by accident) the context / `this` problem was being caused by the use of a transient dependency (`clone`) in one of our build tools. Closing as this isn't webpack's fault!
