### ISSUE TITLE
Disable Autoreload on webpack-dev-server for some tabs (using a special query_param or with a function call)

### ISSUE THREAD

**Issue by edi9999** [webpack/webpack#5043]
**Do you want to request a *feature* or report a *bug*?**

A feature

**What is the current behavior?**

Whenever running with webpack-dev-server, I have the need to run some tests that run with phantomjs and that will test my application fully. However, If I save a file when the tests are running, the phantomjs page reloads and that is not expected in my test, and it will fail randomly. 

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

I would like to be able to disable autoreload with a function call or with a specific query param for example. 

going to `http://localhost?webpack_no_reload=true`

would stop webpack dev-server from reloading the page on each file change (but only for that page)

**If this is a feature request, what is motivation or use case for changing the behavior?**

It is very good to have reload in a "normal" browser, but sometimes, it may be possible that you do not want to reload the page, but would like to keep the "current" version to avoid page reloads (and possible loss of state/information)

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

nodejs version : 8.0.0
webpack version : 2.6.1
webpack dev server : 2.4.5

**Comment by sokra** [comment]
@webpack-bot move to webpack/webpack-dev-server
