### ISSUE TITLE
Load chunked assets from path relative to a variable entry location on CDN

### ISSUE THREAD

**Issue by sirugh** [webpack/webpack#5045]
**Do you want to request a *feature* or report a *bug*?**
Feature!

**What is the current behavior?**
The `publicPath` config option sets path relative to the current page url.

**If the current behavior is a bug, please provide the steps to reproduce.**
(notabug)

**What is the expected behavior?**
I would like to load chunked assets from a path relative to the entry script file's url, not the host page.

**If this is a feature request, what is motivation or use case for changing the behavior?**
My company develops solutions that are loaded on sites as third party scripts, similar to Disqus. Our current assets are hosted from a CDN, but the location is variable (otherwise we'd just hard code the cdn path). Instead of hard-coding a new CDN path each time in `publicPath`, we'd like to be able to configure our bundles to load chunks/assets relative to the entry script's location.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Using webpack 2.

**Comment by Velveeta** [comment]
Just to add some context to this request, we have a webpack script to build our deployment assets, relative to each other, and a deployment script that pushes them to some nested path in S3, segmented by deployment environment, and these are then loaded from any number of urls in the wild.

We could hardcode the S3 paths into our webpack script so they could be set as the publicPath for output, but then we're leaking deployment details into our webpack script, which we'd rather not do.

It would be great if there were an option to just tell the entry file "whatever url you load at, use that as your base, and load all of your chunks relative to yourself".

**Comment by Velveeta** [comment]
Commenting on this to keep it alive. It would still be great if we could load additional assets relative to the url the entry point is loaded from, and not relative to the page url. This would allow us to store our exported bundles and chunks on some external CDN and still be able to load them reliably, without having to specify the publicPath as a fully qualified url path. Deployment scripts often store different environments (prod/staging/dev/test/etc) on different servers, and this would help simplify the build-and-deploy process, by not requiring us to pull the deployment destination from our deploy script and inject it into our build script so it can be used as part of the webpack configuration. Webpack already makes the assumption that the url of the page is its relative path root, and that it can reference everything else from that path, if no publicPath is used in the configuration. It doesn't seem like a huge step, or logically out of place, to have it assume the url it's actually loaded from is it relative path root instead.
