### ISSUE TITLE
V4 Architecture: DependenciesBlock<Module> extensibility API

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack#5046]
Currently there are two projects that are starting or just about to start that will require another file type be treated as a first class citizen in webpack. (ICSS2 & WebAssembly)

For this to happen in the current plugin architecture, we would need to do the following:
* Create new flavor specific Parser.js 
* Facilitate any Template and Subclasses to generate the proper runtime based on the asset
* Create module factories
* Have templates for any supported existing webpack targets: worker, electron-renderer, node, async-node
* Have enhanced-resolve flavor specific resolution patterns for each module type
* Have webpack-sources and source-list-map specific handlings for sourcemaps and source mutations (?)
* Have interoperable caching and minifying patterns where neccesary

Seeing all this in mind I'd like to open discussion for how we are going to scale this appropriately. 

Although I don't have solutions for every bullet point there seems like a possibility to create an API surface that could allow for "first class modules" to be implemented in a much easier fashion. In addition to this even a possibility for users to create "first class modules" themselves. 

### Parser meta/token event map
It would be really hard to maintainers 3+ separate large Parser.js files for each type. So I'd like to propose a meta language or schema map. Our current parser is both parser, and walker. If we could extract and abstract the walkers behavior to adapt to any/most AST's then there is potential to have a map or schema of some sort that could describe each token, how it must be walked, and the events it would emit (for parser plugins to pick up). My knowledge of CSS and HTML (first class potential modules that we would need to know) is limited and I am not sure if there is enough adaptable walking behavior to facilitate this but if it is possible, we could save an extreme amount of boilerplate walker and event emitting logic. 

### Monorepo transition and `webpack-module-x`
I'd like to see the code that we write for each first class module type be isolated into its own package, this way we only require that code when the user is leveraging one of these module types. I think that naming these `webpack-module-x` that would individually reside in webpack/webpack as a monorepo and manage with lerna etc. This would probably warrant us to also separate DependenciesBlock and Module and a few other helper classes into it' own package as well as each "webpack-module" will need to leverage these classes. 

So far these are just a few ideas I have right now that are high level but we want open discussion, ideas and feedback in ways to craft this archicture in a way that will allow first class modules to scale much easier as we go. I imagine that down the road we would ideally see up to 4-5 first class modules including HTML and TypeScript.

**Comment by bmeck** [comment]
> * Have enhanced-resolve flavor specific resolution patterns for each module type
> * Have webpack-sources and source-list-map specific handlings for sourcemaps and source mutations (?)
> * Have interoperable caching and minifying patterns where neccesary

These 3 sound like a data layer needs to be defined for these things. Saving something to cache/disk should keep source/sourcemap but should avoid actual inlining until linking occurs. Otherwise translation of CSS into JS etc. would make it appear as thought the transformed CSS is JS (not ideal if tooling wishes to do CSS specific operations). However, after linking optimization passes such as a minifier probably do want to run where it only sees JS or CSS in the output graph.

**Comment by g0t4** [comment]
Any plans or discussion for the impact on configuration?

**Comment by TheLarkInn** [comment]
@g0t4 Sorry for the inactivity. This materialized into what we call the "type" property that now lives on the module object themselves. I think it's safe for this to be closed.
