### ISSUE TITLE
Consider making all requires lazy (inline requires)

### ISSUE THREAD

**Issue by niieani** [webpack/webpack#5050]
**Feature request**

Use `babel-plugin-transform-inline-imports-commonjs` to inline all requires in the webpack codebase, making most modules lazy-loaded. Switching to inlined requires is a proven way to increase the runtime performance of the application.

**What is the current behavior?**
All Webpack files use top-level `require()`.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Jest is now making the switch to inline requires and they see a massive improvement in performance:

Before inlining requires:

![](https://cloud.githubusercontent.com/assets/5106466/25776153/edb4c296-32b6-11e7-864b-0d5df0378ce6.png)

After:

![](https://cloud.githubusercontent.com/assets/5106466/25776154/f57c3856-32b6-11e7-9252-27a4ad3f4c86.png)

See their issue here: https://github.com/facebook/jest/pull/3493.

If `webpack` would see an even 10% increase in execution speed, I believe it would be worth doing it.

**Comment by rafde** [comment]
Out of curiosity:
Is that testing the jest test suites image?
Have you tried testing to see how `node --ignition --turbo webpack` using NodeJS 8 compares? Supposedly that helps ES2015+ work better.

**Comment by cacheflow** [comment]
Is this still needed? If it is, I'm willing to tackle this issue.

**Comment by niieani** [comment]
I think it would be interesting to experiment with, but given that `webpack` doesn't use transpilation via babel, it would add complexity (a build step). I don't think the benefit will be very big, since you need a large chunk of webpack to run a compilation. I'm happy to close this, but feel free to experiment.

**Comment by salazarm** [comment]
Sorry to Necro an old thread but I think this would be very helpful for big SPA Apps that can't effectively code split their bundles. The problem with codesplitting via dynamic imports is that we need to run javascript before realizing we need to download the extra code. This app doesn't have a webserver its just a static resources.
