### ISSUE TITLE
Tutorial link for webpack 2.x returns a 404

### ISSUE THREAD

**Issue by robcresswell** [webpack/webpack#5051]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

The "tutorial" link under "webpack 2.x" at https://webpack.github.io/ returns a 404. It looks for https://webpack.js.org/guides/get-started which doesn't exist.

**If the current behavior is a bug, please provide the steps to reproduce.**

1) Go to https://webpack.github.io/
2) Click "tutorial" under the "webpack 2.x" header

**What is the expected behavior?**

I would be able to view the tutorial

**If this is a feature request, what is motivation or use case for changing the behavior?**

N / A

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by sokra** [comment]
@webpack-bot move to webpack/webpack.js.org
