### ISSUE TITLE
There are files a.b and a.b.ts, resolve.extensions = ['.ts'] invalid

### ISSUE THREAD

**Issue by zwwtj2014** [webpack/webpack#5054]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

There are files a.b and a.b.ts in a same folder，`import xxx from 'a.b'` will load file a.b even you set up resolve.extensions = ['.ts'] without *

I do not know if this is the default behavior? And how do i configure to load a.b.ts?

In order to find a place to parse the suffix I try to debug the code, and find resource will be resolved in [NormalModuleFactory.js](https://github.com/webpack/webpack/blob/master/lib/NormalModuleFactory.js#L121-L137):
```js
asyncLib.parallel([
	callback => this.resolveRequestArray(contextInfo, context, elements, this.resolvers.loader, callback),
	callback => {
		if(resource === "" || resource[0] === "?")
			return callback(null, {
				resource
			});

		this.resolvers.normal.resolve(contextInfo, context, resource, (err, resource, resourceResolveData) => {
			if(err) return callback(err);
				callback(null, {
					resourceResolveData,
					resource
				});
			});
		}
], (err, results) => {
      // callback
 }
```

**If the current behavior is a bug, please provide the steps to reproduce.**
1. a.b and a.b.ts in the same folder
2. `import xxx from 'a.b';`
3. webpack.config.js: resolve.extensions = ['.ts']

**What is the expected behavior?**

load a.b.ts instead of a.b

**If this is a feature request, what is motivation or use case for changing the behavior?**

none

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

browser version: 58.0.3029.110
Node version: v6.9.5
webpack: v2.6.1
OS: win7

**Comment by sokra** [comment]
The exact match is preferred. `*` is not even valid in this array.

You could disable this behavior with `resolve.enforceExtension = true`.

**Comment by zwwtj2014** [comment]
@sokra Thank you for your reply!

Yes, I also noticed the configuration. but `import xxx from 'a.ts'` will have a error: **[ts] An import path cannot end with a '.ts' extension** and [here](https://github.com/Microsoft/TypeScript/issues/11235#issuecomment-250543334) is a reason.

**Comment by sokra** [comment]
`resolve.enforceExtension` will enforce adding an extension by the resolver. So `a` will resolve to `a.ts` but not to `a`.

**Comment by zwwtj2014** [comment]
@sokra Yes, That is what my hope!

But With `resolve.enforceExtension: true`, has a error: 
```
ERROR in Entry module not found: Error: Can't resolve './src/main/webapp/xxx/xxx.ts' in 'D:\xxx\xxx'
```

And run `webpack` with cli `--display-error-details`:
```txt
resolve './src/main/webapp/xxx/xxx.ts' in 'D:\xxx\xxx'
[0]   using description file: D:\xxx\xxx\package.json (relative path: .)
[0]     Field 'browser' doesn't contain a valid alias configuration
[0]   after using description file: D:\xxx\xxx\package.json (relative path: .)
```
