### ISSUE TITLE
replace the deprecated loader._module API

### ISSUE THREAD

**Issue by FranckFreiburger** [webpack/webpack#5055]
**Do you want to request a *feature* or report a *bug*?**
**feature**

**What is the current behavior?**
`loader._module` and some other loader API are marked as [deprecated](https://webpack.js.org/api/loaders/#deprecated-context-properties)

**If this is a feature request, what is motivation or use case for changing the behavior?**
Currently, I use `_module.meta` to pass some data from my loader to my plugin, without this API I cannot see any other way to do that.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
latest v2.x.x version

**Comment by sokra** [comment]
You should add your own method to the loader context from plugin to pass data.

Hook into `normal-module-loader` from `Compilation` to add properties to the loader context. Best prefix them with some private name (`__dirname`) or use a `Symbol`.
