### ISSUE TITLE
Resolve Modules Doesn't Resolve Modules

### ISSUE THREAD

**Issue by bruce-mitchell** [webpack/webpack#5061]
**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**

I have a submodule which is used across all my projects as a global base for my build config.
At build time the parent project pulls in the webpack config from the submodule and compiles.
Majority of my 3rd party dependencies are located in the submodule so to resolve these modules I have added the absolute path to resolve.modules config array, however these are not resolving as expected.

I have had this issue for a long time and this is the second instance #3160 in which I attempted to gain clarity on what might be causing this issue.

**If the current behavior is a bug, please provide the steps to reproduce.**

**File Structure:**

* Project
  * GlobalSubmodule
    * node_modules
* Webpack.config
* node_modules

**Webpack Config**

resolve: {
modules: [
path.join('path_to_global_submodule', './node_modules'),
'node_modules'
]

**What is the expected behavior?**

The dependencies should resolve at build time.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Webpack version:**
^2.6.1

**Environment:**
Windows 10

**Framework/Language:**
Angular ^4.1.2, Typescript ^2.0.10

**Comment by sokra** [comment]
What's the error? A bit more details would be great.

Note that typescript has it's own resolver that can be configured independently.
