### ISSUE TITLE
webpack2 is much slower than webpack1

### ISSUE THREAD

**Issue by fedeoo** [webpack/webpack#5063]
**Do you want to request a *feature* or report a *bug*?**
NO

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

I build my project with weppack 1 and webpack2 which have almost same config.  It seems webpack2 cost more time to build, even the result file is almost same size. I wonder why webpack2 is so slow, Did I miss some config ?

Context: OS: MacOS Sierra Node: 6.10.2

Version: webpack 1.15.0
Time: 16809ms
   Asset     Size  Chunks             Chunk Names
index.js  4.66 MB       0  [emitted]  index

Version: webpack 2.6.1
Time: 28169ms
   Asset     Size  Chunks                    Chunk Names
index.js  4.62 MB       0  [emitted]  [big]  index

The config of webpack1 like this:
```js
{
  context: 'projectpath', //
  entry: {
    index: './src/index.jsx'
  },
  output: {
    path: 'build',
    filename: '[name].js',
    publicPath: '/build/'
  },
  resolve: {
    modulesDirectories: ['node_modules'],
    extensions: ['', '.js', '.jsx']
  },
  externals: {
    react: 'window.React',
    'react-dom': 'window.ReactDOM',
    // react addons
  },
  module: {
    loaders: [{
      test: /\.scss$/,
      loaders: ['ignore-loader'],
    }, {
      test: /\.json$/,
      loader: 'json-loader',
    }, {
      test: /\.less$/,
      loader: 'ignore-loader',
    }, {
      test: /\.css$/,
      loader: 'ignore-loader',
    }, {
      test: /\.jsx?$/,
      exclude: /node_modules/,
      loader: 'babel-loader',
    }]
  },
  plugins: [
    new webpack.optimize.OccurenceOrderPlugin(),
    new webpack.optimize.DedupePlugin(),
    new webpack.NoErrorsPlugin(),
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: JSON.stringify('production'),
      },
    }),
  ]
}
```

The config of wepback like this:
```js
{
  context: 'projectpath',
  entry: {
    index: './src/index.jsx'
  },
  output: {
    path: 'build',
    filename: '[name].js',
    publicPath: '/build/'
  },
  resolve: {
    modules: ['node_modules'],
    extensions: ['.js', '.jsx'],
  },
  externals: {
    react: 'window.React',
    'react-dom': 'window.ReactDOM',
    // react addons
  },
  module: {
    rules: [{
      test: /\.scss$/,
      use: ['ignore-loader'],
    }, {
      test: /\.json$/,
      use: 'json-loader',
    }, {
      test: /\.less$/,
      use: 'ignore-loader',
    }, {
      test: /\.css$/,
      use: 'ignore-loader',
    }, {
      test: /\.jsx?$/,
      exclude: /node_modules/,
      use: 'babel-loader',
    }]
  },
  plugins: [
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: JSON.stringify('production'),
      },
    }),
  ]
}
```

**Comment by rafde** [comment]
have you tried with webpack 3?
`npm i webpack@beta`?

**Comment by fedeoo** [comment]
@rafde  I rebuild my project using webpack3 and the config of the above webpack2. The result I got 

Hash: 96ecd424077220f68ad2
Version: webpack 3.0.0-rc.1
Time: 25448ms
   Asset     Size  Chunks                    Chunk Names
index.js  4.62 MB       0  [emitted]  [big]  index

It seem better than webpack2.

**Comment by xzyfer** [comment]
I've collected some data on Webpack 1 vs 2 vs 3

```
Version: webpack 1.15.0
Time: 10335ms
 Asset     Size  Chunks             Chunk Names
app.js  3.37 MB       0  [emitted]  main
    + 529 hidden modules


Version: webpack 1.15.0
Time: 31323ms
 Asset     Size  Chunks             Chunk Names
app.js  1.18 MB       0  [emitted]  main
    + 514 hidden modules

=======

Version: webpack 2.6.1
Time: 39612ms
 Asset     Size  Chunks                    Chunk Names
app.js  3.82 MB       0  [emitted]  [big]  main
    + 516 hidden modules

Version: webpack 2.6.1
Time: 65740ms
 Asset    Size  Chunks                    Chunk Names
app.js  1.2 MB       0  [emitted]  [big]  main
    + 499 hidden modules

=======

Version: webpack 3.0.0-rc.2
Time: 41045ms
 Asset     Size  Chunks                    Chunk Names
app.js  4.19 MB       0  [emitted]  [big]  main
    + 678 hidden modules

Version: webpack 3.0.0-rc.2
Time: 71755ms
 Asset     Size  Chunks                    Chunk Names
app.js  1.27 MB       0  [emitted]  [big]  main
    + 661 hidden modules
```

Our config looks like

```js
var config = {
    resolve: {
        extensions: ['.js', '.jsx'],
        modules: [
            'assets'
            'assets/js'
            'node_modules',
        ]
    },
    module: {
        rules: [{ test: /\.jsx?$/, loaders: ['babel-loader'] }]
    },
    plugins: {
        new webpack.DefinePlugin({
            'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV),
        }),
    },
    entry: "js/app.jsx",
    output: {
        path: '/output/js',
        filename: 'app.js',
        chunkFilename: '[id].chunk.js',
        publicPath: '/assets/js'
    }
};

if (process.env.NODE_ENV === 'production') {
    config.plugins = config.plugins.concat([
        new webpack.optimize.OccurrenceOrderPlugin(),
        new webpack.optimize.DedupePlugin(),
        new webpack.optimize.UglifyJsPlugin({
            sourceMap: true,
            compress: {
                warnings: false
            },
        })
    ]);
}

```

**Comment by fedeoo** [comment]
I found the key reason contribute to slow speed with webpack2: It's npm's problem. I used a private npm registry -- cnpm which have different file structure with npm. It seem webpack2 is more efficient after I replace cnpm with npm.

so I'll close this issue.

**Comment by xzyfer** [comment]
We do not use cnpm, and are still experiencing 2x-4x slow downs in builds.

**Comment by xzyfer** [comment]
Following up. We removed the unnecessary `DedupePlugin` and `OccurrenceOrderPlugin` without any appreciable change in compilation times.

**Comment by xzyfer** [comment]
Final follow up, the issue was caused by moving the babel-loader exclusion in to .babelrc from the loader config. Restoring the loader config exclusion fixed things.

**Comment by intpp** [comment]
@xzyfer Can you give more details?

**Comment by xzyfer** [comment]
The babel loader configuration had an exclude config to exclude
node_modules.

I had move the exclusive to my .babelrc assuming they'd be equivalent,
which apparently they are not.
