### ISSUE TITLE
ProvidePlugin doesn't support IIFE this's property

### ISSUE THREAD

**Issue by ljqx** [webpack/webpack#5067]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Similar to #812 which is for IIFE parameters, ProvidePlugin doesn't support IIFE `this`'s property.

**If the current behavior is a bug, please provide the steps to reproduce.**
The entry file:
```
(function(){
  window.export = this.jQuery;

}).call(window);
```

The config:
```javascript
var webpack = require('webpack');

module.exports = {
  entry: './src/index.js',
  output: {
    filename: './dist/bundle.js',
  },
  plugins: [
    new webpack.ProvidePlugin({
      'window.jQuery': 'jquery',
    }),
  ]
};
```

**What is the expected behavior?**
ProvidePlugin should replace `this`'s property following plugin config. In above example, it should require `jquery` and replace window.jQuery with the resolved version.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Not a feature request.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Node v6.9.1, webpack v2.6.1, Windows 10

**Comment by ljqx** [comment]
Seems this is because in `Parser.js` `walkCallExpression` it doesn't rename for `this`, only arguments are renamed. I'll try to send out a fix.

**Comment by TheLarkInn** [comment]
Thank you, I'll keep an eye out for the PR.

**Comment by ljqx** [comment]
Hi, @TheLarkInn , I've sent out a fix. Please help take a look, thanks.
