### ISSUE TITLE
Failed to resolve es6 harmony import

### ISSUE THREAD

**Issue by jakwuh** [webpack/webpack#5068]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Webpack fails to resolve es6 harmony import

**If the current behavior is a bug, please provide the steps to reproduce.**
I've created a small repo to ease bug reproducing https://github.com/jakwuh/webpack-import-bug

**What is the expected behavior?**
The expected behaviour is to resolve harmony import

**If this is a feature request, what is motivation or use case for changing the behavior?**
Not a feature request

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Node v6.10.1
Webpack beta and 2.6.1
macOS 10.12.5 (16F73)

**Comment by TheLarkInn** [comment]
Can you verify this in webpack 3.0.0-rc.2?? Not able to clone the repo myself at the moment but would like to see if this is reproduce in v3

**Comment by jakwuh** [comment]
@TheLarkInn yes, it reproduces in webpack 3.0.0-rc.2

**Comment by sokra** [comment]
yes it's a bug. We should fix this eventually, but it's not super important...
