### ISSUE TITLE
Cannot resolve module

### ISSUE THREAD

**Issue by tcaer** [webpack/webpack#5069]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
Webpack throws an error because it is not properly finding the react or reactdom packages.

**If the current behavior is a bug, please provide the steps to reproduce.**
`import * as React from 'react';`
My webpack configuration is the same one used in the typescript tutorial [here](https://www.typescriptlang.org/docs/handbook/react-&-webpack.html)

**What is the expected behavior?**
All of the code should compile and I should be able to use my react app online.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
I am using all of the most recent webpack and node.js versions. I am using safari and Mac OS X 10.12.5.

Here is the error I get below:
`ERROR in ./~/react-dom/index.js
Module not found: Error: Can't resolve './lib/ReactDOM' in '/Users/tinocaer/phoenix/node_modules/react-dom'
 @ ./~/react-dom/index.js 3:17-42
 @ ./src/resources/js/app.tsx`
`ERROR in ./~/react/react.js
Module not found: Error: Can't resolve './lib/React' in '/Users/tinocaer/phoenix/node_modules/react'
 @ ./~/react/react.js 3:17-39
 @ ./src/resources/js/app.tsx`

**Comment by sokra** [comment]
probably a misconfiguration of `resolve.extensions`

**Comment by tcaer** [comment]
Don't remember how I fixed this... I just did.
I will try to look at my code and see what I did differently and comment if I found an answer.
