### ISSUE TITLE
RawModule has incorrect hashing

### ISSUE THREAD

**Issue by jbellenger** [webpack/webpack#5070]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The module hash of a RawModule does not incorporate the source string that it is initialized with. At Twitter, this has created incidents where the contents of a chunk change between builds but the chunkhash does not, causing web clients to use mismatched assets.

**If the current behavior is a bug, please provide the steps to reproduce.**
Gist at https://gist.github.com/jbellenger/e3cde645b20f15260c9f9189a7cb8f7c

**What is the expected behavior?**
RawModules should include their source strings in their hash. This looks like it was previously done in webpack-1: https://github.com/webpack/webpack/blob/v1.15.0/lib/RawModule.js#L49-L53

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
This was tested in node 6.10.2, webpack-2.4.1, and osx 10.11.6

**Comment by sokra** [comment]
seems like this was accidentally removed in https://github.com/webpack/webpack/commit/5b094c0b5e4e47adccccccdcdc1703db18d85c74
Send a PR readding it.

**Comment by jbellenger** [comment]
Created PR https://github.com/webpack/webpack/pull/5085
