### ISSUE TITLE
"module" field in package.json breaks if author uses it

### ISSUE THREAD

**Issue by bradennapier** [webpack/webpack#5071]
Whenever an author adds the "module" field to a package.json - I start getting errors like "Illegal Invocation" when I try to load that file.  redux-persist for example provides it and if I don't delete the module from the package.json it fails completely.  

Using Webpack 3

**Comment by evilebottnawi** [comment]
@bradennapier very difficult to detect where is problem without configuration or minimum reproducible test repo. Please recreate issue and use issue template. Thanks!
