### ISSUE TITLE
Able to track file removal in `watch-run`

### ISSUE THREAD

**Issue by s-panferov** [webpack/webpack#5072]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

It's not possible to get removed files using current `watching.getTimes()` API.

**What is the expected behavior?**

Provide some way to get the list of removed files from FS watcher.

**If this is a feature request, what is motivation or use case for changing the behavior?**

It will allow TypeScript (and other stateful loaders) to remove files from the inner state.

**Comment by TheLarkInn** [comment]
@s-panferov I assume this is specific to awesome-typescript-loader. Do you have an example you can reference?

**Comment by niieani** [comment]
This would also help us to remove stale cache of extracted locale strings from deleted files.

**Comment by TrySound** [comment]
@TheLarkInn It's specific to stateful loaders with own graphs. ats loader are not the only one with such case. [modular-css](https://github.com/tivac/modular-css) do the same.

**Comment by cacheflow** [comment]
Is this still needed? I'd like to take this on. @s-panferov @TheLarkInn

**Comment by aholtkamp** [comment]
It would be cool if this would be implemented! We currently have an own implementation to track deleted files via a webpack plugin but this does not work very well.

**Comment by s-panferov** [comment]
Yes, this is still a problem

**Comment by evilebottnawi** [comment]
Feel free to PR

**Comment by cacheflow** [comment]
Just to clarify, you want this feature when you hook into the compiler's watchRun correct?  @s-panferov 

Also, what are your thoughts on this being a separate API vs emitted through watchRun? I'm thinking the latter maybe something called `watchRemoved`. @TheLarkInn @sokra

**Comment by cacheflow** [comment]
I think this is it. All feedback/critiques welcome 😄: 

https://github.com/webpack/webpack/pull/8175
