### ISSUE TITLE
CommonsChunkPlugin with children option unsafe for children with multiple parents

### ISSUE THREAD

**Issue by lencioni** [webpack/webpack#5078]
**Do you want to request a *feature* or report a *bug*?**

Bug?

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

If I have two entry points that both use the same async bundles, and use the CommonsChunkPlugin with the `children` option, it seems that one of the parent bundles receives the common chunks from the children, but the other does not. This ends up breaking pages that happen to use the bundle that did not receive the common chunks, which is why I am suggesting it might be a bug.

For example, let's say I have two entry points, `entryFoo.bundle.js` and `entryBar.bundle.js`. Now lets say that both of these entry points use the same async bundles, `async-a.js`, `async-b.js`, `async-c.js`, and `async-d.js`. Now lets say I have configured webpack like this:

```js
    new webpack.optimize.CommonsChunkPlugin({
      names: [
        'entryFoo.bundle',
        'entryBar.bundle',
      ],
      children: true,
      minChunks: 4,
    }),
```

This seems to extract the common chunks from the children into one of the entry bundles but not the other, and there doesn't seem to be a way to configure webpack to make this work.

**What is the expected behavior?**

I think it might make sense to have webpack by default consider both parent trees when making decisions about children common chunks, and provide a mechanism to opt out specific bundles from this behavior (e.g. if you have two entry points that you know will always be on the same page). 

Alternatively, I think it would be acceptable to do the inverse, where the behavior is as it currently works but there is a way to configure webpack to opt in specific entry points into this behavior.

If it is already possible to accomplish this, I'd love to know how!

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

I noticed this on webpack 2.3.2 (which we are stuck on until #4863 is resolved).

Thanks so much for all of your hard work on this project!

**Comment by lencioni** [comment]
I'm trying this with webpack 3.8.1, and using the `async` option as well, and still running into similar issues. Specifically, this type of configuration results in errors like:

```
manifest.bundle.js:150 TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (manifest.bundle.js:58)
    at eval (MemoriesCardRow.jsx:1)
    at Object.4288 (spaCommon-async.js:3746)
    at __webpack_require__ (manifest.bundle.js:58)
    at eval (ExploreSectionContent.jsx:1)
    at Object.4249 (spaCommon-async.js:3435)
    at __webpack_require__ (manifest.bundle.js:58)
    at eval (ExploreSection.jsx:1)
    at Object.2712 (spaCommon-async.js:1158)
    at __webpack_require__ (manifest.bundle.js:58)
```

One thing I noticed is that if I give the `async` option a string and using a single `name`, it will use the string I give to `async` as the bundle name for this common chunk asset. If I use an array of `names`, it will name the common chunk asset based on the name of the first item in the `names` array. Not sure if this is intentional or not.

Looking at the documentation for CommonsChunkPlugin, it seems like it should be possible to use it in this way, so I'm not sure if I'm just missing something obvious or if this is a bug in the plugin. Any suggestions about things to try or where to start looking?

**Comment by nowells** [comment]
This is fixed by https://github.com/webpack/webpack/pull/5145
