### ISSUE TITLE
Feature Request: Log module 

### ISSUE THREAD

**Issue by ev1stensberg** [webpack/webpack#5079]
**Do you want to request a *feature* or report a *bug*?**
Feature Request

**What is the current behavior?**

Right now, running webpack is a smooth experience. However, many of the logs are being done manually, and the output of the CLI could be improved. I'm not sure if stats really fits webpack, because we are combining stats in such a way that is inconsistent for plugin authors to reproduce without having to deal with a lot of digging into the source code. 

If we were to create a logger module / library, this would allow plugin authors to be consistent with how we would output to the terminal, which means better user experience as well as exposing more of the source code in such a way that more people can relate to.

**What is the expected behavior?**
Consistent, polished output from the terminal

**If this is a feature request, what is motivation or use case for changing the behavior?**
It's inconsistent and could be improved

**Comment by ev1stensberg** [comment]
Happy to work on this btw

**Comment by bebraw** [comment]
#3996 feels related.

**Comment by ev1stensberg** [comment]
Closing, lets resume the conv there.
