### ISSUE TITLE
configuration has an unknown property 'allowedHosts'

### ISSUE THREAD

**Issue by screendriver** [webpack/webpack#5080]
**Do you want to request a *feature* or report a *bug*?**

Bug 🐛 

**What is the current behavior?**

I added [devServer.allowedHosts](https://webpack.js.org/configuration/dev-server/#devserver-allowedhosts) to my `webpack.config.js` and it complains with

```sh
configuration has an unknown property 'allowedHosts'. These properties are valid:
   object { hot?, hotOnly?, lazy?, host?, filename?, publicPath?, port?, socket?, watchOptions?, headers?, clientLogLevel?, overlay?, key?, cert?, ca?, pfx?, pfxPassphrase?, inline?, disableHostCheck?, public?, https?, contentBase?, watchContentBase?, open?, features?, compress?, proxy?, historyApiFallback?, staticOptions?, setup?, stats?, reporter?, noInfo?, quiet?, serverSideRender?, index?, log?, warn? }
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Just add 

```js
devServer: {
  allowedHosts: [
    '.host.com',
    'host2.com'
  ]
},
```

to your `webpack.config.js`

**What is the expected behavior?**

It should not complain about it because the property is documented [here](https://webpack.js.org/configuration/dev-server/#devserver-allowedhosts)

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

webpack `2.6.1`

I just want to access the `webpack-dev-server` outside of my local dev machine (e.g. my mobile phone)

**Comment by bebraw** [comment]
The version containing the new feature hasn't been published yet [based on the change log](https://github.com/webpack/webpack-dev-server/commits/master).

@webpack-bot move to webpack/webpack-dev-server

**Comment by xieanwen** [comment]
staticOptions: { 
   index: ‘main.html’
}
无效
![image](https://github.com/webpack/webpack/assets/24740695/6c1f5324-d12d-4a47-9362-5c5cc77a3096)
