### ISSUE TITLE
Cannot get final name for export "default" in "delegated ..." with Webpack 3 scope hoisting

### ISSUE THREAD

**Issue by markogresak** [webpack/webpack#5095]
**Do you want to request a *feature* or report a *bug*?**

Bug report.

**What is the current behavior?**

This error occured when upgrading to webpack 3 and added scope hoisting using the `new webpack.optimize.ModuleConcatenationPlugin()` ([line 92 in webpack.config.js](https://github.com/markogresak/webpack-3-bug/blob/master/webpack.config.js#L92)).
When trying to build the project, app part, the one referencing the dlls, breaks with the following error:

```
ERROR in chunk js [entry]
app-[hash].js
Cannot get final name for export "default" in "delegated ./node_modules/lodash-es/_freeGlobal.js from dll-reference vendor_369f235e615c7d44cdbc" (known exports: true, known reexports: )
``` 

**If the current behavior is a bug, please provide the steps to reproduce.**

Repo reproducing the bug with steps to reproduce: https://github.com/markogresak/webpack-3-bug.

Without adding the scope hoisting plugin, it works fine, even with the webpack 3 update.
I'm not sure if there is a problem with the library or webpack itself. If there is a hack I could add to the config to avoid this error, that would work too.

**What is the expected behavior?**

The `webpack` command should not fail.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Browser version: N/A
Node version: 8.1.2
Webpack version: 3.0.0
OS: macOS Sierra 10.12.5

**Comment by gnoff** [comment]
I encountered a similar issue. Like the error suggests I am using a DLL lib and wonder if there is an incompatibility with the DLL plugin and the scope hoisting plugin

**Comment by gnoff** [comment]
seems to be an incompatibility between DLL plugin and the concat plugin. bundles just fine when not using DLL reference plugin.

**Comment by sokra** [comment]
> seems to be an incompatibility between DLL plugin and the concat plugin. bundles just fine when not using DLL reference plugin.

yep

**Comment by pangjian** [comment]
I got the same error.

**Comment by CRidge** [comment]
I got a very similar error after enabling the scope hoisting plugin:

ERROR in chunk main [initial]
[name].bundle.js
Cannot get final name for export "platformBrowserDynamic" in "delegated ./node_modules/@angular/platform-browser-dynamic/@angular/platform-browser-dynamic.es5.js from dll-reference vendor_lib" (known exports: true, known reexports: )

**Comment by ZhanYishu** [comment]
When using webpack3.0 with DLL plugin, the error accured.

**Comment by zackargyle** [comment]
Are there any leads on this? It's blocking Pinterest from upgrading as well. I might be able to help but not sure where to start.

**Comment by enapupe** [comment]
Adding `context` to  vendor `DllPlugin` solved it for me:
```
diff --git a/webpack.config.production.js b/webpack.config.production.js
index 191672a..b989861 100644
--- a/webpack.config.production.js
+++ b/webpack.config.production.js
@@ -16,6 +16,7 @@ module.exports = {
     publicPath: '/static/',
   },
   plugins: [
+    new webpack.optimize.ModuleConcatenationPlugin(),
     new webpack.DefinePlugin({
       'process.env': {
         NODE_ENV: JSON.stringify('production'),
diff --git a/webpack.config.vendor.js b/webpack.config.vendor.js
index 9ae0d0e..745506c 100644
--- a/webpack.config.vendor.js
+++ b/webpack.config.vendor.js
@@ -29,6 +29,7 @@ module.exports = {
   },

   plugins: [
+    new webpack.optimize.ModuleConcatenationPlugin(),
     new webpack.DefinePlugin({
       'process.env': {
         NODE_ENV: JSON.stringify('production'),
@@ -46,6 +47,7 @@ module.exports = {
     }),
     new webpack.DllPlugin({
       path: 'dist/[name]-manifest.json',
+      context: path.join(__dirname, 'dist'),
       name: '[name]_lib',
     }),
     new CompressionPlugin({
```

**Comment by paztis** [comment]
Same error for me in v3.1.0 without the DLL plugin, but in case of CommonsChunkPlugin for a file inside the common chunck.

**Comment by markogresak** [comment]
What @enapupe suggested worked for the repo where I've managed to reproduce the error.
The fix was to add `context` to `webpack.DllPlugin`. Note that this is the part where you define the dll plugin, do not confuse it with `webpack.DllReferencePlugin`, the part where the dll is being referenced.

**Comment by develar** [comment]
Why closed? Why context is required? 

> context (optional): context of requests in the manifest file (defaults to the webpack context.)

**Comment by develar** [comment]
@enapupe If set context to DLL dist out dir, references to node_modules will be relative. Webpack simply ignores DLL in this case (because module not found). Are your sure that your solution is working and not just masks the issue ;)?

**Comment by dexbol** [comment]
@develar I am sure the solution does work for my case.

**Comment by enapupe** [comment]
@develar @dexbol You are right, that option just made the DllPlugin to become useless. I'll edit my comment pointing that out. I don't have another solution.

**Comment by develar** [comment]
Disabling ModuleConcatenationPlugin also doesn't help. DLL works only for some module (e.g. works for vue, but doesn't work for vue-router).

**Comment by enapupe** [comment]
@markogresak You should reconsider that `context` change. Check if your bundle is indeed not including vendor stuff (it should be).

**Comment by markogresak** [comment]
@develar you are correct, this does not work as expected. @enapupe thanks for pointing that out, I was tired when trying this out and so excited when I saw the build pass I didn't analyze the output thoroughly enough. 
But I started noticing later that build times were much longer and the output size grew significantly, but after I got the same build results when removing `ModuleConcatenationPlugin` while leaving `context` in place, I thought it had something to do with my recent dependency updates, I didn't even think that `context` was causing described issue. Thanks to both @develar and @enapupe for pointing this out so I didn't lose too much time figuring this out.

I'm reopening this. Adding `context` doesn't solve the problem, as @develar pointed out it just masks the real issue.

**Comment by tomchentw** [comment]
Ran into this today. Some of my findings:

1. Our system was having `import from 'react-router'` and `import from 'react-router-dom'` at the same time, and the error message is complaining about:

```txt
Cannot get final name for export "Route" in
"delegated ../node_modules/react-router/es/index.js from dll-reference vendor"
(known exports: true, known reexports: )
```

2. And the contents of `node_modules/react-router/es/index.js` is:

```js
import _Route from './Route';
export { _Route as Route };
```

3. I suspect this bug may be related to ES2015 module re-export, so **I change all imports to `react-router-dom`** and it seems fixed the error.

The warnings by CLI arg `--display-optimization-bailout` are still exists but it finally compiles and outputs the bundle.

**Comment by enapupe** [comment]
Thanks for fixing this. I did tested v3.4.1 and it works perfectly. No code changes were necessary.
