### ISSUE TITLE
Variable name mapping issue *only* when using ModuleConcatentationPlugin

### ISSUE THREAD

**Issue by sdtsui** [webpack/webpack#5096]
_Hi WP Team, congrats on the major version bump, and thank you for all of your hard work this year! Filing this in response to a [tweet](https://twitter.com/TheLarkInn/status/876940147811647489), would be great to get ETA on docs for `ModuleConcatentationPlugin`. We're aware it's an experimental feature. Keep us posted. Thanks!_

**Do you want to request a *feature* or report a *bug*?**
`Bug`

**What is the current behavior?**
Medium sized JS app. 80k LOC, 100s of modules.
Switching Webpack `2.6.1` to `3.0.0` works fine, no issues.
Build fails when adding `ModuleConcatentationPlugin()`.

With no other configuration changes, I get the following output:
```
ERROR in chunk main [entry]
scripts.bundle.js
Cannot map to variable name in module /Users/sdt/te/frontend/src/app/domainData/api/entities/elements/index.js (export 'COMMON_HEADERS')
```

Again, this _only_ happens when adding `ModuleConcatentationPlugin`, build works fine without it.

**If the current behavior is a bug, please provide the steps to reproduce.**
[Gist](https://gist.github.com/sdtsui/3fe95e0fbd0af28c586e257ad470f449), with full config.
Uploaded [BuildOutput.txt](https://github.com/webpack/webpack/files/1086600/BuildOutput.txt).

Unfortunately, my team is on a deadline and I'm unable to provide a minimal reproduceable repo.  I'm filing this issue in hopes that someone has an idea of what might be wrong.  I've tried this >6 times with re-cloning of the repos and a restart of my machine. It's possible I've left something out and this is a simple fix.  

The best I can do is upgrade us to `3.0.0` (which doesn't break our builds), and stay on top of this issue.  If you have tips for how to create a minimal repo, let me know -- seems tough with how big our project is, I'm unsure where to start creating a failure case from a smaller repo.  I've subscribed to the issue and am happy to provide more context: thanks for your attention!

**What is the expected behavior?**
The failed mapping is an api constant (for headers) and used in over a dozen other files successfully in 2.6.1, both in prod and dev builds.  We have changed only two things: webpack version, and a one-line addition of the plugin. 

The expected behavior is to not get this error (or any other future errors), and have a successful build.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Browser Version: `Version 58.0.3029.110 (64-bit)`
Node Version: `v6.9.4`
Webpack Version: `3.0.0`
OS: `OSX Sierra, Version 10.12.4 (16E195)`

**Comment by mrdziuban** [comment]
I'm having this error as well on a default export:

```
Cannot map to variable name in module /path/to/my/file.ts (export 'default')
```

I tried putting together a quick example but was unable to reproduce it with a simple use case. Commenting here because I'm happy to provide more information if it would be helpful.

**Comment by glortho** [comment]
I have this same issue. I'm using https://github.com/jmcriffey/babel-preset-es2015-ie/blob/master/index.js. If I replace this with just the standard babel-preset-es2015 I don't get the error.

**Comment by sokra** [comment]
It would help to see how `COMMON_HEADERS` is defined.

**Comment by sdtsui** [comment]
@sokra - yep, here's where it's defined.
```
export const COMMON_HEADERS = {
  Authorization: 'Bearer XXX',
  'Content-Type': 'application/json',
  'Access-Control-Allow-Origin': 'http://localhost:5000',
};
```
It's imported in the main file via an alias: `api`.

**Comment by probablyup** [comment]
It might be worth seeing if there's a circular dependency in your project: https://www.npmjs.com/package/circular-dependency-plugin

**Comment by sdtsui** [comment]
@epoberezkin - I'm open. Can you please elaborate a little as to why you think it's a circular dep? We've dealt with it before. 

Noting again that it works in WP2, the only change is adding this plugin:
```
Switching Webpack 2.6.1 to 3.0.0 works fine, no issues.
Build fails when adding ModuleConcatentationPlugin().
```

**Comment by probablyup** [comment]
There are a lot of changes to module handling and the scope hoisting optimization is only applied to esm code I think... so a circular dep could cause a lot of trouble.

**Comment by sdtsui** [comment]
Got it, thanks. Can you suggest a way to find our potential circular deps?  To date, we've waited for errors to pop up and patched as-needed.

**Comment by probablyup** [comment]
See the plugin I linked a few comments up.

**Comment by sdtsui** [comment]
Heh, I'm a tube light. Yep, will try this tomorrow and report back. Thanks again.

**Comment by glortho** [comment]
We definitely have/need circular dependencies. I take it that just means no `ModuleConcatentationPlugin`.

**Comment by probablyup** [comment]
No one "needs" circular dependencies. ESM strict implementations won't even
allow them.

Often times it's just a matter of breaking up your files into smaller
chunks.

**Comment by probablyup** [comment]
In any case, it was just a suggestion as to a potential cause. Might not be
the root issue.

**Comment by glortho** [comment]
Well, by "need" I only mean that our app currently depends heavily on them and we won't be able to design around this requirement soon. I otherwise agree with your theoretical assertion. :-)

**Comment by sokra** [comment]
> No one "needs" circular dependencies. ESM strict implementations won't even
> allow them.

Circular dependencies are allowed by the ESM spec. Implementations that doesn't allow circular dependencies are not spec conform. webpack and also the scope hoisting plugins allows circular dependencies. At least it should, if it doesn't this is a bug.

**Comment by axelnyffenegger** [comment]
I had the same problem as well, with some circular dependencies. I've made a repository to show the bug.
https://github.com/Axnyff/reproduction.

yarn bundle (which just calls webpack produce the bug). Weirdly, if I comment at some lines in viewport-utils.js, it seems to work.

**Comment by mrdziuban** [comment]
Here's another very minimal reproduction: https://github.com/mrdziuban/webpack-variable-name. With that I get:

```
ERROR in chunk main [entry]
dist.js
Cannot map to variable name in module /Users/matt/webpack-variable-name/b.js (export 'a')
```

It seems like the issue could be a combination of circular dependencies and [referencing the `global` namespace](https://github.com/mrdziuban/webpack-variable-name/blob/master/a.js#L8-L9). I was able to fix the issue in @axelnyffenegger's repo as well by commenting out [these two lines](https://github.com/Axnyff/reproduction/blob/master/viewport-utils.js#L9-L10).

**Comment by sdtsui** [comment]
@mrdziuban - nice.  Looks like referencing `global` creates an issue as long as it's in the dep graph? i.e. Even if the doesn't matter if the variable that failed to get mapped isn't related to the `global` reference, the bug might occur?

**Comment by sdtsui** [comment]
@probablyup - found some circular dependencies, and they relate directly to the files where the failed mapping is caught.

```
ERROR in chunk main [entry]
scripts.bundle.js
Cannot map to variable name in module /Users/sdt/BlacklightProjects/te/frontend/src/app/domainData/api/entities/elements/index.js (export 'COMMON_HEADERS')

ERROR in Circular dependency detected:
frontend/src/app/domainData/entities/entities.js -> frontend/src/app/domainData/entities/pages/pages.js -> frontend/src/app/domainData/entities/entities.js

ERROR in Circular dependency detected:
frontend/src/app/domainData/entities/pages/pages.js -> frontend/src/app/domainData/entities/entities.js -> frontend/src/app/domainData/entities/pages/pages.js
```

@sokra , or anyone else on the WP team: what would be your advice for our team?  We can resolve deps to see if `ModuleConcatentationPlugin` will work, but it's a nontrivial refactor.  If there's bandwidth to fix it relatively quickly, this is also something we can wait on. Thanks!

**Comment by githoniel** [comment]
me too. the same with stdui.
the module reported is all the circular dependencies module in my project.
I think it is because of circular dependencies~~~

**Comment by Ixonal** [comment]
I just ran into this issue, but it's complaining about an export in third party code. Any suggestions in this case, since I can't really refactor it myself?

**Comment by lukeapage** [comment]
Another case that was down to circular references. After fixing the circular reference it worked fine. Strangely 3.0.0-rc1 I think did not have this bug.

**Comment by sdtsui** [comment]
Looks like this issue has some traction, and others in the community are experiencing the same thing.  

- @sokra  Any thoughts plans to add this bug to the team's backlog? 
- On my team, we're about to go to prod with a new product using the same configs. @lukeapage , do you feel staying on `3.0.0-rc1` would somehow be better? 

Thanks.

**Comment by jgf5013** [comment]
+1 Also experiencing this issue.

**Comment by TheLarkInn** [comment]
Is this something that someone could provide in a reproducible simple isolated repo? This can help us debug this much quicker and get it fixed if it is a bug.

**Comment by mrdziuban** [comment]
@TheLarkInn there have been a couple repos posted here that reproduce the issue. @axelnyffenegger posted his repo: https://github.com/webpack/webpack/issues/5096#issuecomment-310645058 and I posted mine as well: https://github.com/webpack/webpack/issues/5096#issuecomment-310675261. Do those help?
