### ISSUE TITLE
Include only parts of Buffer interface

### ISSUE THREAD

**Issue by indutny** [webpack/webpack#5097]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

Include whole `Buffer` interface: `assert`s, `base64`/`hex` encodings, `copy`, `write`, `fill`, etc.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

It would be cool if I could somehow select the features that I'm interested in, instead of pulling whole Buffer interface.

**If this is a feature request, what is motivation or use case for changing the behavior?**

Output size. `Buffer` implementation is really heavy at the moment!

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by indutny** [comment]
Same could possibly apply to `assert`.

**Comment by TheLarkInn** [comment]
This would be really nice. How would the current implementation look. Can you require only pieces of Buffer?

**Comment by indutny** [comment]
I have no idea :)
