### ISSUE TITLE
Nested tree shaking is not working at webpack@3.0.0

### ISSUE THREAD

**Issue by navarroaxel** [webpack/webpack#5100]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
The tree shaking at 2nd level is not working in webpack@3.0.0, but it's working with webpack@2.6.1.

**If the current behavior is a bug, please provide the steps to reproduce.**
Just use a code like this twice:
````javascript
if (!module.hot || process.env.NODE_ENV === 'production') {
    module.exports = require('./index.prod');
} else {
    module.exports = require('./index.dev');
}
````
The 2nd tree shaking doesn't work. You can see the issue in this repo: https://github.com/navarroaxel/webpack-tree-shaking-bug

Just run this:
````bash
git clone https://github.com/navarroaxel/webpack-tree-shaking-bug.git
cd webpack-tree-shaking-bug
yarn install
yarn run webpack
# ctrl+c to stop the bundle analyzer server
yarn add --dev webpack
#the webpack should upgrade from 2.6.1 to 3.0.0
yarn run webpack #again
````

**What is the expected behavior?**
The tree shaking should works like webpack@2.6.1.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
node@6.11.0
webpack@3.0.0

The issue affects this package [`react-hot-loader@3.0.0-beta.7`](https://www.npmjs.com/package/react-hot-loader) because the [`sourcemapped-stacktrace`](https://www.npmjs.com/package/sourcemapped-stacktrace) dependency is not removed in the production build.

**Comment by jakeNiemiec** [comment]
This also is a problem with builds by angular-cli imported via webpack.
