### ISSUE TITLE
3.0.0 gives twice the build time as 2.*

### ISSUE THREAD

**Issue by phun-ky** [webpack/webpack#5103]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
Build time for development bundle with `webpack@3.0.0.` gives me an increase (double the size) in build time. The bundle was a steady 6 seconds before, now, it's increased to 12seconds +

I think the culprit is `extract-text-webpack-plugin@2.1.2`  or `write-file-webpack-plugin@3.4.2` or most likely the `optimize-css-assets-webpack-plugin@1.3.0` plugin

**If the current behavior is a bug, please provide the steps to reproduce.**
1. upgrade webpack to latest version
2. run it on current webpack config

**What is the expected behavior?**
Equal or reduced build time

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
node@6.11.0
npm@3.10.10
ubuntu@15

**Comment by sokra** [comment]
Please investigate to find the causing plugin and file the issue there.
