### ISSUE TITLE
Error in uglifyjs-webpack-plugin after upgrading to webpack 3

### ISSUE THREAD

**Issue by doberkofler** [webpack/webpack#5107]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
The following error is shown:
core.min.js from UglifyJs
TypeError: Cannot read property 'reset' of undefined
    at D:\MyDev\ljs_app\trunk\periscope\build\node_modules\uglifyjs-webpack-plugin\dist\index.js:96:21
    at Array.forEach (native)

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
no error as when running webpack 2

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
nodejs: 6.11.0
webpack: 3.0.0
os: windows 7

**Comment by YasserKaddour** [comment]
This is caused by the usage of `uglify-js@3`instead of `uglify-js@2`, upgrading [`uglifyjs-webpack-plugin` to 0.4.6](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/releases/tag/v0.4.6) should fix the issue.

**Comment by doberkofler** [comment]
I do actually not include any uglifyjs-webpack-plugin module. Can this still be reason?

**Comment by YasserKaddour** [comment]
Yep `uglifyjs-webpack-plugin` is a dependency of webpack, and previous versions was having `uglify-js` only as a peer dependency see  https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/44 :

> I'm pretty sure this is because webpack 2.6 had "uglify-js": "^2.8.27" as a dependency, but webpack 3.0 has only "uglifyjs-webpack-plugin": "^0.4.4" as a dependency (which does NOT pull in uglify-js v2!)

**Comment by doberkofler** [comment]
@YasserKaddour Thank you. I will test this.

**Comment by bradennapier** [comment]
This does not work for me ... but i posted more context on this I think is related now that I raed this again.  It is not spreading arrays property as function arguments.

**Comment by kcjpop** [comment]
In my case uglifyjs 2.8.22 works while [2.8.29](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/blob/master/package.json#L49) causes errors. I noticed there is a `uglify-js` copy in `node_modules/uglifyjs-webpack-plugin/node_modules` and after had removed it, my build was running again.

**Comment by YasserKaddour** [comment]
I think this should be fixed in `webpack` `3.1` and `3.2`. Can anyone confirm?

**Comment by doberkofler** [comment]
@YasserKaddour Yes, it's working in 3.2. Thank you!

**Comment by cage1618** [comment]
webpack 3.5.4 and uglifyjs-webpack-plugin 0.4.6 has the same promble

**Comment by kcjpop** [comment]
@cage1618 did you try?

```
"uglifyjs-webpack-plugin": "^1.0.0-beta.2"
```

**Comment by otajor** [comment]
Had the same problem - `"uglifyjs-webpack-plugin": "^1.0.0-beta.2"` seems to be working

**Comment by cage1618** [comment]
@kcjpop Yes, I tried that, but useless
