### ISSUE TITLE
Error in uglifyjs after upgrading to webpack 3

### ISSUE THREAD

**Issue by xgszl33614** [webpack/webpack#5110]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
  
    Bundle.js generated, but uglifyjs make no sense and error

    ERROR in assets/js/app.js from UglifyJs
    Unexpected token: name (foo) [assets/js/app.js:83,4]
    Child html-webpack-plugin for "index.html":
           [0] ./node_modules/.2.28.0@html-webpack-plugin/lib/loader.js!./src/index.html 721 bytes {0} [built]
           [2] (webpack)/buildin/global.js 509 bytes {0} [built]
           [3] (webpack)/buildin/module.js 517 bytes {0} [built]
            + 1 hidden module

**If the current behavior is a bug, please provide the steps to reproduce.**
```
// webpack.config
plugins: [
  new webpack.optimize.UglifyJsPlugin(),
]

// bundle.js
...
function _asyncToGenerator(fn) { ... }
let foo = (() => { // line 83
    var _ref = _asyncToGenerator(function* () {
        return 'foo';
    });

    return function foo() {
        return _ref.apply(this, arguments);
    };
})();

let obj = foo();
obj.then(res => alert(res), res => console.log(res));

// app.js
import { foo } from './helper'
let obj = foo()
obj.then(res => console.log(res))

// helper.js
export async function foo() {
    return 'foo';
}

...
```

**What is the expected behavior?**

no error as when running webpack 2

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

nodejs: 6.10.0
webpack: 3.0.0
os: mac

**Comment by tlackemann** [comment]
Getting something very similar after upgrading from 2 -> 3.

Depending if I enable `NamedModulesPlugin` or not, I get a slightly different error.

```bash
# With NamedModulesPlugin
ERROR in index.js from UglifyJs
Unexpected token: name (CancellationToken) [index.js:18278,6]

# Without
ERROR in index.js from UglifyJs
Invalid assignment [index.js:7563,43]
```

I've tried following steps in previous threads to install `uglifyjs-webpack-plugin`, to downgrade to `uglify-js@2` but to no avail yet.

Thank you for all the hard work!

**Comment by xgszl33614** [comment]
uglifyjs can't handle es6+ syntax.  success in webpack2 just because i translate es6+ all to es5

**Comment by iansinnott** [comment]
Just ran into this as well and after a bit of searching found that the docs actually mention this limitation. In case it helps anyone else coming upon this issue check out the note about Uglify and ES6 here: https://webpack.js.org/plugins/uglifyjs-webpack-plugin/#install
