### ISSUE TITLE
ModuleConcatenationPlugin deopts on `process.*`

### ISSUE THREAD

**Issue by STRML** [webpack/webpack#5114]
This is a report of a bug/possible improvement to be made in `ModuleConcatenationPlugin`.

Currently, it deopts on code like:

```js
if (process.browser) {...}
if (process.env.NODE_ENV) {...}
```

with the following message:

```
ModuleConcatenation (inner): dependency variables are used (i. e. ProvidePlugin)
```

Any variables provided via ProvidePlugin cause a deopt, which is understandable, but what is not is that built-in vars (like `process.browser`) and values provided via `EnvPlugin` also deopt. I would have expected them to be replaced in source directly.

This is Node 6.11, Webpack 3.0.0.

**Comment by sokra** [comment]
It should not deopt on a defined `process.env.xxx var. Yes it deopts on `process`. We are aware of this and may optimize this in future versions.

**Comment by STRML** [comment]
It does deopt on `process.env.NODE_ENV` - is there a reason this was closed?
