### ISSUE TITLE
Retry failed async chunk requests

### ISSUE THREAD

**Issue by sebastianseilund** [webpack/webpack#5115]
Thanks for all of your great work!

**Do you want to request a *feature* or report a *bug*?**

Request a feature

**What is the current behavior?**

Async chunks (through `import()`) failing to load due to fx intermittent network issues or server-side 5xx errors causes `Loading chunk <id> failed` errors.

**If the current behavior is a bug, please provide the steps to reproduce.**

It's not a bug, but all you need to see this error is:

- Navigate to a page that uses code splitting and async chunks.
- Turn off your network in DevTools
- Click a link that causes an async chunk to load.

**What is the expected behavior?**

The same, but maybe retrying the request would be possible?

**If this is a feature request, what is motivation or use case for changing the behavior?**

We see in our logs that async chunks sometimes fail to load. It's hard to tell exactly why, but since the user already had all the other assets loaded I assume that it's due to either the CDN failing or the user's network being temporarily unreliable.

Would it be possible to retry the chunk requests a few times before giving up?

If this is something you're interested in, I'd be happy to submit a PR.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Webpack 2.6.1

**Comment by sokra** [comment]
`import()` returns a promise. You can implement retry logic on top of this.

**Comment by sebastianseilund** [comment]
Thanks! I see now that`onScriptComplete` will clear the chunk's promise from `installedChunks` if the chunk fails to load. 👍

**Comment by keningharryscom** [comment]
Hi @sokra,

I wonder if webpack has a default retry behavior? When I use Charles Proxy's rewrite feature to simulate a trunk load failure (I just return status code=500 for a specific trunk), I see in my dev tool network panel that specific trunk is actually loaded 3 times (and because of the Charles Proxy rewrite, all 3 times fail, and eventually stop there, show the ` Loading chunk XXX failed.` error in the console). I search the webpack code and can not figure out where is the code that's making it try to load the trunk up to 3 times.

Thanks!

**Comment by fresk-nc** [comment]
I sometimes have invalid cache because of `ERR_CONTENT_DECODING_FAILED`, seems like some troubles with CDN. It would be great if webpack would have an option like `chunkRetryCount: 1` or something like that. But I also need to change failed chunk's URL like this `${chunkURL}?nocache=${Date.now()}` to bypass invalid cache.

@sokra what do you think about it?

**Comment by fresk-nc** [comment]
Maybe it can help https://github.com/mattlewis92/webpack-retry-chunk-load-plugin

**Comment by fresk-nc** [comment]
But even if do not pay attention to some of the shortcomings of this plugin, I still have the same problem with https://github.com/webpack-contrib/mini-css-extract-plugin

**Comment by rsshilli** [comment]
> import() returns a promise. You can implement retry logic on top of this.

I wish I knew what this meant. Anybody have a code sample? Is there some way in webpack to retry 500 errors?  AWS S3 is pretty good but once in a blue moon coughs up a 500 error and our tests fail.  I'd love it if webpack could retry any give load a second time.

**Comment by andycarrell** [comment]
Hi @rsshilli I've just been looking into this too, and I found this code sample
https://dev.to/goenning/how-to-retry-when-react-lazy-fails-mb5
Hope it helps :)

**Comment by simeyla** [comment]
I'll never understand why as a community (that's the entire web community) we don't seem to collectively care about this.

Whether it's Angular, webpack, [esbuild](https://github.com/evanw/esbuild/issues/2130) or the browsers themselves. Everyone points fingers but then makes excuses and it doesn't amount to anything. With dozens of chunks often needed for an initial page load and increase framework support for lazy / deferred loading of components the problem isn't getting any better. Consider a user that loads an Angular site with a defered component, get into an elevator as they're still scrolling and the page just breaks. We're ok with that?

I'm starting to think it's ultimately better for browsers to handle this and not the responsibility of every framework / bundler to come up with their own mechanism. But more than anything I just don't understand why nobody seems to care about it. 

And then five years from now someone will finally write the 50 lines of code needed to implement this and make a big fuss over how great a feature it is - and I'll just be here silently shaking my head wondering why we didn't already have it five years ago.
