### ISSUE TITLE
Babili not working in 3.0.0

### ISSUE THREAD

**Issue by bradennapier** [webpack/webpack#5116]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
uglify js breaks spread operator in webpack3 only.  I am assuming at the moment it is uglify as I can disable it and things appear to start working.  I am still llooking into the details.

```js
const r = Object.keys(selected).reduce((...args) => {
    console.log(args.length); // 4
    handleProcessReduction(selected, ...args);
  }, {});

function handleProcessReduction(selected, ...args) {
  console.log('p: ', args.length); // 1
} 
```

I can see it is not doing the right thing:

```js
return Object.keys(e).reduce(function() {
            for (var r = arguments.length, t = Array(r), n = 0; n < r; n++)
              t[n] = arguments[n];
            console.log(t.length), u.apply(void 0, [e, t]); // [e, t] not [e].concat(t)?
          }, {});
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

When using previous versions it would output with a concat and would work fine.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Noting #5110 and #5107 -- I thought they were different but looking deeper it appears it's the entire problem.  Updating webpack doesnt work because uglify is breaking spread operation in function arguments.  All of those errors appear to be due to the arguments not being there because they all get added to the first argument.

**Update** oops - meant babili not uglify

**Comment by bradennapier** [comment]
Not using babili and switching back to uglify fixes this.

**Comment by sokra** [comment]
report this to the babili plugin/loader.
