### ISSUE TITLE
Webpack 3 and babel-polyfill issue at runtime

### ISSUE THREAD

**Issue by gyandeeps** [webpack/webpack#5118]
_Thanks for Webpack 3. its really awesome._

**Do you want to request a *feature* or report a *bug*?**

**Bug**

**What is the current behavior?**

* Build is fine.
* At runtime I get the following error

```sh
Uncaught ReferenceError: regeneratorRuntime is not defined
    at Object.<anonymous> (bundle.js:3325)
    at __webpack_require__ (bundle.js:20)
    at bundle.js:63
    at bundle.js:66
```

* As per `babel-polyfill` docs, I use `import "babel-polyfill";` inside [my entry file on top](https://github.com/gyandeeps/webpack3-issue/blob/master/src/index.js).

**If the current behavior is a bug, please provide the steps to reproduce.**

Repro repo with steps: https://github.com/gyandeeps/webpack3-issue

* Maybe this is not an issue with webpack and we have to change on how we consume `babel-polyfill`.
* I wanted to share this issue here to see what can be done.
* I am thinking other people might have this issue.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Node: 8
OS: Windows 7
Webpack: 3.0.0

**Comment by Lanchez** [comment]
Works without ModuleConcatenationPlugin so I guess polyfills are thrown out?

**Comment by rgrwkmn** [comment]
I wasn't able to reproduce the issue, but you could try loading babel-polyfill via the exports in your webpack config. 

```javascript
module.exports = {
  entry: ["babel-polyfill", "./app/js"]
};
```

https://babeljs.io/docs/usage/polyfill/

**Comment by tkachukivan** [comment]
I have this problems with other polyfills when ModuleConcatenationPlugin is added to my webpack config

**Comment by danny-andrews** [comment]
Ran into a similar issue today. Build runs fine, but at runtime we get:
```
Uncaught TypeError: Object(...) is not a function
   at isFunction (vendor.js:70746)
   at baseIsNative (vendor.js:70856)
   at getNative (vendor.js:70891)
   at Object.<anonymous> (vendor.js:70900)
   at __webpack_require__ (vendor.js:55)
   at Object.1371 (app.js:57)
   at __webpack_require__ (vendor.js:55)
   at Object.1370 (app.js:14)
   at __webpack_require__ (vendor.js:55)
   at webpackJsonpCallback (vendor.js:26)
```
Here's the offending code:
```js
function isFunction(value) {
  if (!lodash_es_isObject(value)) {
    return false;
  }
  // The use of `Object#toString` avoids issues with the `typeof` operator
  // in Safari 9 which returns 'object' for typed arrays and other constructors.
  var tag = Object(_baseGetTag["a" /* default */])(value);
  return tag == funcTag || tag == genTag || tag == asyncTag || tag == proxyTag;
}
```
Somehow `Object` isn't a function!?

Ever weirder, this happened to two of my coworkers, but I could not reproduce. Seems like some indeterminate shenanigans or something.

**Comment by the-spyke** [comment]
I probably have a similar issue. I have `babel-preset-env` and `babel-polyfill` (import is on the top of the entry file). If `devtool` option set to `any` value, but `false`/`eval`, it starts missing some polyfills. For example, with `eval` source map a have `Promise.prototype.finally()` in my browser. And if I change source maps to `eval-source-map`, I'll get an error `.finally` is not a function.

I had no such issue with `babel-preset-2016`, and adding `babel-polyfill` to entries in Webpack's config fixes the issue for me.

Any thoughts?

**Comment by sm1990** [comment]
I'm having a similar issue as well. I'm using webpack 3.10.0 and the runtime error I'm getting is below.

```
bundle.js:737 Uncaught Error: Cannot find module "babel-polyfill"
    at webpackMissingModule (bundle.js:737)
    at Object.<anonymous> (bundle.js:737)
    at __webpack_require__ (bundle.js:679)
    at bundle.js:725
    at bundle.js:728
```
I'm not using ModuleConcatenationPlugin(). Any thoughts on how to fix this issue. Thanks in advance :)

**Comment by evilebottnawi** [comment]
Problem on `babel` side and already solve in `7` version, please update babel, also `webpack@3` deprecated so it will be great if you update `webpack` too, thanks!
