### ISSUE TITLE
Getting `Unexpected token import` error for dynamic import

### ISSUE THREAD

**Issue by dineshvgp** [webpack/webpack#5123]
I use enzyme & jest for executing tests.
Even though I use `syntax-dynamic-import` plugin, I am still getting the token error when I execute tests.

But, When I build the code, I didn't get any error.

This is how my **.babelrc** looks,
```
{
  "presets": ["es2015","react"],
  "plugins": ["transform-object-rest-spread", "syntax-dynamic-import"]
}
```

**Comment by dineshvgp** [comment]
Fixed it by using this [plugin](https://github.com/airbnb/babel-plugin-dynamic-import-node)

**Comment by rommguy** [comment]
Thanks @dineshvgp !

**Comment by IzaGz** [comment]
@dineshvgp how you fixed it? 
i got
`require('babel-register')({
  plugins: ["transform-decorators-legacy", "dynamic-import-node"],
  presets: ['es2015', 'stage-0', 'react'],
  // ignore: /scss/,
  extensions: [".es6", ".es", ".jsx", ".js"]
});
`

> ReferenceError: Unknown plugin "dynamic-import-node" specified in "base" at 1, attempted to resolve relative to
