### ISSUE TITLE
Pass Source Maps by default in custom loaders

### ISSUE THREAD

**Issue by donaldpipowitch** [webpack/webpack#5125]
**Do you want to request a *feature* or report a *bug*?**

*feature*

**What is the current behavior?**

If you write a custom loader you need to pass source maps explicitly, so they don't get lost.

**What is the expected behavior?**

It would be nice, if source maps are always passed by default and that you explicitly need to "remove them", if you really want to.

**If this is a feature request, what is motivation or use case for changing the behavior?**

It seems to be too easy to create bugs (https://github.com/Va1/string-replace-loader/issues/18) with this behaviour which can be easily avoided (https://github.com/Va1/string-replace-loader/pull/28).

**Comment by sokra** [comment]
It's not passed by default, because it's not correct to pass the source map along. i. e. in you PR instead of passing the SourceMap along you should better update the SourceMap with the string replacement made in the loader. Otherwise positions doesn't match.

**Comment by donaldpipowitch** [comment]
Okay, but this is _another_ improvement IMHO. Currently the source maps are broken for every file and with my PR they are broken only for where this loader really replaces code and it's "okay" for small replacements (like `_import()` -> `import()`).
