### ISSUE TITLE
module.hot.accept does not accep dependency in the middle of the update chain

### ISSUE THREAD

**Issue by miraage** [webpack/webpack#5128]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Console is populated with next messages, accepted callback is not invoked.

> Ignored an update to unaccepted module ./modules/ep-auth/components/LoginPage/LoginPage.js -> ./modules/ep-auth/components/LoginPage/index.js -> ./modules/ep-auth/components/index.js -> ./modules/ep-auth/index.js -> ./Root/Root.js -> ./Root/index.js -> ./index.js -> 0
> [HMR] The following modules couldn't be hot updated: (They would need a full reload!)
> [HMR]  - ./modules/ep-auth/components/LoginPage/LoginPage.js

**If the current behavior is a bug, please provide the steps to reproduce.**
```js
const components = [
  './modules/ep-auth/components/index.js',
  './modules/ep-core/components/index.js',
  './modules/ep-users/components/index.js',
];

module.hot.accept(components, () => {
  console.log('run');
});
```

**What is the expected behavior?**
Dependency is accepted and callback is invoked.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Chrome, Node.js, webpack, OSX - latest stable versions.

**Comment by sokra** [comment]
module.hot.accept does not accept a dynamic argument. Inline the list of files into the call.

**Comment by miraage** [comment]
Absolutely same behavior when I pass array directly as first parameter.

**Comment by Kelerchian** [comment]
Up and request reopen.
This happens to me too, on the server side, when I call it as `module.hot.accept("./appjs", callback)`.
The passed callback simply isn't invoked.
