### ISSUE TITLE
DefinePlugin only works on initial compilation and not on changes when webpack is run with --watch

### ISSUE THREAD

**Issue by westerp** [webpack/webpack#5129]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

When using `webpack --watch` the first time around DefinePlugin replaces instances of the keys in the code, but after an edit and recompilation it does not.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Pass any variable in with DefinePlugin and use it in the code. eg `{MY_INJECT : '"INJECT"'}`
2. Run with `--watch`
3. See that `MY_INJECT` it gets replaced with `"INJECT"`
4. make any edit that triggers recompilation
5. See that `MY_INJECT` is not replaced and it gives a Reference error when running the bundle

**What is the expected behavior?**

That `MY_INJECT` always gets replaced with `"INJECT"` in the resulting dist. 

**If this is a feature request, what is motivation or use case for changing the behavior?**
N/A

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

node: v7.10.0
webpack: 2.6.1 (also does not work with 3.0.0)

**Comment by hitmands** [comment]
is your code similar to: 
```javascript
{
  plugins: [
    new webpack.DefinePlugin({
      MY_INJECT: JSON.stringify('INJECT')
    })
  ]
}
```

**Comment by westerp** [comment]
Yes. That should reproduce the bug the second time around with `--watch`

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by westerp** [comment]
This is so embarrassing. I notice that when I made a next to nothing version the compilation worked and thus I removed node_modules and run yarn to make sure every package was in line with my package.json and then magically this bug didn't show anymore. I'm sorry for wasting your time. Closing the issue.
