### ISSUE TITLE
Scope hoisting does not work in case if there is multiple entry points

### ISSUE THREAD

**Issue by standy** [webpack/webpack#5134]
**Do you want to request a *feature* or report a *bug*?**
`Bug`

**What is the current behavior?**
With mutiple entry points scope hoisting feature does not working

**If the current behavior is a bug, please provide the steps to reproduce.**
Minimal reproduceable repo: https://github.com/standy/webpack-scope-hoisting-multiple-entry  

Here scope hoisting does not work:
```javascript
module.exports = {
    entry: {
        pageA: "./src/pageA",
        pageB: "./src/pageB"
    },
...
}
```
With same modules, but array of config each with single entry point works fine:
```javascript
module.exports = [
    {entry: {pageA: "./src/pageA"}, ...},
    {entry: {pageB: "./src/pageB"}, ...}
]
```

**What is the expected behavior?**
Multiple entry points should have scope hoisting

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Webpack 3.0.0

**Comment by sokra** [comment]
Yes it's not working perfectly with multiple entry points. It would be too difficult to fix, so won't fix for now.
