### ISSUE TITLE
Base64 hashes in filenames should be URL-safe

### ISSUE THREAD

**Issue by kgram** [webpack/webpack#5136]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When using `output.hashDigest = 'base64'`, hashes can contain `/` and `+`. Both will probably work (at least the slash will), as they will be handled the same way by webservers as filesystems. But it certainly isn't pretty when your full bundle path suddenly is `/public/main.B/0sK5.js`.

**If the current behavior is a bug, please provide the steps to reproduce.**

Because of the random nature of the issue, I don't have a simple way to reproduce it.

**What is the expected behavior?**

URL-safe base64 should be used. This can be achieved by replacing `+` with `-` and `/` with `_`. See https://en.wikipedia.org/wiki/Base64#URL_applications. This should probably be done everywhere base64 can be used as hash encoding.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by swernerx** [comment]
What about just going to base62 which is actually exactly that, file system safe. 💯

**Comment by kgram** [comment]
Maybe we should just get node to support arbitrary bases, then there would be no limits. I can't wait to base37 encode me som data!

**Comment by Kronuz** [comment]
Maybe webpack should use `loaderUtils.interpolateName`?

**Comment by tigt** [comment]
I think this might already be supported if you pass `'base64url'` to `hashDigest`:

> The encoding to use when generating the hash. All encodings from Node.JS' [`hash.digest`](https://nodejs.org/api/crypto.html#crypto_hash_digest_encoding) are supported.
> 
> —[Output | webpack § `output.hashDigest`](https://webpack.js.org/configuration/output/#outputhashdigest)

> `'base64'` - Base64 encoding. When creating a Buffer from a string, this encoding will also correctly accept "URL and Filename Safe Alphabet" as specified in [RFC 4648, Section 5](https://tools.ietf.org/html/rfc4648#section-5).
>
> —[Node.js docs § Buffers and Character Encodings](https://nodejs.org/api/buffer.html#buffer_buffers_and_character_encodings)

> This encoding may be referred to as "base64url". This encoding should not be regarded as the same as the "base64" encoding and should not be referred to as only "base64".
>
> —[RFC 4648 § Base 64 Encoding with URL and Filename Safe Alphabet](https://tools.ietf.org/html/rfc4648#section-5)

**Comment by tigt** [comment]
Whoops, looks like not quite. Node transparently *consumes* base64url if passed in for a `Buffer`, but [they’re unsure if they should implement producing it as well](https://github.com/nodejs/node/issues/26512).
