### ISSUE TITLE
Webpack 3 breaks at runtime when using `import *`

### ISSUE THREAD

**Issue by STRML** [webpack/webpack#5138]
**Do you want to request a *feature* or report a *bug*?**

This is a bug report with a reproduction at https://github.com/STRML/webpack-3-scope-hoisting-bug. 

Node 6.11, Webpack 3. The bug can be easily reproduced.

When using `module.strictThisContextOnImports` (required to work around [#5135](https://github.com/webpack/webpack/issues/5135) and others),
imported `const`s from other modules are not properly referenced when calling a function on a namespace
referred to by an `import *`.

This bug only seems to manifest under these conditions:

* `module.strictThisContextOnImports: true`,
* A constant must be imported from another file,
* That constant must be used in a function referenced on an `import * from`.

The output:

```js
"use strict";
Object.defineProperty(__webpack_exports__, "__esModule", { value: true });

// CONCATENATED MODULE: ./constants.js
const constants_FOO = 'BAR';

// CONCATENATED MODULE: ./functions.js
function print(str) {
  console.log(str);
}

// CONCATENATED MODULE: ./index.js
function init() {
  console.log(constants_FOO)
  print(FOO);
}
```

Notice that the `print` call is referring to `FOO`, not `constants_FOO`.

If we are using the `CommonsChunkPlugin` or split in such a way that `constants` becomes another module,
the `console.log()` line will properly use the imported constant, but the `print()` will not, e.g.:

```js
console.log(__WEBPACK_IMPORTED_MODULE_10_constants__["f" /* FOO */]);
print(FOO);
```

`FOO` is of course not defined in this instance and this will fail at runtime.

See the reproduction at https://github.com/STRML/webpack-3-scope-hoisting-bug.

**Comment by lee-houghton** [comment]
I have also seen this issue when using a default import as well as named imports, if it's any help.

Example:
```
import App from "core/app"; 
import * as WidgetService from "components/widget-service";

export function f() {
    WidgetService.fetchWidgets((err, data) => {
        const foo = App.someProperty;
    });
}
```

The reference to App.someProperty in the output is left as App.someProperty instead of  `__WEBPACK_IMPORTED_MODULE_4_core_app__.default.someProperty`.

**Comment by sokra** [comment]
This should be fixed
