### ISSUE TITLE
Error by default on dynamic requires

### ISSUE THREAD

**Issue by fresheneesz** [webpack/webpack#514]
Webpack should error on dynamic requires unless the user gives a specific list (in the options) of files that dynamic requires should pick from. I wasted a good 2 days trying to figure out why my bundle builder was having memory issues, just to find out webpack was trying to shove my entire backend into the frontend bundle.

@jhnns 
https://github.com/webpack/webpack/issues/496

**Comment by fresheneesz** [comment]
@sokra Is there currently a way to disable dynamic requires via the configuration?

**Comment by sokra** [comment]
http://webpack.github.io/docs/configuration.html#automatically-created-contexts-defaults-module-xxxcontextxxx

**Comment by fresheneesz** [comment]
Oh great! Thanks!

**Comment by fresheneesz** [comment]
@sokra Could the dependency parser be made to be just a tad smarter for dynamic requires? I would think it should be possible to track where a function is called (at least in simple cases) and if that function is only called with constants, the resulting constant requires can be the only ones that are bundled. 

Example:
```
requireSomething('a')

function requireSomthing(theThing) {
   return require(theThing)
}
```

It should be possible to recognize that requireSomething is *only* called once with the require-path 'a'. Webpack could then translate this into a bundle without causing a require cascade. That should be possible in simple cases right? It could then fall back to its usual paranoid "bundle the world" behavior for other cases.

**Comment by fresheneesz** [comment]
From another thread, this helped me avoid moment.js's dynamic requires:

```module: {
  noParse: [/moment.js/]
}
```

**Comment by fresheneesz** [comment]
Also I just noticed that the info at the link you gave me doesn't actually help disable dynamic requires. I added the following to my config:

```
module: {
    // Disable handling of unknown requires
    unknownContextRegExp: /$^/,
    unknownContextCritical: false,

    // Disable handling of requires with a single expression
    exprContextRegExp: /$^/,
    exprContextCritical: false,

    // Warn for every expression in require
    wrappedContextCritical: true
  }
```

But I'm still seeing `moment.js`'s external languages in my bundle.

**Comment by fresheneesz** [comment]
Looks like `new webpack.ContextReplacementPlugin(/.*$/, /NEVER_MATCH^/)` does the trick.

**Comment by fresheneesz** [comment]
@sokra Was this added in or rejected?
