### ISSUE TITLE
Webpack 3 failed on shrinkwrap because of peer invalid error

### ISSUE THREAD

**Issue by iroy2000** [webpack/webpack#5141]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
After upgrade to webpack 3, my repo failed on `shrinkwrap` because of `peer invalid`

And I have created a github branch for testing

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/iroy2000/react-redux-boilerplate/tree/upgrade-to-webpack-3

Try to run 

`npm i` and `npm shrinkwrap`

**What is the expected behavior?**

It should not fail on shrinkwrap or the built just works without peer invalid or unmet

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

OS: Mac 10.12
Node: v6.10.1
npm: 3.10.0

**Comment by sokra** [comment]
webpack has no peerDependencies. You should report this to the package with the invalid peer dependency.
