### ISSUE TITLE
Illegal Folder Creation

### ISSUE THREAD

**Issue by ChrisTalman** [webpack/webpack#5143]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
Webpack creates an illegal folder in Windows 10, named `...`, in some circumstances.

**If the current behavior is a bug, please provide the steps to reproduce.**
Below is a `webpack.config.js` which should reproduce the bug.

```JavaScript
'use strict';

const path = require('path');

module.exports =
{
    entry: './src/app.ts',
    resolve:
    {
        extensions:
        [
            '.js',
            '.html',
            '.css',
            '.ts'
        ]
    },
    output:
    {
        filename: 'bundle.js',
        path: '/.../test'
    },
    watch: true,
    watchOptions:
    {
        ignored: /node_modules/
    }
};
```

**What is the expected behavior?**
Webpack should throw an error, as, so far as I am aware, it is illegal to have a folder in Windows named `...`.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Not applicable.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Webpack: 3.0.0.
Node: 7.8.0.
Operating System: Windows 10 Pro 10.0.15063 Build 15063.

**Comment by sokra** [comment]
Why do you try to call it `...`?

**Comment by ChrisTalman** [comment]
@sokra I started using Webpack recently, and I initially attempted to use relative paths before realising that they were not allowed. During this learning process, for one reason or another, a slash appeared in front of the dots and the rest is history. However, I think the key thing is that this is an illegal folder name, which it should not have been possible for me to have accidentally created. Quite frankly, I'm surprised that Windows allowed it to happen, let alone Webpack.

**Comment by sokra** [comment]
windows behavior is really very weird when you create a folder with this name, but I don't think we (as webpack) should prevent this. node.js is the better place to handle this, since this affects all node.js packages.

But I guess this won't be handled since "this is how the windows API works". node.js only pass fs access to the windows API.
