### ISSUE TITLE
Issue requiring npm module Joi that depends on other npm modules

### ISSUE THREAD

**Issue by charandas** [webpack/webpack#515]
I am running into this case probably because of my specific projector dir structure.

``` bash
. <project-dir>
 -- server
   -- webpack.config.js
   -- node_modules
   -- package.json
 -- app
    -- lib
    -- js
```

My webpack config is:

``` js
// webpack.config.js
var webpack = require('webpack');
var path = require('path');

module.exports = {
    entry: path.join(__dirname, '../app/js/main.js'),
    output: {
        path: path.join(__dirname, '../app/bundle'),
        publicPath: '/app/bundle/',
        filename: 'bundle.js'
    },
    resolve: {
        modulesDirectories: [
           path.join(__dirname, 'node_modules')
        ],
        root: [
            path.join(__dirname, '..', 'app', 'lib'),
            path.join(__dirname, '..', 'app', 'js'),
            path.join(__dirname, '..', 'app', 'themes'),
        ],
        alias: {
            // a bunch removed for brevity
        }
    },
    resolveLoader: {
        root: [
            path.join(__dirname, 'node_modules')
        ]
    },
    module: {
        loaders: [
            // a bunch removed for brevity
        ]
    }
};
```

I have issues using [`joi`](https://github.com/hapijs/joi) in my build. I `npm install` it and try to `require` it. My configuration `modulesDirectories: [ path.join(__dirname, 'node_modules')]` helped `webpack` find `joi` but it cannot find depended-upon modules (`hoek`, `topo`, `isemail`) from its [package.json](https://github.com/hapijs/joi/blob/master/package.json) (or its own nested `node_modules` dir).

Am I expected to expand my `modulesDirectories` variable, or should modules from nested `node_modules` be requireable automagically?

**Comment by jonjaques** [comment]
For anybody landing here with Joi / webpack problems. The problem I had was related to internal node modules `dns` and `net`. Adding `node-libs-browser` and the following to my config did the trick.

```
node: {
  dns: 'mock',
  net: 'mock'
}
```

**Comment by Norm-** [comment]
@jonjaques

Webpack handles the mocking without having to install node-libs-browser. Just the config suffices.

@sokra

What are you suggesting for the modules where a mock isn't provided? 

```javascript
exports.child_process				= null;
exports.cluster						= null;
exports.dgram						= null;
exports.dns							= null;
exports.fs							= null;
exports.module						= null;
exports.net							= null;
exports.readline					= null;
exports.repl						= null;
exports.tls							= null;
```

Interestingly enough, mocking `tls` seems to work. Bundling doesn't complain about not finding it anymore. However, `fs` I can't mock.

Any help is appreciated.

p.s. using 1.12.11
