### ISSUE TITLE
loader is not executed in dependency of dependency

### ISSUE THREAD

**Issue by Fuzzyma** [webpack/webpack#5152]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

loader is ignored when module is not required directly from entry file

**If the current behavior is a bug, please provide the steps to reproduce.**

I use `js-aruco` which is browser only. To shim it, I created 2 modules:

```js
// module cv.js
module.exports = require('exports-loader?CV!../js-aruco/src/cv.js')
// module ar.js
module.exports = require('exports-loader?AR!imports-loader?CV=./cv.js!../js-aruco/src/aruco.js')
```

In my app I require the ar-module

```js
var AR = require('modules/ar.js')
```

However - in the bundled code, no export for the cv module is added.
When I require the cv module directly from my entry, I end up with the code of the cv-module TWICE in the bundled file - one with export and one without. However, ar still does not find it because it tries to load the broken version

PS: An export for the ar module is added correctly

**What is the expected behavior?**

the loader should get executed for cv.js. Currently it just gets ignored.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

webpack 3.0.0
win7
node 6.10.3

PS: My webpack config consists of entry and output - so nothing special there

**Comment by sokra** [comment]
The imports-loader is relative to the decorated file.

`imports-loader?CV=./cv.js`
`imports-loader?CV=modules/cv.js`

**Comment by Fuzzyma** [comment]
That dies not fix it. Instead webpack complains about that it cant find the module. cv.js and ar.js are both in the modules. So it already was relative to the decorated file. So or so: The import loader should at least do something on this directive. I looked into the loader and loged which files are recognised and it just doesnt get executed in my case
