### ISSUE TITLE
Dynamic import behavior is inconsistent with static import

### ISSUE THREAD

**Issue by jkrems** [webpack/webpack#5153]
**Do you want to request a *feature* or report a *bug*?**

This is a bug.

**What is the current behavior?**

The following should always be true for ES6 modules but right now it may evaluate to false when using webpack:

```js
import X1 from 'x';
import('x').then(ns => ns.default === X1); // should always be Promise.resolve(true)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

The following repo contains an example: https://github.com/jkrems/webpack-dynamic-import/blob/master/import-compare.js

This only seems to happen when the imported module was written as a CommonJS module.

You can run it via `npm install && npm test`.

**What is the expected behavior?**

Importing the default export using dynamic- and static import should always evaluate to the same value.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

```
> node --version
v6.11.0

> webpack --version
3.0.0
```

**Comment by sokra** [comment]
Can you point me to the spec speccing the CJS interop for `import()`?

**Comment by jkrems** [comment]
@sokra Not sure what you mean. This isn't related to CJS interop per se. It's an invariant in the module spec that isn't dependent on anything else.

**Comment by jkrems** [comment]
*Note: this seems to be addressed in webpack 4.*
