### ISSUE TITLE
"!" in project path. ERROR in Entry module not found.

### ISSUE THREAD

**Issue by starikan** [webpack/webpack#5154]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

A simple example from the documentation "./node_modules/.bin/webpack src/index.js dist/bundle.js" does not work if project path contain "!". Like "P:\Folder\!DEV\Project".

Path "P:\Folder\DEV\Project" work well.

Webpack 3.0.0
Win10x64

**Comment by pierreneter** [comment]
Don't use `!` in path. See: https://stackoverflow.com/a/26875327

**Comment by ppeterka** [comment]
@pierreneter What if I have to?

**Comment by sokra** [comment]
We can't fix it. Sorry
