### ISSUE TITLE
Webpack should not modify bundles on disk unless changed

### ISSUE THREAD

**Issue by alubbock** [webpack/webpack#5157]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Webpack emits (overwrites) files even if they are unchanged. This updates the file modification time and can break caching mechanisms.

**If the current behavior is a bug, please provide the steps to reproduce.**
I think any webpack config will do this, but I can provide a specific example if needed.

**What is the expected behavior?**
Webpack should check whether the created bundle hash and filename matches the one on disk, and not emit the bundle if so.

**If this is a feature request, what is motivation or use case for changing the behavior?**
HTTP servers will send the file modification date to the client, which can use it for a conditional GET request. I appreciate that setting long cache times combined with hashes in the filename partially solve this issue, but supporting conditional GET would be useful too.

I also move bundles to my web server using [Django's `collectstatic` functionality](https://docs.djangoproject.com/en/1.11/ref/contrib/staticfiles/), which relies on file modification dates. This means that all of the emitted bundles are copied even if their contents has not changed.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Webpack 3.0.0

**Comment by kambing86** [comment]
any update on this? if not then I will write a plugin for this

**Comment by alubbock** [comment]
I'm not aware of any update that fixes this, but a plugin would be a great help.

**Comment by kambing86** [comment]
check this
https://github.com/kambing86/ignore-unchanged-webpack-plugin

feel free to contribute based on your needs

**Comment by alubbock** [comment]
Thanks @kambing86, that seems to do the job! Only caveats I've found are:

* Source maps are still emitted by `SourceMapDevToolPlugin` (not much of a problem, since they're only for developers)
* Compressed assets are still emitted by `CompressionPlugin`, but this can be corrected by setting `cache: true`

Since this plugin covers my needs, I'll close the issue. Thanks for creating the plugin!
