### ISSUE TITLE
output.pathinfo results in invalid javascript

### ISSUE THREAD

**Issue by SebastianS90** [webpack/webpack#5158]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When using the `output.pathinfo` option then the added comment might end early due to `*/` and the asset therefore is not valid javascript anymore.

**If the current behavior is a bug, please provide the steps to reproduce.**
```javascript
const babelConfig = {
    presets: [
        ['es2015', {modules: false}],
    ],
    plugins: [
        ['istanbul', {exclude: '**/node_modules/**'}],
    ],
};

module.exports = {
    // ...
    module: {
        rules: [
            {
                test: /\.vue$/,
                loader: 'vue-loader',
                options: {
                    loaders: {
                        js: 'babel-loader?' + JSON.stringify(babelConfig),
                    },
                },
            }
```

Now I get the following in my compiled asset:
```javascript
  __webpack_require__(/*! !babel-loader?{"presets":[["es2015",{"modules":false}]],"plugins":[["...",{"exclude":"**/node_modules/**"}]]}!../../../../node_modules/vue-loader/lib/selector?type=script&index=0!./Component.vue */ 13),
```
Note that the comment is interrupted because of the occurrence of `*/`

**What is the expected behavior?**
Comment must not contain `*/`.
Could be fixed [here](https://github.com/webpack/webpack/blob/v3.0.0/lib/dependencies/ModuleDependencyTemplateAsId.js#L12)

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Webpack 3.0.0

**Comment by pierreneter** [comment]
Why do you use `exclude: '**/node_modules/**'`? Try: `exclude: /node_modules`

**Comment by pierreneter** [comment]
Why do you use `exclude: '**/node_modules/**'`? Try: `exclude: /node_modules/`

**Comment by SebastianS90** [comment]
@pierreneter I want to override the [default](https://github.com/istanbuljs/nyc/blob/master/README.md#excluding-files):
> Note: exclude defaults to `['test', 'test{,-*}.js', '**/*.test.js', '**/__tests__/**', '**/node_modules/**']`, which would exclude `test`/`__tests__` directories as well as `test.js`, `*.test.js`, and `test-*.js` files. Specifying your own exclude property overrides these defaults.

I guess the stars are needed for istanbul to properly match the `node_modules` folder.

**Comment by pierreneter** [comment]
That is `exclude` of the `nyc`, it's not `webpack`. You can try use: `exclude: /node_modules/` and see this works or not. and go back here

**Comment by SebastianS90** [comment]
You are aware that I'm passing an `exclude` option to the istanbul babel plugin via my webpack configuration file? It's not an option for webpack itself.

**Comment by pierreneter** [comment]
Have you tried `exclude: /node_modules/` yet?

**Comment by pierreneter** [comment]
Please, notice, `nyc` use `micromatch` for exclude paths, but `webpack` is not!
And, the `exclude defaults` above, it follow `micromatch` format.

**Comment by SebastianS90** [comment]
I don't have that problem any more with latest `vue-loader`, as the options are no longer passed as query string.
