### ISSUE TITLE
webpack-dev-server hot-only arg ignored

### ISSUE THREAD

**Issue by benwiley4000** [webpack/webpack#5161]
This is about an issue [already reported in webpack-dev-server](https://github.com/webpack/webpack-dev-server/issues/877), but it seems like the optimal fix lies here in webpack land. I can submit a PR to fix.

**Do you want to request a *feature* or report a *bug*?**

I'd say a bug, but depends on how you look at it.

**What is the current behavior?**

WebpackDevServer supports a `--hot-only` argument which is like `--hot` but uses `webpack/hot/only-dev-server` instead of `webpack/hot/dev-server`.

The problem is we currently ***also*** need to pass `--hot` for this to work as expected, since webpack, which handles processing of arguments for adding the `webpack.HotModuleReplacementPlugin` instance, doesn't recognize `--hot-only`. This contradicts [the documentation which speaks of `--hot-only` as an *alternative* to `--hot`](https://webpack.js.org/configuration/dev-server/#devserver-hotonly-cli-only).

**What is the expected behavior?**

If `--hot-only` is passed then we shouldn't need to pass `--hot` for HMR to work.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Latest webpack - 3.0. Latest webpack-dev-server - 2.5.

In my mind the best solution is to check for both `--hot-only` and `--hot` in [`webpack/bin/convert-argv.js`](https://github.com/webpack/webpack/blob/57825153e531a079eb0dbd2528e47f4cbafcc7f2/bin/convert-argv.js#L385) and run the same function for both. Agreed?

Though it also might be worth considering whether this devserver-related configuration belongs in the webpack package proper.

**Comment by sokra** [comment]
@webpack-bot move to webpack/webpack-dev-server

> Though it also might be worth considering whether this devserver-related configuration belongs in the webpack package proper.

yes I think you are right here. This doesn't belong into webpack core.

webpack-dev-server can implement a hack here: It can add `argv.hot = true` when `argv["hot-only"]` is used.
