### ISSUE TITLE
[BUG] Multiple loader order on same file while in watch mode

### ISSUE THREAD

**Issue by diydyq** [webpack/webpack#5162]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**

In my script js with following content:
// Same file "file.txt" will be processed by different loaders, to generate 2 kinds of data
var ret1 = require("loader11!loader0!./file.txt")
var ret2 = require("loader21!loader0./file.txt")

When run "webpack --watch"，the loader execute order for same file.txt is: 
loader0, loader11, loader0, loader21;

But when I modified file.txt, the execute order is another: 
loader0, loader0, loader11, loader21

Because I modified data in loader11, and save data in loader0; then second loader0 will use the saved data.

But in the second loader execute order, I could not do this, because loader0 is always before loader11.

How can I resolve this problem?

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by sokra** [comment]
Order is not deterministic. Don't rely on it. It's called in parallel.
