### ISSUE TITLE
output.filename [file] is not working

### ISSUE THREAD

**Issue by xhlwill** [webpack/webpack#5164]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
I set output.filename to [file].js and came out ERROR: Path variable [file] not implemented in this context

**If the current behavior is a bug, please provide the steps to reproduce.**
I had two entry and wanted to custom the filenames
```
entry: {
    A: './main.js',
    B: './beta.js'
  },
output: {
    path: path.resolve(__dirname, './dist'),
    filename: '[file].bundle.js',
    library: ['[name]']
  },
```

**What is the expected behavior?**
output: main.bundle.js beta.bundle.js

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
webpack: 2.6.1
node.js: 6.10.1
OS: mac

**Comment by RamYadlapalli** [comment]
Instead of [file] just use [name]. So config might look something like below 
entry: {
    bundle: "./App"
  },
  output: {
    filename: "[name].js",
    path: path.resolve(__dirname, "dist"),
    publicPath: "/"
  }
Which will generate bundle.js in dist

**Comment by xhlwill** [comment]
@RamYadlapalli @sokra  the expected behavior: main.bundle.js beta.bundle.js, why [file] not working
![image](https://user-images.githubusercontent.com/14025269/27825066-fcb156da-60e0-11e7-862f-832278af6907.png)
