### ISSUE TITLE
resolve module in manifest.json when add the DllReferencePlugin

### ISSUE THREAD

**Issue by monkindey** [webpack/webpack#5166]
If I missed something, Please let me know.

### **Do you want to request a *feature* or report a *bug*?**

feature

### **What is the current behavior?**

* I have the manifest and the bundled dll js which include React, React-dom etc.
* I want to use it for other project, and copy them to the other project.
* my src wrote by

   ```js
   const React = require('react')
   ```
   and **not npm install react lib** because I configure the dll plugin in my webpack.config.js.

* But when I run the webpack cli and it throw the `Can't find module react` error

### **If the current behavior is a bug, please provide the steps to reproduce.**

No

### **What is the expected behavior?**

I think webpack will find the react in manifest for me, because I had the react source in the bundled dll js, I didn't need to npm install react in my new project.

### **If this is a feature request, what is motivation or use case for changing the behavior?**

It will save a lot of node module in my project, I just use the manifest.json and bundled dll js.
I trace the webpack src, [enhanced-resolve](https://github.com/webpack/enhanced-resolve) will look up file system and throw error when the file not exist, But It would be awesome if the webpack.config.js include the dllReferencePlugin and the webpack also find the module in the manifest.json and get the module id in the bundled dll js.

### **Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

* MacBook
* Webpack3
* Node 8

Thanks

**Comment by pksjce** [comment]
Have you tried using `externals` parameter? 
It is described better at https://webpack.js.org/configuration/externals/
It might help you access `React` even though it is not in your `node_modules`

**Comment by monkindey** [comment]
Thanks for your reminding, The externals seem not work for the manifest. It may not search the lib in the manifest config. I write the plugin to cheat the webpack that this module have be resolved.

```js
const fakers = ['react', 'react-dom', 'moment'];
const manifestMap = {
  react: 'react.js',
  'react-dom': 'index.js',
  moment: 'moment.js'
};

class FakeResolvePlugin {
  apply(resolver) {
    resolver.plugin('file', (request, callback) => {
      let theFaker = '';
      if (
        fakers.some(f => {
          if (new RegExp(`${f}$`).test(request.path)) {
            theFaker = f;
            return true;
          } else {
            return false;
          }
        })
      ) {
        request.path = path.join(
          __dirname,
          `node_modules/${theFaker}/${manifestMap[theFaker]}`
        );

        resolver.doResolve(
          'existing-file',
          request,
          'existing file: ' + request.path,
          callback,
          true
        );
        return callback();
      }

      return callback();
    });
  }
}
```

**Comment by sokra** [comment]
yes it would be nice.

**Comment by monkindey** [comment]
I think the bot is not smart enough yet. Maybe we should not close the issue has the `feature` and `enhancement` label ?
