### ISSUE TITLE
Error: Can't resolve 'module' in '/app/node_modules/webpack/lib'

### ISSUE THREAD

**Issue by karneaud** [webpack/webpack#5168]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
Module not found: Error: Can't resolve 'module' in '/app/node_modules/webpack/lib'
**If the current behavior is a bug, please provide the steps to reproduce.**
* use the starter kit repo provided
* run a docker compose with mhart/alpine-node:8.1.2
* yarn install which in turn runs node ./webpack-configs/build.js

https://github.com/jaredpalmer/presspack

**What is the expected behavior?**
Should install and start browser-sync server
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
macOS
latest docker
 mhart/alpine-node:8.1.2 image
yarn install v0.24.6
node 8.1.2
npm 5

**Comment by sokra** [comment]
To complex to reproduce...

Try `stats: {errorDetails: true}` resp. `--display-error-details` to see more info.

**Comment by ghostCoder** [comment]
@sokra how did you fix this?

**Comment by boatcoder** [comment]
Pretty sure @sokra didn't fix it.  He tossed out a comment and closed it.....

**Comment by PiTiLeZarD** [comment]
Too bad, I'm having the exact same issue now :/
