### ISSUE TITLE
Array.from(mySet) crashes - cannot assign to read only property 'length' of function (3.0.0)

### ISSUE THREAD

**Issue by eemt** [webpack/webpack#5170]
**Do you want to request a *feature* or report a *bug*?** bug

**What is the current behavior?** 
runtime crash: 
```
Uncaught TypeError: Cannot assign to read only property 'length' of function 'function from() { [native code] }'
at Function.from
```
When converting a set to an array with Array.from().  The crash appears to be on this line:
`result.length = index;`

**If the current behavior is a bug, please provide the steps to reproduce.**
These two lines of javascript code crash on the second line with the above error on Chrome.
```
const mySet = new Set(['a','b','c']);
const myArr = Array.from(mySet);
```

**What is the expected behavior?**
The set should successfully convert to an array. This works okay in regular javascript on a browser and prior versions of webpack, but not on the webpack 3.0.0 built javascript.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
WebPack:  3.0.0
Node: 6.10.2
Windows: 7 SP1
Browser: Chome 58
Firefox 54 - crashes into debugger.
IE 11 - reports a similar error

**Comment by wegry** [comment]
Looks like a dupe of #5135. Are you using the ModuleConcatenationPlugin?

**Comment by eemt** [comment]
We are not using ModuleConcatenationPlugin. 
I agree it is a dup of #5135
