### ISSUE TITLE
consider using krisselden/fast-source-map or something like it

### ISSUE THREAD

**Issue by MagicDuck** [webpack/webpack#5171]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
source-map library is antequated and slow + consumes tons of memory. 

**If the current behavior is a bug, please provide the steps to reproduce.**
**What is the expected behavior?**
fast sourcemaps

**If this is a feature request, what is motivation or use case for changing the behavior?**
For larger projects, sourcemap generation is really a large chunk of the total time webpack spends compiling. Having faster sourcemap generation would help with faster builds/incremental builds.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

The library here seems like an interesting alternative:
https://github.com/krisselden/fast-source-map
According to their benchmarks, they are 10x faster than source-map.

**Comment by sokra** [comment]
@webpack-bot move to webpack/webpack-sources
