### ISSUE TITLE
commonsChunkPlugins troubles with code splitting

### ISSUE THREAD

**Issue by Dictory** [webpack/webpack#5172]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Troubles with chunks and commonsChunkPlugins.

**If the current behavior is a bug, please provide the steps to reproduce.**
I have 2 entry:
```javascript
main: `${appPath}/startup/LightApp`
vendor: [
  'babel-polyfill',
  'core-js',
  'object-assign',
  'immutable',
  'react',
  'react-dom',
  'react-redux',
  ...
]
```
1) If i doesn\`t use commonsChunkPlugins - webpack build 2 files: `main.js` and `vendor.js` **but** both files contain modules from 'vendor'
2) if use commonsChunkPlugins:
```javascript
new webpack.optimize.CommonsChunkPlugin({ names: ['vendor', 'manifest'] })
```
Now `main.js` exclude `vendor` modules.
Finish? No. Let\`s try split to another chunk:
```javascript
const detectChunk = function(targets) {
  return function(module, count) {
    var context = module.context;
    return context && context.indexOf('node_modules') >= 0 &&
      targets.find(t => new RegExp(`/${t}/`, 'i').test(context));
  }
}
...
new webpack.optimize.CommonsChunkPlugin({
  name: 'draft-js',
  minChunks: detectChunk(['draft-js', 'draft-convert', 'draft-js-plugins-editor']),
})
```
1) Without CommonsChunkPlugin for `vendor` that work (remember about multiple includes modules)
2) With CommonsChunkPlugin that doesn\`t work. Just empty `draft-js.js` file.

**Last**

Use in code
```javascript
import(/* webpackChunkName: "my-component-chunk" */ 'MyComponent')
.then((Component) => { this.setState({ Component }); })
```
webpack config:
```javascript
new webpack.optimize.CommonsChunkPlugin({
  children: true,
  async: true,
})
```
Nope, webpack include that to `main`, no special chunk.

**What is the expected behavior?**

Logic with normal code splitting =)

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

macOS Sierra 10.12.5, node v7.8.0, webpack 3.0.0

I just want build superfast app with your brilliant webpack.

**Comment by vinogradov** [comment]
Try your setup with webpack 2, maybe it is just a bug in webpack 3. This article  https://webpack.js.org/guides/caching/ worked for me and webpack **2**.

**Comment by Dictory** [comment]
@vinogradov only vendor work for me. I told about three and more chunks. And about dynamic import.

**Comment by Dictory** [comment]
About last point, dynamic import - that my bad, **all imports will be dynamic**. Nothing will work if someone import will be directly.
