### ISSUE TITLE
Use of Promise.reject() in hot reloading code triggers Chrome debugger on every save

### ISSUE THREAD

**Issue by gaearon** [webpack/webpack#5175]
**Do you want to request a *feature* or report a *bug*?**

An unfortunate issue.

**What is the current behavior?**

Every time you save a file and hot update is not possible, Webpack calls `Promise.reject()` with hot update abort. Unfortunately this pauses Chrome debugger if "break on exceptions" is `true`. And even if the Promise will get caught, Chrome debugger can't know it.

The issue is described in:

* https://github.com/facebookincubator/create-react-app/issues/1880
* https://bugs.chromium.org/p/chromium/issues/detail?id=465666

**If the current behavior is a bug, please provide the steps to reproduce.**

Toggle "break on exceptions" in Chrome.
Save a file with hot reloading enabled but not `accept` handlers.
It will pause here.

![](https://cloud.githubusercontent.com/assets/810438/26559692/22532818-44a9-11e7-8e40-4620f4345cd5.png)

This is very annoying for every edit.

**What is the expected behavior?**

Somehow, on either Chrome or Webpack side, we need to figure out how to avoid pausing on every refresh. Or how to blacklist this particular rejection. Neither Chrome nor Webpack seem to provide a workaround for this.

cc @paulirish

**If this is a feature request, what is motivation or use case for changing the behavior?**

Fast iteration.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Happening with Webpack 2+. macOS, Chrome stable.

**Comment by rafde** [comment]
isn't this an issue for https://github.com/webpack/webpack-dev-server/issues ?

**Comment by gaearon** [comment]
This code lives in Webpack repo. I'm not sure if it's fixable on Webpack side anyway but wanted to raise awareness.

**Comment by sokra** [comment]
I guess we can fix it this way:

https://github.com/webpack/webpack/blob/master/lib/HotModuleReplacement.runtime.js#L231

Instead of this:

``` js
			hotApply(hotApplyOnUpdate).then(function(result) {
				deferred.resolve(result);
			}, function(err) {
				deferred.reject(err);
			});
```

``` js
			Promise.resolve().then(function() {
				return hotApply(hotApplyOnUpdate);
			}).then(function(result) {
				deferred.resolve(result);
			}, function(err) {
				deferred.reject(err);
			});
```

This calls hotApply on the next micro task tick and a reject handler is attached.

Does somebody want to do a PR and test if my assumptions are correct.

**Comment by engmyahya** [comment]
@gaearon @sokra 

I faced also : 

![image](https://user-images.githubusercontent.com/12251024/34198038-51d6f1f8-e582-11e7-8b0b-7dea294e6697.png)

And my fix was to install latest webpack and webpack-dev-server , as followed : 
`npm install webpack@latest --save`
`npm install webpack-dev-server@latest --save`
