### ISSUE TITLE
webpackChunkName bug

### ISSUE THREAD

**Issue by lemonleon** [webpack/webpack#5177]
**Do you want to request a *feature* or report a *bug*?**
this is a bug for magic comment

**What is the current behavior?**
chunkFilename is wrong

**If the current behavior is a bug, please provide the steps to reproduce.**
webpack.conf.js
```javascript
...
output: {
        path: path.resolve('./dest/'),
        filename: '[name].js',
        chunkFilename: 'chunk-[name].js'
    },
module: {
        rules: [
            {
                test: /\.js$/,
                loader: 'babel-loader',
                exclude: /node_modules/,
                include: path.resolve('./src/abc') // if './bcd' || './xxx', it will be ok
            }
        ]
    }
...
```
project structure
```javascript
|--src
    |--abc
        |--async.js
        |--entry.js
```
entry.js
```javascript
import(/* webpackChunkName: "async" */ './async');
```
if webpack.conf.js  module.rules.include the same as project structure， chunkFimename will be wrong,
otherwise it will be ok

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
os: win7
nodejs: 4.3.0
webpack: 2.6.1 || 3.0.0

**Comment by lemonleon** [comment]
I found the cause of the problem ：）

**Comment by atodd** [comment]
@lemonleon Will you please detail what the cause and solution to the problem were?

**Comment by lemonleon** [comment]
Hi @atodd, this problem is caused by the configuration of the .babelrc.
When you set "comments": false in .babelrc, will cause what I said above. And if you not set it, the problem won't happen.

**Comment by atodd** [comment]
Thanks @lemonleon!  I never would have found that.

**Comment by jesujcastillom** [comment]
Am I doing something wrong here?

**webpack.conf.js**

```javascript
output: {
    path: path.resolve(__dirname, 'dist'),
    filename: 'bundles/[name].[hash].js',
    publicPath: '/',
    chunkFilename: "[name].js"
  }
```

**routes.js (angularjs)**

```javascript
{
      state: 'account.**',
      url: '/account',
      lazyLoad: ($transition$) => {
        let $ocLazyLoad = $transition$.injector().get('$ocLazyLoad');
        return import(/* webpackChunkName: "account" */ '../modules/account/account.module.js').then(loadedModule => $ocLazyLoad.load(loadedModule.ACCOUNT_MODULE))
      }
    }
```

And I'm getting:
![captura de pantalla 2017-10-06 a la s 15 46 25](https://user-images.githubusercontent.com/7827281/31293444-96f6ab1c-aaad-11e7-8a88-2ae97d7e68b0.png)
