### ISSUE TITLE
npm run build fails after updating to Webpack 3 and adding a plugin to my config

### ISSUE THREAD

**Issue by EddyVinck** [webpack/webpack#5179]
Hi,
I am relatively new to Webpack and JavaScript bundlers and things like Babel, so please excuse my noobiness. I was following [this article on Medium](https://medium.com/webpack/webpack-3-official-release-15fd2dd8f07b) and I am running into problems. (In fact, I set up Webpack 2 for the first time the weekend before I read this article.)

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
`npm run build` fails after updating to webpack 3 and adding:  (on a side note: why can't I just enter `webpack` like some people can?)
```
plugins: [
    new webpack.optimize.ModuleConcatenationPlugin()
  ]
```
to my webpack configuration file.

**If the current behavior is a bug, please provide the steps to reproduce.**

My old config:
```
var path = require('path');

module.exports = {
	entry: './src/index.js',
	output: {
    	filename: 'bundle.js',
    	path: path.resolve(__dirname, 'dist')
	},
	module: {
	rules: [{ 
  	test: /\.js$/, exclude: /node_modules/, loader: "babel-loader" 
  		}]
	}
};
```
My new (broken) config:
```
var path = require('path');

module.exports = {
	entry: './src/index.js',
	output: {
    	filename: 'bundle.js',
    	path: path.resolve(__dirname, 'dist')
	},
	module: {
	rules: [{ 
  	test: /\.js$/, exclude: /node_modules/, loader: "babel-loader" 
  		}]
	},
	plugins: [
    new webpack.optimize.ModuleConcatenationPlugin()
  	]
};
```
**What is the expected behavior?**
It should run. I'm not even using scope hoisting yet I think, so I don't know why it would fail.

**If this is a feature request, what is motivation or use case for changing the behavior?**
it's not

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Node v7.9.0
Webpack v3 (although the `webpack -v` command doesn't work)
Windows 10
[debug log](https://gist.github.com/EddyVinck/6533a2d24f775653e6961386e9ae08fd)

If I somehow broke any of the rules here please let me know.

**Comment by ChrisRast** [comment]
Hi, I have the same issue.
Which version of npm do you run ? (Use `npm -v` to know.)
For me the issue appeared after I updated to npm@5.0.4.
It was working fine with webpack 3 and npm@4.6.1.
---
MacOsX 10.10.5
Node 6.4.0
npm 5.0.4
webpack 3.0.0

**Comment by sokra** [comment]
Are you using `es2015` babel preset with `modules: false` option?

**Comment by ChrisRast** [comment]
Yes I do.
But why does this issue appear with different version of npm? 😮

**Comment by sokra** [comment]
npm can't execute the `webpack` command. It's probably not installed. `npm i webpack --save-dev`
