### ISSUE TITLE
ModuleConcatenationPlugin interference with hash calculation

### ISSUE THREAD

**Issue by klis87** [webpack/webpack#5184]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If I change a content of a file that is part of ```app-entry-1``` for example, ```chunkhash``` is not calculated correctly. I could change the file and ```chunkhash``` would stay the same. If I remove 
```ModuleConcatenationPlugin``` from plugins, then it works like it should.
```
const webpack = require('webpack');
const CommonsChunkPlugin = require('webpack/lib/optimize/CommonsChunkPlugin');
const WebpackMd5Hash = require('webpack-md5-hash');

const plugins = [
  new webpack.DefinePlugin({
    'process.env': {
      NODE_ENV: JSON.stringify('production'),
    }
  }),
  new webpack.NamedModulesPlugin(),
  new webpack.NamedChunksPlugin(),
  new CommonsChunkPlugin({
    name: 'vendor',
    minChunks(module) {
      return module.context && module.context.indexOf('node_modules') !== -1;
    }
  }),
  new CommonsChunkPlugin({
    name: 'app-common',
    chunks: ['app-entry-1', 'app-entry-2', 'app-entry-3'],
    minChunks: 2
  }),
  new CommonsChunkPlugin({
    name: 'manifest',
  }),
   new WebpackMd5Hash(),
   new webpack.optimize.ModuleConcatenationPlugin()
];

module.exports = {
  context: __dirname,
  entry: {
    'app-entry-1': './ui/app-entry-1',
    'app-entry-2': './ui/app-entry-2',
    'app-entry-3': './ui/app-entry-3'
  },
  output: {
    filename: 'js/[name].[chunkhash].js',
    chunkFilename: 'js/[chunkhash].js',
    path: __dirname + '/dist/',
    publicPath: '/static/'
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        include: [
          __dirname + '/ui'
        ],
        loader: 'babel-loader',
        options: {
          presets: [
            ['latest', {
              es2015: {
                modules: false
              }
            }],
            'stage-0',
            'react'
          ]
        }
      }
    ]
  },
  devtool: 'source-map',
  plugins
};

``` 
**If the current behavior is a bug, please provide the steps to reproduce.**
Use ```ModuleConcatenationPlugin``` and check that ```chunkhash``` is always different for different content of your modules.

**What is the expected behavior?**
```ModuleConcatenationPlugin``` shouldn't interfere at all with hash calculation.

**If this is a feature request, what is motivation or use case for changing the behavior?**
N/A

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Browser unrelated issue, Node 8.1.2, Webpack 3.0.0, Mac OS X.

**Comment by sokra** [comment]
don't use the webpack-md5-hash plugin

**Comment by klis87** [comment]
Only for this case or generally it is not needed anymore? I added this because according to some blog posts content hash wasn't calculated in a deterministic way in pure Webpack, but maybe this was already solved in recent Webpack versions?

**Comment by fresk-nc** [comment]
I have the same problem, but I don't use the webpack-md5-hash plugin

**Comment by fresk-nc** [comment]
Node v8.1.2, Webpack 3.0.0, Mac OS 10.12.3

config:
```
const path = require('path');
const webpack = require('webpack');

const srcPath = path.join(__dirname, 'client');
const distPath = path.join(__dirname, 'dist');

module.exports = {
    context: srcPath,
    entry: {
        index: './a.js'
    },
    output: {
        filename: '[chunkhash]-[name].js',
        path: distPath
    },
    module: {
        rules: [
            {
                test: /\.js$/,
                use: [ 'babel-loader' ],
                include: [ srcPath ]
            }
        ]
    },
    plugins: [
        new webpack.optimize.CommonsChunkPlugin({
            name: 'manifest',
            minChunks: Infinity
        }),
        new webpack.optimize.ModuleConcatenationPlugin()
    ]
};
```

structure:
```
|-client
|--a.js
|--b.js
```
a.js
```
import b from './b.js';

b();

const sum = (a, b) => a + b;

sum(10, 10);
```
b.js
```
export default function() {}
```

I change `sum(10, 10)` to `sum(10, 5)`, but chunkhash doesn't change.

**Comment by twhid** [comment]
Be nice to re-open this because it doesn't appear to be the webpack-md5-hash plugin causing the issue. Like @fresk-nc, we're not using that plugin but have had chunkhash collisions. 

One thing that is similar to @fresk-nc's example in our configs is that we're using the `CommonsChunkPlugin` to produce a manifest bundle. Perhaps there that is the root of the issue?
