### ISSUE TITLE
Simple suggestion: can we use "smart" eqeqeq of eslint?

### ISSUE THREAD

**Issue by blade254353074** [webpack/webpack#5185]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

Now, comparing against `null` or `undefined` need:

```js
typeof foo === 'undefined' && foo === null
```

**If this is a feature request, what is motivation or use case for changing the behavior?**

We could change the eslint rules:

`"eqeqeq": "error"` => `"eqeqeq": "smart"`

> The "smart" option enforces the use of === and !== except for these cases:
>
> * Comparing two literal values
> * Evaluating the value of typeof
> * Comparing against null

More detail: [eqeqeq - Rules - ESLint - Pluggable JavaScript linter](http://eslint.org/docs/rules/eqeqeq#smart)

That could make source code more simple.

```js
foo == null
// It's equal to (typeof foo === 'undefined' && foo === null)
```

**Comment by sokra** [comment]
What's the benefit?

For me this looks like this makes the codebase more inconsistent.

**Comment by blade254353074** [comment]
All right, just a little suggestion.
