### ISSUE TITLE
SourceMap don't link to an src file but to webpack-internal:///[LINE_NUMBER]

### ISSUE THREAD

**Issue by FlorianBurgevin** [webpack/webpack#5186]
**Do you want to request a *feature* or report a *bug*?** bug

**What is the current behavior?**
Javascripts errors not link to my source file in the debug console of chrome.
I recently migrate from webpack 1 to 3.

![image](https://user-images.githubusercontent.com/6703118/27692287-9bfc52b6-5ce6-11e7-91f6-51cd3fd73b64.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Instead of angular.js/10a4:14525 or instead of webpack-internal:///... I should have a link to my source file.
For example here: /src/app/components/series.js

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

This is my webpack config.

    return {
        entry: {
            common: "./public/src/app/common.js",
            app: "./public/src/app/app-module.js"
        },
        output: {
            path: __dirname + '/public/dist', //path to where webpack will build your stuff
            publicPath: isBuild ? "/dist/" : "http://" + devDomain + ":" + devPort + "/dist/", //path that will be considered when requiring your files
            filename: "[name].bundle.js"
        },
        resolve: {
            modules: [
                path.join(__dirname, "public/src"),
                "node_modules"
            ]
        },
        devtool: 'cheap-eval-source-map',
        devServer: {
            contentBase: 'public/',
            host: devDomain,
            port: 9000,
            historyApiFallback: true,
        },
        module: {
            rules: [
                {
                    test: /\.js$/,
                    exclude: [
                        path.resolve(__dirname, "node_modules")
                    ],
                    use: [
                        {
                            loader: 'babel-loader'
                        }
                    ]
                },
                {
                    test: /\.scss$/,
                    exclude: [
                        path.resolve(__dirname, "node_modules")
                    ],
                    use: isBuild ? ExtractTextPlugin.extract({
                        use: [
                            {loader: 'css-loader', options: {sourceMap: true}},
                            {
                                loader: 'postcss-loader',
                                options: {
                                    sourceMap: true,
                                    options: postcssConfig
                                }
                            },
                            {loader: 'sass-loader', options: {sourceMap: true}},
                            {
                                loader: 'sass-resources-loader',
                                options: {
                                    resources: './public/src/app/styles/variables.scss',
                                },
                            }
                        ]
                    }) : [
                        {loader: 'style-loader'},
                        {loader: 'css-loader', options: {sourceMap: true}},
                        {
                            loader: 'postcss-loader',
                            options: {
                                sourceMap: true,
                                options: postcssConfig
                            }
                        },
                        {loader: 'sass-loader', options: {sourceMap: true}},
                        {
                            loader: 'sass-resources-loader',
                            options: {
                                resources: './public/src/app/styles/variables.scss',
                            },
                        }
                    ]
                },
                {
                    test: /\.css$/,
                    use: isBuild ? ExtractTextPlugin.extract('css-loader') :
                        [
                            {loader: 'style-loader'},
                            {loader: 'css-loader', options: {sourceMap: true}},
                        ]
                },
                {
                    test: /\.html$/,
                    loader: "html-loader"
                },
                {
                    test: /\.(png|svg|jpg|gif)$/,
                    use: [
                        {
                            loader: 'url-loader',
                            options: {
                                limit: 8192,
                                name: "[hash].[ext]"
                            }
                        }
                    ]
                },
                {
                    test: /\.(woff|woff2|eot|ttf|otf)$/,
                    use: [
                        'file-loader'
                    ]
                }
            ],
        },
        plugins: [
            new webpack.ProvidePlugin({
                "window.jQuery": "jquery"
            }),
            new webpack.optimize.CommonsChunkPlugin({
                name: 'common'
            }),
            new ExtractTextPlugin("[name].bundle.css"),
            new webpack.DefinePlugin({
                __PRODUCTION__: env.isprod
            }),
            new webpack.ContextReplacementPlugin(/moment[\/\\]locale$/, /en|fr|ru|es|de/),
            new SWPrecacheWebpackPlugin(SW_PRECACHE_CONFIG),
        ]
    }

**Comment by sokra** [comment]
Stack Traces doesn't handle Source Maps (SourceMaps are handled by browser devtools).

**Comment by sokra** [comment]
In `eval-**-source-map` devtools you get a `webpack-internal://[module-id]:[line]:[column]`. In other devtools you get a url pointing to the bundle file.

**Comment by Volcano-Yang** [comment]
get！
