### ISSUE TITLE
HMR not working with webpack loader

### ISSUE THREAD

**Issue by ccoffey** [webpack/webpack#5187]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
Hot module reloading (HMR) does not work with a webpack loader ([entry-loader](https://github.com/eoin/entry-loader)) and I do not understand why.

**If the current behavior is a bug, please provide the steps to reproduce.**
I have created a **[minimal not working example](https://github.com/ccoffey/react-hot-boilerplate)** by forking **react-hot-boilerplate** and adding one extra commit which illustrates the bug i.e. hot reloading stops working after this commit. 

I created another **[minimal not working example](https://github.com/ccoffey/react-hot-loader-minimal-boilerplate)** this time by forking **react-hot-loader-minimal-boilerplate**.

Both examples show the same behavior, hot loading fails after my commit.

**What is the expected behavior?**
Hot reloading should work with or without this commit.

**If this is a feature request, what is motivation or use case for changing the behavior?**
This is not a feature request.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
node -v: v7.0.0
npm -v: 3.10.8
webpack version: ^2.2.1
Operating system: OS X
Browser and version: Chrome Version 58.0.3029.110 (64-bit)

In my minimal not working example, I have inlined the source from [entry-loader](https://github.com/eoin/entry-loader). I have already reached out to the author but they do not understand why this is happening anymore than I do.

**Edit:** Added a second minimal example project.

**Comment by sokra** [comment]
The entry-loader creates a nested compilation, which doesn't seem to break HMR for some reason. I guess this can be supported somehow and it's only a minor change to make it work, but this would require long investigation and have low priority since it's a rar use case.

**Comment by ccoffey** [comment]
>> I guess this can be supported somehow and it's only a minor change to make it work.

If thats true, can you please point me in the right direction? HMR would be a huge win for my projects developer experience.
