### ISSUE TITLE
Feature Request: Make the plugin API play nicely with type systems.

### ISSUE THREAD

**Issue by chriseppstein** [webpack/webpack#5190]
**Do you want to request a *feature* or report a *bug*?**

Feature.

**What is the current behavior?**

The webpack tappable hooks are generic and have complex APIs that can't be type checked when using TypeScript's `@types/webpack` module. This means that IDE features like intellisense are basically useless and I have to read source code or documentation to know what's expected.

**What is the expected behavior?**

If there were two functions per hook it would allow typed environments ensure that events are fired with the right arguments and handled by handlers that expect the right arguments. Also, together with code documentation generators, this would provide a systematic way to document all plugin hooks and their arguments.

**If this is a feature request, what is motivation or use case for changing the behavior?**

I've been doing this in my code and it's really nice:

```ts
class Foo extends Tapable {
  onBar(handler: (barArg: string) => void) {
    this.plugin("bar", handler);
  }
  notifyBar(barArg: string) {
    this.applyPlugins("bar", barArg);
  }
}
```

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Webpack 3.0

**Comment by sokra** [comment]
Is't this possible to type via function overloads?
