### ISSUE TITLE
[enhancement] ModuleConcatenationPlugin - drop webpack bootstrap if possible

### ISSUE THREAD

**Issue by Andarist** [webpack/webpack#5191]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

Single file bundles using ModuleConcatenationPlugin still using so called webpack bootstrap (50~ lines of code) + wrapping the exported module within a single module-closure (numbered `0`).

**What is the expected behavior?**

Omit the current behaviour whenever possible - therefore going closer towards the Rollup behaviour.

**If this is a feature request, what is motivation or use case for changing the behavior?**

Being a viable alternative to rollup when bundling libraries.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

webpack3

Besides the mentioned information I would like to offer my help with implementing this, a helping hand would be great though, im webpack internals noobie ;)

Also rollup handles cjs modules way more gracefully (hoists them!), should I create other issue for this?

**Comment by TheLarkInn** [comment]
Thanks for the submission and I'd be happy to guide you. 

As a primer to the architecture, here is a video you might find very very informative: https://www.youtube.com/watch?v=4tQiJaFzuJ8&app=desktop

The first half will teach you about plugins, how they work, and the 8 important classes in webpack that you can write plugins for. 

In this specific case we are talking about the MainTemplate instance which is the V in MVC for rendering the webpack bootstrap information.

**Comment by Andarist** [comment]
Thanks for the comprehensive video. I dont have time to start working on this right away and on the full speed, but I definitely want to work on this and I'm gonna be back here with questions ;)

**Comment by sokra** [comment]
Yes this is planned, but has no high priority yet.

I added it as item to the voting page: https://webpack.js.org/vote/

**Comment by Andarist** [comment]
@sokra I'll try to implement it when I have time, need to explore the architecture first a little bit. At the moment im focused on some other PRs Ive started for other projects.

**Comment by mzgoddard** [comment]
@Andarist here is a experimental plugin I made a bit ago that could help you implement this. https://github.com/mzgoddard/extract-bootstrap-webpack-plugin

**Comment by Andarist** [comment]
@mzgoddard thanks! Ill definitely take a look

**Comment by Andarist** [comment]
Unfortunately I got occupied in a lot of other OSS work and had no chance to come back to this one as it's only a small optimization anyway - that doesn't matter I wouldn't like to see it implemented one day, but have no time to do it right now myself.

**Comment by Andarist** [comment]
> Unfortunately I got occupied in a lot of other OSS work and had no chance to come back to this one as it's only a small optimization anyway - that doesn't mean I wouldn't like to see it implemented one day, but have no time to do it right now myself.

**Comment by vankop** [comment]
Should work with `webpack@next` (mode=production). Feel free to report new issue with reproducible repo.
