### ISSUE TITLE
ModuleConcatenationPlugin prevents --watch or dev-server from tracking the correct files for changes

### ISSUE THREAD

**Issue by nlutterman** [webpack/webpack#5195]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

When including the `ModuleConcatenationPlugin` while using either the webpack-dev-server or --watch, inside `summarizeDependencies()` ([webpack/lib/Compilation.js:1109](https://github.com/webpack/webpack/blob/master/lib/Compilation.js#L1107)), the `fileDependencies` are not fleshed out fully, as the tree of modules required is already concatenated.

When `summarizeDependencies()` iterates through the modules and checks each module's file dependency, adding it to the compilations list of file dependencies, the concatenated module's file, and thus its children, do not end up being included.

I believe the issue lies around [webpack/lib/Compliation.js:1130](https://github.com/webpack/webpack/blob/master/lib/Compilation.js#L1130) and forward.  

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Create a project with a single entry point, but a tree of imported modules
2. Apply the `webpack.optimize.ModuleConcatenationPlugin()` to the config.plugins[] array,
3. Run webpack --watch
4. Observe that the watch starts correctly, but does not observe file changes of any modules inside the tree

**What is the expected behavior?**
All files included in the concatenated module are watched when using `webpack --watch` or the webpack-dev-server.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Windows 10
Node v8.1.3
webpack 3.0.0

Thanks!

**Comment by nlutterman** [comment]
A temporary solution at the moment is to just remove the ModuleConcatenationPlugin from the list of plugins in your webpack config.

**Comment by rafde** [comment]
I don't think it's ideal to have that plugin enabled while you are using watch or dev-server since it does a lot of work to try to figure out what to tree shake. It seems like is a plugin best used for production builds.

**Comment by sokra** [comment]
fixed by https://github.com/webpack/webpack/pull/5137
