### ISSUE TITLE
[Feature Request] Handle external missing in runtime. (Or make a guarantee before bootstrap)

### ISSUE THREAD

**Issue by mc-zone** [webpack/webpack#5197]
**Do you want to request a *feature* or report a *bug*?**
Feature, or discuss first.

**What is the current behavior?**
Assume there are some Dll or CommonChunks file, we usually put it in HTML script:
```html
<script src="./dll/common.bundle.js"></script>
<script src="./commonChunk.bundle.js"></script>
<script src="./entry.bundle.js"></script>
```

Once the `entry.bundle.js` was loaded, the code will be launched and believe other runtime external dependencies(dll, commonChunk) are already exist.

**If this is a feature request, what is motivation or use case for changing the behavior?**

### What if the previous script load failed? 

They may fail to load due to enter the weak network occasionally, or some area's CDN breakdown, even hijacked by network provider which cause the script broken and blocked by CSP (very common in China mainland).

We will see that the entry will be broken and throw error directly due to lack of dependencies:
![image](https://user-images.githubusercontent.com/4403937/27761817-fbd0b6c6-5e96-11e7-8c5e-1fdbc411c0ab.png)

![image](https://user-images.githubusercontent.com/4403937/27761025-18deef90-5e87-11e7-8a63-5c10612acf36.png)

Currently we have neither ability to guarantee them load done by any webpack way, nor occasion to reload the failed ones before startup. If there are any hooks that let we have ability to inspect and reload them (such as use another CDN), It will help us prevent the page from becoming unusable.

Actually, the page I'm maintaining which have aproximately 20 million PV in China mainland and can met a lot of error reported about it every day because of the terrible network and telecommunications environment (hijacked, CDN timeout, network switch frequently). We do need a retry and assurance mechanism to improve the usability of some unlucky users.

Sorry if tl;dr. 

the one implemetation I can imagine is extract the **bootstrap code** inline to the HTML page, and also with the **external chunks list** analyzed from the entry. So that we can check whether the necessary dependencies are all present before we startup (not sure whether can implemented by write Plugins):

```html
<script src="./dll/common.bundle.js"></script>
<script src="./commonChunk.bundle.js"></script>
<!-- only modules, but extract the bootstrap code. -->
<script src="./entry.bundle.js"></script>
<!-- only modules, but extract the bootstrap code. -->

<script>
//Extracted from entry or commonChunk
var bootstrap = (function(modules) { // webpackBootstrap
/*......*/
});

//Analyzed by plugin
var externalChunksList = /*...*/;

//Generated by plugin, should let users setting their own handler
if(hasAllExternalsInstalled()) {
  bootstrap(/*...*/);
}else{
  tryReloadMissingChunks().then(() => bootstrap(/*...*/)).catch(e => /*...*/);
}
</script>
```

Please feel free to indicate my mistake. I'm also looking forward to more brilliant proposal.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

webpack 3.0.0 with all platform.

**Comment by TheLarkInn** [comment]
@sokra so it appears that this is an incredibly common problem where requests can be hijacked and most times folks need a return for additional chunks. (if understood correctly). Could we add a feature to template/runtime that includes some time out/retry?

**Comment by mc-zone** [comment]
Hi, bother again!

Temporarily I've make a plugin to implement what I need:
https://github.com/mc-zone/bundle-ensure-webpack-plugin

But the inconvenient is that I haven't been able to find a way to extract the startup code completely. There are different cases about entrypoint's execution (where and how they load the entry module):

- Generally, the startup code for a simple entry is at itself's bootstrap code ([MainTemplate.js#L29](https://github.com/webpack/webpack/blob/d1619d495beffe1c030859eebd3c719c40075703/lib/MainTemplate.js#L29)).
- But if using commonChunk, it was placed in the commonChunk's bootstrap and be executed by call `webpackJsonp([0],[/*...*/])` which is at the beginning of the entry chunk ([JsonpMainTemplatePlugin.js#L159](https://github.com/webpack/webpack/blob/d1619d495beffe1c030859eebd3c719c40075703/lib/JsonpMainTemplatePlugin.js#L159)). 

Finally I have to add a function wrap to each chunks for the ability to executed them manually, not a elegant implementation, like following:
```javascript
window.__WP_CHUNKS__[0] = function(webpackJsonp){
/* origin chunk source code */
};
```

```javascript
if(allExternalsInstalled){
  for(var i = 0; i < chunkManifest.length; i+=1){
    var chunk = chunkManifest[i];
    window.__WP_CHUNKS__[chunk.id].call(window, window["webpackJsonp"]);
  }
}else{
  /* reload missing stuffs */
}
```

So I'm still hope that webpack would have more elegant hooks or implementations for this. 

Anyway thanks for your attention. ☺️

**Comment by mc-zone** [comment]
After reading [road-to-webpack-4-week-20-21](https://medium.com/webpack/road-to-webpack-4-week-20-21-1641d03ce06e) and learned the new proposal about script loading in V4, I'd like to be added v4 label at this issue and hope V4 will be more friendly to load error/reload ability.

**Comment by alexander-akait** [comment]
https://github.com/webpack/webpack/pull/7913#issuecomment-414213442 and https://github.com/webpack/webpack.js.org/issues/4575
