### ISSUE TITLE
Incorrect transformation: typeof require.resolve

### ISSUE THREAD

**Issue by Lighttree** [webpack/webpack#5198]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

This is from project dependencies: https://github.com/canjs/can-fixture
If you import this module:
```
import fixture from 'can-fixture';
```

`Webpack` transforms this line:
https://github.com/canjs/can-fixture/blob/master/fixture.js#L68

to:
 
```
if(typeof window !== "undefined" && function !== "function") {
    window.fixture = fixture;
}
```

This cause JS fail:
```
Uncaught SyntaxError: Unexpected token !==
```
because `fucntion !== "function"` - invalid statement
[screenshot](https://u25491580.dl.dropboxusercontent.com/u/25491580/wut.jpg)

**If the current behavior is a bug, please provide the steps to reproduce.**

You will see the issue if install the package and import it. 
I've created a repo that demonstrates the issue as well:
https://github.com/Lighttree/webpack-canjs-fixture-issue

just run `npm install`, `npm run serve`.

**What is the expected behavior?**
This should return `"function"` as string.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
- Node v8.1.2

**Comment by darylteo** [comment]
For google searchers: if you're using Swagger-Codegen, and have set "parser: { amd: false }" in your rules, this bug will break your build. Revert back to the old "imports-loader?define=>false" hack  to workaround.

I'm not sure why this works, other than perhaps "imports-loader" is doing something else to it.

Hopefully this helps to narrow down issue. I'm guessing there is a regression in the commonjs transpiler or something, but I'm not familiar enough with the codebase to figure it out.
