### ISSUE TITLE
resolve.alias support different setting for different entries

### ISSUE THREAD

**Issue by luckydrq** [webpack/webpack#5200]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
`resolve.alias` cannot be set  separately for different entries.

**If the current behavior is a bug, please provide the steps to reproduce.**
it's not a bug

**What is the expected behavior?**
I expect `resolve.alias` can have different settings for multiple entries. For example, i want to do a benchmark test between `react@15.x` and `react@16.x` and i create two entries to bundle the different react versions. So i need to set different alias for different react modules.
 
**If this is a feature request, what is motivation or use case for changing the behavior?**
It helps doing benchmark tests for same library more easily. 

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Node.js version: v6.9.4
OS:  MacOS Sierra 10.12.5

**Comment by bebraw** [comment]
If `resolve.alias` could accept a function and expose enough data, this sort of thing would be possible. I have a similar need in a project of mine where I need to alias differently based on the context (issuer).

**Comment by sokra** [comment]
This is not possible for technical reasons. You can use multiple compilations for this scenario.
