### ISSUE TITLE
'libraryTarget: umd' with nested namespace for optional dependency causes an error

### ISSUE THREAD

**Issue by dongwoo-kim** [webpack/webpack#5202]
**Do you want to request a *feature* or report a *bug*?**
This can be a bug, but I think this is more like a feature.

**What is the current behavior?**
I'm using `'umd'` for the `libraryTarget` and here's my config file.

```js
module.exports = {
  entry: './src/index.js',
  output: {
    library: ['my', 'module'],
    libraryTarget: 'umd',
    filename: 'bundle.js'
  },
  externals: {
    'my-ext-module': {
      commonjs: 'my-ext-module',
      commonjs2: 'my-ext-module',
      amd: 'my-ext-module',
      root: ['my', 'ext', 'module']
    }
  }
};
```
This works just find even though both of my target and external namespaces are multi-nested.

But if I try to make the external module (`my-ext-module`) optional, this doesn't work well. When I run the bundled file on a browser environment (using namespace), a script error occurs at the code below, which is the last line of the `webpackUniversalModuleDefinition` function body.
```js
root["my"] = root["my"] || {}, root["my"]["module"] = factory(root["my"]["ext"]["module"]);
```

Because the `window.my.ext` does not exist, `factory(root["my"]["ext"]["module"])` causes an error and I can't even run my code even though it is executable without `my-ext-module`.

**What is the expected behavior?**

I know I can wrap my `require(...)` code with `try...catch` statement and make the generated code deal with optional dependencies, but it works only for `commonjs` and `amd`. I think the generated code for the 'root` case also should look like this.

```js
root["my"] = root["my"] || {}, root["my"]["module"] = factory(root["my"] && root["my"]["ext"] && root["my"]["ext"]["module"]);
```

**If this is a feature request, what is motivation or use case for changing the behavior?**

My team is maintaining open source UI widgets and each module has namespace under `tui`. (ex. `tui.component.Pagination`, `tui.Grid`). The `tui.Grid` has an optional dependency for `tui.component.Pagination` and it was just fine when we handled dependencies using namespaces (with bower). But recently, we've been moving from bower to npm to support commonjs as well (using umd) and having trouble with this situation.

I think it's reasonable to handle multi-depth namespaces safely as a default, even without `try...catch` statement. If you use ES6 module, there's no way to handle optional dependencies because of its static nature. It's not a big problem in a node environment because adding a dependency has little cost. But in a browser environment, one more external script file means slower loading time. So there should be a way to run a code which has optional dependencies without including those script files.

If granted, I can make a PR as I've already been making my own Plugin to deal with this situation. Please consider this issue and give me a feedback. Thanks :)

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Node: 8.1.2, Webpack: 3.0.0, OS: macos
(Webpack 1.x.x also has same issue)

**Comment by sokra** [comment]
The way optional nested dependencies are handled seem to be a bug. I would appreciate a PR here.

I think it's correct that non-optional dependencies crash early. The errors would be difficult follow if somewhere in your libs code is an undefined. For ES Modules you can wrap the external in a CJS module with try-catch and handling for missing dependency.

**Comment by janrembold** [comment]
@dongwoo-kim Are there any news on this topic? I just ran into the same problem.
