### ISSUE TITLE
Core API should expose Chunk.sortModules

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack#5204]
**Do you want to request a *feature* or report a *bug*?**

Feature.

**What is the current behavior?**

`ExtractTextWebpackPlugin` is [broken in certain scenarios](https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/548) against webpack 3.

**What is the expected behavior?**

ETWP should work. To make it possible, webpack core should expose `Chunk.sortModules(fn)` first.

**If this is a feature request, what is motivation or use case for changing the behavior?**

Currently the functionality is missing and ETWP requires for the fix.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Webpack 3.

**Comment by hulkish** [comment]
Couldn't this be solved in https://github.com/webpack/webpack/blob/master/lib/Chunk.js#L424?
