### ISSUE TITLE
"Uncaught TypeError: Cannot call method 'apply' of undefined" while running Angular based on WebPack with Cordova. (solved)

### ISSUE THREAD

**Issue by z56** [webpack/webpack#5211]
**Do you want to request a *feature* or report a *bug*?**
Bug report.

**What is the current behavior?**
While running Angular app with Cordova, I see only white screen on device and error "`Uncaught TypeError: Cannot call method 'apply' of undefined in vendor.bundle.js:5706`" in `chrome://inspect/#devices`. Angular not works in Cordova+WebKit nor Cordova+Crosswalk.

<img src="https://habrastorage.org/web/76d/58b/b4c/76d58bb4c025457da3d676eda8018e0a.png"/>

**If the current behavior is a bug, please provide the steps to reproduce.**

Configuration is in Angular master branch.
```
ng new App
cd App
cordova create cordova com.mycompany.app App
ng build --output-path=cordova/www/ --base-href .
cd cordova
cordova platform add android
cordova plugin add cordova-plugin-crosswalk-webview #optional
cordova run android
```

**What is the expected behavior?**
No errors in console and "App works!" text on device screen.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Angular version: 4.2.4 (latest)
Browser - Android WebView version 33
Browser - Crosswalk WebView version 23
Node version: 6.11.0
Platform: Windows 10 x64
Cordova version 7.0.1
Android version 4.4 KitKat
Crosswalk version 23

**Comment by sokra** [comment]
Is `Object.assign` available in this environment?

**Comment by z56** [comment]
Problem solved by including polyfill core-js/es6/Object

**Comment by ichorville** [comment]
Can anybody further elaborate on the above comment pls ?

**Comment by z56** [comment]
@ichorville my PC is now broken cause of electricity events on my street (I have recoverable UEFI problem), so I can't remember what's file you must edit. Maybe it was `polyfills.ts`

**Comment by z56** [comment]
@ichorville (offtop) can you explain why most of devs are indians? XD

**Comment by ichorville** [comment]
@z56 Asians probably lol :D
