### ISSUE TITLE
`profile: true` in webpack.config.js has no effect

### ISSUE THREAD

**Issue by jessepinho** [webpack/webpack#5213]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
Adding `profile: true` to my Webpack config doesn't actually result in profiling data being output (as `webpack --profile` would):

```bash
$ webpack
Hash: 11edbad99c963dc573e0
Version: webpack 3.0.0
Time: 64ms
                    Asset     Size  Chunks             Chunk Names
 ./index.main.compiled.js  2.73 kB    0, 1  [emitted]  main
./index.main2.compiled.js  2.73 kB    1, 0  [emitted]  main2
   [0] ./index.js 30 bytes {0} {1} [built]
   [1] ./foo.js 39 bytes {0} {1} [built]
   [2] ./bar.js 20 bytes {0} {1} [built]
```

**If the current behavior is a bug, please provide the steps to reproduce.**
See a minimal reproduction [here](https://github.com/jessepinho/webpack-sandbox/tree/profiling).

**What is the expected behavior?**
The profiling info should be output:

```bash
$ webpack --profile
Hash: 11edbad99c963dc573e0
Version: webpack 3.0.0
Time: 93ms
                    Asset     Size  Chunks             Chunk Names
 ./index.main.compiled.js  2.73 kB    0, 1  [emitted]  main
./index.main2.compiled.js  2.73 kB    1, 0  [emitted]  main2
   [0] ./index.js 30 bytes {0} {1} [built]
        factory:28ms building:18ms = 46ms                         <-- profiling
   [1] ./foo.js 39 bytes {0} {1} [built]
       [] -> factory:2ms building:4ms = 6ms                       <-- profiling
   [2] ./bar.js 20 bytes {0} {1} [built]
       [] -> factory:1ms building:1ms = 2ms                       <-- profiling
```

**If this is a feature request, what is motivation or use case for changing the behavior?**
n/a
**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
webpack 3, Node 6.10.1, Mac OS Sierra (10.12.5)

**Comment by TheLarkInn** [comment]
@jessepinho thank you for submitting your first issue. Would you be able to tell me exactly what version of webpack this was reported in?

**Comment by jessepinho** [comment]
Webpack@3.0.0
Sean Larkin <notifications@github.com> schrieb am Fr. 7. Juli 2017 um 19:14:

**Comment by pierreneter** [comment]
@jessepinho can you install the latest version of `webpack` and try again, after that, let @TheLarkInn know It is faulty or not.
I'm try build your project with `webpack@3.2.0`. it's work.
![captur22222222222222222e](https://user-images.githubusercontent.com/12815768/28188544-b77b06ba-684c-11e7-8979-63b3f998a785.PNG)

**Comment by jessepinho** [comment]
@TheLarkInn / @pierreneter Sorry, I missed the question about 3.1! 

I've just tested it again with 3.2.0 (and pushed it up to the repo), and am still seeing the same problem. @pierreneter, are you using `yarn` to install my setup?

For what it's worth, I'm on node v6.10.1. Here's the full output:

```bash
webpack-sandbox$ nvm ls
         v4.7.2
->      v6.10.1
         system
default -> 6 (-> v6.10.1)
node -> stable (-> v6.10.1) (default)
stable -> 6.10 (-> v6.10.1) (default)
iojs -> N/A (default)
lts/* -> lts/boron (-> N/A)
lts/argon -> v4.8.2 (-> N/A)
lts/boron -> v6.10.2 (-> N/A)
webpack-sandbox$ webpack -v
3.2.0
webpack-sandbox$ webpack
Hash: 11edbad99c963dc573e0
Version: webpack 3.2.0
Time: 64ms
                    Asset     Size  Chunks             Chunk Names
 ./index.main.compiled.js  2.73 kB    0, 1  [emitted]  main
./index.main2.compiled.js  2.73 kB    1, 0  [emitted]  main2
               stats.json  0 bytes          [emitted]
   [0] ./index.js 30 bytes {0} {1} [built]
   [1] ./foo.js 39 bytes {0} {1} [built]
   [2] ./bar.js 20 bytes {0} {1} [built]
```

**Comment by pierreneter** [comment]
You just run `webpack` in the example above, try run:` webpack --profile`

**Comment by sokra** [comment]
This is broken in the CLI args handling.

**Comment by jessepinho** [comment]
@pierreneter The entire point of this issue is that I shouldn't have to use `--profile` in the CLI, since I set `profile: true` in the webpack config.

**Comment by pierreneter** [comment]
I saw. Im trying fix it.

**Comment by jessepinho** [comment]
Great! Works now with PR #5300 (just tested it). Thanks @sokra!
