### ISSUE TITLE
Update docs: option output.libraryExport

### ISSUE THREAD

**Issue by mbraint** [webpack/webpack#5214]
**Do you want to request a *feature* or report a *bug*?**

*feature*

**What is the current behavior?**

There are not enough details in the documentation 
[**output.libraryExport**](https://webpack.js.org/configuration/output/#output-libraryexport) 

And the section about these options is missing here.
[**webpack options**](https://webpack.js.org/configuration/#options)

**What is the expected behavior?**

Examples of options and uses (_like about other options_) 

**If this is a feature request, what is motivation or use case for changing the behavior?**

Have complete documentation

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

not required

**Comment by sokra** [comment]
@webpack-bot move to webpack/webpack.js.org
