### ISSUE TITLE
ModuleConcatenationPlugin (ConcatenatedModule) does not change build hash

### ISSUE THREAD

**Issue by mzgoddard** [webpack/webpack#5217]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

ConcatenatedModule does not affect the build hash. ConcatenatedModule does not have a `updateHash` implementation so that it can update the build hash with its concatenated output.

**If the current behavior is a bug, please provide the steps to reproduce.**

Build a project with the ModuleConcatenationPlugin. Update one of the concatenated files. Compare the build hashes for both builds. The second will not have changed.

**What is the expected behavior?**

ConcatenatedModule changes the output hash when its modules are modified.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by le0nik** [comment]
Same problem. Also the same issue was reported here: https://github.com/webpack/webpack/issues/5184 . There is a minimal reproducible case in this comment: https://github.com/webpack/webpack/issues/5184#issuecomment-312934835

**Comment by sokra** [comment]
see #5231
