### ISSUE TITLE
npm ERR! peer dep missing: webpack@^2.2.0, required by webpack-dev-server@2.5.0

### ISSUE THREAD

**Issue by Download** [webpack/webpack#5218]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Upgrade to Webpack 3 fails on missing peer dependency

**If the current behavior is a bug, please provide the steps to reproduce.**
Take any project that is using both webpack and webpack-dev-server, then:
```sh
npm uninstall --save-dev webpack webpack-dev-server
npm install --save-dev webpack webpack-dev-server
```
Observe: NPM install fails with error message:
> npm ERR! peer dep missing: webpack@^2.2.0, required by webpack-dev-server@2.5.0

For an example, have a look at my project [ulog](https://github.com/download/ulog). It has Greenkeeper enabled but it's [attempts to upgrade webpack](https://github.com/Download/ulog/pull/8) are [failing](https://travis-ci.org/Download/ulog/jobs/244650362) with this message:

> npm ERR! peerinvalid The package webpack@3.0.0 does not satisfy its siblings' peerDependencies requirements!
> npm ERR! peerinvalid Peer webpack-dev-server@2.4.5 wants webpack@^2.2.0

**What is the expected behavior?**
For webpack-dev-server to also have a v3 version published to NPM with a correct peer dependency on webpack v3.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
There is also an issue open on the webpack-dev-server repo:
[Not compatible with webpack 3.0 ?? #961](https://github.com/webpack/webpack-dev-server/issues/961)

It seems the peer dependency was actually [already fixed](https://github.com/webpack/webpack-dev-server/pull/946), but somehow never published to NPM.

Builds all over the web are failing because of this. Really such a big release should get simultaneous releases of all major components so these problems don't occur, but this issue is already open for 9 days. Which is why I ask here in the hope this gets the attention it deserves. Because it looks like fixing it is just a single `npm publish` away...

BTW: I think a lesson to learn here for future releases is that *first* major components like webpack-dev-server (but ideally,also tools from third parties) should get some time to get tested and release *and publish to NPM* a new version that has a wider peer dependency range that includes the new upcoming Webpack version, and only then should webpack itself be released. 

Because NPM will pick the latest version of webpack and webpack-dev-server, any new projects trying to install both (e.g. starter kits etc) run a big risk of ending up with a broken build.

**WORKAROUND**: Downgrade to Webpack 2 until this is resolved by specifying the version explicitly:

```sh
npm install --save-dev webpack@2 webpack-dev-server
```

**Comment by sokra** [comment]
@webpack-bot move to webpack/webpack-dev-server

**Comment by Download** [comment]
@sokra There is one there already...
