### ISSUE TITLE
UglifyJSPlugin hang with some config on win64

### ISSUE THREAD

**Issue by remoe** [webpack/webpack#522]
Hi

I use the following config:

```javascript
var ExtractTextPlugin = require("extract-text-webpack-plugin");
var webpack = require('webpack')
module.exports = {
  context: __dirname + "/lib",
  entry: { 
    build: './boot/index.js',
    test: './test/index.js'
  },
  output: {
    path: __dirname + '/build/',
    filename: "[name].js"
  },
  module: {
    loaders: [
      { test: /\.json$/, loader: "json-loader" },
      { test: /\.html$/, loader: "html-loader" },
      { test: /\.css$/, loader: ExtractTextPlugin.extract("style-loader", "css-loader!autoprefixer-loader") },
      { test: /\.(eot|woff|svg)([\?]?.*)$/, loader: "file-loader?name=fonts/[name].[ext]" },
      { test: /.ttf([\?]?.*)$/, loader: "file-loader?name=fonts/[name].[ext]" },
      { test: /\.wav$/, loader: 'file-loader?name=audio/[hash].[ext]'},
      { test: /\.(png|jpg)$/, loader: 'file-loader?name=images/[hash].[ext]'} 
    ]
  },
  resolve: {
    modulesDirectories: ['node_modules', 'lib'],
  },
  plugins: [
      new ExtractTextPlugin("styles.css", {
        allChunks: true
      }),
      new webpack.optimize.UglifyJsPlugin()      
  ],
  node: {
    fs: "empty"
  }
};

```

The code runs through:

https://github.com/webpack/webpack/blob/master/lib/optimize/UglifyJsPlugin.js#L19
https://github.com/webpack/webpack/blob/master/lib/optimize/UglifyJsPlugin.js#L24
https://github.com/webpack/webpack/blob/master/lib/optimize/UglifyJsPlugin.js#L117

But it never stops and hangs:

36% 30/69 build modules

It builds only *without* this uglifyjs-plugin.

Sorry I don't have a full sample.

**Comment by dylanharrington** [comment]
I just ran into something similar and was able to get it working with:
```javascript
new webpack.optimize.UglifyJsPlugin({sourceMap: false})
```
The wiki page on [build-performance](https://github.com/webpack/docs/wiki/build-performance) led me to trying it.

**Comment by bebraw** [comment]
@remoe Can you try with the current version?

**Comment by sparty02** [comment]
I just updated to ```webpack@1.12.6``` and that fixed it for me!

**Comment by remoe** [comment]
@bebraw, sorry I haven't a working environment to test this.

**Comment by bebraw** [comment]
@remoe No worries. Let's leave this open till someone can confirm.

**Comment by sparty02** [comment]
I am having this same issue and I think I've narrowed it down to something related (either directly or indirectly) to a combination of using ```UglifyJsPlugin``` in conjunction with ```html-loader```.  Looks like there is a related issue going on with #1573.

**Comment by bebraw** [comment]
Ok. I'm closing this in favor of #1573. Let's continue there.
