### ISSUE TITLE
Disable require cache of chunk file when SSR and Code Splitting 

### ISSUE THREAD

**Issue by kimown** [webpack/webpack#5222]
First, Thank you guys for this project, It really helps a lot in my daily job.

**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Here is my problem:
I use code-splitting and server render in my project, after webpack compiled, the bundle and chunks looks like this:

```
tree dist |grep .js
├── detail.js
├── home.js
└── server.bundle.js
```

 Because Node.js will cache Modules, so In my development environment I delete require cache when request arrives
```
const serverBundlePath = 'XXX' // the path of server.bundle.js
const cache = require.cache
delete cache[serverBundlePath]
const serverRender = require(serverBundlePath)
return serverRender(url, initialState)
```
https://nodejs.org/dist/latest-v8.x/docs/api/modules.html#modules_caching

But when server.bundle.js require other chunk files, because node will cache chunk file, so html of  server render is always the same. 
![image](https://user-images.githubusercontent.com/7932380/27910975-0345a94c-628a-11e7-9e88-f2eb7c79c428.png)

I don't read the code of webpack carefully, but I think maybe the template code is here
https://github.com/webpack/webpack/blob/cd2f022d4302e7f4e4926d709f5011423c40de8c/lib/node/NodeMainTemplatePlugin.js#L136

I want to delete require  cache of chunk file, so I think two ways to solve this problem, just idea.
1. like [Babel register](https://babeljs.io/docs/usage/babel-register/), only in development environment,  change the require function 
2. use loader or after emit event, change the source code of server.bundle.js.

But I think these two ways are't very good, so I want to know there is easy way to solve this problem?

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by sokra** [comment]
You could try `target: "async-node"` which uses another technique to load chunks.

**Comment by kimown** [comment]
@sokra  Thank you, this config really solve my problem.

https://webpack.js.org/configuration/target/#string
