### ISSUE TITLE
Error during installation webpack with Yarn

### ISSUE THREAD

**Issue by untone** [webpack/webpack#5223]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
Installation process is failed.

**If the current behavior is a bug, please provide the steps to reproduce.**
`touch 2`
`yarn init`
`yarn add webpack --verbose`

Result is:
`verbose 1.269 Performing "GET" request to "https://registry.yarnpkg.com/base64-js".`
`verbose 1.278 Error: Couldn't find a package.json file in "/Users/untone/Sites/yarn-test/2"`
`    at /usr/local/lib/node_modules/yarn/lib/config.js:452:15`
`    at Generator.next (<anonymous>)`
`    at step (/usr/local/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)`
`    at /usr/local/lib/node_modules/yarn/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13`

**What is the expected behavior?**
Successfully finished installation.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

OSX 10.11, Ubuntu 14.04

node v7.8.0 — v8.1.3
yarn v0.24.5 — 0.27.3

**Comment by sokra** [comment]
Doesn't look like a webpack issue.
