### ISSUE TITLE
convert-argv.js adds HotModuleReplacementPlugin even when already available

### ISSUE THREAD

**Issue by zcei** [webpack/webpack#5233]
**Do you want to request a *feature* or report a *bug*?**
To me it feels more like a bug.

**What is the current behavior?**
If the `argv` contains the `--hot` option, the `HotModuleReplacementPlugin` is added without further checks.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Add `new webpack.plugins.HotModuleReplacementPlugin()` to `webpackConfig.plugins`
2. Invoke `webpack` (or `webpack-dev-server`) bin with `--hot` flag.
3. Break after [bin/convert-argv.js:383](https://github.com/webpack/webpack/blob/master/bin/convert-argv.js#L383)
4. Inspect `options.plugins` (plugin included twice)

Manifests in a weird error: 
> `SyntaxError: missing ) after argument list`

**What is the expected behavior?**
`--hot` should be a noop if already added as plugin

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

I think you could consider it "wrong configuration" and maybe want to close it directlly, then it at least serves better discoverability when facing the error.

A simple fix within `convert-argv.js` would be the following:

```js
var hasHotModuleReplacementPlugin = options.plugins.some((plugin) => {
  return plugin.constructor.name === 'HotModuleReplacementPlugin';
});

if (!hasHotModuleReplacementPlugin) {
  options.plugins.push(new HotModuleReplacementPlugin());
}
```

**Comment by msheakoski** [comment]
I was also bit by this issue. It was very difficult to track down the source of the problem!
