### ISSUE TITLE
"[HMR] Hot Module Replacement is disabled."

### ISSUE THREAD

**Issue by lingyange** [webpack/webpack#5237]
### in package.json  
``
"scripts": {
    "dev": "node_modules/.bin/webpack-dev-server --config webpack.config.js --port 8089 --open",
    "build": "webpack --config webpack.config.js"
  },

### in webpack.config.js
'''
var path = require('path');
var webpack = require('webpack');
module.exports = {
    entry: ['webpack/hot/dev-server', path.resolve(__dirname, 'main.js')],
    output: {
        path: path.resolve(__dirname, './build'),
        filename: 'bundle.js'
    },
    module: {
        loaders: [
            {
                test: /(\.js|\.jsx)$/,
                exclude: /(node_modules|bower_components)/,
                loader: 'babel-loader',
                query: {
                    presets: ['es2015', 'react']
                }
            }
        ]
    },
    plugins: [
        new webpack.HotModuleReplacementPlugin()
    ]
};

**Comment by bebraw** [comment]
Can you please fill in the issue template? Thanks.
