### ISSUE TITLE
react-native init have problems

### ISSUE THREAD

**Issue by SHIRONGWANG** [webpack/webpack#5238]
~This is the problems, somebody have this problems?

iMac-de-MM:first mm$ react-native init FirstProject
This will walk you through creating a new React Native project in /Users/mm/Desktop/test/first/FirstProject
Using yarn v0.27.5
Installing react-native...
yarn add v0.27.5
error An unexpected error occurred: "/Users/mm/package.json: Unexpected end of JSON input".
info If you think this is a bug, please open a bug report with the information provided in "/Users/mm/Desktop/test/first/FirstProject/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
{ Error: Command failed: yarn add react-native --exact
    at checkExecSyncError (child_process.js:481:13)
    at execSync (child_process.js:521:13)
    at run (/usr/local/lib/node_modules/react-native-cli/index.js:294:5)
    at createProject (/usr/local/lib/node_modules/react-native-cli/index.js:249:3)
    at init (/usr/local/lib/node_modules/react-native-cli/index.js:200:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/react-native-cli/index.js:153:7)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
  error: null,
  cmd: 'yarn add react-native --exact',
  file: '/bin/sh',
  args: [ '/bin/sh', '-c', 'yarn add react-native --exact' ],
  options: 
   { stdio: [ [Object], [Object], [Object] ],
     shell: true,
     file: '/bin/sh',
     args: [ '/bin/sh', '-c', 'yarn add react-native --exact' ],
     envPairs: 
      [ 'TERM_PROGRAM=Apple_Terminal',
        'ANDROID_HOME=/Users/mm/Library/Android/sdk',
        'SHELL=/bin/bash',
        'TERM=xterm-256color',
        'TMPDIR=/var/folders/28/w7t62mqj1rbcqxvjs0nc_3sc0000gn/T/',
        'Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.Sfp30zyPJk/Render',
        'TERM_PROGRAM_VERSION=361.1',
        'TERM_SESSION_ID=01E42516-E751-4E1B-83B6-1995353D79A1',
        'USER=batitek1',
        'SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.s3udiDntRu/Listeners',
        '__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x1',
        'PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin',
        'PWD=/Users/mm/Desktop/test/first',
        'LANG=fr_FR.UTF-8',
        'XPC_FLAGS=0x0',
        'XPC_SERVICE_NAME=0',
        'SHLVL=1',
        'HOME=/Users/mm',
        'LOGNAME=mm',
        '_=/usr/local/bin/react-native',
        'OLDPWD=/Users/mm' ] },
  envPairs: 
   [ 'TERM_PROGRAM=Apple_Terminal',
     'ANDROID_HOME=/Users/mm/Library/Android/sdk',
     'SHELL=/bin/bash',
     'TERM=xterm-256color',
     'TMPDIR=/var/folders/28/w7t62mqj1rbcqxvjs0nc_3sc0000gn/T/',
     'Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.Sfp30zyPJk/Render',
     'TERM_PROGRAM_VERSION=361.1',
     'TERM_SESSION_ID=01E42516-E751-4E1B-83B6-1995353D79A1',
     'USER=batitek1',
     'SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.s3udiDntRu/Listeners',
     '__CF_USER_TEXT_ENCODING=0x1F5:0x0:0x1',
     'PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin',
     'PWD=/Users/mm/Desktop/test/first',
     'LANG=fr_FR.UTF-8',
     'XPC_FLAGS=0x0',
     'XPC_SERVICE_NAME=0',
     'SHLVL=1',
     'HOME=/Users/mm',
     'LOGNAME=mm',
     '_=/usr/local/bin/react-native',
     'OLDPWD=/Users/mm' ],
  stderr: null,
  stdout: null,
  pid: 26911,
  output: [ null, null, null ],
  signal: null,
  status: 1 }
Command `yarn add react-native --exact` failed.

$ node --version
v6.11.0
$ npm --version
3.10.10
$ yarn --version
0.27.5

**Comment by bebraw** [comment]
Can you please fill in the issue template?
