### ISSUE TITLE
"[HMR] Hot Module Replacement is disabled."

### ISSUE THREAD

**Issue by lingyange** [webpack/webpack#5239]
**Do you want to request a *feature* or report a *bug*?**
i think it's a bug

**What is the current behavior?**
i want to save files ,the browser can refresh right now. 
**If the current behavior is a bug, please provide the steps to reproduce.**
webpack.config.js not work
`package.json`
```
"scripts": {
"dev": "node_modules/.bin/webpack-dev-server --config webpack.config.js --port 8089 --open",
"build": "webpack --config webpack.config.js"
},
```
`webpack.config.js`
```
var path = require('path');
var webpack = require('webpack');
module.exports = {
entry: ['webpack/hot/dev-server', path.resolve(__dirname, 'main.js')],
output: {
path: path.resolve(__dirname, './build'),
filename: 'bundle.js'
},
module: {
loaders: [
{
test: /(.js|.jsx)$/,
exclude: /(node_modules|bower_components)/,
loader: 'babel-loader',
query: {
presets: ['es2015', 'react']
}
}
]
},
plugins: [
new webpack.HotModuleReplacementPlugin()
]
};
```

**What is the expected behavior?**
no
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by sokra** [comment]
You didn't use WDS correctly. Don't pass HotModuleReplacementPlugin instead pass `--hot`
