### ISSUE TITLE
Add an option to CommonsChunkPlugin that would be used as part of the hashing value

### ISSUE THREAD

**Issue by gajus** [webpack/webpack#5247]
The problem is when there is a build error, e.g. one of the optimization plugins fail. This produces an invalid bundle that is cached by the client. If I fix the plugin configuration that caused the issue, the chunk's hash value remains the same – and therefore the client will ignore the new bundle.

It would be nice to have a value that could be adjusted to generate a new hash for all chunks, e.g. `new CommonsChunkPlugin({uid: '1'})`. The `uid` concatenated with the hash value would be used to rehash the chunk hash.

**Comment by sokra** [comment]
there is a `output.hashSalt` property.

**Comment by gajus** [comment]
Oh, I see. I was looking for something in https://webpack.js.org/plugins/commons-chunk-plugin/. Thank you.
