### ISSUE TITLE
chunks to be downloaded from different urls based on chunk name

### ISSUE THREAD

**Issue by Saravana-Kumar-putta** [webpack/webpack#5249]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
No possibility to specify the particular chunks should be downloaded from different public path

**What is the expected behavior?**
Chunks are obtained using require.ensure methodology.
For example: chunkname : Test should be downloaded from htttp://localhost:8087 and chunkname : Test1 should be downloaded from http://localhost:8080

**If this is a feature request, what is motivation or use case for changing the behavior?**
If an multiple request to one server might cause in slowness of application.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by sokra** [comment]
This doesn't work. Instead you could use HTTP2 on the server.
