### ISSUE TITLE
directory copy support

### ISSUE THREAD

**Issue by enigma1** [webpack/webpack#525]
In some cases I needed to copy all resources from a folder straight to the output without having webpack to rename files or injecting hashes. I created a basic module for this for the time being. Maybe the file loader could be extended to support directories?

Here is what I use as a workaround

```javascript
// index.js in a node module folder say dircopy
var path = require('path');

module.exports = function(content) {
	this.cacheable && this.cacheable();
	if(!this.emitFile) {
    throw new Error("emitFile is required from module system");
  }
  var url = path.relative(path.dirname(this.context), this.resourcePath).replace(/\\/g, "/").replace(/\.\.(\/)?/g, "_$1");
  this.emitFile(url, content);
  return "module.exports = __webpack_public_path__ + " + JSON.stringify(url);
};
module.exports.raw = true;
```

Then to use it I add in the webpack.config.js (preloader or loader section etc)
```javascript
      { test: /[\/\\]wildcardname.*\.jpg$/, loader: "dircopy-loader" },
```
The thing is I still have to add exceptions to the file loader using exclude. I would prefer to have something simpler. If there was a switch so if a file is processed by a preloader not to be processed again from the loader it will be nice

**Comment by wmertens** [comment]
Thanks for this, almost what I need, I want to present a whole folder of assets as one packed file without having to specify each file. I'll write a custom loader that runs a glob and a dummy file to trigger the loader.

@enigma1 can you be more precise about your last question? Maybe you should open a new ticket and close this one.

**Comment by mathieumg** [comment]
> I want to present a whole folder of assets as one packed file without having to specify each file.

Same here!

> I'll write a custom loader that runs a glob and a dummy file to trigger the loader.

Please give a link here once you do it, I'd love to use it too. :+1: Thanks!

**Comment by wmertens** [comment]
@mathieumg I describe my solution here: http://stackoverflow.com/a/30879169/124416

You can use coffeescript.org to convert the code to JS.

**Comment by bebraw** [comment]
To answer the original question, there are packages like https://www.npmjs.com/package/copy-webpack-plugin and https://www.npmjs.com/package/transfer-webpack-plugin now. It's probably better to push possible discussion there.
