### ISSUE TITLE
Bug: "Dead code" eliminate media files

### ISSUE THREAD

**Issue by renarsvilnis** [webpack/webpack#5251]
# Feature request

I need to remove certain media file (non-inlined using file-loader) depending on the environment (development/production) using Webpack (v3.1.0) and UglifyJsPlugin.

I suggest adding "Dead code" elimination unused for media files

## Use case

Developing a software solution that works with different products - where some are launched and others are in production and are not live on production, bet abled to use on development, staging environments.

## Current situation

```javascript
export const IMAGES = Object.assign(
  {
    PROFILE: require('images/profile.png'),
    // ...
  },
  process.env.NODE_ENV !== 'production' && {'LOGO': require('images/logo.png')}
);
```

I have gotten so far that after the production build the outputted Javascript file doesn't contain an `IMAGES.LOGO` key, but the required `images/logo.png` file is present in the output. And has code references if searched by the outputted hash name within the js file.

## Webpack plugin configuration

```javascript
new webpack.DefinePlugin({
  'process.env.NODE_ENV': JSON.stringify('production')
}),
new webpack.optimize.UglifyJsPlugin({
  comments: false,
  sourceMap: true
})
```

**Comment by bebraw** [comment]
Could you try with an `if` block?

**Comment by renarsvilnis** [comment]
@bebraw Using `if` block does the trick. So that's an edge case.

Created a repo which I used to test it out:
 https://github.com/renarsvilnis/webpack-media-dead-code

Using `Object.assign()` method `process.env.NODE_ENV !== 'production' && {b: require('./thumbs-down.jpg')}` outputs as `!1` yet the reference to the file stays.
