### ISSUE TITLE
Feature request: Clean build folder

### ISSUE THREAD

**Issue by jerguslejko** [webpack/webpack#5252]
**Do you want to request a *feature* or report a *bug*?**
Request a feature

**What is the current behavior?**
N/A

**If the current behavior is a bug, please provide the steps to reproduce.**
N/A

**What is the expected behavior?**
It'd amazing, if webpack had built-in support for cleaning the output folder on build.

**If this is a feature request, what is motivation or use case for changing the behavior?**
There are third-party solutions, but this feature feels so important that it could be a part of the core.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
N/A

**Comment by sokra** [comment]
There is a plugin for this. You can use task runners. You can use `rm -rf dist`. I don't think we should add this feature to webpack and instead keep it focus on building.

**Comment by jerguslejko** [comment]
😢
