### ISSUE TITLE
Consider integrating extract-text-webpack-plugin and other "sytemic" plugins as webpack-native

### ISSUE THREAD

**Issue by csentis** [webpack/webpack#5254]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Currently, extract-text-webpack-plugin is handled as a "side-contribution" to webpack. I would like you to consider integrating it as a "native" webpack-plugin due to the following reasons:

after release of `webpack 3.0.0` on June 19th, it took (due to various reasons) 21 days for `extract-text-webpack-plugin` to likewise release version 3.0.0 of their plugin. It is not my intention to blame @d3viant0ne and his contributors who are simply producing great stuff. But it does lead to a rather awkward situation:

with `extract-text-webpack-plugin 3.0.0` released July 10th, it is highly likely that now the ball is in the turf of other fantastic developers such as @jantimon and his contributors to `html-webpack-plugin` who have been waiting for fixes in `extract-text-webpack-plugin` to be available. After that, it will be a whole litany of addons depending on `html-webpack-plugin` (their [README](https://github.com/jantimon/html-webpack-plugin/blob/master/README.md) alone lists thirteen of them).

To put it short: `extract-text-webpack-plugin` is basically "too big to fail" or "systemic" to `webpack` and should be treated as such.

**What is the expected behavior?**
webpack "systemic" plugins are investigated, identified and coupled more closely to `webpack`'s own release cycle.

**If this is a feature request, what is motivation or use case for changing the behavior?**
As described above.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Not deemed necessary due to nature of request.

**Comment by d3viant0ne** [comment]
@csentis - There is a blog post from @sokra related to this topic already https://medium.com/webpack/the-new-css-workflow-step-1-79583bd107d7

The gist is extract-text will eventually be retired.

**Comment by csentis** [comment]
Thank you @d3viant0ne - the nature and content of your answer confirms (for me) what I already thought of you and your work: well tempered and to the point.

I had not know of the blog post - good you pointed to it, helps!

Sorry to hear your `extract-text-plugin` is going to be retired  & looking forward to still seeing your great contributions in other places!

IMO issue can be closed.
