### ISSUE TITLE
Webpack 3 ModuleConcatenationPlugin JavaScript heap out of memory

### ISSUE THREAD

**Issue by alan-agius4** [webpack/webpack#5257]
**Do you want to request a *feature* or report a *bug*?** bug

**What is the current behavior?** Heap out of memory when using `ModuleConcatenationPlugin`, I am not using HMR

**If the current behavior is a bug, please provide the steps to reproduce.**

When using, `new webpack.optimize.ModuleConcatenationPlugin()` I am getting the `FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory`

```
<--- Last few GCs --->
  154254 ms: Mark-sweep 1324.6 (1437.9) -> 1324.6 (1437.9) MB, 1012.4 / 0.0 ms [allocation failure] [GC in old space requested].
  155267 ms: Mark-sweep 1324.6 (1437.9) -> 1324.6 (1437.9) MB, 1012.6 / 0.0 ms [allocation failure] [GC in old space requested].
  156328 ms: Mark-sweep 1324.6 (1437.9) -> 1332.8 (1421.9) MB, 1061.0 / 0.0 ms [last resort gc].
  157361 ms: Mark-sweep 1332.8 (1421.9) -> 1341.1 (1421.9) MB, 1032.7 / 0.0 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================
Security context: 00000266E3BCFB49 <JS Object>
    1: token(aka token) [00000266E3B04381 <undefined>:1729] [pc=0000022506B6474D] (this=00000266E3B04381 <undefined>,type=00000266E3B04FB1 <String[4]: name>,value=00000094B9F86569 <String[4]: this>,is_comment=00000266E3B04381 <undefined>)
    2: arguments adaptor frame: 2->3
    3: read_word(aka read_word) [00000266E3B04381 <undefined>:~1962] [pc=0000022506B8867B] (this=00000266E3B04381 <unde...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

```

**What is the expected behavior?** no error

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**   Webpack 3.1.0, Windows 10

**Comment by sokra** [comment]
You can increase the head size for node.js `node --max-old-space-size=8192`

By default it's limited to a few GB. Newer v8 versions will have a dynamic heap size so this probably won't be a problem in future.

**Comment by alan-agius4** [comment]
@sokra, I have a limit of 4Gb,  increasing the memory limit to 8Gb is not really an option, but it's ridiculous that it needs 8Gb

**Comment by alan-agius4** [comment]
@sokra , I have increased the limit to `10Gb` on a separate machine and still didn't work.

[10:21:23]  preprocess finished in 205 ms
[10:21:23]  webpack started ...

<--- Last few GCs --->

  225050 ms: Mark-sweep 10184.7 (10244.9) -> 10184.0 (10244.9) MB, 792.6 / 0.0 ms [allocation failure] [GC in old space requested].
  225811 ms: Mark-sweep 10184.0 (10244.9) -> 10184.0 (10244.9) MB, 760.4 / 0.0 ms [allocation failure] [GC in old space requested].
  226601 ms: Mark-sweep 10184.0 (10244.9) -> 10189.0 (10243.9) MB, 790.3 / 0.0 ms [last resort gc].
  227359 ms: Mark-sweep 10189.0 (10243.9) -> 10194.0 (10243.9) MB, 757.4 / 0.0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0000005BCC9CFB49 <JS Object>
    1: DoJoin(aka DoJoin) [native array.js:~129] [pc=000000F262D06711] (this=0000005BCC904381 <undefined>,w=000000D3E25F3B21 <JS Array[1472]>,x=1472,N=0000005BCC9043C1 <true>,J=0000005BCC9AE4C9 <String[1]:  >,I=0000005BCC9B46D9 <JS Function ConvertToString (SharedFunctionInfo 0000005BCC952DC9)>)
    2: Join(aka Join) [native array.js:180] [pc=000000F262C5D132] (this=0000005BCC904381 <undefine...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

**Comment by kzc** [comment]
ModuleConcatenationPlugin memory problem was isolated in https://github.com/webpack/webpack/issues/5992#issuecomment-346384896 and fixed in https://github.com/webpack/webpack/pull/5997.
