### ISSUE TITLE
Missing module at 1st build, present at consecutive build only from webpack@3

### ISSUE THREAD

**Issue by JSteunou** [webpack/webpack#5259]
**Do you want to request a *feature* or report a *bug*?**

*bug*

**What is the current behavior?**

Having this error when updating from webpack@2 to webpack@3 on a dynamic css load

```
vendor-2d14daf….js:55 Uncaught (in promise) TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (vendor-2d14daf….js:55)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

It might be an issue from the loader but I dont know for sure.

I have this syntax 

```js
            require.ensure(['../../assets/css/foo.styl'], function(require) {
                require('!!style-loader!css-loader!stylus-loader!../../assets/css/foo.styl');
            }, 'foo-styl');
```

I also tried this new one, but same issue

```js
import(/* webpackChunkName: "foo-styl" */ '!style-loader!css-loader!stylus-loader!../../assets/css/foo.styl');
```

Using webpack dev/watch mode I have the error, but if I hit *save* on the file, webpack watch mode trigger rebuild / reload and the error is gone, all working fine. I reproduce the error by stopping webpack and launch it again or with a production build.

**What is the expected behavior?**

CSS should be inject like with webpack@2

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Using Chrome@59 nodejs@8.1 webpack@3.1.0 Ubuntu 17.04

**Comment by JSteunou** [comment]
I have this default config for `.styl` 

```
                {
                    test: /\.styl$/,
                    use: cssExtractor.extract({
                        fallback: 'style-loader',
                        use: ['css-loader?-autoprefixer', 'stylus-loader'],
                        publicPath: '../'
                    })
                },
```

That's why I'm using `!` or `!!` to bypass config in this use case, without success.

**Comment by awesomenaz** [comment]
Hi, @JSteunou webpack@3 utilize system.import as per new docs. Have you checked that out?

**Comment by JSteunou** [comment]
The doc advices to use `import()` and that's what I tried.

**Comment by awesomenaz** [comment]
Should it be config as this for the extract-text-plugin:

```javascript
const ExtractTextPlugin = require('extract-text-webpack-plugin');

module.exports = {
  module: {
    rules: [
      {
        test: /\.styl$/,
        use: ExtractTextPlugin.extract({
          use: [
            { loader: 'css-loader', options: { importLoaders: 1 } },
            'stylus-loader',
            'postcss-loader'
          ]
          fallback: 'style-loader'
        })
      }
    ]
  plugins: [
    new ExtractTextPlugin('css/[name]-[contenthash].css')
  ]
},
```

**Comment by JSteunou** [comment]
The extraction is not the issue. I already have a working config for extracted stylus files. If you read again my 1st post, I was using `require` to dynamically load stylus files but produce separate files, not mixed in the main css.

I solved the issue by using a 2nd rules and using special naming `.dyn.styl`
This is not as ugly as I though and has the advantage of having all setting at one place, but I expected old `require.ensure()` could have been simply replace with `import()`. As it was not the case I think it is a bug, that's it.

```
                {
                    test: /\.dyn\.styl$/,
                    use: [
                        {
                            loader: 'file-loader',
                            options: {
                                name: fileName => {
                                    // own name to remove .dyn
                                    const r = /.+\/(.+)\.dyn\.styl$/;
                                    const name = r.exec(fileName)[1];
                                    return `css/${name}-[hash].css`;
                                }
                            }
                        },
                        {
                            loader: 'extract-loader',
                            options: {
                                publicPath: '../'
                            }
                        },
                        {
                            loader: 'css-loader',
                            options: cssLoaderOptions
                        },
                        {
                            loader: 'stylus-loader',
                            options: stylusLoaderOptions
                        }

                    ],
                },
```

**Comment by awesomenaz** [comment]
I just realized that.
