### ISSUE TITLE
Check if a module exists without loading it?

### ISSUE THREAD

**Issue by remoe** [webpack/webpack#526]
Hi

For example I have two versions of an app. The first one loads a specific module (bundle) in the script tag and the other one does not.

app1:

``` html
<script src="mod1" />
<script src="mod2" />
```

app2:

``` html
<script src="mod2" />
```

Now I want to check on "mod2" if "mod1" exists and then do something different when it doesn't exist. But I don't want to load "mod1" on mod2!

On other build system like "Component" I can check it as follows:

``` js
if(require.modules['mod1']) {
  mod1 = require('mod1'); 
}
```

Is this possible to solve with webpack?

Thanks!

**Comment by szachara** [comment]
Exists something like this in webpack 2? Thx

**Comment by CezaryDanielNowak** [comment]
Currently I'm doing something like that:
```
let localComponent ;
cont Component = () => { /* ... */ }

try {
  localComponent = require('components/Component');
} catch (e) {}

export default localComponent || Component;
```
but webpack (every version: 1-4) is showing warning, that I want to get rid of:
`Module not found: Error: Can't resolve 'components/Component' in ...`

I've checked several ways to solve it:
- `require.resolveWeak` throws error, the same as `require` and `require.resolve`
- trick with `__webpack_modules__` does not work in minified bundle

Is that even possible?
