### ISSUE TITLE
webpack hangs forever after compilation

### ISSUE THREAD

**Issue by teekaay** [webpack/webpack#5263]
**Do you want to request a *feature* or report a *bug*?**

I want to report a *bug*.

**What is the current behavior?**

Webpack hangs when running it with the following commands:

* `./node_modules/.bin/webpack` (Vanilla)
* `./node_modules/.bin/webpack -p --progress` (Production)
* `NODE_ENV=production ./node_modules/.bin/webpack -p --progress --colors --profile --verbose` ("Full")

I have waited for 30 minutes and nothing happened after the compilation was complete. At least
I assume it because nothing happened even with verbose output. My project consist of a single 
React component so I assume it should not take to long. 

What is **really** weird is that when running webpack with `webpack-dashboard` it behaves as 
expected (running all compilation steps, emitting a `bundle.js`).

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Install webpack (I tested it against 3.x and 2.x)
2. [This](https://gist.github.com/teekaay/fc207a7a11cb1b84dba8ef4705eea91b) configuration
shows my `package.json` as well as the `webpack.config.js` I have used. 
3. Run the commands from the script in the Gist

**What is the expected behavior?**

It should at some time finish the compilation process and exit.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

* Node.js version: `v7.10.0`
* webpack version: `v2.5.1`
* OS: `Linux Mint 18`

**EDIT** I have searched for solutions and tried some like up/downgrading dependencies and doing a fresh install.

**Comment by sokra** [comment]
Did you try to removing the dashboard plugin?

**Comment by teekaay** [comment]
I have now. This indeed solves the problem. Thanks! Haven't thought about removing it.
