### ISSUE TITLE
Error in documentation 

### ISSUE THREAD

**Issue by alanosman** [webpack/webpack#5265]
**Do you want to request a *feature* or report a *bug*?**
Documentation Issue (found it as a newb to webpack 1.14.0)

**What is the current behavior?**
I don't really know how else to communicate this back, but I was following instructions here:
https://webpack.github.io/docs/tutorials/getting-started/#config-file

Under the section for **THE FIRST LOADER** it suggests to add this line to the sample file.
`require("!style!css!./style.css");`

but when you run webpack as instructed in the documentation, you get an error.
```
ERROR in ./entry.js
Module not found: Error: Can't resolve 'style' in '/mnt/d/website'
BREAKING CHANGE: It's no longer allowed to omit the '-loader' suffix when using loaders.
                 You need to specify 'style-loader' instead of 'style',
                 see https://webpack.js.org/guides/migrating/#automatic-loader-module-name-extension-removed
 @ ./entry.js 1:0-33
```

After some research turns out that I need to add -loader to the syntax. It was confusing to figure out because as a newb - you are like, whaaaat!  The example command should be:

`require("!style-loader!css-loader!./style.css");`

The error is also repeated in the next section **BINDING LOADERS** with the command:

`webpack ./entry.js bundle.js --module-bind 'css=style!css'` which should be `webpack ./entry.js bundle.js --module-bind 'css=style-loader!css-loader'`

and also under **A CONFIG FILE** in the code example: `{ test: /\.css$/, loader: "style!css" }` 

In fact, you should point out at the top of the file that you must have the latest version of webpack to follow these instructions.. because I can imagine some other soul having to deal with this late at night and running into the reverse of the problem. 

At this point, I do not have any more to add.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by sokra** [comment]
This is a webpack 1 tutorial, which no longer works with webpack 2. Check the webpack 2 documentation site for webpack 2/3 tutorials.

**Comment by alanosman** [comment]
Don't you think that should be made clear then in the documentation.  I didn't even see that?

**Comment by rainede** [comment]
agreed - I just followed the tutorial today and had the exact same bug!
