### ISSUE TITLE
entry set  css ,generate  css at the same time, but produced a redundant js

### ISSUE THREAD

**Issue by zhump** [webpack/webpack#5267]
webpack config like this 
```
var webpackConfig = {
  entry: {
      app: './src/main.js',
      ohter:'./src/ohter.css'
}
```
generate ohter.css at the same time, but produced a redundant ohter.js

How to remove this ohter.js？

**Comment by bebraw** [comment]
See https://github.com/webpack/webpack/issues/1967 .
