### ISSUE TITLE
DllReferencePlugin: manifest object as promise [bug?]

### ISSUE THREAD

**Issue by damianobarbati** [webpack/webpack#5274]
**Do you want to request a *feature* or report a *bug*?** 
Bug

**What is the current behavior?** 
`DllReference` plugin `manifest` option is not waiting to resolve filename.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Fix/Change behaviour

**What is the expected behavior?** 
If a path / string is given to `manifest` option then webpack should resolve the file when needed and not at plugin instantiation time.
Because file may not exist until webpack is actually running (and created other bundles first)!

In fact I'm stuck with this scenario:
- single webpack.config.js
- multiple configs exported: `module.exports = [webpackVendorConfig, webpackConfig];`
- first config is for dll bundles
- second config is for app bundling

The following (in the second config aka app bundling, 2nd in order) is going to fail because `manifest.json` is not generated yet by the first configuration: but that's going to be run first and `manifest.json` will exist!
```
    new webpack.DllReferencePlugin({
        manifest: require(`../build/manifest.json`), //this is going to exist after webpack runs the first config in the pipeline!
        name: `vendor`,
    })
```

I tried to pass a filepath to `manifest` (both relative and absolute) because I thought webpack was going to require it when needed but it is not!

Here the repro: 
https://github.com/damianobarbati/react-app/tree/v1.0.7

To run:
```
yarn install
yarn build:dev
```
Error:
```
Error: ENOENT: no such file or directory, open '../build/visitor/vendor.manifest.json'
```

Relevant line => https://github.com/damianobarbati/react-app/blob/v1.0.7/config/webpack.config.js#L56

Commenting the second config works fine => https://github.com/damianobarbati/react-app/blob/v1.0.7/config/webpack.config.js#L294

If you comment the second line you can see that the `manifest.json` file is correctly generated in the path reported as error thus webpack is requiring that file at `DllPluginReference` instantiation time instead of waiting once needed.

**Comment by damianobarbati** [comment]
Something is wrong with my last assumption: even commenting out the second config should actually trigger the error if webpack was requiring that file at plugin instantiation time: must be even another case, weird behaviour here! What's going on? When does webpack try to require this file then? 🤔

**Comment by sokra** [comment]
Try it this way:

``` js
module.exports = [
{
  name: "dll",
  // dll config
},
{
  dependencies: ["dll"]
}
];
```

**Comment by damianobarbati** [comment]
It worked!!! Thanks @sokra, closing this.

PS: `happypack` exploded so I'm reporting there xD
