### ISSUE TITLE
Multiple webpack bundles with dynamic public paths cannot live together

### ISSUE THREAD

**Issue by tomasAlabes** [webpack/webpack#5276]
**Do you want to request a *feature* or report a *bug*?**
Bug/feature

**What is the current behavior?**
You can set the `__webpack_public_path__` global variable to change the url where webpack goes to fetch the resources like images. But if 2 or more webpack bundles live in the same page and each one has a different dynamic public path, it doesn't work because `__webpack_public_path__` is global, and they are overwritten.
**If the current behavior is a bug, please provide the steps to reproduce.**
2 bundles with 2 assignments of `__webpack_public_path__` => collision => no resources loaded.

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**
Have an option to define the global variable name? Default it to `${bundleName}_public_path`?

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
3.2.0 but I think it applies to all versions.

**Comment by roysudi** [comment]
++1 This would a great new feature

**Comment by sokra** [comment]
`__webpack_public_path__` is not global. It's local to the bundle.

**Comment by tomasAlabes** [comment]
`__webpack_require__.p` in each bundle. Thanks for the answer.
