### ISSUE TITLE
Partial builds are slow in Webpack 3.2.0

### ISSUE THREAD

**Issue by ilearnio** [webpack/webpack#5277]
**Do you want to request a *feature* or report a *bug*?**

Issue

**What is the current behavior?**

Partial builds are slow in Webpack 3 compared to Webpack 2

**If the current behavior is a bug, please provide the steps to reproduce.**

I just upgraded webpack in my project (based on vue-webpack template) from v2.6.1 to the latest v3.2.0. The partial build time became much slower, from previous ~1.7 sec it's now ~5.5 sec. Initial builds are same ~55 sec.

Also tried to upgrade webpack-dev-middleware from ^1.10.0 to ^1.11.0 and webpack-hot-middleware from ^2.18.0 to ^2.18.2. Didn't help.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Node 8.0.0, yarn 0.24.5, macOS Sierra, [package.json](https://gist.github.com/ilearnio/1b8f8f93aa19dc4e56cd8876f459744b), no SSR enabled

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by ilearnio** [comment]
Hey @sokra. I knew you will ask this. I wish I could show you some reproducible example but it's a private project I'm working on. I thought that this issue may be there for every setup, not sure though. So maybe it can be reproduced by just trying to downgrade/upgrade Webpack on any existing setup and see if there is a difference

**Comment by dcousineau** [comment]
I unfortunately don't have a reproducible example either, however I'm also seeing increases in rebuilds in our production application. I have a 2.4 -> 3.2 upgrade staged and I'm seeing the following change in times:

Activity | 2.4 | 3.2
--------|-----|---
Prod build (e.g. full optimizations, minify) | 111.47s | **96.75s**
Local dev builds (e.g. watch mode, hot module, no minify) | 88.28s | **66.84s**
Partial rebuild (comment out random import, then uncomment) | **5.16s** | 8.32s

Commenting this to add additional reports of this behavior. (I have the latest 3.2.0 that was released yesterday)

**Comment by sokra** [comment]
It's difficult to find the issue without a reproductable repo, but I'm happy to guide you through finding it.

Could you isolate the exact version at which the build got slower? Try to isolate the dependency first. If you change webpack back to `2.4.1` does it still occur? If yes, what happens with `3.0.0`. And so on.

**Comment by the-spyke** [comment]
Same issue with my project. Rebuild on watch raised from `0.6 s` to `2 s`.

**Comment by sokra** [comment]
I think I found the issue.

**Comment by dcousineau** [comment]
❤️

**Comment by sokra** [comment]
@dcousineau @ilearnio Could you measure webpack 3.3.0 and check if this is fixed?

**Comment by dcousineau** [comment]
Keeping old numbers, but upgrading to 3.3.0 and re-running builds:

Activity | 2.4 | 3.2 | 3.3
--------|-----|----|----
Prod build (e.g. full optimizations, minify, gzip) | 111.47s | **96.75s** | 100.04s
Local dev builds (e.g. watch mode, hot module, no minify) | 88.28s | **66.84s** | 78.40s 
Partial rebuild (comment out random import, then uncomment) | 5.16s | 8.32s | **1.34s**

I noticed the very first partial rebuild was about 5s (on par with 2.4) but a subsequent re-builds hovered around the 1-1.5s range. Since rebuild time for development mode is our biggest thing, this is huge win. Thanks @sokra!

(I'm itching to use the next version of Babel with their parser speed improvements and see how much more it drops build times, as well as I'm starting to investigate DLLs to increase build speeds given how aggressive our vendor bundle is)

**Comment by ilearnio** [comment]
@sokra I just tried to install the fresh 3.3.0 version. It's still much slower as for me. The partial rebuilds are taking 3.5 - 7.5 sec compared to 1.8 sec when using Webpack v2.6.1

**Comment by the-spyke** [comment]
@ilearnio Heave you tried to update the `extract-text-webpack-plugin` to the version `3.x`? I see you use `2.x` in your `package.json`, and it's not fully compatible with `Webpack `3.x`

**Comment by the-spyke** [comment]
@sokra It my tests commenting out a function went down from `~1600ms` to `600ms` after upgrading from Webpack `3.2.0` to `3.3.0`. Awesome! Thank you!

**Comment by githoniel** [comment]
the same for me, i have update every package. but it's mucher slower than v2.6.1

**Comment by the-spyke** [comment]
@githoniel Is this with the first rebuild only? I'm on the `3.5.5` and haven't seen this issue since `3.3.0`. Do you have the same set of plug-ins?

**Comment by githoniel** [comment]
@the-spyke  
extract-text-webpack-plugin 3.0 
webpack 3.4.0 

not only the first build is slow and rebuild always do a full rebuild.

i have to downgrade to use webpack 2.7

**Comment by crazyxhz** [comment]
same issue here. I found that webpack >3 and extract-text plugin are relatived to this issue. After downgrade to webpack@2 and extract text plugin@2. Partial build is much fast. In my project. It takes about 1 sec to partial build at webpack 2, but when using the webpack 3, it takes about 16sec
