### ISSUE TITLE
When using the DllPlugin the library variable is assigned as the webpack require function

### ISSUE THREAD

**Issue by jjvainav** [webpack/webpack#5282]
**Do you want to request a *feature* or report a *bug*?**
bug/feature

**What is the current behavior?**
When the output.library is set and output.libraryTarget is 'var' the generated variable is assigned as the webpack require function when using the DllPlugin.

**What is the expected behavior?**
The library should be exposed and not the webpack require function. For example, I have a library with a helloWorld function, in order to invoke this function with the current behavior you would need to do (my_lib(1)).helloWorld(); instead of my_lib.helloWorld();

**If this is a feature request, what is motivation or use case for changing the behavior?**
Not sure if this is a bug or by-design but I am prototyping a plugin system where our customers would be able to uploaded 'extensions' to the system. I want to be able to publish a set of library components for our customers but also use them internally. 

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
webpack 3.1.0

**Comment by sokra** [comment]
If you want to have a library use the `output.library` option.

A Dll is something different.

**Comment by jjvainav** [comment]
Thanks for the response. I am using the output.library option as you suggested. 

`
    output: {
        filename: "./wwwroot/dist/my_lib.js",
        library: "my_lib"
    }
`

The resulting output has this: `module.exports = __webpack_require__(1);` and life is good.

However, if I also add the DllPlugin, the output looks like: `module.exports = __webpack_require__;` so the `my_lib` variable is no longer referencing the library but instead is referencing the webpack require method.
