### ISSUE TITLE
Allow override of webpackJsonp behavior

### ISSUE THREAD

**Issue by mohsen1** [webpack/webpack#5283]
### Feature request: provide API to hook into webpackJsonp

**What is the current behavior?**
When using code splitting, Webpack uses `webpackJsonp` function to load chunks asynchronously in a browser when a code path that requires that chunk is invoked. On the server Webpack does not do anything for loading async chunks because it doesn't know what to do.

**What is the expected behavior?**
Provide an API for overriding webpackJsonp behavior so users can hook into it and inject async chunks in HTML that server returns. 

**If this is a feature request, what is motivation or use case for changing the behavior?**
Making code splitting with async routes is very hard. Solutions like [webpack-flush-chunks](https://www.npmjs.com/package/webpack-flush-chunks) seems way too hacky for doing something simple like this.

Question: when targeting `node` does web pack do anything different for async chunks?

**Comment by sokra** [comment]
> when targeting node does web pack do anything different for async chunks?

yes, it uses `require` (target node) or `fs` + `vm` (target async-node) to load chunks.

---

You can override the `__webpack_chunk_load__` function in a bundle to hook into the chunk loading behavior.

**Comment by mohsen1** [comment]
@sokra Thanks a lot of pointing to `__webpack_chunk_load__` I was able to hook into it and generate my side-effects (adding chunk scripts to index.html). 

The only problem is, once a chunk is loaded, webpack won't call my `__webpack_chunk_load__` again. How can I unload a chunk? I see `installedChunks` object in Webpack bootstrap but there isn't a public API to it.

**Comment by sokra** [comment]
`__webpack_chunk_load__` is always called.

`import("abc")` generates code like this: `__webpack_chunk_load__(17)`

**Comment by hobbeshunter** [comment]
@mohsen1 could you go a bit into detail on how you overrode `__webpack_chunk_load__`?

thanks in advance

**Comment by mohsen1** [comment]
You can check https://github.com/lyft/universal-async-component for that

**Comment by jedwards1211** [comment]
@mohsen1 I don't see any usage of `__webpack_chunk_load__` in that repo
