### ISSUE TITLE
Binding the functions in chunk to window object

### ISSUE THREAD

**Issue by Saravana-Kumar-putta** [webpack/webpack#5287]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
When we use require.ensure to split the code, the function in chunks are not binding to window.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Need to bind the the functions in chunk to window, Is there any loader to do it, or is there any way to do it.

**If this is a feature request, what is motivation or use case for changing the behavior?**
```
require.ensure([],function(require){
var s = require('./a.js');
})
```
since the functions in `a.js` is being used by non webpack code, so I need it to bind all the functions in chunk to the window object.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by sokra** [comment]
Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md).
