### ISSUE TITLE
Use ModuleConcatenationPlugin generates code that raises exceptions

### ISSUE THREAD

**Issue by doberkofler** [webpack/webpack#5288]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
This issue is related to #5266 and describes a build configuration where the use of the ModuleConcatenationPlugin generates code that no longer executes successfully.
I've boiled down a production environment to a (hopefully) manageable repro case.

**If the current behavior is a bug, please provide the steps to reproduce.**
1) extract the attached repro case
2) run npm i
3) run npm run build
4) open index.html in browser
5) The browser should now show an exception `Uncaught ReferenceError: tinymce is not define`
6) Comment out the `new webpack.optimize.ModuleConcatenationPlugin()` in `webpack.util.js`
7) run npm run build
8) refresh index.html in browser
9) The browser should now show the tinymce browser

[webpack.zip](https://github.com/webpack/webpack/files/1147801/webpack.zip)

**What is the expected behavior?**
ModuleConcatenationPlugin not to cause any alterations of the code that make it fail

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
node: 8.1.4
npm: 4.6.1
os: windows 7

**Comment by sokra** [comment]
This seem to be a bug.

The ModuleConcatenationPlugin doesn't seem to follow evaluation order of ESM imports correctly. They are evaluated in source code occurrence order.

**Comment by doberkofler** [comment]
@sokra Wow that was quick. Happy that my example was helpful. Thank you!!!

**Comment by phaistonian** [comment]
@sokra will the be fixed in next release? 

It seems to be affecting all the "big" projects we have working on.

**Comment by felixjung** [comment]
Hey,

I also seem to have this problem. In our relatively large project, the use of ModuleConcatenationPlugin causes the code order in the entry chunk to change.

Specifically, this is a legacy AngularJS project where `angular` has to be available on `window` for our lazily loaded angular modules to be able to register. To guarantee this to work, we order our imports in the application entry accordingly.

```
import 'angular';
import './app';

angular.bootstrap(document, ['Dashboard']);
```

This works just fine when not using ModuleConcatenationPlugin. Once I enable the plugin, I get

> VM1083:1 Uncaught ReferenceError: angular is not defined

when loading the page.

**Comment by mikegreiling** [comment]
I'm running into this issue as well in @gitlab.  Some impure modules which rely on import side effects are executing in an unexpected order and breaking things.  Can't enable `ModuleConcatenationPlugin` until this is fixed 😞

**Comment by phaistonian** [comment]
@sokra: this is great news.

ETA on the new release?:)

**Comment by mikegreiling** [comment]
yay! 🎉

**Comment by sokra** [comment]
This week

**Comment by felixjung** [comment]
Awesome! Means I can ship my new build tools feature branch with webpack 3 *and* scope hoisting. Thanks! 🎉

**Comment by phaistonian** [comment]
Apparently this week is now, i.e [3.5](https://github.com/webpack/webpack/releases) :)

Thank you, @sokra.

**Comment by thecodejack** [comment]
Not sure if its related but getting this error as mentioned in the link.

https://stackoverflow.com/questions/46488914/error-after-webpack-upgrade-from-2-to-3

Basically this is happening only when I add `ModuleConcatenationPlugin` to my prod build.

```
ERROR in chunk main [entry]
[name].[chunkhash].js
'import' and 'export' may only appear at the top level (42:6)
|   if (false) {
|     module.hot.accept('./reducers', function () {
|       import('./reducers').then(function (reducerModule) {
|         var createReducers = reducerModule.default;
|         var nextReducers = createReducers(store.asyncReducers);
```
