### ISSUE TITLE
webpack --version reports 2.4.1

### ISSUE THREAD

**Issue by vp2177** [webpack/webpack#5291]
**Do you want to request a *feature* or report a *bug*?**

- Report a bug

**What is the current behavior?**

- Run `webpack --version`
- Prints `2.4.1`
- Run `webpack`
- Prints `Version: webpack 3.2.0`

**If the current behavior is a bug, please provide the steps to reproduce.**

(above)

**What is the expected behavior?**

- Print the actual version

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by neutraali** [comment]
```webpack@3.3.0``` might be misconfigured for NPM -```npm list webpack``` does not work; Webpack will not be correctly included in ```package-lock.json``` etc.

**Comment by vp2177** [comment]
@neutraali (FWIW I am using `yarn`, `yarn global list webpack` does display the correct version.)

**Comment by bfricka** [comment]
What version of yarn? From 0.25 ish to 0.27.5 yarn incorrectly symlinks bins. Explicitly upgrading to 0.28.1 fixes it. I'm guessing it's unrelated but it's worth a shot

**Comment by vp2177** [comment]
@bfricka Indeed I was using `yarn 0.27.5`

**Comment by vp2177** [comment]
Upgrading to `yarn`  `0.28.4` fixes this, not an issue with `webpack` but `yarn`
