### ISSUE TITLE
Wrong 'externals' processing

### ISSUE THREAD

**Issue by MykhailoMatiiasevych** [webpack/webpack#5292]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
webpack@3.2.0 doesn't import externals correctly.

**If the current behavior is a bug, please provide the steps to reproduce.**
Just build project from gist https://gist.github.com/MykhailoMatiiasevych/0561feca555398fcd2fc9279faae518e

dependency1 - works as expected,
dependency2 - imported as `window[undefined]`
dependency3 - cause `Invalid configuration object.` error

changing `libraryTarget` doesn't solve the issue

**What is the expected behavior?**

dependancy2 should be imported as windows['library2']['module']
dependency3 should be imported somehow without errors 

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Node.js: v8.1.4
npm: v5.0.3
webpack: 3.2.0
macOS Sierra

**Comment by MykhailoMatiiasevych** [comment]
Looks like generic https://github.com/webpack/webpack/issues/5202

**Comment by sokra** [comment]
I guess it's only implemented for the UMD libraryTarget. You can send a PR adding the same behavior for the other libraryTargets. Best extract this code into a common file.
