### ISSUE TITLE
Dynamic Loading chunkName with magic comments behavior 

### ISSUE THREAD

**Issue by ThiagoMiranda** [webpack/webpack#5293]
**Do you want to request a *feature* or report a *bug*?**

I'm not sure if it's a bug or a misbehavior from my part

**What is the current behavior?**

```javascript
static paths = {
    a: 'a',
    b: 'b',
    c: 'c'
}

constructor(x) { //x can be either a, b or c
    import(/* webpackChunkName: "[name]" */
        /* webpackMode: "lazy-once" */
        `./renderers/${paths[x]}`).then(Module => {
    });
}
```

This code is giving me a `0.js` bundle with all the scripts together ( a, b and c ). I've tried `output.chunkFilename: '[name].js'` on the webpack file but it didn't work.

**What is the expected behavior?**
The .js files be named with the given webpackChunk name.
The .js files to be separated ( I'm not sure of this but it is my goal )

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
webpack@^3.0.0 with macOS Sierra

**Comment by sokra** [comment]
> The .js files to be separated ( I'm not sure of this but it is my goal )

`webpackMode: "lazy"` or omit it.

> The .js files be named with the given webpackChunk name.

`webpackChunkName: "[request]"`

**Comment by ThiagoMiranda** [comment]
@sokra 
Thanks for the reply. But it's still not working.
No matter how I change the import /****/ coments or even ommit it, the output bundle is always the same:
0.js

Should I do something in my webpack.js config?
```javascript
entry: {
    'my.plugin': './plugin.js'
output: {
    filename: './[name].js',
    chunkFilename: '[name].bundle.js',
    path: path.resolve(__dirname, '../dist')
},
context: path.resolve(__dirname, '../src/js'),
```

**Comment by ThiagoMiranda** [comment]
@sokra this is my 'a.js' file:

```javascript
class A {

	constructor(player) {
	}

	create(element) {
	}
	
}

module.exports = A;
```

**Comment by ematipico** [comment]
I think I am experiencing the same behavior! 

```javascript
// code
 import(/* webpackChunkName: review */ "./screen/review")
```

```javascript
// configuration
output: {
  chunkFilename: [name].js
}
````

The name of the file is `0.js`

**Comment by sokra** [comment]
Please create a standalong repo to demonstrate the behavior and open a new issue.
