### ISSUE TITLE
add missingNodeModulesPlugin support

### ISSUE THREAD

**Issue by reznord** [webpack/webpack#5295]
**I'm requesting a feature**

**Current behaviour:**

Right now, if we want to add a package when development, I have to terminate the build and install the package and then I will be able to use the package.

**Motivation**

- Development becomes easy.
- Very less time to worry on these things.
- This can be a plugin which the user can plug if he wants.

**Relevant Links**

I was trying this out with one of my employers. Here is a [explanation](https://gist.github.com/reznord/c20bfa59bd7aaa286fd5838b423a4aef) on how this can be done. 

There might be a problem with this approach - it may do the build twice when the user make some changes in the code after he installs a plugin.

**Comment by cwoolum** [comment]
If you install a package while the server is running and import it into one of your modules, Webpack should automatically pull it in without a restart. That's the behavior I'm seeing with Webpack 2.7.

**Comment by evilebottnawi** [comment]
@reznord please use for automatically installed new package https://github.com/webpack-contrib/npm-install-webpack-plugin, also you can install new package without stopping webpack. Thanks for issue!
