### ISSUE TITLE
`hotDownloadManifest` in `JsonpMainTemplate.runtime.js` does not return a promise and causes exception 

### ISSUE THREAD

**Issue by miguel-guedes** [webpack/webpack#5296]
**Do you want to request a *feature* or report a *bug*?**
Report a *bug*.

**What is the current behavior?**
Hot module reloading doesn't work.

When hot reloading modules in our React Chrome extension, the HMR runtime invokes `hotDownloadManifest` in `JsonpMainTemplate.runtime.js`, which is causing an exception to be thrown. 

This begun occurring immediately after upgrading to webpack 2 from v1.13.0.

**If the current behavior is a bug, please provide the steps to reproduce.**
The problem can be summarised as follows:

1. `lib/HotModuleReplacement.runtime.js`: `hotCheck` always expects `hotDownloadManifest` to accept a timeout parameter and to return a promise.
1. `lib/JsonpMainTemplate.runtime.js`: `hotDownloadManifest` here expects a `callback` (no timeout) and does **not** return a promise.

**What is the expected behavior?**
Hot module replacement works as expected.

**If this is a feature request, what is motivation or use case for changing the behavior?**
N/A

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
node 6.11.0
webpack 3.2.0
Linux 4.8.0

**Comment by miguel-guedes** [comment]
I have just realised that `JsonpMainTemplate.runtime.js` is generated dynamically. Is webpack responsible for generating this file or might a plugin be overriding webpack's default behaviour and producing a jsonp template runtime with a function signature for `howDownloadManifest` that is only valid in webpack v1?

**Comment by sokra** [comment]
> lib/JsonpMainTemplate.runtime.js: hotDownloadManifest here expects a callback (no timeout) and does not return a promise.

not in the latest version: https://github.com/webpack/webpack/blob/master/lib/JsonpMainTemplate.runtime.js#L21

**Comment by miguel-guedes** [comment]
Okay, so I've just had yet another look, but this time making sure to install node packages from scratch **and** inspecting the contents of `JsonpMainTemplate.runtime.js` before triggering a build. It turns out that something strange seems to be happening.  

Looking at `JsonpMainTemplate.runtime.js` immediately after installing node packages, the template does indeed look like the version at https://github.com/webpack/webpack/blob/master/lib/JsonpMainTemplate.runtime.js, but as soon as a build is started, it is replaced with a version that accepts a callback.  

I wonder, is this webpack's doing or the work of some plugin?

**Comment by sokra** [comment]
That's not code I've written and afaik it was never part of webpack. Looks like one or your plugins is adding it. Could you paste your webpack.config.js?

**Comment by miguel-guedes** [comment]
Sadly the code is part of a proprietary repository and the company's policy prevents me from sharing any code or files publicly. I will definitely look into the config file and see if I can identify the offending plugin. Is there an easy way of configuring webpack or perhaps adding code in the right place that would allow me to identify the plugin that modifies the template? Unfortunately, the project builds a Chrome extension and it is not easy to disable plugins without affecting the entire build.

Thanks for all your help so far, Tobias. It is much appreciated!

**Comment by sokra** [comment]
Do you have a list of plugins for me?

**Comment by miguel-guedes** [comment]
I can definitely do that! Here's a list of webpack plugins currently in use (options included in parenthesis):

* babel-loader (`{ options: { presets: 'react-hmre' }}`)
* json-loader
* style-loader
* css-loader (`?modules&sourceMap&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]`)
* postcss-loader
* url-loader (`?name=media/[name].[ext]!img-loader`)
* webpack-hot-middleware/client (`?path=__webpack_hmr&dynamicPublicPath=true`)

The following plugins are also used and instantiated as given below:

* `new webpack.HotModuleReplacementPlugin()`
* `new webpack.NoEmitOnErrorsPlugin()`
* `new webpack.IgnorePlugin(/[^/]+\/[\S]+.prod$/)`
* `new webpack.DefinePlugin({ bunch of stuff })`

I personally suspect `webpack-hot-middleware` is at fault here but haven't been
able to confirm this.  What do you think?

**Comment by sokra** [comment]
You could try to make the file read-only. Maybe something errors out...

**Comment by sokra** [comment]
I found this:

https://github.com/jhen0409/react-chrome-extension-boilerplate/blob/master/webpack/replace/JsonpMainTemplate.runtime.js

**Comment by miguel-guedes** [comment]
Ha, that was it! That was definitely the culprit. Thanks for your help, Tobias!
