### ISSUE TITLE
ModuleConcatenation (inner): dependency variables are used (i. e. ProvidePlugin)

### ISSUE THREAD

**Issue by pelotom** [webpack/webpack#5301]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Using the `ModuleConcatenationPlugin` with `--display-optimization-bailout` I get a warning on most of my modules:

```
ModuleConcatenation (inner): dependency variables are used (i. e. ProvidePlugin)
```

As far as I can tell this is not the case. These modules are not referencing any special variables that they haven't imported.

What are all the ways this warning could occur? I'm not using `ProvidePlugin`.

**If the current behavior is a bug, please provide the steps to reproduce.**

This is for a private repo so I can't attach the code. It doesn't seem to happen with the "toy" examples that I build.

**Comment by sokra** [comment]
Are you using `module.???` in the module?

**Comment by pelotom** [comment]
No, I'm not using any variables that aren't either defined within the module or explicitly imported.

**Comment by pelotom** [comment]
Ah, so I take that back: I was using `Buffer`, and that appears to have been causing the deoptimization. Is it expected that referencing `Buffer` would do this?

**Comment by sokra** [comment]
Yep Buffer is also deoptinized. But we plan to remove this limitation in future.

**Comment by pelotom** [comment]
Cool, is there an issue I can subscribe to to stay apprised of progress on that?

**Comment by pelotom** [comment]
It looks like it can be worked around for now by just putting

```js
import { Buffer } from 'buffer';
```

at the top of any file referencing `Buffer`.

**Comment by sokra** [comment]
Watch the changelog...
