### ISSUE TITLE
Defered/Dynamic files loading

### ISSUE THREAD

**Issue by lzanol** [webpack/webpack#5307]
**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**

When I try to bundle/load some JS files from a given dir with `import()` command (`/* webpackChunkName: "[name]" */`, `/* webpackMode: "lazy" */`), Webpack is joining all of them into a single bundle.

I doesn't matter if I change the configs into the comments the behavior is always the same.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

Webpack should split each of the files into separate bundles.

**If this is a feature request, what is motivation or use case for changing the behavior?**

N/A

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

- webpack.js
```javascript
...
entry: {
    'my.plugin': './some-plugin.js'
output: {
    path: path.resolve(__dirname, '../dist'),
    chunkFilename: '[name].bundle.js',
    filename: './[name].js'
},
context: path.resolve(__dirname, '../src/js')
...
```

- OS X El Capitan 10.11.6
- Webpack 3.0.0
- Node 6.10.2

**Comment by sokra** [comment]
`webpackChunkName: "[name]"` doesn't make sense. Omit it.
