### ISSUE TITLE
Static code analysis for bundles - custom call expression

### ISSUE THREAD

**Issue by emilos** [webpack/webpack#5310]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

Currently webpack does static code analysis for async loading and searches for call expressions like:

```js
require(["foo"], function (Foo) {});
```

**What is the expected behavior?**

It would be great if the tool could handle custom call expressions for asynchronous loading too, e.g.:

```js
this.require(["foo"], function (Foo) {});
```

**If this is a feature request, what is motivation or use case for changing the behavior?**

Please consider the following scenario:
- user navigates to `/foo` and loads `foo.js`, you spin a full page loader,
- user clicks `go back` button in the browser, loader hides,
- user navigates to `/bar` and loads `bar.js`, you spin a full page loader (`foo.js` did not finish loading yet),
- you have both `foo.js` and `bar.js` loading right now, there is a race condition and the `require` callbacks will fire in an unknown order

While there are few possibilities how to fix this the solution that was chosen was to provide a `require` method that calls real require under the hood. It also has a guard check inside that only calls the appropriate callback.

The app was originally written with use of requirejs and is being migrated to webpack step by step. The feature above would help a lot.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

node v8.1.4, webpack 3.3.0 and ubuntu 14.10

I'd be happy to contribute if the above makes sense :)

**Comment by sokra** [comment]
In my opinion it's better to rewrite the code to the standard `require` syntax (or better to `import()`). The changes needed are only minimal compared to the changes needed to support this.

I won't implement it and don't think it should be part of webpack, but your can write a custom plugin to handle this if you want to.

**Comment by emilos** [comment]
Thank you for your time and the quick reply - I thought that this use case might be too narrow to justify it. Rewriting it does not fully solve the problem but I'll investigate other approaches.

Thanks again.
