### ISSUE TITLE
Add support for ES6 features

### ISSUE THREAD

**Issue by jampy** [webpack/webpack#532]
Currently webpack seems to fail parsing JavaScript code that contains ES6 syntax like generators.

```
Module parse failed: ..../main.js Line 20: Unexpected token *
You may need an appropriate loader to handle this file type.
| }
| 
| function * ex_test() {
|   throw new Error("work!");
| }
```

Could you please adjust the static code analysis so that it doesn't break with code that uses generators?

I'm trying to use generators **natively** in browsers that support them, so don't want to use a transpiler in this case..

**Comment by sokra** [comment]
#683

**Comment by pornel** [comment]
:+1: I'd like to use ES6 output too.

Esprima 2 is now available and Webpack tests pass with 2.1.0.

**Comment by sokra** [comment]
This should work in the `webpack-2` branch

**Comment by jhnns** [comment]
@pornel webpack-2 is using [acorn](https://github.com/marijnh/acorn).

**Comment by Sinewyk** [comment]
Any news on this ? Is there a way to hack it to let webpack just pass through es6 code, and let the developer the responsibility to send supported code to wherever ?

**Comment by remimarenco** [comment]
:+1:

**Comment by dbrans** [comment]
Hi, has anyone found a solution/workaround?
Cheers

**Comment by sokra** [comment]
You can use the webpack-2 branch. It is using a ES6 parser (acorn) and understands `import` `export` and `System.import`.

**Comment by ariya** [comment]
@sokra I experimented with bumping the dependencies (`package.json`) to Esprima 2.5, ran `npm test` and so far nothing breaks the tests. This is the easiest to allow webpack to consume ES6 code.
Is this something that is desireable? If yes, I can create a PR.

**Comment by sokra** [comment]
> @sokra I experimented with bumping the dependencies (package.json) to Esprima 2.5, ran npm test and so far nothing breaks the tests. This is the easiest to allow webpack to consume ES6 code.
> Is this something that is desireable? If yes, I can create a PR.

I've bumped it in 1.11... Let's see how this works out.

**Comment by XeCycle** [comment]
1.12 is working for my project (babel blacklist regenerator), and tests passed, though very low coverage.  Maybe this can be closed, if no need for further confirmations.
