### ISSUE TITLE
Unclear error message in case of Exclamation mark in project path breaking the build on Windows

### ISSUE THREAD

**Issue by pmunin** [webpack/webpack#5320]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
On Windows build if the path of the project folder contains "!", webpack will throw error:
```
    ERROR in Entry module not found: Error: Can't resolve 'C:\' in 'C:\!ParentFolder\MyProjectFolder'
```
This bug was already reported #4906 with steps to reproduce. And it was closed, I'm opening this one to attract attention that this issue creates hard time for new users of webpack who do not know about this limitation, since webpack does not give any clue to the user about it. It took an hour of my time to figure out why it's not working.

**If the current behavior is a bug, please provide the steps to reproduce.**
see #4906
or:
1) Take any project with webpack (e.g. https://github.com/pmunin/handsontable)
2) Put (or clone) it in any folder, with the name starting from "!" (exclamation mark)
3) run webpack build (e.g. "npm run build:umd" for repo provided at step 1)

**What is the expected behavior?**
Webpack should at least provide a proper error message saying that user cannot have Exclamation marks in the path.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
OS: Windows 10 x64
node v6.3.1
npm v3.10.3
webpack v2.6.1

**Comment by sokra** [comment]
You could send a PR to https://github.com/webpack/webpack/blob/master/schemas/ajv.absolutePath.js validating that an absolute path do not contain an `!` with a useful message.

**Comment by wwwy3y3** [comment]
Hi @sokra I'd like to help on this PR
I got some questions here related to this issue, hope you could help me out.
* Is the exclamation mark `!` forbid on all platform or just Windows?
* Is there any reason why `!` reserved in path?
* Are there any reserved char other than `!` ?
Many thanks!

**Comment by addohm** [comment]
I'm having this same issue.  Will this be fixed?

**Comment by koutsenko** [comment]
Same issue.

**Comment by simonl65** [comment]
+1

I just lost hours of work trying to figure why nuxt wouldn't work only to find it was an exclamation mark in my Windows path. I do this all the time - it places my folders higher up the folder list. Please would you consider removing this restriction?

Cheers,
Simon

**Comment by pmunin** [comment]
I guess the reason for this restriction is module loader syntax (https://webpack.js.org/loaders/).
E.g.: `import Styles from 'style-loader!css-loader?modules!./styles.css';` Not the best design decision, but at least they can provide a message for that so people don't spend a day for finding this.

**Comment by simonl65** [comment]
Agreed - a meaningful message might have saved my hair!
