### ISSUE TITLE
Plugins always emitted in watch mode

### ISSUE THREAD

**Issue by doronbrikman** [webpack/webpack#5321]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When I'm on watch mode, plugins like `html-webpack-plugin` and `extract-text-webpack-plugin` always emitted, even when I'm changing something in my js file.
It started when I upgraded to webpack@3.3.0.
When I go back to webpack@2.3.3 it doesn't happen.

a minimal reproduceable example:

config:
```
const path = require('path');
const HtmlWebpackPlugin = require("html-webpack-plugin");

module.exports = {
    entry: './app.js',
    output: {
        filename: 'bundle.js',
        path: path.resolve(__dirname, 'dist')
    },
    module: {
        rules: [
            {
                test: /\.css$/,
                use: [
                    'style-loader',
                    'css-loader'
                ]
            }
        ]
    },
    plugins: [
        new HtmlWebpackPlugin({
            template: 'index.html',
        }),
    ]
};
```

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
If I change a js file I expected only the js bundle to be emitted when I'm on watch mode

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
node: 6.11.1
wepack: 3.3.0
windows 10

**Comment by ismail-syed** [comment]
Can confirm this is a bug. I was able to reproduce this in webpack@3.0.0, but not webpack@2.7.0.
I believe this bug was introduced in webpack@3.0.0.

**Comment by ismail-syed** [comment]
`git bisect` resulted in this for me.

```
╰─$ git bisect bad
The merge base 302289ce2475432276d5ae3355aeef2640efdedf is bad.
This means the bug has been fixed between 302289ce2475432276d5ae3355aeef2640efdedf and [7cfd2c490ea96c9676e8de54f2e7b6d1
214722da e0c524e43116621f5a2938e54ee1d9644b1b467a eeea490e8ec0e2341cd4bb6da82aabf6ca139322].
```

**Comment by sokra** [comment]
https://github.com/webpack/webpack/releases/tag/v3.0.0

> child compilations get records and cache assigned (they need a unique name) [breaking change]

This is a new requirement for plugins that use child compilations. The name must be unique. Afaik this is implemented in the latest version of extract-text-webpack-plugin. Not sure about html-webpack-plugin.

Do you use the latest versions?

**Comment by doronbrikman** [comment]
Yes.

Here are the versions I'm using:
extract-text-webpack-plugin@3.0.0
html-webpack-plugin@2.30.1

**Comment by doronbrikman** [comment]
I did a check now, if I'm using webpack@2.7.0 it's also re-compile the css files when I'm only changing js file.
But in webpack@3.4.1 it's also re-compile the html

with webpack@2.7.0:
```
Version: webpack 2.7.0
Time: 947ms
     Asset       Size  Chunks             Chunk Names
 bundle.js    3.08 kB       0  [emitted]  main
styles.css   26 bytes       0  [emitted]  main
index.html  123 bytes          [emitted]  
   [0] ./app.css 41 bytes {0} [built]
   [1] ./app.js 21 bytes {0} [built]
   [2] ./~/css-loader!./app.css 192 bytes [built]
   [3] ./~/css-loader/lib/css-base.js 2.26 kB [built]
   [4] ./~/style-loader/lib/addStyles.js 8.7 kB [built]
   [5] ./~/style-loader/lib/urls.js 3.01 kB [built]
Child html-webpack-plugin for "index.html":
       [0] ./~/lodash/lodash.js 540 kB {0} [built]
       [1] ./~/html-webpack-plugin/lib/loader.js!./index.html 368 bytes {0} [bu
ilt]
       [2] (webpack)/buildin/global.js 509 bytes {0} [built]
       [3] (webpack)/buildin/module.js 517 bytes {0} [built]
Child extract-text-webpack-plugin:
       [0] ./~/css-loader/lib/css-base.js 2.26 kB {0} [built]
       [1] ./~/css-loader!./app.css 192 bytes {0} [built]
Hash: 5106c56d063800893c8e
Version: webpack 2.7.0
Time: 34ms
     Asset      Size  Chunks             Chunk Names
 bundle.js   3.08 kB       0  [emitted]  main
styles.css  26 bytes       0  [emitted]  main
   [1] ./app.js 23 bytes {0} [built]
    + 1 hidden modules
Child html-webpack-plugin for "index.html":
        + 4 hidden modules
```

with webpack@3.4.1:
```
Version: webpack 3.4.1
Time: 6422ms
     Asset       Size  Chunks             Chunk Names
 bundle.js    2.92 kB       0  [emitted]  main
styles.css   26 bytes       0  [emitted]  main
index.html  123 bytes          [emitted]  
   [0] ./app.js 23 bytes {0} [built]
   [1] ./app.css 41 bytes {0} [built]
   [2] ./node_modules/css-loader!./app.css 192 bytes [built]
    + 3 hidden modules
Child html-webpack-plugin for "index.html":
       [0] ./node_modules/html-webpack-plugin/lib/loader.js!./index.html 368 by
tes {0} [built]
       [2] (webpack)/buildin/global.js 509 bytes {0} [built]
       [3] (webpack)/buildin/module.js 517 bytes {0} [built]
        + 1 hidden module
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist
 node_modules/css-loader/index.js!app.css:
       [0] ./node_modules/css-loader!./app.css 192 bytes {0} [built]
        + 1 hidden module
Hash: 746b09b4279751b7d68e
Version: webpack 3.4.1
Time: 125ms
     Asset       Size  Chunks             Chunk Names
 bundle.js    2.92 kB       0  [emitted]  main
styles.css   26 bytes       0  [emitted]  main
index.html  123 bytes          [emitted]  
   [0] ./app.js 21 bytes {0} [built]
    + 1 hidden module
Child html-webpack-plugin for "index.html":
       4 modules
```

So I think the new issue only happens in the `html-webpack-plugin` with webpack 3.
But it's seems there's a problem with the `extract-text-webpak-plugin` with both webpack3 and webpack2.

with `webpack@2.7.0` I use `extract-text-webpack-plugin@2.1.2`

**Comment by TheLarkInn** [comment]
@d3viant0ne do you want to x-post this in ETWP?

**Comment by d3viant0ne** [comment]
Sure, send it over with the bot

**Comment by sokra** [comment]
@webpack-bot move to webpack/extract-text-webpack-plugin

**Comment by bs-thomas** [comment]
I'm having the issue too with @doronbrikman where I'm only changing the JS file, but CSS file is being emitted.  This slowed down my build significantly.
