### ISSUE TITLE
Webpack should avoid including file content which contains no explicitly imported modules

### ISSUE THREAD

**Issue by dzearing** [webpack/webpack#5324]
**Do you want to request a *feature* or report a *bug*?**
Feature (I think?)

**What is the current behavior?**

Let's say I have a component library, such as Office UI Fabric React. I export many components, such as the Button, Dropdown, and Toggle.

As an application consuming the library, i use webpack to import only the Toggle:

```tsx
import { Toggle } from 'office-ui-fabric-react';
```

The library package has an index top level file that exports all of the components. (all es6 modules). The package.json and has a `module` entry pointing to the index.

I expect that only the code from Toggle.tsx (and its dependencies which it imports) are included in the pre-bundle output. It is the *only* imported module in my app.

Webpack ends up including the entire library in the pre-minified bundle, leaving the "tree shaking" up to Uglify. We can do better though.

This means that if Button.tsx has any global code, it will get included and there is no way Uglify would remove it... but I never explicitly imported button.

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/dzearing/test-webpack-library-shaking

**What is the expected behavior?**

Webpack should avoid including file content where the file contains no explicitly imported modules.

**If this is a feature request, what is motivation or use case for changing the behavior?**

This specific issue prevents tree shaking from working as expected. Effectively, any global code is guaranteed to be included with the bundle, even when you don't import it, simply because the root export has a graph edge to it. This happens all the time. It should only be included if there is an explicit import to that file.

If this change has too many potential side effects (maybe there are?) I'm perfectly happy with this being a config opt-in option, but i would opt in on every project.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

webpack 3.0.0
not dependent on node version or os

**Comment by sokra** [comment]
> Webpack should avoid including file content where the file contains no explicitly imported modules.

The ESM spec says this code should evaluated even if the exports are not used.

**Comment by dzearing** [comment]
What does "evaluated" mean? I assume webpack is evaluating whether the code is included in the final product, but is this specific about having uglify evaluate?

Without this the whole idea of tree shaking seems rather fragile and doesnt do whats expected unless you follow very specific semantics. If thats the case then we would need even greater gates, like "global code is prohibited in es6". Including static initialization.

**Comment by MLoughry** [comment]
To be clear, if it makes a difference, the code isn't imported before being exported; it's [exported directly](https://github.com/OfficeDev/office-ui-fabric-react/blob/master/packages/office-ui-fabric-react/src/index.ts):
```
...
export * from './Toggle';
...
```

**Comment by Makio64** [comment]
For me the simple solution without breaking all the logic would be to create a DeleteUnusedExportPlugin and start it before the threeshaking:  

- Step 1 : for each file imported flag the property imported
- Step 2 : for each file imported, delete/change the export line base on the flags of Step1
example: export {Foo1, Foo2, Foo2} => export {Foo2}

I have only one experience writing plugin for webpack but is this make sense / is possible?
I'll try to get the time to give it a shot :)

**Comment by TheLarkInn** [comment]
@Makio64 This is possible and similar to what @jdalton did with lodash-webpack-plugin. You could use this as prior art and inspiration for your own.

**Comment by Makio64** [comment]
yeah, i will check his plugin and give a try to make it more generic next week :)

**Comment by RReverser** [comment]
> What does "evaluated" mean?

Evaluated means evaluated as any other JavaScript because if can be imported just for side effects.

**Comment by jdalton** [comment]
You might also want to see if the techniques in [webpack-common-shake](https://github.com/indutny/webpack-common-shake) may apply in this context.
