### ISSUE TITLE
webpack 3.3.0 lazy load callback is undefined

### ISSUE THREAD

**Issue by cruzlauroiii** [webpack/webpack#5328]
**Do you want to request a *feature* or report a *bug*?** 

this is a bug

**What is the current behavior?**

not loading correctly in order and callback return is undefined. 

functions in callback scope are executed earlier.

**If the current behavior is a bug, please provide the steps to reproduce.**

i have nested files:

``` js
//index.js
import(/* webpackChunkName: "assets/Events/bind" */ 'Events/bind').
then(cb => {
console.log("should be last.")
})
```

``` js
// assets/Events/listener.js
import(/* webpackChunkName: "assets/Events/index" */ 'Events/index').
then(cb => {
const {Company} = cb
Company.events.listener = function(){
  console.log('success')
}
exports.Company = Company
})
```

``` js
// assets/Events/bind.js
import(/* webpackChunkName: "assets/Events/index" */ 'Events/index').
then(cb => {
const {Company} = cb
Company.events.bind = function(){
import(/* webpackChunkName: "assets/Events/listener" */ 'Events/listener').
then(cb => {
    Company.events.listener()
})
}
exports.Company = cb
})
```

``` js
// assets/Events/index.js
import(/* webpackChunkName: "assets/Events/index" */ 'Events/index').
then(cb => {

const {Company} = cb
Company.events = {}
exports.Company = Company

})
```

``` js
// assets/Company/index.js
const Company = {}
exports.Company = Company
```

**What is the expected behavior?**

callback should return a value of  exports.foo to caller

**If this is a feature request, what is motivation or use case for changing the behavior?**

bug

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

node v8.1.4

**Comment by sokra** [comment]
You incorrectly assuming that `import()` waits for nested `import()`s. That's not true. Assigning `exports` in a callback in any async operation is (in most cases) wrong. A module counts as evaluated when the first sync evaluation has finished.

Don't mix `exports.` (CommonJs export) with ESM. Rewrite your code to use `import` (not `import()`) and `export` (not `exports.`). i. e.

``` js
// assets/Events/listener.js
import { Company } from 'Events/index';

Company.events.listener = function(){
  console.log('success')
}
export { Company }
```

This should work.

**Comment by cruzlauroiii** [comment]
then you must change the documentation then..

https://webpack.js.org/guides/lazy-loading/

// Note that because a network request is involved, some indication
+   // of loading would need to be shown in a production-level site/app.
+   button.onclick = e => import(/* webpackChunkName: "print" */ './print').then(module => {
+     var print = module.default;
+
+     print();
+   });

all of the webpack documentation is wrong.. 

module should be undefined..

im just relying on docs. and clearly there is a bug here..

and yes. please open this as i will make a patch.

**Comment by cruzlauroiii** [comment]
i wad referring to .then callback
`import(/* webpackChunkName: "print" */ './print').then(module => {
module.default // bug here as its undefined if not loaded yet. in the documentation its returning a value. if its not loaded yet it downloading it on the fly.
})`

**Comment by ematipico** [comment]
You have two options:
1. download on the fly in a cascading order
2. download them all together using a `Promise.all`

1
```javascript
import('a').then(a => {
  import('b').then(b => {
    const { aSomething } = a;
    const { bSomething } = b;
    // ... do what you want
  }) 
})
```

2
```javascript
const promiseA = import('a');
const promiseB = import('b');
Promise.all([promiseA, promiseB]).then((a, b) => {
    const { aSomething } = a;
    const { bSomething } = b;
    // ... do what you want
})
```

**Comment by sokra** [comment]
> bug here as its undefined if not loaded yet. in the documentation its returning a value. if its not loaded yet it downloading it on the fly.

This works.

Just make sure to use `export default ...`

**Comment by cruzlauroiii** [comment]
i think i can fix the bug here..

instead of return promise

should be return Promise.all(promise)

so .then will not be undefined

**Comment by cruzlauroiii** [comment]
like i said export is undefined in the return of .then when the resource is not yet finished downloaded.

**Comment by cruzlauroiii** [comment]
its very clear that for async you can just import and the next line the code will execute. thats called async. but if you put the code inside the .then function, it should execute only after the promise is completed or rejected. in this case the code is executed in .then function even the promise is still pending which i think a bug.
