### ISSUE TITLE
How to refer bundled modules from external JS template loading dynamically

### ISSUE THREAD

**Issue by imsurinder90** [webpack/webpack#5330]
**Do you want to request a *feature* or report a *bug*?**
I am having an issue which i am facing and unable to figure out solution.

I already asked on stackoverflow but didn't got any solution yet.

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**
The link to question asked on Stackoverflow:

https://stackoverflow.com/questions/45216324/webpack-how-to-refer-bundled-modules-from-external-js-template-loading-dynamica

Webpack configuration files: webpack.config.js and webpack.shim.js
https://gist.github.com/imsurinder90/a5ebf5690336667f2fb9679eb3c95a2e.js

Project repo
https://github.com/postgres/pgadmin4/tree/master/web

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
node --version
v8.0.0

./web/node_modules/webpack/bin/webpack.js --version
3.0.0

Mac OSx Yosemite 10.10.2

**Comment by sokra** [comment]
webpack doesn't provide a mechanism for this. You need to use globals or pass arguments to the external.
