### ISSUE TITLE
Filtering assets within the stats, like modules

### ISSUE THREAD

**Issue by ldrick** [webpack/webpack#5333]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Within the stats the assets can not be filtered, only enabled or disabled.

**If the current behavior is a bug, please provide the steps to reproduce.**
not a bug

**What is the expected behavior?**
Being able to filter assets from stats, like modules and chunks.

**If this is a feature request, what is motivation or use case for changing the behavior?**
 Copy-Webpack-Plugin makes use of assets, which can result in heavy output. Filtering the stats.assets would enable users or the plugin-maintainer to disable verbosity. Maybe stats.exclude can be used, it already allows string[], RegExp[] and function[], while function[] seems to not be documented. I am referring to [Is it possible to tell copy-webpack-plugin to be less verbose ?](https://github.com/kevlened/copy-webpack-plugin/issues/113)

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
webpack 3.3.0

**Comment by sokra** [comment]
Sounds like a good idea. Feel free the send a PR adding `excludeAssets` or similar.

**Comment by ketamin** [comment]
Ok, I'll come back to this one next week. Thanks

**Comment by ldrick** [comment]
This already landet and I use it actively. So I think this issue can be closed.

**Comment by mohsenshafiei** [comment]
I use this webpack-plugin: https://www.npmjs.com/package/webpack-shower
