### ISSUE TITLE
bug: ExtendedAPIPlugin incorrectly causes 'cannot use [chunkhash] error'

### ISSUE THREAD

**Issue by hulkish** [webpack/webpack#5337]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
Usage of `[chunkhash]` for both `output.filename` & `output.chunkFilename` along with `ExtendedAPIPlugin` causes incorrect compilation error.

**If the current behavior is a bug, please provide the steps to reproduce.**

**Demo**: https://github.com/hulkish/webpack-ExtendedAPIPlugin-bug

1. In your webpack config, set your output to:
```js
output: {
  filename: '[name].[chunkhash].js',
  chunkFilename: '[id].[chunkhash].js'
}
```
2. Add `ExtendedAPIPlugin`:
```js
plugins: [new ExtendedAPIPlugin()]
```
3. Run the build & get this error:
```bash
ERROR in chunk main [entry]
[name].[chunkhash:5].js
Cannot use [chunkhash] for chunk in '[name].[chunkhash].js' (use [hash] instead)
```

**What is the expected behavior?**
Should not cause this error.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
`node@8.2.0`, `yarn@0.27.5`, `webpack@3.3.0`

**Comment by hulkish** [comment]
Quick update - after a little debugging I found it's coming from [this line](https://github.com/webpack/webpack/blob/master/lib/ExtendedAPIPlugin.js#L35)

**Comment by ematipico** [comment]
@sokra Do you think removing that line would break something else? I could send a PR.

**Comment by gabrielhpugliese** [comment]
Is there any workaround for this? Any 3rd party libs?

**Comment by hulkish** [comment]
@gabrielhpugliese  [this](https://github.com/webpack/webpack/issues/5337#issuecomment-317000307) seems to be the only work around at the moment that im aware of. I'm unsure of what impact commenting out that line will have, though.

**Comment by ematipico** [comment]
This should have a solution :)
I don't want to have this gets closed

**Comment by ematipico** [comment]
Can anyone have a look at this please? This stops from using cache busting and chunkhash properly. @sokra @ooflorent

**Comment by ooflorent** [comment]
There is a PR to improve the error message: #6942
However, I don't understand the limitation.

**Comment by ICELI** [comment]
### bug analyze
Compare with `APIPlugin.js` and `ExtendedAPIPlugin.js`, we will find this line:  
[ExtendedAPIPlugin.js#L35](https://github.com/webpack/webpack/blob/v3.3.0/lib/ExtendedAPIPlugin.js#L35)
```js
compilation.mainTemplate.plugin("global-hash", () => true);
```

so, `useChunkHash` fn always return `false`
[MainTemplate.js#L229](https://github.com/webpack/webpack/blob/v3.3.0/lib/MainTemplate.js#L229)
```js
useChunkHash(chunk) {
	const paths = this.applyPluginsWaterfall("global-hash-paths", []);
	return !this.applyPluginsBailResult("global-hash", chunk, paths); // always return `false`
}
```
then `noChunkHash` always `true`  
[Compilation.js#L1266](https://github.com/webpack/webpack/blob/v3.3.0/lib/Compilation.js#L1266)
```js
file = this.getPath(filenameTemplate, {
	noChunkHash: !useChunkHash,
	chunk
});
```
then `asset-path` plugin will throw the error
```
Cannot use [chunkhash] for chunk in '${path}' (use [hash] instead)
```
[TemplatedPathPlugin.js#L63](https://github.com/webpack/webpack/blob/v3.3.0/lib/TemplatedPathPlugin.js#L63)
```js
// replacePathVariables
if(data.noChunkHash && REGEXP_CHUNKHASH_FOR_TEST.test(path)) {
	throw new Error(`Cannot use [chunkhash] for chunk in '${path}' (use [hash] instead)`);
}
```

by commenting out the following line in the [ExtendedAPIPlugin.js#L35](https://github.com/webpack/webpack/blob/v3.3.0/lib/ExtendedAPIPlugin.js#L35), it works fine.

### hack fix:  
1. create `ExtendedAPIPlugin.js`
```js
/*
	MIT License http://www.opensource.org/licenses/mit-license.php
	Author Tobias Koppers @sokra
*/
"use strict";

const ConstDependency = require("webpack/lib/dependencies/ConstDependency");
const ParserHelpers = require("webpack/lib/ParserHelpers");
const NullFactory = require("webpack/lib/NullFactory");

const REPLACEMENTS = {
	__webpack_hash__: "__webpack_require__.h", // eslint-disable-line camelcase
	__webpack_chunkname__: "__webpack_require__.cn" // eslint-disable-line camelcase
};
const REPLACEMENT_TYPES = {
	__webpack_hash__: "string", // eslint-disable-line camelcase
	__webpack_chunkname__: "string" // eslint-disable-line camelcase
};

class ExtendedAPIPlugin {
	apply(compiler) {
		compiler.plugin("compilation", (compilation, params) => {
			compilation.dependencyFactories.set(ConstDependency, new NullFactory());
			compilation.dependencyTemplates.set(ConstDependency, new ConstDependency.Template());
			compilation.mainTemplate.plugin("require-extensions", function(source, chunk, hash) {
				const buf = [source];
				buf.push("");
				buf.push("// __webpack_hash__");
				buf.push(`${this.requireFn}.h = ${JSON.stringify(hash)};`);
				buf.push("");
				buf.push("// __webpack_chunkname__");
				buf.push(`${this.requireFn}.cn = ${JSON.stringify(chunk.name)};`);
				return this.asString(buf);
			});
			// compilation.mainTemplate.plugin("global-hash", () => true);

			params.normalModuleFactory.plugin("parser", (parser, parserOptions) => {
				Object.keys(REPLACEMENTS).forEach(key => {
					parser.plugin(`expression ${key}`, ParserHelpers.toConstantDependency(REPLACEMENTS[key]));
					parser.plugin(`evaluate typeof ${key}`, ParserHelpers.evaluateToString(REPLACEMENT_TYPES[key]));
				});
			});
		});
	}
}

module.exports = ExtendedAPIPlugin;
```

2. import the custom plugin in `webpack.config.prod.js`
```
const ExtendedAPIPlugin = require('./ExtendedAPIPlugin');
// ...
plugins: [
    // ...
    new ExtendedAPIPlugin()
]
```

**Comment by ICELI** [comment]
### bug analyze
Compare with `APIPlugin.js` and `ExtendedAPIPlugin.js`, we will find this line:  
[ExtendedAPIPlugin.js#L35](https://github.com/webpack/webpack/blob/v3.3.0/lib/ExtendedAPIPlugin.js#L35)
```js
compilation.mainTemplate.plugin("global-hash", () => true);
```

so, `useChunkHash` fn always return `false`
[MainTemplate.js#L229](https://github.com/webpack/webpack/blob/v3.3.0/lib/MainTemplate.js#L229)
```js
useChunkHash(chunk) {
	const paths = this.applyPluginsWaterfall("global-hash-paths", []);
	return !this.applyPluginsBailResult("global-hash", chunk, paths); // always return `false`
}
```
then `noChunkHash` always `true`  
[Compilation.js#L1266](https://github.com/webpack/webpack/blob/v3.3.0/lib/Compilation.js#L1266)
```js
file = this.getPath(filenameTemplate, {
	noChunkHash: !useChunkHash,
	chunk
});
```
then `asset-path` plugin will throw the error
```
Cannot use [chunkhash] for chunk in '${path}' (use [hash] instead)
```
[TemplatedPathPlugin.js#L63](https://github.com/webpack/webpack/blob/v3.3.0/lib/TemplatedPathPlugin.js#L63)
```js
// replacePathVariables
if(data.noChunkHash && REGEXP_CHUNKHASH_FOR_TEST.test(path)) {
	throw new Error(`Cannot use [chunkhash] for chunk in '${path}' (use [hash] instead)`);
}
```

by commenting out the following line in the [ExtendedAPIPlugin.js#L35](https://github.com/webpack/webpack/blob/v3.3.0/lib/ExtendedAPIPlugin.js#L35), it works fine.

### hack fix:  
1. create `ExtendedAPIPlugin.js`
```js
/*
	MIT License http://www.opensource.org/licenses/mit-license.php
	Author Tobias Koppers @sokra
*/
"use strict";

const ConstDependency = require("webpack/lib/dependencies/ConstDependency");
const ParserHelpers = require("webpack/lib/ParserHelpers");
const NullFactory = require("webpack/lib/NullFactory");

const REPLACEMENTS = {
	__webpack_hash__: "__webpack_require__.h", // eslint-disable-line camelcase
	__webpack_chunkname__: "__webpack_require__.cn" // eslint-disable-line camelcase
};
const REPLACEMENT_TYPES = {
	__webpack_hash__: "string", // eslint-disable-line camelcase
	__webpack_chunkname__: "string" // eslint-disable-line camelcase
};

class ExtendedAPIPlugin {
	apply(compiler) {
		compiler.plugin("compilation", (compilation, params) => {
			compilation.dependencyFactories.set(ConstDependency, new NullFactory());
			compilation.dependencyTemplates.set(ConstDependency, new ConstDependency.Template());
			compilation.mainTemplate.plugin("require-extensions", function(source, chunk, hash) {
				const buf = [source];
				buf.push("");
				buf.push("// __webpack_hash__");
				buf.push(`${this.requireFn}.h = ${JSON.stringify(hash)};`);
				buf.push("");
				buf.push("// __webpack_chunkname__");
				buf.push(`${this.requireFn}.cn = ${JSON.stringify(chunk.name)};`);
				return this.asString(buf);
			});
			// compilation.mainTemplate.plugin("global-hash", () => true);

			params.normalModuleFactory.plugin("parser", (parser, parserOptions) => {
				Object.keys(REPLACEMENTS).forEach(key => {
					parser.plugin(`expression ${key}`, ParserHelpers.toConstantDependency(REPLACEMENTS[key]));
					parser.plugin(`evaluate typeof ${key}`, ParserHelpers.evaluateToString(REPLACEMENT_TYPES[key]));
				});
			});
		});
	}
}

module.exports = ExtendedAPIPlugin;
```

2. import the custom plugin in `webpack.config.prod.js`
```
const ExtendedAPIPlugin = require('./ExtendedAPIPlugin'); // your file path
// ...
plugins: [
    // ...
    new ExtendedAPIPlugin()
]
```

**Comment by hulkish** [comment]
@ICELI Sounds like you might have an actual fix, why not make pr?

**Comment by rheaditi** [comment]
Is there any resolution for this? Looks like #7987 got closed.. 🙁

**Comment by glen-84** [comment]
If I'm understanding [this](https://github.com/webpack/webpack/pull/7987#pullrequestreview-153760830) correctly:

* The `ExtendedAPIPlugin` adds `__webpack_hash__` to the runtime<sup>[1]</sup>.
* Because the global hash is included in the runtime, the `chunkhash` of the runtime needs to change with any change to the compilation.
* I'm assuming that the chunkhash of the runtime is calculated on source before the global hash is included, so it's not changing (?).
* It's not possible to set a different `filename`/`chunkFilename` to be used by the runtime only, which would have allowed us to just use `hash` there.

---

[1] There could be multiple runtimes.

**Comment by shaodahong** [comment]
https://github.com/webpack/webpack.js.org/pull/3185

**Comment by evilebottnawi** [comment]
bump
