### ISSUE TITLE
Minification not working with es6

### ISSUE THREAD

**Issue by fearrr** [webpack/webpack#5341]
**Do you want to request a *feature* or report a *bug*?** 
*bug*

**What is the current behavior?**
i get error : 
`ERROR in 0.js from UglifyJs`
`Unexpected token: name (that) [0.js:581,16]`

**If the current behavior is a bug, please provide the steps to reproduce.**

I run the production build for vue.js app, and get the problem in `0.js`
this file is cut of require.ensure and contain in itself vue component (es6 syntax).

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

If i don't use minification, then everything is built without errors

If i don't use es6 syntax , then everything is built without errors

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
windows 10, 
node v8.1.4, 
npm v5.3.0,
webpack v3.3.0

dependencies 

babel-core ^6.25.0
babel-loader ^7.1.1
babel-preset-env ^1.6.0

vue-html-loader ^1.2.4
vue-loader ^12.2.2",
vue-style-loader ^3.0.1
vue-template-compiler ^2.4.1

**Comment by probablyup** [comment]
@fearrr Yeah uglify doesn't know about ES6 syntax. You'll either need to transpile to ES5 or use Babili. https://github.com/babel/babili

**Comment by probablyup** [comment]
Or I suppose use this plugin instead: https://github.com/webpack-contrib/uglifyjs-webpack-plugin

**Comment by fearrr** [comment]
Thanks for the help, I did not know about the existence of this plugin.
It works a little longer, but does not lead to errors. But for production builds, it does not really matter.
close it.
