### ISSUE TITLE
Override how import() is transpiled

### ISSUE THREAD

**Issue by mohsen1** [webpack/webpack#5344]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**

`import()` calls are transpiled to:

```js
new Promise(function(resolve) { resolve(); }).then(__webpack_require__.bind(null, moduleId));
```

**If the current behavior is a bug, please provide the steps to reproduce.**
No

**What is the expected behavior?**
Allowing a way of overriding this output.

**If this is a feature request, what is motivation or use case for changing the behavior?**
This will resolve the biggest pain point in SSR+Code Splitting scenarios. If I can make `import()` calls resolve sync in the server and report the moduleId so I can include corresponding client chunk, I would be able to make SSR+CodeSplitting just work.

Currently I'm doing hacks like [this](https://github.com/mohsen1/perfect-project/blob/cd31dce35965bddf79414d5aaab003c460ca424c/src/components/App.tsx#L12-L19) to make my function return sync results.

**Comment by mohsen1** [comment]
A quick update on this. I ended up using text replacement to replace all `import()` calls with the code I wanted to have for it. 

See https://github.com/mohsen1/universal-async-component/blob/master/webpack.ts

I'm appending a `resolvedValue` to the promise so my component can look for it and resolve the module sync. This is a temporary solution until [promise inspection](http://bluebirdjs.com/docs/api/synchronous-inspection.html) lands in JavaScript. 

Is there a way of doing this as a Webpack plugin so I don't have to use `string-replacement-loader`?

**Comment by sokra** [comment]
Any approach to make `import()` conflicts with the Promise and the import spec. There is probably a way to do this in webpack, but it will not be future-proof.

Instead this should better be solved with user-level code. I see a weak point of react here. Vue.js solves this in a better way (Components can be promises here).

We should push the idea for returning a Promise from render()...
