### ISSUE TITLE
Under watch pattern, At the end of the recompile, there is no file to regenerate

### ISSUE THREAD

**Issue by ulivz** [webpack/webpack#5357]
**Do you want to request a *feature* or report a *bug*?**

Yes

**What is the current behavior?**

I use the option watchin the node API to watch my app, but when I delete the *.map file, then I did some change for the code, the recompile process will be triggered and the log of bundles outputs, but there are no files regenerated.

**If the current behavior is a bug, please provide the steps to reproduce.**

My Webpack Config: 
https://gist.github.com/ulivz/3f3401700d51a414d68044c789ff6514

**What is the expected behavior?**

All files should be re-generated after each compiled ending even when some files had been deleted.

**If this is a feature request, what is motivation or use case for changing the behavior?**

If you have such behavior, development experience will be very bad. log output but no files generated:
![image](https://user-images.githubusercontent.com/23133919/28519771-74cdc3b0-709f-11e7-9a16-28e1261636b1.png)

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

- Node.js 4.7.0
- Webpack 2.6.1
- OS: OSX 10.12.5

**Comment by sokra** [comment]
Unchanged files are cached and not reemitted. Don't delete files while watching.
