### ISSUE TITLE
HELP - Webpack --watch throws error

### ISSUE THREAD

**Issue by awesomenaz** [webpack/webpack#5358]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Webpack is throwing error every time running webpack with the --watch flag.
Running webpack without the flag is normal. 

<img width="948" alt="screen shot 2017-07-24 at 19 35 51" src="https://user-images.githubusercontent.com/14338956/28521690-614c899a-70a7-11e7-9480-0940e145955e.png">

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
To watch and rebuild.
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Node: v6.11.1
webpack: 3.3.0
OS: 10.12.6

**Comment by szmtcjm** [comment]
me too

**Comment by glebtv** [comment]
Also having this problem, can confirm that rolling back enhanced-resolve to 3.3.0 fixes this.

**Comment by awesomenaz** [comment]
This is currently fixed in https://github.com/webpack/enhanced-resolve/pull/100
