### ISSUE TITLE
UMD build does not export

### ISSUE THREAD

**Issue by prajapati-parth** [webpack/webpack#5365]
**Do you want to request a *feature* or report a *bug*?**
Might be a bug

**What is the current behavior?**
UMD build does not export a global variable under *window*

I'm trying to create a UMD build that can be used like so: 
```html
<script src="./dist/framework.js" type="text/javascript"></script>
<script>
    console.log(window.ComponentOne)
</script>
```
My entry file looks like this:
```jsx
import ComponentOne from './component-one'

if (typeof window !== 'undefined') {
	window.ComponentOne = ComponentOne
}

export {
    ComponentOne
}
```

webpack.config.js
```
var path = require('path');

module.exports = {
	entry: './framework/index.js',
	output: {
		path: path.resolve(__dirname, 'dist'),
		filename: 'framework.js',
		library: 'Framework',
		libraryTarget: 'umd'
	},
	module: {
		rules: [
			{
				test: /\.js$/,
				include: path.resolve(__dirname, 'framework'),
				exclude: /(node_modules|bower_components|build)/,
				use: {
					loader: 'babel-loader',
					options: {
						presets: ['env']
					}
				}
			}
		]
	},
	externals: {
		'react': 'umd react',
    	        'react-dom' : 'umd react-dom'
	}
};
```
**What is the expected behavior?**
window.Component should contain ComponentOne

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Operating System: Ubuntu 16.04 LTS
Node version: `6.10.3`
Webpack version: `3.3.0`

**Comment by probablyup** [comment]
I think library is supposed to be a string, not an array. https://webpack.js.org/configuration/output/#output-library

**Comment by prajapati-parth** [comment]
@probablyup Yes, I tried working out with string as well. But had the same issue. 
Editing it to avoid further confusions.

**Comment by sokra** [comment]
You config and code looks correct.

It should be available as `window.ComponentOne` and `window.Framework.ComponentOne`.

This problem is somewhere else. Did you recompile?

**Comment by Shafley** [comment]
I have the same issue. when there is no default export ,  just export some function, get a empty object with import.
