### ISSUE TITLE
ws module

### ISSUE THREAD

**Issue by taoqf** [webpack/webpack#5367]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
when use webpack, `require('ws')` will generated
```js
var ws = null
if (typeof WebSocket != 'undefined'){
  ws = WebSocket
} else if (typeof MozWebSocket !== 'undefined'){
  ws = MozWebSocket
} else {
  ws = window.WebSocket || window.MozWebSocket
}
```
it seems that is not the code from [ws](https://github.com/websockets/ws)
**If the current behavior is a bug, please provide the steps to reproduce.**
`window` may be not defined

**What is the expected behavior?**
May be use the [ws](https://github.com/websockets/ws)?
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
See
https://github.com/mqttjs/MQTT.js/issues/462
https://github.com/maxogden/websocket-stream/issues/99

**Comment by taoqf** [comment]
I think I have solved this after https://github.com/maxogden/websocket-stream/pull/129 is merged.

**Comment by alex-lucid** [comment]
How did you solved that? I have latest ws, NativeScript app, latest web pack and ws is still not working :(

**Comment by taoqf** [comment]
Strange, this issue was resolved long time ago. 
Maybe it's something with `NativeScript`? I don't know `NativeScript` much. 
Could you describe your issue in detail?
