### ISSUE TITLE
[bug] URL is not a constructor

### ISSUE THREAD

**Issue by zalishchuk** [webpack/webpack#5372]
**Do you want to request a *feature* or report a *bug*?**

Bug with [WHATWG URL API](https://nodejs.org/dist/latest-v8.x/docs/api/url.html#url_the_whatwg_url_api) provided by native `url` module.

**What is the current behavior?**
```js modules
// ES6

import { URL } from 'url';

console.log(typeof URL); // undefined
```

```js modules
// CommonJS

const { URL } = require('url');

console.log(typeof URL); // undefined
```

**If the current behavior is a bug, please provide the steps to reproduce.**
I provided code above, is it a normal behavior and we should use [Web API URL](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL) or [WHATWG URL API](https://nodejs.org/dist/latest-v8.x/docs/api/url.html#url_the_whatwg_url_api) should be provided through `url` module?

**What is the expected behavior?**
```js
// ES6 modules

import { URL } from 'url';

console.log(typeof URL); // function
```

```js
// CommonJS modules

const { URL } = require('url');

console.log(typeof URL); // function
```

**Please mention your webpack and Operating System version.**

node 8.2.1
webpack 3.3.0
macOS Sierra 10.12.6

**Comment by sokra** [comment]
@webpack-bot move to defunctzombie/node-url

node-url exports it as `exports.Url` instead of `exports.URL`

**Comment by zalishchuk** [comment]
@sokra `node-url` does not support it at all, last update was 3 years ago, can we replace this deprecated module with a new one?

**Comment by sokra** [comment]
Sure if you have one. See webpack/node-libs-browser.
