### ISSUE TITLE
lazy loading: return resolve to a lazy load file only when all the other lazy loading in it are resolved

### ISSUE THREAD

**Issue by cruzlauroiii** [webpack/webpack#5373]
**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?** The lazy loaded file return resolved in promise even the other lazy loaded files in it are still pending

**If the current behavior is a bug, please provide the steps to reproduce.**
self explanatory: the lazy loaded file returns resolved promise even the the lazy loaded file in it are still pending

currently this is the current code:

``` js
installedChunkData = installedChunks[chunkId] = [resolve, reject];
```

and when the file is lazy loaded, it calls 

``` js
webpackJsonp([0],{
```

which stack goes to

``` js
while(resolves.length) {
     resolves.shift()();
}
```

and eventually calls the resolve function of the promise.

the new code should check all the lazy loaded files in the target file to resolve first before calling the resolve function of its promise

**What is the expected behavior?**
promise in the lazy loaded file should be still pending untill all the lazy loaded in the file in the target file are all resolve, then the target file should only then be marked as resolved.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
minimum requirements of webpack 3

**Comment by sokra** [comment]
I'm not sure if I understand the issue correctly.

This is the correct evaluation order:

``` js
// a.js
import("./b").then(() => console.log(4));
console.log(1);

// b.js
import "./c";
import("./d").then(() => console.log(6);
console.log(3)

// c.js
console.log(2);

// d.js
console.log(5);
```

Is your issue about this isn't the correct order or about webpack behaving not like this?

**Comment by cruzlauroiii** [comment]
`// a.js
import("./b").then(() => console.log(4));
console.log(1);

// b.js
import "./c";
import("./d").then(() => console.log(6);
console.log(3)

// c.js
console.log(2);

// d.js
console.log(5);
`

the bug free way should be:
1
3
2
5
6
4

but its not, and its really bugged. as the bugged output is:
1
4
3
6
2
5

it executed the resolve() immediately even the file that is imported havent finished downloaded yet.

so clearly its a bug.

**Comment by cruzlauroiii** [comment]
imagine slow downloads from the internet:
the output of that is 1 2 3 4 5 6 but i think its bugged as module.exports will be undefined.
but that code output is also bugged,  1 4 3 6 2 5

the correct way it should be is 1 3 2 5 6 4 so when the then((exp) => console.log(exp)) exp will have a value that is due from the other files needed to load.

**Comment by sokra** [comment]
The whole idea about lazy loaded dependencies is that the module evaluation does not wait for completion. lazy. If you want your dependencies to be available before module evaluation and before the promise is resolve you should use normal import (see `import "./c"`, which is evaulated before the promise at 4 is resolved).

**Comment by cruzlauroiii** [comment]
but if you use normal imports, that imported file cannot be separated to another file.

**Comment by sokra** [comment]
All this is possible with the current behavior.

Anyway: as webpack seem to behave as spec'ed in the `import()` spec, this doesn't seem to be an issue.

If you think the behavior should be change you should file an issue on the spec. (But in my opinion the behavior is correct and does make sense)
