### ISSUE TITLE
An ability to interrupt running compile process

### ISSUE THREAD

**Issue by ilyadoroshin** [webpack/webpack#5378]
Is there a way to interrupt current compilation when new changes are coming? So it wouldn't wait for it to end before starts a new compilation process? 

**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
It starts building new changes only after the current build is finished

**If the current behavior is a bug, please provide the steps to reproduce.**
Not a bug, I believe.

**What is the expected behavior?**
It interrupts the current build if present, and starts a new one

**If this is a feature request, what is motivation or use case for changing the behavior?**
If your bundle is really big, it usually takes a lot of time to compile. Adding an ability to interrupt the current compilation process if there's new changes to build will significantly increase the speed.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
webpack@2, macos@10.11.6, node@^6

**Comment by sokra** [comment]
It's difficult to interrupt the process without corrupting the cache or leaving async task hanging around...

**Comment by ilyadoroshin** [comment]
@sokra thanks! while googling around and asking everyone about that, i got the gist that i'm doing something really wrong :) 
so i just created a vendor chunk to separate it from my code, x5 speed increase. 

Thanks!
