### ISSUE TITLE
Chunk.entry was removed

### ISSUE THREAD

**Issue by lqzerogg** [webpack/webpack#5379]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
cannot build, throw an error without error track. 
ERROR in chunk js/vendor [entry]
[name].[chunkhash].js
Chunk.entry was removed. Use hasRuntime()

**If the current behavior is a bug, please provide the steps to reproduce.**
I use sass-loader, extract-text-webapck-plugin. and when I build, it just throw error.
I've search a lot, and I've update extract-text-webapck-plugin. It just doesn't work.

**What is the expected behavior?**
build success.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
node: v7.0.0
webpack: 3.4.0
os: Mac OS 10.12.5

**Comment by SpainTrain** [comment]
Do you use `chunk-manifest-webpack-plugin`? Try updating it to `v1.1.2` 
 See: https://github.com/soundcloud/chunk-manifest-webpack-plugin/issues/43

**Comment by lqzerogg** [comment]
Oh, thank you very much, it works!
