### ISSUE TITLE
[Shimming] shim global object

### ISSUE THREAD

**Issue by ljqx** [webpack/webpack#5381]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
global object could not be shimmed neither by `imports-loader` nor `ProvidePlugin`.

**If the current behavior is a bug, please provide the steps to reproduce.**
not a bug

**What is the expected behavior?**
There should be a way to shim the global object, maybe by a new plugin named as `GlobalObjectPlugin`.

```javascript
module.exports = {
  plugins: [
    new webpack.GlobalObjectPlugin('window') // or 'global'
  ]
};
```

**If this is a feature request, what is motivation or use case for changing the behavior?**
There is code like (from [knockout](https://github.com/knockout/knockout))
```javascript
(function(){
  var window = this, // or (0, eval)('this')
      module.exports = window["jQuery"];
}());
```
currently it's not possible to shim `window.jQuery`.

The scenarios should be taken into consideration for this feature includes 
1. `this` for non strict mode function called with `this` not set
2. `this` for global context (currently could be shimmed by `imports-loader`)
3. `this` for global context in `eval` 

These scenarios may need to be taken into consideration too
1. Variables defined at top level (defined on `window` in browser but not on `global` in Node.js)
2. Variables defined without `var`/`let`/`const` under non strict mode

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
none

**Comment by ljqx** [comment]
I could try to sent out a PR for this, do you have suggestions/concerns about the mentioned solution? @sokra , @TheLarkInn

**Comment by sokra** [comment]
I guess you ain't talking about the `global` object, but instead about `this` in module context. You can shim it with the imports-loaders: `imports-loaders?this=>window`

**Comment by ljqx** [comment]
@sokra , not `this` for the module. For code
```javascript
(function(){
    var window = this || (0, eval)('this'),
        jQueryInstance = window["jQuery"];
}());
```
the inner `this` is the global object, which is `window` in browser and `global` in Node.js.

Using `imports-loaders?this=>window` would only handle `this` for the module, not the inner `this` inside the IIFE.

**Comment by ljqx** [comment]
For correctly handle this, there are several needed changes:
1. Webpack should know if the scope is in strict mode, which affect the `this` value to be the global object or `null`. Webpack don't care about this now.
2. For knowing 1, Webpack should know if the file is loaded as `module` or `script`, in `module` mode strict mode is on by default. Webpack now loads file first as `module`, if failed, then `script`.
3. In strict mode, set `this` for no explicit `this` call as `null`; or set `this` to the global object.
