### ISSUE TITLE
Complex dynamic require doesn't map modules in resolve.modules

### ISSUE THREAD

**Issue by mjanjic01** [webpack/webpack#5382]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Code containing a dynamic require
```javascript
var module = 'User';
const User = require(module);
```
When bundled results with an error:
```javascript
var module = 'User';
const User = !(function webpackMissingModule() { var e = new Error("Cannot find module \".\""); e.code = 'MODULE_NOT_FOUND'; throw e; }());
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Minimal reproducible repo available [here](https://github.com/mjanjic01/webpack-test).

**What is the expected behavior?**
Webpack should map modules in paths specified in `resolve.modules`.
Similar issue [here (#2672)](https://github.com/webpack/webpack/issues/2672).

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
node: v7.10.0
npm: v4.2.0
webpack 3.3.0

**Comment by sokra** [comment]
This case is too dynamic. If you want this to work supply the possible module with the ContextReplacementPlugin.
