### ISSUE TITLE
AggressiveSplittingPlugin and watch mode with multiple entry points.

### ISSUE THREAD

**Issue by KpjComp** [webpack/webpack#5383]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When using AggressiveSplittingPlugin, 2 problems.  Firstly it doesn't work unless you also include "CommonsChunkPlugin", as this then has the bootstrap code, (webpackJsonp etc).  Also if not using "CommonsChunkPlugin" duplicates are created.  eg. If say I used PouchDB twice in 2 entry points I get 2 350k files,..

But the biggest problem, if you have more than 1 entry point using Watch mode, first compile is fine, successive compiles give errors like ->
```
ERROR in chunk 1 [entry]
8a7cd0cd2cc5f21ec12a.js
Conflict: Multiple assets emit to the same filename 8a7cd0cd2cc5f21ec12a.js

ERROR in chunk 3 [initial]
93a8d32df50e5f918ebe.js
Conflict: Multiple assets emit to the same filename 93a8d32df50e5f918ebe.js
etc.

```

Also worth noting, on these successive compiles, it again then duplicates files, eg.  It shows 2 350k files again, like when not using "CommonsChunkPlugin".

A temporary solution while developing in watch mode only have 1 entry point, and only work on this.  Once you are happy re-include all entry points and do a full compile again.

**If the current behavior is a bug, please provide the steps to reproduce.**

Create a project with 2 entry points, start compile in watch mode.  
Now modify a file to cause a recompile.

**What is the expected behavior?**

It works like the first compile, and doesn't error.

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by KpjComp** [comment]
Hi, I'll see if I can knock up a simple demo..

But here is some more info that might help track down were it's going wrong.->

When doing the first compile we get ->
```
Version: webpack 3.0.0-rc.2
Time: 12922ms
                  Asset       Size  Chunks             Chunk Names
658736f5451cc4de0a04.js  739 bytes       0  [emitted]  b
9349f1ffb935bd0f5878.js  630 bytes       1  [emitted]  a
6f509b169ee4e01e7a48.js    21.2 kB       2  [emitted]
5bb64574ca9f59f5474b.js    19.5 kB       3  [emitted]
6394ce8303d15aef3116.js    9.58 kB       4  [emitted]
54eb01b5a0f265aa6f79.js     125 kB       5  [emitted]
splitting-manifest.json  338 bytes          [emitted]
```

Notice the chunk names   a & b..
If we now modify a file ->

```
Version: webpack 3.0.0-rc.2
Time: 26945ms
                  Asset       Size  Chunks             Chunk Names
68a66e6bd5ceab8a89e2.js    12.1 kB      12  [emitted]
4683129bd5331664fb57.js    9.31 kB    0, 1  [emitted]
f383b8edf23864c07c09.js    20.2 kB   2, 10  [emitted]
9f055e4f581a08a93f34.js    20.2 kB   10, 2  [emitted]
e97cc4fb41e4fc2481b6.js    12.2 kB      11  [emitted]
01d7079ad4faee25067a.js    9.31 kB    1, 0  [emitted]
cd1ea98978e7782ddbe6.js    8.42 kB  13, 14  [emitted]
bfe3cb93ae96018c0d65.js    8.42 kB  14, 13  [emitted]
5bbe1d1aa9d049a83d7d.js     124 kB  15, 16  [emitted]
0ad3f7c0eb54676271a4.js     124 kB  16, 15  [emitted]
splitting-manifest.json  338 bytes          [emitted]

```

Notice that chunk names  a & b have disappeared.  Also compile time is double.
And it appears files are compiled twice, as we have   2 of 20.2k & 8.42k, & 124k.

ps. tried doing simple test with small files, can't get the problem to happen. 
But all I have done in the above is include  pouchdb-browser, I assume that's the 124 kb chunk.

**Comment by ematipico** [comment]
Have you tried to use version `3.0.0`? Just wondering since RC might have some bug that the final release could have fixed.

**Comment by TheLarkInn** [comment]
Yes it would be great to see this tested on latest just to be sure (3.4.1).
