### ISSUE TITLE
Common chunks cannot find scripts in resolve.alias

### ISSUE THREAD

**Issue by dobromir-hristov** [webpack/webpack#5384]
**Do you want to request a feature or report a bug?**
Bug

**What is the current behavior?**
When used with commonsChunk with `async:true` and `children:true` I get a message that I have missing dependencies in all the folders specified in the `resolve.alias` config.

**If the current behavior is a bug, please provide the steps to reproduce.**
Using laravel-mix for setting up webpack.
My two entries are:
'resources/assets/js/app.js'
'resources/assets/js/admin.js'
config: https://gist.github.com/dobromir-hristov/546c4cc0d321e6c6ca3486d89fa766b9

**What is the expected behavior?**
Should be able to find the aliased files.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Node - 6.9.1
Webpack 3.2.0, 3.3.0
Windows 10

![127 0 0 1-8888-](https://user-images.githubusercontent.com/9863944/28641253-409a392a-7257-11e7-8970-a5bdcee07f78.png)

**Comment by frankleng** [comment]
@dobromir-hristov hopefully this doesn't get closed cuz you didn't use the issue template...

what version of webpack are you using? try downgrading to 3.2

**Comment by dobromir-hristov** [comment]
Tried with 3.2 and 3.3 didnt work ☹️

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by dobromir-hristov** [comment]
OK a bit of info in the issue.
I did a fresh webpack setup and everything was fine, that made me believe that there was a local issue.

I managed to fix my issue by updating laravel-mix to the latest version (1.4.2 currently). 
I still cant extract common, duplicated code from async components, but I at least don't get compilation errors like before where aliased code was not found in the async chunks. 

```js
...
plugins: [
      /* Extract all common code that is not from node_modules into a common.js */
      new webpack.optimize.CommonsChunkPlugin({
        name: 'common',
        filename: 'js/common.js'
      }),
      /* Extract all node modules common code to vendor.js */
      new webpack.optimize.CommonsChunkPlugin({
        name: 'vendor',
        filename: 'js/vendor.js',
        minChunks: function (module, count) {
          // any required modules inside node_modules are extracted to vendor
          return (
            module.resource &&
            /\.js$/.test(module.resource) &&
            module.resource.indexOf(
              path.join(__dirname, './node_modules')
            ) === 0
          )
        }
      }),
      /* Extract common async code */
      new webpack.optimize.CommonsChunkPlugin({
        name: 'commonlazy',
        children: true,
        async: true,
        minChunks: 2
      })
]
...
```
@TheLarkInn Do you see any issues with this setup? Commonlazy is not created at all.

**Comment by dobromir-hristov** [comment]
Ok so I actually managed to generate async chunks, but the chunk-name is a bit weird.
```js
 output: {
      filename: '[name].js',
      chunkFilename: 'js/[name]-chunk.js',
      publicPath: '/'
    },
 plugins: [
         /* Extract all common code that is not from node_modules into a common.js */
      new webpack.optimize.CommonsChunkPlugin({
        name: 'common',
        filename: 'js/common.js'
      }),
      /* Extract all node modules to vendor.js */
      new webpack.optimize.CommonsChunkPlugin({
        name: 'vendor',
        filename: 'js/vendor.js',
        minChunks: function (module, count) {
          // any required modules inside node_modules are extracted to vendor
          return (
            module.resource &&
            /\.js$/.test(module.resource) &&
            module.resource.indexOf(
              path.join(__dirname, './node_modules')
            ) === 0
          )
        }
      }),
      /* Extract common async code */
      new webpack.optimize.CommonsChunkPlugin({
        async: 'async-vendor',
        children: true,
        // async: true,
        minChunks: function (module, count) {
          // any required modules inside node_modules are extracted to vendor
          return module.context && module.context.indexOf('node_modules') !== -1
        }
      }),
      /* Extract common async code outside of node_modules */
      new webpack.optimize.CommonsChunkPlugin({
        async: 'async-common',
        children: true,
        // async: true,
        minChunks: 2,
        minSize: 100000
      })
 ]
```
I get a chunk named `js/async-vendor-vue-components/checkout-chunk.js`. I have a checkout.js that is async loaded, but why use its name?
Also, there is allot of common code inside my vue components that is not from node_modules, but instead imported from various helpers and stuff, that stays in the app.js. I guess that is to keep the chunks light and skip duplication?

**Comment by imposibrus** [comment]
Just stay opening

**Comment by vedmant** [comment]
So what's the right solution for this?
