### ISSUE TITLE
Code splitting: all chuncks are loaded at once

### ISSUE THREAD

**Issue by yantakus** [webpack/webpack#5389]
**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**

Routing with react-router, redux and redux-saga entails a lot of repeated code, just have a look [here](https://github.com/react-boilerplate/react-boilerplate/blob/master/app/routes.js#L20-L41). 21 lines for a single route. In my app I have dozens of routes, so it is very important to DRY it out somehow. Otherwise this file `routes.js` will be a mess with 1000+ lines.

[This](https://github.com/yantakus/webpack-example/blob/master/app/routes.js) is what I came up to.

It works quite well despite one big problem. Webpack's code splitting works incorrectly: all the chunks get loaded when any page of the app is opened.

**If the current behavior is a bug, please provide the steps to reproduce.**

Here is the [link](https://github.com/yantakus/webpack-example/) to the demo repo.

**What is the expected behavior?**

It should load only the needed chunks for the exact route and load other chunks on demand when a user goes to another page.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Tried on different OSs and node versions with no luck.

----------

I consider this a bug, because my bundle is split into chunks and the app knows which route I open (I tried to insert console.log into `getComponent` method and it prints correct route name for different routes).

When the bundle is divided into chunks and routing works correctly, webpack can work correctly and load the needed chunks on demand, right? But this doesn't happen. Please, correct me if I'm wrong.

**Comment by sokra** [comment]
This code:

``` js
  const childRoutes = [
    createRoute(
      '/',
      'home',
      import('pages/Home'),
    ),
```

calls import().

You better pass a closure:

``` js
  const childRoutes = [
    createRoute(
      '/',
      'home',
      () => import('pages/Home'),
    ),
```
