### ISSUE TITLE
Loaders with same test parameter operate with one source. 

### ISSUE THREAD

**Issue by sshmyg** [webpack/webpack#5391]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
Loaders with same `test` param gets `source` modified by prev loader.

**If the current behavior is a bug, please provide the steps to reproduce.**
Stackoverflow issue  link https://stackoverflow.com/questions/45349178/webpack-loaders-source
Sandbox to reproduce bug https://github.com/sshmyg/webpack-test

**What is the expected behavior?**
Different rules with same `test` should get pure content, not modified prev rule.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
- MacOS latest
- node 7.4.0
- npm 4.6.1
- webpack latest 3.4.1

**Comment by sokra** [comment]
This is working as expected. You can apply multiple loaders to a file.

If you don't want this you could use the `oneOf` rule to enforce only a single match.

**Comment by sshmyg** [comment]
@sokra I want to get pure (not medified) content for each loader with same `test` param. Can you give an advice how to achieve this goal?
