### ISSUE TITLE
[name] and [filebase] templates don't work in output.filename

### ISSUE THREAD

**Issue by 50m30n3** [webpack/webpack#5394]
**Do you want to request a *feature* or report a *bug*?**
I want to report a bug in version 3.4.1 of webpack.

**What is the current behavior?**

Using the [name] or [filebase] templates in the output.filename setting in webpack.config.js leads to the following error message:

```
ERROR in chunk main [entry]
build/[filebase].js
Path variable [filebase] not implemented in this context: build/[filebase].js
```

According to the documentation here this should work: https://webpack.js.org/configuration/output/#output-filename

**If the current behavior is a bug, please provide the steps to reproduce.**

I've created a minimal reproducible example in this gist: https://gist.github.com/50m30n3/c56398e8b95dd4a5fe5aedfa9469c10b

Running `webpack` or `node run build` will result in the error.

**What is the expected behavior?**
According to the documentation the original file name or file basename should be substituted into the output file name.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

I'm running node v8.2.1 and webpack 3.4.1 on Arch Linux.

**Comment by sokra** [comment]
@webpack-bot move to webpack/webpack.js.org

The documentation is wrong here. `[file]` and `[filebase]` is only available in source map filename and not in `filename` or `chunkFilename`.

**Comment by 50m30n3** [comment]
Is there any way to use the input filename as part of the output filename? Using the module name often results in unsuitable filenames for us when building with multiple entry points.

**Comment by pierreneter** [comment]
@50m30n3 you can use `[name]`

Like this:
```
module.exports = {
	entry: {
		outputNameYouWant: ["./test.js"] // list of modules into outputNameYouWant.js
	},
	output: {
		filename: 'build/[name].js'
	}
}
```

**Comment by 50m30n3** [comment]
Sorry I wasn't more specific with my question. We're also using the `[name]` in the `output.library` name with `output.libraryTarget` set to `"var"`, like this:

```
module.exports = {
	entry: {
		Classname: ["./classname.js"],
		Anotherclass: ["./anotherclass.js"]
	},
	output: {
		filename: 'build/product-[name].js'
		libraryTarget: 'var',
		library: ['product', '[name]']
	}
}
```

The problem with this is that we either end up with an output file named `product-Classname.js`, which is rather ugly and requires renaming to lowercase in a second step, or we change the entry name to be lowercase in which case the exported class would have to be accessed as `product.classname`, with a lowercase class name, which is not suitable.

Being able to use the input filename would solve that problem very nicely.
