### ISSUE TITLE
Hot Module Replacement doesn't notice when a symlink is changed

### ISSUE THREAD

**Issue by pweaver** [webpack/webpack#5395]
**What is the current behavior?**
We symlink our node_modules directory and change the symlink when we update node_modules. When the directory is changes HMR doesn't detect that something has changed.

**If the current behavior is a bug, please provide the steps to reproduce.**
Setup HMR referencing a file with the parent directory symlinked. Change the symlink to a different directory with a modified version of the file.

**What is the expected behavior?**
HMR should detect that files have changed. Currently does not.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Linux Ubuntu.

**Comment by sokra** [comment]
@webpack-bot move to webpack/watchpack
