### ISSUE TITLE
Specify output directory with dynamic import

### ISSUE THREAD

**Issue by stephan-v** [webpack/webpack#5401]
**Do you want to request a *feature* or report a *bug*?**

Neither

**What is the current behavior?**

I am wondering if it is possible to specify an output directory per dynamic import context:

```JS
import(/* webpackChunkName: "svg-" */ `resources/assets/images/svg/${this.name}.svg`)
    .then((module) => {
        this.svg = module;
    }
).catch(error => 'An error occured while loading the svg');
```

When using something like the above I would like to specify the output directory of these files so they end up in: `public/js/svg/`.

I am currently doing it by using this:

```JS
output: {
    publicPath: '/',
    chunkFilename: 'js/svg/[name].js'
},
```
This is obviously not flexible since it will do this for all dynamic imports so I can't re-use it for anything but SVG's.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by dobromir-hristov** [comment]
Well technically you could do `/* webpackChunkName: "/js/svg/svg-[name]" *` but that could lead to other problems i think.

**Comment by sokra** [comment]
This is not possible for technical reasons. You can use the approach @dobromir-hristov proposed that should work (without the leading `/`).

**Comment by stephan-v** [comment]
Is `[name]` suppose to translate to the filename just like it would with `chunkFilename` inside my webpack configuration file?

Currently I am literally getting files named:

`[name]0.js`

When I use this:

`/* webpackChunkName: "js/svg/[name]" */`

Something is going wrong here.

**Comment by dobromir-hristov** [comment]
https://webpack.js.org/api/module-methods/#import-

> webpackChunkName: A name for the new chunk. Since webpack 2.6.0, the placeholders [index] and [request] are supported within the given string to an incremented number or the actual resolved filename respectively.

**Comment by stephan-v** [comment]
@dobromir-hristov Thank you, it needed to be `[request]`. This works exactly as I would want it and gives me a lot more flexiblity in where my modules are going per dynamic import that I am using.

**Comment by victorwpbastos** [comment]
In my case, `[request]` is always interpreted literally as `somefilename.[request].js`. Anyone with the same problem?

**Comment by decadef20** [comment]
I have tried it out. The file path can not be string if you use [request]

**Comment by dobromir-hristov** [comment]
It should be "[request]" with quotes

**Comment by ameliapower** [comment]
I am having trouble creating chunk files with json extension, works fine for .js but I need .json format for these files. Although I seem to have a folder called 'locales' that is copied to the build folder along with 'locales lazy /^/.*' that contains a '.json$' map file but there is an error trying to load them: WebpackAsyncContext error. I created a [SO](https://stackoverflow.com/questions/53134801/error-loading-chunk-files-in-webpack-project-using-dynamic-import). Can anyone help? Thanks
