### ISSUE TITLE
dynamic require inside if block fails to compile

### ISSUE THREAD

**Issue by vkbansal** [webpack/webpack#5402]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The following code does not compile with webpack as acorn parser is not able to parse this.
Babel is able to parse this correctly. You can test this on [astexplorer.net](https://astexplorer.net/)
```js
let routes = [];

if (process.env.NODE_ENV === 'development' || process.env.FK_ENV === 'staging') {
    routes.push({
       getComponent: import(/* webpackChunkName: "SomePage" */ './SomePage.js')
    });
}
```

Neither does this.

```js
let routes = [];

if (false || true) {
    routes.push({
       getComponent: import(/* webpackChunkName: "SomePage" */ './SomePage.js')
    });
}
```

**What is the expected behaviour?**
It should compile.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Webpack: 2.5.1
Node: 8.2
OS: MacOS Sierra

**Comment by mikesherov** [comment]
What output do you get? Webpack uses an Acorn plugin specifically able to parse dynamic import statements.

**Comment by vkbansal** [comment]
I get *unexpected token* error

**Comment by dobromir-hristov** [comment]
First try the import to be a function `getComponent: () => import(/* webpackChunkName: "SomePage" */ './SomePage.js')` then check your babel config. Add `babel-plugin-syntax-dynamic-import` to your babel plugins config.

**Comment by vkbansal** [comment]
@mikesherov I already have that in place. `import` functions work out of the `if` block, but not within.

**Comment by sokra** [comment]
Note: unexpected token occurs in the browser. This has already been reported.

**Comment by vkbansal** [comment]
@sokra this happens in webpack build time and not in browser

**Comment by sokra** [comment]
Stack trace? `--display-error-details`

**Comment by vkbansal** [comment]
I'm unable to reproduce it today. I'll reopen the issue if and when I can provide the error logs
