### ISSUE TITLE
Can watch mode support watching new file automatically?

### ISSUE THREAD

**Issue by zwwtj2014** [webpack/webpack#5407]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
watch mode can not support watching new file automatically

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

Watch mode can support add new file ?
Or I can tell webpack know when to run the function again to get new file in watch mode , so I can do something with webpack plugin or loader?

And I have a comment in issue#370 https://github.com/webpack/webpack/issues/370#issuecomment-318870177

**If this is a feature request, what is motivation or use case for changing the behavior?**

I want to use watch mode, because it support incremental compilation and rebuild so fast when I modify a file. 
But now I must restart webpack when add new file. If there are many enties, it will spend a lot of time !!!

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by sokra** [comment]
Could you try it with the lastest versions of webpack and watchpack? I guess this was fixed.

**Comment by zwwtj2014** [comment]
Thanks for your reply!

But how to configuration the entry?
Type of entry is `string | [string] | object { <key>: string | [string] } | (function: () => string | [string] | object { <key>: string | [string] })`. Does it support configuration to directory?

**Comment by sokra** [comment]
> Does it support configuration to directory?

no.

**Comment by sokra** [comment]
Either use the `glob-loader` or 

``` js
var x = require.context("./directory", false, /\.js$/);
x.keys().forEach(x);
```

**Comment by zwwtj2014** [comment]
@sokra I have tried `require.context`, and have a entry.js 
```js
let ctx = require.context('./dyn', false, /\.ts$/);
ctx.keys().forEach(ctx);
```

and  simple webpack.config.js:
```js
...
    entry: './entry.js'
...
```

**This is ok for single entry.** And I understand this is because webpack watch single entry and build index tree from entry.js.

---

But I am currently a **multi-entry scene**， I tried return a map/object in entry.js like this:
```js
const allFiles = (ctx => {
    let keys = ctx.keys();
    let values = keys.map(ctx);
    return keys.reduce((o, k, i) => { o[k] = values[i]; return o; }, {});
})(require.context('./dyn', false, /\.ts$/));

module.export = allFiles;
```
and webpack.config.js:
```js
...
entry: require('./entry.js').allFiles
...
```
and have a error: require.context is not a function...
I think this is because the require.context is defined in the runtime of the webpack.

So sorry I did not describe it clearly.
**I hope the new added file becomes an entry and watched automatically (new file => new entry)**, so is this fixed in lastest version?

**Comment by sokra** [comment]
Ah ok you want to create an entry for each file in a directory. Try this:

``` js
entry: () => {
  fs.readdir() ...
  return a promise resolving to {
    a: "./a",
    b: "./b",
  }
}
```

**Comment by zwwtj2014** [comment]
Thanks! I'll try it for a while !

But I think this should only solve the problem of multiple entrances, watching new file not ok! Or I miss something? 

---

>I hope the new added file becomes an entry and watched automatically (new file => new entry => new dependency graph)

I think it takes two steps: 
1. watch add new file  (add event)
2. when add a new file , create an entry(and watcher) for new file and add watcher into fileWatchers without restart webpack

**Comment by sokra** [comment]
``` js
compiler.plugin("compilation", compilation => {
  compilation.contextDependencies.push(path.resolve(__dirname, "path/to/directory"));
});
```

This watches a directory.

**Comment by wmertens** [comment]
Ok, so my use case is finding all test files in the source tree, creating a separate entry for each, and then creating/removing entries as test files are added and removed.

@sokra how can I add/remove entries to the compiler? How to tell it the entries changed?

**Comment by zwwtj2014** [comment]
@wmertens maybe method addEntry is ok...
```js
compiler.plugin("make", (compilation, callback) => {
        ...
        compilation.addEntry(this.context, SingleEntryPlugin.createDependency(path.resolve(__dirname,, this.dir, 'A2.ts'), 'a2'), 'a2', err => {
            if (err) {
                console.log(err);
            }
            ...
        });
        ...
        callback();
});
```

but I have no idea about how to get the file name and file path of the new file if I watch directory with `compilation.contextDependencies.push(path.resolve(__dirname, "path/to/directory"));`

I'm trying to find a way like chokidar...
```js
let watcher = require('chokidar').watch(dir,{});
watcher.on('add', path=>{
    ...
})
```

**Comment by zwwtj2014** [comment]
@sokra I tried to get new file path by this way (with invalid hook):
```js
compiler.plugin('invalid', filePath => {
        this.filePath = filePath;
});
```

Use the above mentioned way to add entry:
```js
compiler.plugin("make", (compilation, callback) => {
        ...
        compilation.addEntry(this.context, SingleEntryPlugin.createDependency(this.filePath, 'a2'), 'a2', callback);
        ...
        callback();
});
```

But have a error when create module， 
```txt
TypeError: Cannot read property 'addChunk' of null
    at self.preparedChunks.forEach.preparedChunk (D:\quick-start\node_modules\webpack\lib\Compilation.js:565:10)
    at Array.forEach (native)
    at Compilation.seal (D:\quick-start\node_modules\webpack\lib\Compilation.js:558:23)
    at applyPluginsParallel.err (D:\quick-start\node_modules\webpack\lib\Compiler.js:521:17)
    at D:\quick-start\node_modules\tapable\lib\Tapable.js:225:11
    at _addModuleChain (D:\quick-start\node_modules\webpack\lib\Compilation.js:485:11)
    at processModuleDependencies.err (D:\quick-start\node_modules\webpack\lib\Compilation.js:455:13)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

And I found resolve method in [NormalModuleFactory.js](https://github.com/webpack/webpack/blob/master/lib/NormalModuleFactory.js#L118-L123) is fail and can not run into callback...

**Comment by Pontiley** [comment]
@zwwtj2014, Hello, you need correct your code, and it will work:

```
const SingleEntryPlugin = require("webpack/lib/SingleEntryPlugin");
const path = require('path');

let changeFileName;

function AddWatchWebpackPlugin() {
};

AddWatchWebpackPlugin.prototype.apply = function (compiler) {

    compiler.plugin('invalid', function (fileName, changeTime) {
        changeFileName = fileName
    });

    compiler.plugin("make", function (compilation, callback) {
        if (changeFileName) {
            // Set module name
            let name = path.basename(changeFileName).replace('.ts', '');
            // Set context
            let context = path.resolve(__dirname);

            // Create dependency, pass 2 parameters: 1) path to changed file, and 2) module name
            const dep = SingleEntryPlugin.createDependency(changeFileName, name);

            /**
             * And then add entry, pass 3 parameters: 1) context - it the same with webpack context setting, in webpack
             * configuration (simple path to project dir) 2) dependency, it was create above, 3) module name
             * and last 4) callback, which webpack will invoke, when finish create 
             */
            compilation.addEntry(context, dep, name, callback);

            // Finally you need delete changeFileName
            changeFileName = "";
        } else {
            callback();
        }
    })
};
```

**Comment by Pontiley** [comment]
But, I don't know, how make delete entry, when file was remove. When file was delete, webpack throws error:

```
ERROR in D:/Development/Projects/main/src/a2.ts
Module build failed: Error: ENOENT: no such file or directory, open 'D:\Development\Projects\main\src\a2.ts'
at Error (native)
@ D:/Development/Projects/main/src/123.ts 1:0-26
```

**Comment by Pontiley** [comment]
I found another way to get changed/removed file name:

```
const SingleEntryPlugin = require("webpack/lib/SingleEntryPlugin");
const path = require('path');
const del = require('del');

function AddWatchWebpackPlugin() {
};

let changeFileName;
AddWatchWebpackPlugin.prototype.apply = function (compiler) {
    compiler.plugin("after-compile", function (compilation, callback) {
        // Watch for root project dir
        compilation.contextDependencies.push(path.resolve(buildConf.folders.main.src.dir));
        callback();
    });

    compiler.plugin("make", (compilation, callback) => {
        if (changeFileName) {
            let name = path.basename(changeFileName).replace('.ts', '');
            const dep = SingleEntryPlugin.createDependency(changeFileName, name);
            compilation.addEntry(buildConf.folders.main.src.dir, dep, name, callback);
            changeFileName = "";
        } else {
            callback();
        }
    });

    compiler.plugin('watch-run', function (compilation, callback) {
        /**
         * If file was changed, then compiler.watchFileSystem.watcher will object:
         * mtimes: {
         *   'PathToFileWhichWasChange': 'time in mls'
         * }
         * For example:
         *   mtimes: {'D:\Development\Projects\main\src\a2.ts': 1503649122899
         * }
         *
         * If you will watch to dir, it will have 2 objects:
         *
         * For example:
         *   mtimes: {
         *   'D:\Development\Projects\main\src\a2.ts___jb_tmp___': null,
         *   'D:\Development\Projects\main\src\a2.ts': 1503649122899
         * }
         *
         */
        console.log(compilation.compiler.watchFileSystem.watcher.mtimes );
        if (compilation.compiler.watchFileSystem.watcher.mtimes !== {}) {
            for (let file of Object.keys(compilation.compiler.watchFileSystem.watcher.mtimes)) {
                // I will watch for js, ts files, and not dir.
                if (/\.ts|\.js/.test(file) && !/___jb_tmp___/.test(file)) {
                    // If mtimes exist, and time file changed is not null, then we save filePath
                    if (compilation.compiler.watchFileSystem.watcher.mtimes[file] !== null) {
                        changeFileName = file;
                    } else {
                        // If mtimes exist, and time file changed time is NULL, then we delete builded file
                        del.sync(file.replace(path.dirname(file), yourBuildedDir).replace('.ts', '.js'), {force: true});
                    }
                }
            }
        }
        callback();
    })
};
```

**Comment by Pontiley** [comment]
Method above will work for create/delete/change files in for which wather is watching

**Comment by zwwtj2014** [comment]
@Pontiley I have tried to scan my watch dir and rebuild watch tree for every entry and it is ok like this:
```js
        compiler.plugin("make", (compilation, callback) => {
            Q.all(this.watchedDirs.map(this.fetchEntries.bind(this)))
                .then(entries => {
                    compilation.addEntries = Object.assign.apply(null, entries);
                    return Object.keys(compilation.addEntries);
                }).invoke('map', name => {
                    let deferred = Q.defer();
                    let dep = new SingleEntryDependency(compilation.addEntries[name]);
                    compilation.addEntry(this.context, dep, name, deferred.makeNodeResolver());
                    return deferred.promise;
                }).all().nodeify(callback);
        });
```

But I think [your method](https://github.com/webpack/webpack/issues/5407#issuecomment-324856529) is easier, And `compilation.compiler.watchFileSystem.watcher.mtimes` is great !

**Comment by zwwtj2014** [comment]
@Pontiley I have tried your method. But I can not replay the scene watch to dir，Can you explain more in detail?
```js
         * If you will watch to dir, it will have 2 objects:
         *
         * For example:
         *   mtimes: {
         *   'D:\Development\Projects\main\src\a2.ts___jb_tmp___': null,
         *   'D:\Development\Projects\main\src\a2.ts': 1503649122899
         * }
```

**Comment by Pontiley** [comment]
@zwwtj2014 , If I right understand you, you want watch to dir, and rebuild when files are added?

If it is true, then you need add dir for watching in "after-compile":

```
    compiler.plugin("after-compile", function (compilation, callback) {
        // Watch for root project dir
        compilation.contextDependencies.push(path.resolve(YOUR_PATH_TO_WATCH_DIR));
        callback();
    });
```

What about my comment, I want to say, that if you will watch to dir, then compilation.compiler.watchFileSystem.watcher.mtimes object will have 2 properties.

"'D:\Development\Projects\main\src\a2.ts___jb_tmp___': null", this property is necessary for webpack, and you do not need to use it, so I exclude this property like:

`if (/\.ts|\.js/.test(file) && !/___jb_tmp___/.test(file))`

"'D:\Development\Projects\main\src\a2.ts': 1503649122899" this property which you need to use, for to get changed file name.

**Comment by zwwtj2014** [comment]
@Pontiley Yes, I want to watch to dir.

And I understand `"'D:\Development\Projects\main\src\a2.ts___jb_tmp___': null"` and `"D:\Development\Projects\main\src\a2.ts': 1503649122899"`.

Thank you very much!

**Comment by 8427003** [comment]
i write a plugin by your code @zwwtj2014 @Pontiley https://github.com/8427003/wildcards-entry-webpack-plugin

**Comment by webdiscus** [comment]
Hello @Pontiley,

Unfortunately your solution don't work in Webpack 5.
In Webpack 5 the `mtimes` property of the `compilation.compiler.watchFileSystem.watcher` object not exists. The `watcher` has other structure.

I need a solution for the [html-bundler-webpack-plugin](https://github.com/webdiscus/html-bundler-webpack-plugin) where [the entry can be as a path](https://github.com/webdiscus/html-bundler-webpack-plugin#entry-as-a-path-to-templates) to watch the entry directory for changing of entry files and rebuild entries when files are added/deleted/renamed.
