### ISSUE TITLE
Internal `contextify` methods are replacing backslashes with slashes in query strings on Windows

### ISSUE THREAD

**Issue by unconfident** [webpack/webpack#5411]
**Do you want to request a *feature* or report a *bug*?**
A bug. Possibly

Contextify function caught my eye. Since it doesn't isolate filepath from the query it then replaces backslashes with slashes in the entire string including the query if `path.sep === "\\"`. This looks to me like unwanted behavior

**What is the current behavior?**
```js
contextify('./dir', './loader?query=foo\\bar!./path/to/file');
// "../loader?query=foo/bar!../path/to/file"
```

**What is the expected behavior?**
```js
contextify('./dir', './loader?query=foo\\bar!./path/to/file');
// "../loader?query=foo\\bar!../path/to/file"
```

I would suggest rewriting it [like this](https://gist.github.com/unconfident/3936ff5feb67feda1a7e443f2d5168c6), but that code isn't the prettiest

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Node v6.10.3, Webpack v3.4.1, Windows 7

**Comment by sokra** [comment]
Makes sense. Please submit a PR.

**Comment by ksvitkovsky** [comment]
@unconfident are you interested in making a PR or I may take it?

**Comment by unconfident** [comment]
@ksvitkovsky, feel free to take it, it doesn't seem like I'll be getting any spare time until the end of the week
