### ISSUE TITLE
webpack Nodejs API doesn't support custom arguments configuration

### ISSUE THREAD

**Issue by kimown** [webpack/webpack#5418]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**
https://webpack.js.org/api/node/#webpack-
https://webpack.js.org/guides/migrating/#using-custom-arguments-in-cli-and-configuration

webpack support nodejs api and function configuration file, but when I want to combine both, it doesn't work. The error seems exist in webpack v2 and v3.

**If the current behavior is a bug, please provide the steps to reproduce.**

[repo.zip](https://github.com/webpack/webpack/files/1189344/repo.zip)

```
unzip repo.zip
npm  i
node start.js
```
Then the error occurs, like 
```
ebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration should be an object.

```

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by ThatTomPerson** [comment]
your config is a function and not an object
change `const config = require('./webpack.config')` to 
```
const configFn = require('./webpack.config')
const config = configFn()
```

**Comment by kimown** [comment]
@ThatTomPerson 

https://webpack.js.org/guides/migrating/#using-custom-arguments-in-cli-and-configuration

I see, but this doc says we can use a function configuration to pass arguments,  like this example code
>
```
module.exports = function(env) {
  var customStuff = env.customStuff;
  /* ... */
  return config;
};
```

**Comment by ThatTomPerson** [comment]
yeah I realised I was incorrect after I posted that,
if you run webpack from the cli it works just fine 🤔 

`node ./node_modules/.bin/webpack` it works just fine

the part of webpack that changes the config to an object must be part of the cli
which makes sense because it is parsing webpack's arguments (specifically --env) to the function

**Comment by kimown** [comment]
@ThatTomPerson 
Thanks for your reply, the reason I use nodejs api is I want to use [DllPlugin](https://github.com/webpack/webpack/tree/master/examples/dll), the final output file contains [hash], so I want to get the file name from callback. For some reason, many project will rely on the dll plugin, so I need pass some arguments to the configuration

```
webpack(config, (err, stats) => {
  if (err) {
    throw err
  }
  console.info(stats)
})
```

**Comment by sokra** [comment]
``` js
webpack(config(env), (err, stats) => {
  if (err) {
    throw err
  }
  console.info(stats)
})
```

**Comment by kimown** [comment]
@sokra 
😅 I think I shouldn't create this issue.
