### ISSUE TITLE
The way to shim modules relying on `window`, `window.jQuery` and `document`

### ISSUE THREAD

**Issue by utensil** [webpack/webpack#542]
I was migrating a site to webpack and encountered a problem similar to the one discussed here at https://gitter.im/webpack/webpack/archives/2014/07/23 by @mathieumg , which was a dependency on `window.jQuery`. 

My problem was that one of my dependencies (to be specific: https://github.com/eternicode/bootstrap-datepicker ) depended on `window`, `window.jQuery` and `document.defaultView`. 

After a lot of trial and error, eventually I figured out a way combining [externals](http://webpack.github.io/docs/library-and-externals.html) ,  [imports-loader and `ProvidePlugin`](http://webpack.github.io/docs/shimming-modules.html#importing):

In `webpack.config.js`:

```js
// Only the relevant part
{
    output: {
        libraryTarget: "var"
    },
    externals: [
        {
            "window": "window"
        }
    ],
    plugins: [
        new webpack.ProvidePlugin({
            $: "jquery",
            jQuery: "jquery"
        })
    ]  
}
```

In my entry js:

```js
    var window = require("window");
    window.jQuery = jQuery;

    require("imports?this=>window!bootstrap-datepicker");
    require("imports?this=>window!bootstrap-datepicker.zh-CN");
```

Here I share my discovery and wonder whether  there're other approaches and whether this is the best practice of shimming such kind of libraries.

**Comment by shama** [comment]
Closing as this issue appears to be resolved. Please reopen if it has not. Thanks!
