### ISSUE TITLE
Error: Didn't get a result from child compiler

### ISSUE THREAD

**Issue by lqzerogg** [webpack/webpack#5420]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When I am developing, webpack compile success at the first run. But if I modify any of my style, it throw error. This behavior really drives me crazy.
I use many plugin, like extract-text-plugin, sass-loader, url-loader and so on.

**If the current behavior is a bug, please provide the steps to reproduce.**
1 run webpack. 2 modify style file. 3 save. 4 throw error
just clone my rep, and try it out

my rep:  **https://github.com/lqzerogg/webpacktest**

**What is the expected behavior?**
It should compile successfully even if I modify style files.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
webpack: 3.0
OS: MacOS 10.12.5
node: 7.0.0

At last, thank you for your help

**Comment by sokra** [comment]
@webpack-bot move to webpack-contrib/extract-text-webpack-plugin
