### ISSUE TITLE
Module not found: Error: Can't resolve 'module' in '...'

### ISSUE THREAD

**Issue by Bamieh** [webpack/webpack#5423]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
```
const module = require('module')
// Module not found: Error: Can't resolve 'module' in '...'
```
This line of code throws on error even in "node" target

**If the current behavior is a bug, please provide the steps to reproduce.**
just requiring the `module` module will cause the issue.

**What is the expected behavior?**
`module` is a native module in node, just like `fs` or `http`, webpack should not throw when its required.

**If this is a feature request, what is motivation or use case for changing the behavior?**
I need to use the `module` module!

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

latest webpack version, nodeJS 8.1.3, mac OSX

**Comment by Bamieh** [comment]
As suggested by Michael McLaughlin @mmclau14 on webpack gitter. This could be worked around by replacing the require with

```
const NativeModule = module.constructor;
```

however i still believe this should be solved not worked around, as it causes unexpected issues.

**Comment by sokra** [comment]
webpack doesn't support the module module.

**Comment by Bamieh** [comment]
@sokra can you elaborate on the reason?

**Comment by ThatBrianDude** [comment]
Any updates here?
 
Getting this error: 

Module not found: Can't resolve 'module' in 'project_root\node_modules\load-grunt-tasks\node_modules\resolve-from'

**Comment by evilebottnawi** [comment]
@ThatBrianDude please recrea new issue using issue template. This problem is very old and don't related to your. Thanks!

**Comment by mjsarfatti** [comment]
@ThatBrianDude's problem is actually the exact same issue. Any development here?
