### ISSUE TITLE
__dirname paths do not resolve correctly when electron target is packaged

### ISSUE THREAD

**Issue by mmclau14** [webpack/webpack#5424]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
file paths that do not resolve correctly

**If the current behavior is a bug, please provide the steps to reproduce.**
have an es5 module that uses `__dirname` to reference folders located next to it.
use the node config option
```javascript
node: {
    __dirname: true
}
```
run in dev, works
run after packaging, fails

**What is the expected behavior?**
the filesystem should be the same structure, but it ends up not
verified by setting a breakpoint at the line that would join dirname with another path
found that global.__dirname and __dirname differed. fine, probably caused by the node: __dirname: true. still works in development
```javascript
require('fs').readdirSync(__dirname); // successful in development
```
after packaging, the previous line fails but I am able to get the following line to work at the same breakpoint
```javascript
require('fs').readdirSync(path.join(global.__dirname, '..', __dirname));
```
to get to the same place

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
I am on mac osx 10.12.6 (16G29)
tried building with target: electron and electron-renderer
webpack v3.4.1
node v7.10.0

**Comment by fengyinchao** [comment]
@licebeam @maikelmclauflin I recently came across the same issue in my electron application. And I solved it by modify webpack config like this:

module.exports = {
  target: 'electron-renderer',
  node: {
    __dirname: false, //set false to prevent webpack mock
    __filename: false,
  },
};

See https://www.yuque.com/fengyinchao/axyqmr/izibbp for more details
