### ISSUE TITLE
Error: Cannot find module '../package.json'

### ISSUE THREAD

**Issue by Vin-Yuan** [webpack/webpack#5427]
webpack

module.js:471
    throw err;
    ^

Error: Cannot find module '../package.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/vinyuan/code/uculture/webpack-demo3/node_modules/.bin/webpack:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! webpack-demo2@1.0.0 build: `webpack`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the webpack-demo2@1.0.0 build script 'webpack'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the webpack-demo2 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs webpack-demo2
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls webpack-demo2
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/vinyuan/code/uculture/webpack-demo3/npm-debug.log

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by Vin-Yuan** [comment]
It's stupid for me to missing comma in webpack.config.js ,TOT.
 as you see, between the line 8 and line 9, there is no comma, so error occurs
`module.exports = {
  4     entry: './src/index.js',
  5     output: {
  6         filename: 'bundle.js',
  7         path: path.resolve(__dirname, 'dist')
  8     }
  9     module: {
 10       rules: [`
Be careful for the comma between key:value in config file~
so I post this issue for many other people who is new for webpack

**Comment by mygovernance** [comment]
hello @Vin-Yuan  I am suffering from same issue can you please help.
I went through your solution but in my case there is no comma issue. Please help

**Comment by davidtinker** [comment]
@mygovernance I had the same error after moving a project to a different directory. I fixed it by nuking my node_modules and redoing 'npm install'.

**Comment by allan2coder** [comment]
```
rm -rf node_modules
npm install
```

**Comment by LvChengbin** [comment]
I encountered the same problem, I moved my project directory because I cannot use network in that os, are there any other ways to fix this issue?

**Comment by LvChengbin** [comment]
I just fix it by adding new symbolic link:

```sh
cd node_modules/.bin
rm -rf vue-cli-service
ln -s ../@vue/cli-service/bin/vue-cli-service.js vue-cli-service
```

**Comment by vncsmyrnk** [comment]
> I just fixed it by rebuild webpack `npm rebuild webpack` or rebuild all dependencies with `npm rebuild`.

this worked for me!

**Comment by ilejohn-official** [comment]
> I just fixed it by rebuild webpack `npm rebuild webpack` or rebuild all dependencies with `npm rebuild`.

`npm rebuild webpack` didn't work but `npm rebuild` did
