### ISSUE TITLE
report a bug with DllReferencePlugin

### ISSUE THREAD

**Issue by sheweichun** [webpack/webpack#5428]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
My scene is a bit complicated,I use DllPlugin and DllReferencePlugin,when I start to develop, I would check dependencies in package.json,If has a new dependency,I would use DllPlugin to generate a new  dll-only-bundle,then I start to compile my codes with DllReferencePlugin, then something strange has happened,webpack will rebuild many times

**If the current behavior is a bug, please provide the steps to reproduce.**
there steps must be done in one process.
1.use DllPlugin to build dll-only-bundle
2.use express,webpack-dev-middleware,webpack-hot-middleware with HotModuleReplacementPlugin to start server
3.then you will find webpack will rebuild many times,trigger many times HMR

**What is the expected behavior?**
It should not rebuild many times
I had saw the DllReferencePlugin source coude,
```javascript
compiler.plugin("before-compile", (params, callback) => {
			const manifest = this.options.manifest;
			if(typeof manifest === "string") {
                                //_**the problem above is because of the code beblow**_
				params.compilationDependencies.push(manifest);
				compiler.inputFileSystem.readFile(manifest, function(err, result) {
					if(err) return callback(err);
					params["dll reference " + manifest] = JSON.parse(result.toString("utf-8"));
					return callback();
				});
			} else {
				return callback();
			}
		});
```
I write a plugin to fix this like this
```javascript
class HackDllReferencePlugin {
  constructor(options) {
    this.options = options;
  }
  apply(compiler) {
    compiler.plugin('before-compile', (params, callback) => {
      const manifest = this.options.manifest;
      params.compilationDependencies = params.compilationDependencies.filter(val => val !== manifest);
      callback();
    });
  }
}
```
it works, so I doubt what is the use of `params.compilationDependencies.push(manifest)`

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
webpack v3.4.1
node v.10.2
Mac 10.11.6

**Comment by mlucool** [comment]
I am seeing the same issue. This hack fixed it for me too.
