### ISSUE TITLE
[Feature] Expose publicPath to loader context

### ISSUE THREAD

**Issue by FrogTheFrog** [webpack/webpack#5436]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
[nested-require-loader](https://github.com/trutoo/nested-require-loader) uses `this._compilation.options.output.publicPath` which is set to be deprecated, to set `__webpack_public_path__`.

**What is the expected behavior?**
[nested-require-loader](https://github.com/trutoo/nested-require-loader) should use `this.publicPath` to set `__webpack_public_path__`.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Due to [nested-require-loader](https://github.com/trutoo/nested-require-loader)'s nature it is required to known public path at loader execution time so it can set `__webpack_public_path__` for other loaders, however deprecation of `this._compilation` will break this loader completely.

**Comment by evilebottnawi** [comment]
@FrogTheFrog `nested-require-loader` is not part `webpack` or `webpach-org` with loader, please create this issue in `nested-require-loader` repo. Thanks!

**Comment by EECOLOR** [comment]
@evilebottnawi The problem is that `this.publicPath` does not exist in loader context.
