### ISSUE TITLE
Confusing Parser Options

### ISSUE THREAD

**Issue by mrtnbroder** [webpack/webpack#5439]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Description is confusing

**If the current behavior is a bug, please provide the steps to reproduce.**
Go to https://webpack.js.org/configuration/module/#rule-parser,
see confusing description of enable/disable parser options

**What is the expected behavior?**
It would be great to clear up the documentation of the parser options. Right now, I'm really confused if passing `true` would now `disable` or `enable` the parsers?!

**If this is a feature request, what is motivation or use case for changing the behavior?**
I'm so confused.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
irrelevant

**Comment by sokra** [comment]
@webpack-bot move to webpack/webpack.js.org
