### ISSUE TITLE
Option to display loaders output to shell only, not devtools

### ISSUE THREAD

**Issue by avrelaun** [webpack/webpack#5441]
**Do you want to request a *feature* or report a *bug*?**
Feature request

**What is the current behavior?**
The output of loaders (eg. eslint) is currently rendered in both the shell console and the devtools console. The quiet option disable it entirely.

**What is the expected behavior?**

When I'm importing code or while debugging, the output of eslint is redundant between my shell and the devtools console.

Or I'd like to see only logs from the currently running app on my devtools, not being polluted by eslint output. I know that this annoyance shall be resolved by solving the eslint errors, but when I'm coding I do not want to see the console or debugger warnings, yet I'd like to see those in my shell. Plus, some warnings are just warnings and definitely shouldn't make it harder to see the actual console messages from the app.

I'd like to be able to configure the desired output (devtools console, shell console, or both).

**Comment by sokra** [comment]
@webpack-bot move to webpack/webpack-dev-server

**Comment by avrelaun** [comment]
@sokra I'm not using webpack-dev-server, but webpack-dev-middleware + webpack-hot-middleware + express (config generated via vue-cli)

Maybe it should be moved to webpack-hot-middleware instead ?

**Comment by sokra** [comment]
@webpack-bot move to glenjamin/webpack-hot-middleware
