### ISSUE TITLE
ModuleConcatenationPlugin transform re-export module to __WEBPACK_IMPORTED_MODULE_0_lodash__[true]

### ISSUE THREAD

**Issue by morlay** [webpack/webpack#5443]
**Do you want to request a *feature* or report a *bug*?**
Maybe a *bug*, some behavior I don't understand

**What is the current behavior?**
Transformed with undefined error.

**If the current behavior is a bug, please provide the steps to reproduce.**

When I re-export variable from all of some module, And use like below
```js
// ./module.js
import * as lodash from "lodash";
export { lodash };
```
```js
// ./main.js
import { lodash } from "./module"

// webpack will transform here to `__WEBPACK_IMPORTED_MODULE_0_lodash__[true].keys({})`
lodash.keys({}) 
```
I don't understand why `__WEBPACK_IMPORTED_MODULE_0_lodash__[true]`

When I change `./module.js` to 
```js
// ./module.js
import * as l from "lodash";
export const lodash = l;
```
it works again.

**What is the expected behavior?**
first codes of `./module` should be transformed well.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

* Webpack@3.4.1
* Node@8.2.1

**Comment by sokra** [comment]
Seem to be an issue with exporting namespace objects.

**Comment by TheLarkInn** [comment]
I attempted to reproduce this myself locally in multiple varieties on latest and I was unable to do so.  

Is this version of lodash technically a CJS package (regular lodash vs lodash-es)? 

Also, @morlay are you using any plugins such as babel-plugin-lodash or lodash-webpack-plugin (or both?). Could you please provide a minimal reproducible repo for this issue? If so I could probably tackle this myself too.

**Comment by morlay** [comment]
haven't use plugin.
codes with lodash here just show the errors, other CJS package have same issue, like React, moment.

Repo is here https://github.com/morlay/webpack-issue-5443
the error result https://github.com/morlay/webpack-issue-5443/blob/master/__built__/app.js#L81

Without `ts-loader` will got same result.

**Comment by sokra** [comment]
Add this:

``` js
if(exportName === true) return importedVar; // namespace object
```

before this line: https://github.com/webpack/webpack/blob/master/lib/optimize/ConcatenatedModule.js#L44

Because `exportName` is set to `true` here: https://github.com/webpack/webpack/blob/master/lib/optimize/ConcatenatedModule.js#L233-L236

**Comment by sokra** [comment]
And send a PR

**Comment by sokra** [comment]
And write a test

**Comment by sokra** [comment]
I'll do it myself.

**Comment by TheLarkInn** [comment]
Hahaha! Thanks @sokra 

Just returning to this. @morlay if you'd like to verify you are welcome to test against the local branch.

**Comment by morlay** [comment]
@TheLarkInn Cool, It is fixed !
https://github.com/morlay/webpack-issue-5443/blob/master/__built__/app.js#L83

Thanks @sokra  ~
