### ISSUE TITLE
Webpack 3.4.1 yields errors with Typescript loaders when ran from gulp task

### ISSUE THREAD

**Issue by mitchellmorris** [webpack/webpack#5446]
**Do you want to request a *feature* or report a *bug*?** 

bug

**What is the current behavior?**

Running webpack via a gulp task with either ts-loader or awesome-typescript-loader  yields these errors:

    Unhandled Rejection at: Promise Promise {
    <rejected> TypeError: Cannot read property 'default' of undefined
    at /Users/mitchellmorris/Sites/projects/sandbox/node_modules/loader-runner/lib/loadLoader.js:4:66
    } reason: TypeError: Cannot read property 'default' of undefined
    at /Users/mitchellmorris/Sites/projects/sandbox/node_modules/loader-runner/lib/loadLoader.js:4:66

    Unhandled Rejection at: Promise Promise {
    <rejected> TypeError: Cannot read property 'default' of undefined
    at /Users/mitchellmorris/Sites/projects/sandbox/node_modules/loader-runner/lib/loadLoader.js:4:66
    } reason: TypeError: Cannot read property 'default' of undefined
    at /Users/mitchellmorris/Sites/projects/sandbox/node_modules/loader-runner/lib/loadLoader.js:4:66

**If the current behavior is a bug, please provide the steps to reproduce.**

Given the following webpack.config.js

    const path = require('path');
    let _root = path.resolve(__dirname);
    var fromRoot = function (...args) {
        args = Array.prototype.slice.call(args, 0);
        return path.join.apply(path, [_root].concat(args));
    };
    module.exports = {
        context: fromRoot( "src" ),
        devtool: "cheap-module-eval-source-map",
        entry: {
            "app/polyfills": "./app/polyfills.ts",
            "app/vendor": "./app/vendor.ts"
        },
        resolve: {
            modules: [
                fromRoot( "src", "node_modules" ),
                fromRoot( "node_modules" )
            ],
            extensions: ["*", ".js", ".ts"],
            alias: {
                build: fromRoot( "build", "src", "public" ),
                jquery: fromRoot( "src", "node_modules", "jquery", "src", "jquery" )
            }
        },
        module: {
            rules: [{
                    test: /\.ts$/,
                    use: [
                        {
                            loader: "ts-loader",
                            options: {
                                configFileName: fromRoot( "src", "tsconfig.json" ),
                                compilerOptions: {
                                    rootDir: fromRoot( "src" ),
                                    outDir: fromRoot( "build", "src", "public" )
                                }
                            }
                        }
                    ]
                }
            ]
        },
        output: {
            path: fromRoot("build", "src", "public"),
            publicPath: "/",
            filename: "[name].js",
            chunkFilename: "[id].chunk.js"
        }
    };

Running `webpack` works.

Given the following file, test.js:

    var webpack = require("webpack");
    var webpackConfig = require("./webpack.config.js");

    var compiler = webpack(webpackConfig, (err, stats) => {	
        if (err) {
            console.error(err);
        };
    });

Running `node ./test.js` works.

But given the following gulp task:

    var webpack = require("webpack");
    var webpackConfig = require("./webpack.config.js");
    var starting = true;
    gulp.task("ugh", function(cb) {
        var compiler = webpack(webpackConfig, (err, stats) => {	
            if (err) {
                console.error(err);
            };
            if (starting) {
                starting = false;
                cb();
            }
        });
    });

I am getting the errors mentioned above.

**What is the expected behavior?**

Should work? Or am I missing something?

**If this is a feature request, what is motivation or use case for changing the behavior?**

Working with Gulp

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

I did comment on a long standing issue at https://github.com/webpack/loader-runner/issues/16 but thought I'd file the issue here as I am not sure exactly where it stems.

**Comment by TheLarkInn** [comment]
Do you think I could twist your arm into providing a more minimal reproducible repo that we could test against? There's a lot going on here in the aforementioned information that make it hard to really know what the cause could be.

**Comment by mitchellmorris** [comment]
Sure I am crunched for time this week and temporarily got around this error by forking the loader-runner repo and commenting out some code but Ill put together a repo next weekend.

**Comment by mitchellmorris** [comment]
Oops, clicked the close button ...

**Comment by evilebottnawi** [comment]
@mitchellmorris problem still exists?

**Comment by rbmanian75** [comment]
I am facing this error too with the new version of webpack
