### ISSUE TITLE
[BUG] UglifyJs only works with ES5

### ISSUE THREAD

**Issue by trusktr** [webpack/webpack#5449]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

When adding the `UglifyJsPlugin`, I get an error like

```
ERROR in global.js from UglifyJs
Unexpected token: name (resolve) [global.js:1218,8]
```

where the problem like is like this:

```js
function animationFrame() {
    let resolve = null; // <--------------------------------- RIGHT HERE
    const promise = new _promise2.default(function (r) {
        return resolve = r;
    });
    window.requestAnimationFrame(resolve);
    return promise;
}
```

**If the current behavior is a bug, please provide the steps to reproduce.**

This is a bug, because not all loaders convert JavaScript to strictly ES5 (which [UglifyJs requires](https://github.com/mishoo/UglifyJS2
)). For example, `buble-loader` can convert JavaScript code for relatively new browser targets, which results in `let` and `const` statements that UglifyJs seems to crash on.

**What is the expected behavior?**

I should be able to stick `buble-loader` into my Webpack project, and I should be able to use something like `UglifyJsPlugin` to minify it.

However, this only works if one uses something like Babel to completely convert to ES5.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

I'm on Webpack `3.4.1`.

Look how many people have had this problem: https://github.com/joeeames/WebpackFundamentalsCourse/issues/3

**Comment by trusktr** [comment]
Maybe UglifyJs can use the [ES6+ version](https://github.com/mishoo/UglifyJS2/tree/harmony).

**Comment by trusktr** [comment]
Alright, I found a solution that works with more modern code: [babili-webpack-plugin](https://github.com/webpack-contrib/babili-webpack-plugin).

So I'm using

```js
const BabiliPlugin = require("babili-webpack-plugin");
new BabiliPlugin
```

instead of

```js
const UglifyJsPlugin = require('webpack/lib/optimize/UglifyJsPlugin')
new UglifyJsPlugin
```

**Comment by GaryChangCN** [comment]
https://github.com/babel/babili

**Comment by sokra** [comment]
see also https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/105

**Comment by damsorian** [comment]
@trusktr  can you comment you entire webpack.config here?  I have the same issue but is not working for me.

**Comment by trusktr** [comment]
@damsorian just replace `webpack/lib/optimize/UglifyJsPlugin` with `babili-webpack-plugin`. You have to `npm i babili-webpack-plugin --save-dev` first.

**Comment by ickyrr** [comment]
in my case, this [answer](https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/105#issuecomment-320514526) helped me.
