### ISSUE TITLE
Incorrect description for --resolve-extensions parameter

### ISSUE THREAD

**Issue by tomek-d** [webpack/webpack#5451]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
"Module not found: Error: Can't resolve...." - error caused by wrong command line interface parameter description. Description for --resolve-extensions states: "Setup extensions that should be used to resolve modules (Example: --resolve-extensions .es6 .js)". In this description extensions are separated by whitespace but in code following regexp is used `options.resolve.extensions = value.split(/,\s*/);` which means that extensions are separated by comma and any number of whitespace characters.

**If the current behavior is a bug, please provide the steps to reproduce.**
Gist with example configuration: https://gist.github.com/tomek-d/53197f07c042842fab9d2c1b77651256
Please take a look on scripts section in package.json
This is rather trivial issue and I am happy to work on PR for it.

**What is the expected behavior?**
Code transpiled and bundled. 

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
webpack@3.4.1

**Comment by sokra** [comment]
Great find. Send a PR fixing it.
