### ISSUE TITLE
Tree shaking doesn't work with "export { className } from 'module'"

### ISSUE THREAD

**Issue by alan-agius4** [webpack/webpack#5452]
**Do you want to request a *feature* or report a *bug*?** bug

**What is the current behavior?**
I have 2 files, 

``` vendors
export class HelloWorldUnused {
	sayHello () {
		return "hello world";
	}
}

export class HelloWorldUsed {
	sayHello () {
		return "hello world";
	}
}
```

``` index
import { HelloWorldUsed } from "./vendor";

const helloWorld = (new HelloWorldUsed()).sayHello();

export { HelloWorldUnused, HelloWorldUsed } from "./vendor";
```

``` output
webpackJsonp([0],[
/* 0 */,
/* 1 */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var vendor_1 = __webpack_require__(0);
var helloWorld = (new vendor_1.HelloWorldUsed()).sayHello();
var vendor_2 = __webpack_require__(0);
exports.HelloWorldUnused = vendor_2.HelloWorldUnused;
exports.HelloWorldUsed = vendor_2.HelloWorldUsed;


/***/ })
],[1]);
//# sourceMappingURL=app.bundle.map
```

In my final bundle, the unused classed is still being shipped and not threeshaken.

**If the current behavior is a bug, please provide the steps to reproduce.**
https://github.com/alan-agius4/typescript-webpack-error-treeshaking

**What is the expected behavior?**
The unused class is removed from "app.bundle.js"

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**  v3.4.0

**Comment by sokra** [comment]
* Typescript is configured to transpile ESM to CJS
* exporting things from entry points make them "used"

**Comment by alan-agius4** [comment]
What if the file is a seperate is library, How can it be tackling?

**Comment by alan-agius4** [comment]
@sokra I have updated the code, and the problem still persist the unused class is still being exported
