### ISSUE TITLE
Same package appearing in multiple places gets included multiple times

### ISSUE THREAD

**Issue by yachaka** [webpack/webpack#5455]
**Do you want to request a *feature* or report a *bug*?**

A bug

**What is the current behavior?**

See the repo to reproduce the issue: https://github.com/yachaka/webpack-duplicate-module-issue
Having the following folder structure,
```js
webpack.config.js // entry: package1/index.js
package1/
    package.json // dependency: lodash@4.17.4
    index.js // import package2 from '../package2'
package2/
    package.json // dependency: lodash@4.17.4
    index.js
```

With the files `package1/index.js` and `package2/index.js` being:
**package1/index.js**
```js
const _ = require('lodash');
require('../package2/');
```

**package2/index.js**
```js
const _ = require('lodash');
```
Lodash gets included 2 times, even though it is the same version that is installed in both package.
I though this was intended to be deduped.

**If the current behavior is a bug, please provide the steps to reproduce.**

- Get the configuration as provided above (https://github.com/yachaka/webpack-duplicate-module-issue)
- run webpack
- notice lodash is included 2 times in the bundle, with both time the same version

**What is the expected behavior?**

lodash gets included only one time as the version in both package.json is the same

**If this is a feature request, what is motivation or use case for changing the behavior?**
/

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Mac Sierra 10.12.5
node.js 8.1.4
webpack 3.4.1

**Comment by sokra** [comment]
When you install it twice, it'll get included twice...

This is how resolving works. 

see also:

* https://github.com/darrenscerri/duplicate-package-checker-webpack-plugin
* https://github.com/niieani/webpack-dependency-suite/blob/master/plugins/root-most-resolve-plugin.ts
* `resolve.modules`

**Comment by yachaka** [comment]
@sokra Ok, I see.

I remember there was a `DedupePlugin`. Was this plugin made to solve this issue ? I saw it has been removed in webpack 2.

Is there a way for me to keep dependencies isolated while still having a bundle without duplicates ?

**Comment by Jack89ita** [comment]
@yachaka have you found any solutions to this? I've got the same problem..

**Comment by yachaka** [comment]
@Jack89ita Unfortunately, I didn't find a fix to this. :/ Only fix is to have only one parent dependency.

**Comment by evancaldwell** [comment]
I'm also trying to solve this. I was under the impression that Webpack _did_ de-dupe these. The only way I have gotten it to work is having a peer dependency in the **package2** `package.json`, ensuring that those peer dependencies are installed in **package1**'s `node_modules` and aliasing them in the `webpack.config.js` so the imports in both packages resolve properly when bundled. However, this also means that **package1** has fake dependencies because if there is a shared dependency for **package2** and a **package3**, **package1** would also have to have that installed even if it doesn't actually use it. It feels like if we are already in a build step this should be de-duped

**Comment by ru-web-designer** [comment]
I don't really have much workaround, but i have [this comment in related issue, i guess](https://github.com/webpack/webpack/issues/2134#issuecomment-421162285). And also i have [this repo](https://github.com/ru-web-designer/lerna-webpack-typescript) for illustrationg the problem in the box.

Any suggestions?

**Comment by jianzhou520** [comment]
In my situation, right yarn workspace config fixed this problem

**Comment by margox** [comment]
Any news?  I'm facing the same issue :(

**Comment by valentinbdv** [comment]
+1 ;)

**Comment by CharanRoot** [comment]
> yarn workspace config fixed

can you post yarn config.
