### ISSUE TITLE
ModuleConcatenationPlugin renames Classes

### ISSUE THREAD

**Issue by Michael-Tajmajer-Emrsn** [webpack/webpack#5463]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
when ModuleConcatenationPlugin is enabled some classes are renamed.

Generated code without ModuleConcatenationPlugin:
class PatternBrush extends __WEBPACK_IMPORTED_MODULE_1__brush__.a{constructor(args)...

Generated code with ModuleConcatenationPlugin:
class pattern_brush_PatternBrush extends Brush{constructor(args)

**If the current behavior is a bug, please provide the steps to reproduce.**
I haven't discovered why some of my classes are renamed and some are not.

I'm asking with a hope that somebody will see this and have a thought or suggestion.

**What is the expected behavior?**
Class names are not changed.  Renaming the class breaks non-webpacked modules (dynamically generated). 

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Chrome 60, Node v7.10.0, Webpack 3.5.1, Windows 10,

**Comment by sokra** [comment]
webpack renames identifiers when concatenating two modules with the same identifier to avoid conflicts.

Minimizing will rename these identifiers anyway, so your code should not rely on the names.

Names are chosen in a way that make it easy to identify the original identifier and origin module.

Why is the renaming a problem?

**Comment by Michael-Tajmajer-Emrsn** [comment]
We use the class name (Function.name) as a key in places, renaming the class (function) changes the name.

Not an insurmountable problem, we could add a instance property, or use constants.

But, before we do this we're trying to see if there is a way to configure webpack so that the existing code will keep working.

**Comment by sod** [comment]
Instead of the function name and objects you could use `Map` and the function itself as identifier:

```javascript
map = new Map()
a = function() {}
map.set(a, 'value a')
console.log(map.get(a)) // value a
```

Be sure to include [a map shim](https://github.com/zloirock/core-js/blob/v2.5.0/modules/es6.map.js) if you need to support older browsers

**Comment by Michael-Tajmajer-Emrsn** [comment]
yes, there are many ways to rewrite the code to work as expected.

We're exploring ways to allow the existing code to continue to function before we change it :-)

Any thoughts on how we could configure webpack to preserve the Function.name?

**Comment by sokra** [comment]
> We use the class name (Function.name) as a key in places, renaming the class (function) changes the name.

You code will break when minimizing it. Really consider rewriting it.

> Any thoughts on how we could configure webpack to preserve the Function.name?

Don't use the `ModuleConcatenationPlugin`. For module concatenation it's required to be able to rename identifiers.

**Comment by trusktr** [comment]
Why not just don't break JavaScript spec?
