### ISSUE TITLE
Tried to switch from 2.5.0 to 2.7.0

### ISSUE THREAD

**Issue by richtera** [webpack/webpack#5464]
**Do you want to request a *feature* or report a *bug*?**
Seems to be a bug or requires slightly different configuration.

**What is the current behavior?**
When using 2.7.0 I cannot connect to the sockjs-node since it uses a path with two slashes in it.
//sockjs-node instead of /sockjs-node.

**If the current behavior is a bug, please provide the steps to reproduce.**
Seems to be a bug switching back to 2.5.0 makes it work right away.
Seems to be related to how client now calculates the socket path not removing a single /

**What is the expected behavior?**
Both 2.5.0 and 2.7.0 should work the same regarding this part.
Since this didn't work I didn't investigate further but my proxies also seemed affected.

**If this is a feature request, what is motivation or use case for changing the behavior?**
I think it's broken, but maybe it's a new requirement in the config.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
I am using 6.11 node.
Mac OS X 10.12.6

**Comment by sokra** [comment]
@webpack-bot move to webpack/webpack-dev-server
