### ISSUE TITLE
caching problem: delete js file or add js file, many js files's hash will change

### ISSUE THREAD

**Issue by huangshuwei** [webpack/webpack#5470]
**Do you want to request a *feature* or report a *bug*?**

report a bug.

**What is the current behavior?**

When i follow the official documentation  https://webpack.js.org/guides/caching/ ，
I found that if I delete a js file or add a js file, many js files's hash will change.

**If the current behavior is a bug, please provide the steps to reproduce.**
This is my first compiled file's hash
![first](https://user-images.githubusercontent.com/6047141/29109538-e4cc0ab4-7d15-11e7-9a17-0ce71d018962.png)

If i delete a js file(zTree.js),Then I recompile
![se](https://user-images.githubusercontent.com/6047141/29109951-84d9bdd4-7d17-11e7-92a2-dbf85bdb53ea.png)

It was solved when I use the 'webpack-chunk-hash' or 'webpack-md5-hash' plugin, But the runtime file's hash will never changes.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
operating system:win10
node:6.10.0
webpack:3.5.1

**Comment by sokra** [comment]
Do you use records, NamedModules or HashedModuleIds?

**Comment by huangshuwei** [comment]
@sokra 
I have used the ‘HashedModuleIdsPlugin’ plugin
```
// webpack.config.js
new webpack.HashedModuleIdsPlugin()
```

**Comment by huangshuwei** [comment]
@sokra 
here is my plugin options:
```
// webpack.config.js
plugins:[
        new webpack.optimize.CommonsChunkPlugin({
            name: 'vendor'
        }),

        new webpack.optimize.CommonsChunkPlugin({
            name: 'runtime'
        }),

        new webpack.HashedModuleIdsPlugin(),

        new ManifestPlugin({
            fileName: 'fileMaps.json',
            basePath: ''
        }),

        new webpack.ProvidePlugin({}),

        new HtmlWebpackPlugin({
            filename: 'index.html',
            template: __dirname + '/examples/index.html',
            inject: 'true'
        })
    ];


```

**Comment by Darmody** [comment]
@huangshuwei Hey, I have same issue.

Do you fix it?

**Comment by huangshuwei** [comment]
>@huangshuwei Hey, I have same issue.
Do you fix it?

not yet , It's a real problem.
Hope to reply as soon as possible @sokra

**Comment by Darmody** [comment]
@rowanoulton 

Extract a manifest with the CommonsChunkPlugin is the point. That saves my life.

@huangshuwei 

Your chunks is a series of numbers which depend on files' order. So chunks will changing after files added or removed (files' order changed!!!). I resolved this problem by use `webpack.namedChunksPlugin` which use module name as chunks. Hope it is useful.

**Comment by PanJiaChen** [comment]
@Darmody 
`namedChunksPlugin` is suggested for use in development, I have some concerns in production env use it.
