### ISSUE TITLE
Some documentation would be nice

### ISSUE THREAD

**Issue by Sunhat** [webpack/webpack#5472]
**Do you want to request a *feature* or report a *bug*?**
Documentation

**What is the current behavior?**
No Documentation

**If the current behavior is a bug, please provide the steps to reproduce.**
Write Documentation.

**What is the expected behavior?**
Documentation to exist

**If this is a feature request, what is motivation or use case for changing the behavior?**
So people can use webpack

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by TrySound** [comment]
@Sunhat https://webpack.js.org/
