### ISSUE TITLE
Circular dependencies unresolved from 3.4.1 -> 3.5.x

### ISSUE THREAD

**Issue by gpoitch** [webpack/webpack#5476]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
A circular dependency which correctly resolved in 3.4.1 is now undefined in 3.5.1-2 with the ModuleConcatenationPlugin

**If the current behavior is a bug, please provide the steps to reproduce.**
- Install 3.5.2 and use the ModuleConcatenationPlugin.
- Create a circular dependency
- Builds successfully
- See it's undefined when imported

Either downgrading to 3.4.1, or removing the ModuleConcatenationPlugin fixes the issue.

**What is the expected behavior?**
Either the dependency correctly resolves as it did before, or the webpack build errors because it can't resolve the circular dependency.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
node 8.1.4
webpack 3.5.2
os x 10.12.5

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by gpoitch** [comment]
I will try to work on a minimal reproduction.

This plugin has been valuable in detecting circular dependencies: https://github.com/aackerman/circular-dependency-plugin

However, it doesn't work 100% with the ModuleConcatenationPlugin because it checks in the 'done' hook.  @sokra Any tips on what compilation events that should hook into instead?

**Comment by gpoitch** [comment]
I wasn't able to reproduce with a minimal dependency graph.
 https://github.com/gpoitch/webpack-circ-dep-bug

I actually prefer that it isn't able to resolve the circular dependency so it can be fixed by the developer. I'd rather see better error messages as mentioned [here](https://github.com/webpack/webpack/issues/5031), or be able to use this [plugin](https://github.com/aackerman/circular-dependency-plugin) alongside ModuleConcatenationPlugin
