### ISSUE TITLE
3.5.0 introduces breaking change in ConcatenatedModule public API (modules property was removed)

### ISSUE THREAD

**Issue by kisenka** [webpack/webpack#5477]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`ConcatenatedModule.modules` property was removed ([link to commit](https://github.com/webpack/webpack/commit/ec3aa7be5d61a65e70492d11c38774d1bd5fa152#diff-e33d2e7031dc20d53a5c70153b79adf2L137)).
In my webpack loader I need to extract original modules from ConcatenatedModule to replace some values in them. Now with 3.5 [I use private property `_orderedConcatenationList`](https://github.com/kisenka/svg-sprite-loader/blob/508af1eed570912a81f7187e2bc8353ebbf82c58/lib/utils/get-all-modules.js#L37) which potentially can be removed or renamed in future.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
I suggest to return this property for backwards compatibility. It can be a getter for instance.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
webpack version: 3.5.1

**Comment by sokra** [comment]
send a PR
