### ISSUE TITLE
Some way to provide entry files encodings (cp-1251) and readFiles in this encoding 

### ISSUE THREAD

**Issue by Rosstik** [webpack/webpack#5479]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
I have my project files encoded in cp-1251, when webpack (or webpack dev server) works with my entry files (require some js files, styl files and etc...) it opens my files with utf-8 encoding, that results in broken characters (instead of string "Совпадения" i get "CпїЅпїЅпїЅпїЅпїЅпїЅпїЅпїЅпїЅ")

**If the current behavior is a bug, please provide the steps to reproduce.**
Your could save your entry files in "cp1251" (or "windows1251") with some russian letters like "привет мир" and then try to create bundle

**What is the expected behavior?**
I think that this behavior is expected, but that would be great if i could specify encoding for webpack, via some settings (configs), so it would open my files with provided encoding.

**If this is a feature request, what is motivation or use case for changing the behavior?**
My motivation is to change utf-8 core webpack encoding to more multilanguage way
 
**Please mention your webpack and Operating System version.**
webpack 3.5.2 and windows 10 OS

//I tried https://www.npmjs.com/package/webpack-encoding-plugin, but it gets applied after characters already broken by opening in wrong encoding
///I tried to find where in webpack sources happens files reading in wrong encoding and founded it, but this project is too big, and i could not find in which places i shoud write instead of fs.readFileSync(ARGS.o, "utf8") some conversion by iconv code that would readFile in win1251

**Comment by Rosstik** [comment]
I solved it with https://www.npmjs.com/package/webpack-encoding-plugin
Not a solution, but kinda workaround
I converted all my files in UTF-8 for webpack, work with them, and then convert it in cp1251 by encoding plugin

**Comment by waspar** [comment]
It works for me. If site in cp-1251.

```
plugins.EncodingPlugin = require('webpack-encoding-plugin');
....
	, plugins: [

		// - encoding
		new plugins.EncodingPlugin({
			encoding: 'cp-1251'
		}),
```
