### ISSUE TITLE
this._ir.once is not a function

### ISSUE THREAD

**Issue by willin** [webpack/webpack#5490]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

<img width="566" alt="wx20170810-203354 2x" src="https://user-images.githubusercontent.com/1890238/29170451-48a5400e-7d9e-11e7-9786-5356626a2bc1.png">

rails/webpacker#570

source code: https://github.com/AirDwing/vuetify-demo

**If the current behavior is a bug, please provide the steps to reproduce.**

have no idea 

**What is the expected behavior?**

perhaps it's related to devserver

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

- node v8.1.4
- webpack 3.5.1
- webpack-dev-server 2.7.1

**Comment by sokra** [comment]
@webpack-bot move to webpack/webpack-dev-server
