### ISSUE TITLE
Allow falsy values in plugins array

### ISSUE THREAD

**Issue by bgmort** [webpack/webpack#5493]
**Do you want to request a *feature* or report a *bug*?**
Feature.

**What is the current behavior?**
passing `undefined`, `null`, or `false` in a plugins array results in the following error:
TypeError: arguments[i].apply is not a function

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**
Allowing falsy values in the plugins array would allow much simpler plugin definition:

```javascript
plugins: [
    isProd ? new webpack.optimize.UglifyJsPlugin() : null,
    //or
    isDev && new someOtherPlugin(),
 ]
```

There are other ways to accomplish this right now, but all of them are clunkier, more verbose, and/or more repetitive.  Case in point:  The [noop-webpack-plugin](https://www.npmjs.com/package/noop-webpack-plugin) exists to enable this pattern, but it shouldn't have to exist at all.

I'm happy to submit a PR for it when I get around to it, but won't be hurt if anyone else would like to beat me to it.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

I installed webpack 3.5.3 to verify that this is still not supported before filing the issue.

**Comment by michael-ciniawsky** [comment]
Just

**webpack.config.js**
```js
plugins: [
  env === 'production' : new Plugin() : false,
].filter(Boolean)
```

?

**Comment by TheLarkInn** [comment]
I agree with @michael-ciniawsky. By allowing falsies, users open themselves up to a lot of harder to debug problems. If a real plugin is broken and is returning those values or a default prop that isn't assigned, the user will never know and would softly and quietly ignore it.

So I'd recommend what @michael-ciniawsky is recommending over said feature. Does that argument sound reasonable to you @bgmort?

**Comment by niieani** [comment]
You can also make a helper method and use this kind of a pattern, which is arguably more readable:

https://github.com/aurelia/skeleton-navigation/blob/20fc09a0270c15545cd668ba6872ca4ad2951ecc/skeleton-typescript-webpack/webpack.config.js#L122-L124

**Comment by TheLarkInn** [comment]
Ya exactly!!!

**Comment by bgmort** [comment]
I think for me, this is about making configuration as user friendly and declarative as possible, and providing a simple pattern to accomplish what I think must be a pretty common use case.  Those of us with plenty of experience will have no trouble coming up with a multiple workable ways to make our configurations dynamic, but some are bound not to work as intended, and it would be nice to give some help to developers who may need it so they aren't spinning their wheels (and bloating their list of dependencies) looking for complicated solutions to simple problems.

@michael-ciniawsky's suggestion is really nice and clean, and being able to troubleshoot misbehaving plugins is a decent argument for not allowing falsy values.  I would suggest that maybe a pattern along those lines be used in some common examples, but any benefits gained by not allowing non-plugin values in the array are lost when using such a pattern.

I'll throw out another idea:  Add a symbol as sentinel value to represent no-op behavior instead of undefined or null.  Something like `webpack.None = Symbol('none');`  Then you don't have to worry about it accidentally being returned from a malfunctioning plugin.  Such a value could be used in several other places as well.  Sure, you can do the same thing any number of other ways, but the more you can standardize patterns for using webpack, the less time developers new to webpack will spend trying to invent their own solutions, a portion of which you'll end up trying to help troubleshoot.

**Comment by buoyantair** [comment]
I feel like this problem can be solved with those beautiful solutions @michael-ciniawsky & @niieani have given. Maybe this issue can be closed, What do you guys think? :D

**Comment by evilebottnawi** [comment]
Yes, close issue, thanks everyone!
