### ISSUE TITLE
ConcatenatedModulePlugin 3.5.x breaks hot reload

### ISSUE THREAD

**Issue by modosc** [webpack/webpack#5504]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
in development, i make a change to a file and wait for hmr to run. 

with `ConcatenatedModulePlugin` enabled and with version `3.5.3` i get errors and hmr fails.
with `ConcatenatedModulePlugin` disabled and with version `3.5.3` hrm works.
with `ConcatenatedModulePlugin` enabled and with version `3.4.1` hmr works.

**If the current behavior is a bug, please provide the steps to reproduce.**
make a change in a file:

![image](https://user-images.githubusercontent.com/2231664/29222257-962e353c-7e76-11e7-89d7-c931f20b196d.png)
![image](https://user-images.githubusercontent.com/2231664/29222265-a4057ff8-7e76-11e7-9914-bb2d441ceb07.png)
![image](https://user-images.githubusercontent.com/2231664/29222282-b4cba25e-7e76-11e7-8fca-4b479e8d8dc6.png)

the referenced line in `client.js` is:
```
    if (module.hot) {
      module.hot.accept('./app/Router', () => {
```

and in the compiled src for `client.js` i found this:
```
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_19_selectors_zipcode__ = __webpack_require__("oPy7");
```
but no declaration of `__WEBPACK_IMPORTED_MODULE_19__app_Router__`. the `module.hot.accept` section looks like this:
```
module.hot.accept("WuSt",function(__WEBPACK_OUTDATED_DEPENDENCIES__) {
 /* harmony import */  __WEBPACK_IMPORTED_MODULE_19__app_Router__ = __webpack_require__("WuSt"); 
```

**What is the expected behavior?**
using `3.4.1` hrm works as expected and looking into `client.js` i see:
```
/* harmony import */ var __WEBPACK_IMPORTED_MODULE_19__app_Router__ = __webpack_require__("WuSt");
```
and
```
module.hot.accept("WuSt",function(__WEBPACK_OUTDATED_DEPENDENCIES__) { 
/* harmony import */ __WEBPACK_IMPORTED_MODULE_19__app_Router__ = __webpack_require__("WuSt"); 
```

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
most recent node, webpack, osx.

**Comment by sokra** [comment]
Yep that's a bug

**Comment by ismail-syed** [comment]
@modosc I'm not able to reproduce this. 
Can you share this issue in a small reproducible example?

**Comment by modosc** [comment]
hey @sokra - thanks for the quick response. `3.5.4` seems to make hmr work again (at least according to the console, no more errors) but the results are.. strange. lots of react errors, elements not showing up, etc. i don't have time to put together another bug / test case this morning but i will later today or tomorrow, i just wanted to give you a heads up.

**Comment by sokra** [comment]
Create a new issue, if you have a repro case.
