### ISSUE TITLE
Webpack const isWin is not compiled to var

### ISSUE THREAD

**Issue by Manrix** [webpack/webpack#5507]
**Do you want to request a *feature* or report a *bug*?**
Report a bug.

**What is the current behavior?**
Webpack compiles the bundle and adds this line of code:

`/* WEBPACK VAR INJECTION */(function(process) {const isWin = process.platform === 'win32';`

The **const** is not converted to var and this makes old browsers trigger a syntax error. With same project i previously used webpack 2 and this didn't happen.

**If the current behavior is a bug, please provide the steps to reproduce.**
This is my rule for js:
```
test: /\.js$/,
  exclude: [/node_modules/],
  loader: 'babel-loader',
  options: {
    presets: [['es2015', { modules: false }]],
    plugins: ["transform-vue-jsx","transform-runtime"],
}
```

**What is the expected behavior?**
Compile const to var ?

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Node: 6.11.2
Webpack: 3.5.3
OS: Windows 10
If i change const to var manually, all works fine.

**Comment by hkrutzer** [comment]
Webpack does not transpile `const` to `var`. Babel should do that, are you using [this](https://searchcode.com/file/133047436/nestedDataTables/node_modules/remove-trailing-separator/index.js) library which is included from node_modules and therefore not transpiled?

**Comment by Manrix** [comment]
Yes, i know. I use babel but that const is the only one not transpiled in all my bundle.
Yes, the library you linked is the exactly code. Do you know why that library is added ? I can't figure it.

**Comment by hkrutzer** [comment]
You should be able to check that with `npm ls` or `yarn list` if you use yarn.

**Comment by Manrix** [comment]
This is what i got:
```
`-- babel-cli@6.24.1
  `-- chokidar@1.6.1
    `-- anymatch@1.3.0
      `-- micromatch@2.3.11
        `-- normalize-path@2.1.1
          `-- remove-trailing-separator@1.0.1
```

**Comment by hkrutzer** [comment]
That is incomplete, it should include every library and that does not even include Webpack.

**Comment by Manrix** [comment]
I did _npm ls remove-trailing-separator_. Do you need the complete npm ls ?

**Comment by TheLarkInn** [comment]
@manrix is that isWin coming from a node_module? 

You should check the package.json for that node module and see if they are shipping the es6 code in their "main", or "module" field. webpack will resolve "module" before "main" and therefore will server up the code starting from that entry path vs "main" (which may contain the transpiled down distribution".

**Comment by Manrix** [comment]
Yes, that package is in node_modules and seems to be related to babel-cli. But i can't understand why is there. In its package.json there's **"main": "index.js"**.

**Comment by asotog** [comment]
same issue here, getting `const` everywhere coming from webpack code ```/* global __resourceQuery WorkerGlobalScope self */
/* eslint prefer-destructuring: off */

const url = __webpack_require__(55);
const stripAnsi = __webpack_require__(61);
const log = __webpack_require__(63).getLogger('webpack-dev-server');
const socket = __webpack_require__(64);
const overlay = __webpack_require__(96);
```

**Comment by danibram** [comment]
Same here with a typescript project
```{
        test: /\.ts$/,
        exclude: /node_modules/,
        use: [
            { loader: 'babel-loader' },
            { loader: 'awesome-typescript-loader' },
        ],
    },
```

Produces:

```
/* global __resourceQuery WorkerGlobalScope self */
/* eslint prefer-destructuring: off */

const url = __webpack_require__(203);
const stripAnsi = __webpack_require__(209);
const log = __webpack_require__(211).getLogger('webpack-dev-server');
const socket = __webpack_require__(212);
const overlay = __webpack_require__(244);
```

**Comment by asotog** [comment]
@TheLarkInn should this be reopened ? issue is there

**Comment by hkrutzer** [comment]
Not the same issue, nor an issue with Webpack. webpack-dev-server dropped support for browsers that don't support `let` or `const`, see https://github.com/webpack/webpack-dev-server/issues/1104#issuecomment-330516760.

**Comment by asotog** [comment]
thanks @hkrutzer  for the clarification, just checked the generated prod file does not have the issue, it only happens when user dev server, so no more a concern for me

**Comment by danibram** [comment]
Thanks for the clarifications and for your time @hkrutzer and @asotog!
