### ISSUE TITLE
Uncaught TypeError: os.homedir is not a function

### ISSUE THREAD

**Issue by Deadly0** [webpack/webpack#5512]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
After compiling a bundle with deps which use `os.homedir` function (for example `is-reachable`) i've got the error in the runtime: `Uncaught TypeError: os.homedir is not a function`
In the bundle `os.homedir` is undefined. 

**What is the expected behavior?**
`os.homedir` shoud be a function 

Please update `os-browserify` package to the latest version (0.3.0) to get support of `os.homedir` function in bundle.

**Comment by sokra** [comment]
@webpack-bot move to webpack/node-libs-browser
