### ISSUE TITLE
https://webpack.js.org/ sends wrong .css file.

### ISSUE THREAD

**Issue by phiilu** [webpack/webpack#5513]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

The css file for https://webpack.js.org/ is missing.

**If the current behavior is a bug, please provide the steps to reproduce.**

Open https://webpack.js.org/ in the browser. Also with a hard reload the css file can not be found.

![bildschirmfoto 2017-08-14 um 17 44 35](https://user-images.githubusercontent.com/8149519/29279490-48b5bcd6-8118-11e7-8cfb-fdeeb3023930.png)

**What is the expected behavior?**

The browser loads the css file and the website displays correctly.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

* Browser: Google Chrome 59.0.3071.115 
* OS: mac OS Sierra 10.12.5

**Comment by sokra** [comment]
@webpack-bot move to webpack/webpack.js.org
