### ISSUE TITLE
webpack command not found

### ISSUE THREAD

**Issue by Ollie-w** [webpack/webpack#5516]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
I am running NPM 5.3 and Node 8.1.3 on Ubuntu. I did npm install webpack --save-dev 
Webpack is appearing in my package.json
 
"devDependencies": {
    "webpack": "^3.5.4"
  }

On command line I am getting "webpack command not found"

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by sokra** [comment]
Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md).

**Comment by adrianflda** [comment]
Hi, @Ollie-w I am having the same problem. How did you resolve it???
