### ISSUE TITLE
Support 'overrides' option for bower.json

### ISSUE THREAD

**Issue by mizchi** [webpack/webpack#552]
This example can't support bower overrides options.
http://webpack.github.io/docs/usage-with-bower.html

`bower overrides` spec is here.
https://github.com/bower/bower/issues/585

Now I take file by `foo/dist/foo.min.js` for work arround. Browserify and https://github.com/ck86/main-bower-files support it.

**Comment by shama** [comment]
Closing as the issue has moved to here: https://github.com/lpiepiora/bower-webpack-plugin/issues/21 Thanks!
