### ISSUE TITLE
Request organization that it attaches webpack site link

### ISSUE THREAD

**Issue by TonyPythoneer** [webpack/webpack#5521]
**Do you want to request a *feature* or report a *bug*?**

Feature. I hope [organization site](https://github.com/webpack) that it attaches [webpack site link](https://webpack.js.org).

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by sokra** [comment]
done
