### ISSUE TITLE
Error when upgrading to webpack 3.

### ISSUE THREAD

**Issue by gdborton** [webpack/webpack#5527]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Valid modules aren't found in final webpack output. The browser console shows the following `Uncaught TypeError: Cannot read property 'call' of undefined`.   There is an attached repository, and somehow this is related to CommonsChunkPlugin, externals, and I believe hbsfy.

**If the current behavior is a bug, please provide the steps to reproduce.**

Follow the directions in this README - https://github.com/gdborton/call-error

There are directions for creating the error, and steps to show that it doesn't error out in webpack 2.

**What is the expected behavior?**
No `Uncaught TypeError: Cannot read property 'call' of undefined` error when loading pages. These modules exist and aren't related to the externals config, they should be included in the bundles.

**If this is a feature request, what is motivation or use case for changing the behavior?**
N/A

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
I don't think it's relevant, but...
Node - 6.10.2
Npm - 2.15.12
webpack - 3.x (RCs, 3.0.0-3.5.4 tested)
Mac OSX - 10.12.6
Chrome - 60.0.x

**Comment by sokra** [comment]
Thanks for the repro case. It was a difficult bug, but I have a fix.
