### ISSUE TITLE
How to ignore nodejs modules?

### ISSUE THREAD

**Issue by ronag** [webpack/webpack#553]
I'm trying to use "upnode" with webpack. However, upnode requires nodejs modules that are not used client side. However, webpack refuses to create the bundle since it cannot resolve e.g. require('net') which is not used through the client side api.

Suggestions on workaround?

**Comment by haihappen** [comment]
Having the same problem with [route-parser](https://www.npmjs.com/package/route-parser). Though working fine in the browser, route-parser utilises a [jison](http://zaach.github.io/jison) parser which provides a cli and is accessing node's `fs`-module therefore. Using `IgnorePlugin` to ignore `fs` modules seem to break `style-loader` and/or `css-loader`.

Any suggestions how to fix this problem?

**Comment by jhnns** [comment]
Jison is only used by [`scripts/compile_parser.js`](https://github.com/rcs/route-parser/blob/26fd2a2d7951c01cfe1653367b72533766a371cc/scripts/compile_parser.js) which isn't required anywhere afaict. So that shouldn't be a problem.

**Comment by adjavaherian** [comment]
+1, How does one simply flag a node require to be ignored?

**Comment by sokra** [comment]
https://gist.github.com/defunctzombie/4339901#ignore-a-module

**Comment by adjavaherian** [comment]
So, I've created a page loader which effectively shows webpack how to break my react components into discreet chunks based on certain react-router routes.

https://github.com/adjavaherian/webpack-react-router/blob/master/app/PageLoader.jsx

This works well, but now my server side rendering is different than client, so I'd like to be able to require.ensure at one point and then require.ignore that same module, so it doesn't get added to the require graph.  I think what I'm trying to do is different than using the ```browser : { module: false }``` method which appears to globally ignore a module when bundling.  Something like this would be great. 

```javascript
var ServerFront  = require('./pages/FrontPage'); 
/*  I would like ServerFront to be ignored, so the the ensure below, properly chunks the FrontPage 
require graph.  But notice that they are the same module.
*/

var FrontPageLoader = React.createClass({

    componentDidMount: function() {
        var that = this;
        require.ensure(['./pages/FrontPage'], function(require) {
            FrontPage = require('./pages/FrontPage');
            that.forceUpdate();
        });
    },
    render: function() {
        if (FrontPage) {
            return <FrontPage {...this.props} />;
        } else {
            return <ServerFront {...this.props} />;
        }
    }
});
```

**Comment by shama** [comment]
You can set the node built-in to be ignored by setting it to `"empty"` here in your config: http://webpack.github.io/docs/configuration.html#node
