### ISSUE TITLE
`npm test` fail.

### ISSUE THREAD

**Issue by taoqf** [webpack/webpack#5531]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
`Error: Cannot find module 'webpack/lib/Chunk'`
**If the current behavior is a bug, please provide the steps to reproduce.**

1.  `git clone git@github.com:webpack/webpack.git`
2. `npm install`
3. `npm test`

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

OS: Debian
Node.js 8.2 8.4

**Comment by sokra** [comment]
Follow the CONTRIBUTING docs
