### ISSUE TITLE
Can not use CommonsChunkPlugin  when window is not defined.

### ISSUE THREAD

**Issue by taoqf** [webpack/webpack#5532]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When `window` is not declared globally, commons.js contains `window`, https://github.com/webpack/webpack/pull/4820 seems fixed this, unfortunately, is closed.
besides, chunk.js contains `webpackJsonp ` also will cause exception.
**If the current behavior is a bug, please provide the steps to reproduce.**
It seems unlikely reproduce this bug in browser.
I use this in [Wei Xin](https://mp.weixin.qq.com).

I tried fix [this](https://github.com/webpack/webpack/pull/5530/commits/25bd2331f195efb4797f72c70df3d561ffa94d9a) but failed in tests.

**What is the expected behavior?**
use `global` replace `window` in commons.js and `global.webpackJsonp` replace `webpackJsonp` in chunk.js
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Node.js 8.4.0
webpack latest
OS: Debian

**Comment by sokra** [comment]
What is Wei Xin?

**Comment by taoqf** [comment]
@sokra I cannot describe it clearly, but I will try to:
It is somehow like [cordova](http://cordova.apache.org/) and [Electron](https://github.com/electron/electron). 
Coding in JavaScript and behavior more like native.
This is an example:
```js
//app.js
App({
	onLaunch: function () {
		// 展示本地存储能力
		var logs = wx.getStorageSync('logs') || []
		logs.unshift(Date.now())
		wx.setStorageSync('logs', logs)

		// 登录
		wx.login({
			success: res => {
				// 发送 res.code 到后台换取 openId, sessionKey, unionId
			}
		})
		// 获取用户信息
		wx.getSetting({
			success: res => {
				if (res.authSetting['scope.userInfo']) {
					// 已经授权，可以直接调用 getUserInfo 获取头像昵称，不会弹框
					wx.getUserInfo({
						success: res => {
							// 可以将 res 发送给后台解码出 unionId
							this.globalData.userInfo = res.userInfo

							// 由于 getUserInfo 是网络请求，可能会在 Page.onLoad 之后才返回
							// 所以此处加入 callback 以防止这种情况
							if (this.userInfoReadyCallback) {
								this.userInfoReadyCallback(res)
							}
						}
					})
				}
			}
		})
	},
	globalData: {
		userInfo: null
	}
})
```

**Comment by taoqf** [comment]
https://github.com/webpack/webpack/pull/5530#issuecomment-322981332

**Comment by probablyup** [comment]
It seems like a  commons chunk would not be useful for a non-browser environment. Is it beneficial to have multiple bundles for a native-ish client?

**Comment by taoqf** [comment]
It did help, if this issues is fixed. I have done my local tests.

**Comment by technicallyfeasible** [comment]
I believe this would also get me closer to a fix for my usecase. I am using dynamic splitting on a bundle that is loaded in the browser as well as node (for SSR using React). The bundle fails to load on the server because of the direct access to "window".
I would expect code splitting to support being loaded in both environments and fall back to simple "require" on node.js

**Comment by param-fk** [comment]
Any way around for this issue?

**Comment by taoqf** [comment]
This issue is fixed already. see https://github.com/webpack/webpack/pull/6200
