### ISSUE TITLE
Webpack won't replace DefinePlugin variables on some modules

### ISSUE THREAD

**Issue by buddyackerman** [webpack/webpack#5537]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
I've defined some global variables using the DefinePlugin but they don't get replaced in all modules

**If the current behavior is a bug, please provide the steps to reproduce.**

            new webpack.DefinePlugin({
                MAINBUILD: JSON.stringify(ctx.buildType === "main"),
                TESTBUILD: JSON.stringify(ctx.buildType === "test"),
                DEVBUILD: JSON.stringify(ctx.buildType === "dev")
            })

module where it doesn't work

	"use strict";

	var someUrl = DEVBUILD ? "/some/url" : "/other/url";
	var appConfig = {
		"urls": {
			"someUrl": someUrl,
		}
	};

	module.exports = appConfig;

**What is the expected behavior?**
I expect DEVBUILD to be replaced with the value from the defineplugin setup.  However I get the following error

    var someUrl = DEVBUILD ? "/some/url" : "/other/url";
                  ^
    ReferenceError: DEVBUILD is not defined

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Node.js version : 7.5.0
webpack version: 1.13.2
OS: Windows 10

**Comment by TheLarkInn** [comment]
Does this become resolved on updating to webpack@latest? We've halted development on the v1 branch unless there are security related issues.

**Comment by buddyackerman** [comment]
@TheLarkInn I can't use the latest version because we're still supporting IE8. 😦 
It does seem to work on modules that export a function but not ones that export an object (like in my example).

**Comment by sokra** [comment]
This should work fine in webpack 1 too.
