### ISSUE TITLE
Probably incrorrect letter case in filenames make bundlers duplicating modules. 

### ISSUE THREAD

**Issue by Dark-Energy** [webpack/webpack#5539]
** I want report a some like *bug* **

Probably incrorrect letter case in filenames make bundlers duplicating modules and work all library is failed. 

I faced with problem, when webpack and rollup duplicates modules.

I am working on Windows. She is not make it differece between low and up case letters in filenames. For she 'File.js' and 'file.js' are one entity. But Unix-like systems recognize they as two diffirent entities. And bundlers (webpack, rollup) also do. Let you are working on Windows, and you make two 'import' operations, in the one you write from 'File.js', in the second you write 'file.js'. Both are reffered to same file. However bunlers make two copy of this module. 

I made all filenames and statement 'import from' to low case, and problem vanished. It is truth for Webpack. I don't try with rollup yet.

Probably could make some sort of option for show warning about possibily making duplicate modules or option for ignore case in filenames, i don't know.

Sorry for bothering you, if my issue happen usesless.

**Comment by KpjComp** [comment]
You need to make sure of case,..

This is not just a webpack issue, it would also be the case of Node.js on a windows machine.   It might appear it's working, but if you say did    `require('config');` and `require('Config');`, node.js would load them twice, and in some cases this could be problematic.

For this reason, what most javascript / node.js developers do is always use lowercase, and dashes.
IOW: always avoid using `require` with any upper case characters.

> Probably could make some sort of option for show warning about possibily making duplicate modules or option for ignore case in filenames, i don't know.

Are you using the latest webpack, I'm pretty sure it already shows a warning..

**Comment by Dark-Energy** [comment]
i don't used require, i used import directive from new lang standard. Bundler simple load and copy this module, and wrap it in some like function. In result, bundler create two copy of one module with different names, which it create appending dollar sign. And system breaks. 

yes, webpack shows warning. But it message something like 'this may have problem on some operation system'. Not that thing, are i'm waiting.

**Comment by sokra** [comment]
> This is not just a webpack issue, it would also be the case of Node.js on a windows machine.

> yes, webpack shows warning.
