### ISSUE TITLE
Exports undefined when importing from downstream module.

### ISSUE THREAD

**Issue by ajmas** [webpack/webpack#5540]
**Do you want to request a *feature* or report a *bug*?**
Bug

I have asked on both Stackoverflow and and Gitter and haven't found a response.

**What is the current behavior?**

I build my ES6 upstream module, but when I included the exported functions in the downstream module they are undefined for the named exports or {} for the default export.

**If the current behavior is a bug, please provide the steps to reproduce.**

This is a project that I had put together when I first asked the question, but I ended up not using webpack to get around the issue:

https://github.com/ajmas/my-components

`npm run build` produces the file which doesn't seem to export.

**What is the expected behavior?**

The functions exported can be loaded from the downstream module.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
  - macOS X 10.12.6
  - nodejs v7.10.1
  - webpack 3.5.5

In the current problem case the webpack config is as follows:
```javascript
modules.exports = [{
    name: 'lib',
    entry: {
        app: './src/index.js'
    },
    output: {
        filename: 'lib/index.js'
    },
    devtool: 'source-map',
    externals: [/node_modules/],
    module: {
        loaders: [{
            test: /\.(scss|css)$/,
            loaders: ["style", "css", "sass"]
        }, {
            test: /\.js$/,
            loader: 'babel-loader',
            exclude: [/node_modules/],
            options: {
                presets: [
                    'babel-preset-es2015',
                    'babel-preset-react',
                    'babel-preset-stage-0',
                ].map(require.resolve),
            }
        }]
    },
    plugins: [
        new CircularDependencyPlugin({
            // exclude detection of files based on a RegExp 
            exclude: /node_modules/,
            // add errors to webpack instead of warnings 
            failOnError: true
        })
    ]
}]
```
The content of `src/index.js` is:

```javascript
export function xyz () {
    console.log('do you hear me?');
}

export default xyz;
```

and the build command in `package.json`: `webpack -p --config-name lib`

**Comment by ajmas** [comment]
Some more exploring suggests this  may be down to needing the `libraryTarget: 'umd'` property. I only noticed that by looking through other node_module dependencies that used webpack. It was wasn't evident.

Is there any reason, based on the documentation, that `umd` isn't the default that webpack uses?  For example are the any unintended side effects if it was?

**Comment by sokra** [comment]
> Is there any reason, based on the documentation, that umd isn't the default that webpack uses?

Most users use webpack to build an application. `libraryTarget` is only needed when you build a library.
