### ISSUE TITLE
Source maps: webpack serves null content from sourcesContent 

### ISSUE THREAD

**Issue by cy6erGn0m** [webpack/webpack#5542]
I want to report a *bug*

I have a source map generated so that some of sources are embedded while other are on the file system.

So it looks like this

```
.. "sources": [ "../../src/some/path/file", "some/embedded/path/file"], "sourcesContent": [ null, "embedded content of the file"  ] ...
```

However webpack doesn't pick up source file from the file system and only embedded content is available. In devconsole I can see for `webpack:///../../src/some/path/file` the following

```
null

// WEBPACK FOOTER //
// ../../src/some/path/file
```

If I remove sourcesContent then it serves it perfectly but of source embedded content disappears. 

The other workaround is to reorder sources and shrink sourcesContent like this

```
.. "sources": [ "some/embedded/path/file", "../../src/some/path/file" ], "sourcesContent": [ "embedded content of the file"  ] ...
```

However in this case number of "sources" entries and "sourcesContent" entries are not the same that doesn't look safe.

**What is the expected behavior?**

According to the specification

>  “null” may be used if some original sources should be retrieved by name.

However webpack always serves null as text this is why I believe it is a bug as I expected that webpack will serve embedded content if available and serve from file system when null (as per spec).

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

webpack 3.5.5

**Comment by sokra** [comment]
Yep looks like a bug. You can send a PR.

**Comment by axelg12** [comment]
I believe PR GH-5896 fixed the issue so this issue can be safely closed.

**Comment by buoyantair** [comment]
@TheLarkInn ^

**Comment by evilebottnawi** [comment]
Let's close this issue, if somebody face this issue feel free create new issue. Thanks!
