### ISSUE TITLE
CommonsChunkPlugin not working with electron main process

### ISSUE THREAD

**Issue by dland512** [webpack/webpack#5545]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Using the `CommonsChunkPlugin` with the main process of an `electron` app results in the app freezing on start up. The electron icon appears in the doc but the app's main window never shows up.

I have another webpack config for electron's renderer process and using `CommonsChunkPlugin` with that works fine.

**If the current behavior is a bug, please provide the steps to reproduce.**

Here is a repo with a [simple app](https://github.com/dland512/electron-commonschunkplugin-issue) that reproduces the issue and describes things in more detail

**What is the expected behavior?**

The `CommonsChunkPlugin` should work with the electron main process.

Environment info:
```
MacOS:    10.12.6
node:     v6.11.0
npm:      3.10.10
electron: v1.6.12
wepback2: 3.5.5
```

**Comment by sokra** [comment]
`CommonsChunkPlugin` is only supported in web enviroments (support for JSONP).

It's possible to expand this support, but it's currently not planned.
