### ISSUE TITLE
[DefinePlugin] Be able to define globals by entry points ?

### ISSUE THREAD

**Issue by jbeaudoin11** [webpack/webpack#5546]
**Do you want to request a *feature* or report a *bug*?**
feature

**If this is a feature request, what is motivation or use case for changing the behavior?**
My main goal is to create a bundle per role on my app. I discovered the DefinePlugin, and looks pretty cool but it would be better if we could define globals by entry points. This way i could have multiple entry on the same file but something like :
```
/* webpack config */
entry: {
    "user": "path_to_client_index",
    "admin": "path_to_client_index",
}

new webpack.DefinePlugin({
    entry: {
        "user" : {
            __ROLE__: "'" + "user" + "'",
        },
        "admin" : {
            __ROLE__: "'" + "admin" + "'",
        },
    }
})

/* entry index.js */
import route from "routes/" + __ROLE__;
```

**Comment by AnNOtis** [comment]
Maybe "[exporting multiple configurations](https://webpack.js.org/configuration/configuration-types/#exporting-multiple-configurations)" is what you want?

You can configure it like this:

```js
var roles = ["admin", "user"]
module.exports = roles.map(function (role) {
  return {
    entry: "path_to_client_index",
    plugins: [
      new webpack.DefinePlugin({
        __ROLE__: JSON.stringify(role)
      })
    ]
  }
})
```

**Comment by jbeaudoin11** [comment]
Thanks @AnNOtis, this is the solution proposed on Gitter. I'm gonna give it a try.

**Comment by jscinoz** [comment]
The trade off with the multiple-configurations solution is that you'll no longer be able to extract common code with CommonsChunkPlugin. It would still be useful if DefinePlugin supported a `chunks` option like some other plugins do, to allow for per-entry constants.

**Comment by jbeaudoin11** [comment]
But it would be supper complex with the use of UglifyPlugin. Like in my code import doesn't mean commun code after Uglify did his thing.. The output changed base on those defined variables.

But i'm curious about vendors communs chunks, since in most cases this will stay commun. Maybe there is still something to do with that. I just don't bother right now  to explore more, maybe in some weeks i'll invest more time on this.

(a bit out of the subject)
I'm also curious about what you guys think of splitting the client app on a role base ? I mean.. There is no need for the average user to download what an admin uses so i think it help a bit with security since they "don't have the functionality into their app" (they can still hit the api but thats backend)

**Comment by e-e-e** [comment]
👍 to this feature request. Is there any other way to get custom variables into individual entries?

**Comment by blizzardzheng** [comment]
Is there any other way to get custom variables into individual entries? i do not wanner to create mulitiple configs, just the define plugin

**Comment by johnnysprinkles** [comment]
+1 to this. When building "multipage" isomorphic React apps where you have one clientside bundle per page, it would be handle to do it all in one configuration with entry points.
