### ISSUE TITLE
SourceMapDevToolPlugin is working wierdly. It doesn't take over the devtool job.

### ISSUE THREAD

**Issue by yincu** [webpack/webpack#5547]
**Do you want to request a *feature* or report a *bug*?**
It's a bug.

**What is the current behavior?**
When I set the  devtool: 'source-map' and  apply the SourceMapDevToolPlugin , the SourceMapDevToolPlugin doesn't take over the devtool options and produce two different source maps.
**If the current behavior is a bug, please provide the steps to reproduce.**
This is the sample. It's very simple.
https://github.com/yincu/srcMapPlugin.git
steps: npm install => npm run cp => and two source map directories are  produced,  /dist/srcMap and /dist/srcMapPlugin . 
After that, if you browser the dist/html/index.html page. You no longer get the source map. It's not working.
However, if you delete the "**new webpack.SourceMapDevToolPlugin( { ... } )** " configuration.  The source map is correctly working good! 
How can the devtool options and the SourceMapDevToolPlugin options in webpack.config.js  both produce the source maps separately and result in a broken source map ?

https://github.com/yincu/srcMapPlugin.git

**What is the expected behavior?**
I expect the SourceMapDevToolPlugin  overwrites some options about the source map and produce only one source map per js file.
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
node: v6.11.0
webpack:  2.7.0+
Operating System: win10 64bit

**Comment by sokra** [comment]
Use either `devtool` or `SourceMapDevToolPlugin`. Don't use both.

**Comment by yincu** [comment]
@sokra I searched in the google. And I did delete   `devtool` and use `SourceMapDevToolPlugin`, but the webpack  didn't produce the js source map,  however it produced the css source maps.

I check this right now  and I'm sure the js source map files are  NOT generated except the css source maps.

**Comment by yincu** [comment]
If I deleted the `devtool`, how could I  tell the webpack which type of source map I need it to generate.
It seems that the `SourceMapDevToolPlugin`  has no option which  is  concerned  about the source map type.
I think it is the `devtool` option's missing that results in NOT generating the js source maps.
