### ISSUE TITLE
SourceMapDevToolPlugin may support the absolute sourceMappingURL

### ISSUE THREAD

**Issue by yincu** [webpack/webpack#5554]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
The source maps comments are  always attached like this  `//# sourceMappingURL=../srcMap/js/test1.js.map`  with a **relative** url.  It will be very usefull if  supports the absolute url.
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**
It will be very usefull  if it supports the absolute url. 
The use case : 
The comment is  like this `//# sourceMappingURL=http://10.30.1.11/srcMap/js/test1.js.map`,  and we could serve the source map in a server which can only be accessed by developers.
With this,  developers can reproduce the bugs in `production` environment and access the source map with a VPN. Meanwhile, the others will not.

I looked into the  `SourceMapDevToolPlugin.js` file.  It's easy to modify the code to support the feature.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by sokra** [comment]
There is an option on the `SourceMapDevToolPlugin` for this.

**Comment by yincu** [comment]
@sokra  SourceMapDevToolPlugin‘s   `append` option is not working. Still has the `..` relative url if I put all the source maps in a separate directory.
Can't you just try ?  And are you sure?

**Comment by sokra** [comment]
hmm ok... You can send a PR allowing to configure the context directory for the url:

``` js
SourceMapDevToolPlugin({
  append: "//# sourceMappingURL=http://10.30.1.11/[url]",
  context: path.resolve(__dirname, "build/srcMap")
})
```
