### ISSUE TITLE
Performance issues with export ... from ... syntax + unexpected parsed module

### ISSUE THREAD

**Issue by Zephir77167** [webpack/webpack#5556]
**Do you want to request a *feature* or report a *bug*?**

A bug

**What is the current behavior?**

I currently refactored my codebase, from using:

```js
import A from 'src/common/a/js/A';
import B from 'src/common/b/js/B';
etc
```
to
```js
import { A, B } from 'src/common';
```
with a file `src/common/index.js`:
```js
export A from './a/js/A';
export B from './b/js/B';
```

Before this refactoring, a build would take 130s to complete. Now, it takes 330s. 400 files have been changed, and I have tested with the exact same version of each of my node_modules.

I also noticed that if there is an error in a file exported in `index.js`, but this file is not imported, it will break the build anyway. I have set up a repository to reproduce the issue.

**If the current behavior is a bug, please provide the steps to reproduce.**

To reproduce the "breaking the build" bug, which might be a part of the performance issue: https://github.com/Zephir77167/webpack-export-syntax-bug

As for the performance issue, I would be happy, if necessary, to create a repository with hundreds of linked components with the two methods for comparison. Please tell the word if this would be of any help (not sure so I would like your feedback first).

**What is the expected behavior?**

I wouldn't expect a performance difference between the two methods, and also wouldn't expect the build to break on a component which isn't imported anywhere, even if exported in a file which is imported.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

OS: Windows 10 64 bits
Node: 8.2.1
Webpack: 3.5.5 (latest)

Thanks a lot in advance!

PS: here is my `.babelrc` (available on the repo):
```js
{
  "plugins": [
    "transform-decorators-legacy",
    "transform-object-rest-spread"
  ],
  "presets": [
    ["es2015", { "modules": false }],
    "react",
    "stage-0"
  ],
  "env": {
    "test": {
      "plugins": ["transform-es2015-modules-commonjs"]
    }
  }
}
```

**Comment by sokra** [comment]
`import { A, B } from 'src/common'` includes `index.js` in the build. It also includes every module referenced by this file. You refactoring could lead to the inclusion of more modules. This probably lead to the performance difference. It's also expected that an error in `index.js` breaks the build.

**Comment by Zephir77167** [comment]
But what if every module referenced in `index.js` was already referenced before the refactoring? Shouldn't it be the same? Is there another syntax to achieve this kind of sugar on imports, or is this just a no-go from your point of view (and, of course, the perfs)?
