### ISSUE TITLE
Module caches aren't updated sometimes when using require.context

### ISSUE THREAD

**Issue by diurnalist** [webpack/webpack#556]
There seems to be an issue where, if you're using `require.context` to pull in a glob of files, and are also using caching and re-running the compilation, you get some weird behavior. It takes two compilations for the changes from a module to propagate to the output bundle.

I've created a little reproduction branch on my fork of webpack: https://github.com/diurnalist/webpack/tree/bug/require-context-caching

**Comment by philipkocanda** [comment]
Ran into this as well. Using webpack with gulp-watch:

```javascript
gulp.task("webpack:watch", function() {
  watch(["lib/**/*"], function() {
    devCompiler.purgeInputFileSystem();
    gulp.start("webpack:build");
  });
});
```

Makes more sense for webpack to make that call on each run..

**Comment by KarolAltamirano** [comment]
I have ran into this issue as well with gulp watch. Would be good to solve it by calling 'purgeInputFileSystem' internally on each run or maybe at least add 'compiler.purgeInputFileSystem();' to example gulp file [here](https://github.com/webpack/webpack-with-common-libs/blob/master/gulpfile.js)

**Comment by redmagic** [comment]
`Maybe it's useful to call purgeInputFileSystem on each run call.` Is it possible to do that from within a webpack.config.js?

**Comment by redmagic** [comment]
`compiler.plugin('invalid', function(stats) {
                console.log('Purging');
                this.purgeInputFileSystem();
            });`

Is not convincing the webpack dev server that something has actually changed in one of the files required by require.context..

`[WDS] nothing changed`
