### ISSUE TITLE
'done' event called multiple times when in watch mode, even when file doesn't change

### ISSUE THREAD

**Issue by fresheneesz** [webpack/webpack#5564]
Reporting a bug.

**What is the current behavior?**

The callback is called multiple times when in watch mode, even when the file is not changed.

**If the current behavior is a bug, please provide the steps to reproduce.**

Run the following code:

```
var fs = require('fs')
var webpack = require('webpack')

fs.writeFileSync(__dirname+'/bugOutput.js', "exports.x = 2")
webpack({
    context: __dirname,
    entry: "./bugOutput",
    output: {
        path: __dirname,
        filename: 'bugOutput.bundle.js',
        libraryTarget: 'umd'
    },
    watch: true
}, function(err, stats) {
    if(err) console.log("error: "+err)
    else    console.log("no error")

    var jsonStats = stats.toJson({errorDetails: false})
    console.log(jsonStats.warnings)
    // console.log(jsonStats)
})
```

**What is the expected behavior?**

The callback should be called once.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Node.js v7.10.0, webpack version 3.5.5, Windows 8.1

**Comment by sokra** [comment]
This is expected. You can change `stats.hash` to filter "real" changes.

**Comment by fresheneesz** [comment]
@sokra Ok. What's the reason this is expected? Is this a quirk of how the file system reports changes to webpack?

**Comment by sokra** [comment]
Timestamps on filesystem can have up to 2 seconds accuracy. We can't be sure from mtime if the file was changed. In cases when we are unsure we thread this as change. This usually doesn't affect the output files as they are only written when changing.

**Comment by fresheneesz** [comment]
Ok. It does seem to be more than 2 seconds. In fact, it seems like its more than 8 seconds:

```
var fs = require('fs')
var webpack = require('webpack')

fs.writeFileSync(__dirname+'/bugOutput.js', "exports.x = 2")

setTimeout(function() {
    webpack({
        context: __dirname,
        entry: "./bugOutput",
        output: {
            path: __dirname,
            filename: 'bugOutput.bundle.js',
            libraryTarget: 'umd'
        },
        watch: true
    }, function(err, stats) {
        if(err) console.log("error: "+err)
        else    console.log("no error")

        var jsonStats = stats.toJson({errorDetails: false})
        console.log(jsonStats.warnings)
        // console.log(jsonStats)
    })
},8000)
```

But with 20 seconds I do get one single output. @sokra Would it makes sense to have webpack automatically filter by `stats.hash` so that the call back isn't called multiple times like this?
