### ISSUE TITLE
CommonsChunkPlugin does not work as expected with worker-loader

### ISSUE THREAD

**Issue by jnields** [webpack/webpack#5567]
**Do you want to request a *feature* or report a *bug*?**
Request a feature

**What is the current behavior?**
When importing modules in a worker, all module code is included, whether or not other chunks define the module elsewhere, and whether or not CommonsChunkPlugin is used.

**If the current behavior is a bug, please provide the steps to reproduce.**
There is an example of the current behavior at [this repo](https://github.com/jnields/worker-loader-example).

**What is the expected behavior?**
When using CommonsChunkPlugin, chunks/modules should be imported via importScripts where possible.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Importing other chunks via importScripts from workers in order to access modules will drastically reduce their size and load time.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

This issue is for Webpack 2.x.x with worker-loader 0.8.1

**Comment by sokra** [comment]
`CommonsChunkPlugin` is only supported in web enviroments (support for JSONP).

It's possible to expand this support, but it's currently not planned.
