### ISSUE TITLE
BUG: Dynamic import with TS 2.4 and awesome-typescript-loader not working

### ISSUE THREAD

**Issue by kukjevov** [webpack/webpack#5568]
**Do you want to request a *feature* or report a *bug*?** 
BUG

**What is the current behavior?**
According this article https://dev.to/kayis/dynamic-imports-with-webpack-2 dynamic import  with dynamic url should work since webpack 2. 

When i write application in typescript 2.4 using new dynamic import features, it is working when i use *fixed* import url, but if i use *dynamic* import url with concatenation it fails with following error. 

>ERROR in ./index.ts
>Module parse failed: D:\www\dynamicImport\node_modules\awesome-typescript-loader\dist\entry.js!D:\www\dynamicImport\index.ts Unexpected token (62:15)
>You may need an appropriate loader to handle this file type.
>|     };
>|     Test.prototype.loadDynamic = function () {
>|         (import)("./dynamicFolder/" + dyn).then(function (Dynamic) {
>|             var dynamicObj = new Dynamic();
>|             dynamicObj.show();
> @ multi ./index.ts

**If the current behavior is a bug, please provide the steps to reproduce.**
https://github.com/kukjevov/dynamic-import

npm install
npm run build

**What is the expected behavior?**

It should work as written in article mentioned above, generate chunk for all found modules on that path.

**If this is a feature request, what is motivation or use case for changing the behavior?**

I am not sure if this is problem of webpack or awesome-typescript-loader, but it looks like that problem is maybe here. If it is not supported i would like to make it feature request. :)

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

NodeJs 8.1.2
FF 55
Webpack 3.5.5
Windows 10 15063

**Comment by kukjevov** [comment]
Well i was playing with it a little longer and i found out, that this is not definitely problem of awesome-typescript-loader.

If you have in typescript this code
```typescript
import('./dynamicFolder/dynamic').then(all => console.log(all));
```
it will generate this javascript
```javascript
import('./dynamicFolder/dynamic').then(function (all) { return console.log(all); });
```

but if you make it more dynamic by doing this
```typescript
const dyn = "dynamic";
import(`./dynamicFolder/${dyn}`).then(all => console.log(all));
```

it will generate this javascript
```javascript
(import)("./dynamicFolder/" + dyn).then(function (all) { return console.log(all); });
```

which is really weird, because if i remove `()` around `import` it is working in webpack. Question here is, it is request for `webpack` or `typescript`? Well i can make "stupid" loader which will remove parentheses and it will make it working. But this is not good solution it is more like workaround.

Any suggestions?

**Comment by sokra** [comment]
`(import)("./dynamicFolder/" + dyn)` is invalid syntax, because `import` can't be used as expression.

So it's more an typescript issue.
