### ISSUE TITLE
Source maps will not  be generated  when  run the " webpack -p" command.

### ISSUE THREAD

**Issue by yincu** [webpack/webpack#5569]
**Do you want to request a *feature* or report a *bug*?**

> Bug

**What is the current behavior?**
With nothing to be changed, run the command `webpack ` or `webpack -p`，I get source maps only when I execute the `webpack `command. The `webpack -p` will not generate the source map.
**If the current behavior is a bug, please provide the steps to reproduce.**
npm install => npm run cd => NO source maps.
npm install => npm run cc => Yes.
The webpack.config.js:
> ......
new webpack.SourceMapDevToolPlugin({
             filename: 'srcMapPlugin/[file].map',
             include: ['js/test1.js'],
             append: '\n//#sourceMappingURL=http://192.168.32.5:8080/[url]',
             moduleFilenameTemplate:'[absolute-resource-path]',
         }),
devtool: false,
......
>
package.json:

> "scripts": {
>     "test": "echo \"Error: no test specified\" && exit 1",
>     "v": "webpack -version",
>     "cc": ".\\node_modules\\.bin\\webpack   ",
>     "cd": ".\\node_modules\\.bin\\webpack   -p",
>     "cp": "cross-env NODE_ENV=production PLATFORM=web .\\node_modules\\.bin\\webpack --optimize-minimize"
>   },

## **The sample is:**
https://github.com/yincu/srcMapPlugin.git

**What is the expected behavior?**
Source maps will be generated.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by sokra** [comment]
When using the `SourceMapDevToolPlugin` you have to use the `UglifyJsPlugin` with `sourceMap: true` manually.

**Comment by yincu** [comment]
@sokra 
## Some more configurations in `webpack.config.js`:

```
 new webpack.optimize.UglifyJsPlugin({
            test: /\.js$/,
            sourceMap: true,
            uglifyOptions: {
                ie8: false,
                mangle: true,
                output: {
                    comments: false,
                    beautify: false,
                },
                compress: true,
                warnings: false
            },
            parallel: {
                cache: true,
            }
        }),
```
Furthermore, the command `webpack` work right with the `UglifyJsPlugin` and `SourceMapDevToolPlugin`  . But, with the same configurations, `webpack -p`   NOT.

## You can see in the sample project.
https://github.com/yincu/srcMapPlugin.git

**Comment by yincu** [comment]
@sokra 
### The `webpack.config.js`
![1](https://user-images.githubusercontent.com/31179226/29759704-8a09aaca-8bf0-11e7-8c6a-a423d76a9b7b.png)

### In the `webpack.js`  file, I added a log to trace the call and the options.
![image](https://user-images.githubusercontent.com/31179226/29759763-f919811a-8bf0-11e7-94e0-c6c590a694aa.png)

### Then  I run this : `npm run cc`  , which equaled to `webpack`
![image](https://user-images.githubusercontent.com/31179226/29759847-b18cd76a-8bf1-11e7-9552-42f1ea157e29.png)

### And at last, with the same configurations, I run the command `npm run cd`, which eaquled to `webpack   --optimize-minimize`,  I got two more  plugins:

![image](https://user-images.githubusercontent.com/31179226/29759941-82ae162e-8bf2-11e7-956a-48308ba2b8c8.png)

### Now, there were two UglifyJsPlugin and the last one's options was  like this.
![image](https://user-images.githubusercontent.com/31179226/29760030-26c2a46e-8bf3-11e7-88a3-743820121ef2.png)

### It turned off the source map.  And resulted in  none source maps. However, I  configure it to be true.

**Comment by sokra** [comment]
The `-p` sets `UglifyJsPlugin({ source: options.devtool.contains("source-map") })`. This is way doesn't work when using the `SourceMapDevToolPlugin`. Pass the UglifyJsPlugin manually.

**Comment by yincu** [comment]
How to `Pass the UglifyJsPlugin manually`?
You mean I can never get the uglified js files and sourceMaps at the same time  for  PRODUCTION environment?  
But sometimes we need reproduce a bug in the production environment with source maps which can only be accessed by developers?

**Comment by yincu** [comment]
@sokra  Don't you think  `SourceMapDevToolPlugin` and `UglifyJsPlugin` can not work together is  a bug ?

And more, `SourceMapDevToolPlugin`  and `devtool: 'souce-map'` can not work together is a b
ug? If not, how could I configure which type of source-map  I want , Such as `nosources-source-map` and `hidden-source-map` in  production ?

**Comment by ganapativs** [comment]
You can pass options to configure `SourceMapDevToolPlugin`  for `nosources-source-map` or `hidden-source-map`.
```js
new webpack.SourceMapDevToolPlugin({
            test: [/\.js$/, /\.jsx$/],
            filename: '[file].map',
            append: false,
            noSources: true, // Sourcemap without source
            hidden: true
        })
```

**Comment by ooflorent** [comment]
This issue is not longer relevant with webpack 4. I'm closing it for this reason. As sokra said, source map support depends on `devtool` value. If you still encounter this issue, please open a new issue on `webpack-cli` repository.
