### ISSUE TITLE
Webpack Prefers AMD?

### ISSUE THREAD

**Issue by julmot** [webpack/webpack#5573]
**Do you want to request a *feature* or report a *bug*?** Bug

When it encounters an if check [like this](https://github.com/julmot/datatables.mark.js/blob/045ce45653414f81240dc68fe84ec8a2752ad97f/build/templates/datatables.mark.js#L13-L24) I'd expect it to use the first positive if statement and continue. In this case CommonJS (`typeof module === 'object' && module.exports` would be true). I couldn't find any other information in the docs.

_Example in case the above mentioned code gets lost in the meantime:_
```javascript
if (typeof module === 'object' && module.exports) {
    const jquery = require('jquery');
    require('datatables.net');
    require('mark.js');
    factory(window, document, jquery);
} else if (typeof define === 'function' && define.amd) {
    define(['jquery', 'datatables.net', 'mark.js'], jQuery => {
      return factory(window, document, jQuery);
    });
} else {
    factory(window, document, jQuery);
}
```

**What is the current behavior?**

It ignores the first CommonJS if statement (`typeof module === 'object' && module.exports`) when an AMD if statement is available and continues with the AMD if statement (`typeof define === 'function' && define.amd`). If I remove the AMD statement it'll use the CommonJS statement. So it accepts the above named `module.exports` statement, but only if no AMD statement is available. I've tested this with a module inside `node_modules`.

**What is the expected behavior?**

It should use the first positive statement, regardless of whether it's CommonJS or AMD.

Interestingly, if you use `typeof exports === 'object'` instead of `typeof module === 'object' && module.exports` it'll use the CommonJS statement correctly (taken from [this comment](https://github.com/webpack/webpack/issues/919#issuecomment-86735961) by @sokra).

Why do I bother what's used at all? Because a plugin of mine is called `mark.js` (note the .js extension) which RequireJS doesn't support as dependency path name. So I need to load `mark.js` in case of CommonJS environment and `markjs` in case of AMD environments, as you can see in [this example](https://github.com/julmot/datatables.mark.js/blob/90f42a795fc44c090a21ae2f8ad786ead1f7939b/build/templates/datatables.mark.js#L13-L24).

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Webpack: v3.5.5
Node.js: v3.5.5
OS: Windows 10

**Comment by sokra** [comment]
> It should use the first positive statement, regardless of whether it's CommonJS or AMD.

This should work this way.

Could you paste the generated code?

**Comment by julmot** [comment]
@sokra Thanks for your reply. Sure.

**Input**:

```javascript
  if (typeof module === 'object' && module.exports) {
    var jquery = require('jquery');
    require('datatables.net');
    require('mark.js/dist/jquery.mark.js');
    module.exports = factory(window, document, jquery);
  } else if (typeof define === 'function' && define.amd) {
    define(['jquery', 'datatables.net', 'markjs'], function (jQuery) {
      return factory(window, document, jQuery);
    });
  } else {
    factory(window, document, jQuery);
  }
```

**Output**:

```javascript
  if (typeof module === 'object' && module.exports) {
    var jquery = __webpack_require__(1);
    __webpack_require__(3);
    __webpack_require__(52);
    module.exports = factory(window, document, jquery);
  } else if (true) {
    !(__WEBPACK_AMD_DEFINE_ARRAY__ = [__webpack_require__(1), __webpack_require__(3), !(function webpackMissingModule() { var e = new Error("Cannot find module \"markjs\""); e.code = 'MODULE_NOT_FOUND'; throw e; }())], __WEBPACK_AMD_DEFINE_RESULT__ = function (jQuery) {
      return factory(window, document, jQuery);
    }.apply(exports, __WEBPACK_AMD_DEFINE_ARRAY__),
				__WEBPACK_AMD_DEFINE_RESULT__ !== undefined && (module.exports = __WEBPACK_AMD_DEFINE_RESULT__));
  } else {
    factory(window, document, jQuery);
  }
```

**And the corresponding compiling error**:

```bash
 Module not found: Error: Can't resolve 'markjs'
```

=> It should not go into this `else if (typeof define === 'function' && define.amd) {` at all, since the first statement should be positive.

**Comment by julmot** [comment]
The issue isn't solved.

**Comment by montogeek** [comment]
Related #6525

**Comment by julmot** [comment]
Don't close
