### ISSUE TITLE
Inconsistent Path Resolving For Entry Module

### ISSUE THREAD

**Issue by dodekeract** [webpack/webpack#5576]
## :bug: Inconsistent Path Resolving For Entry Module

**Webpack version:** 2.7.0
**Language:** all
**OS:** Ubuntu 16.04, macOS 10.12.6
**Type:** Bug Report
#### When It Works:
- `example.js` and `example/` exist
- `webpack example bundle.js`
- :arrow_right: WebPack compiles
#### When It Doesn't Work Because Of Inconsistencies
- `example.js` exists, but **there is no `example/` folder**
- `webpack example bundle.js`
- :arrow_right: WebPack throws this error:

`ERROR in Entry module not found: Error: Cannot resolve module 'example' in /path/this/test/was/launched/in`
### Expected behavior:

a) WebPack correctly resolves the path and starts compiling.
b) WebPack throws an error in both cases and doesn't compile anything
### Simple Steps To Reproduce
1. place this `package.json` in an empty folder

``` json
{
    "scripts": {
        "a": "mkdir a && touch a.js && webpack a bundle-a.js",
        "b": "touch b.js && webpack b bundle-b.js"
    },
    "dependencies": {
        "webpack": "^2.7.0"
    }
}
```

2, `npm i`
3. `npm run a`
4. `npm run b`

---

## Meta

Original issue: #2656, was closed due to inactivity, but it's still relevant.

**Comment by sokra** [comment]
> WebPack throws an error in both cases and doesn't compile anything

This would be the correct behavior. webpack rewrites `example` to `./example` when passes as CLI option. To solve this problem rewrite it to `./example/` for folders.

Send a PR

**Comment by gyandeeps** [comment]
I was planning to work on this, any pointer on where should I look to fix this. Thanks

**Comment by sokra** [comment]
https://github.com/webpack/webpack/blob/master/bin/convert-argv.js#L538-L540
