### ISSUE TITLE
Show bundle gzip size

### ISSUE THREAD

**Issue by egoroof** [webpack/webpack#5577]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

In the output info it would be nice to see not only bundle size but also gzip size.

**If this is a feature request, what is motivation or use case for changing the behavior?**

Gzip is a standard compression method in the web for javascript. It's important to know gzip size as it has real value for network throughput.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Node has `zlib` module which can gzip bundles for this goal..

**Comment by sokra** [comment]
You can use the [compression-webpack-plugin](https://github.com/webpack-contrib/compression-webpack-plugin).

Always calculating gzip sizes is pretty expensive.
