### ISSUE TITLE
Tree shaking for JSON imported variables [feature request]

### ISSUE THREAD

**Issue by damianobarbati** [webpack/webpack#5578]
Code sample:
```
import { name, version } from './package.json';
```
Right now final bundle will hold full package.json object both in dev and prod mode (dependencies, scripts and so on).
Webpack could transpile the statement into ES imports and tree shake unused vars just as it does for javascript.

Why not implementing this with an additional plugin?
Since one of webpack goals is to reduce bundle size I don't see why not implementing this as a core feature 🤔.

**Comment by graingert** [comment]
@sokra what's the difference between https://github.com/webpack/webpack/milestone/15 and https://github.com/webpack/webpack/milestone/17 ?

**Comment by sokra** [comment]
4 -> before v4 release
4.x -> after v4 release

**Comment by sokra** [comment]
This is done
