### ISSUE TITLE
WebpackOptionsValidationError, Unable to build

### ISSUE THREAD

**Issue by aslam** [webpack/webpack#5579]
**Do you want to request a *feature* or report a *bug*?**
I think so, I am using the latest version of webpack 3.5.5.

**What is the current behavior?**
The command `nuxt build` fails throwing an error `WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.` 

```
nuxt:build Building... +0ms
[AXIOS] Base URL: https://now-staging.hl.com/ , Browser: https://now-staging.hl.com/
  nuxt:build App root: /Users/aslam/Work/hl-student-web +0ms
  nuxt:build Generating /Users/aslam/Work/hl-student-web/.nuxt files... +0ms
  nuxt:build Generating files... +5ms
  nuxt:build Generating routes... +17ms
  nuxt:build Building files... +26ms
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module.rules[2].use should be one of these:
   non-empty string | function | object { loader?, options?, query? } | function | [non-empty string | function | object { loader?, options?, query? }]
   Details:
    * configuration.module.rules[2].use should be a string.
    * configuration.module.rules[2].use should be an instance of function.
    * configuration.module.rules[2].use should be an object.
    * configuration.module.rules[2].use should be one of these:
```
Full stack trace: https://gist.github.com/aslam/b1e4bfb4a8c07ce158dd44ccaafdaea1

**If the current behavior is a bug, please provide the steps to reproduce.**

I am using `nuxtjs` and trying to put this app on Heroku. I can't find anything misplaced with `nuxtjs` webpack config: https://github.com/nuxt/nuxt.js/blob/dev/lib/builder/webpack/base.config.js

My `package.json` looks like this: https://gist.github.com/aslam/d14bf1efdfcec8a1dcbcce32ab3fd5d9

and `nuxt.config.js`: https://gist.github.com/aslam/35302868dbc9ab75ad6deae7e89f53cf

**What is the expected behavior?**
The build works locally. I have specified the node and npm versions to use in package.json so that the Heroku box also use the same versions as I am.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Not a feature request.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

```
"node": "6.11.0",
"npm": "3.10.10",
"yarn": "0.27.5"
```

**Comment by sokra** [comment]
Read the error message.

`configuration.module.rules[2].use[2].options` is not an object.

The configuration is invalid.
