### ISSUE TITLE
Require module every time some other module is required

### ISSUE THREAD

**Issue by unindented** [webpack/webpack#558]
How can I tell webpack to automatically do:

``` js
require('es5-shim/es5-shim');
require('es5-shim/es5-sham');
```

Every time I `require('react')`?

I have multiple entry points in the same project, and I would want to avoid pasting the requires everywhere.

Also, my tests are running on PhantomJS 1.9, which doesn't implement `Function.bind`, so I'd also benefit from automatically requiring the shims there...

**Comment by flyher** [comment]
@sokra 
Thank you for your answer!
