### ISSUE TITLE
webpack require.context will not throw error on failure

### ISSUE THREAD

**Issue by pwang2** [webpack/webpack#5580]
**Do you want to request a *feature* or report a *bug*?**
> Bug report

**What is the current behavior?**
> `require.context` will never fail webpack build

**If the current behavior is a bug, please provide the steps to reproduce.**
> see https://github.com/pwang2/webpack-require-context-swallow-exit-code

**What is the expected behavior?**
> build error(not warning) should be thrown more aggressively and give correct exit code

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Node 6.11.2 | Webpack 3.5.5 | OSX

**Comment by pwang2** [comment]
any followup/comments on this?

**Comment by pwang2** [comment]
seems a year old question:  https://stackoverflow.com/questions/34431015/webpack-babel-karma-does-not-complain-if-test-files-are-invalid

**Comment by pwang2** [comment]
close it as it seems a dup of https://github.com/webpack-contrib/karma-webpack/issues/49

**Comment by yushih** [comment]
Still an issue as of today. Please re-open. Thanks.
