### ISSUE TITLE
HMR multi-parent bug

### ISSUE THREAD

**Issue by AndersDJohnson** [webpack/webpack#5584]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

There seems to be an issue with the Hot Module Replacement feature when the hot replaced module exists in two different dependency trees and only one accepts the hot replacement.

The logic in the `HotModuleReplacementPlugin` seems to walk up the dependency tree of an updated module, but stops on any branch when it hits the main entry file and hasn't yet found an ancestor accepting the update, or hits a declining ancestor, regardless of whether there are other branches pending walk that could lead to other ancestors that might accept the update.

For an example project that reproduces the error, see [AndersDJohnson/webpack-hmr-multi-parent-bug](https://github.com/AndersDJohnson/webpack-hmr-multi-parent-bug).

**If the current behavior is a bug, please provide the steps to reproduce.**

See above.

**What is the expected behavior?**

HMR should work for modules with multiple parents.

**If this is a feature request, what is motivation or use case for changing the behavior?**

Complex applications may require some files from multiple places and want to implement hot reloading for these.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

browser: Google Chrome 60.0.3112.113 (Official Build) (64-bit)
Node.js: v8.4.0
webpack: 3.5.5
OS: macOS Sierra 10.12.4 (16E195)

**Comment by sokra** [comment]
If there is any unaccepted way from a module to the entry points it's not possible to replace/update this module.

Replacing a module in only module but not in another would lead to a inconsistent graph.

**Comment by AndersDJohnson** [comment]
@sokra Technically it could be inconsistent, yes. But there is a use case in our application where we can be guaranteed only one ancestor needs to accept the update and the application will remain consistent, since the other ancestor only runs once at app startup and does not register any callbacks to be run later that depend transitively or otherwise on the updated modules in question.

It's far less trivial for us to implement accepting the updates in both places just to support the fact that `HotModuleReplacementPlugin` makes no guarantees that it will hit one or the other first.

I suspect others working on complex applications may run into this as well.

If nothing else, should we consider making the warning logged more clear? It was difficult to figure out why HMR was rejecting my updates until tweaking the source code to realize how the tree climb is short-circuited at the end of any single branch.

**Comment by sokra** [comment]
The warning displays the complete chain: `Ignored an update to unaccepted module 92 -> 20 -> 94 -> 90 -> 38`. You can use the `NamedModulesPlugin` to show names instead of numbers.

But yeah more description is always great, so send a PR.

**Comment by sibelius** [comment]
`NamedModulesPlugin` works on webpack 4?

**Comment by sibelius** [comment]
use this plugin https://github.com/shellscape/webpack-plugin-serve/releases/tag/v0.2.0 to have HMR for multicompiler

**Comment by evilebottnawi** [comment]
bump

**Comment by evilebottnawi** [comment]
bump

**Comment by sokra** [comment]
There is `ignoreUnaccepted: true`, which fixes that e. g. when using `hot-only`
