### ISSUE TITLE
`module.hot.accept(..., () => ...)` is never called

### ISSUE THREAD

**Issue by leidegre** [webpack/webpack#5586]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

The following modules couldn't be hot updated... the only thing that appears to work is if I list no deps, i.e. `module.hot.accept()` but that breaks rendering in my case, can't just rerun the file.

I have dep chain like this.

main -> requires/imports -> routes
routes -> requires/imports -> pages/index
pages/index -> requires/imports -> pages/Home

Home is changed (React and hot loader is used):

In main there's a `module.hot.accept('./routes', () => ...)`

However, get warning `The following modules couldn't be hot updated`

And it's referring to `pages/Home` but it should have been handled through `routes` because that's how it arrived in `main`...

**If the current behavior is a bug, please provide the steps to reproduce.**

Not generally reproducible.

**What is the expected behavior?**

That `module.hot.accept` get's called and that the module is hot updated.

**If this is a feature request, what is motivation or use case for changing the behavior?**

Countless hours wasted here trying to get it to work without any guide on how to improve the situation. I would like to put together a guide for troubleshooting these issues, something indepth and technical enough so that you can work your way through the problem, right now, I'm just lost with insufficent information from webpack, I have built two identical setups, one works there other doesn't but there's nothing there to help me sort out why, I know this probably is a mistake nested somewhere in my setup but I cannot find it, I've spent the better part of 3 days trying to chase this down and it's not the first time I spend a lot of time trying to understand why HMR isn't working. So, I would really appricate some help trying to root cause this and improving the situation for the future.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Latest version of webpack. 3.5.5

**Comment by sokra** [comment]
> React and hot loader is used

react-hot-loader? Best remove it when you using `module.hot.accept`.

> However, get warning `The following modules couldn't be hot updated`

The warning should include more info. Could you include them?

> Not generally reproducible.

Probably difficult to solve this problem without repro repo.

**Comment by leidegre** [comment]
Are `react-hot-loader` incompatible with `module.hot.accept`? I've used this in the past, without a problem.

If I can get a repo working I will include it, right now it's a really big app and I haven't had the time yet to cut down everything but I'm working on a repo, however, so far the repo isn't repoing, it's working which is annoying. If I figure it out I will share it.

The exact warning message is the standard `The following modules couldn't be hot updated` and then it lists the file that I changed, specifically the `pages/Home` file. That's all I'm getting. I have a vauge memory that it used to include more details but that is not the case.

If there's anthing I can try on my end, anything I can do, I'm willing to do (besides working on the repo).

**Comment by sokra** [comment]
> The exact warning message is the standard The following modules couldn't be hot updated and then it lists the file that I changed, specifically the pages/Home file. That's all I'm getting.

The not `only` (`--hot`  instead of `--hot-only`) should include more info in the error message.

> react-hot-loader

It accepts all updates on component level. This way it doesn't bubble anymore and `accept("component", ...)` will never be called.

**Comment by leidegre** [comment]
...but it is bubbling because it goes away if I do `module.hot.accept()`, no args. Nasty errors and warnings but it looks more like it is working if I do that.

Also, I have it set up as an express middleware.

~~~
app.use(
  webpackDevMiddleware(
    compiler,
    Object.assign({}, compilerConfig.devServer, {
      noInfo: true, // a lot less clutter in console
      publicPath: compilerConfig.output.publicPath,
      stats: 'errors-only'
    })
  )
)

app.use(webpackHotMiddleware(compiler))
~~~

Entry point like this

~~~
[
  'babel-polyfill',
  'react-hot-loader/patch',
  'webpack-hot-middleware/client',
  './src/client-renderer.js'
]
~~~

**Comment by leidegre** [comment]
I have some more peculiar back traces from HMR for you...

~~~
process-update.js:89 [HMR]  - ./src/pages/commitments/blocks/ReservationProcess.js
(anonymous) @ process-update.js:89
logUpdates @ process-update.js:88
applyCallback @ process-update.js:49
(anonymous) @ process-update.js:57
Promise resolved (async)
cb @ process-update.js:56
(anonymous) @ process-update.js:68
Promise resolved (async)
check @ process-update.js:67
webpackJsonp../node_modules/webpack-hot-middleware/process-update.js.module.exports @ process-update.js:28
processMessage @ client.js:228
handleMessage @ client.js:111
handleMessage @ client.js:74
process-update.js:89 [HMR]  - ./src/pages/projectquestions/actions.js
(anonymous) @ process-update.js:89
logUpdates @ process-update.js:88
applyCallback @ process-update.js:49
(anonymous) @ process-update.js:57
Promise resolved (async)
cb @ process-update.js:56
(anonymous) @ process-update.js:68
Promise resolved (async)
check @ process-update.js:67
webpackJsonp../node_modules/webpack-hot-middleware/process-update.js.module.exports @ process-update.js:28
processMessage @ client.js:228
handleMessage @ client.js:111
handleMessage @ client.js:74
process-update.js:89 [HMR]  - ./src/pages/projectquestions/index.js
(anonymous) @ process-update.js:89
logUpdates @ process-update.js:88
applyCallback @ process-update.js:49
(anonymous) @ process-update.js:57
Promise resolved (async)
cb @ process-update.js:56
(anonymous) @ process-update.js:68
Promise resolved (async)
check @ process-update.js:67
webpackJsonp../node_modules/webpack-hot-middleware/process-update.js.module.exports @ process-update.js:28
processMessage @ client.js:228
handleMessage @ client.js:111
handleMessage @ client.js:74
process-update.js:89 [HMR]  - ./src/pages/projects/actions.js
(anonymous) @ process-update.js:89
logUpdates @ process-update.js:88
applyCallback @ process-update.js:49
(anonymous) @ process-update.js:57
Promise resolved (async)
cb @ process-update.js:56
(anonymous) @ process-update.js:68
Promise resolved (async)
check @ process-update.js:67
webpackJsonp../node_modules/webpack-hot-middleware/process-update.js.module.exports @ process-update.js:28
processMessage @ client.js:228
handleMessage @ client.js:111
handleMessage @ client.js:74
process-update.js:89 [HMR]  - ./src/pages/projects/index.js
(anonymous) @ process-update.js:89
logUpdates @ process-update.js:88
applyCallback @ process-update.js:49
(anonymous) @ process-update.js:57
Promise resolved (async)
cb @ process-update.js:56
(anonymous) @ process-update.js:68
Promise resolved (async)
check @ process-update.js:67
webpackJsonp../node_modules/webpack-hot-middleware/process-update.js.module.exports @ process-update.js:28
processMessage @ client.js:228
handleMessage @ client.js:111
handleMessage @ client.js:74
process-update.js:89 [HMR]  - ./src/shared/blocks/Project.js
(anonymous) @ process-update.js:89
logUpdates @ process-update.js:88
applyCallback @ process-update.js:49
(anonymous) @ process-update.js:57
Promise resolved (async)
cb @ process-update.js:56
(anonymous) @ process-update.js:68
Promise resolved (async)
check @ process-update.js:67
webpackJsonp../node_modules/webpack-hot-middleware/process-update.js.module.exports @ process-update.js:28
processMessage @ client.js:228
handleMessage @ client.js:111
handleMessage @ client.js:74
process-update.js:89 [HMR]  - ./src/shared/blocks/SimpleRegisterForm.js
(anonymous) @ process-update.js:89
logUpdates @ process-update.js:88
applyCallback @ process-update.js:49
(anonymous) @ process-update.js:57
Promise resolved (async)
cb @ process-update.js:56
(anonymous) @ process-update.js:68
Promise resolved (async)
check @ process-update.js:67
webpackJsonp../node_modules/webpack-hot-middleware/process-update.js.module.exports @ process-update.js:28
processMessage @ client.js:228
handleMessage @ client.js:111
handleMessage @ client.js:74
process-update.js:89 [HMR]  - ./src/shared/reactstrap/TetherContent.js
(anonymous) @ process-update.js:89
logUpdates @ process-update.js:88
applyCallback @ process-update.js:49
(anonymous) @ process-update.js:57
Promise resolved (async)
cb @ process-update.js:56
(anonymous) @ process-update.js:68
Promise resolved (async)
check @ process-update.js:67
webpackJsonp../node_modules/webpack-hot-middleware/process-update.js.module.exports @ process-update.js:28
processMessage @ client.js:228
handleMessage @ client.js:111
handleMessage @ client.js:74
process-update.js:89 [HMR]  - ./src/shared/urls.js
~~~

And...

~~~
process-update.js:89 [HMR]  - ./src/pages/commitments/blocks/ReservationProcess.js
(anonymous) @ process-update.js:89
logUpdates @ process-update.js:88
applyCallback @ process-update.js:49
(anonymous) @ process-update.js:57
Promise resolved (async)
cb @ process-update.js:56
(anonymous) @ process-update.js:68
Promise resolved (async)
check @ process-update.js:67
applyCallback @ process-update.js:47
(anonymous) @ process-update.js:57
Promise resolved (async)
cb @ process-update.js:56
(anonymous) @ process-update.js:68
Promise resolved (async)
check @ process-update.js:67
webpackJsonp../node_modules/webpack-hot-middleware/process-update.js.module.exports @ process-update.js:28
processMessage @ client.js:228
handleMessage @ client.js:111
handleMessage @ client.js:74
process-update.js:89 [HMR]  - ./src/pages/projects/actions.js
(anonymous) @ process-update.js:89
logUpdates @ process-update.js:88
applyCallback @ process-update.js:49
(anonymous) @ process-update.js:57
Promise resolved (async)
cb @ process-update.js:56
(anonymous) @ process-update.js:68
Promise resolved (async)
check @ process-update.js:67
applyCallback @ process-update.js:47
(anonymous) @ process-update.js:57
Promise resolved (async)
cb @ process-update.js:56
(anonymous) @ process-update.js:68
Promise resolved (async)
check @ process-update.js:67
webpackJsonp../node_modules/webpack-hot-middleware/process-update.js.module.exports @ process-update.js:28
processMessage @ client.js:228
handleMessage @ client.js:111
handleMessage @ client.js:74
process-update.js:89 [HMR]  - ./src/shared/blocks/Project.js
(anonymous) @ process-update.js:89
logUpdates @ process-update.js:88
applyCallback @ process-update.js:49
(anonymous) @ process-update.js:57
Promise resolved (async)
cb @ process-update.js:56
(anonymous) @ process-update.js:68
Promise resolved (async)
check @ process-update.js:67
applyCallback @ process-update.js:47
(anonymous) @ process-update.js:57
Promise resolved (async)
cb @ process-update.js:56
(anonymous) @ process-update.js:68
Promise resolved (async)
check @ process-update.js:67
webpackJsonp../node_modules/webpack-hot-middleware/process-update.js.module.exports @ process-update.js:28
processMessage @ client.js:228
handleMessage @ client.js:111
handleMessage @ client.js:74
process-update.js:89 [HMR]  - ./src/shared/urls.js
~~~

The peculiar thing is that these happen when I edit a component that isn't referenced by any of the modules listed. How should I interpret these warnings? Why are they happening?

**Comment by sokra** [comment]
When you get these messages this means all these modules are updated. Could you take a look into the hot update chunk which is downloaded? It should only contain changed modules.

Which modules does webpack report as changed?

**Comment by leidegre** [comment]
Like these?

~~~
{
  "h": "437d2d6b8e2a3e4451f8",
  "c": {
    "about": true,
    "account": true,
    "blog": true,
    "commitments": true,
    "common": true,
    "kyc": true,
    "projects": true,
    "questions": true
  }
}
~~~

These are chunks that I've named explicitly.

**Comment by leidegre** [comment]
Would it be a mistake to use the common chunks plugin with HMR enabled?

**Comment by sokra** [comment]
`"c"` lists all chunks that include changed modules.

> Would it be a mistake to use the common chunks plugin with HMR enabled?

no

**Comment by leidegre** [comment]
Where do we go from here? What's the next thing to check? Looks like everything changed which is reasonable since some of those files that I did touch are shared.

**Comment by sokra** [comment]
Could you take a look at `account.hot-update-chunk.js` to see the changed modules? It should be loaded shortly after the `hot-update-mainfest.json`.

**Comment by leidegre** [comment]
Different file but I see it, I'm looking through the source now, what I'm I looking for?

I can see the `__REACT_HOT_LOADER__.register` calls for example. Looks like a new module definition for the file changed.

**Comment by sokra** [comment]
> Different file but I see it, I'm looking through the source now, what I'm I looking for?

Find the difference in modules that should not been changed. Compare it to the version in the **original** (before the change) bundle.js file.

i. e. find the difference in the module `./src/shared/urls.js` which you didn't touched.

**Comment by leidegre** [comment]
In the bootstrap code I found this little gem,

~~~
"Update propagation: ./src/pages/home/Home.js -> ./src/pages/home/index.js -> ./src/pages/buildRoutes.js -> ./src/shared/actions.js -> ./src/client-renderer.js -> 0"
~~~

And it's ignored like this

~~~
if (!options.ignoreUnaccepted) // ignoreUnaccepted is true
  abortError = new Error("Aborted because " + moduleId + " is not accepted" + chainInfo);
~~~

The information is there but it's hidden, I think this is a huge mistake.

Becuase as you can see now from the chain the component is actually passing through `./src/shared/actions.js`, it's this file that I must accept in client-renderer. And so I did and now it works however I am a bit dismayed that this information was swalloed in the code, I would have figured this out much sooner if it would have been displayed together with the other warning message.

When I looked closer in `./src/shared/actions.js` it was obvious why it included `./src/pages/buildRoutes.js` and I have to work out a different way of organizing the dependecies to avoid this problem, I think... not sure yet what the best solution is here but well.

Is there anyway we could get webpack HMR to always output that `chainInfo` error message, I think it could really help people out there.

**Comment by sokra** [comment]
hmm... the original webpack HMR management code prints this info here: https://github.com/webpack/webpack/blob/master/hot/only-dev-server.js#L25

It's only the webpack-hot-middleware variant that doesn't print it.

**Comment by leidegre** [comment]
@sokra anything special about the code you linked or would it be possible to just slap that in your "main" function for debugging purposes? What is this `check()` API?

**Comment by mqliutie** [comment]
`module.hot.accept()` is enough actually for me to replace module. 

But I have many subscriptions, every time replace will add a subscription.. so, trigger event will execute my callback many times...

So I want to add dependencies to the args but the callback never be called.. 
```
"webpack": "^5.72.1",
"webpack-cli": "^4.9.2",
"webpack-dev-server": "^4.9.0",
```

**Comment by LingYanSi** [comment]
@mqliutie I have a same problem. when i disable `devServer.liveReload`，the problem is gone.
