### ISSUE TITLE
import chunks when url is not root

### ISSUE THREAD

**Issue by FredericHeem** [webpack/webpack#5588]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
There is an issue when loading chunks with import in the case where the current url is not a root url:
i.e http://localhost:8080/admin/users
In that case, the chunk being loaded is for instance from the url http://localhost:8080/admin/2.js which doesn't exist.
See https://github.com/webpack/webpack/pull/5587 for the original PR.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
The chunk should be loaded from the correct url
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

webpack 3.5.5

**Comment by sokra** [comment]
See `output.publicPath` option

**Comment by FredericHeem** [comment]
As already stated in the other PR, setting output.publicPath to  "/" doesn't solve the issue and makes it even worse.

**Comment by FredericHeem** [comment]
Please find below  the steps to reproduce the issue:
* `git clone git@github.com:FredericHeem/starhackit.git && cd starhackit/client && git checkout webpack-import-url-not-root && npm i && npm start`

* Change the url in the browser to `http://localhost:8080/aaa`, the 404 page should be dynamically loaded with `import` from `http://localhost:8080/10.js`
* Now change the url to `http://localhost:8080/aaa/bbb`, the 404 page is not loaded because it tries to load the chunk `http://localhost:8080/aaa/10.js`

Let me know if you need more information.
