### ISSUE TITLE
Webpack's sourcemap paths are not real paths

### ISSUE THREAD

**Issue by fresheneesz** [webpack/webpack#559]
It seems like webpack changed the way it puts the paths in the sourcemap file, but the paths are all wrong. They all look like:

`webpack://whatever/~/more-stuff.js`

I was working around webpack's previous weird way of writing paths in the sourcemap, but the real question is: why is webpack writing the mapped paths this way? I need to be able to go request the actual file from the server from these paths, and webpack's non-standard paths are blocking me from doing this.

**Comment by TroutZen** [comment]
Old thread, but thanks @sokra  - this config was helpful for getting vscode debugger working with sourcemaps in my node app.
