### ISSUE TITLE
DefinePlugin does not replace process.env variables when process is imported

### ISSUE THREAD

**Issue by mkools-vg** [webpack/webpack#5596]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When importing the `process` module, the DefinePlugin will not substitute `process.env` variables, such as `process.env.NODE_ENV`

**If the current behavior is a bug, please provide the steps to reproduce.**

```js
import * as process from "process"
console.log(process.env.NODE_ENV)
```

For a sample project see [mkools-vg/webpackDemo](https://github.com/mkools-vg/webpackDemo)

**What is the expected behavior?**

`process.env.NODE_ENV` is replaced with the value as defined by DefinePlugin.

**If this is a feature request, what is motivation or use case for changing the behavior?**
N/A

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
browser: N/A
Node.js: 6.11.2
webpack: 3.5.5
Operating System: Windows 10 (1703)

**Comment by sokra** [comment]
Yep this is not support. The DefinePlugin only replaces free vars.
