### ISSUE TITLE
Bundler behaviour with dynamic require

### ISSUE THREAD

**Issue by jbprat** [webpack/webpack#5597]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

My goal is to have dynamic require without having all the dependencies at the same level bundled, since I may have 50 brands at some point.

My structure would be this one:

>     -src/app
>     -theming
>     --default
>     --brand_1

Here is an example Angular component:
 ```
import { Component } from '@angular/core';
    
    const brand = 'brand_1';
    
    @Component({
      selector: 'app-root',
      templateUrl: './app.component.html',
      styleUrls: [`../../theming/${brand}/style.scss`]
    })
    export class AppComponent {
      title = 'app';
    }

```
The current behavior is that whenever I do a dynamic require, all the siblings folders/files are included in the bundle.

**What is the expected behavior?**

The expected behavior would be not to  have a map including all the files.

**If this is a feature request, what is motivation or use case for changing the behavior?**
I read in your documentation that this is the intended behaviour. I think it could be improved to just getting the file. It would avoid adding unnecessary js/scss to the core code.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Node.js : 7.10.0
Webpack version: 3.4.1

**Comment by TheLarkInn** [comment]
If your component there is being processed by a loader that converts it to: 

`require("../../theming/${brand}/style.scss")`

This would cause what you have mentioned, to happen (by design). I would best check with the loader author, or submit an issue there.

**Comment by TheLarkInn** [comment]
Oops I almost forgot. 👏 👏 👏 👏  Thank you so much for submitting your first issue 👏 👏 👏 👏 

And feel free to link this closed issue to the one you open in the loader repo itself so I can track it, if I need to chime in.

**Comment by jbprat** [comment]
@TheLarkInn Thanks for the clarification, I've done a feature request in the Angular repo!
