### ISSUE TITLE
DefinePlugin does NOT inject variables into require() call, if variable was preceded by runtime variable.

### ISSUE THREAD

**Issue by slawus** [webpack/webpack#5602]
**Do you want to request a *feature* or report a *bug*?**
Bug 🐛.

**What is the current behavior?**

__DefinePlugin doesn't replace variable used in require() call__, if this variable is preceded by other runtime variable. It looks like problem exists on in the bundle.js file (final result of the bundling process), but not in 'resolving dependencies phase', as you can notice that webpack copies only necessary files.

Thanks to that, there is no error when bundling project, however it's **impossible to run generated code**, because it has references to undefined (unreplaced) variables.

**If the current behavior is a bug, please provide the steps to reproduce.**

[Here is minimal project, that allows you to reproduce error](https://github.com/slawus/webpack-defineplugin-require-bug)

As the result you will get bundle.js file, with` __FILE__FORMAT__` not being replaced. However, `dist/assets` will contain only files with configured format. 

**What is the expected behavior?**

All variables passed to DefinePlugin should be replaced in the bundle.js file.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
- Webpack 3.5.5 (latest)
- Node 6.11.2 & Node 8.0.0
- macOs 10.12.6

**Comment by sokra** [comment]
Yep this bug exists since webpack version 0.

**Comment by misterdev** [comment]
Updating webpack and file-loader to the latest version solved the problem for me:

```
"devDependencies": {
    "file-loader": "^3.0.1",
    "webpack": "^4.29.0",
    "webpack-cli": "^3.2.1"
}
```
Also, since Webpack 4 throws an error when loading json files using `file-loader` ([link](https://github.com/webpack-contrib/file-loader/issues/259#issuecomment-391779346)), I've also edited your configuration to work with the .txt file:
```
    plugins: [
        new webpack.DefinePlugin({
            __FILE_FORMAT__: JSON.stringify('.txt'), // replaced '.json' with '.txt'
            __SUBDIR__: JSON.stringify('bar')
        })
    ],
    module: {
        rules: [{
            test: /\.(txt)(\?.*$|$)/, // removed "| json"
            use: {
                loader: 'file-loader',
                options: {
                    name: 'assets/[name].[ext]'
                }
            }
        }]
    }
```

From my understanding this is fixed in webpack 4

**Comment by misterdev** [comment]
I've forked @slawus repo and updated with the above configurations [here](https://github.com/misterdev/webpack-defineplugin-require-bug).

I think this could be closed :)
