### ISSUE TITLE
Cannot find module when using alias.

### ISSUE THREAD

**Issue by nikichak** [webpack/webpack#5603]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?** 
I'm using webpack 3.10.10 and in my webpack.config I have : 
`config.resolve = {
    alias: {
      'app': path.join(__dirname, 'src/app/')
    },
    extensions: ['.ts', '.js', '.json', '.css', '.scss', '.html'],
    modules: [__dirname, path.join(__dirname, 'node_modules')]
  };`

I'm also trying to import something from the created alias: 

   `import {BasePage} from 'app/pages/base/base-page';`

  and in the constructor of the component in which I'm trying to import I console log 

   `console.log(BasePage);`

Everything is okay and the imported component is printed. But in the terminal I get the error: 
`ERROR in [at-loader] ./src/app/about/about.component.ts:3:24 
    TS2307: Cannot find module 'app/pages/base/base-page'.
`
How can I fix it ? 
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
I expect to not get cannot find module error in the console when using the alias.
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by TheLarkInn** [comment]
Typescript unfortunately has it's own module resolution and would need to mirror webpack's alas settings. Since this is not a bug im going to close.
