### ISSUE TITLE
But Mah memory!

### ISSUE THREAD

**Issue by keynan** [webpack/webpack#5609]
Bug - sorta
**What is the current behavior?**
Webpack uses 1GB of memory to serve <10MB of static files
**If the current behavior is a bug, please provide the steps to reproduce.**
run any trivial project

**What is the expected behavior?**
Memory usage <50MB

**If this is a feature request, what is motivation or use case for changing the behavior?**
My 16GB dev box is memory constrained enough already thank you very much.

**Comment by sokra** [comment]
> run any trivial project

I ran one. It used only 84MB. Please provide a correct repro repo.

**Comment by keynan** [comment]
git@github.com:shanewilson/react-webpack-example.git

**Comment by about-code** [comment]
shanewilson/react-webpack-example uses SourceMap-Plug-in in its ./config/_base.js.  @sokra Issue may be related to long-standing (urgent) #2157. At the end of the issue's thread I have provided a review of the sourcemap plug-in with a few findings which *may* cause a memory leak. I was in lack of a repro until now and don't really understand the plugin's code, yet. But maybe shanewilson/react-webpack-example eventually provides us with the repro we need.
