### ISSUE TITLE
Stop webpack from altering DEBUG

### ISSUE THREAD

**Issue by simonsmith** [webpack/webpack#561]
I'm using Flight JS which relies on a global DEBUG object to attach various methods to - https://github.com/flightjs/flight/blob/000db07ef37838754f26b105ab8d287ee3561b89/lib/debug.js#L133

Since upgrading Webpack I've noticed it is rewriting this to `(false)` which breaks code. How can I opt out of this behaviour?

**Comment by bebraw** [comment]
@simonsmith Is this relevant still?

**Comment by simonsmith** [comment]
Probably not. FlightJS has since been abandoned and I don't think it's a common problem. Feel free to close.

**Comment by bebraw** [comment]
Thanks.
