### ISSUE TITLE
Chrome dies after trying to modify code at runtime

### ISSUE THREAD

**Issue by djflex68** [webpack/webpack#5610]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
With Chrome, it was possible to modify code while debugging, then save it, and the debugger would re-run the same method again with the previous context.
Since I'm using webpack, doing this breaks the debugger which crashes completely. It's certainly more a chrome than a webpack issue, but it would be nice to know if you're aware of this.

**If the current behavior is a bug, please provide the steps to reproduce.**
Using chrome 60.0.3112.113  and webpack 2.7.0

**What is the expected behavior?**
not breaking 
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by sokra** [comment]
Did you report this to chrome?

**Comment by sokra** [comment]
If this is the problem you can try to use the AggressiveSplittingPlugin which splits large chunks into small ones.

**Comment by rafde** [comment]
@sokra that works well for single builds, but it goes into an infinite loop when using the plugin while in watch mode.

**Comment by rafde** [comment]
It looks like AggressiveSplittingPlugin does not create an entry chunk that will be request to load the rest of the modules.
Example

```js
entry:{
  main:['bootstrap.js']
},
plugins:[
  new CommonsChunkPlugin({
    name: 'manifest',
    minChunks: Infinity
  }),
  new webpack.optimize.AggressiveSplittingPlugin()
],
// rest of config
```
will create a manifest file but the rest of the created chunks will have to included in the page a script tag at a time. Where it would be nice to have one script tag that will kick start requesting the rest of the modules, the same way requirejs(non-bundle) did it.

**Comment by sokra** [comment]
Yeah this is expected. You have to load all splitted chunks via script tags. A single file which kicks of the rest would cause two roundtrips instead of one. The stats contains a `entrypoints` property with all information you need to add the script tags.

**Comment by djflex68** [comment]
ok thanks for this info, I'll report this to Chrome. I have indeed some heavy chunks that might cause this issue.  I'll give a try to the AgressivePluging, thanks :)

**Comment by patrickjuchli** [comment]
This sounds like [this issue](https://bugs.chromium.org/p/v8/issues/detail?id=3894). An old friend/ticket of mine.

I don't see this happening anymore with Chrome 61, though. Could you have a look if it's the same for your project?
