### ISSUE TITLE
NEED HELP: External css-loader

### ISSUE THREAD

**Issue by janhoeck** [webpack/webpack#5612]
Hey guys,

I need your help with the "externals" key in my webpack config.

I looked into my builded app.js file and saw that css-loader gets included. But I don't need this, because I want to use the global css-loader (FYI: I have a module system).
So I put the css-loader into my externals. Like this:

> externals: {
        'axios': 'axios',
        'react': 'react',
        'react-dom': 'reactDom',
        'ff-aws-sdk': 'ffAwsSdk',
        'ff-api-services': 'ffApiServices',
        'mobx': 'mobx',
        'mobx-react': 'mobxReact',
        'mobx-react-devtools': 'mobxReactDevTools',
        'react-router': 'reactRouter',
        'react-router-dom': 'reactRouterDom',
        'prop-types': 'propTypes',
        'react-hot-loader': 'reactHotLoader',
        'resolve-url-loader': 'resolveUrlLoader',
        'style-loader': 'styleLoader',
        'url-loader': 'urlLoader',
        'webpack': 'webpack',
        'webpack-dev-server': 'webpackDevServer',
        'lodash': 'lodash',
        'css-loader': 'cssLoader',
        'jquery': 'jQuery'
    }

After that I build my module again and saw with the webpack visualizer, that it is already there. Why?
![image](https://user-images.githubusercontent.com/15649454/29964267-ce462f80-8f09-11e7-9678-38db3a1ac4de.png)

**Comment by sokra** [comment]
Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md).
