### ISSUE TITLE
Module not found: Error: Can't resolve 'webpackChunkName'

### ISSUE THREAD

**Issue by govis** [webpack/webpack#5613]
**Do you want to request a *feature* or report a *bug*?**
Possibly a bug, with <code>import(/* webpackChunkName: "xxx" */ 'xxx').then(...);</code> where xxx is an <code>.html</code> file that is being loaded with <code>polymer-webpack-loader</code>. Webpack throws <code>Module not found: Error: Can't resolve 'xxx' in Project folder path</code>

**What is the current behavior?**
Webpack appears to be looking for xxx.js file, even though xxx entry is defined as xxx.html. if I change 
 it to <code>import(/* webpackChunkName: "xxx" */ 'xxx.html')</code>, it works, and xxx.js does get created but fails to load: <code>Uncaught (in promise) Error: Loading chunk 0 failed.</code> - It appears to be trying to import '0.js' instead.
 
**If the current behavior is a bug, please provide the steps to reproduce.**
In this example 'xxx' is 'page1' entry point:

<pre><code>module.exports = {
    entry: {
        'app': './app-main.html',
        'page1': './page1.html'
    },
    output: {
        filename: '[name].js',
        path: path.resolve(__dirname, 'build')
    },
    resolve: {
        modules: [ process.env.NODE_PATH || 'node_modules', 'bower_components'],
        descriptionFiles: ['package.json']
    },
    resolveLoader: {
        modules: [ process.env.NODE_PATH || 'node_modules' ],
    },
    module: {
        rules: [
            {
                test: /\.html$/,
                loader: 'polymer-webpack-loader'
            }
        ]
    },
    plugins: [
        new webpack.optimize.CommonsChunkPlugin({
            name: 'common'
        })
    ]
}</code></pre>

<pre><code>app-main.html:
...
import(/* webpackChunkName: "page1" */ './page1').then(_ => {
        ...
    });
...
</code></pre>

<pre><code>ERROR in ./app-main.html
Module not found: Error: Can't resolve 'page1' in 'Project folder path'
resolve 'page1' in 'Project folder path'
  Parsed request is a module
  No description file found
  resolve as module
    looking for modules in C:\Users\govis\AppData\Roaming\npm\node_modules
      No description file found
      No description file found
      no extension
...
</code></pre>

**What is the expected behavior?**
No error

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Node v8.2.1
Webpack v3.5.5
Windows 10

**Comment by donocode** [comment]
You need to resolve the .html extension

```
resolve: {
  extensions: ['.js', '.html'],
  // other resolve stuff
}
```

**Comment by govis** [comment]
Thanks, but I still get an error when running the app 
<pre><code>common.js:104 Uncaught (in promise) Error: Loading chunk 0 failed.
    at HTMLScriptElement.onScriptComplete (common.js:104)</code></pre>
It appears to be looking for <code>0.js</code> instead of <code>page1.js</code>

**Comment by sokra** [comment]
You should not add `page1` to `entry`. Files loaded with `import()` are not entries.

**Comment by govis** [comment]
That works, thank you.
