### ISSUE TITLE
Better control of bundling and de-duping dependencies shared across entry points

### ISSUE THREAD

**Issue by govis** [webpack/webpack#5614]
**Do you want to request a *feature* or report a *bug*?**

Feature to keep Shell and main Bundle free of unnecessary dependencies when CommonsChunkPlugin plugin is used with multiple entry points.

Consider an SPA PRPL Pattern (Shell+lazy loaded bundled routes):

![image](https://user-images.githubusercontent.com/971651/29979454-89434eae-8f13-11e7-8ad2-504ff1cd1252.png)

With 3 entry points (my-app.html, list-view.html and detail-view.html) and use of CommonsChunkPlugin to de-dup dependencies across bundles the common(shared) bundle ends up be containing bootstrap code needed to fire up the shell along with some shared dependencies.

I'm building an application with multiple bundles: Shell, Bundle1(most used, eagerly loaded), Bundle2(less used) and Bundle3(least used and/or fat) and would like to have the Shell contain just the bootstrap code, Bundle1 have just its own dependencies only (de-duped with the Shell) and other bundles share common chunks (shared deps) also de-duped with Shell and Bundle1 and between each other.

I have tried various setups with an array of entry points and CommonsChunkPlugin stacking as per [multiple-commons-chunks](https://github.com/webpack/webpack/tree/master/examples/multiple-commons-chunks), but it seems to be impossible to get unencumbered Shell and Bundle1 while de-dupping and bundling subsequent entries with CommonsChunkPlugin. 

**What is the current behavior?**
When CommonsChunkPlugin is applied some dependencies from Bundle2 and 3 get merged into common chunk that needs to be loaded by the Shell and/or Bundle1.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**
Optimal and efficient load time of a web application

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Webpack v3.5.5

**Comment by sokra** [comment]
see `chunks` options for the `CommonsChunkPlugin`

**Comment by govis** [comment]
Yes, I've tried the following to de-dup all the way:
<pre><code>new webpack.optimize.CommonsChunkPlugin({
    name: 'common1',
    chunks: ['shell', 'bundle1'],
}),
new webpack.optimize.CommonsChunkPlugin({
    name: 'common2',
    chunks: ['common1', 'bundle2'],
}),
new webpack.optimize.CommonsChunkPlugin({
    name: 'common3',
    chunks: ['common2', 'bundle3', 'bundle4', ...],
}), ...</code></pre>

But wouldn't common1, common2 and common3 have to loaded by the Shell and Bundle1? Thanks

**Comment by sokra** [comment]
``` js
// move commons between bundle2 and bundle3 into new chunk common
new webpack.optimize.CommonsChunkPlugin({
    name: 'common',
    chunks: ['bundle2', 'bundle3'],
}),
// Put shell on top of bundle1 and common
new webpack.optimize.CommonsChunkPlugin({
    name: 'shell',
    chunks: ['bundle1', 'common']
}),
```

**Comment by govis** [comment]
Thank you for suggestion - I'll give it a try

**Comment by govis** [comment]
So I got a simple case to work as per your recommendation, but I am still struggling with a more complex scenario where bundles have multiple overlapping sets of shared dependencies. For instance "admin" bundles share common modules that are admin-specific while some "entity" bundles  share enough of common entityX-specific modules. 7 modules altogether (inc shell):

<pre><code>shell
entityA
entityB
entityC
entityBadmin
entityCadmin
entityDadmin</code></pre>

I want to produce 2 shared bundles as follows:
entityCcommon (entityC and entityCadmin)
admincommon (entityBadmin, entityCadmin, entityDadmin)
and have the shell contain bootstrap modules only

<pre><code>new webpack.optimize.CommonsChunkPlugin({
    name: 'entityCcommon',
    chunks: ['entityC', 'entityCadmin']
}),
new webpack.optimize.CommonsChunkPlugin({
    name: 'admincommon',
    chunks: ['entityBadmin', 'entityCadmin', 'entityDadmin']
}),
new webpack.optimize.CommonsChunkPlugin({
    name: 'shell',
    chunks: ['entityA', 'entityB', 'entityCcommon', 'admincommon']
})</code></pre>

does produce the bundles

<pre><code>shell
entityA
entityB
entityC
entityBadmin
entityCadmin
entityDadmin
entityCcommon
admincommon</code></pre>

All but shell and entityA fail to load:

<pre><code>modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
Uncaught (in promise) TypeError: Cannot read property 'call' of undefined
at __webpack_require__
</code></pre> Tried many other combinations to no avail, Thanks

**Comment by govis** [comment]
It appears to be working if I pre-load <code>entityCcommon</code> and <code>admincommon</code> along with the <code>shell</code> - but my goal is to break up bundles into meaningful chunks for lazy load
