### ISSUE TITLE
Default exports from a filename that is a keyword

### ISSUE THREAD

**Issue by gpoitch** [webpack/webpack#5615]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
A file name with a reserved keyword that exports a default, is compiled to something like this:
```js
var async = __webpack_require__("./store/middleware/async.js");
```

Where 'async' in this example is a reserved word.  So when passing that to uglify-es, or run on a server with node 8+, the variable is not actually the expected file when imported.

**If the current behavior is a bug, please provide the steps to reproduce.**
- Create a file named with a reserved word like 'async' and export a default
- Import it somewhere
- Builds successfully
- Various other tools and environments can misinterpret that variable name as a keyword

**What is the expected behavior?**
Webpack should not generate variable names that are keywords, or future keywords

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Node 8
Webpack 3.5.5

**Comment by TheLarkInn** [comment]
Thank you so much for the report. Would you be able to provide a minimal reproducible repo that we could use to bake into our tests and uglifyjs-webpack-plugin tests

//cc @d3viant0ne

**Comment by kzc** [comment]
> Where 'async' in this example is a reserved word. So when passing that to uglify-es, or run on a server with node 8+, the variable is not actually the expected file when imported.

A variable named `async` wouldn't be a problem for `uglify-es` since it's considered to be a pseudo keyword:
```
$ uglifyjs -V
uglify-es 3.0.28

$ echo '"use strict"; var async = "ASYNC"; console.log(async);' | uglifyjs -mc
"use strict";var async="ASYNC";console.log(async);
```
Even `node 8.x` has no issue with it:
```
$ echo '"use strict"; var async = "ASYNC"; console.log(async);' | node800
ASYNC
```
Or `acorn@5.1.1` for that matter:
```
echo '"use strict"; var async = "ASYNC"; console.log(async);' | acorn --ecma2018
...valid JSON AST emitted...
```
However if `webpack` were to generate a variable named `var` (for example) it would be an error. Whether `webpack` generates such code or not - I don't know.

**Comment by gpoitch** [comment]
Working on a minimal repro and haven't been able to trigger it yet.  

On my real application, uglify-es is minifying webpack's output: 
```js
var async = __webpack_require__("./store/middleware/async.js")
```
to 
```js
var t=["e"];
```

Unsure if webpack, uglify or something else is at fault.  Will follow up.
