### ISSUE TITLE
add an option to resolve globally installed modules

### ISSUE THREAD

**Issue by pravi** [webpack/webpack#5618]
**Do you want to request a *feature* or report a *bug*?**

this is a feature request

**What is the current behavior?**

```
ERROR in /usr/lib/nodejs/timers-browserify/main.js
Module not found: Error: Can't resolve 'setimmediate' in '/usr/lib/nodejs/timers-browserify'
 @ /usr/lib/nodejs/timers-browserify/main.js 49:0-23
 @ /usr/lib/nodejs/readable-stream/lib/_stream_writable.js
 @ /usr/lib/nodejs/readable-stream/readable-browser.js
 @ /usr/lib/nodejs/readable-stream/transform.js
 @ /usr/lib/nodejs/browserify-zlib/src/index.js
 @ /var/lib/gitlab/~/pdfjs-dist/build/pdf.js
 @ /var/lib/gitlab/~/babel-loader/lib!/var/lib/gitlab/~/vue-loader/lib/selector.js?type=script&index=0!./pdf/index.vue
 @ ./pdf/index.vue
 @ ./blob/pdf/index.js
```
 @ ./blob/pdf_viewer.js

setimmediate is present in /usr/lib/nodejs but webpack is expecting it to be available only relative to timers-browserify.

**If the current behavior is a bug, please provide the steps to reproduce.**

This can be reproduced if all dependencies are available in a global location.

**What is the expected behavior?**

There should be an option to provide a global module path for resolving, similar to how nodejs itself looks in NODE_PATH. If webpack itself can use NODE_PATH to resolve modules if defined, that is better.

**If this is a feature request, what is motivation or use case for changing the behavior?**

This is useful for debian. We want to be able to use a single version of a module for all apps that need it. I know the nodejs culture is different (it wants to use multiple versions of dependencies), hence only asking for this as an option. We take the extra effort of making sure the module version available in debian is compatible with all the software that use it.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

This is for debian native ppackage of webpack, currently 2.6.1. Nodejs is 6.11.2.

**Comment by sokra** [comment]
You should not use globally installed dependencies in your build. Install them locally or symlink them.

**Comment by benkovsk** [comment]
Global modules are not unheard of even in javascript ecosystem, though:

**Comment by pravi** [comment]
We add `resolve` and resolveLoader` options to every package's webpack.config.js to work around this.
