### ISSUE TITLE
Webpack fails to build on NTFS filesystem

### ISSUE THREAD

**Issue by sheljohn** [webpack/webpack#5620]
**Do you want to request a *feature* or report a *bug*?**
I am reporting a bug.

**What is the current behavior?**
The latest version of webpack `3.5.5` (as well as the `beta` version) does not build on NTFS filesystems.
Specifically, the error seems to be related to the package `fsevents` during the `postinstall` step (error: "directory not empty").

**If the current behavior is a bug, please provide the steps to reproduce.**
This [gist](https://gist.github.com/sheljohn/6021e522397603ed90df87a9157f4728) reproduces the bug on my machine.

**What is the expected behavior?**
The build should not fail.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

```
$ npm --version
5.4.0
$ uname -v
#37~16.04.1-Ubuntu SMP Fri Aug 11 14:07:24 UTC 2017
$ cat /proc/version
Linux version 4.10.0-33-generic (buildd@lgw01-22) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #37~16.04.1-Ubuntu SMP Fri Aug 11 14:07:24 UTC 2017
```

**Comment by sokra** [comment]
You should report it to `fsevents`.

**Comment by sheljohn** [comment]
I think _you_ should maybe? 

I'm happy to help, but bouncing build errors to users is not really a nice way of welcoming contributions. Even if this is caused by `fsevents` internally, it's `webpack` that does not build; other packages using `fsevents` (or actually _not_ using it, since this is on Linux) work just fine. 

In fact, given that the error is about not being able to remove a directory with contents using `rmdir`, I suspect this has little to do with `fsevents` itself (why would a package try to remove itself)? Besides, this is at the `postinstall` step of `webpack`, and not that of `fsevents`. 

So I think this issue has to do with `webpack`, and you did not provide any explanation about why it would not; as this issue stands, I have no idea what I should report to `fsevents`, and would really appreciate some guidance.
