### ISSUE TITLE
Webpack fails to build on NTFS filesystems

### ISSUE THREAD

**Issue by sheljohn** [webpack/webpack#5622]
**Do you want to request a *feature* or report a *bug*?**
I am reporting a bug.

**What is the current behavior?**
The latest version of webpack `3.5.5` (as well as the `beta` version) does not build on NTFS filesystems.
Specifically, the error occurs at the `postinstall` step, and seems to be caused by an attempt to remove a directory with contents using `rmdir`.

**If the current behavior is a bug, please provide the steps to reproduce.**
This [gist](https://gist.github.com/sheljohn/6021e522397603ed90df87a9157f4728) reproduces the bug on my machine. Note that this assumes a Linux OS.

**What is the expected behavior?**
The build should not fail.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

```
$ npm --version
5.4.0
$ uname -v
#37~16.04.1-Ubuntu SMP Fri Aug 11 14:07:24 UTC 2017
$ cat /proc/version
Linux version 4.10.0-33-generic (buildd@lgw01-22) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #37~16.04.1-Ubuntu SMP Fri Aug 11 14:07:24 UTC 2017
```

**Comment by sokra** [comment]
Could you try to `npm install fsevents` without webpack?

**Comment by subramn** [comment]
This error occurs to me install.
 uglifyjs-webpack-plugin@0.4.6 postinstall
node_modules\fsevents\node_modules\abbrev\package.json

**Comment by sheljohn** [comment]
@sokra Many thanks for your reply, I will try this tonight when I get home, and update this post then.

**Comment by sokra** [comment]
also compare results with yarn vs npm.

**Comment by piyushwalia** [comment]
Getting the same error

**Comment by sheljohn** [comment]
@sokra I think that's a problem solved :) 

**Installing with `yarn add webpack`**

This installs with a warning regarding `fsevents` being incompatible with the platform.

**Installing with `npm i  webpack --no-optional`**

This works fine on my machine, no error or warning during the build.

**Installing `fsevents` on Linux**

This was off to a bad start, because the package specifies explicitly that it is for OSX only. The installation fails with `npm`, and throws a warning with `yarn` for the same reason: _"incompatible platform"_.

**Comment by NemoStein** [comment]
Since I'm on a Windows 10 I can't confirm the relation with NTFS, but the problem might be with npm itself...
I was able to install webpack with `npm@5.3.0`, but failed with `npm@5.4.1` with a `EPERM`, so the problem must be in `npm@5.4.0`, since that is the version you used.
Marking the installation with `--no-optional` worked.

I think that this issue should be opened again...
