### ISSUE TITLE
Multiple configs with different `target`s only use the first `target`, breaking builds

### ISSUE THREAD

**Issue by tonyhb** [webpack/webpack#5628]
**Do you want to request a *feature* or report a *bug*?**
**Bug**.

**What is the current behavior?**
With multiple configs (`module.exports = [server, client];`) each using *different* targets, webpack 3.5.5 only uses the first target it encounters.

This means that we're unable to create single configs for both the server and client when targeting multiple platforms.

**If the current behavior is a bug, please provide the steps to reproduce.**

Repo: https://github.com/tonyhb/webpack3targetissue

```
git clone git@github.com:tonyhb/webpack3targetissue.git && yarn install && yarn webpack
```

This repo also has a `webpack-beta` branch which simplifies the config and uses webpack@beta:

```
git checkout webpack-beta && yarn install && yarn webpack
```

**What is the expected behavior?**

Webpack 3 compiles the second client configuration using `target: "web"` successfully. Instead, even though `target: "web"` is specified it uses the existing `target: "node"` data from the first exported config.

In the example repo, if you switch the exports in `webpack.config.js` to:
```
module.exports = [client, server];
```
This will compile.  However, it compiled **both** configs for `target: "web"` so running `node static/assets/server.js` produces the following error:

```
foo@debian ~/projects/_scratch/webpackissue (git)-[master] % node static/assets/server.js
Using browser-only version of superagent in non-browser environment
webpack:///./node_modules/superagent/lib/client.js?:62
  throw Error("Browser-only version of superagent could not find XHR");
  ^

Error: Browser-only version of superagent could not find XHR
    at Function.request.getXHR (webpack:///./node_modules/superagent/lib/client.js?:62:9)
    at Request._end (webpack:///./node_modules/superagent/lib/client.js?:684:32)
    at Request.end (webpack:///./node_modules/superagent/lib/client.js?:679:15)
    at eval (webpack:///./src/index.js?:5:89)
    at Object../src/index.js (/home/vagrant/projects/_scratch/webpackissue/static/assets/server.js:15:1)
    at t (/home/vagrant/projects/_scratch/webpackissue/static/assets/server.js:3:6)
    at eval (webpack:///./src/entry.server.js?:2:65)
    at Object../src/entry.server.js (/home/vagrant/projects/_scratch/webpackissue/static/assets/server.js:14:1)
    at t (/home/vagrant/projects/_scratch/webpackissue/static/assets/server.js:3:6)
    at eval (webpack:///multi_./src/entry.server.js?:1:18)
```

This indicates that the second webpack config exported isn't using `target: "node"` as specified.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Node: v8.1.2
OS: Linux debian 4.9.0-0.bpo.2-amd64 #1 SMP Debian 4.9.18-1~bpo8+1 (2017-04-10) x86_64 GNU/Linux
Webpack: 3.5.5 && webpack@beta

**Comment by tonyhb** [comment]
Maybe this is to do with how we parse `package.json` with multiple targets.  [superagent defines a `browser` section of package.json](https://github.com/visionmedia/superagent/blob/master/package.json#L53) which isn't being respected in the second webpack config if the first config's target is `node`.

**Comment by sokra** [comment]
your repo works fine for me.

**Comment by sokra** [comment]
Oh no sorry. It's really weird..

**Comment by tonyhb** [comment]
Thanks, I tried looking into it but had to learn the plugin internals before I could make progress :)
