### ISSUE TITLE
absurdjs loader for webpack

### ISSUE THREAD

**Issue by enigma1** [webpack/webpack#563]
An attempt to utilize the css generator from js files using the [absurd](https://github.com/krasimir/absurd) library. This is work in progress so here is what I've done thus far:

```javascript
// node_modules/absurd-loader/index.js
'use strict';
var AbsurdApi = require('absurd');

module.exports = function(source) {
	this.cacheable && this.cacheable();

  // See webpack/node_modules/webpack-core/lib/NormalModuleMixin.js loaderContext
  var resource =  this.resource;
  var callback = this.async() || this.callback;

  this.addDependency(resource);
  var absurd = AbsurdApi();

  var json = require(resource);
  if( typeof json === 'function') json = json(absurd);

  return absurd.add(json).compile( function(err, css) {
    if(err) return callback(err);
    callback(null, css);
  });
};
```
Then I have my js to css like object to feed absurdjs (eg test.js)

```javascript
module.exports = {
  body: {
    padding: 0,
    marginLeft: "auto",
    marginRight: "auto",
    background: function() {
      return '#FEF0FE';
    }
  }
};
```
In the webpack config file I setup the loader

```javascript
    loaders: [
      { test: /[\/\\]assets[\/\\].+\.js$/, loader: "style!css!absurd" }
    ]
```

I put a comment about the webpack NormalModuleMixin library because initially I had to dig into the source files to figure out which object the loader was referring to. Although that was a fun exercise I hope the documentation could include some extra information for writing loaders. 

If you have any comments to improve it or if you see things I should be doing differently with webpack please let me know

**Comment by shama** [comment]
Closing as this issue appears to be resolved. Please reopen if it has not. Thanks!
