### ISSUE TITLE
webpack.github.io needs an update for module binding

### ISSUE THREAD

**Issue by paulroth3d** [webpack/webpack#5636]
**Do you want to request a *feature* or report a *bug*?**
Bug - but on webpack.github.io and just a doc change.

**What is the current behavior?**

Look, I know the documentation for webpack 2 is up to date,
but this page was quite helpful for people getting started (like me)
and is still referenced from a couple other places on the web.

**(the two lines to fix are in the 'expected behavior' section below)**

Under the 'Binding Loaders' and 'A Config File' sections of
https://webpack.github.io/docs/tutorials/getting-started/
the loader bindings omit the -loader suffix

so you get this error when trying it:
ERROR in ./entry.js
Module not found: Error: Can't resolve 'css' in '/path/to/webpackTest'
BREAKING CHANGE: It's no longer allowed to omit the '-loader' suffix when using loaders.
                 You need to specify 'css-loader' instead of 'css',
                 see https://webpack.js.org/guides/migrating/#automatic-loader-module-name-extension-removed
 @ ./entry.js 2:0-22

(its under the github.io page - which I think is a private repo - so I couldn't do a pull request there)

**If the current behavior is a bug, please provide the steps to reproduce.**

I can provide more steps as needed, but just follow the steps on
https://webpack.github.io/docs/tutorials/getting-started/

It will fail when you get to this command under 'Binding Loaders'
webpack ./entry.js bundle.js --module-bind 'css=style!css'

To fix it, just change it to:
webpack ./entry.js bundle.js --module-bind 'css=style-loader!css-loader'

Same exact issue under 'A Config File' - webpack.config.js under loaders config.

**What is the expected behavior?**

So I know the docs on the webpack 2 documentation side are updated
but this was actually really helpful when getting started (like me)

Just update the page from:
webpack ./entry.js bundle.js --module-bind 'css=style!css'
to
webpack ./entry.js bundle.js --module-bind 'css=style-loader!css-loader'

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by sokra** [comment]
It's correct for webpack 1. But we plan to remove webpack.github.io/docs anyway as it's pretty old.

**Comment by bfred-it** [comment]
@sokra what's the plan for v1 docs? Will they redirect to `js.org`? Will they just disappear? I don't use it anymore but some might. However it _is_ annoying to land on the v1 docs while looking for the current version.
