### ISSUE TITLE
resolve.mainFields doesn't support objects in package.json

### ISSUE THREAD

**Issue by sjbarag** [webpack/webpack#5638]
**Do you want to request a *feature* or report a *bug*?**
This is a bug, though possibly an intentional omission.

**What is the current behavior?**
Sub-arrays in `resolve.mainFields` are completely ignored during module resolution.

Minimum and contrived working example with repro steps: https://github.com/sjbarag/webpack-mwe

**What is the expected behavior?**
A sub-array in `resolve.mainFields` can be used to access properties from an object in a module's `package.json`, as it was in webpack 1.x.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
* Operating System: Mac OS 10.12.6 "Sierra"
* Shell: Bash 4.4.12
* Node: 6.11.2
* npm: 5.3.0
* Webpack: 3.5.6 (though I've tested 2.0 and every minor version since)

**Comment by sokra** [comment]
Bug is here: https://github.com/webpack/enhanced-resolve/blob/master/lib/ResolverFactory.js#L113

There should be `|| Array.isArray(item)`

@webpack-bot move to webpack/enhanced-resolve

**Comment by sjbarag** [comment]
Thanks @sokra! ❤️
