### ISSUE TITLE
CommonsChunkPlugin fails to detect common modules when an entry point has no `import` statement

### ISSUE THREAD

**Issue by fbedussi** [webpack/webpack#5641]
**I'm submitting a bug report**

**The current behavior is that CommonsChunkPlugin fails to detect common modules when an entry point has no `import` statement**

**Steps to reproduce.**

Given these 3 files:
````
//Entry 1

import a from './a'
import b from './b'
a();
b();
````

````
//Entry 2
import a from './a'
a();
````

````
//Entry 3
console.log(1)
````

and given that they are configured as entry points:
````
entry: {
    entry1: path.resolve(__dirname, '/entry1.js'), 
    entry2: path.resolve(__dirname, '/entry2.js'), 
    entry3: path.resolve(__dirname, '/entry3.js'),
  },
````

**Expected behavior**
the expected result is that the common chunk contains module `a` shared by `entry1` and `entry2`, or eventually that a warning or an error is raised because one entry has no `import ` statement.

The actual result, instead, is that no error or warning is issued, but the common chunk does not contain the shared module. 

**Relevant information:**
OS: windows8.1
Node version: 6.11.1
Webpack version: 3.5.5

**Comment by sokra** [comment]
The module is not shared between all chunks. You could tweak it with the `minChunks` option. `minChunks: 2`
