### ISSUE TITLE
[enhancement] Optimize ModuleConcatenationPlugin Variable Assignment

### ISSUE THREAD

**Issue by jambonrose** [webpack/webpack#5642]
**Do you want to request a *feature* or report a *bug*?**
Feature
(I believe; asked about in [gitter](https://gitter.im/webpack/webpack?at=59b0756dee5c9a4c5f3ece93) but received no answer.)

**What is the current behavior?**
This is in the context of ModuleConcatenationPlugin, which is working great (thank you!).

If I export a function as a named export, I can see that the code is concatenated to the first module in the bundle. However, if the function is a default export, then the function is redefined with a different name. 

```javascript
// bundle.js
var myFunction = function() {
    ...
}, index_es = myFunction;
```

`myFunction` is never invoked, but `index_es` is instead. This feels sub-optimal.

Note that uglify renames both, but does not remove the extra variable.

I suspect this is due to the fact that a default export can be named anything, and seeks to avoid potential namespace conflicts.

**What is the expected behavior?**
Defining two variables for the same thing is suboptimal, and should be avoided.

Either:

1. Use the mangled name for the original token (with a comment)
or
2. check the namespace for a token that could conflict, and rename as necessary

**If this is a feature request, what is motivation or use case for changing the behavior?**

Optimization.

Linking to #5191 as it seems to be in the same spirit.

**Comment by kzc** [comment]
`uglify-es` will eliminate the single-use variable in the example.
```
$ cat ex.js

    var myFunction = function() {
        console.log("Hello"); // ...
    }, index_es = myFunction;
    index_es();
    index_es();
    index_es();
```
```
$ bin/uglifyjs -V
uglify-es 3.0.28
```
```
$ bin/uglifyjs ex.js -m -c --toplevel
var o=function(){console.log("Hello")};o(),o(),o();
```
`uglify-es` is used in the beta version of [`uglifyjs-webpack-plugin`](https://github.com/webpack-contrib/uglifyjs-webpack-plugin):

https://stackoverflow.com/a/45088328

**Comment by sokra** [comment]
> Note that uglify renames both, but does not remove the extra variable.

See @kzc comment

> I suspect this is due to the fact that a default export can be named anything, and seeks to avoid potential namespace conflicts.

The algorithm for variable naming detects and avoids conflicts.

> Defining two variables for the same thing is suboptimal, and should be avoided.

It's due to the semantics for `export default`:

``` js
var myFunction = function() { ... };
export default myFunction;
myFunction = null;
```

```
var myFunction = function() { ... };
var index_es = myFunction;
myFunction = null;
```

**Comment by jambonrose** [comment]
Thank you both for the info!
