### ISSUE TITLE
JSONP method access is inconsistent

### ISSUE THREAD

**Issue by rorticus** [webpack/webpack#5643]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When using the `web` target, you cannot load chunks in node when using a fake DOM implementation like [jsom](https://github.com/tmpvar/jsdom). The JSONP function is defined correctly, as `window["webpackJsonp"]` but when it is called it is not accessed from the `window` object, simply `webpackJsonp(`, which is not defined.

Additionally, using the square bracket syntax for accessing the JSONP method will allow the user to use a name with dashes (or other special characters) in it.

**If the current behavior is a bug, please provide the steps to reproduce.**

* Clone https://github.com/rorticus/webpack-jsonp-jsdom
* `npm i`
* `npm run test`

Result is `webpackJsonp is not defined`

**What is the expected behavior?**

The JSONP method should be called in the same way it is defined, as `window["webpackJsonp"]`. This will allow the `web` target to be used in node with a fake DOM.

**If this is a feature request, what is motivation or use case for changing the behavior?**

Using a single target, `web`, and letting us run the unit tests in node (with jsdom) and the browser would be 💯 .

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Node: v7.10.1
Webpack: 3.5.6
OS: macOS 10.12.6

**Comment by sokra** [comment]
It's now consistent in the `next` branch
