### ISSUE TITLE
Webpack externals for dependencies not in consumer environment

### ISSUE THREAD

**Issue by brianfeister** [webpack/webpack#5645]
**Do you want to request a *feature* or report a *bug*?**
**feature**

**If this is a feature request, what is motivation or use case for changing the behavior?**

So, I'm thinking that what I want to do here is completely unsupported and I've already set things up to use babel polyfill's `window.fetch` to get the external script. As such, I have a string that represents a javascript file, is there any way to convert it into a file that webpack recognizes as an actual javascript file in the webpack ecosystem? Something that can be consumed by webpack.
e.g. I'm looking to do externals with an external CDN rather than a library in node_modules a la the externals option, but I realize this doesn't satisfy the need of calling a URL looking for the file. 

https://webpack.js.org/configuration/externals/

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

`webpack@2.5.0`

**Comment by sokra** [comment]
I don't understand the issue. Could you provide a concrete example?

**Comment by brianfeister** [comment]
Thanks for the reply @sokra! I want to be able to pull webpack-compiled javascript files in like this:

`import foo from 'http://myproject.com/api/cdn/foo.js`

^^^ this `foo.js` file has already been compiled for webpack.

(obviously I would use `resolve.alias` to simplify, but that's trivial)

What I want to know is whether or not I can "jam this externally loaded file into webpack or not? I've been looking over the [DLLPlugin](https://webpack.js.org/plugins/dll-plugin/) and trying to figure out if I can use a simple `window.fetch` request to `http://myproject.com/api/cdn/foo.js` and then take the response body, turn the string into a blob, then a javascript file (in browser memory) and then pipe that to the DLLPlugin so that webpack asynchronously picks it up. 

I'm kind of thinking this might be a "no go", but I'm exploring it and wanted to know if DLLPlugin could handle this, or if not, if it could be added.
