### ISSUE TITLE
*.map file cannot be parsed by souce-map package (originalPositionFor) correctly

### ISSUE THREAD

**Issue by xiachaoxulu** [webpack/webpack#5649]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
soucemap mapping incorrectly
**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/xiachaoxulu/sourceMapDemo

**What is the expected behavior?**
incorrectly
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by evilebottnawi** [comment]
Looks like problem in `vue-loader`. Try to update to latest version and feel free create new issue if problem still exists. Thanks!
