### ISSUE TITLE
Webpack-dev-server is not doing hot loading when using react-routerv4

### ISSUE THREAD

**Issue by siddiq-rehman** [webpack/webpack#5656]
Hi,

I am using react-router V4 and when a change is made in one of the js files, the hot loading is not woking. Further it is throwing error as 

![image](https://user-images.githubusercontent.com/22259730/30242528-a53f69fa-95b5-11e7-8c25-bffd4c7bab4f.png)

package.json:

{
  "name": "myui",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "webpack-dev-server --inline --hot"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.2",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "react": "^15.6.1",
    "react-dom": "^15.6.1",
    "react-router": "^4.2.0",
    "react-router-dom": "^4.2.2",
    "webpack": "^3.5.6",
    "webpack-dev-server": "^2.7.1"
  }
}

webpack.config.js:

var path = require("path");
var config = {
   entry: './main.js',
	
	
  output: {
  path : path.join(__dirname, './'),
        filename : 'index.js'
  },
	
   devServer: {
      inline: true,
	  hot:true,
      port: 6900
   },
	
   module: {
      loaders: [
         {
            test: /\.js?$/,
            exclude: /node_modules/,
            loader: 'babel-loader',
				
            query: {
               presets: ['es2015', 'react']
            }
         }
      ]
   }
}

module.exports = config

The file is bundling properly and not errors are found, only problem arises when i am on a route page and when the file is built again.  

Please help.

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by sokra** [comment]
Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md).
