### ISSUE TITLE
Uncaught Error: _registerComponent(...): Target container is not a DOM element.

### ISSUE THREAD

**Issue by iphonic** [webpack/webpack#5657]
I have migrated from webpack 1 to latest webpack version successfully. Everything works fine, but I get the following error everytime, it wasn't there before

> Uncaught Error: _registerComponent(...): Target container is not a DOM element.
>     at invariant (12:44)
>     at Object._renderNewRootComponent (369:310)
>     at Object._renderSubtreeIntoContainer (369:401)
>     at Object.render (369:422)
>     at eval (729:78)
>     at Object.<anonymous> (bundle.js?61622f7508eae70357c3:4906)
>     at __webpack_require__ (bundle.js?61622f7508eae70357c3:20)
>     at Object.<anonymous> (bundle.js?61622f7508eae70357c3:4562)
>     at __webpack_require__ (bundle.js?61622f7508eae70357c3:20)
>     at bundle.js?61622f7508eae70357c3:63

The strangest thing is app runs fine even after getting this error, I have seen solution for the error above I follow the same configuration of loading bundle.js in the end of <body> tag of html. It never works.

What the bug is, why it is coming, is it doing any harm to the app?

Thanks.

**Comment by sokra** [comment]
Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md).
