### ISSUE TITLE
hotDownloadManifest forming invalid URL for hot-update.json request

### ISSUE THREAD

**Issue by estrattonbailey** [webpack/webpack#5658]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
It appears to respect my custom `__webpack_public_path__` configuration, but when generating the url to the `hot-update.json` manifest it doesn't form the URL correctly.

I realize this may be more directly related to webpack-dev-server, but it uses `__webpack_require__.p` and `hotDownloadManifest` which I understand to be a part of webpack core. Happy to send this over there if need be.

**If the current behavior is a bug, please provide the steps to reproduce.**
I've made a [gist](https://gist.github.com/estrattonbailey/08bf51fc07d431a839f3c05a4653138f) with a reduced explanation of my configuration which I believe covers all the pertinent information. My actual setup involves an external CLI I'm developing that merges my project-specific `webpack.config.js` file with higher level configuration like the hot reloading, etc. The gist linked here is essentially the output of that process.

Currently, the javascript *and* css compiles beautifully when starting up. However, when I make a change to a file and webpack requests the manifest, the URL is invalid.

I've debugged this by overriding `XMLHttpRequest.prototype.open` to output the passed params:

<img width="647" alt="screen shot 2017-09-10 at 2 35 23 pm" src="https://user-images.githubusercontent.com/4732330/30251813-4f836702-9635-11e7-885e-f7be8f762a83.png">

As you can see, a request to `https://localhost:300069f6d0acb70194223568.hot-update.json` is an invalid path. Placing the slash where it should be works fine though: `https://localhost:3000/69f6d0acb70194223568.hot-update.json`.

So the actual error looks like this:

<img width="656" alt="screen shot 2017-09-10 at 2 45 44 pm" src="https://user-images.githubusercontent.com/4732330/30251890-ce3da156-9636-11e7-8c2c-72391f892494.png">

**What is the expected behavior?**
It looks like when I set my `__webpack_public_path__` the trailing slash is removed, and then when the `hotCurrentHash` is concatenated, there's no check for a slash and we end up with a invalid URL.

Provided I'm doing everything correctly, maybe a simple regex check for a trailing slash would help [here](https://github.com/webpack/webpack/blob/0257f6c6e41255cf26230c099fb90140f1f0e0bb/lib/JsonpMainTemplate.runtime.js#L28)? 

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
webpack: 3.5.6
node: 8.1.4
macOS: 10.12.6

**Comment by sokra** [comment]
`__webpack_public_path__` should contain a trailing slash. `__webpack_require__.p` is the interal name for `__webpack_public_path__ `.

**Comment by estrattonbailey** [comment]
Thanks for the quick reply!

Any idea if/why something is stripping that trailing slash?

In the screenshot below I'm setting and then logging the `__webpack_public_path__`at `https://localhost:3000/`, and also echoing the global from the console. As you can see, there's no slash on the end.

<img width="353" alt="screen shot 2017-09-11 at 8 44 49 am" src="https://user-images.githubusercontent.com/4732330/30275437-53c7e776-96cf-11e7-9a42-487e5eb74bd1.png">

In case it's helpful, I've got my setup public now. Here's the [webpack config](https://github.com/the-couch/slater-cli/blob/master/lib/webpack.js) (gets merged with my project specific config as mentioned), and the [dev-server setup](https://github.com/the-couch/slater-cli/blob/master/lib/watch.js#L34). It's compiling fine, but can't hot-reload.

My local webpack config:
```javascript
module.exports = {
  target: 'web',
  devtool: 'source-map',
  entry: [
    path.join(__dirname, 'src/scripts/app.js')
  ],
  output: {
    path: path.join(__dirname, 'src/assets'),
    filename: 'index.js'
  },
  module: {
    rules: [
      {
        enforce: 'pre',
        test: /\.js?$/,
        loader: 'standard-loader',
        include: '/src/scripts/app.js',
        exclude: /node_modules/,
        options: {
          parser: 'babel-eslint'
        }
      },
      {
        test: /\.js$/,
        exclude: /node_modules/,
        include: path.join(__dirname, 'src/scripts'),
        use: {
          loader: 'babel-loader'
        }
      }
    ]
  },
  resolve: {
    alias: {
      // ...
    },
  }
}
```

**Comment by estrattonbailey** [comment]
I first monkey patched the `XMLHttpRequest` open prototype to ensure there was a slash (which works fine) and then continued logging to find a breakage point.

I found the same issue during the JSONP request of the updated chunk. [Code here.](https://github.com/webpack/webpack/blob/0257f6c6e41255cf26230c099fb90140f1f0e0bb/lib/JsonpMainTemplate.runtime.js#L17) 

Again, it's outputting a URL like `https://localhost:30000.68dfdec55f250c0fe20f.hot-update.js` and if I manually add a slash in the address bar `https://localhost:3000/0.68dfdec55f250c0fe20f.hot-update.js` it works.

**Comment by estrattonbailey** [comment]
Another note: my combined webpack config's output prop looks like this: 

```javascript
...
  path: __dirname,
  filename: 'index.js',
  publicPath: 'https://localhost:3000'
...
```

Which runs, *provided I leave the overridden `open` handler in place*. However, if I try to add a slash on the end of this `publicPath` value, it again breaks.

```javascript
...
  publicPath: 'https://localhost:3000/'
...
```

The above causes webpack to send requests to `https://localhost:3000//__webpack_hmr` (two slashes instead of one) which doesn't work.

So in this case it's the opposite of what I've been saying above: **it's adding a slash when it doesn't need to** instead of removing one when it doesn't need to.

**Comment by estrattonbailey** [comment]
I think I've narrowed this down now, sorry for the novel 😛. 

Everything webpack-core related works fine, although it *does* appear to remove the trailing slash at the end, regardless of where I put it. That's all fine though because it works, lol.

webpack-hot-middleware, however, was adding a hard-coded prefixing slash to it's request path, and *that* was what broke the HMR process.

I've posted to an issue [over there](https://github.com/glenjamin/webpack-hot-middleware/issues/222#issuecomment-330633898) and I think this one can be closed.

👍

**Comment by popmanhe** [comment]
I have the same issue.

[info] - 2021-06-06T18:58:30.201Z | HTTP GET /**adminmain**.d9f55c450d9a1b1833d5.hot-update.json

I belive the url should be /admin/main.d9f55c450d9a1b1833d5.hot-update.json

And I can see main.d9f55c450d9a1b1833d5.hot-update.json in the folder.  

Any idea how to add slash to the url? 

Thanks.
