### ISSUE TITLE
Local install of webpack on windows breaks module resolution

### ISSUE THREAD

**Issue by JohnNilsson** [webpack/webpack#566]
On windows I can run (same for cmd and msysgit)

```
$ npm install react && webpack --entry react --output-file bundle.js
```

but if I do 

```
$ npm install react webpack && webpack --entry react --output-file bundle.js
```

I get

ERROR in ./~/react/lib/React.js
Module not found: Error: Cannot resolve directory 'c:' in c:!Files\test\node_modules\react\lib
 @ ./~/react/lib/React.js 1:0-118

**Comment by interist32** [comment]
Same habits = same problem. Also have ! in folder name. Think it's not a critical issue :), but need to be fixed. Thanks.

**Comment by SpaceK33z** [comment]
AFAIK this is no longer an issue in webpack 2, so closing, but we can always re-open if it turns out to still be an issue.
