### ISSUE TITLE
Webpack generated Promises don't reject()

### ISSUE THREAD

**Issue by flasaracina** [webpack/webpack#5662]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Sometimes, Webpack generates code that contains Promises that are not rejectable. If an error is thrown in those Promise's body, the Promise is not rejected and thus the error bubbles up to the console, uncatched.

**If the current behavior is a bug, please provide the steps to reproduce.**
Let's lazy-load some module based on the value of an input field (a real world use-case would be a SPA that loads modules based on the current route)...

```javascript

let input = document.createElement('input');

document.body.appendChild(input);
input.addEventListener('change', function(){
    let path;
    path = input.value;
    
    import(`${path}`)
        .then(module => document.body.innerText = module.default)
        .catch(reason => {console.log(reason); /* go to 404 maybe... */})
})

```
if the value of the input field is not a valid module path, it throws. 
It would be nice and clean to let developer decide whether or not to catch that exception.
If the developer doesn't catch it, it will naturally bubble up to the console. That's the expected behaviour of promises, anyway.

**What is the expected behavior?**
If a Promise is rejected it should be catchable.

**If this is a feature request, what is motivation or use case for changing the behavior?**
When working with Promises the developer should be in control about whether or not to catch the possible exception.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Node: 6.11.3
Webpack 3.5.6
OS: Windows 10

**Comment by zemzela** [comment]
#5360

**Comment by sokra** [comment]
@flasaracina could you validate that you are not using `dynamic-import-webpack` and paste the generated code?

**Comment by flasaracina** [comment]
Sorry for the late replay.
I am using the `dynamic-import-webpack` plugin for this example because i am using the `import` function that breaks babel from compiling the code.

However the generated code is as follows:

```javascript
    new Promise(function (resolve) {
        __webpack_require__.e/* require.ensure */(0).then((function (require) {
            resolve(__webpack_require__(329)("" + path));
        }).bind(null, __webpack_require__)).catch(__webpack_require__.oe);
    }
```
__webpack_require__.oe function throws an Error, while the desired behaviour would be that it `rejects` it. Like this

```javascript
    new Promise(function (resolve, reject) {
        __webpack_require__.e/* require.ensure */(0).then((function (require) {
            resolve(__webpack_require__(329)("" + path));
        }).bind(null, __webpack_require__)).catch(reject.bind(reject));
    }
```

Again, I am using the `dynamic-import-plugin`, so maybe it is just the plugin that is generating that buggy code, I don't know. Feel free to close this issue if it is not strictly related to webpack.

Thank you

**Comment by sokra** [comment]
The plugin generates buggy code. Just omit the plugin, you don't need it.
