### ISSUE TITLE
resolve.modules paths order is not respected

### ISSUE THREAD

**Issue by kamilmielnik** [webpack/webpack#5664]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When `import/require`-ing modules, webpack does not respect the order of paths in `resolve.modules` array - `node_modules` always precedes other paths. When I remove dependency manually from `node_modules` directory, and then I run webpack again, the module is resolved as expected.

**If the current behavior is a bug, please provide the steps to reproduce.**
https://github.com/kamilmielnik/webpack-resolve-modules-problem
(please see `README.md` for steps to reproduce)

**What is the expected behavior?**
The following configuration should cause webpack to look in parent directory *before* looking in `node_modules` when importing a module.
```
resolve: {
  modules: [
    path.resolve(__dirname, 'src'),
    path.resolve(__dirname, '..'),
    'node_modules'
  ],
  extensions: [ '.js' ]
}
```

Webpack [docs](https://webpack.js.org/configuration/resolve/#resolve-modules) state:

> If you want to add a directory to search in that takes precedences over node_modules/:
> `modules: [path.resolve(__dirname, "src"), "node_modules"]`

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Latest webpack (see `package.json`), Node 7.9.0, Win 10

**Comment by sokra** [comment]
In your example `abc` is not processed by webpack as you declared it as external.

**Comment by bytesnail** [comment]
do u mean that if there are modules with same name in both `node_modules` & `my own absolute module folder path`, webpack will use the one in `node_modules`? @sokra

**Comment by bytesnail** [comment]
my problem is different, this is the description:

**webpack.config.js**
```
resolve: {
  modules: [path.resolve(SRC_PATH, 'core'), 'common', 'node_modules'],
  alias: {
    'src': SRC_PATH,
    'sys': path.resolve(SRC_PATH, 'sys')
  },
  extensions: ['.js', '.jsx']
},
```
**src/core**
```
core
  -util
  -ui
  ....
```
**app.js**
```
import UTIL from 'util'
console.log(UTIL)
```
the output is not what i defined in core/util, and it is the module in node_modules folder, what is the problem？
by the way, it is ok with webpack 2.0.

**Comment by Diokuz** [comment]
Same problem here with webpack@4

**Comment by Diokuz** [comment]
Oh, looks like my problem is that my package names consist of namespace + name, and my target directory does not have `@namespace/` folder.
