### ISSUE TITLE
Postinstall fails on npm >= 5.4.0

### ISSUE THREAD

**Issue by NemoStein** [webpack/webpack#5665]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Installation falling during postinstall on npm version 5.4.0 or newer (tested in 5.3.0, 5.4.0 and 5.4.1).
May be related to #5622

**If the current behavior is a bug, please provide the steps to reproduce.**
In a empty folder, run `npm install webpack`.

**What is the expected behavior?**
Expected to install correctly

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Node.js v8.4.0
npm v5.4.1
Windows 10 x64

**Comment by egoroof** [comment]
https://github.com/npm/npm/issues/18380

**Comment by NemoStein** [comment]
@egoroof Nice, Thank you!
