### ISSUE TITLE
module.hot.accept not working if pass `module` as an argument

### ISSUE THREAD

**Issue by GProst** [webpack/webpack#5668]
**Do you want to request a *feature* or report a *bug*?**

Bug or kinda

**What is the current behavior?**

I defined my app `init` function which accepts `module` as a parameter. I did it for testing purposes, so I could mock `module` object. But when I start my app with `init(module)` module.hot.accept doesn't catch the updates and page reloads. If I unwrap the code in `init` function and refer to the global `module` variable directly, everything works fine.

**If the current behavior is a bug, please provide the steps to reproduce.**

Do something like this:

```
require('./Root')

function init(module) {
    if (module.hot) {
      module.hot.accept('./Root', () => { console.log('accepted!') })
    }
}

init(module)
```

`module.hot.accept` callback won't be invoked if `./Root` changes

**What is the expected behavior?**

I expect `module.hot.accept` callback to be invoked

**If this is a feature request, what is motivation or use case for changing the behavior?**

Not a feature

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Node: 8.5.0
npm: 5.3.0
Webpack: 3.5.5
Webpack-dev-server: 2.7.1
Chrome browser: 60
MacOS X Sierra

**Comment by sokra** [comment]
This is not statically analysable and not support. You have to use it directly.

**Comment by GProst** [comment]
That is sad, but thank you for a response!

**Comment by GProst** [comment]
For those who is interested I managed to use this workaround:

```javascript
require('./Root')


const moduleProxy = {
  get hot() {
    return module.hot
  },
  hotAccept(callback) {
    // first argument for `accept` method has to be static string
    module.hot.accept('./components/Root', callback)
  }
}

export function init(module) {
  if (module.hot) {
    module.hotAccept(() => { console.log('accepted!') })
  }
}

init(moduleProxy)
```

**Comment by sokra** [comment]
``` js
export function init(accept) {
  accept(() => { console.log('accepted!') });
}
```

``` js
init(cb => if(module.hot) module.hot.accept('./Root', cb));
```
