### ISSUE TITLE
2 times slower builds with HotModuleReplacementPlugin and code splitting, coz of entry bundles invalidation

### ISSUE THREAD

**Issue by lpk3nny** [webpack/webpack#5669]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
![image](https://user-images.githubusercontent.com/4269628/30358737-d765c7fe-9889-11e7-83fa-5156df2b6915.png)
![image](https://user-images.githubusercontent.com/4269628/30358739-db73b644-9889-11e7-87a7-0b9f040a60e6.png)

I'm get 2 times slower builds with HotModuleReplacementPlugin and code splitting, coz of entry bundles invalidation.
The only changes in entry point - its hotCurrentHash.
![image](https://user-images.githubusercontent.com/4269628/30358710-a3ee5c38-9889-11e7-83a5-232bb36978f1.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
https://gist.github.com/lpk3nny/73a539ccdc3fc5246c4bf930519b491d

**What is the expected behavior?**
HotModuleReplacementPlugin invalidates only modified chunks

**Comment by sokra** [comment]
https://webpack.js.org/guides/build-performance/#minimal-entry-chunk
