### ISSUE TITLE
Feature: The new plugin system - use priorities / proxies

### ISSUE THREAD

**Issue by paulpflug** [webpack/webpack#5670]
**Do you want to request a *feature* or report a *bug*?**
feature

Hey, I just read about your new plugin system in webpack blog.

I want to share my experience from building a plugin system real quick.
I came from event-based, over simple hooks to 2d-hooks, meaning you can define an optional priority along your hook to manipulate execution order.
This additional degree of freedom has many advantages. You can reduce the amount of hooks and any plugin author can exactly determine when his hooks will be called, even when interacting with other plugins.  
You can provide predefined priorities like `webpack.lifecycle.OPTIMIZE` which allows relative positioning of the hook `webpack.lifecycle.OPTIMIZE-1` (just before optimize) 
Example syntax:
```js
webpack.registerHook(["processing"]) // adding beforeProcessing, afterProcessing hooks
// without prio
webpack.before.processing.call(async (o) => {
  // stuff 
})
// with predefined prio
webpack.before.processing.call({
  prio: webpack.lifecycle.OPTIMIZE, 
  cb: async (o) => {
  // stuff 
}})
// call all before-processing hooks with obj argument
webpack.before.processing(obj)
```
To optimize calling recurring hooks, the sorting can be cached after the first call.
Here is my implementation: [hooks](https://github.com/SAMjs/samjs/blob/master/src/hooks.coffee)

The other thing, I actually took from mocha, is proxies.
With proxies you can provide rich runtime errors on accessing unavailable properties.
Even something like `you tried to call procesing hook, Did you mean processing?` is possible.

Feel free to close this, if it isn't helping.
Thanks for webpack, it is great!

**Comment by sokra** [comment]
Thanks for your feedback.

yep what you described with priorities is exactly what I also implemented. I just called it `stage` instead of `priority`. Good idea with exposing constants for priorities. I consider doing this.

I have mixed feelings about using Proxies at all, because of the performance hit to take (factor 5). I guess `cannot read property tap of undefined` has to be enough...

**Comment by paulpflug** [comment]
Oh nice, I didn't get that out of the blog posting.

From what I read proxies are slower, about as much slower as promises compared to callbacks :smile:
But a proper error with line number will probably be enough.
