### ISSUE TITLE
Babel 7's template literal syntax in Dynamic require doesn't work

### ISSUE THREAD

**Issue by laggingreflex** [webpack/webpack#5672]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

With babel 7 this doesn't work:

```js
const file = 'test.js'
require(`./${file}`)
```

I think it's because babel 7 transpiles template literals to use `concat` which webpack doesn't understand: 

```
const file = 'test.js'
require('./'.concat(file))
```

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/laggingreflex/webpack-3-require-test

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by sokra** [comment]
see #5674
