### ISSUE TITLE
Support static analysis of "".concat("") in require() calls

### ISSUE THREAD

**Issue by loganfsmyth** [webpack/webpack#5674]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

```
require("foo".concat(obj, ".js"))
```
is treated as an unknown expression during static analysis.

**What is the expected behavior?**

It can be analysed as if it were `"foo" + obj + ".js"`.

**If this is a feature request, what is motivation or use case for changing the behavior?**

Babel 7 is changing the template literal transformation to output this by default because our current approach of `"foo" + obj + ".js"` (default in 6.x, behind "loose" flag in 7.x) or `"foo" + String(obj) + ".js"` (behind "spec" flag in 6.x, deleted in 7.x), aren't spec-compliant and we want to be compliant.

In https://github.com/babel/babel/pull/5791 we changed our spec-compliant mode to use this new form and in https://github.com/babel/babel/pull/6098 we've made it the default for 7.x.

For now, if people want to work with Webpack, they'll have to use `loose: true` on their plugin or else risk getting webpack warnings about unknown expression-based `require` usage.

I'm happy to dig into implementing this, but I wanted to get a general OK first. 

Thoughts?

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by yavorsky** [comment]
@loganfsmyth Thanks for digging into this!
I don't see any reasons why we shouldn't support `String.prototype.concat` along with `+` for strings while providing static analysis.
You've proposed `"foo" + "".concat(obj) + ".js"` and it will solve static analysis issue and spec compatibility, but it will increase the output size + perf impact for additional operations.

If you need some help, I'm glad to help with it.

**Comment by sokra** [comment]
Sure seems reasonable. Send a PR.

Hint: https://github.com/webpack/webpack/blob/master/lib/Parser.js#L288-L298
