### ISSUE TITLE
When I edit under watch mode, it seems it keeps queueing up recompiling

### ISSUE THREAD

**Issue by tom10271** [webpack/webpack#5676]
**Do you want to request a *feature* or report a *bug*?**
Maybe a bug

**What is the current behavior?**
I am writing code in PHPStorm with webpack running in watch mode. I press Cmd + S to save occasionally when I write code. 

**If the current behavior is a bug, please provide the steps to reproduce.**
Once I made a series of changing and head to Terminal to see when will webpack finish compiling I found it keeps compiling for a few times. I think webpack queued up these tasks.

**What is the expected behavior?**
It should compile the last task and clear other tasks if any.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Node 6.10
Chrome 60
Webpack v2.7.0
macOS Sierra 10.12.6

**Comment by sokra** [comment]
I doesn't queue up task. It may recompile directly after it finishes compilation when a change happend while compiling.

**Comment by tom10271** [comment]
Is it possible for webpack to kill the current process but jump to the last one if any received? I guess you know `92% chunk asset optimization` takes tremendous amount of time, right? Mostly when I go to terminal it is stuck on `92% chunk asset optimization` yet once it is done it takes another iteration of compiling. I seldomly kill the watch process and restart again just try to shorten the waiting time

**Comment by bmayen** [comment]
It wouldn't be enough to "jump to the last one it received" because that could miss changes that happened to other files in the previous save. But perhaps possible to queue up changes in watch mode, rerun the entire queue every time there's a save, and only flush it once a build iteration fully completes?

**Comment by sokra** [comment]
> 92% chunk asset optimization takes tremendous amount of time

You probably should disable minimizing while in watch mode.

An incremental compilation while in watch mode should take about 500ms - a few seconds depending on the size of the application. See https://webpack.js.org/guides/build-performance/

**Comment by tom10271** [comment]
I have disabled it. Maybe I need to disable source map too

**Comment by tom10271** [comment]
@bmayen My idea is to squash all tasks(changes) and compile but not handling them one by one. I think it is similar to what you say

**Comment by sokra** [comment]
> My idea is to squash all tasks(changes)

That's the way it works.
