### ISSUE TITLE
Allowing the build to output several versions of a bundle (one with ES 5, one with ES 6)

### ISSUE THREAD

**Issue by eirslett** [webpack/webpack#5677]
**Do you want to request a *feature* or report a *bug*?**
Feature request

**What is the current behavior?**
Only one babel configuration is allowed at a time

**What is the expected behavior?**

It would be great if Webpack had first-class support for this pattern: https://philipwalton.com/articles/deploying-es2015-code-in-production-today/

It would mean building the same entry point twice; one with full es5 transpiling, and another with only a few transforms enabled (object rest spread, flow, jsx etc)

**If this is a feature request, what is motivation or use case for changing the behavior?**

With newer browsers, we can ship untranspiled ES 6 code directly to the user, but there's no easy way to support both new and old browsers by providing different bundles, one ES 6 for new browsers, and one ES 5 for old browsers.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

.

**Comment by kzc** [comment]
Rollup supports producing multiple bundles in a config file, so there's a precedent for this:

https://github.com/rollup/rollup/blob/v0.49.3/rollup.config.js

**Comment by sokra** [comment]
webpack supports the same with the same syntax. export an array of configurations from webpack.config.js.

**Comment by eirslett** [comment]
> webpack supports the same with the same syntax. export an array of configurations from webpack.config.js.

How does this interact with html-webpack-plugin? We use it to inject `<script src` etc. with the correct hashed bundle names. We would need to inject

```
<script type="module" src="bundle-es6-somerandomhash.js"></script>
<script nomodule src="bundle-es5-somerandomhash.js"></script>
```

**Comment by paveleremin** [comment]
@eirslett did you find solution?

**Comment by eirslett** [comment]
No, I didn't...
