### ISSUE TITLE
.mjs support

### ISSUE THREAD

**Issue by graingert** [webpack/webpack#5686]
**Do you want to request a *feature* or report a *bug*?**
Feature request

**What is the current behavior?**
Can't import .mjs files without extra configuration.

**What is the expected behavior?**
.jsm nodules are supported 'out of the box' also some changes to the module parsing/resolution apply:

* require, define and module.exports are ignored and passed through unchanged.
* can only import cjs exports as esm default export
* can only import using the file file extension. (All imports must be URLs)

**If this is a feature request, what is motivation or use case for changing the behavior?**
Comparability with nodejs
**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by TheLarkInn** [comment]
Are you referring to .mjs?

**Comment by graingert** [comment]
@TheLarkInn yes

**Comment by sokra** [comment]
This will be added for webpack 4.

**Comment by sokra** [comment]
Current status:

* [x] require, define and module.exports are ignored and passed through unchanged.
* [ ] can only import cjs exports as esm default export
* [x] can only import using the file file extension. (All imports must be URLs)

**Comment by JasonJJFS** [comment]
Hi all, I can see this feature is going to imminently land, any ETA on this?

Many thanks

**Comment by graingert** [comment]
@JasonJJFS it's going to land with many other features in one go as webpack 4: https://github.com/webpack/webpack/milestone/15

**Comment by sokra** [comment]
Current status:

* [ ] `import("cjs")` should return a fake namespace object and emit an error
