### ISSUE TITLE
when entry is an array and compile with nodejs api, the output file will generate some repetitive code

### ISSUE THREAD

**Issue by dancon** [webpack/webpack#5690]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

1.  Clone the git [Reproduction Git](git@github.com:dancon/webpack-issues-reproduction.git)

```
git clone git@github.com:dancon/webpack-issues-reproduction.git
cd webpack-issues-reproduction/issue-1
yarn start
```
2. then we can find some repetitive code in build/bundle.js

> the problem is caused by  webpack nodejs api, but the problem gone when i use command line `webpack` directly.

```
"use strict";
class Test {
  run(){
    console.log('this is Test class run method')
    console.log('success compile')
    const obj = {}
    obj.greeting('React')
  }
}

/* unused harmony default export */ var _unused_webpack_default_export = (Test);

/***/ })
/******/ ]);')
    const obj = {}
    obj.greeting('React')
  }
}
```

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by sokra** [comment]
Call either `run` or `watch` never both.
