### ISSUE TITLE
webpack shows distorted entries after compiling large entries 

### ISSUE THREAD

**Issue by muralikr** [webpack/webpack#5695]
**Do you want to request a *feature* or report a *bug*?**
A Bug

**What is the current behavior?**
Our application has ~2K modules with multiple entries. After compiling these entry points, webpack logs given entries + distorted entries in output and emits duplicate events like `after-compile`. With this, our custom plugins are executed twice or thrice for each entry point and causing unexpected issues.

Here is one such output from webpack
```
Hash: b09d9f200c42ca4a76dbf8cc66d5e8b587fba22bdd218de191690012cb805ea514138c6d9e3071acbee62c6b402563b345eeeb7ce7ec3db9b3fcb1aeaf11a86131ea1f00ab71
Version: webpack 3.6.0 / grunt-webpack 3.0.2
Child
    Hash: b09d9f200c42ca4a76db
    Time: 98314ms
                             Asset     Size  Chunks                    Chunk Names
                foo_app.bundle.js  14.7 MB       0  [emitted]  [big]  foo_app
         foo_app_vendor.bundle.js  5.81 MB       1  [emitted]  [big]  vendor
Child
    Hash: f8cc66d5e8b587fba22b
    Time: 101489ms
                                  Asset     Size  Chunks                    Chunk Names
                    bar_app.bundle.js  10.6 MB       0  [emitted]  [big]  bar_app
         bar_app_vendor.bundle.js  9.81 MB       1  [emitted]  [big]  vendor

## Following are distorted chunks which are not in config ##
Child
    Hash: dd218de191690012cb80
    Time: 19155ms
     4 assets
Child
    Hash: 5ea514138c6d9e3071ac
    Time: 11085ms
     3 assets
Child
    Hash: bee62c6b402563b345ee
    Time: 10084ms
     3 assets
Child
    Hash: eb7ce7ec3db9b3fcb1ae
    Time: 1359ms
     2 assets
Child
    Hash: af11a86131ea1f00ab71
    Time: 13631ms
     4 assets
```

On debugger mode, obj in [lib/Stats.js](https://github.com/webpack/webpack/blob/7fe03718f2e5eb554ec3e76eb0536fe2aa56c2a8/lib/Stats.js#L600) file has following value:
```js
{ errors: [],
  warnings: [],
  hash: 'af11a86131ea1f00ab71',
  time: 13631,
  assetsByChunkName:
   { bar_app: 'bar_app.bundle.js',
     vendor: 'bar_app_vendor.bundle.js' },
  assets: [],
  filteredAssets: 4,
  children: [],
  name: undefined } // wonder why name is undefined here.
```
**If the current behavior is a bug, please provide the steps to reproduce.**

Sample webpack config: https://gist.github.com/muralikr/57a9667b6570027d171579447f7dfa6e
We are using custom loader and plugin in our config. Both of them does only synchronous tasks (like modifying source of few modules, processing and storing as files).

**What is the expected behavior?**
Webpack should emit plugin related events only once per entry. If it gets into any error state, it should throw error and suspend compiling.
 
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
node -- v6.10.0
webpack -- 3.5.6
Mac OSX Sierra

**Comment by sokra** [comment]
Never seen this. Probably caused by your configuration. `console.log` the resulting config.

**Comment by muralikr** [comment]
Resulting config from https://gist.github.com/muralikr/57a9667b6570027d171579447f7dfa6e (in JSON format): https://jsonblob.com/ef000341-9d71-11e7-aa97-45ffa05a7fc0

**Comment by sokra** [comment]
Have you tried running without grunt-webpack?

**Comment by muralikr** [comment]
Yes. We are observing same issue without grunt-webpack. It doesn't happen if we try to compile 1-2 entries. When we compile 7 entries (with lot of common modules), it happens frequently.

**Comment by sokra** [comment]
Could you create a minimal repro repo for this issue?

**Comment by muralikr** [comment]
Sorry for the delayed response. With further debugging, I narrowed down issue to generated files in our project.

In our grunt tasks, we are auto-generating few files (creating unique hashes etc..) before `grunt-webpack` task. These auto-generated files are imported in our source code and bundles. I found that these auto-generated files are triggering new `watch` cycle (as modified files) and recompilation of bundles.

If I add a delay of 10 seconds between file creation and webpack, this doesn't happen. I can always reproduce this in our project. I am trying to create the same in an example application. Will update here after it is ready in few days.

**Comment by muralikr** [comment]
I am able to reproduce the issue using this repo (https://github.com/muralikr/beginning-webpack/tree/debugWebpack). After cloning and installing dependencies, if you run `grunt`, you get output like below:

```
$ grunt
Running "generate-file" task
>> Created new file

Running "webpack:dev" (webpack) task
In watch-run event
In after-compile event
Hash: 05d7307b5c8e3ba8d0ac
Version: webpack 3.6.0 / grunt-webpack 3.0.2
Time: 1754ms
    Asset     Size  Chunks                    Chunk Names
bundle.js  1.99 MB       0  [emitted]  [big]  main
  [11] ./node_modules/react-dom/lib/ReactUpdates.js 9.53 kB {0} [built]
  [14] ./node_modules/react/lib/ReactElement.js 11.1 kB {0} [built]
  [16] ./node_modules/react/lib/React.js 4.96 kB {0} [built]
  [49] ./node_modules/react/react.js 56 bytes {0} [built]
  [80] multi ./app.js 28 bytes {0} [built]
  [81] ./app.js 553 bytes {0} [built]
  [98] ./hello.js 491 bytes {0} [built]
  [99] ./node_modules/react-dom/index.js 59 bytes {0} [built]
 [100] ./node_modules/react-dom/lib/ReactDOM.js 5.14 kB {0} [built]
 [180] ./node_modules/react-dom/lib/findDOMNode.js 2.46 kB {0} [built]
 [181] ./node_modules/react-dom/lib/renderSubtreeIntoContainer.js 422 bytes {0} [built]
 [182] ./node_modules/react-dom/lib/ReactDOMUnknownPropertyHook.js 4.32 kB {0} [built]
 [183] ./node_modules/react-dom/lib/ReactDOMNullInputValuePropHook.js 1.37 kB {0} [built]
 [185] ./global.js 57 bytes {0} [built]
 [186] ./generated_file.js 47 bytes {0} [built]
    + 172 hidden modules

Running "wait:pause" (wait) task
Start waiting 1000ms
In watch-run event
In after-compile eventn
Hash: 05d7307b5c8e3ba8d0ac
Version: webpack 3.6.0 / grunt-webpack 3.0.2
Time: 44ms
 1 asset
 [186] ./generated_file.js 47 bytes {0} [built]
    + 186 hidden modules
In watch-run event
In after-compile eventn
Hash: 05d7307b5c8e3ba8d0ac
Version: webpack 3.6.0 / grunt-webpack 3.0.2
Time: 22ms
 1 asset
 [186] ./generated_file.js 47 bytes {0} [built]
    + 186 hidden modules
In watch-run event
In after-compile eventn
Hash: 05d7307b5c8e3ba8d0ac
Version: webpack 3.6.0 / grunt-webpack 3.0.2
Time: 37ms
 1 asset
 [186] ./generated_file.js 47 bytes {0} [built]
    + 186 hidden modules
In watch-run event
In after-compile eventn
Hash: 05d7307b5c8e3ba8d0ac
Version: webpack 3.6.0 / grunt-webpack 3.0.2
Time: 24ms
 1 asset
 [186] ./generated_file.js 47 bytes {0} [built]
    + 186 hidden modules
>> Done waiting after 1001ms

Done.
```

**Comment by muralikr** [comment]
@sokra When you get time, can you please clone https://github.com/muralikr/beginning-webpack/tree/debugWebpack and take a look at this issue?
