### ISSUE TITLE
how can i get the 'contenthash' in the 'compilation'?

### ISSUE THREAD

**Issue by bingqichen** [webpack/webpack#5696]
Hi all:
I am developing a webpack plugin, I need the 'contenthash' from 'compilation', but now I have a problem, I can't find a way to get it. Can you give me a suggestion?
Thank you!

**Comment by sokra** [comment]
There is no contenthash in compilation. You may want to use `chunkhash` which is `chunk.hash`. But keep in mind that it's created late in the whole process.
