### ISSUE TITLE
Allow empty plugin in plugins list

### ISSUE THREAD

**Issue by GProst** [webpack/webpack#5699]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

If we pass empty value (`false`, `null`, `undefined`) to `plugins` list in webpack.config like this:

```javascript
plugins: [
  null
]
```

We will get error like this:

```shell
TypeError: Cannot read property 'apply' of null
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Not a bug

**What is the expected behavior?**

Webpack builds bundle without error thrown, as if we didn't apply any plugins.

**If this is a feature request, what is motivation or use case for changing the behavior?**

It would be much convenient in my opinion to write conditional configs with this feature implemented. For instance when we need some plugin to be applied only when `NODE_ENV === 'production'`. I know, that we can store `config` in JS variable and conditionally `push` plugins to its plugins list, but it is less convenient.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Webpack: 3.5.5
Node: 8.5.0
MacOS

**Comment by sokra** [comment]
`null` is not a valid plugin.

You can use this:

``` js
plugins: [
  null
].filter(Boolean)
```

This removes all non-truthy values.

**Comment by pardoman** [comment]
Another option:

```javascript
function NothingPlugin() {
    this.apply = function(){};
}

plugins: [
  someBool ? new NothingPlugin() : new TheRealPlugin({ ... })
]
```

**Comment by vintprox** [comment]
ew

**Comment by sndmails2arun** [comment]
if you need to conditionally add a plugin (I assume this is the reason why you ended up with a null) you could use the spread operator 

```
plugins : [
    new Plugin1(),
    ... ( yourCondition ? [ new ConditionalPlugin()] : [ ] ),
    new Plugin2()
]
```
