### ISSUE TITLE
Strict module names option

### ISSUE THREAD

**Issue by MMeent** [webpack/webpack#5700]
**Type of issue**
Feature request: Strict module resolving / standard-compliant module resolving as a setting.

**Current behavior?**
currently `import "./module-name"` checks './module-name' and './module-name/index.js' for resolving, and `import "module-name"` is also valid.

**Expected behavior?**
I'd like a "strict" method for resolving modules, as per [browser support](https://jakearchibald.com/2017/es-modules-in-browsers/#bare-import-specifiers-arent-currently-supported)/[specification](https://html.spec.whatwg.org/multipage/webappapis.html#resolve-a-module-specifier), which only allows absolute imports (`/path/to/js/file.js` starting from one/more root folders, error on conflicting names), relative imports (`./path/to/js/file.js`) and url imports (`http(s)://host:port/path/to/file.js`).

**Motivation**
As per the loader standard, only absolute paths, relative paths and valid urls are valid module names for import. Relative paths will be resolved by the client to an absolute path, and absolute paths will be requested from the relevant server. This means the server will eventually be the one resolving to modules. Currently, using webpack, this is done using Node's resolving algorithm, which resolves `name` to `name` and `name/index.js`. I think there should be a configuration option to specify the full resolving of modules (more strongly than the current aliases object, it currently extends nodes' resolving, but you cannot restrict the resolving).

**Other relevant information.**
Stale [WhatWG loader specification project](https://github.com/whatwg/loader) ([WIP spec](https://whatwg.github.io/loader/#browser-loader-prototype-@@resolve)) has not been updated in ~ 13 months. Next source of truth is the [HTML spec](https://html.spec.whatwg.org/multipage/webappapis.html#integration-with-the-javascript-module-system) which has better specified the resolving algorithm and specifically disallows anything that is not a valid URL or does not start with either `/`, `./` or `../`.

**Comment by sokra** [comment]
You can configure the resolver to only allow relative imports:

``` js
resolve: {
  descriptionFiles: [], // ignore package.json
  mainFiles: [], // don't try index.js in directories
  extensions: [], // don't try to append extensions
  modules: [] // don't resolve non-relative requests
}
```

This probably renders some npm modules non-functional.

**Comment by MMeent** [comment]
Thank you, this is exactly what I was looking for.

Note: the resolve.mainFiles option is not specified in the [configuration cheat sheet](https://webpack.js.org/configuration/).
