### ISSUE TITLE
jsonForToString flag into the webpack cli

### ISSUE THREAD

**Issue by jkanczler** [webpack/webpack#5704]
**Do you want to request a *feature* or report a *bug*?**
***feature***

**What is the current behavior?**
Currently when using webpack cli with the json flag, the cli is using the stats.toJson method without passing forToString parameter, so it'll be false. There's no option to get a json for to string by the cli.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
To have a --jsonForToString flag, so the cli will use stats.toJson(outputOptions, true) to generate the json output.

**If this is a feature request, what is motivation or use case for changing the behavior?**
A build tool like [webpack-vsts-extension](https://github.com/Dealogic/webpack-vsts-extension) doesn't need the full json. But still, after analyzing the object the build tool would like to honor the output settings that was provided originally by the user, so we won't pollute the console with unnecessary information when the tool is using the static jsonToString of the Stats.js.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by evilebottnawi** [comment]
@webpack-bot move to `webpack/webpack-cli`
