### ISSUE TITLE
npm install of webpack 3.6.0 fails because of uglifyjs-webpack-plugin@0.4.6 postinstall

### ISSUE THREAD

**Issue by ea167** [webpack/webpack#5705]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
npm install of webpack fails on a fresh install because of uglifyjs-webpack-plugin@0.4.6 dependency

**If the current behavior is a bug, please provide the steps to reproduce.**

From a fresh install, with npm cache cleaned, etc.
When I try to install webpack (v3.6.0) I get the error: 

> uglifyjs-webpack-plugin@0.4.6 postinstall /root/EVGIT/audio-bo-client/node_modules/webpack/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

module.js:491
    throw err;
    ^

Error: Cannot find module '/root/EVGIT/audio-bo-client/node_modules/webpack/node_modules/uglifyjs-webpack-plugin/lib/post_install.js'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:598:3

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! uglifyjs-webpack-plugin@0.4.6 postinstall: `node lib/post_install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the uglifyjs-webpack-plugin@0.4.6 postinstall script.

**What is the expected behavior?**
Install works

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

npm 5.3.0 on centos7, webpack v3.6.0

**Comment by sokra** [comment]
@webpack-bot move to webpack-contrib/uglifyjs-webpack-plugin

Could we backport the removing of the post install script to the 0.4 version?

**Comment by ZLTM** [comment]
I'm encountering this error while doing npm install on windows 10, no problem on ubuntu 19

**Comment by evilebottnawi** [comment]
Please migrate on `terser-webpack-plugin`
