### ISSUE TITLE
Webpack build failing to compile does not successfully exit the process on Linux

### ISSUE THREAD

**Issue by josemaia** [webpack/webpack#5710]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When a build fails on Linux due to an invalid import, my build should throw the error to console and perform a process.exit(1). Instead, it gets stuck.

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Have a npm run build through webpack
2. Have a project with an invalid import (e.g. case sensitive import of "./Breadcrumb.js" fails on Linux because your file is actually named breadcrumb.js)
3. The error is caught and shown in the console via a console.log. The next step being a process.exit(1); does not actually exit, making the process eternally open (can ctrl-c if via tty, stops the whole build agent if in CI)

Build.js => https://gist.github.com/josemaia/f3eb6e0439991ff51ef93e82fbdfb38d
Issue happens on l.100

Webpack config => https://gist.github.com/josemaia/b26c8b1d74bbae1d1caacdc71d7c8b09

If you don't want to go through the whole thing:
**bail** is set to true.
If I set it to false, the build doesn't get stuck!

**What is the expected behavior?**

Build failing correctly stops the process, as happens on Windows.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
npm -v : 3.10.10
node: 6.11.3
OS: Ubuntu 16.04 LTS
Webpack version: 2.7.0

**Comment by sokra** [comment]
Weird. Not sure how to influence the behavior of `process.exit` at all.

You can try to following things:

* Updating node.js version.
* Attach a debugger and press "pause" when it gets stuck.
* Attach a debugger, break on the process.exit and follow control flow from there.

**Comment by evilebottnawi** [comment]
@josemaia problem still exists with webpack@3 or webpack@4?

**Comment by josemaia** [comment]
Unfortunately I am not in a position to check easily. Feel free to close the issue if you cannot reproduce.

**Comment by evilebottnawi** [comment]
@josemaia feel free to reopen/create new issue/feedback if problem happens again. Thanks!
