### ISSUE TITLE
webpack tree-shaking can't handle code form node_modules

### ISSUE THREAD

**Issue by z2014** [webpack/webpack#5712]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**

I'm now working on webpack@3.4.1, and I try to use tree-shaking, all is normal, but when I install mathjs from npm, and I use this
```
import { log } from 'mathjs'
console.log(log(10000,10))
```
when I open bundle.js, besides "log" method, others also are bundled in bundle.js,
i wonder if tree-shaking can handle node_modules.
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
I expected bundle.js only include log method
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
node@6.11.0, webpack@3.4.1

**Comment by kzc** [comment]
It's difficult to perform dead code elimination on this module as it contains [dynamic bindings](https://github.com/josdejong/mathjs/blob/b4a4cb36d33125155a517526c55dd3fadf9abe67/index.js#L26-L38) - the code has to be run to form the exports:

You could try your luck with [prepack](https://github.com/facebook/prepack).

**Comment by z2014** [comment]
I mean if your dependencies (like antd, react...) don't support es6 import/export, the tree-shaking don't work. If that, the tree-shaking seems not so effective as i image

**Comment by sokra** [comment]
Tree Shaking is only available for EcmaScript modules not for CommonJs

**Comment by a-x-** [comment]
How can I create ES libraryTarget library and use it from node_modules with tree-shaking?

**Comment by yeziyou** [comment]
@sokra , I have the same question as @a-x- .
looking forward to reply.
