### ISSUE TITLE
[Feature] Allow loaders to add metadata to modules

### ISSUE THREAD

**Issue by NeekSandhu** [webpack/webpack#5715]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Loader chains are pretty much stateless, if a loader mutates content significantly but next loader needs some critical information (which is now tampered) to do it's thing, it'll have hard time.

**If the current behavior is a bug, please provide the steps to reproduce.**
NA

**What is the expected behavior?**
Take `css-loader` and config `use: ExtractTextPlugin.extract({use: 'css-loader'})` for example.
 If `css-loader` could add some metadata when it's running, something like `meta: {rawContent: "body {margin: 0;}", sourceMap: {...}}` and is accessible by subsequent loaders, ExtractTextPlugin in this example, they won't have to run mini-compilers to extract the content, since it's now directly accessible.
 
**If this is a feature request, what is motivation or use case for changing the behavior?**
See *What is the expected behavior?*

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
NA

**Comment by NeekSandhu** [comment]
PS: I'm aware of `this.data` on `LoaderContext` but that has short life and by design is only consumable within private context. This proposal is about attaching metadata on `Module` object, something like `Module.loaderMetaData` etc. and is persistent for at least one compilation cycle.

**Comment by michael-ciniawsky** [comment]
You can pass a third argument, ideally an `{Object}`

```js
function loader (src, map, meta /* <= */) {
 const cb = this.async()
 ... 
 return cb(err, src, map, meta /* <= /*)
}
```

**Comment by NeekSandhu** [comment]
Great. It'd beautiful if documentation is fixed a bit.

As on this page: https://webpack.js.org/api/loaders it doesn't say anything about third argument.

And second, at https://webpack.js.org/api/loaders/#this-callback it says third argument is `AST` although it can be anything really.

**Comment by sokra** [comment]
@webpack-bot move to webpack/webpack.js.org

> Great. It'd beautiful if documentation is fixed a bit.
> 
> As on this page: https://webpack.js.org/api/loaders it doesn't say anything about third argument.
> 
> And second, at https://webpack.js.org/api/loaders/#this-callback it says third argument is AST although it can be anything really.

Yep you should send a PR to the documentation @NeekSandhu.
