### ISSUE TITLE
Refactor Unit Tests to Jest

### ISSUE THREAD

**Issue by ev1stensberg** [webpack/webpack#5719]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Right now, the Unit Tests are using a mix between `mocha` and `should` to unit test

**What is the expected behavior?**
Painless unit testing within one library
**If this is a feature request, what is motivation or use case for changing the behavior?**
Cleaner code base as well as less dependencies

What are your thoughts about this? I'm happy to refactor into Jest if wanted

**Comment by sokra** [comment]
see https://github.com/webpack/webpack/pull/5644
