### ISSUE TITLE
Directory option for `resolve.mainFiles`

### ISSUE THREAD

**Issue by GProst** [webpack/webpack#5720]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

For `resolve.mainFiles` config option we currently may set only static string value.

**If the current behavior is a bug, please provide the steps to reproduce.**

Not a bug.

**What is the expected behavior?**

May be it would be useful if we could use something like `'[directory]'` as a value. So it would be possible to resolve files such as `/path/to/foo/foo.js` like `import '/path/to/foo'`.

**If this is a feature request, what is motivation or use case for changing the behavior?**

I just think it could be useful.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

MacOS
Node 8.5.0
Webpack 3.5.5

**P.S.** Thank you for your priceless work on `webpack`!

**Comment by TheLarkInn** [comment]
This could be accomplished through a custom Resolver Plugin. This behavior may already exist commonly used by React Developers. (Although I can't remember the plugin name!)
Also see this thread for more information. https://github.com/webpack/webpack.js.org/issues/1458

**Comment by sokra** [comment]
https://www.npmjs.com/package/directory-named-webpack-plugin
