### ISSUE TITLE
Request __webpack_public_path__ be a list of fallback hosts [cdn1, cdn2, ..., webserver]

### ISSUE THREAD

**Issue by micahcatlin** [webpack/webpack#5722]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
`__webpack_public_path__` is a string which is used as a base for computing the URL of dynamically loadable code chunks.
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
I would like the generated chunk loader (in the in initial chunk) to include logic which accepts `__webpack_public_path__ = ["host1/path/", "host2/path", ...]` flexibly, and fallback gracefully at runtime if host1/path/_chunk_ cannot be loaded.

**If this is a feature request, what is motivation or use case for changing the behavior?**
I would like to have a web app which attempts to load its code chunks from a CDN, but which will quietly fall back to fetching the code from the application server if the CDN is unavailable.  I would like to use identical chunk file source in both situations, so the same computed SRI values are valid.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

I've made a patch to JsonpMainTemplatePlugin.js which demonstrates the desired behavior and seems to be working in my application, which will be referenced below.

I'm not sure if this behavior is better implemented as an new distinct plugin, or as increased complexity in the default Jsonp loader.

**Comment by sokra** [comment]
You can implement this in your application code:

``` js
const list = ["url1", "url2", "url3"];

function fallbackImport(fn) {
  const i = 0;
  const next = () => {
    __webpack_public_path__ = list[i];
    return fn().catch(e => {
      if(++i > list.length) throw e;
      return next();
    });
  };
  return next();
}

fallbackImport(() => import("module")).then(module => ...);
```

or see https://github.com/webpack/webpack/issues/5021#issuecomment-306754750 for another solution.

**Comment by evilebottnawi** [comment]
Answer above, close due inactivity
