### ISSUE TITLE
Can I load modules dynamically with expressions?

### ISSUE THREAD

**Issue by zaclummys** [webpack/webpack#5725]
I'm using ES6 Modules to build a lazy view-loader, but I can't load the views dynamically.

### Example
```js
class {
    ...
    importView (url) {
        import(url).then(...);
   }
}
```
When it runs, **webpack-cli** says _Critical dependency: the request of a dependency is an expression_.
And the **browser** says _Uncaught (in promise) Error: Cannot find module 'views/home'._

How can i solve this problem?

**Comment by sokra** [comment]
Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md).
