### ISSUE TITLE
Source map validation warning/errors when using UglifyJsPlugin

### ISSUE THREAD

**Issue by OliverJAsh** [webpack/webpack#5728]
The examples I've used are collected into a project for debugging purposes here: https://github.com/OliverJAsh/webpack-uglifyjs-source-map-issue

---

Given:

``` json
// package.json
{
  "private": true,
  "dependencies": {
    "webpack": "^3.6.0"
  }
}
```

``` js
// webpack.config.js
const webpack = require('webpack');

module.exports = {
    devtool: 'source-map',
    entry: {
        main: ['./test.js'],
    },
    output: {
        path: `${__dirname}/target`,
        filename: 'main.js',
    },
    plugins: [
        new webpack.optimize.UglifyJsPlugin({
            sourceMap: true,
        }),
    ],
};
```

``` js
// test.js
import foo from './foo';

foo.bar();

const x = 1;
const y = x + 1;
console.log(y);
```

``` js
// foo.js
module.exports = {
    bar: function () {},
};
```

When I run `webpack` and use https://sourcemaps.io/ to validate the source map, I get 83 warnings:

![image](https://user-images.githubusercontent.com/921609/30927998-2115f62a-a3b2-11e7-9949-2a291f70a1f4.png)

If I switch from using the default import to importing the whole module:

``` js
// test.js
import * as foo from './foo';

foo.bar();

const x = 1;
const y = x + 1;
console.log(y);
```

… and then I validate the source map, I get 1 error and 81 warnings:

![image](https://user-images.githubusercontent.com/921609/30928084-71246160-a3b2-11e7-924b-da6ca9fbab1a.png)

If I remove `UglifyJsPlugin` altogether, the source map has no warnings or errors.

This could be the validator reporting false positives, although I believe I am also seeing issues resolving stack traces against the source map, so I have reason to believe these are not false positives.

**Comment by sokra** [comment]
@webpack-bot move to webpack-contrib/uglifyjs-webpack-plugin

**Comment by sokra** [comment]
Hey @webpack-bot still asleep?
