### ISSUE TITLE
Context dependencies should support resource queries

### ISSUE THREAD

**Issue by anuraaga** [webpack/webpack#5730]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

There is no way to pass a resource query when using context dependencies via `require.context`. In other words, `this.resourceQuery` will never be set inside a loader when using `require.context`.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

`this.resourceQuery` should be set in a loader for something like the following:

```js
const ctx = require.context('images?foo=bar', false, /\.jpg$/);
ctx('./a.jpg');
```

I have a test case and a proposed fix in my fork here - https://github.com/anuraaga/webpack/pull/1
If the approach seems reasonable, I would be happy to move the PR to this repo for tweaks/submission, otherwise someone more familiar with the webpack design should probably take over as I just stumbled to that solution :)

**If this is a feature request, what is motivation or use case for changing the behavior?**

Some loaders (e.g. sharp-loader) use `this.resourceQuery` to enable certain behavior. This functionality cannot be used with context dependencies due to having no way to set a resource query. There doesn't seem to be any reason context dependencies should not support this feature as the only difference compared to a normal dependency is multiple files are resolved at the same time and placed in a map.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

All

**Comment by sokra** [comment]
Yep, send a PR

**Comment by ogonkov** [comment]
Provided PR doesn't seems working for imports like this

`../foo/${bar}.foo?my-query`

Should i make PR to support queries like the one above?

**Comment by ogonkov** [comment]
`resourceQuery` make it way to `regExp` here, is it expected behaviour, @sokra ?

https://github.com/webpack/webpack/blob/d2aca5638c2269fd00ef30e570953b3dc93711b7/lib/dependencies/ContextDependencyHelpers.js#L100

**Comment by evilebottnawi** [comment]
@ogonkov Problem still exists?

**Comment by ogonkov** [comment]
It seems working properly as of `webpack@4.26.1`

I put a loading of SVGs via `import()`, and using query that switch sprite/file loaders affect that import correctly, by producing sprite and separate chunks respectively.

I think this issue was resolved, not sure when.

**Comment by evilebottnawi** [comment]
Yes, i think we should fix it, feel free to send a PR

**Comment by ogonkov** [comment]
It's fixed

**Comment by evilebottnawi** [comment]
With `const ctx = require.context('images?foo=bar', false, /\.jpg$/);` looks no

**Comment by evilebottnawi** [comment]
bump

**Comment by jclow-sift** [comment]
So just to clarify, the original request is _specifically_ about `require.context` not `import` or `import()` The latter two have worked with resource queries for a while, but the require function returned by `require.context` has no facility for passing the resource query along. 

So, for example, let's say we want to write a rule to use a different svg loader based on the resource query...something like this:

```
{
  test: /\.svg$/,
  resourceQuery: /sprite/,
  use: ['svg-sprite-loader', 'svgo-loader'],
},
```

With that rule, this import of foo.svg ends up using that set of loaders:
`import './foo.svg?sprite';` 

but something like this does not:
```
const requireSprites = require.context('./?sprite', false, /\.svg$/);
requireSprites.keys().forEach(requireSprites);
```

**Comment by jclow-sift** [comment]
For anybody landing here after struggling with this and `require.context`, take a look at https://webpack.js.org/concepts/loaders/#inline for possible solutions

**Comment by alexander-akait** [comment]
Original problem was resolved, if you still have a problem, please create a new issue, other issue https://github.com/webpack/webpack/issues/12900, `test` is preferred over `resourceQuery`, so if you have intersection for `test`, you need specify `resourceQuery` for both rules, i.e. ` resourceQuery: /raw/,` and ` resourceQuery: /^(?!\?raw$).*/,`
