### ISSUE TITLE
JSON loader to ES6 imports [feature request]

### ISSUE THREAD

**Issue by damianobarbati** [webpack/webpack#5734]
**Do you want to request a *feature* or report a *bug*?**
Feature: convert JSON imports to ES6 imports by default.

**What is the current behavior?**
```
import { name } from 'package.json';
```
Here you get the name variable from package.json, but since it was not converted to ES6 imports first you will not achieve tree shaking and any babel feature on it: in the transpiled and minified source you can see the full package.json even if only the name was imported.

**What is the expected behavior?**
Any `import name from 'filename.json'` should transform the latter in a set of ES6 "export" statements, one for each first-level key found (nothing else is needed since destructuring imports is not allowed anyway in ES6).
If user is not "namely importing" then assume `import * as name` to get the full file like the current behaviour (backward-compatible).
If the user is "namely importing" then convert the JSON file to ES6 export statements to allow tree shaking.

**If this is a feature request, what is motivation or use case for changing the behavior?**
I do not see why webpack should not apply this optimisation: whether the json file is big or small we can apply the same optimisation (thanks to loaders) of every other JS file.

**Comment by sokra** [comment]
Note to myself: For backward compatibility this requires different results for `import * as x` and `require()`. Maybe a `__commonjs` export can fulfill this?

**Comment by sokra** [comment]
webpack 4 handles JSON without loader, so it's probably easier to do it.

**Comment by msn0** [comment]
I had the same problem and created a loader as a temporary solution - https://github.com/msn0/json-es6-loader

**Comment by damianobarbati** [comment]
@msn0 exactly what I was looking for!
Indeed having this into the core without additional loaders will be great :)

**Comment by sokra** [comment]
I currently adding native support for this. It's a bit more involved because require and import need to have different behavior for JSON modules (this is not the case for ESM modules).

**Comment by bmeck** [comment]
@jkrems it suffers the same data synchronization issue that I'd like to avoid:

```mjs
// {"x": 1}
import {x}, root from 'json';
console.log(x) // 1
root.x = 2
console.log(x) // 1
console.log(root.x) 1
```

If that is solved so they stay in sync some way (freezing the target or setting up some form of proxy), seems fine. Curious what to do when `default` is defined. Older EPs stated that `default` would always point to the root of the target even if the object had a `.default` property.

**Comment by jkrems** [comment]
Right, the behavior for a JSON file containing `{"default":42,"x":10}` should be explicitly called out. My expectation would be "default is still magic".

Something similar is true for that same file and `import * as ns from './foo.json'`. Would it set `ns` to `{ default: { default: 42, x: 10 }, x: 10 }`? That would be the consistent.

**Comment by sokra** [comment]
done

**Comment by jkrems** [comment]
See PR: https://github.com/webpack/webpack/pull/6184
