### ISSUE TITLE
Support for RequireJS plugins

### ISSUE THREAD

**Issue by jslegers** [webpack/webpack#5735]
**Do you want to request a *feature* or report a *bug*?**

Not sure

**What is the current behavior?**

Webpack supports AMD, but support for [RequireJS plugins](http://requirejs.org/docs/plugins.html) is either missing or undocumented.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Get the [text plugin](http://requirejs.org/docs/api.html#text) for RequireJS
2. Create a file named `file.txt` with some text
3. Define a module `plugintest` like this:
````js
define(["requirejs/text!path/to/file.txt"], function(myFile){
  return {
   content : myFile
  };
});
````

**What is the expected behavior?**

`plugintest` should be able to get loaded just like any other module, and its output should be a POJO with a `content` property that contains the content of `file.txt`.

**If this is a feature request, what is motivation or use case for changing the behavior?**

The lack of support for RequireJS plugins prevents the use of Webpack for libraries that use any such plugins.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

The behavior of the plugin mentioned hereabove is identical to the behavior of the `dojo/text`. I would expect to be able to replace `dojo/text` with `requirejs/text` or vice versa without having to update any configuration.

**Comment by gdborton** [comment]
Is there a reason that you need RequireJS plugin support specifically? I imagine this would work if you were to use webpack's raw loader - https://github.com/webpack-contrib/raw-loader

**Comment by sokra** [comment]
RequireJS plugins are not supported. You can solve this specific case with:

``` js
resolveLoader: {
  alias: { "requirejs/text": "raw-loader" }
}
```

**Comment by jslegers** [comment]
I guess this is good enough for now.

Thanks!
