### ISSUE TITLE
webpack.ProvidePlugin is being too smart

### ISSUE THREAD

**Issue by sixinli** [webpack/webpack#5736]
**report a *bug***

we have this block for angular to find jquery, and we also want to expose jquery to the window

webpack config:
```
new webpack.ProvidePlugin({
      // allows angular to find JQuery
      "window.jQuery": "jquery"
})
```

globalExport.js
```
var globalWindow = window;
globalWindow.jQuery = $;
```

**If the current behavior is a bug, please provide the steps to reproduce.**
in `2.2.1` it used to generate:
```
var globalWindow = window;
globalWindow.jQuery = $;
```

and in `3.2.0` it's generating:
```
var globalWindow = window;
__webpack_provided_window_dot_jQuery = $;
```

**Comment by wub** [comment]
We're using this for exposing to the window, and it works great: https://github.com/webpack-contrib/expose-loader

**Comment by rafde** [comment]
maybe don't include `window.jQuery` in ProvidePlugin so it doesn't affect your globalExport.js file since jquery on the window will be see by all modules.

**Comment by nchen63** [comment]
@rafde unfortunately, AngularJS relies on calling `window.jQuery`, but `window.jQuery` isn't assigned until after AngularJS runs.

**Comment by Rex90** [comment]
was this ever resolved?

**Comment by evilebottnawi** [comment]
@Rex90 use https://github.com/webpack-contrib/expose-loader loader for this purpose. `ProvidePlugin` for other purpose. Thanks!
