### ISSUE TITLE
c.i is not a function, or __webpack_require__.i is not a function, and bundle missing source map URL

### ISSUE THREAD

**Issue by eliperelman** [webpack/webpack#5737]
**Do you want to request a *feature* or report a *bug*?**

Reporting a bug.

**What is the current behavior?**

In production, loading a particular page throws an error with `c.i is not a function`. I tracked this down to map to `__webpack_require__.i is not a function`. Unfortunately I can't seem to replicate this locally on my Mac, only when the project is built in production on Heroku.

Also, for some reason the bundle for the page in question does not produce a source map URL, and this page is loaded via dynamic imports. When running the build command locally, the bundle *does* have a source map URL.

**If the current behavior is a bug, please provide the steps to reproduce.**

Repository uses Neutrino to encapsulate Webpack config. Here is a stringified version of the Webpack configuration that we are using:

<summary>
  Webpack config
  
  <details>

        {
          context: '/Users/eli/code/taskcluster/taskcluster-tools',
          devtool: 'source-map',
          entry: {
            index: [
              '/Users/eli/code/taskcluster/taskcluster-tools/src/index'
            ],
            vendor: [
              'babel-polyfill',
              'deepmerge',
              'lodash.chunk',
              'lodash.clonedeep',
              'prop-types',
              'ramda',
              'markdown-it',
              'highlight.js',
              'moment',
              'qs',
              'react',
              'react-tooltip',
              'react-bootstrap',
              'react-loadable',
              'react-fontawesome',
              'react-router-bootstrap',
              'slugid',
              'react-dom',
              'react-helmet',
              'react-router-dom',
              'taskcluster-client-web'
            ]
          },
          externals: {
            bindings: 'bindings'
          },
          module: {
            rules: [
              {
                enforce: 'pre',
                include: [
                  '/Users/eli/code/taskcluster/taskcluster-tools/src'
                ],
                test: /\.(js|jsx)$/,
                use: [
                  {
                    loader: '/Users/eli/code/taskcluster/taskcluster-tools/node_modules/eslint-loader/index.js',
                    options: {
                      baseConfig: {
                        'extends': [
                          'airbnb-base',
                          'plugin:react/recommended',
                          'eslint-config-prettier'
                        ]
                      },
                      cwd: '/Users/eli/code/taskcluster/taskcluster-tools',
                      emitError: true,
                      emitWarning: true,
                      envs: [
                        'es6',
                        'browser',
                        'commonjs'
                      ],
                      extensions: [
                        'js',
                        'jsx'
                      ],
                      failOnError: true,
                      globals: [
                        'process'
                      ],
                      parser: 'babel-eslint',
                      parserOptions: {
                        ecmaFeatures: {
                          generators: true,
                          impliedStrict: true,
                          objectLiteralDuplicateProperties: false
                        },
                        ecmaVersion: 2017,
                        sourceType: 'module'
                      },
                      plugins: [
                        'babel',
                        'eslint-plugin-react',
                        'eslint-plugin-prettier',
                        'react'
                      ],
                      root: true,
                      rules: {
                        'babel/new-cap': 'off',
                        'babel/object-curly-spacing': [
                          'error',
                          'always'
                        ],
                        'class-methods-use-this': 'off',
                        'comma-dangle': [
                          'error',
                          'never'
                        ],
                        'consistent-return': 'off',
                        'jsx-quotes': [
                          'error',
                          'prefer-double'
                        ],
                        'max-len': [
                          'error',
                          120,
                          2,
                          {
                            ignoreComments: false,
                            ignoreStrings: true,
                            ignoreTemplateLiterals: true,
                            ignoreUrls: true
                          }
                        ],
                        'new-cap': 'off',
                        'no-console': 'error',
                        'no-extra-parens': 'off',
                        'no-mixed-operators': 'off',
                        'no-return-assign': 'off',
                        'no-shadow': 'off',
                        'no-unused-expressions': 'off',
                        'object-curly-spacing': 'off',
                        'prefer-const': 'error',
                        'prettier/prettier': [
                          'error',
                          {
                            bracketSpacing: true,
                            jsxBracketSameLine: true,
                            singleQuote: true,
                            trailingComma: 'none'
                          }
                        ],
                        'react/jsx-closing-bracket-location': 'off',
                        'react/jsx-curly-spacing': [
                          'error',
                          'never'
                        ],
                        'react/jsx-equals-spacing': [
                          'error',
                          'never'
                        ],
                        'react/jsx-first-prop-new-line': [
                          'error',
                          'multiline'
                        ],
                        'react/jsx-indent': 'off',
                        'react/jsx-indent-props': [
                          'error',
                          2
                        ],
                        'react/jsx-key': 'error',
                        'react/jsx-no-comment-textnodes': 'error',
                        'react/jsx-no-target-blank': 'error',
                        'react/jsx-pascal-case': 'error',
                        'react/jsx-tag-spacing': [
                          'error',
                          {
                            beforeSelfClosing: 'always'
                          }
                        ],
                        'react/jsx-wrap-multilines': 'error',
                        'react/prop-types': 'off'
                      },
                      settings: {},
                      useEslintrc: false
                    }
                  }
                ]
              },
              {
                test: /\.html$/,
                use: [
                  {
                    loader: '/Users/eli/code/taskcluster/taskcluster-tools/node_modules/html-loader/index.js',
                    options: {
                      name: '[name].[ext]'
                    }
                  }
                ]
              },
              {
                exclude: [
                  '/Users/eli/code/taskcluster/taskcluster-tools/node_modules'
                ],
                test: /\.css$/,
                use: [
                  {
                    loader: '/Users/eli/code/taskcluster/taskcluster-tools/node_modules/style-loader/index.js'
                  },
                  {
                    loader: '/Users/eli/code/taskcluster/taskcluster-tools/node_modules/css-loader/index.js',
                    options: {
                      modules: true
                    }
                  }
                ]
              },
              {
                test: /\.(woff|woff2)(\?v=\d+\.\d+\.\d+)?$/,
                use: [
                  {
                    loader: '/Users/eli/code/taskcluster/taskcluster-tools/node_modules/url-loader/index.js',
                    options: {
                      limit: '10000',
                      mimetype: 'application/font-woff'
                    }
                  }
                ]
              },
              {
                test: /\.ttf(\?v=\d+\.\d+\.\d+)?$/,
                use: [
                  {
                    loader: '/Users/eli/code/taskcluster/taskcluster-tools/node_modules/url-loader/index.js',
                    options: {
                      limit: '10000',
                      mimetype: 'application/octet-stream'
                    }
                  }
                ]
              },
              {
                test: /\.eot(\?v=\d+\.\d+\.\d+)?$/,
                use: [
                  {
                    loader: '/Users/eli/code/taskcluster/taskcluster-tools/node_modules/file-loader/index.js'
                  }
                ]
              },
              {
                test: /\.svg(\?v=\d+\.\d+\.\d+)?$/,
                use: [
                  {
                    loader: '/Users/eli/code/taskcluster/taskcluster-tools/node_modules/url-loader/index.js',
                    options: {
                      limit: 8192
                    }
                  }
                ]
              },
              {
                test: /\.(png|jpg|jpeg|gif)(\?v=\d+\.\d+\.\d+)?$/,
                use: [
                  {
                    loader: '/Users/eli/code/taskcluster/taskcluster-tools/node_modules/url-loader/index.js',
                    options: {
                      limit: 8192
                    }
                  }
                ]
              },
              {
                test: /\.ico(\?v=\d+\.\d+\.\d+)?$/,
                use: [
                  {
                    loader: '/Users/eli/code/taskcluster/taskcluster-tools/node_modules/url-loader/index.js',
                    options: {
                      limit: 8192
                    }
                  }
                ]
              },
              {
                exclude: [
                  '/Users/eli/code/taskcluster/taskcluster-tools/src/static'
                ],
                include: [
                  '/Users/eli/code/taskcluster/taskcluster-tools/src',
                  '/Users/eli/code/taskcluster/taskcluster-tools/test'
                ],
                test: /\.jsx?$/,
                use: [
                  {
                    loader: '/Users/eli/code/taskcluster/taskcluster-tools/node_modules/babel-loader/lib/index.js',
                    options: {
                      cacheDirectory: true,
                      env: {
                        development: {
                          plugins: [
                            [
                              '/Users/eli/code/taskcluster/taskcluster-tools/node_modules/babel-plugin-transform-class-properties/lib/index.js',
                              {
                                spec: true
                              }
                            ],
                            '/Users/eli/code/taskcluster/taskcluster-tools/node_modules/babel-plugin-transform-es2015-classes/lib/index.js'
                          ]
                        }
                      },
                      plugins: [
                        [
                          '/Users/eli/code/taskcluster/taskcluster-tools/node_modules/fast-async/plugin.js',
                          {
                            spec: true
                          }
                        ],
                        '/Users/eli/code/taskcluster/taskcluster-tools/node_modules/babel-plugin-syntax-dynamic-import/lib/index.js',
                        '/Users/eli/code/taskcluster/taskcluster-tools/node_modules/babel-plugin-transform-object-rest-spread/lib/index.js',
                        [
                          '/Users/eli/code/taskcluster/taskcluster-tools/node_modules/babel-plugin-transform-class-properties/lib/index.js',
                          {
                            spec: true
                          }
                        ]
                      ],
                      presets: [
                        [
                          '/Users/eli/code/taskcluster/taskcluster-tools/node_modules/babel-preset-env/lib/index.js',
                          {
                            debug: false,
                            exclude: [
                              'transform-regenerator',
                              'transform-async-to-generator'
                            ],
                            modules: false,
                            targets: {
                              browsers: [
                                'last 2 Chrome versions',
                                'last 2 Firefox versions',
                                'last 2 Edge versions',
                                'last 2 Opera versions',
                                'last 2 Safari versions',
                                'last 2 iOS versions'
                              ]
                            },
                            useBuiltIns: true
                          }
                        ],
                        '/Users/eli/code/taskcluster/taskcluster-tools/node_modules/babel-preset-react/lib/index.js'
                      ]
                    }
                  }
                ]
              },
              {
                test: /\.worker\.js$/,
                use: [
                  {
                    loader: '/Users/eli/code/taskcluster/taskcluster-tools/node_modules/worker-loader/index.js'
                  }
                ]
              },
              {
                include: [
                  '/Users/eli/code/taskcluster/taskcluster-tools/node_modules'
                ],
                test: /\.css$/,
                use: [
                  {
                    loader: '/Users/eli/code/taskcluster/taskcluster-tools/node_modules/style-loader/index.js'
                  },
                  {
                    loader: '/Users/eli/code/taskcluster/taskcluster-tools/node_modules/css-loader/index.js'
                  }
                ]
              },
              {
                test: /JSONStream/,
                use: [
                  {
                    loader: 'shebang-loader'
                  }
                ]
              }
            ]
          },
          node: {
            Buffer: true,
            fs: 'empty',
            tls: 'empty'
          },
          output: {
            chunkFilename: '[name].[chunkhash].js',
            filename: '[name].[chunkhash].js',
            path: '/Users/eli/code/taskcluster/taskcluster-tools/build',
            publicPath: '/'
          },
          plugins: [
            {
              keys: [
                'NODE_ENV',
                'AUTH0_DOMAIN',
                'AUTH0_CLIENT_ID',
                'AUTH0_AUDIENCE',
                'SIGN_IN_METHODS'
              ],
              defaultValues: {}
            },
            {
              options: {
                template: '/Users/eli/code/taskcluster/taskcluster-tools/node_modules/html-webpack-template/index.ejs',
                filename: 'index.html',
                hash: false,
                inject: false,
                compile: true,
                favicon: false,
                minify: {
                  useShortDoctype: true,
                  keepClosingSlash: true,
                  collapseWhitespace: true,
                  preserveLineBreaks: true
                },
                cache: true,
                showErrors: true,
                chunks: 'all',
                excludeChunks: [],
                title: 'Taskcluster Tools',
                xhtml: true,
                appMountId: 'root',
                mobile: true,
                meta: [
                  {
                    name: 'description',
                    content: 'A collection of tools for Taskcluster components and elements in the Taskcluster ecosystem. Here\n                you\'ll find tools to manage Taskcluster as well as run, debug, inspect, and view tasks, task groups, and\n                other Taskcluster related entities.'
                  },
                  {
                    name: 'author',
                    content: 'Mozilla Taskcluster Team'
                  }
                ]
              }
            },
            {
              options: {
                inline: {
                  test: []
                },
                sync: {
                  test: []
                },
                async: {
                  test: []
                },
                defer: {
                  test: []
                },
                module: {
                  test: []
                },
                prefetch: {
                  test: [],
                  chunks: 'initial'
                },
                preload: {
                  test: [],
                  chunks: 'initial'
                },
                defaultAttribute: 'defer',
                removeInlinedAssets: true,
                custom: []
              }
            },
            {
              options: {}
            },
            {
              nameResolver: chunk => (
                      chunk.name ||
                      hash(chunk.modules.map(({ context, request }) => relative(context || '', request || '')).join('_'))
                    )
            },
            {
              chunkNames: [
                'vendor'
              ],
              filenameTemplate: undefined,
              minChunks: Infinity,
              selectedChunks: undefined,
              children: undefined,
              async: undefined,
              minSize: undefined,
              ident: '/Users/eli/code/taskcluster/taskcluster-tools/node_modules/neutrino-middleware-chunk/node_modules/webpack/lib/optimize/CommonsChunkPlugin.js0'
            },
            {
              chunkNames: [
                'runtime'
              ],
              filenameTemplate: undefined,
              minChunks: undefined,
              selectedChunks: undefined,
              children: undefined,
              async: undefined,
              minSize: undefined,
              ident: '/Users/eli/code/taskcluster/taskcluster-tools/node_modules/neutrino-middleware-chunk/node_modules/webpack/lib/optimize/CommonsChunkPlugin.js1'
            },
            {},
            {
              options: {
                parserOpts: {},
                minifyPreset: function preset(context) {
                  var _opts = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : {};
        
                  var opts = isPlainObject(_opts) ? _opts : {};
        
                  // validate options
                  var validOptions = [].concat(_toConsumableArray(PLUGINS.map(function (p) {
                    return p[0];
                  })), _toConsumableArray(Object.keys(PROXIES)));
                  for (var name in opts) {
                    if (validOptions.indexOf(name) < 0) {
                      throw new Error(`Invalid option "${name}"`);
                    }
                  }
        
                  // build a plugins map from the plugin table above
                  var pluginsMap = PLUGINS.reduce(function (acc, _ref) {
                    var _ref2 = _slicedToArray(_ref, 3),
                        name = _ref2[0],
                        plugin = _ref2[1],
                        defaultValue = _ref2[2];
        
                    return Object.assign(acc, {
                      [name]: {
                        plugin,
                        options: null,
                        enabled: defaultValue
                      }
                    });
                  }, {});
        
                  // handle plugins and their options
                  var _iteratorNormalCompletion = true;
                  var _didIteratorError = false;
                  var _iteratorError = undefined;
        
                  try {
                    for (var _iterator = PLUGINS[Symbol.iterator](), _step; !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorNormalCompletion = true) {
                      var _ref3 = _step.value;
        
                      var _ref4 = _slicedToArray(_ref3, 1);
        
                      var _name = _ref4[0];
        
                      if (isPlainObject(opts[_name])) {
                        pluginsMap[_name].options = opts[_name];
                      } else if (opts[_name] !== void 0) {
                        pluginsMap[_name].enabled = !!opts[_name];
                      }
                    }
        
                    // handle proxies
                  } catch (err) {
                    _didIteratorError = true;
                    _iteratorError = err;
                  } finally {
                    try {
                      if (!_iteratorNormalCompletion && _iterator.return) {
                        _iterator.return();
                      }
                    } finally {
                      if (_didIteratorError) {
                        throw _iteratorError;
                      }
                    }
                  }
        
                  for (var proxyname in PROXIES) {
                    if (opts[proxyname] !== void 0) {
                      var _iteratorNormalCompletion2 = true;
                      var _didIteratorError2 = false;
                      var _iteratorError2 = undefined;
        
                      try {
                        for (var _iterator2 = PROXIES[proxyname][Symbol.iterator](), _step2; !(_iteratorNormalCompletion2 = (_step2 = _iterator2.next()).done); _iteratorNormalCompletion2 = true) {
                          var to = _step2.value;
        
                          if (!pluginsMap[to].options) {
                            pluginsMap[to].options = {};
                          }
                          if (!hop(pluginsMap[to].options, proxyname)) {
                            pluginsMap[to].options[proxyname] = opts[proxyname];
                          }
                        }
                      } catch (err) {
                        _didIteratorError2 = true;
                        _iteratorError2 = err;
                      } finally {
                        try {
                          if (!_iteratorNormalCompletion2 && _iterator2.return) {
                            _iterator2.return();
                          }
                        } finally {
                          if (_didIteratorError2) {
                            throw _iteratorError2;
                          }
                        }
                      }
                    }
                  }
        
                  // get the array of plugins
                  var plugins = Object.keys(pluginsMap).map(function (name) {
                    return pluginsMap[name];
                  }).filter(function (plugin) {
                    return plugin.enabled;
                  }).map(function (plugin) {
                    return plugin.options ? [plugin.plugin, plugin.options] : plugin.plugin;
                  });
        
                  return {
                    minified: true,
                    comments: false,
                    presets: [{ plugins }],
                    passPerPreset: true
                  };
                },
                minifyOpts: {},
                babel: {
                  transform: function () { [native code] }
                },
                comments: /^\**!|@preserve|@license|@cc_on/,
                sourceMap: undefined,
                jsregex: /\.js($|\?)/i
              }
            },
            {
              paths: [
                '/Users/eli/code/taskcluster/taskcluster-tools/build'
              ],
              options: {
                root: '/Users/eli/code/taskcluster/taskcluster-tools',
                verbose: false,
                allowExternal: false,
                dry: false
              }
            },
            {
              apply: function apply(compiler) {
                      var fileDependencies = [];
                      var contextDependencies = [];
                      var written = {};
        
                      compiler.plugin('emit', function (compilation, cb) {
                          debug('starting emit');
                          var callback = function callback() {
                              debug('finishing emit');
                              cb();
                          };
        
                          var globalRef = {
                              info: info,
                              debug: debug,
                              warning: warning,
                              compilation: compilation,
                              written: written,
                              fileDependencies: fileDependencies,
                              contextDependencies: contextDependencies,
                              context: compiler.options.context,
                              output: compiler.options.output.path,
                              ignore: options.ignore || [],
                              copyUnmodified: options.copyUnmodified,
                              concurrency: options.concurrency
                          };
        
                          if (globalRef.output === '/' && compiler.options.devServer && compiler.options.devServer.outputPath) {
                              globalRef.output = compiler.options.devServer.outputPath;
                          }
        
                          _bluebird2.default.each(patterns, function (pattern) {
                              // Identify absolute source of each pattern and destination type
                              return (0, _preProcessPattern2.default)(globalRef, pattern).then(function (pattern) {
                                  // Every source (from) is assumed to exist here
                                  return (0, _processPattern2.default)(globalRef, pattern);
                              });
                          }).catch(function (err) {
                              compilation.errors.push(err);
                          }).finally(callback);
                      });
        
                      compiler.plugin('after-emit', function (compilation, cb) {
                          debug('starting after-emit');
                          var callback = function callback() {
                              debug('finishing after-emit');
                              cb();
                          };
        
                          // Add file dependencies if they're not already tracked
                          _lodash2.default.forEach(fileDependencies, function (file) {
                              if (_lodash2.default.includes(compilation.fileDependencies, file)) {
                                  debug('not adding ' + file + ' to change tracking, because it\'s already tracked');
                              } else {
                                  debug('adding ' + file + ' to change tracking');
                                  compilation.fileDependencies.push(file);
                              }
                          });
        
                          // Add context dependencies if they're not already tracked
                          _lodash2.default.forEach(contextDependencies, function (context) {
                              if (_lodash2.default.includes(compilation.contextDependencies, context)) {
                                  debug('not adding ' + context + ' to change tracking, because it\'s already tracked');
                              } else {
                                  debug('adding ' + context + ' to change tracking');
                                  compilation.contextDependencies.push(context);
                              }
                          });
        
                          callback();
                      });
                  }
            },
            {
              definitions: {
                $: 'jquery',
                jQuery: 'jquery'
              }
            }
          ],
          resolve: {
            alias: {
              'react-native': 'react-native-web'
            },
            extensions: [
              '.js',
              '.json',
              '.jsx'
            ],
            modules: [
              '/Users/eli/code/taskcluster/taskcluster-tools/node_modules/neutrino-middleware-eslint/node_modules',
              'node_modules',
              '/Users/eli/code/taskcluster/taskcluster-tools/node_modules',
              '/Users/eli/code/taskcluster/taskcluster-tools/node_modules/neutrino-preset-web/node_modules',
              '/Users/eli/code/taskcluster/taskcluster-tools/node_modules/neutrino-preset-react/node_modules'
            ]
          },
          resolveLoader: {
            modules: [
              '/Users/eli/code/taskcluster/taskcluster-tools/node_modules/neutrino-middleware-eslint/node_modules',
              '/Users/eli/code/taskcluster/taskcluster-tools/node_modules',
              '/Users/eli/code/taskcluster/taskcluster-tools/node_modules/neutrino-preset-web/node_modules',
              '/Users/eli/code/taskcluster/taskcluster-tools/node_modules/neutrino-preset-react/node_modules'
            ]
          },
          target: 'web'
        }

  </details>
</summary>

**What is the expected behavior?**

No exceptions.

**If this is a feature request, what is motivation or use case for changing the behavior?**

Local environment:
Node.js: 8.6.0
webpack: 3.6.0
OS: MacOS 10.12 High Sierra

Heroku environment:
Node.js: 8.6.0
webpack: 3.6.0
OS: Linux

**Comment by sokra** [comment]
`__webpack_require__.i` was used in older versions of webpack, but it's no longer used in webpack 3.6.0. Maybe you see a older version of a cached file? Maybe it has the same hash? That looks unlikely. Do you have any plugin that modify the hashing behavior?

**Comment by eliperelman** [comment]
I always nuke the build directory prior to building, so it shouldn't be a cached version. For plugins that could modify caching/hashing/chunking behavior, I am using:

```js
const hash = value => createHash('md5').update(value).digest('hex');

plugins = [
  new NamedModulesPlugin(),

  new NamedChunksPlugin([
      chunk => (
        chunk.name ||
        hash(chunk.modules.map(({ context, request }) => relative(context || '', request || '')).join('_'))
      )
    ]),

  new optimize.CommonsChunkPlugin([{ name: 'vendor', minChunks: Infinity }]),

  new optimize.CommonsChunkPlugin([{ name: 'runtime' }]),

  new NameAllModulesPlugin() // from name-all-modules-plugin
]
```

Anything seem suspicious there?

**Comment by eliperelman** [comment]
Also of note, this doesn't happen with webpack 2.7.x.

**Comment by sokra** [comment]
Could be a bug...

Could you create a repro repo?

**Comment by eliperelman** [comment]
I think @sokra was right about this being a caching issue. Several bundle hashes hadn't changed and were cached by CloudFront, so it appeared as though webpack was generating incorrect assets.

I'll close this issue as resolved, but it does bring up another question:

Does switching from no source-map to a source-map change the chunk hash when the sourceMappingUrl gets added to the end of the file? From looking at my local testing, it appears that it doesn't, which seems like a bug to me.
