### ISSUE TITLE
[Question] possible to serve an asset without watching it?

### ISSUE THREAD

**Issue by MonkRocker** [webpack/webpack#5742]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
I am making a request from my project which results in an image file being downloaded asynchronously into an assets folder dev server is serving from.  I am wondering if it is possible to ignore that same folder in watch.

`
app/img/  // <-- I want to ignore this directory in watch mode, but still be able to use links like:
<img src='img/f/fred_cover1.jpg'>   // <-- cover1.jpg does NOT exist at compile time.  It exists after a different request is made for it.
`

I have tried both watchOptions.ignored and WatchIgnorePlugin to no avail.  
 
**If the current behavior is a bug, please provide the steps to reproduce.**

current config:
`new WatchIgnorePlugin([
      path.resolve(__dirname, "./src/img/**/*.jpg")
    ])`

**What is the expected behavior?**
If a directory is being ignored in watchOptions, then watch ACTUALLY ignores it.

**Comment by sokra** [comment]
@webpack-bot move to webpack-contrib/html-loader

That's probably something you want to request from the html-loader?
