### ISSUE TITLE
Internal module drive letter case does not match process.cwd() ( duplicate modules )

### ISSUE THREAD

**Issue by markbjerke** [webpack/webpack#5744]
**Do you want to request a *feature* or report a *bug*?**
report a bug 
**What is the current behavior?**

For web targets when the process global is encountered the  process/browser.js module is included in the bundle.  The problem is the drive letter is sometimes not in sync with the drive letter as specified by process.cwd(). 

This is a problem creating duplicate copies of this internal module when the path differs only by the case of the drive letter.  We have no control over how internal modules are expanded. 

 Our practice is to observe process.cwd() and return config after checking the case of the drive letter with entry points and aliases matching the drive letter case.  This has eliminated 99% of duplicate module warnings.  However the internal modules if they expand out to paths where the drive letter casing is different than the process.cwd() casing we get duplicates of internal modules in our bundle.

```
 [1m[33mWARNING in ./node_modules/process/browser.js
    There are multiple modules with names that only differ in casing.
    This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
    Use equal casing. Compare these module identifiers:
    * C:\WebClientToolkit\node_modules\process\browser.js
        Used by 3 module(s), i. e.
        C:\WebClientToolkit\packages\core\wct-http\source\index.js
    * c:\WebClientToolkit\node_modules\process\browser.js
        Used by 1 module(s), i. e.
        c:\WebClientToolkit\node_modules\path-browserify\index.js[39m[22m
```

**If the current behavior is a bug, please provide the steps to reproduce.**
I can provide our config, however it's going to happen when bundling web targets on windows unless you get 'lucky' and the expansion for the internal process module happens to match process.cwd().

**What is the expected behavior?**
There should not be duplicates of internal modules.

**If this is a feature request, what is motivation or use case for changing the behavior?**
When the path is expanded for internal modules check process.cwd() and match the drive letter case.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
We're on webpack 3.6.0 and Node 6.10.3.

**Comment by markbjerke** [comment]
OK - I"m using the Ignore Plugin, this is still a problem though.

**Comment by siarheiyelin** [comment]
This issue is still reproduced using Webpack 5 and Node v16.18.0. Is there any way to overcome it?
