### ISSUE TITLE
file-loader corrupts output images

### ISSUE THREAD

**Issue by steelstring94** [webpack/webpack#5745]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

file-loader outputs a corrupted image.  It cannot be opened either in the web browser or the local file browser.  Attempting to open it with an image viewer returns an error that the file is corrupt.  Additionally, the output file in /dist is larger than the file in /src.

Output file size: 115.1 kB
Input file size: 63.6 kB

**If the current behavior is a bug, please provide the steps to reproduce.**

Proceed exactly with the Webpack official tutorial up to and including this point (this part is where the failure occurs): https://webpack.js.org/guides/asset-management/#loading-images

**What is the expected behavior?**

file-loader should copy the image from /src to /dist and plug it in to the web page when the page is loaded.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Node.js - v8.6.0
Webpack - 3.6.0
OS - Ubuntu 17.04 MATE

**Comment by michael-ciniawsky** [comment]
We are aware of this :) Please ensure to fix your `file-loader` dependency version to `0.11.2` until [`file-loader` #183](https://github.com/webpack-contrib/file-loader/pull/183) lands and close the issue here

**Comment by steelstring94** [comment]
@michael-ciniawsky Somebody literally just linked me to the bug report on file-loader like a minute after I posted this.  I didn't realize file-loader was a separate repo.  Thank you, and my apologies to the webpack team for this waste of a report!
