### ISSUE TITLE
Importing thousand svgs with a dynamic import expression causes a Javascript Heap out of memory

### ISSUE THREAD

**Issue by speedDeveloper** [webpack/webpack#5747]
**Do you want to request a *feature* or report a *bug*?**
I request a bug

**What is the current behavior?**
Webpack throws an exception, as soon as it reads the dynamic import statement.
The dynamic import looks like this: `import('../images_svg/' + svgData.path + '.svg')`
The folder images_svg contains 677 different svgs.
```
<--- Last few GCs --->

   95733 ms: Mark-sweep 1301.0 (1434.6) -> 1303.2 (1434.6) MB, 61.8 / 0.0 ms [allocation failure] [scavenge might not succeed].
   95794 ms: Mark-sweep 1303.2 (1434.6) -> 1305.4 (1434.6) MB, 60.9 / 0.0 ms [allocation failure] [scavenge might not succeed].
   95856 ms: Mark-sweep 1305.4 (1434.6) -> 1312.2 (1418.6) MB, 62.3 / 0.0 ms [last resort gc].
   95922 ms: Mark-sweep 1312.2 (1418.6) -> 1319.1 (1418.6) MB, 65.9 / 0.0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 000001788583FA99 <JS Object>
    1: stringify [native json.js:178] [pc=000002CFEA0A3CF7] (this=0000017885846091 <a JSON with map 0000010551613B91>,E=0000023A39E19981 <Very long string[11977826]>,F=0000017885804241 <undefined>,S=0000017885804241 <undefined>)
    2: arguments adaptor frame: 1->3
    3: /* anonymous */ [C:\Users\phili\Documents\Kunden\step1\app\node_modules\webpack\lib\EvalDevToolModuleTemplatePlugin.js:~17...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory 
```

**If the current behavior is a bug, please provide the steps to reproduce.**
To reproduce it, you import a folder with 600 different svgs, using svg-inline-loader.

**What is the expected behavior?**
Expected is that the application bundles the files and does not crash while loading.
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
browser latest chrome and opera
node js v6.11.2
webpack 3.6.0
windows

**Comment by sokra** [comment]
Try to increase the node.js memory.

**Comment by speedDeveloper** [comment]
I changed the command in the package.json to `node --max_old_space_size=8000  scripts/start.js` but it still doesn't work after several tries.

**Comment by sokra** [comment]
Could you paste the error with max_old_space_size?

**Comment by speedDeveloper** [comment]
I am sorry, it works with `max_old_space_size`, I just need to be very patient. It takes about ten minutes, which before the import wasn't necessary. How can I go about this? Which solutions are there to solve this? @sokra

**Comment by sokra** [comment]
I guess the svg-inline-loader isn't the cheapest one... Try using the `cache-loader` to cache the result.

**Comment by speedDeveloper** [comment]
Nice, it takes now only a minute. Thank you @sokra. If you know some additional tweaks let me know.

**Comment by sokra** [comment]
see this page for performance hints: https://webpack.js.org/guides/build-performance/

**Comment by speedDeveloper** [comment]
Hey @sokra I added 'include' to the loaders, set symlinks and cacheWithContext to false, implemented the CommonChunksPlugin, set devtool to "eval". Sadly it always takes at least 40 seconds. Is there something I haven't thought about, which could optimize the development performance?

Also after enabling performance hints, it shows:

```
This can impact web performance.
Assets:
  static/js/svgs1159.chunk.js (1.64 MB)
  static/js/svgs1158.chunk.js (411 kB)
  static/js/svgs1157.chunk.js (1.02 MB)
  static/js/svgs1156.chunk.js (305 kB)
  .... list continues ...............
```
