### ISSUE TITLE
Discussion: extracting watch logic to own package

### ISSUE THREAD

**Issue by netanelgilad** [webpack/webpack#5748]
**Do you want to request a *feature* or report a *bug*?**
feature/discussion

**What is the current behavior?**
Currently webpack has the great watch feature, which allows us to re-bundle on a change to one of our source files. As far as I'm aware, I don't know of other tools that can watch files by the dependency tree and not by watching folders/globs/file paths (expect maybe rollup or other bundlers). 

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
I would like to suggest/discuss the possibility of extracting that logic into it's own package in some manner. I am looking to implement a nodemon like utility that will watch only required files (even inside node_modules!), to get a better developer experience while writing code to the server side.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Since I've started working with lerna to manage monorepos with multiple packages with inter dependencies, current solutions for automatically restarting the nodejs process are not good enough. I don't want to watch the whole node_modules folder (where my lerna dependencies are symlinked) cause I don't want to restart my process on changes that are not code related (lerna symlinks the whole package folder, thus the watching process would also watch files that otherwise could be npmignored).

I started this issue as a discussion and seeing if this can be of interest to anyone. Other than the use cases I've mentioned, I think it could also benefit other bundlers and tools, by sharing the dependency tree building and watch logic.

And of course I would love to help contribute to this endeavor if this is something you'd like to implement. Or if this is too big an effort, maybe nudge me in the right direction in the codebase and I'll start investigating myself. 🍻 

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by michael-ciniawsky** [comment]
https://github.com/webpack/watchpack

**Comment by netanelgilad** [comment]
Well it's good to see that the watch logic of webpack has already been extracted to another package, but this is still not exactly what I was talking about (maybe a better wording for the title would have been better).

As I understand (and I may be mistaken), watchpack is a wrapper around lower level watch packages and mechanisms, which is great. But the main point of my suggestion is to have the ability to watch a dependency tree of an entry point just like webpack does when it bundles files in watch mode. Just that I want to perform another operation in response to a change in the files in the dependency tree (restart a process in my case).

Is this still possible with watchpack? How does watchpack get the list of files that it needs to watch? How do I update the list of files once a new dependency in introduces to the graph? 

I totally understand if this is something you are not interested in investigating, and I may investigate more myself. Just let me know if I make sense or not :)

**Comment by michael-ciniawsky** [comment]
Check the chokidar API directly and use something like [dep-graph](https://www.npmjs.com/package/dep-graph) to optimize the dependency graph (in case it is needed), but tbh I don't think you will gain much from using watchpack in another project as it is a extended wrapper around chokidar with additional stuff for webpack itself.

**Comment by netanelgilad** [comment]
Oh, I think we are not talking about the same thing. When I say dependency graph I mean the module dependency graph, and I don't know how I can get the dependency graph of a module using the current webpack API (hopefully I'm not missing something).

In a very high level I'm looking for a function that receives an entry point (say index.js) and returns all the files in the dependency graph of that file (I may be using the wrong webpack terms here). Then I'll be able to watch that list of returned files (using chokidar or watchpack or another watching solution) for any changes, and I'll be able to restart my node proccess.

My end result is having a tool very similar to nodemon where I can just `smart-mon ./app.js` and it will start watching all the files that app.js depends on and restart the process when a change occurs.

So my main point is how to get the list of dependency files of a given entry point and I guess finding a solution for watching those files would be easier.

**Comment by netanelgilad** [comment]
Ok so I found this great package [dependency-tree](https://github.com/dependents/node-dependency-tree), that does exactly what I wanted. I can take it from here integrating with some watch mechanism. 

Thanks for the help!
