### ISSUE TITLE
for first 10-seconds watching is incorrect

### ISSUE THREAD

**Issue by mixtur** [webpack/webpack#5749]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
webpack is triggering "watch-run/invalid" events multiple times if some source file is changed within 10 seconds before (or after?) webpack starts. In turn webpack-dev-server recompiles everything in a loop until that 10 seconds period is ended.

**If the current behavior is a bug, please provide the steps to reproduce.**
with this config https://gist.github.com/mixtur/072c99f2bbeabedccd65d151cf083551
`webpack-dev-server` or `webpack --watch`

in case of `webpack --watch` note that first timestamp is 10 seconds in the future. I think it has something to do with that. I was able to trace it down to here https://github.com/webpack/watchpack/blob/master/lib/DirectoryWatcher.js#L88 , I hope that helps.

**What is the expected behavior?**
Only trigger `watch-run/invalid` at correct times.
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
node 8.5.0
browser - not relevant
webpack 3.6.0
os windows 7

**Comment by mixtur** [comment]
same with ubuntu 16.04
Just pick some small project and do 
```bash 
touch <some-source-file> && webpack-dev-server
```

**Comment by zhenwenc** [comment]
I noticed this issue as well. And I created a webpack project [here](https://github.com/zhenwenc/cra-issue) with minimal configuration to reproduce this issue. Just clone the repo and run `reproduce.sh` script.

**Comment by mixtur** [comment]
Root cause seems to be there https://github.com/webpack/watchpack/issues/25, so I'll close this.
