### ISSUE TITLE
Is it possible to get a summary Stat for multi config?

### ISSUE THREAD

**Issue by zxcabs** [webpack/webpack#575]
Hello,
I have a multi configuration app, and i want to get Stat only when all compilers is done, it is possible?

It will be great to have a something like:
`compiler.plugin('doneAll', function (summaryStat, callback) {})`

or maybe something else.

**Comment by sokra** [comment]
I think it already works like this:

``` js
compiler.plugin('done', function (summaryStat) {})
```
