### ISSUE TITLE
Passing a regex with the g flag to a context can cause some files to not be included in the context

### ISSUE THREAD

**Issue by simon-paris** [webpack/webpack#5750]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Creating a context with the g regex flag like below will cause the context to contain a subset of the files it should contain. It's non-deterministic.
```
require.context(".", false, /\.txt$/g);
```

**If the current behavior is a bug, please provide the steps to reproduce.**
1. In an empty folder, create three files: `1a` (empty), `2a` (empty), `entry.js`, containing `require.context(".", false, /a/g);`.
2. Run `webpack entry.js out.js`, the context will contain only one file. If you remove the g flag, it works.

**What is the expected behavior?**
It should either throw an error or ignore the g flag. The y flag should receive the same treatment.

This is happening because webpack is using one RegExp instance as it iterates over the list of files. The g flag causes it to use the lastIndex property. I've confirmed this by adding `regExp.lastIndex = 0;` above `return regExp.test(obj.request);` in `ContextModuleFactory.js`.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
`node -v` v8.1.2
`webpack -v` 3.6.0 (also tried 2.6.1)
windows 10 (also tried macOS 10.12.6)

**Comment by sokra** [comment]
Yep, looks like a problem. Send a PR with one of the solutions, I'm fine with both.
