### ISSUE TITLE
Fail to locate files when bundling file that imports compiled webpack config that specifies context

### ISSUE THREAD

**Issue by weijiangan** [webpack/webpack#5752]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
I run webpack on a `node` server script with webpack-hot-middleware, which asks for a webpack Compiler as its function parameter. I'm not familiar with the inner workings of webpack, but I believe it looks for the entry files in the specified `context` location and expands the location to speed things up. However, when I execute the output script it fails to locate the files specified in the webpack config because it is look for the file with expanded path `<context.dir>/.../file.js` in `<context.dir>`.

**If the current behavior is a bug, please provide the steps to reproduce.**

Run webpack on a file that imports a webpack config like this
```javascript
import config from '../webpack.config';
const compiler = webpack(config);
```
and here's what the `webpack.config.js` might look like
```javascript
...
  context: path.resolve(__dirname, 'src'),
  entry: [
    'react-hot-loader/patch',
    'webpack-hot-middleware/client',
    './index.js'
  ],
...
```
Execute the output script
```sh
node build/server.js
```
You'll get an error something along of the lines of this:
```
webpack built ec643461f6fe2df75eac in 98ms
Hash: ec643461f6fe2df75eac
Version: webpack 3.6.0
Time: 98ms
    Asset     Size  Chunks  Chunk Names
bundle.js  28.4 kB       0  main
   [0] multi react-hot-loader/patch webpack-hot-middleware/client ./index.js 52 bytes {0} [built]

ERROR in multi react-hot-loader/patch webpack-hot-middleware/client ./index.js
Module not found: Error: Can't resolve './index.js' in '/src'
 @ multi react-hot-loader/patch webpack-hot-middleware/client ./index.js

ERROR in multi react-hot-loader/patch webpack-hot-middleware/client ./index.js
Module not found: Error: Can't resolve 'react-hot-loader/patch' in '/src'
 @ multi react-hot-loader/patch webpack-hot-middleware/client ./index.js

ERROR in multi react-hot-loader/patch webpack-hot-middleware/client ./index.js
Module not found: Error: Can't resolve 'webpack-hot-middleware/client' in '/src'
 @ multi react-hot-loader/patch webpack-hot-middleware/client ./index.js

ERROR in   Error: Child compilation failed:
  Entry module not found: Error: Can't resolve '/src/views/index.html' in '/src'  :
  Error: Can't resolve '/src/views/index.html' in '/src'

  - compiler.js:76
    [IBookVenue]/[html-webpack-plugin]/lib/compiler.js:76:16

  - Compiler.js:304 compile
    [IBookVenue]/[webpack]/lib/Compiler.js:304:11

  - Compiler.js:514 applyPluginsAsync.err
    [IBookVenue]/[webpack]/lib/Compiler.js:514:14

  - Tapable.js:202 next
    [IBookVenue]/[tapable]/lib/Tapable.js:202:11

  - CachePlugin.js:78 Compiler.<anonymous>
    [IBookVenue]/[webpack]/lib/CachePlugin.js:78:5

  - Tapable.js:206 Compiler.applyPluginsAsyncSeries
    [IBookVenue]/[tapable]/lib/Tapable.js:206:13

  - Compiler.js:511 compilation.seal.err
    [IBookVenue]/[webpack]/lib/Compiler.js:511:11

  - Tapable.js:195 Compilation.applyPluginsAsyncSeries
    [IBookVenue]/[tapable]/lib/Tapable.js:195:46

  - Compilation.js:671 self.applyPluginsAsync.err
    [IBookVenue]/[webpack]/lib/Compilation.js:671:19

  - Tapable.js:195 Compilation.applyPluginsAsyncSeries
    [IBookVenue]/[tapable]/lib/Tapable.js:195:46

  - Compilation.js:662 self.applyPluginsAsync.err
    [IBookVenue]/[webpack]/lib/Compilation.js:662:11

  - Tapable.js:195 Compilation.applyPluginsAsyncSeries
    [IBookVenue]/[tapable]/lib/Tapable.js:195:46

  - Compilation.js:657 self.applyPluginsAsync.err
    [IBookVenue]/[webpack]/lib/Compilation.js:657:10

  - Tapable.js:195 Compilation.applyPluginsAsyncSeries
    [IBookVenue]/[tapable]/lib/Tapable.js:195:46

  - Compilation.js:653 sealPart2
    [IBookVenue]/[webpack]/lib/Compilation.js:653:9

  - Tapable.js:195 Compilation.applyPluginsAsyncSeries
    [IBookVenue]/[tapable]/lib/Tapable.js:195:46


Child html-webpack-plugin for "index.html":

    ERROR in Entry module not found: Error: Can't resolve '/src/views/index.html' in '/src'
```
Removing the `context` option in `webpack.config.js` and prepend the location in the entry file eliminates the error:
```javascript
  // context: path.resolve(__dirname, 'src'),
  entry: [
    'react-hot-loader/patch',
    'webpack-hot-middleware/client',
    './src/index.js'
  ],
```

**What is the expected behavior?**
Webpack should respect `context` option and no errors should occur.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Webpack 3.6.0
Node 8.6.0
MacOS 10.13 GM

Edit Oct 7: Use more accurate terminologies

**Comment by weijiangan** [comment]
I'm not familiar with the webpack codebase but I'm currently looking at the source now. I'm thinking, should the context option be removed when compiled since the paths are expanded? Or should webpack avoid expand the path if context is specified? Or even, maybe this is intentional and we should not specify `context` entirely?

**Comment by sokra** [comment]
Did you compile the webpack.config.js with webpack? Looks like `__dirname` has `"/"` as value. This happens on webpack compilation but can be disabled.

**Comment by weijiangan** [comment]
Well, I don't anymore... But I did. Gets rid of the error. I guess it's not meant to be used like that? How do you disable it? 

Also, do you mind pointing out the offending method? I tried debugging the bundle using ChromeDev for days, it's impossible.

**Comment by sokra** [comment]
`node.dirname: false`
