### ISSUE TITLE
`module` gets prioritised over `main`

### ISSUE THREAD

**Issue by catamphetamine** [webpack/webpack#5756]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

`module` entry in `package.json` gets prioritised over the `main` entry (even on Node.js).

Consider `deepmerge` package: https://unpkg.com/deepmerge@1.5.2/dist/es.js

This:
```js
...
export default deepmerge_1;
```
gets transpiled into:
```js

/* 2043 */
/*!********************************************************************!*\
  !*** /Users/donaldtrump/work/JITU/node_modules/deepmerge/dist/es.js ***!
  \********************************************************************/
/*! exports provided: default */
/*! all exports used */
/***/ (function(module, __webpack_exports__, __webpack_require__) {
....

var deepmerge_1 = deepmerge;

/* harmony default export */ __webpack_exports__["default"] = (deepmerge_1);

/***/ }),
```

And therefore another module using it and not suspecting anything crashes:
https://unpkg.com/rest-facade@1.8.0/src/Client.js

```js
var deepmerge = require('deepmerge');

  this.options = deepmerge(defaultOptions, options || {}, true);
```

Because it naturally expects the plain and simple CommonJS export which is supposed to be a function.

Webpack tries to be overly smart in this case resulting in an incompatibility.

**If the current behavior is a bug, please provide the steps to reproduce.**

Create an application using `rest-facade` and it will throw "deepmerge is not a function" (because it's an object now for no reason).

**What is the expected behavior?**

Not throwing the aforementioned error

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by sokra** [comment]
I don't think webpack behaves wrong here. If a `module` field is provided this should be preferred over the `main` field for every system that support ESM. It's expected from the package to export the same API via CommonJS and ESM (which is not the case for deepmerge).

**Comment by catamphetamine** [comment]
So what you're saying is that all Node.js modules exporting `module.exports = ...` won't work in Webpack which is about 99% of all npm modules.

**Comment by sokra** [comment]
no that works fine.

The problem is specifying `module` and `main` in a package with different APIs.

Example:

``` js
// index.js
exports.value = "a";
```

``` js
// index.mjs
export const value = "b";
```

``` json
{
  "main": "./index",
  "module": "./index.mjs"
}
```

``` js
// cjs.js
const { value } = require("module");
console.log(value);
```

In node.js without ESM support this will log `a`.

In webpack this will log `b`.

---

=> Export the same API for your packages when providing ESM and CJS!

**Comment by catamphetamine** [comment]
What about this then:

```js
// index.common.js
module.exports = function convert(from, to) {}
```

```js
// index.es6.js
export default function convert(from, to) {}
```

```js
{
  "main": "./index.common",
  "module": "./index.es6"
}
```

```js
// application.js
var convert = require('convert')

// Throws "convert is not a function"
convert('a', 'b')

// Outputs "{ default: function convert() {} }"
console.log(convert)
```

The result is the application is broken because Webpack tried to be overly smart and chose `module` over `main` which resulted in wrong import.

**Comment by haggholm** [comment]
One problem is that different modules in the same build may import the same package in *different ways*. This is currently causing us problems in a project that uses `moment` and `react-datetime`.

Because we use ES6 imports, `moment` has already been imported by looking at the `module:` field. However, `react-datetime` imports it using `require()`. It seems that (because it’s the same import path, `import 'moment'` vs. `require('moment')`) the latter also gets the ES6 module—even though `DateTime.js` is a CommonJS module.

**Comment by catamphetamine** [comment]
Perhaps all modules loaded during Webpack build should be marked by the module system they're using: either CommonJS or ES6. Then, if a CommonJS-marked module `require()`s something then it should look into the `main` field first.

**Comment by pacey** [comment]
Is there a fix or workaround for this? I have the issue where deepmerge is coming in as transitive dependency so I can't change the way that library is importing/requiring it.

**Comment by TehShrike** [comment]
Related: https://github.com/webpack/webpack/issues/6584

**Comment by skhamoud** [comment]
@pacey can you update on how to deal with this . I have no control over it whatsover .

**Comment by pacey** [comment]
@skhamoud I couldn't find a way around it, so I actually have up on using Webpack for that build

**Comment by skhamoud** [comment]
Thanks @pacey , unfortunately I don't have that option and the alias suggestion from deepmerge didn't work either , thanks anyway .

**Comment by Mosho1** [comment]
Perhaps a way to override this would be useful?

**Comment by firesetter** [comment]
I was having this exact problem. I found that I could change it to prioritize using main instead of module with the following config option: 
`resolve: { mainFields: ["main", "module"] },`

Unfortunately this solution may cause other dependencies to break if they want module instead of main. Your mileage may vary.

**Comment by Antonio-Laguna** [comment]
What's the way ™ to go with this?

We have a lot of libraries that export `module` in ES6 and `main` transpiled but we end up having stuff not being transpiled then. Taking a couple of famous React modules such as:

https://github.com/react-bootstrap/react-bootstrap/blob/master/package.json

or 

https://github.com/react-toolbox/react-toolbox/blob/dev/package.json

I can see that I'm not going against convention here (nor the OP) yet I'm surprised not many people run into this. React needs to run both on the browser and node if SSR is in place so I'm not sure how to proceed here.

Example library here: https://github.com/firstandthird/domodule/blob/master/package.json#L6

**Comment by retorquere** [comment]
Can I configure webpack to only look at `main`? I'm loading `transliteration` and I currently have to do

```
import { transliterate } from 'transliteration/dist/node/src/node'
```

to prevent the umd-ified `transliteration` being loaded as specified in their `'package.json` in the  `browser` field (the umd-ified version does not work for me).

**Comment by ryancat** [comment]
I confirm this works. On top of that, I also found even we don't specify `module` property in package.json file, webpack 4 will still assume it's a module and will output ES6! I would need to have this in my webpack.config.js to opt-out that.

> I was having this exact problem. I found that I could change it to prioritize using main instead of module with the following config option:
> `resolve: { mainFields: ["main", "module"] },`
> 
> Unfortunately this solution may cause other dependencies to break if they want module instead of main. Your mileage may vary.

**Comment by haggholm** [comment]
@retorquere I haven’t used it, but that seems to be what `resolve.mainFields` is for: https://webpack.js.org/configuration/resolve/#resolve-mainfields

**Comment by retorquere** [comment]
@haggholm when I set

```
  resolve: {
    extensions: ['.ts', '.js'],
    mainFields: [ 'main' ], // or [ 'main', 'module' ], same results
  },
```

and I do

```
import { transliterate } from 'transliteration'
```

(where `transliteration` has `"main": "dist/node/src/node/index.js"`
I get

```
    ERROR in Circular dependency detected:
    node_modules/inherits/inherits.js -> node_modules/util/util.js -> node_modules/inherits/inherits.js
    
    ERROR in Circular dependency detected:
    node_modules/util/util.js -> node_modules/inherits/inherits.js -> node_modules/util/util.js
```

Whereas without `mainFields: [ 'main' ],` and using `import { transliterate } from 'transliteration/dist/node/src/node'` (which should do the same), webpack proceeds without error.

**Comment by retorquere** [comment]
I've just updated all my packages, among which `transliteration` (2.0.4 -> 2.1.2) and `webpack` (4.28.4 -> 4.29.0), and the problem has disappeared, no `mainFields` required.

**Comment by mlcohen** [comment]
We're running into this exact problem with D3 packages since they all use rollup for bundling. Each D3 package has a package.json file setup with a `main`, `module` and `unpkg` fields. For example, take a look at the d3-array package https://github.com/d3/d3-array/blob/master/package.json#L24. Notice that file extensions for each type are `.js`.

**Comment by ersel** [comment]
It would be great to be able to configure this per dependency basis.

**Comment by snewcomer** [comment]
Is this something that was fixed already in webpack?  I see this in the dist, which for a library that previously didn't have an esm entry point, nworks fine.

![Screenshot 2019-03-11 at 07 46 46](https://user-images.githubusercontent.com/7374640/54133296-0dc9cc00-43d3-11e9-9ceb-39d8b031b9e8.png)

**Comment by fclemonschool** [comment]
Is there a solution for this other than changing the webpack settings?
I am using a webpack via angular-cli.
Because of this problem, when I use an external library, module takes precedence and runs as es6. Therefore, IE support is not available.

**Comment by limonte** [comment]
@fclemonschool for SweetAlert2 I ended up with adding `"browser": "dist/sweetalert2.all.js"` : https://github.com/sweetalert2/sweetalert2/pull/1599/files

In your case it'll be `"browser": "dist/signature_pad.js",`

**Comment by rdsedmundo** [comment]
I hit this problem and it took me a while to figure out what was going on.

The error that was thrown is not intuitive at all so you start investigating everything. That's what I got:
```
/node_modules/date-fns/esm/format/index.js:1
import isValid from '../isValid/index.js';
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

I use `webpack` for compiling my backend application and I have `webpack-node-externals` to avoid bundling the `node_modules` folder. The `date-fns` package has both `module` and `main`, so `webpack` chose to use the ESM version, and Node 12 wasn't able to run it. If I remove the `externals` configuration it works as expected, because `webpack` will then parse the ES6 import before outputting it to the bundle, but I don't want to package `date-fns` inside the bundle, soat the end I stuck with the `mainFields` solution posted above.

**Comment by alexander-akait** [comment]
I think we can generate warning for these cases, so developers be able to identify the problem faster

**Comment by vankop** [comment]
Specifying `mainFields` is probably best work around for `webpack@5`. Nothing to do from webpack side.. 

Feel free to report new issues with repro.

**Comment by hayyaun** [comment]
> 

there is also ...(modules.webpackAliases || {}) there, should I put it before that or after it?

**Comment by hayyaun** [comment]
> I've solved that with this snippet:
> 
> ```
>     resolve: {
>         alias: {
>             "deepcopy": require.resolve("deepcopy")
>         }
>     }
> ```

            "deepcopy": require.resolve("deepcopy")
