### ISSUE TITLE
Chunk.hasRuntime throwing error

### ISSUE THREAD

**Issue by Vasikaran** [webpack/webpack#5758]
**Do you want to request a *feature* or report a *bug*?**
Yes.

**What is the current behavior?**
I wrote a plugin that work is just collect chunk info. So I decide to separate chunks and root chunks by **chunk.hasRuntime** method. But when I call that, that's throwing an error. The error is **Cannot read property 'entrypoints' of undefined**

Here are my plugins, 

```
class getChunkDetails{
   apply(compiler){
      compiler.plugin('compilation', (compilation)=>{
           let chunkInfo = {};
           let rootChunkInfo = {};
           compilation.plugin('chunk-asset', (chunk, name)=>{
                let { hasRuntime, id } = chunk;
                if (!hasRuntime()){
                      chunkInfo[id] = name;
                }else{
                      rootChunkInfo[id] = name;
                }
           })
      })
   }
}
```

**Comment by sokra** [comment]
``` js
let { a } = b;
a();
```

is not the same as 

``` js
b.a();
```

If you don't know why, read it up in a javascript book.

**Comment by Vasikaran** [comment]
I understood. It's a context problem. Thanks!
