### ISSUE TITLE
Problem with hanging build at 91%

### ISSUE THREAD

**Issue by bytewiz** [webpack/webpack#5759]
**What is the expected behavior?**
Hey guys, so my problem is my build is hanging at `91% additional asset processing`.
What I wish to understand is what going on in this step and if there is anyway to either skip or take this processing outside of webpack?
Note: this is when building quite a large codebase.

Second thing, is this expected build times given these specs:

Build time:
```
OS: Mac OSX
Processor: 2,2 GHz Intel Core i7
Memory: 16 GB 1600 MHz DDR3
Build time: ~250s
```
```
OS: Ubuntu
Processor: 1 CPU
Memory: 1 GB
Build time: ~20min
```

`node -v : v8.5.0`
`webpack: v3.4.1`

**Comment by sokra** [comment]
UglifyJs

**Comment by bytewiz** [comment]
@sokra awesome thanks!
