### ISSUE TITLE
Harmony imports/exports slow down rebuilds

### ISSUE THREAD

**Issue by filipesilva** [webpack/webpack#5763]
**Do you want to request a *feature* or report a *bug*?**
I want to discuss webpack behavior that may either be a bug or end up being a feature request.

**What is the current behavior?**
The number of harmony import/exports in an application increases rebuild time all code changes, even trivial ones that do not affect imports/exports.

This can be seen in CPU profiles of rebuilds, in `applyPluginsBailResult1` (under `seal`). The more harmony exports there are in an application, the more time is spend on this phase checking each one.

There is a reproduction below, where this can be see. The reproduction contains two precompiled Angular applications: one in JIT mode and one in AOT mode. In Angular, AOT mode generates more files than JIT mode. These files contain more harmony exports.

The JIT application rebuild spends `70.5`/`66.0` ms in this phase, whereas the AOT application takes 
`253`/`200.1` ms. Larger applications spend more time in this phase, even on rebuilds where no
import or export was altered (e.g. adding `console.log(1);`).

Here is a screenshot of the `applyPluginsBailResult1` phase in the JIT application:
![image](https://user-images.githubusercontent.com/4172079/31229241-f5b9bc74-a9d7-11e7-90f0-bf5d6b5b105a.png)

And here is the same for the AOT application:
![image](https://user-images.githubusercontent.com/4172079/31229345-43e32278-a9d8-11e7-9d66-0fcd5ef66a58.png)

The 160ms difference might not seem that drastic, but this is just a toy application. In bigger applications 
this phase takes much longer.

In the case of [Angular.io](https://github.com/angular/angular/tree/master/aio), a full rebuild in AOT mode total 4.5s, of which around 1.3s is spent on `applyPluginsBailResult1`. By comparison, the same code change takes only some 0.15s on the JIT (less imports/exports) version.

CPU profile of Angular.io JIT rebuild:
![image](https://user-images.githubusercontent.com/4172079/31229630-48d01e0c-a9d9-11e7-8501-a83b8425d5c0.png)

CPU profile of Angular.io AOT rebuild:
![image](https://user-images.githubusercontent.com/4172079/31229611-3444c8e8-a9d9-11e7-8c5e-1188cc832ca4.png)

I understand harmony imports/exports enable better optimizations and need to be checked because of that, but this seems a very steep increase in rebuild time that is outside of the control of loader/plugin authors. Perhaps there is a way to reduce the time spent on this phase.

**If the current behavior is a bug, please provide the steps to reproduce.**

A reproduction can be found in https://github.com/filipesilva/webpack-harmony-exports, together with CPU profiles for the seen behaviour.

Please note there are no loaders, all code is ES5 with ES2015 imports/exports.

**What is the expected behavior?**

Rebuilds that do not affect import/exports should not incur such a significant rebuild time due to harmony import/export checks.

**If this is a feature request, what is motivation or use case for changing the behavior?**

Rebuild speed is of utmost importance for application development.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Chrome 61, node v6.11.1, webpack 3.6.0, Windows 10

/cc @d3viant0ne

**Comment by sokra** [comment]
hmm ok... I see what's the slow part here...

I guess this can be improved with some refactoring...

**Comment by filipesilva** [comment]
Is this something I can help with?

**Comment by sokra** [comment]
You can try the PR if you want too?

**Comment by filipesilva** [comment]
Using your PR with the repro in my post, the JIT application spent roughly the same time (70ms) in the `applyPluginsBailResult1` phase:
![image](https://user-images.githubusercontent.com/4172079/31343814-a3f14fcc-ad08-11e7-88ae-d949b3b97e0d.png)

The AOT application spent about half the time (109ms) as previously:
![image](https://user-images.githubusercontent.com/4172079/31343834-b5576b0c-ad08-11e7-8d02-c97c7bfa024b.png)

On JIT Angular.io roughly the same time was spent (80ms):
![image](https://user-images.githubusercontent.com/4172079/31344086-91404dd2-ad09-11e7-9345-92a18b351e54.png)

On AOT Angular.io roughly third of the time (500ms) was spent:
![image](https://user-images.githubusercontent.com/4172079/31344263-1780a90a-ad0a-11e7-8818-5b7bb346bd17.png)
 
So your PR seems to reduce the harmony export checks time by at least half in small applications, and more than that in bigger applications. In Angular.io that's a 1s reduction in rebuilds, which is amazing.

Awesome work @sokra!
