### ISSUE TITLE
Unnecessary `require`/`define` when using UMD builds with `var` externals

### ISSUE THREAD

**Issue by NMinhNguyen** [webpack/webpack#5766]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When using a `var` external in a UMD build, the value of the external ends up inside `require` and `define` statements, however they are not actually used inside the bundle. For example, using a `var` external whose value is `foo.bar` (a more realistic example might be `top.someObject`), this value ends up in `require` and `define` statements.

**If the current behavior is a bug, please provide the steps to reproduce.**

* Checkout https://github.com/NMinhNguyen/webpack-umd-with-var-externals-example
* `npm install` or `yarn`
* `npm run build` or `yarn build`.

**What is the expected behavior?**

I may be missing something here, so I do apologise in advance 😅, but I'd expect these externals not to be `require`/`define`d as they do not end up being referenced anyway. I've actually tried modifying https://github.com/webpack/webpack/blob/15f4894ebe7d9b8e6658748573e18aed702f33fe/lib/UmdMainTemplatePlugin.js#L45 to filter `m.external && m.type !== 'var'`, which does achieve the desired behaviour, however I'm really not sure if that's the right place/way to fix it.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Node.js v8.4.0
webpack v3.6.0
macOS Sierra 10.12.6

**Comment by sokra** [comment]
Yep, you can check for `m.type !== "umd" && m.type !== "umd2"`. Send a PR
