### ISSUE TITLE
sourcemap collision when building as a library

### ISSUE THREAD

**Issue by MagicDuck** [webpack/webpack#5767]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
This happens when you have multiple webpack builds that integrate at runtime. For instance, I have a couple of projects that are built as webpack libraries (libraryTarget: "jsonp"). I use those libraries in a 3rd project. When I try to debug, I can see the sourcemaps for the libraries code in the devtool, but if you happen to have a file with the the same path in both libraries, for example:
"webpack:///src/index.js"
Then you basically just see the one for last loaded library...

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
We should have a way namespace those paths. Would be nice if you could change only the webpack:/// prefix independent on the devtool being used. Then we could switch it to something like: `webpack (<library name>):///`
I am guessing there should be some config option, a function, which is applied on the template as a last thing before usage. The reason for not using `output.devtoolModuleFilenameTemplate` is that there seem to be different defaults for different devtool settings...
**If this is a feature request, what is motivation or use case for changing the behavior?**
debugging webpack built lilbraries
**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by sokra** [comment]
Are you thinking about adding the `output.library` name to the devtool prefix by default? This makes sense to me, so send a PR.

**Comment by MagicDuck** [comment]
@sokra yes, will try to do that. I do have some questions though:
1. In my case, the library name is too convoluted since we have designed a "plugin loading" mechanism,
 where each plugin is a webpack lib. The library name is something like __mynamespace__['my.plugin.with.dots']. I would like to able to modify the devtool prefix with a function before usage. EvalDevToolModuleTemplatePlugin, EvalSourceMapDevToolModuleTemplatePlugin and SourceMapDevToolPlugin seem to have their own defaults that get overriden though WebpackOptionsApply. Is it ok to add the option of `output.devtoolModuleFilenameTemplate` being a function `(function(defaultTemplate : string) -> string)`, in which case it gets applied late, after the defaults have been set, rather than early? Or what would you consider to be the best way to approach this?
2. What do you think the the base default be? Something like this: `webpack:///([library])/[resourcePath]`. This would also affect the current non-library case. We could make library="main" or something in that case so you would get `webpack:///(main)/[resourcePath]`. Would that be ok though? Or should we just change [resourcePath] to include the library name? I am not sure if that could break other stuff...
3. What do we do about `css-loader`? It doesn't seem to respect the `output.devtoolModuleFilenameTemplate`. When I look at my ".css files" under webpack://, they all contain the js produced by the style-loader, it's not the original css. I don't think this is useful for the regular dev.

**Comment by sokra** [comment]
1. We could add a options `output.devtoolNamespace` which defaults to the `output.library` when not specified. This way you can override it when a custom name is needed. Although `__mynamespace__['my.plugin.with.dots']` will probably work too.
2. For the non-library build `devtoolNamespace` should be undefined, which will produce the same result as it does currently. With `devtoolNamespace` set to a value it produce the format you stated: `webpack:///[namespace]/[resourcePath]...`. The `[namespace]` placeholder need to be added to the moduleFilenameTemplate option.
3. On long term this will be integrated into webpack, so this is not an important issue. On short term we can add the `namespace` option to the style-loader too to generate source-maps in the same namespace.

**Comment by MagicDuck** [comment]
@sokra thanks for reply! Having `output.devtoolNamespace` option makes sense to me. For number 3, I guess I didn't really communicate that properly. The `css-loader` doesn't even put it's stuff under `webpack://` as far as I can see:   https://github.com/webpack-contrib/css-loader/blob/master/lib/loader.js#L117
![image](https://user-images.githubusercontent.com/95201/31569822-e5696e3a-b032-11e7-8fd6-9da4cedef282.png)
(Ignore some of the weird absolute paths under webpack://, It's cause my package.json is pointing to a local package)

**Comment by michael-ciniawsky** [comment]
@MagicDuck Feel free to open an Issue /PR at `style-loader/css-loader` in case there is any work required there :)

**Comment by MagicDuck** [comment]
I can do that. Just wanted to get to get @sokra 's opinion since he has the context to give a wholistic approach to the solution rather than piecemeal everywhere.

**Comment by sokra** [comment]
In my opinion a prefix for the CSS Source Maps does make sense. Maybe we shouldn't merge it into `webpack://` because it would conflict with the JS files. Maybe `webpack-css://` make sense here. I need to be configurable, because some tools like `create-react-app` don't like the prefix and like to use absolute resource paths instead.

**Comment by MagicDuck** [comment]
PR here: https://github.com/webpack/webpack/pull/5844 :)

**Comment by MagicDuck** [comment]
also filed issue on the `css-loader` side: https://github.com/webpack-contrib/css-loader/issues/622

**Comment by adrianromanko** [comment]
@MagicDuck  Thanks for adding this options. I'm waiting for your namespace PR request to go through.

**Comment by MagicDuck** [comment]
@adrianromanko my pleasure 😀. I looks it was merged a while ago. Its probably available in webpack 4.
This issue should probably be closed...

**Comment by jazdw** [comment]
Thanks for this, its useful when you build a library with multiple entry points. I use a library option like this `library: '[name]'` and without setting `devtoolNamespace` it shows up in the Chrome debugger as `%5Bname%5D`.

**Comment by MagicDuck** [comment]
@jazdw that sounds like a bug to me. You should file an issue I think. Closing this one.

**Comment by airtonix** [comment]
@jazdw Did you end up creating that ticket, also experiencing the same problem:

many entrypoints, many output bundles, each being a umd library with sourcemaps that all get called `[name]` in Chrome.

**Comment by jazdw** [comment]
@airtonix no I didn't sorry
