### ISSUE TITLE
Suggestion: Include chunk filename/URL in load failure error message

### ISSUE THREAD

**Issue by shousper** [webpack/webpack#5768]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

Failed chunk loads only report "Loading chunk `<ID>` failed" in `master`.
Failed chunk loads report "Loading chunk `<ID>` failed.\n(`<error-type>`: `<error-source>`)" in `next`.

**What is the expected behavior?**

Not really "expected", but for example: "Loading chunk ID `<id>` (`<url>`) failed.\n(`<error-type>`: `<error-source>`)"

**If this is a feature request, what is motivation or use case for changing the behavior?**

I came across https://github.com/webpack/webpack/issues/4595 while investigating another issue, and found the PR that made [this change](https://github.com/webpack/webpack/blob/next/lib/JsonpMainTemplatePlugin.js#L85) in the `next` branch which is great.

Including the URL for the chunk could also help solve issues where the filename or URL might hint at problems with: misconfigured cache busting (manifest isn't being generated or deployed), networking issues (firewalls with weird rules), adblockers (maybe the filename randomly contains a blocked string), just to name a few for ideas..

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

N/A

**Comment by sokra** [comment]
This is already implemented in the next branch -> webpack 4.

**Comment by sokra** [comment]
`<error-source>` === `<url>`
