### ISSUE TITLE
Bundling the rc module with webpack results in non-working app

### ISSUE THREAD

**Issue by tomc974** [webpack/webpack#5770]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When importing the `rc` module in an application, `webpack` will bundle it successfully but when run the application will throw an exception. It is as if the function exported by the `rc` module was executed by `webpack` even if the application doesn't call the function.

```shell
shell> webpack

Hash: 55aebddd47bf7a5ac100
Version: webpack 3.6.0
Time: 109ms
  Asset     Size  Chunks             Chunk Names
main.js  26.1 kB       0  [emitted]  main
   [1] ./src/main.js 58 bytes {0} [built]
   [3] (webpack)/buildin/module.js 517 bytes {0} [built]
    + 8 hidden modules

shell> node .\dist\src\main.js
...\dist\src\main.js:96
    throw new Error('rc(name): name *must* be string')
    ^
```

**If the current behavior is a bug, please provide the steps to reproduce.**
```javascript
// Application
const rc = require('rc')
console.log('OK')
````
```javascript
// Webpack configuration
const path = require('path')
const webpack = require('webpack')

module.exports = {
  context: __dirname,
  entry: './src/main.js',
  output: {
    filename: 'main.js',
    libraryTarget: 'commonjs',
    path: path.join(__dirname, './dist/src'),
  },
  module: {
    rules: [
      { loader: 'shebang-loader', test: /\.js$/ },
    ],
  },
  target: 'node',
}
```

**What is the expected behavior?**
`webpack` should not execute the function exported by a module automatically and the sample application provided above should display `OK` in the shell instead of throwing an exception.

**If this is a feature request, what is motivation or use case for changing the behavior?**
N/A

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Node.js 6.11.4 LTS and 8.6.0
Webpack 3.6.0
Windows 10 and Linux Mint 18.1

**Comment by tomc974** [comment]
**Additional information**
Note that the provided sample application requires the use of the `shebang-loader` module for the bundling to work but to rule out this module as the source of the bug, I also made a test by removing the shebang myself and by not using the `shebang-loader` module, the result was the same: running the application throw an exception instead of displaying `OK`.

**Comment by sokra** [comment]
The `rc` package offers a browser-compatible version, but sadly the package.json is only configured for `browserify`

see this line https://github.com/dominictarr/rc/blob/master/package.json#L6

it should be `"browser": "browser.js",` instead.

---

You could also fix it in your configuration with `resolve.alias: { "rc": "rc/browser" }`
