### ISSUE TITLE
Webpack CommonsChunkPlugin filename prop when async:true

### ISSUE THREAD

**Issue by kamleshchandnani** [webpack/webpack#5781]
**Do you want to request a *feature* or report a *bug*?**
*Bug*

**What is the current behavior?**
Context: [Twitter Thread](https://twitter.com/TheLarkInn/status/917260226407022592)
CommonsChunkPlugin doesn't allows to give the template for filename via ```filename``` prop when ```async:true```
At build time I get the error: ```You can not specify a filename if you use the “async” option```

**If the current behavior is a bug, please provide the steps to reproduce.**
just add 
```
new webpack.optimize.CommonsChunkPlugin({
    async: true,
    children: true,
    minChunks: 3,
    filename: "js/commonlazy-[chunkhash:8].js"
  })
```
to your plugins array.

**What is the expected behavior?**
@TheLarkInn mentioned this in the [medium](https://medium.com/webpack/webpack-bits-getting-the-most-out-of-the-commonschunkplugin-ab389e5f318) post that we can pass the ```filename```.
But the docs says:  It is possible to change the name of the output file by providing the desired string for "async" prop instead of `true`.
So was the ```filename``` prop added for some specific version which is now removed?
I have tried to trace from v2.4 onwards but never allowed to give ```filename``` prop in the ```commonschunkplugin```

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Webpack Version: 3.6.0

**Comment by sokra** [comment]
`async: String` sets the chunk name. It's not possible to set the `filename` of a async chunk, as it's part of the normal on-demand-chunking logic which doesn't allow setting the chunk filename.
