### ISSUE TITLE
Unable to skip asynchronous "pitch" loader

### ISSUE THREAD

**Issue by jugglinmike** [webpack/webpack#5782]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**Sample project files**

- `webpack.config.js`:
  ```js
  'use strict';
  var path = require('path');
  
  module.exports = {
    entry: './src/main.js',
    output: {
      path: path.resolve(__dirname, 'dist'),
      filename: 'bundle.js'
    }
  };
  ```
- `src/main.js`:
  ```js
    'use strict';
    
    require('../pitch-loader?skip=true!./other');
    require('../pitch-loader?skip=false!./other');
    require('../pitch-loader?async=true&skip=true!./other');
    require('../pitch-loader?async=true&skip=false!./other');  
  ```
- `src/other.js`:
  ```js
  'use strict';
  ```
- `pitch-loader.js`:
  ```js
  'use strict';
  
  var skip = /skip=true/;
  var async = /async=true/;
  
  function sync(query) {
    if (skip.test(query)) {
      return;
    }
  
    return '2 + 2;';
  }
  
  exports.pitch = function() {
    var query = this.query;
    var done;
  
    if (async.test(query)) {
      done = this.async();
  
      setTimeout(function() {
        done(null, sync(query));
      }, 0);
  
      return;
    }
  
    return sync(query);
  };
  ```

```
$ ./node_modules/.bin/webpack
Hash: 1c0278d58fd909cb2c28
Version: webpack 3.6.0
Time: 124ms
    Asset     Size  Chunks             Chunk Names
bundle.js  3.71 kB       0  [emitted]  main
   [0] ./src/main.js 223 bytes {0} [built]
   [1] ./pitch-loader.js?skip=true!./src/other.js 14 bytes {0} [built]
   [2] ./pitch-loader.js?skip=false!./src/other.js 6 bytes {0} [built]
   [3] ./pitch-loader.js?async=true&skip=true!./src/other.js 831 bytes {0} [built] [failed] [1 error]
   [4] ./pitch-loader.js?async=true&skip=false!./src/other.js 6 bytes {0} [built]

ERROR in ./pitch-loader.js?async=true&skip=true!./src/other.js
Module build failed: Error: Final loader didn't return a Buffer or String
```

(error stack omitted)

```
$ ./node_modules/.bin/webpack --version
3.6.0
$ node --version
v6.10.3
```

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

I would like to skip the pitch loader according to a condition that can only be
determined asynchronously. Webpack's documentation
[describes](https://webpack.js.org/api/loaders/#pitching-loader) (somewhat
implicitly) how synchronous "pitch" loaders which return the value `undefined`
are skipped over during loading:

> [...] If a loader delivers a result in the `pitch` method the process turns
> around and skips the remaining loaders, continuing with the calls to the more
> left loaders. [...]

However, when an asynchronous pitch loader "returns" the value `undefined`
(i.e. by invoking the `this.callback` method with the arguments `null`, and
`undefined`), Webpack reports the error, "Final loader didn't return a Buffer
or String."

It is possible to work around this problem by designing the pitch loader to
construct a "pass through" module in cases where additional loading is not
necessary. This could look something like this:

```js
exports.pitch = function() {
  var done = this.async();

  setTimeout(function() {
    var src = 'module.exports = require(' + JSON.stringify('-!' + remainingRequest) + ')';
    done(src);
  }, 0);
};
```

However, this is not ideal because the resultant module unecessarily
complicates dependency graphs (which my team will use to interpret project
organization).

Would the maintainers entertain a patch that caused Webpack's loading mechanism
to skip pitch loaders under these conditions?

**Comment by sokra** [comment]
Try this:

``` js
    setTimeout(function() {
      var r = sync(query);
      if(r === undefined)
        done(null);
      else
        done(null, r);
    }, 0);
```

**Comment by jugglinmike** [comment]
That works on my end--thank you!

That said, this behavior is implicit and undocumented. I'd be happy to work on a patch to make Webpack more consistent in how it interprets the value `undefined`, but I'll wait on your input before starting. Let me know!

**Comment by sokra** [comment]
Yep that makes sense. See webpack/loader-runner for the relevant code.

**Comment by jugglinmike** [comment]
Thanks for the tip! I've submitted a patch to that project here: https://github.com/webpack/loader-runner/pull/24

**Comment by jugglinmike** [comment]
@sokra This bug has a pull request, it's just blocked on a confusing linting error. Can you please offer some guidance there?
