### ISSUE TITLE
Cannot read property 'Blob' of undefined

### ISSUE THREAD

**Issue by imkimchi** [webpack/webpack#5788]
**Do you want to request a *feature* or report a *bug*?**

A bug

**What is the current behavior?**
entry file will build literally just fine, but the error occurs on client side, which makes the whole bundle file doesn't work with this issue `Uncaught TypeError: Cannot read property 'Blob' of undefined`

`webpack.config.js`

```
const path = require('path')
const webpack = require('webpack')
const HtmlPlugin = require('html-webpack-plugin')
const ExtractTextPlugin = require('extract-text-webpack-plugin')

const config = {
    entry: './src/main-entry.js',
    output: {
        path: path.resolve(__dirname, 'views/dist'),
        filename: 'bundle.js'
    },
    module: {
        rules: [
            { test: /\.(png|woff|woff2|eot|ttf|svg|gif)$/, loader: 'url-loader?limit=100000' },
            {
                test: /\.css$/,
                use: ExtractTextPlugin.extract({
                    use: 'css-loader', fallback: 'style-loader'
                })
            },
            {
                test: /\.js$/,
                loader: 'babel-loader',
                exclude: /node_modules/
            }
        ]
    },
    plugins: [
        new ExtractTextPlugin('bundle.css'),
        new webpack.optimize.UglifyJsPlugin({
            include: /\.min\.js$/,
            minimize: true
        })
    ]
}

module.exports = config

```

**If the current behavior is a bug, please provide the steps to reproduce.**

I don't even have no idea why this happens.

**What is the expected behavior?**

to just work fine

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

OS: Windows 7
Node: 8.1.2
webpack: latest

**Comment by Kondax** [comment]
Disabling name mangling in the UglifyJS plugin.

**Comment by evilebottnawi** [comment]
@imkimchi problem still exists?

**Comment by ooflorent** [comment]
Issue was closed because of inactivity.
If you think this is still a valid issue, please file a new issue with additional information.
