### ISSUE TITLE
Webpack NormalModule swallows loader errors

### ISSUE THREAD

**Issue by guilhermevrs** [webpack/webpack#5796]
**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**

Loaders bubble up errors but webpack NormalModule swallows it

**If the current behavior is a bug, please provide the steps to reproduce.**

Force an error in a loader (e.g. sass-loader) and run it until line 284 of lib/NormalModule.js

`return callback();`

**What is the expected behavior?**

When NormalModule sees it's an error, the error should be bubble up to Compilation.js so that the line 170 can be executed.

``this.applyPlugins2("failed-module", module, error);``

**If this is a feature request, what is motivation or use case for changing the behavior?**

Not a feature request

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Webpack version: ``3.6.0``

**Comment by evilebottnawi** [comment]
@guilhermevrs can you describe you problem more verbosely?
