### ISSUE TITLE
How to ensure that CSS loads before JS in webpack-dev-server?

### ISSUE THREAD

**Issue by perny** [webpack/webpack#5798]
**Do you want to request a *feature* or report a *bug*?**
a feature

**What is the current behavior?**
in index.js

import './index.pug';
import './css/index.scss';//reset chrome normal css

document.querySelector('body').clientWidth; //is wrong
//but
setTimeout(function(){
      document.querySelector('body').clientWidth; //is right
},5000)

why?

Thank you!

**If this is a feature request, what is motivation or use case for changing the behavior?**
How to ensure that CSS loads before JS in webpack-dev-server?
**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
"webpack": "^3.5.5",
"webpack-dev-server": "^2.7.1",

**Comment by sokra** [comment]
Not a webpack issue.

Please submit support requests and questions to StackOverflow. StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md).
