### ISSUE TITLE
Docs: Creating tree-shaking able library with webpack

### ISSUE THREAD

**Issue by a-x-** [webpack/webpack#5801]
*feature*

Can you describe in documentation how to create library with es-modules with webpack?

**What is the current behavior?**

tree-shaking does not work with `libraryTarget: commonjs`

**browser version, Node.js version, webpack version and Operating System.**

webpack@latest (3.6.0)

**Comment by a-x-** [comment]
`webpack.config.js example:`
```json5
{
  // ...
  output: {
    path: path.resolve(__dirname, 'build'),
    library: 'lib',
    filename: 'main.js',
    libraryTarget: 'commonjs',
  }
  externals: {
    react: {
      root: 'React',
      'commonjs-module': 'react',
      commonjs2: 'react',
      commonjs: 'react',
      amd: 'react',
    },
  },
  plugins: [
    new UglifyJsPlugin({ sourceMap: true })
  ]
}
```

**Comment by sokra** [comment]
It's better to not bundle libraries. Stay with a modular version of it, better written in ESM.

If you don't want this: https://rollupjs.org/ allows to bundle ESM to ESM.

**Comment by a-x-** [comment]
I want to do not bundle, but I cannot. Can you suggest correct direction?

project/src/index.js:
```js
import React from 'react';
import { foo } from 'lib';
console.log('lib', foo());
```

It transpiles to:
`...... console.log('lib', Object(__WEBPACK_IMPORTED_MODULE_1_lib__[\"a\" /* foo */])()); ........`
And I got an error: `Uncaught TypeError: Object(...) is not a function`

project/webpack.config.js:
```js
//...
  {
    test: /\.jsx?$/,
    // exclude: /node_modules/,
    include: [conf.paths.src, ...conf.paths.include], // contains path to *lib*
    use: [
      { loader: 'babel-loader', options: babelLoaderOptions },
    ],
  },
//...
```

lib/src/index.js:
```js
import React from 'react';
export { default as foo } from './foo';
export { default as bar } from './bar';
...
```

lib/package.json:
```json5
{
    // ...
    main: 'src'
}
```
