### ISSUE TITLE
Filter Dynamic Import Statements

### ISSUE THREAD

**Issue by ljcrapo** [webpack/webpack#5805]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

We have dynamic **import().then()** statements and we have **require.context**.

**What is the expected behavior?**

I'd like to take the filter functionality from require.context and add it to dynamic imports using comment args just like we do for assigning chunk names. 

EG: 
``` javascript 
import(
  /* filter: /\.(?:js|tsx?)$/ */
  "./someDir/" + theFileIWant
).then(...)
```

**If this is a feature request, what is motivation or use case for changing the behavior?**

sometimes it's difficult to demonstrate in string literal form what will actually be imported at run-time. This will give us more control over what modules are bundled on a dynamic import.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

I'm willing to work on a pull request for this feature if I can get enough support from the community.

**Comment by sokra** [comment]
Yep, send a PR.

**Comment by ljcrapo** [comment]
https://github.com/webpack/webpack/pull/5809
