### ISSUE TITLE
ExternalModule throws on hashing `optional`

### ISSUE THREAD

**Issue by STRML** [webpack/webpack#5806]
**Do you want to request a *feature* or report a *bug*?**

Bug in 3.7.0

**What is the current behavior?**

Crash on https://github.com/webpack/webpack/blob/551ea76838f163a1e0fbf65182e2ac08d346a1f3/lib/ExternalModule.js#L123

```
TypeError: Data must be a string or a buffer
```

Reason is that `this.optional` is `undefined`, and `JSON.stringify(undefined)` does not produce `"undefined"` as you might expect, it produces `undefined`.

**If the current behavior is a bug, please provide the steps to reproduce.**

Include a basic external module. In my case, I had `/^react(?:\/.*)?$/` in my `externals` and this was crashing on the `request` to `react`.

**What is the expected behavior?**
Don't crash.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Webpack 3.7.0

PR incoming.

**Comment by sokra** [comment]
Do you want to send a PR fixing it?

**Comment by STRML** [comment]
It's in

**Comment by sokra** [comment]
Thanks. Published as 3.7.1
