### ISSUE TITLE
Unable to setup bootstrap-sass

### ISSUE THREAD

**Issue by venkataramkishore** [webpack/webpack#5808]
**Do you want to request a *feature* or report a *bug*?**
Bug

ERROR in ./node_modules/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.eot
Module parse failed: D:\workspaces\visualstudio-workspace\webpack3.6\node_modules\bootstrap-sass\assets\fonts\bootstrap\glyphicons-halflings-re
gular.eot Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/style/index.scss 6:4172-4253 6:4276-4357
 @ ./src/style/index.scss
 @ ./src/app.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server babel-polyfill ./src/app.js

ERROR in ./node_modules/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.ttf
Module parse failed: D:\workspaces\visualstudio-workspace\webpack3.6\node_modules\bootstrap-sass\assets\fonts\bootstrap\glyphicons-halflings-re
gular.ttf Unexpected character ' ' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/style/index.scss 6:4639-4720
 @ ./src/style/index.scss
 @ ./src/app.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server babel-polyfill ./src/app.js

ERROR in ./node_modules/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.woff
Module parse failed: D:\workspaces\visualstudio-workspace\webpack3.6\node_modules\bootstrap-sass\assets\fonts\bootstrap\glyphicons-halflings-re
gular.woff Unexpected character ' ' (1:4)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./node_modules/css-loader!./node_modules/sass-loader/lib/loader.js!./src/style/index.scss 6:4525-4607
 @ ./src/style/index.scss
 @ ./src/app.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server babel-polyfill ./src/app.js

Yes, its clear but i tried with various helps from stackoverflow still have same error, i have tried with all relevant loaders still the same output.

I am not a designer or UXUI to understand well in SASS but i was trying to just setup a simple bootstrap with sass using webpack 3.6.6 release version and following guide and for issues stackOverflow, my brain is ofcourse overflowed but no luck. Following is the repo of my work
https://github.com/venkataramkishore/webpack3.6/tree/webpack3.6-sass

 If you were able to fix please guide me.

**What is the current behavior?**
Simple sass setup as per guide using bootstrap-sass@3.3.7
**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/venkataramkishore/webpack3.6/tree/webpack3.6-sass

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**
Motivation to create separate build setup for various frameworks we use for regular development. Ofcourse we still have "frameworks"-cli although want to learn this build system better.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Chrome 61 updated, Node 6.11.X, webpack 3.6.6, Window XP

**Comment by sokra** [comment]
merge `module.loaders` into `module.rules`. You can't have both.

**Comment by venkataramkishore** [comment]
Thank you it worked!!
