### ISSUE TITLE
Failed to apply HMR update

### ISSUE THREAD

**Issue by juncaixinchi** [webpack/webpack#5813]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Failed to apply HMR update

**If the current behavior is a bug, please provide the steps to reproduce.**

update webpack from v2 -> v3.7.1
update react-hot-loader from v1.3.1 -> v3.0.0

webpack.config.js:
```js
const path = require('path')
const webpack = require('webpack')

module.exports = {
  output: {
    path: path.join(__dirname, 'public'),
    filename: 'bundle.js'
  },
  target: 'electron-renderer',
  devtool: 'eval-source-map',
  entry: [
    'webpack/hot/poll?1000',
    './src/app.jsx'
  ],
  stats: { colors: true, minimal: true },
  resolve: { extensions: ['.js', '.jsx', '.css', '.json'] },
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        use: ['react-hot-loader/webpack', 'babel-loader']
      },
      {
        test: /\.css$/,
        use: ['style-loader', 'css-loader']
      },
      {
        test: /\.json$/,
        loader: 'json-loader'
      }
    ]
  },
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new webpack.DefinePlugin({ 'global.GENTLY': false })
  ]
}
```

set `target: 'electron-renderer'`:

```
Failed to load resource: net::ERR_FILE_NOT_FOUND
webpack-internal:///71:25 [HMR] Update failed: Error: Manifest request to 21d5fcb124cced9d3615.hot-update.json timed out.
    at XMLHttpRequest.request.onreadystatechange (file:///home/lxw/GitHub/WX-App/public/bundle.js:64:22)
```

set `target: electron`, and modify something in src

```
log.js?4244:25 [HMR] Error: Aborted because 124 is not accepted
Update propagation: 124 -> 121
    at hotApply (file:///home/lxw/GitHub/WX-App/public/bundle.js:416:30)
    at file:///home/lxw/GitHub/WX-App/public/bundle.js:265:21
    at <anonymous>
module.exports @ log.js?4244:25
(anonymous) @ poll.js?78e9:23
log.js?4244:25 [HMR] You need to restart the application!
```

reproduceable repo: 

https://github.com/juncaixinchi/WX-App

script to run: 

```
git clone https://github.com/juncaixinchi/WX-App.git
cd WX-App
npm i
npm run webpack
npm start // another terminal
```
**What is the expected behavior?**

HMR update successfully

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

electron: v1.7.9

Node.js: v8.2.1

webpack: v3.7.1

Operating System: ubuntu 16.10

**Comment by sokra** [comment]
Could you add the `NamedModulesPlugin` and take another look at the error message?

**Comment by WisnucCDCI** [comment]
error message after `NamedModulesPlugin` added
![screenshot from 2017-10-13 09-41-00](https://user-images.githubusercontent.com/28702154/31526654-d1b579c0-affa-11e7-8f40-1dfd91a9d49d.png)

**Comment by juncaixinchi** [comment]
error message after `NamedModulesPlugin` added
![screenshot from 2017-10-13 09-41-00](https://user-images.githubusercontent.com/8253814/31526703-173c4262-affb-11e7-81fb-6cbe9cce47c9.png)
