### ISSUE TITLE
Performance degradation in build times after upgrade to 3.7.1

### ISSUE THREAD

**Issue by creage** [webpack/webpack#5814]
**Do you want to request a *feature* or report a *bug*?**
A bug

**What is the current behavior?**
We build our main app as a [Dll](https://webpack.js.org/plugins/dll-plugin/), and after recent upgrade we experience huge build times compared to what we had before upgrade.

It takes **~30** seconds to complete our initial build, comparing to **~18** on webpack 3.6.0.
Rebuilds in watch mode now take **~12** seconds, and they were **less than a second** before upgrade.
We had no [bundle duplication](https://github.com/samccone/bundle-buddy) before upgrade, and now we have tons of them.

**If the current behavior is a bug, please provide the steps to reproduce.**
I'm not sure if I could provide any right now, as we have really huge project. I'll try to setup a demo env soon.

**What is the expected behavior?**
Release notes [state](https://github.com/webpack/webpack/releases/tag/v3.7.0) about performance fixes, but I'd expect it to be at least the same as before upgrade.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Node 8.6.0
Windows 7,
Webpack 3.7.1

**Comment by tquetano-r7** [comment]
Experiencing this as well. We too have a very large project, and build times have slowed tremendously, with lots of bundle duplication.

**Comment by sokra** [comment]
> We had no bundle duplication before upgrade, and now we have tons of them.

Sounds like the changes intruduced a bug in the algorithm. It would be great if you can construct a repro case for the duplication. I'm pretty sure the duplication is the origin of the performance problem.

**Comment by sokra** [comment]
Ok I have an idea of a fix, but wasn't able to construct a testcase yet. If you want to you can try doing this change in `webpack/lib/Compilation.js` line 1004:

``` diff
			let minAvailableModules = minAvailableModulesMap.get(chunk);
			if(minAvailableModules === undefined) {
				minAvailableModulesMap.set(chunk, new Set(availableModules));
			} else {
				let deletedModules = false;
				for(const m of minAvailableModules) {
					if(!availableModules.has(m)) {
						minAvailableModules.delete(m);
						deletedModules = true;
					}
				}
				if(!deletedModules)
					continue;
+				availableModules = minAvailableModules;
			}
```

**Comment by sokra** [comment]
It could also be cause by the change in the CommonChunkPlugin. Do you use it?

If you want to you can try to `git bisect` the issue.

**Comment by creage** [comment]
@sokra right - we are using CommonsChunkPlugin as well, but it is rather simple one
``new webpack.optimize.CommonsChunkPlugin({
			name: 'App',
			children: true,
			minChunks: 2
		})``

**Comment by sgal** [comment]
@creage The thing is that the changes in `CommonsChunkPlugin` are affecting `children: true` as well. See https://github.com/webpack/webpack/pull/5764/files#diff-1f5e5440c51d8accc603eb6f399cf08bR260

**Comment by ljcrapo** [comment]
looking at the code again, we may possibly have lost the following functionality: 
``` javascript 
if(!asyncOption)		
	return chunk.parents.length === 1;
```
which would affect all cases where you are using `children`, **not** using `async`, and the chunk has more than just the common chunk as a parent.
https://github.com/webpack/webpack/pull/5764/files#diff-1f5e5440c51d8accc603eb6f399cf08bL237

but, again, this is all guess work. We won't be able to know for sure until someone comes up with a repro case.

**Comment by sokra** [comment]
@ljcrapo Yep I thought that as well. But the replacement code:

``` js
if(asyncOption || chunk.parents.every((parentChunk) => parentChunk === targetChunk || affectedChunks.has(parentChunk))) {
```

should have similar effect.

I guess we can't fix this without a repro case.

It also looks like only very few people are affected as no one else reported this so far.

@creage @tquetano-r7 If you want to get this fixed, we need your help.

**Comment by creage** [comment]
@sokra I've disabled CommonsChunkPlugin completely, and my build times now reduced, but they are still high comparing to 3.6.0: initial build takes ~25 secs, rebuild in watch mode is ~7 seconds. I've tried to create a simple repo, but cannot reproduce the behavior. I need more time to find the reason.

**Comment by creage** [comment]
@sokra just upgraded to 3.8.0, and I see these

![image](https://user-images.githubusercontent.com/910967/31657172-07d357d0-b32e-11e7-90cc-5eb29f0fde0a.png)

Build times are now back to normal. Thank you very much!

**Comment by sokra** [comment]
Ok great. I wasn't sure if it was related, but great to see it was.

@tquetano-r7 Do you see the same effect?

**Comment by tquetano-r7** [comment]
@sokra i just updated to `3.8.1` ... build time breakdown looks different (more time sealing / optimizing, less time building modules), but is roughly equivalent to what it was in `3.6.0`. certainly not the problem it was prior, well done!
