### ISSUE TITLE
Module version resolution/resolve problem

### ISSUE THREAD

**Issue by theKashey** [webpack/webpack#5819]
**Do you want to request a *feature* or report a *bug*?**
A bug

**What is the current behavior?**
Some problem with module resolution. Nested node_modules are not always used.
**If the current behavior is a bug, please provide the steps to reproduce.**
Download this repo - https://github.com/Koenkk/react-hot-loader-problem/blob/master/app/App.js#L18
Run npm install (not yarn)
Checkout ./node_modules/react-hot-loader/lib/AppContainer.dev.js

**What is the expected behavior?**
./node_modules/react-hot-loader/lib/AppContainer.dev.js will contain next code 
```js
var React = __webpack_require__("./node_modules/react/index.js"); <- points to top most React.
var PropTypes = __webpack_require__("./node_modules/prop-types/index.js");
var deepForceUpdate = __webpack_require__("./node_modules/react-deep-force-update/lib/index.js");
```
But the last require is wrong.
The project will require the latest version of react-deep-force-update, but shrinkwrap it to v1. And react-hot-loader will have react-deep-force-update v2 as nested dep. And that dep should be used, but will be not.
So actually this is about wrong configuration, but you should stand it.

More about it - https://github.com/gaearon/react-hot-loader/issues/668#issuecomment-336298074
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by sokra** [comment]
You did override the resolve configuration to behave like this: https://github.com/Koenkk/react-hot-loader-problem/blob/master/webpack.config.js#L93

**Comment by theKashey** [comment]
That was not me :)
