### ISSUE TITLE
Loading jquery before angular and DOMContentLoaded (angular and jquery)

### ISSUE THREAD

**Issue by jdivock** [webpack/webpack#582]
Just for some brief background, angular by default will load it's own jquery spinoff jqlite for DOM queries and manipulations, unless it sees jquery in which case it'll use that instead. From the angular docs:

> To use jQuery, simply load it before DOMContentLoaded event fired.

Recently I converted over my angular application to use webpack and this is one of the only things left I've been unable to solve. I haven't found a way to have webpack load jquery prior to angular or prior to DOMContentLoaded for it to default to jquery. For the moment I'm just using $() to explicitly call jquery where I need to rather than relying on angular.element() which will fall back to jqlite. I was hoping the authors or any other heavy users of webpack would have some insight here as I've been unable to make this work on my own. Thanks.

**Comment by jcubic** [comment]
I've try:
```javascript
{ test: /jquery(\.min)?\.js$/, loader: 'expose?jQuery' }
```
but got error:
```
ERROR in ./~/angular/angular.js
Module not found: Error: Cannot resolve module 'expose'
```

**Comment by jcubic** [comment]
running this ` npm install expose-loader --save` solve the issue.

**Comment by fredriks** [comment]
An alternative is to use [ProviderPlugin](http://webpack.github.io/docs/list-of-plugins.html#provideplugin) to automatically load jQuery when [angular looks for it](https://github.com/angular/angular.js/blob/v1.5.8/src/Angular.js#L1776).

```js
new webpack.ProvidePlugin({'window.jQuery': 'jquery'})
```

**Comment by woohling** [comment]
I'm not sure My situation fits. I used fancyBox plugin, and this plugin generated html `<a href="javascript:jQuery.fancybox.jumpto(1);" `. When I clicked this anchor, the error was jQuery is not defined. I used all the methods mentioned above, but still didn't work. 
Any help please? I use Angular and webpack together BTW.

**Comment by mccool** [comment]
@jdivock @fredriks solution worked for me. You need to specify `'window.jQuery'` not simply `jQuery` or `$`. I originally had
```javascript
new webpack.ProvidePlugin({
  $: 'jquery',
  jQuery:'jquery'
})
```
but was still seeing jQLite elements in my directives until i added `'window.jQuery':'jquery'`. I had to keep `jQuery:'jquery'` because i was seeing an error from transition.js about jQuery being undefined. I don't have the time at the moment to understand why since a simple line fixes it. 

Thanks!

**Comment by theangular** [comment]
Also this https://angulars.space/questions/ways-to-execute-a-jquery-function-in-angular-2-post-the-completion-of-each-component-load

**Comment by jcubic** [comment]
@theangular this is a question from 2014 about AngularJS aka Angular 1
