### ISSUE TITLE
ProvidePlugin doesn't work on modules that have "polyfill guards"

### ISSUE THREAD

**Issue by fstanis** [webpack/webpack#5828]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
If a module polyfills an API, e.g. fetch, the module code might check if `window.fetch` is already defined:
```js
if (typeof fetch === 'undefined') {
  module.exports = // fetch polyfill
} else {
  module.exports = fetch;
}
```
This module can then be included by using e.g. `const fetch = require('fetch-polyfill');` or, ideally, via `ProvidePlugin`:

```js
module.exports = {
  ...
  plugins: [
    ...
    new webpack.ProvidePlugin({
      fetch: 'fetch-polyfill'
    })
  ]
}
```

However, this doesn't work - since `fetch` is used in the module itself (`if (typeof fetch...`), this "confuses" webpack and `fetch` becomes an empty object (`{}`). Importing the module as anything other than "fetch" works fine, e.g.
```js
module.exports = {
  ...
  plugins: [
    ...
    new webpack.ProvidePlugin({
      myfetch: 'fetch-polyfill'
    })
  ]
}
```
...but this defeats the purpose of a polyfill.

[webextension-polyfill](https://github.com/mozilla/webextension-polyfill) relies on this "polyfill guard", which if how I found out about the issue.

**If the current behavior is a bug, please provide the steps to reproduce.**
https://gist.github.com/fstanis/450776f48682e6ff85b7c7ba366a5d1e

**What is the expected behavior?**
`ProvidePlugin` matching the behaviour of `const <name> = require('<module>');`

**Comment by Velveeta** [comment]
Should you be referencing that with a namespace prefix? Like:
```javascript
if (typeof window.fetch === 'undefined') {
  module.exports = // fetch polyfill
} else {
  module.exports = window.fetch;
}
```

**Comment by fstanis** [comment]
Agreed, that's what [I suggested to webextension-polyfill](https://github.com/mozilla/webextension-polyfill/issues/68) - still, I felt it's a bug with ProvidePlugin how this "self-referencing" is handled (at the very least, I'd expect an error).

**Comment by sokra** [comment]
You should be able to workaround this with:

``` js
module: {
 rules: [
  {
    test: require.resolve('fetch-polyfill'),
    use: "imports-loader?fetch=>undefined"
  }
 ]
}
```

**Comment by NN---** [comment]
What is the solution for core-js provide 
For instance:
ProvidePlugin([“Object.assign”: “core/fn/Object/assign”])

Unfortunately in this case it replaces Object.assign in core-js and there is no way to say to not replace there.

**Comment by ooflorent** [comment]
Issue was closed because of inactivity.
If you think this is still a valid issue, please file a new issue with additional information.
