### ISSUE TITLE
Rule.issuer - what properties belong to it? What does the option do?

### ISSUE THREAD

**Issue by wzup** [webpack/webpack#5829]
From you [docs](https://webpack.js.org/configuration/module/#rule-conditions):

> In a Rule the properties test, include, exclude and resource are matched with the resource and the property issuer is matched with the issuer.

> You can either supply a `Rule.resource` option or use the shortcut options `Rule.test`, `Rule.exclude`, and `Rule.include`

So we have:
```
    {
        resource: {
            test: ...,
            include: ...,
            exclude: ...,
        },
        issuer: { ...boom?? }
    }
```

There is nothing for `issuer` in your reference. What properties belong to it? What is it for? What does `issuer` do?

**Comment by sokra** [comment]
`resource`, `issuer`, `resourceQuery` and `compiler` can all have the same properties:

``` js
issuer: {
  test: ...,
  include: ...,
  exclude: ....,
  and: ....,
  or: ....,
},
issuer: /regexp/,
issuer: [{ ... }, { ... }] // matched with or
```

@webpack-bot move to webpack/webpack.js.org
