### ISSUE TITLE
Does resourceQuery belong to Rule.resource?

### ISSUE THREAD

**Issue by wzup** [webpack/webpack#5830]
> In a Rule the properties `test`, `include`, `exclude `and `resource `are matched with the **resource**

[Rule.resourceQuery](https://webpack.js.org/configuration/module/#rule-resourcequery) :

> A Condition matched with the resource query. The condition matches against a string that starts with a question mark ("?exampleQuery"). See details in Rule conditions.

And your example present only shortcut version.
```
{
  test: /.css$/,
  resourceQuery: /inline/, // foo.css?inline
  use: 'url-loader'
}
```

Does `resourceQuery` belong to `Rule.resource`?
```
    {
        resource: {
            test: ...,
            include: ...,
            exclude: ...,
            resourceQuery: ???
        }
    }
```

**Comment by sokra** [comment]
`resource` and `resourceQuery` are on the same level.

for `/path/to/file.js?123` => `resource: "/path/to/file.js", resourceQuery: "?123"`

@webpack-bot move to webpack/webpack.js.org
