### ISSUE TITLE
Support CoffeeScipt 2 for webpack.config.coffee

### ISSUE THREAD

**Issue by Fudoshiki** [webpack/webpack#5831]
**Do you want to request a *feature* or report a *bug*?**
- proposal

**What is the current behavior?**
`webpack.config.coffee` fails with installed CoffeeScript 2.0. CoffeeScript 2.0 compiles code to ES6

```bash
webpack -p
/Users/sharevari/Repository/test_app/webpack.config.coffee:3
import path from 'path';
^^^^^^

SyntaxError: Unexpected token import
```

**If the current behavior is a bug, please provide the steps to reproduce.**
- add `"coffeescript": "^2.0.1"` and `"webpack": "^3.4.1"` in `package.json`

- run `npm i` or `yarn`
- create `webpack.config.coffee`
``` coffee
import path from 'path'
import webpack from 'webpack'

export default
  context: path.resolve __dirname, 'js'
  entry: './app.js'
  output:
    path: path.resolve __dirname, 'dist'
    filename: 'bundle.js'
```
- run `webpack -p`

**What is the expected behavior?**
- webpack precompilation

**If this is a feature request, what is motivation or use case for changing the behavior?**

In CLI we can run `coffee -t path/to/file.coffee` or `coffee --transpile path/to/file.coffee` to compile ES5

But when we run `webpack -p`, we can't write `coffee -t webpack -p`.

Webpack register coffescript/register module via node module require for webpack.config.* files.
No options to pass `--transpile`

http://coffeescript.org/#transpilation

Config must be transpiled to ES5 before passing to webpack

coffee 2 -> ES6 -> babel.transform to ES5 -> webpack run config

Maybe as option add support .babel.coffee files

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
- macOS High Sierra 10.13.1
- CoffeeScript 2.0.1
- Webpack 3.4.1

**Comment by sokra** [comment]
js-interpret handles this.
