### ISSUE TITLE
commonschunk bug last webpack 3.7.1

### ISSUE THREAD

**Issue by simonjoom** [webpack/webpack#5832]
**Do you want to request a *feature* or report a *bug*?**
it's a bug

**What is the current behavior?**
i found an issue with last web pack and common chunk  

my webpackconfig is configured with:
 entry: {
    main: ["babel-polyfill",  './main.js'],
vendor: ["react", "react-dom"],
map: ['./routes/Map/Map.js'],
},

config.plugins.push(new webpack.optimize.CommonsChunkPlugin({
  name: 'main',
  chunks: ["container", "map"],
  minChunks: Infinity
}));

config.plugins.push(new webpack.optimize.CommonsChunkPlugin({
  name: 'vendor',
  chunks: ['main',"map"],
  minChunks: Infinity
}));

So i have got a chunk named "map" who is not the entry chunk .
in the code of this chunk "map i did a mistake to write :    
 
await System.import(/* webpackChunkName: 'main' */ 'mapbox.js');
instead of
await System.import(/* webpackChunkName: 'mapbox' */ 'mapbox.js');

to add load the code "lazily" mapbox.js in the bundle map

yes i know it's not really logical to use System.import to load a code from main
 but web pack should give the result as web pack 3.6  (who let working the application even with this)

**it's seems that with web pack 3.7.1 do an import from a chunk to main not work at all** 

maybe you should to test this

With await System.import(/* webpackChunkName: 'main' */ 'mapbox.js'); in code of map.js
The result of bundle main remain empty and the application do not start at all.
At least it's should to display an error to help the developper. (i scrolled in all my 1000 lines of code to find the problem) 

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

Same behavior than web-pack 3.6 continue to build properly the main chunk
At least it's should to display an error to inform the developper. (i scrolled in all my 1000 lines of code to find the problem) 

**If this is a feature request, what is motivation or use case for changing the behavior?**
To have a more stable webpack 3.7.1 :)

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by sokra** [comment]
could be similar to #5841?

**Comment by simonjoom** [comment]
not really, for me build time seems faster than 3.6.0 ... i used as well the code from 3.8 same behavior
