### ISSUE TITLE
Improve ability to spy on methods exported from a library 

### ISSUE THREAD

**Issue by bdwain** [webpack/webpack#5834]
**Do you want to request a *feature* or report a *bug*?**
request a feature

**What is the current behavior?**
to spy on a function, usually I can say

```js
import * as fooMethods from 'foo.js';
...
spyOn(fooMethods, 'bar'); //jasmine syntax but other libraries are similar
```
However, this requires that the module can be modified at runtime. That's fine if you just say `export function bar(){...}`.

When defining library exports though, the typical pattern is like

```js
//index.js
import fooMethod from 'path';
export {
  foo
};
```
in the generated bundle, this looks like
```js
/* harmony reexport (binding) */ __webpack_require__.d(__webpack_exports__, "foo", function() { return __WEBPACK_IMPORTED_MODULE_0_path__["f"]; });
```
it's basically the same if you use the `export from` syntax also.

this can not be modified at runtime, and so it can't be spied on. 

The 2 ways around this that i can see are to use a default export for the library (which is more annoying to actually use) or to do something weird like this
```js
//index.js
import fooFn from 'path';
export function foo(...args){
  return fooFn(...args);
}
```

This works because it generates different code because foo is constant.
```js
/* harmony export (immutable) */ __webpack_exports__["foo"] = foo;
```
But it's weird and hacky and causes extra function calls, so it's not ideal.

**What is the requested behavior?**
```js
import foo from 'foo';
export {foo};
```

In that example, is it possible to have webpack assume that foo is constant, and so use an immutable export instead of the binding one?

If that's not possible because import results are not constant, what about in this scenario
```js
export {foo} from 'foo';
//or
export * from 'foo';
```

That at least that seems like it would work as an immutable export.

**If this is a feature request, what is motivation or use case for changing the behavior?**
To improve the ability to spy on library methods.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
doesn't matter

**Comment by sokra** [comment]
The spec says there properties are not mutable. This will not work. You can't modify a namespace object.

You can use this as workaround:

``` js
import * as fooMethods_ from 'foo.js';
const fooMethods = {...fooMethods_}
spyOn(fooMethods, 'bar'); //jasmine syntax but other libraries are similar
```

**Comment by bdwain** [comment]
ah got it. oh well. that example does not work because even if i make a shallow copy of the module in tests, my code is still using the original module, which does get the spy. 

i think if it can't be an immutable export then there's probably no good way around it. I'll just wrap the things in functions. It's not really slow and is easier to use for the user of the library at least.

Thanks for responding so quickly!
