### ISSUE TITLE
Version 3.8.0 configuration problems.

### ISSUE THREAD

**Issue by Tadasb** [webpack/webpack#5839]
**Bug**

I am running Laravel app and using webpack. It fails to run after updating to version 3.8.0. Previous version 3.7.1 had no problems. Error: 

`cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`

`Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.`

 `- configuration.stats should be one of these:
   object { context?, hash?, version?, timings?, assets?, env?, colors?, maxModules?, chunks?, chunkModules?, modules?, children?, cached?, cachedAssets?, reasons?, source?, warningsFilter?, excludeAssets?, excludeModules?, exclude?, entrypoints?, errorDetails?, chunkOrigins?, modulesSort?, moduleTrace?, chunksSort?, assetsSort?, publicPath?, providedExports?, usedExports?, optimizationBailout? } | boolean | "none" | "errors-only" | "minimal" | "normal" | "detailed" | "verbose"`

   `Used by the webpack CLI program to pass stats options.`
   `Details:`
   ` * configuration.stats has an unknown property 'errors'. These properties are valid:
      object { context?, hash?, version?, timings?, assets?, env?, colors?, maxModules?, chunks?, chunkModules?, modules?, children?, cached?, cachedAssets?, reasons?, source?, warningsFilter?, excludeAssets?, excludeModules?, exclude?, entrypoints?, errorDetails?, chunkOrigins?, modulesSort?, moduleTrace?, chunksSort?, assetsSort?, publicPath?, providedExports?, usedExports?, optimizationBailout? }`
    `* configuration.stats has an unknown property 'warnings'. These properties are valid:
      object { context?, hash?, version?, timings?, assets?, env?, colors?, maxModules?, chunks?, chunkModules?, modules?, children?, cached?, cachedAssets?, reasons?, source?, warningsFilter?, excludeAssets?, excludeModules?, exclude?, entrypoints?, errorDetails?, chunkOrigins?, modulesSort?, moduleTrace?, chunksSort?, assetsSort?, publicPath?, providedExports?, usedExports?, optimizationBailout? }`
   ` * configuration.stats should be a boolean.`
   ` * configuration.stats should be one of these:
      "none" | "errors-only" | "minimal" | "normal" | "detailed" | "verbose"`

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
npm 5.5.1
node 8.5.0
fails on macOS and Ubuntu 16.04

**Comment by brauni182** [comment]
Same here...
Ubuntu 16.04 by using Laravel Mix

**Comment by CDingerdis** [comment]
Same here.
node: 8.2.1
npm: 5.4.2

**Comment by zenkermatheus** [comment]
Same here. @nniicc solution of downgrade worked here.

**Comment by maximilianfixl** [comment]
@nniicc 
Not working with `webpack3.8.0`, `laravel-mix`, `npm 5.4.2`

Still getting error:
` * configuration.stats should be a boolean.
    * configuration.stats should be one of these:
      "none" | "errors-only" | "minimal" | "normal" | "detailed" | "verbose"`

**Comment by CDingerdis** [comment]
it looks like the error is in: `/schemas/webpackOptionsSchema.json` on line `978`.
if you remove the prop `"additionalProperties": false`, it works again.

@sokra

**Comment by dawin09** [comment]
Same here, back to 3.7 meanwhile

**Comment by hzoo** [comment]
Should pin to 3.7.1 until 3.8.1, @sokra has a PR already at https://github.com/webpack/webpack/pull/5840
