### ISSUE TITLE
The org >GUIDES>Hot Module Replacement,when I try the chapter HMR with Stylesheets....

### ISSUE THREAD

**Issue by Jet12138** [webpack/webpack#5845]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
It is OK now. Because I follow all the chapters before this chapter,I find it necessary to add the behave "1.end first 2.do as your chapter content 'npm install --save-dev style-loader css-loader' 3.you should' npm start' "
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
I expected that I don‘t need to restart the serve and the program will automatically find the new loader and the module.rule that I just added in webpack.config.js .That is all .
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
{
  "name": "webpack-demo",
  "version": "1.0.0",
  "description": "webpack 2.0 demo",
  "main": "webpack.config.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "watch": "webpack --progress --watch",
    "start": "webpack-dev-server --open",
    "server": "node server.js",
    "build": "webpack"
  },
  "keywords": [
    "webpack 2.0 ",
    "Jet12138",
    "学习版"
  ],
  "author": "Jet12138",
  "license": "ISC",
  "devDependencies": {
    "clean-webpack-plugin": "^0.1.17",
    "css-loader": "^0.28.7",
    "csv-loader": "^2.1.1",
    "express": "^4.16.2",
    "file-loader": "^1.1.5",
    "gulp": "^3.9.1",
    "html-webpack-plugin": "^2.30.1",
    "image-webpack-loader": "^3.4.2",
    "style-loader": "^0.18.2",
    "url-loader": "^0.6.2",
    "webpack": "^2.6.1",
    "webpack-dev-middleware": "^1.12.0",
    "webpack-dev-server": "^2.9.2",
    "xml-loader": "^1.2.1"
  },
  "dependencies": {
    "lodash": "^4.17.4"
  }
}
win7  Chrome59.0.3071.115（正式版本）  node@8.4.0

**Comment by sokra** [comment]
We decided to not watch the webpack configuration. It would be too difficult/impossible to get reliable in all cases. So we better go for reliable not-watching.
