### ISSUE TITLE
Path variable [name] not implemented in this context

### ISSUE THREAD

**Issue by imfenghuang** [webpack/webpack#5846]
使用 weex-toolkit v1.0.0-beta.4时，会提示 
`Error Path variable [name] not implemented in this context : C:\Users\user\.weex_tmp/[name].weex.js`

但是换用 1.0.7版 则不会报错

求教该怎么解决？

**Comment by liangklfang** [comment]
这个解决了吗 为啥我用了1.0.7也有这个问题？
