### ISSUE TITLE
Bundle is including development and production versions of react

### ISSUE THREAD

**Issue by guyfedwards** [webpack/webpack#5848]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Bundling react results in both 'react.production.js' and 'react.development.js' being included.

**If the current behavior is a bug, please provide the steps to reproduce.**
See https://github.com/guyfedwards/react-webpack/blob/master/bundle.js#L586 for example minimal repro.

**What is the expected behavior?**
Only have 'react.development.js' bundled.
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Node: 8.6.0
Webpack: 3.8.1

**Comment by sokra** [comment]
react is expecting you to define `process.env.NODE_ENV` to `"production"`.

see https://reactjs.org/docs/optimizing-performance.html#webpack

**Comment by guyfedwards** [comment]
I know that for a production build, but the issue here is that in development it is also bundling 'react.production.min.js' which it shouldn't be

**Comment by guyfedwards** [comment]
Profiling shows that `react/index.js`requires both min and prod versions which is unexpected.
![image](https://user-images.githubusercontent.com/1794071/31727322-34d6e492-b421-11e7-9d77-3b6ea4ff19d1.png)


![image](https://user-images.githubusercontent.com/1794071/31727316-2effbe68-b421-11e7-9c38-8cc2497d9fd7.png)

![image](https://user-images.githubusercontent.com/1794071/31727290-1e5a853e-b421-11e7-83f3-beff22159264.png)
