### ISSUE TITLE
How to request a ressource (JSON) without including it into the generated bundle

### ISSUE THREAD

**Issue by biquetto** [webpack/webpack#585]
I can't figure out how to request an external ressource (JSON file) from my bundle without including it into.
My client has to fill separated JSON files for internalization purposes, and I don't want him depends of the webpack build process. Basically I just want webpack make a basic ajax request in order to fetch the requested i18n file. 

I've already tried to use :

```
require.ensure([], function() {
    data = require('../data/i18n/en-GB.json');
});
```

But this result of an additional generated bundle.
I also tried to use the [i18n webpack-plugin](https://github.com/webpack/webpack/tree/master/examples/i18n) but this not fit my needs as it depends of the build process.

Any help would be awesome
Thanks

**Comment by jslegers** [comment]
> This is not webpacks job. Just make an ajax call. see #150

What if I need to dynamically load a JSON file from a path relative to the path of my AMD / CommonJS / ES6 module?
