### ISSUE TITLE
Uncaught Error: Cannot find module "fs"

### ISSUE THREAD

**Issue by hawx1993** [webpack/webpack#5850]
my webpack version is v3.8.1.

I just `require('fs')` in my js file, but I got the error:
```
Uncaught Error: Cannot find module "fs";
```
and when I add `node{ fs: 'empty' },`

and then I got another error: `fs.readdirSync is not a function`

why? how can I fixed it ?

**Comment by sokra** [comment]
There is no `fs` in the browser.

**Comment by chensivan** [comment]
@sokra what does that mean? 

@hawx1993 did you fix your problem? I tried pretty much the same and got the same errors.

**Comment by samanthagiraudeau** [comment]
@chensivan @hawx1993 did you fix your problem ? I've got the same errors...

**Comment by montogeek** [comment]
@samanthagiraudeau Please open a new issue

**Comment by FionaWong** [comment]
I just meet the problem .
as sokra said "There is no fs in the browser.", he means you just can use it in the node running js,just as express ,koa and so on. like webpack can use the module only when it is called in node commands.
am i right?
