### ISSUE TITLE
Bundle is including development and production versions of react

### ISSUE THREAD

**Issue by guyfedwards** [webpack/webpack#5851]
Apologies for opening another issue but seeing as my previous was closed without resolution, I had no choice. Previous issue https://github.com/webpack/webpack/issues/5848

**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Bundling react **not** in production results in both 'react.production.js' and 'react.development.js' being included.

**If the current behavior is a bug, please provide the steps to reproduce.**
This is running a simple `./node_modules/.bin/webpack` from the root of [this](https://github.com/guyfedwards/react-webpack) project. 
See the output [here](https://github.com/guyfedwards/react-webpack/blob/master/bundle.js#L586) where both production and development builds are included.

Looking at the bundle profile you can see both react.development.js and react.production.js being required despite the `if (NODE_ENV === 'production')` check. 
![image](https://user-images.githubusercontent.com/1794071/31762082-05f08052-b4b2-11e7-9870-e6db5081a24a.png)
![image](https://user-images.githubusercontent.com/1794071/31762085-0880c76e-b4b2-11e7-84e1-c4de6260712a.png)
![image](https://user-images.githubusercontent.com/1794071/31762090-0b5e0ae6-b4b2-11e7-9963-a0fc32bc5540.png)

**What is the expected behavior?**
Only have '**react.development.js**' bundled when running a development build.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Node: 8.6.0
Webpack: 3.8.1

**Comment by sokra** [comment]
This is working as expected. `NODE_ENV` is not set to a compile-time constant value (no DefinePlugin). webpack doesn't know which value `process.env.NODE_ENV` will have at runtime, and can't assume any branch of the if-else is untaken. It have to include both versions. At runtime it will only load the dev version.

cc @gaearon

**Comment by guyfedwards** [comment]
ok makes sense but that's causing us issues with having create-react-class unminified and react minified as per https://github.com/facebook/react/issues/9999

**Comment by guyfedwards** [comment]
Solved this by explicitly defining `NODE_ENV: JSON.stringify('development')` in webpack.

**Comment by psimoneau22** [comment]
For anyone who comes across this same issue, the problem that I had was that I was using the wrong 'devtool' defined in webpack config.   When building react for production, Avoid inline-*** and eval-*** devtool config values.  For prod, you can use 'source-map' and dev you can use 'eval-source-map'
