### ISSUE TITLE
Not the all css file combined to styles.css

### ISSUE THREAD

**Issue by symbios-zi** [webpack/webpack#5853]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
I am importing more than 10 css files and not the all files will combined to finished styles.css

**If the current behavior is a bug, please provide the steps to reproduce.**
Import more than 10 css files in common js file
```

// common.js
import '../../../../public/static/plugins/bootstrap/assets/stylesheets/bootstrap.scss';
import '../../../../public/static/plugins/jquery-ui/jquery-ui.css';
import '../../../../public/static/plugins/owl-carousel2/assets/owl.carousel.min.css';
import '../../../../public/static/plugins/select2/select2.css';
import '../../../../public/static/plugins/iCheck/all.css';
import '../../../../public/static/plugins/owl-carousel2/assets/owl.theme.default.min.css';
import '../../../../public/static/plugins/bootstrap-input/css/fileinput.min.css';
import '../../../../public/static/plugins/font.awesome/font-awesome.css';
import '../../theme/scss/common.scss';
import '../../theme/scss/responsive.scss';
import '../../../../public/static/plugins/pace/pace-theme-minimal.css';
```

```
            {
                test: /\.css$/i,
                use: ExtractTextPlugin.extract({
                    fallback: 'style-loader',
                    use: 'css-loader'
                })
            },
            {
                test: /\.scss$/i,
                use: ExtractTextPlugin.extract({
                    use: ['css-loader', 'sass-loader']
                })
            },
```

and if I remove one of files, it will make normal file.

**What is the expected behavior?**
Concatenated styles.css 
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
webpack. 3.8.1
node v8.2.1
macos siera

**Comment by sokra** [comment]
@webpack-bot move to webpack-contrib/extract-text-webpack-plugin
