### ISSUE TITLE
Vendor chunk id changes when adding dependencies to main. This breaks caching

### ISSUE THREAD

**Issue by ptrts** [webpack/webpack#5856]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Vendor chunk id changes when adding dependencies to main. This breaks caching. 

**If the current behavior is a bug, please provide the steps to reproduce.**

1. git clone https://github.com/ptrts/HashedModuleIdsPluginBug
2. npm install
3. npm run build
4. rename build directory to build-dep
5. comment out the first line in main.js which is import './main-dep.js'
6. npm run build
7. rename build directory to build-no-dep
8. compare build-no-dep/vendor.###.js with build-dep/vendor.###.js. You'll see the difference in the chunk ids. This breaks caching.

**What is the expected behavior?**

Vendor chunk id shouldn't change if we add dependencies to main. 

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

OS: Linux Mint 17.3 Rosa (Ubuntu 14.04.5 LTS, Trusty Tahr)
node: 6.11.4
webpack: 3.8.1

**Comment by sokra** [comment]
see https://webpack.js.org/concepts/manifest/

**Comment by ptrts** [comment]
@sokra, thank you, I've read through the manifest article. Besides I've studied through every bit of the generated runtime: webpacJsonp, \_\_webpack_require__.e, installedChunks and so on, and I still can't see why it's not a bug and it's just I'm doing wrong.

[chunkhash] based caching as described in https://webpack.js.org/guides/caching/ still seems to me as not working, since chunk IDs may be randomly shuffled when adding dependencies to the main. 

Could you please write some more on this?
