### ISSUE TITLE
Import module split emit ModuleParseError when in brackets

### ISSUE THREAD

**Issue by Delagen** [webpack/webpack#5859]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

```
(import)(/* webpackChunkName: "a" */ "./a.module")
   .then(function (module) { return module.Module; });
```
emit
```
ModuleParseError: Module parse failed: Unexpected token
```

**What is the expected behavior?**
Works as
```
import(/* webpackChunkName: "a" */ "./a.module")
   .then(function (module) { return module.Module; });
```

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by sokra** [comment]
`(import)` is wrong syntax. `import` is not a normal identifier, it's a keyword. You have to use it the correct way.
