### ISSUE TITLE
ProvidePlugin loads the module onto that module.

### ISSUE THREAD

**Issue by dashed** [webpack/webpack#586]
For example, I'm using the following config:

```js
// config
new webpack.ProvidePlugin({
    'regeneratorRuntime': 'regenerator/runtime'
});
```
To load https://github.com/facebook/regenerator/blob/master/runtime.js for variable `regeneratorRuntime`. But the variable is also referenced in the file `runtime.js`. 

It doesn't seem desirable to be loading the same module onto itself, if it happens to be using the same variable that `ProvidePlugin` is detecting.

**Comment by pksjce** [comment]
This issue was moved to webpack/webpack.io#137
