### ISSUE TITLE
require in a new expression is not processed correctly

### ISSUE THREAD

**Issue by mingyuan-xia** [webpack/webpack#5860]
Report a bug

Encountered when webpacking `urllib/lib/detect_proxy_agent.js` line 24, specifically `new require('proxy-agent')(proxy)` .

warning message: 
```
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
```
And in the final bundle, this require is replaced with a failed require trap.
```
proxyAgent = proxyAgents[proxy] = new !(function webpackMissingModule() { var e = new Error("Cannot find module \".\""); e.code = 'MODULE_NOT_FOUND'; throw e; }())('proxy-agent')(proxy);
```

versions: `webpack@3.8.1` and `urllib@2.25.0`

`require('proxy-agent')` should be recognized nicely.

**Comment by sokra** [comment]
It should be `new (require('proxy-agent'))(proxy)`.

`new require('proxy-agent')(proxy)` is equal to `x = new require('proxy-agent'); x(proxy)` and that probably not what you want.
