### ISSUE TITLE
Support transitive noparse

### ISSUE THREAD

**Issue by reda-alaoui** [webpack/webpack#5861]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
`noparse` must be put in the webpack config file.

**What is the expected behavior?**
I would like to be able to indicate that a module must no be parsed inside the module itself.

**If this is a feature request, what is motivation or use case for changing the behavior?**
We have a project A that contains an Emscripttent output.
Therefore, webpack must not parse module A.
A is not bundled with webpack itself.

We have multiple projects depending on project A and bundled with webpack.
Currently, we have to add module A in `noparse` in each project webpack configuration depending on project A.

It would be cleaner to let module A indicates that it is not parseable.

**Comment by alexander-akait** [comment]
You can use `noParse: (content) => { return true || false; }`
