### ISSUE TITLE
UglifyJs warnings

### ISSUE THREAD

**Issue by ghostwords** [webpack/webpack#587]
Building succeeds, but I get these warnings from a dependency of a webpack dependency:

```
Dropping unused function argument name [(webpack)/~/node-libs-browser/~/process/browser.js:55,0]
Dropping unused function argument dir [(webpack)/~/node-libs-browser/~/process/browser.js:61,0]
```

Should these get reported to https://github.com/defunctzombie/node-process instead?

**Comment by Jerry-Lau** [comment]
@redonkulus wow, great job!

**Comment by mrchief** [comment]
@ghostwords @redonkulus How is suppressing _all_ warnings a solution? You want to see warnings from your own code, don't you?

**Comment by js2me** [comment]
anyone knows that uglifyjs warnings it is just warnings, that problems its removing?
Just I have in cody that expression:``` if(__DEV__) ```
After build I think so it will be : ```if(1)```
But if I using UglifyJS plugin that conditions will be stay in my production code?

**Comment by js2me** [comment]
UglifyJS will be removing conditions with always true/false values?
For example:
`if(true) foo = 1`
has been removed to 
`foo = 1`
Is it so???
