### ISSUE TITLE
Sequence of `resolve.alias` keys can cause import failure

### ISSUE THREAD

**Issue by jasonaden** [webpack/webpack#5870]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When using the `alias` key to re-map imports, if the more general alias appears above a more specific alias in the object, imports to the more specific module will fail.

We recently published a new version of RxJS and published a re-mapping file to point deep imports to their ESM build sources rather than CJS. Came across this issue debugging some user issues.

**If the current behavior is a bug, please provide the steps to reproduce.**

Created a reproduction [here](https://github.com/jasonaden/repro/blob/webpack_alias_failure/webpack/webpack.config.js). Clone repo on `webpack_alias_failure` branch, go to `webpack` directory, `yarn install`, `yarn webpack`.

Comments show how to "fix" the issue in `webpack.config.js`.

**What is the expected behavior?**

`alias` is an object. Sequence of keys should not be depended up on for behavior.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by sokra** [comment]
They are matched in order.

These configuration is ambiguous:

``` js
    alias: {
      "./utils": "./genericUtils/index.js",
      "./utils/sum": "./genericUtils/sum.js"
    }
```

You can use this one instead, which is not ambiguous:

``` js
    alias: {
      "./utils$": "./genericUtils/index.js",
      "./utils/sum": "./genericUtils/sum.js"
    }
```

**Comment by RussellSprouts** [comment]
I have a similar issue -- I'm using alias to allow absolute paths, so I have something like:

```js
{
  alias: {
    "src": path.resolve(__dirname, "src")
  }
}
```

But I also have a folder in src that needs to be mapped to somewhere else:

```js
{
  alias: {
    "src/needs-to-be-generated": path.resolve(__dirname, "out/generated"),
    "src": path.resolve(__dirname, "src"),
  }
}
```

It happens to work if I put the "src/grammar" first right now, but is there a better way to handle it? Will that consistently work? I can't use exact matches, since each of the aliases covers many items.

Thanks

**Comment by evilebottnawi** [comment]
```
{
  alias: {
    "src": path.resolve(__dirname, "src"),
    "src/needs-to-be-generated$": path.resolve(__dirname, "out/generated"),
  }
}
```

Here docs how it works https://webpack.js.org/configuration/resolve/. Feel free to feedback.
