### ISSUE TITLE
Dynamic Code Splitting

### ISSUE THREAD

**Issue by tooltonix** [webpack/webpack#5872]
Hi,

I am using webpack **^3.8.1** and the Code Splitting feature, which is working:
_import(/* webpackChunkName: "category" */ `components/category/index`)_

Now I want to dynamically import chunks/components like this, which is not working - I got an error in the browser:
_let path = '/components/category/index';
import(/* webpackChunkName: "category" */ `${path}`);_

Error: **services lazy ^.*$?5417:54  Uncaught (in promise) Error: Cannot find module '/components/category/index'.**

Here is my webpack.config.js
```
const path = require("path");

module.exports = {
	entry: {
		main: "./theme/src/js/main.js"
	},
	output: {
		path: path.resolve(__dirname, "theme/assets/js"),
		publicPath: "./asset/assets/js/",
		filename: "[name].js",
		chunkFilename: "[name].bundle.js"

	},
	resolve: {
		modules: [
			path.resolve(__dirname, "theme/src/js"),
			path.resolve(__dirname, "node_modules")
		]
	},
	module: {
		loaders: [
		{
			test: /\.js$/,
			loader: "babel-loader",
			query: {
				babelrc: false,
				cacheDirectory: true,
				presets: ["latest"],
				plugins: [
					["transform-class-properties"],
					["es6-promise"],
					["syntax-dynamic-import"]
				]
			},
		}
	]}
};
```

I am grateful for every tip.

Cheers Patrick

**Comment by sokra** [comment]
webpack doesn't support full dynamic expressions. Only partially dynamic expressions are supported.

```
const path = "category";
import(/* .. */`compontents/${path}/index`)
```
