### ISSUE TITLE
Option to stop harmony import hoisting

### ISSUE THREAD

**Issue by bingzheyuan** [webpack/webpack#5873]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
For harmony import, imports are moved to beginning of the source code. Please have a look at the code https://github.com/webpack/webpack/blob/0c4d69b7c63f3dfa2b25faaed3ada84e9e9f8fbc/lib/dependencies/HarmonyImportDependency.js#L37-L38, webpack is moving all imports to the starting position.

**If this is a feature request, what is motivation or use case for changing the behavior?**
I am having the same problem as in https://github.com/webpack/webpack/issues/4120, I understand this is the expected behavior, but it is better that webpack can respect the original import order since we are solving circular dependency by changing imports locations. I suggest that we add an boolean parameter in `output` settings to prevent import hoisting.
**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by sokra** [comment]
Sorry, no.

It's not good to write spec-incompatible code, and I won't add an option to support writing wrong code 💣 🔥 . Fix your code.

**Comment by bingzheyuan** [comment]
I wouldn't really expect that the dev team will approve this idea since it is against spec. But you have to realize in lots of circumstances you can't just fix the code.
I hope what i find can help those who suffers from import hoisting. It's fine to close the issue.
