### ISSUE TITLE
webpack --watch does not have an ignore option

### ISSUE THREAD

**Issue by ORESoftware** [webpack/webpack#5874]
**Do you want to request a *feature* or report a *bug*?**

This a bug report

**What is the current behavior?**

There is an infinite loop using `webpack --watch` - this seems to be a problem with webpack for the reasons listed below.

The nature of the loop is like so:

> webpack -w => ts transpile => .js changes => webpack -w

My guess is that if I could do something like this:

```bash
webpack -w  --ignore=*.js
```

then this `ignore` option would solve the problem...

**If the current behavior is a bug, please provide the steps to reproduce.**

Run `webpack -w` using this configuration:

```js
module.exports = {

  entry: ['babel-polyfill', './lib/index.ts'],

  output: {
    path: path.resolve(__dirname + '/dist'),
    filename: 'suman.js'
  },

  module: {

    rules: [
      // all files with a `.ts` extension will be handled by `ts-loader`
      {
        test: /\.ts$/,
        loader: 'ts-loader'
      },
      {
        test: /^\.d.ts$/,
        loader: 'ignore-loader'
      }
    ],

  },

  resolve: {
    alias: {
      fs: require.resolve('suman-browser-polyfills/modules/fs'),
      process: require.resolve('suman-browser-polyfills/modules/process'),
    },
    extensions: ['.ts', '.js']
  }

};
```

**What is the expected behavior?**

Webpack will build the output file, and not keep doing it in a loop.

**If this is a feature request, what is motivation or use case for changing the behavior?**

This is a bug report, not a feature request.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Node.js version 6, on OSX/Darwin

**Comment by ORESoftware** [comment]
I mean this in a good way:

It literally blows my mind that `webpack -w` does not have an ignore option or exclude option.

**Comment by sokra** [comment]
There is a WatchIgnorePlugin somewhere in this repo.

**Comment by ORESoftware** [comment]
@sokra sure, but it would be really nice to have:

`webpack -w --ignore=*.js`

would it not

**Comment by sokra** [comment]
There is probably a weird import/require with an expression that creates a dependency to the complete application including the output directory.

**Comment by sokra** [comment]
You could try:

``` js
watchOptions: {
  ignored: ... // see chokidar options 
}
```

**Comment by ORESoftware** [comment]
@sokra thanks

I had to add:

```js
  plugins: [
    new webpack.WatchIgnorePlugin([
      /\.js$/,
      /\.d\.ts$/    // had to ignore .d.ts files too
    ])
  ],
```

now it seems to work, so I will close, thanks for your help
