### ISSUE TITLE
Feature request: export with multiple library names

### ISSUE THREAD

**Issue by artemjackson** [webpack/webpack#5877]
**Do you want to request a *feature* or report a *bug*?**
*feature*

**What is the current behavior?**
Only single library name can be passed to `output.library`.
It would be useful if multiple library names could be passed.

e.g.
```js
output: {
  // ...
  library: ["jquery", "jQuery", "$"]
  // ...
}
```
**If the current behavior is a bug, please provide the steps to reproduce.**
\-

**What is the expected behavior?**
\-

**If this is a feature request, what is motivation or use case for changing the behavior?**
It would be useful for me and probably for some other folks (see https://github.com/webpack/webpack/issues/2981)

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
webpack: 3.3.0

**Comment by sokra** [comment]
Feel free to either do a PR to add support for this or just use a BannerPlugin to add custom content to the bundle.
