### ISSUE TITLE
Documentation's HtmlWebpackPlugin conf doesn't work

### ISSUE THREAD

**Issue by ptitFicus** [webpack/webpack#5879]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
When using webpack configuration provided in the HtmlWebpackPlugin doc section [https://webpack.js.org/plugins/html-webpack-plugin/](here), `webpack` command fail with this message
```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.output.path: The provided value "dist" is not an absolute path!
```
**If the current behavior is a bug, please provide the steps to reproduce.**
Juste use the configuration provided on this page, (below) and run `webpack` command
```js
var HtmlWebpackPlugin = require('html-webpack-plugin');

var webpackConfig = {
  entry: 'index.js',
  output: {
    path: 'dist',
    filename: 'index_bundle.js'
  },
  plugins: [new HtmlWebpackPlugin()]
};
```

**What is the expected behavior?**
Webpack command should end without error.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
I'm using webpack 3.8.1, on linux.

This problem can br fixed by replacing `path: 'dist'` by `path: __dirname + '/dist'` in webpack configuration. Documentation should probably be updated this way.

**Comment by sokra** [comment]
@webpack-bot move to jantimon/html-webpack-plugin
