### ISSUE TITLE
Dynamic insertion of js file and cannot execute code again

### ISSUE THREAD

**Issue by ketuzhong** [webpack/webpack#5881]
**Do you want to request a *feature* or report a *bug*?**

report a *bug*

**What is the current behavior?**

I need execute dynamic insertion of js file again, when using the CommonsChunkPlugin.
but because in the installedModules, being cached， cannot execute code again

**If the current behavior is a bug, please provide the steps to reproduce.**

[config](https://github.com/ketuzhong/es-webpack-engine)

**What is the expected behavior?**

can execute code again

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

webpack3.7.1

[merge request #5880](https://github.com/webpack/webpack/pull/5880)

**Comment by sokra** [comment]
I don't understand your issue. Could explain it in more detail? Examples?

**Comment by ooflorent** [comment]
Issue was closed because of inactivity.
If you think this is still a valid issue, please file a new issue with additional information.
