### ISSUE TITLE
Configuration stats.all not validated correctly

### ISSUE THREAD

**Issue by k15a** [webpack/webpack#5884]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Webpack doesn't accept the stats.all configuration option but it is mentioned in the Docs: https://webpack.js.org/configuration/stats/

**If the current behavior is a bug, please provide the steps to reproduce.**

Add this to the config:

```js
stats: {
  all: 'none',
}
```

**What is the expected behavior?**

Either the docs should be updated or the API schema.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Node: v8.6.0
NPM: 5.4.2
Yarn: 0.27.5
Webpack: 3.8.1

**Comment by sokra** [comment]
yep, PR #5842 was already merged, but not published to npm yet.
