### ISSUE TITLE
Add not recommend using '-loader' under resolveLoader.moduleExtensions part of the document

### ISSUE THREAD

**Issue by Williammer** [webpack/webpack#5885]
**Do you want to request a *feature* or report a *bug*?**
It's a enhancement on document.

**What is the current behavior?**
Currently https://webpack.js.org/configuration/resolve/#resolveloader-moduleextensions has no preference on adding '-loader'.

**What is the expected behavior?**
Updating the https://webpack.js.org/configuration/resolve/#resolveloader-moduleextensions document to not recommend using '-loader'.

**If this is a feature request, what is motivation or use case for changing the behavior?**
It's not recommended to add '-loader' in https://webpack.js.org/guides/migrating/#automatic-loader-module-name-extension-removed. It'll be better to make the document consistent.

**Comment by sokra** [comment]
@webpack-bot move to webpack/webpack.js.org
