### ISSUE TITLE
Module.hot.accept is not requiring new modules.

### ISSUE THREAD

**Issue by theKashey** [webpack/webpack#5886]
**Do you want to request a *feature* or report a *bug*?**
Report a bug. Inside feature.

**What is the current behavior?**
module.hot.accept should "magicaly" update a dep.

**If the current behavior is a bug, please provide the steps to reproduce.**
Webpack 3.1.0. works
module.hot.accept will be converted into
```js
    module.hot.accept("./src/shared/core/createRoutes.js", function(__WEBPACK_OUTDATED_DEPENDENCIES__) { /* harmony import */ __WEBPACK_IMPORTED_MODULE_5_core_createRoutes__ = __webpack_require__("./src/shared/core/createRoutes.js"); (updateApp)(__WEBPACK_OUTDATED_DEPENDENCIES__); });
```
Webpack 3.8.1 - NOT working
```
module.hot.accept("./src/shared/core/createRoutes.js", updateApp);
```
Ie - no code transformation. After a version bump.

In the same time HotModuleReplacement expects that module will be required in callback.

**What is the expected behavior?**
It should work across versions.

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by theKashey** [comment]
Look like it was false alarm. The root cause of this issue was simple - transpiled module system. HarmonyImportDependencyParserPlugin, you know.

Anyway - may be it will be better to:
1. Notice user about non-harmony file system.
2. In the same time - be more tolerant to the user code, and more fault tolerant. I mean - execute (self) updated modules before calling callbacks, for example.

**Comment by sokra** [comment]
> Notice user about non-harmony file system.

Do you mean non-harmony module system? CommonJs and AMD are valid module systems and and warning/error would annoy many people that are using CJS/AMD.

**Comment by theKashey** [comment]
I mean HarmonyImportDependencyParserPlugin will add code to re-require hot-updated module in case of harmony, and will not do it in another case.

At least HRM module, but itself can track the behaviour of accept callback, and double check that someone somehow used the updated module in the end.
