### ISSUE TITLE
Feature request - streaming a build to browser

### ISSUE THREAD

**Issue by ORESoftware** [webpack/webpack#5894]
**Do you want to request a *feature* or report a *bug*?**
Feature request.

**If this is a feature request, what is motivation or use case for changing the behavior?**

Is there some way to stream a Webpack build to the browser

Something like this:

```js
const webpack = require('webpack');

app.use(function(req,res,next){ 
  webpack().pipe(res);
});
```

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

MacOS/Darwin, Webpack version 2.3.3, Node.js version 8

**Comment by ORESoftware** [comment]
I see there is a Gulp "plugin" for creating a streaming Webpack build - I am not sure how high fidelity is it. (It's [here](https://github.com/shama/webpack-stream)).

The problem is that I think Gulp uses "Vinyl" streams and those aren't really compatible with Node.js core streams.

**Comment by sokra** [comment]
This is not supported. webpack could emit multiple files...

**Comment by ORESoftware** [comment]
@sokra you mean webpack could emit multiple chunks?

If you think about it SystemJS and RequireJS could stream a build to the browser because each file is separate :) Not sure how helpful that would be though
