### ISSUE TITLE
`name` property broken for deepchildren property in CommonChunkPlugin

### ISSUE THREAD

**Issue by wbern** [webpack/webpack#5899]
**Do you want to request a *feature* or report a *bug*?**
Bug. After PR merge #5764.

My original post here: https://github.com/webpack/webpack/issues/4392#issuecomment-338153563

> @ljcrapo  you are right, I had to omit `name`, then it successfully took my dynamic imported controllers and put the vendors in `vendor.bundle.js`.
> 
> What worries me here is that if I have not defined either `name` or `filename`, how can I be so sure that the generated bundle will be `vendor.bundle.js`?
> 
> And why shouldn't `name` be allowed anyway? You do get an error if you define `filename` which is
> 
> ```
> ERROR in chunk app/file [initial]
> vendor.bundle.js
> Conflict: Multiple assets emit to the same filename vendor.bundle.js
> ```
> 
> but there's no error for `name`, just that it plain doesn't work.

https://github.com/webpack/webpack/issues/4392#issuecomment-340327942

**What is the current behavior?**
After this PR, dynamic imports get imported only if `name` property is omitted from CommonChunkPlugin.

**If the current behavior is a bug, please provide the steps to reproduce.**
Try to include name in a CommonChunkPlugin configuration for dynamic imports that you want to be located in your specially named bundle. It will not work at all.

Then omit name, and you will find that the packages end up in `vendor.bundle.js` and who knows where else!

**What is the expected behavior?**
It should be possible to pass `name` for dynamic imports to decide where they should be bundled.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
`3.8.1`

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by wbern** [comment]
I'm sorry, I haven't got around to make a repo with repro.

I will try to get it done someday. In the mean time, I am hoping the community behind the PR's and issues can help.

**Comment by jorrit** [comment]
I hope to have created a good repo with a reproduction at https://github.com/jorrit/webpackcommonschunkbug. Just run `npm start` in after running `npm install`. I expect a vendor chunk to be created with momentjs + bluebird. Instead, bluebird ends up in the app chunk and momentjs is duplicated in the dynamically imported chunks.

**Comment by evilebottnawi** [comment]
You have multiple assets with same name `vendor.bundle.js` double check configuration, also i recommend update `webpack` to v4, thanks
