### ISSUE TITLE
Turn off parsing dynamic requires

### ISSUE THREAD

**Issue by wachunga** [webpack/webpack#59]
[moment.js](http://momentjs.com) has a dynamic include:

```
    function loadLang(key, values) {
        var i, m,
            parse = [];

        if (!values && hasModule) {
            values = require('./lang/' + key);
        }
```

By default, webpack finds every single language pack and includes it:

```
   67      2676  ./~/moment/lang/tr.js
       context from ./~/moment/moment.js
   61      2505  ./~/moment/lang/pl.js
       context from ./~/moment/moment.js
   39      2458  ./~/moment/lang/ca.js
       context from ./~/moment/moment.js
   45      2455  ./~/moment/lang/es.js
       context from ./~/moment/moment.js
   51      2443  ./~/moment/lang/gl.js
       context from ./~/moment/moment.js
...
```

That's really not what I want. Is there a way to turn off resolving dynamic includes like this? Some of webpack's fancier options are not always desirable.

**Comment by fab1an** [comment]
Just a comment for people who stumble upon this. Now you need:

```javascript
new webpack.ContextReplacementPlugin(/moment[\/\\]locale$/, /de/)
```

(`locale` instead of `lang` in the regexp)

**Comment by maciej-gurban** [comment]
If you cannot or don't want to modify your build, you can also fix the issue at bower.json level, by manually defining which locale files to include in the overrides section:

```
...
"overrides": {
  "moment": {
      "main": [
        "moment.js",
        "locale/en.js",
        "locale/de.js"
      ]
    }
}
...
```

**Comment by fab1an** [comment]
This doesn't apply to me, since i don't use bower.
