### ISSUE TITLE
Programatic -p

### ISSUE THREAD

**Issue by felipenmoura** [webpack/webpack#5904]
**Bug AND Feature request**

Support the `-p` option programmatically.  
When using the `compiler` API (as described here: https://webpack.js.org/api/node/#compiler-instance) there is simply no way to execute it using `compiler.run` or `compiler.watch` for a production environment. Or if there is a way, I couldn't find it anywhere in documentation.

**What is the current behavior?**

It builds, but never uglifies it (neither treeshake it).
It will not uglify, not even if I add plugins for it in the settings.

**What is the expected behavior?**

It should accept an option for the compiler to run and execute exactly the same behavior as with the `-p` flag. Minifying and tree shaking it.

I've been using the webpack beta version, with babel(es2015)  loaders on a mac.

**Sample codes**

To make it simpler to test and simulate:

This is my `index.js` file

```
const webpack = require('webpack')
const webpackConfig = require('./webpack-conf')

const compiler = webpack(webpackConfig)

compiler.run(function (err, stats) {
    if (err) {
        return console.error('FATAL BUILD ERROR: ', (err.message || er))
    }
    console.info('BUILT')
}, {
    env: {
        production: true,
        p: true
    }
})
```

And this is my `webpack-conf.js` file:

```
// process.argv.push('-p')

const webpack = require('webpack')
const path = require('path')
const HtmlWebpackPlugin = require('html-webpack-plugin');
module.exports = {
  entry: './src/index.js',
  output: {
    filename: 'bundle.js',
    path: path.resolve(__dirname, 'dist')
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loader: 'babel-loader',
        options: { 
          presets: [ [ 'es2015', { modules: false } ] ]
        }
      }
    ]
  },
  plugins: [
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: '"production"'
      }
    }),
    new HtmlWebpackPlugin({ title: 'Tree-shaking' })
  ]
}
```

Then, I'm trying and executing this:

```
node index.js
```

It does NOT work even if I try:

```NODE_ENV="production" node index.js```

or

```
node index.js -p
```

It will not work either if I use one of, all of, or a combination of the plugins bellow:

```
plugins: [
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: '"production"'
      }
    }),
    new HtmlWebpackPlugin({ title: 'Tree-shaking' }),
    new webpack.LoaderOptionsPlugin({
      minimize: true
    }),
    new webpack.optimize.CommonsChunkPlugin('common'),
    new webpack.optimize.DedupePlugin(),
    new webpack.optimize.UglifyJsPlugin({
        minimize: true,
        test: /\.js($|\?)/i,
        ecma: 8,
        include: path.resolve(__dirname, 'dist')
    }),
    new webpack.optimize.AggressiveMergingPlugin(),
    new CompressionPlugin({
        asset: "[path].gz[query]",
        algorithm: "gzip",
        test: /\.js$|\.css$|\.html$/,
        threshold: 10240,
        minRatio: 0.8
    })
  ]
```

OBS: It is adding the comment `/* unused harmony export unusedFunc */`, so, I guess it is ready for tree shake, but is not running it  (the _unusedFunc_ is still there in the source code).

**Comment by felipenmoura** [comment]
Hi.
Any idea on what I could be doing wrong here?

Thanks.

**Comment by evilebottnawi** [comment]
@felipenmoura Thanks for issue. Solved in `webpack@4`. It is allow set `mode`. `mode` based on `NODE_ENV` value variable. Feel free to feedback :+1:

**Comment by felipenmoura** [comment]
Awesome!
Will give it a try :)
