### ISSUE TITLE
How to include  jQuery-UI with Vs 2017 Angular 4 template

### ISSUE THREAD

**Issue by mrjohnr** [webpack/webpack#5905]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
not able to include jQuery-UI with Vs 2017 Angular 4 template

I've tried adding to webpack.config.vendor.js:

```
const treeShakableModules = [
    '@angular/animations',
    '@angular/common',
    '@angular/compiler',
    '@angular/core',
    '@angular/forms',
    '@angular/http',
    '@angular/platform-browser',
    '@angular/platform-browser-dynamic',
    '@angular/router',
    'font-awesome/css/font-awesome.css',
    'zone.js',
    'virtual-keyboard',
    'jquery-ui'             //Here
```
what is the right place to include js/css files to webpack?
found also this but not helped me too much

[https://www.npmjs.com/package/webpack-jquery-ui](https://www.npmjs.com/package/webpack-jquery-ui)

thanks

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Windows 10 64/webpack 3.8.1/node 8.4.0

**Comment by sokra** [comment]
Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md).

**Comment by mrjohnr** [comment]
Hi,already [done ](https://stackoverflow.com/questions/47038936/how-to-load-jquery-ui-with-asp-core-angular-4-template-from-vs-2017)
thanks
