### ISSUE TITLE
[Bug] Entry points don't match rules that contain an issuer condition

### ISSUE THREAD

**Issue by dooks** [webpack/webpack#5906]
**Do you want to request a *feature* or report a *bug*?**
Report a potential bug.

**What is the current behavior?**
If a module is an entry point, it does not attempt to match with a rule if an issuer is defined.
https://webpack.js.org/configuration/module/#rule-issuer

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Define one or more files as an entry point. `config.entry = [ 'foo.ts', 'bar.ts' ];`
2. Define a module rule that contains an issuer `Condition`. In this case, I'm returning a `Condition` function that always returns true to illustrate a point.
```
config.entry = ['foo.ts', 'bar.ts'];

config.module {
  rules: [
    {
      test: /\.ts$/,
      issuer: () => true,
      loader: 'arbritary-loader'
    }
}
```

**What is the expected behavior?**
`arbitrary-loader` to execute on the files `foo.ts` and `bar.ts`.

**If this is a feature request, what is motivation or use case for changing the behavior?**
If this is not supported behavior, this is a feature request in order for a loader to differentiate between an entry point and a harmony import.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
webpack v3.6.0
node v8.2.0
Mac OS X 10.11.6 El Capitan

**Comment by dooks** [comment]
Since this is a personal issue, I just pushed changes to my own fork. I'm not sure of the repercussions of this change and I am not sure what is the expected behavior. If someone could verify this is actually a bug, I can submit a proper pull request with tests.

**Comment by sokra** [comment]
Could you send a PR?

Could you change all matchers in similar way? `resource`, `resourceQuery`, ... This has been reported for `resourceQuery` too.

**Comment by dooks** [comment]
@sokra I'd love to. I believe my changes will affect anything with a ruleset. I'll need to write unit tests before I submit the PR

**Comment by pgn-vole** [comment]
I'm experiencing the same issue. Can it be looked at ?

**Comment by alexander-akait** [comment]
Fixed in webpack@5
