### ISSUE TITLE
Scope of `self.postMessage` is easily overridden and provides no errors

### ISSUE THREAD

**Issue by DustinArmstrong** [webpack/webpack#5908]
**Do you want to request a *feature* or report a *bug*?**
Bug

[As a note, I was sent here from the `webpack-dev-server` repo](https://github.com/webpack/webpack-dev-server/issues/792#issuecomment-341156254)

**What is the current behavior?**
<img width="1440" alt="screenshot 2017-11-01 13 13 24" src="https://user-images.githubusercontent.com/1608205/32287237-858bba26-bf06-11e7-8224-9e3197ee1481.png">

[`self.postMessage` in webpack-dev-server](https://github.com/webpack/webpack-dev-server/blob/c490b245ad65f315762e03e51710f7f7177b1e7b/client/index.js#L216) does not properly handle the variable `self` being  overridden by components compiled with webpack with a useful error message. I'm not sure if it's that the scope isn't handled properly, or if it should be set as a reserved variable.

**If the current behavior is a bug, please provide the steps to reproduce.**
Project:
https://github.com/DustinArmstrong/webpack-self-error
Specific Code Instance
https://github.com/DustinArmstrong/webpack-self-error/blob/master/app/javascript/packs/application.js#L21

**What is the expected behavior?**
Using `self` should either provide an error that explains the variable is reserved, or shouldn't be accessible.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Webpack@3.5.5, Node@8.8.1, OSX 10.12.6, all browsers tested return same result

**Comment by sokra** [comment]
Why did you override the self variable? Don't do that.

**Comment by ndiezel0** [comment]
@sokra it is very easy to miss `var` by mistake. Just because you say "don't do that", doesn't mean that there shouldn't be at least a warning.

**Comment by iislucas** [comment]
Having a warning would be helpful; although I don't know how easy it is to implement. It's very easy to have global 'self' accidentally overwritten.
