### ISSUE TITLE
Webpack did not change resolve path after extension changed

### ISSUE THREAD

**Issue by jasonxia23** [webpack/webpack#5910]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
I have two files, index.js and constant.js.
In index.js
```
import { something } from './constant'
```
When I change my filename from constant.js to constant.jsx, error throw out like this:

>Module build failed: Error: ENOENT: no such file or directory, open 'path/to/constant.js'

I know restart webpack can fix this problem, but I was wondering if webpack can optimize the problem so I don't need to restart webpack :)
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**
Dont need to restart webpack.
**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by sokra** [comment]
Yep, that's a limitation of `unsafeCache` of `enhanced-resolve`. You could disable it, but this hurts performance.

**Comment by jasonxia23** [comment]
@sokra Nice, will take a try on this.

**Comment by phyllisstein** [comment]
Setting `resolve.unsafeCache` to `false` doesn't seem to fix this issue. I've created a small reproduction case that'll fail the dev server if `test.js` is changed to `test.jsx`: <https://github.com/phyllisstein/webpack-unsafe-cache-repro>. Been bitten by this pretty often myself, would love to figure out a workaround.

**Comment by vankop** [comment]
Should work with `webpack@next`. Feel free to report new issue with reproducible repo.

**Comment by phyllisstein** [comment]
@vankop 11am Monday and you've already made my week. Thanks so much!
