### ISSUE TITLE
CommonsChunkPlugin broken for circularly dependent modules Webpack >= v3.7.0

### ISSUE THREAD

**Issue by niedzielski** [webpack/webpack#5911]
**Do you want to request a *feature* or report a *bug*?** Bug

**What is the expected behavior?**

On Webpack v3.6.0, the following configuration coalesces all common chunks in the entry point:

```js
  new webpack.optimize.CommonsChunkPlugin({
    children: true,

    // https://webpack.js.org/plugins/commons-chunk-plugin/#move-common-modules-into-the-parent-chunk
    minChunks: 3
  }),
```

Like:

```
dist/public/index.e2772e0a6203bb4e7d8c.js              19K <-- Entry is big
dist/public/pages/about.6cf1f3ef68a498cda3ef.js        2.0K <-- Non-entry page chunks are tiny
dist/public/pages/home.027c5030538475eb1253.js         1.9K
dist/public/pages/not-found.2c096c3f04c871042160.js    448B
dist/public/pages/style-guide.d86c4d68eb850d6c36e4.js  2.0K
dist/public/pages/summary.45286bca48ea38c1929b.js      8.1K
dist/public/pages/wiki.670fa01a683d03f3c5df.js         10K
dist/public/runtime.c036110d9b32450e4fb0.js            1.7K
dist/public/vendor.2901ebc67815bbff6383.js             22K
```

**What is the current behavior?**

On Webpack v3.7.0 and v3.8.0, common code across all chunks are not considered when a circular dependency exists:

```
dist/public/index.84cb3fa611f8da94bbb5.js              4.8K <-- Entry is now tiny
dist/public/pages/about.71697989077e06339d2c.js        14K <-- Non-entry page chunks are now big
dist/public/pages/home.0ad17e1e78e8c66e484d.js         14K
dist/public/pages/not-found.428ad62674b108aff056.js    9.9K
dist/public/pages/style-guide.d69441ab8f388893d8a6.js  16K
dist/public/pages/summary.05023b8004ac6e05bf6e.js      22K
dist/public/pages/wiki.1daa761c2c4b9edf772f.js         24K
dist/public/runtime.e14c4d042a867105bc22.js            1.7K
dist/public/vendor.be0eb951a32cd662052a.js             22K
```

The workaround is to manually list each chunk:

```js
  new webpack.optimize.CommonsChunkPlugin({
    // todo: remove manual children chunking when non-entry chunks can be considered automatically.
    name: "index",
    chunks: [
      "index",
      "pages/home",
      "pages/about",
      "pages/wiki",
      "pages/summary",
      "pages/style-guide",
      "pages/not-found"
    ],

    // todo: enable children chunking when non-entry chunks can be considered automatically.
    // children: true,
    // deepChildren: true,

    // https://webpack.js.org/plugins/commons-chunk-plugin/#move-common-modules-into-the-parent-chunk
    minChunks: 3
  }),
```

When `async` is enabled, all chunks are considered like in Webpack v3.6.0 but it generates an unwanted parallel chunk:

```js
  new webpack.optimize.CommonsChunkPlugin({
    children: true,
    deepChildren: true,

    // https://webpack.js.org/plugins/commons-chunk-plugin/#move-common-modules-into-the-parent-chunk
    minChunks: 3,

    async: true
  }),
```

```
dist/public/0.90e930a2e35b968db8f0.js                  14K <-- Common code is coalesced but not in entry chunk
dist/public/index.898d568eb6fca382c91e.js              4.9K <-- Entry is now tiny
dist/public/pages/about.82e8ac428a248a2acbbb.js        2.0K <-- Non-entry page chunks are still tiny
dist/public/pages/home.b720c13912c4681aa83f.js         1.9K
dist/public/pages/not-found.0ba66e4e5d4da6f726cc.js    448B
dist/public/pages/style-guide.a6dc976a1ce90345dc94.js  2.0K
dist/public/pages/summary.7597d02c96e6e8197af1.js      8.1K
dist/public/pages/wiki.b43422b087af102526f0.js         10K
dist/public/runtime.af02afd35a5431909f68.js            1.7K
dist/public/vendor.2901ebc67815bbff6383.js             22K
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Working dummy example: https://github.com/niedzielski/webpack-commons-chunk-example/tree/dd7497bd27effdf4ad0a666fd72aaf2334269894
Same dummy example after upgrading to v3.8.1: https://github.com/niedzielski/webpack-commons-chunk-example/commit/1907fb862a513b25b6e7f79502129fee042ed62c#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

And here's a complete copy of the [Webpack config used in the dummy example repo](https://github.com/niedzielski/webpack-commons-chunk-example/blob/master/webpack.config.js):
```
const path = require("path");
const webpack = require("webpack");
const BundleAnalyzerPlugin = require("webpack-bundle-analyzer")
  .BundleAnalyzerPlugin;

module.exports = {
  entry: {
    index: "./src/index.js"
  },
  output: {
    path: path.resolve("dist", "js"),
    filename: "[name].js",
    chunkFilename: "[name].js",
    publicPath: "./js/"
  },
  devtool: "source-map",
  plugins: [
    new webpack.optimize.CommonsChunkPlugin({
      minChunks: 2,
      children: true
    }),
    new BundleAnalyzerPlugin({
      analyzerMode: "static",
      reportFilename: "bundle-analysis.html"
    })
  ]
};
```

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by joakin** [comment]
@niedzielski provided a great small example.

To clarify a bit what we do on the real project:

* We have one entry point, `src/client/index.js`, [which includes a routes file](https://github.com/wikimedia/marvin/blob/master/src/client/index.tsx#L7) to initialize a router
* The routes file ([`src/common/routers/api.ts`](https://github.com/wikimedia/marvin/blob/master/src/common/routers/api.ts) contains [objects with a function that uses dynamic imports](https://github.com/wikimedia/marvin/blob/master/src/common/routers/api.ts#L9-L14) to load page chunks as routes
  * When processed these route objects have a `toPath` method to construct a string path
* The home page specifically in this case, [imports `src/common/routers/api.ts`](https://github.com/wikimedia/marvin/blob/master/src/common/pages/home.tsx#L3-L11) to get the routes, and [construct links to paths with the `toPath` helpers](https://github.com/wikimedia/marvin/blob/master/src/common/pages/home.tsx#L65-L71)
  * Other parts like the header also [include the routes to construct links](https://github.com/wikimedia/marvin/blob/master/src/common/components/header/header.tsx#L12)

This seemed to work well with 3.6.0, here's the full [`webpack.config.ts`](https://github.com/wikimedia/marvin/blob/master/webpack.config.ts).

Let us know if there is something else we can do to help 👍

**Comment by defnull** [comment]
I think I hit the same bug or a similar bug when using HtmlWebpackPlugin together with CommonsChunkPlugin. The HTML plugin somehow causes `(webpack)/buildin/global.js` and friends to end up in the `main` chunk instead of the `common` chunk, but the `main` chunk depends on `common` and `common` depends on the buildins.
