### ISSUE TITLE
Watch config file in watch mode

### ISSUE THREAD

**Issue by paulpflug** [webpack/webpack#5922]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

Webpack needs to be restarted in order to read in changed configuration files

**What is the expected behavior?**

At least in watch mode, webpack should also watch configuration files for changes.

**If this is a feature request, what is motivation or use case for changing the behavior?**

Debugging configuration files is a constant cycle:
Change file -> Save file -> Restart Webpack
It would be very handy to skip the last step.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

For one of my projects I created a small package to read and watch a configuration file and all of its dependencies: [read-conf](https://github.com/paulpflug/read-conf).

All `require` calls while reading the config will be watched and invalidated, once changed:
```js
// example config
somePlugin = require("somePlugin") // all files read here will also be watched
// great for plugin development
// won't work for loaders, as they are given by name or path
module.exports = {
  ...
  plugins = [
    new somePlugin()
  ]
  ...
}
````

Something similar to this could go in the cli: 
```js
readConf = require("read-config")
webpack = require("webpack")
compiler = null
watcher = null
readConf({
  name: "webpack.conf",
  filename: ,// if a config filename is given in args
  assign: {}, // options object generated from args, overwrites read-in config
  watch: ,// if webpack is in watch mode
  cancel: => {
    compiler.close()
    watcher.close()
  },
  cb: (conf) => { return new Promise((resolve) => {
    compiler = webpack(conf)
    // if  in watch mode
    watcher = compiler.watch({},=>{})
    // else
    compiler.run(=>{resolve()})
  }}
})
```

update:
I created a wrapper as prove of concept
https://github.com/paulpflug/webpack-watch-config

But it relies on node 8.9 for the new `paths` option in `require.resolve`:  
`require.resolve("webpack",{paths:[process.cwd()]})`

**Comment by sokra** [comment]
We decided against watching the config file because it's too error-prone.

While normal development you don't need to change the config file very often, once you figured out a working configuration.

I guess you module works great in simple scenarios where config file depends only on other modules. But config file could read files from filesystem, load part of the configuration from Database, etc.. This partially correct watching behavior could confuse users and probably lead to user restarting webpack "just to be sure". In general webpack tries to avoid partially working solutions.

**Comment by paulpflug** [comment]
what a pitty.
Especially as the main critique of webpack out there is difficult configuration..

> While normal development you don't need to change the config file very often, once you figured out a working configuration.

This doesn't match my experience. I have to touch the configuration to setup the development environment, then again to get a deployable build. 
Also everytime I change the technique I use in any of html, js, css or assets, I have to change the configuration. That's not that often, but definitely more than once.

But most important, configuration changes never work on the first try and that is what sticks.

> But config file could read files from filesystem, load part of the configuration from Database, etc.. 

how many users do this? I never seen this in anything I read about webpack..

> In general webpack tries to avoid partially working solutions.

Quality is important. But isn't a partially working solution the first step to a fully working solution?

**Comment by sokra** [comment]
> I never seen this in anything I read about webpack..

I've seen it. Somebody hashed the graphql schema and passed this value to the babel-loader.

It's also not uncommon to use some configuration library, which read (configuration) files.

babel-loader reads .babelrc file.

**Comment by clecap** [comment]
This feature request is just a **wonderful** idea. 

And, yes, there might be umpteenth very valid reasons of purism not to do that, as seen above. All of these counter-arguments raised here can easily be killed by correct naming and by a single line in the documentation. And: For all those reasons where watching might be a problem (dynamic, including, database-loaded-configs, etc.) people would usually be sophisticated enough to know about these difficulties. 

We could add an option 

```javascript
  {watchOptions: { includeConfigFile: true } }
````
and document that
  
```
  includeConfigFile restarts the build after a change in the configuration file only. 
  Dependencies due to file inclusions, dynamic loads etc. are NOT followed.
```

Also a simple include option where files to be **included** can be mentioned would b e great (we already have an *ignored* option !)

Sadly enough, I do not know sufficient webpack internals to implement that myself.

**Comment by paulpflug** [comment]
Hey @clecap,

back in the days I created [webpack-watch-config](https://github.com/paulpflug/webpack-watch-config)  as a wrapper around webpack, with a sophisticated config watch mechanism (watching everything loaded over nodejs require mechanism for changes - reevaluating the config file and restarts webpack on real changes). 
Give it a try and report back - for me it is quite a time saver in the phase until the configuration is stable.

**Comment by clecap** [comment]
Hey @paulpflug,

I had tried it and it did not react to any edit in the webpack.config.js so I assumed it broken. 

But in response to your nice comment 👍 I now tried it again and realized that it is not watching the configuration file (as in: add a blank or comment) but the configuration options (as in: modify the JSON object), as it should be done. My mistake not to have checked it thoroughly enough.

Great hint, great reply, great wrapper. It now is part of my dev environment.

**Comment by clecap** [comment]
For the sake of completeness: Just stumbled over a case where [webpack-watch-config](https://github.com/paulpflug/webpack-watch-config ) fails due to a dynamic situation. [autoprefixer](https://github.com/postcss/autoprefixer) loads CSS rules from [Can I Use](https://caniuse.com/) and this breaks read-conf. *However* I'd rather use a static configuration for postcss-loader to fix this issue.

**Comment by nickperkinslondon** [comment]
This seems like a no-brainer.  Just make it a separate option like "watchConfigFile" that does exactly ( and only ) what it says it does.  That's what the people want.  Something very simple.  They don't want abstract arguments about "incompleteness".

**Comment by brycekunkel** [comment]
This is the closest thing to the problem I'm trying to solve. I am using HTMLWebpackPlugin and pulling in data through the `templateParameters` option. I can use a `require` statement to get an external file, but if I update said external file, I have to quit watching and restart webpack. I couldn't find anything that would allow me to watch my required config files.

**Comment by alexander-akait** [comment]
@brycekunkel move options to external file and put it in `snapshot.buildDependencies` (webpack@5 only)

**Comment by brycekunkel** [comment]
I'll have to look at that, thanks, @alexander-akait!

**Comment by brycekunkel** [comment]
Okay I'm confused here.. maybe you can help. Here is (a slimed down) copy of my webpack config:

``` js
module.exports = {
  entry: './src/index.js',
  snapshot: {
    buildDependencies: { hash: true, timestamp: true },
  },
  ... 
  plugins: {
    new HTMLWebpackPlugin({
      title: 'Title Here',
      template: './src/assets/template.hbs'
      templateParameters: require('./src/assets/data.js')
    })
  }
}
```

Webpack doesn't recompile when the data.js file is updated. Am I missing something?
