### ISSUE TITLE
Webpack tree shaking not working with React components

### ISSUE THREAD

**Issue by solo474** [webpack/webpack#5923]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
index.js
```
export { Component1 } from './Component1';
export { Component2 } from './Component2';
export { Component3 } from './Component3';
export { Component4 } from './Component4';

```
otherfile.js
```
import { Component1 } from './index';
```
Tree shakeing not working

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Tree shaking should work

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

NodeJS 6.x
Webpack 3.8.1

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by qiyuan-wang** [comment]
@sokra it should be same problem with [this one](https://github.com/webpack/webpack/issues/5944). I include a example repo there.
