### ISSUE TITLE
what happened to Sokra?

### ISSUE THREAD

**Issue by TrejGun** [webpack/webpack#5924]
do you have a vacation, man?

**Comment by TheLarkInn** [comment]
We just got back last week from a conference and have been busy until wednesday! Is there something that made you wonder this?

**Comment by sokra** [comment]
I'm here?

**Comment by TrejGun** [comment]
nothing special) just worrying for you)

**Comment by xtuc** [comment]
and what happened to Sean?

**Comment by sokra** [comment]
@TrejGun Thanks, I wasn't hit by a bus...
