### ISSUE TITLE
When webpack will have a support for circular dependency?

### ISSUE THREAD

**Issue by Judahh** [webpack/webpack#5928]
**Do you want to request a *feature* or report a *bug*?**
*feature*.

**What is the current behavior?**
Webpack does not have support for circular dependancy.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Webpack having support for circular dependancy just like commonJs in node.

**If this is a feature request, what is motivation or use case for changing the behavior?**
I have a big and strong circular dependent Typescript project and I want to use webpack.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Chrome Version 61.0.3163.100 (Official Build) (64-bit)
Node Version 8.7.0
NPM Version 5.5.1
Webpack Version 3.8.1
Ubuntu Version 16.04 LTS

**Comment by sokra** [comment]
webpack supports circular dependencies according to the spec.

Note when migrating a Typescript project: Typescript transpiles ESM incorrectly which causes different behavior for circular dependencies.

**Comment by Judahh** [comment]
So what can I do?
I have:
//b file
import { B } from './b';

export class A {
private b:B;
}
_________________________________________________________
//a file
import { A } from './a';

export class B extends A {

}

**Comment by sokra** [comment]
```
//a.ts
import { IB } from './ib';

export class A {
  private b:IB;
}

//b.ts
import { A } from './a';
import { IB } from './ib';

export class B extends A implements IB {

}

//ib.ts
interface IB {

}
```
