### ISSUE TITLE
Possibility to abort build on watch when saved file and previous save-build is in progress

### ISSUE THREAD

**Issue by bodurkalukasz** [webpack/webpack#5929]
**Feature**
When watch is running a build (after tracked file was saved) user made a change (and saved again) previous build should be aborted and start again immediately.

**What is the current behavior?**
First build order must be finished and then second one starts.

**What is the expected behavior?**
Build that is running is aborted and new build starts.

**If this is a feature request, what is motivation or use case for changing the behavior?**
When changed file has been saved and then developer spotted a typo (and saved again) we must wait for two builds to finish before we can see changes. It could be frustrating. 

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Webpack version: 3.8.1
System: Windows/Mac
Node version: 6.11.3

**Comment by sokra** [comment]
It's currently to difficult to implement. Try to made incremental build fast and you won't notice it...

**Comment by benjiwheeler** [comment]
I second this bug report/feature request. @sokra can you say more about why this is difficult to implement?

**Comment by ZackMFleischman** [comment]
Sometimes incremental builds aren't able to be fast. This would be a nice feature to have.

**Comment by timtos** [comment]
Any updates on this?

**Comment by daksh-varshneya** [comment]
Facing the same issue, would be really helpful

**Comment by justyna-bodurka** [comment]
Hi @daksh-varshneya i guess guys will try to solve it by: https://github.com/vercel/next.js/issues/1083
This topic has been closed for some reason long time ago :)

**Comment by bodurkalukasz** [comment]
Hi @daksh-varshneya i guess guys will try to solve it by: vercel/next.js#1083
This topic has been closed for some reason long time ago :)
