### ISSUE TITLE
Default `devtoolModuleFilenameTemplate` is not a good default

### ISSUE THREAD

**Issue by jhnns** [webpack/webpack#593]
The current default for `devtoolModuleFilenameTemplate` and `devtool: "eval"` is `webpack:///[resource-path]?[loaders]`. This renders a question mark at the end of the filename in stack traces (at least on Chrome). Clicking on these links doesn't reveal the file in the devtool.

Just use the given configuration, throw an exception and try to click on the filename in the console.

**Comment by bebraw** [comment]
Is this relevant still?

**Comment by jhnns** [comment]
Yes, it's still relevant, but it should be merged with #2395. Let's continue there.
