### ISSUE TITLE
How to migrate from 1.13.1 to latest version , Getting following error 

### ISSUE THREAD

**Issue by vittal288** [webpack/webpack#5930]
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'tslint'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, parallelism?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }

1.13.1 configuration  and help me same configuration for latest version
```
'use strict';

const path = require('path');
const webpack = require('webpack');

module.exports = {
    devtool: 'inline-source-map',
    module: {
        preLoaders: [
            { exclude: /node_modules/, loader: 'tslint', test: /\.ts$/ }
        ],
        loaders: [
            { loader: 'raw', test: /\.(css|html)$/ },
            { exclude: /node_modules/, loader: 'ts', test: /\.ts$/ }
        ]
    },
    resolve: {
        extensions: ['', '.js', '.ts'],
        modulesDirectories: ['node_modules'],
        root: path.resolve('.', 'src')
    },
    tslint: {
        emitErrors: true
    }
};
```

**Comment by sean-vieira** [comment]
You need to move `tslint` to a [`webpack.LoaderOptionsPlugin`](https://webpack.js.org/plugins/loader-options-plugin/):

```js
module.exports = {
  // ... snip ...
  plugins: [
    new webpack.LoaderOptionsPlugin({
      tslint: {
        emitErrors: true
      }
    });
  ]
}
```

**Comment by sokra** [comment]
There is a migration guide: https://webpack.js.org/guides/migrating/

**Comment by vittal288** [comment]
Can any provide me webpack configuration for running unit test cases for Angular 4 spec files using Karma, Jasmine
