### ISSUE TITLE
When there's a broken sourcemap, error doesn't tell you which file it broke on

### ISSUE THREAD

**Issue by natew** [webpack/webpack#5931]
**Do you want to request a *feature* or report a *bug*?**

UX feature/bug

**What is the current behavior?**

I'm running webpack on a big project and getting this suddenty:

```
original.line and original.column are not numbers -- you probably meant to omit the original mapping entirely and only map the generated position. If so, pass null for the original mapping instead of an object with empty or null values.
```

But the error doesn't tell me which file/map is causing this issue. Also hard to debug as I've went and put logs in variety of places along the stack trace, but none seem to clue me into *which* file this is breaking on. I've been binary searching to narrow it down to certain node_modules but after an hour no luck, so opening an issue.

**If the current behavior is a bug, please provide the steps to reproduce.**

Have a bad sourcemap of some sort, and then run webpack.

**What is the expected behavior?**

Outputting the file it broke on would be immensely helpful!

**If this is a feature request, what is motivation or use case for changing the behavior?**

Dev UX

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Webpack 3.4, Mac, Node 8

**Comment by natew** [comment]
More notes:

I can't seem to "avoid" this, even with `devtool: false`. I notice there's some switch in SourceMapGenerator that's undocumented to turn it of which I'll try.

I'm still moving around trying to find good logs. One seems to hint that it's already concatted the whole bundle together at the time it fails.

I've also disabled various plugins. Keep in mind, this was working fine until recently. Some sub-dependency may have published something bad, but not certain yet.

**Comment by natew** [comment]
Extremely strange. Updating to 3.8 didn't do anything. Then I added `bail: true`, and it actually just worked, no error 😳

**Comment by sokra** [comment]
Send a PR for the improved error if you find a place to add it.

**Comment by sylvesteraswin** [comment]
@natew I have the same issue, and I upgraded to webpack `3.8.1` used `bail: true` and I still see the same problem.

Did you upgrade any other package?

**Comment by ahem** [comment]
I have the same issue also. It is definitely related to some broken dependency somewhere, because I could fix it by resetting package-lock.json to last working build. Right now I am going through all the updates of dependencies (and dependencies of dependencies) to figure out exactly what broke this.

**Comment by sylvesteraswin** [comment]
@ahem, unfortunately, we don't have a `package-lock.json`, so I just did this `devtool: none` and it worked. 

But I would like to re-enable `source-maps`.

**Comment by frooeyzanny** [comment]
I have the same issue, I'm it's related to https://github.com/webpack/webpack-sources/releases/tag/v1.0.2

**Comment by OlegLustenko** [comment]
are you using 'extract-text-webpack-plugin' ?

Seems like an error with that plugin

**Comment by natew** [comment]
Turned out turning off Babel minify helped us. It was definitely working
though just the other day so not sure what happened.

**Comment by OlegLustenko** [comment]
yes it related to https://github.com/webpack/webpack-sources/issues/28

fix looking like:
```json
+    "webpack-sources": "1.0.1"
```

**Comment by jrencz** [comment]
@OlegLustenko It happens regardless of whether I use extract plugin or not. 
forcing `webpack-sources@1.0.1` helps

My setup: 
webpack 1.15.0
Babili plugin: 0.1.2
extract text plugin: 1.0.1

**Comment by OrDuan** [comment]
Same issue here, `devtool: none` did the trick, but would be only a temp solution for me.

**Comment by ahem** [comment]
Adding `"webpack-sources": "1.0.1"` to dependencies in package.json fixed this for me.

**Comment by sokra** [comment]
cc @TheLarkInn

**Comment by xjunior** [comment]
Adding "webpack-sources": "1.0.1" to dependencies in package.json fixed this for me.

**Comment by michael-ciniawsky** [comment]
Are all of you using `babili/babel-minify-webpack-plugin` ?

**Comment by toddb** [comment]
We had to downgrade the transitive dependency webpack-sources from 1.0.2 to 1.0.1

package.json
```
  ...
"resolutions": {
    "webpack-sources": "1.0.1"
  },
```
Then 

`yarn upgrade`

**Comment by sokra** [comment]
`webpack-sources@1.0.2` updated `source-map` to `0.6.1`

Could somebody `git bisect` this bug on this version range: https://github.com/mozilla/source-map/compare/0.5.7...0.6.1

**Comment by theWebalyst** [comment]
```
"devDependencies": {
    "webpack-sources": "1.0.1"
```
In package.json, then `npm install`, then webpack worked for me.

**Comment by joysoft33** [comment]
No webpack-sources module for me but for those using babili, the following setting solved  (temporaly) the problem:
```
"devDependencies": {
    "babili-webpack-plugin": "0.1.1"
```

**Comment by vsimonovski** [comment]
I had same error as others in this thread but I've notices something strange, setting version of `webpack-sources` fix problem for me but only when used with npm. 

For example If I install dependencies from package.json with **yarn** I still get the error, If I install them with **npm** install error goes away. Any thoughts on why npm works and yarn doesn't?

I'll leave [link to my webpack-boilerplate github repo](https://github.com/vsimonovski/webpack-starter) where this problem occurs. 
To reproduce problem type following commands:
```bash
yarn install
yarn run build #error happens 💩

rm -rf node_modules/
npm install
npm run build #everything works 👍

**Comment by itsjoekent** [comment]
I'm using `babel-minify-webpack-plugin@^0.2.0`, changing my dev tool to `none` solved the build error for now

**Comment by jrencz** [comment]
[`webpack-sources@1.1.0`](https://github.com/webpack/webpack-sources/releases/tag/v1.1.0) has ben released and it's being installed but this release does not affect the problem

**Comment by timwis** [comment]
I'm also using `babel-minify-plugin-webpack`. Setting `module.exports.devtool = '#cheap-source-map'` instead of `'#source-map'` did the trick for me.

**Comment by jrencz** [comment]
@timwis according to https://webpack.js.org/configuration/devtool/ check-source-map is not recommended for production

**Comment by timwis** [comment]
@jrencz sry, where are you seeing that?

**Comment by jrencz** [comment]
@timwis https://webpack.js.org/configuration/devtool/#devtool there's a table in that section

**Comment by timwis** [comment]
Ah, right in front of me :P Thanks.

**Comment by nealoke** [comment]
Just wanted to chip in and say that in my case it doesn't matter if i use the `BabiliPlugin()` or not, as long as I don't have the `"webpack-sources": "1.0.1"` installed it always fails. 

Also wanted to provide you with my files used:
- [`package.json`](https://gist.github.com/nealoke/b9adc553b63d09e5be3ef8b012d51fde#file-package-json)
- [`webpack.config.js`](https://gist.github.com/nealoke/b9adc553b63d09e5be3ef8b012d51fde#file-webpack-config-js)
- [`webpack.config.production.js`
](https://gist.github.com/nealoke/b9adc553b63d09e5be3ef8b012d51fde#file-webpack-config-production-js)

**Cases**
- `npm run server` -> no error
- `npm run server:test` -> error (if `webpack-sources@1.0.1` is not explicitly installed)
- `npm run build:prod` -> no error

**Comment by Reinmar** [comment]
@nealoke, I think that this ticket is more about the DX, not the error itself.

Regarding the error, see:

* https://github.com/webpack/webpack/issues/6131 (with steps to reproduce the issue)
* https://github.com/mozilla/source-map/issues/304 (issue on source-map's side, with steps too)

**Comment by jpcbdev** [comment]
Just add this line inside your webpack config file module.exports = {
  productionSourceMap: false
}

**Comment by peteromano** [comment]
@jpcbdev smh lol

**Comment by jpcbdev** [comment]
@peteromano https://cavestrongdotnet1.files.wordpress.com/2015/09/american-stereotypes-im-not-fat-just-american.jpeg?w=614

**Comment by evilebottnawi** [comment]
`babel-minify-plugin-webpack` was deprecated, please migrate on `terser-webpack-plugin`, if you still have same problems feel free to open a new issue with reproducible test repo, thanks for using webpack and sorry for delay
