### ISSUE TITLE
DllReferencePlugin fails when using webpack-dev-server

### ISSUE THREAD

**Issue by HQidea** [webpack/webpack#5934]
**Do you want to request a *feature* or report a *bug*?**

report a *bug*

**What is the current behavior?**

When using DllReferencePlugin with webpack-dev-server or webpack-dev-middleware, it will occurs an error: 
```
Error: ENOENT: no such file or directory, open '/path/to/js/manifest.json'
    at Error (native)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

```
const webpack = require('webpack');
const WebpackDevServer = require('webpack-dev-server');
const config = require('./webpack.config');
const compiler = webpack(config);
const server = new WebpackDevServer(compiler, {});

server.listen(8080, '127.0.0.1', () => {
  console.log('Starting server on http://localhost:' + 8080);
});
```

and the `webpack.config` is just from this project's example directory, https://github.com/webpack/webpack/blob/master/examples/explicit-vendor-chunk/webpack.config.js

**What is the expected behavior?**

run correctly like the code below:
```
const webpack = require('webpack');
const config = require('./webpack.config');

webpack(config, (err, stats) => {
  process.stdout.write(stats.toString() + "\n");
});  // this runs ok
```

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

node version: 6.9.0
webpack version: 3.8.1

**Comment by sokra** [comment]
yep, sorry that's not implemented yet.

The problem is that the file is written into the in-memory filesystem, but the other compilation tries to read it from the real filesystem. Maybe we need to overlay the in-memory filesystem on top of the input filesystem.

**Comment by jetpack3331** [comment]
@sokra is any solution/workaround for that? I'm having the same problem but when i'm trying to build the production build.

**Comment by evilebottnawi** [comment]
@jetpack3331 no, you can send a PR

**Comment by evilebottnawi** [comment]
bump

**Comment by evilebottnawi** [comment]
I think it can be solved using `writeFiles`, but let's add tests for this case, keep open
