### ISSUE TITLE
Stand up for the jsnext/esnext standard

### ISSUE THREAD

**Issue by damianobarbati** [webpack/webpack#5935]
As the environment evolves we developers often have the need to transpile dependencies into our own configured environments.
Until now most of webpack+babel configuration simply dodged the ball with a `node_modules` exclusion while transpiling but as we move on this is not going to be the case anymore.

Babel already made huge steps forward on this with the `babel-preset-env` but lots of these efforts in optimizing the application vanish because most of packages specify:
- main: transpiled (fully polyfilled) entrypoint
- module: transpiled (fully polyfilled) es6 main export
- jsnext:main: yet again transpiled (fully polyfilled) es6 main export instead of plain sources

I lately found myself asking the package maintaners to either add an `esnext` field or fix `jsnext:main` in order to have a reference to plain sources.
No success so far because the first thing they do is 1) checking what other popular packages (i.e. react, lodash) are doing and 2) googling what should be done.

The bad news is "no standard still emerged for this" so they just drop the discussion and wait.

Why this issue then?
@sokra as the father of Webpack you have the chance to stand up and make a choice on what should be the standard here and the environment would simply embrace it.
Would you consider this?

**Comment by graingert** [comment]
@damianobarbati the answer is `.mjs`

**Comment by damianobarbati** [comment]
@graingert what do you mean? 
`.mjs` is just the new extension needed to let node understand you're importing an "es6 export powered" file.
Even if the npm packages start using the `.mjs` extension we need an entry in the package.json to link it.
If you use `main` then you need another entry to define the "transpiled" version: `jsprevious:main? xD

**Comment by michael-ciniawsky** [comment]
@damianobarbati The most promising way is `pkg.main` (CJS) && `pkg.module` (ESM) which is already supported by webpack, rollup and friends and has a quite similar approach to `<script src="index.js"></script>` && `<script type="module" src="index.js"></script>`

> the answer is .mjs

Absolutely **No**  😛

**Comment by damianobarbati** [comment]
@michael-ciniawsky can you please elaborate?
The `pkg.main` is currently used by 99% of ecosystem packages to link the transpiled entrypoint.
So is the `pkg.module` but using the `export` syntax from ES6.

As I said, most of packages specify:
- main: transpiled (fully polyfilled) entrypoint
- module: transpiled (fully polyfilled) es6 main export
- jsnext:main: yet again transpiled (fully polyfilled) es6 main export instead of plain sources

How can `main` be the answer? Using main you'd be forced to transpile all the `node_modules` dependencies with babel because you could not distinguish between already-transpiled and non-transpiled sources.

And we also have the problem to distinguish between different environments when importing: `node` and `browser`
(BTW I agree with you: in an ideal world `main` should link the plain main entrypoint, and another entry should link the transpiled one if needed)

**Comment by michael-ciniawsky** [comment]
Full ESM support in NodeJS is scheduled for v10.0.0, so CJS (`require`) will still be the **default** for some time. There are two parse goals `CJS` (Script) && `ESM` (Module), which are covered by `pkg.main` (for CJS) && `pkg.module` (for ESM). If you author a package using ESM, you need to transpile it to CJS and provide these files via `pkg.main` and the untranspiled sources via `pkg.module`.

`pkg.main` is official, `pkg.module` isn't currently (by npm)

In the long-term `pkg.main` should be replaced by `pkg.module` e.g when no Node LTS without support for ESM is still active most packages should lookup `pkg.module` by **default** then 

The `pkg.browser` field is supported by webpack and I think rollup aswell (not 💯 here) but that's entirely env related issue which can be more complex to handle depending on the package. It's only needed if branching  isn't sufficient enough or undesired

```js
const file = 'path/to/file'

if (!window && process) {
  fs.readFile(file, 'utf8')...
} else if (window || document) {
  fetch(file)...
} else {
  throw new Error(...)
}
```

etc etc...

`pkg.module` is the successor of `jsnext:main` to my knowledge and has the same purpose, it's use should be discouraged in favor of `pkg.module`

In my opinion `npm` itself should take a stand on `pkg.module` and make it official

**Comment by graingert** [comment]
'index.mjs' should be compiled and tree shaken using babel-preset-env with
`node: 8, modules: false`. `index.js` should be compiled with `"last 2
versions"`

**Comment by michael-ciniawsky** [comment]
`pkg.module`s intend is to link to ESM Modules, they can be transpiled if 'cutting edge' JS features are used, but shouldn't use CJS as the module format since `pkg.main` is the **official** standard there

`pkg.main` = `module.exports/exports` (CJS)
`pkg.module` = `export default/export` (ESM)

**Comment by graingert** [comment]
I don't want to see experimental features, type annotations or JSX in
exported modules on npm

**Comment by michael-ciniawsky** [comment]
Official means that a `package.json` file needs to have at least a `pkg.main` field specifying an entrypoint atm

**Comment by Kovensky** [comment]
This discussion seems to be about being able to publish modern JS for optional consumption (e.g. when debugging), rather than about whether the file is a module or script.

Even if, for `.mjs`, the community goes with `'env', { targets: { node: 9 }, modules: false }`, this would still put things such as async generators as being forever transpiled, even if it might be useful to be able to use the original function (much easier debugging once browser debuggers catch up).
