### ISSUE TITLE
Angular: Webpack- module build failed error 

### ISSUE THREAD

**Issue by mmanavaz** [webpack/webpack#5941]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
I'm getting a compilation error. Below is the error.

ERROR in ./src/main.ts
Module build failed: [object Object]
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
ERROR in ./src/polyfills.ts
Module build failed: [object Object]
 @ multi ./src/polyfills.ts

**If the current behavior is a bug, please provide the steps to reproduce.**
I followed the steps from the Angular webpack docs to set up my webpack.

**What is the expected behavior?**
Successful compilation and able to see the webpage on localhost:4200.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Node version: v6.9.5
npm version: v5.5.1
OS: Windows 10
webpack version: 3.8.1
@types/webpack-dev-server version: 2.9.1
@ngtools/webpack version: 1.2.4
webpack-dev-server: 2.9.4

I've written webpack.dev.js, a webpack.config.js, and a webpack.common.js files. Please let me know if those need to be included.

I would appreciate any suggestions on how to fix the error.

Thank you.

**Comment by sokra** [comment]
There is literally no information in your issue report.

Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md).
