### ISSUE TITLE
Wepback tree-shaking and vue-components package

### ISSUE THREAD

**Issue by qiyuan-wang** [webpack/webpack#5944]
### Reproduction link
https://github.com/qiyuan-wang/vue-tree-shaking-example

### Steps to reproduce
I have a package, named like 'Cards', including several vue components, its structure is likes:
```
| - components
  | - NoteCard.vue
  | - ItemCard.vue
  | - UserCard.vue
| - index.js
| - package.json

```

I exports all components in the index.js file.

So, I can use those components in my business package:
```
<template>
  <div>
    <note-card />
  </div>
</template>
<script>
  import { NoteCard } from 'cards'

  export default {
   ...
  }
</script>
```
I try to use the feature ‘Tree shaking’.

I thought the output bundle would contain the components I import in my business package. For example, it would contain NoteCard only for the codes above.

But the reality is, all components would be in the bundle, that makes the bundle size huge.

So, my question is, what makes ‘tree-shaking’ not work?

### What is expected?
Codes from ItemCard and UserCard should not be included in the output bundle.

### What is actually happening?
Codes from ItemCard and UserCard are included in the output bundle.

**Comment by sokra** [comment]
> So, my question is, what makes ‘tree-shaking’ not work?

The ESM spec.

It say that every imported module must be evaluated.

You import all modules:

``` js
export { default as NoteCard } from './components/NoteCard.vue'
export { default as ItemCard } from './components/ItemCard.vue'
export { default as UserCard } from './components/UserCard.vue'
```

webpack 4 will come with a new feature to opt-in into non-spec-comform behavior that can eliminate these reexports.

**Comment by qiyuan-wang** [comment]
ok, I see.

**Comment by qiyuan-wang** [comment]
@sokra it is still not work on webpack@4.0.0-alpha.2?

**Comment by zxb5102** [comment]
I had the same problem. I tried configuring the uglifyJSPlugin plug-in. But it didn't work

**Comment by aboeglin** [comment]
Any news on this ?
