### ISSUE TITLE
Hot Module Accept Callback - Outdated Dependency Graph

### ISSUE THREAD

**Issue by RyanThomas73** [webpack/webpack#5947]
**Do you want to request a *feature* or report a *bug*?**
Request a *Feature*.

**What is the current behavior?**
The HMR Runtime supports `module.hot.accept('./path/to/module', acceptCallback)` registrations. The runtime passes the accept callback an array of outdated depedencies (relative to the current module) as the first parameter.

The outdated dependencies contain only the direct dependencies of the current module and do not indicate outdated grandchildren, etc.

**If the current behavior is a bug, please provide the steps to reproduce.**
N/A

**What is the expected behavior?**
The accept callback should be provided more information such as the entire list of outdated child and grandchild dependencies or a graph representing the outdated child/grandchild structure.

**If this is a feature request, what is motivation or use case for changing the behavior?**
A module that wishes to handle HMR updates should be able to determine what modules initiated the update. For example when multiple modules are grouped and reexported from a parent module.
Below is one such example:

`./FooComponents/FooComponent1.js`
```
import React from 'react';
import { View } from 'react-native';

...

export class FooComponent1 extends React.Component {
    ...
}
```

`./FooComponents/FooComponent2.js`
```
...
export class FooComponent2 extends React.Component {
   ...
}
```

`./BarComponents/BarComponent1.js`
```
...
export class BarComponent1 extends React.Component {
    ...
}
```

`./BarComponents/BarComponent2.js`
```
...
export class BarComponent2 extends React.Component {
    ...
}
```

`./FooBarComponents.js`
```
export { FooComponent1 } from './FooComponents/FooComponent1';
export { FooComponent2 } from './FooComponents/FooComponent2';
export { BarComponent1 } from './BarComponents/BarComponent1';
export { BarComponent2 } from './BarComponents/BarComponent2';
```

`./proxied-components.js`
```
import { createProxy } from 'react-proxy';

import { FooComponent1, FooComponent2, BarComponent1, BarComponent2} from './FooBarComponents';


const fooComponent1Proxy = createProxy(FooComponent1);
const fooComponent2Proxy = createProxy(FooComponent2);
const barComponent1Proxy = createProxy(BarComponent1);
const barComponent2Proxy = createProxy(BarComponent2);

... do stuff using proxied component classes ...

if(module.hot) {
    module.hot.accept('./FooBarComponents.js', (outdatedDeps, outdatedDependencyGraph) => {
        const { FooComponent1: ReloadedFooComponent1 } = require('./FooBarComponents');
        console.log(outdatedDeps);   //  [ moduleId for './FooBarComponents' ] not very useful...

        const fooComponent1ModuleId = require.resolve('./FooComponents/FooComponent1.js');
        if(fooComponent1ModuleId in outdatedDependencyGraph) {
            let fooComponent1Instances = fooComponent1Proxy.update(ReloadedFooComponent1);

            ... do potentially expensive stuff specific to a foo component 1 update ...
        }

        ...
    });
}

```

**Comment by sokra** [comment]
This would break the encapsulation of `FooBarComponents`. When importing `FooBarComponents` the user doesn't/shouldn't know about nested components. The same is true in the other direction. The author `FooBarComponents` should be able to reorganize nested modules.

---

Your use case could be handled with a simple `===` comparison between the old and the new version:

``` js
import { createProxy } from 'react-proxy';

import { FooComponent1, FooComponent2, BarComponent1, BarComponent2} from './FooBarComponents';


const fooComponent1Proxy = createProxy(FooComponent1);
let fooComponent1ProxySource = FooComponent1;
const fooComponent2Proxy = createProxy(FooComponent2);
let fooComponent2ProxySource = FooComponent2;
// ...
... do stuff using proxied component classes ...

if(module.hot) {
    module.hot.accept('./FooBarComponents.js', (outdatedDeps, outdatedDependencyGraph) => {
        if(fooComponent1ProxySource !== FooComponent1) { // Did the component change?
            // do expensive update
            fooComponent1Proxy.update(fooComponent1ProxySource = FooComponent1);
        }
        // ...
    });
}
```

**You don't need to call `require` in the accept handler when using ESM**

**Comment by RyanThomas73** [comment]
@sokra Thanks for the sample code that clarifies a few points for me. 

Would you like me to submit a PR with the two unit tests I added for the existing `outdatedDependencies` parameter that is passed to the call back or do you feel those tests are superfluous?
