### ISSUE TITLE
The webpack way to load svg?

### ISSUE THREAD

**Issue by jehoshua02** [webpack/webpack#595]
Every time I use svg images, I want to provide png fallbacks. I was looking into using the `file-loader`, but I need to do a bit more:

+ Move svg and png fallback files into the destination folder.
+ Bundle a module for the client to check for svg support.
+ Bundle a module for the client that returns the correct url for the image based on svg support.

I hoped there would be an `svg-loader` but didn't find one in the list. Maybe it's a good idea?

Obviously we only want to check for svg support one time so the svg support test module would be [memoized](http://en.wikipedia.org/wiki/Memoization).

I'm using React, so my example would look like this:

__my-logo.jsx__

```jsx
var React = require('react');
module.exports = React.createClass({
  render: function () {
    return (
      <img src="{require('my-logo.svg')}" />
    )
  }
});
```

I would imagine the configs would look something like this:

__webpack.config.js__

```js
module.exports = {
  module.loaders = [
    { test: /\.svg$/, loader: 'svg-loader' }
  ]
}
```

Not a requirement in my situation, but a nice to have: the `svg-loader` could take it one step further and generate the png fallback automatically as well. I'm using [`gulp-svg2png`](https://www.npmjs.org/package/gulp-svg2png). The `svg-loader` can learn something here from `gulp-svg2png` to generate png. I'm using the `scale` option to enlarge the png so it is more crisp. Query params could be passed to `svg-loader`:

__webpack.config.js__

```js
module.exports = {
  module.loaders = [
    { test: /\.svg$/, loader: 'svg-loader?{png:{scale:2}}' }
  ]
}
```

What is the "webpack way" to load svgs with png fallbacks? A new loader or some other way?

**Comment by shama** [comment]
Closing as it looks like this issue has been resolved by @jehoshua02's `getCurrentScript`. Please reopen if this issue has not been resolved. Thanks!

**Comment by vickychijwani** [comment]
Found this [svg-url-loader](https://www.npmjs.com/package/svg-url-loader) that does the right thing (i.e., like `url-loader` except it doesn't encode the whole SVG). Tested with `css-loader`, didn't try with `html-loader`.

**Comment by koutsenko** [comment]
Issue is not resolved. The question was how-to convert svg to png like that
`
 { test: /\.svg$/, loader: 'svg-loader?{png:{scale:2}}' }
`

**Comment by PierBover** [comment]
Maybe this will help others trying to load SVGs with Webpack:

https://github.com/webpack-contrib/svg-inline-loader

**Comment by alansutherland** [comment]
@sokra perhaps I'm missing the point of webpack but so far my experience hasn't been good, it's a struggle. It promises all these great features but seems to take away some very basic things that in my opinion should just work out of the box. Is there a reason it's not configured to recognize svg and fonts formats by default? instead of needing all these extra addons and loaders

**Comment by kantuni** [comment]
For base 64 [svg-url-loader](https://github.com/bhovhannes/svg-url-loader) worked perfectly.

**Comment by DawidMmM** [comment]
Is there any way to load svg files frim .html file using webpack?
