### ISSUE TITLE
Build time got too high after upgrade versions

### ISSUE THREAD

**Issue by cmargulhano** [webpack/webpack#5951]
* Operating System: Linux Ubuntu 16.04
* Node Version: v8.6.0
* NPM Version: 5.5.1
* webpack Version: 3.8.1
* webpack-dev-server Version: 2.9.4

- [ ] This is a **bug**
- [ ] This is a **feature** request
- [x] This is a **modification** request

### Expected Behavior

When we downgrade to the versions:

"typescript": "2.5.1"
"webpack-dev-server": "2.6.1"
"webpack": "3.4.1"
The build time back to normal which in our case is approximately 7 minutes.

### Actual Behavior

After upgrading to the versions:

"typescript": "2.6.1"
"webpack-dev-server": "2.9.4",
"webpack": "3.8.1"

The build time got very high and in our project it took about 20 minutes to finish.

### For Features; What is the motivation and/or use-case for the feature?

The build time is too high, please consider to review this problem.

**Comment by pamtbaau** [comment]
Same issue here. Compilation 4 times slower after upgrading from Typescript 2.5.3 to 2.6.1. 

webpack: 3.8.1
awesome-typescript-loader: 3.2.3
OS: Windows 10

**Comment by sokra** [comment]
You should report this to typescript or the typescript loaders when it happens for a typescript upgrade...

**Comment by pamtbaau** [comment]
I allready opened an issue at [awesome-typescript-loader](https://github.com/s-panferov/awesome-typescript-loader/issues/517)

**Comment by denisnikolayev** [comment]
I don't know it is breaking change or what, but awesome-typescript-loader returns undefined if file exists but empty. So new typescript mark the file as missing and can not reuse cache
```
if (oldProgram.getMissingFilePaths().some(missingFilePath => host.fileExists(missingFilePath))) {
                return oldProgram.structureIsReused = StructureIsReused.SafeModules;
            }
```

**Comment by pamtbaau** [comment]
Compilation performance issue is fixed and closed by  [awesome-typescript-loader](https://github.com/s-panferov/awesome-typescript-loader/issues/517).

**Comment by cmargulhano** [comment]
cool :1st_place_medal:
