### ISSUE TITLE
Feature: Report bundle duplication on the CLI when outputting multiple chunks

### ISSUE THREAD

**Issue by samccone** [webpack/webpack#5952]
### What:

When a user specifies multiple chunks as output report a numeric statistic about the amount of bundle duplication across chunks.

For example:

    *chunks*
      * 124124.js ~ 10% duplication
      * 213412.js ~ 50% duplication
      * 545634.js ~ 25% duplication

    run build -- -bundle-stats-viz to explore duplication

### Why:

When multiple chunks are output the volume of duplication is non-obvious and actually quite hard to know without using external tools.  (see this post to understand the full implications http://www.susielu.com/data-viz/bundle-buddy) Since this "duplication" number is critical to ensuring good bundle chunk settings these values should be reported to the user so that they can better tweak their splitting process to minimize duplicaiton.

Inspired by the work here
https://github.com/samccone/bundle-buddy

### How:

The current approach used in bundle buddy uses source maps to build up a mapping of source lines to final bundle outputs, reusing this code should be possible if we keep using source maps as the backing data store.

Thanks.

**Comment by sokra** [comment]
This makes duplication look bad, but it's not bad in general.

**Comment by samccone** [comment]
I agree duplication is not always bad, however right now this statistic is hidden from end users causing optimized split bundles to ship to end users.

As @susielu put so well, "optimizing performance is a balancing act"
![image](https://user-images.githubusercontent.com/883126/32905337-81764e20-caae-11e7-916f-ff7a1619aa6e.png)

However to balance one typically needs to be able to see, at the moment users are "blind".

I have seen non-trivial wins from teams at multiple "BigCorp" companies when this data was presented to them. This "feature" is intended to pull back the curtain of what is happening and to empower end users to tweak their common chunks plugin arguments and splitting approach to deliver what is best for their end users.

Thanks so much for your time!

**Comment by samccone** [comment]
Friendliest of pings cc @TheLarkInn

**Comment by TheLarkInn** [comment]
Hmm, @sokra. How do we want to skin this lizard? Iterating over both chunks and modules and calculating their percentages of duplication is likely to be pretty costly no? Probably: 

* Opt In Plugin
* We'd need to build this into stats, (stats needs a refactor also). 
* I feel like a visual would be heavily beneficial here, and theres no reason why we can't, but I don't think fits the 4.x milestone.

**Comment by sokra** [comment]
I could image a summary in this way:

``` text
Entrypoints:
* first (8 requests, 46kb unneeded modules, 28kb duplicated modules): vendors.js ... first.js 
* second (5 requests, 24kb duplicated modules): vendors.js ... second.js
ChunkGroups:
* async (2 requests, 4kb duplicated modules): vendors~async.js async.js
```

This disables the 3 conflicting metrics to choose the correct trade-off.
