### ISSUE TITLE
Unexpected behaviour when using the CommonChunksPlugin and Async chunks

### ISSUE THREAD

**Issue by ricardobrandao** [webpack/webpack#5956]
**Do you want to request a *feature* or report a *bug*?**

Unexpected behaviour when using the CommonChunksPlugin.

**What is the current behavior?**

Async chunks are **not** removed after being extracted by the CommonChunksPlugin.

**If the current behavior is a bug, please provide the steps to reproduce.**

A Pull Request with this behaviour [was created](https://github.com/ricardobrandao/webpack/pull/1). Just run ```webpack``` inside the **hybrid-router** example.

**What is the expected behavior?**

- the chunks ```0.chunk.js```, ```1.chunk.js``` and ```2.chunk.js``` shouldn't be written to the disk.

- when rendering ```pageA.html```, ```vendorBundle.js``` should be loaded instead of ```0.chunk.js```.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Webpack 3.8.1

**Comment by sokra** [comment]
I don't understand your issue. The CCP doesn't remove chunks, it creates additional chunks.

**Comment by ricardobrandao** [comment]
Hi @sokra,

Chunk ```0``` is an async chunk [emitted by walking through ```pageA``` dependencies](https://github.com/ricardobrandao/webpack/pull/1/files#diff-a9ff6bc9b9aff54faad56d4b07eccb92R3):
```javascript
webpackJsonp([0],[
/* 0 */,
/* 1 */
/***/ (function(module, exports) {

module.exports = function() {
	console.log("This is vendor A.");
};


/***/ }),
/* 2 */
/***/ (function(module, exports) {

module.exports = function() {
	console.log("This is vendor B.");
};


/***/ })
]);
```
Then [CCP adds a new](https://github.com/ricardobrandao/webpack/pull/1/files#diff-e9bee07c39acd8a3cfc9ef4301be59b2R26) ```vendorsBundle``` by extracting chunk ```0``` and adding some new information:
```javascript
webpackJsonp([4,0],[
/* 0 */,
/* 1 */
/***/ (function(module, exports) {

module.exports = function() {
	console.log("This is vendor A.");
};


/***/ }),
/* 2 */
/***/ (function(module, exports) {

module.exports = function() {
	console.log("This is vendor B.");
};


/***/ }),
/* 3 */,
/* 4 */,
/* 5 */,
/* 6 */,
/* 7 */
/***/ (function(module, exports, __webpack_require__) {

__webpack_require__(1);
module.exports = __webpack_require__(2);


/***/ })
],[7]);
```

I was now expecting that webpack would fetch ```vendorA```and ```vendorB``` from the ```vendorsBundle```. However, it still references the ```0```chunk:
<img width="643" alt="screen shot 2017-11-16 at 07 47 28" src="https://user-images.githubusercontent.com/2292745/32879637-b71a7cb0-caa2-11e7-95a4-b8cb55d94fa7.png">


This is the full webpack log:
<img width="631" alt="screen shot 2017-11-16 at 07 38 00" src="https://user-images.githubusercontent.com/2292745/32879671-cbb8ae30-caa2-11e7-93d9-605cb66370b8.png">

**Comment by sokra** [comment]
Your network graph doesn't show loading of `vendorsBundle.js`

**Comment by ricardobrandao** [comment]
That's the problem exactly. I don't want to add all the dependencies beforehand (i.e. add the `vendorBundle.js` script to the HTML) because I might not need it. When asking for ```vendorA```or ```vendorB``` I want webpack to fetch the `vendorsBundle` asynchronously.

**Comment by ricardobrandao** [comment]
CommonsChunkPlugin has now been deprecated by SplitChunksPlugin so this issue does not apply anymore.
