### ISSUE TITLE
validation - absolutePath keyword

### ISSUE THREAD

**Issue by epoberezkin** [webpack/webpack#5957]
**Do you want to request a *feature* or report a *bug*?**

Refactoring - replace a custom keyword absolutePath with the standard formats uri/uri-reference (or with a custom format if there is some difference).

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

Make schema more standard

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by sokra** [comment]
Send a PR
