### ISSUE TITLE
Feature: Working on an idea for having a visual tool for beginners to configure webpack setup

### ISSUE THREAD

**Issue by NaviMarella** [webpack/webpack#5958]
I have been working on an idea for providing a visual tool for web pack setup.

For a beginner, one should go through all the docs to understand and do a minimal setup of web pack. 

I think learning process should be simple. I am working on a visual tool/playground for web pack, where the user can select options to generate a config file. Once he generates the config file, he can copy it and paste this file into his project with few modifications.

In this way, a beginner can easily understand web pack and he can visually see options along with output.

I wanted the community to give their opinions and pain points so that collectively we can give better options to this new tool.

If I raise a PR will it be accepted and if anyone has any opinions or use cases??
 
Overall trying to make Web pack more reachable and understandable to everyone. :relaxed:

**Comment by sokra** [comment]
If you tool is good and popular, feel free to add a link to the documentation.
