### ISSUE TITLE
Babel 7 not being executed on webpack.config.babel.js

### ISSUE THREAD

**Issue by Benjamin-Dobell** [webpack/webpack#5960]
**What is the current behavior?**

Executing `webpack` with a ES6+ config file (`webpack.config.babel.js`) whilst using Babel 7 leads to a `SyntaxError` being reported e.g.

```
$ webpack --env.production
<OMITTED>/webpack.config.babel.js:1
(function (exports, require, module, __filename, __dirname) { import path from 'path'
                                                              ^^^^^^

SyntaxError: Unexpected token import
```

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Install the latest `webpack` and the latest `@babel/core` & `@babel/preset-env` (e.g 7.0.0-beta.32)

2. Create a `webpack.config.babel.js` with ES6+ syntax e.g.

    ```
    echo "import path from 'path'" > webpack.config.babel.js
    ```
    __Note:__ For illustrative purposes only, this obviously doesn't produce a valid webpack config, but it's sufficient to recreate the issue.

3. Create a `.babelrc` with the `env` preset:

    ```
    echo "{\"presets\":[\"@babel/env\"]}" > ./.babelrc
    ```

4. Run webpack e.g.

    ```
    webpack
    ```

**What is the expected behavior?**

Babel to to be executed on `webpack.config.babel.js` before Node executes the file.

Following the steps above you're expecting a webpack specific error regarding an invalid configuration:

```
<OMITTED>/node_modules/webpack/bin/convert-argv.js:507
				throw new Error("'output.filename' is required, either in config file or as --output-filename");
```

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

`webpack`: 3.8.1
`@babel/core`: 7.0.0-beta.32
`@babel/preset-env`: 7.0.0-beta.32

What I'm assuming is happening is that Webpack is looking for the presence of a `babel-core` package, can't find it, so proceeds without using babel. Babel 7 has scoped packages, the new package is `@babel/core`.

**Comment by Benjamin-Dobell** [comment]
Looks like we need an `interpreter` update:
https://github.com/js-cli/js-interpret/pull/47

**Comment by laozhu** [comment]
Babel 6 with `babel-preset-env` didn't support `browserlist` in `package.json`, I upgrade to Babel 7 to support this, then I encountered the some `Unexpected token import` error with my `webpack.config.babel.js` file, hope there's a solution soon :)

**Comment by Benjamin-Dobell** [comment]
@laozhu We're waiting on the following procedure:

* `interpret` PR I mentioned above to be modified/accepted and merged.
* A new `interpret ` release to be published.
* `webpack` to bump its dependency on `interpret`.
* A new `webpack` release.

So this issue is effectively blocked by `interpret` for now.

However, there are several work-arounds that may be appropriate for various use-case:

1. Manually run babel on your config _before_ running webpack (cli):

__package.json__
```
{
  ...
  "scripts": {
    ...
    "build": "babel webpack.config.babel.js > webpack.config.js; webpack --env.production",
    ...
  },
...
```

This is fine for packaging up for production, but may not be ideal during development.

2. Call webpack's compiler from a JS entry-point, here's an example that does just that and also supports server-side hot-reloading:

__<project_root>/start-debug.js__
```
require('@babel/register')

const webpack = require('webpack')

const serverConfig = require('./webpack.config.babel').serverConfig

const environment = process.env.NODE_ENV === 'development' ? {development: true} : {production: true}
const config = serverConfig({...environment})
const bundlePath = `${config.output.path}/${config.output.filename}`;

const compiler = webpack(config)
const compilerOptions = {
    aggregateTimeout: 300,
    poll: true,
}

let server = null

const openSockets = new Map()
let nextSocketId = 0

function loadServer() {
    delete require.cache[require.resolve(bundlePath)]
    server = require(bundlePath).default

    server.on('connection', (socket) => {
        const socketId = nextSocketId++
        openSockets.set(socketId, socket)

        socket.on('close', () => {
            openSockets.delete(socketId)
        })
    })

}

compiler.watch(compilerOptions, err => {
    if (err) {
        console.log(`Server bundling error: ${JSON.stringify(err)}`)
        return
    }

    if (server) {
        for (const socket of openSockets.values()) {
            socket.destroy()
        }

        server.close(() => {
            loadServer()
            console.log('Server restarted')
        })
    } else {
        loadServer()
        console.log("Server started.")
    }
})
```

__package.json__
```
{
  ...
  "scripts": {
    ...
    "debug-hot": "NODE_ENV=development node ./start-hot.js",
    ...
  },
...
```

I'm using `@babel/register` here, so you'll need to add it as a _dev_ dependency if you haven't already.

For anyone curious, `@babel/register` modifies `require` so Babel transpilation will be run on the fly upon required files (namely `webpack.config.babel.js`).

Note that I'm only compiling the server configuration, which in my case is exported as a _function_, you may need to adjust accordingly. I'm only compiling my server, because I'm running Webpack's HMR for the client bundle as part of my server. If you're not, you can modify the code above to load the client config and instantiate a second compiler.

There are packages out there that do something very similar to the provided `start-hot.js`, but they're opinionated (as is my solution) - but you can customise as you see fit.

**Comment by sokra** [comment]
Another workaround when using the CLI.

Create a webpack.config.js file which calls babel register and your webpack.config.babel.js

**Comment by laozhu** [comment]
@Benjamin-Dobell Thank you for your patiently reply, the CLI solution is very great but complicated for me, I choose  the easy `@babel/register` solution too, below is my steps.

1. move ES-Version config entry into config directory.

```bash
mv webpack.config.babel.js config/webpack.babel.js
```

2. Create a new webpack config entry in root directory

```
config
├── webpack.babel.js
├── webpack.base.js
├── webpack.dev.js
├── webpack.dll.js
├── webpack.helper.js
├── webpack.loader.js
├── webpack.path.js
├── webpack.plugin.js
└── webpack.prod.js

webpack.config.js
```
3. Install `@babel/register` package

```bash
yarn add --dev @babel/register
```

4. Require `@babel/register` and `webpack.babel.js` inside `webpack.config.js`

```javascript
require('@babel/register');
module.exports = require('./config/webpack.babel');
```

The solution is easy and useful, let's waiting for webpack upgrade together :)


---
BTW, official [uglify-es](https://webpack.js.org/plugins/uglifyjs-webpack-plugin/) feature is also waiting for webpack upgrade 😂

**Comment by simonbuchan** [comment]
The other option is to continue to use `babel-register` over `@babel/register` and *also* add `babel-core` on the `bridge` dist-tag (e.g. `7.0.0-bridge.0`) - which simply forwards to `@babel/core`.

**Comment by sokra** [comment]
interpret was updated

**Comment by laozhu** [comment]
After upgrading to [Webpack v3.9.0](https://github.com/webpack/webpack/releases/tag/v3.9.0), everything OK again with `webpack.config.babel.js` 🎉

**Comment by haywirez** [comment]
Does this even work with the 4.x versions?

**Comment by ugrupp** [comment]
This exact issue is happening to me on Webpack 4.20.2 still.

**Comment by simonbuchan** [comment]
@ugrupp And you have `@babel/core` installed and a `.babelrc` / `.babelrc.js` file that will apply `@babel/transform-modules-commonjs` (e.g via `@babel/preset-env`)?

**Comment by ugrupp** [comment]
yup!

I just now managed to get it working though, with an extra install of `@babel/register`. So this is my setup now:

**package.json**

```
"dependencies": {
    "@babel/core": "^7.1.2",
    "@babel/preset-env": "^7.1.0",
    "@babel/register": "^7.0.0",
    ...
    "webpack": "^4.20.2",
  },
```

**.babelrc**
```
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "useBuiltIns": "usage",
        "targets": {
          "node": "current"
        }
      }
    ]
  ]
}
```

**webpack.config.babel.js**

```
import { xyz } from 'xyz';
...
```

**Comment by kud** [comment]
I'm sorry I'll post that here but I'm a bit lost with all this babel stuff.

For the moment I've got two config files for babel:

- One for starting webpack in ES6 (`.babelrc`)
- One for defining how webpack should compile my code (`webpack.babel.config.js`)

- `.babelrc`

```
{
  "presets": [
    "@babel/preset-env"
  ]
}
```

- `webpack.babel.config.js`

```
export default {
  presets: ["@babel/preset-env", "@babel/preset-react"],
  plugins: [
    "react-hot-loader/babel",
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-proposal-object-rest-spread",
    "babel-plugin-idx",
    ["import", { libraryName: "antd" }],
  ],
}
```

Since I've updated babel, I've got now this error:

```
> rm -rf ./dist/ && webpack --progress --colors --config=./webpack.babel.js --env.stage=salt

/Users/kud/Projects/_contexte/lois-webapp/webpack.babel.js:1
(function (exports, require, module, __filename, __dirname) { import path from "path"
                                                                     

SyntaxError: Unexpected identifier
```

which means it can't read in ES6, which means my `.babelrc` isn't read anymore.



```
 "devDependencies": {
    "@babel/core": "7.1.2",
    "@babel/plugin-proposal-class-properties": "7.1.0",
    "@babel/plugin-proposal-object-rest-spread": "7.0.0",
    "@babel/preset-env": "7.1.0",
    "@babel/preset-react": "7.0.0",
    "autoprefixer": "9.1.5",
    "babel-eslint": "10.0.1",
    "babel-loader": "8.0.4",
    "babel-plugin-idx": "2.4.0",
    "babel-plugin-import": "1.9.1",
```

Do you have any solution?

Thank you

**Comment by ugrupp** [comment]
Try installing [@babel/register](https://babeljs.io/docs/en/babel-register) as I've suggested in the comment right above yours ;)

**Comment by kud** [comment]
I miss to report it but yeah this is what I did finally and it works. :) Thank you.

I'd like to know why do we need "register" in fact?

**Comment by wmertens** [comment]
@kud the register is for making Babel do the transpiling at runtime, it's what `interpret` uses

**Comment by ChaseChan** [comment]
whatever i did. it just not work for me.
my webpack file name is webpack.config.dll.babel.js.
my npm script command is `webpack --config webpack.config.dll.babel.js`
i was install @babel/core @babel/register babel-loader already.

webpack version:4.25.1.

node version: 9.11.2

babel: 
"@babel/cli": "^7.1.5",
"@babel/core": "^7.1.5",
"@babel/preset-env": "^7.1.5",
"babel-loader": "^8.0.4",

I don't know why it can not work for me...

even i try this way :require('@babel/register');

```
module.exports =
    process.env.VDEPLOY === '1'  ?
    require('./webpack.config.prod.babel')
    :
    require('./webpack.config.dev.babel');

```
it reported the same error:
```
(function (exports, require, module, __filename, __dirname) { (function () {var enterModule = require('react-hot-loader').enterModule;ente
rModule && enterModule(module);})();import path from 'path';

                                    ^^^^^^
SyntaxError: Unexpected token import
```

please help me...

**Comment by simonbuchan** [comment]
@ChaseChan Your `.babelrc` config is not transforming the `import / export` syntax (if you have no config, babel does nothing!). You want at least `{ "plugins": "@babel/transform-modules-commonjs" }`, but as you already have `@babel/preset-env` you probably actually want:

```json
{
  "presets": [
    ["@babel/env", {
      "targets": { "node": "current" }
    }]
  ]
}
```

This can be a problem if you already have a different babel config for your actual app code. In that case, you might need to start looking into weirder babel options like [`overrides`](https://babeljs.io/docs/en/options#overrides) or switching to `babel.config.js` and using [`api.env()`](https://babeljs.io/docs/en/config-files#apienv) (in babel 6, the `.babelrc` `env` key, but that's now deprecated) to detect if you're building .babel.js or your app.

**Comment by simonbuchan** [comment]
Hmm, sorry, what you've got looks like it should work to me, with the `modules: false` line commented out (it should be defaulting to `"commonjs"`).

It's possible you have something else funky going on, I'd try to recreate your current build setup step by step in a new test project to find where it's breaking. (Unless anyone else sees something?)

**Comment by simonbuchan** [comment]
Err: `webpack --config webpack.config.babel.dll.js` won't work, that's not a `*.babel.js` file, and thus won't be run through babel! (`*.ts` is run through typescript, etc...) You probably want something like `webpack.config.dll.babel.js`

**Comment by ChaseChan** [comment]
@simonbuchan 
Hi, morning.
after I change file name like what you suggest for ,but vscode terminal reported the same error...

below was my step.

1. change my filename to webpack.config.dll.babel.js
2. nvm use 9.11.2
3. npm run buil:dll
4. vscode reported the error.

```

chenzhiqiangMacBook-Pro:game_frontend_service chenzhiqiang$ nvm use 9.11.2
Now using node v9.11.2 (npm v5.6.0)
chenzhiqiangMacBook-Pro:game_frontend_service chenzhiqiang$ npm run build:dll

> game_frontend_service@1.0.0 build:dll /Users/chenzhiqiang/Documents/game_frontend_service
> webpack --config webpack.config.dll.babel.js

/Users/chenzhiqiang/Documents/game_frontend_service/webpack.config.dll.babel.js:2
import path from 'path';
^^^^^^

SyntaxError: Unexpected token import
    at new Script (vm.js:51:7)
    at NativeCompileCache._moduleCompile (/Users/chenzhiqiang/Documents/game_frontend_service/node_modules/v8-compile-cache/v8-compile-cache.js:226:18)
at Module._compile (/Users/chenzhiqiang/Documents/game_frontend_service/node_modules/v8-compile-cache/v8-compile-cache.js:172:36)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (/Users/chenzhiqiang/Documents/game_frontend_service/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (/Users/chenzhiqiang/Documents/game_frontend_service/node_modules/webpack-cli/bin/convert-argv.js:133:13)
    at requireConfig (/Users/chenzhiqiang/Documents/game_frontend_service/node_modules/webpack-cli/bin/convert-argv.js:135:6)
    at /Users/chenzhiqiang/Documents/game_frontend_service/node_modules/webpack-cli/bin/convert-argv.js:142:17
    at Array.forEach (<anonymous>)
    at module.exports (/Users/chenzhiqiang/Documents/game_frontend_service/node_modules/webpack-cli/bin/convert-argv.js:140:15)
    at yargs.parse (/Users/chenzhiqiang/Documents/game_frontend_service/node_modules/webpack-cli/bin/cli.js:241:39)
    at Object.parse (/Users/chenzhiqiang/Documents/game_frontend_service/node_modules/yargs/yargs.js:563:18)
    at /Users/chenzhiqiang/Documents/game_frontend_service/node_modules/webpack-cli/bin/cli.js:219:8
    at Object.<anonymous> (/Users/chenzhiqiang/Documents/game_frontend_service/node_modules/webpack-cli/bin/cli.js:538:3)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/Users/chenzhiqiang/Documents/game_frontend_service/node_modules/webpack/bin/webpack.js:155:2)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
```
that is the full message after I change filename and run command again.

**Comment by zzh8829** [comment]
For anybody still wondering in this thread or people who got here from google like me. This is caused by a bug in webpack-cli and will be fixed after this merging this PR https://github.com/webpack/webpack-cli/pull/728

**Comment by stavalfi** [comment]
@zzh8829   still have this problem.

```
    "webpack": "^4.29.6",
    "webpack-cli": "^3.3.0",
    "webpack-dev-server": "^3.2.1"
    "@babel/register": "^7.4.0",
```

**Comment by zzh8829** [comment]
@stavalfi 
Did you follow these steps exactly
1. having @babel/preset-env in babelrc
2. webpack filename is `webpack.config.babel.js`
3. running webpack with `yarn webpack`

If you did then I have no idea, it does work for me.

**Comment by stavalfi** [comment]
@zzh8829  No, I didn't. didn't know I should do `yarn webpack`. I will try. Thanks

**Comment by j78742** [comment]
I have also gotten this problem. In my occasion, adding `@babel/register` works for me.

**Comment by aminnairi** [comment]
Here is what worked for me:

Note: I tried calling my configuration file `babel.config.js`, it didn't work. When I renamed it `.babelrc` the loader picked it up and it worked. So naming it `.babelrc` is really important for `babel-loader`.

Here an example for React.

```console
$ npm install --save-dev @babel/core @babel/preset-env @babel/preset-react @babel/register babel-loader webpack webpack.cli 
$ touch .babelrc
```

```json
{
    "presets": [
        "@babel/preset-env",
        "@babel/preset-react"
    ]
}
```

```javascript
"use strict";

import { resolve } from "path";

export default ({ NODE_ENV }) => ({
    mode: NODE_ENV,
    entry: resolve("src", "index.jsx"),
    output: {
        path: resolve("public"),
        filename: "index.js",
    },
    module: {
        rules: [
            {
                test: /.jsx$/,
                include: [
                    resolve("src")
                ],
                loader: "babel-loader"
            }
        ]
    }
});
```
