### ISSUE TITLE
CodeSplitting / requireEnsure: strange bootstrap generation

### ISSUE THREAD

**Issue by crazyx13th** [webpack/webpack#5966]
**Do you want to request a *feature* or report a *bug*?**
bug (and feature)

**What is the current behavior?**
inside the bootstrap function... there is the output-name added...
![grafik](https://user-images.githubusercontent.com/8912561/32887073-f95ce75a-cac2-11e7-9cfc-1d0dbe9dea40.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
I run it with 
![grafik](https://user-images.githubusercontent.com/8912561/32887129-199502b4-cac3-11e7-83ca-7989c532edc0.png)

**What is the expected behavior?**
without output-name

**If this is a feature request, what is motivation or use case for changing the behavior?**
I don't need this requireEnsure function because there are no async children. I have only my application.js and vendor.js (would be cool to switch this off or automatically remove this Promise Function if there is no children) to save some bytes

**Comment by crazyx13th** [comment]
now I changed 
![grafik](https://user-images.githubusercontent.com/8912561/32891213-09df9c62-cad2-11e7-8e25-d73627fdb401.png)

to
![grafik](https://user-images.githubusercontent.com/8912561/32891243-1feb0ff0-cad2-11e7-8ced-d6fe005f6cc9.png)

result looks better:
![grafik](https://user-images.githubusercontent.com/8912561/32891281-3bbf2946-cad2-11e7-929e-b329d1181e97.png)

**Comment by sokra** [comment]
Working as expected. Also see `output.chunkFilename` if you want to configure the filename.
