### ISSUE TITLE
CommonsChunkPlugin incompatible with IE11, relies on globally available Promise

### ISSUE THREAD

**Issue by coryc5** [webpack/webpack#5968]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
CommonsChunkPlugin does not work in IE11. The bootstrap code relies on a globally available Promise, which is [not available in IE11](https://caniuse.com/#feat=promises). This causes an error which prevents the code from loading.

**If the current behavior is a bug, please provide the steps to reproduce.**
Use CommonsChunkPlugin to split out any code. In that file, the bootstrap will produce code like this:
```
/******/ 	// This file contains only the entry chunk.
/******/ 	// The chunk loading function for additional chunks
/******/ 	__webpack_require__.e = function requireEnsure(chunkId) {
/******/ 		var installedChunkData = installedChunks[chunkId];
/******/ 		if(installedChunkData === 0) {
/******/ 			return new Promise(function(resolve) { resolve(); });
/******/ 		}
/******/
/******/ 		// a Promise means "currently loading".
/******/ 		if(installedChunkData) {
/******/ 			return installedChunkData[2];
/******/ 		}
/******/
/******/ 		// setup Promise in chunk cache
/******/ 		var promise = new Promise(function(resolve, reject) {
/******/ 			installedChunkData = installedChunks[chunkId] = [resolve, reject];
/******/ 		});
/******/ 		installedChunkData[2] = promise;
```

To use these promises, you have to separately load a Promise polyfill on the page before the webpack chunks and add it to the Window object if it does not already exist.

**What is the expected behavior?**
CommonsChunkPlugin works on IE11.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
IE11, Webpack 3.8.1

**Comment by coryc5** [comment]
closing this, was a mistake on my end

**Comment by bluepnume** [comment]
@coryc5 What was the mistake on your end? I'm having the same problem.

**Comment by coryc5** [comment]
@bluepnume The real problem had nothing to do with the promise, but we were missing another ES6 polyfill

**Comment by peterholmberg** [comment]
Which polyfill were you missing?

**Comment by coryc5** [comment]
@peterholmberg I believe we were actually missing `Symbol`
