### ISSUE TITLE
[Bug/Feature] Module file timestamps are only recorded on change events.

### ISSUE THREAD

**Issue by gdborton** [webpack/webpack#5970]
**Do you want to request a *feature* or report a *bug*?**
Both-ish. I think it's a bug, but could be a feature.

**What is the current behavior?**
Webpack is only recording file timestamps for modules after changing a file. This is bad because it causes full rebuilds when dynamically adding to a compiler.

**If the current behavior is a bug, please provide the steps to reproduce.**
I created a [demo repository](https://github.com/gdborton/webpack-build-as-needed).

```
git clone git@github.com:gdborton/webpack-build-as-needed.git
cd webpack-build-as-needed
npm install
node server
```

In your console you should see that `file1.bundle.js` was compiled.
```
building: multi /Users/gary_borton/code/webpack-filetimestamp/src/file1.bundle.js
Listening on port: 3000
building: /Users/gary_borton/code/webpack-filetimestamp/src/file1.bundle.js

webpack: Compiled successfully.
```

If you request `http://localhost:3000/dist/file2.bundle.js`, we'll add it to the compiler, and invalidate. You'll see a message about that, and then you'll see that `file1.bundle.js` was compiled again, despite having no changes.

```
Found a request for an unbuilt bundle "file2.bundle", adding to compiler: "myFancyCompiler"
webpack: Compiling...
building: /Users/gary_borton/code/webpack-filetimestamp/src/file1.bundle.js
building: multi /Users/gary_borton/code/webpack-filetimestamp/src/file2.bundle.js
webpack: wait until bundle finished: /dist/file2.bundle.js
building: /Users/gary_borton/code/webpack-filetimestamp/src/file2.bundle.js
```

**What is the expected behavior?**
Since `file1.bundle.js` has already been compiled successfully and hasn't changed, it shouldn't need to be recompiled.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Performance! I think Airbnb (and others) could see huge dev performance benefits by only compiling/recompiling assets as needed.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
This isn't really relevant.

cc: @sokra @TheLarkInn @ljharb @iancmyers

**Comment by sokra** [comment]
To fix it in webpack, we would need to get the timestamps when calling invalidate, but this requires a change of the WatchFileSystem interface. So this would be a breaking change. We can do that for webpack 4.

**Comment by ljharb** [comment]
Why would it have to be a breaking change; could it not be additive?

**Comment by TheLarkInn** [comment]
This would likely be an improvement for most people, plus vs. a new config
option+opt in, this makes sense to me.

**Comment by arunoda** [comment]
@sokra the workeraround looks nice.
We've also hit by this issue at Next.js.

As a workaround we `touch` a file when starting the app. Then it invalidates first.
And it introduce many other issues.

Looking forward for a proper fix. 
But again the workaround looks cleaner than what we have now.

**Comment by sokra** [comment]
> Why would it have to be a breaking change; could it not be additive?

The WatchFileSystem has no interface method to `getTimes`. We can add this method to the NodeWatchFileSystem, but if somebody provided a custom watch filesystem this will be broken. So it's a breaking change, but I guess only 1-3 people provided a custom watch filesystem and need to change their code.

Anyway webpack 4 is in the pipeline. We can add it there.

**Comment by gdborton** [comment]
I'm totally fine with waiting until webpack 4 for this. We've implemented
the workaround in our server, waiting for more data to see the impact, but
I expect to see some significant dev performance boosts.

**Comment by lencioni** [comment]
@sokra Just a quick update here. We've been working on getting on webpack 4 and I tried removing our workaround for this and the problem seems to still be there. For now we'll just keep our workaround, but it would be nice if this just worked without it.

**Comment by jharris4** [comment]
I just hit on this issue as well, because I was trying to figure out why the `compilation.fileTimestamps` is always empty on first compile.

I would say that this bug has definitely not been fixed. Too bad, as it makes it really hard to check for changed source files etc. (Really biting me with service workers where they install/activate for any change which this bug is causing)
