### ISSUE TITLE
When devtool is 'eval-source-map' In Safari, it will throw ERROR [Can't find variable] of const 

### ISSUE THREAD

**Issue by AmyFoxFN** [webpack/webpack#5971]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When devtool is 'eval-source-map' In Safari, it will throw ERROR [Can't find variable] of const
**If the current behavior is a bug, please provide the steps to reproduce.**
1. devtool is 'eval-source-map' In Safari
2. define a const, like `const test = 1`
3. use this const, like `console.log(test)`-> throw ERROR Can't find variable: test

**What is the expected behavior?**
 
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Safari 10.1.1
Webpack 3.8.1
MacOS 10.12.5

**Comment by sokra** [comment]
That's a browser bug.

**Comment by sokra** [comment]
The same bug was in chrome but was fixed a while ago. You can report it to safari too.
