### ISSUE TITLE
output.libraryTarget: expose library as an CMD module

### ISSUE THREAD

**Issue by JunreyCen** [webpack/webpack#5973]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

1.CMD([Common Module Definition](https://github.com/cmdjs/specification/blob/master/draft/module.md))
2.how to make the library support cmd, such as [transform jquery into cmd module](https://github.com/seajs/seajs/issues/971)

My project use seajs to manage js modules, so it's neccessary for webpack to support output cmd library, instead of modifying output manually!

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by sokra** [comment]
This module format is not common enough do be supported. In addition to that we can support this and AMD, because both use the `define` method. All these old module formats are superseeded by Ecmascript Modules anyway.

So we won't add this.

**Comment by JunreyCen** [comment]
There are something different between cmd and amd, especially the `require `object to load dependency, so it can't support cmd for this moment. Btw,  we certainly prefer to ECMAscript Modules, but it's difficult to refactor an old project.

Thanks for your reply.
