### ISSUE TITLE
Need a mean to rename a resource between loaders

### ISSUE THREAD

**Issue by FranckFreiburger** [webpack/webpack#5978]
*feature*

**What is the current behavior?**

Unable to rename a resource between loaders

**If this is a feature request, what is motivation or use case for changing the behavior?**

`require('convert-to-jpeg!image.png')`

`convert-to-jpeg` loader simply converts png content into jpeg content,
as result, image asset is still `image.png` but its content is jpeg, this leads to an incorrect mimetype.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

webpack 3.6.0

**Comment by sokra** [comment]
You can override the extension in the `file-loader` -> `name` option.

**Comment by FranckFreiburger** [comment]
Thanks, but it seems not possible to only change the extension for files that pass through my `convert-to-jpeg` loader.
- If I use the following config: `rules: [ {  test:/\.png$/, ... file-loader ...`, then all my `png` files will be renamed into `jpeg`, regardless they pass through `convert-to-jpeg`.
- If I use `require('file-loader?{...}!convert-to-jpeg!image.png')`, the file is emitted here (by file-loader) and cannot be processed by a further `url-loader` for example.

**Comment by evilebottnawi** [comment]
@FranckFreiburger 
Use:
1. Use `require('file-loader?{...}!convert-to-jpeg?name=[name]jpeg!image.png'`
2. Use `image.convert.png` and add loader `test: /\.convert\.png/`
3. **Best:** Implement in you loader `test/include/exclude` options and filters what files should be converted what not (example in plugin https://github.com/webpack-contrib/uglifyjs-webpack-plugin/blob/master/src/index.js#L115, but you can you this for loader too)

Thanks for issue.
