### ISSUE TITLE
[Feature] allow resolution of async loaded external dependencies in runtime

### ISSUE THREAD

**Issue by mauron85** [webpack/webpack#5984]
I understand this request is out of mainstream usage of webpack, but I would grateful, if there is small chance that it would be evaluated.

**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Currently all external dependencies has to be defined in global scope (window), before bundle is loaded.

Example:
Your app that depends on external BackgroundGeolocation module.

```
import BackgroundGeolocation from 'cordova-plugin-mauron85-background-geolocation';
```

In your webpack.config.js you mark BackgroundGeolocation as external:

```
...
  output: {
    filename: 'app_bundle.js'
  },
  externals: {
    'cordova-plugin-mauron85-background-geolocation': 'BackgroundGeolocation'
  },
...
```

Resulting app_bundle.js bundle (relevant part) will look like this:

```
/***/ }),
/* 59 */
/***/ (function(module, exports) {

module.exports = BackgroundGeolocation;

/***/ }),
```

module.exports is referencing global object BackgroundGeolocation, meaning in your index.html you have to make sure external dependency is loaded before your app bundle. In other words `app_bundle.js` loading will fail, if BackgroundGeolocation is undefined. 

**If this is a feature request, what is motivation or use case for changing the behavior?**

In some cases external dependencies might be loaded **asynchronously**. For example [Cordova](https://cordova.apache.org/), which is using it's own module loader similar to AMD requirejs.

Describe problem:
Every Cordova app index.html looks like this:
```
<script src="cordova.js"></script>
<script src="app_bundle.js"></script>
```

`cordova.js` is responsible for async loading of cordova plugins (our external dependency).

Process of loading cordova app:
1. cordova.js is loaded
In parallel:
2a. cordova.js will load external dependency (BackgroundGeolocation) asynchronously
2b. main app_bundle.js is loaded

Step 2b. is problematic. As app_bundle depends on external dependency BackgroundGeolocation, which will not be loaded sooner then in step 2a. As result app_bundle.js loading fail, because BackgroundGeolocation is `undefined`.

There some workarounds:
1. load app_bundle after cordova.js is done loading plugins (DISADVANTAGE: delayed app start)
```
    <div id="root"></div>
    <script src="cordova.js"></script>
    <script>
        function run() {
            var script = document.createElement('script');
            script.src = 'app_bundle.js'
            document['body'].appendChild(script);
        }
        document.addEventListener('deviceready', run, false);        
    </script>
```

**Proposal**

Alternative 1.:
Add some webpack configuration flag, that when turned on will:

1. wrap external dependency with function. 
2. if some module is requiring external dependency inject result of wrapped function call, instead of object/function itself.

webpack.config.js
```
...
  output: {
    filename: 'app_bundle.js'
  },
  externals: {
    'cordova-plugin-mauron85-background-geolocation': ['BackgroundGeolocation', { async: true }]
  },
...
```

So webpack will generate code like this (compare with very top)

```
/***/ }),
/* 59 */
/***/ (function(module, exports) {

module.exports = function inject() {
  return BackgroundGeolocation;
}
/***/ }),
```

This allows us to initialise app, without worrying that BackgroundGeolocation might be undefined. It will defined after 'deviceready' event.
```
    <script src="cordova.js"></script>
    <script src="app.js"></script>
    <script>
        function run() {
            App.default.run();
        }
        document.addEventListener('deviceready', run, false);        
    </script>
```

Alternative 2:

Wrap global library var with function (currently IIFE)

```
{
    output: {
        // export itself to a global var
        libraryTarget: "var",
        // name of the global var: "Foo"
        library: "Foo",
        libraryWrapStyle: 'function' // proposal
    },
    externals: {
        // require("jquery") is external and available
        //  on the global var jQuery
        "jquery": "jQuery"
    }
}
```

So it can be initialised after dependencies are loaded.

```
<script src="app_bundle.js"></script>
<script>
var BackgroundGeolocation;
// mimic async dependency loading
setTimeout(function(){
   BackgroundGeolocation = {..};
   App(); //run app
}, 3000);
</script>
```

Other similar usecases I've found on stackoverflow:
* https://stackoverflow.com/questions/30575060/require-js-files-dynamically-on-runtime-using-webpack
* https://stackoverflow.com/questions/34777595/any-way-to-use-webpack-to-load-a-resource-at-runtime

**Comment by sokra** [comment]
You can use `import()` and `require()` to import the external when needed.

Instead of `import BackgroundGeolocation from 'cordova-plugin-mauron85-background-geolocation';`:

``` js
function run() {
  const BackgroundGeolocation = require('cordova-plugin-mauron85-background-geolocation');
  // do something with BackgroundGeolocation
  App.default.run();
}
document.addEventListener('deviceready', run, false);
```

or


``` js
function run() {
  import('cordova-plugin-mauron85-background-geolocation').then(BackgroundGeolocation => {
    // do something with BackgroundGeolocation
    App.default.run();
  });
}
document.addEventListener('deviceready', run, false);
```

**Comment by mauron85** [comment]
@sokra I probably failed to express problem, because I don't see your answer as solution.

Because problem I'm describing will appear just by simply loading bundle with script tag.
It's about resolving runtime dependencies in bundle itself.

It's not about I want to do something with BackgroundGeolocation somewhere external from bundle.

**Comment by mauron85** [comment]
In other words:

```
function run() {
  const BackgroundGeolocation = require('cordova-plugin-mauron85-background-geolocation');
  // do something with BackgroundGeolocation
  App.default.run(); // this will never be executed, because bundle will fail to **load** due missing external dependencies.
}
document.addEventListener('deviceready', run, false);
```

**Comment by seajean** [comment]
Any solution?

**Comment by seajean** [comment]
@mauron85  I can see that you described it very well~  Do you find any solution now?

**Comment by mauron85** [comment]
@seajean I personally use workaround that loads app bundle with `document.createElement('script');`

https://github.com/mauron85/cordova-plugin-background-geolocation-example/blob/master/src/index.cordova.html#L17

It's suboptimal because loading and parsing app bundle javascript is unnecessary delayed, but in my use case (cordova app) it is defensible, as all javascript resources are already bundled with application.

But in case of hosted web applications we need better solution.
