### ISSUE TITLE
[windows 7]Could not excute 'if else' in webpack.config.js

### ISSUE THREAD

**Issue by xusai2014** [webpack/webpack#5989]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by xusai2014** [comment]
webpack 3.3.0


`
const nodeenv = process.env.NODE_ENV;
console.log('yes',nodeenv)
if(nodeenv  == 'development'){
console.log('development')
}
if(nodeenv.indexOf('de')>0){
console.log('de')
}
`

the result:
`
yes development
`
why?

Please give me help. Thanks a lot!

**Comment by sokra** [comment]
Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md).
