### ISSUE TITLE
Real world example (phonecat) of Webpack, Angular and features

### ISSUE THREAD

**Issue by mlmarius** [webpack/webpack#599]
Hi. I think it would be a great asset for new comers if you could show an example of how to use webpack to build an angular app. You could do the phonecat app and maybe also include external libraries from public cdn (angular, bootstrap, jguery). I think that would really help and it would make things really clear since people use the phonecat example to learn angular ... that is a "real world" example for a lot of new comers. I for one would really appreciate it.

**Comment by nkbt** [comment]
Hi, @mlmarius 
You can start with https://github.com/packetloop/angular-webpack
That is kind of build-core of our real-world app.

**Comment by shama** [comment]
Here is another: https://github.com/escapedcat/angular-phonecat-webpack-gulp

Closing as this appears to no longer be an issue. Thanks!
