### ISSUE TITLE
Entry point chunk hash not changing whereas content changes

### ISSUE THREAD

**Issue by ccambournac** [webpack/webpack#5990]
**Do you want to request a *feature* or report a *bug*?**
**Bug**

**What is the current behavior?**
I have implemented long-term caching of assets but I am experiencing a weird behaviour. 

I asynchronously load JS chunks via ES6 dynamic imports pushed into an array to be Promise.all'ed. I have a separate vendor chunk (via `CommonsChunkPlugin`) and inline both the JSON manifest and the JS manifest (via `CommonsChunkPlugin`, `webpack-manifest-plugin`, `chunk-manifest-webpack2-plugin`, and `html-webpack-plugin`). Every assets (main, vendor, manifest and chunks) use hashes via `[name].[chunkhash].js`. Webpack implementation makes use of `HashedModuleIdsPlugin`, `ModuleConcatenationPlugin`, and `webpack-chunk-hash` npm package.

Here is the issue: although all works fine at first production build, if I change content of a chunk module, its hash changes accordingly, the manifest JSON and JS change too, but the main.js hash stays the same although its content has effectively changed. I tried many things without any success.

**If the current behavior is a bug, please provide the steps to reproduce.**
Could provide an example if needed.

**What is the expected behavior?**
The main.js chunk hash should change.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Front-end cache invalidation is broken due to main.js hash not changing when any dynamically-imported chunk changes.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Win 7
Node 9
Webpack 3.8.1

**Comment by sokra** [comment]
Did you try it without all these `manifest` plugins?

otherwise

It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by ccambournac** [comment]
You were right @sokra, it is working now as expected after removing `chunk-manifest-webpack2-plugin`  and `webpack-chunk-hash`. Sorry for not trying that before...
