### ISSUE TITLE
new webpack.optimize.CommonsChunkPlugin无法分离vue-router

### ISSUE THREAD

**Issue by fooller** [webpack/webpack#5991]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

这是我在webpack里边的配置，前边的echarts vue  vux vuex 都可以实现分离 只有vue-router不可以
 new webpack.optimize.CommonsChunkPlugin({
      // name对应入口文件，入口文件单独抽离
      name: ['echarts', 'vue', 'vux', 'vuex','vue-router'],
      // 抽离路径
      filename: 'assets/js/[name].js',
      // filename:'assets/js/[name].[ext]',
      // 最小抽离两个文件
      minChunks: 2
    }),

**Comment by sokra** [comment]
Please file issues in English

**Comment by fooller** [comment]
ok i will
