### ISSUE TITLE
Use multiple mainFields in resolver

### ISSUE THREAD

**Issue by dispmaxstaff** [webpack/webpack#6010]
**Do you want to request a *feature* or report a *bug*?**
I want to request a feature.

**What is the current behavior?**
Current behavior is to use one of the mainFields and the first matched field will be used, ignoring all others.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Use multiple mainFields, i.e. if mainFields is `[["module", "main", "style", "styles"]]`, if one of main fields in mainFields[0] matches, then inject assets in all mainFields[0] found from vendor's package.json.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Because this will allow to import .css assets with just `require("package")`, if mainFields is `[["module", "main", "style", "styles"]]`.
Currently module authors include "style" field in their package.json and this will be quite useful to import css assets author intended for the module with one line instead explicitly requiring each individual css file which is the case now to my understanding.
i.e. if I do require("bootstrap") in vendor.js, then all .js assets and .css assets would be imported.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Using webpack 3.8.1, nodejs v6.11.2 , windows 8.1

**Comment by evilebottnawi** [comment]
You can achieve this using `loaderContext.getResolve({ mainFields: ["module"] })` and `loaderContext.getResolve({ mainFields: ["main"] })` and etc, css-loader will load `style` field by default in the next release
