### ISSUE TITLE
ModuleConcatenationPlugin does not preserve module.id

### ISSUE THREAD

**Issue by jeremiegirault** [webpack/webpack#6017]
**Do you want to request a *feature* or report a *bug*?**

It's looking like a bug.

**What is the current behavior?**

I'm trying to use `ModuleConcatenationPlugin`. The code used by some modules is using `module.id`.
At runtime, all hoisted modules share the same (hoisted) module.id.

**If the current behavior is a bug, please provide the steps to reproduce.**

See gist: https://gist.github.com/jeremiegirault/5c20cf51d79c737a09b8d370803622d1

**What is the expected behavior?**

It is expected for each module to have it's unique module id after hoisting, not the shared (hoisted) module id.

**If this is a feature request, what is motivation or use case for changing the behavior?**

N/A

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

node: 9.8.1
webpack: ^3.8.1
os: macOS 10.13.1

Thank you and keep up the good work !

**Comment by sokra** [comment]
Yep, looks like a bug. Using module.id should opt-out of ModuleConcatenation to get the correct module.id.

**Comment by jeremiegirault** [comment]
Wouldn’t it be possible to assign a unique module id? So that modules could be concatenated correctly.

--

Jérémie Girault

**Comment by sokra** [comment]
done
