### ISSUE TITLE
DllReferencePlugin / DllPlugin can't work in Safari 9.1, it will throw ERROR [Can't find variable] 

### ISSUE THREAD

**Issue by Dragon-Rider** [webpack/webpack#6019]
**Do you want to request a *feature* or report a *bug*?**

It's looking like a bug.

**Please tell us about your environment:**
Webpack version: 2.5.1
OSX 10.11.4
Safari 9.1 **(Only in safari version < 10)**
Language: [all | TypeScript X.X | ES6/7 | ES5 | Dart | ...]
ES6

Project Directory:
_~/my-project/config/webpack.config.js
~/my-project/config/webpack.dll.config.js_

_webpack.dll.config.js_
```
plugins: [
    new webpack.DllPlugin({
            path: path.join(__dirname, '../dest/[name]-manifest.json'),
            name: '[name]',
            context: path.join(__dirname, '../dest')
        })
]
```

_webpack.config.js_
```
plugins: [
    new webpack.DllReferencePlugin({
        name: 'commons',
        manifest: require(path.join(__dirname, '../dest/commons-manifest.json')),
        context: path.join(__dirname, '../dest')
    })
    new webpack.DllReferencePlugin({
        name: 'manifest',
        manifest: require(path.join(__dirname, '../dest/manifest-manifest.json')),
        context: path.join(__dirname, '../dest')
    })
]
```

**What is the current behavior?**
We use webpack to pack our source codes into "dest" Directory.
And in html files, we import the comons.js and other js files by using script tags.

But In Safari 9.1, our page is blank. And the console reports an error, suck like this:
![1511712697943-image](https://user-images.githubusercontent.com/8859216/33242156-56c2561e-d30b-11e7-8bff-610ff7e2c25d.png)

But in Chrome and Safari 10.1.1 are ok.

And if we delete the 'context' in webpack.DllPlugin，Safari 9.1 is ok.

**Comment by sokra** [comment]
How does the script tags look like?

**Comment by Dragon-Rider** [comment]
@sokra 
<img width="872" alt="dx-20171128 2x" src="https://user-images.githubusercontent.com/8859216/33308548-e0d7d856-d455-11e7-85ff-2a6e2489fa34.png">

**Comment by sokra** [comment]
I have no idea. Could be a browser bug?

**Comment by Dragon-Rider** [comment]
Perhaps. After all, it only appears in Safari version < 10.

Meanwhile，I have a question: How to set the context in the webpack.dll.config.js?

If the project directory is like "~/my-project/webpack.config.js"
```
new webpack.DllPlugin({
        path: path.join(__dirname, '../dest/[name]-manifest.json'),
        name: '[name]',
        context: __dirname
    })
```
Right?

But If the project directory is like "~/my-project/config/webpack.config.js"
And We use webpack to pack our source codes into "dest" Directory.
Which of the following is right?
```
new webpack.DllPlugin({
        path: path.join(__dirname, '../dest/[name]-manifest.json'),
        name: '[name]',
        context: path.join(__dirname, '../dest')
    })
```
or
```
new webpack.DllPlugin({
        path: path.join(__dirname, '../dest/[name]-manifest.json'),
        name: '[name]',
        context: path.join(__dirname, '..')
    })
```
Thanks for your reply. @sokra

**Comment by sokra** [comment]
Both DllPlugin and DllReferencePlugin should point to the same `context`. Best point them to the src directory.
