### ISSUE TITLE
ESLint enforces Node v4 features

### ISSUE THREAD

**Issue by VickyKoblinski** [webpack/webpack#6024]
**Do you want to request a *feature* or report a *bug*?**

Nice-to-have QoL update. Node v4 support isn't at end-of-life until April, but that is coming up.

**What is the current behavior?**
`.eslintrc::54: "node/no-unsupported-features": ["error", { version: 4 }],`

ESLint is enforcing Node v4 features and discourages newer ES6 features that Node v4 doesn't support (such as destructuring).

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

As per the [Webpack Installation/Pre-requisites Docs](https://webpack.js.org/guides/installation/), "Before we begin, make sure you have a fresh version of Node.js installed. The current Long Term Support (LTS) release is an ideal starting point. You may run into a variety of issues with the older versions as they may be missing functionality webpack and/or its related packages require."

So I expected newer Node feature support.

**If this is a feature request, what is motivation or use case for changing the behavior?**

I was refactoring/cleaning and came across this error: `[eslint] Destructuring are not supported yet on Node 4.0.0. (node/no-unsupported-features)`

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Webpack 3.8.1

**Comment by sokra** [comment]
We've upgraded to node 6 in the `next` branch (webpack 4).

webpack 3 will stay on node 4, because changing this would be a breaking change.
