### ISSUE TITLE
Webpack gives error while bundling modules having "main", "module" or "js:next" attributes set to "." in their package.json

### ISSUE THREAD

**Issue by aakashkharche04** [webpack/webpack#6026]
Let us assume I am using a module named **do-something** in my package.json as a dependency. This module has package.json with entry attributes like 

````
"main": ".",
"module": ".",
"jsnext:main": ".",
````

While doing bundling for this module through webpack, I get this error
``Module not found: Error: Recursion in resolving``

I am in an assumption that, the ``"main": "."`` attribute path will resolve to ``"main": "index.js"``
I am suspecting webpack is calling **do-something** module folder again and again.
 
I investigated more and it is coming from enhanced-resolve package that webpack uses for resolving paths. I use webpack major version 2 ``"webpack": "^2.4.0"``

But I have tried with the latest webpack version as well, it still does not work. Is there a way in webpack to bundle these kinds of dependent modules?

**Comment by sokra** [comment]
@webpack-bot move to webpack/enhanced-resolve

Looks like a bug.
