### ISSUE TITLE
webpack watch mode incorrectly throw a ENOENT error 

### ISSUE THREAD

**Issue by cshengx** [webpack/webpack#6036]
**Do you want to request a *feature* or report a *bug*?**
report a bug

**What is the current behavior?**
webpack watch mode will throw a "Module build failed: Error: ENOENT: no such file or directory " error when rename a file imported by a entry and rename it back

**If the current behavior is a bug, please provide the steps to reproduce.**
webpack.config.js:
```
const path = require('path');
const webpack = require('webpack');

module.exports = {
    entry: {
        'bundle': path.resolve(__dirname, './test.js')
    },
    output: {
        path: path.resolve(__dirname, '../dist'),
        filename: '[name].js'
    },
    module: {
        rules: [
            {
                test: /\.js$/,
                use: {
                    loader: 'babel-loader',
                    options: {
                        babelrc: false,
                        presets: [path.resolve(__dirname, '../node_modules/babel-preset-es2015')],
                        cacheDirectory: path.resolve(__dirname, '../build-cache')
                    }
                },
                exclude: /node_modules/
            }]
    },
    plugins: [
        new webpack.LoaderOptionsPlugin({
            options: {
                babel: {
                    babelrc: false,
                    presets: [path.resolve(__dirname, '../node_modules/babel-preset-es2015')],
                    cacheDirectory: path.resolve(__dirname, '../build-cache')
                }
            }
        })
    ]
};
```

test.js:
```
import "./test1"
const a = 1;
```

test1.js:
`const b = 2;`

1 run webpack -w
2 rename test1.js to test2.js
3 edit test.js `import "./test1"` to `import "./test2"`
now it works fine
4 rename test2.js back to test1.js
5 edit test.js `import "./test2"` to `import "./test1"`
now webpack still throw a error "Module build failed: Error: ENOENT: no such file or directory, open 'dir/test1.js'"

**What is the expected behavior?**
should not throw the error and compile success

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
webpack: 3.8.1 
nodejs: 6.11.2
os :win7 pro

**Comment by TheLarkInn** [comment]
@chaosheng-git I've not seen a specific commit for this landing in v4, but we are <30 days out from releasing v4 final, would you mind testing this on v4 and seeing if this is still an issue? 

Thanks!

**Comment by TheLarkInn** [comment]
Will confirm this is an issue still in webpack 4.0.0-beta. 

Ironically my case: 
Changed file names, and then renamed path names, but had to repeat the @chaosheng-git's steps 3-5 2 times and reuse a filename for this to reproduce. As if the cache is not invalidating after the path/file rename is reused / rereferenced.

**Comment by TheLarkInn** [comment]
@sokra are we going to try and land this for v4 release? If so: 

- [ ] Identify where contributors can help fix
- [ ] Add tests to guard this

**Comment by TheLarkInn** [comment]
Awesome! Will you start by submitting a PR, then we can help guide you for tests, etc.

**Comment by chaosheng-git** [comment]
PR submitted #6451

**Comment by rdmclin2** [comment]
run into this bug with webpack 3.0，is there any chance to solve this problem in wepack 3.0?

**Comment by chaosheng-git** [comment]
@rdmclin2 I use custom watch file system to avoid this issue in webpack 3, and it's works fine for me,  I'll publish a npm module later.

**Comment by a-x-** [comment]
Still actual and annoying

Similar case: rename ./Component.js → ./Component.jsx
webpack watch throws:
`Error: ENOENT: no such file or directory, open ...`

**Comment by sokra** [comment]
Fixed in webpack 5
