### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by jitchavan** [webpack/webpack#6043]
**Do you want to request a *feature* or report a *bug*?**
>>  bug

**What is the current behavior?**
`ReferenceError: window is not defined at new Provider (webpack:///./src/provider.js?:42:86) at Object.<anonymous> (/home/Demo-App/demo/tmp/webpack:/src/routes/requireAuthentication.js:10:20) at webpack_require (/home/Demo-App/demo/tmp/webpack:/webpack/bootstrap 4f5669005e928a572010:19:1) at Object.exports.__esModule (/home/Demo-App/demo/tmp/webpack:/src/routes.js:15:1) at webpack_require (/home/Demo-App/demo/tmp/webpack:/webpack/bootstrap 4f5669005e928a572010:19:1) at Object.<anonymous> (/home/Demo-App/demo/tmp/webpack:/server.babel.js:9:1) at webpack_require (/home/Demo-App/demo/tmp/webpack:/webpack/bootstrap 4f5669005e928a572010:19:1) at Object.<anonymous> (/home/Demo-App/demo/tmp/bundle.js:50:19) at webpack_require (/home/Demo-App/demo/tmp/webpack:/webpack/bootstrap 4f5669005e928a572010:19:1) at /home/Demo-App/demo/tmp/webpack:/webpack/bootstrap 4f5669005e928a572010:39:1`

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
build completing and serving server-side rendered HTML

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
node: 8.9.1 
os: ubuntu 16.04 
webpack: 1.15.0 
webpack-dev-server: 1.16.5 
oauth2-client-js: "0.0.15", 
react: 15.4.0", 
react-dom: 15.4.0"

**Comment by sokra** [comment]
> webpack: 1.15.0

webpack 1 is no longer supported
