### ISSUE TITLE
Bug Webpack 3.9.0 breaks `--stdin` config

### ISSUE THREAD

**Issue by tomciopp** [webpack/webpack#6046]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
On version 3.9.0 of webpack I receive the following error message 

```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.watchOptions has an unknown property 'stdin'. These properties are valid:
   object { aggregateTimeout?, poll? }
   -> Options for the watcher
```

**If the current behavior is a bug, please provide the steps to reproduce.**
`$: node node_modules/.bin/webpack-dev-server --inline --colors --https --hot --stdin --host localhost --port 8080 --public localhost:8080`

I'm unsure whether the bug is in webpack or webpack-dev-server. However the bug has occurred during an upgrade to webpack so I'm posting here.

**What is the expected behavior?**
Running the same command using webpack version 3.8.1
`$: node node_modules/.bin/webpack-dev-server --inline --colors --https --hot --stdin --host localhost --port 8080 --public localhost:8080`

It starts up || shuts down webpack on localhost:8080 when the server is started/stopped.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

OS: MacOS High Sierra version 10.13.1 (17B1002)
node: v8.9.1
webpack: 3.8.1/3.9.0

**Comment by evilebottnawi** [comment]
@tomciopp known issue, PR - https://github.com/webpack/webpack/pull/6044, in near future we will release `3.9.1` with fix, thank for issue!
