### ISSUE TITLE
`watchOptions.ignored` is now an "unknown property" in v3.9.0

### ISSUE THREAD

**Issue by Tokimon** [webpack/webpack#6047]
**Do you want to request a *feature* or report a *bug*?**  
bug

**What is the current behavior?**
I get this error, when adding an `ignored` regex to watchOptions:

```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration[0].watchOptions has an unknown property 'ignored'. These properties are valid:
   object { aggregateTimeout?, poll? }
   -> Options for the watcher
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Add the `ignored` property to the `watchOptions`:

```js
{
  watchOptions: {
      poll: 500,
      ignored: /node_modules/
    }
}
```

**What is the expected behavior?**
It shouldn't throw an error as the `ignored` is [clearly stated in the documentation](https://webpack.js.org/configuration/watch/#watchoptions-ignored) + it was originally introduced to solve the problems with heavy CPU usage while watching.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Webpack** `3.9.0` (failing version) - Webpack `3.8.1` works
**Node**: 6.10.0
**npm**: 5.5.1

**Comment by sokra** [comment]
fixed in https://github.com/webpack/webpack/pull/6044 3.9.1
