### ISSUE TITLE
Memory usage regression related to uglify between Webpack 2.1 beta to 3.X

### ISSUE THREAD

**Issue by Phoenixmatrix** [webpack/webpack#6048]
**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**

Using the uglify plugin on a large project (3000-4500 modules) to do a production build seems to have fairly high memory usage and fails with an an heap out of memory error. It's not 100%, but in our projects is fairly easy to repro in all versions I tried, 2.7 all the way to the latest 3.X. In the older 2.1 (beta) version, it never happened over hundreds of builds.

I've tried to narrow down the exact change that causes this but have been unable to do so.

**If the current behavior is a bug, please provide the steps to reproduce.**

Using a fairly large build (3000+ modules),  we're using the following config for the Uglify plugin. Removing it stops the issue from happening as far as I can tell. Sourcemaps enabled are not necessary to repro but make it more frequent:

```js
      new webpack.optimize.UglifyJsPlugin({
        compress: {
          warnings: false,
          reduce_vars: false,
          sequences: false,
        },
        output: {
          comments: false,
        },
        sourceMap: true,
      })
```

**What is the expected behavior?**

So  just using `--max_old_space_size=XXXX` fixes the issue and normally I'd just punt on this saying "our build is big, so it's normal", but the fact that it never happened in 2.1 leads me to think there's a regression somewhere.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Happens in both node 6 LTS and Node 8 LTS, Webpack 2.7 as well as 3.X, MacOS as well as Linux, across several applications (but is related to their size)

**Comment by evilebottnawi** [comment]
@webpack-bot move to webpack-contrib/uglifyjs-webpack-plugin
