### ISSUE TITLE
silent mode

### ISSUE THREAD

**Issue by sarkiroka** [webpack/webpack#6051]
**Do you want to request a *feature* or report a *bug*?**
both of them

**What is the current behavior?**
I use webpack config with stats: 'errors-only' settings and when I turn on watch, the console appear an unwanted message: "webpack is watching the files"

**If the current behavior is a bug, please provide the steps to reproduce.**
config or webpack -w

**What is the expected behavior?**
If it is not an error (not it is), then shouldn't appear. Or present a really silent mode :)

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by sokra** [comment]
Yep, it makes sense to add an options for this output to the configuration.

Could be combined with #5895

Send a PR

**Comment by EugeneHlushko** [comment]
@sarkiroka hi are you planning on doing a pr? otherwise i can do and update the docs

**Comment by sarkiroka** [comment]
@EugeneHlushko, no. I will happy when you can do this

**Comment by TheLarkInn** [comment]
@EugeneHlushko looks like it's all yours, feel free and ping myself and sokra when the PR is submitted, or if you need any help along the way.

**Comment by EugeneHlushko** [comment]
@TheLarkInn PR is there for a while, want to join the review as noone is active recently: webpack/webpack-cli#200
