### ISSUE TITLE
ReferenceError: webpackJsonp is not defined 

### ISSUE THREAD

**Issue by hackintoshrao** [webpack/webpack#606]
Here is my webpack configuration file , im getting this error on loading the html's containing both p1.chunk and p2.chunk  
     var commonResourcePlugin = require('webpack/lib/optimize/CommonsChunkPlugin')
     module.exports = {

```
    entry: {

        p1: './js/components/character/main-character.jsx',
        p2: './js/components/character/character_template/character_template_entry.jsx'
    },

    output: {
        filename: './js/[name].chunk.js'
    },
    externals: {
        "jquery": "jQuery",
        "$": "$",
        "React": "React"
    },
    module: {
        loaders: [
            {
                test: /\.jsx$/,
                loader: 'jsx-loader'
            } // loaders can take parameters as a querystring
        ]
    },
    resolve: {
        extensions: ['', '.js', '.json', '.coffee', 'jsx']
    },
    plugins: [
        new commonResourcePlugin("./js/commons.chunk.js");
    ]
};
```

**Comment by sjelfull** [comment]
@Karthic-Hackintosh Could you clarify what you mean by "adding commons.chunk.js"? I have the same problem, and I think this issue might be more helpful if you explain where you added it?

**Comment by tuliomonteazul** [comment]
@sjelfull I think it means the loading order of your app and vendor files in your html. I had this problem and I realised that my `<script src='app.js'>` was before `<script src='vendor.js'>`. Switching orders fixed it.

**Comment by Karthic-Hackintosh** [comment]
@sjelfull , @tuliomonteazul  is right !

**Comment by JMingZI** [comment]
I have understanded.
because we use `webpack.optimize.CommonsChunkPlugin` plugin but not follow in `html file`。
Need to introduce public JS files in the HTML page, like this:
```html
<script src="common.js"></script>
<script src="list.js"></script>
```

**Comment by Yidada** [comment]
I have occur the same problem , I know the common.js should put before list.js. But there is a scene that I want have a style.js to require all the stylesheet like main.css in this js file. So I cannot put the style.js after the common.js which lead to a 0.5s raw html show in the browser. Hope to get a perfect solution. Thx a lot!

**Comment by tuliomonteazul** [comment]
@Yidada What is in you common.js? Just external libraries or also code written by you?

My `vendor.js` (or `common.js`) is just libraries like `moment`, `redux`, `superagent`, etc
My `app.js` has all my view components including their css.
Not sure if it's the best practice but it works well for me.

Maybe in your case you need a 3rd entry

**Comment by qiqihaobenben** [comment]
Need to introduce public JS files in the HTML page, like this:
```
    <script src="common.js"></script>
    <script src="list.js"></script>
```
and <script src="common.js"></script>,Must be the first，otherwise, it will be reported to the wrong.

**Comment by 89alex** [comment]
good，i study now

**Comment by LiuYashion** [comment]
`<script src="build/vendor.js"></script>
<script src="build/0.js"></script>
<script src="build/1.js"></script>
<script src="build/bundle.js"></script>`

it's easy to understand vendor.js should be put ahead
but I tried order like above:

`<script src="build/vendor.js"></script>
<script src="build/bundle.js"></script>
<script src="build/0.js"></script>
<script src="build/1.js"></script>`

`require.ensure(['../app/js/a'], function(require){
    require('../app/js/c');
    console.log('done!');
});

require.ensure(['../app/js/b'], function(require){
    require('../app/js/c');
    console.log('done!');
});

// bundle..etc
`

so I got an error in my browser:
done!
done!
vendor.js:102 GET http://127.0.0.1:8020/workspace/webserver/0.js 
vendor.js:102 GET http://127.0.0.1:8020/workspace/webserver/1.js 

I don't know why bundle.js needs to be list last
they are not independent? bundle.js/0.js/1.js?

**Comment by escapedcat** [comment]
In our case it using https://github.com/turbolinks/turbolinks in a static page (generated via ruby on rails) which was loading our SPA was the issue.

**Comment by DaveWelling** [comment]
In case it is helpful to somebody, I ran into this because my common chunk was crashing.  The real problem was that I had a node module that was intended for node and was not being pre-compiled by babel.  Fix like so:
```module: {
        rules: [
            {
                test: /\.js$/,
                exclude: [ /joi-browser/ ],
                include: [
                    // These are modules that are used as is in Node, but must be sent through babel
                    // to use in the browser.
                    path.join(__dirname, 'node_modules', '<your node module that needs babel>'),
                    path.join(__dirname, 'src')
                ],
                loaders: ['babel-loader']
            },```
