### ISSUE TITLE
webpack -p with EnvironmentPlugin doesn't work

### ISSUE THREAD

**Issue by aaronbeall** [webpack/webpack#6062]
**Do you want to request a *feature* or report a *bug*?**

Bug, or I don't understand the documentation.

**What is the current behavior?**

I am using `webpack -p`, which the [docs describe as as shortcut](https://webpack.js.org/api/cli/#shortcuts) for:

> --optimize-minimize --define process.env.NODE_ENV="production"

In my `webpack.config.js` I use the `EnvironmentPlugin`:

```
new webpack.EnvironmentPlugin(["NODE_ENV"])
```

However, if I try to use `process.env.NODE_ENV` in `webpack.config.js` I simply get `undefined`, and in my bundled code I get `process.env` but `process.env.NODE_ENV` is also `undefined`.

**If the current behavior is a bug, please provide the steps to reproduce.**

See above

**What is the expected behavior?**

I expected `webpack.config.js` to have the value `process.env.NODE_ENV == "production"` and at runtime in the bundled code to have the same thing.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

ts-node v3.3.0
node v8.6.0
typescript v2.6.1
webpack 3.9.1
OSX 10.11.6 (El Capitan)

**Comment by daft300punk** [comment]
This is mentioned on the docs page https://webpack.js.org/guides/production/, the para in blue(Technically ...). In case you just want to separate config files in prod and dev, you coul go for a common config file and use webpack-merge to separate differences. What is your use case for needing process.env.NODE_ENV inside webpack config?

**Comment by aaronbeall** [comment]
@daft300punk Thanks that definitely explains what I misunderstood. 

My use case is to disable `css-loader` source-maps in production, because they are causing a "flash of unstyled content"... separating out a production config for just that one option flag seems a bit heavy at this point, but I guess that's the right way to do it.
