### ISSUE TITLE
Support logging statements for sourcemaps

### ISSUE THREAD

**Issue by nikhilgaba** [webpack/webpack#6063]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Building a large codebase, sourcemaps do not provide any console logging to show that the build is in fact proceeding forward.
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Add console logging to show the progress of the build during chunk generation
**If this is a feature request, what is motivation or use case for changing the behavior?**
The end user can confirm that the build is actually proceeding and that it is not just hanging.
**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by EugeneHlushko** [comment]
Are you planning to work on this or do you need help? @nikhilgaba

**Comment by nikhilgaba** [comment]
You could take a go at it. I wont be able to have a look at it until early next week. @EugeneHlushko

**Comment by EugeneHlushko** [comment]
Okay, will take it on Sat, @sokra any comments on this?

**Comment by sokra** [comment]
We currently don't have a way for logging in webpack. There is a kind of progress support in the next plugin system, but it doesn't support logging or more inner plugin logging.

We should consider adding logging support to the plugin system.

This can be handled through the `intercept` API: 

``` js
compiler.hooks.something.tap("MyPlugin", () => {
  for(...) {
    if(compiler.hooks.something.log !== undefined) {
      compiler.hooks.something.log(step, message);
    }
  }
});
```

``` js
compiler.hooks.something.intercept({
  log: (tap, step, message) => {
    console.log(tap.name, step, message);
  }
});
```

This can be integrated into the ProgressPlugin.

**Comment by sokra** [comment]
The ProgressPlugin has now a new feature to allow fine progress reporting by plugins. This is how it can be used:

``` js
compiler.hooks.someHook.tap({
  name: "MyPlugin",
  context: true
}, (context, arg1, arg2) => {
  const reportProgress = context && context.reportProgress || () => {};

  reportProgress(0.1, filename);
  reportProgress(0.4, filename);
  reportProgress(0.8, filename);
});
```

**Comment by sokra** [comment]
Somebody can send a PR to add this to expensive plugins
