### ISSUE TITLE
Got “Blocked:mixed content” on HTTPS website

### ISSUE THREAD

**Issue by yoginth** [webpack/webpack#6067]
**Do you want to request a feature or report a bug?**

Neither but bug on my end

**What is the current behavior?**

I'm Running a Website using Webpack in Production.

I was surprised to see in Chrome console the following error about loading the js file which is mixed with weback and laravel-mix

![untitled-1](https://user-images.githubusercontent.com/10177861/33589080-7e7180da-d99c-11e7-88b8-d00094e0780b.png)

**My questions:**

- How can we have a mixed content on a website loaded using HTTPS protocol?
- How can I fix the error? I don't plan to serve website over HTTP and I want my js to load properly both in development and production.

**Comment by sokra** [comment]
Not a webpack issue.

**Comment by sokra** [comment]
Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md).
