### ISSUE TITLE
HMR fails to update if accept module name has file extension and main import doesn't

### ISSUE THREAD

**Issue by leesaxby** [webpack/webpack#6069]
**Do you want to request a *feature* or report a *bug*?**
Bug...possibly

**What is the current behavior?**
If you add an extension to either the main app module name `import App from './App'` or `accept` module name ` module.hot.accept('./App.js', () => { render(App); });` HMR fails to update.

```
import App from './App';

const render = Component => {
    ReactDOM.render(
        <AppContainer>
            <Component />
        </AppContainer>,
        document.getElementById('root')
    );
};

...

if (module.hot) {
    module.hot.accept('./App.js', () => { render(App); });
}

```

Further detail here: https://github.com/leesaxby/webpack-hmr-issue.

**If the current behavior is a bug, please provide the steps to reproduce.**
Reproduceable repo here: https://github.com/leesaxby/webpack-hmr-issue

**What is the expected behavior?**
Not sure if this would be considered a bug, but can be a bit of a gotcha if you accidentally add a file extension to one of the module names as the HMR console output is the same with or without the extension.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Chrome
Node v9
Ubuntu
Webpack 3.10.0
webpack-dev-server  2.9.5

**Comment by sokra** [comment]
It must be the same string content. You are literally accepting this import selected by source.

**Comment by leesaxbygresham** [comment]
Thanks for the reply.

When the accept name contains the extension (differing from the main app import string).
You update the `App` module and the accept callback will fire once but `App` will be the old version (without changes), then any further changes to `App` won't trigger the accept callback.

Would you be able to  clarify what webpack is doing here, to help in understanding?
Thanks

**Comment by alexander-akait** [comment]
We have docs https://webpack.js.org/concepts/hot-module-replacement/
