### ISSUE TITLE
"External requires" documentation clarification

### ISSUE THREAD

**Issue by ghostwords** [webpack/webpack#607]
Hi, could you please expand on "do it like this" in the [docs for requiring modules at-will from outside the bundle](http://webpack.github.io/docs/webpack-for-browserify-users.html#external-requires)? I think an explanation of what the code snippets are and what they do would be great.

Do you suggest to build a bundle that will produce something like `this['require'] = function(parentRequire) { ...` (according to [libraryTarget docs](http://webpack.github.io/docs/configuration.html#output-librarytarget)), and then use that bundle to load any module from any other bundle? If so, should this just be a plugin/loader, built once for everybody?

My use case is to be able to require any module for debugging purposes (examine its state, call its methods, ...) from the browser JS console.

**Comment by pksjce** [comment]
This issue was moved to webpack/webpack.io#106
