### ISSUE TITLE
Add support for more complex selectors for sideEffects

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack#6074]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
webpack searched for `"sideEffects": false` in package.json to perform the extra optimizations for esm modules. However if `false` is a string, the optimization isn't detected. 

We should probably (in the case that package authors might mistake this as "false" vs `false`) put the wrong value in, and theres no simple way to detect (as a dev) why the 'deopt' occurs.
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
`"sideEffects": "false"` in package.json works the same as `"sideEffects": false`

**If this is a feature request, what is motivation or use case for changing the behavior?**
Motivation described above.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
webpack 4.0.0-alpha

**Comment by CWelshE** [comment]
I'm not quite sure how to architect the test case(s) for this issue. However, I am looking into existing tests to see if I can reuse anything.

**Comment by sokra** [comment]
`"sideEffects": "false"` should mark every module as side effect free except a file named `false`

**Comment by CWelshE** [comment]
Oh, I may have completely misunderstood the issue, then. Am I just to implement the case where specifying a `String` instead of a `Boolean` value tells webpack which files are known to have effects? If so, should we allow `Array`s of strings as well?

**Comment by sokra** [comment]
yep Array of string should be allowed too.

It should support glob expressions too.

``` js
"sideEffects": [
  "src/**/*.js"
  "./lib/abc.js"
]
```

**Comment by CWelshE** [comment]
Got it - I'll work on that, and inquire further if I have any difficulties.

**Comment by CWelshE** [comment]
I've been trying to decipher some segments of this particular Plugin instance, but I might be lacking some context. The first ambiguous thing in here (to me) is the usage of `harmony`, so I ran off to check out examples. As far as I can tell, this is part of how webpack keeps collisions out of imports. I can tell that it will take some time before I grasp the larger web of interaction, so I'll proceed with that assumption (unless somebody corrects me, which would be welcome anyways).

In any case, do I have access to the name of the module or the filename when `normal-module-factory` returns the data object? I'm assuming that's how I will be comparing it to the array of strings the user provides. It looks like I may be able to call `__filename` from the Node API, but it's unclear to me whether that would report what I want inside of this context.

**Comment by sokra** [comment]
https://github.com/webpack/webpack/blob/next/lib/optimize/SideEffectsFlagPlugin.js#L19

`resolveData.relativePath` is the relative path of the file relative to the package.json.

**Comment by CWelshE** [comment]
Oh, thanks for that. This will make things much easier.

**Comment by CWelshE** [comment]
Apologies for the gap!

Here's where I am at:

- `glob` expansion via `glob` (run against the user strings if they both contain `*` and there was no prior match for the current module);
- matches for relative paths.

I need to make tests for:
- arbitrary relative file paths
- glob paths of arbitrary depths and file extensions

I guess there might be some potential slowdown if there's a significantly larger `glob` than normal. I'll measure performance if it's wanted. Otherwise, I'll continue immersing myself to learn `webpack` contribution knowledge. 😃

**Comment by sokra** [comment]
Instead of using `glob`: Convert the glob expression into a RegExp and just test the relative path with it.

`src/**/abc/*.js` => `/\/src\/.+\/abc\/[^\/]+\.js($|\/)/`

`./src/def` => `/^\./src\/def($|\/)/`

**Comment by CWelshE** [comment]
Oh, interesting. I'd not thought of that. I'll convert it over accordingly!

**Comment by sokra** [comment]
Maybe just use https://github.com/fitzgen/glob-to-regexp

**Comment by reergymerej** [comment]
Hey, @CWelshE.  Want to tag team this?  I've got the tests for `false`/`"false"` done and looking to support the glob option [here].

[here]: https://github.com/reergymerej/webpack/commit/591d0534bb551f3f8d7a28721fa38ed1adf79d8e

**Comment by abiduzz420** [comment]
Hi @CWelshE I want to know if you are still working on it ?

**Comment by reergymerej** [comment]
@abiduzz420 I've got a PR that needs a modification to the glob feature.  It's a pretty small change, but I'm not able to follow up on it right now.

**Comment by TheLarkInn** [comment]
@reergymerej is there any notes you could provide to assist others? Happy to help find another contributor.

**Comment by reergymerej** [comment]
The PR is https://github.com/webpack/webpack/pull/6334.  I just needed to switch the library doing with glob checking to minimatch and update tests.  The test structure is already there.  It's should be as easy as changing the library in the source and the assertions to go along with those in the PR review notes.

**Comment by jevan0307** [comment]
Hi, may I take up this issue and continue what @reergymerej has done?

**Comment by reergymerej** [comment]
@jevan0307, please do.  I pushed the work in progress I had.  https://github.com/webpack/webpack/pull/6334/commits/2b45e65364b12dde94658c835495d043758862a6

**Comment by srq18211** [comment]
Some of the choices will conflict with a sideEffects ，such as inline-source-map
Maybe there are other options that will do the same thing
`module.exports = {
    devtool: 'inline-source-map'
}`
