### ISSUE TITLE
Webpack 4: include UglifyJsPlugin under the production mode

### ISSUE THREAD

**Issue by iamakulov** [webpack/webpack#6075]
**Do you want to request a *feature* or report a *bug*?**

A feature.

**What is the current behavior?**

`mode: 'production'` in webpack 4 doesn’t enable the minificator. The code with `mode: 'production'` comes out not fully ready for production.

**What is the expected behavior?**

`mode: 'production'` in webpack 4 enables the minificator (the `UglifyJsPlugin`).

**If this is a feature request, what is motivation or use case for changing the behavior?**

I was testing the `mode` switch in webpack 4, and what surprised me was that the `UglifyJsPlugin` is not enabled in the production mode by default.

My expectations were like “I write `mode: 'production'`, specify entry, output, a couple of loaders, and it just works.” Without minification, the production mode feels half-baked or incomplete – I still have to add additional plugins to make it work.

Would it make sense to enable the `UglifyJsPlugin` in production? We’ll have to make the plugin disableable (for folks that use other minifiers), so probably it would make sense to add an `optimization.minimize: true/false` option that enables/disables it. Because this plugin has options, we could either allow passing them into `optimization.minimize`:

```js
module.exports = {
  optimization: {
    minimize: {
      sourceMap: true,
    },
  },
};
```

or create a separate field for them (e.g. `optimization.minimizeOptions`).

**Comment by TheLarkInn** [comment]
So I'm on the fence with this one for a few reasons and I'll open it for discussion: 

* we are working towards multiple minifiers (closure, uglify) as being options with pure integrations
* in the past we've seen some upstream issues with our default uglify implementation and since moved out the recommended one (uglify-es) to a separate package (trivial but worth mentioning).

**Comment by jouni-kantola** [comment]
Wouldn't this be one of those cases where a default one would be one less thing to configure? uglify by default, override with config.

**Comment by kzc** [comment]
@sokra @TheLarkInn If `uglifyjs-webpack-plugin@1.x` is not incorporated into `webpack@4` by default, then it would be better to remove `uglifyjs-webpack-plugin` from webpack's `package.json` altogether:

https://github.com/webpack/webpack/blob/v4.0.0-alpha.0/package.json#L24

There is much user confusion with `webpack -p` running the ES5-only `uglifyjs-webpack-plugin@0.4.6` unconditionally regardless of people specifying the ES6+ compatible `uglifyjs-webpack-plugin@1.x` plugin in their `package.json`:

* https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/179#issuecomment-349136025
* https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/144#issuecomment-338245526
* https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/123#issuecomment-328705400
* https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/112#issuecomment-329069520
* https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/104#issuecomment-321529673

**Comment by iamakulov** [comment]
> we are working towards multiple minifiers (closure, uglify) as being options with pure integrations

Would that prevent us from enabling UglifyJS by default? I.e. if we have a multiple available minifiers, we could make `options.minimize` accept a string with a minifier name (e.g. `options.minimize: 'closure'`) and default it to `'uglifyjs'`.

(Options, in this case, might go into a separate field.)

> in the past we've seen some upstream issues with our default uglify implementation and since moved out the recommended one (uglify-es) to a separate package (trivial but worth mentioning)

I agree with @kzc and would also love to see this fixed. We should either include a good working solution or not include it at all – or otherwise we just add complexity (“We serve UglifyJsPlugin out of the box, but don’t use it, go and install a separate plugin and use that one”). (But better include one – if we’re moving to also including Closure Compiler and other minifiers.)

Is there something that prevents us from using `uglifyjs-webpack-plugin@1` in webpack 4?

**Comment by michael-ciniawsky** [comment]
`uglifyjs-webpack-plugin` v1.0.0 landed on the `next` (#5940)  but isn't released yet (`webpack v4.0.0-alpha.0`). +1 to not included it as a direct dependency anymore (alias) and instead handle it in a different way via `mode` somehow.

**webpack.config.js**
```js
const config = {
   mode: process.env.NODE_ENV || 'development'
   plugins: this.mode === 'production' 
     ? [
       ...plugins,
       new UglifyJSPlugin() || new BabelMinifyPlugin() || ClosurePlugin()
     ]
     : [ ...plugins ] 
}
```

**Comment by sokra** [comment]
On the one hand when included in production mode uglifyjs can get outdated and it's more complex to use other minimizers,

on the other hand it's easier to getting started and we avoid users publishing unminimized bundles to prodution.

...

I guess the arguments pro inclusion have more weight. We can use `optimize.uglifyjs` for options/disable.

Best case: Users only need mode: production to create an production build and no other options....

**Comment by sokra** [comment]
cc @gaearon

**Comment by michael-ciniawsky** [comment]
Many folks just generally seemed to be confused by the current `-p` flag's behavior e.g expecting `BabelMinifyPlugin()` to be applied automatically when using it etc. So maybe if the (JS) Minifier (e.g `config.optimization.minifier`) could be customized (with still defaulting to `uglifyjs-webpack-plugin`) and `webpack -p` is 💯 based upon `config.mode = 'production'` && settings in `config.optimization` things would become clearer and (some trivial but still) breaking changes (e.g `options` => `uglifyOptions`) in direct dependencies could be handled internally and abstracted from users and released as minor/patch then

**Comment by d3viant0ne** [comment]
Given we are moving towards simplifying the on boarding process, I agree with @sokra's point about having a default for the production build.

The de facto minification tool is still uglify, I don't see an issue with defaulting it. We ( on the contrib side ) just need to make a point of updating it in webpack as we release new versions.

**Comment by wtgtybhertgeghgtwtg** [comment]
I'd suggest keeping it out of the core `webpack` package, but unless `babel-minify` lands between now and the time `webpack@5` comes into beta, it might be a little pointless.

**Comment by iamakulov** [comment]
🎉 Seems like alpha.1 now includes `optimization.mininize`, and itʼs on in the production mode! #6132

Thanks folks, closing this :–)

**Comment by Maximaximum** [comment]
In my opinion, production mode should also have `uglifyOptions.output.comments = false` by default

**Comment by iamakulov** [comment]
@Maximaximum Better make a new issue – the comment won’t be noticed here.

(Also: does this affect webpack or UglifyJS’ default settings?)

**Comment by Maximaximum** [comment]
Opened a new issue regarding comments: https://github.com/webpack/webpack/issues/7246
