### ISSUE TITLE
Duplicate record entries caused by RuleSet `ref--` keys

### ISSUE THREAD

**Issue by rowanoulton** [webpack/webpack#6080]
**Do you want to request a *feature* or report a *bug*?**

Report a bug.

**What is the current behavior?**

Duplicate entries are added to records when RuleSet `ref--` values are needed and the order of loader config changes. This causes the records file to balloon over time.

**If the current behavior is a bug, please provide the steps to reproduce.**

Please see https://github.com/rowanoulton/webpack-records-ruleset-ref-bug for an example.

**What is the expected behavior?**

Duplicate entries should not occur. Perhaps RecordIdsPlugin should strip `ref--` values from the loader request to prevent this.

Reproduced on webpack 3.4 and 3.10.0.

**Comment by sokra** [comment]
webpack gives these option objects a unqiue ident, by default the position in the config. You can provide your own ident with this config:

``` js
module.rules: [
{ test: ...,
  use: [
    {
      loader: ...,
      options: ...,
      ident: "some unique id"
    }
  ]
}
]
```

**Comment by rowanoulton** [comment]
@sokra Adding an `ident` property in that way throws a validation error:

```bash
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module.rules[0].use should be one of these:
   non-empty string | function | object { loader?, options?, query? } | function | [non-empty string | function | object { loader?, options?, query? }]
   -> Modifiers applied to the module when rule is matched
   Details:
    * configuration.module.rules[0].use should be a string.
    * configuration.module.rules[0].use should be an instance of function
    * configuration.module.rules[0].use should be an object.
    * configuration.module.rules[0].use should be an instance of function
    * configuration.module.rules[0].use[0] should be a string.
    * configuration.module.rules[0].use[0] should be an instance of function
    * configuration.module.rules[0].use[0] has an unknown property 'ident'. These properties are valid:
      object { loader?, options?, query? }
```

Is it possible that [this schema](https://github.com/webpack/webpack/blob/master/schemas/webpackOptionsSchema.json#L917-L943) needs to be updated to include the `ident` property?

**Comment by rowanoulton** [comment]
I have experimented with the change to schema and it works. Submitted #6089 above for review.

**Comment by sokra** [comment]
great
