### ISSUE TITLE
Stats.toJson() is taking a lot of the build time on incremental builds (3sec+)

### ISSUE THREAD

**Issue by MagicDuck** [webpack/webpack#6083]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
During incremental build, the Stats.toJson() takes 3s+ (out of 10s) to do it's thing. See profiler picture below. 
![image](https://user-images.githubusercontent.com/95201/33693754-622542e6-daa9-11e7-9776-03de420dce1a.png)

Attached CPU profile from chrome dev tools as well.
[CPU-20171206T171932.zip](https://github.com/webpack/webpack/files/1537455/CPU-20171206T171932.zip)

The time taken seems to be in the area of the code guarded by "showChunks" and "showModules". Also, setting the stats options to disable stuff on the webpack config does not seem to make any difference. 

**If the current behavior is a bug, please provide the steps to reproduce.**

Run the incremental build on a larger project.

**What is the expected behavior?**

Minimal performance impact and/or options to disable most of the expensive stats. Flag the expensive stats in the documentation at https://webpack.js.org/configuration/stats/ .

**If this is a feature request, what is motivation or use case for changing the behavior?**
performance.
**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
node v8.9.1, webpack 3.8.1

**Comment by sokra** [comment]
Do you use any plugin that store the stats in a file?

**Comment by MagicDuck** [comment]
ah, you're right, we are using the ManifestPlugin
![image](https://user-images.githubusercontent.com/95201/33737354-ae728432-db4a-11e7-94ae-8149318638d3.png)

**Comment by MagicDuck** [comment]
interesting, rolling back from `webpack-manifest-plugin@1.3.2` to `webpack-manifest-plugin@1.1.0` does not make any difference.

**Comment by sokra** [comment]
Could be... Maybe you find the problem by profiling...
