### ISSUE TITLE
HMR fails in the WebWorker

### ISSUE THREAD

**Issue by webschik** [webpack/webpack#6084]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
HMR fails in the WebWorker

**If the current behavior is a bug, please provide the steps to reproduce.**

```html
<!-- index.html -->
<head>
  <script src="./polyfill.js"></script>
  <script src="./index.js"></script>
</head>
```

```js
// index.js
// ...
const worker = new WebWorker('./worker.js');
// ...
```

```js
// worker.js
// ...
importScripts('./polyfill.js')
// ...
```

Webpack builds 2 files `index.js` and `polyfill.js` and in `webpack/lib/JsonpMainTemplatePlugin.js` it uses `window` that fails in the WebWorker when I start Webpack dev. server with HMR.

**What is the expected behavior?**

We should use`self` instead of `window`.

I've already fixed that in my [webpack fork](https://github.com/webschik/webpack/blob/master/lib/JsonpMainTemplatePlugin.js)

**Comment by sokra** [comment]
Did you specify `target: "webworker"`?

**Comment by webschik** [comment]
@sokra , with my current webpack setup it's hard to use multiple targets, but I will try to rewrite the config and `target: "webworker"`

**Comment by webschik** [comment]
@sokra , `target: "webworker"` didn't help.
I've created a repo with a minimal sample of this issue:

https://github.com/webschik/webpack-hmr-worker-bug

**Comment by webschik** [comment]
@sokra , may we fix this issue?

**Comment by coldi** [comment]
+1
I'm also having this issue when bundle an entry for usage with web worker under webpack 3.10.
Was running fine on 3.8 before, since it referenced with `this` instead of `window`.

**Comment by webschik** [comment]
It's similar to https://github.com/webpack/webpack/issues/6642
Current workaround:

```js
// webpack.config.js
output: {
    globalObject: `(typeof self === 'undefined' ? this : self)`
}
```
