### ISSUE TITLE
Unknown argument: save. Why --save doesn't work?

### ISSUE THREAD

**Issue by wzup** [webpack/webpack#6090]
From [here](https://webpack.js.org/api/cli/#watch-options)

> --save, -s | Recompiles on save regardless of changes

In real life:

> Unknown argument: save

My CLI command. Why `--save` doesn't work?

```
NODE_ENV='development' node_modules/.bin/webpack --config webpack.conf.js --debug --progress --display-depth --colors --display-chunks --watch --save
```

**Comment by ooflorent** [comment]
The option has been removed in #3896 but I don't know why.

**Comment by sokra** [comment]
removed from documentation
