### ISSUE TITLE
EnvironmentPlugin Handles Bracket Notation Inconsistently

### ISSUE THREAD

**Issue by PapaStef** [webpack/webpack#6091]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Using bracket notation works when using a string directly (i.e. `process.env['TEST_ENV_VAR']`). It does NOT however work when using a string accessed from an object. See the following example:

```js
const stringMap = { someString: 'TEST_ENV_VAR' }
process.env['TEST_ENV_VAR'] // Variable is defined
process.env[stringMap.someString] // Variable is undefined
```

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Add an env var via configuration named `TEST_ENV_VAR` (any value will work)
2. Try to access that env var from your compiled script using the two methods described above (bracket notation with a string literal and bracket notation with a string accessed as an object property)
3. One should be defined w/ the correct value, one should be undefined

**What is the expected behavior?**
Should be able to use bracket notation using a string accessed from an object property as this is normal Javascript behavior and one of the primary use-cases for using bracket notation at all

**If this is a feature request, what is motivation or use case for changing the behavior?**
N/A

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Using Chrome 62.0.3202.94 (Official Build) (64-bit), Mac OSX Sierra 10.12.6, Node v8.2.1, Webpack v3.4.0

**Comment by TheLarkInn** [comment]
@PapaStef thanks for the report. A few questions: To make sure its still working for you, or you can get the desired behavior, does `process.env[stringmap['someString']]` work?

Also, is there a way you can create a minimal reproducible repository that we can test against? It could greatly improve our ability to test and diagnose the source of the problem locally. Do you have a proposed fix already also?

**Comment by PapaStef** [comment]
@TheLarkInn Let me give that a try! And yes, I'd be glad to put together a small repo. I was messing around with the env plugin itself to see if I could duct tape something together, no luck yet though.

**Comment by PapaStef** [comment]
@TheLarkInn demo repo: https://github.com/PapaStef/webpack-env-plugin-bracket-notation-test/tree/master

**Comment by sokra** [comment]
Only statically analyseable expressions are replaced.
