### ISSUE TITLE
Make output.libraryExport's default behaviour smarter for ES2015 module entry points

### ISSUE THREAD

**Issue by insin** [webpack/webpack#6097]
**Do you want to request a *feature* or report a *bug*?**

A feature, please!

**What is the current behavior?**

As of Webpack 3.0.0, `output.libraryExport` lets you specify what should be exported for a library, which works perfectly well, but it would be nice if it had some smarts for ES2015 modules as its default behaviour.

**If this is a feature request, what is motivation or use case for changing the behavior?**

When using a shared Webpack configuration to bundle multiple libraries written with ES2015 modules, it would be nice if the default behaviour for `libraryExport` was to export the `default` export when present, otherwise export the named exports (I'm not sure if the latter is equivalent to the current default behaviour, but will check later).

This would avoid the need to tweak configuration when switching between `default` and named exports.

For an existing example elsewhere, [this is what Rollup does by default](https://rollupjs.org/#exports).

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Webpack version: 3.10.0
Webpack Team feels: ❤️

**Comment by benwiley4000** [comment]
What do the maintainers think of this one?
