### ISSUE TITLE
More flexible options for `output.filename`

### ISSUE THREAD

**Issue by jaketodaro** [webpack/webpack#6098]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

Specifying output file names is not very flexible.

```
{
    output: {
        filename: '[name].js'
    }
}
```

**If this is a feature request, what is motivation or use case for changing the behavior?**

The current way of specifying output filenames is very limiting. I'm in a situation where (for shitty legacy reasons), I need one of my entry points to always output `[name].js`, but for all other entry points I want to use `[name].min.js` in prod and `[name].js` in dev. I'm not aware of anyway to do this without specifying two webpack configs. It would be great if `output.filename` could accept either a function that is passed the bundle info (`{ hash, name, ... }`) and returns a filename, or a map of entry name to filename pattern.

#### function
```
{
    output: {
        filename: (bundle) => {
            return `${bundle.name}-foo.js`;
        }
    }
}
```

#### map
```
{
    output: {
        filename: {
            entry1: '[name].js`,
            entry2: '[name].min.js`,
            entry3: '[name]-foo.min.js`
    }
}
```

Adding something like this would also allow the use of kebab case names without having to quote your entry names, along with opening up many other opportunities.

```
{
    entry: {
        'this-is-my-bundle-name': 'index.js', // meh
        thisIsMyBundleName: 'index.js`, // nice
    },
    output: {
        filename: (bundle) => {
            return `${_.kebabCase(bundle.name)}.js`;
        }
    }
}
```

I'm happy to contribute if this idea is approved.

**Comment by jaketodaro** [comment]
I suppose I could hack around this with separate entries for dev and prod configs like this, but this seems gross and I have to duplicate entries.

#### dev

```
{
    entry: {
        'always-min.min': 'index.js',
        'sometimes-min': 'other.js'
    output: {
        filename: '[name].js'
    }
}
```

#### prod

```
{
    entry: {
        'always-min': 'index.js',
        'sometimes-min': 'other.js'
    output: {
        filename: '[name].min.js'
    }
}
```

**Comment by sokra** [comment]
Send a PR
