### ISSUE TITLE
configurable sourceURL to avoid chromium cross-origin policy

### ISSUE THREAD

**Issue by githoniel** [webpack/webpack#6099]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
As this [Issue](https://github.com/webpack/webpack-dev-server/issues/1222)  describe, Chrome's native Promise global event `onunhandledrejection` not working in webpack-dev-server when using `eval-source-map`

I found It's because of chromium `cross-origin policy` and it's cause by `souce-map url`

when the Promise reject to the global, the track was
```
    at VueComponent.queryDetail (webpack-internal:///./node_modules/babel-loader/lib/index.js!./node_modules/if-loader/index.js!./node_modules/vue-loader/lib/selector.js?type=script&index=0&bustCache!./node_modules/if-loader/index.js!./helios-view/src/commonPack/biz-detail/view/page/step1.vue:229:50)
```
sourceMap url is `webpack-internal///` but my dev url was `http://localhost:8078`

I found this in webpack source code
```js
//libs/EvalSourceMapDevToolModuleTemplatePlugin.js Line 65
const footer = self.sourceMapComment.replace(/\[url\]/g, `data:application/json;charset=utf-8;base64,${new Buffer(JSON.stringify(sourceMap), "utf8").toString("base64")}`) + //eslint-disable-line
 `\n//# sourceURL=webpack-internal:///${module.id}\n`; // workaround for chrome bug
```
`sourceURL` is fixed and when I modify it to `\n//# sourceURL=http://localhost:8078/webpack-internal///${module.id}\n`. It seem nothing broken and Now I can capture `unhandledrejection` now.
the error track is 
```
    at VueComponent.queryDetail (http://localhost:8078/webpack-internal///./node_modules/babel-loader/lib/index.js!./node_modules/if-loader/index.js!./node_modules/vue-loader/lib/selector.js?type=script&index=0&bustCache!./node_modules/if-loader/index.js!./helios-view/src/commonPack/biz-detail/view/page/step1.vue:229:50)
```

**What is the expected behavior?**
configurable sourceURL to avoid chromium `cross-origin policy`.

**If this is a feature request, what is motivation or use case for changing the behavior?**
To avoid chromium `cross-origin policy` to ignore `unhandledrejection event`

**Comment by sokra** [comment]
Did you report this bug to chrome?

**Comment by githoniel** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=794057#c1

@sokra，It got wont fix....

**Comment by CherryDT** [comment]
I see this issue was closed, but the problem still exists

**Comment by githoniel** [comment]
> I see this issue was closed, but the problem still exists

yes it has been 3 years.

It can be easily fixed by using promise polyfill with `onunhandledrejection` support  if you need to simulate this perfectly

**Comment by CherryDT** [comment]
I'm not sure I understand. Are you saying in order to get a feature to work that works great with native promises as long as the source map URL (which has no function on the code itself anyway) could be slightly adjusted, I should use a non-native, slower, promise implementation? That doesn't sound reasonable to me so I'm not sure I understood correctly.

**Comment by githoniel** [comment]
> I'm not sure I understand. Are you saying in order to get a native feature to work that works great with native promises as long as the source map URL (which has no function on the code itself anyway) could be slightly adjusted, I should use a non-native, slower, promise implementation to simulate both the feature and promises themselves? That doesn't sound reasonable to me so I'm not sure I understood correctly. 

source map make effect only if you open devtool. so it is reasonable. 

adjust the soucemap URL by plugin is not possible in wepack3. maybe it can be done now in webpack5
