### ISSUE TITLE
How to skip requires?

### ISSUE THREAD

**Issue by redonkulus** [webpack/webpack#610]
Is there a way to tell webpack to skip a require from with in a file. Example:

index.js:

```
module.exports = require('foo');

/* skip the one below ???? */
module.exports = require('dont-require-this');
```

**Comment by rogeriochaves** [comment]
@redonkulus which workaround?

**Comment by yeerkkiller1** [comment]
I think you want do use: http://stackoverflow.com/questions/34828722/how-can-i-make-webpack-skip-an-require .

**Comment by ruslanchek** [comment]
What the point of getting solution, tells everyone about it, but leave no explanation aboit it in comments?

**Comment by cirias** [comment]
My package uses engine.io, and it uses `uws` as devDependence. When I do `yarn` it won't install the devDeps. So the code that `require('uws')` in engine.io let the webpack yields `Module not found: Error: Can't resolve 'uws'` every time I build it. And this `require` will never be reached. I think this should be an issue for engine.io. But it will be nice if webpack give me an option to just ignore the require.

**Comment by yvele** [comment]
A good workaround may be using `__non_webpack_require__ `, see https://github.com/webpack/webpack/issues/1021#issuecomment-345870406

**Comment by Skywalker13** [comment]
My workaround : 
```js
const require = module[`require`];
```
Note the use of a template string
