### ISSUE TITLE
Support deep link in library depedency

### ISSUE THREAD

**Issue by mocheng** [webpack/webpack#6103]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Suppose I want to build a library X in bundle file according to https://webpack.js.org/guides/author-libraries/ . The Library X utilize a couple of `lodash` methods, but it doesn't need to bundle `lodash` together, since hosting application should include `lodash` as well. So, library X has `externals` in webpack config as below.
```
   externals: {
     lodash: {
       commonjs: 'lodash',
       commonjs2: 'lodash',
       amd: 'lodash',
       root: '_'
     }
   }
```

The problem is that when library X is to be loaded in UMD way, there should whole `lodash` library loaded at the root (which is `window`) in browser side, even though X and the hosting application only use a couple of functions exported by `lodash`.

When the code reads as below, it tends to only import code of `isFunction` instead of whole `lodash`.
```
import isFunction from 'lodash/isFunction';
```

**What is the expected behavior?**

There should be a way for webpack to support deep link importing from `externals`.

**If this is a feature request, what is motivation or use case for changing the behavior?**

As mentioned above, the use case is to reduce unnecessary bundle of peer dependency libraries.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

N/A

**Comment by sokra** [comment]
``` js
   externals: {
     "lodash/isFunction": {
       commonjs: 'lodash/isFunction',
       commonjs2: 'lodash/isFunction',
       amd: 'lodash/isFunction',
       root: ['_', 'isFunction']
     }
   }
```

**Comment by mocheng** [comment]
@sokra  Thanks for your response.

If config as your suggestion, then in hosting application there should statements like below.
```
window['_ '] = {
  isFunction: require('lodash/isFunction');
}
```

This sort of works, but it is awkward. The hosting application must know which function is needed by dynamic loaded library in advance.

**Comment by sokra** [comment]
Yeah that's the problem with externals... They are disconnected from the application and you have to manage them manually.

**Comment by maciej-gurban** [comment]
@sokra Is there currently any way to configure externals in a way that would only require specifying library to externalise and not all imports from that library?

To follow the above example, if I'm including `lodash/get` and `lodash/map`, I'd only want to specify `lodash` as an external.

**Comment by Pyrolistical** [comment]
I believe you can write a [externals function](https://webpack.js.org/configuration/externals/#function) that will match on `lodash/*` and convert `lodash/a/b/c` to `_.a.b.c`

**Comment by maciej-gurban** [comment]
My solution was simply using a regexp as one of the entries in externals in the end
