### ISSUE TITLE
DefinePlugin not replacing exported tokens when setting Babel preset-env modules to false

### ISSUE THREAD

**Issue by OrenMe** [webpack/webpack#6104]
**Do you want to request a *feature* or report a *bug*?**
No

**What is the current behavior?**
When I set babel-preset-env config with `modules: false` the webpack define plugin doesn't replace my defined tokens
Issue happens when I use the tokens directly in the export declarations.

**If the current behavior is a bug, please provide the steps to reproduce.**
Clone this repo: https://github.com/OrenMe/WebpackDefinePluginIssue and follow the steps to see the issue

**What is the expected behavior?**
Defined tokens are replaced with the values configured in the DefinePlugin options.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Node 0.8.6, webpack 3.6.0, Mac high sierra

**Comment by sokra** [comment]
in `export { XXX }` XXX must be a variable declared in the module. It's not valid ESM to export expressions/defined identifiers.
