### ISSUE TITLE
module cannot be loaded because required buildin/module being included in another bundle

### ISSUE THREAD

**Issue by MhMadHamster** [webpack/webpack#6113]
**Do you want to request a *feature* or report a *bug*?**
I dont know if this is a bug or by design, if by design then it is a request for a feature i guess

**What is the current behavior?**
I am having problems with modules which are being included in bundles by webpack itself, (for different module declaration i believe), they are located in webpack/buildin directory (not all of them tho). In my provided example i have A, B, C, common and vendor bundles, the common bundle is included on all pages while vendor only on page B. Page A and B also have one module which leads to injecting buildin/global and process/browser modules into those page bundles by webpack. I'm using CommonChunkPlugin to extract vendor and common scripts to their bundles. As a result, i'm getting buildin/global included in the vendor bundle, even if i set ```minChunks: Infinity``` , so i don't have control over those "buildin" modules. It leads to the error on page A because i dont have vendor bundle there, but the "buildin/global" module which is required, to load module used in bundle of page A, is requiring "buildin/global".
I wrote before that not all of them are located in webpack/buildin, what i meant is for example module process/browser which is also being included in bundles by webpack and can cause the same problem as "buldin" modules. Those are all, however, examples and there probably more modules like this.
As for example i provided, "common-scripts" created just for example that we might have custom ```minChunks``` there, so we cannot use one CommonChunksPlugin with ```names: []```. Probably first thing that comes to the head is to not specify entries in "chunks" array for CommonChunkPlugin for "vendor-scripts", which are not containing any vendor scripts. I am not considering this as a solution because in my real project i have multiple different vendor scripts which are not always all loading on the same pages, which leads to creating multiple arrays with different sets of entries, and when you have a lot of chunks it drastically lowers maintainability. And i am even not sure if it is going to work.

**If the current behavior is a bug, please provide the steps to reproduce.**
[repo to reproduce](https://github.com/MhMadHamster/webpack-buildin-modules-problem)

**What is the expected behavior?**
I am expecting to all those "buldin" modules to be placed in each module, in which they're needed. Best to be able to specify bundle in which they should be placed. For example i'm having some common bundle and i know it is loading on all pages, so i can say: if some of those "buildin" modules are needed place them in that bundle.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
node.js: v8.3.0
webpack: v3.10.0
os: win10

In addition: i'm not sure if i'm doing something wrong or is it really the case for error, since for me it looks like a common use case, i haven't found any similar issues tho, so it might be just me using webpack or commonchunkplugin wrong way.
Thanks.

**Comment by MhMadHamster** [comment]
I have found a workaround, however, which more look like a hack:
```
minChunks(module) {
  return (
    module.resource &&
    (/process\\browser/.test(module.resource) || /webpack\\buildin/.test(module.resource))
  );
},
```

**Comment by MhMadHamster** [comment]
i would really appreciate any response on this issue. Are you considering this as a bug or this behavior is expected and you wont fix/accept pr with fix for it?

**Comment by sokra** [comment]
vendor-scripts is a parent of a, b and c (see chunks option). You must include the vendor-scripts.js file before including a.js. It's missing in the indexA.html.

Try to run with `--display-entrypoints` to print required output files for each html.

**Comment by MhMadHamster** [comment]
thanks for reply @sokra i do understand that this would fix the error and why it is fixin it, but the point of this issue is that even if vendor-scripts is a parent of "a" but "a" do not contains any modules which are being placed in vendor-scripts it's shouldnt be required to include vendor-scripts on the page, because otherwise you have to specify chunks options for vendor-scripts and this could be really painfull to maintain the config on the big project
