### ISSUE TITLE
Output management guide not showing proper diff for webpack.config.js

### ISSUE THREAD

**Issue by JGJP** [webpack/webpack#6120]
**Do you want to request a *feature* or report a *bug*?**
problem in Documentation > Guides

**What is the current behavior?**
the ["Output Management" guide](https://webpack.js.org/guides/output-management/) is a continuation of the previous ["Asset Management" guide](https://webpack.js.org/guides/asset-management/) but the first modification of webpack.config.js is not showing the proper diff for what should be modified in the file.

Respectively:

![webpack1](https://user-images.githubusercontent.com/3692190/33942247-a4035e64-e058-11e7-818a-88d0f7235d1b.png)

![webpack2](https://user-images.githubusercontent.com/3692190/33942251-a78d60f2-e058-11e7-91d4-a4809d9a5a3e.png)

The passing of an object instead of a string is not indicated. It's not a huge deal, just leads to a few unnecessary errors when trying to build, wondering if I hadn't followed the guide correctly.

**If the current behavior is a bug, please provide the steps to reproduce.**
Follow the guide instructions, changing only what it says to change.

**What is the expected behavior?**
Should show in green the lines that include the entry object brackets.

**Comment by sokra** [comment]
@webpack-bot move to webpack/webpack.js.org
