### ISSUE TITLE
Respect semver when using resolve.modules

### ISSUE THREAD

**Issue by Wildhoney** [webpack/webpack#6121]
```javascript
resolve: {
    modules: [
        path.resolve('node_modules'),
        path.resolve('../shared/node_modules')
    ]
}
```

**Do you want to request a *feature* or report a *bug*?**
Unsure, as I don't know whether it's intentional or not.

**What is the current behavior?**
I setup `resolve.modules` as seen above. When the resolve happens, it only takes into consideration a match based on the package name, but doesn't take into consideration the version of the package.

**If the current behavior is a bug, please provide the steps to reproduce.**
Setup the `resolve.modules` as above with two versions of the same module installed in each of the `node_modules` directories and build.

**What is the expected behavior?**
I'd expect that if `node_modules` had `pkg@1.0.0` installed, but `../shared/node_modules` only supported `pkg@<1.0.0` then it would choose the `pkg` from `../shared/node_modules` rather than `node_modules`, yielding two versions of `pkg` in the final build. If both are able to support a common version of `pkg` then only the one version would be used.

**If this is a feature request, what is motivation or use case for changing the behavior?**
If it's not changed, then shared files are **always** built against the `node_modules` listed first in `resolve.modules`, potentially leaving a broken build at runtime.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

---

I realise there could be a better way to achieve the desired outcome. Using `peerDependencies` doesn't seem to be an option, because the Webpack build still needs to resolve the dependencies.

**Comment by sokra** [comment]
The package manager (npm or yarn) manage versions for you when using the default resolution. Why does the default doesn't work for you?

**Comment by sokra** [comment]
semver is out of scope for webpack. The package manager will handle semver and install packages in the correct locations.
