### ISSUE TITLE
Watch doesn`t work correctly with links

### ISSUE THREAD

**Issue by arshtepe** [webpack/webpack#6122]
**Do you want to request a *feature* or report a *bug*?**
Bug report.

**What is the current behavior?**
When i create link in node_modules and set symlinks to false, I have problem with watch, it works sometimes (more often it doesn`t work)

**If the current behavior is a bug, please provide the steps to reproduce.**
1. create link
2. set symlinks to false
3. change file by link

**What is the expected behavior?**
Watch must work

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

node v8.9.3
npm 5.6.0
Description: Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
4.4.0-83-generic
webpack 3.10.0

**Comment by evilebottnawi** [comment]
@arshtepe webpack version?

**Comment by arshtepe** [comment]
@evilebottnawi Sorry, I forgot. I have edited my comment

**Comment by evilebottnawi** [comment]
@arshtepe please create minimum reproducible test repo, thank you

**Comment by arshtepe** [comment]
@evilebottnawi  I have created repo https://bitbucket.org/CyBer_UA/webpack-demo/src/344771d7d4b403eb662a9c0e7f23aaedc920f0e9?at=master
For reproduce you need:
```npm install 
cd repo/
npm link
cd ..
npm link simple-repo
webpack --watch
```
and after you need change file index.js in repo folder 
from
```js
import test from "src/test";
```
to
```js
import test from "./src/test"; 
```
and after webpack do nothing...

**Comment by sokra** [comment]
@webpack-bot move to webpack/watchpack

@evilebottnawi  I have created repo https://bitbucket.org/CyBer_UA/webpack-demo/src/344771d7d4b403eb662a9c0e7f23aaedc920f0e9?at=master
To reproduce you need:
```npm install 
cd repo/
npm link
cd ..
npm link simple-repo
webpack --watch
```
and after that you need to change file index.js in repo folder 
from
```js
import test from "src/test";
```
to
```js
import test from "./src/test"; 
```
and after webpack do nothing...
