### ISSUE TITLE
Feature to get the entry file name in a loader

### ISSUE THREAD

**Issue by psabharwal123** [webpack/webpack#6124]
**Do you want to request a *feature* or report a *bug*?**
feature 

**What is the current behavior?**
it is not possible to get entry filename  in loader

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
it should be possible to get entry file name in loader

**If this is a feature request, what is motivation or use case for changing the behavior?**
https://github.com/webpack-contrib/file-loader/issues/114
https://github.com/webpack/webpack/issues/2090 (FuriouZz's solution doesnt work)
https://github.com/webpack/webpack/issues/1381

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by sokra** [comment]
This doesn't work for technical reasons. The module could be used in multiple entries. You can use "multiple configurations" if you want to customize loaders per entry.

**Comment by Finesse** [comment]
@sokra But there is an [issuer](https://webpack.js.org/configuration/module#ruleissuer) option that lets apply different loaders for the same file
