### ISSUE TITLE
webpack-dev-server: integrate with Chrome Dev Tools

### ISSUE THREAD

**Issue by DenisIzmaylov** [webpack/webpack#613]
It would be great to build Chrome extension for webpack-dev-server (through HMR?) to allow edit CSS/JS directly in Debugger (with using source-maps of course):
http://tin.cr/

I'm sure it will be the kill-feature! :+1:

**Comment by rafde** [comment]
This may be old, but google will lead here. For those who find this, maybe this helps. 
https://medium.com/@rafaelideleon/webpack-your-chrome-devtools-workspaces-cb9cca8d50da#.em2b88941

The issue I run into atm, involves making a change to a large chunk file with a lot of modules. When those types of files update, Chrome will show a blank screen or crash. I will create an issue regarding how to hopefully handle this.

**Comment by SpaceK33z** [comment]
Closing since the Medium article above it explains devving with Chrome extensions + webpack perfectly. If there are any issues that need fixing, please open an issue on [webpack-dev-server](https://github.com/webpack/webpack-dev-server/issues).
