### ISSUE TITLE
source-map does not work with MinifyPlugin

### ISSUE THREAD

**Issue by ericprud** [webpack/webpack#6131]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Including `devtool: 'source-map'` and `babel-minify-webpack-plugin` gives error:

>  92% chunk asset optimization/tmp/checkouts/linkeddata/t/webpack-source-map-minify-bug/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:276
>         throw new Error(
>         ^
> 
> Error: original.line and original.column are not numbers -- you probably meant to omit the original mapping entirely and only map the generated position. If so, pass null for the original mapping instead of an object with empty or null values.
>     at SourceMapGenerator_validateMapping [as _validateMapping] (/tmp/checkouts/linkeddata/t/webpack-source-map-minify-bug/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:276:15)
> ...

**If the current behavior is a bug, please provide the steps to reproduce.**
The [ericprud/webpack-source-map-minify-bug](https://github.com/ericprud/webpack-source-map-minify-bug) repo has a [package.json](https://github.com/ericprud/webpack-source-map-minify-bug/blob/master/package.json) and a [webpack.config.js](https://github.com/ericprud/webpack-source-map-minify-bug/blob/master/webpack.config.js) which reproduce this bug (tried with node 6.11.3, 7.0.0 and 8.0.0).

    git clone git@github.com:ericprud/webpack-source-map-minify-bug &&
    cd webpack-source-map-minify-bug && npm install &&
    npm run build:browser

Commenting out either of
```
devtool: 'source-map',
plugins: [ new MinifyPlugin({ deadcode: false }) ],
```
in [webpack.config.js](https://github.com/ericprud/webpack-source-map-minify-bug/blob/master/webpack.config.js#L10-L11) results in a successful build.

**What is the expected behavior?**
```
Hash: 19fc963e64c07be61729
Version: webpack 3.10.0
Time: 281ms
                               Asset       Size  Chunks             Chunk Names
webpack-source-map-minify-bug.min.js  797 bytes       0  [emitted]  main
   [0] multi ./index.js 28 bytes {0} [built]
   [1] ./index.js 21 bytes {0} [built]
```

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Tried with node 6.11.3, 7.0.0, 8.0.0 and webpack@3.10.0 on up-to-date Description:	Ubuntu 16.04.3 LTS (xenial).

The may be the source of some of the me-toos on #5931.

**Comment by evilebottnawi** [comment]
Not related to `webpack`. Looks problem in `babel-minify` and/or `babel-minify-webpack-plugin` https://github.com/webpack-contrib/babel-minify-webpack-plugin/issues/68. Thanks!
