### ISSUE TITLE
Invalid mode shows unrelated schema error message 

### ISSUE THREAD

**Issue by statianzo** [webpack/webpack#6135]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

Discovered when @TheLarkInn was streaming:

The reported schema error when specifying an invalid `mode` includes additional messaging unrelated to the setting.

**If the current behavior is a bug, please specify repro steps**

Create a webpack.config.js
```js
const webpack = require('webpack');
const path = require('path');

module.exports = {
  entry: 'src/index',

  output: {
    filename: '[name].bundle.js',
    path: path.resolve(__dirname, 'dist'),
  },

  mode: 'invalid'
};
```

Webpack responds with an error message:

```
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.mode should be one of these:
   "development" | "production" | "none"
   -> Set the value of `require.amd` and `define.amd`.
```

Notice the last line about `require.amd` and `define.amd`

**What is the expected behavior?**

Error message is printed without `-> Set the value of require.amd and define.amd`

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

webpack 4.0.0-alpha.1
Mac OS 10.13.1
Node 8.9.0

**Comment by TheLarkInn** [comment]
Linking #6132

**Comment by sokra** [comment]
Yeah, looks like the `"description"` in the schema is wrong. Do you want to send a PR?

**Comment by statianzo** [comment]
Sure. I can put something together.
