### ISSUE TITLE
Suggesting webpack.config.json

### ISSUE THREAD

**Issue by christianalfoni** [webpack/webpack#6138]
**Do you want to request a *feature* or report a *bug*?**
Not request, but suggest a feature ;-)

**What is the current behavior?**
This suggestion is based on the following tweet from @TheLarkInn : https://twitter.com/TheLarkInn/status/941431327890358272. I think the reason developers get a bit off put by the configuration is simple things like `path.join`, regexps and `new webpack.optimize.somePlugin()`. This is not typical config syntax.

**If the current behavior is a bug, please provide the steps to reproduce.**
N/A

**What is the expected behavior?**
I think Webpack would benefit from having a simplified `webpack.config.json` as default. A limited configuration which is pure json. Take @TheLarkInn example on twitter:

```json
{
  "entry": "./src",
  "output": "./static/index.js",
  "loaders": {
    ".js": "babel-loader"
  }
}
```

This is of course just an example to prove a point, using the following limitations:

- All paths are relative to config path
- `output` has been simplified to a single path with filename
- `module.rules` has been simplified to a loaders map of file endings with loader name
- `mode` is by default "development" unless `NODE_ENV` equlas "production"

**If this is a feature request, what is motivation or use case for changing the behavior?**
Webpack is an amazing tool, I have been using it myself for several years, but it shoves too much functionality on developers from the get go. If developers could start off with a simple config file, to reap the benefits of Webpack instantly it would be less of a jump opting into the the `webpack.config.js` version for more granular control. This is more of a first impression thing than anything else!

The challenge here is to decide on an official simplified format, but yeah... had a moment of inspiration after the tweet, so thought I would start suggesting the approach first :)

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
N/A

**Comment by TheLarkInn** [comment]
Did you know: you can already write webpack.config.json. The feature is already supported!

**Comment by christianalfoni** [comment]
You can? Is this documented somewhere? I think it would benefit to use this approach on the introductory documentation of Webpack :) Happy to suggest a change with a PR on that one!

**Comment by TheLarkInn** [comment]
Pretty darn sure you can specific webpack.json and then point --config towards it

**Comment by mytee306** [comment]
One of the biggest benefits of writing your config file in `json` format is that you may rely on the intellisense provided by your editor, based on your [json schema](https://json-schema.org/)

Reference [json in vscode](https://code.visualstudio.com/docs/languages/json) 

Right now, my editor is not picking any schema for a `webpack.config.json` or `webpack.json`

Does a `json schema` exist for webpack? If not, are any known obstacles that stand in the way of creating a schema?

**Comment by bebraw** [comment]
@mytee306 There's a schema for TypeScript. I wonder if you could derive a JSON Schema from that.

**Comment by mytee306** [comment]
> schema for Typescript 

I suppose you mean a `d.ts` file with type definitions, can you link it please @bebraw

**Comment by bebraw** [comment]
@mytee306 See [@types/webpack](https://www.npmjs.com/package/@types/webpack). It's hosted on DefinitelyTyped. Maybe there's some conversion tool you could use already. I think you might run into troubles with plugins due to the way they are defined.

**Comment by mytee306** [comment]
Thanks, I'd like to give it a try. Perhaps, creating a large enough functioning subset might suffice initially.
