### ISSUE TITLE
 compression-webpack-plugin

### ISSUE THREAD

**Issue by yzgc** [webpack/webpack#6149]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
使用该插件后，打包的文件都带上了后缀，成为了压缩文件，那么怎么上传到服务器呢？

**Comment by evilebottnawi** [comment]
@yzgc please use English
