### ISSUE TITLE
Should I minify node_modules or should I use the minified version provided for deploy on client?

### ISSUE THREAD

**Issue by bitplanets** [webpack/webpack#615]
I recently moved to webpack from require.js and some node_module have .min files built in. When I use a file from node_module I just do `require('my-module')` and it loads it right away without any config. But this will load the development version or a bigger version. 

For example react is loaded `require('react/addons')` but this is not the minified version. 

My question is:

 - Should I load modules normally and then minify everything?
 - Should I use their .min files provided and then minify everything again? (in this way I save a lot of disk)
 - Any better way? Would be nice to automatically loade minified files.

For now, I'm changing the aliases of webpack to load the minified version when building the app:

    myConfig.resolve.alias.phaserUnFixed = "nodeModules/phaser/build/custom/phaser-no-physics.min.js";
    myConfig.resolve.alias.react = "nodeModules/react/dist/react-with-addons.min.js";
    myConfig.resolve.alias.lodash = "nodeModules/lodash/dist/lodash.compat.min.js";
    myConfig.resolve.alias.moment = "nodeModules/moment/min/moment.min.js";

But this is not a good approach either... Can you think of anything better?

**Comment by luckylooke** [comment]
Webpack have some problem with Phaser library on ubuntu see:  https://github.com/the-simian/slush-phaser-webpack/issues/2
Seems to be related to this issue, but I could not help with this thread either.

**Comment by srcspider** [comment]
> Why do you use `JSON.stringify("production")` instead of `"production"`?

`"production"` produces the value `production` 
`JSON.stringify("production")` produces the value `"production"`

Essentially it's converting the string to evaluate-able piece of javascript coce.

It's probably much clearer and shorter to just write `'"production"'`

**Comment by bebraw** [comment]
@bitplanets Safe to close?

**Comment by alltom** [comment]
`UglifyJsPlugin` used to make my source code several megabytes bigger too, but then I read the docs and found that it generates source maps by default. If I invoke it with that option disabled, the minified version is as small as I expected:

    new webpack.optimize.UglifyJsPlugin({sourceMap: false})

**Comment by srcspider** [comment]
@alltom just extract the source maps to a separate file and it's fix'ed with out any negative consequences.

**Comment by wayofthefuture** [comment]
Will Webpack automatically include requires from node modules for minification? Or do I have to explicitly set to minify the node module references?
