### ISSUE TITLE
Webpack Plugin: run command after assets are written to file system

### ISSUE THREAD

**Issue by joha91** [webpack/webpack#6159]
**Do you want to request a *feature* or report a *bug*?**

This is a Bug

**What is the current behavior?**

I created a very basic Plugin like

```javascript
 Testplugin.prototype.apply = function(compiler) {

    compiler.plugin('after-emit', function(compilation, callback) {
        console.log("Files Emiited")
        runGulpTaskToCopyFiles()
        callback();
    });
 };
```

Now in the first comilation process, the "after-emit" event is fired before my bundled files are written to the filesystem. This will cause, that my task to move the files to another location, doesn´t get all files.  
  

**What is the expected behavior?**

I would expect that the event is thrown when all my compiled files exists on the filesystem.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

- I´m running in the webpack watch mode
- The failure only occurs on the first comilation. After the first comilation, when webpack doesn´t create all files over new, they are already adjusted when the "after-emit" event hook is thrown.
- I also tested it with the "done" event --> same result
- I´m using Webpack 3.5.5, but already tested it with 3.10.0 with the same result
- Node Version: 6.10.2
- There is already an existing [stackoverflow article](https://stackoverflow.com/questions/40130961/webpack-plugin-run-command-after-assets-are-written-to-file-system) without any response

_Edit:_
- You can check this plugin ( https://github.com/1337programming/webpack-shell-plugin ) it also has the same problem with it´s basic configuration 
```javascript
new WebpackShellPlugin({onBuildStart:['echo "Webpack Start"'], onBuildEnd:['echo "Webpack End"']})
```
"Webpack End" is printed out before all files are in the output folder

**Comment by sokra** [comment]
I wonder why this is the case. after-emit is called in the callback of `fs.writeFile`...

Could you try to upgrade your node.js version?

**Comment by joha91** [comment]
I upgraded node to 8.9.3 now.     
Same problem !     
It´s easier to reproduce if you have many/big files to compile

**Comment by jaywcjlove** [comment]
`fs.writeFile` lead to repeated compilation. `after-resolvers write` a file, introduced.
@sokra

**Comment by Aqours** [comment]
I encounter the same issue. I want to use gulp to handle the file outputed by webpack.

**Comment by Hoten** [comment]
This is still an issue.

**Comment by ZebraFlesh** [comment]
This is a big pain for SSR where you want to build the client files, emit a stats.json file, and then consume that stats.json file in a server webpack configuration.

**Comment by evilebottnawi** [comment]
@ZebraFlesh can you describe use case more verbosely? Do you want write `stats.json` in watch mode or when you use `webpack-dev-server`?

**Comment by ZebraFlesh** [comment]
I want to write `stats.json` using `webpack-dev-server`. I'm using [serverless-react-boilerplate](https://github.com/arabold/serverless-react-boilerplate) as a starting point.

When I do an `npm start` from that project, it runs the script `sls offline start --exec \"webpack-dev-server --config webpack.client.config.js --mode development\"`. Even when adding a `writeToDisk: true` config to the `devServer` portion of `webpack.client.config.js`, the `webpack.server.config.js` often warns about the missing `stats.json` file. That file is generated [by the webpack-stats-plugin from the compiler `emit` hook](https://github.com/FormidableLabs/webpack-stats-plugin/blob/master/lib/stats-writer-plugin.js#L62). Using `devServer.writeToDisk` shows that the `stats.json` file always lands on disk, but only sometimes before it's needed.

webpack: 4.29.0
npm: 6.4.1
node: 10.15.0
OS: Windows 10

**Comment by ZebraFlesh** [comment]
Yes, the problem I described still occurs as described. I have some private forks that are using the latest versions and it definitely occurs on Windows (which I know, has a very brain dead file system compared to POSIX systems).

**Comment by evilebottnawi** [comment]
@ZebraFlesh Can you create minimum reproducible test repo with small description in README (what you actually have and what you you expected) + os/node versions

**Comment by ZebraFlesh** [comment]
The most minimal reproduction I have is [what I described above](https://github.com/webpack/webpack/issues/6159#issuecomment-457577876).

**Comment by evilebottnawi** [comment]
Thanks

**Comment by evilebottnawi** [comment]
@ZebraFlesh I can't reproduce your problems, anyway i think better use `afterEmit` for this plugin instead `emit` hook, because other plugins can emit files on `emit` hook and it is possible to lose some assets

**Comment by alvinlee001** [comment]
does anyone still face this issue? Generating a file in assets folder after assets is completed seems impossible yet.
