### ISSUE TITLE
Find and replace referenced to modules error.  modulesWithInfo not find referencedModule

### ISSUE THREAD

**Issue by QuietWind** [webpack/webpack#6168]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
```
TypeError: Cannot read property 'type' of undefined
    at getFinalName (XXX/node_modules/webpack/lib/optimize/ConcatenatedModule.js:51:13)
    at info.globalScope.through.forEach.reference (XXX/node_modules/webpack/lib/optimize/ConcatenatedModule.js:582:25)
    at Array.forEach (native)
    at modulesWithInfo.forEach.info (XXX/node_modules/webpack/lib/optimize/ConcatenatedModule.js:569:30)
    at Array.forEach (native)
    at ConcatenatedModule.source (XXX/node_modules/webpack/lib/optimize/ConcatenatedModule.js:567:19)
    at ModuleTemplate.render (XXX/node_modules/webpack/lib/ModuleTemplate.js:14:31)
    at XXX/node_modules/webpack/lib/Template.js:116:28
    at Function.from (native)
    at Chunk.mapModules (XXX/node_modules/webpack/lib/Chunk.js:163:16)
```

**If the current behavior is a bug, please provide the steps to reproduce.**
// Find and replace referenced to modules
https://github.com/webpack/webpack/blob/c26d1f0d226ee9aa940211fa1b3822de7d09f4d5/lib/optimize/ConcatenatedModule.js#L573

referencedModule maybe is `undefined`

**What is the expected behavior?**
if the config is an error, will log reason of error.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by EugeneHlushko** [comment]
Hello @QuietWind 
I am not able to reproduce the error, can you provide steps to reproduce?

**Comment by QuietWind** [comment]
```
function addEntry(compilation, context, name, entry) {
	return new Promise((resolve, reject) => {
		const dep = DynamicEntryPlugin.createDependency(entry, name);
		compilation.addEntry(context, dep, name, err => {
			if (err) return reject(err);
			resolve();
		});
	});
}

compiler.plugin("make", function(compilation, done) {
		invalidator.startBuilding();
		const allEntries = Object.keys(compilerEntryInfo).map(page => {
			const { name, entry } = compilerEntryInfo[page];
			compilerEntryInfo[page].status = BUILDING;
			return addEntry(compilation, process.cwd(), name, entry);
		});

		Promise.all(allEntries)
			.then(() => done())
			.catch(done);
	});

	compiler.plugin("done", function() {
		// Call all the doneCallbacks
		Object.keys(compilerEntryInfo).forEach(page => {
			const entryInfo = compilerEntryInfo[page];
			if (entryInfo.status !== BUILDING) return;
			entryInfo.status = BUILT;
			compilerEntryInfo[page].lastActiveTime = Date.now();
			doneCallbacks.emit(page);
		});

		invalidator.doneBuilding();
	});
```
I learn next.js build code that add entry file only use it,  and my code has this error.

**Comment by EugeneHlushko** [comment]
Still not able to reproduce locally but will this suffice @sokra ?
https://github.com/webpack/webpack/blob/c26d1f0d226ee9aa940211fa1b3822de7d09f4d5/lib/optimize/ConcatenatedModule.js#L573

```
const referencedModule = modulesWithInfo[+match[1]];
if (!referencedModule)
  return;
```

**Comment by sokra** [comment]
@EugeneHlushko this is not a valid fix. The problem is deeper, but not sure exactly.

@QuietWind Could you create a repro repo?

**Comment by QuietWind** [comment]
@sokra this problem is accidental，  I cannot create demo repro.

**Comment by sokra** [comment]
@QuietWind 

Are you using the latest webpack version?

Are you using any custom plugins?

**Comment by QuietWind** [comment]
version: webpack@3.10.0
plugins: dll-link-webpack-plugin@1.0.4

@sokra

**Comment by arekstryjski** [comment]
I got the same error after code refactoring (React components renaming) when I had circular-dependency-plugin [https://www.npmjs.com/package/circular-dependency-plugin] switched on.
My version of webpack is 3.10.0.

**Comment by QuietWind** [comment]
my webpack version :  "version": "3.10.0"

**Comment by pascalduez** [comment]
Hi,

were are seeing those errors quite often since we ran some updates on our stack.
I suspect the fact that we are now using `{ modules: false }` for our `babel-preset-env` config. While we previously was using the default `'commonjs'`.

**Comment by QuietWind** [comment]
often the happen this problem！so crazy。。。。

**Comment by gitlab-winnie** [comment]
This is our current config: https://gitlab.com/gitlab-org/gitlab-ce/blob/a28045124f33c67068246df91d9c0ca17c3ad035/config/webpack.config.js

With webpack 3.11.0: https://gitlab.com/gitlab-org/gitlab-ce/blob/a28045124f33c67068246df91d9c0ca17c3ad035/yarn.lock#L8778

**Comment by gitlab-winnie** [comment]
To me it looks like disabling Hot Module Replacement significantly reduces this error.

**Comment by ooflorent** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.
