### ISSUE TITLE
bug - Object prototype may only be an Object or null: undefined

### ISSUE THREAD

**Issue by minatonda** [webpack/webpack#6171]
**Do you want to request a *feature* or report a *bug*?**
- Bug

**What is the current behavior?**
- I'm having a problem with inherited class.
- Object prototype may only be an Object or null: undefined

**If the current behavior is a bug, please provide the steps to reproduce.**

consider i have : 
many ***.factory.ts** files, that inherit from a **base.factory.ts** (i dont have a circular dependency).

and, i a have many components (vue js), divided as : **commom components** (reusable), and **page components** (route components).

when i call a ***.factory.ts** in a **common component**, that i have called in a **page component**, the application crash on runtime. (webpack doesn't emmit an compilation error, only the web console emit that error).

i'm using awesome-typescript-loader,

**What is the expected behavior?**
The application should not crash.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Chrome 63.0.3239.108,
Linux POP OS (Ubuntu)

Node 6.11.4

Webpack 3.10.0,

![image](https://user-images.githubusercontent.com/14216484/34265617-8f4ace2a-e65d-11e7-81c9-eb258188f98b.png)

![image](https://user-images.githubusercontent.com/14216484/34265685-cbf63a62-e65d-11e7-83ff-3bde726fc3cb.png)

![image](https://user-images.githubusercontent.com/14216484/34265771-153421b2-e65e-11e7-9e94-b23f2afe91f0.png)

can anyone help me ?

thanks.

**Comment by EugeneHlushko** [comment]
I could look if you set up a small repo with problem isolated @minatonda

**Comment by sokra** [comment]
> i dont have a circular dependency

Are you sure? This looks like one.

**Comment by minatonda** [comment]
I looked again at the code, and found a circular reference, which was like this:

factory -> service
factory -> component
service -> component

the webpack can not manage this?

**Comment by sokra** [comment]
> the webpack can not manage this?

It handles this correctly according to the spec.

ES-class are not hoisted so they don't like circular dependencies that much...

**Comment by engelchrisi** [comment]
10 points. I also fixed it by removing a circular import.
