### ISSUE TITLE
Public Path add js variable support

### ISSUE THREAD

**Issue by LingYanSi** [webpack/webpack#6178]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
Public Path donot support  js variable

**If the current behavior is a bug, please provide the steps to reproduce.**
not a bug

**What is the expected behavior?**
I want publicPath support js variable.
like this
```js
output: {
    publicPathVar: 'window.webpackPublicPath'
},
```

**If this is a feature request, what is motivation or use case for changing the behavior?**

In some cases, js file host is based on the user or the current domain name decision. Therefore, dymanic publicPath is needed.

```
window.webpackPublicPath = window.userinfo.id > 0 ? '//cdn.js.com' : '//dev.js.com'
```

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
not a bug

**Comment by sokra** [comment]
`__webpack_public_path__` is writable from inside the bundle.

**Comment by jokeewu** [comment]
})();
![image](https://user-images.githubusercontent.com/5811682/48886062-7cefd480-ee65-11e8-9266-6837c5b51985.png)
why??
