### ISSUE TITLE
feat: add `--babel` option

### ISSUE THREAD

**Issue by AndersDJohnson** [webpack/webpack#6182]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

Using future syntax in webpack configuration files requires the use of a `.babel.js` extension or running webpack with `babel-node`.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

It would be nice to support an option to use Babel syntax without needing a specific file extension, e.g., with a `--babel` CLI flag. Eventually, this could become the default.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by sokra** [comment]
@webpack-bot move to webpack/webpack-cli
