### ISSUE TITLE
CommonsChunkPlugin should not move runtime by default

### ISSUE THREAD

**Issue by sokra** [webpack/webpack#6195]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
CCP moves runtime into CC.

**What is the expected behavior?**
CCP should leave runtime in the original chunk.
CCP should have a `runtime: true` option to move runtime into new chunk.

**If this is a feature request, what is motivation or use case for changing the behavior?**
CC should change only when content changes. Since `app` chunk changes more frequencially, it should contain the runtime by default.
When using a manifest chunks you can use the `runtime` option.

**Comment by Kovensky** [comment]
IIUC it was a necessary side-effect on webpack < 4 because of the lack of out-of-order loading support.
