### ISSUE TITLE
feature: document aternative way to build CSS in isolation and not with CSS imports from JS

### ISSUE THREAD

**Issue by MagicPoulp** [webpack/webpack#6197]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

The documentation of webpack explains only one method for loading CSS, the one with CSS import from Javascript.
https://webpack.js.org/guides/asset-management/#loading-css

As discussed here,
https://www.sitepoint.com/community/t/webpack-what-do-you-think-of-this-way-building-css-and-javascript-separately/284349
there is another method. Not worse or better. It depends of what one prefers.

I would like to resolve this issue by documenting in short the existence of another method. This issue is about updating the documentation.

The other method:
It is possible to build CSS in isolation, without CSS imports from Javascript, with the benefits of:
- faster build time with the potential to parallelize more with parallel-webpack, because Javascript does not need to be parsed to parse the SASS/CSS.
- following the SASS tradition (see link above)
- separate configs (hard to understand but no source-maps in ES6 Javascript, while keeping source-maps for SASS wins me 2s build time), and 

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

Document in short that there is another method. Here is a suggestion. It must be short because people will have a hard time to agree. Or small details may not be supported (like using a dummy js file with an import to the global css file). Forget the details. Just say to people it is possible.

**Suggestion:
"Although it is not the official way, it is possible to bundle CSS in isolation without CSS imports from Javascript. It can be useful to speed up the build with parallel-webpack, or to follow the tradition of CSS."**

**If this is a feature request, what is motivation or use case for changing the behavior?**

1. It can be very useful for people to know there is another way. I regret I could not find it there in the first place.
2. The webpack community may see a new way, and the update of this documentation may raise new ideas for webpack to speed up build time in a simple way.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by sokra** [comment]
One of webpacks core concepts is the idea of **one** dependency graph with all modules (js + css). Building CSS in isolation sounds like a step backwards to me. I won't recommend this as official way.

In addition to this, it's weird to use webpack when building SASS in isolation. In this case just to a task runner to build sass i. e. gulp...

**Comment by MagicPoulp** [comment]
> One of webpacks core concepts is the idea of one dependency graph with all modules (js + css). Building CSS in isolation sounds like a step backwards to me. I won't recommend this as official way.

Fine. Just curious: is it possible to parallelize builds, as parallel-webpack does, with all modules loaded together? How can it work in parallel since Javascript needs to import CSS from many files?

> In addition to this, it's weird to use webpack when building SASS in isolation. In this case just to a task runner to build sass i. e. gulp...

When building SASS in isolation, it is simpler to use webpack for all builds. Otherwise, one needs to download gulp and to learn gulp.

**Comment by MagicPoulp** [comment]
I am curious to know if you can parallelize and speed up the build as much when using the official way. See question in previous post.
