### ISSUE TITLE
[next] add run and watchRun hook to MultiCompiler

### ISSUE THREAD

**Issue by sokra** [webpack/webpack#6205]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
run and watchRun doesn't exist

**What is the expected behavior?**
run and watchRun hooks should exist. run and watchRun should be forwarded from child compilers.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Compatibility with webpack-dev-middleware

#6179

**Comment by ooflorent** [comment]
I'd like to tackle this one but I'm not sure how I should do it.

1. Using a `SyncHook` (or `AsyncSeriesHook`) and forward the call? My main concern here is that the hook will be called for each child compiler.
    ```js
    compiler.hooks.run.tap("MultiCompiler", compilation => {
      this.hooks.run.call(compilation);
    });
    ```
2. Using `compiler.hooks.run.intercept({tap: …})` to hook into the child compiler

Could you give me some hint? cc @sokra @TheLarkInn

**Comment by sokra** [comment]
1.

Yep it will be called multiple times when multiple children run.
