### ISSUE TITLE
Warning when using webpack/hot/signal

### ISSUE THREAD

**Issue by brunoabreu** [webpack/webpack#6206]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When using `bluebird` as global promise implementation and `webpack/hot/signal`, I always get this warning when doing hot module replacement:
```
16:36:30.822 - [HMR] Updated modules:
16:36:30.866 - [HMR]  - ./node/index.ts
16:36:30.867 - (node:52) Warning: a promise was created in a handler at usr/local/app/service/index.js:843:5 but was not returned from it, see http://goo.gl/rRqMUw
    at Function.Promise.cast (/usr/local/app/service/index.js:18356:13)
16:36:30.872 - [HMR] Update applied.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Just use `bluebird` as global promise implementation, enable warnings and do HMR using `webpack/hot/signal`: 

```
const bluebird = require('bluebird')
global.Promise = bluebird
bluebird.config({warnings: true})
```

**What is the expected behavior?**

There should be no warnings.

The warning is pointing to this [line of code](../blob/master/hot/signal.js#L26) and according to [this bluebird doc](http://bluebirdjs.com/docs/warning-explanations.html#warning-a-promise-was-created-in-a-handler-but-was-not-returned-from-it) can be easily fixed by returning null after that `checkUpdate(true);`

**If this is a feature request, what is motivation or use case for changing the behavior?**
N/A

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

*OS*: Alpine Linux
*webpack*: 3.8.1
*node*: 8.9.3

**Comment by sokra** [comment]
Send a PR
