### ISSUE TITLE
devtool: "source-map" how to pass publicPath option?

### ISSUE THREAD

**Issue by sarkiroka** [webpack/webpack#6216]
**Do you want to request a *feature* or report a *bug*?**
I don't know

**What is the current behavior?**
I try to use both of devtool: "source-map" option and this plugin: https://webpack.js.org/plugins/source-map-dev-tool-plugin/
But I cannot found a way to pass publicPath to sourceMap plugin when it defined in devtool.
When I use only the plugin:
```
	plugins: [
		new webpack.SourceMapDevToolPlugin({
			filename: '[file].map',
			publicPath: 'https://example.com/project/'
		}),
...
```
then it generated as well in javascript file, but the sourcemap file is empty:
`{"version":3,"sources":[],"names":[],"mappings":"","file":"project.js","sourceRoot":""}`

When I use only the devtools option, the sourcemap generated well, but I cannot set publicPath.
I want to set sourcemap to external server.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
for example in output options I can specify the sourcemap publicPath option

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
node: 8.9.0
webpack 3.10.0
os: linux

**Comment by sokra** [comment]
You can't pass it with `devtool`, use the plugin instead.

**Comment by sokra** [comment]
also pass `sourceMap: true` to the UglifyJsPlugin.

**Comment by evilebottnawi** [comment]
Docs was updated https://webpack.js.org/plugins/source-map-dev-tool-plugin/ , see `publicPath`
