### ISSUE TITLE
Unused harmony exports are exported in v4.0.0-alpha.2

### ISSUE THREAD

**Issue by blikblum** [webpack/webpack#6221]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Unused harmony exports are exported in v4.0.0-alpha.2 (in v3.10 they are not exported).

**If the current behavior is a bug, please provide the steps to reproduce.**

* Install v4.0.0-alpha.2
* A minimal webpack.config:

```
var path = require('path')

module.exports = {
  entry: './test.js',
  output: {
    filename: 'bundle.js',
    path: path.resolve(__dirname, 'dist')
  }
}
```

* A module (my-module.js) that exports two objects:
```
var View = {name: 'view'}

var CollectionView = {name: 'collectionview'}

export {
	View, CollectionView
}
```
* An entry (test.js) importing only one object
```
import {View} from './my-module'

var v = View.name
```
It will output the following code:

```
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "View", function() { return View; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "CollectionView", function() { return CollectionView; });
```

**What is the expected behavior?**

It should not export the unused export (CollectionView) like v3.10 does

v3.10 output:
```
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "a", function() { return View; });
/* unused harmony export CollectionView */

```

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Node v8.x, webpack 4.0.0-alpha.2

**Comment by sokra** [comment]
Did you run in production mode?

**Comment by blikblum** [comment]
No, the script just runs `webpack --display=verbose` with the above config.

Since i'd like to evaluate the output code, production mode would obfuscate being harder to see the generated code.

One thing that i noticed is that v3 logs that only View export is being used (`[only some exports used: View]`), while v4 does not logs that info:

v3 log:
```bash
chunk    {0} bundle.js, bundle.js.map (main) 167 bytes [entry] [rendered]
    > main [0] ./test.js
    [0] ./test.js 55 bytes {0} [depth 0] [built]
        [no exports]
    [1] ./my-module.js 112 bytes {0} [depth 1] [built]
        [exports: View, CollectionView]
        [only some exports used: View]
        harmony import ./my-module [0] ./testshaking.js 1:0-35
```
v4 log:
```
chunk    {0} bundle.js (main) 171 bytes [entry] [rendered]
    > main [0] ./test.js
    [0] ./test.js 59 bytes {0} [depth 0] [built]
        [no exports]
        single entry ./test.js  main
    [1] ./my-module.js 112 bytes {0} [depth 1] [built]
        [exports: View, CollectionView]
        harmony side effect evaluation ./my-module [0] ./testshaking.js 1:0-32
        harmony import specifier ./my-module [0] ./testshaking.js 3:8-12
```

**Comment by sokra** [comment]
It only does that optimization in production mode. What's your `mode` setting?

**Comment by blikblum** [comment]
> What's your mode setting?

I did not configured `mode`

The configuration that i know is putting in the config the following options
```
 optimization: {
   minimize: true,
   concatenateModules: true
  }
```
If i use `concatenateModules`, nothing is exported (as per design)

> It only does that optimization in production mode

Is there any optimization flag that would enable this feature without `concatenateModules`?

**Comment by sokra** [comment]
yep, just use `mode: "production"` and omit all the `optimization` stuff.

It actually should give you a warning when omitting the `mode` option.

**Comment by blikblum** [comment]
By setting `mode: "production"` the modules are concatenated, so there's no reason to have a export at all. 

While still not the output i was looking (non concatenated module without exporting unused modules - like v3),  `mode: "production"` removes the unused export from the bundle which, in the end, is the desired effect.

From my mind there's a potential issue  when module concatenation bailouts in `mode: "production"`. It will export unused modules? Since is a corner case and i don't know how to test, i will be closing this issue for now.

@sokra  thanks for the feedback

**Comment by sokra** [comment]
There is also `optimization.usedExports: true`, if you want to try unused export elimination on it's own.
