### ISSUE TITLE
impossible to debug based on logs when adding plugins TypeError: arguments[i].apply is not a function

### ISSUE THREAD

**Issue by Kielan** [webpack/webpack#6223]
**Do you want to request a *feature* or report a *bug*?**
This is a bug because there is no documentation and related issues are "old" and not being actively resolved.

**What is the current behavior?**
Whenever I add a plugin such as the chunk below should throw no error. but throws a cryptic message `TypeError: arguments[i].apply is not a function`in webpack 3 and similar in webpack4. There should be more explanation of what is wrong regarding adding plugins

```
module.exports = {
  module: {
    rules: [
      {
        test: /\.(css|scss)$/,      // also tried...:      /\.scss$/,
//        exclude: /node_modules/,
//        use: ['style-loader','css-loader', 'sass-loader']
        use: ExtractTextPlugin.extract({
          fallback: "style-loader",
          use: ['css-loader', 'sass-loader']
        })
    },
    plugins: [
      new ExtractTextPlugin("styles.css"),
    ],
  ]

```
**If the current behavior is a bug, please provide the steps to reproduce.**
I provide a related issue with the dependency where the maintainer seems to be struggling as well
https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/681

here is a stale issue/pr:
https://github.com/webpack/webpack/pull/6008

another related pr with no explanation to the solution
https://github.com/stryker-mutator/stryker-karma-runner/issues/20

and here is a project to reproduce the issue
https://github.com/Kielan/testWebpackErr

**What is the expected behavior?**
I expect webpack to not break when I add plugins or provide some documentation to resolve this issue, even on version 4 there is no documented solution.

**If this is a feature request, what is motivation or use case for changing the behavior?**
please let me know what I can do to help.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
webpack 3 and 4

**Comment by ooflorent** [comment]
ˋplugins` should be defined at root level. Not into ˋmoduleˋ.

**Comment by Kielan** [comment]
`
var plugins = [
  new webpack.DefinePlugin({
    'process.env': {
      'ENV': JSON.stringify(process.env.ENV),
    }
  })
]
const WebpackRecipe = deepmerge({
  cache: false,
  devtool: '',
  entry: entry,
  module: {
    loaders: loaders
  },
  output: {
    path: path.join(process.cwd(), 'public'),
    publicPath: '/',//publicPath, //isProduction was just /
    chunkFilename: 'js/[name].js',
    filename: 'js/[name].js',
  },
  plugins: plugins,
}, webpackCommonConfig);`

@ooflorent no difference

**Comment by Kielan** [comment]
The problem I have found is with the deepmerge package which does not support new webpack types. I recommend using webpack-merge which solved using functions. Using deepmerge dependency will break on plugins in latest webpack.
