### ISSUE TITLE
error reading webpack.config.ts when node_modules is in parent folder

### ISSUE THREAD

**Issue by Gullfaxi171** [webpack/webpack#6230]
**Do you want to request a *feature* or report a *bug*?**
A bug

**What is the current behavior?**
my webpack.config.ts (the extension is ts, not js) starts with:
```ts
import * as webpack from 'webpack'
```
Building my project works perfectly when webpack.config.ts is in the same folder than node_modules (which contains ts-node and webpack as devDependencies)

However when the *node_modules* folder is in a parent folder, I get

```
SyntaxError: Unexpected token import
```

**If the current behavior is a bug, please provide the steps to reproduce.**

create webpack.config.ts starting with:
```ts
import * as webpack from 'webpack'
```
create a package.json and 
```ts
npm install -D ts-node webpack
```
now try to build, it should work
then, move node_modules and package.json in parent folder -> it shouldn't work anymore

**What is the expected behavior?**
I believe normal behavior should be using package.json and node_modules of parent folder (recursively, if parent has none too) when there is none in the same folder that webpack.config.ts ; since it is the normal behavior for calling node_modules packages

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
node 9.3.0
webpack 3.10.0
windows 10.0.16299.125

**Comment by sokra** [comment]
@webpack-bot move to webpack/webpack-cli
