### ISSUE TITLE
adding alias by webpack cli

### ISSUE THREAD

**Issue by amorenew** [webpack/webpack#6232]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
I Manually add alias to webpack 
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
I can add alias from  package.json by script using webpack cli
**If this is a feature request, what is motivation or use case for changing the behavior?**
https://stackoverflow.com/questions/48057127/add-alias-to-webpack-config-by-npm-script
**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by sokra** [comment]
webpack allows to configure `resolve.alias`. It's create-react-app that hides this configuration. You should report it there, but I guess they won't add this.
