### ISSUE TITLE
Import typescript file from another folder with another configuration

### ISSUE THREAD

**Issue by karaxuna** [webpack/webpack#6233]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**
Suppose we have following folder structure:

    /folderA
        indexA.ts
        webpackA.config.js
    /folderB
        indexB.ts
        webpackB.config.js

In both folders I have different webpack configurations. What if I want to import `folderA/index.ts` from `folderB/index.ts`? Something like this:

    import '../folderA/indexA?config=webpackA.config.js';

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by sokra** [comment]
A webpack configurations describes a "build" not the "import". What's the motivation for this?

**Comment by karaxuna** [comment]
@sokra I have core module written with typescript, also I have 2 more modules written with typescript that should use core module, but with different configuration, one is react native and second is web. I know I can build core and then import js and use typescript definition file, but that's not comfortable when in development mode.

**Comment by sokra** [comment]
Why do you need a separate webpack configuration for importing the core. Just import it.

**Comment by karaxuna** [comment]
@sokra I want core to be isolated, with different aliases.

**Comment by sokra** [comment]
hmmm... that doesn't work. Maybe you can have multiple tsconfig files, I don't know. But you can't have multiple webpack configs in one build.
