### ISSUE TITLE
[Refactor] - Move dirTimestamps to Set to prevent deopts

### ISSUE THREAD

**Issue by TheLarkInn** [webpack/webpack#6234]
This is a good contribution opportunity. See [this PR comment](https://github.com/webpack/webpack/pull/6229#pullrequestreview-86355358) 

We can move the dirTimestamps to a Set for better performance. Please followup if you have any questions or need direction on this. 

Tagging @ooflorent whom can also assist.

**Comment by rowdown** [comment]
I like to help out here.

**Comment by neeharv** [comment]
@TheLarkInn I'll tackle this, is there a way I can benchmark any perf improvement with this?

**Comment by ooflorent** [comment]
@neeharv I usually measure perfs by bundling webpack itself or using ˋyarn link webpack` inside a huge project.

**Comment by neeharv** [comment]
@ooflorent Thanks! I'll try that out. I'm thinking of editing `NodeWatchFileSystem` to convert the times object from Watchpack to a Map. Does that seem like the right approach?

**Comment by TheLarkInn** [comment]
I believe so!

**Comment by TheLarkInn** [comment]
However feel free and profile the differences in execution.

**Comment by probablyup** [comment]
This can be closed now 👌

**Comment by TheLarkInn** [comment]
Thanks!
