### ISSUE TITLE
require-ensure should not include initial chunks

### ISSUE THREAD

**Issue by nename0** [webpack/webpack#6239]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When the `require-ensure` / `__webpack_require__.e` method is generated for the runtime code it includes initial chunks. I think this is wrong because of two reasons:
1. When a [chunk is mapped to a filename](https://github.com/webpack/webpack/blob/9a0da7bcf3e082b4babefd0974a7ce9fe375ffcc/lib/Compilation.js#L1374), it gets`chunk.isInitial() ? outputOptions.filename :
outputOptions.chunkFilename`. 
However when the filename is generated in the `assets-path` for the `require-ensure` method [only the `chunkFilename` is used
](https://github.com/webpack/webpack/blob/9a0da7bcf3e082b4babefd0974a7ce9fe375ffcc/lib/JsonpMainTemplatePlugin.js#L28)  This will create an invalid `assets-path` in the webpack runtime code. (see reproduce)
2. Initial chunk don't need to be loaded dynamicly. At least form a bit of testing it seems that when initial chunks are loaded dynamic, the `__webpack_require__.e` gets replaced with `new Promise(function(resolve) { resolve(); })`

**If the current behavior is a bug, please provide the steps to reproduce.**
This will generate a invalid `assets-path`:
<details>
 <summary>webpack.config.js</summary>

```js
const webpack = require('webpack');
module.exports = {
    entry: {
        a: './a.js'
    },
    output: {
        filename: '[name].[chunkHash].bundle.js'
    },
    plugins: [
        new webpack.optimize.CommonsChunkPlugin({
            name: ['manifest'],
            minChunks: Infinity,
        }),
    ]
};
```
</details>

`a.js` is an empty file.
This will generate two files: `mainfest.<somehash>.js` and `a.<somehash>.js`.
Inside the mainfest file will be this line:
```
script.src = __webpack_require__.p + "" + chunkId + "." + {"0":"<somehash>"}[chunkId] + ".bundle.js"; 
```
This is wrong because there is no file `0.<somehash>.js`. It gets generated because `JsonpMainTemplatePlugin` only uses the `outputOptions.chunkFilename` ignoring the chunk being initial.

**What is the expected behavior?**
Filter the chunks included the `require-ensure` function to only include chunks which are needed.
**Additional Note:**
If this is changed, this should actually help with long term caching when using the above pattern (which even popular project like [jhipster ](https://github.com/jhipster/generator-jhipster/blob/master/generators/client/templates/angular/webpack/_webpack.common.js#L89) use). This is because currently the hash of the `mainfest `chunk changes each time another chunkhash changes. 

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
"webpack": "3.10.0"

**Comment by sokra** [comment]
That's true.

Try changing `hasRuntime` to `isInitial` in this line https://github.com/webpack/webpack/blob/8e9470cb967d9d15df5c755d3bea07987d73e9a3/lib/Chunk.js#L547

When this works, send a PR.
