### ISSUE TITLE
Watch bug

### ISSUE THREAD

**Issue by rosea1** [webpack/webpack#6241]
BUG

Ok perhaps i am doing this wrong as i am new to webpack but surely i cant be the first person to try this. When i run webpack with the --watch option, it seems to start the watching of the files before all the build occurs. Therefore during the build when im using HTML webpack plugin to create files and using copy plugin to move files to dist folder, webpack seems to get stuck in a loop because it is watching the files which are being changes by the above commands ?

Additionally to this i have tried using the watchOptions.ignored config but this doesnt seem to ignore the folders i specify.

Run webpack with the watch switch and try and copy a file using copy plugin and it will go into a loop unless im doing something wrong?

Start the watch after all the bundling and processing is done ? 

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Node v9.3.0
npm 5.5.1
MAC OSX El Capitan Version 10.11.6

**Comment by mikeyhogarth** [comment]
Do you have a link to a repo that this issue is occurring on?

**Comment by rosea1** [comment]
NO, it is currently on a local machine. 
Here is my webpack config;

const path = require('path');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const ExtractTextPlugin = require("extract-text-webpack-plugin");
const env = process.env.NODE_ENV;
const themeDirectory  = path.resolve(__dirname, 'theme');

module.exports = {
  	entry: './app.js',
  	output: {
  		path: path.join(__dirname,'public/dist/'),
    	filename: 'app.js',
  	},
  	//watch:true,
  	devtool: 'source-map', //(env !== 'production') ? 'source-map' : false,
  	module : {
	    rules: [{
	        	test: /\.js$/,
	        	loader: 'babel-loader',
		    	exclude: '/node-modules/',
		        options: {
		          presets: ["es2015", "react"]
		        }
	    	}, { 
				test: /\.(jpe?g|png|gif)$/i, 
				loader:"file-loader",
				query:{
					name:'[name].[ext]',
					outputPath:'images/'
				}
			},
			{
				test: /\.(woff(2)?|ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/,
				loader: "url-loader",
				query:{
					limit:'10000',
					name:'[name].[ext]',
					outputPath:'fonts/'
				}
			},
		    {
		      	test: /\.scss$/,
		      	use: ExtractTextPlugin.extract({
		      		fallback: 'style-loader',
		      		use: [
						{
							loader: 'css-loader',
							options: {
								minimize: (env === 'production') ,
								sourceMap: true,
							}
						}, 
						{
							loader: "resolve-url-loader",
						},
						{
							loader: 'sass-loader',
							options: {
								sourceMap: true,
								sourceMapContents: true
							}
						}
					]
		  		})
		    }
	    	]
	  	},
	plugins:[
		new CopyWebpackPlugin([
			{from: 'node_modules/suru/images', to: path.resolve(themeDirectory, 'images') },
			{from: 'node_modules/suru/fonts', to: path.resolve(themeDirectory, 'fonts') }
		]),
    	new ExtractTextPlugin('app.css')
	]
};

**Comment by rosea1** [comment]
I have had to comment out the watch as it just gets caught in an uncontrollable loop when files are copied with the copy loader.

**Comment by rosea1** [comment]
Update on this, When i put the watchOptions.ignored config in there and comment out the copy command, to test weather files are actually being ignored it works. So i ignore both whole directories where the copy command is getting files from and copying to. Confirmed that the ignore is working by changing files in both of these directories and webpack does not rebuild as expected. However when i uncomment copy command with ignore options, it still gets stuck in a rebuild loop.

**Comment by mixtur** [comment]
Looks like the same bug as this one https://github.com/webpack/webpack/issues/5749.
Also there is shorter reproduce example.

**Comment by rosea1** [comment]
sure looks like the same issue, is there any fix for it ? this must be something that lots of other people would want to do right?

**Comment by mixtur** [comment]
Not really. In my own plugin I just sent new files to the past via `fs.utimes`. It worked but I felt dirty after doing that)
Just found this issue https://github.com/webpack/watchpack/issues/53. It seems to be closer to the root cause.

**Comment by rosea1** [comment]
hmm ok, gulp seems to do this really well with no issues so maybe il go back to that.

**Comment by evilebottnawi** [comment]
@rosea1 problem still exists?

**Comment by rosea1** [comment]
@evilebottnawi  Yes afraid so, are you experiencing something similar ?

**Comment by evilebottnawi** [comment]
@rosea1 can you create minimum reproducible test repo?

**Comment by rosea1** [comment]
@evilebottnawi  , just tried to create a gist to recreate issue but it seems to have fixed. Has webpack been updated recently ?

**Comment by evilebottnawi** [comment]
@rosea1 we recently update `watchpack@1.5.0` (fix some issues in watch mode on mac os). Seems you describe here this bug :smile: Can we close?

**Comment by evilebottnawi** [comment]
@rosea1 also `webpack` have `"watchpack": "^1.5.0"` as deps. Next fixes can be shipped without update `webpack`. Only update lock files, if you have

**Comment by rosea1** [comment]
ahh that would be why it works now, i ran an npm update so yes i think we can now close this bug ! brilliant
