### ISSUE TITLE
Webpacker Breaking Webpack?

### ISSUE THREAD

**Issue by NicholasLYang** [webpack/webpack#6245]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
When I run `webpack`, I get the following error:

`webpack config /Users/nicholas/cs_projects/content-editor/config/webpack/development.js not found, please run 'bundle exec rails webpacker:install' to install Webpacker with default configs or add the missing config file for your custom environment.`

Weirdly enough, these are the instructions for a Rails application, i.e. webpacker. I think for some reason webpacker is breaking webpack. I don't know why or how. 

**If the current behavior is a bug, please provide the steps to reproduce.**
I'm not sure. Install webpacker, then run webpack? I've uninstalled and reinstalled webpack to no avail.

**What is the expected behavior?**
Webpack should run normally
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
macOS 10.12
node v9.3.0
webpack version not available because error persists even with version flag

**Comment by sokra** [comment]
Report this to webpacker
