### ISSUE TITLE
RemoveParentModulesPlugin takes a long time with hundreds of chunks

### ISSUE THREAD

**Issue by filipesilva** [webpack/webpack#6248]
**Do you want to request a *feature* or report a *bug*?**
I want to report a performance bug.

**What is the current behavior?**
In projects with a lot of chunks, a lot of time is spent on `RemoveParentModulesPlugin`.

The original report (https://github.com/angular/angular-cli/issues/5618#issuecomment-354973859) detailed a 1h build time for a non-production (no uglify etc) build.

The project uses Angular CLI and contains around ~2700 source files. This project has [376 chunks](https://github.com/angular/angular-cli/files/1599960/ng-build.log).

A similar sized project (https://github.com/filipesilva/angular-cli-test-repo) takes only a few minutes to build using the same options.

**If the current behavior is a bug, please provide the steps to reproduce.**

The project is closed source so I do not have a source, but the owner is available for some remote debugging (https://github.com/angular/angular-cli/issues/5618#issuecomment-355033864).

He provided CPU profiles for the first ~10m with node 8.4.0 ([here](https://github.com/angular/angular-cli/files/1600687/CPU-20180103T195000.cpuprofile.zip)) and with node 9.3.0 ([here](https://github.com/angular/angular-cli/files/1606383/CPU-20180105T160658.cpuprofile.zip)).

Both profiles show the majority of time being spent in `RemoveParentModulesPlugin`, specifically within the `hasModule` function. Also see the "Other information" bit at the end for a comparison with Webpack 4.

**What is the expected behavior?**
`RemoveParentModulesPlugin` is optimized to allow having a lot of chunks without a big performance hit.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Node.js 8.4.0, Webpack 3.10.0. Unknown browser/OS.

**Other information.**

I've been looking at Webpack 4 and thought maybe it could help since there are a lot of performance improvements there. The plugin in question has suffered some changes:
- in `webpack@3.10.0`: https://github.com/webpack/webpack/blob/b545b519b2024e3f8be3041385bd326bf5d24449/lib/optimize/RemoveParentModulesPlugin.js
- in `webpack@4.0.0-alpha.3`: https://github.com/webpack/webpack/blob/9334fd8547831ded7f11e05319616a72ea0b4698/lib/optimize/RemoveParentModulesPlugin.js

It looks like there's a fair bit of optimizations changes there. But I'm not sure if the bottleneck has changed. 

There's two places where time is being spent on the CPU profile:
- a `has` call inside the `hasModule` function:
![image](https://user-images.githubusercontent.com/4172079/34612357-52195fb0-f221-11e7-9af3-435cdfaab77f.png)
- a `filter` call inside the `hasModule` function:
![image](https://user-images.githubusercontent.com/4172079/34612366-61c554b4-f221-11e7-8c22-e4aa27a57744.png)

This function hasn't changed though so I don't think it would speed up in this case.

/cc @pleerock @TheLarkInn

**Comment by ooflorent** [comment]
I have an idea to fix this but I need a repo where the build is moderately long (from 10s to 5min) because of this plugin. Could someone provide it?

**Comment by filipesilva** [comment]
I don't have one, I'm sorry... Investigation on this was mostly from exchanges with @pleerock over at angular/angular-cli#5618 (he's the one that experiences the problem).

I'm guessing it's because of the chunk quantity but to be honest it might not be.

**Comment by sokra** [comment]
Please try webpack 4. There is a 80% chance that this has been fixed.

**Comment by pleerock** [comment]
@filipesilva is it possible to use angular cli with webpack 4? (maybe with night builds) then I can check it?

**Comment by ooflorent** [comment]
I've opened a PR to attempt to fix this. Another maybe-solution could be to replace the `Queue` by a `UniqueQueue` to avoid processing the same chunk multiple times.

**Comment by filipesilva** [comment]
@pleerock I have https://github.com/angular/angular-cli/pull/8611 but it probably will break on stuff. If you want to try it you'll have to link it to your project like detailed in https://github.com/angular/angular-cli#development-hints-for-working-on-angular-cli.

This might be a bit involved though. Happy to get on that screenshare you mentioned to help you set it up. Might have to disable stuff that uses plugins that don't yet work with webpack 4 as well.

**Comment by pleerock** [comment]
@filipesilva I have new reports with your branch and webpack 4. First 10+ minutes of `RemoveParentModulesPlugin` execution without `max_old_space_size` being set:

![screenshot 2018-01-10 12 52 10](https://user-images.githubusercontent.com/1753397/34761485-e105a6d8-f605-11e7-844a-3fff54f22a98.png)

[webpack4_no_high_memory.cpuprofile.zip](https://github.com/webpack/webpack/files/1617915/webpack4_no_high_memory.cpuprofile.zip)

First 10+ minutes of `RemoveParentModulesPlugin` execution with `max_old_space_size` being set:

![screenshot 2018-01-10 13 10 01](https://user-images.githubusercontent.com/1753397/34761943-a981c5dc-f607-11e7-9303-ffbbeeff653a.png)
[webpack4_high_memory.cpuprofile.zip](https://github.com/webpack/webpack/files/1617959/webpack4_high_memory.cpuprofile.zip)

This part of code:

```js
while(queue.length > 0) {
  const chunk = queue.dequeue();
  let availableModules = availableModulesMap.get(chunk);
  let changed = false;
  for(const parent of chunk.parentsIterable) {
    const availableModulesInParent = availableModulesMap.get(parent);
    if(availableModulesInParent !== undefined) {
      // If we know the available modules in parent: process these
      if(availableModules === undefined) {
        // if we have not own info yet: create new entry
        availableModules = new Set(availableModulesInParent);
        for(const m of parent.modulesIterable)
          availableModules.add(m);
        availableModulesMap.set(chunk, availableModules);
        changed = true;
      } else {
        for(const m of availableModules) {
          if(!parent.containsModule(m) && !availableModulesInParent.has(m)) {
            availableModules.delete(m);
            changed = true;
          }
        }
      }
    }
  }
  if(changed) {
    // if something changed: enqueue our children
    for(const child of chunk.chunksIterable)
      queue.enqueue(child);
  }
}
```

Takes lot of loops. I didn't measure time but it was running like 50000 times each iteration took around half second. I wasn't successful in finishing this operation at all since don't know when. But I guess since node.js updation from 8 to 9 (as was recommended me before). I'll try to finish this operation and share reports how log it takes on node 9 and then run again on node 8 and compare results.

Also Im open to communication via skype, hangouts or similar service, just let me know how and when.

**Comment by filipesilva** [comment]
Great job on getting those CPU profiles @pleerock! I think the high memory CPU log is the most accurate one because the other will have a lot of time spent on GC, and that doesn't really help narrow down the problem.

It looks like the seal hook is running into a lot of error cases:
![image](https://user-images.githubusercontent.com/4172079/34768402-a1216f38-f5f2-11e7-8705-d03dea1233ff.png)

@sokra is this information useful for you? I can jump on a hangouts with @pleerock and try some more advanced debugging if you can give us some directions.

**Comment by ooflorent** [comment]
@pleerock @filipesilva have you tried the fix in my PR?

**Comment by filipesilva** [comment]
I have not, no. I don't have access to the repo where the problem manifests. @pleerock can you try manually patching your local `webpack` node_modules with https://github.com/webpack/webpack/pull/6249/files?

**Comment by pleerock** [comment]
@filipesilva I will. btw it was running since I posted my message (over 3hrs) and Im going to stop execution since I don't see the end (last time I run it with webpack3 and node9 was over 6hrs and I stopped execution as well)

**Comment by pleerock** [comment]
So, its same with provided code. Problem is still in `while` cycle. In 10+ minutes it run 2500 cycles each iteration take 200ms in average. Profile results:

(https://github.com/webpack/webpack/files/1618650/webpack4_extra_changes.cpuprofile.zip)
![screenshot 2018-01-10 17 11 10](https://user-images.githubusercontent.com/1753397/34772266-487b87c4-f629-11e7-8335-9230f339c336.png)
[webpack4_extra_changes.cpuprofile.zip]

**Comment by pleerock** [comment]
Okay, I downgraded node from 9.3.0 to 8.9.4 and same `while` cycle iteration now takes ~50ms. As I previously told I wasn't able to finish `serve` process since I upgraded to node 9. 

Results of running 10 minutes with node8:

![screenshot 2018-01-10 17 41 38](https://user-images.githubusercontent.com/1753397/34773492-ad61974c-f62d-11e7-962a-eab8c9f5bcf5.png)
[webpack4_node8.cpuprofile.zip](https://github.com/webpack/webpack/files/1618751/webpack4_node8.cpuprofile.zip)

**Comment by filipesilva** [comment]
@pleerock was this last one done with increased memory cap? Looking at that log I still get the feeling that the same error handling logic is taking a lot of time, but that the memory thrashing might be hiding it somewhat.

**Comment by pleerock** [comment]
@filipesilva yes:

```
node --max_old_space_size=8192 --inspect --debug-brk ./node_modules/@angular/cli/bin/ng serve
```

**Comment by filipesilva** [comment]
Huh, don't know why so much time is spend on GC then...

**Comment by sokra** [comment]
hmm I have an idea...

**Comment by sokra** [comment]
Could you try this fix https://github.com/webpack/webpack/pull/6292/files?

**Comment by pleerock** [comment]
@sokra thank you, now `serve` takes only 1001676ms (~17 minutes). It is a great optimization already.

`while` cycle takes **25169ms** and has `741` iterations (372 chunks). Now majority of time taken by `for` loop right after `while` loop. Please see [this log](https://github.com/webpack/webpack/files/1625849/webpack4-optimized-while.log) for the following code:

```ts
class RemoveParentModulesPlugin {
  apply(compiler) {
    compiler.hooks.compilation.tap("RemoveParentModulesPlugin", (compilation) => {
      const handler = (chunks) => {
      const queue = new Queue(chunks);
    const availableModulesMap = new Map();

    for(const chunk of chunks) {
      // initialize available modules for chunks without parents
      if(chunk.getNumberOfParents() === 0)
        availableModulesMap.set(chunk, new Set());
    }

    console.log("chunks.length", chunks.length);
    console.time("while cycle");
    while(queue.length > 0) {
      const chunk = queue.dequeue();
      let availableModules = availableModulesMap.get(chunk);
      let changed = false;
      for(const parent of chunk.parentsIterable) {
        const availableModulesInParent = availableModulesMap.get(parent);
        if(availableModulesInParent !== undefined) {
          // If we know the available modules in parent: process these
          if(availableModules === undefined) {
            // if we have not own info yet: create new entry
            availableModules = new Set(availableModulesInParent);
            for(const m of parent.modulesIterable)
              availableModules.add(m);
            availableModulesMap.set(chunk, availableModules);
            changed = true;
          } else {
            for(const m of availableModules) {
              if(!parent.containsModule(m) && !availableModulesInParent.has(m)) {
                availableModules.delete(m);
                changed = true;
              }
            }
          }
        }
      }
      if(changed) {
        // if something changed: enqueue our children
        for(const child of chunk.chunksIterable)
          queue.enqueue(child);
      }
    }
    console.timeEnd("while cycle");

    // now we have available modules for every chunk

    console.log("starting for loop:", chunks.length);
    console.time("for loop");
    let index = 0;
    for(const chunk of chunks) {
      index++;
      console.time("for iteration #" + index);
      // remove modules from chunk if they are already available
      const availableModules = availableModulesMap.get(chunk);
      const modules = new Set(chunk.modulesIterable);
      const toRemove = new Set();
      console.time("for iteration > step 1");
      if(modules.size < availableModules.size) {
        for(const m of modules)
          if(availableModules.has(m))
            toRemove.add(m);
      } else {
        for(const m of availableModules)
          if(modules.has(m))
            toRemove.add(m);
      }
      console.timeEnd("for iteration > step 1");
      console.time("for iteration > step 2");
      for(const module of toRemove) {
        module.rewriteChunkInReasons(chunk, getParentChunksWithModule(chunk, module));
        chunk.removeModule(module);
      }
      console.timeEnd("for iteration > step 2");
      console.timeEnd("for iteration #" + index);
    }
    console.timeEnd("for loop");
  };
    compilation.hooks.optimizeChunksBasic.tap("RemoveParentModulesPlugin", handler);
    compilation.hooks.optimizeExtractedChunksBasic.tap("RemoveParentModulesPlugin", handler);
  });
  }
}
```

As you can see it takes significant time only during first `handler` execution and each for loop iteration increases in time.

**Comment by sokra** [comment]
I have a plan, but this will take a bit...

**Comment by sokra** [comment]
ok, after a big refactoring I was able to remove the need of rewriting chunks in reasons which should improve performance a lot.

Here is the experimental PR, untested and not sure if it's totally correct yet. But if you want to try it:

https://github.com/webpack/webpack/pull/6354

**Comment by filipesilva** [comment]
@sokra awesome work! @pleerock can you try using that PRs branch with my webpack4 branch? You should be able to install it via `npm install webpack/webpack#performance/remove-rewrite-chunk-in-reasons`.

**Comment by pleerock** [comment]
@filipesilva I have an `webpack.optimize.CommonsChunkPlugin is not a constructor` error

**Comment by filipesilva** [comment]
Ok it seems like there isn't a `CommonsChunkPlugin` anymore (https://github.com/webpack/webpack/pull/6341 and https://gist.github.com/sokra/1522d586b8e5c0f5072d7565c2bee693). I'm going to need some time to figure out how this affects our settings.

**Comment by filipesilva** [comment]
@pleerock can you try with https://github.com/angular/angular-cli/pull/9459 please?

**Comment by TheLarkInn** [comment]
Any updates? Just curious if we need further action.

**Comment by pleerock** [comment]
@TheLarkInn yes I have left comment in https://github.com/angular/angular-cli/pull/9459 . Build now takes 2,5 minutes however there are other issues Im currently facing, but I think they are related to angular cli and not webpack

**Comment by kenotron** [comment]
Still seeing lots of time wasted in this one plugin - keep in mind that this is for inner loop. Any kind of optimization at all done here seems to be unhelpful:

![image](https://user-images.githubusercontent.com/34725/36619208-d40e9006-18a2-11e8-9b9c-a9f80f42f4ec.png)

**Comment by kenotron** [comment]
For incremental build situations (mode: development) for us, when I put this option in:
```
optimization: {
    removeAvailableModules: false,
}
```

The initial build time went down from total of 150s to 100s while the incremental went from near the full build time to 24s!! I'm happy, but it looks like I can do even more here by removing more plugins in my dev mode build.

**Comment by filipesilva** [comment]
@kenotron yeah I kinda expected that option to be off for development but according to https://medium.com/webpack/webpack-4-mode-and-optimization-5423a6bc597a it's always on.

**Comment by kenotron** [comment]
@filipesilva: it's listed there as always on for production mode. 

@sokra: I believe the optimization.removeAvailableModules algo cost should actually be more like 3-4 of those boxes after seeing it in action.

**Comment by filipesilva** [comment]
@kenotron `optimization.removeAvailableModules` is listed as `Always Enabled`, not just for production:

![image](https://user-images.githubusercontent.com/4172079/36631931-8908ff6c-1977-11e8-9694-97346af06b17.png)

**Comment by kenotron** [comment]
Oh! I misread the word "performance" and thought it said "production" - wow, I obviously hadn't had my morning coffee here yet. I'm surprised that it's always enabled. In my dev environment, my scripts got 20% bigger - I would take that hit during development to gain 2-3x speed on innerloop anyday!

**Comment by filipesilva** [comment]
On https://github.com/angular/angular-cli we noticed something similar back on Webpack 3 with TS some time ago. Transpiling to CommonJS modules resulted in MUCH faster rebuilds than ES2015 modules (with ES5 code). 

The reason being imports were analysed for tree shaking with ES2015 modules, but not with CommonJS. This was tracked in https://github.com/webpack/webpack/issues/5863 and marked as resolved for Webpack 4.

Having these granular controls allows to decide what the development builds actually do. Just going through the descriptions in that article it sounds to me that disabling the following for dev would help:
- `optimization.removeAvailableModules`
- `optimization.removeEmptyChunks`

I'd like to actually benchmark the impact that each has but haven't yet.

I don't think chunk size is relevant in dev. One could make the argument that smaller chunks take less time for the browser to parse, and that's true. But the fastest sourcemaps for dev (`eval`, the default) are already essentially duplicating all of your JS chunks anyway.

**Comment by TheLarkInn** [comment]
Please let us know what those results are. It will help us validate this
change.

**Comment by filipesilva** [comment]
Ran some benchmarks with https://github.com/filipesilva/angular-cli-test-repo and modified latest Angular CLI master, which uses `webpack@4.0.0` (final).

On `mode: 'development'` with the in the following in `optimization`:
```
    optimization: {
      noEmitOnErrors: true,
      runtimeChunk: 'single',
      splitChunks: {
        chunks: buildOptions.commonChunk ? 'all' : 'initial',
        cacheGroups: {
          vendors: false,
          vendor: buildOptions.vendorChunk && {
            name: 'vendor',
            chunks: 'initial',
            test: (module: any, chunks: Array<{name: string}>) => {
              const moduleName = module.nameForCondition ? module.nameForCondition() : '';
              return /[\\/]node_modules[\\/]/.test(moduleName)
                     && !chunks.some(({ name }) => name === 'polyfills'
                        || globalStylesEntries.includes(name));
            },
          },
        }
      }
    },
```

With these settings rebuilds take an average of 117,483 ms (111227, 124867, 120434, 112090, 118799). Total size is 92.48 MB.

If I add `removeAvailableModules: false`: rebuilds take an average of 127,518 ms (116335, 125906, 129306, 136256, 129790) and total size is now 103.01 MB. So 10% ish worse in rebuild time and size. I don't consider a 10% change in rebuild time to be noteworthy either way, since it can just be due to extra CPU load from other processes.

If I instead add `removeEmptyChunks: false`: rebuilds take an average of 138,406 ms (132739, 129140, 146174, 140448, 143532) and total size is now 92.48 MB. Same size as default, but around 20% worse rebuild time.

If I instead add `providedExports: false`: rebuilds take an average of 125,699 ms (122223, 124940, 125670, 118347, 137317) and total size is now 91.7 MB. No idea why the size is smaller, I guess a bit less boilerplate.

My conclusion is that none of these defaults improve rebuilds for this test project. I'd like to see some benchmarks from projects like @kenotron's one and the effects of  `removeAvailableModules: false` on them.

Note: if someone is trying to reproduce these numbers, remember to use the high memory script, serve command, `--aot` flag, (so `npm run ng-high-memory -- serve --aot`) and to take the numbers of around the 4th to 9th rebuild (the first ones take longer). I edited `src/main.ts` and added `console.log(1);` for each change.

**Comment by sokra** [comment]
Hey @filipesilva thanks for the report. Do you have some time to test the same repo again with webpack version 4.5?

**Comment by pleerock** [comment]
@sokra it was my repo and I did it again with `angular-cli@6.0.0-rc.5` and `webpack@4.5.0`.

Here is profile results for running `node --max_old_space_size=8192 --inspect --debug-brk ./node_modules/@angular/cli/bin/ng serve`:

![screenshot 2018-04-20 18 52 27](https://user-images.githubusercontent.com/1753397/39054895-45a38cf8-44cc-11e8-9593-1a495d0a24ce.png)

Operation took 6 minutes. I'm not sure if its a bug of chrome of what but I wasn't able to save cpu results this time - profiler just closes imminently when I save the report.

**Comment by elliottsj** [comment]
Using the latest versions of webpack & Node.js (v4.8.3 & v10.1.0 currently), I've found that RemoveParentModulesPlugin is much faster on my project that has ~230 chunks. Previously was on the order of 30-40 seconds, now appears to be less than 2 seconds.

@filipesilva @kenotron @pleerock I encourage you to try out the latest versions of webpack & Node to see if there's any improvement.

**Comment by pleerock** [comment]
@elliottsj its faster thanks to this issue I believe. We are using latest version. With webpack 3 it took hours to build, now it takes only 6 minutes with webpack 4. Great improvement but waiting 6 minutes after each change during development isn't acceptable. 

@sokra since more and more people are using lazy loading in their apps, current situation won't be scalable for webpack. Do you have any ideas what webpack can do in order to fix this issue? Currently we are using webpack for production and systemjs for development. We hate systemjs and the fact that we have to use two tools for the same thing, but only systemjs makes our development acceptable - load time is 10-15 seconds - it loads using multiple queries only what it needs (start page is loading 600-700 files) and compile typescript on-the-fly. For me it looks like bundling such big projects isn't productive anymore and its easier to load and compile things on the fly. What do you think about it?

**Comment by elliottsj** [comment]
To clarify, I was previously using webpack@4.8.0 and Node.js v8.11.0 when I had the build times of 30-40 seconds. webpack@4.8.3 was recently released with [this improvement](https://github.com/webpack/webpack/commit/4daaf6cd3308cfd0331f43ccbf686602b3603f3d#diff-85fbed05eca5e121b22d10eb9cd921d5), and I suspect that Node.js v10 includes some optimizations to Map / WeakMap / Set which improve performance significantly. 

@pleerock Have you tried Node.js v10?

**Comment by akashdeepshah** [comment]
Upgrading to node 10.3.0 fixed the problem for me.

**Comment by sibelius** [comment]
`RemoveParentModulesPlugin` is causing memory leaks as well

```
ℹ ｢wdm｣: Compiling...
 75% basic chunk optimization RemoveParentModulesPlugin                            
<--- Last few GCs --->

[10847:0x102802400]  1151783 ms: Mark-sweep 1319.0 (1447.7) -> 1312.8 (1444.7) MB, 420.5 / 0.0 ms  (average mu = 0.184, current mu = 0.082) allocation failure GC in old space requested
[10847:0x102802400]  1152186 ms: Mark-sweep 1325.3 (1447.7) -> 1315.5 (1444.7) MB, 345.2 / 0.0 ms  (average mu = 0.165, current mu = 0.143) allocation failure GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x1b544d3041bd]
Security context: 0xedd36b1e6c9 <JSObject>
    1: delete [0xedd36b13cb9](this=0xedd70ed5d31 <Set map = 0xedd59d02a99>,0xedde8a7c929 <DependenciesBlock map = 0xedd9b28ee31>)
    2: handler(aka handler) [0xeddd9afc9b9] [/Users/sibelius/Dev/entria/app/app-admin/node_modules/webpack/lib/optimize/RemoveParentModulesPlugin.js:~30] [pc=0x1b544ec573d9](this=0xedd88e822e1 <undefined>,chunks=0xeddc282...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x100033c31 node::Abort() [/Users/sibelius/.nvm/versions/node/v10.5.0/bin/node]
 2: 0x1000353ea node::FatalTryCatch::~FatalTryCatch() [/Users/sibelius/.nvm/versions/node/v10.5.0/bin/node]
 3: 0x10019bc9a v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/sibelius/.nvm/versions/node/v10.5.0/bin/node]
 4: 0x10056a072 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/sibelius/.nvm/versions/node/v10.5.0/bin/node]
 5: 0x100569029 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/Users/sibelius/.nvm/versions/node/v10.5.0/bin/node]
 6: 0x100566cb8 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/sibelius/.nvm/versions/node/v10.5.0/bin/node]
 7: 0x1005731fc v8::internal::Heap::AllocateRawWithRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/Users/sibelius/.nvm/versions/node/v10.5.0/bin/node]
 8: 0x10054174e v8::internal::Factory::NewFixedArrayWithFiller(v8::internal::Heap::RootListIndex, int, v8::internal::Object*, v8::internal::PretenureFlag) [/Users/sibelius/.nvm/versions/node/v10.5.0/bin/node]
 9: 0x1006ab943 v8::internal::OrderedHashTable<v8::internal::OrderedHashSet, 1>::Rehash(v8::internal::Handle<v8::internal::OrderedHashSet>, int) [/Users/sibelius/.nvm/versions/node/v10.5.0/bin/node]
10: 0x100792153 v8::internal::Runtime_SetShrink(int, v8::internal::Object**, v8::internal::Isolate*) [/Users/sibelius/.nvm/versions/node/v10.5.0/bin/node]
11: 0x1b544d3041bd 
/bin/sh: line 1: 10847 Abort trap: 6           webpack-dev-server --config webpack.config.js --progress
error Command failed with exit code 134.
```

**Comment by ScottMGerstl** [comment]
Upgrading to Node 8.12.0 worked for me
