### ISSUE TITLE
Possible to require every file in a directory?

### ISSUE THREAD

**Issue by christophercliff** [webpack/webpack#625]
There are some modules on npm that do this, but they all use `fs`.

**Comment by mightyiam** [comment]
What's the webpack 2 way to achieve this?

**Comment by okbel** [comment]
I cannot find a good way to achieve this with Webpack 2. Anyone? :)

**Comment by mih-kopylov** [comment]
@okbel please find the way in example:
```
(function () {
    var angular = require("angular");
    angular.module("core.components", []);

    var context = require.context(".", true, /\.js$/);
    context.keys().forEach(function (key) {
        context(key);
    });
})();
```

This way I define new angular module and require all js files in subdirectories.

**Comment by jhnns** [comment]
@okbel `require.context` still works with webpack 2.

You can also try https://www.npmjs.com/package/contents-loader

**Comment by okbel** [comment]
@mih-kopylov @jhnns Thank you! Is there a way to have them all imported in an object?

For example:


`Plugin-One.js`
```js
export default () => {
  return 'Plugin One'
}
````

`Plugin-Two.js`
```js
export default () => {
  return 'Plugin Two'
}
````

and have some api like this or

```js
import * as plugins from '<PLUGIN_FOLDER>'
```

and logging plugin outputs

```js
{
  'Plugin-One': () => {...}
  'Plugin-Two': () => {...}
}
```


(I'm experimenting with context, but so far I was able just to import them)


Thank you so much!

**Comment by okbel** [comment]
I solved it using `plugins[key] = context(key)`. If you have any suggestion, please let me know. Thanks!

**Comment by mih-kopylov** [comment]
@okbel `require.context` already gets you an object. You can just replace the files with modules
```
    var context = require.context(".", true, /\.js$/);
    var obj = {};
    context.keys().forEach(function (key) {
        obj[key] = context(key);
    });
    return obj;
```

**Comment by yesvods** [comment]
@mightyiam But when I use 

```
obj[key] = require(key)
```
It will be transform  to 

```
obj[key] = webpackMissModule(){...}
```

**Comment by DanDvoracek** [comment]
Thanks @mih-kopylov! it does the job just fine! 👍

**Comment by dietergeerts** [comment]
See https://github.com/webpack/webpack/issues/370#issuecomment-326821108

**Comment by peey** [comment]
Is it possible to do this for any loaders? I've defined my loaders correctly in webpack config and have even tried prepending them to the require call itself, e.g.

```
    var context = require.context(".", true, /\.js$/);
    var obj = {};
    context.keys().forEach(function (key) {
        obj[key] = context("raw-loader!" + key);
    });
    return obj;

```

But it doesn't work. It always gives me an error like `Error: Module parse failed: Unexpected token (1:6)` which makes me think that it's trying to parse the required file as js.

**Comment by aleen42** [comment]
Should `require.context` have the following problems?

1. Cannot extract it as a method, like `requireAll()`, which results in static analysis unsuccessfully.
2. It is inconvenient to control something via `require.context` like the recursivly access level, or exclude pattern.
3. Side effect on tree shaking? (Not confirmed yet)

That's why I hope to use webpack loader to implement `requireAll`.
