### ISSUE TITLE
Webpack doesn't use common chunks for Angular lazy loaded modules : 

### ISSUE THREAD

**Issue by RoyiNamir** [webpack/webpack#6251]
I'm using Webpack with Angular and Nativescript .  
I already know how to make the `compiler` to be removed when  `AOT` compilation.

It seems that CommonsChunkPlugin doesn't work ( or is it) with angular lazy loaded modules 

My problem begins with lazy loaded modules. You see , when I load lazy modules ( `0.js` and `1.js` in image) , Where each  uses the `Http Module`  , it seems that `Http` is embedded/repeated in EACH module :

[![enter image description here][1]][1]

**Question**

Is there any option to tell webpack : "_this lazy module uses `http` , but `http` is already used before somewhere else. No need to worry , remove it from this bundle._"

Or better  - all shared modules for lazy modules , will be as common

Is it  supported ?

Full webpack.config : https://gist.github.com/anonymous/da35cb88252018422327663e0f14a942

  [1]: https://i.stack.imgur.com/i5Ncy.png

**Comment by sokra** [comment]
Yes the CommonsChunkPlugin supports this too. See documentation

**Comment by RoyiNamir** [comment]
@sokra ive seen and tried with async with children bit it doubled the size of the files. 

Can you please tell me what im doing wrong?
