### ISSUE TITLE
beautify-lint and eslint configs fight (#next branch)

### ISSUE THREAD

**Issue by samccone** [webpack/webpack#6256]
Right now if you run eslint fix over the code and then run beautify-lint you will hit this error

![image](https://user-images.githubusercontent.com/883126/34655097-6f824154-f3b9-11e7-90e2-7f1862300547.png)

if you run in the inverse order eslint will complain.

**Comment by sokra** [comment]
I know. That's a problem with `return` followed by `(`.

We eventally move to prettier and remove js-beautify and eslint styling...

**Comment by samccone** [comment]
Would it be reasonable to disable one of these so every presubmit test does not fail?

**Comment by sokra** [comment]
For now, just write code this way:

``` js
const fn = (...args) => { ...
return fn;
```

**Comment by samccone** [comment]
OK. 

I still think that if one of the tools that is supposed to autofix the code generates code that causes another linter on the project to fail that it is a pretty poor experience for a contributor that is not privy to this info.

**Comment by ooflorent** [comment]
`beautify-lint` is gone. Long live `prettier` 🎉
