### ISSUE TITLE
webpack watch mode will cause a permission issue

### ISSUE THREAD

**Issue by chaosheng-git** [webpack/webpack#6258]
**Do you want to request a *feature* or report a *bug*?**

report a bug

**What is the current behavior?**
use nodejs api to watch a file with a dependencies like below
--build-script.js
--entry-file.js
--src
----test
------file-import-by-entry-file.js
it will cause a Windows permission denied dialog when deleting the src folder in windows.

**If the current behavior is a bug, please provide the steps to reproduce.**

build-script.js
```
const path = require('path');
const fs = require('fs');
const webpack = require('webpack');

const filePath = path.resolve(__dirname, "./entry-file.js");
const compiler = webpack({
   entry: filePath,
   output: {
      path: "/",
      filename: "bundle.js"
   }
});
compiler.watch({}, (err, stat) => {
    console.log(stat.hash);
});
```
entry-file.js
```var a = require('./src/test/file-import-by-entry-file');```   
file-import-by-entry-file.js   
```var b = 1;```   
run `npm init` `npm i webpack --save` `node build-script`,then choose the src folder and press Delete button.
if need, I'll push a project in my github to reproduce this,
but I can't push code to github behind my company 's proxy,so I 'll push it after work (about 7 hours later), sorry for this;

**What is the expected behavior?**
delete the folder without permission denied dialog
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
windows 7 64bit
webpack 3.10.0 3.8.1 4.0.0-alpha.4(I choose some versions, seems a common problem)
Nodejs 8.9.3

**Comment by sokra** [comment]
Yep, that's how windows works. Watching a folder locks the parent folder.

Try to change the require first and delete the folder afterwards.

**Comment by chaosheng-git** [comment]
[this](https://github.com/chaosheng-git/webpack-watch-issue) is the reproduce repo; and it's ok on mac

**Comment by chaosheng-git** [comment]
got it; thanks for the comment.
