### ISSUE TITLE
output umd bug

### ISSUE THREAD

**Issue by seekwe** [webpack/webpack#6259]
Old version of UMD output : 
```
(function webpackUniversalModuleDefinition(root, factory) {
  // root === {__esModule: true}
  if(typeof exports === 'object' && typeof module === 'object')
    module.exports = factory();
  else if(typeof define === 'function' && define.amd)
    define([], factory);
  else if(typeof exports === 'object')
    exports["aa"] = factory();
  else
    root["aa"] = factory();
})(this, function() {
  //Be careful this 
});

```

New version of UMD output : 

```
(function webpackUniversalModuleDefinition(root, factory) {
        // root === Window {frames: Window, postMessage: ƒ, blur: ƒ, focus: ƒ, close: ƒ, …}
	if(typeof exports === 'object' && typeof module === 'object')
		module.exports = factory();
	else if(typeof define === 'function' && define.amd)
		define("aa", [], factory);
	else if(typeof exports === 'object')
		exports["aa"] = factory();
	else
		root["aa"] = factory();
})(typeof self !== 'undefined' ? self : this, function() {
  //Be careful self 
});
```

`import * as test from './umd.js'`

Two output is wrong.

1.{__esModule: true}

2.Window {frames: Window, postMessage: ƒ, blur: ƒ, focus: ƒ, close: ƒ, …}

**Comment by sokra** [comment]
I don't understand the problem...

**Comment by seekwe** [comment]
@sokra  

Old version of UMD output : 
```
(function webpackUniversalModuleDefinition(root, factory) {
  // root === {__esModule: true}
  if(typeof exports === 'object' && typeof module === 'object')
    module.exports = factory();
  else if(typeof define === 'function' && define.amd)
    define([], factory);
  else if(typeof exports === 'object')
    exports["aa"] = factory();
  else
    root["aa"] = factory();
})(this, function() {
  //Be careful this 
});
```
New version of UMD output : 
(function webpackUniversalModuleDefinition(root, factory) {
        // root === Window {frames: Window, postMessage: ƒ, blur: ƒ, focus: ƒ, close: ƒ, …}
	if(typeof exports === 'object' && typeof module === 'object')
		module.exports = factory();
	else if(typeof define === 'function' && define.amd)
		define("aa", [], factory);
	else if(typeof exports === 'object')
		exports["aa"] = factory();
	else
		root["aa"] = factory();
})(typeof self !== 'undefined' ? self : this, function() {
  //Be careful self 
});
```

`import * as test from './umd.js'`

Two output is wrong.

1.{__esModule: true}

2.Window {frames: Window, postMessage: ƒ, blur: ƒ, focus: ƒ, close: ƒ, …}

**Comment by orzechowskid** [comment]
we experienced a similar problem and had to downgrade to webpack 3.4 from 3.5+ to properly build UMD modules.

**Comment by bq-hentai** [comment]
@sokra maybe means that the comment is not appropriate
