### ISSUE TITLE
Use shorter variable name for an import

### ISSUE THREAD

**Issue by gaearon** [webpack/webpack#6266]
**Do you want to request a *feature* or report a *bug*?**

Feature.

**What is the current behavior?**

Webpack uses names like `__WEBPACK_IMPORTED_MODULE_0__lodash___default` for the imports. This makes errors very long and a bit hard to read:

![example message with long variable name](https://camo.githubusercontent.com/421c84099cc51bb3f0e7d386ed1df0ac6aecc3d7/68747470733a2f2f646c2e64726f70626f7875736572636f6e74656e742e636f6d2f7370612f73793574697a317a6e3935326331352f6430736233346f632e706e67)

**What is the expected behavior?**

Maybe we could use a shorter magic name that is also a bit less dramatic? For example `__webpack_import_lodash__default`.

**If this is a feature request, what is motivation or use case for changing the behavior?**

More concise error messages.

**Comment by ooflorent** [comment]
Relates to #3957

**Comment by evilebottnawi** [comment]
Close in favor https://github.com/webpack/webpack/issues/3957
