### ISSUE TITLE
In IE11 wds 2.10.0 is broken 2.9.7 works - Invalid Character

### ISSUE THREAD

**Issue by httpete** [webpack/webpack#6275]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
Invalid Character in my bundle. This issue has been around before, it's some library in the dependency tree that uses ` .
**If the current behavior is a bug, please provide the steps to reproduce.**
Just start the dev server in IE11

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

IE11

**Comment by sokra** [comment]
Wrong repo. File this on webpack-dev-server
