### ISSUE TITLE
[4.0] `module.hot` is replaced by `false` on development

### ISSUE THREAD

**Issue by JounQin** [webpack/webpack#6276]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
As title

**If the current behavior is a bug, please provide the steps to reproduce.**

configuration:
```js
module.exports = {
  mode: 'development',
}
```

source code:
``` js
if (module.hot) {
  console.log('module.hot')
}
```
generated code:
https://github.com/JounQin/webpack-next-study/blob/module.hot/dist/main.js#L80

**What is the expected behavior?**
`module.hot` should not be replaced by `false` on development

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
node: v9.3.0
webpack: 4.0.0-alpha.4
webpack-cli: 2.0.2

**Comment by EugeneHlushko** [comment]
Hi @JounQin 
I cannot reproduce, can you set up a reproduction repo? Using your repo the build command does build in production mode and works as expected. If i add build-dev script it also works fine e.g.:

```
"scripts": {
    "dev": "cross-env DEBUG=1stg:* babel-node server",
    "build": "rimraf dist && cross-env NODE_ENV=production webpack --colors --progress",
    "build-dev": "rimraf dist && cross-env NODE_ENV=development webpack --colors --progress",
    "start": "cross-env NODE_ENV=production DEBUG=1stg:* babel-node server"
  },
```

**Comment by JounQin** [comment]
@EugeneHlushko The reproduction is at `module.hot` branch, just run `yarn build`.

**Comment by EugeneHlushko** [comment]
I think you need to explicitly set module hot in plugins or pass a hot option in the cli:
e.g. `webpack --hot` or in the config:
```
const webpack = require('webpack');
module.exports = {
  mode: 'development',
  plugins: [
    new webpack.HotModuleReplacementPlugin()
  ]
}
```

I suppose that in the master branch the koa-webpack requires the plugin in development mode for you along these deps
https://github.com/shellscape/koa-webpack/blob/f2eb3f99adbed049ac854f48adb056910d261dca/index.js#L5-L6

**Comment by JounQin** [comment]
I can't add `HotModuleReplacementPlugin` into plugins because of `koa-webpack@2.0`, see https://github.com/shellscape/koa-webpack#migrating-to-version-2x .

**Comment by sokra** [comment]
This is working as expected on webpack side, see @EugeneHlushko answer.

You should file the issue on koa-webpack if you have problems using it.

**Comment by shellscape** [comment]
@JounQin webpack-hot-client handles injecting that plugin. Haven't seen that behavior before with that module.

**Comment by JounQin** [comment]
@shellscape So it should be an issue of `webpack-hot-client`? You can check https://github.com/JounQin/webpack-next-study/blob/module.hot/src/index.js#L19, branch `module.hot`, simply run `yarn dev`.

**Comment by shellscape** [comment]
First thing that stands out to me is that `publicPath` should just be `'/'` here: https://github.com/JounQin/webpack-next-study/blob/module.hot/server/index.js#L17. You actually shouldn't even have to set that.

I'm not sure why that's not working. But I can point you to the test app in webpack-hot-client that works as expected (https://github.com/webpack-contrib/webpack-hot-client/blob/master/test/app.js) and it's a similar minimal example as yours. I don't use React, so maybe that's causing problems? I wouldn't know about that unfortunately. I would recommend taking a look at that test app to see how it works and maybe you can apply something from that to your app.

Agree with @sokra that this isn't a webpack issue. If you can't figure it out then lets continue the discussion in webpack-hot-client's repo.
