### ISSUE TITLE
Webpack watch mode , so many recompilation

### ISSUE THREAD

**Issue by retyui** [webpack/webpack#6284]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
I'm testing a plugin that creates automatically icon fonts:
Webpack watch mode : compiler triggered ~30-40 `invalid` event 

**If the current behavior is a bug, please provide the steps to reproduce.**
```bash
git clone https://github.com/retyui/postcss-icon/ -b dev-font-mode
cd postcss-icon/example/font/webpack/
yarn # or npm install
yarn dev # npm run dev
```
**What is the expected behavior?**
 triggered 1 `invalid` event 

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
**System**:    Host: amur Kernel: 4.10.0-42-generic x86_64 (64 bit) Desktop: Cinnamon 3.6.6, Distro: Linux Mint 18.3 Sylvia
**Node**: 8.9.1
**yarn**: 1.3.2

![image](https://user-images.githubusercontent.com/4661784/34789218-766f636a-f64e-11e7-982a-6e8116d33494.png)

**Comment by sokra** [comment]
This is expected behavior because of filesystem timestamp inaccuracy.

**Comment by retyui** [comment]
@sokra  How fix this problem ?
