### ISSUE TITLE
3D Perspective on logo.

### ISSUE THREAD

**Issue by trusktr** [webpack/webpack#629]
Just an idea:

http://youtu.be/-D_3vw69Mkc

Just add the CSS perspective property to the `.logo`.

**Comment by trusktr** [comment]
@sokra Is there some JavaScript that triggers the animation? It'd be easier to do it there without actually modifying the logo.

**Comment by shama** [comment]
I also prefer the isometric look of the logo but @trusktr if you're still interested in updating the logo; the animation is timed just by the CSS. So you would need to modify the translations to each side or maybe get fancy with the `perspective` css declaration.

Feel free to send a PR to https://github.com/webpack/docs/blob/master/app/css/mixins.styl#L17-L94

Cheers!
