### ISSUE TITLE
ModuleConcatenationPlugin option to disable name scoping

### ISSUE THREAD

**Issue by truebden** [webpack/webpack#6294]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Currently ModuleConcatenationPlugin keeps the scope for exports by adding an identifier in front of the variables (the name of the file).

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
Add an option to disable this behavior, so that the name of the exports remain the same.

**If this is a feature request, what is motivation or use case for changing the behavior?**
In our project the names of the classes are generated and it is not possible that name clashes exist. But we rely on the names of the classes at some points (e.g. de/serialization with type hints) and need the names not to be changed.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
I already created a fork with the changes I would suggest. Please see https://github.com/webpack/webpack/compare/master...unblu:feature/module-concatenation-disable-name-scoping

**Comment by sokra** [comment]
1. Don't rely on class names. They will be removed by minimizers anyway.
2. ModuleConcatenation already tries to keep variable names and only rename when conflicts occur.

**Comment by truebden** [comment]
1. For minimizing we have a special handling. But this handling is expensive and not needed for development.
2. Currently it changes always the names of the exports in our project

**Comment by sokra** [comment]
You can look at this example:

https://github.com/webpack/webpack/tree/master/examples/scope-hoisting#jsoutputjs

Here `x` and `y` are not renamed because they are unique. `a` is renamed because it occurs in two modules.

**Comment by truebden** [comment]
Okay, that is true. For me the question is then, why it does the name scoping. I checked in the Code of ConcatenatedModule why this does happen and the reason is, that the class variable is added to the list of allUsedNames already at the begining where the global names are added and the check with the regex for __WEBPACK_MODULE_REFERENCE__ [here](https://github.com/webpack/webpack/blob/b545b519b2024e3f8be3041385bd326bf5d24449/lib/optimize/ConcatenatedModule.js#L504). Can you give me an explanation for this? As this happens only for some modules

**Comment by sokra** [comment]
Could you create a minimal test case for this?

**Comment by sokra** [comment]
Maybe `class` is handled incorrectly?

**Comment by truebden** [comment]
Maybe, but it does not seems to be a simple case as I already made a small test for it.
I hope I can create a small test, where this also happens and will let you know about it.

**Comment by truebden** [comment]
Sorry for the long delay.
Here https://github.com/unblu/webpack-test-naming you find a repo with a small test scenario which causes the issue. Could you please check it out?

**Comment by evilebottnawi** [comment]
Fixed in webpack@5, big sorry for delay
