### ISSUE TITLE
require the same library with module drive to different files to be required

### ISSUE THREAD

**Issue by vedmalex** [webpack/webpack#6295]
i've posted the [question on stackoverflow](https://stackoverflow.com/questions/48208632/strange-webpack-create-react-app-graphql-graphq-tools-behaviour-the-same-librar)
**Do you want to request a *feature* or report a *bug*?**
I think this is the bug ot expected to the feature.

**What is the current behavior?**
it is about module loading:

When we require the module that have not meaning `pkg.module` entry, or it is absend webpack loads files 
 and the module from one location.
```
var graphql_1 = require("graphql");
var values_1 = require("graphql/execution/values");
```
the output 
```
var graphql_1 = __webpack_require__(/*! graphql */ "./node_modules/graphql/index.js");
var values_1 = __webpack_require__(/*! graphql/execution/values */ "./node_modules/graphql/execution/values.js");
```
otherwise: we have `pkg.module` definition and loading module and file from the same module 

the output 
```
var graphql_1 = __webpack_require__(/*! graphql */ "./node_modules/graphql/module/index.js");
var values_1 = __webpack_require__(/*! graphql/execution/values */ "./node_modules/graphql/execution/values.js");
```

**If the current behavior is a bug, please provide the steps to reproduce.**

[repo with reproducable issue](https://github.com/vedmalex/webpack-issue-modules)

```
git clone https://github.com/vedmalex/webpack-issue-modules
cd webpack-issue-modules
npm i
```
`npm run check-node` -- not failed
`npm run check-wp` -- failed

**What is the expected behavior?**

`npm run check-node` -- not failed
`npm run check-wp` -- not failed

**If this is a feature request, what is motivation or use case for changing the behavior?**

I think they should behave the same way!!!

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
ubuntu 14.04
node v8.5

**Comment by sokra** [comment]
You should better file the issue in the graphql library.

You can avoid this issue by not using inner requires.

``` js
import { getDirectiveValues } from "graphql";
// instead of
import { getDirectiveValues } from "graphql/execution/values";
```

**Comment by vedmalex** [comment]
this not only one library

**Comment by vedmalex** [comment]
this code works differently in nodejs and in nodejs using webpack? is that might be possible?
```
var assert = require('assert');
var graphql_1 = require("graphql");
var values_1 = require("graphql/type/definition");

var st = graphql_1.GraphQLScalarType;
var st2 = values_1.GraphQLScalarType;

assert(st === st2);
```
there a lot of guys that use this way of requiring files.
your solution is not a solution at all...
Any suggestions?
if you point me to the source code I can contribute as well.
