### ISSUE TITLE
[4.0] json tree shaking with object spread

### ISSUE THREAD

**Issue by JounQin** [webpack/webpack#6305]
**Do you want to request a *feature* or report a *bug*?**
I don't know is it as expected or a bug indeed

**What is the current behavior?**
```js
import * as json from './test.json'

const { used } = json // json tree shaking does not work
const used = json.used // json tree shaking works

console.log(used)
```

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/JounQin/webpack-next-study/blob/json_tree_shaking/src/index.js

**What is the expected behavior?**
both codes should work

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
node: v9.3.0
webpack: 4.0.0-alpha.4

**Additional Info**
I'm using TypeScript which does not support ESM style import for json files, so I'm using object ~~spread~~ destructuring to short json variables usage.

**Comment by sokra** [comment]
Better use it this way:

``` js
import { used } from "./test.json";
```

**Comment by JounQin** [comment]
@sokra I'm using TypeScript which does not support ESM style import for json files, so I'm using object spread to short json variables usage.

**Comment by sokra** [comment]
yeah, it's currently not supported.

**Comment by TheLarkInn** [comment]
@JounQin I believe this actually is possible. cc @danielrosenwasser

**Comment by ooflorent** [comment]
@damianobarbati no. If you want tree-shaking on JSON files, don't use `import * as`.

---

According to the original question, the issue is about object destructuring and not object spread. Object destructuring is not supported by the tree-shaking algorithm. To enable tree-shaking you must use named imports:

```js
import {foo} from "./test.json"      // ✅
import test from "./test.json"       // ❌
import * as test2 from "./test.json" // ❌

**Comment by JounQin** [comment]
@ooflorent But actually it works like following as like in description:

``` js
import * as json from './test.json'

const used = json.used

console.log(used)
```

**Comment by ooflorent** [comment]
@JounQin Hmm. I'll try to find out what's going on then.

**Comment by tbassetto** [comment]
@ooflorent: Could you find if this behavior is expected? :) Is JSON tree-shaking with code like in the latest comment expected to be future-proof?

I need tree-shaking on a JSON file, but since the its keys are not valid JavaScript identifier so I ended up writing:
```javascript
import * as json from "some-package/iconsData.json";
const path = json["arrow-circle-down"];
console.log("arrow-circle-down", path);
```

**Comment by JounQin** [comment]
@tbassetto Your case should be fine as I mentioned at https://github.com/webpack/webpack/issues/6305#issuecomment-387653005.

This issue is about `object spread`.
