### ISSUE TITLE
Manual opt-in for dynamic dependencies

### ISSUE THREAD

**Issue by rmja** [webpack/webpack#6306]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
`import()` with [dynamic dependencies](https://webpack.js.org/guides/dependency-management/) includes [all matching dependencies](https://github.com/webpack/webpack/issues/87) by default.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**
It would be extremely useful if one could give webpack a hint that the possible set of dynamic dependencies in a require context is manually specified elsewhere in the application. A typical example is `moment` where all locales are included by default because of its internal call `require()` to dynamically get a language.

If such a call instead could be something like:
```
import(/* webpackMode: "manual" */ './locale/' + id);
```

Then, in the application consuming the library, one could somewhere in the code manually put the exact set of includable dependencies:
```
import 'moment/locale/da' /* webpackChunkName: "lang-da" */
import 'moment/locale/de' /* webpackChunkName: "lang-de" */
```

I know that one can use `ContextReplacementPlugin` to remove from the set of all dependencies, but this just seems much more intuitive in many cases.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Windows 10, node 9.2.0, webpack 3.10.0

**Comment by sokra** [comment]
`webpackMode: "weak"`

see https://webpack.js.org/api/module-methods/#import-
