### ISSUE TITLE
Bug: --verbose breaking --json log file

### ISSUE THREAD

**Issue by axe312ger** [webpack/webpack#6307]
**Do you want to request a *feature* or report a *bug*?**

This is a bug with latest webpack (`3.10.0`), some version between `3.10.0` and `3.3.0` introduced this bug.

**What is the current behavior?**

`module` root property is missing in json output, producing a log file which breaks several analysers like [webpack-bundle-analyzer](https://github.com/webpack-contrib/webpack-bundle-analyzer) and https://webpack.github.io/analyse/

The modules can be found in `root.chunks[0].modules` and moving these to `root.modules` fixes the problem and analysing works again.

### webpack-bundle-analyzer output from broken log
![screen shot 2018-01-12 at 13 50 57](https://user-images.githubusercontent.com/1737026/34876195-cfea24e0-f7a0-11e7-8647-e422174ea3b7.png)

### error message of https://webpack.github.io/analyse/ from broken log
<img width="1038" alt="screen shot 2018-01-12 at 13 53 13" src="https://user-images.githubusercontent.com/1737026/34876220-e308aa2e-f7a0-11e7-9933-b482f2e31544.png">

**If the current behavior is a bug, please provide the steps to reproduce.**

* attach `--verbose` to your webpack call
* or set `config.stats` to `verbose`

I created a minimal repository to reproduce the bug: https://github.com/axe312ger/webpack-broken-log

just run `npm run log:broken` and `npm run log:working` to see the difference.

**What is the expected behavior?**

1. The modules should be found in `root.modules`.
2. https://webpack.github.io/analyse/ should not fail and webpack-bundle-analyzer should output the following:
![screen shot 2018-01-12 at 13 50 28](https://user-images.githubusercontent.com/1737026/34876236-f2e09114-f7a0-11e7-8f75-75baffd6dbb3.png)

**If this is a feature request, what is motivation or use case for changing the behavior?**

Bugreport

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

We found this issue in several webpack projects, all on OSX (I am pretty sure this is not OS related)

**Comment by sokra** [comment]
hmm yeah seem to be a bug. `--json` should enable `modules: true`. You can send a PR to webpack/webpack-cli

**Comment by axe312ger** [comment]
So here we go, PR is open. Worked for me locally :)
