### ISSUE TITLE
[perf] Why not avoid so many property accesses for imports?

### ISSUE THREAD

**Issue by trusktr** [webpack/webpack#6310]
In the output, I see stuff like

```js
__WEBPACK_IMPORTED_MODULE_15__Scene__["a" /* default */]
```

That code is running in an animation loop, along with a bunch of other similar code. It has:

1. string creation
1. property access

In contrast, the original code is just

```js
Scene
```

1. no string creation
1. no property access

which means better performance.

It can at least be simply:

```js
var Scene = __WEBPACK_IMPORTED_MODULE_15__Scene__["a" /* default */]
```

at the top of the module so that the variable is cached for every re-use. 

This is what Rollup does, which is a great thing (though Webpack has many more other useful features).

Why not do these sort of improvements with Webpack?

**Comment by trusktr** [comment]
There's also so may function calls:

```js
        __WEBPACK_IMPORTED_MODULE_2_babel_runtime_core_js_object_define_property___default()(ImperativeBase, __WEBPACK_IMPORTED_MODULE_1_babel_runtime_core_js_symbol_has_instance___default.a, {
```

Can this not be prevented? I don't imagine that the `object_define_property` polyfill module ever changes the value of the export.

**Comment by sokra** [comment]
ESM imports are live bindings, so it's a getter to the variable in the foreign scope.

This can be omitted when using Scope Hoisting -> ModuleConcatenationPlugin (will be default in webpack 4).

The JS optimizer optimizes most of this away anyway. Functions/Getters/properties access are inlined, strings optimize away.

You can "cache" the imported binding in a local variable if you want too. You will loose the live binding, but I guess you don't care in this case.

**Comment by snarun** [comment]
Also, Can these imported dependencies be pushed to global (window), to avoid the duplicates. In our app, we need these references badly to avoid the duplicates, as we're injecting the web pack chunk files at run time.  
```javascript
static getModuleVar(state, request) {
		if(!state.harmonyModules) state.harmonyModules = [];
		let idx = state.harmonyModules.indexOf(request);
		if(idx < 0) {
			idx = state.harmonyModules.length;
			state.harmonyModules.push(request);
		}
		return `__WEBPACK_IMPORTED_MODULE_${idx}_${request.replace(/[^A-Za-z0-9_]/g, "_").replace(/__+/g, "_")}__`;
	}
```

As these are defined with in the global scope of webpack, what is the best way to publish this outside?
