### ISSUE TITLE
require.context, keys() no return correctly

### ISSUE THREAD

**Issue by cdac901** [webpack/webpack#6317]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
keys() functions no return correctly

**If the current behavior is a bug, please provide the steps to reproduce.**
I have this structure directory:

```
/exclude/1.js
/exclude/2.js
3.js
/include/4.js

const list = require.context('./actions/', true, /^(?!.*(^|\/)exclude)[\w/-]+\.js$/)
list.keys(), return Array(0)
```

**What is the expected behavior?**
list.keys() should be:
```
3.js
/include/4.js
```

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Node: 9.4.0
webpack: 3.1.0
Operating System: Mac OSX High Sierra

**Comment by sokra** [comment]
keys always start with `./`.
Your regexp doesn't match `./3.js`
