### ISSUE TITLE
Loaders should skip builtins

### ISSUE THREAD

**Issue by gaearon** [webpack/webpack#632]
I'm trying to fix a few issues in my loader and I noticed it behaves weirdly because it also transforms Webpack's built-in `(webpack)/buildin/module.js`. My loader inserts `module.hot` instructions into it and this creates some sort of circular dependency.

Shouldn't loaders skip builtins altogether? Sadly I found no way to check if a module is a builtin, from inside the loader.

**Comment by bebraw** [comment]
Closing as a solution was presented. Feel free to open a specific feature request if this is still a problem.

**Comment by th0r** [comment]
@bebraw This solution is a workaround. It would be great to support function as `test` value.

**Comment by bebraw** [comment]
@th0r Can you open a separate feature request for that? Make sure you fill the template carefully. Thanks.
