### ISSUE TITLE
Importing chunks asynchronously in require.context scope is not working

### ISSUE THREAD

**Issue by phaistonian** [webpack/webpack#6320]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
`import`ing chunks inside a require.context scope will not result in code-splitting.

**If the current behavior is a bug, please provide the steps to reproduce.**
```js
const pagesContext = require.context('../pages/', true, /index\.js$/);

pagesContext.keys().forEach(file => {
  if (/^\.\/[^/]+?\/(js\/)?index\.js$/.test(file)) {
    const result = pagesContext(file);

    if (result.default) {
       result.default();
    }
  }
});
```

The files (js files) contain `import` calls that are not loaded asynchronously, as expected.

What happens is that the chunks are include in the main bundle file.

**What is the expected behavior?**

The chunks to be loaded asynchronously.

**If this is a feature request, what is motivation or use case for changing the behavior?**

If this is not a bug,  then should be a suggestion; enable having async chunk loading inside a require.context scope.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

System and version (>= 3) independent.

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by phaistonian** [comment]
As it turned out, this was caused by using a too greedy regex in the `require.context` call.

That said, false alarm, apologies.

**Comment by sylvesteraswin** [comment]
@phaistonian I am having the same problem, can you please tell me how you fixed it?

The below is how I grab all the files inside a folder.

```
const context = require.context("./docs", true, /\.js$/);
```

**Comment by phaistonian** [comment]
@sylvesteraswin Check you regexp. I suspect it's too greedy.

Having the regexp be `\.js$` it means that the files you may want to load asynchronously are loaded in the context.

So my guess is that you need to change this regular expression to match the entry points only, not (also) the files that you intend to split-load.
