### ISSUE TITLE
WebPack bootstrap throws undefined error when loading specific chunk

### ISSUE THREAD

**Issue by kenoyer130** [webpack/webpack#6326]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
We are currently injecting multiple webpack modules javascript projects into our app. The issue is if we inject Module A and download a chunk, then inject Module B and download a chunk for that module, then go back to Module A and download a specific chunk it fails with the following error:

 -- bootstrap file
// Execute the module function
 modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);

Uncaught (in promise) TypeError: Cannot read property 'call' of undefined

The moduleId is indeed not in the modules collection.

We have no idea what is causing this specific chunk to trigger the null exception.

Here is the calling code

loader={(cb) => {
          System.import('./components/path/foo')
            .then((component) => {
              cb(component);
            });

Any ideas on how to further trouble shoot this issue would be greatly appreciated.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
webpack is 3.5.5

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by edude03** [comment]
I'm having the same issue thought with webpack 4.0.0 @ beta.0, from what I can tell so far, certain modules don't get bundled. for example in a file I have index.tsx

```
import React from 'react'
import {Link} from "react-router-dom"
import * as R from 'ramda'
import {withMedia} from 'react-media-query-hoc'
import graphql from "react-apollo/graphql"
import {compose, mapProps} from "recompose"
import gql from "graphql-tag"
import Slider from 'react-slick'
```
The line `import gql from "graphql-tag"` throws this error. Commenting it out causes the `import Slider from 'react-slick'` line to cause the same error. Moving those lines around to anywhere in my project triggers this error, so it seems to be something about those libraries. 

When I inspect the `modules` object neither of these modules are included.

**Comment by alexhoma** [comment]
Hi @sokra @edude03, is there any update onn this issue?

**Comment by ashishyadav0019** [comment]
yes please update
