### ISSUE TITLE
Webpack is not externalizing one of my packages

### ISSUE THREAD

**Issue by felipellrocha** [webpack/webpack#6330]
**Report a *bug***

**What is the current behavior?**
I'm trying to externalize one of the packages in my library, but webpack seems to miss it.

**If the current behavior is a bug, please provide the steps to reproduce.**

Install `react-bootstrap`, externalize it like so:

```
module.exports = {
  entry: "./src/index.js",
  devtool: "source-map",
  target: 'web',

  externals: {
    'react': true,
    'react-dom': true,
    'react-bootstrap': true,
    'create-react-class': true,
    'react-ga': true,
    'react-router-dom': true,

    'react-redux': true,
    'redux': true,

    'babel-runtime': true,
    'core-js': true,

    'apollo-client': true,
    'react-apollo': true,

    'lodash': true,
  },

  output: {
    path: paths.appDist,
    filename: 'index.js',
    libraryTarget: 'umd',
  },

```

run webpack: `NODE_ENV=development webpack --display-modules`

Verify that `react-bootstrap` was not included in the list of packages added to library (list given by `--display-modules`)

**What is the expected behavior?**
`react-bootstrap` should not be listed in the list of packages added to the library. There shouldn't be two `react-bootstraps` loaded in my final browser app.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

```
MacOS High Sierra 10.13.1
npx webpack --version
3.8.1
node --version
v9.3.0
Chrome latest
```

**Comment by ooflorent** [comment]
I'm not able de reproduce the issue. I've created a gist: https://gist.github.com/ooflorent/7930acb4ef38d82342a7434bffb58056

As you can see, the modules are externalized. If you want further help, please create a repository that match your case to reproduce the behavior you described and reopen this issue. Thanks!
