### ISSUE TITLE
Dynamic imports causing test failures

### ISSUE THREAD

**Issue by TaylorBriggs** [webpack/webpack#6336]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
`Error: Uncaught [TypeError: __webpack_require__.e is not a function]` when running tests via Karma.

**If the current behavior is a bug, please provide the steps to reproduce.**
The bug can be reproduced by running this repository:
https://github.com/TaylorBriggs/webpack-import-bug

**What is the expected behavior?**
The dynamic import works in the test environment just as it does in development and production.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Browser: ChromeHeadless
Node: v9.3.0
web pack: 3.10.0
OS: Mac OS X 10.12.6

**Comment by TaylorBriggs** [comment]
Investigated further and found the tests start failing with v3.7. I updated the repository above with a branch that shows the tests passing with web pack v3.6.

**Comment by evilebottnawi** [comment]
@TaylorBriggs problem still exists?

**Comment by TaylorBriggs** [comment]
@evilebottnawi I've since moved on to a different project. This can be closed since webpack is now well into v4. Thanks!
