### ISSUE TITLE
invalid event hook only triggered for one file when multiple files have been invalidated

### ISSUE THREAD

**Issue by oennen** [webpack/webpack#6337]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
"invalid" plugin hook is only called once when detecting file changes. If you saved multiple files at one time, only one of them will be provided via the "invalid" plugin hook.

**If the current behavior is a bug, please provide the steps to reproduce.**
Write a simple plugin like this: 

```javascript
compiler.plugin('invalid', function(fileName, changeTime) {
    console.log('changed file:', fileName, 'at', changeTime);
});
```

Run `webpack --watch`, modify two files and save the changes in both files using "Save all" in your favorite IDE. Both files will be processed by the watch mode, but the "invalid" plugin hook will log only one of the two files.

**What is the expected behavior?**

The "invalid" plugin hook is called for every invalidated file or receives an array of invalidated files.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Node.js 8.9.3
webpack 3.10.0
OS X 10.12.6

**Comment by sokra** [comment]
This is expected. The invalid hook is called when the bundle becomes invalid. It's doesn't trigger for each change. Otherwise if would be called `file-changed`.
