### ISSUE TITLE
chunkhash, webworker target

### ISSUE THREAD

**Issue by penge** [webpack/webpack#6338]
**chunkhash**

Problem:
chunkhash is always from source file, not output file
chunkhash is the same for minified and non-minified file

How it should be:
chunkhash is computed from output file

Example:
Removing comments and console using MinifyPlugin
Changing comments in source file changes chunkhash of output file even when output file is the same as before because comments are removed.

**webworker target**

Problem:
Setting target to webworker causes HMR to not work
Bahaving same as hot: false, inline: false

**Comment by sokra** [comment]
The issue here is that chunkhashes need to be inside of the output file.

webworker: File separate issue.
