### ISSUE TITLE
Why isn't bail: true the default?

### ISSUE THREAD

**Issue by gaearon** [webpack/webpack#6343]
**Do you want to request a *feature* or report a *bug*?**

A confusing default?

**What is the current behavior?**

With 3.x, running `webpack` from CLI on a codebase that has a bad `require` that doesn't resolve anywhere compiles the bundle (but the require fails at runtime).

**If the current behavior is a bug, please provide the steps to reproduce.**

1. Create an entry that imports a non-existent file
2. Run `webpack` on it

**What is the expected behavior?**

It fails on first build error by default, and doesn't produce broken builds. Possibly suggesting `bail: false` if people want to get runtime errors instead.

Node 9, webpack 3.10, any OS.

**Comment by sokra** [comment]
webpack 4 doesn't emit output files in productions mode on errors.

In my opinion failing on the first error isn't the best solution. I think it's better to get a list of all errors of the build.

**Comment by gaearon** [comment]
Fair enough! Yeah, I was mostly puzzled by the fact that it still emits files. Sounds like this is solved then, thanks!
