### ISSUE TITLE
(feature) load the same file with different rule sets without inline loaders

### ISSUE THREAD

**Issue by plexigras** [webpack/webpack#6344]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
you need to use `import Styles from 'style-loader!css-loader?modules!./styles.css';`

~~**If the current behavior is a bug, please provide the steps to reproduce.**~~

**What is the expected behavior?**
i would like to be able to load the same kind of file with different rule sets defined in the config

pseudo code exampe:
`import Styles from './styles.css' as 'css-module'`

and then you have the rules for `css-module` in `webpack.config.js`

**If this is a feature request, what is motivation or use case for changing the behavior?**
i don't like having loader configuration in the source code

~~**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**~~

**Comment by ooflorent** [comment]
> i don't like having loader configuration in the source code

What you’re proposing is not valid JavaScript syntax so webpack can’t handle it.

**Comment by plexigras** [comment]
i don't understand, pseudo code is by definition not valid?

**Comment by ooflorent** [comment]
Absolutely. That’s why there is not pseudo code in webpack but comment directives and runtime.

**Comment by plexigras** [comment]
this is infuriating you do understand that i don't want to have non valid js to work right?

https://en.wikipedia.org/wiki/Pseudocode

**Comment by ooflorent** [comment]
Let me clarify my answer.

Webpack can't parse invalid JavaScript. Its parser walks the AST (defined by ESTree) and emits events on interesting nodes such as `require` calls or `import` / `export` statements. If you want to specify loaders or instrument the code, it must done using JavaScript valid code.

To achieve this webpack chose to add metadata into the import source (or required path) to control the loaders. That's not the sole instrumentation done. Some bindings are evaluated at parse time to replace the original code.

If the current loader syntax does not fit your needs, feel free to propose something else. I was just saying that the following couldn't be implemented:

```js
import Styles from './styles.css' as 'css-module'
                                  ^^ SyntaxError: Unexpected identifier
```

**Comment by plexigras** [comment]
pseudo code is not computer readable and not intended to be.

> Pseudocode is an informal high-level description of the operating principle of a computer program or other algorithm.

> It uses the structural conventions of a normal programming language, but is intended for human reading rather than machine reading. Pseudocode typically omits details that are essential for machine understanding of the algorithm, such as variable declarations, system-specific code and some subroutines. The programming language is augmented with natural language description details, where convenient, or with compact mathematical notation. The purpose of using pseudocode is that it is easier for people to understand than conventional programming language code, and that it is an efficient and environment-independent description of the key principles of an algorithm. It is commonly used in textbooks and scientific publications that are documenting various algorithms, and also in planning of computer program development, for sketching out the structure of the program before the actual coding takes place.

**Comment by TheLarkInn** [comment]
@plexigras, this is something that wouldn't be possible currently in webpack or for the future module type architecture. However you maybe could accomplish this in some way through a loader, but it may not give you what you are looking to accomplish. 

However, what I would highly encourage is taking a look at the current architecture we have in the source code, and if you provide some nice context, and justifications (via an RFC), we would definitely promise to carefully consider it.

**Comment by plexigras** [comment]
https://webpack.js.org/configuration/module/#rule-resourcequery is what was looking for
