### ISSUE TITLE
webpack 怎么实现api的url可配置

### ISSUE THREAD

**Issue by walidream** [webpack/webpack#6351]
我现在有这样一种需求，在src中我定义api.json的文件 `{"ip":192.168.1.1,"prot":8888}` ,然后我在其他js文件中import导入这个api.json文件，可以正常工作。
但是当我打包好了放在服务器上，由于服务器老出现问题，只需要更改 ip地址，不需要每次生成dist目录，请问我应该怎么配置webpack

**Comment by vok123** [comment]
1. 后台提供均衡负载?
2. 把接口文件写成一个js, 用window挂载api地址, 对应读取api地址也在window上取, 最后在html文件里面引用这个文件即可. 这个文件可以放cdn上, 或者放项目目录

**Comment by sokra** [comment]
Please use english here
