### ISSUE TITLE
Dynamic import react component not working with webpack3

### ISSUE THREAD

**Issue by nontachaiwebdev** [webpack/webpack#6366]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
I try to use dynamic import to code splitting react component but i found this problem
```__webpack_require__(...) is not a function``` 
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
I want to import react component success.
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by nontachaiwebdev** [comment]
Thankyou for fast reply. This is my code.

route.js
```
import asyncComponent from 'components/AsyncComponent'
const AsyncAppScreen = asyncComponent(() => import('screens/App').then(module => module.default))
const Routes = (
  <Route path='/' component={AsyncAppScreen} />
```

AsyncComponent.js
```
import React, { Component } from 'react'

export default function asyncComponent (importComponent) {
  class AsyncComponent extends Component {
    constructor (props) {
      super(props)
      this.state = {
        component: null
      }
    }

    async componentDidMount () {
      try {
        console.log('Before Dynamic Import')
       /*--- code break down here ---*/
        let template = importComponent().then(component => console.log(component))
        console.log(template)
      } catch (err) {
        console.error('template error')
        return new Error(err)
      }
      const component = null
      console.log('After dynamic import')
      this.setState({
        component: component
      })
    }

    render () {
      // const C = this.state.component
      return (
        <div>xxx</div>
      )
    }
  }

  return AsyncComponent
}
```
this is error message
```
Uncaught (in promise) TypeError: Cannot read property 'call' of undefined
```

thankyou

**Comment by dangodev** [comment]
@nontachaiwebdev do you have Babel enabled, `babel-plugin-syntax-dynamic-import` installed, and configured to use that plugin?

If you have, then it’s an error in that higher-order component you made. Try something like [react-loadable](https://github.com/thejameskyle/react-loadable) that handles this for you.

Dynamic imports work just fine in React with webpack 3; there are hundreds of projects using it, a few of which I‘ve made.

**Comment by Rody-Kirwan** [comment]
@nontachaiwebdev Have you solved this?
I am having a very similar issue using the following:
```
loader: (router) => import('../components/pages/home').then(component => {

      console.log(component)
      debugger;
      return router(component.default)
}
```

component = `{HomePage: undefined, __esModule: true}`

When I include a static import of the same module at the top of the file the component is defined.

I am using babel-plugin-syntax-dynamic-import

**Comment by elonybear** [comment]
Hey folks, @ooflorent  I realize this is closed but I have a similar issue in webpack 4.
Here's the repo: https://github.com/elonybear/social-attitudes
Currently all props being passed into dynamically imported components are non-existent (not getting passed in). 
Here's the critical piece of code: https://github.com/elonybear/social-attitudes/blob/master/src/components/App/Base.js#L25
I don't do dynamic imports anywhere else.

**Comment by ooflorent** [comment]
@elonybear The problem lives in your `Async` component. Not related to webpack.
