### ISSUE TITLE
[Feature Request] Include output path in webpack stats object

### ISSUE THREAD

**Issue by franjohn21** [webpack/webpack#6373]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
The webpack stats object does not include the output path.

When using a tool like [webpack-bundle-analyzer](https://www.npmjs.com/package/webpack-bundle-analyzer), it requires a second option to pass the webpack output path. Ideally the stats file already contained this path and was able to be parsed by such tools so a sane default could be obtained from the stats file. 

**What is the expected behavior?**
Emitting a stats file, either via the `--json` flag or via a tool such as [webpack-stats-plugin](https://github.com/FormidableLabs/webpack-stats-plugin) includes webpack's output path.

**If this is a feature request, what is motivation or use case for changing the behavior?**
The motivation for this is that we are designing a command line tool for doing analysis on emitted JS and CSS files from a webpack stats file and the interface would be a bit simpler if there was an output path that could be used as a default.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Using webpack@3.10.0

Happy to submit a PR if we agree this makes sense.

**Comment by sokra** [comment]
Send a PR.

**Comment by TheLarkInn** [comment]
This has landed. Thanks @franjohn21 for your contribution 🙇 🙇 🙇 🙇 🙇 🙇 🙇 🙇
