### ISSUE TITLE
Webpack's CLI parses numbers too aggressively

### ISSUE THREAD

**Issue by boxmein** [webpack/webpack#6376]
**Do you want to request a *feature* or report a *bug*?**

I would like to report a bug. I'm using webpack@3.10.0 without any loaders or plugins. (see [the Gist link](https://gist.github.com/boxmein/51948f5634ac2178712f2947c95e4f90))

**What is the current behavior?**

Webpack's command line parses environment arguments into numbers (because yargs does). This causes issues with passing short commit IDs into Webpack, since there is a chance they look like a number to yargs.

**If the current behavior is a bug, please provide the steps to reproduce.**

[Here's the webpack config and three commands to verify the command line's behaviour.](https://gist.github.com/boxmein/51948f5634ac2178712f2947c95e4f90)

**What is the expected behavior?**

The expected behaviour is that all environment arguments are strings at first, and can be parsed into integers by the developers.

Alternatively, the expected behaviour is some ability to tell which type the config file expects an environment variable to be, conditionally turning off yargs parsing as needed.

**If this is a feature request, what is motivation or use case for changing the behavior?**

This is a change request, the motivation of which is avoiding nasty surprises in production builds. Additionally, this is undocumented behaviour. 

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Node version: v8.6.0
OS: macOS 10.13.2
Webpack version: 3.10.0

**Comment by sokra** [comment]
We can't control this behavior since it's controlled by yargs. You can report it there, but that probably neither helps.

Since it's pretty edge-case-y I would recommend working around it by prefixing something to the commit: i.e. `--env.commit sha:12354e2` and removing it in the configuration.

**Comment by boxmein** [comment]
This behavior can be controlled by yargs config options though - I can submit a PR tomorrow.
