### ISSUE TITLE
Invalid less generated 

### ISSUE THREAD

**Issue by benoj** [webpack/webpack#6383]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**
Less fails to build correctly?

```
Module build failed:

module.exports = __webpack_public_path__ + "static/media/semantic.d6f6ac40.less";
             ^
Unrecognised input
      in /Users/benflowers/Projects/candidate/candidate-ui-cra/node_modules/semantic-ui-less/semantic.less (line 1, column 15)
```
**If the current behavior is a bug, please provide the steps to reproduce.**

My webpack config:
https://gist.github.com/benoj/908f20a64066ca8606733c36206bccdd

I have been following the tutorial here to import semantic-ui-less into my webpack project https://medium.com/webmonkeys/webpack-2-semantic-ui-theming-a216ddf60daf

Although i suspect this is to do with less in general rather than being anything to with semantic-ui

**What is the expected behavior?**

Webpack builds the less file from semantic-ui-less

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

webpack: 3.8.1
node: 8.5.0
os: MacOS Sierra

**Comment by TheLarkInn** [comment]
Best bet would be to start by verifying this is an issue with [less-loader](https://github.com/webpack-contrib/less-loader) first. Would you mind submitting this there and tagging me in it.
