### ISSUE TITLE
Make require-ensure plugin append jsonp-scripts to body instead of head

### ISSUE THREAD

**Issue by kanzelm3** [webpack/webpack#6385]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

When dynamically imported scripts are loaded via JSONP, they are appended to the head of the document. See https://github.com/webpack/webpack/blob/master/lib/JsonpMainTemplatePlugin.js#L106 for code that drives this behavior.

**What is the expected behavior?**

It would be great if scripts loaded via JSONP could instead be appended to the body of the document.

**If this is a feature request, what is motivation or use case for changing the behavior?**

Many sites place scripts at the end of the body so that the browser can render all of the html before it starts parsing the JS files for the site. There is a growing base of users who use tools such as react-snapshot to prerender their react SPA to generate an html snapshot that is used as an app shell to get meaningful content on the page faster for the user. The problem with appending scripts to the head is that when react-snapshot crawls the site, and snapshots it once the dynamic chunks for the page have loaded, the dynamic chunk script tags are in the head of the document, whereas the main app bundle is at the end of the body. This leads to the error `Uncaught ReferenceError: webpackJsonp is not defined` being thrown since the browser tries to parse the chunk file before the main bundle.

I realize this can be solved simply by moving the main app bundle into the head, but I don't think this is sufficient, as the script now blocks the page from rendering. So I think the better solution is to simply append chunk script tags to the end of the body.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Tested with latest webpack version

**Comment by TheLarkInn** [comment]
@kanzelm3 I spoke with @hulkish about this personally and I'll express the same concerns:

`<scripts>` loaded into the head will gain blocking parse, load, and eval priority, so lazy loaded chunks would ideally _need_ (for the fastest lazy-load), to be added into the `<head>`. 

That being said, you could technically write a plugin to do this by tapping into the "require-ensure" hook of the `MainTemplate`. Or you can write a few template instances and apply them using [this target option](https://webpack.js.org/configuration/target/#function)

Also, we maybe would consider a PR for this to add a new `ssr-web` target, however I'd recommend you implement the local version using the "target as function type" API first to see if it solves your needs.

**Comment by kanzelm3** [comment]
@TheLarkInn so for example, you are saying that if my main bundle is in the head and it lazy loads script b, you want to ensure it gets blocking priority over the rest of the content on the page? I think that makes sense.

I will look into other options, but I wonder if there is a way to always have the lazy loaded chunk scripts be placed after the entry chunk.

Theoretically, lazy loaded chunks will never be added to the DOM until the browser has finished parsing the main entry chunk, so if `require-ensure` always injected scripts after the entry chunk, it should solve your concern while also solving the problem I am running into.
