### ISSUE TITLE
What does 'Chunks' mean in CLI output?

### ISSUE THREAD

**Issue by wzup** [webpack/webpack#6387]
Command I run:
```
$ webpack --config webpack.config.js -p --progress
```

This is the result I get. What does `chunks` mean? Why sometimes they are change?
If I understand it right, the more chunks the better. But I can't see same amount of files. If I have 0-1-2 chunks in every entry point, where are chunks' files then? I have only entry points

Many
![wp_chunks](https://user-images.githubusercontent.com/3880497/35434589-61563d20-0290-11e8-97f5-fe21670bffc4.png)

Singles
![wp_chunks-0](https://user-images.githubusercontent.com/3880497/35434675-9e810252-0290-11e8-9bca-ceebe4a5db73.png)

My WP config:
```javascript
module.exports = {
    context: path.resolve(__dirname, '..'),
    entry: {
        index: 'index.wp',
        home: 'home.wp',
        vendors: [
            'react',
            'react-dom',
            'querystring',
            'react-router',
        ]
    },
    output: {
        path: path.resolve(__dirname, '_distro_'),
        publicPath: '/',
        filename: '[name].[chunkhash:5].js',
        pathinfo: true,
        chunkFilename: 'chunk-[name].[chunkhash].js'
    },
    plugins: [
        new webpack.optimize.CommonsChunkPlugin({
            names: ["vendors", 'index', 'home'],
            minChunks: 1 // << I play with this value and # of chunks change
        }),
    ],
}
```

SO https://stackoverflow.com/questions/48459234/what-does-chunks-mean-in-cli-output

**Comment by TheLarkInn** [comment]
Answered the q on SO.
