### ISSUE TITLE
e

### ISSUE THREAD

**Issue by noahleigh** [webpack/webpack#6388]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by jakelacey2012** [comment]
@noahleigh did you mean to create this? Has no details so should be closed!

**Comment by evilebottnawi** [comment]
@noahleigh if you have issue with webpack please recreate issue using template, thanks!

**Comment by noahleigh** [comment]
@jakelacey2012 um, somehow my browser had focus instead of my editor, and a serendipitous series of keystrokes created this issue and submitted it? I didn't think this had actually been posted...

**Comment by evilebottnawi** [comment]
@noahleigh don't worry
