### ISSUE TITLE
Combining require.ensure with a dynamic require

### ISSUE THREAD

**Issue by KidkArolis** [webpack/webpack#639]
I've finally found one possible solution to configuring how chunks should be created for my app, it looks something like this:

``` js
resolvers.index = function(name, cb) {
  require.ensure([
    "app/modules/foo/routes/a",
    "app/modules/foo/routes/b",
    "app/modules/foo/routes/c"
  ], function (require) {
    cb(require("app/modules/foo/routes/" + name));
  }, "index");
};

resolvers.review = function(name, cb) {
  require.ensure([
    "app/modules/foo/routes/d",
    "app/modules/foo/routes/e"
  ], function (require) {
    cb(require("app/modules/foo/routes/" + name));
  }, "review");
};
```

Here, the router will call `resolvers.index("a")`, `resolvers.index("b")` or `resolvers.review("e")`, etc. whenever it wants to load that page. `require.ensure` makes sure a named chunk is created for each group of routes. This is exactly what I want.

However, in the callback I need to require a specific route by name. Unfortunately `require("app/modules/foo/routes/" + name)` creates a dynamic context and forces everything into that chunk. So instead of having chunks "index" and "review", I get a chunk "index" with all of the routes in it. Any suggestions?

**Comment by alexsandro-xpt** [comment]
Webpack build should be have something like "build in memory/var script" to run extra requires.
