### ISSUE TITLE
Link to legacy Webpack 1 docs for people stuck in legacy land

### ISSUE THREAD

**Issue by eteeselink** [webpack/webpack#6390]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**

When I google for a problem in a legacy webpack 1 setup, I might end up on pages like this: https://webpack.github.io/docs/using-plugins, which currently shows nothing but

![image](https://user-images.githubusercontent.com/703546/35457829-859c2a92-02da-11e8-85cf-bdd41e8769d5.png)

and then redirects to the webpack 2 docs. In effect, this is telling people stuck on Webpack 1 for all kinds of realistic reasons to first try to upgrade to webpack 2 before they're even allowed to read docs. Especially if the *current* situation does not work this can be frustrating, because it's scary to try to upgrade something that doesn't work - did I just break it while upgrading or was it already broken? 

This feels very user-hostile. Webpack has been popular long enough that there are many codebases out there, open and closed, that use Webpack but aren't as actively maintained as they used to be. Having to do many steps before you can even make small fixes in the build setup can be a real blocker to making progress, and I can imagine many cases where it would be far preferable to get things up and running again, get the project to regain some momentum, and only *then* upgrade the build tooling.

**What is the expected behavior?**

I'd expect there to be some way for users to be able to find the Webpack 1 docs back, even though the Webpack 2+ docs are better. I learned from @TheLarkInn on HN that the old Webpack 1 docs are still available in the wiki: I'd suggest to disable the automatic redirect on the old webpack.github.io URLs, plus add a small link to those dead pages to the appropriate site in the wiki.

Similarly I'd leave a few notes here and there in the new webpack docs, which have finally started "winning" on Google recently (probably thanks to the very pages I'm complaining about here), along the lines of "these docs are for Webpack versions 2 and up. If you're stuck on Webpack 1 and can't upgrade, the old Webpack 1 docs are available \_here\_".

**Comment by TheLarkInn** [comment]
For the work needed here. Let's just have a note near "Support" section of our README. I'm going to mark this as a first-time contribution opportunity for anyone who would like to grab it. 

TODO: 
- [ ] Add link to webpack 1 docs in wiki in support section of README in webpack/webpack repo
- [ ] Open issue in webpack/webpack.js.org to explore the _right_ location to link back to wiki from new docs page.

**Comment by abiduzz420** [comment]
@TheLarkInn Hi, I would like to work on this issue. This would be my first contribution to webpack.

**Comment by TheLarkInn** [comment]
Great! The check boxes above in the issue should give you guidance on where to start, ping me for any questions.

**Comment by s1iqbal** [comment]
Done tackling the problem!

**Comment by iFlameing** [comment]
@TheLarkInn  I just made a pull request on " Add link to webpack 1 docs in wiki in support section of README in webpack/webpack repo:   is this ok or I have to add more information.

**Comment by ArwaLokhandwala** [comment]
@TheLarkInn I am first time contributor. Just wanted to know is the second issue in the checklist still open for contribution. I would love to work on it.

**Comment by BeniCheni** [comment]
Hi dear maintainer(s), I've taken a stab at this issue about _Webpack 1_ doc with #7286 to give my "_1st-timer_" PR an attempt at a small update such as a doc change. 🙏 in advance for your time reviewing.
