### ISSUE TITLE
[FR] Warn when plugins are duplicated

### ISSUE THREAD

**Issue by probablyup** [webpack/webpack#6399]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
There is no warning if two or more instances of the same plugin are applied.

**If the current behavior is a bug, please provide the steps to reproduce.**
n/a

**What is the expected behavior?**
A warning should be emitted for each plugin that is duplicated, featuring the name of the plugin.

**If this is a feature request, what is motivation or use case for changing the behavior?**
I noticed [@ooflorent's comment](https://github.com/webpack/webpack/pull/6395#issuecomment-360980992) and figured it probably would be possible to add a dev-time warning to aid in avoiding plugin clashes.

**Comment by ooflorent** [comment]
Duplicates #5363
