### ISSUE TITLE
ModuleConcatenationPlugin throws on array default exports with functions

### ISSUE THREAD

**Issue by filipesilva** [webpack/webpack#6407]
**Do you want to request a *feature* or report a *bug*?**
I want to report a bug.

**What is the current behavior?**
`webpack.optimize.ModuleConcatenationPlugin()` throws `Cannot read property 'range' of null` when two modules are imported that:
- declare a function with the same name
- declare a default export
- the default export is an array with empty (not undefined) elements

For instance, this will break:
```
function foo(n) {
  return 'bar';
}
export default [, foo];
```

But this is fine:
```
function foo(n) {
  return 'bar';
}
export default [undefined, foo];
```

**If the current behavior is a bug, please provide the steps to reproduce.**

I have a minimal repro at https://github.com/filipesilva/webpack-default-exports-concat that depends only on webpack.

```
git clone https://github.com/filipesilva/webpack-default-exports-concat
cd webpack-default-exports-concat
npm i
npm test
```

**What is the expected behavior?**
```
$ npm test

> webpack-default-exports@1.0.0 test D:\sandbox\webpack-default-exports
> webpack

Hash: 677662c2dee177954e76
Version: webpack 3.10.0
Time: 79ms
   [0] ./main.js + 2 modules 274 bytes {0} [built]

ERROR in chunk main [entry]
bundle.js
Cannot read property 'range' of null
npm ERR! Test failed.  See above for more details.
```

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
No browser, node v8.9.1, webpack 3.10.0, Windows 10

Related to https://github.com/angular/angular/issues/21809, https://github.com/webpack/webpack/issues/5415.

**Comment by filipesilva** [comment]
This bug also exists with `webpack@4.0.0-beta.0`:
```
$ npm test

> webpack-default-exports@1.0.0 test D:\sandbox\webpack-default-exports
> webpack

(node:3352) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
Hash: 82ba7dd94993235c3dd2
Version: webpack 4.0.0-beta.0
Time: 105ms
Entrypoint main =
   [0] ./main.js + 2 modules 274 bytes {0} [built]
       | ./main.js 76 bytes [built]
       | ./import-one.js 99 bytes [built]
       | ./import-two.js 99 bytes [built]

WARNING in configuration
The 'mode' option has not been set. Set 'mode' option to 'development' or 'production' to enable defaults for this environment.

ERROR in chunk main [entry]
bundle.js
Cannot read property 'range' of null
npm ERR! Test failed.  See above for more details.
```

**Comment by sokra** [comment]
yep seem to be a bug

**Comment by ocombe** [comment]
This is unfortunate as we have these conditions in Angular right now. We can change the code on our side, if this is bug not going to be resolved anytime soon (I would understand that it gets low priority given that it happens in very odd conditions).

**Comment by sokra** [comment]
As workaround you can disable module concatenation until this is resolved:

``` js
optimization.concatenateModules: false
```

**Comment by sokra** [comment]
But seem to be easy to fix

**Comment by sokra** [comment]
I guess: Insert a `if(!n) return undefined;` here https://github.com/webpack/webpack/blob/3972d9ae734a0b65725e6237e8a221d5e320fd51/lib/optimize/ConcatenatedModule.js#L146

**Comment by ocombe** [comment]
Yes it works, I'll make a PR then!

**Comment by ocombe** [comment]
Where should I add a test? You have like 2k test files :D

**Comment by sokra** [comment]
`test/cases/scope-hoisting`

**Comment by ocombe** [comment]
PR sent :) https://github.com/webpack/webpack/pull/6408
