### ISSUE TITLE
TypeError: webpack.optimize.UglifyJsPlugin is not a constructor

### ISSUE THREAD

**Issue by bfred-it** [webpack/webpack#6409]
This is in **`webpack@4.0.0-beta.0`**

**Do you want to request a *feature* or report a *bug*?**

**bug**

**What is the current behavior?**

```
TypeError: webpack.optimize.UglifyJsPlugin is not a constructor
```

**If the current behavior is a bug, please provide the steps to reproduce.**

```js
const webpack = require('webpack');
new webpack.optimize.UglifyJsPlugin()
```

Also:

```sh
$ npm i webpack@4.0.0-beta.0
$ node -e 'console.log(require("webpack").optimize)'

{ AggressiveMergingPlugin: [Getter],
  AggressiveSplittingPlugin: [Getter],
  ChunkModuleIdRangePlugin: [Getter],
  LimitChunkCountPlugin: [Getter],
  MinChunkSizePlugin: [Getter],
  ModuleConcatenationPlugin: [Getter],
  OccurrenceOrderPlugin: [Getter],
  RuntimeChunkPlugin: [Getter],
  SideEffectsFlagPlugin: [Getter],
  SplitChunksPlugin: [Getter] }
```

**What is the expected behavior?**

`webpack.optimize.UglifyJsPlugin === function`

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

❯ node v8.6.0
❯ npm 5.6.0
❯ webpack 4.0.0-beta.0

**Comment by michael-ciniawsky** [comment]
`CommonChunksPlugin` (removed) && `UglifyJsPlugin` aren't exposed as plugins anymore since `webpack@v4.0.0-beta.0`, use `config.optimization.splitChunks && config.optimization.minimize` instead please

**Comment by bfred-it** [comment]
Any docs available for those two?

**Comment by swarajgiri** [comment]
@bfred-it - https://gist.github.com/sokra/1522d586b8e5c0f5072d7565c2bee693

```
optimization: {
    minimize: true,
    runtimeChunk: true,
    splitChunks: {
        chunks: "async",
        minSize: 1000,
        minChunks: 2,
        maxAsyncRequests: 5,
        maxInitialRequests: 3,
        name: true,
        cacheGroups: {
            default: {
                minChunks: 1,
                priority: -20,
                reuseExistingChunk: true,
            },
            vendors: {
                test: /[\\/]node_modules[\\/]/,
                priority: -10
            }
        }
    }
}
```

**Comment by bfred-it** [comment]
Thanks! Is it possible to configure the minification as well?

**Comment by ooflorent** [comment]
@bfred-it yes. Set `optimization.minimize` to `false`, add `uglifyjs-webpack-plugin` to your project deps. Use this one instead of webpack’s builtin.

**Comment by NekR** [comment]
Now it's even more confusing. What exactly minimize option is doing then?

**Comment by ooflorent** [comment]
When `mode` is `production` or not defined, `minimize` is enabled. This option automatically adds Uglify plugin. If you want to add your own setup, you should set `minimize` to `false` to avoid double minification.

**Comment by NekR** [comment]
Totally confusing again. So right now anyone who uses Uglify plugin has
double minification?

**Comment by bfred-it** [comment]
If you set `minimize: false` you won’t have double minification. 

What I don’t understand is why not make `minimize` accept a `uglifyjs-webpack-plugin` config object.

**Comment by ooflorent** [comment]
Because `minimize` tells webpack to use `optimization.minimizer` to create the minification plugin. Currently it creates uglify’s one but one could set it to closure or babili.

**Comment by ooflorent** [comment]
But sure, minimize could also accept an object and pass it to minimizer. What do you think about this @sokra?

**Comment by evilebottnawi** [comment]
@ooflorent should accept, otherwise, how to configure uglify plugin?

**Comment by benthemonkey** [comment]
I could be mistaken, but if you look at https://github.com/webpack/webpack/blob/next/lib/WebpackOptionsApply.js#L306, you'll see that if `optimization.minimize = true`, then webpack just takes the array of plugins from `optimization.minimizer` (e.g. `optimization.minimizer = [new UglifyJSPlugin(your options)]`) and applies it to the compiler. So I think that's how you should configure the uglify plugin.

**Comment by backflip** [comment]
@benthemonkey, there seem to be issues with the config validation when doing this. Example:
```js
optimization: {
  minimizer: new UglifyJSPlugin({
    mangle: {
      keep_fnames: true,
    },
  }),
}
```

This triggers the following error for me: 
```
schema-utils/dist/validateOptions.js:49
    throw new _ValidationError2.default(ajv.errors, name);
    ^

ValidationError: UglifyJs Plugin Invalid Options

options['mangle'] should NOT have additional properties
```

**Comment by evilebottnawi** [comment]
@backflip ?
```js
optimization: {
  minimizer: {
    mangle: {
      keep_fnames: true,
    },
  },
},
```

**Comment by backflip** [comment]
I was using on outdated structure, the config needs to be wrapped with `uglifyOptions`:
```js
optimization: {
  minimizer: [
    new UglifyJSPlugin({
      uglifyOptions: {
        mangle: {
          keep_fnames: true,
        },
      },
    }),
  ],
},
```

Sorry for spamming.

**Comment by Vnthf** [comment]
@backflip But treeshaking not work anymore if I use minimizer option. I think unused option not work in webpack4. right?

**Comment by ooflorent** [comment]
`webpack.optimize.UglifyJsPlugin` is gone in webpack 4.

Now you must load the plugin:

```js
const UglifyJsPlugin = require("uglifyjs-webpack-plugin");
```

And register it:

```js
optimization.minimizer = [new UglifyJSPlugin(…)]
```

**Comment by grig0ry** [comment]
@ooflorent If my configuration is in another package, @evilebottnawi variant is more convenient. There is no need to add uglifyjs-webpack-plugin in dependencies.

**Comment by D19cannon** [comment]
Hi guys, Sorry for coming back to this topic, but I have tried a billion ways now to get the UglyJsPlugin running. All I get i the same error over and over again. Any thoughts what I might be doing wrong here?

const UglifyJsPlugin = require("uglifyjs-webpack-plugin");

module.exports = {
  mode: "production",
  optimization: {
    minimizer: [
      new UglifyJSPlugin({
        sourceMap: true,
        ecma: 5,
        warnings: false,
        ie8: false,
        safari10: false,
        dead_code: true,
        comments: false,
        uglifyOptions: {
          compress: {
            inline: false
          }
        }
      })
    ]
  },
...
};

**Comment by evilebottnawi** [comment]
@D19cannon what error you are got?

**Comment by D19cannon** [comment]
@evilebottnawi ReferenceError: UglifyJSPlugin is not defined

Error doesn't make any sense to me. As you can see I have the require() and with an extension in VScode I can see that 733.3k has been imported.

Any ideas?

**Comment by evilebottnawi** [comment]
You need add `const UglifyJsPlugin = require('uglifyjs-webpack-plugin')` in your config file

**Comment by D19cannon** [comment]
@evilebottnawi Yes I understand, but as I mentioned in my first message. It is there, but I still receive this error.

**Comment by D19cannon** [comment]
<img width="981" alt="screen shot 2018-07-23 at 14 06 17" src="https://user-images.githubusercontent.com/14916043/43073288-ab900e66-8e81-11e8-8c4f-f68a7d6b63d2.png">

**Comment by evilebottnawi** [comment]
@D19cannon seriously? You use `const UglifyJsPlugin = require('uglifyjs-webpack-plugin')` in top, but in `minimizer` option you use `UglifyJSPlugin`. Looks on `s` in plugin  name (first example with lowercase, second in UPPERCASE)

**Comment by danchristian** [comment]
Tripped up on this too, thanks!

**Comment by KevinPan** [comment]
And first of all, you need to install the package
npm install uglifyjs-webpack-plugin --save-dev
