### ISSUE TITLE
Feature: Add API to work with webpack configs

### ISSUE THREAD

**Issue by mdreizin** [webpack/webpack#641]
In some cases when you have a lot of webpack configs it would be very useful if webpack core has API which helps to work with these configs (load/extend/find closest config/etc).

Currently as I can see it is not possible and I have created my own API and you can find it [here](https://github.com/mdreizin/webpack-config).

Also I have create `gulp` [plugin](https://github.com/mdreizin/gulp-webpack-build) which uses that API and it helps to find all configs and compile them.

Have you any plans to add these features in nearest release? If yes, I can help you with these.

**Comment by mdreizin** [comment]
Currently you can use this feature via [webpack-config](https://github.com/mdreizin/webpack-config).

**Comment by bebraw** [comment]
@mdreizin I developed a simple solution known as [webpack-merge](https://www.npmjs.com/package/webpack-merge) that gets to the core of the issue. It works quite well for small configurations. Most importantly it allows you to maintain it all within a single file while allowing you to split it up and share bits as you want.

**Comment by mdreizin** [comment]
@bebraw Thanks. Have you had a chance to try [webpack-config](https://github.com/mdreizin/webpack-config)? It has been develop to cover a lot of cases and `merge` is one of them. Also please look at https://github.com/webpack/webpack/pull/1491.

**Comment by bebraw** [comment]
@mdreizin Not yet. I'm fairly strictly in "one module for configuration" camp (Make influence?). But it's nice to have alternative solutions around. :+1:

**Comment by bebraw** [comment]
@mdreizin Any idea what to do with this issue? Given the original PR was closed by Tobias, I guess this isn't going to happen in the core at least. This doesn't mean we cannot solve the problem outside the core as evidenced by our little projects: :smile:

**Comment by sokra** [comment]
This should happen in 3rd-party-libraries not in webpack core itself
