### ISSUE TITLE
Expose webpack version in the `compiler` object passed to plugins

### ISSUE THREAD

**Issue by jeffposnick** [webpack/webpack#6411]
**Do you want to request a *feature* or report a *bug*?**
*feature*

**What is the current behavior?**
When writing a plugin whose goal is compatibility with both the legacy and webpack v4 plugin system, it's something of a manual process to determine which version of webpack we're running under. It would likely involve loading the `webpack/package.json` that applies to the current compilation, and interpreting the data from there. 

**If the current behavior is a bug, please provide the steps to reproduce.**
n/a

**What is the expected behavior?**
It would be much cleaner if the webpack version were exposed as a property of the `compiler` object, and passed through to plugins. The plugin would still need to know how to do semver comparisons, but at least it wouldn't also need to know how to find the right `package.json` and parse it.

**If this is a feature request, what is motivation or use case for changing the behavior?**
See https://github.com/GoogleChrome/workbox/issues/1151#issuecomment-360964776 for more context.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
webpack v4

**Comment by sokra** [comment]
Sounds useful, feel free to send a PR which exposes the version as property on the compiler object.

But in general you should use feature detection instead of version testing:

i. e. use `if(compiler.hooks)` instead of `if(compiler.version >= 4)`

**Comment by jeffposnick** [comment]
I'd rather do feature detection: https://github.com/GoogleChrome/workbox/issues/1151#issuecomment-360904727

@TheLarkInn suggested version detection instead: https://github.com/GoogleChrome/workbox/issues/1151#issuecomment-360964776

Is `if ('hooks' in compiler) {...}` sufficient for feature checking, or is there something better or additional that we'd need to check for?

**Comment by ooflorent** [comment]
@jeffposnick should be enough.

**Comment by sokra** [comment]
yep

**Comment by jeffposnick** [comment]
Thanks! 👍

**Comment by TheLarkInn** [comment]
🙇
