### ISSUE TITLE
[v4] Duplication between split chunks

### ISSUE THREAD

**Issue by joshjg** [webpack/webpack#6413]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
A bunch of async child chunks in my application require a common dependency (which lives within my repo). The common dependency also has its own 3rd party dependencies (in node_modules). Webpack creates two output chunks which **both** include the 3rd party dependencies:
* childA\~childB\~childC
* vendors\~childA\~childB\~childC

**If the current behavior is a bug, please provide the steps to reproduce.**
* Use default chunk-splitting behavior
* Have several async child chunks
* Have a large common 1st party (non-node_modules) dependency between those chunks
* 1st party common dependency has large 3rd party dependencies

**What is the expected behavior?**
The 3rd party code should only be present in one chunk, not both.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Webpack: v4.0.0-beta.0
Node: 8.x

**Comment by TheLarkInn** [comment]
@joshjg can you confirm that #6432 fixes your issue? 

Just want to confirm and track.

**Comment by joshjg** [comment]
@TheLarkInn @sokra Confirmed the fix

**Comment by TheLarkInn** [comment]
Appreciate you taking the time to test this.

**Comment by billyvg** [comment]
Is it possible this is also present in 3.x?

**Comment by sokra** [comment]
@billyvg no, splitChunks was added in v4
