### ISSUE TITLE
Chunking / lazy-loading doesn't split out exports that are in the same file

### ISSUE THREAD

**Issue by bluepnume** [webpack/webpack#6417]
**Do you want to request a *feature* or report a *bug*?**

Report a (potential?) bug

**What is the current behavior?**

Let's say I have the following file layout:

    // index.js

    import { foo } from './foo';
    import { bar } from './bar';

    foo();
    bar();

----

    // foo.js

    export function foo() {
        console.log('foo');

        import('./bar').then(res => {
            res.baz();
        });
    }

----

    // bar.js

    export function bar() {
        console.log('bar');
    }

    export function baz() {
        console.log('baz');
    }

----

So, what I was expecting to happen here is for webpack to generate two chunks:

- main: `foo` and `bar` functions
- chunk.1: `baz` function

Since, for all intents and purposes, `baz` is a lazy dependency, and it's only ever used lazily.

But the only way I can get webpack to split out `baz` is to put `baz` into its own `baz.js` file and `import('./baz')`.

So with the current behavior, seems like the only way I can guarantee good chunking is to put each export in its own individual file. But that doesn't seem very optimal to me.

**If the current behavior is a bug, please provide the steps to reproduce.**

(Please see code example above)

**What is the expected behavior?**

I would expect webpack to create chunks on an export-by-export basis, rather than on a file-by-file basis. In my actual case I have a large `util.js` file with a load of exports, and I was hoping to have webpack automatically split these up based on whether they're used as static or lazy dependencies.

**If this is a feature request, what is motivation or use case for changing the behavior?**

Users should not have to manually split up their exports into different files to take full advantage of chunking.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

- Node 6
- Webpack 3.10.0
- OSX

**Comment by TheLarkInn** [comment]
@sokra I could see this working if user in above example used destructure syntax in `import().then(({baz}) => {});` then we could statically determine the other export isn't used, etc. However I'm unaware what export function's do to this behavior. I also tested this with webpack 4 in the same manner. Probably a good test we should add no matter what the behavior is supposed to be.

**Comment by bluepnume** [comment]
@TheLarkInn -- I like the idea of webpack recognizing destructuring -- but that said, even if the lazy import doesn't use destructuring, webpack should still have enough information at compile time to know that `function baz` isn't statically imported anywhere -- so it can be pushed into a lazy chunk. Right?

**Comment by sokra** [comment]
It may be possible to do this in this example, but it's not in general true, because of two aspects:

* Ensure correct evaluation order according to spec
* Allow all exports to access a single scope

Example:

``` js
// bar.js
let counter = 0;
console.log('bar evaluated');

export function bar() {
    console.log('bar' + counter++);
}

export function baz() {
    console.log('baz' + counter++);
}
```

bar evaluated should only be printed once.

counter must be shared between bar and baz.

You could argue that it's still possible by moving `counter` into a new module, but this is getter complexer...

Nontheless it's would be a nice feature, could even be implemented in a loader.

**Comment by bluepnume** [comment]
> * Ensure correct evaluation order according to spec
> * Allow all exports to access a single scope

Totally makes sense. But that said -- it would be fairly straightforward to detect whether the functions are consuming any module-level variables, right? Each export could be marked pure/impure based on whether it depended on external state or execution order.

**Comment by TheLarkInn** [comment]
Would sideEffects be applicable here @sokra?

**Comment by bluepnume** [comment]
Still interested in a resolution for this one, if possible; it's a barrier to doing optimal code-splitting right now.
