### ISSUE TITLE
Import with wildcard not working

### ISSUE THREAD

**Issue by SassNinja** [webpack/webpack#6418]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Importing several files via wildcard is not working.
No matter if I use ES6 native `import './riot/tags/*.tag';` or `require.context('./riot/tags', false, /\.js$/);`
The only way that seems to work is importing without wildcards via `import './riot/tags/example.tag';`

**If the current behavior is a bug, please provide the steps to reproduce.**

I've got an app.js as bootstraper which imports all components and initializes them.
In my case it's the [riot](http://riotjs.com/) library.
```javascript
import riot from 'riot';
import './riot/tags/example.tag';
riot.mount('*');
```
I'm using gulp with the webpack package and the loaders babel & riot-tag
```javascript
import gulp from 'gulp';
import webpackStream from 'webpack-stream';
import webpack2 from 'webpack';
import named from 'vinyl-named';

let webpackConfig = {
    module: {
        rules: [
            { test: /.js$/, use: 'babel-loader' },
            { test: /.tag$/, use: 'riot-tag-loader' }
        ]
    }
};

gulp.src('./src/app.js')
    .pipe(named())
    .pipe(webpackStream(webpackConfig, webpack2))
    .pipe(gulp.dest('./dist/app.js'));
```

**What is the expected behavior?**

I expected that webpack resolves the import with wildcard correctly.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

- node v.8.6.0
- webpack v3.10.0
- macOS 10.13.2 (High Sierra)

**Comment by ooflorent** [comment]
I’m not sure if I correctly understand your issue. Are talking about this?

```js
import "./foo/*.js"

**Comment by SassNinja** [comment]
Yup @ooflorent that's exactly what I'm talking about.
I would like to avoid importing all files within a folder hard coded.

**Comment by SassNinja** [comment]
One additional note:
the files I'm importing in my example case (riot tag files) are no ES modules, meaning there's no `export ...` in it (don't know if this matters).
However `import "./foo/test.tag"` is working and `import "./foo/*.tag" not.

**Comment by ooflorent** [comment]
That’s the expected behavior. There is not issue here. `import` targets a file, not a glob match. If `*.js` is specified it means _“import the file named `*.js`”_.

**Comment by SassNinja** [comment]
Ok, I see, no issue.

But would you tell me how to achieve an import with glob match otherwise?
The right keywords would already help bcz I'm still new to webpack and haven't be able to find a solution yet.

**Comment by ooflorent** [comment]
Unfortunately there is no automatic solution. You have to manually import all files. You could also try to generate the file outside of webpack which imports all your tags and then import type from your app.

**Comment by SassNinja** [comment]
Ok thanks for the explanation. I really thought there has to be a way to use import with global match in webpack.
I think I'll precompile & concatenate the files via gulp then and import the output file.

**Comment by trullock** [comment]
would be lovely if wildcard globbing worked
