### ISSUE TITLE
[question] is there a plugin event for package change

### ISSUE THREAD

**Issue by maciej-ka** [webpack/webpack#6420]
I'm working on https://github.com/facebook/create-react-app/issues/2956 and would like to write a plugin, that will trigger a webpack rebuild whenever any package in node_modules is changed by `yarn upgrade`.

Is there an event that a plugin can subscribe to, that will notify about any file change inside `node_modules` (or just `package.json` of these modules)?

In `Compiler` source there is a line that may suggest it is an ["invalid" event](https://github.com/webpack/webpack/blob/master/lib/Compiler.js#L125) but manually changing a `package.json` in a started CRA app didn't end with a console log below:
```js
class WatchChangedNodeModulesPlugin {
  apply(compiler) {
    compiler.plugin('invalid', console.log);
  }
}
```

Warm Greetings!

**Comment by sokra** [comment]
webpack watches all dependencies including node_modules by default.

But CRA explicitly exclude node_modules from watching:

https://github.com/facebook/create-react-app/blob/5348d6eecf208a6298e48072314157804282002e/packages/react-scripts/config/webpackDevServer.config.js#L78-L80

**Comment by TheLarkInn** [comment]
Oh strange... 

Yeah thats a good starting place.

**Comment by sokra** [comment]
see also https://github.com/facebook/create-react-app/pull/294

**Comment by maciej-ka** [comment]
Thank you, these links are on spot!
