### ISSUE TITLE
webpack3/4 only emits files with 2 or more dynamically added entries

### ISSUE THREAD

**Issue by saboya** [webpack/webpack#6427]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
I'm currently writing a plugin that needs to dynamically add entries to webpack,

During `compiler.plugin('make'`(now `compiler.hooks.make.tapAsync('TestPlugin'`), I call `compiler.addEntry`, following [this instructions](https://github.com/webpack/docs/wiki/plugins#makec-compilation-parallel).

However, webpack only emit files if there are 2 or more entries in the bundle. Even if I add the same exact entry twice, it works, and only outputs 1 file.

**If the current behavior is a bug, please provide the steps to reproduce.**

I've written a simplified version of my plugin, along with a webpack config example. Considering the following file structure:

```
.
├── files
│   └── test.js
├── package.json
└── webpack.config.js
```
The plugin will read all files from `./files/` and add them to the bundle. The following code will work with webpack3 or webpack4:
```javascript
const fs = require('fs')
const path = require('path')
const SingleEntryPlugin = require('webpack/lib/SingleEntryPlugin')

class TestPlugin {
  constructor (options = {}) {
    this.options = options
  }

  apply (compiler) {
    const dir = path.resolve(compiler.context,this.options.dir)

    const make = (compilation, callback) => {
      fs.readdir(dir,(err, files) => {
        files.forEach(file => {
          let i = 0
          while (i++ < this.options.count) {
            compilation.addEntry(
              this.context,
              SingleEntryPlugin.createDependency(path.resolve(dir,file), file),
              path.basename(file,'.js'),
              callback,
            )
          }
        })
      })
    }

    if (compiler.hooks === undefined) {
      compiler.plugin('make', make)
    } else {
      compiler.hooks.make.tapAsync('TestPlugin', make)
    }
  }
}

module.exports = {
  target: 'web',
  entry: () => {},
  plugins: [
    new TestPlugin({
      dir: 'files/',
      count: parseInt(process.env.TEST_COUNT) || 1,
    }),
  ],
  output: {
    path: path.join(__dirname, 'dist'),
    filename: '[name].js',
  },
}
```

I'm using the `TEST_COUNT` env var to simplify testing. Running webpack with `TEST_COUNT=1` will do nothing, no output from webpack whatsoever. However, setting `TEST_COUNT=2` will cause webpack to work as desired. Having 2 different files inside the `./files/` directory also works correctly.

**What is the expected behavior?**
webpack works with a single entry added.

**If this is a feature request, what is motivation or use case for changing the behavior?**
-
**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
webpack-3.10 and webpack-v4.0.0-beta.0
```
$ node -v
v8.9.4
```
```
$ uname -a
Linux saboya-desktop 4.14.14-gentoo #1 SMP PREEMPT Sun Jan 21 12:41:09 -02 2018 x86_64 Intel(R) Core(TM) i7-2700K CPU @ 3.50GHz GenuineIntel GNU/Linux
```

**Comment by TheLarkInn** [comment]
What's the cause of this plugin? Or I should ask: what are you trying to accomplish with this Test plugin?

**Comment by saboya** [comment]
@TheLarkInn I'm writinga plugin to simplify a build for an existing Chrome extension. The idea is to read files from 2 different directories and add each file from each directory as an entry.

There's an argument to be made that that info is known beforehand and I could just do that in the `webpack.config.js` file and be done with it. But I wanted to have all the logic inside the plugin since that's only a fraction of what I'm doing.

I opened the issue because it seemed like incorrect behavior nonetheless, but since I'm not familiar with webpack's inner workings, maybe this is intended or I'm doing something wrong. I welcome your feedback on this.

Thanks in advance, and thanks for your work on webpack!

**Comment by sokra** [comment]
In you code you are calling `callback` multiple times. This is wrong and may cause unexpected behavior. Use something like `async.js` forEach.

**Comment by saboya** [comment]
@sokra Thanks for pointing that out. Turns out calling callback multiple times is what makes it work. This is the updated code:

```javascript
const fs = require('fs')
const path = require('path')
const SingleEntryPlugin = require('webpack/lib/SingleEntryPlugin')

class TestPlugin {
  constructor (options = {}) {
    this.options = options
  }

  apply (compiler) {
    const dir = path.resolve(compiler.context,this.options.dir)

    const make = (compilation, callback) => {
      fs.readdir(dir,(err, files) => {
        const promises = files.map(file => new Promise((resolve, reject) => {
          compilation.addEntry(
            this.context,
            SingleEntryPlugin.createDependency(path.resolve(dir,file), file),
            path.basename(file,'.js'),
            (err) => err ? reject(err) : resolve(),
          )
        }))

        Promise.all(promises).then(() => {
          let i = 0
          while (i++ < this.options.count) {
            callback()
          }
        })
      })
    }

    if (compiler.hooks === undefined) {
      compiler.plugin('make', make)
    } else {
      compiler.hooks.make.tapAsync('TestPlugin', make)
    }
  }
}

module.exports = {
  target: 'web',
  entry: () => {},
  plugins: [
    new TestPlugin({
      dir: 'files/',
      count: parseInt(process.env.TEST_COUNT) || 1,
    }),
  ],
  output: {
    path: path.join(__dirname, 'dist'),
    filename: '[name].js',
  },
}
```
Running this with `TEST_COUNT=1` will only call callback once, and not emit any files. `TEST_COUNT>1` will call callback multiple times and emit the files as desired.

So, the intended behavior is to not emit files in this case? Is this not the correct way to add entries dynamically?

**Comment by ScriptedAlchemy** [comment]
That doesn't seem correct. `make` is used to resolve the hook and tell webpack to continue. 

You should only need to call it once. 

Also, this issue is pretty stale, we can probably close it out

**Comment by evilebottnawi** [comment]
Agree. Anyway if somebody have an other opinion feel free to open a new issue
