### ISSUE TITLE
[Feature Request] Use virtual file as entry point

### ISSUE THREAD

**Issue by axetroy** [webpack/webpack#6437]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

You must specify the entry point file path and output dir.

**If the current behavior is a bug, please provide the steps to reproduce.**

not a bugs.

**What is the expected behavior?**

We can specify the code string as an entry point.

**If this is a feature request, what is motivation or use case for changing the behavior?**

I some case. I build a builder cli base on webpack. I need to pack my code.

In current behavior, I gonna create a temp file and use it as entry file, so webpack can work it well.

```javascript
webpack({
  entry: "/path/to/temp/file.js" // before pack the code, I need to create this temp file first
});
```

What if I can use code string as an entry point?

such as this:

```javascript
webpack({
  entry: {
    code: "const xx = require('xxx'); // do something else",
    filepath: "/home/xxx/xxx.js"
  }
});
```

Or maybe we can make it better

```javascript
const virtualEntryFile = new webpack.VirtualFile(
  "filepath.js",
  "// here is the js code string"
);

const virtualImages = new webpack.VirtualFile(
  "example.png",
  new Buffer()
);

webpack({
  entry: virtualEntryFile
});
```

In here, you can see that, I don't need to create an intermediary file anymore

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by axetroy** [comment]
**For more detail:**

here is the file
- a.js

```javascript
console.log("This is a file name 'a.js'")
```

- b.js

```javascript
console.log("This is a file name 'b.js'")
```

I want pack them together.

I the version of current webpack.

I need to create a intermediary file **temp.js**

```javascript
// temp.js
require("./a");
require("./a");
```

and then apply webpack api

```javascript
webpack({
  entry: "temp.js"
});
```

pack done! but ``temp.js`` still there, that's wan't I want.

I can remove it by manual.

but I think, If webpack support virtual file as entry point. that will be cool.

**Comment by ooflorent** [comment]
@axetroy instead of `temp.js` you could do this:

```js
{
  entry: [
    "./a.js",
    "./b.js",
  ]
}
```

I don't get why you would like to use a virtual file. Being explicit is always better. If you want to aggregate _imports_, use the above syntax. If you need to inject some code, create separate file or use `BannerPlugin`.

**Comment by axetroy** [comment]
@ooflorent 
I got a project, pack the all js file into a new file. and all the original file still exist.

but the source code have been change.

**Example: pack them into a new js file**

- a.js

```javascript
// a.js
console.log("a.js file module")
```

- b.js

```javascript
// b.js
console.log("b.js file module")
```

- c.js

```javascript
// c.js
console.log("c.js file module")
```

**expected behavior**

```javascript
const virtualEntryFile = new webpack.VirtualFile(
  "/home/xxx/example.js",
  `
module.exports = function(moduleId) {
  const webpackModule = {
    "0": function(){
      return require("./a.js")
    },
    "1": function(){
      return require("./b.js")
    },
    "2": function(){
      return require("./c.js")
    },
  };
  return webpackModule[moduleId] ? webpackModule[moduleId]() : {};
};
  `
);

webpack({
  entry: virtualEntryFile,
  output:{
     path: "/xxxx/xxx",
     filename: "m.js"
  }
});
```

Use virtual file, I can custom how to pack it without create an intermediary file

**Here is the output**

This part is not the Webpack job.

Webpack just pack them up, and create ``m.js`` as output

- a.js

```javascript
// a.js
require("./m")(0);
```

- b.js

```javascript
// b.js
require("./m")(1);
```

- c.js

```javascript
// c.js
require("./m")(2);
```

**Comment by axetroy** [comment]
Any way.

Pack them up, and provider module for original file.

Virtual file make webpack be more personalized. 

**Custom how to pack without create an intermediary file**

**Comment by axetroy** [comment]
@AsyncWizard 
Sound great!

**Comment by micha149** [comment]
I just tested `virtual-module-webpack-plugin` which seems to work with entry points and also (interesting for my case) as template source for the HtmlWebpackPlugin.

Example:
const VirtualModulePlugin = require('virtual-module-webpack-plugin');

```javascript
{
    // ...
    entry: '/path/to/temp/file.js',
    // ...
    plugins: [
        new VirtualModulePlugin({
            moduleName: '/path/to/temp/file.js',
            contents: 'const xx = require('xxx'); // do something else',
        }),
    ],
}
```

**Comment by axetroy** [comment]
@micha149 
This plugin still need entry file path

**Comment by micha149** [comment]
@axetroy where is the problem? The path is just used to identify the (virtual) asset which I want to use as the entrypoint…

**Comment by axetroy** [comment]
@micha149 
yeah. I got it. no problem.

entrypoint still be a string path, but it can get from VirtualModulePlugin.

great.

**Comment by axetroy** [comment]
any solution for this?

I can not find a solution for now.

**Comment by DominusVilicus** [comment]
If you want to be able to access node_modules, I'd suggest using a memory file system with the normal node fs and merging them with `unionfs` and then in the compiler using:

```javascript
const {Union} = require('unionfs');
const MFS = require('memory-fs');
const fs = require('fs');
let mfs = new MFS();
let ufs = new Union();
ufs.use(mfs).use(fs);

const compiler = webpack(config.config);
compiler.inputFileSystem = this.ufs
compiler.outputFileSystem = this.mfs;
```

**Comment by gabeklein** [comment]
@axetroy I see this is an old issue but just throwing this in the thread. I'd made a webpack plugin to accomplish just this.

https://github.com/gabeklein/webpack-intermediate-entry

**Comment by PierBover** [comment]
The solution by @micha149 with `webpack-virtual-modules` works beautifully, although it would be great if Webpack simply accepted a string of code as an entry.

**Comment by sokra** [comment]
You can use Data URL for that:

```js
webpack({
  entry: `data:text/javascript,
const xx = require('xxx'); // do something else
`
});

**Comment by PierBover** [comment]
> You can use Data URLs for that:
> 
> ```js
> webpack({
>   entry: `data:text/javascript,
> const xx = require('xxx'); // do something else
> `
> });
> ```

Is this documented anywhere?

**Comment by sokra** [comment]
In which configs didn't it work?

A data url Module is kind of anonymous so you have different options to apply rules to it:

By `mimetype`: Instead of `test` you can use `mimetype`. You can also come up with your own mimetypes for modules like svelte

By giving the module a name: 

```js
entry: "some-module.js!=!data:..."
```

**Comment by PierBover** [comment]
Thanks for the tips @sokra I will try to reproduce and open an issue once I have figured it out.

Is all this documented anywhere? I looked at the entry docs but didn't find anything related to data URIs or the `!=!` thing.

**Comment by chenxsan** [comment]
@PierBover https://webpack.js.org/api/loaders/#inline-matchresource for `!=!`.

**Comment by PierBover** [comment]
Thanks @chenxsan . Would you accept a PR to the entry docs to mention these?

**Comment by chenxsan** [comment]
> Thanks @chenxsan . Would you accept a PR to the entry docs to mention these?

PR welcome.

**Comment by vankop** [comment]
Should work with `webpack@latest`. Feel free to report new issue with reproducible repo.

Answer above: `You can use Data URLs for that`

**Comment by alexander-akait** [comment]
Yes, js/css/html supports Data URI in `import`/`url`/`src`, so we don't need extra virtual layer, just use `data:` and it will work even without webpack
