### ISSUE TITLE
Webpack HMR Infinite Refresh on Chrome

### ISSUE THREAD

**Issue by cgray9** [webpack/webpack#6454]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I'm having a strange hot reloading issue that I think is related to my environment, but I can't track down what is. I was hoping someone else had run into it and could point me in the right direction. I've been banging my head on this one for several days now.

I'm running dev webpack locally that comes bundled with react-boilerplate with hot reloading enabled. Anytime a changes is picked up by webpack it rebuilds and then infinitely fetches the *.hot-update.json file from the in memory file system causing the page to infinitely refresh.

Logs from server: 
```
0|web-clie | 2018-02-07 00:30 +00:00: webpack building...
0|web-clie | 2018-02-07 00:30 +00:00: webpack built 665bc020ab09de31dd8e in 372ms
0|web-clie | 2018-02-07 00:30 +00:00: 200 GET /static/7dd032a1be4383284dfd.hot-update.json - 0
0|web-clie | 2018-02-07 00:30 +00:00: 200 GET /static/1.7dd032a1be4383284dfd.hot-update.js - 1
0|web-clie | 2018-02-07 00:30 +00:00: 200 GET /static/1.7dd032a1be4383284dfd.hot-update.js.map - 0
0|web-clie | 2018-02-07 00:30 +00:00: 200 GET /perk/6 - 148
0|web-clie | 2018-02-07 00:30 +00:00: 200 GET /static/7dd032a1be4383284dfd.hot-update.json - 0
0|web-clie | 2018-02-07 00:30 +00:00: 200 GET /perk/6 - 142
0|web-clie | 2018-02-07 00:30 +00:00: 200 GET /static/7dd032a1be4383284dfd.hot-update.json - 0
0|web-clie | 2018-02-07 00:30 +00:00: 200 GET /perk/6 - 138
0|web-clie | 2018-02-07 00:30 +00:00: 200 GET /static/7dd032a1be4383284dfd.hot-update.json - 0
0|web-clie | 2018-02-07 00:30 +00:00: 200 GET /perk/6 - 139
0|web-clie | 2018-02-07 00:30 +00:00: 200 GET /static/7dd032a1be4383284dfd.hot-update.json - 0
0|web-clie | 2018-02-07 00:30 +00:00: 200 GET /perk/6 - 138
0|web-clie | 2018-02-07 00:30 +00:00: 200 GET /static/7dd032a1be4383284dfd.hot-update.json - 0
0|web-clie | 2018-02-07 00:30 +00:00: 200 GET /perk/6 - 141
0|web-clie | 2018-02-07 00:30 +00:00: 200 GET /static/7dd032a1be4383284dfd.hot-update.json - 0
0|web-clie | 2018-02-07 00:30 +00:00: 200 GET /perk/6 - 141
0|web-clie | 2018-02-07 00:30 +00:00: 200 GET /static/7dd032a1be4383284dfd.hot-update.json - 0
0|web-clie | 2018-02-07 00:30 +00:00: 200 GET /perk/6 - 142
```
**If the current behavior is a bug, please provide the steps to reproduce.**
webpack config: https://gist.github.com/cgray9/0333b4b4278da06a17395c7967ca489a
dev middleware: https://gist.github.com/cgray9/0333b4b4278da06a17395c7967ca489a

Note: This issue is only occurring in Chrome. HMR works fine in Safari.
I've tried uninstalling Chrome and deleting all of it's Applications files with no luck.

**What is the expected behavior?**
Receive hot-update without continuing to poll

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Node.js: v8.9.4
webpack: v3.10.0
Operating System: Mac OSX
Google Chrome: Version 64.0.3282.140 (Official Build) (64-bit)

**Comment by CharlesKumar** [comment]
Hi @cgray9 ,

I had problem with chrome and node v8.9.4 when i updated the nodejs to v8.9.4

chrome and node.exe was consuming more memory than it should.

Finally I reverted back to nodejs v8.9.1, everything worked fine.

This has been filed as memory leak issue in nodejs/node, try some other versions of nodejs if you still have the problem

**Comment by achillesrasquinha** [comment]
Facing this issue as well.

**Comment by evilebottnawi** [comment]
Not related to webpack, if somebody have problem please open issue in webpack-dev-server with minimum reproducible test repo, thanks

**Comment by wonsuc** [comment]
I'M HAVING SAME ISSUE ANYBODY GIVE ME A TIP
