### ISSUE TITLE
webpack 4: access the mode flag from webpack.config.js file

### ISSUE THREAD

**Issue by bfred-it** [webpack/webpack#6460]
**Do you want to request a *feature* or report a *bug*?**

*feature*

**If this is a feature request, what is motivation or use case for changing the behavior?**

Since webpack 4 introduces an official `--mode` it'd be nice to be able to access it, otherwise I'm back to the old `process.env.NODE_ENV === 'production'` if I want to customize the production build, like for https://github.com/webpack/webpack/issues/6409#issuecomment-361636056

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

webpack 4.0.0-beta.0

**Comment by michael-ciniawsky** [comment]
**webpack.config.js**
```js
const env = process.env.NODE_ENV

const config = {
   mode: env || 'development'
}
```

**Comment by michael-ciniawsky** [comment]
I suggested to 'inherit'  `mode`  from `process.env.NODE_ENV` in the PR back then, but this was 'rejected', since `webpack` itself should not implicitly rely on any `ENV` variables by default

**Comment by bfred-it** [comment]
That's already what I'm doing, I'd rather _only_ use `--mode production`, **not**  `NODE_ENV`.

For example:

```sh
$ webpack --mode production
```
```js
// webpack.config.js
process.env.WEBPACK_MODE === 'production'
```

**Comment by michael-ciniawsky** [comment]
Could you try 

```js
const config = {
   mode: 'development',
   plugins: [
      this.mode === 'production' ? new Plugin() : false
   ].filter(Boolean)
}
```

```
webpack ---mode production || webpack -p
```

But I think this won't work tbh

Yeah... exposing `mode` to be programmatically accessible in `webpack.config.js` is a good idea imho

**Comment by bfred-it** [comment]
`this` is empty

```js
// webpack.config.js
console.log(this)
```
```sh
$ webpack --mode production
{}
//errors...

$ webpack -p
{}
//errors...
```

**Comment by mbrandys** [comment]
I think this could do the job: https://webpack.js.org/configuration/configuration-types/#exporting-a-function

When you export function that return object in config file instead of returning object itself you have option to access environment info and options map that you passed to webpack command as arguments in that function.

**Comment by bfred-it** [comment]
That seems to work. Are there any caveats to using a function? Like subtle changes of behavior?

```js
module.exports = (env, argv) => ({
	...etc,
	optimization: {
		minimize: false,
		minimizer: argv.mode === 'production' ? [
			new UglifyJsPlugin(...customConfig)
		] : []
	}
});
```

This seems to work correctly with `--mode production`, `-p` and `<no flag>`. 👍 for normalized `argv`

**Comment by michael-ciniawsky** [comment]
No there shouldn't to my knowledge, I didn't know the `{Function}`  already takes a second param passing the CLI arguments. Then it's already implemented :)

**Comment by scriptjs** [comment]
@bfred-it I have been using a similar approach in my `webpack.config.babel.js` and it behaves properly, running the minimizer only with production from argv.

```
const argv = process.argv.slice(2)

if (argv.includes('production')) {
  plugins = plugins.concat(productionPlugins) 
}

In my optimization config, I set my UglifyJsPlugin with custom options but don't set minimize because webpack will handle this with the production mode option. My productionPlugins include other plugins I want run in production mode and add a static bundle analyzer report.

```

**Comment by bfred-it** [comment]
That fails if any other unrelated argument is `production`, it's best to just stick with @mbrandys' solution.

**Comment by longhuynh95** [comment]
https://github.com/webpack/webpack/issues/6460#issuecomment-364286147 <- it's not work with `webpack-dev-server`

**Comment by glen-84** [comment]
@bfred-it Why would it fail?

**Comment by bengrunfeld** [comment]
Just to clarify for all those a little who need a little extra explanation (I fall into that camp).

    webpack --mode development 

**webpack.config.js**

    module.exports = (env, argv) => {
      console.log(argv.mode)        // outputs development
      return {
        // All your other custom config...
      }
    }

**Comment by gabesu** [comment]
@bengrunfeld This was the explanation I needed and it worked perfectly. Cheers.

**Comment by Tiendq** [comment]
It's quite disappointed that Webpack 4 comes with a new `mode` configuration but forgot to set `process.env.NODE_ENV` accordingly so this variable could be used in `webpack.config.js` :(

I just refreshed myself while investigating this a typical use case [#154](https://github.com/webpack-contrib/mini-css-extract-plugin/issues/154)

AFAIK if you want to use `process.env.NODE_ENV` in the `webpack.config.js` you have to set `NODE_ENV` manually on the command line e.g. `NODE_ENV=production webpack --mode=production`. The command is a bit funny, so it's better to get rid of `mode` and go back to old way:

`NODE_ENV=production webpack` and assign mode dynamically in `webpack.config.js`:

```javascript
{
  mode: process.env.NODE_ENV
}
```

**Comment by montogeek** [comment]
@daaain Where does it change? Do you have a commit id?

**Comment by daaain** [comment]
Ah, I realised what's going on, I also switched to webpack-command, not only bumped the webpack version!

Given the following code:

```js
module.exports = (env, argv) => {
  console.log(env, argv);
  ...
}
```

With webpack 4.12.0 and webpack-command 0.2.1 I get:

```
> webpack --mode production

{ _: [], mode: 'production' } undefined
```

With webpack 4.12.0 and webpack-cli 2.1.4 I get:

```
> webpack --mode production

undefined { _: [],
  help: false,
  h: false,
  version: false,
  v: false,
  ...
}
```

I'll open an issue on webpack-command.

**Comment by daaain** [comment]
Apparently not having `env` only `argv` returned is apparently an explicit design choice in webpack-command / config-loader: https://github.com/webpack-contrib/config-loader#gotchas

So I guess that leaves us with 2 different config solutions...

**Comment by montogeek** [comment]
Good news is that it is going to end soon: https://medium.com/webpack/unladen-swallows-and-the-deprecation-of-webpack-cli-39814f6694d3
cc @shellscape

**Comment by bfred-it** [comment]
@montogeek I don't see anything related to this issue in there. The package changes name but `--mode` remains.

**Comment by lmj0011** [comment]
for those of us still using webpack v3, here's one way to figure out beforehand if `production` mode is active.

**webpack.config.js**
```js
module.exports = (env, argv) => {

  if(argv.define && argv.define.includes('process.env.NODE_ENV="production"')){
    // do production related things here
  } else {
    // do non-production related things here
  }

  return {
   // config object
  }
}
```

**Comment by fmcosta** [comment]
i use this:
`const PROD_MODE = argv[argv.indexOf('--mode')+1] === 'production' || process.env.NODE_ENV === 'production'`

**Comment by bebraw** [comment]
@modestotech Try something along

```javascript
module.exports = mode => {
  // return webpack config from here
  return merge(..., { mode }); 
}
```

**Comment by modestotech** [comment]
> @modestotech Try something along
> 
> ```js
> module.exports = mode => {
>   // return webpack config from here
>   return merge(..., { mode }); 
> }
> ```

Can't quite understand. Can you give a more elaborated and clear example? 

In this way I can react the mode in `webpack.prod.js`:
```js
module.exports = (env, argv) => {
  console.log(argv.mode);
  return merge(common, {// prod code}
}
```

Now I need to pass that on to the webpack.common.js.

**Comment by bebraw** [comment]
@modestotech I mean, if you provide a function at the root of your configuration, then you get access to `mode`. I have [a full example](https://github.com/survivejs-demos/webpack-demo) doing something along this. You can have one entry point to your config and then split based on mode there once you know it.

**Comment by modestotech** [comment]
> @modestotech I mean, if you provide a function at the root of your configuration, then you get access to `mode`. I have [a full example](https://github.com/survivejs-demos/webpack-demo) doing something along this. You can have one entry point to your config and then split based on mode there once you know it.

Thanks. I ended up doing that re-ordering. As I was having a setup with 3 files there were some stuff to fix, but now it works as I want it to.

**Comment by wangxuedongOvO** [comment]
> Just a heads up that the [previous proposed solution](https://github.com/webpack/webpack/issues/6460#issuecomment-386947990) won't work as the method signature changed, so now it should look like this:
> 
> ```js
> module.exports = env => {
>   console.log(env.mode)
>   const isProduction = env.mode === 'production';
>   return {
>     // All your other custom config...
>   }
> }
> ```

env is undefined!!!

**Comment by bebraw** [comment]
@wangxuedongOvO For it to work, you have to pass it with `--env` parameter. [I've written a bit about it](https://survivejs.com/webpack/developing/composing-configuration/#understanding-env).

**Comment by robertmain** [comment]
For anyone else that might find this helpful - I tend to do this:

```js
module.exports = ({mode = 'development'}) => ({
    mode,
    entry; {}
    // Other webpack stuff goes here
    output: {
        filename: `[name]${mode === 'production' ? '.min' : ''}.js`
    }
})
```

**Comment by LucidityDesign** [comment]
I have the problem, that my config function gets called multiple times but the arguments are defined only the first time:

webpack.config.babel.js:
```
module.exports = (env, options) => {
  console.log(env, options)
  return { ... }
}
```
`webpack --env.development --mode development` logs:

```
{ development: true } { _: [],
  cache: null,
  bail: null,
  profile: null,
  color: { level: 2, hasBasic: true, has256: true, has16m: false },
  colors: { level: 2, hasBasic: true, has256: true, has16m: false },
  env: { development: true },
  mode: 'development',
  'info-verbosity': 'info',
  infoVerbosity: 'info',
  '$0': 'webpack' }
undefined undefined
undefined undefined
undefined undefined
undefined undefined
undefined undefined
undefined undefined
undefined undefined
undefined undefined
undefined undefined
undefined undefined
undefined undefined
undefined undefined
undefined undefined
undefined undefined
undefined undefined
undefined undefined
```

Therefore I can't use `env.development` nor `options.mode`

**Comment by robertmain** [comment]
That sounds like an issue with chokidar or whatever webpack uses under the hood...


What platform are you on?

**Comment by LucidityDesign** [comment]
Mac OSX 10.14.3

**Comment by robertmain** [comment]
Interesting. Can you link us to a repo to reproduce this?

**Comment by LucidityDesign** [comment]
I think it is a problem with `eslint-import-resolver-webpack` or `eslint-import-resolver-babel-module`. When I don't use aliases or skip eslinting, the webpack-options are logged only once (as it should be).

See: https://github.com/LucidityDesign/webpack-6460

**Comment by robertmain** [comment]
Ah yes, I think you might be on to something there

**Comment by shaching** [comment]
> I have the problem, that my config function gets called multiple times but the arguments are defined only the first time:
> 
> webpack.config.babel.js:
> 
> ```
> module.exports = (env, options) => {
>   console.log(env, options)
>   return { ... }
> }
> ```
> `webpack --env.development --mode development` logs:
> 
> ```
> { development: true } { _: [],
>   cache: null,
>   bail: null,
>   profile: null,
>   color: { level: 2, hasBasic: true, has256: true, has16m: false },
>   colors: { level: 2, hasBasic: true, has256: true, has16m: false },
>   env: { development: true },
>   mode: 'development',
>   'info-verbosity': 'info',
>   infoVerbosity: 'info',
>   '$0': 'webpack' }
> undefined undefined
> undefined undefined
> undefined undefined
> undefined undefined
> undefined undefined
> undefined undefined
> undefined undefined
> undefined undefined
> undefined undefined
> undefined undefined
> undefined undefined
> undefined undefined
> undefined undefined
> undefined undefined
> undefined undefined
> undefined undefined
> ```
> Therefore I can't use `env.development` nor `options.mode`. (webpack v4.29.6)

I got the same errors. And I found the [webpack-mode](https://qiita.com/shaching/items/f542dbb2f96da3c7718b) library which can solve it.

**Comment by soztrk** [comment]
@bengrunfeld , thanks for solution. It works properly.

**Comment by soztrk** [comment]
> Just to clarify for all those a little who need a little extra explanation (I fall into that camp).
> 
> ```
> webpack --mode development 
> ```
> **webpack.config.js**
> 
> ```
> module.exports = (env, argv) => {
>   console.log(argv.mode)        // outputs development
>   return {
>     // All your other custom config...
>   }
> }
> ```

@bengrunfeld , thanks for solution. It works properly.

**Comment by ernestjumbe** [comment]
My understanding of this issue is that if `webpack --development` from the command line you will have do:
```module.exports = (env, argv) => {
    if (env.mode === 'development'){
        ...
    }
}
```
and if you execute it from your `package.json`  i.e:`npm run dev` where your configuration is:
```"scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "dev": "webpack --mode development",
    ...
  },
```

Then it picks up:
```module.exports = (env, argv) => {
    if (argv.mode === 'development'){
        ...
    }
}
```

**Comment by MJGurav** [comment]
> > Just to clarify for all those a little who need a little extra explanation (I fall into that camp).
> > ```
> > webpack --mode development 
> > ```
> > 
> > 
> > **webpack.config.js**
> > ```
> > module.exports = (env, argv) => {
> >   console.log(argv.mode)        // outputs development
> >   return {
> >     // All your other custom config...
> >   }
> > }
> > ```
> 
> @bengrunfeld , thanks for solution. It works properly.

It seems to work fine for development but in case of production it's causing error 

![pack](https://user-images.githubusercontent.com/42145480/71586510-7c357180-2b40-11ea-880e-d64e369c3465.jpg)

![config](https://user-images.githubusercontent.com/42145480/71586508-7c357180-2b40-11ea-89ba-51069b5ac49f.jpg)

![error](https://user-images.githubusercontent.com/42145480/71586511-7c357180-2b40-11ea-8b2b-b0ef71d0a3a1.jpg)

As you can see it returns production when console.logged but it says there is an error with the script with unknown option '--mode'

Could anyone help me figure out whats wrong here 🙏

**Comment by kungcode** [comment]
> Just to clarify for all those a little who need a little extra explanation (I fall into that camp).
> 
> ```
> webpack --mode development 
> ```
> 
> **webpack.config.js**
> 
> ```
> module.exports = (env, argv) => {
>   console.log(argv.mode)        // outputs development
>   return {
>     // All your other custom config...
>   }
> }
> ```

This works great, though I don't understand where env and argv are defined. Also, I still haven't figured out whey env needs to be passed, and why passing argv by itself won't work in the following:

module.exports = (env, argv) => getConfig(argv.mode);

**Comment by account-sxf** [comment]
This is working for me with webpack-cli ^4.10.0
```
module.exports = (_, { mode }) => {
  prod = mode === "production"
  return {
    plugins: [
      // plugins to run regardless
      new HtmlWebpackPlugin({
        title: 'Development',
        templateContent: `
        <html>
            <body>
              <div id="app"></div>
            </body>
        </html>`
      }),
    ].concat(prod ? [
      // plugins to run in production
      new MiniCssExtractPlugin({
        filename: "[name].css",
        chunkFilename: "[id].css",
        ignoreOrder: false, // Enable to remove warnings about conflicting order
      })
    ] : [
      // plugins to run in development
    ]),
    ...
```
