### ISSUE TITLE
How to remove eval and Function constructor from webpack build to avoid CSP issues

### ISSUE THREAD

**Issue by akanshgulati** [webpack/webpack#6461]
**Do you want to request a *feature* or report a *bug*?**
BUG : [Stackoverflow Link](https://stackoverflow.com/questions/48695579/how-to-remove-eval-and-function-constructor-from-webpack-build-to-avoid-csp-issu)

**What is the current behavior?**
It gives both eval and Function contructor which is not required
````
try {
    // This works if eval is allowed (see CSP)
    g = g || Function("return this")() || (1,eval)("this");
} catch(e) {
    // This works if the window reference is available
    if(typeof window === "object")
        g = window;
}

// Another method of build 
function setImmediate(callback) {
      // Callback can either be a function or a string
      if (typeof callback !== "function") {
        callback = new Function("" + callback);
      }
````
**If the current behavior is a bug, please provide the steps to reproduce.**
````
$ npm install -g vue-cli
$ vue init webpack-simple my-project
$ cd my-project
$ npm install
$ npm run prod

You can see in `build.js` having eval 
````

**What is the expected behavior?**
I expect that webpack should provide provision to build according to CSP policy as I am using runtime vue which does not even require compiler.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Node.js : 9.5.0

Tried it with latest config too.
**Package.json**
 ````
{
   "webpack": "^3.10.0",
   "babel-core": "^6.18.2",
   "babel-loader": "^7.1.2",
   "babel-preset-es2015": "^6.18.0",
   "babel-preset-stage-2": "^6.24.1",
   "file-loader": "^0.9.0",
   "style-loader": "^0.18.2",
   "vue-loader": "^10.0.2"
}
````

**Comment by akanshgulati** [comment]
Linked Issue : #5627

**Comment by akanshgulati** [comment]
@sokra Can you help in this?

**Comment by sokra** [comment]
You can replace these modules with your own variants avoiding eval and Function.

The first one is from the `global` shim and isn't an issue of CSP.

I don't know where the second one comes from.

**Comment by evilebottnawi** [comment]
@akanshgulati Thanks for issue, please create minimum reproducible test repo. Also closing as duplicate #5627. Please put your information there. Thanks!

**Comment by akanshgulati** [comment]
@sokra can you tell more about this as how I can remove this issue. Can I define some pattern in config?

**Comment by akanshgulati** [comment]
@evilebottnawi its not totally a same issue actually. I have provided the reproduction steps in description already. Its a very basic boilerplate of vue using webpack and vue-loader

**Comment by jhchen** [comment]
I was able to fix the first eval issue by setting [node.global](https://webpack.js.org/configuration/node/#node-global) to false. This will avoid including this [shim](https://github.com/webpack/webpack/blob/master/buildin/global.js) which includes an eval in a try/catch. Not sure if this will be confusing or clarifying but I only observed this CSP warning in Firefox and not Chrome.

**Comment by akanshgulati** [comment]
@jhchen I tried to learn more and turns out setting `node:false` solved my problem. Thanks man

**Comment by HaNdTriX** [comment]
Disabling `node` or `node.global` might break your isomorphic/universal modules.

Responsible for that eval call is the following code: https://github.com/webpack/webpack/blob/master/buildin/global.js#L8-L11

If you remove it by setting `node.global` to false, will result in `global` being undefined in your code.

### How I solved the issue:

1. Create a `global.js` file somewhere in your project:

    **global.js**

    ```js
    module.exports = window
    ````
2. Disable `node.global` in your `webpack.config.js` by setting it to false.
3. Add the `global.js` by using webpacks provide plugin:

    **webpack.config.js**

    ```js
    {
      ...
      node: {
        global: false
      },
      plugins: [
        ...
        new webpack.ProvidePlugin({
          global: require.resolve('./global.js')
        })
        ...
      ],
      ...
    }
    ```
