### ISSUE TITLE
React - Module parse failed: You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by lalitmee** [webpack/webpack#6473]
- **Webpack Version: "^1.12.12"**

**Do you want to request a *feature* or report a *bug*?**
- I want help in my webpack.config.js. I want to know that is there something wrong in my file.

- I asked on **webpack Gitter** but no one replied. That'w why I am asking here.

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

- Link to **[webpack.config.js](https://gist.github.com/lalitmee/a562d812e50672761217ace0242ea98b)**
- Link to **[package.json](https://gist.github.com/lalitmee/389d2b8d4227c57f745e9e7134a88d7a)**
- **.babelrc**
```
{
  "presets":[
    "es2015", "react", "stage-0"
  ],
  "plugins": ["transform-class-properties"]
}
```
- **error message when I am running**  `npm run electron`
```bash
Hash: a15466a376457c6f3383
Version: webpack 1.12.12
Time: 145ms
    Asset     Size  Chunks             Chunk Names
bundle.js  1.51 kB       0  [emitted]  main
   [0] multi main 28 bytes {0} [built] [1 error]
   [1] ./app/app.js 0 bytes [built] [failed]

ERROR in ./app/app.js
Module parse failed: /home/lalit/Desktop/Github/Electron/simple-electron/scotch-player/app/app.js Line 3: Unexpected token
You may need an appropriate loader to handle this file type.
| // ES6 Component
| 
| import React from "react";
| import ReactDOM from "react-dom";
| import { Header, Button, Container } from "semantic-ui-react";
 @ multi main
```

**What is the expected behavior?**
- expected behavious is to create a bundle.js file for my code so that I can run my application on electron.
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
- **OS** : Ubuntu 16.04
- **Node.js verison** : v9.3.0
- **webpack version** : 1.12.12
- **I am using electron**

**Please help me. Thank you.**

**Comment by sokra** [comment]
Upgrade webpack. The config file is not valid for webpack 1.

**Comment by AlokBansal8** [comment]
My webpack is 3.10 .0
I am still getting this error:

``` cmd
ERROR in ./node_modules/antd/es/style/index.css
Module parse failed: Unexpected character '@' (6:0)
You may need an appropriate loader to handle this file type.
```

**Comment by evilebottnawi** [comment]
@AlokBansal8 seems you have invalid configuration for `style/css` loader(s)

**Comment by AlokBansal8** [comment]
Following is my `webpack.config.babel.js`

``` js
import path from 'path'
import webpack from 'webpack'

import { WDS_PORT } from './src/shared/config'
import { isProd } from './src/shared/util'

export default {
  entry: [
    'babel-polyfill',
    'react-hot-loader/patch',
    './src/client',
  ],
  output: {
    filename: 'js/bundle.js',
    path: path.resolve(__dirname, 'dist'),
    publicPath: isProd ? '/static/' : `http://localhost:${WDS_PORT}/dist/`,
  },
  module: {
    rules: [
      { test: /\.(js|jsx)$/, use: 'babel-loader', exclude: /node_modules/ },
    ],
  },
  devtool: isProd ? false : 'source-map',
  resolve: {
    extensions: ['.js', '.jsx'],
  },
  devServer: {
    port: WDS_PORT,
    hot: true,
    headers: {
      'Access-Control-Allow-Origin': '*',
    },
  },
  plugins: [
    new webpack.optimize.OccurrenceOrderPlugin(),
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NamedModulesPlugin(),
    new webpack.NoEmitOnErrorsPlugin(),
  ],
}
```

And Following is my `.babelrc` file
``` js
{
  "presets": [
    "env",
    "flow",
    "react"
  ],
  "plugins": [
    [
      "import",
      {
        "libraryName": "antd",
        "libraryDirectory": "es",
        "style": "css"
      }
    ],
    "flow-react-proptypes"
  ]
}
```
@evilebottnawi Can you please suggest where am I making the mistake.

**Comment by lalitmee** [comment]
@AlokBansal8 first correct your file name. I think it should be `webpack.config.js`. No need to add babel there.

**Comment by lalitmee** [comment]
@AlokBansal8 Remove the `js/` form `filename: 'js/bundle.js'`. Since it is a `filename`, it should not contain any folder name. You can describe your folder in the `path` variable.
