### ISSUE TITLE
Incomplete Documentation Regarding Implementing BlueBird Promise in New Webpack

### ISSUE THREAD

**Issue by Kielan** [webpack/webpack#6474]
**You want to request a feature/documentation request***

https://webpack.js.org/loaders/babel-loader/
only one approach to "bootstrap "bluebird promise library? There is documentation out there for previous versions of webpack but the do not work, For example this imports/exports strategy does not work.

https://ilikekillnerds.com/2017/03/polyfilling-promises-using-bluebird-webpack-2/

**What is the current behavior?**
Currently setting up a bootstrap or entry point as explained in webpack.org docs strategy is either an incomplete explanation or doesn't work. I cannot override babel polyfill global in console or code using imports exports loader as covered in previous documentation

Minimal reproduceable repo.

https://github.com/Kielan/testWebpackErr

In src/tools/webpack.client.js
**If the current behavior is a bug, please provide the steps to reproduce.**
It could be a bug if I'm doing it correctly and it is not working.

**If this is a feature request, what is motivation or use case for changing the behavior?**
I just want  up to date documentation.

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by sokra** [comment]
create a new file with your polyfill bootstrap code. Add this file as array item to the array provided via `entry`.

**Comment by sokra** [comment]
@webpack-bot move to babel/babel-loader

**Comment by Kielan** [comment]
@sokra what data type is the polyfill bootstrap code?

**Comment by Kielan** [comment]
so appears to be a babel error, can we confirm that?
