### ISSUE TITLE
Unable to import WebAssembly modules bigger than 4KB

### ISSUE THREAD

**Issue by kiurchv** [webpack/webpack#6475]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When importing WebAssembly modules bigger than 4KB browser throws 
```
RangeError: WebAssembly.Instance is disallowed on the main thread, if the buffer size is larger than 4KB. Use WebAssembly.instantiate.
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Import the WASM module bigger than 4KB.

**What is the expected behavior?**

The module should be imported and instantiated correctly.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Browser: Google Chrome 64.0.3282.140 (Official Build) (64-bit)
Node.js: 8.9.1
webpack: 4.0.0-beta.1
Operating System: macOS 10.13

**Comment by sokra** [comment]
@bmeurer Who can I beg to remove this error from Chrome?

see also https://github.com/webpack/webpack/issues/6433

**Comment by bmeurer** [comment]
Redirecting to @mstarzinger from the WebAssembly team.

**Comment by TheLarkInn** [comment]
@kiurchv do you get this error on Microsoft Edge 16-17(insider)? If so I'll also want to see our Chakra team and platform team fall in line here given the tagged issues discussion.

**Comment by mathiasbynens** [comment]
We have [no plans of removing the size limit from Chrome. Using `WebAssembly.{Instance,Module}` is a bad practice, and hurts the user experience especially for large modules. [Use the `WebAssembly.instantiateStreaming` pattern instead](https://developers.google.com/web/updates/2018/04/loading-wasm).

**Comment by jdalton** [comment]
Imposing arbitrary limits on APIs is a bad practice. Super disappointed in the direction you, @mathiasbynens, have moved in general and Chrome's direction on this.

**Comment by jdalton** [comment]
As far as I'm aware Chrome never bothered to see how Webpack was using the API *(good or bad)* and instead of just digging their heels in delivering a broken API.

**Comment by jdalton** [comment]
It's fine to encourage async use but to offer an sync API and then make it a broken one is super wonky. As discussed in #6433 there are other ways to discourage API without delivering a broken one.

**Comment by jdalton** [comment]
@sokra From the https://github.com/webpack/webpack/issues/6433#issuecomment-368094760 it looks like there is no 4kB limit in workers. Have you found that to be the case and is that something currently being leveraged by webpack?

**Comment by jdalton** [comment]
It looks like [Chrome 66](https://github.com/webpack/webpack/issues/6433#issuecomment-381189335) due out in a few days, will remove the 4kB limit in workers.

**Comment by mathiasbynens** [comment]
> It looks like Chrome 66, due out in a few days, will remove the 4kB limit in workers.

The 4 KB limit never applied in workers, only on the main thread.

**Comment by jdalton** [comment]
> The 4 KB limit never applied in workers, only on the main thread.

Yap, @gahaas [corrected](https://github.com/webpack/webpack/issues/6433) the note.

**Comment by jasondavies** [comment]
Looks like this is still an issue on Chrome Version 66.0.3359.117 (Official Build) (64-bit) macOS 10.13.4?

**Comment by gahaas** [comment]
@jasondavies did you try it on a worker or on the main thread? If you did it on a worker could you please give me a repro? `new WebAssembly.Module()` works for me without limitations on a worker.

**Comment by jasondavies** [comment]
Main thread.

**Comment by jasondavies** [comment]
BTW, after reading through the other issues (and I may have misread the comments above), I realise that the 4KB limit still applies on the main thread on Chrome 66, and there are likely no plans to change this.  In other words, sorry for the noise!

It seems like switching to instantiateStreaming would close this issue.

**Comment by moritzuehling** [comment]
Is there a known workaround for this? At the moment it seems like this pretty much renders webpack + wasm unusable. What does the timeline for a fix look like?

**Comment by xtuc** [comment]
yes @Eruant Webpack is going to use `instantiateStreaming` in the future to bypass this limitation.

**Comment by sokra** [comment]
fixed

**Comment by fschutt** [comment]
@mathiasbynens Just a note, but `instantiateStreaming` only works when the response carries the MIME type of `application/wasm`, which, depending on the hoster of the WASM file, isn't always the case. For example, GitHub servers have no way of setting the MIME type. In such cases, you have to either use the fetch() version or the synchronous version. So please don't "force" people to use the `instantiateStreaming` API because there might be valid reasons for not using it.

**Comment by xtuc** [comment]
@fschutt we're adding a fallback here https://github.com/webpack/webpack/pull/7983

**Comment by mathiasbynens** [comment]
@fschutt Yeah, our guidance includes that note: https://developers.google.com/web/updates/2018/04/loading-wasm (look for "Note: The server must be configured to serve [...]")

**Comment by jolestar** [comment]
Create a URL object by Buffer, then use instantiateStreaming async method to load wasm.

    const blob = new Blob([buffer], { type: "application/wasm" });
    const url = URL.createObjectURL(blob);
    wasm = await instantiateStreaming(fetch(url), {});

https://stackoverflow.com/a/55813693/334103

**Comment by Pauan** [comment]
@jolestar Don't forget to call [`URL.revokeObjectURL`](https://developer.mozilla.org/en-US/docs/Web/API/URL/revokeObjectURL) afterwards:

```js
const blob = new Blob([buffer], { type: "application/wasm" });
const url = URL.createObjectURL(blob);
wasm = await instantiateStreaming(fetch(url), {});
URL.revokeObjectURL(url);
```
