### ISSUE TITLE
Webpack does't resolve next in line module from `resolve.modules`

### ISSUE THREAD

**Issue by andrew-polyansky** [webpack/webpack#6476]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
Webpack does't resolve next in line module from `resolve.modules` section if you delete first in line module.
```
./src/customization/foo/index.js
Module build failed: Error: ENOENT: no such file or directory, open '/....../src/customization/foo/index.js'
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Project structure: 
```
|-- src
|   |-- core
|   |   |-- foo
|   |   |    |-- index.js
|   |-- customization
|   |   |-- foo
|   |   |    |-- index.js
```

Resolve options `webpack.config.js`: 
```
 resolve: {
    modules: [
        path.resolve(__dirname, 'src/customization'),
         path.resolve(__dirname, 'src/core'),
        'node_modules',
    ],
```

Code:
```
import foo from 'foo';
```

1) Build webpack with `watch` option
2) Delete `src/customization/foo/index.js` file.
3) Module build failed: Error: ENOENT: no such file or directory,

**What is the expected behavior?**
`src/core/foo/index.js` should be resolved

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Linux, webpack 3.11.0, Node.JS v8.9.1

**Comment by wujashek** [comment]
Actually I have some luck with resolve.unsafeCache and module.unsafeCache set to false in configuration, try this one
