### ISSUE TITLE
Webpack incorrect  resolve `constants`  module with `resolve.modules`.

### ISSUE THREAD

**Issue by andrew-polyansky** [webpack/webpack#6477]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
Webpack incorrect  resolve `constants`  module with `resolve.modules`.

**If the current behavior is a bug, please provide the steps to reproduce.**
Project structure: 
```
|-- src
|   |-- constants
|   |   |-- index.js
|   |   |-- foo.js
```

Resolve options `webpack.config.js`: 
```
 resolve: {
    modules: [
        path.resolve(__dirname, 'src'),
        'node_modules',
    ],
```

Code:
```
import constants from 'constants';
import foo from 'constants/foo'
```

`constants` will be resolved as `constants-browserify` from `node_modules`;
But `foo` work as it should
Also if set `node.constants: false` `constants` will be resolved as `undefined`

**What is the expected behavior?**
`import constants from 'constants';`  should  resolve  `src/constants/index.js` 

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

Linux, webpack 3.11.0, Node.JS v8.9.1

**Comment by sokra** [comment]
`constants` is a node.js core module, but `node.constants: false` should work. What's the content of your `constants/index.js` file.

**Comment by andrew-polyansky** [comment]
@sokra just for test is
`constants/index.js`
```
export default 'constants';
```
