### ISSUE TITLE
[documentation/feature request] extending loaders

### ISSUE THREAD

**Issue by plexigras** [webpack/webpack#6480]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

i would like to be able to use a existing loader inside another loader

**If this is a feature request, what is motivation or use case for changing the behavior?**

for example i would like to be able to apply loaders to a markdown codeblock

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**

**Comment by evilebottnawi** [comment]
@plexigras you can install required loader in you loader repo, looks https://github.com/webpack-contrib/url-loader/blob/master/src/index.js#L42 (we use `fallback` option for other loader)

**Comment by plexigras** [comment]
for now i will just run a separate loader-runner inside my loader

**Comment by sokra** [comment]
loaders are just functions. You can call them from other loaders.

**Comment by plexigras** [comment]
ok and how would i do that?

**Comment by montogeek** [comment]
@plexigras Like executing any other function:
```
const loader = require('loader')

new loader()
```

**Comment by plexigras** [comment]
i know i can just run `require('raw-loader')(content)` but there are a bunch of loaders that are more complicated then this and they take options and sometimes are async and i don't know how i would run one of those more complicated loaders.

**Comment by plexigras** [comment]
i will just stick with loader-runner as it seams to be working well
