### ISSUE TITLE
output.publicPath config required for dynamic import()

### ISSUE THREAD

**Issue by dangodev** [webpack/webpack#6483]
**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?** Using webpack v4 beta & dynamic `import()`, main chunk spits out relative paths rather than absolute paths. This means code splitting works on the index, but as soon as you get to `/subroute/`, the main file tries to load `/subroute/0.js`, e.g., rather than `/0.js` as it should.

**If the current behavior is a bug, please provide the steps to reproduce.** Example here, using webpack-dev-server: https://github.com/dangodev/webpack-v4-code-splitting-test

**What is the expected behavior?** Absolute paths

**If this is a feature request, what is motivation or use case for changing the behavior?** N/A

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
- Node 9.5.0
- webpack 4.0.0-beta

**Comment by MunifTanjim** [comment]
Exists on v4.0.1

**Comment by dangodev** [comment]
@MunifTanjim confirmed in 4.0.1. And yup! You nailed it.

I’m going off memory here, but I could have sworn `output.publicPath` defaulted to `/` in v3 and before. That’s no longer the case with v4. Setting that value fixes the issue.

Not sure whether to close the issue, because I’m not sure if that’s an intended design decision with v4 or not.

Seems like it’s a step away from “#0CJS” because I can‘t imagine a scenario where relative-by-default imports is even usable?

**Comment by pldg** [comment]
I've the same problem, `import()` file path is not parsed correctly. Here is a simple test repository [test-dynamic-import](https://github.com/pldg/test-dynamic-import). Hope to receive a feedback from one of the core contributors...

**Comment by evilebottnawi** [comment]
@pldg please create new issue, it is bug from beta and already was solved. Thanks!
