### ISSUE TITLE
Deps issues due to major bump of ajv

### ISSUE THREAD

**Issue by backwardok** [webpack/webpack#6484]
**Do you want to request a *feature* or report a *bug*?**
Report a bug (sorta)

**What is the current behavior?**
There was a major dependency update to `ajv` in https://github.com/webpack/webpack/pull/6430 and it was released as a patch release. This is resulting in a ripple effect on all other dependencies that rely on `ajv`. For example, [eslint's latest version](https://github.com/eslint/eslint/blob/master/package.json#L37) is currently pegged to `ajv: ^5.3.0`.

As most libraries peg to minor versions, having this change introduced as a minor version bump instead of a major version bump is making this incompatible with a number of libraries.

Can the upgrade to `ajv` happen in a major release and a new patch release be put out that downgrades `ajv` to what it was before?

**If the current behavior is a bug, please provide the steps to reproduce.**
Create a project with a dependency on `eslint` and `webpack`.

**What is the expected behavior?**
npm install works without error

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
webpack version `3.11.0`

**Comment by backwardok** [comment]
See also https://github.com/webpack-contrib/schema-utils/issues/23

**Comment by sokra** [comment]
see https://github.com/webpack-contrib/schema-utils/issues/23#issuecomment-365392978
