### ISSUE TITLE
Cannot find module 'source-map' after installing: `npm install @types/webpack`

### ISSUE THREAD

**Issue by Legends** [webpack/webpack#6490]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Cannot find module 'source-map'  error when running `tsc` after installing:
`npm install @types/webpack`
**If the current behavior is a bug, please provide the steps to reproduce.**
Cannot find module 'source-map'  error when running `tsc` after installing:
`npm install @types/webpack`

**What is the expected behavior?**
I want to have full intellisense support for my webpack.config.js, therefore I install `@types/webpack`.
No errors when running `tsc` afterwards.
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
Win 10 x64
VsCode 1.20

```
"dependencies": {
    "@types/node": "^9.4.5"
  },
  "devDependencies": {
    "@types/jquery": "^3.3.0",
    "@types/lodash": "^4.14.102",
    "html-webpack-plugin": "^2.30.1",
    "jquery": "^3.3.1",
    "lodash": "^4.17.5",
    "ts-loader": "^3.5.0",
    "typescript": "^2.7.1",
    "webpack": "^3.11.0"
  },
```
[Issue posted in TS repo](https://github.com/Microsoft/TypeScript/issues/21942)

**Comment by j-oliveras** [comment]
I think you should fill this issue here: https://github.com/DefinitelyTyped/DefinitelyTyped (is the repository for all npm `@types` packages).

**Comment by Legends** [comment]
@j-oliveras This works! Thank you !

[I opened an issue DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/23649)
