### ISSUE TITLE
Useless error message, when executing command: webpack

### ISSUE THREAD

**Issue by Legends** [webpack/webpack#6492]
**Do you want to request a *feature* or report a *bug*?**
improvement

**What is the current behavior?**
I am trying to use the ExtractTextPlugin and have therefore modified webpack.config.js
Probably there is something wrong with the configuration.
But the error message returned from the comand: `webpack` I cannot interpret.

> PS C:\inetpub\wwwroot\WebPack_TypeScript_Setup_Example> webpack
> Hash: b908062cd010944f1044
> Version: webpack 3.11.0
> Time: 463ms
>      Asset       Size  Chunks             Chunk Names
>  bundle.js    6.12 kB       0  [emitted]  main
> index.html  182 bytes          [emitted]
>    [0] ./src/index.ts 320 bytes {0} [built] [failed] [1 error]
> 
> ERROR in ./src/index.ts
> Module parse failed: Unexpected token (48:44)
> You may need an appropriate loader to handle this file type.
> | setTimeout(() => {
> |     getComponent().then(component => {
> |         document.body.appendChild(component as HTMLDivElement);
> |     }).catch((e) => {
> |         console.log(e);
> Child html-webpack-plugin for "index.html":
>      1 asset
>        [2] (webpack)/buildin/global.js 509 bytes {0} [built]
>        [3] (webpack)/buildin/module.js 517 bytes {0} [built]
>         + 2 hidden modules

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
I have only changed the .config, so the error message should point to the config and not to index.ts!
Because i didn't change anything in index.ts.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Now I am stuck. The error message tells me nothing.
It points to index.ts, which has nothing to do with the error.
When I remove the config modifications regarding the ExtractTextPlugin everything works again.
The modification is 1 to 1 copy of an example of the webpack online guide.
Is there a way people can debug build errors?

**Please mention other relevant information such as the browser version, Node.js version, webpack version and Operating System.**
```
Win10 x64
VsCode 1.20
"dependencies": {
    "@types/extract-text-webpack-plugin": "^3.0.1",
    "@types/html-webpack-plugin": "^2.30.2",
    "@types/node": "^9.4.5",
    "@types/source-map": "^0.5.2"
  },
  "devDependencies": {
    "@types/jquery": "^3.3.0",
    "@types/lodash": "^4.14.102",
    "@types/webpack": "^3.8.7",
    "css-loader": "^0.28.9",
    "extract-text-webpack-plugin": "^3.0.2",
    "html-webpack-plugin": "^2.30.1",
    "jquery": "^3.3.1",
    "less": "^3.0.0",
    "less-loader": "^4.0.5",
    "lodash": "^4.17.5",
    "node-sass": "^4.7.2",
    "raw-loader": "^0.5.1",
    "sass-loader": "^6.0.6",
    "style-loader": "^0.20.1",
    "ts-loader": "^3.5.0",
    "typescript": "^2.7.1",
    "webpack": "^3.11.0"
  },
```

**Comment by sokra** [comment]
ts-loader doesn't seem to be configured properly

Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md).

**Comment by Legends** [comment]
It's a bug because it bugs me. I think, `ts-loader` uses the `tsconfig.json`.
Unexpected char at (23:44) doesn't help me at all.... debugging/finding a solution  is hell.
For example, if a C# library produces crap, tweaking compiler options won't help that much..

**Comment by Legends** [comment]
Adding parameter `webpack --display-error-details` helps a lot in debugging
