### ISSUE TITLE
[Feature] Compiler macros to detect target in JS sources

### ISSUE THREAD

**Issue by NeekSandhu** [webpack/webpack#6494]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Undefined

**What is the expected behavior?**

Presence of compiler macros as seen in `C` or `C++`, set dynamically, and look like `#ifdef _APPLE_` when building for macOS, `#ifdef _WIN32` when building for Windows.

Similarly, would be nice if `webpack` did something similar, for when targetting different targets, that way developers can have their JS wrapped in `if` blocks and those blocks would get removed during uglification process.

Example:
```javascript
// my_cool_lib.js ( a library that works on node and browser, but with slight differences)

const env = typeof process !== 'undefined' && typeof process.env !== 'undefined' ? process.env : { }

if (env && env.WEBPACK_EXPLICIT_TARGET === 'node') {
    // ~400 lines of code, that can now be removed by uglify when target is `web`
}

```

**If this is a feature request, what is motivation or use case for changing the behavior?**

When building `wasm` with Emscripten, it also emits Javascript glue code.

AFAIK it has glue code for both node and browser environments. When using `wasm` in browser, the user is also sent extra nodejs glue code although not needed.

**Comment by TheLarkInn** [comment]
This can be done today with webpack.DefinePlugin({})

https://webpack.js.org/plugins/define-plugin/

If this is what you are looking for please feel free and close the issue!

**Comment by alexander-akait** [comment]
If you still need this, you can create own plugin for this, as you can see no one reacted :+1: or `I want it`, I want to close it in favor plugin API/loader API
