### ISSUE TITLE
Expose the `mode` option for loaders

### ISSUE THREAD

**Issue by iamakulov** [webpack/webpack#6496]
**Do you want to request a *feature* or report a *bug*?**
A feature.

**What is the current behavior?**
Currently, loaders don’t have access to webpack’s `mode` option.

**What is the expected behavior?**
Loaders should have access to `mode`.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Does it make sense to expose the `mode` option to loaders? Loaders might use it to apply mode-specific optimizations – e.g., `css-loader` could enable minification in the production mode automatically.

This decreases the number of things a user has to know about and configure to make things work right.

(If the option is already exposed – sorry, just point me to it, I haven’t found it.)

**Comment by evilebottnawi** [comment]
@iamakulov `css-loader@next` remove minification, it should be do in plugin

**Comment by iamakulov** [comment]
@evilebottnawi Oh, I see (ref for everyone else: https://github.com/webpack-contrib/css-loader/pull/639). Thanks for noting this!

Is this going to be released alongside with webpack 4? Is the plugin for minification already available? (Or should I ask these questions in the `css-loader` repo?)

(Asking because I’m working on webpack 4 updates for https://developers.google.com/web/fundamentals/performance/webpack/decrease-frontend-size)

**Comment by evilebottnawi** [comment]
css (using `cssnano`) - https://github.com/NMFR/optimize-css-assets-webpack-plugin
css with any plugin for minification - https://github.com/NMFR/last-call-webpack-plugin

**Comment by iamakulov** [comment]
Thank you!

**Comment by evilebottnawi** [comment]
@iamakulov problem is solved?

**Comment by iamakulov** [comment]
@evilebottnawi IDK – this is a generic proposal related to all loaders, not just `css-loader`. However, I don’t know other loaders where this might be useful, so feel free to close the issue if you feel it’s irrelevant.

**Comment by ferrao** [comment]
Would be nice to uglify (or not) html and css by simply inspecting `mode`.

Until them I have to keep on using different config files for dev/prod environments...

**Comment by TheYorkshireDev** [comment]
I have to agree, it would be nice to toggle settings depending on the mode.

**Comment by osya** [comment]
@TheYorkshireDev, your solution is not worked for me. 
```
const isDevMode = () => {
    return (process.env.NODE_ENV === 'development');
};
console.log('process.env.NODE_ENV == ' + process.env.NODE_ENV);
console.log('isDevMode == ' + isDevMode());
```
running by `webpack --mode development --config ./webpack.config.js --progress` outputs
```
process.env.NODE_ENV == undefined
isDevMode == false
```
Webpack 4.1.1

**Comment by TheYorkshireDev** [comment]
@osya I suggested setting **NODE.ENV** rather than the mode. Then toggle the mode within the config, so you do not pass in `--mode development`.

For example, `NODE_ENV=development webpack --config ./webpack.config.js --progress`

Then you set the mode:
```
module. isDevMode = {
    mode: isDevBuild ? 'development' : 'production',
...
```

**Comment by osya** [comment]
@TheYorkshireDev, Thanks. I got it

**Comment by evilebottnawi** [comment]
@sokra can we set mode from config for loader options if `mode` will not set?

**Comment by montogeek** [comment]
Related https://github.com/webpack/webpack/issues/7074

**Comment by weishijun14** [comment]
webpack.common.js:

```javascript
const devMode = process.env.NODE_ENV !== 'production';    //devMode = undefined
 module.exports = {
    module: {
        rules: [
         {
           test: /\.css$/,
           use: [
             devMode ? 'style-loader' : MiniCssExtractPlugin.loader,
             'css-loader'
            ]
          }
        ]
    }
  },
```

webpack.prod.js:
```
module.exports = merge(common, {
   mode: 'production'
})
```

package.json: 

```
 "build": "webpack --config webpack.prod.js",  // not work
// "build": "webpack --mode=production --config webpack.prod.js", // not work
// "build": "cross-env NODE_ENV=production webpack --config webpack.prod.js", // work
```

**Comment by danburzo** [comment]
I'm trying to configure `mini-css-extract-plugin` and the [documentation for it](https://webpack.js.org/plugins/mini-css-extract-plugin/) seems to be checking NODE_ENV for conditionally using their loader, but since the `mode` option does not set it, `devMode` will always be true in the 'advanced example'.

**Comment by QWp6t** [comment]
`mode` could be used by [this loader](https://github.com/vuejs/vue-loader), which utilizes its own `isProduction` variable that (when undefined) it attempts to guess by looking at `NODE_ENV`.

https://github.com/vuejs/vue-loader/blob/master/lib/index.js
(search for "isProduction" to see how it's used)

xref: https://github.com/vuejs/vue-loader/pull/1345

**Comment by bensampaio** [comment]
My loader needs to add some extra code when in development / watch mode.  So it would be pretty useful to have access to the `mode` option of webpack to determine what to do. Relying on `process.env.NODE_ENV` to be set sounds a bit weird to me. It is not a webpack specific variable and people can still set the mode without setting the environment variables, right?

**Comment by danburzo** [comment]
After warming up a bit to Webpack 4, I think given the current status, it's still a better idea to set NODE_ENV to the desired value and pass it to the `mode` option, instead of the other way around.

**Comment by KESHAmambo** [comment]
I have the save issue: needed to access env in loader to decide on optimizing. Long story short, had to agree with @danburzo, thank you!

**Comment by evilebottnawi** [comment]
Feel free to send a PR to expose the `mode` option for loaders

**Comment by evilebottnawi** [comment]
bump

**Comment by shcarrico** [comment]
bump

**Comment by tschaub** [comment]
See #9140 for a proposed change that adds the `mode` to the loader context.
