### ISSUE TITLE
ModuleNotFound error 

### ISSUE THREAD

**Issue by spion-h4** [webpack/webpack#6497]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Current published webpack 3.11.0 generates the following error when used together with worker-loader:

```
ModuleNotFoundError: Module not found: Error: Can't resolve 'module' in '/path/to/project/node_modules/webpack/lib/node'
```

**If the current behavior is a bug, please provide the steps to reproduce.**

The problem is this commit:

https://github.com/webpack/webpack/commit/e4375f8833eeb39391f868ca9b0409d69d71b768#diff-131e884e3538765183bbd2341e7fdaf1

The line

```
const builtins = require("module").builtinModules || Object.keys(process.binding("natives"));
```

does not work in the context of worker loader, since apparently it encounters the require call and tries to bundle the built-in module "module"

**Comment by sokra** [comment]
Don't name your packages like node.js internal modules.

**Comment by spion-h4** [comment]
Thats not whats going on here. worker-loader is broken because it tries to bundle the above file.

**Comment by sokra** [comment]
hmm... This file is not meant to be bundled.

**Comment by evilebottnawi** [comment]
@spion-h4 problem still exists?

**Comment by spion-h4** [comment]
Don't know, we ended up not using worker loader anymore.

**Comment by evilebottnawi** [comment]
@spion-h4 let's close issue, if somebody will have same problem feel free to recreate issue. Thanks!
