### ISSUE TITLE
Webpack 4.0.0.beta.1 warnings emitted

### ISSUE THREAD

**Issue by scriptjs** [webpack/webpack#6499]
**Do you want to request a *feature* or report a *bug*?**
Possible bug

**What is the current behavior?**
Emission of warnings. Not certain where these are being emitted during the build but only present in development mode.
```
schema id ignored BannerPlugin
schema id ignored BannerPlugin
schema id ignored BannerPlugin
schema id ignored BannerPlugin
schema id ignored BannerPlugin
schema id ignored BannerPlugin
schema id ignored BannerPlugin
schema id ignored HashedModuleIdsPlugin
schema id ignored HashedModuleIdsPlugin
schema id ignored HashedModuleIdsPlugin
schema id ignored HashedModuleIdsPlugin
(node:26081) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
```
**If the current behavior is a bug, please provide the steps to reproduce.**
Configure webpack with BannerPlugin and HashedModulePlugin. Webpack in `development` mode.

**What is the expected behavior?**
No warnings should be emitted

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

node: 8.9.4
webpack: 4.0.0.beta.1
os: macos 10.12.6

**Comment by TheLarkInn** [comment]
Hmm. This could be potentially the schemas/ for those plugins? If you are able to reduce further, would you have interest in submitting a PR? Happy to help.

**Comment by scriptjs** [comment]
@TheLarkInn Yeah, I can attempt to look into this further. Its annoying to see in my output. The last one, Tapable, was that not something just being introduced? How can it be deprecated?

**Comment by michael-ciniawsky** [comment]
This is due to changes in the JSON Schema Spec I assume. I guess all [`id`'s](https://github.com/webpack/webpack/blob/master/schemas/plugins/BannerPlugin.json#L2) simply need to be removed. But I need to take a look at the spec (changes) first, but this happened before already

**Comment by scriptjs** [comment]
@michael-ciniawsky Thanks. Perhaps a regression then. I work with JSON Schema as well and know about the changes which is now at draft-07

**Comment by scriptjs** [comment]
@TheLarkInn @michael-ciniawsky So webpack is using draft-04 schema when ajv is at draft-07 that supporting draft-06 without changes. There seem to be a couple of possibilities here. Instead of using ajv as a dependency of webpack, I would suggest removing it as a dependency and  generate a validate method  for each schema. This will eliminate the need to include the parser/validator and reducing webpack's size substantially.  To do this is best to isolate the validate method for each plugin and require it. I generate these methods from a script in my package.json Regardless of whether to leave it in or take it out, the schemas need small adjustment to conform.

**Comment by michael-ciniawsky** [comment]
For `loaders/plugins`  we use [`schema-utils`](https://github.com/webpack-contrib/schema-utils) which is very basic compared to  `webpack`'s own schema handling. Any suggestions always welcome :)

> I am only using webpack's own plugins ie. BannerPlugin, DefinePlugin, ModuleConcatenationPlugin, HashedModuleIdsPlugin with two external plugins BundleAnalyzerPlugin and the latest UglifyJSPlugin. I don't see anything to change in my config.

E.g UglifyJSPlugin isn't updated to the new plugin system yet, since the plugin should also support `webpack =< v4.0.0` for a while to keep maintenance low. It's annoying to get those and a way to silence them would be good imho, but most of the time one can simply ignore them :)

**Comment by handrews** [comment]
> webpack is using draft-04 schema when ajv is at draft-07, supporting draft-06 without changes

What would need to happen to get webpack up to draft-07, given that the validator on which it depends supports draft-07?  I don't necessarily mean requiring everything to be draft-07 but perhaps allowing choosing it based on `$schema` and calling ajv with an explicit meta-schema version accordingly.

My apologies if this is a naive question, I'm dropping in from the JSON Schema project and have only a very basic knowledge of webpack.  I'm trying to spur projects to update and/or get a better understanding of the barriers to updating.

**Comment by scriptjs** [comment]
@handrews I really see no barrier at all for upgrading, only whether or not we include a compiled ajv validate method or the validator in webpack. I am for keeping all packages as light as possible since webpack may be used as a lib as well as a command line bundler.

**Comment by damianobarbati** [comment]
Is there any docs/documentation on webpack@4 available online? Or just the post on medium?

**Comment by scriptjs** [comment]
@damianobarbati For the most part the online docs should work for you. The main changes for me was that you will need to put your uglify plugin into an optimization config since it is no longer handled as a regular plugin.  Second you use modes instead of environment for configuring development vs production. So I am capturing the mode from argv to determine which plugins to load. That was all to have it working. You can look at the docs for exporting a function instead of an object to get hold of argv for your mode. I am responding but this doesn't have anything to do this issue.

**Comment by damianobarbati** [comment]
Thanks @scriptjs for replying me and sharing your experience even if my q wasn't related to your issue 👍🏻

**Comment by nveenjain** [comment]
Hey, @scriptjs , guess, this is working fine for me in development, could you please upload webpack.config.js file, so that i can start working on it?
