### ISSUE TITLE
Apply sourcemap to only one chunk

### ISSUE THREAD

**Issue by davidtheclark** [webpack/webpack#650]
If I follow the directions from the [the canonical example for app-vendor splitting](http://webpack.github.io/docs/code-splitting.html#split-app-and-vendor-code), *and* I want to apply sourcemaps to my app bundle (via the `devtool` config option) --- sourcemaps will be generated for *both* chunks. Which makes sense, because the `devtool` config option is not chunk-specific.

The problem with this is that the vendor file can get pretty big, and its gigantic sourcemap then severely slows down dev tool initialization on page reload. I would much prefer to *only* have a sourcemap for my app chunk (and *not* to have a sourcemap for my vendor chunk).

As far as a I can tell there is no way to do this now. But I think it would be nice. (So I suppose this issue is either a question or a feature request, depending on whether there is already a way that I just don't know about.)

**Comment by gaearon** [comment]
+1! I'll probably switch to source maps from devtool eval if this is implemented.

**Comment by nelix** [comment]
I generate the .map files then delete the vendor map manually to speed up dev tools, but this would be much better.

**Comment by gaearon** [comment]
I talked to @sokra and plan to start working on this today if I don't get distracted by something else :-). The plain is to add `exclude` to `SourceMapDevToolPlugin`.

**Comment by nelix** [comment]
awesome!

**Comment by sebastienbarre** [comment]
+1 this would be great, these vendors source map files are getting really really big.

**Comment by gaearon** [comment]
Sorry I have not followed through on this one. I'm not working on it, so if some one is keen to jump in, by all means, do!

**Comment by sebastienbarre** [comment]
@gaearon I'll give it a shot.

**Comment by sebastienbarre** [comment]
@gaearon @sokra here you go, first stab.

**Comment by antwan1986** [comment]
+1!

**Comment by sokra** [comment]
see #897
