### ISSUE TITLE
Issue in generating multiple vendor bundle

### ISSUE THREAD

**Issue by nikhil4326** [webpack/webpack#6502]
I am new to webpack, I am using webpack3 with angular 4. I have added dependencies in package.json. I have mentioned dependencies below. For each dependency i want to create respective vendor bundle. Like i have 5 dependencies i want 5 vendor bundles.
```
"dependencies": {
    "@angular/common": "4.4.6",
    "@angular/compiler": "4.4.6",
    "@angular/core": "4.4.6",
    "@angular/forms": "4.4.6",
    "@angular/http": "4.4.6",
    "@angular/platform-browser": "4.4.6",
    "@angular/platform-browser-dynamic": "4.4.6",
    "@angular/router": "4.4.6",
    "codelyzer": "^4.1.0",
    "core-js": "2.5.3",
    "rxjs": "5.5.6",
    "zone.js": "0.8.9"
  }
```
Please help me in creating multiple bundle for each dependency.
if possible please share the pros and cons with this approach.
Thanks in advance.

**Comment by sokra** [comment]
Please submit support requests and questions to StackOverflow using the tag [[webpack]](http://stackoverflow.com/tags/webpack). StackOverflow is better suited for this kind of support. The issue tracker is for bug reports and feature discussions. See also [our CONTRIBUTING guidelines](https://github.com/webpack/webpack/blob/master/CONTRIBUTING.md).
