### ISSUE TITLE
electron-main and electron-renderer targets problem with original-fs module

### ISSUE THREAD

**Issue by sagorshkov** [webpack/webpack#6504]
**Do you want to request a *feature* or report a *bug*?**
    Bug

**What is the current behavior?**
    If your Webpack's target is **electron renderer** and you try to import **original-fs** built-in module, Webpack will try to find this module in the node-modules to include it in the bundle.

**What is the expected behavior?**
    Webpack should perceive the **original-fs** as the module from the core of the Node, when the Target is electron-renderer or electron-main. It's because this module is built-in to Electron's NodeJS core. [Here is](https://electronjs.org/docs/all#treating-an-asar-archive-as-a-normal-file) a link to Electron doc. [Here is](https://github.com/electron/electron/issues/9500) link to an issue in electron repo.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
    Webpack - 3.10.0
    Node - 9.4.0
    OS - macOS 10.12.6

**Comment by EugeneHlushko** [comment]
Seems legit, mind if i create PR @sokra ?

**Comment by sokra** [comment]
Yep send a PR
