### ISSUE TITLE
webpack 4: Invalid configuration object when using "type" in the rules configuration

### ISSUE THREAD

**Issue by hrasoa** [webpack/webpack#6507]
**Do you want to request a *feature* or report a *bug*?**
I want to report a bug

**What is the current behavior?**

Given this configuration:

      {
        test: /\.scss$/,
        type: 'stylesheet',
        use: [
          'sass-loader',
        ],
        exclude: /node_modules/,
      },

When I launch the webpack dev server:

```
/var/www/node_modules/webpack/lib/webpack.js:20
		throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
		^

WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration[0].module.rules[1].type should be one of these:
   object { enforce?, exclude?, include?, issuer?, loader?, loaders?, oneOf?, options?, parser?, resolve?, sideEffects?, query?, type?, resource?, resourceQuery?, compiler?, rules?, test?, use? }
   -> Module type to use for the module
    at webpack (/var/www/node_modules/webpack/lib/webpack.js:20:9)
    at Object.<anonymous> (/var/www/server/app/dev.js:24:17)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:190:16)
    at bootstrap_node.js:662:3
```
**If the current behavior is a bug, please provide the steps to reproduce.**
* Install webpack 4
* Put the configuration given above
* Launch the devserver

**What is the expected behavior?**
I should work without any errors.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
* node: v9.5.0
* webpack: 4.0.0-beta.1

**Comment by michael-ciniawsky** [comment]
There isn't a `type: 'stylesheet'` (yet) #6448 and it this wouldn't have any effect, the `{Error}` is correct here atm
