### ISSUE TITLE
NSP check is reporting vulnerability on latest Webpack package.

### ISSUE THREAD

**Issue by sneharghya** [webpack/webpack#6513]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

Just executed the nsp check command on my project and it is reporting a vulnerability on latest webpack package due to a downstream dependency on the module hoek.
Please refer the link from node security: https://nodesecurity.io/advisories/566

Path: webpack >> watchpack@1.4.0>>chokidar@1.7.0>>fsevents@1.1.3>>node-pre-gyp@0.6.39>>hawk>>hoek

**Comment by EugeneHlushko** [comment]
I think chokidar needs version bump, can submit a pr if that sounds good @sokra

**Comment by evilebottnawi** [comment]
@EugeneHlushko PR welcome

**Comment by evilebottnawi** [comment]
@webpack-bot move to webpack/watchpack
