### ISSUE TITLE
Intended dev-server behaviour?

### ISSUE THREAD

**Issue by andru** [webpack/webpack#652]
I'm trying to set up the webpack dev server (without hot replacement initially) following the docs here: http://webpack.github.io/docs/webpack-dev-server.html

What the docs don't make clear is: what kind of behaviour should one actually expect from the dev server?

Should running the dev-server actually package my module and write the resulting files to the output dir?

If not, what should the process be? How does the recompilation it's doing as a result of my changes reach the browser?

At present, I'm having to run webpack to generate my packaged modules, which takes over a minute, and then start up the dev-server which recompiles when I change my files, but doesn't seem to actually write this recompiled file anywhere. The only way to see the changes is to run a full re-package, which is untenably slow as a development environment. 

Any hints?

**Comment by jhnns** [comment]
Close?
