### ISSUE TITLE
Breaking change in version 3.11?!

### ISSUE THREAD

**Issue by theCuriousOne** [webpack/webpack#6521]
This is an unintentional breaking change, that was not in the released notes.

Currently there is webpack.js in lib folder, which is not the same as webpack.js in the bin folder like it was in version 3.10

**If the current behavior is a bug, please provide the steps to reproduce.**

I would like to remain the webpack.js in the bin folder like it was in version 3.10, or at least how to use it in the same manner.

N/A

There is not related to environment

**Comment by sokra** [comment]
This didn't change

https://github.com/webpack/webpack/compare/v3.10.0...v3.11.0

**Comment by theCuriousOne** [comment]
Hmm sorry.  It must have been some strange mistake while fetching the package. Really sorry
