### ISSUE TITLE
this.jQuery cannot be shimmed with ProvidePlugin

### ISSUE THREAD

**Issue by garygreen** [webpack/webpack#6526]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

The ProvidePlugin does not properly support importing and replacing `this.jQuery` in legacy apps.

**If the current behavior is a bug, please provide the steps to reproduce.**

**test.js**

```javascript
if (this.jQuery) {
    throw 'Jquery is not available.';
}

console.log('jQuery found.', this.jQuery);
```

This outputs the following:

```javascript
webpackJsonp([0],[
/* 0 */
/***/ (function(module, exports) {

if (this.jQuery) {
    throw 'Jquery is not available.';
}

console.log('jQuery found.', this.jQuery);


/***/ })
],[0]);
```

If you were to define it as `this2` instead, you get the correct output:

```javascript
webpackJsonp([0],[
/* 0 */
/***/ (function(module, exports, __webpack_require__) {

/* WEBPACK VAR INJECTION */(function(__webpack_provided_this2_dot_jQuery) {if (__webpack_provided_this2_dot_jQuery) {
    throw 'Jquery is not available.';
}

console.log('jQuery found.', __webpack_provided_this2_dot_jQuery);

/* WEBPACK VAR INJECTION */}.call(exports, __webpack_require__(1)))
```

**config**
```javascript
var webpack = require('webpack');
var path = require('path');

module.exports = {

    entry: {
        test: './test.js'
    },

    output: {
        path: path.resolve(__dirname, './output.js'),
        filename: '[name].js'
    },

    plugins: [
        new webpack.ProvidePlugin({
           'this.jQuery': 'jquery'
       })
    ]

};
```

**What is the expected behavior?**

It should replace `this.jQuery` with the imported version.

**If this is a feature request, what is motivation or use case for changing the behavior?**

To support shimming legacy apps that use `this` as the global window context.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

Webpack version: 3.11.0

**Comment by sokra** [comment]
Could you check if this is still an issue in webpack 4? We did some changes to the handling of `this` in the parser,

**Comment by nveenjain** [comment]
Can i work on this? i think the problem lies on this line https://github.com/webpack/webpack/blob/master/lib/ProvidePlugin.js#L34

**Comment by nveenjain** [comment]
@sokra, I was working on this issue, seems like it could be solved by twinkering with Parser, https://github.com/webpack/webpack/blob/master/lib/Parser.js#L1694 have exprName.name property on which hook could be applied, but in this statements, we have `exprName.free` assigned as `false`. Now currently we walk through this statement according to https://github.com/webpack/webpack/blob/master/lib/Parser.js#L1713, where we don't have access to it's property which is accessed, now i'm a bit confused as to what exactly should i do? should i set exprName.free (which i'm confused, what exactly does it do?) to be true for `this` expressions or anything else?? Please suggest. Thanks.

**Comment by sokra** [comment]
I guess in this line https://github.com/webpack/webpack/blob/213226ece261a0e89edb9de15fbc6775418f6041/lib/Parser.js#L2011 you can assign `free = this.scope.topLevelScope`

**Comment by nveenjain** [comment]
@sokra, does `free` property mean `allowed to be renamed`? I'm actually confused as to what `free` represents. Also `topLevelScoped this` represents `exported modules from current module`, will it not cause any ambiguity?? Acc. to me, either we should completely support changing this.propertyName to a module using providPlugin, or not support it at all. That way, we can be sure that user wants it and it's developer's responsibility to not abuse it..

**Comment by sokra** [comment]
Free means not defined in these module. Coming from the environment.

Only the top level this comes from webpack. Every other this is defined in the module.
