### ISSUE TITLE
WASM parsing and more

### ISSUE THREAD

**Issue by xtuc** [webpack/webpack#6530]
I was playing around with the [ballercat/wasm-loader](https://github.com/ballercat/wasm-loader), but I believe you want to add first-class support in Webpack?

I would like to share a bit of my work done so far. We have a first implementation of the wasm binary DCE here https://github.com/ballercat/wasm-loader/pull/7 (you might have an idea to collect the usages btw :) ) and I was thinking about a new API here https://github.com/ballercat/wasm-loader/issues/8, according to the discussion in https://github.com/webpack/webpack/issues/6433 that might not be the best approach.

I came across this:

https://github.com/webpack/webpack/blob/221d2cee4336a3873fc2c9972b7eb25a0dce028b/lib/WebAssemblyParser.js#L21-L22

I can suggest you to use the same tools I used, see [example in wasm-dce](https://github.com/xtuc/wasmgen/blob/master/src/printers/text.js#L36-L50), basically Babel for WebAssembly.

The tools are backend by https://github.com/xtuc/js-webassembly-interpreter, which can be used for many other things!

I already shared some of my ideas with @TheLarkInn :+1:

**Comment by sokra** [comment]
I tried to use `wasm-dce`, but it seem to have problems with `imports`

``` js
parseWat failed:
out.wast:2:40: error: unexpected token 0, expected ).
  (import "./module" "getNumber" (func 0 (result i32)))
                                       ^

Error: parseWat failed:
out.wast:2:40: error: unexpected token 0, expected ).
  (import "./module" "getNumber" (func 0 (result i32)))
                                       ^

    at Object.parseWat (D:\Repos\webpack\node_modules\wasm-dce\src\libwabt.js:19:13536)
    at module.exports (D:\Repos\webpack\node_modules\wasm-dce\src\index.js:59:21)
```

**Comment by xtuc** [comment]
Ah sorry about that, could you please share the binary? Is it the one used in the tests here?
