### ISSUE TITLE
Webpack4 - Modules Imported from Separate Chunk Initialized More Than Once

### ISSUE THREAD

**Issue by veebz** [webpack/webpack#6537]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
In webpack 3, modules are initialized exactly once.
In webpack@4.0.0-beta2, modules from another chunk are initialized each time they are imported.

This becomes problematic any time you have a module containing global state that is consumed by multiple other modules.  A more specific example would be [Redux with code splitting](https://gist.github.com/gaearon/0a2213881b5d53973514).  There are workarounds such as using the window object to store and reference information, but this change with Webpack4 may catch many by surprise.

**If the current behavior is a bug, please provide the steps to reproduce.**
I have created a repository to demo this behavior:
https://github.com/veebz/webpack-module-init-sample

**What is the expected behavior?**
The module should only be initialized once.  All global module state should persist.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
Chrome 64
Node v8.1.0
Webpack 4.0.0-beta2
Windows 10

**Comment by sokra** [comment]
Use `optimization.runtimeChunk: "single"` when using more than one entrypoint in a single page.

**Comment by veebz** [comment]
Thanks, that solves it.

**Comment by mqliutie** [comment]
@sokra  I don't use `extract-text-webpack-plugin` 

in my html file I used `<script src="./dist/app.js">` to reference `app.js`

but I have two entry point in a single page 

genare chunk file and `runtime.js`  chunk file have hash  If only reference `runtime.js` the app is paralyzed 

hope your help
