### ISSUE TITLE
Webpack imports wrong version of duplicate dependency

### ISSUE THREAD

**Issue by haggholm** [webpack/webpack#6538]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Part of our dependency tree:

```
@client/root@2.3.5
├─┬ @client/base@2.3.15
│ └─┬ @client/app-files@1.8.8
│   └─┬ pixel@0.0.4
│     └─┬ pixel-util@0.0.2
│       └── mime@1.6.0 
├── mime@2.2.0 
```

But importing `pixel` fails, because it actually ends up with `mime@2.2.0` (which is incompatible).

**If the current behavior is a bug, please provide the steps to reproduce.**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

Node 9.5.0
webpack-dev-middleware@1.12.2
webpack-dev-middleware@2.0.5
webpack-dev-server@2.11.1
webpack-inline-source-plugin@0.0.9
webpack-log@1.1.2
webpack-manifest-plugin@1.3.2
webpack-plugin@0.1.2
webpack-plugin@0.11.4
webpack-plugin@0.4.6
webpack-plugin@0.6.2
webpack-plugin@1.2.0
webpack-plugin@2.30.1
webpack-sources@1.1.0
webpack-sources@1.1.0 deduped
webpack-sources@1.1.0 deduped
webpack-sources@1.1.0 deduped
webpack-visualizer-plugin@0.1.11
webpack@3.11.0

**Comment by montogeek** [comment]
Could you please create a repository with a test case?

**Comment by sokra** [comment]
I bet on your `resolve.modules` uses `path.resolve(__dirname, "node_modules")`, which causes the problem.

**Comment by haggholm** [comment]
@sokra You bet correctly, that was the problem. Thanks!

**Comment by robstax** [comment]
i'm having a very similar issue... @haggholm what was your fix/workaround? did you just remove the `resolve.modules` property?
