### ISSUE TITLE
Object.create'd config causes output to be written to wrong path (when multiple entrypoints require CSS files)

### ISSUE THREAD

**Issue by sqs** [webpack/webpack#654]
Multiple entrypoints that use the extract-text-webpack-plugin to
require CSS cause CSS output to be written to the wrong path when the webpack config is created with Object.create.

This is a weird bug that I am able to reproduce but not isolate or solve (after a couple hours of trying). Basically, if you pass webpack a config object, it works--except if you wrapped that same config object in `Object.create`. I am guessing something is enumerating the properties in the wrong way, but I can't figure out where. I can't even determine if this is a webpack bug or a extract-text-webpack-plugin bug.

I made a repro at https://github.com/sqs/webpack-config-property-bug:

To reproduce, run `./test.sh`. First it runs webpack with a webpack.config.js whose
exported config is a standard JS object. Then it runs webpack with the
same webpack.config.js, except that its exported config is wrapped in
`Object.create(...)` (as is recommended in
[webpack-with-common-libs/gulpfile.js](https://github.com/webpack/webpack-with-common-libs/blob/617e7757868653854a7f32a73293efb4454c707d/gulpfile.js)).

The expected behavior is that both modes of running webpack produce
the same output. But the second mode (with Object.create) produces an
output dir `dist/home/$USER/...` with a `.css` extension but with JS
contents.

(The sample app is based on the
[Separate CSS bundle](http://webpack.github.io/docs/stylesheets.html#separate-css-bundle)
guide.)

**Comment by sqs** [comment]
In the meantime, the workaround is simple: don't use Object.create for webpack config if you are experiencing this issue. Usually you don't reuse the config object in a single webpack/gulp/etc. process for multiple kinds of builds anyway, so it's easy to just mutate the original config object instead of shallow cloning it with Object.create first.

If other people are experiencing this issue too and there hasn't been a fix, we could change the docs to mention this (but so far nobody else seems to be hitting it).

**Comment by jhnns** [comment]
Mhmmm yes... to be honest, it is very unusual to use prototype inheritance with config objects and I'd guess that most libraries would have problems with this.
