### ISSUE TITLE
webpack@4 - [name] identifier ignored in output filename

### ISSUE THREAD

**Issue by damianobarbati** [webpack/webpack#6543]
**Do you want to request a *feature* or report a *bug*?**
Maybe a bug or a renamed variable?

**What is the current behavior?**
Migrating from @3 to @4, here a simple config:
```
const path = require('path');
const webpack = require('webpack');

const config = module.exports = {
    entry: path.resolve('./app/index.js'),
    output: {
        path: path.resolve('./dist'),
        filename: '[name].js', //ignored?
    },
    profile: true,
    module: {
        rules: [{
            test: /\.(js|mjs|jsx)$/i,
            use: [{
                loader: 'babel-loader',
                options: {
                    cacheDirectory: true,
                },
            }],
        }],
    },
};
```

Here src/*index.js*: <== filename thus [name] should yield "index"
```
console.log('yo!');
```

**If the current behavior is a bug, please provide the steps to reproduce.**
`yarn webpack --mode development --config webpack.config.js`

**What is the expected behavior?**
I'm expecting a dist/index.js file but dist/main.js is created instead.

**Comment by montogeek** [comment]
What version of webpack 3 are you using?

**Comment by damianobarbati** [comment]
```
imac:yarsk damz$ cat node_modules/webpack/package.json | grep version
  "version": "4.0.0-beta.2",
```

**Comment by montogeek** [comment]
Even in webpack 3.11.0 you get `main.js`: https://github.com/montogeek/webpack-filename-output-bug

What version of webpack 3 are you using?

**Comment by montogeek** [comment]
You have to name your entry to get `index.js`:
```
 entry: {
   index: path.resolve('./src/index.js'),
 },
```

**Comment by damianobarbati** [comment]
It was that, thanks!

**Comment by montogeek** [comment]
Surprisingly, webpack docs does not mention it, something like: "`main` will be the default name", although you can deduce it by this example (https://webpack.js.org/concepts/entry-points/#single-entry-shorthand-syntax), in any case it would be better to say it explicitly.

**Comment by damianobarbati** [comment]
I don't know why but I was sure [name] yielded the filename without extension. It yields the entry label instead.
