### ISSUE TITLE
Should webpack forbid directly importing transitive dependencies?

### ISSUE THREAD

**Issue by samouri** [webpack/webpack#6547]
**Do you want to request a *feature* or report a *bug*?**
Feature I think! bugs are in the eye of the beholder :)

**What is the current behavior?**
Webpack allows for application code to depend directly on transitive dependencies

**If the current behavior is a bug, please provide the steps to reproduce.**
minimal example and short writeup is here: https://github.com/samouri/webpack-transitive-deps-question

**What is the expected behavior?**
I would expect that webpack would cause a ReferenceError at compile time if trying to import a transitive dependency from within application code.  Right now webpack will happily hum along and bundle anything in `node_modules`.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Directly depending on a transitive dependencies is bad practice and as far as I know, there isn't a use case for it. Forbidding devs from directly calling into transitive dependencies will help them fall into the pit of success.  Two issues that not having this can cause are:
1. Builds will be more fragile over time 
2. For large projects like the one I work on ([wp-calypso](https://github.com/Automattic/wp-calypso))  it can be difficult to ensure a module isn't bundled.  For example, lets say I wanted to disable the nodejs `path` module.  I could add `node: { path: false }` to the webpack config, but if the polyfill is also a transitive dependency then it can still get sneakily bundled if some file imports it. 

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
N/A

---

Please let me know if y'all think this is a good idea and I'll take a stab at implementing it!

**Comment by sokra** [comment]
webpack doesn't know about "dependencies" in the sense of package managers. It doesn't imply that you are using a package manager. So it doesn't know what your "dependencies" are.

But if this is an issue for you there is an eslint plugin to check this.
