### ISSUE TITLE
Relative url() in css with path *without* quotation marks not resolvable

### ISSUE THREAD

**Issue by fubar-coder** [webpack/webpack#6548]
**Do you want to request a *feature* or report a *bug*?**
A bug.

**What is the current behavior?**

Webpack fails to resolve relative paths in a CSS file with a relative url() whose path is not enclosed in quotation marks.

This is the error I get:

```
ERROR in ./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/devextreme/dist/css/dx.light.css
(Emitted value instead of an instance of Error) CssSyntaxError: C:\Test-Projekte\Angular6\angular-tour-of-heroes\node_modules\devextreme\dist\css\dx.light.css:3219:12: Can't resolve 'icons/dxicons.woff)%20format(%27woff%27),%20url(icons/dxicons.ttf)%20format(%27truetype%27' in 'C:\Test-Projekte\Angular6\angular-tour-of-heroes\node_modules\devextreme\dist\css'

  3217 | @font-face {
  3218 |   font-family: 'DXIcons';
> 3219 |   src: url(icons/dxicons.woff) format('woff'), url(icons/dxicons.ttf) format('truetype');
       |            ^
  3220 |   font-weight: normal;
  3221 |   font-style: normal;
```

**If the current behavior is a bug, please provide the steps to reproduce.**

I guess that it's a bug, because it's a change in behavior compared to previous versions. Example:

```css
@font-face {
  font-family: 'DXIcons';
  src: url(icons/dxicons.woff) format(woff)
}
```

**What is the expected behavior?**

No error message and a correctly resolved path.

**If this is a feature request, what is motivation or use case for changing the behavior?**

My motivation is clarify if the new behavior is intentional or if it's a regression.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

The problem occurs during an `npm run build`:

Node.js: 9.5.0
npm: 5.6.0
Webpack: 3.11.0
OS: Win10 1709

EDIT: It worked in 3.10.0

**Comment by evilebottnawi** [comment]
@fubar-coder not related to `webpack`
@webpack-bot move to postcss/postcss-loader
