### ISSUE TITLE
Copying files won't trigger a rebuild when in watch mode

### ISSUE THREAD

**Issue by alan-agius4** [webpack/webpack#6550]
**What is the current behavior?**
What I noticed is that when I copy a file the rebuild is not triggered even if I am in watch mode. 

The rebuild is triggered only after I change the contents of the copied file.

**If the current behaviour is a bug, please provide the steps to reproduce.**
> start webpack
> Copy a file and paste the file somewhere that webpack should pick.
> nothing happens unless you change the contents of the file.
 
Example
If you have setup webpack to compile typescript, create a file
**index.ts**
```ts
import './test';
```
Then for instance from your desktop copy and paste the below file next to `index.ts`
**test.ts**
```ts
export const x = 'foo';
```

**What is the expected behaviour?**
That a build is triggered when copying a file, that webpack has a loader for.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
```
Webpack: 3.11.0
Windows: 10
Node.js: 8.9.1
```

**Comment by evilebottnawi** [comment]
@alan-agius4 do you use `copy-webpack-plugin`?

**Comment by alan-agius4** [comment]
No, I meant when you copy the file manually. Example `ctrl+c` and `ctrl+p`
