### ISSUE TITLE
Transpiler is messing up the scope of anonymous functions with short hand syntax ()=>{}

### ISSUE THREAD

**Issue by devblazer** [webpack/webpack#6553]
Bug:

Whenever I specify a shorthand anonymous function like: var func = (a, b) { return a + b }
and call said function using func.call or func.apply, the context of 'this' is not what I assigned.

To reproduce:
```
const dotdotdot = ()=>{ return this + '...'}; 
let str = 'not working';
console.log(dotdotdot.call(str));
```

This should output 'not working...', but it does not, due to the context of 'this' being incorrect.

The context of this on an anonymous function can be dynamic when call or apply is used and should not be assumed as something else.

This may be a babel issue, I am not sure, if so feel free to move, re-assign, etc.

Also note that this issue is not new I first noticed it one to two years ago, its been around for a long time.

**Comment by sokra** [comment]
Arrow function don't have their own this scope.
