### ISSUE TITLE
Webpack 4 bug with vue.js this

### ISSUE THREAD

**Issue by hanxue** [webpack/webpack#6555]
### Error

I get an `undefined` variable in the generated `app.js` when I upgrade from Webpack 3 to Webpack 4

The relevant Vue.js source file and affected line in the generated `app.js` is [uploaded here](https://gist.github.com/hanxue/63eb5f03a4bd78df2111c9b64a625fcf) . Specifically [line 112,](https://gist.github.com/hanxue/63eb5f03a4bd78df2111c9b64a625fcf#file-pmi-vue-L102) with the variable reference `this.houseValue`

```
data: () => ({
    //...
    selectedFicoScore: '660-679',
    houseValue: accounting.formatMoney(300000,'$', 0),
    loanAmount: accounting.formatMoney(285000,'$', 0),
    //...
  }),
  validations: {
      // ...
      loanAmount: {
        required,
        between: between(0, 100000000),
        maxLength: maxLength(this.houseValue)
      },
```

### Workaround

Commenting out the line will remove the error, but will change the behaviour of the application. 

Node: v8.4.0
webpack: 4.0.0-beta.2
vue: 2.5.2

**Comment by sokra** [comment]
Looks correct to me. The `this` here is a top level this, which is undefined in ESM. Looks like a bug in your code.

**Comment by hanxue** [comment]
Oops, indeed that was a nested object literal.
