### ISSUE TITLE
Webpack 4 issue with eslint

### ISSUE THREAD

**Issue by hanxue** [webpack/webpack#6556]
### Problem

Unable to run eslint/eslint-loader when using Webpack 4, `npm run dev` results in this

Module build failed: TypeError: Cannot read property 'eslint' of undefined
    at Object.module.exports (/Users/hanxue/PPP/jinrong/node_modules/eslint-loader/index.js:148:17)

### Steps to reproduce

1. Use the Vue.js webpack template at https://github.com/vuejs-templates/webpack
2. Make the necessary changes to webpack.dev.conf.js and webpack.prod.conf.js per https://github.com/webpack/webpack/issues/6357
3. `npm run dev`

My webpack configuration and package.json: https://gist.github.com/hanxue/e395d04d0d316d2f587174f5ebc91b74

### Environment

Node: v8.4.0
webpack: 4.0.0-beta.2
vue: 2.5.2

**Comment by montogeek** [comment]
Thanks for the report, Would you mind creating a repository instead? It will make it easier to debug the problem

**Comment by sokra** [comment]
eslint-loader seem to try to access `this.options` which was removed.

As workaround use `new webpack.LoaderOptionsPlugin({ options: {} })`

**Comment by hanxue** [comment]
Thank you @sokra , adding the following to `webpack.dev.conf.js` made ESLint work with Webpack 4

```js
mode: "development",
  plugins: [
    new webpack.LoaderOptionsPlugin({ options: {} }),
```

**Comment by BenesFT** [comment]
good job

**Comment by Anima-t3d** [comment]
Fixed in eslint-loader v2: https://github.com/webpack-contrib/eslint-loader/issues/215
