### ISSUE TITLE
How to run the examples -  ENOENT: no such file or directory

### ISSUE THREAD

**Issue by Legends** [webpack/webpack#6558]
**Do you want to request a *feature* or report a *bug*?**
bug in examples or unsufficient documentation, to get them up and running.

**What is the current behavior?**

![image](https://user-images.githubusercontent.com/966368/36599696-86af08c8-18b0-11e8-85b9-3d4297fd50a3.png)

**If the current behavior is a bug, please provide the steps to reproduce.**

**Steps taken:**

1. Download webpack from the master-branch
2. I open cmd.exe as admin, `cd` to `webpack-master` root folder.
3. npm install
4. npm link webpack
5. npm run build:examples  --> Now I get:

![image](https://user-images.githubusercontent.com/966368/36599696-86af08c8-18b0-11e8-85b9-3d4297fd50a3.png)

**What is the expected behavior?**
running examples
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
Win10 x64, node 9.5 , webpack 3.11

**Comment by sokra** [comment]
Since webpack and webpack-cli has been splitted into two projects, but the examples need webpack-cli to run:
1. Checkout webpack-cli
2. `yarn link` in webpack-cli
3. `yarn link webpack-cli`

But there is an new problem with it: https://github.com/webpack/webpack-cli/pull/278

**Comment by Legends** [comment]
Sorry, I am from the .NET side, what do you mean with:

> 2. yarn link **in** webpack-cli

**Comment by montogeek** [comment]
It means:
1. `git clone https://github.com/webpack/webpack-cli`
2. `cd webpack-cli`
3. `yarn link`
4. `cd to/your/project`
5. `yarn link webpack-cli`

What it does is to create a symlink between webpack-cli and your project.

But you are using `npm`, in that case just replace `yarn` with `npm`

**Comment by Legends** [comment]
Thanks!
I did that now, but still get the error, perhaps of [this](webpack/webpack-cli#278) mentioned by @sokra

**Comment by Legends** [comment]
Will be fixed with [PR](https://github.com/webpack/webpack-cli/issues/378)
