### ISSUE TITLE
Add page to documentation that tracks webpack ecosystem status 

### ISSUE THREAD

**Issue by lencioni** [webpack/webpack#6560]
[On the Twittersphere, I recently tweeted](https://twitter.com/lencioni/status/966857043058425856):

> One of the more painful aspects of the previous couple of #webpack major version releases was waiting for all the related packages to publish compatible versions.

> Is there a webpack ecosystem status page to track compatibility progress for these events?

People seem to think this would be useful as a page in the webpack documentation. I think maybe having a table that lists each plugin or loader or whatever and how ready it is for any given webpack release would be awesome. I think relevant statuses might be unstarted, in progress, merged, and published.

Keeping this list up to date should be a community effort and might be a good, low-cost way to encourage folks to get involved and contribute to webpack documentation.

**Comment by sokra** [comment]
@webpack-bot move to webpack/webpack.js.org
