### ISSUE TITLE
Consider supporting webpack.config.mjs alongside webpack.config.js

### ISSUE THREAD

**Issue by TomasHubelbauer** [webpack/webpack#6566]
**Do you want to request a *feature* or report a *bug*?**
Feature.

**What is the current behavior?**
`webpack.config.mjs` cannot be used in place of `webpack.config.js`.

**What is the expected behavior?**
`webpack.config.mjs` could be used instead of `webpack.config.js`.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Consistency.

**Comment by sokra** [comment]
> It's a valid request, but not possible to do without changing the config loading to be asynchronous and using import() (only available as of node 9.5.0?)

That shouldn't be an issue. We already support exporting a promise from webpack.config.js.

**Comment by sokra** [comment]
@webpack-bot move to webpack/webpack-cli

**Comment by damianobarbati** [comment]
Is this approved? Can we define webpack.config.mjs in next versions?

**Comment by TomasHubelbauer** [comment]
@damianobarbati See the moved issue webpack/webpack-cli#282. This will probably take a good, good bit of time to be implemented and released.
