### ISSUE TITLE
webpack@4: uglify configuration [feat request]

### ISSUE THREAD

**Issue by damianobarbati** [webpack/webpack#6567]
- What is the intended way to configure uglify-es without explicitly disabling and then re-requiring uglify plugin with custom configuration?

- Shouldn't be "parallel" enabled by default? Looks like a great way to improve compiling times. https://github.com/webpack-contrib/uglifyjs-webpack-plugin#parallel

I'm asking because unfortunately uglify-es is broken right now and I'm getting `Uncaught TypeError: Assignment to constant variable.` all over my projects I attempted to migrate from webpack@3 to webpack@4.

Here is a suggested fix: https://github.com/mishoo/UglifyJS2/issues/2842#issuecomment-359527962
But I don't know how to translate `uglifyjs -m -c inline=false` to webpack uglify options 🤷🏻‍♂️

If I manage to finally migrate to webpack@4 I'll share the speed improvements I got on all of my (very big) projects 👍🏻

**Comment by montogeek** [comment]
If you read the README, you will find https://github.com/webpack-contrib/uglifyjs-webpack-plugin#uglifyoptions, then you will find `compress` options that is used by UglifyJS2 (https://github.com/mishoo/UglifyJS2/tree/harmony#compress-options)

So it would be: 
```
{
 compress: {
	inline: false
 }
}
```

**Comment by damianobarbati** [comment]
Yes @montogeek that's what I'm trying to do but how?
- if mode=production and I apply UglifyJsPlugin then "section" errors are thrown (because fired 2 times)
- if mode=development other optimizations are disabled (how do I enabled everything but uglify?)
- if mode=development with devtool=source-map and UglifyJsPlugin.sourcemap enabled I get sourcemap not to original sources but transpiled ones.

```
devtool: 'source-map',
plugins: [
    new UglifyJsPlugin({ <=== running uglifyjs 2 times if mode=production
        sourceMap: true, <=== sourcemap linking to transpiled code and not original source
        uglifyOptions: {
            inline: false, <=== current workaround...
        },
    });
  ]
```

**Comment by montogeek** [comment]
`uglifyOptions: { compress: { inline: false }}}`

**Comment by damianobarbati** [comment]
Solved with https://github.com/damianobarbati/yarsk/blob/50b6f352a13ec2e778fa8b252f915550b6132964/config/webpack.config.js#L110

**Comment by julbra** [comment]
Just digging further on this one, incorrect inlining occurs when one of the function's arguments name clashes with another const defined in the scope where that function is used.

for example:
```
const bar = 'qux'
function foo(bar) { return bar; }
foo();
```
Seems to cause the `TypeError: Assignment to constant variable.`

Also found out that inlining simple functions seems safe (inline: 1).

I now use the following:
```
new UglifyJsPlugin({
        uglifyOptions: {
          ecma: 8,
          compress: {
            inline: 1
          }
        }
      })
```

**Comment by Offirmo** [comment]
For fellow googlers looking to completely disable minification in production: https://github.com/webpack/webpack/issues/6619#issuecomment-370204173

**Comment by chrisdothtml** [comment]
@damianobarbati Just a heads up, the config you linked to is overriding the default webpack config for the uglify plugin, so since you didn't also include `cache` and `parallel` options, they're not applied (which can cause some significant build time differences in bigger builds).

I found this out the hard way after a very long time of dealing with high build times

**Comment by Maximaximum** [comment]
@chrisdothtml thanks a lot for your comment! I didn't notice that in the first time, but now when I add these options my build time decreases from ~1 min to ~15 sec!

**Comment by g4d** [comment]
> Solved with https://github.com/damianobarbati/yarsk/blob/50b6f352a13ec2e778fa8b252f915550b6132964/config/webpack.config.js#L110

@ damianobarbati FYI, link 404's.

**Comment by damianobarbati** [comment]
@g4d sorry, anyway I just moved to `terser` when I was using webpack.

Here a ref, maybe you can find anything useful for you: https://github.com/damianobarbati/webapp/blob/feature/webpack-old/webpack.config.js
