### ISSUE TITLE
Tapable.plugin is deprecated. Use new API on `.hooks` instead

### ISSUE THREAD

**Issue by julmot** [webpack/webpack#6568]
**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?**

![topic](https://user-images.githubusercontent.com/8310677/36646814-e5ecfbe2-1a7c-11e8-9a01-89c196249b2e.png)

https://travis-ci.org/julmot/form-components/builds/346048668#L4063-L4081

**If the current behavior is a bug, please provide the steps to reproduce.**

Run the build of [this repository](https://github.com/julmot/form-components) which uses [these settings](https://github.com/julmot/form-components/blob/greenkeeper/webpack-4.0.0/build/webpack.config.js). PR: https://github.com/julmot/form-components/pull/9

**What is the expected behavior?**

It shouldn't fail or provide a meaningful message that helps resolving the issue. The current message looks like an internal error.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

webpack v4
Win10
node v6.11.3

**Comment by sokra** [comment]
Did you upgrade the extract-text-webpack-plugin to latest version?

**Comment by Dirtyburger1338** [comment]
Just got the same issue directly after installing webpack

webpack 4.0.0
node 8.9.3
text-webpack-plugin 3.0.2

**Comment by chrste90** [comment]
I think you have to install `v4.0.0-alpha.0`.

As you can see in the release notes under Code Refactoring: `ExtractTextPlugin: update to new plugin system and API's`.

**Comment by julmot** [comment]
Can't imagine that relaying on alpha releases is intended.

**Comment by Dirtyburger1338** [comment]
using v4.0.0-alpha.0 worked for me

**Comment by julmot** [comment]
@sokra If using v4.0.0-alpha.0 works (can't confirm), is this the way to go?

**Comment by rgbkrk** [comment]
I'm no longer using `extract-text-webpack-plugin` anywhere, is there a way to find out which plugin is generating this warning?

**Comment by sokra** [comment]
`node --trace-depracation`

**Comment by hoqqun** [comment]
I had the same problem.but resolved it using version 3.11.0

**Comment by julmot** [comment]
@sokra What's the solution in this regard?

**Comment by montogeek** [comment]
@julmot Try with `extract-text-webpack-plugin@next`

**Comment by yinsang** [comment]
[extract-text-webpack-plugin](https://github.com/webpack-contrib/extract-text-webpack-plugin/releases)
`npm i -D extract-text-webpack-plugin@next`

**Comment by zhy023** [comment]
No Works with extract-text-webpack-plugin v4.0.0-beta.0

**Comment by julmot** [comment]
Doesn't work for me either, just gives a different error message:
```
Module build failed: ModuleBuildError: Module build failed: TypeError: Cannot read property 'resolveUrlLoader' of undefined
```

**Comment by montogeek** [comment]
@julmot Could you please submit an issue for that error?

**Comment by misostack** [comment]
Hello guys, i've found the way to resolve this problem. You can check my config here, hope it will help you.

http://io.misostack.com/posts/webpack-003/

**Comment by Slapbox** [comment]
I'm sure using `extract-text-webpack-plugin@next` works if you're getting the error from `extract-text-webpack`, but what if you're not?

**Comment by d2phap** [comment]
`extract-text-webpack-plugin@next` works for me

**Comment by julmot** [comment]
@montogeek The issue that occured afterwards seems to be covered in: https://github.com/bholloway/resolve-url-loader/issues/79

@sokra It's annoying that you're ignoring my questions.

**Comment by ooflorent** [comment]
In order to use `webpack@4.0.1` you must install `extract-text-webpack-plugin@4.0.0-beta.0`. What you are seeing is not an error but a deprecation notice. If there actually is an error, you could [open an issue on ETWP repository](https://github.com/webpack-contrib/extract-text-webpack-plugin/issues).

**Comment by Slapbox** [comment]
@ooflorent I assume the reason there are so many people reporting this as an error and not just a notice is that something else is failing silently, and without anywhere else to look people believe this to be the error. I for one cannot get Webpack 4 working, but no error messages.

**Comment by evilebottnawi** [comment]
@Slapbox try to comment plugins and loader step by step

**Comment by je-lopez** [comment]
I'm still getting:
```
DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead
```
with:
```
"html-webpack-plugin": "^3.0.4"
"extract-text-webpack-plugin": "^4.0.0-beta.0"
```
same with or without `"extract-text-webpack-plugin": "^4.0.0-beta.0"`

**Comment by wiejakp** [comment]
Also having same issue:

```user@server:/var/www/example.com# ./node_modules/.bin/encore production
Running webpack ...

(node:26427) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
/var/www/example.com/node_modules/webpack/lib/Chunk.js:460
                throw new Error(
                ^

Error: Chunk.entrypoints: Use Chunks.groupsIterable and filter by instanceof Entrypoint instead
    at Chunk.get (/var/www/example.com/node_modules/webpack/lib/Chunk.js:460:9)
    at /var/www/example.com/node_modules/@symfony/webpack-encore/node_modules/extract-text-webpack-plugin/dist/index.js:176:48
    at Array.forEach (<anonymous>)
    at /var/www/example.com/node_modules/@symfony/webpack-encore/node_modules/extract-text-webpack-plugin/dist/index.js:171:18
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/var/www/example.com/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:7:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/var/www/example.com/node_modules/webpack/node_modules/tapable/lib/Hook.js:35:21)
    at Compilation.seal (/var/www/example.com/node_modules/webpack/lib/Compilation.js:881:27)
    at hooks.make.callAsync.err (/var/www/example.com/node_modules/webpack/lib/Compiler.js:464:17)
    at _done (eval at create (/var/www/example.com/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:9:1)
    at _err1 (eval at create (/var/www/example.com/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:32:22)
    at _addModuleChain (/var/www/example.com/node_modules/webpack/lib/Compilation.js:749:12)
    at processModuleDependencies.err (/var/www/example.com/node_modules/webpack/lib/Compilation.js:688:9)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)```

`package.json`:

```user@server:/var/www/example.com# cat package.json 
{
    "devDependencies": {
        "@symfony/webpack-encore": "^0.17.0",
        "webpack-cli": "^2.0.10",
        "webpack-notifier": "^1.5.1"
    },
    "license": "UNLICENSED",
    "private": true,
    "scripts": {
        "dev-server": "encore dev-server",
        "dev": "encore dev",
        "watch": "encore dev --watch",
        "build": "encore production"
    },
    "dependencies": {
        "bootstrap-sass": "^3.3.7",
        "extract-text-webpack-plugin": "4.0.0-beta.0",
        "jquery": "^3.3.1",
        "node-sass": "^4.7.2",
        "sass-loader": "^6.0.6",
        "webpack": "^4.0.1"
    }
}```

Also getting `yarn run encore dev` error which is weird:

```error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c /var/www/example.com/node_modules/.bin/encore dev
Directory: /var/www/example.com
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/var/www/example.com/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.```

**Comment by retorquere** [comment]
I don't have extract-text-webpack-plugin installed but I'm still getting the deprecation warning: `yarn list | grep text-web` returns nothing

**Comment by ooflorent** [comment]
@retorquere Currently multiple plugins use these deprecated APIs. You can use node's `--trace-deprecation` flag to identify which vendor is involved and open an issue on its repository.

**Comment by retorquere** [comment]
There was already an [open issue](https://github.com/aackerman/circular-dependency-plugin/issues/32) for it so I've joined that.

**Comment by lukasztyminski** [comment]
Plugin > extract-text-webpack-plugin@next  It helped me

**Comment by pgilad** [comment]
Happens:
- https://github.com/jantimon/html-webpack-plugin/issues/874
- https://github.com/webpack/webpack-dev-server/issues/1324

**Comment by brigand** [comment]
Is using .hooks documented somewhere?

**Comment by sanu-explore** [comment]
I have been facing following issue after updating webpack4. I was thinking it is an issue with "extract-text-webpack-plugin (4.0.0-beta.0)". But to debug I started removing plugins one by one. When remove "webpack-manifest-plugin" things started working. Sometimes other plugins also make "Tapable.plugin" issues

(node:8445) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
Unhandled rejection Error: Chunk.initial was removed. Use canBeInitial/isOnlyInitial()
    at Chunk.get initial [as initial] (/home/xxxxxx/Documents/Marketing/form-framework/node_modules/webpack/lib/Chunk.js:72:9)

webpack-manifest-plugin

**Comment by deanshub** [comment]
the ```--progress``` flag also prompts the warning

**Comment by joe-bader** [comment]
Same as @deanshub. Removing the '--progress' flag got rid of the warning for me:

OLD
`    "build": "webpack --progress --bail --env dist -p",
    "start": "webpack-dev-server --progress --mode development --watch-content-base --open"`

NEW
`    "build": "webpack --bail --env dist -p",
    "start": "webpack-dev-server --mode development --watch-content-base --open"`

**Comment by jaschaio** [comment]
resolved by using `npm install extract-text-webpack-plugin@next --save-dev`

**Comment by matthew-gordon** [comment]
I had the same issue.. So far, my issue was using the uglify plugin..

```
const path = require('path');
const webpack = require('webpack');
const nodeExternals = require('webpack-node-externals');
const UglifyJsPlugin = require('uglifyjs-webpack-plugin');

module.exports = {
  target: 'node',
  entry: './src/index.js',
  output: {
    filename: 'server.js',
    path: path.resolve(__dirname, 'dist'),
  },
  mode: 'production',
  module: {
    rules: [
      {
        enforce: 'pre',
        test: /\.js?$/,
        exclude: [/node_modules/],
        loader: 'eslint-loader',
      },
      {
        test: /\.js?$/,
        loader: 'babel-loader',
        exclude: [/node_modules/],
        options: {
          presets: [
            ['env', {
              targets: {
                node: "current",
              }
            }]
          ],
          plugins: ['transform-object-rest-spread']
        }
      }
    ]
  },
  plugins: [
    new webpack.LoaderOptionsPlugin({ options: {} }),
  ],
  optimization: {
    minimizer: [
      new UglifyJsPlugin({
        cache: true,
        uglifyOptions: {
          ecma: 8,
        },
      })
    ]
  },
  externals: [nodeExternals()],
};
```
new config resolved the problem for me...

```
const path = require('path');
const webpack = require('webpack');
const nodeExternals = require('webpack-node-externals');

module.exports = {
  target: 'node',
  entry: './src/index.js',
  output: {
    filename: 'server.js',
    path: path.resolve(__dirname, 'dist'),
  },
  mode: 'production',
  module: {
    rules: [
      {
        enforce: 'pre',
        test: /\.js?$/,
        exclude: [/node_modules/],
        loader: 'eslint-loader',
      },
      {
        test: /\.js?$/,
        loader: 'babel-loader',
        exclude: [/node_modules/],
        options: {
          presets: [
            ['env', {
              targets: {
                node: "current",
              }
            }]
          ],
          plugins: ['transform-object-rest-spread']
        }
      }
    ]
  },
  plugins: [
    new webpack.LoaderOptionsPlugin({ options: {} }),
  ],
  externals: [nodeExternals()],
};
```

**Comment by zebrallel** [comment]
extract-text-webpack-plugin@next works 👍

**Comment by dtothefp** [comment]
@sokra I'm getting this when using `compiler.plugin('done'` with Webpack `v4.1.1`

**Comment by ooflorent** [comment]
@dtothefp That's expected. In webpack 4 you should use hooks:

```js
compiler.hooks.done.tap("MyPlugin", () => { … })

**Comment by ChoppyThing** [comment]
Same error here. On my side extract-text-webpack-plugin@next isn't helping.

**Comment by MartinX3** [comment]
I can confirm that warning with @next

Am 14. März 2018 17:32:21 MEZ schrieb Choppy Thing <notifications@github.com>:
>Same error here. On my side extract-text-webpack-plugin@next isn't
>helping.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/webpack/webpack/issues/6568#issuecomment-373087137

-- 
Mit freundlichen Grüßen

Martin Dünkelmann

**Comment by aaronshaf** [comment]
Still getting the same issue with `next` :-(

**Comment by bmf-san** [comment]
I have a same error too.

before
```javascript
  "devDependencies": {
    "css-loader": "^0.28.10",
    "extract-text-webpack-plugin": "^3.0.2",
    "gulp": "^3.8.8",
    "node-sass": "^4.7.2",
    "sass-loader": "^6.0.7",
    "style-loader": "^0.20.3",
    "webpack": "^4.1.1",
    "webpack-cli": "^2.0.12"
  },
```

after
  "devDependencies": {
    "css-loader": "^0.28.10",
    "extract-text-webpack-plugin": "^4.0.0-beta.0",  // updated by `npm i -D extract-text-webpack-plugin@next` fnpm i -D extract-text-webpack-plugin@next`
    "gulp": "^3.8.8",
    "node-sass": "^4.7.2",
    "sass-loader": "^6.0.7",
    "style-loader": "^0.20.3",
    "webpack": "^4.1.1",
    "webpack-cli": "^2.0.12"
  },

and I've solve it.

**Comment by MartinX3** [comment]
"devDependencies": {
"extract-text-webpack-plugin": "^4.0.0-beta.0",
},

Still get the error

**Comment by ooflorent** [comment]
For everyone commenting here about using the latest version of _X_ and still having the notices: Please run webpack using `node --trace-deprecation ./node_modules/.bin/webpack`. **This is the only way to identify which package is using deprecated APIs**.

If the stack trace shows that `extract-text-webpack-plugin` is responsible for the notice, please open an issue on its repository.

**Comment by MartinX3** [comment]
No configuration file found and no output filename configured via CLI option.
A configuration file could be named 'webpack.config.js' in the current directory.
Use --help to display the CLI options.

**Comment by ooflorent** [comment]
@MartinX3 I've submitted a PR (see geowarin/friendly-errors-webpack-plugin#63)

**Comment by fuchao2012** [comment]
Sorry to say, migrate to Webpack 4 now, sucks!!!

**Comment by mqliutie** [comment]
I'm no longer using extract-text-webpack-plugin anywhere
The same notice here

**Comment by Fenntasy** [comment]
I add the same problem and the deprecation notice is linked to `uglifyjs-webpack-plugin`.

I checked the version installed via npm:

```
npm list uglifyjs-webpack-plugin
└─┬ webpack@4.1.1
  └── uglifyjs-webpack-plugin@1.2.0
```

I wanted to use the why function of yarn and I was surprised to not have the `.hook` warning anymore and justly:

```
❯ yarn list uglifyjs-webpack-plugin
└─ uglifyjs-webpack-plugin@1.2.4
```

Seems like npm is not installing the latest dependency for `uglifyjs-webpack-plugin`, I can't explain why but this seems to be the problem.

**Comment by evilebottnawi** [comment]
@Fenntasy `npm/yarn cache clear && npm/yarn install`

**Comment by Fenntasy** [comment]
Well...

```
npm cache clear
npm ERR! As of npm@5, the npm cache self-heals from corruption issues and data extracted from the cache is guaranteed to be valid. If you want to make sure everything is consistent, use 'npm cache verify' instead.
npm ERR!
npm ERR! If you're sure you want to delete the entire cache, rerun this command with --force.
```

To be sure, I tried `npm cache verify` but it does not change anything.
`npm cache clear --force` did not change anything either (which is somewhat reassuring considered the previous message, it really self heal, it just still has an error).
I even tried upgrading npm to 5.7.1 but it did not change the fact that npm does not want to install the last version of `uglifyjs-webpack-plugin`

**Comment by julmot** [comment]
@Fenntasy Delete the node_modules folder and try installing again

**Comment by Fenntasy** [comment]
I did that between every try ^^'.

I'm not saying that because I have the problem, just pointing to a potential way of discovering the problem or a way out (using yarn).

**Comment by kinsomicrote** [comment]
I have tried all the solutions above and still get the same error. I even went as far as removing all plugins from my config file and got the same error.
When I try to do a node trace to figure out the cause of the problem, I get the error;

```
ERROR in Entry module not found: Error: Can't resolve './src' in '/home/jioke/lab/altalabs/ui'
```

What could I possibly be doing wrong?

**Comment by ooflorent** [comment]
@kinsomicrote please open an issue to help us diagnose the problem.

**Comment by RobertMcReed** [comment]
For anyone still reading this and struggling with `extract-text-webpack-plugin`, first off I will say that the `@next` solution worked for me. 

However, it seems that `extract-text-webpack-plugin` is being replaced with `mini-css-extract-plugin` for weback4.

See [this issue](https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/755#issuecomment-374548202) for reference.

**Comment by hadnet** [comment]
Just remember, mini-css-extract-plugin requires webpack >= 4.1

**Comment by jstarnate16** [comment]
Sean Larkin just said in his [blog post](https://medium.com/webpack/webpack-4-released-today-6cdb994702d4) about the release of Webpack 4 that it won't support ExtractTextPlugin anymore. CSS files will be simply added to the entry points for bundling (which is way better).

**Comment by Paveldub** [comment]
**extract-text-webpack-plugin@next works** for me

**Comment by wellyshen** [comment]
I have used `mini-css-extract-plugin` but this issue still exist. Are there other libraries will also causes this issue?

**Comment by Tiendq** [comment]
Same error with `"webpack": "^4.4.1"` and `"extract-text-webpack-plugin": "^3.0.2"`.

Fixed with `extract-text-webpack-plugin@next` (currently `extract-text-webpack-plugin@4.0.0-beta.0`).

**Comment by ooflorent** [comment]
Here is a quick summary for everyone encountering this message.

### What is this message?

webpack 4 is using a new plugin system and deprecates the previous APIs. There are 2 new warnings:

```
DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead
DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
```

**These are warnings.** They are outputted to the console to _warn_ our users that they are using an outdated API and should migrate to the newest.

### How _bad_ are these warnings?

They are only a textual information, not errors. **If you see a `DeprecationWarning` you can ignore it** until you have to update to the next major version of webpack.

### How to get rid of them?

Update your webpack dependencies (webpack, loaders, plugins, …). If all your dependencies have done the migration, the warnings should be gone. If they are not and **you can help us and the plugin authors** to fix this!

1. Identify who raises the warning by **getting the stracktrace**:
    - add `process.traceDeprecation = true` at the top of your config
    - or run you node process using the `--trace-deprecation` flag

2. The stracktrace will be similar to this:
    ```
    (node:10213) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
        at FriendlyErrorsWebpackPlugin.apply (./node_modules/friendly-errors-webpack-plugin/src/friendly-errors-plugin.js:39:14)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
             this plugin is using a                                it is defined in
                deprecated API                                       this package

        at webpack (./node_modules/webpack/lib/webpack.js:37:12)
        at processOptions (./node_modules/webpack-cli/bin/webpack.js:436:16)
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:160:7)
        at Function.Module.runMain (module.js:703:11)
        at startup (bootstrap_node.js:193:16)
        at bootstrap_node.js:617:3
    ```
     In the above stacktrace, `FriendlyErrorsWebpackPlugin` is causing the warning.

3. **Open an issue on the plugin's (or loader's) repository** and include the stacktrace so its author could identify what is causing the warning.

If you absolutely want to remove them, you can disable the deprecation notices within your configuration by adding the following statement:

```js
// Ignore all deprecations and hope that nothing will silently break in the future.
process.noDeprecation = true;
```
