### ISSUE TITLE
Update list of loaders with coffee-jsx-loader

### ISSUE THREAD

**Issue by jsifalda** [webpack/webpack#657]
Hello there, 
is here way who to update docs? I would like to add coffee-jsx-loader into "dialects" section in list of loaders there http://webpack.github.io/docs/list-of-loaders.html. 

In the list can be something like:
coffee-jsx : Loads coffee-script with JSX like JavaScript

The loader has repo here https://github.com/jsifalda/coffee-jsx-loader.

**Comment by sokra** [comment]
You can edit the page with the edit button on the top-right corner.

**Comment by jsifalda** [comment]
Thanks!
