### ISSUE TITLE
Webpack Should Include Version in Exports

### ISSUE THREAD

**Issue by shellscape** [webpack/webpack#6573]
**Do you want to request a *feature* or report a *bug*?**

Feature/Improvement

**What is the current behavior?**

Users must load the package and manually parse the package version to determine the version of webpack in use.

**If the current behavior is a bug, please provide the steps to reproduce.**

n/a

**What is the expected behavior?**

As per many large, popular packages do, webpack's default export should include a field containing the current version.

**If this is a feature request, what is motivation or use case for changing the behavior?**

Ease of use, user experience improvement, less error prone than manually parsing.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

n/a
``

**Comment by sokra** [comment]
This was reported before by somebody else, I told to "send a PR" but I guess this never happened.
But it definitely makes sense to include the version.

**Comment by nveenjain** [comment]
Implemented it in #6575
