### ISSUE TITLE
Webpack GC error on command 'webpack -p'

### ISSUE THREAD

**Issue by ViswanathLekshmanan** [webpack/webpack#6574]
**What is the current behavior?**
Should build successfully

**If the current behavior is a bug, please provide the steps to reproduce.**
use command 'webpack-p'

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

Node: v6.9.1, MAC OSX: Sierra 10.12.6, webpack: 3.10.0

<--- Last few GCs --->
  232397 ms: Mark-sweep 1226.7 (1404.5) -> 1226.7 (1406.5) MB, 1547.2 / 0.0 ms [allocation failure] [GC in old space requ
ested].
  233993 ms: Mark-sweep 1226.7 (1406.5) -> 1226.7 (1406.5) MB, 1595.5 / 0.0 ms [allocation failure] [GC in old space requ
ested].
  235682 ms: Mark-sweep 1226.7 (1406.5) -> 1235.0 (1404.5) MB, 1688.6 / 0.0 ms [last resort gc].
  237370 ms: Mark-sweep 1235.0 (1404.5) -> 1243.3 (1404.5) MB, 1687.4 / 0.0 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x6270bccfb51 <JS Object>
    2: _visit [0x6270bc04381 <undefined>:~1337] [pc=0x2cb709ce8959] (this=0x2f1a1a2fbaf9 <a TreeWalker with map 0x9f4b5a12069>,node=0x1f1ac4a2f651 <an AST_Dot with map 0x397799520d41>,descend=0x281b2fd04401 <JS Function (SharedFunctionInfo 0x13659bdc9209)>)
    3: _walk [0x6270bc04381 <undefined>:~1059] [pc=0x2cb709ced51e] (this=0x1f1ac4a2f651 <an AST_Dot with map 0x397799520d41>,visitor=0x2f1a1...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::Factory::NewFixedArray(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 5: v8::internal::Handle<v8::internal::TypeFeedbackMetadata> v8::internal::TypeFeedbackMetadata::New<v8::internal::FeedbackVectorSpec>(v8::internal::Isolate*, v8::internal::FeedbackVectorSpec const*) [/usr/local/bin/node]
 6: v8::internal::(anonymous namespace)::EnsureFeedbackVector(v8::internal::CompilationInfo*) [/usr/local/bin/node]
 7: v8::internal::(anonymous namespace)::GenerateBaselineCode(v8::internal::CompilationInfo*) [/usr/local/bin/node]
 8: v8::internal::(anonymous namespace)::GetUnoptimizedCodeCommon(v8::internal::CompilationInfo*) [/usr/local/bin/node]
 9: v8::internal::Compiler::Compile(v8::internal::Handle<v8::internal::JSFunction>, v8::internal::Compiler::ClearExceptionFlag) [/usr/local/bin/node]
10: v8::internal::Runtime_CompileLazy(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
11: 0x2cb7040092a7
Abort trap: 6

**Comment by sokra** [comment]
Increase the node.js memory `--max-old-space-size 8096`

**Comment by ooflorent** [comment]
See the above comment.
If the problem persists in webpack 4, please open an issue on [`webpack-cli` repository](https://github.com/webpack/webpack-cli/issues).
