### ISSUE TITLE
webpack 4's "export default" wrapping of dynamic import()s when target is commonjs

### ISSUE THREAD

**Issue by AviVahl** [webpack/webpack#6576]
**What is the current behavior?**
In webpack 4, when the target module is using commonjs, the exports are now being automatically wrapped as namespace object with a default export.

So if I call `import('react')`, the type I got in webpack 3 was `Promise<{createElement, Component, ...}>`, while webpack 4 now returns `Promise<{default: {createElement, Component, ...}}>`.

This behavior breaks in TypeScript projects (ones that use ts-loader alongside webpack), as the type system is not aware of the wrapping, and the type of the resolved Promise value no longer matches the newly wrapped namespace object.

**What is the expected behavior?**
I'm not sure whether this behavior was changed to match some standard or module interoperability, but the implications on my projects are rather large.

The truth is I'm not sure how the module system should behave in such cases (mixing cjs modules). I would personally expect it to match whatever the Node team has in store for 9-10+ versions.

Would it be possible to have a configuration flag to turn this auto module wrapping off?

**Comment by montogeek** [comment]
You can learn more about this change at https://medium.com/webpack/webpack-4-import-and-commonjs-d619d626b655
I think there is some work being done from ts-loader to make it compatible with webpack 4

**Comment by AviVahl** [comment]
I fail to understand the logic in the blog post:
> webpack 4 will now create a artificial namespace object for the CommonJs module, to let import() consistently resolve to namespace objects.

Consistent, in my view, is:
```
import {createElement, Component} from 'react'

async function myLoader() {
  const {createElement, Component} = await import('react')
  ....
}
```
The extra wrapping done for the `import()`s in webpack 4 now breaks the above code, doesn't it?
One would have to:
```
const {default: {createElement, Component}} = await import('react');
```

**Comment by sokra** [comment]
cc @johnnyreilly

**Comment by sokra** [comment]
The `default` export now exists when `import()`ing CJS and points to the `module.exports` value.

**Comment by AviVahl** [comment]
Verified as fixed. Thanks for the quick bug-fix!
