### ISSUE TITLE
Webpack 4.0.0 command tutorial

### ISSUE THREAD

**Issue by mihai011** [webpack/webpack#6577]
Report a bug.

I followed the steps from your official "Getting started" page. The latest version is 4.0.0. but the page is referring to version 3.9.1. When i followed the steps with version 4.0.0. the output of the "npx webpack " command was not the same as the one with 3.9.1.The bundle was produced in file "main.js" not "bundle.js". When i followed the tutorial with the 3.9.1 version installed all was well.

Can you please provide a updated version for 4.0.0. version?

**Comment by sokra** [comment]
@webpack-bot move to webpack/webpack.js.org
