### ISSUE TITLE
Webpack 4.0 has incorrect peerDep uglifyjs-webpack-plugin@1.1.8

### ISSUE THREAD

**Issue by stnwk** [webpack/webpack#6578]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

When having `webpack 4.0` installed you get the following warning by npm/yarn

```
"webpack > uglifyjs-webpack-plugin@1.1.8" has incorrect peer dependency "webpack@^2.0.0 || ^3.0.0".
```

Although there is already a newer version of uglifyjs-webpack-plugin 1.2.2 https://github.com/webpack-contrib/uglifyjs-webpack-plugin/releases/tag/v1.2.2, that adds webpack 4.x as peerDep, webpack itself still only has version 1.1.8 in its deps.

**What is the expected behavior?**
Upgrade required uglifyjs-webpack-plugin to 1.2.2 in package.json

**Comment by evilebottnawi** [comment]
@stnwk `npm cache clear --force && npm install`

**Comment by stnwk** [comment]
@evilebottnawi 

I ran `yarn cache clean` (and `npm cache clear --force), even removed the `node_modules` folder and still got the described warning upon runnning `yarn install` :/

**Comment by evilebottnawi** [comment]
@stnwk maybe you have global installation?

**Comment by stnwk** [comment]
`yarn which webpack` outputs the path to the local webpack node_module.
Same for `uglifyjs-webpack-plugin`

**Comment by stnwk** [comment]
Running `yarn upgrade uglifyjs-webpack-plugin` did not help, but apparantely I didn't have the latest yarn version installed.

As soon as I updated the warning was gone.
Thanks for your support! :)
