### ISSUE TITLE
Cannot install webpack 4.0.0 using node 6.11.4 (current Ubuntu)

### ISSUE THREAD

**Issue by webmaster128** [webpack/webpack#6579]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

I cannot use the latest stable webpack with node v6.11.4 (version shipped with the current Ubuntu).

**If the current behavior is a bug, please provide the steps to reproduce.**

```
mkdir webpack-node-6.11.4 && cd webpack-node-6.11.4
yarn init -y
yarn add webpack --dev
```

this leads to

```
yarn add v1.3.2
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
error enhanced-resolve@4.0.0: The engine "node" is incompatible with this module. Expected version ">=6.11.5".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**What is the expected behavior?**

webpack can be installed

**If this is a feature request, what is motivation or use case for changing the behavior?**

–

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

```
$ node --version
v6.11.4
$ yarn --version
1.3.2
```

Ubuntu 17.04 with nodejs installed from the [packages](https://packages.ubuntu.com/artful/nodejs)

**Comment by montogeek** [comment]
From @sokra twitter: https://twitter.com/wSokra/status/967852475918274561

**Comment by montogeek** [comment]
In this specific case enhanced-resolve dependency was updated to ES6 https://github.com/webpack/enhanced-resolve/pull/132

**Comment by webmaster128** [comment]
Regarding twitter: this is a statement on performance, not compatibility. The Webpack 4 release notes mention that Node.js 4 support was dropped, not Nodejs 6.

Regarding enhanced-resolve dependency: thanks for the source of the change. However, a feature upgrade should not affect the patch release (v6.11.4 vs. v6.11.5).

**Comment by ematipico** [comment]
Unless there's a security fix

**Comment by sokra** [comment]
Maybe @TheLarkInn can say why this version was selected?

**Comment by TheLarkInn** [comment]
It was at the time the latest version of 6. When choosing this version we seeked the advice of Node Evangelists who said that we should be supporting at the minimum the latest patch of Node 6 and no further back. So are you suggesting that we should only concern ourselves with `>=6.11`?

**Comment by webmaster128** [comment]
In #132 it is stated, that 6.4 supports all required features, so this might be a good setting. Given http://node.green, if 6.4 is not sufficient, the next step would be 6.5.0+

Additionally it should be added to the Webpack 4 release notes, which Node versions have been dropped.

**Comment by anthonator** [comment]
I'm seeing this when using node 9.4 as well.

```
 The engine "node" is incompatible with this module. Expected version ">= 9.4.0".
```

I'm assuming the expected version it's printing is whatever you have configured in the `engines` section of package.json.

**Comment by webmaster128** [comment]
@anthonator for which module does this happen for you? See e.g. this error message

> error **enhanced-resolve@4.0.0**: The engine "node" is incompatible with this module. Expected version ">=6.11.5".

**Comment by webmaster128** [comment]
Assuming you do not want to care about older versions of the 6.x branch, I think the best idea is to set the min version to 6.11. 6.11 is LTS, installed on current Ubuntu and should be equal to 6.11.5 in terms of features.

**Comment by mmswi** [comment]
Just tried running 
`yarn add webpack webpack-dev-server path`
`yarn add v0.27.5`
`[1/4] Resolving packages...`
`[2/4] Fetching packages...`
`error enhanced-resolve@4.0.0: The engine "node" is incompatible with this module. Expected version ">=6.11.5".`
`error Found incompatible module`
`info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.`

**Comment by rbelliard-vivial** [comment]
I have the same issue @thomasmichaelwallace has -- Our environments have to match what AWS Lambda supports and Webpack `>= 4` is out of the question, for no clear reason. :/

**Comment by thomasmichaelwallace** [comment]
(n.b. for now I've just switched our build environment up to 6.11.5- and nothing has gone wrong; but it's arguably a dangerous game not matching versions across build, test and deploy.)

**Comment by TheLarkInn** [comment]
We should change this to 6.9 after speaking with multiple members of the Node Team I wanted to verify that this would be appropriate. 

We will take PRs here but before I can merge the PR to webpack/webpack we need to ensure our depenent packages align with this as well.

**Comment by thomasmichaelwallace** [comment]
OK-

I started putting together a pull request building with node v.6.9.0 and I discovered why someone decided to bump the engine up to v6.11.5:

```error enhanced-resolve@4.0.0: The engine "node" is incompatible with this module. Expected version ">=6.11.5".```

With a personal build of enhanced-resolve with the engine dropped to 6.9.0 all tests seem to pass and everything builds ok for me. But it does mean this is a two stage fix!

So, once I've got https://github.com/webpack/enhanced-resolve/issues/141 resolved and the corresponding PR accepted, I'll then upgrade my dependencies and make a PR with the engine change here.

**Comment by thomasmichaelwallace** [comment]
PR has been merged on enhanced-resolve. However we'll have to wait until a release until any PR I make here will work.

I don't suppose anyone could give me a hint on when that would be? Or how to watch effectively for it?

n.b. anyone coming back here who spots enhanced-resolve is on > 4.0.0, mention here and I'll get my PR for webpack updated :)

**Comment by rlayeh** [comment]
Any chance that node version will be set to 6.9 any time soon?

**Comment by Hamms** [comment]
@ooflorent would it be possible to release a new version of enhanced-resolve so we can get this fix in webpack?

**Comment by myklt** [comment]
Are there any plans to release `webpack` with a lower required version of `node`? I see that blocking dependency was updated some time ago: https://github.com/webpack/enhanced-resolve/pull/142 . Thanks!

**Comment by thomasmichaelwallace** [comment]
I've just found some time to take another look at this, and it seems that the build is now blocked because webpack depends on eslint@5.4.0, which in turn requires node version "^6.14.0 || ^8.10.0 || >=9.10.0".

It's worth noting, however, that my reasoning to drop the supported version lower is no longer quite as valid because Lambda now supports Node v8.10.
