### ISSUE TITLE
Webpack with react and lodash makes bundle.js more than 800kb

### ISSUE THREAD

**Issue by vvwind** [webpack/webpack#658]
I'm new to webpack, and many info about this issue is on browserify. I switched to webpack and had the same issue.
The thing is - I don't really know is this issue at all or not? Is it ok to have 800kb js file for using node module loader system?

**Comment by jhnns** [comment]
Sorry, that's too vague. You need to give us information about what modules have been included... 800kb is too much. Webpack's default module runtime is roughly 100 LOC so that shouldn't be the problem.

However, I have one guess: lodash split the codebase into small modules recently which leads to lots of redundant modules in a deep dependency tree (as npm is creating it). You could try to install lodash via bower (which uses a flat dependency tree) and check if the problems still exists.

**Comment by nelix** [comment]
Another idea would be to explicitly require the bits you want from lodash:
```javascript
const _each = require('lodash-node/modern/collections/forEach');
```

Also you can make react much smaller by doing a production build:
```javascript
new webpack.DefinePlugin({
    'process.env': {
      // This has effect on the react lib size
      'NODE_ENV': JSON.stringify('production'),
    },
  })
```

**Comment by vvwind** [comment]
@nelix @jhnns thank you!
The problem was that I used non-minified version of libs. The thing is, react by itself is pretty big (around 170kb min), so after adding minification all is ok.
For people, experiencing similar problem, my config:

```javascript
var webpack = require('webpack');

module.exports = {
    entry: "./src.js",
    output: {
        path: __dirname,
        filename: "bundle.js"
    },
    module: {
        loaders: [
            { loader: "jsx-loader" }
        ]
    },
    plugins: [
      new webpack.optimize.UglifyJsPlugin({minimize: true})
    ]
};
```

So my 800kb turned into 180kb

**Comment by gaearon** [comment]
For React, it's a good idea to use React NPM module and have 

```js
        new webpack.DefinePlugin({
          'process.env': {
            'NODE_ENV': JSON.stringify(argv.debug ? 'development' : 'production')
          }
        })
```

in `plugins` in production config.

**Comment by binarykitchen** [comment]
@gaearon a quick question: is the JSON.stringify really needed for `'NODE_ENV': JSON.stringify('production')` ??

**Comment by gaearon** [comment]
@binarykitchen 

You want the quotes to be there.
i.e. it should be 

```
'NODE_ENV': '"production"'
```

and not

```
'NODE_ENV': 'production'
```

or it'll refer to undefined `production` variable.

`JSON.stringify` it just to make it clear.

**Comment by binarykitchen** [comment]
thanks

**Comment by leinov** [comment]
@gaearon nice

**Comment by nanvel** [comment]
Use `-p` key (shortcut for `--optimize-minimize`):
```bash
webpack -p --progress
```
