### ISSUE TITLE
Require a img file using a variable into path

### ISSUE THREAD

**Issue by paologf** [webpack/webpack#6580]
**Do you want to request a *feature* or report a *bug*?**
Report bug

**What is the current behavior?**
I'm not able to require a path using that contains a variable.

**If the current behavior is a bug, please provide the steps to reproduce.**
Here a code example. 
If I do this works fine:
`var img = require('/Users/username/folder/imgs/img_name.png');`
, but if I use this: 
`var tmpPath = '/Users/username/folder/';` 
`var img = require(tmpPath+'/imgs/img_name.png');`
I got 
>Uncaught Error: Cannot find module "."

**What is the expected behavior?**
I expect that using a variable path (that comes from app.getPath() or similar) instead of hardcoded path works in the same way.

**If this is a feature request, what is motivation or use case for changing the behavior?**
NA

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
I'm using: 
 - OSX 10.13.3
 - webpack 3.11.0 
 - electron 1.7.9

And this is my webpack.dev.config.js:
```
{
const webpack = require('webpack');
const path = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const { spawn } = require('child_process');
const redis = require('redis')

// Config directories
const SRC_DIR = path.resolve(__dirname, 'src');
const OUTPUT_DIR = path.resolve(__dirname, 'dist');

// Any directories you will be adding code/files into, need to be added to this array so webpack will pick them up
const defaultInclude = [SRC_DIR];

module.exports = {
  entry: SRC_DIR + '/index.js',
  output: {
    path: OUTPUT_DIR,
    publicPath: '/',
    filename: 'bundle.js'
  },
  resolve: {
    alias: {
      'hiredis': path.join(__dirname, 'aliases/hiredis.js')
    }
  },
  module: {
    rules: [
      {
        test: /\.css$/,
        include: /node_modules/,
        loaders: ['style-loader', 'css-loader']
      },
      {
        test: /\.css$/,
        use: [{ loader: 'style-loader' },
              { loader: 'css-loader' }],
        include: defaultInclude
      },
      {
        test: /\.jsx?$/,
        use: [{ loader: 'babel-loader' }],
        include: defaultInclude
      },
      {
        test: /\.(jpe?g|png|gif)$/,
        use: [{ loader: 'file-loader?name=img/[name]__[hash:base64:5].[ext]' }],
        include: defaultInclude
      },
      {
        test: /\.(eot|svg|ttf|woff|woff2)$/,
        use: [{ loader: 'file-loader?name=font/[name]__[hash:base64:5].[ext]' }],
        include: defaultInclude
      }
"webpack.dev.config.js" 81L, 2061C
```

Thanks

Paolo

**Comment by sokra** [comment]
webpack does only support simple dynamic dependencies. It's a static bundler and all files need to be able to be determined while compiling. Using absolute paths is also strongly dis-encouraged. Just use static relative paths: `require("./imgs/img_name.png")`
