### ISSUE TITLE
Provide a way to pass options to webpack-composed plugins

### ISSUE THREAD

**Issue by probablyup** [webpack/webpack#6581]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
if `mode` is set to `"production"`, there's no (documented) way to instruct webpack to pass along options to a plugin composed by webpack itself, like `uglifyjs-webpack-plugin`

**If the current behavior is a bug, please provide the steps to reproduce.**
n/a

**What is the expected behavior?**
n/a

**If this is a feature request, what is motivation or use case for changing the behavior?**
Through some config object, I want to be able to pass overrides to the uglifyjs plugin and perhaps other plugins that webpack composes without user input. e.g.

```js
{
    optimize: {
        minify: {
            myOption: myValue,
        }
    }
}
```

My exact use case is to pass a different regex to the extractComments feature in uglify.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
webpack 4

**Comment by sokra** [comment]
You can use the `optimization.minimizer` option to configure uglifyjs:

``` js
optimization: {
  minimizer: [
    new UglifyJsPlugin( ... )
  ]
}
```

**Comment by probablyup** [comment]
Gotcha. I don't believe that's documented.

This works, but it would be nice to not have to recompose the plugin and replicate all the "mode" behaviors, if that makes sense.

**Comment by NemoStein** [comment]
There are other reports related to this.

The proposed solution everywhere (`optimization.minimizer = new UglifyJsPlugin( ... )`) doesn't solve the problem entirely...
I don't want to fiddle with webpack defaults, I just want to override a config (e.g.: `output.comments`) keeping the rest as is.

**Comment by miracle2k** [comment]
A lot of people seem to basically want to remove the comments; what is the reason this is not the default?

**Comment by evilebottnawi** [comment]
We can't use `optimization.minimizer = new UglifyJsPlugin(options)` due minimizer can be not only for `js`, here developers can add `css` optimizes, `image` optimizer and etc
