### ISSUE TITLE
IE11 incompatible JavaScript syntax (ES2015 Shorthand property names)

### ISSUE THREAD

**Issue by webmaster128** [webpack/webpack#6582]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

In some cases, webpack produces output that uses the ES2015 Shorthand property names, which are not supported by IE11.

**If the current behavior is a bug, please provide the steps to reproduce.**

```
$ mkdir object-test && cd object-test
$ yarn init -y
$ yarn add webpack webpack-cli --dev && yarn add pica

$ mkdir src 
$ echo "const pica = require('pica')();" > src/index.js
$ (
    echo 'module.exports = {                         '
    echo '  entry: { "bundle": "./src/index.js", },  '
    echo '  resolve: { extensions: [".js"] },        '
    echo '  devtool: "source-map",                   '
    echo '}                                          '
) > webpack.config.js
$ node node_modules/webpack-cli/bin/webpack.js --optimize-minimize false --mode development
$ grep -A 5 "DEFAULT_PICA_OPTS = " node_modules/pica/dist/pica.js dist/bundle.js
```

this leads to

```
node_modules/pica/dist/pica.js:var DEFAULT_PICA_OPTS = {
node_modules/pica/dist/pica.js-  tile: 1024,
node_modules/pica/dist/pica.js-  concurrency: concurrency,
node_modules/pica/dist/pica.js-  features: ['js', 'wasm', 'ww'],
node_modules/pica/dist/pica.js-  idle: 2000
node_modules/pica/dist/pica.js-};
--
dist/bundle.js:const DEFAULT_PICA_OPTS = {
dist/bundle.js-  tile: 1024,
dist/bundle.js-  concurrency,
dist/bundle.js-  features: [ 'js', 'wasm', 'ww' ],
dist/bundle.js-  idle: 2000
dist/bundle.js-};
```

where `concurrency: concurrency` is reduced to `concurrency`.

The same effect does not happen when adding

`echo "var foo = 1; var bar = { foo: foo };" >> src/index.js`

In this case, the code is preserved untouched in dist/bundle.js.

**What is the expected behavior?**

The inlined version of pica.js in bundle.js should be IE11 compatible.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

webpack 3.11.0
webpack 4.0.0
node v9.4.0
yarn 1.3.2

**Comment by sokra** [comment]
webpack doesn't change these code. It's written this way in the pica package:

https://github.com/nodeca/pica/blob/44a37e9ec7602ee46e7d7388b374febd872e5281/index.js#L36

You can file an issue there or use transpilation to rewrite it

**Comment by webmaster128** [comment]
Thanks a lot for the hint and sorry for disturbing you.

My problem was that I compared `node_modules/pica/dist/pica.js` vs. `dist/bundle.js` and not `node_modules/pica/index.js` vs. `dist/bundle.js`.
