### ISSUE TITLE
No indication of which modules failed to hot reload in Firefox

### ISSUE THREAD

**Issue by pmlamotte** [webpack/webpack#6589]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When an attempt to update hot modules is unsuccessful due to unaccepted modules, in browsers other than Firefox a console.warn message will appear including the full stack trace of `hotApply` and a message detailing the import tree that was not accepted. This message is useful for determining why a full refresh is needed.

This is how the message appears in chrome:

![chrome](https://user-images.githubusercontent.com/1351490/36706106-e97b5fa4-1b2d-11e8-85e6-bf9452e88013.png)

In Firefox, a stack trace appears with no indication of _why_ a full refresh was needed:

![firefox](https://user-images.githubusercontent.com/1351490/36706093-dfb26f62-1b2d-11e8-9273-78523297fff0.png)

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Have a root file that imports two files but only accepts hot updates from one of them
2. Make a change to the file not accepted

I have a simple repo which has this set up: https://github.com/pmlamotte/webpack-firefox-hmr-error

**What is the expected behavior?**
The same message that appears in other browsers detailing why a full refresh was needed should show up in the Firefox console.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
Firefox 58 & Nightly
Webpack 3.10.0
Arch Linux

**Comment by pmlamotte** [comment]
My reproduction repo only uses 3.10 since I don't know how to get this to work with 4.x since html-webpack-plugin seems to be broken. That said, I believe it affects 4.0 as well.

The problem line appears to be: https://github.com/webpack/webpack/blob/5044762c846a3a83a208853e48785a293fe9ef7d/hot/dev-server.js#L43
```
	log("warning", "[HMR] " + err.stack || err.message);
```

In Firefox, err.stack only gives the stack trace, while chrome includes the message. If I remove `err.stack || ` then it works as expected in firefox (though without the stack trace, not that it seems useful).

**Comment by TheLarkInn** [comment]
To use html-webpack-plugin you can use this (for now) doing the following: 

`yarn add html-webpack-plugin@webpack-contrib/html-webpack-plugin#master`

**Comment by sokra** [comment]
Seems like the formatting is vendor-specific and doesn't include the message in firefox and safari.
We should add the message in these cases. Please send a PR fixing it.
