### ISSUE TITLE
dynamic import code compressed though it's in dead code

### ISSUE THREAD

**Issue by ruoqianfengshao** [webpack/webpack#6590]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
dynamic import code compressed though it's in dead code, I use webpack.optimize.UglifyJsPlugin to try to remove this code but chunkfile still presented in dist directory

**If the current behavior is a bug, please provide the steps to reproduce.**

here is example:
![image](https://user-images.githubusercontent.com/2928664/36712622-a09cb976-1bc4-11e8-8ed1-af678b89b737.png)

**What is the expected behavior?**
When process.env.CURRENT_DOMAIN is 'purchaser', there is only one chunk file about purchaser.

** What is the actual result?**
But now all import chunk produced in dist.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

webpack@3.6.0
macOS Hight Sierra@10.13.3

**Comment by webyonet** [comment]
+1

**Comment by TheLarkInn** [comment]
Would you please test this in webpack 4? If this still persists then we can confirm work needs to be done to fix this.

**Comment by sokra** [comment]
Did you use the `DefinePlugin` to make `process.env.CURRENT_DOMAIN` compile-time static?

**Comment by ruoqianfengshao** [comment]
@sokra yeah, I used `DefinePlugin` to set `process.env.CURRENT_DOMAIN` as well as `process.env.NODE_ENV`, but it didn't work.

@TheLarkInn Ok, I will try it in webpack@4, and give report here, thanks yours amazing work!

**Comment by sokra** [comment]
It would be great if you reduce your issue to a small reproducible example using webpack 4. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by ruoqianfengshao** [comment]
Sorry for long time to reply
In my case, dead code disappear under using webpack@4 😄
