### ISSUE TITLE
HMR only works at the first time.

### ISSUE THREAD

**Issue by Rokt33r** [webpack/webpack#6592]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

HMR only works at the first time. Later on, it keep refreshing page.

![webpack-hmr](https://user-images.githubusercontent.com/5865853/36713942-49af5f2e-1bd3-11e8-8419-7026b327a454.gif)

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/Rokt33r/ts-webpack-hmr

**What is the expected behavior?**

It should not refresh the page.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

Node.js version: v8.9.4
Webpack: v4.0.1

**Comment by TheLarkInn** [comment]
Does this work correctly without TypeScript? Just wanting to rule out any of the behaviors as possible.

**Comment by Rokt33r** [comment]
@TheLarkInn It works perfectly without TypeScript... 😭

**Comment by Rokt33r** [comment]
It has been fixed after I put `transpileOnly` option. I assume this is a problem of ts-loader

```
      {
        test: /\.tsx?$/,
        loader: 'ts-loader',
        options:{
          transpileOnly: true
        },
        exclude: /node_modules/
      }
```
