### ISSUE TITLE
使用v4.0.1版本运行中文文档示例里的html-webpack-plugin报错

### ISSUE THREAD

**Issue by Tiepiren** [webpack/webpack#6593]
使用最新的v4.0.1版本webpack运行中文文档里html-webpack-plugin章节的示例会报错
文档地址：[https://doc.webpack-china.org/guides/output-management/#-htmlwebpackplugin](url)
![image](https://user-images.githubusercontent.com/26787977/36719104-0c63132a-1bdf-11e8-85df-1ee1609fa6a6.png)

**Comment by jarvis1024** [comment]
`npm i -D webpack-contrib/html-webpack-plugin`

**Comment by haishengXie0712** [comment]
@jarvis1024 我尝试了，还是不行

**Comment by evilebottnawi** [comment]
@Tiepiren Please read comment above and use issue template in future. Thanks!
