### ISSUE TITLE
hi,I have the same issue.How to solve it?

### ISSUE THREAD

**Issue by feiyang0117** [webpack/webpack#6594]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

**Comment by evilebottnawi** [comment]
@feiyang0117 please recreate issue if problem still exists. Thanks!

**Comment by feiyang0117** [comment]
ok
