### ISSUE TITLE
(node:44011) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead (node:44011) DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead

### ISSUE THREAD

**Issue by feiyang0117** [webpack/webpack#6595]
Hi,Ihave one issue，when I install html-webpack-plugin and npm run build.It's error.Can youhelp me?

DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
DeprecationWarning: Tapable.apply is deprecated. Call apply on the plugin directly instead.

webpack:4.0.0 /4.0.1 
node:v8.9.4

**Comment by montogeek** [comment]
Please use issue template.

**Comment by plexigras** [comment]
`npm i webpack-contrib/html-webpack-plugin` works

**Comment by mqliutie** [comment]
@feiyang0117  这些 **warning** 不用理他好了
`webpack` 插件会调用 `Tapable.plugin(''xxx, (compilation)=>{})`不知道是哪个版本开始 `plugin` 方法不在建议使用, 应该用 `hooks`
所以要想解决这些 `warning` 应该由插件们的作者来解决
