### ISSUE TITLE
when I install html-webpack-plugin and npm run build,it's error.

### ISSUE THREAD

**Issue by feiyang0117** [webpack/webpack#6596]
**Do you want to request a *feature* or report a *bug*?**
bug
When I install html-webpack-plugin plugin and npm run build,the issue is happen.I try to install 4.0.1 and 4.0.0 but it still error.

![image](https://user-images.githubusercontent.com/10703466/36722784-741f0668-1be9-11e8-8c9e-25b31eb790bc.png)
node:8.9.4
webpack:4.0.1/4.0.0

**Comment by trippingtarballs** [comment]
https://medium.com/webpack/webpack-4-released-today-6cdb994702d4

See the section titled, **If you use HtmlWebpackPlugin**

<img width="759" alt="screen shot 2018-02-27 at 10 31 32" src="https://user-images.githubusercontent.com/2758507/36723906-697549ce-1ba9-11e8-855d-c4d858e2b697.png">

**Comment by feiyang0117** [comment]
I have just search npm and resolve it just you said.Tks
