### ISSUE TITLE
Requiring absolute paths on windows fails

### ISSUE THREAD

**Issue by jhnns** [webpack/webpack#66]
webpack 0.8.x can't find the module on windows if I required it like this:

``` javascript
require("c:/Users/jhnns/dev/test/b.js");
```

node does :smile: 

I haven't tested it with webpack 0.9.x.

**Comment by pavel06081991** [comment]
Hi, I met with the same problem. I have windows 8. When I set absolute path with forward slashes
in include/exclude properties of loaders, webpack can not understand them, but if I set path with backslashes - it works.
