### ISSUE TITLE
Source maps not created when mode is production

### ISSUE THREAD

**Issue by johnywith1n** [webpack/webpack#6614]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Using `SourceMapDevToolPlugin` to create source maps doesn't work when mode is set to `production`. If I set mode to `none`, then the source maps are created.

**If the current behavior is a bug, please provide the steps to reproduce.**
Set mode to `production` and attempt to use `SourceMapDevToolPlugin` to generate source maps.

webpack config: https://gist.github.com/johnywith1n/8ddf42309f3bf4fa4a4b3537c3d956ba

**What is the expected behavior?**
Source maps should be generated when mode is production.
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
node 8.9.3, webpack 4.01, macOS 10.12.6

**Comment by Hoten** [comment]
I can confirm the same issue on my end. Setting the mode to production seems incompatible with using SourceMapDevToolPlugin.

**Comment by Hoten** [comment]
I added logging to the plugin's `constructor` and `apply` methods. It seems that the plugin is added twice. Once from me explicitly including it in the plugins, and once (I assume) from mode being set to `production` (not sure where to look to confirm that).

**Comment by sokra** [comment]
Could you try with `optimization.minimize: false`?

**Comment by Hoten** [comment]
Figured it out. You must offer a custom configuration for UglifyJS (enabling the source map).

```
optimization: {
      minimizer: [new UglifyJsPlugin({
              cache: true,
              parallel: true,
              sourceMap: true
            })]
    }
```

**Comment by Hoten** [comment]
The default sets sourceMap to false.

```
this.set("optimization.minimizer", "make", options => [{
			apply: compiler => {
				// Lazy load the uglifyjs plugin
				const UglifyJsPlugin = require("uglifyjs-webpack-plugin");
				new UglifyJsPlugin({
					cache: true,
					parallel: true,
					sourceMap: options.devtool && /source-?map/.test(options.devtool)
				}).apply(compiler);
			}
		}]);
```

Perhaps the default value of sourceMap should be:

```
(options.devtool && /source-?map/.test(options.devtool)) || < SourceMapDevToolPlugin exists>
```

Not sure if that is possible within the context of `WebpackOptionsDefaulter`.

**Comment by miraage** [comment]
Please, spend some time reading changelogs before opening an issue.
It is indented behavior.

https://medium.com/webpack/webpack-4-released-today-6cdb994702d4
https://medium.com/webpack/webpack-4-mode-and-optimization-5423a6bc597a

**Comment by sokra** [comment]
> < SourceMapDevToolPlugin exists>

You can try to send a PR to add this kind of check.

**Comment by Tomekmularczyk** [comment]
I think I have the same problem. When I set `devtool: source-map` in production mode, then I have source-maps in the chunks (they are a lot bigger and I can find original modules in chrome dev tools). I'm looking for an easy way to have source-maps as external files.

**Comment by Hoten** [comment]
I'll send in a PR.

**Comment by kanghongyan** [comment]
cc
