### ISSUE TITLE
UMD built from webpack 4 can not be imported by webpack 2

### ISSUE THREAD

**Issue by njleonzhang** [webpack/webpack#6617]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
UMD built from webpack 4 can not be imported by webpack 2

**If the current behavior is a bug, please provide the steps to reproduce.**
look at this [project](https://github.com/njleonzhang/web-cached-persistence), I currently build the project as `cmd`. It now can be loaded correctly in webpack 3 project. But if I change the `libraryTarget ` to `umd`, the generated lib can not be load by webpack 3. (generated `umd` can be loaded by webpack 4)
 
```
  output: {
    filename: "./index.js",
    libraryTarget: "commonjs"
    // libraryTarget: "umd"
  },
```

When I use the generated `umd` in webpack 3, it runs in to the following error:
```
"export 'CachedStorage' was not found in 'web-cached-persistence'
```
 
**What is the expected behavior?**
no error should be emitted.

**Comment by lilijialiang** [comment]
I also encountered a similar problem.

```js
// test.js
export default { a ( ) { console.log( 'a' ) }  }
```

```js
// webpack.config.js
output: {
    library: 'TEST',
    libraryTarget: 'umd',
    filename: '[name].min.js',
    path: path.resolve( __dirname, '../dist' ),
},
```

```js
window.TEST.a  // undefined
```

webpack@4.1.1
