### ISSUE TITLE
Chunks encoded as ASCII in Webpack 4.x

### ISSUE THREAD

**Issue by phaistonian** [webpack/webpack#6618]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Chunks that contain unicode characters are encoding in ASCII not in UTF-8.

**If the current behavior is a bug, please provide the steps to reproduce.**

- `import('./my-file-containing-greek-chars.js');`

**What is the expected behavior?**

The chunk to be encoded in UTF-8, as it was the case with webpack 3.x.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

Node: 9.x. All browsers, Webpack: 4.01, OSX.

**Comment by sokra** [comment]
webpack encodes all file as utf-8. You need to use server configuration or meta tags to tell the browser that it's utf-8.

**Comment by phaistonian** [comment]
I know - thing is somehow this all started in webpack 4.x

Will investigate further.

Thank you.

**Comment by evilebottnawi** [comment]
@phaistonian Can you set `minimize: false` and check?

**Comment by phaistonian** [comment]
@evilebottnawi  Will do - but until then, if it holds any value, "this" is working properly when not in production mode.

In other words, when in production mode, those chunks are served in UTF-8.

**Comment by phaistonian** [comment]
Closing it since this seems to be related to something else.

**Comment by et** [comment]
@phaistonian - do you know what it was related to? I'm having encoding problems after upgrading to webpack 4.

**Comment by phaistonian** [comment]
Well, not really.

However, I noticed that this was also the case -though in lesser degree- with webpack 3; some chunks are saved as ASCII, not as UTF-8.

Since -for some weird reason- webpack 4  takes 3x time to bundle in our production system, we are still on 3x.

Once I figure out what's causing this huge lag and be able to move to webpack 4, I shall try to investigate why this encoding issue takes place --- and get back here with some extra info, if any.

**Comment by et** [comment]
> Since -for some weird reason- webpack 4 takes 3x time to bundle in our production system, we are still on 3x.

Glad to know I'm not the only one experiencing this.

While everything in webpack4 has been great, the prod builds are painfully slow and have been spiking my CPU.

Anyways, thanks for you insight on the encoding.

**Comment by phaistonian** [comment]
@et We resolved this by using [mini-extraxct-plugin](https://github.com/webpack-contrib/mini-css-extract-plugin) --- and not [extract-text-webpack-plugin](https://github.com/webpack-contrib/extract-text-webpack-plugin).

Perhaps this will do the trick for you as well.
