### ISSUE TITLE
From 3.11.0 the main bundle chunkhash is different when built across different machines

### ISSUE THREAD

**Issue by marnusw** [webpack/webpack#6623]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Using `v3.11.0` the `chunkhash` of the main bundle is different when the same code is bundled on different servers. Using `v3.10.0` this was/is not the case.

The changelog for `v3.11.0` includes: "Initial chunk are no longer part of the chunk manifest and no longer contribute to the hash"

Could this change be the cause of this issue?

**If the current behavior is a bug, please provide the steps to reproduce.**

Create a production build of the same code on two different machines and compare the hashes of the main chunk: `filename: [name].[chunkhash].js`

The additional async chunks (`chunkFilename: [name].[chunkhash].chunk.js`) seem to be unaffected by this issue.

If more info is needed I will provide the config, but I don't think we're doing anything out of the ordinary; and when we simply switched Webpack back to 3.10 from 3.11 all was well.

**What is the expected behavior?**

The main chunk hash should be the same on different machines.

**If this is a feature request, what is motivation or use case for changing the behavior?**

Not a feature request. It is important when the build is done on each of a number of load-balanced web servers.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

Node version: `8.9.4`

OS version: `Ubuntu 16.04.3 LTS`

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by marnusw** [comment]
Thanks for the quick response. I thought there might be something that stands out from the recent changes made to the hash calculations, but in this case I'll certainly put a repo together.

**Comment by marnusw** [comment]
I haven't been able to reproduce this with a minimal setup yet. It happens on a fairly large project. I did, however, find that removing the `webpack.HashedModuleIdsPlugin()` from the config fixes the issue on the large project (and I'm fine with doing that). 

Adding this plugin to the minimal repo doesn't seem to be sufficient to cause the problem though which is odd. I'll spend some more time on it when I can.

**Comment by evilebottnawi** [comment]
@marnusw can you provide systems/node/webpack version where problem happens?

**Comment by marnusw** [comment]
@evilebottnawi I must admit have completely forgotten about this issue. I eventually upgraded from v3.10 to v4 and haven't noticed this issue since. If this has not been reported by anyone else I'd be happy to just close this issue. Thanks for the reply though!
