### ISSUE TITLE
Acorn parser options (ecmaVersion)

### ISSUE THREAD

**Issue by urugator** [webpack/webpack#6624]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

It's impossible to provide options for Acorn parser.

**What is the expected behavior?**

Being able to provide options for Acorn parser.

**If this is a feature request, what is motivation or use case for changing the behavior?**

I want to provide `ecmaVersion: 9` option to support [object spread props](https://github.com/adrianheine/acorn5-object-spread), which is now supported out of the box on node and latest browsers...

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

node 9.5.0
webpack 3.11.0

**Comment by sokra** [comment]
Upgrate to webpack 4, which supports ES2018.

**Comment by urugator** [comment]
Thanks, spread props no longer throw after upgrading to v4. Closing the issue, because it solved my problem.
However the ability to provide these options could be useful in other cases, so it should be taken into consideration...

**Comment by urugator** [comment]
Hm, compilation is around 100ms slower, which I can live with, but sources are wrapped in inline `eval` ...  I quess this is configurable with `devtool`? I want sources exactly the same as the original, just glued together ... don't you have a quick tip for the config?
