### ISSUE TITLE
Webpack 4 chunking different runtime behaviour compared to Webpack 3

### ISSUE THREAD

**Issue by garygreen** [webpack/webpack#6626]
**Do you want to request a *feature* or report a *bug*?**

Bug / Change in behaviour compared to Webpack 3

**What is the current behavior?**

When telling Webpack which chunk the runtime should be in, it doesn't appear to change the order of excecution - see below example.

**If the current behavior is a bug, please provide the steps to reproduce.**

### vendor.js
```js
import $ from 'jquery';
console.log('vendor run.');
$.fn.sayHi = function() {
    alert('Hi');
};
```

### main.js
```js
import $ from 'jquery';
console.log('main run.');
$.fn.sayHi();
```

### index.htm
```htm
<html>
<body>
<script src="dist/vendor.js"></script>
<script src="dist/main.js"></script>
</body>
</html>
```

### Webpack 3 config
```js
var webpack = require('webpack');
var path = require('path');

module.exports = {

    mode: 'production',

    entry: {
        main: './main.js',
        vendor: './vendor.js'
    },

    output: {
        path: path.resolve(__dirname, './dist'),
        filename: '[name].js',
    },

    optimization: {
        minimize: false,
        runtimeChunk: {
            name: 'vendor'
        },
        splitChunks: {
            cacheGroups: {
                default: false,
                commons: {
                    test: /node_modules/,
                    name: "vendor",
                    chunks: "initial",
                    minSize: 1
                }
            }
        }
    }

};
```

### Webpack 4 Result

![image](https://user-images.githubusercontent.com/1702638/36878612-b34a8f90-1db7-11e8-8267-4de7ac8b68bd.png)

![image](https://user-images.githubusercontent.com/1702638/36878462-054e3de2-1db7-11e8-904b-257e69c57938.png)

As you can see, `main run` fires before vendor, even though the runtime has been put inside vendor and it's loaded first.

## Webpack 3 Result

![image](https://user-images.githubusercontent.com/1702638/36878543-6657b262-1db7-11e8-951c-55b2b735172a.png)

As you can see `vendor run` fires first, which means plugin is successfully registered and the alert dialog pops up.

~~

Original issue below - fixed by providing custom `splitChunks`. Above is now the current issue.

~~
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Webpack 4 will add jQuery to both `vendor.js` and `main.js` when you use `ProvidePlugin` - this has a side effect that if you have a vendor plugin that is registering itself as a jQuery plugin in `vendor.js` thru `$.fn` it is only available for use in `vendor.js` and won't work in `main.js`

**If the current behavior is a bug, please provide the steps to reproduce.**

### vendor.js
```js
$.fn.sayHi = function() {
    alert('Hi');
};
```

### main.js
```js
import $ from 'jquery';

$.fn.sayHi();
```

### Webpack 3 config
```js
var webpack = require('webpack');
var path = require('path');

module.exports = {

    entry: {
        main: './main.js',
        vendor: './vendor.js'
    },

    output: {
        path: path.resolve(__dirname, './dist'),
        filename: '[name].js',
    },

    plugins: [
        new webpack.ProvidePlugin({
           $: 'jquery',
           jQuery: 'jquery',
           'window.jQuery': 'jquery',
       }),
        new webpack.optimize.CommonsChunkPlugin({
            name: 'vendor'
        })
    ]

};
```

The webpack 4 config is exactly the same, except minus the `CommonChunkPlugin`

This is the output:

## Webpack 3 with ProvidePlugin

![w3 with provideplugin](https://user-images.githubusercontent.com/1702638/36815281-2072d884-1cd2-11e8-94cc-31f437f98cbb.png)

## Webpack 4 with ProvidePlugin

![w4 with provideplugin](https://user-images.githubusercontent.com/1702638/36815290-2918c868-1cd2-11e8-92f3-ddc41ea6a99b.png)

As you can see, Webpack 4 has added `jQuery` to both entries, though Webpack 3 hasn't.

**What is the expected behavior?**

To only include one version of jQuery.

**If this is a feature request, what is motivation or use case for changing the behavior?**

This is likely down to the new "rules" surrounding when to chunk and it also not playing nicely with the ProvidePlugin. This is something that will likely catch a lot of people out, if they use the default chunking algorithm in Webpack 4 along with ProvidePlugin. Maybe there is a way to default to the old behaviour as Webpack 3, but it's not immediately obvious to me how to do this.

### Example Repository

https://github.com/garygreen/webpack4-chunks-prob
~~

**Comment by pavelloz** [comment]
You removed commonsChunkPlugin, but didnt use optimization.splitChunks as a replacement, thats probably the reason why it doesnt work as expected.

**Comment by garygreen** [comment]
> You removed commonsChunkPlugin, but didnt use optimization.splitChunks as a replacement, thats probably the reason why it doesnt work as expected.

Well I've tried various different config options with `splitChunks` and although it does stop duplicate jQuery and move it to the `vendor` chunk, the code still doesn't work as expected compared to Webpack 3.

Maybe some futher tweaks to the config would make it work, but in any case I think a lot of people will stumble into this same problem.

```
splitChunks: {
	cacheGroups: {
		commons: {
			test: /[\\/]node_modules[\\/]
			name: "vendors",
			chunks: "all"
		}
	}
}
```

![image](https://user-images.githubusercontent.com/1702638/36819876-2308f478-1ce3-11e8-9234-86a921ca98f7.png)

**Comment by pavelloz** [comment]
Well, thats not an code splitting problem anymore. When code is splitted correctly i would shift my focus on this last error - maybe you should use `window.jQuery.fn`. 

Personally i migrated my project yesterday and ProvidePlugin didn't make any issues, with config:

```
new webpack.ProvidePlugin({
    $: 'jquery',
    jQuery: 'jquery'
  }),
```

I would try wrapping the plugin code into class, exporting it as ES module and try to instantiate it when appropriate. Hope something from above makes positive effect.

**Comment by garygreen** [comment]
Nope. For the life of me I cannot get it working as it did in Webpack 3 - the new `splitChunks` config settings are cryptic, despite reading https://gist.github.com/sokra/1522d586b8e5c0f5072d7565c2bee693 a million times.

So this is what I've got now:

```js
var webpack = require('webpack');
var path = require('path');

module.exports = {

    mode: 'production',

    entry: {
        main: './main.js',
        vendor: './vendor.js'
    },

    output: {
        path: path.resolve(__dirname, './dist'),
        filename: '[name].js',
    },

    optimization: {
        minimize: false,
        splitChunks: {
            cacheGroups: {
                default: false,
                commons: {
                    test: /jquery/,
                    name: "vendor",
                    chunks: "initial",
                    minSize: 1,
                    reuseExistingChunk: true
                }
            }
        }
    },

    plugins: [
        new webpack.ProvidePlugin({
            '$' : './jquery.js',
           jQuery: './jquery'
       })
    ]

};
```

This gives me a runtime in `main.js` and not in `vendor.js` - however in Webpack 3 it was the other way round, runtime was in `vendor.js` and not in `main.js`.

After some debugging it looks like `main.js` is executing BEFORE vendor.js which is why the plugins aren't available, as they haven't been attached yet because vendor hasn't run.

I've tried fiddling around with the new `optimization.runtimeChunk` config option to see if I can get the vendor.js with the runtime instead, but that option doesn't seem to have any effect whatsoever.

I know Webpack 4 is in it's early days - but looking at the comments on that Gist I'm not the only one having trouble migrating.

@pavelloz you mention you had no troubles with migrating - do you use jQuery and any plugins (and chunk to vendor.js) by any chance? Have you tried just creating a very basic setup where you have a) jQuery, b) some jQuery plugin, c) Use the jQuery plugin in `main.js` and have jQuery and the plugin go to `vendor.js` ? That's essentially the problem I'm experiencing at the moment.

**Comment by garygreen** [comment]
Ok I've managed to get the runtime to go to a seperate file by doing:

```js
    optimization: {
        runtimeChunk: true
....
```

This creates a `runtime~main.js` file however that still runs BEFORE `vendor.js` and so the plugins aren't attached yet.

### Webpack 3

![webpack3](https://user-images.githubusercontent.com/1702638/36847497-72436aa0-1d56-11e8-83fe-f7af5fdb3abc.png)

### Webpack 4

![webpack4](https://user-images.githubusercontent.com/1702638/36847504-7831c664-1d56-11e8-921c-0bace6bbcbe9.png)

**Comment by pavelloz** [comment]
I know its cryptic ;)

Anyway, i think your webpack config looks suspicious, the things i mentioned and now...
```
new webpack.ProvidePlugin({
            '$' : './jquery.js',
           jQuery: './jquery.js'
       })
```

I have never seen anyone using this plugin this way.

**Comment by garygreen** [comment]
> Anyway, i think your webpack config looks suspicious, the things i mentioned and now... I have never seen anyone using ProvidePlugin that way ('./jquery.js')

That's a perfectly valid way to use the plugin. Also I only did it that way to try to understand / debug what's happening with Webpack behind the scenes rather than pulling down the whole of jQuery and looking at the build outputs. If you shim jQuery library itself, you get the same result.

**Comment by Sebazzz** [comment]
I am having the same issue. The gist of the issue is that you'd expect the common chunk to contain the runtime, as it contains the dependencies of the other chunks, but instead the dependent code contains the runtime chunk. 

Since it is a complex subject, and is black magic for the uninitiated, the best solution would IMHO be an option to be able to specify in which output(s) the runtime should be placed. Or consider it a bug as it does follow behavior essentially preventing this (imho) common code splitting scenario. 

Fairly [large example for a SPA](https://github.com/Sebazzz/financial-app/blob/webpack4/src/App/webpack.config.common.js) / Smaller [example of multiple-pages/entry points](https://github.com/Sebazzz/IFS/blob/webpack4/src/IFS.Web/webpack.config.common.js).

**Comment by garygreen** [comment]
So it seems you can change where the runtime goes by naming the entry:

```js
    optimization: {
        runtimeChunk: {
            name: 'vendor'
        },
```

However in my case this doesn't change what order the files are executed in, it seems `main.js` is still firing before `vendor.js`, even though runtime is in `vendor`.

**Comment by garygreen** [comment]
I'm opening a new issue as this one went off track a bit at the start - #6647

**Comment by Legends** [comment]
Continuing off track..

**Multi-Page-Application**

I have a question regarding "controlling the bundle output using webpack.config.js"

With webpack v3 we used `CommonsChunkPlugin`, worked good for me.
With webpack 4 we have to configure this with `optimization.splitchunks` right?!


**What I want:**

I have a vendor.build.js which imports all vendor libs, output should be: vendor.bundle.js.
Inside of vendor.build.js I also import all css/scss/less files which want to be outputed as: bundle.css.

In the webpack.config I use one instance of the `ExtractTextPlugin` for extracting all` css/scss/less` into one file.

I also load modules dynamically in `vendor.js` and `postome.js`.

```
 entry: {
        "vendor": [join(scriptsfolder, "vendor.build")],  // jquery/boostrap/lodash...
        "view.default.index": join(scriptsfolder, "controllers/default/index"),  // page script
        "view.default.posttome": join(scriptsfolder, "posttome")     // page script
    },
```

**How do I have to configure the optimization config part to get the following results in dist folder:**

- vendor.bundle.js
- bundle.css
- postome.js
- view.default.index.js
- AsynchronouslyLoadedModule1.js
- AsynchronouslyLoadedModule2.js

**Comment by Legends** [comment]
Can someone setup a gist with examples for common configurations using SPA and MPA?

**Comment by Legends** [comment]
Is there a plugin which outputs all source-map files into a predefined output directory and updates the source-map urls adequately?

**Comment by wyhaya** [comment]
@Legends  

Hello, I encountered a similar problem, I do not know if you solved it ?

---

In webpack `^3` :
```javascript
// ...
plugins: [
    new webpack.optimize.CommonsChunkPlugin({
        name: ['react']
    }),
    new ExtractTextPlugin('[name].css'),
    ...htmls
]
```
Output :
```
index.html
index.css
index.js

home.html
home.css
home.js

react.js
```
Looks very good, this is exactly what I want

---

In webpack `^4` :
```javascript
// ...
optimization: {
    splitChunks: {
        cacheGroups: {
            commons: {
                // test: /[\\/]node_modules[\\/]/,
                name: 'react',
                chunks: 'all'
            }
        }
    }
},
plugins: [
    new ExtractTextPlugin('[name].css'),
    ...htmls
]
```
Output :
```
index.html
index.js

home.html
home.js

react.js
react.css
```
---

Is the `webpack.optimize.CommonsChunkPlugin` method replaced with `optimization.splitChunks` in webpack4?

**Comment by Legends** [comment]
The `CommonsChunkPlugin` has been removed in v4.
You better open a new issue, this thread is dead.

[Read this](https://gist.github.com/sokra/1522d586b8e5c0f5072d7565c2bee693) and tell me this solves your problem.

**Comment by wyhaya** [comment]
@Legends 
I have read this article, but did not solve my problem, thank you for your reply.

**Comment by Legends** [comment]
I guess, the main problem is, that we still think the `CommonsChunk way` and the documentation it rather sparse regarding this new approach...

**Comment by message** [comment]
@Legends what did you use to make usage analytics data [here](https://github.com/webpack/webpack/issues/6626#issuecomment-373224575)?

**Comment by Legends** [comment]
@message  `webpack-bundle-analyzer`

**Comment by ioanungurean** [comment]
Hi, I had the same issues but I managed to fix it. [Here](https://github.com/ioanungurean/react-app) you have a Webpack 4 SPA build configuration example maybe it will help you. And this is the commit when I migrated from Webpack 3 to Webpack 4.
