### ISSUE TITLE
"x is not defined"

### ISSUE THREAD

**Issue by ffpetrovic** [webpack/webpack#6632]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

Why does no one know the answer to this question? 

https://stackoverflow.com/questions/49036774/webpack-velocity-is-not-defined

**Comment by montogeek** [comment]
This is a question that doesn't belong to an issue tracker
