### ISSUE TITLE
'compile' hook doesn't exist in MultiCompiler

### ISSUE THREAD

**Issue by qazbnm456** [webpack/webpack#6633]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
'compile' hook doesn't exist.

**What is the expected behavior?**
'compile' hook should exist.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Compatibility with webpack-dev-middleware and webpack-hot-middleware.

**Comment by sokra** [comment]
There is no compile hook on the MultiCompiler. webpack-dev-server shoudn't use the hook for invalidation. The `invalid` hook can be used for invalidation. There is no need for a `compile` hook, and it doesn't make sense.
