### ISSUE TITLE
Webpack breaking vuex

### ISSUE THREAD

**Issue by DusanMilko** [webpack/webpack#6635]
Bug report

**What is the current behavior?**

Vuex breaks and throws error:
Uncaught TypeError: Cannot assign to read only property 'watch' of object '#<Store>'

**If the current behavior is a bug, please provide the steps to reproduce.**

import vue and import vuex;

**What is the expected behavior?**

No error

**If this is a feature request, what is motivation or use case for changing the behavior?**

Mac
Webpack 4.0.1
Vue 2.5.13
Vuex 3.0.1

**Comment by montogeek** [comment]
Do you have a repository to reproduce the issue?
