### ISSUE TITLE
'compilation' hook doesn't exist in MultiCompiler

### ISSUE THREAD

**Issue by qazbnm456** [webpack/webpack#6637]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
'compilation' hook doesn't exist.

**What is the expected behavior?**
'compilation' hook should exist.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Compatibility with https://github.com/SimulatedGREG/electron-vue/blob/master/template/.electron-vue/dev-runner.js#L51.

**Comment**
@ooflorent Do you think we should implement more hooks in the MultiCompiler instance? There're still [several hooks](https://github.com/webpack/webpack/blob/5238159/lib/Compiler.js#L30-L56) there. 🤔

BTW, thanks for the PR. 😄

**Comment by sokra** [comment]
The `compilation` hook should not exist on the MultiCompiler. It never existed.

The referenced code can use the `done` hook instead.
