### ISSUE TITLE
Webpack UglifyJS Transformer + JSX Loader Broken

### ISSUE THREAD

**Issue by iammerrick** [webpack/webpack#664]
I have made an example project using the jsx-loader and webpack which demonstrates an instance where the output of the uglifyjs plugin behaves differently than non uglified code. 

https://github.com/iammerrick/webpack-jsx-uglify-bug

If you comment out the uglifyjs plugin the code works as expected. If not, you get an undefined variable. Any ideas? Is this more likely an uglify bug?

**Comment by iammerrick** [comment]
+ @petehunt

**Comment by iammerrick** [comment]
I think it has something to do with the compiled out put of an ES6 class in concert with Uglify.

**Comment by loganfsmyth** [comment]
I was bored and did some debugging. This is an issue between angular/di and uglifyjs. https://github.com/angular/di.js/pull/93

**Comment by iammerrick** [comment]
Thank you!
