### ISSUE TITLE
SplitChunksPlugin blows up without options object

### ISSUE THREAD

**Issue by zacanger** [webpack/webpack#6644]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

SplitChunksPlugin blows up without options object, but proposed docs suggest options are optional.

**If the current behavior is a bug, please provide the steps to reproduce.**

Include `webpack.optimize.SplitChunksPlugin()` in your plugins and run Webpack -- it blows up. Add an empty object `{}` and it's fine.

**What is the expected behavior?**

It probably shouldn't blow up. A change [here](https://github.com/webpack/webpack/blob/master/lib/optimize/SplitChunksPlugin.js#L86) (`static normalizeOptions (options = {}) {` is all it would take.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

Node 8.9.4, Webpack 4.0.1.

**Comment by montogeek** [comment]
Send a PR
