### ISSUE TITLE
Sourcemaps not working correctly with typescript.

### ISSUE THREAD

**Issue by Glinkis** [webpack/webpack#6654]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Sourcemaps does not show the source correctly, but show the transformed code.
I am building with `--mode development`

**If the current behavior is a bug, please provide the steps to reproduce.**
[repo to reproduce](https://github.com/Glinkis/webpack-sourcemap-test)
Build and trace the `console.error`

**What is the expected behavior?**
Sourcemaps should lead to the source files.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
Browsers: Chrome & Firefox, others unknown.
Node 8.9.4, Webpack 4.01, Mac OSX High Sierra

**Comment by sokra** [comment]
`--mode developement` doesn't enable full source maps. It only uses a very simple (but performant) version, which maps to the generated source. Enable SourceMaps with i. e. `--devtool source-map`

**Comment by Glinkis** [comment]
Enabling sourcemaps with devtool unfortunately makes no difference.

**Comment by sokra** [comment]
Are SourceMaps enabled in the browser devtools?

**Comment by Glinkis** [comment]
Yes, the sourcemaps works fine if I use webpack 3.

**Comment by sokra** [comment]
I tried your repo and it works great in firefox and chrome

![grafik](https://user-images.githubusercontent.com/1365881/36945412-1a3b4274-1fae-11e8-8270-a4aab796ff5e.png)

![grafik](https://user-images.githubusercontent.com/1365881/36945427-32487666-1fae-11e8-8f80-97a45c7b65be.png)

**Comment by Glinkis** [comment]
Hmm, that is very odd. I'll make sure to try it again once I have access to a computer and report back of I can get it working.

Did you run it with sourcemaps enabled in the npm script, or in the config file?

**Comment by Glinkis** [comment]
All right, so it seems I did not fully cover my problem in the repository. My issue has to do with emitting a library in multiple parts. 

I could not get ``devtool: "source-map"` to work, due to an error saying:
```ValidationError: SourceMap DevTool Plugin Invalid Options
options.namespace should be string```
And in my experiments I had set devtool to `source` instead of `source-map`, which let me build without problem. But if course did not produce any actual sourcemaps.

I have updated the repository to reflect this, and would be grateful for another look.

**Comment by Glinkis** [comment]
This seems to be the very same issue as #6634.

**Comment by tmilloff** [comment]
@Glinkis #6634 has been closed. If you try the commit with the merged fix (ie `"webpack": "https://github.com/webpack/webpack.git#4f399322ad19"
` in your `package.json` dependencies, is the issue resolved?

**Comment by Glinkis** [comment]
@tmilloff Yep, everything seems to work as expected now. Thank you.
