### ISSUE TITLE
Webpack 4 - SSR config

### ISSUE THREAD

**Issue by GuillaumeCisco** [webpack/webpack#6655]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
SSR client part doesn't load modules. But the server part works.

**If the current behavior is a bug, please provide the steps to reproduce.**

In the client part, a `main.js` file is correctly created with the webpack bootstrap logic, then the modules declarations. But the modules are never loaded, so the app is never loaded.
In my research, I think the code that should load the modules is:
```javascript
     var jsonpArray = window["webpackJsonp"] = window["webpackJsonp"] || [];
     var oldJsonpFunction = jsonpArray.push.bind(jsonpArray);
     jsonpArray.push = webpackJsonpCallback;
     jsonpArray = jsonpArray.slice();
     for(var i = 0; i < jsonpArray.length; i++) webpackJsonpCallback(jsonpArray[i]);
     var parentJsonpFunction = oldJsonpFunction;
```
But the `window["webpackJsonp"]` variable is undefined, so `jsonpArray` is an empty array, and nothing run inside `webpackJsonpCallback`.
Do you think I have a config problem? My client config is very simple:

```javascript
export default {
    mode: process.env.NODE_ENV,
    name: 'client',
    target: 'web',
    devtool: DEBUG ? 'source-map' : (DEVELOPMENT ? 'cheap-module-source-map' : '#hidden-source-map'),
    entry: [
        'babel-polyfill',
        'fetch-everywhere',
        path.resolve(__dirname, '../../src/client/index.js'),
    ],
    module: {
        rules: rules(),
    },
    output: {
        filename: `[name]${PRODUCTION ? '-[hash:6]' : ''}.js`,
        chunkFilename: '[name].js',
        path: path.resolve(__dirname, '../../build/ssr/client'),
        publicPath: DEBUG ? DEBUG_BASE_NAME : PRODUCTION_BASE_NAME,
    },
    plugins: plugins('client'),
    resolve: resolve(),
};

```

**What is the expected behavior?**

Modules are loaded. SSR client part rehydrate state from server and run in place.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
Webpack 4.0.1
node 9.5.0

**Comment by GuillaumeCisco** [comment]
Ok just found out why, I was using a modifed version of the package `extract-webpack-css-chunks` for supporting webpack 4.
Disabling it fixes the error.

The real deaal was with the code just after `var parentJsonpFunction = oldJsonpFunction;`:
```javascript
// add entry module to deferred list
deferredModules.push([null,'vendor',null]);
// run deferred modules when ready
return checkDeferredModules();
```

**Comment by charliesibbach** [comment]
I just ran into this exact issue, and tracked it down to the same place you did- checkDeferredModules(). I don't understand your solution though, because I am using out of the box stuff for webpack. Any chance you have more wisdom on this issue you can share? Thanks!

**Comment by GuillaumeCisco** [comment]
Hey @charliesibbach, in my case it was a modified version of `extract-css-chunks-webpack-plugin` I was using, which broke the loading.

Try commenting all your plugins, then uncomment them step by step to find the issue.
If you want, you can check my webpack4 branch (still in progress) for more details: https://github.com/GuillaumeCisco/guillaumecisco/tree/gcisco-webpack-4
I hope you will find some solutions to your problem :)

**Comment by charliesibbach** [comment]
Thanks for the reply, @GuillaumeCisco! I appreciate it. In my case it was not a plugin issue. It was an issue with the way Karma was generating the bundles for the tests. I was importing my webpack configuration into Karma, which included some configuration for splitChunks, but it was not actually including the shared chunk in the output test harness. The deferred modules were then waiting for modules from the shared chunk that never arrived. Of course, nothing in the debugger indicated this until I noticed that the nature of the tests that weren't running all had some deep set dependency on NPM modules (in the shared chunk), and then it was easy. So note for future people that may stumble on this issue- you are probably already overriding the Entry settings for webpack in karma.conf.js; you should also set webpackConfig.optimization.splitChunks = false.
