### ISSUE TITLE
Configuration: Entry doesn't support all relative paths

### ISSUE THREAD

**Issue by nmschulte** [webpack/webpack#6657]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
Webpack build fails and outputs error message:
`ERROR in Entry module not found: Error: Can't resolve 'src/main.js' in '/home/nmschulte/projects/wpcerp'`

**If the current behavior is a bug, please provide the steps to reproduce.**
`git clone https://github.com/nmschulte/wpcerp.git && cd wpcerp.git && npm install && npm start`

**What is the expected behavior?**
Webpack build succeeds (because it knows how to resolve "non-complex" (no `./` or `../`) relative paths.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
```
nmschulte@desmas-l:cts/aviture/ispan/wpcerp$ uname -a && node -v && npm -v && grep 'webpack' package.json
Linux desmas-l.desmas 4.14.0-3-amd64 #1 SMP Debian 4.14.17-1 (2018-02-14) x86_64 GNU/Linux
v9.6.0
5.6.0
    "start": "webpack"
    "webpack": "^4.0.1",
    "webpack-cli": "^2.0.10"
```

**Comment by sokra** [comment]
`entry` doesn't support relative paths. It supports requests, which is the same you write into `import`/`require`. It has to start with `./` or `../` if it's a relative paths.

**Comment by nmschulte** [comment]
@sokra thanks for the clarification.  The documentation clearly states that these values are "paths," when it sounds like in reality they're "module names" ("requests" as you say).  It'd be nice to see this reflected in the documentation.
