### ISSUE TITLE
wrong minimize

### ISSUE THREAD

**Issue by taoqf** [webpack/webpack#6659]
**Do you want to request a *feature* or report a *bug*?**
a bug

**What is the current behavior?**
```js
for (let i = 0; i < l; i++) {
	const args = match.attrs[i];
	const value = args[3] || args[4] || args[5] || '';
	attrs[i] = {
		name: args[1],
		value: decodeAttr(value)
	}
}
```

`r = r,` will throw an exception `TypeError: Assignment to constant variable.`

```js
for (let e = 0; e < o; e++) {
  const n = t.attrs[e],
  r = n[3] || n[4] || n[5] || "";
  a[e] = {
    name: n[1],
    value: (r = r, r.replace(_, "<").replace(g, ">").replace(m, "&").replace(b, '"'))
  }
}
```
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
```js
for (let e = 0; e < o; e++) {
  const n = t.attrs[e],
  r = n[3] || n[4] || n[5] || "";
  a[e] = {
    name: n[1],
    value: (r.replace(_, "<").replace(g, ">").replace(m, "&").replace(b, '"'))
  }
}
```
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
OS: Debian
Node.js 9.6.1
webpack version: 4.0.1 4.0.0-beta.3

**Comment by ooflorent** [comment]
What is `decodeAttr`? Why is it replaced? Could you create a repository to reproduce the issue?

**Comment by kzc** [comment]
Already asked/answered. Search issues before reporting a bug.

https://github.com/webpack/webpack/issues?q=is%3Aissue+TypeError%3A+Assignment+to+constant+variable+is%3Aclosed

**Comment by lusentis** [comment]
This is the related issue: https://github.com/webpack/webpack/issues/6567. Took me ages to figure out, since its title refers to a feat request.
