### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by mysuf** [webpack/webpack#6662]
Hello guys,

I am just beginner with webpack and I fall in love to that. I would like to use edge version(v4). After many days I finally composed config file. I already worked with other bundlers(grunt, gulp, browserify) and now I can say that it was quite confusing intro into webpack. Most of time spent by googling.

In compare with other bundlers, configuration is more complex and require some node experiences and javascript skills from developer. So please be patient if you are one of them. It is possible that information that beginner find is already contained in doc, but then maybe it is not clear enough.

I found most of usefull informations in closed github issues and on stackoverflow. This tells something about current state of documentation.

There are already four major versions of webpacks and all beginner issues turn around it:

1. Proper migration doc v3 -> v4 is missing. In your doc, there is one page about migration and until now I really dont know which versions it solves. Most usefull migration info I found on medium.com.
2. Doc versioning. For example ag-grid doc has 4.0.1 mark but doc corresponds with v2 or v3. Each part of config doc could contain well-listed versions with corresponding code. It applies also to plugins and loaders. Versions are now mixed and not well marked in most of docs.
3. Better explained behaviour of each part.

For example I tried to configure webpack-dev-server and information that dev-server can not write files into folders on disc came to me after one day of googling "what is wrong with my config". I expected that it serves files in memory aswell as writing into disc when production mode is set and ExtractTextPlugin is provided.

**Comment by sokra** [comment]
@webpack-bot move to webpack/webpack.js.org
