### ISSUE TITLE
Parts of async loaded chunk end up in explicit vendor chunk

### ISSUE THREAD

**Issue by Sebazzz** [webpack/webpack#6666]
**Do you want to request a *feature* or report a *bug*?**
I think this is a *bug*.

**What is the current behavior?**
I am using an explit vendor chunk, but one part of my app uses the async harmony import to import a vendor library asynchronously. When I use a wildcard to get all the *initial* dependencies from *node_modules* into my vendor chunk, webpack also packs the *async* dependencies into the vendor chunk,

When using an explicit vendor chunk, you can either specify a function or regexp to specify which libs should end up in the vendor chunk.

*Explicit:*

	const libraries = [
		'jquery',
		'whatever'
	];

	module.exports =  {
		optimization: {
			splitChunks: {
				cacheGroups: {
					lib: {
						test: function(chunk) {
							var request = chunk.rawRequest;
							return libraries.indexOf(request) !== -1;   
						},
						chunks: 'initial',
						name: 'lib',
						enforce: true
					},
				},
			},
		},
	}

*Regexp:*

	module.exports =  {
		optimization: {
			occurrenceOrder: true, // tried this, doesn't make a difference

			splitChunks: {
				minSize:0, // tried this, doesn't make a difference
				
				cacheGroups: {
					lib: {
						test: /node_modules/,
						chunks: 'initial',
						name: 'lib',
						enforce: true 
					},
				},
			},
		},
	}

In my case, I am asynchronously loading a module (chart.js, which is loaded through 'ChartLoader.ts'). Find the webpack stats: [stats.zip](https://github.com/webpack/webpack/files/1778466/stats.zip)

When I explicitly define which initial chunks I want in the 'lib' chunk, everything goes okay and when built, ChartLoader.ts and its dependencies end up in a seperate asynchronously loaded chunk. However, when using a wildcard (like /node_modules/), almost everything from node_modules that was previously split into the async chunk ends up in the 'lib' chunk.

To be clear we have this graph:
'ChartHandler' (code splitting point) `await import('ChartLoader')` -> 'ChartLoader' `import { Chart } from 'chart.js`

Interesting, though, if you put 'webpack-stats-regexp.json' (from the attachment) in the excellent [Webpack Visualizer](http://chrisbateman.github.io/webpack-visualizer/), you can see that a subdependency moment.js of 'chart.js' (specifically the wildcard import) is included in the chunk (25).

**If the current behavior is a bug, please provide the steps to reproduce.**
Please let me know if this requires more exploration, and I will try to cook something up.

**What is the expected behavior?**

Because 'chart.js' is referenced from 'ChartLoader', and asynchronously loaded from 'ChartHandler' I would expect both 'ChartLoader' and 'chart.js' to end up in a seperate chunk, even when using a wildcard (since I specified that only initial chunks should be loaded). Using a wildcard or explicit check should not make a difference for 'chart.js' since it is indirectly always referenced beyond the code splitting point.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
Windows 10, Node latest LTS, webpack 4.1.0.

**Comment by Sebazzz** [comment]
Alright, I cooked up [a repro](https://github.com/Sebazzz/financial-app/commit/57ccb2fc397d7d737e493d6ca98959d0b4b23d5f) which is hopefully is clear enough. Ensure yarn is installed, checkout, and run "Run.ps1" in src/App. 

Statistics for this repro:
[repro-stats.zip](https://github.com/webpack/webpack/files/1779041/repro-stats.zip)

Some screenshots of the bundle contents:

** Expected: Chart.js seperated in async chunk**
![explicit-1](https://user-images.githubusercontent.com/1426097/36951519-1f7f9fd0-2005-11e8-9a4f-df6d6bc1d191.PNG)
![explicit-2](https://user-images.githubusercontent.com/1426097/36951521-1f99cc66-2005-11e8-945c-fe6931ee1910.PNG)

** Issue: Chart.js incorporated in main bundle, though it is not an initial chunk **
![regexp-1](https://user-images.githubusercontent.com/1426097/36951522-1fb6fab6-2005-11e8-85fc-33ae3b72422b.PNG)
![regexp-2](https://user-images.githubusercontent.com/1426097/36951524-1fd4827a-2005-11e8-9ea3-fbb849610175.PNG)

**Comment by Sebazzz** [comment]
Anyone?

**Comment by Sebazzz** [comment]
@sokra Since this is obviously a difficult issue, can you indicate whether this might be a bug?

**Comment by EECOLOR** [comment]
Not sure if it helps, but if you have a construction like that webpack will think the given chunk is not a runtime chunk.

[`Chunk.js#L536`](https://github.com/webpack/webpack/blob/master/lib/Chunk.js#L536):
```js
getAllAsyncChunks() {
    const queue = new Set();
    const chunks = new Set();

    const initialChunks = intersect(
        Array.from(this.groupsIterable, g => new Set(g.chunks))
    );

    for (const chunkGroup of this.groupsIterable) {
        for (const child of chunkGroup.childrenIterable) {
            queue.add(child);
        }
    }

    for (const chunkGroup of queue) {
        for (const chunk of chunkGroup.chunks) {
            if (!initialChunks.has(chunk)) {
                chunks.add(chunk);
            }
        }
        for (const child of chunkGroup.childrenIterable) {
            queue.add(child);
        }
    }

    return chunks;
}
```

[`SplitChunksPlugin.js#L100`](https://github.com/webpack/webpack/blob/master/lib/optimize/SplitChunksPlugin.js#L100):
```js
const ASYNC_CHUNK_FILTER = chunk => !chunk.canBeInitial();
```

[`Chunk.js#L198`](https://github.com/webpack/webpack/blob/master/lib/Chunk.js#L198):
```js
canBeInitial() {
    for (const chunkGroup of this._groups) {
        if (chunkGroup.isInitial()) return true;
    }
    return false;
}
```

As you can see, webpack detects an async chunk by making sure it is not in a group with an initial chunk.

I do not have enough knowledge to determine if this can cause trouble. From a naive perspective it I would say it would be best to add a property to a chunk to determine if it is loaded async.

**Comment by Sebazzz** [comment]
If this is not a bug, the webpack docs should at least mention that any default chunk filter is basically useless when you want to build async chunks.

**Comment by EECOLOR** [comment]
I haven't checked your source code, but my guess is that you import `chart.js` in a regular fashion from other non async chunks.

If I am correct, this will cause `chart.js` to be put into another chunk because webpack thinks it will be available anyway. I am not sure how you determine the javascripts that should be rendered to each page, but the `chunk.groupsIterable` has the correct dependency, even though webpack does not recognise the chunk containing `chart.js` as (purely) async.

**Comment by Sebazzz** [comment]
If I import file A synchronously from file B which is asynchronously requested from file C, it should not end up in the chunk where C resides right? Otherwise it would mean that recursively everything that should be loaded asynchronously should also load the dependencies asynchronously.

**Comment by EECOLOR** [comment]
@Sebazzz I don't understand your last comment

**Comment by Sebazzz** [comment]
What you said meant that beyond the async boundary every import into an file that would be imported asynchronously, would need to be imported async as well. The docs inside otherwise, if you import async you create an async boundary..

**Comment by EECOLOR** [comment]
Thank you for the clarification. It is not exactly what I am saying.

If you have sync `import A` from `B` and async `import(B)` from `C` (entry) you can not just tell where `A` ends up. If there is an sync `import A` from `C` (entry) it might end up in a chunk shared by `B` and `C`. This shared chunk is not marked as async and is expected to be present in the page.

This same behavior will happen if there is a sync `import A` from an unrelated `D` (entry). This can be extra tricky in the following case:

- sync `import A` from `B`, async `import(B)` from `C`
- sync `import A` from `D`

If `C` and `D` are used on different pages, the page with `C` should also render any shared chunks that are shared between `B` and non-async entries (in this example `D`).

Please note that I might be wrong, but that is what I think I read in the code. @sokra might be able to shed some light here.

**Comment by Sebazzz** [comment]
In this case the graph is like:

- ChartHandler loads ChartLoader asynchronously
- ChartLoader loads chart.js synchronously
- chart.js is not referenced anywhere else

That would make two chunks:
(charthandler) (chartloader, chart.js)

However, chunks are:
(charthandler, chart.js) (chartloader)

> In the case where a chunk is initial and async ("can be initial") and a static name is provided, it can happen that chunks: "initial" merges modules that were async loaded into a chunk that is loaded initially.

Initial means synchronously loaded from the entry point, right? That is not the case.

> splitChunks will only merge chunks if a constant name is provided. 

If I don't give it a static name, I cannot reference it from HTML and JS (service worker) without server-side postprocessing.

**Comment by EECOLOR** [comment]
I'm not sure if it is still representative, but I see `chart.js` loaded two times:

https://github.com/Sebazzz/financial-app/blob/master/src/App/js/App/Services/ChartLoader.ts#L1
https://github.com/Sebazzz/financial-app/blob/a5fcdb38bce556978202a5959eda5e45b4a2b917/src/App/js/App/Pages/Report/GeneralPage.ts#L4

**Comment by Sebazzz** [comment]
@EECOLOR Correct, but the second instance is only an Typescript interface import. It is omitted in the compiled javascript file.

**Comment by EECOLOR** [comment]
I wonder if webpack knows that too when it determines the chunk groups

**Comment by Sebazzz** [comment]
It would, otherwise chart.js wouldn't end up in the async chunk in my "explicit" example in my report. It would still end up in the initial chunk because it would then be synchronously loaded.
