### ISSUE TITLE
Strange webpack output.

### ISSUE THREAD

**Issue by acupofspirt** [webpack/webpack#6667]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When I upgraded Webpack from 3 to 4 I'v got strange output in dev mode:
```
vue__WEBPACK_IMPORTED_MODULE_0__["default"]vue__WEBPACK_IMPORTED_MODULE_1__["default"].config.performance = "development""development" !== 'production'
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
```
**If the current behavior is a bug, please provide the steps to reproduce.**
Here is config:
``` js
const path = require('path'),
      webpack = require('webpack'),
      VueSSRServerPlugin = require('vue-server-renderer/server-plugin'),
      CopyWebpackPlugin = require('copy-webpack-plugin')

module.exports = {
  mode: 'development',

  entry: path.resolve(__dirname, './js/entry-server.js'),

  output: {
    path: path.resolve(__dirname, '../dist/server'),
    libraryTarget: 'commonjs2',
    filename: 'ssr-bundle.js'
  },

  target: 'node',

  module: {
    rules: [
      {
        test: /\.vue?$/,
        loader: 'vue-loader'
      }
    ]
  },

  plugins: [
    new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/),
    new webpack.DefinePlugin({
      'API_PATH': '"http://192.168.1.8:3001/api/"'
    }),
    new VueSSRServerPlugin(),
    new CopyWebpackPlugin([{from: './js/server'}])
  ],

  performance: {
    maxEntrypointSize: 400000,
    assetFilter: assetFilename => assetFilename.endsWith('.js')
  },

  devtool: false
}
```

Here is part of code: 
``` js
import Vue from 'vue'
Vue.config.performance = process.env.NODE_ENV !== 'production'
```

**What is the expected behavior?**
Output must be correсt without strange duplication.

**If this is a feature request, what is motivation or use case for changing the behavior?**
N/A
**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
Win 7 x64
Node 9.7.1
Webpack 4.1

**Comment by montogeek** [comment]
Can you please create a minimal reproducible code in a repository?

**Comment by acupofspirt** [comment]
@montogeek I think that I understood the reason for such stange behaviour.
Next code produces duplication in output:
``` js
```

**Comment by acupofspirt** [comment]
@montogeek I think that I understood the reason for such stange behaviour.
Code below produces duplication in output:
``` js
const server = require('express')(), 
      webpack = require('webpack'),
      devMiddleware = require('webpack-dev-middleware'),
      config = require('./webpack.client.dev.js'),
      compiler = webpack(config, () => {})

server.use(devMiddleware(compiler))
```

Key moment is an callback function in `webpack(config, () => {})`. If I change to just `webpack(config)` all errors will go away.

**Comment by montogeek** [comment]
That is a direct use of the Node API: https://webpack.js.org/api/node/#webpack-
I don't know exactly but I guess that since you are not passing a callback to handle errors and stats, webpack will handle them by default

**Comment by acupofspirt** [comment]
I see - `webpack()` runs the webpack compiler if a callback function is provided and there is https://github.com/webpack/webpack-dev-middleware/blob/master/index.js#L48 code in dev-middleware, which invoke `.watch()`. As mentioned in docs: _"It’s not allowed to watch or run again before the existing watcher has been closed or invalidated."_

**Comment by sokra** [comment]
You can send a PR to add a flag into the compiler to prevent calling run/watch when another run/watch is still running.

**Comment by acupofspirt** [comment]
Good idea - I'll do it on the weekend.

**Comment by sokra** [comment]
In the `Compiler`.
