### ISSUE TITLE
bundle file is not shown.

### ISSUE THREAD

**Issue by hyunsooda** [webpack/webpack#6668]
**Do you want to request a *feature* or report a *bug*?**
I'm not sure this is bug.

**What is the current behavior?**
I would like to show output file.
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
I should show my output file.
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
"webpack": "^4.1.0",
"webpack-dev-server": "^3.1.0"
"webpack-cli": "^2.0.10"

Hi, I'm korean university student.
I usaully use webpack to bundle my project.
However, one day when I use webpack, my output file which be bundled is not shown in my directory.
so I would like to know how to I can see my output file.
Thank you.

**Comment by montogeek** [comment]
Please post your webpack configuration

**Comment by takahiro-saeki** [comment]
@hyunsooda hi! you should have better show your config, otherwise we and I can't know whether it's bug or not.
please share your configuration.

**Comment by hyunsooda** [comment]
Hi, my configuration is 
module.exports = {
    devtool : 'source-map',
    entry : './main.js',
    output : {
        path : __dirname,
        filename : 'convert_main.js'
    },
    module : {
        rules : [{
            test : /\.js$/,
            exclude : /node_modules/,
            use : [{
                loader : 'babel-loader',
                options : {
                    presets : ['es2015'],
                    plugins : [
                        ['transform-private', {
                            'pattern' : '_'
                        }]
                    ]
                }
            }]        
        }]
    },
    devServer : {
        inline : true,
        port : 7878,
        contentBase : __dirname
    }
}

**Comment by sokra** [comment]
Are you using the webpack-dev-server and expecting the files writting to disk? Note that the webpack-dev-server compiles in memory and intentionally do not write files to disk.

**Comment by hyunsooda** [comment]
oh my god... really?
When I was soldier(2015~2017), in my recollection, my webpack-dev-server has made file in my directory. but now, I think It is not same before. well, Do you know how to make file at the same time I use webpack-dev-server?
Thank you for responding.

**Comment by sokra** [comment]
It never did, but there are plugins for that, i. e. https://github.com/FormidableLabs/webpack-disk-plugin
