### ISSUE TITLE
Loader.exec method does not eval loaders

### ISSUE THREAD

**Issue by kpdecker** [webpack/webpack#667]
Hit a snag where trying to run the `exec` method on a require statement that has a loader in it, causing it to fail out.

Not sure what solutions are available here, but it would be nice to have loader require support within exec or document how to properly "polyfill require" that the val-loader alludes to.

**Comment by kpdecker** [comment]
To elaborate a little bit more, there is a loader that we have where we are trying to do a `.exec` to get css content. Within the content there is something along the lines of:

```
require('./foo.gif')
```

Which we have the proper loader mapping setup for but when run through exec it effectively runs require and tries to exec the gif data as if it were javascript.

**Comment by camshaft** [comment]
I ran into this as well. It would be great if `exec` used the same config as the parent compiler as well. I've tried prepending enhanced-require to the beginning of the source but it's having a hard time resolving some of the loaders.

**Comment by noxan** [comment]
Had been struggling with this one for hours while trying to use `to-string-loader` or `val-loader` in combination with `css-loader` to handle `url()` statements in stylesheets and getting a plain string in return. Referenced this issue from the original one I filled for `to-string-loader`.

**Comment by tookko** [comment]
+1 exactly same problem as @noxan here.

**Comment by kamilkp** [comment]
+1

**Comment by kamilkp** [comment]
Deriving from the parent config would be ideal but currently is there a way to hardcode a config into the .exec call to force it to use a proper loader?

**Comment by jessepollak** [comment]
I'm wondering about this same issue — has anyone made progress?

**Comment by dallas** [comment]
+1 banging our heads against this same issue for a few hours now. Any resolution or guidance would be greatly appreciated!

**Comment by jessepollak** [comment]
I'm not sure if this will be helpful, but I ultimately ended up solving my issue by using the `_compilation.createChildCompiler` functionality. If you're interested, you can see how I do that [here](https://github.com/clef/jql-loader/blob/b70153a0a08799938933a68bc0bd75547e8ab930/index.js#L6-L48).

**Comment by dallas** [comment]
Cool, thanks for that info, @jessepollak!

We actually ended up with a different solution using the [exports loader](https://github.com/webpack/exports-loader) like so:

```
loader: 'exports-loader?module.exports.toString()!css-loader'
```

as advised in https://github.com/gajus/to-string-loader/issues/2#issuecomment-191105608

**Comment by machadoum** [comment]
Same problem as @kpdecker here. I have to build a static json (tojson-loader) that depends on a image path (file-loader).
I made this repository to explain the error: https://github.com/machadoum/webpack-loader-loader

Any idea?

**Comment by bebraw** [comment]
Can you try against webpack 2?

**Comment by cvle** [comment]
Hit on this on webpack 2.

**Comment by cvle** [comment]
I quickly put together a version of `val-loader` that uses a child compiler based on the work done by Nathan Tran for [css-in-js-loader](https://github.com/nthtran/css-in-js-loader).

See https://github.com/wikiwi/value-loader.
