### ISSUE TITLE
minChunks does not accept a function

### ISSUE THREAD

**Issue by AvraamMavridis** [webpack/webpack#6671]
**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**

`minChunks` option is not accepting a function

**If the current behavior is a bug, please provide the steps to reproduce.**

In Webpack 3, in the CommonChunksPlugin we were able to do somthing like:

```
    new webpack.optimize.CommonsChunkPlugin({
      name: 'vendor',
      filename: 'vendorbundle.js',
      children: false,
      minChunks(m) {
        // do not include ui-lib stuff in the vendor bundle
        if (m.context && m.context.indexOf('ui-lib/src') > -1) {
          return false;
        }
        // include only src files, avoids to re-include react, react-dom etc
        return /node_modules/.test(m.context);
      },
    }),
```

**What is the expected behavior?**

In webpack 4 passing a function in the `optimizations` doesnt work. Throws schema exception.

**Comment by sokra** [comment]
see `optimizations.splitChunks.cacheGroups[xxx].test`

**Comment by AvraamMavridis** [comment]
@sokra any example on how `cacheGroups` are used?

Something like

```
  optimization: {
    splitChunks: {
      name: 'vendor',
      filename: 'vendorbundle.js',
      chunks: 'all',
      cacheGroups: {
           vendor: {
              test: ...
           }
      }
    }
  },
```

??

**Comment by AvraamMavridis** [comment]
Ok, I figured that out

```
    splitChunks: {
      name: 'vendor',
      filename: 'vendorbundle.js',
      chunks: 'all',
      cacheGroups: {
        vendor(m) {
          // do not include ui-lib stuff in the vendor bundle
          if (m.context && m.context.indexOf('ui-lib/src') > -1) {
            return false;
          }
          // include only src files, avoids to re-include react, react-dom etc
          return /node_modules/.test(m.context);
        },
      },
    },
```

**Comment by phil-w** [comment]
Could you point me at a definition of the "module" object in that cacheGroups callback please? 
I can see it has field "context", but that's not quite what I need. 

I want to return a different result depending on if the module is genuine "sharable" stuff, or if it's stuff split out by the MiniCssExtractPlugin which I always want to put it in the bundle.
