### ISSUE TITLE
option to proxy optimization.nodeEnv to let ancestor define the NODE_ENV

### ISSUE THREAD

**Issue by andriijas** [webpack/webpack#6673]
**Do you want to request a *feature* or report a *bug*?**
- Feature

**What is the current behavior?**
process.env.NODE_ENV defaults to production and its not possible to let it be process.env.NODE_ENV in user code.

**If the current behavior is a bug, please provide the steps to reproduce.**
- optimization.nodeEnv: false

**What is the expected behavior?**
A way to tell optimization.nodeEnv to not define any NODE_ENV at all, leaving it up to a parent project to define it.

**If this is a feature request, what is motivation or use case for changing the behavior?**
While it makes sense that there is a default for nodeEnv in webpack 4 it would be useful for some projects to let the ancestor of the project define the NODE_ENV rather than enforcing it at project level.  For example in `create-react-app` there is a  https://github.com/facebook/create-react-app/tree/next/packages/react-error-overlay  and its more useful for the overlay to use the NODE_ENV of `create-react-app` rather than its own, unfortunately  the ancestors NODE_ENV is not known at compile time of the overlay project.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
9.7.1, webpack 4.1.0, macos

**Comment by andriijas** [comment]
Yeah but default kicks in:

https://github.com/webpack/webpack/blob/master/lib/WebpackOptionsDefaulter.js#L279

or for some reason process.env.NODE_ENV gets resolved to undefined where its set to development in ancestor app.

**Comment by sokra** [comment]
It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by andriijas** [comment]
Example repo

console output in index.html:

```
foo-tool:  undefined
ancestor:  development
```

expected:

```
foo-tool:  development
ancestor:  development
```

**Comment by ooflorent** [comment]
Using `process` includes `process` polyfill.

- If you want to target node, then use `target: "node"`
- Otherwise set `node: {process: false}`

**Comment by andriijas** [comment]
@ooflorent thanks, that worked. sorry for opening issue!
