### ISSUE TITLE
libraryTarget: 'umd' produces wrong code

### ISSUE THREAD

**Issue by meltedspark** [webpack/webpack#6677]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The code that is being produced when using `libraryTarget: 'umd'` starts with:
```js
(function webpackUniversalModuleDefinition(root, factory) {
    if(typeof exports === 'object' && typeof module === 'object')
        module.exports = factory();
    else if(typeof define === 'function' && define.amd)
        define("lib", [], factory);
    else if(typeof exports === 'object')
        exports["lib"] = factory();
    else
        root["lib"] = factory();
})(window, function() {
return
```
**If the current behavior is a bug, please provide the steps to reproduce.**
1. Checkout this: https://github.com/meltedspark/jest-marbles
2. Run `npm i && npm run build`
3. The code is in `umd` folder

**What is the expected behavior?**
The produced code starts with this (this is the code produced by **webpack 3**): 
```js
(function webpackUniversalModuleDefinition(root, factory) {
    if(typeof exports === 'object' && typeof module === 'object')
        module.exports = factory();
    else if(typeof define === 'function' && define.amd)
        define("lib", [], factory);
    else if(typeof exports === 'object')
        exports["lib"] = factory();
    else
        root["lib"] = factory();
})(this, function() {
return
```
Or with this (from the official [documentation](https://webpack.js.org/configuration/output/#output-librarytarget)):
```js
(function webpackUniversalModuleDefinition(root, factory) {
  if(typeof exports === 'object' && typeof module === 'object')
    module.exports = factory();
  else if(typeof define === 'function' && define.amd)
    define([], factory);
  else if(typeof exports === 'object')
    exports["MyLibrary"] = factory();
  else
    root["MyLibrary"] = factory();
})(typeof self !== 'undefined' ? self : this, function() {
  return _entry_return_;
});
```
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
Webpack 4

**Comment by jdkanani** [comment]
Same issue. @shahbhavir

**Comment by sokra** [comment]
see #6642 and #6525
