### ISSUE TITLE
config absolutePath validation rejects windows paths beginning with C:/

### ISSUE THREAD

**Issue by cspotcode** [webpack/webpack#6679]
**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**

When webpack config `context` is of the form `C:/Users/myUserName/Documents/myproject/` it is rejected by validation as being not absolute.

**If the current behavior is a bug, please provide the steps to reproduce.**

In the node REPL, after `npm install webpack@2`:

```
> require('webpack')({
    context: 'C:/Users/cspotcode/Documents/dev/myproject',
    entry: 'a'
});
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.context: The provided value "C:/Users/cspotcode/Documents/dev/myproject" is not an absolute path!
    at webpack (C:\Users\<... truncated by me>
```

**What is the expected behavior?**

The validation should recognize that path as a valid, absolute path on Windows.  `/` and `\` are both valid path separators on Windows.  Node's `path.isAbsolute()` indicates that the path is absolute.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

webpack v2.7.0
Windows 10
node v9.2.0

EDIT: related to, but not a duplicate of, #4530 and #4533

**Comment by sokra** [comment]
This is expected as `'C:/Users/cspotcode/Documents/dev/myproject'` is not a valid path. It should be `'C:\\Users\\cspotcode\\Documents\\dev\\myproject'`

**Comment by sokra** [comment]
`

**Comment by sokra** [comment]
`/` is only sometimes valid as path separator, but not in general:

Try to type this into your cmd:

```
dir C:/Users
dir C:\Users
```

**Comment by cspotcode** [comment]
Works fine with quotes in cmd, which you would need if the path had spaces anyway.  Works without quotes in PowerShell.  PowerShell is the new default for Windows shell, so I never use cmd.

```
# In cmd.exe
dir "C:/Users"
# In Powershell
dir C:/Users
$foo = 'C:/Users'
dir $foo
```

In general, Windows allows both / and \ as path separators.
