### ISSUE TITLE
If file is missing, Webpack stays in error state even after it is created

### ISSUE THREAD

**Issue by gaearon** [webpack/webpack#668]
This has bugged me for months because it requires restarting dev server which is taking a loong time.

If I accidentally mistype a `require`, Webpack will enter an invalid state:

```js
ERROR in ./src/scripts/atoms/CheckLink.jsx
Module not found: Error: Cannot resolve 'file' or 'directory' ./CheckLink.less in /Users/dan/Documents/Projects/whatever/src/scripts/atoms
 @ ./src/scripts/atoms/CheckLink.jsx 11:0-27
webpack: bundle is now VALID.
```

Now even if I add this file, Webpack won't ever see it, even though it will trigger recompilation.
I have to restart dev server for changes to take effect.

**Comment by gaearon** [comment]
I'm not sure if this happens every time though.
I'll try to give exact steps to repro later today.

**Comment by sokra** [comment]
I know this bug... It's caching the fs access...

**Comment by sokra** [comment]
can you test if this still occurs in `webpack@1.5.0`?

**Comment by gaearon** [comment]
I will on Monday. Thank you.

**Comment by jhnns** [comment]
It may also be related to the jsx-loader. The sass-loader for example had this problem, because we were unable to mark the dependencies correctly. When a syntax error occurred, node-sass just didn't report the malformed file.

**Comment by gaearon** [comment]
This is fixed in 1.5 indeed, thank you!

@jhnns How to reproduce this scenario? I think missing files are now picked up by Webpack but I'm not sure about errors involving syntax errors—can you give me steps to check that?

**Comment by jhnns** [comment]
Write a SyntaxError, correct it and check if the file is compiled by Webpack again.

**Comment by gaearon** [comment]
This has been working for me for quite a while, but I'm using `NoErrorsPlugin`. Not sure if there are any problems without it..
