### ISSUE TITLE
Can't import node core modules( fs, os, child_process, etc.) . 

### ISSUE THREAD

**Issue by aifer2007** [webpack/webpack#6682]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit support request here, instead see https://github.com/angular/angular/blob/master/CONTRIBUTING.md#question
</code></pre>

## Current behavior

I use node core modules (os, fs, path, child_process,  dgram, etc.)  in my Angular project.
I create a new angular4 project:
<pre><code>
ng new ngs
cd ngs
ng serve --open
...
webpack: Compiled successfully.
</code></pre>

Then I try to import 'os' module in app.component.ts file
<pre><code>
import { Component } from '@angular/core';

// to import node core modules
import { CpuInfo } from 'os'

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app';

  constructor(cpu:CpuInfo){

  }
}
</code></pre>
and then 
<pre><code>
ng serve --open
</code></pre>
Some errors are reported by webpack:
<pre><code>
ERROR in src/app/app.component.ts(4,25): error TS2307: Cannot find module 'os'.
webpack: Failed to compile.
</code></pre>

All the node core modules, such as fs, os, child_process, dgram etc., will give the same error 
<pre><code>
Cannot find module 'core-module-name'.
</code></pre>
Yet, much extenral node modules work well at the same time.

## Expected behavior

How to use node core modules( fs, os, child_process, etc.)  with webpack? 

## Environment

<pre><code>
Angular CLI: 1.7.2
Node: 8.9.4
OS: darwin x64
Angular: 5.2.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.2
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.1
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.4  
- Platform:  Mac 

Others:

</code></pre>

**Comment by aifer2007** [comment]
For example,  import a node core module 'os' and a normal module 'q' at the same time in app.component.ts:
<pre><code>
import { Component } from '@angular/core';

// to import node core modules
import { CpuInfo } from 'os'

// to import common node modules
import { when } from 'q';
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app';

  constructor(cpu:CpuInfo){
    when(); // from 'q' module
  }
}

</code></pre>

Then
<pre><code>
 ng serve --open
...
ERROR in src/app/app.component.ts(4,25): error TS2307: Cannot find module 'os'.
webpack: Failed to compile.
</code></pre>

ONLY 'os' reports error: Cannot find module 'os'. 
'q' module works well.

**Comment by ooflorent** [comment]
If you want to use node's builtin, you should target node by adding the following line into your config:

```js
target: "node"
```

**Comment by sokra** [comment]
These node core modules doesn't work in the browser.
