### ISSUE TITLE
chunk is not generated with import()

### ISSUE THREAD

**Issue by AvraamMavridis** [webpack/webpack#6684]
**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**

Using `import()` does not generate a chunk

**If the current behavior is a bug, please provide the steps to reproduce.**

This is my webpack 4 setup

```
  mode: 'production',
  devtool: 'cheap-source-map',
  optimization: {
    splitChunks: {
      name: 'vendor',
      filename: 'vendorbundle.js',
      chunks: 'all',
      cacheGroups: {
        vendor(m) {
          // do not include ui-lib stuff in the vendor bundle
          if (m.context && m.context.indexOf('ui-lib/src') > -1) {
            return false;
          }
          // include only src files, avoids to re-include react, react-dom etc
          return /node_modules/.test(m.context);
        },
      },
    },
    minimize: true,
    minimizer: [
      new UglifyJSPlugin({
        uglifyOptions: {
          output: {
            comments: false,
          },
        },
      }),
    ],
  },
```

Somewhere in my code I have the following line

```
 const messages = await import(/* webpackChunkName: "translations" */ '../i18n/de.json');
```

In my previous Webpack 3 setup this used to generated a chunk (translations).
Should I do something special for webpack 4?

**What is the expected behavior?**

Generate a chunk with the specified name

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

Webpack 4

**Comment by sokra** [comment]
Your `splitChunks` configuration is super weird.

**Comment by AvraamMavridis** [comment]
@sokra 

I managed to create the chunk having

```
  optimization: {
    splitChunks: {
      chunks: 'all',
      cacheGroups: {
        vendor: {
          filename: 'vendorbundle.js',
          test(m) {
            // do not include ui-lib stuff in the vendor bundle
            if (m.context && m.context.indexOf('ui-lib') > -1) {
              return false;
            }
            // include only src files, avoids to re-include react, react-dom etc
            return /node_modules/.test(m.context);
          },
        },
        ignore: {
          filename: 'ignore.js',
          test(m) {
            if (m.context && m.context.indexOf('/fonts/ws-iconset/') > -1) {
              return true;
            }
            if (m.context && m.context.indexOf('sg-styles') > -1) {
              return true;
            }
            return false;
          },
        },
      },
    },
```

But the chunk with `import()` is generated as `0.bundle.js`, what I want is to give it a specific name (`/* webpackChunkName: "translations" */`)

**Comment by AvraamMavridis** [comment]
Another issue I see is that although I use the ExtractTextPlugin I see in my bundle the `scss` files

![screen shot 2018-03-06 at 14 46 03](https://user-images.githubusercontent.com/283690/37035559-38911000-214d-11e8-8e3b-500421cb54f1.png)

**Comment by sokra** [comment]
`output.chunkFilename: "[name].js"`

**Comment by AvraamMavridis** [comment]
@sokra 

thx a lot, that works.

**Comment by Djelnar** [comment]
in my webpack 3 setup i have problem - my chunks are going into main bundle. How can i solve it?

**Comment by hinell** [comment]
@Djelnar have you solved your problem?
