### ISSUE TITLE
Module lookup broken when classname has the same name

### ISSUE THREAD

**Issue by drcmda** [webpack/webpack#6688]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

```js
import * as Module from './module'
export default class Something extends Module.Something
```

gets mangled into

```js
export default class Something extends Something
```
thereby probably causing the class to overwrite the module. If i rename the class or leave it unnamed (since its the default export in that case), it works.

<img width="849" alt="screen shot 2018-03-06 at 13 08 29" src="https://user-images.githubusercontent.com/2223602/37031622-c5ada858-213f-11e8-9677-c2bc474fc8fe.png">
<img width="741" alt="screen shot 2018-03-06 at 13 09 03 1" src="https://user-images.githubusercontent.com/2223602/37031631-ca760fb0-213f-11e8-8666-584ea4eeaf2c.png">

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

Webpack 4.1.0 Node 9 Macos sierra

**Comment by montogeek** [comment]
Could you please create a small repository showing this behaviour?

**Comment by drcmda** [comment]
Here's an example without dependencies. Note: this only happens in mode: 'production'

module.js

```js
export class Hello {}
```

test.js

```js
import * as MODULE from './module'
class Hello extends MODULE.Hello {}
```

index.js

```js
import t from './test'
new t()
```
