### ISSUE TITLE
Any way to only emit HMR updates on watch and not rebuild chunks until requested?

### ISSUE THREAD

**Issue by gaearon** [webpack/webpack#669]
When I change a file, Webpack (with dev server & HMR enabled) emits both new versions of bundles containing that file _and_ HMR update.

It seems like majority of time is spent generating bundles but I have no interest in them unless I refresh.

It it possible that, in HMR mode, Webpack would emit HMR updates on change _but_ only emit bundles if they are explicitly requested (that is, if I press F5)? This would make HMR instant in most cases.

Another option is to emit HMR update first, and only after it is ready, regenerate the bundles.

**Comment by sokra** [comment]
> Another option is to emit HMR update first, and only after it is ready, regenerate the bundles.

:+1:

**Comment by gaearon** [comment]
Anything I can do to help make this happen?

**Comment by sokra** [comment]
You can test it... on the `hot-multi-pass` branch...

**Comment by gaearon** [comment]
Oh man :heart: 
First thing in the morning tomorrow!

**Comment by gaearon** [comment]
Hm.. I see first compilation happens fast but it looks like HMR update kicks in only after the second pass.
I have `multiStep: true` in options.

Maybe I overestimated this change.. Or there's something else yet.

**Comment by sokra** [comment]
Hmm maybe the dev-server need a change too or I missed something...

But I go to bed now.

**Comment by gaearon** [comment]
Yeah me too :-)

I have a minor problem implementing [flux-hot-loader](https://github.com/gaearon/flux-hot-loader/blob/master/index.js) btw, hope to catch you tomorrow in Gitter!

**Comment by sokra** [comment]
no works fine for me... :smile:

**Comment by sokra** [comment]
oh I should merge it in....

**Comment by gaearon** [comment]
I'm testing this in `webpack-2` branch and it doesn't seem to work as intended. Here's the stats I see on hot update:

```
webpack: bundle is now INVALID.
webpack: bundle is now INVALID.
Hash: e2e7e24c9f92abc9133a
Version: webpack 1.9.10
Time: 731ms
    Asset     Size  Chunks             Chunk Names
bundle.js  1.09 MB       0  [emitted]  main
chunk    {0} bundle.js (main) 931 kB [rendered]
    [0] ../~/react/react.js 41 bytes {0}
    [1] ../~/node-libs-browser/~/process/browser.js 2.02 kB {0}
    [2] ../~/react/lib/ReactMount.js 31.2 kB {0}
    [3] ../~/react/lib/invariant.js 1.54 kB {0}
    [4] ../~/webpack/buildin/module.js 241 bytes {0}
    [5] ../~/babel-runtime/core-js/object/define-property.js 103 bytes {0}
    [6] ../~/react-hot-loader/RootInstanceProvider.js 1.18 kB {0}
    [7] ../~/react-hot-loader/makeExportsHot.js 1.38 kB {0}
    [8] ../~/react-hot-loader/~/react-hot-api/modules/index.js 57 bytes {0}
    [9] ../~/react/lib/Object.assign.js 1.26 kB {0}
   [10] ../~/react/lib/ReactElement.js 8.27 kB {0}
   [11] ../~/babel-runtime/~/core-js/library/modules/$.js 2.72 kB {0}
   [12] ../~/react/lib/warning.js 1.9 kB {0}
   [13] ../~/babel-runtime/helpers/interop-require-default.js 148 bytes {0}
   [14] ../~/react/lib/ExecutionEnvironment.js 1.13 kB {0}
  
   ...

  [344] ../~/webpack-dev-server/~/strip-ansi/index.js 161 bytes {0}
  [345] ../~/webpack-dev-server/~/strip-ansi/~/ansi-regex/index.js 145 bytes {0}
  [346] ../~/webpack/buildin/amd-options.js 42 bytes {0}
  [347] ../~/webpack/hot/log-apply-result.js 788 bytes {0}
  [348] multi main 52 bytes {0}
webpack: bundle is now VALID.
```

In the console, I see this:

![screen shot 2015-06-15 at 16 48 31](https://cloud.githubusercontent.com/assets/810438/8161262/66a26938-137e-11e5-90a2-684776142d04.png)

The timer is just `console.time` I put into `io.on("invalid"` and `console.timeEnd` in `reloadApp`.
As you can see it takes *plenty* of time to emit a small hot update file (2 kilobytes).

It feels that it still waits for the whole recompilation before serving the hot update chunk.

**Comment by gaearon** [comment]
This fixes `multiPass` mode for me on OS X: #1171.
Now I get two passes:

```
webpack: bundle is now INVALID.
Hash: b6d0cfc58b3459a1500a
Version: webpack 1.9.10
Time: 539ms
                               Asset      Size  Chunks             Chunk Names
0.1ffc19da1ba9f1bd7625.hot-update.js   1.94 kB       0  [emitted]  main
1ffc19da1ba9f1bd7625.hot-update.json  36 bytes          [emitted]  
chunk    {0} 0.1ffc19da1ba9f1bd7625.hot-update.js (main) 931 kB
    [0] ../~/react/react.js 41 bytes {0}
    [1] ../~/node-libs-browser/~/process/browser.js 2.02 kB {0}
    [2] ../~/react/lib/ReactMount.js 31.2 kB {0}
    [3] ../~/react/lib/invariant.js 1.54 kB {0}

  ...

  [343] ../~/webpack-dev-server/~/socket.io-client/~/to-array/index.js 216 bytes {0}
  [344] ../~/webpack-dev-server/~/strip-ansi/index.js 161 bytes {0}
  [345] ../~/webpack-dev-server/~/strip-ansi/~/ansi-regex/index.js 145 bytes {0}
  [346] ../~/webpack/buildin/amd-options.js 42 bytes {0}
  [347] ../~/webpack/hot/log-apply-result.js 788 bytes {0}
  [348] multi main 52 bytes {0}
Compilation needs an additional pass and will compile again.
webpack: bundle is now VALID.

webpack: bundle is now INVALID.
Hash: b6d0cfc58b3459a1500a
Version: webpack 1.9.10
Time: 996ms
    Asset     Size  Chunks             Chunk Names
bundle.js  1.09 MB       0  [emitted]  main
chunk    {0} bundle.js (main) 931 kB [rendered]
    [0] ../~/react/react.js 41 bytes {0}
    [1] ../~/node-libs-browser/~/process/browser.js 2.02 kB {0}
    [2] ../~/react/lib/ReactMount.js 31.2 kB {0}
  
  ...

  [345] ../~/webpack-dev-server/~/strip-ansi/~/ansi-regex/index.js 145 bytes {0}
  [346] ../~/webpack/buildin/amd-options.js 42 bytes {0}
  [347] ../~/webpack/hot/log-apply-result.js 788 bytes {0}
  [348] multi main 52 bytes {0}
webpack: bundle is now VALID.
```

The first pass is still long though. This part intrigues me:

```
0.1ffc19da1ba9f1bd7625.hot-update.js   1.94 kB       0  [emitted]  main
1ffc19da1ba9f1bd7625.hot-update.json  36 bytes          [emitted]  
chunk    {0} 0.1ffc19da1ba9f1bd7625.hot-update.js (main) 931 kB
```

What's this 931 kB beast? The client only loads the 1.94 kB thing. Is there any unneeded concatenation going on?

**Comment by gaearon** [comment]
An update on this. I'm getting *much* faster, almost instant hot updates (and that's on my new “slow” Macbook) if I tweak #1171 to schedule the main compilation to be about a second after the hot update. It seems that it just can't serve `json` manifest fast if there's a main build being done at the same time.

When the main build is scheduled right away, `hot-update.json` takes about 500ms to be served. When the main build is scheduled after a timeout of 1500ms, `hot-update.json` takes about 10ms to be served.

**Comment by gaearon** [comment]
Related:

https://github.com/webpack/webpack-dev-server/pull/196
https://github.com/webpack/webpack/pull/1173

**Comment by Robinfr** [comment]
Is there any update on this? This looks promising for setups which have multiple entry points since rebuilding all bundles takes too long during development.

**Comment by vasyas** [comment]
Any news on this? Building bundles for all entry points almost kills the HMR for us (

**Comment by niieani** [comment]
Having this would be very important for us too.

**Comment by moimael** [comment]
This would have a huge impact for us, we have a lot of entry points and HMR takes ~5.5s, with all possible wepack optimisations we could find and apply.

**Comment by chris-symplectic** [comment]
Any news on this? "Almost instant hot updates" sounds so tantalizing.

**Comment by Restuta** [comment]
I think the best way to hear the news/updates is to send a PR ;)

**Comment by niieani** [comment]
@webpack-bot, you naughty boy!

**Comment by sokra** [comment]
There is a multiStep mode for the HMRPlugin. You can try it if you want but don't expect too much.

**Comment by montogeek** [comment]
@sibelius 
```
plugins: [
			new webpack.HotModuleReplacementPlugin({
				multiStep: true
			})
]
```

**Comment by peteromano** [comment]
A month away from 2019, and I still see this issue myself with Webpack 4.26, React 16.6, Node 10.13.0 (have tried webpack 3, react 15, node 8.4.0, in different combinations, etc.)

It's actually hurting my business quite badly, but this HAS to be a simple fix.. `multiStep` in the HMR plugin doesn't do anything for me.

Why this even the default webpack behavior? If HMR is enabled, it should be applying HMR updates as the first priority over rebuilding the bundles.

Is there a 2018, webpack 4 solution for delaying the incremental build (or, ideally, only rebuilding on browser page reload......)

@sokra ?

**Comment by evilebottnawi** [comment]
bump

**Comment by evilebottnawi** [comment]
bump

**Comment by alexander-akait** [comment]
I think we can close it in favor https://webpack.js.org/configuration/experiments/#experimentslazycompilation
