### ISSUE TITLE
Webpack 4. Uncaught ReferenceError: webpackHotUpdate is not defined

### ISSUE THREAD

**Issue by StalkAlex** [webpack/webpack#6693]
**Do you want to request a *feature* or report a *bug*?** 
*bug*

**What is the current behavior?**
![capture](https://user-images.githubusercontent.com/2943154/37077073-2246a590-21fb-11e8-9ebb-99d7b690d4b7.JPG)

**If the current behavior is a bug, please provide the steps to reproduce.**
1. Run webpack-dev-server, it builds sucessfully.
2. Open page containing my bundled React code.
3. It runs sucessfully.
4. Change something in jsx to emit hot-update.
5. Webpack rebuilds sucessfully, changes applied.
6. Update whole page using F5 in browser.

**What is the expected behavior?**
After step 6 I expect normal page loading again, but instead I get error messages above and not loaded page. Didn't have such problems in webpack 3.

With this option it works 
```js
  new webpack.HotModuleReplacementPlugin({
     multiStep: true,
  }),
```
 but in webpack 3 it worked like this
```js
  new webpack.HotModuleReplacementPlugin(),
```

**If this is a feature request, what is motivation or use case for changing the behavior?**
*not feature request*

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

webpack: 4.1.0
chrome: last stable
node: 8.9.4
react: 16.2.0

**Comment by bebraw** [comment]
@sokra Maybe it's time to make `multiStep` default or simplify somehow?

**Comment by StalkAlex** [comment]
Maybe I just didn't configured properly webpack v4?

**Comment by clarkdo** [comment]
Add `multiStep` can fix the issue, but `multiStep` will break `html-webpack-plugin` as https://github.com/jantimon/html-webpack-plugin/issues/533 described.

**Comment by jantimon** [comment]
@clarkdo the html-webpack-plugin will switch to the webpack 4 entrypoints api - this should probably fix the multiStep problems

**Comment by TSMMark** [comment]
For the record,
```js
multiStep: true
```

fixes the same error for me as well.

**Comment by dtothefp** [comment]
This strangely just started occurring for me.

webpack v4.6.0
webpack-dev-server v3.1.3
react-hot-loader v4.0.1

Everything works fine until I reload the current page and then I get the `Uncaught ReferenceError: webpackHotUpdate is not defined` error. Adding `multi-step` seems to work but messes up things like progress bars and seems to slow down my build after multiple saves.

**Comment by evilebottnawi** [comment]
@GabrielDuarteM can you test this with latest webpack (i.e. `4.8.2`)?

**Comment by GabrielDuarteM** [comment]
@evilebottnawi I just tested using `4.8.2`, still the same thing

**Comment by GabrielDuarteM** [comment]
@evilebottnawi I still did not found a reliable way to reproduce it, but i'm gonna try to make it and post here

**Comment by GabrielDuarteM** [comment]
What i noticed is that webpack throws a message `Compilation needs an additional pass and will compile again.` when the build needs to be run twice, and webpack only do this when that `multistep` option is enabled on `webpack-dev-server`

**Comment by GabrielDuarteM** [comment]
@evilebottnawi I got a reproducible repo available [here](https://github.com/GabrielDuarteM/webpack-multistep), can you check it out?

To reproduce the bug:

* Run `yarn install` or `npm install`
* Run the script `start`
* Run the script `start:server` in another shell instance
* Go to `localhost:3000`
* Edit the render of the file `src/components/App/App.js` (in my case, I included the letter "a" between the `<div>` and the `<Routes />` component)
* See the app crash and the following error on the console `Uncaught ReferenceError: webpackHotUpdate is not defined`

If you add the `multistep` option i said above, the message `Compilation needs an additional pass and will compile again.` will appear, the build will run twice and the content will load on the second build, but on larger projects, the wait time is too long to bear and i see no reason why the build should run twice.

That only started happening after the upgrade from webpack 3 to webpack 4.

**Comment by GabrielDuarteM** [comment]
I think the issue was with the plugin `assets-webpack-plugin`.

If anyone is having the same problem, I got to fix the issue I was having simply by changing from `assets-webpack-plugin` to [`webpack-manifest-plugin`](https://www.npmjs.com/package/webpack-manifest-plugin), the same one that `create-react-app` uses. After that, i could remove the `multiStep: true`, and everything returned back to normal.

**Comment by f3l1x** [comment]
@GabrielDuarteM Issue still remains. I think it's in html-webpack-plugin.

```
 ｢wdm｣: Compiled successfully.
ℹ ｢wdm｣: Compiling...
  0% compiling/<--path-->node_modules/html-webpack-plugin/lib/compiler.js:111
          content: childCompilation.assets[outputName].source()
                                                       ^

TypeError: Cannot read property 'source' of undefined
    at childCompiler.runAsChild (/node_modules/html-webpack-plugin/lib/compiler.js:111:56)
    at compile (/<--path-->node_modules/webpack/lib/Compiler.js:242:11)
    at hooks.afterCompile.callAsync.err (/<--path-->node_modules/webpack/lib/Compiler.js:487:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/<--path-->node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/<--path-->node_modules/tapable/lib/Hook.js:35:21)
    at compilation.seal.err (/<--path-->node_modules/webpack/lib/Compiler.js:484:30)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/<--path-->node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/<--path-->node_modules/tapable/lib/Hook.js:35:21)
    at hooks.optimizeAssets.callAsync.err (/<--path-->node_modules/webpack/lib/Compilation.js:966:35)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/<--path-->node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/<--path-->node_modules/tapable/lib/Hook.js:35:21)
    at hooks.optimizeChunkAssets.callAsync.err (/<--path-->node_modules/webpack/lib/Compilation.js:957:32)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/<--path-->node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/<--path-->node_modules/tapable/lib/Hook.js:35:21)
    at hooks.additionalAssets.callAsync.err (/<--path-->node_modules/webpack/lib/Compilation.js:952:36)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/<--path-->node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
```

**Comment by evilebottnawi** [comment]
@f3l1x please look on your stacktrace, problem in `html-webpack-plugin`, please create issue in their repo

**Comment by jantimon** [comment]
@f3l1x could you please try the https://github.com/jantimon/html-webpack-plugin/tree/webpack-4 branch - I am not sure but maybe it fixes your issue

**Comment by f3l1x** [comment]
@jantimon It's fixed now. Thanks.

**Comment by darkowic** [comment]
@jantimon I've just tried `html-webpack-plugin` alpha version and HMR is broken with `multiStep: true` option.

Webpack: 4.12.0

**Comment by darkowic** [comment]
```
node_modules/html-webpack-plugin/lib/compiler.js:100
          content: childCompilation.assets[outputName].source()
                                                       ^

TypeError: Cannot read property 'source' of undefined
```
It is gone when setting `multiStep` to false
```
new webpack.HotModuleReplacementPlugin({
          multiStep: false,
        })
```

"html-webpack-plugin": "^4.0.0-alpha" - checked in `package-lock` and there is no old version

**Comment by jantimon** [comment]
The html-webpack-plugin calls

```
childCompiler.runAsChild((err, entries, childCompilation) => {
```
and expects that once the callback is executed the compilation is done.

https://github.com/jantimon/html-webpack-plugin/blob/c6f0f5ab6daab0469fd5eefae839c3bd12ec732e/lib/compiler.js#L73-L101

Any idea how we could change that?

**Comment by darklightcode** [comment]
I just encountered 'webpackHotUpdate is not defined' on Internet Explorer 11, win10.
The error turned out to be from **Google Recaptcha**.

I removed `import "grecaptcha"` from my file and everthing worked as it should.
If you are using typescript, add in your `global.d.ts` , the module declaration `declare var grecaptcha: any;`.

**Comment by Timehello** [comment]
I have fixed this by switch runtimeChunk to true.
![image](https://user-images.githubusercontent.com/7313124/43381746-372eeb14-9408-11e8-9f0c-5d6de5ba1158.png)

**Comment by manniL** [comment]
Still present.

**Comment by Remexllee** [comment]
I have this issue too in my local dev env.
I fixed it by change the watch to `false` in RunConfigPlugin.

```
  plugins: [
    new RunConfigPlugin({
      watch: **false**,
      serverConfig
    })
 ]

**Comment by BonBonSlick** [comment]
Also sometimes clearing project cache and rebuilding from scratch might help.
EG remove dist build folder and run webpack again.

**Comment by R10burning** [comment]
new webpack.HotModuleReplacementPlugin({ multiStep: true }  not work  for me 
    "webpack": "^4.42.1",
    "webpack-cli": "^3.3.11",
    "webpack-dev-server": "^3.10.3",
    "webpack-merge": "^4.2.2"

**Comment by evilebottnawi** [comment]
Somebody can create reproducible test repo?

**Comment by wuyuweixin** [comment]
runtimeChunk: true

**Comment by evilebottnawi** [comment]
Please create reproducible test repo, thanks

**Comment by FishOrBear** [comment]
[Test.zip](https://github.com/webpack/webpack/files/4603891/Test.zip)
```
yarn
yarn dev
```

in vscode f5

change /src/renderer/index.tsx

config/webpack.config.renderer.dev.ts
```
//line 192
   new webpack.HotModuleReplacementPlugin({
            multiStep: true // webpackHotUpdate undefine 
            // multiStep: false  //is ok
        }),
```

In my complex project, this will appear
![image](https://user-images.githubusercontent.com/19372111/81478000-3c4c6c80-924d-11ea-8ded-deead8b42ae2.png)

In the test project, there will be a problem of page loss.


@evilebottnawi

**Comment by web-mi** [comment]
Hi,
i know its an old issue but i had the same problem.
If you are using webpack-assets-manifest and reading the manifest.json on reload you have to ignore the hot-update files on hmr.
webpack-assets-manifest already includes an regex but reads the webpack.config.js option if its set.
If you set the defaults in webpack.config.js it will ignore them automatically and will no longer override your base files in manifest.json.

`
output: {
    ...,
    hotUpdateChunkFilename: '[id].[fullhash].hot-update.js',
    hotUpdateMainFilename: '[runtime].[fullhash].hot-update.json',
},
`

Hope it helps

**Comment by simPod** [comment]
@web-mi Thx, that helped. Had the issue with w5.

**Comment by alexander-akait** [comment]
I think nothing to fix on webpack side, here bug with `webpack-manifest-plugin`, also manifest generation (i.e. `webpack-manifest-plugin` inside core in our roadmap https://github.com/webpack/webpack/issues/11562), workaround above https://github.com/webpack/webpack/issues/6693#issuecomment-745688108

**Comment by JordanRifaey** [comment]
Upgrading `webpack-assets-manifest` to v5 fixed it for me.
