### ISSUE TITLE
split chunks for async chunk doesn't work

### ISSUE THREAD

**Issue by lili21** [webpack/webpack#6696]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
there's no *async-vendors* chunk.

**If the current behavior is a bug, please provide the steps to reproduce.**

[reproduce repo](https://github.com/lili21/webpack4-demo)

**What is the expected behavior?**
*async-vendors* chunk should be generated.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

Node:  v9.3.0
webpack: v4.1.0
OS: macOS 10.13.1

**webpack config**

```javascript
module.exports = {
  mode: 'production',
  output: {
    filename: '[name].[chunkhash].js',
    chunkFilename: '[name].[chunkhash].js'
  },
  optimization: {
    splitChunks: {
      cacheGroups: {
        vendors: {
          test: /[\\/]node_modules[\\/]/,
          chunks: 'initial',
          priority: -10,
          name: 'vendors',
        },
        'async-vendors': {
          test: /[\\/]node_modules[\\/]/,
          minChunks: 2,
          chunks: 'async',
          priority: 0,
          name: 'async-vendors'
        }
      }
    },
    runtimeChunk: true,
    namedModules: true,
    namedChunks: true
  }
}
```

**Comment by montogeek** [comment]
Thanks for the report!
