### ISSUE TITLE
Named exports of CJS modules in ESM

### ISSUE THREAD

**Issue by jdalton** [webpack/webpack#6699]
The choice to go all-in on `default` export only for CJS in ESM in Webpack 4 was a bit premature since these details are still being ironed out by Node *(I'm helping with one possible implementation)*. It looks like it's also causing issues in [other projects](https://github.com/apollographql/react-apollo/issues/1737).

Is there a way to enabled named exports of CJS modules in ESM with Webpack 4?

**Update:**

<img width="636" src="https://user-images.githubusercontent.com/4303/37104375-66191542-21e1-11e8-9c76-c837376b7cbc.png">

**Comment by jdalton** [comment]
**Update:**
<img width="636" src="https://user-images.githubusercontent.com/4303/37104375-66191542-21e1-11e8-9c76-c837376b7cbc.png">

**Comment by jdalton** [comment]
Does normal ESM (.js) mean `module.rules[].type` of `"javascript/auto"`?

**Comment by sokra** [comment]
> Does normal ESM (.js) mean module.rules[].type of "javascript/auto"?

yes

**Comment by Havunen** [comment]
So its not currently possible to have named export in `.mjs` file? In inferno we have `.mjs` extensions for module entry point which has named exports. Now recently we got this issue: 
https://github.com/infernojs/inferno/issues/1296

This has been working previously by adding `.mjs` to resolve.extensions. Also doesn't the specification mention here: https://github.com/nodejs/node-eps/blob/master/002-es-modules.md#47-commonjs-consuming-es
that `export {foo as bar}` is allowed. I'm confused. Webpack compatibility is important for us what is the recommended way now?

**Comment by sokra** [comment]
> So its not currently possible to have named export in .mjs file?

That's possible, we are talking about a `.mjs` importing from a CJS file. Example:

``` js
// cjs.js
module.exports = { a: 1, b: 2 }
```

``` js
// module.mjs (MJS)
import cjs from "./cjs" // possible
import { a } from "./cjs" // not possible
```

``` js
// module.js (NOT MJS)
import cjs from "./cjs" // possible
import { a } from "./cjs" // possible
```

**Comment by jdalton** [comment]
@sokra If you don't specify a type and have ESM in .js will it support named exports? I was talking with Sean and it looks like type:auto is used for ESM in .js automatically without having to explicit specify the type.

**Comment by jdalton** [comment]
It looks like named exports of CJS are supported for ESM with .js out of the box. So it's all good on that front at least.

**Comment by jdalton** [comment]
It would be super nice if that was documented. The release [blog post](https://medium.com/webpack/webpack-4-released-today-6cdb994702d4) mentions ESM with `.mjs` default *(only)* and doesn't mention that existing ESM with `.js` will not only *"just work"* but work in a less limited way.

**Comment by eldh** [comment]
Is it possible to force all .mjs files to be loaded as `javascript/auto`?

**Comment by michael-ciniawsky** [comment]
**webpack.config.js**
```js
{
  type: 'javascript/auto',
  test: /\.mjs$/,
  use: [ ...loaders ]
}
```

**Comment by snoack** [comment]
Node.js is now (as of 14.15.0) providing named exports for CommonJS modules imported from ESM. So if `javascript/esm` in webpack is meant to be consistent with Node.js, then the current semantics are incorrect, and this issue should be revisited.
