### ISSUE TITLE
Parsing fails because of illegal return statement

### ISSUE THREAD

**Issue by jhnns** [webpack/webpack#67]
If I write in a module something like this:

``` javascript
if (typeof window === "undefined") {
    return;
}
```

webpack will throw a parsing error because of a illegal return statement. 

I know, the described case is no good coding style, but this code works in node. The problem is that uglifyjs expects the code to be top-level. But in fact it's always wrapped within a function (even in node, because they just add a [wrapper](https://github.com/joyent/node/blob/master/src/node.js#L839) around the module code).

I don't know if this is the only case where it matters, but to be consistent, uglifyjs should parse the code wrapped in a function statement.

**Comment by timoxley** [comment]
@sokra what do you recommend when such a problem stems from 3rd-party packages maintained by an [unwilling/webpack-adverse author](https://github.com/defunctzombie/synthetic-dom-events/pull/10#issuecomment-114681554)?
