### ISSUE TITLE
https://webpack.js.org/configuration/resolve/#resolve-alias

### ISSUE THREAD

**Issue by chinazhaghai** [webpack/webpack#6705]
alias:{ xyz: "modu/dir" }
**import 'xyz/file.js' => ///abc/node_modules/*dir*/file.js**
alias:{xyz:"xyz/dir"}
**import 'xyz/file.js' => ///abc/node_modules/*xyz/dir*/file.js**

**Comment by sokra** [comment]
@webpack-bot move to webpack/webpack.js.org
