### ISSUE TITLE
Documentation: devserver --open flag docs incomplete/incorrect

### ISSUE THREAD

**Issue by bobwalker99** [webpack/webpack#6706]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Documentation [here](https://webpack.js.org/configuration/dev-server/#devserver-open) states that to open a specific browser, "just  pass its name": `webpack-dev-server --open 'Google Chrome'`.
This does not work in my environment (Windows 10 x64, node 9.6.1, yarn 1.5.1, webpack 4.1.1):
1. With single quotes (as per the docs) it splits the string on the space and errors with "Windows cannot find "Google'. Make sure you typed the name correctly and try again."
2. With double quotes it doesn't split the string but still errors, with "Windows cannot find 'Google Chrome'. Make sure you typed the name correctly and try again."
 
**If the current behavior is a bug, please provide the steps to reproduce.**
(See above), add this to package.json "scripts":
```
"serve": "webpack-dev-server --mode development --open 'Google Chrome'",
```
or
```
"serve": "webpack-dev-server --mode development --open \"Google Chrome\"",
```
Then run either `yarn serve` or `npm run serve`.

**What is the expected behavior?**
Webpack dev server opens Google Chrome, regardless of default browser. I think this is just a doumentation issue, If I change it to `chrome`, i.e. 
```
"serve": "webpack-dev-server --mode development --progress --colors --hot --watch --open chrome"
```
...it works fine.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
(Chrome 65.0.3325.146, default browser Firefox)

**Comment by ooflorent** [comment]
@webpack-bot move to webpack/webpack-dev-server
