### ISSUE TITLE
webpack 4 - redux warnings due to changed defaults

### ISSUE THREAD

**Issue by iongion** [webpack/webpack#6708]
This issue on redux https://github.com/reactjs/redux/issues/2878 appears due to the fact that the developers rely on detecting minification by analyzing if the name of the functions have been mangled.

```
if (process.env.NODE_ENV !== 'production' && isCrushed.name !== 'isCrushed') {
  warning('You are currently using minified code outside of NODE_ENV === \'production\'. ' + 'This means that you are running a slower development build of Redux. ' + 'You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify ' + 'or DefinePlugin for webpack (http://stackoverflow.com/questions/30030031) ' + 'to ensure you have the correct code for your production build.');
}
```

The code expects `isCrushed` but the new defaults in webpack 4, output `es_isCrushed` as function name.

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template.

**Comment by iongion** [comment]
I removed the template because it had a lot of noise, I reduced the issue to minimal information you need to understand it, without other noise. It is up to you if you want to ignore the issue. Here is a sample project, where it shows up, together with other issues of webpack 4 such as broken hot reload for css hot reload plugin.
 It is not really fun or easy to chase the source of problems [react-demo.zip](https://github.com/webpack/webpack/files/1793942/react-demo.zip) and having as little noise as possible is good.

I understand the template is helpful and avoids you from dealing with repetitive issue reporting problems, but this does not mean 7 lines of text are hard to read and identify if ambiguities are created by the issue format or the expressed problem.

Thank you for reading it and having a look.

```webpack 4.x has a default in some of its plugins that makes it generate/compress/uglify/minify function names by adding es_ prefix, which is unexpected for other plugins relying on code transformation to detect minified code```

**Comment by iongion** [comment]
@michaeldzjap because the developer did not like the report, not following the template

**Comment by michaeldzjap** [comment]
@iongion I filed a new issue (linking this one), following the provided template. Let's see.
