### ISSUE TITLE
Duplicate files generated if namedChunkFilename is specified

### ISSUE THREAD

**Issue by dimsmol** [webpack/webpack#671]
For example

```
output: {
  chunkFilename: 'not_named_[id].[chunkhash].[name].js',
  namedChunkFilename: 'named_[id].[chunkhash].[name].js',
}
```

will generate two js files for every named chunk - one according to first name template and one according to second. File names will be identical except for a prefix (not_named vs named) and file contents will be absolutely identical.

Even worse,for entry js file it will also generate duplicate file according to the second name template.

I think the expected behavior is to use namedChunkFilename for named chunks only (not to use for entry chunks and/or not named chunks) and not to use chunkFilename for named chunks if namedChunkFilename is specified (chunkFilename should be used for named chunks only if namedChunkFilename is omitted).

Also, documentation should be updated to mention that:

* [name] can be used in chunkFilename and will be chunk name for named chunks and equal to [id] for not named (it works this way currently and it's fine, but needs to be fixed in documentation)
* both [id] and [chunkhash] can be used for namedChunkFilename (they actually can, need to fix in docs)

PS As a workaround, currently I recommend not to use namedChunkFilename and use chunkFilename for both named and not named chunks, using [name] if needed.

**Comment by sokra** [comment]
I removed `namedChunkFilename` from the documentation as it's absolute useless...
