### ISSUE TITLE
Webpack 4 Documentation

### ISSUE THREAD

**Issue by bannostookaylo** [webpack/webpack#6711]
Is it just me or is there no documentation yet for Webpack 4? I am trying to read more about this "splitChunks" thing but I can't find crap on the website. Hell the website shows version 4.1.1 but still says to use CommonsChunkPlugin

**Comment by montogeek** [comment]
@webpack-bot move to webpack/webpack.js.org

**Comment by jhamPac** [comment]
Same here, I can't find anything about the optimization property.

**Comment by montogeek** [comment]
Please submit this issue to https://github.com/webpack/webpack.js.org

**Comment by ooflorent** [comment]
@webpack-bot move to webpack/webpack.js.org
