### ISSUE TITLE
[Suggestion] Restrict target about size limit checking.

### ISSUE THREAD

**Issue by mc-zone** [webpack/webpack#6715]
**Do you want to request a *feature* or report a *bug*?**
Improvment

**What is the current behavior?**
Size warning will show if there are big assets generated, even with `target:node`.
```
WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  main.bundle.js (1.24 MiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  main (1.24 MiB)
      main.bundle.js


WARNING in webpack performance recommendations:
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Build a single quite large bundle with node target.

```javascript
module.exports = {
  entry:"./index.js",
  output:{
    path:path.resolve(__dirname, "./dist"),
    filename:"[name].bundle.js",
  },
  mode:"production",
  target:"node",
};
```

index.js:
```javascript
import * as s1 from "react";
import * as s2 from "moment";
import * as s3 from "antd";
import * as s4 from "react-dom";
```

**What is the expected behavior?**
Only `web` or `webworker` target need this, I think.
**If this is a feature request, what is motivation or use case for changing the behavior?**

I saw previous code about the target checking for `performance.hints` in #3604 (#3216) (Cc @TheLarkInn) . At that time, only web and webworker would show size warnings. 

But looks like it was rewritten to:
https://github.com/webpack/webpack/blob/41bb63ad69d0f32c042e74e732cb045b5966c452/lib/WebpackOptionsDefaulter.js#L183-L187
not sure when or for what.

Actually now in my `target:node` projects I often receive size warning messages but it seems useless. And I prefer to pack all my modules into one bundle than split it separately. Because I think the file size has less effect about some backend target, in other words, using one bundle even reduce I/O times.

So:
- Should we add the target checking back to `performance.hints` to avoid this? 
- Or should add a new option to performance/SizeLimitPlugin such as `includeTarget`? (in case there are some other places are using performance.hints too)

I'd like to make a PR if it needed. Just want to make sure which way is right at first.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

Version:4.1.1

**Comment by sokra** [comment]
Send a PR defaulting `performance` to false in not web related targets
