### ISSUE TITLE
entry as function not supported everywhere

### ISSUE THREAD

**Issue by ndelangen** [webpack/webpack#6718]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
In the webpack config, the value of the entry property CAN be a function. This is used by [`webpack-watched-glob-entries-plugin`](https://github.com/Milanzor/webpack-watched-glob-entries-plugin) (and other similar plugins).

However this feature doesn't seem to be supported by a few other plugins in the ecosystem.
The one I'm running into at this time is `webpack-hot-client` which I'm using via `webpack-serve`. Webpack is on the latest 4.x.x version.

**If the current behavior is a bug, please provide the steps to reproduce.**

Here's a reproduction repo:
https://github.com/ndelangen/webpack-entry-function-reprodution

to reproduce run:
- clone repo
- `yarn install`
- `yarn dev`
- `yarn serve`

<details>
<summary>minimal webpack config:</summary>

```js
const path = require('path');

const webpack = require('webpack');
const WebpackWatchedGlobEntries = require('webpack-watched-glob-entries-plugin');


module.exports = {
  entry: WebpackWatchedGlobEntries.getEntries(['./in/**/*.example.js']),
  output: {
    filename: 'out/[name].js',
    library: 'example_[id]',
    publicPath: '/',
  },
  plugins: [
    new WebpackWatchedGlobEntries(),
  ],
};
```

</details>

<details>
<summary>full config I'm using:</summary>

```js
// vendor-bundles.webpack.config.js
const webpack = require('webpack');

module.exports = {
  entry: {
    sb: ['@sb/core'],
    react: ['react'],
  },

  output: {
    filename: 'out/[name].dll.js',
    library: '[name]_dll',
  },

  plugins: [
    new webpack.DllPlugin({
      path: './out/[name]-manifest.json',
      name: '[name]_dll',
    }),
  ],
};

```

```js
// webpack.entries.config.js
const path = require('path');

const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const WebpackWatchedGlobEntries = require('webpack-watched-glob-entries-plugin');

function resolve(dir) {
  return path.join(__dirname, dir);
}

module.exports = {
  entry: WebpackWatchedGlobEntries.getEntries(['./in/**/*.example.js']),
  output: {
    filename: 'out/[name].js',
    library: 'example_[id]',
    publicPath: '/',
  },
  module: {
    rules: [
      {
        test: /\.jsx?$/,
        exclude: /node_modules/,
        use: ['babel-loader'],
      },
      {
        test: /\.ejs$/,
        loader: 'ejs-loader',
      },
    ],
  },
  plugins: [
    new WebpackWatchedGlobEntries(),
    new webpack.DllReferencePlugin({
      context: resolve('.'),
      manifest: require('./out/sb-manifest.json'),
    }),
    new webpack.DllReferencePlugin({
      context: resolve('.'),
      manifest: require('./out/react-manifest.json'),
    }),
    new HtmlWebpackPlugin({
      filename: resolve('./out/iframe.html'),
      inject: false,
      scripts: ['/out/react.dll.js', '/out/sb.dll.js'],
      template: 'templates/iframe.ejs',
      xhtml: true,

      minify: {
        collapseBooleanAttributes: true,
        collapseWhitespace: true,
        decodeEntities: true,
        keepClosingSlash: true,
        removeComments: true,
        removeScriptTypeAttributes: true,
      },
    }),
  ],
};
```

</details>

Then when I run this config via `webpack-serve` there's an error from `webpack-hot-client`:

```
yarn run v1.5.1
$ webpack-serve --config webpack.entries.config.js
TypeError: webpack-hot-client: The value of `entry` must be an Array or Object. Please check your webpack config.
    at validateEntry (/Users/dev/Projects/GitHub/storybook/experiment-v4/node_modules/webpack-hot-client/lib/util.js:124:15)
    at module.exports (/Users/dev/Projects/GitHub/storybook/experiment-v4/node_modules/webpack-hot-client/index.js:32:3)
    at fn (/Users/dev/Projects/GitHub/storybook/experiment-v4/node_modules/koa-webpack/index.js:84:32)
    at Object.webpack (/Users/dev/Projects/GitHub/storybook/experiment-v4/node_modules/webpack-serve/lib/server.js:32:25)
    at Promise.all.then (/Users/dev/Projects/GitHub/storybook/experiment-v4/node_modules/webpack-serve/lib/server.js:127:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
Error: An error was thrown while initializing koa-webpack
 TypeError: webpack-hot-client: The value of `entry` must be an Array or Object. Please check your webpack config.
    at Object.webpack (/Users/dev/Projects/GitHub/storybook/experiment-v4/node_modules/webpack-serve/lib/server.js:43:15)
    at Promise.all.then (/Users/dev/Projects/GitHub/storybook/experiment-v4/node_modules/webpack-serve/lib/server.js:127:24)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c webpack-serve --config webpack.entries.config.js
Directory: /Users/dev/Projects/GitHub/storybook/experiment-v4/bundler
Output:
```

**What is the expected behavior?**
I'm expecting no error, and the compilation to be successful.

I am able to get this behavior by editing `node_modules/webpack-hot-client/lib/util.js` a bit.

Here's the relevant change ( in 2 places ):
```js
const { entry: temp } = comp.options;
const entry = typeof temp === 'function' ? temp() : temp;
```

If this is a good approach to fix this issue, when indeed it's a legitimate bug, I'd like to submit a fix PR myself.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
macOS, Node 9, Webpack 4

**Comment by shellscape** [comment]
@ndelangen First, thanks for the PR on `webpack-hot-client`, much appreciated.

There's a problem with webpack that's existed for a long while, and it's part of the reason you're running into this: **webpack and its CLI have long been out of sync.** The big caveat with `Function` and `Promise` is that those two config types are _only supported by the CLI and not webpack's API_. You'll find the same issues you're facing with plugins when using webpack's API directly. In face, the API is actually very naive about options: you get a `PlainObjecrt` or an `Array` of the same, it's it. https://github.com/webpack/webpack/blob/master/lib/webpack.js#L27-L29

The larger issue here is that the CLI and API are out of sync. That's something on the radar to address, but its not going to be quick and will likely take several major versions of each module (webpack and webpack-cli) to correct.

So around these mistakes in architecture, there have emerged patterns. Modules which furnish a CLI (webpack-serve, webpack-dev-server, create-react-app, etc) have implemented support for the two "rogue" config types, and pass their results onto the API (and plugins) essentially mimicking webpack-cli in this way. That's what you ran into with `webpack-hot-client` - the plugin behaves exactly like the API in it's expectations of what a config should look like. If all plugins try to support the config of both CLI and API, it's going to make an awful mess, as each are specific to the environment they're targeting at the moment.
