### ISSUE TITLE
 Error during loading module: TypeError: Cannot read property 'includes' of undefined (Windows)

### ISSUE THREAD

**Issue by MrDarkSkil** [webpack/webpack#6722]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**

import() does't work with webpack alias on Windows OS 

**If the current behavior is a bug, please provide the steps to reproduce.**

create an alias on webpack.config.js like that
```javascript
  resolve: {
    alias: {
      '@Modules': process.env.HOME + '/.ezgames/modules/'
    },
    extensions: ['.js', '.json', '.node']
  },
```
and try to import a script with
```javascript
  const module = 'test'
  import(`@Modules/${module}/index.js`)
      .then((m) => {
        m = m.default
        console.log(m.title)
      })
      .catch(err => {
        console.error('Error during loading module: ' + err)
        callback()
      })
```

I get another error with alias in console on windows ( FIXED )
```console
 ERROR in ./node_modules/vue-loader/lib/template-compiler?{"id":"data-v-d013f384","hasScoped":true,"buble":{"transforms":{}}}!./node_modules/vue-loader/lib/selector.js?type=template&index=0!./src/renderer/components/Includes/Sidebar.vue
  Module not found: Error: Can't resolve '@Modules' in 'C:\Users\Leo Hubert\Desktop\launcher-ezgames.eu\src\renderer\components\Includes'
   @ ./node_modules/vue-loader/lib/template-compiler?{"id":"data-v-d013f384","hasScoped":true,"buble":{"transforms":{}}}!./node_modules/vue-loader/lib/selector.js?type=template&index=0!./src/renderer/components/Includes/Sidebar.vue 63:35-66:44
   @ ./src/renderer/components/Includes/Sidebar.vue
   @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/renderer/App.vue
   @ ./src/renderer/App.vue
   @ ./src/renderer/main.js
   @ multi ./.electron-vue/dev-client ./src/renderer/main.js

```

**What is the expected behavior?**

Load correctly the node.js script 

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

Node.js => 9.5.0
webpack => 3.10.0
Operating System => Windows 10

**Comment by michael-ciniawsky** [comment]
Does the `vue-loader` respect `config.resolve.alias` ?

**Comment by MrDarkSkil** [comment]
Yes but it work on Linux and maxOS, i get this error on windows.

And vue-loader error is not my primary bug, on windows (in Node.Js) i get this error ```Error during loading module: TypeError: Cannot read property 'includes' of undefined```

**Comment by michael-ciniawsky** [comment]
hmm... it's difficult to really provide help with the info given, maybe  

```diff
+ const path = require('path')

alias: {
-  '@Modules': process.env.HOME + '/.ezgames/modules/'
+  '@Modules': path.resolve(process.env.HOME, '.ezgames', 'modules')
},
```

```
'C:\Users\Leo Hubert\Desktop\launcher-ezgames.eu\src\renderer\components\Includes' === process.env.HOME ?
```

**Comment by MrDarkSkil** [comment]
Ok for vue-loader error it's fixed, I don't know why but it's fixed now x) 

I still get this error in console ```Error during loading module: TypeError: Cannot read property 'includes' of undefined```do you know why ?

**Comment by sokra** [comment]
Could you add the stack trace?

**Comment by MrDarkSkil** [comment]
I did not see that one of my collaborators had a file, so the problem is not webpack x) Sorry for the inconvenience 😄
