### ISSUE TITLE
config.stats has no option to show hidden modules (CLI: --display-modules)

### ISSUE THREAD

**Issue by ARDivekar** [webpack/webpack#6726]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
In [the docs](https://webpack.js.org/configuration/stats/#stats) I'm trying to find the option of `config.stats` that replicates `--display-modules`, but I can't seem to find it.
Setting `config.stats` to `"verbose"` shows all the modules; I'm not using that since it is not sorted by depth (which is part of what I require).
I have tried setting `stats.maxModules` to `100000`, but that does not show them either.

**If the current behavior is a bug, please provide the steps to reproduce.**
N/A

**What is the expected behavior?**
Setting `config.stats.hiddenModules` to `true` will show the hidden modules, as with `--display-modules` on the CLI.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Parity of `config.stats` with the CLI.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
Webpack 4.1.0

**Comment by ARDivekar** [comment]
After consulting [the schema](https://github.com/webpack/webpack/blob/master/schemas/WebpackOptions.json), I am able to get it to work using `excludeModules: function(){return false;}`. 

I think `excludeModules: false` should be a supported parameter.

**Comment by sokra** [comment]
Send a PR

**Comment by ARDivekar** [comment]
I'm not familiar with the inner workings of the framework. Could you do it?

**Comment by sokra** [comment]
I could, but I don't have time.

See `lib/Stats.js`

**Comment by byzyk** [comment]
I can have a look into it

**Comment by sokra** [comment]
Allow booleans for `excludeModules`

**Comment by ooflorent** [comment]
Fixed by #6750
