### ISSUE TITLE
optimization.splitChunks.chunks = 'all' has error in node env

### ISSUE THREAD

**Issue by lqzerogg** [webpack/webpack#6727]
**Do you want to request a *feature* or report a *bug*?**
a bug

**What is the current behavior?**
throw error: TypeError: Cannot read property 'call' of undefined
code line: modules[moduleId].call
**If the current behavior is a bug, please provide the steps to reproduce.**
1. add config file:
{
        target: 'node',
        optimization: {
            splitChunks: {
                chunks: 'all',
            },
        },
        module: {
            rules: [
                {
                    test: /\.jsx?$/,
                    exclude: /node_modules/,
                    use: {
                        loader: 'babel-loader',
                    },
                },
            ],
        },
}
2. entry file:
import React from 'react'
import { renderToString } from 'react-dom/server'
export default function() {}
3. compile
4. require compiled file in node

**What is the expected behavior?**
not throw any error
**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
If I remove the config: optimization.splitChunks.chunks = 'all',
it will throw no error. 
So I think the problem is in splitChunkPlugin

**Comment by ooflorent** [comment]
What version of `webpack` are you using?

**Comment by sokra** [comment]
`target: node` doesn't support splitting of initial chunks.

**Comment by lqzerogg** [comment]
webpack 4

**Comment by lqzerogg** [comment]
ok all right. I got it

**Comment by mijay** [comment]
@sokra Is there a conceptual reason why this is option is not supported?
