### ISSUE TITLE
When using --mode development, all newlines are removed

### ISSUE THREAD

**Issue by richayrich** [webpack/webpack#6728]
**Do you want to request a *feature* or report a *bug*?**
Bug report (Webpack 4.1.1).

**What is the current behavior?**
When using `--mode development`, all newlines are removed, and so each file and related import are concatenated into a single line. This obviously makes debugging rather difficult.

This was working fine (no newline removal) in Webpack 3.x.

I am using this config:

```
var path = require("path");
var webpack = require('webpack');
var BundleTracker = require('webpack-bundle-tracker');

module.exports = {
    context: __dirname,

    entry: {
        file1: './www/static/jsx/file1',
        file2: './www/static/jsx/file2',
        file3: './www/static/jsx/file3',
    },

    output: {
        path: path.resolve('./www/static/bundles/'),
        filename: "[name].js"
    },

    plugins: [
        new BundleTracker({ filename: './www/webpack-stats.json' })
    ],

    module: {
        rules: [
            { test: /\.jsx?$/, enforce: "pre", exclude: /node_modules/, loader: 'babel-loader', query: { presets: ['es2015', 'react'] } } // to transform JSX into JS
        ]
    },

    resolve: {
        alias: { Components: path.resolve(__dirname, "./www/static/jsx/components") },
        extensions: ['.js', '.jsx'],
        modules: ['./node_modules']
    }
};
```

**If the current behavior is a bug, please provide the steps to reproduce.**
Use the supplied config, then view the compiled javascript in a browser.

**What is the expected behavior?**
Preserve newlines when using `--mode development`.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

Webpack 4.1.1.
npm 5.7.1

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template.

**Comment by richayrich** [comment]
@montogeek done.

**Comment by sokra** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by richayrich** [comment]
Although the issue remains, the untouched files are actually available under "webpack://" within the Chrome developer tools, so it's not as much of a problem as I originally thought.

**Comment by sokra** [comment]
ah I understand what the problem was. With "newlines removed" you actually mean "the source is stringified". That's the effect for the default devtool. You should not read the bundle, but the sources in the `webpack://` folder. btw. you can disabled this behavior with `devtool: false`
