### ISSUE TITLE
About CSS entrypoint and HTML entrypoint

### ISSUE THREAD

**Issue by zD98** [webpack/webpack#6729]
**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
` Entrypoint undefined = index.html`
and
` Entrypoint undefined = extract-text-webpack-plugin-output-filename`

**If the current behavior is a bug, please provide the steps to reproduce.**
In webpack production mode with HtmlWebpackPlugin and ExtractTextWebpackPlugin

**What is the expected behavior?**
Have no errors

The error does't affect the last output file, but it log lots of info in console. 
Does  the features about `html entrypoint` and `css entrypoint` working in progress throw the error ?

**Comment by zD98** [comment]
[extract-text-webpack-plugin issue](https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/731)
[html-webpack-plugin issue](https://github.com/jantimon/html-webpack-plugin/issues/895)

**Comment by michael-ciniawsky** [comment]
You can't use a `.css` or `.html` file as an entrypoint (yet). It 'works' but will a generate an 'empty' JS File with the webpack wrapper code. `import` the CSS in the JS entrypoint instead and the`html-webpack-plugin` emits the `index.html` (template) on it's own as an asset (no `.html` entry`) needed and it won't pick it up anyways. See #6447 && #6448 for rough attempts to add this functionality in the (near) future, but especially the bare entrypoint support is not done yet :) (Still emits an additional JS File)

**Comment by zD98** [comment]
Thanks. 
Hoever I didn't  use `.css` or `.html`  as an entrypoint. 

Recently, I updated webpack from v3 to v4. The Plugin  `HtmlWebpackPlugin` and `ExtractTextWebpackPlugin` throw the same error. The log info were just like the `js` entry. 

log:  `entrypoint undefined = xxxxxx`

But I have no ideas to solve it and it isn't a realy "error". It just produced much log info. The log info like `entrypoint undefined = xxxx` should be produced by `webpack.`.

So could you give me some suggestions  to solve it ?

**Comment by montogeek** [comment]
Please post your entire stack trace

**Comment by zD98** [comment]
`webpack --config webpack.prod.conf.js`

my webpack config file:
```
   ...
    stats: {
        errors: false,
        errorDetails: false,
        colors: true,
        modules: false,
        children: true, 
        chunks: false,
        chunkModules: false
    },
   ...
```

ExtarctTextWebpackPlugin
```
Child extract-text-webpack-plugin ../node_modules/extract-text-webpack-plugin/dist ../node_modules/css-loader/index.js??ref--9-2!../node_modules/postcss-loader/lib/index.js??ref--9-3!../node_modules/less-loader/dist/cjs.js??ref--9-4!../node_modules/react-list-scroll/dist/index.less:
```
HtmlWebpackPlugin
```
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
```

**Comment by zD98** [comment]
```
    stats: {
        ...
        children: false, 
        ...
    },
```

Setting the property `children` to false will show off the log info.

**Comment by ecanro** [comment]
for the extract-text-webpack-plugin install it like this: 
**npm install -D extract-text-webpack-plugin@next** 
install the beta version, I had the same problem, now it works, but the other html-webpack-plugin still does not let me finish the script and gives error, try to install it with the @next but there is no beta version

**Comment by fqborges** [comment]
I faced the same issue of having a style only entry (css/sass/less) generating an extra .js file, and ended up creating a webpack plugin to remove the js file from the compilation.

I published it on npm as webpack-fix-style-only-entries. You can find the source code on https://github.com/fqborges/webpack-fix-style-only-entries.

:-) shamelessly promoting my package :-)
