### ISSUE TITLE
Misleading doc for ExtractTextPlugin's allChunks option

### ISSUE THREAD

**Issue by dimsmol** [webpack/webpack#673]
[Documentation](http://webpack.github.io/docs/stylesheets.html#separate-css-bundle) says that setting `allChunks=true` will generate single css file for the whole bundle, but in practice it's not true.

With `allChunks=true` we still have one css file per entry but styles are extracted not only from initial chunk of entry but from all entry chunks. It allows to completely remove styles embeded into JS files but still on per entry basis. Without `allChunks=true` styles are extracted from initial chunk only, leaving other styles in JS files.

Documentation of [extract-text-webpack-plugin](https://github.com/webpack/extract-text-webpack-plugin) package itself is a little bit vague according to this. It's says about initial chunk vs all chunks extraction but says nothing about is it per entry or whole bundle extraction.

I think current behavior is fine, but documentation should be updated.

PS Not sure if we really need bundle-level css extraction, but maybe it also should be allowed with an additional option.

**Comment by sokra** [comment]
fixed
