### ISSUE TITLE
splitChunks.minChunks config

### ISSUE THREAD

**Issue by AWSPaul** [webpack/webpack#6730]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I can pass a function to minChunks (Webpack v3.8) which allows me to exclude certain modules from inclusion in vendors.js:
`        minChunks: module => {
          if ((module.context && module.context.indexOf('my-uikit') >= 0) || (module.resource && /^.*\.(css|scss)$/.test(module.resource))) {
            return false;
          }
          if (module.context && module.context.indexOf('server.js') >= 0) {
            return false;
          }
          return /node_modules/.test(module.resource);
        },`

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**
I still want to exclude these modules from vendor.js - with Webpack 4, they are now included. minChunk now only accepts a numerical value.

How can I achieve the same result as with my previous config?

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

**Comment by montogeek** [comment]
Stackoverflow is a better fit for these questions.
Check this about your use case 
https://gist.github.com/sokra/1522d586b8e5c0f5072d7565c2bee693
https://gist.github.com/gricard/e8057f7de1029f9036a990af95c62ba8

**Comment by sokra** [comment]
see `test` option.
