### ISSUE TITLE
Webpack 4 made its own loaders work weird

### ISSUE THREAD

**Issue by FlamesoFF** [webpack/webpack#6731]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
See below.

**If the current behavior is a bug, please provide the steps to reproduce.**
See below.

**What is the expected behavior?**
See below.

**If this is a feature request, what is motivation or use case for changing the behavior?**
No.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
Win 10, Node: v8.9.4, npm: 5.6.0, Webpack: 4.1.1

# Issue Description:
After I updated from webpack `3.8.1` to version `4.1.1` my `raw-loader` started to return an object instead of a string.
Before the update in my AngularJS application I could simply do this:
```
...
template: require('./my-template')
...
```
and everything worked fine. But now I forced to do like this:
```
...
template: require('./my-template').default
...
```
because otherwise variable `template` will be equal an object:
```
{
  default: '<tempate data>'
}
```
instead of a string:
```
'<tempate data>'
```
So what is this cr*p and how to return everything at how it was in webpack 3?

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template.

**Comment by FlamesoFF** [comment]
@montogeek Done.

**Comment by michael-ciniawsky** [comment]
Which version of the `raw-loader` are you currently using ?  `>= v0.5.1 (@latest)`  exports a CJS Module, while `>=1.0.0-beta-0 (@beta)` exports an ES Module. The latter causes to use `.default` in conjunction with `require()`

```js
require('cjs')
require('esm').default
```

**Comment by FlamesoFF** [comment]
@michael-ciniawsky I already know that, captain Obvious. It's still not resolves the problem.
