### ISSUE TITLE
HMR with inline mode breaks in IE11

### ISSUE THREAD

**Issue by aaronrosenthal** [webpack/webpack#6733]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Using `--inline --hot` with `webpack-dev-server` causes HMR to not work with IE11 because IE11 requires a polyfill to implement `includes` for Array objects.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

**Comment by deanshub** [comment]
as you said it seems that the plugin uses es2015 features. for now, our workaround is to add babel-polyfill from the html through cdn which makes the webpack code run after the polyfill...
It'll be great to get a real fix

**Comment by aaronrosenthal** [comment]
Do you know of a way I can configure my project to import my polyfills before the Webpack code from HMR? Currently I have an entry point to polyfills.js (where I import my other polyfills), but it seems that the HMR code gets written at the top of that file.

**Comment by sokra** [comment]
Could you locate the `includes` call and send a PR to replace it with a `indexOf` call. Runtime code emitted by webpack should use only ES5 features.
