### ISSUE TITLE
want to new loader api to skip build or suppress the log

### ISSUE THREAD

**Issue by rchaser53** [webpack/webpack#6734]
**Do you want to request a *feature* or report a *bug*?**
 i want to new loader api to skip build or suppress the log.

**What is the current behavior?**
webpack builds twice with webpack-dev-server and [awesome-prettier-loader](https://github.com/rchaser53/awesome-prettier-loader). now i make new loader [awesome-prettier-loader](https://github.com/rchaser53/awesome-prettier-loader). this loader uses prettier to format the changed file. the performance is not a terrible but the log is very noisy.

**If the current behavior is a bug, please provide the steps to reproduce.**
 1. git clone https://github.com/rchaser53/awesome-prettier-loader.git
 2. yarn install
 3. npm start
 4. change ```src/__tests__/index.js```

**What is the expected behavior?**
skip webpack build or suppress the log. i think webpack-dev-server cannot distinguish the change between the user changes and the prettier changes. so i want to new loader api to skip the build or suppress the log. 

**If this is a feature request, what is motivation or use case for changing the behavior?**
new api is very convinient to use formatter in loader. you may know ```eslint-loader``` with fix option also builds twice. webpack with formatter is a very convinient.  the user  the user just install loader and use webpack only. no need to use formatter.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
Node.js: 9.7.1
webpack: 4.1.1
Operating System: macOS 10.13.3

**Comment by sokra** [comment]
It's not the idea of loaders to rewrite input files. This use case is not supported. Don't use webpack loaders to rewrite files.

Use `npm scripts` or `lint-staged` instead.
