### ISSUE TITLE
Wrong arguments interpretation by CommonsChunkPlugin ctor

### ISSUE THREAD

**Issue by dimsmol** [webpack/webpack#674]
For example, `CommonsChunkPlugin('entry', null, null, Infinity)` seems to erroneously miss `Infinity` argument. There could be more problems as well.

At least it should be fixed to work correctly if all 4 arguments are specified. But in general, it has too messy mix of optional arguments.

Also, you should know "recipes" for combining these args for very different purposes, such as extracting vendor libs or moving common code to parent chunk.

Perhaps it would be better to provide several goal-oriented factories that would hide this complexity under the hood.

**Comment by sokra** [comment]
> But in general, it has too messy mix of optional arguments.

true...

**Comment by sokra** [comment]
You can use `CommonsChunkPlugin('entry', null, Infinity)` as workaround

**Comment by dimsmol** [comment]
yep, I do, thx )
