### ISSUE TITLE
Parser.plugin('call functionName') would break if functionName was declared in the same file

### ISSUE THREAD

**Issue by TylerYang** [webpack/webpack#6740]
**What is the current behavior?**
The callback in `Parser.plugin('call funcName', callback)` would not be invoked if `funcName` was declared in the same file. 

**If the current behavior is a bug, please provide the steps to reproduce.**
Edit `test/Parser.unittest.js`, update the [`call ident`](https://github.com/webpack/webpack/blob/master/test/Parser.unittest.js#L13) test case to the code blew.

```
"call ident": [
  function() {
    function abc() {} // added this line
    abc("test");
  },
  {
    abc: ["test"]
  }
],
```
run `npm run test:unit` , we got the error below.
```
  1) Parser should parse call ident:

      AssertionError: expected Object {} to equal Object { abc: Array [ 'test' ] }
      + expected - actual

      -{}
      +{
      +  "abc": [
      +    "test"
      +  ]
      +}
```

**What is the expected behavior?**
**`npm run test:unit` should run successfully.**

**Comment by sokra** [comment]
The Parser only handles "free-vars". Identifiers declared in scope do not trigger hooks. This is expected.

**Comment by sokra** [comment]
The options in the Parser are limited:

When the identifier is declared with `var/let/const`, you can hook into `varDeclaration` and `return false` to keep it `free`, which would allow to hook into `call` to this identifer.

**Comment by TylerYang** [comment]
Thx, that would be my pleasure to do so. But the case could be quite complex, and we need further discussion for now.
e.g. 
1. What if the declared method got renamed? 
```
function test() {}
var alias = test;
alias();
```
2. What if we have another variable happened to be the same name in the lower scope. 
```
function test() {}
(function () {
    var alias = test;
    test = 'abc';
    alias();
    test = alias;
}())
test();
```
