### ISSUE TITLE
optimization.sideEffects = true causes issues with local CSS

### ISSUE THREAD

**Issue by evan-scott-zocdoc** [webpack/webpack#6741]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When `optimization.sideEffects = true` like in `mode: "production"`, local (not from node_modules) CSS is not added to the chunk and is lost.

**If the current behavior is a bug, please provide the steps to reproduce.**
Don't have one as of yet, but will try and make something.

```json5
// package.json
{
  "name": "project",
  "module": "src/index.js",
  "sideEffects": false
}
```

```js
// src/index.js
import './foo.css';                       // <- this is not preserved
import 'highlight.js/styles/default.css'; // <- this is preserved

// some other stuff
```

```scss
// foo.css
.foo { color: red; }
```

```js
// webpack.config.js

module.export = {
  mode: "production",
  module: {
    rules: [{
      test: /\.css$/,
      use: ['extracted-loader'].concat(
        ExtractTextPlugin.extract({
          fallback: style,
          use: [
            cssLoader,
            postcssLoader,
          ],
        })
      ),
    }]
  }
}
```

**What is the expected behavior?**
CSS should not be tree shaken.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
webpack 4.1.1
node 8.10.0
macOS latest

**Comment by evan-scott-zocdoc** [comment]
I think this has to do with https://github.com/webpack/webpack/issues/6571

**Comment by sokra** [comment]
CSS has a side effect: "adding CSS to the DOM". You can't mark it as side-effect-free. Instead do this:

``` js
"sideEffects": [
  "*.css"
]
```

**Comment by evan-scott-zocdoc** [comment]
Thanks @sokra. That definitely does work, but isn't it confusing? I think more documentation is needed for this feature, I found it surprising that tree shaking would be applied to non-JS.

**Comment by edmorley** [comment]
A mention of the CSS caveat was added to webpack/webpack.js.org#1865 (currently only on the `next` branch and not deployed) - so I think this issue can now be closed?

**Comment by TheLarkInn** [comment]
@evan-scott-zocdoc I just stumbled across this issue again and I didn't know about this API capability here. So yes, I definitely believe that we should have a documentation piece for this. Would you mind creating an issue?

**Comment by VinayakBagaria** [comment]
In the rules section for webpack config, its simple to add a snippet as:
`
{
        test: /\.js$/,
        exclude: <any folder's / file's absolute path>
        sideEffects: false,
     },
`
With excluding *.css, I found an issue with images assets.
