### ISSUE TITLE
Debugging bundle invalidations

### ISSUE THREAD

**Issue by KevinGrandon** [webpack/webpack#6745]
**Do you want to request a *feature* or report a *bug*?**

Feature request.

**What is the current behavior?**

Currently Webpack 4 can invalidate bundles due to unknown causes, and can cause bundle generation to get stuck in an infinite loop.

**If this is a feature request, what is motivation or use case for changing the behavior?**

One problem we have seen while upgrading to webpack 4 is that it's hard to get debug information out of the system. This leads to long and frustrating upgrade processes. A verbose mode would be welcome, or at a minimum for this issue some way to know exactly what caused a bundle to become invalidated. It seems that `compiler.hooks.invalid` is not sufficient enough to tap into, but perhaps there is another option that has not been documented well.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

Node version: 8.10
Webpack: 4.1.1
OS: Mac and Linux

**Comment by Legends** [comment]
Have you tried any of these switches? Especially `--display-error-details`
`webpack --mode development --display-entrypoints --progress --display-modules --display-error-details ....`

**Comment by KevinGrandon** [comment]
I actually don't even get to stats, it just restarts infinitely. Let me see if I can put together a minimal reproducible test case to make this more actionable.

**Comment by KevinGrandon** [comment]
@Legends - Thank you for chiming in here. I've filed #6759 with more information and a repro that reproduces the issue.
