### ISSUE TITLE
Question: has no exported member 'Tapable'

### ISSUE THREAD

**Issue by Legends** [webpack/webpack#6746]
Webpack v4.1.1
Win10 x64

It's actually the TypeScript compiler that is complaining....

I get the below error, when executing `tsc`.
I can see that I have `@types/tapable --> "version": "0.2.5",` installed.

How can I upate this package, it's not part of my webpack.config.js ?!

**node_modules/`@types/tapable`/index"' has no exported member 'Tapable'.**
**node_modules/`@types/tapable`/index"' has no exported member 'HookMap'**
......
..

**Packages.json of tapable package**
```
{
    "name": "@types/tapable",
    "version": "0.2.5",
    "description": "TypeScript definitions for tapable",
    "license": "MIT",
    "contributors": [
        {
            "name": "e-cloud",
            "url": "https://github.com/e-cloud",
            "githubUsername": "e-cloud"
        }
    ],
    "main": "",
    "repository": {
        "type": "git",
        "url": "https://www.github.com/DefinitelyTyped/DefinitelyTyped.git"
    },
    "scripts": {},
    "dependencies": {},
    "typesPublisherContentHash": "48644369fadbc86c2d4e3af19df770580677b68e4022f8821c89b0d746d10b20",
    "typeScriptVersion": "2.0"
}
```

**Comment by sokra** [comment]
File an issue at @types/tapable

**Comment by Legends** [comment]
at?

**Comment by montogeek** [comment]
At Typescript project I guess

**Comment by Legends** [comment]
It looks like `Yarn` is messing things up....

**Comment by BertrandFritsch** [comment]
As a workaround, adding 

```
"resolutions": {
    "@types/tapable": "1.0.0"
  }
```
to package.json to force the use of the latest version works for me.

**Comment by Legends** [comment]
No my installation is messed up, webpack folders are missing.
In my webpack folder I only have a `node_modules` folder..hot, bin, lib, schemas ... are missing.

**Comment by BertrandFritsch** [comment]
@Legends May be I should have added that the package.json file that I have modified is the one of my project and not the one from webpack.

From my understanding of the issue, the problem comes from the `@types/tapable` package.
Version 0.2.5 has been published after version 1.0.0

```
 >> yarn info @types/tapable time
yarn info v1.5.1
{ modified: '2018-03-14T09:05:19.557Z',
  created: '2016-11-03T17:43:33.642Z',
  '0.2.0': '2016-11-03T17:43:33.642Z',
  '0.2.1': '2016-11-10T12:27:58.747Z',
  '0.2.2': '2016-11-30T00:20:40.803Z',
  '0.2.3': '2016-12-23T14:16:33.379Z',
  '0.2.4': '2017-08-21T22:05:18.405Z',
  '1.0.0': '2018-03-10T02:21:13.748Z',
  '0.2.5': '2018-03-10T02:21:17.297Z' }
```
and has been published as the latest version

```
 >> yarn info @types/tapable dist-tags
yarn info v1.5.1
{ latest: '0.2.5',
  'ts2.0': '0.2.4',
  'ts2.1': '0.2.4',
  'ts2.2': '0.2.4',
  'ts2.3': '1.0.0',
  'ts2.4': '1.0.0',
  'ts2.5': '1.0.0',
  'ts2.6': '1.0.0',
  'ts2.7': '1.0.0',
  'ts2.8': '1.0.0' }
```

On the other side, as `@types/webpack` has been configured to always take the latest version in its dependencies

```
    "dependencies": {
        "source-map": "^0.6.0",
        "@types/tapable": "*",
        "@types/uglify-js": "*",
        "@types/node": "*"
    },
```

the wrong version is chosen.

**Comment by Legends** [comment]
I got a bunch of erros even when doing a fresh install.
I have uninstalled node.js and installed the latest LTS version.

Then I got these errors again, error error error the it was suddenly downloading and installing `node-sass`.

Now it works again.


Here a little preview of the errors:


`npm install`

> > ws@0.4.31 install C:\Users\Admin\Documents\Visual Studio 2017\Projects\JM.Demosv4\JM.Web.MVC5_2\node_modules\ws
> > (node-gyp rebuild 2> builderror.log) || (exit 0)
> 
> 
> C:\Users\Admin\Documents\Visual Studio 2017\Projects\JM.Demosv4\JM.Web.MVC5_2\node_modules\ws>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
> Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
>   bufferutil.cc
>   win_delay_load_hook.cc
> C:\Users\Admin\Documents\Visual Studio 2017\Projects\JM.Demosv4\JM.Web.MVC5_2\node_modules\ws\node_modules\nan\nan.h(213): error C2039: 'ThrowException': is not a member of 'v8' (compi
> ling source file ..\src\bufferutil.cc) [C:\Users\Admin\Documents\Visual Studio 2017\Projects\JM.Demosv4\JM.Web.MVC5_2\node_modules\ws\build\bufferutil.vcxproj]
>   C:\Users\Admin\.node-gyp\8.10.0\include\node\v8.h(64): note: see declaration of 'v8' (compiling source file ..\src\bufferutil.cc)
> C:\Users\Admin\Documents\Visual Studio 2017\Projects\JM.Demosv4\JM.Web.MVC5_2\node_modules\ws\node_modules\nan\nan.h(213): error C2039: 'New': is not a member of 'v8::String' (compilin
> g source file ..\src\bufferutil.cc) [C:\Users\Admin\Documents\Visual Studio 2017\Projects\JM.Demosv4\JM.Web.MVC5_2\node_modules\ws\build\bufferutil.vcxproj]
>   C:\Users\Admin\.node-gyp\8.10.0\include\node\v8.h(2453): note: see declaration of 'v8::String' (compiling source file ..\src\bufferutil.cc)
> C:\Users\Admin\Documents\Visual Studio 2017\Projects\JM.Demosv4\JM.Web.MVC5_2\node_modules\ws\node_modules\nan\nan.h(213): error C3861: 'New': identifier not found (compiling source fi
> le ..\src\bufferutil.cc) [C:\Users\Admin\Documents\Visual Studio 2017\Projects\JM.Demosv4\JM.Web.MVC5_2\node_modules\ws\build\bufferutil.vcxproj]
> C:\Users\Admin\Documents\Visual Studio 2017\Projects\JM.Demosv4\JM.Web.MVC5_2\node_modules\ws\node_modules\nan\nan.h(213): error C3861: 'ThrowException': identifier not found (compilin
> g source file ..\src\bufferutil.cc) [C:\Users\Admin\Documents\Visual Studio 2017\Projects\JM.Demosv4\JM.Web.MVC5_2\node_modules\ws\build\bufferutil.vcxproj]
> C:\Users\Admin\Documents\Visual Studio 2017\Projects\JM.Demosv4\JM.Web.MVC5_2\node_modules\ws\node_modules\nan\nan.h(218): error C2039: 'ThrowException': is not a member of 'v8' (compi
> ling source file ..\src\bufferutil.cc) [C:\Users\Admin\Documents\Visual Studio 2017\Projects\JM.Demosv4\JM.Web.MVC5_2\node_modules\ws\build\bufferutil.vcxproj]
>   C:\Users\Admin\.node-gyp\8.10.0\include\node\v8.h(64): note: see declaration of 'v8' (compiling source file ..\src\bufferutil.cc)
> C:\Users\Admin\Documents\Visual Studio 2017\Projects\JM.Demosv4\JM.Web.MVC5_2\node_modules\ws\node_modules\nan\nan.h(218): error C3861: 'ThrowException': identifier not found (compilin
> g source file ..\src\bufferutil.cc) [C:\Users\Admin\Documents\Visual Studio 2017\Projects\JM.Demosv4\JM.Web.MVC5_2\node_modules\ws\build\bufferutil.vcxproj]
> C:\Users\Admin\Documents\Visual Studio 2017\Projects\JM.Demosv4\JM.Web.MVC5_2\node_modules\ws\node_modules\nan\nan.h(222): error C2039: 'New': is not a member of 'v8::String' (compilin
> g source file ..\src\bufferutil.cc) [C:\Users\Admin\Documents\Visual Studio 2017\Projects\JM.Demosv4\JM.Web.MVC5_2\node_modules\ws\build\bufferutil.vcxproj]
>   C:\Users\Admin\.node-gyp\8.10.0\include\node\v8.h(2453): note: see declaration of 'v8::String' (compiling source file ..\src\bufferutil.cc)
> C:\Users\Admin\Documents\Visual Studio 2017\Projects\JM.Demosv4\JM.Web.MVC5_2\node_modules\ws\node_modules\nan\nan.h(222): error C3861: 'New': identifier not found (compiling source fi
> le ..\src\bufferutil.cc) [C:\Users\Admin\Documents\Visual Studio 2017\Projects\JM.Demosv4\JM.Web.MVC5_2\node_modules\ws\build\bufferutil.vcxproj]
> C:\Users\Admin\Documents\Visual Studio 2017\Projects\JM.Demosv4\JM.Web.MVC5_2\node_modules\ws\node_modules\nan\nan.h(224): error C2039: 'New': is not a member of 'v8::String' (compilin
> g source file ..\src\bufferutil.cc) [C:\Users\Admin\Documents\Visual Studio 2017\Projects\JM.Demosv4\JM.Web.MVC5_2\node_modules\ws\build\bufferutil.vcxproj]
>   C:\Users\Admin\.node-gyp\8.10.0\include\node\v8.h(2453): note: see declaration of 'v8::String' (compiling source file ..\src\bufferutil.cc)
> C:\Users\Admin\Documents\Visual Studio 2017\Projects\JM.Demosv4\JM.Web.MVC5_2\node_modules\ws\node_modules\nan\nan.h(224): error C3861: 'New': identifier not found (compiling source fi
> le ..\src\bufferutil.cc) [C:\Users\Admin\Documents\Visual Studio 2017\Projects\JM.Demosv4\JM.Web.MVC5_2\node_modules\ws\build\bufferutil.vcxproj]
> C:\Users\Admin\Documents\Visual Studio 2017\Projects\JM.Demosv4\JM.Web.MVC5_2\node_modules\ws\node_modules\nan\nan.h(224): error C2660: 'v8::Integer::New': function does not take 1 arg
> uments (compiling source file ..\src\bufferutil.cc) [C:\Users\Admin\Documents\Visual Studio 2017\Projects\JM.Demosv4\JM.Web.MVC5_2\node_modules\ws\build\bufferutil.vcxproj]
> C:\Users\Admin\Documents\Visual Studio 2017\Projects\JM.Demosv4\JM.Web.MVC5_2\node_modules\ws\node_modules\nan\nan.h(229): error C2039: 'ThrowException': is not a member of 'v8' (compi
> ling source file ..\src\bufferutil.cc) [C:\Users\Admin\Documents\Visual Studio 2017\Projects\JM.Demosv4\JM.Web.MVC5_2\node_modules\ws\build\bufferutil.vcxproj]
>   C:\Users\Admin\.node-gyp\8.10.0\include\node\v8.h(64): note: see declaration of 'v8' (compiling source file ..\src\bufferutil.cc)
> C:\Users\Admin\Documents\Visual Studio 2017\Projects\JM.Demosv4\JM.Web.MVC5_2\node_modules\ws\node_modules\nan\nan.h(229): error C2039: 'New': is not a member of 'v8::String' (compilin
> g source file ..\src\bufferutil.cc) [C:\Users\Admin\Documents\Visual Studio 2017\Projects\JM.Demosv4\JM.Web.MVC5_2\node_modules\ws\build\bufferutil.vcxproj]
>   C:\Users\Admin\.node-gyp\8.10.0\include\node\v8.h(2453): note: see declaration of 'v8::String' (compiling source file ..\src\bufferutil.cc)
> C:\Users\Admin\Documents\Visual Studio 2017\Projects\JM.Demosv4\JM.Web.MVC5_2\node_modules\ws\node_modules\nan\nan.h(229): error C3861: 'New': identifier not found (compiling source fi
> le ..\src\bufferutil.cc) [C:\Users\Admin\Documents\Visual Studio 2017\Projects\JM.Demosv4\JM.Web.MVC5_2\node_modules\ws\build\bufferutil.vcxproj]
> C:\Users\Admin\Documents\Visual Studio 2017\Projects\JM.Demosv4\JM.Web.MVC5_2\node_modules\ws\node_modules\nan\nan.h(229): error C3861: 'ThrowException': identifier not found (compilin
> g source file ..\src\bufferutil.cc) [C:\Users\Admin\Documents\Visual Studio 2017\Projects\JM.Demosv4\JM.Web.MVC5_2\node_modules\ws\build\bufferutil.vcxproj]
> C:\Users\Admin\Documents\Visual Studio 2017\Projects\JM.Demosv4\JM.Web.MVC5_2\node_modules\ws\node_modules\nan\nan.h(233): error C2039: 'ThrowException': is not a member of 'v8' (compi
> ling source file ..\src\bufferutil.cc) [C:\Users\Admin\Documents\Visual Studio 2017\Projects\JM.Demosv4\JM.Web.MVC5_2\node_modules\ws\build\bufferutil.vcxproj]
>   C:\Users\Admin\.node-gyp\8.10.0\include\node\v8.h(64): note: see declaration of 'v8' (compiling source file ..\src\bufferutil.cc)

**Comment by Legends** [comment]
@BertrandFritsch

Yes adding:

```
"resolutions": {
    "@types/tapable": "1.0.0"
  }
```

to my package.json of my project and hitting:

`yarn install`

worked for me. No errors anymore. Strange, that i am the only one having this issue.
Thanks a lot!

P.S.: So who's fault is it now? :-)

**Comment by BertrandFritsch** [comment]
From my point of view, the culprit is the `@types/tapable` package as the package tagged `latest` is version 0.2.5 whereas it should be 1.0.0

**Comment by belgattitude** [comment]
Same error here, I've added @BertrandFritsch solution:

```
"resolutions": {
    "@types/tapable": "1.0.0"
  }
```
A new error now (using ts2.7):

```
ERROR in [at-loader] ./node_modules/@types/webpack/index.d.ts:541:28 
    TS2507: Type 'typeof "/web/www/mfts/node_modules/@types/tapable/index"' is not a constructor function type.
ERROR in [at-loader] ./node_modules/@types/webpack/index.d.ts:568:42 
    TS2507: Type 'typeof "/web/www/mfts/node_modules/@types/tapable/index"' is not a constructor function type.
ERROR in [at-loader] ./node_modules/@types/webpack/index.d.ts:584:46 
    TS2694: Namespace '"/web/www/mfts/node_modules/@types/tapable/index"' has no exported member 'Plugin'.
ERROR in [at-loader] ./node_modules/@types/webpack/index.d.ts:588:53 
    TS2694: Namespace '"/web/www/mfts/node_modules/@types/tapable/index"' has no exported member 'Plugin'.
```
Looking in  `node_modules/@types/tapable/package.json` I noticed it installed the types for ts2.3...

Just fixed it by adding:
```
  "resolutions": {
    "@types/tapable": "ts2.7"
  },
```

Is there a better alternative  ?

**Comment by swenyang** [comment]
As @BertrandFritsch said, installing `@types/tapable` by `npm i -D @types/tapable@1.0.0` solved the problem.

**Comment by Legends** [comment]
Just one thing I want to mention here:

I did `yarn install` and `@types\tapable` got updated.

In my case doing `npm install` **will not update** the package!

`npm install` is equivalent to `yarn install` right?

**Comment by LKTPD** [comment]
try to add `process.traceDeprecation = true;` in `webpack.config.js`

ref: [https://mutter.monotalk.xyz/posts/c5611095ba5bd8d824b3a76359650141](https://mutter.monotalk.xyz/posts/c5611095ba5bd8d824b3a76359650141)
