### ISSUE TITLE
[Feature] function values for DefinePlugin to execute rather than stringify.

### ISSUE THREAD

**Issue by ronkorving** [webpack/webpack#6749]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

DefinePlugin stringifies values that are functions.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

I wish DefinePlugin would execute the function and use the return value instead.

**If this is a feature request, what is motivation or use case for changing the behavior?**

When running watch or webpack-dev-server, and my injected value changes based on external factors, the watcher won't pick up these changes. For example, in my project I inject an RPC schema into the build. When I change the server's RPC schema, I wish my build would update. I can rebuild when the schema changes using `extra-watch-webpack-plugin`, but what I cannot do is update the injected schema value. It would be very useful if I could pass a function to define plugin sort of like this:

```js
new webpack.DefinePlugin({
  RPC_CONFIG: () => { return JSON.stringify(rpc.getSchema()); }
});
```

I do realize that serializing functions is also an interesting feature to support, but users could always call `.toString()` on their functions themselves. I believe that is not rocket science and can be documented.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

**Comment by sokra** [comment]
This would definitely a great feature, but as this would be a breaking change, I guess we can't change the behavior.

Instead I would encourage you to add new syntax for this feature instead:

``` js
new webpack.DefinePlugin({
  RPC_CONFIG: webpack.DefinePlugin.runtimeValue(
    () => { return JSON.stringify(rpc.getSchema()); },
    [/* list of file dependencies */]
  )
})
```

Send a PR.

**Comment by ronkorving** [comment]
@sokra Fair enough, this would at best be semver-major, but your suggestion works 👍 

Could you explain what you mean by the 2nd argument "list of file dependencies"? What will that do?

**Comment by sokra** [comment]
Each module has a list of dependencies, and is cached until dependencies change. So we need to add the correct dependencies to `module.fileDependencies` to make caching and watching to work correctly.

**Comment by ronkorving** [comment]
After digging and reading a lot of code for a while now, I'm wondering which module's fileDependencies to append to. The DefinePlugin seems to be applied at the full built output, not individual modules. I could be wrong though, I am completely new to the Webpack code base.

Any advice in the right direction would be most appreciated. Alternatively, relevant documentation or if you know of a Webpack 4 plugin that does something similar, I could learn from how that's put together. Thanks.

**Comment by ronkorving** [comment]
After digging and reading a lot of code for a while now, I'm wondering how I find the module whose fileDependencies I need to append to. The DefinePlugin acts on a parser object, which doesn't seem to have a reference to the Module object. Therefore I'm not sure how during the parse and traversal process (where DefinePlugin replaces strings with new values) I can augment someModule.buildInfo.fileDependencies.

Any advice in the right direction would be most appreciated. Alternatively, relevant documentation or if you know of a Webpack 4 plugin that does something similar, I could learn from how that's put together. Thanks.

**Comment by sokra** [comment]
parser.state.module

**Comment by ronkorving** [comment]
I created [a PR](#6793), but I don't consider it done.

**Comment by crazyx13th** [comment]
I hoped that I can use this function for UPDATE variables inside watch mode, but function not called on recompile :-( . not possible? thx!

```
use /webpack/webpack-next.client.js
$db> DefinePlugin.constructor():
[buildNr]: 1
i ｢wds｣: Project is running at http://local....net:80/
i ｢wds｣: webpack output is served from /
$db> DefinePlugin.exec():
$db> myFunction():
$db> DefinePlugin.exec():
$db> myFunction():
$db> DefinePlugin.exec():
$db> myFunction():
i ｢wdm｣: Version: webpack 4.14.0
Built at: 2018-07-06 09:40:31
chunk    {0} assets/css/0.2.1.0.dev-5cae67.css, assets/js/0.2.1.0.dev-5cae67.js, assets/css/0.2.1.0.dev-5cae67.css.map, assets/js/0.2.1.0.dev-5cae67.js.map 436 KiB <{preload}> ={1}= [rendered]
chunk    {1} assets/js/1.2.1.0.dev-5cae67.js, assets/js/1.2.1.0.dev-5cae67.js.map 3.25 MiB <{preload}> ={0}= [rendered] split chunk (cache group: vendors)
chunk {preload} assets/js/preload.2.1.0.dev-5cae67.js, assets/js/preload.2.1.0.dev-5cae67.js.map (preload) 1.02 MiB >{0}< >{1}< [entry] [rendered]
i ｢wdm｣: Compiled successfully.
i ｢wdm｣: Compiling...
[buildNr]: 2
i ｢wdm｣: Version: webpack 4.14.0
Built at: 2018-07-06 09:42:24
chunk    {0} assets/css/0.2.1.0.dev-5cae67.css, assets/js/0.2.1.0.dev-5cae67.js, 0.2ed0116b4e22b244d07d.hot-update.js, assets/css/0.2.1.0.dev-5cae67.css.map, assets/js/0.2.1.0.dev-5cae67.js.map, 0.2ed0116b4e22b244d07d.hot-update.js.map 436 KiB <{preload}> ={1}= [rendered]
chunk    {1} assets/js/1.2.1.0.dev-5cae67.js, assets/js/1.2.1.0.dev-5cae67.js.map 3.25 MiB <{preload}> ={0}= split chunk (cache group: vendors)
chunk {preload} assets/js/preload.2.1.0.dev-5cae67.js, assets/js/preload.2.1.0.dev-5cae67.js.map (preload) 1.02 MiB >{0}< >{1}< [entry] [rendered]
i ｢wdm｣: Compiled successfully.

```
