### ISSUE TITLE
webpack3 on npm

### ISSUE THREAD

**Issue by ghuser** [webpack/webpack#6751]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

I think it's good to mention that on npm there is a webpack3 package: https://www.npmjs.com/package/webpack3 with github link: github.com/webpack/webpack
For people that want to download webpack3 this seems like a meta package. I guess it is not.

**Comment by montogeek** [comment]
We should ask npm to delete it

**Comment by probablyup** [comment]
I filed a ticket 👍

**Comment by ooflorent** [comment]
NPM handled it. Thanks @montogeek 

<img width="720" alt="npm" src="https://user-images.githubusercontent.com/168498/37760128-0bb60610-2db6-11e8-8eda-e0ba82968387.png">

**Comment by montogeek** [comment]
Thanks @ghuser for finding it and let us know :)
