### ISSUE TITLE
modify a chunk in multipage, but all chunk will  be compile

### ISSUE THREAD

**Issue by yiqianglin** [webpack/webpack#6755]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

I am using webpack, 'webpack-dev-middleware', 'webpack-hot-middleware'  to create multipage website, but when i modify one page(one chunk will be compile?), but all chunk rebuild. Every content is not modified after complied, but hotCurrentHash is changed in manifest.js.  All rebuild make compilation get very slow. How can i do?
 
first compile:
![image](https://user-images.githubusercontent.com/15794229/37416403-a4b05b64-27e8-11e8-98eb-c1f6b97febc3.png)
rebuild after i modified one js file in a chunk: (why all chunk compile?)
![image](https://user-images.githubusercontent.com/15794229/37416525-f1a6bb2a-27e8-11e8-8300-ac6874c06522.png)
It will be slower, as i push more chunk in entry.

node: 6.10.2
webpack: ^3.10.0
webpack-dev-middleware: ^2.0.4
webpack-hot-middleware: ^2.21.0

**Comment by yiqianglin** [comment]
dev-server.js
`const devMiddleware = require('webpack-dev-middleware')(compiler, {
  publicPath: webpackConfig.output.publicPath,
  stats: webpackConfig.stats
});

const hotMiddleware = require('webpack-hot-middleware')(compiler, {
  log: false
});

compiler.plugin('compilation', (compilation) => {
  compilation.plugin('html-webpack-plugin-after-emit', (data, cb) => {
    hotMiddleware.publish({ action: 'reload' });
    cb();
  });
});`

webpack.base.config.js:
`module.exports = {
  module: {
    rules: [
      {
          test: /\.vue$/,
          use: 'happypack/loader?id=vue'
      }, 
      {
        test: /\.art$/,
        use: 'happypack/loader?id=artTemplate'
      },
      {
        test: /\.(png|jpe?g|gif)$/,
        use: [
          {
            loader: 'url-loader',
            options: {
              name: isDev ? 'images/[name].[ext]' : 'images/[name].[hash].[ext]',
              limit: 1000,
              // publicPath: process.env.NODE_ENV === 'production' ? `${config.build.assetsPublicPath}/` : `${config.dev.assetsPublicPath}/`
            }
          }
        ]
      },
      {
        test: /\.css$/,
        use: ExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: 'happypack/loader?id=css'
        })
      },
      {
        test: /\.scss$/,
        use: ExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: 'happypack/loader?id=scss'
        })
      },
      {
        test:  /\.(eot|woff|woff2|ttf|svg)(\?\S*)?$/,
        use: [
          {
            loader: 'url-loader',
            options: {
              publicPath: process.env.NODE_ENV === 'production' ? `${config.build.assetsPublicPath}/` : `${config.dev.assetsPublicPath}/`,
              name: isDev ? 'fonts/[name].[ext]' : 'fonts/[name].[hash].[ext]',
              limit: 10000
            }
          }
        ]
      },
      {
        test: /\.js$/,
        use: 'happypack/loader?id=babel',
        exclude: [/node_modules/, path.join(__dirname, '../../src/js/lib/')]
      }
    ]
  },
  externals: {
  },
  resolve: {
    extensions: ['*', '.js', '.vue', '.less', '.css', '.scss'],
    modules: ['node_modules'],
    alias: {
      assets: path.resolve(__dirname, '../htdocs/res/scss'),
      images: path.resolve(__dirname, '../htdocs/res/images'),
      js: path.resolve(__dirname, '../htdocs/res/js'),
      components: path.resolve(__dirname, '../htdocs/components'),
      vue: 'vue/dist/vue.js'
    }
  },
  plugins: [
    new webpack.NoEmitOnErrorsPlugin(),
    new webpack.optimize.CommonsChunkPlugin({
      name: ['polyfill', 'vendor', 'manifest'],
      minChunks: Infinity,
      // children: true,  // chunk非常大
      // async: true
    }),
    new ExtractTextPlugin({
      filename: isDev ? 'css/[name].css' : 'css/[name].[contenthash:8].css',
      allChunks: true
    }),
    new FriendlyErrorsPlugin(),
    new HappyPack({
      id: 'vue',
      threadPool: happyThreadPool,      
      threads: 3,
      loaders: [
        {
          loader: 'vue-loader',
          options: {
            extractCSS: true,
            postcss:  {
              plugins: postcssConfig,
              options: {
                  sourceMap: true
              }
            }
          }
        }
      ],
    }),
    new HappyPack({
      id: 'artTemplate',
      threadPool: happyThreadPool,      
      threads: 3,
      loaders: [
        {
          loader: 'art-template-loader'
        }
      ]
    }),
    new HappyPack({
      id: 'css',
      threadPool: happyThreadPool,      
      threads: 3,
      loaders: [
        {
          loader: 'css-loader',
          options: {
            sourceMap: true,
            importLoaders: 1, // 允许配置css-loader应用于@import资源之前的加载器数量。
            // minimize: true // css压缩
          }
        },
        // {
        //   loader: 'postcss-loader',
        //   // options: {
        //   //   sourceMap: true,
        //   //   ident: 'postcss',
        //   //   plugins: postcssConfig
        //   // }
        // }
      ]
    }),
    new HappyPack({
      id: 'scss',
      threadPool: happyThreadPool,      
      threads: require('os').cpus().length,
      loaders: [
        {
          loader: 'css-loader',
          options: {
            sourceMap: true,
            importLoaders: 2 // 允许配置css-loader应用于@import资源之前的加载器数量。
          }
        },
        // {
        //   loader: 'postcss-loader',
        //   // options: {
        //   //   sourceMap: true,
        //   //   ident: 'postcss',
        //   //   plugins: postcssConfig
        //   // }
        // },
        {
          loader: 'sass-loader'
        }
      ]
    }),
    new HappyPack({
      id: 'babel',
      threadPool: happyThreadPool,      
      threads: 3,
      loaders: [
        {
          loader: 'babel-loader?cacheDirectory'
        }
      ]
    }),

  ],
  profile: true, // boolean
};`


dev  plugin:
`plugins = [
  new webpack.optimize.OccurrenceOrderPlugin(),
  new webpack.NamedChunksPlugin((chunk) => { 
    if (chunk.name) { 
      return chunk.name; 
    } 
    return chunk.mapModules(m => path.relative(m.context, m.request)).join("_"); 
  }),
  new webpack.HotModuleReplacementPlugin(),
  // new webpack.NoErrorsPlugin(),
  new webpack.DefinePlugin({
    'process.env.NODE_ENV': JSON.stringify('development'),
    entries: plugin_entry
  }),
  new CopyWebpackPlugin([
    {
      from: `${__dirname}/../htdocs/res/libs`,
      to: 'libs'
    }
  ]),
  new BundleAnalyzerPlugin(),
  new webpack.DllReferencePlugin({
    // context: path.resolve(__dirname, '../dll'),
    context: __dirname,
    manifest: require('../manifest.json'),
  }),
  new AddAssetHtmlPlugin([{
    filepath: path.resolve(__dirname, '../dll/lib.dll.js'),
    includeSourcemap: false
  }])
];`

**Comment by ooflorent** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.
