### ISSUE TITLE
FlagDependencyUsagePlugin: 'used' of null

### ISSUE THREAD

**Issue by code-chris** [webpack/webpack#6757]
Hi,

this is more a **question** than a *bug report*.

**Current behavior?**
A developer from my team got this exception during compilation today. It is not reproduceable from other devs in the team or on my own machine.
```
node_modules/webpack/lib/FlagDependencyUsagePlugin.js:56
                                        const oldUsed = module.used;
                                                              ^

TypeError: Cannot read property 'used' of null
    at processDependency (node_modules/webpack/lib/FlagDependencyUsagePlugin.js:56:28)
    at depBlock.dependencies.forEach.dep (node_modules/webpack/lib/FlagDependencyUsagePlugin.js:46:43)
    at Array.forEach (native)
...
```

If I understand the plugin code correctly this searches for references of my JavaScript modules in my codebase to optimize the assets. Is it possible to disable this plugin? If yes, how? Are there common mistakes or situations which can produce this behavior?

I completely reinstalled the node_modules folder but the problem still occurs (only on this one machine).

**Steps to reproduce**
- As mentioned above, this is not clearly reproducable, so I can't provide steps for that.

**Expected behavior**
The error doesn't occur

**Relevant infos**
Node 8.9.4
Webpack 3.11.0
Windows 10

Thanks!

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template.

**Comment by montogeek** [comment]
Also, please use Stackoverflow for questions or our Gitter channel https://gitter.im/webpack/webpack

**Comment by code-chris** [comment]
@montogeek I updated the description above, but it does not contain more information than before, cause I don't have more.... ;)

**Comment by code-chris** [comment]
Error is gone. There were strange problems with some node modules. I don't know what happend before...

**Comment by mredbishop** [comment]
@code-chris  We currently get this with the latest webpack 4 and aurelia etc. Have you had it since?

Cheers,

Ed

**Comment by code-chris** [comment]
hey @mredbishop Yes, I figured out, that there was a runtime-dependency missing. Npm had not installed it. So a clean install should maybe help

**Comment by mredbishop** [comment]
We ended up getting round this by adding {aureliaApp: undefined} into the AureliaPlugin for webpack

**Comment by hanyao94** [comment]
> Error is gone. There were strange problems with some node modules. I don't know what happend before...

this error is still  happen in my project,but i don't known how to resolve

**Comment by silbinarywolf** [comment]
@hanyao94 If you manually fix the bug in FlagDependencyUsagePlugin as I did in this PR here, you should get an error message telling you exactly whats wrong.

https://github.com/webpack/webpack/pull/9723

**Comment by sokra** [comment]
This look like a bug in AureliaPlugin, since `module` in `DependencyReference` must not be null in first place.
