### ISSUE TITLE
Webpack-dev-server "e.transport is null" browser error

### ISSUE THREAD

**Issue by dschissler** [webpack/webpack#676]
I'm accessing the webpack-dev-server through an nginx proxy from a local HTTPS connection and I'm receiving the error "e.transport is null" on line 2 column 15229 with `"...tbeatTimeoutTimer=setTimeout(function(){e.transport.onClose()},this.heartbeatTim..."`

Here is my upstream conf:

```
upstream webpack-7002beeb-55e9-434f-8311-f730bc5f4317 {
    server localhost:8090;
}
```

Then inside of the vhost:

```
    location ~ ^/(css|js|fonts)/(.+)$ {
        proxy_pass http://webpack-7002beeb-55e9-434f-8311-f730bc5f4317;
        proxy_redirect off;
        proxy_buffering off;
        rewrite ^/js/webpack-dev-server.js$ /webpack-dev-server.js break;
    }
```

Am I missing something?  My PHP Ratchet forwarding is working correctly.

**Comment by bebraw** [comment]
If this is still relevant, can you re-open this at the [webpack-dev-server repo](https://github.com/webpack/webpack-dev-server/issues)?
