### ISSUE TITLE
Webpack 4.1.1 production (uglified) code throws uncaught error - development OK

### ISSUE THREAD

**Issue by jamesopti** [webpack/webpack#6760]
**Do you want to request a *feature* or report a *bug*?**
Report a *BUG*

**What is the current behavior?**
Uglified code via `mode: 'production'` throws uncaught error
`mode: 'development'` is OK

**If the current behavior is a bug, please provide the steps to reproduce.**

Minimally reproducible repo setup here: https://github.com/jamesopti/uglifyjs-webpack-issue

**What is the expected behavior?**

The code should work the same in development and production.

Webpack version: 4.1.1
React-codemirror version: 1.0.0

I haven't dug into the react-codemirror code to isolate it further (will continue to do that), but even with these uglifyJS options disabled, the issue persists:

*webpack.config.js*
```
optimization: {
    minimizer: [
      new UglifyJsPlugin({
        cache: true,
        parallel: true,
        uglifyOptions: {
          mangle: false,
          keep_classnames: true,
          keep_fnames: true,
        },
      }),
    ]
  }
```

*main.js*
```
import React from 'react';
import { render } from 'react-dom';
import ReactCodeMirror from 'react-codemirror';

// Enables syntax highlighting for javascript
require('codemirror/mode/javascript/javascript');
// Enables linting for javascript
require('codemirror/addon/lint/lint');
require('codemirror/addon/lint/javascript-lint');

window.JSHINT = require('jshint').JSHINT;

const defaultOptions = {
  lint: true,
};

render(
  <ReactCodeMirror
    options={defaultOptions}
    value={'some\ncode'}
  />, document.querySelector('#root')
);
```

*Error screenshot:*
<img width="1273" alt="codemirror_error" src="https://user-images.githubusercontent.com/3718812/37438952-d2bd2162-27b2-11e8-9593-28cdeb184a7d.png">

**Comment by sokra** [comment]
Report it to react-codemirrow

**Comment by kzc** [comment]
Possible dup of #6567

**Comment by quarklemotion** [comment]
This issue does appear to be `uglify-es` related.  Here is a focused view of the problematic pre and post uglified code (from codemirror npm module):
PRE-UGLIFIED
```
function getMaxSeverity(a, b) {
  if (a == "error") return a;
  else return b;
}

maxSeverity = getMaxSeverity(maxSeverity, severity);
```
source refs:
https://github.com/codemirror/CodeMirror/blob/master/addon/lint/lint.js#L96
https://github.com/codemirror/CodeMirror/blob/master/addon/lint/lint.js#L177

POST-UGLIFIED
```
maxSeverity = "error" == (a = maxSeverity) ? a : b,
```
it appears that the uglifier is attempting to inline the getMaxSeverity function, but the second function parameter (`b`) does not get defined in the inlined uglified code, causing an undeclared variable reference.

Based on https://github.com/webpack/webpack/issues/6567#issuecomment-369554250 I tried using that some configuration `uglifyOptions: { compress: { inline: 1 } }` and that resolves the issue WRT codemirror - here is the full working minimizer config:
```
  optimization: {
    minimizer: [
      new UglifyJsPlugin({
        uglifyOptions: {
          compress: {
            inline: 1,
          },
          parallel: true,
        },
      }),
    ]
  }
```

**Comment by jamesopti** [comment]
Confirmed this is an uglify-js issue and opened an issue on uglifyjs-webpack-plugin as such:
https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/265
