### ISSUE TITLE
Ensure that runtime source code stays in ES5

### ISSUE THREAD

**Issue by sokra** [webpack/webpack#6764]
**Do you want to request a *feature* or report a *bug*?**
feature for test infrastructure

**What is the current behavior?**
CI doesn't warn you when using post-ES5 stuff in runtime code.

**If the current behavior is a bug, please provide the steps to reproduce.**
Add > ES5 syntax to `lib/*.runtime.js` or `hot/*`.
CI will allow this change

**What is the expected behavior?**
CI reports error. Maybe a linter error?

**If this is a feature request, what is motivation or use case for changing the behavior?**
No compat regression

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
see also #6739

**Comment by sokra** [comment]
Send a PR

**Comment by Kovensky** [comment]
To add: ideally, this also should check for API usage; IIRC the only post-ES5 API the runtime is allowed to use is `Promise`, but not synchronously, to give a chance for bundled code to polyfill it.

**Comment by montogeek** [comment]
Isn't it enough to run the code against a Node version that doesn't support ES6 features?

**Comment by ooflorent** [comment]
#6775 disallows ES2015+ language features. However, we still need to figure out how to lint the methods (e.g. `Array#includes`, `Object.entries`, …)

**Comment by montogeek** [comment]
@ooflorent I think this is possible via Babel plugin

**Comment by vagusX** [comment]
Have to load babel-polyfill under development when debuggin in some Android phones...
