### ISSUE TITLE
babel-polyfill not shimming Array.prototype.includes

### ISSUE THREAD

**Issue by mkastner** [webpack/webpack#6768]
**Do you want to request a *feature* or report a *bug*?**

Looks like a bug to me. I've tried StackOverflow but didn't get an answer.

**What is the current behavior?**
In Internet Explorer 11 throwing Error

Object does not support property or method "includes"
Original German error message (Das Objekt unterstützt die Eigenschaft oder Methode "includes" nicht);

**If the current behavior is a bug, please provide the steps to reproduce.**

This is the client part of a VueSSR application. Works of course fine on real browsers.

```
module.exports = {
  target: 'web',
  entry: {
    app: ['babel-polyfill', 'picturefill', './src/entry-client1.js']
  },
  output: {
    path: path.resolve('public/dist'),
    publicPath: '/dist
  },
  plugins: {
    new VueSSRClientPlugin()
  }
  /* some other stuff */
}
```

**What is the expected behavior?**

Babel polyfill should be shimming.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

Client Test: Windows 7, Browser IE11 
Build System: Node 9.8.0, Webpack 4.1.1, MacOS

**Comment by montogeek** [comment]
Thanks for your report, unfortunately this is a Babel https://github.com/babel/babel bug, not a webpack one.

**Comment by xtuc** [comment]
Yes that looks like a Babel bug. @mkastner could you please open an issue on https://github.com/babel/babel, please indicate your babel configuration.

**Comment by mkastner** [comment]
You're absolutely right. I'm honestly sorry!!!

**Comment by xtuc** [comment]
no worries, we are happy to help you

**Comment by mkastner** [comment]
I was checking the generated code again:

[https://gist.github.com/mkastner/afdec77bcea9db437be8b3b693cafa3e](https://gist.github.com/mkastner/afdec77bcea9db437be8b3b693cafa3e)

What I noticed was that the error occurs in the webpack-bootstrap section i.e. in

line 112

which is, due to its bootstrapping purpose, being executed before babel-polyfill.

Array.prototype.includes should already be shimmed in bootstrap or it should not be used at all.

**Comment by montogeek** [comment]
@mkastner You are correct, this was already fixed #6739 but haven't been released, also we are planning to implement a CI feature to detect these incompatible changes #6764.

This should be fixed in our next release.

**Comment by montogeek** [comment]
Also, apologies for not debugging the error thoughtfully, next time please post your stack trace

**Comment by mkastner** [comment]
@montogeek Thank you for letting me know. I appreciate that. And apologies for the missing stack trace.
