### ISSUE TITLE
CLI --module-bind + resolve extension

### ISSUE THREAD

**Issue by chenglou** [webpack/webpack#677]
(Related: #503)

More specifically, regarding `--module-bind` and `resolve.extension`: my use-cases are demoing some quick examples of my code so I didn't want to bother with a config file. Passing e.g. `--module-bind 'jsx=jsx-loader'` is really convenient, except this doesn't work because `.jsx` isn't a recognized extension unless it's specified in `resolve.extension` in the config that (which I don't have).

I kinda wish the API for `module.loaders` was designed so that it wouldn't need `resolve.extension`. This way that use-case would work in CLI:

```js
loaders: [
  {extensions: ['jsx'], test: /moreComplicatedTestHere/, loader: 'jsx-loader?harmony'},
]
```

I'm not that familiar with webpack yet so maybe this isn't a good idea; if so, feel free to close this. Anyhow, should I go ahead and put a note on the docs page on [loaders](http://webpack.github.io/docs/using-loaders.html)?

**Comment by sokra** [comment]
fixed by #2696
