### ISSUE TITLE
Webpack ProvidePlugin doesn't apply to webpackBootstrap

### ISSUE THREAD

**Issue by graingert** [webpack/webpack#6770]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
When using ProvidePlugin to define Promise and Object.assign, those values arn't provided to the webpackBootstrap script so it fails in IE11.

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/graingert/webpack-chunking-provide/blob/master/dist/main.js#L80

**What is the expected behavior?**

the ProvidePlugin should overwrite Promise with the given node module.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template.

**Comment by graingert** [comment]
closing in favor of https://github.com/webpack/webpack/issues/3531

**Comment by graingert** [comment]
@montogeek I didn't delete the template...

**Comment by montogeek** [comment]
It was incomplete, sorry
