### ISSUE TITLE
Unnecessary optimisation related warning printed in console when using Redux

### ISSUE THREAD

**Issue by michaeldzjap** [webpack/webpack#6771]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When `concatenateModules` is set to `true` the following warning is printed in the console (despite setting `process.env.NODE_ENV` to `'development'` with `DefinePlugin`:
```
You are currently using minified code outside of NODE_ENV === 'production'. This means that you are running a slower development build of Redux.
```

**If the current behavior is a bug, please provide the steps to reproduce.**
- pass `'development'` as value for process.env.NODE_ENV, i.e.
```javascript
new webpack.DefinePlugin({ 
    'process.env': { 
        NODE_ENV: JSON.stringify('development'), 
    }, 
 })
```
- set `concatenateModules: true` in your _webpack_ config
- import _redux_ in your project

**What is the expected behavior?**
This warning should not be printed in the console.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
webpack: v4.1.1

See #6708 as well. It is addressing the same problem, but it was closed without a resolution. Also see [this](https://github.com/reactjs/redux/issues/2878).

**Comment by montogeek** [comment]
What is your problem exactly? The message is correct, you are not using `production`, therefore Redux prints the message in the console.

**Comment by michaeldzjap** [comment]
I guess I am a little unclear as to what `concatenateModules: true` exactly does internally (so except for what it is supposed to do functionality wise, i.e. safely concatenating segments). Does it do (or is a side effect) any function renaming? Because I suspect the reason this warning is printed is because the `isCrushed()` function from _redux_ is being renamed when `concatenateModules` is set to `true`. This is its source:
```javascript
/*
 * This is a dummy function to check if the function name has been altered by minification.
 * If the function has been minified and NODE_ENV !== 'production', warn the user.
 */
function isCrushed() {}

if (
  process.env.NODE_ENV !== 'production' &&
  typeof isCrushed.name === 'string' &&
  isCrushed.name !== 'isCrushed'
) {
  warning(
    "You are currently using minified code outside of NODE_ENV === 'production'. " +
      'This means that you are running a slower development build of Redux. ' +
      'You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify ' +
      'or DefinePlugin for webpack (http://stackoverflow.com/questions/30030031) ' +
      'to ensure you have the correct code for your production build.'
  )
}
```
I guess setting `concatenateModules` to `true` really only makes sense to do when making a production build anyway, so I guess I can just ignore this setting all together for a development build.

**Comment by montogeek** [comment]
Yes, it is normal for development, it will never be in your production bundle
