### ISSUE TITLE
Block-local variable hides imported function.

### ISSUE THREAD

**Issue by babatakao** [webpack/webpack#6773]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

An imported function cannot be referenced if there is a variable with the same name in the file.
(block-scope seems not respected)

**If the current behavior is a bug, please provide the steps to reproduce.**

I put the example code to https://github.com/babatakao/webpack-import-test.

This example can be executed by the following steps:

```
git clone git@github.com:babatakao/webpack-import-test.git
cd webpack-import-test
npm i
npm run build
node dist/main.js
```

**What is the expected behavior?**

`1` should be shown in the console.

**actual behavior:**

An error occurs:
```
    console.log(foo());
            ^
ReferenceError: foo is not defined
```

**remarks:**

It works well if the "foo" variable in the second "if" block is renamed like:

```diff
diff --git a/main.js b/main.js
index 23f3360..e441e48 100644
--- a/main.js
+++ b/main.js
@@ -7,7 +7,7 @@ function main() {
   }
   if (true) {
     // This "foo" is a block-local variable. Should not affect to the first "if" block.
-    const foo = 2;
+    const foo1 = 2;
   }
 }
```

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

node: v9.2.0
webpack: 4.1.1

**Comment by ooflorent** [comment]
Thanks for your report. I'm closing this issue in favor of #6773.
