### ISSUE TITLE
webpakc4.1.1 chunkhash  is the same

### ISSUE THREAD

**Issue by holdfuture** [webpack/webpack#6774]
I have set the Chunkname of files，after builds ，All the chunkhash of files is the same !!!!

**Comment by holdfuture** [comment]
![1](https://user-images.githubusercontent.com/17507765/37507936-d4d58848-292b-11e8-9cf6-7be2a0c8be4e.png)
![2](https://user-images.githubusercontent.com/17507765/37507940-d8e1000c-292b-11e8-91b9-73b11039accd.png)

**Comment by ooflorent** [comment]
It looks like you just deleted/ignored our [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template. I'm closing this. Please open a new issue with filled issue template.
