### ISSUE TITLE
Tree-shaking of constants not longer works

### ISSUE THREAD

**Issue by duclet** [webpack/webpack#6776]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**

If importing just one constant, the generated bundle still includes all constants even those that are not used. It did not do that before.

**If the current behavior is a bug, please provide the steps to reproduce.**

*constants.js*
export const ONE = 'one';
export const TWO = 'two';

*index.js*
export { ONE } from './constants';

**What is the expected behavior?**

Generated bundle should strip *export const TWO = 'two';*. However, with version 4, it does not. It was correctly stripping in version 3.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

**Comment by probablyup** [comment]
@duclet Are you using the `"sideEffects"` package.json flag? https://github.com/probablyup/webpack.js.org/blob/2f19976a95927ac6a76aeb34db697413ea0e81b1/src/content/guides/tree-shaking.md#mark-the-file-as-side-effect-free

**Comment by sokra** [comment]
Could you create a repo repo for this using production mode?

**Comment by duclet** [comment]
I ended up figuring out the issue. It was from me using TypeScript and forgetting to specify the **"module": "ES6"** option.
