### ISSUE TITLE
Can webpack *not* output to a file but return data?

### ISSUE THREAD

**Issue by ericmorand** [webpack/webpack#6777]
Hi,

I'm currently using Browserify on my custom builder because it doesn't take any responsibility on writing to the filesystem and only return data. It's mandatory to me since my builder will send the bundle to another system that will do whatever he wants with - and my builder don't care.

In the past, I ditched webpack because of this limitation - and I'm still convinced to this day that this is not the purpose of a bundler to write to the filesystem. But maybe things changed and I can now reconsider Webpack.

Any feedback on this?

**Comment by montogeek** [comment]
Yes, use its Node API https://webpack.js.org/api/node/

**Comment by ericmorand** [comment]
Aweome! Thank you very much.
