### ISSUE TITLE
Worker error Error: No code sections found

### ISSUE THREAD

**Issue by wellyshen** [webpack/webpack#6778]
Hi guys, I upgraded to webpack v4 with babel 7. When I use `babelrc: false` option I got the following error on my console and it only occurs in `development`: 

<img width="871" alt="2018-03-17 1 58 17" src="https://user-images.githubusercontent.com/21308003/37536981-226555ec-2987-11e8-9123-285296de02b4.png">

Here's the error snippet of my webpack config:
```javascript
// ...

      {
        test: /\.jsx?$/,
        exclude: /node_modules/,
        loader: 'babel',
        options: {
          cacheDirectory: isDev,
          babelrc: false,  // <== Turn it off will cause the error
          presets: [
            ['@babel/preset-env', { modules: false, useBuiltIns: 'usage' }],
            '@babel/preset-react',
            '@babel/preset-stage-0',
            '@babel/preset-flow'
          ],
          plugins: [
            'react-hot-loader/babel',
            'loadable-components/babel',
            'lodash'
          ],
          env: { production: { plugins: ['transform-remove-console'] } }
        }
      },

// ...
```

Any suggestion for it?

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template.

**Comment by montogeek** [comment]
Also, there is nothing from webpack in that stack trace, submit this issue to `inspectpack` repository.
