### ISSUE TITLE
Add mention of ability to use [chunkhash] in output.filename to documentation

### ISSUE THREAD

**Issue by dimsmol** [webpack/webpack#678]
In practice [chunkhash] can be used as part of output.filename and it's very useful for caching, but [documentation](http://webpack.github.io/docs/configuration.html#output-filename) says nothing about such a possibility.

**Comment by sokra** [comment]
fixed...

Did you know that you can edit the documentation... There is a Edit button in the top right corner.

**Comment by dimsmol** [comment]
> Did you know that you can edit the documentation...

Didn't know, will use, thanks!
