### ISSUE TITLE
No modules built - upgrade from 3.8 to 3.11 / Angular 4.4 to Angular 5.2.9

### ISSUE THREAD

**Issue by ctearpak** [webpack/webpack#6782]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
After making the necessary changes to compile my project, it compiles tiny bundles that don't contain any of my code. All that is loading, and all that is packaged is the initial HTML file. No errors are logged to console

**If the current behavior is a bug, please provide the steps to reproduce.**
Update web pack from 3.8 to 3.11, update Angular 4.4 to Angular 5.2.9. Make changes as recommended by the Angular team between these two versions.

**What is the expected behavior?**
That my page will load with components populated in router outlets and base app module.
That the bundles are > a few KB

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
angular/cli : 1.7.3

**Comment by montogeek** [comment]
Post a repository to test it.
Also please submit all necessary information. Which webpack version are you suing?

**Comment by ctearpak** [comment]
Webpack 3.11.

**Comment by ctearpak** [comment]
Will post a repo when I can strip all of our closed source code out as a demonstration.

**Comment by ctearpak** [comment]
https://github.com/ctearpak/bug-webpack-6782-sample

I expect the content from the Root component in src/app/root/root.component.ts to display in place of the loading screen. The code doesn't even seem to get compiled into the output js files.

**Comment by ctearpak** [comment]
I just kept stripping away stuff vs. the boilerplate code from ng new and determined it was my tsconfig.json file...

noemit: true was the issue.

Not sure why this worked with the older versions I was running, but it breaks on this one.
