### ISSUE TITLE
Dynamic imports are not being removed or transpiled in dead code conditions that leads to nodejs failures because of unknown syntax

### ISSUE THREAD

**Issue by egorvoronov** [webpack/webpack#6786]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
If you have dynamic import statement inside the obvious false condition then webpack doesn't transpile/remove dynamic imports inside the condition.

**If the current behavior is a bug, please provide the steps to reproduce.**
```js
if (false) {
    import('./module1').then(module1 => module1());
}
```
would be transpiled to
```js
/* 0 */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

if (false) {
    import('./module1').then(function (module1) {
        return module1();
    });
}

/***/ })
```
And running this code on server would lead to nodejs failure.

https://github.com/egorvoronov/non_working_defineplugin_dynamic_import/
just do
```bash
npm install; npm run build-dev; node dist/bundle.js
```

**What is the expected behavior?**
Dynamic imports should be still transpiled or the whole obvious false condition should be removed.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
nodejs 8.9.4; webpack3; macOS

**Comment by sokra** [comment]
Fixed in v4
