### ISSUE TITLE
React not able to get the application environment at UI with DefinePlugin?

### ISSUE THREAD

**Issue by VishalGulati** [webpack/webpack#6794]
I am working on a React application. In there I have to showcase different functionality based on whether app is running in dev mode or production. My query is how do I get this application environment in my React code?

I tried below code but it did not work:

    // webpack.config.js
      plugins: [
        new webpack.DefinePlugin({
          appenv: JSON.stringify('dev')
        })
      ]
    // any-component.js
    console.log("Env: " + appenv);
    
    //error
    appenv is not defined.

I also tried `EnvironmentPlugin` of webpack but got same error. Could anyone help? TIA.

CC: @rouzbeh84 @simon04

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template.

**Comment by ooflorent** [comment]
Please reopen this issue with filled issue template.
