### ISSUE TITLE
WARNING in configuration The 'mode' option has not been set. Set 'mode' option to 'development' or 'production' to enable defaults for this environment.

### ISSUE THREAD

**Issue by hwq2017** [webpack/webpack#6795]
How to resolve this error：WARNING in configuration The 'mode' option has not been set. Set 'mode' option to 'development' or 'production' to enable defaults for this environment.

**Comment by evilebottnawi** [comment]
@hwq2017 just use `NODE_ENV=development`(or `production`) or manually set `mode: "development"` (or production) in your `webpack.config.js`
