### ISSUE TITLE
Webpack4 splitChunks 'all' 'initial' -> bundle.js not  working

### ISSUE THREAD

**Issue by KevinGruber** [webpack/webpack#6797]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
As soon as i am defining splitChunks.cacheGroups.[name].chunks: 'initial' or 'all'
the produced bundle is not being executed in the browser -> not working. 
If i define it as 'async' it is working.

**If the current behavior is a bug, please provide the steps to reproduce.**
Configure splitChunks.cacheGroups.[name].chunks: 'initial' or 'all'
It has the same behaviour without cacheGroups when chunks are defined in that way.
 
If it helps you i can send you the produced bundle.

**What is the expected behavior?**
The browser bundle is working normally.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
Node: 8.9.1
webpack: 4.1.1
MacOs: 10.13.3

**Comment by audiolion** [comment]
I am having a similar issue where the bundle is not executing, however if I didn't try `async` mode.

**Comment by sokra** [comment]
Did you include script tags for all initial chunks? With `initial` or `all` it may create additional files that need to be included.

**Comment by KevinGruber** [comment]
Ok now it is working :-)
But it generates that vendor chunk with .saync what is only configured for chunkFilename.
So i was assumeing that it will be loaded by the initial bundle async.

Do i have configuration errors?
Or is there meybe a way to make it clearer what is an initial chunk.

BR,
Kev

**Comment by sokra** [comment]
There is a list of files needed for each entrypoint in the stats.

**Comment by KevinGruber** [comment]
Ok thanks!
But i still think it would be more intuitive if all files use the fileName template instead the chunkFileName template if they are initially required. 

Would that be possible?

**Comment by sokra** [comment]
> Would that be possible?

No. One chunk can be initial for one entrypoint and loaded on demand for another one.

**Comment by Nirazul** [comment]
I'm stuck here as well. I need all entrypoints to be without chunkhash because I need to check in the HTML file that holds the entrypoint script tags.

It seems to work just fine when I'm not using the runtimeChunk. But the moment I'd like to have a runtime chunk, it doesn't seem to be possible anymore to have an entrypoint that is using the filename template (as in webpack 3).

After having invested many hours in trying to implement webpack 4, I'm having a hard time to implement it with the restrictions I'm facing. I guess I'll have to reevaluate, once the documentation has arrived.

**Comment by ooflorent** [comment]
When using `runtimeChunk`, `splitChunks` or hashing, I hardly recommend using `webpack-stats-plugin` or reading the `stats` object:

```js
webpack({
  // Configuration Object
}, (err, stats) => {
  fs.writeFileSync("stats.json", JSON.stringify(stats.toJson()));
});
```

This contains the list of your entrypoints and could be used to generate the `script` tags.

**Comment by rhalaly** [comment]
> There is a list of files needed for each entrypoint in the stats.

@sokra can you point which files should we select? I'm trying to include all the `js` files from `entrypoints > main > assets` and it still not working.

**Comment by TotallWAR** [comment]
@rhalaly as @ooflorent mentioned you can see what files you should load in stats.json. It will be created with `webpack --json > stats.json`. You can find `entrypoints` block there and in field `chunks` of one of your entrypoints will be pointed array of chunks' id you should load. And then you can find chunkname by id you should load.

**Comment by jeron-diovis** [comment]
I don't understand concept at all. 
So webpack automatically extracts common content to chunk files, gives that files unpredictable names (I mean hashes), and does not load them automatically. And we have to generate build profile, parse it, find entries list there and include them manually. 
This doesn't make any sense, or I'm missing something?

**Comment by ReinisV** [comment]
> find entries list there and include them manually.

That's what we use HtmlWebpackPlugin for. It generates an html file that contains `<script src="...">` references for all of the necessary files. Everything happens automatically, it is pretty cool. 

In my case it was not super useful to have a full html index page generated by webpack though, as the HTML for the website is being generated by another frontend server side application, and the JS code that webpack builds is only a small part of it. For this case, HtmlWebpackPlugin allows using custom templates, so you can modify the resulting generated html. Just modify the template so that your main serverside webapp can include the generated webpack html code (the one that contains `<script src="...">` for JS) and you are golden.

**Comment by jeron-diovis** [comment]
@ReinisV Ok, thanks, that might work. 

But, returning to general concept of webpack@4 – is that mean that webpack **requires** you to use HtmlWebpackPlugin now? It looks like this plugin must be a part of webpack itself, if it's the only way to create html without digging into build stats.

**Comment by ReinisV** [comment]
@jeron-diovis if you want to use chunking for all modules not just asynchronous ones (i.e. the `chunks: 'all'` option) and not write your own imports generation logic, then yes, webpack requires you to use HtmlWebpackPlugin. It is not super fortunate in my opinion either, as HtmlWebpackPlugin starts to seem to become abandoned. Last npm release was 7 months ago, and we've been waiting for the official release of v4 for over a year.

**Comment by TheImpressionist** [comment]
I'm having the same issue, where none of the `bundle.js` files get executed at all. However, mine is not a `HtmlWebpackPlugin` issue.

Here's the config

```javascript
module.exports = {
  context: process.cwd(),

  node: {
    __filename: true,
  },

  resolve: {
    extensions: [
      '.tsx',
      '.ts',
      '.js',
      '.jsx',
      '.css',
      '.scss',
    ],
  },

  stats: {
    colors: false,
    hash: true,
    timings: true,
    assets: true,
    chunks: true,
    chunkModules: true,
    modules: true,
    children: true,
  },
  
  entry: {
        editor: ['@babel/polyfill', './src/client/admin/index.tsx'],
        vendor: [
          'react',
          'antd',
          'lodash',
          'mathjs',
          'moment',
          'redux',
          'react-dom',
          'prop-types',
          'react-redux',
          'redux-thunk',
          'redux-logger',
        ],
      };
  
  output: {
    filename: 'js/[name].js',
    path: path.resolve(__dirname, '../', 'dist/static/'),
  },
  
  module: {
    rules: [{
      test: /\.ts(x?)$/,
      exclude: /node_modules/,
      use: [
        {
          loader: 'babel-loader',
        },
        {
          loader: 'ts-loader',
          options: {
            transpileOnly: true,
            logLevel: 'error',
            ignoreDiagnostics: [1039, 2665, 2686]
          }
        },
      ],
    }, {
    test: /\.js(x?)$/,
    exclude: /node_modules/,
    use: [
      {
        loader: 'babel-loader',
      },
    ],
  }, {
    test: /\.(s?)css$/,
    use: [
      !shouldExtractStyles() ? 'style-loader' : MCEP.loader,
      'css-loader',
      {
        loader: 'postcss-loader',
        options: {
          plugins: [
            require('autoprefixer'),
            require('cssnano')({
              zindex: false,
              reduceIdents: false,
            })],
        },
      },
      'sass-loader',
    ],
  }, {
    test: /\.(jpg|png|svg)$/,
    exclude: /node_modules/,
    use: [
      {
        loader: 'file-loader',
        options: {
          name: '[name].[ext]',
          emitFile: true,
          outputPath: process.env.NODE_ENV !== 'development'
            ? '/images'
            : '../',
        },
      },
    ],
  }],
  },
  
  

  optimization: {
    minimizer: [
      new UglifyJSPlugin({
        parallel: true,
        uglifyOptions: {
          compress: {
            // warnings: false,
            dead_code: true,
            drop_console: false,
            // pure_funcs: process.env.NODE_ENV === 'production'
            //   ? ['console.log', 'console.info']
            //   : void 0,
          },
          output: {
            comments: false,
          },
          mangle: true,
        },
      }),
    ],

    runtimeChunk: false,

    splitChunks: {
      name: 'vendor.js',
      cacheGroups: {
        default: false,
        commons: {
          test: /[\\/]node_modules[\\/]/,
          name: 'vendor',
          chunks: 'all',
          minChunks: 2,
        },
      },
    },
};
```

Basically, nothing gets executed at all.
Both, the `vendor.js` and `editor.js` files get loaded by the browser, but the bundle is not executed. And yes, those both bundles are in the HTML as follows:

```html
 <script defer src="<my_cdn>/vendor.js"></script>
 <script defer src="<my_cdn>/editor.js"></script>
```

Funny thing though. It works in the **development** environment and our **staging** environment.
