### ISSUE TITLE
Cannot transpile files from included folder

### ISSUE THREAD

**Issue by renatonmendes** [webpack/webpack#6799]
i´m using a monorepo, where a package is linked to another through symlinks (Lerna and Yarn Workspaces).

Using the react-scripts as based, I need to transpile my shared react component. For that I configured the following script:

```
module.exports = {
  devtool: 'cheap-module-source-map',
  entry: [
    require.resolve('./polyfills'),
    require.resolve('react-dev-utils/webpackHotDevClient'),
    paths.appIndexJs,
  ],
  output: {
    pathinfo: true,
    filename: 'static/js/bundle.js',
    chunkFilename: 'static/js/[name].chunk.js',
    publicPath: publicPath,
    devtoolModuleFilenameTemplate: info =>
      path.resolve(info.absoluteResourcePath).replace(/\\/g, '/'),
  },
  resolve: {
    modules: ['node_modules', paths.appNodeModules].concat(
      process.env.NODE_PATH.split(path.delimiter).filter(Boolean)
    ),
    extensions: ['.web.js', '.mjs', '.js', '.json', '.web.jsx', '.jsx'],
    alias: {
      'react-native': 'react-native-web',
    },
    plugins: [
      new ModuleScopePlugin(paths.appSrc, [paths.appPackageJson]),
    ],
  },
  module: {
    strictExportPresence: true,
    rules: [
      {
        test: /\.(js|jsx|mjs)$/,
        enforce: 'pre',
        use: [
          {
            options: {
              formatter: eslintFormatter,
              eslintPath: require.resolve('eslint'),
              
            },
            loader: require.resolve('eslint-loader'),
          },
        ],
        include: paths.appSrc,
      },
      {
        oneOf: [
          {
            test: [/\.bmp$/, /\.gif$/, /\.jpe?g$/, /\.png$/],
            loader: require.resolve('url-loader'),
            options: {
              limit: 10000,
              name: 'static/media/[name].[hash:8].[ext]',
            },
          },
          {
            test: /\.(js|jsx|mjs)$/,
            include: [
              paths.appSrc,
              path.resolve(paths.lernaNodeModules, '@test\\ux\\src'),
              path.resolve(paths.lernaNodeModules, '@test\\ux\\src\\atoms'),
              path.resolve(paths.lernaNodeModules, '@test\\ux\\src\\atoms\\Footer')
            ],
            loader: require.resolve('babel-loader'),
            options: {
              
              // This is a feature of `babel-loader` for webpack (not Babel itself).
              // It enables caching results in ./node_modules/.cache/babel-loader/
              // directory for faster rebuilds.
              cacheDirectory: true,
            },
          },
          {
            test: /\.css$/,
            use: [
              require.resolve('style-loader'),
              {
                loader: require.resolve('css-loader'),
                options: {
                  importLoaders: 1,
                },
              },
              {
                loader: require.resolve('postcss-loader'),
                options: {
                  ident: 'postcss',
                  plugins: () => [
                    require('postcss-flexbugs-fixes'),
                    autoprefixer({
                      browsers: [
                        '>1%',
                        'last 4 versions',
                        'Firefox ESR',
                        'not ie < 9', // React doesn't support IE8 anyway
                      ],
                      flexbox: 'no-2009',
                    }),
                  ],
                },
              },
            ],
          },
          {
            exclude: [/\.(js|jsx|mjs)$/, /\.html$/, /\.json$/],
            loader: require.resolve('file-loader'),
            options: {
              name: 'static/media/[name].[hash:8].[ext]',
            },
          },
        ],
      },
    ],
  },
  plugins: [
    new InterpolateHtmlPlugin(env.raw),
    new HtmlWebpackPlugin({
      inject: true,
      template: paths.appHtml,
    }),
    new webpack.NamedModulesPlugin(),
    new webpack.DefinePlugin(env.stringified),
    new webpack.HotModuleReplacementPlugin(),
    new CaseSensitivePathsPlugin(),
    new WatchMissingNodeModulesPlugin(paths.appNodeModules),
    new webpack.IgnorePlugin(/^\.\/locale$/, /moment$/),
  ],
  node: {
    dgram: 'empty',
    fs: 'empty',
    net: 'empty',
    tls: 'empty',
    child_process: 'empty',
  },
  performance: {
    hints: false,
  },
};

```

For some reason webpack is not transpiling code that is located in the `include`d links. The `@test//ux` is a symlink crated by monorepo. I tried also the original paths with no success.

Why is webpack not babel transpiling the imported code ?

**Comment by montogeek** [comment]
It looks like you just deleted our lovely crafted [issue template](https://raw.githubusercontent.com/webpack/webpack/master/.github/ISSUE_TEMPLATE.md). It was there for good reasons. Please help us solving your issue by answering the questions asked in this template.

**Comment by renatonmendes** [comment]
Sorry @montogeek  for being relapsed. Here is the template answered:





**Do you want to request a *feature* or report a *bug*?**




**What is the current behavior?**
Webpack is not processing files that comes from included symlinks

**If the current behavior is a bug, please provide the steps to reproduce.**
Download the ZIP and extract in some folder:
[Download Zip File Here](https://github.com/webpack/webpack/files/1826767/test.zip)

The zip requires lerna and yarn installed.

Go to the extracted folder:
```
$ yarn
$ cd packages/cra-app
$ yarn start
```

You are gonna see the SharedComponent not being transpiled.

PS: Yarn start may issue an error on cmd.exe. In that case go to extracted root and create a git repository:
```
$ git init
$ git add .
$ git commit -am "init"

```

Check the added configuration at `packages/cra-apps/config/webpack.config.dev.js`
```
/////////////////////////////////////////////////////////
/// THIS SECTION WAS ADDED TO ORIGINAL create-react-app
/////////////////////////////////////////////////////////
const myIncludePaths = [
  paths.appSrc,
  "C:\\test\\packages\\lib",
  "C:\\test\\packages\\lib\\",
  "C:\\test\\packages\\lib\\src",
];
```
And on babel-loader include (line 155):
  ```
          //include: paths.appSrc,<== oringial
            //
            // THIS WAS CHANGED
            //
            include: myIncludePaths,

```





**What is the expected behavior?**

I expected to lint, transpile and load the SharedComponent.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Not a feature request.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
Chrome 64
Windows 10
Node v6.9.2
Webpack: 3.8.1
Webpack-dev-server: 2.9.4

**Comment by ooflorent** [comment]
You could change your include test to `/@test/` instead of a `path.resolve` call. I do on a private project an it works as expected.

**Comment by renatonmendes** [comment]
@ooflorent , I´ve changed:

          {
            test: /\.(js|jsx|mjs)$/,
            //include: paths.appSrc,<== oringial
            //
            // THIS WAS CHANGED
            //
            //include: myIncludePaths,
			include: /@test/,
            loader: require.resolve('babel-loader'),
            options: {
              
              // This is a feature of `babel-loader` for webpack (not Babel itself).
              // It enables caching results in ./node_modules/.cache/babel-loader/
              // directory for faster rebuilds.
              cacheDirectory: true,
            },
          },

And same error:
```

./src/index.js
Module parse failed: Unexpected token (7:16)
You may need an appropriate loader to handle this file type.
| import registerServiceWorker from './registerServiceWorker';
|
| ReactDOM.render(<App />, document.getElementById('root'));
| registerServiceWorker();
|
```

It does not consider the include, either a path or not.

Please reopen and investigate. I´m stuck with this for some days...

**Comment by ooflorent** [comment]
It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem. Once this is done, feel free to reopen the issue and I'll look further into the issue.

**Comment by renatonmendes** [comment]
If you look at my post there is a minimum reproducible example. Just download the ZIP file and follow the instructions, basically 3 commands:
```
$ yarn
$ cd packages/cra-app
$ yarn start
```

**Comment by ooflorent** [comment]
Okay, I got it working. Instead of defining your babel configuration inside `package.json`, do it like this:

```js
options: {
  cacheDirectory: true,
  presets: [
    "react-app"
  ]
},
```

**Comment by renatonmendes** [comment]
Indeed it worked! What a nightmare. Thanks @ooflorent

**Comment by ooflorent** [comment]
Have you tried after the fix I suggested?

**Comment by renatonmendes** [comment]
Yes, check below: 

```

          // Process JS with Babel.
          {
            test: /\.(js|jsx|mjs)$/,
   	    include: /@test/,
            loader: require.resolve('babel-loader'),
            options: {
              cacheDirectory: true,
              presets: [
                "react-app"
              ]
            },
```

The only thing that works is explicitely setting the paths...

**Comment by johnnycopperstone** [comment]
> You could change your include test to `/@test/` instead of a `path.resolve` call. I do it on a private project an it works as expected.

@ooflorent What's the reasoning behind doing this? I'm curious to understand more about this `/@test/` as I've not come across this yet and not quite sure what it implies
