### ISSUE TITLE
Can we allow multiple module.hot.accept calls in one file?

### ISSUE THREAD

**Issue by gaearon** [webpack/webpack#680]
If I'm using React Hot Loader (which adds `module.hot.accept` at the end), it seems like I can no longer `module.hot.accept` dependencies on my own in the source.

For example, I was trying to add hot-reload for [jss](https://github.com/jsstyles/jss) stylesheets via custom `module.hot.accept` code for a dependency, and it didn't work.

Can we allow several `module.hot.accept` calls in one file? Can't accepting own module & accepting a dependency coexist together?

**Comment by gaearon** [comment]
Actually just allowing several `dispose` handlers to be registered independently would help here.

**Comment by gaearon** [comment]
Sorry, this looks like my bad. Multiple `dispose` handlers work fine.

**Comment by sokra** [comment]
> Can we allow several module.hot.accept calls in one file? Can't accepting own module & accepting a dependency coexist together?

yes, yes

**Comment by sokra** [comment]
> For example, I was trying to add hot-reload for jss stylesheets via custom module.hot.accept code for a dependency, and it didn't work.

Could a jss-loader compile json to css? Than the style-loader would handle the HMR: `style-loader!css-loader!jss-loader`

**Comment by gaearon** [comment]
It can, but the reason it doesn't is to be able to access that JSON from sources. It's similar to style-loader actually, but with plugins & source access.

I think I'm solving this by writing a JSS React mixin with `mixins: [useSheet(json)]` API that refcounts + adding some kind of hook to React Hot Loader to notify class it's being hot-replaced.
