### ISSUE TITLE
Dll bundle outputs is much larger after upgrading to 4.1.1 from 4.1.0

### ISSUE THREAD

**Issue by JounQin** [webpack/webpack#6803]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

After upgrading, the bundle size is about 1.5MB

**If the current behavior is a bug, please provide the steps to reproduce.**

https://github.com/JounQin/Rubick/blob/master/package.json#L161

change webpack version to `4.1.1`, then run `yarn build:dll`

**What is the expected behavior?**

dll bundle is only 188kb on version 4.1.0 .

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

node: 9.8.0
webpack: 4.1.1
OS: macOS 10.13.3

**Comment by bebraw** [comment]
Could it be possible `4.1.1` includes sourcemaps? Maybe one of the fixes caused that to happen.

**Comment by JounQin** [comment]
@bebraw It seems true. All source maps are not removed.

**Comment by bebraw** [comment]
@JounQin That could be a regression. Better wait for Tobias to comment.
