### ISSUE TITLE
obsolete documentation

### ISSUE THREAD

**Issue by iSynth** [webpack/webpack#6805]
**Do you want to request a *feature* or report a *bug*?**

wrong/inconsistent documentation

**What is the current behavior?**

Documentation is not true

**If the current behavior is a bug, please provide the steps to reproduce.**

If you go to the documentation "[Writing a Plugin](https://webpack.js.org/contribute/writing-a-plugin/)" section, then you will see the current webpack version (v4.1.1). But if you follow this documentation, you will finally get the message "Deprecation Warning: Tapable.plugin is deprecated. Use new API on.hooks instead ".

Also, the "event hook" link on this documentation page lead to a 404 error.

**What is the expected behavior?**

The documentation is obsolete and must be updated in accordance with the new requirements.

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

**Comment by michael-ciniawsky** [comment]
https://webpack.js.org/api/plugins/ (seems to be updated)

```diff
- compiler.plugin('hook', cb)

+ const { hook, ... } = compiler.hooks

+ const plugin = { name: 'NamePlugin' }

+ hook.tap(plugin, cb)
```

### `Compiler Hooks`

https://github.com/webpack/webpack/blob/master/lib/Compiler.js#L30-L58

### `Compilation Hooks`

https://github.com/webpack/webpack/blob/master/lib/Compilation.js#L91-L190

Closing as the doc folks a likely to aware of the issue :). Feel free to help them out, even updating a few examples will help them a lot

**Comment by iSynth** [comment]
In this case, please correct the link to the obsolete documentation on page header:

Contribute --> Writing a Plugin.
