### ISSUE TITLE
TypeError: fileTimestamps.get is not a function in NormalModule.js

### ISSUE THREAD

**Issue by sunel** [webpack/webpack#6807]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
```bash
\node_modules\webpack\lib\NormalModule.js:432
const timestamp = fileTimestamps.get(file);
                                     ^
TypeError: fileTimestamps.get is not a function
```

**If the current behavior is a bug, please provide the steps to reproduce.**

This Error occurs while watching for file changes
 `webpack --watch`

**What is the expected behavior?**
Must recompile changed file without error

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

node v9.6.1
webpack 4.1.1
Operating System Windows 10 64bit

**Comment by sokra** [comment]
Looks like multiple different webpack versions installed.

If not:

---

Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by sunel** [comment]
Sorry the issue is with AngularCompilerPlugin its what causing this issue. i think its not compatible with 4.1.1
