### ISSUE TITLE
Absolute path require() for isomorphic apps

### ISSUE THREAD

**Issue by irvinebroque** [webpack/webpack#681]
In node, I can use `npm link myApp` to create symlinks and get fake absolute path require statements like:

`var myModule = require('myApp/dir/myModule')`

Webpack is more flexible, and can do [absolute path require statements](https://github.com/webpack/docs/wiki/resolving#resolving-an-absolute-path), but they're incompatible with node/NPM:

`var myModule = require('/myApp/dir/myModule')` (won't work in node)

This incompatibility makes writing isomorphic apps with hundreds of components hard, because I'm forced to use relative paths that are painful to maintain, like:

`var myModule = require('../../../../myModule')`

Is there a solution that works in **both** a node and webpack environment? Especially one that doesn't force me to put application code inside `node_modules` as a "local module" (the browserify-handbook recommendation)?

Related: #554

**Comment by sokra** [comment]
* There is a deprecated [`NODE_PATH`](http://nodejs.org/api/modules.html#modules_loading_from_the_global_folders) enviroment var for node.js to add module lookup paths
* You can compile your server app (or only the isomorphic part) with `webpack --target node`.
* There is an old [`enhanced-require`](https://github.com/webpack/enhanced-require) which add `resolve.root` option to node.js
* Don't nest your directories so depth
* private npm server

I'm using `webpack --target node`, but feel free to use another approch.

**Comment by jhnns** [comment]
I've written a module called [link-package](https://github.com/peerigon/link-package) which does the symlinking for you. It works quite well with webpack (with implications as discussed in #554)
