### ISSUE TITLE
Target `electron-renderer` should have `browser` in `resolve.mainFields`

### ISSUE THREAD

**Issue by sindresorhus** [webpack/webpack#6811]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

When using `target: 'electron-renderer'`, it doesn't use the browser version of dependencies with a `browser` field in their package.json.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

A renderer process in Electron is just a browser, so it makes sense for it to get browser versions of dependencies, like the `web` target. So when `electron-renderer` is specified as `target`, it `mainFields: ["browser", "module", "main"]` should be set.

https://webpack.js.org/configuration/resolve/#resolve-mainfields

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

Webpack 4.1.1

**Comment by sokra** [comment]
Send a PR
