### ISSUE TITLE
Feature: resolve alias array of directories

### ISSUE THREAD

**Issue by mantissa7** [webpack/webpack#6817]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behaviour?**
Alias accepts single directory path

**What is the expected behaviour?**
Alias accepts array of paths

**If this is a feature request, what is motivation or use case for changing the behaviour?**
I'd like to make use of path bundling to use a library that has a default set of icons, but also allow adding other icons from within the project using the library, but use both from a single source.

Currently:

```js
import { circleIcon } from "@npm_org/Icons/map";
import { extraIcon } from "./icons/map";
```

Ideally: 
```js
alias: {
  "@Icons": [ 
    path.resolve(firstPath),
    path.resolve(secondPath)
  ]
}
```

```js
import { circleIcon, extraIcon } from "@Icons";
```

This could also be used as a fallback per alias i.e. "look here" else "look there", perhaps to fallback to defaults.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

webpack v3.8 but docs for v4 only mention a single string as each alias so nothing relevant seems to have changed between versions

Edit: 
I've just realised i've seen this feature before in TypeScript Module Resolution as `paths`

**Comment by sokra** [comment]
Feel free to send a PR to the AliasPlugin in enhanced-resolve

**Comment by Legends** [comment]
@sokra , @TheLarkInn 

I have code ready for this feature.
Following files need to be changed:

- enhanced-resolve/lib/AliasPlugin.js
- enhanced-resolve/lib/ResolverFactory.js
- webpack/schemas/WebpackOptions.json

Can I run any tests additionally?
And in which branch should the PR go to?

**Comment by Legends** [comment]
I have mistakenly checked out the master branch which v4.
Using `git clone --branch webpack-3 https://github.com/Legends/webpack.git` I have checked out the `webpack-3` branch, but after executing `npm run test` I get the error:

> 9936 passing (7m)
>   125 pending
>   1 failing
> 
>   1) WebWorkerMainTemplatePlugin when applied hot-bootstrap handler when called returns the original source with hot update callback:
> 
>       AssertionError: expected 'moduleSource()\nvar parentHotUpdateCallback = self["webpackHotUpdate"];\nself["webpackHotUpdate"] =

**Comment by Legends** [comment]
@sokra Should this PR go `webpack master` and `enhanced-resolve master`?

**Comment by Legends** [comment]
@mantissa7 

How do you import images like this? Do you use a loader for this to work?

```
import { circleIcon } from "@npm_org/Icons/map";
import { extraIcon } from "./icons/map";
```

**Comment by mantissa7** [comment]
It's loading SVGs using svg-react-loader, and I was using each map as a list of exports to individual files, but since for bundling reasons this is less than ideal, I'd like to be able to do something like 
`import { circleIcon } from "@Icon/circle_icon.svg";`
where `@Icon` could be multiple directories. 

From memory I think Typescript uses something like:
```
paths: {
  "@Icon": [
    "./path/to/category1/*",
    "./path/to/category2/*",
    "./node_modules/to/Icons/*"
  ]
}
```

**Comment by Legends** [comment]
Send a PR

**Comment by alexandrukis** [comment]
Can you tell me why yours was closed? What were the issues with it?

**Comment by lkraav** [comment]
Related https://github.com/webpack/webpack/issues/5348#issuecomment-453708632

**Comment by ohnnyj** [comment]
FWIW, here is a quick crack at adding support for an array of aliases with added tests.

It is kind of hacky to bypass webpacks schema check.

in your config you would have something like:

```
alias: {
  'foo': ['a/foo', 'b/foo'].join(':') // schema needs a string
}
```

and if you want to failover:

```
alias: {
  'foo/index': ['a/foo/index', 'b/foo/index', 'foo/index'].join(':')
}
```

https://github.com/ohnnyj/enhanced-resolve/blob/alias-arrays/lib/AliasPlugin.js

**Comment by zyqshanshui** [comment]
@ohnnyj 

This is a good idea, but how to override AliasPlugin.js without changing webpack/enhanced-resolve in node_modules?

**Comment by ohnnyj** [comment]
@zyqshanshui That I do not know. It was the only way I could find.

I suppose you could create a new plugin which does the same thing but you wouldn't automatically get any fixes / tweaks done to `AliasPlugin`.

**Comment by piglovesyou** [comment]
I sent [a PR](https://github.com/webpack/enhanced-resolve/pull/181) to [webpack/enhanced-resolve](https://github.com/webpack/enhanced-resolve). Later on I'll send another to [webpack/webpack](https://github.com/webpack/webpack) to fix this issue.

Until then, you can use [_early access version_](https://www.npmjs.com/package/@piglovesyou/enhanced-resolve) in your webpack config.




```
npm install @piglovesyou/enhanced-resolve
```

and try

```js
import MultiAliasPlugin from '@piglovesyou/enhanced-resolve/lib/AliasPlugin';

const config = {
  resolve: {
    plugins: [new MultiAliasPlugin('described-resolve', {
      name: '@multi@',
      alias: [ './first', './second', ], // <- What this package supports
    }, 'resolve')],
  }
};
```

**Comment by evilebottnawi** [comment]
bump

**Comment by piglovesyou** [comment]
The official `enhanced-resolve@5.0.0-beta.0` now supports multi-aliasing.

To use it with webpack@4, run

```
yarn add enhanced-resolve@next  # Choose 5.0.0-beta.0 or higher
```

and configure with this syntax.

```js
import AliasPlugin from 'enhanced-resolve/lib/AliasPlugin';

const config = {
  resolve: {
    plugins: [ new AliasPlugin('described-resolve', [
      { name: 'mySingleAlias', alias: '/path/to/alias' },
      { name: 'myMultiAlias', alias: [
        '/path/to/try/first',
        '/path/to/try/second',
        '/path/to/try/last',
      ]},
    ], 'resolve') ],
  },
};
```

From webpack@5, this syntax should work.

```js
const config = {
  resolve: {
    alias: {
      mySingleAlias: '/path/to/alias',
      myMultiAlias: [
        '/path/to/try/first',
        '/path/to/try/second',
        '/path/to/try/last',
      ],
    },
  },
};
```

**Comment by sokra** [comment]
Fixed

**Comment by latel** [comment]
is it possible, if both folder `src/servers/overrides` and `Proto/ProtoCPP/HEAD/Proto` have same file ABC.ts, when I delete `src/servers/overrides/ABC.ts`, webpack auto matically use `Proto/ProtoCPP/HEAD/Proto/ABC.ts`

```javascript
configureWebpack: {
        resolve: {
            plugins: [
                // @see https://github.com/webpack/webpack/issues/6817#issuecomment-542448438
                new AliasPlugin(
                    'described-resolve',
                    [
                        {
                            name: '%',
                            alias: [resolve('src/servers/overrides'), resolve('Proto/ProtoCPP/HEAD/Proto')],
                        },
                    ],
                    'resolve'
                ),
            ],
        },
    },
```

currently when I delete `src/servers/overrides/ABC.ts`, webpack throws ENOENT errors like this
![image](https://user-images.githubusercontent.com/5621862/227145261-1e2ee50b-8b53-407f-81e7-f436e30eb77c.png)
