### ISSUE TITLE
Cannot enable minification when in development mode

### ISSUE THREAD

**Issue by jamesopti** [webpack/webpack#6820]
Per the **webpack4: mode and optimization** [blog post](https://medium.com/webpack/webpack-4-mode-and-optimization-5423a6bc597a), the production & development modes are intended to setup reasonable defaults, but allow overriding configuration.

A unit testing environment seems to be one of those reasonable in between states of development and production, where I want to do some production things, such as code uglification, but not all.

Is there a suggested configuration for testing?

**Do you want to request a *feature* or report a *bug*?**
BUG

**What is the current behavior?**
When mode is set to `development`, `optimization.minimizer` is ignored.
My use case is running tests via karma in development mode with uglified code.

**Config:**
```javascript
webpackConfig.mode = 'production';
webpackConfig.optimization = {
    minimize: true,
    minimizer: [
      new UglifyJsPlugin({
        exclude: /(?:\/tests\/|tests\.js)/,
        uglifyOptions: {
          compress: {
            inline: 1,
            keep_classnames: true,
            keep_fnames: true,
          },
          mangle: {
            keep_fnames: true,
          },
        },
      }),
    ],
}
```

**If the current behavior is a bug, please provide the steps to reproduce.**

Setup a project where 
```javascript
mode: development,
optimization: {
  minimize: true,
  minimizer: [new UglifyJsPlugin()]
}
```

**What is the expected behavior?**
The build code is uglified using the UglifyJs Plugin

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
Webpack v4.1.1
Node v6.10.2

**Comment by jamesopti** [comment]
@sokra Thanks for pointing that out! Did I miss that in the documentation somewhere?

Development mode does appear to be minimizing now, but the output is different (dramatically larger) than with the exact same configuration using production mode:


mode: production
```
                                       Asset      Size  Chunks                    Chunk Names
                                   vendor.js   542 KiB       0  [emitted]  [big]  vendor
                               firstparty.js   873 KiB       1  [emitted]  [big]  firstparty
                /bundles/x/tests/unit/main.js  84.4 KiB      2  [emitted]         /bundles/x/tests/unit/main.js
```

mode: development
```
                                       Asset      Size                                        Chunks                    Chunk Names
                               firstparty.js   1.1 MiB                                    firstparty  [emitted]  [big]  firstparty
                /bundles/x/tests/unit/main.js  93.8 KiB  src/js/bundles/p13n_inner/tests/unit/main.js  [emitted]         /bundles/x/tests/unit/main.js
                                   vendor.js   736 KiB                                        vendor  [emitted]  [big]  vendor
```

**Comment by sokra** [comment]
Read this to see what's the difference between production and development mode: https://medium.com/webpack/webpack-4-mode-and-optimization-5423a6bc597a
