### ISSUE TITLE
feedback request: simultaneously emitting multiple ES targets

### ISSUE THREAD

**Issue by DanielSchaffer** [webpack/webpack#6822]
**Do you want to request a *feature* or report a *bug*?** 

Feature

**What is the current behavior?** 

Can only target a single "profile" per compilation

**What is the expected behavior?** 

Allow emitting multiple "profiles" from a single compilation

**If this is a feature request, what is motivation or use case for changing the behavior?** 

It is currently possible to target both modern browsers that support ES2015 and legacy browsers by making use of `<script type="module">` and `<script nomodule>`, respectively. (see https://philipwalton.com/articles/deploying-es2015-code-in-production-today/) However, generating both bundles requires a cumbersome process of creating multiple compilations with the only difference being the settings for Babel.

I've created a plugin that seeks to provide an easier way to do this: https://github.com/DanielSchaffer/webpack-babel-multi-target-plugin/tree/feature/webpack4 (current changes are on the `feature/webpack4` branch)

It works by overriding the built-in entry option handling and internally generating multiple entries for each browser "target", and then also updating dependencies with those targets as the graph is loaded.

I'd love to get some feedback on how I implemented this feature, as this is my first webpack plugin. I'd specifically be interested in any potential side effects of doing what it does, or situations where it wouldn't work at all. Currently, it works as intended with Angular 5, including routing with lazy routes.

My apologies if this is not the right venue for asking for feedback like this - nobody responded in Gitter or on Twitter. If there's a better place to ask, please let me know.

**Comment by sokra** [comment]
> However, generating both bundles requires a cumbersome process of creating multiple compilations with the only difference being the settings for Babel.

Why is this cumbersome?

``` js
// webpack.config.js
module.exports = [
  { /* babel options for legacy */ },
  { /* babel options for modern */ }
].map(babelOptions => ({
  entry: ...,
  // other options
  module: {
    rules: [
      { // babel
        options: babelOptions
      }
    ]
  }
}));
```

**Comment by DanielSchaffer** [comment]
Perhaps "cumbersome" is a bit of a strong word ... 

I started down this path because I wanted to end up with a complete package including an HTML file that correctly referenced both bundles (the "modern" bundle with `<script type="module">` and the "legacy" bundle with `<script nomodule>`), which HtmlWebpackPlugin can't do with multiple compilations.
