### ISSUE TITLE
regression in 4.2 after "Prevent webpack from running twice at a time" merged

### ISSUE THREAD

**Issue by Alexander-Taran** [webpack/webpack#6825]
**I want to  report a *bug*?**

**What is the current behavior?**

webpack-dev-server --lazy is now broken

**If the current behavior is a bug, please provide the steps to reproduce.**

Run `dev-server with --lazy --open` or add the same flag it to `webpack.config.js`
Looks like a breaking change.

**What is the expected behavior?**
Bundles compiled on page request without exceptions thrown.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
After this pull request was merged
https://github.com/webpack/webpack/pull/6691

a new issue was reported for aurelia-cli, which does use lazy option by default
https://github.com/aurelia/cli/issues/852

No two compilers are used explicitly.

Trying to run dev server with the same options from command line produces the same result.

**Comment by sokra** [comment]
We need to add a new hook `afterDone`, which is called after the callback.

The webpack-dev-middleware can use this hook to figure out when the compilation has finished.

The `done` hook is not usable for this, because it's async and it could still take a while until the compilation has really finished.

**Comment by jardakotesovec** [comment]
Getting this error with webpack-dev-middleware. Is there currently some workaround?

**Comment by Alexander-Taran** [comment]
@arkadyt 
So far I failed to create a minimal repro, but the issue still there with the latest webpack.
So attaching a big repro 
[wp-repro.zip](https://github.com/webpack/webpack/files/2153257/wp-repro.zip)

**Comment by evilebottnawi** [comment]
If you still have problem, please reopen issue in webpack-dev-server, thanks
Looks like you have error in done hook, we have issue about this
