### ISSUE TITLE
[Proposal] Production entry hints

### ISSUE THREAD

**Issue by probablyup** [webpack/webpack#6828]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
When bundling for production, the same entry files are used when a more optimized flat build or entry may be available.

**If this is a feature request, what is motivation or use case for changing the behavior?**
Library authors generally try to provide a good experience for end developers by making their code available in a number of formats and configurations. There's a good amount of flexibility in the current resolution algorithm (browser, module, main fields), but the current suite of offerings only handles non-production use cases.

In particular, the current way of doing things has shortcomings when it comes to newer webpack features like module concatenation. An author may be able to provide a fully-realized ESM production build, but today must use a pattern like this:

```js
if (process.env.NODE_ENV === 'production') {
  module.exports = require('./production.js');
} else {
  module.exports = require('./development.js');
}
```

Due to the use of cjs `require`, it will cause a module concatenation deopt and limit the amount of bundling optimization possible.

I propose automatically adding an extension to the resolution algorithm that allows a package author to specify a different entry file for production builds (e.g. `config.mode === 'production'`.) There are two potential ways this could be implemented.

> Before I go into more detail, when I refer to a "production build" I mean any case where `config.mode === 'production'` or `config.optimize.nodeEnv === 'production'`.

### `*:production` entry hints

webpack natively supports a number of entry hints like "browser", "module", and "main" for various build environments and targets. We can piggyback off this established model and automatically add production equivalents that will be used performing a production build.

They'd look like this (naming TBD):

```
module:production
main:production
```

If the production variant field is not used by the package, it is skipped and the normal entry hint is used.

An example with the _styled-components_ project:

```json
{
    "name": "styled-components",
    "main:production": "dist/styled-components.browser.cjs.min.js",
    "main": "dist/styled-components.browser.cjs.js",
    "module:production": "dist/styled-components.browser.es.min.js",
    "module": "dist/styled-components.browser.es.js"
}
```

Proposed implementation: https://github.com/webpack/webpack/pull/6763

**Comment by probablyup** [comment]
cc @guybedford @devongovett @nchanged @goto-bus-stop

What do you think of this general idea? Granted module concat is a webpack-specific feature, but the rest should be universally-applicable.

**Comment by guybedford** [comment]
@probablyup in general I'm for this, but compositions get hard here (eg browser + production, node + production).

I've been working on a similar proposal to this attempting to deal with the composition problem too at - https://gist.github.com/guybedford/1faf00cf900ba8540e2362cbdefe0a90. Where `production` and `dev` would similarly be considered part of this, and environments can defined their own conditional names above and beyond the simple ones.

Perhaps there's a middle ground to be found.

**Comment by probablyup** [comment]
@sokra @TheLarkInn I'd really like to move forward with this proposal and land it. Is there any reason why we can't add it as an experiment and see if it catches on? This is particularly necessary for ESM bundling without having to write a ton of aliases.

**Comment by probablyup** [comment]
> in general I'm for this, but compositions get hard here (eg browser + production, node + production).

Here's what a fully functioning setup would look like for styled-components:

```
  "main": "dist/styled-components.cjs.js",
  "main:production": "dist/styled-components.cjs.min.js",
  "module": "dist/styled-components.esm.js",
  "module:production": "dist/styled-components.esm.min.js",
  "react-native": "native/dist/styled-components.native.cjs.js",
  "browser": {
    "./dist/styled-components.esm.js": "./dist/styled-components.browser.esm.js",
    "./dist/styled-components.esm.min.js": "./dist/styled-components.browser.esm.min.js",
    "./dist/styled-components.cjs.js": "./dist/styled-components.browser.cjs.js",
    "./dist/styled-components.cjs.min.js": "./dist/styled-components.browser.cjs.min.js"
  },
```

Note that the production hints are used to specify the appropriate variants and then the browser object style maps on top of that to alias the production version of the browser bundle.

**Comment by merrywhether** [comment]
It seems like this would work nicely with Node's upcoming conditional exports: https://nodejs.org/api/esm.html#esm_conditional_exports
