### ISSUE TITLE
Need better standards for plugins and loaders. Documentation needs drastic improvement

### ISSUE THREAD

**Issue by janswee** [webpack/webpack#6829]
I don't know if this post belongs here but I would appreciate if you don't close this issue right away to see if others share in my frustration. I am a true newbie and there is a lack of good documentation or standards for the webpack ecosystem. To make matters worse, the proliferation of plugins and loaders without standards is causing confusion. 

Please consider recommending certain style guidelines before sponsoring or supporting plugins or loaders.

Few examples: 

1) Unnecessary plugins creates saturation in webpack development. If a new plugin is created, it should be peer reviewed and determined if it belongs in the webpack ecosystem before recommending it to users: e.g. The need for clean-webpack-plugin vs. rimraf which already exists.

2) Poorly named plugins. I can't think of a good reason why extract-text-webpack-plugin should be named as such since it boils down as the defacto CSS bundler and should be named as such.

3) Precedence of operations in the webpack build process is not clear. Its not even mentioned in the docs. For example, it was surprising to learn that style-loader must load after css-loader.

https://medium.com/a-beginners-guide-for-webpack-2/webpack-loaders-css-and-sass-2cc0079b5b3a

Thanks for listening and I hope this helps someone else.

**Comment by ooflorent** [comment]
First of all, **please do not delete the issue template**. I'm okay having this conversation here but this is not the place to discuss about the documentation or the ecosystem. It would have been better suited on `webpack/webpack.js.org` repository.

1. That's something we don't have control on. If someone creates a new plugin or a new loader, we can't stop them from doing it. This person probably has a good reason doing so. `clean-webpack-plugin` has a legitimate use for example. If you run a build in watch mode (not talking about the dev server) you may need to remove the assets between each rebuild. That's not possible using `rimraf`.

2. Regarding _Poorly named plugins_, webpack can't do anything about it. If you want to publish a plugin named `pizza-cat-css-webpack-plugin`, I cannot prevent you from publishing it on NPM or telling you that someone already created a plugin called `cat-pizza-css-webpack-plugin`. The ecosystem is too vast to be monitored. Each plugin/loader author should do some legwork before creating something new.

    `extract-text-webpack-plugin` is advertised as a way to _extract_ CSS from your bundle. However if look closing at the source code, you'll find **there is no reference to CSS** in the `src/` folder. The reason is simple: this plugin is not dedicated to CSS processing! CSS is only the most obvious use-case. One could use it to extract all JSON files from a bundle. Hence the naming.

3. The order is the one enforced by _composition_ in FP. `[style, css, less]` should be interpreted as `style(css(less(source)))`. **That's something mentioned in the documentation in the [`Rule.use` section](https://webpack.js.org/configuration/module/#rule-use)**.

I admit that our discussion is far from perfect but we do our best to improve it. We have a [dedicated repository](https://github.com/webpack/webpack.js.org) for it and I encourage you to expose your concerns there and to submit pull requests to add what you think is missing!

**Comment by montogeek** [comment]
1. That is how the ecosystem works, this is not a close webpack ecosystem, it is completely open, anybody can and will create plugins for their needs. Users should test and judge thoughtfully which libraries or plugins install in their applications.

2. `extract-text-webpack-plugin` readme clearly states:
> Extract text from a bundle, or bundles, into a separate file.

CSS extraction is just an example of all endless possibilities. We could add different examples, like extracting JSON files.

3. Those loaders readme says:
css-loader
> The css-loader interprets @import and url() like import/require() and will resolve them.

It is also necessary to make webpack understand CSS files, it doesn't by default, yet (https://github.com/webpack/webpack/pull/6448).

style-loader
> Adds CSS to the DOM by injecting a <style> tag

Meaning that it will take your CSS (previously processed by `css-loader`) and put it into your actual DOM.

If something is not completely clear send a PR, we will be happy to merge it.

**Comment by janswee** [comment]
Thanks, I can leave same feedback for webpack/webpack.js.org repository. We can close this here.
