### ISSUE TITLE
Webpack master - npm run test

### ISSUE THREAD

**Issue by Legends** [webpack/webpack#6830]
Not sure, if this is the right place for this question, if not, I am open to any advice.

I cloned the webpack master branch, `yarn install` and executed `npm run test`.
But I get the below error.

Any hints what might be missing here?

> > mocha test/*.lint.js --opts test/lint-mocha.opts
> 
>   1016 passing (198ms)
> 
> 
> > webpack@4.2.0 test C:\Users\Admin\Downloads\webpack
> > mocha test/*.test.js test/*.unittest.js --max-old-space-size=4096 --harmony --trace-deprecation
> 
> module.js:549
>     throw err;
>     ^
> 
> Error: Cannot find module 'webpack/lib/RequestShortener'
>     at Function.Module._resolveFilename (module.js:547:15)
>     at Function.Module._load (module.js:474:25)
>     at Module.require (module.js:596:17)

**Comment by ooflorent** [comment]
I think you forgot to run these commands:

```
yarn link
yarn link webpack
```

**Comment by Legends** [comment]
Yup, that was missing, thanks.

**Comment by montogeek** [comment]
I did the same first time I clone it, we should automate it.
It is written in the Contributors guide but it would be great to just work out of the box :)

**Comment by Legends** [comment]
What are we waiting for?

**Comment by ooflorent** [comment]
In order to automate it we must have some kind of _bootstrapping_ command which would be documented in `CONTRIBUTING.md`. Currently the setup instructions are also in this file. The issue is the discoverability of this file, not the commands.

**Comment by Legends** [comment]
Yes reading the `Contributing.md` would have been helpful.
The problem is the visibility or people not reading it, like me.
Perhaps, it would make sense to extract the setup part from `Contributing.md`  and put into a separate MD file, like `*****SETUP****.md`, to increase visibility.

Automating it and documenting the bootstrap command in `Contributing.md` wouldn't change anything.

This would be my opinion about this.

**Comment by TheLarkInn** [comment]
Would you like to submit a PR for this. 

We can leave the existing setup content but then also add another *****SETUP****.md file and link to it from the contributing section.

Thanks!!

**Comment by Legends** [comment]
I will. And in the meantime, I will take a look at how to bootstrap it.

**Comment by Legends** [comment]
@ooflorent , @montogeek 

I would like you to have a look on this little setup script I have created (initial approach).
Any suggestions, issues?

**Let me explain what the script does:**
As it seems, that `yarn` is the preferred package manger here, I first check if it is installed.
If not `npm` will be used. I didn't want to force the user to install `yarn`.
Then the setup is executed using `require('child_process').exec`.
Finally I check if a `symlink ` has been created for the `webpack` folder.

For sure, there are myriad of packages available that do this, but I wanted a simple solution.

**package.json**
```
scripts:{
      "setup" : "node ./setup/setup.js"
```

And would be executed using: `npm run setup`

**./setup/setup.js**
```
#!/usr/bin/env node

class Setup {

	constructor() {
		this.fs = require('fs')
		this.path = require('path')
		this.exec = require('child_process').exec;
		this.wpfolder = this.path.join(__dirname, "../node_modules/webpack/");
		this.exists = this.fs.existsSync(this.wpfolder);
		this.hasYarn = false;
	}

	run() {
		console.log("Setup starts ...");

		this.checkYarnInstalledAsync().then(() => {
			return this.runSetupAsync();
		}).catch((e) => {
			console.error(error)
		}).then((msg) => {
			console.log(msg);
			if(!this.checkSymlinkExistsSync()) {
				console.error("Setup failed to establish symlink for webpack");
			} else {
				console.log("Setup has completed successfully");
			}
		}).catch((e) => {
			console.error(e)
		});
	}

	runSetupAsync() {
		return new Promise((resolve, reject) => {
			try {
				const pm = this.hasYarn ? "yarn" : "npm";
				var cmdSetup = this.exec(`${pm} install && ${pm} link && ${pm} link webpack`,
					(error, stdout, stderr) => {
						if(error) {
							reject(error);
						} else {
							resolve(stdout);
						}
					});
			} catch(e) {
				reject(e);
			}
		});
	}

	checkYarnInstalledAsync() {
		return new Promise((resolve, reject) => {
			try {
				var semverPattern = /^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$/

				this.exec("yarn -v", (error, stdout, stderr) => {
					if(error) {
						reject(error);
					} else {
						this.hasYarn = semverPattern.test(stdout.trim());
						resolve(this.hasYarn);
					}
				});
			} catch(error) {
				reject(error);
			}
		});
	}

	checkSymlinkExistsSync() {
		return this.fs.existsSync(this.wpfolder) && this.fs.lstatSync(this.wpfolder);
	}
}

new Setup().run();
```

**Comment by montogeek** [comment]
Original PR (https://github.com/webpack/webpack/pull/3125) used `yarn`. There was an objection about yarn.lock but it was merge anyway.

There is an inconsistency problem with webpack repositories, some have yarn.lock but their `scripts` uses npm, meaning that they are using `npm` as a task runner and nothing more, that is the case of this repository, `webpack.js.org`, `webpack-sources`, `tapable` and others.

`webpack-cli` is using exclusively `npm`.

We should make this consistency and use or another exclusively.

You could argue against using `yarn` because it is not installed by default with Node and that would make us lost contributors.

Any ideas about this @TheLarkInn @ooflorent ?

**Comment by montogeek** [comment]
@Legends About your script, you could simplify it by just using functions.
My idea about automatizing it, is that dev would just run `yarn test` and it would work without any additional commands. We could add your script to `test` script: `"test":"yarn setup && yarn test"`, this means your script should return exit codes accordingly.

**Comment by Legends** [comment]
Regarding `yarn`, imo it is more reliable than `npm`, means: sometimes I get errors with `npm`, retry it with `yarn` and it works.
Which exit codes does webpack use, is there a reference list? O r just `0` and `1`, `passed` and `failed`?

Do you really want to execute the `setup` script on every test run?
If yes, then I have to modify the code a bit to check if a `webpack symlink` already exists, it's a one-liner.

Thanks for your feedback!

**Comment by montogeek** [comment]
It would exit early successfully if it is already linked.
You can see https://nodejs.org/api/process.html#process_process_exit_code for exit codes, that script is outside webpack, is like any script in any language executed in bash (http://tldp.org/LDP/abs/html/exitcodes.html)

That is what I know from my limited experience, I guess exit codes have their root in linux process management.

**Comment by TheLarkInn** [comment]
> Regarding yarn, imo it is more reliable


Our experience has been exactly this so far. I'm not sure what kind of problems that poses, but I've been a large proponent of yarn since day one in addition to build speed.

**Comment by montogeek** [comment]
@TheLarkInn `yarn build` you mean?

**Comment by Legends** [comment]
Ok, we now just have to agree how we want to proceed, therefore I will ask the following questions:

1. Should the setup script install `yarn` if yarn is not installed already? As I can see, all commands in `scripts` use `npm`. If we agree on "devs should use yarn", we should change all commands/tasks under `scripts` to use `yarn`, to make it consistent?
2. Should the setup script be executed on `yarn test`?
4. How is this going to be tested cross-platform and by whom?

**Comment by Legends** [comment]
[Same issue here](https://github.com/webpack/webpack/issues/6851)

**Comment by Legends** [comment]
@TheLarkInn 

I will make another PR for the bootstrap stuff.

I want to propose a change. On Windows I cannot use `*` in file names, so I will use `_` instead, which pushes the file to the top of all files in this folder.

For example under folder `test` I found this `README.md` hidden between `*.js` files. I would expect it to be on top.
In total we currently have 96 `.md` files in the repository. Most of them, should be renamed to `_xxxx.md` to shift them to the top of the respective folder and update all the cross-links adequately.

![image](https://user-images.githubusercontent.com/966368/37864986-5ac01842-2f76-11e8-8759-c50c764e26ce.png)

**Comment by Legends** [comment]
@montogeek , @TheLarkInn 

I have created a [npm package for bootstraping the setup](https://github.com/Legends/Webpack-Dev-Setup) (initial draft).

Appreciate suggestions/improvements, just open an issue in the repo.
Just let me know if you would like to incorporate it into the webpack repo and how.
