### ISSUE TITLE
Resolvers not being rerun in webpack 3.

### ISSUE THREAD

**Issue by gdborton** [webpack/webpack#6838]
@TheLarkInn It seems this is the problem that we were stuck on last night.

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Webpack 3.11.0 doesn't rerun resolvers (including the UnsafeCache) between runs in memory.  I think this is a bug, because webpack 4 does, and it seems closer to the expected behavior.

**If the current behavior is a bug, please provide the steps to reproduce.**
I created a repo with instructions to reproduce - https://github.com/gdborton/webpack-resolver-reproduction

**What is the expected behavior?**
Even if a module hasn't changed, webpack should rerun the resolvers against it's original requests. 

**If this is a feature request, what is motivation or use case for changing the behavior?**
N/A

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
I don't think any of this matters. Problem is in webpack 3, but not in 4.2.0.

**Comment by V1shvesh** [comment]
Hey! I'm a first-time contributor to Webpack. Can I help fix this issue?
