### ISSUE TITLE
Bug: Require a relative file path with a !

### ISSUE THREAD

**Issue by gfranko** [webpack/webpack#684]
Webpack seems to error when you try to require a file that includes a relative file path with a `!` in it.  I realize that Webpack uses the exclamation point as it's syntax for loading plugins, but is there anything that can be done for normal file paths, that contain exclamation points, that are not trying to use any special loaders?

**Comment by sokra** [comment]
yeah I'm sorry, I hoped nobody would use an `!` in filenames. You need to rename the file... Sorry...

**Comment by gfranko** [comment]
Okay, well hopefully this issue helps someone else realize the problem if they run into it.

**Comment by apucacao** [comment]
I just ran into this. There is still no way to resolve paths that contain `!`, right?

**Comment by GorisWW** [comment]
Maybe this one needs to be fixed?

Default installation path for on-premise MS Build Agent **2017** is c:/!agent/_work. We can change it on-premise, but i wonder what will happen in cloud.

Lost half of a day tracing this bug... frustrating

**Comment by ascott18** [comment]
Also just spent quite a while running into this same issue. At the very least an informative error message that this does not work would be greatly appreciated.
