### ISSUE TITLE
can't load svg files from html file

### ISSUE THREAD

**Issue by DawidMmM** [webpack/webpack#6840]
**Do you want to request a *feature* or report a *bug*?**

I want to report a potential bug.

**What is the current behavior?**

Can't load svg files directly from html files.

**What is the expected behavior?**

Webpack should load this kind of files.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

I just wanna ask if is it possible to load svg files in the same way as for example png files. This is how i load pictures from my index.html:

```ejs
<body class="">
        <main class="content">            
            <img class="img img_custom-size" src=<%=require("./img/picture.jpg") %>       
        </main>
</body>
```

but when i try to load svg files doing:

```ejs
<body class="">
        <main class="content">
             <img class="img img_custom-size" src="img/picture.svg">
            <img src={require("img/picture.svg")} /> 
            <img src={require('!svg-inline!img/picture.svg')} />
            <img class="img img_custom-size" src=<%=require("./img/picture.svg") %>
        </main>
</body>
```

nothing happend.

This is my webpack.config.js:

```js
const {resolve} = require('path');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const webpack = require('webpack');

module.exports = {
  entry: {
    // polyfills: 'babel-polyfill',
    bundle: './src/app.js'
  },
  output: {
    path: resolve(__dirname, 'dist'),
    filename: '[name].js'
  },
  resolve: {
    extensions: ['.js', '.css']    
  },
  module: {    
    rules: [
      {
        test: /\.scss$/,
        enforce: "pre",
        loader: 'import-glob-loader'
      },  
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['env']
          }
        }
      },
      { 
        test: /\.(ttf|eot|woff2?|svg)$/,
        loaders: [
          {
            loader: 'url-loader',
            options: { 
              limit: 50000,    
              name: "./fonts/[name].[ext]"
            }
          }
        ]
      },
      {
        test: /\.(ico|gif|png|jpe?g|svg)$/,
        loaders: [
          {
            loader: 'file-loader',
            options: {
              name: '[path][name].[ext]',
              context: './src'     
            }
          }          
        ]
      },
      {
        test: /\.svg$/,
        loaders: [
          {
            loader: 'svg-inline-loader'                      
          }          
        ]
      }  
    ]
  },
  plugins: [       
    new HtmlWebpackPlugin({
      title: 'Sticky Notes',
      hash: true,    
      template: './src/index.html',
      // minify: {
      //   collapseWhitespace: true
      // },
    }) 
  ]
};
```

I don't wnat to use any svg-inline-loaders. I just wanna simply load a simple svg file from my index.html file.

**Comment by montogeek** [comment]
Read the documentation https://webpack.js.org/loaders/svg-inline-loader/#src/components/Sidebar/Sidebar.jsx

**Comment by DawidMmM** [comment]
I have read the documentation and there is nothing about how to load svg files using svg-inline-loader from html file.

**Comment by montogeek** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by ooflorent** [comment]
Yes it is possible. Remove `svg-inline-loader` and use `file-loader`.

- - - 

This is a usage question, and we encourage you to ask it on StackOverflow instead. We try to use the issue tracker for bug reports and feature requests, as well as some discussions, but this appears to be a very localized question. This is the only way to ensure the same question doesn’t get asked many times in a row, and that folks who have the same question in the future will be able to find it.

I’m closing for these reasons.
