### ISSUE TITLE
function constructor name changed after bundled as a library

### ISSUE THREAD

**Issue by zhenyulin** [webpack/webpack#6841]
**Do you want to request a *feature* or report a *bug*?**
report a bug

**What is the current behavior?**
the function constructor name was changed after code bundled via webpack

**If the current behavior is a bug, please provide the steps to reproduce.**

my webpack.config.js
```js
module.exports = {
	mode: 'production',
	devtool: 'source-map',
	target: 'node',
	entry: './src/index',
	output: {
		libraryTarget: 'umd',
		path: path.resolve('./dist'),
		filename: 'index.js',
	},
	externals: nodeExternals(),
	module: {
		rules: [
			{
				test: /\.js?$/,
				use: 'babel-loader',
				exclude: '/node_modules/',
			},
		],
	},
};
```

creator.js
```js
export function NError(fields) {
	if (!(this instanceof NError)) {
		return new NError(fields);
	}
	Object.keys(fields).forEach(key => {
		this[key] = fields[key];
	});
	Error.captureStackTrace(this, NError);
	return this;
}
```

test result in jest
```js
     - Snapshot
    + Received

    - NError {
    + a {
        "category": "FETCH_NETWORK_ERROR",
        "code": "MOCKED_FETCH_NETWORK_ERROR_CODE",
        "message": "mocked fetch network error",
      }
```

here the constructor name `NError` has changed to `a`

**What is the expected behavior?**

the constructor name in the above example should remain NError

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

Node:carbon
Webpack: ~4.0
OS: Mac 10.13.3

**Comment by montogeek** [comment]
I believe this is a Babel bug, not webpack, you can try using https://github.com/loganfsmyth/babel-plugin-transform-builtin-extend

**Comment by zhenyulin** [comment]
@montogeek have tried this, but don't think it is relevant, 1) the example NError here doesn't extend Error or Array, 2) if I comment out babel-loader to bundle the code without transpiling it and run the test with jest (babel builtin), if would still get the same error

so I think this may be something to do with webpack

**Comment by evilebottnawi** [comment]
@zhenyulin can you try `reserved` option for uglify (https://github.com/mishoo/UglifyJS2/tree/harmony#mangle-properties-options)

**Comment by zhenyulin** [comment]
@evilebottnawi the error can be re-produced without using uglify plugin, but have tried set it up with `keep_fnames, keep_classname, mangle: { reserved: ['NError']}` as well, but name still mangled

**Comment by zhenyulin** [comment]
tested with webpack@3.10.0, and it works fine

**Comment by evilebottnawi** [comment]
@zhenyulin can you create minimum reproducible test repo?

**Comment by ooflorent** [comment]
Did you disabled `modules` transpilation in babel? If it is enabled, then it is the expected behavior.

```js
// original
export function foo() {}

// after babel
exports.foo = foo;
function foo() {}

// after uglify (because mode=production)
function o(){}n.foo=o
```

**Comment by zhenyulin** [comment]
@ooflorent thanks for following up

here's my .babelrc
```json
{
  "presets": [
    [
      "env",
      {
      	"targets": { "node": "6.10" }
	  }
    ]
  ],
  "plugins": [
    "transform-object-rest-spread"
  ]
}
```

does `mode=production` has uglify built-in? if so, with what configuration and is there a good way to override that?

**Comment by ooflorent** [comment]
@zhenyulin You should change your Babel config to:

```js
{
  "presets": [
    [
      "env",
      {
        "modules": false,
        "targets": {"node": "6.10"}
      }
    ]
  ],
  "plugins": ["transform-object-rest-spread"]
}
```

By adding `modules=false` Babel won't transpile `import`/`export` statements so webpack could handle them.

For webpack 4, `mode=production` (or no mode) enables production settings, which include minification. If you want to disable this, set `optimization.minimize=true`.

For webpack 3, don't use `-p` flag.

**Comment by zhenyulin** [comment]
@ooflorent thanks for the quick followup.

I've tried use that option in babel-loader to override settings in .babelrc used by development and test, but still have the same issue.

I'm currently working on https://github.com/Financial-Times/n-error, which is a relatively small repo, happy to create a minimum repo for this as well ^

**Comment by zhenyulin** [comment]
@ooflorent , fixed the issue by setting `optimization.minimize` to `false`, thanks for the insight on this was turned on by default in production mode in v4.
