### ISSUE TITLE
Combination of entry and common modules in one chuck

### ISSUE THREAD

**Issue by maximuk** [webpack/webpack#6846]
**Do you want to request a *feature* or report a *bug*?**
feature or bug?

**What is the current behavior?**
Chunk includes entry's files code, but does not execute it.

**If the current behavior is a bug, please provide the steps to reproduce.**
I created test repository https://github.com/maximuk/webpack-test

**What is the expected behavior?**
Code from entry point should be executed

**If this is a feature request, what is motivation or use case for changing the behavior?**
I'm trying to mode all node_modules to one file, but also I want to execute some scripts (e.g. babel-polyfill). Of course I can add this scripts for each entry point, but in webpack 3 we had this possibility (with CommonsChunkPlugin - https://github.com/maximuk/webpack-test/tree/webpack-3-working-example)

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
* node 8
* webpack 4.2.0
* os ubuntu 16.04

**Comment by sokra** [comment]
`vendor` shoudn't be an entrypoint as you don't "enter" the application here.

Instead add modules you want to be executed at bootstrap into the entrypoints array.

I. e. when `vendor1` should be executed at bootstrap:

``` diff
  entry: {
-   module1: ['./module1'],
-   module2: ['./module2'],
-   vendors: ['./vendors1', './vendors2'],
+   module1: ['./vendors1', './module1'],
+   module2: ['./vendors1', './module2'],
  },
```

**Comment by maximuk** [comment]
This solution is not suitable for the project I am working on. We have ~10 entrypoints and also a lot of third party scripts that use modules from vendors script.
We include to vendors script, that has the next functionality:
```javascript
(function() {
  window['_'] = require('lodash');
})();
(function() {
  window['React'] = require('react');
})();
```
and provide webpack config with `externals` to other companies. The companies build scripts and we use them in our application.

Some pages use our scripts, some use third party scripts and some use both. And now for all pages, that use only 3rd party scripts we have to add entrypoint:
```javascript
entry: {
  'i-only-execute-vendors-scripts': [
    'babel-polyfill',
    'isomorphic-fetch',
    'someOtherVendorScript'
  ],
  ...
}
```
and load the script on this pages to execute vendors scripts.

I added example how it works in webpack@3 - https://github.com/maximuk/webpack-test/tree/webpack-3-working-example and would be nice to have the same possibility in webpack@4

**Comment by deleteme** [comment]
This relates to #6977.

**Comment by sergei-startsev** [comment]
Take a look at [ExecutableDllPlugin ](https://github.com/sergei-startsev/ExecutableDllPlugin)that allows to bundle shared modules and execute these modules.
