### ISSUE TITLE
Should mode production add a hash to output main.js?

### ISSUE THREAD

**Issue by joshunger** [webpack/webpack#6848]
**Do you want to request a *feature* or report a *bug*?**

feature

**What is the current behavior?**

Setting mode production does not add a hash to the default main.js.

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

Should mode production add a hash to output main.js?

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

**Comment by ooflorent** [comment]
No it should not to keep webpack integration simple. Currenlty, asset names are deterministic. If the filename contains a hash, the developer should consume `stats.json` to lookup the asset name. This is not beginner friendly.

**Comment by joshunger** [comment]
@ooflorent what's the goal of the production mode?  Can you state it?  Thanks.

**Comment by TheLarkInn** [comment]
@joshunger to elaborate further, if we ship hashes out of the box for production mode, then we risk breaking changes to users or forcing them to use a plugin like html-webpack-plugin to manage injecting files with hashes in them.

**Comment by TheLarkInn** [comment]
We will want to have a great preset to enable all of the best production features so that zero config is still a value proposition for those whod like it
