### ISSUE TITLE
Matching project folder name in noParse breaks build

### ISSUE THREAD

**Issue by christianalfoni** [webpack/webpack#685]
This is a weird one :-)

1. Clone repo: https://github.com/christianalfoni/webpack-example
2. `npm install`
3. `npm run dev`
4. localhost:8080 - Everything works
5. Change project folder name to something that contains "react", e.g.: "react-test"
6. `npm run dev``
7. localhost:8080 - broken

What I figured out was the following.

```javascript
{
  module: {
    noParse: [/react/] // matches project folder name
  }
}
```
If the noParse regexp matches the project folder name, everything brakes.

Thanks for an awesome tool!

**Comment by sokra** [comment]
It's a RegExp. What do you expect? Better pass an absolute filename...

**Comment by christianalfoni** [comment]
Well, I suppose I expected that aliased names are handled by noParse, not the actual path.

```javascript
{
  resolve: {
    alias: {
      'react': 'my/react/path'
    }
  },
  module: {
    noParse: [/react/]
  }
}
```
This is where I got confused, as I thought it pointed to the alias name. Much like a require('myNodeModule') noParse would not be the full path to the node module, but the string used in the require call?

**Comment by sokra** [comment]
It's matched agains the full resolved path.

**Comment by christianalfoni** [comment]
Okay, I will settle with that. Thanks for taking the time to answer the questions :-)
