### ISSUE TITLE
accessing process.env freshly in bundled code

### ISSUE THREAD

**Issue by zhenyulin** [webpack/webpack#6850]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
currently process.env.VARS would be replaced the defined values in webpack.config.js, and remains fixed value after code being bundled, not possible to access process.env.VARS when running the bundled code.

**What is the expected behavior?**
bundled code still being able to access values set in process.env

**If this is a feature request, what is motivation or use case for changing the behavior?**
e.g. if I use webpack to bundle a node server code or an npm package code, where there're features that rely on dynamically set ENV_VARS, then this wouldn't work after code being bundled with webpack.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

node: carbon
webpack: latest
OS: Mac OS

**Comment by ooflorent** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by mc-zone** [comment]
> e.g. if I use webpack to bundle a node server code or an npm package code, where there're features that rely on dynamically set ENV_VARS, then this wouldn't work after code being bundled with webpack.

Are you using `DefinePlugin` to transform your `process.env.VARS`? IMO, if you've transform some identifiers to constants, it doesn't make sense to continued mutating it. Or you could make a default values (like polyfills) in your code instead of using `DefinePlugin`.

**Comment by zhenyulin** [comment]
hi @ooflorent , thanks for following up quickly.

I've made a mini-repo to show the behaviour (https://github.com/zhenyulin/webpack-process-env)

**Comment by mc-zone** [comment]
@zhenyulin Just change it to:
```diff
new webpack.DefinePlugin({
-    'process.env': {
-        NODE_ENV: JSON.stringify('production'),
-    },
+    'process.env.NODE_ENV': JSON.stringify('production'),
}),

```

**Comment by mc-zone** [comment]
And also noticed that you are using webpack@4. This is no longer necessary to set `process.env.NODE_ENV` manually. You should set `mode` to `development`  or `production` to  Instead of it.

**Comment by zhenyulin** [comment]
seems to be an change in the DefinePlugin configs, when used the previous hierarchical configuration it wouldn't throw errors. remove or flatten this part did achieve the expected behaviour. 🎉

**Comment by zhenyulin** [comment]
I have further updated the repo

@mc-zone 
this config wouldn't set `process.env.ENV_VAR_BAR` to `bar`, while the original hierarchical setup works.

```js
new webpack.DefinePlugin({
    'process.env.ENV_VAR_BAR': JSON.stringify('bar'),
}),
```

Here's the current behaviour in the repo, and there seems to be some conflicts when partially set some ENV_VAR values in webpack.DefinePlugin:

If no values are set for `process.env` in `webpack.DefinePlugin`(comment out the section) then `ENV_VAR_FOO` got picks up correctly; if any value was set for `process.env`, e.g. set value to `ENV_VAR_BAR` but not `ENV_VAR_FOO`, ENV_VARS not set wouldn't pickup process.env correctly.

**Comment by ionphractal** [comment]
I've been wondering for quite a while, why webpack insists by design/default of compiling in the process.env variables at all. It seems rather counter intuitive of what the process.env object stands for and is a pitfall to many if not all newbies. Additionally it's not even 12factor compatible (https://12factor.net/config) which is the basis for modern development paradigms (i.e. microservice architecture).

Is there some technical reason behind it that it can't be the default to just pass process.env always from the environment? Is this a design decision? If so, why?

I'd be happy to have a deeper understanding of this, so could any core dev member please explain it? (Of if it already has been explained before, please point me to the documentation).

**Comment by dyladan** [comment]
I would also like to throw in that I find this behavior very frustrating for node.js apps. We have an existing app where we change configurations by modifying the environment and restarting the process. We wanted to move to Webpack for a handful of reasons but we can't if Webpack insists on replacing all instances of `process.env.VAR_NAME` with a string literal. Please provide a configuration to disable this behavior.

This code compiles but fails at runtime:

```javascript
process.env.VAR = PROCESS.env.VAR || "default";
```

transpiles to either of the following depending if the var is set:

```javascript
"default" = "default" || false;
```

```javascript
"value" = "value" || "default";
```

**Comment by zhenyulin** [comment]
An update from me for getting Webpack to pack node server code, I'm currently using `webpack-dotenv-plugin`, which is essentially a wrapper around DefinePlugin, and I'm only using this for dev and excluding it for PROD bundle build, and without it the bundle code would just pick up ENV_VAR from process.

**Comment by arenddeboer** [comment]
For anyone looking for a solution.

None of the above comments solved this issue for me. But I found this example that worked on SO:
```
// avoid cunning webpack replacement of process.env code
let process_env = {}
for (var a of ['env']) {
  process_env = process[a]
}
console.log(process.env.HOME) // this gives undefined
console.log(process_env.HOME) // this works
```
https://stackoverflow.com/a/49896877/588950

Credit goes to David Fraser
