### ISSUE TITLE
After a fresh clone test is failing as uglifyjs-webpack-plugin package needs webpack itself.

### ISSUE THREAD

**Issue by devsumanmdn** [webpack/webpack#6851]
**Do you want to request a *feature* or report a *bug*?**
It's a bug.

**What is the current behavior?**
In node_modules/uglifyjs-webpack-plugin/dist/index.js requires "webpack/lib/RequestShortener" and others from webpack. after I install webpack in "node_modules/uglifyjs-webpack-plugin/" dir the things goes well but 

10750 passing (11m)
  144 pending
  2 failing
is the result any way with these errors
1. Error: Cannot find module 'webpack/lib/dependencies/ConstDependency'
2. Error: (webpack)/node_modules/worker-loader/dist/cjs.js?name=hash.worker.js!./worker.js
**If the current behavior is a bug, please provide the steps to reproduce.**
Just try doing "npm i" and then "npm run test".

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
webpack@4.2.0
node@8.10.0
Ubuntu@14.04.4

**Comment by Legends** [comment]
After `git clone`, did you do the following?:

1. `cd webpack`
2. `yarn install`
3. `yarn link`
4. `yarn link webpack`

**Comment by ooflorent** [comment]
@devsumanmdn the bootstrap instructions are listed in `CONTRIBUTING.md`. Please read this file. It also contains useful tips to get started with the codebase.

Run the commands given by @Legends and it should work.

**Comment by devsumanmdn** [comment]
Thanks, its working now.
