### ISSUE TITLE
Errors in 'Getting Started' documentation

### ISSUE THREAD

**Issue by pjverity** [webpack/webpack#6852]
**Do you want to request a *feature* or report a *bug*?**
Documentation error

**What is the current behavior?**
The browser fails to load the compiled .js as the resource can not be found

**If the current behavior is a bug, please provide the steps to reproduce.**

Follow the [**Getting Started**](https://webpack.js.org/guides/getting-started/) guide

**What is the expected behavior?**

The compiled .js should be loaded by the browser

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

Under the [**Creating a Bundle**](https://webpack.js.org/guides/getting-started/#creating-a-bundle) section, it states the output from running `npx webpack` should be:

`Entrypoint main = bundle.js`

But it is in fact

`Entrypoint main = main.js`

Consequently, the browser fails to load the .js from the location the example states:
`<script src="dist/bundle.js"></script>`

Also, as the guide instructs the reader to move `index.html` in to `dist/`, the path in the example is incorrect and should actually be:
`<script src="main.js"></script>`

**Comment by montogeek** [comment]
@webpack-bot move to webpack/webpack.js.org
