### ISSUE TITLE
error when starting webpack

### ISSUE THREAD

**Issue by idessignflo** [webpack/webpack#6853]
**Do you want to request a *feature* or report a *bug*?**
yes it's a mistake

**What is the current behavior?**
webpack does not compile

**If the current behavior is a bug, please provide the steps to reproduce.**

C:\Idessign>webpack
The CLI moved into a separate package: webpack-cli.
Please install 'webpack-cli' in addition to webpack itself to use the CLI.
-> When using npm: npm install webpack-cli -D
-> When using yarn: yarn add webpack-cli -D

**What is the expected behavior?**
that webpack compiles correctly

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
Node.js v8.9.3 
webpack v4.
windows 8.1 professionnel 
I compiled well with webpack v3 when I made the update to go to webpack v4 is here the error

C:\Idessign>webpack
The CLI moved into a separate package: webpack-cli.
Please install 'webpack-cli' in addition to webpack itself to use the CLI.
-> When using npm: npm install webpack-cli -D
-> When using yarn: yarn add webpack-cli -D
thank you in advance for help

**Comment by Legends** [comment]
Sooo, did you install the 'webpack-cli' ?
Cannot figure it out, while reading your post.

> -> When using npm: npm install webpack-cli -D
> -> When using yarn: yarn add webpack-cli -D

**Comment by ooflorent** [comment]
With webpack 4 you must also add `webpack-cli` to your dependencies. Once installed, `webpack` command would work as expected.
