### ISSUE TITLE
Can't use AggressiveSplittingPlugin split code run well in html

### ISSUE THREAD

**Issue by BarryYan** [webpack/webpack#6855]
**Do you want to request a *feature* or report a *bug*?**  
Bug

**What is the current behavior?**   
After I use `AggressiveSplittingPlugin` split big chunk into small chunks, and edit `AggressiveSplittingPlugin` source code to add name for new chunks, using `HtmlWebpackPlugin` inject all chunks into html, but the js not work, throw an error: `Uncaught TypeError: Cannot read property 'call' of undefined`

**If the current behavior is a bug, please provide the steps to reproduce.**    
Use `AggressiveSplittingPlugin`, `HtmlWebpackPlugin` in webpack.config.js, run devServer, preview html page

**What is the expected behavior?**    
Split code success, run page well 

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

node: 9.0.0       
webpack: 3.8.0    
html-webpack-plugin: 2.30.1

**Comment by montogeek** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by Shafley** [comment]
@montogeek  I have created an example [https://github.com/Shafley/AggressiveSplittingPlugin-test](https://github.com/Shafley/AggressiveSplittingPlugin-test)
If I remove `AggressiveSplittingPlugin`, after build, html run well, and the file `vendor.js`, `index.js` all in html script. 
If  I add `AggressiveSplittingPlugin`, there only `index.js` in html, `vendor.js` is splited many small chunk, but they are not injected into html by  `HtmlWebpackPlugin`, becase `HtmlWebpackPlugin` only distinguish chunk name to work, `vendor.js`  is  disappear,  insted of  many small chunks without name. 
I try edit `AggressiveSplittingPlugin` source code to add name for new chunk, after they can be injected into html, but not work either.
So can you help me ?
Thanks.

**Comment by sokra** [comment]
This is a problem in `HtmlWebpackPlugin`, but as far as I know they are aware of it and working on it.

**Comment by Shafley** [comment]
Any process? 
I found some issues in [html-webpack-plugin/issues/889](https://github.com/jantimon/html-webpack-plugin/issues/889). it seemed they weren't sure the bug belonged to `HtmlWebpackPlugin`. 
**I was running to `AggressiveSplittingPlugin` souce code, added name for new chunks, then they could be injected into html, but it still not worked 😞**
