### ISSUE TITLE
Old documentations (3.8)

### ISSUE THREAD

**Issue by Erowlin** [webpack/webpack#6868]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Can't find the documentation of old Webpack versions (3.8). - Especially the API for the webpack.config.js file. 

**If the current behavior is a bug, please provide the steps to reproduce.**
[Go to documentation](https://webpack.js.org/configuration/devtool/), and don't find the 3.x documentation. 

**What is the expected behavior?**
[Go to documentation](https://webpack.js.org/configuration/devtool/) and find documentation for old versions

**Comment by montogeek** [comment]
@webpack-bot move to webpack/webpack.js.org
