### ISSUE TITLE
webpackChunkName is missing in webpack production mode

### ISSUE THREAD

**Issue by Wyntau** [webpack/webpack#6876]
**Do you want to request a *feature* or report a *bug*?**
*bug*

**What is the current behavior?**
webpackChunkName is missing in webpack production mode
**If the current behavior is a bug, please provide the steps to reproduce.**
demo project: https://github.com/Wyntau/webpackChunkName-demo
the output is in production directory
![image](https://user-images.githubusercontent.com/2631733/37950161-2535423c-31ca-11e8-8bbe-1261ef713729.png)
![image](https://user-images.githubusercontent.com/2631733/37950182-326ee778-31ca-11e8-81f5-b4b9e7192d0f.png)

**What is the expected behavior?**
webpackChunkName is corrent in production mode

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
webpack 4.2.0

**Comment by EugeneHlushko** [comment]
It is not a bug @Wyntau 
Named chunks are disabled for production mode, you can override the default behavior by modifying your config:
```diff
module.exports = {
  mode: process.env.NODE_ENV === 'development' ? 'development' : 'production',
  ...
+ optimization: {
+   namedChunks: true
+ }
}
```

> Note: Since the chunk name includes all origin chunk names it’s recommended for production builds with long term caching to NOT include [name] in the filenames, or switch off name generation via optimization.splitChunks.name: false. Elsewise files will invalidate i. e. when more chunks with the same vendors are added.

**Comment by Wyntau** [comment]
@EugeneHlushko Thanks for you answer. 
Could you please have a look at #6866 
Does `[request]` require a variable in `webpackChunkName`?

**Comment by EugeneHlushko** [comment]
I glad i could help @Wyntau 
I had seen the issue yesterday, but unfortunately i need some time to investigate so did not leave a comment yet maybe someone from our team will respond quicker

**Comment by AndreyLuzinov** [comment]
I don't understand how to write dynamic module loading which will work in production with default, namedChunks: false?
