### ISSUE TITLE
Cannot remove comments from production bundle using optimization.minimize

### ISSUE THREAD

**Issue by shamas** [webpack/webpack#6879]
feature

**What is the current behavior?**
Currently no options can be passed to the default minimizer. And it does not remove comments by default.

minimize could be : boolean | { options? : object } where the options get directly applied to the uglifier. The only draw back is the options check would have to be kept in sync with the uglifier.

**If this is a feature request, what is motivation or use case for changing the behavior?**
This was something that was easy to do in webpack 3 (after initial config) which is now impossible without a lot of work...

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
Webpack 4.2 - Node 8.9.1

**Comment by ooflorent** [comment]
Use `optimization.minimizer` to specify options:

```js
{
  optimization: {
    minimizer: [
      new UglifyJsPlugin({ /* … */ })
    ]
  }
}
```

**Comment by Inigo-Pascall** [comment]
So. Do I take it that there is currently no way to remove comments from js with Webpack..? Seriously?

**Comment by lmjhs** [comment]
This worked for me

```js
{
  optimization: {
    minimizer: [
      new UglifyJsPlugin({
        uglifyOptions: {
          output: {
            comments: false
          }
        }
      })
    ]
  }
}
```

**Comment by Inigo-Pascall** [comment]
@lmjhs Works perfectly for me (Webpack 4.10.2). Many thanks :)

**Comment by bitterloa** [comment]
it baffles me why @lmjhs solution is not in the main Readme and can only be found buried deep in an issues thread. Removing comments seems like one of the most popular things to do when minimizing JS...

**Comment by davidyeiser** [comment]
Where does @lmjhs’s solution actually go? I tried putting it in `webpack.config.js` in the project’s root directory, but that doesn’t seem to be correct…

**Comment by bitterloa** [comment]
@davidyeiser perhaps this may help? i put the optimization code in the root node of my webpack config alongside my other options:

https://webpack.js.org/configuration/optimization/

**Comment by davidyeiser** [comment]
@bitterloa That seemed to work — thank you!

**Comment by yaitskov** [comment]
I have similar issue. Adding UglifyJs plugin doesn't change anything.

```
Version: webpack 4.28.1
node --version
v10.14.2
```
webpack config:
```
  optimization: {
    minimizer: [
      new UglifyJsPlugin({
        uglifyOptions: {
          output: {
            comments: false
          }
        }
      })
    ]
  },
  
  module: {
    rules: [
      // Handle .ts and .tsx file via ts-loader.
      {
        test: /\.tsx?$/,
        exclude: /node_modules/,
        use: {
          loader: "babel-loader",
          options: {
            presets: [['@babel/typescript', { jsxPragma: "h" }]],
            plugins: [
              ['@babel/proposal-class-properties'],
              ['@babel/proposal-object-rest-spread'],
              ['@babel/plugin-syntax-dynamic-import'],
              ["@babel/transform-react-jsx", { "pragma": "h" }]
            ]
          }
        }
      }
    ]
  }

Sample of supposed to be minimized code. 

```webpack-cli -p```

It looks like everything wrong with this code: supper long names, spaces, comments.

```

(window.webpackJsonp=window.webpackJsonp||[]).push([[1],{6:function(module,__webpack_exports__,__webpack_require__){"use strict";eval('__webpack_require__.r(__webpack_exports__);\n/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "default", function() { return Home; });\n/* harmony import */ var preact__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(0);\n/* harmony import */ var preact_router__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(1);\n\n\nclass Home extends preact__WEBPACK_IMPORTED_MODULE_0__["Component"] {\n  routeToLink() {\n    Object(preact_router__WEBPACK_IMPORTED_MODULE_1__[/* route */ "d"])(\'/terms\');\n  }\n\n  power2() {\n    return this.powerX(2);\n  }\n\n  powerX(n) {\n    return n * n;\n  }\n\n  render() {\n    return Object(preact__WEBPACK_IMPORTED_MODULE_0__["h"])("h1", null, "This is Profile page of", Object(preact__WEBPACK_IMPORTED_MODULE_0__["h"])("div", null, Object(preact__WEBPACK_IMPORTED_MODULE_0__["h"])(preact_router__WEBPACK_IMPORTED_MODULE_1__[/* Link */ "a"], {\n      href: "/profile/blah"\n    }, "blah profile")), Object(preact__WEBPACK_IMPORTED_MODULE_0__["h"])(preact_router__WEBPACK_IMPORTED_MODULE_1__[/* Link */ "a"], {\n      href: "/terms"\n    }, "terms"), Object(preact__WEBPACK_IMPORTED_MODULE_0__["h"])("div", {\n      href: "/terms",\n      onClick: this.routeToLink\n    }, "terms via route"), Object(preact__WEBPACK_IMPORTED_MODULE_0__["h"])("div", null, "2 * 2 = ", this.power2()));\n  }\n\n}\n\n//# sourceURL=webpack:///./src/components/Profile.tsx?')}}]);

```

**Comment by arcanis** [comment]
@vinogradov A dependency being a dependency of Webpack doesn't mean you're allowed to require it just like this. If you use `terser-webpack-plugin`, you **must** list it in your `package.json`. Doing otherwise may or may not work, and the exact behavior may change in the future without notice (that includes plain crashes or the possibility that you'll use an incorrect version of `terser-webpack-plugin`).

**Comment by Birowsky** [comment]
Did anyone who tried @vinogradov 's suggestion ran into problems with sourcemaps? It seems to me that sourcemaps are referenced through comments. Any input here?

**Comment by marechal-p** [comment]
@Birowsky I suppose you shouldn't optimize your bundles too much when developing (when you need source maps), versus production mode where you wouldn't use source map anymore. Might be best to have at least two bundling configurations in this case: one fully optimized without comments, and one for development when you have to use source-maps.

**Comment by raimund-schluessler** [comment]
@Birowsky `terser-webpack-plugin` has a sourceMap option: https://github.com/webpack-contrib/terser-webpack-plugin#sourcemap

This works for me:
```js
optimization: {
	minimizer: [new TerserPlugin({
		terserOptions: {
			output: {
				comments: false,
			}
		},
		sourceMap: true
	})],
}
```

**Comment by Birowsky** [comment]
@marechal-p I use Sentry for reporting production issues. It does rely on source maps to do it's job.

@raimund-schluessler beautiful! Thanx.

**Comment by Sumit2105** [comment]
Is it possible to have the build without .LICENSE file

**Comment by RaviDasari** [comment]
@raimund-schluessler I tried those settings but it is not working for me. Terser will always keep comments if I enable sourceMap.

**Comment by evilebottnawi** [comment]
Regression in new version, WIP

**Comment by evilebottnawi** [comment]
Please update terser plugin to `2.1.1` and use this https://github.com/webpack-contrib/terser-webpack-plugin#remove-comments

**Comment by shijiezhou1** [comment]
> Use `optimization.minimizer` to specify options:
> 
> ```js
> {
>   optimization: {
>     minimizer: [
>       new UglifyJsPlugin({ /* … */ })
>     ]
>   }
> }
> ```

That's for js bro

**Comment by xgqfrms** [comment]
```js
module.exports = {
  entry: /*...*/
  output: /*...*/,
  module: /*...*/,
  optimization: {
    minimizer: [
      new TerserPlugin({
        terserOptions: {
          output: {
            // 1. remove comments
            comments: false,
          },
        },
      }),
    ],
  },
}

```

```js
module.exports = {
  entry: /*...*/
  output: /*...*/,
  module: /*...*/,
  optimization: {
    minimizer: [
      new TerserPlugin({
        terserOptions: {
          output: {
            // 2. preserve  comments
            comments: false,
          },
        },
      }),
    ],
  },
}

```

```js
module.exports = {
  optimization: {
    minimizer: [
      new UglifyJsPlugin({
        uglifyOptions: {
          output: {
            comments: /@license/i,
          },
        },
        extractComments: true,
      }),
    ],
  },
};
