### ISSUE TITLE
dynamic import is not working

### ISSUE THREAD

**Issue by vikasraj789** [webpack/webpack#6887]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
By using import(), webpack is not creating a new chunk and i noticed that import("../pages/x.js") is transpiled into ```Promise.resolve(/*! import() */).then(__webpack_require__.bind(null, /*! ../pages/x.js))```

**If the current behavior is a bug, please provide the steps to reproduce.**
Here is my webpack config [(webpack.config.dev.js)](https://gist.github.com/vikasraj789/4a1805b616b89c1012213d0d385e80d2)

**What is the expected behavior?**
By using import(), webpack should spit out another chunk and lazyily load the chunk.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
chrome - latest
webpack - 4.3.0
os - macos high sierra

Posted the same issue in webpack gitter, but to no avail.

**Comment by ooflorent** [comment]
Thanks for your report. It would be great if you reduce your issue to a small reproducible example. Best put this example into a github repository together with instructions how to get to the problem.

**Comment by sokra** [comment]
babel plugin `"dynamic-import-node"` is the problem. Use the syntax import plugin instead.

**Comment by vikasraj789** [comment]
@sokra  Thanks for the prompt response.
I have used syntax import plugin and dynamic import webpack plugins. Both are not solving the issue

**Comment by RobertHeim** [comment]
@vikasraj789 try adding the plugin to webpack.config.js

**Comment by snikobonyadrad** [comment]
Removing `dynamic-import-node` and using just `syntax-dynamic-import` fixes this but then node can't run the tests:

```
return import('../a-file');
           ^^^^^^
SyntaxError: Unexpected token import
```
