### ISSUE TITLE
where is the '~' symbol resolve rule

### ISSUE THREAD

**Issue by Oscar-ren** [webpack/webpack#6888]
**Do you want to request a *feature* or report a *bug*?**
Yes, sorry for the question.

In the .css file, we can import file use ('~moduleName'),but i can't find why? 
I search the source code, find in stackoverflow and issue,but there is nothing about the `~` symbol resolve rule.

Could you tell me why the webpack will resolve as module if path begin with `~` sybmol?
Where is the source code?

Thank you so much.

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
mac
webpack@3
node@8

**Comment by sokra** [comment]
https://github.com/webpack/loader-utils/blob/67499ff3d13c13ef455ec0fede90b714fc16d787/lib/urlToRequest.js#L23-L29
