### ISSUE TITLE
cheap-module-eval-source-map break the folder structure

### ISSUE THREAD

**Issue by maunier** [webpack/webpack#6896]
**Do you want to request a *feature* or report a *bug*?**
feature

**What is the current behavior?**
if i use cheap-module-eval-source-map, the source map's folder structure is not the same with when i write it.

eg: the structrue when i wrote it is like this:

```
- src
    - index.js
    - my-component1
       - index.js
       - main.vue
    - my-component2
       - index.js
       - main.vue
```

but the source map's folder structrue is like this:

```
- webpack://
    -src
        - index.js
    - main.vue?s03s
    - main.vue?34ds
```
        
   

**If the current behavior is a bug, please provide the steps to reproduce.**
you can just run a project with the folder structure I have described above, and use the cheap-module-eval-source-map devtool.

**What is the expected behavior?**
i expect the source map's folder structure is the same with when i wrote it.  

**If this is a feature request, what is motivation or use case for changing the behavior?**

when i wanted to set a break point , i found i can't find the target file. All the components files are named main.vue， i can't use 'my-component1/main.vue' to find the right file

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**
browser: chrome 63
node: 8.4.0
webpack: 3.11.0
operating system: osx

**Comment by montogeek** [comment]
Have you tried with another source map plugin?

**Comment by maunier** [comment]
@montogeek Yes, I have tried eval-source-map, it dosen't  break the folder structure but it has lower perfomance.

**Comment by montogeek** [comment]
@maunier Then that is how that plugin works :/
Try with `eval` it is faster than `cheap-module-eval-source-map` https://webpack.js.org/configuration/devtool/

**Comment by sokra** [comment]
no it should have correct paths
