### ISSUE TITLE
Show your modules tree

### ISSUE THREAD

**Issue by sokra** [webpack/webpack#690]
Just for entertainment:
1. Compile with `webpack --profile --json > stats.json` <br>
   (node.js API: `{ profile: true }` and `stats.toJson()`)
2. Go to http://webpack.github.io/analyse/#modules
3. Load your stats file (It's not uploaded, the analyse tools is a client only tool).
4. Wait a bit until the graph has been stabilized.
5. Screenshot and cut the graph area.
6. Post it into this thread.

These are the webpack test cases:
![image](https://cloud.githubusercontent.com/assets/1365881/5745055/40da9236-9c26-11e4-9e2b-6611cd743423.png)

React:
![image](https://cloud.githubusercontent.com/assets/1365881/5745876/0635f318-9c2c-11e4-8d73-652b8616200a.png)

**Comment by gaearon** [comment]
Stampsy.com (React, Flux, CSS also processed with Webpack)

![screen shot 2015-01-14 at 23 44 53](https://cloud.githubusercontent.com/assets/810438/5747202/608498fe-9c47-11e4-9a30-e26ad6f091ae.png)


Icons:

![screen shot 2015-01-14 at 23 46 17](https://cloud.githubusercontent.com/assets/810438/5747229/92d7594a-9c47-11e4-95e4-feb3dcf28add.png)


PureRenderMixin:

![screen shot 2015-01-14 at 23 47 09](https://cloud.githubusercontent.com/assets/810438/5747243/b0645e2c-9c47-11e4-9442-06d459549e0d.png)


Routes:

![screen shot 2015-01-14 at 23 49 26](https://cloud.githubusercontent.com/assets/810438/5747292/045f7d72-9c48-11e4-8298-e406e0d81795.png)


react-router:

![screen shot 2015-01-14 at 23 50 46](https://cloud.githubusercontent.com/assets/810438/5747328/32e001f8-9c48-11e4-8a29-5353047c88e3.png)

Article page components:

![screen shot 2015-01-14 at 23 54 28](https://cloud.githubusercontent.com/assets/810438/5747403/bb1ad0de-9c48-11e4-9bb9-2f9a5f0cac46.png)

**Comment by nelix** [comment]
getstack.io (React, Fluxxor)
![screen shot 2015-01-15 at 11 00 37 am](https://cloud.githubusercontent.com/assets/33324/5750233/cf9d5efc-9ca5-11e4-96ef-6d5c3c1389b8.png)

Our icons look much the same as stampsy..
![screen shot 2015-01-15 at 11 02 04 am](https://cloud.githubusercontent.com/assets/33324/5750245/11ef0738-9ca6-11e4-975e-335c7f62a9bd.png)

Fluxxor (red things are actions and stores):
![screen shot 2015-01-15 at 11 03 43 am](https://cloud.githubusercontent.com/assets/33324/5750256/488460a4-9ca6-11e4-8ffc-718aa38d989c.png)

react-router:
![screen shot 2015-01-15 at 11 06 46 am](https://cloud.githubusercontent.com/assets/33324/5750284/ab5019c6-9ca6-11e4-9448-cd83a35c4e7e.png)

**Comment by jlongster** [comment]
A somewhat simpler site, but still with quite a few dependencies: my blog, http://jlongster.com/

![screen shot 2015-01-14 at 11 17 05 pm](https://cloud.githubusercontent.com/assets/17031/5752474/08e4f326-9c44-11e4-897b-a69b754a1d09.png)

These are all the locale files loaded by [momentjs](http://momentjs.com/). I did not know it was loading all of those, this is awesome! I don't need them, and I should remove them. Should have seen them in the modules list in the output, but I missed that.

![screen shot 2015-01-14 at 11 18 28 pm](https://cloud.githubusercontent.com/assets/17031/5752475/0be3cd86-9c44-11e4-83f0-e07d244e8ce2.png)

This is my editor which uses code splitting to lazily load the CodeMirror files. I'm impressed it shows that, and with a dotted line.

![screen shot 2015-01-14 at 11 19 21 pm](https://cloud.githubusercontent.com/assets/17031/5752476/0e77df4c-9c44-11e4-8a9a-99a1a0068da4.png)

**Comment by andrewk** [comment]
99designs.com/contests

![screen shot 2015-01-15 at 3 31 35 pm](https://cloud.githubusercontent.com/assets/37946/5752534/ac67d5d6-9ccb-11e4-90b8-04a0599e6880.png)

99designs.com/projects

![screen shot 2015-01-15 at 3 29 05 pm](https://cloud.githubusercontent.com/assets/37946/5752536/bc3baa0a-9ccb-11e4-8fdd-b494fd3765ce.png)

@jlongster We have momentjs as well, webpack will get rid of large amounts of those lang files via dead code removal. But if you're not doing i18n, no need to have them in the first place.

**Comment by ifandelse** [comment]
From a portion of [LeanKit](http://leankit.com/)'s soon-to-be analytics site (we're retiring legacy code, using React, lux, machina, moment, postal and more):

![](https://www.evernote.com/shard/s21/sh/f5956f83-ba68-4075-8134-bac24f173826/32605c88b2828786edc4d5929d16d596/deep/0/modules.png)

**Comment by KyleAMathews** [comment]
Internal app at [RelateRocket](https://relaterocket.co)

![screen shot 2015-01-14 at 9 07 08 pm](https://cloud.githubusercontent.com/assets/71047/5752765/57fd093e-9c31-11e4-9fbb-d9c91c6b2eb0.png)

Clusters include react-bootstrap, Bluebird, react-spinkit (brings in a bunch of little css files), Reflux, and a large assortments of other small modules.

**Comment by kossnocorp** [comment]
React powered app (821 modules at the moment):

![screen shot 2015-01-15 at 12 13 33](https://cloud.githubusercontent.com/assets/52201/5753482/2f0cbfe0-9cb0-11e4-8555-f4b0fd9686cf.png)

As @jlongster I noticed rudimental Moment.js flower (on the left)

**Comment by gaearon** [comment]
That's funny. I also noticed Moment from Webpack stats (and removed it because realized I only ever used it in two places where I could write my own simple handler).

**Comment by winkler1** [comment]
react.rocks

![image](https://cloud.githubusercontent.com/assets/883896/5758978/1f07ce18-9c98-11e4-8488-fb36ed0540be.png)

That's me in the corner-
![image](https://cloud.githubusercontent.com/assets/883896/5759003/6fcdf58e-9c98-11e4-98f6-453fd5d428e1.png)

Underscore, 44K. TODO: lodash custom builds.
![image](https://cloud.githubusercontent.com/assets/883896/5759032/a472b932-9c98-11e4-8d0e-eef8608386a1.png)

Currently using Masonry via react-masonry-mixin...and jquery. 276K. To be replaced a more React-centric layout. 
![image](https://cloud.githubusercontent.com/assets/883896/5759164/b466ea92-9c99-11e4-9c70-e8b4d639c6cd.png)

**Comment by loganfsmyth** [comment]
[Inkling Habitat](https://www.inkling.com/habitat/) I switched us to Webpack last week. The graph is a little gross because we haven't had much of a build system up until now.  I debated posting this since it's not as nice looking as the ones above, but oh well, 4 years of slowly evolving JS will do that :P I'll be working to clean things up in the next few months. The two main blobs are tests and templates, because we directly require them all centrally right now.

~1350 modules including all tests and templates
![screen shot 2015-01-15 at 11 43 35 am](https://cloud.githubusercontent.com/assets/132260/5765586/9f323602-9caf-11e4-84d2-ced4d8ea2934.png)

~810 modules without tests
![screen shot 2015-01-15 at 1 05 59 pm](https://cloud.githubusercontent.com/assets/132260/5766545/4bba9d18-9cb7-11e4-9567-4f1d434ac5ce.png)

P.S. Hi @KyleAMathews !

**Comment by damassi** [comment]
[Kindling](http://www.kindlingapp.com) -- Funny about that Moment.js!

![screen shot 2015-01-15 at 5 48 36 pm](https://cloud.githubusercontent.com/assets/236943/5770419/dfa8e4f4-9cde-11e4-81d7-a52354e4a465.png)

**Comment by jhnns** [comment]
From our [peerigon](https://peerigon.com/) web-app

### *Nobody wants to play with jquery*
![](https://cloud.githubusercontent.com/assets/781746/5774858/fbece022-9d72-11e4-9351-1b6f132635ba.jpg)

**Comment by jkimbo** [comment]
[onefinestay.com](http://www.onefinestay.com/) (React, Fluxxor, Immutable and lots of old Backbone, jQuery code)

![screenshot 2015-01-21 18 28 23](https://cloud.githubusercontent.com/assets/691952/5842318/bd8fe66c-a19b-11e4-8226-2efce7d27eb2.png)

We use the [6to5-loader](https://github.com/6to5/6to5-loader) and move the runtime into a separate module:

![screenshot 2015-01-21 18 28 58](https://cloud.githubusercontent.com/assets/691952/5842339/e442a8bc-a19b-11e4-8978-c7a3d7124604.png)

And unfortunately jQuery is still used in a lot of our code:

![screenshot 2015-01-21 18 33 30](https://cloud.githubusercontent.com/assets/691952/5842355/09da5778-a19c-11e4-95e3-15910cce96c7.png)

**Comment by lettertwo** [comment]
[rockefellercenter.com][1] — an isomorphic React app which has two builds of the same code base: a browser build and a server build.

## The browser:
![rcbrowser](https://cloud.githubusercontent.com/assets/210630/5988908/572c6702-a942-11e4-8f1d-f18fc65a1095.jpg)

This is a graph of **~1370** modules, roughly **~130** of which are assets other than js (images, icons, etc). This graph also includes styles (less).

A bunch of modules with React components:
![rcbrowser-reactjs](https://cloud.githubusercontent.com/assets/210630/5989007/fad3668c-a945-11e4-87f3-ee568fed2581.jpg)

The main App entry point:
![rcbrowser-app](https://cloud.githubusercontent.com/assets/210630/5989093/972ef340-a949-11e4-864e-f3a480a84b85.jpg)

## The server:
![rcserver](https://cloud.githubusercontent.com/assets/210630/5988909/5e570690-a942-11e4-8f66-5f44b0f74455.jpg)

Notably smaller than the browser build at just **~787** modules because we exclude all node modules from the build (since we are building a node app for the server). 

The same bunch of React components, but with React as an external dependency:
![rcserver-reactjs](https://cloud.githubusercontent.com/assets/210630/5989011/16f4e4f8-a946-11e4-803a-7e6482f142b8.jpg)

And the same App entry point:
![rcserver-app](https://cloud.githubusercontent.com/assets/210630/5989090/8453f3e2-a949-11e4-9730-04fea0a29f95.jpg)

---

Webpack has been *amazing* for this app—it made building both the browser and server apps from the same code base trivial. It enabled us to just build the same dependency tree for both apps, but get much different output by simply configuring Webpack differently for each build target.

Including *all* of our assets (not just the 'code' assets like scripts and styles) in the graph meant that Webpack would build the same (hashed!) file paths into both the server and the client, which allows us to aggressively cache everything in the browser with impunity.

[1]: http://www.rockefellercenter.com/

**Comment by ThomasDeutsch** [comment]
Where can i find the analyzer now?
This link is broken: [http://webpack.github.io/analyse/#modules](http://webpack.github.io/analyse/#modules)

**Comment by gaearon** [comment]
@ThomasDeutsch It works for me..

**Comment by ThomasDeutsch** [comment]
Sorry it works. I am using the https-everywhere Chrome extension - and was redirected to [https://webpack.github.io/analyse/#modules] (https://webpack.github.io/analyse/#modules)

**Comment by Sinewyk** [comment]
For momentjs I used `noParse: [/moment.js/],` and manually include the supported locales. I should try sometimes to create an i18n bundle having everything for a locale but for now it does the job ^^.

**Comment by itsazzad** [comment]
nice entertainment :100:

**Comment by fnlctrl** [comment]
Awesome!

**Comment by SilentCicero** [comment]
@sokra I get this: 

```
Uncaught SyntaxError: Unexpected token St.onload @ 8.970b70af1d8094b96211.js:1
```

Thoughts?

**Comment by loganfsmyth** [comment]
@SilentCicero Webpack has a support channel, that is the best place for questions: https://gitter.im/webpack/webpack

**Comment by guitarmanvt** [comment]
@SilentCicero : I had the same problem. I discovered that my process was dumping junk into the same file with the JSON, so it wasn't producing valid JSON. I manually edited my file, then used a JSON parser to validate it. After that, it worked great.

**Comment by guitarmanvt** [comment]
A React/Redux pluggable framework, with just a few modules plugged in. (With Mac volume control watermark, too!)

![react redux pluggable framework](https://cloud.githubusercontent.com/assets/325439/15270427/b241e870-19ed-11e6-969a-0f61cdc29ece.png)

**Comment by derekstavis** [comment]
My webpack work on an already in production angular app:

![screenshot from 2016-05-15 16-41-01](https://cloud.githubusercontent.com/assets/1611639/15276360/5f849748-1abc-11e6-80a6-28867ecb7d56.png)

**Comment by whtouche** [comment]
Am I doing something wrong, or just not being patient enough? I chose my stats.json file but don't see a button to consummate the upload, and it doesn't move past this screen:
![stats](https://cloud.githubusercontent.com/assets/7044329/16337808/33be0178-39e6-11e6-8b44-a6e2033f659b.JPG)

**Comment by terox** [comment]
@whtouche check that stats.json are well-generated. If is an invalid file, it wont work.

**Comment by ctaepper** [comment]
@whtouche it will only work if your webpack config exports one single config object. if you are exporting an array of multiple configs, the analyse tool won't work

**Comment by amcdnl** [comment]
50K LOC in our app ( swimlane.com )
![graph thingy](http://content.screencast.com/users/amcdaniel22/folders/Snagit/media/3a777c1f-46c5-40c5-86cc-baf99d97d3a6/2016-08-04_09-31-36.png)

**Comment by imvetri** [comment]
I am imagining the same visualization from a VR. Wherein user can shrink the and expand the dots using hand gestures. Just like tony stark in Iron man movie.

**Comment by amcdnl** [comment]
@imvetri our app has a threejs graph viz in it that works on cardboard, need to make format consume this but yet i will demo it soon :)

**Comment by gaearon** [comment]
FYI @alexkuz wrote a beautiful 3D visualization for `stats.json`, check it out:
https://alexkuz.github.io/stellar-webpack/

**Comment by sunasra** [comment]
@sokra is possible to download table content as csv/excel. This will help to sort largest component

**Comment by imvetri** [comment]
@gaearon Thanks for sharing. @alexkuz  Its spectacular.

**Comment by alexkuz** [comment]
@imvetri Thank you! :)

**Comment by adampietrasiak** [comment]
@gaearon seems its not working anymore. JS is throwing 500 errors per sec.

**Comment by ccorcos** [comment]
@sokra all I'm seeing is the webpack test cases...

![image](https://cloud.githubusercontent.com/assets/1794527/18853452/16452b90-83fa-11e6-9026-c79ee6b27017.png)

how do I see the graph for my code?

**Comment by ccorcos** [comment]
lol. I forgot to stringify:

```js
fs.writeFileSync(filename, stats.toJson('verbose'))
```

So I just got this webpack test case graph back. Thats a little confusing. This worked though :)

```js
fs.writeFileSync(filename, JSON.stringify(stats.toJson('verbose')))
```

**Comment by sasha240100** [comment]
WhitestormJS: https://github.com/WhitestormJS/whitestorm.js

![image](https://cloud.githubusercontent.com/assets/7657429/22306309/715a7574-e347-11e6-8326-ffe704349cec.png)

**Comment by ghotiphud** [comment]
I was playing with this, and wondering if I could do a bit more with it, so built this [converter from stats.json to GDF](https://github.com/ghotiphud/stats_to_gdf) so I could open it in [Gephi](https://gephi.org/).  It'll allow you to delete nodes you don't care about, etc. so you can look at things in more detail.  Currently doesn't export that much information, but open to suggestions on further things to export.  Fun to play with either way :-)

**Comment by KyleAMathews** [comment]
@ghotiphud would be fun to see a screenshot!

**Comment by ghotiphud** [comment]
Alright, wanted to make something prettier before I commented...

Modules colored by chunks, and sized according to module size.
![modules](https://cloud.githubusercontent.com/assets/412313/23484151/cc2224f8-fea3-11e6-8455-2a9f17ded51c.png)

Filtering the modules down to only those in the common chunk.
![common_chunk](https://cloud.githubusercontent.com/assets/412313/23484155/d1ae9046-fea3-11e6-98cc-618463e67744.png)

I can see from these that we have a few rather large dependencies (jquery is one) and that the common bundle has a larger one that's kind of loosely connected and can potentially be removed from page load a majority of the time...  🙌

Different arrangement...
![modules_openord](https://cloud.githubusercontent.com/assets/412313/23484622/bdbd5e80-fea5-11e6-9c3e-5202e51587c1.png)

**Comment by spalger** [comment]
https://github.com/elastic/kibana

webpack 1.12.15
34045 ms
3475 modules
11 chunks
80 assets

![image](https://cloud.githubusercontent.com/assets/1329312/25550430/b9f322ac-2c2d-11e7-9ce4-1b088146e1e3.png)

**Comment by dickeylth** [comment]
I'm wondering if the <http://webpack.github.io/analyse> site could be open sourced or if there's already such tools works like [source-map-explorer](https://www.npmjs.com/package/source-map-explorer), so that I could deploy such a service in my own server, feed it the `stats.json` file path on my server and display every project's dependency graph.

**Comment by light24bulbs** [comment]
I hit "choose file" and it selects, but then nothing happens.  I don't get a next button or any progress.  My stats file is around 12mb.  Is this tool still working?

**Comment by bfkeinberg** [comment]
<img width="557" alt="screen shot 2018-03-03 at 7 26 32 pm" src="https://user-images.githubusercontent.com/9753972/36941816-d6178a34-1f18-11e8-9181-6685eba4bf3b.png">

**Comment by Frozzy6** [comment]
I've got "Cannot read property 'parents' of undefined" error in console

**Comment by sseppola** [comment]
I'm having a lot of trouble getting https://webpack.github.io/analyse/ to analyze my stats.json file.
I keep getting this error:
![screen shot 2018-10-23 at 16 25 20](https://user-images.githubusercontent.com/4065840/47369704-8e1db800-d6e4-11e8-848e-1d26609925d0.png)

Considering the comment above, I have to ask wether this tool is updated?
Otherwise, I may of course be wrong. Here's what I do in my build.js script (webpack 3.8.1):
```
let compiler = webpack({ ...config, stats: 'verbose' });
  return new Promise((resolve, reject) => {
    compiler.run((err, stats) => {
      if (err) {
        return reject(err);
      }
      fs.writeFileSync(
        './stats.json',
        JSON.stringify(stats.toJson('verbose'), null, 2)
      );
      ...
```

**Comment by errorx666** [comment]
Is there a way to produce this graph as a build artifact, a la [webpack-bundle-analyzer](/webpack-contrib/webpack-bundle-analyzer)?

**Comment by Richard-Choooou** [comment]
> I'm having a lot of trouble getting https://webpack.github.io/analyse/ to analyze my stats.json file.
> I keep getting this error:
> ![screen shot 2018-10-23 at 16 25 20](https://user-images.githubusercontent.com/4065840/47369704-8e1db800-d6e4-11e8-848e-1d26609925d0.png)
> 
> Considering the comment above, I have to ask wether this tool is updated?
> Otherwise, I may of course be wrong. Here's what I do in my build.js script (webpack 3.8.1):
> 
> ```
> let compiler = webpack({ ...config, stats: 'verbose' });
>   return new Promise((resolve, reject) => {
>     compiler.run((err, stats) => {
>       if (err) {
>         return reject(err);
>       }
>       fs.writeFileSync(
>         './stats.json',
>         JSON.stringify(stats.toJson('verbose'), null, 2)
>       );
>       ...
> ```

I have this problem too

**Comment by TehcJS** [comment]
Often, many things in Javascript are deprecated, changed, or even removed. This may be the case here, as the analyzer probably hasn't been updated in quite some time; I could be wrong.

**Comment by kriskate** [comment]
no other fun dependency viewers (eg https://alexkuz.github.io/stellar-webpack/) work with the new webpack stats, unfortunatelly

**Comment by evilebottnawi** [comment]
Let's close, no many activity
