### ISSUE TITLE
webpack watcher compiles EVERY file and not just the changed one.

### ISSUE THREAD

**Issue by kobelobster** [webpack/webpack#6901]
**Do you want to request a *feature* or report a *bug*?**
Maybe I'm misunderstanding the doucemtation/watcher, but otherwise this is a bug. However, it's such a fundamental piece of webpack, if it would be a bug, someone else probably already reported it?

**What is the current behavior?**
`webpack` watcher compiles EVERY file and not just the changed one.

Steps to reproduce:
These steps assume you already have `yarn/npm` installed.
* Check out the repository I created which you can find at https://github.com/tzfrs/webpack-watch-bug
* Initially run `yarn install` or `npm install`.
* Run `./node_modules/.bin/webpack`. This should create two files in the `dist` folder and automatically watch.
* Delete `dist/second.js`
* Change something in `src/first.js`
* `src/second.js` has no changes, but will still be recompiled (because `dist/second.js` is created again).
* Also, the log states something along the lines

```
Hash: d13339396526426e402d
Version: webpack 4.3.0
Time: 304ms
Built at: 3/29/2018 12:11:20 PM
    Asset       Size  Chunks             Chunk Names
second.js  545 bytes       0  [emitted]  second
 first.js  561 bytes       1  [emitted]  first
Entrypoint first = first.js
Entrypoint second = second.js
   [0] ./src/second.js 0 bytes {0} [built]
   [1] ./src/first.js 17 bytes {1} [built]

```

As you can see. `second.js` is also in the log.

**What is the expected behavior?**
Only changed files should be recompiled. I assume that this is the expected behavior, because [the documentation for Watch](https://webpack.js.org/configuration/watch/) states:

> webpack can watch files and recompile whenever they change.

**Comment by jameskerr** [comment]
This has been a problem for me as well.

**Comment by s-panferov** [comment]
This happened for me too before and then I tried to disable HardSource cache plugin. Everything started to work just fine.

**Comment by tzfrs** [comment]
Hey guys, quick update on this. I don't think this is a "bug" just a misunderstanding from our site. I posted the same question on stackoverflow and got the following response

> Webpack and similar watchers hold your entire bundle in memory, and watch a file stream. You can think of it kinda like an asynchronous reduce. Each time data is pushed to the stream, it updates the accumulated bundle accordingly, until the stream closes and the task ends.

> If it has an out directory, it writes the latest state of the bundle -- that is, the entire bundle -- to that directory on each change. But even though we think of this as the primary goal, it's more like a "side effect" if we go with the reduce analogy.

> This does not mean that it recompiled everything...in fact, unexpected changes like an unsafe deletion can actually break the watcher, precisely because it's not starting from scratch every time something changes.

> For a demonstration, clone a larger project and notice the difference between the first compile (whole bundle) and subsequent (single file) updates. There should be an order of magnitude difference in time taken.

Link to the answer: https://stackoverflow.com/a/50641766/2823419

---------

However, would be cool if some team member of could confirm this?

**Comment by alexander-akait** [comment]
Yes, answer right https://stackoverflow.com/questions/49553082/webpack-watch-compiles-every-file/50641766#50641766, just test it, feel free to feedback

**Comment by CalculonPrime** [comment]
> Just to note, using `--mode=development` will give the desired behavior you are describing (unless I am missing something).

But then all the other development-mode-specific behavior kicks in.  What would be the way to apply only the change that fixes this from development mode, without getting any other development mode settings?

> Hey guys, quick update on this. I don't think this is a "bug" just a misunderstanding from our side. I posted the same question on stackoverflow and got the following response
> 
> Link to the answer: https://stackoverflow.com/a/50641766/2823419

From what I'm seeing right now, the claim in that answer that subsequent changes will be faster is wrong.  Not only are all the source files recompiled in production mode, it takes 23 seconds in my specific case, as long as a fresh production build from scratch.  If I change to development mode, then it takes 1-2 seconds for a single file change to finish, and only the .js file for the changed .jsx source is updated (plus all the .html files for some reason).
