### ISSUE TITLE
Run selectively test cases

### ISSUE THREAD

**Issue by jeremenichelli** [webpack/webpack#6903]
**Do you want to request a *feature* or report a *bug*?**

*feature*

**What is the current behavior?**

When someone wants to contribute with a small change and run tests, the developer needs to wait for all the tests (which are a lot) to run.

**If the current behavior is a bug, please provide the steps to reproduce.**

--

**What is the expected behavior?**

I can indicate in the command which test to run like:

```
yarn test ./test/someTest.js
```

or:

```
yarn test --testCase="./test/someTest.js"
```

React does something similar in its packages: https://reactjs.org/docs/how-to-contribute.html#development-workflow

If also performance can be improved to make tests run faster, double win.

**If this is a feature request, what is motivation or use case for changing the behavior?**

This will remove a lot of friction to contributing, I've recently submitted a PR with an improvement on warning messages and had to run the entire test suite because I was changing the lines and content of a string.

**Comment by montogeek** [comment]
Meanwhile you can tweak https://github.com/webpack/webpack/blob/master/test/ConfigTestCases.test.js#L29 to only run test that have a special character, I had to do the same time ago

**Comment by montogeek** [comment]
Screenshot from that branch:
![image](https://user-images.githubusercontent.com/1002461/38086829-2a43025e-3356-11e8-91c7-8dbe826785b8.png)

**Comment by Janpot** [comment]
Actually, when I initially made the comment about selectively running tests in https://github.com/webpack/webpack/issues/6893 I had more something like `it.only` in mind. Right now that's clashing a bit with the way nested tests are set up.

**Comment by ooflorent** [comment]
Here is how I usually work around this:

- prefix my test case folder with `_`
- use `--grep` flag 
- use `--bail` flag

I admit this is not ideal but it is possible to test your changes easily. Once the tests are fine, I ran the full suite while preparing the PR.

**Comment by Janpot** [comment]
@ooflorent Maybe there could be a note about this technique in the `CONTRIBUTING.md` as part of https://github.com/webpack/webpack/issues/6893 ?

**Comment by montogeek** [comment]
@Janpot It won't hurt but I find it unnecessary, if you read Mocha docs would find about it

**Comment by Janpot** [comment]
@montogeek [Mocha docs](https://mochajs.org/#exclusive-tests) will tell you to use `.only`, which doesn't work in this case because these tests are set up dynamically. `--grep` seems more of a workaround to me, and quite frankly, even knowing mocha very well and its functionalities, it didn't occur to me naturally to use it this way. You know ultimately, #6893 is trying, to shorten the time from going from zero to the first contribution. I'm just communicating what made me lose most of my time yesterday, trying to make that transition. Because for me it was not at all what's being proposed in that PR.
Anyway, how would you propose that workflow to be after https://github.com/webpack/webpack/pull/6565 ?

**Comment by montogeek** [comment]
@Janpot Yes, I was talking about @ooflorent approach.
#6893 Will alleviate that other issue.
Check Jest docs, you can see from my [screenshot](https://github.com/webpack/webpack/issues/6903#issuecomment-377207931) that I am using `--t` to run tests selectively

**Comment by jeremenichelli** [comment]
More than increasing the complexity of the contributing process with hacks-like instructions on the CONTRIBUTING.md file I prefer for us to think about improvements or refactors if they are necessary :)

**Comment by Janpot** [comment]
@montogeek But I'm not really interested in only running one config like `TestCasesMinimizedHashedModules.test.js` for all test folders. I'm rather interested in running all configs for one test folder.

**Comment by sokra** [comment]
I usually use i. e. `mocha -g "normal.+namespace-object-lazy`

**Comment by jeremenichelli** [comment]
@sokra -g flag is like a grep provided by mocha? Because we could just add a script and use yarn to deeply pass the argument to mocha bin, easy to document also.

**Comment by sokra** [comment]
Doesn't `yarn test -g "..."` work?

**Comment by jeremenichelli** [comment]
It might, I'll give it a try over the weekend and see if there's something needed on the infrastructure or documentation to help with this.
