### ISSUE TITLE
WebWorker auto splitting like import()

### ISSUE THREAD

**Issue by dyst5422** [webpack/webpack#6908]
**Do you want to request a *feature* or report a *bug*?**

Feature:

Auto split out webworker files by reading and using the `const worker = new Worker(filepath)` syntax in much the same way that dynamic imports are automatically split

**What is the current behavior?**
WebWorkers currently need their own loader which essentially just splits out the file. This requires a nonstandard syntax of 
```ts
const Worker = require(`worker_loader!filename`);
const worker = new Worker();
```
or
```ts
const Worker = require(`filename.worker`);
const worker = new Worker();
```

and having another loader for workers

**What is the expected behavior?**

I should be able to have the line `const worker = new Worker(filename);` in my code and have webpack automatically code split it like `import()` does;

**If this is a feature request, what is motivation or use case for changing the behavior?**

Simplifying the use of web workers and avoid changing the syntax based on using webpack to bundle.

**Please mention other relevant information such as the browser version, Node.js version, webpack version, and Operating System.**

webpack 4

**Comment by sokra** [comment]
Good idea.

**Comment by kesne** [comment]
The same can apply to `SharedWorker` as well.

**Comment by dyst5422** [comment]
Seems like there is a quorum of support.

**Comment by phil-lgr** [comment]
https://github.com/developit/workerize-loader works pretty well except that (and it's a pain) it uses .createChildCompilation soooo it creates an entry that is not aware of the main compilation.

I have to support IE11, so my workers needs Promise, I have Promise included in my polyfills chunk (as DLLs) but the child compilation does not see it.

The ability to output something like a worker-as-a-chunk would be 🔥

**Comment by mixtur** [comment]
Is anyone working towards this feature?

**Comment by buoyantair** [comment]
I used multiple entries to specify my app and service worker files but yeah I guess this would be nice :D

**Comment by kesne** [comment]
There's a plugin that handles this: https://github.com/GoogleChromeLabs/worker-plugin

**Comment by dyst5422** [comment]
@kesne Huzzah! This definitely didn't exist when I originally opened this issue.

Seems like we can probably close this issue.

**Comment by evilebottnawi** [comment]
Feel free to send a PR :+1:

**Comment by evilebottnawi** [comment]
bump

**Comment by sokra** [comment]
This has been implemented: `const worker = new Worker(new URL(filepath, import.meta.url))`
