### ISSUE TITLE
chrome-trace-event

### ISSUE THREAD

**Issue by mlucool** [webpack/webpack#6909]
**What is the current behavior?**
[chrome-trace-event](https://www.npmjs.com/package/chrome-trace-event) is a dependency

**If the current behavior is a bug, please provide the steps to reproduce.**
[This commit](https://github.com/webpack/webpack/commit/d235a6141229d84970ae74a796f9d62dc78c46ed) added this dependency (PR: https://github.com/webpack/webpack/pull/6322)

**What is the expected behavior?**
chrome-trace-event [package.json](http://registry.npmjs.org/chrome-trace-event/latest) points (poorly in that npm cannot parse it) to [this repo](https://github.com/samccone/chrome-trace-event) which is a fork of [node-trace-event](https://github.com/joyent/node-trace-event).  I am do not believe this is a good choice because that repo has no issue tracker and webpack is the only thing that depends on it (per npm's dependents). 

Should webpack should move it into the namespace and maintain it or possibly into the repo itself (only 175 LOC)? All other dependencies appear to be highly used by other libraries as well, so this stands out. If there is a strong reason to keep it as it is, @samccone can you please open the issue tracker and possibly add a collaborator in case this project needs to make changes?

cc @TheLarkInn @samccone

**Comment by evilebottnawi** [comment]
@samccone looks like all done and we can close issue

**Comment by evilebottnawi** [comment]
Feel free to feedback. Thanks!
