### ISSUE TITLE
I need help to improve my nunjucks-loader

### ISSUE THREAD

**Issue by dschissler** [webpack/webpack#691]
I created nunjucks-loader for Nunjucks templates.

* [github](https://github.com/perchlayer/nunjucks-loader)
* [npm](https://www.npmjs.com/package/nunjucks-loader)

I'll say that it took me a while to figure out how to do this and I'm a bit lost now.  I'm thinking that I could dig through the handlebars-loader code to find how to improve this.  Basically it doesn't do anything very special and it doesn't know how to do much.  It does appear though that helpers can work since they can be defined in your module code.  I am just putting it into a template module that sets everything up and then I'm calling it from a factory.

Is anyone with understanding interested in this?  I can do the work but I need some guidance.

**Comment by dschissler** [comment]
[nunjucksify](https://github.com/rotundasoftware/nunjucksify/blob/master/index.js) apparently has done it already.  I can't make much sense of it though.

**Comment by gaearon** [comment]
I'm a bit confused as `index.js` appears to be end abruptly.
Do you have any specific questions?

**Comment by bebraw** [comment]
@dschissler I can't see your loader anymore. Safe to close?
