### ISSUE TITLE
Today webpack version 4.4.1. Where can I read the documentation?

### ISSUE THREAD

**Issue by antonreshetov** [webpack/webpack#6911]
Today webpack version 4.4.1. Where can I read the documentation?

**Comment by TheLarkInn** [comment]
Hi @antonreshetov!!! Thanks for reaching out. For all immediate releases please look to https://github.com/webpack/webpack/releases for the changelog. 

From there I would even ask a great opportunity for you to contribute these updates to [our docs repo](https://github.com/webpack/webpack.js.org) as a first great contribution issue and PR!
