### ISSUE TITLE
The document is outdated ？

### ISSUE THREAD

**Issue by vipcxj** [webpack/webpack#6912]
webpack 4 removes the CommonsChunkPlugin in favor of two new options (optimization.splitChunks and optimization.runtimeChunk).  However, in the [offical document page](https://webpack.js.org/plugins/), the CommonsChunkPlugin is still here, and no splitChunks and runtimeChunk found.

**Comment by huzedong2015** [comment]
+1

**Comment by ooflorent** [comment]
The documentation is outdated. We are doing our best to update it. You could track our progress in the [webpack/webpack.js.org](https://github.com/webpack/webpack.js.org) repository.

**Comment by rico345100** [comment]
Upgrade document please. I'm stuck in Code splitting section.
